MercuryDPM: ChangingTOIParticle Class Reference
ChangingTOIParticle Class Reference
Public Member Functions
MatrixSymmetric3D MtoS (Matrix3D M)
Matrix3D StoM (MatrixSymmetric3D M)
Matrix3D transpose (Matrix3D M)
ChangingTOIParticle ()
void setClumpDamping (Mdouble damp)
void setClumpIndex (Mdouble index)
Mdouble getClumpMass ()
void setupInitialConditions () override
This function allows to set the initial conditions for our problem to be solved, by default particle locations are randomly set. Remember particle properties must also be defined here.
void actionsAfterTimeStep () override
A virtual function which allows to define operations to be executed after time step.
ChangingTOIParticle ()
void setClumpDamping (Mdouble damp)
void setClumpIndex (Mdouble index)
Mdouble getClumpMass ()
void setupInitialConditions () override
This function allows to set the initial conditions for our problem to be solved, by default particle locations are randomly set. Remember particle properties must also be defined here.
void actionsAfterTimeStep () override
A virtual function which allows to define operations to be executed after time step.
ChangingTOIParticle ()
void setClumpDamping (Mdouble damp)
void setClumpIndex (Mdouble index)
Mdouble getClumpMass ()
void setupInitialConditions () override
This function allows to set the initial conditions for our problem to be solved, by default particle locations are randomly set. Remember particle properties must also be defined here.
void actionsAfterTimeStep () override
A virtual function which allows to define operations to be executed after time step.
ChangingTOIParticle ()
void setClumpDamping (Mdouble damp)
void setClumpIndex (Mdouble index)
Mdouble getClumpMass ()
void setupInitialConditions () override
This function allows to set the initial conditions for our problem to be solved, by default particle locations are randomly set. Remember particle properties must also be defined here.
void actionsAfterTimeStep () override
A virtual function which allows to define operations to be executed after time step.
ChangingTOIParticle ()
void setClumpDamping (Mdouble damp)
void setClumpIndex (Mdouble index)
Mdouble getClumpMass ()
void setupInitialConditions () override
This function allows to set the initial conditions for our problem to be solved, by default particle locations are randomly set. Remember particle properties must also be defined here.
void actionsAfterTimeStep () override
A virtual function which allows to define operations to be executed after time step.
ChangingTOIParticle ()
void setClumpDamping (Mdouble damp)
void setClumpIndex (Mdouble index)
Mdouble getClumpMass ()
void setupInitialConditions () override
This function allows to set the initial conditions for our problem to be solved, by default particle locations are randomly set. Remember particle properties must also be defined here.
ChangingTOIParticle ()
void setClumpDamping (Mdouble damp)
void setClumpIndex (Mdouble index)
Mdouble getClumpMass ()
void setupInitialConditions () override
This function allows to set the initial conditions for our problem to be solved, by default particle locations are randomly set. Remember particle properties must also be defined here.
ChangingTOIParticle ()
void setClumpDamping (Mdouble damp)
void setClumpIndex (Mdouble index)
Mdouble getClumpMass ()
void setupInitialConditions () override
This function allows to set the initial conditions for our problem to be solved, by default particle locations are randomly set. Remember particle properties must also be defined here.
void actionsAfterTimeStep () override
A virtual function which allows to define operations to be executed after time step.
Public Member Functions inherited from Mercury3Dclump
Mercury3Dclump ()
void computeInternalForce (BaseParticle *P1, BaseParticle *P2) override
void computeForcesDueToWalls (BaseParticle *pI, BaseWall *w) override
void computeAllForces () override
bool checkClumpForInteraction (BaseParticle &particle)
bool checkClumpForInteractionPeriodic (BaseParticle &particle)
Public Member Functions inherited from Mercury3D
Mercury3D ()
This is the default constructor. All it does is set sensible defaults.
Mercury3D (const DPMBase &other)
Copy-constructor for creates an Mercury3D problem from an existing MD problem.
Mercury3D (const Mercury3D &other)
Copy-constructor.
void constructor ()
Function that sets the SystemDimension and ParticleDimension to 3.
std::vector< BaseParticle * > hGridFindParticleContacts (const BaseParticle *obj) override
Returns all particles that have a contact with a given particle.
Public Member Functions inherited from MercuryBase
MercuryBase ()
This is the default constructor. It sets sensible defaults.
~MercuryBase () override
This is the default destructor.
MercuryBase (const MercuryBase &mercuryBase)
Copy-constructor.
void constructor ()
This is the actual constructor, it is called do both constructors above.
void hGridActionsBeforeTimeLoop () override
This sets up the broad phase information, has to be done at this stage because it requires the particle size.
void hGridActionsBeforeTimeStep () override
Performs all necessary actions before a time-step, like updating the particles and resetting all the bucket information, etc.
void read (std::istream &is, ReadOptions opt=ReadOptions::ReadAll) override
Reads the MercuryBase from an input stream, for example a restart file.
void write (std::ostream &os, bool writeAllParticles=true) const override
Writes all data into a restart file.
Mdouble getHGridCurrentMaxRelativeDisplacement () const
Returns hGridCurrentMaxRelativeDisplacement_.
Mdouble getHGridTotalCurrentMaxRelativeDisplacement () const
Returns hGridTotalCurrentMaxRelativeDisplacement_.
void setHGridUpdateEachTimeStep (bool updateEachTimeStep)
Sets whether or not the HGrid must be updated every time step.
bool getHGridUpdateEachTimeStep () const final
Gets whether or not the HGrid is updated every time step.
void setHGridMaxLevels (unsigned int HGridMaxLevels)
Sets the maximum number of levels of the HGrid in this MercuryBase.
unsigned int getHGridMaxLevels () const
Gets the maximum number of levels of the HGrid in this MercuryBase.
HGridMethod getHGridMethod () const
Gets whether the HGrid in this MercuryBase is BOTTOMUP or TOPDOWN.
void setHGridMethod (HGridMethod hGridMethod)
Sets the HGridMethod to either BOTTOMUP or TOPDOWN.
HGridDistribution getHGridDistribution () const
Gets how the sizes of the cells of different levels are distributed.
void setHGridDistribution (HGridDistribution hGridDistribution)
Sets how the sizes of the cells of different levels are distributed.
Mdouble getHGridCellOverSizeRatio () const
Gets the ratio of the smallest cell over the smallest particle.
void setHGridCellOverSizeRatio (Mdouble cellOverSizeRatio)
Sets the ratio of the smallest cell over the smallest particle.
bool hGridNeedsRebuilding ()
Gets if the HGrid needs rebuilding before anything else happens.
virtual unsigned int getHGridTargetNumberOfBuckets () const
Gets the desired number of buckets, which is the maximum of the number of particles and 10.
virtual Mdouble getHGridTargetMinInteractionRadius () const
Gets the desired size of the smallest cells of the HGrid.
virtual Mdouble getHGridTargetMaxInteractionRadius () const
Gets the desired size of the largest cells of the HGrid.
bool checkParticleForInteraction (const BaseParticle &P) final
Checks if given BaseParticle has an interaction with a BaseWall or other BaseParticle.
bool checkParticleForInteractionLocal (const BaseParticle &P) final
Checks if the given BaseParticle has an interaction with a BaseWall or other BaseParticles in a local domain.
virtual Mdouble userHGridCellSize (unsigned int level)
Virtual function that enables inheriting classes to implement a function to let the user set the cell size of the HGrid.
void hGridInfo (std::ostream &os=std::cout) const
Writes the info of the HGrid to the screen in a nice format.
Public Member Functions inherited from DPMBase
void constructor ()
A function which initialises the member variables to default values, so that the problem can be solved off the shelf; sets up a basic two dimensional problem which can be solved off the shelf. It is called in the constructor DPMBase().
DPMBase ()
Constructor that calls the "void constructor()".
DPMBase (const DPMBase &other)
Copy constructor type-2.
virtual ~DPMBase ()
virtual destructor
void autoNumber ()
The autoNumber() function calls three functions: setRunNumber(), readRunNumberFromFile() and incrementRunNumberInFile().
std::vector< int > get1DParametersFromRunNumber (int size_x) const
This turns a counter into 1 index, which is a useful feature for performing 1D parameter study. The index run from 1:size_x, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
std::vector< int > get2DParametersFromRunNumber (int size_x, int size_y) const
This turns a counter into 2 indices which is a very useful feature for performing a 2D study. The indices run from 1:size_x and 1:size_y, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
std::vector< int > get3DParametersFromRunNumber (int size_x, int size_y, int size_z) const
This turns a counter into 3 indices, which is a useful feature for performing a 3D parameter study. The indices run from 1:size_x, 1:size_y and 1:size_z, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
int launchNewRun (const char *name, bool quick=false)
This launches a code from within this code. Please pass the name of the code to run.
void setRunNumber (int runNumber)
This sets the counter/Run number, overriding the defaults.
int getRunNumber () const
This returns the current value of the counter (runNumber_)
virtual void decompose ()
Sends particles from processorId to the root processor.
void solve ()
The work horse of the code.
void initialiseSolve ()
Beginning of the solve routine, before time stepping.
void finaliseSolve ()
End of the solve routine, after time stepping.
virtual void computeOneTimeStep ()
Performs everything needed for one time step, used in the time-loop of solve().
void checkSettings ()
Checks if the essentials are set properly to go ahead with solving the problem.
void forceWriteOutputFiles ()
Writes output files immediately, even if the current time step was not meant to be written. Also resets the last saved time step.
virtual void writeOutputFiles ()
Writes simulation data to all the main Mercury files: .data, .ene, .fstat, .xballs and .restart (see the Mercury website for more details regarding these files).
void solve (int argc, char *argv[])
The work horse of the code. Can handle flags from the command line.
virtual void writeXBallsScript () const
This writes a script which can be used to load the xballs problem to display the data just generated.
virtual Mdouble getInfo (const BaseParticle &P) const
A virtual function that returns some user-specified information about a particle.
ParticleVtkWriter * getVtkWriter () const
virtual void writeRestartFile ()
Stores all the particle data for current save time step to a "restart" file, which is a file simply intended to store all the information necessary to "restart" a simulation from a given time step (see also MercuryDPM.org for more information on restart files).
void writeDataFile ()
void writeEneFile ()
void writeFStatFile ()
void fillDomainWithParticles (unsigned N=50)
bool readRestartFile (ReadOptions opt=ReadOptions::ReadAll)
Reads all the particle data corresponding to a given, existing . restart file (for more details regarding restart files, refer to the training materials on the MercuryDPM website).Returns true if it is successful, false otherwise.
int readRestartFile (std::string fileName, ReadOptions opt=ReadOptions::ReadAll)
The same as readRestartFile(bool), but also reads all the particle data corresponding to the current saved time step.
virtual BaseWall * readUserDefinedWall (const std::string &type) const
Allows you to read in a wall defined in a Driver directory; see USER/Luca/ScrewFiller.
virtual void readOld (std::istream &is)
Reads all data from a restart file, e.g. domain data and particle data; old version.
bool readDataFile (std::string fileName="", unsigned int format=0)
This allows particle data to be reloaded from data files.
bool readParAndIniFiles (std::string fileName)
Allows the user to read par.ini files (useful to read files produced by the MDCLR simulation code - external to MercuryDPM)
bool readNextDataFile (unsigned int format=0)
Reads the next data file with default format=0. However, one can modify the format based on whether the particle data corresponds to 3D or 2D data- see Visualising data in xballs.
void readNextFStatFile ()
Reads the next fstat file.
bool findNextExistingDataFile (Mdouble tMin, bool verbose=true)
Finds and opens the next data file, if such a file exists.
bool readArguments (int argc, char *argv[])
Can interpret main function input arguments that are passed by the driver codes.
bool checkParticleForInteractionLocalPeriodic (const BaseParticle &P)
void readSpeciesFromDataFile (bool read=true)
void importParticlesAs (ParticleHandler &particleHandler, InteractionHandler &interactionHandler, const ParticleSpecies *species)
Copies particles, interactions assigning species from a local simulation to a global one. Useful for the creation of a cluster.
MERCURYDPM_DEPRECATED File & getDataFile ()
The non const version. Allows one to edit the File::dataFile.
MERCURYDPM_DEPRECATED File & getEneFile ()
The non const version. Allows to edit the File::eneFile.
MERCURYDPM_DEPRECATED File & getFStatFile ()
The non const version. Allows to edit the File::fStatFile.
MERCURYDPM_DEPRECATED File & getRestartFile ()
The non const version. Allows to edit the File::restartFile.
MERCURYDPM_DEPRECATED File & getStatFile ()
The non const version. Allows to edit the File::statFile.
File & getInteractionFile ()
Return a reference to the file InteractionsFile.
MERCURYDPM_DEPRECATED const File & getDataFile () const
The const version. Does not allow for any editing of the File::dataFile.
MERCURYDPM_DEPRECATED const File & getEneFile () const
The const version. Does not allow for any editing of the File::eneFile.
MERCURYDPM_DEPRECATED const File & getFStatFile () const
The const version. Does not allow for any editing of the File::fStatFile.
MERCURYDPM_DEPRECATED const File & getRestartFile () const
The const version. Does not allow for any editing of the File::restartFile.
MERCURYDPM_DEPRECATED const File & getStatFile () const
The const version. Does not allow for any editing of the File::statFile.
const File & getInteractionFile () const
Returns a constant reference to an Interactions file.
const std::string & getName () const
Returns the name of the file. Does not allow to change it though.
void setName (const std::string &name)
Allows to set the name of all the files (ene, data, fstat, restart, stat)
void setName (const char *name)
Calls setName(std::string)
void setSaveCount (unsigned int saveCount)
Sets File::saveCount_ for all files (ene, data, fstat, restart, stat)
void setFileType (FileType fileType)
Sets File::fileType_ for all files (ene, data, fstat, restart, stat)
void setOpenMode (std::fstream::openmode openMode)
Sets File::openMode_ for all files (ene, data, fstat, restart, stat)
void resetFileCounter ()
Resets the file counter for each file i.e. for ene, data, fstat, restart, stat)
void closeFiles ()
Closes all files (ene, data, fstat, restart, stat) that were opened to read or write.
void setVTKOutputDirectory (const std::string &dir)
Sets the output directory of the VTK files.
void setLastSavedTimeStep (unsigned int nextSavedTimeStep)
Sets the next time step for all the files (ene, data, fstat, restart, stat) at which the data is to be written or saved.
Mdouble getTime () const
Returns the current simulation time.
Mdouble getNextTime () const
Returns the current simulation time.
unsigned int getNumberOfTimeSteps () const
Returns the current counter of time-steps, i.e. the number of time-steps that the simulation has undergone so far.
void setTime (Mdouble time)
Sets a new value for the current simulation time.
void setTimeMax (Mdouble newTMax)
Sets a new value for the maximum simulation duration.
Mdouble getTimeMax () const
Returns the maximum simulation duration.
void setLogarithmicSaveCount (Mdouble logarithmicSaveCountBase)
Sets File::logarithmicSaveCount_ for all files (ene, data, fstat, restart, stat)
void setNToWrite (int nToWrite)
set the number of elements to write to the screen
int getNToWrite () const
get the number of elements to write to the
void setRotation (bool rotation)
Sets whether particle rotation is enabled or disabled.
bool getRotation () const
Indicates whether particle rotation is enabled or disabled.
MERCURYDPM_DEPRECATED void setWallsWriteVTK (FileType writeWallsVTK)
Sets whether walls are written into a VTK file.
MERCURYDPM_DEPRECATED void setWallsWriteVTK (bool)
Sets whether walls are written into a VTK file.
MERCURYDPM_DEPRECATED void setInteractionsWriteVTK (bool)
Sets whether interactions are written into a VTK file.
void setParticlesWriteVTK (bool writeParticlesVTK)
Sets whether particles are written in a VTK file.
void setSuperquadricParticlesWriteVTK (bool writeSuperquadricParticlesVTK)
MERCURYDPM_DEPRECATED FileType getWallsWriteVTK () const
Returns whether walls are written in a VTK file.
bool getParticlesWriteVTK () const
Returns whether particles are written in a VTK file.
bool getSuperquadricParticlesWriteVTK () const
Mdouble getXMin () const
If the length of the problem domain in x-direction is XMax - XMin, then getXMin() returns XMin.
Mdouble getXMax () const
If the length of the problem domain in x-direction is XMax - XMin, then getXMax() returns XMax.
Mdouble getYMin () const
If the length of the problem domain in y-direction is YMax - YMin, then getYMin() returns YMin.
Mdouble getYMax () const
If the length of the problem domain in y-direction is YMax - YMin, then getYMax() returns XMax.
Mdouble getZMin () const
If the length of the problem domain in z-direction is ZMax - ZMin, then getZMin() returns ZMin.
Mdouble getZMax () const
If the length of the problem domain in z-direction is ZMax - ZMin, then getZMax() returns ZMax.
Mdouble getXCenter () const
Mdouble getYCenter () const
Mdouble getZCenter () const
Vec3D getCenter () const
get center of domain
Vec3D getMin () const
Returns the minimum coordinates of the problem domain.
Vec3D getMax () const
Returns the maximum coordinates of the problem domain.
void setXMin (Mdouble newXMin)
Sets the value of XMin, the lower bound of the problem domain in the x-direction.
void setYMin (Mdouble newYMin)
Sets the value of YMin, the lower bound of the problem domain in the y-direction.
void setZMin (Mdouble newZMin)
Sets the value of ZMin, the lower bound of the problem domain in the z-direction.
void setXMax (Mdouble newXMax)
Sets the value of XMax, the upper bound of the problem domain in the x-direction.
void setYMax (Mdouble newYMax)
Sets the value of YMax, the upper bound of the problem domain in the y-direction.
void setZMax (Mdouble newZMax)
Sets the value of ZMax, the upper bound of the problem domain in the z-direction.
void setMax (const Vec3D &max)
Sets the maximum coordinates of the problem domain.
void setMax (Mdouble, Mdouble, Mdouble)
Sets the maximum coordinates of the problem domain.
void setDomain (const Vec3D &min, const Vec3D &max)
Sets the minimum coordinates of the problem domain.
void setMin (const Vec3D &min)
Sets the minimum coordinates of the problem domain.
void setMin (Mdouble, Mdouble, Mdouble)
Sets the minimum coordinates of the problem domain.
void setTimeStep (Mdouble newDt)
Sets a new value for the simulation time step.
Mdouble getTimeStep () const
Returns the simulation time step.
void setNumberOfOMPThreads (int numberOfOMPThreads)
Sets the number of omp threads.
int getNumberOfOMPThreads () const
Returns the number of omp threads.
void setXBallsColourMode (int newCMode)
Set the xballs output mode.
int getXBallsColourMode () const
Get the xballs colour mode (CMode).
void setXBallsVectorScale (double newVScale)
Set the scale of vectors in xballs.
double getXBallsVectorScale () const
Returns the scale of vectors used in xballs.
void setXBallsAdditionalArguments (std::string newXBArgs)
Set the additional arguments for xballs.
std::string getXBallsAdditionalArguments () const
Returns the additional arguments for xballs.
void setXBallsScale (Mdouble newScale)
Sets the scale of the view (either normal, zoom in or zoom out) to display in xballs. The default is fit to screen.
double getXBallsScale () const
Returns the scale of the view in xballs.
void setGravity (Vec3D newGravity)
Sets a new value for the gravitational acceleration.
Vec3D getGravity () const
Returns the gravitational acceleration.
void setBackgroundDrag (Mdouble backgroundDrag)
Simple access function to turn on a background drag. The force of particleVelocity*drag is applied (note, it allowed to be negative i.e. create energy)
const Mdouble getBackgroundDrag () const
Return the background drag.
void setDimension (unsigned int newDim)
Sets both the system dimensions and the particle dimensionality.
void setSystemDimensions (unsigned int newDim)
Sets the system dimensionality.
unsigned int getSystemDimensions () const
Returns the system dimensionality.
void setParticleDimensions (unsigned int particleDimensions)
Sets the particle dimensionality.
unsigned int getParticleDimensions () const
Returns the particle dimensionality.
std::string getRestartVersion () const
This is to take into account for different Mercury versions. Returns the version of the restart file.
void setRestartVersion (std::string newRV)
Sets restart_version.
bool getRestarted () const
Returns the flag denoting if the simulation was restarted or not.
void setRestarted (bool newRestartedFlag)
Allows to set the flag stating if the simulation is to be restarted or not.
bool getAppend () const
Returns whether the "append" option is on or off.
void setAppend (bool newAppendFlag)
Sets whether the "append" option is on or off.
Mdouble getElasticEnergy () const
Returns the global elastic energy within the system.
Mdouble getKineticEnergy () const
Returns the global kinetic energy stored in the system.
Mdouble getGravitationalEnergy (Vec3D origin={0, 0, 0}) const
Returns the global gravitational potential energy stored relative to a user-defined origin in the system. Note, if no origin is specified the real origin i.e. (0,0,0) is taken.
Mdouble getRotationalEnergy () const
Returns the global rotational energy stored in the system.
Mdouble getTotalEnergy () const
Mdouble getTotalMass () const
JMFT: Return the total mass of the system, excluding fixed particles.
Vec3D getCentreOfMass () const
JMFT: Return the centre of mass of the system, excluding fixed particles.
Vec3D getTotalMomentum () const
JMFT: Return the total momentum of the system, excluding fixed particles.
double getCPUTime ()
double getWallTime ()
virtual void hGridInsertParticle (BaseParticle *obj UNUSED)
virtual void hGridUpdateParticle (BaseParticle *obj UNUSED)
virtual void hGridRemoveParticle (BaseParticle *obj UNUSED)
bool mpiIsInCommunicationZone (BaseParticle *particle)
Checks if the position of the particle is in an mpi communication zone or not.
bool mpiInsertParticleCheck (BaseParticle *P)
Function that checks if the mpi particle should really be inserted by the current domain.
void insertGhostParticle (BaseParticle *P)
This function inserts a particle in the mpi communication boundaries.
void updateGhostGrid (BaseParticle *P)
Checks if the Domain/periodic interaction distance needs to be updated and updates it accordingly.
virtual void gatherContactStatistics (unsigned int index1, int index2, Vec3D Contact, Mdouble delta, Mdouble ctheta, Mdouble fdotn, Mdouble fdott, Vec3D P1_P2_normal_, Vec3D P1_P2_tangential)
//Not unsigned index because of possible wall collisions.
void setNumberOfDomains (std::vector< unsigned > direction)
Sets the number of domains in x-,y- and z-direction. Required for parallel computations.
void splitDomain (DomainSplit domainSplit)
std::vector< unsigned > getNumberOfDomains ()
returns the number of domains
Domain * getCurrentDomain ()
Function that returns a pointer to the domain corresponding to the processor.
void removeOldFiles () const
void setMeanVelocity (Vec3D V_mean_goal)
This function will help you set a fixed kinetic energy and mean velocity in your system.
void setMeanVelocityAndKineticEnergy (Vec3D V_mean_goal, Mdouble Ek_goal)
This function will help you set a fixed kinetic energy and mean velocity in your system.
Mdouble getTotalVolume () const
Get the total volume of the cuboid system.
Matrix3D getKineticStress () const
Calculate the kinetic stress tensor in the system averaged over the whole volume.
Matrix3D getStaticStress () const
Calculate the static stress tensor in the system averaged over the whole volume.
Matrix3D getTotalStress () const
Calculate the total stress tensor in the system averaged over the whole volume.
virtual void handleParticleRemoval (unsigned int id)
Handles the removal of particles from the particleHandler.
virtual void handleParticleAddition (unsigned int id, BaseParticle *p)
Handles the addition of particles to the particleHandler.
void writePythonFileForVTKVisualisation () const
writes .py file for ParaView
void setWritePythonFileForVTKVisualisation (bool forceWritePythonFileForVTKVisualisation)
bool getWritePythonFileForVTKVisualisation () const
WallVTKWriter & getWallVTKWriter ()
Public Attributes
Vec3D init_orientation = Vec3D(1,0,0)
Vec3D final_orientation = Vec3D(1,0,0)
Double2DVector inertia_profiles
Mdouble functional = 0
Mdouble progDuration = 0
Mdouble symDuration = 0
Mdouble baseAngVel = 0
Mdouble c_theta
Mdouble c_phi
DoubleVector angularMomentumLog
Public Attributes inherited from DPMBase
SpeciesHandler speciesHandler
A handler to that stores the species type i.e. LinearViscoelasticSpecies, etc.
RNG random
This is a random generator, often used for setting up the initial conditions etc...
ParticleHandler particleHandler
An object of the class ParticleHandler, contains the pointers to all the particles created.
ParticleHandler paoloParticleHandler
Fake particleHandler created by Paolo needed temporary by just Paolo.
WallHandler wallHandler
An object of the class WallHandler. Contains pointers to all the walls created.
BoundaryHandler boundaryHandler
An object of the class BoundaryHandler which concerns insertion and deletion of particles into or from regions.
PeriodicBoundaryHandler periodicBoundaryHandler
Internal handler that deals with periodic boundaries, especially in a parallel build.
DomainHandler domainHandler
An object of the class DomainHandler which deals with parallel code.
InteractionHandler interactionHandler
An object of the class InteractionHandler.
CGHandler cgHandler
Object of the class cgHandler.
File dataFile
An instance of class File to handle in- and output into a .data file.
File fStatFile
An instance of class File to handle in- and output into a .fstat file.
File eneFile
An instance of class File to handle in- and output into a .ene file.
File restartFile
An instance of class File to handle in- and output into a .restart file.
File statFile
An instance of class File to handle in- and output into a .stat file.
File interactionFile
File class to handle in- and output into .interactions file. This file hold information about interactions.
Time clock_
record when the simulation started
Private Attributes
int clump_index
ClumpData data
Mdouble clump_mass
Mdouble clump_damping = 10
unsigned rotatingWallID = 0
CubeInsertionBoundary * insertionBoundary
Additional Inherited Members
Public Types inherited from DPMBase
enum class ReadOptions : int { ReadAll , ReadNoInteractions , ReadNoParticlesAndInteractions }
enum class DomainSplit {
X , Y , Z , XY ,
XZ , YZ , XYZ
}
Static Public Member Functions inherited from DPMBase
static void incrementRunNumberInFile ()
Increment the run Number (counter value) stored in the file_counter (COUNTER_DONOTDEL) by 1 and store the new value in the counter file.
static int readRunNumberFromFile ()
Read the run number or the counter from the counter file (COUNTER_DONOTDEL)
static bool areInContact (const BaseParticle *pI, const BaseParticle *pJ)
Checks if two particle are in contact or is there any positive overlap.
Protected Member Functions inherited from Mercury3D
void hGridFindContactsWithinTargetCell (int x, int y, int z, unsigned int l)
Finds contacts between particles in the target cell.
void hGridFindContactsWithTargetCell (int x, int y, int z, unsigned int l, BaseParticle *obj)
Finds contacts between the BaseParticle and the target cell.
void computeWallForces (BaseWall *w) override
Compute contacts with a wall.
void hGridFindParticlesWithTargetCell (int x, int y, int z, unsigned int l, BaseParticle *obj, std::vector< BaseParticle * > &list)
Finds particles within target cell and stores them in a list.
void hGridGetInteractingParticleList (BaseParticle *obj, std::vector< BaseParticle * > &list) override
Obtains all neighbour particles of a given object, obtained from the hgrid.
void computeInternalForces (BaseParticle *obj) override
Finds contacts with the BaseParticle; avoids multiple checks.
bool hGridHasContactsInTargetCell (int x, int y, int z, unsigned int l, const BaseParticle *obj) const
Tests if the BaseParticle has contacts with other Particles in the target cell.
bool hGridHasParticleContacts (const BaseParticle *obj) override
Tests if a BaseParticle has any contacts in the HGrid.
void hGridRemoveParticle (BaseParticle *obj) override
Removes a BaseParticle from the HGrid.
void hGridUpdateParticle (BaseParticle *obj) override
Updates the cell (not the level) of a BaseParticle.
Protected Member Functions inherited from MercuryBase
void hGridRebuild ()
This sets up the parameters required for the contact model.
void hGridInsertParticle (BaseParticle *obj) final
Inserts a single Particle to current grid.
void hGridUpdateMove (BaseParticle *iP, Mdouble move) final
Computes the relative displacement of the given BaseParticle and updates the currentMaxRelativeDisplacement_ accordingly.
void hGridActionsBeforeIntegration () override
Resets the currentMaxRelativeDisplacement_ to 0.
void hGridActionsAfterIntegration () override
This function has to be called before integrateBeforeForceComputation.
HGrid * getHGrid ()
Gets the HGrid used by this problem.
const HGrid * getHGrid () const
Gets the HGrid used by this problem, const version.
bool readNextArgument (int &i, int argc, char *argv[]) override
Reads the next command line argument.
Protected Member Functions inherited from DPMBase
virtual void computeExternalForces (BaseParticle *)
Computes the external forces, such as gravity, acting on particles.
virtual void actionsOnRestart ()
A virtual function where the users can add extra code which is executed only when the code is restarted.
virtual void actionsBeforeTimeLoop ()
A virtual function. Allows one to carry out any operations before the start of the time loop.
virtual void actionsBeforeTimeStep ()
A virtual function which allows to define operations to be executed before the new time step.
virtual void computeAdditionalForces ()
A virtual function which allows to define operations to be executed prior to the OMP force collect.
virtual void actionsAfterSolve ()
A virtual function which allows to define operations to be executed after the solve().
void writeVTKFiles () const
virtual void outputXBallsData (std::ostream &os) const
This function writes the location of the walls and particles in a format the XBalls program can read. For more information on the XBalls program, see Visualising data in xballs.
virtual void outputXBallsDataParticle (unsigned int i, unsigned int format, std::ostream &os) const
This function writes out the particle locations into an output stream in a format the XBalls program can read. For more information on the XBalls program, see Visualising data in xballs.
virtual void writeEneHeader (std::ostream &os) const
Writes a header with a certain format for ENE file.
virtual void writeFstatHeader (std::ostream &os) const
Writes a header with a certain format for FStat file.
virtual void writeEneTimeStep (std::ostream &os) const
Write the global kinetic, potential energy, etc. in the system.
virtual void initialiseStatistics ()
virtual void outputStatistics ()
void gatherContactStatistics ()
virtual void processStatistics (bool)
virtual void finishStatistics ()
virtual void integrateBeforeForceComputation ()
Update particles' and walls' positions and velocities before force computation.
virtual void integrateAfterForceComputation ()
Update particles' and walls' positions and velocities after force computation.
virtual void checkInteractionWithBoundaries ()
There are a range of boundaries one could implement depending on ones' problem. This methods checks for interactions between particles and such range of boundaries. See BaseBoundary.h and all the boundaries in the Boundaries folder.
void setFixedParticles (unsigned int n)
Sets a number, n, of particles in the particleHandler as "fixed particles".
virtual void printTime () const
Displays the current simulation time and the maximum simulation duration.
virtual bool continueSolve () const
A virtual function for deciding whether to continue the simulation, based on a user-specified criterion.
void outputInteractionDetails () const
Displays the interaction details corresponding to the pointer objects in the interaction handler.
bool isTimeEqualTo (Mdouble time) const
Checks whether the input variable "time" is the current time in the simulation.
void removeDuplicatePeriodicParticles ()
Removes periodic duplicate Particles.
void checkAndDuplicatePeriodicParticles ()
For simulations using periodic boundaries, checks and adds particles when necessary into the particle handler. See DPMBase.cc and PeriodicBoundary.cc for more details.
void performGhostParticleUpdate ()
When the Verlet scheme updates the positions and velocities of particles, ghost particles will need an update as wel. Their status will also be updated accordingly.
void deleteGhostParticles (std::set< BaseParticle * > &particlesToBeDeleted)
void synchroniseParticle (BaseParticle *, unsigned fromProcessor=0)
void performGhostVelocityUpdate ()
updates the final time-step velocity of the ghost particles
void disableSoftStop ()
This prevents the initialisation of the soft stop feature.
void discontinueSolve ()
This discontinues the solve loop after the current time step is finished.
Constructor & Destructor Documentation
ChangingTOIParticle() [1/8]
ChangingTOIParticle::ChangingTOIParticle () inline explicit
     {
         setGravity(Vec3D(0.0, 0.0, 0.0));
         setName("ChangingTOI");
         setXBallsAdditionalArguments("-solidf -v0");
         setXMax(f_max);
         setYMax(f_max);
         setZMax(f_max);
         setXMin(f_min);
         setYMin(f_min);
         setZMin(f_min);
         LoadClumps(data);
         clump_mass = data.mass[clump_index];
     }
References clump_index, clump_mass, data, f_max, f_min, LoadClumps(), ClumpData::mass, DPMBase::setGravity(), DPMBase::setName(), DPMBase::setXBallsAdditionalArguments(), DPMBase::setXMax(), DPMBase::setXMin(), DPMBase::setYMax(), DPMBase::setYMin(), DPMBase::setZMax(), and DPMBase::setZMin().
ChangingTOIParticle() [2/8]
ChangingTOIParticle::ChangingTOIParticle () inline explicit
     {
         setGravity(Vec3D(0.0, 0.0, -10.0));
         setName("Domino");
         setXBallsAdditionalArguments("-solidf -v0");
         setXMax(D.x_max);
         setYMax(D.y_max);
         setZMax(D.z_max);
         setXMin(D.x_min);
         setYMin(D.y_min);
         setZMin(D.z_min);
     }
References D, DPMBase::setGravity(), DPMBase::setName(), DPMBase::setXBallsAdditionalArguments(), DPMBase::setXMax(), DPMBase::setXMin(), DPMBase::setYMax(), DPMBase::setYMin(), DPMBase::setZMax(), DPMBase::setZMin(), dominoes::x_max, dominoes::x_min, dominoes::y_max, dominoes::y_min, dominoes::z_max, and dominoes::z_min.
ChangingTOIParticle() [3/8]
ChangingTOIParticle::ChangingTOIParticle () inline explicit
     {
         setGravity(Vec3D(0.0, 0.0, -10.0));
         setName("Gomboc");
         setXBallsAdditionalArguments("-solidf -v0");
         setXMax(2*f_max);
         setYMax(2*f_max);
         setZMax(f_max);
         setXMin(2*f_min);
         setYMin(2*f_min);
         setZMin(f_min);
         LoadClumps(data);
         setClumpIndex(0);
         clump_mass = data.mass[clump_index];
     }
References clump_index, clump_mass, data, f_max, f_min, LoadClumps(), ClumpData::mass, setClumpIndex(), DPMBase::setGravity(), DPMBase::setName(), DPMBase::setXBallsAdditionalArguments(), DPMBase::setXMax(), DPMBase::setXMin(), DPMBase::setYMax(), DPMBase::setYMin(), DPMBase::setZMax(), and DPMBase::setZMin().
ChangingTOIParticle() [4/8]
ChangingTOIParticle::ChangingTOIParticle () inline explicit
     {
         setGravity(Vec3D(0.0, 0.0, -10.0));
         setName("Rattleback");
         setXBallsAdditionalArguments("-solidf -v0");
         setXMax(2*f_max);
         setYMax(2*f_max);
         setZMax(f_max);
         setXMin(2*f_min);
         setYMin(2*f_min);
         setZMin(f_min);
         LoadClumps(data);
         setClumpIndex(0);
         clump_mass = data.mass[clump_index];
     }
References clump_index, clump_mass, data, f_max, f_min, LoadClumps(), ClumpData::mass, setClumpIndex(), DPMBase::setGravity(), DPMBase::setName(), DPMBase::setXBallsAdditionalArguments(), DPMBase::setXMax(), DPMBase::setXMin(), DPMBase::setYMax(), DPMBase::setYMin(), DPMBase::setZMax(), and DPMBase::setZMin().
ChangingTOIParticle() [5/8]
ChangingTOIParticle::ChangingTOIParticle () inline explicit
     {
         setGravity(Vec3D(0,-9.8,0));
         // Set name of output files
         setName("RotatingDrumClumps");
         setXBallsAdditionalArguments("-solidf -v0");
         // Set domain size
         setMin({f_min,f_min,f_min});
         setMax({f_max,f_max,f_max});
         // Output files: wall-vtu
         LoadClumps(data);
         setClumpIndex(2);
         clump_mass = data.mass[clump_index];
     }
References clump_index, clump_mass, data, f_max, f_min, LoadClumps(), ClumpData::mass, setClumpIndex(), DPMBase::setGravity(), DPMBase::setMax(), DPMBase::setMin(), DPMBase::setName(), and DPMBase::setXBallsAdditionalArguments().
ChangingTOIParticle() [6/8]
ChangingTOIParticle::ChangingTOIParticle () inline explicit
     {
         setGravity(Vec3D(0.0, 0.0, 0.0));
         setName("Single");
         setXBallsAdditionalArguments("-solidf -v0");
         setXMax(f_max);
         setYMax(f_max);
         setZMax(f_max);
         setXMin(f_min);
         setYMin(f_min);
         setZMin(f_min);
         LoadClumps(data);
         setClumpIndex(0);
         clump_mass = data.mass[clump_index];
     }
References clump_index, clump_mass, data, f_max, f_min, LoadClumps(), ClumpData::mass, setClumpIndex(), DPMBase::setGravity(), DPMBase::setName(), DPMBase::setXBallsAdditionalArguments(), DPMBase::setXMax(), DPMBase::setXMin(), DPMBase::setYMax(), DPMBase::setYMin(), DPMBase::setZMax(), and DPMBase::setZMin().
ChangingTOIParticle() [7/8]
ChangingTOIParticle::ChangingTOIParticle () inline explicit
     {
         setGravity(Vec3D(0.0, 0.0, 0.0));
         setName("TBar");
         setXBallsAdditionalArguments("-solidf -v0");
         setXMax(f_max);
         setYMax(f_max);
         setZMax(f_max);
         setXMin(f_min);
         setYMin(f_min);
         setZMin(f_min);
         LoadClumps(data);
         setClumpIndex(0);
         clump_mass = data.mass[clump_index];
     }
References clump_index, clump_mass, data, f_max, f_min, LoadClumps(), ClumpData::mass, setClumpIndex(), DPMBase::setGravity(), DPMBase::setName(), DPMBase::setXBallsAdditionalArguments(), DPMBase::setXMax(), DPMBase::setXMin(), DPMBase::setYMax(), DPMBase::setYMin(), DPMBase::setZMax(), and DPMBase::setZMin().
ChangingTOIParticle() [8/8]
ChangingTOIParticle::ChangingTOIParticle () inline explicit
     {
         setGravity(Vec3D(0.0, 0.0, -0.0));
         setName("TGas");
         setXBallsAdditionalArguments("-solidf -v0");
         setXMax(f_max);
         setYMax(f_max);
         setZMax(f_max); // Unbounded domain
         setXMin(f_min);
         setYMin(f_min);
         setZMin(f_min);
         LoadClumps(data);
         clump_mass = data.mass[clump_index];
     }
References clump_index, clump_mass, data, f_max, f_min, LoadClumps(), ClumpData::mass, DPMBase::setGravity(), DPMBase::setName(), DPMBase::setXBallsAdditionalArguments(), DPMBase::setXMax(), DPMBase::setXMin(), DPMBase::setYMax(), DPMBase::setYMin(), DPMBase::setZMax(), and DPMBase::setZMin().
Member Function Documentation
actionsAfterTimeStep() [1/6]
void ChangingTOIParticle::actionsAfterTimeStep () inline override virtual
A virtual function which allows to define operations to be executed after time step.
no implementation but can be overridden in its derived classes.
Reimplemented from DPMBase.
{
         MatrixSymmetric3D cInertia;
         MatrixSymmetric3D inertiaRate;
         MatrixSymmetric3D fInertia;
         fInertia.XX = inertia_profiles[inertia_profiles.size()-1][1];
         fInertia.YY = inertia_profiles[inertia_profiles.size()-1][2];
         fInertia.ZZ = inertia_profiles[inertia_profiles.size()-1][3];
         fInertia.XY = 0;
         fInertia.XZ = 0;
         fInertia.YZ = 0;
     for (std::vector<BaseParticle*>::iterator it= particleHandler.begin(); it!=particleHandler.end(); ++it){
         if ((*it)->isClump()) {
             // Get Principal directions/rotation matrix
             Matrix3D Q = static_cast<ClumpParticle*>(*it)->getRotationMatrix();
             Matrix3D Qt = transpose(Q);
             // Prescribe particle TOI (specified in inertia_profiles array) for every moment of simulation
             int ind = (int) floor(inertia_profiles.size()*(getTime()/progDuration));
             if (ind < inertia_profiles.size()-1) {
                 cInertia.XX = inertia_profiles[ind][1];
                 cInertia.YY = inertia_profiles[ind][2];
                 cInertia.ZZ = inertia_profiles[ind][3];
                 cInertia.XY = 0;
                 cInertia.XZ = 0;
                 cInertia.YZ = 0;
                 inertiaRate.XX = inertia_profiles[ind][4];
                 inertiaRate.YY = inertia_profiles[ind][5];
                 inertiaRate.ZZ = inertia_profiles[ind][6];
                 inertiaRate.XY = 0;
                 inertiaRate.XZ = 0;
                 inertiaRate.YZ = 0;
                 MatrixSymmetric3D rotatedCInertia = MtoS(Q * (StoM(cInertia) * Qt));
                 static_cast<ClumpParticle *>(*it)->setInitInertia(rotatedCInertia);
                 // Add extra torques  - I^{dot} * omega
                 Vec3D angVel = (*it)->getAngularVelocity();
                 Matrix3D S = Matrix3D(0, -angVel.Z, angVel.Y,   angVel.Z, 0, -angVel.X, -angVel.Y, angVel.X, 0);
                 Matrix3D St = transpose(S);
                 //MatrixSymmetric3D rotatedInertiaRate = MtoS( Q * StoM(inertiaRate) * Qt +
                 //                                                S * StoM(rotatedCInertia) * Qt +
                 //                                                Q * StoM(rotatedCInertia) * St);
                 MatrixSymmetric3D rotatedInertiaRate = MtoS( Q * StoM(inertiaRate) * Qt);
                 Vec3D TorqueDueToRate = rotatedInertiaRate * angVel;
                 static_cast<ClumpParticle *>(*it)->setTorque(-TorqueDueToRate);
                 // Store angular momentum (for validation purposes)
                 angularMomentumLog.push_back((rotatedCInertia * angVel).getLength());
             }
             if (ind == inertia_profiles.size()-1){ // The last step of control program
                 // Ensure no torques and static TOI at the final part of the simulation
                 static_cast<ClumpParticle*>(*it)->setTorque(Vec3D(0,0,0));
                 MatrixSymmetric3D rotatedFInertia = MtoS(Q * (StoM(fInertia) * Qt));
                 static_cast<ClumpParticle*>(*it)->setInitInertia(rotatedFInertia);
                 // Compute functional (has to be done once in the end of simulation)
                 Vec3D angVel = (*it)->getAngularVelocity();
                 Vec3D e1 = Vec3D(1,0,0); // Cartesian axes
                 Vec3D e2 = Vec3D(0,1,0);
                 Vec3D e3 = Vec3D(0,0,1);
                 Vec3D n1 = Q * Vec3D(1,0,0); // principal axes orientations
                 Vec3D n2 = Q * Vec3D(0,1,0);
                 Vec3D n3 = Q * Vec3D(0,0,1);
                 Vec3D w = angVel / angVel.getLength(); // angular velocity
                 c_theta = acos(Vec3D::dot(n3, w));
                 Vec3D n_phi = n1 * Vec3D::dot(n1, w) + n2 * Vec3D::dot(n2, w);
                 n_phi = n_phi / n_phi.getLength();
                 c_phi = atan2(Vec3D::dot(n2, n_phi), Vec3D::dot(n1, n_phi));
                 Vec3D f = final_orientation;
                 Mdouble f_theta = acos(Vec3D::dot(e3, f));
                 Vec3D e_phi = e1 * Vec3D::dot(e1, f) + e2 * Vec3D::dot(e2, f);
                 e_phi = e_phi / e_phi.getLength();
                 Mdouble f_phi = atan2(Vec3D::dot(e2, e_phi), Vec3D::dot(e1, e_phi));
                 Vec3D k1 = Vec3D(sin(c_theta) * cos(c_phi), sin(c_theta) * sin(c_phi), cos(c_theta));
                 Vec3D k2 = Vec3D(sin(f_theta) * cos(f_phi), sin(f_theta) * sin(f_phi), cos(f_theta));
                 functional = acos(Vec3D::dot(k1, k2));
             }
         }
         }
         Mercury3D::actionsAfterTimeStep();
     }
References acos(), DPMBase::actionsAfterTimeStep(), angularMomentumLog, atan2(), BaseHandler< T >::begin(), c_phi, c_theta, cos(), Vec3D::dot(), BaseHandler< T >::end(), f(), final_orientation, Eigen::bfloat16_impl::floor(), functional, Vec3D::getLength(), ClumpParticle::getRotationMatrix(), DPMBase::getTime(), ind, inertia_profiles, int(), MtoS(), DPMBase::particleHandler, progDuration, Q, oomph::QuadTreeNames::S, ClumpParticle::setInitInertia(), BaseInteractable::setTorque(), sin(), Global_Physical_Variables::St, StoM(), transpose(), w, Vec3D::X, MatrixSymmetric3D::XX, MatrixSymmetric3D::XY, MatrixSymmetric3D::XZ, Vec3D::Y, MatrixSymmetric3D::YY, MatrixSymmetric3D::YZ, Vec3D::Z, and MatrixSymmetric3D::ZZ.
actionsAfterTimeStep() [2/6]
void ChangingTOIParticle::actionsAfterTimeStep () inline override virtual
A virtual function which allows to define operations to be executed after time step.
no implementation but can be overridden in its derived classes.
Reimplemented from DPMBase.
{
         // Measurement of the propagation velocity of a Domino wave
         for (std::vector<BaseParticle*>::iterator it= particleHandler.begin(); it!=particleHandler.end(); ++it){
             if ((*it)->isClump()) {
                 //D_num += (int) static_cast<Clump*>(*it)->getDzhanibekovParticle();
                 if ((D.started == false)&&((*it)->getPosition().X > D.margin + D.N_ini*D.S_dom - 0.001)&&( (*it)->getVelocity().getLength()>0.001  ))
                 {
                     D.started = true;
                     D.T1 = getTime();
                 }
                 if ((D.started == true)&&(D.finished == false)&&((*it)->getPosition().X > D.margin + D.N_fin*D.S_dom - 0.001)&&( (*it)->getVelocity().getLength()>0.001  ))
                 {
                     D.finished = true;
                     D.T2 = getTime();
                 }
             }
         }
     }
References BaseHandler< T >::begin(), D, BaseHandler< T >::end(), dominoes::finished, DPMBase::getTime(), dominoes::margin, dominoes::N_fin, dominoes::N_ini, DPMBase::particleHandler, dominoes::S_dom, dominoes::started, dominoes::T1, and dominoes::T2.
actionsAfterTimeStep() [3/6]
void ChangingTOIParticle::actionsAfterTimeStep () inline override virtual
A virtual function which allows to define operations to be executed after time step.
no implementation but can be overridden in its derived classes.
Reimplemented from DPMBase.
{
         if (getNumberOfTimeSteps()/SAVECOUNT == getNumberOfTimeSteps()/(double) SAVECOUNT ){
             for (std::vector<BaseParticle*>::iterator it= particleHandler.begin(); it!=particleHandler.end(); ++it){
                 if ((*it)->isClump()) {
                     std::cout<<"Saving timestep "<<getNumberOfTimeSteps() <<std::endl;
                     // Add velocity to log
                     std::ofstream funct("ClumpSeq.txt", std::ios_base::app | std::ios_base::out);
                     funct << getNumberOfTimeSteps() << " "
                           << static_cast<ClumpParticle*>(*it)->getPosition() << " "
                           << static_cast<ClumpParticle*>(*it)->getPrincipalDirections_e1() << " "
                           << static_cast<ClumpParticle*>(*it)->getPrincipalDirections_e2() << " "
                           << static_cast<ClumpParticle*>(*it)->getPrincipalDirections_e3() << " "
                     <<"\n";
                     funct.close();
                 }
             }
         }
     }
References BaseHandler< T >::begin(), BaseHandler< T >::end(), DPMBase::getNumberOfTimeSteps(), BaseInteractable::getPosition(), ClumpParticle::getPrincipalDirections_e1(), ClumpParticle::getPrincipalDirections_e2(), ClumpParticle::getPrincipalDirections_e3(), out(), DPMBase::particleHandler, and SAVECOUNT.
actionsAfterTimeStep() [4/6]
void ChangingTOIParticle::actionsAfterTimeStep () inline override virtual
A virtual function which allows to define operations to be executed after time step.
no implementation but can be overridden in its derived classes.
Reimplemented from DPMBase.
{
         if (getNumberOfTimeSteps()/SAVECOUNT == getNumberOfTimeSteps()/(double) SAVECOUNT ){
             for (std::vector<BaseParticle*>::iterator it= particleHandler.begin(); it!=particleHandler.end(); ++it){
                 if ((*it)->isClump()) {
                     std::cout<<"Saving timestep "<<getNumberOfTimeSteps() <<std::endl;
                     // Add velocity to log
                     std::ofstream funct("ClumpSeq.txt", std::ios_base::app | std::ios_base::out);
                     funct << getNumberOfTimeSteps() << " "
                           << static_cast<ClumpParticle*>(*it)->getPosition() << " "
                           << static_cast<ClumpParticle*>(*it)->getPrincipalDirections_e1() << " "
                           << static_cast<ClumpParticle*>(*it)->getPrincipalDirections_e2() << " "
                           << static_cast<ClumpParticle*>(*it)->getPrincipalDirections_e3() << " "
                     <<"\n";
                     funct.close();
                 }
             }
         }
     }
References BaseHandler< T >::begin(), BaseHandler< T >::end(), DPMBase::getNumberOfTimeSteps(), BaseInteractable::getPosition(), ClumpParticle::getPrincipalDirections_e1(), ClumpParticle::getPrincipalDirections_e2(), ClumpParticle::getPrincipalDirections_e3(), out(), DPMBase::particleHandler, and SAVECOUNT.
actionsAfterTimeStep() [5/6]
void ChangingTOIParticle::actionsAfterTimeStep () inline override virtual
A virtual function which allows to define operations to be executed after time step.
no implementation but can be overridden in its derived classes.
Reimplemented from DPMBase.
{
         Vec3D angularVelocity = Vec3D(0,0,1.0/12.0*constants::pi);
         for (const auto wall : wallHandler) {
                 if (wall->getGroupId()==rotatingWallID) {
                     wall->setAngularVelocity(angularVelocity);
                 }
             }
     }
References constants::pi, rotatingWallID, and DPMBase::wallHandler.
actionsAfterTimeStep() [6/6]
void ChangingTOIParticle::actionsAfterTimeStep () inline override virtual
A virtual function which allows to define operations to be executed after time step.
no implementation but can be overridden in its derived classes.
Reimplemented from DPMBase.
{
         int D_num = 0;
         for (std::vector<BaseParticle*>::iterator it= particleHandler.begin(); it!=particleHandler.end(); ++it){
             if ((*it)->isClump()) {
                 D_num += (int) static_cast<ClumpParticle*>(*it)->getDzhanibekovParticle();
             }
         }
         D_h.push_back(D_num);
     }
References BaseHandler< T >::begin(), D_h, BaseHandler< T >::end(), ClumpParticle::getDzhanibekovParticle(), int(), and DPMBase::particleHandler.
getClumpMass() [1/8]
Mdouble ChangingTOIParticle::getClumpMass () inline
 {return clump_mass;}
References clump_mass.
getClumpMass() [2/8]
Mdouble ChangingTOIParticle::getClumpMass () inline
 {return clump_mass;}
References clump_mass.
getClumpMass() [3/8]
Mdouble ChangingTOIParticle::getClumpMass () inline
 {return clump_mass;}
References clump_mass.
getClumpMass() [4/8]
Mdouble ChangingTOIParticle::getClumpMass () inline
 {return clump_mass;}
References clump_mass.
getClumpMass() [5/8]
Mdouble ChangingTOIParticle::getClumpMass () inline
 {return clump_mass;}
References clump_mass.
getClumpMass() [6/8]
Mdouble ChangingTOIParticle::getClumpMass () inline
 {return clump_mass;}
References clump_mass.
getClumpMass() [7/8]
Mdouble ChangingTOIParticle::getClumpMass () inline
 {return clump_mass;}
References clump_mass.
getClumpMass() [8/8]
Mdouble ChangingTOIParticle::getClumpMass () inline
 {return clump_mass;}
References clump_mass.
MtoS()
MatrixSymmetric3D ChangingTOIParticle::MtoS (Matrix3D M) inline
 { return MatrixSymmetric3D(M.XX, M.XY, M.XZ, M.YY, M.YZ, M.ZZ);}
Referenced by actionsAfterTimeStep().
setClumpDamping() [1/8]
void ChangingTOIParticle::setClumpDamping (Mdouble damp) inline
 { clump_damping = damp;}
References clump_damping.
setClumpDamping() [2/8]
void ChangingTOIParticle::setClumpDamping (Mdouble damp) inline
 { clump_damping = damp;}
References clump_damping.
setClumpDamping() [3/8]
void ChangingTOIParticle::setClumpDamping (Mdouble damp) inline
 { clump_damping = damp;}
References clump_damping.
setClumpDamping() [4/8]
void ChangingTOIParticle::setClumpDamping (Mdouble damp) inline
 { clump_damping = damp;}
References clump_damping.
setClumpDamping() [5/8]
void ChangingTOIParticle::setClumpDamping (Mdouble damp) inline
 { clump_damping = damp;}
References clump_damping.
setClumpDamping() [6/8]
void ChangingTOIParticle::setClumpDamping (Mdouble damp) inline
 { clump_damping = damp;}
References clump_damping.
setClumpDamping() [7/8]
void ChangingTOIParticle::setClumpDamping (Mdouble damp) inline
 { clump_damping = damp;}
References clump_damping.
setClumpDamping() [8/8]
void ChangingTOIParticle::setClumpDamping (Mdouble damp) inline
 { clump_damping = damp;}
References clump_damping.
setClumpIndex() [1/8]
void ChangingTOIParticle::setClumpIndex (Mdouble index) inline
 { clump_index = index;}
References clump_index.
Referenced by ChangingTOIParticle(), and setupInitialConditions().
setClumpIndex() [2/8]
void ChangingTOIParticle::setClumpIndex (Mdouble index) inline
 { clump_index = index;}
References clump_index.
setClumpIndex() [3/8]
void ChangingTOIParticle::setClumpIndex (Mdouble index) inline
 { clump_index = index;}
References clump_index.
setClumpIndex() [4/8]
void ChangingTOIParticle::setClumpIndex (Mdouble index) inline
 { clump_index = index;}
References clump_index.
setClumpIndex() [5/8]
void ChangingTOIParticle::setClumpIndex (Mdouble index) inline
 { clump_index = index;}
References clump_index.
setClumpIndex() [6/8]
void ChangingTOIParticle::setClumpIndex (Mdouble index) inline
 { clump_index = index;}
References clump_index.
setClumpIndex() [7/8]
void ChangingTOIParticle::setClumpIndex (Mdouble index) inline
 { clump_index = index;}
References clump_index.
setClumpIndex() [8/8]
void ChangingTOIParticle::setClumpIndex (Mdouble index) inline
 { clump_index = index;}
References clump_index.
setupInitialConditions() [1/8]
void ChangingTOIParticle::setupInitialConditions () inline override virtual
This function allows to set the initial conditions for our problem to be solved, by default particle locations are randomly set. Remember particle properties must also be defined here.
A virtual function with no implementation but can be overridden.
Todo:
I (Anthony) wants to change this to be an external function. This has a lot of advantages especially when using copy-constructors. This is a major change and will break other codes, so therefore has to be done carefully.
This sets up the particles initial conditions it is as you expect the user to override this. By default the particles are randomly distributed
Reimplemented from DPMBase.
     {
         // Generate single clump
         ClumpParticle p0;
         p0.setSpecies(speciesHandler.getObject(0)); // Assign the material type to ClumpParticle
         p0.setClump();
         p0.setRadius(0.5);
         p0.setPosition(Vec3D(0, 0, 0));
         // Pebble particles are used for visualisation purposes only
         // (sphere/arrow glyphs are employed in Paraview to visualize the corresponding directions)
         // Pebble's inertial properties are not employed in calculations
         p0.addPebble(Vec3D(0,0,0),1);
         p0.addPebble(Vec3D(1,0,0),3.5);
         p0.addPebble(Vec3D(-1,0,0),4);
         p0.addPebble(Vec3D(0,1,0),2.5);
         p0.addPebble(Vec3D(0,-1,0),3);
         p0.addPebble(Vec3D(0,0,1),1.5);
         p0.addPebble(Vec3D(0,0,-1),2);
         // Extra direction markers (for Paraview arrow glyphs)
         p0.addPebble(Vec3D(10e-8,10e-8,10e-8),2); // Marker of point 4
         p0.addPebble(Vec3D(10e-8,0,10e-8),2); // marker of point 3
         p0.addPebble(Vec3D(0,10e-8,10e-8),2); // marker of point 2
         p0.addPebble(Vec3D(10e-8,10e-8,0),2); // marker of point 1
         p0.addPebble(Vec3D(10e-8,0,0),2); // marker of point 6
         p0.addPebble(Vec3D(0,10e-8,0),2); // marker of point 7
         p0.addPebble(Vec3D(0,0,10e-8),2); // marker of point 5
         p0.addPebble(Vec3D(0,0,-10e-8),2); // marker of point 8
         p0.setPrincipalDirections(Matrix3D(1,0,0, 0,1,0, 0,0,1));
         MatrixSymmetric3D cInertia;
         cInertia.XX = inertia_profiles[0][1];
         cInertia.YY = inertia_profiles[0][2];
         cInertia.ZZ = inertia_profiles[0][3];
         cInertia.XY = 0;
         cInertia.XZ = 0;
         cInertia.YZ = 0;
         p0.setInitInertia(cInertia);
         p0.setClumpMass(5);
         p0.setAngularVelocity(baseAngVel * init_orientation);
         particleHandler.copyAndAddObject(p0);
     }
References baseAngVel, BaseHandler< T >::copyAndAddObject(), e(), BaseHandler< T >::getObject(), inertia_profiles, init_orientation, p0, DPMBase::particleHandler, DPMBase::speciesHandler, MatrixSymmetric3D::XX, MatrixSymmetric3D::XY, MatrixSymmetric3D::XZ, MatrixSymmetric3D::YY, MatrixSymmetric3D::YZ, and MatrixSymmetric3D::ZZ.
setupInitialConditions() [2/8]
void ChangingTOIParticle::setupInitialConditions () inline override virtual
This function allows to set the initial conditions for our problem to be solved, by default particle locations are randomly set. Remember particle properties must also be defined here.
A virtual function with no implementation but can be overridden.
Todo:
I (Anthony) wants to change this to be an external function. This has a lot of advantages especially when using copy-constructors. This is a major change and will break other codes, so therefore has to be done carefully.
This sets up the particles initial conditions it is as you expect the user to override this. By default the particles are randomly distributed
Reimplemented from DPMBase.
     {
         setParticlesWriteVTK(1);
         // Dominoes
         for (int part = 0; part<D.N_dom; part++) {
             ClumpParticle p0;
             p0.setSpecies(speciesHandler.getObject(0)); // Assign the material type to Clump 1
             p0.setClump();
             p0.setRadius(D.R_peb);
             for (int i = 0; i < 2*D.m_peb; i++) {
                 for (int j = 0; j < 2*D.n_peb; j++) {
                     for (int k = 0; k < 2*D.k_peb; k++) {
                         p0.addPebble(Vec3D(-D.S_peb * D.m_peb + (i + 0.5) * D.S_peb,
                                            -D.S_peb * D.n_peb + (j + 0.5) * D.S_peb,
                                            -D.S_peb * D.k_peb + (k + 0.5) * D.S_peb), D.R_peb);
             }}}
             p0.setPrincipalDirections(
                     Matrix3D(1, 0, 0,
                              0, 1, 0,
                              0, 0, 1));
             std::cout<<"I_xx = "<<D.I_xx<<std::endl;
             std::cout<<"I_yy = "<<D.I_yy<<std::endl;
             p0.setInitInertia(
                     MatrixSymmetric3D(D.I_xx,       0,      0,
                                                      D.I_yy,      0,
                                                                   D.I_zz));
             p0.setClumpMass(1 * D.mass);
             p0.setDamping(clump_damping);
             Vec3D pos = Vec3D(D.margin + part*D.S_dom,
                             0,
                             0);
             p0.setPosition(pos);
             Vec3D angVel(0,0,0);
             Vec3D vel(0,0,0);
             p0.setAngularVelocity(angVel);
             p0.setVelocity(vel);
             particleHandler.copyAndAddObject(p0);
         }
         // Cue
         ClumpParticle p0;
         p0.setSpecies(speciesHandler.getObject(0)); // Assign the material type to Clump 1
         p0.setClump();
         p0.setRadius(D.R_cue);
         p0.addPebble(Vec3D(0, 0, 0), D.R_cue);
         p0.setPosition(Vec3D(0.9*D.margin, 0, D.S_peb*(D.k_peb-0.5))); // sets particle position
         p0.setVelocity(Vec3D(D.Vel_cue, 0., 0.));// sets particle velocity
         particleHandler.copyAndAddObject(p0);
         // Rectangular box
         wallHandler.clear();
         InfiniteWall w0;
         w0.setSpecies(speciesHandler.getObject(1));
         w0.set(Vec3D(0.0, 0.0, -1.0), Vec3D(0, 0, getZMin()));
         wallHandler.copyAndAddObject(w0);
     }
References BaseHandler< T >::clear(), clump_damping, BaseHandler< T >::copyAndAddObject(), D, BaseHandler< T >::getObject(), DPMBase::getZMin(), i, dominoes::I_xx, dominoes::I_yy, dominoes::I_zz, j, k, dominoes::k_peb, dominoes::m_peb, dominoes::margin, dominoes::mass, dominoes::N_dom, dominoes::n_peb, p0, DPMBase::particleHandler, dominoes::R_cue, dominoes::R_peb, dominoes::S_dom, dominoes::S_peb, InfiniteWall::set(), DPMBase::setParticlesWriteVTK(), BaseWall::setSpecies(), DPMBase::speciesHandler, dominoes::Vel_cue, and DPMBase::wallHandler.
setupInitialConditions() [3/8]
void ChangingTOIParticle::setupInitialConditions () inline override virtual
This function allows to set the initial conditions for our problem to be solved, by default particle locations are randomly set. Remember particle properties must also be defined here.
A virtual function with no implementation but can be overridden.
Todo:
I (Anthony) wants to change this to be an external function. This has a lot of advantages especially when using copy-constructors. This is a major change and will break other codes, so therefore has to be done carefully.
This sets up the particles initial conditions it is as you expect the user to override this. By default the particles are randomly distributed
Reimplemented from DPMBase.
     {
         // Generate gomboc
         setClumpIndex(2);
         ClumpParticle p0;
         p0.setSpecies(speciesHandler.getObject(0)); // Assign the material type to Clump 1
         p0.setClump();
         // DoubleVector upds = UniformRandomPDs();
         DoubleVector upds = {0, 0.707107, 0.707107, 0, -0.707107, 0.707107, -1, 0, 0};
         data = RotateClump(data, clump_index, upds); // here you can try different seeds
         p0.setRadius(data.pebblesR[clump_index][0]);
         Vec3D pos = Vec3D(0, 0, -1.2);
         p0.setPosition(pos);
         for (int j = 0; j < data.pebblesR[clump_index].size(); j++) {
             p0.addPebble(Vec3D(data.pebblesX[clump_index][j],
                                data.pebblesY[clump_index][j],
                                data.pebblesZ[clump_index][j]),
                          data.pebblesR[clump_index][j]);
         }
         p0.setPrincipalDirections(
                 Matrix3D(data.pd[clump_index][0], data.pd[clump_index][1], data.pd[clump_index][2],
                          data.pd[clump_index][3], data.pd[clump_index][4], data.pd[clump_index][5],
                          data.pd[clump_index][6], data.pd[clump_index][7], data.pd[clump_index][8]));
         p0.setInitInertia(
                 MatrixSymmetric3D(data.toi[clump_index][0], data.toi[clump_index][1], data.toi[clump_index][2],
                                   data.toi[clump_index][4], data.toi[clump_index][5],
                                   data.toi[clump_index][8]));
         p0.setClumpMass(data.mass[clump_index]);
         double mag = 0;
         p0.setAngularVelocity(Vec3D(0,0,0));
         p0.setVelocity(Vec3D(0,0,0));
         p0.setDamping(clump_damping);
         particleHandler.copyAndAddObject(p0);
         // Rectangular box
         wallHandler.clear();
         InfiniteWall w0;
         w0.setSpecies(speciesHandler.getObject(0));
         w0.set(Vec3D(-1.0, 0.0, 0.0), Vec3D(getXMin(), 0, 0));
         wallHandler.copyAndAddObject(w0);
         w0.set(Vec3D(1.0, 0.0, 0.0), Vec3D(getXMax(), 0, 0));
         wallHandler.copyAndAddObject(w0);
         w0.set(Vec3D(0.0, -1.0, 0.0), Vec3D(0, getYMin(), 0));
         wallHandler.copyAndAddObject(w0);
         w0.set(Vec3D(0.0, 1.0, 0.0), Vec3D(0, getYMax(), 0));
         wallHandler.copyAndAddObject(w0);
         w0.set(Vec3D(0.0, 0.0, -1.0), Vec3D(0, 0, getZMin()));
         wallHandler.copyAndAddObject(w0);
         w0.set(Vec3D(0.0, 0.0, 1.0), Vec3D(0, 0, getZMax()));
         wallHandler.copyAndAddObject(w0);
     }
References BaseHandler< T >::clear(), clump_damping, clump_index, BaseHandler< T >::copyAndAddObject(), data, BaseHandler< T >::getObject(), DPMBase::getXMax(), DPMBase::getXMin(), DPMBase::getYMax(), DPMBase::getYMin(), DPMBase::getZMax(), DPMBase::getZMin(), j, ClumpData::mass, p0, DPMBase::particleHandler, ClumpData::pd, ClumpData::pebblesR, ClumpData::pebblesX, ClumpData::pebblesY, ClumpData::pebblesZ, RotateClump(), InfiniteWall::set(), setClumpIndex(), BaseWall::setSpecies(), DPMBase::speciesHandler, ClumpData::toi, and DPMBase::wallHandler.
setupInitialConditions() [4/8]
void ChangingTOIParticle::setupInitialConditions () inline override virtual
This function allows to set the initial conditions for our problem to be solved, by default particle locations are randomly set. Remember particle properties must also be defined here.
A virtual function with no implementation but can be overridden.
Todo:
I (Anthony) wants to change this to be an external function. This has a lot of advantages especially when using copy-constructors. This is a major change and will break other codes, so therefore has to be done carefully.
This sets up the particles initial conditions it is as you expect the user to override this. By default the particles are randomly distributed
Reimplemented from DPMBase.
     {
         // Generate rattleback
         setClumpIndex(3);
         ClumpParticle p0;
         p0.setSpecies(speciesHandler.getObject(0)); // Assign the material type to Clump 1
         p0.setClump();
         //DoubleVector upds = UniformRandomPDs();
         DoubleVector upds = {1, 0, 0, 0, 0, 1, 0, -1, 0};
         data = RotateClump(data, clump_index, upds); // here you can try different seeds
         p0.setRadius(data.pebblesR[clump_index][0]);
         Vec3D pos = Vec3D(0, 0, -94);
         p0.setPosition(pos);
         for (int j = 0; j < data.pebblesR[clump_index].size(); j++) {
             p0.addPebble(Vec3D(data.pebblesX[clump_index][j],
                                data.pebblesY[clump_index][j],
                                data.pebblesZ[clump_index][j]),
                          data.pebblesR[clump_index][j]);
         }
         p0.setPrincipalDirections(
                 Matrix3D(data.pd[clump_index][0], data.pd[clump_index][1], data.pd[clump_index][2],
                          data.pd[clump_index][3], data.pd[clump_index][4], data.pd[clump_index][5],
                          data.pd[clump_index][6], data.pd[clump_index][7], data.pd[clump_index][8]));
         p0.setInitInertia(
                 MatrixSymmetric3D(data.toi[clump_index][0], data.toi[clump_index][1], data.toi[clump_index][2],
                                   data.toi[clump_index][4], data.toi[clump_index][5],
                                   data.toi[clump_index][8]));
         p0.setClumpMass(data.mass[clump_index]);
         double mag = 0;
         p0.setAngularVelocity(Vec3D(0,0,-0.7));
         p0.setVelocity(Vec3D(0,0,0));
         p0.setDamping(clump_damping);
         particleHandler.copyAndAddObject(p0);
         // Rectangular box
         wallHandler.clear();
         InfiniteWall w0;
         w0.setSpecies(speciesHandler.getObject(0));
         w0.set(Vec3D(-1.0, 0.0, 0.0), Vec3D(getXMin(), 0, 0));
         wallHandler.copyAndAddObject(w0);
         w0.set(Vec3D(1.0, 0.0, 0.0), Vec3D(getXMax(), 0, 0));
         wallHandler.copyAndAddObject(w0);
         w0.set(Vec3D(0.0, -1.0, 0.0), Vec3D(0, getYMin(), 0));
         wallHandler.copyAndAddObject(w0);
         w0.set(Vec3D(0.0, 1.0, 0.0), Vec3D(0, getYMax(), 0));
         wallHandler.copyAndAddObject(w0);
         w0.set(Vec3D(0.0, 0.0, -1.0), Vec3D(0, 0, getZMin()));
         wallHandler.copyAndAddObject(w0);
         w0.set(Vec3D(0.0, 0.0, 1.0), Vec3D(0, 0, getZMax()));
         wallHandler.copyAndAddObject(w0);
     }
References BaseHandler< T >::clear(), clump_damping, clump_index, BaseHandler< T >::copyAndAddObject(), data, BaseHandler< T >::getObject(), DPMBase::getXMax(), DPMBase::getXMin(), DPMBase::getYMax(), DPMBase::getYMin(), DPMBase::getZMax(), DPMBase::getZMin(), j, ClumpData::mass, p0, DPMBase::particleHandler, ClumpData::pd, ClumpData::pebblesR, ClumpData::pebblesX, ClumpData::pebblesY, ClumpData::pebblesZ, RotateClump(), InfiniteWall::set(), setClumpIndex(), BaseWall::setSpecies(), DPMBase::speciesHandler, ClumpData::toi, and DPMBase::wallHandler.
setupInitialConditions() [5/8]
void ChangingTOIParticle::setupInitialConditions () inline override virtual
This function allows to set the initial conditions for our problem to be solved, by default particle locations are randomly set. Remember particle properties must also be defined here.
A virtual function with no implementation but can be overridden.
Todo:
I (Anthony) wants to change this to be an external function. This has a lot of advantages especially when using copy-constructors. This is a major change and will break other codes, so therefore has to be done carefully.
This sets up the particles initial conditions it is as you expect the user to override this. By default the particles are randomly distributed
Reimplemented from DPMBase.
     {
         setClumpIndex(2);
         int N_created = 0;
         for (int part = 0; part<N_att; part++) {
             ClumpParticle p0;
             p0.setSpecies(speciesHandler.getObject(0)); // Assign the material type to Clump 1
             p0.setClump();
             ClumpData rdata = RotateClump(data, clump_index, UniformRandomPDs()); // Rotate clump arbitrarily
             p0.setRadius(rdata.pebblesR[clump_index][0]);
             for (int j = 0; j < rdata.pebblesR[clump_index].size(); j++) {
                 p0.addPebble(Vec3D(rdata.pebblesX[clump_index][j],
                                    rdata.pebblesY[clump_index][j],
                                    rdata.pebblesZ[clump_index][j]),
                              rdata.pebblesR[clump_index][j]);
             }
             p0.setPrincipalDirections(
                     Matrix3D(rdata.pd[clump_index][0], rdata.pd[clump_index][1], rdata.pd[clump_index][2],
                              rdata.pd[clump_index][3], rdata.pd[clump_index][4], rdata.pd[clump_index][5],
                              rdata.pd[clump_index][6], rdata.pd[clump_index][7], rdata.pd[clump_index][8]));
             p0.setInitInertia(
                     MatrixSymmetric3D(rdata.toi[clump_index][0], rdata.toi[clump_index][1], rdata.toi[clump_index][2],
                                       rdata.toi[clump_index][4], rdata.toi[clump_index][5],
                                       rdata.toi[clump_index][8]));
             p0.setClumpMass(rdata.mass[clump_index]);
             p0.setDamping(clump_damping);
             Vec3D pos = Vec3D(f_min + margin + RandomDouble(f_max - f_min - 2 * margin),
                               f_min + margin + RandomDouble(f_max - f_min - 2 * margin),
                               z_shift + f_min + z_margin + RandomDouble(f_max - f_min - 2 * z_margin));
             p0.setPosition(pos);
             Vec3D angVel = Vec3D(av_min + RandomDouble(av_max - av_min),
                                  av_min + RandomDouble(av_max - av_min),
                                  av_min + RandomDouble(av_max - av_min));
             Vec3D vel = Vec3D(tv_min + RandomDouble(tv_max - tv_min),
                               tv_min + RandomDouble(tv_max - tv_min),
                               tv_min + RandomDouble(tv_max - tv_min));
             p0.setAngularVelocity(angVel);
             p0.setVelocity(vel);
             if (checkClumpForInteractionPeriodic(p0)) {
                 particleHandler.copyAndAddObject(p0);
                 N_created++;
             }
         }
         std::cout<<"N_created = "<<N_created<<std::endl;
         // Introduce a rotating wall
         Mdouble wallScaleFactor = 1e-3; // Scale used in the stl file (mm)
         Vec3D shift = {0,0,0};
         Vec3D velocity = {0,0,0};
         rotatingWallID = wallHandler.readTriangleWall(getMercuryDPMSourceDir() + "/Drivers/Clump/RotatingDrum/RotatingDrum.stl",speciesHandler.getObject(0), wallScaleFactor,shift,velocity,Vec3D(0,0,0));
         wallHandler.setWriteVTK(true);
     }
References av_max, av_min, Mercury3Dclump::checkClumpForInteractionPeriodic(), clump_damping, clump_index, BaseHandler< T >::copyAndAddObject(), data, e(), f_max, f_min, getMercuryDPMSourceDir(), BaseHandler< T >::getObject(), j, margin, ClumpData::mass, N_att, p0, DPMBase::particleHandler, ClumpData::pd, ClumpData::pebblesR, ClumpData::pebblesX, ClumpData::pebblesY, ClumpData::pebblesZ, RandomDouble(), WallHandler::readTriangleWall(), RotateClump(), rotatingWallID, setClumpIndex(), WallHandler::setWriteVTK(), DPMBase::speciesHandler, ClumpData::toi, tv_max, tv_min, UniformRandomPDs(), Jeffery_Solution::velocity(), DPMBase::wallHandler, z_margin, and z_shift.
setupInitialConditions() [6/8]
void ChangingTOIParticle::setupInitialConditions () inline override virtual
This function allows to set the initial conditions for our problem to be solved, by default particle locations are randomly set. Remember particle properties must also be defined here.
A virtual function with no implementation but can be overridden.
Todo:
I (Anthony) wants to change this to be an external function. This has a lot of advantages especially when using copy-constructors. This is a major change and will break other codes, so therefore has to be done carefully.
This sets up the particles initial conditions it is as you expect the user to override this. By default the particles are randomly distributed
Reimplemented from DPMBase.
     {
         // Generate single clump
         setClumpIndex(0);
         ClumpParticle p0;
         p0.setSpecies(speciesHandler.getObject(0)); // Assign the material type to Clump 1
         p0.setClump();
         // data = RotateClump(data, clump_index, UniformRandomPDs()); // Rotate clump arbitrarily
         p0.setRadius(data.pebblesR[clump_index][0]);
         Vec3D pos = Vec3D(0, 0, 5);
         p0.setPosition(pos);
         for (int j = 0; j < data.pebblesR[clump_index].size(); j++) {
             p0.addPebble(Vec3D(data.pebblesX[clump_index][j],
                                data.pebblesY[clump_index][j],
                                data.pebblesZ[clump_index][j]),
                          data.pebblesR[clump_index][j]);
         }
         p0.setPrincipalDirections(
                     Matrix3D(data.pd[clump_index][0], data.pd[clump_index][1], data.pd[clump_index][2],
                              data.pd[clump_index][3], data.pd[clump_index][4], data.pd[clump_index][5],
                              data.pd[clump_index][6], data.pd[clump_index][7], data.pd[clump_index][8]));
         p0.setInitInertia(
                     MatrixSymmetric3D(data.toi[clump_index][0], data.toi[clump_index][1], data.toi[clump_index][2],
                                       data.toi[clump_index][4], data.toi[clump_index][5],
                                       data.toi[clump_index][8]));
         std::cout<<"CLUMP MASS set = "<<data.mass[clump_index]<<std::endl;
         p0.setClumpMass(data.mass[clump_index]);
         p0.setAngularVelocity(Vec3D(0,5,0));
         p0.setVelocity(Vec3D(4,0,10));
         std::cout<<"CLUMP MASS get = "<<p0.getMass()<<std::endl;
         p0.setDamping(clump_damping);
         particleHandler.copyAndAddObject(p0);
         // Rectangular box
         wallHandler.clear();
         InfiniteWall w0;
         w0.setSpecies(speciesHandler.getObject(0));
         w0.set(Vec3D(-1.0, 0.0, 0.0), Vec3D(getXMin(), 0, 0));
         wallHandler.copyAndAddObject(w0);
         w0.set(Vec3D(1.0, 0.0, 0.0), Vec3D(getXMax(), 0, 0));
         wallHandler.copyAndAddObject(w0);
         w0.set(Vec3D(0.0, -1.0, 0.0), Vec3D(0, getYMin(), 0));
         wallHandler.copyAndAddObject(w0);
         w0.set(Vec3D(0.0, 1.0, 0.0), Vec3D(0, getYMax(), 0));
         wallHandler.copyAndAddObject(w0);
         w0.set(Vec3D(0.0, 0.0, -1.0), Vec3D(0, 0, getZMin()));
         wallHandler.copyAndAddObject(w0);
         w0.set(Vec3D(0.0, 0.0, 1.0), Vec3D(0, 0, getZMax()));
         wallHandler.copyAndAddObject(w0);
     }
References BaseHandler< T >::clear(), clump_damping, clump_index, BaseHandler< T >::copyAndAddObject(), data, BaseHandler< T >::getObject(), DPMBase::getXMax(), DPMBase::getXMin(), DPMBase::getYMax(), DPMBase::getYMin(), DPMBase::getZMax(), DPMBase::getZMin(), j, ClumpData::mass, p0, DPMBase::particleHandler, ClumpData::pd, ClumpData::pebblesR, ClumpData::pebblesX, ClumpData::pebblesY, ClumpData::pebblesZ, InfiniteWall::set(), setClumpIndex(), BaseWall::setSpecies(), DPMBase::speciesHandler, ClumpData::toi, and DPMBase::wallHandler.
setupInitialConditions() [7/8]
void ChangingTOIParticle::setupInitialConditions () inline override virtual
This function allows to set the initial conditions for our problem to be solved, by default particle locations are randomly set. Remember particle properties must also be defined here.
A virtual function with no implementation but can be overridden.
Todo:
I (Anthony) wants to change this to be an external function. This has a lot of advantages especially when using copy-constructors. This is a major change and will break other codes, so therefore has to be done carefully.
This sets up the particles initial conditions it is as you expect the user to override this. By default the particles are randomly distributed
Reimplemented from DPMBase.
     {
         // Generate single clump
         setClumpIndex(1);
         ClumpParticle p0;
         p0.setSpecies(speciesHandler.getObject(0)); // Assign the material type to Clump 1
         p0.setClump();
         DoubleVector urpds = {0.707, 0.707, 0, -0.707, 0.707, 0, 0, 0, 1};
         // DoubleVector urpds = UniformRandomPDs();
         Vec3D angVel = 2 * Vec3D( urpds[0], urpds[1], urpds[2]);
         data = RotateClump(data, clump_index, urpds); // Rotate clump arbitrarily
         p0.setRadius(data.pebblesR[clump_index][0]);
         Vec3D pos = Vec3D(0, 0, 0);
         p0.setPosition(pos);
         //p0.setInitPrincipalDirections(
         //        Matrix3D(data.pd[clump_index][0], data.pd[clump_index][1], data.pd[clump_index][2],
         //                 data.pd[clump_index][3], data.pd[clump_index][4], data.pd[clump_index][5],
         //                 data.pd[clump_index][6], data.pd[clump_index][7], data.pd[clump_index][8]));
         p0.setPrincipalDirections(
                     Matrix3D(data.pd[clump_index][0], data.pd[clump_index][1], data.pd[clump_index][2],
                              data.pd[clump_index][3], data.pd[clump_index][4], data.pd[clump_index][5],
                              data.pd[clump_index][6], data.pd[clump_index][7], data.pd[clump_index][8]));
         p0.setInitInertia(
                     MatrixSymmetric3D(data.toi[clump_index][0], data.toi[clump_index][1], data.toi[clump_index][2],
                                       data.toi[clump_index][4], data.toi[clump_index][5],
                                       data.toi[clump_index][8]));
         for (int j = 0; j < data.pebblesR[clump_index].size(); j++) {
             p0.addPebble(Vec3D(data.pebblesX[clump_index][j],
                                data.pebblesY[clump_index][j],
                                data.pebblesZ[clump_index][j]),
                          data.pebblesR[clump_index][j]);
         }
         std::cout<<"CLUMP MASS set = "<<data.mass[clump_index]<<std::endl;
         p0.setClumpMass(data.mass[clump_index]);
         p0.setAngularVelocity(angVel);
         std::cout<<"CLUMP MASS get = "<<p0.getMass()<<std::endl;
         p0.setDamping(clump_damping);
         particleHandler.copyAndAddObject(p0);
         // Rectangular box
         wallHandler.clear();
         InfiniteWall w0;
         w0.setSpecies(speciesHandler.getObject(0));
         w0.set(Vec3D(-1.0, 0.0, 0.0), Vec3D(getXMin(), 0, 0));
         wallHandler.copyAndAddObject(w0);
         w0.set(Vec3D(1.0, 0.0, 0.0), Vec3D(getXMax(), 0, 0));
         wallHandler.copyAndAddObject(w0);
         w0.set(Vec3D(0.0, -1.0, 0.0), Vec3D(0, getYMin(), 0));
         wallHandler.copyAndAddObject(w0);
         w0.set(Vec3D(0.0, 1.0, 0.0), Vec3D(0, getYMax(), 0));
         wallHandler.copyAndAddObject(w0);
         w0.set(Vec3D(0.0, 0.0, -1.0), Vec3D(0, 0, getZMin()));
         wallHandler.copyAndAddObject(w0);
         w0.set(Vec3D(0.0, 0.0, 1.0), Vec3D(0, 0, getZMax()));
         wallHandler.copyAndAddObject(w0);
     }
References BaseHandler< T >::clear(), clump_damping, clump_index, BaseHandler< T >::copyAndAddObject(), data, BaseHandler< T >::getObject(), DPMBase::getXMax(), DPMBase::getXMin(), DPMBase::getYMax(), DPMBase::getYMin(), DPMBase::getZMax(), DPMBase::getZMin(), j, ClumpData::mass, p0, DPMBase::particleHandler, ClumpData::pd, ClumpData::pebblesR, ClumpData::pebblesX, ClumpData::pebblesY, ClumpData::pebblesZ, RotateClump(), InfiniteWall::set(), setClumpIndex(), BaseWall::setSpecies(), DPMBase::speciesHandler, ClumpData::toi, and DPMBase::wallHandler.
setupInitialConditions() [8/8]
void ChangingTOIParticle::setupInitialConditions () inline override virtual
This function allows to set the initial conditions for our problem to be solved, by default particle locations are randomly set. Remember particle properties must also be defined here.
A virtual function with no implementation but can be overridden.
Todo:
I (Anthony) wants to change this to be an external function. This has a lot of advantages especially when using copy-constructors. This is a major change and will break other codes, so therefore has to be done carefully.
This sets up the particles initial conditions it is as you expect the user to override this. By default the particles are randomly distributed
Reimplemented from DPMBase.
     {
         setParticlesWriteVTK(1);
         /* Double periodic + bottom wall + unlimited top
         auto per_x = boundaryHandler.copyAndAddObject(new PeriodicBoundary);
         per_x->set(Vec3D(1, 0, 0), getXMin(), getXMax());
         auto per_y = boundaryHandler.copyAndAddObject(new PeriodicBoundary);
         per_y->set(Vec3D(0, 1, 0), getYMin(), getYMax());
         wallHandler.clear();
         InfiniteWall w0;
         w0.set(Vec3D(0.0, 0.0, -1.0), Vec3D(0, 0, getZMin()));
         wallHandler.copyAndAddObject(w0);
         */
         /* Rectangular box
         wallHandler.clear();
         InfiniteWall w0;
         w0.setSpecies(speciesHandler.getObject(0));
         w0.set(Vec3D(-1.0, 0.0, 0.0), Vec3D(getXMin(), 0, 0));
         wallHandler.copyAndAddObject(w0);
         w0.set(Vec3D(1.0, 0.0, 0.0), Vec3D(getXMax(), 0, 0));
         wallHandler.copyAndAddObject(w0);
         w0.set(Vec3D(0.0, -1.0, 0.0), Vec3D(0, getYMin(), 0));
         wallHandler.copyAndAddObject(w0);
         w0.set(Vec3D(0.0, 1.0, 0.0), Vec3D(0, getYMax(), 0));
         wallHandler.copyAndAddObject(w0);
         w0.set(Vec3D(0.0, 0.0, -1.0), Vec3D(0, 0, getZMin()));
         wallHandler.copyAndAddObject(w0);
         w0.set(Vec3D(0.0, 0.0, 1.0), Vec3D(0, 0, getZMax()));
         wallHandler.copyAndAddObject(w0);
         */
         // Periodic box
         auto per_x = boundaryHandler.copyAndAddObject(new PeriodicBoundary);
         per_x->set(Vec3D(1, 0, 0), getXMin(), getXMax());
         auto per_y = boundaryHandler.copyAndAddObject(new PeriodicBoundary);
         per_y->set(Vec3D(0, 1, 0), getYMin(), getYMax());
         auto per_z = boundaryHandler.copyAndAddObject(new PeriodicBoundary);
         per_z->set(Vec3D(0, 0, 1), getZMin(), getZMax());
         /*
         SphericalParticle p0;
         p0.setSpecies(speciesHandler.getObject(0));
         p0.setRadius(1); // sets particle radius
         p0.setPosition(Vec3D(0., 0., 0.)); // sets particle position
         p0.setVelocity(Vec3D(0., 0., 0.));// sets particle velocity
         particleHandler.copyAndAddObject(p0);
         */
         // Generate a dense packing of Clumps
         setClumpIndex(1);
         int N_created = 0;
         for (int part = 0; part<N_att; part++) {
                 ClumpParticle p0;
                 p0.setSpecies(speciesHandler.getObject(0)); // Assign the material type to Clump 1
             p0.setClump();
                 ClumpData rdata = RotateClump(data, clump_index, UniformRandomPDs()); // Rotate clump arbitrarily
                 p0.setRadius(rdata.pebblesR[clump_index][0]);
                 for (int j = 0; j < rdata.pebblesR[clump_index].size(); j++) {
                     p0.addPebble(Vec3D(rdata.pebblesX[clump_index][j],
                                        rdata.pebblesY[clump_index][j],
                                        rdata.pebblesZ[clump_index][j]),
                                  rdata.pebblesR[clump_index][j]);
                 }
                 p0.setPrincipalDirections(
                         Matrix3D(rdata.pd[clump_index][0], rdata.pd[clump_index][1], rdata.pd[clump_index][2],
                                  rdata.pd[clump_index][3], rdata.pd[clump_index][4], rdata.pd[clump_index][5],
                                  rdata.pd[clump_index][6], rdata.pd[clump_index][7], rdata.pd[clump_index][8]));
                 p0.setInitInertia(
                         MatrixSymmetric3D(rdata.toi[clump_index][0], rdata.toi[clump_index][1], rdata.toi[clump_index][2],
                                           rdata.toi[clump_index][4], rdata.toi[clump_index][5],
                                           rdata.toi[clump_index][8]));
             p0.setClumpMass(rdata.mass[clump_index]);
                 p0.setDamping(clump_damping);
                 Vec3D pos = Vec3D(f_min + margin + RandomDouble(f_max - f_min - 2 * margin),
                                   f_min + margin + RandomDouble(f_max - f_min - 2 * margin),
                                   f_min + margin + RandomDouble(f_max - f_min - 2 * margin));
                 p0.setPosition(pos);
                 Vec3D angVel = Vec3D(av_min + RandomDouble(av_max - av_min),
                                      av_min + RandomDouble(av_max - av_min),
                                      av_min + RandomDouble(av_max - av_min));
                 Vec3D vel = Vec3D(tv_min + RandomDouble(tv_max - tv_min),
                                   tv_min + RandomDouble(tv_max - tv_min),
                                   tv_min + RandomDouble(tv_max - tv_min));
                 // No motion with zero initial conditions
                 //angVel = Vec3D(0,0,0);
                 //vel = Vec3D(0,0,0);
                 p0.setAngularVelocity(angVel);
                 p0.setVelocity(vel);
                 if (checkClumpForInteractionPeriodic(p0)) {
                     particleHandler.copyAndAddObject(p0);
                     N_created++;
                 }
             }
         std::cout<<"Number of particles created: "<<N_created<<std::endl;
     }
References av_max, av_min, DPMBase::boundaryHandler, Mercury3Dclump::checkClumpForInteractionPeriodic(), clump_damping, clump_index, BaseHandler< T >::copyAndAddObject(), data, f_max, f_min, BaseHandler< T >::getObject(), DPMBase::getXMax(), DPMBase::getXMin(), DPMBase::getYMax(), DPMBase::getYMin(), DPMBase::getZMax(), DPMBase::getZMin(), j, margin, ClumpData::mass, N_att, p0, DPMBase::particleHandler, ClumpData::pd, ClumpData::pebblesR, ClumpData::pebblesX, ClumpData::pebblesY, ClumpData::pebblesZ, RandomDouble(), RotateClump(), setClumpIndex(), DPMBase::setParticlesWriteVTK(), DPMBase::speciesHandler, ClumpData::toi, tv_max, tv_min, and UniformRandomPDs().
StoM()
Matrix3D ChangingTOIParticle::StoM (MatrixSymmetric3D M) inline
 { return Matrix3D(M.XX, M.XY, M.XZ, M.XY, M.YY, M.YZ, M.XZ, M.YZ, M.ZZ);}
Referenced by actionsAfterTimeStep().
transpose()
Matrix3D ChangingTOIParticle::transpose (Matrix3D M) inline
 { return Matrix3D(M.XX, M.YX, M.ZX, M.XY, M.YY, M.ZY, M.XZ, M.YZ, M.ZZ);}
Referenced by actionsAfterTimeStep().
Member Data Documentation
angularMomentumLog
DoubleVector ChangingTOIParticle::angularMomentumLog
Referenced by actionsAfterTimeStep().
baseAngVel
Mdouble ChangingTOIParticle::baseAngVel = 0
Referenced by setupInitialConditions().
c_phi
Mdouble ChangingTOIParticle::c_phi
Referenced by actionsAfterTimeStep().
c_theta
Mdouble ChangingTOIParticle::c_theta
Referenced by actionsAfterTimeStep().
clump_damping
Mdouble ChangingTOIParticle::clump_damping = 10 private
Referenced by setClumpDamping(), and setupInitialConditions().
clump_index
int ChangingTOIParticle::clump_index private
Referenced by ChangingTOIParticle(), setClumpIndex(), and setupInitialConditions().
clump_mass
Mdouble ChangingTOIParticle::clump_mass private
Referenced by ChangingTOIParticle(), and getClumpMass().
data
ClumpData ChangingTOIParticle::data private
Referenced by ChangingTOIParticle(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), setupInitialConditions(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
final_orientation
Vec3D ChangingTOIParticle::final_orientation = Vec3D(1,0,0)
Referenced by actionsAfterTimeStep().
functional
Mdouble ChangingTOIParticle::functional = 0
Referenced by actionsAfterTimeStep().
inertia_profiles
Double2DVector ChangingTOIParticle::inertia_profiles
Referenced by actionsAfterTimeStep(), and setupInitialConditions().
init_orientation
Vec3D ChangingTOIParticle::init_orientation = Vec3D(1,0,0)
Referenced by setupInitialConditions().
insertionBoundary
CubeInsertionBoundary* ChangingTOIParticle::insertionBoundary private
progDuration
Mdouble ChangingTOIParticle::progDuration = 0
Referenced by actionsAfterTimeStep().
rotatingWallID
unsigned ChangingTOIParticle::rotatingWallID = 0 private
Referenced by actionsAfterTimeStep(), and setupInitialConditions().
symDuration
Mdouble ChangingTOIParticle::symDuration = 0
The documentation for this class was generated from the following files:
ChangingTOI.cpp
Domino.cpp
Gomboc.cpp
Rattleback.cpp
RotatingDrumClumps.cpp
Single.cpp
TBar.cpp
TGas.cpp