MercuryDPM: helical_pipe.cc File Reference
helical_pipe.cc File Reference
#include "generic.h"
#include "navier_stokes.h"
#include "meshes/tube_mesh.h"
Classes
class MyHelicalCylinder
class SteadyHelicalProblem< ELEMENT >
Entry flow problem in tapered tube domain.
Namespaces
Global_Physical_Variables
Global variables.
Functions
int main (int argc, char *argv[])
Variables
double Global_Physical_Variables::Pitch = 1.0
Function Documentation
main()
int main (int argc , char * argv[])
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// Driver for 3D entry flow into a tapered tube. If there are any command line arguments, we regard this as a validation run and perform only a single adaptation
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Allow (up to) two rounds of fully automatic adapation in response to
  //-----------------------------------------------------------------------
  // error estimate
  //---------------
  unsigned max_adapt;
  double max_error_target,min_error_target;
  // Set max number of adaptations in black-box Newton solver and
  // error targets for adaptation
  if (CommandLineArgs::Argc==1)
   {
    // Up to two adaptations
    max_adapt=2;
    // Error targets for adaptive refinement
    max_error_target=0.005;
    min_error_target=0.0005;
   }
  // Validation run: Only one adaptation. Relax error targets
  // to ensure that not all elements are refined so we're getting
  // some hanging nodes.
  else
   {
    // Validation run: Just one round of adaptation
    max_adapt=1;
    // Error targets for adaptive refinement
    max_error_target=0.02;
    min_error_target=0.002;
   }
  // end max_adapt setup
  // Set up doc info
  DocInfo doc_info;
  // Do Taylor-Hood elements
  //------------------------
  {
   // Set output directory
   doc_info.set_directory("RESLT_TH");
   // Step number
   doc_info.number()=0;
   // Build problem
   SteadyHelicalProblem<RefineableQTaylorHoodElement<3> >
    problem(doc_info,min_error_target,max_error_target);
   cout << " Doing Taylor-Hood elements " << std::endl;
   // Solve the problem
   problem.newton_solve(max_adapt);
   // Doc solution after solving
   problem.doc_solution();
  }
  // Do Crouzeix-Raviart elements
  //------------------------
  {
   // Set output directory
   doc_info.set_directory("RESLT_CR");
   // Step number
   doc_info.number()=0;
   // Build problem
   SteadyHelicalProblem<RefineableQCrouzeixRaviartElement<3> >
    problem(doc_info,min_error_target,max_error_target);
   cout << " Doing Crouzeix-Raviart elements " << std::endl;
   // Solve the problem
   problem.newton_solve(max_adapt);
   // Doc solution after solving
   problem.doc_solution();
  }
 } // end_of_main
References oomph::CommandLineArgs::Argc, oomph::DocInfo::number(), problem, oomph::DocInfo::set_directory(), and Flag_definition::setup().