MercuryDPM: resize.cpp File Reference
resize.cpp File Reference
#include "main.h"
Functions
template<DenseIndex rows, DenseIndex cols>
void resizeLikeTest ()
void resizeLikeTest12 ()
void resizeLikeTest1020 ()
void resizeLikeTest31 ()
EIGEN_DECLARE_TEST (resize)
Function Documentation
EIGEN_DECLARE_TEST()
EIGEN_DECLARE_TEST (resize)
{
   CALL_SUBTEST(resizeLikeTest12());
   CALL_SUBTEST(resizeLikeTest1020());
   CALL_SUBTEST(resizeLikeTest31());
 }
References CALL_SUBTEST, resizeLikeTest1020(), resizeLikeTest12(), and resizeLikeTest31().
resizeLikeTest()
template<DenseIndex rows, DenseIndex cols> void resizeLikeTest ()
                       {
   MatrixXf A(rows, cols);
   MatrixXf B;
   Matrix<double, rows, cols> C;
   B.resizeLike(A);
   C.resizeLike(B);  // Shouldn't crash.
   VERIFY(B.rows() == rows && B.cols() == cols);
   VectorXf x(rows);
   RowVectorXf y;
   y.resizeLike(x);
   VERIFY(y.rows() == 1 && y.cols() == rows);
   y.resize(cols);
   x.resizeLike(y);
   VERIFY(x.rows() == cols && x.cols() == 1);
 }
References cols, rows, VERIFY, plotDoE::x, and y.
resizeLikeTest1020()
void resizeLikeTest1020 ()
 { resizeLikeTest<10, 20>(); }
Referenced by EIGEN_DECLARE_TEST().
resizeLikeTest12()
void resizeLikeTest12 ()
 { resizeLikeTest<1, 2>(); }
Referenced by EIGEN_DECLARE_TEST().
resizeLikeTest31()
void resizeLikeTest31 ()
 { resizeLikeTest<3, 1>(); }
Referenced by EIGEN_DECLARE_TEST().