MercuryDPM: ObliqueImpactSelfTest.cpp File Reference
ObliqueImpactSelfTest.cpp File Reference
#include "Mercury2D.h"
#include "Walls/InfiniteWall.h"
#include <Species/HertzianViscoelasticMindlinSpecies.h>
Classes
class ObliqueImpactSelfTest
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
 {
     logger(INFO, "Single particle hitting the bottom plate in an oblique impact");
     // Make the problem and set the name
     ObliqueImpactSelfTest ObliqueImpactSelfTestProblem;
     ObliqueImpactSelfTestProblem.setName("ObliqueImpactSelfTest");
     //Set the species of the particle and wall, and its properties
     HertzianViscoelasticMindlinSpecies species;
     species.setDensity(6./constants::pi);
     ObliqueImpactSelfTestProblem.setParticleDimensions(3);
     species.setEffectiveElasticModulusAndPoissonRatio(1e5, 0.3);
 //    species.setDissipation(0.2);
 //    species.setSlidingDissipation(0.9);
     species.setSlidingFrictionCoefficient(0.1);
     ObliqueImpactSelfTestProblem.speciesHandler.copyAndAddObject(species);
     //set the parameters for the solver
     ObliqueImpactSelfTestProblem.setSaveCount(500);
     ObliqueImpactSelfTestProblem.setFileType(FileType::ONE_FILE);
     ObliqueImpactSelfTestProblem.fStatFile.setFileType(FileType::ONE_FILE);
 //    ObliqueImpactSelfTestProblem.wallHandler.setWriteVTK(FileType::NO_FILE);
     ObliqueImpactSelfTestProblem.setTimeStep(0.25e-8);
     //solve the system, the single particle will now bounce on the plate
     ObliqueImpactSelfTestProblem.solve(argc, argv);
     helpers::writeToFile(ObliqueImpactSelfTestProblem.getName() + ".gnu", "plot '" + ObliqueImpactSelfTestProblem.getName() + ".fstat' u 8:($10*$14) w lp");
     logger(INFO, "finished oblique impact test: run 'gnuplot %.gnu' to view output", ObliqueImpactSelfTestProblem.getName());
 }
References BaseHandler< T >::copyAndAddObject(), DPMBase::fStatFile, DPMBase::getName(), INFO, logger, ONE_FILE, constants::pi, ParticleSpecies::setDensity(), DPMBase::setFileType(), File::setFileType(), DPMBase::setName(), DPMBase::setParticleDimensions(), DPMBase::setSaveCount(), DPMBase::setTimeStep(), DPMBase::solve(), DPMBase::speciesHandler, and helpers::writeToFile().