MercuryDPM: two_d_multi_poisson.cc File Reference
linear_solvers/two_d_multi_poisson.cc File Reference
#include <fenv.h>
#include "generic.h"
#include "meshes/simple_rectangular_quadmesh.h"
#include "multi_poisson_elements.h"
#include "multi_poisson_block_preconditioners.h"
Classes
class MultiPoissonProblem< ELEMENT >
Namespaces
TanhSolnForMultiPoisson
Namespace for exact solution for MultiPoisson equation with "sharp step".
Macros
#define N_FIELD 5
Functions
double TanhSolnForMultiPoisson::scalar_soln (const Vector< double > &x)
Scalar solution.
double TanhSolnForMultiPoisson::scalar_source (const Vector< double > &x)
Scalar source.
void TanhSolnForMultiPoisson::get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void TanhSolnForMultiPoisson::source_function (const Vector< double > &x, Vector< double > &source)
Source function required to make the solution above an exact solution.
int main (int argc, char *argv[])
Driver code for 2D MultiPoisson problem.
Variables
double TanhSolnForMultiPoisson::Alpha =5.0
Parameter for steepness of "step".
double TanhSolnForMultiPoisson::TanPhi =1.0
Parameter for angle Phi of "step" (45 degrees)
double TanhSolnForMultiPoisson::Beta =1.0
Interaction parameter.
Macro Definition Documentation
N_FIELD
#define N_FIELD 5
Function Documentation
main()
int main (int argc , char * argv[])
Driver code for 2D MultiPoisson problem.
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Define possible command line arguments and parse the ones that
  // were actually specified
  CommandLineArgs::specify_command_line_flag("--simple");
  CommandLineArgs::specify_command_line_flag
   ("--upper_triangular");
  CommandLineArgs::specify_command_line_flag
   ("--two_plus_three");
  CommandLineArgs::specify_command_line_flag
   ("--two_plus_three_upper_triangular");
  CommandLineArgs::specify_command_line_flag
   ("--two_plus_three_upper_triangular_with_sub");
  CommandLineArgs::specify_command_line_flag
   ("--two_plus_three_upper_triangular_with_two_sub");
  CommandLineArgs::specify_command_line_flag
   ("--two_plus_three_upper_triangular_with_replace");
  CommandLineArgs::specify_command_line_flag
   ("--coarse_two_plus_two_plus_one");
  CommandLineArgs::specify_command_line_flag
   ("--one_plus_four_with_two_coarse");
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  // Create the problem with 2D nine-node elements from the
  // QMultiPoissonElement family.
  MultiPoissonProblem<QMultiPoissonElement<2,3,N_FIELD> > problem;
  // Create label for output
  DocInfo doc_info;
  // Set output directory
  doc_info.set_directory("RESLT");
  // Step number
  doc_info.number()=0;
  oomph_info << "\n\nSolving for TanhSolnForMultiPoisson::Alpha="
             << TanhSolnForMultiPoisson::Alpha << std::endl << std::endl;
  // Solve the problem
  problem.newton_solve();
  //Output the solution
  problem.doc_solution(doc_info);
 } //end of main
References TanhSolnForMultiPoisson::Alpha, oomph::CommandLineArgs::doc_specified_flags(), oomph::DocInfo::number(), oomph::oomph_info, oomph::CommandLineArgs::parse_and_assign(), problem, oomph::DocInfo::set_directory(), Flag_definition::setup(), and oomph::CommandLineArgs::specify_command_line_flag().