MercuryDPM: eigensolver_complex.cpp File Reference
eigensolver_complex.cpp File Reference
#include "main.h"
#include <limits>
#include <Eigen/Eigenvalues>
#include <Eigen/LU>
Functions
template<typename MatrixType >
bool find_pivot (typename MatrixType::Scalar tol, MatrixType &diffs, Index col=0)
template<typename VectorType >
void verify_is_approx_upto_permutation (const VectorType &vec1, const VectorType &vec2)
template<typename MatrixType >
void eigensolver (const MatrixType &m)
template<typename MatrixType >
void eigensolver_verify_assert (const MatrixType &m)
EIGEN_DECLARE_TEST (eigensolver_complex)
Function Documentation
EIGEN_DECLARE_TEST()
EIGEN_DECLARE_TEST (eigensolver_complex)
{
   int s = 0;
   for (int i = 0; i < g_repeat; i++) {
     CALL_SUBTEST_1(eigensolver(Matrix4cf()));
     s = internal::random<int>(1, EIGEN_TEST_MAX_SIZE / 4);
     CALL_SUBTEST_2(eigensolver(MatrixXcd(s, s)));
     CALL_SUBTEST_3(eigensolver(Matrix<std::complex<float>, 1, 1>()));
     CALL_SUBTEST_4(eigensolver(Matrix3f()));
     TEST_SET_BUT_UNUSED_VARIABLE(s)
   }
   CALL_SUBTEST_1(eigensolver_verify_assert(Matrix4cf()));
   s = internal::random<int>(1, EIGEN_TEST_MAX_SIZE / 4);
   CALL_SUBTEST_2(eigensolver_verify_assert(MatrixXcd(s, s)));
   CALL_SUBTEST_3(eigensolver_verify_assert(Matrix<std::complex<float>, 1, 1>()));
   CALL_SUBTEST_4(eigensolver_verify_assert(Matrix3f()));
   // Test problem size constructors
   CALL_SUBTEST_5(ComplexEigenSolver<MatrixXf> tmp(s));
   TEST_SET_BUT_UNUSED_VARIABLE(s)
 }
References CALL_SUBTEST_1, CALL_SUBTEST_2, CALL_SUBTEST_3, CALL_SUBTEST_4, CALL_SUBTEST_5, EIGEN_TEST_MAX_SIZE, eigensolver(), eigensolver_verify_assert(), Eigen::g_repeat, i, s, TEST_SET_BUT_UNUSED_VARIABLE, and tmp.
eigensolver()
template<typename MatrixType > void eigensolver (const MatrixType & m)
{
   /* this test covers the following files:
      ComplexEigenSolver.h, and indirectly ComplexSchur.h
   */
   Index rows = m.rows();
   Index cols = m.cols();
   typedef typename MatrixType::Scalar Scalar;
   typedef typename NumTraits<Scalar>::Real RealScalar;
   MatrixType a = MatrixType::Random(rows, cols);
   MatrixType symmA = a.adjoint() * a;
   ComplexEigenSolver<MatrixType> ei0(symmA);
   VERIFY_IS_EQUAL(ei0.info(), Success);
   VERIFY_IS_APPROX(symmA * ei0.eigenvectors(), ei0.eigenvectors() * ei0.eigenvalues().asDiagonal());
   ComplexEigenSolver<MatrixType> ei1(a);
   VERIFY_IS_EQUAL(ei1.info(), Success);
   VERIFY_IS_APPROX(a * ei1.eigenvectors(), ei1.eigenvectors() * ei1.eigenvalues().asDiagonal());
   // Note: If MatrixType is real then a.eigenvalues() uses EigenSolver and thus
   // another algorithm so results may differ slightly
   verify_is_approx_upto_permutation(a.eigenvalues(), ei1.eigenvalues());
   ComplexEigenSolver<MatrixType> ei2;
   ei2.setMaxIterations(ComplexSchur<MatrixType>::m_maxIterationsPerRow * rows).compute(a);
   VERIFY_IS_EQUAL(ei2.info(), Success);
   VERIFY_IS_EQUAL(ei2.eigenvectors(), ei1.eigenvectors());
   VERIFY_IS_EQUAL(ei2.eigenvalues(), ei1.eigenvalues());
   if (rows > 2) {
     ei2.setMaxIterations(1).compute(a);
     VERIFY_IS_EQUAL(ei2.info(), NoConvergence);
     VERIFY_IS_EQUAL(ei2.getMaxIterations(), 1);
   }
   ComplexEigenSolver<MatrixType> eiNoEivecs(a, false);
   VERIFY_IS_EQUAL(eiNoEivecs.info(), Success);
   VERIFY_IS_APPROX(ei1.eigenvalues(), eiNoEivecs.eigenvalues());
   // Regression test for issue #66
   MatrixType z = MatrixType::Zero(rows, cols);
   ComplexEigenSolver<MatrixType> eiz(z);
   VERIFY((eiz.eigenvalues().cwiseEqual(0)).all());
   MatrixType id = MatrixType::Identity(rows, cols);
   VERIFY_IS_APPROX(id.operatorNorm(), RealScalar(1));
   if (rows > 1 && rows < 20) {
     // Test matrix with NaN
     a(0, 0) = std::numeric_limits<typename MatrixType::RealScalar>::quiet_NaN();
     ComplexEigenSolver<MatrixType> eiNaN(a);
     VERIFY_IS_EQUAL(eiNaN.info(), NoConvergence);
   }
   // regression test for bug 1098
   {
     ComplexEigenSolver<MatrixType> eig(a.adjoint() * a);
     eig.compute(a.adjoint() * a);
   }
   // regression test for bug 478
   {
     a.setZero();
     ComplexEigenSolver<MatrixType> ei3(a);
     VERIFY_IS_EQUAL(ei3.info(), Success);
     VERIFY_IS_MUCH_SMALLER_THAN(ei3.eigenvalues().norm(), RealScalar(1));
     VERIFY((ei3.eigenvectors().transpose() * ei3.eigenvectors().transpose()).eval().isIdentity());
   }
 }
References a, cols, Eigen::ComplexEigenSolver< MatrixType_ >::compute(), Eigen::ComplexEigenSolver< MatrixType_ >::eigenvalues(), Eigen::ComplexEigenSolver< MatrixType_ >::eigenvectors(), Eigen::ComplexEigenSolver< MatrixType_ >::getMaxIterations(), Eigen::ComplexEigenSolver< MatrixType_ >::info(), m, Eigen::NoConvergence, rows, Eigen::ComplexEigenSolver< MatrixType_ >::setMaxIterations(), Eigen::Success, VERIFY, VERIFY_IS_APPROX, verify_is_approx_upto_permutation(), VERIFY_IS_EQUAL, VERIFY_IS_MUCH_SMALLER_THAN, and oomph::PseudoSolidHelper::Zero.
Referenced by EIGEN_DECLARE_TEST(), and main().
eigensolver_verify_assert()
template<typename MatrixType > void eigensolver_verify_assert (const MatrixType & m)
{
   ComplexEigenSolver<MatrixType> eig;
   VERIFY_RAISES_ASSERT(eig.eigenvectors());
   VERIFY_RAISES_ASSERT(eig.eigenvalues());
   MatrixType a = MatrixType::Random(m.rows(), m.cols());
   eig.compute(a, false);
   VERIFY_RAISES_ASSERT(eig.eigenvectors());
 }
References a, Eigen::ComplexEigenSolver< MatrixType_ >::compute(), Eigen::ComplexEigenSolver< MatrixType_ >::eigenvalues(), Eigen::ComplexEigenSolver< MatrixType_ >::eigenvectors(), m, and VERIFY_RAISES_ASSERT.
Referenced by EIGEN_DECLARE_TEST().
find_pivot()
template<typename MatrixType > bool find_pivot (typename MatrixType::Scalar tol, MatrixType & diffs, Index col = 0)
{
   bool match = diffs.diagonal().sum() <= tol;
   if (match || col == diffs.cols()) {
     return match;
   } else {
     Index n = diffs.cols();
     std::vector<std::pair<Index, Index> > transpositions;
     for (Index i = col; i < n; ++i) {
       Index best_index(0);
       if (diffs.col(col).segment(col, n - i).minCoeff(&best_index) > tol) break;
       best_index += col;
       diffs.row(col).swap(diffs.row(best_index));
       if (find_pivot(tol, diffs, col + 1)) return true;
       diffs.row(col).swap(diffs.row(best_index));
       // move current pivot to the end
       diffs.row(n - (i - col) - 1).swap(diffs.row(best_index));
       transpositions.push_back(std::pair<Index, Index>(n - (i - col) - 1, best_index));
     }
     // restore
     for (Index k = transpositions.size() - 1; k >= 0; --k)
       diffs.row(transpositions[k].first).swap(diffs.row(transpositions[k].second));
   }
   return false;
 }
References col(), i, k, match(), and n.
Referenced by verify_is_approx_upto_permutation().
verify_is_approx_upto_permutation()
template<typename VectorType > void verify_is_approx_upto_permutation (const VectorType & vec1, const VectorType & vec2)
{
   typedef typename VectorType::Scalar Scalar;
   typedef typename NumTraits<Scalar>::Real RealScalar;
   VERIFY(vec1.cols() == 1);
   VERIFY(vec2.cols() == 1);
   VERIFY(vec1.rows() == vec2.rows());
   Index n = vec1.rows();
   RealScalar tol = test_precision<RealScalar>() * test_precision<RealScalar>() *
                    numext::maxi(vec1.squaredNorm(), vec2.squaredNorm());
   Matrix<RealScalar, Dynamic, Dynamic> diffs =
       (vec1.rowwise().replicate(n) - vec2.rowwise().replicate(n).transpose()).cwiseAbs2();
   VERIFY(find_pivot(tol, diffs));
 }
References find_pivot(), Eigen::numext::maxi(), n, vec1(), and VERIFY.
Referenced by eigensolver().