MercuryDPM: SmallMatrix.h File Reference
SmallMatrix.h File Reference
#include "GeneralDefine.h"
#include "Logger.h"
#include "SmallVector.h"
#include "SmallMatrix_impl.h"
Classes
class SmallMatrix< numberOfRows, numberOfColumns >
Data type for small dense matrix.
Functions
template<unsigned int numberOfRows, unsigned int numberOfColumns>
std::ostream & operator<< (std::ostream &os, const SmallMatrix< numberOfRows, numberOfColumns > &A)
Writes nicely formatted entries of the Matrix A to the stream os.
template<unsigned int numberOfRows, unsigned int numberOfColumns>
SmallMatrix< numberOfRows, numberOfColumns > operator* (const Mdouble d, const SmallMatrix< numberOfRows, numberOfColumns > &mat)
Multiplies a matrix with a Mdouble.
template<unsigned int numberOfRows, unsigned int numberOfColumns>
SmallVector< numberOfColumns > operator* (SmallVector< numberOfRows > &vec, SmallMatrix< numberOfRows, numberOfColumns > &mat)
Multiplies a matrix with a vector.
Function Documentation
operator*() [1/2]
template<unsigned int numberOfRows, unsigned int numberOfColumns> SmallMatrix<numberOfRows, numberOfColumns> operator* (const Mdouble d, const SmallMatrix< numberOfRows, numberOfColumns > & mat)
Multiplies a matrix with a Mdouble.
 {
     return mat * d;
 }
operator*() [2/2]
template<unsigned int numberOfRows, unsigned int numberOfColumns> SmallVector<numberOfColumns> operator* (SmallVector< numberOfRows > & vec, SmallMatrix< numberOfRows, numberOfColumns > & mat)
Multiplies a matrix with a vector.
 {
     if (numberOfColumns == 0)
     {
         logger(WARN, "Trying to multiply a vector with a matrix without any columns.");
         return SmallVector<numberOfColumns>();
     }
     int nr = numberOfRows;
     int nc = numberOfColumns;
     int i_one = 1;
     double d_one = 1.0;
     double d_zero = 0.0;
     SmallVector<numberOfColumns> result;
     logger(DEBUG, "Matrix size: % x % \n Vector size: %", nr, nc, vec.size());
     dgemv_("T", &nr, &nc, &d_one, mat.data(), &nr, vec.data(), &i_one, &d_zero, result.data(), &i_one);
     return result;
 }
References Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::data(), SmallVector< numberOfRows >::data(), DEBUG, dgemv_(), logger, SmallVector< numberOfRows >::size(), and WARN.
operator<<()
template<unsigned int numberOfRows, unsigned int numberOfColumns> std::ostream& operator<< (std::ostream & os, const SmallMatrix< numberOfRows, numberOfColumns > & A)
Writes nicely formatted entries of the Matrix A to the stream os.
 {
     for (unsigned int i = 0; i < numberOfRows; ++i)
     {
         os << A.getRow(i) << std::endl;
     }
     return os;
 }
References i.