MercuryDPM: OscillatingCylinder Class Reference
OscillatingCylinder Class Reference
Oscillating cylinder class.
Public Member Functions
OscillatingCylinder (double *radius_pt, double *amplitude_pt, Time *time_pt)
virtual ~OscillatingCylinder ()
Destructor: Empty.
double & amplitude ()
Access function for the amplitude (lvalue)
Time * time_pt ()
Access function for the Time pointer.
void position (const Vector< double > &xi, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &xi, Vector< double > &r) const
virtual void position (const double &t, const Vector< double > &xi, Vector< double > &r) const
virtual void velocity (const double &t, Vector< double > &u) const
Velocity at any given point on the rigid cylinder at time, t.
OscillatingCylinder (double *radius_pt, double *amplitude_pt, Time *time_pt, const bool &use_transition_phase=true)
virtual ~OscillatingCylinder ()
Destructor: Empty.
double & amplitude ()
Access function for the amplitude (lvalue)
void position (const Vector< double > &xi, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &xi, Vector< double > &r) const
OscillatingCylinder (double *radius_pt, double *amplitude_pt, Time *time_pt)
virtual ~OscillatingCylinder ()
Destructor: Empty.
double & amplitude ()
Access function for the amplitude (lvalue)
Time * time_pt ()
Access function for the Time pointer.
void position (const Vector< double > &xi, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &xi, Vector< double > &r) const
virtual void position (const double &t, const Vector< double > &xi, Vector< double > &r) const
virtual void velocity (const double &t, Vector< double > &u) const
Velocity at any given point on the rigid cylinder at time, t.
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual unsigned ngeom_data () const
virtual Data * geom_data_pt (const unsigned &j)
virtual void dposition_dt (const Vector< double > &zeta, const unsigned &j, Vector< double > &drdt)
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
virtual void locate_zeta (const Vector< double > &zeta, GeomObject *&sub_geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
Private Attributes
double * Radius_pt
Radius of the cylinder.
double * Amplitude_pt
Non-dimensionalised amplitude of the cylinder motion.
Time * Time_pt
Pointer to the current time in the problem.
bool Use_transition_phase
Additional Inherited Members
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Detailed Description
Oscillating cylinder class.
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Constructor & Destructor Documentation
OscillatingCylinder() [1/3]
OscillatingCylinder::OscillatingCylinder (double * radius_pt, double * amplitude_pt, Time * time_pt) inline
Constructor: Pass in the radius, the amplitude of the cylinder motion, the simulation Strouhal number and a pointer to time object.
                                      :
     GeomObject(1,2),
     Radius_pt(radius_pt),
     Amplitude_pt(amplitude_pt),
     Time_pt(time_pt)
   {}
~OscillatingCylinder() [1/3]
virtual OscillatingCylinder::~OscillatingCylinder () inline virtual
Destructor: Empty.
 {}
OscillatingCylinder() [2/3]
OscillatingCylinder::OscillatingCylinder (double * radius_pt, double * amplitude_pt, Time * time_pt, const bool & use_transition_phase = true) inline
Constructor: Pass radius, amplitude of the motion, the excitation wavelength and pointer to time object.
                                                              :
     GeomObject(1,2),
     Radius_pt(radius_pt),
     Amplitude_pt(amplitude_pt),
     Time_pt(time_pt),
     Use_transition_phase(use_transition_phase)
   {}
~OscillatingCylinder() [2/3]
virtual OscillatingCylinder::~OscillatingCylinder () inline virtual
Destructor: Empty.
 {}
OscillatingCylinder() [3/3]
OscillatingCylinder::OscillatingCylinder (double * radius_pt, double * amplitude_pt, Time * time_pt) inline
Constructor: Pass in the radius, the amplitude of the cylinder motion, the simulation Strouhal number and a pointer to time object.
                                      :
     GeomObject(1,2),
     Radius_pt(radius_pt),
     Amplitude_pt(amplitude_pt),
     Time_pt(time_pt)
   {}
~OscillatingCylinder() [3/3]
virtual OscillatingCylinder::~OscillatingCylinder () inline virtual
Destructor: Empty.
 {}
Member Function Documentation
amplitude() [1/3]
double& OscillatingCylinder::amplitude () inline
Access function for the amplitude (lvalue)
   {
     // Return the value of the amplitude
     return *Amplitude_pt;
   } // End of amplitude
amplitude() [2/3]
double& OscillatingCylinder::amplitude () inline
Access function for the amplitude (lvalue)
   {
     // Return the value of the amplitude
     return *Amplitude_pt;
   } // End of amplitude
amplitude() [3/3]
double& OscillatingCylinder::amplitude () inline
Access function for the amplitude (lvalue)
   {
     // Return the value of the amplitude
     return *Amplitude_pt;
   } // End of amplitude
position() [1/8]
virtual void OscillatingCylinder::position (const double & t, const Vector< double > & xi, Vector< double > & r) const inline virtual
Parametrised position on object: r(zeta). Evaluated at the continuous time value, t.
Reimplemented from oomph::GeomObject.
   {
     // Calculate the coordinate before translation
     position(xi,r);
     // Scaling factor
     double arg=2.0*MathematicalConstants::Pi;
     // Calculate the translation
     double translation=(*Amplitude_pt)*sin(arg*t);
     // Update the y-coordinate
     r[1]+=translation;
   } // End of position
References oomph::MathematicalConstants::Pi, UniformPSDSelfTest::r, sin(), and plotPSD::t.
position() [2/8]
virtual void OscillatingCylinder::position (const double & t, const Vector< double > & xi, Vector< double > & r) const inline virtual
Parametrised position on object: r(zeta). Evaluated at the continuous time value, t.
Reimplemented from oomph::GeomObject.
   {
     // Calculate the coordinate before translation
     position(xi,r);
     // Scaling factor
     double arg=2.0*MathematicalConstants::Pi;
     // Calculate the translation
     double translation=(*Amplitude_pt)*sin(arg*t);
     // Update the y-coordinate
     r[1]+=translation;
   } // End of position
References oomph::MathematicalConstants::Pi, UniformPSDSelfTest::r, sin(), and plotPSD::t.
position() [3/8]
void OscillatingCylinder::position (const unsigned & t, const Vector< double > & xi, Vector< double > & r) const inline virtual
Current position vector to material point at Lagrangian coordinate xi (unsteady version). Implementation includes a transition phase where the cylinder oscillates to a smaller amplitude than the target value. Used to ensure that the solution isn't drastically different to that at the next time step. This can be disabled by setting Use_transition_phase to false.
Reimplemented from oomph::GeomObject.
   {
     // We can only use this if t=0
     if (t!=0)
     {
       // Create an output stream
       std::ostringstream error_message_stream;
       // Create an error message
       error_message_stream << "Trying to access the position at time history "
                            << "value, t: " << t << ".\nThis doesn't make sense "
                            << "in the space-time mesh!" << std::endl;
       // Throw the error message
       throw OomphLibError(error_message_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
     // Calculate the coordinate before translation
     position(xi,r);
     // Get current time
     double time=Time_pt->time(t);
     // Scaling factor
     double arg=2.0*MathematicalConstants::Pi;
     // Calculate the translation
     double translation=(*Amplitude_pt)*sin(arg*time);
     // Update the y-coordinate
     r[1]+=translation;
   } // End of position
References OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::MathematicalConstants::Pi, UniformPSDSelfTest::r, sin(), plotPSD::t, oomph::Time::time(), and Flag_definition::Time_pt.
position() [4/8]
void OscillatingCylinder::position (const unsigned & t, const Vector< double > & xi, Vector< double > & r) const inline virtual
Current position vector to material point at Lagrangian coordinate xi (unsteady version). Implementation includes a transition phase where the cylinder oscillates to a smaller amplitude than the target value. Used to ensure that the solution isn't drastically different to that at the next time step. This can be disabled by setting Use_transition_phase to false.
Reimplemented from oomph::GeomObject.
   {
     // Calculate the coordinate before translation
     position(xi,r);
     // Get current time
     double time=Time_pt->time(t);
     // Scaling factor
     double arg=2.0*MathematicalConstants::Pi;
     // Calculate the translation
     double translation=(*Amplitude_pt)*sin(arg*time);
     // If the user wishes to use a transition phase
     if (Use_transition_phase)
     {
       // Time for transition (equal to two periods)
       double t_transition=2.0;
       // If we're not past the transition point
       if (time<t_transition)
       {
         // Scale the translation
         translation*=(time/t_transition)*exp(1.0-(time/t_transition));
       }
     } // if (Use_transition_phase)
     // Update the y-coordinate
     r[1]+=translation;
   } // End of position
References Eigen::bfloat16_impl::exp(), oomph::MathematicalConstants::Pi, UniformPSDSelfTest::r, sin(), plotPSD::t, oomph::Time::time(), and Flag_definition::Time_pt.
position() [5/8]
void OscillatingCylinder::position (const unsigned & t, const Vector< double > & xi, Vector< double > & r) const inline virtual
Current position vector to material point at Lagrangian coordinate xi (unsteady version). Implementation includes a transition phase where the cylinder oscillates to a smaller amplitude than the target value. Used to ensure that the solution isn't drastically different to that at the next time step. This can be disabled by setting Use_transition_phase to false.
Reimplemented from oomph::GeomObject.
   {
     // We can only use this if t=0
     if (t!=0)
     {
       // Create an output stream
       std::ostringstream error_message_stream;
       // Create an error message
       error_message_stream << "Trying to access the position at time history "
                            << "value, t: " << t << ".\nThis doesn't make sense "
                            << "in the space-time mesh!" << std::endl;
       // Throw the error message
       throw OomphLibError(error_message_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
     // Calculate the coordinate before translation
     position(xi,r);
     // Get current time
     double time=Time_pt->time(t);
     // Scaling factor
     double arg=2.0*MathematicalConstants::Pi;
     // Calculate the translation
     double translation=(*Amplitude_pt)*sin(arg*time);
     // Update the y-coordinate
     r[1]+=translation;
   } // End of position
References OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::MathematicalConstants::Pi, UniformPSDSelfTest::r, sin(), plotPSD::t, oomph::Time::time(), and Flag_definition::Time_pt.
position() [6/8]
void OscillatingCylinder::position (const Vector< double > & xi, Vector< double > & r) const inline virtual
Current position vector to material point at Lagrangian coordinate xi (steady version)
Implements oomph::GeomObject.
   {
     // X-coordinate
     r[0]=(*Radius_pt)*cos(xi[0]);
     // Y-coordinate
     r[1]=(*Radius_pt)*sin(xi[0]);
   } // End of position
References cos(), UniformPSDSelfTest::r, and sin().
Referenced by CylinderAndInterfaceDomain::CylinderAndInterfaceDomain(), RectangleWithHoleDomain::macro_element_boundary(), oomph::HalfRectangleWithHoleDomain::macro_element_boundary(), CylinderAndInterfaceDomain::macro_element_boundary(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::node_update_IX(), and oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::node_update_VIII().
position() [7/8]
void OscillatingCylinder::position (const Vector< double > & xi, Vector< double > & r) const inline virtual
Current position vector to material point at Lagrangian coordinate xi (steady version)
Implements oomph::GeomObject.
   {
     // X-coordinate
     r[0]=(*Radius_pt)*cos(xi[0]);
     // Y-coordinate
     r[1]=(*Radius_pt)*sin(xi[0]);
   } // End of position
References cos(), UniformPSDSelfTest::r, and sin().
position() [8/8]
void OscillatingCylinder::position (const Vector< double > & xi, Vector< double > & r) const inline virtual
Current position vector to material point at Lagrangian coordinate xi (steady version)
Implements oomph::GeomObject.
   {
     // X-coordinate
     r[0]=(*Radius_pt)*cos(xi[0]);
     // Y-coordinate
     r[1]=(*Radius_pt)*sin(xi[0]);
   } // End of position
References cos(), UniformPSDSelfTest::r, and sin().
time_pt() [1/2]
Time* OscillatingCylinder::time_pt () inline
Access function for the Time pointer.
   {
     // Return the Time pointer
     return Time_pt;
   } // End of time_pt
References Flag_definition::Time_pt.
time_pt() [2/2]
Time* OscillatingCylinder::time_pt () inline
Access function for the Time pointer.
   {
     // Return the Time pointer
     return Time_pt;
   } // End of time_pt
References Flag_definition::Time_pt.
velocity() [1/2]
virtual void OscillatingCylinder::velocity (const double & t, Vector< double > & u) const inline virtual
Velocity at any given point on the rigid cylinder at time, t.
   {
     // Scaling factor
     double arg=2.0*MathematicalConstants::Pi;
     // Zero velocity component in the x-direction
     u[0]=0.0;
     // Calculate the (non-zero) velocity component in the y-direction
     u[1]=arg*(*Amplitude_pt)*cos(arg*t);
   } // End of velocity
References cos(), oomph::MathematicalConstants::Pi, and plotPSD::t.
Referenced by NavierStokesProblem< ELEMENT >::apply_boundary_conditions().
velocity() [2/2]
virtual void OscillatingCylinder::velocity (const double & t, Vector< double > & u) const inline virtual
Velocity at any given point on the rigid cylinder at time, t.
   {
     // Scaling factor
     double arg=2.0*MathematicalConstants::Pi;
     // Zero velocity component in the x-direction
     u[0]=0.0;
     // Calculate the (non-zero) velocity component in the y-direction
     u[1]=arg*(*Amplitude_pt)*cos(arg*t);
   } // End of velocity
References cos(), oomph::MathematicalConstants::Pi, and plotPSD::t.
Member Data Documentation
Amplitude_pt
double * OscillatingCylinder::Amplitude_pt private
Non-dimensionalised amplitude of the cylinder motion.
Radius_pt
double * OscillatingCylinder::Radius_pt private
Radius of the cylinder.
Time_pt
Time * OscillatingCylinder::Time_pt private
Pointer to the current time in the problem.
Use_transition_phase
bool OscillatingCylinder::Use_transition_phase private
Boolean variable to indicate whether or not to use a transition phase at the start of the simulation. Defaults to true.
The documentation for this class was generated from the following files:
extrude_with_macro_element_representation.cc
flow_past_oscillating_cylinder.cc
space_time_oscillating_cylinder.cc