MercuryDPM: ExactSolnForUnsteadyHeat Namespace Reference
ExactSolnForUnsteadyHeat Namespace Reference
Namespace for unforced exact solution for UnsteadyHeat equation.
Functions
void get_exact_u (const double &time, const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void get_exact_u (const double &time, const Vector< double > &x, double &u)
Exact solution as a scalar.
void get_source (const double &time, const Vector< double > &x, double &source)
Source function to make it an exact solution.
void prescribed_flux_on_fixed_y_boundary (const double &time, const Vector< double > &x, const Vector< double > &n, const double &u, double &flux)
Flux required by the exact solution.
Variables
double K =10
Decay factor.
double Phi =1.0
Angle of bump.
double Gamma =10.0
Factor controlling the rate of change.
Detailed Description
Namespace for unforced exact solution for UnsteadyHeat equation.
Namespace for forced exact solution for UnsteadyHeat equation.
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Function Documentation
get_exact_u() [1/2]
void ExactSolnForUnsteadyHeat::get_exact_u (const double & time, const Vector< double > & x, double & u)
Exact solution as a scalar.
  {
   double zeta=cos(Phi)*x[0]+sin(Phi)*x[1];
   u=exp(-K*time)*sin(zeta*sqrt(K));
  }
References cos(), Eigen::bfloat16_impl::exp(), K, Phi, sin(), sqrt(), plotDoE::x, and Eigen::zeta().
get_exact_u() [2/2]
void ExactSolnForUnsteadyHeat::get_exact_u (const double & time, const Vector< double > & x, Vector< double > & u)
Exact solution as a Vector.
  {
   double zeta=cos(Phi)*x[0]+sin(Phi)*x[1];
   u[0]=exp(-K*time)*sin(zeta*sqrt(K));
  }
References cos(), Eigen::bfloat16_impl::exp(), K, Phi, sin(), sqrt(), plotDoE::x, and Eigen::zeta().
Referenced by UnsteadyHeatProblem< ELEMENT >::actions_before_implicit_timestep(), UnsteadyHeatProblem< ELEMENT >::doc_solution(), and UnsteadyHeatProblem< ELEMENT >::set_initial_condition().
get_source()
void ExactSolnForUnsteadyHeat::get_source (const double & time, const Vector< double > & x, double & source)
Source function to make it an exact solution.
  {
   source = 0.0;
  }
References TestProblem::source().
Referenced by main(), and run_it().
prescribed_flux_on_fixed_y_boundary()
void ExactSolnForUnsteadyHeat::prescribed_flux_on_fixed_y_boundary (const double & time, const Vector< double > & x, const Vector< double > & n, const double & u, double & flux)
Flux required by the exact solution.
  {
   double NX = n[0];
   double NY = n[1];
   //The flux in terms of the normal is
   double zeta=cos(Phi)*x[0]+sin(Phi)*x[1];
   flux=exp(-K*time)*sqrt(K)*cos(zeta*sqrt(K))*(cos(Phi)*NX+sin(Phi)*NY);
  }
References cos(), Eigen::bfloat16_impl::exp(), ProblemParameters::flux(), K, n, Phi, sin(), sqrt(), plotDoE::x, and Eigen::zeta().
Variable Documentation
Gamma
double ExactSolnForUnsteadyHeat::Gamma =10.0
Factor controlling the rate of change.
K
double ExactSolnForUnsteadyHeat::K =10
Decay factor.
Wavenumber.
Referenced by get_exact_u(), prescribed_flux_on_fixed_y_boundary(), and UnsteadyHeatProblem< ELEMENT >::UnsteadyHeatProblem().
Phi
double ExactSolnForUnsteadyHeat::Phi =1.0
Angle of bump.
Referenced by TanhSolnForLinearWave::get_exact_gradient(), get_exact_u(), and prescribed_flux_on_fixed_y_boundary().