MercuryDPM: Eigen::internal::dhs_pack< bfloat16, DataMapper, Packet8bf, StorageOrder, PanelMode, true > Struct Template Reference
Eigen::internal::dhs_pack< bfloat16, DataMapper, Packet8bf, StorageOrder, PanelMode, true > Struct Template Reference
#include <MatrixProduct.h>
Public Member Functions
EIGEN_STRONG_INLINE void operator() (bfloat16 *blockA, const DataMapper &lhs, Index depth, Index rows, Index stride, Index offset)
Member Function Documentation
operator()()
template<typename DataMapper , int StorageOrder, bool PanelMode> EIGEN_STRONG_INLINE void Eigen::internal::dhs_pack< bfloat16, DataMapper, Packet8bf, StorageOrder, PanelMode, true >::operator() (bfloat16 * blockA, const DataMapper & lhs, Index depth, Index rows, Index stride, Index offset) inline
{
     const Index vectorSize = quad_traits<bfloat16>::vectorsize;
     Index ri = 0, j = 0;
     for (; j + 2 * vectorSize <= rows; j += 2 * vectorSize) {
       const DataMapper lhs2 = lhs.getSubMapper(j, 0);
       Index i = 0;
       if (PanelMode) ri += 2 * vectorSize * offset;
       if (StorageOrder == ColMajor) {
         for (; i + 2 <= depth; i += 2) {
           PacketBlock<Packet8bf, 4> block;
           block.packet[0] = lhs2.template loadPacket<Packet8bf>(0 * vectorSize, i + 0);
           block.packet[1] = lhs2.template loadPacket<Packet8bf>(1 * vectorSize, i + 0);
           block.packet[2] = lhs2.template loadPacket<Packet8bf>(0 * vectorSize, i + 1);
           block.packet[3] = lhs2.template loadPacket<Packet8bf>(1 * vectorSize, i + 1);
           Packet8bf t0, t1;
           t0 = vec_mergeh(block.packet[0].m_val, block.packet[2].m_val);
           t1 = vec_mergel(block.packet[0].m_val, block.packet[2].m_val);
           block.packet[2] = vec_mergeh(block.packet[1].m_val, block.packet[3].m_val);
           block.packet[3] = vec_mergel(block.packet[1].m_val, block.packet[3].m_val);
           block.packet[0] = t0;
           block.packet[1] = t1;
           storeBlock<bfloat16, Packet8bf, 4>(blockA + ri, block);
           ri += 2 * 2 * vectorSize;
         }
         if (depth & 1) {
           PacketBlock<Packet8bf, 2> block;
           block.packet[0] = lhs2.template loadPacket<Packet8bf>(0 * vectorSize, i + 0);
           block.packet[1] = lhs2.template loadPacket<Packet8bf>(1 * vectorSize, i + 0);
           storeBlock<bfloat16, Packet8bf, 2>(blockA + ri, block);
           ri += 2 * vectorSize;
         }
       } else {
         for (; i + vectorSize <= depth; i += vectorSize) {
           PacketBlock<Packet8bf, 8> block1, block2;
           bload<DataMapper, Packet8bf, 8, StorageOrder, false, 8>(block1, lhs2, 0 * vectorSize, i);
           bload<DataMapper, Packet8bf, 8, StorageOrder, false, 8>(block2, lhs2, 1 * vectorSize, i);
           Packet4ui v1[8], v2[8];
           v1[0] = vec_mergeh(reinterpret_cast<Packet4ui>(block1.packet[0].m_val),
                              reinterpret_cast<Packet4ui>(block1.packet[1].m_val));
           v1[1] = vec_mergel(reinterpret_cast<Packet4ui>(block1.packet[0].m_val),
                              reinterpret_cast<Packet4ui>(block1.packet[1].m_val));
           v1[2] = vec_mergeh(reinterpret_cast<Packet4ui>(block1.packet[2].m_val),
                              reinterpret_cast<Packet4ui>(block1.packet[3].m_val));
           v1[3] = vec_mergel(reinterpret_cast<Packet4ui>(block1.packet[2].m_val),
                              reinterpret_cast<Packet4ui>(block1.packet[3].m_val));
           v1[4] = vec_mergeh(reinterpret_cast<Packet4ui>(block1.packet[4].m_val),
                              reinterpret_cast<Packet4ui>(block1.packet[5].m_val));
           v1[5] = vec_mergel(reinterpret_cast<Packet4ui>(block1.packet[4].m_val),
                              reinterpret_cast<Packet4ui>(block1.packet[5].m_val));
           v1[6] = vec_mergeh(reinterpret_cast<Packet4ui>(block1.packet[6].m_val),
                              reinterpret_cast<Packet4ui>(block1.packet[7].m_val));
           v1[7] = vec_mergel(reinterpret_cast<Packet4ui>(block1.packet[6].m_val),
                              reinterpret_cast<Packet4ui>(block1.packet[7].m_val));
           v2[0] = vec_mergeh(reinterpret_cast<Packet4ui>(block2.packet[0].m_val),
                              reinterpret_cast<Packet4ui>(block2.packet[1].m_val));
           v2[1] = vec_mergel(reinterpret_cast<Packet4ui>(block2.packet[0].m_val),
                              reinterpret_cast<Packet4ui>(block2.packet[1].m_val));
           v2[2] = vec_mergeh(reinterpret_cast<Packet4ui>(block2.packet[2].m_val),
                              reinterpret_cast<Packet4ui>(block2.packet[3].m_val));
           v2[3] = vec_mergel(reinterpret_cast<Packet4ui>(block2.packet[2].m_val),
                              reinterpret_cast<Packet4ui>(block2.packet[3].m_val));
           v2[4] = vec_mergeh(reinterpret_cast<Packet4ui>(block2.packet[4].m_val),
                              reinterpret_cast<Packet4ui>(block2.packet[5].m_val));
           v2[5] = vec_mergel(reinterpret_cast<Packet4ui>(block2.packet[4].m_val),
                              reinterpret_cast<Packet4ui>(block2.packet[5].m_val));
           v2[6] = vec_mergeh(reinterpret_cast<Packet4ui>(block2.packet[6].m_val),
                              reinterpret_cast<Packet4ui>(block2.packet[7].m_val));
           v2[7] = vec_mergel(reinterpret_cast<Packet4ui>(block2.packet[6].m_val),
                              reinterpret_cast<Packet4ui>(block2.packet[7].m_val));
 #ifdef EIGEN_VECTORIZE_VSX
           block1.packet[0] = reinterpret_cast<Packet8us>(
               vec_mergeh(reinterpret_cast<Packet2ul>(v1[0]), reinterpret_cast<Packet2ul>(v1[2])));
           block1.packet[2] = reinterpret_cast<Packet8us>(
               vec_mergel(reinterpret_cast<Packet2ul>(v1[0]), reinterpret_cast<Packet2ul>(v1[2])));
           block1.packet[4] = reinterpret_cast<Packet8us>(
               vec_mergeh(reinterpret_cast<Packet2ul>(v1[1]), reinterpret_cast<Packet2ul>(v1[3])));
           block1.packet[6] = reinterpret_cast<Packet8us>(
               vec_mergel(reinterpret_cast<Packet2ul>(v1[1]), reinterpret_cast<Packet2ul>(v1[3])));
           block1.packet[1] = reinterpret_cast<Packet8us>(
               vec_mergeh(reinterpret_cast<Packet2ul>(v1[4]), reinterpret_cast<Packet2ul>(v1[6])));
           block1.packet[3] = reinterpret_cast<Packet8us>(
               vec_mergel(reinterpret_cast<Packet2ul>(v1[4]), reinterpret_cast<Packet2ul>(v1[6])));
           block1.packet[5] = reinterpret_cast<Packet8us>(
               vec_mergeh(reinterpret_cast<Packet2ul>(v1[5]), reinterpret_cast<Packet2ul>(v1[7])));
           block1.packet[7] = reinterpret_cast<Packet8us>(
               vec_mergel(reinterpret_cast<Packet2ul>(v1[5]), reinterpret_cast<Packet2ul>(v1[7])));
           block2.packet[0] = reinterpret_cast<Packet8us>(
               vec_mergeh(reinterpret_cast<Packet2ul>(v2[0]), reinterpret_cast<Packet2ul>(v2[2])));
           block2.packet[2] = reinterpret_cast<Packet8us>(
               vec_mergel(reinterpret_cast<Packet2ul>(v2[0]), reinterpret_cast<Packet2ul>(v2[2])));
           block2.packet[4] = reinterpret_cast<Packet8us>(
               vec_mergeh(reinterpret_cast<Packet2ul>(v2[1]), reinterpret_cast<Packet2ul>(v2[3])));
           block2.packet[6] = reinterpret_cast<Packet8us>(
               vec_mergel(reinterpret_cast<Packet2ul>(v2[1]), reinterpret_cast<Packet2ul>(v2[3])));
           block2.packet[1] = reinterpret_cast<Packet8us>(
               vec_mergeh(reinterpret_cast<Packet2ul>(v2[4]), reinterpret_cast<Packet2ul>(v2[6])));
           block2.packet[3] = reinterpret_cast<Packet8us>(
               vec_mergel(reinterpret_cast<Packet2ul>(v2[4]), reinterpret_cast<Packet2ul>(v2[6])));
           block2.packet[5] = reinterpret_cast<Packet8us>(
               vec_mergeh(reinterpret_cast<Packet2ul>(v2[5]), reinterpret_cast<Packet2ul>(v2[7])));
           block2.packet[7] = reinterpret_cast<Packet8us>(
               vec_mergel(reinterpret_cast<Packet2ul>(v2[5]), reinterpret_cast<Packet2ul>(v2[7])));
 #else
           block1.packet[0] = reinterpret_cast<Packet8us>(vec_perm(v1[0], v1[2], p16uc_TRANSPOSE64_HI));
           block1.packet[2] = reinterpret_cast<Packet8us>(vec_perm(v1[0], v1[2], p16uc_TRANSPOSE64_LO));
           block1.packet[4] = reinterpret_cast<Packet8us>(vec_perm(v1[1], v1[3], p16uc_TRANSPOSE64_HI));
           block1.packet[6] = reinterpret_cast<Packet8us>(vec_perm(v1[1], v1[3], p16uc_TRANSPOSE64_LO));
           block1.packet[1] = reinterpret_cast<Packet8us>(vec_perm(v1[4], v1[6], p16uc_TRANSPOSE64_HI));
           block1.packet[3] = reinterpret_cast<Packet8us>(vec_perm(v1[4], v1[6], p16uc_TRANSPOSE64_LO));
           block1.packet[5] = reinterpret_cast<Packet8us>(vec_perm(v1[5], v1[7], p16uc_TRANSPOSE64_HI));
           block1.packet[7] = reinterpret_cast<Packet8us>(vec_perm(v1[5], v1[7], p16uc_TRANSPOSE64_LO));
           block2.packet[0] = reinterpret_cast<Packet8us>(vec_perm(v2[0], v2[2], p16uc_TRANSPOSE64_HI));
           block2.packet[2] = reinterpret_cast<Packet8us>(vec_perm(v2[0], v2[2], p16uc_TRANSPOSE64_LO));
           block2.packet[4] = reinterpret_cast<Packet8us>(vec_perm(v2[1], v2[3], p16uc_TRANSPOSE64_HI));
           block2.packet[6] = reinterpret_cast<Packet8us>(vec_perm(v2[1], v2[3], p16uc_TRANSPOSE64_LO));
           block2.packet[1] = reinterpret_cast<Packet8us>(vec_perm(v2[4], v2[6], p16uc_TRANSPOSE64_HI));
           block2.packet[3] = reinterpret_cast<Packet8us>(vec_perm(v2[4], v2[6], p16uc_TRANSPOSE64_LO));
           block2.packet[5] = reinterpret_cast<Packet8us>(vec_perm(v2[5], v2[7], p16uc_TRANSPOSE64_HI));
           block2.packet[7] = reinterpret_cast<Packet8us>(vec_perm(v2[5], v2[7], p16uc_TRANSPOSE64_LO));
 #endif
           for (Index M = 0; M < 8; M += 2) {
             pstore<bfloat16>(blockA + ri + (0 * vectorSize) + (2 * vectorSize * M), block1.packet[M + 0]);
             pstore<bfloat16>(blockA + ri + (1 * vectorSize) + (2 * vectorSize * M), block1.packet[M + 1]);
             pstore<bfloat16>(blockA + ri + (2 * vectorSize) + (2 * vectorSize * M), block2.packet[M + 0]);
             pstore<bfloat16>(blockA + ri + (3 * vectorSize) + (2 * vectorSize * M), block2.packet[M + 1]);
           }
           ri += 2 * vectorSize * vectorSize;
         }
         for (; i + 2 <= depth; i += 2) {
           for (Index M = 0; M < 2 * vectorSize; M++) {
             blockA[ri + (M * 2) + 0] = lhs2(M, i + 0);
             blockA[ri + (M * 2) + 1] = lhs2(M, i + 1);
           }
           ri += 2 * 2 * vectorSize;
         }
         if (depth & 1) {
           for (Index M = 0; M < 2 * vectorSize; M++) {
             blockA[ri + M] = lhs2(M, i);
           }
           ri += 2 * vectorSize;
         }
       }
       if (PanelMode) ri += 2 * vectorSize * (stride - offset - depth);
     }
     for (; j + vectorSize <= rows; j += vectorSize) {
       const DataMapper lhs2 = lhs.getSubMapper(j, 0);
       Index i = 0;
       if (PanelMode) ri += vectorSize * offset;
       if (StorageOrder == ColMajor) {
         for (; i + 2 <= depth; i += 2) {
           PacketBlock<Packet8bf, 2> block;
           block.packet[0] = lhs2.template loadPacket<Packet8bf>(0 * vectorSize, i + 0);
           block.packet[1] = lhs2.template loadPacket<Packet8bf>(0 * vectorSize, i + 1);
           Packet8bf t0;
           t0 = vec_mergeh(block.packet[0].m_val, block.packet[1].m_val);
           block.packet[1] = vec_mergel(block.packet[0].m_val, block.packet[1].m_val);
           block.packet[0] = t0;
           storeBlock<bfloat16, Packet8bf, 2>(blockA + ri, block);
           ri += 2 * vectorSize;
         }
         if (depth & 1) {
           Packet8bf lhsV = lhs2.template loadPacket<Packet8bf>(0 * vectorSize, i + 0);
           pstore<bfloat16>(blockA + ri, lhsV);
           ri += vectorSize;
         }
       } else {
         for (; i + vectorSize <= depth; i += vectorSize) {
           PacketBlock<Packet8bf, 8> block1;
           bload<DataMapper, Packet8bf, 8, StorageOrder, false, 8>(block1, lhs2, 0 * vectorSize, i);
           Packet4ui v1[8];
           // This is transposing and interleaving data
           v1[0] = vec_mergeh(reinterpret_cast<Packet4ui>(block1.packet[0].m_val),
                              reinterpret_cast<Packet4ui>(block1.packet[1].m_val));
           v1[1] = vec_mergel(reinterpret_cast<Packet4ui>(block1.packet[0].m_val),
                              reinterpret_cast<Packet4ui>(block1.packet[1].m_val));
           v1[2] = vec_mergeh(reinterpret_cast<Packet4ui>(block1.packet[2].m_val),
                              reinterpret_cast<Packet4ui>(block1.packet[3].m_val));
           v1[3] = vec_mergel(reinterpret_cast<Packet4ui>(block1.packet[2].m_val),
                              reinterpret_cast<Packet4ui>(block1.packet[3].m_val));
           v1[4] = vec_mergeh(reinterpret_cast<Packet4ui>(block1.packet[4].m_val),
                              reinterpret_cast<Packet4ui>(block1.packet[5].m_val));
           v1[5] = vec_mergel(reinterpret_cast<Packet4ui>(block1.packet[4].m_val),
                              reinterpret_cast<Packet4ui>(block1.packet[5].m_val));
           v1[6] = vec_mergeh(reinterpret_cast<Packet4ui>(block1.packet[6].m_val),
                              reinterpret_cast<Packet4ui>(block1.packet[7].m_val));
           v1[7] = vec_mergel(reinterpret_cast<Packet4ui>(block1.packet[6].m_val),
                              reinterpret_cast<Packet4ui>(block1.packet[7].m_val));
 #ifdef EIGEN_VECTORIZE_VSX
           block1.packet[0] = reinterpret_cast<Packet8us>(
               vec_mergeh(reinterpret_cast<Packet2ul>(v1[0]), reinterpret_cast<Packet2ul>(v1[2])));
           block1.packet[2] = reinterpret_cast<Packet8us>(
               vec_mergel(reinterpret_cast<Packet2ul>(v1[0]), reinterpret_cast<Packet2ul>(v1[2])));
           block1.packet[4] = reinterpret_cast<Packet8us>(
               vec_mergeh(reinterpret_cast<Packet2ul>(v1[1]), reinterpret_cast<Packet2ul>(v1[3])));
           block1.packet[6] = reinterpret_cast<Packet8us>(
               vec_mergel(reinterpret_cast<Packet2ul>(v1[1]), reinterpret_cast<Packet2ul>(v1[3])));
           block1.packet[1] = reinterpret_cast<Packet8us>(
               vec_mergeh(reinterpret_cast<Packet2ul>(v1[4]), reinterpret_cast<Packet2ul>(v1[6])));
           block1.packet[3] = reinterpret_cast<Packet8us>(
               vec_mergel(reinterpret_cast<Packet2ul>(v1[4]), reinterpret_cast<Packet2ul>(v1[6])));
           block1.packet[5] = reinterpret_cast<Packet8us>(
               vec_mergeh(reinterpret_cast<Packet2ul>(v1[5]), reinterpret_cast<Packet2ul>(v1[7])));
           block1.packet[7] = reinterpret_cast<Packet8us>(
               vec_mergel(reinterpret_cast<Packet2ul>(v1[5]), reinterpret_cast<Packet2ul>(v1[7])));
 #else
           block1.packet[0] = reinterpret_cast<Packet8us>(vec_perm(v1[0], v1[2], p16uc_TRANSPOSE64_HI));
           block1.packet[2] = reinterpret_cast<Packet8us>(vec_perm(v1[0], v1[2], p16uc_TRANSPOSE64_LO));
           block1.packet[4] = reinterpret_cast<Packet8us>(vec_perm(v1[1], v1[3], p16uc_TRANSPOSE64_HI));
           block1.packet[6] = reinterpret_cast<Packet8us>(vec_perm(v1[1], v1[3], p16uc_TRANSPOSE64_LO));
           block1.packet[1] = reinterpret_cast<Packet8us>(vec_perm(v1[4], v1[6], p16uc_TRANSPOSE64_HI));
           block1.packet[3] = reinterpret_cast<Packet8us>(vec_perm(v1[4], v1[6], p16uc_TRANSPOSE64_LO));
           block1.packet[5] = reinterpret_cast<Packet8us>(vec_perm(v1[5], v1[7], p16uc_TRANSPOSE64_HI));
           block1.packet[7] = reinterpret_cast<Packet8us>(vec_perm(v1[5], v1[7], p16uc_TRANSPOSE64_LO));
 #endif
           for (Index M = 0; M < 8; M++) {
             pstore<bfloat16>(blockA + ri + (vectorSize * M), block1.packet[M]);
           }
           ri += vectorSize * vectorSize;
         }
         for (; i + 2 <= depth; i += 2) {
           for (Index M = 0; M < vectorSize; M++) {
             blockA[ri + (M * 2) + 0] = lhs2(M, i + 0);
             blockA[ri + (M * 2) + 1] = lhs2(M, i + 1);
           }
           ri += 2 * vectorSize;
         }
         if (depth & 1) {
           for (Index M = 0; M < vectorSize; M++) {
             blockA[ri + M] = lhs2(M, i);
           }
           ri += vectorSize;
         }
       }
       if (PanelMode) ri += vectorSize * (stride - offset - depth);
     }
     if (j + 4 <= rows) {
       const DataMapper lhs2 = lhs.getSubMapper(j, 0);
       Index i = 0;
       if (PanelMode) ri += 4 * offset;
       for (; i + 2 <= depth; i += 2) {
         if (StorageOrder == ColMajor) {
           PacketBlock<Packet8bf, 2> block;
           block.packet[0] = lhs2.template loadPacketPartial<Packet8bf>(0, i + 0, 4);
           block.packet[1] = lhs2.template loadPacketPartial<Packet8bf>(0, i + 1, 4);
           block.packet[0] = vec_mergeh(block.packet[0].m_val, block.packet[1].m_val);
           pstore<bfloat16>(blockA + ri, block.packet[0]);
         } else {
           blockA[ri + 0] = lhs2(0, i + 0);
           blockA[ri + 1] = lhs2(0, i + 1);
           blockA[ri + 2] = lhs2(1, i + 0);
           blockA[ri + 3] = lhs2(1, i + 1);
           blockA[ri + 4] = lhs2(2, i + 0);
           blockA[ri + 5] = lhs2(2, i + 1);
           blockA[ri + 6] = lhs2(3, i + 0);
           blockA[ri + 7] = lhs2(3, i + 1);
         }
         ri += 2 * 4;
       }
       if (depth & 1) {
         if (StorageOrder == ColMajor) {
           Packet8bf lhsV = lhs2.template loadPacketPartial<Packet8bf>(0, i + 0, 4);
           pstore_partial<bfloat16>(blockA + ri, lhsV, 4);
         } else {
           blockA[ri + 0] = lhs2(0, i);
           blockA[ri + 1] = lhs2(1, i);
           blockA[ri + 2] = lhs2(2, i);
           blockA[ri + 3] = lhs2(3, i);
         }
         ri += 4;
       }
       if (PanelMode) ri += 4 * (stride - offset - depth);
       j += 4;
     }
     if (j < rows) {
       if (PanelMode) ri += offset * (rows - j);
       Index i = 0;
       for (; i + 2 <= depth; i += 2) {
         Index k = j;
         for (; k < rows; k++) {
           blockA[ri + 0] = lhs(k, i + 0);
           blockA[ri + 1] = lhs(k, i + 1);
           ri += 2;
         }
       }
       if (depth & 1) {
         for (; j < rows; j++) {
           blockA[ri] = lhs(j, i);
           ri += 1;
         }
       }
     }
   }
References block(), Eigen::ColMajor, i, j, k, Eigen::internal::p16uc_TRANSPOSE64_HI, Eigen::internal::p16uc_TRANSPOSE64_LO, Eigen::internal::PacketBlock< Packet, N >::packet, Eigen::internal::pstore< bfloat16 >(), Eigen::internal::pstore_partial< bfloat16 >(), rows, v1(), and v2().
The documentation for this struct was generated from the following file:
MatrixProduct.h