MercuryDPM: locate_zeta_tester_triangle.cc File Reference
locate_zeta_tester_triangle.cc File Reference
#include <fenv.h>
#include "generic.h"
#include "poisson.h"
#include "meshes/triangle_mesh.h"
#include "locate_zeta_tester.h"
Classes
class UnstructuredPoissonProblem< ELEMENT >
Class definition.
Namespaces
TanhSolnForPoisson
Namespace for exact solution for Poisson equation with "sharp step".
Functions
void TanhSolnForPoisson::get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void TanhSolnForPoisson::get_source (const Vector< double > &x, double &source)
Source function to make it an exact solution.
void TanhSolnForPoisson::zero (const Vector< double > &x, Vector< double > &u)
int main (int argc, char **argv)
Driver code for demo of inline triangle mesh generation.
Function Documentation
main()
int main (int argc , char ** argv)
Driver code for demo of inline triangle mesh generation.
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Define possible command line arguments and parse the ones that
  // were actually specified
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  // Create problem
  UnstructuredPoissonProblem<ProjectablePoissonElement<TPoissonElement<2,3> > >
   problem;
  // Doc the initial mesh
  //=====================
  std::stringstream comment_stream;
  comment_stream << "Initial mesh ";
  problem.doc_solution(comment_stream.str());
  // Solve with spatial adaptation
  //==============================
  unsigned max_adapt=3;
  problem.newton_solve(max_adapt);
  // Doc the solution
  //=================
  problem.doc_solution();
  // Check it out!
  check_locate_zeta(problem.mesh_pt());
 } //End of main
References check_locate_zeta(), oomph::CommandLineArgs::doc_specified_flags(), oomph::CommandLineArgs::parse_and_assign(), problem, and Flag_definition::setup().