MercuryDPM: Eigen::internal::Packet1cd Struct Reference
Eigen::internal::Packet1cd Struct Reference
#include <Complex.h>
Public Member Functions
EIGEN_STRONG_INLINE Packet1cd ()
EIGEN_STRONG_INLINE Packet1cd (const __m128d &a)
EIGEN_STRONG_INLINE Packet1cd ()
EIGEN_STRONG_INLINE Packet1cd (const std::complex< double > &a)
EIGEN_STRONG_INLINE Packet1cd (const Packet2d &a)
EIGEN_STRONG_INLINE Packet1cd (const Packet1cd &a)
EIGEN_STRONG_INLINE Packet1cd & operator= (const Packet1cd &b)
EIGEN_STRONG_INLINE Packet1cd conjugate (void) const
EIGEN_STRONG_INLINE Packet1cd & operator*= (const Packet1cd &b)
EIGEN_STRONG_INLINE Packet1cd operator* (const Packet1cd &b) const
EIGEN_STRONG_INLINE Packet1cd & operator+= (const Packet1cd &b)
EIGEN_STRONG_INLINE Packet1cd operator+ (const Packet1cd &b) const
EIGEN_STRONG_INLINE Packet1cd & operator-= (const Packet1cd &b)
EIGEN_STRONG_INLINE Packet1cd operator- (const Packet1cd &b) const
EIGEN_STRONG_INLINE Packet1cd & operator/= (const Packet1cd &b)
EIGEN_STRONG_INLINE Packet1cd operator/ (const Packet1cd &b) const
EIGEN_STRONG_INLINE Packet1cd operator- (void) const
EIGEN_STRONG_INLINE Packet1cd ()
EIGEN_STRONG_INLINE Packet1cd (const __m128d &a)
EIGEN_STRONG_INLINE Packet1cd ()
EIGEN_STRONG_INLINE Packet1cd (const Packet2d &a)
Public Attributes
Packet2d v
Constructor & Destructor Documentation
Packet1cd() [1/10]
EIGEN_STRONG_INLINE Eigen::internal::Packet1cd::Packet1cd () inline
 {}
Referenced by operator*(), operator*=(), operator+(), operator-(), and operator/().
Packet1cd() [2/10]
EIGEN_STRONG_INLINE Eigen::internal::Packet1cd::Packet1cd (const __m128d & a) inline explicit
 : v(a) {}
Packet1cd() [3/10]
EIGEN_STRONG_INLINE Eigen::internal::Packet1cd::Packet1cd () inline
 {}
Packet1cd() [4/10]
EIGEN_STRONG_INLINE Eigen::internal::Packet1cd::Packet1cd (const std::complex< double > & a) inline explicit
{
     v[0] = std::real(a);
     v[1] = std::imag(a);
   }
References a, imag(), and v.
Packet1cd() [5/10]
EIGEN_STRONG_INLINE Eigen::internal::Packet1cd::Packet1cd (const Packet2d & a) inline explicit
 : v(a) {}
Packet1cd() [6/10]
EIGEN_STRONG_INLINE Eigen::internal::Packet1cd::Packet1cd (const Packet1cd & a) inline
 : v(a.v) {}
Packet1cd() [7/10]
EIGEN_STRONG_INLINE Eigen::internal::Packet1cd::Packet1cd () inline
 {}
Packet1cd() [8/10]
EIGEN_STRONG_INLINE Eigen::internal::Packet1cd::Packet1cd (const __m128d & a) inline explicit
 : v(a) {}
Packet1cd() [9/10]
EIGEN_STRONG_INLINE Eigen::internal::Packet1cd::Packet1cd () inline
 {}
Packet1cd() [10/10]
EIGEN_STRONG_INLINE Eigen::internal::Packet1cd::Packet1cd (const Packet2d & a) inline explicit
 : v(a) {}
Member Function Documentation
conjugate()
EIGEN_STRONG_INLINE Packet1cd Eigen::internal::Packet1cd::conjugate (void) const inline
{
     static const v2u64 p2ul_CONJ_XOR = {0x0, 0x8000000000000000};
     return (Packet1cd)pxor(v, (Packet2d)p2ul_CONJ_XOR);
   }
References Eigen::internal::pxor(), and v.
operator*()
EIGEN_STRONG_INLINE Packet1cd Eigen::internal::Packet1cd::operator* (const Packet1cd & b) const inline
 { return Packet1cd(*this) *= b; }
References b, and Packet1cd().
operator*=()
EIGEN_STRONG_INLINE Packet1cd& Eigen::internal::Packet1cd::operator*= (const Packet1cd & b) inline
{
     Packet2d v1, v2;
     // Get the real values of a | a1_re | a1_re
     v1 = (Packet2d)__builtin_msa_ilvev_d((v2i64)v, (v2i64)v);
     // Get the imag values of a | a1_im | a1_im
     v2 = (Packet2d)__builtin_msa_ilvod_d((v2i64)v, (v2i64)v);
     // Multiply the real a with b
     v1 = pmul(v1, b.v);
     // Multiply the imag a with b
     v2 = pmul(v2, b.v);
     // Conjugate v2
     v2 = Packet1cd(v2).conjugate().v;
     // Swap real/imag elements in v2.
     v2 = (Packet2d)__builtin_msa_shf_w((v4i32)v2, EIGEN_MSA_SHF_I8(2, 3, 0, 1));
     // Add and return the result
     v = padd(v1, v2);
     return *this;
   }
References b, EIGEN_MSA_SHF_I8, Packet1cd(), Eigen::internal::padd(), Eigen::internal::pmul(), v, v1(), and v2().
operator+()
EIGEN_STRONG_INLINE Packet1cd Eigen::internal::Packet1cd::operator+ (const Packet1cd & b) const inline
 { return Packet1cd(*this) += b; }
References b, and Packet1cd().
operator+=()
EIGEN_STRONG_INLINE Packet1cd& Eigen::internal::Packet1cd::operator+= (const Packet1cd & b) inline
{
     v = padd(v, b.v);
     return *this;
   }
References b, Eigen::internal::padd(), and v.
operator-() [1/2]
EIGEN_STRONG_INLINE Packet1cd Eigen::internal::Packet1cd::operator- (const Packet1cd & b) const inline
 { return Packet1cd(*this) -= b; }
References b, and Packet1cd().
operator-() [2/2]
EIGEN_STRONG_INLINE Packet1cd Eigen::internal::Packet1cd::operator- (void) const inline
 { return Packet1cd(pnegate(v)); }
References Packet1cd(), Eigen::internal::pnegate(), and v.
operator-=()
EIGEN_STRONG_INLINE Packet1cd& Eigen::internal::Packet1cd::operator-= (const Packet1cd & b) inline
{
     v = psub(v, b.v);
     return *this;
   }
References b, Eigen::internal::psub(), and v.
operator/()
EIGEN_STRONG_INLINE Packet1cd Eigen::internal::Packet1cd::operator/ (const Packet1cd & b) const inline
 { return Packet1cd(*this) /= b; }
References b, and Packet1cd().
operator/=()
EIGEN_STRONG_INLINE Packet1cd& Eigen::internal::Packet1cd::operator/= (const Packet1cd & b) inline
{
     *this *= b.conjugate();
     Packet2d s = pmul<Packet2d>(b.v, b.v);
     s = padd(s, preverse<Packet2d>(s));
     v = pdiv(v, s);
     return *this;
   }
References b, Eigen::internal::padd(), Eigen::internal::pdiv(), Eigen::internal::pmul< Packet2d >(), s, and v.
operator=()
EIGEN_STRONG_INLINE Packet1cd& Eigen::internal::Packet1cd::operator= (const Packet1cd & b) inline
{
     v = b.v;
     return *this;
   }
References b, and v.
Member Data Documentation
v
Packet2d Eigen::internal::Packet1cd::v
Referenced by conjugate(), operator*=(), operator+=(), operator-(), operator-=(), operator/=(), operator=(), Packet1cd(), pload_complex_full(), pload_realimag_combine(), pload_realimag_combine_row(), and Eigen::internal::pmadd< Packet1cd >().
The documentation for this struct was generated from the following file:
LSX/Complex.h