MercuryDPM: Eigen::internal::imklfft::imklfft_impl< Scalar_ > Struct Template Reference
Eigen::internal::imklfft::imklfft_impl< Scalar_ > Struct Template Reference
#include <ei_imklfft_impl.h>
Public Types
typedef Scalar_ Scalar
typedef std::complex< Scalar > Complex
Public Member Functions
void clear ()
void fwd (Complex *dst, const Complex *src, int nfft)
void fwd (Complex *dst, const Scalar *src, int nfft)
void fwd2 (Complex *dst, const Complex *src, int n0, int n1)
void inv (Complex *dst, const Complex *src, int nfft)
void inv (Scalar *dst, const Complex *src, int nfft)
void inv2 (Complex *dst, const Complex *src, int n0, int n1)
Private Member Functions
plan< Scalar > & get_plan (int nfft, void *dst, const void *src)
plan< Scalar > & get_plan (int n0, int n1, void *dst, const void *src)
Private Attributes
std::map< int64_t, plan< Scalar > > m_plans
Member Typedef Documentation
Complex
template<typename Scalar_ > typedef std::complex<Scalar> Eigen::internal::imklfft::imklfft_impl< Scalar_ >::Complex
Scalar
template<typename Scalar_ > typedef Scalar_ Eigen::internal::imklfft::imklfft_impl< Scalar_ >::Scalar
Member Function Documentation
clear()
template<typename Scalar_ > void Eigen::internal::imklfft::imklfft_impl< Scalar_ >::clear () inline
 { m_plans.clear(); }
References Eigen::internal::imklfft::imklfft_impl< Scalar_ >::m_plans.
fwd() [1/2]
template<typename Scalar_ > void Eigen::internal::imklfft::imklfft_impl< Scalar_ >::fwd (Complex * dst, const Complex * src, int nfft) inline
{
     MKL_LONG size = nfft;
     get_plan(nfft, dst, src).forward(complex_cast(dst), complex_cast(src), size);
   }
References Eigen::internal::imklfft::complex_cast(), Eigen::internal::imklfft::imklfft_impl< Scalar_ >::get_plan(), and size.
fwd() [2/2]
template<typename Scalar_ > void Eigen::internal::imklfft::imklfft_impl< Scalar_ >::fwd (Complex * dst, const Scalar * src, int nfft) inline
{
     MKL_LONG size = nfft;
     get_plan(nfft, dst, src).forward(complex_cast(dst), const_cast<Scalar*>(src), nfft);
   }
References Eigen::internal::imklfft::complex_cast(), Eigen::internal::imklfft::imklfft_impl< Scalar_ >::get_plan(), and size.
fwd2()
template<typename Scalar_ > void Eigen::internal::imklfft::imklfft_impl< Scalar_ >::fwd2 (Complex * dst, const Complex * src, int n0, int n1) inline
{
     get_plan(n0, n1, dst, src).forward2(complex_cast(dst), complex_cast(src), n0, n1);
   }
References Eigen::internal::imklfft::complex_cast(), and Eigen::internal::imklfft::imklfft_impl< Scalar_ >::get_plan().
get_plan() [1/2]
template<typename Scalar_ > plan<Scalar>& Eigen::internal::imklfft::imklfft_impl< Scalar_ >::get_plan (int n0, int n1, void * dst, const void * src) inline private
{
     int inplace = (dst == src) ? 1 : 0;
     int aligned = ((reinterpret_cast<size_t>(src) & 15) | (reinterpret_cast<size_t>(dst) & 15)) == 0 ? 1 : 0;
     int64_t key = (((((int64_t)n0) << 31) | (n1 << 2) | (inplace << 1) | aligned) << 1) + 1;
     // Create element if key does not exist.
     return m_plans[key];
   }
References inplace(), and Eigen::internal::imklfft::imklfft_impl< Scalar_ >::m_plans.
get_plan() [2/2]
template<typename Scalar_ > plan<Scalar>& Eigen::internal::imklfft::imklfft_impl< Scalar_ >::get_plan (int nfft, void * dst, const void * src) inline private
{
     int inplace = dst == src ? 1 : 0;
     int aligned = ((reinterpret_cast<size_t>(src) & 15) | (reinterpret_cast<size_t>(dst) & 15)) == 0 ? 1 : 0;
     int64_t key = ((nfft << 2) | (inplace << 1) | aligned) << 1;
     // Create element if key does not exist.
     return m_plans[key];
   }
References inplace(), and Eigen::internal::imklfft::imklfft_impl< Scalar_ >::m_plans.
Referenced by Eigen::internal::imklfft::imklfft_impl< Scalar_ >::fwd(), Eigen::internal::imklfft::imklfft_impl< Scalar_ >::fwd2(), Eigen::internal::imklfft::imklfft_impl< Scalar_ >::inv(), and Eigen::internal::imklfft::imklfft_impl< Scalar_ >::inv2().
inv() [1/2]
template<typename Scalar_ > void Eigen::internal::imklfft::imklfft_impl< Scalar_ >::inv (Complex * dst, const Complex * src, int nfft) inline
{
     MKL_LONG size = nfft;
     get_plan(nfft, dst, src).inverse(complex_cast(dst), complex_cast(src), nfft);
   }
References Eigen::internal::imklfft::complex_cast(), Eigen::internal::imklfft::imklfft_impl< Scalar_ >::get_plan(), and size.
inv() [2/2]
template<typename Scalar_ > void Eigen::internal::imklfft::imklfft_impl< Scalar_ >::inv (Scalar * dst, const Complex * src, int nfft) inline
{
     MKL_LONG size = nfft;
     get_plan(nfft, dst, src).inverse(const_cast<Scalar*>(dst), complex_cast(src), nfft);
   }
References Eigen::internal::imklfft::complex_cast(), Eigen::internal::imklfft::imklfft_impl< Scalar_ >::get_plan(), and size.
inv2()
template<typename Scalar_ > void Eigen::internal::imklfft::imklfft_impl< Scalar_ >::inv2 (Complex * dst, const Complex * src, int n0, int n1) inline
{
     get_plan(n0, n1, dst, src).inverse2(complex_cast(dst), complex_cast(src), n0, n1);
   }
References Eigen::internal::imklfft::complex_cast(), and Eigen::internal::imklfft::imklfft_impl< Scalar_ >::get_plan().
Member Data Documentation
m_plans
template<typename Scalar_ > std::map<int64_t, plan<Scalar> > Eigen::internal::imklfft::imklfft_impl< Scalar_ >::m_plans private
Referenced by Eigen::internal::imklfft::imklfft_impl< Scalar_ >::clear(), and Eigen::internal::imklfft::imklfft_impl< Scalar_ >::get_plan().
The documentation for this struct was generated from the following file:
ei_imklfft_impl.h