MercuryDPM: CapProblem< ELEMENT > Class Template Reference
CapProblem< ELEMENT > Class Template Reference
Public Member Functions
CapProblem (const bool &hijack_internal)
~CapProblem ()
void parameter_study (const string &dir_name)
void actions_before_newton_convergence_check ()
Update the spine mesh after every Newton step.
void create_volume_constraint_elements ()
Create the volume constraint elements.
void doc_solution (DocInfo &doc_info)
Doc the solution.
CapProblem (const unsigned &Nr, const unsigned &Nz1, const unsigned &Nz2, const double &width)
Constructor.
void set_boundary_conditions ()
Set boundary conditions on the wall.
void solve_system ()
Solve the problem.
void create_volume_constraint_elements ()
Create the volume constraint elements.
void actions_before_newton_convergence_check ()
Update the spine mesh after every Newton step.
CapProblem (const bool &hijack_internal)
~CapProblem ()
void parameter_study (const string &dir_name)
void actions_before_newton_convergence_check ()
Update the spine mesh after every Newton step.
void create_volume_constraint_elements ()
Create the volume constraint elements.
void doc_solution (DocInfo &doc_info)
Doc the solution.
CapProblem (const unsigned &Nx, const unsigned &Nh1, const unsigned &Nh2)
Constructor.
void parameter_study ()
Peform a parameter study: Solve problem for a range of contact angles.
void finish_problem_setup ()
Finish full specification of the elements.
void actions_before_newton_convergence_check ()
Update the spine mesh after every Newton step.
void create_volume_constraint_elements ()
Create the volume constraint elements.
void doc_solution (DocInfo &doc_info)
Doc the solution.
Public Member Functions inherited from oomph::Problem
virtual void debug_hook_fct (const unsigned &i)
void set_analytic_dparameter (double *const &parameter_pt)
void unset_analytic_dparameter (double *const &parameter_pt)
bool is_dparameter_calculated_analytically (double *const &parameter_pt)
void set_analytic_hessian_products ()
void unset_analytic_hessian_products ()
bool are_hessian_products_calculated_analytically ()
void set_pinned_values_to_zero ()
bool distributed () const
virtual void actions_before_adapt ()
virtual void actions_after_adapt ()
Actions that are to be performed after a mesh adaptation.
OomphCommunicator * communicator_pt ()
access function to the oomph-lib communicator
const OomphCommunicator * communicator_pt () const
access function to the oomph-lib communicator, const version
Problem ()
Problem (const Problem &dummy)=delete
Broken copy constructor.
void operator= (const Problem &)=delete
Broken assignment operator.
virtual ~Problem ()
Virtual destructor to clean up memory.
Mesh *& mesh_pt ()
Return a pointer to the global mesh.
Mesh *const & mesh_pt () const
Return a pointer to the global mesh (const version)
Mesh *& mesh_pt (const unsigned &imesh)
Mesh *const & mesh_pt (const unsigned &imesh) const
Return a pointer to the i-th submesh (const version)
unsigned nsub_mesh () const
Return number of submeshes.
unsigned add_sub_mesh (Mesh *const &mesh_pt)
void flush_sub_meshes ()
void build_global_mesh ()
void rebuild_global_mesh ()
LinearSolver *& linear_solver_pt ()
Return a pointer to the linear solver object.
LinearSolver *const & linear_solver_pt () const
Return a pointer to the linear solver object (const version)
LinearSolver *& mass_matrix_solver_for_explicit_timestepper_pt ()
LinearSolver * mass_matrix_solver_for_explicit_timestepper_pt () const
EigenSolver *& eigen_solver_pt ()
Return a pointer to the eigen solver object.
EigenSolver *const & eigen_solver_pt () const
Return a pointer to the eigen solver object (const version)
Time *& time_pt ()
Return a pointer to the global time object.
Time * time_pt () const
Return a pointer to the global time object (const version).
double & time ()
Return the current value of continuous time.
double time () const
Return the current value of continuous time (const version)
TimeStepper *& time_stepper_pt ()
const TimeStepper * time_stepper_pt () const
TimeStepper *& time_stepper_pt (const unsigned &i)
Return a pointer to the i-th timestepper.
ExplicitTimeStepper *& explicit_time_stepper_pt ()
Return a pointer to the explicit timestepper.
unsigned long set_timestepper_for_all_data (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data=false)
virtual void shift_time_values ()
Shift all values along to prepare for next timestep.
AssemblyHandler *& assembly_handler_pt ()
Return a pointer to the assembly handler object.
AssemblyHandler *const & assembly_handler_pt () const
Return a pointer to the assembly handler object (const version)
double & minimum_dt ()
Access function to min timestep in adaptive timestepping.
double & maximum_dt ()
Access function to max timestep in adaptive timestepping.
unsigned & max_newton_iterations ()
Access function to max Newton iterations before giving up.
void problem_is_nonlinear (const bool &prob_lin)
Access function to Problem_is_nonlinear.
double & max_residuals ()
bool & time_adaptive_newton_crash_on_solve_fail ()
Access function for Time_adaptive_newton_crash_on_solve_fail.
double & newton_solver_tolerance ()
void add_time_stepper_pt (TimeStepper *const &time_stepper_pt)
void set_explicit_time_stepper_pt (ExplicitTimeStepper *const &explicit_time_stepper_pt)
void initialise_dt (const double &dt)
void initialise_dt (const Vector< double > &dt)
Data *& global_data_pt (const unsigned &i)
Return a pointer to the the i-th global data object.
void add_global_data (Data *const &global_data_pt)
void flush_global_data ()
LinearAlgebraDistribution *const & dof_distribution_pt () const
Return the pointer to the dof distribution (read-only)
unsigned long ndof () const
Return the number of dofs.
unsigned ntime_stepper () const
Return the number of time steppers.
unsigned nglobal_data () const
Return the number of global data values.
unsigned self_test ()
Self-test: Check meshes and global data. Return 0 for OK.
void enable_store_local_dof_pt_in_elements ()
void disable_store_local_dof_pt_in_elements ()
unsigned long assign_eqn_numbers (const bool &assign_local_eqn_numbers=true)
void describe_dofs (std::ostream &out= *(oomph_info.stream_pt())) const
void enable_discontinuous_formulation ()
void disable_discontinuous_formulation ()
void get_dofs (DoubleVector &dofs) const
void get_dofs (const unsigned &t, DoubleVector &dofs) const
Return vector of the t'th history value of all dofs.
void set_dofs (const DoubleVector &dofs)
Set the values of the dofs.
void set_dofs (const unsigned &t, DoubleVector &dofs)
Set the history values of the dofs.
void set_dofs (const unsigned &t, Vector< double * > &dof_pt)
void add_to_dofs (const double &lambda, const DoubleVector &increment_dofs)
Add lambda x incremenet_dofs[l] to the l-th dof.
double * global_dof_pt (const unsigned &i)
double & dof (const unsigned &i)
i-th dof in the problem
double dof (const unsigned &i) const
i-th dof in the problem (const version)
double *& dof_pt (const unsigned &i)
Pointer to i-th dof in the problem.
double * dof_pt (const unsigned &i) const
Pointer to i-th dof in the problem (const version)
virtual void get_inverse_mass_matrix_times_residuals (DoubleVector &Mres)
virtual void get_dvaluesdt (DoubleVector &f)
virtual void get_residuals (DoubleVector &residuals)
Get the total residuals Vector for the problem.
virtual void get_jacobian (DoubleVector &residuals, DenseDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CRDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CCDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, SumOfMatrices &jacobian)
void get_fd_jacobian (DoubleVector &residuals, DenseMatrix< double > &jacobian)
Get the full Jacobian by finite differencing.
void get_derivative_wrt_global_parameter (double *const &parameter_pt, DoubleVector &result)
void get_hessian_vector_products (DoubleVectorWithHaloEntries const &Y, Vector< DoubleVectorWithHaloEntries > const &C, Vector< DoubleVectorWithHaloEntries > &product)
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, Vector< DoubleVector > &eigenvector, const bool &steady=true)
Solve the eigenproblem.
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, const bool &steady=true)
virtual void get_eigenproblem_matrices (CRDoubleMatrix &mass_matrix, CRDoubleMatrix &main_matrix, const double &shift=0.0)
void assign_eigenvector_to_dofs (DoubleVector &eigenvector)
Assign the eigenvector passed to the function to the dofs.
void add_eigenvector_to_dofs (const double &epsilon, const DoubleVector &eigenvector)
void store_current_dof_values ()
Store the current values of the degrees of freedom.
void restore_dof_values ()
Restore the stored values of the degrees of freedom.
void enable_jacobian_reuse ()
void disable_jacobian_reuse ()
Disable recycling of Jacobian in Newton iteration.
bool jacobian_reuse_is_enabled ()
Is recycling of Jacobian in Newton iteration enabled?
bool & use_predictor_values_as_initial_guess ()
void newton_solve ()
Use Newton method to solve the problem.
void enable_globally_convergent_newton_method ()
enable globally convergent Newton method
void disable_globally_convergent_newton_method ()
disable globally convergent Newton method
void newton_solve (unsigned const &max_adapt)
void steady_newton_solve (unsigned const &max_adapt=0)
void copy (Problem *orig_problem_pt)
virtual Problem * make_copy ()
virtual void read (std::ifstream &restart_file, bool &unsteady_restart)
virtual void read (std::ifstream &restart_file)
virtual void dump (std::ofstream &dump_file) const
void dump (const std::string &dump_file_name) const
void delete_all_external_storage ()
virtual void symmetrise_eigenfunction_for_adaptive_pitchfork_tracking ()
double * bifurcation_parameter_pt () const
void get_bifurcation_eigenfunction (Vector< DoubleVector > &eigenfunction)
void activate_fold_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const DoubleVector &normalisation, const bool &block_solve=true)
void activate_pitchfork_tracking (double *const &parameter_pt, const DoubleVector &symmetry_vector, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const double &omega, const DoubleVector &null_real, const DoubleVector &null_imag, const bool &block_solve=true)
void deactivate_bifurcation_tracking ()
void reset_assembly_handler_to_default ()
Reset the system to the standard non-augemented state.
double arc_length_step_solve (double *const &parameter_pt, const double &ds, const unsigned &max_adapt=0)
double arc_length_step_solve (Data *const &data_pt, const unsigned &data_index, const double &ds, const unsigned &max_adapt=0)
void reset_arc_length_parameters ()
int & sign_of_jacobian ()
void explicit_timestep (const double &dt, const bool &shift_values=true)
Take an explicit timestep of size dt.
void unsteady_newton_solve (const double &dt)
void unsteady_newton_solve (const double &dt, const bool &shift_values)
void unsteady_newton_solve (const double &dt, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const unsigned &suppress_resolve_after_spatial_adapt_flag, const bool &first, const bool &shift=true)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon, const bool &shift_values)
void assign_initial_values_impulsive ()
void assign_initial_values_impulsive (const double &dt)
void calculate_predictions ()
Calculate predictions.
void enable_mass_matrix_reuse ()
void disable_mass_matrix_reuse ()
bool mass_matrix_reuse_is_enabled ()
Return whether the mass matrix is being reused.
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly (DocInfo &doc_info)
void refine_uniformly_and_prune (DocInfo &doc_info)
void refine_uniformly ()
void refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform refinement for submesh i_mesh with documentation.
void refine_uniformly (const unsigned &i_mesh)
Do uniform refinement for submesh i_mesh without documentation.
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly (DocInfo &doc_info)
void p_refine_uniformly_and_prune (DocInfo &doc_info)
void p_refine_uniformly ()
void p_refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-refinement for submesh i_mesh with documentation.
void p_refine_uniformly (const unsigned &i_mesh)
Do uniform p-refinement for submesh i_mesh without documentation.
void refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const unsigned &i_mesh, const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void refine_selected_elements (const Vector< Vector< RefineableElement * >> &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void p_refine_selected_elements (const Vector< Vector< PRefineableElement * >> &elements_to_be_refined_pt)
unsigned unrefine_uniformly ()
unsigned unrefine_uniformly (const unsigned &i_mesh)
void p_unrefine_uniformly (DocInfo &doc_info)
void p_unrefine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-unrefinement for submesh i_mesh without documentation.
void adapt (unsigned &n_refined, unsigned &n_unrefined)
void adapt ()
void p_adapt (unsigned &n_refined, unsigned &n_unrefined)
void p_adapt ()
void adapt_based_on_error_estimates (unsigned &n_refined, unsigned &n_unrefined, Vector< Vector< double >> &elemental_error)
void adapt_based_on_error_estimates (Vector< Vector< double >> &elemental_error)
void get_all_error_estimates (Vector< Vector< double >> &elemental_error)
void doc_errors (DocInfo &doc_info)
Get max and min error for all elements in submeshes.
void doc_errors ()
Get max and min error for all elements in submeshes.
void enable_info_in_newton_solve ()
void disable_info_in_newton_solve ()
Disable the output of information when in the newton solver.
Public Member Functions inherited from oomph::ExplicitTimeSteppableObject
ExplicitTimeSteppableObject ()
Empty constructor.
ExplicitTimeSteppableObject (const ExplicitTimeSteppableObject &)=delete
Broken copy constructor.
void operator= (const ExplicitTimeSteppableObject &)=delete
Broken assignment operator.
virtual ~ExplicitTimeSteppableObject ()
Empty destructor.
virtual void actions_before_explicit_stage ()
virtual void actions_after_explicit_stage ()
Public Attributes
TwoLayerSpineMesh< SpineElement< ELEMENT > > * Bulk_mesh_pt
Pointer to the mesh.
Public Attributes inherited from oomph::Problem
bool Shut_up_in_newton_solve
Private Attributes
double Ca
The Capillary number.
double Volume
The volume of the fluid.
double Pext
The external pressure.
double Angle
The contact angle.
SingleLayerSpineMesh< SpineElement< ELEMENT > > * Bulk_mesh_pt
The bulk mesh of fluid elements.
Mesh * Surface_mesh_pt
The mesh for the interface elements.
Mesh * Point_mesh_pt
The mesh for the element at the contact point.
Mesh * Volume_constraint_mesh_pt
The volume constraint mesh.
ofstream Trace_file
Trace file.
Data * External_pressure_data_pt
Data object whose single value stores the external pressure.
Data * Traded_pressure_data_pt
Data that is traded for the volume constraint.
Additional Inherited Members
Public Types inherited from oomph::Problem
typedef void(* SpatialErrorEstimatorFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error)
Function pointer for spatial error estimator.
typedef void(* SpatialErrorEstimatorWithDocFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error, DocInfo &doc_info)
Function pointer for spatial error estimator with doc.
Static Public Attributes inherited from oomph::Problem
static bool Suppress_warning_about_actions_before_read_unstructured_meshes
Protected Types inherited from oomph::Problem
enum Assembly_method {
Perform_assembly_using_vectors_of_pairs , Perform_assembly_using_two_vectors , Perform_assembly_using_maps , Perform_assembly_using_lists ,
Perform_assembly_using_two_arrays
}
Enumerated flags to determine which sparse assembly method is used.
Protected Member Functions inherited from oomph::Problem
unsigned setup_element_count_per_dof ()
virtual void sparse_assemble_row_or_column_compressed (Vector< int * > &column_or_row_index, Vector< int * > &row_or_column_start, Vector< double * > &value, Vector< unsigned > &nnz, Vector< double * > &residual, bool compressed_row_flag)
virtual void actions_before_newton_solve ()
virtual void actions_after_newton_solve ()
virtual void actions_before_newton_step ()
virtual void actions_after_newton_step ()
virtual void actions_before_implicit_timestep ()
virtual void actions_after_implicit_timestep ()
virtual void actions_after_implicit_timestep_and_error_estimation ()
virtual void actions_before_explicit_timestep ()
Actions that should be performed before each explicit time step.
virtual void actions_after_explicit_timestep ()
Actions that should be performed after each explicit time step.
virtual void actions_before_read_unstructured_meshes ()
virtual void actions_after_read_unstructured_meshes ()
virtual void actions_after_change_in_global_parameter (double *const &parameter_pt)
virtual void actions_after_change_in_bifurcation_parameter ()
virtual void actions_after_parameter_increase (double *const &parameter_pt)
double & dof_derivative (const unsigned &i)
double & dof_current (const unsigned &i)
virtual void set_initial_condition ()
virtual double global_temporal_error_norm ()
unsigned newton_solve_continuation (double *const &parameter_pt)
unsigned newton_solve_continuation (double *const &parameter_pt, DoubleVector &z)
void calculate_continuation_derivatives (double *const &parameter_pt)
void calculate_continuation_derivatives (const DoubleVector &z)
void calculate_continuation_derivatives_fd (double *const &parameter_pt)
bool does_pointer_correspond_to_problem_data (double *const &parameter_pt)
void set_consistent_pinned_values_for_continuation ()
Protected Attributes inherited from oomph::Problem
Vector< Problem * > Copy_of_problem_pt
std::map< double *, bool > Calculate_dparameter_analytic
bool Calculate_hessian_products_analytic
LinearAlgebraDistribution * Dof_distribution_pt
Vector< double * > Dof_pt
Vector of pointers to dofs.
DoubleVectorWithHaloEntries Element_count_per_dof
double Relaxation_factor
double Newton_solver_tolerance
unsigned Max_newton_iterations
Maximum number of Newton iterations.
unsigned Nnewton_iter_taken
Vector< double > Max_res
Maximum residuals at start and after each newton iteration.
double Max_residuals
bool Time_adaptive_newton_crash_on_solve_fail
bool Jacobian_reuse_is_enabled
Is re-use of Jacobian in Newton iteration enabled? Default: false.
bool Jacobian_has_been_computed
bool Problem_is_nonlinear
bool Pause_at_end_of_sparse_assembly
bool Doc_time_in_distribute
unsigned Sparse_assembly_method
unsigned Sparse_assemble_with_arrays_initial_allocation
unsigned Sparse_assemble_with_arrays_allocation_increment
Vector< Vector< unsigned > > Sparse_assemble_with_arrays_previous_allocation
double Numerical_zero_for_sparse_assembly
double FD_step_used_in_get_hessian_vector_products
bool Mass_matrix_reuse_is_enabled
bool Mass_matrix_has_been_computed
bool Discontinuous_element_formulation
double Minimum_dt
Minimum desired dt: if dt falls below this value, exit.
double Maximum_dt
Maximum desired dt.
double DTSF_max_increase
double DTSF_min_decrease
double Minimum_dt_but_still_proceed
bool Scale_arc_length
Boolean to control whether arc-length should be scaled.
double Desired_proportion_of_arc_length
Proportion of the arc-length to taken by the parameter.
double Theta_squared
int Sign_of_jacobian
Storage for the sign of the global Jacobian.
double Continuation_direction
double Parameter_derivative
Storage for the derivative of the global parameter wrt arc-length.
double Parameter_current
Storage for the present value of the global parameter.
bool Use_continuation_timestepper
Boolean to control original or new storage of dof stuff.
unsigned Dof_derivative_offset
unsigned Dof_current_offset
Vector< double > Dof_derivative
Storage for the derivative of the problem variables wrt arc-length.
Vector< double > Dof_current
Storage for the present values of the variables.
double Ds_current
Storage for the current step value.
unsigned Desired_newton_iterations_ds
double Minimum_ds
Minimum desired value of arc-length.
bool Bifurcation_detection
Boolean to control bifurcation detection via determinant of Jacobian.
bool Bisect_to_find_bifurcation
Boolean to control wheter bisection is used to located bifurcation.
bool First_jacobian_sign_change
Boolean to indicate whether a sign change has occured in the Jacobian.
bool Arc_length_step_taken
Boolean to indicate whether an arc-length step has been taken.
bool Use_finite_differences_for_continuation_derivatives
OomphCommunicator * Communicator_pt
The communicator for this problem.
bool Always_take_one_newton_step
double Timestep_reduction_factor_after_nonconvergence
bool Keep_temporal_error_below_tolerance
Static Protected Attributes inherited from oomph::Problem
static ContinuationStorageScheme Continuation_time_stepper
Storage for the single static continuation timestorage object.
Detailed Description
template<class ELEMENT>
class CapProblem< ELEMENT >
A Problem class that solves the Navier–Stokes equations + free surface in an axisymmetric geometry using a spine-based node update
A Problem class that solves the Navier–Stokes equations in an axisymmetric geometry N.B. we usually template problems by element-type and a timestepper in any problems where different elements or timesteppers MAY be used
A Problem class that solves the Navier–Stokes equations + free surface in a 2D geometry using a spine-based node update
Constructor & Destructor Documentation
CapProblem() [1/4]
template<class ELEMENT > CapProblem< ELEMENT >::CapProblem (const bool & hijack_internal)
Constructor: Pass boolean flag to indicate if the volume constraint is applied by hijacking an internal pressure or the external pressure
                                                            :
  Ca(2.1),  //Initialise value of Ca to some random value
  Volume(0.125),  //Initialise the value of the volume:
                  //the physical volume divided by 2pi
  Pext(1.23),  //Initialise the external pressure to some random value
  Angle(0.5*MathematicalConstants::Pi) //Initialise the contact angle
 {
  //Set the wall normal
  Global_Physical_Variables::Wall_normal.resize(2);
  Global_Physical_Variables::Wall_normal[0] = 1.0;
  Global_Physical_Variables::Wall_normal[1] = 0.0;
  // Number of elements in the horizontal direction
  unsigned nx=4;
  // Number of elements in the vertical direction
  unsigned nh=4;
  // Halfwidth of domain
  double half_width=0.5;
  //Construct bulk mesh
  Bulk_mesh_pt =
   new SingleLayerSpineMesh<SpineElement<ELEMENT> >(nx,nh,half_width,1.0);
  //Create the surface mesh that will contain the interface elements
  //First create storage, but with no elements or nodes
  Surface_mesh_pt = new Mesh;
  //Also create storage for a point mesh that contain the single element
  //responsible for  enforcing the contact angle condition
  Point_mesh_pt = new Mesh;
  //Loop over the horizontal elements adjacent to the upper surface
  //(boundary 2) and create the surface elements
  unsigned n_boundary_element = Bulk_mesh_pt->nboundary_element(2);
  for(unsigned e=0;e<n_boundary_element;e++)
   {
    //Construct a new 1D line element adjacent to boundary 2
    FiniteElement *interface_element_pt =
     new SpineAxisymmetricFluidInterfaceElement<SpineElement<ELEMENT> >(
      Bulk_mesh_pt->boundary_element_pt(2,e),
      Bulk_mesh_pt->face_index_at_boundary(2,e));
    //Push it back onto the stack
    this->Surface_mesh_pt->add_element_pt(interface_element_pt);
    //Find the (single) node that is on the solid boundary (boundary 1)
    unsigned n_node = interface_element_pt->nnode();
    //We only need to check the right-hand nodes (because I know the
    //ordering of the nodes within the element)
    if(interface_element_pt->node_pt(n_node-1)->is_on_boundary(1))
     {
      //Make the point (contact) element from right-hand edge of the element
      FiniteElement* point_element_pt =
       dynamic_cast<SpineAxisymmetricFluidInterfaceElement<
        SpineElement<ELEMENT> >*>(interface_element_pt)
       ->make_bounding_element(1);
      //Add it to the mesh
      this->Point_mesh_pt->add_element_pt(point_element_pt);
     }
   }
  //Create a Data object whose single value stores the
  //external pressure
  External_pressure_data_pt = new Data(1);
  // Set external pressure
  External_pressure_data_pt->set_value(0,Pext);
  // Which pressure are we trading for the volume constraint: We
  // can either hijack an internal pressure or use the external pressure.
  if (hijack_internal)
   {
    // The external pressure is pinned -- the external pressure
    // sets the pressure throughout the domain -- we do not have
    // the liberty to fix another pressure value!
    External_pressure_data_pt->pin(0);
    //Hijack one of the pressure values in the fluid and use it
    //as the pressure whose value is determined by the volume constraint.
    //(Its value will affect the residual of that element but it will not
    //be determined by it, i.e. it's hijacked).
    Traded_pressure_data_pt = dynamic_cast<ELEMENT*>(
     Bulk_mesh_pt->element_pt(0))->hijack_internal_value(0,0);
   }
  else
   {
    // Regard the external pressure as an unknown and add
    // it to the problem's global data so it gets included
    // in the equation numbering. Note that, at the moment,
    // there's no equation that determines its value!
    add_global_data(External_pressure_data_pt);
    // Declare the external pressure to be the pressure determined
    // by the volume constraint, i.e. the pressure that's "traded":
    Traded_pressure_data_pt = External_pressure_data_pt;
    // Since the external pressure is "traded" for the volume constraint,
    // it no longer sets the overall pressure, and we
    // can add an arbitrary constant to all pressures. To make
    // the solution unique, we pin a single pressure value in the bulk:
    // We arbitrarily set the pressure dof 0 in element 0 to zero.
    dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(0))->fix_pressure(0,0.0);
   }
  // Loop over the elements on the interface to pass pointer to Ca and
  // the pointers to the Data items that contains the single
  // (pressure) value that is "traded" for the volume constraint
  // and the external pressure
  unsigned n_interface = Surface_mesh_pt->nelement();
  for(unsigned e=0;e<n_interface;e++)
   {
    //Cast to a 1D element
    SpineAxisymmetricFluidInterfaceElement<SpineElement<ELEMENT> >*el_pt=
     dynamic_cast<SpineAxisymmetricFluidInterfaceElement<SpineElement<ELEMENT> >*>
     (Surface_mesh_pt->element_pt(e));
    //Set the Capillary number
    el_pt->ca_pt() = &Ca;
    //Pass the Data item that contains the single external pressure value
    el_pt->set_external_pressure_data(External_pressure_data_pt);
   }
  //Set the boundary conditions
  //Pin the velocities on all boundaries apart from the free surface
  //(boundary 2) where all velocities are free, and apart from the symmetry
  //line (boundary 3) where only the horizontal velocity is pinned
  unsigned n_bound=Bulk_mesh_pt->nboundary();
  for (unsigned b=0;b<n_bound;b++)
   {
    if (b!=2)
     {
      //Find the number of nodes on the boundary
      unsigned n_boundary_node = Bulk_mesh_pt->nboundary_node(b);
      //Loop over the nodes on the boundary
      for(unsigned n=0;n<n_boundary_node;n++)
       {
        Bulk_mesh_pt->boundary_node_pt(b,n)->pin(0);
        Bulk_mesh_pt->boundary_node_pt(b,n)->pin(2);
        if (b!=3)
         {
          Bulk_mesh_pt->boundary_node_pt(b,n)->pin(1);
         }
       }
     }
   }
  // Set the contact angle boundary condition for the rightmost element
  // (pass pointer to double that specifies the contact angle)
  FluidInterfaceBoundingElement *contact_angle_element_pt
   = dynamic_cast<FluidInterfaceBoundingElement*>(
    Point_mesh_pt->element_pt(0));
  contact_angle_element_pt->set_contact_angle(&Angle);
  contact_angle_element_pt->ca_pt() = &Ca;
  contact_angle_element_pt->wall_unit_normal_fct_pt()
   =  &Global_Physical_Variables::wall_unit_normal_fct;
  //Now add the volume constraint
  create_volume_constraint_elements();
  this->add_sub_mesh(Bulk_mesh_pt);
  this->add_sub_mesh(Surface_mesh_pt);
  this->add_sub_mesh(Point_mesh_pt);
  this->add_sub_mesh(Volume_constraint_mesh_pt);
  this->build_global_mesh();
  //Setup all the equation numbering and look-up schemes
  cout << "Number of unknowns: " << assign_eqn_numbers() << std::endl;
 }
References oomph::Mesh::add_element_pt(), oomph::Problem::add_global_data(), oomph::Problem::add_sub_mesh(), CapProblem< ELEMENT >::Angle, oomph::Problem::assign_eqn_numbers(), b, oomph::Mesh::boundary_element_pt(), oomph::Mesh::boundary_node_pt(), oomph::Problem::build_global_mesh(), CapProblem< ELEMENT >::Bulk_mesh_pt, CapProblem< ELEMENT >::Ca, oomph::FluidInterfaceBoundingElement::ca_pt(), oomph::FluidInterfaceElement::ca_pt(), CapProblem< ELEMENT >::create_volume_constraint_elements(), e(), oomph::Mesh::element_pt(), CapProblem< ELEMENT >::External_pressure_data_pt, oomph::Mesh::face_index_at_boundary(), oomph::Node::is_on_boundary(), n, oomph::Mesh::nboundary(), oomph::Mesh::nboundary_element(), oomph::Mesh::nboundary_node(), oomph::Mesh::nelement(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), Mesh_Parameters::nx, CapProblem< ELEMENT >::Pext, oomph::Data::pin(), CapProblem< ELEMENT >::Point_mesh_pt, oomph::FluidInterfaceBoundingElement::set_contact_angle(), oomph::FluidInterfaceElement::set_external_pressure_data(), oomph::Data::set_value(), CapProblem< ELEMENT >::Surface_mesh_pt, CapProblem< ELEMENT >::Traded_pressure_data_pt, CapProblem< ELEMENT >::Volume_constraint_mesh_pt, Global_Physical_Variables::Wall_normal, Global_Physical_Variables::wall_unit_normal_fct(), and oomph::FluidInterfaceBoundingElement::wall_unit_normal_fct_pt().
~CapProblem() [1/2]
template<class ELEMENT > CapProblem< ELEMENT >::~CapProblem
Destructor. Make sure to clean up all allocated memory, so that multiple instances of the problem don't lead to excessive memory usage.
 {
  //Loop over the volume mesh and delete the elements
  unsigned n_element = Volume_constraint_mesh_pt->nelement();
  for(unsigned e=0;e<n_element;e++)
   {delete Volume_constraint_mesh_pt->element_pt(e);}
  //Now flush the storage
  Volume_constraint_mesh_pt->flush_element_and_node_storage();
  //Now delete the mesh
  delete Volume_constraint_mesh_pt;
  //Delete the traded pressure if not the same as the external pressure
  if(Traded_pressure_data_pt!=External_pressure_data_pt)
   {delete Traded_pressure_data_pt;}
   //Next delete the external data
  delete External_pressure_data_pt;
  //Loop over the point mesh and delete the elements
  n_element = Point_mesh_pt->nelement();
  for(unsigned e=0;e<n_element;e++)
   {delete Point_mesh_pt->element_pt(e);}
  //Now flush the storage
  Point_mesh_pt->flush_element_and_node_storage();
  //Then delete the mesh
  delete Point_mesh_pt;
  //Loop over the surface mesh and delete the elements
  n_element = Surface_mesh_pt->nelement();
  for(unsigned e=0;e<n_element;e++)
   {delete Surface_mesh_pt->element_pt(e);}
  //Now flush the storage
  Surface_mesh_pt->flush_element_and_node_storage();
  //Then delete the mesh
  delete Surface_mesh_pt;
  //Then delete the bulk mesh
  delete Bulk_mesh_pt;
 }
References e().
CapProblem() [2/4]
template<class ELEMENT > CapProblem< ELEMENT >::CapProblem (const unsigned & Nr, const unsigned & Nz1, const unsigned & Nz2, const double & width)
Constructor.
                                            :
  Ca(1.0),  //Initialise value of Ca to one
  Volume(0.125),  //Initialise the value of the volume to 0.125
  Angle(1.57)     //Initialise the value of the contact angle
 {
  //Set the wall normal (in the r-direction)
  Global_Physical_Variables::Wall_normal.resize(2);
  Global_Physical_Variables::Wall_normal[0] = 1.0;
  Global_Physical_Variables::Wall_normal[1] = 0.0;
  //Construct our mesh
  Bulk_mesh_pt =
   new TwoLayerSpineMesh<SpineElement<ELEMENT> >(Nr,Nz1,Nz2,width,1.0,1.0);
  Surface_mesh_pt = new Mesh;
  //Loop over the horizontal elements
  unsigned n_interface_lower = Bulk_mesh_pt->ninterface_lower();
  for(unsigned i=0;i<n_interface_lower;i++)
   {
    //Construct a new 1D line element adjacent to the interface
    FiniteElement *interface_element_pt =  new
     SpineAxisymmetricFluidInterfaceElement<SpineElement<ELEMENT> >(
      Bulk_mesh_pt->interface_lower_boundary_element_pt(i),
      Bulk_mesh_pt->interface_lower_face_index_at_boundary(i));
     this->Surface_mesh_pt->add_element_pt(interface_element_pt);
    }
 //Create the point mesh
  Point_mesh_pt = new Mesh;
  {
   //Make the point (contact) element from the last surface element
   FiniteElement* point_element_pt =
    dynamic_cast<SpineAxisymmetricFluidInterfaceElement<
     SpineElement<ELEMENT> >*>(Surface_mesh_pt->element_pt(n_interface_lower-1))
    ->make_bounding_element(1);
   //Add it to the mesh
   this->Point_mesh_pt->add_element_pt(point_element_pt);
  }
  //Set the linear solver (frontal solver) (function defined in Problem class)
  //linear_solver_pt() = new HSL_MA42;
  //We are going to hijack one of the pressure values and make a copy of it
  //in global data
  flush_global_data();
  //Hijack one of the pressure values in the upper fluid
  add_global_data(dynamic_cast<ELEMENT*>(Bulk_mesh_pt->upper_layer_element_pt(0))
   ->hijack_internal_value(0,0));
  Traded_pressure_data_pt = this->global_data_pt(0);
  //Loop over the elements on the free surface
  unsigned Ninterface = Surface_mesh_pt->nelement();
  for(unsigned e=0;e<Ninterface;e++)
   {
    //Cast to a 1D element
    SpineAxisymmetricFluidInterfaceElement<SpineElement<ELEMENT> >
     *el_pt =
     dynamic_cast<
     SpineAxisymmetricFluidInterfaceElement<SpineElement<ELEMENT> >*>
     (Surface_mesh_pt->element_pt(e));
    //Set the Capillary number
    el_pt->ca_pt() = &Ca;
   }
  //Set the boundary conditions
  //Pin all velocity components on the bottom, wall and top
  for(unsigned b=0;b<4;b++)
   {
    //Find the number of nodes on the boundary
    unsigned n_boundary_node = Bulk_mesh_pt->nboundary_node(b);
    //Loop over the nodes on the boundary
    for(unsigned n=0;n<n_boundary_node;n++)
     {
      for(unsigned i=0;i<3;i++)
       {
        Bulk_mesh_pt->boundary_node_pt(b,n)->pin(i);
       }
     }
   }
  //Axis boundary, pin u (component 0) and v (component 2), but leave w free
  for(unsigned b=4;b<6;b++)
   {
    //Find the number of nodes on the boundary
    unsigned Nboundary_node = Bulk_mesh_pt->nboundary_node(b);
    //Loop over the nodes on the boundary
    for(unsigned n=0;n<Nboundary_node;n++)
     {
      Bulk_mesh_pt->boundary_node_pt(b,n)->pin(0);
      Bulk_mesh_pt->boundary_node_pt(b,n)->pin(2);
     }
   }
  //Set the contact angle on the RHS
  dynamic_cast<FluidInterfaceBoundingElement*>
   (Point_mesh_pt->element_pt(0))->set_contact_angle(&Angle);
  dynamic_cast<FluidInterfaceBoundingElement*>
   (Point_mesh_pt->element_pt(0))->ca_pt() = &Ca;
  //Set the wall normal on the rhs
  dynamic_cast<FluidInterfaceBoundingElement*>
   (Point_mesh_pt->element_pt(0))->wall_unit_normal_fct_pt() =
   &Global_Physical_Variables::wall_unit_normal_fct;
  //Pin a single pressure value
  dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(0))->fix_pressure(0,0.0);
  this->create_volume_constraint_elements();
  this->add_sub_mesh(Bulk_mesh_pt);
  this->add_sub_mesh(Surface_mesh_pt);
  this->add_sub_mesh(Point_mesh_pt);
  this->add_sub_mesh(Volume_constraint_mesh_pt);
  this->build_global_mesh();
  //Setup all the equation numbering and look-up schemes
  //(function defined in Problem class)
  cout << assign_eqn_numbers() << std::endl;
 }
References oomph::Mesh::add_element_pt(), oomph::Problem::add_global_data(), oomph::Problem::add_sub_mesh(), CapProblem< ELEMENT >::Angle, oomph::Problem::assign_eqn_numbers(), b, oomph::Mesh::boundary_node_pt(), oomph::Problem::build_global_mesh(), CapProblem< ELEMENT >::Bulk_mesh_pt, CapProblem< ELEMENT >::Ca, oomph::FluidInterfaceElement::ca_pt(), CapProblem< ELEMENT >::create_volume_constraint_elements(), e(), oomph::Mesh::element_pt(), oomph::Problem::flush_global_data(), oomph::Problem::global_data_pt(), i, n, oomph::Mesh::nboundary_node(), oomph::Mesh::nelement(), Global_Parameters::Nr, oomph::Data::pin(), CapProblem< ELEMENT >::Point_mesh_pt, CapProblem< ELEMENT >::Surface_mesh_pt, CapProblem< ELEMENT >::Traded_pressure_data_pt, CapProblem< ELEMENT >::Volume_constraint_mesh_pt, Global_Physical_Variables::Wall_normal, and Global_Physical_Variables::wall_unit_normal_fct().
CapProblem() [3/4]
template<class ELEMENT > CapProblem< ELEMENT >::CapProblem (const bool & hijack_internal)
~CapProblem() [2/2]
template<class ELEMENT > CapProblem< ELEMENT >::~CapProblem ()
CapProblem() [4/4]
template<class ELEMENT > CapProblem< ELEMENT >::CapProblem (const unsigned & Nx, const unsigned & Nh1, const unsigned & Nh2)
Constructor.
                                                                :
  Ca(2.1),  //Initialise value of Ca to some random value
  Volume(0.5),  //Initialise the value of the volume
  Angle(0.5*MathematicalConstants::Pi) //Initialise the contact angle
 {
  Global_Physical_Variables::Wall_normal.resize(2);
  Global_Physical_Variables::Wall_normal[0] = 1.0;
  Global_Physical_Variables::Wall_normal[1] = 0.0;
  //Construct our mesh
  Bulk_mesh_pt = new TwoLayerSpineMesh<SpineElement<ELEMENT> >
  (Nx,Nh1,Nh2,0.5,1.0,1.0);
  Surface_mesh_pt = new Mesh;
  //Loop over the horizontal elements
  unsigned n_interface_lower = Bulk_mesh_pt->ninterface_lower();
  for(unsigned i=0;i<n_interface_lower;i++)
   {
    //Construct a new 1D line element adjacent to the interface
    FiniteElement *interface_element_pt =  new
     SpineLineFluidInterfaceElement<SpineElement<ELEMENT> >(
      Bulk_mesh_pt->interface_lower_boundary_element_pt(i),
      Bulk_mesh_pt->interface_lower_face_index_at_boundary(i));
     this->Surface_mesh_pt->add_element_pt(interface_element_pt);
    }
 //Create the point mesh
 Point_mesh_pt = new Mesh;
  {
   //Make the point (contact) element from the last surface element
   FiniteElement* point_element_pt =
   dynamic_cast<SpineLineFluidInterfaceElement<
    SpineElement<ELEMENT> >*>(Surface_mesh_pt->element_pt(n_interface_lower-1))
    ->make_bounding_element(1);
  //Add it to the mesh
  this->Point_mesh_pt->add_element_pt(point_element_pt);
 }
  //Hijack one of the pressure values in the upper fluid. Its value
  //will affect the residual of that element but it will not
  //be determined by it!
  Traded_pressure_data_pt = dynamic_cast<ELEMENT*>(
   Bulk_mesh_pt->upper_layer_element_pt(0))->hijack_internal_value(0,0);
  // Loop over the elements on the interface to pass pointer to Ca and
  // the pointer to the Data item that contains the single
  // (pressure) value that is "traded" for the volume constraint
  unsigned n_interface = Surface_mesh_pt->nelement();
  for(unsigned e=0;e<n_interface;e++)
   {
    //Cast to a 1D element
    SpineLineFluidInterfaceElement<SpineElement<ELEMENT> >*el_pt=
    dynamic_cast<SpineLineFluidInterfaceElement<
     SpineElement<ELEMENT> >*>
     (Surface_mesh_pt->element_pt(e));
    //Set the Capillary number
    el_pt->ca_pt() = &Ca;
   }
  //Set the boundary conditions
  //Pin the velocities on all external boundaries apart from the symmetry
  //line (boundaries 4 and 5) where only the horizontal velocity is pinned
  for (unsigned b=0;b<6;b++)
   {
    //Find the number of nodes on the boundary
    unsigned n_boundary_node = Bulk_mesh_pt->nboundary_node(b);
    //Loop over the nodes on the boundary
    for(unsigned n=0;n<n_boundary_node;n++)
     {
      Bulk_mesh_pt->boundary_node_pt(b,n)->pin(0);
      if ((b!=4) && (b!=5))
       {
        Bulk_mesh_pt->boundary_node_pt(b,n)->pin(1);
       }
     }
   }
  // Set the contact angle boundary condition for the rightmost element
  dynamic_cast<FluidInterfaceBoundingElement*>(
   Point_mesh_pt->element_pt(0))->set_contact_angle(&Angle);
  dynamic_cast<FluidInterfaceBoundingElement*>(
   Point_mesh_pt->element_pt(0))->ca_pt() = &Ca;
  dynamic_cast<FluidInterfaceBoundingElement*>(
   Point_mesh_pt->element_pt(0))->wall_unit_normal_fct_pt() =
   &Global_Physical_Variables::wall_unit_normal_fct;
  // Pin a single pressure value: Set the pressure dof 0 in element 0
  // of the lower layer to zero.
  dynamic_cast<ELEMENT*>(Bulk_mesh_pt->lower_layer_element_pt(0))
   ->fix_pressure(0,0.0);
  this->create_volume_constraint_elements();
  this->add_sub_mesh(Bulk_mesh_pt);
  this->add_sub_mesh(Surface_mesh_pt);
  this->add_sub_mesh(Point_mesh_pt);
  this->add_sub_mesh(Volume_constraint_mesh_pt);
  this->build_global_mesh();
  //Setup all the equation numbering and look-up schemes
  cout << "Number of unknowns: " << assign_eqn_numbers() << std::endl;
 }
References oomph::Mesh::add_element_pt(), oomph::Problem::add_sub_mesh(), CapProblem< ELEMENT >::Angle, oomph::Problem::assign_eqn_numbers(), b, oomph::Mesh::boundary_node_pt(), oomph::Problem::build_global_mesh(), CapProblem< ELEMENT >::Bulk_mesh_pt, CapProblem< ELEMENT >::Ca, oomph::FluidInterfaceElement::ca_pt(), CapProblem< ELEMENT >::create_volume_constraint_elements(), e(), oomph::Mesh::element_pt(), i, n, oomph::Mesh::nboundary_node(), oomph::Mesh::nelement(), GlobalParameters::Nx, oomph::Data::pin(), CapProblem< ELEMENT >::Point_mesh_pt, CapProblem< ELEMENT >::Surface_mesh_pt, CapProblem< ELEMENT >::Traded_pressure_data_pt, CapProblem< ELEMENT >::Volume_constraint_mesh_pt, Global_Physical_Variables::Wall_normal, and Global_Physical_Variables::wall_unit_normal_fct().
Member Function Documentation
actions_before_newton_convergence_check() [1/4]
template<class ELEMENT > void CapProblem< ELEMENT >::actions_before_newton_convergence_check () inline virtual
Update the spine mesh after every Newton step.
Reimplemented from oomph::Problem.
 {Bulk_mesh_pt->node_update();}
actions_before_newton_convergence_check() [2/4]
template<class ELEMENT > void CapProblem< ELEMENT >::actions_before_newton_convergence_check () inline virtual
Update the spine mesh after every Newton step.
Reimplemented from oomph::Problem.
 {Bulk_mesh_pt->node_update();}
References oomph::SpineMesh::node_update().
actions_before_newton_convergence_check() [3/4]
template<class ELEMENT > void CapProblem< ELEMENT >::actions_before_newton_convergence_check () inline virtual
Update the spine mesh after every Newton step.
Reimplemented from oomph::Problem.
 {Bulk_mesh_pt->node_update();}
actions_before_newton_convergence_check() [4/4]
template<class ELEMENT > void CapProblem< ELEMENT >::actions_before_newton_convergence_check () inline virtual
Update the spine mesh after every Newton step.
Reimplemented from oomph::Problem.
 {Bulk_mesh_pt->node_update();}
References oomph::SpineMesh::node_update().
create_volume_constraint_elements() [1/4]
template<class ELEMENT > void CapProblem< ELEMENT >::create_volume_constraint_elements
Create the volume constraint elements.
 {
  //The single volume constraint element
  Volume_constraint_mesh_pt = new Mesh;
  VolumeConstraintElement* vol_constraint_element =
   new VolumeConstraintElement(&Volume,Traded_pressure_data_pt,0);
  Volume_constraint_mesh_pt->add_element_pt(vol_constraint_element);
  //Loop over all boundaries (or just 1 and 2 why?)
  for(unsigned b=0;b<4;b++)
   {
    // How many bulk fluid elements are adjacent to boundary b?
    unsigned n_element = Bulk_mesh_pt->nboundary_element(b);
    // Loop over the bulk fluid elements adjacent to boundary b?
    for(unsigned e=0;e<n_element;e++)
     {
      // Get pointer to the bulk fluid element that is
      // adjacent to boundary b
      ELEMENT* bulk_elem_pt = dynamic_cast<ELEMENT*>(
       Bulk_mesh_pt->boundary_element_pt(b,e));
      //Find the index of the face of element e along boundary b
      int face_index = Bulk_mesh_pt->face_index_at_boundary(b,e);
      // Create new element
      SpineAxisymmetricVolumeConstraintBoundingElement<ELEMENT>* el_pt =
       new SpineAxisymmetricVolumeConstraintBoundingElement<ELEMENT>(
        bulk_elem_pt,face_index);
      //Set the "master" volume control element
      el_pt->set_volume_constraint_element(vol_constraint_element);
      // Add it to the mesh
      Volume_constraint_mesh_pt->add_element_pt(el_pt);
     }
   }
 }
References b, e(), oomph::VolumeConstraintBoundingElement::set_volume_constraint_element(), and Global_Physical_Variables::Volume.
Referenced by CapProblem< ELEMENT >::CapProblem().
create_volume_constraint_elements() [2/4]
template<class ELEMENT > void CapProblem< ELEMENT >::create_volume_constraint_elements ()
Create the volume constraint elements.
create_volume_constraint_elements() [3/4]
template<class ELEMENT > void CapProblem< ELEMENT >::create_volume_constraint_elements ()
Create the volume constraint elements.
create_volume_constraint_elements() [4/4]
template<class ELEMENT > void CapProblem< ELEMENT >::create_volume_constraint_elements ()
Create the volume constraint elements.
doc_solution() [1/3]
template<class ELEMENT > void CapProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
 {
  ofstream some_file;
  char filename[100];
  // Number of plot points
  unsigned npts=5;
  //Output domain
  sprintf(filename,"%s/soln%i.dat",doc_info.directory().c_str(),
          doc_info.number());
  some_file.open(filename);
  Bulk_mesh_pt->output(some_file,npts);
  Surface_mesh_pt->output(some_file,npts);
  some_file.close();
  //Output domain in paraview format
  sprintf(filename,"%s/soln%i.vtu",doc_info.directory().c_str(),
          doc_info.number());
  some_file.open(filename);
  Bulk_mesh_pt->output_paraview(some_file,npts);
  some_file.close();
  // Number of spines
  unsigned nspine=Bulk_mesh_pt->nspine();
  // Doc
  Trace_file << Angle*180.0/MathematicalConstants::Pi;
  Trace_file << " "  << Bulk_mesh_pt->spine_pt(0)->height();
  Trace_file << " "  << Bulk_mesh_pt->spine_pt(nspine-1)->height();
  Trace_file << " "
             << dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(0))
   ->p_axi_nst(0) - External_pressure_data_pt->value(0);
  Trace_file << " " << -4.0*cos(Angle)/Ca;
  Trace_file << std::endl;
 }
References Global_Physical_Variables::Angle, Global_Physical_Variables::Ca, cos(), oomph::DocInfo::directory(), MergeRestartFiles::filename, oomph::DocInfo::number(), BiharmonicTestFunctions2::Pi, and oomph::Problem_Parameter::Trace_file.
doc_solution() [2/3]
template<class ELEMENT > void CapProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
doc_solution() [3/3]
template<class ELEMENT > void CapProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
finish_problem_setup()
template<class ELEMENT > void CapProblem< ELEMENT >::finish_problem_setup ()
Finish full specification of the elements.
parameter_study() [1/3]
template<class ELEMENT > void CapProblem< ELEMENT >::parameter_study
Peform a parameter study: Solve problem for a range of contact angles.
Perform a parameter study.
 {
  // Create DocInfo object (allows checking if output directory exists)
  DocInfo doc_info;
  doc_info.set_directory("RESLT");
  doc_info.number()=0;
  // Open trace file
  char filename[100];
  sprintf(filename,"%s/trace.dat",doc_info.directory().c_str());
  Trace_file.open(filename);
  Trace_file << "VARIABLES=\"<greek>a</greek><sub>prescribed</sub>\",";
  Trace_file << "\"h<sub>left</sub>\",\"h<sub>right</sub>\",";
  Trace_file << "\"<greek>a</greek><sub>left</sub>\",";
  Trace_file << "\"<greek>a</greek><sub>right</sub>\",";
  Trace_file << "\"p<sub>upper</sub>\",";
  Trace_file << "\"p<sub>lower</sub>\",";
  Trace_file << "\"p<sub>exact</sub>\"";
  Trace_file << std::endl;
  // Doc initial state
  doc_solution(doc_info);
  // Bump up counter
  doc_info.number()++;
  //Gradually increase the contact angle
  for(unsigned i=0;i<6;i++)
   {
    //Solve the problem
    steady_newton_solve();
    //Output result
    doc_solution(doc_info);
    // Bump up counter
    doc_info.number()++;
    //Decrease the contact angle
    Angle -= 5.0*MathematicalConstants::Pi/180.0;
   }
 }
References Global_Physical_Variables::Angle, oomph::DocInfo::directory(), MergeRestartFiles::filename, i, oomph::DocInfo::number(), BiharmonicTestFunctions2::Pi, oomph::DocInfo::set_directory(), and oomph::Problem_Parameter::Trace_file.
parameter_study() [2/3]
template<class ELEMENT > void CapProblem< ELEMENT >::parameter_study (const string & dir_name)
Perform a parameter study: Solve problem for a range of contact angles Pass name of output directory as a string
Perform a parameter study. Pass name of output directory as a string
 {
  // Create DocInfo object (allows checking if output directory exists)
  DocInfo doc_info;
  doc_info.set_directory(dir_name);
  doc_info.number()=0;
  // Open trace file
  char filename[100];
  sprintf(filename,"%s/trace.dat",doc_info.directory().c_str());
  Trace_file.open(filename);
  Trace_file << "VARIABLES=\"<greek>a</greek><sub>prescribed</sub>\",";
  Trace_file << "\"h<sub>left</sub>\",\"h<sub>right</sub>\",";
  Trace_file << "\"p<sub>fluid</sub>-p<sub>ext</sub>\",";
  Trace_file << "\"<greek>D</greek>p<sub>exact</sub>\"";
  Trace_file << std::endl;
  //Gradually increase the contact angle
  for(unsigned i=0;i<6;i++)
   {
    //Solve the problem
    steady_newton_solve();
    //Output result
    doc_solution(doc_info);
    // Bump up counter
    doc_info.number()++;
    //Decrease the contact angle
    Angle -= 5.0*MathematicalConstants::Pi/180.0;
   }
 }
References Global_Physical_Variables::Angle, oomph::DocInfo::directory(), MergeRestartFiles::filename, i, oomph::DocInfo::number(), BiharmonicTestFunctions2::Pi, oomph::DocInfo::set_directory(), and oomph::Problem_Parameter::Trace_file.
parameter_study() [3/3]
template<class ELEMENT > void CapProblem< ELEMENT >::parameter_study (const string & dir_name)
Perform a parameter study: Solve problem for a range of contact angles Pass name of output directory as a string
set_boundary_conditions()
template<class ELEMENT > void CapProblem< ELEMENT >::set_boundary_conditions
Set boundary conditions on the wall.
 {
  //NOTE: The default value of all parameters is zero, so we don't need
  //to set anything here
 }
solve_system()
template<class ELEMENT > void CapProblem< ELEMENT >::solve_system
Solve the problem.
 {
  //Define a string that we can set to be the name of the output file
  char filename[100];
  //Set the boundary conditions (only need to do this once)
  //If the boundary conditions depend up on time, or Re, we need to
  //reset them every time something changes. This is most easily
  //achieved using the actions_before_newton_solve() {} function.
  set_boundary_conditions();
  //Solve the problem (function defined in Problem class)
  //The default tolerance is that the maximum residual must be less that 1.0e-8
  steady_newton_solve();
  //Output first solution
  ofstream file("step0_spine.dat");
  Bulk_mesh_pt->output(file,5);
  Surface_mesh_pt->output(file,5);
  file.close();
  //Gradually increase the contact angle
  for(unsigned i=1;i<6;i++)
   {
    //Decrease the contact angle
    Angle -= 0.1;
    //Solve the problem
    steady_newton_solve();
    //Create the filename, including the array index
    sprintf(filename,"step%i_spine.dat",i);
    //Actually, write the data
    file.open(filename);
    Bulk_mesh_pt->output(file,5);
    Surface_mesh_pt->output(file,5);
    file.close();
   }
 }
References Global_Physical_Variables::Angle, MergeRestartFiles::filename, and i.
Member Data Documentation
Angle
template<class ELEMENT > double CapProblem< ELEMENT >::Angle private
The contact angle.
Referenced by CapProblem< ELEMENT >::CapProblem().
Bulk_mesh_pt [1/2]
template<class ELEMENT > TwoLayerSpineMesh< SpineElement< ELEMENT > > * CapProblem< ELEMENT >::Bulk_mesh_pt private
The bulk mesh of fluid elements.
Pointer to the mesh.
Referenced by CapProblem< ELEMENT >::CapProblem().
Bulk_mesh_pt [2/2]
template<class ELEMENT > TwoLayerSpineMesh<SpineElement<ELEMENT> >* CapProblem< ELEMENT >::Bulk_mesh_pt
Pointer to the mesh.
Ca
template<class ELEMENT > double CapProblem< ELEMENT >::Ca private
The Capillary number.
Referenced by CapProblem< ELEMENT >::CapProblem().
External_pressure_data_pt
template<class ELEMENT > Data * CapProblem< ELEMENT >::External_pressure_data_pt private
Data object whose single value stores the external pressure.
Referenced by CapProblem< ELEMENT >::CapProblem().
Pext
template<class ELEMENT > double CapProblem< ELEMENT >::Pext private
The external pressure.
Referenced by CapProblem< ELEMENT >::CapProblem().
Point_mesh_pt
template<class ELEMENT > Mesh * CapProblem< ELEMENT >::Point_mesh_pt private
The mesh for the element at the contact point.
Pointer to the point mesh.
Referenced by CapProblem< ELEMENT >::CapProblem().
Surface_mesh_pt
template<class ELEMENT > Mesh * CapProblem< ELEMENT >::Surface_mesh_pt private
The mesh for the interface elements.
Pointer to the surface mesh.
Referenced by CapProblem< ELEMENT >::CapProblem().
Trace_file
template<class ELEMENT > ofstream CapProblem< ELEMENT >::Trace_file private
Trace file.
Traded_pressure_data_pt
template<class ELEMENT > Data * CapProblem< ELEMENT >::Traded_pressure_data_pt private
Data that is traded for the volume constraint.
Referenced by CapProblem< ELEMENT >::CapProblem().
Volume
template<class ELEMENT > double CapProblem< ELEMENT >::Volume private
The volume of the fluid.
Volume_constraint_mesh_pt
template<class ELEMENT > Mesh * CapProblem< ELEMENT >::Volume_constraint_mesh_pt private
The volume constraint mesh.
Pointer to the volume constraint mesh.
Referenced by CapProblem< ELEMENT >::CapProblem().
The documentation for this class was generated from the following files:
axi_static_cap.cc
two_fluid_spherical_cap.cc
static_single_layer.cc
static_two_layer.cc