MercuryDPM: Eigen::internal::check_transpose_aliasing_run_time_selector< Scalar, DestIsTransposed, CwiseBinaryOp< BinOp, DerivedA, DerivedB > > Struct Template Reference
Eigen::internal::check_transpose_aliasing_run_time_selector< Scalar, DestIsTransposed, CwiseBinaryOp< BinOp, DerivedA, DerivedB > > Struct Template Reference
#include <Transpose.h>
Static Public Member Functions
static EIGEN_DEVICE_FUNC bool run (const Scalar *dest, const CwiseBinaryOp< BinOp, DerivedA, DerivedB > &src)
Member Function Documentation
run()
template<typename Scalar , bool DestIsTransposed, typename BinOp , typename DerivedA , typename DerivedB > static EIGEN_DEVICE_FUNC bool Eigen::internal::check_transpose_aliasing_run_time_selector< Scalar, DestIsTransposed, CwiseBinaryOp< BinOp, DerivedA, DerivedB > >::run (const Scalar * dest, const CwiseBinaryOp< BinOp, DerivedA, DerivedB > & src) inline static
{
     return ((blas_traits<DerivedA>::IsTransposed != DestIsTransposed) &&
             (dest != 0 && dest == (const Scalar*)extract_data(src.lhs()))) ||
            ((blas_traits<DerivedB>::IsTransposed != DestIsTransposed) &&
             (dest != 0 && dest == (const Scalar*)extract_data(src.rhs())));
   }
References Eigen::internal::extract_data(), Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::lhs(), and Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::rhs().
The documentation for this struct was generated from the following file:
Transpose.h