MercuryDPM: rapidjson::PrettyWriter< Stream, Encoding, Allocator > Class Template Reference
rapidjson::PrettyWriter< Stream, Encoding, Allocator > Class Template Reference
Writer with indentation and spacing.
#include <prettywriter.h>
Public Types
typedef Writer< Stream, Encoding, Allocator > Base
typedef Base::Ch Ch
Public Types inherited from rapidjson::Writer< Stream, UTF8<>, MemoryPoolAllocator<> >
typedef Encoding::Ch Ch
Public Member Functions
PrettyWriter (Stream &stream, int precision=20, Allocator *allocator=0, size_t levelDepth=Base::kDefaultLevelDepth)
Constructor.
PrettyWriter & SetIndent (Ch indentChar, unsigned indentCharCount)
Set custom indentation.
PrettyWriter & Null_ ()
PrettyWriter & Bool_ (bool b)
PrettyWriter & Int (int i)
PrettyWriter & Uint (unsigned u)
PrettyWriter & Int64 (int64_t i64)
PrettyWriter & Uint64 (uint64_t u64)
PrettyWriter & Double (double d)
PrettyWriter & String (const Ch *str, SizeType length, bool copy=false)
PrettyWriter & StartObject ()
PrettyWriter & EndObject (SizeType memberCount=0)
PrettyWriter & StartArray ()
PrettyWriter & EndArray (SizeType memberCount=0)
PrettyWriter & String (const Ch *str)
Simpler but slower overload.
Public Member Functions inherited from rapidjson::Writer< Stream, UTF8<>, MemoryPoolAllocator<> >
Writer (Stream &stream, int precision=20, MemoryPoolAllocator<> *allocator=0, size_t levelDepth=kDefaultLevelDepth)
Writer & Null_ ()
Writer & Bool_ (bool b)
Writer & Int (int i)
Writer & Uint (unsigned u)
Writer & Int64 (int64_t i64)
Writer & Uint64 (uint64_t u64)
Writer & Double (double d)
Writer & LongDouble (long double d)
Writer & LongLong (long long d)
Writer & ULongLong (unsigned long long d)
Writer & String (const Ch *str, SizeType length, bool copy=false)
Writer & String (const Ch *str)
Simpler but slower overload.
Writer & StartObject ()
Writer & EndObject (SizeType memberCount=0)
Writer & StartArray ()
Writer & EndArray (SizeType elementCount=0)
Protected Member Functions
void PrettyPrefix (Type type)
void WriteIndent ()
Protected Member Functions inherited from rapidjson::Writer< Stream, UTF8<>, MemoryPoolAllocator<> >
void WriteNull_ ()
void WriteBool_ (bool b)
void WriteInt (int i)
void WriteUint (unsigned u)
void WriteInt64 (int64_t i64)
void WriteUint64 (uint64_t u64)
std::enable_if< to_int(std::numeric_limits< Ch >::max())< to_int(256), bool >::type characterOk(Ch) { return true;} template< class Ch > typename std::enable_if< to_int(std::numeric_limits< Ch >::max()) >=to_int(256), bool >::type characterOk (Ch c)
void WriteDouble (double d)
void WriteLongDouble (long double d)
void WriteLongLong (long long d)
void WriteULongLong (unsigned long long d)
void WriteString (const Ch *str, SizeType length)
void WriteStartObject ()
void WriteEndObject ()
void WriteStartArray ()
void WriteEndArray ()
void Prefix (Type type)
Protected Attributes
Ch indentChar_
unsigned indentCharCount_
Protected Attributes inherited from rapidjson::Writer< Stream, UTF8<>, MemoryPoolAllocator<> >
char double_format [32]
char long_double_format [32]
Stream & stream_
internal::Stack< MemoryPoolAllocator<> > level_stack_
Additional Inherited Members
Static Protected Member Functions inherited from rapidjson::Writer< Stream, UTF8<>, MemoryPoolAllocator<> >
static constexpr int to_int (T t)
Static Protected Attributes inherited from rapidjson::Writer< Stream, UTF8<>, MemoryPoolAllocator<> >
static const size_t kDefaultLevelDepth
Detailed Description
template<typename Stream, typename Encoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>>
class rapidjson::PrettyWriter< Stream, Encoding, Allocator >
Writer with indentation and spacing.
Template Parameters
Stream Type of ouptut stream.
Encoding Encoding of both source strings and output.
Allocator Type of allocator for allocating memory of stack.
Member Typedef Documentation
Base
template<typename Stream , typename Encoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> typedef Writer<Stream, Encoding, Allocator> rapidjson::PrettyWriter< Stream, Encoding, Allocator >::Base
Ch
template<typename Stream , typename Encoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> typedef Base::Ch rapidjson::PrettyWriter< Stream, Encoding, Allocator >::Ch
Constructor & Destructor Documentation
PrettyWriter()
template<typename Stream , typename Encoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> rapidjson::PrettyWriter< Stream, Encoding, Allocator >::PrettyWriter (Stream & stream, int precision = 20, Allocator * allocator = 0, size_t levelDepth = Base::kDefaultLevelDepth) inline
Constructor.
Parameters
stream Output stream.
allocator User supplied allocator. If it is null, it will create a private one.
levelDepth Initial capacity of
                                                                                                                            :
         Base(stream, precision, allocator, levelDepth), indentChar_(' '), indentCharCount_(4) {}
Member Function Documentation
Bool_()
template<typename Stream , typename Encoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> PrettyWriter& rapidjson::PrettyWriter< Stream, Encoding, Allocator >::Bool_ (bool b) inline
 { PrettyPrefix(b ? kTrueType : kFalseType); Base::WriteBool_(b); return *this; }
References b, rapidjson::kFalseType, rapidjson::kTrueType, rapidjson::PrettyWriter< Stream, Encoding, Allocator >::PrettyPrefix(), and rapidjson::Writer< Stream, Encoding, Allocator >::WriteBool_().
Double()
template<typename Stream , typename Encoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> PrettyWriter& rapidjson::PrettyWriter< Stream, Encoding, Allocator >::Double (double d) inline
 { PrettyPrefix(kNumberType); Base::WriteDouble(d);      return *this; }
References rapidjson::kNumberType, rapidjson::PrettyWriter< Stream, Encoding, Allocator >::PrettyPrefix(), and rapidjson::Writer< Stream, Encoding, Allocator >::WriteDouble().
EndArray()
template<typename Stream , typename Encoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> PrettyWriter& rapidjson::PrettyWriter< Stream, Encoding, Allocator >::EndArray (SizeType memberCount = 0) inline
{
         (void)memberCount;
         RAPIDJSON_ASSERT(Base::level_stack_.GetSize() >= sizeof(typename Base::Level));
         RAPIDJSON_ASSERT(Base::level_stack_.template Top<typename Base::Level>()->inArray);
         bool empty = Base::level_stack_.template Pop<typename Base::Level>(1)->valueCount == 0;
         if (!empty) {
             Base::stream_.Put('\n');
             WriteIndent();
         }
         Base::WriteEndArray();
         return *this;
     }
References rapidjson::Writer< Stream, Encoding, Allocator >::level_stack_, RAPIDJSON_ASSERT, rapidjson::Writer< Stream, Encoding, Allocator >::stream_, rapidjson::Writer< Stream, Encoding, Allocator >::WriteEndArray(), and rapidjson::PrettyWriter< Stream, Encoding, Allocator >::WriteIndent().
EndObject()
template<typename Stream , typename Encoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> PrettyWriter& rapidjson::PrettyWriter< Stream, Encoding, Allocator >::EndObject (SizeType memberCount = 0) inline
{
         (void)memberCount;
         RAPIDJSON_ASSERT(Base::level_stack_.GetSize() >= sizeof(typename Base::Level));
         RAPIDJSON_ASSERT(!Base::level_stack_.template Top<typename Base::Level>()->inArray);
         bool empty = Base::level_stack_.template Pop<typename Base::Level>(1)->valueCount == 0;
         if (!empty) {
             Base::stream_.Put('\n');
             WriteIndent();
         }
         Base::WriteEndObject();
         return *this;
     }
References rapidjson::Writer< Stream, Encoding, Allocator >::level_stack_, RAPIDJSON_ASSERT, rapidjson::Writer< Stream, Encoding, Allocator >::stream_, rapidjson::Writer< Stream, Encoding, Allocator >::WriteEndObject(), and rapidjson::PrettyWriter< Stream, Encoding, Allocator >::WriteIndent().
Int()
template<typename Stream , typename Encoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> PrettyWriter& rapidjson::PrettyWriter< Stream, Encoding, Allocator >::Int (int i) inline
 { PrettyPrefix(kNumberType); Base::WriteInt(i);         return *this; }
References i, rapidjson::kNumberType, rapidjson::PrettyWriter< Stream, Encoding, Allocator >::PrettyPrefix(), and rapidjson::Writer< Stream, Encoding, Allocator >::WriteInt().
Int64()
template<typename Stream , typename Encoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> PrettyWriter& rapidjson::PrettyWriter< Stream, Encoding, Allocator >::Int64 (int64_t i64) inline
 { PrettyPrefix(kNumberType); Base::WriteInt64(i64);     return *this; }
References rapidjson::kNumberType, rapidjson::PrettyWriter< Stream, Encoding, Allocator >::PrettyPrefix(), and rapidjson::Writer< Stream, Encoding, Allocator >::WriteInt64().
Null_()
template<typename Stream , typename Encoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> PrettyWriter& rapidjson::PrettyWriter< Stream, Encoding, Allocator >::Null_ () inline
 { PrettyPrefix(kNull_Type);   Base::WriteNull_();           return *this; }
References rapidjson::kNull_Type, rapidjson::PrettyWriter< Stream, Encoding, Allocator >::PrettyPrefix(), and rapidjson::Writer< Stream, Encoding, Allocator >::WriteNull_().
PrettyPrefix()
template<typename Stream , typename Encoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> void rapidjson::PrettyWriter< Stream, Encoding, Allocator >::PrettyPrefix (Type type) inline protected
{
         (void)type;
         if (Base::level_stack_.GetSize() != 0) { // this value is not at root
             typename Base::Level* level = Base::level_stack_.template Top<typename Base::Level>();
             if (level->inArray) {
                 if (level->valueCount > 0) {
                     Base::stream_.Put(','); // add comma if it is not the first element in array
                     Base::stream_.Put('\n');
                 }
                 else
                     Base::stream_.Put('\n');
                 WriteIndent();
             }
             else {  // in object
                 if (level->valueCount > 0) {
                     if (level->valueCount % 2 == 0) {
                         Base::stream_.Put(',');
                         Base::stream_.Put('\n');
                     }
                     else {
                         Base::stream_.Put(':');
                         Base::stream_.Put(' ');
                     }
                 }
                 else
                     Base::stream_.Put('\n');
                 if (level->valueCount % 2 == 0)
                     WriteIndent();
             }
             if (!level->inArray && level->valueCount % 2 == 0)
                 RAPIDJSON_ASSERT(type == kStringType);  // if it's in object, then even number should be a name
             level->valueCount++;
         }
         else
             RAPIDJSON_ASSERT(type == kObjectType || type == kArrayType);
     }
References rapidjson::Writer< Stream, Encoding, Allocator >::Level::inArray, rapidjson::kArrayType, rapidjson::kObjectType, rapidjson::kStringType, rapidjson::Writer< Stream, Encoding, Allocator >::level_stack_, RAPIDJSON_ASSERT, rapidjson::Writer< Stream, Encoding, Allocator >::stream_, compute_granudrum_aor::type, rapidjson::Writer< Stream, Encoding, Allocator >::Level::valueCount, and rapidjson::PrettyWriter< Stream, Encoding, Allocator >::WriteIndent().
Referenced by rapidjson::PrettyWriter< Stream, Encoding, Allocator >::Bool_(), rapidjson::PrettyWriter< Stream, Encoding, Allocator >::Double(), rapidjson::PrettyWriter< Stream, Encoding, Allocator >::Int(), rapidjson::PrettyWriter< Stream, Encoding, Allocator >::Int64(), rapidjson::PrettyWriter< Stream, Encoding, Allocator >::Null_(), rapidjson::PrettyWriter< Stream, Encoding, Allocator >::StartArray(), rapidjson::PrettyWriter< Stream, Encoding, Allocator >::StartObject(), rapidjson::PrettyWriter< Stream, Encoding, Allocator >::String(), rapidjson::PrettyWriter< Stream, Encoding, Allocator >::Uint(), and rapidjson::PrettyWriter< Stream, Encoding, Allocator >::Uint64().
SetIndent()
template<typename Stream , typename Encoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> PrettyWriter& rapidjson::PrettyWriter< Stream, Encoding, Allocator >::SetIndent (Ch indentChar, unsigned indentCharCount) inline
Set custom indentation.
Parameters
indentChar Character for indentation. Must be whitespace character (' ', '\t', '
', '\r').
indentCharCount Number of indent characters for each indentation level.
Note
The default indentation is 4 spaces.
{
         RAPIDJSON_ASSERT(indentChar == ' ' || indentChar == '\t' || indentChar == '\n' || indentChar == '\r');
         indentChar_ = indentChar;
         indentCharCount_ = indentCharCount;
         return *this;
     }
References rapidjson::PrettyWriter< Stream, Encoding, Allocator >::indentChar_, rapidjson::PrettyWriter< Stream, Encoding, Allocator >::indentCharCount_, and RAPIDJSON_ASSERT.
StartArray()
template<typename Stream , typename Encoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> PrettyWriter& rapidjson::PrettyWriter< Stream, Encoding, Allocator >::StartArray () inline
{
         PrettyPrefix(kArrayType);
         new (Base::level_stack_.template Push<typename Base::Level>()) typename Base::Level(true);
         Base::WriteStartArray();
         return *this;
     }
References rapidjson::kArrayType, rapidjson::Writer< Stream, Encoding, Allocator >::level_stack_, rapidjson::PrettyWriter< Stream, Encoding, Allocator >::PrettyPrefix(), and rapidjson::Writer< Stream, Encoding, Allocator >::WriteStartArray().
StartObject()
template<typename Stream , typename Encoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> PrettyWriter& rapidjson::PrettyWriter< Stream, Encoding, Allocator >::StartObject () inline
{
         PrettyPrefix(kObjectType);
         new (Base::level_stack_.template Push<typename Base::Level>()) typename Base::Level(false);
         Base::WriteStartObject();
         return *this;
     }
References rapidjson::kObjectType, rapidjson::Writer< Stream, Encoding, Allocator >::level_stack_, rapidjson::PrettyWriter< Stream, Encoding, Allocator >::PrettyPrefix(), and rapidjson::Writer< Stream, Encoding, Allocator >::WriteStartObject().
String() [1/2]
template<typename Stream , typename Encoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> PrettyWriter& rapidjson::PrettyWriter< Stream, Encoding, Allocator >::String (const Ch * str) inline
Simpler but slower overload.
 { return String(str, internal::StrLen(str)); }
References compute_granudrum_aor::str, rapidjson::PrettyWriter< Stream, Encoding, Allocator >::String(), and rapidjson::internal::StrLen().
Referenced by rapidjson::PrettyWriter< Stream, Encoding, Allocator >::String().
String() [2/2]
template<typename Stream , typename Encoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> PrettyWriter& rapidjson::PrettyWriter< Stream, Encoding, Allocator >::String (const Ch * str, SizeType length, bool copy = false) inline
{
         (void)copy;
         PrettyPrefix(kStringType);
         Base::WriteString(str, length);
         return *this;
     }
References copy(), rapidjson::kStringType, rapidjson::PrettyWriter< Stream, Encoding, Allocator >::PrettyPrefix(), compute_granudrum_aor::str, and rapidjson::Writer< Stream, Encoding, Allocator >::WriteString().
Uint()
template<typename Stream , typename Encoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> PrettyWriter& rapidjson::PrettyWriter< Stream, Encoding, Allocator >::Uint (unsigned u) inline
 { PrettyPrefix(kNumberType); Base::WriteUint(u);        return *this; }
References rapidjson::kNumberType, rapidjson::PrettyWriter< Stream, Encoding, Allocator >::PrettyPrefix(), and rapidjson::Writer< Stream, Encoding, Allocator >::WriteUint().
Uint64()
template<typename Stream , typename Encoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> PrettyWriter& rapidjson::PrettyWriter< Stream, Encoding, Allocator >::Uint64 (uint64_t u64) inline
 { PrettyPrefix(kNumberType); Base::WriteUint64(u64);    return *this; }
References rapidjson::kNumberType, rapidjson::PrettyWriter< Stream, Encoding, Allocator >::PrettyPrefix(), and rapidjson::Writer< Stream, Encoding, Allocator >::WriteUint64().
WriteIndent()
template<typename Stream , typename Encoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> void rapidjson::PrettyWriter< Stream, Encoding, Allocator >::WriteIndent () inline protected
{
         size_t count = (Base::level_stack_.GetSize() / sizeof(typename Base::Level)) * indentCharCount_;
         PutN(Base::stream_, indentChar_, count);
     }
References rapidjson::PrettyWriter< Stream, Encoding, Allocator >::indentChar_, rapidjson::PrettyWriter< Stream, Encoding, Allocator >::indentCharCount_, rapidjson::Writer< Stream, Encoding, Allocator >::level_stack_, rapidjson::PutN(), and rapidjson::Writer< Stream, Encoding, Allocator >::stream_.
Referenced by rapidjson::PrettyWriter< Stream, Encoding, Allocator >::EndArray(), rapidjson::PrettyWriter< Stream, Encoding, Allocator >::EndObject(), and rapidjson::PrettyWriter< Stream, Encoding, Allocator >::PrettyPrefix().
Member Data Documentation
indentChar_
template<typename Stream , typename Encoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> Ch rapidjson::PrettyWriter< Stream, Encoding, Allocator >::indentChar_ protected
Referenced by rapidjson::PrettyWriter< Stream, Encoding, Allocator >::SetIndent(), and rapidjson::PrettyWriter< Stream, Encoding, Allocator >::WriteIndent().
indentCharCount_
template<typename Stream , typename Encoding = UTF8<>, typename Allocator = MemoryPoolAllocator<>> unsigned rapidjson::PrettyWriter< Stream, Encoding, Allocator >::indentCharCount_ protected
Referenced by rapidjson::PrettyWriter< Stream, Encoding, Allocator >::SetIndent(), and rapidjson::PrettyWriter< Stream, Encoding, Allocator >::WriteIndent().
The documentation for this class was generated from the following file:
prettywriter.h