MercuryDPM: misra1a_functor Struct Reference
misra1a_functor Struct Reference
Public Member Functions
misra1a_functor (void)
int operator() (const VectorXd &b, VectorXd &fvec)
int df (const VectorXd &b, MatrixXd &fjac)
misra1a_functor (void)
int operator() (const VectorXd &b, VectorXd &fvec)
int df (const VectorXd &b, MatrixXd &fjac)
Public Member Functions inherited from Eigen::DenseFunctor< double >
DenseFunctor ()
DenseFunctor (int inputs, int values)
int inputs () const
int values () const
Public Member Functions inherited from Functor< double >
Functor ()
Functor (int inputs, int values)
Functor ()
Functor (int inputs_, int values_)
int inputs () const
int inputs () const
int values () const
int values () const
Static Public Attributes
static const double m_x [14]
static const double m_y [14]
Additional Inherited Members
Public Types inherited from Eigen::DenseFunctor< double >
enum
typedef double Scalar
typedef Matrix< Scalar, InputsAtCompileTime, 1 > InputType
typedef Matrix< Scalar, ValuesAtCompileTime, 1 > ValueType
typedef Matrix< Scalar, ValuesAtCompileTime, InputsAtCompileTime > JacobianType
typedef ColPivHouseholderQR< JacobianType > QRSolver
Public Types inherited from Functor< double >
enum
enum
typedef double Scalar
typedef double Scalar
typedef Matrix< Scalar, InputsAtCompileTime, 1 > InputType
typedef Matrix< Scalar, InputsAtCompileTime, 1 > InputType
typedef Matrix< Scalar, ValuesAtCompileTime, 1 > ValueType
typedef Matrix< Scalar, ValuesAtCompileTime, 1 > ValueType
typedef Matrix< Scalar, ValuesAtCompileTime, InputsAtCompileTime > JacobianType
typedef Matrix< Scalar, ValuesAtCompileTime, InputsAtCompileTime > JacobianType
Public Attributes inherited from Eigen::DenseFunctor< double >
const int m_inputs
const int m_values
Public Attributes inherited from Functor< double >
const int m_inputs
int m_inputs
const int m_values
int m_values
Constructor & Destructor Documentation
misra1a_functor() [1/2]
misra1a_functor::misra1a_functor (void) inline
 : DenseFunctor<double>(2, 14) {}
misra1a_functor() [2/2]
misra1a_functor::misra1a_functor (void) inline
 : Functor<double>(2, 14) {}
Member Function Documentation
df() [1/2]
int misra1a_functor::df (const VectorXd & b, MatrixXd & fjac) inline
{
     assert(b.size() == 2);
     assert(fjac.rows() == 14);
     assert(fjac.cols() == 2);
     for (int i = 0; i < 14; i++) {
       fjac(i, 0) = (1. - exp(-b[1] * m_x[i]));
       fjac(i, 1) = (b[0] * m_x[i] * exp(-b[1] * m_x[i]));
     }
     return 0;
   }
References assert, b, Eigen::bfloat16_impl::exp(), i, and m_x.
df() [2/2]
int misra1a_functor::df (const VectorXd & b, MatrixXd & fjac) inline
{
     assert(b.size() == 2);
     assert(fjac.rows() == 14);
     assert(fjac.cols() == 2);
     for (int i = 0; i < 14; i++) {
       fjac(i, 0) = (1. - exp(-b[1] * m_x[i]));
       fjac(i, 1) = (b[0] * m_x[i] * exp(-b[1] * m_x[i]));
     }
     return 0;
   }
References assert, b, Eigen::bfloat16_impl::exp(), i, and m_x.
operator()() [1/2]
int misra1a_functor::operator() (const VectorXd & b, VectorXd & fvec) inline
{
     assert(b.size() == 2);
     assert(fvec.size() == 14);
     for (int i = 0; i < 14; i++) {
       fvec[i] = b[0] * (1. - exp(-b[1] * m_x[i])) - m_y[i];
     }
     return 0;
   }
References assert, b, Eigen::bfloat16_impl::exp(), i, m_x, and m_y.
operator()() [2/2]
int misra1a_functor::operator() (const VectorXd & b, VectorXd & fvec) inline
{
     assert(b.size() == 2);
     assert(fvec.size() == 14);
     for (int i = 0; i < 14; i++) {
       fvec[i] = b[0] * (1. - exp(-b[1] * m_x[i])) - m_y[i];
     }
     return 0;
   }
References assert, b, Eigen::bfloat16_impl::exp(), i, m_x, and m_y.
Member Data Documentation
m_x
const double misra1a_functor::m_x static
Initial value:
= {77.6E0,  114.9E0, 141.1E0, 190.8E0, 239.9E0, 289.0E0, 332.8E0,
                                         378.4E0, 434.8E0, 477.3E0, 536.8E0, 593.1E0, 689.1E0, 760.0E0}
Referenced by df(), and operator()().
m_y
const double misra1a_functor::m_y static
Initial value:
= {10.07E0, 14.73E0, 17.94E0, 23.93E0, 29.61E0, 35.18E0, 40.02E0,
                                         44.82E0, 50.76E0, 55.05E0, 61.01E0, 66.40E0, 75.47E0, 81.78E0}
Referenced by operator()().
The documentation for this struct was generated from the following files:
levenberg_marquardt.cpp
NonLinearOptimization.cpp