MercuryDPM: oomph::RefineablePolarNavierStokesEquations Class Reference
oomph::RefineablePolarNavierStokesEquations Class Reference abstract
#include <refineable_polar_navier_stokes_elements.h>
Public Member Functions
RefineablePolarNavierStokesEquations ()
Constructor.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
void further_build ()
Further build, pass the pointers down to the sons.
Public Member Functions inherited from oomph::PolarNavierStokesEquations
PolarNavierStokesEquations ()
Constructor: NULL the body force and source function.
const double & re () const
Reynolds number.
const double & alpha () const
Alpha.
const double & re_st () const
Product of Reynolds and Strouhal number (=Womersley number)
double *& re_pt ()
Pointer to Reynolds number.
double *& alpha_pt ()
Pointer to Alpha.
double *& re_st_pt ()
Pointer to product of Reynolds and Strouhal number (=Womersley number)
const double & viscosity_ratio () const
double *& viscosity_ratio_pt ()
Pointer to Viscosity Ratio.
const double & density_ratio () const
double *& density_ratio_pt ()
Pointer to Density ratio.
const double & re_invfr () const
Global inverse Froude number.
double *& re_invfr_pt ()
Pointer to global inverse Froude number.
const Vector< double > & g () const
Vector of gravitational components.
Vector< double > *& g_pt ()
Pointer to Vector of gravitational components.
NavierStokesBodyForceFctPt & body_force_fct_pt ()
Access function for the body-force pointer.
NavierStokesBodyForceFctPt body_force_fct_pt () const
Access function for the body-force pointer. Const version.
NavierStokesSourceFctPt & source_fct_pt ()
Access function for the source-function pointer.
NavierStokesSourceFctPt source_fct_pt () const
Access function for the source-function pointer. Const version.
virtual unsigned npres_pnst () const =0
Function to return number of pressure degrees of freedom.
virtual double u_pnst (const unsigned &n, const unsigned &i) const =0
virtual double u_pnst (const unsigned &t, const unsigned &n, const unsigned &i) const =0
virtual unsigned u_index_pnst (const unsigned &i) const
double du_dt_pnst (const unsigned &n, const unsigned &i) const
virtual double p_pnst (const unsigned &n_p) const =0
virtual void fix_pressure (const unsigned &p_dof, const double &p_value)=0
Pin p_dof-th pressure dof and set it to value specified by p_value.
virtual int p_nodal_index_pnst ()
double pressure_integral () const
Integral of pressure over element.
double dissipation () const
Return integral of dissipation over element.
double dissipation (const Vector< double > &s) const
Return dissipation at local coordinate s.
double kin_energy () const
Get integral of kinetic energy over element.
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
Strain-rate tensor: Now returns polar strain.
void strain_rate_by_r (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
Function to return polar strain multiplied by r.
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction)
void get_load (const Vector< double > &s, const Vector< double > &xi, const Vector< double > &x, const Vector< double > &N, Vector< double > &load)
void output (std::ostream &outfile)
void output (std::ostream &outfile, const unsigned &nplot)
void output (FILE *file_pt)
void output (FILE *file_pt, const unsigned &nplot)
void full_output (std::ostream &outfile)
void full_output (std::ostream &outfile, const unsigned &nplot)
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element's residual Vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
void interpolated_u_pnst (const Vector< double > &s, Vector< double > &veloc) const
Compute vector of FE interpolated velocity u at local coordinate s.
double interpolated_u_pnst (const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s.
double interpolated_p_pnst (const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s.
double interpolated_dudx_pnst (const Vector< double > &s, const unsigned &i, const unsigned &j) const
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void disable_ALE ()
virtual void enable_ALE ()
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::RefineableElement
RefineableElement ()
virtual ~RefineableElement ()
Destructor, delete the allocated storage for the hanging equations.
RefineableElement (const RefineableElement &)=delete
Broken copy constructor.
void operator= (const RefineableElement &)=delete
Broken assignment operator.
Tree * tree_pt ()
Access function: Pointer to quadtree representation of this element.
void set_tree_pt (Tree *my_tree_pt)
Set pointer to quadtree representation of this element.
virtual unsigned required_nsons () const
bool refinement_is_enabled ()
Flag to indicate suppression of any refinement.
void disable_refinement ()
Suppress of any refinement for this element.
void enable_refinement ()
Emnable refinement for this element.
template<class ELEMENT >
void split (Vector< ELEMENT * > &son_pt) const
int local_hang_eqn (Node *const &node_pt, const unsigned &i)
virtual void build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt, bool &was_already_built, std::ofstream &new_nodes_file)=0
void set_refinement_level (const int &refine_level)
Set the refinement level.
unsigned refinement_level () const
Return the Refinement level.
void select_for_refinement ()
Select the element for refinement.
void deselect_for_refinement ()
Deselect the element for refinement.
void select_sons_for_unrefinement ()
Unrefinement will be performed by merging the four sons of this element.
void deselect_sons_for_unrefinement ()
bool to_be_refined ()
Has the element been selected for refinement?
bool sons_to_be_unrefined ()
Has the element been selected for unrefinement?
virtual void rebuild_from_sons (Mesh *&mesh_pt)=0
virtual void unbuild ()
virtual void deactivate_element ()
virtual bool nodes_built ()
Return true if all the nodes have been built, false if not.
long number () const
Element number (for debugging/plotting)
void set_number (const long &mynumber)
Set element number (for debugging/plotting)
virtual unsigned ncont_interpolated_values () const =0
virtual void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
virtual void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)=0
virtual Node * interpolating_node_pt (const unsigned &n, const int &value_id)
virtual double local_one_d_fraction_of_interpolating_node (const unsigned &n1d, const unsigned &i, const int &value_id)
virtual Node * get_interpolating_node_at_local_coordinate (const Vector< double > &s, const int &value_id)
virtual unsigned ninterpolating_node (const int &value_id)
virtual unsigned ninterpolating_node_1d (const int &value_id)
virtual void interpolating_basis (const Vector< double > &s, Shape &psi, const int &value_id) const
virtual void check_integrity (double &max_error)=0
void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual RefineableElement * root_element_pt ()
virtual RefineableElement * father_element_pt () const
Return a pointer to the father element.
void get_father_at_refinement_level (unsigned &refinement_level, RefineableElement *&father_at_reflevel_pt)
virtual void initial_setup (Tree *const &adopted_father_pt=0, const unsigned &initial_p_order=0)
virtual void pre_build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt)
Pre-build the element.
virtual void setup_hanging_nodes (Vector< std::ofstream * > &output_stream)
virtual void further_setup_hanging_nodes ()
void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
unsigned nshape_controlling_nodes ()
std::map< Node *, unsigned > shape_controlling_node_lookup ()
Public Member Functions inherited from oomph::ElementWithZ2ErrorEstimator
ElementWithZ2ErrorEstimator ()
Default empty constructor.
ElementWithZ2ErrorEstimator (const ElementWithZ2ErrorEstimator &)=delete
Broken copy constructor.
void operator= (const ElementWithZ2ErrorEstimator &)=delete
Broken assignment operator.
virtual unsigned ncompound_fluxes ()
virtual void compute_exact_Z2_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_flux_pt, double &error, double &norm)
virtual void get_Z2_compound_flux_indices (Vector< unsigned > &flux_index)
virtual unsigned nvertex_node () const =0
Number of vertex nodes in the element.
virtual Node * vertex_node_pt (const unsigned &j) const =0
virtual unsigned nrecovery_order ()=0
Order of recovery shape functions.
virtual double geometric_jacobian (const Vector< double > &x)
Static Public Member Functions
static void pin_redundant_nodal_pressures (const Vector< GeneralisedElement * > &element_pt)
static void unpin_all_pressure_dofs (const Vector< GeneralisedElement * > &element_pt)
Unpin all pressure dofs in elements listed in vector.
Static Public Member Functions inherited from oomph::RefineableElement
static double & max_integrity_tolerance ()
Max. allowed discrepancy in element integrity check.
Protected Member Functions
virtual Node * pressure_node_pt (const unsigned &n_p)
virtual void unpin_elemental_pressure_dofs ()=0
Unpin all pressure dofs in the element.
virtual void pin_elemental_redundant_nodal_pressure_dofs ()
virtual void fill_in_generic_residual_contribution (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
Start of what would've been refineable_navier_stokes_elements.cc //.
Protected Member Functions inherited from oomph::PolarNavierStokesEquations
virtual int p_local_eqn (const unsigned &n)=0
virtual double dshape_and_dtest_eulerian_pnst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
virtual double dshape_and_dtest_eulerian_at_knot_pnst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
virtual void pshape_pnst (const Vector< double > &s, Shape &psi) const =0
Compute the pressure shape functions at local coordinate s.
virtual void pshape_pnst (const Vector< double > &s, Shape &psi, Shape &test) const =0
void get_body_force (double time, const Vector< double > &x, Vector< double > &result)
Calculate the body force at a given time and Eulerian position.
double get_source_fct (double time, const Vector< double > &x)
Protected Member Functions inherited from oomph::FiniteElement
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Member Functions inherited from oomph::RefineableElement
void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
void assign_hanging_local_eqn_numbers (const bool &store_local_dof_pt)
Assign the local equation numbers for hanging node variables.
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Additional Inherited Members
Public Types inherited from oomph::PolarNavierStokesEquations
typedef void(* NavierStokesBodyForceFctPt) (const double &time, const Vector< double > &x, Vector< double > &body_force)
typedef double(* NavierStokesSourceFctPt) (const double &time, const Vector< double > &x)
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Static Public Attributes inherited from oomph::PolarNavierStokesEquations
static Vector< double > Gamma
Vector to decide whether the stress-divergence form is used or not.
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Static Protected Member Functions inherited from oomph::RefineableElement
static void check_value_id (const int &n_continuously_interpolated_values, const int &value_id)
Protected Attributes inherited from oomph::PolarNavierStokesEquations
double * Viscosity_Ratio_pt
double * Density_Ratio_pt
double * Alpha_pt
Pointer to the angle alpha.
double * Re_pt
Pointer to global Reynolds number.
double * ReSt_pt
Pointer to global Reynolds number x Strouhal number (=Womersley)
double * ReInvFr_pt
Vector< double > * G_pt
Pointer to global gravity Vector.
NavierStokesBodyForceFctPt Body_force_fct_pt
Pointer to body force function.
NavierStokesSourceFctPt Source_fct_pt
Pointer to volumetric source function.
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Protected Attributes inherited from oomph::RefineableElement
Tree * Tree_pt
A pointer to a general tree object.
unsigned Refine_level
Refinement level.
bool To_be_refined
Flag for refinement.
bool Refinement_is_enabled
Flag to indicate suppression of any refinement.
bool Sons_to_be_unrefined
Flag for unrefinement.
long Number
Global element number – for plotting/validation purposes.
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Static Protected Attributes inherited from oomph::RefineableElement
static double Max_integrity_tolerance = 1.0e-8
Max. allowed discrepancy in element integrity check.
Detailed Description
Refineable version of my Polar Navier–Stokes equations
Constructor & Destructor Documentation
RefineablePolarNavierStokesEquations()
oomph::RefineablePolarNavierStokesEquations::RefineablePolarNavierStokesEquations () inline
Constructor.
       : PolarNavierStokesEquations(),
         RefineableElement(),
         ElementWithZ2ErrorEstimator()
     {
     }
Member Function Documentation
fill_in_generic_residual_contribution()
void oomph::RefineablePolarNavierStokesEquations::fill_in_generic_residual_contribution (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, unsigned flag) protected virtual
Start of what would've been refineable_navier_stokes_elements.cc //.
Add element's contribution to elemental residual vector and/or Jacobian matrix flag=1: compute both flag=0: compute only residual vector
Compute the residuals for the Navier–Stokes equations; flag=1(or 0): do (or don't) compute the Jacobian as well. flag=2 for Residuals, Jacobian and mass_matrix
This is now my new version with Jacobian and dimensionless phi
This version supports hanging nodes
Reimplemented from oomph::PolarNavierStokesEquations.
   {
     // Find out how many nodes there are
     unsigned n_node = nnode();
     // Find out how many pressure dofs there are
     unsigned n_pres = npres_pnst();
     // Find the indices at which the local velocities are stored
     unsigned u_nodal_index[2];
     for (unsigned i = 0; i < 2; i++)
     {
       u_nodal_index[i] = u_index_pnst(i);
     }
     // Which nodal value represents the pressure? (Negative if pressure
     // is not based on nodal interpolation).
     int p_index = this->p_nodal_index_pnst();
     // Local array of booleans that are true if the l-th pressure value is
     // hanging (avoid repeated virtual function calls)
     bool pressure_dof_is_hanging[n_pres];
     // If the pressure is stored at a node
     if (p_index >= 0)
     {
       // Read out whether the pressure is hanging
       for (unsigned l = 0; l < n_pres; ++l)
       {
         pressure_dof_is_hanging[l] = pressure_node_pt(l)->is_hanging(p_index);
       }
     }
     // Otherwise the pressure is not stored at a node and so cannot hang
     else
     {
       for (unsigned l = 0; l < n_pres; ++l)
       {
         pressure_dof_is_hanging[l] = false;
       }
     }
     // Set up memory for the shape and test functions
     Shape psif(n_node), testf(n_node);
     DShape dpsifdx(n_node, 2), dtestfdx(n_node, 2);
     // Set up memory for pressure shape and test functions
     Shape psip(n_pres), testp(n_pres);
     // Number of integration points
     unsigned n_intpt = integral_pt()->nweight();
     // Set the Vector to hold local coordinates
     Vector<double> s(2);
     // Get the reynolds number and Alpha
     const double Re = re();
     const double Alpha = alpha();
     const double Re_St = re_st();
     // Integers to store the local equations and unknowns
     int local_eqn = 0, local_unknown = 0;
     // Pointers to hang info objects
     HangInfo *hang_info_pt = 0, *hang_info2_pt = 0;
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Assign values of s
       for (unsigned i = 0; i < 2; i++) s[i] = integral_pt()->knot(ipt, i);
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Call the derivatives of the shape and test functions
       double J = dshape_and_dtest_eulerian_at_knot_pnst(
         ipt, psif, dpsifdx, testf, dtestfdx);
       // Call the pressure shape and test functions
       this->pshape_pnst(s, psip, testp);
       // Premultiply the weights and the Jacobian
       double W = w * J;
       // Calculate local values of the pressure and velocity components
       // Allocate storage initialised to zero
       double interpolated_p = 0.0;
       Vector<double> interpolated_u(2, 0.0);
       Vector<double> interpolated_x(2, 0.0);
       // Vector<double> dudt(2);
       DenseMatrix<double> interpolated_dudx(2, 2, 0.0);
       // Initialise to zero
       for (unsigned i = 0; i < 2; i++)
       {
         // dudt[i] = 0.0;
         interpolated_u[i] = 0.0;
         interpolated_x[i] = 0.0;
         for (unsigned j = 0; j < 2; j++)
         {
           interpolated_dudx(i, j) = 0.0;
         }
       }
       // Calculate pressure
       for (unsigned l = 0; l < n_pres; l++)
         interpolated_p += this->p_pnst(l) * psip[l];
       // Calculate velocities and derivatives:
       // Loop over nodes
       for (unsigned l = 0; l < n_node; l++)
       {
         // Loop over directions
         for (unsigned i = 0; i < 2; i++)
         {
           // Get the nodal value
           double u_value = this->nodal_value(l, u_nodal_index[i]);
           interpolated_u[i] += u_value * psif[l];
           interpolated_x[i] += this->nodal_position(l, i) * psif[l];
           // dudt[i]+=du_dt_pnst(l,i)*psif[l];
           // Loop over derivative directions
           for (unsigned j = 0; j < 2; j++)
           {
             interpolated_dudx(i, j) += u_value * dpsifdx(l, j);
           }
         }
       }
       // MOMENTUM EQUATIONS
       //------------------
       // Number of master nodes and storage for the weight of the shape function
       unsigned n_master = 1;
       double hang_weight = 1.0;
       // Loop over the nodes for the test functions
       for (unsigned l = 0; l < n_node; l++)
       {
         // Local boolean to indicate whether the node is hanging
         bool is_node_hanging = node_pt(l)->is_hanging();
         // If the node is hanging
         if (is_node_hanging)
         {
           hang_info_pt = node_pt(l)->hanging_pt();
           // Read out number of master nodes from hanging data
           n_master = hang_info_pt->nmaster();
         }
         // Otherwise the node is its own master
         else
         {
           n_master = 1;
         }
         // Now add in a new loop over the master nodes
         for (unsigned m = 0; m < n_master; m++)
         {
           // Can't loop over velocity components as don't have identical
           // contributions Do seperately for i = {0,1} instead
           unsigned i = 0;
           {
             // Get the equation number
             // If the node is hanging
             if (is_node_hanging)
             {
               // Get the equation number from the master node
               local_eqn = this->local_hang_eqn(hang_info_pt->master_node_pt(m),
                                                u_nodal_index[i]);
               // Get the hang weight from the master node
               hang_weight = hang_info_pt->master_weight(m);
             }
             // If the node is not hanging
             else
             {
               // Local equation number
               local_eqn = this->nodal_local_eqn(l, u_nodal_index[i]);
               // Node contributes with full weight
               hang_weight = 1.0;
             }
             /*IF it's not a boundary condition*/
             if (local_eqn >= 0)
             {
               // Add the testf[l] term of the stress tensor
               residuals[local_eqn] +=
                 ((interpolated_p / interpolated_x[0]) -
                  ((1. + Gamma[i]) / pow(interpolated_x[0], 2.)) *
                    ((1. / Alpha) * interpolated_dudx(1, 1) +
                     interpolated_u[0])) *
                 testf[l] * interpolated_x[0] * Alpha * W * hang_weight;
               // Add the dtestfdx(l,0) term of the stress tensor
               residuals[local_eqn] +=
                 (interpolated_p - (1. + Gamma[i]) * interpolated_dudx(0, 0)) *
                 dtestfdx(l, 0) * interpolated_x[0] * Alpha * W * hang_weight;
               // Add the dtestfdx(l,1) term of the stress tensor
               residuals[local_eqn] -=
                 ((1. / (interpolated_x[0] * Alpha)) * interpolated_dudx(0, 1) -
                  (interpolated_u[1] / interpolated_x[0]) +
                  Gamma[i] * interpolated_dudx(1, 0)) *
                 (1. / (interpolated_x[0] * Alpha)) * dtestfdx(l, 1) *
                 interpolated_x[0] * Alpha * W * hang_weight;
               // Convective terms
               residuals[local_eqn] -=
                 Re *
                 (interpolated_u[0] * interpolated_dudx(0, 0) +
                  (interpolated_u[1] / (interpolated_x[0] * Alpha)) *
                    interpolated_dudx(0, 1) -
                  (pow(interpolated_u[1], 2.) / interpolated_x[0])) *
                 testf[l] * interpolated_x[0] * Alpha * W * hang_weight;
               // CALCULATE THE JACOBIAN
               if (flag)
               {
                 // Number of master nodes and weights
                 unsigned n_master2 = 1;
                 double hang_weight2 = 1.0;
                 // Loop over the velocity shape functions again
                 for (unsigned l2 = 0; l2 < n_node; l2++)
                 {
                   // Local boolean to indicate whether the node is hanging
                   bool is_node2_hanging = node_pt(l2)->is_hanging();
                   // If the node is hanging
                   if (is_node2_hanging)
                   {
                     hang_info2_pt = node_pt(l2)->hanging_pt();
                     // Read out number of master nodes from hanging data
                     n_master2 = hang_info2_pt->nmaster();
                   }
                   // Otherwise the node is its own master
                   else
                   {
                     n_master2 = 1;
                   }
                   // Loop over the master nodes
                   for (unsigned m2 = 0; m2 < n_master2; m2++)
                   {
                     // Again can't loop over velocity components due to loss of
                     // symmetry
                     unsigned i2 = 0;
                     {
                       // Get the number of the unknown
                       // If the node is hanging
                       if (is_node2_hanging)
                       {
                         // Get the equation number from the master node
                         local_unknown = this->local_hang_eqn(
                           hang_info2_pt->master_node_pt(m2), u_nodal_index[i2]);
                         // Get the hang weights
                         hang_weight2 = hang_info2_pt->master_weight(m2);
                       }
                       else
                       {
                         local_unknown =
                           this->nodal_local_eqn(l2, u_nodal_index[i2]);
                         hang_weight2 = 1.0;
                       }
                       // If at a non-zero degree of freedom add in the entry
                       if (local_unknown >= 0)
                       {
                         // Add contribution to Elemental Matrix
                         jacobian(local_eqn, local_unknown) -=
                           (1. + Gamma[i]) *
                           (psif[l2] / pow(interpolated_x[0], 2.)) * testf[l] *
                           interpolated_x[0] * Alpha * W * hang_weight *
                           hang_weight2;
                         jacobian(local_eqn, local_unknown) -=
                           (1. + Gamma[i]) * dpsifdx(l2, 0) * dtestfdx(l, 0) *
                           interpolated_x[0] * Alpha * W * hang_weight *
                           hang_weight2;
                         jacobian(local_eqn, local_unknown) -=
                           (1. / (interpolated_x[0] * Alpha)) * dpsifdx(l2, 1) *
                           (1. / (interpolated_x[0] * Alpha)) * dtestfdx(l, 1) *
                           interpolated_x[0] * Alpha * W * hang_weight *
                           hang_weight2;
                         // Now add in the inertial terms
                         jacobian(local_eqn, local_unknown) -=
                           Re *
                           (psif[l2] * interpolated_dudx(0, 0) +
                            interpolated_u[0] * dpsifdx(l2, 0) +
                            (interpolated_u[1] / (interpolated_x[0] * Alpha)) *
                              dpsifdx(l2, 1)) *
                           testf[l] * interpolated_x[0] * Alpha * W *
                           hang_weight * hang_weight2;
                         // extra bit for mass matrix
                         if (flag == 2)
{
                           mass_matrix(local_eqn, local_unknown) +=
                             Re_St * psif[l2] * testf[l] * interpolated_x[0] *
                             Alpha * W * hang_weight * hang_weight2;
                         }
                       } // End of (Jacobian's) if not boundary condition
                         // statement
                     } // End of i2=0 section
                     i2 = 1;
                     {
                       // Get the number of the unknown
                       // If the node is hanging
                       if (is_node2_hanging)
                       {
                         // Get the equation number from the master node
                         local_unknown = this->local_hang_eqn(
                           hang_info2_pt->master_node_pt(m2), u_nodal_index[i2]);
                         // Get the hang weights
                         hang_weight2 = hang_info2_pt->master_weight(m2);
                       }
                       else
                       {
                         local_unknown =
                           this->nodal_local_eqn(l2, u_nodal_index[i2]);
                         hang_weight2 = 1.0;
                       }
                       // If at a non-zero degree of freedom add in the entry
                       if (local_unknown >= 0)
                       {
                         // Add contribution to Elemental Matrix
                         jacobian(local_eqn, local_unknown) -=
                           ((1. + Gamma[i]) /
                            (pow(interpolated_x[0], 2.) * Alpha)) *
                           dpsifdx(l2, 1) * testf[l] * interpolated_x[0] *
                           Alpha * W * hang_weight * hang_weight2;
                         jacobian(local_eqn, local_unknown) -=
                           (-(psif[l2] / interpolated_x[0]) +
                            Gamma[i] * dpsifdx(l2, 0)) *
                           (1. / (interpolated_x[0] * Alpha)) * dtestfdx(l, 1) *
                           interpolated_x[0] * Alpha * W * hang_weight *
                           hang_weight2;
                         // Now add in the inertial terms
                         jacobian(local_eqn, local_unknown) -=
                           Re *
                           ((psif[l2] / (interpolated_x[0] * Alpha)) *
                              interpolated_dudx(0, 1) -
                            2 * interpolated_u[1] *
                              (psif[l2] / interpolated_x[0])) *
                           testf[l] * interpolated_x[0] * Alpha * W *
                           hang_weight * hang_weight2;
                       } // End of (Jacobian's) if not boundary condition
                         // statement
                     } // End of i2=1 section
                   } // End of loop over master nodes m2
                 } // End of l2 loop
                 /*Now loop over pressure shape functions*/
                 /*This is the contribution from pressure gradient*/
                 for (unsigned l2 = 0; l2 < n_pres; l2++)
                 {
                   // If the pressure dof is hanging
                   if (pressure_dof_is_hanging[l2])
                   {
                     hang_info2_pt =
                       this->pressure_node_pt(l2)->hanging_pt(p_index);
                     // Pressure dof is hanging so it must be nodal-based
                     // Get the number of master nodes from the pressure node
                     n_master2 = hang_info2_pt->nmaster();
                   }
                   // Otherwise the node is its own master
                   else
                   {
                     n_master2 = 1;
                   }
                   // Loop over the master nodes
                   for (unsigned m2 = 0; m2 < n_master2; m2++)
                   {
                     // Get the number of the unknown
                     // If the pressure dof is hanging
                     if (pressure_dof_is_hanging[l2])
                     {
                       // Get the unknown from the master node
                       local_unknown = this->local_hang_eqn(
                         hang_info2_pt->master_node_pt(m2), p_index);
                       // Get the weight from the hanging object
                       hang_weight2 = hang_info2_pt->master_weight(m2);
                     }
                     else
                     {
                       local_unknown = this->p_local_eqn(l2);
                       hang_weight2 = 1.0;
                     }
                     /*If we are at a non-zero degree of freedom in the entry*/
                     if (local_unknown >= 0)
                     {
                       jacobian(local_eqn, local_unknown) +=
                         (psip[l2] / interpolated_x[0]) * testf[l] *
                         interpolated_x[0] * Alpha * W * hang_weight *
                         hang_weight2;
                       jacobian(local_eqn, local_unknown) +=
                         psip[l2] * dtestfdx(l, 0) * interpolated_x[0] * Alpha *
                         W * hang_weight * hang_weight2;
                     } // End of Jacobian pressure if not a boundary condition
                       // statement
                   } // End of loop over master nodes m2
                 } // End of loop over pressure shape functions l2
               } /*End of Jacobian calculation*/
             } // End of if not boundary condition statement
           } // End of i=0 section
           i = 1;
           {
             // Get the equation number
             // If the node is hanging
             if (is_node_hanging)
             {
               // Get the equation number from the master node
               local_eqn = this->local_hang_eqn(hang_info_pt->master_node_pt(m),
                                                u_nodal_index[i]);
               // Get the hang weight from the master node
               hang_weight = hang_info_pt->master_weight(m);
             }
             // If the node is not hanging
             else
             {
               // Local equation number
               local_eqn = this->nodal_local_eqn(l, u_nodal_index[i]);
               // Node contributes with full weight
               hang_weight = 1.0;
             }
             /*IF it's not a boundary condition*/
             if (local_eqn >= 0)
             {
               // Add the testf[l] term of the stress tensor
               residuals[local_eqn] +=
                 ((1. / (pow(interpolated_x[0], 2.) * Alpha)) *
                    interpolated_dudx(0, 1) -
                  (interpolated_u[1] / pow(interpolated_x[0], 2.)) +
                  Gamma[i] * (1. / interpolated_x[0]) *
                    interpolated_dudx(1, 0)) *
                 testf[l] * interpolated_x[0] * Alpha * W * hang_weight;
               // Add the dtestfdx(l,0) term of the stress tensor
               residuals[local_eqn] -=
                 (interpolated_dudx(1, 0) +
                  Gamma[i] * ((1. / (interpolated_x[0] * Alpha)) *
                                interpolated_dudx(0, 1) -
                              (interpolated_u[1] / interpolated_x[0]))) *
                 dtestfdx(l, 0) * interpolated_x[0] * Alpha * W * hang_weight;
               // Add the dtestfdx(l,1) term of the stress tensor
               residuals[local_eqn] +=
                 (interpolated_p -
                  (1. + Gamma[i]) * ((1. / (interpolated_x[0] * Alpha)) *
                                       interpolated_dudx(1, 1) +
                                     (interpolated_u[0] / interpolated_x[0]))) *
                 (1. / (interpolated_x[0] * Alpha)) * dtestfdx(l, 1) *
                 interpolated_x[0] * Alpha * W * hang_weight;
               // Convective terms
               residuals[local_eqn] -=
                 Re *
                 (interpolated_u[0] * interpolated_dudx(1, 0) +
                  (interpolated_u[1] / (interpolated_x[0] * Alpha)) *
                    interpolated_dudx(1, 1) +
                  ((interpolated_u[0] * interpolated_u[1]) /
                   interpolated_x[0])) *
                 testf[l] * interpolated_x[0] * Alpha * W * hang_weight;
               // CALCULATE THE JACOBIAN
               if (flag)
               {
                 // Number of master nodes and weights
                 unsigned n_master2 = 1;
                 double hang_weight2 = 1.0;
                 // Loop over the velocity shape functions again
                 for (unsigned l2 = 0; l2 < n_node; l2++)
                 {
                   // Local boolean to indicate whether the node is hanging
                   bool is_node2_hanging = node_pt(l2)->is_hanging();
                   // If the node is hanging
                   if (is_node2_hanging)
                   {
                     hang_info2_pt = node_pt(l2)->hanging_pt();
                     // Read out number of master nodes from hanging data
                     n_master2 = hang_info2_pt->nmaster();
                   }
                   // Otherwise the node is its own master
                   else
                   {
                     n_master2 = 1;
                   }
                   // Loop over the master nodes
                   for (unsigned m2 = 0; m2 < n_master2; m2++)
                   {
                     // Again can't loop over velocity components due to loss of
                     // symmetry
                     unsigned i2 = 0;
                     {
                       // Get the number of the unknown
                       // If the node is hanging
                       if (is_node2_hanging)
                       {
                         // Get the equation number from the master node
                         local_unknown = this->local_hang_eqn(
                           hang_info2_pt->master_node_pt(m2), u_nodal_index[i2]);
                         // Get the hang weights
                         hang_weight2 = hang_info2_pt->master_weight(m2);
                       }
                       else
                       {
                         local_unknown =
                           this->nodal_local_eqn(l2, u_nodal_index[i2]);
                         hang_weight2 = 1.0;
                       }
                       // If at a non-zero degree of freedom add in the entry
                       if (local_unknown >= 0)
                       {
                         // Add contribution to Elemental Matrix
                         jacobian(local_eqn, local_unknown) +=
                           (1. / (pow(interpolated_x[0], 2.) * Alpha)) *
                           dpsifdx(l2, 1) * testf[l] * interpolated_x[0] *
                           Alpha * W * hang_weight * hang_weight2;
                         jacobian(local_eqn, local_unknown) -=
                           Gamma[i] * (1. / (interpolated_x[0] * Alpha)) *
                           dpsifdx(l2, 1) * dtestfdx(l, 0) * interpolated_x[0] *
                           Alpha * W * hang_weight * hang_weight2;
                         jacobian(local_eqn, local_unknown) -=
                           (1 + Gamma[i]) * (psif[l2] / interpolated_x[0]) *
                           (1. / (interpolated_x[0] * Alpha)) * dtestfdx(l, 1) *
                           interpolated_x[0] * Alpha * W * hang_weight *
                           hang_weight2;
                         // Now add in the inertial terms
                         jacobian(local_eqn, local_unknown) -=
                           Re *
                           (psif[l2] * interpolated_dudx(1, 0) +
                            (psif[l2] * interpolated_u[1] / interpolated_x[0])) *
                           testf[l] * interpolated_x[0] * Alpha * W *
                           hang_weight * hang_weight2;
                       } // End of (Jacobian's) if not boundary condition
                         // statement
                     } // End of i2=0 section
                     i2 = 1;
                     {
                       // Get the number of the unknown
                       // If the node is hanging
                       if (is_node2_hanging)
                       {
                         // Get the equation number from the master node
                         local_unknown = this->local_hang_eqn(
                           hang_info2_pt->master_node_pt(m2), u_nodal_index[i2]);
                         // Get the hang weights
                         hang_weight2 = hang_info2_pt->master_weight(m2);
                       }
                       else
                       {
                         local_unknown =
                           this->nodal_local_eqn(l2, u_nodal_index[i2]);
                         hang_weight2 = 1.0;
                       }
                       // If at a non-zero degree of freedom add in the entry
                       if (local_unknown >= 0)
                       {
                         // Add contribution to Elemental Matrix
                         jacobian(local_eqn, local_unknown) +=
                           (-(psif[l2] / pow(interpolated_x[0], 2.)) +
                            Gamma[i] * (1. / interpolated_x[0]) *
                              dpsifdx(l2, 0)) *
                           testf[l] * interpolated_x[0] * Alpha * W *
                           hang_weight * hang_weight2;
                         jacobian(local_eqn, local_unknown) -=
                           (dpsifdx(l2, 0) -
                            Gamma[i] * (psif[l2] / interpolated_x[0])) *
                           dtestfdx(l, 0) * interpolated_x[0] * Alpha * W *
                           hang_weight * hang_weight2;
                         jacobian(local_eqn, local_unknown) -=
                           (1. + Gamma[i]) * (1. / (interpolated_x[0] * Alpha)) *
                           dpsifdx(l2, 1) * (1. / (interpolated_x[0] * Alpha)) *
                           dtestfdx(l, 1) * interpolated_x[0] * Alpha * W *
                           hang_weight * hang_weight2;
                         // Now add in the inertial terms
                         jacobian(local_eqn, local_unknown) -=
                           Re *
                           (interpolated_u[0] * dpsifdx(l2, 0) +
                            (psif[l2] / (interpolated_x[0] * Alpha)) *
                              interpolated_dudx(1, 1) +
                            (interpolated_u[1] / (interpolated_x[0] * Alpha)) *
                              dpsifdx(l2, 1) +
                            (interpolated_u[0] * psif[l2] / interpolated_x[0])) *
                           testf[l] * interpolated_x[0] * Alpha * W *
                           hang_weight * hang_weight2;
                         // extra bit for mass matrix
                         if (flag == 2)
{
                           mass_matrix(local_eqn, local_unknown) +=
                             Re_St * psif[l2] * testf[l] * interpolated_x[0] *
                             Alpha * W * hang_weight * hang_weight2;
                         }
                       } // End of (Jacobian's) if not boundary condition
                         // statement
                     } // End of i2=1 section
                   } // End of loop over master nodes m2
                 } // End of l2 loop
                 /*Now loop over pressure shape functions*/
                 /*This is the contribution from pressure gradient*/
                 for (unsigned l2 = 0; l2 < n_pres; l2++)
                 {
                   // If the pressure dof is hanging
                   if (pressure_dof_is_hanging[l2])
                   {
                     hang_info2_pt =
                       this->pressure_node_pt(l2)->hanging_pt(p_index);
                     // Pressure dof is hanging so it must be nodal-based
                     // Get the number of master nodes from the pressure node
                     n_master2 = hang_info2_pt->nmaster();
                   }
                   // Otherwise the node is its own master
                   else
                   {
                     n_master2 = 1;
                   }
                   // Loop over the master nodes
                   for (unsigned m2 = 0; m2 < n_master2; m2++)
                   {
                     // Get the number of the unknown
                     // If the pressure dof is hanging
                     if (pressure_dof_is_hanging[l2])
                     {
                       // Get the unknown from the master node
                       local_unknown = this->local_hang_eqn(
                         hang_info2_pt->master_node_pt(m2), p_index);
                       // Get the weight from the hanging object
                       hang_weight2 = hang_info2_pt->master_weight(m2);
                     }
                     else
                     {
                       local_unknown = this->p_local_eqn(l2);
                       hang_weight2 = 1.0;
                     }
                     /*If we are at a non-zero degree of freedom in the entry*/
                     if (local_unknown >= 0)
                     {
                       jacobian(local_eqn, local_unknown) +=
                         (psip[l2] / interpolated_x[0]) * (1. / Alpha) *
                         dtestfdx(l, 1) * interpolated_x[0] * Alpha * W *
                         hang_weight * hang_weight2;
                     } // End of if not boundary condition for pressure in
                       // jacobian
                   } // End of loop over master nodes m2
                 } // End of loop over pressure test functions l2
               } /*End of Jacobian calculation*/
             } // End of if not boundary condition statement
           } // End of i=1 section
         } // End of loop over master nodes m
       } // End of loop over shape functions
       // CONTINUITY EQUATION
       //-------------------
       // Loop over the shape functions
       for (unsigned l = 0; l < n_pres; l++)
       {
         // If the pressure dof is hanging
         if (pressure_dof_is_hanging[l])
         {
           // Pressure dof is hanging so it must be nodal-based
           // Get the hang info object
           hang_info_pt = this->pressure_node_pt(l)->hanging_pt(p_index);
           // Get the number of master nodes from the pressure node
           n_master = hang_info_pt->nmaster();
         }
         // Otherwise the node is its own master
         else
         {
           n_master = 1;
         }
         // Loop over the master nodes
         for (unsigned m = 0; m < n_master; m++)
         {
           // Get the number of the unknown
           // If the pressure dof is hanging
           if (pressure_dof_is_hanging[l])
           {
             // Get the local equation from the master node
             local_eqn =
               this->local_hang_eqn(hang_info_pt->master_node_pt(m), p_index);
             // Get the weight for the node
             hang_weight = hang_info_pt->master_weight(m);
           }
           else
           {
             local_eqn = this->p_local_eqn(l);
             hang_weight = 1.0;
           }
           // If not a boundary conditions
           if (local_eqn >= 0)
           {
             residuals[local_eqn] +=
               (interpolated_dudx(0, 0) +
                (interpolated_u[0] / interpolated_x[0]) +
                (1. / (interpolated_x[0] * Alpha)) * interpolated_dudx(1, 1)) *
               testp[l] * interpolated_x[0] * Alpha * W * hang_weight;
             /*CALCULATE THE JACOBIAN*/
             if (flag)
             {
               unsigned n_master2 = 1;
               double hang_weight2 = 1.0;
               /*Loop over the velocity shape functions*/
               for (unsigned l2 = 0; l2 < n_node; l2++)
               {
                 // Local boolean to indicate whether the node is hanging
                 bool is_node2_hanging = node_pt(l2)->is_hanging();
                 // If the node is hanging
                 if (is_node2_hanging)
                 {
                   hang_info2_pt = node_pt(l2)->hanging_pt();
                   // Read out number of master nodes from hanging data
                   n_master2 = hang_info2_pt->nmaster();
                 }
                 // Otherwise the node is its own master
                 else
                 {
                   n_master2 = 1;
                 }
                 // Loop over the master nodes
                 for (unsigned m2 = 0; m2 < n_master2; m2++)
                 {
                   unsigned i2 = 0;
                   {
                     // Get the number of the unknown
                     // If the node is hanging
                     if (is_node2_hanging)
                     {
                       // Get the equation number from the master node
                       local_unknown = this->local_hang_eqn(
                         hang_info2_pt->master_node_pt(m2), u_nodal_index[i2]);
                       hang_weight2 = hang_info2_pt->master_weight(m2);
                     }
                     else
                     {
                       local_unknown =
                         this->nodal_local_eqn(l2, u_nodal_index[i2]);
                       hang_weight2 = 1.0;
                     }
                     /*If we're at a non-zero degree of freedom add it in*/
                     if (local_unknown >= 0)
                     {
                       jacobian(local_eqn, local_unknown) +=
                         (dpsifdx(l2, 0) + (psif[l2] / interpolated_x[0])) *
                         testp[l] * interpolated_x[0] * Alpha * W * hang_weight *
                         hang_weight2;
                     }
                   } // End of i2=0 section
                   i2 = 1;
                   {
                     // Get the number of the unknown
                     // If the node is hanging
                     if (is_node2_hanging)
                     {
                       // Get the equation number from the master node
                       local_unknown = this->local_hang_eqn(
                         hang_info2_pt->master_node_pt(m2), u_nodal_index[i2]);
                       hang_weight2 = hang_info2_pt->master_weight(m2);
                     }
                     else
                     {
                       local_unknown =
                         this->nodal_local_eqn(l2, u_nodal_index[i2]);
                       hang_weight2 = 1.0;
                     }
                     /*If we're at a non-zero degree of freedom add it in*/
                     if (local_unknown >= 0)
                     {
                       jacobian(local_eqn, local_unknown) +=
                         (1. / (interpolated_x[0] * Alpha)) * dpsifdx(l2, 1) *
                         testp[l] * interpolated_x[0] * Alpha * W * hang_weight *
                         hang_weight2;
                     }
                   } // End of i2=1 section
                 } // End of loop over master nodes m2
               } /*End of loop over l2*/
             } /*End of Jacobian calculation*/
           } // End of if not boundary condition
         } // End of loop over master nodes m
       } // End of loop over pressure test functions l
     } // End of loop over integration points
   } // End of add_generic_residual_contribution
References TanhSolnForAdvectionDiffusion::Alpha, oomph::PolarNavierStokesEquations::alpha(), oomph::PolarNavierStokesEquations::dshape_and_dtest_eulerian_at_knot_pnst(), oomph::PolarNavierStokesEquations::Gamma, oomph::Node::hanging_pt(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), oomph::Node::is_hanging(), J, j, oomph::Integral::knot(), oomph::RefineableElement::local_hang_eqn(), m, m2(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::PolarNavierStokesEquations::npres_pnst(), oomph::Integral::nweight(), oomph::PolarNavierStokesEquations::p_local_eqn(), oomph::PolarNavierStokesEquations::p_nodal_index_pnst(), oomph::PolarNavierStokesEquations::p_pnst(), Eigen::bfloat16_impl::pow(), pressure_node_pt(), oomph::PolarNavierStokesEquations::pshape_pnst(), GlobalPhysicalVariables::Re, oomph::PolarNavierStokesEquations::re(), oomph::Problem_Parameter::Re_St, oomph::PolarNavierStokesEquations::re_st(), s, oomph::PolarNavierStokesEquations::u_index_pnst(), w, oomph::QuadTreeNames::W, and oomph::Integral::weight().
further_build()
void oomph::RefineablePolarNavierStokesEquations::further_build () inline virtual
Further build, pass the pointers down to the sons.
Reimplemented from oomph::RefineableElement.
Reimplemented in oomph::RefineablePolarCrouzeixRaviartElement.
     {
       // Find the father element
       RefineablePolarNavierStokesEquations* cast_father_element_pt =
         dynamic_cast<RefineablePolarNavierStokesEquations*>(
           this->father_element_pt());
       // Set the viscosity ratio pointer
       this->Viscosity_Ratio_pt = cast_father_element_pt->viscosity_ratio_pt();
       // Set the density ratio pointer
       this->Density_Ratio_pt = cast_father_element_pt->density_ratio_pt();
       // Set pointer to global Reynolds number
       this->Re_pt = cast_father_element_pt->re_pt();
       // Set pointer to global Reynolds number x Strouhal number (=Womersley)
       this->ReSt_pt = cast_father_element_pt->re_st_pt();
       // Set pointer to global Reynolds number x inverse Froude number
       this->ReInvFr_pt = cast_father_element_pt->re_invfr_pt();
       // Set pointer to global gravity Vector
       this->G_pt = cast_father_element_pt->g_pt();
       // Set pointer to alpha
       this->Alpha_pt = cast_father_element_pt->alpha_pt();
       // Set pointer to body force function
       this->Body_force_fct_pt = cast_father_element_pt->body_force_fct_pt();
       // Set pointer to volumetric source function
       this->Source_fct_pt = cast_father_element_pt->source_fct_pt();
     }
References oomph::PolarNavierStokesEquations::Alpha_pt, oomph::PolarNavierStokesEquations::alpha_pt(), oomph::PolarNavierStokesEquations::Body_force_fct_pt, oomph::PolarNavierStokesEquations::body_force_fct_pt(), oomph::PolarNavierStokesEquations::Density_Ratio_pt, oomph::PolarNavierStokesEquations::density_ratio_pt(), oomph::RefineableElement::father_element_pt(), oomph::PolarNavierStokesEquations::G_pt, oomph::PolarNavierStokesEquations::g_pt(), oomph::PolarNavierStokesEquations::re_invfr_pt(), oomph::PolarNavierStokesEquations::Re_pt, oomph::PolarNavierStokesEquations::re_pt(), oomph::PolarNavierStokesEquations::re_st_pt(), oomph::PolarNavierStokesEquations::ReInvFr_pt, oomph::PolarNavierStokesEquations::ReSt_pt, oomph::PolarNavierStokesEquations::Source_fct_pt, oomph::PolarNavierStokesEquations::source_fct_pt(), oomph::PolarNavierStokesEquations::Viscosity_Ratio_pt, and oomph::PolarNavierStokesEquations::viscosity_ratio_pt().
Referenced by oomph::RefineablePolarCrouzeixRaviartElement::further_build().
get_Z2_flux()
void oomph::RefineablePolarNavierStokesEquations::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) inline virtual
Get 'flux' for Z2 error recovery: Upper triangular entries in strain rate tensor.
Implements oomph::ElementWithZ2ErrorEstimator.
     {
 #ifdef PARANOID
       unsigned num_entries = 3;
       if (flux.size() != num_entries)
       {
         std::ostringstream error_message;
         error_message << "The flux vector has the wrong number of entries, "
                       << flux.size() << ", whereas it should be " << num_entries
                       << std::endl;
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // Get strain rate matrix
       DenseMatrix<double> strainrate(2);
       // this->strain_rate(s,strainrate);
       this->strain_rate_by_r(s, strainrate);
       // Pack into flux Vector
       unsigned icount = 0;
       // Start with diagonal terms
       for (unsigned i = 0; i < 2; i++)
       {
         flux[icount] = strainrate(i, i);
         icount++;
       }
       // Off diagonals row by row
       for (unsigned i = 0; i < 2; i++)
       {
         for (unsigned j = i + 1; j < 2; j++)
         {
           flux[icount] = strainrate(i, j);
           icount++;
         }
       }
     }
References ProblemParameters::flux(), i, j, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::PolarNavierStokesEquations::strain_rate_by_r().
num_Z2_flux_terms()
unsigned oomph::RefineablePolarNavierStokesEquations::num_Z2_flux_terms () inline virtual
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
     {
       // DIM diagonal strain rates, DIM(DIM -1) /2 off diagonal rates
       return 3;
     }
pin_elemental_redundant_nodal_pressure_dofs()
virtual void oomph::RefineablePolarNavierStokesEquations::pin_elemental_redundant_nodal_pressure_dofs () inline protected virtual
Pin unused nodal pressure dofs (empty by default, because by default pressure dofs are not associated with nodes)
Reimplemented in oomph::RefineablePolarTaylorHoodElement.
 {}
Referenced by pin_redundant_nodal_pressures().
pin_redundant_nodal_pressures()
static void oomph::RefineablePolarNavierStokesEquations::pin_redundant_nodal_pressures (const Vector< GeneralisedElement * > & element_pt) inline static
Loop over all elements in Vector (which typically contains all the elements in a fluid mesh) and pin the nodal pressure degrees of freedom that are not being used. Function uses the member function
RefineablePolarNavierStokesEquations:: pin_elemental_redundant_nodal_pressure_dofs()
which is empty by default and should be implemented for elements with nodal pressure degrees of freedom (e.g. for refineable Taylor-Hood.)
     {
       // Loop over all elements and call the function that pins their
       // unused nodal pressure data
       unsigned n_element = element_pt.size();
       for (unsigned e = 0; e < n_element; e++)
       {
         dynamic_cast<RefineablePolarNavierStokesEquations*>(element_pt[e])
           ->pin_elemental_redundant_nodal_pressure_dofs();
       }
     }
References e(), and pin_elemental_redundant_nodal_pressure_dofs().
pressure_node_pt()
virtual Node* oomph::RefineablePolarNavierStokesEquations::pressure_node_pt (const unsigned & n_p) inline protected virtual
Pointer to n_p-th pressure node (Default: NULL, indicating that pressure is not based on nodal interpolation).
Reimplemented from oomph::PolarNavierStokesEquations.
Reimplemented in oomph::RefineablePolarTaylorHoodElement.
     {
       return NULL;
     }
Referenced by fill_in_generic_residual_contribution().
unpin_all_pressure_dofs()
static void oomph::RefineablePolarNavierStokesEquations::unpin_all_pressure_dofs (const Vector< GeneralisedElement * > & element_pt) inline static
Unpin all pressure dofs in elements listed in vector.
     {
       // Loop over all elements to brutally unpin all nodal pressure degrees of
       // freedom and internal pressure degrees of freedom
       unsigned n_element = element_pt.size();
       for (unsigned e = 0; e < n_element; e++)
       {
         dynamic_cast<RefineablePolarNavierStokesEquations*>(element_pt[e])
           ->unpin_elemental_pressure_dofs();
       }
     }
References e(), and unpin_elemental_pressure_dofs().
unpin_elemental_pressure_dofs()
virtual void oomph::RefineablePolarNavierStokesEquations::unpin_elemental_pressure_dofs () protected pure virtual
Unpin all pressure dofs in the element.
Implemented in oomph::RefineablePolarCrouzeixRaviartElement, and oomph::RefineablePolarTaylorHoodElement.
Referenced by unpin_all_pressure_dofs().
The documentation for this class was generated from the following files:
refineable_polar_navier_stokes_elements.h
refineable_polar_navier_stokes_elements.cc