MercuryDPM: oomph::FiniteElement Class Reference
oomph::FiniteElement Class Reference abstract
#include <elements.h>
Public Types
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Public Member Functions
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
virtual void disable_ALE ()
virtual void enable_ALE ()
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual unsigned nvertex_node () const
virtual Node * vertex_node_pt (const unsigned &j) const
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (std::ostream &outfile)
virtual void output (std::ostream &outfile, const unsigned &n_plot)
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output (FILE *file_pt)
virtual void output (FILE *file_pt, const unsigned &n_plot)
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output an exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output a time-dependent exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Static Public Attributes
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Protected Member Functions
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
virtual void fill_in_contribution_to_residuals (Vector< double > &residuals)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Attributes
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Static Protected Attributes
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Private Attributes
Integral * Integral_pt
Pointer to the spatial integration scheme.
Node ** Node_pt
Storage for pointers to the nodes in the element.
int ** Nodal_local_eqn
unsigned Nnode
Number of nodes in the element.
unsigned Elemental_dimension
unsigned Nodal_dimension
unsigned Nnodal_position_type
Detailed Description
A general Finite Element class.
The main components of a FiniteElement are:
pointers to its Nodes
pointers to its internal Data (inherited from GeneralisedElement)
pointers to its external Data (inherited from GeneralisedElement)
a pointer to a spatial integration scheme
a pointer to the global Time object (inherited from GeneralisedElement)
a lookup table which establishes the relation between local and global equation numbers (inherited from GeneralisedElement)
We also provide interfaces for functions that compute the element's Jacobian matrix and/or the Vector of residuals (inherited from GeneralisedElement) plus various output routines.
Member Typedef Documentation
SteadyExactSolutionFctPt
typedef void(* oomph::FiniteElement::SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
Function pointer for function that computes vector-valued steady "exact solution" \({\bf f}({\bf x}) \) as \(\mbox{\tt fct}({\bf x}, {\bf f}) \).
UnsteadyExactSolutionFctPt
typedef void(* oomph::FiniteElement::UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Function pointer for function that computes Vector-valued time-dependent function \({\bf f}(t,{\bf x}) \) as \(\mbox{\tt fct}(t, {\bf x}, {\bf f}) \).
Constructor & Destructor Documentation
FiniteElement() [1/2]
oomph::FiniteElement::FiniteElement () inline
Constructor.
       : GeneralisedElement(),
         Integral_pt(0),
         Node_pt(0),
         Nodal_local_eqn(0),
         Nnode(0),
         Elemental_dimension(0),
         Nodal_dimension(0),
         Nnodal_position_type(1),
         Macro_elem_pt(0)
     {
     }
~FiniteElement()
FiniteElement::~FiniteElement () virtual
The destructor cleans up the static memory allocated for shape function storage. Internal and external data get wiped by the GeneralisedElement destructor; nodes get killed in mesh destructor.
The destructor cleans up the memory allocated for storage of pointers to nodes. Internal and external data get wiped by the GeneralisedElement destructor; nodes get killed in mesh destructor.
   {
     // Delete the storage allocated for the pointers to the loca nodes
     delete[] Node_pt;
     // Delete the storage allocated for the nodal numbering schemes
     if (Nodal_local_eqn)
     {
       delete[] Nodal_local_eqn[0];
       delete[] Nodal_local_eqn;
     }
   }
References Nodal_local_eqn, and Node_pt.
FiniteElement() [2/2]
oomph::FiniteElement::FiniteElement (const FiniteElement &) delete
Broken copy constructor.
Member Function Documentation
assemble_eulerian_base_vectors()
void FiniteElement::assemble_eulerian_base_vectors (const DShape & dpsids, DenseMatrix< double > & interpolated_G) const protected virtual
Assemble the covariant Eulerian base vectors, assuming that the derivatives of the shape functions with respect to the local coordinates have already been constructed.
Assemble the covariant Eulerian base vectors and return them in the matrix interpolated_G. The derivatives of the shape functions with respect to the local coordinate should already have been calculated before calling this function
Reimplemented in oomph::RefineableElement.
   {
     // Find the number of nodes and position types
     const unsigned n_node = nnode();
     const unsigned n_position_type = nnodal_position_type();
     // Find the dimension of the node and element
     const unsigned n_dim_node = nodal_dimension();
     const unsigned n_dim_element = dim();
     // Loop over the dimensions and compute the entries of the
     // base vector matrix
     for (unsigned i = 0; i < n_dim_element; i++)
     {
       for (unsigned j = 0; j < n_dim_node; j++)
       {
         // Initialise the j-th component of the i-th base vector to zero
         interpolated_G(i, j) = 0.0;
         for (unsigned l = 0; l < n_node; l++)
         {
           for (unsigned k = 0; k < n_position_type; k++)
           {
             interpolated_G(i, j) +=
               raw_nodal_position_gen(l, k, j) * dpsids(l, k, i);
           }
         }
       }
     }
   }
References dim(), i, j, k, nnodal_position_type(), nnode(), nodal_dimension(), and raw_nodal_position_gen().
Referenced by J_eulerian(), and J_eulerian_at_knot().
assemble_local_to_eulerian_jacobian()
void FiniteElement::assemble_local_to_eulerian_jacobian (const DShape & dpsids, DenseMatrix< double > & jacobian) const protected virtual
Assemble the jacobian matrix for the mapping from local to Eulerian coordinates, given the derivatives of the shape function w.r.t the local coordinates.
Internal function that is used to assemble the jacobian of the mapping from local coordinates (s) to the eulerian coordinates (x), given the derivatives of the shape functions. The entire jacobian matrix is constructed and this function will only work if there are the same number of local coordinates as global coordinates (i.e. for "bulk" elements).
Reimplemented in oomph::RefineableElement.
   {
     // Locally cache the elemental dimension
     const unsigned el_dim = dim();
     // The number of shape functions must be equal to the number
     // of nodes (by definition)
     const unsigned n_shape = nnode();
     // The number of shape function types must be equal to the number
     // of nodal position types (by definition)
     const unsigned n_shape_type = nnodal_position_type();
 #ifdef PARANOID
     // Check for dimensional compatibility
     if (Elemental_dimension != Nodal_dimension)
     {
       std::ostringstream error_message;
       error_message << "Dimension mismatch" << std::endl;
       error_message << "The elemental dimension: " << Elemental_dimension
                     << " must equal the nodal dimension: " << Nodal_dimension
                     << " for the jacobian of the mapping to be well-defined"
                     << std::endl;
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Loop over the rows of the jacobian
     for (unsigned i = 0; i < el_dim; i++)
     {
       // Loop over the columns of the jacobian
       for (unsigned j = 0; j < el_dim; j++)
       {
         // Zero the entry
         jacobian(i, j) = 0.0;
         // Loop over the shape functions
         for (unsigned l = 0; l < n_shape; l++)
         {
           for (unsigned k = 0; k < n_shape_type; k++)
           {
             // Jacobian is dx_j/ds_i, which is represented by the sum
             // over the dpsi/ds_i of the nodal points X j
             // Call the Non-hanging version of positions
             // This is overloaded in refineable elements
             jacobian(i, j) += raw_nodal_position_gen(l, k, j) * dpsids(l, k, i);
           }
         }
       }
     }
   }
References dim(), el_dim, Elemental_dimension, i, j, k, nnodal_position_type(), nnode(), Nodal_dimension, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and raw_nodal_position_gen().
Referenced by local_to_eulerian_mapping().
assemble_local_to_eulerian_jacobian2()
void FiniteElement::assemble_local_to_eulerian_jacobian2 (const DShape & d2psids, DenseMatrix< double > & jacobian2) const protected virtual
Assemble the the "jacobian" matrix of second derivatives of the mapping from local to Eulerian coordinates, given the second derivatives of the shape functions w.r.t. local coordinates.
Internal function that is used to assemble the jacobian of second derivatives of the mapping from local coordinates (s) to the eulerian coordinates (x), given the second derivatives of the shape functions.
Reimplemented in oomph::RefineableElement.
   {
     // Find the dimension of the element
     const unsigned el_dim = dim();
     // Find the number of shape functions and shape functions types
     // Must be equal to the number of nodes and their position types
     // by the definition of the shape function.
     const unsigned n_shape = nnode();
     const unsigned n_shape_type = nnodal_position_type();
     // Find the number of second derivatives
     const unsigned n_row = N2deriv[el_dim];
     // Assemble the "jacobian" (d^2 x_j/ds_i^2) for second derivatives of
     // shape functions
     // Loop over the rows (number of second derivatives)
     for (unsigned i = 0; i < n_row; i++)
     {
       // Loop over the columns (element dimension
       for (unsigned j = 0; j < el_dim; j++)
       {
         // Zero the entry
         jacobian2(i, j) = 0.0;
         // Loop over the shape functions
         for (unsigned l = 0; l < n_shape; l++)
         {
           // Loop over the shape function types
           for (unsigned k = 0; k < n_shape_type; k++)
           {
             // Add the terms to the jacobian entry
             // Call the Non-hanging version of positions
             // This is overloaded in refineable elements
             jacobian2(i, j) +=
               raw_nodal_position_gen(l, k, j) * d2psids(l, k, i);
           }
         }
       }
     }
   }
References dim(), el_dim, i, j, k, N2deriv, nnodal_position_type(), nnode(), and raw_nodal_position_gen().
Referenced by d2shape_eulerian(), and d2shape_eulerian_at_knot().
assign_all_generic_local_eqn_numbers()
virtual void oomph::FiniteElement::assign_all_generic_local_eqn_numbers (const bool & store_local_dof_pt) inline virtual
Overloaded version of the calculation of the local equation numbers. If the boolean argument is true then pointers to the degrees of freedom associated with each equation number are stored locally in the array Dof_pt.
Reimplemented from oomph::GeneralisedElement.
Reimplemented in oomph::RefineableQSpectralPoissonElement< DIM, NNODE_1D >, oomph::SpectralElement, oomph::FaceElementAsGeomObject< ELEMENT >, oomph::SolidFiniteElement, oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >, oomph::ElementWithSpecificMovingNodes< ELEMENT, SpineNode >, oomph::ElementWithSpecificMovingNodes< ELEMENT, PerturbedSpineNode >, oomph::ElementWithSpecificMovingNodes< ELEMENT, AlgebraicNode >, oomph::ElementWithSpecificMovingNodes< ELEMENT, MacroElementNodeUpdateNode >, and oomph::ElementWithMovingNodes.
     {
       // GeneralisedElement's version assigns internal and external data
       GeneralisedElement::assign_all_generic_local_eqn_numbers(
         store_local_dof_pt);
       // Need simply to add the nodal numbering scheme
       assign_nodal_local_eqn_numbers(store_local_dof_pt);
     }
References oomph::GeneralisedElement::assign_all_generic_local_eqn_numbers(), and assign_nodal_local_eqn_numbers().
Referenced by oomph::SolidFiniteElement::assign_all_generic_local_eqn_numbers(), oomph::FaceElementAsGeomObject< ELEMENT >::assign_all_generic_local_eqn_numbers(), oomph::SpectralElement::assign_all_generic_local_eqn_numbers(), and oomph::RefineableQSpectralPoissonElement< DIM, NNODE_1D >::assign_all_generic_local_eqn_numbers().
assign_nodal_local_eqn_numbers()
void FiniteElement::assign_nodal_local_eqn_numbers (const bool & store_local_dof_pt) virtual
Assign the local equation numbers for Data stored at the nodes Virtual so that it can be overloaded by RefineableFiniteElements. If the boolean is true then the pointers to the degrees of freedom associated with each equation number are stored in Dof_pt
This function loops over the nodal data of the element, adds the GLOBAL equation numbers to the local-to-global look-up scheme and fills in the Nodal_local_eqn look-up scheme for the local equation numbers If the boolean argument is true then pointers to the dofs will be stored in Dof_pt
Reimplemented in oomph::RefineableElement.
   {
     // Find the number of nodes
     const unsigned n_node = nnode();
     // If there are nodes
     if (n_node > 0)
     {
       // Find the number of local equations assigned so far
       unsigned local_eqn_number = ndof();
       // We need to find the total number of values stored at the node
       // Initialise to the number of values stored at the first node
       unsigned n_total_values = node_pt(0)->nvalue();
       // Loop over the other nodes and add the values stored
       for (unsigned n = 1; n < n_node; n++)
       {
         n_total_values += node_pt(n)->nvalue();
       }
       // If allocated delete the old storage
       if (Nodal_local_eqn)
       {
         delete[] Nodal_local_eqn[0];
         delete[] Nodal_local_eqn;
       }
       // If there are no values, we are done, null out the storage and
       // return
       if (n_total_values == 0)
       {
         Nodal_local_eqn = 0;
         return;
       }
       // Resize the storage for the nodal local equation numbers
       // Firstly allocate pointers to rows for each node
       Nodal_local_eqn = new int*[n_node];
       // Now allocate storage for the equation numbers
       Nodal_local_eqn[0] = new int[n_total_values];
       // initially all local equations are unclassified
       for (unsigned i = 0; i < n_total_values; i++)
       {
         Nodal_local_eqn[0][i] = Data::Is_unclassified;
       }
       // Loop over the remaining rows and set their pointers
       for (unsigned n = 1; n < n_node; ++n)
       {
         // Initially set the pointer to the i-th row to the pointer
         // to the i-1th row
         Nodal_local_eqn[n] = Nodal_local_eqn[n - 1];
         // Now increase the row pointer by the number of values
         // stored at the i-1th node
         Nodal_local_eqn[n] += Node_pt[n - 1]->nvalue();
       }
       // A local queue to store the global equation numbers
       std::deque<unsigned long> global_eqn_number_queue;
       // Now loop over the nodes again and assign local equation numbers
       for (unsigned n = 0; n < n_node; n++)
       {
         // Pointer to node
         Node* const nod_pt = node_pt(n);
         // Find the number of values stored at the node
         unsigned n_value = nod_pt->nvalue();
         // Loop over the number of values
         for (unsigned j = 0; j < n_value; j++)
         {
           // Get the GLOBAL equation number
           long eqn_number = nod_pt->eqn_number(j);
           // If the GLOBAL equation number is positive (a free variable)
           if (eqn_number >= 0)
           {
             // Add the GLOBAL equation number to the queue
             global_eqn_number_queue.push_back(eqn_number);
             // Add pointer to the dof to the queue if required
             if (store_local_dof_pt)
             {
               GeneralisedElement::Dof_pt_deque.push_back(nod_pt->value_pt(j));
             }
             // Add the local equation number to the local scheme
             Nodal_local_eqn[n][j] = local_eqn_number;
             // Increase the local number
             local_eqn_number++;
           }
           else
           {
             // Set the local scheme to be pinned
             Nodal_local_eqn[n][j] = Data::Is_pinned;
           }
         }
       }
       // Now add our global equations numbers to the internal element storage
       add_global_eqn_numbers(global_eqn_number_queue,
                              GeneralisedElement::Dof_pt_deque);
       // Clear the memory used in the deque
       if (store_local_dof_pt)
       {
         std::deque<double*>().swap(GeneralisedElement::Dof_pt_deque);
       }
     }
   }
References oomph::GeneralisedElement::add_global_eqn_numbers(), oomph::GeneralisedElement::Dof_pt_deque, oomph::Data::eqn_number(), oomph::GeneralisedElement::eqn_number(), i, oomph::Data::Is_pinned, oomph::Data::Is_unclassified, j, oomph::GeneralisedElement::local_eqn_number(), n, oomph::GeneralisedElement::ndof(), nnode(), Nodal_local_eqn, Node_pt, node_pt(), oomph::Data::nvalue(), and oomph::Data::value_pt().
Referenced by assign_all_generic_local_eqn_numbers(), and oomph::RefineableElement::assign_nodal_local_eqn_numbers().
build_face_element()
void FiniteElement::build_face_element (const int & face_index, FaceElement * face_element_pt) virtual
Function for building a lower dimensional FaceElement on the specified face of the FiniteElement. The arguments are the index of the face, an integer whose value depends on the particular element type, and a pointer to the FaceElement.
Reimplemented in oomph::SolidTElement< 3, NNODE_1D >, oomph::SolidTElement< 2, NNODE_1D >, oomph::SolidTElement< 1, NNODE_1D >, oomph::TElement< 3, NNODE_1D >, oomph::TElement< 2, NNODE_1D >, oomph::TElement< 1, NNODE_1D >, oomph::QSpectralElement< 3, NNODE_1D >, oomph::QSpectralElement< 2, NNODE_1D >, oomph::QSpectralElement< 1, NNODE_1D >, oomph::SolidQElement< 3, NNODE_1D >, oomph::SolidQElement< 2, NNODE_1D >, oomph::SolidQElement< 1, NNODE_1D >, oomph::SolidQHermiteElement< DIM >, oomph::SolidQHermiteElement< 1 >, oomph::SolidQHermiteElement< 2 >, oomph::QHermiteElement< DIM >, oomph::QHermiteElement< DIM - 1 >, oomph::QHermiteElement< DIM >, oomph::QHermiteElement< DIM - 1 >, oomph::QHermiteElement< DIM >, and oomph::QHermiteElement< DIM - 1 >.
   {
     // Set the nodal dimension
     face_element_pt->set_nodal_dimension(nodal_dimension());
     // Set the pointer to the orginal "bulk" element
     face_element_pt->bulk_element_pt() = this;
 #ifdef OOMPH_HAS_MPI
     // Pass on non-halo proc ID
     face_element_pt->set_halo(Non_halo_proc_ID);
 #endif
     // Set the face index
     face_element_pt->face_index() = face_index;
     // Get number of bulk nodes on a face of this element
     const unsigned nnode_face = nnode_on_face();
     // Set the function pointer for face coordinate to bulk coordinate
     // mapping
     face_element_pt->face_to_bulk_coordinate_fct_pt() =
       face_to_bulk_coordinate_fct_pt(face_index);
     // Set the function pointer for the derivative of the face coordinate to
     // bulk coordinate mapping
     face_element_pt->bulk_coordinate_derivatives_fct_pt() =
       bulk_coordinate_derivatives_fct_pt(face_index);
     // Resize storage for the number of values originally stored each of the
     // face element's nodes.
     face_element_pt->nbulk_value_resize(nnode_face);
     // Resize storage for the bulk node numbers corresponding to the face
     // element's nodes.
     face_element_pt->bulk_node_number_resize(nnode_face);
     // Copy bulk_node_numbers and nbulk_values
     for (unsigned i = 0; i < nnode_face; i++)
     {
       // Find the corresponding bulk node's number
       unsigned bulk_number = get_bulk_node_number(face_index, i);
       // Assign the pointer and number into the face element
       face_element_pt->node_pt(i) = node_pt(bulk_number);
       face_element_pt->bulk_node_number(i) = bulk_number;
       // Set the number of values originally stored at this node
       face_element_pt->nbulk_value(i) = required_nvalue(bulk_number);
     }
     // Set the outer unit normal sign
     face_element_pt->normal_sign() = face_outer_unit_normal_sign(face_index);
   }
References oomph::FaceElement::bulk_coordinate_derivatives_fct_pt(), bulk_coordinate_derivatives_fct_pt(), oomph::FaceElement::bulk_element_pt(), oomph::FaceElement::bulk_node_number(), oomph::FaceElement::bulk_node_number_resize(), oomph::FaceElement::face_index(), face_outer_unit_normal_sign(), oomph::FaceElement::face_to_bulk_coordinate_fct_pt(), face_to_bulk_coordinate_fct_pt(), get_bulk_node_number(), i, oomph::FaceElement::nbulk_value(), oomph::FaceElement::nbulk_value_resize(), nnode_on_face(), nodal_dimension(), node_pt(), oomph::FaceElement::normal_sign(), required_nvalue(), and set_nodal_dimension().
Referenced by oomph::AdvectionDiffusionFluxElement< ELEMENT >::AdvectionDiffusionFluxElement(), oomph::AxisymmetricLinearElasticityTractionElement< ELEMENT >::AxisymmetricLinearElasticityTractionElement(), oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::AxisymmetricNavierStokesTractionElement(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::AxisymmetricPoroelasticityTractionElement(), oomph::AxisymmetricSolidTractionElement< ELEMENT >::AxisymmetricSolidTractionElement(), oomph::BiharmonicFluxElement< DIM >::BiharmonicFluxElement(), oomph::ClampedHermiteShellBoundaryConditionElement::ClampedHermiteShellBoundaryConditionElement(), oomph::ClampedSlidingHermiteBeamBoundaryConditionElement::ClampedSlidingHermiteBeamBoundaryConditionElement(), oomph::DarcyFaceElement< ELEMENT >::DarcyFaceElement(), oomph::DGEulerFaceElement< ELEMENT >::DGEulerFaceElement(), oomph::DGEulerFaceReflectionElement< ELEMENT >::DGEulerFaceReflectionElement(), oomph::DGScalarAdvectionFaceElement< ELEMENT >::DGScalarAdvectionFaceElement(), DragNusseltCalculationElement< ELEMENT >::DragNusseltCalculationElement(), oomph::DummyFaceElement< ELEMENT >::DummyFaceElement(), oomph::ElasticAxisymmetricVolumeConstraintBoundingElement< ELEMENT >::ElasticAxisymmetricVolumeConstraintBoundingElement(), oomph::ElasticLineVolumeConstraintBoundingElement< ELEMENT >::ElasticLineVolumeConstraintBoundingElement(), oomph::ElasticSurfaceVolumeConstraintBoundingElement< ELEMENT >::ElasticSurfaceVolumeConstraintBoundingElement(), oomph::ElasticUpdateFluidInterfaceElement< EQUATION_CLASS, DERIVATIVE_CLASS, ELEMENT >::ElasticUpdateFluidInterfaceElement(), oomph::FaceElementAsGeomObject< ELEMENT >::FaceElementAsGeomObject(), oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >::FourierDecomposedHelmholtzBCElementBase(), oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::FourierDecomposedHelmholtzFluxElement(), oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement(), oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement(), oomph::FpPressureAdvDiffRobinBCElement< ELEMENT >::FpPressureAdvDiffRobinBCElement(), oomph::FpPressureAdvDiffRobinBCMixedOrderSpaceTimeElement< ELEMENT >::FpPressureAdvDiffRobinBCMixedOrderSpaceTimeElement(), oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >::FpPressureAdvDiffRobinBCSpaceTimeElement(), oomph::FSIAxisymmetricLinearElasticityTractionElement< ELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >::FSIAxisymmetricLinearElasticityTractionElement(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::FSIImposeDisplacementByLagrangeMultiplierElement(), oomph::HeatedPenetratorFluxElement< ELEMENT >::HeatedPenetratorFluxElement(), oomph::HelmholtzBCElementBase< ELEMENT >::HelmholtzBCElementBase(), oomph::HelmholtzFluxElement< ELEMENT >::HelmholtzFluxElement(), oomph::HelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::HelmholtzFluxFromNormalDisplacementBCElement(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::ImposeDisplacementByLagrangeMultiplierElement(), oomph::ImposeImpenetrabilityElement< ELEMENT >::ImposeImpenetrabilityElement(), oomph::ImposeParallelOutflowElement< ELEMENT >::ImposeParallelOutflowElement(), oomph::LinearElasticityTractionElement< ELEMENT >::LinearElasticityTractionElement(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::LinearisedAxisymPoroelasticBJS_FSIElement(), oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::LinearisedFSIAxisymmetricNStNoSlipBCElementElement(), oomph::LinearWaveFluxElement< ELEMENT >::LinearWaveFluxElement(), oomph::SpineUpdateFluidInterfaceElement< EQUATION_CLASS, DERIVATIVE_CLASS, ELEMENT >::make_bounding_element(), oomph::NavierStokesFluxControlElement< ELEMENT >::NavierStokesFluxControlElement(), oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::NavierStokesImpedanceTractionElement(), oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::NavierStokesMixedOrderSpaceTimeTractionElement(), oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::NavierStokesSpaceTimeTractionElement(), oomph::NavierStokesSurfaceDragTorqueElement< ELEMENT >::NavierStokesSurfaceDragTorqueElement(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::NavierStokesSurfacePowerElement(), oomph::NavierStokesTractionElement< ELEMENT >::NavierStokesTractionElement(), oomph::PerturbedSpineLinearisedAxisymmetricFluidInterfaceElement< ELEMENT >::PerturbedSpineLinearisedAxisymmetricFluidInterfaceElement(), oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::PMLFourierDecomposedHelmholtzFluxElement(), oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::PMLFourierDecomposedHelmholtzPowerMonitorElement(), oomph::PMLHelmholtzFluxElement< ELEMENT >::PMLHelmholtzFluxElement(), oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::PMLHelmholtzFluxFromNormalDisplacementBCElement(), oomph::PMLHelmholtzPowerElement< ELEMENT >::PMLHelmholtzPowerElement(), oomph::PMLTimeHarmonicLinearElasticityTractionElement< ELEMENT >::PMLTimeHarmonicLinearElasticityTractionElement(), oomph::PoissonFluxElement< ELEMENT >::PoissonFluxElement(), oomph::PolarNavierStokesTractionElement< ELEMENT >::PolarNavierStokesTractionElement(), oomph::PolarStreamfunctionTractionElement< ELEMENT >::PolarStreamfunctionTractionElement(), oomph::PolarStressIntegralElement< ELEMENT >::PolarStressIntegralElement(), oomph::PoroelasticityFaceElement< ELEMENT >::PoroelasticityFaceElement(), oomph::SolidTractionElement< ELEMENT >::SolidTractionElement(), oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::SphericalAdvectionDiffusionFluxElement(), oomph::SpineAxisymmetricVolumeConstraintBoundingElement< ELEMENT >::SpineAxisymmetricVolumeConstraintBoundingElement(), SpineGravityTractionElement< ELEMENT >::SpineGravityTractionElement(), oomph::SpineLineVolumeConstraintBoundingElement< ELEMENT >::SpineLineVolumeConstraintBoundingElement(), oomph::SpineSurfaceVolumeConstraintBoundingElement< ELEMENT >::SpineSurfaceVolumeConstraintBoundingElement(), oomph::SpineUpdateFluidInterfaceElement< EQUATION_CLASS, DERIVATIVE_CLASS, ELEMENT >::SpineUpdateFluidInterfaceElement(), oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::SteadyAxisymAdvectionDiffusionFluxElement(), oomph::SurfaceContactElementBase< ELEMENT >::SurfaceContactElementBase(), oomph::TimeHarmonicFourierDecomposedLinearElasticityTractionElement< ELEMENT >::TimeHarmonicFourierDecomposedLinearElasticityTractionElement(), oomph::TimeHarmonicLinearElasticityTractionElement< ELEMENT >::TimeHarmonicLinearElasticityTractionElement(), oomph::TimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::TimeHarmonicLinElastLoadedByHelmholtzPressureBCElement(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement(), TorqueCalculationElement< ELEMENT >::TorqueCalculationElement(), oomph::UnsteadyHeatBaseFaceElement< ELEMENT >::UnsteadyHeatBaseFaceElement(), oomph::UnsteadyHeatFluxElement< ELEMENT >::UnsteadyHeatFluxElement(), oomph::UnsteadyHeatFluxPseudoMeltElement< ELEMENT >::UnsteadyHeatFluxPseudoMeltElement(), and oomph::YoungLaplaceContactAngleElement< ELEMENT >::YoungLaplaceContactAngleElement().
bulk_coordinate_derivatives_fct_pt()
virtual BulkCoordinateDerivativesFctPt oomph::FiniteElement::bulk_coordinate_derivatives_fct_pt (const int & face_index) const inline virtual
Get a pointer to the derivative of the mapping from face to bulk coordinates.
Reimplemented in oomph::QElement< 3, NNODE_1D >, oomph::QElement< 2, NNODE_1D >, and oomph::QElement< 1, NNODE_1D >.
     {
       std::string err = "Not implemented for this element.";
       throw OomphLibError(
         err, OOMPH_EXCEPTION_LOCATION, OOMPH_CURRENT_FUNCTION);
     }
References OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
Referenced by build_face_element().
check_J_eulerian_at_knots()
void FiniteElement::check_J_eulerian_at_knots (bool & passed) const
Check that Jacobian of mapping between local and Eulerian coordinates at all integration points is positive.
   {
     // Bypass check deep down in the guts...
     bool backup = FiniteElement::Accept_negative_jacobian;
     FiniteElement::Accept_negative_jacobian = true;
     // Let's be optimistic...
     passed = true;
     // Find the number of nodes
     const unsigned n_node = nnode();
     // Find the number of position types
     const unsigned n_position_type = nnodal_position_type();
     // DRAIG: Unused variable
     // const unsigned n_dim_node = nodal_dimension();
     // Find the dimension of the node and element
     const unsigned n_dim_element = dim();
     // Set up dummy memory for the shape functions
     Shape psi(n_node, n_position_type);
     DShape dpsi(n_node, n_dim_element);
     unsigned nintpt = integral_pt()->nweight();
     for (unsigned ipt = 0; ipt < nintpt; ipt++)
     {
       double jac = dshape_eulerian_at_knot(ipt, psi, dpsi);
       // Are we dead yet?
       if (jac <= 0.0)
       {
         passed = false;
         // Reset
         FiniteElement::Accept_negative_jacobian = backup;
         return;
       }
     }
     // Reset
     FiniteElement::Accept_negative_jacobian = backup;
   }
References Accept_negative_jacobian, dim(), dshape_eulerian_at_knot(), integral_pt(), nnodal_position_type(), nnode(), and oomph::Integral::nweight().
Referenced by oomph::TetMeshBase::snap_nodes_onto_geometric_objects(), and oomph::WomersleyMesh< WOMERSLEY_ELEMENT >::WomersleyMesh().
check_jacobian()
void FiniteElement::check_jacobian (const double & jacobian) const
Helper function used to check for singular or negative Jacobians in the transform from local to global or Lagrangian coordinates.
Internal function used to check for singular or negative values of the determinant of the Jacobian of the mapping between local and global or lagrangian coordinates. Negative jacobians are allowed if the Accept_negative_jacobian flag is set to true.
   {
     // First check for a zero jacobian
     if (std::fabs(jacobian) < Tolerance_for_singular_jacobian)
     {
       if (FiniteElement::Suppress_output_while_checking_for_inverted_elements)
       {
         throw OomphLibQuietException();
       }
       else
       {
         std::ostringstream error_stream;
         error_stream
           << "Determinant of Jacobian matrix is zero --- "
           << "singular mapping!\nThe determinant of the "
           << "jacobian is " << std::fabs(jacobian)
           << " which is smaller than the treshold "
           << Tolerance_for_singular_jacobian << "\n"
           << "You can change this treshold, by specifying "
           << "FiniteElement::Tolerance_for_singular_jacobian \n"
           << "Here are the nodal coordinates of the inverted element\n"
           << "in the form \n\n       x,y[,z], hang_status\n\n"
           << "where hang_status = 1 or 2 for non-hanging or hanging\n"
           << "nodes respectively (useful for automatic sizing of\n"
           << "tecplot markers to identify the hanging nodes). \n\n";
         unsigned n_dim_nod = node_pt(0)->ndim();
         unsigned n_nod = nnode();
         unsigned hang_count = 0;
         for (unsigned j = 0; j < n_nod; j++)
         {
           for (unsigned i = 0; i < n_dim_nod; i++)
           {
             error_stream << node_pt(j)->x(i) << " ";
           }
           if (node_pt(j)->is_hanging())
           {
             error_stream << " 2";
             hang_count++;
           }
           else
           {
             error_stream << " 1";
           }
           error_stream << std::endl;
         }
         error_stream << std::endl << std::endl;
         if ((Macro_elem_pt != 0) && (0 != hang_count))
         {
           error_stream
             << "NOTE:  Offending element is associated with a MacroElement\n"
             << "       AND the element has hanging nodes! \n"
             << "       If an element is thin and highly curved, the \n"
             << "       constraints imposed by\n \n"
             << "       (1) inter-element continuity (imposed by the hanging\n"
             << "           node constraints) and \n\n"
             << "       (2) the need to respect curvilinear domain boundaries\n"
             << "           during mesh refinement (imposed by the element's\n"
             << "           macro element mapping)\n\n"
             << "       may be irreconcilable!  \n \n"
             << "       You may have to re-design your base mesh to avoid \n"
             << "       the creation of thin, highly curved elements during\n"
             << "       the refinement process.\n"
             << std::endl;
         }
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
     }
     // Now check for negative jacobians, if we're not allowing them (default)
     if ((Accept_negative_jacobian == false) && (jacobian < 0.0))
     {
       if (FiniteElement::Suppress_output_while_checking_for_inverted_elements)
       {
         throw OomphLibQuietException();
       }
       else
       {
         std::ostringstream error_stream;
         error_stream << "Negative Jacobian in transform from "
                      << "local to global coordinates" << std::endl
                      << "       You have an inverted coordinate system!"
                      << std::endl
                      << std::endl;
         error_stream
           << "Here are the nodal coordinates of the inverted element\n"
           << "in the form \n\n       x,y[,z], hang_status\n\n"
           << "where hang_status = 1 or 2 for non-hanging or hanging\n"
           << "nodes respectively (useful for automatic sizing of\n"
           << "tecplot markers to identify the hanging nodes). \n\n";
         unsigned n_dim_nod = node_pt(0)->ndim();
         unsigned n_nod = nnode();
         unsigned hang_count = 0;
         for (unsigned j = 0; j < n_nod; j++)
         {
           for (unsigned i = 0; i < n_dim_nod; i++)
           {
             error_stream << node_pt(j)->x(i) << " ";
           }
           if (node_pt(j)->is_hanging())
           {
             error_stream << " 2";
             hang_count++;
           }
           else
           {
             error_stream << " 1";
           }
           error_stream << std::endl;
         }
         error_stream << std::endl << std::endl;
         if ((Macro_elem_pt != 0) && (0 != hang_count))
         {
           error_stream
             << "NOTE: The inverted element is associated with a MacroElement\n"
             << "       AND the element has hanging nodes! \n"
             << "       If an element is thin and highly curved, the \n"
             << "       constraints imposed by\n \n"
             << "       (1) inter-element continuity (imposed by the hanging\n"
             << "           node constraints) and \n\n"
             << "       (2) the need to respect curvilinear domain boundaries\n"
             << "           during mesh refinement (imposed by the element's\n"
             << "           macro element mapping)\n\n"
             << "       may be irreconcilable!  \n \n"
             << "       You may have to re-design your base mesh to avoid \n"
             << "       the creation of thin, highly curved elements during\n"
             << "       the refinement process.\n"
             << std::endl;
         }
         error_stream
           << std::endl
           << std::endl
           << "If you believe that inverted elements do not cause any\n"
           << "problems in your specific application you can \n "
           << "suppress this test by: " << std::endl
           << "  i) setting the (static) flag "
           << "FiniteElement::Accept_negative_jacobian to be true" << std::endl;
         error_stream << " ii) switching OFF the PARANOID flag" << std::endl
                      << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
     }
   }
References Accept_negative_jacobian, boost::multiprecision::fabs(), i, j, Macro_elem_pt, oomph::Node::ndim(), nnode(), node_pt(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, Suppress_output_while_checking_for_inverted_elements, Tolerance_for_singular_jacobian, and oomph::Node::x().
Referenced by oomph::Mesh::check_inverted_elements(), invert_jacobian(), local_to_eulerian_mapping_diagonal(), oomph::RefineableElement::local_to_eulerian_mapping_diagonal(), oomph::SolidFiniteElement::local_to_lagrangian_mapping_diagonal(), and oomph::RefineableSolidElement::local_to_lagrangian_mapping_diagonal().
compute_abs_error()
virtual void oomph::FiniteElement::compute_abs_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error) inline virtual
Plot the error when compared against a given exact solution \({\bf f}({\bf x}) \). Also calculates the maximum absolute error
     {
       std::string error_message =
         "compute_abs_error undefined for this element \n";
       outfile << error_message;
       throw OomphLibError(
         error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
compute_error() [1/8]
virtual void oomph::FiniteElement::compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) inline virtual
Calculate the norm of the error and that of the exact solution.
Reimplemented in oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::NavierStokesEquations< DIM >, and oomph::NavierStokesEquations< 2 >.
     {
       std::string error_message = "compute_error undefined for this element \n";
       throw OomphLibError(
         error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
Referenced by RefineableBuoyantQCrouzeixRaviartElement< DIM >::compute_error(), RefineableQCrouzeixRaviartElementWithExternalElement< DIM >::compute_error(), RefineableQAdvectionDiffusionElementWithExternalElement< DIM >::compute_error(), QThermalPVDElement< DIM >::compute_error(), oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::compute_error(), oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::compute_error(), oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::compute_error(), oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement::compute_error(), oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >::compute_error(), oomph::BiharmonicEquations< DIM >::compute_error(), oomph::Mesh::compute_error(), oomph::BuoyantQCrouzeixRaviartElement< DIM >::compute_error(), and oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::compute_error().
compute_error() [2/8]
virtual void oomph::FiniteElement::compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > & error, Vector< double > & norm) inline virtual
Given the exact solution \({\bf f}({\bf x}) \) this function calculates the norm of the error and that of the exact solution. Version with vectors of norms and errors so that different variables' norms and errors can be returned individually
     {
       std::string error_message = "compute_error undefined for this element \n";
       throw OomphLibError(
         error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
compute_error() [3/8]
virtual void oomph::FiniteElement::compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) inline virtual
Calculate the norm of the error and that of the exact solution.
Reimplemented in oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::NavierStokesEquations< DIM >, and oomph::NavierStokesEquations< 2 >.
     {
       std::string error_message = "time-dependent compute_error ";
       error_message += "undefined for this element \n";
       throw OomphLibError(
         error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
compute_error() [4/8]
virtual void oomph::FiniteElement::compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, Vector< double > & error, Vector< double > & norm) inline virtual
Given the exact solution \({\bf f}({\bf x}) \) this function calculates the norm of the error and that of the exact solution. Version with vectors of norms and errors so that different variables' norms and errors can be returned individually
     {
       std::string error_message = "time-dependent compute_error ";
       error_message += "undefined for this element \n";
       throw OomphLibError(
         error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
compute_error() [5/8]
virtual void oomph::FiniteElement::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) inline virtual
Plot the error when compared against a given exact solution \({\bf f}({\bf x}) \). Also calculates the norm of the error and that of the exact solution.
Reimplemented in oomph::YoungLaplaceEquations, oomph::WomersleyEquations< DIM >, oomph::UnsteadyHeatEquations< DIM >, oomph::UnsteadyHeatEquations< 2 >, oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations, oomph::SteadyAxisymAdvectionDiffusionEquations, oomph::SphericalNavierStokesEquations, oomph::SphericalAdvectionDiffusionEquations, oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< 2 >, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< 2 >, oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::PolarNavierStokesEquations, oomph::PoissonEquations< DIM >, oomph::PoissonEquations< 1 >, oomph::PoissonEquations< 2 >, oomph::PoissonEquations< 3 >, oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >, oomph::PMLHelmholtzEquations< DIM >, oomph::PMLFourierDecomposedHelmholtzEquations, oomph::NavierStokesEquations< DIM >, oomph::NavierStokesEquations< 2 >, oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >, oomph::BuoyantQCrouzeixRaviartElement< DIM >, oomph::LinearWaveEquations< DIM >, oomph::LinearElasticityEquations< DIM >, oomph::HelmholtzEquations< DIM >, oomph::GeneralisedNewtonianNavierStokesEquations< DIM >, oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations, oomph::FourierDecomposedHelmholtzEquations, oomph::FoepplvonKarmanEquations, oomph::DisplacementBasedFoepplvonKarmanEquations, oomph::BiharmonicFluidBoundaryElement, oomph::BiharmonicFluxElement< DIM >, oomph::BiharmonicElement< DIM >, oomph::BiharmonicEquations< DIM >, oomph::AxisymmetricNavierStokesEquations, oomph::AxisymmetricLinearElasticityEquations, oomph::AxisymFoepplvonKarmanEquations, oomph::AxisymFoepplvonKarmanEquations, oomph::AxisymAdvectionDiffusionEquations, oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >, oomph::GeneralisedAdvectionDiffusionEquations< DIM >, oomph::GeneralisedAdvectionDiffusionEquations< 2 >, oomph::AdvectionDiffusionEquations< DIM >, oomph::AdvectionDiffusionEquations< 2 >, oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::AxisymmetricQAdvectionCrouzeixRaviartElement, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement, oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement, oomph::MultiPoissonEquations< DIM, NFIELDS >, and oomph::TLinearHeatAndElasticityElement< DIM, NNODE_1D >.
     {
       std::string error_message = "compute_error undefined for this element \n";
       outfile << error_message;
       throw OomphLibError(
         error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
compute_error() [6/8]
virtual void oomph::FiniteElement::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > & error, Vector< double > & norm) inline virtual
Plot the error when compared against a given exact solution \({\bf f}({\bf x}) \). Also calculates the norm of the error and that of the exact solution. The version with vectors of norms and errors so that different variables' norms and errors can be returned individually
Reimplemented in oomph::PoroelasticityEquations< DIM >, oomph::PoroelasticityEquations< 2 >, oomph::DarcyEquations< DIM >, oomph::DarcyEquations< 2 >, and oomph::AxisymmetricPoroelasticityEquations.
     {
       std::string error_message = "compute_error undefined for this element \n";
       outfile << error_message;
       throw OomphLibError(error_message,
                           "FiniteElement::compute_error()",
                           OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
compute_error() [7/8]
virtual void oomph::FiniteElement::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) inline virtual
Plot the error when compared against a given time-dependent exact solution \({\bf f}(t,{\bf x}) \). Also calculates the norm of the error and that of the exact solution.
Reimplemented in oomph::YoungLaplaceEquations, oomph::WomersleyEquations< DIM >, oomph::UnsteadyHeatEquations< DIM >, oomph::UnsteadyHeatEquations< 2 >, oomph::SphericalNavierStokesEquations, oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< 2 >, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< 2 >, oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::PolarNavierStokesEquations, oomph::PoissonEquations< DIM >, oomph::PoissonEquations< 1 >, oomph::PoissonEquations< 2 >, oomph::PoissonEquations< 3 >, oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >, oomph::PMLHelmholtzEquations< DIM >, oomph::PMLFourierDecomposedHelmholtzEquations, oomph::NavierStokesEquations< DIM >, oomph::NavierStokesEquations< 2 >, oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >, oomph::BuoyantQCrouzeixRaviartElement< DIM >, oomph::LinearWaveEquations< DIM >, oomph::LinearElasticityEquations< DIM >, oomph::HelmholtzEquations< DIM >, oomph::GeneralisedNewtonianNavierStokesEquations< DIM >, oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations, oomph::FourierDecomposedHelmholtzEquations, oomph::FoepplvonKarmanEquations, oomph::DisplacementBasedFoepplvonKarmanEquations, oomph::BiharmonicElement< DIM >, oomph::BiharmonicEquations< DIM >, oomph::AxisymmetricNavierStokesEquations, oomph::AxisymmetricLinearElasticityEquations, oomph::AxisymFoepplvonKarmanEquations, oomph::AxisymFoepplvonKarmanEquations, oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >, oomph::GeneralisedAdvectionDiffusionEquations< DIM >, oomph::GeneralisedAdvectionDiffusionEquations< 2 >, oomph::AdvectionDiffusionEquations< DIM >, oomph::AdvectionDiffusionEquations< 2 >, oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::AxisymmetricQAdvectionCrouzeixRaviartElement, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement, oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement, oomph::MultiPoissonEquations< DIM, NFIELDS >, and oomph::TLinearHeatAndElasticityElement< DIM, NNODE_1D >.
     {
       std::string error_message =
         "time-dependent compute_error undefined for this element \n";
       outfile << error_message;
       throw OomphLibError(
         error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
compute_error() [8/8]
virtual void oomph::FiniteElement::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, Vector< double > & error, Vector< double > & norm) inline virtual
Plot the error when compared against a given time-dependent exact solution \({\bf f}(t,{\bf x}) \). Also calculates the norm of the error and that of the exact solution. The version with vectors of norms and errors so that different variables' norms and errors can be returned individually
Reimplemented in oomph::ScalarAdvectionEquations< DIM >, oomph::EulerEquations< DIM >, oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::PoroelasticityEquations< DIM >, oomph::PoroelasticityEquations< 2 >, and oomph::AxisymmetricPoroelasticityEquations.
     {
       std::string error_message =
         "time-dependent compute_error undefined for this element \n";
       outfile << error_message;
       throw OomphLibError(error_message,
                           "FiniteElement::compute_error()",
                           OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
compute_physical_size()
virtual double oomph::FiniteElement::compute_physical_size () const inline virtual
Broken virtual function to compute the actual size (taking into account factors such as 2pi or radii the integrand) – such function can only be implemented on an equation-by-equation basis.
Reimplemented in oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations, oomph::AxisymmetricPVDEquationsWithPressure, oomph::AxisymmetricPVDEquations, and oomph::AxisymmetricNavierStokesEquations.
     {
       throw OomphLibError(
         "compute_physical_size() isn't implemented for this element\n",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
       // Dummy return
       return 0.0;
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::MyProblem::min_element_size().
construct_boundary_node() [1/2]
virtual Node* oomph::FiniteElement::construct_boundary_node (const unsigned & n) inline virtual
Construct the local node n as a boundary node; that is a node that MAY be placed on a mesh boundary and return a pointer to the newly created node object.
Reimplemented in oomph::SolidFiniteElement, oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >, oomph::ElementWithSpecificMovingNodes< ELEMENT, SpineNode >, oomph::ElementWithSpecificMovingNodes< ELEMENT, PerturbedSpineNode >, oomph::ElementWithSpecificMovingNodes< ELEMENT, AlgebraicNode >, and oomph::ElementWithSpecificMovingNodes< ELEMENT, MacroElementNodeUpdateNode >.
     {
       // Create a node and assign it to the local node pointer
       // The dimension and number of values are taken from internal element data
       node_pt(n) = new BoundaryNode<Node>(
         Nodal_dimension, Nnodal_position_type, required_nvalue(n));
       // Now return a pointer to the node, so that the mesh can use it
       return node_pt(n);
     }
References n, Nnodal_position_type, Nodal_dimension, node_pt(), and required_nvalue().
Referenced by oomph::GmshTetMesh< ELEMENT >::build_from_scaffold(), oomph::TetgenMesh< ELEMENT >::build_from_scaffold(), oomph::TriangleMesh< ELEMENT >::build_from_scaffold(), oomph::BrickFromTetMesh< ELEMENT >::build_mesh(), oomph::ChannelWithLeafletMesh< ELEMENT >::ChannelWithLeafletMesh(), oomph::DGElement::construct_boundary_nodes_and_faces(), oomph::Mesh::convert_to_boundary_node(), oomph::GeompackQuadScaffoldMesh::GeompackQuadScaffoldMesh(), oomph::QuarterCircleSectorMesh< ELEMENT >::QuarterCircleSectorMesh(), oomph::TetMeshBase::split_elements_in_corners(), oomph::TetgenScaffoldMesh::TetgenScaffoldMesh(), and oomph::TriangleScaffoldMesh::TriangleScaffoldMesh().
construct_boundary_node() [2/2]
virtual Node* oomph::FiniteElement::construct_boundary_node (const unsigned & n, TimeStepper *const & time_stepper_pt) inline virtual
Construct the local node n, including storage for history values required by timestepper, as a boundary node; that is a node that MAY be placed on a mesh boundary and return a pointer to the newly created node object.
Reimplemented in oomph::SolidFiniteElement, oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >, oomph::ElementWithSpecificMovingNodes< ELEMENT, SpineNode >, oomph::ElementWithSpecificMovingNodes< ELEMENT, PerturbedSpineNode >, oomph::ElementWithSpecificMovingNodes< ELEMENT, AlgebraicNode >, and oomph::ElementWithSpecificMovingNodes< ELEMENT, MacroElementNodeUpdateNode >.
     {
       // Create a node and assign it to the local node pointer.
       // The dimension and number of values are taken from internal element data
       node_pt(n) = new BoundaryNode<Node>(time_stepper_pt,
                                           Nodal_dimension,
                                           Nnodal_position_type,
                                           required_nvalue(n));
       // Now return a pointer to the node, so that the mesh can find it
       return node_pt(n);
     }
References n, Nnodal_position_type, Nodal_dimension, node_pt(), required_nvalue(), and oomph::GeomObject::time_stepper_pt().
construct_node() [1/2]
virtual Node* oomph::FiniteElement::construct_node (const unsigned & n) inline virtual
Construct the local node n and return a pointer to the newly created node object.
Reimplemented in oomph::SolidFiniteElement, oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >, oomph::ElementWithSpecificMovingNodes< ELEMENT, SpineNode >, oomph::ElementWithSpecificMovingNodes< ELEMENT, PerturbedSpineNode >, oomph::ElementWithSpecificMovingNodes< ELEMENT, AlgebraicNode >, and oomph::ElementWithSpecificMovingNodes< ELEMENT, MacroElementNodeUpdateNode >.
     {
       // Create a node and assign it to the local node pointer
       // The dimension and number of values are taken from internal element data
       node_pt(n) =
         new Node(Nodal_dimension, Nnodal_position_type, required_nvalue(n));
       // Now return a pointer to the node, so that the mesh can use it
       return node_pt(n);
     }
References n, Nnodal_position_type, Nodal_dimension, node_pt(), and required_nvalue().
Referenced by oomph::GmshTetMesh< ELEMENT >::build_from_scaffold(), oomph::TetgenMesh< ELEMENT >::build_from_scaffold(), oomph::TriangleMesh< ELEMENT >::build_from_scaffold(), oomph::BrickFromTetMesh< ELEMENT >::build_mesh(), oomph::DGElement::construct_boundary_nodes_and_faces(), oomph::DGElement::construct_nodes_and_faces(), oomph::FullCircleMesh< ELEMENT >::FullCircleMesh(), oomph::GeompackQuadScaffoldMesh::GeompackQuadScaffoldMesh(), oomph::LinearElasticitySmoothMesh< LINEAR_ELASTICITY_ELEMENT >::operator()(), oomph::PoissonSmoothMesh< POISSON_ELEMENT >::operator()(), oomph::QuarterCircleSectorMesh< ELEMENT >::QuarterCircleSectorMesh(), oomph::QuarterTubeMesh< ELEMENT >::QuarterTubeMesh(), oomph::RectangleWithHoleMesh< ELEMENT >::RectangleWithHoleMesh(), oomph::SimpleRectangularTriMesh< ELEMENT >::SimpleRectangularTriMesh(), oomph::TetMeshBase::split_elements_in_corners(), oomph::TetgenScaffoldMesh::TetgenScaffoldMesh(), oomph::TriangleScaffoldMesh::TriangleScaffoldMesh(), oomph::TubeMesh< ELEMENT >::TubeMesh(), and oomph::WomersleyMesh< WOMERSLEY_ELEMENT >::WomersleyMesh().
construct_node() [2/2]
virtual Node* oomph::FiniteElement::construct_node (const unsigned & n, TimeStepper *const & time_stepper_pt) inline virtual
Construct the local node n, including storage for history values required by timestepper, and return a pointer to the newly created node object.
Reimplemented in oomph::SolidFiniteElement, oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >, oomph::ElementWithSpecificMovingNodes< ELEMENT, SpineNode >, oomph::ElementWithSpecificMovingNodes< ELEMENT, PerturbedSpineNode >, oomph::ElementWithSpecificMovingNodes< ELEMENT, AlgebraicNode >, and oomph::ElementWithSpecificMovingNodes< ELEMENT, MacroElementNodeUpdateNode >.
     {
       // Create a node and assign it to the local node pointer.
       // The dimension and number of values are taken from internal element data
       node_pt(n) = new Node(time_stepper_pt,
                             Nodal_dimension,
                             Nnodal_position_type,
                             required_nvalue(n));
       // Now return a pointer to the node, so that the mesh can find it
       return node_pt(n);
     }
References n, Nnodal_position_type, Nodal_dimension, node_pt(), required_nvalue(), and oomph::GeomObject::time_stepper_pt().
d2shape_eulerian()
double FiniteElement::d2shape_eulerian (const Vector< double > & s, Shape & psi, DShape & dpsi, DShape & d2psi) const
Compute the geometric shape functions and also first and second derivatives w.r.t. global coordinates at local coordinate s; Returns Jacobian of mapping from global to local coordinates. Numbering: 1D: d2psidx(i,0) = \(d^2 \psi_j / d x^2 \) 2D: d2psidx(i,0) = \(\partial^2 \psi_j / \partial x_0^2 \) d2psidx(i,1) = \(\partial^2 \psi_j / \partial x_1^2 \) d2psidx(i,2) = \(\partial^2 \psi_j / \partial x_0 \partial x_1 \) 3D: d2psidx(i,0) = \(\partial^2 \psi_j / \partial x_0^2 \) d2psidx(i,1) = \(\partial^2 \psi_j / \partial x_1^2 \) d2psidx(i,2) = \(\partial^2 \psi_j / \partial x_2^2 \) d2psidx(i,3) = \(\partial^2 \psi_j / \partial x_0 \partial x_1 \) d2psidx(i,4) = \(\partial^2 \psi_j / \partial x_0 \partial x_2 \) d2psidx(i,5) = \(\partial^2 \psi_j / \partial x_1 \partial x_2 \)
Compute the geometric shape functions and also first and second derivatives w.r.t. global coordinates at local coordinate s; Also returns Jacobian of mapping from global to local coordinates. Numbering: 1D: d2psidx(i,0) = \(d^2 \psi_j / d x^2 \) 2D: d2psidx(i,0) = \(\partial^2 \psi_j / \partial x_0^2 \) d2psidx(i,1) = \(\partial^2 \psi_j / \partial x_1^2 \) d2psidx(i,2) = \(\partial^2 \psi_j / \partial x_0 \partial x_1 \) 3D: d2psidx(i,0) = \(\partial^2 \psi_j / \partial x_0^2 \) d2psidx(i,1) = \(\partial^2 \psi_j / \partial x_1^2 \) d2psidx(i,2) = \(\partial^2 \psi_j / \partial x_2^2 \) d2psidx(i,3) = \(\partial^2 \psi_j / \partial x_0 \partial x_1 \) d2psidx(i,4) = \(\partial^2 \psi_j / \partial x_0 \partial x_2 \) d2psidx(i,5) = \(\partial^2 \psi_j / \partial x_1 \partial x_2 \)
   {
     // Find the values of the indices of the shape functions
     // Locally cached.
     // Find the element dimension
     const unsigned el_dim = dim();
     // Find the number of second derivatives required
     const unsigned n_deriv = N2deriv[el_dim];
     // Get the values of the shape function and local derivatives
     d2shape_local(s, psi, dpsi, d2psi);
     // Allocate memory for the jacobian and inverse jacobian
     DenseMatrix<double> jacobian(el_dim), inverse_jacobian(el_dim);
     // Calculate the jacobian and inverse jacobian
     const double det =
       local_to_eulerian_mapping(dpsi, jacobian, inverse_jacobian);
     // Allocate memory for the jacobian of second derivatives
     DenseMatrix<double> jacobian2(n_deriv, el_dim);
     // Assemble the jacobian of second derivatives
     assemble_local_to_eulerian_jacobian2(d2psi, jacobian2);
     // Now set the value of the derivatives
     transform_second_derivatives(
       jacobian, inverse_jacobian, jacobian2, dpsi, d2psi);
     // Return the determinant of the mapping
     return det;
   }
References assemble_local_to_eulerian_jacobian2(), d2shape_local(), dim(), el_dim, local_to_eulerian_mapping(), N2deriv, s, and transform_second_derivatives().
d2shape_eulerian_at_knot()
double FiniteElement::d2shape_eulerian_at_knot (const unsigned & ipt, Shape & psi, DShape & dpsi, DShape & d2psi) const virtual
Return the geometric shape functions and also first and second derivatives w.r.t. global coordinates at ipt-th integration point. Numbering: 1D: d2psidx(i,0) = \(d^2 \psi_j / d s^2 \) 2D: d2psidx(i,0) = \(\partial^2 \psi_j / \partial x_0^2 \) d2psidx(i,1) = \(\partial^2 \psi_j / \partial x_1^2 \) d2psidx(i,2) = \(\partial^2 \psi_j / \partial x_0 \partial x_1 \) 3D: d2psidx(i,0) = \(\partial^2 \psi_j / \partial x_0^2 \) d2psidx(i,1) = \(\partial^2 \psi_j / \partial x_1^2 \) d2psidx(i,2) = \(\partial^2 \psi_j / \partial x_2^2 \) d2psidx(i,3) = \(\partial^2 \psi_j / \partial x_0 \partial x_1 \) d2psidx(i,4) = \(\partial^2 \psi_j / \partial x_0 \partial x_2 \) d2psidx(i,5) = \(\partial^2 \psi_j / \partial x_1 \partial x_2 \)
Compute the geometric shape functions and also first and second derivatives w.r.t. global coordinates at ipt-th integration point Returns Jacobian of mapping from global to local coordinates. This is the most general version, may be overloaded, if desired. Numbering: 1D: d2psidx(i,0) = \(d^2 \psi_j / d x^2 \) 2D: d2psidx(i,0) = \(\partial^2 \psi_j / \partial x_0^2 \) d2psidx(i,1) = \(\partial^2 \psi_j / \partial x_1^2 \) d2psidx(i,2) = \(\partial^2 \psi_j / \partial x_0 \partial x_1 \) 3D: d2psidx(i,0) = \(\partial^2 \psi_j / \partial x_0^2 \) d2psidx(i,1) = \(\partial^2 \psi_j / \partial x_1^2 \) d2psidx(i,2) = \(\partial^2 \psi_j / \partial x_2^2 \) d2psidx(i,3) = \(\partial^2 \psi_j / \partial x_0 \partial x_1 \) d2psidx(i,4) = \(\partial^2 \psi_j / \partial x_0 \partial x_2 \) d2psidx(i,5) = \(\partial^2 \psi_j / \partial x_1 \partial x_2 \)
Reimplemented in oomph::StorableShapeElementBase.
   {
     // Find the values of the indices of the shape functions
     // Locally cached
     // Find the element dimension
     const unsigned el_dim = dim();
     // Find the number of second derivatives required
     const unsigned n_deriv = N2deriv[el_dim];
     // Get the values of the shape function and local derivatives
     d2shape_local_at_knot(ipt, psi, dpsi, d2psi);
     // Allocate memory for the jacobian and inverse jacobian
     DenseMatrix<double> jacobian(el_dim), inverse_jacobian(el_dim);
     // Calculate the jacobian and inverse jacobian
     const double det =
       local_to_eulerian_mapping(dpsi, jacobian, inverse_jacobian);
     // Allocate memory for the jacobian of second derivatives
     DenseMatrix<double> jacobian2(n_deriv, el_dim);
     // Assemble the jacobian of second derivatives
     assemble_local_to_eulerian_jacobian2(d2psi, jacobian2);
     // Now set the value of the derivatives
     transform_second_derivatives(
       jacobian, inverse_jacobian, jacobian2, dpsi, d2psi);
     // Return the determinant of the mapping
     return det;
   }
References assemble_local_to_eulerian_jacobian2(), d2shape_local_at_knot(), dim(), el_dim, local_to_eulerian_mapping(), N2deriv, and transform_second_derivatives().
Referenced by oomph::StorableShapeElementBase::d2shape_eulerian_at_knot(), and oomph::StorableShapeElementBase::pre_compute_d2shape_eulerian_at_knots().
d2shape_local()
virtual void oomph::FiniteElement::d2shape_local (const Vector< double > & s, Shape & psi, DShape & dpsids, DShape & d2psids) const inline virtual
Function to compute the geometric shape functions and also first and second derivatives w.r.t. local coordinates at local coordinate s. This function must be overloaded for each specific geometric element (if required). (Broken virtual function — specifies the interface). Numbering: 1D: d2psids(i,0) = \(d^2 \psi_j / ds^2 \) 2D: d2psids(i,0) = \(\partial^2 \psi_j / \partial s_0^2 \) d2psids(i,1) = \(\partial^2 \psi_j / \partial s_1^2 \) d2psids(i,2) = \(\partial^2 \psi_j / \partial s_0 \partial s_1 \) 3D: d2psids(i,0) = \(\partial^2 \psi_j / \partial s_0^2 \) d2psids(i,1) = \(\partial^2 \psi_j / \partial s_1^2 \) d2psids(i,2) = \(\partial^2 \psi_j / \partial s_2^2 \) d2psids(i,3) = \(\partial^2 \psi_j / \partial s_0 \partial s_1 \) d2psids(i,4) = \(\partial^2 \psi_j / \partial s_0 \partial s_2 \) d2psids(i,5) = \(\partial^2 \psi_j / \partial s_1 \partial s_2 \)
Reimplemented in oomph::TElement< 3, NNODE_1D >, oomph::TElement< 2, NNODE_1D >, oomph::TElement< 1, NNODE_1D >, oomph::QSpectralElement< 3, NNODE_1D >, oomph::QSpectralElement< 2, NNODE_1D >, oomph::QSpectralElement< 1, NNODE_1D >, oomph::QElement< 3, NNODE_1D >, oomph::QElement< 2, NNODE_1D >, oomph::QElement< 1, NNODE_1D >, oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >, oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >, oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >, oomph::QHermiteElement< DIM >, oomph::QHermiteElement< DIM - 1 >, oomph::QHermiteElement< DIM >, oomph::QHermiteElement< DIM - 1 >, oomph::QHermiteElement< DIM >, and oomph::QHermiteElement< DIM - 1 >.
     {
       throw OomphLibError(
         "d2shape_local() is not implemented for this element\n",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by d2shape_eulerian(), oomph::SolidFiniteElement::d2shape_lagrangian(), and d2shape_local_at_knot().
d2shape_local_at_knot()
void FiniteElement::d2shape_local_at_knot (const unsigned & ipt, Shape & psi, DShape & dpsids, DShape & d2psids) const virtual
Return the geometric shape function and its first and second derivatives w.r.t. the local coordinates at the ipt-th integration point. Numbering: 1D: d2psids(i,0) = \(d^2 \psi_j / ds^2 \) 2D: d2psids(i,0) = \(\partial^2 \psi_j / \partial s_0^2 \) d2psids(i,1) = \(\partial^2 \psi_j / \partial s_1^2 \) d2psids(i,2) = \(\partial^2 \psi_j / \partial s_0 \partial s_1 \) 3D: d2psids(i,0) = \(\partial^2 \psi_j / \partial s_0^2 \) d2psids(i,1) = \(\partial^2 \psi_j / \partial s_1^2 \) d2psids(i,2) = \(\partial^2 \psi_j / \partial s_2^2 \) d2psids(i,3) = \(\partial^2 \psi_j / \partial s_0 \partial s_1 \) d2psids(i,4) = \(\partial^2 \psi_j / \partial s_0 \partial s_2 \) d2psids(i,5) = \(\partial^2 \psi_j / \partial s_1 \partial s_2 \)
Calculate the shape function and its first and second derivatives w.r.t. local coordinates at the ipt-th integration point. Numbering: 1D: d2psids(i,0) = \(d^2 \psi_j / d s^2 \) 2D: d2psids(i,0) = \(\partial^2 \psi_j / \partial s_0^2 \) d2psids(i,1) = \(\partial^2 \psi_j / \partial s_1^2 \) d2psids(i,2) = \(\partial^2 \psi_j / \partial s_0 \partial s_1 \) 3D: d2psids(i,0) = \(\partial^2 \psi_j / \partial s_0^2 \) d2psids(i,1) = \(\partial^2 \psi_j / \partial s_1^2 \) d2psids(i,2) = \(\partial^2 \psi_j / \partial s_2^2 \) d2psids(i,3) = \(\partial^2 \psi_j / \partial s_0 \partial s_1 \) d2psids(i,4) = \(\partial^2 \psi_j / \partial s_0 \partial s_2 \) d2psids(i,5) = \(\partial^2 \psi_j / \partial s_1 \partial s_2 \)
Reimplemented in oomph::StorableShapeElementBase.
   {
     // Find the dimension of the element
     const unsigned el_dim = dim();
     // Storage for the local coordinates of the integration point
     Vector<double> s(el_dim);
     // Set the local coordinate
     for (unsigned i = 0; i < el_dim; i++)
     {
       s[i] = integral_pt()->knot(ipt, i);
     }
     // Get the shape function and first and second derivatives
     d2shape_local(s, psi, dpsids, d2psids);
   }
References d2shape_local(), dim(), el_dim, i, integral_pt(), oomph::Integral::knot(), and s.
Referenced by d2shape_eulerian_at_knot(), oomph::SolidFiniteElement::d2shape_lagrangian_at_knot(), oomph::StorableShapeElementBase::d2shape_local_at_knot(), and oomph::StorableShapeElementBase::pre_compute_d2shape_local_at_knots().
d_dshape_eulerian_dnodal_coordinates()
void FiniteElement::d_dshape_eulerian_dnodal_coordinates (const double & det_jacobian, const DenseMatrix< double > & jacobian, const DenseMatrix< double > & djacobian_dX, const DenseMatrix< double > & inverse_jacobian, const DShape & dpsids, RankFourTensor< double > & d_dpsidx_dX) const protected virtual
A template-free interface that calculates the derivative w.r.t. the nodal coordinates \(X_{pq} \) of the derivative of the shape functions \(\psi_j \) w.r.t. the global eulerian coordinates \(x_i \). I.e. this function calculates
\[ \frac{\partial}{\partial X_{pq}} \left(\frac{\partial \psi_j}{\partial x_i} \right). \]
To do this it requires the determinant of the jacobian mapping, its derivative w.r.t. the nodal coordinates \(X_{pq} \), the inverse jacobian and the derivatives of the shape functions w.r.t. the local coordinates. The result is returned as a tensor of rank four. Numbering: d_dpsidx_dX(p,q,j,i) = \(\frac{\partial}{\partial X_{pq}} \left(\frac{\partial \psi_j}{\partial x_i} \right) \) By default the function will use the dimension of the element to call the correct d_dshape_eulerian_dnodal_coordinates_templated_helper(..) function. This should be overloaded for efficiency (removal of a switch statement) in specific elements.
Template-free interface calculating the derivative w.r.t. the nodal coordinates \(X_{pq} \) of the derivative of the shape functions \(\psi_j \) w.r.t. the global eulerian coordinates \(x_i \). I.e. this function calculates
\[ \frac{\partial}{\partial X_{pq}} \left(\frac{\partial \psi_j}{\partial x_i} \right). \]
To do this it requires the determinant of the jacobian mapping, its derivative w.r.t. the nodal coordinates \(X_{pq} \), the inverse jacobian and the derivatives of the shape functions w.r.t. the local coordinates. The result is returned as a tensor of rank four. Numbering: d_dpsidx_dX(p,q,j,i) = \(\frac{\partial}{\partial X_{pq}} \left(\frac{\partial \psi_j}{\partial x_i} \right) \) This function is slightly inefficient, given that it uses a switch statement. It can always be overloaded in specific geometric elements, for efficiency reasons.
   {
     // Determine the spatial dimension of the element
     const unsigned el_dim = dim();
 #ifdef PARANOID
     // Determine the number of nodes in the element
     const unsigned n_node = nnode();
     // Check that d_dpsidx_dX is of the correct size
     if (d_dpsidx_dX.nindex1() != el_dim || d_dpsidx_dX.nindex2() != n_node ||
         d_dpsidx_dX.nindex3() != n_node || d_dpsidx_dX.nindex4() != el_dim)
     {
       std::ostringstream error_message;
       error_message << "d_dpsidx_dX must be of the following dimensions:"
                     << "\nd_dpsidx_dX(el_dim,n_node,n_node,el_dim)";
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Call the appropriate templated function, depending on the
     // element dimension
     switch (el_dim)
     {
       case 0:
         d_dshape_eulerian_dnodal_coordinates_templated_helper<0>(
           det_jacobian,
           jacobian,
           djacobian_dX,
           inverse_jacobian,
           dpsids,
           d_dpsidx_dX);
         break;
       case 1:
         d_dshape_eulerian_dnodal_coordinates_templated_helper<1>(
           det_jacobian,
           jacobian,
           djacobian_dX,
           inverse_jacobian,
           dpsids,
           d_dpsidx_dX);
         break;
       case 2:
         d_dshape_eulerian_dnodal_coordinates_templated_helper<2>(
           det_jacobian,
           jacobian,
           djacobian_dX,
           inverse_jacobian,
           dpsids,
           d_dpsidx_dX);
         break;
       case 3:
         d_dshape_eulerian_dnodal_coordinates_templated_helper<3>(
           det_jacobian,
           jacobian,
           djacobian_dX,
           inverse_jacobian,
           dpsids,
           d_dpsidx_dX);
         break;
         // Catch-all default case: issue warning and die
       default:
         std::ostringstream error_stream;
         error_stream << "Dimension of the element must be 0,1,2 or 3, not "
                      << el_dim << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
   }
References dim(), el_dim, oomph::RankFourTensor< T >::nindex1(), oomph::RankFourTensor< T >::nindex2(), oomph::RankFourTensor< T >::nindex3(), oomph::RankFourTensor< T >::nindex4(), nnode(), OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by dshape_eulerian_at_knot(), oomph::AxisymmetricNavierStokesEquations::interpolated_d_dudx_dX_axi_nst(), and oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::interpolated_d_dudx_dX_axi_nst().
d_dshape_eulerian_dnodal_coordinates_templated_helper() [1/5]
template<> void oomph::FiniteElement::d_dshape_eulerian_dnodal_coordinates_templated_helper (const double & det_jacobian, const DenseMatrix< double > & jacobian, const DenseMatrix< double > & djacobian_dX, const DenseMatrix< double > & inverse_jacobian, const DShape & dpsids, RankFourTensor< double > & d_dpsidx_dX) const protected
Zero-d specialisation of function to calculate the derivative w.r.t. the nodal coordinates \(X_{pq} \) of the derivative of the shape functions w.r.t. the global eulerian coordinates \(x_i \).
   {
     // Issue a warning
     oomph_info << "\nWarning: You are trying to calculate derivatives of "
                << "eulerian derivatives of shape functions w.r.t. nodal "
                << "coordinates for a 'point' element." << std::endl
                << "This makes no sense and is almost certainly an error."
                << std::endl
                << std::endl;
   }
References oomph::oomph_info.
d_dshape_eulerian_dnodal_coordinates_templated_helper() [2/5]
template<> void oomph::FiniteElement::d_dshape_eulerian_dnodal_coordinates_templated_helper (const double & det_jacobian, const DenseMatrix< double > & jacobian, const DenseMatrix< double > & djacobian_dX, const DenseMatrix< double > & inverse_jacobian, const DShape & dpsids, RankFourTensor< double > & d_dpsidx_dX) const protected
One-d specialisation of function to calculate the derivative w.r.t. the nodal coordinates \(X_{pq} \) of the derivative of the shape functions w.r.t. the global eulerian coordinates \(x_i \).
   {
     // Find inverse of determinant of jacobian of mapping
     const double inv_det_jac = 1.0 / det_jacobian;
     // Determine the number of nodes in the element
     const unsigned n_node = nnode();
     // Loop over the shape functions
     for (unsigned q = 0; q < n_node; q++)
     {
       // Loop over the shape functions
       for (unsigned j = 0; j < n_node; j++)
       {
         d_dpsidx_dX(0, q, j, 0) =
           -djacobian_dX(0, q) * dpsids(j, 0) * inv_det_jac * inv_det_jac;
       }
     }
   }
References j, nnode(), and Eigen::numext::q.
d_dshape_eulerian_dnodal_coordinates_templated_helper() [3/5]
template<> void oomph::FiniteElement::d_dshape_eulerian_dnodal_coordinates_templated_helper (const double & det_jacobian, const DenseMatrix< double > & jacobian, const DenseMatrix< double > & djacobian_dX, const DenseMatrix< double > & inverse_jacobian, const DShape & dpsids, RankFourTensor< double > & d_dpsidx_dX) const protected
Two-d specialisation of function to calculate the derivative w.r.t. the nodal coordinates \(X_{pq} \) of the derivative of the shape functions w.r.t. the global eulerian coordinates \(x_i \).
   {
     // Find inverse of determinant of jacobian of mapping
     const double inv_det_jac = 1.0 / det_jacobian;
     // Determine the number of nodes in the element
     const unsigned n_node = nnode();
     // Loop over the spatial dimension (this must be 2)
     for (unsigned p = 0; p < 2; p++)
     {
       // Loop over the shape functions
       for (unsigned q = 0; q < n_node; q++)
       {
         // Loop over the shape functions
         for (unsigned j = 0; j < n_node; j++)
         {
           // i=0
           d_dpsidx_dX(p, q, j, 0) =
             -djacobian_dX(p, q) * (inverse_jacobian(0, 0) * dpsids(j, 0) +
                                    inverse_jacobian(0, 1) * dpsids(j, 1));
           if (p == 1)
           {
             d_dpsidx_dX(p, q, j, 0) +=
               dpsids(j, 0) * dpsids(q, 1) - dpsids(j, 1) * dpsids(q, 0);
           }
           d_dpsidx_dX(p, q, j, 0) *= inv_det_jac;
           // i=1
           d_dpsidx_dX(p, q, j, 1) =
             -djacobian_dX(p, q) * (inverse_jacobian(1, 1) * dpsids(j, 1) +
                                    inverse_jacobian(1, 0) * dpsids(j, 0));
           if (p == 0)
           {
             d_dpsidx_dX(p, q, j, 1) +=
               dpsids(j, 1) * dpsids(q, 0) - dpsids(j, 0) * dpsids(q, 1);
           }
           d_dpsidx_dX(p, q, j, 1) *= inv_det_jac;
         }
       }
     }
   }
References j, nnode(), p, and Eigen::numext::q.
d_dshape_eulerian_dnodal_coordinates_templated_helper() [4/5]
template<> void oomph::FiniteElement::d_dshape_eulerian_dnodal_coordinates_templated_helper (const double & det_jacobian, const DenseMatrix< double > & jacobian, const DenseMatrix< double > & djacobian_dX, const DenseMatrix< double > & inverse_jacobian, const DShape & dpsids, RankFourTensor< double > & d_dpsidx_dX) const protected
Three-d specialisation of function to calculate the derivative w.r.t. the nodal coordinates \(X_{pq} \) of the derivative of the shape functions w.r.t. the global eulerian coordinates \(x_i \).
   {
     // Find inverse of determinant of jacobian of mapping
     const double inv_det_jac = 1.0 / det_jacobian;
     // Determine the number of nodes in the element
     const unsigned n_node = nnode();
     // Loop over the spatial dimension (this must be 3)
     for (unsigned p = 0; p < 3; p++)
     {
       // Loop over the shape functions
       for (unsigned q = 0; q < n_node; q++)
       {
         // Loop over the shape functions
         for (unsigned j = 0; j < n_node; j++)
         {
           // Terms not multiplied by delta function
           for (unsigned i = 0; i < 3; i++)
           {
             d_dpsidx_dX(p, q, j, i) =
               -djacobian_dX(p, q) * (inverse_jacobian(i, 0) * dpsids(j, 0) +
                                      inverse_jacobian(i, 1) * dpsids(j, 1) +
                                      inverse_jacobian(i, 2) * dpsids(j, 2));
           }
           // Delta function terms
           switch (p)
           {
             case 0:
               d_dpsidx_dX(p, q, j, 1) += ((dpsids(q, 2) * jacobian(1, 2) -
                                            dpsids(q, 1) * jacobian(2, 2)) *
                                             dpsids(j, 0) +
                                           (dpsids(q, 0) * jacobian(2, 2) -
                                            dpsids(q, 2) * jacobian(0, 2)) *
                                             dpsids(j, 1) +
                                           (dpsids(q, 1) * jacobian(0, 2) -
                                            dpsids(q, 0) * jacobian(1, 2)) *
                                             dpsids(j, 2));
               d_dpsidx_dX(p, q, j, 2) += ((dpsids(q, 1) * jacobian(2, 1) -
                                            dpsids(q, 2) * jacobian(1, 1)) *
                                             dpsids(j, 0) +
                                           (dpsids(q, 2) * jacobian(0, 1) -
                                            dpsids(q, 0) * jacobian(2, 1)) *
                                             dpsids(j, 1) +
                                           (dpsids(q, 0) * jacobian(1, 1) -
                                            dpsids(q, 1) * jacobian(0, 1)) *
                                             dpsids(j, 2));
               break;
             case 1:
               d_dpsidx_dX(p, q, j, 0) += ((dpsids(q, 1) * jacobian(2, 2) -
                                            dpsids(q, 2) * jacobian(1, 2)) *
                                             dpsids(j, 0) +
                                           (dpsids(q, 2) * jacobian(0, 2) -
                                            dpsids(q, 0) * jacobian(2, 2)) *
                                             dpsids(j, 1) +
                                           (dpsids(q, 0) * jacobian(1, 2) -
                                            dpsids(q, 1) * jacobian(0, 2)) *
                                             dpsids(j, 2));
               d_dpsidx_dX(p, q, j, 2) += ((dpsids(q, 2) * jacobian(1, 0) -
                                            dpsids(q, 1) * jacobian(2, 0)) *
                                             dpsids(j, 0) +
                                           (dpsids(q, 0) * jacobian(2, 0) -
                                            dpsids(q, 2) * jacobian(0, 0)) *
                                             dpsids(j, 1) +
                                           (dpsids(q, 1) * jacobian(0, 0) -
                                            dpsids(q, 0) * jacobian(1, 0)) *
                                             dpsids(j, 2));
               break;
             case 2:
               d_dpsidx_dX(p, q, j, 0) += ((dpsids(q, 2) * jacobian(1, 1) -
                                            dpsids(q, 1) * jacobian(2, 1)) *
                                             dpsids(j, 0) +
                                           (dpsids(q, 0) * jacobian(2, 1) -
                                            dpsids(q, 2) * jacobian(0, 1)) *
                                             dpsids(j, 1) +
                                           (dpsids(q, 1) * jacobian(0, 1) -
                                            dpsids(q, 0) * jacobian(1, 1)) *
                                             dpsids(j, 2));
               d_dpsidx_dX(p, q, j, 1) += ((dpsids(q, 1) * jacobian(2, 0) -
                                            dpsids(q, 2) * jacobian(1, 0)) *
                                             dpsids(j, 0) +
                                           (dpsids(q, 2) * jacobian(0, 0) -
                                            dpsids(q, 0) * jacobian(2, 0)) *
                                             dpsids(j, 1) +
                                           (dpsids(q, 0) * jacobian(1, 0) -
                                            dpsids(q, 1) * jacobian(0, 0)) *
                                             dpsids(j, 2));
               break;
           }
           // Divide through by the determinant of the Jacobian mapping
           for (unsigned i = 0; i < 3; i++)
           {
             d_dpsidx_dX(p, q, j, i) *= inv_det_jac;
           }
         }
       }
     }
   }
References i, j, nnode(), p, and Eigen::numext::q.
d_dshape_eulerian_dnodal_coordinates_templated_helper() [5/5]
template<unsigned DIM> void oomph::FiniteElement::d_dshape_eulerian_dnodal_coordinates_templated_helper (const double & det_jacobian, const DenseMatrix< double > & jacobian, const DenseMatrix< double > & djacobian_dX, const DenseMatrix< double > & inverse_jacobian, const DShape & dpsids, RankFourTensor< double > & d_dpsidx_dX) const protected
Calculate the derivative w.r.t. the nodal coordinates \(X_{pq} \) of the derivative of the shape functions w.r.t. the global eulerian coordinates \(x_i \), using the determinant of the jacobian mapping, its derivative w.r.t. the nodal coordinates \(X_{pq} \), the inverse jacobian and the derivatives of the shape functions w.r.t. the local coordinates. The result is returned as a tensor of rank four. Numbering: d_dpsidx_dX(p,q,j,i) = \(\frac{\partial}{\partial X_{pq}} \left(\frac{\partial \psi_j}{\partial x_i} \right) \) This function is templated by the dimension of the element.
describe_local_dofs()
void FiniteElement::describe_local_dofs (std::ostream & out, const std::string & current_string) const virtual
Function to describe the local dofs of the element[s]. The ostream specifies the output stream to which the description is written; the string stores the currently assembled output that is ultimately written to the output stream by Data::describe_dofs(...); it is typically built up incrementally as we descend through the call hierarchy of this function when called from Problem::describe_dofs(...)
Function to describe the local dofs of the element. The ostream specifies the output stream to which the description is written; the string stores the currently assembled output that is ultimately written to the output stream by Data::describe_dofs(...); it is typically built up incrementally as we descend through the call hierarchy of this function when called from Problem::describe_dofs(...)
Reimplemented from oomph::GeneralisedElement.
Reimplemented in DistanceWrapper< ELEMENT >, oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >, oomph::RefineableQSpectralPoissonElement< DIM, NNODE_1D >, oomph::SpectralElement, oomph::PseudoSolidNodeUpdateElement< TCrouzeixRaviartElement< 2 >, TPVDBubbleEnrichedElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< TTaylorHoodElement< 2 >, TPVDElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< GeneralisedNewtonianAxisymmetricTTaylorHoodElement, TPVDElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< AxisymmetricTTaylorHoodElement, TPVDElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< GeneralisedNewtonianTTaylorHoodElement< 2 >, TPVDElement< 2, 3 > >, oomph::ProjectableElement< ELEMENT >, oomph::ProjectableElement< FVK_ELEMENT >, oomph::ProjectableElement< AXISYM_LINEAR_ELAST_ELEMENT >, oomph::ProjectableElement< UNSTEADY_HEAT_ELEMENT >, oomph::ProjectableElement< LINEAR_ELAST_ELEMENT >, oomph::ProjectableElement< CROUZEIX_RAVIART_ELEMENT >, oomph::ProjectableElement< HELMHOLTZ_ELEMENT >, oomph::ProjectableElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >, oomph::ProjectableElement< TAYLOR_HOOD_ELEMENT >, oomph::ProjectableElement< PVD_ELEMENT >, oomph::ProjectableElement< ADR_ELEMENT >, oomph::ProjectableElement< DARCY_ELEMENT >, oomph::ProjectableElement< POISSON_ELEMENT >, oomph::ProjectableElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >, oomph::ProjectableElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >, oomph::ProjectableElement< LINEAR_HEAT_AND_ELAST_ELEMENT >, oomph::FSIWallElement, oomph::FaceElementAsGeomObject< ELEMENT >, oomph::SolidFiniteElement, oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >, oomph::ElementWithSpecificMovingNodes< ELEMENT, SpineNode >, oomph::ElementWithSpecificMovingNodes< ELEMENT, PerturbedSpineNode >, oomph::ElementWithSpecificMovingNodes< ELEMENT, AlgebraicNode >, oomph::ElementWithSpecificMovingNodes< ELEMENT, MacroElementNodeUpdateNode >, oomph::ElementWithMovingNodes, oomph::HeatedLinearSurfaceContactElement< ELEMENT >, and oomph::ElementWithExternalElement.
   {
     // Call the standard finite element classification.
     GeneralisedElement::describe_local_dofs(out, current_string);
     describe_nodal_local_dofs(out, current_string);
   }
References oomph::GeneralisedElement::describe_local_dofs(), describe_nodal_local_dofs(), and out().
Referenced by oomph::ElementWithMovingNodes::describe_local_dofs(), oomph::SolidFiniteElement::describe_local_dofs(), oomph::FSIWallElement::describe_local_dofs(), oomph::SpectralElement::describe_local_dofs(), and oomph::RefineableQSpectralPoissonElement< DIM, NNODE_1D >::describe_local_dofs().
describe_nodal_local_dofs()
void FiniteElement::describe_nodal_local_dofs (std::ostream & out, const std::string & current_string) const virtual
Function to describe the local dofs of the element[s]. The ostream specifies the output stream to which the description is written; the string stores the currently assembled output that is ultimately written to the output stream by Data::describe_dofs(...); it is typically built up incrementally as we descend through the call hierarchy of this function when called from Problem::describe_dofs(...)
specifies the output stream to which the description is written; the string stores the currently assembled output that is ultimately written to the output stream by Data::describe_dofs(...); it is typically built up incrementally as we descend through the call hierarchy of this function when called from Problem::describe_dofs(...)
   {
     // Find the number of nodes
     const unsigned n_node = nnode();
     for (unsigned n = 0; n < n_node; n++)
     {
       // Pointer to node
       Node* const nod_pt = node_pt(n);
       std::stringstream conversion;
       conversion << " of Node " << n << current_string;
       std::string in(conversion.str());
       nod_pt->describe_dofs(out, in);
     } // End if for n_node
   } // End describe_nodal_local_dofs
References oomph::Data::describe_dofs(), n, nnode(), node_pt(), out(), and oomph::Global_string_for_annotation::string().
Referenced by describe_local_dofs(), and oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::describe_local_dofs().
dim()
unsigned oomph::FiniteElement::dim () const inline
Return the spatial dimension of the element, i.e. the number of local coordinates required to parametrise its geometry.
     {
       return Elemental_dimension;
     }
References Elemental_dimension.
Referenced by oomph::TreeBasedRefineableMeshBase::adapt_mesh(), oomph::DGFaceElement::add_flux_contributions(), oomph::ImposeImpenetrabilityElement< ELEMENT >::additional_ndof_types(), assemble_eulerian_base_vectors(), oomph::RefineableElement::assemble_eulerian_base_vectors(), assemble_local_to_eulerian_jacobian(), oomph::RefineableElement::assemble_local_to_eulerian_jacobian(), assemble_local_to_eulerian_jacobian2(), oomph::RefineableElement::assemble_local_to_eulerian_jacobian2(), oomph::SolidFiniteElement::assemble_local_to_lagrangian_jacobian(), oomph::RefineableSolidElement::assemble_local_to_lagrangian_jacobian(), oomph::SolidFiniteElement::assemble_local_to_lagrangian_jacobian2(), oomph::RefineableSolidElement::assemble_local_to_lagrangian_jacobian2(), oomph::Multi_domain_functions::aux_setup_multi_domain_interaction(), oomph::AxisymmetricLinearElasticityEquationsBase::body_force(), oomph::LinearElasticityEquationsBase< DIM >::body_force(), oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::body_force(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::body_force(), oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::body_force(), oomph::PVDEquationsBase< DIM >::body_force(), oomph::MeshAsGeomObject::build_it(), oomph::OneDMesh< ELEMENT >::check_1d(), FourierDecomposedHelmholtzProblem< ELEMENT >::check_gamma(), oomph::Mesh::check_inverted_elements(), check_J_eulerian_at_knots(), oomph::FaceElement::check_J_eulerian_at_knots(), oomph::SolidFiniteElement::compute_norm(), oomph::AxisymmetricNavierStokesEquations::compute_physical_size(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::compute_physical_size(), AirwayReopeningProblem< ELEMENT >::connect_walls(), oomph::FaceElement::continuous_tangent_and_outer_unit_normal(), d2shape_eulerian(), d2shape_eulerian_at_knot(), oomph::SolidFiniteElement::d2shape_lagrangian(), oomph::SolidFiniteElement::d2shape_lagrangian_at_knot(), d2shape_local_at_knot(), d_dshape_eulerian_dnodal_coordinates(), oomph::ProjectableGeneralisedNewtonianTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::data_values_of_field(), oomph::ProjectableGeneralisedNewtonianCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::data_values_of_field(), oomph::DGEulerFaceElement< ELEMENT >::DGEulerFaceElement(), oomph::DGEulerFaceReflectionElement< ELEMENT >::DGEulerFaceReflectionElement(), dJ_eulerian_at_knot(), dJ_eulerian_dnodal_coordinates(), oomph::Z2ErrorEstimator::doc_flux(), oomph::FSI_functions::doc_fsi(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::drag_force(), dshape_eulerian(), dshape_eulerian_at_knot(), oomph::SolidFiniteElement::dshape_lagrangian(), oomph::SolidFiniteElement::dshape_lagrangian_at_knot(), dshape_local_at_knot(), oomph::Mesh::elemental_dimension(), oomph::ElementElementMortaringElement::evaluate_constraint_functions(), oomph::FaceElementAsGeomObject< ELEMENT >::FaceElementAsGeomObject(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), oomph::ImposeImpenetrabilityElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(), oomph::ImposeParallelOutflowElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(), oomph::SolidFiniteElement::fill_in_generic_jacobian_for_solid_ic(), oomph::FluidInterfaceElement::fill_in_generic_residual_contribution_interface(), oomph::PointFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary(), oomph::LineFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary(), oomph::SolidFiniteElement::fill_in_jacobian_for_newmark_accel(), oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::fill_in_off_diagonal_block_analytic(), oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_off_diagonal_block_analytic(), oomph::NavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::fill_in_off_diagonal_block_analytic(), oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_off_diagonal_block_analytic(), oomph::AxisymmetricPoroelasticityEquations::fluid_body_force(), oomph::PoroelasticityEquations< DIM >::force_fluid(), oomph::PoroelasticityEquations< DIM >::force_solid(), oomph::FpPressureAdvDiffRobinBCElement< ELEMENT >::FpPressureAdvDiffRobinBCElement(), oomph::FpPressureAdvDiffRobinBCMixedOrderSpaceTimeElement< ELEMENT >::FpPressureAdvDiffRobinBCMixedOrderSpaceTimeElement(), oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >::FpPressureAdvDiffRobinBCSpaceTimeElement(), oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::FpPressureAdvectionDiffusionProblem(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::FSIImposeDisplacementByLagrangeMultiplierElement(), oomph::MGSolver< DIM >::full_setup(), oomph::HelmholtzMGPreconditioner< DIM >::full_setup(), oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::get_body_force_nst(), oomph::ImposeImpenetrabilityElement< ELEMENT >::get_dof_numbers_for_unknowns(), oomph::ImposeParallelOutflowElement< ELEMENT >::get_dof_numbers_for_unknowns(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::get_dof_numbers_for_unknowns(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::get_dof_numbers_for_unknowns(), oomph::NavierStokesSurfaceDragTorqueElement< ELEMENT >::get_drag_and_torque(), oomph::Z2ErrorEstimator::get_element_errors(), oomph::ProjectableGeneralisedNewtonianTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::get_field(), oomph::ProjectableGeneralisedNewtonianCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::get_field(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::get_flux(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_kinetic_energy_flux(), oomph::NavierStokesSchurComplementPreconditioner::get_pressure_advection_diffusion_matrix(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_rate_of_traction_work(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_rate_of_traction_work_components(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_volume_flux(), oomph::QSolidElementBase::get_x_and_xi(), oomph::QElementBase::get_x_from_macro_element(), oomph::PMLHelmholtzPowerElement< ELEMENT >::global_flux_contribution(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::global_flux_contribution_from_helmholtz(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::global_flux_contribution_from_solid(), oomph::HelmholtzBCElementBase< ELEMENT >::global_power_contribution(), oomph::PMLHelmholtzPowerElement< ELEMENT >::global_power_contribution(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::ImposeDisplacementByLagrangeMultiplierElement(), oomph::ImposeParallelOutflowElement< ELEMENT >::ImposeParallelOutflowElement(), oomph::SurfactantTransportInterfaceElement::integrate_c(), integrate_fct(), oomph::SolubleSurfactantTransportInterfaceElement::integrated_C(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::interpolated_du_dt_nst(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::interpolated_du_dt_ust_heat(), oomph::FaceElement::interpolated_dxdt(), oomph::SolidFiniteElement::interpolated_dxids(), oomph::AxisymFoepplvonKarmanEquations::interpolated_stress(), oomph::FoepplvonKarmanEquations::interpolated_stress(), oomph::FaceElement::interpolated_x(), oomph::SolidFaceElement::interpolated_xi(), interpolated_zeta(), invert_jacobian_mapping(), J_eulerian(), oomph::FaceElement::J_eulerian(), J_eulerian_at_knot(), oomph::FaceElement::J_eulerian_at_knot(), oomph::ProjectableAdvectionDiffusionReactionElement< ADR_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableAxisymLinearElasticityElement< AXISYM_LINEAR_ELAST_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableAxisymmetricTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableAxisymmetricCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableDarcyElement< DARCY_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableDisplacementBasedFoepplvonKarmanElement< FVK_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableFoepplvonKarmanElement< FVK_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableFourierDecomposedHelmholtzElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >::jacobian_and_shape_of_field(), oomph::GeneralisedNewtonianProjectableAxisymmetricTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::jacobian_and_shape_of_field(), oomph::GeneralisedNewtonianProjectableAxisymmetricCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableGeneralisedNewtonianTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableGeneralisedNewtonianCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableHelmholtzElement< HELMHOLTZ_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableLinearElasticityElement< LINEAR_ELAST_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectablePMLFourierDecomposedHelmholtzElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectablePMLHelmholtzElement< HELMHOLTZ_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectablePMLTimeHarmonicLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectablePoissonElement< POISSON_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableUnsteadyHeatMixedOrderSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableTimeHarmonicFourierDecomposedLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableTimeHarmonicLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableUnsteadyHeatElement< UNSTEADY_HEAT_ELEMENT >::jacobian_and_shape_of_field(), oomph::SolubleSurfactantTransportInterfaceElement::l2_norm_of_height(), oomph::QHermiteElement< DIM >::local_coord_is_valid(), oomph::QElementBase::local_coord_is_valid(), oomph::TElementBase::local_coord_is_valid(), oomph::FaceElement::local_coordinate_in_bulk(), oomph::ProjectableGeneralisedNewtonianTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::local_equation(), oomph::ProjectableGeneralisedNewtonianCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::local_equation(), local_to_eulerian_mapping(), local_to_eulerian_mapping_diagonal(), oomph::RefineableElement::local_to_eulerian_mapping_diagonal(), oomph::SolidFiniteElement::local_to_lagrangian_mapping(), oomph::SolidFiniteElement::local_to_lagrangian_mapping_diagonal(), oomph::RefineableSolidElement::local_to_lagrangian_mapping_diagonal(), locate_zeta(), oomph::Multi_domain_functions::locate_zeta_for_local_coordinates(), oomph::QHermiteElement< DIM >::move_local_coord_back_into_element(), oomph::QElementBase::move_local_coord_back_into_element(), oomph::TElementBase::move_local_coord_back_into_element(), oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::NavierStokesMixedOrderSpaceTimeTractionElement(), oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::NavierStokesSpaceTimeTractionElement(), oomph::NavierStokesTractionElement< ELEMENT >::NavierStokesTractionElement(), oomph::ImposeParallelOutflowElement< ELEMENT >::ndof_types(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::ndof_types(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::ndof_types(), oomph::ProjectableGeneralisedNewtonianTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::nfields_for_projection(), oomph::ProjectableGeneralisedNewtonianCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::nfields_for_projection(), oomph::ProjectableLinearElasticityElement< LINEAR_ELAST_ELEMENT >::nfields_for_projection(), oomph::ProjectablePMLTimeHarmonicLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::nfields_for_projection(), oomph::ProjectableTimeHarmonicFourierDecomposedLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::nfields_for_projection(), oomph::ProjectableTimeHarmonicLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::nfields_for_projection(), oomph::ProjectableGeneralisedNewtonianTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::nhistory_values_for_projection(), oomph::ProjectableGeneralisedNewtonianCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::nhistory_values_for_projection(), oomph::QElementBase::nnode_on_face(), oomph::Mesh::node_update(), oomph::NodeElementSolidOnlyMortaringElement::NodeElementSolidOnlyMortaringElement(), oomph::DGEulerFaceElement< ELEMENT >::numerical_flux(), oomph::ProjectableGeneralisedNewtonianTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::nvalue_of_field(), oomph::ProjectableGeneralisedNewtonianCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::nvalue_of_field(), oomph::FaceElement::outer_unit_normal(), oomph::DummyFaceElement< ELEMENT >::output(), oomph::FluidInterfaceElement::output(), oomph::SurfactantTransportInterfaceElement::output(), oomph::NavierStokesSurfaceDragTorqueElement< ELEMENT >::output(), oomph::FSISolidTractionElement< ELEMENT, DIM >::output(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::output(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::output(), oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::output(), oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::output(), oomph::PMLTimeHarmonicLinearElasticityTractionElement< ELEMENT >::output(), oomph::PoissonFluxElement< ELEMENT >::output(), oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::output(), oomph::ProjectableUnsteadyHeatMixedOrderSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::output(), oomph::TimeHarmonicLinearElasticityTractionElement< ELEMENT >::output(), oomph::ProjectableUnsteadyHeatElement< UNSTEADY_HEAT_ELEMENT >::output(), oomph::ElementWithExternalElement::output_external_elements(), oomph::FaceElement::output_zeta(), oomph::TreeBasedRefineableMeshBase::p_adapt_mesh(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::point_output_data(), oomph::NavierStokesEquations< DIM >::point_output_data(), oomph::PoissonEquations< DIM >::point_output_data(), oomph::StorableShapeElementBase::pre_compute_d2shape_local_at_knots(), oomph::StorableShapeElementBase::pre_compute_dshape_local_at_knots(), oomph::RefineableImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::RefineableFSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), oomph::DGFaceElement::report_info(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::residual_for_projection(), oomph::ProjectableDarcyElement< DARCY_ELEMENT >::residual_for_projection(), oomph::ProjectableElement< ELEMENT >::residual_for_projection(), self_test(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::set_boundary_shape_geom_object_pt(), set_dimension(), oomph::QElementBase::set_macro_elem_pt(), oomph::LineMeshBase::setup_boundary_element_info(), oomph::QuadMeshBase::setup_boundary_element_info(), oomph::TetMeshBase::setup_boundary_element_info(), oomph::TriangleMeshBase::setup_boundary_element_info(), oomph::HermiteQuadMesh< ELEMENT >::setup_boundary_element_info(), oomph::FourierDecomposedHelmholtzDtNMesh< ELEMENT >::setup_gamma(), oomph::HelmholtzDtNMesh< ELEMENT >::setup_gamma(), oomph::DGFaceElement::setup_neighbour_info(), oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::shape_and_test_at_knot(), oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::shape_and_test_at_knot(), shape_at_knot(), oomph::DGElement::slope_limit(), oomph::AxisymmetricPoroelasticityEquations::solid_body_force(), oomph::PVDEquationsWithPressure< DIM >::solid_pshape_at_knot(), oomph::SolidTractionElement< ELEMENT >::SolidTractionElement(), oomph::DarcyEquations< DIM >::source(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::square_of_l2_norm_of_error(), oomph::StefanBoltzmannUnsteadyHeatFluxElement< ELEMENT >::StefanBoltzmannUnsteadyHeatFluxElement(), oomph::SurfaceContactElementBase< ELEMENT >::SurfaceContactElementBase(), oomph::SurfaceMeltElement< ELEMENT >::SurfaceMeltElement(), transform_derivatives(), transform_derivatives_diagonal(), transform_second_derivatives(), oomph::UnsteadyHeatBaseFaceElement< ELEMENT >::UnsteadyHeatBaseFaceElement(), oomph::YoungLaplaceContactAngleElement< ELEMENT >::YoungLaplaceContactAngleElement(), oomph::FaceElement::zeta_nodal(), and oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::zeta_nodal().
disable_ALE()
virtual void oomph::FiniteElement::disable_ALE () inline virtual
This is an empty function that establishes a uniform interface for all (derived) elements that involve time-derivatives. Such elements are/should be implemented in ALE form to allow mesh motions. The additional expense associated with the computation of the mesh velocities is, of course, superfluous if the elements are used in problems in which the mesh is stationary. This function should therefore be overloaded in all derived elements that are formulated in ALE form to suppress the computation of the mesh velocities. The user disables the ALE functionality at his/her own risk! If the mesh does move after all, then the results will be wrong. Here we simply issue a warning message stating that the empty function has been called.
Reimplemented in oomph::UnsteadyHeatEquations< DIM >, oomph::UnsteadyHeatEquations< 2 >, oomph::SphericalNavierStokesEquations, oomph::SphericalAdvectionDiffusionEquations, oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< 2 >, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< 2 >, oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::NavierStokesEquations< DIM >, oomph::NavierStokesEquations< 2 >, oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >, oomph::BuoyantQCrouzeixRaviartElement< DIM >, oomph::LinearisedNavierStokesEquations, oomph::LinearisedAxisymmetricNavierStokesEquations, oomph::GeneralisedNewtonianNavierStokesEquations< DIM >, oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations, oomph::AxisymmetricNavierStokesEquations, oomph::AxisymAdvectionDiffusionEquations, oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >, oomph::GeneralisedAdvectionDiffusionEquations< DIM >, oomph::GeneralisedAdvectionDiffusionEquations< 2 >, oomph::AdvectionDiffusionEquations< DIM >, oomph::AdvectionDiffusionEquations< 2 >, oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::AxisymmetricQAdvectionCrouzeixRaviartElement, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement, oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement, RefineableBuoyantQCrouzeixRaviartElement< DIM >, oomph::LinearisedAxisymmetricNavierStokesEquations, and oomph::LinearisedAxisymmetricNavierStokesEquations.
     {
       std::ostringstream warn_message;
       warn_message
         << "Warning: You have just called the default (empty) function \n\n"
         << "    FiniteElement::disable_ALE() \n\n"
         << "This suggests that you've either tried to call it for an element\n"
         << "that \n"
         << "(1) does not involve time-derivatives (e.g. a Poisson element) \n"
         << "(2) an element for which the time-derivatives aren't implemented \n"
         << "    in ALE form \n"
         << "(3) an element for which the ALE form of the equations can't be \n"
         << "    be disabled (yet).\n";
       OomphLibWarning(
         warn_message.str(), "Problem::disable_ALE()", OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_EXCEPTION_LOCATION.
dJ_eulerian_at_knot()
double FiniteElement::dJ_eulerian_at_knot (const unsigned & ipt, Shape & psi, DenseMatrix< double > & djacobian_dX) const
Compute the geometric shape functions (psi) at integration point ipt. Return the determinant of the jacobian of the mapping (detJ). Additionally calculate the derivatives of "detJ" w.r.t. the nodal coordinates.
   {
     // Find the element dimension
     const unsigned el_dim = dim();
     // Get the values of the shape function and local derivatives
     unsigned nnod = nnode();
     DShape dpsi(nnod, el_dim);
     dshape_local_at_knot(ipt, psi, dpsi);
     // Allocate memory for the jacobian and the inverse of the jacobian
     DenseMatrix<double> jacobian(el_dim), inverse_jacobian(el_dim);
     // Now calculate the inverse jacobian
     const double det =
       local_to_eulerian_mapping(dpsi, jacobian, inverse_jacobian);
     // Calculate the derivative of the jacobian w.r.t. nodal coordinates
     // Note: must call this before "transform_derivatives(...)" since this
     // function requires dpsids rather than dpsidx
     dJ_eulerian_dnodal_coordinates(jacobian, dpsi, djacobian_dX);
     // Return the determinant of the jacobian
     return det;
   }
References dim(), dJ_eulerian_dnodal_coordinates(), dshape_local_at_knot(), el_dim, local_to_eulerian_mapping(), and nnode().
dJ_eulerian_dnodal_coordinates()
void FiniteElement::dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > & jacobian, const DShape & dpsids, DenseMatrix< double > & djacobian_dX) const protected virtual
A template-free interface that calculates the derivative of the jacobian of a mapping with respect to the nodal coordinates X_ij. To do this it requires the jacobian matrix and the derivatives of the shape functions w.r.t. the local coordinates. By default the function will use the dimension of the element to call the correct dJ_eulerian_dnodal_coordinates_templated_helper(..) function. This should be overloaded for efficiency (removal of a switch statement) in specific elements.
Template-free interface calculating the derivative of the jacobian of a mapping with respect to the nodal coordinates X_ij. This is slightly inefficient, given that it uses a switch statement. It can always be overloaded in specific geometric elements, for efficiency reasons.
   {
     // Determine the spatial dimension of the element
     const unsigned el_dim = dim();
 #ifdef PARANOID
     // Determine the number of nodes in the element
     const unsigned n_node = nnode();
     // Check that djacobian_dX has the correct number of rows (= el_dim)
     if (djacobian_dX.nrow() != el_dim)
     {
       std::ostringstream error_message;
       error_message << "djacobian_dX must have the same number of rows as the"
                     << "\nspatial dimension of the element.";
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
     // Check that djacobian_dX has the correct number of columns (= n_node)
     if (djacobian_dX.ncol() != n_node)
     {
       std::ostringstream error_message;
       error_message
         << "djacobian_dX must have the same number of columns as the"
         << "\nnumber of nodes in the element.";
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Call the appropriate templated function, depending on the
     // element dimension
     switch (el_dim)
     {
       case 0:
         dJ_eulerian_dnodal_coordinates_templated_helper<0>(
           jacobian, dpsids, djacobian_dX);
         break;
       case 1:
         dJ_eulerian_dnodal_coordinates_templated_helper<1>(
           jacobian, dpsids, djacobian_dX);
         break;
       case 2:
         dJ_eulerian_dnodal_coordinates_templated_helper<2>(
           jacobian, dpsids, djacobian_dX);
         break;
       case 3:
         dJ_eulerian_dnodal_coordinates_templated_helper<3>(
           jacobian, dpsids, djacobian_dX);
         break;
         // Catch-all default case: issue warning and die
       default:
         std::ostringstream error_stream;
         error_stream << "Dimension of the element must be 0,1,2 or 3, not "
                      << el_dim << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
   }
References dim(), el_dim, oomph::DenseMatrix< T >::ncol(), nnode(), oomph::DenseMatrix< T >::nrow(), OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by dJ_eulerian_at_knot(), dshape_eulerian_at_knot(), oomph::AxisymmetricNavierStokesEquations::interpolated_d_dudx_dX_axi_nst(), and oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::interpolated_d_dudx_dX_axi_nst().
dJ_eulerian_dnodal_coordinates_templated_helper() [1/5]
template<> void oomph::FiniteElement::dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > & jacobian, const DShape & dpsids, DenseMatrix< double > & djacobian_dX) const protected
Zero-d specialisation of function to calculate the derivative of the jacobian of a mapping with respect to the nodal coordinates X_ij.
   {
     // Issue a warning
     oomph_info << "\nWarning: You are trying to calculate derivatives of "
                << "a jacobian w.r.t. nodal coordinates for a 'point' "
                << "element." << std::endl
                << "This makes no sense and is almost certainly an error."
                << std::endl
                << std::endl;
   }
References oomph::oomph_info.
dJ_eulerian_dnodal_coordinates_templated_helper() [2/5]
template<> void oomph::FiniteElement::dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > & jacobian, const DShape & dpsids, DenseMatrix< double > & djacobian_dX) const protected
One-d specialisation of function to calculate the derivative of the jacobian of a mapping with respect to the nodal coordinates X_ij.
   {
     // Determine the number of nodes in the element
     const unsigned n_node = nnode();
     // Loop over nodes
     for (unsigned j = 0; j < n_node; j++)
     {
       djacobian_dX(0, j) = dpsids(j, 0);
     }
   }
References j, and nnode().
dJ_eulerian_dnodal_coordinates_templated_helper() [3/5]
template<> void oomph::FiniteElement::dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > & jacobian, const DShape & dpsids, DenseMatrix< double > & djacobian_dX) const protected
Two-d specialisation of function to calculate the derivative of the jacobian of a mapping with respect to the nodal coordinates X_ij.
   {
     // Determine the number of nodes in the element
     const unsigned n_node = nnode();
     // Loop over nodes
     for (unsigned j = 0; j < n_node; j++)
     {
       // i=0
       djacobian_dX(0, j) =
         dpsids(j, 0) * jacobian(1, 1) - dpsids(j, 1) * jacobian(0, 1);
       // i=1
       djacobian_dX(1, j) =
         dpsids(j, 1) * jacobian(0, 0) - dpsids(j, 0) * jacobian(1, 0);
     }
   }
References j, and nnode().
dJ_eulerian_dnodal_coordinates_templated_helper() [4/5]
template<> void oomph::FiniteElement::dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > & jacobian, const DShape & dpsids, DenseMatrix< double > & djacobian_dX) const protected
Three-d specialisation of function to calculate the derivative of the jacobian of a mapping with respect to the nodal coordinates X_ij.
   {
     // Determine the number of nodes in the element
     const unsigned n_node = nnode();
     // Loop over nodes
     for (unsigned j = 0; j < n_node; j++)
     {
       // i=0
       djacobian_dX(0, j) =
         dpsids(j, 0) *
           (jacobian(1, 1) * jacobian(2, 2) - jacobian(1, 2) * jacobian(2, 1)) +
         dpsids(j, 1) *
           (jacobian(0, 2) * jacobian(2, 1) - jacobian(0, 1) * jacobian(2, 2)) +
         dpsids(j, 2) *
           (jacobian(0, 1) * jacobian(1, 2) - jacobian(0, 2) * jacobian(1, 1));
       // i=1
       djacobian_dX(1, j) =
         dpsids(j, 0) *
           (jacobian(1, 2) * jacobian(2, 0) - jacobian(1, 0) * jacobian(2, 2)) +
         dpsids(j, 1) *
           (jacobian(0, 0) * jacobian(2, 2) - jacobian(0, 2) * jacobian(2, 0)) +
         dpsids(j, 2) *
           (jacobian(0, 2) * jacobian(1, 0) - jacobian(0, 0) * jacobian(1, 2));
       // i=2
       djacobian_dX(2, j) =
         dpsids(j, 0) *
           (jacobian(1, 0) * jacobian(2, 1) - jacobian(1, 1) * jacobian(2, 0)) +
         dpsids(j, 1) *
           (jacobian(0, 1) * jacobian(2, 0) - jacobian(0, 0) * jacobian(2, 1)) +
         dpsids(j, 2) *
           (jacobian(0, 0) * jacobian(1, 1) - jacobian(0, 1) * jacobian(1, 0));
     }
   }
References j, and nnode().
dJ_eulerian_dnodal_coordinates_templated_helper() [5/5]
template<unsigned DIM> void oomph::FiniteElement::dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > & jacobian, const DShape & dpsids, DenseMatrix< double > & djacobian_dX) const protected
Calculate the derivative of the jacobian of a mapping with respect to the nodal coordinates X_ij using the jacobian matrix and the derivatives of the shape functions w.r.t. the local coordinates. This function is templated by the dimension of the element.
dnodal_position_dt() [1/2]
double oomph::FiniteElement::dnodal_position_dt (const unsigned & n, const unsigned & i) const inline
Return the i-th component of nodal velocity: dx/dt at local node n.
     {
       return node_pt(n)->dposition_dt(i);
     }
References oomph::Node::dposition_dt(), i, n, and node_pt().
Referenced by oomph::SurfactantTransportInterfaceElement::add_additional_residual_contributions_interface(), oomph::SphericalNavierStokesEquations::d_kin_energy_dt(), oomph::LinearisedAxisymmetricNavierStokesEquations::dkin_energy_dt(), oomph::RefineableAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_cons_axisym_adv_diff(), oomph::FluidInterfaceElement::fill_in_generic_residual_contribution_interface(), oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::RefineableSphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst(), oomph::PolarNavierStokesEquations::full_output(), oomph::SphericalNavierStokesEquations::full_output(), oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), and oomph::MyTaylorHoodElement< DIM >::output().
dnodal_position_dt() [2/2]
double oomph::FiniteElement::dnodal_position_dt (const unsigned & n, const unsigned & j, const unsigned & i) const inline
Return the i-th component of j-th derivative of nodal position: d^jx/dt^j at node n.
     {
       return node_pt(n)->dposition_dt(j, i);
     }
References oomph::Node::dposition_dt(), i, j, n, and node_pt().
dnodal_position_gen_dt() [1/2]
double oomph::FiniteElement::dnodal_position_gen_dt (const unsigned & j, const unsigned & n, const unsigned & k, const unsigned & i) const inline
i-th component of j-th time derivative of the generalised position, dx(k,i)/dt at local node n. ‘Type’: k; Coordinate direction: i.
     {
       return node_pt(n)->dposition_gen_dt(j, k, i);
     }
References oomph::Node::dposition_gen_dt(), i, j, k, n, and node_pt().
dnodal_position_gen_dt() [2/2]
double oomph::FiniteElement::dnodal_position_gen_dt (const unsigned & n, const unsigned & k, const unsigned & i) const inline
i-th component of time derivative (velocity) of the generalised position, dx(k,i)/dt at local node n. ‘Type’: k; Coordinate direction: i.
     {
       return node_pt(n)->dposition_gen_dt(k, i);
     }
References oomph::Node::dposition_gen_dt(), i, k, n, and node_pt().
Referenced by oomph::RefineableQDPVDElement< DIM, NNODE_1D >::fill_in_generic_contribution_to_residuals_pvd(), oomph::KirchhoffLoveShellEquations::get_energy(), interpolated_dxdt(), and oomph::KirchhoffLoveShellEquations::load_rate_of_work().
dposition_dt()
void oomph::FiniteElement::dposition_dt (const Vector< double > & zeta, const unsigned & t, Vector< double > & drdt) inline virtual
Return the t-th time derivative of the parametrised position of the FiniteElement in its GeomObject incarnation: \(\frac{d^{t} dr(zeta)}{d t^{t}} \). Call the t-th time derivative of the FE-interpolated Eulerian coordinate
Reimplemented from oomph::GeomObject.
     {
       this->interpolated_dxdt(zeta, t, drdt);
     }
References interpolated_dxdt(), and plotPSD::t.
dshape_eulerian()
double FiniteElement::dshape_eulerian (const Vector< double > & s, Shape & psi, DShape & dpsi) const
Compute the geometric shape functions and also first derivatives w.r.t. global coordinates at local coordinate s; Returns Jacobian of mapping from global to local coordinates.
Compute the geometric shape functions and also first derivatives w.r.t. global coordinates at local coordinate s; Returns Jacobian of mapping from global to local coordinates. Most general form of the function, but may be over-loaded, if desired
   {
     // Find the element dimension
     const unsigned el_dim = dim();
     // Get the values of the shape functions and their local derivatives
     // Temporarily stored in dpsi
     dshape_local(s, psi, dpsi);
     // Allocate memory for the inverse jacobian
     DenseMatrix<double> inverse_jacobian(el_dim);
     // Now calculate the inverse jacobian
     const double det = local_to_eulerian_mapping(dpsi, inverse_jacobian);
     // Now set the values of the derivatives to be dpsidx
     transform_derivatives(inverse_jacobian, dpsi);
     // Return the determinant of the jacobian
     return det;
   }
References dim(), dshape_local(), el_dim, local_to_eulerian_mapping(), s, and transform_derivatives().
Referenced by oomph::Mesh::check_inverted_elements(), oomph::AxisymmetricQCrouzeixRaviartElement::dshape_and_dtest_eulerian_axi_nst(), oomph::AxisymmetricQTaylorHoodElement::dshape_and_dtest_eulerian_axi_nst(), oomph::AxisymmetricTCrouzeixRaviartElement::dshape_and_dtest_eulerian_axi_nst(), oomph::AxisymmetricTTaylorHoodElement::dshape_and_dtest_eulerian_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement::dshape_and_dtest_eulerian_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricQTaylorHoodElement::dshape_and_dtest_eulerian_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::dshape_and_dtest_eulerian_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::dshape_and_dtest_eulerian_axi_nst(), oomph::LinearisedAxisymmetricQCrouzeixRaviartElement::dshape_and_dtest_eulerian_lin_axi_nst(), oomph::LinearisedAxisymmetricQTaylorHoodElement::dshape_and_dtest_eulerian_lin_axi_nst(), oomph::LinearisedAxisymmetricQCrouzeixRaviartElement::dshape_and_dtest_eulerian_linearised_axi_nst(), oomph::LinearisedAxisymmetricQTaylorHoodElement::dshape_and_dtest_eulerian_linearised_axi_nst(), oomph::LinearisedQCrouzeixRaviartElement::dshape_and_dtest_eulerian_linearised_nst(), oomph::LinearisedQTaylorHoodElement::dshape_and_dtest_eulerian_linearised_nst(), oomph::PolarStreamfunctionElement::dshape_and_dtest_eulerian_poisson(), oomph::QSphericalCrouzeixRaviartElement::dshape_and_dtest_eulerian_spherical_nst(), oomph::QSphericalTaylorHoodElement::dshape_and_dtest_eulerian_spherical_nst(), oomph::PerturbedSpineLinearisedAxisymmetricFluidInterfaceElement< ELEMENT >::fill_in_generic_residual_contribution_interface(), oomph::PolarNavierStokesEquations::full_output(), oomph::SphericalNavierStokesEquations::full_output(), oomph::PoissonEquations< DIM >::get_dflux_dnodal_u(), oomph::PolarStreamfunctionEquations::get_flux(), oomph::AdvectionDiffusionEquations< DIM >::get_flux(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::get_flux(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::get_flux(), oomph::AxisymAdvectionDiffusionEquations::get_flux(), oomph::LinearWaveEquations< DIM >::get_flux(), oomph::PoissonEquations< DIM >::get_flux(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::get_flux(), oomph::SphericalAdvectionDiffusionEquations::get_flux(), oomph::SteadyAxisymAdvectionDiffusionEquations::get_flux(), oomph::UnsteadyHeatEquations< DIM >::get_flux(), oomph::WomersleyEquations< DIM >::get_flux(), oomph::YoungLaplaceEquations::get_flux(), oomph::FourierDecomposedHelmholtzEquations::get_flux(), oomph::HelmholtzEquations< DIM >::get_flux(), oomph::PMLFourierDecomposedHelmholtzEquations::get_flux(), oomph::PMLHelmholtzEquations< DIM >::get_flux(), oomph::AxisymFoepplvonKarmanEquations::get_gradient_of_deflection(), oomph::DisplacementBasedFoepplvonKarmanEquations::get_gradient_of_deflection(), oomph::FoepplvonKarmanEquations::get_gradient_of_deflection(), oomph::DisplacementBasedFoepplvonKarmanEquations::get_gradient_of_field(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::get_strain(), oomph::DisplacementBasedFoepplvonKarmanEquations::get_stress_and_strain_for_output(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::get_total_flux(), oomph::SphericalNavierStokesEquations::get_vorticity(), oomph::SpectralPeriodicOrbitElement< NNODE_1D >::get_Z2_flux(), oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::get_Z2_flux(), oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >::get_Z2_flux(), oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::get_Z2_flux(), oomph::RefineableSpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::get_Z2_flux(), oomph::AxisymmetricPoroelasticityEquations::interpolated_div_du_dt(), oomph::AxisymmetricPoroelasticityEquations::interpolated_div_u(), oomph::SpaceTimeNavierStokesEquations< DIM >::interpolated_du_dt_nst(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::interpolated_du_dt_ust_heat(), oomph::PolarStreamfunctionEquations::interpolated_dudx(), oomph::BiharmonicEquations< DIM >::interpolated_dudx(), oomph::AxisymmetricNavierStokesEquations::interpolated_dudx_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::interpolated_dudx_axi_nst(), oomph::NavierStokesEquations< DIM >::interpolated_dudx_nst(), oomph::PolarNavierStokesEquations::interpolated_dudx_pnst(), oomph::SphericalNavierStokesEquations::interpolated_dudx_spherical_nst(), oomph::AxisymFoepplvonKarmanEquations::interpolated_stress(), oomph::FoepplvonKarmanEquations::interpolated_stress(), oomph::ProjectableAxisymLinearElasticityElement< AXISYM_LINEAR_ELAST_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableLinearElasticityElement< LINEAR_ELAST_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectablePMLTimeHarmonicLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableTimeHarmonicFourierDecomposedLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableTimeHarmonicLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::jacobian_and_shape_of_field(), oomph::PeriodicOrbitEquations::orbit_output(), oomph::MyTaylorHoodElement< DIM >::output(), oomph::LinearisedAxisymmetricNavierStokesEquations::strain_rate(), oomph::AxisymmetricNavierStokesEquations::strain_rate(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::strain_rate(), oomph::PolarNavierStokesEquations::strain_rate(), oomph::SphericalNavierStokesEquations::strain_rate(), oomph::LinearisedNavierStokesEquations::strain_rate(), and oomph::PolarNavierStokesEquations::strain_rate_by_r().
dshape_eulerian_at_knot() [1/2]
double FiniteElement::dshape_eulerian_at_knot (const unsigned & ipt, Shape & psi, DShape & dpsi, DenseMatrix< double > & djacobian_dX, RankFourTensor< double > & d_dpsidx_dX) const virtual
Compute the geometric shape functions (psi) and first derivatives w.r.t. global coordinates (dpsidx) at the ipt-th integration point. Return the determinant of the jacobian of the mapping (detJ). Additionally calculate the derivatives of both "detJ" and "dpsidx" w.r.t. the nodal coordinates.
Compute the geometric shape functions (psi) and first derivatives w.r.t. global coordinates (dpsidx) at integration point ipt. Return the determinant of the jacobian of the mapping (detJ). Additionally calculate the derivatives of both "detJ" and "dpsidx" w.r.t. the nodal coordinates. Most general form of function, but may be over-loaded if desired.
   {
     // Find the element dimension
     const unsigned el_dim = dim();
     // Get the values of the shape function and local derivatives
     // Temporarily store in dpsi
     dshape_local_at_knot(ipt, psi, dpsi);
     // Allocate memory for the jacobian and the inverse of the jacobian
     DenseMatrix<double> jacobian(el_dim), inverse_jacobian(el_dim);
     // Now calculate the inverse jacobian
     const double det =
       local_to_eulerian_mapping(dpsi, jacobian, inverse_jacobian);
     // Calculate the derivative of the jacobian w.r.t. nodal coordinates
     // Note: must call this before "transform_derivatives(...)" since this
     // function requires dpsids rather than dpsidx
     dJ_eulerian_dnodal_coordinates(jacobian, dpsi, djacobian_dX);
     // Calculate the derivative of dpsidx w.r.t. nodal coordinates
     // Note: this function also requires dpsids rather than dpsidx
     d_dshape_eulerian_dnodal_coordinates(
       det, jacobian, djacobian_dX, inverse_jacobian, dpsi, d_dpsidx_dX);
     // Now set the values of the derivatives to dpsidx
     transform_derivatives(inverse_jacobian, dpsi);
     // Return the determinant of the jacobian
     return det;
   }
References d_dshape_eulerian_dnodal_coordinates(), dim(), dJ_eulerian_dnodal_coordinates(), dshape_local_at_knot(), el_dim, local_to_eulerian_mapping(), and transform_derivatives().
dshape_eulerian_at_knot() [2/2]
double FiniteElement::dshape_eulerian_at_knot (const unsigned & ipt, Shape & psi, DShape & dpsi) const virtual
Return the geometric shape functions and also first derivatives w.r.t. global coordinates at the ipt-th integration point.
Compute the geometric shape functions and also first derivatives w.r.t. global coordinates at integration point ipt. Most general form of function, but may be over-loaded if desired
Reimplemented in HarmonicEquations, OrrSommerfeldEquations< DIM >, HarmonicEquations, ComplexHarmonicEquations, oomph::StorableShapeElementBase, QHarmonicElement< NNODE_1D >, QOrrSommerfeldElement< 1, NNODE_1D >, QHarmonicElement< NNODE_1D >, and QComplexHarmonicElement< NNODE_1D >.
   {
     // Find the element dimension
     const unsigned el_dim = dim();
     // Get the values of the shape function and local derivatives
     // Temporarily store it in dpsi
     dshape_local_at_knot(ipt, psi, dpsi);
     // Allocate memory for the inverse jacobian
     DenseMatrix<double> inverse_jacobian(el_dim);
     // Now calculate the inverse jacobian
     const double det = local_to_eulerian_mapping(dpsi, inverse_jacobian);
     // Now set the values of the derivatives to dpsidx
     transform_derivatives(inverse_jacobian, dpsi);
     // Return the determinant of the jacobian
     return det;
   }
References dim(), dshape_local_at_knot(), el_dim, local_to_eulerian_mapping(), and transform_derivatives().
Referenced by check_J_eulerian_at_knots(), oomph::EulerEquations< DIM >::compute_error(), oomph::ScalarAdvectionEquations< DIM >::compute_error(), oomph::SphericalNavierStokesEquations::d_kin_energy_dt(), oomph::LinearisedAxisymmetricQCrouzeixRaviartElement::dshape_and_dtest_eulerian_and_dnodal_coordinates_at_knot_lin_axi_nst(), oomph::LinearisedAxisymmetricQTaylorHoodElement::dshape_and_dtest_eulerian_and_dnodal_coordinates_at_knot_lin_axi_nst(), oomph::AxisymmetricQCrouzeixRaviartElement::dshape_and_dtest_eulerian_at_knot_axi_nst(), oomph::AxisymmetricQTaylorHoodElement::dshape_and_dtest_eulerian_at_knot_axi_nst(), oomph::AxisymmetricTCrouzeixRaviartElement::dshape_and_dtest_eulerian_at_knot_axi_nst(), oomph::AxisymmetricTTaylorHoodElement::dshape_and_dtest_eulerian_at_knot_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement::dshape_and_dtest_eulerian_at_knot_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricQTaylorHoodElement::dshape_and_dtest_eulerian_at_knot_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::dshape_and_dtest_eulerian_at_knot_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::dshape_and_dtest_eulerian_at_knot_axi_nst(), oomph::LinearisedAxisymmetricQCrouzeixRaviartElement::dshape_and_dtest_eulerian_at_knot_lin_axi_nst(), oomph::LinearisedAxisymmetricQTaylorHoodElement::dshape_and_dtest_eulerian_at_knot_lin_axi_nst(), oomph::LinearisedAxisymmetricQCrouzeixRaviartElement::dshape_and_dtest_eulerian_at_knot_linearised_axi_nst(), oomph::LinearisedAxisymmetricQTaylorHoodElement::dshape_and_dtest_eulerian_at_knot_linearised_axi_nst(), oomph::LinearisedQCrouzeixRaviartElement::dshape_and_dtest_eulerian_at_knot_linearised_nst(), oomph::LinearisedQTaylorHoodElement::dshape_and_dtest_eulerian_at_knot_linearised_nst(), oomph::PolarStreamfunctionElement::dshape_and_dtest_eulerian_at_knot_poisson(), oomph::QSphericalCrouzeixRaviartElement::dshape_and_dtest_eulerian_at_knot_spherical_nst(), oomph::QSphericalTaylorHoodElement::dshape_and_dtest_eulerian_at_knot_spherical_nst(), oomph::StorableShapeElementBase::dshape_eulerian_at_knot(), oomph::RefineableYoungLaplaceEquations::fill_in_contribution_to_residuals(), oomph::YoungLaplaceEquations::fill_in_contribution_to_residuals(), oomph::AxisymmetricLinearElasticityEquations::fill_in_generic_contribution_to_residuals_axisymmetric_linear_elasticity(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::fill_in_generic_contribution_to_residuals_fourier_decomp_time_harmonic_linear_elasticity(), oomph::FoepplvonKarmanEquations::get_bounded_volume(), oomph::StorableShapeElementBase::pre_compute_dshape_eulerian_at_knots(), self_test(), and oomph::MyTaylorHoodElement< DIM >::square_of_l2_norm().
dshape_local()
virtual void oomph::FiniteElement::dshape_local (const Vector< double > & s, Shape & psi, DShape & dpsids) const inline virtual
Function to compute the geometric shape functions and derivatives w.r.t. local coordinates at local coordinate s. This function must be overloaded for each specific geometric element. (Broken virtual function — specifies the interface)
Reimplemented in oomph::ClampedHermiteShellBoundaryConditionElement, oomph::TElement< 3, NNODE_1D >, oomph::TElement< 2, NNODE_1D >, oomph::TElement< 1, NNODE_1D >, oomph::QSpectralElement< 3, NNODE_1D >, oomph::QSpectralElement< 2, NNODE_1D >, oomph::QSpectralElement< 1, NNODE_1D >, oomph::QElement< 3, NNODE_1D >, oomph::QElement< 2, NNODE_1D >, oomph::QElement< 1, NNODE_1D >, oomph::QHermiteElement< DIM >, oomph::QHermiteElement< DIM - 1 >, oomph::QHermiteElement< DIM >, oomph::QHermiteElement< DIM - 1 >, oomph::QHermiteElement< DIM >, oomph::QHermiteElement< DIM - 1 >, TwoNodeGeometricElement, FixSpineHeightElement, FixSpineHeightElement, oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >, oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >, and oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >.
     {
       throw OomphLibError(
         "dshape_local() is not implemented for this element\n",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::HelmholtzBCElementBase< ELEMENT >::compute_contribution_to_fourier_components(), oomph::FaceElement::continuous_tangent_and_outer_unit_normal(), oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >::d_shape_and_test_local(), oomph::HelmholtzBCElementBase< ELEMENT >::d_shape_and_test_local(), oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::d_shape_and_test_local(), oomph::AxisymmetricTCrouzeixRaviartElement::dpshape_and_dptest_eulerian_axi_nst(), oomph::AxisymmetricTTaylorHoodElement::dpshape_and_dptest_eulerian_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::dpshape_and_dptest_eulerian_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::dpshape_and_dptest_eulerian_axi_nst(), dshape_eulerian(), oomph::SolidFiniteElement::dshape_lagrangian(), dshape_local_at_knot(), oomph::LineFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary(), oomph::KirchhoffLoveBeamEquations::get_non_unit_tangent(), oomph::AxisymmetricNavierStokesEquations::interpolated_d_dudx_dX_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::interpolated_d_dudx_dX_axi_nst(), oomph::AxisymmetricPoroelasticityEquations::interpolated_div_q(), oomph::DarcyEquations< DIM >::interpolated_div_q(), oomph::PoroelasticityEquations< DIM >::interpolated_div_q(), oomph::AxisymmetricNavierStokesEquations::interpolated_duds_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::interpolated_duds_axi_nst(), oomph::SolidFiniteElement::interpolated_dxids(), J_eulerian(), oomph::FaceElement::J_eulerian(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::lagrangian_eulerian_translation_factor(), locate_zeta(), oomph::FaceElement::outer_unit_normal(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::output(), and oomph::AxisymmetricPoroelasticityEquations::transform_basis().
dshape_local_at_knot()
void FiniteElement::dshape_local_at_knot (const unsigned & ipt, Shape & psi, DShape & dpsids) const virtual
Return the geometric shape function and its derivative w.r.t. the local coordinates at the ipt-th integration point.
Return the shape function and its derivatives w.r.t. the local coordinates at the ipt-th integration point.
Reimplemented in oomph::StorableShapeElementBase.
   {
     // Find the dimension of the element
     const unsigned el_dim = dim();
     // Storage for the local coordinates of the integration point
     Vector<double> s(el_dim);
     // Set the local coordinate
     for (unsigned i = 0; i < el_dim; i++)
     {
       s[i] = integral_pt()->knot(ipt, i);
     }
     // Get the shape function and derivatives
     dshape_local(s, psi, dpsids);
   }
References dim(), dshape_local(), el_dim, i, integral_pt(), oomph::Integral::knot(), and s.
Referenced by oomph::FaceElement::check_J_eulerian_at_knots(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::contribution_to_enclosed_volume(), oomph::LineVolumeConstraintBoundingElement::contribution_to_enclosed_volume(), oomph::AxisymmetricVolumeConstraintBoundingElement::contribution_to_enclosed_volume(), oomph::StefanBoltzmannRadiationBase::contribution_to_stefan_boltzmann_radiation(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::contribution_to_total_porous_flux(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::contribution_to_total_porous_flux(), oomph::AxisymmetricVolumeConstraintBoundingElement::contribution_to_volume_flux(), dJ_eulerian_at_knot(), oomph::LinearisedAxisymmetricNavierStokesEquations::dkin_energy_dt(), dshape_eulerian_at_knot(), oomph::SolidFiniteElement::dshape_lagrangian_at_knot(), oomph::StorableShapeElementBase::dshape_local_at_knot(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), oomph::FluidInterfaceElement::fill_in_generic_residual_contribution_interface(), oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_lin_axi_nst(), oomph::LineVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint(), oomph::AxisymmetricVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint(), oomph::SurfaceVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint(), oomph::SurfactantTransportInterfaceElement::integrate_c(), J_eulerian_at_knot(), oomph::FaceElement::J_eulerian_at_knot(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::output(), oomph::StorableShapeElementBase::pre_compute_dshape_local_at_knots(), oomph::RefineableImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::RefineableFSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), and oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::square_of_l2_norm_of_error().
element_geometry()
virtual ElementGeometry::ElementGeometry oomph::FiniteElement::element_geometry () const inline virtual
Return the geometry type of the element (either Q or T usually).
Reimplemented in oomph::TElementBase, and oomph::QElementBase.
     {
       std::string err = "Broken virtual function.";
       throw OomphLibError(
         err, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
enable_ALE()
virtual void oomph::FiniteElement::enable_ALE () inline virtual
(Re-)enable ALE, i.e. take possible mesh motion into account when evaluating the time-derivative. This function is empty and simply establishes a common interface for all derived elements that are formulated in ALE form.
Reimplemented in oomph::UnsteadyHeatEquations< DIM >, oomph::UnsteadyHeatEquations< 2 >, oomph::SphericalNavierStokesEquations, oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< 2 >, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< 2 >, oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::NavierStokesEquations< DIM >, oomph::NavierStokesEquations< 2 >, oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >, oomph::BuoyantQCrouzeixRaviartElement< DIM >, oomph::LinearisedNavierStokesEquations, oomph::LinearisedAxisymmetricNavierStokesEquations, oomph::GeneralisedNewtonianNavierStokesEquations< DIM >, oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations, oomph::AxisymmetricNavierStokesEquations, oomph::AxisymAdvectionDiffusionEquations, oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >, oomph::GeneralisedAdvectionDiffusionEquations< DIM >, oomph::GeneralisedAdvectionDiffusionEquations< 2 >, oomph::AdvectionDiffusionEquations< DIM >, oomph::AdvectionDiffusionEquations< 2 >, oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::AxisymmetricQAdvectionCrouzeixRaviartElement, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement, oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement, RefineableBuoyantQCrouzeixRaviartElement< DIM >, oomph::LinearisedAxisymmetricNavierStokesEquations, and oomph::LinearisedAxisymmetricNavierStokesEquations.
     {
       std::ostringstream warn_message;
       warn_message
         << "Warning: You have just called the default (empty) function \n\n"
         << "    FiniteElement::enable_ALE() \n\n"
         << "This suggests that you've either tried to call it for an element\n"
         << "that \n"
         << "(1) does not involve time-derivatives (e.g. a Poisson element) \n"
         << "(2) an element for which the time-derivatives aren't implemented \n"
         << "    in ALE form \n"
         << "(3) an element for which the ALE form of the equations can't be \n"
         << "    be disabled (yet)\n"
         << "(4) an element for which this function has not been (properly) \n "
         << "    implemented. This is likely to be a bug!\n ";
       OomphLibWarning(
         warn_message.str(), "Problem::enable_ALE()", OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement::enable_ALE().
face_node_number_error_check()
void oomph::FiniteElement::face_node_number_error_check (const unsigned & i) const inline
Range check for face node numbers.
     {
 #ifdef RANGE_CHECKING
       if (i > nnode_on_face())
       {
         std::string err = "Face node index i out of range on face.";
         throw OomphLibError(
           err, OOMPH_EXCEPTION_LOCATION, OOMPH_CURRENT_FUNCTION);
       }
 #endif
     }
References i, nnode_on_face(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
face_outer_unit_normal_sign()
virtual int oomph::FiniteElement::face_outer_unit_normal_sign (const int & face_index) const inline virtual
Get the sign of the outer unit normal on the face given by face_index.
Reimplemented in oomph::QElement< 3, NNODE_1D >, oomph::QElement< 2, NNODE_1D >, and oomph::QElement< 1, NNODE_1D >.
     {
       std::string err = "Not implemented for this element.";
       throw OomphLibError(
         err, OOMPH_EXCEPTION_LOCATION, OOMPH_CURRENT_FUNCTION);
     }
References OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
Referenced by build_face_element().
face_to_bulk_coordinate_fct_pt()
virtual CoordinateMappingFctPt oomph::FiniteElement::face_to_bulk_coordinate_fct_pt (const int & face_index) const inline virtual
Get a pointer to the function mapping face coordinates to bulk coordinates
Reimplemented in oomph::QElement< 3, NNODE_1D >, oomph::QElement< 2, NNODE_1D >, and oomph::QElement< 1, NNODE_1D >.
     {
       std::string err = "Not implemented for this element.";
       throw OomphLibError(
         err, OOMPH_EXCEPTION_LOCATION, OOMPH_CURRENT_FUNCTION);
     }
References OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
Referenced by build_face_element().
fill_in_contribution_to_jacobian()
void oomph::FiniteElement::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline protected virtual
Add the elemental contribution to the jacobian matrix. and the residuals vector. Note that this function will NOT initialise the residuals vector or the jacobian matrix. It must be called after the residuals vector and jacobian matrix have been initialised to zero. The default is to use finite differences to calculate the jacobian
Reimplemented from oomph::GeneralisedElement.
Reimplemented in oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >, oomph::WomersleyEquations< DIM >, oomph::UnsteadyHeatFluxElement< ELEMENT >, oomph::UnsteadyHeatEquations< DIM >, oomph::UnsteadyHeatEquations< 2 >, oomph::TimeHarmonicLinearElasticityTractionElement< ELEMENT >, oomph::TimeHarmonicLinearElasticityEquations< DIM >, oomph::TimeHarmonicFourierDecomposedLinearElasticityTractionElement< ELEMENT >, oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations, oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >, oomph::SteadyAxisymAdvectionDiffusionEquations, oomph::SphericalNavierStokesEquations, oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >, oomph::SphericalAdvectionDiffusionEquations, oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< 2 >, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< 2 >, oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >, oomph::FpPressureAdvDiffRobinBCMixedOrderSpaceTimeElement< ELEMENT >, oomph::RefineableNavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >, oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >, oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >, oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >, oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >, oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >, oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >, oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >, oomph::RefineableFSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >, oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >, oomph::RefineableImposeDisplacementByLagrangeMultiplierElement< ELEMENT >, oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >, oomph::RefineableFSISolidTractionElement< ELEMENT, DIM >, oomph::FSISolidTractionElement< ELEMENT, DIM >, oomph::RefineableSolidTractionElement< ELEMENT >, oomph::SolidTractionElement< ELEMENT >, oomph::PVDEquationsWithPressure< DIM >, oomph::PVDEquations< DIM >, oomph::FSIDiagHermiteShellElement, oomph::KirchhoffLoveShellEquations, oomph::PoroelasticityFaceElement< ELEMENT >, oomph::PoroelasticityEquations< DIM >, oomph::PoroelasticityEquations< 2 >, oomph::PolarStressIntegralElement< ELEMENT >, oomph::PolarNavierStokesEquations, oomph::PolarNavierStokesTractionElement< ELEMENT >, oomph::PoissonFluxElement< ELEMENT >, oomph::PoissonEquations< DIM >, oomph::PoissonEquations< 1 >, oomph::PoissonEquations< 2 >, oomph::PoissonEquations< 3 >, oomph::PMLTimeHarmonicLinearElasticityTractionElement< ELEMENT >, oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >, oomph::PMLHelmholtzFluxElement< ELEMENT >, oomph::PMLHelmholtzEquations< DIM >, oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >, oomph::PMLFourierDecomposedHelmholtzEquations, oomph::RefineableNavierStokesFluxControlElement< ELEMENT >, oomph::NavierStokesFluxControlElement< ELEMENT >, oomph::NavierStokesEquations< DIM >, oomph::NavierStokesEquations< 2 >, oomph::FpPressureAdvDiffRobinBCElement< ELEMENT >, oomph::ImposeParallelOutflowElement< ELEMENT >, oomph::ImposeImpenetrabilityElement< ELEMENT >, oomph::RefineableNavierStokesTractionElement< ELEMENT >, oomph::NavierStokesTractionElement< ELEMENT >, oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >, oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >, oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >, oomph::NavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >, oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >, oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >, oomph::HelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >, oomph::TimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >, oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >, oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >, oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >, oomph::BuoyantQCrouzeixRaviartElement< DIM >, RefineableLinearisedQCrouzeixRaviartMultiDomainElement, RefineableLinearisedQTaylorHoodMultiDomainElement, LinearisedQCrouzeixRaviartMultiDomainElement, LinearisedQTaylorHoodMultiDomainElement, RefineableLinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, RefineableLinearisedAxisymmetricQTaylorHoodMultiDomainElement, LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, LinearisedAxisymmetricQTaylorHoodMultiDomainElement, oomph::LinearisedAxisymmetricNavierStokesEquations, oomph::LinearWaveFluxElement< ELEMENT >, oomph::LinearWaveEquations< DIM >, oomph::LinearElasticityTractionElement< ELEMENT >, oomph::LinearElasticityEquations< DIM >, oomph::HelmholtzFluxElement< ELEMENT >, oomph::HelmholtzEquations< DIM >, oomph::HelmholtzDtNBoundaryElement< ELEMENT >, oomph::HelmholtzAbsorbingBCElement< ELEMENT >, oomph::PseudoSolidNodeUpdateElement< TCrouzeixRaviartElement< 2 >, TPVDBubbleEnrichedElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< TTaylorHoodElement< 2 >, TPVDElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< GeneralisedNewtonianAxisymmetricTTaylorHoodElement, TPVDElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< AxisymmetricTTaylorHoodElement, TPVDElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< GeneralisedNewtonianTTaylorHoodElement< 2 >, TPVDElement< 2, 3 > >, oomph::ProjectableElement< ELEMENT >, oomph::ProjectableElement< FVK_ELEMENT >, oomph::ProjectableElement< AXISYM_LINEAR_ELAST_ELEMENT >, oomph::ProjectableElement< UNSTEADY_HEAT_ELEMENT >, oomph::ProjectableElement< LINEAR_ELAST_ELEMENT >, oomph::ProjectableElement< CROUZEIX_RAVIART_ELEMENT >, oomph::ProjectableElement< HELMHOLTZ_ELEMENT >, oomph::ProjectableElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >, oomph::ProjectableElement< TAYLOR_HOOD_ELEMENT >, oomph::ProjectableElement< PVD_ELEMENT >, oomph::ProjectableElement< ADR_ELEMENT >, oomph::ProjectableElement< DARCY_ELEMENT >, oomph::ProjectableElement< POISSON_ELEMENT >, oomph::ProjectableElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >, oomph::ProjectableElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >, oomph::ProjectableElement< LINEAR_HEAT_AND_ELAST_ELEMENT >, oomph::FSIWallElement, oomph::FaceElementAsGeomObject< ELEMENT >, oomph::SolidFiniteElement, oomph::ElasticUpdateFluidInterfaceElement< FluidInterfaceElement, SurfaceDerivatives, ELEMENT >, oomph::ElasticUpdateFluidInterfaceElement< SurfactantTransportInterfaceElement, AxisymmetricDerivatives, ELEMENT >, oomph::ElasticUpdateFluidInterfaceElement< FluidInterfaceElement, AxisymmetricDerivatives, ELEMENT >, oomph::ElasticUpdateFluidInterfaceElement< SolubleSurfactantTransportInterfaceElement, LineDerivatives, ELEMENT >, oomph::ElasticUpdateFluidInterfaceElement< FluidInterfaceElement, LineDerivatives, ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< SurfactantTransportInterfaceElement, LineDerivatives, ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< FluidInterfaceElement, SurfaceDerivatives, ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< SurfactantTransportInterfaceElement, AxisymmetricDerivatives, ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< SurfactantTransportInterfaceElement, SurfaceDerivatives, ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< FluidInterfaceElement, AxisymmetricDerivatives, ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< SolubleSurfactantTransportInterfaceElement, LineDerivatives, ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< FluidInterfaceElement, LineDerivatives, ELEMENT >, oomph::AxisymmetricPoroelasticityTractionElement< POROELASTICITY_BULK_ELEMENT >, oomph::GeneralisedAdvectionDiffusionEquations< 2 >, and oomph::AdvectionDiffusionEquations< 2 >.
     {
       // Add the contribution to the residuals
       fill_in_contribution_to_residuals(residuals);
       // Allocate storage for the full residuals (residuals of entire element)
       unsigned n_dof = ndof();
       Vector<double> full_residuals(n_dof);
       // Get the residuals for the entire element
       get_residuals(full_residuals);
       // Calculate the contributions from the internal dofs
       //(finite-difference the lot by default)
       fill_in_jacobian_from_internal_by_fd(full_residuals, jacobian, true);
       // Calculate the contributions from the external dofs
       //(finite-difference the lot by default)
       fill_in_jacobian_from_external_by_fd(full_residuals, jacobian, true);
       // Calculate the contributions from the nodal dofs
       fill_in_jacobian_from_nodal_by_fd(full_residuals, jacobian);
     }
References oomph::GeneralisedElement::fill_in_contribution_to_residuals(), oomph::GeneralisedElement::fill_in_jacobian_from_external_by_fd(), oomph::GeneralisedElement::fill_in_jacobian_from_internal_by_fd(), fill_in_jacobian_from_nodal_by_fd(), oomph::GeneralisedElement::get_residuals(), and oomph::GeneralisedElement::ndof().
Referenced by RefineableBuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_jacobian(), RefineableQCrouzeixRaviartElementWithExternalElement< DIM >::fill_in_contribution_to_jacobian(), oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::fill_in_contribution_to_jacobian(), RefineableQCrouzeixRaviartElementWithTwoExternalElement< DIM >::fill_in_contribution_to_jacobian(), RefineableQAdvectionDiffusionElementWithExternalElement< DIM >::fill_in_contribution_to_jacobian(), oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement::fill_in_contribution_to_jacobian(), LinearisedQTaylorHoodMultiDomainElement::fill_in_contribution_to_jacobian(), LinearisedQCrouzeixRaviartMultiDomainElement::fill_in_contribution_to_jacobian(), RefineableLinearisedQTaylorHoodMultiDomainElement::fill_in_contribution_to_jacobian(), RefineableLinearisedQCrouzeixRaviartMultiDomainElement::fill_in_contribution_to_jacobian(), oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_jacobian(), oomph::SolubleSurfactantTransportInterfaceElement::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::SurfactantTransportInterfaceElement::fill_in_contribution_to_jacobian_and_mass_matrix(), and oomph::DisplacementBasedFoepplvonKarmanEquations::fill_in_contribution_to_jacobian_and_mass_matrix().
fill_in_jacobian_from_nodal_by_fd() [1/2]
void oomph::FiniteElement::fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > & jacobian) inline protected
Calculate the contributions to the jacobian from the nodal degrees of freedom using finite differences. This version computes the residuals vector before calculating the jacobian terms.
     {
       // Allocate storage for a residuals vector and initialise to zero
       unsigned n_dof = ndof();
       Vector<double> residuals(n_dof, 0.0);
       // Get the residuals for the entire element
       get_residuals(residuals);
       // Call the jacobian calculation
       fill_in_jacobian_from_nodal_by_fd(residuals, jacobian);
     }
References fill_in_jacobian_from_nodal_by_fd(), oomph::GeneralisedElement::get_residuals(), and oomph::GeneralisedElement::ndof().
fill_in_jacobian_from_nodal_by_fd() [2/2]
void FiniteElement::fill_in_jacobian_from_nodal_by_fd (Vector< double > & residuals, DenseMatrix< double > & jacobian) protected virtual
Calculate the contributions to the jacobian from the nodal degrees of freedom using finite differences. This version of the function assumes that the residuals vector has already been calculated
This function calculates the entries of Jacobian matrix, used in the Newton method, associated with the nodal degrees of freedom. It does this using finite differences, rather than an analytical formulation, so can be done in total generality.
Reimplemented in oomph::RefineableElement.
   {
     // Find the number of nodes
     const unsigned n_node = nnode();
     // If there aren't any nodes, then return straight awayy
     if (n_node == 0)
     {
       return;
     }
     // Call the update function to ensure that the element is in
     // a consistent state before finite differencing starts
     update_before_nodal_fd();
     // Find the number of dofs in the element
     const unsigned n_dof = ndof();
     // Create newres vector
     Vector<double> newres(n_dof);
     // Integer storage for local unknown
     int local_unknown = 0;
     // Use the default finite difference step
     const double fd_step = Default_fd_jacobian_step;
     // Loop over the nodes
     for (unsigned n = 0; n < n_node; n++)
     {
       // Get the number of values stored at the node
       const unsigned n_value = node_pt(n)->nvalue();
       // Loop over the number of values
       for (unsigned i = 0; i < n_value; i++)
       {
         // Get the local equation number
         local_unknown = nodal_local_eqn(n, i);
         // If it's not pinned
         if (local_unknown >= 0)
         {
           // Store a pointer to the nodal data value
           double* const value_pt = node_pt(n)->value_pt(i);
           // Save the old value of the Nodal data
           const double old_var = *value_pt;
           // Increment the value of the Nodal data
           *value_pt += fd_step;
           // Now update any dependent variables
           update_in_nodal_fd(i);
           // Calculate the new residuals
           get_residuals(newres);
           // Do finite differences
           for (unsigned m = 0; m < n_dof; m++)
           {
             double sum = (newres[m] - residuals[m]) / fd_step;
             // Stick the entry into the Jacobian matrix
             jacobian(m, local_unknown) = sum;
           }
           // Reset the Nodal data
           *value_pt = old_var;
           // Reset any dependent variables
           reset_in_nodal_fd(i);
         }
       }
     }
     // End of finite difference loop
     // Final reset of any dependent data
     reset_after_nodal_fd();
   }
References oomph::GeneralisedElement::Default_fd_jacobian_step, oomph::GeneralisedElement::get_residuals(), i, m, n, oomph::GeneralisedElement::ndof(), nnode(), nodal_local_eqn(), node_pt(), oomph::Data::nvalue(), reset_after_nodal_fd(), reset_in_nodal_fd(), update_before_nodal_fd(), update_in_nodal_fd(), and oomph::Data::value_pt().
Referenced by oomph::ElementWithExternalElement::fill_in_contribution_to_jacobian(), fill_in_contribution_to_jacobian(), oomph::SolidFiniteElement::fill_in_contribution_to_jacobian(), oomph::FSIWallElement::fill_in_contribution_to_jacobian(), and fill_in_jacobian_from_nodal_by_fd().
geom_data_pt()
Data* oomph::FiniteElement::geom_data_pt (const unsigned & j) inline virtual
A standard FiniteElement is fixed, so there are no geometric data when viewed in its GeomObject incarnation
Reimplemented from oomph::GeomObject.
Reimplemented in oomph::RefineableSolidElement, oomph::FaceElementAsGeomObject< ELEMENT >, and oomph::SolidFiniteElement.
     {
       return 0;
     }
Referenced by oomph::ElementWithExternalElement::assign_external_interaction_data_local_eqn_numbers().
get_bulk_node_number()
virtual unsigned oomph::FiniteElement::get_bulk_node_number (const int & face_index, const unsigned & i) const inline virtual
Get the number of the ith node on face face_index (in the bulk node vector).
Reimplemented in oomph::TElement< 3, NNODE_1D >, oomph::TElement< 2, NNODE_1D >, oomph::QElement< 3, NNODE_1D >, oomph::QElement< 2, NNODE_1D >, and oomph::QElement< 1, NNODE_1D >.
     {
       std::string err = "Not implemented for this element.";
       throw OomphLibError(
         err, OOMPH_EXCEPTION_LOCATION, OOMPH_CURRENT_FUNCTION);
     }
References OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
Referenced by build_face_element().
get_centre_of_gravity_and_max_radius_in_terms_of_zeta()
void FiniteElement::get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > & cog, double & max_radius) const
Compute centre of gravity of all nodes and radius of node that is furthest from it. Used to assess approximately if a point is likely to be contained with an element in locate_zeta-like operations
Compute centre of gravity of all nodes and radius of node that is furthest from it. Used to assess approximately if a point is likely to be contained with an element in locate_zeta-like operations. NOTE: All computed in terms of zeta!
   {
     // Initialise
     cog.resize(Elemental_dimension);
     max_radius = 0.0;
     // Get cog
     unsigned nnod = nnode();
     for (unsigned j = 0; j < nnod; j++)
     {
       for (unsigned i = 0; i < Elemental_dimension; i++)
       {
         cog[i] += zeta_nodal(j, 0, i);
       }
     }
     for (unsigned i = 0; i < Elemental_dimension; i++)
     {
       cog[i] /= double(nnod);
     }
     // Get max distance
     for (unsigned j = 0; j < nnod; j++)
     {
       double dist_squared = 0.0;
       for (unsigned i = 0; i < Elemental_dimension; i++)
       {
         dist_squared +=
           (cog[i] - zeta_nodal(j, 0, i)) * (cog[i] - zeta_nodal(j, 0, i));
       }
       if (dist_squared > max_radius) max_radius = dist_squared;
     }
     max_radius = sqrt(max_radius);
   }
References Elemental_dimension, i, j, nnode(), sqrt(), and zeta_nodal().
Referenced by locate_zeta().
get_dresidual_dnodal_coordinates()
void FiniteElement::get_dresidual_dnodal_coordinates (RankThreeTensor< double > & dresidual_dnodal_coordinates) virtual
Compute derivatives of elemental residual vector with respect to nodal coordinates. Default implementation by FD can be overwritten for specific elements. dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij}
Compute derivatives of elemental residual vector with respect to nodal coordinates. Default implementation by FD can be overwritten for specific elements. dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij} /=======================================================================
Reimplemented in oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >, oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::RefineableSpaceTimeNavierStokesEquations< DIM >, oomph::RefineableSpaceTimeNavierStokesEquations< DIM >, oomph::RefineableSpaceTimeNavierStokesEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::RefineablePoissonEquations< DIM >, oomph::PoissonEquations< DIM >, oomph::PoissonEquations< 1 >, oomph::PoissonEquations< 2 >, oomph::PoissonEquations< 3 >, oomph::RefineableNavierStokesEquations< DIM >, oomph::NavierStokesEquations< DIM >, oomph::NavierStokesEquations< 2 >, oomph::RefineableElement, oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >, oomph::GeneralisedNewtonianNavierStokesEquations< DIM >, oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations, oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations, oomph::RefineableAxisymmetricNavierStokesEquations, oomph::AxisymmetricNavierStokesEquations, ModalPRefineableQPoissonElement< DIM >, and RefineableModalPoissonEquations< DIM >.
   {
     // Number of nodes
     unsigned n_nod = nnode();
     // If the element has no nodes (why??!!) return straightaway
     if (n_nod == 0) return;
     // Get dimension from first node
     unsigned dim_nod = node_pt(0)->ndim();
     // Number of dofs
     unsigned n_dof = ndof();
     // Get reference residual
     Vector<double> res(n_dof);
     Vector<double> res_pls(n_dof);
     get_residuals(res);
     // FD step
     double eps_fd = GeneralisedElement::Default_fd_jacobian_step;
     // Do FD loop
     for (unsigned j = 0; j < n_nod; j++)
     {
       // Get node
       Node* nod_pt = node_pt(j);
       // Loop over coordinate directions
       for (unsigned i = 0; i < dim_nod; i++)
       {
         // Make backup
         double backup = nod_pt->x(i);
         // Do FD step. No node update required as we're
         // attacking the coordinate directly...
         nod_pt->x(i) += eps_fd;
         // Perform auxiliary node update function
         nod_pt->perform_auxiliary_node_update_fct();
         // Get advanced residual
         get_residuals(res_pls);
         // Fill in FD entries [Loop order is "wrong" here as l is the
         // slow index but this is in a function that's costly anyway
         // and gives us the fastest loop outside where these tensor
         // is actually used.]
         for (unsigned l = 0; l < n_dof; l++)
         {
           dresidual_dnodal_coordinates(l, i, j) =
             (res_pls[l] - res[l]) / eps_fd;
         }
         // Reset coordinate. No node update required as we're
         // attacking the coordinate directly...
         nod_pt->x(i) = backup;
         // Perform auxiliary node update function
         nod_pt->perform_auxiliary_node_update_fct();
       }
     }
   }
References oomph::GeneralisedElement::Default_fd_jacobian_step, oomph::GeneralisedElement::get_residuals(), i, j, oomph::Node::ndim(), oomph::GeneralisedElement::ndof(), nnode(), node_pt(), oomph::Node::perform_auxiliary_node_update_fct(), res, and oomph::Node::x().
Referenced by oomph::ElementWithMovingNodes::fill_in_jacobian_from_geometric_data(), and ModalPRefineableQPoissonElement< DIM >::get_dresidual_dnodal_coordinates().
get_node_at_local_coordinate()
Node * FiniteElement::get_node_at_local_coordinate (const Vector< double > & s) const virtual
If there is a node at this local coordinate, return the pointer to the node
If there is a node at the local coordinate, s, return the pointer to the node. If not return 0. Note that this is a default, brute force implementation, can almost certainly be made more efficient for specific elements.
Reimplemented in oomph::QElement< 3, NNODE_1D >, oomph::QElement< 2, NNODE_1D >, oomph::QElement< 1, NNODE_1D >, oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >, oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >, and oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >.
   {
     // Locally cache the tolerance
     const double tol = Node_location_tolerance;
     Vector<double> s_node;
     // Locally cache the member data
     const unsigned el_dim = Elemental_dimension;
     const unsigned n_node = Nnode;
     // Loop over the nodes
     for (unsigned n = 0; n < n_node; n++)
     {
       bool Match = true;
       // Find the local coordinate of the node
       local_coordinate_of_node(n, s_node);
       for (unsigned i = 0; i < el_dim; i++)
       {
         // Calculate the difference between coordinates
         // and if it's bigger than our tolerance
         // break out of the (inner)loop
         if (std::fabs(s[i] - s_node[i]) > tol)
         {
           Match = false;
           break;
         }
       }
       // If we haven't complained then we have a match
       if (Match)
       {
         return node_pt(n);
       }
     }
     // If we get here, we have no match
     return 0;
   }
Referenced by oomph::RefineableQElement< 3 >::build(), oomph::RefineableQElement< 1 >::build(), oomph::RefineableQElement< 2 >::build(), oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::get_interpolating_node_at_local_coordinate(), oomph::RefineableAxisymmetricQTaylorHoodElement::get_interpolating_node_at_local_coordinate(), oomph::RefineableGeneralisedNewtonianAxisymmetricQTaylorHoodElement::get_interpolating_node_at_local_coordinate(), oomph::RefineableLinearisedQTaylorHoodElement::get_interpolating_node_at_local_coordinate(), oomph::RefineableQSphericalTaylorHoodElement::get_interpolating_node_at_local_coordinate(), oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::get_interpolating_node_at_local_coordinate(), oomph::RefineableElement::get_interpolating_node_at_local_coordinate(), oomph::RefineableQTaylorHoodElement< DIM >::get_interpolating_node_at_local_coordinate(), oomph::RefineablePolarTaylorHoodElement::get_interpolating_node_at_local_coordinate(), oomph::RefineableQPVDElementWithContinuousPressure< DIM >::get_interpolating_node_at_local_coordinate(), oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::get_interpolating_node_at_local_coordinate(), oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >::get_interpolating_node_at_local_coordinate(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::node_created_by_neighbour(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::node_created_by_neighbour(), oomph::RefineableQElement< 3 >::node_created_by_neighbour(), oomph::RefineableQElement< 1 >::node_created_by_neighbour(), oomph::RefineableQElement< 2 >::node_created_by_neighbour(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::node_created_by_son_of_neighbour(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::node_created_by_son_of_neighbour(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::pre_build(), and oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::pre_build().
get_node_number()
int FiniteElement::get_node_number (Node *const & global_node_pt) const
Return the number of the node *node_pt if this node is in the element, else return -1;
Return the number of the node located at *node_pt if this node is in the element, else return \(-1 \)
   {
     // Initialise the number to -1
     int number = -1;
     // Find the number of nodes
     unsigned n_node = nnode();
 #ifdef PARANOID
     {
       // Error check that node does not appear in element more than once
       unsigned count = 0;
       // Storage for the local node numbers of the element
       std::vector<int> local_node_number;
       // Loop over the nodes
       for (unsigned i = 0; i < n_node; i++)
       {
         // If the node is present increase the counter
         // and store the local node number
         if (node_pt(i) == global_node_pt)
         {
           ++count;
           local_node_number.push_back(i);
         }
       }
       // If the node appears more than once, complain
       if (count > 1)
       {
         std::ostringstream error_stream;
         error_stream << "Node " << global_node_pt << " appears " << count
                      << " times in an element." << std::endl
                      << "In positions: ";
         for (std::vector<int>::iterator it = local_node_number.begin();
              it != local_node_number.end();
              ++it)
         {
           error_stream << *it << " ";
         }
         error_stream << std::endl << "That seems very odd." << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
     }
 #endif
     // Loop over the nodes
     for (unsigned i = 0; i < n_node; i++)
     {
       // If the passed node pointer is present in the element
       // set number to be its local node number
       if (node_pt(i) == global_node_pt)
       {
         number = i;
         break;
       }
     }
     // Return the node number
     return number;
   }
References i, nnode(), node_pt(), OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::OcTreeForest::construct_up_right_equivalents(), oomph::Mesh::convert_to_boundary_node(), and oomph::RefineableElement::unbuild().
get_s_plot()
virtual void oomph::FiniteElement::get_s_plot (const unsigned & i, const unsigned & nplot, Vector< double > & s, const bool & shifted_to_interior = false) const inline virtual
Get cector of local coordinates of plot point i (when plotting nplot points in each "coordinate direction"). Generally these plot points will be uniformly spaced across the element. The optional final boolean flag (default: false) allows them to be shifted inwards to avoid duplication of plot point points between elements – useful when they are used in locate_zeta, say.
Reimplemented in oomph::TElement< 3, NNODE_1D >, oomph::TElement< 2, NNODE_1D >, oomph::TElement< 1, NNODE_1D >, oomph::QSpectralElement< 3, NNODE_1D >, oomph::QSpectralElement< 2, NNODE_1D >, oomph::QSpectralElement< 1, NNODE_1D >, oomph::QElement< 3, NNODE_1D >, oomph::QElement< 2, NNODE_1D >, oomph::QElement< 1, NNODE_1D >, oomph::QHermiteElement< DIM >, oomph::QHermiteElement< DIM - 1 >, oomph::QHermiteElement< DIM >, oomph::QHermiteElement< DIM - 1 >, oomph::QHermiteElement< DIM >, and oomph::QHermiteElement< DIM - 1 >.
     {
       throw OomphLibError(
         "get_s_plot(...) is not implemented for this element\n",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     };
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by UnstructuredFluidProblem< ELEMENT >::doc_boundary_coordinates(), oomph::Mesh::doc_boundary_coordinates(), oomph::Z2ErrorEstimator::doc_flux(), oomph::StefanBoltzmannHelper::doc_sample_points(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solid_boundary_coordinates(), UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solid_boundary_coordinates(), oomph::PolarNavierStokesEquations::full_output(), oomph::SphericalNavierStokesEquations::full_output(), locate_zeta(), oomph::NonlinearSurfaceContactElement< ELEMENT >::output(), oomph::LinearSurfaceContactElement< ELEMENT >::output(), oomph::UnsteadyHeatFluxPseudoMeltElement< ELEMENT >::output(), oomph::PolarStreamfunctionEquations::output(), oomph::AxisymFoepplvonKarmanEquations::output(), oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >::output(), oomph::AxisymmetricLinearElasticityEquations::output(), oomph::AxisymmetricLinearElasticityTractionElement< ELEMENT >::output(), oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::output(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::output(), oomph::FluidInterfaceElement::output(), oomph::SurfactantTransportInterfaceElement::output(), oomph::DisplacementBasedFoepplvonKarmanEquations::output(), oomph::FoepplvonKarmanEquations::output(), oomph::FourierDecomposedHelmholtzEquations::output(), oomph::NavierStokesSurfaceDragTorqueElement< ELEMENT >::output(), oomph::PMLFourierDecomposedHelmholtzEquations::output(), oomph::SolidTractionElement< ELEMENT >::output(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::output(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::output(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::output(), oomph::YoungLaplaceEquations::output(), oomph::LinearisedAxisymmetricNavierStokesEquations::output(), oomph::THomogenisedLinearElasticityElement< DIM, NNODE_1D >::output(), oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::output(), oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >::output(), oomph::MyTaylorHoodElement< DIM >::output(), oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::output(), oomph::AxisymAdvectionDiffusionEquations::output(), oomph::AxisymmetricNavierStokesEquations::output(), oomph::AxisymmetricPoroelasticityEquations::output(), oomph::BiharmonicEquations< DIM >::output(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::output(), oomph::LinearisedNavierStokesEquations::output(), oomph::BuoyantQCrouzeixRaviartElement< DIM >::output(), oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::output(), oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::output(), oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::output(), oomph::PMLTimeHarmonicLinearElasticityTractionElement< ELEMENT >::output(), oomph::PoissonFluxElement< ELEMENT >::output(), oomph::PolarNavierStokesEquations::output(), oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::output(), oomph::ProjectableUnsteadyHeatMixedOrderSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::output(), oomph::SphericalAdvectionDiffusionEquations::output(), oomph::SphericalNavierStokesEquations::output(), oomph::SteadyAxisymAdvectionDiffusionEquations::output(), oomph::TimeHarmonicLinearElasticityTractionElement< ELEMENT >::output(), oomph::ProjectableUnsteadyHeatElement< UNSTEADY_HEAT_ELEMENT >::output(), oomph::AxisymFoepplvonKarmanEquations::output_fct(), oomph::DisplacementBasedFoepplvonKarmanEquations::output_fct(), oomph::FoepplvonKarmanEquations::output_fct(), oomph::FourierDecomposedHelmholtzEquations::output_fct(), oomph::PMLFourierDecomposedHelmholtzEquations::output_fct(), oomph::YoungLaplaceEquations::output_fct(), oomph::AxisymAdvectionDiffusionEquations::output_fct(), oomph::AxisymmetricLinearElasticityEquations::output_fct(), oomph::AxisymmetricNavierStokesEquations::output_fct(), oomph::AxisymmetricPoroelasticityEquations::output_fct(), oomph::BiharmonicEquations< DIM >::output_fct(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::output_fct(), oomph::PolarNavierStokesEquations::output_fct(), oomph::SphericalAdvectionDiffusionEquations::output_fct(), oomph::SphericalNavierStokesEquations::output_fct(), oomph::SteadyAxisymAdvectionDiffusionEquations::output_fct(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::output_fct(), oomph::BiharmonicEquations< DIM >::output_fluid_velocity(), output_paraview(), oomph::FourierDecomposedHelmholtzEquations::output_real(), oomph::PMLFourierDecomposedHelmholtzEquations::output_real(), oomph::FourierDecomposedHelmholtzEquations::output_real_fct(), oomph::PMLFourierDecomposedHelmholtzEquations::output_real_fct(), oomph::LinearisedAxisymmetricNavierStokesEquations::output_veloc(), oomph::AxisymmetricNavierStokesEquations::output_veloc(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::output_veloc(), oomph::LinearisedNavierStokesEquations::output_veloc(), oomph::PolarNavierStokesEquations::output_veloc(), oomph::SphericalNavierStokesEquations::output_veloc(), oomph::SphericalNavierStokesEquations::output_vorticity(), oomph::FaceElement::output_zeta(), oomph::NavierStokesEquations< DIM >::scalar_value_fct_paraview(), oomph::SpaceTimeNavierStokesEquations< DIM >::scalar_value_fct_paraview(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::scalar_value_fct_paraview(), oomph::PMLHelmholtzEquations< DIM >::scalar_value_fct_paraview(), oomph::PoissonEquations< DIM >::scalar_value_fct_paraview(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::scalar_value_fct_paraview(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::scalar_value_fct_paraview(), oomph::MultiPoissonEquations< DIM, NFIELDS >::scalar_value_paraview(), oomph::AdvectionDiffusionEquations< DIM >::scalar_value_paraview(), oomph::AxisymAdvectionDiffusionEquations::scalar_value_paraview(), oomph::AxisymmetricNavierStokesEquations::scalar_value_paraview(), oomph::AxisymmetricPoroelasticityEquations::scalar_value_paraview(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::scalar_value_paraview(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::scalar_value_paraview(), oomph::HelmholtzEquations< DIM >::scalar_value_paraview(), oomph::NavierStokesEquations< DIM >::scalar_value_paraview(), oomph::PMLHelmholtzEquations< DIM >::scalar_value_paraview(), oomph::PoissonEquations< DIM >::scalar_value_paraview(), oomph::SpaceTimeNavierStokesEquations< DIM >::scalar_value_paraview(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::scalar_value_paraview(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::scalar_value_paraview(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::scalar_value_paraview(), oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::scalar_value_paraview(), oomph::Multi_domain_functions::setup_bulk_elements_adjacent_to_face_mesh(), oomph::StefanBoltzmannHelper::setup_stefan_boltzmann_visibility(), and TFaceTestProblem< ELEMENT >::TFaceTestProblem().
get_x() [1/2]
void oomph::FiniteElement::get_x (const unsigned & t, const Vector< double > & s, Vector< double > & x) inline
Global coordinates as function of local coordinates at previous time "level" t (t=0: present; t>0: previous). Either via FE representation of QElement or via macro-element (if Macro_elem_pt!=0).
     {
       // Get timestepper from first node
       TimeStepper* time_stepper_pt = node_pt(0)->time_stepper_pt();
       // Number of previous values
       const unsigned nprev = time_stepper_pt->nprev_values();
       // If t > nprev_values(), we're not dealing with a previous value
       // but a generalised history value -- this cannot be recovered from
       // macro element but must be determined by finite element interpolation
       // If there is no macro element, or we're dealing with a generalised
       // history value then use the FE representation
       if ((Macro_elem_pt == 0) || (t > nprev))
       {
         interpolated_x(t, s, x);
       }
       // Otherwise use the macro element representation
       else
       {
         get_x_from_macro_element(t, s, x);
       }
     }
References get_x_from_macro_element(), interpolated_x(), Macro_elem_pt, node_pt(), oomph::TimeStepper::nprev_values(), s, plotPSD::t, oomph::GeomObject::time_stepper_pt(), oomph::Data::time_stepper_pt(), and plotDoE::x.
get_x() [2/2]
void oomph::FiniteElement::get_x (const Vector< double > & s, Vector< double > & x) const inline
Global coordinates as function of local coordinates. Either via FE representation or via macro-element (if Macro_elem_pt!=0)
     {
       // If there is no macro element then return interpolated x
       if (Macro_elem_pt == 0)
       {
         interpolated_x(s, x);
       }
       // Otherwise call the macro element representation
       else
       {
         get_x_from_macro_element(s, x);
       }
     }
References get_x_from_macro_element(), interpolated_x(), Macro_elem_pt, s, and plotDoE::x.
Referenced by oomph::TreeBasedRefineableMeshBase::adapt_mesh(), oomph::RefineableQElement< 3 >::build(), oomph::RefineableQElement< 1 >::build(), oomph::RefineableQElement< 2 >::build(), oomph::OcTree::doc_face_neighbours(), oomph::BinaryTree::doc_neighbours(), oomph::QuadTree::doc_neighbours(), oomph::OcTree::doc_true_edge_neighbours(), oomph::Mesh::node_update(), oomph::MacroElementNodeUpdateNode::node_update(), oomph::TreeBasedRefineableMeshBase::p_adapt_mesh(), oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::p_refine(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::p_refine(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::p_refine(), oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::rebuild_from_sons(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::rebuild_from_sons(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::rebuild_from_sons(), oomph::RefineableQSpectralElement< 3 >::rebuild_from_sons(), oomph::RefineableQSpectralElement< 1 >::rebuild_from_sons(), and oomph::RefineableQSpectralElement< 2 >::rebuild_from_sons().
get_x_from_macro_element() [1/2]
virtual void oomph::FiniteElement::get_x_from_macro_element (const unsigned & t, const Vector< double > & s, Vector< double > & x) inline virtual
Global coordinates as function of local coordinates at previous time "level" t (t=0: present; t>0: previous). using macro element representation (Broken virtual – overload in specific geometric element class if you want to use this functionality.)
Reimplemented in oomph::QElementBase.
     {
       throw OomphLibError(
         "get_x_from_macro_element(...) is not implemented for this element\n",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
get_x_from_macro_element() [2/2]
virtual void oomph::FiniteElement::get_x_from_macro_element (const Vector< double > & s, Vector< double > & x) const inline virtual
Global coordinates as function of local coordinates using macro element representation. (Broken virtual — this must be overloaded in specific geometric element classes)
Reimplemented in oomph::QElementBase.
     {
       throw OomphLibError(
         "get_x_from_macro_element(...) is not implemented for this element\n",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by get_x(), and interpolated_zeta().
has_hanging_nodes()
bool oomph::FiniteElement::has_hanging_nodes () const inline
Return boolean to indicate if any of the element's nodes are geometrically hanging.
     {
       unsigned nnod = nnode();
       for (unsigned j = 0; j < nnod; j++)
       {
         if (node_pt(j)->is_hanging())
         {
           return true;
         }
       }
       return false;
     }
References j, nnode(), and node_pt().
Referenced by oomph::AdvectionDiffusionFluxElement< ELEMENT >::AdvectionDiffusionFluxElement(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::AxisymmetricPoroelasticityTractionElement(), oomph::DarcyFaceElement< ELEMENT >::DarcyFaceElement(), oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement(), oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement(), oomph::FpPressureAdvDiffRobinBCElement< ELEMENT >::FpPressureAdvDiffRobinBCElement(), oomph::FpPressureAdvDiffRobinBCMixedOrderSpaceTimeElement< ELEMENT >::FpPressureAdvDiffRobinBCMixedOrderSpaceTimeElement(), oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >::FpPressureAdvDiffRobinBCSpaceTimeElement(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::FSIImposeDisplacementByLagrangeMultiplierElement(), oomph::HeatedPenetratorFluxElement< ELEMENT >::HeatedPenetratorFluxElement(), oomph::HelmholtzFluxElement< ELEMENT >::HelmholtzFluxElement(), oomph::HelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::HelmholtzFluxFromNormalDisplacementBCElement(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::ImposeDisplacementByLagrangeMultiplierElement(), oomph::LinearElasticityTractionElement< ELEMENT >::LinearElasticityTractionElement(), oomph::LinearWaveFluxElement< ELEMENT >::LinearWaveFluxElement(), oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::NavierStokesImpedanceTractionElement(), oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::NavierStokesMixedOrderSpaceTimeTractionElement(), oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::NavierStokesSpaceTimeTractionElement(), oomph::NavierStokesTractionElement< ELEMENT >::NavierStokesTractionElement(), oomph::PMLHelmholtzFluxElement< ELEMENT >::PMLHelmholtzFluxElement(), oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::PMLHelmholtzFluxFromNormalDisplacementBCElement(), oomph::PMLHelmholtzPowerElement< ELEMENT >::PMLHelmholtzPowerElement(), oomph::PMLTimeHarmonicLinearElasticityTractionElement< ELEMENT >::PMLTimeHarmonicLinearElasticityTractionElement(), oomph::PoissonFluxElement< ELEMENT >::PoissonFluxElement(), oomph::PolarNavierStokesTractionElement< ELEMENT >::PolarNavierStokesTractionElement(), oomph::PolarStressIntegralElement< ELEMENT >::PolarStressIntegralElement(), oomph::SolidTractionElement< ELEMENT >::SolidTractionElement(), oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::SphericalAdvectionDiffusionFluxElement(), oomph::SpineUpdateFluidInterfaceElement< EQUATION_CLASS, DERIVATIVE_CLASS, ELEMENT >::SpineUpdateFluidInterfaceElement(), oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::SteadyAxisymAdvectionDiffusionFluxElement(), oomph::SurfaceContactElementBase< ELEMENT >::SurfaceContactElementBase(), oomph::TimeHarmonicLinearElasticityTractionElement< ELEMENT >::TimeHarmonicLinearElasticityTractionElement(), oomph::TimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::TimeHarmonicLinElastLoadedByHelmholtzPressureBCElement(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement(), and oomph::UnsteadyHeatFluxElement< ELEMENT >::UnsteadyHeatFluxElement().
identify_field_data_for_interactions()
void FiniteElement::identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> & paired_field_data) virtual
The purpose of this function is to identify all possible Data that can affect the fields interpolated by the FiniteElement. The information will typically be used in interaction problems in which the FiniteElement provides a forcing term for an ElementWithExternalElement. The Data must be provided as paired_load data containing
the pointer to a Data object and
the index of the value in that Data objectThe generic implementation (should be overloaded in more specific applications) is to include all nodal and internal Data stored in the FiniteElement. The geometric data, which includes the positions of SolidNodes, is treated separately by the function identify_geometric_data()
The purpose of this function is to identify all possible Data that can affect the fields interpolated by the FiniteElement. The information will typically be used in interaction problems in which the FiniteElement provides a forcing term for an ElementWithExternalElement. The Data must be provided as paired_load data containing (a) the pointer to a Data object and (b) the index of the value in that Data object. The generic implementation (should be overloaded in more specific applications) is to include all nodal and internal Data stored in the FiniteElement. Note that the geometric data, which includes the positions of SolidNodes, is treated separately by the function identify_geometric_data()
Reimplemented in oomph::RefineableElement.
   {
     // Loop over all internal data
     const unsigned n_internal = this->ninternal_data();
     for (unsigned n = 0; n < n_internal; n++)
     {
       // Cache the data pointer
       Data* const dat_pt = this->internal_data_pt(n);
       // Find the number of data values stored in the data object
       const unsigned n_value = dat_pt->nvalue();
       // Add the index of each data value and the pointer to the set
       // of pairs
       for (unsigned i = 0; i < n_value; i++)
       {
         paired_field_data.insert(std::make_pair(dat_pt, i));
       }
     }
     // Loop over all the nodes
     const unsigned n_node = this->nnode();
     for (unsigned n = 0; n < n_node; n++)
     {
       // Cache the node pointer
       Node* const nod_pt = this->node_pt(n);
       // Find the number of values stored at the node
       const unsigned n_value = nod_pt->nvalue();
       // Add the index of each data value and the pointer to the set
       // of pairs
       for (unsigned i = 0; i < n_value; i++)
       {
         paired_field_data.insert(std::make_pair(nod_pt, i));
       }
     }
   }
References i, oomph::GeneralisedElement::internal_data_pt(), n, oomph::GeneralisedElement::ninternal_data(), nnode(), node_pt(), and oomph::Data::nvalue().
identify_geometric_data()
virtual void oomph::FiniteElement::identify_geometric_data (std::set< Data * > & geometric_data_pt) inline virtual
The purpose of this function is to identify all Data objects that affect the elements' geometry. This function is implemented as an empty virtual function since it can only be implemented in conjunction with a node-update strategy. A specific implementation is provided in the ElementWithMovingNodes class.
Reimplemented in oomph::RefineableSolidElement, oomph::PseudoSolidNodeUpdateElement< TCrouzeixRaviartElement< 2 >, TPVDBubbleEnrichedElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< TTaylorHoodElement< 2 >, TPVDElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< GeneralisedNewtonianAxisymmetricTTaylorHoodElement, TPVDElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< AxisymmetricTTaylorHoodElement, TPVDElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< GeneralisedNewtonianTTaylorHoodElement< 2 >, TPVDElement< 2, 3 > >, oomph::SolidFiniteElement, and oomph::ElementWithMovingNodes.
 {}
Referenced by oomph::ImmersedRigidBodyElement::set_drag_mesh().
integral_pt()
Integral* const& oomph::FiniteElement::integral_pt () const inline
Return the pointer to the integration scheme (const version)
     {
       return Integral_pt;
     }
References Integral_pt.
Referenced by oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::add_element_contribution_to_aux_integral(), oomph::DGFaceElement::add_flux_contributions(), oomph::ElementWithExternalElement::assign_external_interaction_data_local_eqn_numbers(), oomph::Multi_domain_functions::aux_setup_multi_domain_interaction(), FourierDecomposedHelmholtzProblem< ELEMENT >::check_gamma(), oomph::Mesh::check_inverted_elements(), check_J_eulerian_at_knots(), oomph::FaceElement::check_J_eulerian_at_knots(), oomph::HelmholtzBCElementBase< ELEMENT >::compute_contribution_to_fourier_components(), oomph::AxisymAdvectionDiffusionEquations::compute_error(), oomph::AxisymFoepplvonKarmanEquations::compute_error(), oomph::AxisymmetricLinearElasticityEquations::compute_error(), oomph::BiharmonicEquations< DIM >::compute_error(), oomph::DisplacementBasedFoepplvonKarmanEquations::compute_error(), oomph::FoepplvonKarmanEquations::compute_error(), oomph::FourierDecomposedHelmholtzEquations::compute_error(), oomph::PMLFourierDecomposedHelmholtzEquations::compute_error(), oomph::SphericalAdvectionDiffusionEquations::compute_error(), oomph::SteadyAxisymAdvectionDiffusionEquations::compute_error(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::compute_error(), oomph::YoungLaplaceEquations::compute_error(), oomph::AxisymmetricPoroelasticityEquations::compute_error(), oomph::AxisymmetricNavierStokesEquations::compute_error(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::compute_error(), oomph::PolarNavierStokesEquations::compute_error(), oomph::SphericalNavierStokesEquations::compute_error(), oomph::EulerEquations< DIM >::compute_error(), oomph::ScalarAdvectionEquations< DIM >::compute_error(), oomph::SphericalNavierStokesEquations::compute_error_e(), oomph::SolidFiniteElement::compute_norm(), oomph::FourierDecomposedHelmholtzEquations::compute_norm(), oomph::PMLFourierDecomposedHelmholtzEquations::compute_norm(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::compute_norm(), oomph::AxisymmetricNavierStokesEquations::compute_physical_size(), oomph::AxisymmetricPVDEquations::compute_physical_size(), oomph::AxisymmetricPVDEquationsWithPressure::compute_physical_size(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::compute_physical_size(), AirwayReopeningProblem< ELEMENT >::connect_walls(), oomph::FaceElement::continuous_tangent_and_outer_unit_normal(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::contribution_to_enclosed_volume(), oomph::LineVolumeConstraintBoundingElement::contribution_to_enclosed_volume(), oomph::AxisymmetricVolumeConstraintBoundingElement::contribution_to_enclosed_volume(), oomph::StefanBoltzmannRadiationBase::contribution_to_stefan_boltzmann_radiation(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::contribution_to_total_porous_flux(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::contribution_to_total_porous_flux(), oomph::AxisymmetricVolumeConstraintBoundingElement::contribution_to_volume_flux(), d2shape_local_at_knot(), oomph::SphericalNavierStokesEquations::d_kin_energy_dt(), oomph::AxisymmetricNavierStokesEquations::dissipation(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::dissipation(), oomph::PolarNavierStokesEquations::dissipation(), oomph::SphericalNavierStokesEquations::dissipation(), oomph::LinearisedAxisymmetricNavierStokesEquations::dkin_energy_dt(), oomph::FSI_functions::doc_fsi(), ContactProblem< ELEMENT >::doc_solution(), StefanBoltzmannProblem< ELEMENT >::doc_solution(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::drag_force(), dshape_local_at_knot(), oomph::SphericalNavierStokesEquations::extract_velocity(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::extrapolated_strain_rate(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::extrapolated_strain_rate(), oomph::AxisymmetricNavierStokesEquations::fill_in_contribution_to_hessian_vector_products(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_contribution_to_hessian_vector_products(), oomph::AxisymFoepplvonKarmanEquations::fill_in_contribution_to_residuals(), oomph::DisplacementBasedFoepplvonKarmanEquations::fill_in_contribution_to_residuals(), oomph::FoepplvonKarmanEquations::fill_in_contribution_to_residuals(), oomph::ClampedHermiteShellBoundaryConditionElement::fill_in_contribution_to_residuals(), oomph::RefineableYoungLaplaceEquations::fill_in_contribution_to_residuals(), oomph::YoungLaplaceEquations::fill_in_contribution_to_residuals(), oomph::AxisymmetricPVDEquations::fill_in_contribution_to_residuals_axisym_pvd(), oomph::KirchhoffLoveBeamEquations::fill_in_contribution_to_residuals_beam(), oomph::KirchhoffLoveShellEquations::fill_in_contribution_to_residuals_shell(), oomph::AxisymmetricLinearElasticityEquations::fill_in_generic_contribution_to_residuals_axisymmetric_linear_elasticity(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::fill_in_generic_contribution_to_residuals_fourier_decomp_time_harmonic_linear_elasticity(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), oomph::ImposeImpenetrabilityElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(), oomph::ImposeParallelOutflowElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(), oomph::RefineableQDPVDElement< DIM, NNODE_1D >::fill_in_generic_contribution_to_residuals_pvd(), oomph::AxisymmetricNavierStokesEquations::fill_in_generic_dresidual_contribution_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_dresidual_contribution_axi_nst(), oomph::SolidFiniteElement::fill_in_generic_jacobian_for_solid_ic(), oomph::AxisymmetricPoroelasticityEquations::fill_in_generic_residual_contribution(), oomph::PolarNavierStokesEquations::fill_in_generic_residual_contribution(), oomph::RefineablePolarNavierStokesEquations::fill_in_generic_residual_contribution(), oomph::RefineablePolarStreamfunctionEquations::fill_in_generic_residual_contribution(), oomph::PolarStreamfunctionEquations::fill_in_generic_residual_contribution(), oomph::SteadyAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_adv_diff(), oomph::AxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), oomph::RefineableAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), oomph::AxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::AxisymmetricPVDEquationsWithPressure::fill_in_generic_residual_contribution_axisym_pvd_with_pressure(), oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_cons_axisym_adv_diff(), oomph::NavierStokesFluxControlElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction(), oomph::FourierDecomposedHelmholtzEquations::fill_in_generic_residual_contribution_fourier_decomposed_helmholtz(), oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::fill_in_generic_residual_contribution_fourier_decomposed_helmholtz_DtN_bc(), oomph::HelmholtzAbsorbingBCElement< ELEMENT >::fill_in_generic_residual_contribution_helmholtz_abc(), oomph::HelmholtzDtNBoundaryElement< ELEMENT >::fill_in_generic_residual_contribution_helmholtz_DtN_bc(), oomph::FluidInterfaceElement::fill_in_generic_residual_contribution_interface(), oomph::LineFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary(), oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_lin_axi_nst(), oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::LinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst(), oomph::RefineableLinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst(), oomph::PeriodicOrbitEquations::fill_in_generic_residual_contribution_orbit(), oomph::PMLFourierDecomposedHelmholtzEquations::fill_in_generic_residual_contribution_pml_fourier_decomposed_helmholtz(), oomph::RefineableSphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), oomph::SphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), oomph::RefineableSphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst(), oomph::SphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst(), oomph::LineVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint(), oomph::AxisymmetricVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint(), oomph::SurfaceVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint(), oomph::SolidFiniteElement::fill_in_jacobian_for_newmark_accel(), oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::fill_in_off_diagonal_block_analytic(), oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_off_diagonal_block_analytic(), oomph::NavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::fill_in_off_diagonal_block_analytic(), oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_off_diagonal_block_analytic(), oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::BuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::FoepplvonKarmanEquations::get_bounded_volume(), oomph::NavierStokesSurfaceDragTorqueElement< ELEMENT >::get_drag_and_torque(), oomph::AxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::Z2ErrorEstimator::get_element_errors(), oomph::KirchhoffLoveShellEquations::get_energy(), oomph::KirchhoffLoveBeamEquations::get_energy(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_kinetic_energy_flux(), oomph::AxisymmetricNavierStokesEquations::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::SphericalNavierStokesEquations::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_rate_of_traction_work(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_rate_of_traction_work_components(), oomph::FSILinearisedAxisymPoroelasticTractionElement< POROELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >::get_traction(), oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::get_volume_flux(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_volume_flux(), oomph::PMLHelmholtzPowerElement< ELEMENT >::global_flux_contribution(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::global_flux_contribution_from_helmholtz(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::global_flux_contribution_from_solid(), oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >::global_power_contribution(), oomph::HelmholtzBCElementBase< ELEMENT >::global_power_contribution(), oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::global_power_contribution(), oomph::PMLHelmholtzPowerElement< ELEMENT >::global_power_contribution(), oomph::ElementWithExternalElement::initialise_external_element_storage(), oomph::SurfactantTransportInterfaceElement::integrate_c(), integrate_fct(), oomph::SolubleSurfactantTransportInterfaceElement::integrated_C(), oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::integrated_C_and_M(), oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >::integrated_C_and_M(), oomph::AxisymmetricNavierStokesEquations::kin_energy(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::kin_energy(), oomph::PolarNavierStokesEquations::kin_energy(), oomph::SphericalNavierStokesEquations::kin_energy(), oomph::SolubleSurfactantTransportInterfaceElement::l2_norm_of_height(), oomph::KirchhoffLoveShellEquations::load_rate_of_work(), oomph::Multi_domain_functions::locate_zeta_for_local_coordinates(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::max_and_min_invariant_and_viscosity(), oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >::node_update_adjacent_fluid_elements(), oomph::FSIWallElement::node_update_adjacent_fluid_elements(), oomph::FaceElement::outer_unit_normal(), oomph::UnsteadyHeatBaseFaceElement< ELEMENT >::output(), oomph::FSIAxisymmetricLinearElasticityTractionElement< ELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >::output(), oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::output(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::output(), oomph::FSILinearisedAxisymPoroelasticTractionElement< POROELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >::output(), oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::output(), oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::output(), oomph::TimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::output(), oomph::HelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::output(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::output(), oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::output(), oomph::ClampedHermiteShellBoundaryConditionElement::output(), oomph::FSISolidTractionElement< ELEMENT, DIM >::output(), oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >::output_adjacent_fluid_elements(), oomph::SolarRadiationBase::output_atmospheric_radiation(), oomph::SolarRadiationBase::output_diffuse_radiation_cone(), oomph::SolarRadiationBase::output_diffuse_radiation_cone_max_angle(), oomph::SolarRadiationBase::output_diffuse_radiation_cone_min_angle(), oomph::ElementWithExternalElement::output_external_elements(), oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >::output_integration_points(), oomph::SolarRadiationBase::output_limiting_angles(), oomph::SurfaceMeltElement< ELEMENT >::output_melt(), oomph::NavierStokesEquations< DIM >::output_pressure_advection_diffusion_robin_elements(), oomph::SpaceTimeNavierStokesEquations< DIM >::output_pressure_advection_diffusion_robin_elements(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::output_pressure_advection_diffusion_robin_elements(), oomph::StefanBoltzmannUnsteadyHeatFluxElement< ELEMENT >::output_stefan_boltzmann_radiation(), oomph::StefanBoltzmannRadiationBase::output_stefan_boltzmann_radiation_rays(), oomph::StorableShapeElementBase::pre_compute_d2shape_eulerian_at_knots(), oomph::StorableShapeSolidElementBase::pre_compute_d2shape_lagrangian_at_knots(), oomph::StorableShapeElementBase::pre_compute_d2shape_local_at_knots(), oomph::StorableShapeElementBase::pre_compute_dshape_eulerian_at_knots(), oomph::StorableShapeSolidElementBase::pre_compute_dshape_lagrangian_at_knots(), oomph::StorableShapeElementBase::pre_compute_dshape_local_at_knots(), oomph::InterpolateFromIntegralPointsBase::pre_compute_ipt_to_node_mapping(), oomph::StorableShapeElementBase::pre_compute_J_eulerian_at_knots(), oomph::StorableShapeElementBase::pre_compute_shape_at_knots(), oomph::AxisymmetricNavierStokesEquations::pressure_integral(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::pressure_integral(), oomph::PolarNavierStokesEquations::pressure_integral(), oomph::SphericalNavierStokesEquations::pressure_integral(), oomph::RefineableImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::RefineableFSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), oomph::RefineableNavierStokesFluxControlElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction(), oomph::DGFaceElement::report_info(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::residual_for_projection(), oomph::ProjectableDarcyElement< DARCY_ELEMENT >::residual_for_projection(), oomph::ProjectableElement< ELEMENT >::residual_for_projection(), self_test(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::set_boundary_shape_geom_object_pt(), oomph::InterpolateFromIntegralPointsBase::set_integration_scheme(), oomph::StefanBoltzmannUnsteadyHeatFluxElement< ELEMENT >::set_integration_scheme(), set_integration_scheme(), oomph::StorableShapeElementBase::set_integration_scheme(), oomph::StorableShapeSolidElementBase::set_integration_scheme(), oomph::FourierDecomposedHelmholtzDtNMesh< ELEMENT >::setup_gamma(), oomph::HelmholtzDtNMesh< ELEMENT >::setup_gamma(), oomph::DGFaceElement::setup_neighbour_info(), oomph::StefanBoltzmannHelper::setup_stefan_boltzmann_visibility(), oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::shape_and_test_at_knot(), oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::shape_and_test_at_knot(), shape_at_knot(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::shape_basis_test_local_at_knot(), oomph::TPoroelasticityElement< ORDER >::shape_basis_test_local_at_knot(), oomph::TRaviartThomasDarcyElement< ORDER >::shape_basis_test_local_at_knot(), size(), oomph::SolarRadiationBase::SolarRadiationBase(), oomph::AxisymmetricPVDEquationsWithPressure::solid_pshape_at_knot(), oomph::PVDEquationsWithPressure< DIM >::solid_pshape_at_knot(), oomph::MyTaylorHoodElement< DIM >::square_of_l2_norm(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::square_of_l2_norm_of_error(), oomph::StefanBoltzmannRadiationBase::StefanBoltzmannRadiationBase(), oomph::StorableShapeElement< ELEMENT >::StorableShapeElement(), oomph::StorableShapeSolidElement< ELEMENT >::StorableShapeSolidElement(), oomph::SolarRadiationBase::update_limiting_angles(), oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::~PRefineableGeneralisedNewtonianQCrouzeixRaviartElement(), oomph::PRefineableQCrouzeixRaviartElement< DIM >::~PRefineableQCrouzeixRaviartElement(), oomph::PRefineableQLinearElasticityElement< DIM >::~PRefineableQLinearElasticityElement(), oomph::PRefineableQPoissonElement< DIM >::~PRefineableQPoissonElement(), and oomph::QTaylorHoodSpaceTimeElement< DIM >::~QTaylorHoodSpaceTimeElement().
integrate_fct() [1/2]
void FiniteElement::integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > & integral)
Integrate Vector-valued function over element.
Evaluate integral of a Vector-valued function \({\bf f}({\bf x}) \) over the element.
   {
     // Initialise all components of integral Vector
     const unsigned ncomponents = integral.size();
     Vector<double> integrand(ncomponents);
     for (unsigned i = 0; i < ncomponents; i++)
     {
       integral[i] = 0.0;
     }
     // Figure out the global (Eulerian) spatial dimension of the
     // element by checking the Eulerian dimension of the nodes
     const unsigned n_dim_eulerian = nodal_dimension();
     // Allocate Vector of global Eulerian coordinates
     Vector<double> x(n_dim_eulerian);
     // Set the value of n_intpt
     const unsigned n_intpt = integral_pt()->nweight();
     // Vector of local coordinates
     const unsigned n_dim = dim();
     Vector<double> s(n_dim);
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Assign the values of s
       for (unsigned i = 0; i < n_dim; i++)
       {
         s[i] = integral_pt()->knot(ipt, i);
       }
       // Assign the values of the global Eulerian coordinates
       for (unsigned i = 0; i < n_dim_eulerian; i++)
       {
         x[i] = interpolated_x(s, i);
       }
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Get Jacobian of mapping
       double J = J_eulerian(s);
       // Evaluate the integrand at the knot points
       integrand_fct_pt(x, integrand);
       // Add to components of integral Vector
       for (unsigned i = 0; i < ncomponents; i++)
       {
         integral[i] += integrand[i] * w * J;
       }
     }
   }
References dim(), i, integral_pt(), interpolated_x(), J, J_eulerian(), oomph::Integral::knot(), nodal_dimension(), oomph::Integral::nweight(), s, w, oomph::Integral::weight(), and plotDoE::x.
integrate_fct() [2/2]
void FiniteElement::integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double & time, Vector< double > & integral)
Integrate Vector-valued time-dep function over element.
Evaluate integral of a Vector-valued, time-dependent function \({\bf f}(t,{\bf x}) \) over the element.
   {
     // Initialise all components of integral Vector and setup integrand vector
     const unsigned ncomponents = integral.size();
     Vector<double> integrand(ncomponents);
     for (unsigned i = 0; i < ncomponents; i++)
     {
       integral[i] = 0.0;
     }
     // Figure out the global (Eulerian) spatial dimension of the
     // element
     const unsigned n_dim_eulerian = nodal_dimension();
     // Allocate Vector of global Eulerian coordinates
     Vector<double> x(n_dim_eulerian);
     // Set the value of n_intpt
     const unsigned n_intpt = integral_pt()->nweight();
     // Vector of local coordinates
     const unsigned n_dim = dim();
     Vector<double> s(n_dim);
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Assign the values of s
       for (unsigned i = 0; i < n_dim; i++)
       {
         s[i] = integral_pt()->knot(ipt, i);
       }
       // Assign the values of the global Eulerian coordinates
       for (unsigned i = 0; i < n_dim_eulerian; i++)
       {
         x[i] = interpolated_x(s, i);
       }
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Get Jacobian of mapping
       double J = J_eulerian(s);
       // Evaluate the integrand at the knot points
       integrand_fct_pt(time, x, integrand);
       // Add to components of integral Vector
       for (unsigned i = 0; i < ncomponents; i++)
       {
         integral[i] += integrand[i] * w * J;
       }
     }
   }
References dim(), i, integral_pt(), interpolated_x(), J, J_eulerian(), oomph::Integral::knot(), nodal_dimension(), oomph::Integral::nweight(), s, w, oomph::Integral::weight(), and plotDoE::x.
interpolated_dxdt() [1/2]
double FiniteElement::interpolated_dxdt (const Vector< double > & s, const unsigned & i, const unsigned & t_deriv) virtual
Return t-th time-derivative of the i-th FE-interpolated Eulerian coordinate at local coordinate s.
Return the t-th time-derivative of the i-th FE-interpolated Eulerian coordinate at local coordinate s.
Reimplemented in oomph::FaceElement.
   {
     // Find the number of nodes and positions (locally cached)
     const unsigned n_node = nnode();
     const unsigned n_position_type = nnodal_position_type();
     // Get shape functions: specify # of nodes, # of positional dofs
     Shape psi(n_node, n_position_type);
     shape(s, psi);
     // Initialise
     double drdt = 0.0;
     // Assemble time derivative
     // Loop over nodes
     for (unsigned l = 0; l < n_node; l++)
     {
       // Loop over types of dof
       for (unsigned k = 0; k < n_position_type; k++)
       {
         drdt += dnodal_position_gen_dt(t_deriv, l, k, i) * psi(l, k);
       }
     }
     return drdt;
   }
References dnodal_position_gen_dt(), i, k, nnodal_position_type(), nnode(), s, and shape().
Referenced by DiskShockWaveProblem< ELEMENT, TIMESTEPPER >::doc_solution(), DiskOscillationProblem< ELEMENT >::doc_solution(), dposition_dt(), oomph::FaceElement::interpolated_dxdt(), oomph::SCoupledElement< ELEMENT >::output(), oomph::VolumeCoupledElement< ELEMENT >::output(), and oomph::HermiteShellElement::output_with_time_dep_quantities().
interpolated_dxdt() [2/2]
void FiniteElement::interpolated_dxdt (const Vector< double > & s, const unsigned & t_deriv, Vector< double > & dxdt) virtual
Compte t-th time-derivative of the FE-interpolated Eulerian coordinate vector at local coordinate s.
Compute t-th time-derivative of the FE-interpolated Eulerian coordinate vector at local coordinate s.
Reimplemented in oomph::FaceElement.
   {
     // Find the number of nodes and positions (locally cached)
     const unsigned n_node = nnode();
     const unsigned n_position_type = nnodal_position_type();
     const unsigned nodal_dim = nodal_dimension();
     // Get shape functions: specify # of nodes, # of positional dofs
     Shape psi(n_node, n_position_type);
     shape(s, psi);
     // Loop over directions
     for (unsigned i = 0; i < nodal_dim; i++)
     {
       // Initialise
       dxdt[i] = 0.0;
       // Assemble time derivative
       // Loop over nodes
       for (unsigned l = 0; l < n_node; l++)
       {
         // Loop over types of dof
         for (unsigned k = 0; k < n_position_type; k++)
         {
           dxdt[i] += dnodal_position_gen_dt(t_deriv, l, k, i) * psi(l, k);
         }
       }
     }
   }
References dnodal_position_gen_dt(), i, k, nnodal_position_type(), nnode(), nodal_dimension(), s, and shape().
interpolated_x() [1/4]
double FiniteElement::interpolated_x (const unsigned & t, const Vector< double > & s, const unsigned & i) const virtual
Return FE interpolated coordinate x[i] at local coordinate s at previous timestep t (t=0: present; t>0: previous timestep)
Reimplemented in oomph::FaceElement.
   {
     // Find the number of nodes
     const unsigned n_node = nnode();
     // Find the number of positional types
     const unsigned n_position_type = nnodal_position_type();
     // Assign storage for the local shape function
     Shape psi(n_node, n_position_type);
     // Find the values of shape function
     shape(s, psi);
     // Initialise value of x
     double interpolated_x = 0.0;
     // Loop over the local nodes
     for (unsigned l = 0; l < n_node; l++)
     {
       // Loop over the number of dofs
       for (unsigned k = 0; k < n_position_type; k++)
       {
         interpolated_x += nodal_position_gen(t, l, k, i) * psi(l, k);
       }
     }
     return (interpolated_x);
   }
References i, interpolated_x(), k, nnodal_position_type(), nnode(), nodal_position_gen(), s, shape(), and plotPSD::t.
interpolated_x() [2/4]
void FiniteElement::interpolated_x (const unsigned & t, const Vector< double > & s, Vector< double > & x) const virtual
Return FE interpolated position x[] at local coordinate s at previous timestep t as Vector (t=0: present; t>0: previous timestep)
Reimplemented in oomph::FaceElement.
   {
     // Find the number of nodes
     const unsigned n_node = nnode();
     // Find the number of positional types
     const unsigned n_position_type = nnodal_position_type();
     // Find the dimensions of the nodes
     const unsigned nodal_dim = nodal_dimension();
     // Assign storage for the local shape function
     Shape psi(n_node, n_position_type);
     // Find the values of shape function
     shape(s, psi);
     // Loop over the dimensions
     for (unsigned i = 0; i < nodal_dim; i++)
     {
       // Initilialise value of x[i] to zero
       x[i] = 0.0;
       // Loop over the local nodes
       for (unsigned l = 0; l < n_node; l++)
       {
         // Loop over the number of dofs
         for (unsigned k = 0; k < n_position_type; k++)
         {
           x[i] += nodal_position_gen(t, l, k, i) * psi(l, k);
         }
       }
     }
   }
References i, k, nnodal_position_type(), nnode(), nodal_dimension(), nodal_position_gen(), s, shape(), plotPSD::t, and plotDoE::x.
interpolated_x() [3/4]
double FiniteElement::interpolated_x (const Vector< double > & s, const unsigned & i) const virtual
Return FE interpolated coordinate x[i] at local coordinate s.
Reimplemented in oomph::FaceElement.
   {
     // Find the number of nodes
     const unsigned n_node = nnode();
     // Find the number of positional types
     const unsigned n_position_type = nnodal_position_type();
     // Assign storage for the local shape function
     Shape psi(n_node, n_position_type);
     // Find the values of shape function
     shape(s, psi);
     // Initialise value of x
     double interpolated_x = 0.0;
     // Loop over the local nodes
     for (unsigned l = 0; l < n_node; l++)
     {
       // Loop over the number of dofs
       for (unsigned k = 0; k < n_position_type; k++)
       {
         interpolated_x += nodal_position_gen(l, k, i) * psi(l, k);
       }
     }
     return (interpolated_x);
   }
References i, k, nnodal_position_type(), nnode(), nodal_position_gen(), s, and shape().
Referenced by oomph::SpineUpdateFluidInterfaceElement< EQUATION_CLASS, DERIVATIVE_CLASS, ELEMENT >::add_additional_residual_contributions_interface(), oomph::Multi_domain_functions::aux_setup_multi_domain_interaction(), oomph::RefineableSolidQElement< 3 >::build(), oomph::RefineableSolidQElement< 2 >::build(), oomph::GmshTetMesh< ELEMENT >::build_from_scaffold(), oomph::TetgenMesh< ELEMENT >::build_from_scaffold(), oomph::TriangleMesh< ELEMENT >::build_from_scaffold(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::check_integrity(), oomph::RefineableQElement< 3 >::check_integrity(), oomph::RefineableQElement< 1 >::check_integrity(), oomph::RefineableQElement< 2 >::check_integrity(), oomph::AxisymAdvectionDiffusionEquations::compute_error(), oomph::AxisymFoepplvonKarmanEquations::compute_error(), oomph::AxisymmetricLinearElasticityEquations::compute_error(), oomph::BiharmonicEquations< DIM >::compute_error(), oomph::DisplacementBasedFoepplvonKarmanEquations::compute_error(), oomph::FoepplvonKarmanEquations::compute_error(), oomph::FourierDecomposedHelmholtzEquations::compute_error(), oomph::PMLFourierDecomposedHelmholtzEquations::compute_error(), oomph::SphericalAdvectionDiffusionEquations::compute_error(), oomph::SteadyAxisymAdvectionDiffusionEquations::compute_error(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::compute_error(), oomph::AxisymmetricPoroelasticityEquations::compute_error(), oomph::AxisymmetricNavierStokesEquations::compute_error(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::compute_error(), oomph::PolarNavierStokesEquations::compute_error(), oomph::SphericalNavierStokesEquations::compute_error(), oomph::EulerEquations< DIM >::compute_error(), oomph::ScalarAdvectionEquations< DIM >::compute_error(), oomph::SphericalNavierStokesEquations::compute_error_e(), oomph::SolidFiniteElement::compute_norm(), oomph::AxisymmetricNavierStokesEquations::compute_physical_size(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::compute_physical_size(), oomph::SphericalNavierStokesEquations::compute_shear_stress(), oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::compute_stabilisation_parameter(), oomph::SpineUpdateFluidInterfaceElement< EQUATION_CLASS, DERIVATIVE_CLASS, ELEMENT >::compute_surface_derivatives(), oomph::Z2ErrorEstimator::doc_flux(), oomph::FSI_functions::doc_fsi(), oomph::StefanBoltzmannHelper::doc_sample_points(), DiskShockWaveProblem< ELEMENT, TIMESTEPPER >::doc_solution(), CantileverProblem< ELEMENT >::doc_solution(), DiskOscillationProblem< ELEMENT >::doc_solution(), TestPoissonProblem< ELEMENT >::doc_solution(), FSIChannelWithLeafletProblem< ELEMENT >::doc_solution(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::edge_flux_interpolation_point_global(), oomph::TRaviartThomasDarcyElement< ORDER >::edge_flux_interpolation_point_global(), oomph::TPoroelasticityElement< ORDER >::edge_gauss_point_global(), UnsteadyHeatProblem< ELEMENT >::enforce_time_periodic_boundary_conditions(), oomph::ElementElementMortaringElement::evaluate_constraint_functions(), oomph::YoungLaplaceEquations::exact_position(), oomph::SphericalNavierStokesEquations::extract_velocity(), oomph::AxisymmetricNavierStokesEquations::fill_in_contribution_to_hessian_vector_products(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_contribution_to_hessian_vector_products(), oomph::DisplacementBasedFoepplvonKarmanEquations::fill_in_contribution_to_residuals(), oomph::FoepplvonKarmanEquations::fill_in_contribution_to_residuals(), oomph::DisplacementControlElement::fill_in_contribution_to_residuals(), oomph::KirchhoffLoveBeamEquations::fill_in_contribution_to_residuals_beam(), oomph::KirchhoffLoveShellEquations::fill_in_contribution_to_residuals_shell(), oomph::AxisymmetricLinearElasticityEquations::fill_in_generic_contribution_to_residuals_axisymmetric_linear_elasticity(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::fill_in_generic_contribution_to_residuals_fourier_decomp_time_harmonic_linear_elasticity(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), oomph::AxisymmetricNavierStokesEquations::fill_in_generic_dresidual_contribution_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_dresidual_contribution_axi_nst(), oomph::SolidFiniteElement::fill_in_generic_jacobian_for_solid_ic(), oomph::AxisymmetricPoroelasticityEquations::fill_in_generic_residual_contribution(), oomph::PolarNavierStokesEquations::fill_in_generic_residual_contribution(), oomph::RefineablePolarNavierStokesEquations::fill_in_generic_residual_contribution(), oomph::RefineablePolarStreamfunctionEquations::fill_in_generic_residual_contribution(), oomph::PolarStreamfunctionEquations::fill_in_generic_residual_contribution(), oomph::SteadyAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_adv_diff(), oomph::AxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), oomph::RefineableAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), oomph::AxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_cons_axisym_adv_diff(), oomph::FourierDecomposedHelmholtzEquations::fill_in_generic_residual_contribution_fourier_decomposed_helmholtz(), oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_lin_axi_nst(), oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::LinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst(), oomph::RefineableLinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst(), oomph::PMLFourierDecomposedHelmholtzEquations::fill_in_generic_residual_contribution_pml_fourier_decomposed_helmholtz(), oomph::RefineableSphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), oomph::SphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), oomph::RefineableSphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst(), oomph::SphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst(), FSICollapsibleChannelProblem< ELEMENT >::FSICollapsibleChannelProblem(), oomph::PolarNavierStokesEquations::full_output(), oomph::SphericalNavierStokesEquations::full_output(), oomph::AxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::Z2ErrorEstimator::get_element_errors(), oomph::KirchhoffLoveBeamEquations::get_energy(), oomph::Z2ErrorEstimator::get_recovered_flux_in_patch(), oomph::AxisymmetricLinearElasticityEquations::get_strain(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::get_strain(), oomph::KirchhoffLoveShellEquations::get_strain_and_bend(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::get_total_flux(), oomph::FSILinearisedAxisymPoroelasticTractionElement< POROELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >::get_traction(), get_x(), oomph::QSolidElementBase::get_x_and_xi(), integrate_fct(), oomph::AxisymmetricPoroelasticityEquations::interpolated_div_du_dt(), oomph::AxisymmetricPoroelasticityEquations::interpolated_div_q(), oomph::AxisymmetricPoroelasticityEquations::interpolated_div_u(), oomph::AxisymFoepplvonKarmanEquations::interpolated_stress(), interpolated_x(), oomph::FaceElement::interpolated_x(), oomph::AxisymmetricNavierStokesEquations::kin_energy(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::kin_energy(), oomph::RefineableQElement< 3 >::oc_hang_helper(), oomph::HermiteBeamElement::output(), oomph::PolarStreamfunctionEquations::output(), oomph::AxisymFoepplvonKarmanEquations::output(), oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >::output(), oomph::AxisymmetricLinearElasticityEquations::output(), oomph::FSILinearisedAxisymPoroelasticTractionElement< POROELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >::output(), oomph::AxisymmetricPVDEquations::output(), oomph::AxisymDiagHermitePVDElement::output(), oomph::AxisymmetricPVDEquationsWithPressure::output(), oomph::DisplacementBasedFoepplvonKarmanEquations::output(), oomph::FoepplvonKarmanEquations::output(), oomph::FourierDecomposedHelmholtzEquations::output(), oomph::PMLFourierDecomposedHelmholtzEquations::output(), oomph::HermiteShellElement::output(), oomph::ClampedHermiteShellBoundaryConditionElement::output(), oomph::FSISolidTractionElement< ELEMENT, DIM >::output(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::output(), oomph::YoungLaplaceEquations::output(), oomph::LinearisedAxisymmetricNavierStokesEquations::output(), oomph::THomogenisedLinearElasticityElement< DIM, NNODE_1D >::output(), oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::output(), oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::output(), oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::output(), oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement::output(), oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >::output(), oomph::MyTaylorHoodElement< DIM >::output(), oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::output(), oomph::AxisymAdvectionDiffusionEquations::output(), oomph::AxisymmetricNavierStokesEquations::output(), oomph::AxisymmetricPoroelasticityEquations::output(), oomph::BiharmonicEquations< DIM >::output(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::output(), oomph::LinearisedNavierStokesEquations::output(), oomph::BuoyantQCrouzeixRaviartElement< DIM >::output(), oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::output(), oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::output(), oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::output(), oomph::PolarNavierStokesEquations::output(), oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::output(), oomph::ProjectableUnsteadyHeatMixedOrderSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::output(), oomph::SphericalAdvectionDiffusionEquations::output(), oomph::SphericalNavierStokesEquations::output(), oomph::SteadyAxisymAdvectionDiffusionEquations::output(), oomph::ProjectableUnsteadyHeatElement< UNSTEADY_HEAT_ELEMENT >::output(), oomph::SolarRadiationBase::output_atmospheric_radiation(), oomph::SolarRadiationBase::output_diffuse_radiation_cone(), oomph::SolarRadiationBase::output_diffuse_radiation_cone_max_angle(), oomph::SolarRadiationBase::output_diffuse_radiation_cone_min_angle(), oomph::ElementWithExternalElement::output_external_elements(), oomph::AxisymFoepplvonKarmanEquations::output_fct(), oomph::DisplacementBasedFoepplvonKarmanEquations::output_fct(), oomph::FoepplvonKarmanEquations::output_fct(), oomph::FourierDecomposedHelmholtzEquations::output_fct(), oomph::PMLFourierDecomposedHelmholtzEquations::output_fct(), oomph::YoungLaplaceEquations::output_fct(), oomph::AxisymAdvectionDiffusionEquations::output_fct(), oomph::AxisymmetricLinearElasticityEquations::output_fct(), oomph::AxisymmetricNavierStokesEquations::output_fct(), oomph::AxisymmetricPoroelasticityEquations::output_fct(), oomph::BiharmonicEquations< DIM >::output_fct(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::output_fct(), oomph::PolarNavierStokesEquations::output_fct(), oomph::SphericalAdvectionDiffusionEquations::output_fct(), oomph::SphericalNavierStokesEquations::output_fct(), oomph::SteadyAxisymAdvectionDiffusionEquations::output_fct(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::output_fct(), oomph::BiharmonicEquations< DIM >::output_fluid_velocity(), oomph::SolarRadiationBase::output_limiting_angles(), output_paraview(), oomph::FourierDecomposedHelmholtzEquations::output_real(), oomph::PMLFourierDecomposedHelmholtzEquations::output_real(), oomph::FourierDecomposedHelmholtzEquations::output_real_fct(), oomph::PMLFourierDecomposedHelmholtzEquations::output_real_fct(), oomph::StefanBoltzmannRadiationBase::output_stefan_boltzmann_radiation_rays(), oomph::LinearisedAxisymmetricNavierStokesEquations::output_veloc(), oomph::AxisymmetricNavierStokesEquations::output_veloc(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::output_veloc(), oomph::LinearisedNavierStokesEquations::output_veloc(), oomph::PolarNavierStokesEquations::output_veloc(), oomph::SphericalNavierStokesEquations::output_veloc(), oomph::SphericalNavierStokesEquations::output_vorticity(), oomph::HermiteShellElement::output_with_time_dep_quantities(), PlateProblem< ELEMENT >::PlateProblem(), oomph::AxisymmetricNavierStokesEquations::point_output_data(), oomph::AxisymmetricPoroelasticityEquations::point_output_data(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::point_output_data(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::point_output_data(), oomph::NavierStokesEquations< DIM >::point_output_data(), oomph::PoissonEquations< DIM >::point_output_data(), oomph::SpaceTimeNavierStokesEquations< DIM >::point_output_data(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::point_output_data(), oomph::YoungLaplaceEquations::position(), position(), oomph::AxisymmetricNavierStokesEquations::pressure_integral(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::pressure_integral(), oomph::RefineableQElement< 2 >::quad_hang_helper(), oomph::RefineableFSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::residual_for_projection(), oomph::ProjectableDarcyElement< DARCY_ELEMENT >::residual_for_projection(), oomph::ProjectableElement< ELEMENT >::residual_for_projection(), oomph::NavierStokesEquations< DIM >::scalar_value_fct_paraview(), oomph::SpaceTimeNavierStokesEquations< DIM >::scalar_value_fct_paraview(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::scalar_value_fct_paraview(), oomph::PMLHelmholtzEquations< DIM >::scalar_value_fct_paraview(), oomph::PoissonEquations< DIM >::scalar_value_fct_paraview(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::scalar_value_fct_paraview(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::scalar_value_fct_paraview(), oomph::AdvectionDiffusionEquations< DIM >::scalar_value_paraview(), oomph::AxisymAdvectionDiffusionEquations::scalar_value_paraview(), oomph::StefanBoltzmannHelper::setup_stefan_boltzmann_visibility(), ShellProblem< ELEMENT >::ShellProblem(), oomph::PolarNavierStokesEquations::strain_rate(), oomph::PolarNavierStokesEquations::strain_rate_by_r(), and oomph::SolarRadiationBase::update_limiting_angles().
interpolated_x() [4/4]
void FiniteElement::interpolated_x (const Vector< double > & s, Vector< double > & x) const virtual
Return FE interpolated position x[] at local coordinate s as Vector.
Reimplemented in oomph::FaceElement.
   {
     // Find the number of nodes
     const unsigned n_node = nnode();
     // Find the number of positional types
     const unsigned n_position_type = nnodal_position_type();
     // Find the dimension stored in the node
     const unsigned nodal_dim = nodal_dimension();
     // Assign storage for the local shape function
     Shape psi(n_node, n_position_type);
     // Find the values of shape function
     shape(s, psi);
     // Loop over the dimensions
     for (unsigned i = 0; i < nodal_dim; i++)
     {
       // Initilialise value of x[i] to zero
       x[i] = 0.0;
       // Loop over the local nodes
       for (unsigned l = 0; l < n_node; l++)
       {
         // Loop over the number of dofs
         for (unsigned k = 0; k < n_position_type; k++)
         {
           x[i] += nodal_position_gen(l, k, i) * psi(l, k);
         }
       }
     }
   }
References i, k, nnodal_position_type(), nnode(), nodal_dimension(), nodal_position_gen(), s, shape(), and plotDoE::x.
interpolated_zeta()
void FiniteElement::interpolated_zeta (const Vector< double > & s, Vector< double > & zeta) const virtual
Calculate the interpolated value of zeta, the intrinsic coordinate of the element when viewed as a compound geometric object within a Mesh as a function of the local coordinate of the element, s. The default assumption is the zeta is interpolated using the shape functions of the element with the values given by zeta_nodal(). A MacroElement representation of the intrinsic coordinate parametrised by the local coordinate s is used if available. Choosing the MacroElement representation of zeta (Eulerian x by default) allows a correspondence to be established between elements on different Meshes covering the same curvilinear domain in cases where one element is much coarser than the other.
Reimplemented from oomph::GeomObject.
   {
     // If there is a macro element use it
     if (Macro_elem_pt != 0)
     {
       this->get_x_from_macro_element(s, zeta);
     }
     // Otherwise interpolate zeta_nodal using the shape functions
     else
     {
       // Find the number of nodes
       const unsigned n_node = this->nnode();
       // Find the number of positional types
       const unsigned n_position_type = this->nnodal_position_type();
       // Storage for the shape functions
       Shape psi(n_node, n_position_type);
       // Get the values of the shape functions at the local coordinate s
       this->shape(s, psi);
       // Find the number of coordinates
       const unsigned ncoord = this->dim();
       // Initialise the value of zeta to zero
       for (unsigned i = 0; i < ncoord; i++)
       {
         zeta[i] = 0.0;
       }
       // Add the contributions from each nodal dof to the interpolated value
       // of zeta.
       for (unsigned l = 0; l < n_node; l++)
       {
         for (unsigned k = 0; k < n_position_type; k++)
         {
           // Locally cache the value of the shape function
           const double psi_ = psi(l, k);
           for (unsigned i = 0; i < ncoord; i++)
           {
             zeta[i] += this->zeta_nodal(l, k, i) * psi_;
           }
         }
       }
     }
   }
References dim(), get_x_from_macro_element(), i, k, Macro_elem_pt, nnodal_position_type(), nnode(), shape(), Eigen::zeta(), and zeta_nodal().
Referenced by oomph::BrickFromTetMesh< ELEMENT >::build_mesh(), UnstructuredFluidProblem< ELEMENT >::doc_boundary_coordinates(), oomph::Mesh::doc_boundary_coordinates(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solid_boundary_coordinates(), UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solid_boundary_coordinates(), oomph::RefineableYoungLaplaceEquations::fill_in_contribution_to_residuals(), oomph::YoungLaplaceEquations::fill_in_contribution_to_residuals(), oomph::Multi_domain_functions::first_closer_than_second(), oomph::FSIHermiteBeamElement::locate_zeta(), locate_zeta(), oomph::Multi_domain_functions::locate_zeta_for_local_coordinates(), oomph::FSIAxisymmetricLinearElasticityTractionElement< ELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >::output(), oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::output(), oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::output(), oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::output(), oomph::TimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::output(), oomph::HelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::output(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::output(), oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::output(), oomph::FaceElement::output_zeta(), oomph::Multi_domain_functions::setup_bulk_elements_adjacent_to_face_mesh(), and oomph::ThinLayerBrickOnTetMesh< ELEMENT >::ThinLayerBrickOnTetMesh().
invert_jacobian() [1/5]
template<> double oomph::FiniteElement::invert_jacobian (const DenseMatrix< double > & jacobian, DenseMatrix< double > & inverse_jacobian) const protected
Zero-d specialisation of function to calculate inverse of jacobian mapping.
   {
     // Issue a warning
     oomph_info << "\nWarning: You are trying to invert the jacobian for "
                << "a 'point' element" << std::endl
                << "This makes no sense and is almost certainly an error"
                << std::endl
                << std::endl;
     // Dummy return
     return (1.0);
   }
References oomph::oomph_info.
invert_jacobian() [2/5]
template<> double oomph::FiniteElement::invert_jacobian (const DenseMatrix< double > & jacobian, DenseMatrix< double > & inverse_jacobian) const protected
One-d specialisation of function to calculate inverse of jacobian mapping.
   {
     // Calculate the determinant of the matrix
     const double det = jacobian(0, 0);
 // Report if Matrix is singular or negative
 #ifdef PARANOID
     check_jacobian(det);
 #endif
     // Calculate the inverse --- trivial in 1D
     inverse_jacobian(0, 0) = 1.0 / jacobian(0, 0);
     // Return the determinant
     return (det);
   }
References check_jacobian().
invert_jacobian() [3/5]
template<> double oomph::FiniteElement::invert_jacobian (const DenseMatrix< double > & jacobian, DenseMatrix< double > & inverse_jacobian) const protected
Two-d specialisation of function to calculate inverse of jacobian mapping.
   {
     // Calculate the determinant of the matrix
     const double det =
       jacobian(0, 0) * jacobian(1, 1) - jacobian(0, 1) * jacobian(1, 0);
 // Report if Matrix is singular or negative
 #ifdef PARANOID
     check_jacobian(det);
 #endif
     // Calculate the inverset of the 2x2 matrix
     inverse_jacobian(0, 0) = jacobian(1, 1) / det;
     inverse_jacobian(0, 1) = -jacobian(0, 1) / det;
     inverse_jacobian(1, 0) = -jacobian(1, 0) / det;
     inverse_jacobian(1, 1) = jacobian(0, 0) / det;
     // Return the jacobian
     return (det);
   }
References check_jacobian().
invert_jacobian() [4/5]
template<> double oomph::FiniteElement::invert_jacobian (const DenseMatrix< double > & jacobian, DenseMatrix< double > & inverse_jacobian) const protected
Three-d specialisation of function to calculate inverse of jacobian mapping
   {
     // Calculate the determinant of the matrix
     const double det = jacobian(0, 0) * jacobian(1, 1) * jacobian(2, 2) +
                        jacobian(0, 1) * jacobian(1, 2) * jacobian(2, 0) +
                        jacobian(0, 2) * jacobian(1, 0) * jacobian(2, 1) -
                        jacobian(0, 0) * jacobian(1, 2) * jacobian(2, 1) -
                        jacobian(0, 1) * jacobian(1, 0) * jacobian(2, 2) -
                        jacobian(0, 2) * jacobian(1, 1) * jacobian(2, 0);
     // Report if Matrix is singular or negative
 #ifdef PARANOID
     check_jacobian(det);
 #endif
     // Calculate the inverse of the 3x3 matrix
     inverse_jacobian(0, 0) =
       (jacobian(1, 1) * jacobian(2, 2) - jacobian(1, 2) * jacobian(2, 1)) / det;
     inverse_jacobian(0, 1) =
       -(jacobian(0, 1) * jacobian(2, 2) - jacobian(0, 2) * jacobian(2, 1)) /
       det;
     inverse_jacobian(0, 2) =
       (jacobian(0, 1) * jacobian(1, 2) - jacobian(0, 2) * jacobian(1, 1)) / det;
     inverse_jacobian(1, 0) =
       -(jacobian(1, 0) * jacobian(2, 2) - jacobian(1, 2) * jacobian(2, 0)) /
       det;
     inverse_jacobian(1, 1) =
       (jacobian(0, 0) * jacobian(2, 2) - jacobian(0, 2) * jacobian(2, 0)) / det;
     inverse_jacobian(1, 2) =
       -(jacobian(0, 0) * jacobian(1, 2) - jacobian(0, 2) * jacobian(1, 0)) /
       det;
     inverse_jacobian(2, 0) =
       (jacobian(1, 0) * jacobian(2, 1) - jacobian(1, 1) * jacobian(2, 0)) / det;
     inverse_jacobian(2, 1) =
       -(jacobian(0, 0) * jacobian(2, 1) - jacobian(0, 1) * jacobian(2, 0)) /
       det;
     inverse_jacobian(2, 2) =
       (jacobian(0, 0) * jacobian(1, 1) - jacobian(0, 1) * jacobian(1, 0)) / det;
     // Return the determinant
     return (det);
   }
References check_jacobian().
invert_jacobian() [5/5]
template<unsigned DIM> double oomph::FiniteElement::invert_jacobian (const DenseMatrix< double > & jacobian, DenseMatrix< double > & inverse_jacobian) const protected
Take the matrix passed as jacobian and return its inverse in inverse_jacobian. This function is templated by the dimension of the element because matrix inversion cannot be written efficiently in a generic manner.
invert_jacobian_mapping()
double FiniteElement::invert_jacobian_mapping (const DenseMatrix< double > & jacobian, DenseMatrix< double > & inverse_jacobian) const protected virtual
A template-free interface that takes the matrix passed as jacobian and return its inverse in inverse_jacobian. By default the function will use the dimension of the element to call the correct invert_jacobian(..) function. This should be overloaded for efficiency (removal of a switch statement) in specific elements.
Template-free interface for inversion of the jacobian of a mapping. This is slightly inefficient, given that it uses a switch statement. It can always be overloaded in specific geometric elements, for efficiency reasons.
Reimplemented in oomph::TElement< 3, NNODE_1D >, oomph::TElement< 2, NNODE_1D >, oomph::TElement< 1, NNODE_1D >, oomph::QSpectralElement< 3, NNODE_1D >, oomph::QSpectralElement< 2, NNODE_1D >, oomph::QSpectralElement< 1, NNODE_1D >, oomph::QElement< 3, NNODE_1D >, oomph::QElement< 2, NNODE_1D >, oomph::QElement< 1, NNODE_1D >, oomph::DiagQHermiteElement< DIM >, oomph::QHermiteElement< DIM >, and oomph::QHermiteElement< DIM - 1 >.
   {
     // Find the spatial dimension of the element
     const unsigned el_dim = dim();
     // Call the appropriate templated function, depending on the
     // element dimension
     switch (el_dim)
     {
       case 0:
         return invert_jacobian<0>(jacobian, inverse_jacobian);
         break;
       case 1:
         return invert_jacobian<1>(jacobian, inverse_jacobian);
         break;
       case 2:
         return invert_jacobian<2>(jacobian, inverse_jacobian);
         break;
       case 3:
         return invert_jacobian<3>(jacobian, inverse_jacobian);
         break;
         // Catch-all default case: issue warning and die
       default:
         std::ostringstream error_stream;
         error_stream << "Dimension of the element must be 0,1,2 or 3, not "
                      << el_dim << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
     // Dummy return for Intel compiler
     return 1.0;
   }
References dim(), el_dim, OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by local_to_eulerian_mapping(), and oomph::SolidFiniteElement::local_to_lagrangian_mapping().
J_eulerian()
double FiniteElement::J_eulerian (const Vector< double > & s) const virtual
Return the Jacobian of mapping from local to global coordinates at local position s.
Calculate the determinant of the Jacobian of the mapping between local and global coordinates at the position. Works directly from the base vectors without assuming that coordinates match spatial dimension. Will be overloaded in FaceElements, in which the elemental dimension does not match the spatial dimension. WARNING: this is always positive and cannot be used to check if the element is inverted, say!
Reimplemented in oomph::FaceElement, oomph::BiharmonicFluxElement< DIM >, and oomph::BiharmonicFluxElement< DIM >.
   {
     // Find the number of nodes and position types
     const unsigned n_node = nnode();
     const unsigned n_position_type = nnodal_position_type();
     // Find the dimension of the node and element
     const unsigned n_dim_node = nodal_dimension();
     const unsigned n_dim_element = dim();
     // Set up dummy memory for the shape functions
     Shape psi(n_node, n_position_type);
     DShape dpsids(n_node, n_position_type, n_dim_element);
     // Get the shape functions and local derivatives
     dshape_local(s, psi, dpsids);
     // Right calculate the base vectors
     DenseMatrix<double> interpolated_G(n_dim_element, n_dim_node);
     assemble_eulerian_base_vectors(dpsids, interpolated_G);
     // Calculate the metric tensor of the element
     DenseMatrix<double> G(n_dim_element, n_dim_element, 0.0);
     for (unsigned i = 0; i < n_dim_element; i++)
     {
       for (unsigned j = 0; j < n_dim_element; j++)
       {
         for (unsigned k = 0; k < n_dim_node; k++)
         {
           G(i, j) += interpolated_G(i, k) * interpolated_G(j, k);
         }
       }
     }
     // Calculate the determinant of the metric tensor
     double det = 0.0;
     switch (n_dim_element)
     {
       case 0:
         throw OomphLibError("Cannot calculate J_eulerian() for point element\n",
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
         break;
       case 1:
         det = G(0, 0);
         break;
       case 2:
         det = G(0, 0) * G(1, 1) - G(0, 1) * G(1, 0);
         break;
       case 3:
         det = G(0, 0) * G(1, 1) * G(2, 2) + G(0, 1) * G(1, 2) * G(2, 0) +
               G(0, 2) * G(1, 0) * G(2, 1) - G(0, 0) * G(1, 2) * G(2, 1) -
               G(0, 1) * G(1, 0) * G(2, 2) - G(0, 2) * G(1, 1) * G(2, 0);
         break;
       default:
         oomph_info << "More than 3 dimensions in J_eulerian()" << std::endl;
         break;
     }
     // Return the Jacobian (square-root of the determinant of the metric tensor)
     return sqrt(det);
   }
References assemble_eulerian_base_vectors(), dim(), dshape_local(), G, i, j, k, nnodal_position_type(), nnode(), nodal_dimension(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::oomph_info, s, and sqrt().
Referenced by oomph::AxisymAdvectionDiffusionEquations::compute_error(), oomph::AxisymFoepplvonKarmanEquations::compute_error(), oomph::AxisymmetricLinearElasticityEquations::compute_error(), oomph::BiharmonicEquations< DIM >::compute_error(), oomph::DisplacementBasedFoepplvonKarmanEquations::compute_error(), oomph::FoepplvonKarmanEquations::compute_error(), oomph::FourierDecomposedHelmholtzEquations::compute_error(), oomph::PMLFourierDecomposedHelmholtzEquations::compute_error(), oomph::SphericalAdvectionDiffusionEquations::compute_error(), oomph::SteadyAxisymAdvectionDiffusionEquations::compute_error(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::compute_error(), oomph::YoungLaplaceEquations::compute_error(), oomph::AxisymmetricPoroelasticityEquations::compute_error(), oomph::AxisymmetricNavierStokesEquations::compute_error(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::compute_error(), oomph::PolarNavierStokesEquations::compute_error(), oomph::SphericalNavierStokesEquations::compute_error(), oomph::SphericalNavierStokesEquations::compute_error_e(), oomph::SolidFiniteElement::compute_norm(), oomph::FourierDecomposedHelmholtzEquations::compute_norm(), oomph::PMLFourierDecomposedHelmholtzEquations::compute_norm(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::compute_norm(), oomph::AxisymmetricNavierStokesEquations::compute_physical_size(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::compute_physical_size(), oomph::AxisymmetricNavierStokesEquations::dissipation(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::dissipation(), oomph::PolarNavierStokesEquations::dissipation(), oomph::SphericalNavierStokesEquations::dissipation(), oomph::LinearisedAxisymmetricNavierStokesEquations::dkin_energy_dt(), oomph::SphericalNavierStokesEquations::extract_velocity(), oomph::Z2ErrorEstimator::get_element_errors(), oomph::Z2ErrorEstimator::get_recovered_flux_in_patch(), integrate_fct(), oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectablePVDElement< PVD_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectablePVDElementWithContinuousPressure< PVD_ELEMENT >::jacobian_and_shape_of_field(), oomph::AxisymmetricNavierStokesEquations::kin_energy(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::kin_energy(), oomph::PolarNavierStokesEquations::kin_energy(), oomph::SphericalNavierStokesEquations::kin_energy(), oomph::AxisymmetricNavierStokesEquations::pressure_integral(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::pressure_integral(), oomph::PolarNavierStokesEquations::pressure_integral(), oomph::SphericalNavierStokesEquations::pressure_integral(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::residual_for_projection(), oomph::ProjectableDarcyElement< DARCY_ELEMENT >::residual_for_projection(), oomph::ProjectableElement< ELEMENT >::residual_for_projection(), and self_test().
J_eulerian_at_knot()
double FiniteElement::J_eulerian_at_knot (const unsigned & ipt) const virtual
Return the Jacobian of the mapping from local to global coordinates at the ipt-th integration point
Compute the Jacobian of the mapping between the local and global coordinates at the ipt-th integration point
Reimplemented in oomph::StorableShapeElementBase, and oomph::FaceElement.
   {
     // Find the number of nodes
     const unsigned n_node = nnode();
     // Find the number of position types
     const unsigned n_position_type = nnodal_position_type();
     // Find the dimension of the node and element
     const unsigned n_dim_node = nodal_dimension();
     const unsigned n_dim_element = dim();
     // Set up dummy memory for the shape functions
     Shape psi(n_node, n_position_type);
     DShape dpsids(n_node, n_position_type, n_dim_element);
     // Get the shape functions and local derivatives at the knot
     // This call may use the stored versions, which is why this entire
     // function doesn't just call J_eulerian(s), after reading out s from
     // the knots.
     dshape_local_at_knot(ipt, psi, dpsids);
     // Right calculate the base vectors
     DenseMatrix<double> interpolated_G(n_dim_element, n_dim_node);
     assemble_eulerian_base_vectors(dpsids, interpolated_G);
     // Calculate the metric tensor of the element
     DenseMatrix<double> G(n_dim_element, n_dim_element, 0.0);
     for (unsigned i = 0; i < n_dim_element; i++)
     {
       for (unsigned j = 0; j < n_dim_element; j++)
       {
         for (unsigned k = 0; k < n_dim_node; k++)
         {
           G(i, j) += interpolated_G(i, k) * interpolated_G(j, k);
         }
       }
     }
     // Calculate the determinant of the metric tensor
     double det = 0.0;
     switch (n_dim_element)
     {
       case 0:
         throw OomphLibError("Cannot calculate J_eulerian() for point element\n",
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
         break;
       case 1:
         det = G(0, 0);
         break;
       case 2:
         det = G(0, 0) * G(1, 1) - G(0, 1) * G(1, 0);
         break;
       case 3:
         det = G(0, 0) * G(1, 1) * G(2, 2) + G(0, 1) * G(1, 2) * G(2, 0) +
               G(0, 2) * G(1, 0) * G(2, 1) - G(0, 0) * G(1, 2) * G(2, 1) -
               G(0, 1) * G(1, 0) * G(2, 2) - G(0, 2) * G(1, 1) * G(2, 0);
         break;
       default:
         oomph_info << "More than 3 dimensions in J_eulerian()" << std::endl;
         break;
     }
     // Return the Jacobian (square-root of the determinant of the metric tensor)
     return sqrt(det);
   }
References assemble_eulerian_base_vectors(), dim(), dshape_local_at_knot(), G, i, j, k, nnodal_position_type(), nnode(), nodal_dimension(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::oomph_info, and sqrt().
Referenced by oomph::AxisymmetricNavierStokesEquations::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::SphericalNavierStokesEquations::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::integrated_C_and_M(), oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >::integrated_C_and_M(), oomph::StorableShapeElementBase::J_eulerian_at_knot(), oomph::StorableShapeElementBase::pre_compute_J_eulerian_at_knots(), and size().
local_coord_is_valid()
virtual bool oomph::FiniteElement::local_coord_is_valid (const Vector< double > & s) inline virtual
Broken assignment operator.
Check whether the local coordinate are valid or not
Reimplemented in oomph::TElementBase, oomph::QElementBase, oomph::QHermiteElement< DIM >, and oomph::QHermiteElement< DIM - 1 >.
     {
       throw OomphLibError(
         "local_coord_is_valid is not implemented for this element\n",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
       return true;
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by locate_zeta().
local_coordinate_of_node()
virtual void oomph::FiniteElement::local_coordinate_of_node (const unsigned & j, Vector< double > & s) const inline virtual
Get local coordinates of node j in the element; vector sets its own size (broken virtual)
Reimplemented in oomph::QSpectralElement< 3, NNODE_1D >, oomph::QSpectralElement< 2, NNODE_1D >, oomph::QSpectralElement< 1, NNODE_1D >, oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >, oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >, oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >, oomph::TElement< 3, NNODE_1D >, oomph::TElement< 2, NNODE_1D >, oomph::TElement< 1, NNODE_1D >, oomph::QElement< 3, NNODE_1D >, oomph::QElement< 2, NNODE_1D >, oomph::QElement< 1, NNODE_1D >, oomph::QHermiteElement< DIM >, oomph::QHermiteElement< DIM - 1 >, and oomph::PointElement.
     {
       throw OomphLibError(
         "local_coordinate_of_node(...) is not implemented for this element\n",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::TreeBasedRefineableMeshBase::adapt_mesh(), oomph::GmshTetMesh< ELEMENT >::build_from_scaffold(), oomph::TetgenMesh< ELEMENT >::build_from_scaffold(), oomph::TriangleMesh< ELEMENT >::build_from_scaffold(), oomph::BrickFromTetMesh< ELEMENT >::build_mesh(), oomph::TPVDElement< DIM, NNODE_1D >::describe_local_dofs(), oomph::SpaceTimeNavierStokesEquations< DIM >::du_dt_nst(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::du_dt_nst(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::du_dt_ust_heat(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::du_dt_ust_heat(), SCoupling< M, O >::getSCoupledElements(), TwoDDGProblem< ELEMENT >::limit(), local_fraction_of_node(), oomph::Mesh::node_update(), oomph::TreeBasedRefineableMeshBase::p_adapt_mesh(), oomph::MacroElementNodeUpdateElement< ELEMENT >::rebuild_from_sons(), oomph::MacroElementNodeUpdateElement< ELEMENT >::set_node_update_info(), and oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::setup_algebraic_node_update().
local_fraction_of_node()
void FiniteElement::local_fraction_of_node (const unsigned & j, Vector< double > & s_fraction) virtual
Get the local fraction of the node j in the element A dumb, but correct default implementation is provided.
Get the local fraction of the node j in the element; vector sets its own size
Reimplemented in oomph::QSpectralElement< 3, NNODE_1D >, oomph::QSpectralElement< 2, NNODE_1D >, oomph::QSpectralElement< 1, NNODE_1D >, oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >, oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >, oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >, oomph::QElement< 3, NNODE_1D >, oomph::QElement< 2, NNODE_1D >, oomph::QElement< 1, NNODE_1D >, oomph::QHermiteElement< DIM >, and oomph::QHermiteElement< DIM - 1 >.
   {
     // Default implementation is rather dumb
     // Get the local coordinate and scale by local coordinate range
     local_coordinate_of_node(j, s_fraction);
     unsigned n_coordinates = s_fraction.size();
     for (unsigned i = 0; i < n_coordinates; i++)
     {
       s_fraction[i] = (s_fraction[i] - s_min()) / (s_max() - s_min());
     }
   }
References i, j, local_coordinate_of_node(), s_max(), and s_min().
Referenced by oomph::EighthSphereMesh< ELEMENT >::EighthSphereMesh(), and OneDimMesh< ELEMENT >::OneDimMesh().
local_one_d_fraction_of_node()
virtual double oomph::FiniteElement::local_one_d_fraction_of_node (const unsigned & n1d, const unsigned & i) inline virtual
Get the local fraction of any node in the n-th position in a one dimensional expansion along the i-th local coordinate
Reimplemented in oomph::QSpectralElement< 3, NNODE_1D >, oomph::QSpectralElement< 2, NNODE_1D >, oomph::QSpectralElement< 1, NNODE_1D >, oomph::QElement< 3, NNODE_1D >, oomph::QElement< 2, NNODE_1D >, oomph::QElement< 1, NNODE_1D >, oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >, oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >, oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >, oomph::QHermiteElement< DIM >, and oomph::QHermiteElement< DIM - 1 >.
     {
       std::string error_message =
         "local one_d_fraction_of_node is not implemented for this element\n";
       error_message +=
         "It only makes sense for elements that use tensor-product expansions\n";
       throw OomphLibError(
         error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
Referenced by oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::local_one_d_fraction_of_interpolating_node(), oomph::RefineableAxisymmetricQTaylorHoodElement::local_one_d_fraction_of_interpolating_node(), oomph::RefineableGeneralisedNewtonianAxisymmetricQTaylorHoodElement::local_one_d_fraction_of_interpolating_node(), oomph::RefineableLinearisedQTaylorHoodElement::local_one_d_fraction_of_interpolating_node(), oomph::RefineableQSphericalTaylorHoodElement::local_one_d_fraction_of_interpolating_node(), oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::local_one_d_fraction_of_interpolating_node(), oomph::RefineableElement::local_one_d_fraction_of_interpolating_node(), oomph::RefineableQTaylorHoodElement< DIM >::local_one_d_fraction_of_interpolating_node(), oomph::RefineablePolarTaylorHoodElement::local_one_d_fraction_of_interpolating_node(), oomph::RefineableQPVDElementWithContinuousPressure< DIM >::local_one_d_fraction_of_interpolating_node(), oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::local_one_d_fraction_of_interpolating_node(), and oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >::local_one_d_fraction_of_interpolating_node().
local_to_eulerian_mapping() [1/2]
double oomph::FiniteElement::local_to_eulerian_mapping (const DShape & dpsids, DenseMatrix< double > & inverse_jacobian) const inline protected
Calculate the mapping from local to Eulerian coordinates, given the derivatives of the shape functions w.r.t. local coordinates, Return only the determinant of the jacobian and the inverse of the mapping (ds/dx).
     {
       // Find the dimension of the element
       const unsigned el_dim = dim();
       // Assign memory for the jacobian
       DenseMatrix<double> jacobian(el_dim);
       // Calculate the jacobian and inverse
       return local_to_eulerian_mapping(dpsids, jacobian, inverse_jacobian);
     }
References dim(), el_dim, and local_to_eulerian_mapping().
local_to_eulerian_mapping() [2/2]
virtual double oomph::FiniteElement::local_to_eulerian_mapping (const DShape & dpsids, DenseMatrix< double > & jacobian, DenseMatrix< double > & inverse_jacobian) const inline protected virtual
Calculate the mapping from local to Eulerian coordinates, given the derivatives of the shape functions w.r.t. local coordinates. Returns the determinant of the jacobian, the jacobian and inverse jacobian
Reimplemented in oomph::DiagQHermiteElement< DIM >.
     {
       // Assemble the jacobian
       assemble_local_to_eulerian_jacobian(dpsids, jacobian);
       // Invert the jacobian (use the template-free interface)
       return invert_jacobian_mapping(jacobian, inverse_jacobian);
     }
References assemble_local_to_eulerian_jacobian(), and invert_jacobian_mapping().
Referenced by d2shape_eulerian(), d2shape_eulerian_at_knot(), dJ_eulerian_at_knot(), oomph::AxisymmetricTCrouzeixRaviartElement::dpshape_and_dptest_eulerian_axi_nst(), oomph::AxisymmetricTTaylorHoodElement::dpshape_and_dptest_eulerian_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::dpshape_and_dptest_eulerian_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::dpshape_and_dptest_eulerian_axi_nst(), dshape_eulerian(), dshape_eulerian_at_knot(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::get_flux(), oomph::AxisymmetricNavierStokesEquations::interpolated_d_dudx_dX_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::interpolated_d_dudx_dX_axi_nst(), oomph::AxisymmetricPoroelasticityEquations::interpolated_div_q(), oomph::DarcyEquations< DIM >::interpolated_div_q(), oomph::PoroelasticityEquations< DIM >::interpolated_div_q(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::interpolated_du_dt_nst(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::interpolated_du_dt_ust_heat(), local_to_eulerian_mapping(), and oomph::AxisymmetricPoroelasticityEquations::transform_basis().
local_to_eulerian_mapping_diagonal()
double FiniteElement::local_to_eulerian_mapping_diagonal (const DShape & dpsids, DenseMatrix< double > & jacobian, DenseMatrix< double > & inverse_jacobian) const protected virtual
Calculate the mapping from local to Eulerian coordinates given the derivatives of the shape functions w.r.t the local coordinates. assuming that the coordinates are aligned in the direction of the local coordinates, i.e. there are no cross terms and the jacobian is diagonal. This function returns the determinant of the jacobian, the jacobian and the inverse jacobian.
Calculate the mapping from local to eulerian coordinates assuming that the coordinates are aligned in the direction of the local coordinates, i.e. there are no cross terms and the jacobian is diagonal. The local derivatives are passed as dpsids and the jacobian and inverse jacobian are returned.
Reimplemented in oomph::RefineableElement.
   {
     // Find the dimension of the element
     const unsigned el_dim = dim();
     // Find the number of shape functions and shape functions types
     // Equal to the number of nodes and their position types by definition
     const unsigned n_shape = nnode();
     const unsigned n_shape_type = nnodal_position_type();
 #ifdef PARANOID
     // Check for dimension compatibility
     if (Elemental_dimension != Nodal_dimension)
     {
       std::ostringstream error_message;
       error_message << "Dimension mismatch" << std::endl;
       error_message << "The elemental dimension: " << Elemental_dimension
                     << " must equal the nodal dimension: " << Nodal_dimension
                     << " for the jacobian of the mapping to be well-defined"
                     << std::endl;
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // In this case we assume that there are no cross terms, that is
     // global coordinate 0 is always in the direction of local coordinate 0
     // Loop over the coordinates
     for (unsigned i = 0; i < el_dim; i++)
     {
       // Zero the jacobian and inverse jacobian entries
       for (unsigned j = 0; j < el_dim; j++)
       {
         jacobian(i, j) = 0.0;
         inverse_jacobian(i, j) = 0.0;
       }
       // Loop over the shape functions
       for (unsigned l = 0; l < n_shape; l++)
       {
         // Loop over the types of dof
         for (unsigned k = 0; k < n_shape_type; k++)
         {
           // Derivatives are always dx_{i}/ds_{i}
           jacobian(i, i) += raw_nodal_position_gen(l, k, i) * dpsids(l, k, i);
         }
       }
     }
     // Now calculate the determinant of the matrix
     double det = 1.0;
     for (unsigned i = 0; i < el_dim; i++)
     {
       det *= jacobian(i, i);
     }
 // Report if Matrix is singular, or negative
 #ifdef PARANOID
     check_jacobian(det);
 #endif
     // Calculate the inverse mapping (trivial in this case)
     for (unsigned i = 0; i < el_dim; i++)
     {
       inverse_jacobian(i, i) = 1.0 / jacobian(i, i);
     }
     // Return the value of the Jacobian
     return (det);
   }
References check_jacobian(), dim(), el_dim, Elemental_dimension, i, j, k, nnodal_position_type(), nnode(), Nodal_dimension, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and raw_nodal_position_gen().
Referenced by oomph::DiagQHermiteElement< DIM >::local_to_eulerian_mapping().
locate_zeta()
void FiniteElement::locate_zeta (const Vector< double > & zeta, GeomObject *& geom_object_pt, Vector< double > & s, const bool & use_coordinate_as_initial_guess = false) virtual
For a given value of zeta, the "global" intrinsic coordinate of a mesh of FiniteElements represented as a compound geometric object, find the local coordinate in this element that corresponds to the requested value of zeta. If zeta cannot be located in this element, geom_object_pt is set to NULL. If zeta is located in this element, we return its "this" pointer. By default don't use any value passed in to the local coordinate s as the initial guess in the Newton method
For a given value of zeta, the "global" intrinsic coordinate of a mesh of FiniteElements represented as a compound geometric object, find the local coordinate in this element that corresponds to the requested value of zeta. This is achieved in generality by using Newton's method to find the value of the local coordinate, s, such that interpolated_zeta(s) is equal to the requested value of zeta. If zeta cannot be located in this element, geom_object_pt is set to NULL. If zeta is located in this element, we return its "this" pointer. Setting the optional bool argument to true means that the coordinate argument "s" is used as the initial guess. (Default is false).
Reimplemented from oomph::GeomObject.
   {
     // Find the number of coordinates, the dimension of the element
     // This must be the same for the local and intrinsic global coordinate
     unsigned ncoord = this->dim();
     // Fast return based on centre of gravity and max. radius of any nodal
     // point
     if (Locate_zeta_helpers::Radius_multiplier_for_fast_exit_from_locate_zeta >
         0.0)
     {
       Vector<double> cog(ncoord);
       double max_radius = 0.0;
       get_centre_of_gravity_and_max_radius_in_terms_of_zeta(cog, max_radius);
       // Get radius
       double radius = 0.0;
       for (unsigned i = 0; i < ncoord; i++)
       {
         radius += (cog[i] - zeta[i]) * (cog[i] - zeta[i]);
       }
       radius = sqrt(radius);
       if (radius > Locate_zeta_helpers::
                        Radius_multiplier_for_fast_exit_from_locate_zeta *
                      max_radius)
       {
         geom_object_pt = 0;
         return;
       }
     }
     // Assign storage for the vector and matrix used in Newton's method
     Vector<double> dx(ncoord, 0.0);
     DenseDoubleMatrix jacobian(ncoord, ncoord, 0.0);
     // // Make a list of (equally-spaced) local coordinates inside the element
     // unsigned n_list=Locate_zeta_helpers::N_local_points;
     // double list_space=(1.0/(double(n_list)-1.0))*(s_max()-s_min());
     // Possible initial guesses for Newton's method
     Vector<Vector<double>> s_list;
     // If the boolean argument use_coordinate_as_initial_guess was set
     // to true then we don't need to initialise s
     if (!use_coordinate_as_initial_guess)
     {
       // Vector of local coordinates
       Vector<double> s_c(ncoord);
       // Loop over plot points
       unsigned num_plot_points =
         nplot_points(Locate_zeta_helpers::N_local_points);
       for (unsigned iplot = 0; iplot < num_plot_points; iplot++)
       {
         // Get local coordinates of plot point
         get_s_plot(iplot, Locate_zeta_helpers::N_local_points, s_c);
         s_list.push_back(s_c);
       }
     }
     // Counter for the number of Newton steps
     unsigned count = 0;
     // Control flag for the Newton loop
     bool keep_going = true;
     // Storage for the interpolated value of x
     Vector<double> inter_x(ncoord);
     // Ifwe have specified the coordinate already
     if (use_coordinate_as_initial_guess)
     {
       // Get the value of x at the initial guess
       this->interpolated_zeta(s, inter_x);
       // Set up the residuals
       for (unsigned i = 0; i < ncoord; i++)
       {
         dx[i] = zeta[i] - inter_x[i];
       }
     }
     else
     {
       // Find the smallest residual from the list of coordinates made earlier
       double my_min_resid = DBL_MAX;
       Vector<double> s_local(ncoord);
       Vector<double> work_x(ncoord);
       Vector<double> work_dx(ncoord);
       unsigned n_list_coord = s_list.size();
       for (unsigned i_coord = 0; i_coord < n_list_coord; i_coord++)
       {
         for (unsigned i = 0; i < ncoord; i++)
         {
           s_local[i] = s_list[i_coord][i];
         }
         // get_x for this coordinate
         this->interpolated_zeta(s_local, work_x);
         // calculate residuals
         for (unsigned i = 0; i < ncoord; i++)
         {
           work_dx[i] = zeta[i] - work_x[i];
         }
         double maxres = std::fabs(
           *std::max_element(work_dx.begin(), work_dx.end(), AbsCmp<double>()));
         // test against previous residuals
         if (maxres < my_min_resid)
         {
           my_min_resid = maxres;
           dx = work_dx;
           inter_x = work_x;
           s = s_local;
         }
       }
     }
     // Main Newton Loop
     do // start of do while loop
     {
       // Increase loop counter
       count++;
       // Bail out if necessary (without an error for now...)
       if (count > Locate_zeta_helpers::Max_newton_iterations)
       {
         keep_going = false;
         continue;
       }
       // If it's the first time round the loop, check the initial residuals
       if (count == 1)
       {
         double maxres =
           std::fabs(*std::max_element(dx.begin(), dx.end(), AbsCmp<double>()));
         // If it's small enough exit
         if (maxres < Locate_zeta_helpers::Newton_tolerance)
         {
           keep_going = false;
           continue;
         }
       }
       // Is there a macro element? If so, assemble the Jacobian by FD-ing
       if (macro_elem_pt() != 0)
       {
         // Assemble jacobian on the fly by finite differencing
         Vector<double> work_s = s;
         Vector<double> r = inter_x; // i.e. the result of previous call to get_x
         // Finite difference step
         double fd_step = GeneralisedElement::Default_fd_jacobian_step;
         // Storage for calculated r from incremented s
         Vector<double> work_r(ncoord, 0.0);
         // Loop over s coordinates
         for (unsigned i = 0; i < ncoord; i++)
         {
           // Increment work_s by a small amount
           work_s[i] += fd_step;
           // Calculate work_r from macro element
           this->interpolated_zeta(work_s, work_r);
           // Loop over r to fill Jacobian
           for (unsigned j = 0; j < ncoord; j++)
           {
             jacobian(j, i) = -(work_r[j] - r[j]) / fd_step;
           }
           // Reset work_s
           work_s[i] = s[i];
         }
       }
       else // no macro element, so compute Jacobian with shape functions etc.
       {
         // Compute the entries of the Jacobian matrix
         unsigned n_node = this->nnode();
         unsigned n_position_type = this->nnodal_position_type();
         Shape psi(n_node, n_position_type);
         DShape dpsids(n_node, n_position_type, ncoord);
         // Get the local shape functions and their derivatives
         dshape_local(s, psi, dpsids);
         // Calculate the values of dxds
         DenseMatrix<double> interpolated_dxds(ncoord, ncoord, 0.0);
         // MH: No longer needed
         //          //This implementation will only work for n_position_type=1
         //          //since the function nodal_position_gen does not yet exist
         // #ifdef PARANOID
         //          if (n_position_type!=1)
         //           {
         //            std::ostringstream error_stream;
         //            error_stream << "This implementation does not exist
         //            yet;\n"
         //                         << "it currently uses
         //                         raw_nodal_position_gen\n"
         //                         << "which does not take hangingness into
         //                         account\n"
         //                         << "It will work if n_position_type=1\n";
         //            throw OomphLibError(error_stream.str(),
         //         OOMPH_CURRENT_FUNCTION,
         //                                OOMPH_EXCEPTION_LOCATION);
         //           }
         // #endif
         // Loop over the nodes
         for (unsigned l = 0; l < n_node; l++)
         {
           // Loop over position type even though it should be 1; the
           // functionality for n_position_type>1 will exist in the future
           for (unsigned k = 0; k < n_position_type; k++)
           {
             // Add the contribution from the nodal coordinates to the matrix
             for (unsigned i = 0; i < ncoord; i++)
             {
               for (unsigned j = 0; j < ncoord; j++)
               {
                 interpolated_dxds(i, j) +=
                   this->zeta_nodal(l, k, i) * dpsids(l, k, j);
               }
             }
           }
         }
         // The entries of the Jacobian matrix are merely dresiduals/ds
         // i.e. \f$ -dx/ds \f$
         for (unsigned i = 0; i < ncoord; i++)
         {
           for (unsigned j = 0; j < ncoord; j++)
           {
             jacobian(i, j) = -interpolated_dxds(i, j);
           }
         }
       }
       // Now solve the damn thing
       try
       {
         jacobian.solve(dx);
       }
       catch (OomphLibError& error)
       {
         // I've caught the error so shut up!
         error.disable_error_message();
 #ifdef PARANOID
         oomph_info << "Error in linear solve for "
                    << "FiniteElement::locate_zeta()" << std::endl;
         oomph_info << "Should not affect the result!" << std::endl;
 #endif
       }
       // Add the correction to the local coordinates
       for (unsigned i = 0; i < ncoord; i++)
       {
         s[i] -= dx[i];
       }
       // Get the new residuals
       this->interpolated_zeta(s, inter_x);
       for (unsigned i = 0; i < ncoord; i++)
       {
         dx[i] = zeta[i] - inter_x[i];
       }
       // Get the maximum residuals
       double maxres =
         std::fabs(*std::max_element(dx.begin(), dx.end(), AbsCmp<double>()));
       // If we have converged jump straight to the test at the end of the loop
       if (maxres < Locate_zeta_helpers::Newton_tolerance)
       {
         keep_going = false;
         continue;
       }
     } while (keep_going);
     // Test whether the local coordinates are valid or not
     bool valid = local_coord_is_valid(s);
     // If not valid, experimentally push back into element
     // and see if the result is still valid (within the Newton tolerance)
     if (!valid)
     {
       move_local_coord_back_into_element(s);
       // Check residuals again
       this->interpolated_zeta(s, inter_x);
       for (unsigned i = 0; i < ncoord; i++)
       {
         dx[i] = zeta[i] - inter_x[i];
       }
       // Get the maximum residuals
       double maxres =
         std::fabs(*std::max_element(dx.begin(), dx.end(), AbsCmp<double>()));
       // Are we still OK?
       if (maxres > Locate_zeta_helpers::Newton_tolerance)
       {
         // oomph_info
         // << "Pushing back inside has violated the Newton tolerance: max_res =
         // "
         // << maxres << std::endl;
         geom_object_pt = 0;
         return;
       }
     }
     // It is also possible now that it may not have converged "correctly",
     // i.e. count is greater than Max_newton_iterations
     if (count > Locate_zeta_helpers::Max_newton_iterations)
     {
       // Don't trust the current answer, return null
       geom_object_pt = 0;
       return;
     }
     // Otherwise the required point is located in "this" element:
     geom_object_pt = this;
   }
References oomph::GeneralisedElement::Default_fd_jacobian_step, dim(), dshape_local(), calibrate::error, boost::multiprecision::fabs(), get_centre_of_gravity_and_max_radius_in_terms_of_zeta(), get_s_plot(), i, interpolated_zeta(), j, k, local_coord_is_valid(), macro_elem_pt(), oomph::Locate_zeta_helpers::Max_newton_iterations, move_local_coord_back_into_element(), oomph::Locate_zeta_helpers::N_local_points, oomph::Locate_zeta_helpers::Newton_tolerance, nnodal_position_type(), nnode(), nplot_points(), oomph::oomph_info, UniformPSDSelfTest::r, UniformPSDSelfTest::radius, oomph::Locate_zeta_helpers::Radius_multiplier_for_fast_exit_from_locate_zeta, s, oomph::DoubleMatrixBase::solve(), sqrt(), Eigen::zeta(), and zeta_nodal().
macro_elem_pt()
MacroElement* oomph::FiniteElement::macro_elem_pt () inline
Access function to pointer to macro element.
     {
       return Macro_elem_pt;
     }
References Macro_elem_pt.
Referenced by oomph::TreeBasedRefineableMeshBase::adapt_mesh(), oomph::RefineableQElement< 3 >::build(), oomph::ExtrudedCubeMeshFromQuadMesh< ELEMENT >::build_mesh(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::check_integrity(), locate_zeta(), oomph::TreeBasedRefineableMeshBase::p_adapt_mesh(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::pre_build(), set_macro_elem_pt(), oomph::SolidFiniteElement::set_macro_elem_pt(), oomph::QElementBase::set_macro_elem_pt(), and oomph::QSolidElementBase::set_macro_elem_pt().
move_local_coord_back_into_element()
virtual void oomph::FiniteElement::move_local_coord_back_into_element (Vector< double > & s) const inline virtual
Adjust local coordinates so that they're located inside the element
Reimplemented in oomph::TElementBase, oomph::QElementBase, oomph::QHermiteElement< DIM >, and oomph::QHermiteElement< DIM - 1 >.
     {
       throw OomphLibError("move_local_coords_back_into_element() is not "
                           "implemented for this element\n",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by locate_zeta().
ngeom_data()
unsigned oomph::FiniteElement::ngeom_data () const inline virtual
A standard FiniteElement is fixed, so there are no geometric data when viewed in its GeomObject incarnation
Reimplemented from oomph::GeomObject.
Reimplemented in oomph::RefineableSolidElement, oomph::FaceElementAsGeomObject< ELEMENT >, and oomph::SolidFiniteElement.
     {
       return 0;
     }
Referenced by oomph::ElementWithExternalElement::assign_external_interaction_data_local_eqn_numbers().
nnodal_position_type()
unsigned oomph::FiniteElement::nnodal_position_type () const inline
Return the number of coordinate types that the element requires to interpolate the geometry between the nodes. For Lagrange elements it is 1.
     {
       return Nnodal_position_type;
     }
References Nnodal_position_type.
Referenced by assemble_eulerian_base_vectors(), oomph::RefineableElement::assemble_eulerian_base_vectors(), assemble_local_to_eulerian_jacobian(), oomph::RefineableElement::assemble_local_to_eulerian_jacobian(), assemble_local_to_eulerian_jacobian2(), oomph::RefineableElement::assemble_local_to_eulerian_jacobian2(), oomph::RefineableSolidElement::assign_solid_hanging_local_eqn_numbers(), oomph::SolidFiniteElement::assign_solid_local_eqn_numbers(), oomph::SolidICProblem::backup_original_state(), check_J_eulerian_at_knots(), oomph::FaceElement::check_J_eulerian_at_knots(), oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >::construct_boundary_node(), oomph::SolidFiniteElement::construct_boundary_node(), oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >::construct_node(), oomph::SolidFiniteElement::construct_node(), oomph::FaceElement::continuous_tangent_and_outer_unit_normal(), oomph::FSIHermiteBeamElement::dposition_dlagrangian_at_local_coordinate(), oomph::FSIDiagHermiteShellElement::dposition_dlagrangian_at_local_coordinate(), oomph::ClampedSlidingHermiteBeamBoundaryConditionElement::fill_in_contribution_to_residuals(), oomph::AxisymmetricPVDEquations::fill_in_contribution_to_residuals_axisym_pvd(), oomph::KirchhoffLoveBeamEquations::fill_in_contribution_to_residuals_beam(), oomph::KirchhoffLoveShellEquations::fill_in_contribution_to_residuals_shell(), oomph::AxisymmetricLinearElasticityEquations::fill_in_generic_contribution_to_residuals_axisymmetric_linear_elasticity(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::fill_in_generic_contribution_to_residuals_fourier_decomp_time_harmonic_linear_elasticity(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), oomph::RefineableQDPVDElement< DIM, NNODE_1D >::fill_in_generic_contribution_to_residuals_pvd(), oomph::SolidFiniteElement::fill_in_generic_jacobian_for_solid_ic(), oomph::AxisymmetricPVDEquationsWithPressure::fill_in_generic_residual_contribution_axisym_pvd_with_pressure(), oomph::SolidFiniteElement::fill_in_jacobian_for_newmark_accel(), oomph::SolidFiniteElement::fill_in_jacobian_from_solid_position_by_fd(), oomph::RefineableSolidElement::fill_in_jacobian_from_solid_position_by_fd(), FlatPlateMesh< ELEMENT >::FlatPlateMesh(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::FSIImposeDisplacementByLagrangeMultiplierElement(), oomph::FSIHermiteBeamElement::get_dof_numbers_for_unknowns(), oomph::FSIDiagHermiteShellElement::get_dof_numbers_for_unknowns(), oomph::ClampedHermiteShellBoundaryConditionElement::get_dof_numbers_for_unknowns(), oomph::PVDEquationsBase< DIM >::get_dof_numbers_for_unknowns(), oomph::PVDEquationsWithPressure< DIM >::get_dof_numbers_for_unknowns(), oomph::KirchhoffLoveShellEquations::get_energy(), oomph::KirchhoffLoveBeamEquations::get_energy(), oomph::KirchhoffLoveBeamEquations::get_non_unit_tangent(), oomph::KirchhoffLoveShellEquations::get_normal(), oomph::KirchhoffLoveBeamEquations::get_normal(), oomph::AxisymmetricLinearElasticityEquations::get_strain(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::get_strain(), oomph::KirchhoffLoveShellEquations::get_strain_and_bend(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::ImposeDisplacementByLagrangeMultiplierElement(), interpolated_dxdt(), interpolated_x(), interpolated_zeta(), J_eulerian(), oomph::FaceElement::J_eulerian(), J_eulerian_at_knot(), oomph::FaceElement::J_eulerian_at_knot(), oomph::KirchhoffLoveShellEquations::load_rate_of_work(), local_to_eulerian_mapping_diagonal(), oomph::RefineableElement::local_to_eulerian_mapping_diagonal(), locate_zeta(), oomph::FaceElement::outer_unit_normal(), oomph::HermiteBeamElement::output(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::output(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::output(), oomph::SolidFiniteElement::position_local_eqn(), oomph::StorableShapeElementBase::pre_compute_d2shape_eulerian_at_knots(), oomph::StorableShapeElementBase::pre_compute_d2shape_local_at_knots(), oomph::StorableShapeElementBase::pre_compute_dshape_eulerian_at_knots(), oomph::StorableShapeElementBase::pre_compute_dshape_local_at_knots(), oomph::StorableShapeElementBase::pre_compute_shape_at_knots(), oomph::RefineableImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::RefineableFSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), oomph::SolidICProblem::reset_original_state(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::residual_for_projection(), oomph::ProjectableDarcyElement< DARCY_ELEMENT >::residual_for_projection(), oomph::ProjectableElement< ELEMENT >::residual_for_projection(), self_test(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::set_boundary_shape_geom_object_pt(), oomph::SolidICProblem::setup_problem(), ShellMesh< ELEMENT >::ShellMesh(), and oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::square_of_l2_norm_of_error().
nnode()
unsigned oomph::FiniteElement::nnode () const inline
Return the number of nodes.
     {
       return Nnode;
     }
References Nnode.
Referenced by oomph::TreeBasedRefineableMeshBase::adapt_mesh(), oomph::SolubleSurfactantTransportInterfaceElement::add_additional_residual_contributions_interface(), oomph::SurfactantTransportInterfaceElement::add_additional_residual_contributions_interface(), oomph::FaceElement::add_additional_values(), oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::add_element_contribution_to_aux_integral(), oomph::DGFaceElement::add_flux_contributions(), oomph::StefanBoltzmannRadiationBase::add_stefan_boltzmann_illumination_info(), AirwayReopeningProblem< ELEMENT >::AirwayReopeningProblem(), assemble_eulerian_base_vectors(), oomph::RefineableElement::assemble_eulerian_base_vectors(), assemble_local_to_eulerian_jacobian(), oomph::RefineableElement::assemble_local_to_eulerian_jacobian(), assemble_local_to_eulerian_jacobian2(), oomph::RefineableElement::assemble_local_to_eulerian_jacobian2(), oomph::SolidFiniteElement::assemble_local_to_lagrangian_jacobian(), oomph::RefineableSolidElement::assemble_local_to_lagrangian_jacobian(), oomph::SolidFiniteElement::assemble_local_to_lagrangian_jacobian2(), oomph::RefineableSolidElement::assemble_local_to_lagrangian_jacobian2(), oomph::ElementWithMovingNodes::assemble_set_of_all_geometric_data(), oomph::ElementWithExternalElement::assign_external_interaction_data_local_eqn_numbers(), oomph::RefineableElement::assign_hanging_local_eqn_numbers(), oomph::GeneralisedElement::assign_local_eqn_numbers(), assign_nodal_local_eqn_numbers(), oomph::RefineableSolidElement::assign_solid_hanging_local_eqn_numbers(), oomph::SolidFiniteElement::assign_solid_local_eqn_numbers(), oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT >::BackupMeshForProjection(), oomph::GmshTetMesh< ELEMENT >::build_from_scaffold(), RefineableUnsteadyHeatProblem< ELEMENT >::build_mesh(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::build_mesh(), oomph::BackwardStepQuadMesh< ELEMENT >::build_mesh(), oomph::ExtrudedCubeMeshFromQuadMesh< ELEMENT >::build_mesh(), CapProblem< ELEMENT >::CapProblem(), oomph::Mesh::check_inverted_elements(), check_J_eulerian_at_knots(), oomph::FaceElement::check_J_eulerian_at_knots(), check_jacobian(), oomph::TriangleScaffoldMesh::check_mesh_integrity(), ContactProblem< ELEMENT >::complete_problem_setup(), oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::complete_setup_of_dependencies(), oomph::HelmholtzDtNBoundaryElement< ELEMENT >::complete_setup_of_dependencies(), oomph::HelmholtzBCElementBase< ELEMENT >::compute_contribution_to_fourier_components(), oomph::AxisymAdvectionDiffusionEquations::compute_error(), oomph::AxisymFoepplvonKarmanEquations::compute_error(), oomph::BiharmonicEquations< DIM >::compute_error(), oomph::DisplacementBasedFoepplvonKarmanEquations::compute_error(), oomph::FoepplvonKarmanEquations::compute_error(), oomph::FourierDecomposedHelmholtzEquations::compute_error(), oomph::PMLFourierDecomposedHelmholtzEquations::compute_error(), oomph::SphericalAdvectionDiffusionEquations::compute_error(), oomph::SteadyAxisymAdvectionDiffusionEquations::compute_error(), oomph::EulerEquations< DIM >::compute_error(), oomph::ScalarAdvectionEquations< DIM >::compute_error(), oomph::SolidFiniteElement::compute_norm(), oomph::FourierDecomposedHelmholtzEquations::compute_norm(), oomph::PMLFourierDecomposedHelmholtzEquations::compute_norm(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::compute_norm(), oomph::AxisymmetricPVDEquations::compute_physical_size(), oomph::AxisymmetricPVDEquationsWithPressure::compute_physical_size(), oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::compute_stabilisation_parameter(), oomph::DGElement::construct_boundary_nodes_and_faces(), oomph::DGElement::construct_nodes_and_faces(), oomph::FaceElement::continuous_tangent_and_outer_unit_normal(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::contribution_to_enclosed_volume(), oomph::LineVolumeConstraintBoundingElement::contribution_to_enclosed_volume(), oomph::AxisymmetricVolumeConstraintBoundingElement::contribution_to_enclosed_volume(), oomph::StefanBoltzmannRadiationBase::contribution_to_stefan_boltzmann_radiation(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::contribution_to_total_porous_flux(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::contribution_to_total_porous_flux(), oomph::AxisymmetricVolumeConstraintBoundingElement::contribution_to_volume_flux(), oomph::LinearisedQCrouzeixRaviartElement::copy_efunction_to_normalisation(), ContactProblem< ELEMENT >::create_displ_imposition_elements(), RefineableRotatingCylinderProblem< ELEMENT >::create_free_surface_elements(), UnstructuredTorusProblem< ELEMENT >::create_lagrange_multiplier_elements(), FSICollapsibleChannelProblem< ELEMENT >::create_lagrange_multiplier_elements(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_lagrange_multiplier_elements(), FSIChannelWithLeafletProblem< ELEMENT >::create_lagrange_multiplier_elements(), UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_lagrange_multiplier_elements(), PrescribedBoundaryDisplacementProblem< ELEMENT >::create_lagrange_multiplier_elements(), UnstructuredImmersedEllipseProblem< ELEMENT >::create_lagrange_multiplier_elements(), UnstructuredFluidProblem< ELEMENT >::create_lagrange_multiplier_elements(), CollapsibleChannelProblem< ELEMENT >::create_lagrange_multiplier_elements(), StefanBoltzmannProblem< ELEMENT >::create_melt_elements(), TiltedCavityProblem< ELEMENT >::create_parall_outflow_lagrange_elements(), d_dshape_eulerian_dnodal_coordinates(), d_dshape_eulerian_dnodal_coordinates_templated_helper(), oomph::SphericalNavierStokesEquations::d_kin_energy_dt(), oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >::d_shape_and_test_local(), oomph::HelmholtzBCElementBase< ELEMENT >::d_shape_and_test_local(), oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::d_shape_and_test_local(), oomph::ProjectableAdvectionDiffusionReactionElement< ADR_ELEMENT >::data_values_of_field(), oomph::ProjectableAxisymLinearElasticityElement< AXISYM_LINEAR_ELAST_ELEMENT >::data_values_of_field(), oomph::ProjectableAxisymmetricTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::data_values_of_field(), oomph::ProjectableAxisymmetricCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::data_values_of_field(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::data_values_of_field(), oomph::ProjectableDisplacementBasedFoepplvonKarmanElement< FVK_ELEMENT >::data_values_of_field(), oomph::ProjectableFoepplvonKarmanElement< FVK_ELEMENT >::data_values_of_field(), oomph::ProjectableFourierDecomposedHelmholtzElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >::data_values_of_field(), oomph::GeneralisedNewtonianProjectableAxisymmetricTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::data_values_of_field(), oomph::GeneralisedNewtonianProjectableAxisymmetricCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::data_values_of_field(), oomph::ProjectableGeneralisedNewtonianTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::data_values_of_field(), oomph::ProjectableGeneralisedNewtonianCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::data_values_of_field(), oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::data_values_of_field(), oomph::ProjectableHelmholtzElement< HELMHOLTZ_ELEMENT >::data_values_of_field(), oomph::ProjectableLinearElasticityElement< LINEAR_ELAST_ELEMENT >::data_values_of_field(), oomph::ProjectablePMLFourierDecomposedHelmholtzElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >::data_values_of_field(), oomph::ProjectablePMLHelmholtzElement< HELMHOLTZ_ELEMENT >::data_values_of_field(), oomph::ProjectablePMLTimeHarmonicLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::data_values_of_field(), oomph::ProjectablePoissonElement< POISSON_ELEMENT >::data_values_of_field(), oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::data_values_of_field(), oomph::ProjectableUnsteadyHeatMixedOrderSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::data_values_of_field(), oomph::ProjectableTimeHarmonicFourierDecomposedLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::data_values_of_field(), oomph::ProjectableTimeHarmonicLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::data_values_of_field(), oomph::ProjectableUnsteadyHeatElement< UNSTEADY_HEAT_ELEMENT >::data_values_of_field(), oomph::RefineableElement::deactivate_element(), describe_nodal_local_dofs(), oomph::SolidFiniteElement::describe_solid_local_dofs(), oomph::AdvectionDiffusionEquations< DIM >::dinterpolated_u_adv_diff_ddata(), oomph::RefineableAdvectionDiffusionEquations< DIM >::dinterpolated_u_adv_diff_ddata(), oomph::RefineableAxisymAdvectionDiffusionEquations::dinterpolated_u_adv_diff_ddata(), oomph::RefineableSphericalAdvectionDiffusionEquations::dinterpolated_u_adv_diff_ddata(), oomph::SphericalAdvectionDiffusionEquations::dinterpolated_u_adv_diff_ddata(), oomph::SteadyAxisymAdvectionDiffusionEquations::dinterpolated_u_adv_diff_ddata(), oomph::AxisymAdvectionDiffusionEquations::dinterpolated_u_axi_adv_diff_ddata(), oomph::AxisymmetricNavierStokesEquations::dinterpolated_u_axi_nst_ddata(), oomph::RefineableAxisymmetricNavierStokesEquations::dinterpolated_u_axi_nst_ddata(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::dinterpolated_u_axi_nst_ddata(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::dinterpolated_u_axi_nst_ddata(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::dinterpolated_u_nst_ddata(), oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::dinterpolated_u_nst_ddata(), oomph::NavierStokesEquations< DIM >::dinterpolated_u_nst_ddata(), oomph::RefineableNavierStokesEquations< DIM >::dinterpolated_u_nst_ddata(), oomph::SpaceTimeNavierStokesEquations< DIM >::dinterpolated_u_nst_ddata(), oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::dinterpolated_u_nst_ddata(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::dinterpolated_u_nst_ddata(), oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >::dinterpolated_u_nst_ddata(), oomph::SurfaceMeltElement< ELEMENT >::disable_melting(), oomph::UnsteadyHeatFluxPseudoMeltElement< ELEMENT >::disable_melting(), oomph::DisplacementControlElement::DisplacementControlElement(), dJ_eulerian_at_knot(), dJ_eulerian_dnodal_coordinates(), dJ_eulerian_dnodal_coordinates_templated_helper(), oomph::LinearisedAxisymmetricNavierStokesEquations::dkin_energy_dt(), oomph::Z2ErrorEstimator::doc_flux(), StefanBoltzmannProblem< ELEMENT >::doc_solution(), PoissonProblem< ELEMENT >::doc_solution(), FallingBlockProblem< ELEMENT >::doc_solution(), RisingBubbleProblem< ELEMENT >::doc_solution(), oomph::FSIHermiteBeamElement::dposition_dlagrangian_at_local_coordinate(), oomph::FSIDiagHermiteShellElement::dposition_dlagrangian_at_local_coordinate(), oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >::dposition_dt(), oomph::DummyErrorEstimator::DummyErrorEstimator(), ElasticRefineableTwoLayerMesh< ELEMENT >::ElasticRefineableTwoLayerMesh(), oomph::AxisymmetricNavierStokesEquations::fill_in_contribution_to_hessian_vector_products(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_contribution_to_hessian_vector_products(), oomph::SpinePointMarangoniSurfactantFluidInterfaceBoundingElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::NodeElementSolidOnlyMortaringElement::fill_in_contribution_to_jacobian_mortared_nodes(), oomph::AxisymFoepplvonKarmanEquations::fill_in_contribution_to_residuals(), oomph::DisplacementBasedFoepplvonKarmanEquations::fill_in_contribution_to_residuals(), oomph::FoepplvonKarmanEquations::fill_in_contribution_to_residuals(), oomph::ClampedHermiteShellBoundaryConditionElement::fill_in_contribution_to_residuals(), oomph::RefineableYoungLaplaceEquations::fill_in_contribution_to_residuals(), oomph::YoungLaplaceEquations::fill_in_contribution_to_residuals(), oomph::AxisymmetricPVDEquations::fill_in_contribution_to_residuals_axisym_pvd(), oomph::KirchhoffLoveBeamEquations::fill_in_contribution_to_residuals_beam(), oomph::KirchhoffLoveShellEquations::fill_in_contribution_to_residuals_shell(), oomph::AxisymmetricLinearElasticityEquations::fill_in_generic_contribution_to_residuals_axisymmetric_linear_elasticity(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::fill_in_generic_contribution_to_residuals_fourier_decomp_time_harmonic_linear_elasticity(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), oomph::ImposeImpenetrabilityElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(), oomph::ImposeParallelOutflowElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(), oomph::RefineableQDPVDElement< DIM, NNODE_1D >::fill_in_generic_contribution_to_residuals_pvd(), oomph::AxisymmetricNavierStokesEquations::fill_in_generic_dresidual_contribution_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_dresidual_contribution_axi_nst(), oomph::SolidFiniteElement::fill_in_generic_jacobian_for_solid_ic(), oomph::AxisymmetricPoroelasticityEquations::fill_in_generic_residual_contribution(), oomph::PolarNavierStokesEquations::fill_in_generic_residual_contribution(), oomph::RefineablePolarNavierStokesEquations::fill_in_generic_residual_contribution(), oomph::RefineablePolarStreamfunctionEquations::fill_in_generic_residual_contribution(), oomph::PolarStreamfunctionEquations::fill_in_generic_residual_contribution(), oomph::SteadyAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_adv_diff(), oomph::AxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), oomph::RefineableAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), oomph::AxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::AxisymmetricPVDEquationsWithPressure::fill_in_generic_residual_contribution_axisym_pvd_with_pressure(), oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_cons_axisym_adv_diff(), oomph::NavierStokesFluxControlElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction(), oomph::FourierDecomposedHelmholtzEquations::fill_in_generic_residual_contribution_fourier_decomposed_helmholtz(), oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::fill_in_generic_residual_contribution_fourier_decomposed_helmholtz_DtN_bc(), oomph::HelmholtzAbsorbingBCElement< ELEMENT >::fill_in_generic_residual_contribution_helmholtz_abc(), oomph::HelmholtzDtNBoundaryElement< ELEMENT >::fill_in_generic_residual_contribution_helmholtz_DtN_bc(), oomph::PerturbedSpineLinearisedAxisymmetricFluidInterfaceElement< ELEMENT >::fill_in_generic_residual_contribution_interface(), oomph::FluidInterfaceElement::fill_in_generic_residual_contribution_interface(), oomph::LineFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary(), oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_lin_axi_nst(), oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::LinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst(), oomph::RefineableLinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst(), oomph::PeriodicOrbitEquations::fill_in_generic_residual_contribution_orbit(), oomph::PMLFourierDecomposedHelmholtzEquations::fill_in_generic_residual_contribution_pml_fourier_decomposed_helmholtz(), oomph::RefineableSphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), oomph::SphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), oomph::RefineableSphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst(), oomph::SphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst(), oomph::LineVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint(), oomph::AxisymmetricVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint(), oomph::SurfaceVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint(), oomph::SolidFiniteElement::fill_in_jacobian_for_newmark_accel(), oomph::ElementWithMovingNodes::fill_in_jacobian_from_geometric_data(), fill_in_jacobian_from_nodal_by_fd(), oomph::RefineableElement::fill_in_jacobian_from_nodal_by_fd(), oomph::SolidFiniteElement::fill_in_jacobian_from_solid_position_by_fd(), oomph::RefineableSolidElement::fill_in_jacobian_from_solid_position_by_fd(), oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::fill_in_off_diagonal_block_analytic(), oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_off_diagonal_block_analytic(), oomph::NavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::fill_in_off_diagonal_block_analytic(), oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_off_diagonal_block_analytic(), oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::BuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_by_fd(), oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::fill_in_off_diagonal_jacobian_blocks_by_fd(), oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_by_fd(), GlobalParameters::find_node_on_centerline(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::FSIImposeDisplacementByLagrangeMultiplierElement(), FSIRingProblem::FSIRingProblem(), oomph::PolarNavierStokesEquations::full_output(), oomph::SphericalNavierStokesEquations::full_output(), oomph::RefineableSolidElement::geom_data_pt(), oomph::LinearisedAxisymmetricNavierStokesEquations::get_base_flow_d_dudx_dX(), oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::get_body_force_nst(), oomph::FoepplvonKarmanEquations::get_bounded_volume(), get_centre_of_gravity_and_max_radius_in_terms_of_zeta(), oomph::PoissonEquations< DIM >::get_dflux_dnodal_u(), oomph::ElementWithMovingNodes::get_dnodal_coordinates_dgeom_dofs(), oomph::MultiPoissonEquations< DIM, NFIELDS >::get_dof_numbers_for_unknowns(), oomph::AxisymmetricLinearElasticityEquationsBase::get_dof_numbers_for_unknowns(), oomph::AxisymmetricQCrouzeixRaviartElement::get_dof_numbers_for_unknowns(), oomph::AxisymmetricQTaylorHoodElement::get_dof_numbers_for_unknowns(), oomph::AxisymmetricTCrouzeixRaviartElement::get_dof_numbers_for_unknowns(), oomph::AxisymmetricTTaylorHoodElement::get_dof_numbers_for_unknowns(), oomph::FSIHermiteBeamElement::get_dof_numbers_for_unknowns(), oomph::BiharmonicEquations< DIM >::get_dof_numbers_for_unknowns(), oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >::get_dof_numbers_for_unknowns(), oomph::GeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement::get_dof_numbers_for_unknowns(), oomph::GeneralisedNewtonianAxisymmetricQTaylorHoodElement::get_dof_numbers_for_unknowns(), oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::get_dof_numbers_for_unknowns(), oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::get_dof_numbers_for_unknowns(), oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >::get_dof_numbers_for_unknowns(), oomph::LinearElasticityEquationsBase< DIM >::get_dof_numbers_for_unknowns(), oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::get_dof_numbers_for_unknowns(), oomph::ImposeImpenetrabilityElement< ELEMENT >::get_dof_numbers_for_unknowns(), oomph::ImposeParallelOutflowElement< ELEMENT >::get_dof_numbers_for_unknowns(), oomph::TTaylorHoodElement< DIM >::get_dof_numbers_for_unknowns(), oomph::PMLHelmholtzEquations< DIM >::get_dof_numbers_for_unknowns(), oomph::PMLHelmholtzFluxElement< ELEMENT >::get_dof_numbers_for_unknowns(), oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::get_dof_numbers_for_unknowns(), oomph::FSIDiagHermiteShellElement::get_dof_numbers_for_unknowns(), oomph::ClampedHermiteShellBoundaryConditionElement::get_dof_numbers_for_unknowns(), oomph::PVDEquationsBase< DIM >::get_dof_numbers_for_unknowns(), oomph::PVDEquationsWithPressure< DIM >::get_dof_numbers_for_unknowns(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::get_dof_numbers_for_unknowns(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::get_dof_numbers_for_unknowns(), oomph::BlockPrecQTaylorHoodSpaceTimeElement::get_dof_numbers_for_unknowns(), oomph::BlockPrecQTaylorHoodMixedOrderSpaceTimeElement::get_dof_numbers_for_unknowns(), oomph::QSphericalCrouzeixRaviartElement::get_dof_numbers_for_unknowns(), oomph::QSphericalTaylorHoodElement::get_dof_numbers_for_unknowns(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::get_dof_numbers_for_unknowns(), oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::get_dof_numbers_for_unknowns(), oomph::AxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), get_dresidual_dnodal_coordinates(), oomph::RefineableElement::get_dresidual_dnodal_coordinates(), oomph::Z2ErrorEstimator::get_element_errors(), oomph::KirchhoffLoveShellEquations::get_energy(), oomph::KirchhoffLoveBeamEquations::get_energy(), oomph::ProjectableAdvectionDiffusionReactionElement< ADR_ELEMENT >::get_field(), oomph::ProjectableAxisymLinearElasticityElement< AXISYM_LINEAR_ELAST_ELEMENT >::get_field(), oomph::ProjectableAxisymmetricTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::get_field(), oomph::ProjectableDisplacementBasedFoepplvonKarmanElement< FVK_ELEMENT >::get_field(), oomph::ProjectableFoepplvonKarmanElement< FVK_ELEMENT >::get_field(), oomph::ProjectableFourierDecomposedHelmholtzElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >::get_field(), oomph::GeneralisedNewtonianProjectableAxisymmetricTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::get_field(), oomph::ProjectableGeneralisedNewtonianTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::get_field(), oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::get_field(), oomph::ProjectableHelmholtzElement< HELMHOLTZ_ELEMENT >::get_field(), oomph::ProjectableLinearElasticityElement< LINEAR_ELAST_ELEMENT >::get_field(), oomph::ProjectablePMLFourierDecomposedHelmholtzElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >::get_field(), oomph::ProjectablePMLHelmholtzElement< HELMHOLTZ_ELEMENT >::get_field(), oomph::ProjectablePMLTimeHarmonicLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::get_field(), oomph::ProjectablePoissonElement< POISSON_ELEMENT >::get_field(), oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::get_field(), oomph::ProjectableUnsteadyHeatMixedOrderSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::get_field(), oomph::ProjectableTimeHarmonicFourierDecomposedLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::get_field(), oomph::ProjectableTimeHarmonicLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::get_field(), oomph::ProjectableUnsteadyHeatElement< UNSTEADY_HEAT_ELEMENT >::get_field(), oomph::PolarStreamfunctionEquations::get_flux(), oomph::AdvectionDiffusionEquations< DIM >::get_flux(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::get_flux(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::get_flux(), oomph::AxisymAdvectionDiffusionEquations::get_flux(), oomph::LinearWaveEquations< DIM >::get_flux(), oomph::PoissonEquations< DIM >::get_flux(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::get_flux(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::get_flux(), oomph::SphericalAdvectionDiffusionEquations::get_flux(), oomph::SteadyAxisymAdvectionDiffusionEquations::get_flux(), oomph::UnsteadyHeatEquations< DIM >::get_flux(), oomph::WomersleyEquations< DIM >::get_flux(), oomph::YoungLaplaceEquations::get_flux(), oomph::FourierDecomposedHelmholtzEquations::get_flux(), oomph::HelmholtzEquations< DIM >::get_flux(), oomph::PMLFourierDecomposedHelmholtzEquations::get_flux(), oomph::PMLHelmholtzEquations< DIM >::get_flux(), oomph::AxisymFoepplvonKarmanEquations::get_gradient_of_deflection(), oomph::DisplacementBasedFoepplvonKarmanEquations::get_gradient_of_deflection(), oomph::FoepplvonKarmanEquations::get_gradient_of_deflection(), oomph::DisplacementBasedFoepplvonKarmanEquations::get_gradient_of_field(), oomph::SurfaceContactElementBase< ELEMENT >::get_interpolated_lagrange_p(), oomph::SurfaceMeltElement< ELEMENT >::get_interpolated_lagrange_p(), oomph::SpectralPeriodicOrbitElement< NNODE_1D >::get_interpolated_values(), oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::get_interpolated_values(), oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::get_interpolated_values(), oomph::RefineableAxisymmetricQTaylorHoodElement::get_interpolated_values(), oomph::RefineableAxisymmetricQCrouzeixRaviartElement::get_interpolated_values(), oomph::RefineableGeneralisedNewtonianAxisymmetricQTaylorHoodElement::get_interpolated_values(), oomph::RefineableGeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement::get_interpolated_values(), oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::get_interpolated_values(), oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::get_interpolated_values(), oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::get_interpolated_values(), oomph::RefineableLinearElasticityEquations< DIM >::get_interpolated_values(), oomph::RefineableLinearisedQCrouzeixRaviartElement::get_interpolated_values(), oomph::RefineableLinearisedQTaylorHoodElement::get_interpolated_values(), oomph::RefineableQTaylorHoodElement< DIM >::get_interpolated_values(), oomph::RefineableQCrouzeixRaviartElement< DIM >::get_interpolated_values(), oomph::PRefineableQCrouzeixRaviartElement< DIM >::get_interpolated_values(), oomph::RefineablePolarTaylorHoodElement::get_interpolated_values(), oomph::RefineablePolarCrouzeixRaviartElement::get_interpolated_values(), oomph::RefineableQSphericalTaylorHoodElement::get_interpolated_values(), oomph::RefineableQSphericalCrouzeixRaviartElement::get_interpolated_values(), oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >::get_interpolated_values(), oomph::RefineablePolarStreamfunctionEquations::get_interpolated_values(), oomph::RefineableAdvectionDiffusionEquations< DIM >::get_interpolated_values(), oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::get_interpolated_values(), oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >::get_interpolated_values(), oomph::RefineableAxisymAdvectionDiffusionEquations::get_interpolated_values(), oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::get_interpolated_values(), oomph::RefineableHelmholtzEquations< DIM >::get_interpolated_values(), oomph::RefineableLinearWaveEquations< DIM >::get_interpolated_values(), oomph::RefineablePMLHelmholtzEquations< DIM >::get_interpolated_values(), oomph::RefineablePoissonEquations< DIM >::get_interpolated_values(), oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::get_interpolated_values(), oomph::RefineableSpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::get_interpolated_values(), oomph::RefineableSphericalAdvectionDiffusionEquations::get_interpolated_values(), oomph::RefineableUnsteadyHeatEquations< DIM >::get_interpolated_values(), oomph::RefineableYoungLaplaceEquations::get_interpolated_values(), oomph::DGFaceElement::get_interpolation_data(), ThreeDimBethertonProblem< ELEMENT >::get_lambda(), oomph::PolarCrouzeixRaviartElement::get_load_data(), oomph::PolarTaylorHoodElement::get_load_data(), get_node_number(), NodeReordering::get_node_reordering(), oomph::Mesh::get_node_reordering(), oomph::KirchhoffLoveBeamEquations::get_non_unit_tangent(), oomph::KirchhoffLoveShellEquations::get_normal(), oomph::KirchhoffLoveBeamEquations::get_normal(), oomph::AxisymmetricNavierStokesEquations::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::SphericalNavierStokesEquations::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::AxisymmetricPoroelasticityEquations::get_q_basis(), oomph::DarcyEquations< DIM >::get_q_basis(), oomph::PoroelasticityEquations< DIM >::get_q_basis(), oomph::AxisymmetricLinearElasticityEquations::get_strain(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::get_strain(), oomph::KirchhoffLoveShellEquations::get_strain_and_bend(), oomph::DisplacementBasedFoepplvonKarmanEquations::get_stress_and_strain_for_output(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::get_total_flux(), oomph::SphericalNavierStokesEquations::get_vorticity(), oomph::SpectralPeriodicOrbitElement< NNODE_1D >::get_Z2_flux(), oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::get_Z2_flux(), oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >::get_Z2_flux(), oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::get_Z2_flux(), oomph::RefineableSpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::get_Z2_flux(), SCoupling< M, O >::getSCoupledElements(), oomph::PMLHelmholtzPowerElement< ELEMENT >::global_flux_contribution(), oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >::global_power_contribution(), oomph::HelmholtzBCElementBase< ELEMENT >::global_power_contribution(), oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::global_power_contribution(), oomph::PMLHelmholtzPowerElement< ELEMENT >::global_power_contribution(), has_hanging_nodes(), RefineableQAxisymAdvectionDiffusionBoussinesqElement::identify_all_field_data_for_external_interaction(), identify_field_data_for_interactions(), oomph::RefineableElement::identify_field_data_for_interactions(), oomph::SolidFiniteElement::identify_geometric_data(), oomph::RefineableSolidElement::identify_geometric_data(), oomph::FSIAxisymmetricQTaylorHoodElement::identify_load_data(), oomph::AxisymmetricTCrouzeixRaviartElement::identify_load_data(), oomph::AxisymmetricTTaylorHoodElement::identify_load_data(), oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::identify_load_data(), oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::identify_load_data(), oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::identify_load_data(), oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::identify_load_data(), oomph::RefineableQTaylorHoodElement< DIM >::identify_load_data(), oomph::RefineableQCrouzeixRaviartElement< DIM >::identify_load_data(), oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::identify_load_data(), oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >::identify_load_data(), oomph::QSphericalCrouzeixRaviartElement::identify_load_data(), oomph::QSphericalTaylorHoodElement::identify_load_data(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::ImposeDisplacementByLagrangeMultiplierElement(), oomph::ImposeImpenetrabilityElement< ELEMENT >::ImposeImpenetrabilityElement(), oomph::ImposeParallelOutflowElement< ELEMENT >::ImposeParallelOutflowElement(), oomph::RefineablePolarTaylorHoodElement::insert_load_data(), oomph::RefineablePolarCrouzeixRaviartElement::insert_load_data(), oomph::SurfactantTransportInterfaceElement::integrate_c(), oomph::SolubleSurfactantTransportInterfaceElement::integrated_C(), oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::integrated_C_and_M(), oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >::integrated_C_and_M(), oomph::SurfactantTransportInterfaceElement::interpolated_C(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::interpolated_c_adv_diff_react(), oomph::SolubleSurfactantTransportInterfaceElement::interpolated_C_bulk(), oomph::AxisymmetricLinearElasticityEquationsBase::interpolated_d2u_dt2_axisymmetric_linear_elasticity(), oomph::LinearWaveEquations< DIM >::interpolated_d2u_dt2_lin_wave(), oomph::AxisymmetricNavierStokesEquations::interpolated_d_dudx_dX_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::interpolated_d_dudx_dX_axi_nst(), oomph::AxisymmetricPoroelasticityEquations::interpolated_div_du_dt(), oomph::AxisymmetricPoroelasticityEquations::interpolated_div_q(), oomph::DarcyEquations< DIM >::interpolated_div_q(), oomph::PoroelasticityEquations< DIM >::interpolated_div_q(), oomph::AxisymmetricPoroelasticityEquations::interpolated_div_u(), oomph::AxisymmetricPoroelasticityEquations::interpolated_du_dt(), oomph::AxisymmetricLinearElasticityEquationsBase::interpolated_du_dt_axisymmetric_linear_elasticity(), oomph::LinearWaveEquations< DIM >::interpolated_du_dt_lin_wave(), oomph::SpaceTimeNavierStokesEquations< DIM >::interpolated_du_dt_nst(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::interpolated_du_dt_nst(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::interpolated_du_dt_ust_heat(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::interpolated_du_dt_ust_heat(), oomph::UnsteadyHeatEquations< DIM >::interpolated_du_dt_ust_heat(), oomph::AxisymmetricNavierStokesEquations::interpolated_duds_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::interpolated_duds_axi_nst(), oomph::AxisymmetricNavierStokesEquations::interpolated_dudt_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::interpolated_dudt_axi_nst(), oomph::PolarStreamfunctionEquations::interpolated_dudx(), oomph::BiharmonicEquations< DIM >::interpolated_dudx(), oomph::AxisymmetricNavierStokesEquations::interpolated_dudx_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::interpolated_dudx_axi_nst(), oomph::NavierStokesEquations< DIM >::interpolated_dudx_nst(), oomph::PolarNavierStokesEquations::interpolated_dudx_pnst(), oomph::SphericalNavierStokesEquations::interpolated_dudx_spherical_nst(), interpolated_dxdt(), oomph::SolidFiniteElement::interpolated_dxids(), oomph::PerturbedSpineLinearisedAxisymmetricFluidInterfaceElement< ELEMENT >::interpolated_H(), oomph::SolubleSurfactantTransportInterfaceElement::interpolated_M(), oomph::SurfaceMeltElement< ELEMENT >::interpolated_melt_rate(), oomph::LinearisedAxisymmetricNavierStokesEquations::interpolated_nodal_position_perturbation_lin_axi_nst(), oomph::PolarStreamfunctionEquations::interpolated_streamfunction(), oomph::AxisymFoepplvonKarmanEquations::interpolated_stress(), oomph::FoepplvonKarmanEquations::interpolated_stress(), oomph::YoungLaplaceEquations::interpolated_u(), oomph::LinearisedAxisymmetricFluidInterfaceElement::interpolated_u(), oomph::FluidInterfaceElement::interpolated_u(), oomph::UnsteadyHeatBaseFaceElement< ELEMENT >::interpolated_u(), oomph::AxisymmetricPoroelasticityEquations::interpolated_u(), oomph::PoroelasticityEquations< DIM >::interpolated_u(), oomph::DGFaceElement::interpolated_u(), oomph::AdvectionDiffusionEquations< DIM >::interpolated_u_adv_diff(), oomph::SteadyAxisymAdvectionDiffusionEquations::interpolated_u_adv_diff(), oomph::AxisymAdvectionDiffusionEquations::interpolated_u_axi_adv_diff(), oomph::AxisymmetricNavierStokesEquations::interpolated_u_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::interpolated_u_axi_nst(), oomph::AxisymmetricLinearElasticityEquationsBase::interpolated_u_axisymmetric_linear_elasticity(), oomph::BiharmonicEquations< DIM >::interpolated_u_biharmonic(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::interpolated_u_cons_adv_diff(), oomph::FourierDecomposedHelmholtzEquations::interpolated_u_fourier_decomposed_helmholtz(), oomph::AxisymFoepplvonKarmanEquations::interpolated_u_fvk(), oomph::HelmholtzEquations< DIM >::interpolated_u_helmholtz(), oomph::LinearisedAxisymmetricNavierStokesEquations::interpolated_u_lin_axi_nst(), oomph::LinearWaveEquations< DIM >::interpolated_u_lin_wave(), oomph::LinearSurfaceContactElement< ELEMENT >::interpolated_u_linear_elasticity(), oomph::HomogenisedLinearElasticityEquationsBase::interpolated_u_linear_elasticity(), oomph::LinearElasticityEquationsBase< DIM >::interpolated_u_linear_elasticity(), oomph::LinearisedAxisymmetricNavierStokesEquations::interpolated_u_linearised_axi_nst(), oomph::LinearisedNavierStokesEquations::interpolated_u_linearised_nst(), oomph::MultiPoissonEquations< DIM, NFIELDS >::interpolated_u_multi_poisson(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::interpolated_u_nst(), oomph::NavierStokesEquations< DIM >::interpolated_u_nst(), oomph::SpaceTimeNavierStokesEquations< DIM >::interpolated_u_nst(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::interpolated_u_nst(), oomph::PMLFourierDecomposedHelmholtzEquations::interpolated_u_pml_fourier_decomposed_helmholtz(), oomph::PMLHelmholtzEquations< DIM >::interpolated_u_pml_helmholtz(), oomph::PolarNavierStokesEquations::interpolated_u_pnst(), oomph::PoissonEquations< DIM >::interpolated_u_poisson(), oomph::SphericalAdvectionDiffusionEquations::interpolated_u_spherical_adv_diff(), oomph::SphericalNavierStokesEquations::interpolated_u_spherical_nst(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::interpolated_u_time_harmonic_fourier_decomposed_linear_elasticity(), oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::interpolated_u_time_harmonic_linear_elasticity(), oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::interpolated_u_time_harmonic_linear_elasticity(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::interpolated_u_ust_heat(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::interpolated_u_ust_heat(), oomph::UnsteadyHeatEquations< DIM >::interpolated_u_ust_heat(), oomph::WomersleyEquations< DIM >::interpolated_u_womersley(), oomph::PolarStreamfunctionEquations::interpolated_velocity(), oomph::PolarStreamfunctionEquations::interpolated_vorticity(), oomph::AxisymFoepplvonKarmanEquations::interpolated_w_fvk(), oomph::DisplacementBasedFoepplvonKarmanEquations::interpolated_w_fvk(), oomph::FoepplvonKarmanEquations::interpolated_w_fvk(), interpolated_x(), oomph::SolidFiniteElement::interpolated_xi(), interpolated_zeta(), J_eulerian(), oomph::FaceElement::J_eulerian(), J_eulerian_at_knot(), oomph::FaceElement::J_eulerian_at_knot(), oomph::ProjectableAdvectionDiffusionReactionElement< ADR_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableAxisymLinearElasticityElement< AXISYM_LINEAR_ELAST_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableAxisymmetricTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableAxisymmetricCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableDarcyElement< DARCY_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableDisplacementBasedFoepplvonKarmanElement< FVK_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableFoepplvonKarmanElement< FVK_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableFourierDecomposedHelmholtzElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >::jacobian_and_shape_of_field(), oomph::GeneralisedNewtonianProjectableAxisymmetricTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::jacobian_and_shape_of_field(), oomph::GeneralisedNewtonianProjectableAxisymmetricCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableGeneralisedNewtonianTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableGeneralisedNewtonianCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableHelmholtzElement< HELMHOLTZ_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableLinearElasticityElement< LINEAR_ELAST_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectablePMLFourierDecomposedHelmholtzElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectablePMLHelmholtzElement< HELMHOLTZ_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectablePMLTimeHarmonicLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectablePoissonElement< POISSON_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableUnsteadyHeatMixedOrderSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableTimeHarmonicFourierDecomposedLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableTimeHarmonicLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::jacobian_and_shape_of_field(), oomph::ProjectableUnsteadyHeatElement< UNSTEADY_HEAT_ELEMENT >::jacobian_and_shape_of_field(), oomph::SolubleSurfactantTransportInterfaceElement::l2_norm_of_height(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::lagrangian_eulerian_translation_factor(), TwoDDGProblem< ELEMENT >::limit(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::LinearisedAxisymPoroelasticBJS_FSIElement(), oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::LinearisedFSIAxisymmetricNStNoSlipBCElementElement(), oomph::KirchhoffLoveShellEquations::load_rate_of_work(), local_to_eulerian_mapping_diagonal(), oomph::RefineableElement::local_to_eulerian_mapping_diagonal(), oomph::SolidFiniteElement::local_to_lagrangian_mapping_diagonal(), oomph::RefineableSolidElement::local_to_lagrangian_mapping_diagonal(), locate_zeta(), oomph::MeshHelper::merge_spine_meshes(), oomph::NetFluxControlElement< ELEMENT >::NetFluxControlElement(), oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >::ngeom_data(), oomph::SolidFiniteElement::ngeom_data(), oomph::RefineableSolidElement::ngeom_data(), oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::ninterpolating_node(), oomph::RefineableAxisymmetricQTaylorHoodElement::ninterpolating_node(), oomph::RefineableGeneralisedNewtonianAxisymmetricQTaylorHoodElement::ninterpolating_node(), oomph::RefineableLinearisedQTaylorHoodElement::ninterpolating_node(), oomph::RefineableQSphericalTaylorHoodElement::ninterpolating_node(), oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::ninterpolating_node(), oomph::RefineableElement::ninterpolating_node(), oomph::RefineableQTaylorHoodElement< DIM >::ninterpolating_node(), oomph::RefineablePolarTaylorHoodElement::ninterpolating_node(), oomph::RefineableQPVDElementWithContinuousPressure< DIM >::ninterpolating_node(), oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::ninterpolating_node(), oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >::ninterpolating_node(), oomph::NodeElementSolidOnlyMortaringElement::node_and_vector_to_data_pt(), node_update(), oomph::Mesh::node_update(), oomph::PRefineableElement::nodes_built(), oomph::DGFaceElement::numerical_flux_at_knot(), oomph::ProjectableAdvectionDiffusionReactionElement< ADR_ELEMENT >::nvalue_of_field(), oomph::ProjectableAxisymLinearElasticityElement< AXISYM_LINEAR_ELAST_ELEMENT >::nvalue_of_field(), oomph::ProjectableAxisymmetricTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::nvalue_of_field(), oomph::ProjectableAxisymmetricCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::nvalue_of_field(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::nvalue_of_field(), oomph::ProjectableDisplacementBasedFoepplvonKarmanElement< FVK_ELEMENT >::nvalue_of_field(), oomph::ProjectableFoepplvonKarmanElement< FVK_ELEMENT >::nvalue_of_field(), oomph::ProjectableFourierDecomposedHelmholtzElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >::nvalue_of_field(), oomph::GeneralisedNewtonianProjectableAxisymmetricTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::nvalue_of_field(), oomph::GeneralisedNewtonianProjectableAxisymmetricCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::nvalue_of_field(), oomph::ProjectableGeneralisedNewtonianTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::nvalue_of_field(), oomph::ProjectableGeneralisedNewtonianCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::nvalue_of_field(), oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::nvalue_of_field(), oomph::ProjectableHelmholtzElement< HELMHOLTZ_ELEMENT >::nvalue_of_field(), oomph::ProjectableLinearElasticityElement< LINEAR_ELAST_ELEMENT >::nvalue_of_field(), oomph::ProjectablePMLFourierDecomposedHelmholtzElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >::nvalue_of_field(), oomph::ProjectablePMLHelmholtzElement< HELMHOLTZ_ELEMENT >::nvalue_of_field(), oomph::ProjectablePMLTimeHarmonicLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::nvalue_of_field(), oomph::ProjectablePoissonElement< POISSON_ELEMENT >::nvalue_of_field(), oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::nvalue_of_field(), oomph::ProjectableUnsteadyHeatMixedOrderSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::nvalue_of_field(), oomph::ProjectableTimeHarmonicFourierDecomposedLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::nvalue_of_field(), oomph::ProjectableTimeHarmonicLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::nvalue_of_field(), oomph::ProjectableUnsteadyHeatElement< UNSTEADY_HEAT_ELEMENT >::nvalue_of_field(), OneDimMesh< ELEMENT >::OneDimMesh(), oomph::LinearElasticitySmoothMesh< LINEAR_ELASTICITY_ELEMENT >::operator()(), oomph::PoissonSmoothMesh< POISSON_ELEMENT >::operator()(), oomph::PeriodicOrbitEquations::orbit_output(), oomph::FaceElement::outer_unit_normal(), oomph::DummyFaceElement< ELEMENT >::output(), oomph::UnsteadyHeatFluxPseudoMeltElement< ELEMENT >::output(), oomph::AxisymmetricLinearElasticityTractionElement< ELEMENT >::output(), oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::output(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::output(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::output(), oomph::HermiteBeamElement::output(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::output(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::output(), oomph::MyTaylorHoodElement< DIM >::output(), oomph::TriangleMesh< ELEMENT >::output_boundary_coordinates(), oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >::output_integration_points(), output_paraview(), oomph::LinearisedAxisymmetricNavierStokesEquations::output_veloc(), oomph::AxisymmetricNavierStokesEquations::output_veloc(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::output_veloc(), oomph::LinearisedNavierStokesEquations::output_veloc(), oomph::PolarNavierStokesEquations::output_veloc(), oomph::SphericalNavierStokesEquations::output_veloc(), oomph::TreeBasedRefineableMeshBase::p_adapt_mesh(), oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::p_refine(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::p_refine(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::p_refine(), oomph::Tree::p_refine_if_required(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::pin_all(), oomph::AxisymmetricTTaylorHoodElement::pin_all_nodal_pressure_dofs(), oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::pin_all_nodal_pressure_dofs(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::pin_all_non_pressure_dofs(), oomph::NavierStokesEquations< DIM >::pin_all_non_pressure_dofs(), oomph::SpaceTimeNavierStokesEquations< DIM >::pin_all_non_pressure_dofs(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::pin_all_non_pressure_dofs(), oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::pin_elemental_redundant_nodal_pressure_dofs(), oomph::RefineableAxisymmetricQTaylorHoodElement::pin_elemental_redundant_nodal_pressure_dofs(), oomph::RefineableGeneralisedNewtonianAxisymmetricQTaylorHoodElement::pin_elemental_redundant_nodal_pressure_dofs(), oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::pin_elemental_redundant_nodal_pressure_dofs(), oomph::RefineableLinearisedQTaylorHoodElement::pin_elemental_redundant_nodal_pressure_dofs(), oomph::RefineableQTaylorHoodElement< DIM >::pin_elemental_redundant_nodal_pressure_dofs(), oomph::RefineablePolarTaylorHoodElement::pin_elemental_redundant_nodal_pressure_dofs(), oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::pin_elemental_redundant_nodal_pressure_dofs(), oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >::pin_elemental_redundant_nodal_pressure_dofs(), oomph::RefineableQSphericalTaylorHoodElement::pin_elemental_redundant_nodal_pressure_dofs(), oomph::RefineableQPVDElementWithContinuousPressure< DIM >::pin_elemental_redundant_nodal_solid_pressures(), oomph::LinearisedQCrouzeixRaviartElement::pin_real_or_imag(), oomph::MGSolver< DIM >::plot(), oomph::PMLQuadMeshBase< ELEMENT >::pml_locate_zeta(), oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >::position(), oomph::NodeElementSolidOnlyMortaringElement::position_in_element(), oomph::SolidFiniteElement::position_local_eqn(), oomph::StorableShapeElementBase::pre_compute_d2shape_eulerian_at_knots(), oomph::StorableShapeSolidElementBase::pre_compute_d2shape_lagrangian_at_knots(), oomph::StorableShapeElementBase::pre_compute_d2shape_local_at_knots(), oomph::StorableShapeElementBase::pre_compute_dshape_eulerian_at_knots(), oomph::StorableShapeSolidElementBase::pre_compute_dshape_lagrangian_at_knots(), oomph::StorableShapeElementBase::pre_compute_dshape_local_at_knots(), oomph::InterpolateFromIntegralPointsBase::pre_compute_ipt_to_node_mapping(), oomph::StorableShapeElementBase::pre_compute_shape_at_knots(), PressureWaveFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::PressureWaveFSIProblem(), print_connectivity_matrix(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::project(), oomph::MacroElementNodeUpdateElement< ELEMENT >::rebuild_from_sons(), oomph::TreeBasedRefineableMeshBase::refine_as_in_reference_mesh(), oomph::RefineableImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::RefineableFSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), oomph::RefineableNavierStokesFluxControlElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction(), RefineableUnsteadyHeatProblem< ELEMENT >::RefineableUnsteadyHeatProblem(), oomph::DGFaceElement::report_info(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::residual_for_projection(), oomph::ProjectableDarcyElement< DARCY_ELEMENT >::residual_for_projection(), oomph::ProjectableElement< ELEMENT >::residual_for_projection(), oomph::FaceElement::resize_nodes(), oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::scalar_value_paraview(), self_test(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::set_boundary_conditions(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::set_boundary_shape_geom_object_pt(), HeatedCircularPenetratorElement::set_contact_element_mesh_pt(), CircularPenetratorElement::set_contact_element_mesh_pt(), oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::set_external_data_from_navier_stokes_outflow_mesh(), AdvectionProblem::set_initial_conditions(), EulerProblem::set_initial_conditions(), oomph::SurfaceMeltElement< ELEMENT >::set_lagrange_multiplier_pressure_to_zero(), oomph::MacroElementNodeUpdateElement< ELEMENT >::set_node_update_info(), oomph::SurfaceContactElementBase< ELEMENT >::set_penetrator_pt(), oomph::MGSolver< DIM >::set_self_test_vector(), oomph::PeriodicOrbitEquations::set_timestepper_weights(), oomph::VolumeConstraintBoundingElement::set_volume_constraint_element(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::setup_algebraic_node_update(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::setup_algebraic_node_update(), oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::setup_algebraic_node_update(), oomph::AlgebraicElementBase::setup_algebraic_node_update(), oomph::UnstructuredTwoDMeshGeometryBase::setup_boundary_coordinates(), oomph::FluidInterfaceAdditionalValues< SolubleSurfactantTransportInterfaceElement >::setup_equation_indices(), oomph::FluidInterfaceAdditionalValues< SurfactantTransportInterfaceElement >::setup_equation_indices(), oomph::FourierDecomposedHelmholtzDtNMesh< ELEMENT >::setup_gamma(), oomph::HelmholtzDtNMesh< ELEMENT >::setup_gamma(), oomph::MGSolver< DIM >::setup_interpolation_matrices_unstructured(), oomph::HelmholtzMGPreconditioner< DIM >::setup_interpolation_matrices_unstructured(), oomph::Z2ErrorEstimator::setup_patches(), SolarRadiationProblem< ELEMENT >::setup_shielding_nodes(), oomph::UnsteadyHeatBaseFaceElement< ELEMENT >::shape_and_test(), oomph::UnsteadyHeatFluxPseudoMeltElement< ELEMENT >::shape_and_test(), oomph::AdvectionDiffusionFluxElement< ELEMENT >::shape_and_test(), oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::shape_and_test(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::shape_and_test(), oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >::shape_and_test(), oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::shape_and_test(), oomph::HelmholtzFluxElement< ELEMENT >::shape_and_test(), oomph::LinearWaveFluxElement< ELEMENT >::shape_and_test(), oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::shape_and_test(), oomph::HelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::shape_and_test(), oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::shape_and_test(), oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::shape_and_test(), oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::shape_and_test(), oomph::PMLHelmholtzFluxElement< ELEMENT >::shape_and_test(), oomph::PoissonFluxElement< ELEMENT >::shape_and_test(), oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::shape_and_test(), oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::shape_and_test(), oomph::UnsteadyHeatFluxElement< ELEMENT >::shape_and_test(), oomph::PolarStreamfunctionTractionElement< ELEMENT >::shape_and_test_at_knot(), oomph::NavierStokesFluxControlElement< ELEMENT >::shape_and_test_at_knot(), oomph::AdvectionDiffusionFluxElement< ELEMENT >::shape_and_test_at_knot(), oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::shape_and_test_at_knot(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::shape_and_test_at_knot(), oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::shape_and_test_at_knot(), oomph::HelmholtzFluxElement< ELEMENT >::shape_and_test_at_knot(), oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::shape_and_test_at_knot(), oomph::HelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::shape_and_test_at_knot(), oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::shape_and_test_at_knot(), oomph::NavierStokesTractionElement< ELEMENT >::shape_and_test_at_knot(), oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::shape_and_test_at_knot(), oomph::PMLHelmholtzFluxElement< ELEMENT >::shape_and_test_at_knot(), oomph::PoissonFluxElement< ELEMENT >::shape_and_test_at_knot(), oomph::PolarNavierStokesTractionElement< ELEMENT >::shape_and_test_at_knot(), oomph::PolarStressIntegralElement< ELEMENT >::shape_and_test_at_knot(), oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::shape_and_test_at_knot(), oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::shape_and_test_at_knot(), oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::shape_and_test_at_knot(), oomph::SurfactantTransportInterfaceElement::sigma(), SimpleRefineableRectangularQuadMesh< ELEMENT >::SimpleRefineableRectangularQuadMesh(), oomph::TetMeshBase::snap_nodes_onto_geometric_objects(), oomph::TetMeshBase::snap_to_quadratic_surface(), oomph::SolidQHermiteElement< DIM >::SolidQHermiteElement(), RefineableRotatingCylinderProblem< ELEMENT >::solve(), oomph::SpineElement< ELEMENT >::spine_local_eqn(), oomph::PerturbedSpineElement< ELEMENT >::spine_local_eqn(), oomph::SpineUpdateFluidInterfaceElement< EQUATION_CLASS, DERIVATIVE_CLASS, ELEMENT >::SpineUpdateFluidInterfaceElement(), oomph::TetMeshBase::split_elements_in_corners(), oomph::Tree::split_if_required(), oomph::MyTaylorHoodElement< DIM >::square_of_l2_norm(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::square_of_l2_norm_of_error(), oomph::LinearisedAxisymmetricNavierStokesEquations::strain_rate(), oomph::AxisymmetricNavierStokesEquations::strain_rate(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::strain_rate(), oomph::PolarNavierStokesEquations::strain_rate(), oomph::SphericalNavierStokesEquations::strain_rate(), oomph::LinearisedNavierStokesEquations::strain_rate(), oomph::PolarNavierStokesEquations::strain_rate_by_r(), oomph::SurfaceContactElementBase< ELEMENT >::SurfaceContactElementBase(), oomph::SurfaceMeltElement< ELEMENT >::SurfaceMeltElement(), ThreeDimBethertonProblem< ELEMENT >::ThreeDimBethertonProblem(), oomph::AxisymmetricPoroelasticityEquations::transform_basis(), oomph::PoroelasticityEquations< DIM >::transform_basis(), TriangleFaceTestProblem< ELEMENT >::TriangleFaceTestProblem(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::TurekProblem(), oomph::RefineableElement::unbuild(), oomph::AxisymmetricTTaylorHoodElement::unpin_all_nodal_pressure_dofs(), oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::unpin_all_nodal_pressure_dofs(), oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::unpin_elemental_pressure_dofs(), oomph::RefineableAxisymmetricQTaylorHoodElement::unpin_elemental_pressure_dofs(), oomph::RefineableGeneralisedNewtonianAxisymmetricQTaylorHoodElement::unpin_elemental_pressure_dofs(), oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::unpin_elemental_pressure_dofs(), oomph::RefineableLinearisedQTaylorHoodElement::unpin_elemental_pressure_dofs(), oomph::RefineableQTaylorHoodElement< DIM >::unpin_elemental_pressure_dofs(), oomph::RefineablePolarTaylorHoodElement::unpin_elemental_pressure_dofs(), oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::unpin_elemental_pressure_dofs(), oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >::unpin_elemental_pressure_dofs(), oomph::RefineableQSphericalTaylorHoodElement::unpin_elemental_pressure_dofs(), oomph::RefineableQPVDElementWithContinuousPressure< DIM >::unpin_elemental_solid_pressure_dofs(), oomph::QPVDElementWithContinuousPressure< DIM >::unpin_elemental_solid_pressure_dofs(), oomph::TPVDElementWithContinuousPressure< DIM >::unpin_elemental_solid_pressure_dofs(), oomph::LinearisedQCrouzeixRaviartElement::unpin_real_or_imag(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::unpin_surface(), oomph::UnsteadyHeatFluxPseudoMeltElement< ELEMENT >::UnsteadyHeatFluxPseudoMeltElement(), oomph::SolarRadiationBase::update_limiting_angles(), oomph::AxisymFoepplvonKarmanEquations::use_linear_bending_model(), oomph::DisplacementBasedFoepplvonKarmanEquations::use_linear_bending_model(), oomph::FoepplvonKarmanEquations::use_linear_bending_model(), and oomph::WomersleyMesh< WOMERSLEY_ELEMENT >::WomersleyMesh().
nnode_1d()
virtual unsigned oomph::FiniteElement::nnode_1d () const inline virtual
Return the number of nodes along one edge of the element Default is to return zero — must be overloaded by geometric elements
Reimplemented in oomph::TElement< 3, NNODE_1D >, oomph::TElement< 2, NNODE_1D >, oomph::TElement< 1, NNODE_1D >, oomph::QSpectralElement< 3, NNODE_1D >, oomph::QSpectralElement< 2, NNODE_1D >, oomph::QSpectralElement< 1, NNODE_1D >, oomph::QElement< 3, NNODE_1D >, oomph::QElement< 2, NNODE_1D >, oomph::QElement< 1, NNODE_1D >, oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >, oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >, oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >, oomph::QHermiteElement< DIM >, oomph::QHermiteElement< DIM - 1 >, ModalPRefineableQPoissonElement< DIM >, TwoNodeGeometricElement, FixSpineHeightElement, and FixSpineHeightElement.
     {
       return 0;
     }
Referenced by AxialSolidQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::AxialSolidQuarterTubeMesh(), AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::AxialSpineQuarterTubeMesh(), oomph::GmshTetMesh< ELEMENT >::build_from_scaffold(), oomph::BackwardStepQuadMesh< ELEMENT >::build_mesh(), oomph::ExtrudedCubeMeshFromQuadMesh< ELEMENT >::build_mesh(), oomph::ChannelWithLeafletMesh< ELEMENT >::ChannelWithLeafletMesh(), oomph::CollapsibleChannelMesh< ELEMENT >::CollapsibleChannelMesh(), oomph::EighthSphereMesh< ELEMENT >::EighthSphereMesh(), oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_lin_axi_nst(), oomph::FSIDrivenCavityMesh< ELEMENT >::FSIDrivenCavityMesh(), oomph::BlockPrecQTaylorHoodSpaceTimeElement::get_dof_numbers_for_unknowns(), oomph::BlockPrecQTaylorHoodMixedOrderSpaceTimeElement::get_dof_numbers_for_unknowns(), oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::get_interpolating_node_at_local_coordinate(), oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >::get_interpolating_node_at_local_coordinate(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::nfree_surface_spines(), oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::ninterpolating_node_1d(), oomph::RefineableAxisymmetricQTaylorHoodElement::ninterpolating_node_1d(), oomph::RefineableGeneralisedNewtonianAxisymmetricQTaylorHoodElement::ninterpolating_node_1d(), oomph::RefineableLinearisedQTaylorHoodElement::ninterpolating_node_1d(), oomph::RefineableQSphericalTaylorHoodElement::ninterpolating_node_1d(), oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::ninterpolating_node_1d(), oomph::RefineableElement::ninterpolating_node_1d(), oomph::RefineableQTaylorHoodElement< DIM >::ninterpolating_node_1d(), oomph::RefineablePolarTaylorHoodElement::ninterpolating_node_1d(), oomph::RefineableQPVDElementWithContinuousPressure< DIM >::ninterpolating_node_1d(), oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::ninterpolating_node_1d(), oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >::ninterpolating_node_1d(), oomph::QElementBase::nnode_on_face(), oomph::MGSolver< DIM >::plot(), oomph::PMLQuadMeshBase< ELEMENT >::pml_locate_zeta(), oomph::PMLCornerQuadMesh< ELEMENT >::PMLCornerQuadMesh(), oomph::PMLQuadMesh< ELEMENT >::PMLQuadMesh(), oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::setup_algebraic_node_update(), oomph::BrickMeshBase::setup_boundary_element_info(), oomph::LineMeshBase::setup_boundary_element_info(), oomph::QuadMeshBase::setup_boundary_element_info(), oomph::HermiteQuadMesh< ELEMENT >::setup_boundary_element_info(), oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::shape_and_test_at_knot(), oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::shape_and_test_at_knot(), oomph::SimpleRectangularTriMesh< ELEMENT >::SimpleRectangularTriMesh(), oomph::TetMeshBase::snap_nodes_onto_geometric_objects(), oomph::TetMeshBase::split_elements_in_corners(), and TwoDDGMesh< ELEMENT >::TwoDDGMesh().
nnode_on_face()
virtual unsigned oomph::FiniteElement::nnode_on_face () const inline virtual
Reimplemented in oomph::QElementBase.
     {
       std::string err = "Not implemented for this element.";
       throw OomphLibError(
         err, OOMPH_EXCEPTION_LOCATION, OOMPH_CURRENT_FUNCTION);
     }
References OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
Referenced by build_face_element(), and face_node_number_error_check().
nodal_dimension()
unsigned oomph::FiniteElement::nodal_dimension () const inline
Return the required Eulerian dimension of the nodes in this element.
     {
       return Nodal_dimension;
     }
References Nodal_dimension.
Referenced by assemble_eulerian_base_vectors(), oomph::RefineableElement::assemble_eulerian_base_vectors(), oomph::RefineableElement::assemble_local_to_eulerian_jacobian(), oomph::RefineableSolidElement::assign_solid_hanging_local_eqn_numbers(), oomph::SolidFiniteElement::assign_solid_local_eqn_numbers(), oomph::SolarRadiationBase::atmospheric_radiation(), oomph::AxisymmetricLinearElasticityTractionElement< ELEMENT >::AxisymmetricLinearElasticityTractionElement(), oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::AxisymmetricNavierStokesTractionElement(), oomph::MyProblem::build(), build_face_element(), oomph::Mesh::check_inverted_elements(), oomph::FaceElement::check_J_eulerian_at_knots(), oomph::AxisymmetricNavierStokesEquations::compute_physical_size(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::compute_physical_size(), oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >::construct_boundary_node(), oomph::SolidFiniteElement::construct_boundary_node(), oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >::construct_node(), oomph::SolidFiniteElement::construct_node(), oomph::FaceElement::continuous_tangent_and_outer_unit_normal(), oomph::FSI_functions::doc_fsi(), oomph::FaceElementAsGeomObject< ELEMENT >::FaceElementAsGeomObject(), oomph::ClampedSlidingHermiteBeamBoundaryConditionElement::fill_in_contribution_to_residuals(), oomph::SolidFiniteElement::fill_in_generic_jacobian_for_solid_ic(), oomph::FluidInterfaceElement::fill_in_generic_residual_contribution_interface(), oomph::PointFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary(), oomph::LineFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary(), oomph::SolidFiniteElement::fill_in_jacobian_for_newmark_accel(), oomph::SolidFiniteElement::fill_in_jacobian_from_solid_position_by_fd(), oomph::RefineableSolidElement::fill_in_jacobian_from_solid_position_by_fd(), oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement(), oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement(), oomph::FSIAxisymmetricLinearElasticityTractionElement< ELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >::FSIAxisymmetricLinearElasticityTractionElement(), oomph::FSIHermiteBeamElement::get_dof_numbers_for_unknowns(), oomph::FSIDiagHermiteShellElement::get_dof_numbers_for_unknowns(), oomph::ClampedHermiteShellBoundaryConditionElement::get_dof_numbers_for_unknowns(), oomph::PVDEquationsBase< DIM >::get_dof_numbers_for_unknowns(), oomph::PVDEquationsWithPressure< DIM >::get_dof_numbers_for_unknowns(), oomph::FSILinearisedAxisymPoroelasticTractionElement< POROELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >::get_pressure(), oomph::FSILinearisedAxisymPoroelasticTractionElement< POROELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >::get_traction(), oomph::SurfactantTransportInterfaceElement::integrate_c(), integrate_fct(), interpolated_dxdt(), oomph::LinearSurfaceContactElement< ELEMENT >::interpolated_u_linear_elasticity(), interpolated_x(), J_eulerian(), oomph::FaceElement::J_eulerian(), J_eulerian_at_knot(), oomph::FaceElement::J_eulerian_at_knot(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::lagrangian_eulerian_translation_factor(), oomph::LinearElasticityTractionElement< ELEMENT >::LinearElasticityTractionElement(), oomph::LinearSurfaceContactElement< ELEMENT >::LinearSurfaceContactElement(), oomph::RefineableElement::local_to_eulerian_mapping_diagonal(), oomph::Mesh::nodal_dimension(), oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::nscalar_paraview(), oomph::DGFaceElement::numerical_flux_at_knot(), oomph::FaceElement::outer_unit_normal(), oomph::NonlinearSurfaceContactElement< ELEMENT >::output(), oomph::LinearSurfaceContactElement< ELEMENT >::output(), oomph::UnsteadyHeatBaseFaceElement< ELEMENT >::output(), oomph::AxisymmetricLinearElasticityTractionElement< ELEMENT >::output(), oomph::FSIAxisymmetricLinearElasticityTractionElement< ELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >::output(), oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::output(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::output(), oomph::FSILinearisedAxisymPoroelasticTractionElement< POROELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >::output(), oomph::FluidInterfaceElement::output(), oomph::SurfactantTransportInterfaceElement::output(), oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::output(), oomph::TimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::output(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::output(), oomph::SolidTractionElement< ELEMENT >::output(), oomph::SolarRadiationBase::output_atmospheric_radiation(), oomph::SolarRadiationBase::output_diffuse_radiation_cone(), oomph::SolarRadiationBase::output_diffuse_radiation_cone_max_angle(), oomph::SolarRadiationBase::output_diffuse_radiation_cone_min_angle(), oomph::SolarRadiationBase::output_limiting_angles(), oomph::SurfaceMeltElement< ELEMENT >::output_melt(), oomph::StefanBoltzmannUnsteadyHeatFluxElement< ELEMENT >::output_stefan_boltzmann_radiation(), oomph::PMLTimeHarmonicLinearElasticityTractionElement< ELEMENT >::PMLTimeHarmonicLinearElasticityTractionElement(), oomph::SolidFiniteElement::position_local_eqn(), oomph::StorableShapeElementBase::pre_compute_d2shape_eulerian_at_knots(), oomph::StorableShapeElementBase::pre_compute_dshape_eulerian_at_knots(), oomph::DGFaceElement::report_info(), oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::scalar_name_paraview(), oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::scalar_value_paraview(), oomph::FaceElement::set_tangent_direction(), oomph::TimeHarmonicFourierDecomposedLinearElasticityTractionElement< ELEMENT >::TimeHarmonicFourierDecomposedLinearElasticityTractionElement(), oomph::TimeHarmonicLinearElasticityTractionElement< ELEMENT >::TimeHarmonicLinearElasticityTractionElement(), oomph::TimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::TimeHarmonicLinElastLoadedByHelmholtzPressureBCElement(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement(), and oomph::SolarRadiationBase::update_limiting_angles().
nodal_local_eqn()
int oomph::FiniteElement::nodal_local_eqn (const unsigned & n, const unsigned & i) const inline
Return the local equation number corresponding to the i-th value at the n-th local node.
     {
 #ifdef RANGE_CHECKING
       if (n >= Nnode)
       {
         std::ostringstream error_message;
         error_message << "Range Error: Node number " << n
                       << " is not in the range (0," << Nnode - 1 << ")";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
       else
       {
         unsigned n_value = node_pt(n)->nvalue();
         if (i >= n_value)
         {
           std::ostringstream error_message;
           error_message << "Range Error: value " << i << " at node " << n
                         << " is not in the range (0," << n_value - 1 << ")";
           throw OomphLibError(error_message.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
       }
 #endif
 #ifdef PARANOID
       // Check that the equations have been allocated
       if (Nodal_local_eqn == 0)
       {
         throw OomphLibError(
           "Nodal local equation numbers have not been allocated",
           OOMPH_CURRENT_FUNCTION,
           OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       return Nodal_local_eqn[n][i];
     }
References i, n, Nnode, Nodal_local_eqn, node_pt(), oomph::Data::nvalue(), OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::SolubleSurfactantTransportInterfaceElement::add_additional_residual_contributions_interface(), oomph::SurfactantTransportInterfaceElement::add_additional_residual_contributions_interface(), oomph::DGFaceElement::add_flux_contributions(), oomph::RefineableElement::assign_hanging_local_eqn_numbers(), oomph::AxisymmetricNavierStokesEquations::fill_in_contribution_to_hessian_vector_products(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_contribution_to_hessian_vector_products(), oomph::SpinePointMarangoniSurfactantFluidInterfaceBoundingElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::AxisymFoepplvonKarmanEquations::fill_in_contribution_to_residuals(), oomph::ClampedSlidingHermiteBeamBoundaryConditionElement::fill_in_contribution_to_residuals(), oomph::DisplacementBasedFoepplvonKarmanEquations::fill_in_contribution_to_residuals(), oomph::FoepplvonKarmanEquations::fill_in_contribution_to_residuals(), oomph::ClampedHermiteShellBoundaryConditionElement::fill_in_contribution_to_residuals(), oomph::AxisymmetricLinearElasticityEquations::fill_in_generic_contribution_to_residuals_axisymmetric_linear_elasticity(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::fill_in_generic_contribution_to_residuals_fourier_decomp_time_harmonic_linear_elasticity(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), oomph::ImposeImpenetrabilityElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(), oomph::ImposeParallelOutflowElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(), oomph::AxisymmetricNavierStokesEquations::fill_in_generic_dresidual_contribution_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_dresidual_contribution_axi_nst(), oomph::AxisymmetricPoroelasticityEquations::fill_in_generic_residual_contribution(), oomph::PolarNavierStokesEquations::fill_in_generic_residual_contribution(), oomph::RefineablePolarNavierStokesEquations::fill_in_generic_residual_contribution(), oomph::RefineablePolarStreamfunctionEquations::fill_in_generic_residual_contribution(), oomph::PolarStreamfunctionEquations::fill_in_generic_residual_contribution(), oomph::SteadyAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_adv_diff(), oomph::AxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), oomph::RefineableAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), oomph::AxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::BiharmonicFluidBoundaryElement::fill_in_generic_residual_contribution_biharmonic_boundary(), oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_cons_axisym_adv_diff(), oomph::FourierDecomposedHelmholtzEquations::fill_in_generic_residual_contribution_fourier_decomposed_helmholtz(), oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::fill_in_generic_residual_contribution_fourier_decomposed_helmholtz_DtN_bc(), oomph::HelmholtzAbsorbingBCElement< ELEMENT >::fill_in_generic_residual_contribution_helmholtz_abc(), oomph::HelmholtzDtNBoundaryElement< ELEMENT >::fill_in_generic_residual_contribution_helmholtz_DtN_bc(), oomph::FluidInterfaceElement::fill_in_generic_residual_contribution_interface(), oomph::PointFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary(), oomph::LineFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary(), oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_lin_axi_nst(), oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::LinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst(), oomph::RefineableLinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst(), oomph::PeriodicOrbitEquations::fill_in_generic_residual_contribution_orbit(), oomph::PMLFourierDecomposedHelmholtzEquations::fill_in_generic_residual_contribution_pml_fourier_decomposed_helmholtz(), oomph::RefineableSphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), oomph::SphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), oomph::RefineableSphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst(), oomph::SphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst(), fill_in_jacobian_from_nodal_by_fd(), oomph::RefineableElement::fill_in_jacobian_from_nodal_by_fd(), oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::fill_in_off_diagonal_block_analytic(), oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_off_diagonal_block_analytic(), oomph::NavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::fill_in_off_diagonal_block_analytic(), oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_off_diagonal_block_analytic(), oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::BuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_by_fd(), oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::fill_in_off_diagonal_jacobian_blocks_by_fd(), oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_by_fd(), oomph::MultiPoissonEquations< DIM, NFIELDS >::get_dof_numbers_for_unknowns(), oomph::AxisymmetricLinearElasticityEquationsBase::get_dof_numbers_for_unknowns(), oomph::AxisymmetricQCrouzeixRaviartElement::get_dof_numbers_for_unknowns(), oomph::AxisymmetricQTaylorHoodElement::get_dof_numbers_for_unknowns(), oomph::AxisymmetricTCrouzeixRaviartElement::get_dof_numbers_for_unknowns(), oomph::AxisymmetricTTaylorHoodElement::get_dof_numbers_for_unknowns(), oomph::BiharmonicEquations< DIM >::get_dof_numbers_for_unknowns(), oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >::get_dof_numbers_for_unknowns(), oomph::GeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement::get_dof_numbers_for_unknowns(), oomph::GeneralisedNewtonianAxisymmetricQTaylorHoodElement::get_dof_numbers_for_unknowns(), oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::get_dof_numbers_for_unknowns(), oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::get_dof_numbers_for_unknowns(), oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >::get_dof_numbers_for_unknowns(), oomph::LinearElasticityEquationsBase< DIM >::get_dof_numbers_for_unknowns(), oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::get_dof_numbers_for_unknowns(), oomph::ImposeImpenetrabilityElement< ELEMENT >::get_dof_numbers_for_unknowns(), oomph::ImposeParallelOutflowElement< ELEMENT >::get_dof_numbers_for_unknowns(), oomph::TTaylorHoodElement< DIM >::get_dof_numbers_for_unknowns(), oomph::PMLHelmholtzEquations< DIM >::get_dof_numbers_for_unknowns(), oomph::PMLHelmholtzFluxElement< ELEMENT >::get_dof_numbers_for_unknowns(), oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::get_dof_numbers_for_unknowns(), oomph::ClampedHermiteShellBoundaryConditionElement::get_dof_numbers_for_unknowns(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::get_dof_numbers_for_unknowns(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::get_dof_numbers_for_unknowns(), oomph::BlockPrecQTaylorHoodSpaceTimeElement::get_dof_numbers_for_unknowns(), oomph::BlockPrecQTaylorHoodMixedOrderSpaceTimeElement::get_dof_numbers_for_unknowns(), oomph::QSphericalCrouzeixRaviartElement::get_dof_numbers_for_unknowns(), oomph::QSphericalTaylorHoodElement::get_dof_numbers_for_unknowns(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::get_dof_numbers_for_unknowns(), oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::get_dof_numbers_for_unknowns(), oomph::AxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::AxisymmetricNavierStokesEquations::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::SphericalNavierStokesEquations::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::ElasticPointFluidInterfaceBoundingElement< ELEMENT >::kinematic_local_eqn(), oomph::ElasticLineFluidInterfaceBoundingElement< ELEMENT >::kinematic_local_eqn(), oomph::ProjectableAdvectionDiffusionReactionElement< ADR_ELEMENT >::local_equation(), oomph::ProjectableAxisymLinearElasticityElement< AXISYM_LINEAR_ELAST_ELEMENT >::local_equation(), oomph::ProjectableAxisymmetricTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::local_equation(), oomph::ProjectableAxisymmetricCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::local_equation(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::local_equation(), oomph::ProjectableDisplacementBasedFoepplvonKarmanElement< FVK_ELEMENT >::local_equation(), oomph::ProjectableFoepplvonKarmanElement< FVK_ELEMENT >::local_equation(), oomph::ProjectableFourierDecomposedHelmholtzElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >::local_equation(), oomph::GeneralisedNewtonianProjectableAxisymmetricTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::local_equation(), oomph::GeneralisedNewtonianProjectableAxisymmetricCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::local_equation(), oomph::ProjectableGeneralisedNewtonianTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::local_equation(), oomph::ProjectableGeneralisedNewtonianCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::local_equation(), oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::local_equation(), oomph::ProjectableHelmholtzElement< HELMHOLTZ_ELEMENT >::local_equation(), oomph::ProjectableLinearElasticityElement< LINEAR_ELAST_ELEMENT >::local_equation(), oomph::ProjectablePMLFourierDecomposedHelmholtzElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >::local_equation(), oomph::ProjectablePMLHelmholtzElement< HELMHOLTZ_ELEMENT >::local_equation(), oomph::ProjectablePMLTimeHarmonicLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::local_equation(), oomph::ProjectablePoissonElement< POISSON_ELEMENT >::local_equation(), oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::local_equation(), oomph::ProjectableUnsteadyHeatMixedOrderSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::local_equation(), oomph::ProjectableTimeHarmonicFourierDecomposedLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::local_equation(), oomph::ProjectableTimeHarmonicLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::local_equation(), oomph::ProjectableUnsteadyHeatElement< UNSTEADY_HEAT_ELEMENT >::local_equation(), oomph::PolarTaylorHoodElement::p_local_eqn(), oomph::AxisymmetricQTaylorHoodElement::p_local_eqn(), oomph::AxisymmetricTTaylorHoodElement::p_local_eqn(), oomph::GeneralisedNewtonianAxisymmetricQTaylorHoodElement::p_local_eqn(), oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::p_local_eqn(), oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::p_local_eqn(), oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >::p_local_eqn(), oomph::QTaylorHoodElement< DIM >::p_local_eqn(), oomph::TTaylorHoodElement< DIM >::p_local_eqn(), oomph::QTaylorHoodSpaceTimeElement< DIM >::p_local_eqn(), oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >::p_local_eqn(), oomph::QSphericalTaylorHoodElement::p_local_eqn(), oomph::LinearisedAxisymmetricQTaylorHoodElement::p_local_eqn(), oomph::LinearisedQTaylorHoodElement::p_local_eqn(), oomph::VolumeConstraintBoundingElement::ptraded_local_eqn(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_edge_local_eqn(), oomph::TRaviartThomasDarcyElement< ORDER >::q_edge_local_eqn(), oomph::TPoroelasticityElement< ORDER >::q_edge_local_eqn(), oomph::RefineableImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::RefineableFSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), oomph::RefineableNavierStokesFluxControlElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction(), oomph::PolarStreamfunctionTractionElement< ELEMENT >::s_local_eqn(), oomph::PeriodicOrbitEquations::set_timestepper_weights(), oomph::FourierDecomposedHelmholtzDtNMesh< ELEMENT >::setup_gamma(), oomph::HelmholtzDtNMesh< ELEMENT >::setup_gamma(), oomph::QPVDElementWithContinuousPressure< DIM >::solid_p_local_eqn(), oomph::TPVDElementWithContinuousPressure< DIM >::solid_p_local_eqn(), oomph::YoungLaplaceContactAngleElement< ELEMENT >::u_local_eqn(), oomph::YoungLaplaceEquations::u_local_eqn(), oomph::NavierStokesFluxControlElement< ELEMENT >::u_local_eqn(), oomph::NavierStokesTractionElement< ELEMENT >::u_local_eqn(), oomph::PolarNavierStokesTractionElement< ELEMENT >::u_local_eqn(), oomph::PolarStressIntegralElement< ELEMENT >::u_local_eqn(), oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::u_local_eqn(), oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::u_local_eqn(), and oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::u_local_eqn().
nodal_position() [1/2]
double oomph::FiniteElement::nodal_position (const unsigned & n, const unsigned & i) const inline
Return the i-th coordinate at local node n. If the node is hanging, the appropriate interpolation is handled by the position function in the Node class.
     {
       return node_pt(n)->position(i);
     }
References i, n, node_pt(), and oomph::Node::position().
Referenced by oomph::HelmholtzBCElementBase< ELEMENT >::compute_contribution_to_fourier_components(), oomph::EulerEquations< DIM >::compute_error(), oomph::ScalarAdvectionEquations< DIM >::compute_error(), oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::compute_stabilisation_parameter(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::contribution_to_enclosed_volume(), oomph::LineVolumeConstraintBoundingElement::contribution_to_enclosed_volume(), oomph::AxisymmetricVolumeConstraintBoundingElement::contribution_to_enclosed_volume(), oomph::StefanBoltzmannRadiationBase::contribution_to_stefan_boltzmann_radiation(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::contribution_to_total_porous_flux(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::contribution_to_total_porous_flux(), oomph::AxisymmetricVolumeConstraintBoundingElement::contribution_to_volume_flux(), oomph::LinearisedAxisymmetricNavierStokesEquations::dkin_energy_dt(), oomph::DisplacementBasedFoepplvonKarmanEquations::fill_in_contribution_to_residuals(), oomph::RefineableYoungLaplaceEquations::fill_in_contribution_to_residuals(), oomph::YoungLaplaceEquations::fill_in_contribution_to_residuals(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), oomph::AxisymmetricPoroelasticityEquations::fill_in_generic_residual_contribution(), oomph::PolarNavierStokesEquations::fill_in_generic_residual_contribution(), oomph::RefineablePolarNavierStokesEquations::fill_in_generic_residual_contribution(), oomph::RefineablePolarStreamfunctionEquations::fill_in_generic_residual_contribution(), oomph::RefineableAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_cons_axisym_adv_diff(), oomph::NavierStokesFluxControlElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction(), oomph::FluidInterfaceElement::fill_in_generic_residual_contribution_interface(), oomph::LineFluidInterfaceBoundingElement::fill_in_generic_residual_contribution_interface_boundary(), oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::RefineableLinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst(), oomph::RefineableSphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), oomph::RefineableSphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst(), oomph::LineVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint(), oomph::AxisymmetricVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint(), oomph::SurfaceVolumeConstraintBoundingElement::fill_in_generic_residual_contribution_volume_constraint(), oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::SphericalAdvectionDiffusionEquations::get_flux(), oomph::AxisymmetricNavierStokesEquations::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::SphericalNavierStokesEquations::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::get_strain(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::get_total_flux(), oomph::SurfactantTransportInterfaceElement::integrate_c(), oomph::PolarStreamfunctionEquations::interpolated_vorticity(), oomph::SolubleSurfactantTransportInterfaceElement::l2_norm_of_height(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::lagrangian_eulerian_translation_factor(), oomph::UnsteadyHeatFluxPseudoMeltElement< ELEMENT >::output(), oomph::AxisymmetricLinearElasticityTractionElement< ELEMENT >::output(), oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::output(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::output(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::output(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::output(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::output(), oomph::LinearisedAxisymmetricNavierStokesEquations::output_veloc(), oomph::AxisymmetricNavierStokesEquations::output_veloc(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::output_veloc(), oomph::LinearisedNavierStokesEquations::output_veloc(), oomph::PolarNavierStokesEquations::output_veloc(), oomph::SphericalNavierStokesEquations::output_veloc(), oomph::RefineableImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::RefineableFSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::scalar_value_paraview(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::square_of_l2_norm_of_error(), oomph::LinearisedAxisymmetricNavierStokesEquations::strain_rate(), oomph::AxisymmetricNavierStokesEquations::strain_rate(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::strain_rate(), oomph::PolarNavierStokesEquations::strain_rate(), oomph::SphericalNavierStokesEquations::strain_rate(), oomph::PolarNavierStokesEquations::strain_rate_by_r(), oomph::PolarStreamfunctionTractionElement< ELEMENT >::x(), oomph::PolarNavierStokesTractionElement< ELEMENT >::x(), and oomph::PolarStressIntegralElement< ELEMENT >::x().
nodal_position() [2/2]
double oomph::FiniteElement::nodal_position (const unsigned & t, const unsigned & n, const unsigned & i) const inline
Return the i-th coordinate at local node n, at time level t (t=0: present; t>0: previous time level) Returns suitably interpolated version for hanging nodes.
     {
       return node_pt(n)->position(t, i);
     }
References i, n, node_pt(), oomph::Node::position(), and plotPSD::t.
nodal_position_gen() [1/2]
double oomph::FiniteElement::nodal_position_gen (const unsigned & n, const unsigned & k, const unsigned & i) const inline
Return the value of the k-th type of the i-th positional variable at the local node n.
     {
       return node_pt(n)->position_gen(k, i);
     }
References i, k, n, node_pt(), and oomph::Node::position_gen().
Referenced by oomph::RefineableElement::assemble_eulerian_base_vectors(), oomph::RefineableElement::assemble_local_to_eulerian_jacobian(), oomph::RefineableElement::assemble_local_to_eulerian_jacobian2(), oomph::FaceElement::check_J_eulerian_at_knots(), oomph::AxisymmetricPVDEquations::compute_physical_size(), oomph::AxisymmetricPVDEquationsWithPressure::compute_physical_size(), oomph::FaceElement::continuous_tangent_and_outer_unit_normal(), oomph::FSIHermiteBeamElement::dposition_dlagrangian_at_local_coordinate(), oomph::FSIDiagHermiteShellElement::dposition_dlagrangian_at_local_coordinate(), oomph::AxisymmetricPVDEquations::fill_in_contribution_to_residuals_axisym_pvd(), oomph::RefineableQDPVDElement< DIM, NNODE_1D >::fill_in_generic_contribution_to_residuals_pvd(), oomph::AxisymmetricPVDEquationsWithPressure::fill_in_generic_residual_contribution_axisym_pvd_with_pressure(), oomph::KirchhoffLoveShellEquations::get_energy(), interpolated_x(), oomph::FaceElement::J_eulerian(), oomph::FaceElement::J_eulerian_at_knot(), oomph::KirchhoffLoveShellEquations::load_rate_of_work(), oomph::RefineableElement::local_to_eulerian_mapping_diagonal(), oomph::FaceElement::outer_unit_normal(), zeta_nodal(), and oomph::ProjectableElement< ELEMENT >::zeta_nodal().
nodal_position_gen() [2/2]
double oomph::FiniteElement::nodal_position_gen (const unsigned & t, const unsigned & n, const unsigned & k, const unsigned & i) const inline
Return the generalised nodal position (type k, i-th variable) at previous timesteps at local node n
     {
       return node_pt(n)->position_gen(t, k, i);
     }
References i, k, n, node_pt(), oomph::Node::position_gen(), and plotPSD::t.
nodal_value() [1/2]
double oomph::FiniteElement::nodal_value (const unsigned & n, const unsigned & i) const inline
Return the i-th value stored at local node n. Produces suitably interpolated values for hanging nodes.
     {
       return node_pt(n)->value(i);
     }
References i, n, node_pt(), and oomph::Node::value().
Referenced by oomph::SolubleSurfactantTransportInterfaceElement::add_additional_residual_contributions_interface(), oomph::SurfactantTransportInterfaceElement::add_additional_residual_contributions_interface(), oomph::HelmholtzBCElementBase< ELEMENT >::compute_contribution_to_fourier_components(), oomph::EulerEquations< DIM >::compute_error(), oomph::ScalarAdvectionEquations< DIM >::compute_error(), oomph::AxisymmetricPoroelasticityEquations::d2u_dt2(), oomph::PoroelasticityEquations< DIM >::d2u_dt2(), oomph::AxisymmetricLinearElasticityEquationsBase::d2u_dt2_axisymmetric_linear_elasticity(), oomph::LinearWaveEquations< DIM >::d2u_dt2_lin_wave(), oomph::LinearElasticityEquationsBase< DIM >::d2u_dt2_linear_elasticity(), oomph::SphericalNavierStokesEquations::d_kin_energy_dt(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::dc_dt_adv_diff_react(), oomph::SurfactantTransportInterfaceElement::dcdt_surface(), oomph::LinearisedAxisymmetricNavierStokesEquations::dkin_energy_dt(), oomph::LinearisedAxisymmetricNavierStokesEquations::dnodal_position_perturbation_dt_lin_axi_nst(), oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >::dposition_dt(), oomph::AxisymmetricPoroelasticityEquations::du_dt(), oomph::PoroelasticityEquations< DIM >::du_dt(), oomph::AdvectionDiffusionEquations< DIM >::du_dt_adv_diff(), oomph::AxisymAdvectionDiffusionEquations::du_dt_axi_adv_diff(), oomph::AxisymmetricNavierStokesEquations::du_dt_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::du_dt_axi_nst(), oomph::AxisymmetricLinearElasticityEquationsBase::du_dt_axisymmetric_linear_elasticity(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::du_dt_cons_adv_diff(), oomph::LinearisedAxisymmetricNavierStokesEquations::du_dt_lin_axi_nst(), oomph::LinearWaveEquations< DIM >::du_dt_lin_wave(), oomph::LinearisedAxisymmetricNavierStokesEquations::du_dt_linearised_axi_nst(), oomph::LinearisedNavierStokesEquations::du_dt_linearised_nst(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::du_dt_nst(), oomph::NavierStokesEquations< DIM >::du_dt_nst(), oomph::SphericalAdvectionDiffusionEquations::du_dt_spherical_adv_diff(), oomph::SphericalNavierStokesEquations::du_dt_spherical_nst(), oomph::UnsteadyHeatEquations< DIM >::du_dt_ust_heat(), oomph::WomersleyEquations< DIM >::du_dt_womersley(), oomph::AxisymFoepplvonKarmanEquations::fill_in_contribution_to_residuals(), oomph::DisplacementBasedFoepplvonKarmanEquations::fill_in_contribution_to_residuals(), oomph::FoepplvonKarmanEquations::fill_in_contribution_to_residuals(), oomph::ImposeImpenetrabilityElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(), oomph::ImposeParallelOutflowElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(), oomph::PolarNavierStokesEquations::fill_in_generic_residual_contribution(), oomph::RefineablePolarNavierStokesEquations::fill_in_generic_residual_contribution(), oomph::RefineablePolarStreamfunctionEquations::fill_in_generic_residual_contribution(), oomph::PolarStreamfunctionEquations::fill_in_generic_residual_contribution(), oomph::RefineableAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_cons_axisym_adv_diff(), oomph::HelmholtzAbsorbingBCElement< ELEMENT >::fill_in_generic_residual_contribution_helmholtz_abc(), oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::RefineableLinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst(), oomph::RefineableSphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), oomph::RefineableSphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst(), oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_off_diagonal_block_analytic(), oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::SphericalNavierStokesEquations::full_output(), oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::ProjectableAdvectionDiffusionReactionElement< ADR_ELEMENT >::get_field(), oomph::ProjectableAxisymLinearElasticityElement< AXISYM_LINEAR_ELAST_ELEMENT >::get_field(), oomph::ProjectableAxisymmetricTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::get_field(), oomph::ProjectableDisplacementBasedFoepplvonKarmanElement< FVK_ELEMENT >::get_field(), oomph::ProjectableFoepplvonKarmanElement< FVK_ELEMENT >::get_field(), oomph::ProjectableFourierDecomposedHelmholtzElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >::get_field(), oomph::GeneralisedNewtonianProjectableAxisymmetricTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::get_field(), oomph::ProjectableGeneralisedNewtonianTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::get_field(), oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::get_field(), oomph::ProjectableHelmholtzElement< HELMHOLTZ_ELEMENT >::get_field(), oomph::ProjectableLinearElasticityElement< LINEAR_ELAST_ELEMENT >::get_field(), oomph::ProjectablePMLFourierDecomposedHelmholtzElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >::get_field(), oomph::ProjectablePMLHelmholtzElement< HELMHOLTZ_ELEMENT >::get_field(), oomph::ProjectablePMLTimeHarmonicLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::get_field(), oomph::ProjectablePoissonElement< POISSON_ELEMENT >::get_field(), oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::get_field(), oomph::ProjectableUnsteadyHeatMixedOrderSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::get_field(), oomph::ProjectableTimeHarmonicFourierDecomposedLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::get_field(), oomph::ProjectableTimeHarmonicLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::get_field(), oomph::ProjectableUnsteadyHeatElement< UNSTEADY_HEAT_ELEMENT >::get_field(), oomph::PolarStreamfunctionEquations::get_flux(), oomph::AdvectionDiffusionEquations< DIM >::get_flux(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::get_flux(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::get_flux(), oomph::AxisymAdvectionDiffusionEquations::get_flux(), oomph::LinearWaveEquations< DIM >::get_flux(), oomph::PoissonEquations< DIM >::get_flux(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::get_flux(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::get_flux(), oomph::SphericalAdvectionDiffusionEquations::get_flux(), oomph::SteadyAxisymAdvectionDiffusionEquations::get_flux(), oomph::UnsteadyHeatEquations< DIM >::get_flux(), oomph::WomersleyEquations< DIM >::get_flux(), oomph::FourierDecomposedHelmholtzEquations::get_flux(), oomph::HelmholtzEquations< DIM >::get_flux(), oomph::PMLFourierDecomposedHelmholtzEquations::get_flux(), oomph::PMLHelmholtzEquations< DIM >::get_flux(), oomph::AxisymFoepplvonKarmanEquations::get_gradient_of_deflection(), oomph::DisplacementBasedFoepplvonKarmanEquations::get_gradient_of_deflection(), oomph::FoepplvonKarmanEquations::get_gradient_of_deflection(), oomph::DisplacementBasedFoepplvonKarmanEquations::get_gradient_of_field(), oomph::SpectralPeriodicOrbitElement< NNODE_1D >::get_interpolated_values(), oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::get_interpolated_values(), oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::get_interpolated_values(), oomph::RefineableAxisymmetricQTaylorHoodElement::get_interpolated_values(), oomph::RefineableAxisymmetricQCrouzeixRaviartElement::get_interpolated_values(), oomph::RefineableGeneralisedNewtonianAxisymmetricQTaylorHoodElement::get_interpolated_values(), oomph::RefineableGeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement::get_interpolated_values(), oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::get_interpolated_values(), oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::get_interpolated_values(), oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::get_interpolated_values(), oomph::RefineableLinearElasticityEquations< DIM >::get_interpolated_values(), oomph::RefineableLinearisedQCrouzeixRaviartElement::get_interpolated_values(), oomph::RefineableLinearisedQTaylorHoodElement::get_interpolated_values(), oomph::RefineableQTaylorHoodElement< DIM >::get_interpolated_values(), oomph::RefineableQCrouzeixRaviartElement< DIM >::get_interpolated_values(), oomph::PRefineableQCrouzeixRaviartElement< DIM >::get_interpolated_values(), oomph::RefineablePolarTaylorHoodElement::get_interpolated_values(), oomph::RefineablePolarCrouzeixRaviartElement::get_interpolated_values(), oomph::RefineableQSphericalTaylorHoodElement::get_interpolated_values(), oomph::RefineableQSphericalCrouzeixRaviartElement::get_interpolated_values(), oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >::get_interpolated_values(), oomph::RefineablePolarStreamfunctionEquations::get_interpolated_values(), oomph::RefineableAdvectionDiffusionEquations< DIM >::get_interpolated_values(), oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::get_interpolated_values(), oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >::get_interpolated_values(), oomph::RefineableAxisymAdvectionDiffusionEquations::get_interpolated_values(), oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::get_interpolated_values(), oomph::RefineableHelmholtzEquations< DIM >::get_interpolated_values(), oomph::RefineableLinearWaveEquations< DIM >::get_interpolated_values(), oomph::RefineablePMLHelmholtzEquations< DIM >::get_interpolated_values(), oomph::RefineablePoissonEquations< DIM >::get_interpolated_values(), oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::get_interpolated_values(), oomph::RefineableSpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::get_interpolated_values(), oomph::RefineableSphericalAdvectionDiffusionEquations::get_interpolated_values(), oomph::RefineableUnsteadyHeatEquations< DIM >::get_interpolated_values(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::get_strain(), oomph::DisplacementBasedFoepplvonKarmanEquations::get_stress_and_strain_for_output(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::get_total_flux(), oomph::SphericalNavierStokesEquations::get_vorticity(), oomph::SpectralPeriodicOrbitElement< NNODE_1D >::get_Z2_flux(), oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::get_Z2_flux(), oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >::get_Z2_flux(), oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::get_Z2_flux(), oomph::RefineableSpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::get_Z2_flux(), oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >::global_power_contribution(), oomph::HelmholtzBCElementBase< ELEMENT >::global_power_contribution(), oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::global_power_contribution(), oomph::PMLHelmholtzPowerElement< ELEMENT >::global_power_contribution(), oomph::SurfactantTransportInterfaceElement::integrate_c(), oomph::SolubleSurfactantTransportInterfaceElement::integrated_C(), oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::integrated_C_and_M(), oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >::integrated_C_and_M(), oomph::SurfactantTransportInterfaceElement::interpolated_C(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::interpolated_c_adv_diff_react(), oomph::SolubleSurfactantTransportInterfaceElement::interpolated_C_bulk(), oomph::AxisymmetricNavierStokesEquations::interpolated_d_dudx_dX_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::interpolated_d_dudx_dX_axi_nst(), oomph::AxisymmetricPoroelasticityEquations::interpolated_div_u(), oomph::SpaceTimeNavierStokesEquations< DIM >::interpolated_du_dt_nst(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::interpolated_du_dt_nst(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::interpolated_du_dt_ust_heat(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::interpolated_du_dt_ust_heat(), oomph::AxisymmetricNavierStokesEquations::interpolated_duds_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::interpolated_duds_axi_nst(), oomph::PolarStreamfunctionEquations::interpolated_dudx(), oomph::AxisymmetricNavierStokesEquations::interpolated_dudx_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::interpolated_dudx_axi_nst(), oomph::NavierStokesEquations< DIM >::interpolated_dudx_nst(), oomph::SphericalNavierStokesEquations::interpolated_dudx_spherical_nst(), oomph::SolubleSurfactantTransportInterfaceElement::interpolated_M(), oomph::LinearisedAxisymmetricNavierStokesEquations::interpolated_nodal_position_perturbation_lin_axi_nst(), oomph::PolarStreamfunctionEquations::interpolated_streamfunction(), oomph::AxisymFoepplvonKarmanEquations::interpolated_stress(), oomph::AxisymmetricPoroelasticityEquations::interpolated_u(), oomph::PoroelasticityEquations< DIM >::interpolated_u(), oomph::AdvectionDiffusionEquations< DIM >::interpolated_u_adv_diff(), oomph::SteadyAxisymAdvectionDiffusionEquations::interpolated_u_adv_diff(), oomph::AxisymAdvectionDiffusionEquations::interpolated_u_axi_adv_diff(), oomph::AxisymmetricNavierStokesEquations::interpolated_u_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::interpolated_u_axi_nst(), oomph::AxisymmetricLinearElasticityEquationsBase::interpolated_u_axisymmetric_linear_elasticity(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::interpolated_u_cons_adv_diff(), oomph::FourierDecomposedHelmholtzEquations::interpolated_u_fourier_decomposed_helmholtz(), oomph::AxisymFoepplvonKarmanEquations::interpolated_u_fvk(), oomph::HelmholtzEquations< DIM >::interpolated_u_helmholtz(), oomph::LinearisedAxisymmetricNavierStokesEquations::interpolated_u_lin_axi_nst(), oomph::LinearWaveEquations< DIM >::interpolated_u_lin_wave(), oomph::LinearSurfaceContactElement< ELEMENT >::interpolated_u_linear_elasticity(), oomph::HomogenisedLinearElasticityEquationsBase::interpolated_u_linear_elasticity(), oomph::LinearElasticityEquationsBase< DIM >::interpolated_u_linear_elasticity(), oomph::LinearisedAxisymmetricNavierStokesEquations::interpolated_u_linearised_axi_nst(), oomph::LinearisedNavierStokesEquations::interpolated_u_linearised_nst(), oomph::MultiPoissonEquations< DIM, NFIELDS >::interpolated_u_multi_poisson(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::interpolated_u_nst(), oomph::NavierStokesEquations< DIM >::interpolated_u_nst(), oomph::SpaceTimeNavierStokesEquations< DIM >::interpolated_u_nst(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::interpolated_u_nst(), oomph::PMLFourierDecomposedHelmholtzEquations::interpolated_u_pml_fourier_decomposed_helmholtz(), oomph::PMLHelmholtzEquations< DIM >::interpolated_u_pml_helmholtz(), oomph::PoissonEquations< DIM >::interpolated_u_poisson(), oomph::SphericalAdvectionDiffusionEquations::interpolated_u_spherical_adv_diff(), oomph::SphericalNavierStokesEquations::interpolated_u_spherical_nst(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::interpolated_u_time_harmonic_fourier_decomposed_linear_elasticity(), oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::interpolated_u_time_harmonic_linear_elasticity(), oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::interpolated_u_time_harmonic_linear_elasticity(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::interpolated_u_ust_heat(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::interpolated_u_ust_heat(), oomph::UnsteadyHeatEquations< DIM >::interpolated_u_ust_heat(), oomph::WomersleyEquations< DIM >::interpolated_u_womersley(), oomph::PolarStreamfunctionEquations::interpolated_velocity(), oomph::AxisymFoepplvonKarmanEquations::interpolated_w_fvk(), oomph::DisplacementBasedFoepplvonKarmanEquations::interpolated_w_fvk(), oomph::FoepplvonKarmanEquations::interpolated_w_fvk(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::lagrangian_eulerian_translation_factor(), oomph::DGFaceElement::numerical_flux_at_knot(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::output(), oomph::MyTaylorHoodElement< DIM >::output(), oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >::output_integration_points(), oomph::LinearisedAxisymmetricNavierStokesEquations::output_veloc(), oomph::AxisymmetricNavierStokesEquations::output_veloc(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::output_veloc(), oomph::LinearisedNavierStokesEquations::output_veloc(), oomph::SphericalNavierStokesEquations::output_veloc(), oomph::AxisymmetricQTaylorHoodElement::p_axi_nst(), oomph::AxisymmetricTTaylorHoodElement::p_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricQTaylorHoodElement::p_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::p_axi_nst(), oomph::LinearisedAxisymmetricQTaylorHoodElement::p_lin_axi_nst(), oomph::LinearisedAxisymmetricQTaylorHoodElement::p_linearised_axi_nst(), oomph::LinearisedQTaylorHoodElement::p_linearised_nst(), oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::p_nst(), oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >::p_nst(), oomph::QTaylorHoodElement< DIM >::p_nst(), oomph::TTaylorHoodElement< DIM >::p_nst(), oomph::QTaylorHoodSpaceTimeElement< DIM >::p_nst(), oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >::p_nst(), oomph::PolarTaylorHoodElement::p_pnst(), oomph::QSphericalTaylorHoodElement::p_spherical_nst(), oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >::position(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_edge(), oomph::TRaviartThomasDarcyElement< ORDER >::q_edge(), oomph::TPoroelasticityElement< ORDER >::q_edge(), oomph::PolarStreamfunctionTractionElement< ELEMENT >::s(), oomph::SurfactantTransportInterfaceElement::sigma(), oomph::QPVDElementWithContinuousPressure< DIM >::solid_p(), oomph::TPVDElementWithContinuousPressure< DIM >::solid_p(), oomph::LinearisedAxisymmetricNavierStokesEquations::strain_rate(), oomph::AxisymmetricNavierStokesEquations::strain_rate(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::strain_rate(), oomph::PolarNavierStokesEquations::strain_rate(), oomph::SphericalNavierStokesEquations::strain_rate(), oomph::PolarNavierStokesEquations::strain_rate_by_r(), oomph::PolarNavierStokesTractionElement< ELEMENT >::u(), oomph::PolarStressIntegralElement< ELEMENT >::u(), oomph::YoungLaplaceEquations::u(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::u_nst(), oomph::NavierStokesEquations< DIM >::u_nst(), oomph::SpaceTimeNavierStokesEquations< DIM >::u_nst(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::u_nst(), oomph::PolarCrouzeixRaviartElement::u_pnst(), oomph::PolarTaylorHoodElement::u_pnst(), and oomph::SphericalNavierStokesEquations::u_spherical_nst().
nodal_value() [2/2]
double oomph::FiniteElement::nodal_value (const unsigned & t, const unsigned & n, const unsigned & i) const inline
Return the i-th value stored at local node n, at time level t (t=0: present; t>0 previous timesteps). Produces suitably interpolated values for hanging nodes.
     {
       return node_pt(n)->value(t, i);
     }
References i, n, node_pt(), plotPSD::t, and oomph::Node::value().
node_pt() [1/2]
Node*& oomph::FiniteElement::node_pt (const unsigned & n) inline
Return a pointer to the local node n.
     {
 #ifdef RANGE_CHECKING
       if (n >= Nnode)
       {
         std::ostringstream error_message;
         error_message << "Range Error: " << n << " is not in the range (0,"
                       << Nnode - 1 << ")";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       return Node_pt[n];
     }
References n, Nnode, Node_pt, OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::TreeBasedRefineableMeshBase::adapt_mesh(), oomph::SurfactantTransportInterfaceElement::add_additional_residual_contributions_interface(), oomph::FaceElement::add_additional_values(), oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::add_element_contribution_to_aux_integral(), oomph::StefanBoltzmannRadiationBase::add_stefan_boltzmann_illumination_info(), oomph::AdvectionDiffusionFluxElement< ELEMENT >::AdvectionDiffusionFluxElement(), oomph::ElementWithMovingNodes::assemble_set_of_all_geometric_data(), oomph::TetMeshBase::assess_mesh_quality(), oomph::ElementWithExternalElement::assign_external_interaction_data_local_eqn_numbers(), oomph::RefineableElement::assign_hanging_local_eqn_numbers(), oomph::GeneralisedElement::assign_local_eqn_numbers(), assign_nodal_local_eqn_numbers(), oomph::RefineableSolidElement::assign_solid_hanging_local_eqn_numbers(), oomph::SolidFiniteElement::assign_solid_local_eqn_numbers(), oomph::Multi_domain_functions::aux_setup_multi_domain_interaction(), AxialSolidQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::AxialSolidQuarterTubeMesh(), AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::AxialSpineQuarterTubeMesh(), oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT >::BackupMeshForProjection(), oomph::BiharmonicFluidBoundaryElement::BiharmonicFluidBoundaryElement(), oomph::LinearElasticityEquationsBase< DIM >::body_force(), oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::body_force(), oomph::PVDEquationsBase< DIM >::body_force(), oomph::RefineableQElement< 3 >::build(), oomph::RefineableSolidQElement< 3 >::build(), oomph::RefineableQElement< 1 >::build(), oomph::RefineableQElement< 2 >::build(), oomph::RefineableSolidQElement< 2 >::build(), build_face_element(), oomph::QHermiteElement< DIM >::build_face_element(), oomph::QSpectralElement< 1, NNODE_1D >::build_face_element(), oomph::QSpectralElement< 2, NNODE_1D >::build_face_element(), oomph::QSpectralElement< 3, NNODE_1D >::build_face_element(), oomph::TBubbleEnrichedElement< DIM, NNODE_1D >::build_face_element(), oomph::TElement< 1, NNODE_1D >::build_face_element(), oomph::TElement< 2, NNODE_1D >::build_face_element(), oomph::TElement< 3, NNODE_1D >::build_face_element(), oomph::GmshTetMesh< ELEMENT >::build_from_scaffold(), oomph::TetgenMesh< ELEMENT >::build_from_scaffold(), oomph::TriangleMesh< ELEMENT >::build_from_scaffold(), oomph::QuadFromTriangleMesh< ELEMENT >::build_from_scaffold(), RefineableUnsteadyHeatProblem< ELEMENT >::build_mesh(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::build_mesh(), oomph::BackwardStepQuadMesh< ELEMENT >::build_mesh(), oomph::ExtrudedCubeMeshFromQuadMesh< ELEMENT >::build_mesh(), oomph::BrickFromTetMesh< ELEMENT >::build_mesh(), oomph::TwoLayerSpineMesh< BASE_ELEMENT >::build_two_layer_mesh(), CapProblem< ELEMENT >::CapProblem(), oomph::ChannelWithLeafletMesh< ELEMENT >::ChannelWithLeafletMesh(), check_jacobian(), oomph::TriangleScaffoldMesh::check_mesh_integrity(), oomph::CollapsibleChannelMesh< ELEMENT >::CollapsibleChannelMesh(), ContactProblem< ELEMENT >::complete_problem_setup(), oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::complete_setup_of_dependencies(), oomph::HelmholtzDtNBoundaryElement< ELEMENT >::complete_setup_of_dependencies(), oomph::RefineableTriangleMesh< ELEMENT >::compute_area_target(), oomph::RefineableTetgenMesh< ELEMENT >::compute_volume_target(), oomph::RefineableTetMeshBase::compute_volume_target(), oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >::construct_boundary_node(), construct_boundary_node(), oomph::SolidFiniteElement::construct_boundary_node(), oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >::construct_node(), construct_node(), oomph::SolidFiniteElement::construct_node(), oomph::StefanBoltzmannRadiationBase::contribution_to_stefan_boltzmann_radiation(), oomph::AxisymmetricVolumeConstraintBoundingElement::contribution_to_volume_flux(), oomph::Mesh::convert_to_boundary_node(), oomph::LinearisedQCrouzeixRaviartElement::copy_efunction_to_normalisation(), ContactProblem< ELEMENT >::create_displ_imposition_elements(), RefineableRotatingCylinderProblem< ELEMENT >::create_free_surface_elements(), UnstructuredTorusProblem< ELEMENT >::create_lagrange_multiplier_elements(), FSICollapsibleChannelProblem< ELEMENT >::create_lagrange_multiplier_elements(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_lagrange_multiplier_elements(), FSIChannelWithLeafletProblem< ELEMENT >::create_lagrange_multiplier_elements(), UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_lagrange_multiplier_elements(), PrescribedBoundaryDisplacementProblem< ELEMENT >::create_lagrange_multiplier_elements(), UnstructuredImmersedEllipseProblem< ELEMENT >::create_lagrange_multiplier_elements(), UnstructuredFluidProblem< ELEMENT >::create_lagrange_multiplier_elements(), CollapsibleChannelProblem< ELEMENT >::create_lagrange_multiplier_elements(), StefanBoltzmannProblem< ELEMENT >::create_melt_elements(), TiltedCavityProblem< ELEMENT >::create_parall_outflow_lagrange_elements(), oomph::AxisymmetricPoroelasticityEquations::d2u_dt2(), oomph::PoroelasticityEquations< DIM >::d2u_dt2(), oomph::AxisymmetricLinearElasticityEquationsBase::d2u_dt2_axisymmetric_linear_elasticity(), oomph::LinearWaveEquations< DIM >::d2u_dt2_lin_wave(), oomph::LinearElasticityEquationsBase< DIM >::d2u_dt2_linear_elasticity(), oomph::ProjectableAdvectionDiffusionReactionElement< ADR_ELEMENT >::data_values_of_field(), oomph::ProjectableAxisymLinearElasticityElement< AXISYM_LINEAR_ELAST_ELEMENT >::data_values_of_field(), oomph::ProjectableAxisymmetricTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::data_values_of_field(), oomph::ProjectableAxisymmetricCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::data_values_of_field(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::data_values_of_field(), oomph::ProjectableDisplacementBasedFoepplvonKarmanElement< FVK_ELEMENT >::data_values_of_field(), oomph::ProjectableFoepplvonKarmanElement< FVK_ELEMENT >::data_values_of_field(), oomph::ProjectableFourierDecomposedHelmholtzElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >::data_values_of_field(), oomph::GeneralisedNewtonianProjectableAxisymmetricTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::data_values_of_field(), oomph::GeneralisedNewtonianProjectableAxisymmetricCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::data_values_of_field(), oomph::ProjectableGeneralisedNewtonianTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::data_values_of_field(), oomph::ProjectableGeneralisedNewtonianCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::data_values_of_field(), oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::data_values_of_field(), oomph::ProjectableHelmholtzElement< HELMHOLTZ_ELEMENT >::data_values_of_field(), oomph::ProjectableLinearElasticityElement< LINEAR_ELAST_ELEMENT >::data_values_of_field(), oomph::ProjectablePMLFourierDecomposedHelmholtzElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >::data_values_of_field(), oomph::ProjectablePMLHelmholtzElement< HELMHOLTZ_ELEMENT >::data_values_of_field(), oomph::ProjectablePMLTimeHarmonicLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::data_values_of_field(), oomph::ProjectablePoissonElement< POISSON_ELEMENT >::data_values_of_field(), oomph::ProjectablePVDElementWithContinuousPressure< PVD_ELEMENT >::data_values_of_field(), oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::data_values_of_field(), oomph::ProjectableUnsteadyHeatMixedOrderSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::data_values_of_field(), oomph::ProjectableTimeHarmonicFourierDecomposedLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::data_values_of_field(), oomph::ProjectableTimeHarmonicLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::data_values_of_field(), oomph::ProjectableUnsteadyHeatElement< UNSTEADY_HEAT_ELEMENT >::data_values_of_field(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::dc_dt_adv_diff_react(), oomph::SurfactantTransportInterfaceElement::dcdt_surface(), oomph::RefineableElement::deactivate_element(), oomph::TPVDElement< DIM, NNODE_1D >::describe_local_dofs(), describe_nodal_local_dofs(), oomph::SolidFiniteElement::describe_solid_local_dofs(), oomph::PerturbedSpineLinearisedAxisymmetricFluidInterfaceElement< ELEMENT >::dH_dt(), oomph::AdvectionDiffusionEquations< DIM >::dinterpolated_u_adv_diff_ddata(), oomph::RefineableAdvectionDiffusionEquations< DIM >::dinterpolated_u_adv_diff_ddata(), oomph::RefineableAxisymAdvectionDiffusionEquations::dinterpolated_u_adv_diff_ddata(), oomph::RefineableSphericalAdvectionDiffusionEquations::dinterpolated_u_adv_diff_ddata(), oomph::SphericalAdvectionDiffusionEquations::dinterpolated_u_adv_diff_ddata(), oomph::SteadyAxisymAdvectionDiffusionEquations::dinterpolated_u_adv_diff_ddata(), oomph::AxisymAdvectionDiffusionEquations::dinterpolated_u_axi_adv_diff_ddata(), oomph::AxisymmetricNavierStokesEquations::dinterpolated_u_axi_nst_ddata(), oomph::RefineableAxisymmetricNavierStokesEquations::dinterpolated_u_axi_nst_ddata(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::dinterpolated_u_axi_nst_ddata(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::dinterpolated_u_axi_nst_ddata(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::dinterpolated_u_nst_ddata(), oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::dinterpolated_u_nst_ddata(), oomph::NavierStokesEquations< DIM >::dinterpolated_u_nst_ddata(), oomph::RefineableNavierStokesEquations< DIM >::dinterpolated_u_nst_ddata(), oomph::SpaceTimeNavierStokesEquations< DIM >::dinterpolated_u_nst_ddata(), oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::dinterpolated_u_nst_ddata(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::dinterpolated_u_nst_ddata(), oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >::dinterpolated_u_nst_ddata(), oomph::SurfaceMeltElement< ELEMENT >::disable_melting(), oomph::UnsteadyHeatFluxPseudoMeltElement< ELEMENT >::disable_melting(), oomph::DiskTetMeshFacetedSurface::DiskTetMeshFacetedSurface(), oomph::DisplacementControlElement::DisplacementControlElement(), dnodal_position_dt(), dnodal_position_gen_dt(), oomph::LinearisedAxisymmetricNavierStokesEquations::dnodal_position_perturbation_dt_lin_axi_nst(), oomph::Mesh::doc_boundary_coordinates(), oomph::Z2ErrorEstimator::doc_flux(), StefanBoltzmannProblem< ELEMENT >::doc_solution(), PoissonProblem< ELEMENT >::doc_solution(), FallingBlockProblem< ELEMENT >::doc_solution(), RisingBubbleProblem< ELEMENT >::doc_solution(), oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >::dposition_dt(), oomph::AxisymmetricPoroelasticityEquations::dq_edge_dt(), oomph::PoroelasticityEquations< DIM >::dq_edge_dt(), oomph::AxisymmetricPoroelasticityEquations::du_dt(), oomph::PoroelasticityEquations< DIM >::du_dt(), oomph::AdvectionDiffusionEquations< DIM >::du_dt_adv_diff(), oomph::AxisymAdvectionDiffusionEquations::du_dt_axi_adv_diff(), oomph::AxisymmetricNavierStokesEquations::du_dt_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::du_dt_axi_nst(), oomph::AxisymmetricLinearElasticityEquationsBase::du_dt_axisymmetric_linear_elasticity(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::du_dt_cons_adv_diff(), oomph::LinearisedAxisymmetricNavierStokesEquations::du_dt_lin_axi_nst(), oomph::LinearWaveEquations< DIM >::du_dt_lin_wave(), oomph::LinearisedAxisymmetricNavierStokesEquations::du_dt_linearised_axi_nst(), oomph::LinearisedNavierStokesEquations::du_dt_linearised_nst(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::du_dt_nst(), oomph::NavierStokesEquations< DIM >::du_dt_nst(), oomph::PolarNavierStokesEquations::du_dt_pnst(), oomph::SphericalAdvectionDiffusionEquations::du_dt_spherical_adv_diff(), oomph::SphericalNavierStokesEquations::du_dt_spherical_nst(), oomph::UnsteadyHeatEquations< DIM >::du_dt_ust_heat(), oomph::WomersleyEquations< DIM >::du_dt_womersley(), oomph::DummyErrorEstimator::DummyErrorEstimator(), oomph::LinearisedAxisymmetricFluidInterfaceElement::dXhat_dt(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::edge_flux_node_pt(), oomph::TRaviartThomasDarcyElement< ORDER >::edge_flux_node_pt(), oomph::EighthSphereMesh< ELEMENT >::EighthSphereMesh(), ElasticRefineableTwoLayerMesh< ELEMENT >::ElasticRefineableTwoLayerMesh(), ElasticTwoLayerMesh< ELEMENT >::ElasticTwoLayerMesh(), oomph::PerturbedSpineMesh::element_node_pt(), oomph::SolidMesh::element_node_pt(), oomph::SpineMesh::element_node_pt(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::extrapolated_strain_rate(), oomph::SpinePointMarangoniSurfactantFluidInterfaceBoundingElement< ELEMENT >::fill_in_contribution_to_jacobian(), oomph::ClampedSlidingHermiteBeamBoundaryConditionElement::fill_in_contribution_to_residuals(), oomph::ClampedHermiteShellBoundaryConditionElement::fill_in_contribution_to_residuals(), oomph::RefineableYoungLaplaceEquations::fill_in_contribution_to_residuals(), oomph::AxisymmetricLinearElasticityEquations::fill_in_generic_contribution_to_residuals_axisymmetric_linear_elasticity(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), oomph::ImposeImpenetrabilityElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(), oomph::ImposeParallelOutflowElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(), oomph::RefineableQDPVDElement< DIM, NNODE_1D >::fill_in_generic_contribution_to_residuals_pvd(), oomph::AxisymmetricNavierStokesEquations::fill_in_generic_dresidual_contribution_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_dresidual_contribution_axi_nst(), oomph::AxisymmetricPoroelasticityEquations::fill_in_generic_residual_contribution(), oomph::RefineablePolarNavierStokesEquations::fill_in_generic_residual_contribution(), oomph::RefineablePolarStreamfunctionEquations::fill_in_generic_residual_contribution(), oomph::AxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), oomph::RefineableAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), oomph::AxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::BiharmonicFluidBoundaryElement::fill_in_generic_residual_contribution_biharmonic_boundary(), oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_cons_axisym_adv_diff(), oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::fill_in_generic_residual_contribution_fourier_decomposed_helmholtz_DtN_bc(), oomph::PerturbedSpineLinearisedAxisymmetricFluidInterfaceElement< ELEMENT >::fill_in_generic_residual_contribution_interface(), oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_lin_axi_nst(), oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::LinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst(), oomph::RefineableLinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst(), oomph::RefineableSphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), oomph::SphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), oomph::RefineableSphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst(), oomph::SphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst(), oomph::SolidFiniteElement::fill_in_jacobian_for_newmark_accel(), oomph::ElementWithMovingNodes::fill_in_jacobian_from_geometric_data(), fill_in_jacobian_from_nodal_by_fd(), oomph::RefineableElement::fill_in_jacobian_from_nodal_by_fd(), oomph::SolidFiniteElement::fill_in_jacobian_from_solid_position_by_fd(), oomph::RefineableSolidElement::fill_in_jacobian_from_solid_position_by_fd(), oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::fill_in_off_diagonal_block_analytic(), oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_off_diagonal_block_analytic(), oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_by_fd(), oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::fill_in_off_diagonal_jacobian_blocks_by_fd(), oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_by_fd(), GlobalParameters::find_node_on_centerline(), oomph::LinearisedAxisymmetricQTaylorHoodElement::fix_cosine_component_of_pressure(), oomph::LinearisedAxisymmetricQTaylorHoodElement::fix_pressure(), oomph::AxisymmetricQTaylorHoodElement::fix_pressure(), oomph::GeneralisedNewtonianAxisymmetricQTaylorHoodElement::fix_pressure(), oomph::LinearisedQTaylorHoodElement::fix_pressure(), oomph::AxisymmetricTTaylorHoodElement::fix_pressure(), oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::fix_pressure(), oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >::fix_pressure(), oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >::fix_pressure(), oomph::QTaylorHoodElement< DIM >::fix_pressure(), oomph::TTaylorHoodElement< DIM >::fix_pressure(), oomph::PolarTaylorHoodElement::fix_pressure(), oomph::QTaylorHoodSpaceTimeElement< DIM >::fix_pressure(), oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >::fix_pressure(), oomph::QSphericalTaylorHoodElement::fix_pressure(), oomph::LinearisedAxisymmetricQTaylorHoodElement::fix_sine_component_of_pressure(), oomph::QPVDElementWithContinuousPressure< DIM >::fix_solid_pressure(), oomph::TPVDElementWithContinuousPressure< DIM >::fix_solid_pressure(), oomph::FSIDrivenCavityMesh< ELEMENT >::FSIDrivenCavityMesh(), FSIRingProblem::FSIRingProblem(), oomph::FullCircleMesh< ELEMENT >::FullCircleMesh(), oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >::geom_data_pt(), oomph::SolidFiniteElement::geom_data_pt(), oomph::RefineableSolidElement::geom_data_pt(), oomph::GeompackQuadScaffoldMesh::GeompackQuadScaffoldMesh(), oomph::ElementWithMovingNodes::get_dnodal_coordinates_dgeom_dofs(), oomph::AxisymmetricQCrouzeixRaviartElement::get_dof_numbers_for_unknowns(), oomph::AxisymmetricQTaylorHoodElement::get_dof_numbers_for_unknowns(), oomph::AxisymmetricTCrouzeixRaviartElement::get_dof_numbers_for_unknowns(), oomph::BiharmonicEquations< DIM >::get_dof_numbers_for_unknowns(), oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >::get_dof_numbers_for_unknowns(), oomph::GeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement::get_dof_numbers_for_unknowns(), oomph::GeneralisedNewtonianAxisymmetricQTaylorHoodElement::get_dof_numbers_for_unknowns(), oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::get_dof_numbers_for_unknowns(), oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::get_dof_numbers_for_unknowns(), oomph::ImposeImpenetrabilityElement< ELEMENT >::get_dof_numbers_for_unknowns(), oomph::ImposeParallelOutflowElement< ELEMENT >::get_dof_numbers_for_unknowns(), oomph::ClampedHermiteShellBoundaryConditionElement::get_dof_numbers_for_unknowns(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::get_dof_numbers_for_unknowns(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::get_dof_numbers_for_unknowns(), oomph::BlockPrecQTaylorHoodSpaceTimeElement::get_dof_numbers_for_unknowns(), oomph::BlockPrecQTaylorHoodMixedOrderSpaceTimeElement::get_dof_numbers_for_unknowns(), oomph::QSphericalCrouzeixRaviartElement::get_dof_numbers_for_unknowns(), oomph::QSphericalTaylorHoodElement::get_dof_numbers_for_unknowns(), oomph::AxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), get_dresidual_dnodal_coordinates(), oomph::RefineableElement::get_dresidual_dnodal_coordinates(), oomph::Z2ErrorEstimator::get_element_errors(), oomph::DummyErrorEstimator::get_element_errors(), oomph::ProjectablePMLTimeHarmonicLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::get_field(), oomph::ProjectableTimeHarmonicFourierDecomposedLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::get_field(), oomph::ProjectableTimeHarmonicLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::get_field(), oomph::SurfaceContactElementBase< ELEMENT >::get_interpolated_lagrange_p(), oomph::SurfaceMeltElement< ELEMENT >::get_interpolated_lagrange_p(), oomph::RefineablePolarTaylorHoodElement::get_interpolated_values(), oomph::RefineablePolarCrouzeixRaviartElement::get_interpolated_values(), oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::get_interpolating_node_at_local_coordinate(), oomph::RefineableAxisymmetricQTaylorHoodElement::get_interpolating_node_at_local_coordinate(), oomph::RefineableGeneralisedNewtonianAxisymmetricQTaylorHoodElement::get_interpolating_node_at_local_coordinate(), oomph::RefineableLinearisedQTaylorHoodElement::get_interpolating_node_at_local_coordinate(), oomph::RefineableQSphericalTaylorHoodElement::get_interpolating_node_at_local_coordinate(), oomph::DGFaceElement::get_interpolation_data(), ThreeDimBethertonProblem< ELEMENT >::get_lambda(), oomph::PolarCrouzeixRaviartElement::get_load_data(), oomph::PolarTaylorHoodElement::get_load_data(), get_node_number(), NodeReordering::get_node_reordering(), oomph::Mesh::get_node_reordering(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::get_wind_adv_diff_react(), get_x(), oomph::SpectralPeriodicOrbitElement< NNODE_1D >::get_Z2_flux(), SCoupling< M, O >::getSCoupledElements(), oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >::global_power_contribution(), oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::global_power_contribution(), has_hanging_nodes(), oomph::HeatedPenetratorFluxElement< ELEMENT >::HeatedPenetratorFluxElement(), oomph::HelmholtzBCElementBase< ELEMENT >::HelmholtzBCElementBase(), oomph::HelmholtzFluxElement< ELEMENT >::HelmholtzFluxElement(), oomph::HelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::HelmholtzFluxFromNormalDisplacementBCElement(), RefineableQAxisymAdvectionDiffusionBoussinesqElement::identify_all_field_data_for_external_interaction(), identify_field_data_for_interactions(), oomph::RefineableElement::identify_field_data_for_interactions(), oomph::SolidFiniteElement::identify_geometric_data(), oomph::RefineableSolidElement::identify_geometric_data(), oomph::FSIAxisymmetricQTaylorHoodElement::identify_load_data(), oomph::AxisymmetricTCrouzeixRaviartElement::identify_load_data(), oomph::AxisymmetricTTaylorHoodElement::identify_load_data(), oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::identify_load_data(), oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::identify_load_data(), oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::identify_load_data(), oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::identify_load_data(), oomph::RefineableQTaylorHoodElement< DIM >::identify_load_data(), oomph::RefineableQCrouzeixRaviartElement< DIM >::identify_load_data(), oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::identify_load_data(), oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >::identify_load_data(), oomph::QSphericalCrouzeixRaviartElement::identify_load_data(), oomph::QSphericalTaylorHoodElement::identify_load_data(), oomph::FSIAxisymmetricQTaylorHoodElement::identify_pressure_data(), oomph::AxisymmetricTTaylorHoodElement::identify_pressure_data(), oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::identify_pressure_data(), oomph::QSphericalTaylorHoodElement::identify_pressure_data(), oomph::RefineablePolarTaylorHoodElement::insert_load_data(), oomph::RefineablePolarCrouzeixRaviartElement::insert_load_data(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::interface_min_max(), oomph::BiharmonicEquations< DIM >::interpolated_dudx(), oomph::PerturbedSpineLinearisedAxisymmetricFluidInterfaceElement< ELEMENT >::interpolated_H(), oomph::SurfaceMeltElement< ELEMENT >::interpolated_melt_rate(), oomph::DGFaceElement::interpolated_u(), oomph::BiharmonicEquations< DIM >::interpolated_u_biharmonic(), oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::interpolating_node_pt(), oomph::RefineableAxisymmetricQTaylorHoodElement::interpolating_node_pt(), oomph::RefineableGeneralisedNewtonianAxisymmetricQTaylorHoodElement::interpolating_node_pt(), oomph::RefineableLinearisedQTaylorHoodElement::interpolating_node_pt(), oomph::RefineableQSphericalTaylorHoodElement::interpolating_node_pt(), oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::interpolating_node_pt(), oomph::RefineableElement::interpolating_node_pt(), oomph::RefineableQTaylorHoodElement< DIM >::interpolating_node_pt(), oomph::RefineablePolarTaylorHoodElement::interpolating_node_pt(), oomph::RefineableQPVDElementWithContinuousPressure< DIM >::interpolating_node_pt(), oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::interpolating_node_pt(), oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >::interpolating_node_pt(), oomph::SolubleSurfactantTransportInterfaceElement::l2_norm_of_height(), oomph::SolidFiniteElement::lagrangian_position(), oomph::SolidFiniteElement::lagrangian_position_gen(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::LinearisedAxisymPoroelasticBJS_FSIElement(), oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::LinearisedFSIAxisymmetricNStNoSlipBCElementElement(), oomph::LinearWaveFluxElement< ELEMENT >::LinearWaveFluxElement(), oomph::ProjectablePMLTimeHarmonicLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::local_equation(), oomph::ProjectableTimeHarmonicFourierDecomposedLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::local_equation(), oomph::ProjectableTimeHarmonicLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::local_equation(), oomph::RefineableElement::local_hang_eqn(), oomph::RefineableSolidElement::local_position_hang_eqn(), oomph::FixedVolumeSpineLineMarangoniFluidInterfaceElement< ELEMENT >::make_bounding_element(), oomph::HelmholtzMGPreconditioner< DIM >::maximum_edge_width(), oomph::MeshHelper::merge_spine_meshes(), oomph::NavierStokesFluxControlElement< ELEMENT >::NavierStokesFluxControlElement(), oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::NavierStokesMixedOrderSpaceTimeTractionElement(), oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::NavierStokesSpaceTimeTractionElement(), oomph::NavierStokesSurfaceDragTorqueElement< ELEMENT >::NavierStokesSurfaceDragTorqueElement(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::NavierStokesSurfacePowerElement(), oomph::NavierStokesTractionElement< ELEMENT >::NavierStokesTractionElement(), oomph::RefineableImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::ncont_interpolated_values(), oomph::RefineableFSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::ncont_interpolated_values(), oomph::NetFluxControlElement< ELEMENT >::NetFluxControlElement(), oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::nfields_for_projection(), oomph::RefineableSolidElement::ngeom_data(), oomph::ProjectableAdvectionDiffusionReactionElement< ADR_ELEMENT >::nhistory_values_for_coordinate_projection(), oomph::ProjectableAxisymLinearElasticityElement< AXISYM_LINEAR_ELAST_ELEMENT >::nhistory_values_for_coordinate_projection(), oomph::ProjectableAxisymmetricTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::nhistory_values_for_coordinate_projection(), oomph::ProjectableAxisymmetricCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::nhistory_values_for_coordinate_projection(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::nhistory_values_for_coordinate_projection(), oomph::ProjectableDarcyElement< DARCY_ELEMENT >::nhistory_values_for_coordinate_projection(), oomph::ProjectableDisplacementBasedFoepplvonKarmanElement< FVK_ELEMENT >::nhistory_values_for_coordinate_projection(), oomph::ProjectableFoepplvonKarmanElement< FVK_ELEMENT >::nhistory_values_for_coordinate_projection(), oomph::ProjectableFourierDecomposedHelmholtzElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >::nhistory_values_for_coordinate_projection(), oomph::GeneralisedNewtonianProjectableAxisymmetricTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::nhistory_values_for_coordinate_projection(), oomph::GeneralisedNewtonianProjectableAxisymmetricCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::nhistory_values_for_coordinate_projection(), oomph::ProjectableGeneralisedNewtonianTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::nhistory_values_for_coordinate_projection(), oomph::ProjectableGeneralisedNewtonianCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::nhistory_values_for_coordinate_projection(), oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::nhistory_values_for_coordinate_projection(), oomph::ProjectableHelmholtzElement< HELMHOLTZ_ELEMENT >::nhistory_values_for_coordinate_projection(), oomph::ProjectableLinearElasticityElement< LINEAR_ELAST_ELEMENT >::nhistory_values_for_coordinate_projection(), oomph::ProjectablePMLFourierDecomposedHelmholtzElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >::nhistory_values_for_coordinate_projection(), oomph::ProjectablePMLHelmholtzElement< HELMHOLTZ_ELEMENT >::nhistory_values_for_coordinate_projection(), oomph::ProjectablePMLTimeHarmonicLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::nhistory_values_for_coordinate_projection(), oomph::ProjectablePoissonElement< POISSON_ELEMENT >::nhistory_values_for_coordinate_projection(), oomph::ProjectablePVDElement< PVD_ELEMENT >::nhistory_values_for_coordinate_projection(), oomph::ProjectablePVDElementWithContinuousPressure< PVD_ELEMENT >::nhistory_values_for_coordinate_projection(), oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::nhistory_values_for_coordinate_projection(), oomph::ProjectableUnsteadyHeatMixedOrderSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::nhistory_values_for_coordinate_projection(), oomph::ProjectableTimeHarmonicFourierDecomposedLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::nhistory_values_for_coordinate_projection(), oomph::ProjectableTimeHarmonicLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::nhistory_values_for_coordinate_projection(), oomph::ProjectableUnsteadyHeatElement< UNSTEADY_HEAT_ELEMENT >::nhistory_values_for_coordinate_projection(), oomph::ProjectableAdvectionDiffusionReactionElement< ADR_ELEMENT >::nhistory_values_for_projection(), oomph::ProjectableAxisymLinearElasticityElement< AXISYM_LINEAR_ELAST_ELEMENT >::nhistory_values_for_projection(), oomph::ProjectableAxisymmetricTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::nhistory_values_for_projection(), oomph::ProjectableAxisymmetricCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::nhistory_values_for_projection(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::nhistory_values_for_projection(), oomph::ProjectableDarcyElement< DARCY_ELEMENT >::nhistory_values_for_projection(), oomph::ProjectableDisplacementBasedFoepplvonKarmanElement< FVK_ELEMENT >::nhistory_values_for_projection(), oomph::ProjectableFoepplvonKarmanElement< FVK_ELEMENT >::nhistory_values_for_projection(), oomph::ProjectableFourierDecomposedHelmholtzElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >::nhistory_values_for_projection(), oomph::GeneralisedNewtonianProjectableAxisymmetricTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::nhistory_values_for_projection(), oomph::GeneralisedNewtonianProjectableAxisymmetricCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::nhistory_values_for_projection(), oomph::ProjectableGeneralisedNewtonianTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::nhistory_values_for_projection(), oomph::ProjectableGeneralisedNewtonianCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >::nhistory_values_for_projection(), oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::nhistory_values_for_projection(), oomph::ProjectableHelmholtzElement< HELMHOLTZ_ELEMENT >::nhistory_values_for_projection(), oomph::ProjectableLinearElasticityElement< LINEAR_ELAST_ELEMENT >::nhistory_values_for_projection(), oomph::ProjectablePMLFourierDecomposedHelmholtzElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >::nhistory_values_for_projection(), oomph::ProjectablePMLHelmholtzElement< HELMHOLTZ_ELEMENT >::nhistory_values_for_projection(), oomph::ProjectablePMLTimeHarmonicLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::nhistory_values_for_projection(), oomph::ProjectablePoissonElement< POISSON_ELEMENT >::nhistory_values_for_projection(), oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::nhistory_values_for_projection(), oomph::ProjectableUnsteadyHeatMixedOrderSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::nhistory_values_for_projection(), oomph::ProjectableTimeHarmonicFourierDecomposedLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::nhistory_values_for_projection(), oomph::ProjectableTimeHarmonicLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::nhistory_values_for_projection(), oomph::ProjectableUnsteadyHeatElement< UNSTEADY_HEAT_ELEMENT >::nhistory_values_for_projection(), nodal_local_eqn(), nodal_position(), nodal_position_gen(), nodal_value(), oomph::NodeElementSolidOnlyMortaringElement::node_and_vector_to_data_pt(), node_update(), oomph::Mesh::node_update(), oomph::RefineableElement::nodes_built(), oomph::PRefineableElement::nodes_built(), oomph::SpectralPeriodicOrbitElement< NNODE_1D >::num_Z2_flux_terms(), OneDimMesh< ELEMENT >::OneDimMesh(), FiniteElementComp::operator()(), ElementCmp::operator()(), oomph::LinearElasticitySmoothMesh< LINEAR_ELASTICITY_ELEMENT >::operator()(), oomph::PoissonSmoothMesh< POISSON_ELEMENT >::operator()(), oomph::HermiteBeamElement::output(), oomph::DummyFaceElement< ELEMENT >::output(), oomph::UnsteadyHeatBaseFaceElement< ELEMENT >::output(), oomph::UnsteadyHeatFluxPseudoMeltElement< ELEMENT >::output(), oomph::AxisymmetricLinearElasticityTractionElement< ELEMENT >::output(), oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::output(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::output(), oomph::FSILinearisedAxisymPoroelasticTractionElement< POROELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >::output(), oomph::ClampedHermiteShellBoundaryConditionElement::output(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::output(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::output(), oomph::MyTaylorHoodElement< DIM >::output(), oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::output(), oomph::ProjectableUnsteadyHeatMixedOrderSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::output(), oomph::ProjectableUnsteadyHeatElement< UNSTEADY_HEAT_ELEMENT >::output(), oomph::SolarRadiationBase::output_atmospheric_radiation(), oomph::TriangleMesh< ELEMENT >::output_boundary_coordinates(), oomph::TriangleMesh< FLUID_ELEMENT >::output_boundary_coordinates(), oomph::ElementWithExternalElement::output_external_elements(), oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >::output_integration_points(), oomph::SurfaceMeltElement< ELEMENT >::output_melt(), output_paraview(), oomph::StefanBoltzmannUnsteadyHeatFluxElement< ELEMENT >::output_stefan_boltzmann_radiation(), oomph::TreeBasedRefineableMeshBase::p_adapt_mesh(), oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::p_refine(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::p_refine(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::p_refine(), oomph::Tree::p_refine_if_required(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::pin_all(), oomph::AxisymmetricTTaylorHoodElement::pin_all_nodal_pressure_dofs(), oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::pin_all_nodal_pressure_dofs(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::pin_all_non_pressure_dofs(), oomph::NavierStokesEquations< DIM >::pin_all_non_pressure_dofs(), oomph::SpaceTimeNavierStokesEquations< DIM >::pin_all_non_pressure_dofs(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::pin_all_non_pressure_dofs(), oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::pin_elemental_redundant_nodal_pressure_dofs(), oomph::RefineableAxisymmetricQTaylorHoodElement::pin_elemental_redundant_nodal_pressure_dofs(), oomph::RefineableGeneralisedNewtonianAxisymmetricQTaylorHoodElement::pin_elemental_redundant_nodal_pressure_dofs(), oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::pin_elemental_redundant_nodal_pressure_dofs(), oomph::RefineableLinearisedQTaylorHoodElement::pin_elemental_redundant_nodal_pressure_dofs(), oomph::RefineableQTaylorHoodElement< DIM >::pin_elemental_redundant_nodal_pressure_dofs(), oomph::RefineablePolarTaylorHoodElement::pin_elemental_redundant_nodal_pressure_dofs(), oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::pin_elemental_redundant_nodal_pressure_dofs(), oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >::pin_elemental_redundant_nodal_pressure_dofs(), oomph::RefineableQSphericalTaylorHoodElement::pin_elemental_redundant_nodal_pressure_dofs(), oomph::RefineableQPVDElementWithContinuousPressure< DIM >::pin_elemental_redundant_nodal_solid_pressures(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::pin_q_edge_value(), oomph::LinearisedQCrouzeixRaviartElement::pin_real_or_imag(), oomph::ProjectableDarcyElement< DARCY_ELEMENT >::pin_superfluous_darcy_dofs(), oomph::MGSolver< DIM >::plot(), oomph::UnsteadyHeatFluxPseudoMeltElement< ELEMENT >::plot_residual_landscape(), oomph::PMLQuadMeshBase< ELEMENT >::pml_locate_zeta(), oomph::PMLHelmholtzFluxElement< ELEMENT >::PMLHelmholtzFluxElement(), oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::PMLHelmholtzFluxFromNormalDisplacementBCElement(), oomph::PMLHelmholtzPowerElement< ELEMENT >::PMLHelmholtzPowerElement(), oomph::PoissonFluxElement< ELEMENT >::PoissonFluxElement(), oomph::PolarNavierStokesTractionElement< ELEMENT >::PolarNavierStokesTractionElement(), oomph::PolarStreamfunctionTractionElement< ELEMENT >::PolarStreamfunctionTractionElement(), oomph::PolarStressIntegralElement< ELEMENT >::PolarStressIntegralElement(), oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >::position(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::pre_build(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::pre_build(), oomph::StorableShapeSolidElementBase::pre_compute_d2shape_lagrangian_at_knots(), oomph::StorableShapeSolidElementBase::pre_compute_dshape_lagrangian_at_knots(), oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::pressure_node_pt(), oomph::RefineableAxisymmetricQTaylorHoodElement::pressure_node_pt(), oomph::RefineableGeneralisedNewtonianAxisymmetricQTaylorHoodElement::pressure_node_pt(), oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::pressure_node_pt(), oomph::RefineableLinearisedQTaylorHoodElement::pressure_node_pt(), oomph::RefineableQTaylorHoodElement< DIM >::pressure_node_pt(), oomph::PolarTaylorHoodElement::pressure_node_pt(), oomph::RefineablePolarTaylorHoodElement::pressure_node_pt(), oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::pressure_node_pt(), oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >::pressure_node_pt(), oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >::pressure_node_pt(), oomph::RefineableQSphericalTaylorHoodElement::pressure_node_pt(), PressureWaveFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::PressureWaveFSIProblem(), print_connectivity_matrix(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::project(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_edge_data_pt(), oomph::TRaviartThomasDarcyElement< ORDER >::q_edge_data_pt(), oomph::QuarterCircleSectorMesh< ELEMENT >::QuarterCircleSectorMesh(), oomph::QuarterTubeMesh< ELEMENT >::QuarterTubeMesh(), raw_dnodal_position_dt(), raw_dnodal_position_gen_dt(), oomph::SolidFiniteElement::raw_lagrangian_position(), oomph::SolidFiniteElement::raw_lagrangian_position_gen(), raw_nodal_position(), raw_nodal_position_gen(), raw_nodal_value(), oomph::MacroElementNodeUpdateElement< ELEMENT >::rebuild_from_sons(), oomph::RectangleWithHoleMesh< ELEMENT >::RectangleWithHoleMesh(), oomph::TreeBasedRefineableMeshBase::refine_as_in_reference_mesh(), CollapsibleChannelProblem< ELEMENT >::refine_elements_based_on_x_coord(), oomph::RefineableImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::RefineableFSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), oomph::RefineableNavierStokesFluxControlElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction(), RefineableUnsteadyHeatProblem< ELEMENT >::RefineableUnsteadyHeatProblem(), oomph::FaceElement::resize_nodes(), oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::scalar_value_paraview(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::scale_basis(), oomph::TRaviartThomasDarcyElement< ORDER >::scale_basis(), oomph::TPoroelasticityElement< ORDER >::scale_basis(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::set_boundary_conditions(), HeatedCircularPenetratorElement::set_contact_element_mesh_pt(), CircularPenetratorElement::set_contact_element_mesh_pt(), oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::set_external_data_from_navier_stokes_outflow_mesh(), AdvectionProblem::set_initial_conditions(), EulerProblem::set_initial_conditions(), oomph::SurfaceMeltElement< ELEMENT >::set_lagrange_multiplier_pressure_to_zero(), oomph::MacroElementNodeUpdateElement< ELEMENT >::set_node_update_info(), oomph::SurfaceContactElementBase< ELEMENT >::set_penetrator_pt(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::set_q_edge(), oomph::TRaviartThomasDarcyElement< ORDER >::set_q_edge(), oomph::MGSolver< DIM >::set_self_test_vector(), oomph::QPVDElementWithContinuousPressure< DIM >::set_solid_p(), oomph::TPVDElementWithContinuousPressure< DIM >::set_solid_p(), oomph::VolumeConstraintBoundingElement::set_volume_constraint_element(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::setup_algebraic_node_update(), oomph::AlgebraicFishMesh< ELEMENT >::setup_algebraic_node_update(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::setup_algebraic_node_update(), oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::setup_algebraic_node_update(), oomph::AlgebraicElementBase::setup_algebraic_node_update(), oomph::XdaTetMesh< ELEMENT >::setup_boundary_coordinates(), oomph::UnstructuredTwoDMeshGeometryBase::setup_boundary_coordinates(), oomph::BrickMeshBase::setup_boundary_element_info(), oomph::LineMeshBase::setup_boundary_element_info(), oomph::QuadMeshBase::setup_boundary_element_info(), oomph::TetMeshBase::setup_boundary_element_info(), oomph::TriangleMeshBase::setup_boundary_element_info(), oomph::HermiteQuadMesh< ELEMENT >::setup_boundary_element_info(), oomph::FluidInterfaceAdditionalValues< SolubleSurfactantTransportInterfaceElement >::setup_equation_indices(), oomph::FluidInterfaceAdditionalValues< SurfactantTransportInterfaceElement >::setup_equation_indices(), oomph::FourierDecomposedHelmholtzDtNMesh< ELEMENT >::setup_gamma(), oomph::HelmholtzDtNMesh< ELEMENT >::setup_gamma(), oomph::MGSolver< DIM >::setup_interpolation_matrices_unstructured(), oomph::HelmholtzMGPreconditioner< DIM >::setup_interpolation_matrices_unstructured(), oomph::Z2ErrorEstimator::setup_patches(), SolarRadiationProblem< ELEMENT >::setup_shielding_nodes(), oomph::SimpleRectangularTriMesh< ELEMENT >::SimpleRectangularTriMesh(), SimpleRefineableRectangularQuadMesh< ELEMENT >::SimpleRefineableRectangularQuadMesh(), oomph::TetMeshBase::snap_nodes_onto_geometric_objects(), oomph::TetMeshBase::snap_to_quadratic_surface(), oomph::RefineableQPVDElementWithContinuousPressure< DIM >::solid_pressure_node_pt(), solve_with_selected_refinement_pattern(), oomph::TetMeshBase::split_elements_in_corners(), oomph::Tree::split_if_required(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::square_of_l2_norm_of_error(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::strain_rate(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::SurfactantProblem(), oomph::TetgenScaffoldMesh::TetgenScaffoldMesh(), oomph::ThinLayerBrickOnTetMesh< ELEMENT >::ThinLayerBrickOnTetMesh(), ThreeDimBethertonProblem< ELEMENT >::ThreeDimBethertonProblem(), oomph::TemplateFreeContactElementBase::traction_fct(), TriangleFaceTestProblem< ELEMENT >::TriangleFaceTestProblem(), oomph::TriangleScaffoldMesh::TriangleScaffoldMesh(), oomph::TubeMesh< ELEMENT >::TubeMesh(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::TurekProblem(), TwoDDGMesh< ELEMENT >::TwoDDGMesh(), oomph::FluidInterfaceElement::u(), oomph::LinearisedAxisymmetricFluidInterfaceElement::u(), oomph::BiharmonicElement< DIM >::u(), oomph::YoungLaplaceContactAngleElement< ELEMENT >::u(), oomph::RefineableElement::unbuild(), oomph::AxisymmetricTTaylorHoodElement::unpin_all_nodal_pressure_dofs(), oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::unpin_all_nodal_pressure_dofs(), oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::unpin_elemental_pressure_dofs(), oomph::RefineableAxisymmetricQTaylorHoodElement::unpin_elemental_pressure_dofs(), oomph::RefineableGeneralisedNewtonianAxisymmetricQTaylorHoodElement::unpin_elemental_pressure_dofs(), oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::unpin_elemental_pressure_dofs(), oomph::RefineableLinearisedQTaylorHoodElement::unpin_elemental_pressure_dofs(), oomph::RefineableQTaylorHoodElement< DIM >::unpin_elemental_pressure_dofs(), oomph::RefineablePolarTaylorHoodElement::unpin_elemental_pressure_dofs(), oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::unpin_elemental_pressure_dofs(), oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >::unpin_elemental_pressure_dofs(), oomph::RefineableQSphericalTaylorHoodElement::unpin_elemental_pressure_dofs(), oomph::RefineableQPVDElementWithContinuousPressure< DIM >::unpin_elemental_solid_pressure_dofs(), oomph::QPVDElementWithContinuousPressure< DIM >::unpin_elemental_solid_pressure_dofs(), oomph::TPVDElementWithContinuousPressure< DIM >::unpin_elemental_solid_pressure_dofs(), oomph::AxisymmetricTTaylorHoodElement::unpin_proper_nodal_pressure_dofs(), oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::unpin_proper_nodal_pressure_dofs(), oomph::LinearisedQCrouzeixRaviartElement::unpin_real_or_imag(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::unpin_surface(), oomph::UnsteadyHeatBaseFaceElement< ELEMENT >::UnsteadyHeatBaseFaceElement(), oomph::UnsteadyHeatFluxElement< ELEMENT >::UnsteadyHeatFluxElement(), oomph::UnsteadyHeatFluxPseudoMeltElement< ELEMENT >::UnsteadyHeatFluxPseudoMeltElement(), oomph::RefineableTetgenMesh< ELEMENT >::update_faceted_surface_using_face_mesh(), oomph::SolarRadiationBase::update_limiting_angles(), oomph::AxisymFoepplvonKarmanEquations::use_linear_bending_model(), oomph::DisplacementBasedFoepplvonKarmanEquations::use_linear_bending_model(), oomph::FoepplvonKarmanEquations::use_linear_bending_model(), oomph::AxisymmetricTCrouzeixRaviartElement::vertex_node_pt(), oomph::AxisymmetricTTaylorHoodElement::vertex_node_pt(), oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::vertex_node_pt(), oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::vertex_node_pt(), oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >::vertex_node_pt(), oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >::vertex_node_pt(), oomph::TCrouzeixRaviartElement< DIM >::vertex_node_pt(), oomph::TTaylorHoodElement< DIM >::vertex_node_pt(), oomph::WomersleyMesh< WOMERSLEY_ELEMENT >::WomersleyMesh(), oomph::YoungLaplaceContactAngleElement< ELEMENT >::YoungLaplaceContactAngleElement(), oomph::FaceElement::zeta_nodal(), and oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::zeta_nodal().
node_pt() [2/2]
Node* const& oomph::FiniteElement::node_pt (const unsigned & n) const inline
Return a pointer to the local node n (const version)
     {
 #ifdef RANGE_CHECKING
       if (n >= Nnode)
       {
         std::ostringstream error_message;
         error_message << "Range Error: " << n << " is not in the range (0,"
                       << Nnode - 1 << ")";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       return Node_pt[n];
     }
References n, Nnode, Node_pt, OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
node_update()
void FiniteElement::node_update () virtual
Update the positions of all nodes in the element using each node update function. The default implementation may be overloaded so that more efficient versions can be written
Loop over all nodes in the element and update their positions using each node's (algebraic) update function
Reimplemented in SpineGravityTractionElement< ELEMENT >.
   {
     const unsigned n_node = nnode();
     for (unsigned n = 0; n < n_node; n++)
     {
       node_pt(n)->node_update();
     }
   }
References n, nnode(), node_pt(), and oomph::Node::node_update().
Referenced by oomph::ElementWithMovingNodes::fill_in_jacobian_from_geometric_data(), oomph::ElementWithMovingNodes::get_dnodal_coordinates_dgeom_dofs(), oomph::FSIWallElement::node_update_adjacent_fluid_elements(), oomph::ImmersedRigidBodyElement::node_update_adjacent_fluid_elements(), oomph::FluidInterfaceBoundingElement::reset_after_external_fd(), and oomph::FluidInterfaceBoundingElement::update_in_external_fd().
nplot_points()
virtual unsigned oomph::FiniteElement::nplot_points (const unsigned & nplot) const inline virtual
Return total number of plot points (when plotting nplot points in each "coordinate direction")
Reimplemented in oomph::TElement< 3, NNODE_1D >, oomph::TElement< 2, NNODE_1D >, oomph::TElement< 1, NNODE_1D >, oomph::QSpectralElement< 3, NNODE_1D >, oomph::QSpectralElement< 2, NNODE_1D >, oomph::QSpectralElement< 1, NNODE_1D >, oomph::QElement< 3, NNODE_1D >, oomph::QElement< 2, NNODE_1D >, oomph::QElement< 1, NNODE_1D >, oomph::QHermiteElement< DIM >, oomph::QHermiteElement< DIM - 1 >, oomph::QHermiteElement< DIM >, oomph::QHermiteElement< DIM - 1 >, oomph::QHermiteElement< DIM >, and oomph::QHermiteElement< DIM - 1 >.
     {
       throw OomphLibError(
         "nplot_points(...) is not implemented for this element",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
       // Dummy return
       return 0;
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by UnstructuredFluidProblem< ELEMENT >::doc_boundary_coordinates(), oomph::Mesh::doc_boundary_coordinates(), oomph::Z2ErrorEstimator::doc_flux(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solid_boundary_coordinates(), UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solid_boundary_coordinates(), oomph::PolarNavierStokesEquations::full_output(), oomph::SphericalNavierStokesEquations::full_output(), locate_zeta(), oomph::NonlinearSurfaceContactElement< ELEMENT >::output(), oomph::LinearSurfaceContactElement< ELEMENT >::output(), oomph::UnsteadyHeatFluxPseudoMeltElement< ELEMENT >::output(), oomph::PolarStreamfunctionEquations::output(), oomph::AxisymFoepplvonKarmanEquations::output(), oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >::output(), oomph::AxisymmetricLinearElasticityEquations::output(), oomph::AxisymmetricLinearElasticityTractionElement< ELEMENT >::output(), oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::output(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::output(), oomph::FluidInterfaceElement::output(), oomph::SurfactantTransportInterfaceElement::output(), oomph::DisplacementBasedFoepplvonKarmanEquations::output(), oomph::FoepplvonKarmanEquations::output(), oomph::FourierDecomposedHelmholtzEquations::output(), oomph::NavierStokesSurfaceDragTorqueElement< ELEMENT >::output(), oomph::PMLFourierDecomposedHelmholtzEquations::output(), oomph::SolidTractionElement< ELEMENT >::output(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::output(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::output(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::output(), oomph::YoungLaplaceEquations::output(), oomph::LinearisedAxisymmetricNavierStokesEquations::output(), oomph::THomogenisedLinearElasticityElement< DIM, NNODE_1D >::output(), oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::output(), oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >::output(), oomph::MyTaylorHoodElement< DIM >::output(), oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::output(), oomph::AxisymAdvectionDiffusionEquations::output(), oomph::AxisymmetricNavierStokesEquations::output(), oomph::AxisymmetricPoroelasticityEquations::output(), oomph::BiharmonicEquations< DIM >::output(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::output(), oomph::LinearisedNavierStokesEquations::output(), oomph::BuoyantQCrouzeixRaviartElement< DIM >::output(), oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::output(), oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::output(), oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::output(), oomph::PMLTimeHarmonicLinearElasticityTractionElement< ELEMENT >::output(), oomph::PoissonFluxElement< ELEMENT >::output(), oomph::PolarNavierStokesEquations::output(), oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::output(), oomph::ProjectableUnsteadyHeatMixedOrderSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::output(), oomph::SphericalAdvectionDiffusionEquations::output(), oomph::SphericalNavierStokesEquations::output(), oomph::SteadyAxisymAdvectionDiffusionEquations::output(), oomph::TimeHarmonicLinearElasticityTractionElement< ELEMENT >::output(), oomph::ProjectableUnsteadyHeatElement< UNSTEADY_HEAT_ELEMENT >::output(), oomph::AxisymFoepplvonKarmanEquations::output_fct(), oomph::DisplacementBasedFoepplvonKarmanEquations::output_fct(), oomph::FoepplvonKarmanEquations::output_fct(), oomph::FourierDecomposedHelmholtzEquations::output_fct(), oomph::PMLFourierDecomposedHelmholtzEquations::output_fct(), oomph::YoungLaplaceEquations::output_fct(), oomph::AxisymAdvectionDiffusionEquations::output_fct(), oomph::AxisymmetricLinearElasticityEquations::output_fct(), oomph::AxisymmetricNavierStokesEquations::output_fct(), oomph::AxisymmetricPoroelasticityEquations::output_fct(), oomph::BiharmonicEquations< DIM >::output_fct(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::output_fct(), oomph::PolarNavierStokesEquations::output_fct(), oomph::SphericalAdvectionDiffusionEquations::output_fct(), oomph::SphericalNavierStokesEquations::output_fct(), oomph::SteadyAxisymAdvectionDiffusionEquations::output_fct(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::output_fct(), oomph::BiharmonicEquations< DIM >::output_fluid_velocity(), oomph::FourierDecomposedHelmholtzEquations::output_real(), oomph::PMLFourierDecomposedHelmholtzEquations::output_real(), oomph::FourierDecomposedHelmholtzEquations::output_real_fct(), oomph::PMLFourierDecomposedHelmholtzEquations::output_real_fct(), oomph::LinearisedAxisymmetricNavierStokesEquations::output_veloc(), oomph::AxisymmetricNavierStokesEquations::output_veloc(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::output_veloc(), oomph::LinearisedNavierStokesEquations::output_veloc(), oomph::PolarNavierStokesEquations::output_veloc(), oomph::SphericalNavierStokesEquations::output_veloc(), oomph::SphericalNavierStokesEquations::output_vorticity(), oomph::FaceElement::output_zeta(), oomph::Multi_domain_functions::setup_bulk_elements_adjacent_to_face_mesh(), and TFaceTestProblem< ELEMENT >::TFaceTestProblem().
nplot_points_paraview()
virtual unsigned oomph::FiniteElement::nplot_points_paraview (const unsigned & nplot) const inline virtual
Return the number of actual plot points for paraview plot with parameter nplot. Broken virtual; can be overloaded in specific elements.
Reimplemented in oomph::TElement< 3, NNODE_1D >, oomph::TElement< 2, NNODE_1D >, oomph::TElement< 1, NNODE_1D >, oomph::QElement< 3, NNODE_1D >, oomph::QElement< 2, NNODE_1D >, and oomph::QElement< 1, NNODE_1D >.
     {
       throw OomphLibError(
         "This function hasn't been implemented for this element",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
       // Dummy unsigned
       return 0;
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::Mesh::output_fct_paraview(), output_paraview(), oomph::Mesh::output_paraview(), oomph::NavierStokesEquations< DIM >::scalar_value_fct_paraview(), oomph::SpaceTimeNavierStokesEquations< DIM >::scalar_value_fct_paraview(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::scalar_value_fct_paraview(), oomph::PMLHelmholtzEquations< DIM >::scalar_value_fct_paraview(), oomph::PoissonEquations< DIM >::scalar_value_fct_paraview(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::scalar_value_fct_paraview(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::scalar_value_fct_paraview(), oomph::MultiPoissonEquations< DIM, NFIELDS >::scalar_value_paraview(), oomph::AdvectionDiffusionEquations< DIM >::scalar_value_paraview(), oomph::AxisymAdvectionDiffusionEquations::scalar_value_paraview(), oomph::AxisymmetricNavierStokesEquations::scalar_value_paraview(), oomph::AxisymmetricPoroelasticityEquations::scalar_value_paraview(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::scalar_value_paraview(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::scalar_value_paraview(), oomph::HelmholtzEquations< DIM >::scalar_value_paraview(), oomph::NavierStokesEquations< DIM >::scalar_value_paraview(), oomph::PMLHelmholtzEquations< DIM >::scalar_value_paraview(), oomph::PoissonEquations< DIM >::scalar_value_paraview(), oomph::SpaceTimeNavierStokesEquations< DIM >::scalar_value_paraview(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::scalar_value_paraview(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::scalar_value_paraview(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::scalar_value_paraview(), and oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::scalar_value_paraview().
nscalar_paraview()
virtual unsigned oomph::FiniteElement::nscalar_paraview () const inline virtual
Number of scalars/fields output by this element. Broken virtual. Needs to be implemented for each new specific element type.
Reimplemented in oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< 2 >, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< 2 >, oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::PoissonEquations< DIM >, oomph::PoissonEquations< 1 >, oomph::PoissonEquations< 2 >, oomph::PoissonEquations< 3 >, oomph::PMLHelmholtzEquations< DIM >, oomph::NavierStokesEquations< DIM >, oomph::NavierStokesEquations< 2 >, oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >, oomph::BuoyantQCrouzeixRaviartElement< DIM >, oomph::HelmholtzEquations< DIM >, oomph::GeneralisedNewtonianNavierStokesEquations< DIM >, oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations, oomph::AxisymmetricPoroelasticityEquations, oomph::AxisymmetricNavierStokesEquations, oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >, oomph::AxisymAdvectionDiffusionEquations, oomph::AdvectionDiffusionEquations< DIM >, oomph::AdvectionDiffusionEquations< 2 >, oomph::AxisymmetricQAdvectionCrouzeixRaviartElement, oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement, oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement, RefineableBuoyantQCrouzeixRaviartElement< DIM >, oomph::MultiPoissonEquations< DIM, NFIELDS >, and oomph::TLinearHeatAndElasticityElement< DIM, NNODE_1D >.
     {
       throw OomphLibError(
         "This function hasn't been implemented for this element",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
       // Dummy unsigned
       return 0;
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::Mesh::output_fct_paraview(), and oomph::Mesh::output_paraview().
nsub_elements_paraview()
virtual unsigned oomph::FiniteElement::nsub_elements_paraview (const unsigned & nplot) const inline virtual
Return the number of local sub-elements for paraview plot with parameter nplot. Broken virtual; can be overloaded in specific elements.
Reimplemented in oomph::TElement< 3, NNODE_1D >, oomph::TElement< 2, NNODE_1D >, oomph::TElement< 1, NNODE_1D >, oomph::QElement< 3, NNODE_1D >, oomph::QElement< 2, NNODE_1D >, and oomph::QElement< 1, NNODE_1D >.
     {
       throw OomphLibError(
         "This function hasn't been implemented for this element",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
       // Dummy unsigned
       return 0;
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::Mesh::output_fct_paraview(), and oomph::Mesh::output_paraview().
nvertex_node()
virtual unsigned oomph::FiniteElement::nvertex_node () const inline virtual
Return the number of vertex nodes in this element. Broken virtual function in "pure" finite elements.
Reimplemented in oomph::BrickElementBase, oomph::QuadElementBase, oomph::LineElementBase, oomph::ElementWithZ2ErrorEstimator, oomph::RefineableQYoungLaplaceElement< NNODE_1D >, oomph::TUnsteadyHeatElement< DIM, NNODE_1D >, oomph::RefineableQUnsteadyHeatElement< DIM, NNODE_1D >, oomph::TTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::RefineableQTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::TTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >, oomph::RefineableQSphericalCrouzeixRaviartElement, oomph::RefineableQSphericalTaylorHoodElement, oomph::RefineableQSphericalAdvectionDiffusionElement< NNODE_1D >, oomph::RefineableQSphericalAdvectionDiffusionElement< 3 >, oomph::RefineableQUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, oomph::RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, oomph::RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::TPVDElementWithContinuousPressure< DIM >, oomph::TPVDBubbleEnrichedElement< DIM, NNODE_1D >, oomph::TPVDElement< DIM, NNODE_1D >, oomph::RefineableQPVDElementWithContinuousPressure< DIM >, oomph::RefineableQPVDElementWithPressure< DIM >, oomph::RefineableQPVDElement< DIM, NNODE_1D >, oomph::RefineablePolarCrouzeixRaviartElement, oomph::RefineablePolarTaylorHoodElement, oomph::TPoissonElement< DIM, NNODE_1D >, oomph::RefineableQSpectralPoissonElement< DIM, NNODE_1D >, oomph::PRefineableQPoissonElement< DIM >, oomph::RefineableQPoissonElement< DIM, NNODE_1D >, oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::TPMLHelmholtzElement< DIM, NNODE_1D >, oomph::RefineableQPMLHelmholtzElement< DIM, NNODE_1D >, oomph::RefineableQPMLHelmholtzElement< 2, NNODE_1D >, oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::TTaylorHoodElement< DIM >, oomph::TCrouzeixRaviartElement< DIM >, oomph::PRefineableQCrouzeixRaviartElement< DIM >, oomph::RefineableQCrouzeixRaviartElement< DIM >, oomph::RefineableQCrouzeixRaviartElement< 2 >, oomph::RefineableQTaylorHoodElement< DIM >, oomph::RefineableQTaylorHoodElement< 2 >, oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >, oomph::RefineableLinearisedQTaylorHoodElement, oomph::RefineableLinearisedQCrouzeixRaviartElement, oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement, oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement, oomph::RefineableQLinearWaveElement< DIM, NNODE_1D >, oomph::TLinearElasticityElement< DIM, NNODE_1D >, oomph::PRefineableQLinearElasticityElement< DIM >, oomph::RefineableQLinearElasticityElement< DIM, NNODE_1D >, oomph::THelmholtzElement< DIM, NNODE_1D >, oomph::RefineableQHelmholtzElement< DIM, NNODE_1D >, oomph::TElement< 3, NNODE_1D >, oomph::TElement< 2, NNODE_1D >, oomph::TElement< 1, NNODE_1D >, oomph::QSpectralElement< 3, NNODE_1D >, oomph::QSpectralElement< 2, NNODE_1D >, oomph::QSpectralElement< 1, NNODE_1D >, oomph::QElement< 3, NNODE_1D >, oomph::QElement< 2, NNODE_1D >, oomph::QElement< 1, NNODE_1D >, oomph::PseudoSolidNodeUpdateElement< TCrouzeixRaviartElement< 2 >, TPVDBubbleEnrichedElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< TTaylorHoodElement< 2 >, TPVDElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< GeneralisedNewtonianAxisymmetricTTaylorHoodElement, TPVDElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< AxisymmetricTTaylorHoodElement, TPVDElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< GeneralisedNewtonianTTaylorHoodElement< 2 >, TPVDElement< 2, 3 > >, oomph::SpectralPeriodicOrbitElement< NNODE_1D >, oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >, oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >, oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >, oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >, oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >, oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement, oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement, oomph::RefineableGeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement, oomph::RefineableGeneralisedNewtonianAxisymmetricQTaylorHoodElement, oomph::TFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::TFoepplvonKarmanElement< NNODE_1D >, oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >, oomph::TRaviartThomasDarcyElement< ORDER >, oomph::TAxisymmetricPoroelasticityElement< ORDER >, oomph::AxisymmetricTTaylorHoodElement, oomph::AxisymmetricTCrouzeixRaviartElement, oomph::RefineableAxisymmetricQCrouzeixRaviartElement, oomph::RefineableAxisymmetricQTaylorHoodElement, oomph::TAxisymmetricLinearElasticityElement< NNODE_1D >, oomph::RefineableQGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >, oomph::RefineableQAxisymAdvectionDiffusionElement< NNODE_1D >, oomph::RefineableQAxisymAdvectionDiffusionElement< 3 >, oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, oomph::RefineableQAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, oomph::RefineableQAdvectionDiffusionReactionElement< 2, DIM, 3 >, oomph::RefineableQSUPGAdvectionDiffusionElement< DIM, NNODE_1D >, oomph::RefineableQGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >, oomph::RefineableQAdvectionDiffusionElement< DIM, NNODE_1D >, oomph::RefineableQAdvectionDiffusionElement< DIM, 3 >, oomph::RefineablePolarStreamfunctionElement, ModalPRefineableQPoissonElement< DIM >, oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement, oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement, oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement, RefineableBuoyantQCrouzeixRaviartElement< DIM >, oomph::TLinearHeatAndElasticityElement< DIM, NNODE_1D >, oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement, and oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement.
     {
       std::string error_msg = "Not implemented for FiniteElement.";
       throw OomphLibError(
         error_msg, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
Referenced by oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::nvertex_node(), oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::nvertex_node(), oomph::RefineablePolarStreamfunctionElement::nvertex_node(), oomph::RefineableQAdvectionDiffusionElement< DIM, NNODE_1D >::nvertex_node(), oomph::RefineableQSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::nvertex_node(), oomph::RefineableQAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::nvertex_node(), oomph::RefineableAxisymmetricQTaylorHoodElement::nvertex_node(), oomph::RefineableAxisymmetricQCrouzeixRaviartElement::nvertex_node(), oomph::RefineableGeneralisedNewtonianAxisymmetricQTaylorHoodElement::nvertex_node(), oomph::RefineableGeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement::nvertex_node(), oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::nvertex_node(), oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::nvertex_node(), oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::nvertex_node(), oomph::RefineableQHelmholtzElement< DIM, NNODE_1D >::nvertex_node(), oomph::RefineableQLinearElasticityElement< DIM, NNODE_1D >::nvertex_node(), oomph::PRefineableQLinearElasticityElement< DIM >::nvertex_node(), oomph::RefineableQLinearWaveElement< DIM, NNODE_1D >::nvertex_node(), oomph::RefineableLinearisedQCrouzeixRaviartElement::nvertex_node(), oomph::RefineableLinearisedQTaylorHoodElement::nvertex_node(), oomph::RefineableQTaylorHoodElement< DIM >::nvertex_node(), oomph::RefineableQCrouzeixRaviartElement< DIM >::nvertex_node(), oomph::PRefineableQCrouzeixRaviartElement< DIM >::nvertex_node(), oomph::RefineableQPMLHelmholtzElement< DIM, NNODE_1D >::nvertex_node(), oomph::RefineableQPoissonElement< DIM, NNODE_1D >::nvertex_node(), oomph::PRefineableQPoissonElement< DIM >::nvertex_node(), oomph::RefineableQSpectralPoissonElement< DIM, NNODE_1D >::nvertex_node(), oomph::RefineablePolarTaylorHoodElement::nvertex_node(), oomph::RefineablePolarCrouzeixRaviartElement::nvertex_node(), oomph::RefineableQPVDElement< DIM, NNODE_1D >::nvertex_node(), oomph::RefineableQPVDElementWithPressure< DIM >::nvertex_node(), oomph::RefineableQPVDElementWithContinuousPressure< DIM >::nvertex_node(), oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::nvertex_node(), oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >::nvertex_node(), oomph::RefineableQSphericalTaylorHoodElement::nvertex_node(), oomph::RefineableQSphericalCrouzeixRaviartElement::nvertex_node(), and oomph::RefineableQUnsteadyHeatElement< DIM, NNODE_1D >::nvertex_node().
output() [1/5]
virtual void oomph::FiniteElement::output (const unsigned & t, std::ostream & outfile, const unsigned & n_plot) const inline virtual
Output the element data at time step t. This is const because it is newly added and so can be done easily. Really all the output(...) functions should be const!
Reimplemented in oomph::HermiteBeamElement.
     {
       throw OomphLibError(
         "Output function function hasn't been implemented for this element",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
output() [2/5]
virtual void oomph::FiniteElement::output (FILE * file_pt) inline virtual
Output the element data — typically the values at the nodes in a format suitable for post-processing. (C style output)
Reimplemented in oomph::YoungLaplaceContactAngleElement< ELEMENT >, oomph::QWomersleyElement< DIM, NNODE_1D >, oomph::WomersleyEquations< DIM >, oomph::TWomersleyElement< DIM, NNODE_1D >, oomph::UnsteadyHeatFluxElement< ELEMENT >, oomph::QUnsteadyHeatElement< DIM, NNODE_1D >, oomph::QUnsteadyHeatElement< DIM, 3 >, oomph::UnsteadyHeatEquations< DIM >, oomph::UnsteadyHeatEquations< 2 >, oomph::TUnsteadyHeatElement< DIM, NNODE_1D >, oomph::TTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::TimeHarmonicLinearElasticityTractionElement< ELEMENT >, oomph::QTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::TimeHarmonicLinearElasticityEquations< DIM >, oomph::TimeHarmonicFourierDecomposedLinearElasticityTractionElement< ELEMENT >, oomph::TTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >, oomph::QTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >, oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations, oomph::QSteadyAxisymAdvectionDiffusionElement< NNODE_1D >, oomph::SteadyAxisymAdvectionDiffusionEquations, oomph::QSphericalTaylorHoodElement, oomph::QSphericalCrouzeixRaviartElement, oomph::SphericalNavierStokesEquations, oomph::QSphericalAdvectionDiffusionElement< NNODE_1D >, oomph::SphericalAdvectionDiffusionEquations, oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >, oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< 2 >, oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< 2 >, oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >, oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >, oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >, oomph::QTaylorHoodSpaceTimeElement< DIM >, oomph::QTaylorHoodSpaceTimeElement< 2 >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::QTaylorHoodSpaceTimeElement< DIM >, oomph::QTaylorHoodSpaceTimeElement< 2 >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::QTaylorHoodSpaceTimeElement< DIM >, oomph::QTaylorHoodSpaceTimeElement< 2 >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::SolidTractionElement< ELEMENT >, oomph::TPVDElementWithContinuousPressure< DIM >, oomph::TPVDBubbleEnrichedElement< DIM, NNODE_1D >, oomph::TPVDElement< DIM, NNODE_1D >, oomph::QPVDElementWithContinuousPressure< DIM >, oomph::QPVDElementWithPressure< DIM >, oomph::PVDEquationsWithPressure< DIM >, oomph::HermitePVDElement< DIM >, oomph::QPVDElement< DIM, NNODE_1D >, oomph::QPVDElement< DIM, 3 >, oomph::PVDEquations< DIM >, oomph::ClampedHermiteShellBoundaryConditionElement, oomph::HermiteShellElement, oomph::KirchhoffLoveShellEquations, oomph::PoroelasticityFaceElement< ELEMENT >, oomph::PolarTaylorHoodElement, oomph::PolarCrouzeixRaviartElement, oomph::PolarNavierStokesEquations, oomph::TPoissonElement< DIM, NNODE_1D >, oomph::QSpectralPoissonElement< DIM, NNODE_1D >, oomph::PoissonFluxElement< ELEMENT >, oomph::QPoissonElement< DIM, NNODE_1D >, oomph::QPoissonElement< DIM, 2 >, oomph::PoissonEquations< DIM >, oomph::PoissonEquations< 1 >, oomph::PoissonEquations< 2 >, oomph::PoissonEquations< 3 >, oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::PMLTimeHarmonicLinearElasticityTractionElement< ELEMENT >, oomph::QPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::QPMLTimeHarmonicLinearElasticityElement< 2, NNODE_1D >, oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >, oomph::TPMLHelmholtzElement< DIM, NNODE_1D >, oomph::PMLHelmholtzFluxElement< ELEMENT >, oomph::QPMLHelmholtzElement< DIM, NNODE_1D >, oomph::QPMLHelmholtzElement< 2, NNODE_1D >, oomph::PMLHelmholtzEquations< DIM >, oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >, oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >, oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::PMLFourierDecomposedHelmholtzEquations, oomph::TTaylorHoodElement< DIM >, oomph::TCrouzeixRaviartElement< DIM >, oomph::QTaylorHoodElement< DIM >, oomph::QTaylorHoodElement< 2 >, oomph::QCrouzeixRaviartElement< DIM >, oomph::NavierStokesEquations< DIM >, oomph::NavierStokesEquations< 2 >, oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >, oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >, oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >, oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >, oomph::HelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >, oomph::TimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >, oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >, oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >, oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >, oomph::BuoyantQCrouzeixRaviartElement< DIM >, oomph::LinearisedQTaylorHoodElement, oomph::LinearisedQCrouzeixRaviartElement, oomph::LinearisedNavierStokesEquations, oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::LinearisedAxisymmetricNavierStokesEquations, oomph::LinearWaveFluxElement< ELEMENT >, oomph::QLinearWaveElement< DIM, NNODE_1D >, oomph::LinearWaveEquations< DIM >, oomph::TLinearElasticityElement< DIM, NNODE_1D >, oomph::LinearElasticityTractionElement< ELEMENT >, oomph::QLinearElasticityElement< DIM, NNODE_1D >, oomph::QLinearElasticityElement< DIM, 2 >, oomph::QLinearElasticityElement< DIM, 3 >, oomph::LinearElasticityEquations< DIM >, oomph::THelmholtzElement< DIM, NNODE_1D >, oomph::HelmholtzFluxElement< ELEMENT >, oomph::QHelmholtzElement< DIM, NNODE_1D >, oomph::HelmholtzEquations< DIM >, oomph::HelmholtzBCElementBase< ELEMENT >, oomph::TElement< 3, NNODE_1D >, oomph::TElement< 2, NNODE_1D >, oomph::TElement< 1, NNODE_1D >, oomph::QSpectralElement< 3, NNODE_1D >, oomph::QSpectralElement< 2, NNODE_1D >, oomph::QSpectralElement< 1, NNODE_1D >, oomph::SolidQElement< 3, NNODE_1D >, oomph::SolidQElement< 2, NNODE_1D >, oomph::SolidQElement< 1, NNODE_1D >, oomph::QElement< 3, NNODE_1D >, oomph::QElement< 2, NNODE_1D >, oomph::QElement< 1, NNODE_1D >, oomph::PseudoSolidNodeUpdateElement< TCrouzeixRaviartElement< 2 >, TPVDBubbleEnrichedElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< TTaylorHoodElement< 2 >, TPVDElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< GeneralisedNewtonianAxisymmetricTTaylorHoodElement, TPVDElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< AxisymmetricTTaylorHoodElement, TPVDElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< GeneralisedNewtonianTTaylorHoodElement< 2 >, TPVDElement< 2, 3 > >, oomph::SpectralPeriodicOrbitElement< NNODE_1D >, oomph::SolidQHermiteElement< DIM >, oomph::SolidQHermiteElement< 1 >, oomph::SolidQHermiteElement< 2 >, oomph::QHermiteElement< DIM >, oomph::QHermiteElement< DIM - 1 >, oomph::QHermiteElement< DIM >, oomph::QHermiteElement< DIM - 1 >, oomph::QHermiteElement< DIM >, oomph::QHermiteElement< DIM - 1 >, oomph::DummyFaceElement< ELEMENT >, oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >, oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >, oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >, oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >, oomph::GeneralisedNewtonianNavierStokesEquations< DIM >, oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement, oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement, oomph::GeneralisedNewtonianAxisymmetricQTaylorHoodElement, oomph::GeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement, oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations, oomph::TFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >, oomph::QFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::FourierDecomposedHelmholtzEquations, oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >, oomph::TFoepplvonKarmanElement< NNODE_1D >, oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >, oomph::QFoepplvonKarmanElement< NNODE_1D >, oomph::FoepplvonKarmanEquations, oomph::DisplacementBasedFoepplvonKarmanEquations, oomph::SurfactantTransportInterfaceElement, oomph::ElasticLineFluidInterfaceBoundingElement< ELEMENT >, oomph::ElasticPointFluidInterfaceBoundingElement< ELEMENT >, oomph::ElasticUpdateFluidInterfaceElement< FluidInterfaceElement, SurfaceDerivatives, ELEMENT >, oomph::ElasticUpdateFluidInterfaceElement< SurfactantTransportInterfaceElement, AxisymmetricDerivatives, ELEMENT >, oomph::ElasticUpdateFluidInterfaceElement< FluidInterfaceElement, AxisymmetricDerivatives, ELEMENT >, oomph::ElasticUpdateFluidInterfaceElement< SolubleSurfactantTransportInterfaceElement, LineDerivatives, ELEMENT >, oomph::ElasticUpdateFluidInterfaceElement< FluidInterfaceElement, LineDerivatives, ELEMENT >, oomph::SpineLineFluidInterfaceBoundingElement< ELEMENT >, oomph::SpinePointFluidInterfaceBoundingElement< ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< EQUATION_CLASS, DERIVATIVE_CLASS, ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< SurfactantTransportInterfaceElement, LineDerivatives, ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< FluidInterfaceElement, SurfaceDerivatives, ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< SurfactantTransportInterfaceElement, AxisymmetricDerivatives, ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< SurfactantTransportInterfaceElement, SurfaceDerivatives, ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< FluidInterfaceElement, AxisymmetricDerivatives, ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< SolubleSurfactantTransportInterfaceElement, LineDerivatives, ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< FluidInterfaceElement, LineDerivatives, ELEMENT >, oomph::FluidInterfaceElement, oomph::FluidInterfaceBoundingElement, oomph::DarcyFaceElement< ELEMENT >, oomph::BiharmonicFluidBoundaryElement, oomph::BiharmonicFluxElement< DIM >, oomph::BiharmonicElement< DIM >, oomph::BiharmonicEquations< DIM >, oomph::ClampedSlidingHermiteBeamBoundaryConditionElement, oomph::HermiteBeamElement, oomph::AxisymmetricSolidTractionElement< ELEMENT >, oomph::AxisymQPVDElementWithPressure, oomph::AxisymmetricPVDEquationsWithPressure, oomph::AxisymDiagHermitePVDElement, oomph::AxisymQPVDElement, oomph::AxisymmetricPVDEquations, oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >, oomph::AxisymmetricPoroelasticityTractionElement< POROELASTICITY_BULK_ELEMENT >, oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >, oomph::AxisymmetricTTaylorHoodElement, oomph::AxisymmetricTCrouzeixRaviartElement, oomph::AxisymmetricQTaylorHoodElement, oomph::AxisymmetricQCrouzeixRaviartElement, oomph::AxisymmetricNavierStokesEquations, oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >, oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >, oomph::TAxisymmetricLinearElasticityElement< NNODE_1D >, oomph::FSIAxisymmetricLinearElasticityTractionElement< ELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >, oomph::AxisymmetricLinearElasticityTractionElement< ELEMENT >, oomph::QAxisymmetricLinearElasticityElement< NNODE_1D >, oomph::AxisymmetricLinearElasticityEquations, oomph::AxisymFoepplvonKarmanElement< NNODE_1D >, oomph::AxisymFoepplvonKarmanEquations, oomph::AxisymFoepplvonKarmanElement< NNODE_1D >, oomph::AxisymFoepplvonKarmanEquations, oomph::QAxisymAdvectionDiffusionElement< NNODE_1D >, oomph::QAxisymAdvectionDiffusionElement< 3 >, oomph::AxisymAdvectionDiffusionEquations, oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, oomph::QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, oomph::QAdvectionDiffusionReactionElement< 2, DIM, 3 >, oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >, oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >, oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >, oomph::GeneralisedAdvectionDiffusionEquations< DIM >, oomph::GeneralisedAdvectionDiffusionEquations< 2 >, oomph::QAdvectionDiffusionElement< DIM, NNODE_1D >, oomph::QAdvectionDiffusionElement< DIM, 3 >, oomph::AdvectionDiffusionEquations< DIM >, oomph::AdvectionDiffusionEquations< 2 >, oomph::PolarStreamfunctionElement, oomph::PolarStreamfunctionEquations, oomph::SolubleSurfactantTransportInterfaceElement, oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, QThermalPVDElement< DIM >, oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::AxisymmetricQAdvectionCrouzeixRaviartElement, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, QAxisymAdvectionDiffusionElementWithExternalElement, RefineableQAxisymAdvectionDiffusionBoussinesqElement, oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement, QAxisymAdvectionDiffusionElementWithExternalElement, RefineableQAxisymAdvectionDiffusionBoussinesqElement, oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement, RefineableQAdvectionDiffusionElementWithExternalElement< DIM >, RefineableQCrouzeixRaviartElementWithExternalElement< DIM >, RefineableBuoyantQCrouzeixRaviartElement< DIM >, oomph::PerturbedSpineLinearisedAxisymmetricFluidInterfaceElement< ELEMENT >, oomph::LinearisedAxisymmetricFluidInterfaceElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::LinearisedAxisymmetricNavierStokesEquations, oomph::QMultiPoissonElement< DIM, NNODE_1D, NFIELDS >, oomph::MultiPoissonEquations< DIM, NFIELDS >, oomph::THomogenisedLinearElasticityElement< DIM, NNODE_1D >, oomph::HomogenisedLinearElasticityEquations< DIM >, oomph::UnsteadyHeatFluxPseudoMeltElement< ELEMENT >, oomph::HeatedPenetratorFluxElement< ELEMENT >, oomph::TLinearHeatAndElasticityElement< DIM, NNODE_1D >, oomph::UnsteadyHeatBaseFaceElement< ELEMENT >, oomph::SurfaceContactElementBase< ELEMENT >, oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, and oomph::LinearisedAxisymmetricNavierStokesEquations.
     {
       throw OomphLibError("C-style otput function function hasn't been "
                           "implemented for this element",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
output() [3/5]
virtual void oomph::FiniteElement::output (FILE * file_pt, const unsigned & n_plot) inline virtual
Output the element data — pass (some measure of) the number of plot points per element (C style output)
Reimplemented in oomph::QSphericalTaylorHoodElement, oomph::QSphericalCrouzeixRaviartElement, oomph::SphericalNavierStokesEquations, oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< 2 >, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< 2 >, oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >, oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >, oomph::QTaylorHoodSpaceTimeElement< DIM >, oomph::QTaylorHoodSpaceTimeElement< 2 >, oomph::QTaylorHoodSpaceTimeElement< DIM >, oomph::QTaylorHoodSpaceTimeElement< 2 >, oomph::QTaylorHoodSpaceTimeElement< DIM >, oomph::QTaylorHoodSpaceTimeElement< 2 >, oomph::PolarTaylorHoodElement, oomph::PolarCrouzeixRaviartElement, oomph::PolarNavierStokesEquations, oomph::QTaylorHoodElement< DIM >, oomph::QTaylorHoodElement< 2 >, oomph::QCrouzeixRaviartElement< DIM >, oomph::NavierStokesEquations< DIM >, oomph::NavierStokesEquations< 2 >, oomph::LinearisedNavierStokesEquations, oomph::LinearisedAxisymmetricNavierStokesEquations, oomph::LinearWaveEquations< DIM >, oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >, oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >, oomph::GeneralisedNewtonianNavierStokesEquations< DIM >, oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations, oomph::AxisymmetricNavierStokesEquations, oomph::LinearisedAxisymmetricNavierStokesEquations, oomph::LinearisedAxisymmetricNavierStokesEquations, oomph::YoungLaplaceContactAngleElement< ELEMENT >, oomph::QWomersleyElement< DIM, NNODE_1D >, oomph::WomersleyEquations< DIM >, oomph::TWomersleyElement< DIM, NNODE_1D >, oomph::UnsteadyHeatFluxElement< ELEMENT >, oomph::QUnsteadyHeatElement< DIM, NNODE_1D >, oomph::QUnsteadyHeatElement< DIM, 3 >, oomph::UnsteadyHeatEquations< DIM >, oomph::UnsteadyHeatEquations< 2 >, oomph::TUnsteadyHeatElement< DIM, NNODE_1D >, oomph::TTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::TimeHarmonicLinearElasticityTractionElement< ELEMENT >, oomph::QTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::TimeHarmonicLinearElasticityEquations< DIM >, oomph::TimeHarmonicFourierDecomposedLinearElasticityTractionElement< ELEMENT >, oomph::TTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >, oomph::QTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >, oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations, oomph::QSteadyAxisymAdvectionDiffusionElement< NNODE_1D >, oomph::SteadyAxisymAdvectionDiffusionEquations, oomph::QSphericalAdvectionDiffusionElement< NNODE_1D >, oomph::SphericalAdvectionDiffusionEquations, oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::SolidTractionElement< ELEMENT >, oomph::TPVDElementWithContinuousPressure< DIM >, oomph::TPVDBubbleEnrichedElement< DIM, NNODE_1D >, oomph::TPVDElement< DIM, NNODE_1D >, oomph::QPVDElementWithContinuousPressure< DIM >, oomph::QPVDElementWithPressure< DIM >, oomph::PVDEquationsWithPressure< DIM >, oomph::HermitePVDElement< DIM >, oomph::QPVDElement< DIM, NNODE_1D >, oomph::QPVDElement< DIM, 3 >, oomph::PVDEquations< DIM >, oomph::ClampedHermiteShellBoundaryConditionElement, oomph::HermiteShellElement, oomph::KirchhoffLoveShellEquations, oomph::PoroelasticityFaceElement< ELEMENT >, oomph::TPoissonElement< DIM, NNODE_1D >, oomph::QSpectralPoissonElement< DIM, NNODE_1D >, oomph::PoissonFluxElement< ELEMENT >, oomph::QPoissonElement< DIM, NNODE_1D >, oomph::QPoissonElement< DIM, 2 >, oomph::PoissonEquations< DIM >, oomph::PoissonEquations< 1 >, oomph::PoissonEquations< 2 >, oomph::PoissonEquations< 3 >, oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::PMLTimeHarmonicLinearElasticityTractionElement< ELEMENT >, oomph::QPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::QPMLTimeHarmonicLinearElasticityElement< 2, NNODE_1D >, oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >, oomph::TPMLHelmholtzElement< DIM, NNODE_1D >, oomph::PMLHelmholtzFluxElement< ELEMENT >, oomph::QPMLHelmholtzElement< DIM, NNODE_1D >, oomph::QPMLHelmholtzElement< 2, NNODE_1D >, oomph::PMLHelmholtzEquations< DIM >, oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >, oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >, oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::PMLFourierDecomposedHelmholtzEquations, oomph::TTaylorHoodElement< DIM >, oomph::TCrouzeixRaviartElement< DIM >, oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >, oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >, oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >, oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >, oomph::HelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >, oomph::TimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >, oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >, oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >, oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >, oomph::BuoyantQCrouzeixRaviartElement< DIM >, oomph::LinearisedQTaylorHoodElement, oomph::LinearisedQCrouzeixRaviartElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::LinearWaveFluxElement< ELEMENT >, oomph::QLinearWaveElement< DIM, NNODE_1D >, oomph::TLinearElasticityElement< DIM, NNODE_1D >, oomph::LinearElasticityTractionElement< ELEMENT >, oomph::QLinearElasticityElement< DIM, NNODE_1D >, oomph::QLinearElasticityElement< DIM, 2 >, oomph::QLinearElasticityElement< DIM, 3 >, oomph::LinearElasticityEquations< DIM >, oomph::THelmholtzElement< DIM, NNODE_1D >, oomph::HelmholtzFluxElement< ELEMENT >, oomph::QHelmholtzElement< DIM, NNODE_1D >, oomph::HelmholtzEquations< DIM >, oomph::HelmholtzBCElementBase< ELEMENT >, oomph::TElement< 3, NNODE_1D >, oomph::TElement< 2, NNODE_1D >, oomph::TElement< 1, NNODE_1D >, oomph::QSpectralElement< 3, NNODE_1D >, oomph::QSpectralElement< 2, NNODE_1D >, oomph::QSpectralElement< 1, NNODE_1D >, oomph::SolidQElement< 3, NNODE_1D >, oomph::SolidQElement< 2, NNODE_1D >, oomph::SolidQElement< 1, NNODE_1D >, oomph::QElement< 3, NNODE_1D >, oomph::QElement< 2, NNODE_1D >, oomph::QElement< 1, NNODE_1D >, oomph::SpectralPeriodicOrbitElement< NNODE_1D >, oomph::SolidQHermiteElement< DIM >, oomph::SolidQHermiteElement< 1 >, oomph::SolidQHermiteElement< 2 >, oomph::QHermiteElement< DIM >, oomph::QHermiteElement< DIM - 1 >, oomph::SolidQHermiteElement< DIM >, oomph::SolidQHermiteElement< 1 >, oomph::SolidQHermiteElement< 2 >, oomph::SolidQHermiteElement< DIM >, oomph::SolidQHermiteElement< 1 >, oomph::SolidQHermiteElement< 2 >, oomph::QHermiteElement< DIM >, oomph::QHermiteElement< DIM - 1 >, oomph::QHermiteElement< DIM >, oomph::QHermiteElement< DIM - 1 >, oomph::DummyFaceElement< ELEMENT >, oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >, oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >, oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement, oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement, oomph::GeneralisedNewtonianAxisymmetricQTaylorHoodElement, oomph::GeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement, oomph::TFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >, oomph::QFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::FourierDecomposedHelmholtzEquations, oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >, oomph::TFoepplvonKarmanElement< NNODE_1D >, oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >, oomph::QFoepplvonKarmanElement< NNODE_1D >, oomph::FoepplvonKarmanEquations, oomph::DisplacementBasedFoepplvonKarmanEquations, oomph::SurfactantTransportInterfaceElement, oomph::ElasticLineFluidInterfaceBoundingElement< ELEMENT >, oomph::ElasticPointFluidInterfaceBoundingElement< ELEMENT >, oomph::ElasticUpdateFluidInterfaceElement< FluidInterfaceElement, SurfaceDerivatives, ELEMENT >, oomph::ElasticUpdateFluidInterfaceElement< SurfactantTransportInterfaceElement, AxisymmetricDerivatives, ELEMENT >, oomph::ElasticUpdateFluidInterfaceElement< FluidInterfaceElement, AxisymmetricDerivatives, ELEMENT >, oomph::ElasticUpdateFluidInterfaceElement< SolubleSurfactantTransportInterfaceElement, LineDerivatives, ELEMENT >, oomph::ElasticUpdateFluidInterfaceElement< FluidInterfaceElement, LineDerivatives, ELEMENT >, oomph::SpineLineFluidInterfaceBoundingElement< ELEMENT >, oomph::SpinePointFluidInterfaceBoundingElement< ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< EQUATION_CLASS, DERIVATIVE_CLASS, ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< SurfactantTransportInterfaceElement, LineDerivatives, ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< FluidInterfaceElement, SurfaceDerivatives, ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< SurfactantTransportInterfaceElement, AxisymmetricDerivatives, ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< SurfactantTransportInterfaceElement, SurfaceDerivatives, ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< FluidInterfaceElement, AxisymmetricDerivatives, ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< SolubleSurfactantTransportInterfaceElement, LineDerivatives, ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< FluidInterfaceElement, LineDerivatives, ELEMENT >, oomph::FluidInterfaceElement, oomph::FluidInterfaceBoundingElement, oomph::DarcyFaceElement< ELEMENT >, oomph::BiharmonicFluidBoundaryElement, oomph::BiharmonicFluxElement< DIM >, oomph::BiharmonicElement< DIM >, oomph::BiharmonicEquations< DIM >, oomph::ClampedSlidingHermiteBeamBoundaryConditionElement, oomph::HermiteBeamElement, oomph::AxisymmetricSolidTractionElement< ELEMENT >, oomph::AxisymQPVDElementWithPressure, oomph::AxisymmetricPVDEquationsWithPressure, oomph::AxisymDiagHermitePVDElement, oomph::AxisymQPVDElement, oomph::AxisymmetricPVDEquations, oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >, oomph::AxisymmetricPoroelasticityTractionElement< POROELASTICITY_BULK_ELEMENT >, oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >, oomph::AxisymmetricTTaylorHoodElement, oomph::AxisymmetricTCrouzeixRaviartElement, oomph::AxisymmetricQTaylorHoodElement, oomph::AxisymmetricQCrouzeixRaviartElement, oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >, oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >, oomph::TAxisymmetricLinearElasticityElement< NNODE_1D >, oomph::FSIAxisymmetricLinearElasticityTractionElement< ELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >, oomph::AxisymmetricLinearElasticityTractionElement< ELEMENT >, oomph::QAxisymmetricLinearElasticityElement< NNODE_1D >, oomph::AxisymmetricLinearElasticityEquations, oomph::AxisymFoepplvonKarmanElement< NNODE_1D >, oomph::AxisymFoepplvonKarmanEquations, oomph::AxisymFoepplvonKarmanElement< NNODE_1D >, oomph::AxisymFoepplvonKarmanEquations, oomph::QAxisymAdvectionDiffusionElement< NNODE_1D >, oomph::QAxisymAdvectionDiffusionElement< 3 >, oomph::AxisymAdvectionDiffusionEquations, oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, oomph::QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, oomph::QAdvectionDiffusionReactionElement< 2, DIM, 3 >, oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >, oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >, oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >, oomph::GeneralisedAdvectionDiffusionEquations< DIM >, oomph::GeneralisedAdvectionDiffusionEquations< 2 >, oomph::QAdvectionDiffusionElement< DIM, NNODE_1D >, oomph::QAdvectionDiffusionElement< DIM, 3 >, oomph::AdvectionDiffusionEquations< DIM >, oomph::AdvectionDiffusionEquations< 2 >, oomph::PolarStreamfunctionElement, oomph::PolarStreamfunctionEquations, oomph::SolubleSurfactantTransportInterfaceElement, oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, QThermalPVDElement< DIM >, oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::AxisymmetricQAdvectionCrouzeixRaviartElement, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, QAxisymAdvectionDiffusionElementWithExternalElement, RefineableQAxisymAdvectionDiffusionBoussinesqElement, oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement, QAxisymAdvectionDiffusionElementWithExternalElement, RefineableQAxisymAdvectionDiffusionBoussinesqElement, oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement, RefineableQAdvectionDiffusionElementWithExternalElement< DIM >, RefineableQCrouzeixRaviartElementWithExternalElement< DIM >, RefineableBuoyantQCrouzeixRaviartElement< DIM >, oomph::PerturbedSpineLinearisedAxisymmetricFluidInterfaceElement< ELEMENT >, oomph::LinearisedAxisymmetricFluidInterfaceElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::QMultiPoissonElement< DIM, NNODE_1D, NFIELDS >, oomph::MultiPoissonEquations< DIM, NFIELDS >, oomph::THomogenisedLinearElasticityElement< DIM, NNODE_1D >, oomph::HomogenisedLinearElasticityEquations< DIM >, oomph::UnsteadyHeatFluxPseudoMeltElement< ELEMENT >, oomph::HeatedPenetratorFluxElement< ELEMENT >, oomph::TLinearHeatAndElasticityElement< DIM, NNODE_1D >, oomph::UnsteadyHeatBaseFaceElement< ELEMENT >, oomph::SurfaceContactElementBase< ELEMENT >, oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::PseudoSolidNodeUpdateElement< TCrouzeixRaviartElement< 2 >, TPVDBubbleEnrichedElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< TTaylorHoodElement< 2 >, TPVDElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< GeneralisedNewtonianAxisymmetricTTaylorHoodElement, TPVDElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< AxisymmetricTTaylorHoodElement, TPVDElement< 2, 3 > >, and oomph::PseudoSolidNodeUpdateElement< GeneralisedNewtonianTTaylorHoodElement< 2 >, TPVDElement< 2, 3 > >.
     {
       throw OomphLibError("C-style output function function hasn't been "
                           "implemented for this element",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
output() [4/5]
virtual void oomph::FiniteElement::output (std::ostream & outfile) inline virtual
Output the element data — typically the values at the nodes in a format suitable for post-processing.
Reimplemented in oomph::CustomisedQPoissonElement< DIM, NNODE_1D >, oomph::TElement< 3, NNODE_1D >, oomph::TElement< 2, NNODE_1D >, oomph::TElement< 1, NNODE_1D >, oomph::QYoungLaplaceElement< NNODE_1D >, oomph::YoungLaplaceEquations, oomph::YoungLaplaceContactAngleElement< ELEMENT >, oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >, oomph::QWomersleyElement< DIM, NNODE_1D >, oomph::WomersleyEquations< DIM >, oomph::TWomersleyElement< DIM, NNODE_1D >, oomph::UnsteadyHeatFluxElement< ELEMENT >, oomph::QUnsteadyHeatElement< DIM, NNODE_1D >, oomph::QUnsteadyHeatElement< DIM, 3 >, oomph::UnsteadyHeatEquations< DIM >, oomph::UnsteadyHeatEquations< 2 >, oomph::TUnsteadyHeatElement< DIM, NNODE_1D >, oomph::TTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::TimeHarmonicLinearElasticityTractionElement< ELEMENT >, oomph::QTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::TimeHarmonicLinearElasticityEquations< DIM >, oomph::TimeHarmonicFourierDecomposedLinearElasticityTractionElement< ELEMENT >, oomph::TTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >, oomph::QTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >, oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations, oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >, oomph::QSteadyAxisymAdvectionDiffusionElement< NNODE_1D >, oomph::SteadyAxisymAdvectionDiffusionEquations, oomph::QSphericalTaylorHoodElement, oomph::QSphericalCrouzeixRaviartElement, oomph::SphericalNavierStokesEquations, oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >, oomph::QSphericalAdvectionDiffusionElement< NNODE_1D >, oomph::SphericalAdvectionDiffusionEquations, oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >, oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< 2 >, oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< 2 >, oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >, oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >, oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >, oomph::FpPressureAdvDiffRobinBCMixedOrderSpaceTimeElement< ELEMENT >, oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >, oomph::QTaylorHoodSpaceTimeElement< DIM >, oomph::QTaylorHoodSpaceTimeElement< 2 >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >, oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >, oomph::QTaylorHoodSpaceTimeElement< DIM >, oomph::QTaylorHoodSpaceTimeElement< 2 >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >, oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >, oomph::QTaylorHoodSpaceTimeElement< DIM >, oomph::QTaylorHoodSpaceTimeElement< 2 >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >, oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >, oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >, oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >, oomph::SolidTractionElement< ELEMENT >, oomph::TPVDElementWithContinuousPressure< DIM >, oomph::TPVDBubbleEnrichedElement< DIM, NNODE_1D >, oomph::TPVDElement< DIM, NNODE_1D >, oomph::QPVDElementWithContinuousPressure< DIM >, oomph::QPVDElementWithPressure< DIM >, oomph::PVDEquationsWithPressure< DIM >, oomph::HermitePVDElement< DIM >, oomph::QPVDElement< DIM, NNODE_1D >, oomph::QPVDElement< DIM, 3 >, oomph::PVDEquations< DIM >, oomph::ClampedHermiteShellBoundaryConditionElement, oomph::HermiteShellElement, oomph::KirchhoffLoveShellEquations, oomph::TPoroelasticityElement< ORDER >, oomph::PoroelasticityFaceElement< ELEMENT >, oomph::PoroelasticityEquations< DIM >, oomph::PoroelasticityEquations< 2 >, oomph::PolarStressIntegralElement< ELEMENT >, oomph::PolarTaylorHoodElement, oomph::PolarCrouzeixRaviartElement, oomph::PolarNavierStokesEquations, oomph::PolarNavierStokesTractionElement< ELEMENT >, oomph::TPoissonElement< DIM, NNODE_1D >, oomph::QSpectralPoissonElement< DIM, NNODE_1D >, oomph::PoissonFluxElement< ELEMENT >, oomph::QPoissonElement< DIM, NNODE_1D >, oomph::QPoissonElement< DIM, 2 >, oomph::PoissonEquations< DIM >, oomph::PoissonEquations< 1 >, oomph::PoissonEquations< 2 >, oomph::PoissonEquations< 3 >, oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::PMLTimeHarmonicLinearElasticityTractionElement< ELEMENT >, oomph::QPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::QPMLTimeHarmonicLinearElasticityElement< 2, NNODE_1D >, oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >, oomph::TPMLHelmholtzElement< DIM, NNODE_1D >, oomph::PMLHelmholtzFluxElement< ELEMENT >, oomph::QPMLHelmholtzElement< DIM, NNODE_1D >, oomph::QPMLHelmholtzElement< 2, NNODE_1D >, oomph::PMLHelmholtzEquations< DIM >, oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >, oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >, oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::PMLFourierDecomposedHelmholtzEquations, oomph::TTaylorHoodElement< DIM >, oomph::TCrouzeixRaviartElement< DIM >, oomph::QTaylorHoodElement< DIM >, oomph::QTaylorHoodElement< 2 >, oomph::QCrouzeixRaviartElement< DIM >, oomph::NavierStokesEquations< DIM >, oomph::NavierStokesEquations< 2 >, oomph::FpPressureAdvDiffRobinBCElement< ELEMENT >, oomph::ImposeParallelOutflowElement< ELEMENT >, oomph::ImposeImpenetrabilityElement< ELEMENT >, oomph::NavierStokesTractionElement< ELEMENT >, oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >, oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >, oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >, oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >, oomph::HelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >, oomph::TimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >, oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >, oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >, oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >, oomph::BuoyantQCrouzeixRaviartElement< DIM >, oomph::LinearisedQTaylorHoodElement, oomph::LinearisedQCrouzeixRaviartElement, oomph::LinearisedNavierStokesEquations, oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::LinearisedAxisymmetricNavierStokesEquations, oomph::LinearWaveFluxElement< ELEMENT >, oomph::QLinearWaveElement< DIM, NNODE_1D >, oomph::LinearWaveEquations< DIM >, oomph::TLinearElasticityElement< DIM, NNODE_1D >, oomph::LinearElasticityTractionElement< ELEMENT >, oomph::QLinearElasticityElement< DIM, NNODE_1D >, oomph::QLinearElasticityElement< DIM, 2 >, oomph::QLinearElasticityElement< DIM, 3 >, oomph::LinearElasticityEquations< DIM >, oomph::THelmholtzElement< DIM, NNODE_1D >, oomph::HelmholtzFluxElement< ELEMENT >, oomph::QHelmholtzElement< DIM, NNODE_1D >, oomph::HelmholtzEquations< DIM >, oomph::HelmholtzBCElementBase< ELEMENT >, oomph::QSpectralElement< 3, NNODE_1D >, oomph::QSpectralElement< 2, NNODE_1D >, oomph::QSpectralElement< 1, NNODE_1D >, oomph::SolidQElement< 3, NNODE_1D >, oomph::SolidQElement< 2, NNODE_1D >, oomph::SolidQElement< 1, NNODE_1D >, oomph::QElement< 3, NNODE_1D >, oomph::QElement< 2, NNODE_1D >, oomph::QElement< 1, NNODE_1D >, oomph::PseudoSolidNodeUpdateElement< TCrouzeixRaviartElement< 2 >, TPVDBubbleEnrichedElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< TTaylorHoodElement< 2 >, TPVDElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< GeneralisedNewtonianAxisymmetricTTaylorHoodElement, TPVDElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< AxisymmetricTTaylorHoodElement, TPVDElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< GeneralisedNewtonianTTaylorHoodElement< 2 >, TPVDElement< 2, 3 > >, oomph::SpectralPeriodicOrbitElement< NNODE_1D >, oomph::SolidQHermiteElement< DIM >, oomph::SolidQHermiteElement< 1 >, oomph::SolidQHermiteElement< 2 >, oomph::QHermiteElement< DIM >, oomph::QHermiteElement< DIM - 1 >, oomph::QHermiteElement< DIM >, oomph::QHermiteElement< DIM - 1 >, oomph::QHermiteElement< DIM >, oomph::QHermiteElement< DIM - 1 >, oomph::DummyFaceElement< ELEMENT >, oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >, oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >, oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >, oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >, oomph::GeneralisedNewtonianNavierStokesEquations< DIM >, oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement, oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement, oomph::GeneralisedNewtonianAxisymmetricQTaylorHoodElement, oomph::GeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement, oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations, oomph::TFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >, oomph::QFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::FourierDecomposedHelmholtzEquations, oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >, oomph::TFoepplvonKarmanElement< NNODE_1D >, oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >, oomph::QFoepplvonKarmanElement< NNODE_1D >, oomph::FoepplvonKarmanEquations, oomph::DisplacementBasedFoepplvonKarmanEquations, oomph::QScalarAdvectionElement< DIM, NNODE_1D >, oomph::QScalarAdvectionElement< 1, NNODE_1D >, oomph::QScalarAdvectionElement< 2, NNODE_1D >, oomph::QSpectralScalarAdvectionElement< DIM, NNODE_1D >, oomph::QSpectralScalarAdvectionElement< 1, NNODE_1D >, oomph::QSpectralScalarAdvectionElement< 2, NNODE_1D >, oomph::FluxTransportEquations< DIM >, oomph::QSpectralEulerElement< DIM, NNODE_1D >, oomph::QSpectralEulerElement< 1, NNODE_1D >, oomph::QSpectralEulerElement< 2, NNODE_1D >, oomph::EulerEquations< DIM >, oomph::SurfactantTransportInterfaceElement, oomph::ElasticLineFluidInterfaceBoundingElement< ELEMENT >, oomph::ElasticPointFluidInterfaceBoundingElement< ELEMENT >, oomph::ElasticUpdateFluidInterfaceElement< FluidInterfaceElement, SurfaceDerivatives, ELEMENT >, oomph::ElasticUpdateFluidInterfaceElement< SurfactantTransportInterfaceElement, AxisymmetricDerivatives, ELEMENT >, oomph::ElasticUpdateFluidInterfaceElement< FluidInterfaceElement, AxisymmetricDerivatives, ELEMENT >, oomph::ElasticUpdateFluidInterfaceElement< SolubleSurfactantTransportInterfaceElement, LineDerivatives, ELEMENT >, oomph::ElasticUpdateFluidInterfaceElement< FluidInterfaceElement, LineDerivatives, ELEMENT >, oomph::SpineLineFluidInterfaceBoundingElement< ELEMENT >, oomph::SpinePointFluidInterfaceBoundingElement< ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< EQUATION_CLASS, DERIVATIVE_CLASS, ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< SurfactantTransportInterfaceElement, LineDerivatives, ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< FluidInterfaceElement, SurfaceDerivatives, ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< SurfactantTransportInterfaceElement, AxisymmetricDerivatives, ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< SurfactantTransportInterfaceElement, SurfaceDerivatives, ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< FluidInterfaceElement, AxisymmetricDerivatives, ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< SolubleSurfactantTransportInterfaceElement, LineDerivatives, ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< FluidInterfaceElement, LineDerivatives, ELEMENT >, oomph::FluidInterfaceElement, oomph::FluidInterfaceBoundingElement, oomph::TRaviartThomasDarcyElement< ORDER >, oomph::DarcyFaceElement< ELEMENT >, oomph::DarcyEquations< DIM >, oomph::DarcyEquations< 2 >, oomph::BiharmonicFluidBoundaryElement, oomph::BiharmonicFluxElement< DIM >, oomph::BiharmonicElement< DIM >, oomph::BiharmonicEquations< DIM >, oomph::ClampedSlidingHermiteBeamBoundaryConditionElement, oomph::HermiteBeamElement, oomph::AxisymmetricSolidTractionElement< ELEMENT >, oomph::AxisymQPVDElementWithPressure, oomph::AxisymmetricPVDEquationsWithPressure, oomph::AxisymDiagHermitePVDElement, oomph::AxisymQPVDElement, oomph::AxisymmetricPVDEquations, oomph::TAxisymmetricPoroelasticityElement< ORDER >, oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >, oomph::AxisymmetricPoroelasticityTractionElement< POROELASTICITY_BULK_ELEMENT >, oomph::AxisymmetricPoroelasticityEquations, oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >, oomph::AxisymmetricTTaylorHoodElement, oomph::AxisymmetricTCrouzeixRaviartElement, oomph::AxisymmetricQTaylorHoodElement, oomph::AxisymmetricQCrouzeixRaviartElement, oomph::AxisymmetricNavierStokesEquations, oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >, oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >, oomph::TAxisymmetricLinearElasticityElement< NNODE_1D >, oomph::FSIAxisymmetricLinearElasticityTractionElement< ELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >, oomph::AxisymmetricLinearElasticityTractionElement< ELEMENT >, oomph::QAxisymmetricLinearElasticityElement< NNODE_1D >, oomph::AxisymmetricLinearElasticityEquations, oomph::AxisymFoepplvonKarmanElement< NNODE_1D >, oomph::AxisymFoepplvonKarmanEquations, oomph::AxisymFoepplvonKarmanElement< NNODE_1D >, oomph::AxisymFoepplvonKarmanEquations, oomph::QAxisymAdvectionDiffusionElement< NNODE_1D >, oomph::QAxisymAdvectionDiffusionElement< 3 >, oomph::AxisymAdvectionDiffusionEquations, oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, oomph::QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, oomph::QAdvectionDiffusionReactionElement< 2, DIM, 3 >, oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >, oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >, oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >, oomph::GeneralisedAdvectionDiffusionEquations< DIM >, oomph::GeneralisedAdvectionDiffusionEquations< 2 >, oomph::AdvectionDiffusionFluxElement< ELEMENT >, oomph::QAdvectionDiffusionElement< DIM, NNODE_1D >, oomph::QAdvectionDiffusionElement< DIM, 3 >, oomph::AdvectionDiffusionEquations< DIM >, oomph::AdvectionDiffusionEquations< 2 >, oomph::NavierStokesFluxControlElement< ELEMENT >, oomph::PolarStreamfunctionElement, oomph::PolarStreamfunctionEquations, oomph::PolarStreamfunctionTractionElement< ELEMENT >, SpineGravityTractionElement< ELEMENT >, FixSpineHeightElement, oomph::SolubleSurfactantTransportInterfaceElement, oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::AxisymmetricQAdvectionCrouzeixRaviartElement, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement, oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement, oomph::PerturbedSpineLinearisedAxisymmetricFluidInterfaceElement< ELEMENT >, oomph::LinearisedAxisymmetricFluidInterfaceElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::LinearisedAxisymmetricNavierStokesEquations, oomph::QMultiPoissonElement< DIM, NNODE_1D, NFIELDS >, oomph::MultiPoissonEquations< DIM, NFIELDS >, oomph::THomogenisedLinearElasticityElement< DIM, NNODE_1D >, oomph::HomogenisedLinearElasticityEquations< DIM >, oomph::UnsteadyHeatFluxPseudoMeltElement< ELEMENT >, oomph::HeatedPenetratorFluxElement< ELEMENT >, oomph::TLinearHeatAndElasticityElement< DIM, NNODE_1D >, oomph::UnsteadyHeatBaseFaceElement< ELEMENT >, oomph::LinearSurfaceContactElement< ELEMENT >, oomph::NonlinearSurfaceContactElement< ELEMENT >, oomph::SurfaceContactElementBase< ELEMENT >, oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::LinearisedAxisymmetricNavierStokesEquations, TwoNodePoissonElement, GelfandBratuElement< NNODE_1D >, ModalPRefineableQPoissonElement< DIM >, ModalPoissonEquations< DIM >, QThermalPVDElement< DIM >, QAxisymAdvectionDiffusionElementWithExternalElement, RefineableQAxisymAdvectionDiffusionBoussinesqElement, QAxisymAdvectionDiffusionElementWithExternalElement, RefineableQAxisymAdvectionDiffusionBoussinesqElement, RefineableQAdvectionDiffusionElementWithExternalElement< DIM >, RefineableQCrouzeixRaviartElementWithExternalElement< DIM >, RefineableBuoyantQCrouzeixRaviartElement< DIM >, QHarmonicElement< NNODE_1D >, HarmonicEquations, SSPorousChannelElement, SSPorousChannelEquations, FixSpineHeightElement, SpineGravityTractionElement< ELEMENT >, QOrrSommerfeldElement< 1, NNODE_1D >, OrrSommerfeldEquations< DIM >, QHarmonicElement< NNODE_1D >, HarmonicEquations, QComplexHarmonicElement< NNODE_1D >, ComplexHarmonicEquations, SSPorousChannelElement, and SSPorousChannelEquations.
     {
       throw OomphLibError(
         "Output function function hasn't been implemented for this element",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::Multi_domain_functions::aux_setup_multi_domain_interaction(), oomph::Mesh::check_inverted_elements(), RingWithTRibProblem< ELASTICITY_ELEMENT >::doc_solution(), oomph::FluidInterfaceAdditionalValues< SolubleSurfactantTransportInterfaceElement >::FluidInterfaceAdditionalValues(), oomph::SurfaceContactElementBase< ELEMENT >::output(), oomph::UnsteadyHeatBaseFaceElement< ELEMENT >::output(), oomph::AxisymmetricLinearElasticityTractionElement< ELEMENT >::output(), oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::output(), oomph::QSpectralElement< 1, NNODE_1D >::output(), oomph::QSpectralElement< 2, NNODE_1D >::output(), oomph::QSpectralElement< 3, NNODE_1D >::output(), oomph::PMLTimeHarmonicLinearElasticityTractionElement< ELEMENT >::output(), oomph::PoissonFluxElement< ELEMENT >::output(), oomph::SolidTractionElement< ELEMENT >::output(), oomph::TimeHarmonicLinearElasticityTractionElement< ELEMENT >::output(), RefineableBuoyantQCrouzeixRaviartElement< DIM >::output(), RefineableQCrouzeixRaviartElementWithExternalElement< DIM >::output(), RefineableQAdvectionDiffusionElementWithExternalElement< DIM >::output(), RefineableQAxisymAdvectionDiffusionBoussinesqElement::output(), QAxisymAdvectionDiffusionElementWithExternalElement::output(), QThermalPVDElement< DIM >::output(), oomph::LinearisedAxisymmetricFluidInterfaceElement::output(), oomph::PerturbedSpineLinearisedAxisymmetricFluidInterfaceElement< ELEMENT >::output(), oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::output(), oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::output(), oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::output(), oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement::output(), oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >::output(), oomph::SolubleSurfactantTransportInterfaceElement::output(), oomph::PolarStreamfunctionTractionElement< ELEMENT >::output(), oomph::NavierStokesFluxControlElement< ELEMENT >::output(), oomph::AdvectionDiffusionFluxElement< ELEMENT >::output(), oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::output(), oomph::AxisymmetricPVDEquations::output(), oomph::AxisymQPVDElement::output(), oomph::AxisymDiagHermitePVDElement::output(), oomph::AxisymmetricPVDEquationsWithPressure::output(), oomph::AxisymQPVDElementWithPressure::output(), oomph::AxisymmetricSolidTractionElement< ELEMENT >::output(), oomph::ClampedSlidingHermiteBeamBoundaryConditionElement::output(), oomph::BiharmonicEquations< DIM >::output(), oomph::FluidInterfaceBoundingElement::output(), oomph::FluidInterfaceElement::output(), oomph::SpinePointFluidInterfaceBoundingElement< ELEMENT >::output(), oomph::SpineLineFluidInterfaceBoundingElement< ELEMENT >::output(), oomph::ElasticPointFluidInterfaceBoundingElement< ELEMENT >::output(), oomph::ElasticLineFluidInterfaceBoundingElement< ELEMENT >::output(), oomph::SurfactantTransportInterfaceElement::output(), oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >::output(), oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::output(), oomph::Mesh::output(), oomph::SpectralPeriodicOrbitElement< NNODE_1D >::output(), oomph::SolidQElement< 1, NNODE_1D >::output(), oomph::SolidQElement< 2, NNODE_1D >::output(), oomph::SolidQElement< 3, NNODE_1D >::output(), oomph::HelmholtzBCElementBase< ELEMENT >::output(), oomph::HelmholtzFluxElement< ELEMENT >::output(), oomph::LinearElasticityTractionElement< ELEMENT >::output(), oomph::LinearWaveFluxElement< ELEMENT >::output(), oomph::BuoyantQCrouzeixRaviartElement< DIM >::output(), oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::output(), oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::output(), oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::output(), oomph::NavierStokesTractionElement< ELEMENT >::output(), oomph::ImposeImpenetrabilityElement< ELEMENT >::output(), oomph::ImposeParallelOutflowElement< ELEMENT >::output(), oomph::FpPressureAdvDiffRobinBCElement< ELEMENT >::output(), oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::output(), oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::output(), oomph::PMLHelmholtzFluxElement< ELEMENT >::output(), oomph::PolarNavierStokesTractionElement< ELEMENT >::output(), oomph::PolarStressIntegralElement< ELEMENT >::output(), oomph::PoroelasticityFaceElement< ELEMENT >::output(), oomph::KirchhoffLoveShellEquations::output(), oomph::ClampedHermiteShellBoundaryConditionElement::output(), oomph::QPVDElementWithPressure< DIM >::output(), oomph::QPVDElementWithContinuousPressure< DIM >::output(), oomph::TPVDElementWithContinuousPressure< DIM >::output(), oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::output(), oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >::output(), oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::output(), oomph::FpPressureAdvDiffRobinBCMixedOrderSpaceTimeElement< ELEMENT >::output(), oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::output(), oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::output(), oomph::TimeHarmonicFourierDecomposedLinearElasticityTractionElement< ELEMENT >::output(), oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::output(), oomph::YoungLaplaceContactAngleElement< ELEMENT >::output(), oomph::DummyFaceElement< ELEMENT >::output(), oomph::DGElement::output_faces(), oomph::MyProblem::output_solution(), oomph::TetMeshBase::setup_boundary_element_info(), oomph::TetMeshBase::snap_nodes_onto_geometric_objects(), and STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::surface_output().
output() [5/5]
virtual void oomph::FiniteElement::output (std::ostream & outfile, const unsigned & n_plot) inline virtual
Output the element data — pass (some measure of) the number of plot points per element
Reimplemented in oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >, oomph::WomersleyEquations< DIM >, oomph::ProjectableUnsteadyHeatElement< UNSTEADY_HEAT_ELEMENT >, oomph::UnsteadyHeatEquations< DIM >, oomph::UnsteadyHeatEquations< 2 >, oomph::TTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::TimeHarmonicLinearElasticityTractionElement< ELEMENT >, oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >, oomph::SteadyAxisymAdvectionDiffusionEquations, oomph::QSphericalTaylorHoodElement, oomph::QSphericalCrouzeixRaviartElement, oomph::SphericalNavierStokesEquations, oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >, oomph::SphericalAdvectionDiffusionEquations, oomph::ProjectableUnsteadyHeatMixedOrderSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >, oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >, oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< 2 >, oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< 2 >, oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >, oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >, oomph::FpPressureAdvDiffRobinBCMixedOrderSpaceTimeElement< ELEMENT >, oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >, oomph::QTaylorHoodSpaceTimeElement< DIM >, oomph::QTaylorHoodSpaceTimeElement< 2 >, oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >, oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >, oomph::QTaylorHoodSpaceTimeElement< DIM >, oomph::QTaylorHoodSpaceTimeElement< 2 >, oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >, oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >, oomph::QTaylorHoodSpaceTimeElement< DIM >, oomph::QTaylorHoodSpaceTimeElement< 2 >, oomph::FpPressureAdvDiffRobinBCSpaceTimeElement< ELEMENT >, oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >, oomph::TPoroelasticityElement< ORDER >, oomph::PoroelasticityEquations< DIM >, oomph::PoroelasticityEquations< 2 >, oomph::PolarStressIntegralElement< ELEMENT >, oomph::PolarTaylorHoodElement, oomph::PolarCrouzeixRaviartElement, oomph::PolarNavierStokesEquations, oomph::PolarNavierStokesTractionElement< ELEMENT >, oomph::PoissonFluxElement< ELEMENT >, oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::PMLTimeHarmonicLinearElasticityTractionElement< ELEMENT >, oomph::ProjectablePMLHelmholtzElement< HELMHOLTZ_ELEMENT >, oomph::ProjectablePMLFourierDecomposedHelmholtzElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >, oomph::TTaylorHoodElement< DIM >, oomph::TCrouzeixRaviartElement< DIM >, oomph::QTaylorHoodElement< DIM >, oomph::QTaylorHoodElement< 2 >, oomph::QCrouzeixRaviartElement< DIM >, oomph::NavierStokesEquations< DIM >, oomph::NavierStokesEquations< 2 >, oomph::FpPressureAdvDiffRobinBCElement< ELEMENT >, oomph::ImposeParallelOutflowElement< ELEMENT >, oomph::ImposeImpenetrabilityElement< ELEMENT >, oomph::NavierStokesTractionElement< ELEMENT >, oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >, oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >, oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >, oomph::BuoyantQCrouzeixRaviartElement< DIM >, oomph::LinearisedNavierStokesEquations, oomph::LinearisedAxisymmetricNavierStokesEquations, oomph::LinearWaveEquations< DIM >, oomph::TLinearElasticityElement< DIM, NNODE_1D >, oomph::ProjectableHelmholtzElement< HELMHOLTZ_ELEMENT >, oomph::TElement< 3, NNODE_1D >, oomph::TElement< 2, NNODE_1D >, oomph::TElement< 1, NNODE_1D >, oomph::QSpectralElement< 3, NNODE_1D >, oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >, oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >, oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >, oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >, oomph::GeneralisedNewtonianNavierStokesEquations< DIM >, oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement, oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement, oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations, oomph::ProjectableFourierDecomposedHelmholtzElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >, oomph::FluxTransportEquations< DIM >, oomph::TRaviartThomasDarcyElement< ORDER >, oomph::ProjectableDarcyElement< DARCY_ELEMENT >, oomph::DarcyEquations< DIM >, oomph::DarcyEquations< 2 >, oomph::BiharmonicEquations< DIM >, oomph::TAxisymmetricPoroelasticityElement< ORDER >, oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >, oomph::AxisymmetricPoroelasticityEquations, oomph::AxisymmetricTTaylorHoodElement, oomph::AxisymmetricTCrouzeixRaviartElement, oomph::AxisymmetricNavierStokesEquations, oomph::TAxisymmetricLinearElasticityElement< NNODE_1D >, oomph::AxisymAdvectionDiffusionEquations, oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >, oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >, oomph::GeneralisedAdvectionDiffusionEquations< DIM >, oomph::GeneralisedAdvectionDiffusionEquations< 2 >, oomph::AdvectionDiffusionFluxElement< ELEMENT >, oomph::AdvectionDiffusionEquations< DIM >, oomph::AdvectionDiffusionEquations< 2 >, oomph::NavierStokesFluxControlElement< ELEMENT >, oomph::PolarStreamfunctionTractionElement< ELEMENT >, oomph::MyCrouzeixRaviartElement, oomph::MyTaylorHoodElement< DIM >, oomph::MyTaylorHoodElement< DIM >, oomph::MyCrouzeixRaviartElement, oomph::MyTaylorHoodElement< DIM >, oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::AxisymmetricQAdvectionCrouzeixRaviartElement, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement, oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement, oomph::LinearisedAxisymmetricNavierStokesEquations, oomph::THomogenisedLinearElasticityElement< DIM, NNODE_1D >, oomph::HeatedPenetratorFluxElement< ELEMENT >, oomph::TLinearHeatAndElasticityElement< DIM, NNODE_1D >, oomph::MyTaylorHoodElement< DIM >, oomph::LinearisedAxisymmetricNavierStokesEquations, SpineGravityTractionElement< ELEMENT >, FixSpineHeightElement, oomph::QYoungLaplaceElement< NNODE_1D >, oomph::YoungLaplaceEquations, oomph::YoungLaplaceContactAngleElement< ELEMENT >, oomph::QWomersleyElement< DIM, NNODE_1D >, oomph::TWomersleyElement< DIM, NNODE_1D >, oomph::UnsteadyHeatFluxElement< ELEMENT >, oomph::QUnsteadyHeatElement< DIM, NNODE_1D >, oomph::QUnsteadyHeatElement< DIM, 3 >, oomph::TUnsteadyHeatElement< DIM, NNODE_1D >, oomph::QTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::TimeHarmonicLinearElasticityEquations< DIM >, oomph::TimeHarmonicFourierDecomposedLinearElasticityTractionElement< ELEMENT >, oomph::TTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >, oomph::QTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >, oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations, oomph::QSteadyAxisymAdvectionDiffusionElement< NNODE_1D >, oomph::QSphericalAdvectionDiffusionElement< NNODE_1D >, oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >, oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >, oomph::FSISolidTractionElement< ELEMENT, DIM >, oomph::SolidTractionElement< ELEMENT >, oomph::TPVDElementWithContinuousPressure< DIM >, oomph::TPVDBubbleEnrichedElement< DIM, NNODE_1D >, oomph::TPVDElement< DIM, NNODE_1D >, oomph::QPVDElementWithContinuousPressure< DIM >, oomph::QPVDElementWithPressure< DIM >, oomph::PVDEquationsWithPressure< DIM >, oomph::HermitePVDElement< DIM >, oomph::QPVDElement< DIM, NNODE_1D >, oomph::QPVDElement< DIM, 3 >, oomph::PVDEquations< DIM >, oomph::ClampedHermiteShellBoundaryConditionElement, oomph::HermiteShellElement, oomph::KirchhoffLoveShellEquations, oomph::PoroelasticityFaceElement< ELEMENT >, oomph::TPoissonElement< DIM, NNODE_1D >, oomph::QSpectralPoissonElement< DIM, NNODE_1D >, oomph::QPoissonElement< DIM, NNODE_1D >, oomph::QPoissonElement< DIM, 2 >, oomph::PoissonEquations< DIM >, oomph::PoissonEquations< 1 >, oomph::PoissonEquations< 2 >, oomph::PoissonEquations< 3 >, oomph::QPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::QPMLTimeHarmonicLinearElasticityElement< 2, NNODE_1D >, oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >, oomph::TPMLHelmholtzElement< DIM, NNODE_1D >, oomph::PMLHelmholtzFluxElement< ELEMENT >, oomph::QPMLHelmholtzElement< DIM, NNODE_1D >, oomph::QPMLHelmholtzElement< 2, NNODE_1D >, oomph::PMLHelmholtzEquations< DIM >, oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >, oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >, oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::PMLFourierDecomposedHelmholtzEquations, oomph::NavierStokesSurfaceDragTorqueElement< ELEMENT >, oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >, oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >, oomph::HelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >, oomph::TimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >, oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >, oomph::FourierDecomposedTimeHarmonicLinElastLoadedByHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >, oomph::LinearisedQTaylorHoodElement, oomph::LinearisedQCrouzeixRaviartElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::LinearWaveFluxElement< ELEMENT >, oomph::QLinearWaveElement< DIM, NNODE_1D >, oomph::LinearElasticityTractionElement< ELEMENT >, oomph::QLinearElasticityElement< DIM, NNODE_1D >, oomph::QLinearElasticityElement< DIM, 2 >, oomph::QLinearElasticityElement< DIM, 3 >, oomph::LinearElasticityEquations< DIM >, oomph::THelmholtzElement< DIM, NNODE_1D >, oomph::HelmholtzFluxElement< ELEMENT >, oomph::QHelmholtzElement< DIM, NNODE_1D >, oomph::HelmholtzEquations< DIM >, oomph::HelmholtzBCElementBase< ELEMENT >, oomph::QSpectralElement< 2, NNODE_1D >, oomph::QSpectralElement< 1, NNODE_1D >, oomph::SolidQElement< 3, NNODE_1D >, oomph::SolidQElement< 2, NNODE_1D >, oomph::SolidQElement< 1, NNODE_1D >, oomph::QElement< 3, NNODE_1D >, oomph::QElement< 2, NNODE_1D >, oomph::QElement< 1, NNODE_1D >, oomph::SpectralPeriodicOrbitElement< NNODE_1D >, oomph::SolidQHermiteElement< DIM >, oomph::SolidQHermiteElement< 1 >, oomph::SolidQHermiteElement< 2 >, oomph::QHermiteElement< DIM >, oomph::QHermiteElement< DIM - 1 >, oomph::SolidQHermiteElement< DIM >, oomph::SolidQHermiteElement< 1 >, oomph::SolidQHermiteElement< 2 >, oomph::QHermiteElement< DIM >, oomph::QHermiteElement< DIM - 1 >, oomph::QHermiteElement< DIM >, oomph::QHermiteElement< DIM - 1 >, oomph::DummyFaceElement< ELEMENT >, oomph::GeneralisedNewtonianAxisymmetricQTaylorHoodElement, oomph::GeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement, oomph::TFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >, oomph::QFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::FourierDecomposedHelmholtzEquations, oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >, oomph::TFoepplvonKarmanElement< NNODE_1D >, oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >, oomph::QFoepplvonKarmanElement< NNODE_1D >, oomph::FoepplvonKarmanEquations, oomph::DisplacementBasedFoepplvonKarmanEquations, oomph::QScalarAdvectionElement< DIM, NNODE_1D >, oomph::QScalarAdvectionElement< 1, NNODE_1D >, oomph::QScalarAdvectionElement< 2, NNODE_1D >, oomph::QSpectralScalarAdvectionElement< DIM, NNODE_1D >, oomph::QSpectralScalarAdvectionElement< 1, NNODE_1D >, oomph::QSpectralScalarAdvectionElement< 2, NNODE_1D >, oomph::QSpectralEulerElement< DIM, NNODE_1D >, oomph::QSpectralEulerElement< 1, NNODE_1D >, oomph::QSpectralEulerElement< 2, NNODE_1D >, oomph::EulerEquations< DIM >, oomph::SurfactantTransportInterfaceElement, oomph::ElasticLineFluidInterfaceBoundingElement< ELEMENT >, oomph::ElasticPointFluidInterfaceBoundingElement< ELEMENT >, oomph::ElasticUpdateFluidInterfaceElement< FluidInterfaceElement, SurfaceDerivatives, ELEMENT >, oomph::ElasticUpdateFluidInterfaceElement< SurfactantTransportInterfaceElement, AxisymmetricDerivatives, ELEMENT >, oomph::ElasticUpdateFluidInterfaceElement< FluidInterfaceElement, AxisymmetricDerivatives, ELEMENT >, oomph::ElasticUpdateFluidInterfaceElement< SolubleSurfactantTransportInterfaceElement, LineDerivatives, ELEMENT >, oomph::ElasticUpdateFluidInterfaceElement< FluidInterfaceElement, LineDerivatives, ELEMENT >, oomph::SpineLineFluidInterfaceBoundingElement< ELEMENT >, oomph::SpinePointFluidInterfaceBoundingElement< ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< EQUATION_CLASS, DERIVATIVE_CLASS, ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< SurfactantTransportInterfaceElement, LineDerivatives, ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< FluidInterfaceElement, SurfaceDerivatives, ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< SurfactantTransportInterfaceElement, AxisymmetricDerivatives, ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< SurfactantTransportInterfaceElement, SurfaceDerivatives, ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< FluidInterfaceElement, AxisymmetricDerivatives, ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< SolubleSurfactantTransportInterfaceElement, LineDerivatives, ELEMENT >, oomph::SpineUpdateFluidInterfaceElement< FluidInterfaceElement, LineDerivatives, ELEMENT >, oomph::FluidInterfaceElement, oomph::FluidInterfaceBoundingElement, oomph::DarcyFaceElement< ELEMENT >, oomph::BiharmonicFluidBoundaryElement, oomph::BiharmonicFluxElement< DIM >, oomph::BiharmonicElement< DIM >, oomph::ClampedSlidingHermiteBeamBoundaryConditionElement, oomph::HermiteBeamElement, oomph::AxisymmetricSolidTractionElement< ELEMENT >, oomph::AxisymQPVDElementWithPressure, oomph::AxisymmetricPVDEquationsWithPressure, oomph::AxisymDiagHermitePVDElement, oomph::AxisymQPVDElement, oomph::AxisymmetricPVDEquations, oomph::FSILinearisedAxisymPoroelasticTractionElement< POROELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >, oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >, oomph::AxisymmetricPoroelasticityTractionElement< POROELASTICITY_BULK_ELEMENT >, oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >, oomph::AxisymmetricQTaylorHoodElement, oomph::AxisymmetricQCrouzeixRaviartElement, oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >, oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >, oomph::FSIAxisymmetricLinearElasticityTractionElement< ELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >, oomph::AxisymmetricLinearElasticityTractionElement< ELEMENT >, oomph::QAxisymmetricLinearElasticityElement< NNODE_1D >, oomph::AxisymmetricLinearElasticityEquations, oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >, oomph::AxisymFoepplvonKarmanElement< NNODE_1D >, oomph::AxisymFoepplvonKarmanEquations, oomph::AxisymFoepplvonKarmanElement< NNODE_1D >, oomph::AxisymFoepplvonKarmanEquations, oomph::QAxisymAdvectionDiffusionElement< NNODE_1D >, oomph::QAxisymAdvectionDiffusionElement< 3 >, oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, oomph::QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, oomph::QAdvectionDiffusionReactionElement< 2, DIM, 3 >, oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >, oomph::QAdvectionDiffusionElement< DIM, NNODE_1D >, oomph::QAdvectionDiffusionElement< DIM, 3 >, oomph::PolarStreamfunctionElement, oomph::PolarStreamfunctionEquations, oomph::SolubleSurfactantTransportInterfaceElement, oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >, ElasticAxisymmetricSolubleSurfactantTransportInterfaceElement< ELEMENT >, oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >, oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >, oomph::PerturbedSpineLinearisedAxisymmetricFluidInterfaceElement< ELEMENT >, oomph::LinearisedAxisymmetricFluidInterfaceElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::QMultiPoissonElement< DIM, NNODE_1D, NFIELDS >, oomph::MultiPoissonEquations< DIM, NFIELDS >, oomph::HomogenisedLinearElasticityEquations< DIM >, oomph::UnsteadyHeatFluxPseudoMeltElement< ELEMENT >, oomph::HeatedLinearSurfaceContactElement< ELEMENT >, oomph::UnsteadyHeatBaseFaceElement< ELEMENT >, oomph::LinearSurfaceContactElement< ELEMENT >, oomph::NonlinearSurfaceContactElement< ELEMENT >, oomph::SurfaceContactElementBase< ELEMENT >, oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, DistanceWrapper< ELEMENT >, oomph::PseudoSolidNodeUpdateElement< TCrouzeixRaviartElement< 2 >, TPVDBubbleEnrichedElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< TTaylorHoodElement< 2 >, TPVDElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< GeneralisedNewtonianAxisymmetricTTaylorHoodElement, TPVDElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< AxisymmetricTTaylorHoodElement, TPVDElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< GeneralisedNewtonianTTaylorHoodElement< 2 >, TPVDElement< 2, 3 > >, oomph::SolidQHermiteElement< DIM >, oomph::SolidQHermiteElement< 1 >, oomph::SolidQHermiteElement< 2 >, ModalPRefineableQPoissonElement< DIM >, ModalPoissonEquations< DIM >, QThermalPVDElement< DIM >, QAxisymAdvectionDiffusionElementWithExternalElement, RefineableQAxisymAdvectionDiffusionBoussinesqElement, QAxisymAdvectionDiffusionElementWithExternalElement, RefineableQAxisymAdvectionDiffusionBoussinesqElement, RefineableQAdvectionDiffusionElementWithExternalElement< DIM >, RefineableQCrouzeixRaviartElementWithExternalElement< DIM >, RefineableBuoyantQCrouzeixRaviartElement< DIM >, QHarmonicElement< NNODE_1D >, HarmonicEquations, SSPorousChannelElement, QOrrSommerfeldElement< 1, NNODE_1D >, OrrSommerfeldEquations< DIM >, QHarmonicElement< NNODE_1D >, HarmonicEquations, QComplexHarmonicElement< NNODE_1D >, ComplexHarmonicEquations, SSPorousChannelElement, SSPorousChannelEquations, FixSpineHeightElement, SpineGravityTractionElement< ELEMENT >, and SSPorousChannelEquations.
     {
       throw OomphLibError(
         "Output function function hasn't been implemented for this element",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
output_fct() [1/3]
virtual void oomph::FiniteElement::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, const SolutionFunctorBase & exact_soln) const inline virtual
Output a time-dependent exact solution over the element.
     {
       throw OomphLibError(
         "Output function function hasn't been implemented for exact solution",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
output_fct() [2/3]
virtual void oomph::FiniteElement::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) inline virtual
Output a time-dependent exact solution over the element.
Reimplemented in oomph::WomersleyEquations< DIM >, oomph::UnsteadyHeatEquations< DIM >, oomph::UnsteadyHeatEquations< 2 >, oomph::SphericalNavierStokesEquations, oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< 2 >, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< 2 >, oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::PoroelasticityEquations< DIM >, oomph::PoroelasticityEquations< 2 >, oomph::PolarNavierStokesEquations, oomph::NavierStokesEquations< DIM >, oomph::NavierStokesEquations< 2 >, oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >, oomph::BuoyantQCrouzeixRaviartElement< DIM >, oomph::LinearWaveEquations< DIM >, oomph::LinearElasticityEquations< DIM >, oomph::GeneralisedNewtonianNavierStokesEquations< DIM >, oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations, oomph::BiharmonicElement< DIM >, oomph::BiharmonicEquations< DIM >, oomph::AxisymmetricPoroelasticityEquations, oomph::AxisymmetricNavierStokesEquations, oomph::AxisymmetricLinearElasticityEquations, oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >, oomph::GeneralisedAdvectionDiffusionEquations< DIM >, oomph::GeneralisedAdvectionDiffusionEquations< 2 >, oomph::AdvectionDiffusionEquations< DIM >, oomph::AdvectionDiffusionEquations< 2 >, oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::AxisymmetricQAdvectionCrouzeixRaviartElement, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement, oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement, oomph::TLinearHeatAndElasticityElement< DIM, NNODE_1D >, oomph::QYoungLaplaceElement< NNODE_1D >, oomph::YoungLaplaceEquations, oomph::QWomersleyElement< DIM, NNODE_1D >, oomph::TWomersleyElement< DIM, NNODE_1D >, oomph::QUnsteadyHeatElement< DIM, NNODE_1D >, oomph::QUnsteadyHeatElement< DIM, 3 >, oomph::TUnsteadyHeatElement< DIM, NNODE_1D >, oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, oomph::TPoissonElement< DIM, NNODE_1D >, oomph::QSpectralPoissonElement< DIM, NNODE_1D >, oomph::QPoissonElement< DIM, NNODE_1D >, oomph::QPoissonElement< DIM, 2 >, oomph::PoissonEquations< DIM >, oomph::PoissonEquations< 1 >, oomph::PoissonEquations< 2 >, oomph::PoissonEquations< 3 >, oomph::TPMLHelmholtzElement< DIM, NNODE_1D >, oomph::QPMLHelmholtzElement< DIM, NNODE_1D >, oomph::QPMLHelmholtzElement< 2, NNODE_1D >, oomph::PMLHelmholtzEquations< DIM >, oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::PMLFourierDecomposedHelmholtzEquations, oomph::QLinearWaveElement< DIM, NNODE_1D >, oomph::THelmholtzElement< DIM, NNODE_1D >, oomph::QHelmholtzElement< DIM, NNODE_1D >, oomph::HelmholtzEquations< DIM >, oomph::TFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::QFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::FourierDecomposedHelmholtzEquations, oomph::TFoepplvonKarmanElement< NNODE_1D >, oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >, oomph::QFoepplvonKarmanElement< NNODE_1D >, oomph::FoepplvonKarmanEquations, oomph::DisplacementBasedFoepplvonKarmanEquations, oomph::AxisymFoepplvonKarmanElement< NNODE_1D >, oomph::AxisymFoepplvonKarmanEquations, oomph::AxisymFoepplvonKarmanElement< NNODE_1D >, oomph::AxisymFoepplvonKarmanEquations, oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, oomph::QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, oomph::QAdvectionDiffusionReactionElement< 2, DIM, 3 >, oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >, oomph::QAdvectionDiffusionElement< DIM, NNODE_1D >, oomph::QAdvectionDiffusionElement< DIM, 3 >, oomph::PolarStreamfunctionElement, oomph::QMultiPoissonElement< DIM, NNODE_1D, NFIELDS >, and oomph::MultiPoissonEquations< DIM, NFIELDS >.
     {
       throw OomphLibError(
         "Output function function hasn't been implemented for exact solution",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
output_fct() [3/3]
virtual void oomph::FiniteElement::output_fct (std::ostream & outfile, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) inline virtual
Output an exact solution over the element.
Reimplemented in oomph::WomersleyEquations< DIM >, oomph::UnsteadyHeatEquations< DIM >, oomph::UnsteadyHeatEquations< 2 >, oomph::TimeHarmonicLinearElasticityEquations< DIM >, oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations, oomph::SteadyAxisymAdvectionDiffusionEquations, oomph::SphericalNavierStokesEquations, oomph::SphericalAdvectionDiffusionEquations, oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< 2 >, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< 2 >, oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::PoroelasticityEquations< DIM >, oomph::PoroelasticityEquations< 2 >, oomph::PolarNavierStokesEquations, oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >, oomph::NavierStokesEquations< DIM >, oomph::NavierStokesEquations< 2 >, oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >, oomph::BuoyantQCrouzeixRaviartElement< DIM >, oomph::LinearWaveEquations< DIM >, oomph::QLinearElasticityElement< DIM, NNODE_1D >, oomph::QLinearElasticityElement< DIM, 2 >, oomph::QLinearElasticityElement< DIM, 3 >, oomph::LinearElasticityEquations< DIM >, oomph::GeneralisedNewtonianNavierStokesEquations< DIM >, oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations, oomph::DarcyEquations< DIM >, oomph::DarcyEquations< 2 >, oomph::BiharmonicFluxElement< DIM >, oomph::BiharmonicElement< DIM >, oomph::BiharmonicEquations< DIM >, oomph::AxisymmetricPoroelasticityEquations, oomph::AxisymmetricNavierStokesEquations, oomph::AxisymmetricLinearElasticityEquations, oomph::AxisymAdvectionDiffusionEquations, oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >, oomph::GeneralisedAdvectionDiffusionEquations< DIM >, oomph::GeneralisedAdvectionDiffusionEquations< 2 >, oomph::AdvectionDiffusionEquations< DIM >, oomph::AdvectionDiffusionEquations< 2 >, oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::AxisymmetricQAdvectionCrouzeixRaviartElement, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement, oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement, oomph::TLinearHeatAndElasticityElement< DIM, NNODE_1D >, oomph::QYoungLaplaceElement< NNODE_1D >, oomph::YoungLaplaceEquations, oomph::QWomersleyElement< DIM, NNODE_1D >, oomph::TWomersleyElement< DIM, NNODE_1D >, oomph::QUnsteadyHeatElement< DIM, NNODE_1D >, oomph::QUnsteadyHeatElement< DIM, 3 >, oomph::TUnsteadyHeatElement< DIM, NNODE_1D >, oomph::QSteadyAxisymAdvectionDiffusionElement< NNODE_1D >, oomph::QSphericalAdvectionDiffusionElement< NNODE_1D >, oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, oomph::TPoissonElement< DIM, NNODE_1D >, oomph::QSpectralPoissonElement< DIM, NNODE_1D >, oomph::QPoissonElement< DIM, NNODE_1D >, oomph::QPoissonElement< DIM, 2 >, oomph::PoissonEquations< DIM >, oomph::PoissonEquations< 1 >, oomph::PoissonEquations< 2 >, oomph::PoissonEquations< 3 >, oomph::TPMLHelmholtzElement< DIM, NNODE_1D >, oomph::QPMLHelmholtzElement< DIM, NNODE_1D >, oomph::QPMLHelmholtzElement< 2, NNODE_1D >, oomph::PMLHelmholtzEquations< DIM >, oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::PMLFourierDecomposedHelmholtzEquations, oomph::QLinearWaveElement< DIM, NNODE_1D >, oomph::THelmholtzElement< DIM, NNODE_1D >, oomph::QHelmholtzElement< DIM, NNODE_1D >, oomph::HelmholtzEquations< DIM >, oomph::TFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::QFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::FourierDecomposedHelmholtzEquations, oomph::TFoepplvonKarmanElement< NNODE_1D >, oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >, oomph::QFoepplvonKarmanElement< NNODE_1D >, oomph::FoepplvonKarmanEquations, oomph::DisplacementBasedFoepplvonKarmanEquations, oomph::AxisymFoepplvonKarmanElement< NNODE_1D >, oomph::AxisymFoepplvonKarmanEquations, oomph::AxisymFoepplvonKarmanElement< NNODE_1D >, oomph::AxisymFoepplvonKarmanEquations, oomph::QAxisymAdvectionDiffusionElement< NNODE_1D >, oomph::QAxisymAdvectionDiffusionElement< 3 >, oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, oomph::QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, oomph::QAdvectionDiffusionReactionElement< 2, DIM, 3 >, oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >, oomph::QAdvectionDiffusionElement< DIM, NNODE_1D >, oomph::QAdvectionDiffusionElement< DIM, 3 >, oomph::PolarStreamfunctionElement, oomph::QMultiPoissonElement< DIM, NNODE_1D, NFIELDS >, and oomph::MultiPoissonEquations< DIM, NFIELDS >.
     {
       throw OomphLibError(
         "Output function function hasn't been implemented for exact solution",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::MyProblem::output_exact_solution(), RefineableBuoyantQCrouzeixRaviartElement< DIM >::output_fct(), RefineableQCrouzeixRaviartElementWithExternalElement< DIM >::output_fct(), RefineableQAdvectionDiffusionElementWithExternalElement< DIM >::output_fct(), QThermalPVDElement< DIM >::output_fct(), oomph::PolarStreamfunctionElement::output_fct(), oomph::Mesh::output_fct(), oomph::BiharmonicEquations< DIM >::output_fct(), oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::output_fct(), oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::output_fct(), oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::output_fct(), oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement::output_fct(), oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >::output_fct(), oomph::BuoyantQCrouzeixRaviartElement< DIM >::output_fct(), and oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::output_fct().
output_paraview()
void oomph::FiniteElement::output_paraview (std::ofstream & file_out, const unsigned & nplot) const inline
Paraview output – this outputs the coordinates at the plot points (for parameter nplot) to specified output file.
     {
       // Decide the dimensions of the nodes
       unsigned nnod = nnode();
       if (nnod == 0) return;
       unsigned n = node_pt(0)->ndim();
       // Vector for local coordinates
       Vector<double> s(n, 0.0);
       // Vector for cartesian coordinates
       Vector<double> x(n, 0.0);
       // Determine the total number of plotpoints
       unsigned plot = nplot_points_paraview(nplot);
       // Loop over the local points
       for (unsigned j = 0; j < plot; j++)
       {
         // Determine where in the local element the point is
         this->get_s_plot(j, nplot, s);
         // Update the cartesian coordinates vector
         this->interpolated_x(s, x);
         // Print the global coordinates. Note: no whitespace after last
         // coordinate or paraview is very unhappy.
         for (unsigned i = 0; i < n - 1; i++)
         {
           file_out << x[i] << " ";
         }
         file_out << x[n - 1];
         // Since unstructured grid always needs 3 components for each
         // point, output 0's by default
         switch (n)
         {
           case 1:
             file_out << " 0"
                      << " 0" << std::endl;
             break;
           case 2:
             file_out << " 0" << std::endl;
             break;
           case 3:
             file_out << std::endl;
             break;
           // Paraview can't handle more than 3 dimensions, output error
           default:
             throw OomphLibError(
               "Printing PlotPoint to .vtu failed; it has >3 dimensions.",
               OOMPH_CURRENT_FUNCTION,
               OOMPH_EXCEPTION_LOCATION);
         }
       }
     }
References get_s_plot(), i, interpolated_x(), j, n, oomph::Node::ndim(), nnode(), node_pt(), nplot_points_paraview(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, PlanarWave::plot(), s, and plotDoE::x.
Referenced by oomph::Mesh::output_fct_paraview(), and oomph::Mesh::output_paraview().
point_output()
void oomph::FiniteElement::point_output (std::ostream & outfile, const Vector< double > & s) inline
Output solution (as defined by point_output_data()) at local cordinates s
     {
       // Get point data
       Vector<double> data;
       this->point_output_data(s, data);
       // Output
       unsigned n = data.size();
       for (unsigned i = 0; i < n; i++)
       {
         outfile << data[i] << " ";
       }
     }
References data, i, n, and point_output_data().
point_output_data()
virtual void oomph::FiniteElement::point_output_data (const Vector< double > & s, Vector< double > & data) inline virtual
Virtual function to write the double precision numbers that appear in a single line of output into the data vector. Empty virtual, can be overloaded for specific elements; used e.g. by LineVisualiser.
Reimplemented in oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::PoissonEquations< DIM >, oomph::PoissonEquations< 1 >, oomph::PoissonEquations< 2 >, oomph::PoissonEquations< 3 >, oomph::NavierStokesEquations< DIM >, oomph::NavierStokesEquations< 2 >, oomph::GeneralisedNewtonianNavierStokesEquations< DIM >, oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations, oomph::AxisymmetricPoroelasticityEquations, and oomph::AxisymmetricNavierStokesEquations.
     {
     }
Referenced by point_output().
position() [1/2]
void oomph::FiniteElement::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const inline virtual
Return the parametrised position of the FiniteElement in its GeomObject incarnation: r(zeta). The position is given by the Eulerian coordinate and the intrinsic coordinate (zeta) is the local coordinate of the element (s) This version of the function returns the position as a function of time t=0: current time; t>0: previous timestep. Works for t=0 but needs to be overloaded if genuine time-dependence is required.
Reimplemented from oomph::GeomObject.
     {
       this->interpolated_x(t, zeta, r);
     }
References interpolated_x(), UniformPSDSelfTest::r, and Eigen::zeta().
position() [2/2]
void oomph::FiniteElement::position (const Vector< double > & zeta, Vector< double > & r) const inline virtual
Return the parametrised position of the FiniteElement in its incarnation as a GeomObject, r(zeta). The position is given by the Eulerian coordinate and the intrinsic coordinate (zeta) is the local coordinate of the element (s).
Implements oomph::GeomObject.
Reimplemented in oomph::YoungLaplaceEquations.
     {
       this->interpolated_x(zeta, r);
     }
References interpolated_x(), and UniformPSDSelfTest::r.
raw_dnodal_position_dt() [1/2]
double oomph::FiniteElement::raw_dnodal_position_dt (const unsigned & n, const unsigned & i) const inline
Return the i-th component of nodal velocity: dx/dt at local node n. Do not use the hanging node representation.
     {
       return node_pt(n)->dx_dt(i);
     }
References oomph::Node::dx_dt(), i, n, and node_pt().
Referenced by oomph::AxisymmetricNavierStokesEquations::fill_in_generic_dresidual_contribution_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_dresidual_contribution_axi_nst(), oomph::AxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), oomph::AxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_lin_axi_nst(), oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::SphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst(), oomph::AxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), and oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates().
raw_dnodal_position_dt() [2/2]
double oomph::FiniteElement::raw_dnodal_position_dt (const unsigned & n, const unsigned & j, const unsigned & i) const inline
Return the i-th component of j-th derivative of nodal position: d^jx/dt^j at node n. Do not use the hanging node representation.
     {
       return node_pt(n)->dx_dt(j, i);
     }
References oomph::Node::dx_dt(), i, j, n, and node_pt().
raw_dnodal_position_gen_dt() [1/2]
double oomph::FiniteElement::raw_dnodal_position_gen_dt (const unsigned & j, const unsigned & n, const unsigned & k, const unsigned & i) const inline
i-th component of j-th time derivative of the generalised position, dx(k,i)/dt at local node n. ‘Type’: k; Coordinate direction: i. Do not use the hanging node representation.
     {
       return node_pt(n)->dx_gen_dt(j, k, i);
     }
References oomph::Node::dx_gen_dt(), i, j, k, n, and node_pt().
raw_dnodal_position_gen_dt() [2/2]
double oomph::FiniteElement::raw_dnodal_position_gen_dt (const unsigned & n, const unsigned & k, const unsigned & i) const inline
i-th component of time derivative (velocity) of the generalised position, dx(k,i)/dt at local node n. ‘Type’: k; Coordinate direction: i. Do not use the hanging node representation.
     {
       return node_pt(n)->dx_gen_dt(k, i);
     }
References oomph::Node::dx_gen_dt(), i, k, n, and node_pt().
Referenced by oomph::KirchhoffLoveBeamEquations::fill_in_contribution_to_residuals_beam(), oomph::KirchhoffLoveShellEquations::fill_in_contribution_to_residuals_shell(), oomph::KirchhoffLoveBeamEquations::get_energy(), oomph::KirchhoffLoveShellEquations::get_strain_and_bend(), and oomph::HermiteBeamElement::output().
raw_nodal_position() [1/2]
double FiniteElement::raw_nodal_position (const unsigned & n, const unsigned & i) const
Return the i-th coordinate at local node n. Do not use the hanging node representation. NOTE: Moved to cc file because of a possible compiler bug in gcc (yes, really!). The move to the cc file avoids inlining which appears to cause problems (only) when compiled with gcc and -O3; offensive "illegal read" is in optimised-out section of code and data that is allegedly illegal is readily readable (by other means) just before this function is called so I can't really see how we could possibly be responsible for this...
//////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////// Return the i-th coordinate at local node n. Do not use the hanging node representation. NOTE: Moved to cc file because of a possible compiler bug in gcc (yes, really!). The move to the cc file avoids inlining which appears to cause problems (only) when compiled with gcc and -O3; offensive "illegal read" is in optimised-out section of code and data that is allegedly illegal is readily readable (by other means) just before this function is called so I can't really see how we could possibly be responsible for this...
   {
     /* oomph_info << "n: "<< n << std::endl; */
     /* oomph_info << "i: "<< i << std::endl; */
     /* oomph_info << "node_pt(n): "<< node_pt(n) << std::endl; */
     /* oomph_info << "node_pt(n)->x(i): "<< node_pt(n)->x(i) << std::endl; */
     // double tmp=node_pt(n)->x(i);
     // oomph_info << "tmp: "<< tmp << std::endl;
     return node_pt(n)->x(i);
   }
References i, n, node_pt(), and oomph::Node::x().
Referenced by oomph::AxisymmetricNavierStokesEquations::fill_in_contribution_to_hessian_vector_products(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_contribution_to_hessian_vector_products(), oomph::AxisymFoepplvonKarmanEquations::fill_in_contribution_to_residuals(), oomph::FoepplvonKarmanEquations::fill_in_contribution_to_residuals(), oomph::AxisymmetricLinearElasticityEquations::fill_in_generic_contribution_to_residuals_axisymmetric_linear_elasticity(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::fill_in_generic_contribution_to_residuals_fourier_decomp_time_harmonic_linear_elasticity(), oomph::AxisymmetricNavierStokesEquations::fill_in_generic_dresidual_contribution_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_dresidual_contribution_axi_nst(), oomph::PolarStreamfunctionEquations::fill_in_generic_residual_contribution(), oomph::SteadyAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_adv_diff(), oomph::AxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), oomph::AxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::FourierDecomposedHelmholtzEquations::fill_in_generic_residual_contribution_fourier_decomposed_helmholtz(), oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_lin_axi_nst(), oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::LinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst(), oomph::PeriodicOrbitEquations::fill_in_generic_residual_contribution_orbit(), oomph::PMLFourierDecomposedHelmholtzEquations::fill_in_generic_residual_contribution_pml_fourier_decomposed_helmholtz(), oomph::SphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), oomph::SphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst(), oomph::AxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::AxisymmetricLinearElasticityEquations::get_strain(), oomph::AxisymFoepplvonKarmanEquations::interpolated_stress(), and oomph::PeriodicOrbitEquations::orbit_output().
raw_nodal_position() [2/2]
double oomph::FiniteElement::raw_nodal_position (const unsigned & t, const unsigned & n, const unsigned & i) const inline
Return the i-th coordinate at local node n, at time level t (t=0: present; t>0: previous time level). Do not use the hanging node representation.
     {
       return node_pt(n)->x(t, i);
     }
References i, n, node_pt(), plotPSD::t, and oomph::Node::x().
raw_nodal_position_gen() [1/2]
double oomph::FiniteElement::raw_nodal_position_gen (const unsigned & n, const unsigned & k, const unsigned & i) const inline
Return the value of the k-th type of the i-th positional variable at the local node n. Do not use the hanging node representation.
     {
       return node_pt(n)->x_gen(k, i);
     }
References i, k, n, node_pt(), and oomph::Node::x_gen().
Referenced by assemble_eulerian_base_vectors(), assemble_local_to_eulerian_jacobian(), assemble_local_to_eulerian_jacobian2(), oomph::KirchhoffLoveBeamEquations::fill_in_contribution_to_residuals_beam(), oomph::KirchhoffLoveShellEquations::fill_in_contribution_to_residuals_shell(), oomph::KirchhoffLoveBeamEquations::get_energy(), oomph::KirchhoffLoveBeamEquations::get_non_unit_tangent(), oomph::KirchhoffLoveShellEquations::get_normal(), oomph::KirchhoffLoveBeamEquations::get_normal(), oomph::KirchhoffLoveShellEquations::get_strain_and_bend(), and local_to_eulerian_mapping_diagonal().
raw_nodal_position_gen() [2/2]
double oomph::FiniteElement::raw_nodal_position_gen (const unsigned & t, const unsigned & n, const unsigned & k, const unsigned & i) const inline
Return the generalised nodal position (type k, i-th variable) at previous timesteps at local node n. Do not use the hanging node representation.
     {
       return node_pt(n)->x_gen(t, k, i);
     }
References i, k, n, node_pt(), plotPSD::t, and oomph::Node::x_gen().
raw_nodal_value() [1/2]
double oomph::FiniteElement::raw_nodal_value (const unsigned & n, const unsigned & i) const inline
Return the i-th value stored at local node n but do NOT take hanging nodes into account
     {
       return node_pt(n)->raw_value(i);
     }
References i, n, node_pt(), and oomph::Node::raw_value().
Referenced by oomph::AxisymmetricNavierStokesEquations::fill_in_contribution_to_hessian_vector_products(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_contribution_to_hessian_vector_products(), oomph::AxisymFoepplvonKarmanEquations::fill_in_contribution_to_residuals(), oomph::FoepplvonKarmanEquations::fill_in_contribution_to_residuals(), oomph::AxisymmetricLinearElasticityEquations::fill_in_generic_contribution_to_residuals_axisymmetric_linear_elasticity(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::fill_in_generic_contribution_to_residuals_fourier_decomp_time_harmonic_linear_elasticity(), oomph::AxisymmetricNavierStokesEquations::fill_in_generic_dresidual_contribution_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_dresidual_contribution_axi_nst(), oomph::AxisymmetricPoroelasticityEquations::fill_in_generic_residual_contribution(), oomph::PolarStreamfunctionEquations::fill_in_generic_residual_contribution(), oomph::SteadyAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_adv_diff(), oomph::AxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), oomph::AxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::FourierDecomposedHelmholtzEquations::fill_in_generic_residual_contribution_fourier_decomposed_helmholtz(), oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_lin_axi_nst(), oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::LinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst(), oomph::PMLFourierDecomposedHelmholtzEquations::fill_in_generic_residual_contribution_pml_fourier_decomposed_helmholtz(), oomph::SphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), oomph::SphericalNavierStokesEquations::fill_in_generic_residual_contribution_spherical_nst(), oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::fill_in_off_diagonal_block_analytic(), oomph::BuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_analytic(), oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::get_body_force_nst(), oomph::FoepplvonKarmanEquations::get_bounded_volume(), oomph::AxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::AxisymmetricLinearElasticityEquations::get_strain(), oomph::AxisymFoepplvonKarmanEquations::interpolated_stress(), oomph::FoepplvonKarmanEquations::interpolated_stress(), oomph::UnsteadyHeatBaseFaceElement< ELEMENT >::interpolated_u(), oomph::MyTaylorHoodElement< DIM >::square_of_l2_norm(), and oomph::LinearisedNavierStokesEquations::strain_rate().
raw_nodal_value() [2/2]
double oomph::FiniteElement::raw_nodal_value (const unsigned & t, const unsigned & n, const unsigned & i) const inline
Return the i-th value stored at local node n, at time level t (t=0: present; t>0 previous timesteps), but do NOT take hanging nodes into account
     {
       return node_pt(n)->raw_value(t, i);
     }
References i, n, node_pt(), oomph::Node::raw_value(), and plotPSD::t.
required_nvalue()
virtual unsigned oomph::FiniteElement::required_nvalue (const unsigned & n) const inline virtual
Number of values that must be stored at local node n by the element. The default is 0, until over-ridden by a particular element. For example, a Poisson equation requires only one value to be stored at each node; 2D Navier–Stokes equations require two values (velocity components) to be stored at each Node (provided that the pressure interpolation is discontinuous).
Reimplemented in oomph::PoroelasticityEquations< 2 >, oomph::DarcyEquations< 2 >, oomph::PoroelasticityEquations< DIM >, oomph::DarcyEquations< DIM >, oomph::AxisymmetricPoroelasticityEquations, oomph::QYoungLaplaceElement< NNODE_1D >, oomph::QWomersleyElement< DIM, NNODE_1D >, oomph::TWomersleyElement< DIM, NNODE_1D >, oomph::QUnsteadyHeatElement< DIM, NNODE_1D >, oomph::QUnsteadyHeatElement< DIM, 3 >, oomph::TUnsteadyHeatElement< DIM, NNODE_1D >, oomph::TimeHarmonicLinearElasticityEquations< DIM >, oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations, oomph::QSteadyAxisymAdvectionDiffusionElement< NNODE_1D >, oomph::QSphericalTaylorHoodElement, oomph::QSphericalCrouzeixRaviartElement, oomph::RefineableQSphericalTaylorHoodElement, oomph::QSphericalAdvectionDiffusionElement< NNODE_1D >, oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, oomph::QUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >, oomph::QTaylorHoodMixedOrderSpaceTimeElement< DIM >, oomph::QTaylorHoodMixedOrderSpaceTimeElement< 2 >, oomph::QTaylorHoodSpaceTimeElement< DIM >, oomph::QTaylorHoodSpaceTimeElement< 2 >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::QTaylorHoodSpaceTimeElement< DIM >, oomph::QTaylorHoodSpaceTimeElement< 2 >, oomph::QTaylorHoodSpaceTimeElement< DIM >, oomph::QTaylorHoodSpaceTimeElement< 2 >, oomph::TPVDElementWithContinuousPressure< DIM >, oomph::QPVDElementWithContinuousPressure< DIM >, oomph::RefineableQPVDElementWithContinuousPressure< DIM >, oomph::TPoroelasticityElement< ORDER >, oomph::RefineablePolarTaylorHoodElement, oomph::PolarTaylorHoodElement, oomph::PolarCrouzeixRaviartElement, oomph::TPoissonElement< DIM, NNODE_1D >, oomph::QSpectralPoissonElement< DIM, NNODE_1D >, oomph::QPoissonElement< DIM, NNODE_1D >, oomph::QPoissonElement< DIM, 2 >, oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >, oomph::TPMLHelmholtzElement< DIM, NNODE_1D >, oomph::QPMLHelmholtzElement< DIM, NNODE_1D >, oomph::QPMLHelmholtzElement< 2, NNODE_1D >, oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::QPMLFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::TTaylorHoodElement< DIM >, oomph::TCrouzeixRaviartElement< DIM >, oomph::PRefineableQCrouzeixRaviartElement< DIM >, oomph::RefineableQTaylorHoodElement< DIM >, oomph::RefineableQTaylorHoodElement< 2 >, oomph::QTaylorHoodElement< DIM >, oomph::QTaylorHoodElement< 2 >, oomph::QCrouzeixRaviartElement< DIM >, oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >, oomph::BuoyantQCrouzeixRaviartElement< DIM >, oomph::RefineableLinearisedQTaylorHoodElement, oomph::LinearisedQTaylorHoodElement, oomph::LinearisedQCrouzeixRaviartElement, oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::QLinearWaveElement< DIM, NNODE_1D >, oomph::LinearElasticityEquations< DIM >, oomph::THelmholtzElement< DIM, NNODE_1D >, oomph::QHelmholtzElement< DIM, NNODE_1D >, oomph::PseudoSolidNodeUpdateElement< TCrouzeixRaviartElement< 2 >, TPVDBubbleEnrichedElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< TTaylorHoodElement< 2 >, TPVDElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< GeneralisedNewtonianAxisymmetricTTaylorHoodElement, TPVDElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< AxisymmetricTTaylorHoodElement, TPVDElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< GeneralisedNewtonianTTaylorHoodElement< 2 >, TPVDElement< 2, 3 > >, oomph::SpectralPeriodicOrbitElement< NNODE_1D >, oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >, oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >, oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >, oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >, oomph::GeneralisedNewtonianQTaylorHoodElement< DIM >, oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >, oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement, oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement, oomph::RefineableGeneralisedNewtonianAxisymmetricQTaylorHoodElement, oomph::GeneralisedNewtonianAxisymmetricQTaylorHoodElement, oomph::GeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement, oomph::TFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::QFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::TFoepplvonKarmanElement< NNODE_1D >, oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >, oomph::QFoepplvonKarmanElement< NNODE_1D >, oomph::QScalarAdvectionElement< DIM, NNODE_1D >, oomph::QScalarAdvectionElement< 1, NNODE_1D >, oomph::QScalarAdvectionElement< 2, NNODE_1D >, oomph::QSpectralScalarAdvectionElement< DIM, NNODE_1D >, oomph::QSpectralScalarAdvectionElement< 1, NNODE_1D >, oomph::QSpectralScalarAdvectionElement< 2, NNODE_1D >, oomph::ScalarAdvectionEquations< DIM >, oomph::EulerEquations< DIM >, oomph::TRaviartThomasDarcyElement< ORDER >, oomph::ProjectableDarcyElement< DARCY_ELEMENT >, oomph::BiharmonicElement< DIM >, oomph::TAxisymmetricPoroelasticityElement< ORDER >, oomph::AxisymmetricTTaylorHoodElement, oomph::AxisymmetricTCrouzeixRaviartElement, oomph::RefineableAxisymmetricQTaylorHoodElement, oomph::AxisymmetricQTaylorHoodElement, oomph::AxisymmetricQCrouzeixRaviartElement, oomph::AxisymmetricLinearElasticityEquations, oomph::AxisymFoepplvonKarmanElement< NNODE_1D >, oomph::AxisymFoepplvonKarmanElement< NNODE_1D >, oomph::QAxisymAdvectionDiffusionElement< NNODE_1D >, oomph::QAxisymAdvectionDiffusionElement< 3 >, oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, oomph::QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, oomph::QAdvectionDiffusionReactionElement< 2, DIM, 3 >, oomph::QGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >, oomph::QAdvectionDiffusionElement< DIM, NNODE_1D >, oomph::QAdvectionDiffusionElement< DIM, 3 >, oomph::PolarStreamfunctionElement, TwoNodePoissonElement, oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, QThermalPVDElement< DIM >, oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::AxisymmetricQAdvectionCrouzeixRaviartElement, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement, oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement, RefineableQAdvectionDiffusionElementWithExternalElement< DIM >, RefineableQCrouzeixRaviartElementWithExternalElement< DIM >, RefineableBuoyantQCrouzeixRaviartElement< DIM >, QHarmonicElement< NNODE_1D >, SSPorousChannelElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::QMultiPoissonElement< DIM, NNODE_1D, NFIELDS >, oomph::HomogenisedLinearElasticityEquations< DIM >, oomph::TLinearHeatAndElasticityElement< DIM, NNODE_1D >, QOrrSommerfeldElement< 1, NNODE_1D >, QHarmonicElement< NNODE_1D >, QComplexHarmonicElement< NNODE_1D >, SSPorousChannelElement, GelfandBratuElement< NNODE_1D >, oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
     {
       return Default_Initial_Nvalue;
     }
References Default_Initial_Nvalue.
Referenced by oomph::GeneralisedElement::assign_local_eqn_numbers(), build_face_element(), oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >::construct_boundary_node(), construct_boundary_node(), oomph::SolidFiniteElement::construct_boundary_node(), oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >::construct_node(), construct_node(), oomph::SolidFiniteElement::construct_node(), and oomph::BiharmonicEquations< DIM >::ndof_types().
reset_after_nodal_fd()
virtual void oomph::FiniteElement::reset_after_nodal_fd () inline protected virtual
Function that is call after the finite differencing of the nodal data. This may be overloaded to reset any dependent variables that may have changed during the finite differencing.
Reimplemented in oomph::FSIWallElement.
 {}
Referenced by fill_in_jacobian_from_nodal_by_fd(), and oomph::RefineableElement::fill_in_jacobian_from_nodal_by_fd().
reset_in_nodal_fd()
virtual void oomph::FiniteElement::reset_in_nodal_fd (const unsigned & i) inline protected virtual
Function called within the finite difference loop for nodal data after the i-th nodal values is reset. The default behaviour is to call the update function.
Reimplemented in oomph::FSIWallElement.
     {
       update_in_nodal_fd(i);
     }
References i, and update_in_nodal_fd().
Referenced by fill_in_jacobian_from_nodal_by_fd(), and oomph::RefineableElement::fill_in_jacobian_from_nodal_by_fd().
s_max()
virtual double oomph::FiniteElement::s_max () const inline virtual
Max. value of local coordinate.
Reimplemented in oomph::TElement< 3, NNODE_1D >, oomph::TElement< 2, NNODE_1D >, oomph::TElement< 1, NNODE_1D >, oomph::QSpectralElement< 3, NNODE_1D >, oomph::QSpectralElement< 2, NNODE_1D >, oomph::QSpectralElement< 1, NNODE_1D >, oomph::QElement< 3, NNODE_1D >, oomph::QElement< 2, NNODE_1D >, oomph::QElement< 1, NNODE_1D >, oomph::QHermiteElement< DIM >, oomph::QHermiteElement< DIM - 1 >, and oomph::SurfaceContactElementBase< ELEMENT >.
     {
       throw OomphLibError("s_max() isn't implemented for this element\n",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
       // Dummy return
       return 0.0;
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::FSI_functions::doc_fsi(), oomph::QElementBase::local_coord_is_valid(), local_fraction_of_node(), oomph::QElementBase::move_local_coord_back_into_element(), oomph::RefineableQElement< 3 >::oc_hang_helper(), and oomph::RefineableQElement< 2 >::quad_hang_helper().
s_min()
virtual double oomph::FiniteElement::s_min () const inline virtual
Min value of local coordinate.
Reimplemented in oomph::TElement< 3, NNODE_1D >, oomph::TElement< 2, NNODE_1D >, oomph::TElement< 1, NNODE_1D >, oomph::QSpectralElement< 3, NNODE_1D >, oomph::QSpectralElement< 2, NNODE_1D >, oomph::QSpectralElement< 1, NNODE_1D >, oomph::QElement< 3, NNODE_1D >, oomph::QElement< 2, NNODE_1D >, oomph::QElement< 1, NNODE_1D >, oomph::QHermiteElement< DIM >, oomph::QHermiteElement< DIM - 1 >, and oomph::SurfaceContactElementBase< ELEMENT >.
     {
       throw OomphLibError("s_min() isn't implemented for this element\n",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
       // Dummy return
       return 0.0;
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::FSI_functions::doc_fsi(), oomph::QElementBase::local_coord_is_valid(), local_fraction_of_node(), oomph::QElementBase::move_local_coord_back_into_element(), oomph::RefineableQElement< 3 >::oc_hang_helper(), and oomph::RefineableQElement< 2 >::quad_hang_helper().
scalar_name_paraview()
virtual std::string oomph::FiniteElement::scalar_name_paraview (const unsigned & i) const inline virtual
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc. Can (should!) be overloaded with more meaningful names in specific elements.
Reimplemented in oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< 2 >, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< 2 >, oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::PoissonEquations< DIM >, oomph::PoissonEquations< 1 >, oomph::PoissonEquations< 2 >, oomph::PoissonEquations< 3 >, oomph::PMLHelmholtzEquations< DIM >, oomph::NavierStokesEquations< DIM >, oomph::NavierStokesEquations< 2 >, oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >, oomph::BuoyantQCrouzeixRaviartElement< DIM >, oomph::HelmholtzEquations< DIM >, oomph::GeneralisedNewtonianNavierStokesEquations< DIM >, oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations, oomph::AxisymmetricPoroelasticityEquations, oomph::AxisymmetricNavierStokesEquations, oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >, oomph::AxisymAdvectionDiffusionEquations, oomph::AdvectionDiffusionEquations< DIM >, oomph::AdvectionDiffusionEquations< 2 >, oomph::AxisymmetricQAdvectionCrouzeixRaviartElement, oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement, oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement, RefineableBuoyantQCrouzeixRaviartElement< DIM >, oomph::MultiPoissonEquations< DIM, NFIELDS >, and oomph::TLinearHeatAndElasticityElement< DIM, NNODE_1D >.
     {
       return "V" + StringConversion::to_string(i);
     }
References i, and oomph::StringConversion::to_string().
Referenced by oomph::Mesh::output_fct_paraview(), and oomph::Mesh::output_paraview().
scalar_value_fct_paraview() [1/2]
virtual void oomph::FiniteElement::scalar_value_fct_paraview (std::ofstream & file_out, const unsigned & i, const unsigned & nplot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const inline virtual
Write values of the i-th scalar field at the plot points. Broken virtual. Needs to be implemented for each new specific element type.
Reimplemented in oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< 2 >, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< 2 >, oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::NavierStokesEquations< DIM >, and oomph::NavierStokesEquations< 2 >.
     {
       throw OomphLibError(
         "This function hasn't been implemented for this element",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
scalar_value_fct_paraview() [2/2]
virtual void oomph::FiniteElement::scalar_value_fct_paraview (std::ofstream & file_out, const unsigned & i, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const inline virtual
Write values of the i-th scalar field at the plot points. Broken virtual. Needs to be implemented for each new specific element type.
Reimplemented in oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< 2 >, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< 2 >, oomph::PoissonEquations< DIM >, oomph::PoissonEquations< 1 >, oomph::PoissonEquations< 2 >, oomph::PoissonEquations< 3 >, and oomph::PMLHelmholtzEquations< DIM >.
     {
       throw OomphLibError(
         "This function hasn't been implemented for this element",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::Mesh::output_fct_paraview().
scalar_value_paraview()
virtual void oomph::FiniteElement::scalar_value_paraview (std::ofstream & file_out, const unsigned & i, const unsigned & nplot) const inline virtual
Write values of the i-th scalar field at the plot points. Broken virtual. Needs to be implemented for each new specific element type.
Reimplemented in oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >, oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< 2 >, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< 2 >, oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::SpaceTimeNavierStokesEquations< DIM >, oomph::PoissonEquations< DIM >, oomph::PoissonEquations< 1 >, oomph::PoissonEquations< 2 >, oomph::PoissonEquations< 3 >, oomph::PMLHelmholtzEquations< DIM >, oomph::NavierStokesEquations< DIM >, oomph::NavierStokesEquations< 2 >, oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >, oomph::BuoyantQCrouzeixRaviartElement< DIM >, oomph::HelmholtzEquations< DIM >, oomph::GeneralisedNewtonianNavierStokesEquations< DIM >, oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations, oomph::AxisymmetricPoroelasticityEquations, oomph::AxisymmetricNavierStokesEquations, oomph::AxisymAdvectionDiffusionEquations, oomph::AdvectionDiffusionEquations< DIM >, oomph::AdvectionDiffusionEquations< 2 >, oomph::AxisymmetricQAdvectionCrouzeixRaviartElement, oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement, oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement, RefineableBuoyantQCrouzeixRaviartElement< DIM >, oomph::MultiPoissonEquations< DIM, NFIELDS >, and oomph::TLinearHeatAndElasticityElement< DIM, NNODE_1D >.
     {
       throw OomphLibError(
         "This function hasn't been implemented for this element",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::Mesh::output_paraview().
self_test()
unsigned FiniteElement::self_test () virtual
Self-test: Check inversion of element & do self-test for GeneralisedElement. Return 0 if OK.
Self-test: Have all internal values been classified as pinned/unpinned? Has pointer to spatial integration scheme been set? Return 0 if OK.
Reimplemented from oomph::GeneralisedElement.
Reimplemented in oomph::YoungLaplaceEquations, oomph::WomersleyEquations< DIM >, oomph::UnsteadyHeatEquations< DIM >, oomph::UnsteadyHeatEquations< 2 >, oomph::SteadyAxisymAdvectionDiffusionEquations, oomph::SphericalAdvectionDiffusionEquations, oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< 2 >, oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >, oomph::SpaceTimeUnsteadyHeatEquations< 2 >, oomph::PoroelasticityEquations< DIM >, oomph::PoroelasticityEquations< 2 >, oomph::PoissonEquations< DIM >, oomph::PoissonEquations< 1 >, oomph::PoissonEquations< 2 >, oomph::PoissonEquations< 3 >, oomph::PMLHelmholtzEquations< DIM >, oomph::PMLFourierDecomposedHelmholtzEquations, oomph::LinearWaveEquations< DIM >, oomph::HelmholtzEquations< DIM >, oomph::FourierDecomposedHelmholtzEquations, oomph::FoepplvonKarmanEquations, oomph::DisplacementBasedFoepplvonKarmanEquations, oomph::DarcyEquations< DIM >, oomph::DarcyEquations< 2 >, oomph::BiharmonicEquations< DIM >, oomph::AxisymmetricPoroelasticityEquations, oomph::AxisymFoepplvonKarmanEquations, oomph::AxisymFoepplvonKarmanEquations, oomph::AxisymAdvectionDiffusionEquations, oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >, oomph::GeneralisedAdvectionDiffusionEquations< DIM >, oomph::GeneralisedAdvectionDiffusionEquations< 2 >, oomph::AdvectionDiffusionEquations< DIM >, oomph::AdvectionDiffusionEquations< 2 >, ModalPRefineableQPoissonElement< DIM >, ModalPoissonEquations< DIM >, TwoNodePoissonElement, and oomph::MultiPoissonEquations< DIM, NFIELDS >.
   {
     // Initialise
     bool passed = true;
     if (GeneralisedElement::self_test() != 0)
     {
       passed = false;
     }
     // Check that pointer to spatial integration scheme has been set
     if (integral_pt() == 0)
     {
       passed = false;
       OomphLibWarning("Pointer to spatial integration scheme has not been set.",
                       "FiniteElement::self_test()",
                       OOMPH_EXCEPTION_LOCATION);
     }
     // If the dimension of the element is zero (point element), there
     // is not jacobian
     const unsigned dim_el = dim();
     if (dim_el > 0)
     {
       // Loop over integration points to check sign of Jacobian
       //-------------------------------------------------------
       // Set the value of n_intpt
       const unsigned n_intpt = integral_pt()->nweight();
       // Set the Vector to hold local coordinates
       Vector<double> s(dim_el);
       // Find the number of local nodes
       const unsigned n_node = nnode();
       const unsigned n_position_type = nnodal_position_type();
       // Set up memory for the shape and test functions
       Shape psi(n_node, n_position_type);
       DShape dpsidx(n_node, dim_el);
       // Jacobian
       double jacobian;
       // Two ways of testing for negative Jacobian for non-FaceElements
       unsigned ntest = 1;
       // For FaceElements checking the Jacobian via dpsidx doesn't
       // make sense
       FiniteElement* tmp_pt = const_cast<FiniteElement*>(this);
       FaceElement* face_el_pt = dynamic_cast<FaceElement*>(tmp_pt);
       if (face_el_pt == 0)
       {
         ntest = 2;
       }
       // For now overwrite -- the stuff above fails for Bretherton.
       // Not sure why.
       ntest = 1;
       // Loop over the integration points
       for (unsigned ipt = 0; ipt < n_intpt; ipt++)
       {
         // Assign values of s
         for (unsigned i = 0; i < dim_el; i++)
         {
           s[i] = integral_pt()->knot(ipt, i);
         }
         // Do tests
         for (unsigned test = 0; test < ntest; test++)
         {
           switch (test)
           {
             case 0:
               // Get the jacobian from the mapping between local and Eulerian
               // coordinates
               jacobian = J_eulerian(s);
               break;
             case 1:
               // Call the geometrical shape functions and derivatives
               // This also computes the Jacobian by a slightly different
               // method
               jacobian = dshape_eulerian_at_knot(ipt, psi, dpsidx);
               break;
             default:
               throw OomphLibError("Never get here",
                                   OOMPH_CURRENT_FUNCTION,
                                   OOMPH_EXCEPTION_LOCATION);
           }
           // Check for a singular jacobian
           if (std::fabs(jacobian) < 1.0e-16)
           {
             std::ostringstream warning_stream;
             warning_stream << "Determinant of Jacobian matrix is zero at ipt "
                            << ipt << std::endl;
             OomphLibWarning(warning_stream.str(),
                             "FiniteElement::self_test()",
                             OOMPH_EXCEPTION_LOCATION);
             passed = false;
             // Skip the next test
             continue;
           }
           // Check sign of Jacobian
           if ((Accept_negative_jacobian == false) && (jacobian < 0.0))
           {
             std::ostringstream warning_stream;
             warning_stream << "Jacobian negative at integration point ipt="
                            << ipt << std::endl;
             warning_stream
               << "If you think that this is what you want you may: "
               << std::endl
               << "set the (static) flag "
               << "FiniteElement::Accept_negative_jacobian to be true"
               << std::endl;
             OomphLibWarning(warning_stream.str(),
                             "FiniteElement::self_test()",
                             OOMPH_EXCEPTION_LOCATION);
             passed = false;
           }
         } // end of loop over two tests
       }
     } // End of non-zero dimension check
     // Return verdict
     if (passed)
     {
       return 0;
     }
     else
     {
       return 1;
     }
   }
References Accept_negative_jacobian, dim(), dshape_eulerian_at_knot(), boost::multiprecision::fabs(), i, integral_pt(), J_eulerian(), oomph::Integral::knot(), nnodal_position_type(), nnode(), oomph::Integral::nweight(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, s, and oomph::GeneralisedElement::self_test().
Referenced by oomph::MultiPoissonEquations< DIM, NFIELDS >::self_test(), oomph::AdvectionDiffusionEquations< DIM >::self_test(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::self_test(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::self_test(), oomph::AxisymAdvectionDiffusionEquations::self_test(), oomph::AxisymFoepplvonKarmanEquations::self_test(), oomph::BiharmonicEquations< DIM >::self_test(), oomph::DisplacementBasedFoepplvonKarmanEquations::self_test(), oomph::FoepplvonKarmanEquations::self_test(), oomph::FourierDecomposedHelmholtzEquations::self_test(), oomph::HelmholtzEquations< DIM >::self_test(), oomph::LinearWaveEquations< DIM >::self_test(), oomph::PMLFourierDecomposedHelmholtzEquations::self_test(), oomph::PMLHelmholtzEquations< DIM >::self_test(), oomph::PoissonEquations< DIM >::self_test(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::self_test(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::self_test(), oomph::SphericalAdvectionDiffusionEquations::self_test(), oomph::SteadyAxisymAdvectionDiffusionEquations::self_test(), oomph::UnsteadyHeatEquations< DIM >::self_test(), oomph::WomersleyEquations< DIM >::self_test(), and oomph::YoungLaplaceEquations::self_test().
set_dimension()
void oomph::FiniteElement::set_dimension (const unsigned & dim) inline
Set the dimension of the element and initially set the dimension of the nodes to be the same as the dimension of the element.
     {
       Elemental_dimension = dim;
       Nodal_dimension = dim;
     }
References dim(), Elemental_dimension, and Nodal_dimension.
Referenced by oomph::QHermiteElement< DIM >::QHermiteElement().
set_integration_scheme()
void FiniteElement::set_integration_scheme (Integral *const & integral_pt) virtual
Set the spatial integration scheme.
Set the spatial integration scheme and also calculate the values of the shape functions and their derivatives w.r.t. the local coordinates, placing the values into storage so that they may be re-used, without recalculation
Reimplemented in oomph::StorableShapeSolidElementBase, oomph::StorableShapeElementBase, oomph::StefanBoltzmannUnsteadyHeatFluxElement< ELEMENT >, and oomph::InterpolateFromIntegralPointsBase.
   {
     // Assign the integration scheme
     Integral_pt = integral_pt;
   }
References Integral_pt, and integral_pt().
Referenced by oomph::DGEulerFaceElement< ELEMENT >::DGEulerFaceElement(), oomph::PointElement::PointElement(), oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement(), oomph::PRefineableQCrouzeixRaviartElement< DIM >::PRefineableQCrouzeixRaviartElement(), oomph::PRefineableQLinearElasticityElement< DIM >::PRefineableQLinearElasticityElement(), oomph::PRefineableQPoissonElement< DIM >::PRefineableQPoissonElement(), oomph::QHermiteElement< DIM >::QHermiteElement(), oomph::InterpolateFromIntegralPointsBase::set_integration_scheme(), oomph::StefanBoltzmannUnsteadyHeatFluxElement< ELEMENT >::set_integration_scheme(), oomph::StorableShapeElementBase::set_integration_scheme(), and oomph::SurfaceContactElementBase< ELEMENT >::SurfaceContactElementBase().
set_macro_elem_pt()
virtual void oomph::FiniteElement::set_macro_elem_pt (MacroElement * macro_elem_pt) inline virtual
Set pointer to macro element – can be overloaded in derived elements to perform additional tasks
Reimplemented in oomph::RefineableSolidQElement< 2 >, oomph::RefineableSolidQElement< 1 >, oomph::RefineableSolidQElement< 3 >, oomph::QSolidElementBase, oomph::QElementBase, and oomph::SolidFiniteElement.
     {
       Macro_elem_pt = macro_elem_pt;
     }
References Macro_elem_pt, and macro_elem_pt().
Referenced by oomph::FishMesh< ELEMENT >::build_mesh(), oomph::ChannelWithLeafletMesh< ELEMENT >::ChannelWithLeafletMesh(), oomph::CollapsibleChannelMesh< ELEMENT >::CollapsibleChannelMesh(), oomph::QuarterPipeMesh< ELEMENT >::QuarterPipeMesh(), oomph::QElementBase::set_macro_elem_pt(), and SimpleRefineableFishMesh< ELEMENT >::SimpleRefineableFishMesh().
set_n_node()
void oomph::FiniteElement::set_n_node (const unsigned & n) inline
Set the number of nodes in the element to n, by resizing the storage for pointers to the Node objects.
     {
       // This should only be done once, in a Node constructor
       //#ifdef PARANOID
       // if(Node_pt)
       // {
       //  OomphLibWarning(
       //   "You are resetting the number of nodes in an element -- Be careful",
       //   "FiniteElement::set_n_node()",
       //   OOMPH_EXCEPTION_LOCATION);
       // }
       //#endif
       // Delete any previous storage to avoid memory leaks
       // This will only happen in very special cases
       delete[] Node_pt;
       // Set the number of nodes
       Nnode = n;
       // Allocate the storage
       Node_pt = new Node*[n];
       // Initialise all the pointers to NULL
       for (unsigned i = 0; i < n; i++)
       {
         Node_pt[i] = 0;
       }
     }
References i, n, Nnode, and Node_pt.
Referenced by oomph::PointElement::PointElement(), and oomph::QHermiteElement< DIM >::QHermiteElement().
set_nnodal_position_type()
void oomph::FiniteElement::set_nnodal_position_type (const unsigned & nposition_type) inline
Set the number of types required to interpolate the coordinate.
     {
       Nnodal_position_type = nposition_type;
     }
References Nnodal_position_type.
Referenced by oomph::ClampedHermiteShellBoundaryConditionElement::ClampedHermiteShellBoundaryConditionElement(), oomph::ClampedSlidingHermiteBeamBoundaryConditionElement::ClampedSlidingHermiteBeamBoundaryConditionElement(), and oomph::QHermiteElement< DIM >::QHermiteElement().
set_nodal_dimension()
void oomph::FiniteElement::set_nodal_dimension (const unsigned & nodal_dim) inline
Set the dimension of the nodes in the element. This will typically only be required when constructing FaceElements or in beam and shell type elements where a lower dimensional surface is embedded in a higher dimensional space.
     {
       Nodal_dimension = nodal_dim;
     }
References Nodal_dimension.
Referenced by oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT >::BackupMeshForProjection(), build_face_element(), oomph::QHermiteElement< DIM >::build_face_element(), oomph::QSpectralElement< 1, NNODE_1D >::build_face_element(), oomph::QSpectralElement< 2, NNODE_1D >::build_face_element(), oomph::QSpectralElement< 3, NNODE_1D >::build_face_element(), oomph::TElement< 1, NNODE_1D >::build_face_element(), oomph::TElement< 2, NNODE_1D >::build_face_element(), oomph::TElement< 3, NNODE_1D >::build_face_element(), oomph::HermiteBeamElement::HermiteBeamElement(), and oomph::HermiteShellElement::HermiteShellElement().
shape()
virtual void oomph::FiniteElement::shape (const Vector< double > & s, Shape & psi) const pure virtual
Calculate the geometric shape functions at local coordinate s. This function must be overloaded for each specific geometric element.
Implemented in oomph::ClampedHermiteShellBoundaryConditionElement, oomph::TElement< 3, NNODE_1D >, oomph::TElement< 2, NNODE_1D >, oomph::TElement< 1, NNODE_1D >, oomph::QSpectralElement< 3, NNODE_1D >, oomph::QSpectralElement< 2, NNODE_1D >, oomph::QSpectralElement< 1, NNODE_1D >, oomph::QElement< 3, NNODE_1D >, oomph::QElement< 2, NNODE_1D >, oomph::QElement< 1, NNODE_1D >, oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >, oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >, oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >, oomph::QHermiteElement< DIM >, oomph::QHermiteElement< DIM - 1 >, oomph::QHermiteElement< DIM >, oomph::QHermiteElement< DIM - 1 >, oomph::QHermiteElement< DIM >, oomph::QHermiteElement< DIM - 1 >, oomph::PointElement, TwoNodeGeometricElement, FixSpineHeightElement, and FixSpineHeightElement.
Referenced by oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::add_element_contribution_to_aux_integral(), oomph::AdvectionDiffusionEquations< DIM >::dinterpolated_u_adv_diff_ddata(), oomph::RefineableAdvectionDiffusionEquations< DIM >::dinterpolated_u_adv_diff_ddata(), oomph::RefineableAxisymAdvectionDiffusionEquations::dinterpolated_u_adv_diff_ddata(), oomph::RefineableSphericalAdvectionDiffusionEquations::dinterpolated_u_adv_diff_ddata(), oomph::SphericalAdvectionDiffusionEquations::dinterpolated_u_adv_diff_ddata(), oomph::SteadyAxisymAdvectionDiffusionEquations::dinterpolated_u_adv_diff_ddata(), oomph::AxisymAdvectionDiffusionEquations::dinterpolated_u_axi_adv_diff_ddata(), oomph::AxisymmetricNavierStokesEquations::dinterpolated_u_axi_nst_ddata(), oomph::RefineableAxisymmetricNavierStokesEquations::dinterpolated_u_axi_nst_ddata(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::dinterpolated_u_axi_nst_ddata(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::dinterpolated_u_axi_nst_ddata(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::dinterpolated_u_nst_ddata(), oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::dinterpolated_u_nst_ddata(), oomph::NavierStokesEquations< DIM >::dinterpolated_u_nst_ddata(), oomph::RefineableNavierStokesEquations< DIM >::dinterpolated_u_nst_ddata(), oomph::SpaceTimeNavierStokesEquations< DIM >::dinterpolated_u_nst_ddata(), oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::dinterpolated_u_nst_ddata(), oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >::dinterpolated_u_nst_ddata(), oomph::Z2ErrorEstimator::doc_flux(), oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >::dposition_dt(), oomph::NodeElementSolidOnlyMortaringElement::fill_in_contribution_to_jacobian_mortared_nodes(), oomph::SolidFiniteElement::fill_in_generic_jacobian_for_solid_ic(), oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::get_body_force_nst(), oomph::Z2ErrorEstimator::get_element_errors(), oomph::ProjectableAdvectionDiffusionReactionElement< ADR_ELEMENT >::get_field(), oomph::ProjectableAxisymLinearElasticityElement< AXISYM_LINEAR_ELAST_ELEMENT >::get_field(), oomph::ProjectableAxisymmetricTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::get_field(), oomph::ProjectableDisplacementBasedFoepplvonKarmanElement< FVK_ELEMENT >::get_field(), oomph::ProjectableFoepplvonKarmanElement< FVK_ELEMENT >::get_field(), oomph::ProjectableFourierDecomposedHelmholtzElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >::get_field(), oomph::GeneralisedNewtonianProjectableAxisymmetricTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::get_field(), oomph::ProjectableGeneralisedNewtonianTaylorHoodElement< TAYLOR_HOOD_ELEMENT >::get_field(), oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::get_field(), oomph::ProjectableHelmholtzElement< HELMHOLTZ_ELEMENT >::get_field(), oomph::ProjectableLinearElasticityElement< LINEAR_ELAST_ELEMENT >::get_field(), oomph::ProjectablePMLFourierDecomposedHelmholtzElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >::get_field(), oomph::ProjectablePMLHelmholtzElement< HELMHOLTZ_ELEMENT >::get_field(), oomph::ProjectablePMLTimeHarmonicLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::get_field(), oomph::ProjectablePoissonElement< POISSON_ELEMENT >::get_field(), oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::get_field(), oomph::ProjectableUnsteadyHeatMixedOrderSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::get_field(), oomph::ProjectableTimeHarmonicFourierDecomposedLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::get_field(), oomph::ProjectableTimeHarmonicLinearElasticityElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >::get_field(), oomph::ProjectableUnsteadyHeatElement< UNSTEADY_HEAT_ELEMENT >::get_field(), oomph::SurfaceMeltElement< ELEMENT >::get_interpolated_lagrange_p(), oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::get_interpolated_values(), oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::get_interpolated_values(), oomph::RefineableAxisymmetricQTaylorHoodElement::get_interpolated_values(), oomph::RefineableAxisymmetricQCrouzeixRaviartElement::get_interpolated_values(), oomph::RefineableGeneralisedNewtonianAxisymmetricQTaylorHoodElement::get_interpolated_values(), oomph::RefineableGeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement::get_interpolated_values(), oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::get_interpolated_values(), oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::get_interpolated_values(), oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::get_interpolated_values(), oomph::RefineableLinearElasticityEquations< DIM >::get_interpolated_values(), oomph::RefineableLinearisedQCrouzeixRaviartElement::get_interpolated_values(), oomph::RefineableLinearisedQTaylorHoodElement::get_interpolated_values(), oomph::RefineableQTaylorHoodElement< DIM >::get_interpolated_values(), oomph::RefineableQCrouzeixRaviartElement< DIM >::get_interpolated_values(), oomph::PRefineableQCrouzeixRaviartElement< DIM >::get_interpolated_values(), oomph::RefineablePolarTaylorHoodElement::get_interpolated_values(), oomph::RefineablePolarCrouzeixRaviartElement::get_interpolated_values(), oomph::RefineableQSphericalTaylorHoodElement::get_interpolated_values(), oomph::RefineableQSphericalCrouzeixRaviartElement::get_interpolated_values(), oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >::get_interpolated_values(), oomph::RefineablePolarStreamfunctionEquations::get_interpolated_values(), oomph::RefineableAdvectionDiffusionEquations< DIM >::get_interpolated_values(), oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::get_interpolated_values(), oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >::get_interpolated_values(), oomph::RefineableAxisymAdvectionDiffusionEquations::get_interpolated_values(), oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::get_interpolated_values(), oomph::RefineableHelmholtzEquations< DIM >::get_interpolated_values(), oomph::RefineableLinearWaveEquations< DIM >::get_interpolated_values(), oomph::RefineablePMLHelmholtzEquations< DIM >::get_interpolated_values(), oomph::RefineablePoissonEquations< DIM >::get_interpolated_values(), oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::get_interpolated_values(), oomph::RefineableSpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::get_interpolated_values(), oomph::RefineableSphericalAdvectionDiffusionEquations::get_interpolated_values(), oomph::RefineableUnsteadyHeatEquations< DIM >::get_interpolated_values(), oomph::RefineableYoungLaplaceEquations::get_interpolated_values(), oomph::PMLHelmholtzPowerElement< ELEMENT >::global_flux_contribution(), oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >::global_power_contribution(), oomph::HelmholtzBCElementBase< ELEMENT >::global_power_contribution(), oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::global_power_contribution(), oomph::PMLHelmholtzPowerElement< ELEMENT >::global_power_contribution(), oomph::SurfactantTransportInterfaceElement::interpolated_C(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::interpolated_c_adv_diff_react(), oomph::SolubleSurfactantTransportInterfaceElement::interpolated_C_bulk(), oomph::AxisymmetricLinearElasticityEquationsBase::interpolated_d2u_dt2_axisymmetric_linear_elasticity(), oomph::LinearWaveEquations< DIM >::interpolated_d2u_dt2_lin_wave(), oomph::AxisymmetricPoroelasticityEquations::interpolated_du_dt(), oomph::AxisymmetricLinearElasticityEquationsBase::interpolated_du_dt_axisymmetric_linear_elasticity(), oomph::LinearWaveEquations< DIM >::interpolated_du_dt_lin_wave(), oomph::UnsteadyHeatEquations< DIM >::interpolated_du_dt_ust_heat(), oomph::AxisymmetricNavierStokesEquations::interpolated_dudt_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::interpolated_dudt_axi_nst(), interpolated_dxdt(), oomph::PerturbedSpineLinearisedAxisymmetricFluidInterfaceElement< ELEMENT >::interpolated_H(), oomph::SolubleSurfactantTransportInterfaceElement::interpolated_M(), oomph::SurfaceMeltElement< ELEMENT >::interpolated_melt_rate(), oomph::LinearisedAxisymmetricNavierStokesEquations::interpolated_nodal_position_perturbation_lin_axi_nst(), oomph::PolarStreamfunctionEquations::interpolated_streamfunction(), oomph::YoungLaplaceEquations::interpolated_u(), oomph::LinearisedAxisymmetricFluidInterfaceElement::interpolated_u(), oomph::FluidInterfaceElement::interpolated_u(), oomph::UnsteadyHeatBaseFaceElement< ELEMENT >::interpolated_u(), oomph::AxisymmetricPoroelasticityEquations::interpolated_u(), oomph::PoroelasticityEquations< DIM >::interpolated_u(), oomph::DGFaceElement::interpolated_u(), oomph::AdvectionDiffusionEquations< DIM >::interpolated_u_adv_diff(), oomph::SteadyAxisymAdvectionDiffusionEquations::interpolated_u_adv_diff(), oomph::AxisymAdvectionDiffusionEquations::interpolated_u_axi_adv_diff(), oomph::AxisymmetricNavierStokesEquations::interpolated_u_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::interpolated_u_axi_nst(), oomph::AxisymmetricLinearElasticityEquationsBase::interpolated_u_axisymmetric_linear_elasticity(), oomph::BiharmonicEquations< DIM >::interpolated_u_biharmonic(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::interpolated_u_cons_adv_diff(), oomph::FourierDecomposedHelmholtzEquations::interpolated_u_fourier_decomposed_helmholtz(), oomph::AxisymFoepplvonKarmanEquations::interpolated_u_fvk(), oomph::HelmholtzEquations< DIM >::interpolated_u_helmholtz(), oomph::LinearisedAxisymmetricNavierStokesEquations::interpolated_u_lin_axi_nst(), oomph::LinearWaveEquations< DIM >::interpolated_u_lin_wave(), oomph::LinearSurfaceContactElement< ELEMENT >::interpolated_u_linear_elasticity(), oomph::HomogenisedLinearElasticityEquationsBase::interpolated_u_linear_elasticity(), oomph::LinearElasticityEquationsBase< DIM >::interpolated_u_linear_elasticity(), oomph::LinearisedAxisymmetricNavierStokesEquations::interpolated_u_linearised_axi_nst(), oomph::LinearisedNavierStokesEquations::interpolated_u_linearised_nst(), oomph::MultiPoissonEquations< DIM, NFIELDS >::interpolated_u_multi_poisson(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::interpolated_u_nst(), oomph::NavierStokesEquations< DIM >::interpolated_u_nst(), oomph::SpaceTimeNavierStokesEquations< DIM >::interpolated_u_nst(), oomph::PMLFourierDecomposedHelmholtzEquations::interpolated_u_pml_fourier_decomposed_helmholtz(), oomph::PMLHelmholtzEquations< DIM >::interpolated_u_pml_helmholtz(), oomph::PolarNavierStokesEquations::interpolated_u_pnst(), oomph::PoissonEquations< DIM >::interpolated_u_poisson(), oomph::SphericalAdvectionDiffusionEquations::interpolated_u_spherical_adv_diff(), oomph::SphericalNavierStokesEquations::interpolated_u_spherical_nst(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::interpolated_u_time_harmonic_fourier_decomposed_linear_elasticity(), oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::interpolated_u_time_harmonic_linear_elasticity(), oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::interpolated_u_time_harmonic_linear_elasticity(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::interpolated_u_ust_heat(), oomph::UnsteadyHeatEquations< DIM >::interpolated_u_ust_heat(), oomph::WomersleyEquations< DIM >::interpolated_u_womersley(), oomph::PolarStreamfunctionEquations::interpolated_velocity(), oomph::PolarStreamfunctionEquations::interpolated_vorticity(), oomph::AxisymFoepplvonKarmanEquations::interpolated_w_fvk(), oomph::DisplacementBasedFoepplvonKarmanEquations::interpolated_w_fvk(), oomph::FoepplvonKarmanEquations::interpolated_w_fvk(), interpolated_x(), oomph::SolidFiniteElement::interpolated_xi(), interpolated_zeta(), oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::interpolating_basis(), oomph::RefineableAxisymmetricQTaylorHoodElement::interpolating_basis(), oomph::RefineableGeneralisedNewtonianAxisymmetricQTaylorHoodElement::interpolating_basis(), oomph::RefineableLinearisedQTaylorHoodElement::interpolating_basis(), oomph::RefineableQSphericalTaylorHoodElement::interpolating_basis(), oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::interpolating_basis(), oomph::RefineableElement::interpolating_basis(), oomph::RefineableQTaylorHoodElement< DIM >::interpolating_basis(), oomph::RefineablePolarTaylorHoodElement::interpolating_basis(), oomph::RefineableQPVDElementWithContinuousPressure< DIM >::interpolating_basis(), oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::interpolating_basis(), oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >::interpolating_basis(), oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::jacobian_and_shape_of_field(), oomph::UnsteadyHeatFluxPseudoMeltElement< ELEMENT >::output(), oomph::AxisymmetricLinearElasticityTractionElement< ELEMENT >::output(), oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::output(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::output(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::output(), oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >::output_integration_points(), oomph::LinearisedAxisymmetricNavierStokesEquations::output_veloc(), oomph::AxisymmetricNavierStokesEquations::output_veloc(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::output_veloc(), oomph::LinearisedNavierStokesEquations::output_veloc(), oomph::PolarNavierStokesEquations::output_veloc(), oomph::SphericalNavierStokesEquations::output_veloc(), oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >::position(), oomph::NodeElementSolidOnlyMortaringElement::position_in_element(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >::residual_for_projection(), oomph::ProjectableDarcyElement< DARCY_ELEMENT >::residual_for_projection(), oomph::ProjectableElement< ELEMENT >::residual_for_projection(), oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::scalar_value_paraview(), oomph::AlgebraicElementBase::setup_algebraic_node_update(), oomph::MGSolver< DIM >::setup_interpolation_matrices_unstructured(), oomph::HelmholtzMGPreconditioner< DIM >::setup_interpolation_matrices_unstructured(), oomph::UnsteadyHeatBaseFaceElement< ELEMENT >::shape_and_test(), oomph::UnsteadyHeatFluxPseudoMeltElement< ELEMENT >::shape_and_test(), oomph::AdvectionDiffusionFluxElement< ELEMENT >::shape_and_test(), oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::shape_and_test(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::shape_and_test(), oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >::shape_and_test(), oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::shape_and_test(), oomph::HelmholtzFluxElement< ELEMENT >::shape_and_test(), oomph::LinearWaveFluxElement< ELEMENT >::shape_and_test(), oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::shape_and_test(), oomph::HelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::shape_and_test(), oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::shape_and_test(), oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::shape_and_test(), oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >::shape_and_test(), oomph::PMLHelmholtzFluxElement< ELEMENT >::shape_and_test(), oomph::PoissonFluxElement< ELEMENT >::shape_and_test(), oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::shape_and_test(), oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::shape_and_test(), oomph::UnsteadyHeatFluxElement< ELEMENT >::shape_and_test(), shape_at_knot(), oomph::SurfactantTransportInterfaceElement::sigma(), and oomph::HelmholtzBCElementBase< ELEMENT >::test_only().
shape_at_knot()
void FiniteElement::shape_at_knot (const unsigned & ipt, Shape & psi) const virtual
Return the geometric shape function at the ipt-th integration point
Return the shape function stored at the ipt-th integration point.
Reimplemented in oomph::StorableShapeElementBase.
   {
     // Find the dimension of the element
     const unsigned el_dim = dim();
     // Storage for the local coordinates of the integration point
     Vector<double> s(el_dim);
     // Set the local coordinate
     for (unsigned i = 0; i < el_dim; i++)
     {
       s[i] = integral_pt()->knot(ipt, i);
     }
     // Get the shape function
     shape(s, psi);
   }
References dim(), el_dim, i, integral_pt(), oomph::Integral::knot(), s, and shape().
Referenced by oomph::DGFaceElement::add_flux_contributions(), oomph::ImposeImpenetrabilityElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(), oomph::ImposeParallelOutflowElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(), oomph::AxisymmetricNavierStokesEquations::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::SphericalNavierStokesEquations::get_pressure_and_velocity_mass_matrix_diagonal(), oomph::SolubleSurfactantTransportInterfaceElement::integrated_C(), oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::integrated_C_and_M(), oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >::integrated_C_and_M(), oomph::SolubleSurfactantTransportInterfaceElement::l2_norm_of_height(), oomph::InterpolateFromIntegralPointsBase::pre_compute_ipt_to_node_mapping(), oomph::StorableShapeElementBase::pre_compute_shape_at_knots(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::set_boundary_shape_geom_object_pt(), oomph::PolarStreamfunctionTractionElement< ELEMENT >::shape_and_test_at_knot(), oomph::NavierStokesFluxControlElement< ELEMENT >::shape_and_test_at_knot(), oomph::AdvectionDiffusionFluxElement< ELEMENT >::shape_and_test_at_knot(), oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::shape_and_test_at_knot(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::shape_and_test_at_knot(), oomph::FourierDecomposedHelmholtzFluxElement< ELEMENT >::shape_and_test_at_knot(), oomph::HelmholtzFluxElement< ELEMENT >::shape_and_test_at_knot(), oomph::FourierDecomposedHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::shape_and_test_at_knot(), oomph::HelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::shape_and_test_at_knot(), oomph::PMLHelmholtzFluxFromNormalDisplacementBCElement< HELMHOLTZ_BULK_ELEMENT, ELASTICITY_BULK_ELEMENT >::shape_and_test_at_knot(), oomph::NavierStokesTractionElement< ELEMENT >::shape_and_test_at_knot(), oomph::PMLFourierDecomposedHelmholtzFluxElement< ELEMENT >::shape_and_test_at_knot(), oomph::PMLHelmholtzFluxElement< ELEMENT >::shape_and_test_at_knot(), oomph::PoissonFluxElement< ELEMENT >::shape_and_test_at_knot(), oomph::PolarNavierStokesTractionElement< ELEMENT >::shape_and_test_at_knot(), oomph::PolarStressIntegralElement< ELEMENT >::shape_and_test_at_knot(), oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::shape_and_test_at_knot(), oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >::shape_and_test_at_knot(), oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >::shape_and_test_at_knot(), oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::shape_and_test_at_knot(), and oomph::StorableShapeElementBase::shape_at_knot().
size()
double FiniteElement::size () const
Calculate the size of the element (length, area, volume,...) in Eulerian computational coordinates. Use suitably overloaded compute_physical_size() function to compute the actual size (taking into account factors such as 2pi or radii the integrand) – such function can only be implemented on an equation-by-equation basis.
Calculate the size of the element (in Eulerian computational coordinates. Use suitably overloaded compute_physical_size() function to compute the actual size (taking into account factors such as 2pi or radii the integrand). Such function can only be implemented on an equation-by-equation basis.
   {
     // Initialise the sum to zero
     double sum = 0.0;
     // Loop over the integration points
     const unsigned n_intpt = integral_pt()->nweight();
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Get the value of the Jacobian of the mapping to global coordinates
       double J = J_eulerian_at_knot(ipt);
       // Add the product to the sum
       sum += w * J;
     }
     // Return the answer
     return (sum);
   }
References integral_pt(), J, J_eulerian_at_knot(), oomph::Integral::nweight(), w, and oomph::Integral::weight().
Referenced by oomph::RefineableTetgenMesh< ELEMENT >::adapt(), oomph::RefineableTriangleMesh< ELEMENT >::compute_area_target(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::compute_areas(), oomph::RefineableTetgenMesh< ELEMENT >::compute_volume_target(), oomph::RefineableTetMeshBase::compute_volume_target(), oomph::FaceElement::continuous_tangent_and_outer_unit_normal(), oomph::GmshTetScaffoldMesh::create_mesh_from_msh_file(), TetmeshPoissonProblem< ELEMENT >::doc_solution(), RefineableQCrouzeixRaviartElementWithTwoExternalElement< DIM >::get_dbody_force_nst_dexternal_element_data(), QCrouzeixRaviartElementWithTwoExternalElement< DIM >::get_dbody_force_nst_dexternal_element_data(), oomph::MyTaylorHoodElement< DIM >::output(), oomph::StefanBoltzmannRadiationBase::output_stefan_boltzmann_radiation_rays(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::pin_all_non_pressure_dofs(), oomph::NavierStokesEquations< DIM >::pin_all_non_pressure_dofs(), oomph::SpaceTimeNavierStokesEquations< DIM >::pin_all_non_pressure_dofs(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::pin_all_non_pressure_dofs(), and oomph::Mesh::total_size().
tecplot_zone_string()
virtual std::string oomph::FiniteElement::tecplot_zone_string (const unsigned & nplot) const inline virtual
Return string for tecplot zone header (when plotting nplot points in each "coordinate direction")
Reimplemented in oomph::TElement< 3, NNODE_1D >, oomph::TElement< 2, NNODE_1D >, oomph::TElement< 1, NNODE_1D >, oomph::QSpectralElement< 3, NNODE_1D >, oomph::QSpectralElement< 2, NNODE_1D >, oomph::QSpectralElement< 1, NNODE_1D >, oomph::QElement< 3, NNODE_1D >, oomph::QElement< 2, NNODE_1D >, oomph::QElement< 1, NNODE_1D >, oomph::QHermiteElement< DIM >, oomph::QHermiteElement< DIM - 1 >, oomph::QHermiteElement< DIM >, oomph::QHermiteElement< DIM - 1 >, oomph::QHermiteElement< DIM >, and oomph::QHermiteElement< DIM - 1 >.
     {
       throw OomphLibError(
         "tecplot_zone_string(...) is not implemented for this element\n",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
       return "dummy return";
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::BiharmonicEquations< DIM >::compute_error(), UnstructuredFluidProblem< ELEMENT >::doc_boundary_coordinates(), oomph::Mesh::doc_boundary_coordinates(), oomph::Z2ErrorEstimator::doc_flux(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solid_boundary_coordinates(), UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solid_boundary_coordinates(), oomph::PolarNavierStokesEquations::full_output(), oomph::SphericalNavierStokesEquations::full_output(), oomph::AxisymFoepplvonKarmanEquations::output(), oomph::NonlinearSurfaceContactElement< ELEMENT >::output(), oomph::LinearSurfaceContactElement< ELEMENT >::output(), oomph::UnsteadyHeatFluxPseudoMeltElement< ELEMENT >::output(), oomph::PolarStreamfunctionEquations::output(), oomph::AxisymmetricLinearElasticityEquations::output(), oomph::AxisymmetricLinearElasticityTractionElement< ELEMENT >::output(), oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >::output(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::output(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::output(), oomph::FSILinearisedAxisymPoroelasticTractionElement< POROELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >::output(), oomph::FluidInterfaceElement::output(), oomph::SurfactantTransportInterfaceElement::output(), oomph::DisplacementBasedFoepplvonKarmanEquations::output(), oomph::FoepplvonKarmanEquations::output(), oomph::FourierDecomposedHelmholtzEquations::output(), oomph::NavierStokesSurfaceDragTorqueElement< ELEMENT >::output(), oomph::PMLFourierDecomposedHelmholtzEquations::output(), oomph::SolidTractionElement< ELEMENT >::output(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::output(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::output(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::output(), oomph::YoungLaplaceEquations::output(), oomph::LinearisedAxisymmetricNavierStokesEquations::output(), oomph::THomogenisedLinearElasticityElement< DIM, NNODE_1D >::output(), oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::output(), oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >::output(), oomph::MyTaylorHoodElement< DIM >::output(), oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::output(), oomph::AxisymAdvectionDiffusionEquations::output(), oomph::AxisymmetricNavierStokesEquations::output(), oomph::AxisymmetricPoroelasticityEquations::output(), oomph::BiharmonicEquations< DIM >::output(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::output(), oomph::LinearisedNavierStokesEquations::output(), oomph::BuoyantQCrouzeixRaviartElement< DIM >::output(), oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::output(), oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::output(), oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::output(), oomph::PMLTimeHarmonicLinearElasticityTractionElement< ELEMENT >::output(), oomph::PoissonFluxElement< ELEMENT >::output(), oomph::PolarNavierStokesEquations::output(), oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::output(), oomph::ProjectableUnsteadyHeatMixedOrderSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::output(), oomph::SphericalAdvectionDiffusionEquations::output(), oomph::SphericalNavierStokesEquations::output(), oomph::SteadyAxisymAdvectionDiffusionEquations::output(), oomph::TimeHarmonicLinearElasticityTractionElement< ELEMENT >::output(), oomph::ProjectableUnsteadyHeatElement< UNSTEADY_HEAT_ELEMENT >::output(), oomph::AxisymFoepplvonKarmanEquations::output_fct(), oomph::DisplacementBasedFoepplvonKarmanEquations::output_fct(), oomph::FoepplvonKarmanEquations::output_fct(), oomph::FourierDecomposedHelmholtzEquations::output_fct(), oomph::PMLFourierDecomposedHelmholtzEquations::output_fct(), oomph::YoungLaplaceEquations::output_fct(), oomph::AxisymAdvectionDiffusionEquations::output_fct(), oomph::AxisymmetricLinearElasticityEquations::output_fct(), oomph::AxisymmetricNavierStokesEquations::output_fct(), oomph::AxisymmetricPoroelasticityEquations::output_fct(), oomph::BiharmonicEquations< DIM >::output_fct(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::output_fct(), oomph::PolarNavierStokesEquations::output_fct(), oomph::SphericalAdvectionDiffusionEquations::output_fct(), oomph::SphericalNavierStokesEquations::output_fct(), oomph::SteadyAxisymAdvectionDiffusionEquations::output_fct(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::output_fct(), oomph::BiharmonicEquations< DIM >::output_fluid_velocity(), oomph::FourierDecomposedHelmholtzEquations::output_real(), oomph::PMLFourierDecomposedHelmholtzEquations::output_real(), oomph::FourierDecomposedHelmholtzEquations::output_real_fct(), oomph::PMLFourierDecomposedHelmholtzEquations::output_real_fct(), oomph::LinearisedAxisymmetricNavierStokesEquations::output_veloc(), oomph::AxisymmetricNavierStokesEquations::output_veloc(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::output_veloc(), oomph::LinearisedNavierStokesEquations::output_veloc(), oomph::PolarNavierStokesEquations::output_veloc(), oomph::SphericalNavierStokesEquations::output_veloc(), oomph::SphericalNavierStokesEquations::output_vorticity(), oomph::FaceElement::output_zeta(), oomph::MGSolver< DIM >::plot(), oomph::Multi_domain_functions::setup_bulk_elements_adjacent_to_face_mesh(), and TFaceTestProblem< ELEMENT >::TFaceTestProblem().
transform_derivatives()
void FiniteElement::transform_derivatives (const DenseMatrix< double > & inverse_jacobian, DShape & dbasis) const protected virtual
Convert derivative w.r.t.local coordinates to derivatives w.r.t the coordinates used to assemble the inverse_jacobian passed in the mapping. On entry, dbasis must contain the basis function derivatives w.r.t. the local coordinates; it will contain the derivatives w.r.t. the new coordinates on exit. This is virtual so that it may be overloaded if desired for efficiency reasons.
Convert derivatives w.r.t local coordinates to derivatives w.r.t the coordinates used to assemble the inverse jacobian mapping passed as inverse_jacobian. The derivatives passed in dbasis will be modified in this function from dbasisds to dbasisdX.
Reimplemented in oomph::DiagQHermiteElement< DIM >.
   {
     // Find the number of basis functions and basis function types
     const unsigned n_basis = dbasis.nindex1();
     const unsigned n_basis_type = dbasis.nindex2();
     // Find the dimension of the array (Must be the elemental dimension)
     const unsigned n_dim = dim();
     // Allocate temporary (stack) storage of the dimension of the element
     double new_derivatives[n_dim];
     // Loop over the number of basis functions
     for (unsigned l = 0; l < n_basis; l++)
     {
       // Loop over type of basis functions
       for (unsigned k = 0; k < n_basis_type; k++)
       {
         // Loop over the coordinates
         for (unsigned j = 0; j < n_dim; j++)
         {
           // Zero the new transformed derivatives
           new_derivatives[j] = 0.0;
           // Do premultiplication by inverse jacobian
           for (unsigned i = 0; i < n_dim; i++)
           {
             new_derivatives[j] += inverse_jacobian(j, i) * dbasis(l, k, i);
           }
         }
         // We now copy the new derivatives into the shape functions
         for (unsigned j = 0; j < n_dim; j++)
         {
           dbasis(l, k, j) = new_derivatives[j];
         }
       }
     }
   }
References dim(), i, j, k, oomph::DShape::nindex1(), and oomph::DShape::nindex2().
Referenced by oomph::AxisymmetricTCrouzeixRaviartElement::dpshape_and_dptest_eulerian_axi_nst(), oomph::AxisymmetricTTaylorHoodElement::dpshape_and_dptest_eulerian_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement::dpshape_and_dptest_eulerian_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement::dpshape_and_dptest_eulerian_axi_nst(), dshape_eulerian(), dshape_eulerian_at_knot(), oomph::SolidFiniteElement::dshape_lagrangian(), oomph::SolidFiniteElement::dshape_lagrangian_at_knot(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::get_flux(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::interpolated_du_dt_nst(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::interpolated_du_dt_ust_heat(), oomph::AxisymmetricPoroelasticityEquations::transform_basis(), and transform_second_derivatives_template().
transform_derivatives_diagonal()
void FiniteElement::transform_derivatives_diagonal (const DenseMatrix< double > & inverse_jacobian, DShape & dbasis) const protected
Convert derivative w.r.t local coordinates to derivatives w.r.t the coordinates used to assemble the inverse jacobian passed in the mapping, assuming that the coordinates are aligned in the direction of the local coordinates. On entry dbasis must contain the derivatives of the basis functions w.r.t. the local coordinates; it will contain the derivatives w.r.t. the new coordinates. are converted into the new using the mapping inverse_jacobian.
Convert derivatives w.r.t local coordinates to derivatives w.r.t the coordinates used to assemble the inverse jacobian mapping passed as inverse_jacobian, assuming that the mapping is diagonal. This merely saves a few loops, but is probably worth it.
   {
     // Find the number of basis functions and basis function types
     const unsigned n_basis = dbasis.nindex1();
     const unsigned n_basis_type = dbasis.nindex2();
     // Find the dimension of the array (must be the elemental dimension)
     const unsigned n_dim = dim();
     // Loop over the number of basis functions
     for (unsigned l = 0; l < n_basis; l++)
     {
       // Loop over type of basis functions
       for (unsigned k = 0; k < n_basis_type; k++)
       {
         // Loop over the coordinates
         for (unsigned j = 0; j < n_dim; j++)
         {
           dbasis(l, k, j) *= inverse_jacobian(j, j);
         }
       }
     }
   }
References dim(), j, k, oomph::DShape::nindex1(), and oomph::DShape::nindex2().
Referenced by oomph::DiagQHermiteElement< DIM >::transform_derivatives(), and transform_second_derivatives_diagonal().
transform_second_derivatives()
void FiniteElement::transform_second_derivatives (const DenseMatrix< double > & jacobian, const DenseMatrix< double > & inverse_jacobian, const DenseMatrix< double > & jacobian2, DShape & dbasis, DShape & d2basis) const protected virtual
Convert derivatives and second derivatives w.r.t. local coordiantes to derivatives and second derivatives w.r.t. the coordinates used to assemble the jacobian, inverse jacobian and jacobian2 passed to the function. By default this function will call transform_second_derivatives_template<>(...) using the dimension of the element as the template parameter. It is virtual so that it can be overloaded by a specific element to save using a switch statement. Optionally, the element writer may wish to use the transform_second_derivatives_diagonal<>(...) function On entry dbasis and d2basis must contain the derivatives w.r.t. the local coordinates; on exit they will be the derivatives w.r.t. the transformed coordinates.
Convert derivatives and second derivatives w.r.t. local coordiantes to derivatives and second derivatives w.r.t. the coordinates used to assemble the jacobian, inverse jacobian and jacobian2 passed to the function. This is a template-free general interface, that should be overloaded for efficiency
Reimplemented in oomph::DiagQHermiteElement< DIM >, oomph::QHermiteElement< DIM >, and oomph::QHermiteElement< DIM - 1 >.
   {
     // Find the dimension of the element
     const unsigned el_dim = dim();
     // Choose the appropriate function based on the dimension of the element
     switch (el_dim)
     {
       case 1:
         transform_second_derivatives_template<1>(
           jacobian, inverse_jacobian, jacobian2, dbasis, d2basis);
         break;
       case 2:
         transform_second_derivatives_template<2>(
           jacobian, inverse_jacobian, jacobian2, dbasis, d2basis);
         break;
       case 3:
         throw OomphLibError("Not implemented yet ... maybe one day",
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
         // transform_second_derivatives_template<3>(dphids,d2phids,jacobian,
         //                                         inverse_jacobian,jacobian2,
         //                                         dphidX,d2phidX);
         break;
         // Catch-all default case: issue warning and die
       default:
         std::ostringstream error_stream;
         error_stream << "Dimension of the element must be 1,2 or 3, not "
                      << el_dim << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
   }
References dim(), el_dim, OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by d2shape_eulerian(), d2shape_eulerian_at_knot(), oomph::SolidFiniteElement::d2shape_lagrangian(), and oomph::SolidFiniteElement::d2shape_lagrangian_at_knot().
transform_second_derivatives_diagonal() [1/3]
template<> void oomph::FiniteElement::transform_second_derivatives_diagonal (const DenseMatrix< double > & jacobian, const DenseMatrix< double > & inverse_jacobian, const DenseMatrix< double > & jacobian2, DShape & dbasis, DShape & d2basis) const protected
Convert derivatives and second derivatives w.r.t local coordinates to derivatives w.r.t. the coordinates used to assemble the jacobian, inverse_jacobian and jacobian 2 passed. This must be specialised for each dimension, otherwise it gets very ugly Specialisation to one dimension.
   {
     FiniteElement::transform_second_derivatives_template<1>(
       jacobian, inverse_jacobian, jacobian2, dbasis, d2basis);
   }
transform_second_derivatives_diagonal() [2/3]
template<> void oomph::FiniteElement::transform_second_derivatives_diagonal (const DenseMatrix< double > & jacobian, const DenseMatrix< double > & inverse_jacobian, const DenseMatrix< double > & jacobian2, DShape & dbasis, DShape & d2basis) const protected
Convert second derivatives w.r.t. local coordinates to second derivatives w.r.t. the coordinates passed in the tensor coordinate. Specialised to two spatial dimension
   {
     // Find the number of basis functions and basis function types
     const unsigned n_basis = dbasis.nindex1();
     const unsigned n_basis_type = dbasis.nindex2();
     // Again we assume that there are no cross terms and that  coordinate
     // i depends only upon local coordinate i
     // Now calculate the DShape d2phidx
     for (unsigned l = 0; l < n_basis; l++)
     {
       for (unsigned k = 0; k < n_basis_type; k++)
       {
         // Second derivatives
         d2basis(l, k, 0) =
           d2basis(l, k, 0) / (jacobian(0, 0) * jacobian(0, 0)) -
           dbasis(l, k, 0) * jacobian2(0, 0) /
             (jacobian(0, 0) * jacobian(0, 0) * jacobian(0, 0));
         d2basis(l, k, 1) =
           d2basis(l, k, 1) / (jacobian(1, 1) * jacobian(1, 1)) -
           dbasis(l, k, 1) * jacobian2(1, 1) /
             (jacobian(1, 1) * jacobian(1, 1) * jacobian(1, 1));
         d2basis(l, k, 2) = d2basis(l, k, 2) / (jacobian(0, 0) * jacobian(1, 1));
       }
     }
     // Assemble the first derivatives
     transform_derivatives_diagonal(inverse_jacobian, dbasis);
   }
References k, oomph::DShape::nindex1(), oomph::DShape::nindex2(), and transform_derivatives_diagonal().
transform_second_derivatives_diagonal() [3/3]
template<unsigned DIM> void oomph::FiniteElement::transform_second_derivatives_diagonal (const DenseMatrix< double > & jacobian, const DenseMatrix< double > & inverse_jacobian, const DenseMatrix< double > & jacobian2, DShape & dbasis, DShape & d2basis) const protected
Convert derivatives and second derivatives w.r.t. local coordinates to derivatives and second derivatives w.r.t. the coordinates used to asssmble the jacobian, inverse jacobian and jacobian2 passed in the mapping. This version of the function assumes that the local coordinates are aligned with the global coordinates, i.e. the jacobians are diagonal On entry dbasis and d2basis must contain the derivatives w.r.t. the local coordinates; on exit they will be the derivatives w.r.t. the transformed coordinates.
transform_second_derivatives_template() [1/3]
template<> void oomph::FiniteElement::transform_second_derivatives_template (const DenseMatrix< double > & jacobian, const DenseMatrix< double > & inverse_jacobian, const DenseMatrix< double > & jacobian2, DShape & dbasis, DShape & d2basis) const protected
Convert derivatives and second derivatives w.r.t local coordinates to derivatives w.r.t. the coordinates used to assemble the jacobian, inverse_jacobian and jacobian 2 passed. This must be specialised for each dimension, otherwise it gets very ugly Specialisation to one dimension.
   {
     // Find the number of basis functions and basis function types
     const unsigned n_basis = dbasis.nindex1();
     const unsigned n_basis_type = dbasis.nindex2();
     // The second derivatives are easy, because there can be no mixed terms
     // Loop over number of basis functions
     for (unsigned l = 0; l < n_basis; l++)
     {
       // Loop over number of basis function types
       for (unsigned k = 0; k < n_basis_type; k++)
       {
         d2basis(l, k, 0) =
           d2basis(l, k, 0) / (jacobian(0, 0) * jacobian(0, 0))
           // Second term comes from taking d/dx of (dpsi/ds / dx/ds)
           - dbasis(l, k, 0) * jacobian2(0, 0) /
               (jacobian(0, 0) * jacobian(0, 0) * jacobian(0, 0));
       }
     }
     // Assemble the first derivatives (do this last so that we don't
     // overwrite the dphids before we use it in the above)
     transform_derivatives(inverse_jacobian, dbasis);
   }
References k, oomph::DShape::nindex1(), oomph::DShape::nindex2(), and transform_derivatives().
transform_second_derivatives_template() [2/3]
template<> void oomph::FiniteElement::transform_second_derivatives_template (const DenseMatrix< double > & jacobian, const DenseMatrix< double > & inverse_jacobian, const DenseMatrix< double > & jacobian2, DShape & dbasis, DShape & d2basis) const protected
Convert derivatives and second derivatives w.r.t local coordinates to derivatives w.r.t. the coordinates used to assemble the jacobian, inverse_jacobian and jacobian 2 passed. This must be specialised for each dimension, otherwise it gets very ugly. Specialisation to two spatial dimensions
   {
     // Find the number of basis functions and basis function types
     const unsigned n_basis = dbasis.nindex1();
     const unsigned n_basis_type = dbasis.nindex2();
     // Calculate the determinant
     const double det =
       jacobian(0, 0) * jacobian(1, 1) - jacobian(0, 1) * jacobian(1, 0);
     // Second derivatives ... the approach taken here is to construct
     // dphidX/ds which can then be used to calculate the second derivatives
     // using the relationship d/dX = inverse_jacobian*d/ds
     double ddetds[2];
     ddetds[0] =
       jacobian2(0, 0) * jacobian(1, 1) + jacobian(0, 0) * jacobian2(2, 1) -
       jacobian2(0, 1) * jacobian(1, 0) - jacobian(0, 1) * jacobian2(2, 0);
     ddetds[1] =
       jacobian2(2, 0) * jacobian(1, 1) + jacobian(0, 0) * jacobian2(1, 1) -
       jacobian2(2, 1) * jacobian(1, 0) - jacobian(0, 1) * jacobian2(1, 0);
     // Calculate the derivatives of the inverse jacobian wrt the local
     // coordinates
     double dinverse_jacobiands[2][2][2];
     dinverse_jacobiands[0][0][0] =
       jacobian2(2, 1) / det - jacobian(1, 1) * ddetds[0] / (det * det);
     dinverse_jacobiands[0][1][0] =
       -jacobian2(0, 1) / det + jacobian(0, 1) * ddetds[0] / (det * det);
     dinverse_jacobiands[1][0][0] =
       -jacobian2(2, 0) / det + jacobian(1, 0) * ddetds[0] / (det * det);
     dinverse_jacobiands[1][1][0] =
       jacobian2(0, 0) / det - jacobian(0, 0) * ddetds[0] / (det * det);
     dinverse_jacobiands[0][0][1] =
       jacobian2(1, 1) / det - jacobian(1, 1) * ddetds[1] / (det * det);
     dinverse_jacobiands[0][1][1] =
       -jacobian2(2, 1) / det + jacobian(0, 1) * ddetds[1] / (det * det);
     dinverse_jacobiands[1][0][1] =
       -jacobian2(1, 0) / det + jacobian(1, 0) * ddetds[1] / (det * det);
     dinverse_jacobiands[1][1][1] =
       jacobian2(2, 0) / det - jacobian(0, 0) * ddetds[1] / (det * det);
     // Set up derivatives of dpsidx wrt local coordinates
     DShape dphidXds0(n_basis, n_basis_type, 2),
       dphidXds1(n_basis, n_basis_type, 2);
     for (unsigned l = 0; l < n_basis; l++)
     {
       for (unsigned k = 0; k < n_basis_type; k++)
       {
         for (unsigned j = 0; j < 2; j++)
         {
           // Note that we can't have an inner loop because of the
           // convention I've chosen for the mixed derivatives!
           dphidXds0(l, k, j) = dinverse_jacobiands[j][0][0] * dbasis(l, k, 0) +
                                dinverse_jacobiands[j][1][0] * dbasis(l, k, 1) +
                                inverse_jacobian(j, 0) * d2basis(l, k, 0) +
                                inverse_jacobian(j, 1) * d2basis(l, k, 2);
           dphidXds1(l, k, j) = dinverse_jacobiands[j][0][1] * dbasis(l, k, 0) +
                                dinverse_jacobiands[j][1][1] * dbasis(l, k, 1) +
                                inverse_jacobian(j, 0) * d2basis(l, k, 2) +
                                inverse_jacobian(j, 1) * d2basis(l, k, 1);
         }
       }
     }
     // Now calculate the DShape d2phidX
     for (unsigned l = 0; l < n_basis; l++)
     {
       for (unsigned k = 0; k < n_basis_type; k++)
       {
         // Zero dpsidx
         for (unsigned j = 0; j < 3; j++)
         {
           d2basis(l, k, j) = 0.0;
         }
         // Do premultiplication by inverse jacobian
         for (unsigned i = 0; i < 2; i++)
         {
           d2basis(l, k, i) = inverse_jacobian(i, 0) * dphidXds0(l, k, i) +
                              inverse_jacobian(i, 1) * dphidXds1(l, k, i);
         }
         // Calculate mixed derivative term
         d2basis(l, k, 2) += inverse_jacobian(0, 0) * dphidXds0(l, k, 1) +
                             inverse_jacobian(0, 1) * dphidXds1(l, k, 1);
       }
     }
     // Assemble the first derivatives second, so that we don't
     // overwrite dphids
     transform_derivatives(inverse_jacobian, dbasis);
   }
References i, j, k, oomph::DShape::nindex1(), oomph::DShape::nindex2(), and transform_derivatives().
transform_second_derivatives_template() [3/3]
template<unsigned DIM> void oomph::FiniteElement::transform_second_derivatives_template (const DenseMatrix< double > & jacobian, const DenseMatrix< double > & inverse_jacobian, const DenseMatrix< double > & jacobian2, DShape & dbasis, DShape & d2basis) const protected
Convert derivatives and second derivatives w.r.t. local coordinates to derivatives and second derivatives w.r.t. the coordinates used to asssmble the jacobian, inverse jacobian and jacobian2 passed in the mapping. This is templated by dimension because the method of calculation varies significantly with the dimension. On entry dbasis and d2basis must contain the derivatives w.r.t. the local coordinates; on exit they will be the derivatives w.r.t. the transformed coordinates.
update_before_nodal_fd()
virtual void oomph::FiniteElement::update_before_nodal_fd () inline protected virtual
Function that is called before the finite differencing of any nodal data. This may be overloaded to update any dependent data before finite differencing takes place.
 {}
Referenced by fill_in_jacobian_from_nodal_by_fd(), and oomph::RefineableElement::fill_in_jacobian_from_nodal_by_fd().
update_in_nodal_fd()
virtual void oomph::FiniteElement::update_in_nodal_fd (const unsigned & i) inline protected virtual
Function called within the finite difference loop for nodal data after a change in the i-th nodal value.
Reimplemented in oomph::FSIWallElement.
 {}
Referenced by fill_in_jacobian_from_nodal_by_fd(), oomph::RefineableElement::fill_in_jacobian_from_nodal_by_fd(), and reset_in_nodal_fd().
vertex_node_pt()
virtual Node* oomph::FiniteElement::vertex_node_pt (const unsigned & j) const inline virtual
Pointer to the j-th vertex node in the element. Broken virtual function in "pure" finite elements.
Reimplemented in oomph::BrickElementBase, oomph::QuadElementBase, oomph::LineElementBase, oomph::ElementWithZ2ErrorEstimator, oomph::RefineableQYoungLaplaceElement< NNODE_1D >, oomph::TUnsteadyHeatElement< DIM, NNODE_1D >, oomph::RefineableQUnsteadyHeatElement< DIM, NNODE_1D >, oomph::TTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::RefineableQTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::TTimeHarmonicFourierDecomposedLinearElasticityElement< NNODE_1D >, oomph::RefineableQSphericalCrouzeixRaviartElement, oomph::RefineableQSphericalTaylorHoodElement, oomph::RefineableQSphericalAdvectionDiffusionElement< NNODE_1D >, oomph::RefineableQSphericalAdvectionDiffusionElement< 3 >, oomph::RefineableQUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, oomph::RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, oomph::RefineableQUnsteadyHeatSpaceTimeElement< SPATIAL_DIM, NNODE_1D >, oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >, oomph::TPVDElementWithContinuousPressure< DIM >, oomph::TPVDBubbleEnrichedElement< DIM, NNODE_1D >, oomph::TPVDElement< DIM, NNODE_1D >, oomph::RefineableQPVDElementWithContinuousPressure< DIM >, oomph::RefineableQPVDElementWithPressure< DIM >, oomph::RefineableQPVDElement< DIM, NNODE_1D >, oomph::RefineablePolarCrouzeixRaviartElement, oomph::RefineablePolarTaylorHoodElement, oomph::TPoissonElement< DIM, NNODE_1D >, oomph::RefineableQSpectralPoissonElement< DIM, NNODE_1D >, oomph::PRefineableQPoissonElement< DIM >, oomph::RefineableQPoissonElement< DIM, NNODE_1D >, oomph::TPMLTimeHarmonicLinearElasticityElement< DIM, NNODE_1D >, oomph::TPMLHelmholtzElement< DIM, NNODE_1D >, oomph::RefineableQPMLHelmholtzElement< DIM, NNODE_1D >, oomph::RefineableQPMLHelmholtzElement< 2, NNODE_1D >, oomph::TPMLFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::TTaylorHoodElement< DIM >, oomph::TCrouzeixRaviartElement< DIM >, oomph::PRefineableQCrouzeixRaviartElement< DIM >, oomph::RefineableQCrouzeixRaviartElement< DIM >, oomph::RefineableQCrouzeixRaviartElement< 2 >, oomph::RefineableQTaylorHoodElement< DIM >, oomph::RefineableQTaylorHoodElement< 2 >, oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >, oomph::RefineableLinearisedQTaylorHoodElement, oomph::RefineableLinearisedQCrouzeixRaviartElement, oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement, oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement, oomph::RefineableQLinearWaveElement< DIM, NNODE_1D >, oomph::TLinearElasticityElement< DIM, NNODE_1D >, oomph::PRefineableQLinearElasticityElement< DIM >, oomph::RefineableQLinearElasticityElement< DIM, NNODE_1D >, oomph::THelmholtzElement< DIM, NNODE_1D >, oomph::RefineableQHelmholtzElement< DIM, NNODE_1D >, oomph::TElement< 3, NNODE_1D >, oomph::TElement< 2, NNODE_1D >, oomph::TElement< 1, NNODE_1D >, oomph::QSpectralElement< 3, NNODE_1D >, oomph::QSpectralElement< 2, NNODE_1D >, oomph::QSpectralElement< 1, NNODE_1D >, oomph::QElement< 3, NNODE_1D >, oomph::QElement< 2, NNODE_1D >, oomph::QElement< 1, NNODE_1D >, oomph::PseudoSolidNodeUpdateElement< TCrouzeixRaviartElement< 2 >, TPVDBubbleEnrichedElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< TTaylorHoodElement< 2 >, TPVDElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< GeneralisedNewtonianAxisymmetricTTaylorHoodElement, TPVDElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< AxisymmetricTTaylorHoodElement, TPVDElement< 2, 3 > >, oomph::PseudoSolidNodeUpdateElement< GeneralisedNewtonianTTaylorHoodElement< 2 >, TPVDElement< 2, 3 > >, oomph::SpectralPeriodicOrbitElement< NNODE_1D >, oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >, oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >, oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >, oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >, oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >, oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement, oomph::GeneralisedNewtonianAxisymmetricTCrouzeixRaviartElement, oomph::RefineableGeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement, oomph::RefineableGeneralisedNewtonianAxisymmetricQTaylorHoodElement, oomph::TFourierDecomposedHelmholtzElement< NNODE_1D >, oomph::TFoepplvonKarmanElement< NNODE_1D >, oomph::TDisplacementBasedFoepplvonKarmanElement< NNODE_1D >, oomph::TRaviartThomasDarcyElement< ORDER >, oomph::TAxisymmetricPoroelasticityElement< ORDER >, oomph::AxisymmetricTTaylorHoodElement, oomph::AxisymmetricTCrouzeixRaviartElement, oomph::RefineableAxisymmetricQCrouzeixRaviartElement, oomph::RefineableAxisymmetricQTaylorHoodElement, oomph::TAxisymmetricLinearElasticityElement< NNODE_1D >, oomph::RefineableQGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >, oomph::RefineableQAxisymAdvectionDiffusionElement< NNODE_1D >, oomph::RefineableQAxisymAdvectionDiffusionElement< 3 >, oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, oomph::RefineableQAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, oomph::RefineableQAdvectionDiffusionReactionElement< 2, DIM, 3 >, oomph::RefineableQSUPGAdvectionDiffusionElement< DIM, NNODE_1D >, oomph::RefineableQGeneralisedAdvectionDiffusionElement< DIM, NNODE_1D >, oomph::RefineableQAdvectionDiffusionElement< DIM, NNODE_1D >, oomph::RefineableQAdvectionDiffusionElement< DIM, 3 >, oomph::RefineablePolarStreamfunctionElement, ModalPRefineableQPoissonElement< DIM >, oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement, oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement, oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement, RefineableBuoyantQCrouzeixRaviartElement< DIM >, oomph::TLinearHeatAndElasticityElement< DIM, NNODE_1D >, oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement, and oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement.
     {
       std::string error_msg = "Not implemented for FiniteElement.";
       throw OomphLibError(
         error_msg, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
Referenced by oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::compute_stabilisation_parameter(), oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::vertex_node_pt(), oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::vertex_node_pt(), oomph::RefineablePolarStreamfunctionElement::vertex_node_pt(), oomph::RefineableQAdvectionDiffusionElement< DIM, NNODE_1D >::vertex_node_pt(), oomph::RefineableQSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::vertex_node_pt(), oomph::RefineableQAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::vertex_node_pt(), oomph::RefineableAxisymmetricQTaylorHoodElement::vertex_node_pt(), oomph::RefineableAxisymmetricQCrouzeixRaviartElement::vertex_node_pt(), oomph::RefineableGeneralisedNewtonianAxisymmetricQTaylorHoodElement::vertex_node_pt(), oomph::RefineableGeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement::vertex_node_pt(), oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::vertex_node_pt(), oomph::RefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::vertex_node_pt(), oomph::PRefineableGeneralisedNewtonianQCrouzeixRaviartElement< DIM >::vertex_node_pt(), oomph::RefineableQHelmholtzElement< DIM, NNODE_1D >::vertex_node_pt(), oomph::RefineableQLinearElasticityElement< DIM, NNODE_1D >::vertex_node_pt(), oomph::PRefineableQLinearElasticityElement< DIM >::vertex_node_pt(), oomph::RefineableQLinearWaveElement< DIM, NNODE_1D >::vertex_node_pt(), oomph::RefineableLinearisedQCrouzeixRaviartElement::vertex_node_pt(), oomph::RefineableLinearisedQTaylorHoodElement::vertex_node_pt(), oomph::RefineableQTaylorHoodElement< DIM >::vertex_node_pt(), oomph::RefineableQCrouzeixRaviartElement< DIM >::vertex_node_pt(), oomph::PRefineableQCrouzeixRaviartElement< DIM >::vertex_node_pt(), oomph::RefineableQPMLHelmholtzElement< DIM, NNODE_1D >::vertex_node_pt(), oomph::RefineableQPoissonElement< DIM, NNODE_1D >::vertex_node_pt(), oomph::PRefineableQPoissonElement< DIM >::vertex_node_pt(), oomph::RefineableQSpectralPoissonElement< DIM, NNODE_1D >::vertex_node_pt(), oomph::RefineablePolarTaylorHoodElement::vertex_node_pt(), oomph::RefineablePolarCrouzeixRaviartElement::vertex_node_pt(), oomph::RefineableQPVDElement< DIM, NNODE_1D >::vertex_node_pt(), oomph::RefineableQPVDElementWithPressure< DIM >::vertex_node_pt(), oomph::RefineableQPVDElementWithContinuousPressure< DIM >::vertex_node_pt(), oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::vertex_node_pt(), oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >::vertex_node_pt(), oomph::RefineableQUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::vertex_node_pt(), oomph::RefineableQSphericalTaylorHoodElement::vertex_node_pt(), oomph::RefineableQSphericalCrouzeixRaviartElement::vertex_node_pt(), and oomph::RefineableQUnsteadyHeatElement< DIM, NNODE_1D >::vertex_node_pt().
write_paraview_offsets()
virtual void oomph::FiniteElement::write_paraview_offsets (std::ofstream & file_out, const unsigned & nplot, unsigned & offset_sum) const inline virtual
Return the offsets for the paraview sub-elements. Broken virtual. Needs to be implemented for each new geometric element type; see http://www.vtk.org/VTK/img/file-formats.pdf
Reimplemented in oomph::TElement< 3, NNODE_1D >, oomph::TElement< 2, NNODE_1D >, oomph::TElement< 1, NNODE_1D >, oomph::QElement< 3, NNODE_1D >, oomph::QElement< 2, NNODE_1D >, and oomph::QElement< 1, NNODE_1D >.
     {
       throw OomphLibError(
         "This function hasn't been implemented for this element",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::Mesh::output_fct_paraview(), and oomph::Mesh::output_paraview().
write_paraview_output_offset_information()
virtual void oomph::FiniteElement::write_paraview_output_offset_information (std::ofstream & file_out, const unsigned & nplot, unsigned & counter) const inline virtual
Fill in the offset information for paraview plot. Broken virtual. Needs to be implemented for each new geometric element type; see http://www.vtk.org/VTK/img/file-formats.pdf
Reimplemented in oomph::TElement< 3, NNODE_1D >, oomph::TElement< 2, NNODE_1D >, oomph::TElement< 1, NNODE_1D >, oomph::QElement< 3, NNODE_1D >, oomph::QElement< 2, NNODE_1D >, and oomph::QElement< 1, NNODE_1D >.
     {
       throw OomphLibError(
         "This function hasn't been implemented for this element",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::Mesh::output_fct_paraview(), and oomph::Mesh::output_paraview().
write_paraview_type()
virtual void oomph::FiniteElement::write_paraview_type (std::ofstream & file_out, const unsigned & nplot) const inline virtual
Return the paraview element type. Broken virtual. Needs to be implemented for each new geometric element type; see http://www.vtk.org/VTK/img/file-formats.pdf
Reimplemented in oomph::TElement< 3, NNODE_1D >, oomph::TElement< 2, NNODE_1D >, oomph::TElement< 1, NNODE_1D >, oomph::QElement< 3, NNODE_1D >, oomph::QElement< 2, NNODE_1D >, and oomph::QElement< 1, NNODE_1D >.
     {
       throw OomphLibError(
         "This function hasn't been implemented for this element",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::Mesh::output_fct_paraview(), and oomph::Mesh::output_paraview().
write_tecplot_zone_footer() [1/2]
virtual void oomph::FiniteElement::write_tecplot_zone_footer (FILE * file_pt, const unsigned & nplot) const inline virtual
Add tecplot zone "footer" to C-style output. (when plotting nplot points in each "coordinate direction"). Empty by default – can be used, e.g., to add FE connectivity lists to elements that need it.
Reimplemented in oomph::TElement< 3, NNODE_1D >, and oomph::TElement< 2, NNODE_1D >.
                                                                         {};
write_tecplot_zone_footer() [2/2]
virtual void oomph::FiniteElement::write_tecplot_zone_footer (std::ostream & outfile, const unsigned & nplot) const inline virtual
Add tecplot zone "footer" to output stream (when plotting nplot points in each "coordinate direction"). Empty by default – can be used, e.g., to add FE connectivity lists to elements that need it.
Reimplemented in oomph::TElement< 3, NNODE_1D >, and oomph::TElement< 2, NNODE_1D >.
                                                                         {};
Referenced by oomph::BiharmonicEquations< DIM >::compute_error(), oomph::Mesh::doc_boundary_coordinates(), oomph::Z2ErrorEstimator::doc_flux(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solid_boundary_coordinates(), UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solid_boundary_coordinates(), oomph::SphericalNavierStokesEquations::full_output(), oomph::AxisymFoepplvonKarmanEquations::output(), oomph::NonlinearSurfaceContactElement< ELEMENT >::output(), oomph::LinearSurfaceContactElement< ELEMENT >::output(), oomph::PolarStreamfunctionEquations::output(), oomph::AxisymmetricLinearElasticityEquations::output(), oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >::output(), oomph::FSILinearisedAxisymPoroelasticTractionElement< POROELASTICITY_BULK_ELEMENT, NAVIER_STOKES_BULK_ELEMENT >::output(), oomph::FluidInterfaceElement::output(), oomph::DisplacementBasedFoepplvonKarmanEquations::output(), oomph::FoepplvonKarmanEquations::output(), oomph::FourierDecomposedHelmholtzEquations::output(), oomph::NavierStokesSurfaceDragTorqueElement< ELEMENT >::output(), oomph::PMLFourierDecomposedHelmholtzEquations::output(), oomph::SolidTractionElement< ELEMENT >::output(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::output(), oomph::YoungLaplaceEquations::output(), oomph::LinearisedAxisymmetricNavierStokesEquations::output(), oomph::THomogenisedLinearElasticityElement< DIM, NNODE_1D >::output(), oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::output(), oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::output(), oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::output(), oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement::output(), oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >::output(), oomph::MyTaylorHoodElement< DIM >::output(), oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::output(), oomph::AxisymAdvectionDiffusionEquations::output(), oomph::AxisymmetricNavierStokesEquations::output(), oomph::AxisymmetricPoroelasticityEquations::output(), oomph::BiharmonicEquations< DIM >::output(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::output(), oomph::LinearisedNavierStokesEquations::output(), oomph::BuoyantQCrouzeixRaviartElement< DIM >::output(), oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::output(), oomph::RefineableAdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::output(), oomph::AdvectionDiffusionBoussinesqElement< AD_ELEMENT, NST_ELEMENT >::output(), oomph::PMLTimeHarmonicLinearElasticityTractionElement< ELEMENT >::output(), oomph::PoissonFluxElement< ELEMENT >::output(), oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::output(), oomph::ProjectableUnsteadyHeatMixedOrderSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >::output(), oomph::SphericalAdvectionDiffusionEquations::output(), oomph::SphericalNavierStokesEquations::output(), oomph::SteadyAxisymAdvectionDiffusionEquations::output(), oomph::TimeHarmonicLinearElasticityTractionElement< ELEMENT >::output(), oomph::ProjectableUnsteadyHeatElement< UNSTEADY_HEAT_ELEMENT >::output(), oomph::AxisymFoepplvonKarmanEquations::output_fct(), oomph::DisplacementBasedFoepplvonKarmanEquations::output_fct(), oomph::FoepplvonKarmanEquations::output_fct(), oomph::FourierDecomposedHelmholtzEquations::output_fct(), oomph::PMLFourierDecomposedHelmholtzEquations::output_fct(), oomph::YoungLaplaceEquations::output_fct(), oomph::AxisymAdvectionDiffusionEquations::output_fct(), oomph::AxisymmetricLinearElasticityEquations::output_fct(), oomph::AxisymmetricNavierStokesEquations::output_fct(), oomph::AxisymmetricPoroelasticityEquations::output_fct(), oomph::BiharmonicEquations< DIM >::output_fct(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::output_fct(), oomph::PolarNavierStokesEquations::output_fct(), oomph::SphericalAdvectionDiffusionEquations::output_fct(), oomph::SphericalNavierStokesEquations::output_fct(), oomph::SteadyAxisymAdvectionDiffusionEquations::output_fct(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::output_fct(), oomph::BiharmonicEquations< DIM >::output_fluid_velocity(), oomph::FourierDecomposedHelmholtzEquations::output_real(), oomph::PMLFourierDecomposedHelmholtzEquations::output_real(), oomph::FourierDecomposedHelmholtzEquations::output_real_fct(), oomph::PMLFourierDecomposedHelmholtzEquations::output_real_fct(), oomph::LinearisedAxisymmetricNavierStokesEquations::output_veloc(), oomph::AxisymmetricNavierStokesEquations::output_veloc(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::output_veloc(), oomph::LinearisedNavierStokesEquations::output_veloc(), oomph::PolarNavierStokesEquations::output_veloc(), oomph::SphericalNavierStokesEquations::output_veloc(), oomph::SphericalNavierStokesEquations::output_vorticity(), oomph::FaceElement::output_zeta(), oomph::Multi_domain_functions::setup_bulk_elements_adjacent_to_face_mesh(), and TFaceTestProblem< ELEMENT >::TFaceTestProblem().
zeta_nodal()
virtual double oomph::FiniteElement::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const inline virtual
Specify the values of the "global" intrinsic coordinate, zeta, of a compound geometric object (a mesh of elements) when the element is viewied as a sub-geometric object. The default assumption is that the element will be treated as a sub-geometric object in a bulk Mesh of other elements (geometric objects). The "global" coordinate of the compound geometric object is simply the Eulerian coordinate, x. The second default assumption is that the coordinate zeta will be stored at the nodes and interpolated using the shape functions of the element. This function returns the value of zeta stored at local node n, where k is the type of coordinate and i is the coordinate direction. The function is virtual so that it can be overloaded by different types of element: FaceElements and SolidFiniteElements
Reimplemented in oomph::YoungLaplaceContactAngleElement< ELEMENT >, oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >, oomph::UnsteadyHeatFluxElement< ELEMENT >, oomph::TimeHarmonicLinearElasticityTractionElement< ELEMENT >, oomph::TimeHarmonicFourierDecomposedLinearElasticityTractionElement< ELEMENT >, oomph::SteadyAxisymAdvectionDiffusionFluxElement< ELEMENT >, oomph::SphericalAdvectionDiffusionFluxElement< ELEMENT >, oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >, oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >, oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >, oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >, oomph::PoroelasticityFaceElement< ELEMENT >, oomph::PoissonFluxElement< ELEMENT >, oomph::PMLTimeHarmonicLinearElasticityTractionElement< ELEMENT >, oomph::PMLHelmholtzFluxElement< ELEMENT >, oomph::PMLHelmholtzPowerElement< ELEMENT >, oomph::PMLFourierDecomposedHelmholtzPowerMonitorElement< ELEMENT >, oomph::NavierStokesSurfacePowerElement< ELEMENT >, oomph::NavierStokesSurfaceDragTorqueElement< ELEMENT >, oomph::ImposeParallelOutflowElement< ELEMENT >, oomph::ImposeImpenetrabilityElement< ELEMENT >, oomph::NavierStokesTractionElement< ELEMENT >, oomph::LinearWaveFluxElement< ELEMENT >, oomph::LinearElasticityTractionElement< ELEMENT >, oomph::HelmholtzFluxElement< ELEMENT >, oomph::HelmholtzBCElementBase< ELEMENT >, oomph::ProjectableElement< ELEMENT >, oomph::ProjectableElement< FVK_ELEMENT >, oomph::ProjectableElement< AXISYM_LINEAR_ELAST_ELEMENT >, oomph::ProjectableElement< UNSTEADY_HEAT_ELEMENT >, oomph::ProjectableElement< LINEAR_ELAST_ELEMENT >, oomph::ProjectableElement< CROUZEIX_RAVIART_ELEMENT >, oomph::ProjectableElement< HELMHOLTZ_ELEMENT >, oomph::ProjectableElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >, oomph::ProjectableElement< TAYLOR_HOOD_ELEMENT >, oomph::ProjectableElement< PVD_ELEMENT >, oomph::ProjectableElement< ADR_ELEMENT >, oomph::ProjectableElement< DARCY_ELEMENT >, oomph::ProjectableElement< POISSON_ELEMENT >, oomph::ProjectableElement< FOURIER_DECOMPOSED_HELMHOLTZ_ELEMENT >, oomph::ProjectableElement< TIME_HARMONIC_LINEAR_ELAST_ELEMENT >, oomph::ProjectableElement< LINEAR_HEAT_AND_ELAST_ELEMENT >, oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >, oomph::FaceElementAsGeomObject< ELEMENT >, oomph::DummyFaceElement< ELEMENT >, oomph::SolidFaceElement, oomph::FaceElement, oomph::SolidFiniteElement, oomph::FourierDecomposedHelmholtzBCElementBase< ELEMENT >, oomph::DGEulerFaceReflectionElement< ELEMENT >, oomph::DGEulerFaceElement< ELEMENT >, oomph::ElasticLineFluidInterfaceBoundingElement< ELEMENT >, oomph::ElasticPointFluidInterfaceBoundingElement< ELEMENT >, oomph::ElasticUpdateFluidInterfaceElement< FluidInterfaceElement, SurfaceDerivatives, ELEMENT >, oomph::ElasticUpdateFluidInterfaceElement< SurfactantTransportInterfaceElement, AxisymmetricDerivatives, ELEMENT >, oomph::ElasticUpdateFluidInterfaceElement< FluidInterfaceElement, AxisymmetricDerivatives, ELEMENT >, oomph::ElasticUpdateFluidInterfaceElement< SolubleSurfactantTransportInterfaceElement, LineDerivatives, ELEMENT >, oomph::ElasticUpdateFluidInterfaceElement< FluidInterfaceElement, LineDerivatives, ELEMENT >, oomph::SpineSurfaceVolumeConstraintBoundingElement< ELEMENT >, oomph::ElasticSurfaceVolumeConstraintBoundingElement< ELEMENT >, oomph::SpineAxisymmetricVolumeConstraintBoundingElement< ELEMENT >, oomph::ElasticAxisymmetricVolumeConstraintBoundingElement< ELEMENT >, oomph::SpineLineVolumeConstraintBoundingElement< ELEMENT >, oomph::ElasticLineVolumeConstraintBoundingElement< ELEMENT >, oomph::DarcyFaceElement< ELEMENT >, oomph::BiharmonicFluxElement< DIM >, oomph::AxisymmetricPoroelasticityTractionElement< ELEMENT >, oomph::AxisymmetricPoroelasticityTractionElement< POROELASTICITY_BULK_ELEMENT >, oomph::AxisymmetricNavierStokesTractionElement< ELEMENT >, oomph::AxisymmetricLinearElasticityTractionElement< ELEMENT >, oomph::AdvectionDiffusionFluxElement< ELEMENT >, oomph::UnsteadyHeatFluxPseudoMeltElement< ELEMENT >, oomph::StefanBoltzmannUnsteadyHeatFluxElement< ELEMENT >, StefanBoltzmannMeltElement< ELEMENT >, oomph::HeatedPenetratorFluxElement< ELEMENT >, oomph::HeatedLinearSurfaceContactElement< ELEMENT >, oomph::SurfaceMeltElement< ELEMENT >, oomph::UnsteadyHeatBaseFaceElement< ELEMENT >, and oomph::SurfaceContactElementBase< ELEMENT >.
     {
       // By default return the value for nodal_position_gen
       return nodal_position_gen(n, k, i);
     }
References i, k, n, and nodal_position_gen().
Referenced by get_centre_of_gravity_and_max_radius_in_terms_of_zeta(), interpolated_zeta(), locate_zeta(), and oomph::SurfaceContactElementBase< ELEMENT >::zeta_nodal().
Member Data Documentation
Accept_negative_jacobian
bool FiniteElement::Accept_negative_jacobian = false static
Boolean that if set to true allows a negative jacobian in the transform between global and local coordinates (negative surface area = left-handed coordinate system).
Set the default value of the Accept_negative_jacobian flag to be false
Referenced by check_J_eulerian_at_knots(), check_jacobian(), and self_test().
Default_Initial_Nvalue
const unsigned FiniteElement::Default_Initial_Nvalue = 0 static protected
Default value for the number of values at a node.
Default return value for required_nvalue(n) which gives the number of "data" values required by the element at node n; for example, solving a Poisson equation would required only one "data" value at each node. The defaults is set to zero, because a general element is problem-less.
Referenced by required_nvalue().
Elemental_dimension
unsigned oomph::FiniteElement::Elemental_dimension private
The spatial dimension of the element, i.e. the number of local coordinates used to parametrize it.
Referenced by assemble_local_to_eulerian_jacobian(), dim(), get_centre_of_gravity_and_max_radius_in_terms_of_zeta(), local_to_eulerian_mapping_diagonal(), and set_dimension().
Integral_pt
Integral* oomph::FiniteElement::Integral_pt private
Pointer to the spatial integration scheme.
Referenced by integral_pt(), and set_integration_scheme().
Macro_elem_pt
MacroElement* oomph::FiniteElement::Macro_elem_pt protected
Pointer to the element's macro element (NULL by default)
Referenced by oomph::RefineableQElement< 1 >::build(), oomph::RefineableQElement< 2 >::build(), check_jacobian(), get_x(), oomph::QSolidElementBase::get_x_and_xi(), oomph::QElementBase::get_x_from_macro_element(), interpolated_zeta(), macro_elem_pt(), set_macro_elem_pt(), and oomph::SolidFiniteElement::set_macro_elem_pt().
N2deriv
const unsigned FiniteElement::N2deriv = {0, 1, 3, 6} static protected
Static array that holds the number of second derivatives as a function of the dimension of the element
Static array that holds the number of rows in the second derivative matrix as a function of spatial dimension. In one-dimension, there is only one possible second derivative. In two-dimensions, there are three, the two second derivatives and the mixed derivatives. In three dimensions there are six.
Referenced by assemble_local_to_eulerian_jacobian2(), oomph::RefineableElement::assemble_local_to_eulerian_jacobian2(), oomph::SolidFiniteElement::assemble_local_to_lagrangian_jacobian2(), oomph::RefineableSolidElement::assemble_local_to_lagrangian_jacobian2(), d2shape_eulerian(), d2shape_eulerian_at_knot(), oomph::SolidFiniteElement::d2shape_lagrangian(), and oomph::SolidFiniteElement::d2shape_lagrangian_at_knot().
Nnodal_position_type
unsigned oomph::FiniteElement::Nnodal_position_type private
The number of coordinate types required to interpolate the element's geometry between the nodes. For Lagrange elements it is 1 (the default). It must be over-ridden by using the set_nposition_type() function in the constructors of elements that use generalised coordinate, e.g. for 1D Hermite elements Nnodal_position_types =2.
Referenced by construct_boundary_node(), construct_node(), nnodal_position_type(), and set_nnodal_position_type().
Nnode
unsigned oomph::FiniteElement::Nnode private
Number of nodes in the element.
Referenced by nnode(), nodal_local_eqn(), node_pt(), and set_n_node().
Nodal_dimension
unsigned oomph::FiniteElement::Nodal_dimension private
The spatial dimension of the nodes in the element. We assume that nodes have the same spatial dimension, because we cannot think of any "real" problems for which that would not be the case.
Referenced by assemble_local_to_eulerian_jacobian(), construct_boundary_node(), construct_node(), local_to_eulerian_mapping_diagonal(), nodal_dimension(), set_dimension(), and set_nodal_dimension().
Nodal_local_eqn
int** oomph::FiniteElement::Nodal_local_eqn private
Storage for the local equation numbers associated with the values stored at the nodes
Referenced by assign_nodal_local_eqn_numbers(), nodal_local_eqn(), and ~FiniteElement().
Node_location_tolerance
const double FiniteElement::Node_location_tolerance = 1.0e-14 static protected
Default value for the tolerance to be used when locating nodes via local coordinates
Default value that is used for the tolerance required when locating nodes via local coordinates
Referenced by oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::get_interpolating_node_at_local_coordinate(), oomph::RefineableAxisymmetricQTaylorHoodElement::get_interpolating_node_at_local_coordinate(), oomph::RefineableGeneralisedNewtonianAxisymmetricQTaylorHoodElement::get_interpolating_node_at_local_coordinate(), oomph::RefineableLinearisedQTaylorHoodElement::get_interpolating_node_at_local_coordinate(), oomph::RefineableQSphericalTaylorHoodElement::get_interpolating_node_at_local_coordinate(), oomph::RefineableGeneralisedNewtonianQTaylorHoodElement< DIM >::get_interpolating_node_at_local_coordinate(), oomph::RefineableQTaylorHoodElement< DIM >::get_interpolating_node_at_local_coordinate(), oomph::RefineablePolarTaylorHoodElement::get_interpolating_node_at_local_coordinate(), oomph::RefineableQPVDElementWithContinuousPressure< DIM >::get_interpolating_node_at_local_coordinate(), oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >::get_interpolating_node_at_local_coordinate(), oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >::get_interpolating_node_at_local_coordinate(), oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::get_node_at_local_coordinate(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::get_node_at_local_coordinate(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::get_node_at_local_coordinate(), oomph::QElement< 1, NNODE_1D >::get_node_at_local_coordinate(), oomph::QElement< 2, NNODE_1D >::get_node_at_local_coordinate(), and oomph::QElement< 3, NNODE_1D >::get_node_at_local_coordinate().
Node_pt
Node** oomph::FiniteElement::Node_pt private
Storage for pointers to the nodes in the element.
Referenced by assign_nodal_local_eqn_numbers(), node_pt(), set_n_node(), and ~FiniteElement().
Suppress_output_while_checking_for_inverted_elements
bool FiniteElement::Suppress_output_while_checking_for_inverted_elements static
Initial value:
=
    false
Static boolean to suppress output while checking for inverted elements
Set default for static boolean to suppress output while checking for inverted elements
Referenced by oomph::Mesh::check_inverted_elements(), and check_jacobian().
Tolerance_for_singular_jacobian
double FiniteElement::Tolerance_for_singular_jacobian = 1.0e-16 static
Tolerance below which the jacobian is considered singular.
Set the default tolerance for a singular jacobian.
Referenced by check_jacobian().
The documentation for this class was generated from the following files:
elements.h
elements.cc