MercuryDPM: Eigen::internal::matrix_exp_computeUV< MatrixType, float > Struct Template Reference
Eigen::internal::matrix_exp_computeUV< MatrixType, float > Struct Template Reference
#include <MatrixExponential.h>
Static Public Member Functions
template<typename ArgType >
static void run (const ArgType &arg, MatrixType &U, MatrixType &V, int &squarings)
Member Function Documentation
run()
template<typename MatrixType > template<typename ArgType > static void Eigen::internal::matrix_exp_computeUV< MatrixType, float >::run (const ArgType & arg, MatrixType & U, MatrixType & V, int & squarings) inline static
{
     using std::frexp;
     using std::pow;
     const float l1norm = arg.cwiseAbs().colwise().sum().maxCoeff();
     squarings = 0;
     if (l1norm < 4.258730016922831e-001f) {
       matrix_exp_pade3(arg, U, V);
     } else if (l1norm < 1.880152677804762e+000f) {
       matrix_exp_pade5(arg, U, V);
     } else {
       const float maxnorm = 3.925724783138660f;
       frexp(l1norm / maxnorm, &squarings);
       if (squarings < 0) squarings = 0;
       MatrixType A = arg.unaryExpr(MatrixExponentialScalingOp<float>(squarings));
       matrix_exp_pade7(A, U, V);
     }
   }
References Eigen::internal::matrix_exp_pade3(), Eigen::internal::matrix_exp_pade5(), Eigen::internal::matrix_exp_pade7(), Eigen::bfloat16_impl::pow(), RachelsAdvectionDiffusion::U, and V.
The documentation for this struct was generated from the following file:
MatrixExponential.h