MercuryDPM: Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, CoeffBasedProductMode > Struct Template Reference
Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, CoeffBasedProductMode > Struct Template Reference
#include <ProductEvaluators.h>
Public Types
typedef Product< Lhs, Rhs >::Scalar Scalar
Static Public Member Functions
template<typename Dst >
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void evalTo (Dst &dst, const Lhs &lhs, const Rhs &rhs)
template<typename Dst >
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void addTo (Dst &dst, const Lhs &lhs, const Rhs &rhs)
template<typename Dst >
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void subTo (Dst &dst, const Lhs &lhs, const Rhs &rhs)
template<typename Dst , typename Func >
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void eval_dynamic (Dst &dst, const Lhs &lhs, const Rhs &rhs, const Func &func)
Static Protected Member Functions
template<typename Dst , typename LhsT , typename RhsT , typename Func , typename Scalar >
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void eval_dynamic_impl (Dst &dst, const LhsT &lhs, const RhsT &rhs, const Func &func, const Scalar &s, false_type)
template<typename Dst , typename LhsT , typename RhsT , typename Func , typename Scalar >
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void eval_dynamic_impl (Dst &dst, const LhsT &lhs, const RhsT &rhs, const Func &func, const Scalar &s, true_type)
Member Typedef Documentation
Scalar
template<typename Lhs , typename Rhs > typedef Product<Lhs, Rhs>::Scalar Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, CoeffBasedProductMode >::Scalar
Member Function Documentation
addTo()
template<typename Lhs , typename Rhs > template<typename Dst > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, CoeffBasedProductMode >::addTo (Dst & dst, const Lhs & lhs, const Rhs & rhs) inline static
{
     // dst.noalias() += lhs.lazyProduct(rhs);
     call_assignment_no_alias(dst, lhs.lazyProduct(rhs), internal::add_assign_op<typename Dst::Scalar, Scalar>());
   }
References Eigen::internal::call_assignment_no_alias().
eval_dynamic()
template<typename Lhs , typename Rhs > template<typename Dst , typename Func > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, CoeffBasedProductMode >::eval_dynamic (Dst & dst, const Lhs & lhs, const Rhs & rhs, const Func & func) inline static
{
     enum {
       HasScalarFactor = blas_traits<Lhs>::HasScalarFactor || blas_traits<Rhs>::HasScalarFactor,
       ConjLhs = blas_traits<Lhs>::NeedToConjugate,
       ConjRhs = blas_traits<Rhs>::NeedToConjugate
     };
     // FIXME: in c++11 this should be auto, and extractScalarFactor should also return auto
     //        this is important for real*complex_mat
     Scalar actualAlpha = combine_scalar_factors<Scalar>(lhs, rhs);
     eval_dynamic_impl(dst, blas_traits<Lhs>::extract(lhs).template conjugateIf<ConjLhs>(),
                       blas_traits<Rhs>::extract(rhs).template conjugateIf<ConjRhs>(), func, actualAlpha,
                       std::conditional_t<HasScalarFactor, true_type, false_type>());
   }
eval_dynamic_impl() [1/2]
template<typename Lhs , typename Rhs > template<typename Dst , typename LhsT , typename RhsT , typename Func , typename Scalar > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, CoeffBasedProductMode >::eval_dynamic_impl (Dst & dst, const LhsT & lhs, const RhsT & rhs, const Func & func, const Scalar & s, false_type) inline static protected
{
     EIGEN_UNUSED_VARIABLE(s);
     eigen_internal_assert(numext::is_exactly_one(s));
     call_restricted_packet_assignment_no_alias(dst, lhs.lazyProduct(rhs), func);
   }
References Eigen::internal::call_restricted_packet_assignment_no_alias(), eigen_internal_assert, EIGEN_UNUSED_VARIABLE, Eigen::numext::is_exactly_one(), and s.
eval_dynamic_impl() [2/2]
template<typename Lhs , typename Rhs > template<typename Dst , typename LhsT , typename RhsT , typename Func , typename Scalar > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, CoeffBasedProductMode >::eval_dynamic_impl (Dst & dst, const LhsT & lhs, const RhsT & rhs, const Func & func, const Scalar & s, true_type) inline static protected
{
     call_restricted_packet_assignment_no_alias(dst, s * lhs.lazyProduct(rhs), func);
   }
References Eigen::internal::call_restricted_packet_assignment_no_alias(), and s.
evalTo()
template<typename Lhs , typename Rhs > template<typename Dst > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, CoeffBasedProductMode >::evalTo (Dst & dst, const Lhs & lhs, const Rhs & rhs) inline static
{
     // Same as: dst.noalias() = lhs.lazyProduct(rhs);
     // but easier on the compiler side
     call_assignment_no_alias(dst, lhs.lazyProduct(rhs), internal::assign_op<typename Dst::Scalar, Scalar>());
   }
References Eigen::internal::call_assignment_no_alias().
subTo()
template<typename Lhs , typename Rhs > template<typename Dst > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, CoeffBasedProductMode >::subTo (Dst & dst, const Lhs & lhs, const Rhs & rhs) inline static
{
     // dst.noalias() -= lhs.lazyProduct(rhs);
     call_assignment_no_alias(dst, lhs.lazyProduct(rhs), internal::sub_assign_op<typename Dst::Scalar, Scalar>());
   }
References Eigen::internal::call_assignment_no_alias().
The documentation for this struct was generated from the following file:
ProductEvaluators.h