MercuryDPM: MindlinSpecies Class Reference
MindlinSpecies Class Reference
MindlinSpecies contains the parameters used to describe sliding friction.
#include <MindlinSpecies.h>
Public Types
typedef MindlinInteraction InteractionType
The correct Interaction type for this FrictionForceSpecies.
Public Member Functions
MindlinSpecies ()
The default constructor.
MindlinSpecies (const MindlinSpecies &s)
The default copy constructor.
~MindlinSpecies ()
The default destructor.
void read (std::istream &is)
Reads the species properties from an input stream.
void write (std::ostream &os) const
Writes the species properties to an output stream.
virtual std::string getBaseName () const
Used in Species::getName to obtain a unique name for each Species.
void setSlidingDissipation (Mdouble new_dispt)
Allows the tangential viscosity to be changed.
Mdouble getSlidingDissipation () const
Allows the tangential viscosity to be accessed.
void setSlidingFrictionCoefficient (Mdouble new_mu)
Allows the (dynamic) Coulomb friction coefficient to be changed; also sets mu_s by default.
Mdouble getSlidingFrictionCoefficient () const
Allows the (dynamic) Coulomb friction coefficient to be accessed.
void setSlidingFrictionCoefficientStatic (Mdouble new_mu)
Allows the static Coulomb friction coefficient to be changed.
Mdouble getSlidingFrictionCoefficientStatic () const
Allows the static Coulomb friction coefficient to be accessed.
MERCURYDPM_DEPRECATED void setPoissonRatio (Mdouble poissonRatio)
Allows the poisson ratio to be changed.
void setEffectiveShearModulus (Mdouble shearModulus)
allows the shear modulus to be changed
Mdouble getEffectiveShearModulus () const
Allows the shear modulus to be accessed.
bool getUseAngularDOFs () const override
Returns true if torques have to be calculated.
void mix (MindlinSpecies *S, MindlinSpecies *T)
creates default values for mixed species
Public Member Functions inherited from BaseForce
BaseSpecies * getBaseSpecies () const
void setBaseSpecies (BaseSpecies *baseSpecies)
Private Attributes
Mdouble slidingDissipation_
tangential dissipation coefficient.
Mdouble slidingFrictionCoefficient_
(dynamic) Coulomb friction coefficient
Mdouble slidingFrictionCoefficientStatic_
static Coulomb friction coefficient (by default set equal to mu)
Mdouble shearModulus_
tangential spring constant
Detailed Description
MindlinSpecies contains the parameters used to describe sliding friction.
See MindlinInteraction::computeForce for a description of the force law.
Member Typedef Documentation
InteractionType
typedef MindlinInteraction MindlinSpecies::InteractionType
The correct Interaction type for this FrictionForceSpecies.
Constructor & Destructor Documentation
MindlinSpecies() [1/2]
MindlinSpecies::MindlinSpecies ()
The default constructor.
 {
     slidingDissipation_ = 0;
     slidingFrictionCoefficient_ = 0;
     slidingFrictionCoefficientStatic_ = 0;
     shearModulus_ = 0;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"MindlinSpecies::MindlinSpecies() finished"<<std::endl;
 #endif
 }
References shearModulus_, slidingDissipation_, slidingFrictionCoefficient_, and slidingFrictionCoefficientStatic_.
MindlinSpecies() [2/2]
MindlinSpecies::MindlinSpecies (const MindlinSpecies & s)
The default copy constructor.
Parameters
[in] s the species that is copied
 {
     slidingDissipation_ = s.slidingDissipation_;
     slidingFrictionCoefficient_ = s.slidingFrictionCoefficient_;
     slidingFrictionCoefficientStatic_ = s.slidingFrictionCoefficientStatic_;
     shearModulus_ = s.shearModulus_;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"MindlinSpecies::MindlinSpecies(const MindlinSpecies &p) finished"<<std::endl;
 #endif
 }
References s, shearModulus_, slidingDissipation_, slidingFrictionCoefficient_, and slidingFrictionCoefficientStatic_.
~MindlinSpecies()
MindlinSpecies::~MindlinSpecies ()
The default destructor.
 {
 #ifdef DEBUG_DESTRUCTOR
     std::cout<<"MindlinSpecies::~MindlinSpecies() finished"<<std::endl;
 #endif
 }
Member Function Documentation
getBaseName()
std::string MindlinSpecies::getBaseName () const virtual
Used in Species::getName to obtain a unique name for each Species.
Returns
a string containing the name of the species (minus the word "Species")
Reimplemented in MindlinRollingTorsionSpecies.
 {
     return "Mindlin";
 }
getEffectiveShearModulus()
Mdouble MindlinSpecies::getEffectiveShearModulus () const
Allows the shear modulus to be accessed.
 {
     return shearModulus_;
 }
References shearModulus_.
Referenced by MindlinInteraction::computeFrictionForce(), mix(), and setPoissonRatio().
getSlidingDissipation()
Mdouble MindlinSpecies::getSlidingDissipation () const
Allows the tangential viscosity to be accessed.
 {
     return slidingDissipation_;
 }
References slidingDissipation_.
Referenced by MindlinInteraction::computeFrictionForce(), and mix().
getSlidingFrictionCoefficient()
Mdouble MindlinSpecies::getSlidingFrictionCoefficient () const
Allows the (dynamic) Coulomb friction coefficient to be accessed.
 {
     return slidingFrictionCoefficient_;
 }
References slidingFrictionCoefficient_.
Referenced by MindlinInteraction::computeFrictionForce(), and mix().
getSlidingFrictionCoefficientStatic()
Mdouble MindlinSpecies::getSlidingFrictionCoefficientStatic () const
Allows the static Coulomb friction coefficient to be accessed.
 {
     return slidingFrictionCoefficientStatic_;
 }
References slidingFrictionCoefficientStatic_.
Referenced by mix().
getUseAngularDOFs()
bool MindlinSpecies::getUseAngularDOFs () const override virtual
Returns true if torques have to be calculated.
Returns true for any FrictionForceSpecies except EmptyFrictionSpecies, because for spherical particles, torques are only caused by tangential forces. See SpeciesHandler::useAngularDOFs for more details
Returns
true
Implements BaseFrictionForce.
 {
     return true;
 }
mix()
void MindlinSpecies::mix (MindlinSpecies * S, MindlinSpecies * T)
creates default values for mixed species
For all parameters we assume that the harmonic mean of the parameters of the original two species is a sensible default.
Parameters
[in] SFrictional the first species whose properties are mixed to create the new species
[in] TFrictional the second species whose properties are mixed to create the new species
 {
     slidingDissipation_ = BaseSpecies::average(SFrictional->getSlidingDissipation(),TFrictional->getSlidingDissipation());
     slidingFrictionCoefficient_ = BaseSpecies::average(SFrictional->getSlidingFrictionCoefficient(),TFrictional->getSlidingFrictionCoefficient());
     slidingFrictionCoefficientStatic_ = BaseSpecies::average(SFrictional->getSlidingFrictionCoefficientStatic(),TFrictional->getSlidingFrictionCoefficientStatic());
     shearModulus_ = BaseSpecies::average(SFrictional->getEffectiveShearModulus(), TFrictional->getEffectiveShearModulus());
 }
References BaseSpecies::average(), getEffectiveShearModulus(), getSlidingDissipation(), getSlidingFrictionCoefficient(), getSlidingFrictionCoefficientStatic(), shearModulus_, slidingDissipation_, slidingFrictionCoefficient_, and slidingFrictionCoefficientStatic_.
read()
void MindlinSpecies::read (std::istream & is)
Reads the species properties from an input stream.
Parameters
[in] is input stream (typically the restart file)
 {
     //BaseSpecies::read(is);
     std::string dummy;
     is >> dummy >> slidingDissipation_;
     is >> dummy >> slidingFrictionCoefficient_;
     is >> dummy >> slidingFrictionCoefficientStatic_;
     is >> dummy >> shearModulus_;
 }
References shearModulus_, slidingDissipation_, slidingFrictionCoefficient_, slidingFrictionCoefficientStatic_, and oomph::Global_string_for_annotation::string().
Referenced by MindlinRollingTorsionSpecies::read().
setEffectiveShearModulus()
void MindlinSpecies::setEffectiveShearModulus (Mdouble shearModulus)
allows the shear modulus to be changed
Allows the shear modulus to be changed.
 {
     logger.assert_debug(shearModulus > 0,
                   "setEffectiveShearModulus(%): value needs to be positive",shearModulus);
     shearModulus_ = shearModulus;
 }
References logger, and shearModulus_.
setPoissonRatio()
void MindlinSpecies::setPoissonRatio (Mdouble poissonRatio)
Allows the poisson ratio to be changed.
 {
     auto hertz = dynamic_cast<HertzianViscoelasticNormalSpecies*>(getBaseSpecies());
     logger.assert_debug(hertz, "setPoissonRatio only works with HertzianViscoelastic*Species.");
     shearModulus_ = hertz->getEffectiveElasticModulus() / 2 * (1 + poissonRatio);
     logger(INFO, "Effective shear modulus set to %, based on effective elastic modulus % and Poisson's ratio %",
            getEffectiveShearModulus(),
            hertz->getEffectiveElasticModulus(), poissonRatio);
 }
References BaseForce::getBaseSpecies(), getEffectiveShearModulus(), INFO, logger, and shearModulus_.
setSlidingDissipation()
void MindlinSpecies::setSlidingDissipation (Mdouble new_dispt)
Allows the tangential viscosity to be changed.
 {
     if (new_dispt >= 0)
         slidingDissipation_ = new_dispt;
     else
     {
         logger(ERROR, "Error in setSlidingDissipation");
     }
 }
References ERROR, logger, and slidingDissipation_.
setSlidingFrictionCoefficient()
void MindlinSpecies::setSlidingFrictionCoefficient (Mdouble new_mu)
Allows the (dynamic) Coulomb friction coefficient to be changed; also sets mu_s by default.
 {
     if (new_mu >= 0)
     {
         slidingFrictionCoefficient_ = new_mu;
         slidingFrictionCoefficientStatic_ = slidingFrictionCoefficient_;
     }
     else
     {
         logger(ERROR, "Error in setSlidingFrictionCoefficient");
     }
 }
References ERROR, logger, slidingFrictionCoefficient_, and slidingFrictionCoefficientStatic_.
setSlidingFrictionCoefficientStatic()
void MindlinSpecies::setSlidingFrictionCoefficientStatic (Mdouble new_mu)
Allows the static Coulomb friction coefficient to be changed.
 {
     if (new_mu >= 0)
     {
         slidingFrictionCoefficientStatic_ = new_mu;
     }
     else
     {
         logger(ERROR, "Error in setSlidingFrictionCoefficientStatic");
     }
 }
References ERROR, logger, and slidingFrictionCoefficientStatic_.
write()
void MindlinSpecies::write (std::ostream & os) const
Writes the species properties to an output stream.
Parameters
[out] os output stream (typically the restart file)
 {
     //BaseSpecies::write(os);
     os << " slidingDissipation " << slidingDissipation_;
     os << " slidingFrictionCoefficient " << slidingFrictionCoefficient_;
     os << " slidingFrictionCoefficientStatic " << slidingFrictionCoefficientStatic_;
     os << " shearModulus " << shearModulus_;
 }
References shearModulus_, slidingDissipation_, slidingFrictionCoefficient_, and slidingFrictionCoefficientStatic_.
Referenced by MindlinRollingTorsionSpecies::write().
Member Data Documentation
shearModulus_
Mdouble MindlinSpecies::shearModulus_ private
tangential spring constant
Referenced by getEffectiveShearModulus(), MindlinSpecies(), mix(), read(), setEffectiveShearModulus(), setPoissonRatio(), and write().
slidingDissipation_
Mdouble MindlinSpecies::slidingDissipation_ private
tangential dissipation coefficient.
Typically set to 2/7 of the normal force dissipation, as both the tangential and the normal spring have the same restitution coefficients (if the tangential and normal stiffnesses also have a ratio of 2/7). should always satisfy \(4*dispt*dt<mass, dispt \approx disp\), otherwise the restitution is zero and the particles stick.
Referenced by getSlidingDissipation(), MindlinSpecies(), mix(), read(), setSlidingDissipation(), and write().
slidingFrictionCoefficient_
Mdouble MindlinSpecies::slidingFrictionCoefficient_ private
(dynamic) Coulomb friction coefficient
Referenced by getSlidingFrictionCoefficient(), MindlinSpecies(), mix(), read(), setSlidingFrictionCoefficient(), and write().
slidingFrictionCoefficientStatic_
Mdouble MindlinSpecies::slidingFrictionCoefficientStatic_ private
static Coulomb friction coefficient (by default set equal to mu)
Referenced by getSlidingFrictionCoefficientStatic(), MindlinSpecies(), mix(), read(), setSlidingFrictionCoefficient(), setSlidingFrictionCoefficientStatic(), and write().
The documentation for this class was generated from the following files:
MindlinSpecies.h
MindlinSpecies.cc