MercuryDPM: numext.cpp File Reference
numext.cpp File Reference
#include "main.h"
Classes
struct check_sqrt_impl< T >
struct check_sqrt_impl< std::complex< T > >
struct check_rsqrt_impl< T >
struct check_rsqrt_impl< std::complex< T > >
struct check_signbit_impl< T >
Macros
#define VERIFY_IS_EQUAL_OR_NANS(a, b) VERIFY(test_is_equal_or_nans(a, b))
Functions
template<typename T , typename U >
bool check_if_equal_or_nans (const T &actual, const U &expected)
template<typename T , typename U >
bool check_if_equal_or_nans (const std::complex< T > &actual, const std::complex< U > &expected)
template<typename T , typename U >
bool test_is_equal_or_nans (const T &actual, const U &expected)
template<typename T >
void check_negate ()
template<typename T >
void check_abs ()
template<>
void check_abs< bool > ()
template<typename T >
void check_arg ()
template<typename T >
void check_sqrt ()
template<typename T >
void check_rsqrt ()
template<typename T >
void check_signbit ()
template<typename T >
void check_shift ()
EIGEN_DECLARE_TEST (numext)
Macro Definition Documentation
VERIFY_IS_EQUAL_OR_NANS
#define VERIFY_IS_EQUAL_OR_NANS (a, b) VERIFY(test_is_equal_or_nans(a, b))
Function Documentation
check_abs()
template<typename T > void check_abs ()
                  {
   typedef typename NumTraits<T>::Real Real;
   Real zero(0);
   if (NumTraits<T>::IsSigned) VERIFY_IS_EQUAL(numext::abs(numext::negate(T(1))), T(1));
   VERIFY_IS_EQUAL(numext::abs(T(0)), T(0));
   VERIFY_IS_EQUAL(numext::abs(T(1)), T(1));
   for (int k = 0; k < 100; ++k) {
     T x = internal::random<T>();
     x = x / Real(2);
     if (NumTraits<T>::IsSigned) {
       VERIFY_IS_EQUAL(numext::abs(x), numext::abs(numext::negate(x)));
       VERIFY(numext::abs(numext::negate(x)) >= zero);
     }
     VERIFY(numext::abs(x) >= zero);
     VERIFY_IS_APPROX(numext::abs2(x), numext::abs2(numext::abs(x)));
   }
 }
References abs(), Eigen::numext::abs2(), k, Eigen::test::negate(), VERIFY, VERIFY_IS_APPROX, VERIFY_IS_EQUAL, plotDoE::x, and zero().
Referenced by EIGEN_DECLARE_TEST().
check_abs< bool >()
template<> void check_abs< bool > ()
{
   for (bool x : {true, false}) {
     VERIFY_IS_EQUAL(numext::abs(x), x);
     VERIFY(numext::abs(x) >= false);
     VERIFY_IS_EQUAL(numext::abs2(x), numext::abs2(numext::abs(x)));
   }
 }
References abs(), Eigen::numext::abs2(), VERIFY, VERIFY_IS_EQUAL, and plotDoE::x.
Referenced by EIGEN_DECLARE_TEST().
check_arg()
template<typename T > void check_arg ()
                  {
   typedef typename NumTraits<T>::Real Real;
   VERIFY_IS_EQUAL(numext::abs(T(0)), T(0));
   VERIFY_IS_EQUAL(numext::abs(T(1)), T(1));
   for (int k = 0; k < 100; ++k) {
     T x = internal::random<T>();
     Real y = numext::arg(x);
     VERIFY_IS_APPROX(y, std::arg(x));
   }
 }
References abs(), k, VERIFY_IS_APPROX, VERIFY_IS_EQUAL, plotDoE::x, and y.
Referenced by EIGEN_DECLARE_TEST().
check_if_equal_or_nans() [1/2]
template<typename T , typename U > bool check_if_equal_or_nans (const std::complex< T > & actual, const std::complex< U > & expected)
{
   return check_if_equal_or_nans(numext::real(actual), numext::real(expected)) &&
          check_if_equal_or_nans(numext::imag(actual), numext::imag(expected));
 }
References check_if_equal_or_nans(), and imag().
check_if_equal_or_nans() [2/2]
template<typename T , typename U > bool check_if_equal_or_nans (const T & actual, const U & expected)
{
   return (numext::equal_strict(actual, expected) || ((numext::isnan)(actual) && (numext::isnan)(expected)));
 }
References Eigen::numext::equal_strict(), and isnan.
Referenced by check_if_equal_or_nans(), and test_is_equal_or_nans().
check_negate()
template<typename T > void check_negate ()
                     {
   Index size = 1000;
   for (Index i = 0; i < size; i++) {
     T val = i == 0 ? T(0) : internal::random<T>(T(0), NumTraits<T>::highest());
     T neg_val = numext::negate(val);
     VERIFY_IS_EQUAL(T(val + neg_val), T(0));
     VERIFY_IS_EQUAL(numext::negate(neg_val), val);
   }
 }
References i, Eigen::test::negate(), size, calibrate::val, and VERIFY_IS_EQUAL.
Referenced by EIGEN_DECLARE_TEST().
check_rsqrt()
template<typename T > void check_rsqrt ()
                    {
   check_rsqrt_impl<T>::run();
 }
References check_rsqrt_impl< T >::run().
Referenced by EIGEN_DECLARE_TEST().
check_shift()
template<typename T > void check_shift ()
                    {
   using SignedT = typename numext::get_integer_by_size<sizeof(T)>::signed_type;
   using UnsignedT = typename numext::get_integer_by_size<sizeof(T)>::unsigned_type;
   constexpr int kNumBits = CHAR_BIT * sizeof(T);
   for (int i = 0; i < 1000; ++i) {
     const T a = internal::random<T>();
     for (int s = 1; s < kNumBits; s++) {
       T a_bsll = numext::logical_shift_left(a, s);
       T a_bsll_ref = a << s;
       VERIFY_IS_EQUAL(a_bsll, a_bsll_ref);
       T a_bsrl = numext::logical_shift_right(a, s);
       T a_bsrl_ref = numext::bit_cast<T, UnsignedT>(numext::bit_cast<UnsignedT, T>(a) >> s);
       VERIFY_IS_EQUAL(a_bsrl, a_bsrl_ref);
       T a_bsra = numext::arithmetic_shift_right(a, s);
       T a_bsra_ref = numext::bit_cast<T, SignedT>(numext::bit_cast<SignedT, T>(a) >> s);
       VERIFY_IS_EQUAL(a_bsra, a_bsra_ref);
     }
   }
 }
References a, Eigen::numext::arithmetic_shift_right(), i, Eigen::numext::logical_shift_left(), Eigen::numext::logical_shift_right(), s, and VERIFY_IS_EQUAL.
check_signbit()
template<typename T > void check_signbit ()
                      {
   check_signbit_impl<T>::run();
 }
References check_signbit_impl< T >::run().
check_sqrt()
template<typename T > void check_sqrt ()
                   {
   check_sqrt_impl<T>::run();
 }
References check_sqrt_impl< T >::run().
Referenced by EIGEN_DECLARE_TEST().
EIGEN_DECLARE_TEST()
EIGEN_DECLARE_TEST (numext)
{
   for (int k = 0; k < g_repeat; ++k) {
     CALL_SUBTEST(check_negate<signed char>());
     CALL_SUBTEST(check_negate<unsigned char>());
     CALL_SUBTEST(check_negate<short>());
     CALL_SUBTEST(check_negate<unsigned short>());
     CALL_SUBTEST(check_negate<int>());
     CALL_SUBTEST(check_negate<unsigned int>());
     CALL_SUBTEST(check_negate<long>());
     CALL_SUBTEST(check_negate<unsigned long>());
     CALL_SUBTEST(check_negate<half>());
     CALL_SUBTEST(check_negate<bfloat16>());
     CALL_SUBTEST(check_negate<float>());
     CALL_SUBTEST(check_negate<double>());
     CALL_SUBTEST(check_negate<long double>());
     CALL_SUBTEST(check_negate<std::complex<float> >());
     CALL_SUBTEST(check_negate<std::complex<double> >());
     CALL_SUBTEST(check_abs<bool>());
     CALL_SUBTEST(check_abs<signed char>());
     CALL_SUBTEST(check_abs<unsigned char>());
     CALL_SUBTEST(check_abs<short>());
     CALL_SUBTEST(check_abs<unsigned short>());
     CALL_SUBTEST(check_abs<int>());
     CALL_SUBTEST(check_abs<unsigned int>());
     CALL_SUBTEST(check_abs<long>());
     CALL_SUBTEST(check_abs<unsigned long>());
     CALL_SUBTEST(check_abs<half>());
     CALL_SUBTEST(check_abs<bfloat16>());
     CALL_SUBTEST(check_abs<float>());
     CALL_SUBTEST(check_abs<double>());
     CALL_SUBTEST(check_abs<long double>());
     CALL_SUBTEST(check_abs<std::complex<float> >());
     CALL_SUBTEST(check_abs<std::complex<double> >());
     CALL_SUBTEST(check_arg<std::complex<float> >());
     CALL_SUBTEST(check_arg<std::complex<double> >());
     CALL_SUBTEST(check_sqrt<float>());
     CALL_SUBTEST(check_sqrt<double>());
     CALL_SUBTEST(check_sqrt<std::complex<float> >());
     CALL_SUBTEST(check_sqrt<std::complex<double> >());
     CALL_SUBTEST(check_rsqrt<float>());
     CALL_SUBTEST(check_rsqrt<double>());
     CALL_SUBTEST(check_rsqrt<std::complex<float> >());
     CALL_SUBTEST(check_rsqrt<std::complex<double> >());
     CALL_SUBTEST(check_signbit<half>());
     CALL_SUBTEST(check_signbit<bfloat16>());
     CALL_SUBTEST(check_signbit<float>());
     CALL_SUBTEST(check_signbit<double>());
     CALL_SUBTEST(check_signbit<uint8_t>());
     CALL_SUBTEST(check_signbit<uint16_t>());
     CALL_SUBTEST(check_signbit<uint32_t>());
     CALL_SUBTEST(check_signbit<uint64_t>());
     CALL_SUBTEST(check_signbit<int8_t>());
     CALL_SUBTEST(check_signbit<int16_t>());
     CALL_SUBTEST(check_signbit<int32_t>());
     CALL_SUBTEST(check_signbit<int64_t>());
     CALL_SUBTEST(check_shift<int8_t>());
     CALL_SUBTEST(check_shift<int16_t>());
     CALL_SUBTEST(check_shift<int32_t>());
     CALL_SUBTEST(check_shift<int64_t>());
     CALL_SUBTEST(check_shift<uint8_t>());
     CALL_SUBTEST(check_shift<uint16_t>());
     CALL_SUBTEST(check_shift<uint32_t>());
     CALL_SUBTEST(check_shift<uint64_t>());
   }
 }
References CALL_SUBTEST, check_abs(), check_abs< bool >(), check_arg(), check_negate(), check_rsqrt(), check_sqrt(), Eigen::g_repeat, and k.
test_is_equal_or_nans()
template<typename T , typename U > bool test_is_equal_or_nans (const T & actual, const U & expected)
{
   if (check_if_equal_or_nans(actual, expected)) {
     return true;
   }
   // false:
   std::cerr << "\n    actual   = " << actual << "\n    expected = " << expected << "\n\n";
   return false;
 }
References check_if_equal_or_nans().