MercuryDPM: CGHandlerLargeSelfTest.cpp File Reference
CGHandlerLargeSelfTest.cpp File Reference
#include "Mercury3D.h"
#include "StatisticsVector.h"
#include "Walls/InfiniteWall.h"
#include "CG/CG.h"
#include "CG/Functions/Gauss.h"
#include <cmath>
#include <iostream>
#include <iomanip>
#include <Species/LinearViscoelasticSpecies.h>
Classes
class CGHandlerSelfTest
In this file a cubic packing of 5^3 particles in a tri-axial box is created and allowed to settle under small gravity. After that Z statistics are calculated.
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
 {
     CGHandlerSelfTest problem;
     problem.setName("CGHandlerSelfTest");
     auto species = problem.speciesHandler.copyAndAddObject(LinearViscoelasticSpecies());
     //set the number of particles
     problem.N = 5;
     problem.setSystemDimensions(3);
     problem.speciesHandler.getObject(0)->setDensity(6.0 / constants::pi);
     problem.setGravity(Vec3D(0., 0., -1.));
     species->setCollisionTimeAndRestitutionCoefficient(.01, .1, 1.);
     problem.setTimeStep(.0002);
     problem.setTimeMax(1.5 - 1e-10);
     problem.setSaveCount(7500);
 //    CG<CGCoordinates::XY,CGFunctions::Gauss> cg0;
 //    cg0.setWidth(0);
 //    problem.cgHandler.copyAndAddObject(cg0);
 //
 //    CG<CGCoordinates::Z,CGFunctions::Gauss> cg1;
 //    cg1.setNZ(100);
 //    cg1.setWidth(0.1);
 //    problem.cgHandler.copyAndAddObject(cg1);
     CG<CGCoordinates::XZ,CGFunctions::Gauss> cg2;
     cg2.setNX(20);
     cg2.setNZ(30);
     cg2.setWidth(0.5);
     cg2.statFile.setSaveCount(20000);
     problem.cgHandler.copyAndAddObject(cg2);
 //    CG<CGCoordinates::XYZ,CGFunctions::Gauss> cg3;
 //    cg3.setNX(10);
 //    cg3.setNY(10);
 //    cg3.setNZ(10);
 //    cg3.setWidth(0.1);
 //    problem.cgHandler.copyAndAddObject(cg3);
     problem.solve(argc, argv);
     //p 'CGHandlerSelfTest.1.stat' u 7:32 w l, '' u 7:11 w l
     //sp [][][0:] 'CGHandlerSelfTest.2.stat' u 7:9:34, '' u 7:9:13
 }
References e(), constants::pi, problem, BaseCG::setNX(), BaseCG::setNZ(), File::setSaveCount(), CG< Coordinates, BaseFunction, Fields >::setWidth(), and BaseCG::statFile.