MercuryDPM: CubeInsertionBoundary Class Reference
CubeInsertionBoundary Class Reference
It's an insertion boundary which has cuboidal shape (yes, 'CuboidalInsertionBoundary' would have been the correct name).
#include <CubeInsertionBoundary.h>
Public Member Functions
CubeInsertionBoundary ()
Constructor; sets everything to 0.
CubeInsertionBoundary (const CubeInsertionBoundary &other)
Copy constructor with deep copy.
~CubeInsertionBoundary () override
Destructor: default destructor.
CubeInsertionBoundary * copy () const override
Creates a copy on the heap and returns a pointer.
void set (BaseParticle *particleToCopy, unsigned int maxFailed, Vec3D posMin, Vec3D posMax, Vec3D velMin={0, 0, 0}, Vec3D velMax={0, 0, 0})
Sets the properties of the InsertionBoundary for mutliple different particle types.
void set (BaseParticle &particleToCopy, unsigned int maxFailed, Vec3D posMin, Vec3D posMax, Vec3D velMin={0, 0, 0}, Vec3D velMax={0, 0, 0})
void set (std::vector< BaseParticle * > particleToCopy, unsigned int maxFailed, Vec3D posMin, Vec3D posMax, Vec3D velMin={0, 0, 0}, Vec3D velMax={0, 0, 0})
Sets the properties of the InsertionBoundary for a single particle type.
void set (BaseParticle *particleToCopy, unsigned int maxFailed, Vec3D posMin, Vec3D posMax, Vec3D velMin, Vec3D velMax, Mdouble rMin, Mdouble rMax)
old style set function which assumes a uniform psd.
void set (BaseParticle &particleToCopy, unsigned int maxFailed, Vec3D posMin, Vec3D posMax, Vec3D velMin, Vec3D velMax, Mdouble rMin, Mdouble rMax)
old style set function which assumes a uniform psd.
void setGeometry (Vec3D posMin, Vec3D posMax)
Sets the geometry (position and velocity distribution) of the CubeInsertionBoundary.
void placeParticle (BaseParticle *p, RNG &random) override
Generates a random position, velocity for the particle p.
void read (std::istream &is) override
reads boundary properties from istream
void write (std::ostream &os) const override
writes boundary properties to ostream
Public Member Functions inherited from InsertionBoundary
InsertionBoundary ()
InsertionBoundary (const InsertionBoundary &other)
Copy constructor (with deep copy)
~InsertionBoundary () override
Destructor: delete the particle that has to be copied at every insertion.
virtual BaseParticle * generateParticle (RNG &random)
Sets the properties of the InsertionBoundary for a single particle type ‍/ virtual void set(BaseParticle* particleToCopy, unsigned int maxFailed, Vec3D velMin, Vec3D velMax, double radMin, double radMax)=0;.
virtual void shiftBoundary (Vec3D shift)
virtual function that shifts the boundary.
virtual void rotateBoundary (Vec3D angle)
virtual function that rotates the boundary.
void checkBoundaryBeforeTimeStep (DPMBase *md) override
Fills the boundary with particles.
void insertParticles (DPMBase *md)
Fill a certain domain with particles.
unsigned int getNumberOfParticlesInserted () const
Gets the number of particles inserted by the boundary.
Mdouble getMassOfParticlesInserted () const
Gets the mass of particles inserted by the boundary.
Mdouble getVolumeOfParticlesInserted () const
Gets the volume of particles inserted by the boundary.
void reset ()
resets particle property counter variables.
void activate ()
Turns on the InsertionBoundary.
void deactivate ()
Turns off the InsertionBoundary.
bool isActivated ()
Returns whether the InsertionBoundary is activated.
unsigned int getMaxFailed () const
Gets the number of times that the boundary may fail to insert a particle.
void setParticleToCopy (std::vector< BaseParticle * > particleToCopy)
Sets multiple different particles that will be inserted through the insertion boundary.
void setParticleToCopy (BaseParticle *particleToCopy)
Sets the particle that will be inserted through the insertion boundary.
std::vector< BaseParticle * > getParticleToCopy ()
Gets the particles that will be inserted through the insertion boundary.
void read (std::istream &is) override
Reads the boundary's id_ and maxFailed_.
void write (std::ostream &os) const override
Writes the boundary's id_ and maxFailed_.
Mdouble getVolumeFlowRate () const
Gets the volume flow rate of the insertion routine.
void setVolumeFlowRate (Mdouble volumeFlowRate)
Sets the volume flow rate of the insertion routine.
Mdouble getInitialVolume () const
Gets the initialVolume() .
void setInitialVolume (Mdouble initialVolume)
Gets the Volume which should be inserted by the insertion routine.
void setPSD (const PSD psd)
Sets the range of particle radii that may be generated from a user defined PSD.
void setPSD (std::vector< PSD > psd, std::vector< Mdouble > probability)
Sets the ranges of particle radii that may be generated from user defined PSDs.
std::vector< PSD > getPSD ()
Gets the particle size distributions set by the user.
void setVariableVolumeFlowRate (const std::vector< Mdouble > &variableCumulativeVolumeFlowRate, Mdouble samplingInterval)
Sets a variable volume flow rate.
bool insertParticle (Mdouble time)
Checks the inserted total volume and returns if a particle is still allowed to be inserted.
bool getCheckParticleForInteraction () const
Gets the variable that checks if a particle has an interaction.
void setCheckParticleForInteraction (bool checkParticleForInteraction)
Sets the variable that checks if a particle has an interaction.
void setManualInsertion (bool manualInsertion)
Set the flag for a manual PSD insertion routine.
Public Member Functions inherited from BaseBoundary
BaseBoundary ()
default constructor.
BaseBoundary (const BaseBoundary &b)
copy constructor
~BaseBoundary () override
destructor
virtual void createPeriodicParticle (BaseParticle *p UNUSED, ParticleHandler &pH UNUSED)
Creates a periodic particle in case of periodic boundaries in serial build.
virtual void createPeriodicParticles (ParticleHandler &pH UNUSED)
Creates periodic copies of given particle in case of periodic boundaries.
virtual void checkBoundaryAfterParticlesMove (ParticleHandler &pH)
Virtual function that does things to particles, each time step after particles have moved.
virtual void actionsBeforeTimeLoop ()
Virtual function that does something after DPMBase::setupInitialConditions but before the first time step.
virtual void modifyGhostAfterCreation (BaseParticle *particle, int i)
virtual void writeVTK (std::fstream &file)
void setHandler (BoundaryHandler *handler)
Sets the boundary's BoundaryHandler.
BoundaryHandler * getHandler () const
Returns the boundary's BoundaryHandler.
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Protected Attributes
Vec3D posMin_
Minimal and maximal positions defining the boundary's boundaries, and minimum and maximum velocity of the particles to be inserted.
Vec3D posMax_
Private Member Functions
std::string getName () const override
Returns the name of the object.
Additional Inherited Members
Public Attributes inherited from InsertionBoundary
std::vector< BaseParticle * > particleToCopy_
read Distribution class from file. ‍/ friend std::istream& operator>>(std::istream& is, InsertionBoundary::Distribution& type);
unsigned int maxFailed_
Number of times that the wall may fail to insert a particle.
unsigned int numberOfParticlesInserted_
Number of particles that are already inserted.
Mdouble massInserted_
Total mass of particles inserted.
Mdouble volumeInserted_
Total volume of particles inserted.
bool isActivated_
The InsertionBoundary is activated by default. If the InsertionBoundary is deactivated, then it introduces no particles (useful for trying to maintain a certain insertion rate).
Mdouble volumeFlowRate_
Mdouble initialVolume_
std::vector< Mdouble > variableCumulativeVolumeFlowRate_
Mdouble samplingInterval_
bool checkParticleForInteraction_
Checks if a particle has an interaction with a wall or other particles.
std::vector< PSD > particleSizeDistributionVector_
Defines a particle size distribution as an object of the PSD class; if particleSizeDistributionVector_ is empty, distribution_ is used instead.
Vec3D velMin_
Minimum and maximum velocity of the particles to be inserted.
Vec3D velMax_
bool isManuallyInserting_
A flag to enable a top-down class-by-class manual insertion of a PSD; default is FALSE.
std::vector< Mdouble > probability_
vector of probabilities in range [0,1] which determine the mixing ratio of partice size distributions.
int chosenSpecies_
stores the chosen species for each timestep.
BaseParticle * p0 = nullptr
pointer to the next particle that should be inserted (needs to be stored across time steps).
Detailed Description
It's an insertion boundary which has cuboidal shape (yes, 'CuboidalInsertionBoundary' would have been the correct name).
Constructor & Destructor Documentation
CubeInsertionBoundary() [1/2]
CubeInsertionBoundary::CubeInsertionBoundary ()
Constructor; sets everything to 0.
Default constructor; sets every data member to 0.
                                              : InsertionBoundary()
 {
     posMin_ = Vec3D(0.0, 0.0, 0.0);
     posMax_ = Vec3D(0.0, 0.0, 0.0);
 }
References posMax_, and posMin_.
Referenced by copy().
CubeInsertionBoundary() [2/2]
CubeInsertionBoundary::CubeInsertionBoundary (const CubeInsertionBoundary & other)
Copy constructor with deep copy.
Copy constructor
         : InsertionBoundary(other)
 {
     posMin_ = other.posMin_;
     posMax_ = other.posMax_;
 }
References posMax_, and posMin_.
~CubeInsertionBoundary()
CubeInsertionBoundary::~CubeInsertionBoundary () override default
Destructor: default destructor.
Destructor. Since there are no pointers in this class, there is no need for any actions here.
Member Function Documentation
copy()
CubeInsertionBoundary * CubeInsertionBoundary::copy () const override virtual
Creates a copy on the heap and returns a pointer.
Copy method; creates a copy on the heap and returns its pointer.
Returns
pointer to the copy on the heap
Implements BaseBoundary.
 {
 #ifdef DEBUG_CONSTRUCTOR
     std::cout << "CubeInsertionBoundary::copy() const finished" << std::endl;
 #endif
     return new CubeInsertionBoundary(*this);
 }
References CubeInsertionBoundary().
getName()
std::string CubeInsertionBoundary::getName () const override private virtual
Returns the name of the object.
Returns the name of the object class
Returns
the object's class' name, i.e. 'CubeInsertionBoundary'
Implements BaseObject.
 {
     return "CubeInsertionBoundary";
 }
placeParticle()
void CubeInsertionBoundary::placeParticle (BaseParticle * p, RNG & random) override virtual
Generates a random position, velocity for the particle p.
places a particle with random position (although within the boundary, of course), velocity and radius and returns its pointer.
Parameters
[in] random Random number generator
Implements InsertionBoundary.
 {
     Vec3D pos, vel;
     pos.X = random.getRandomNumber(posMin_.X, posMax_.X);
     pos.Y = random.getRandomNumber(posMin_.Y, posMax_.Y);
     pos.Z = random.getRandomNumber(posMin_.Z, posMax_.Z);
     vel.X = random.getRandomNumber(velMin_.X, velMax_.X);
     vel.Y = random.getRandomNumber(velMin_.Y, velMax_.Y);
     vel.Z = random.getRandomNumber(velMin_.Z, velMax_.Z);
     p->setPosition(pos);
     p->setVelocity(vel);
 }
References RNG::getRandomNumber(), p, posMax_, posMin_, InsertionBoundary::velMax_, InsertionBoundary::velMin_, Vec3D::X, Vec3D::Y, and Vec3D::Z.
read()
void CubeInsertionBoundary::read (std::istream & is) override virtual
reads boundary properties from istream
Reads the boundary properties from an istream
Parameters
[in,out] is the istream
Implements BaseBoundary.
 {
     InsertionBoundary::read(is);
     std::string dummy;
     is >> dummy >> posMin_
        >> dummy >> posMax_;
     is >> dummy >> velMin_
        >> dummy >> velMax_;
 }
References posMax_, posMin_, InsertionBoundary::read(), oomph::Global_string_for_annotation::string(), InsertionBoundary::velMax_, and InsertionBoundary::velMin_.
Referenced by BidisperseCubeInsertionBoundary::read().
set() [1/5]
void CubeInsertionBoundary::set (BaseParticle & particleToCopy, unsigned int maxFailed, Vec3D posMin, Vec3D posMax, Vec3D velMin, Vec3D velMax, Mdouble rMin, Mdouble rMax)
old style set function which assumes a uniform psd.
 {
     PSD uniformPSD;
     uniformPSD.setDistributionUniform(rMin, rMax, 2);
     setPSD(uniformPSD);
     set(particleToCopy, maxFailed, posMin, posMax, velMin, velMax);
 }
References set(), PSD::setDistributionUniform(), and InsertionBoundary::setPSD().
set() [2/5]
void CubeInsertionBoundary::set (BaseParticle & particleToCopy, unsigned int maxFailed, Vec3D posMin, Vec3D posMax, Vec3D velMin = {0,0,0}, Vec3D velMax = {0,0,0})
 {
     set(&particleToCopy, maxFailed, posMin, posMax, velMin, velMax);
 }
References set().
set() [3/5]
void CubeInsertionBoundary::set (BaseParticle * particleToCopy, unsigned int maxFailed, Vec3D posMin, Vec3D posMax, Vec3D velMin, Vec3D velMax, Mdouble rMin, Mdouble rMax)
old style set function which assumes a uniform psd.
old style set function which also assumes a uniform psd. Note if you want a specific PSD do not use but this is quicker for a uniform in size PSD
 {
     PSD uniformPSD;
     uniformPSD.setDistributionUniform(rMin, rMax, 2);
     setPSD(uniformPSD);
     set(particleToCopy, maxFailed, posMin, posMax, velMin, velMax);
 }
References set(), PSD::setDistributionUniform(), and InsertionBoundary::setPSD().
set() [4/5]
void CubeInsertionBoundary::set (BaseParticle * particleToCopy, unsigned int maxFailed, Vec3D posMin, Vec3D posMax, Vec3D velMin = {0,0,0}, Vec3D velMax = {0,0,0})
Sets the properties of the InsertionBoundary for mutliple different particle types.
Sets all the properties of the cuboidal insertion boundary.
Parameters
[in] particleToCopy Pointer to the BaseParticle which is used as a basis for the particles to be inserted
[in] maxFailed The maximum number of times the insertion of a particle may be tried and failed before the insertion of particles is considered done NB: this property is used in the parent's InsertionBoundary::checkBoundaryBeforeTimeStep().
[in] posMin First defining corner of cuboidal insertion boundary
[in] posMax Second defining corner of cuboidal insertion boundary
[in] velMin Minimum velocity of inserted particles
[in] velMax Maximum velocity of inserted particles
 {
     velMin_ = velMin;
     velMax_ = velMax;
     maxFailed_ = maxFailed;
     setParticleToCopy(particleToCopy);
     setGeometry(posMin, posMax);
 }
References InsertionBoundary::maxFailed_, setGeometry(), InsertionBoundary::setParticleToCopy(), InsertionBoundary::velMax_, and InsertionBoundary::velMin_.
Referenced by BoundariesSelfTest::BoundariesSelfTest(), FluxBoundarySelfTest::FluxBoundarySelfTest(), GranuDrum::GranuDrum(), GranuHeap::GranuHeap(), main(), protectiveWall::protectiveWall(), RotatingDrumBidisperseInitialise::RotatingDrumBidisperseInitialise(), set(), BidisperseCubeInsertionBoundary::set(), NozzleDemo::setupInitialConditions(), Drum::setupInitialConditions(), RotatingDrumWet::setupInitialConditions(), FreeCooling2DinWalls::setupInitialConditions(), StressStrainControl::setupInitialConditions(), Chutebelt::setupInitialConditions(), ConstantMassFlowMaserSelfTest::setupInitialConditions(), DistributionPhiNormalSelfTest::setupInitialConditions(), DistributionSelfTest::setupInitialConditions(), DistributionToPSDSelfTest::setupInitialConditions(), InsertionBoundarySelfTest::setupInitialConditions(), MultiplePSDSelfTest::setupInitialConditions(), NozzleSelfTest::setupInitialConditions(), PSDManualInsertionSelfTest::setupInitialConditions(), PSDSelfTest::setupInitialConditions(), FullRestartTest::setupInitialConditions(), SetDistributionPhiNormalSelfTest::setupInitialConditions(), and T_protectiveWall::T_protectiveWall().
set() [5/5]
void CubeInsertionBoundary::set (std::vector< BaseParticle * > particleToCopy, unsigned int maxFailed, Vec3D posMin, Vec3D posMax, Vec3D velMin = {0,0,0}, Vec3D velMax = {0,0,0})
Sets the properties of the InsertionBoundary for a single particle type.
Sets all the properties of the cuboidal insertion boundary.
Parameters
[in] particleToCopy vector of pointers to the BaseParticles which are used as a basis for the particle types (species) to be inserted
[in] maxFailed The maximum number of times the insertion of a particle may be tried and failed before the insertion of particles is considered done NB: this property is used in the parent's InsertionBoundary::checkBoundaryBeforeTimeStep().
[in] posMin First defining corner of cuboidal insertion boundary
[in] posMax Second defining corner of cuboidal insertion boundary
[in] velMin Minimum velocity of inserted particles
[in] velMax Maximum velocity of inserted particles
 {
     velMin_ = velMin;
     velMax_ = velMax;
     maxFailed_ = maxFailed;
     setParticleToCopy(particleToCopy);
     setGeometry(posMin, posMax);
 }
References InsertionBoundary::maxFailed_, setGeometry(), InsertionBoundary::setParticleToCopy(), InsertionBoundary::velMax_, and InsertionBoundary::velMin_.
setGeometry()
void CubeInsertionBoundary::setGeometry (Vec3D posMin, Vec3D posMax)
Sets the geometry (position and velocity distribution) of the CubeInsertionBoundary.
set the geometry of the Cuboidal insertion boundary.
Parameters
[in] posMin First defining corner of cuboidal insertion boundary
[in] posMax Second defining corner of cuboidal insertion boundary
 {
     posMin_ = posMin;
     posMax_ = posMax;
 }
References posMax_, and posMin_.
Referenced by set().
write()
void CubeInsertionBoundary::write (std::ostream & os) const override virtual
writes boundary properties to ostream
Writes boundary's properties to an ostream
Parameters
[in] os the ostream
Implements BaseBoundary.
 {
     InsertionBoundary::write(os);
     os << " posMin " << posMin_
        << " posMax " << posMax_
        << " velMin " << velMin_
        << " velMax " << velMax_;
 }
References posMax_, posMin_, InsertionBoundary::velMax_, InsertionBoundary::velMin_, and InsertionBoundary::write().
Referenced by BidisperseCubeInsertionBoundary::write().
Member Data Documentation
posMax_
Vec3D CubeInsertionBoundary::posMax_ protected
Referenced by CubeInsertionBoundary(), BidisperseCubeInsertionBoundary::generateParticle(), placeParticle(), read(), setGeometry(), and write().
posMin_
Vec3D CubeInsertionBoundary::posMin_ protected
Minimal and maximal positions defining the boundary's boundaries, and minimum and maximum velocity of the particles to be inserted.
Referenced by CubeInsertionBoundary(), BidisperseCubeInsertionBoundary::generateParticle(), placeParticle(), read(), setGeometry(), and write().
The documentation for this class was generated from the following files:
CubeInsertionBoundary.h
CubeInsertionBoundary.cc