MercuryDPM: Eigen::GeneralizedEigenSolver< MatrixType_ > Class Template Reference
Eigen::GeneralizedEigenSolver< MatrixType_ > Class Template Reference
Dense linear problems and decompositions » Reference » Eigenvalues_Module
Computes the generalized eigenvalues and eigenvectors of a pair of general matrices.
#include <GeneralizedEigenSolver.h>
Public Types
enum {
RowsAtCompileTime = MatrixType::RowsAtCompileTime , ColsAtCompileTime = MatrixType::ColsAtCompileTime , Options = internal::traits<MatrixType>::Options , MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime ,
MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime
}
typedef MatrixType_ MatrixType
Synonym for the template parameter MatrixType_.
typedef MatrixType::Scalar Scalar
Scalar type for matrices of type MatrixType.
typedef NumTraits< Scalar >::Real RealScalar
typedef Eigen::Index Index
typedef std::complex< RealScalar > ComplexScalar
Complex scalar type for MatrixType.
typedef Matrix< Scalar, ColsAtCompileTime, 1, Options &~RowMajor, MaxColsAtCompileTime, 1 > VectorType
Type for vector of real scalar values eigenvalues as returned by betas().
typedef Matrix< ComplexScalar, ColsAtCompileTime, 1, Options &~RowMajor, MaxColsAtCompileTime, 1 > ComplexVectorType
Type for vector of complex scalar values eigenvalues as returned by alphas().
typedef CwiseBinaryOp< internal::scalar_quotient_op< ComplexScalar, Scalar >, ComplexVectorType, VectorType > EigenvalueType
Expression type for the eigenvalues as returned by eigenvalues().
typedef Matrix< ComplexScalar, RowsAtCompileTime, ColsAtCompileTime, Options, MaxRowsAtCompileTime, MaxColsAtCompileTime > EigenvectorsType
Type for matrix of eigenvectors as returned by eigenvectors().
Public Member Functions
GeneralizedEigenSolver ()
Default constructor.
GeneralizedEigenSolver (Index size)
Default constructor with memory preallocation.
GeneralizedEigenSolver (const MatrixType &A, const MatrixType &B, bool computeEigenvectors=true)
Constructor; computes the generalized eigendecomposition of given matrix pair.
EigenvectorsType eigenvectors () const
Returns the computed generalized eigenvectors.
EigenvalueType eigenvalues () const
Returns an expression of the computed generalized eigenvalues.
const ComplexVectorType & alphas () const
const VectorType & betas () const
GeneralizedEigenSolver & compute (const MatrixType &A, const MatrixType &B, bool computeEigenvectors=true)
Computes generalized eigendecomposition of given matrix.
ComputationInfo info () const
GeneralizedEigenSolver & setMaxIterations (Index maxIters)
Protected Attributes
EigenvectorsType m_eivec
ComplexVectorType m_alphas
VectorType m_betas
bool m_computeEigenvectors
bool m_isInitialized
RealQZ< MatrixType > m_realQZ
ComplexVectorType m_tmp
Detailed Description
template<typename MatrixType_>
class Eigen::GeneralizedEigenSolver< MatrixType_ >
Computes the generalized eigenvalues and eigenvectors of a pair of general matrices.
\eigenvalues_module
Template Parameters
MatrixType_ the type of the matrices of which we are computing the eigen-decomposition; this is expected to be an instantiation of the Matrix class template. Currently, only real matrices are supported.
The generalized eigenvalues and eigenvectors of a matrix pair \(A \) and \(B \) are scalars \(\lambda \) and vectors \(v \) such that \(Av = \lambda Bv \). If \(D \) is a diagonal matrix with the eigenvalues on the diagonal, and \(V \) is a matrix with the eigenvectors as its columns, then \(A V = B V D \). The matrix \(V \) is almost always invertible, in which case we have \(A = B V D V^{-1} \). This is called the generalized eigen-decomposition.
The generalized eigenvalues and eigenvectors of a matrix pair may be complex, even when the matrices are real. Moreover, the generalized eigenvalue might be infinite if the matrix B is singular. To workaround this difficulty, the eigenvalues are provided as a pair of complex \(\alpha \) and real \(\beta \) such that: \(\lambda_i = \alpha_i / \beta_i \). If \(\beta_i \) is (nearly) zero, then one can consider the well defined left eigenvalue \(\mu = \beta_i / \alpha_i\) such that: \(\mu_i A v_i = B v_i \), or even \(\mu_i u_i^T A = u_i^T B \) where \(u_i \) is called the left eigenvector.
Call the function compute() to compute the generalized eigenvalues and eigenvectors of a given matrix pair. Alternatively, you can use the GeneralizedEigenSolver(const MatrixType&, const MatrixType&, bool) constructor which computes the eigenvalues and eigenvectors at construction time. Once the eigenvalue and eigenvectors are computed, they can be retrieved with the eigenvalues() and eigenvectors() functions.
Here is an usage example of this class: Example:
GeneralizedEigenSolver<MatrixXf> ges;
MatrixXf A = MatrixXf::Random(4, 4);
MatrixXf B = MatrixXf::Random(4, 4);
ges.compute(A, B);
cout << "The (complex) numerators of the generalzied eigenvalues are: " << ges.alphas().transpose() << endl;
cout << "The (real) denominatore of the generalzied eigenvalues are: " << ges.betas().transpose() << endl;
cout << "The (complex) generalzied eigenvalues are (alphas./beta): " << ges.eigenvalues().transpose() << endl;
Output:
See also
MatrixBase::eigenvalues(), class ComplexEigenSolver, class SelfAdjointEigenSolver
Member Typedef Documentation
ComplexScalar
template<typename MatrixType_ > typedef std::complex<RealScalar> Eigen::GeneralizedEigenSolver< MatrixType_ >::ComplexScalar
Complex scalar type for MatrixType.
This is std::complex<Scalar> if Scalar is real (e.g., float or double) and just Scalar if Scalar is complex.
ComplexVectorType
template<typename MatrixType_ > typedef Matrix<ComplexScalar, ColsAtCompileTime, 1, Options & ~RowMajor, MaxColsAtCompileTime, 1> Eigen::GeneralizedEigenSolver< MatrixType_ >::ComplexVectorType
Type for vector of complex scalar values eigenvalues as returned by alphas().
This is a column vector with entries of type ComplexScalar. The length of the vector is the size of MatrixType.
EigenvalueType
template<typename MatrixType_ > typedef CwiseBinaryOp<internal::scalar_quotient_op<ComplexScalar, Scalar>, ComplexVectorType, VectorType> Eigen::GeneralizedEigenSolver< MatrixType_ >::EigenvalueType
Expression type for the eigenvalues as returned by eigenvalues().
EigenvectorsType
template<typename MatrixType_ > typedef Matrix<ComplexScalar, RowsAtCompileTime, ColsAtCompileTime, Options, MaxRowsAtCompileTime, MaxColsAtCompileTime> Eigen::GeneralizedEigenSolver< MatrixType_ >::EigenvectorsType
Type for matrix of eigenvectors as returned by eigenvectors().
This is a square matrix with entries of type ComplexScalar. The size is the same as the size of MatrixType.
Index
template<typename MatrixType_ > typedef Eigen::Index Eigen::GeneralizedEigenSolver< MatrixType_ >::Index
Deprecated:
since Eigen 3.3
MatrixType
template<typename MatrixType_ > typedef MatrixType_ Eigen::GeneralizedEigenSolver< MatrixType_ >::MatrixType
Synonym for the template parameter MatrixType_.
RealScalar
template<typename MatrixType_ > typedef NumTraits<Scalar>::Real Eigen::GeneralizedEigenSolver< MatrixType_ >::RealScalar
Scalar
template<typename MatrixType_ > typedef MatrixType::Scalar Eigen::GeneralizedEigenSolver< MatrixType_ >::Scalar
Scalar type for matrices of type MatrixType.
VectorType
template<typename MatrixType_ > typedef Matrix<Scalar, ColsAtCompileTime, 1, Options & ~RowMajor, MaxColsAtCompileTime, 1> Eigen::GeneralizedEigenSolver< MatrixType_ >::VectorType
Type for vector of real scalar values eigenvalues as returned by betas().
This is a column vector with entries of type Scalar. The length of the vector is the size of MatrixType.
Member Enumeration Documentation
anonymous enum
template<typename MatrixType_ > anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
Options
MaxRowsAtCompileTime
MaxColsAtCompileTime
        {
     RowsAtCompileTime = MatrixType::RowsAtCompileTime,
     ColsAtCompileTime = MatrixType::ColsAtCompileTime,
     Options = internal::traits<MatrixType>::Options,
     MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime,
     MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime
   };
Constructor & Destructor Documentation
GeneralizedEigenSolver() [1/3]
template<typename MatrixType_ > Eigen::GeneralizedEigenSolver< MatrixType_ >::GeneralizedEigenSolver () inline
Default constructor.
The default constructor is useful in cases in which the user intends to perform decompositions via EigenSolver::compute(const MatrixType&, bool).
See also
compute() for an example.
       : m_eivec(), m_alphas(), m_betas(), m_computeEigenvectors(false), m_isInitialized(false), m_realQZ() {}
GeneralizedEigenSolver() [2/3]
template<typename MatrixType_ > Eigen::GeneralizedEigenSolver< MatrixType_ >::GeneralizedEigenSolver (Index size) inline explicit
Default constructor with memory preallocation.
Like the default constructor but with preallocation of the internal data according to the specified problem size.
See also
GeneralizedEigenSolver()
       : m_eivec(size, size),
         m_alphas(size),
         m_betas(size),
         m_computeEigenvectors(false),
         m_isInitialized(false),
         m_realQZ(size),
         m_tmp(size) {}
GeneralizedEigenSolver() [3/3]
template<typename MatrixType_ > Eigen::GeneralizedEigenSolver< MatrixType_ >::GeneralizedEigenSolver (const MatrixType & A, const MatrixType & B, bool computeEigenvectors = true) inline
Constructor; computes the generalized eigendecomposition of given matrix pair.
Parameters
[in] A Square matrix whose eigendecomposition is to be computed.
[in] B Square matrix whose eigendecomposition is to be computed.
[in] computeEigenvectors If true, both the eigenvectors and the eigenvalues are computed; if false, only the eigenvalues are computed.
This constructor calls compute() to compute the generalized eigenvalues and eigenvectors.
See also
compute()
       : m_eivec(A.rows(), A.cols()),
         m_alphas(A.cols()),
         m_betas(A.cols()),
         m_computeEigenvectors(false),
         m_isInitialized(false),
         m_realQZ(A.cols()),
         m_tmp(A.cols()) {
     compute(A, B, computeEigenvectors);
   }
References Eigen::GeneralizedEigenSolver< MatrixType_ >::compute().
Member Function Documentation
alphas()
template<typename MatrixType_ > const ComplexVectorType& Eigen::GeneralizedEigenSolver< MatrixType_ >::alphas () const inline
Returns
A const reference to the vectors containing the alpha values
This vector permits to reconstruct the j-th eigenvalues as alphas(i)/betas(j).
See also
betas(), eigenvalues()
{
     eigen_assert(info() == Success && "GeneralizedEigenSolver failed to compute alphas.");
     return m_alphas;
   }
References eigen_assert, Eigen::GeneralizedEigenSolver< MatrixType_ >::info(), Eigen::GeneralizedEigenSolver< MatrixType_ >::m_alphas, and Eigen::Success.
Referenced by generalized_eigensolver_assert(), and generalized_eigensolver_real().
betas()
template<typename MatrixType_ > const VectorType& Eigen::GeneralizedEigenSolver< MatrixType_ >::betas () const inline
Returns
A const reference to the vectors containing the beta values
This vector permits to reconstruct the j-th eigenvalues as alphas(i)/betas(j).
See also
alphas(), eigenvalues()
{
     eigen_assert(info() == Success && "GeneralizedEigenSolver failed to compute betas.");
     return m_betas;
   }
References eigen_assert, Eigen::GeneralizedEigenSolver< MatrixType_ >::info(), Eigen::GeneralizedEigenSolver< MatrixType_ >::m_betas, and Eigen::Success.
Referenced by generalized_eigensolver_assert(), and generalized_eigensolver_real().
compute()
template<typename MatrixType > GeneralizedEigenSolver< MatrixType > & Eigen::GeneralizedEigenSolver< MatrixType >::compute (const MatrixType & A, const MatrixType & B, bool computeEigenvectors = true)
Computes generalized eigendecomposition of given matrix.
Parameters
[in] A Square matrix whose eigendecomposition is to be computed.
[in] B Square matrix whose eigendecomposition is to be computed.
[in] computeEigenvectors If true, both the eigenvectors and the eigenvalues are computed; if false, only the eigenvalues are computed.
Returns
Reference to *this
This function computes the eigenvalues of the real matrix matrix. The eigenvalues() function can be used to retrieve them. If computeEigenvectors is true, then the eigenvectors are also computed and can be retrieved by calling eigenvectors().
The matrix is first reduced to real generalized Schur form using the RealQZ class. The generalized Schur decomposition is then used to compute the eigenvalues and eigenvectors.
The cost of the computation is dominated by the cost of the generalized Schur decomposition.
This method reuses of the allocated data in the GeneralizedEigenSolver object.
{
   using std::abs;
   using std::sqrt;
   eigen_assert(A.cols() == A.rows() && B.cols() == A.rows() && B.cols() == B.rows());
   Index size = A.cols();
   // Reduce to generalized real Schur form:
   // A = Q S Z and B = Q T Z
   m_realQZ.compute(A, B, computeEigenvectors);
   if (m_realQZ.info() == Success) {
     // Resize storage
     m_alphas.resize(size);
     m_betas.resize(size);
     if (computeEigenvectors) {
       m_eivec.resize(size, size);
       m_tmp.resize(size);
     }
     // Aliases:
     Map<VectorType> v(reinterpret_cast<Scalar*>(m_tmp.data()), size);
     ComplexVectorType& cv = m_tmp;
     const MatrixType& mS = m_realQZ.matrixS();
     const MatrixType& mT = m_realQZ.matrixT();
     Index i = 0;
     while (i < size) {
       if (i == size - 1 || mS.coeff(i + 1, i) == Scalar(0)) {
         // Real eigenvalue
         m_alphas.coeffRef(i) = mS.diagonal().coeff(i);
         m_betas.coeffRef(i) = mT.diagonal().coeff(i);
         if (computeEigenvectors) {
           v.setConstant(Scalar(0.0));
           v.coeffRef(i) = Scalar(1.0);
           // For singular eigenvalues do nothing more
           if (abs(m_betas.coeffRef(i)) >= (std::numeric_limits<RealScalar>::min)()) {
             // Non-singular eigenvalue
             const Scalar alpha = real(m_alphas.coeffRef(i));
             const Scalar beta = m_betas.coeffRef(i);
             for (Index j = i - 1; j >= 0; j--) {
               const Index st = j + 1;
               const Index sz = i - j;
               if (j > 0 && mS.coeff(j, j - 1) != Scalar(0)) {
                 // 2x2 block
                 Matrix<Scalar, 2, 1> rhs = (alpha * mT.template block<2, Dynamic>(j - 1, st, 2, sz) -
                                             beta * mS.template block<2, Dynamic>(j - 1, st, 2, sz))
                                                .lazyProduct(v.segment(st, sz));
                 Matrix<Scalar, 2, 2> lhs =
                     beta * mS.template block<2, 2>(j - 1, j - 1) - alpha * mT.template block<2, 2>(j - 1, j - 1);
                 v.template segment<2>(j - 1) = lhs.partialPivLu().solve(rhs);
                 j--;
               } else {
                 v.coeffRef(j) = -v.segment(st, sz)
                                      .transpose()
                                      .cwiseProduct(beta * mS.block(j, st, 1, sz) - alpha * mT.block(j, st, 1, sz))
                                      .sum() /
                                 (beta * mS.coeffRef(j, j) - alpha * mT.coeffRef(j, j));
               }
             }
           }
           m_eivec.col(i).real().noalias() = m_realQZ.matrixZ().transpose() * v;
           m_eivec.col(i).real().normalize();
           m_eivec.col(i).imag().setConstant(0);
         }
         ++i;
       } else {
         // We need to extract the generalized eigenvalues of the pair of a general 2x2 block S and a positive diagonal
         // 2x2 block T Then taking beta=T_00*T_11, we can avoid any division, and alpha is the eigenvalues of A = (U^-1
         // * S * U) * diag(T_11,T_00):
         // T =  [a 0]
         //      [0 b]
         RealScalar a = mT.diagonal().coeff(i), b = mT.diagonal().coeff(i + 1);
         const RealScalar beta = m_betas.coeffRef(i) = m_betas.coeffRef(i + 1) = a * b;
         // ^^ NOTE: using diagonal()(i) instead of coeff(i,i) workarounds a MSVC bug.
         Matrix<RealScalar, 2, 2> S2 = mS.template block<2, 2>(i, i) * Matrix<Scalar, 2, 1>(b, a).asDiagonal();
         Scalar p = Scalar(0.5) * (S2.coeff(0, 0) - S2.coeff(1, 1));
         Scalar z = sqrt(abs(p * p + S2.coeff(1, 0) * S2.coeff(0, 1)));
         const ComplexScalar alpha = ComplexScalar(S2.coeff(1, 1) + p, (beta > 0) ? z : -z);
         m_alphas.coeffRef(i) = conj(alpha);
         m_alphas.coeffRef(i + 1) = alpha;
         if (computeEigenvectors) {
           // Compute eigenvector in position (i+1) and then position (i) is just the conjugate
           cv.setZero();
           cv.coeffRef(i + 1) = Scalar(1.0);
           // here, the "static_cast" workaround expression template issues.
           cv.coeffRef(i) = -(static_cast<Scalar>(beta * mS.coeffRef(i, i + 1)) - alpha * mT.coeffRef(i, i + 1)) /
                            (static_cast<Scalar>(beta * mS.coeffRef(i, i)) - alpha * mT.coeffRef(i, i));
           for (Index j = i - 1; j >= 0; j--) {
             const Index st = j + 1;
             const Index sz = i + 1 - j;
             if (j > 0 && mS.coeff(j, j - 1) != Scalar(0)) {
               // 2x2 block
               Matrix<ComplexScalar, 2, 1> rhs = (alpha * mT.template block<2, Dynamic>(j - 1, st, 2, sz) -
                                                  beta * mS.template block<2, Dynamic>(j - 1, st, 2, sz))
                                                     .lazyProduct(cv.segment(st, sz));
               Matrix<ComplexScalar, 2, 2> lhs =
                   beta * mS.template block<2, 2>(j - 1, j - 1) - alpha * mT.template block<2, 2>(j - 1, j - 1);
               cv.template segment<2>(j - 1) = lhs.partialPivLu().solve(rhs);
               j--;
             } else {
               cv.coeffRef(j) = cv.segment(st, sz)
                                    .transpose()
                                    .cwiseProduct(beta * mS.block(j, st, 1, sz) - alpha * mT.block(j, st, 1, sz))
                                    .sum() /
                                (alpha * mT.coeffRef(j, j) - static_cast<Scalar>(beta * mS.coeffRef(j, j)));
             }
           }
           m_eivec.col(i + 1).noalias() = (m_realQZ.matrixZ().transpose() * cv);
           m_eivec.col(i + 1).normalize();
           m_eivec.col(i) = m_eivec.col(i + 1).conjugate();
         }
         i += 2;
       }
     }
   }
   m_computeEigenvectors = computeEigenvectors;
   m_isInitialized = true;
   return *this;
 }
References a, abs(), alpha, b, beta, block< 2, Dynamic >(), Eigen::PlainObjectBase< Derived >::coeff(), Eigen::Matrix< Scalar_, Rows_, Cols_, Options_, MaxRows_, MaxCols_ >::coeffRef(), Eigen::PlainObjectBase< Derived >::cols(), Eigen::RealQZ< MatrixType_ >::compute(), Eigen::conj(), Eigen::PlainObjectBase< Derived >::data(), eigen_assert, i, Eigen::RealQZ< MatrixType_ >::info(), j, Eigen::GeneralizedEigenSolver< MatrixType_ >::m_alphas, Eigen::GeneralizedEigenSolver< MatrixType_ >::m_betas, Eigen::GeneralizedEigenSolver< MatrixType_ >::m_computeEigenvectors, Eigen::GeneralizedEigenSolver< MatrixType_ >::m_eivec, Eigen::GeneralizedEigenSolver< MatrixType_ >::m_isInitialized, Eigen::GeneralizedEigenSolver< MatrixType_ >::m_realQZ, Eigen::GeneralizedEigenSolver< MatrixType_ >::m_tmp, Eigen::RealQZ< MatrixType_ >::matrixS(), Eigen::RealQZ< MatrixType_ >::matrixT(), Eigen::RealQZ< MatrixType_ >::matrixZ(), min, p, Eigen::real(), Eigen::PlainObjectBase< Derived >::resize(), Eigen::PlainObjectBase< Derived >::rows(), Eigen::PlainObjectBase< Derived >::setConstant(), Eigen::PlainObjectBase< Derived >::setZero(), size, sqrt(), Eigen::Success, and v.
Referenced by generalized_eigensolver_assert(), generalized_eigensolver_real(), and Eigen::GeneralizedEigenSolver< MatrixType_ >::GeneralizedEigenSolver().
eigenvalues()
template<typename MatrixType_ > EigenvalueType Eigen::GeneralizedEigenSolver< MatrixType_ >::eigenvalues () const inline
Returns an expression of the computed generalized eigenvalues.
Returns
An expression of the column vector containing the eigenvalues.
It is a shortcut for
this->alphas().cwiseQuotient(this->betas());
Not that betas might contain zeros. It is therefore not recommended to use this function, but rather directly deal with the alphas and betas vectors.
Precondition
Either the constructor GeneralizedEigenSolver(const MatrixType&,const MatrixType&,bool) or the member function compute(const MatrixType&,const MatrixType&,bool) has been called before.
The eigenvalues are repeated according to their algebraic multiplicity, so there are as many eigenvalues as rows in the matrix. The eigenvalues are not sorted in any particular order.
See also
alphas(), betas(), eigenvectors()
{
     eigen_assert(info() == Success && "GeneralizedEigenSolver failed to compute eigenvalues.");
     return EigenvalueType(m_alphas, m_betas);
   }
References eigen_assert, Eigen::GeneralizedEigenSolver< MatrixType_ >::info(), Eigen::GeneralizedEigenSolver< MatrixType_ >::m_alphas, Eigen::GeneralizedEigenSolver< MatrixType_ >::m_betas, and Eigen::Success.
Referenced by generalized_eigensolver_assert(), and generalized_eigensolver_real().
eigenvectors()
template<typename MatrixType_ > EigenvectorsType Eigen::GeneralizedEigenSolver< MatrixType_ >::eigenvectors () const inline
Returns the computed generalized eigenvectors.
Returns
Matrix whose columns are the (possibly complex) right eigenvectors. i.e. the eigenvectors that solve (A - l*B)x = 0. The ordering matches the eigenvalues.
Precondition
Either the constructor GeneralizedEigenSolver(const MatrixType&,const MatrixType&, bool) or the member function compute(const MatrixType&, const MatrixType& bool) has been called before, and computeEigenvectors was set to true (the default).
See also
eigenvalues()
{
     eigen_assert(info() == Success && "GeneralizedEigenSolver failed to compute eigenvectors");
     eigen_assert(m_computeEigenvectors && "Eigenvectors for GeneralizedEigenSolver were not calculated");
     return m_eivec;
   }
References eigen_assert, Eigen::GeneralizedEigenSolver< MatrixType_ >::info(), Eigen::GeneralizedEigenSolver< MatrixType_ >::m_computeEigenvectors, Eigen::GeneralizedEigenSolver< MatrixType_ >::m_eivec, and Eigen::Success.
Referenced by generalized_eigensolver_assert(), and generalized_eigensolver_real().
info()
template<typename MatrixType_ > ComputationInfo Eigen::GeneralizedEigenSolver< MatrixType_ >::info () const inline
{
     eigen_assert(m_isInitialized && "EigenSolver is not initialized.");
     return m_realQZ.info();
   }
References eigen_assert, Eigen::RealQZ< MatrixType_ >::info(), Eigen::GeneralizedEigenSolver< MatrixType_ >::m_isInitialized, and Eigen::GeneralizedEigenSolver< MatrixType_ >::m_realQZ.
Referenced by Eigen::GeneralizedEigenSolver< MatrixType_ >::alphas(), Eigen::GeneralizedEigenSolver< MatrixType_ >::betas(), Eigen::GeneralizedEigenSolver< MatrixType_ >::eigenvalues(), Eigen::GeneralizedEigenSolver< MatrixType_ >::eigenvectors(), and generalized_eigensolver_assert().
setMaxIterations()
template<typename MatrixType_ > GeneralizedEigenSolver& Eigen::GeneralizedEigenSolver< MatrixType_ >::setMaxIterations (Index maxIters) inline
Sets the maximal number of iterations allowed.
{
     m_realQZ.setMaxIterations(maxIters);
     return *this;
   }
References Eigen::GeneralizedEigenSolver< MatrixType_ >::m_realQZ, and Eigen::RealQZ< MatrixType_ >::setMaxIterations().
Referenced by generalized_eigensolver_assert().
Member Data Documentation
m_alphas
template<typename MatrixType_ > ComplexVectorType Eigen::GeneralizedEigenSolver< MatrixType_ >::m_alphas protected
Referenced by Eigen::GeneralizedEigenSolver< MatrixType_ >::alphas(), Eigen::GeneralizedEigenSolver< MatrixType_ >::compute(), and Eigen::GeneralizedEigenSolver< MatrixType_ >::eigenvalues().
m_betas
template<typename MatrixType_ > VectorType Eigen::GeneralizedEigenSolver< MatrixType_ >::m_betas protected
Referenced by Eigen::GeneralizedEigenSolver< MatrixType_ >::betas(), Eigen::GeneralizedEigenSolver< MatrixType_ >::compute(), and Eigen::GeneralizedEigenSolver< MatrixType_ >::eigenvalues().
m_computeEigenvectors
template<typename MatrixType_ > bool Eigen::GeneralizedEigenSolver< MatrixType_ >::m_computeEigenvectors protected
Referenced by Eigen::GeneralizedEigenSolver< MatrixType_ >::compute(), and Eigen::GeneralizedEigenSolver< MatrixType_ >::eigenvectors().
m_eivec
template<typename MatrixType_ > EigenvectorsType Eigen::GeneralizedEigenSolver< MatrixType_ >::m_eivec protected
Referenced by Eigen::GeneralizedEigenSolver< MatrixType_ >::compute(), and Eigen::GeneralizedEigenSolver< MatrixType_ >::eigenvectors().
m_isInitialized
template<typename MatrixType_ > bool Eigen::GeneralizedEigenSolver< MatrixType_ >::m_isInitialized protected
Referenced by Eigen::GeneralizedEigenSolver< MatrixType_ >::compute(), and Eigen::GeneralizedEigenSolver< MatrixType_ >::info().
m_realQZ
template<typename MatrixType_ > RealQZ<MatrixType> Eigen::GeneralizedEigenSolver< MatrixType_ >::m_realQZ protected
Referenced by Eigen::GeneralizedEigenSolver< MatrixType_ >::compute(), Eigen::GeneralizedEigenSolver< MatrixType_ >::info(), and Eigen::GeneralizedEigenSolver< MatrixType_ >::setMaxIterations().
m_tmp
template<typename MatrixType_ > ComplexVectorType Eigen::GeneralizedEigenSolver< MatrixType_ >::m_tmp protected
Referenced by Eigen::GeneralizedEigenSolver< MatrixType_ >::compute().
The documentation for this class was generated from the following file:
GeneralizedEigenSolver.h