MercuryDPM: Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV2D > Struct Template Reference
Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV2D > Struct Template Reference
#include <TensorConvolutionSycl.h>
Public Types
typedef cl::sycl::accessor< CoeffReturnType, 1, cl::sycl::access::mode::read_write, cl::sycl::access::target::local > Local_accessor
Public Member Functions
EigenConvolutionKernel (Local_accessor local_acc_, Evaluator device_evaluator_, Kernel_accessor kernel_filter_, Buffer_accessor buffer_acc_, internal::IndexMapper< Index, InputDims, 2, Evaluator::Layout > indexMapper_, const cl::sycl::range< 2 > kernel_size_, const cl::sycl::range< 3 > input_range_)
template<typename BooleanDim3 >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool boundary_check (const BooleanDim3 boolean_check) const
void operator() (cl::sycl::nd_item< 3 > itemID) const
Public Attributes
Local_accessor local_acc
Evaluator device_evaluator
Kernel_accessor kernel_filter
Buffer_accessor buffer_acc
internal::IndexMapper< Index, InputDims, 2, Evaluator::Layout > indexMapper
const cl::sycl::range< 2 > kernel_size
const cl::sycl::range< 3 > input_range
Member Typedef Documentation
Local_accessor
template<typename Evaluator , typename CoeffReturnType , typename KernelType , typename Index , typename InputDims , typename Kernel_accessor , typename Buffer_accessor > typedef cl::sycl::accessor<CoeffReturnType, 1, cl::sycl::access::mode::read_write, cl::sycl::access::target::local> Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV2D >::Local_accessor
Constructor & Destructor Documentation
EigenConvolutionKernel()
template<typename Evaluator , typename CoeffReturnType , typename KernelType , typename Index , typename InputDims , typename Kernel_accessor , typename Buffer_accessor > Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV2D >::EigenConvolutionKernel (Local_accessor local_acc_, Evaluator device_evaluator_, Kernel_accessor kernel_filter_, Buffer_accessor buffer_acc_, internal::IndexMapper< Index, InputDims, 2, Evaluator::Layout > indexMapper_, const cl::sycl::range< 2 > kernel_size_, const cl::sycl::range< 3 > input_range_) inline
       : local_acc(local_acc_),
         device_evaluator(device_evaluator_),
         kernel_filter(kernel_filter_),
         buffer_acc(buffer_acc_),
         indexMapper(indexMapper_),
         kernel_size(kernel_size_),
         input_range(input_range_) {}
Member Function Documentation
boundary_check()
template<typename Evaluator , typename CoeffReturnType , typename KernelType , typename Index , typename InputDims , typename Kernel_accessor , typename Buffer_accessor > template<typename BooleanDim3 > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV2D >::boundary_check (const BooleanDim3 boolean_check) const inline
{
     return (boolean_check[0] && boolean_check[1] && boolean_check[2]);
   }
operator()()
template<typename Evaluator , typename CoeffReturnType , typename KernelType , typename Index , typename InputDims , typename Kernel_accessor , typename Buffer_accessor > void Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV2D >::operator() (cl::sycl::nd_item< 3 > itemID) const inline
{
     auto buffer_ptr = buffer_acc;
     auto kernel_ptr = kernel_filter;
     // the required row to be calculated for the for each plane in shered memory
     const auto num_input = cl::sycl::range<2>{
         (cl::sycl::range<2>(itemID.get_local_range()[0], itemID.get_local_range()[1]) + kernel_size - 1)};
     const size_t plane_input_offset = indexMapper.mapGpuInputPlaneToTensorInputOffset(itemID.get_global_id(2));
     const size_t plane_kernel_offset = itemID.get_local_id(2) * num_input[1];
     const auto input_offset = cl::sycl::range<2>{itemID.get_group(0) * itemID.get_local_range()[0],
                                                  itemID.get_group(1) * itemID.get_local_range()[1]};
     // fill the local memory
     bool in_range_dim2 = itemID.get_global_id(2) < input_range[2];
     for (size_t j = itemID.get_local_id(1); j < num_input[1]; j += itemID.get_local_range()[1]) {
       const size_t local_input_offset = num_input[0] * (j + plane_kernel_offset);
       bool in_range_dim1 = ((j + input_offset[1]) < (input_range[1] + kernel_size[1] - 1));
       for (size_t i = itemID.get_local_id(0); i < num_input[0]; i += itemID.get_local_range()[0]) {
         const size_t local_index = i + local_input_offset;
         const size_t tensor_index = plane_input_offset + indexMapper.mapGpuInputKernelToTensorInputOffset(
                                                              i + input_offset[0], j + input_offset[1]);
         local_acc[local_index] =
             (((i + input_offset[0]) < (input_range[0] + kernel_size[0] - 1)) && in_range_dim1 && in_range_dim2)
                 ? device_evaluator.coeff(tensor_index)
                 : CoeffReturnType(0);
       }
     }
     itemID.barrier(cl::sycl::access::fence_space::local_space);
     // output offset start for each thread
     const auto output_offset = cl::sycl::range<2>{itemID.get_group(0) * itemID.get_local_range()[0],
                                                   itemID.get_group(1) * itemID.get_local_range()[1]};
     if (boundary_check(itemID.get_global_id() < input_range)) {
       CoeffReturnType result = static_cast<CoeffReturnType>(0);
       for (size_t j = 0; j < kernel_size[1]; j++) {
         size_t kernel_offset = kernel_size[0] * j;
         const size_t index =
             (num_input[0] * (plane_kernel_offset + j + itemID.get_local_id(1))) + itemID.get_local_id(0);
         for (size_t i = 0; i < kernel_size[0]; i++) {
           result += (local_acc[i + index] * kernel_ptr[i + kernel_offset]);
         }
       }
       const size_t tensor_index =
           indexMapper.mapGpuOutputPlaneToTensorOutputOffset(itemID.get_global_id(2)) +
           indexMapper.mapGpuOutputKernelToTensorOutputOffset(itemID.get_local_id(0) + output_offset[0],
                                                              itemID.get_local_id(1) + output_offset[1]);
       buffer_ptr[tensor_index] = result;
     }
   }
References i, j, Eigen::internal::IndexMapper< Index, InputDims, NumKernelDims, Layout >::mapGpuInputKernelToTensorInputOffset(), Eigen::internal::IndexMapper< Index, InputDims, NumKernelDims, Layout >::mapGpuInputPlaneToTensorInputOffset(), Eigen::internal::IndexMapper< Index, InputDims, NumKernelDims, Layout >::mapGpuOutputKernelToTensorOutputOffset(), and Eigen::internal::IndexMapper< Index, InputDims, NumKernelDims, Layout >::mapGpuOutputPlaneToTensorOutputOffset().
Member Data Documentation
buffer_acc
template<typename Evaluator , typename CoeffReturnType , typename KernelType , typename Index , typename InputDims , typename Kernel_accessor , typename Buffer_accessor > Buffer_accessor Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV2D >::buffer_acc
device_evaluator
template<typename Evaluator , typename CoeffReturnType , typename KernelType , typename Index , typename InputDims , typename Kernel_accessor , typename Buffer_accessor > Evaluator Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV2D >::device_evaluator
indexMapper
template<typename Evaluator , typename CoeffReturnType , typename KernelType , typename Index , typename InputDims , typename Kernel_accessor , typename Buffer_accessor > internal::IndexMapper<Index, InputDims, 2, Evaluator::Layout> Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV2D >::indexMapper
input_range
template<typename Evaluator , typename CoeffReturnType , typename KernelType , typename Index , typename InputDims , typename Kernel_accessor , typename Buffer_accessor > const cl::sycl::range<3> Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV2D >::input_range
kernel_filter
template<typename Evaluator , typename CoeffReturnType , typename KernelType , typename Index , typename InputDims , typename Kernel_accessor , typename Buffer_accessor > Kernel_accessor Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV2D >::kernel_filter
kernel_size
template<typename Evaluator , typename CoeffReturnType , typename KernelType , typename Index , typename InputDims , typename Kernel_accessor , typename Buffer_accessor > const cl::sycl::range<2> Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV2D >::kernel_size
local_acc
template<typename Evaluator , typename CoeffReturnType , typename KernelType , typename Index , typename InputDims , typename Kernel_accessor , typename Buffer_accessor > Local_accessor Eigen::EigenConvolutionKernel< Evaluator, CoeffReturnType, KernelType, Index, InputDims, Kernel_accessor, Buffer_accessor, convolution_type::CONV2D >::local_acc
The documentation for this struct was generated from the following file:
TensorConvolutionSycl.h