MercuryDPM: SolnForPoisson Namespace Reference
SolnForPoisson Namespace Reference
Namespace for exact solution for Poisson equation.
Functions
void get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void source_function (const Vector< double > &x, double &source)
Source function required to make the solution above an exact solution.
void prescribed_flux_on_fixed_x_boundary (const Vector< double > &x, double &flux)
Flux required by the exact solution on a boundary on which x is fixed.
Variables
double Alpha =4.0
Parameter for steepness of "step".
double TanPhi =1.0
Parameter for angle Phi of "step".
Detailed Description
Namespace for exact solution for Poisson equation.
/////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////
Function Documentation
get_exact_u()
void SolnForPoisson::get_exact_u (const Vector< double > & x, Vector< double > & u)
Exact solution as a Vector.
  {
   u[0]=tanh(1.0-Alpha*(TanPhi*x[0]-x[1]));
  }
References Alpha, Eigen::bfloat16_impl::tanh(), TanPhi, and plotDoE::x.
Referenced by FluxPoissonMGProblem< ELEMENT, MESH >::doc_solution().
prescribed_flux_on_fixed_x_boundary()
void SolnForPoisson::prescribed_flux_on_fixed_x_boundary (const Vector< double > & x, double & flux)
Flux required by the exact solution on a boundary on which x is fixed.
  {
   // The outer unit normal to the boundary is (1,0)
   double N[2] = {1.0,0.0};
   // The flux in terms of the normal is
   flux = -(1.0-pow(tanh(-1.0+Alpha*(TanPhi*x[0]-x[1])),2.0))*
    Alpha*TanPhi*N[0]+(1.0-pow(tanh(-1.0+Alpha*(TanPhi*x[0]-x[1])),2.0))*
    Alpha*N[1];
  }
References Alpha, ProblemParameters::flux(), N, Eigen::bfloat16_impl::pow(), Eigen::bfloat16_impl::tanh(), TanPhi, and plotDoE::x.
Referenced by FluxPoissonMGProblem< ELEMENT, MESH >::create_flux_elements().
source_function()
void SolnForPoisson::source_function (const Vector< double > & x, double & source)
Source function required to make the solution above an exact solution.
  {
   source = 2.0*tanh(-1.0+Alpha*(TanPhi*x[0]-x[1]))*
    (1.0-pow(tanh(-1.0+Alpha*(TanPhi*x[0]-x[1])),2.0))*
    Alpha*Alpha*TanPhi*TanPhi+2.0*tanh(-1.0+Alpha*(TanPhi*x[0]-x[1]))*
    (1.0-pow(tanh(-1.0+Alpha*(TanPhi*x[0]-x[1])),2.0))*Alpha*Alpha;
  }
References Alpha, Eigen::bfloat16_impl::pow(), TestProblem::source(), Eigen::bfloat16_impl::tanh(), TanPhi, and plotDoE::x.
Referenced by main(), and FluxPoissonMGProblem< ELEMENT, MESH >::make_new_problem().
Variable Documentation
Alpha
double SolnForPoisson::Alpha =4.0
Parameter for steepness of "step".
Referenced by get_exact_u(), prescribed_flux_on_fixed_x_boundary(), and source_function().
TanPhi
double SolnForPoisson::TanPhi =1.0
Parameter for angle Phi of "step".
Referenced by get_exact_u(), prescribed_flux_on_fixed_x_boundary(), and source_function().