MercuryDPM: Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ > Class Template Reference
Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ > Class Template Reference
Geometry » Reference » Geometry_Module
A hyperplane.
#include <Hyperplane.h>
Public Types
typedef Scalar_ Scalar
typedef NumTraits< Scalar >::Real RealScalar
typedef Eigen::Index Index
typedef Matrix< Scalar, AmbientDimAtCompileTime, 1 > VectorType
typedef Matrix< Scalar, Index(AmbientDimAtCompileTime)==Dynamic ? Dynamic :Index(AmbientDimAtCompileTime)+1, 1, Options > Coefficients
typedef Block< Coefficients, AmbientDimAtCompileTime, 1 > NormalReturnType
typedef const Block< const Coefficients, AmbientDimAtCompileTime, 1 > ConstNormalReturnType
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW_IF_VECTORIZABLE_FIXED_SIZE (Scalar_, AmbientDim_==Dynamic ? Dynamic :AmbientDim_+1) enum
EIGEN_DEVICE_FUNC Hyperplane ()
template<int OtherOptions>
EIGEN_DEVICE_FUNC Hyperplane (const Hyperplane< Scalar, AmbientDimAtCompileTime, OtherOptions > &other)
EIGEN_DEVICE_FUNC Hyperplane (Index _dim)
EIGEN_DEVICE_FUNC Hyperplane (const VectorType &n, const VectorType &e)
EIGEN_DEVICE_FUNC Hyperplane (const VectorType &n, const Scalar &d)
EIGEN_DEVICE_FUNC Hyperplane (const ParametrizedLine< Scalar, AmbientDimAtCompileTime > &parametrized)
EIGEN_DEVICE_FUNC ~Hyperplane ()
EIGEN_DEVICE_FUNC Index dim () const
EIGEN_DEVICE_FUNC void normalize (void)
EIGEN_DEVICE_FUNC Scalar signedDistance (const VectorType &p) const
EIGEN_DEVICE_FUNC Scalar absDistance (const VectorType &p) const
EIGEN_DEVICE_FUNC VectorType projection (const VectorType &p) const
EIGEN_DEVICE_FUNC ConstNormalReturnType normal () const
EIGEN_DEVICE_FUNC NormalReturnType normal ()
EIGEN_DEVICE_FUNC const Scalar & offset () const
EIGEN_DEVICE_FUNC Scalar & offset ()
EIGEN_DEVICE_FUNC const Coefficients & coeffs () const
EIGEN_DEVICE_FUNC Coefficients & coeffs ()
EIGEN_DEVICE_FUNC VectorType intersection (const Hyperplane &other) const
template<typename XprType >
EIGEN_DEVICE_FUNC Hyperplane & transform (const MatrixBase< XprType > &mat, TransformTraits traits=Affine)
template<int TrOptions>
EIGEN_DEVICE_FUNC Hyperplane & transform (const Transform< Scalar, AmbientDimAtCompileTime, Affine, TrOptions > &t, TransformTraits traits=Affine)
template<typename NewScalarType >
EIGEN_DEVICE_FUNC internal::cast_return_type< Hyperplane, Hyperplane< NewScalarType, AmbientDimAtCompileTime, Options > >::type cast () const
template<typename OtherScalarType , int OtherOptions>
EIGEN_DEVICE_FUNC Hyperplane (const Hyperplane< OtherScalarType, AmbientDimAtCompileTime, OtherOptions > &other)
template<int OtherOptions>
EIGEN_DEVICE_FUNC bool isApprox (const Hyperplane< Scalar, AmbientDimAtCompileTime, OtherOptions > &other, const typename NumTraits< Scalar >::Real &prec=NumTraits< Scalar >::dummy_precision()) const
Static Public Member Functions
static EIGEN_DEVICE_FUNC Hyperplane Through (const VectorType &p0, const VectorType &p1)
static EIGEN_DEVICE_FUNC Hyperplane Through (const VectorType &p0, const VectorType &p1, const VectorType &p2)
Protected Attributes
Coefficients m_coeffs
Detailed Description
template<typename Scalar_, int AmbientDim_, int Options_>
class Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >
A hyperplane.
\geometry_module
A hyperplane is an affine subspace of dimension n-1 in a space of dimension n. For example, a hyperplane in a plane is a line; a hyperplane in 3-space is a plane.
Template Parameters
Scalar_ the scalar type, i.e., the type of the coefficients
AmbientDim_ the dimension of the ambient space, can be a compile time value or Dynamic. Notice that the dimension of the hyperplane is AmbientDim_-1.
This class represents an hyperplane as the zero set of the implicit equation \(n \cdot x + d = 0 \) where \(n \) is a unit normal vector of the plane (linear part) and \(d \) is the distance (offset) to the origin.
Member Typedef Documentation
Coefficients
template<typename Scalar_ , int AmbientDim_, int Options_> typedef Matrix<Scalar, Index(AmbientDimAtCompileTime) == Dynamic ? Dynamic : Index(AmbientDimAtCompileTime) + 1, 1, Options> Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::Coefficients
ConstNormalReturnType
template<typename Scalar_ , int AmbientDim_, int Options_> typedef const Block<const Coefficients, AmbientDimAtCompileTime, 1> Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::ConstNormalReturnType
Index
template<typename Scalar_ , int AmbientDim_, int Options_> typedef Eigen::Index Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::Index
Deprecated:
since Eigen 3.3
NormalReturnType
template<typename Scalar_ , int AmbientDim_, int Options_> typedef Block<Coefficients, AmbientDimAtCompileTime, 1> Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::NormalReturnType
RealScalar
template<typename Scalar_ , int AmbientDim_, int Options_> typedef NumTraits<Scalar>::Real Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::RealScalar
Scalar
template<typename Scalar_ , int AmbientDim_, int Options_> typedef Scalar_ Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::Scalar
VectorType
template<typename Scalar_ , int AmbientDim_, int Options_> typedef Matrix<Scalar, AmbientDimAtCompileTime, 1> Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::VectorType
Constructor & Destructor Documentation
Hyperplane() [1/7]
template<typename Scalar_ , int AmbientDim_, int Options_> EIGEN_DEVICE_FUNC Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::Hyperplane () inline
Default constructor without initialization
 {}
Referenced by Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::cast().
Hyperplane() [2/7]
template<typename Scalar_ , int AmbientDim_, int Options_> template<int OtherOptions> EIGEN_DEVICE_FUNC Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::Hyperplane (const Hyperplane< Scalar, AmbientDimAtCompileTime, OtherOptions > & other) inline
       : m_coeffs(other.coeffs()) {}
Hyperplane() [3/7]
template<typename Scalar_ , int AmbientDim_, int Options_> EIGEN_DEVICE_FUNC Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::Hyperplane (Index _dim) inline explicit
Constructs a dynamic-size hyperplane with _dim the dimension of the ambient space
 : m_coeffs(_dim + 1) {}
Hyperplane() [4/7]
template<typename Scalar_ , int AmbientDim_, int Options_> EIGEN_DEVICE_FUNC Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::Hyperplane (const VectorType & n, const VectorType & e) inline
Construct a plane from its normal n and a point e onto the plane.
Warning
the vector normal is assumed to be normalized.
                                                                                 : m_coeffs(n.size() + 1) {
     normal() = n;
     offset() = -n.dot(e);
   }
References e(), n, Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::normal(), and Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::offset().
Hyperplane() [5/7]
template<typename Scalar_ , int AmbientDim_, int Options_> EIGEN_DEVICE_FUNC Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::Hyperplane (const VectorType & n, const Scalar & d) inline
Constructs a plane from its normal n and distance to the origin d such that the algebraic equation of the plane is \(n \cdot x + d = 0 \).
Warning
the vector normal is assumed to be normalized.
                                                                             : m_coeffs(n.size() + 1) {
     normal() = n;
     offset() = d;
   }
References n, Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::normal(), and Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::offset().
Hyperplane() [6/7]
template<typename Scalar_ , int AmbientDim_, int Options_> EIGEN_DEVICE_FUNC Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::Hyperplane (const ParametrizedLine< Scalar, AmbientDimAtCompileTime > & parametrized) inline explicit
Constructs a hyperplane passing through the parametrized line parametrized. If the dimension of the ambient space is greater than 2, then there isn't uniqueness, so an arbitrary choice is made.
{
     normal() = parametrized.direction().unitOrthogonal();
     offset() = -parametrized.origin().dot(normal());
   }
References Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::direction(), Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::normal(), Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::offset(), and Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::origin().
~Hyperplane()
template<typename Scalar_ , int AmbientDim_, int Options_> EIGEN_DEVICE_FUNC Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::~Hyperplane () inline
 {}
Hyperplane() [7/7]
template<typename Scalar_ , int AmbientDim_, int Options_> template<typename OtherScalarType , int OtherOptions> EIGEN_DEVICE_FUNC Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::Hyperplane (const Hyperplane< OtherScalarType, AmbientDimAtCompileTime, OtherOptions > & other) inline explicit
Copy constructor with scalar type conversion
{
     m_coeffs = other.coeffs().template cast<Scalar>();
   }
References Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::coeffs(), and Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::m_coeffs.
Member Function Documentation
absDistance()
template<typename Scalar_ , int AmbientDim_, int Options_> EIGEN_DEVICE_FUNC Scalar Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::absDistance (const VectorType & p) const inline
Returns
the absolute distance between the plane *this and a point p.
See also
signedDistance()
 { return numext::abs(signedDistance(p)); }
References Eigen::numext::abs(), p, and Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::signedDistance().
cast()
template<typename Scalar_ , int AmbientDim_, int Options_> template<typename NewScalarType > EIGEN_DEVICE_FUNC internal::cast_return_type<Hyperplane, Hyperplane<NewScalarType, AmbientDimAtCompileTime, Options> >::type Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::cast () const inline
Returns
*this with scalar type casted to NewScalarType
Note that if NewScalarType is equal to the current scalar type of *this then this function smartly returns a const reference to *this.
                    {
     return
         typename internal::cast_return_type<Hyperplane,
                                             Hyperplane<NewScalarType, AmbientDimAtCompileTime, Options> >::type(*this);
   }
References Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::Hyperplane(), and compute_granudrum_aor::type.
coeffs() [1/2]
template<typename Scalar_ , int AmbientDim_, int Options_> EIGEN_DEVICE_FUNC Coefficients& Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::coeffs () inline
Returns
a non-constant reference to the coefficients c_i of the plane equation: \(c_0*x_0 + ... + c_{d-1}*x_{d-1} + c_d = 0 \)
 { return m_coeffs; }
References Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::m_coeffs.
coeffs() [2/2]
template<typename Scalar_ , int AmbientDim_, int Options_> EIGEN_DEVICE_FUNC const Coefficients& Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::coeffs () const inline
Returns
a constant reference to the coefficients c_i of the plane equation: \(c_0*x_0 + ... + c_{d-1}*x_{d-1} + c_d = 0 \)
 { return m_coeffs; }
References Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::m_coeffs.
Referenced by Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::Hyperplane(), and Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::intersection().
dim()
template<typename Scalar_ , int AmbientDim_, int Options_> EIGEN_DEVICE_FUNC Index Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::dim () const inline
Returns
the dimension in which the plane holds
{
     return AmbientDimAtCompileTime == Dynamic ? m_coeffs.size() - 1 : Index(AmbientDimAtCompileTime);
   }
References Eigen::Dynamic, and Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::m_coeffs.
Referenced by Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::normal(), and Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::offset().
EIGEN_MAKE_ALIGNED_OPERATOR_NEW_IF_VECTORIZABLE_FIXED_SIZE()
template<typename Scalar_ , int AmbientDim_, int Options_> Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::EIGEN_MAKE_ALIGNED_OPERATOR_NEW_IF_VECTORIZABLE_FIXED_SIZE (Scalar_ , AmbientDim_ = = Dynamic ? Dynamic : AmbientDim_ + 1) inline
                                                                                               : AmbientDim_ + 1)
   enum { AmbientDimAtCompileTime = AmbientDim_, Options = Options_ };
intersection()
template<typename Scalar_ , int AmbientDim_, int Options_> EIGEN_DEVICE_FUNC VectorType Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::intersection (const Hyperplane< Scalar_, AmbientDim_, Options_ > & other) const inline
Returns
the intersection of *this with other.
Warning
The ambient space must be a plane, i.e. have dimension 2, so that *this and other are lines.
Note
If other is approximately parallel to *this, this method will return any point on *this.
{
     EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE(VectorType, 2)
     Scalar det = coeffs().coeff(0) * other.coeffs().coeff(1) - coeffs().coeff(1) * other.coeffs().coeff(0);
     // since the line equations ax+by=c are normalized with a^2+b^2=1, the following tests
     // whether the two lines are approximately parallel.
     if (internal::isMuchSmallerThan(det, Scalar(1))) {  // special case where the two lines are approximately parallel.
                                                         // Pick any point on the first line.
       if (numext::abs(coeffs().coeff(1)) > numext::abs(coeffs().coeff(0)))
         return VectorType(coeffs().coeff(1), -coeffs().coeff(2) / coeffs().coeff(1) - coeffs().coeff(0));
       else
         return VectorType(-coeffs().coeff(2) / coeffs().coeff(0) - coeffs().coeff(1), coeffs().coeff(0));
     } else {  // general case
       Scalar invdet = Scalar(1) / det;
       return VectorType(
           invdet * (coeffs().coeff(1) * other.coeffs().coeff(2) - other.coeffs().coeff(1) * coeffs().coeff(2)),
           invdet * (other.coeffs().coeff(0) * coeffs().coeff(2) - coeffs().coeff(0) * other.coeffs().coeff(2)));
     }
   }
References Eigen::numext::abs(), Eigen::PlainObjectBase< Derived >::coeff(), Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::coeffs(), EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE, and Eigen::internal::isMuchSmallerThan().
isApprox()
template<typename Scalar_ , int AmbientDim_, int Options_> template<int OtherOptions> EIGEN_DEVICE_FUNC bool Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::isApprox (const Hyperplane< Scalar, AmbientDimAtCompileTime, OtherOptions > & other, const typename NumTraits< Scalar >::Real & prec = NumTraits<Scalar>::dummy_precision()) const inline
Returns
true if *this is approximately equal to other, within the precision determined by prec.
See also
MatrixBase::isApprox()
{
     return m_coeffs.isApprox(other.m_coeffs, prec);
   }
References Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::m_coeffs.
normal() [1/2]
template<typename Scalar_ , int AmbientDim_, int Options_> EIGEN_DEVICE_FUNC NormalReturnType Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::normal () inline
Returns
a non-constant reference to the unit normal vector of the plane, which corresponds to the linear part of the implicit equation.
 { return NormalReturnType(m_coeffs, 0, 0, dim(), 1); }
References Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::dim(), and Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::m_coeffs.
normal() [2/2]
template<typename Scalar_ , int AmbientDim_, int Options_> EIGEN_DEVICE_FUNC ConstNormalReturnType Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::normal () const inline
Returns
a constant reference to the unit normal vector of the plane, which corresponds to the linear part of the implicit equation.
{
     return ConstNormalReturnType(m_coeffs, 0, 0, dim(), 1);
   }
References Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::dim(), and Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::m_coeffs.
Referenced by Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::Hyperplane(), Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::normalize(), Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::projection(), Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::signedDistance(), Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::Through(), and Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::transform().
normalize()
template<typename Scalar_ , int AmbientDim_, int Options_> EIGEN_DEVICE_FUNC void Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::normalize (void) inline
normalizes *this
 { m_coeffs /= normal().norm(); }
References Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::m_coeffs, and Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::normal().
offset() [1/2]
template<typename Scalar_ , int AmbientDim_, int Options_> EIGEN_DEVICE_FUNC Scalar& Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::offset () inline
Returns
a non-constant reference to the distance to the origin, which is also the constant part of the implicit equation
 { return m_coeffs(dim()); }
References Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::dim(), and Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::m_coeffs.
offset() [2/2]
template<typename Scalar_ , int AmbientDim_, int Options_> EIGEN_DEVICE_FUNC const Scalar& Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::offset () const inline
Returns
the distance to the origin, which is also the "constant term" of the implicit equation
Warning
the vector normal is assumed to be normalized.
 { return m_coeffs.coeff(dim()); }
References Eigen::PlainObjectBase< Derived >::coeff(), Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::dim(), and Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::m_coeffs.
Referenced by Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::Hyperplane(), Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::signedDistance(), Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::Through(), and Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::transform().
projection()
template<typename Scalar_ , int AmbientDim_, int Options_> EIGEN_DEVICE_FUNC VectorType Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::projection (const VectorType & p) const inline
Returns
the projection of a point p onto the plane *this.
 { return p - signedDistance(p) * normal(); }
References Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::normal(), p, and Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::signedDistance().
signedDistance()
template<typename Scalar_ , int AmbientDim_, int Options_> EIGEN_DEVICE_FUNC Scalar Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::signedDistance (const VectorType & p) const inline
Returns
the signed distance between the plane *this and a point p.
See also
absDistance()
 { return normal().dot(p) + offset(); }
References Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::normal(), Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::offset(), and p.
Referenced by Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::absDistance(), and Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::projection().
Through() [1/2]
template<typename Scalar_ , int AmbientDim_, int Options_> static EIGEN_DEVICE_FUNC Hyperplane Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::Through (const VectorType & p0, const VectorType & p1) inline static
Constructs a hyperplane passing through the two points. If the dimension of the ambient space is greater than 2, then there isn't uniqueness, so an arbitrary choice is made.
{
     Hyperplane result(p0.size());
     result.normal() = (p1 - p0).unitOrthogonal();
     result.offset() = -p0.dot(result.normal());
     return result;
   }
References Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::normal(), Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::offset(), p0, and p1.
Through() [2/2]
template<typename Scalar_ , int AmbientDim_, int Options_> static EIGEN_DEVICE_FUNC Hyperplane Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::Through (const VectorType & p0, const VectorType & p1, const VectorType & p2) inline static
Constructs a hyperplane passing through the three points. The dimension of the ambient space is required to be exactly 3.
{
     EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE(VectorType, 3)
     Hyperplane result(p0.size());
     VectorType v0(p2 - p0), v1(p1 - p0);
     result.normal() = v0.cross(v1);
     RealScalar norm = result.normal().norm();
     if (norm <= v0.norm() * v1.norm() * NumTraits<RealScalar>::epsilon()) {
       Matrix<Scalar, 2, 3> m;
       m << v0.transpose(), v1.transpose();
       JacobiSVD<Matrix<Scalar, 2, 3>, ComputeFullV> svd(m);
       result.normal() = svd.matrixV().col(2);
     } else
       result.normal() /= norm;
     result.offset() = -p0.dot(result.normal());
     return result;
   }
References Eigen::ComputeFullV, EIGEN_STATIC_ASSERT_VECTOR_SPECIFIC_SIZE, m, Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::normal(), Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::offset(), p0, p1, svd(), and v1().
transform() [1/2]
template<typename Scalar_ , int AmbientDim_, int Options_> template<typename XprType > EIGEN_DEVICE_FUNC Hyperplane& Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::transform (const MatrixBase< XprType > & mat, TransformTraits traits = Affine) inline
Applies the transformation matrix mat to *this and returns a reference to *this.
Parameters
mat the Dim x Dim transformation matrix
traits specifies whether the matrix mat represents an Isometry or a more generic Affine transformation. The default is Affine.
{
     if (traits == Affine) {
       normal() = mat.inverse().transpose() * normal();
       m_coeffs /= normal().norm();
     } else if (traits == Isometry)
       normal() = mat * normal();
     else {
       eigen_assert(0 && "invalid traits value in Hyperplane::transform()");
     }
     return *this;
   }
References Eigen::Affine, eigen_assert, Eigen::Isometry, Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::m_coeffs, Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::normal(), and Eigen::SparseMatrixBase< Derived >::transpose().
Referenced by Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::transform().
transform() [2/2]
template<typename Scalar_ , int AmbientDim_, int Options_> template<int TrOptions> EIGEN_DEVICE_FUNC Hyperplane& Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::transform (const Transform< Scalar, AmbientDimAtCompileTime, Affine, TrOptions > & t, TransformTraits traits = Affine) inline
Applies the transformation t to *this and returns a reference to *this.
Parameters
t the transformation of dimension Dim
traits specifies whether the transformation t represents an Isometry or a more generic Affine transformation. The default is Affine. Other kind of transformations are not supported.
{
     transform(t.linear(), traits);
     offset() -= normal().dot(t.translation());
     return *this;
   }
References Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::normal(), Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::offset(), plotPSD::t, and Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::transform().
Member Data Documentation
m_coeffs
template<typename Scalar_ , int AmbientDim_, int Options_> Coefficients Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::m_coeffs protected
Referenced by Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::coeffs(), Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::dim(), Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::Hyperplane(), Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::isApprox(), Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::normal(), Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::normalize(), Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::offset(), and Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::transform().
The documentation for this class was generated from the following files:
ForwardDeclarations.h
Hyperplane.h