MercuryDPM: InfiniteWall Class Reference
InfiniteWall Class Reference final
A infinite wall fills the half-space {point: (position_-point)*normal_<=0}.
#include <InfiniteWall.h>
Public Member Functions
InfiniteWall ()
Default constructor, the normal is infinitely long.
InfiniteWall (const InfiniteWall &w)
Copy constructor, copy the given wall.
InfiniteWall (const ParticleSpecies *species)
Constructor setting species.
InfiniteWall (Vec3D normal, Vec3D point, const ParticleSpecies *species)
Constructor setting values.
InfiniteWall (Vec3D PointA, Vec3D PointB, Vec3D PointC, const ParticleSpecies *species)
Constructor setting values if 3 coordinates are given.
~InfiniteWall () override
Default destructor.
InfiniteWall * copy () const override
Wall copy method. It calls the copy constructor of this Wall, useful for polymorphism.
void set (Vec3D normal, Vec3D point)
Defines a standard wall, given an outward normal vector s.t. normal*x=normal*point for all x of the wall.
void setNormal (Vec3D normal)
Changes the normal of the InfiniteWall.
MERCURYDPM_DEPRECATED void set (Vec3D normal, Mdouble position)
Defines a standard wall by computing normal*position = point and using the overloaded function set(Vec3D, vec3D).
Mdouble getDistance (Vec3D position) const
Returns the distance of the wall to the particle.
bool getDistanceAndNormal (const BaseParticle &p, Mdouble &distance, Vec3D &normal_return) const override
Compute the distance from the wall for a given BaseParticle and return if there is a collision. If there is a collision, also return the normal vector.
bool getDistanceNormalOverlapSuperquadric (const SuperQuadricParticle &p, Mdouble &distance, Vec3D &normal_return, Mdouble &overlap) const override
Compute the distance from the wall for a given BaseParticle and return if there is a collision. If there is a collision, also return the normal vector.
void read (std::istream &is) override
Reads InfiniteWall from a restart file.
void oldRead (std::istream &is)
Reads InfiniteWall from an old-style restart file.
std::string getName () const override
Writes the InfiniteWall to an output stream, usually a restart file.
Vec3D getNormal () const
Access function for normal.
void createVTK (std::vector< Vec3D > &myPoints) const
void createVTK (std::vector< Vec3D > &myPoints, Vec3D max, Vec3D min) const
void writeVTK (VTKContainer &vtk) const override
Vec3D getFurthestPointSuperQuadric (const Vec3D &normalBodyFixed, const Vec3D &axes, Mdouble eps1, Mdouble eps2) const override
Largely untested, use at your own risk for anything other than ellipsoids.
Public Member Functions inherited from BaseWall
BaseWall ()
Default constructor.
BaseWall (const BaseWall &w)
Copy constructor.
~BaseWall () override
Default destructor.
void write (std::ostream &os) const override
Function that writes a BaseWall to an output stream, usually a restart file.
virtual bool getDistanceNormalOverlap (const BaseParticle &P, Mdouble &distance, Vec3D &normal_return, Mdouble &overlap) const
virtual void setHandler (WallHandler *handler)
A function which sets the WallHandler for this BaseWall.
WallHandler * getHandler () const
A function which returns the WallHandler that handles this BaseWall.
void setIndSpecies (unsigned int indSpecies) override
Define the species of this wall using the index of the species in the SpeciesHandler in this DPMBase.
void setSpecies (const ParticleSpecies *species)
Defines the species of the current wall.
bool isFixed () const override
void setForceControl (Vec3D forceGoal, Vec3D gainFactor, Vec3D baseVelocity={0, 0, 0})
Slowly adjusts the force on a wall towards a specified goal, by adjusting (prescribing) the velocity of the wall.
virtual bool isLocal (Vec3D &min, Vec3D &max) const
bool getLinePlaneIntersect (Vec3D &intersect, const Vec3D &p0, const Vec3D &p1, const Vec3D &n, const Vec3D &p)
bool isInsideWallVTK (const Vec3D &point, const Vec3D &normal, const Vec3D &position) const
void projectOntoWallVTK (Vec3D &point0, const Vec3D &point1, const Vec3D &normal, const Vec3D &position) const
void intersectVTK (std::vector< Vec3D > &points, Vec3D normal, Vec3D position) const
virtual BaseInteraction * getInteractionWithSuperQuad (SuperQuadricParticle *p, unsigned timeStamp, InteractionHandler *interactionHandler)
void getVTK (std::vector< Vec3D > &points, std::vector< std::vector< double >> &triangleStrips)
const Vec3D getAxis () const
BaseInteraction * getInteractionWith (BaseParticle *p, unsigned timeStamp, InteractionHandler *interactionHandler) override
Returns the interaction between this wall and a given particle, nullptr if there is no interaction.
virtual void actionsOnRestart ()
No implementation but can be overidden in its derived classes.
virtual void actionsAfterParticleGhostUpdate ()
No implementation but can be overidden in its derived classes.
virtual void handleParticleAddition (unsigned int id, BaseParticle *p)
Handles the addition of particles to the particleHandler.
virtual void handleParticleRemoval (unsigned int id)
Handles the addition of particles to the particleHandler.
virtual void checkInteractions (InteractionHandler *interactionHandler, unsigned int timeStamp)
Check if all interactions are valid.
bool getVTKVisibility () const
void setVTKVisibility (bool vtkVisibility)
void addRenderedWall (BaseWall *w)
BaseWall * getRenderedWall (size_t i) const
std::vector< BaseWall * > getRenderedWalls () const
void removeRenderedWalls ()
void renderWall (VTKContainer &vtk)
void addParticlesAtWall (unsigned numElements=50)
void setVelocityControl (Vec3D forceGoal, Vec3D gainFactor, Vec3D baseVelocity)
virtual void writeWallDetailsVTK (VTKData &data) const
virtual void computeWear ()
Public Member Functions inherited from BaseInteractable
BaseInteractable ()
Default BaseInteractable constructor.
BaseInteractable (const BaseInteractable &p)
Copy constructor.
~BaseInteractable () override
Destructor, it simply destructs the BaseInteractable and all the objects it contains.
unsigned int getIndSpecies () const
Returns the index of the species associated with the interactable object.
const ParticleSpecies * getSpecies () const
Returns a pointer to the species of this BaseInteractable.
void setSpecies (const ParticleSpecies *species)
Sets the species of this BaseInteractable.
const Vec3D & getForce () const
Returns the force on this BaseInteractable.
const Vec3D & getTorque () const
Returns the torque on this BaseInteractable.
void setForce (const Vec3D &force)
Sets the force on this BaseInteractable.
void setTorque (const Vec3D &torque)
Sets the torque on this BaseInteractable.
void addForce (const Vec3D &addForce)
Adds an amount to the force on this BaseInteractable.
void addTorque (const Vec3D &addTorque)
Adds an amount to the torque on this BaseInteractable.
virtual void resetForceTorque (int numberOfOMPthreads)
void sumForceTorqueOMP ()
const Vec3D & getPosition () const
Returns the position of this BaseInteractable.
const Quaternion & getOrientation () const
Returns the orientation of this BaseInteractable.
virtual void setPosition (const Vec3D &position)
Sets the position of this BaseInteractable.
void setOrientationViaNormal (Vec3D normal)
Sets the orientation of this BaseInteractable by defining the vector that results from the rotation of the (1,0,0) vector.
void setOrientationViaEuler (Vec3D eulerAngle)
Sets the orientation of this BaseInteractable by defining the euler angles.
virtual void setOrientation (const Quaternion &orientation)
Sets the orientation of this BaseInteractable.
virtual void move (const Vec3D &move)
Moves this BaseInteractable by adding an amount to the position.
virtual void rotate (const Vec3D &angularVelocityDt)
Rotates this BaseInteractable.
const std::vector< BaseInteraction * > & getInteractions () const
Returns a list of interactions which belong to this interactable.
void addInteraction (BaseInteraction *I)
Adds an interaction to this BaseInteractable.
bool removeInteraction (BaseInteraction *I)
Removes an interaction from this BaseInteractable.
void copyInteractionsForPeriodicParticles (const BaseInteractable &p)
Copies interactions to this BaseInteractable whenever a periodic copy made.
void setVelocity (const Vec3D &velocity)
set the velocity of the BaseInteractable.
void setAngularVelocity (const Vec3D &angularVelocity)
set the angular velocity of the BaseInteractble.
void addVelocity (const Vec3D &velocity)
adds an increment to the velocity.
void addAngularVelocity (const Vec3D &angularVelocity)
add an increment to the angular velocity.
virtual const Vec3D & getVelocity () const
Returns the velocity of this interactable.
virtual const Vec3D & getAngularVelocity () const
Returns the angular velocity of this interactable.
void setPrescribedPosition (const std::function< Vec3D(double)> &prescribedPosition)
Allows the position of an infinite mass interactable to be prescribed.
void applyPrescribedPosition (double time)
Computes the position from the user defined prescribed position function.
void setPrescribedVelocity (const std::function< Vec3D(double)> &prescribedVelocity)
Allows the velocity of an infinite mass interactable to be prescribed.
void applyPrescribedVelocity (double time)
Computes the velocity from the user defined prescribed velocity function.
void setPrescribedOrientation (const std::function< Quaternion(double)> &prescribedOrientation)
Allows the orientation of the infinite mass interactbale to be prescribed.
void applyPrescribedOrientation (double time)
Computes the orientation from the user defined prescribed orientation function.
void setPrescribedAngularVelocity (const std::function< Vec3D(double)> &prescribedAngularVelocity)
Allows the angular velocity of the infinite mass interactable to be prescribed.
void applyPrescribedAngularVelocity (double time)
Computes the angular velocity from the user defined prescribed angular velocity.
virtual const Vec3D getVelocityAtContact (const Vec3D &contact) const
Returns the velocity at the contact point, use by many force laws.
void integrateBeforeForceComputation (double time, double timeStep)
This is part of integrate routine for objects with infinite mass.
void integrateAfterForceComputation (double time, double timeStep)
This is part of the integration routine for objects with infinite mass.
virtual Mdouble getInvMass () const
virtual Mdouble getCurvature (const Vec3D &labFixedCoordinates) const
virtual bool isFaceContact (const Vec3D &normal) const
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Additional Inherited Members
Static Public Member Functions inherited from BaseWall
static void addToVTK (const std::vector< Vec3D > &points, VTKContainer &vtk)
Takes the points provided and adds a triangle strip connecting these points to the vtk container.
Detailed Description
A infinite wall fills the half-space {point: (position_-point)*normal_<=0}.
This is a class defining walls. It defines the interaction of regular walls and periodic walls with particles as defined in Particle Modifications:
Thus, the surface of the wall is a plane through position position_ with normal_ the outward unit normal vector of the wall (pointing away from the particles, into the wall). Please note that this wall is infinite and straight.
A particle touches an infinite wall if (position_-point)*normal_<=radius.
Constructor & Destructor Documentation
InfiniteWall() [1/5]
InfiniteWall::InfiniteWall ()
Default constructor, the normal is infinitely long.
 {
     logger(DEBUG, "InfiniteWall::InfiniteWall ) finished");
 }
References DEBUG, and logger.
Referenced by copy().
InfiniteWall() [2/5]
InfiniteWall::InfiniteWall (const InfiniteWall & w)
Copy constructor, copy the given wall.
Parameters
[in] w InfiniteWall that has to be copied.
First copy the attributes of the BaseWall, then copy the ones that are specific for the InfiniteWall.
         : BaseWall(w)
 {
     logger(DEBUG, "InfiniteWall::InfiniteWall(const InfiniteWall &p) finished");
 }
References DEBUG, and logger.
InfiniteWall() [3/5]
InfiniteWall::InfiniteWall (const ParticleSpecies * species) explicit
Constructor setting species.
         : BaseWall()
 {
     setSpecies(s);
     logger(DEBUG, "InfiniteWall::InfiniteWall(const ParticleSpecies* s) finished");
 }
References DEBUG, logger, s, and BaseWall::setSpecies().
InfiniteWall() [4/5]
InfiniteWall::InfiniteWall (Vec3D normal, Vec3D point, const ParticleSpecies * species)
Constructor setting values.
 {
     setNormal(normal);
     setPosition(point);
     setSpecies(species);
 }
References WallFunction::normal(), setNormal(), BaseInteractable::setPosition(), and BaseWall::setSpecies().
InfiniteWall() [5/5]
InfiniteWall::InfiniteWall (Vec3D PointA, Vec3D PointB, Vec3D PointC, const ParticleSpecies * species)
Constructor setting values if 3 coordinates are given.
Parameters
PointA first coordinate
PointB second coordinate
PointC third coordinate
species
Builds an infinite wall through 3 points, normal is defined with Right hand rule following the three input points.
 {
 //function returns infinite wall passing through 3 points
 //subtract second and third from the first
     Vec3D SubtB = PointA - PointB;
     Vec3D SubtC = PointA - PointC;
     Vec3D WallNormal = Vec3D::cross(SubtB, SubtC);
     //Check if walls coordinates  inline, if true Do not build wall and give error message.
     if (WallNormal.getLengthSquared() == 0.0)
     {
         logger(ERROR,
                "Error Building InfiniteWall out of 3 coordinates. Coordinates are in line, Wall not constructed.");
     }
     else
     {
         setNormal(WallNormal);
         setPosition(PointA);
         setSpecies(species);
     }
 }
References Vec3D::cross(), ERROR, Vec3D::getLengthSquared(), logger, setNormal(), BaseInteractable::setPosition(), and BaseWall::setSpecies().
~InfiniteWall()
InfiniteWall::~InfiniteWall () override
Default destructor.
 {
     logger(DEBUG, "InfiniteWall::~InfiniteWall finished");
 }
References DEBUG, and logger.
Member Function Documentation
copy()
InfiniteWall * InfiniteWall::copy () const override virtual
Wall copy method. It calls the copy constructor of this Wall, useful for polymorphism.
Wall copy method. It calls the copy constructor of this Wall, useful for polymorphism
Implements BaseWall.
 {
     return new InfiniteWall(*this);
 }
References InfiniteWall().
Referenced by RestrictedWall::set().
createVTK() [1/2]
void InfiniteWall::createVTK (std::vector< Vec3D > & myPoints) const
Returns all intersection points of the infinite wall with the domain boundary.
Used to create an array of points for representing the wall in the VTK viewer. E.g., for a InfiniteWall through p=(0,0,0) with normal n=(0,0,-1) in a domain (-1,1)^3, createVTK returns {(0,-1,-1), (0,-1,1), (0,1,1), (0,1,-1)} Calling addToVTK will then create a triangle strip connecting these points with triangle faces.
 {
     Vec3D max = getHandler()->getDPMBase()->getMax();
     Vec3D min = getHandler()->getDPMBase()->getMin();
     createVTK(myPoints, min, max);
 }
References BaseHandler< T >::getDPMBase(), BaseWall::getHandler(), DPMBase::getMax(), DPMBase::getMin(), max, and min.
Referenced by LevelSetWall::createVTK(), and writeVTK().
createVTK() [2/2]
void InfiniteWall::createVTK (std::vector< Vec3D > & myPoints, Vec3D max, Vec3D min) const
Same as createVTK(), but with a self-defined domain size (useful for plotting AxisymmetricWall's).
 {
     const Vec3D& n = getOrientation().getAxis();
     const Vec3D& p = getPosition();
     if (fabs(n.X) > 0.5)
     {
         // If the wall normal has a nonzero x-component,
         // We first find four intersection points with the four domain edges pointing in x-direction.
         // Because these points might be outside the domain in x-direction, we use the intersection function have points in the domain
         myPoints.emplace_back(p.X - ((min.Y - p.Y) * n.Y + (min.Z - p.Z) * n.Z) / n.X, min.Y, min.Z);
         myPoints.emplace_back(p.X - ((min.Y - p.Y) * n.Y + (max.Z - p.Z) * n.Z) / n.X, min.Y, max.Z);
         myPoints.emplace_back(p.X - ((max.Y - p.Y) * n.Y + (max.Z - p.Z) * n.Z) / n.X, max.Y, max.Z);
         myPoints.emplace_back(p.X - ((max.Y - p.Y) * n.Y + (min.Z - p.Z) * n.Z) / n.X, max.Y, min.Z);
         intersectVTK(myPoints, Vec3D(+1, 0, 0), Vec3D(max.X, 0, 0));
         intersectVTK(myPoints, Vec3D(-1, 0, 0), Vec3D(min.X, 0, 0));
     }
     else if (fabs(n.Y) > 0.5)
     {
         // Else, if the wall normal has a nonzero y-component ...
         myPoints.emplace_back(min.X, p.Y - ((min.X - p.X) * n.X + (min.Z - p.Z) * n.Z) / n.Y, min.Z);
         myPoints.emplace_back(min.X, p.Y - ((min.X - p.X) * n.X + (max.Z - p.Z) * n.Z) / n.Y, max.Z);
         myPoints.emplace_back(max.X, p.Y - ((max.X - p.X) * n.X + (max.Z - p.Z) * n.Z) / n.Y, max.Z);
         myPoints.emplace_back(max.X, p.Y - ((max.X - p.X) * n.X + (min.Z - p.Z) * n.Z) / n.Y, min.Z);
         intersectVTK(myPoints, Vec3D(0, +1, 0), Vec3D(0, max.Y, 0));
         intersectVTK(myPoints, Vec3D(0, -1, 0), Vec3D(0, min.Y, 0));
     }
     else
     {
         // Else, the wall normal has to have a a nonzero z-component ...
         myPoints.emplace_back(min.X, min.Y, p.Z - ((min.Y - p.Y) * n.Y + (min.X - p.X) * n.X) / n.Z);
         myPoints.emplace_back(min.X, max.Y, p.Z - ((max.Y - p.Y) * n.Y + (min.X - p.X) * n.X) / n.Z);
         myPoints.emplace_back(max.X, max.Y, p.Z - ((max.Y - p.Y) * n.Y + (max.X - p.X) * n.X) / n.Z);
         myPoints.emplace_back(max.X, min.Y, p.Z - ((min.Y - p.Y) * n.Y + (max.X - p.X) * n.X) / n.Z);
         intersectVTK(myPoints, Vec3D(0, 0, +1), Vec3D(0, 0, max.Z));
         intersectVTK(myPoints, Vec3D(0, 0, -1), Vec3D(0, 0, min.Z));
     }
 }
References boost::multiprecision::fabs(), Quaternion::getAxis(), BaseInteractable::getOrientation(), BaseInteractable::getPosition(), BaseWall::intersectVTK(), max, min, n, and p.
getDistance()
Mdouble InfiniteWall::getDistance (Vec3D otherPosition) const
Returns the distance of the wall to the particle.
Parameters
[in] otherPosition The position to which the distance must be computed to.
Returns
The distance of the wall to the particle.
 {
     return getOrientation().getDistance(otherPosition, getPosition());
 }
References Quaternion::getDistance(), BaseInteractable::getOrientation(), and BaseInteractable::getPosition().
Referenced by getDistanceAndNormal(), RestrictedWall::getDistanceAndNormal(), getDistanceNormalOverlapSuperquadric(), RestrictedWall::getInteractionWith(), and RestrictedWall::writeVTK().
getDistanceAndNormal()
bool InfiniteWall::getDistanceAndNormal (const BaseParticle & p, Mdouble & distance, Vec3D & normal_return) const override virtual
Compute the distance from the wall for a given BaseParticle and return if there is a collision. If there is a collision, also return the normal vector.
Parameters
[in] p BaseParticle for which the distance to the wall must be computed.
[out] distance Distance between the particle and the wall.
[out] normal_return The normal of this wall, will only be set if there is a collision.
Returns
A boolean value for whether or not there is a collision.
First the distance is checked. If there is no collision, this function will return false and give the distance. If there is a collision, the function will return true and give the distance and the normal vector of this wall. Since this function should be called before calculating any Particle-Wall interactions, it can also be used to set the normal vector in case of curved walls.
Implements BaseWall.
 {
     distance = getDistance(p.getPosition());
     if (distance >= p.getWallInteractionRadius(this))
         return false;
     normal_return = getOrientation().getAxis();
     return true;
 }
References Quaternion::getAxis(), getDistance(), BaseInteractable::getOrientation(), and p.
Referenced by SimpleDrumSuperquadrics::getDistanceAndNormal().
getDistanceNormalOverlapSuperquadric()
bool InfiniteWall::getDistanceNormalOverlapSuperquadric (const SuperQuadricParticle & p, Mdouble & distance, Vec3D & normal_return, Mdouble & overlap) const override virtual
Compute the distance from the wall for a given BaseParticle and return if there is a collision. If there is a collision, also return the normal vector.
Reimplemented from BaseWall.
 {
     //first check: if the bounding sphere does not touch the wall, there is no contact.
     if (getDistance(p.getPosition()) >= p.getWallInteractionRadius(this))
     {
         return false;
     }
     Vec3D normalBodyFixed = getOrientation().getAxis();
     p.getOrientation().rotateBack(normalBodyFixed);
     Vec3D xWallBodyFixed = getPosition() - p.getPosition();
     p.getOrientation().rotateBack(xWallBodyFixed);
     Vec3D axes = p.getAxes();
     Mdouble eps1 = p.getExponentEps1();
     Mdouble eps2 = p.getExponentEps2();
     Vec3D furthestPoint = getFurthestPointSuperQuadric(normalBodyFixed, axes, eps1, eps2);
     overlap = Vec3D::dot(xWallBodyFixed - furthestPoint, -normalBodyFixed);
     if (overlap > 0)
     {
         Vec3D overlapBody = overlap * normalBodyFixed;
         Vec3D contactPoint = furthestPoint - overlapBody / 2;
         p.getOrientation().rotate(contactPoint);
         contactPoint += p.getPosition();
         distance = (contactPoint - overlapBody / 2 - p.getPosition()).getLength();
         normal_return = getOrientation().getAxis();
         return true;
     }
     return false;
 }
References Vec3D::dot(), Quaternion::getAxis(), getDistance(), getFurthestPointSuperQuadric(), BaseInteractable::getOrientation(), BaseInteractable::getPosition(), and p.
Referenced by SimpleDrumSuperquadrics::getDistanceNormalOverlapSuperquadric().
getFurthestPointSuperQuadric()
Vec3D InfiniteWall::getFurthestPointSuperQuadric (const Vec3D & normalBodyFixed, const Vec3D & axes, Mdouble eps1, Mdouble eps2) const override virtual
Largely untested, use at your own risk for anything other than ellipsoids.
Reimplemented from BaseWall.
 {
     Vec3D furthestPoint;
     if (std::abs(normalBodyFixed.X) > 1e-10)
     {
         Mdouble alpha = std::abs(normalBodyFixed.Y * axes.Y / normalBodyFixed.X / axes.X);
         Mdouble gamma = std::pow(1 + std::pow(alpha, 2 / eps2), eps2 / eps1 - 1);
         Mdouble beta = std::pow(gamma * std::abs(normalBodyFixed.Z * axes.Z / normalBodyFixed.X / axes.X),
                                 eps1 / (2 - eps1));
         furthestPoint.X = axes.X * mathsFunc::sign(normalBodyFixed.X) /
                           (std::pow(std::pow(1 + std::pow(alpha, 2 / eps2), eps2 / eps1) + std::pow(beta, 2 / eps1),
                                     eps1 / 2));
         furthestPoint.Y = axes.Y * alpha / axes.X * std::abs(furthestPoint.X) * mathsFunc::sign(normalBodyFixed.Y);
         furthestPoint.Z = axes.Z * beta / axes.X * std::abs(furthestPoint.X) * mathsFunc::sign(normalBodyFixed.Z);
     }
     else if (std::abs(normalBodyFixed.Y) > 1e-10)
     {
         Mdouble beta = std::pow(std::abs(normalBodyFixed.Z * axes.Z / normalBodyFixed.Y / axes.Y), eps1 / (2 - eps1));
         furthestPoint.Y = axes.Y / std::pow((1 + std::pow(beta, 2/eps1)), eps1 / 2) * mathsFunc::sign(normalBodyFixed.Y);
         furthestPoint.Z = axes.Z / axes.Y * std::abs(furthestPoint.Y) * beta * mathsFunc::sign(normalBodyFixed.Z);
     }
     else
     {
         furthestPoint.Z = axes.Z * mathsFunc::sign(normalBodyFixed.Z);
     }
     return furthestPoint;
 }
References abs(), alpha, beta, e(), mathsFunc::gamma(), Eigen::bfloat16_impl::pow(), mathsFunc::sign(), Vec3D::X, Vec3D::Y, and Vec3D::Z.
Referenced by getDistanceNormalOverlapSuperquadric(), and SimpleDrumSuperquadrics::getFurthestPointSuperQuadric().
getName()
std::string InfiniteWall::getName () const override virtual
Writes the InfiniteWall to an output stream, usually a restart file.
Returns the name of the object, in this case the string "InfiniteWall".
Returns
The string "InfiniteWall", which is the name of this class.
Implements BaseObject.
 {
     return "InfiniteWall";
 }
getNormal()
Vec3D InfiniteWall::getNormal () const
Access function for normal.
Returns
The 3D vector that represents the normal to the wall.
 {
     return getOrientation().getAxis();
 }
References Quaternion::getAxis(), and BaseInteractable::getOrientation().
Referenced by LawinenBox::actionsBeforeTimeStep(), CGHandler::computeContactPoints(), FlowFrontChute::stretch(), LawinenBox::writeEneTimeStep(), and RestrictedWall::writeVTK().
oldRead()
void InfiniteWall::oldRead (std::istream & is)
Reads InfiniteWall from an old-style restart file.
Parameters
[in] is The input stream from which the InfiniteWall old style is read.
 {
     std::string dummy;
     Vec3D velocity;
     Vec3D position;
     Vec3D normal;
     is >> dummy >> normal >> dummy >> position >> dummy >> velocity;
     setPosition(position);
     setVelocity(velocity);
     setOrientation(Quaternion(normal));
 }
References WallFunction::normal(), BaseInteractable::setOrientation(), BaseInteractable::setPosition(), BaseInteractable::setVelocity(), oomph::Global_string_for_annotation::string(), and Jeffery_Solution::velocity().
read()
void InfiniteWall::read (std::istream & is) override virtual
Reads InfiniteWall from a restart file.
Parameters
[in] is The input stream from which the InfiniteWall is read. Only needed for backward compatibility.
Reimplemented from BaseWall.
 {
     BaseWall::read(is);
     Vec3D normal;
     if (helpers::readOptionalVariable(is,"normal",normal)) setNormal(normal);
 }
References WallFunction::normal(), BaseWall::read(), helpers::readOptionalVariable(), and setNormal().
Referenced by SimpleDrumSuperquadrics::read(), and RestrictedWall::read().
set() [1/2]
void InfiniteWall::set (Vec3D normal, Mdouble positionInNormalDirection)
Defines a standard wall by computing normal*position = point and using the overloaded function set(Vec3D, vec3D).
Deprecated:
In Mercury 2, the user will have to use the new interface, namely set(Vec3D, Vec3D).
Defines a standard wall, given an normal vector pointing into the wall (i.e. out of the flow domain), to give a plane defined by normal*x=position
Parameters
[in] normal A Vec3D that represents the normal vector to the wall.
[in] positionInNormalDirection The position of the wall in the direction of the normal vector.
Deprecated:
InfiniteWall::set(Vec3D, Mdouble) is deprecated. Use set(Vec3D, Vec3D) instead.
 {
     logger(WARN, "InfiniteWall::set(Vec3D, Mdouble) is deprecated. Use set(Vec3D, Vec3D) instead.");
     set(normal, positionInNormalDirection * normal);
 }
References logger, WallFunction::normal(), set(), and WARN.
set() [2/2]
void InfiniteWall::set (Vec3D normal, Vec3D point)
Defines a standard wall, given an outward normal vector s.t. normal*x=normal*point for all x of the wall.
 {
     setNormal(normal);
     setPosition(point);
 }
References WallFunction::normal(), setNormal(), and BaseInteractable::setPosition().
Referenced by Chute::createBottom(), LevelSetWall::createVTK(), SimpleDrumSuperquadrics::getDistanceAndNormal(), SimpleDrumSuperquadrics::getDistanceNormalOverlapSuperquadric(), GranuDrum::GranuDrum(), InitialConditions< SpeciesType >::InitialConditions(), main(), MercuryCGSelfTest::MercuryCGSelfTest(), WallHandler::readAndCreateOldObject(), DPMBase::readParAndIniFiles(), set(), T_protectiveWall::setupInitialConditions(), LawinenBox::setupInitialConditions(), MercuryLogo::setupInitialConditions(), SmoothChute::setupInitialConditions(), ChangingTOIParticle::setupInitialConditions(), VerticalMixer::setupInitialConditions(), Binary::setupInitialConditions(), my_problem::setupInitialConditions(), FreeCooling2DinWallsDemo::setupInitialConditions(), FreeCooling3DinWallsDemo::setupInitialConditions(), HeaterBoundaryTest::setupInitialConditions(), HourGlass2D::setupInitialConditions(), HourGlass::setupInitialConditions(), Cstatic2d::setupInitialConditions(), AngleOfRepose::setupInitialConditions(), SilbertPeriodic::setupInitialConditions(), Drum::setupInitialConditions(), HertzSelfTest::setupInitialConditions(), MindlinSelfTest::setupInitialConditions(), Penetration::setupInitialConditions(), SegregationPeriodic::setupInitialConditions(), Chutebelt::setupInitialConditions(), ConstantMassFlowMaserBoundaryMixedSpeciesSelfTest::setupInitialConditions(), ConstantMassFlowMaserSelfTest::setupInitialConditions(), DistributionPhiNormalSelfTest::setupInitialConditions(), InsertionBoundarySelfTest::setupInitialConditions(), PolydisperseInsertionBoundarySelfTest::setupInitialConditions(), CGHandlerSelfTest::setupInitialConditions(), NewtonsCradleSelftest::setupInitialConditions(), SquarePacking::setupInitialConditions(), ChargedBondedParticleUnitTest::setupInitialConditions(), WallParticleCollision::setupInitialConditions(), my_problem_HGRID::setupInitialConditions(), FreeFallInteractionSelfTest::setupInitialConditions(), FreeFallSelfTest::setupInitialConditions(), LiquidMigrationSelfTest::setupInitialConditions(), ObliqueImpactSelfTest::setupInitialConditions(), TwoBondedParticleElasticCollision::setupInitialConditions(), TwoParticleBagheriCollision::setupInitialConditions(), TwoParticleClassicalWilletCollision::setupInitialConditions(), TwoParticleCollisionInteraction::setupInitialConditions(), TwoParticleElasticCollisionInteraction::setupInitialConditions(), TwoParticleElasticCollision::setupInitialConditions(), UnionOfWalls::setupInitialConditions(), DrumRot::setupInitialConditions(), RotatingDrum::setupInitialConditions(), BouncingSuperQuadric::setupInitialConditions(), EllipsoidsBouncingOnWallDemo::setupInitialConditions(), GranularCollapse::setupInitialConditions(), EllipticalSuperQuadricCollision::setupInitialConditions(), protectiveWall::setupInitialConditions(), Tutorial11::setupInitialConditions(), Tutorial12::setupInitialConditions(), Tutorial3::setupInitialConditions(), Tutorial4::setupInitialConditions(), Tutorial7::setupInitialConditions(), Tutorial8::setupInitialConditions(), Tutorial9::setupInitialConditions(), EvaporationAndHeatTest::setupInitialConditions(), ExtremeOverlapWithWallsUnitTest::setupInitialConditions(), FreeFallHertzMindlinUnitTest::setupInitialConditions(), FreeFall::setupInitialConditions(), FullRestartTest::setupInitialConditions(), InclinedPlane::setupInitialConditions(), MpiMaserChuteTest::setupInitialConditions(), MultiParticlesInsertion::setupInitialConditions(), MpiPeriodicBoundaryUnitTest::setupInitialConditions(), SetDistributionPhiNormalSelfTest::setupInitialConditions(), WallSpecies::setupInitialConditions(), AreaVTK::setupInitialConditions(), ChuteBottom::setupInitialConditions(), ContactDetectionWithWallTester::setupParticleAndWall(), Chute::setupSideWalls(), SimpleDrumSuperquadrics::SimpleDrumSuperquadrics(), and Slide::Slide().
setNormal()
void InfiniteWall::setNormal (Vec3D normal)
Changes the normal of the InfiniteWall.
Parameters
[in] normal The vector normal to the wall.
 {
     setOrientationViaNormal(normal);
 }
References WallFunction::normal(), and BaseInteractable::setOrientationViaNormal().
Referenced by InfiniteWall(), read(), set(), and MovingWall::setupInitialConditions().
writeVTK()
void InfiniteWall::writeVTK (VTKContainer & vtk) const override virtual
Adds the vtk wall representation to the VTK container
Reimplemented from BaseWall.
 {
     std::vector<Vec3D> points;
     createVTK(points);
     addToVTK(points, vtk);
 }
References BaseWall::addToVTK(), and createVTK().
The documentation for this class was generated from the following files:
InfiniteWall.h
InfiniteWall.cc