MercuryDPM: File.cc File Reference
File.cc File Reference
#include "File.h"
#include <string>
#include <sstream>
#include <iostream>
#include <cmath>
#include <iomanip>
#include "Logger.h"
Functions
std::string to_string_padded (unsigned int value)
Pads the number This function tries to pad the number to 4 digits, which is used when you create multiple files with padded numbers. Any numbers larger than 4 digits return unmodified.
std::ostream & operator<< (std::ostream &os, FileType fileType)
Writes the FileType as a human-readable string into the output stream 'os'.
std::istream & operator>> (std::istream &is, FileType &fileType)
Reads the FileType from an input stream 'is'.
std::ostream & operator<< (std::ostream &os, const File &o)
std::istream & operator>> (std::istream &is, File &o)
Function Documentation
operator<<() [1/2]
std::ostream& operator<< (std::ostream & os, const File & o)
Parameters
[in,out] os
[in] o
Returns
std::ostream& os
 {
     o.write(os);
     return os;
 }
operator<<() [2/2]
std::ostream& operator<< (std::ostream & os, FileType fileType)
Writes the FileType as a human-readable string into the output stream 'os'.
Parameters
[in,out] os output stream to which the fileType is written
[in] fileType the fileType that has to be written to the output stream
Returns
the output stream "os" that is returned after adding the fileType string
 {
     if (fileType == FileType::NO_FILE)
         os << "NO_FILE";
     else if (fileType == FileType::ONE_FILE)
         os << "ONE_FILE";
     else if (fileType == FileType::MULTIPLE_FILES)
         os << "MULTIPLE_FILES";
     else if (fileType == FileType::MULTIPLE_FILES_PADDED)
         os << "MULTIPLE_FILES_PADDED";
     else
     {
         logger(ERROR, "FileType not recognized");
     }
     return os;
 }
References ERROR, logger, MULTIPLE_FILES, MULTIPLE_FILES_PADDED, NO_FILE, and ONE_FILE.
operator>>() [1/2]
std::istream& operator>> (std::istream & is, File & o)
Parameters
[in,out] is
[in] o
Returns
std::istream&
 {
     o.read(is);
     return (is);
 }
operator>>() [2/2]
std::istream& operator>> (std::istream & is, FileType & fileType)
Reads the FileType from an input stream 'is'.
Parameters
[in,out] is The input stream from which the fileType is read
[in] fileType The fileType that has to be read from the input stream
Returns
the input stream "is" (that is returned after the fileType string is read out)
 {
     std::string fileTypeString;
     is >> fileTypeString;
     if (!fileTypeString.compare("NO_FILE"))
         fileType = FileType::NO_FILE;
     else if (!fileTypeString.compare("ONE_FILE"))
         fileType = FileType::ONE_FILE;
     else if (!fileTypeString.compare("MULTIPLE_FILES"))
         fileType = FileType::MULTIPLE_FILES;
     else if (!fileTypeString.compare("MULTIPLE_FILES_PADDED"))
         fileType = FileType::MULTIPLE_FILES_PADDED;
     else
     {
         logger(ERROR, "operator>>: FileType % not recognized", fileTypeString);
     }
     return is;
 }
References ERROR, logger, MULTIPLE_FILES, MULTIPLE_FILES_PADDED, NO_FILE, ONE_FILE, and oomph::Global_string_for_annotation::string().
to_string_padded()
std::string to_string_padded (unsigned int value)
Pads the number This function tries to pad the number to 4 digits, which is used when you create multiple files with padded numbers. Any numbers larger than 4 digits return unmodified.
Parameters
value The value to modify
Returns
A padded string
 {
     std::ostringstream out;
     out << std::setw(4) << std::setfill('0') << value;
     return out.str();
 }
References out(), and Eigen::value.
Referenced by File::getFullName(), and DPMBase::removeOldFiles().