MercuryDPM: Trackball Class Reference
Trackball Class Reference
#include <trackball.h>
Public Types
enum Mode { Around , Local }
Public Member Functions
Trackball ()
void start (Mode m=Around)
void setCamera (Camera *pCam)
void track (const Eigen::Vector2i &newPoint2D)
Protected Member Functions
bool mapToSphere (const Eigen::Vector2i &p2, Eigen::Vector3f &v3)
Protected Attributes
Camera * mpCamera
Eigen::Vector3f mLastPoint3D
Mode mMode
bool mLastPointOk
Member Enumeration Documentation
Mode
enum Trackball::Mode
Enumerator
Around
Local
 { Around, Local };
Constructor & Destructor Documentation
Trackball()
Trackball::Trackball () inline
 : mpCamera(0) {}
Member Function Documentation
mapToSphere()
bool Trackball::mapToSphere (const Eigen::Vector2i & p2, Eigen::Vector3f & v3) protected
{
   if ((p2.x() >= 0) && (p2.x() <= int(mpCamera->vpWidth())) && (p2.y() >= 0) && (p2.y() <= int(mpCamera->vpHeight()))) {
     double x = (double)(p2.x() - 0.5 * mpCamera->vpWidth()) / (double)mpCamera->vpWidth();
     double y = (double)(0.5 * mpCamera->vpHeight() - p2.y()) / (double)mpCamera->vpHeight();
     double sinx = sin(M_PI * x * 0.5);
     double siny = sin(M_PI * y * 0.5);
     double sinx2siny2 = sinx * sinx + siny * siny;
     v3.x() = sinx;
     v3.y() = siny;
     v3.z() = sinx2siny2 < 1.0 ? sqrt(1.0 - sinx2siny2) : 0.0;
     return true;
   } else
     return false;
 }
References M_PI, sin(), sqrt(), plotDoE::x, and y.
setCamera()
void Trackball::setCamera (Camera * pCam) inline
 { mpCamera = pCam; }
References mpCamera.
start()
void Trackball::start (Mode m = Around) inline
{
     mMode = m;
     mLastPointOk = false;
   }
References m, mLastPointOk, and mMode.
track()
void Trackball::track (const Eigen::Vector2i & newPoint2D)
{
   if (mpCamera == 0) return;
   Vector3f newPoint3D;
   bool newPointOk = mapToSphere(point2D, newPoint3D);
   if (mLastPointOk && newPointOk) {
     Vector3f axis = mLastPoint3D.cross(newPoint3D).normalized();
     float cos_angle = mLastPoint3D.dot(newPoint3D);
     if (std::abs(cos_angle) < 1.0) {
       float angle = 2. * acos(cos_angle);
       if (mMode == Around)
         mpCamera->rotateAroundTarget(Quaternionf(AngleAxisf(angle, axis)));
       else
         mpCamera->localRotate(Quaternionf(AngleAxisf(-angle, axis)));
     }
   }
   mLastPoint3D = newPoint3D;
   mLastPointOk = newPointOk;
 }
References abs(), acos(), and Jeffery_Solution::angle().
Member Data Documentation
mLastPoint3D
Eigen::Vector3f Trackball::mLastPoint3D protected
mLastPointOk
bool Trackball::mLastPointOk protected
Referenced by start().
mMode
Mode Trackball::mMode protected
Referenced by start().
mpCamera
Camera* Trackball::mpCamera protected
Referenced by setCamera().
The documentation for this class was generated from the following files:
trackball.h
trackball.cpp