MercuryDPM: Particles.h File Reference
Particles.h File Reference
#include <cereal/cereal.hpp>
#include <ParticleHandler.h>
#include <Particles/BaseParticle.h>
Functions
template<class Archive >
void load (Archive &ar, ParticleHandler &handl)
template<class Archive >
void save (Archive &ar, const ParticleHandler &handl)
template<class Archive >
void load (Archive &ar, BaseParticle &p)
template<class Archive >
void save (Archive &ar, const BaseParticle &p)
Function Documentation
load() [1/2]
template<class Archive > void load (Archive & ar, BaseParticle & p)
{
     Vec3D position;
     Vec3D velocity;
     Mdouble radius;
     ar( CEREAL_NVP(position),
         CEREAL_NVP(velocity),
         CEREAL_NVP(radius));
     p.setPosition(position);
     p.setRadius(radius);
     p.setVelocity(velocity);
 }
References p, UniformPSDSelfTest::radius, and Jeffery_Solution::velocity().
load() [2/2]
template<class Archive > void load (Archive & ar, ParticleHandler & handl)
{
     cereal::size_type size;
     ar ( cereal::make_size_tag(size) );
     SphericalParticle p;
     for (int i = 0; i < size; i++) {
         ar(p);
         logger(INFO, "Particle: \n\tPOS: % \n\tVEL: % \n\tRAD: %", p.getPosition(), p.getVelocity(), p.getRadius());
         handl.copyAndAddObject(p);
     }
 }
References BaseHandler< T >::copyAndAddObject(), i, INFO, logger, p, and size.
Referenced by RefineableFishPoissonProblem< ELEMENT >::doc_solution(), GeomObjectAsGeneralisedElementProblem::doc_solution(), ElasticFishBackElement::fill_in_generic_residual_contribution(), oomph::FSIWallElement::fluid_load_vector(), oomph::FSIAxisymmetricQTaylorHoodElement::get_load(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::get_load(), oomph::NavierStokesEquations< DIM >::get_load(), oomph::SpaceTimeNavierStokesEquations< DIM >::get_load(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::get_load(), oomph::SphericalNavierStokesEquations::get_load(), oomph::PolarNavierStokesEquations::get_load(), oomph::KirchhoffLoveShellEquations::load_rate_of_work(), oomph::KirchhoffLoveBeamEquations::load_vector(), oomph::FSIHermiteBeamElement::load_vector(), oomph::KirchhoffLoveShellEquations::load_vector(), oomph::FSIDiagHermiteShellElement::load_vector(), oomph::KirchhoffLoveShellEquations::load_vector_for_rate_of_work_computation(), oomph::FSIDiagHermiteShellElement::load_vector_for_rate_of_work_computation(), Eigen::ThreadLocal< T, Initialize, Release >::local(), main(), Global_Physical_Variables::pcos_load(), Eigen::internal::pload_partial_common(), Eigen::internal::ploadu_partial_common(), Global_Physical_Variables::press_load(), Global_Parameters::press_load(), Global_Physical_Variables::spring_load(), Global_Physical_Variables::spring_load_lower(), oomph::AxisymmetricPoroelasticityTractionElementHelper::Zero_pressure_fct(), oomph::DarcyFaceElementHelper::Zero_pressure_fct(), oomph::PoroelasticityFaceElementHelper::Zero_pressure_fct(), oomph::AxisymmetricLinearElasticityTractionElementHelper::Zero_traction_fct(), oomph::AxisymmetricNavierStokesTractionElementHelper::Zero_traction_fct(), oomph::AxisymmetricPoroelasticityTractionElementHelper::Zero_traction_fct(), oomph::LinearElasticityTractionElementHelper::Zero_traction_fct(), oomph::PoroelasticityFaceElementHelper::Zero_traction_fct(), oomph::PMLTimeHarmonicLinearElasticityTractionElementHelper::Zero_traction_fct(), oomph::TimeHarmonicFourierDecomposedLinearElasticityTractionElementHelper::Zero_traction_fct(), oomph::TimeHarmonicLinearElasticityTractionElementHelper::Zero_traction_fct(), oomph::KirchhoffLoveBeamEquations::Zero_traction_fct(), oomph::KirchhoffLoveShellEquations::Zero_traction_fct(), and oomph::SolidTractionElementHelper::Zero_traction_fct().
save() [1/2]
template<class Archive > void save (Archive & ar, const BaseParticle & p)
{
     ar( cereal::make_nvp("position", p.getPosition()),
         cereal::make_nvp("velocity", p.getVelocity()),
         cereal::make_nvp("radius", p.getRadius()));
 }
References p.
save() [2/2]
template<class Archive > void save (Archive & ar, const ParticleHandler & handl)
{
     ar ( cereal::make_size_tag( handl.getNumberOfObjects() ));
     for (const auto& p : handl) {
         ar ( p );
     }
 }
References ParticleHandler::getNumberOfObjects(), and p.