MercuryDPM: Eigen::internal::accurate_log2< double > Struct Reference
Eigen::internal::accurate_log2< double > Struct Reference
#include <GenericPacketMathFunctions.h>
Public Member Functions
template<typename Packet >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void operator() (const Packet &x, Packet &log2_x_hi, Packet &log2_x_lo)
Member Function Documentation
operator()()
template<typename Packet > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::accurate_log2< double >::operator() (const Packet & x, Packet & log2_x_hi, Packet & log2_x_lo) inline
{
     // We use a transformation of variables:
     //    r = c * (x-1) / (x+1),
     // such that
     //    log2(x) = log2((1 + r/c) / (1 - r/c)) = f(r).
     // The function f(r) can be approximated well using an odd polynomial
     // of the form
     //   P(r) = ((Q(r^2) * r^2 + C) * r^2 + 1) * r,
     // For the implementation of log2<double> here, Q is of degree 6 with
     // coefficient represented in working precision (double), while C is a
     // constant represented in extra precision as a double word to achieve
     // full accuracy.
     //
     // The polynomial coefficients were computed by the Sollya script:
     //
     // c = 2 / log(2);
     // trans = c * (x-1)/(x+1);
     // itrans = (1+x/c)/(1-x/c);
     // interval=[trans(sqrt(0.5)); trans(sqrt(2))];
     // print(interval);
     // f = log2(itrans(x));
     // p=fpminimax(f,[|1,3,5,7,9,11,13,15,17|],[|1,DD,double...|],interval,relative,floating);
     const Packet q12 = pset1<Packet>(2.87074255468000586e-9);
     const Packet q10 = pset1<Packet>(2.38957980901884082e-8);
     const Packet q8 = pset1<Packet>(2.31032094540014656e-7);
     const Packet q6 = pset1<Packet>(2.27279857398537278e-6);
     const Packet q4 = pset1<Packet>(2.31271023278625638e-5);
     const Packet q2 = pset1<Packet>(2.47556738444535513e-4);
     const Packet q0 = pset1<Packet>(2.88543873228900172e-3);
     const Packet C_hi = pset1<Packet>(0.0400377511598501157);
     const Packet C_lo = pset1<Packet>(-4.77726582251425391e-19);
     const Packet one = pset1<Packet>(1.0);
     const Packet cst_2_log2e_hi = pset1<Packet>(2.88539008177792677);
     const Packet cst_2_log2e_lo = pset1<Packet>(4.07660016854549667e-17);
     // c * (x - 1)
     Packet t_hi, t_lo;
     // t = c * (x-1)
     twoprod(cst_2_log2e_hi, cst_2_log2e_lo, psub(x, one), t_hi, t_lo);
     // r = c * (x-1) / (x+1),
     Packet r_hi, r_lo;
     doubleword_div_fp(t_hi, t_lo, padd(x, one), r_hi, r_lo);
     // r2 = r * r
     Packet r2_hi, r2_lo;
     twoprod(r_hi, r_lo, r_hi, r_lo, r2_hi, r2_lo);
     // r4 = r2 * r2
     Packet r4_hi, r4_lo;
     twoprod(r2_hi, r2_lo, r2_hi, r2_lo, r4_hi, r4_lo);
     // Evaluate Q(r^2) in working precision. We evaluate it in two parts
     // (even and odd in r^2) to improve instruction level parallelism.
     Packet q_even = pmadd(q12, r4_hi, q8);
     Packet q_odd = pmadd(q10, r4_hi, q6);
     q_even = pmadd(q_even, r4_hi, q4);
     q_odd = pmadd(q_odd, r4_hi, q2);
     q_even = pmadd(q_even, r4_hi, q0);
     Packet q = pmadd(q_odd, r2_hi, q_even);
     // Now evaluate the low order terms of P(x) in double word precision.
     // In the following, due to the increasing magnitude of the coefficients
     // and r being constrained to [-0.5, 0.5] we can use fast_twosum instead
     // of the slower twosum.
     // Q(r^2) * r^2
     Packet p_hi, p_lo;
     twoprod(r2_hi, r2_lo, q, p_hi, p_lo);
     // Q(r^2) * r^2 + C
     Packet p1_hi, p1_lo;
     fast_twosum(C_hi, C_lo, p_hi, p_lo, p1_hi, p1_lo);
     // (Q(r^2) * r^2 + C) * r^2
     Packet p2_hi, p2_lo;
     twoprod(r2_hi, r2_lo, p1_hi, p1_lo, p2_hi, p2_lo);
     // ((Q(r^2) * r^2 + C) * r^2 + 1)
     Packet p3_hi, p3_lo;
     fast_twosum(one, p2_hi, p2_lo, p3_hi, p3_lo);
     // log(z) ~= ((Q(r^2) * r^2 + C) * r^2 + 1) * r
     twoprod(p3_hi, p3_lo, r_hi, r_lo, log2_x_hi, log2_x_lo);
   }
References Eigen::internal::doubleword_div_fp(), Eigen::internal::fast_twosum(), Eigen::internal::padd(), Eigen::internal::pmadd(), Eigen::internal::psub(), Eigen::numext::q, Eigen::internal::twoprod(), and plotDoE::x.
The documentation for this struct was generated from the following file:
GenericPacketMathFunctions.h