MercuryDPM: oscillating_sphere.cc File Reference
oscillating_sphere.cc File Reference
#include <complex>
#include <cmath>
#include "generic.h"
#include "pml_fourier_decomposed_helmholtz.h"
#include "meshes/triangle_mesh.h"
#include "oomph_crbond_bessel.h"
Classes
class oomph::PMLHelmholtzPointSourceElement< ELEMENT >
Class to impose point source to (wrapped) Helmholtz element.
class oomph::FaceGeometry< PMLHelmholtzPointSourceElement< ELEMENT > >
class oomph::FaceGeometry< FaceGeometry< PMLHelmholtzPointSourceElement< ELEMENT > > >
class oomph::PMLLayerElement< PMLHelmholtzPointSourceElement< ELEMENT > >
class oomph::PMLLayerElement< ProjectablePMLFourierDecomposedHelmholtzElement< PMLHelmholtzPointSourceElement< ELEMENT > > >
class PMLFourierDecomposedHelmholtzProblem< ELEMENT >
Problem class.
Namespaces
ProblemParameters
Namespace for exact solution and problem parameters.
oomph
DRAIG: Change all instances of (SPATIAL_DIM) to (DIM-1).
Functions
std::complex< double > ProblemParameters::I (0.0, 1.0)
Imaginary unit.
void ProblemParameters::get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector of size 2, containing real and imag parts.
void ProblemParameters::exact_minus_dudr (const Vector< double > &x, std::complex< double > &flux)
std::complex< double > ProblemParameters::Magnitude (100.0, 100.0)
Point source magnitude (Complex)
int main (int argc, char **argv)
Driver code for Pml Fourier decomposed Helmholtz problem.
Variables
string ProblemParameters::Directory ="RESLT"
Output directory.
double ProblemParameters::PML_thickness =4.0
Default physical PML thickness.
unsigned ProblemParameters::Nel_pml =15
Default number of elements within PMLs.
double ProblemParameters::R_source = 2.0
Radial position of point source.
double ProblemParameters::Z_source = 2.0
Axial position of point source.
Vector< double > ProblemParameters::Coeff (N_terms, 1.0)
Coefficients in the exact solution.
Function Documentation
main()
int main (int argc , char ** argv)
Driver code for Pml Fourier decomposed Helmholtz problem.
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Define possible command line arguments and parse the ones that
  // were actually specified
  // Fourier wavenumber
  CommandLineArgs::specify_command_line_flag("--Fourier_wavenumber",
                                             &ProblemParameters::N_fourier);
  // Output directory
  CommandLineArgs::specify_command_line_flag("--dir",
                                             &ProblemParameters::Directory);
  // PML thickness
  CommandLineArgs::specify_command_line_flag("--pml_thick",
                                             &ProblemParameters::PML_thickness);
  // Number of elements within PMLs
  CommandLineArgs::specify_command_line_flag("--npml_element",
                                             &ProblemParameters::Nel_pml);
  // Target Element size on first mesh generation
  CommandLineArgs::specify_command_line_flag("--element_area",
                                             &ProblemParameters::Element_area);
  // k squared (wavenumber squared)
  CommandLineArgs::specify_command_line_flag("--k_squared",
                                             &ProblemParameters::K_squared);
  // Validation run?
  CommandLineArgs::specify_command_line_flag("--validate");
   // Demonstrate across a range of omega (or k) values with good mesh for a
   // visual test of accuracy (put in by Jonathan Deakin)
   CommandLineArgs::specify_command_line_flag("--demonstrate");
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  // Create label for output
  DocInfo doc_info;
  // Set output directory
  doc_info.set_directory(ProblemParameters::Directory);
 #ifdef ADAPTIVE
  // Create the problem with 2D projectable six-node elements from the
  // TPMLFourierDecomposedHelmholtzElement family,
  // allowing for the imposition of a point source (via another
  // templated wrapper)
  PMLFourierDecomposedHelmholtzProblem<
  ProjectablePMLFourierDecomposedHelmholtzElement<
  PMLHelmholtzPointSourceElement<
  TPMLFourierDecomposedHelmholtzElement<3> > > > problem;
 #else
  // Create the problem with 2D six-node elements from the
  // TPMLFourierDecomposedHelmholtzElement family.
  PMLFourierDecomposedHelmholtzProblem
   <TPMLFourierDecomposedHelmholtzElement<3> >
   problem;
 #endif
  // Step number
  doc_info.number()=ProblemParameters::N_fourier;
 #ifdef ADAPTIVE
  // Max. number of adaptations
  unsigned max_adapt=4;
  // Validation run?
  if (CommandLineArgs::command_line_flag_has_been_set("--validate"))
   {
    max_adapt=1;
   }
  // Solve the problem, allowing
  // up to max_adapt mesh adaptations after every solve.
  problem.newton_solve(max_adapt);
 #else
 // Solve the problem with Newton's method
 problem.newton_solve();
 #endif
  //Output the solution
  problem.doc_solution(doc_info);
 } //end of main
References oomph::CommandLineArgs::command_line_flag_has_been_set(), ProblemParameters::Directory, oomph::CommandLineArgs::doc_specified_flags(), ProblemParameters::Element_area, ProblemParameters::K_squared, ProblemParameters::N_fourier, ProblemParameters::Nel_pml, oomph::DocInfo::number(), oomph::CommandLineArgs::parse_and_assign(), ProblemParameters::PML_thickness, problem, oomph::DocInfo::set_directory(), oomph::CommandLineArgs::setup(), and oomph::CommandLineArgs::specify_command_line_flag().