MercuryDPM: bicgstab.cpp File Reference
bicgstab.cpp File Reference
#include "sparse_solver.h"
#include <Eigen/IterativeLinearSolvers>
Functions
template<typename T , typename I_ >
void test_bicgstab_T ()
EIGEN_DECLARE_TEST (bicgstab)
Function Documentation
EIGEN_DECLARE_TEST()
EIGEN_DECLARE_TEST (bicgstab)
{
   CALL_SUBTEST_1((test_bicgstab_T<double, int>()));
   CALL_SUBTEST_2((test_bicgstab_T<std::complex<double>, int>()));
   CALL_SUBTEST_3((test_bicgstab_T<double, long int>()));
 }
References CALL_SUBTEST_1, CALL_SUBTEST_2, CALL_SUBTEST_3, and test_bicgstab_T().
test_bicgstab_T()
template<typename T , typename I_ > void test_bicgstab_T ()
{
   BiCGSTAB<SparseMatrix<T, 0, I_>, DiagonalPreconditioner<T> > bicgstab_colmajor_diag;
   BiCGSTAB<SparseMatrix<T, 0, I_>, IdentityPreconditioner> bicgstab_colmajor_I;
   BiCGSTAB<SparseMatrix<T, 0, I_>, IncompleteLUT<T, I_> > bicgstab_colmajor_ilut;
   // BiCGSTAB<SparseMatrix<T>, SSORPreconditioner<T> >     bicgstab_colmajor_ssor;
   bicgstab_colmajor_diag.setTolerance(NumTraits<T>::epsilon() * 4);
   bicgstab_colmajor_ilut.setTolerance(NumTraits<T>::epsilon() * 4);
   CALL_SUBTEST(check_sparse_square_solving(bicgstab_colmajor_diag));
   //   CALL_SUBTEST( check_sparse_square_solving(bicgstab_colmajor_I)     );
   CALL_SUBTEST(check_sparse_square_solving(bicgstab_colmajor_ilut));
   // CALL_SUBTEST( check_sparse_square_solving(bicgstab_colmajor_ssor)     );
 }
References CALL_SUBTEST, check_sparse_square_solving(), and Eigen::IterativeSolverBase< Derived >::setTolerance().
Referenced by EIGEN_DECLARE_TEST().