MercuryDPM: LiquidMigrationLSSpecies Class Reference
LiquidMigrationLSSpecies Class Reference
LiquidMigrationLSSpecies contains the parameters used to describe a short-range force caused by liquid bridges.
#include <LiquidMigrationLSSpecies.h>
Public Types
typedef LiquidMigrationLSInteraction InteractionType
The correct Interaction type for this AdhesiveForceSpecies.
Public Member Functions
LiquidMigrationLSSpecies ()
The default constructor.
LiquidMigrationLSSpecies (const LiquidMigrationLSSpecies &s)
The default copy constructor.
~LiquidMigrationLSSpecies ()
The default destructor.
void read (std::istream &is)
Reads the species properties from an input stream.
void write (std::ostream &os) const
Writes the species properties to an output stream.
std::string getBaseName () const
Used in Species::getName to obtain a unique name for each Species.
void mix (LiquidMigrationLSSpecies *S, LiquidMigrationLSSpecies *T)
creates default values for mixed species
void setInteractionDistance ()
returns the largest separation distance at which adhesive short-range forces can occur.
void setLiquidBridgeVolumeMax (Mdouble liquidBridgeVolume)
Returns a pointer to the adhesive force interaction LiquidMigrationLSInteraction.
Mdouble getLiquidBridgeVolumeMax () const
used to access the Volume of the liquid bridge.
void setLiquidBridgeVolumeMin (Mdouble)
used to set the Volume of the liquid bridge.
Mdouble getLiquidBridgeVolumeMin () const
used to access the Volume of the liquid bridge.
void setDistributionCoefficient (Mdouble distributionCoefficient)
used to set the distribution coefficient of the liquid.
Mdouble getDistributionCoefficient () const
used to access the surface tension of the liquid.
void setSurfaceTension (Mdouble surfaceTension)
used to set the surface tension of the liquid.
Mdouble getSurfaceTension () const
used to access the surface tension of the liquid.
void setContactAngle (Mdouble contactAngle)
used to set the contact angle between particle and liquid bridge surface (in radians)
Mdouble getContactAngle () const
used to access the contact angle between particle and liquid bridge surface.
void setViscosity (Mdouble viscosity)
used to set the Viscosity of the liquid.
Mdouble getViscosity () const
used to access the Viscosity of the liquid.
Public Member Functions inherited from BaseForce
BaseSpecies * getBaseSpecies () const
void setBaseSpecies (BaseSpecies *baseSpecies)
Private Attributes
Mdouble liquidBridgeVolumeMax_
Max volume a liquid bridge gets during formation; any excess remains in the liquid film of the particle.
Mdouble liquidBridgeVolumeMin_
Minimum volume needed to form a liquid bridge.
Mdouble distributionCoefficient_
distribution coefficient of the liquid
Mdouble contactAngle_
contact angle between particle and liquid bridge surface (in radians)
Mdouble surfaceTension_
surface tension of the liquid
Mdouble viscosity_
viscosity of the liquid
Detailed Description
LiquidMigrationLSSpecies contains the parameters used to describe a short-range force caused by liquid bridges.
See LiquidMigrationLSInteraction::computeForce for a description of the force law.
Member Typedef Documentation
InteractionType
typedef LiquidMigrationLSInteraction LiquidMigrationLSSpecies::InteractionType
The correct Interaction type for this AdhesiveForceSpecies.
Constructor & Destructor Documentation
LiquidMigrationLSSpecies() [1/2]
LiquidMigrationLSSpecies::LiquidMigrationLSSpecies ()
The default constructor.
 {
     liquidBridgeVolumeMax_ = 0.0; //std::numeric_limits<double>::infinity();
     liquidBridgeVolumeMin_ = 0.0;
     distributionCoefficient_ = 1.0;
     surfaceTension_ = 0.0;
     contactAngle_ = 0.0;
     viscosity_ = 0.0;
 #ifdef DEBUG_CONSTRUCTOR
     logger(INFO, "LiquidMigrationLSSpecies::LiquidMigrationLSSpecies() finished");
 #endif
 }
References contactAngle_, distributionCoefficient_, INFO, liquidBridgeVolumeMax_, liquidBridgeVolumeMin_, logger, surfaceTension_, and viscosity_.
LiquidMigrationLSSpecies() [2/2]
LiquidMigrationLSSpecies::LiquidMigrationLSSpecies (const LiquidMigrationLSSpecies & s)
The default copy constructor.
Parameters
[in] the species that is copied
 {
     liquidBridgeVolumeMax_ = s.liquidBridgeVolumeMax_;
     liquidBridgeVolumeMin_ = s.liquidBridgeVolumeMin_;
     distributionCoefficient_ = s.distributionCoefficient_;
     surfaceTension_ = s.surfaceTension_;
     contactAngle_ = s.contactAngle_;
     viscosity_ = s.viscosity_;
 #ifdef DEBUG_CONSTRUCTOR
     logger(INFO, "LiquidMigrationLSSpecies::LiquidMigrationLSSpecies(const LiquidMigrationLSSpecies &p) finished");
 #endif
 }
References contactAngle_, distributionCoefficient_, INFO, liquidBridgeVolumeMax_, liquidBridgeVolumeMin_, logger, s, surfaceTension_, and viscosity_.
~LiquidMigrationLSSpecies()
LiquidMigrationLSSpecies::~LiquidMigrationLSSpecies ()
The default destructor.
 {
 #ifdef DEBUG_DESTRUCTOR
     logger(INFO, "LiquidMigrationLSSpecies::~LiquidMigrationLSSpecies() finished");
 #endif
 }
References INFO, and logger.
Member Function Documentation
getBaseName()
std::string LiquidMigrationLSSpecies::getBaseName () const
Used in Species::getName to obtain a unique name for each Species.
Returns
a string containing the name of the species (minus the word "Species")
 {
     return "LiquidMigrationLS";
 }
getContactAngle()
Mdouble LiquidMigrationLSSpecies::getContactAngle () const
used to access the contact angle between particle and liquid bridge surface.
Returns
the contact angle between particle and liquid bridge surface.
 {
     return contactAngle_;
 }
References contactAngle_.
Referenced by LiquidMigrationLSInteraction::computeAdhesionForce(), LiquidMigrationLSInteraction::getHalfFillingAngle(), and LiquidMigrationLSInteraction::getRuptureDistance().
getDistributionCoefficient()
Mdouble LiquidMigrationLSSpecies::getDistributionCoefficient () const
used to access the surface tension of the liquid.
Returns
the distribution coefficient of the liquid.
 {
     return distributionCoefficient_;
 }
References distributionCoefficient_.
Referenced by LiquidMigrationLSInteraction::distributeToOtherBridges().
getLiquidBridgeVolumeMax()
Mdouble LiquidMigrationLSSpecies::getLiquidBridgeVolumeMax () const
used to access the Volume of the liquid bridge.
Returns
the maximum volume of the liquid bridge.
 {
     return liquidBridgeVolumeMax_;
 }
References liquidBridgeVolumeMax_.
getLiquidBridgeVolumeMin()
Mdouble LiquidMigrationLSSpecies::getLiquidBridgeVolumeMin () const
used to access the Volume of the liquid bridge.
Returns
the minimum volume of the liquid bridge.
 {
     return liquidBridgeVolumeMin_;
 }
References liquidBridgeVolumeMin_.
getSurfaceTension()
Mdouble LiquidMigrationLSSpecies::getSurfaceTension () const
used to access the surface tension of the liquid.
Returns
the surface tension of the liquid.
 {
     return surfaceTension_;
 }
References surfaceTension_.
Referenced by LiquidMigrationLSInteraction::computeAdhesionForce().
getViscosity()
Mdouble LiquidMigrationLSSpecies::getViscosity () const
used to access the Viscosity of the liquid.
Returns
the the viscosity of the liquid.
 {
     return viscosity_;
 }
References viscosity_.
Referenced by LiquidMigrationLSInteraction::computeAdhesionForce().
mix()
void LiquidMigrationLSSpecies::mix (LiquidMigrationLSSpecies * S, LiquidMigrationLSSpecies * T)
creates default values for mixed species
For all parameters we assume that the harmonic mean of the parameters of the original two species is a sensible default.
Parameters
[in] S,T the two species whose properties are mixed to create the new species
 {
     liquidBridgeVolumeMax_ = BaseSpecies::average(S->getLiquidBridgeVolumeMax(), T->getLiquidBridgeVolumeMax());
     liquidBridgeVolumeMin_ = BaseSpecies::average(S->getLiquidBridgeVolumeMin(), T->getLiquidBridgeVolumeMin());
     distributionCoefficient_ = BaseSpecies::average(S->getDistributionCoefficient(), T->getDistributionCoefficient());
     surfaceTension_ = BaseSpecies::average(S->getSurfaceTension(), T->getSurfaceTension());
     contactAngle_ = BaseSpecies::average(S->getContactAngle(), T->getContactAngle());
     setInteractionDistance();
     viscosity_ = BaseSpecies::average(S->getViscosity(), T->getViscosity());
 }
References BaseSpecies::average(), contactAngle_, distributionCoefficient_, liquidBridgeVolumeMax_, liquidBridgeVolumeMin_, oomph::QuadTreeNames::S, setInteractionDistance(), surfaceTension_, and viscosity_.
read()
void LiquidMigrationLSSpecies::read (std::istream & is)
Reads the species properties from an input stream.
Parameters
[in] input stream (typically the restart file)
 {
     std::string dummy;
     is >> dummy >> liquidBridgeVolumeMax_;
     helpers::readOptionalVariable(is,"liquidBridgeVolumeMin",liquidBridgeVolumeMin_);
     is >> dummy >> distributionCoefficient_;
     is >> dummy >> surfaceTension_;
     is >> dummy >> contactAngle_;
     setInteractionDistance();
     is >> dummy >> viscosity_;
 }
References contactAngle_, distributionCoefficient_, liquidBridgeVolumeMax_, liquidBridgeVolumeMin_, helpers::readOptionalVariable(), setInteractionDistance(), oomph::Global_string_for_annotation::string(), surfaceTension_, and viscosity_.
setContactAngle()
void LiquidMigrationLSSpecies::setContactAngle (Mdouble contactAngle)
used to set the contact angle between particle and liquid bridge surface (in radians)
Parameters
[in] contactAngle the contact angle between particle and liquid bridge surface.
 {
     logger.assert_always(contactAngle >= 0, "Error in setContactAngle(%), contactAngle should be >= 0", contactAngle);
     contactAngle_ = contactAngle;
     setInteractionDistance();
 }
References contactAngle_, logger, and setInteractionDistance().
setDistributionCoefficient()
void LiquidMigrationLSSpecies::setDistributionCoefficient (Mdouble distributionCoefficient)
used to set the distribution coefficient of the liquid.
Parameters
[in] distributionCoefficient the distribution coefficient of the liquid.
 {
     logger.assert_always(distributionCoefficient >= 0 && distributionCoefficient <= 1.0,
                          "Error in setDistributionCoefficient(%), distributionCoefficient should be between 0 and 1",
                          distributionCoefficient);
     distributionCoefficient_ = distributionCoefficient;
 }
References distributionCoefficient_, and logger.
setInteractionDistance()
void LiquidMigrationLSSpecies::setInteractionDistance () virtual
returns the largest separation distance at which adhesive short-range forces can occur.
Returns
the maximum separation distance below which adhesive forces can occur (needed for contact detection)
Reimplemented from BaseAdhesiveForce.
 {
     getBaseSpecies()->setInteractionDistance((1.0 + 0.5 * contactAngle_) * (cbrt(liquidBridgeVolumeMax_) + 0.1 * pow(liquidBridgeVolumeMax_, 2.0/3.0)));
 }
References Eigen::numext::cbrt(), contactAngle_, BaseForce::getBaseSpecies(), liquidBridgeVolumeMax_, Eigen::bfloat16_impl::pow(), and BaseSpecies::setInteractionDistance().
Referenced by mix(), read(), setContactAngle(), and setLiquidBridgeVolumeMax().
setLiquidBridgeVolumeMax()
void LiquidMigrationLSSpecies::setLiquidBridgeVolumeMax (Mdouble liquidBridgeVolumeMax)
Returns a pointer to the adhesive force interaction LiquidMigrationLSInteraction.
used to set the Volume of the liquid bridge.
Parameters
[in] liquidBridgeVolume the maximum volume of the liquid bridge.
 {
     logger.assert_always(liquidBridgeVolumeMax >= 0,
                          "Error in setLiquidBridgeVolumeMax(%), liquidBridgeVolumeMax should be >= 0", liquidBridgeVolumeMax);
     liquidBridgeVolumeMax_ = liquidBridgeVolumeMax;
     setInteractionDistance();
 }
References liquidBridgeVolumeMax_, logger, and setInteractionDistance().
setLiquidBridgeVolumeMin()
void LiquidMigrationLSSpecies::setLiquidBridgeVolumeMin (Mdouble liquidBridgeVolumeMin)
used to set the Volume of the liquid bridge.
Parameters
[in] liquidBridgeVolume the minimum volume of the liquid bridge, the criterion value of the summation of the liquid film volumes for the liquid bridge forming.
 {
     logger.assert_always(liquidBridgeVolumeMin >= 0,
             "Error in setLiquidBridgeVolumeMin(%), liquidBridgeVolumeMin should be >= 0", liquidBridgeVolumeMin);
     liquidBridgeVolumeMin_ = liquidBridgeVolumeMin;
 }
References liquidBridgeVolumeMin_, and logger.
setSurfaceTension()
void LiquidMigrationLSSpecies::setSurfaceTension (Mdouble surfaceTension)
used to set the surface tension of the liquid.
Parameters
[in] surfaceTension the surface tension of the liquid.
 {
     logger.assert_always(surfaceTension >= 0, "Error in setSurfaceTension(%), surfaceTension should be >= 0", surfaceTension);
     surfaceTension_ = surfaceTension;
 }
References logger, and surfaceTension_.
setViscosity()
void LiquidMigrationLSSpecies::setViscosity (Mdouble viscosity)
used to set the Viscosity of the liquid.
Parameters
[in] viscosity the viscosity of the liquid.
 {
     logger.assert_always(viscosity >= 0, "Error in setViscosity(%), viscosity should be >= 0", viscosity);
     viscosity_ = viscosity;
 }
References logger, and viscosity_.
write()
void LiquidMigrationLSSpecies::write (std::ostream & os) const
Writes the species properties to an output stream.
Parameters
[out] output stream (typically the restart file)
 {
     os << " liquidBridgeVolumeMax " << liquidBridgeVolumeMax_;
     if (liquidBridgeVolumeMin_) os << " liquidBridgeVolumeMin " << liquidBridgeVolumeMin_;
     os << " distributionCoefficient " << distributionCoefficient_;
     os << " surfaceTension " << surfaceTension_;
     os << " contactAngle " << contactAngle_;
     os << " viscosity_ " << viscosity_;
 }
References contactAngle_, distributionCoefficient_, liquidBridgeVolumeMax_, liquidBridgeVolumeMin_, surfaceTension_, and viscosity_.
Member Data Documentation
contactAngle_
Mdouble LiquidMigrationLSSpecies::contactAngle_ private
contact angle between particle and liquid bridge surface (in radians)
Referenced by getContactAngle(), LiquidMigrationLSSpecies(), mix(), read(), setContactAngle(), setInteractionDistance(), and write().
distributionCoefficient_
Mdouble LiquidMigrationLSSpecies::distributionCoefficient_ private
distribution coefficient of the liquid
This is a variable that determines the fraction of the liquid that is to be distributed to the neighboring contacts of the particles after a liquid bridge rupture.
Referenced by getDistributionCoefficient(), LiquidMigrationLSSpecies(), mix(), read(), setDistributionCoefficient(), and write().
liquidBridgeVolumeMax_
Mdouble LiquidMigrationLSSpecies::liquidBridgeVolumeMax_ private
Max volume a liquid bridge gets during formation; any excess remains in the liquid film of the particle.
Referenced by getLiquidBridgeVolumeMax(), LiquidMigrationLSSpecies(), mix(), read(), setInteractionDistance(), setLiquidBridgeVolumeMax(), and write().
liquidBridgeVolumeMin_
Mdouble LiquidMigrationLSSpecies::liquidBridgeVolumeMin_ private
Minimum volume needed to form a liquid bridge.
Referenced by getLiquidBridgeVolumeMin(), LiquidMigrationLSSpecies(), mix(), read(), setLiquidBridgeVolumeMin(), and write().
surfaceTension_
Mdouble LiquidMigrationLSSpecies::surfaceTension_ private
surface tension of the liquid
Referenced by getSurfaceTension(), LiquidMigrationLSSpecies(), mix(), read(), setSurfaceTension(), and write().
viscosity_
Mdouble LiquidMigrationLSSpecies::viscosity_ private
viscosity of the liquid
Referenced by getViscosity(), LiquidMigrationLSSpecies(), mix(), read(), setViscosity(), and write().
The documentation for this class was generated from the following files:
LiquidMigrationLSSpecies.h
LiquidMigrationLSSpecies.cc