MercuryDPM: Eigen::internal::TensorLazyEvaluatorReadOnly< Dimensions, Expr, Device > Class Template Reference
Eigen::internal::TensorLazyEvaluatorReadOnly< Dimensions, Expr, Device > Class Template Reference
#include <TensorRef.h>
Public Types
typedef TensorEvaluator< Expr, Device >::Scalar Scalar
typedef StorageMemory< Scalar, Device > Storage
typedef Storage::Type EvaluatorPointerType
typedef TensorEvaluator< Expr, Device > EvalType
Public Member Functions
TensorLazyEvaluatorReadOnly (const Expr &expr, const Device &device)
virtual ~TensorLazyEvaluatorReadOnly ()
virtual EIGEN_DEVICE_FUNC const Dimensions & dimensions () const
virtual EIGEN_DEVICE_FUNC const Scalar * data () const
virtual EIGEN_DEVICE_FUNC const Scalar coeff (DenseIndex index) const
virtual EIGEN_DEVICE_FUNC Scalar & coeffRef (DenseIndex)
Public Member Functions inherited from Eigen::internal::TensorLazyBaseEvaluator< Dimensions, TensorEvaluator< Expr, Device >::Scalar >
TensorLazyBaseEvaluator ()
virtual ~TensorLazyBaseEvaluator ()
void incrRefCount ()
void decrRefCount ()
int refCount () const
Protected Attributes
TensorEvaluator< Expr, Device > m_impl
Dimensions m_dims
Scalar m_dummy
Member Typedef Documentation
EvalType
template<typename Dimensions , typename Expr , typename Device > typedef TensorEvaluator<Expr, Device> Eigen::internal::TensorLazyEvaluatorReadOnly< Dimensions, Expr, Device >::EvalType
EvaluatorPointerType
template<typename Dimensions , typename Expr , typename Device > typedef Storage::Type Eigen::internal::TensorLazyEvaluatorReadOnly< Dimensions, Expr, Device >::EvaluatorPointerType
Scalar
template<typename Dimensions , typename Expr , typename Device > typedef TensorEvaluator<Expr, Device>::Scalar Eigen::internal::TensorLazyEvaluatorReadOnly< Dimensions, Expr, Device >::Scalar
Storage
template<typename Dimensions , typename Expr , typename Device > typedef StorageMemory<Scalar, Device> Eigen::internal::TensorLazyEvaluatorReadOnly< Dimensions, Expr, Device >::Storage
Constructor & Destructor Documentation
TensorLazyEvaluatorReadOnly()
template<typename Dimensions , typename Expr , typename Device > Eigen::internal::TensorLazyEvaluatorReadOnly< Dimensions, Expr, Device >::TensorLazyEvaluatorReadOnly (const Expr & expr, const Device & device) inline
                                                                       : m_impl(expr, device), m_dummy(Scalar(0)) {
     m_dims = m_impl.dimensions();
     m_impl.evalSubExprsIfNeeded(NULL);
   }
References Eigen::TensorEvaluator< Derived, Device >::dimensions(), Eigen::TensorEvaluator< Derived, Device >::evalSubExprsIfNeeded(), Eigen::internal::TensorLazyEvaluatorReadOnly< Dimensions, Expr, Device >::m_dims, and Eigen::internal::TensorLazyEvaluatorReadOnly< Dimensions, Expr, Device >::m_impl.
~TensorLazyEvaluatorReadOnly()
template<typename Dimensions , typename Expr , typename Device > virtual Eigen::internal::TensorLazyEvaluatorReadOnly< Dimensions, Expr, Device >::~TensorLazyEvaluatorReadOnly () inline virtual
 { m_impl.cleanup(); }
References Eigen::TensorEvaluator< Derived, Device >::cleanup(), and Eigen::internal::TensorLazyEvaluatorReadOnly< Dimensions, Expr, Device >::m_impl.
Member Function Documentation
coeff()
template<typename Dimensions , typename Expr , typename Device > virtual EIGEN_DEVICE_FUNC const Scalar Eigen::internal::TensorLazyEvaluatorReadOnly< Dimensions, Expr, Device >::coeff (DenseIndex index) const inline virtual
Implements Eigen::internal::TensorLazyBaseEvaluator< Dimensions, TensorEvaluator< Expr, Device >::Scalar >.
 { return m_impl.coeff(index); }
References Eigen::TensorEvaluator< Derived, Device >::coeff(), and Eigen::internal::TensorLazyEvaluatorReadOnly< Dimensions, Expr, Device >::m_impl.
coeffRef()
template<typename Dimensions , typename Expr , typename Device > virtual EIGEN_DEVICE_FUNC Scalar& Eigen::internal::TensorLazyEvaluatorReadOnly< Dimensions, Expr, Device >::coeffRef (DenseIndex) inline virtual
Implements Eigen::internal::TensorLazyBaseEvaluator< Dimensions, TensorEvaluator< Expr, Device >::Scalar >.
Reimplemented in Eigen::internal::TensorLazyEvaluatorWritable< Dimensions, Expr, Device >.
{
     eigen_assert(false && "can't reference the coefficient of a rvalue");
     return m_dummy;
   };
References eigen_assert, and Eigen::internal::TensorLazyEvaluatorReadOnly< Dimensions, Expr, Device >::m_dummy.
data()
template<typename Dimensions , typename Expr , typename Device > virtual EIGEN_DEVICE_FUNC const Scalar* Eigen::internal::TensorLazyEvaluatorReadOnly< Dimensions, Expr, Device >::data () const inline virtual
Implements Eigen::internal::TensorLazyBaseEvaluator< Dimensions, TensorEvaluator< Expr, Device >::Scalar >.
 { return m_impl.data(); }
References Eigen::TensorEvaluator< Derived, Device >::data(), and Eigen::internal::TensorLazyEvaluatorReadOnly< Dimensions, Expr, Device >::m_impl.
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
dimensions()
template<typename Dimensions , typename Expr , typename Device > virtual EIGEN_DEVICE_FUNC const Dimensions& Eigen::internal::TensorLazyEvaluatorReadOnly< Dimensions, Expr, Device >::dimensions () const inline virtual
Implements Eigen::internal::TensorLazyBaseEvaluator< Dimensions, TensorEvaluator< Expr, Device >::Scalar >.
 { return m_dims; }
References Eigen::internal::TensorLazyEvaluatorReadOnly< Dimensions, Expr, Device >::m_dims.
Member Data Documentation
m_dims
template<typename Dimensions , typename Expr , typename Device > Dimensions Eigen::internal::TensorLazyEvaluatorReadOnly< Dimensions, Expr, Device >::m_dims protected
Referenced by Eigen::internal::TensorLazyEvaluatorReadOnly< Dimensions, Expr, Device >::dimensions(), and Eigen::internal::TensorLazyEvaluatorReadOnly< Dimensions, Expr, Device >::TensorLazyEvaluatorReadOnly().
m_dummy
template<typename Dimensions , typename Expr , typename Device > Scalar Eigen::internal::TensorLazyEvaluatorReadOnly< Dimensions, Expr, Device >::m_dummy protected
Referenced by Eigen::internal::TensorLazyEvaluatorReadOnly< Dimensions, Expr, Device >::coeffRef().
m_impl
template<typename Dimensions , typename Expr , typename Device > TensorEvaluator<Expr, Device> Eigen::internal::TensorLazyEvaluatorReadOnly< Dimensions, Expr, Device >::m_impl protected
Referenced by Eigen::internal::TensorLazyEvaluatorReadOnly< Dimensions, Expr, Device >::coeff(), Eigen::internal::TensorLazyEvaluatorWritable< Dimensions, Expr, Device >::coeffRef(), Eigen::internal::TensorLazyEvaluatorReadOnly< Dimensions, Expr, Device >::data(), Eigen::internal::TensorLazyEvaluatorReadOnly< Dimensions, Expr, Device >::TensorLazyEvaluatorReadOnly(), and Eigen::internal::TensorLazyEvaluatorReadOnly< Dimensions, Expr, Device >::~TensorLazyEvaluatorReadOnly().
The documentation for this class was generated from the following file:
TensorRef.h