MercuryDPM: Eigen::internal::generic_y1< T, double > Struct Template Reference
Eigen::internal::generic_y1< T, double > Struct Template Reference
#include <BesselFunctionsImpl.h>
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T run (const T &x)
Member Function Documentation
run()
template<typename T > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T Eigen::internal::generic_y1< T, double >::run (const T & x) inline static
{
     /*  j1.c
      *  Bessel function of second kind of order one
      *
      *
      *
      * SYNOPSIS:
      *
      * double x, y, y1();
      *
      * y = y1( x );
      *
      *
      *
      * DESCRIPTION:
      *
      * Returns Bessel function of the second kind of order one
      * of the argument.
      *
      * The domain is divided into the intervals [0, 8] and
      * (8, infinity). In the first interval a 25 term Chebyshev
      * expansion is used, and a call to j1() is required.
      * In the second, the asymptotic trigonometric representation
      * is employed using two rational functions of degree 5/5.
      *
      *
      *
      * ACCURACY:
      *
      *                      Absolute error:
      * arithmetic   domain      # trials      peak         rms
      *    DEC       0, 30       10000       8.6e-17     1.3e-17
      *    IEEE      0, 30       30000       1.0e-15     1.3e-16
      *
      * (error criterion relative when |y1| > 1).
      *
      */
     const double PP[] = {7.62125616208173112003E-4, 7.31397056940917570436E-2, 1.12719608129684925192E0,
                          5.11207951146807644818E0,  8.42404590141772420927E0,  5.21451598682361504063E0,
                          1.00000000000000000254E0};
     const double PQ[] = {5.71323128072548699714E-4, 6.88455908754495404082E-2, 1.10514232634061696926E0,
                          5.07386386128601488557E0,  8.39985554327604159757E0,  5.20982848682361821619E0,
                          9.99999999999999997461E-1};
     const double QP[] = {5.10862594750176621635E-2, 4.98213872951233449420E0, 7.58238284132545283818E1,
                          3.66779609360150777800E2,  7.10856304998926107277E2, 5.97489612400613639965E2,
                          2.11688757100572135698E2,  2.52070205858023719784E1};
     const double QQ[] = {1.00000000000000000000E0, 7.42373277035675149943E1, 1.05644886038262816351E3,
                          4.98641058337653607651E3, 9.56231892404756170795E3, 7.99704160447350683650E3,
                          2.82619278517639096600E3, 3.36093607810698293419E2};
     const double YP[] = {1.26320474790178026440E9,   -6.47355876379160291031E11, 1.14509511541823727583E14,
                          -8.12770255501325109621E15, 2.02439475713594898196E17,  -7.78877196265950026825E17};
     const double YQ[] = {1.00000000000000000000E0,  5.94301592346128195359E2,  2.35564092943068577943E5,
                          7.34811944459721705660E7,  1.87601316108706159478E10, 3.88231277496238566008E12,
                          6.20557727146953693363E14, 6.87141087355300489866E16, 3.97270608116560655612E18};
     const T SQ2OPI = pset1<T>(.79788456080286535588);
     const T NEG_THPIO4 = pset1<T>(-2.35619449019234492885); /* -3*pi/4 */
     const T TWOOPI = pset1<T>(0.636619772367581343075535);  /* 2/pi */
     const T NEG_MAXNUM = pset1<T>(-NumTraits<double>::infinity());
     T z = pmul(x, x);
     T x_le_five = pdiv(internal::ppolevl<T, 5>::run(z, YP), internal::ppolevl<T, 8>::run(z, YQ));
     x_le_five =
         pmadd(x_le_five, x, pmul(TWOOPI, pmadd(generic_j1<T, double>::run(x), plog(x), pdiv(pset1<T>(-1.0), x))));
     x_le_five = pselect(pcmp_le(x, pset1<T>(0.0)), NEG_MAXNUM, x_le_five);
     T s = pdiv(pset1<T>(25.0), z);
     T p = pdiv(internal::ppolevl<T, 6>::run(s, PP), internal::ppolevl<T, 6>::run(s, PQ));
     T q = pdiv(internal::ppolevl<T, 7>::run(s, QP), internal::ppolevl<T, 7>::run(s, QQ));
     T xn = padd(x, NEG_THPIO4);
     T w = pdiv(pset1<T>(5.0), x);
     p = pmadd(p, psin(xn), pmul(w, pmul(q, pcos(xn))));
     T x_gt_five = pmul(p, pmul(SQ2OPI, prsqrt(x)));
     return pselect(pcmp_le(x, pset1<T>(5.0)), x_le_five, x_gt_five);
   }
References p, Eigen::internal::padd(), Eigen::internal::pcmp_le(), Eigen::internal::pcos(), Eigen::internal::pdiv(), Eigen::internal::plog(), Eigen::internal::pmadd(), Eigen::internal::pmul(), Eigen::internal::prsqrt(), Eigen::internal::pselect(), Eigen::internal::psin(), Eigen::numext::q, s, w, and plotDoE::x.
The documentation for this struct was generated from the following file:
BesselFunctionsImpl.h