MercuryDPM: oomph::PressureAdvectionDiffusionValidation Namespace Reference
oomph::PressureAdvectionDiffusionValidation Namespace Reference
Functions
void wind_function (const Vector< double > &x, Vector< double > &wind)
Wind.
void get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void get_exact_u (const Vector< double > &x, double &u)
Exact solution as a scalar.
double source_function (const Vector< double > &x_vect)
Source function required to make the solution above an exact solution.
Variables
unsigned Flag = 0
Flag for solution.
double Peclet = 0.0
Peclet number – overwrite with actual Reynolds number.
Detailed Description
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// Namespace for exact solution for pressure advection diffusion problem
Function Documentation
get_exact_u() [1/2]
void oomph::PressureAdvectionDiffusionValidation::get_exact_u (const Vector< double > & x, double & u)
Exact solution as a scalar.
     {
       if (Flag == 0)
       {
         u = x[0] * x[0] * pow(1.0 - x[0], 2.0) * x[1] * x[1] *
             pow(1.0 - x[1], 2.0);
       }
       else
       {
         u = 0.1E1 - Peclet * x[0] * (0.1E1 - 0.5 * x[0]);
       }
     }
References Flag, Peclet, Eigen::bfloat16_impl::pow(), and plotDoE::x.
get_exact_u() [2/2]
void oomph::PressureAdvectionDiffusionValidation::get_exact_u (const Vector< double > & x, Vector< double > & u)
Exact solution as a Vector.
     {
       u.resize(3);
       wind_function(x, u);
       if (Flag == 0)
       {
         u[2] = x[0] * x[0] * pow(1.0 - x[0], 2.0) * x[1] * x[1] *
                pow(1.0 - x[1], 2.0);
       }
       else
       {
         u[2] = 0.1E1 - Peclet * x[0] * (0.1E1 - 0.5 * x[0]);
       }
     }
References Flag, Peclet, Eigen::bfloat16_impl::pow(), wind_function(), and plotDoE::x.
Referenced by oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::doc_solution().
source_function()
double oomph::PressureAdvectionDiffusionValidation::source_function (const Vector< double > & x_vect)
Source function required to make the solution above an exact solution.
     {
       double x[2];
       x[0] = x_vect[0];
       x[1] = x_vect[1];
       double source = 0.0;
       if (Flag == 0)
       {
         source =
           Peclet *
             (sin(0.6E1 * x[1]) * (2.0 * x[0] * pow(1.0 - x[0], 2.0) * x[1] *
                                     x[1] * pow(1.0 - x[1], 2.0) -
                                   2.0 * x[0] * x[0] * (1.0 - x[0]) * x[1] *
                                     x[1] * pow(1.0 - x[1], 2.0)) +
              cos(0.6E1 * x[0]) * (2.0 * x[0] * x[0] * pow(1.0 - x[0], 2.0) *
                                     x[1] * pow(1.0 - x[1], 2.0) -
                                   2.0 * x[0] * x[0] * pow(1.0 - x[0], 2.0) *
                                     x[1] * x[1] * (1.0 - x[1]))) -
           2.0 * pow(1.0 - x[0], 2.0) * x[1] * x[1] * pow(1.0 - x[1], 2.0) +
           8.0 * x[0] * (1.0 - x[0]) * x[1] * x[1] * pow(1.0 - x[1], 2.0) -
           2.0 * x[0] * x[0] * x[1] * x[1] * pow(1.0 - x[1], 2.0) -
           2.0 * x[0] * x[0] * pow(1.0 - x[0], 2.0) * pow(1.0 - x[1], 2.0) +
           8.0 * x[0] * x[0] * pow(1.0 - x[0], 2.0) * x[1] * (1.0 - x[1]) -
           2.0 * x[0] * x[0] * pow(1.0 - x[0], 2.0) * x[1] * x[1];
       }
       else
       {
         source = Peclet * (-0.1E1 * Peclet * (0.1E1 - 0.5 * x[0]) +
                            0.5 * Peclet * x[0]) -
                  0.1E1 * Peclet;
       }
       return source;
     }
References cos(), Flag, Peclet, Eigen::bfloat16_impl::pow(), sin(), TestProblem::source(), and plotDoE::x.
Referenced by oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::validate().
wind_function()
void oomph::PressureAdvectionDiffusionValidation::wind_function (const Vector< double > & x, Vector< double > & wind)
Wind.
     {
       if (Flag == 0)
       {
         wind[0] = sin(6.0 * x[1]);
         wind[1] = cos(6.0 * x[0]);
       }
       else
       {
         wind[0] = 1.0;
         wind[1] = 0.0;
       }
     }
References cos(), Flag, sin(), and plotDoE::x.
Referenced by get_exact_u(), and oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::pin_all_non_pressure_dofs().
Variable Documentation
Flag
unsigned oomph::PressureAdvectionDiffusionValidation::Flag = 0
Flag for solution.
Referenced by CombCanSpineMesh< ELEMENT, INTERFACE_ELEMENT >::build_single_layer_mesh(), CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::build_single_layer_mesh(), get_exact_u(), source_function(), test_reference(), oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::validate(), and wind_function().
Peclet
double oomph::PressureAdvectionDiffusionValidation::Peclet = 0.0
Peclet number – overwrite with actual Reynolds number.
Referenced by get_exact_u(), source_function(), and oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::validate().