MercuryDPM: two_d_poisson_compare_solvers.cc File Reference
two_d_poisson_compare_solvers.cc File Reference
#include "generic.h"
#include "poisson.h"
#include "meshes/simple_rectangular_quadmesh.h"
Classes
class PoissonProblem< ELEMENT >
Micky mouse Poisson problem.
Namespaces
TanhSolnForPoisson
Namespace for exact solution for Poisson equation with "sharp step".
Functions
void TanhSolnForPoisson::get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void TanhSolnForPoisson::get_source (const Vector< double > &x, double &source)
Source function to make it an exact solution.
void run (const string &dir_name, LinearSolver *linear_solver_pt, const unsigned nel_1d, bool mess_up_order)
int main ()
Driver code for 2D Poisson problem – compare different solvers.
Function Documentation
main()
int main ()
Driver code for 2D Poisson problem – compare different solvers.
Use SuperLU with compressed row storage
Use compressed row storage
Switch on full doc
Use SuperLU with compressed column storage
Use compressed row storage
Switch on full doc
Use dense matrix LU decomposition
Use dense matrix LU decomposition
 {
  // Pointer to linear solver
  LinearSolver* linear_solver_pt;
  // Result directory
  string dir_name;
  // Cpu start/end times
  clock_t cpu_start,cpu_end;
  // Storage for cpu times with and without messed up order
  Vector<double> superlu_cr_cpu(2);
  Vector<double> superlu_cc_cpu(2);
  Vector<double> hsl_ma42_cpu(2);
  Vector<double> hsl_ma42_reordered_cpu(2);
  Vector<double> dense_lu_cpu(2);
  Vector<double> fd_lu_cpu(2);
  // Flag to indicate if order should be messed up:
  bool mess_up_order;
  // Number of elements along 1D edge of mesh; total number of elements
  // is nel_1d x nel_1d
  unsigned nel_1d;
  // Do run with and without messed up elements
  for (unsigned mess=0;mess<2;mess++)
   {
    // Mess up order?
    if (mess==0)
     {
      mess_up_order=true;
     }
    else
     {
      mess_up_order=false;
     }
    //-----------------------------------------
    cout << std::endl;
    cout << " Use SuperLU with compressed row storage: " << std::endl;
    cout << "========================================= " << std::endl;
    cout << std::endl;
    // Start cpu clock
    cpu_start=clock();
    // Build linear solver
    linear_solver_pt = new SuperLUSolver;
    static_cast<SuperLUSolver*>(linear_solver_pt)
     ->use_compressed_row_for_superlu_serial();
    static_cast<SuperLUSolver*>(linear_solver_pt)->enable_doc_stats();
    // Choose result directory
    dir_name="RESLT_cr";
    // Number of elements along 1D edge of mesh; total number of elements
    // is nel_1d x nel_1d
    nel_1d=20;
    // Run it
    run(dir_name,linear_solver_pt,nel_1d,mess_up_order);
    // Note: solver does not have to be deleted -- it's killed automatically
    // in the problem destructor.
    // End cpu clock
    cpu_end=clock();
    // Timing
    superlu_cr_cpu[mess]=double(cpu_end-cpu_start)/CLOCKS_PER_SEC;
    //--------------------------------------------
    cout << std::endl;
    cout << " Use SuperLU with compressed column storage: " << std::endl;
    cout << "============================================ " << std::endl;
    cout << std::endl;
    // Start cpu clock
    cpu_start=clock();
    // Build linear solver
    linear_solver_pt = new SuperLUSolver;
    static_cast<SuperLUSolver*>(linear_solver_pt)
     ->use_compressed_column_for_superlu_serial();
    static_cast<SuperLUSolver*>(linear_solver_pt)->enable_doc_stats();
    // Choose result directory
    dir_name="RESLT_cc";
    // Number of elements along 1D edge of mesh; total number of elements
    // is nel_1d x nel_1d
    nel_1d=20;
    // Run it
    run(dir_name,linear_solver_pt,nel_1d,mess_up_order);
    // Note: solver does not have to be deleted -- it's killed automatically
    // in the problem destructor.
    // End cpu clock
    cpu_end=clock();
    // Timing
    superlu_cc_cpu[mess]=double(cpu_end-cpu_start)/CLOCKS_PER_SEC;
 #ifdef HAVE_HSL_SOURCES
    //---------------------------------------------------------
    cout << std::endl;
    cout << " Use HSL frontal solver MA42 without element re-ordering: " << std::endl;
    cout << "========================================================= " << std::endl;
    cout << std::endl;
    // Start cpu clock
    cpu_start=clock();
    // Build linear solver
    linear_solver_pt = new HSL_MA42;
    static_cast<HSL_MA42*>(linear_solver_pt)->enable_doc_stats();
    // Choose result directory
    dir_name="RESLT_frontal";
    // Number of elements along 1D edge of mesh; total number of elements
    // is nel_1d x nel_1d
    nel_1d=20;
    // Run it
    run(dir_name,linear_solver_pt,nel_1d,mess_up_order);
    // Note: solver does not have to be deleted -- it's killed automatically
    // in the problem destructor.
    // End cpu clock
    cpu_end=clock();
    // Timing
    hsl_ma42_cpu[mess]=double(cpu_end-cpu_start)/CLOCKS_PER_SEC;
    //--------------------------------------------------------------------------
    cout << std::endl;
    cout << " Use HSL frontal solver MA42 with element re-ordering: " << std::endl;
    cout << "====================================================== " << std::endl;
    cout << std::endl;
    // Start cpu clock
    cpu_start=clock();
    // Build linear solver
    linear_solver_pt = new HSL_MA42;
    static_cast<HSL_MA42*>(linear_solver_pt)->enable_doc_stats();
    static_cast<HSL_MA42*>(linear_solver_pt)->enable_reordering();
    // Choose result directory
    dir_name="RESLT_frontal_reordered";
    // Number of elements along 1D edge of mesh; total number of elements
    // is nel_1d x nel_1d
    nel_1d=20;
    // Run it
    run(dir_name,linear_solver_pt,nel_1d,mess_up_order);
    // Note: solver does not have to be deleted -- it's killed automatically
    // in the problem destructor.
    // End cpu clock
    cpu_end=clock();
    // Timing
    hsl_ma42_reordered_cpu[mess]=double(cpu_end-cpu_start)/CLOCKS_PER_SEC;
 #endif
    //-----------------------------------
    cout << std::endl;
    cout << " Use dense matrix LU decomposition: " << std::endl;
    cout << "=================================== " << std::endl;
    cout << std::endl;
    // Start cpu clock
    cpu_start=clock();
    // Build linear solver
    linear_solver_pt = new DenseLU;
    // Choose result directory
    dir_name="RESLT_dense_LU";
    // Number of elements along 1D edge of mesh; total number of elements
    // is nel_1d x nel_1d
    nel_1d=4;
    // Run it
    run(dir_name,linear_solver_pt,nel_1d,mess_up_order);
    // Note: solver does not have to be deleted -- it's killed automatically
    // in the problem destructor.
    // End cpu clock
    cpu_end=clock();
    // Timing
    dense_lu_cpu[mess]=double(cpu_end-cpu_start)/CLOCKS_PER_SEC;
    //-----------------------------------
    cout << std::endl;
    cout << " Use dense FD-ed matrix LU decomposition: " << std::endl;
    cout << "========================================= " << std::endl;
    cout << std::endl;
    // Start cpu clock
    cpu_start=clock();
    // Build linear solver
    linear_solver_pt = new FD_LU;
    // Choose result directory
    dir_name="RESLT_FD_LU";
    // Number of elements along 1D edge of mesh; total number of elements
    // is nel_1d x nel_1d
    nel_1d=4;
    // Run it
    run(dir_name,linear_solver_pt,nel_1d,mess_up_order);
    // Note: solver does not have to be deleted -- it's killed automatically
    // in the problem destructor.
    // End cpu clock
    cpu_end=clock();
    // Timing
    fd_lu_cpu[mess]=double(cpu_end-cpu_start)/CLOCKS_PER_SEC;
   }
  // Doc timings with and without messed up elements
  for (unsigned mess=0;mess<2;mess++)
   {
    cout << std::endl   << std::endl   << std::endl ;
    if (mess==0)
     {
      cout << "TIMINGS WITH MESSED UP ORDERING OF ELEMENTS: " << std::endl;
      cout << "============================================ " << std::endl;
     }
    else
     {
      cout << "TIMINGS WITHOUT MESSED UP ORDERING OF ELEMENTS: " << std::endl;
      cout << "=============================================== " << std::endl;
     }
    cout << "CPU time with SuperLU compressed row                 : "
         <<  superlu_cr_cpu[mess] << std::endl;
    cout << "CPU time with SuperLU compressed col                 : "
         <<  superlu_cc_cpu[mess] << std::endl;
 #ifdef HAVE_HSL_SOURCES
    cout << "CPU time with MA42 frontal solver                    : "
         <<  hsl_ma42_cpu[mess] << std::endl;
    cout << "CPU time with MA42 frontal solver (incl. reordering) : "
         <<  hsl_ma42_reordered_cpu[mess] << std::endl;
 #endif
    cout << "CPU time with dense LU solver (fewer elements!)      : "
         <<  dense_lu_cpu[mess] << std::endl;
    cout << "CPU time with dense LU solver & FD (fewer elements!) : "
         <<  fd_lu_cpu[mess] << std::endl;
    cout << std::endl   << std::endl   << std::endl ;
   }
 } //end of main
References run().
run()
void run (const string & dir_name, LinearSolver * linear_solver_pt, const unsigned nel_1d, bool mess_up_order)
Build and run problem with specified linear solver. Also pass flag to specify if order of elements should be messed up. nel_1d is the number of elements along the 1D mesh edge. Total number of elements is nel_1d x nel_1d.
Set linear solver:
 {
  //Set up the problem
  //------------------
  // Create the problem with 2D nine-node elements from the
  // QPoissonElement family. Pass pointer to source function
  // and flag to specify if order of elements should be messed up.
  PoissonProblem<QPoissonElement<2,3> >
   problem(&TanhSolnForPoisson::get_source,nel_1d,mess_up_order);
  //--------------------
  problem.linear_solver_pt() = linear_solver_pt;
  // Create label for output
  //------------------------
  DocInfo doc_info;
  // Set output directory
  doc_info.set_directory(dir_name);
  // Step number
  doc_info.number()=0;
  // Check if we're ready to go:
  //----------------------------
  cout << "\n\n\nProblem self-test:";
  if (problem.self_test()==0)
   {
    cout << "passed: Problem can be solved." << std::endl;
   }
  else
   {
    throw OomphLibError("Self test failed",
                        OOMPH_CURRENT_FUNCTION,
                        OOMPH_EXCEPTION_LOCATION);
   }
  // Set the orientation of the "step" to 45 degrees
  TanhSolnForPoisson::TanPhi=1.0;
  // Initial value for the steepness of the "step"
  TanhSolnForPoisson::Alpha=1.0;
  // Solve the problem
  problem.newton_solve();
  //Output the solution
  problem.doc_solution(doc_info);
 } //end of run
References TanhSolnForPoisson::Alpha, TanhSolnForPoisson::get_source(), oomph::DocInfo::number(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, problem, oomph::DocInfo::set_directory(), and TanhSolnForPoisson::TanPhi.
Referenced by Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, InnerProduct >::addTo(), adjoint(), Eigen::DenseBase< Derived >::all(), Eigen::SimplicialCholeskyBase< Derived >::analyzePattern_preordered(), Eigen::DenseBase< Derived >::any(), Eigen::DynamicSGroup::apply(), Eigen::internal::call_assignment_no_alias(), Eigen::internal::call_assignment_no_alias_no_transpose(), Eigen::internal::call_dense_assignment_loop(), Eigen::internal::call_restricted_packet_assignment_no_alias(), cast_test(), casting_all(), Eigen::MatrixBase< Derived >::computeInverseAndDetWithCheck(), Eigen::DenseBase< Derived >::count(), DefaultAssign(), DeviceAssign(), EIGEN_DECLARE_TEST(), Eigen::numext::equal_strict(), Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::evalSubExprsIfNeededCommon(), Eigen::internal::generic_product_impl< Inverse< Lhs >, Rhs, PermutationShape, MatrixShape, ProductTag >::evalTo(), Eigen::internal::generic_product_impl< Lhs, Inverse< Rhs >, MatrixShape, PermutationShape, ProductTag >::evalTo(), Eigen::internal::generic_product_impl< Lhs, Rhs, PermutationShape, MatrixShape, ProductTag >::evalTo(), Eigen::internal::generic_product_impl< Lhs, Rhs, MatrixShape, PermutationShape, ProductTag >::evalTo(), Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, InnerProduct >::evalTo(), Eigen::internal::h_array_apply(), Eigen::internal::h_array_apply_and_reduce(), Eigen::internal::h_array_zip(), Eigen::internal::h_array_zip_and_reduce(), Eigen::internal::instantiate_by_c_array(), main(), mapstaticmethods(), Eigen::numext::not_equal_strict(), Eigen::internal::scalar_unary_pow_op< Scalar, ExponentScalar, BaseIsInteger, true, false, false >::operator()(), Eigen::internal::gemm_functor< Scalar, Index, Gemm, Lhs, Rhs, Dest, BlockingType >::operator()(), Eigen::RotationBase< Derived, Dim_ >::operator*(), Eigen::Transform< Scalar_, Dim_, Mode_, Options_ >::operator*(), Eigen::Transform< Scalar_, Dim_, Mode_, Options_ >::operator=(), Eigen::EulerAngles< Scalar_, _System >::operator=(), Eigen::QuaternionBase< Derived >::operator=(), Eigen::TensorAsyncDevice< ExpressionType, DeviceType, DoneCallback >::operator=(), Eigen::SparseVector< Scalar_, Options_, StorageIndex_ >::operator=(), Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::packet(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::packet(), Eigen::internal::scalar_unary_pow_op< Scalar, ExponentScalar, false, false, false, false >::packetOp(), Eigen::internal::scalar_unary_pow_op< Scalar, ExponentScalar, BaseIsInteger, true, false, false >::packetOp(), Eigen::internal::pcast(), Eigen::internal::preinterpret(), Eigen::internal::psignbit(), Eigen::SelfAdjointView< MatrixType_, UpLo >::rankUpdate(), Eigen::internal::lapacke_helpers::lapacke_llt< Scalar, Mode >::rankUpdate(), Eigen::DenseBase< Derived >::redux(), Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::resize(), Eigen::PlainObjectBase< Derived >::resize(), Eigen::PlainObjectBase< Derived >::resizeLike(), Eigen::VectorwiseOp< ExpressionType, Direction >::reverseInPlace(), test_transform< func, arg1, arg2 >::run(), cast_test_impl< SrcType, DstType, RowsAtCompileTime, ColsAtCompileTime >::run(), test_cast< SrcPacket, TgtPacket >::run(), Eigen::internal::reduce< Reducer, A, Ts... >::run(), Eigen::internal::h_array_reduce< Reducer, T, N, n >::run(), Eigen::internal::h_instantiate_by_c_array< InstType, ArrType, N, false, Ps... >::run(), Eigen::internal::h_instantiate_by_c_array< InstType, ArrType, N, true, Ps... >::run(), Eigen::internal::random_impl< bfloat16 >::run(), Eigen::internal::visit_impl< Derived, Visitor, ShortCircuitEvaulation >::run(), Eigen::internal::visitor_impl< Visitor, Derived, Dynamic, false, false, ShortCircuitEvaluation >::run(), Eigen::internal::visitor_impl< Visitor, Derived, Dynamic, true, false, ShortCircuitEvaluation >::run(), Eigen::internal::visitor_impl< Visitor, Derived, Dynamic, false, true, ShortCircuitEvaluation >::run(), Eigen::internal::visitor_impl< Visitor, Derived, Dynamic, true, true, ShortCircuitEvaluation >::run(), Eigen::internal::inner_product_impl< Evaluator, true >::run(), Eigen::internal::redux_impl< Func, Evaluator, DefaultTraversal, CompleteUnrolling >::run(), Eigen::internal::redux_impl< Func, Evaluator, LinearTraversal, CompleteUnrolling >::run(), Eigen::internal::redux_impl< Func, Evaluator, SliceVectorizedTraversal, Unrolling >::run(), Eigen::internal::random_impl< half >::run(), Eigen::internal::gemv_dense_selector< OnTheLeft, StorageOrder, BlasCompatible >::run(), Eigen::internal::triangular_solver_unroller< Lhs, Rhs, Mode, LoopIndex, Size, false >::run(), Eigen::internal::triangular_solver_selector< Lhs, Rhs, OnTheLeft, Mode, CompleteUnrolling, 1 >::run(), Eigen::internal::default_inner_product_impl< Lhs, Rhs, Conj >::run(), mapstaticmethods_impl< PlainObjectType, false, IsVector >::run(), Eigen::internal::random_int_impl< Scalar, true, true >::run(), Eigen::internal::random_default_impl< Scalar, true, false >::run(), Eigen::internal::tensor_static_symgroup_do_apply< internal::type_list< first, next... > >::run(), Eigen::numext::equal_strict_impl< X, Y, true, true, true, false >::run(), Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, true >::run(), Eigen::internal::sparse_vector_assign_selector< Dest, Src, SVA_RuntimeSwitch >::run(), Eigen::internal::Assignment< DstXprType, CwiseNullaryOp< scalar_constant_op< typename DstXprType::Scalar >, SrcPlainObject >, assign_op< typename DstXprType::Scalar, typename DstXprType::Scalar >, Dense2Dense, Weak >::run(), Eigen::internal::Assignment< DstXprType, CwiseNullaryOp< scalar_zero_op< typename DstXprType::Scalar >, SrcPlainObject >, assign_op< typename DstXprType::Scalar, typename DstXprType::Scalar >, Dense2Dense, Weak >::run(), Eigen::internal::AssignmentWithDevice< DstXprType, Product< Lhs, Rhs, Options >, Functor, Device, Dense2Dense, Weak >::run(), Eigen::internal::triangular_matrix_vector_product< Index, Mode, LhsScalar, ConjLhs, RhsScalar, ConjRhs, RowMajor, Version >::run(), Eigen::internal::triangular_matrix_vector_product< Index, Mode, LhsScalar, ConjLhs, RhsScalar, ConjRhs, ColMajor, Version >::run(), Eigen::internal::etor_product_packet_impl< RowMajor, UnrollingIndex, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::internal::etor_product_packet_impl< ColMajor, UnrollingIndex, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::internal::general_rank1_update< Scalar, Index, RowMajor, ConjLhs, ConjRhs >::run(), Eigen::internal::selfadjoint_packed_rank1_update< Scalar, Index, RowMajor, UpLo, ConjLhs, ConjRhs >::run(), Eigen::selfadjoint_rank1_update< Scalar, Index, RowMajor, UpLo, ConjLhs, ConjRhs >::run(), Eigen::internal::random_default_impl< Scalar, false, false >::run(), Eigen::internal::dense_assignment_loop< Kernel, SliceVectorizedTraversal, NoUnrolling >::run(), Eigen::internal::dense_assignment_loop_with_device< Kernel, Device, Traversal, Unrolling >::run(), Eigen::internal::tuple_impl::tuple_cat_impl< NTuples, TupleImpl< N1, Args1... >, TupleImpl< N2, Args2... >, Tuples... >::run(), Eigen::internal::generic_product_impl< Lhs, Rhs, TriangularShape, DenseShape, ProductTag >::scaleAndAddTo(), Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, TriangularShape, ProductTag >::scaleAndAddTo(), Eigen::internal::generic_product_impl< Lhs, Rhs, SelfAdjointShape, DenseShape, ProductTag >::scaleAndAddTo(), Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, SelfAdjointShape, ProductTag >::scaleAndAddTo(), Eigen::DenseBase< Derived >::setConstant(), Eigen::DenseBase< Derived >::setZero(), Eigen::numext::signbit(), Eigen::internal::sparse_time_dense_product(), Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, InnerProduct >::subTo(), test_execute_binary_expr(), test_execute_broadcasting(), test_execute_broadcasting_of_forced_eval(), test_execute_chipping_lvalue(), test_execute_chipping_rvalue(), test_execute_generator_op(), test_execute_reshape(), test_execute_reverse_rvalue(), test_execute_slice_lvalue(), test_execute_slice_rvalue(), test_execute_unary_expr(), test_tensor_ostream(), testGeneral(), testLogThenExp(), testMatrixSqrt(), tpmv(), tpsv(), Eigen::Transform< Scalar_, Dim_, Mode_, Options_ >::Transform(), Eigen::DenseBase< Derived >::transposeInPlace(), VerifyBlockAssignment(), VerifyBlockEvaluator(), Eigen::viewAsCholmod(), Eigen::DenseBase< Derived >::visit(), and Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::writePacket().