MercuryDPM: GpuHelper Class Reference
GpuHelper Class Reference
#include <gpuhelper.h>
Public Types
enum ProjectionMode2D { PM_Normalized = 1 , PM_Viewport = 2 }
Public Member Functions
GpuHelper ()
~GpuHelper ()
void pushProjectionMode2D (ProjectionMode2D pm)
void popProjectionMode2D ()
template<typename Scalar , int Flags_>
void multMatrix (const Matrix< Scalar, 4, 4, Flags_, 4, 4 > &mat, GLenum matrixTarget)
template<typename Scalar , int Flags_>
void loadMatrix (const Eigen::Matrix< Scalar, 4, 4, Flags_, 4, 4 > &mat, GLenum matrixTarget)
template<typename Scalar , typename Derived >
void loadMatrix (const Eigen::CwiseNullaryOp< Eigen::internal::scalar_identity_op< Scalar >, Derived > &, GLenum matrixTarget)
void forceMatrixTarget (GLenum matrixTarget)
void setMatrixTarget (GLenum matrixTarget)
template<typename Scalar , int Flags_>
void pushMatrix (const Matrix< Scalar, 4, 4, Flags_, 4, 4 > &mat, GLenum matrixTarget)
template<typename Scalar , typename Derived >
void pushMatrix (const Eigen::CwiseNullaryOp< Eigen::internal::scalar_identity_op< Scalar >, Derived > &, GLenum matrixTarget)
void pushMatrix (GLenum matrixTarget)
void popMatrix (GLenum matrixTarget)
void drawVector (const Vector3f &position, const Vector3f &vec, const Color &color, float aspect=50.)
void drawVectorBox (const Vector3f &position, const Vector3f &vec, const Color &color, float aspect=50.)
void drawUnitCube (void)
void drawUnitSphere (int level=0)
void draw (GLenum mode, uint nofElement)
draw the nofElement first elements
void draw (GLenum mode, uint start, uint end)
draw a range of elements
void draw (GLenum mode, const std::vector< uint > *pIndexes)
draw an indexed subset
Protected Member Functions
void update (void)
Protected Attributes
GLuint mColorBufferId
int mVpWidth
int mVpHeight
GLenum mCurrentMatrixTarget
bool mInitialized
Member Enumeration Documentation
ProjectionMode2D
enum GpuHelper::ProjectionMode2D
Enumerator
PM_Normalized
PM_Viewport
 { PM_Normalized = 1, PM_Viewport = 2 };
Constructor & Destructor Documentation
GpuHelper()
GpuHelper::GpuHelper ()
                      {
   mVpWidth = mVpHeight = 0;
   mCurrentMatrixTarget = 0;
   mInitialized = false;
 }
References mCurrentMatrixTarget, mInitialized, mVpHeight, and mVpWidth.
~GpuHelper()
GpuHelper::~GpuHelper ()
 {}
Member Function Documentation
draw() [1/3]
void GpuHelper::draw (GLenum mode, const std::vector< uint > * pIndexes) inline
draw an indexed subset
{
   glDrawElements(mode, pIndexes->size(), GL_UNSIGNED_INT, &(pIndexes->front()));
 }
draw() [2/3]
void GpuHelper::draw (GLenum mode, uint nofElement) inline
draw the nofElement first elements
 { glDrawArrays(mode, 0, nofElement); }
draw() [3/3]
void GpuHelper::draw (GLenum mode, uint start, uint end) inline
draw a range of elements
 { glDrawArrays(mode, start, end - start); }
References Eigen::placeholders::end, and oomph::CumulativeTimings::start().
drawUnitCube()
void GpuHelper::drawUnitCube (void)
{
   static float vertices[][3] = {{-0.5, -0.5, -0.5}, {0.5, -0.5, -0.5}, {-0.5, 0.5, -0.5}, {0.5, 0.5, -0.5},
                                 {-0.5, -0.5, 0.5},  {0.5, -0.5, 0.5},  {-0.5, 0.5, 0.5},  {0.5, 0.5, 0.5}};
   glBegin(GL_QUADS);
   glNormal3f(0, 0, -1);
   glVertex3fv(vertices[0]);
   glVertex3fv(vertices[2]);
   glVertex3fv(vertices[3]);
   glVertex3fv(vertices[1]);
   glNormal3f(0, 0, 1);
   glVertex3fv(vertices[4]);
   glVertex3fv(vertices[5]);
   glVertex3fv(vertices[7]);
   glVertex3fv(vertices[6]);
   glNormal3f(0, -1, 0);
   glVertex3fv(vertices[0]);
   glVertex3fv(vertices[1]);
   glVertex3fv(vertices[5]);
   glVertex3fv(vertices[4]);
   glNormal3f(0, 1, 0);
   glVertex3fv(vertices[2]);
   glVertex3fv(vertices[6]);
   glVertex3fv(vertices[7]);
   glVertex3fv(vertices[3]);
   glNormal3f(-1, 0, 0);
   glVertex3fv(vertices[0]);
   glVertex3fv(vertices[4]);
   glVertex3fv(vertices[6]);
   glVertex3fv(vertices[2]);
   glNormal3f(1, 0, 0);
   glVertex3fv(vertices[1]);
   glVertex3fv(vertices[3]);
   glVertex3fv(vertices[7]);
   glVertex3fv(vertices[5]);
   glEnd();
 }
Referenced by drawVectorBox().
drawUnitSphere()
void GpuHelper::drawUnitSphere (int level = 0)
{
   static IcoSphere sphere;
   sphere.draw(level);
 }
References IcoSphere::draw().
drawVector()
void GpuHelper::drawVector (const Vector3f & position, const Vector3f & vec, const Color & color, float aspect = 50.)
{
   static GLUquadricObj* cylinder = gluNewQuadric();
   glColor4fv(color.data());
   float length = vec.norm();
   pushMatrix(GL_MODELVIEW);
   glTranslatef(position.x(), position.y(), position.z());
   Vector3f ax = Matrix3f::Identity().col(2).cross(vec);
   ax.normalize();
   Vector3f tmp = vec;
   tmp.normalize();
   float angle = 180.f / M_PI * acos(tmp.z());
   if (angle > 1e-3) glRotatef(angle, ax.x(), ax.y(), ax.z());
   gluCylinder(cylinder, length / aspect, length / aspect, 0.8 * length, 10, 10);
   glTranslatef(0.0, 0.0, 0.8 * length);
   gluCylinder(cylinder, 2.0 * length / aspect, 0.0, 0.2 * length, 10, 10);
   popMatrix(GL_MODELVIEW);
 }
References acos(), Jeffery_Solution::angle(), plotDoE::ax, e(), M_PI, popMatrix(), pushMatrix(), and tmp.
Referenced by RenderingWidget::drawScene().
drawVectorBox()
void GpuHelper::drawVectorBox (const Vector3f & position, const Vector3f & vec, const Color & color, float aspect = 50.)
{
   static GLUquadricObj* cylinder = gluNewQuadric();
   glColor4fv(color.data());
   float length = vec.norm();
   pushMatrix(GL_MODELVIEW);
   glTranslatef(position.x(), position.y(), position.z());
   Vector3f ax = Matrix3f::Identity().col(2).cross(vec);
   ax.normalize();
   Vector3f tmp = vec;
   tmp.normalize();
   float angle = 180.f / M_PI * acos(tmp.z());
   if (angle > 1e-3) glRotatef(angle, ax.x(), ax.y(), ax.z());
   gluCylinder(cylinder, length / aspect, length / aspect, 0.8 * length, 10, 10);
   glTranslatef(0.0, 0.0, 0.8 * length);
   glScalef(4.0 * length / aspect, 4.0 * length / aspect, 4.0 * length / aspect);
   drawUnitCube();
   popMatrix(GL_MODELVIEW);
 }
References acos(), Jeffery_Solution::angle(), plotDoE::ax, drawUnitCube(), e(), M_PI, popMatrix(), pushMatrix(), and tmp.
forceMatrixTarget()
void GpuHelper::forceMatrixTarget (GLenum matrixTarget) inline
Make the matrix matrixTarget the current OpenGL matrix target. Call this function before loadMatrix() or multMatrix() if you cannot guarantee that glMatrixMode() has never been called after the last loadMatrix() or multMatrix() calls.
Todo:
provides a debug mode checking the sanity of the cached matrix mode.
 { glMatrixMode(mCurrentMatrixTarget = matrixTarget); }
loadMatrix() [1/2]
template<typename Scalar , typename Derived > void GpuHelper::loadMatrix (const Eigen::CwiseNullaryOp< Eigen::internal::scalar_identity_op< Scalar >, Derived > & , GLenum matrixTarget)
{
   setMatrixTarget(matrixTarget);
   glLoadIdentity();
 }
loadMatrix() [2/2]
template<typename Scalar , int Flags_> void GpuHelper::loadMatrix (const Eigen::Matrix< Scalar, 4, 4, Flags_, 4, 4 > & mat, GLenum matrixTarget)
Load the matrix mat to the OpenGL matrix matrixTarget. Essentially, this helper function automatically calls glMatrixMode(matrixTarget) if required and does a proper call to the right glLoadMatrix*() or glLoadIdentity() function according to the scalar type and storage order.
Warning
glMatrixMode() must never be called directly. If you are unsure, use forceMatrixMode().
See also
Matrix, multMatrix(), forceMatrixMode()
{
   setMatrixTarget(matrixTarget);
   GlMatrixHelper<(Flags_ & Eigen::RowMajorBit) != 0, Flags_>::loadMatrix(mat);
 }
References Eigen::RowMajorBit.
Referenced by Camera::activateGL().
multMatrix()
template<typename Scalar , int Flags_> void GpuHelper::multMatrix (const Matrix< Scalar, 4, 4, Flags_, 4, 4 > & mat, GLenum matrixTarget)
Multiply the OpenGL matrix matrixTarget by the matrix mat. Essentially, this helper function automatically calls glMatrixMode(matrixTarget) if required and does a proper call to the right glMultMatrix*() function according to the scalar type and storage order.
Warning
glMatrixMode() must never be called directly. If you are unsure, use forceMatrixMode().
See also
Matrix, loadMatrix(), forceMatrixMode()
{
   setMatrixTarget(matrixTarget);
   GlMatrixHelper<Flags_ & Eigen::RowMajorBit, Flags_>::multMatrix(mat);
 }
Referenced by FancySpheres::draw().
popMatrix()
void GpuHelper::popMatrix (GLenum matrixTarget) inline
Pop the OpenGL matrix matrixTarget
{
   setMatrixTarget(matrixTarget);
   glPopMatrix();
 }
Referenced by FancySpheres::draw(), drawVector(), drawVectorBox(), and popProjectionMode2D().
popProjectionMode2D()
void GpuHelper::popProjectionMode2D (void)
{
   popMatrix(GL_PROJECTION);
   popMatrix(GL_MODELVIEW);
 }
References popMatrix().
pushMatrix() [1/3]
template<typename Scalar , typename Derived > void GpuHelper::pushMatrix (const Eigen::CwiseNullaryOp< Eigen::internal::scalar_identity_op< Scalar >, Derived > & , GLenum matrixTarget)
{
   pushMatrix(matrixTarget);
   glLoadIdentity();
 }
pushMatrix() [2/3]
template<typename Scalar , int Flags_> void GpuHelper::pushMatrix (const Matrix< Scalar, 4, 4, Flags_, 4, 4 > & mat, GLenum matrixTarget) inline
Push the OpenGL matrix matrixTarget and load mat.
{
   pushMatrix(matrixTarget);
   GlMatrixHelper<Flags_ & Eigen::RowMajorBit, Flags_>::loadMatrix(mat);
 }
Referenced by FancySpheres::draw(), drawVector(), drawVectorBox(), and pushProjectionMode2D().
pushMatrix() [3/3]
void GpuHelper::pushMatrix (GLenum matrixTarget) inline
Push and clone the OpenGL matrix matrixTarget
{
   setMatrixTarget(matrixTarget);
   glPushMatrix();
 }
pushProjectionMode2D()
void GpuHelper::pushProjectionMode2D (ProjectionMode2D pm)
{
   // switch to 2D projection
   pushMatrix(Matrix4f::Identity(), GL_PROJECTION);
   if (pm == PM_Normalized) {
     // glOrtho(-1., 1., -1., 1., 0., 1.);
   } else if (pm == PM_Viewport) {
     GLint vp[4];
     glGetIntegerv(GL_VIEWPORT, vp);
     glOrtho(0., vp[2], 0., vp[3], -1., 1.);
   }
   pushMatrix(Matrix4f::Identity(), GL_MODELVIEW);
 }
References pm, PM_Normalized, PM_Viewport, and pushMatrix().
setMatrixTarget()
void GpuHelper::setMatrixTarget (GLenum matrixTarget) inline
{
   if (matrixTarget != mCurrentMatrixTarget) glMatrixMode(mCurrentMatrixTarget = matrixTarget);
 }
update()
void GpuHelper::update (void) protected
Referenced by smc.smc::recursiveBayesian().
Member Data Documentation
mColorBufferId
GLuint GpuHelper::mColorBufferId protected
mCurrentMatrixTarget
GLenum GpuHelper::mCurrentMatrixTarget protected
Referenced by GpuHelper().
mInitialized
bool GpuHelper::mInitialized protected
Referenced by GpuHelper().
mVpHeight
int GpuHelper::mVpHeight protected
Referenced by GpuHelper().
mVpWidth
int GpuHelper::mVpWidth protected
Referenced by GpuHelper().
The documentation for this class was generated from the following files:
gpuhelper.h
gpuhelper.cpp