MercuryDPM: Eigen::SparseMapBase< Derived, WriteAccessors > Class Template Reference
Eigen::SparseMapBase< Derived, WriteAccessors > Class Template Reference
Sparse linear algebra » Reference » SparseCore_Module
Common base class for writable Map and Ref instance of sparse matrix and vector.
#include <SparseMap.h>
Public Types
enum { IsRowMajor = Base::IsRowMajor }
typedef SparseMapBase< Derived, ReadOnlyAccessors > Base
typedef Base::Scalar Scalar
typedef Base::StorageIndex StorageIndex
Public Types inherited from Eigen::SparseMapBase< Derived, ReadOnlyAccessors >
enum { IsRowMajor = Base::IsRowMajor }
typedef SparseCompressedBase< Derived > Base
typedef Base::Scalar Scalar
typedef Base::StorageIndex StorageIndex
Public Types inherited from Eigen::SparseCompressedBase< Derived >
typedef SparseMatrixBase< Derived > Base
Public Types inherited from Eigen::SparseMatrixBase< Derived >
enum {
RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime , ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime , SizeAtCompileTime = (internal::size_of_xpr_at_compile_time<Derived>::ret) , MaxRowsAtCompileTime = RowsAtCompileTime ,
MaxColsAtCompileTime = ColsAtCompileTime , MaxSizeAtCompileTime = internal::size_at_compile_time(MaxRowsAtCompileTime, MaxColsAtCompileTime) , IsVectorAtCompileTime = RowsAtCompileTime == 1 || ColsAtCompileTime == 1 , NumDimensions ,
Flags = internal::traits<Derived>::Flags , IsRowMajor = Flags & RowMajorBit ? 1 : 0 , InnerSizeAtCompileTime , HasDirectAccess_ = (int(Flags) & DirectAccessBit) ? 1 : 0
}
typedef internal::traits< Derived >::Scalar Scalar
typedef Scalar value_type
typedef internal::packet_traits< Scalar >::type PacketScalar
typedef internal::traits< Derived >::StorageKind StorageKind
typedef internal::traits< Derived >::StorageIndex StorageIndex
typedef internal::add_const_on_value_type_if_arithmetic< typename internal::packet_traits< Scalar >::type >::type PacketReturnType
typedef SparseMatrixBase StorageBaseType
typedef Matrix< StorageIndex, Dynamic, 1 > IndexVector
typedef Matrix< Scalar, Dynamic, 1 > ScalarVector
typedef std::conditional_t< NumTraits< Scalar >::IsComplex, CwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, Eigen::Transpose< const Derived > >, Transpose< const Derived > > AdjointReturnType
typedef Transpose< Derived > TransposeReturnType
typedef Transpose< const Derived > ConstTransposeReturnType
typedef SparseMatrix< Scalar, Flags &RowMajorBit ? RowMajor :ColMajor, StorageIndex > PlainObject
typedef NumTraits< Scalar >::Real RealScalar
typedef std::conditional_t< HasDirectAccess_, const Scalar &, Scalar > CoeffReturnType
typedef CwiseNullaryOp< internal::scalar_constant_op< Scalar >, Matrix< Scalar, Dynamic, Dynamic > > ConstantReturnType
typedef Matrix< Scalar, RowsAtCompileTime, ColsAtCompileTime > DenseMatrixType
typedef Matrix< Scalar, internal::max_size_prefer_dynamic(RowsAtCompileTime, ColsAtCompileTime), internal::max_size_prefer_dynamic(RowsAtCompileTime, ColsAtCompileTime)> SquareMatrixType
typedef EigenBase< Derived > Base
Public Types inherited from Eigen::EigenBase< Derived >
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< Derived >::StorageKind StorageKind
Public Member Functions
Scalar * valuePtr ()
StorageIndex * innerIndexPtr ()
StorageIndex * outerIndexPtr ()
StorageIndex * innerNonZeroPtr ()
Scalar & coeffRef (Index row, Index col)
SparseMapBase (Index rows, Index cols, Index nnz, StorageIndex *outerIndexPtr, StorageIndex *innerIndexPtr, Scalar *valuePtr, StorageIndex *innerNonZerosPtr=0)
SparseMapBase (Index size, Index nnz, StorageIndex *innerIndexPtr, Scalar *valuePtr)
~SparseMapBase ()
template<typename OtherDerived >
Derived & operator= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator= (const ReturnByValue< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator= (const SparseMatrixBase< OtherDerived > &other)
Derived & operator= (const Derived &other)
Public Member Functions inherited from Eigen::SparseMapBase< Derived, ReadOnlyAccessors >
Index rows () const
Index cols () const
Index innerSize () const
Index outerSize () const
Index nonZeros () const
bool isCompressed () const
const Scalar * valuePtr () const
const StorageIndex * innerIndexPtr () const
const StorageIndex * outerIndexPtr () const
const StorageIndex * innerNonZeroPtr () const
Scalar coeff (Index row, Index col) const
SparseMapBase (Index rows, Index cols, Index nnz, IndexPointer outerIndexPtr, IndexPointer innerIndexPtr, ScalarPointer valuePtr, IndexPointer innerNonZerosPtr=0)
SparseMapBase (Index size, Index nnz, IndexPointer innerIndexPtr, ScalarPointer valuePtr)
~SparseMapBase ()
template<typename OtherDerived >
Derived & operator= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator= (const ReturnByValue< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator= (const SparseMatrixBase< OtherDerived > &other)
Derived & operator= (const Derived &other)
Public Member Functions inherited from Eigen::SparseCompressedBase< Derived >
Index nonZeros () const
const Scalar * valuePtr () const
Scalar * valuePtr ()
const StorageIndex * innerIndexPtr () const
StorageIndex * innerIndexPtr ()
const StorageIndex * outerIndexPtr () const
StorageIndex * outerIndexPtr ()
const StorageIndex * innerNonZeroPtr () const
StorageIndex * innerNonZeroPtr ()
bool isCompressed () const
const Map< const Array< Scalar, Dynamic, 1 > > coeffs () const
Map< Array< Scalar, Dynamic, 1 > > coeffs ()
template<class Comp = std::less<>>
void sortInnerIndices (Index begin, Index end)
template<class Comp = std::less<>>
Index innerIndicesAreSorted (Index begin, Index end) const
template<class Comp = std::less<>>
void sortInnerIndices ()
template<class Comp = std::less<>>
Index innerIndicesAreSorted () const
template<typename OtherDerived >
Derived & operator= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator= (const ReturnByValue< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator= (const SparseMatrixBase< OtherDerived > &other)
Derived & operator= (const Derived &other)
Public Member Functions inherited from Eigen::SparseMatrixBase< Derived >
template<typename OtherDerived >
Derived & operator= (const EigenBase< OtherDerived > &other)
const Derived & derived () const
Derived & derived ()
Derived & const_cast_derived () const
Index rows () const
Index cols () const
Index size () const
bool isVector () const
Index outerSize () const
Index innerSize () const
bool isRValue () const
Derived & markAsRValue ()
SparseMatrixBase ()
template<typename OtherDerived >
Derived & operator= (const ReturnByValue< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator= (const SparseMatrixBase< OtherDerived > &other)
Derived & operator= (const Derived &other)
template<typename OtherDerived >
Derived & operator+= (const SparseMatrixBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator-= (const SparseMatrixBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator+= (const DiagonalBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator-= (const DiagonalBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator+= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator-= (const EigenBase< OtherDerived > &other)
Derived & operator*= (const Scalar &other)
Derived & operator/= (const Scalar &other)
template<typename OtherDerived >
EIGEN_STRONG_INLINE const CwiseProductDenseReturnType< OtherDerived >::Type cwiseProduct (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
const Product< Derived, OtherDerived > operator* (const DiagonalBase< OtherDerived > &other) const
template<typename OtherDerived >
const Product< Derived, OtherDerived, AliasFreeProduct > operator* (const SparseMatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
const Product< Derived, OtherDerived > operator* (const MatrixBase< OtherDerived > &other) const
SparseSymmetricPermutationProduct< Derived, Upper|Lower > twistedBy (const PermutationMatrix< Dynamic, Dynamic, StorageIndex > &perm) const
template<typename OtherDerived >
Derived & operator*= (const SparseMatrixBase< OtherDerived > &other)
template<int Mode>
const TriangularView< const Derived, Mode > triangularView () const
template<unsigned int UpLo>
ConstSelfAdjointViewReturnType< UpLo >::Type selfadjointView () const
template<unsigned int UpLo>
SelfAdjointViewReturnType< UpLo >::Type selfadjointView ()
template<typename OtherDerived >
Scalar dot (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
Scalar dot (const SparseMatrixBase< OtherDerived > &other) const
RealScalar squaredNorm () const
RealScalar norm () const
RealScalar blueNorm () const
TransposeReturnType transpose ()
const ConstTransposeReturnType transpose () const
const AdjointReturnType adjoint () const
DenseMatrixType toDense () const
template<typename OtherDerived >
bool isApprox (const SparseMatrixBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
template<typename OtherDerived >
bool isApprox (const MatrixBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
const internal::eval< Derived >::type eval () const
Scalar sum () const
const SparseView< Derived > pruned (const Scalar &reference=Scalar(0), const RealScalar &epsilon=NumTraits< Scalar >::dummy_precision()) const
template<typename OtherDerived >
EIGEN_STRONG_INLINE Derived & operator-= (const SparseMatrixBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_STRONG_INLINE Derived & operator+= (const SparseMatrixBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_STRONG_INLINE const SparseMatrixBase< Derived >::template CwiseProductDenseReturnType< OtherDerived >::Type cwiseProduct (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
internal::traits< Derived >::Scalar dot (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
internal::traits< Derived >::Scalar dot (const SparseMatrixBase< OtherDerived > &other) const
template<unsigned int UpLo>
SparseMatrixBase< Derived >::template ConstSelfAdjointViewReturnType< UpLo >::Type selfadjointView () const
template<unsigned int UpLo>
SparseMatrixBase< Derived >::template SelfAdjointViewReturnType< UpLo >::Type selfadjointView ()
Public Member Functions inherited from Eigen::EigenBase< Derived >
constexpr EIGEN_DEVICE_FUNC Derived & derived ()
constexpr EIGEN_DEVICE_FUNC const Derived & derived () const
EIGEN_DEVICE_FUNC Derived & const_cast_derived () const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index size () const EIGEN_NOEXCEPT
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
template<typename Device >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< Derived, Device > device (Device &device)
template<typename Device >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< const Derived, Device > device (Device &device) const
Protected Member Functions
SparseMapBase ()
Protected Member Functions inherited from Eigen::SparseMapBase< Derived, ReadOnlyAccessors >
SparseMapBase ()
Protected Member Functions inherited from Eigen::SparseCompressedBase< Derived >
Eigen::Map< IndexVector > innerNonZeros ()
const Eigen::Map< const IndexVector > innerNonZeros () const
SparseCompressedBase ()
internal::LowerBoundIndex lower_bound (Index row, Index col) const
Protected Member Functions inherited from Eigen::SparseMatrixBase< Derived >
template<typename OtherDerived >
Derived & assign (const OtherDerived &other)
template<typename OtherDerived >
void assignGeneric (const OtherDerived &other)
Private Types
typedef MapBase< Derived, ReadOnlyAccessors > ReadOnlyMapBase
Additional Inherited Members
Protected Types inherited from Eigen::SparseMapBase< Derived, ReadOnlyAccessors >
typedef std::conditional_t< bool(internal::is_lvalue< Derived >::value), Scalar *, const Scalar * > ScalarPointer
typedef std::conditional_t< bool(internal::is_lvalue< Derived >::value), StorageIndex *, const StorageIndex * > IndexPointer
Protected Types inherited from Eigen::SparseCompressedBase< Derived >
typedef Base::IndexVector IndexVector
Static Protected Member Functions inherited from Eigen::SparseMatrixBase< Derived >
static StorageIndex convert_index (const Index idx)
Protected Attributes inherited from Eigen::SparseMapBase< Derived, ReadOnlyAccessors >
Index m_outerSize
Index m_innerSize
Array< StorageIndex, 2, 1 > m_zero_nnz
IndexPointer m_outerIndex
IndexPointer m_innerIndices
ScalarPointer m_values
IndexPointer m_innerNonZeros
Protected Attributes inherited from Eigen::SparseMatrixBase< Derived >
bool m_isRValue
Detailed Description
template<typename Derived>
class Eigen::SparseMapBase< Derived, WriteAccessors >
Common base class for writable Map and Ref instance of sparse matrix and vector.
class SparseMapBase
Member Typedef Documentation
Base
template<typename Derived > typedef SparseMapBase<Derived, ReadOnlyAccessors> Eigen::SparseMapBase< Derived, WriteAccessors >::Base
ReadOnlyMapBase
template<typename Derived > typedef MapBase<Derived, ReadOnlyAccessors> Eigen::SparseMapBase< Derived, WriteAccessors >::ReadOnlyMapBase private
Scalar
template<typename Derived > typedef Base::Scalar Eigen::SparseMapBase< Derived, WriteAccessors >::Scalar
StorageIndex
template<typename Derived > typedef Base::StorageIndex Eigen::SparseMapBase< Derived, WriteAccessors >::StorageIndex
Member Enumeration Documentation
anonymous enum
template<typename Derived > anonymous enum
Enumerator
IsRowMajor
 { IsRowMajor = Base::IsRowMajor };
Constructor & Destructor Documentation
SparseMapBase() [1/3]
template<typename Derived > Eigen::SparseMapBase< Derived, WriteAccessors >::SparseMapBase (Index rows, Index cols, Index nnz, StorageIndex * outerIndexPtr, StorageIndex * innerIndexPtr, Scalar * valuePtr, StorageIndex * innerNonZerosPtr = 0) inline
       : Base(rows, cols, nnz, outerIndexPtr, innerIndexPtr, valuePtr, innerNonZerosPtr) {}
SparseMapBase() [2/3]
template<typename Derived > Eigen::SparseMapBase< Derived, WriteAccessors >::SparseMapBase (Index size, Index nnz, StorageIndex * innerIndexPtr, Scalar * valuePtr) inline
       : Base(size, nnz, innerIndexPtr, valuePtr) {}
~SparseMapBase()
template<typename Derived > Eigen::SparseMapBase< Derived, WriteAccessors >::~SparseMapBase () inline
Empty destructor
 {}
SparseMapBase() [3/3]
template<typename Derived > Eigen::SparseMapBase< Derived, WriteAccessors >::SparseMapBase () inline protected
 {}
Member Function Documentation
coeffRef()
template<typename Derived > Scalar& Eigen::SparseMapBase< Derived, WriteAccessors >::coeffRef (Index row, Index col) inline
Returns
a non-const reference to the value of the matrix at position i, j
If the element does not exist then it is inserted via the insert(Index,Index) function which itself turns the matrix into a non compressed form if that was not the case.
This is a O(log(nnz_j)) operation (binary search) plus the cost of insert(Index,Index) function if the element does not already exist.
{
     const Index outer = IsRowMajor ? row : col;
     const Index inner = IsRowMajor ? col : row;
     Index start = Base::m_outerIndex[outer];
     Index end = Base::isCompressed() ? Base::m_outerIndex[outer + 1] : start + Base::m_innerNonZeros[outer];
     eigen_assert(end >= start && "you probably called coeffRef on a non finalized matrix");
     eigen_assert(end > start && "coeffRef cannot be called on a zero coefficient");
     StorageIndex* r = std::lower_bound(&Base::m_innerIndices[start], &Base::m_innerIndices[end], inner);
     const Index id = r - &Base::m_innerIndices[0];
     eigen_assert((*r == inner) && (id < end) && "coeffRef cannot be called on a zero coefficient");
     return const_cast<Scalar*>(Base::m_values)[id];
   }
References col(), eigen_assert, Eigen::placeholders::end, UniformPSDSelfTest::r, row(), and oomph::CumulativeTimings::start().
innerIndexPtr()
template<typename Derived > StorageIndex* Eigen::SparseMapBase< Derived, WriteAccessors >::innerIndexPtr () inline
Returns
a const pointer to the array of inner indices. This function is aimed at interoperability with other libraries.
See also
valuePtr(), outerIndexPtr()
 { return Base::m_innerIndices; }
innerNonZeroPtr()
template<typename Derived > StorageIndex* Eigen::SparseMapBase< Derived, WriteAccessors >::innerNonZeroPtr () inline
Returns
a const pointer to the array of the number of non zeros of the inner vectors. This function is aimed at interoperability with other libraries.
Warning
it returns the null pointer 0 in compressed mode
 { return Base::m_innerNonZeros; }
operator=() [1/4]
template<typename Derived > Derived & Eigen::SparseMatrixBase< Derived >::operator= inline
{
   internal::call_assignment_no_alias(derived(), other.derived());
   return derived();
 }
operator=() [2/4]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator= (typename OtherDerived)
{
   internal::call_assignment_no_alias(derived(), other.derived());
   return derived();
 }
operator=() [3/4]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator= (typename OtherDerived)
{
   // TODO use the evaluator mechanism
   other.evalTo(derived());
   return derived();
 }
operator=() [4/4]
template<typename Derived > template<typename OtherDerived > Derived & Eigen::SparseMatrixBase< Derived >::operator= (typename OtherDerived) inline
{
   // by default sparse evaluation do not alias, so we can safely bypass the generic call_assignment routine
   internal::Assignment<Derived, OtherDerived, internal::assign_op<Scalar, typename OtherDerived::Scalar>>::run(
       derived(), other.derived(), internal::assign_op<Scalar, typename OtherDerived::Scalar>());
   return derived();
 }
outerIndexPtr()
template<typename Derived > StorageIndex* Eigen::SparseMapBase< Derived, WriteAccessors >::outerIndexPtr () inline
Returns
a const pointer to the array of the starting positions of the inner vectors. This function is aimed at interoperability with other libraries.
See also
valuePtr(), innerIndexPtr()
 { return Base::m_outerIndex; }
valuePtr()
template<typename Derived > Scalar* Eigen::SparseMapBase< Derived, WriteAccessors >::valuePtr () inline
Returns
a const pointer to the array of values. This function is aimed at interoperability with other libraries.
See also
innerIndexPtr(), outerIndexPtr()
 { return Base::m_values; }
The documentation for this class was generated from the following file:
SparseMap.h