MercuryDPM: oomph::AxisymmetricNavierStokesEquations Class Reference
oomph::AxisymmetricNavierStokesEquations Class Reference abstract
#include <axisym_navier_stokes_elements.h>
Public Member Functions
AxisymmetricNavierStokesEquations ()
Constructor: NULL the body force and source function.
const double & re () const
Reynolds number.
const double & re_st () const
Product of Reynolds and Strouhal number (=Womersley number)
double *& re_pt ()
Pointer to Reynolds number.
double *& re_st_pt ()
Pointer to product of Reynolds and Strouhal number (=Womersley number)
const double & re_invfr () const
Global inverse Froude number.
double *& re_invfr_pt ()
Pointer to global inverse Froude number.
const double & re_invro () const
Global Reynolds number multiplied by inverse Rossby number.
double *& re_invro_pt ()
Pointer to global inverse Froude number.
const Vector< double > & g () const
Vector of gravitational components.
Vector< double > *& g_pt ()
Pointer to Vector of gravitational components.
const double & density_ratio () const
double *& density_ratio_pt ()
Pointer to Density ratio.
const double & viscosity_ratio () const
double *& viscosity_ratio_pt ()
Pointer to Viscosity Ratio.
virtual unsigned npres_axi_nst () const =0
Function to return number of pressure degrees of freedom.
virtual unsigned u_index_axi_nst (const unsigned &i) const
unsigned u_index_nst (const unsigned &i) const
unsigned n_u_nst () const
double du_dt_axi_nst (const unsigned &n, const unsigned &i) const
void disable_ALE ()
void enable_ALE ()
virtual double p_axi_nst (const unsigned &n_p) const =0
virtual int p_nodal_index_axi_nst () const
Which nodal value represents the pressure?
double pressure_integral () const
Integral of pressure over element.
double dissipation () const
Return integral of dissipation over element.
double dissipation (const Vector< double > &s) const
Return dissipation at local coordinate s.
double kin_energy () const
Get integral of kinetic energy over element.
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
Strain-rate tensor: \(e_{ij} \) where \(i,j = r,z,\theta \) (in that order)
void traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction) const
void get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > &press_mass_diag, Vector< double > &veloc_mass_diag, const unsigned &which_one=0)
unsigned nscalar_paraview () const
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
std::string scalar_name_paraview (const unsigned &i) const
void point_output_data (const Vector< double > &s, Vector< double > &data)
void output (std::ostream &outfile)
void output (std::ostream &outfile, const unsigned &nplot)
void output (FILE *file_pt)
void output (FILE *file_pt, const unsigned &nplot)
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element's residual Vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
Compute the element's residual Vector.
void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
void interpolated_u_axi_nst (const Vector< double > &s, Vector< double > &veloc) const
Compute vector of FE interpolated velocity u at local coordinate s.
double interpolated_u_axi_nst (const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s.
double interpolated_u_axi_nst (const unsigned &t, const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s.
virtual void dinterpolated_u_axi_nst_ddata (const Vector< double > &s, const unsigned &i, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
double interpolated_p_axi_nst (const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s.
double interpolated_duds_axi_nst (const Vector< double > &s, const unsigned &i, const unsigned &j) const
double interpolated_dudx_axi_nst (const Vector< double > &s, const unsigned &i, const unsigned &j) const
double interpolated_dudt_axi_nst (const Vector< double > &s, const unsigned &i) const
double interpolated_d_dudx_dX_axi_nst (const Vector< double > &s, const unsigned &p, const unsigned &q, const unsigned &i, const unsigned &k) const
double compute_physical_size () const
Compute the volume of the element.
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual unsigned nvertex_node () const
virtual Node * vertex_node_pt (const unsigned &j) const
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::NavierStokesElementWithDiagonalMassMatrices
NavierStokesElementWithDiagonalMassMatrices ()
Empty constructor.
virtual ~NavierStokesElementWithDiagonalMassMatrices ()
Virtual destructor.
NavierStokesElementWithDiagonalMassMatrices (const NavierStokesElementWithDiagonalMassMatrices &)=delete
Broken copy constructor.
void operator= (const NavierStokesElementWithDiagonalMassMatrices &)=delete
Broken assignment operator.
Public Attributes
void(*&)(const double &time, const Vector< double > &x, Vector< double > &f) axi_nst_body_force_fct_pt ()
Access function for the body-force pointer.
double(*&)(const double &time, const Vector< double > &x) source_fct_pt ()
Access function for the source-function pointer.
Static Public Attributes
static Vector< double > Gamma
Vector to decide whether the stress-divergence form is used or not.
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Protected Member Functions
virtual int p_local_eqn (const unsigned &n) const =0
virtual double dshape_and_dtest_eulerian_axi_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
virtual double dshape_and_dtest_eulerian_at_knot_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
virtual double dshape_and_dtest_eulerian_at_knot_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const =0
virtual void pshape_axi_nst (const Vector< double > &s, Shape &psi) const =0
Compute the pressure shape functions at local coordinate s.
virtual void pshape_axi_nst (const Vector< double > &s, Shape &psi, Shape &test) const =0
virtual void get_body_force_axi_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &result)
Calculate the body force fct at a given time and Eulerian position.
virtual void get_body_force_gradient_axi_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, DenseMatrix< double > &d_body_force_dx)
double get_source_fct (const double &time, const unsigned &ipt, const Vector< double > &x)
Calculate the source fct at given time and Eulerian position.
virtual void get_source_fct_gradient (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &gradient)
virtual void get_viscosity_ratio_axisym_nst (const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, double &visc_ratio)
virtual void fill_in_generic_residual_contribution_axi_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
virtual void fill_in_generic_dresidual_contribution_axi_nst (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam, unsigned flag)
void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Attributes
double * Viscosity_Ratio_pt
double * Density_Ratio_pt
double * Re_pt
Pointer to global Reynolds number.
double * ReSt_pt
Pointer to global Reynolds number x Strouhal number (=Womersley)
double * ReInvFr_pt
double * ReInvRo_pt
Vector< double > * G_pt
Pointer to global gravity Vector.
void(* Body_force_fct_pt)(const double &time, const Vector< double > &x, Vector< double > &result)
Pointer to body force function.
double(* Source_fct_pt)(const double &time, const Vector< double > &x)
Pointer to volumetric source function.
bool ALE_is_disabled
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Static Private Attributes
static int Pressure_not_stored_at_node = -100
static double Default_Physical_Constant_Value
Navier–Stokes equations static data.
static double Default_Physical_Ratio_Value = 1.0
static Vector< double > Default_Gravity_vector
Static default value for the gravity vector.
Additional Inherited Members
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
A class for elements that solve the unsteady axisymmetric Navier–Stokes equations in cylindrical polar coordinates, \(x_0^* = r^*\) and \(x_1^* = z^* \) with \(\partial / \partial \theta = 0 \). We're solving for the radial, axial and azimuthal (swirl) velocities, \(u_0^* = u_r^*(r^*,z^*,t^*) = u^*(r^*,z^*,t^*), \ u_1^* = u_z^*(r^*,z^*,t^*) = w^*(r^*,z^*,t^*)\) and \(u_2^* = u_\theta^*(r^*,z^*,t^*) = v^*(r^*,z^*,t^*) \), respectively, and the pressure \(p(r^*,z^*,t^*) \). This class contains the generic maths – any concrete implementation must be derived from this.
In dimensional form the axisymmetric Navier-Stokes equations are given by the momentum equations (for the \(r^* \), \(z^* \) and \(\theta \) directions, respectively)
\[ \rho\left(\frac{\partial u^*}{\partial t^*} + {u^*}\frac{\partial u^*}{\partial r^*} - \frac{{v^*}^2}{r^*} + {w^*}\frac{\partial u^*}{\partial z^*} \right) = B_r^*\left(r^*,z^*,t^*\right)+ \rho G_r^*+ \frac{1}{r^*} \frac{\partial\left({r^*}\sigma_{rr}^*\right)}{\partial r^*} - \frac{\sigma_{\theta\theta}^*}{r^*} + \frac{\partial\sigma_{rz}^*}{\partial z^*}, \]
\[ \rho\left(\frac{\partial w^*}{\partial t^*} + {u^*}\frac{\partial w^*}{\partial r^*} + {w^*}\frac{\partial w^*}{\partial z^*} \right) = B_z^*\left(r^*,z^*,t^*\right)+\rho G_z^*+ \frac{1}{r^*}\frac{\partial\left({r^*}\sigma_{zr}^*\right)}{\partial r^*} + \frac{\partial\sigma_{zz}^*}{\partial z^*}, \]
\[ \rho\left(\frac{\partial v^*}{\partial t^*} + {u^*}\frac{\partial v^*}{\partial r^*} + \frac{u^* v^*}{r^*} +{w^*}\frac{\partial v^*}{\partial z^*} \right)= B_\theta^*\left(r^*,z^*,t^*\right)+ \rho G_\theta^*+ \frac{1}{r^*}\frac{\partial\left({r^*}\sigma_{\theta r}^*\right)}{\partial r^*} + \frac{\sigma_{r\theta}^*}{r^*} + \frac{\partial\sigma_{\theta z}^*}{\partial z^*}, \]
and
\[ \frac{1}{r^*}\frac{\partial\left(r^*u^*\right)}{\partial r^*} + \frac{\partial w^*}{\partial z^*} = Q^*. \]
The dimensional, symmetric stress tensor is defined as:
\[ \sigma_{rr}^* = -p^* + 2\mu\frac{\partial u^*}{\partial r^*}, \qquad \sigma_{\theta\theta}^* = -p^* +2\mu\frac{u^*}{r^*}, \]
\[ \sigma_{zz}^* = -p^* + 2\mu\frac{\partial w^*}{\partial z^*}, \qquad \sigma_{rz}^* = \mu\left(\frac{\partial u^*}{\partial z^*} + \frac{\partial w^*}{\partial r^*}\right), \]
\[ \sigma_{\theta r}^* = \mu r^*\frac{\partial}{\partial r^*} \left(\frac{v^*}{r^*}\right), \qquad \sigma_{\theta z}^* = \mu\frac{\partial v^*}{\partial z^*}. \]
Here, the (dimensional) velocity components are denoted by \(u^* \), \(w^* \) and \(v^* \) for the radial, axial and azimuthal velocities, respectively, and we have split the body force into two components: A constant vector \(\rho \ G_i^* \) which typically represents gravitational forces; and a variable body force, \(B_i^*(r^*,z^*,t^*) \). \(Q^*(r^*,z^*,t^*) \) is a volumetric source term for the continuity equation and is typically equal to zero.
We non-dimensionalise the equations, using problem-specific reference quantities for the velocity, \(U \), length, \(L \), and time, \(T \), and scale the constant body force vector on the gravitational acceleration, \(g \), so that
\[ u^* = U\, u, \qquad w^* = U\, w, \qquad v^* = U\, v, \]
\[ r^* = L\, r, \qquad z^* = L\, z, \qquad t^* = T\, t, \]
\[ G_i^* = g\, G_i, \qquad B_i^* = \frac{U\mu_{ref}}{L^2}\, B_i, \qquad p^* = \frac{\mu_{ref} U}{L}\, p, \qquad Q^* = \frac{U}{L}\, Q. \]
where we note that the pressure and the variable body force have been non-dimensionalised on the viscous scale. \(\mu_{ref} \) and \(\rho_{ref} \) (used below) are reference values for the fluid viscosity and density, respectively. In single-fluid problems, they are identical to the viscosity \(\mu \) and density \(\rho \) of the (one and only) fluid in the problem.
The non-dimensional form of the axisymmetric Navier-Stokes equations is then given by
\[ R_{\rho} Re\left(St\frac{\partial u}{\partial t} + {u}\frac{\partial u}{\partial r} - \frac{{v}^2}{r} + {w}\frac{\partial u}{\partial z} \right) = B_r\left(r,z,t\right)+ R_\rho \frac{Re}{Fr} G_r + \frac{1}{r} \frac{\partial\left({r}\sigma_{rr}\right)}{\partial r} - \frac{\sigma_{\theta\theta}}{r} + \frac{\partial\sigma_{rz}}{\partial z}, \]
\[ R_{\rho} Re\left(St\frac{\partial w}{\partial t} + {u}\frac{\partial w}{\partial r} + {w}\frac{\partial w}{\partial z} \right) = B_z\left(r,z,t\right)+ R_\rho \frac{Re}{Fr} G_z+ \frac{1}{r}\frac{\partial\left({r}\sigma_{zr}\right)}{\partial r} + \frac{\partial\sigma_{zz}}{\partial z}, \]
\[ R_{\rho} Re\left(St\frac{\partial v}{\partial t} + {u}\frac{\partial v}{\partial r} + \frac{u v}{r} +{w}\frac{\partial v}{\partial z} \right)= B_\theta\left(r,z,t\right)+ R_\rho \frac{Re}{Fr} G_\theta+ \frac{1}{r}\frac{\partial\left({r}\sigma_{\theta r}\right)}{\partial r} + \frac{\sigma_{r\theta}}{r} + \frac{\partial\sigma_{\theta z}}{\partial z}, \]
and
\[ \frac{1}{r}\frac{\partial\left(ru\right)}{\partial r} + \frac{\partial w}{\partial z} = Q. \]
Here the non-dimensional, symmetric stress tensor is defined as:
\[ \sigma_{rr} = -p + 2R_\mu \frac{\partial u}{\partial r}, \qquad \sigma_{\theta\theta} = -p +2R_\mu \frac{u}{r}, \]
\[ \sigma_{zz} = -p + 2R_\mu \frac{\partial w}{\partial z}, \qquad \sigma_{rz} = R_\mu \left(\frac{\partial u}{\partial z} + \frac{\partial w}{\partial r}\right), \]
\[ \sigma_{\theta r} = R_\mu r \frac{\partial}{\partial r}\left(\frac{v}{r}\right), \qquad \sigma_{\theta z} = R_\mu \frac{\partial v}{\partial z}. \]
and the dimensionless parameters
\[ Re = \frac{UL\rho_{ref}}{\mu_{ref}}, \qquad St = \frac{L}{UT}, \qquad Fr = \frac{U^2}{gL}, \]
are the Reynolds number, Strouhal number and Froude number respectively. \(R_\rho=\rho/\rho_{ref} \) and \(R_\mu(T) =\mu(T)/\mu_{ref}\) represent the ratios of the fluid's density and its dynamic viscosity, relative to the density and viscosity values used to form the non-dimensional parameters (By default, \(R_\rho = R_\mu = 1 \); other values tend to be used in problems involving multiple fluids).
Constructor & Destructor Documentation
AxisymmetricNavierStokesEquations()
oomph::AxisymmetricNavierStokesEquations::AxisymmetricNavierStokesEquations () inline
Constructor: NULL the body force and source function.
       : Body_force_fct_pt(0), Source_fct_pt(0), ALE_is_disabled(false)
     {
       // Set all the Physical parameter pointers to the default value zero
       Re_pt = &Default_Physical_Constant_Value;
       ReSt_pt = &Default_Physical_Constant_Value;
       ReInvFr_pt = &Default_Physical_Constant_Value;
       ReInvRo_pt = &Default_Physical_Constant_Value;
       G_pt = &Default_Gravity_vector;
       // Set the Physical ratios to the default value of 1
       Viscosity_Ratio_pt = &Default_Physical_Ratio_Value;
       Density_Ratio_pt = &Default_Physical_Ratio_Value;
     }
References Default_Gravity_vector, Default_Physical_Constant_Value, Default_Physical_Ratio_Value, Density_Ratio_pt, G_pt, Re_pt, ReInvFr_pt, ReInvRo_pt, ReSt_pt, and Viscosity_Ratio_pt.
Member Function Documentation
compute_error() [1/2]
void oomph::AxisymmetricNavierStokesEquations::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) virtual
Validate against exact solution. Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element
Validate against exact velocity solution Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
Reimplemented from oomph::FiniteElement.
   {
     error = 0.0;
     norm = 0.0;
     // Vector of local coordinates
     Vector<double> s(2);
     // Vector for coordintes
     Vector<double> x(2);
     // Set the value of Nintpt
     unsigned Nintpt = integral_pt()->nweight();
     outfile << "ZONE" << std::endl;
     // Exact solution Vector (u,v,w,p)
     Vector<double> exact_soln(4);
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < Nintpt; ipt++)
     {
       // Assign values of s
       for (unsigned i = 0; i < 2; i++)
       {
         s[i] = integral_pt()->knot(ipt, i);
       }
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Get jacobian of mapping
       double J = J_eulerian(s);
       // Get x position as Vector
       interpolated_x(s, x);
       // Premultiply the weights and the Jacobian and r
       double W = w * J * x[0];
       // Get exact solution at this point
       (*exact_soln_pt)(x, exact_soln);
       // Velocity error
       for (unsigned i = 0; i < 3; i++)
       {
         norm += exact_soln[i] * exact_soln[i] * W;
         error += (exact_soln[i] - interpolated_u_axi_nst(s, i)) *
                  (exact_soln[i] - interpolated_u_axi_nst(s, i)) * W;
       }
       // Output x,y,...,u_exact
       for (unsigned i = 0; i < 2; i++)
       {
         outfile << x[i] << " ";
       }
       // Output x,y,u_error,v_error,w_error
       for (unsigned i = 0; i < 3; i++)
       {
         outfile << exact_soln[i] - interpolated_u_axi_nst(s, i) << " ";
       }
       outfile << std::endl;
     }
   }
References calibrate::error, ProblemParameters::exact_soln(), i, oomph::FiniteElement::integral_pt(), interpolated_u_axi_nst(), oomph::FiniteElement::interpolated_x(), J, oomph::FiniteElement::J_eulerian(), oomph::Integral::knot(), GlobalParameters::Nintpt, oomph::Integral::nweight(), s, w, oomph::QuadTreeNames::W, oomph::Integral::weight(), and plotDoE::x.
compute_error() [2/2]
void oomph::AxisymmetricNavierStokesEquations::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) virtual
Validate against exact solution at given time Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element
Validate against exact velocity solution at given time. Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element.
Reimplemented from oomph::FiniteElement.
   {
     error = 0.0;
     norm = 0.0;
     // Vector of local coordinates
     Vector<double> s(2);
     // Vector for coordintes
     Vector<double> x(2);
     // Set the value of Nintpt
     unsigned Nintpt = integral_pt()->nweight();
     outfile << "ZONE" << std::endl;
     // Exact solution Vector (u,v,w,p)
     Vector<double> exact_soln(4);
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < Nintpt; ipt++)
     {
       // Assign values of s
       for (unsigned i = 0; i < 2; i++)
       {
         s[i] = integral_pt()->knot(ipt, i);
       }
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Get jacobian of mapping
       double J = J_eulerian(s);
       // Get x position as Vector
       interpolated_x(s, x);
       // Premultiply the weights and the Jacobian and r
       double W = w * J * x[0];
       // Get exact solution at this point
       (*exact_soln_pt)(time, x, exact_soln);
       // Velocity error
       for (unsigned i = 0; i < 3; i++)
       {
         norm += exact_soln[i] * exact_soln[i] * W;
         error += (exact_soln[i] - interpolated_u_axi_nst(s, i)) *
                  (exact_soln[i] - interpolated_u_axi_nst(s, i)) * W;
       }
       // Output x,y,...,u_exact
       for (unsigned i = 0; i < 2; i++)
       {
         outfile << x[i] << " ";
       }
       // Output x,y,[z],u_error,v_error,[w_error]
       for (unsigned i = 0; i < 3; i++)
       {
         outfile << exact_soln[i] - interpolated_u_axi_nst(s, i) << " ";
       }
       outfile << std::endl;
     }
   }
References calibrate::error, ProblemParameters::exact_soln(), i, oomph::FiniteElement::integral_pt(), interpolated_u_axi_nst(), oomph::FiniteElement::interpolated_x(), J, oomph::FiniteElement::J_eulerian(), oomph::Integral::knot(), GlobalParameters::Nintpt, oomph::Integral::nweight(), s, w, oomph::QuadTreeNames::W, oomph::Integral::weight(), and plotDoE::x.
compute_physical_size()
double oomph::AxisymmetricNavierStokesEquations::compute_physical_size () const inline virtual
Compute the volume of the element.
Reimplemented from oomph::FiniteElement.
     {
       // Initialise result
       double result = 0.0;
       // Figure out the global (Eulerian) spatial dimension of the
       // element by checking the Eulerian dimension of the nodes
       const unsigned n_dim_eulerian = nodal_dimension();
       // Allocate Vector of global Eulerian coordinates
       Vector<double> x(n_dim_eulerian);
       // Set the value of n_intpt
       const unsigned n_intpt = integral_pt()->nweight();
       // Vector of local coordinates
       const unsigned n_dim = dim();
       Vector<double> s(n_dim);
       // Loop over the integration points
       for (unsigned ipt = 0; ipt < n_intpt; ipt++)
       {
         // Assign the values of s
         for (unsigned i = 0; i < n_dim; i++)
         {
           s[i] = integral_pt()->knot(ipt, i);
         }
         // Assign the values of the global Eulerian coordinates
         for (unsigned i = 0; i < n_dim_eulerian; i++)
         {
           x[i] = interpolated_x(s, i);
         }
         // Get the integral weight
         const double w = integral_pt()->weight(ipt);
         // Get Jacobian of mapping
         const double J = J_eulerian(s);
         // The integrand at the current integration point is r
         result += x[0] * w * J;
       }
       // Multiply by 2pi (integrating in azimuthal direction)
       return (2.0 * MathematicalConstants::Pi * result);
     }
References oomph::FiniteElement::dim(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), J, oomph::FiniteElement::J_eulerian(), oomph::Integral::knot(), oomph::FiniteElement::nodal_dimension(), oomph::Integral::nweight(), oomph::MathematicalConstants::Pi, s, w, oomph::Integral::weight(), and plotDoE::x.
density_ratio()
const double& oomph::AxisymmetricNavierStokesEquations::density_ratio () const inline
Density ratio for element: Element's density relative to the viscosity used in the definition of the Reynolds number
     {
       return *Density_Ratio_pt;
     }
References Density_Ratio_pt.
Referenced by fill_in_contribution_to_hessian_vector_products(), fill_in_generic_dresidual_contribution_axi_nst(), fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), get_dresidual_dnodal_coordinates(), and oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates().
density_ratio_pt()
double*& oomph::AxisymmetricNavierStokesEquations::density_ratio_pt () inline
Pointer to Density ratio.
     {
       return Density_Ratio_pt;
     }
References Density_Ratio_pt.
Referenced by oomph::RefineableAxisymmetricNavierStokesEquations::further_build().
dinterpolated_u_axi_nst_ddata()
virtual void oomph::AxisymmetricNavierStokesEquations::dinterpolated_u_axi_nst_ddata (const Vector< double > & s, const unsigned & i, Vector< double > & du_ddata, Vector< unsigned > & global_eqn_number) inline virtual
Compute the derivatives of the i-th component of velocity at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. The function is virtual so that it can be overloaded in the refineable version
Reimplemented in oomph::RefineableAxisymmetricNavierStokesEquations.
     {
       // Find number of nodes
       unsigned n_node = nnode();
       // Local shape function
       Shape psi(n_node);
       // Find values of shape function
       shape(s, psi);
       // Find the index at which the velocity component is stored
       const unsigned u_nodal_index = u_index_axi_nst(i);
       // Find the number of dofs associated with interpolated u
       unsigned n_u_dof = 0;
       for (unsigned l = 0; l < n_node; l++)
       {
         int global_eqn = this->node_pt(l)->eqn_number(u_nodal_index);
         // If it's positive add to the count
         if (global_eqn >= 0)
         {
           ++n_u_dof;
         }
       }
       // Now resize the storage schemes
       du_ddata.resize(n_u_dof, 0.0);
       global_eqn_number.resize(n_u_dof, 0);
       // Loop over th nodes again and set the derivatives
       unsigned count = 0;
       // Loop over the local nodes and sum
       for (unsigned l = 0; l < n_node; l++)
       {
         // Get the global equation number
         int global_eqn = this->node_pt(l)->eqn_number(u_nodal_index);
         if (global_eqn >= 0)
         {
           // Set the global equation number
           global_eqn_number[count] = global_eqn;
           // Set the derivative with respect to the unknown
           du_ddata[count] = psi[l];
           // Increase the counter
           ++count;
         }
       }
     }
References oomph::Data::eqn_number(), i, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), s, oomph::FiniteElement::shape(), and u_index_axi_nst().
Referenced by QAxisymAdvectionDiffusionElementWithExternalElement::get_dwind_axi_adv_diff_dexternal_element_data().
disable_ALE()
void oomph::AxisymmetricNavierStokesEquations::disable_ALE () inline virtual
Disable ALE, i.e. assert the mesh is not moving – you do this at your own risk!
Reimplemented from oomph::FiniteElement.
     {
       ALE_is_disabled = true;
     }
References ALE_is_disabled.
Referenced by oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::disable_ALE(), and oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::disable_ALE().
dissipation() [1/2]
double oomph::AxisymmetricNavierStokesEquations::dissipation () const
Return integral of dissipation over element.
   {
     throw OomphLibError(
       "Check the dissipation calculation for axisymmetric NSt",
       OOMPH_CURRENT_FUNCTION,
       OOMPH_EXCEPTION_LOCATION);
     // Initialise
     double diss = 0.0;
     // Set the value of Nintpt
     unsigned Nintpt = integral_pt()->nweight();
     // Set the Vector to hold local coordinates
     Vector<double> s(2);
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < Nintpt; ipt++)
     {
       // Assign values of s
       for (unsigned i = 0; i < 2; i++)
       {
         s[i] = integral_pt()->knot(ipt, i);
       }
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Get Jacobian of mapping
       double J = J_eulerian(s);
       // Get strain rate matrix
       DenseMatrix<double> strainrate(3, 3);
       strain_rate(s, strainrate);
       // Initialise
       double local_diss = 0.0;
       for (unsigned i = 0; i < 3; i++)
       {
         for (unsigned j = 0; j < 3; j++)
         {
           local_diss += 2.0 * strainrate(i, j) * strainrate(i, j);
         }
       }
       diss += local_diss * w * J;
     }
     return diss;
   }
References i, oomph::FiniteElement::integral_pt(), J, j, oomph::FiniteElement::J_eulerian(), oomph::Integral::knot(), GlobalParameters::Nintpt, oomph::Integral::nweight(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, s, strain_rate(), w, and oomph::Integral::weight().
dissipation() [2/2]
double oomph::AxisymmetricNavierStokesEquations::dissipation (const Vector< double > & s) const
Return dissipation at local coordinate s.
   {
     throw OomphLibError(
       "Check the dissipation calculation for axisymmetric NSt",
       OOMPH_CURRENT_FUNCTION,
       OOMPH_EXCEPTION_LOCATION);
     // Get strain rate matrix
     DenseMatrix<double> strainrate(3, 3);
     strain_rate(s, strainrate);
     // Initialise
     double local_diss = 0.0;
     for (unsigned i = 0; i < 3; i++)
     {
       for (unsigned j = 0; j < 3; j++)
       {
         local_diss += 2.0 * strainrate(i, j) * strainrate(i, j);
       }
     }
     return local_diss;
   }
References i, j, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, s, and strain_rate().
dshape_and_dtest_eulerian_at_knot_axi_nst() [1/2]
virtual double oomph::AxisymmetricNavierStokesEquations::dshape_and_dtest_eulerian_at_knot_axi_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const protected pure virtual
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Implemented in oomph::AxisymmetricTTaylorHoodElement, oomph::AxisymmetricTCrouzeixRaviartElement, oomph::AxisymmetricQTaylorHoodElement, and oomph::AxisymmetricQCrouzeixRaviartElement.
dshape_and_dtest_eulerian_at_knot_axi_nst() [2/2]
virtual double oomph::AxisymmetricNavierStokesEquations::dshape_and_dtest_eulerian_at_knot_axi_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const protected pure virtual
Compute the shape functions and derivatives w.r.t. global coords at ipt-th integration point Return Jacobian of mapping between local and global coordinates.
Implemented in oomph::AxisymmetricTTaylorHoodElement, oomph::AxisymmetricTCrouzeixRaviartElement, oomph::AxisymmetricQTaylorHoodElement, and oomph::AxisymmetricQCrouzeixRaviartElement.
Referenced by fill_in_contribution_to_hessian_vector_products(), fill_in_generic_dresidual_contribution_axi_nst(), fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), get_dresidual_dnodal_coordinates(), and oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates().
dshape_and_dtest_eulerian_axi_nst()
virtual double oomph::AxisymmetricNavierStokesEquations::dshape_and_dtest_eulerian_axi_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const protected pure virtual
Compute the shape functions and derivatives w.r.t. global coords at local coordinate s. Return Jacobian of mapping between local and global coordinates.
Implemented in oomph::AxisymmetricTTaylorHoodElement, oomph::AxisymmetricTCrouzeixRaviartElement, oomph::AxisymmetricQTaylorHoodElement, and oomph::AxisymmetricQCrouzeixRaviartElement.
du_dt_axi_nst()
double oomph::AxisymmetricNavierStokesEquations::du_dt_axi_nst (const unsigned & n, const unsigned & i) const inline
i-th component of du/dt at local node n. Uses suitably interpolated value for hanging nodes.
     {
       // Get the data's timestepper
       TimeStepper* time_stepper_pt = this->node_pt(n)->time_stepper_pt();
       // Initialise dudt
       double dudt = 0.0;
       // Loop over the timesteps, if there is a non Steady timestepper
       if (!time_stepper_pt->is_steady())
       {
         // Get the index at which the velocity is stored
         const unsigned u_nodal_index = u_index_axi_nst(i);
         // Number of timsteps (past & present)
         const unsigned n_time = time_stepper_pt->ntstorage();
         // Add the contributions to the time derivative
         for (unsigned t = 0; t < n_time; t++)
         {
           dudt +=
             time_stepper_pt->weight(1, t) * nodal_value(t, n, u_nodal_index);
         }
       }
       return dudt;
     }
References i, oomph::TimeStepper::is_steady(), n, oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), plotPSD::t, oomph::GeomObject::time_stepper_pt(), oomph::Data::time_stepper_pt(), u_index_axi_nst(), and oomph::TimeStepper::weight().
Referenced by fill_in_generic_dresidual_contribution_axi_nst(), fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), get_dresidual_dnodal_coordinates(), oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), and interpolated_dudt_axi_nst().
enable_ALE()
void oomph::AxisymmetricNavierStokesEquations::enable_ALE () inline virtual
(Re-)enable ALE, i.e. take possible mesh motion into account when evaluating the time-derivative. Note: By default, ALE is enabled, at the expense of possibly creating unnecessary work in problems where the mesh is, in fact, stationary.
Reimplemented from oomph::FiniteElement.
     {
       ALE_is_disabled = false;
     }
References ALE_is_disabled.
Referenced by oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::enable_ALE(), and oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::enable_ALE().
fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter()
void oomph::AxisymmetricNavierStokesEquations::fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const & parameter_pt, Vector< double > & dres_dparam, DenseMatrix< double > & djac_dparam, DenseMatrix< double > & dmass_matrix_dparam) inline virtual
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix
Reimplemented from oomph::GeneralisedElement.
     {
       // Call the generic routine with the flag set to 2
       fill_in_generic_dresidual_contribution_axi_nst(
         parameter_pt, dres_dparam, djac_dparam, dmass_matrix_dparam, 2);
     }
References fill_in_generic_dresidual_contribution_axi_nst().
fill_in_contribution_to_djacobian_dparameter()
void oomph::AxisymmetricNavierStokesEquations::fill_in_contribution_to_djacobian_dparameter (double *const & parameter_pt, Vector< double > & dres_dparam, DenseMatrix< double > & djac_dparam) inline virtual
Compute the element's residual Vector and the jacobian matrix Virtual function can be overloaded by hanging-node version
Reimplemented from oomph::GeneralisedElement.
     {
       // Call the generic routine with the flag set to 1
       fill_in_generic_dresidual_contribution_axi_nst(
         parameter_pt,
         dres_dparam,
         djac_dparam,
         GeneralisedElement::Dummy_matrix,
         1);
     }
References oomph::GeneralisedElement::Dummy_matrix, and fill_in_generic_dresidual_contribution_axi_nst().
fill_in_contribution_to_dresiduals_dparameter()
void oomph::AxisymmetricNavierStokesEquations::fill_in_contribution_to_dresiduals_dparameter (double *const & parameter_pt, Vector< double > & dres_dparam) inline virtual
Compute the element's residual Vector.
Reimplemented from oomph::GeneralisedElement.
     {
       // Call the generic residuals function with flag set to 0
       // and using a dummy matrix argument
       fill_in_generic_dresidual_contribution_axi_nst(
         parameter_pt,
         dres_dparam,
         GeneralisedElement::Dummy_matrix,
         GeneralisedElement::Dummy_matrix,
         0);
     }
References oomph::GeneralisedElement::Dummy_matrix, and fill_in_generic_dresidual_contribution_axi_nst().
fill_in_contribution_to_hessian_vector_products()
void oomph::AxisymmetricNavierStokesEquations::fill_in_contribution_to_hessian_vector_products (Vector< double > const & Y, DenseMatrix< double > const & C, DenseMatrix< double > & product) protected virtual
Compute the hessian tensor vector products required to perform continuation of bifurcations analytically
Reimplemented from oomph::GeneralisedElement.
Reimplemented in oomph::RefineableAxisymmetricNavierStokesEquations.
   {
     // Find out how many nodes there are
     unsigned n_node = nnode();
     // Get the nodal indices at which the velocity is stored
     unsigned u_nodal_index[3];
     for (unsigned i = 0; i < 3; ++i)
     {
       u_nodal_index[i] = u_index_axi_nst(i);
     }
     // Set up memory for the shape and test functions
     // Note that there are only two dimensions, r and z in this problem
     Shape psif(n_node), testf(n_node);
     DShape dpsifdx(n_node, 2), dtestfdx(n_node, 2);
     // Number of integration points
     unsigned Nintpt = integral_pt()->nweight();
     // Set the Vector to hold local coordinates (two dimensions)
     Vector<double> s(2);
     // Get Physical Variables from Element
     // Reynolds number must be multiplied by the density ratio
     double scaled_re = re() * density_ratio();
     // double visc_ratio = viscosity_ratio();
     Vector<double> G = g();
     // Integers used to store the local equation and unknown numbers
     int local_eqn = 0, local_unknown = 0, local_freedom = 0;
     // How may dofs are there
     const unsigned n_dof = this->ndof();
     // Create a local matrix eigenvector product contribution
     DenseMatrix<double> jac_y(n_dof, n_dof, 0.0);
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < Nintpt; ipt++)
     {
       // Assign values of s
       for (unsigned i = 0; i < 2; i++) s[i] = integral_pt()->knot(ipt, i);
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Call the derivatives of the shape and test functions
       double J = dshape_and_dtest_eulerian_at_knot_axi_nst(
         ipt, psif, dpsifdx, testf, dtestfdx);
       // Premultiply the weights and the Jacobian
       double W = w * J;
       // Allocate storage for the position and the derivative of the
       // mesh positions wrt time
       Vector<double> interpolated_x(2, 0.0);
       // Vector<double> mesh_velocity(2,0.0);
       // Allocate storage for the pressure, velocity components and their
       // time and spatial derivatives
       Vector<double> interpolated_u(3, 0.0);
       // Vector<double> dudt(3,0.0);
       DenseMatrix<double> interpolated_dudx(3, 2, 0.0);
       // Calculate velocities and derivatives at integration point
       // Loop over nodes
       for (unsigned l = 0; l < n_node; l++)
       {
         // Cache the shape function
         const double psif_ = psif(l);
         // Loop over the two coordinate directions
         for (unsigned i = 0; i < 2; i++)
         {
           interpolated_x[i] += this->raw_nodal_position(l, i) * psif_;
         }
         // Loop over the three velocity directions
         for (unsigned i = 0; i < 3; i++)
         {
           // Get the u_value
           const double u_value = this->raw_nodal_value(l, u_nodal_index[i]);
           interpolated_u[i] += u_value * psif_;
           // dudt[i]+= du_dt_axi_nst(l,i)*psif_;
           // Loop over derivative directions
           for (unsigned j = 0; j < 2; j++)
           {
             interpolated_dudx(i, j) += u_value * dpsifdx(l, j);
           }
         }
       }
       // Get the mesh velocity if ALE is enabled
       if (!ALE_is_disabled)
       {
         throw OomphLibError("Moving nodes not implemented\n",
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
       // r is the first position component
       double r = interpolated_x[0];
       // MOMENTUM EQUATIONS
       //------------------
       // Loop over the test functions
       for (unsigned l = 0; l < n_node; l++)
       {
         // FIRST (RADIAL) MOMENTUM EQUATION
         local_eqn = nodal_local_eqn(l, u_nodal_index[0]);
         // If it's not a boundary condition
         if (local_eqn >= 0)
         {
           // Loop over the velocity shape functions yet again
           for (unsigned l3 = 0; l3 < n_node; l3++)
           {
             // Derivative of jacobian terms with respect to radial velocity
             local_freedom = nodal_local_eqn(l3, u_nodal_index[0]);
             if (local_freedom >= 0)
             {
               // Storage for the sums
               double temp = 0.0;
               // Loop over the velocity shape functions again
               for (unsigned l2 = 0; l2 < n_node; l2++)
               {
                 local_unknown = nodal_local_eqn(l2, u_nodal_index[0]);
                 // Radial velocity component
                 if (local_unknown >= 0)
                 {
                   // Remains of convective terms
                   temp -= scaled_re *
                           (r * psif[l2] * dpsifdx(l3, 0) +
                            r * psif[l3] * dpsifdx(l2, 0)) *
                           Y[local_unknown] * testf[l] * W;
                 }
                 // Axial velocity component
                 local_unknown = nodal_local_eqn(l2, u_nodal_index[1]);
                 if (local_unknown >= 0)
                 {
                   // Convective terms
                   temp -= scaled_re * r * psif[l2] * dpsifdx(l3, 1) *
                           Y[local_unknown] * testf[l] * W;
                 }
               }
               // Add the summed contribution to the product matrix
               jac_y(local_eqn, local_freedom) += temp;
             } // End of derivative wrt radial coordinate
             // Derivative of jacobian terms with respect to axial velocity
             local_freedom = nodal_local_eqn(l3, u_nodal_index[1]);
             if (local_freedom >= 0)
             {
               double temp = 0.0;
               // Loop over the velocity shape functions again
               for (unsigned l2 = 0; l2 < n_node; l2++)
               {
                 local_unknown = nodal_local_eqn(l2, u_nodal_index[0]);
                 // Radial velocity component
                 if (local_unknown >= 0)
                 {
                   // Remains of convective terms
                   temp -= scaled_re * (r * psif[l3] * dpsifdx(l2, 1)) *
                           Y[local_unknown] * testf[l] * W;
                 }
               }
               // Add the summed contribution to the product matrix
               jac_y(local_eqn, local_freedom) += temp;
             } // End of derivative wrt axial coordinate
             // Derivative of jacobian terms with respect to azimuthal velocity
             local_freedom = nodal_local_eqn(l3, u_nodal_index[2]);
             if (local_freedom >= 0)
             {
               double temp = 0.0;
               // Loop over the velocity shape functions again
               for (unsigned l2 = 0; l2 < n_node; l2++)
               {
                 // Azimuthal velocity component
                 local_unknown = nodal_local_eqn(l2, u_nodal_index[2]);
                 if (local_unknown >= 0)
                 {
                   // Convective terms
                   temp -= -scaled_re * 2.0 * psif[l3] * psif[l2] *
                           Y[local_unknown] * testf[l] * W;
                 }
               }
               // Add the summed contibution
               jac_y(local_eqn, local_freedom) += temp;
             } // End of if not boundary condition statement
           } // End of loop over freedoms
         } // End of RADIAL MOMENTUM EQUATION
         // SECOND (AXIAL) MOMENTUM EQUATION
         local_eqn = nodal_local_eqn(l, u_nodal_index[1]);
         // If it's not a boundary condition
         if (local_eqn >= 0)
         {
           // Loop over the velocity shape functions yet again
           for (unsigned l3 = 0; l3 < n_node; l3++)
           {
             // Derivative of jacobian terms with respect to radial velocity
             local_freedom = nodal_local_eqn(l3, u_nodal_index[0]);
             if (local_freedom >= 0)
             {
               double temp = 0.0;
               // Loop over the velocity shape functions again
               for (unsigned l2 = 0; l2 < n_node; l2++)
               {
                 // Axial velocity component
                 local_unknown = nodal_local_eqn(l2, u_nodal_index[1]);
                 if (local_unknown >= 0)
                 {
                   // Convective terms
                   temp -= scaled_re * (r * psif[l3] * dpsifdx(l2, 0)) *
                           Y[local_unknown] * testf[l] * W;
                 }
               }
               jac_y(local_eqn, local_freedom) += temp;
               // There are no azimithal terms in the axial momentum equation
             } // End of loop over velocity shape functions
             // Derivative of jacobian terms with respect to axial velocity
             local_freedom = nodal_local_eqn(l3, u_nodal_index[1]);
             if (local_freedom >= 0)
             {
               double temp = 0.0;
               // Loop over the velocity shape functions again
               for (unsigned l2 = 0; l2 < n_node; l2++)
               {
                 local_unknown = nodal_local_eqn(l2, u_nodal_index[0]);
                 // Radial velocity component
                 if (local_unknown >= 0)
                 {
                   // Convective terms
                   temp -= scaled_re * r * psif[l2] * dpsifdx(l3, 0) *
                           Y[local_unknown] * testf[l] * W;
                 }
                 // Axial velocity component
                 local_unknown = nodal_local_eqn(l2, u_nodal_index[1]);
                 if (local_unknown >= 0)
                 {
                   // Convective terms
                   temp -= scaled_re *
                           (r * psif[l2] * dpsifdx(l3, 1) +
                            r * psif[l3] * dpsifdx(l2, 1)) *
                           Y[local_unknown] * testf[l] * W;
                 }
                 // There are no azimithal terms in the axial momentum equation
               } // End of loop over velocity shape functions
               // Add summed contributiont to jacobian product matrix
               jac_y(local_eqn, local_freedom) += temp;
             }
           } // End of loop over local freedoms
         } // End of AXIAL MOMENTUM EQUATION
         // THIRD (AZIMUTHAL) MOMENTUM EQUATION
         local_eqn = nodal_local_eqn(l, u_nodal_index[2]);
         if (local_eqn >= 0)
         {
           // Loop over the velocity shape functions yet again
           for (unsigned l3 = 0; l3 < n_node; l3++)
           {
             // Derivative of jacobian terms with respect to radial velocity
             local_freedom = nodal_local_eqn(l3, u_nodal_index[0]);
             if (local_freedom >= 0)
             {
               double temp = 0.0;
               // Loop over the velocity shape functions again
               for (unsigned l2 = 0; l2 < n_node; l2++)
               {
                 // Azimuthal velocity component
                 local_unknown = nodal_local_eqn(l2, u_nodal_index[2]);
                 if (local_unknown >= 0)
                 {
                   // Convective terms
                   temp -=
                     scaled_re *
                     (r * psif[l3] * dpsifdx(l2, 0) + psif[l3] * psif[l2]) *
                     Y[local_unknown] * testf[l] * W;
                 }
               }
               // Add the summed contribution to the jacobian eigenvector sum
               jac_y(local_eqn, local_freedom) += temp;
             }
             // Derivative of jacobian terms with respect to axial velocity
             local_freedom = nodal_local_eqn(l3, u_nodal_index[1]);
             if (local_freedom >= 0)
             {
               double temp = 0.0;
               // Loop over the velocity shape functions again
               for (unsigned l2 = 0; l2 < n_node; l2++)
               {
                 // Azimuthal velocity component
                 local_unknown = nodal_local_eqn(l2, u_nodal_index[2]);
                 if (local_unknown >= 0)
                 {
                   // Convective terms
                   temp -= scaled_re * (r * psif[l3] * dpsifdx(l2, 1)) *
                           Y[local_unknown] * testf[l] * W;
                 }
               }
               // Add the summed contribution to the jacobian eigenvector sum
               jac_y(local_eqn, local_freedom) += temp;
             }
             // Derivative of jacobian terms with respect to azimuthal velocity
             local_freedom = nodal_local_eqn(l3, u_nodal_index[2]);
             if (local_freedom >= 0)
             {
               double temp = 0.0;
               // Loop over the velocity shape functions again
               for (unsigned l2 = 0; l2 < n_node; l2++)
               {
                 // Radial velocity component
                 local_unknown = nodal_local_eqn(l2, u_nodal_index[0]);
                 if (local_unknown >= 0)
                 {
                   // Convective terms
                   temp -=
                     scaled_re *
                     (r * psif[l2] * dpsifdx(l3, 0) + psif[l2] * psif[l3]) *
                     Y[local_unknown] * testf[l] * W;
                 }
                 // Axial velocity component
                 local_unknown = nodal_local_eqn(l2, u_nodal_index[1]);
                 if (local_unknown >= 0)
                 {
                   // Convective terms
                   temp -= scaled_re * r * psif[l2] * dpsifdx(l3, 1) *
                           Y[local_unknown] * testf[l] * W;
                 }
               }
               // Add the fully summed contribution
               jac_y(local_eqn, local_freedom) += temp;
             }
           } // End of loop over freedoms
           // There are no pressure terms
         } // End of AZIMUTHAL EQUATION
       } // End of loop over shape functions
     }
     // We have now assembled the matrix (d J_{ij} Y_j)/d u_{k}
     // and simply need to sum over the vectors
     const unsigned n_vec = C.nrow();
     for (unsigned i = 0; i < n_dof; i++)
     {
       for (unsigned k = 0; k < n_dof; k++)
       {
         // Cache the value of the hessian y product
         const double j_y = jac_y(i, k);
         // Loop over the possible vectors
         for (unsigned v = 0; v < n_vec; v++)
         {
           product(v, i) += j_y * C(v, k);
         }
       }
     }
   }
References ALE_is_disabled, density_ratio(), dshape_and_dtest_eulerian_at_knot_axi_nst(), G, g(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), J, j, k, oomph::Integral::knot(), oomph::GeneralisedElement::ndof(), GlobalParameters::Nintpt, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::Matrix< T, MATRIX_TYPE >::nrow(), oomph::Integral::nweight(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, product(), UniformPSDSelfTest::r, oomph::FiniteElement::raw_nodal_position(), oomph::FiniteElement::raw_nodal_value(), re(), s, u_index_axi_nst(), v, w, oomph::QuadTreeNames::W, oomph::Integral::weight(), and Y.
fill_in_contribution_to_jacobian()
void oomph::AxisymmetricNavierStokesEquations::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline virtual
Compute the element's residual Vector and the jacobian matrix Virtual function can be overloaded by hanging-node version
Reimplemented from oomph::GeneralisedElement.
Reimplemented in oomph::PseudoSolidNodeUpdateElement< AxisymmetricTTaylorHoodElement, TPVDElement< 2, 3 > >.
     {
       // Call the generic routine with the flag set to 1
       fill_in_generic_residual_contribution_axi_nst(
         residuals, jacobian, GeneralisedElement::Dummy_matrix, 1);
     }
References oomph::GeneralisedElement::Dummy_matrix, and fill_in_generic_residual_contribution_axi_nst().
Referenced by oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::fill_in_contribution_to_jacobian(), RefineableQAxisymCrouzeixRaviartBoussinesqElement::fill_in_contribution_to_jacobian(), QAxisymCrouzeixRaviartElementWithExternalElement::fill_in_contribution_to_jacobian(), and oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::fill_in_contribution_to_jacobian().
fill_in_contribution_to_jacobian_and_mass_matrix()
void oomph::AxisymmetricNavierStokesEquations::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) inline virtual
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix
Reimplemented from oomph::GeneralisedElement.
Reimplemented in oomph::PseudoSolidNodeUpdateElement< AxisymmetricTTaylorHoodElement, TPVDElement< 2, 3 > >.
     {
       // Call the generic routine with the flag set to 2
       fill_in_generic_residual_contribution_axi_nst(
         residuals, jacobian, mass_matrix, 2);
     }
References fill_in_generic_residual_contribution_axi_nst().
Referenced by oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::fill_in_contribution_to_jacobian_and_mass_matrix().
fill_in_contribution_to_residuals()
void oomph::AxisymmetricNavierStokesEquations::fill_in_contribution_to_residuals (Vector< double > & residuals) inline virtual
Compute the element's residual Vector.
Reimplemented from oomph::GeneralisedElement.
Reimplemented in oomph::PseudoSolidNodeUpdateElement< AxisymmetricTTaylorHoodElement, TPVDElement< 2, 3 > >.
     {
       // Call the generic residuals function with flag set to 0
       // and using a dummy matrix argument
       fill_in_generic_residual_contribution_axi_nst(
         residuals,
         GeneralisedElement::Dummy_matrix,
         GeneralisedElement::Dummy_matrix,
         0);
     }
References oomph::GeneralisedElement::Dummy_matrix, and fill_in_generic_residual_contribution_axi_nst().
Referenced by oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::fill_in_contribution_to_residuals(), and oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::fill_in_contribution_to_residuals().
fill_in_generic_dresidual_contribution_axi_nst()
void oomph::AxisymmetricNavierStokesEquations::fill_in_generic_dresidual_contribution_axi_nst (double *const & parameter_pt, Vector< double > & dres_dparam, DenseMatrix< double > & djac_dparam, DenseMatrix< double > & dmass_matrix_dparam, unsigned flag) protected virtual
Compute the derivative of residuals for the Navier–Stokes equations; with respect to a parameeter flag=2 or 1 or 0: compute the Jacobian and/or mass matrix as well
Compute the residuals for the Navier–Stokes equations; flag=1(or 0): do (or don't) compute the Jacobian as well.
Reimplemented in oomph::RefineableAxisymmetricNavierStokesEquations.
   {
     // Die if the parameter is not the Reynolds number
     if (parameter_pt != this->re_pt())
     {
       std::ostringstream error_stream;
       error_stream
         << "Cannot compute analytic jacobian for parameter addressed by "
         << parameter_pt << "\n";
       error_stream << "Can only compute derivatives wrt Re (" << Re_pt << ")\n";
       throw OomphLibError(
         error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
     // Which parameters are we differentiating with respect to
     bool diff_re = false;
     bool diff_re_st = false;
     bool diff_re_inv_fr = false;
     bool diff_re_inv_ro = false;
     // Set the boolean flags according to the parameter pointer
     if (parameter_pt == this->re_pt())
     {
       diff_re = true;
     }
     if (parameter_pt == this->re_st_pt())
     {
       diff_re_st = true;
     }
     if (parameter_pt == this->re_invfr_pt())
     {
       diff_re_inv_fr = true;
     }
     if (parameter_pt == this->re_invro_pt())
     {
       diff_re_inv_ro = true;
     }
     // Find out how many nodes there are
     unsigned n_node = nnode();
     // Find out how many pressure dofs there are
     unsigned n_pres = npres_axi_nst();
     // Get the nodal indices at which the velocity is stored
     unsigned u_nodal_index[3];
     for (unsigned i = 0; i < 3; ++i)
     {
       u_nodal_index[i] = u_index_axi_nst(i);
     }
     // Set up memory for the shape and test functions
     // Note that there are only two dimensions, r and z in this problem
     Shape psif(n_node), testf(n_node);
     DShape dpsifdx(n_node, 2), dtestfdx(n_node, 2);
     // Set up memory for pressure shape and test functions
     Shape psip(n_pres), testp(n_pres);
     // Number of integration points
     unsigned Nintpt = integral_pt()->nweight();
     // Set the Vector to hold local coordinates (two dimensions)
     Vector<double> s(2);
     // Get Physical Variables from Element
     // Reynolds number must be multiplied by the density ratio
     // double scaled_re = re()*density_ratio();
     // double scaled_re_st = re_st()*density_ratio();
     // double scaled_re_inv_fr = re_invfr()*density_ratio();
     // double scaled_re_inv_ro = re_invro()*density_ratio();
     double dens_ratio = this->density_ratio();
     // double visc_ratio = viscosity_ratio();
     Vector<double> G = g();
     // Integers used to store the local equation and unknown numbers
     int local_eqn = 0, local_unknown = 0;
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < Nintpt; ipt++)
     {
       // Assign values of s
       for (unsigned i = 0; i < 2; i++) s[i] = integral_pt()->knot(ipt, i);
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Call the derivatives of the shape and test functions
       double J = dshape_and_dtest_eulerian_at_knot_axi_nst(
         ipt, psif, dpsifdx, testf, dtestfdx);
       // Call the pressure shape and test functions
       pshape_axi_nst(s, psip, testp);
       // Premultiply the weights and the Jacobian
       double W = w * J;
       // Allocate storage for the position and the derivative of the
       // mesh positions wrt time
       Vector<double> interpolated_x(2, 0.0);
       Vector<double> mesh_velocity(2, 0.0);
       // Allocate storage for the pressure, velocity components and their
       // time and spatial derivatives
       double interpolated_p = 0.0;
       Vector<double> interpolated_u(3, 0.0);
       Vector<double> dudt(3, 0.0);
       DenseMatrix<double> interpolated_dudx(3, 2, 0.0);
       // Calculate pressure at integration point
       for (unsigned l = 0; l < n_pres; l++)
       {
         interpolated_p += p_axi_nst(l) * psip[l];
       }
       // Calculate velocities and derivatives at integration point
       // Loop over nodes
       for (unsigned l = 0; l < n_node; l++)
       {
         // Cache the shape function
         const double psif_ = psif(l);
         // Loop over the two coordinate directions
         for (unsigned i = 0; i < 2; i++)
         {
           interpolated_x[i] += this->raw_nodal_position(l, i) * psif_;
         }
         // mesh_velocity[i]  += dnodal_position_dt(l,i)*psif[l];
         // Loop over the three velocity directions
         for (unsigned i = 0; i < 3; i++)
         {
           // Get the u_value
           const double u_value = this->raw_nodal_value(l, u_nodal_index[i]);
           interpolated_u[i] += u_value * psif_;
           dudt[i] += du_dt_axi_nst(l, i) * psif_;
           // Loop over derivative directions
           for (unsigned j = 0; j < 2; j++)
           {
             interpolated_dudx(i, j) += u_value * dpsifdx(l, j);
           }
         }
       }
       // Get the mesh velocity if ALE is enabled
       if (!ALE_is_disabled)
       {
         // Loop over nodes
         for (unsigned l = 0; l < n_node; l++)
         {
           // Loop over the two coordinate directions
           for (unsigned i = 0; i < 2; i++)
           {
             mesh_velocity[i] += this->raw_dnodal_position_dt(l, i) * psif(l);
           }
         }
       }
       // Get the user-defined body force terms
       // Vector<double> body_force(3);
       // get_body_force(time(),ipt,interpolated_x,body_force);
       // Get the user-defined source function
       // double source = get_source_fct(time(),ipt,interpolated_x);
       // Get the user-defined viscosity function
       double visc_ratio;
       get_viscosity_ratio_axisym_nst(ipt, s, interpolated_x, visc_ratio);
       // r is the first position component
       double r = interpolated_x[0];
       // MOMENTUM EQUATIONS
       //------------------
       // Loop over the test functions
       for (unsigned l = 0; l < n_node; l++)
       {
         // FIRST (RADIAL) MOMENTUM EQUATION
         local_eqn = nodal_local_eqn(l, u_nodal_index[0]);
         // If it's not a boundary condition
         if (local_eqn >= 0)
         {
           // No user-defined body force terms
           // dres_dparam[local_eqn] +=
           // r*body_force[0]*testf[l]*W;
           // Add the gravitational body force term if the reynolds number
           // is equal to re_inv_fr
           if (diff_re_inv_fr)
           {
             dres_dparam[local_eqn] += r * dens_ratio * testf[l] * G[0] * W;
           }
           // No pressure gradient term
           // residuals[local_eqn]  +=
           // interpolated_p*(testf[l] + r*dtestfdx(l,0))*W;
           // No in the stress tensor terms
           // The viscosity ratio needs to go in here to ensure
           // continuity of normal stress is satisfied even in flows
           // with zero pressure gradient!
           // residuals[local_eqn] -= visc_ratio*
           // r*(1.0+Gamma[0])*interpolated_dudx(0,0)*dtestfdx(l,0)*W;
           // residuals[local_eqn] -= visc_ratio*r*
           // (interpolated_dudx(0,1) + Gamma[0]*interpolated_dudx(1,0))*
           // dtestfdx(l,1)*W;
           // residuals[local_eqn] -=
           // visc_ratio*(1.0 + Gamma[0])*interpolated_u[0]*testf[l]*W/r;
           // Add in the inertial terms
           // du/dt term
           if (diff_re_st)
           {
             dres_dparam[local_eqn] -= dens_ratio * r * dudt[0] * testf[l] * W;
           }
           // Convective terms
           if (diff_re)
           {
             dres_dparam[local_eqn] -=
               dens_ratio *
               (r * interpolated_u[0] * interpolated_dudx(0, 0) -
                interpolated_u[2] * interpolated_u[2] +
                r * interpolated_u[1] * interpolated_dudx(0, 1)) *
               testf[l] * W;
           }
           // Mesh velocity terms
           if (!ALE_is_disabled)
           {
             if (diff_re_st)
             {
               for (unsigned k = 0; k < 2; k++)
               {
                 dres_dparam[local_eqn] += dens_ratio * r * mesh_velocity[k] *
                                           interpolated_dudx(0, k) * testf[l] *
                                           W;
               }
             }
           }
           // Add the Coriolis term
           if (diff_re_inv_ro)
           {
             dres_dparam[local_eqn] +=
               2.0 * r * dens_ratio * interpolated_u[2] * testf[l] * W;
           }
           // CALCULATE THE JACOBIAN
           if (flag)
           {
             // Loop over the velocity shape functions again
             for (unsigned l2 = 0; l2 < n_node; l2++)
             {
               local_unknown = nodal_local_eqn(l2, u_nodal_index[0]);
               // Radial velocity component
               if (local_unknown >= 0)
               {
                 if (flag == 2)
                 {
                   if (diff_re_st)
                   {
                     // Add the mass matrix
                     dmass_matrix_dparam(local_eqn, local_unknown) +=
                       dens_ratio * r * psif[l2] * testf[l] * W;
                   }
                 }
                 // Add contribution to the Jacobian matrix
                 // jacobian(local_eqn,local_unknown)
                 // -= visc_ratio*r*(1.0+Gamma[0])
                 //*dpsifdx(l2,0)*dtestfdx(l,0)*W;
                 // jacobian(local_eqn,local_unknown)
                 // -= visc_ratio*r*dpsifdx(l2,1)*dtestfdx(l,1)*W;
                 // jacobian(local_eqn,local_unknown)
                 // -= visc_ratio*(1.0 + Gamma[0])*psif[l2]*testf[l]*W/r;
                 // Add in the inertial terms
                 // du/dt term
                 if (diff_re_st)
                 {
                   djac_dparam(local_eqn, local_unknown) -=
                     dens_ratio * r *
                     node_pt(l2)->time_stepper_pt()->weight(1, 0) * psif[l2] *
                     testf[l] * W;
                 }
                 // Convective terms
                 if (diff_re)
                 {
                   djac_dparam(local_eqn, local_unknown) -=
                     dens_ratio *
                     (r * psif[l2] * interpolated_dudx(0, 0) +
                      r * interpolated_u[0] * dpsifdx(l2, 0) +
                      r * interpolated_u[1] * dpsifdx(l2, 1)) *
                     testf[l] * W;
                 }
                 // Mesh velocity terms
                 if (!ALE_is_disabled)
                 {
                   for (unsigned k = 0; k < 2; k++)
                   {
                     if (diff_re_st)
                     {
                       djac_dparam(local_eqn, local_unknown) +=
                         dens_ratio * r * mesh_velocity[k] * dpsifdx(l2, k) *
                         testf[l] * W;
                     }
                   }
                 }
               }
               // Axial velocity component
               local_unknown = nodal_local_eqn(l2, u_nodal_index[1]);
               if (local_unknown >= 0)
               {
                 // jacobian(local_eqn,local_unknown) -=
                 // visc_ratio*r*Gamma[0]*dpsifdx(l2,0)*dtestfdx(l,1)*W;
                 // Convective terms
                 if (diff_re)
                 {
                   djac_dparam(local_eqn, local_unknown) -=
                     dens_ratio * r * psif[l2] * interpolated_dudx(0, 1) *
                     testf[l] * W;
                 }
               }
               // Azimuthal velocity component
               local_unknown = nodal_local_eqn(l2, u_nodal_index[2]);
               if (local_unknown >= 0)
               {
                 // Convective terms
                 if (diff_re)
                 {
                   djac_dparam(local_eqn, local_unknown) -=
                     -dens_ratio * 2.0 * interpolated_u[2] * psif[l2] *
                     testf[l] * W;
                 }
                 // Coriolis terms
                 if (diff_re_inv_ro)
                 {
                   djac_dparam(local_eqn, local_unknown) +=
                     2.0 * r * dens_ratio * psif[l2] * testf[l] * W;
                 }
               }
             }
             /*Now loop over pressure shape functions*/
             /*This is the contribution from pressure gradient*/
             // for(unsigned l2=0;l2<n_pres;l2++)
             // {
             //  local_unknown = p_local_eqn(l2);
             //  /*If we are at a non-zero degree of freedom in the entry*/
             //  if(local_unknown >= 0)
             //   {
             //    jacobian(local_eqn,local_unknown)
             //     += psip[l2]*(testf[l] + r*dtestfdx(l,0))*W;
             //   }
             // }
           } /*End of Jacobian calculation*/
         } // End of if not boundary condition statement
         // SECOND (AXIAL) MOMENTUM EQUATION
         local_eqn = nodal_local_eqn(l, u_nodal_index[1]);
         // If it's not a boundary condition
         if (local_eqn >= 0)
         {
           // Add the user-defined body force terms
           // Remember to multiply by the density ratio!
           // residuals[local_eqn] +=
           // r*body_force[1]*testf[l]*W;
           // Add the gravitational body force term
           if (diff_re_inv_fr)
           {
             dres_dparam[local_eqn] += r * dens_ratio * testf[l] * G[1] * W;
           }
           // Add the pressure gradient term
           // residuals[local_eqn]  += r*interpolated_p*dtestfdx(l,1)*W;
           // Add in the stress tensor terms
           // The viscosity ratio needs to go in here to ensure
           // continuity of normal stress is satisfied even in flows
           // with zero pressure gradient!
           // residuals[local_eqn] -= visc_ratio*
           //  r*(interpolated_dudx(1,0) + Gamma[1]*interpolated_dudx(0,1))
           // *dtestfdx(l,0)*W;
           // residuals[local_eqn] -= visc_ratio*r*
           // (1.0 + Gamma[1])*interpolated_dudx(1,1)*dtestfdx(l,1)*W;
           // Add in the inertial terms
           // du/dt term
           if (diff_re_st)
           {
             dres_dparam[local_eqn] -= dens_ratio * r * dudt[1] * testf[l] * W;
           }
           // Convective terms
           if (diff_re)
           {
             dres_dparam[local_eqn] -=
               dens_ratio *
               (r * interpolated_u[0] * interpolated_dudx(1, 0) +
                r * interpolated_u[1] * interpolated_dudx(1, 1)) *
               testf[l] * W;
           }
           // Mesh velocity terms
           if (!ALE_is_disabled)
           {
             if (diff_re_st)
             {
               for (unsigned k = 0; k < 2; k++)
               {
                 dres_dparam[local_eqn] += dens_ratio * r * mesh_velocity[k] *
                                           interpolated_dudx(1, k) * testf[l] *
                                           W;
               }
             }
           }
           // CALCULATE THE JACOBIAN
           if (flag)
           {
             // Loop over the velocity shape functions again
             for (unsigned l2 = 0; l2 < n_node; l2++)
             {
               local_unknown = nodal_local_eqn(l2, u_nodal_index[0]);
               // Radial velocity component
               if (local_unknown >= 0)
               {
                 // Add in the stress tensor terms
                 // The viscosity ratio needs to go in here to ensure
                 // continuity of normal stress is satisfied even in flows
                 // with zero pressure gradient!
                 // jacobian(local_eqn,local_unknown) -=
                 // visc_ratio*r*Gamma[1]*dpsifdx(l2,1)*dtestfdx(l,0)*W;
                 // Convective terms
                 if (diff_re)
                 {
                   djac_dparam(local_eqn, local_unknown) -=
                     dens_ratio * r * psif[l2] * interpolated_dudx(1, 0) *
                     testf[l] * W;
                 }
               }
               // Axial velocity component
               local_unknown = nodal_local_eqn(l2, u_nodal_index[1]);
               if (local_unknown >= 0)
               {
                 if (flag == 2)
                 {
                   if (diff_re_st)
                   {
                     // Add the mass matrix
                     dmass_matrix_dparam(local_eqn, local_unknown) +=
                       dens_ratio * r * psif[l2] * testf[l] * W;
                   }
                 }
                 // Add in the stress tensor terms
                 // The viscosity ratio needs to go in here to ensure
                 // continuity of normal stress is satisfied even in flows
                 // with zero pressure gradient!
                 // jacobian(local_eqn,local_unknown) -=
                 // visc_ratio*r*dpsifdx(l2,0)*dtestfdx(l,0)*W;
                 // jacobian(local_eqn,local_unknown) -=
                 // visc_ratio*r*(1.0 + Gamma[1])*dpsifdx(l2,1)*
                 // dtestfdx(l,1)*W;
                 // Add in the inertial terms
                 // du/dt term
                 if (diff_re_st)
                 {
                   djac_dparam(local_eqn, local_unknown) -=
                     dens_ratio * r *
                     node_pt(l2)->time_stepper_pt()->weight(1, 0) * psif[l2] *
                     testf[l] * W;
                 }
                 // Convective terms
                 if (diff_re)
                 {
                   djac_dparam(local_eqn, local_unknown) -=
                     dens_ratio *
                     (r * interpolated_u[0] * dpsifdx(l2, 0) +
                      r * psif[l2] * interpolated_dudx(1, 1) +
                      r * interpolated_u[1] * dpsifdx(l2, 1)) *
                     testf[l] * W;
                 }
                 // Mesh velocity terms
                 if (!ALE_is_disabled)
                 {
                   for (unsigned k = 0; k < 2; k++)
                   {
                     if (diff_re_st)
                     {
                       djac_dparam(local_eqn, local_unknown) +=
                         dens_ratio * r * mesh_velocity[k] * dpsifdx(l2, k) *
                         testf[l] * W;
                     }
                   }
                 }
               }
               // There are no azimithal terms in the axial momentum equation
             } // End of loop over velocity shape functions
           } /*End of Jacobian calculation*/
         } // End of AXIAL MOMENTUM EQUATION
         // THIRD (AZIMUTHAL) MOMENTUM EQUATION
         local_eqn = nodal_local_eqn(l, u_nodal_index[2]);
         if (local_eqn >= 0)
         {
           // Add the user-defined body force terms
           // Remember to multiply by the density ratio!
           // residuals[local_eqn] +=
           // r*body_force[2]*testf[l]*W;
           // Add the gravitational body force term
           if (diff_re_inv_fr)
           {
             dres_dparam[local_eqn] += r * dens_ratio * testf[l] * G[2] * W;
           }
           // There is NO pressure gradient term
           // Add in the stress tensor terms
           // The viscosity ratio needs to go in here to ensure
           // continuity of normal stress is satisfied even in flows
           // with zero pressure gradient!
           // residuals[local_eqn] -= visc_ratio*
           // (r*interpolated_dudx(2,0) -
           //  Gamma[0]*interpolated_u[2])*dtestfdx(l,0)*W;
           // residuals[local_eqn] -= visc_ratio*r*
           // interpolated_dudx(2,1)*dtestfdx(l,1)*W;
           // residuals[local_eqn] -= visc_ratio*
           // ((interpolated_u[2]/r) -
           // Gamma[0]*interpolated_dudx(2,0))*testf[l]*W;
           // Add in the inertial terms
           // du/dt term
           if (diff_re_st)
           {
             dres_dparam[local_eqn] -= dens_ratio * r * dudt[2] * testf[l] * W;
           }
           // Convective terms
           if (diff_re)
           {
             dres_dparam[local_eqn] -=
               dens_ratio *
               (r * interpolated_u[0] * interpolated_dudx(2, 0) +
                interpolated_u[0] * interpolated_u[2] +
                r * interpolated_u[1] * interpolated_dudx(2, 1)) *
               testf[l] * W;
           }
           // Mesh velocity terms
           if (!ALE_is_disabled)
           {
             if (diff_re_st)
             {
               for (unsigned k = 0; k < 2; k++)
               {
                 dres_dparam[local_eqn] += dens_ratio * r * mesh_velocity[k] *
                                           interpolated_dudx(2, k) * testf[l] *
                                           W;
               }
             }
           }
           // Add the Coriolis term
           if (diff_re_inv_ro)
           {
             dres_dparam[local_eqn] -=
               2.0 * r * dens_ratio * interpolated_u[0] * testf[l] * W;
           }
           // CALCULATE THE JACOBIAN
           if (flag)
           {
             // Loop over the velocity shape functions again
             for (unsigned l2 = 0; l2 < n_node; l2++)
             {
               // Radial velocity component
               local_unknown = nodal_local_eqn(l2, u_nodal_index[0]);
               if (local_unknown >= 0)
               {
                 // Convective terms
                 if (diff_re)
                 {
                   djac_dparam(local_eqn, local_unknown) -=
                     dens_ratio *
                     (r * psif[l2] * interpolated_dudx(2, 0) +
                      psif[l2] * interpolated_u[2]) *
                     testf[l] * W;
                 }
                 // Coriolis term
                 if (diff_re_inv_ro)
                 {
                   djac_dparam(local_eqn, local_unknown) -=
                     2.0 * r * dens_ratio * psif[l2] * testf[l] * W;
                 }
               }
               // Axial velocity component
               local_unknown = nodal_local_eqn(l2, u_nodal_index[1]);
               if (local_unknown >= 0)
               {
                 // Convective terms
                 if (diff_re)
                 {
                   djac_dparam(local_eqn, local_unknown) -=
                     dens_ratio * r * psif[l2] * interpolated_dudx(2, 1) *
                     testf[l] * W;
                 }
               }
               // Azimuthal velocity component
               local_unknown = nodal_local_eqn(l2, u_nodal_index[2]);
               if (local_unknown >= 0)
               {
                 if (flag == 2)
                 {
                   // Add the mass matrix
                   if (diff_re_st)
                   {
                     dmass_matrix_dparam(local_eqn, local_unknown) +=
                       dens_ratio * r * psif[l2] * testf[l] * W;
                   }
                 }
                 // Add in the stress tensor terms
                 // The viscosity ratio needs to go in here to ensure
                 // continuity of normal stress is satisfied even in flows
                 // with zero pressure gradient!
                 // jacobian(local_eqn,local_unknown) -=
                 // visc_ratio*(r*dpsifdx(l2,0) -
                 //                  Gamma[0]*psif[l2])*dtestfdx(l,0)*W;
                 // jacobian(local_eqn,local_unknown) -=
                 // visc_ratio*r*dpsifdx(l2,1)*dtestfdx(l,1)*W;
                 // jacobian(local_eqn,local_unknown) -=
                 // visc_ratio*((psif[l2]/r) - Gamma[0]*dpsifdx(l2,0))
                 // *testf[l]*W;
                 // Add in the inertial terms
                 // du/dt term
                 if (diff_re_st)
                 {
                   djac_dparam(local_eqn, local_unknown) -=
                     dens_ratio * r *
                     node_pt(l2)->time_stepper_pt()->weight(1, 0) * psif[l2] *
                     testf[l] * W;
                 }
                 // Convective terms
                 if (diff_re)
                 {
                   djac_dparam(local_eqn, local_unknown) -=
                     dens_ratio *
                     (r * interpolated_u[0] * dpsifdx(l2, 0) +
                      interpolated_u[0] * psif[l2] +
                      r * interpolated_u[1] * dpsifdx(l2, 1)) *
                     testf[l] * W;
                 }
                 // Mesh velocity terms
                 if (!ALE_is_disabled)
                 {
                   if (diff_re_st)
                   {
                     for (unsigned k = 0; k < 2; k++)
                     {
                       djac_dparam(local_eqn, local_unknown) +=
                         dens_ratio * r * mesh_velocity[k] * dpsifdx(l2, k) *
                         testf[l] * W;
                     }
                   }
                 }
               }
             }
             // There are no pressure terms
           } // End of Jacobian
         } // End of AZIMUTHAL EQUATION
       } // End of loop over shape functions
       // CONTINUITY EQUATION NO PARAMETERS
       //-------------------
     }
   }
References ALE_is_disabled, density_ratio(), dshape_and_dtest_eulerian_at_knot_axi_nst(), du_dt_axi_nst(), G, g(), get_viscosity_ratio_axisym_nst(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), J, j, k, oomph::Integral::knot(), GlobalParameters::Nintpt, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), npres_axi_nst(), oomph::Integral::nweight(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, p_axi_nst(), pshape_axi_nst(), UniformPSDSelfTest::r, oomph::FiniteElement::raw_dnodal_position_dt(), oomph::FiniteElement::raw_nodal_position(), oomph::FiniteElement::raw_nodal_value(), re_invfr_pt(), re_invro_pt(), Re_pt, re_pt(), re_st_pt(), s, oomph::Data::time_stepper_pt(), u_index_axi_nst(), w, oomph::QuadTreeNames::W, oomph::Integral::weight(), and oomph::TimeStepper::weight().
Referenced by fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter(), fill_in_contribution_to_djacobian_dparameter(), and fill_in_contribution_to_dresiduals_dparameter().
fill_in_generic_residual_contribution_axi_nst()
void oomph::AxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, unsigned flag) protected virtual
Compute the residuals for the Navier–Stokes equations; flag=2 or 1 or 0: compute the Jacobian and/or mass matrix as well.
Compute the residuals for the Navier–Stokes equations; flag=1(or 0): do (or don't) compute the Jacobian as well.
Reimplemented in oomph::RefineableAxisymmetricNavierStokesEquations.
   {
     // Find out how many nodes there are
     unsigned n_node = nnode();
     // Get continuous time from timestepper of first node
     double time = node_pt(0)->time_stepper_pt()->time_pt()->time();
     // Find out how many pressure dofs there are
     unsigned n_pres = npres_axi_nst();
     // Get the nodal indices at which the velocity is stored
     unsigned u_nodal_index[3];
     for (unsigned i = 0; i < 3; ++i)
     {
       u_nodal_index[i] = u_index_axi_nst(i);
     }
     // Set up memory for the shape and test functions
     // Note that there are only two dimensions, r and z in this problem
     Shape psif(n_node), testf(n_node);
     DShape dpsifdx(n_node, 2), dtestfdx(n_node, 2);
     // Set up memory for pressure shape and test functions
     Shape psip(n_pres), testp(n_pres);
     // Number of integration points
     unsigned Nintpt = integral_pt()->nweight();
     // Set the Vector to hold local coordinates (two dimensions)
     Vector<double> s(2);
     // Get Physical Variables from Element
     // Reynolds number must be multiplied by the density ratio
     double scaled_re = re() * density_ratio();
     double scaled_re_st = re_st() * density_ratio();
     double scaled_re_inv_fr = re_invfr() * density_ratio();
     double scaled_re_inv_ro = re_invro() * density_ratio();
     // double visc_ratio = viscosity_ratio();
     Vector<double> G = g();
     // Integers used to store the local equation and unknown numbers
     int local_eqn = 0, local_unknown = 0;
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < Nintpt; ipt++)
     {
       // Assign values of s
       for (unsigned i = 0; i < 2; i++) s[i] = integral_pt()->knot(ipt, i);
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Call the derivatives of the shape and test functions
       double J = dshape_and_dtest_eulerian_at_knot_axi_nst(
         ipt, psif, dpsifdx, testf, dtestfdx);
       // Call the pressure shape and test functions
       pshape_axi_nst(s, psip, testp);
       // Premultiply the weights and the Jacobian
       double W = w * J;
       // Allocate storage for the position and the derivative of the
       // mesh positions wrt time
       Vector<double> interpolated_x(2, 0.0);
       Vector<double> mesh_velocity(2, 0.0);
       // Allocate storage for the pressure, velocity components and their
       // time and spatial derivatives
       double interpolated_p = 0.0;
       Vector<double> interpolated_u(3, 0.0);
       Vector<double> dudt(3, 0.0);
       DenseMatrix<double> interpolated_dudx(3, 2, 0.0);
       // Calculate pressure at integration point
       for (unsigned l = 0; l < n_pres; l++)
       {
         interpolated_p += p_axi_nst(l) * psip[l];
       }
       // Calculate velocities and derivatives at integration point
       // Loop over nodes
       for (unsigned l = 0; l < n_node; l++)
       {
         // Cache the shape function
         const double psif_ = psif(l);
         // Loop over the two coordinate directions
         for (unsigned i = 0; i < 2; i++)
         {
           interpolated_x[i] += this->raw_nodal_position(l, i) * psif_;
         }
         // mesh_velocity[i]  += dnodal_position_dt(l,i)*psif[l];
         // Loop over the three velocity directions
         for (unsigned i = 0; i < 3; i++)
         {
           // Get the u_value
           const double u_value = this->raw_nodal_value(l, u_nodal_index[i]);
           interpolated_u[i] += u_value * psif_;
           dudt[i] += du_dt_axi_nst(l, i) * psif_;
           // Loop over derivative directions
           for (unsigned j = 0; j < 2; j++)
           {
             interpolated_dudx(i, j) += u_value * dpsifdx(l, j);
           }
         }
       }
       // Get the mesh velocity if ALE is enabled
       if (!ALE_is_disabled)
       {
         // Loop over nodes
         for (unsigned l = 0; l < n_node; l++)
         {
           // Loop over the two coordinate directions
           for (unsigned i = 0; i < 2; i++)
           {
             mesh_velocity[i] += this->raw_dnodal_position_dt(l, i) * psif(l);
           }
         }
       }
       // Get the user-defined body force terms
       Vector<double> body_force(3);
       get_body_force_axi_nst(time, ipt, s, interpolated_x, body_force);
       // Get the user-defined source function
       double source = get_source_fct(time, ipt, interpolated_x);
       // Get the user-defined viscosity function
       double visc_ratio;
       get_viscosity_ratio_axisym_nst(ipt, s, interpolated_x, visc_ratio);
       // r is the first position component
       double r = interpolated_x[0];
       // MOMENTUM EQUATIONS
       //------------------
       // Loop over the test functions
       for (unsigned l = 0; l < n_node; l++)
       {
         // FIRST (RADIAL) MOMENTUM EQUATION
         local_eqn = nodal_local_eqn(l, u_nodal_index[0]);
         // If it's not a boundary condition
         if (local_eqn >= 0)
         {
           // Add the user-defined body force terms
           residuals[local_eqn] += r * body_force[0] * testf[l] * W;
           // Add the gravitational body force term
           residuals[local_eqn] += r * scaled_re_inv_fr * testf[l] * G[0] * W;
           // Add the pressure gradient term
           residuals[local_eqn] +=
             interpolated_p * (testf[l] + r * dtestfdx(l, 0)) * W;
           // Add in the stress tensor terms
           // The viscosity ratio needs to go in here to ensure
           // continuity of normal stress is satisfied even in flows
           // with zero pressure gradient!
           residuals[local_eqn] -= visc_ratio * r * (1.0 + Gamma[0]) *
                                   interpolated_dudx(0, 0) * dtestfdx(l, 0) * W;
           residuals[local_eqn] -=
             visc_ratio * r *
             (interpolated_dudx(0, 1) + Gamma[0] * interpolated_dudx(1, 0)) *
             dtestfdx(l, 1) * W;
           residuals[local_eqn] -= visc_ratio * (1.0 + Gamma[0]) *
                                   interpolated_u[0] * testf[l] * W / r;
           // Add in the inertial terms
           // du/dt term
           residuals[local_eqn] -= scaled_re_st * r * dudt[0] * testf[l] * W;
           // Convective terms
           residuals[local_eqn] -=
             scaled_re *
             (r * interpolated_u[0] * interpolated_dudx(0, 0) -
              interpolated_u[2] * interpolated_u[2] +
              r * interpolated_u[1] * interpolated_dudx(0, 1)) *
             testf[l] * W;
           // Mesh velocity terms
           if (!ALE_is_disabled)
           {
             for (unsigned k = 0; k < 2; k++)
             {
               residuals[local_eqn] += scaled_re_st * r * mesh_velocity[k] *
                                       interpolated_dudx(0, k) * testf[l] * W;
             }
           }
           // Add the Coriolis term
           residuals[local_eqn] +=
             2.0 * r * scaled_re_inv_ro * interpolated_u[2] * testf[l] * W;
           // CALCULATE THE JACOBIAN
           if (flag)
           {
             // Loop over the velocity shape functions again
             for (unsigned l2 = 0; l2 < n_node; l2++)
             {
               local_unknown = nodal_local_eqn(l2, u_nodal_index[0]);
               // Radial velocity component
               if (local_unknown >= 0)
               {
                 if (flag == 2)
                 {
                   // Add the mass matrix
                   mass_matrix(local_eqn, local_unknown) +=
                     scaled_re_st * r * psif[l2] * testf[l] * W;
                 }
                 // Add contribution to the Jacobian matrix
                 jacobian(local_eqn, local_unknown) -=
                   visc_ratio * r * (1.0 + Gamma[0]) * dpsifdx(l2, 0) *
                   dtestfdx(l, 0) * W;
                 jacobian(local_eqn, local_unknown) -=
                   visc_ratio * r * dpsifdx(l2, 1) * dtestfdx(l, 1) * W;
                 jacobian(local_eqn, local_unknown) -=
                   visc_ratio * (1.0 + Gamma[0]) * psif[l2] * testf[l] * W / r;
                 // Add in the inertial terms
                 // du/dt term
                 jacobian(local_eqn, local_unknown) -=
                   scaled_re_st * r *
                   node_pt(l2)->time_stepper_pt()->weight(1, 0) * psif[l2] *
                   testf[l] * W;
                 // Convective terms
                 jacobian(local_eqn, local_unknown) -=
                   scaled_re *
                   (r * psif[l2] * interpolated_dudx(0, 0) +
                    r * interpolated_u[0] * dpsifdx(l2, 0) +
                    r * interpolated_u[1] * dpsifdx(l2, 1)) *
                   testf[l] * W;
                 // Mesh velocity terms
                 if (!ALE_is_disabled)
                 {
                   for (unsigned k = 0; k < 2; k++)
                   {
                     jacobian(local_eqn, local_unknown) +=
                       scaled_re_st * r * mesh_velocity[k] * dpsifdx(l2, k) *
                       testf[l] * W;
                   }
                 }
               }
               // Axial velocity component
               local_unknown = nodal_local_eqn(l2, u_nodal_index[1]);
               if (local_unknown >= 0)
               {
                 jacobian(local_eqn, local_unknown) -=
                   visc_ratio * r * Gamma[0] * dpsifdx(l2, 0) * dtestfdx(l, 1) *
                   W;
                 // Convective terms
                 jacobian(local_eqn, local_unknown) -= scaled_re * r * psif[l2] *
                                                       interpolated_dudx(0, 1) *
                                                       testf[l] * W;
               }
               // Azimuthal velocity component
               local_unknown = nodal_local_eqn(l2, u_nodal_index[2]);
               if (local_unknown >= 0)
               {
                 // Convective terms
                 jacobian(local_eqn, local_unknown) -= -scaled_re * 2.0 *
                                                       interpolated_u[2] *
                                                       psif[l2] * testf[l] * W;
                 // Coriolis terms
                 jacobian(local_eqn, local_unknown) +=
                   2.0 * r * scaled_re_inv_ro * psif[l2] * testf[l] * W;
               }
             }
             /*Now loop over pressure shape functions*/
             /*This is the contribution from pressure gradient*/
             for (unsigned l2 = 0; l2 < n_pres; l2++)
             {
               local_unknown = p_local_eqn(l2);
               /*If we are at a non-zero degree of freedom in the entry*/
               if (local_unknown >= 0)
               {
                 jacobian(local_eqn, local_unknown) +=
                   psip[l2] * (testf[l] + r * dtestfdx(l, 0)) * W;
               }
             }
           } /*End of Jacobian calculation*/
         } // End of if not boundary condition statement
         // SECOND (AXIAL) MOMENTUM EQUATION
         local_eqn = nodal_local_eqn(l, u_nodal_index[1]);
         // If it's not a boundary condition
         if (local_eqn >= 0)
         {
           // Add the user-defined body force terms
           // Remember to multiply by the density ratio!
           residuals[local_eqn] += r * body_force[1] * testf[l] * W;
           // Add the gravitational body force term
           residuals[local_eqn] += r * scaled_re_inv_fr * testf[l] * G[1] * W;
           // Add the pressure gradient term
           residuals[local_eqn] += r * interpolated_p * dtestfdx(l, 1) * W;
           // Add in the stress tensor terms
           // The viscosity ratio needs to go in here to ensure
           // continuity of normal stress is satisfied even in flows
           // with zero pressure gradient!
           residuals[local_eqn] -=
             visc_ratio * r *
             (interpolated_dudx(1, 0) + Gamma[1] * interpolated_dudx(0, 1)) *
             dtestfdx(l, 0) * W;
           residuals[local_eqn] -= visc_ratio * r * (1.0 + Gamma[1]) *
                                   interpolated_dudx(1, 1) * dtestfdx(l, 1) * W;
           // Add in the inertial terms
           // du/dt term
           residuals[local_eqn] -= scaled_re_st * r * dudt[1] * testf[l] * W;
           // Convective terms
           residuals[local_eqn] -=
             scaled_re *
             (r * interpolated_u[0] * interpolated_dudx(1, 0) +
              r * interpolated_u[1] * interpolated_dudx(1, 1)) *
             testf[l] * W;
           // Mesh velocity terms
           if (!ALE_is_disabled)
           {
             for (unsigned k = 0; k < 2; k++)
             {
               residuals[local_eqn] += scaled_re_st * r * mesh_velocity[k] *
                                       interpolated_dudx(1, k) * testf[l] * W;
             }
           }
           // CALCULATE THE JACOBIAN
           if (flag)
           {
             // Loop over the velocity shape functions again
             for (unsigned l2 = 0; l2 < n_node; l2++)
             {
               local_unknown = nodal_local_eqn(l2, u_nodal_index[0]);
               // Radial velocity component
               if (local_unknown >= 0)
               {
                 // Add in the stress tensor terms
                 // The viscosity ratio needs to go in here to ensure
                 // continuity of normal stress is satisfied even in flows
                 // with zero pressure gradient!
                 jacobian(local_eqn, local_unknown) -=
                   visc_ratio * r * Gamma[1] * dpsifdx(l2, 1) * dtestfdx(l, 0) *
                   W;
                 // Convective terms
                 jacobian(local_eqn, local_unknown) -= scaled_re * r * psif[l2] *
                                                       interpolated_dudx(1, 0) *
                                                       testf[l] * W;
               }
               // Axial velocity component
               local_unknown = nodal_local_eqn(l2, u_nodal_index[1]);
               if (local_unknown >= 0)
               {
                 if (flag == 2)
                 {
                   // Add the mass matrix
                   mass_matrix(local_eqn, local_unknown) +=
                     scaled_re_st * r * psif[l2] * testf[l] * W;
                 }
                 // Add in the stress tensor terms
                 // The viscosity ratio needs to go in here to ensure
                 // continuity of normal stress is satisfied even in flows
                 // with zero pressure gradient!
                 jacobian(local_eqn, local_unknown) -=
                   visc_ratio * r * dpsifdx(l2, 0) * dtestfdx(l, 0) * W;
                 jacobian(local_eqn, local_unknown) -=
                   visc_ratio * r * (1.0 + Gamma[1]) * dpsifdx(l2, 1) *
                   dtestfdx(l, 1) * W;
                 // Add in the inertial terms
                 // du/dt term
                 jacobian(local_eqn, local_unknown) -=
                   scaled_re_st * r *
                   node_pt(l2)->time_stepper_pt()->weight(1, 0) * psif[l2] *
                   testf[l] * W;
                 // Convective terms
                 jacobian(local_eqn, local_unknown) -=
                   scaled_re *
                   (r * interpolated_u[0] * dpsifdx(l2, 0) +
                    r * psif[l2] * interpolated_dudx(1, 1) +
                    r * interpolated_u[1] * dpsifdx(l2, 1)) *
                   testf[l] * W;
                 // Mesh velocity terms
                 if (!ALE_is_disabled)
                 {
                   for (unsigned k = 0; k < 2; k++)
                   {
                     jacobian(local_eqn, local_unknown) +=
                       scaled_re_st * r * mesh_velocity[k] * dpsifdx(l2, k) *
                       testf[l] * W;
                   }
                 }
               }
               // There are no azimithal terms in the axial momentum equation
             } // End of loop over velocity shape functions
             /*Now loop over pressure shape functions*/
             /*This is the contribution from pressure gradient*/
             for (unsigned l2 = 0; l2 < n_pres; l2++)
             {
               local_unknown = p_local_eqn(l2);
               /*If we are at a non-zero degree of freedom in the entry*/
               if (local_unknown >= 0)
               {
                 jacobian(local_eqn, local_unknown) +=
                   r * psip[l2] * dtestfdx(l, 1) * W;
               }
             }
           } /*End of Jacobian calculation*/
         } // End of AXIAL MOMENTUM EQUATION
         // THIRD (AZIMUTHAL) MOMENTUM EQUATION
         local_eqn = nodal_local_eqn(l, u_nodal_index[2]);
         if (local_eqn >= 0)
         {
           // Add the user-defined body force terms
           // Remember to multiply by the density ratio!
           residuals[local_eqn] += r * body_force[2] * testf[l] * W;
           // Add the gravitational body force term
           residuals[local_eqn] += r * scaled_re_inv_fr * testf[l] * G[2] * W;
           // There is NO pressure gradient term
           // Add in the stress tensor terms
           // The viscosity ratio needs to go in here to ensure
           // continuity of normal stress is satisfied even in flows
           // with zero pressure gradient!
           residuals[local_eqn] -=
             visc_ratio *
             (r * interpolated_dudx(2, 0) - Gamma[0] * interpolated_u[2]) *
             dtestfdx(l, 0) * W;
           residuals[local_eqn] -=
             visc_ratio * r * interpolated_dudx(2, 1) * dtestfdx(l, 1) * W;
           residuals[local_eqn] -=
             visc_ratio *
             ((interpolated_u[2] / r) - Gamma[0] * interpolated_dudx(2, 0)) *
             testf[l] * W;
           // Add in the inertial terms
           // du/dt term
           residuals[local_eqn] -= scaled_re_st * r * dudt[2] * testf[l] * W;
           // Convective terms
           residuals[local_eqn] -=
             scaled_re *
             (r * interpolated_u[0] * interpolated_dudx(2, 0) +
              interpolated_u[0] * interpolated_u[2] +
              r * interpolated_u[1] * interpolated_dudx(2, 1)) *
             testf[l] * W;
           // Mesh velocity terms
           if (!ALE_is_disabled)
           {
             for (unsigned k = 0; k < 2; k++)
             {
               residuals[local_eqn] += scaled_re_st * r * mesh_velocity[k] *
                                       interpolated_dudx(2, k) * testf[l] * W;
             }
           }
           // Add the Coriolis term
           residuals[local_eqn] -=
             2.0 * r * scaled_re_inv_ro * interpolated_u[0] * testf[l] * W;
           // CALCULATE THE JACOBIAN
           if (flag)
           {
             // Loop over the velocity shape functions again
             for (unsigned l2 = 0; l2 < n_node; l2++)
             {
               // Radial velocity component
               local_unknown = nodal_local_eqn(l2, u_nodal_index[0]);
               if (local_unknown >= 0)
               {
                 // Convective terms
                 jacobian(local_eqn, local_unknown) -=
                   scaled_re *
                   (r * psif[l2] * interpolated_dudx(2, 0) +
                    psif[l2] * interpolated_u[2]) *
                   testf[l] * W;
                 // Coriolis term
                 jacobian(local_eqn, local_unknown) -=
                   2.0 * r * scaled_re_inv_ro * psif[l2] * testf[l] * W;
               }
               // Axial velocity component
               local_unknown = nodal_local_eqn(l2, u_nodal_index[1]);
               if (local_unknown >= 0)
               {
                 // Convective terms
                 jacobian(local_eqn, local_unknown) -= scaled_re * r * psif[l2] *
                                                       interpolated_dudx(2, 1) *
                                                       testf[l] * W;
               }
               // Azimuthal velocity component
               local_unknown = nodal_local_eqn(l2, u_nodal_index[2]);
               if (local_unknown >= 0)
               {
                 if (flag == 2)
                 {
                   // Add the mass matrix
                   mass_matrix(local_eqn, local_unknown) +=
                     scaled_re_st * r * psif[l2] * testf[l] * W;
                 }
                 // Add in the stress tensor terms
                 // The viscosity ratio needs to go in here to ensure
                 // continuity of normal stress is satisfied even in flows
                 // with zero pressure gradient!
                 jacobian(local_eqn, local_unknown) -=
                   visc_ratio * (r * dpsifdx(l2, 0) - Gamma[0] * psif[l2]) *
                   dtestfdx(l, 0) * W;
                 jacobian(local_eqn, local_unknown) -=
                   visc_ratio * r * dpsifdx(l2, 1) * dtestfdx(l, 1) * W;
                 jacobian(local_eqn, local_unknown) -=
                   visc_ratio * ((psif[l2] / r) - Gamma[0] * dpsifdx(l2, 0)) *
                   testf[l] * W;
                 // Add in the inertial terms
                 // du/dt term
                 jacobian(local_eqn, local_unknown) -=
                   scaled_re_st * r *
                   node_pt(l2)->time_stepper_pt()->weight(1, 0) * psif[l2] *
                   testf[l] * W;
                 // Convective terms
                 jacobian(local_eqn, local_unknown) -=
                   scaled_re *
                   (r * interpolated_u[0] * dpsifdx(l2, 0) +
                    interpolated_u[0] * psif[l2] +
                    r * interpolated_u[1] * dpsifdx(l2, 1)) *
                   testf[l] * W;
                 // Mesh velocity terms
                 if (!ALE_is_disabled)
                 {
                   for (unsigned k = 0; k < 2; k++)
                   {
                     jacobian(local_eqn, local_unknown) +=
                       scaled_re_st * r * mesh_velocity[k] * dpsifdx(l2, k) *
                       testf[l] * W;
                   }
                 }
               }
             }
             // There are no pressure terms
           } // End of Jacobian
         } // End of AZIMUTHAL EQUATION
       } // End of loop over shape functions
       // CONTINUITY EQUATION
       //-------------------
       // Loop over the shape functions
       for (unsigned l = 0; l < n_pres; l++)
       {
         local_eqn = p_local_eqn(l);
         // If not a boundary conditions
         if (local_eqn >= 0)
         {
           // Source term
           residuals[local_eqn] -= r * source * testp[l] * W;
           // Gradient terms
           residuals[local_eqn] +=
             (interpolated_u[0] + r * interpolated_dudx(0, 0) +
              r * interpolated_dudx(1, 1)) *
             testp[l] * W;
           /*CALCULATE THE JACOBIAN*/
           if (flag)
           {
             /*Loop over the velocity shape functions*/
             for (unsigned l2 = 0; l2 < n_node; l2++)
             {
               // Radial velocity component
               local_unknown = nodal_local_eqn(l2, u_nodal_index[0]);
               if (local_unknown >= 0)
               {
                 jacobian(local_eqn, local_unknown) +=
                   (psif[l2] + r * dpsifdx(l2, 0)) * testp[l] * W;
               }
               // Axial velocity component
               local_unknown = nodal_local_eqn(l2, u_nodal_index[1]);
               if (local_unknown >= 0)
               {
                 jacobian(local_eqn, local_unknown) +=
                   r * dpsifdx(l2, 1) * testp[l] * W;
               }
             } /*End of loop over l2*/
           } /*End of Jacobian calculation*/
         } // End of if not boundary condition
       } // End of loop over l
     }
   }
References ALE_is_disabled, Global_Parameters::body_force(), density_ratio(), dshape_and_dtest_eulerian_at_knot_axi_nst(), du_dt_axi_nst(), G, g(), Gamma, get_body_force_axi_nst(), get_source_fct(), get_viscosity_ratio_axisym_nst(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), J, j, k, oomph::Integral::knot(), GlobalParameters::Nintpt, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), npres_axi_nst(), oomph::Integral::nweight(), p_axi_nst(), p_local_eqn(), pshape_axi_nst(), UniformPSDSelfTest::r, oomph::FiniteElement::raw_dnodal_position_dt(), oomph::FiniteElement::raw_nodal_position(), oomph::FiniteElement::raw_nodal_value(), re(), re_invfr(), re_invro(), re_st(), s, TestProblem::source(), oomph::Time::time(), oomph::TimeStepper::time_pt(), oomph::Data::time_stepper_pt(), u_index_axi_nst(), w, oomph::QuadTreeNames::W, oomph::Integral::weight(), and oomph::TimeStepper::weight().
Referenced by fill_in_contribution_to_jacobian(), fill_in_contribution_to_jacobian_and_mass_matrix(), and fill_in_contribution_to_residuals().
g()
const Vector<double>& oomph::AxisymmetricNavierStokesEquations::g () const inline
Vector of gravitational components.
     {
       return *G_pt;
     }
References G_pt.
Referenced by fill_in_contribution_to_hessian_vector_products(), fill_in_generic_dresidual_contribution_axi_nst(), fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::fill_in_off_diagonal_jacobian_blocks_analytic(), RefineableQAxisymCrouzeixRaviartBoussinesqElement::get_body_force_axi_nst(), oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::get_body_force_axi_nst(), QAxisymCrouzeixRaviartElementWithExternalElement::get_body_force_axi_nst(), RefineableQAxisymCrouzeixRaviartBoussinesqElement::get_dbody_force_axi_nst_dexternal_element_data(), QAxisymCrouzeixRaviartElementWithExternalElement::get_dbody_force_axi_nst_dexternal_element_data(), get_dresidual_dnodal_coordinates(), and oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates().
g_pt()
Vector<double>*& oomph::AxisymmetricNavierStokesEquations::g_pt () inline
Pointer to Vector of gravitational components.
     {
       return G_pt;
     }
References G_pt.
Referenced by oomph::RefineableAxisymmetricNavierStokesEquations::further_build().
get_body_force_axi_nst()
virtual void oomph::AxisymmetricNavierStokesEquations::get_body_force_axi_nst (const double & time, const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, Vector< double > & result) inline protected virtual
Calculate the body force fct at a given time and Eulerian position.
Reimplemented in QAxisymCrouzeixRaviartElementWithExternalElement, oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement, QAxisymCrouzeixRaviartElementWithExternalElement, oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement, RefineableQAxisymCrouzeixRaviartBoussinesqElement, and RefineableQAxisymCrouzeixRaviartBoussinesqElement.
     {
       // If the function pointer is zero return zero
       if (Body_force_fct_pt == 0)
       {
         // Loop over dimensions and set body forces to zero
         for (unsigned i = 0; i < 3; i++)
         {
           result[i] = 0.0;
         }
       }
       // Otherwise call the function
       else
       {
         (*Body_force_fct_pt)(time, x, result);
       }
     }
References Body_force_fct_pt, i, and plotDoE::x.
Referenced by fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), get_body_force_gradient_axi_nst(), get_dresidual_dnodal_coordinates(), and oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates().
get_body_force_gradient_axi_nst()
virtual void oomph::AxisymmetricNavierStokesEquations::get_body_force_gradient_axi_nst (const double & time, const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, DenseMatrix< double > & d_body_force_dx) inline protected virtual
Get gradient of body force term at (Eulerian) position x. Computed via function pointer (if set) or by finite differencing (default)
     {
       // hierher: Implement function pointer version
       /*    //If no gradient function has been set, FD it */
       /*    if(Body_force_fct_gradient_pt==0) */
       {
         // Reference value
         Vector<double> body_force(3, 0.0);
         get_body_force_axi_nst(time, ipt, s, x, body_force);
         // FD it
         const double eps_fd = GeneralisedElement::Default_fd_jacobian_step;
         Vector<double> body_force_pls(3, 0.0);
         Vector<double> x_pls(x);
         for (unsigned i = 0; i < 2; i++)
         {
           x_pls[i] += eps_fd;
           get_body_force_axi_nst(time, ipt, s, x_pls, body_force_pls);
           for (unsigned j = 0; j < 3; j++)
           {
             d_body_force_dx(j, i) =
               (body_force_pls[j] - body_force[j]) / eps_fd;
           }
           x_pls[i] = x[i];
         }
       }
       /*    else */
       /*     { */
       /*      // Get gradient */
       /*      (*Source_fct_gradient_pt)(time,x,gradient); */
       /*     } */
     }
References Global_Parameters::body_force(), oomph::GeneralisedElement::Default_fd_jacobian_step, get_body_force_axi_nst(), i, j, s, and plotDoE::x.
Referenced by get_dresidual_dnodal_coordinates(), and oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates().
get_dresidual_dnodal_coordinates()
void oomph::AxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates (RankThreeTensor< double > & dresidual_dnodal_coordinates) virtual
Compute derivatives of elemental residual vector with respect to nodal coordinates. This function computes these terms analytically and overwrites the default implementation in the FiniteElement base class. dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij}
Compute derivatives of elemental residual vector with respect to nodal coordinates. dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij} Overloads the FD-based version in the FiniteElement base class.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::RefineableAxisymmetricNavierStokesEquations.
   {
     // Return immediately if there are no dofs
     if (ndof() == 0)
     {
       return;
     }
     // Get continuous time from timestepper of first node
     double time = node_pt(0)->time_stepper_pt()->time_pt()->time();
     // Determine number of nodes in element
     const unsigned n_node = nnode();
     // Determine number of pressure dofs in element
     const unsigned n_pres = npres_axi_nst();
     // Find the indices at which the local velocities are stored
     unsigned u_nodal_index[3];
     for (unsigned i = 0; i < 3; i++)
     {
       u_nodal_index[i] = u_index_axi_nst(i);
     }
     // Set up memory for the shape and test functions
     // Note that there are only two dimensions, r and z, in this problem
     Shape psif(n_node), testf(n_node);
     DShape dpsifdx(n_node, 2), dtestfdx(n_node, 2);
     // Set up memory for pressure shape and test functions
     Shape psip(n_pres), testp(n_pres);
     // Deriatives of shape fct derivatives w.r.t. nodal coords
     RankFourTensor<double> d_dpsifdx_dX(2, n_node, n_node, 2);
     RankFourTensor<double> d_dtestfdx_dX(2, n_node, n_node, 2);
     // Derivative of Jacobian of mapping w.r.t. to nodal coords
     DenseMatrix<double> dJ_dX(2, n_node);
     // Derivatives of derivative of u w.r.t. nodal coords
     // Note that the entry d_dudx_dX(p,q,i,k) contains the derivative w.r.t.
     // nodal coordinate X_pq of du_i/dx_k. Since there are three velocity
     // components, i can take on the values 0, 1 and 2, while k and p only
     // take on the values 0 and 1 since there are only two spatial dimensions.
     RankFourTensor<double> d_dudx_dX(2, n_node, 3, 2);
     // Derivatives of nodal velocities w.r.t. nodal coords:
     // Assumption: Interaction only local via no-slip so
     // X_pq only affects U_iq.
     // Note that the entry d_U_dX(p,q,i) contains the derivative w.r.t. nodal
     // coordinate X_pq of nodal value U_iq. In other words this entry is the
     // derivative of the i-th velocity component w.r.t. the p-th spatial
     // coordinate, taken at the q-th local node.
     RankThreeTensor<double> d_U_dX(2, n_node, 3, 0.0);
     // Determine the number of integration points
     const unsigned n_intpt = integral_pt()->nweight();
     // Vector to hold local coordinates (two dimensions)
     Vector<double> s(2);
     // Get physical variables from element
     // (Reynolds number must be multiplied by the density ratio)
     const double scaled_re = re() * density_ratio();
     const double scaled_re_st = re_st() * density_ratio();
     const double scaled_re_inv_fr = re_invfr() * density_ratio();
     const double scaled_re_inv_ro = re_invro() * density_ratio();
     const double visc_ratio = viscosity_ratio();
     const Vector<double> G = g();
     // FD step
     double eps_fd = GeneralisedElement::Default_fd_jacobian_step;
     // Pre-compute derivatives of nodal velocities w.r.t. nodal coords:
     // Assumption: Interaction only local via no-slip so
     // X_ij only affects U_ij.
     bool element_has_node_with_aux_node_update_fct = false;
     for (unsigned q = 0; q < n_node; q++)
     {
       // Get pointer to q-th local node
       Node* nod_pt = node_pt(q);
       // Only compute if there's a node-update fct involved
       if (nod_pt->has_auxiliary_node_update_fct_pt())
       {
         element_has_node_with_aux_node_update_fct = true;
         // This functionality has not been tested so issue a warning
         // to this effect
         std::ostringstream warning_stream;
         warning_stream << "\nThe functionality to evaluate the additional"
                        << "\ncontribution to the deriv of the residual eqn"
                        << "\nw.r.t. the nodal coordinates which comes about"
                        << "\nif a node's values are updated using an auxiliary"
                        << "\nnode update function has NOT been tested for"
                        << "\naxisymmetric Navier-Stokes elements. Use at your"
                        << "\nown risk" << std::endl;
         OomphLibWarning(
           warning_stream.str(),
           "AxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates",
           OOMPH_EXCEPTION_LOCATION);
         // Current nodal velocity
         Vector<double> u_ref(3);
         for (unsigned i = 0; i < 3; i++)
         {
           u_ref[i] = *(nod_pt->value_pt(u_nodal_index[i]));
         }
         // FD
         for (unsigned p = 0; p < 2; p++)
         {
           // Make backup
           double backup = nod_pt->x(p);
           // Do FD step. No node update required as we're
           // attacking the coordinate directly...
           nod_pt->x(p) += eps_fd;
           // Do auxiliary node update (to apply no slip)
           nod_pt->perform_auxiliary_node_update_fct();
           // Loop over velocity components
           for (unsigned i = 0; i < 3; i++)
           {
             // Evaluate
             d_U_dX(p, q, i) =
               (*(nod_pt->value_pt(u_nodal_index[i])) - u_ref[i]) / eps_fd;
           }
           // Reset
           nod_pt->x(p) = backup;
           // Do auxiliary node update (to apply no slip)
           nod_pt->perform_auxiliary_node_update_fct();
         }
       }
     }
     // Integer to store the local equation number
     int local_eqn = 0;
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Assign values of s
       for (unsigned i = 0; i < 2; i++)
       {
         s[i] = integral_pt()->knot(ipt, i);
       }
       // Get the integral weight
       const double w = integral_pt()->weight(ipt);
       // Call the derivatives of the shape and test functions
       const double J = dshape_and_dtest_eulerian_at_knot_axi_nst(ipt,
                                                                  psif,
                                                                  dpsifdx,
                                                                  d_dpsifdx_dX,
                                                                  testf,
                                                                  dtestfdx,
                                                                  d_dtestfdx_dX,
                                                                  dJ_dX);
       // Call the pressure shape and test functions
       pshape_axi_nst(s, psip, testp);
       // Allocate storage for the position and the derivative of the
       // mesh positions w.r.t. time
       Vector<double> interpolated_x(2, 0.0);
       Vector<double> mesh_velocity(2, 0.0);
       // Allocate storage for the pressure, velocity components and their
       // time and spatial derivatives
       double interpolated_p = 0.0;
       Vector<double> interpolated_u(3, 0.0);
       Vector<double> dudt(3, 0.0);
       DenseMatrix<double> interpolated_dudx(3, 2, 0.0);
       // Calculate pressure at integration point
       for (unsigned l = 0; l < n_pres; l++)
       {
         interpolated_p += p_axi_nst(l) * psip[l];
       }
       // Calculate velocities and derivatives at integration point
       // ---------------------------------------------------------
       // Loop over nodes
       for (unsigned l = 0; l < n_node; l++)
       {
         // Cache the shape function
         const double psif_ = psif(l);
         // Loop over the two coordinate directions
         for (unsigned i = 0; i < 2; i++)
         {
           interpolated_x[i] += this->raw_nodal_position(l, i) * psif_;
         }
         // Loop over the three velocity directions
         for (unsigned i = 0; i < 3; i++)
         {
           // Get the nodal value
           const double u_value = this->raw_nodal_value(l, u_nodal_index[i]);
           interpolated_u[i] += u_value * psif_;
           dudt[i] += du_dt_axi_nst(l, i) * psif_;
           // Loop over derivative directions
           for (unsigned j = 0; j < 2; j++)
           {
             interpolated_dudx(i, j) += u_value * dpsifdx(l, j);
           }
         }
       }
       // Get the mesh velocity if ALE is enabled
       if (!ALE_is_disabled)
       {
         // Loop over nodes
         for (unsigned l = 0; l < n_node; l++)
         {
           // Loop over the two coordinate directions
           for (unsigned i = 0; i < 2; i++)
           {
             mesh_velocity[i] += this->raw_dnodal_position_dt(l, i) * psif[l];
           }
         }
       }
       // Calculate derivative of du_i/dx_k w.r.t. nodal positions X_{pq}
       for (unsigned q = 0; q < n_node; q++)
       {
         // Loop over the two coordinate directions
         for (unsigned p = 0; p < 2; p++)
         {
           // Loop over the three velocity components
           for (unsigned i = 0; i < 3; i++)
           {
             // Loop over the two coordinate directions
             for (unsigned k = 0; k < 2; k++)
             {
               double aux = 0.0;
               // Loop over nodes and add contribution
               for (unsigned j = 0; j < n_node; j++)
               {
                 aux += this->raw_nodal_value(j, u_nodal_index[i]) *
                        d_dpsifdx_dX(p, q, j, k);
               }
               d_dudx_dX(p, q, i, k) = aux;
             }
           }
         }
       }
       // Get weight of actual nodal position/value in computation of mesh
       // velocity from positional/value time stepper
       const double pos_time_weight =
         node_pt(0)->position_time_stepper_pt()->weight(1, 0);
       const double val_time_weight =
         node_pt(0)->time_stepper_pt()->weight(1, 0);
       // Get the user-defined body force terms
       Vector<double> body_force(3);
       get_body_force_axi_nst(time, ipt, s, interpolated_x, body_force);
       // Get the user-defined source function
       const double source = get_source_fct(time, ipt, interpolated_x);
       // Note: Can use raw values and avoid bypassing hanging information
       // because this is the non-refineable version!
       // Get gradient of body force function
       DenseMatrix<double> d_body_force_dx(3, 2, 0.0);
       get_body_force_gradient_axi_nst(
         time, ipt, s, interpolated_x, d_body_force_dx);
       // Get gradient of source function
       Vector<double> source_gradient(2, 0.0);
       get_source_fct_gradient(time, ipt, interpolated_x, source_gradient);
       // Cache r (the first position component)
       const double r = interpolated_x[0];
       // Assemble shape derivatives
       // --------------------------
       // ==================
       // MOMENTUM EQUATIONS
       // ==================
       // Loop over the test functions
       for (unsigned l = 0; l < n_node; l++)
       {
         // Cache the test function
         const double testf_ = testf[l];
         // --------------------------------
         // FIRST (RADIAL) MOMENTUM EQUATION
         // --------------------------------
         local_eqn = nodal_local_eqn(l, u_nodal_index[0]);
         ;
         // If it's not a boundary condition
         if (local_eqn >= 0)
         {
           // Loop over the two coordinate directions
           for (unsigned p = 0; p < 2; p++)
           {
             // Loop over nodes
             for (unsigned q = 0; q < n_node; q++)
             {
               // Residual x deriv of Jacobian
               // ----------------------------
               // Add the user-defined body force terms
               double sum = r * body_force[0] * testf_;
               // Add the gravitational body force term
               sum += r * scaled_re_inv_fr * testf_ * G[0];
               // Add the pressure gradient term
               sum += interpolated_p * (testf_ + r * dtestfdx(l, 0));
               // Add the stress tensor terms
               // The viscosity ratio needs to go in here to ensure
               // continuity of normal stress is satisfied even in flows
               // with zero pressure gradient!
               sum -= visc_ratio * r * (1.0 + Gamma[0]) *
                      interpolated_dudx(0, 0) * dtestfdx(l, 0);
               sum -=
                 visc_ratio * r *
                 (interpolated_dudx(0, 1) + Gamma[0] * interpolated_dudx(1, 0)) *
                 dtestfdx(l, 1);
               sum -=
                 visc_ratio * (1.0 + Gamma[0]) * interpolated_u[0] * testf_ / r;
               // Add the du/dt term
               sum -= scaled_re_st * r * dudt[0] * testf_;
               // Add the convective terms
               sum -= scaled_re *
                      (r * interpolated_u[0] * interpolated_dudx(0, 0) -
                       interpolated_u[2] * interpolated_u[2] +
                       r * interpolated_u[1] * interpolated_dudx(0, 1)) *
                      testf_;
               // Add the mesh velocity terms
               if (!ALE_is_disabled)
               {
                 for (unsigned k = 0; k < 2; k++)
                 {
                   sum += scaled_re_st * r * mesh_velocity[k] *
                          interpolated_dudx(0, k) * testf_;
                 }
               }
               // Add the Coriolis term
               sum += 2.0 * r * scaled_re_inv_ro * interpolated_u[2] * testf_;
               // Multiply through by deriv of Jacobian and integration weight
               dresidual_dnodal_coordinates(local_eqn, p, q) +=
                 sum * dJ_dX(p, q) * w;
               // Derivative of residual x Jacobian
               // ---------------------------------
               // Body force
               sum = r * d_body_force_dx(0, p) * psif[q] * testf_;
               if (p == 0)
               {
                 sum += body_force[0] * psif[q] * testf_;
               }
               // Gravitational body force
               if (p == 0)
               {
                 sum += scaled_re_inv_fr * G[0] * psif[q] * testf_;
               }
               // Pressure gradient term
               sum += r * interpolated_p * d_dtestfdx_dX(p, q, l, 0);
               if (p == 0)
               {
                 sum += interpolated_p * psif[q] * dtestfdx(l, 0);
               }
               // Viscous terms
               sum -=
                 r * visc_ratio *
                 ((1.0 + Gamma[0]) *
                    (d_dudx_dX(p, q, 0, 0) * dtestfdx(l, 0) +
                     interpolated_dudx(0, 0) * d_dtestfdx_dX(p, q, l, 0)) +
                  (d_dudx_dX(p, q, 0, 1) + Gamma[0] * d_dudx_dX(p, q, 1, 0)) *
                    dtestfdx(l, 1) +
                  (interpolated_dudx(0, 1) +
                   Gamma[0] * interpolated_dudx(1, 0)) *
                    d_dtestfdx_dX(p, q, l, 1));
               if (p == 0)
               {
                 sum -= visc_ratio *
                        ((1.0 + Gamma[0]) *
                           (interpolated_dudx(0, 0) * psif[q] * dtestfdx(l, 0) -
                            interpolated_u[0] * psif[q] * testf_ / (r * r)) +
                         (interpolated_dudx(0, 1) +
                          Gamma[0] * interpolated_dudx(1, 0)) *
                           psif[q] * dtestfdx(l, 1));
               }
               // Convective terms, including mesh velocity
               for (unsigned k = 0; k < 2; k++)
               {
                 double tmp = scaled_re * interpolated_u[k];
                 if (!ALE_is_disabled)
                 {
                   tmp -= scaled_re_st * mesh_velocity[k];
                 }
                 sum -= r * tmp * d_dudx_dX(p, q, 0, k) * testf_;
                 if (p == 0)
                 {
                   sum -= tmp * interpolated_dudx(0, k) * psif[q] * testf_;
                 }
               }
               if (!ALE_is_disabled)
               {
                 sum += scaled_re_st * r * pos_time_weight *
                        interpolated_dudx(0, p) * psif[q] * testf_;
               }
               // du/dt term
               if (p == 0)
               {
                 sum -= scaled_re_st * dudt[0] * psif[q] * testf_;
               }
               // Coriolis term
               if (p == 0)
               {
                 sum +=
                   2.0 * scaled_re_inv_ro * interpolated_u[2] * psif[q] * testf_;
               }
               // Multiply through by Jacobian and integration weight
               dresidual_dnodal_coordinates(local_eqn, p, q) += sum * J * w;
               // Derivs w.r.t. nodal velocities
               // ------------------------------
               if (element_has_node_with_aux_node_update_fct)
               {
                 // Contribution from deriv of first velocity component
                 double tmp =
                   scaled_re_st * r * val_time_weight * psif[q] * testf_;
                 tmp +=
                   r * scaled_re * interpolated_dudx(0, 0) * psif[q] * testf_;
                 for (unsigned k = 0; k < 2; k++)
                 {
                   double tmp2 = scaled_re * interpolated_u[k];
                   if (!ALE_is_disabled)
                   {
                     tmp2 -= scaled_re_st * mesh_velocity[k];
                   }
                   tmp += r * tmp2 * dpsifdx(q, k) * testf_;
                 }
                 tmp += r * visc_ratio * (1.0 + Gamma[0]) * dpsifdx(q, 0) *
                        dtestfdx(l, 0);
                 tmp += r * visc_ratio * dpsifdx(q, 1) * dtestfdx(l, 1);
                 tmp += visc_ratio * (1.0 + Gamma[0]) * psif[q] * testf_ / r;
                 // Multiply through by dU_0q/dX_pq
                 sum = -d_U_dX(p, q, 0) * tmp;
                 // Contribution from deriv of second velocity component
                 tmp =
                   scaled_re * r * interpolated_dudx(0, 1) * psif[q] * testf_;
                 tmp +=
                   r * visc_ratio * Gamma[0] * dpsifdx(q, 0) * dtestfdx(l, 1);
                 // Multiply through by dU_1q/dX_pq
                 sum -= d_U_dX(p, q, 1) * tmp;
                 // Contribution from deriv of third velocity component
                 tmp = 2.0 *
                       (r * scaled_re_inv_ro + scaled_re * interpolated_u[2]) *
                       psif[q] * testf_;
                 // Multiply through by dU_2q/dX_pq
                 sum += d_U_dX(p, q, 2) * tmp;
                 // Multiply through by Jacobian and integration weight
                 dresidual_dnodal_coordinates(local_eqn, p, q) += sum * J * w;
               }
             } // End of loop over q
           } // End of loop over p
         } // End of if it's not a boundary condition
         // --------------------------------
         // SECOND (AXIAL) MOMENTUM EQUATION
         // --------------------------------
         local_eqn = nodal_local_eqn(l, u_nodal_index[1]);
         ;
         // If it's not a boundary condition
         if (local_eqn >= 0)
         {
           // Loop over the two coordinate directions
           for (unsigned p = 0; p < 2; p++)
           {
             // Loop over nodes
             for (unsigned q = 0; q < n_node; q++)
             {
               // Residual x deriv of Jacobian
               // ----------------------------
               // Add the user-defined body force terms
               double sum = r * body_force[1] * testf_;
               // Add the gravitational body force term
               sum += r * scaled_re_inv_fr * testf_ * G[1];
               // Add the pressure gradient term
               sum += r * interpolated_p * dtestfdx(l, 1);
               // Add the stress tensor terms
               // The viscosity ratio needs to go in here to ensure
               // continuity of normal stress is satisfied even in flows
               // with zero pressure gradient!
               sum -=
                 visc_ratio * r *
                 (interpolated_dudx(1, 0) + Gamma[1] * interpolated_dudx(0, 1)) *
                 dtestfdx(l, 0);
               sum -= visc_ratio * r * (1.0 + Gamma[1]) *
                      interpolated_dudx(1, 1) * dtestfdx(l, 1);
               // Add the du/dt term
               sum -= scaled_re_st * r * dudt[1] * testf_;
               // Add the convective terms
               sum -= scaled_re *
                      (r * interpolated_u[0] * interpolated_dudx(1, 0) +
                       r * interpolated_u[1] * interpolated_dudx(1, 1)) *
                      testf_;
               // Add the mesh velocity terms
               if (!ALE_is_disabled)
               {
                 for (unsigned k = 0; k < 2; k++)
                 {
                   sum += scaled_re_st * r * mesh_velocity[k] *
                          interpolated_dudx(1, k) * testf_;
                 }
               }
               // Multiply through by deriv of Jacobian and integration weight
               dresidual_dnodal_coordinates(local_eqn, p, q) +=
                 sum * dJ_dX(p, q) * w;
               // Derivative of residual x Jacobian
               // ---------------------------------
               // Body force
               sum = r * d_body_force_dx(1, p) * psif[q] * testf_;
               if (p == 0)
               {
                 sum += body_force[1] * psif[q] * testf_;
               }
               // Gravitational body force
               if (p == 0)
               {
                 sum += scaled_re_inv_fr * G[1] * psif[q] * testf_;
               }
               // Pressure gradient term
               sum += r * interpolated_p * d_dtestfdx_dX(p, q, l, 1);
               if (p == 0)
               {
                 sum += interpolated_p * psif[q] * dtestfdx(l, 1);
               }
               // Viscous terms
               sum -=
                 r * visc_ratio *
                 ((d_dudx_dX(p, q, 1, 0) + Gamma[1] * d_dudx_dX(p, q, 0, 1)) *
                    dtestfdx(l, 0) +
                  (interpolated_dudx(1, 0) +
                   Gamma[1] * interpolated_dudx(0, 1)) *
                    d_dtestfdx_dX(p, q, l, 0) +
                  (1.0 + Gamma[1]) * d_dudx_dX(p, q, 1, 1) * dtestfdx(l, 1) +
                  (1.0 + Gamma[1]) * interpolated_dudx(1, 1) *
                    d_dtestfdx_dX(p, q, l, 1));
               if (p == 0)
               {
                 sum -=
                   visc_ratio * ((interpolated_dudx(1, 0) +
                                  Gamma[1] * interpolated_dudx(0, 1)) *
                                   psif[q] * dtestfdx(l, 0) +
                                 (1.0 + Gamma[1]) * interpolated_dudx(1, 1) *
                                   psif[q] * dtestfdx(l, 1));
               }
               // Convective terms, including mesh velocity
               for (unsigned k = 0; k < 2; k++)
               {
                 double tmp = scaled_re * interpolated_u[k];
                 if (!ALE_is_disabled)
                 {
                   tmp -= scaled_re_st * mesh_velocity[k];
                 }
                 sum -= r * tmp * d_dudx_dX(p, q, 1, k) * testf_;
                 if (p == 0)
                 {
                   sum -= tmp * interpolated_dudx(1, k) * psif[q] * testf_;
                 }
               }
               if (!ALE_is_disabled)
               {
                 sum += scaled_re_st * r * pos_time_weight *
                        interpolated_dudx(1, p) * psif[q] * testf_;
               }
               // du/dt term
               if (p == 0)
               {
                 sum -= scaled_re_st * dudt[1] * psif[q] * testf_;
               }
               // Multiply through by Jacobian and integration weight
               dresidual_dnodal_coordinates(local_eqn, p, q) += sum * J * w;
               // Derivs w.r.t. to nodal velocities
               // ---------------------------------
               if (element_has_node_with_aux_node_update_fct)
               {
                 // Contribution from deriv of first velocity component
                 double tmp =
                   scaled_re * r * interpolated_dudx(1, 0) * psif[q] * testf_;
                 tmp +=
                   r * visc_ratio * Gamma[1] * dpsifdx(q, 1) * dtestfdx(l, 0);
                 // Multiply through by dU_0q/dX_pq
                 sum = -d_U_dX(p, q, 0) * tmp;
                 // Contribution from deriv of second velocity component
                 tmp = scaled_re_st * r * val_time_weight * psif[q] * testf_;
                 tmp +=
                   r * scaled_re * interpolated_dudx(1, 1) * psif[q] * testf_;
                 for (unsigned k = 0; k < 2; k++)
                 {
                   double tmp2 = scaled_re * interpolated_u[k];
                   if (!ALE_is_disabled)
                   {
                     tmp2 -= scaled_re_st * mesh_velocity[k];
                   }
                   tmp += r * tmp2 * dpsifdx(q, k) * testf_;
                 }
                 tmp += r * visc_ratio *
                        (dpsifdx(q, 0) * dtestfdx(l, 0) +
                         (1.0 + Gamma[1]) * dpsifdx(q, 1) * dtestfdx(l, 1));
                 // Multiply through by dU_1q/dX_pq
                 sum -= d_U_dX(p, q, 1) * tmp;
                 // Multiply through by Jacobian and integration weight
                 dresidual_dnodal_coordinates(local_eqn, p, q) += sum * J * w;
               }
             } // End of loop over q
           } // End of loop over p
         } // End of if it's not a boundary condition
         // -----------------------------------
         // THIRD (AZIMUTHAL) MOMENTUM EQUATION
         // -----------------------------------
         local_eqn = nodal_local_eqn(l, u_nodal_index[2]);
         ;
         // If it's not a boundary condition
         if (local_eqn >= 0)
         {
           // Loop over the two coordinate directions
           for (unsigned p = 0; p < 2; p++)
           {
             // Loop over nodes
             for (unsigned q = 0; q < n_node; q++)
             {
               // Residual x deriv of Jacobian
               // ----------------------------
               // Add the user-defined body force terms
               double sum = r * body_force[2] * testf_;
               // Add the gravitational body force term
               sum += r * scaled_re_inv_fr * testf_ * G[2];
               // There is NO pressure gradient term
               // Add in the stress tensor terms
               // The viscosity ratio needs to go in here to ensure
               // continuity of normal stress is satisfied even in flows
               // with zero pressure gradient!
               sum -=
                 visc_ratio *
                 (r * interpolated_dudx(2, 0) - Gamma[0] * interpolated_u[2]) *
                 dtestfdx(l, 0);
               sum -= visc_ratio * r * interpolated_dudx(2, 1) * dtestfdx(l, 1);
               sum -=
                 visc_ratio *
                 ((interpolated_u[2] / r) - Gamma[0] * interpolated_dudx(2, 0)) *
                 testf_;
               // Add the du/dt term
               sum -= scaled_re_st * r * dudt[2] * testf_;
               // Add the convective terms
               sum -= scaled_re *
                      (r * interpolated_u[0] * interpolated_dudx(2, 0) +
                       interpolated_u[0] * interpolated_u[2] +
                       r * interpolated_u[1] * interpolated_dudx(2, 1)) *
                      testf_;
               // Add the mesh velocity terms
               if (!ALE_is_disabled)
               {
                 for (unsigned k = 0; k < 2; k++)
                 {
                   sum += scaled_re_st * r * mesh_velocity[k] *
                          interpolated_dudx(2, k) * testf_;
                 }
               }
               // Add the Coriolis term
               sum -= 2.0 * r * scaled_re_inv_ro * interpolated_u[0] * testf_;
               // Multiply through by deriv of Jacobian and integration weight
               dresidual_dnodal_coordinates(local_eqn, p, q) +=
                 sum * dJ_dX(p, q) * w;
               // Derivative of residual x Jacobian
               // ---------------------------------
               // Body force
               sum = r * d_body_force_dx(2, p) * psif[q] * testf_;
               if (p == 0)
               {
                 sum += body_force[2] * psif[q] * testf_;
               }
               // Gravitational body force
               if (p == 0)
               {
                 sum += scaled_re_inv_fr * G[2] * psif[q] * testf_;
               }
               // There is NO pressure gradient term
               // Viscous terms
               sum -= visc_ratio * r *
                      (d_dudx_dX(p, q, 2, 0) * dtestfdx(l, 0) +
                       interpolated_dudx(2, 0) * d_dtestfdx_dX(p, q, l, 0) +
                       d_dudx_dX(p, q, 2, 1) * dtestfdx(l, 1) +
                       interpolated_dudx(2, 1) * d_dtestfdx_dX(p, q, l, 1));
               sum += visc_ratio * Gamma[0] * d_dudx_dX(p, q, 2, 0) * testf_;
               if (p == 0)
               {
                 sum -= visc_ratio *
                        (interpolated_dudx(2, 0) * psif[q] * dtestfdx(l, 0) +
                         interpolated_dudx(2, 1) * psif[q] * dtestfdx(l, 1) +
                         interpolated_u[2] * psif[q] * testf_ / (r * r));
               }
               // Convective terms, including mesh velocity
               for (unsigned k = 0; k < 2; k++)
               {
                 double tmp = scaled_re * interpolated_u[k];
                 if (!ALE_is_disabled)
                 {
                   tmp -= scaled_re_st * mesh_velocity[k];
                 }
                 sum -= r * tmp * d_dudx_dX(p, q, 2, k) * testf_;
                 if (p == 0)
                 {
                   sum -= tmp * interpolated_dudx(2, k) * psif[q] * testf_;
                 }
               }
               if (!ALE_is_disabled)
               {
                 sum += scaled_re_st * r * pos_time_weight *
                        interpolated_dudx(2, p) * psif[q] * testf_;
               }
               // du/dt term
               if (p == 0)
               {
                 sum -= scaled_re_st * dudt[2] * psif[q] * testf_;
               }
               // Coriolis term
               if (p == 0)
               {
                 sum -=
                   2.0 * scaled_re_inv_ro * interpolated_u[0] * psif[q] * testf_;
               }
               // Multiply through by Jacobian and integration weight
               dresidual_dnodal_coordinates(local_eqn, p, q) += sum * J * w;
               // Derivs w.r.t. to nodal velocities
               // ---------------------------------
               if (element_has_node_with_aux_node_update_fct)
               {
                 // Contribution from deriv of first velocity component
                 double tmp = (2.0 * r * scaled_re_inv_ro +
                               r * scaled_re * interpolated_dudx(2, 0) -
                               scaled_re * interpolated_u[2]) *
                              psif[q] * testf_;
                 // Multiply through by dU_0q/dX_pq
                 sum = -d_U_dX(p, q, 0) * tmp;
                 // Contribution from deriv of second velocity component
                 // Multiply through by dU_1q/dX_pq
                 sum -= d_U_dX(p, q, 1) * scaled_re * r *
                        interpolated_dudx(2, 1) * psif[q] * testf_;
                 // Contribution from deriv of third velocity component
                 tmp = scaled_re_st * r * val_time_weight * psif[q] * testf_;
                 tmp -= scaled_re * interpolated_u[0] * psif[q] * testf_;
                 for (unsigned k = 0; k < 2; k++)
                 {
                   double tmp2 = scaled_re * interpolated_u[k];
                   if (!ALE_is_disabled)
                   {
                     tmp2 -= scaled_re_st * mesh_velocity[k];
                   }
                   tmp += r * tmp2 * dpsifdx(q, k) * testf_;
                 }
                 tmp += visc_ratio * (r * dpsifdx(q, 0) - Gamma[0] * psif[q]) *
                        dtestfdx(l, 0);
                 tmp += r * visc_ratio * dpsifdx(q, 1) * dtestfdx(l, 1);
                 tmp += visc_ratio * ((psif[q] / r) - Gamma[0] * dpsifdx(q, 0)) *
                        testf_;
                 // Multiply through by dU_2q/dX_pq
                 sum -= d_U_dX(p, q, 2) * tmp;
                 // Multiply through by Jacobian and integration weight
                 dresidual_dnodal_coordinates(local_eqn, p, q) += sum * J * w;
               }
             } // End of loop over q
           } // End of loop over p
         } // End of if it's not a boundary condition
       } // End of loop over test functions
       // ===================
       // CONTINUITY EQUATION
       // ===================
       // Loop over the shape functions
       for (unsigned l = 0; l < n_pres; l++)
       {
         local_eqn = p_local_eqn(l);
         // Cache the test function
         const double testp_ = testp[l];
         // If not a boundary conditions
         if (local_eqn >= 0)
         {
           // Loop over the two coordinate directions
           for (unsigned p = 0; p < 2; p++)
           {
             // Loop over nodes
             for (unsigned q = 0; q < n_node; q++)
             {
               // Residual x deriv of Jacobian
               //-----------------------------
               // Source term
               double aux = -r * source;
               // Gradient terms
               aux += (interpolated_u[0] + r * interpolated_dudx(0, 0) +
                       r * interpolated_dudx(1, 1));
               // Multiply through by deriv of Jacobian and integration weight
               dresidual_dnodal_coordinates(local_eqn, p, q) +=
                 aux * dJ_dX(p, q) * testp_ * w;
               // Derivative of residual x Jacobian
               // ---------------------------------
               // Gradient of source function
               aux = -r * source_gradient[p] * psif[q];
               if (p == 0)
               {
                 aux -= source * psif[q];
               }
               // Gradient terms
               aux += r * (d_dudx_dX(p, q, 0, 0) + d_dudx_dX(p, q, 1, 1));
               if (p == 0)
               {
                 aux +=
                   (interpolated_dudx(0, 0) + interpolated_dudx(1, 1)) * psif[q];
               }
               // Derivs w.r.t. nodal velocities
               // ------------------------------
               if (element_has_node_with_aux_node_update_fct)
               {
                 aux += d_U_dX(p, q, 0) * (psif[q] + r * dpsifdx(q, 0));
                 aux += d_U_dX(p, q, 1) * r * dpsifdx(q, 1);
               }
               // Multiply through by Jacobian, test fct and integration weight
               dresidual_dnodal_coordinates(local_eqn, p, q) +=
                 aux * testp_ * J * w;
             }
           }
         }
       } // End of loop over shape functions for continuity eqn
     } // End of loop over integration points
   }
References ALE_is_disabled, Global_Parameters::body_force(), oomph::GeneralisedElement::Default_fd_jacobian_step, density_ratio(), dshape_and_dtest_eulerian_at_knot_axi_nst(), du_dt_axi_nst(), G, g(), Gamma, get_body_force_axi_nst(), get_body_force_gradient_axi_nst(), get_source_fct(), get_source_fct_gradient(), oomph::Node::has_auxiliary_node_update_fct_pt(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), J, j, k, oomph::Integral::knot(), oomph::GeneralisedElement::ndof(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), npres_axi_nst(), oomph::Integral::nweight(), OOMPH_EXCEPTION_LOCATION, p, p_axi_nst(), p_local_eqn(), oomph::Node::perform_auxiliary_node_update_fct(), oomph::Node::position_time_stepper_pt(), pshape_axi_nst(), Eigen::numext::q, UniformPSDSelfTest::r, oomph::FiniteElement::raw_dnodal_position_dt(), oomph::FiniteElement::raw_nodal_position(), oomph::FiniteElement::raw_nodal_value(), re(), re_invfr(), re_invro(), re_st(), s, TestProblem::source(), oomph::Time::time(), oomph::TimeStepper::time_pt(), oomph::Data::time_stepper_pt(), tmp, u_index_axi_nst(), oomph::Data::value_pt(), viscosity_ratio(), w, oomph::Integral::weight(), oomph::TimeStepper::weight(), and oomph::Node::x().
get_pressure_and_velocity_mass_matrix_diagonal()
void oomph::AxisymmetricNavierStokesEquations::get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > & press_mass_diag, Vector< double > & veloc_mass_diag, const unsigned & which_one = 0) virtual
Compute the diagonal of the velocity/pressure mass matrices. If which one=0, both are computed, otherwise only the pressure (which_one=1) or the velocity mass matrix (which_one=2 – the LSC version of the preconditioner only needs that one) NOTE: pressure versions isn't implemented yet because this element has never been tried with Fp preconditoner.
Implements oomph::NavierStokesElementWithDiagonalMassMatrices.
   {
 #ifdef PARANOID
     if ((which_one == 0) || (which_one == 1))
     {
       throw OomphLibError("Computation of diagonal of pressure mass matrix is "
                           "not impmented yet.\n",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Resize and initialise
     veloc_mass_diag.assign(ndof(), 0.0);
     // find out how many nodes there are
     const unsigned n_node = nnode();
     // find number of coordinates
     const unsigned n_value = 3;
     // find the indices at which the local velocities are stored
     Vector<unsigned> u_nodal_index(n_value);
     for (unsigned i = 0; i < n_value; i++)
     {
       u_nodal_index[i] = this->u_index_axi_nst(i);
     }
     // Set up memory for test functions
     Shape test(n_node);
     // Number of integration points
     unsigned n_intpt = integral_pt()->nweight();
     // Integer to store the local equations no
     int local_eqn = 0;
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Get determinant of Jacobian of the mapping
       double J = J_eulerian_at_knot(ipt);
       // Premultiply weights and Jacobian
       double W = w * J;
       // Get the velocity test functions - there is no explicit
       // function to give the test function so use shape
       shape_at_knot(ipt, test);
       // Need to get the position to sort out the jacobian properly
       double r = 0.0;
       for (unsigned l = 0; l < n_node; l++)
       {
         r += this->nodal_position(l, 0) * test(l);
       }
       // Multiply by the geometric factor
       W *= r;
       // Loop over the veclocity test functions
       for (unsigned l = 0; l < n_node; l++)
       {
         // Loop over the velocity components
         for (unsigned i = 0; i < n_value; i++)
         {
           local_eqn = nodal_local_eqn(l, u_nodal_index[i]);
           // If not a boundary condition
           if (local_eqn >= 0)
           {
             // Add the contribution
             veloc_mass_diag[local_eqn] += test[l] * test[l] * W;
           } // End of if not boundary condition statement
         } // End of loop over dimension
       } // End of loop over test functions
     }
   }
References i, oomph::FiniteElement::integral_pt(), J, oomph::FiniteElement::J_eulerian_at_knot(), oomph::GeneralisedElement::ndof(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::nodal_position(), oomph::Integral::nweight(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, UniformPSDSelfTest::r, oomph::FiniteElement::shape_at_knot(), Eigen::test, u_index_axi_nst(), w, oomph::QuadTreeNames::W, and oomph::Integral::weight().
get_source_fct()
double oomph::AxisymmetricNavierStokesEquations::get_source_fct (const double & time, const unsigned & ipt, const Vector< double > & x) inline protected
Calculate the source fct at given time and Eulerian position.
     {
       // If the function pointer is zero return zero
       if (Source_fct_pt == 0)
       {
         return 0;
       }
       // Otherwise call the function
       else
       {
         return (*Source_fct_pt)(time, x);
       }
     }
References Source_fct_pt, and plotDoE::x.
Referenced by fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), get_dresidual_dnodal_coordinates(), oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), and get_source_fct_gradient().
get_source_fct_gradient()
virtual void oomph::AxisymmetricNavierStokesEquations::get_source_fct_gradient (const double & time, const unsigned & ipt, const Vector< double > & x, Vector< double > & gradient) inline protected virtual
Get gradient of source term at (Eulerian) position x. Computed via function pointer (if set) or by finite differencing (default)
     {
       // hierher: Implement function pointer version
       /*    //If no gradient function has been set, FD it */
       /*    if(Source_fct_gradient_pt==0) */
       {
         // Reference value
         const double source = get_source_fct(time, ipt, x);
         // FD it
         const double eps_fd = GeneralisedElement::Default_fd_jacobian_step;
         double source_pls = 0.0;
         Vector<double> x_pls(x);
         for (unsigned i = 0; i < 2; i++)
         {
           x_pls[i] += eps_fd;
           source_pls = get_source_fct(time, ipt, x_pls);
           gradient[i] = (source_pls - source) / eps_fd;
           x_pls[i] = x[i];
         }
       }
       /*    else */
       /*     { */
       /*      // Get gradient */
       /*      (*Source_fct_gradient_pt)(time,x,gradient); */
       /*     } */
     }
References oomph::GeneralisedElement::Default_fd_jacobian_step, get_source_fct(), i, TestProblem::source(), and plotDoE::x.
Referenced by get_dresidual_dnodal_coordinates(), and oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates().
get_viscosity_ratio_axisym_nst()
virtual void oomph::AxisymmetricNavierStokesEquations::get_viscosity_ratio_axisym_nst (const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, double & visc_ratio) inline protected virtual
Calculate the viscosity ratio relative to the viscosity used in the definition of the Reynolds number at given time and Eulerian position
     {
       visc_ratio = *Viscosity_Ratio_pt;
     }
References Viscosity_Ratio_pt.
Referenced by fill_in_generic_dresidual_contribution_axi_nst(), and fill_in_generic_residual_contribution_axi_nst().
interpolated_d_dudx_dX_axi_nst()
double oomph::AxisymmetricNavierStokesEquations::interpolated_d_dudx_dX_axi_nst (const Vector< double > & s, const unsigned & p, const unsigned & q, const unsigned & i, const unsigned & k) const inline
Return FE interpolated derivatives w.r.t. nodal coordinates X_{pq} of the spatial derivatives of the velocity components du_i/dx_k at local coordinate s
     {
       // Determine number of nodes
       const unsigned n_node = nnode();
       // Allocate storage for local shape function and its derivatives
       // with respect to space
       Shape psif(n_node);
       DShape dpsifds(n_node, 2);
       // Find values of shape function (ignore jacobian)
       (void)this->dshape_local(s, psif, dpsifds);
       // Allocate memory for the jacobian and the inverse of the jacobian
       DenseMatrix<double> jacobian(2), inverse_jacobian(2);
       // Allocate memory for the derivative of the jacobian w.r.t. nodal coords
       DenseMatrix<double> djacobian_dX(2, n_node);
       // Allocate memory for the derivative w.r.t. nodal coords of the
       // spatial derivatives of the shape functions
       RankFourTensor<double> d_dpsifdx_dX(2, n_node, 3, 2);
       // Now calculate the inverse jacobian
       const double det =
         local_to_eulerian_mapping(dpsifds, jacobian, inverse_jacobian);
       // Calculate the derivative of the jacobian w.r.t. nodal coordinates
       // Note: must call this before "transform_derivatives(...)" since this
       // function requires dpsids rather than dpsidx
       dJ_eulerian_dnodal_coordinates(jacobian, dpsifds, djacobian_dX);
       // Calculate the derivative of dpsidx w.r.t. nodal coordinates
       // Note: this function also requires dpsids rather than dpsidx
       d_dshape_eulerian_dnodal_coordinates(
         det, jacobian, djacobian_dX, inverse_jacobian, dpsifds, d_dpsifdx_dX);
       // Get the index at which the velocity is stored
       const unsigned u_nodal_index = u_index_axi_nst(i);
       // Initialise value of dudx
       double interpolated_d_dudx_dX = 0.0;
       // Loop over the local nodes and sum
       for (unsigned l = 0; l < n_node; l++)
       {
         interpolated_d_dudx_dX +=
           nodal_value(l, u_nodal_index) * d_dpsifdx_dX(p, q, l, k);
       }
       return (interpolated_d_dudx_dX);
     }
References oomph::FiniteElement::d_dshape_eulerian_dnodal_coordinates(), oomph::FiniteElement::dJ_eulerian_dnodal_coordinates(), oomph::FiniteElement::dshape_local(), i, k, oomph::FiniteElement::local_to_eulerian_mapping(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), p, Eigen::numext::q, and u_index_axi_nst().
interpolated_duds_axi_nst()
double oomph::AxisymmetricNavierStokesEquations::interpolated_duds_axi_nst (const Vector< double > & s, const unsigned & i, const unsigned & j) const inline
Return FE interpolated derivatives of velocity component u[i] w.r.t spatial local coordinate direction s[j] at local coordinate s
     {
       // Determine number of nodes
       const unsigned n_node = nnode();
       // Allocate storage for local shape function and its derivatives
       // with respect to space
       Shape psif(n_node);
       DShape dpsifds(n_node, 2);
       // Find values of shape function (ignore jacobian)
       (void)this->dshape_local(s, psif, dpsifds);
       // Get the index at which the velocity is stored
       const unsigned u_nodal_index = u_index_axi_nst(i);
       // Initialise value of duds
       double interpolated_duds = 0.0;
       // Loop over the local nodes and sum
       for (unsigned l = 0; l < n_node; l++)
       {
         interpolated_duds += nodal_value(l, u_nodal_index) * dpsifds(l, j);
       }
       return (interpolated_duds);
     }
References oomph::FiniteElement::dshape_local(), i, j, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), and u_index_axi_nst().
Referenced by LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement::get_base_flow_duds().
interpolated_dudt_axi_nst()
double oomph::AxisymmetricNavierStokesEquations::interpolated_dudt_axi_nst (const Vector< double > & s, const unsigned & i) const inline
Return FE interpolated derivatives of velocity component u[i] w.r.t time at local coordinate s
     {
       // Determine number of nodes
       const unsigned n_node = nnode();
       // Allocate storage for local shape function
       Shape psif(n_node);
       // Find values of shape function
       shape(s, psif);
       // Initialise value of dudt
       double interpolated_dudt = 0.0;
       // Loop over the local nodes and sum
       for (unsigned l = 0; l < n_node; l++)
       {
         interpolated_dudt += du_dt_axi_nst(l, i) * psif[l];
       }
       return (interpolated_dudt);
     }
References du_dt_axi_nst(), i, oomph::FiniteElement::nnode(), s, and oomph::FiniteElement::shape().
Referenced by LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement::get_base_flow_dudt().
interpolated_dudx_axi_nst()
double oomph::AxisymmetricNavierStokesEquations::interpolated_dudx_axi_nst (const Vector< double > & s, const unsigned & i, const unsigned & j) const inline
Return FE interpolated derivatives of velocity component u[i] w.r.t spatial global coordinate direction x[j] at local coordinate s
     {
       // Determine number of nodes
       const unsigned n_node = nnode();
       // Allocate storage for local shape function and its derivatives
       // with respect to space
       Shape psif(n_node);
       DShape dpsifdx(n_node, 2);
       // Find values of shape function (ignore jacobian)
       (void)this->dshape_eulerian(s, psif, dpsifdx);
       // Get the index at which the velocity is stored
       const unsigned u_nodal_index = u_index_axi_nst(i);
       // Initialise value of dudx
       double interpolated_dudx = 0.0;
       // Loop over the local nodes and sum
       for (unsigned l = 0; l < n_node; l++)
       {
         interpolated_dudx += nodal_value(l, u_nodal_index) * dpsifdx(l, j);
       }
       return (interpolated_dudx);
     }
References oomph::FiniteElement::dshape_eulerian(), i, j, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), and u_index_axi_nst().
Referenced by LinearisedAxisymmetricQTaylorHoodMultiDomainElement::get_base_flow_dudx(), LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement::get_base_flow_dudx(), RefineableLinearisedAxisymmetricQTaylorHoodMultiDomainElement::get_base_flow_dudx(), and RefineableLinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement::get_base_flow_dudx().
interpolated_p_axi_nst()
double oomph::AxisymmetricNavierStokesEquations::interpolated_p_axi_nst (const Vector< double > & s) const inline
Return FE interpolated pressure at local coordinate s.
     {
       // Find number of nodes
       unsigned n_pres = npres_axi_nst();
       // Local shape function
       Shape psi(n_pres);
       // Find values of shape function
       pshape_axi_nst(s, psi);
       // Initialise value of p
       double interpolated_p = 0.0;
       // Loop over the local nodes and sum
       for (unsigned l = 0; l < n_pres; l++)
       {
         interpolated_p += p_axi_nst(l) * psi[l];
       }
       return (interpolated_p);
     }
References npres_axi_nst(), p_axi_nst(), pshape_axi_nst(), and s.
Referenced by oomph::RefineableAxisymmetricQCrouzeixRaviartElement::further_build(), LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement::get_base_flow_p(), oomph::RefineableAxisymmetricQTaylorHoodElement::get_interpolated_values(), oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::output(), oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::output(), output(), point_output_data(), pressure_integral(), scalar_value_paraview(), and traction().
interpolated_u_axi_nst() [1/3]
double oomph::AxisymmetricNavierStokesEquations::interpolated_u_axi_nst (const unsigned & t, const Vector< double > & s, const unsigned & i) const inline
Return FE interpolated velocity u[i] at local coordinate s.
     {
       // Find number of nodes
       unsigned n_node = nnode();
       // Local shape function
       Shape psi(n_node);
       // Find values of shape function
       shape(s, psi);
       // Get the index at which the velocity is stored
       unsigned u_nodal_index = u_index_axi_nst(i);
       // Initialise value of u
       double interpolated_u = 0.0;
       // Loop over the local nodes and sum
       for (unsigned l = 0; l < n_node; l++)
       {
         interpolated_u += nodal_value(t, l, u_nodal_index) * psi[l];
       }
       return (interpolated_u);
     }
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), plotPSD::t, and u_index_axi_nst().
interpolated_u_axi_nst() [2/3]
double oomph::AxisymmetricNavierStokesEquations::interpolated_u_axi_nst (const Vector< double > & s, const unsigned & i) const inline
Return FE interpolated velocity u[i] at local coordinate s.
     {
       // Find number of nodes
       unsigned n_node = nnode();
       // Local shape function
       Shape psi(n_node);
       // Find values of shape function
       shape(s, psi);
       // Get the index at which the velocity is stored
       unsigned u_nodal_index = u_index_axi_nst(i);
       // Initialise value of u
       double interpolated_u = 0.0;
       // Loop over the local nodes and sum
       for (unsigned l = 0; l < n_node; l++)
       {
         interpolated_u += nodal_value(l, u_nodal_index) * psi[l];
       }
       return (interpolated_u);
     }
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), and u_index_axi_nst().
interpolated_u_axi_nst() [3/3]
void oomph::AxisymmetricNavierStokesEquations::interpolated_u_axi_nst (const Vector< double > & s, Vector< double > & veloc) const inline
Compute vector of FE interpolated velocity u at local coordinate s.
     {
       // Find number of nodes
       unsigned n_node = nnode();
       // Local shape function
       Shape psi(n_node);
       // Find values of shape function
       shape(s, psi);
       for (unsigned i = 0; i < 3; i++)
       {
         // Index at which the nodal value is stored
         unsigned u_nodal_index = u_index_axi_nst(i);
         // Initialise value of u
         veloc[i] = 0.0;
         // Loop over the local nodes and sum
         for (unsigned l = 0; l < n_node; l++)
         {
           veloc[i] += nodal_value(l, u_nodal_index) * psi[l];
         }
       }
     }
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), and u_index_axi_nst().
Referenced by compute_error(), LinearisedAxisymmetricQTaylorHoodMultiDomainElement::get_base_flow_u(), LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement::get_base_flow_u(), RefineableLinearisedAxisymmetricQTaylorHoodMultiDomainElement::get_base_flow_u(), RefineableLinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement::get_base_flow_u(), oomph::RefineableAxisymmetricQTaylorHoodElement::get_interpolated_values(), oomph::RefineableAxisymmetricQCrouzeixRaviartElement::get_interpolated_values(), oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::get_wind_axi_adv_diff(), RefineableQAxisymAdvectionDiffusionBoussinesqElement::get_wind_axi_adv_diff(), QAxisymAdvectionDiffusionElementWithExternalElement::get_wind_axi_adv_diff(), oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::get_wind_axi_adv_diff(), kin_energy(), oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::output(), oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::output(), output(), point_output_data(), and scalar_value_paraview().
kin_energy()
double oomph::AxisymmetricNavierStokesEquations::kin_energy () const
Get integral of kinetic energy over element.
Get integral of kinetic energy over element:
   {
     throw OomphLibError(
       "Check the kinetic energy calculation for axisymmetric NSt",
       OOMPH_CURRENT_FUNCTION,
       OOMPH_EXCEPTION_LOCATION);
     // Initialise
     double kin_en = 0.0;
     // Set the value of Nintpt
     unsigned Nintpt = integral_pt()->nweight();
     // Set the Vector to hold local coordinates
     Vector<double> s(2);
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < Nintpt; ipt++)
     {
       // Assign values of s
       for (unsigned i = 0; i < 2; i++)
       {
         s[i] = integral_pt()->knot(ipt, i);
       }
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Get Jacobian of mapping
       double J = J_eulerian(s);
       // Loop over directions
       double veloc_squared = 0.0;
       for (unsigned i = 0; i < 3; i++)
       {
         veloc_squared +=
           interpolated_u_axi_nst(s, i) * interpolated_u_axi_nst(s, i);
       }
       kin_en += 0.5 * veloc_squared * w * J * interpolated_x(s, 0);
     }
     return kin_en;
   }
References i, oomph::FiniteElement::integral_pt(), interpolated_u_axi_nst(), oomph::FiniteElement::interpolated_x(), J, oomph::FiniteElement::J_eulerian(), oomph::Integral::knot(), GlobalParameters::Nintpt, oomph::Integral::nweight(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, s, w, and oomph::Integral::weight().
n_u_nst()
unsigned oomph::AxisymmetricNavierStokesEquations::n_u_nst () const inline
Return the number of velocity components for use in general FluidInterface clas
     {
       return 3;
     }
npres_axi_nst()
virtual unsigned oomph::AxisymmetricNavierStokesEquations::npres_axi_nst () const pure virtual
Function to return number of pressure degrees of freedom.
Implemented in oomph::AxisymmetricTTaylorHoodElement, oomph::AxisymmetricTCrouzeixRaviartElement, oomph::AxisymmetricQTaylorHoodElement, and oomph::AxisymmetricQCrouzeixRaviartElement.
Referenced by fill_in_generic_dresidual_contribution_axi_nst(), fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), get_dresidual_dnodal_coordinates(), oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), and interpolated_p_axi_nst().
nscalar_paraview()
unsigned oomph::AxisymmetricNavierStokesEquations::nscalar_paraview () const inline virtual
Number of scalars/fields output by this element. Reimplements broken virtual function in base class.
Reimplemented from oomph::FiniteElement.
     {
       return 4;
     }
Referenced by oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::nscalar_paraview().
output() [1/4]
void oomph::AxisymmetricNavierStokesEquations::output (FILE * file_pt) inline virtual
Output function: x,y,[z],u,v,[w],p in tecplot format. Default number of plot points
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::PseudoSolidNodeUpdateElement< AxisymmetricTTaylorHoodElement, TPVDElement< 2, 3 > >, oomph::AxisymmetricTTaylorHoodElement, oomph::AxisymmetricTCrouzeixRaviartElement, oomph::AxisymmetricQTaylorHoodElement, and oomph::AxisymmetricQCrouzeixRaviartElement.
     {
       unsigned nplot = 5;
       output(file_pt, nplot);
     }
References output().
output() [2/4]
void oomph::AxisymmetricNavierStokesEquations::output (FILE * file_pt, const unsigned & nplot) virtual
Output function: x,y,[z],u,v,[w],p in tecplot format. nplot points in each coordinate direction
Output function: r,z,u,v,w,p in tecplot format. Specified number of plot points in each coordinate direction.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::AxisymmetricTTaylorHoodElement, oomph::AxisymmetricTCrouzeixRaviartElement, oomph::AxisymmetricQTaylorHoodElement, oomph::AxisymmetricQCrouzeixRaviartElement, and oomph::PseudoSolidNodeUpdateElement< AxisymmetricTTaylorHoodElement, TPVDElement< 2, 3 > >.
   {
     // Vector of local coordinates
     Vector<double> s(2);
     // Tecplot header info
     fprintf(file_pt, "%s ", tecplot_zone_string(nplot).c_str());
     // Loop over plot points
     unsigned num_plot_points = nplot_points(nplot);
     for (unsigned iplot = 0; iplot < num_plot_points; iplot++)
     {
       // Get local coordinates of plot point
       get_s_plot(iplot, nplot, s);
       // Coordinates
       for (unsigned i = 0; i < 2; i++)
       {
         // outfile << interpolated_x(s,i) << " ";
         fprintf(file_pt, "%g ", interpolated_x(s, i));
       }
       // Velocities
       for (unsigned i = 0; i < 3; i++)
       {
         // outfile << interpolated_u(s,i) << " ";
         fprintf(file_pt, "%g ", interpolated_u_axi_nst(s, i));
       }
       // Pressure
       // outfile << interpolated_p(s)  << " ";
       fprintf(file_pt, "%g ", interpolated_p_axi_nst(s));
       // outfile << std::endl;
       fprintf(file_pt, "\n");
     }
     // outfile << std::endl;
     fprintf(file_pt, "\n");
     // Write tecplot footer (e.g. FE connectivity lists)
     write_tecplot_zone_footer(file_pt, nplot);
   }
References oomph::FiniteElement::get_s_plot(), i, interpolated_p_axi_nst(), interpolated_u_axi_nst(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output() [3/4]
void oomph::AxisymmetricNavierStokesEquations::output (std::ostream & outfile) inline virtual
Output function: x,y,[z],u,v,[w],p in tecplot format. Default number of plot points
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::PseudoSolidNodeUpdateElement< AxisymmetricTTaylorHoodElement, TPVDElement< 2, 3 > >, oomph::AxisymmetricTTaylorHoodElement, oomph::AxisymmetricTCrouzeixRaviartElement, oomph::AxisymmetricQTaylorHoodElement, and oomph::AxisymmetricQCrouzeixRaviartElement.
     {
       unsigned nplot = 5;
       output(outfile, nplot);
     }
Referenced by output(), oomph::AxisymmetricQCrouzeixRaviartElement::output(), oomph::AxisymmetricQTaylorHoodElement::output(), oomph::AxisymmetricTCrouzeixRaviartElement::output(), and oomph::AxisymmetricTTaylorHoodElement::output().
output() [4/4]
void oomph::AxisymmetricNavierStokesEquations::output (std::ostream & outfile, const unsigned & nplot) virtual
Output function: x,y,[z],u,v,[w],p in tecplot format. nplot points in each coordinate direction
Output function: r,z,u,v,w,p in tecplot format. Specified number of plot points in each coordinate direction.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::AxisymmetricTTaylorHoodElement, oomph::AxisymmetricTCrouzeixRaviartElement, oomph::AxisymmetricQTaylorHoodElement, oomph::AxisymmetricQCrouzeixRaviartElement, and oomph::PseudoSolidNodeUpdateElement< AxisymmetricTTaylorHoodElement, TPVDElement< 2, 3 > >.
   {
     // Vector of local coordinates
     Vector<double> s(2);
     // Tecplot header info
     outfile << tecplot_zone_string(nplot);
     // Loop over plot points
     unsigned num_plot_points = nplot_points(nplot);
     for (unsigned iplot = 0; iplot < num_plot_points; iplot++)
     {
       // Get local coordinates of plot point
       get_s_plot(iplot, nplot, s);
       // Coordinates
       for (unsigned i = 0; i < 2; i++)
       {
         outfile << interpolated_x(s, i) << " ";
       }
       // Velocities
       for (unsigned i = 0; i < 3; i++)
       {
         outfile << interpolated_u_axi_nst(s, i) << " ";
       }
       // Pressure
       outfile << interpolated_p_axi_nst(s) << " ";
       outfile << std::endl;
     }
     outfile << std::endl;
     // Write tecplot footer (e.g. FE connectivity lists)
     write_tecplot_zone_footer(outfile, nplot);
   }
References oomph::FiniteElement::get_s_plot(), i, interpolated_p_axi_nst(), interpolated_u_axi_nst(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output_fct() [1/2]
void oomph::AxisymmetricNavierStokesEquations::output_fct (std::ostream & outfile, const unsigned & nplot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) virtual
Output exact solution specified via function pointer at a given time and at a given number of plot points. Function prints as many components as are returned in solution Vector.
Output "exact" solution at a given time Solution is provided via function pointer. Plot at a given number of plot points. Function prints as many components as are returned in solution Vector.
Reimplemented from oomph::FiniteElement.
   {
     // Vector of local coordinates
     Vector<double> s(2);
     // Vector for coordintes
     Vector<double> x(2);
     // Tecplot header info
     outfile << tecplot_zone_string(nplot);
     // Exact solution Vector
     Vector<double> exact_soln;
     // Loop over plot points
     unsigned num_plot_points = nplot_points(nplot);
     for (unsigned iplot = 0; iplot < num_plot_points; iplot++)
     {
       // Get local coordinates of plot point
       get_s_plot(iplot, nplot, s);
       // Get x position as Vector
       interpolated_x(s, x);
       // Get exact solution at this point
       (*exact_soln_pt)(time, x, exact_soln);
       // Output x,y,...
       for (unsigned i = 0; i < 2; i++)
       {
         outfile << x[i] << " ";
       }
       // Output "exact solution"
       for (unsigned i = 0; i < exact_soln.size(); i++)
       {
         outfile << exact_soln[i] << " ";
       }
       outfile << std::endl;
     }
     // Write tecplot footer (e.g. FE connectivity lists)
     write_tecplot_zone_footer(outfile, nplot);
   }
References ProblemParameters::exact_soln(), oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), oomph::FiniteElement::write_tecplot_zone_footer(), and plotDoE::x.
output_fct() [2/2]
void oomph::AxisymmetricNavierStokesEquations::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) virtual
Output exact solution specified via function pointer at a given number of plot points. Function prints as many components as are returned in solution Vector
Output "exact" solution Solution is provided via function pointer. Plot at a given number of plot points. Function prints as many components as are returned in solution Vector.
Reimplemented from oomph::FiniteElement.
   {
     // Vector of local coordinates
     Vector<double> s(2);
     // Vector for coordintes
     Vector<double> x(2);
     // Tecplot header info
     outfile << tecplot_zone_string(nplot);
     // Exact solution Vector
     Vector<double> exact_soln;
     // Loop over plot points
     unsigned num_plot_points = nplot_points(nplot);
     for (unsigned iplot = 0; iplot < num_plot_points; iplot++)
     {
       // Get local coordinates of plot point
       get_s_plot(iplot, nplot, s);
       // Get x position as Vector
       interpolated_x(s, x);
       // Get exact solution at this point
       (*exact_soln_pt)(x, exact_soln);
       // Output x,y,...
       for (unsigned i = 0; i < 2; i++)
       {
         outfile << x[i] << " ";
       }
       // Output "exact solution"
       for (unsigned i = 0; i < exact_soln.size(); i++)
       {
         outfile << exact_soln[i] << " ";
       }
       outfile << std::endl;
     }
     // Write tecplot footer (e.g. FE connectivity lists)
     write_tecplot_zone_footer(outfile, nplot);
   }
References ProblemParameters::exact_soln(), oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), oomph::FiniteElement::write_tecplot_zone_footer(), and plotDoE::x.
output_veloc()
void oomph::AxisymmetricNavierStokesEquations::output_veloc (std::ostream & outfile, const unsigned & nplot, const unsigned & t)
Output function: x,y,[z],u,v,[w] in tecplot format. nplot points in each coordinate direction at timestep t (t=0: present; t>0: previous timestep)
Output function: Velocities only x,y,[z],u,v,[w] in tecplot format at specified previous timestep (t=0: present; t>0: previous timestep). Specified number of plot points in each coordinate direction.
   {
     // Find number of nodes
     unsigned n_node = nnode();
     // Local shape function
     Shape psi(n_node);
     // Vectors of local coordinates and coords and velocities
     Vector<double> s(2);
     Vector<double> interpolated_x(2);
     Vector<double> interpolated_u(3);
     // Tecplot header info
     outfile << tecplot_zone_string(nplot);
     // Loop over plot points
     unsigned num_plot_points = nplot_points(nplot);
     for (unsigned iplot = 0; iplot < num_plot_points; iplot++)
     {
       // Get local coordinates of plot point
       get_s_plot(iplot, nplot, s);
       // Get shape functions
       shape(s, psi);
       // Loop over coordinate directions
       for (unsigned i = 0; i < 2; i++)
       {
         interpolated_x[i] = 0.0;
         // Loop over the local nodes and sum
         for (unsigned l = 0; l < n_node; l++)
         {
           interpolated_x[i] += nodal_position(t, l, i) * psi[l];
         }
       }
       // Loop over the velocity components
       for (unsigned i = 0; i < 3; i++)
       {
         // Get the index at which the velocity is stored
         unsigned u_nodal_index = u_index_axi_nst(i);
         interpolated_u[i] = 0.0;
         // Loop over the local nodes and sum
         for (unsigned l = 0; l < n_node; l++)
         {
           interpolated_u[i] += nodal_value(t, l, u_nodal_index) * psi[l];
         }
       }
       // Coordinates
       for (unsigned i = 0; i < 2; i++)
       {
         outfile << interpolated_x[i] << " ";
       }
       // Velocities
       for (unsigned i = 0; i < 3; i++)
       {
         outfile << interpolated_u[i] << " ";
       }
       outfile << std::endl;
     }
     // Write tecplot footer (e.g. FE connectivity lists)
     write_tecplot_zone_footer(outfile, nplot);
   }
References oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::shape(), plotPSD::t, oomph::FiniteElement::tecplot_zone_string(), u_index_axi_nst(), and oomph::FiniteElement::write_tecplot_zone_footer().
p_axi_nst()
virtual double oomph::AxisymmetricNavierStokesEquations::p_axi_nst (const unsigned & n_p) const pure virtual
Pressure at local pressure "node" n_p Uses suitably interpolated value for hanging nodes.
Implemented in oomph::AxisymmetricTTaylorHoodElement, oomph::AxisymmetricQTaylorHoodElement, oomph::AxisymmetricTCrouzeixRaviartElement, and oomph::AxisymmetricQCrouzeixRaviartElement.
Referenced by fill_in_generic_dresidual_contribution_axi_nst(), fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), get_dresidual_dnodal_coordinates(), oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), and interpolated_p_axi_nst().
p_local_eqn()
virtual int oomph::AxisymmetricNavierStokesEquations::p_local_eqn (const unsigned & n) const protected pure virtual
Access function for the local equation number information for the pressure. p_local_eqn[n] = local equation number or < 0 if pinned
Implemented in oomph::AxisymmetricTTaylorHoodElement, oomph::AxisymmetricTCrouzeixRaviartElement, oomph::AxisymmetricQTaylorHoodElement, and oomph::AxisymmetricQCrouzeixRaviartElement.
Referenced by fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), get_dresidual_dnodal_coordinates(), and oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates().
p_nodal_index_axi_nst()
virtual int oomph::AxisymmetricNavierStokesEquations::p_nodal_index_axi_nst () const inline virtual
Which nodal value represents the pressure?
Reimplemented in oomph::AxisymmetricTTaylorHoodElement, and oomph::AxisymmetricQTaylorHoodElement.
     {
       return Pressure_not_stored_at_node;
     }
References Pressure_not_stored_at_node.
Referenced by oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), and oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates().
point_output_data()
void oomph::AxisymmetricNavierStokesEquations::point_output_data (const Vector< double > & s, Vector< double > & data) inline virtual
Output solution in data vector at local cordinates s: r,z,u_r,u_z,u_phi,p
Reimplemented from oomph::FiniteElement.
     {
       // Output the components of the position
       for (unsigned i = 0; i < 2; i++)
       {
         data.push_back(interpolated_x(s, i));
       }
       // Output the components of the FE representation of u at s
       for (unsigned i = 0; i < 3; i++)
       {
         data.push_back(interpolated_u_axi_nst(s, i));
       }
       // Output FE representation of p at s
       data.push_back(interpolated_p_axi_nst(s));
     }
References data, i, interpolated_p_axi_nst(), interpolated_u_axi_nst(), oomph::FiniteElement::interpolated_x(), and s.
pressure_integral()
double oomph::AxisymmetricNavierStokesEquations::pressure_integral () const
Integral of pressure over element.
Return pressure integrated over the element.
   {
     // Initialise
     double press_int = 0;
     // Set the value of Nintpt
     unsigned Nintpt = integral_pt()->nweight();
     // Set the Vector to hold local coordinates
     Vector<double> s(2);
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < Nintpt; ipt++)
     {
       // Assign values of s
       for (unsigned i = 0; i < 2; i++)
       {
         s[i] = integral_pt()->knot(ipt, i);
       }
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Get Jacobian of mapping
       double J = J_eulerian(s);
       // Premultiply the weights and the Jacobian
       double W = w * J * interpolated_x(s, 0);
       // Get pressure
       double press = interpolated_p_axi_nst(s);
       // Add
       press_int += press * W;
     }
     return press_int;
   }
References i, oomph::FiniteElement::integral_pt(), interpolated_p_axi_nst(), oomph::FiniteElement::interpolated_x(), J, oomph::FiniteElement::J_eulerian(), oomph::Integral::knot(), GlobalParameters::Nintpt, oomph::Integral::nweight(), s, w, oomph::QuadTreeNames::W, and oomph::Integral::weight().
pshape_axi_nst() [1/2]
virtual void oomph::AxisymmetricNavierStokesEquations::pshape_axi_nst (const Vector< double > & s, Shape & psi) const protected pure virtual
Compute the pressure shape functions at local coordinate s.
Implemented in oomph::AxisymmetricTTaylorHoodElement, oomph::AxisymmetricTCrouzeixRaviartElement, oomph::AxisymmetricQTaylorHoodElement, and oomph::AxisymmetricQCrouzeixRaviartElement.
Referenced by fill_in_generic_dresidual_contribution_axi_nst(), fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), get_dresidual_dnodal_coordinates(), oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), and interpolated_p_axi_nst().
pshape_axi_nst() [2/2]
virtual void oomph::AxisymmetricNavierStokesEquations::pshape_axi_nst (const Vector< double > & s, Shape & psi, Shape & test) const protected pure virtual
Compute the pressure shape and test functions at local coordinate s
Implemented in oomph::AxisymmetricTTaylorHoodElement, oomph::AxisymmetricTCrouzeixRaviartElement, oomph::AxisymmetricQTaylorHoodElement, and oomph::AxisymmetricQCrouzeixRaviartElement.
re()
const double& oomph::AxisymmetricNavierStokesEquations::re () const inline
Reynolds number.
     {
       return *Re_pt;
     }
References Re_pt.
Referenced by fill_in_contribution_to_hessian_vector_products(), fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), get_dresidual_dnodal_coordinates(), and oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates().
re_invfr()
const double& oomph::AxisymmetricNavierStokesEquations::re_invfr () const inline
Global inverse Froude number.
     {
       return *ReInvFr_pt;
     }
References ReInvFr_pt.
Referenced by fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), get_dresidual_dnodal_coordinates(), and oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates().
re_invfr_pt()
double*& oomph::AxisymmetricNavierStokesEquations::re_invfr_pt () inline
Pointer to global inverse Froude number.
     {
       return ReInvFr_pt;
     }
References ReInvFr_pt.
Referenced by fill_in_generic_dresidual_contribution_axi_nst(), and oomph::RefineableAxisymmetricNavierStokesEquations::further_build().
re_invro()
const double& oomph::AxisymmetricNavierStokesEquations::re_invro () const inline
Global Reynolds number multiplied by inverse Rossby number.
     {
       return *ReInvRo_pt;
     }
References ReInvRo_pt.
Referenced by fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), get_dresidual_dnodal_coordinates(), and oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates().
re_invro_pt()
double*& oomph::AxisymmetricNavierStokesEquations::re_invro_pt () inline
Pointer to global inverse Froude number.
     {
       return ReInvRo_pt;
     }
References ReInvRo_pt.
Referenced by fill_in_generic_dresidual_contribution_axi_nst(), and oomph::RefineableAxisymmetricNavierStokesEquations::further_build().
re_pt()
double*& oomph::AxisymmetricNavierStokesEquations::re_pt () inline
Pointer to Reynolds number.
     {
       return Re_pt;
     }
References Re_pt.
Referenced by fill_in_generic_dresidual_contribution_axi_nst(), and oomph::RefineableAxisymmetricNavierStokesEquations::further_build().
re_st()
const double& oomph::AxisymmetricNavierStokesEquations::re_st () const inline
Product of Reynolds and Strouhal number (=Womersley number)
     {
       return *ReSt_pt;
     }
References ReSt_pt.
Referenced by fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), get_dresidual_dnodal_coordinates(), and oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates().
re_st_pt()
double*& oomph::AxisymmetricNavierStokesEquations::re_st_pt () inline
Pointer to product of Reynolds and Strouhal number (=Womersley number)
     {
       return ReSt_pt;
     }
References ReSt_pt.
Referenced by fill_in_generic_dresidual_contribution_axi_nst(), and oomph::RefineableAxisymmetricNavierStokesEquations::further_build().
scalar_name_paraview()
std::string oomph::AxisymmetricNavierStokesEquations::scalar_name_paraview (const unsigned & i) const inline virtual
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc. Can (should!) be overloaded with more meaningful names in specific elements.
Reimplemented from oomph::FiniteElement.
     {
       // Veloc
       if (i < 3)
       {
         return "Velocity " + StringConversion::to_string(i);
       }
       // Pressure field
       else if (i == 3)
       {
         return "Pressure";
       }
       // Never get here
       else
       {
         std::stringstream error_stream;
         error_stream
           << "Axisymmetric Navier-Stokes Elements only store 4 fields "
           << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
         return " ";
       }
     }
References i, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::StringConversion::to_string().
Referenced by oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::scalar_name_paraview().
scalar_value_paraview()
void oomph::AxisymmetricNavierStokesEquations::scalar_value_paraview (std::ofstream & file_out, const unsigned & i, const unsigned & nplot) const inline virtual
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
Reimplemented from oomph::FiniteElement.
     {
       // Vector of local coordinates
       Vector<double> s(2);
       // Loop over plot points
       unsigned num_plot_points = nplot_points_paraview(nplot);
       for (unsigned iplot = 0; iplot < num_plot_points; iplot++)
       {
         // Get local coordinates of plot point
         get_s_plot(iplot, nplot, s);
         // Velocities
         if (i < 3)
         {
           file_out << interpolated_u_axi_nst(s, i) << std::endl;
         }
         // Pressure
         else if (i == 3)
         {
           file_out << interpolated_p_axi_nst(s) << std::endl;
         }
         // Never get here
         else
         {
           std::stringstream error_stream;
           error_stream
             << "Axisymmetric Navier-Stokes Elements only store 4 fields "
             << std::endl;
           throw OomphLibError(error_stream.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
       }
     }
References oomph::FiniteElement::get_s_plot(), i, interpolated_p_axi_nst(), interpolated_u_axi_nst(), oomph::FiniteElement::nplot_points_paraview(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and s.
Referenced by oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::scalar_value_paraview().
strain_rate()
void oomph::AxisymmetricNavierStokesEquations::strain_rate (const Vector< double > & s, DenseMatrix< double > & strainrate) const
Strain-rate tensor: \(e_{ij} \) where \(i,j = r,z,\theta \) (in that order)
Get strain-rate tensor: \(e_{ij} \) where \(i,j = r,z,\theta \) (in that order)
   {
 #ifdef PARANOID
     if ((strainrate.ncol() != 3) || (strainrate.nrow() != 3))
     {
       std::ostringstream error_message;
       error_message << "The strain rate has incorrect dimensions "
                     << strainrate.ncol() << " x " << strainrate.nrow()
                     << " Not 3" << std::endl;
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Find out how many nodes there are in the element
     unsigned n_node = nnode();
     // Set up memory for the shape and test functions
     Shape psi(n_node);
     DShape dpsidx(n_node, 2);
     // Call the derivatives of the shape functions
     dshape_eulerian(s, psi, dpsidx);
     // Radius
     double interpolated_r = 0.0;
     // Velocity components and their derivatives
     double ur = 0.0;
     double durdr = 0.0;
     double durdz = 0.0;
     double uz = 0.0;
     double duzdr = 0.0;
     double duzdz = 0.0;
     double uphi = 0.0;
     double duphidr = 0.0;
     double duphidz = 0.0;
     // Get the local storage for the indices
     unsigned u_nodal_index[3];
     for (unsigned i = 0; i < 3; ++i)
     {
       u_nodal_index[i] = u_index_axi_nst(i);
     }
     // Loop over nodes to assemble velocities and their derivatives
     // w.r.t. to r and z (x_0 and x_1)
     for (unsigned l = 0; l < n_node; l++)
     {
       interpolated_r += nodal_position(l, 0) * psi[l];
       ur += nodal_value(l, u_nodal_index[0]) * psi[l];
       uz += nodal_value(l, u_nodal_index[1]) * psi[l];
       uphi += nodal_value(l, u_nodal_index[2]) * psi[l];
       durdr += nodal_value(l, u_nodal_index[0]) * dpsidx(l, 0);
       durdz += nodal_value(l, u_nodal_index[0]) * dpsidx(l, 1);
       duzdr += nodal_value(l, u_nodal_index[1]) * dpsidx(l, 0);
       duzdz += nodal_value(l, u_nodal_index[1]) * dpsidx(l, 1);
       duphidr += nodal_value(l, u_nodal_index[2]) * dpsidx(l, 0);
       duphidz += nodal_value(l, u_nodal_index[2]) * dpsidx(l, 1);
     }
     // Assign strain rates without negative powers of the radius
     // and zero those with:
     strainrate(0, 0) = durdr;
     strainrate(0, 1) = 0.5 * (durdz + duzdr);
     strainrate(1, 0) = strainrate(0, 1);
     strainrate(0, 2) = 0.0;
     strainrate(2, 0) = strainrate(0, 2);
     strainrate(1, 1) = duzdz;
     strainrate(1, 2) = 0.5 * duphidz;
     strainrate(2, 1) = strainrate(1, 2);
     strainrate(2, 2) = 0.0;
     // Overwrite the strain rates with negative powers of the radius
     // unless we're at the origin
     if (std::fabs(interpolated_r) > 1.0e-16)
     {
       double inverse_radius = 1.0 / interpolated_r;
       strainrate(0, 2) = 0.5 * (duphidr - inverse_radius * uphi);
       strainrate(2, 0) = strainrate(0, 2);
       strainrate(2, 2) = inverse_radius * ur;
     }
   }
References oomph::FiniteElement::dshape_eulerian(), boost::multiprecision::fabs(), i, oomph::DenseMatrix< T >::ncol(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_value(), oomph::DenseMatrix< T >::nrow(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, s, and u_index_axi_nst().
Referenced by dissipation(), oomph::RefineableAxisymmetricNavierStokesEquations::get_Z2_flux(), oomph::AxisymmetricTCrouzeixRaviartElement::get_Z2_flux(), oomph::AxisymmetricTTaylorHoodElement::get_Z2_flux(), and traction().
traction()
void oomph::AxisymmetricNavierStokesEquations::traction (const Vector< double > & s, const Vector< double > & N, Vector< double > & traction) const
Compute traction (on the viscous scale) at local coordinate s for outer unit normal N
   {
     // throw OomphLibError(
     // "Check the traction calculation for axisymmetric NSt",
     // OOMPH_CURRENT_FUNCTION,
     // OOMPH_EXCEPTION_LOCATION);
     // Pad out normal vector if required
     Vector<double> n_local(3, 0.0);
     n_local[0] = N[0];
     n_local[1] = N[1];
 #ifdef PARANOID
     if ((N.size() == 3) && (N[2] != 0.0))
     {
       throw OomphLibError(
         "Unit normal passed into this fct should either be 2D (r,z) or have a "
         "zero component in the theta-direction",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Get velocity gradients
     DenseMatrix<double> strainrate(3, 3);
     strain_rate(s, strainrate);
     // Get pressure
     double press = interpolated_p_axi_nst(s);
     // Loop over traction components
     for (unsigned i = 0; i < 3; i++)
     {
       traction[i] = -press * n_local[i];
       for (unsigned j = 0; j < 3; j++)
       {
         traction[i] += 2.0 * strainrate(i, j) * n_local[j];
       }
     }
   }
References i, interpolated_p_axi_nst(), j, N, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, s, and strain_rate().
Referenced by oomph::AxisymmetricQCrouzeixRaviartElement::get_traction(), and oomph::AxisymmetricQTaylorHoodElement::get_traction().
u_index_axi_nst()
virtual unsigned oomph::AxisymmetricNavierStokesEquations::u_index_axi_nst (const unsigned & i) const inline virtual
Return the index at which the i-th unknown velocity component is stored. The default value, i, is appropriate for single-physics problems. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknowns are always stored at the same indices at each node.
     {
       return i;
     }
References i.
Referenced by dinterpolated_u_axi_nst_ddata(), oomph::RefineableAxisymmetricNavierStokesEquations::dinterpolated_u_axi_nst_ddata(), du_dt_axi_nst(), fill_in_contribution_to_hessian_vector_products(), fill_in_generic_dresidual_contribution_axi_nst(), fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::fill_in_off_diagonal_jacobian_blocks_analytic(), get_dresidual_dnodal_coordinates(), oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::RefineableAxisymmetricQTaylorHoodElement::get_interpolated_values(), oomph::RefineableAxisymmetricQCrouzeixRaviartElement::get_interpolated_values(), get_pressure_and_velocity_mass_matrix_diagonal(), RefineableQAxisymAdvectionDiffusionBoussinesqElement::identify_all_field_data_for_external_interaction(), oomph::AxisymmetricTCrouzeixRaviartElement::identify_load_data(), interpolated_d_dudx_dX_axi_nst(), interpolated_duds_axi_nst(), interpolated_dudx_axi_nst(), interpolated_u_axi_nst(), output_veloc(), strain_rate(), and u_index_nst().
u_index_nst()
unsigned oomph::AxisymmetricNavierStokesEquations::u_index_nst (const unsigned & i) const inline
Return the index at which the i-th unknown velocity component is stored with a common interface for use in general FluidInterface and similar elements. To do: Merge all common storage etc to a common base class for Navier–Stokes elements in all coordinate systems.
     {
       return this->u_index_axi_nst(i);
     }
References u_index_axi_nst().
Referenced by oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::fill_in_off_diagonal_jacobian_blocks_by_fd(), and oomph::FSIAxisymmetricQTaylorHoodElement::identify_load_data().
viscosity_ratio()
const double& oomph::AxisymmetricNavierStokesEquations::viscosity_ratio () const inline
Viscosity ratio for element: Element's viscosity relative to the viscosity used in the definition of the Reynolds number
     {
       return *Viscosity_Ratio_pt;
     }
References Viscosity_Ratio_pt.
Referenced by oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), get_dresidual_dnodal_coordinates(), and oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates().
viscosity_ratio_pt()
double*& oomph::AxisymmetricNavierStokesEquations::viscosity_ratio_pt () inline
Pointer to Viscosity Ratio.
     {
       return Viscosity_Ratio_pt;
     }
References Viscosity_Ratio_pt.
Referenced by oomph::RefineableAxisymmetricNavierStokesEquations::further_build().
Member Data Documentation
ALE_is_disabled
bool oomph::AxisymmetricNavierStokesEquations::ALE_is_disabled protected
Boolean flag to indicate if ALE formulation is disabled when the time-derivatives are computed. Only set to true if you're sure that the mesh is stationary
Referenced by disable_ALE(), enable_ALE(), fill_in_contribution_to_hessian_vector_products(), fill_in_generic_dresidual_contribution_axi_nst(), fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableAxisymmetricNavierStokesEquations::further_build(), get_dresidual_dnodal_coordinates(), and oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates().
axi_nst_body_force_fct_pt
void(*&)(const double& time, const Vector<double>& x, Vector<double>& f) oomph::AxisymmetricNavierStokesEquations::axi_nst_body_force_fct_pt() inline
Access function for the body-force pointer.
     {
       return Body_force_fct_pt;
     }
Referenced by oomph::RefineableAxisymmetricNavierStokesEquations::further_build().
Body_force_fct_pt
void(* oomph::AxisymmetricNavierStokesEquations::Body_force_fct_pt) (const double &time, const Vector< double > &x, Vector< double > &result) protected
Pointer to body force function.
Referenced by oomph::RefineableAxisymmetricNavierStokesEquations::further_build(), and get_body_force_axi_nst().
Default_Gravity_vector
Vector< double > oomph::AxisymmetricNavierStokesEquations::Default_Gravity_vector static private
Static default value for the gravity vector.
Navier-Stokes equations default gravity vector.
Referenced by AxisymmetricNavierStokesEquations().
Default_Physical_Constant_Value
double oomph::AxisymmetricNavierStokesEquations::Default_Physical_Constant_Value static private
Initial value:
=
    0.0
Navier–Stokes equations static data.
Static default value for the physical constants (all initialised to zero)
Referenced by AxisymmetricNavierStokesEquations().
Default_Physical_Ratio_Value
double oomph::AxisymmetricNavierStokesEquations::Default_Physical_Ratio_Value = 1.0 static private
Static default value for the physical ratios (all are initialised to one)
Referenced by AxisymmetricNavierStokesEquations().
Density_Ratio_pt
double* oomph::AxisymmetricNavierStokesEquations::Density_Ratio_pt protected
Pointer to the density ratio (relative to the density used in the definition of the Reynolds number)
Referenced by AxisymmetricNavierStokesEquations(), density_ratio(), density_ratio_pt(), and oomph::RefineableAxisymmetricNavierStokesEquations::further_build().
G_pt
Vector<double>* oomph::AxisymmetricNavierStokesEquations::G_pt protected
Pointer to global gravity Vector.
Referenced by AxisymmetricNavierStokesEquations(), oomph::RefineableAxisymmetricNavierStokesEquations::further_build(), g(), and g_pt().
Gamma
Vector< double > oomph::AxisymmetricNavierStokesEquations::Gamma static
Vector to decide whether the stress-divergence form is used or not.
Navier–Stokes equations static data.
Referenced by fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), get_dresidual_dnodal_coordinates(), and oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates().
Pressure_not_stored_at_node
int oomph::AxisymmetricNavierStokesEquations::Pressure_not_stored_at_node = -100 static private
Static "magic" number that indicates that the pressure is not stored at a node
"Magic" negative number that indicates that the pressure is not stored at a node. This cannot be -1 because that represents the positional hanging scheme in the hanging_pt object of nodes
Referenced by p_nodal_index_axi_nst().
Re_pt
double* oomph::AxisymmetricNavierStokesEquations::Re_pt protected
Pointer to global Reynolds number.
Referenced by AxisymmetricNavierStokesEquations(), fill_in_generic_dresidual_contribution_axi_nst(), oomph::RefineableAxisymmetricNavierStokesEquations::further_build(), re(), and re_pt().
ReInvFr_pt
double* oomph::AxisymmetricNavierStokesEquations::ReInvFr_pt protected
Pointer to global Reynolds number x inverse Froude number (= Bond number / Capillary number)
Referenced by AxisymmetricNavierStokesEquations(), oomph::RefineableAxisymmetricNavierStokesEquations::further_build(), re_invfr(), and re_invfr_pt().
ReInvRo_pt
double* oomph::AxisymmetricNavierStokesEquations::ReInvRo_pt protected
Pointer to global Reynolds number x inverse Rossby number (used when in a rotating frame)
Referenced by AxisymmetricNavierStokesEquations(), oomph::RefineableAxisymmetricNavierStokesEquations::further_build(), re_invro(), and re_invro_pt().
ReSt_pt
double* oomph::AxisymmetricNavierStokesEquations::ReSt_pt protected
Pointer to global Reynolds number x Strouhal number (=Womersley)
Referenced by AxisymmetricNavierStokesEquations(), oomph::RefineableAxisymmetricNavierStokesEquations::further_build(), re_st(), and re_st_pt().
source_fct_pt
double(*&)(const double& time, const Vector<double>& x) oomph::AxisymmetricNavierStokesEquations::source_fct_pt() inline
Access function for the source-function pointer.
     {
       return Source_fct_pt;
     }
Referenced by oomph::RefineableAxisymmetricNavierStokesEquations::further_build().
Source_fct_pt
double(* oomph::AxisymmetricNavierStokesEquations::Source_fct_pt) (const double &time, const Vector< double > &x) protected
Pointer to volumetric source function.
Referenced by oomph::RefineableAxisymmetricNavierStokesEquations::further_build(), and get_source_fct().
Viscosity_Ratio_pt
double* oomph::AxisymmetricNavierStokesEquations::Viscosity_Ratio_pt protected
Pointer to the viscosity ratio (relative to the viscosity used in the definition of the Reynolds number)
Referenced by AxisymmetricNavierStokesEquations(), oomph::RefineableAxisymmetricNavierStokesEquations::further_build(), get_viscosity_ratio_axisym_nst(), viscosity_ratio(), and viscosity_ratio_pt().
The documentation for this class was generated from the following files:
axisym_navier_stokes_elements.h
axisym_navier_stokes_elements.cc