MercuryDPM: oomph::TreeRoot Class Reference
oomph::TreeRoot Class Reference
#include <tree.h>
Public Member Functions
TreeRoot (RefineableElement *const &object_pt)
Constructor for the (empty) root tree.
TreeRoot (const TreeRoot &dummy)=delete
Broken copy constructor.
void operator= (const TreeRoot &)=delete
Broken assignment operator.
TreeRoot *& neighbour_pt (const int &direction)
bool is_neighbour_periodic (const int &direction)
void set_neighbour_periodic (const int &direction)
Set the neighbour in particular direction to be periodic.
void set_neighbour_nonperiodic (const int &direction)
Set the neighbour in particular direction to be nonperiodic.
unsigned nneighbour ()
Return the number of neighbours.
Public Member Functions inherited from oomph::Tree
virtual ~Tree ()
Tree (const Tree &dummy)=delete
Broken copy constructor.
void operator= (const Tree &)=delete
Broken assignment operator.
RefineableElement * object_pt () const
void flush_object ()
Flush the object represented by the tree.
Tree * son_pt (const int &son_index) const
void set_son_pt (const Vector< Tree * > &son_pt)
unsigned nsons () const
Return number of sons (zero if it's a leaf node)
void flush_sons ()
Flush the sons.
TreeRoot *& root_pt ()
Return pointer to root of the tree.
TreeRoot * root_pt () const
Return pointer to root of the tree (const version)
template<class ELEMENT >
void split_if_required ()
template<class ELEMENT >
void p_refine_if_required (Mesh *&mesh_pt)
void merge_sons_if_required (Mesh *&mesh_pt)
void deactivate_object ()
Call the RefineableElement's deactivate_element() function.
virtual Tree * construct_son (RefineableElement *const &object_pt, Tree *const &father_pt, const int &son_type)=0
void traverse_all (Tree::VoidMemberFctPt member_function)
void traverse_all (Tree::VoidMeshPtArgumentMemberFctPt member_function, Mesh *&mesh_pt)
void traverse_all_but_leaves (Tree::VoidMemberFctPt member_function)
void traverse_leaves (Tree::VoidMemberFctPt member_function)
void traverse_leaves (Tree::VoidMeshPtArgumentMemberFctPt member_function, Mesh *&mesh_pt)
void stick_leaves_into_vector (Vector< Tree * > &)
Traverse tree and stick pointers to leaf "nodes" (only) into Vector.
void stick_all_tree_nodes_into_vector (Vector< Tree * > &)
Traverse and stick pointers to all "nodes" into Vector.
int son_type () const
Return son type.
bool is_leaf ()
Return true if the tree is a leaf node.
Tree * father_pt () const
Return pointer to father: NULL if it's a root node.
void set_father_pt (Tree *const &father_pt)
Set the father.
unsigned level () const
Return the level of the Tree (root=0)
Protected Attributes
std::map< int, TreeRoot * > Neighbour_pt
std::map< int, bool > Neighbour_periodic
Protected Attributes inherited from oomph::Tree
TreeRoot * Root_pt
Pointer to the root of the tree.
Tree * Father_pt
Pointer to the Father of the Tree.
Vector< Tree * > Son_pt
Vector of pointers to the sons of the Tree.
int Level
Level of the Tree (level 0 = root)
int Son_type
Son type (e.g. SW/SE/NW/NE in a quadtree)
RefineableElement * Object_pt
Pointer to the object represented by the tree.
Additional Inherited Members
Public Types inherited from oomph::Tree
typedef void(Tree::* VoidMemberFctPt) ()
Function pointer to argument-free void Tree member function.
typedef void(Tree::* VoidMeshPtArgumentMemberFctPt) (Mesh *&mesh_pt)
Static Public Member Functions inherited from oomph::Tree
static double & max_neighbour_finding_tolerance ()
Static Public Attributes inherited from oomph::Tree
static const int OMEGA = 26
Default value for an unassigned neighbour.
Protected Member Functions inherited from oomph::Tree
Tree ()
Default constructor (empty and broken)
Tree (RefineableElement *const &object_pt)
Tree (RefineableElement *const &object_pt, Tree *const &father_pt, const int &son_type)
Static Protected Attributes inherited from oomph::Tree
static double Max_neighbour_finding_tolerance = 1.0e-14
Detailed Description
TreeRoot is a Tree that forms the root of a (recursive) tree. The "root node" is special as it holds additional information about its neighbours and their relative rotation (inside a TreeForest).
Constructor & Destructor Documentation
TreeRoot() [1/2]
oomph::TreeRoot::TreeRoot (RefineableElement *const & object_pt) inline
Constructor for the (empty) root tree.
                                                   : Tree(object_pt)
     {
       // TreeRoot is the Root
       Root_pt = this;
     }
References oomph::Tree::Root_pt.
TreeRoot() [2/2]
oomph::TreeRoot::TreeRoot (const TreeRoot & dummy) delete
Broken copy constructor.
Member Function Documentation
is_neighbour_periodic()
bool oomph::TreeRoot::is_neighbour_periodic (const int & direction) inline
Return whether the neighbour in the particular direction is periodic.
     {
       return Neighbour_periodic[direction];
     }
References Neighbour_periodic.
Referenced by oomph::OcTree::doc_face_neighbours(), oomph::BinaryTree::doc_neighbours(), oomph::QuadTree::doc_neighbours(), and oomph::OcTree::doc_true_edge_neighbours().
neighbour_pt()
TreeRoot*& oomph::TreeRoot::neighbour_pt (const int & direction) inline
Return the pointer to the neighbouring TreeRoots in specified direction. Returns NULL if there's no neighbour in this direction.
     {
       return Neighbour_pt[direction];
     }
References Neighbour_pt.
Referenced by UnsteadyHeatProblem< ELEMENT >::enforce_time_periodic_boundary_conditions(), oomph::BinaryTree::gteq_edge_neighbour(), oomph::QuadTree::gteq_edge_neighbour(), oomph::OcTree::gteq_face_neighbour(), and UnsteadyHeatProblem< ELEMENT >::set_neighbour_periodic_and_up_right_equivalents().
nneighbour()
unsigned oomph::TreeRoot::nneighbour () inline
Return the number of neighbours.
     {
       // Loop over the neighbours and test whether they are non-null
       unsigned count = 0;
       for (std::map<int, TreeRoot*>::iterator it = Neighbour_pt.begin();
            it != Neighbour_pt.end();
            it++)
       {
         if (Neighbour_pt[it->first] != 0)
         {
           count++;
         }
       }
       // Return number counted
       return count;
     }
References Neighbour_pt.
operator=()
void oomph::TreeRoot::operator= (const TreeRoot &) delete
Broken assignment operator.
set_neighbour_nonperiodic()
void oomph::TreeRoot::set_neighbour_nonperiodic (const int & direction) inline
Set the neighbour in particular direction to be nonperiodic.
     {
       Neighbour_periodic[direction] = false;
     }
References Neighbour_periodic.
set_neighbour_periodic()
void oomph::TreeRoot::set_neighbour_periodic (const int & direction) inline
Set the neighbour in particular direction to be periodic.
     {
       Neighbour_periodic[direction] = true;
     }
References Neighbour_periodic.
Referenced by UnsteadyHeatProblem< ELEMENT >::set_neighbour_periodic_and_up_right_equivalents().
Member Data Documentation
Neighbour_periodic
std::map<int, bool> oomph::TreeRoot::Neighbour_periodic protected
Map of booleans used for periodic boundaries: Neighbour_periodic_direction[directon] returns true if the neighbour in that direction is actually a periodic neighbour — shared data values, but independent position. The default return of the map is false.
Referenced by is_neighbour_periodic(), set_neighbour_nonperiodic(), and set_neighbour_periodic().
Neighbour_pt
std::map<int, TreeRoot*> oomph::TreeRoot::Neighbour_pt protected
Map of pointers to the neighbouring TreeRoots: Neighbour_pt[direction] returns the pointer to the TreeRoot's neighbour in the (enumerated) direction. Returns NULL if there's no neighbour in this direction.
Referenced by oomph::BinaryTreeRoot::direction_of_neighbour(), oomph::QuadTreeRoot::direction_of_neighbour(), oomph::OcTreeRoot::direction_of_neighbour(), neighbour_pt(), and nneighbour().
The documentation for this class was generated from the following file:
tree.h