MercuryDPM: circular_disk.cc File Reference
foeppl_von_karman/circular_disk/circular_disk.cc File Reference
#include <fenv.h>
#include "generic.h"
#include "foeppl_von_karman.h"
#include "meshes/triangle_mesh.h"
Classes
class UnstructuredFvKProblem< ELEMENT >
Class definition.
Namespaces
TestSoln
Functions
void TestSoln::get_pressure (const Vector< double > &x, double &pressure)
void TestSoln::get_airy_forcing (const Vector< double > &x, double &airy_forcing)
void TestSoln::zero (const Vector< double > &x, Vector< double > &u)
int main (int argc, char **argv)
Driver code for demo of inline triangle mesh generation.
Variables
double TestSoln::A = 1.0
double TestSoln::B = 2.0
double TestSoln::eta = 1
double TestSoln::r_b = 0.1
Data * TestSoln::p_b_pt = 0
Data * TestSoln::p_0_pt = 0
double TestSoln::prescribed_volume = 0.01
Function Documentation
main()
int main (int argc , char ** argv)
Driver code for demo of inline triangle mesh generation.
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Define possible command line arguments and parse the ones that
  // were actually specified
  // Validation?
  CommandLineArgs::specify_command_line_flag("--validation");
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  // Problem instance
  UnstructuredFvKProblem<
   ProjectableFoepplvonKarmanElement<TFoepplvonKarmanElement<3> > >
   problem(0.01);
  problem.newton_solve();
  problem.doc_solution();
 } //End of main
References oomph::CommandLineArgs::doc_specified_flags(), oomph::CommandLineArgs::parse_and_assign(), problem, Flag_definition::setup(), and oomph::CommandLineArgs::specify_command_line_flag().