MercuryDPM: No_Slip Namespace Reference
No_Slip Namespace Reference
Functions
void no_slip_condition_first (Node *node_pt)
Function that is used to set and update the no-slip boundary condition.
void no_slip_condition_second (Node *node_pt)
Function Documentation
no_slip_condition_first()
void No_Slip::no_slip_condition_first (Node * node_pt)
Function that is used to set and update the no-slip boundary condition.
  {
   //Cast the node to a spine node
   SpineNode* spine_node_pt = static_cast<SpineNode*>(node_pt);
   //Get the wall coordinate
   Vector<double> s(1);
   s[0] = spine_node_pt->spine_pt()->geom_parameter(0);
   // Prepare the storage for the derivative
   DenseMatrix<double> drdxi(1,2);
   //Get the derivative
   dynamic_cast<FSIHermiteBeamElement*>
    (spine_node_pt->spine_pt()->geom_object_pt(0))->
    dposition_dlagrangian_at_local_coordinate(s,drdxi);
   for(unsigned i=0;i<2;i++) {*node_pt->value_pt(i) = -drdxi(0,i);}
  }
References oomph::Spine::geom_object_pt(), oomph::Spine::geom_parameter(), i, s, oomph::SpineNode::spine_pt(), and oomph::Data::value_pt().
Referenced by AirwayReopeningProblem< ELEMENT >::AirwayReopeningProblem().
no_slip_condition_second()
void No_Slip::no_slip_condition_second (Node * node_pt)
  {
   //Cast the node to a spine node
   SpineNode* spine_node_pt = static_cast<SpineNode*>(node_pt);
   //Get the wall coordinate
   Vector<double> s(1);
   s[0] = spine_node_pt->spine_pt()->geom_parameter(1);
   // Prepare the storage for the derivative
   DenseMatrix<double> drdxi(1,2);
   //Get the derivative
   dynamic_cast<FSIHermiteBeamElement*>
    (spine_node_pt->spine_pt()->geom_object_pt(1))->
    dposition_dlagrangian_at_local_coordinate(s,drdxi);
   for(unsigned i=0;i<2;i++) {*node_pt->value_pt(i) = -drdxi(0,i);}
  }
References oomph::Spine::geom_object_pt(), oomph::Spine::geom_parameter(), i, s, oomph::SpineNode::spine_pt(), and oomph::Data::value_pt().
Referenced by AirwayReopeningProblem< ELEMENT >::AirwayReopeningProblem().