MercuryDPM: HertzianViscoelasticInteraction Class Reference
HertzianViscoelasticInteraction Class Reference
Computes normal forces for a Herztian visco-elastic interaction.
#include <HertzianViscoelasticInteraction.h>
Public Types
typedef HertzianViscoelasticNormalSpecies SpeciesType
An alias for HertzianViscoelasticNormalSpecies.
Public Member Functions
HertzianViscoelasticInteraction (BaseInteractable *P, BaseInteractable *I, unsigned timeStamp)
Constructor.
HertzianViscoelasticInteraction ()
HertzianViscoelasticInteraction (const HertzianViscoelasticInteraction &p)
Copy constructor.
~HertzianViscoelasticInteraction () override
Destructor.
void computeNormalForce ()
Computes the amount of normal force due to an Hertzian visco-elastic interaction.
HertzianViscoelasticInteraction (const BaseInteraction &p)
void read (std::istream &is) override
Interaction read function, which accepts an std::istream as input.
void write (std::ostream &os) const override
Interaction write function, which accepts an std::ostream as input.
std::string getBaseName () const
Returns the name of the interaction.
Mdouble getElasticEnergy () const override
Computes and returns the amount of elastic energy stored in the spring.
const HertzianViscoelasticNormalSpecies * getSpecies () const
Returns a const pointer of type HerztianViscoelasticNormalSpecies (static-cast).
Mdouble getElasticEnergyAtEquilibrium (Mdouble adhesiveForce) const override
Public Member Functions inherited from BaseInteraction
BaseInteraction (BaseInteractable *P, BaseInteractable *I, unsigned timeStamp)
A constructor takes the BaseInteractable objects which are interacting (come into contact) and time the interaction starts.
BaseInteraction ()
BaseInteraction (const BaseInteraction &p)
Copy constructor.
~BaseInteraction () override
The destructor. It removes this interactions from the objects that were interacting, and writes the time to a file when needed.
virtual void actionsOnErase ()
If an interaction needs to do something before it gets erased, add it here. E.g. Liquid bridges rupture at the end of their lifetime, and the liquid bridge volume has to be redistributed. The reason this action is not done in the destructor is that this action should not be taken when erasing ghost interactions.
virtual void computeForce ()
Virtual function that contains the force law between the two objects interacting.
void writeToFStat (std::ostream &os, Mdouble time) const
Writes forces data to the FStat file.
std::string getName () const override
Virtual function which allows interactions to be named.
void setDistance (Mdouble distance)
Sets the interaction distance between the two interacting objects.
void setNormal (Vec3D normal)
Sets the normal vector between the two interacting objects.
void setOverlap (Mdouble overlap)
Set the overlap between the two interacting object.
void setContactPoint (Vec3D contactPoint)
Set the location of the contact point between the two interacting objects.
void setTimeStamp (unsigned timeStamp)
Updates the time step of the interacting. Note, time steps used to find completed interactions.
void setSpecies (const BaseSpecies *species)
Set the Species of the interaction; note this can either be a Species or MixedSpecies.
void setP (BaseInteractable *P)
Sets the first object involved in the interaction (normally a particle).
void setI (BaseInteractable *I)
Sets the second object involved in the interaction (often particle or wall).
void importP (BaseInteractable *P)
Sets the first object involved in the interaction (normally a particle).
void importI (BaseInteractable *I)
Sets the second object involved in the interaction (often particle or wall).
Vec3D getIP () const
Vec3D getIC () const
Vec3D getCP () const
void setLagrangeMultiplier (Mdouble multiplier)
Mdouble getLagrangeMultiplier ()
void setHandler (InteractionHandler *handler)
Sets the pointer to the interaction hander which is storing this interaction.
InteractionHandler * getHandler () const
Gets a point to the interaction handlers to which this interaction belongs.
const Vec3D & getForce () const
Gets the current force (vector) between the two interacting objects.
const Vec3D & getTorque () const
Gets the current torque (vector) between the two interacting objects.
const Vec3D & getNormal () const
Gets the normal vector between the two interacting objects.
const Vec3D & getContactPoint () const
Gets constant reference to contact point (vector).
Mdouble getOverlap () const
Returns a Mdouble with the current overlap between the two interacting objects.
Mdouble getOverlapVolume () const
Returns the overlap volume between two interacting objects.
Mdouble getContactRadius () const
Returns a Mdouble with the current contact between the two interacting objects.
void removeFromHandler ()
Removes this interaction from its interaction hander.
void copySwitchPointer (const BaseInteractable *original, BaseInteractable *ghost) const
This copies the interactions of the original particle and replaces the original with the ghost copy.
void gatherContactStatistics ()
BaseInteractable * getP ()
Returns a pointer to first object involved in the interaction (normally a particle).
BaseInteractable * getI ()
Returns a pointer to the second object involved in the interaction (often a wall or a particle).
const BaseInteractable * getP () const
Returns a constant pointer to the first object involved in the interaction.
const BaseInteractable * getI () const
Returns a constant pointer to the second object involved in the interaction.
Mdouble getTimeStamp () const
Returns an Mdouble which is the time stamp of the interaction.
virtual void integrate (Mdouble timeStep)
integrates variables of the interaction which need to be integrate e.g. the tangential overlap.
virtual Mdouble getTangentialOverlap () const
get the length of the current tangential overlap
Mdouble getDistance () const
Returns an Mdouble which is the norm (length) of distance vector.
const Vec3D & getRelativeVelocity () const
Returns a constant reference to a vector of relative velocity.
Mdouble getNormalRelativeVelocity () const
Returns a double which is the norm (length) of the relative velocity vector.
Mdouble getAbsoluteNormalForce () const
Returns the absolute value of the norm (length) of the Normal force vector.
virtual BaseInteraction * copy () const =0
Makes a copy of the interaction and returns a pointer to the copy.
void setFStatData (std::fstream &fstat, BaseParticle *P, BaseWall *I)
void setFStatData (std::fstream &fstat, BaseParticle *P, BaseParticle *I)
unsigned int getMultiContactIdentifier () const
void setMultiContactIdentifier (unsigned int multiContactIdentifier_)
virtual void rotateHistory (Matrix3D &rotationMatrix)
When periodic particles are used, some interactions need certain history properties rotated (e.g. tangential springs). This is the function for that.
virtual void actionsAfterTimeStep ()
virtual unsigned getNumberOfFieldsVTK () const
virtual std::string getTypeVTK (unsigned i) const
virtual std::string getNameVTK (unsigned i) const
virtual std::vector< Mdouble > getFieldVTK (unsigned i) const
void addForce (Vec3D force)
add an force increment to the total force.
void addTorque (Vec3D torque)
add a torque increment to the total torque.
void setForce (Vec3D force)
set total force (this is used by the normal force, tangential forces are added use addForce)
void setTorque (Vec3D torque)
set the total force (this is used by the normal force, tangential torques are added use addTorque)
const BaseSpecies * getBaseSpecies () const
Return a constant point to BaseSpecies of the interaction.
virtual void createMPIType ()
virtual void * createMPIInteractionDataArray (unsigned int numberOfInteractions) const
virtual void deleteMPIInteractionDataArray (void *dataArray)
virtual void getMPIInteraction (void *historyDataArray, unsigned int index) const
copies the history interactions into the data array
virtual void getInteractionDetails (void *interactionDataArray, unsigned int index, unsigned int &identificationP, unsigned int &identificationI, bool &isWallInteraction, unsigned &timeStamp)
virtual void setMPIInteraction (void *interactionDataArray, unsigned int index, bool resetPointers)
void setBasicMPIInteractionValues (int P, int I, unsigned timeStamp, Vec3D force, Vec3D torque, bool isWallInteraction, bool resetPointers)
void setIdentificationP (unsigned int identification)
void setIdentificationI (int identification)
void setWallInteraction (bool flag)
unsigned int getIdentificationP ()
int getIdentificationI ()
bool isWallInteraction ()
virtual bool isBonded () const
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Additional Inherited Members
Protected Member Functions inherited from BaseInteraction
virtual const Vec3D getTangentialForce () const
Mdouble getEffectiveRadius () const
Returns a Mdouble to the effective radius of the interaction. (Not corrected for the overlap)
Mdouble getEffectiveMass () const
Returns a Mdouble to the effective radius of the interaction. (Not corrected for the overlap)
void setRelativeVelocity (Vec3D relativeVelocity)
set the relative velocity of the current of the interactions.
void setNormalRelativeVelocity (Mdouble normalRelativeVelocit)
set the normal component of the relative velocity.
void setAbsoluteNormalForce (Mdouble absoluteNormalForce)
the absolute values of the norm (length) of the normal force
virtual void reverseHistory ()
When periodic particles some interaction need certain history properties reversing. This is the function for that.
void writeInteraction (std::ostream &os, bool created) const
Writes information about a interaction to the interaction file.
Detailed Description
Computes normal forces for a Herztian visco-elastic interaction.
Member Typedef Documentation
SpeciesType
typedef HertzianViscoelasticNormalSpecies HertzianViscoelasticInteraction::SpeciesType
An alias for HertzianViscoelasticNormalSpecies.
Constructor & Destructor Documentation
HertzianViscoelasticInteraction() [1/4]
HertzianViscoelasticInteraction::HertzianViscoelasticInteraction (BaseInteractable * P, BaseInteractable * I, unsigned timeStamp)
Constructor.
Parameters
[in] P
[in] I
[in] timeStamp
         : BaseInteraction(P, I, timeStamp)
 {
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"HertzianViscoelasticInteraction::HertzianViscoelasticInteraction() finished"<<std::endl;
 #endif
 }
HertzianViscoelasticInteraction() [2/4]
HertzianViscoelasticInteraction::HertzianViscoelasticInteraction () default
HertzianViscoelasticInteraction() [3/4]
HertzianViscoelasticInteraction::HertzianViscoelasticInteraction (const HertzianViscoelasticInteraction & p)
Copy constructor.
Parameters
[in] p
         : BaseInteraction(p)
 {
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"HertzianViscoelasticInteraction::HertzianViscoelasticInteraction(const HertzianViscoelasticInteraction& p) finished"<<std::endl;
 #endif
 }
~HertzianViscoelasticInteraction()
HertzianViscoelasticInteraction::~HertzianViscoelasticInteraction () override
Destructor.
 {
 #ifdef DEBUG_DESTRUCTOR
     std::cout<<"HertzianViscoelasticInteraction::~HertzianViscoelasticInteraction() finished"<<std::endl;
 #endif
 }
HertzianViscoelasticInteraction() [4/4]
HertzianViscoelasticInteraction::HertzianViscoelasticInteraction (const BaseInteraction & p) inline explicit
                                                                        : BaseInteraction(p)
     {
     }
Member Function Documentation
computeNormalForce()
void HertzianViscoelasticInteraction::computeNormalForce ()
Computes the amount of normal force due to an Hertzian visco-elastic interaction.
The contact model is based on the description given in http://people.ds.cam.ac.uk/jae1001/CUS/research/pfizer/Antypov_Elliott_EPL_2011.pdf (which is the same as in Yade https://answers.launchpad.net/yade/+question/235934) kn = 4/3 E* sqrt(R/2 delta) = sqrt(2)/3 kn fn = kn delta + gamma sqrt(m/2 kn) vn =
Note, the constants are slightly different in the C Thornton model, otherwise it's the same: www.cfd.com.au/cfd_conf12/PDFs/175CUM.pdf
Todo:
check for superquadrics
 {
     // This function is called for all particles within interactionRadius distance.
     // This has to be outside the loop because it is needed for the other forces
     // Compute the relative velocity vector of particle P w.r.t. I
     setRelativeVelocity(
             getP()->getVelocityAtContact(getContactPoint()) - getI()->getVelocityAtContact(getContactPoint()));
     // Compute the projection of vrel onto the normal (can be negative)
     setNormalRelativeVelocity(Vec3D::dot(getRelativeVelocity(), getNormal()));
     if (getOverlap() > 0) //if contact forces
     {
         const HertzianViscoelasticNormalSpecies* species = getSpecies();
         Mdouble stiffness = 4. / 3. * species->getEffectiveElasticModulus() * std::sqrt(getEffectiveRadius() * getOverlap());
         //calculating the current normal force
         //dissipation is computed such that the restitution is constant
         Mdouble dissipationCoefficient = species->getDissipation() * sqrt(getEffectiveMass() * stiffness);
         Mdouble normalForce = stiffness * getOverlap() - dissipationCoefficient * getNormalRelativeVelocity();
         //setting the normal force parameter in the base interaction class so that it can be accessed
         //by other classes...
         setAbsoluteNormalForce(std::abs(normalForce)); //used for further force calculations;
         setForce(getNormal() * normalForce);
         setTorque(Vec3D(0.0, 0.0, 0.0));
     }
     else
     {
         setAbsoluteNormalForce(0.0);
         setForce(Vec3D(0.0, 0.0, 0.0));
         setTorque(Vec3D(0.0, 0.0, 0.0));
     }
 }
References abs(), Vec3D::dot(), BaseInteraction::getContactPoint(), BaseInteraction::getEffectiveMass(), BaseInteraction::getEffectiveRadius(), BaseInteraction::getI(), BaseInteraction::getNormal(), BaseInteraction::getNormalRelativeVelocity(), BaseInteraction::getOverlap(), BaseInteraction::getP(), BaseInteraction::getRelativeVelocity(), getSpecies(), BaseInteraction::setAbsoluteNormalForce(), BaseInteraction::setForce(), BaseInteraction::setNormalRelativeVelocity(), BaseInteraction::setRelativeVelocity(), BaseInteraction::setTorque(), and sqrt().
getBaseName()
std::string HertzianViscoelasticInteraction::getBaseName () const
Returns the name of the interaction.
Returns
std::string
 {
     return "HertzianViscoelastic";
 }
getElasticEnergy()
Mdouble HertzianViscoelasticInteraction::getElasticEnergy () const override virtual
Computes and returns the amount of elastic energy stored in the spring.
kn = 4/3 E* sqrt(R/2 delta) fn = kn delta -> E = int fn ddelta = 2/5 4/3 E sqrt(R/2 delta) delta^2
Reimplemented from BaseInteraction.
 {
     if (getOverlap() > 0)
     {
         return 8. / 15. * getSpecies()->getEffectiveElasticModulus() * std::sqrt(getEffectiveRadius() * getOverlap()) *
                mathsFunc::square(getOverlap());
     }
     else
     {
         return 0.0;
     }
 }
References BaseInteraction::getEffectiveRadius(), BaseInteraction::getOverlap(), getSpecies(), sqrt(), and mathsFunc::square().
getElasticEnergyAtEquilibrium()
Mdouble HertzianViscoelasticInteraction::getElasticEnergyAtEquilibrium (Mdouble adhesiveForce) const override virtual
Computes elastic-adhesive energy at zero overlap, assuming the energy is zero at the equilibrium point mod = 4/3 E* sqrt(R/2) fn = mod delta^3/2 - fadh -> E = int_deltaEq^0 fn ddelta = [2/5 mod delta^5/2 - fadh * delta]_deltaEq^0 = [2/5 fn delta - 3/5 fadh delta]_deltaEq^0 = 3/5 fadh deltaEq
Todo:
TW consider renaming to getElasticAdhesiveEnergy or getElasticAdhesiveEnergyRelativeToEquilibrium
Reimplemented from BaseInteraction.
 {
     const HertzianViscoelasticNormalSpecies* species = getSpecies();
     const Mdouble modulus = 4. / 3. * species->getEffectiveElasticModulus() * std::sqrt(getEffectiveRadius());
     const Mdouble equilibriumOverlap = std::cbrt(mathsFunc::square(adhesiveForce / modulus));
     return 0.6 * adhesiveForce * equilibriumOverlap;//why not 0.4?
 }
References Eigen::numext::cbrt(), BaseInteraction::getEffectiveRadius(), getSpecies(), sqrt(), and mathsFunc::square().
getSpecies()
const HertzianViscoelasticNormalSpecies * HertzianViscoelasticInteraction::getSpecies () const
Returns a const pointer of type HerztianViscoelasticNormalSpecies (static-cast).
Returns
const HertzianViscoelasticNormalSpecies*
 {
     return static_cast<const HertzianViscoelasticNormalSpecies*>(getBaseSpecies()->getNormalForce());
 }
References BaseInteraction::getBaseSpecies(), and BaseSpecies::getNormalForce().
Referenced by computeNormalForce(), getElasticEnergy(), and getElasticEnergyAtEquilibrium().
read()
void HertzianViscoelasticInteraction::read (std::istream & is) override virtual
Interaction read function, which accepts an std::istream as input.
Parameters
[in,out] is
Reimplemented from BaseInteraction.
 {
     BaseInteraction::read(is);
 }
References BaseInteraction::read().
Referenced by HertzianBSHPViscoelasticInteraction::read().
write()
void HertzianViscoelasticInteraction::write (std::ostream & os) const override virtual
Interaction write function, which accepts an std::ostream as input.
Parameters
[in,out] os
Reimplemented from BaseInteraction.
 {
     BaseInteraction::write(os);
 }
References BaseInteraction::write().
Referenced by HertzianBSHPViscoelasticInteraction::write().
The documentation for this class was generated from the following files:
HertzianViscoelasticInteraction.h
HertzianViscoelasticInteraction.cc