MercuryDPM: OscillatingWall Class Reference
OscillatingWall Class Reference
Public Member Functions
OscillatingWall (const double &h, const double &x_left, const double &l, const double &a, const double &period, Time *time_pt)
~OscillatingWall ()
Destructor: Empty.
double & amplitude ()
Access function to the amplitude.
double & period ()
Access function to the period.
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void position (const Vector< double > &zeta, Vector< double > &r) const
"Current" position vector at Lagrangian coordinate zeta
unsigned ngeom_data () const
Number of geometric Data in GeomObject: None.
OscillatingWall (const double &h, const double &x_left, const double &l, const double &a, const double &period, Time *time_pt)
~OscillatingWall ()
Destructor: Empty.
double & amplitude ()
Access function to the amplitude.
double & period ()
Access function to the period.
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void position (const Vector< double > &zeta, Vector< double > &r) const
"Current" position vector at Lagrangian coordinate zeta
unsigned ngeom_data () const
Number of geometric Data in GeomObject: None.
OscillatingWall (const double &h, const double &x_left, const double &l, const double &a, const double &period, Time *time_pt)
~OscillatingWall ()
Destructor: Empty.
double & amplitude ()
Access function to the amplitude.
double & period ()
Access function to the period.
void enable_remain_steady_at_maximum_amplitude ()
void disable_remain_steady_at_maximum_amplitude ()
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void position (const Vector< double > &zeta, Vector< double > &r) const
"Current" position vector at Lagrangian coordinate zeta
unsigned ngeom_data () const
Number of geometric Data in GeomObject: None.
OscillatingWall (const double &h, const double &x_left, const double &l, const double &a, const double &period, Time *time_pt)
~OscillatingWall ()
Destructor: Empty.
double & amplitude ()
Access function to the amplitude.
double & period ()
Access function to the period.
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void position (const Vector< double > &zeta, Vector< double > &r) const
"Current" position vector at Lagrangian coordinate zeta
unsigned ngeom_data () const
Number of geometric Data in GeomObject: None.
OscillatingWall (const double &h, const double &x_left, const double &l, const double &a, const double &period, Time *time_pt)
~OscillatingWall ()
Destructor: Empty.
double & amplitude ()
Access function to the amplitude.
double & period ()
Access function to the period.
void enable_remain_steady_at_maximum_amplitude ()
void disable_remain_steady_at_maximum_amplitude ()
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void position (const Vector< double > &zeta, Vector< double > &r) const
"Current" position vector at Lagrangian coordinate zeta
unsigned ngeom_data () const
Number of geometric Data in GeomObject: None.
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual Data * geom_data_pt (const unsigned &j)
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition_dt (const Vector< double > &zeta, const unsigned &j, Vector< double > &drdt)
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
virtual void locate_zeta (const Vector< double > &zeta, GeomObject *&sub_geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
Private Attributes
double H
Height at ends.
double Length
Length.
double X_left
x-coordinate of left end
double A
Amplitude of oscillation.
double B
Relative amplitude of horizontal wall motion.
double T
Period of the oscillations.
Time * Time_pt
Pointer to the global time object.
bool Remain_steady_at_maximum_amplitude
Additional Inherited Members
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Detailed Description
Straight, horizontal channel wall at \(y=H \) deforms into an oscillating parabola. The amplitude of the oscillation \(A \) and its period is \(T \). The position vector to a point on the wall, parametrised by the Lagrangian coordinate \(\zeta \in [0,L]\), is therefore given by
\[ {\bf R}(\zeta,t) = \left(\begin{array}{c} L_{up} + \zeta \\ 1 \end{array} \right) + A \left(\begin{array}{l} - B \sin\left(\frac{2\pi}{L_{collapsible}}\zeta\right) \\ \left(\frac{2}{L_{collapsible}}\right)^2 \zeta \ (L-\zeta) \end{array} \right) \ \sin\left(\frac{2\pi t}{T}\right) \ {\cal R}(t) \]
The parameter \(B \) is zero by default. If it is set to a nonzero value, the material particles on the wall also perform some horizontal motion. The "ramp" function
\[ {\cal R}(t) = \left\{ \begin{array}{ll} \frac{1}{2}(1-\cos(\pi t/T)) & \mbox{for $t<T$} \\ 1 & \mbox{for $t \ge T$} \end{array} \right. \]
provides a "smooth" startup of the oscillation.
Straight, horizontal channel wall at \(y=H \) deforms into an oscillating parabola. The amplitude of the oscillation \(A \) and its period is \(T \). The position vector to a point on the wall, parametrised by the Lagrangian coordinate \(\zeta \in [0,L]\), is therefore given by
\[ {\bf R}(\zeta,t) = \left(\begin{array}{c} L_{up} + \zeta \newline 1 \end{array} \right) + A \left(\begin{array}{l} - B \sin\left(\frac{2\pi}{L_{collapsible}}\zeta\right) \newline \left(\frac{2}{L_{collapsible}}\right)^2 \zeta \ (L-\zeta) \end{array} \right) \ \sin\left(\frac{2\pi t}{T}\right) \ {\cal R}(t) \]
The parameter \(B \) is zero by default. If it is set to a nonzero value, the material particles on the wall also perform some horizontal motion. The "ramp" function
\[ {\cal R}(t) = \left\{ \begin{array}{ll} \frac{1}{2}(1-\cos(\pi t/T)) & \mbox{for $t<T$} \\ 1 & \mbox{for $t \ge T$} \end{array} \right. \]
provides a "smooth" startup of the oscillation.
Constructor & Destructor Documentation
OscillatingWall() [1/5]
OscillatingWall::OscillatingWall (const double & h, const double & x_left, const double & l, const double & a, const double & period, Time * time_pt) inline
Constructor : It's a 2D object, parametrised by one Lagrangian coordinate. Arguments: height at ends, x-coordinate of left end, length, amplitude of deflection, period of oscillation, and pointer to time object
                                                                        :
   GeomObject(1,2), H(h), Length(l), X_left(x_left), A(a), B(0.0), T(period),
   Time_pt(time_pt)
   {}
~OscillatingWall() [1/5]
OscillatingWall::~OscillatingWall () inline
Destructor: Empty.
 {}
OscillatingWall() [2/5]
OscillatingWall::OscillatingWall (const double & h, const double & x_left, const double & l, const double & a, const double & period, Time * time_pt) inline
Constructor : It's a 2D object, parametrised by one Lagrangian coordinate. Arguments: height at ends, x-coordinate of left end, length, amplitude of deflection, period of oscillation, and pointer to time object
                                                                        :
   GeomObject(1,2), H(h), Length(l), X_left(x_left), A(a), B(0.0), T(period),
   Time_pt(time_pt)
   {}
~OscillatingWall() [2/5]
OscillatingWall::~OscillatingWall () inline
Destructor: Empty.
 {}
OscillatingWall() [3/5]
OscillatingWall::OscillatingWall (const double & h, const double & x_left, const double & l, const double & a, const double & period, Time * time_pt) inline
Constructor : It's a 2D object, parametrised by one Lagrangian coordinate. Arguments: height at ends, x-coordinate of left end, length, amplitude of deflection, period of oscillation, and pointer to time object
                                                                        :
   GeomObject(1,2), H(h), Length(l), X_left(x_left), A(a), B(0.0), T(period),
   Time_pt(time_pt)
   {
    Remain_steady_at_maximum_amplitude=false;
   }
~OscillatingWall() [3/5]
OscillatingWall::~OscillatingWall () inline
Destructor: Empty.
 {}
OscillatingWall() [4/5]
OscillatingWall::OscillatingWall (const double & h, const double & x_left, const double & l, const double & a, const double & period, Time * time_pt) inline
Constructor : It's a 2D object, parametrised by one Lagrangian coordinate. Arguments: height at ends, x-coordinate of left end, length, amplitude of deflection, period of oscillation, and pointer to time object
                                                                        :
   GeomObject(1,2), H(h), Length(l), X_left(x_left), A(a), B(0.0), T(period),
   Time_pt(time_pt)
   {}
~OscillatingWall() [4/5]
OscillatingWall::~OscillatingWall () inline
Destructor: Empty.
 {}
OscillatingWall() [5/5]
OscillatingWall::OscillatingWall (const double & h, const double & x_left, const double & l, const double & a, const double & period, Time * time_pt) inline
Constructor : It's a 2D object, parametrised by one Lagrangian coordinate. Arguments: height at ends, x-coordinate of left end, length, amplitude of deflection, period of oscillation, and pointer to time object
                                                                        :
   GeomObject(1,2), H(h), Length(l), X_left(x_left), A(a), B(0.0), T(period),
   Time_pt(time_pt)
   {
    Remain_steady_at_maximum_amplitude=false;
   }
~OscillatingWall() [5/5]
OscillatingWall::~OscillatingWall () inline
Destructor: Empty.
 {}
Member Function Documentation
amplitude() [1/5]
double& OscillatingWall::amplitude () inline
Access function to the amplitude.
 {return A;}
amplitude() [2/5]
double& OscillatingWall::amplitude () inline
Access function to the amplitude.
 {return A;}
amplitude() [3/5]
double& OscillatingWall::amplitude () inline
Access function to the amplitude.
 {return A;}
amplitude() [4/5]
double& OscillatingWall::amplitude () inline
Access function to the amplitude.
 {return A;}
amplitude() [5/5]
double& OscillatingWall::amplitude () inline
Access function to the amplitude.
 {return A;}
disable_remain_steady_at_maximum_amplitude() [1/2]
void OscillatingWall::disable_remain_steady_at_maximum_amplitude () inline
Set the flag so that the wall continues to oscillate after it reaches maximum amplitude
   {Remain_steady_at_maximum_amplitude = false;}
disable_remain_steady_at_maximum_amplitude() [2/2]
void OscillatingWall::disable_remain_steady_at_maximum_amplitude () inline
Set the flag so that the wall continues to oscillate after it reaches maximum amplitude
   {Remain_steady_at_maximum_amplitude = false;}
enable_remain_steady_at_maximum_amplitude() [1/2]
void OscillatingWall::enable_remain_steady_at_maximum_amplitude () inline
Set the flag so that the wall remains steady once it reaches maximum amplitude
   {Remain_steady_at_maximum_amplitude = true;}
enable_remain_steady_at_maximum_amplitude() [2/2]
void OscillatingWall::enable_remain_steady_at_maximum_amplitude () inline
Set the flag so that the wall remains steady once it reaches maximum amplitude
   {Remain_steady_at_maximum_amplitude = true;}
ngeom_data() [1/5]
unsigned OscillatingWall::ngeom_data () const inline virtual
Number of geometric Data in GeomObject: None.
Reimplemented from oomph::GeomObject.
 {return 0;}
ngeom_data() [2/5]
unsigned OscillatingWall::ngeom_data () const inline virtual
Number of geometric Data in GeomObject: None.
Reimplemented from oomph::GeomObject.
 {return 0;}
ngeom_data() [3/5]
unsigned OscillatingWall::ngeom_data () const inline virtual
Number of geometric Data in GeomObject: None.
Reimplemented from oomph::GeomObject.
 {return 0;}
ngeom_data() [4/5]
unsigned OscillatingWall::ngeom_data () const inline virtual
Number of geometric Data in GeomObject: None.
Reimplemented from oomph::GeomObject.
 {return 0;}
ngeom_data() [5/5]
unsigned OscillatingWall::ngeom_data () const inline virtual
Number of geometric Data in GeomObject: None.
Reimplemented from oomph::GeomObject.
 {return 0;}
period() [1/5]
double& OscillatingWall::period () inline
Access function to the period.
 {return T;}
period() [2/5]
double& OscillatingWall::period () inline
Access function to the period.
 {return T;}
period() [3/5]
double& OscillatingWall::period () inline
Access function to the period.
 {return T;}
period() [4/5]
double& OscillatingWall::period () inline
Access function to the period.
 {return T;}
period() [5/5]
double& OscillatingWall::period () inline
Access function to the period.
 {return T;}
position() [1/10]
void OscillatingWall::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position vector at Lagrangian coordinate zeta at time level t.
Reimplemented from oomph::GeomObject.
   {
    using namespace MathematicalConstants;
    // Smoothly ramp up the oscillation during the first period
    double ramp=1.0;
    if (Time_pt->time(t)<T)
     {
      ramp=0.5*(1.0-cos(Pi*Time_pt->time(t)/T));
     }
    // Position vector
    r[0] = zeta[0]+X_left
     -B*A*sin(2.0*3.14159*zeta[0]/Length)*
     sin(2.0*Pi*(Time_pt->time(t))/T)*ramp;
    r[1] = H+A*((Length-zeta[0])*zeta[0])/pow(0.5*Length,2)*
     sin(2.0*Pi*(Time_pt->time(t))/T)*ramp;
   } // end of "unsteady" version
References cos(), H, Global_Physical_Variables::Length, BiharmonicTestFunctions2::Pi, Eigen::bfloat16_impl::pow(), UniformPSDSelfTest::r, ramp(), sin(), plotPSD::t, oomph::Time::time(), Flag_definition::Time_pt, GlobalParameters::X_left, and Eigen::zeta().
position() [2/10]
void OscillatingWall::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position vector at Lagrangian coordinate zeta at time level t.
Reimplemented from oomph::GeomObject.
   {
    using namespace MathematicalConstants;
    // Smoothly ramp up the oscillation during the first period
    double ramp=1.0;
    if (Time_pt->time(t)<T)
     {
      ramp=0.5*(1.0-cos(Pi*Time_pt->time(t)/T));
     }
    // Position vector
    r[0] = zeta[0]+X_left
     -B*A*sin(2.0*3.14159*zeta[0]/Length)*
     sin(2.0*Pi*(Time_pt->time(t))/T)*ramp;
    r[1] = H+A*((Length-zeta[0])*zeta[0])/pow(0.5*Length,2)*
     sin(2.0*Pi*(Time_pt->time(t))/T)*ramp;
   } // end of "unsteady" version
References cos(), H, Global_Physical_Variables::Length, BiharmonicTestFunctions2::Pi, Eigen::bfloat16_impl::pow(), UniformPSDSelfTest::r, ramp(), sin(), plotPSD::t, oomph::Time::time(), Flag_definition::Time_pt, GlobalParameters::X_left, and Eigen::zeta().
position() [3/10]
void OscillatingWall::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position vector at Lagrangian coordinate zeta at time level t.
Reimplemented from oomph::GeomObject.
   {
    using namespace MathematicalConstants;
    // Smoothly ramp up the oscillation during the first period
    double ramp=1.0;
    if (Time_pt->time(t)<T)
     {
      ramp=0.5*(1.0-cos(Pi*Time_pt->time(t)/T));
     }
    if (Remain_steady_at_maximum_amplitude)
     {
      // Position vector
      r[0] = zeta[0]+X_left
       +B*A*sin(2.0*3.14159*zeta[0]/Length)*ramp;
      r[1] = H-A*((Length-zeta[0])*zeta[0])/pow(0.5*Length,2)*ramp;
     }
    else
     {
      // Position vector
      r[0] = zeta[0]+X_left
       -B*A*sin(2.0*3.14159*zeta[0]/Length)*
       sin(2.0*Pi*(Time_pt->time(t))/T)*ramp;
      r[1] = H+A*((Length-zeta[0])*zeta[0])/pow(0.5*Length,2)*
       sin(2.0*Pi*(Time_pt->time(t))/T)*ramp;
     }
   } // end of "unsteady" version
References cos(), H, Global_Physical_Variables::Length, BiharmonicTestFunctions2::Pi, Eigen::bfloat16_impl::pow(), UniformPSDSelfTest::r, ramp(), sin(), plotPSD::t, oomph::Time::time(), Flag_definition::Time_pt, GlobalParameters::X_left, and Eigen::zeta().
position() [4/10]
void OscillatingWall::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position vector at Lagrangian coordinate zeta at time level t.
Reimplemented from oomph::GeomObject.
   {
    using namespace MathematicalConstants;
    // Smoothly ramp up the oscillation during the first period
    double ramp=1.0;
    if (Time_pt->time(t)<T)
     {
      ramp=0.5*(1.0-cos(Pi*Time_pt->time(t)/T));
     }
    // Position vector
    r[0] = zeta[0]+X_left
     -B*A*sin(2.0*3.14159*zeta[0]/Length)*
     sin(2.0*Pi*(Time_pt->time(t))/T)*ramp;
    r[1] = H+A*((Length-zeta[0])*zeta[0])/pow(0.5*Length,2)*
     sin(2.0*Pi*(Time_pt->time(t))/T)*ramp;
   } // end of "unsteady" version
References cos(), H, Global_Physical_Variables::Length, BiharmonicTestFunctions2::Pi, Eigen::bfloat16_impl::pow(), UniformPSDSelfTest::r, ramp(), sin(), plotPSD::t, oomph::Time::time(), Flag_definition::Time_pt, GlobalParameters::X_left, and Eigen::zeta().
position() [5/10]
void OscillatingWall::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position vector at Lagrangian coordinate zeta at time level t.
Reimplemented from oomph::GeomObject.
   {
    using namespace MathematicalConstants;
    // Smoothly ramp up the oscillation during the first period
    double ramp=1.0;
    if (Time_pt->time(t)<T)
     {
      ramp=0.5*(1.0-cos(Pi*Time_pt->time(t)/T));
     }
    if (Remain_steady_at_maximum_amplitude)
     {
      // Position vector
      r[0] = zeta[0]+X_left
       +B*A*sin(2.0*3.14159*zeta[0]/Length)*ramp;
      r[1] = H-A*((Length-zeta[0])*zeta[0])/pow(0.5*Length,2)*ramp;
     }
    else
     {
      // Position vector
      r[0] = zeta[0]+X_left
       -B*A*sin(2.0*3.14159*zeta[0]/Length)*
       sin(2.0*Pi*(Time_pt->time(t))/T)*ramp;
      r[1] = H+A*((Length-zeta[0])*zeta[0])/pow(0.5*Length,2)*
       sin(2.0*Pi*(Time_pt->time(t))/T)*ramp;
     }
   } // end of "unsteady" version
References cos(), H, Global_Physical_Variables::Length, BiharmonicTestFunctions2::Pi, Eigen::bfloat16_impl::pow(), UniformPSDSelfTest::r, ramp(), sin(), plotPSD::t, oomph::Time::time(), Flag_definition::Time_pt, GlobalParameters::X_left, and Eigen::zeta().
position() [6/10]
void OscillatingWall::position (const Vector< double > & zeta, Vector< double > & r) const inline virtual
"Current" position vector at Lagrangian coordinate zeta
Implements oomph::GeomObject.
   {
    position (0, zeta, r);
   }
References UniformPSDSelfTest::r, and Eigen::zeta().
position() [7/10]
void OscillatingWall::position (const Vector< double > & zeta, Vector< double > & r) const inline virtual
"Current" position vector at Lagrangian coordinate zeta
Implements oomph::GeomObject.
   {
    position (0, zeta, r);
   }
References UniformPSDSelfTest::r, and Eigen::zeta().
position() [8/10]
void OscillatingWall::position (const Vector< double > & zeta, Vector< double > & r) const inline virtual
"Current" position vector at Lagrangian coordinate zeta
Implements oomph::GeomObject.
   {
    position (0, zeta, r);
   }
References UniformPSDSelfTest::r, and Eigen::zeta().
position() [9/10]
void OscillatingWall::position (const Vector< double > & zeta, Vector< double > & r) const inline virtual
"Current" position vector at Lagrangian coordinate zeta
Implements oomph::GeomObject.
   {
    position (0, zeta, r);
   }
References UniformPSDSelfTest::r, and Eigen::zeta().
position() [10/10]
void OscillatingWall::position (const Vector< double > & zeta, Vector< double > & r) const inline virtual
"Current" position vector at Lagrangian coordinate zeta
Implements oomph::GeomObject.
   {
    position (0, zeta, r);
   }
References UniformPSDSelfTest::r, and Eigen::zeta().
Member Data Documentation
A
double OscillatingWall::A private
Amplitude of oscillation.
B
double OscillatingWall::B private
Relative amplitude of horizontal wall motion.
H
double OscillatingWall::H private
Height at ends.
Length
double OscillatingWall::Length private
Length.
Remain_steady_at_maximum_amplitude
bool OscillatingWall::Remain_steady_at_maximum_amplitude private
Flag which if true causes the wall to move to it's maximum amplitude position over one period and then remains steady
T
double OscillatingWall::T private
Period of the oscillations.
Time_pt
Time * OscillatingWall::Time_pt private
Pointer to the global time object.
X_left
double OscillatingWall::X_left private
x-coordinate of left end
The documentation for this class was generated from the following files:
collapsible_channel.cc
collapsible_channel_algebraic.cc
flux_control.cc
pseudo_solid_collapsible_channel.cc
one_d_womersley.cc