MercuryDPM: HeatFluidCoupledSpecies< NormalForceSpecies > Class Template Reference
HeatFluidCoupledSpecies< NormalForceSpecies > Class Template Reference
Species for the HeatFluidCoupledParticle.
#include <HeatFluidCoupledSpecies.h>
Public Types
typedef HeatFluidCoupledInteraction< typename NormalForceSpecies::InteractionType > InteractionType
Public Types inherited from ThermalSpecies< NormalForceSpecies >
typedef ThermalInteraction< typename NormalForceSpecies::InteractionType > InteractionType
The correct Interaction type for this FrictionForceSpecies.
Public Member Functions
HeatFluidCoupledSpecies ()
The default constructor.
HeatFluidCoupledSpecies (const HeatFluidCoupledSpecies &s)
The default copy constructor.
virtual ~HeatFluidCoupledSpecies ()
The default destructor.
void write (std::ostream &os) const
Writes the species properties to an output stream.
void read (std::istream &is)
Reads the species properties from an input stream.
std::string getBaseName () const
Used in Species::getName to obtain a unique name for each Species.
Mdouble getMassTransferCoefficient () const
Allows massTransferCoefficient_ to be accessed.
void setMassTransferCoefficient (Mdouble massTransferCoefficient)
Allows massTransferCoefficient_ to be changed.
Mdouble getLatentHeatVaporization () const
Allows latentHeatVaporization_ to be accessed.
void setLatentHeatVaporization (Mdouble latentHeatVaporization)
Allows latentHeatVaporization_ to be changed.
Mdouble getLiquidDensity () const
Allows liquidDensity_ to be accessed.
void setLiquidDensity (Mdouble liquidDensity)
Allows liquidDensity_ to be changed.
Mdouble getEvaporationCoefficientA () const
Allows evaporationCoefficientA_ to be accessed.
void setEvaporationCoefficientA (Mdouble evaporationCoefficientA)
Allows evaporationCoefficientA_ to be changed.
Mdouble getEvaporationCoefficientB () const
Allows evaporationCoefficientB_ to be accessed.
void setEvaporationCoefficientB (Mdouble evaporationCoefficientB)
Allows evaporationCoefficientB_ to be changed.
Mdouble getAmbientHumidity () const
Allows ambientHumidity_ to be accessed.
void setAmbientHumidity (Mdouble ambientHumidity)
Allows ambientHumidity_ to be changed.
Mdouble getAmbientEquilibriumMoistureContent () const
Allows ambientEquilibriumMoistureContent_ to be accessed.
void setAmbientEquilibriumMoistureContent (Mdouble ambientEquilibriumMoistureContent)
Allows ambientEquilibriumMoistureContent_ to be changed.
Mdouble getAmbientVapourConcentration () const
Allows ambientVapourConcentration_ to be accessed.
void setAmbientVapourConcentration (Mdouble ambientVapourConcentration)
Allows ambientVapourConcentration_ to be changed.
void actionsAfterTimeStep (BaseParticle *particle) const override
std::array< double, 2 > f (double liquidVolume, double temperature, double mass, double surfaceArea) const
f1 is used in Runge–Kutta method.
Public Member Functions inherited from ThermalSpecies< NormalForceSpecies >
ThermalSpecies ()
The default constructor.
ThermalSpecies (const ThermalSpecies &s)
The default copy constructor.
virtual ~ThermalSpecies ()
The default destructor.
void write (std::ostream &os) const
Writes the species properties to an output stream.
void read (std::istream &is)
Reads the species properties from an input stream.
std::string getBaseName () const
Used in Species::getName to obtain a unique name for each Species.
void actionsAfterTimeStep (BaseParticle *particle) const override
Computes the heat transfer rate (.
Mdouble getHeatCapacity () const
Allows heatCapacity_ to be accessed.
void setHeatCapacity (Mdouble heatCapacity)
Allows heatCapacity_ to be changed.
Mdouble getThermalConductivity () const
Allows heatCapacity_ to be accessed.
void setThermalConductivity (Mdouble thermalConductivity)
Allows heatCapacity_ to be changed.
Mdouble getAmbientTemperature () const
void setAmbientTemperature (Mdouble ambientTemperature)
Vec3D getAmbientVelocity () const
Allows ambientVelocity_ to be accessed.
void setAmbientVelocity (Vec3D ambientVelocity)
Allows ambientVelocity_ to be changed.
Mdouble getAmbientThermalConductivity () const
Allows ambientThermalConductivity_ to be accessed.
void setAmbientThermalConductivity (Mdouble ambientThermalConductivity)
Allows ambientThermalConductivity_ to be changed.
Mdouble getAmbientDynamicViscosity () const
Allows ambientDynamicViscosity_ to be accessed.
void setAmbientDynamicViscosity (Mdouble ambientDynamicViscosity)
Allows ambientDynamicViscosity_ to be changed.
Mdouble getAmbientHeatCapacity () const
Allows ambientHeatCapacity_ to be accessed.
void setAmbientHeatCapacity (Mdouble ambientHeatCapacity)
Allows ambientHeatCapacity_ to be changed.
Mdouble getAmbientDensity () const
Allows ambientDensity_ to be accessed.
void setAmbientDensity (Mdouble ambientDensity)
Allows ambientDensity_ to be changed.
Private Attributes
Mdouble massTransferCoefficient_
The mass transfer rate (m/s)
Mdouble latentHeatVaporization_
The latent heat of vaporization (J/kg)
Mdouble liquidDensity_
The liquid density (kg/m^3)
Mdouble evaporationCoefficientA_
The evaporation coefficient a (dimensionless)
Mdouble evaporationCoefficientB_
The evaporation coefficient b (dimensionless)
Mdouble ambientHumidity_
The ambient humidity (dimensionless, between 0 and 1, but cannot be 0)
Mdouble ambientEquilibriumMoistureContent_
The ambient equilibrium moisture content (dimensionless, between 0 and 1).
Mdouble ambientVapourConcentration_
The ambient vapour concentration (kg/m^3).
Detailed Description
template<class NormalForceSpecies>
class HeatFluidCoupledSpecies< NormalForceSpecies >
Species for the HeatFluidCoupledParticle.
Member Typedef Documentation
InteractionType
template<class NormalForceSpecies > typedef HeatFluidCoupledInteraction<typename NormalForceSpecies::InteractionType> HeatFluidCoupledSpecies< NormalForceSpecies >::InteractionType
Constructor & Destructor Documentation
HeatFluidCoupledSpecies() [1/2]
template<class NormalForceSpecies > HeatFluidCoupledSpecies< NormalForceSpecies >::HeatFluidCoupledSpecies
The default constructor.
         : ThermalSpecies<NormalForceSpecies>()
 {
     massTransferCoefficient_=0.0;
     latentHeatVaporization_=0.0;
     liquidDensity_=1.0;
     evaporationCoefficientA_=0.0;
     evaporationCoefficientB_=0.0;
     // note, this default value is unrealistically high; 0.3 is realistic.
     ambientHumidity_=1.0;
     ambientEquilibriumMoistureContent_=0.0;
     ambientVapourConcentration_=0.0;
 }
References HeatFluidCoupledSpecies< NormalForceSpecies >::ambientEquilibriumMoistureContent_, HeatFluidCoupledSpecies< NormalForceSpecies >::ambientHumidity_, HeatFluidCoupledSpecies< NormalForceSpecies >::ambientVapourConcentration_, HeatFluidCoupledSpecies< NormalForceSpecies >::evaporationCoefficientA_, HeatFluidCoupledSpecies< NormalForceSpecies >::evaporationCoefficientB_, HeatFluidCoupledSpecies< NormalForceSpecies >::latentHeatVaporization_, HeatFluidCoupledSpecies< NormalForceSpecies >::liquidDensity_, and HeatFluidCoupledSpecies< NormalForceSpecies >::massTransferCoefficient_.
HeatFluidCoupledSpecies() [2/2]
template<class NormalForceSpecies > HeatFluidCoupledSpecies< NormalForceSpecies >::HeatFluidCoupledSpecies (const HeatFluidCoupledSpecies< NormalForceSpecies > & s)
The default copy constructor.
         : ThermalSpecies<NormalForceSpecies>(s)
 {
     massTransferCoefficient_= s.massTransferCoefficient_;
     latentHeatVaporization_= s.latentHeatVaporization_;
     liquidDensity_=s.liquidDensity_;
     evaporationCoefficientA_=s.evaporationCoefficientA_;
     evaporationCoefficientB_=s.evaporationCoefficientB_;
     ambientHumidity_=s.ambientHumidity_;
     ambientEquilibriumMoistureContent_=s.ambientEquilibriumMoistureContent_;
     ambientVapourConcentration_=s.ambientVapourConcentration_;
 }
References HeatFluidCoupledSpecies< NormalForceSpecies >::ambientEquilibriumMoistureContent_, HeatFluidCoupledSpecies< NormalForceSpecies >::ambientHumidity_, HeatFluidCoupledSpecies< NormalForceSpecies >::ambientVapourConcentration_, HeatFluidCoupledSpecies< NormalForceSpecies >::evaporationCoefficientA_, HeatFluidCoupledSpecies< NormalForceSpecies >::evaporationCoefficientB_, HeatFluidCoupledSpecies< NormalForceSpecies >::latentHeatVaporization_, HeatFluidCoupledSpecies< NormalForceSpecies >::liquidDensity_, HeatFluidCoupledSpecies< NormalForceSpecies >::massTransferCoefficient_, and s.
~HeatFluidCoupledSpecies()
template<class NormalForceSpecies > HeatFluidCoupledSpecies< NormalForceSpecies >::~HeatFluidCoupledSpecies virtual
The default destructor.
 {}
Member Function Documentation
actionsAfterTimeStep()
template<class NormalForceSpecies > void HeatFluidCoupledSpecies< NormalForceSpecies >::actionsAfterTimeStep (BaseParticle * particle) const override
 {
     double dt = baseParticle->getHandler()->getDPMBase()->getTimeStep();
     auto p = dynamic_cast<HeatFluidCoupledParticle*>(baseParticle);
     double mass = p->getMass();
     double surfaceArea = p->getSurfaceArea();
     // Runge–Kutta method.
     std::array<double,2> k1 = f(p->getLiquidVolume()               , p->getTemperature()               , mass, surfaceArea);
     std::array<double,2> k2 = f(p->getLiquidVolume() + 0.5*dt*k1[0], p->getTemperature() + 0.5*dt*k1[1], mass, surfaceArea);
     std::array<double,2> k3 = f(p->getLiquidVolume() + 0.5*dt*k2[0], p->getTemperature() + 0.5*dt*k2[1], mass, surfaceArea);
     std::array<double,2> k4 = f(p->getLiquidVolume() +     dt*k3[0], p->getTemperature() +     dt*k3[1], mass, surfaceArea);
     double dLiquidVolume = dt * (k1[0] + 2*k2[0] + 2*k3[0] + k4[0]) / 6.0;
     double dTemperature  = dt * (k1[1] + 2*k2[1] + 2*k3[1] + k4[1]) / 6.0;
     // Change sign, so we can think in terms of subtracting a positive number, instead of adding a negative number.
     // Keep in mind, it is still possible that we are adding liquid/temperature (so now subtracting a negative number),
     // however, since there is only a lower limit of 0 but no upper limit, this is easier to think about.
     dLiquidVolume = -dLiquidVolume;
     dTemperature = -dTemperature;
     // Subtract as much as possible from the liquid film. Any remainder is subtracted from the liquid bridges.
     double dLiquidFilm = std::min(dLiquidVolume, p->getLiquidVolume());
     double remainder = dLiquidVolume - dLiquidFilm;
     if (remainder > 0.0)
     {
         // Get the total liquid bridge volume. Note, don't use p->getLiquidBridgeVolume() as it halves the bridges with
         // other particles. The order of handling the particles matters for how much liquid bridge is still available
         // to them. It might seem more correct to use half the bridge instead of the full bridge, however that would
         // only add an error, because the second particle halving the bridge would include the evaporated volume of the
         // first particle. So instead of using L/2 it would use (L-evap)/2, which completely undoes the "correction" of
         // halving the bridges in the first place.
         double liquidBridgeVolume = 0.0;
         for (auto i : p->getInteractions())
         {
             auto j = dynamic_cast<LiquidMigrationWilletInteraction*>(i);
             liquidBridgeVolume += j->getLiquidBridgeVolume();
         }
         double dLiquidBridge = std::min(remainder, liquidBridgeVolume);
         remainder -= dLiquidBridge;
         double factor = liquidBridgeVolume == 0.0 ? 0.0 : dLiquidBridge / liquidBridgeVolume;
         for (auto i : p->getInteractions())
         {
             auto j = dynamic_cast<LiquidMigrationWilletInteraction*>(i);
             j->addLiquidBridgeVolumeByEvaporation(-factor * j->getLiquidBridgeVolume());
         }
     }
     p->addLiquidVolume(-dLiquidFilm);
     p->addTotalEvaporatedLiquidVolume(dLiquidVolume - remainder);
     // If not all liquid could be removed, correct the temperature to be removed.
     double dLiquidVolumeFactor = dLiquidVolume == 0.0 ? 0.0 : (dLiquidVolume - remainder) / dLiquidVolume;
     p->setTemperature(std::max(0.0, p->getTemperature() - dTemperature * dLiquidVolumeFactor));
 }
References f(), BaseHandler< T >::getDPMBase(), BaseParticle::getHandler(), DPMBase::getTimeStep(), i, j, max, min, and p.
f()
template<class NormalForceSpecies > std::array< double, 2 > HeatFluidCoupledSpecies< NormalForceSpecies >::f (double liquidVolume, double temperature, double mass, double surfaceArea) const
f1 is used in Runge–Kutta method.
Computes the drying and cooling rate of a particle; based on equations in (Azmir et al., 2018), which are summarised in EvaporationModel.pdf
Parameters
liquidVolume_ Liquid film volume
temperature_ Temperature of particle
mass Mass of particle
surfaceArea Surface area of particle
Returns
 {
     // Saturated vapour concentration  (kg/m^3), eq(7)
     // Dependency on temperature is valid between 1 and 200 degree Celsius
     // (it is unphysically decreasing between 0 and 1 degree),
     // extrapolated as linear functions
     double dT = temperature - 273;
     double saturatedVapourConcentration = dT < 1 ? 8.319815774e-3 * temperature / 274 :
             (((4.844e-9*dT - 1.4807e-7)*dT + 2.6572e-5)*dT - 4.8613e-5)*dT + 8.342e-3;
     // Relative activation energy of evaporation, eq(6)
     double equilibriumActivationEnergy = -constants::R * this->getAmbientTemperature() * log(getAmbientHumidity());
     // \todo what is the difference between the variable X and Y in Azmir?
     double moistureContent = liquidVolume * getLiquidDensity() / mass;
     double activationEnergy = equilibriumActivationEnergy * (moistureContent - getAmbientEquilibriumMoistureContent());
     // Vapour concentrations at the particle-medium interface (kg/m^3), eq(5)
     // Implemented such that the code does not necessarily fail if temperature is 0
     double interfaceVapourConcentration = temperature == 0 ? 0.0 :
             exp(-activationEnergy / (constants::R * temperature)) * saturatedVapourConcentration;
     // Drying rate of liquid film mass (kg/s), eq (4)
     double dLiquidMass = -getMassTransferCoefficient() * surfaceArea * (interfaceVapourConcentration - getAmbientVapourConcentration());
     // Drying rate of liquid film volume (kg/s), eq (3)
     double dLiquidVolume = dLiquidMass / getLiquidDensity();
     // Heat of evaporation (J/s), eq (2)
     double heatOfEvaporation = getLatentHeatVaporization() * (1.0 + getEvaporationCoefficientA() *
             exp((getEvaporationCoefficientB() * getLiquidDensity() / mass) * liquidVolume)) * dLiquidMass;
     // Cooling rate of particle (K/s), eq (1)
     double dTemperature = heatOfEvaporation / (mass * this->getHeatCapacity());
     return { dLiquidVolume, dTemperature };
 }
References Eigen::bfloat16_impl::exp(), Eigen::bfloat16_impl::log(), and constants::R.
getAmbientEquilibriumMoistureContent()
template<class NormalForceSpecies > Mdouble HeatFluidCoupledSpecies< NormalForceSpecies >::getAmbientEquilibriumMoistureContent
Allows ambientEquilibriumMoistureContent_ to be accessed.
 {
     return ambientEquilibriumMoistureContent_;
 }
getAmbientHumidity()
template<class NormalForceSpecies > Mdouble HeatFluidCoupledSpecies< NormalForceSpecies >::getAmbientHumidity
Allows ambientHumidity_ to be accessed.
 {
     return ambientHumidity_;
 }
getAmbientVapourConcentration()
template<class NormalForceSpecies > Mdouble HeatFluidCoupledSpecies< NormalForceSpecies >::getAmbientVapourConcentration
Allows ambientVapourConcentration_ to be accessed.
 {
     return ambientVapourConcentration_;
 }
getBaseName()
template<class NormalForceSpecies > std::string HeatFluidCoupledSpecies< NormalForceSpecies >::getBaseName
Used in Species::getName to obtain a unique name for each Species.
 {
     return "HeatFluidCoupled" + NormalForceSpecies::getBaseName();
 }
getEvaporationCoefficientA()
template<class NormalForceSpecies > Mdouble HeatFluidCoupledSpecies< NormalForceSpecies >::getEvaporationCoefficientA
Allows evaporationCoefficientA_ to be accessed.
 {
     return evaporationCoefficientA_;
 }
getEvaporationCoefficientB()
template<class NormalForceSpecies > Mdouble HeatFluidCoupledSpecies< NormalForceSpecies >::getEvaporationCoefficientB
Allows evaporationCoefficientB_ to be accessed.
 {
     return evaporationCoefficientB_;
 }
getLatentHeatVaporization()
template<class NormalForceSpecies > Mdouble HeatFluidCoupledSpecies< NormalForceSpecies >::getLatentHeatVaporization
Allows latentHeatVaporization_ to be accessed.
 {
     return latentHeatVaporization_;
 }
getLiquidDensity()
template<class NormalForceSpecies > Mdouble HeatFluidCoupledSpecies< NormalForceSpecies >::getLiquidDensity
Allows liquidDensity_ to be accessed.
 {
     return liquidDensity_;
 }
getMassTransferCoefficient()
template<class NormalForceSpecies > Mdouble HeatFluidCoupledSpecies< NormalForceSpecies >::getMassTransferCoefficient
Allows massTransferCoefficient_ to be accessed.
 {
     return massTransferCoefficient_;
 }
read()
template<class NormalForceSpecies > void HeatFluidCoupledSpecies< NormalForceSpecies >::read (std::istream & is)
Reads the species properties from an input stream.
 {
     std::string dummy;
     ThermalSpecies<NormalForceSpecies>::read(is);
     is >> dummy >> massTransferCoefficient_;
     is >> dummy >> latentHeatVaporization_;
     is >> dummy >> liquidDensity_;
     is >> dummy >> evaporationCoefficientA_;
     is >> dummy >> evaporationCoefficientB_;
     is >> dummy >> ambientHumidity_;
     is >> dummy >> ambientEquilibriumMoistureContent_;
     is >> dummy >> ambientVapourConcentration_;
     double ambientTemperature;
     if (helpers::readOptionalVariable<Mdouble>(is, "ambientTemperature", ambientTemperature)) {
         ThermalSpecies<NormalForceSpecies>::setAmbientTemperature(ambientTemperature);
     }
 }
References ThermalSpecies< NormalForceSpecies >::read(), ThermalSpecies< NormalForceSpecies >::setAmbientTemperature(), and oomph::Global_string_for_annotation::string().
setAmbientEquilibriumMoistureContent()
template<class NormalForceSpecies > void HeatFluidCoupledSpecies< NormalForceSpecies >::setAmbientEquilibriumMoistureContent (Mdouble ambientEquilibriumMoistureContent)
Allows ambientEquilibriumMoistureContent_ to be changed.
 {
     logger.assert_always(ambientEquilibriumMoistureContent >= 0,
                          "[HeatFluidCoupledSpecies<>::setAmbientEquilibriumMoistureContent(%)] value has to be positive",
                          ambientEquilibriumMoistureContent);
     ambientEquilibriumMoistureContent_ = ambientEquilibriumMoistureContent;
 }
References logger.
setAmbientHumidity()
template<class NormalForceSpecies > void HeatFluidCoupledSpecies< NormalForceSpecies >::setAmbientHumidity (Mdouble ambientHumidity)
Allows ambientHumidity_ to be changed.
 {
     //note, this is not allowed to be zero!
     logger.assert_always(ambientHumidity > 0,
                          "[HeatFluidCoupledSpecies<>::setAmbientHumidity(%)] value has to be positive",
                          ambientHumidity);
     ambientHumidity_ = ambientHumidity;
 }
References logger.
setAmbientVapourConcentration()
template<class NormalForceSpecies > void HeatFluidCoupledSpecies< NormalForceSpecies >::setAmbientVapourConcentration (Mdouble ambientVapourConcentration)
Allows ambientVapourConcentration_ to be changed.
 {
     logger.assert_always(ambientVapourConcentration >= 0,
                          "[HeatFluidCoupledSpecies<>::setAmbientVapourConcentration(%)] value has to be positive",
                          ambientVapourConcentration);
     ambientVapourConcentration_ = ambientVapourConcentration;
 }
References logger.
setEvaporationCoefficientA()
template<class NormalForceSpecies > void HeatFluidCoupledSpecies< NormalForceSpecies >::setEvaporationCoefficientA (Mdouble evaporationCoefficientA)
Allows evaporationCoefficientA_ to be changed.
 {
     logger.assert_always(evaporationCoefficientA >= 0,
                          "[HeatFluidCoupledSpecies<>::setEvaporationCoefficientA(%)] value has to be positive",
                          evaporationCoefficientA);
     evaporationCoefficientA_ = evaporationCoefficientA;
 }
References logger.
setEvaporationCoefficientB()
template<class NormalForceSpecies > void HeatFluidCoupledSpecies< NormalForceSpecies >::setEvaporationCoefficientB (Mdouble evaporationCoefficientB)
Allows evaporationCoefficientB_ to be changed.
 {
     logger.assert_always(evaporationCoefficientB <= 0,
                          "[HeatFluidCoupledSpecies<>::setEvaporationCoefficientB(%)] value has to be negative",
                          evaporationCoefficientB);
     evaporationCoefficientB_ = evaporationCoefficientB;
 }
References logger.
setLatentHeatVaporization()
template<class NormalForceSpecies > void HeatFluidCoupledSpecies< NormalForceSpecies >::setLatentHeatVaporization (Mdouble latentHeatVaporization)
Allows latentHeatVaporization_ to be changed.
 {
     logger.assert_always(latentHeatVaporization > 0,
                          "[HeatFluidCoupledSpecies<>::setLatentHeatVaporization(%)] value has to be positive",
                          latentHeatVaporization);
     latentHeatVaporization_ = latentHeatVaporization;
 }
References logger.
setLiquidDensity()
template<class NormalForceSpecies > void HeatFluidCoupledSpecies< NormalForceSpecies >::setLiquidDensity (Mdouble liquidDensity)
Allows liquidDensity_ to be changed.
 {
     logger.assert_always(liquidDensity > 0,
                          "[HeatFluidCoupledSpecies<>::setLiquidDensity(%)] value has to be positive",
                          liquidDensity);
     liquidDensity_ = liquidDensity;
 }
References logger.
setMassTransferCoefficient()
template<class NormalForceSpecies > void HeatFluidCoupledSpecies< NormalForceSpecies >::setMassTransferCoefficient (Mdouble massTransferCoefficient)
Allows massTransferCoefficient_ to be changed.
 {
     logger.assert_always(massTransferCoefficient > 0,
                          "[HeatFluidCoupledSpecies<>::setMassTransferCoefficient(%)] value has to be positive",
                          massTransferCoefficient);
     massTransferCoefficient_ = massTransferCoefficient;
 }
References logger.
write()
template<class NormalForceSpecies > void HeatFluidCoupledSpecies< NormalForceSpecies >::write (std::ostream & os) const
Writes the species properties to an output stream.
 {
     ThermalSpecies<NormalForceSpecies>::write(os);
     os << " massTransferCoefficient " << massTransferCoefficient_;
     os << " latentHeatVaporization " << latentHeatVaporization_;
     os << " liquidDensity " << liquidDensity_;
     os << " evaporationCoefficientA " << evaporationCoefficientA_;
     os << " evaporationCoefficientA " << evaporationCoefficientB_;
     os << " ambientHumidity " << ambientHumidity_;
     os << " ambientEquilibriumMoistureContent " << ambientEquilibriumMoistureContent_;
     os << " ambientVapourConcentration " << ambientVapourConcentration_;
 }
References ThermalSpecies< NormalForceSpecies >::write().
Member Data Documentation
ambientEquilibriumMoistureContent_
template<class NormalForceSpecies > Mdouble HeatFluidCoupledSpecies< NormalForceSpecies >::ambientEquilibriumMoistureContent_ private
The ambient equilibrium moisture content (dimensionless, between 0 and 1).
Referenced by HeatFluidCoupledSpecies< NormalForceSpecies >::HeatFluidCoupledSpecies().
ambientHumidity_
template<class NormalForceSpecies > Mdouble HeatFluidCoupledSpecies< NormalForceSpecies >::ambientHumidity_ private
The ambient humidity (dimensionless, between 0 and 1, but cannot be 0)
Referenced by HeatFluidCoupledSpecies< NormalForceSpecies >::HeatFluidCoupledSpecies().
ambientVapourConcentration_
template<class NormalForceSpecies > Mdouble HeatFluidCoupledSpecies< NormalForceSpecies >::ambientVapourConcentration_ private
The ambient vapour concentration (kg/m^3).
Referenced by HeatFluidCoupledSpecies< NormalForceSpecies >::HeatFluidCoupledSpecies().
evaporationCoefficientA_
template<class NormalForceSpecies > Mdouble HeatFluidCoupledSpecies< NormalForceSpecies >::evaporationCoefficientA_ private
The evaporation coefficient a (dimensionless)
Referenced by HeatFluidCoupledSpecies< NormalForceSpecies >::HeatFluidCoupledSpecies().
evaporationCoefficientB_
template<class NormalForceSpecies > Mdouble HeatFluidCoupledSpecies< NormalForceSpecies >::evaporationCoefficientB_ private
The evaporation coefficient b (dimensionless)
Referenced by HeatFluidCoupledSpecies< NormalForceSpecies >::HeatFluidCoupledSpecies().
latentHeatVaporization_
template<class NormalForceSpecies > Mdouble HeatFluidCoupledSpecies< NormalForceSpecies >::latentHeatVaporization_ private
The latent heat of vaporization (J/kg)
Referenced by HeatFluidCoupledSpecies< NormalForceSpecies >::HeatFluidCoupledSpecies().
liquidDensity_
template<class NormalForceSpecies > Mdouble HeatFluidCoupledSpecies< NormalForceSpecies >::liquidDensity_ private
The liquid density (kg/m^3)
Referenced by HeatFluidCoupledSpecies< NormalForceSpecies >::HeatFluidCoupledSpecies().
massTransferCoefficient_
template<class NormalForceSpecies > Mdouble HeatFluidCoupledSpecies< NormalForceSpecies >::massTransferCoefficient_ private
The mass transfer rate (m/s)
Referenced by HeatFluidCoupledSpecies< NormalForceSpecies >::HeatFluidCoupledSpecies().
The documentation for this class was generated from the following files:
HeatFluidCoupledInteraction.h
HeatFluidCoupledSpecies.h