MercuryDPM: NavierStokesProblem< ELEMENT > Class Template Reference
NavierStokesProblem< ELEMENT > Class Template Reference
Entry flow problem in quarter tube domain.
Public Member Functions
NavierStokesProblem (DocInfo &doc_info, const string &node_file_name, const string &element_file_name, const string &face_file_name)
Constructor: Pass DocInfo object and file names.
~NavierStokesProblem ()
Destructor (empty)
void actions_after_newton_solve ()
Doc the solution after solve.
void actions_before_newton_solve ()
Update the problem specs before solve.
void doc_solution ()
Doc the solution.
TetgenMesh< ELEMENT > * mesh_pt ()
NavierStokesProblem ()
Constructor.
~NavierStokesProblem ()
Destructor.
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_newton_solve ()
Update the problem specs before solve (empty)
void actions_after_parameter_increase (double *const &parameter_pt)
Update the problem specs after an increase in a parameter.
void create_spacetime_mesh ()
void apply_boundary_conditions ()
void pin_redundant_temporal_nodes ()
void assign_time_slice_id ()
Assign the time slice number to each element.
void set_up_spacetime_solver ()
Set up the solver for this Problem.
void complete_problem_setup ()
Complete problem setup: pass pointers to physical variables.
void run_natural_continuation (double &parameter, const double &parameter_target, const unsigned &max_n_parameter_step)
void doc_solution (const bool &doc_spacetime_soln=false)
Doc the solution.
Public Member Functions inherited from oomph::Problem
virtual void debug_hook_fct (const unsigned &i)
void set_analytic_dparameter (double *const &parameter_pt)
void unset_analytic_dparameter (double *const &parameter_pt)
bool is_dparameter_calculated_analytically (double *const &parameter_pt)
void set_analytic_hessian_products ()
void unset_analytic_hessian_products ()
bool are_hessian_products_calculated_analytically ()
void set_pinned_values_to_zero ()
bool distributed () const
virtual void actions_before_adapt ()
virtual void actions_after_adapt ()
Actions that are to be performed after a mesh adaptation.
OomphCommunicator * communicator_pt ()
access function to the oomph-lib communicator
const OomphCommunicator * communicator_pt () const
access function to the oomph-lib communicator, const version
Problem ()
Problem (const Problem &dummy)=delete
Broken copy constructor.
void operator= (const Problem &)=delete
Broken assignment operator.
virtual ~Problem ()
Virtual destructor to clean up memory.
Mesh *& mesh_pt ()
Return a pointer to the global mesh.
Mesh *const & mesh_pt () const
Return a pointer to the global mesh (const version)
Mesh *& mesh_pt (const unsigned &imesh)
Mesh *const & mesh_pt (const unsigned &imesh) const
Return a pointer to the i-th submesh (const version)
unsigned nsub_mesh () const
Return number of submeshes.
unsigned add_sub_mesh (Mesh *const &mesh_pt)
void flush_sub_meshes ()
void build_global_mesh ()
void rebuild_global_mesh ()
LinearSolver *& linear_solver_pt ()
Return a pointer to the linear solver object.
LinearSolver *const & linear_solver_pt () const
Return a pointer to the linear solver object (const version)
LinearSolver *& mass_matrix_solver_for_explicit_timestepper_pt ()
LinearSolver * mass_matrix_solver_for_explicit_timestepper_pt () const
EigenSolver *& eigen_solver_pt ()
Return a pointer to the eigen solver object.
EigenSolver *const & eigen_solver_pt () const
Return a pointer to the eigen solver object (const version)
Time *& time_pt ()
Return a pointer to the global time object.
Time * time_pt () const
Return a pointer to the global time object (const version).
double & time ()
Return the current value of continuous time.
double time () const
Return the current value of continuous time (const version)
TimeStepper *& time_stepper_pt ()
const TimeStepper * time_stepper_pt () const
TimeStepper *& time_stepper_pt (const unsigned &i)
Return a pointer to the i-th timestepper.
ExplicitTimeStepper *& explicit_time_stepper_pt ()
Return a pointer to the explicit timestepper.
unsigned long set_timestepper_for_all_data (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data=false)
virtual void shift_time_values ()
Shift all values along to prepare for next timestep.
AssemblyHandler *& assembly_handler_pt ()
Return a pointer to the assembly handler object.
AssemblyHandler *const & assembly_handler_pt () const
Return a pointer to the assembly handler object (const version)
double & minimum_dt ()
Access function to min timestep in adaptive timestepping.
double & maximum_dt ()
Access function to max timestep in adaptive timestepping.
unsigned & max_newton_iterations ()
Access function to max Newton iterations before giving up.
void problem_is_nonlinear (const bool &prob_lin)
Access function to Problem_is_nonlinear.
double & max_residuals ()
bool & time_adaptive_newton_crash_on_solve_fail ()
Access function for Time_adaptive_newton_crash_on_solve_fail.
double & newton_solver_tolerance ()
void add_time_stepper_pt (TimeStepper *const &time_stepper_pt)
void set_explicit_time_stepper_pt (ExplicitTimeStepper *const &explicit_time_stepper_pt)
void initialise_dt (const double &dt)
void initialise_dt (const Vector< double > &dt)
Data *& global_data_pt (const unsigned &i)
Return a pointer to the the i-th global data object.
void add_global_data (Data *const &global_data_pt)
void flush_global_data ()
LinearAlgebraDistribution *const & dof_distribution_pt () const
Return the pointer to the dof distribution (read-only)
unsigned long ndof () const
Return the number of dofs.
unsigned ntime_stepper () const
Return the number of time steppers.
unsigned nglobal_data () const
Return the number of global data values.
unsigned self_test ()
Self-test: Check meshes and global data. Return 0 for OK.
void enable_store_local_dof_pt_in_elements ()
void disable_store_local_dof_pt_in_elements ()
unsigned long assign_eqn_numbers (const bool &assign_local_eqn_numbers=true)
void describe_dofs (std::ostream &out= *(oomph_info.stream_pt())) const
void enable_discontinuous_formulation ()
void disable_discontinuous_formulation ()
void get_dofs (DoubleVector &dofs) const
void get_dofs (const unsigned &t, DoubleVector &dofs) const
Return vector of the t'th history value of all dofs.
void set_dofs (const DoubleVector &dofs)
Set the values of the dofs.
void set_dofs (const unsigned &t, DoubleVector &dofs)
Set the history values of the dofs.
void set_dofs (const unsigned &t, Vector< double * > &dof_pt)
void add_to_dofs (const double &lambda, const DoubleVector &increment_dofs)
Add lambda x incremenet_dofs[l] to the l-th dof.
double * global_dof_pt (const unsigned &i)
double & dof (const unsigned &i)
i-th dof in the problem
double dof (const unsigned &i) const
i-th dof in the problem (const version)
double *& dof_pt (const unsigned &i)
Pointer to i-th dof in the problem.
double * dof_pt (const unsigned &i) const
Pointer to i-th dof in the problem (const version)
virtual void get_inverse_mass_matrix_times_residuals (DoubleVector &Mres)
virtual void get_dvaluesdt (DoubleVector &f)
virtual void get_residuals (DoubleVector &residuals)
Get the total residuals Vector for the problem.
virtual void get_jacobian (DoubleVector &residuals, DenseDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CRDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CCDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, SumOfMatrices &jacobian)
void get_fd_jacobian (DoubleVector &residuals, DenseMatrix< double > &jacobian)
Get the full Jacobian by finite differencing.
void get_derivative_wrt_global_parameter (double *const &parameter_pt, DoubleVector &result)
void get_hessian_vector_products (DoubleVectorWithHaloEntries const &Y, Vector< DoubleVectorWithHaloEntries > const &C, Vector< DoubleVectorWithHaloEntries > &product)
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, Vector< DoubleVector > &eigenvector, const bool &steady=true)
Solve the eigenproblem.
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, const bool &steady=true)
virtual void get_eigenproblem_matrices (CRDoubleMatrix &mass_matrix, CRDoubleMatrix &main_matrix, const double &shift=0.0)
void assign_eigenvector_to_dofs (DoubleVector &eigenvector)
Assign the eigenvector passed to the function to the dofs.
void add_eigenvector_to_dofs (const double &epsilon, const DoubleVector &eigenvector)
void store_current_dof_values ()
Store the current values of the degrees of freedom.
void restore_dof_values ()
Restore the stored values of the degrees of freedom.
void enable_jacobian_reuse ()
void disable_jacobian_reuse ()
Disable recycling of Jacobian in Newton iteration.
bool jacobian_reuse_is_enabled ()
Is recycling of Jacobian in Newton iteration enabled?
bool & use_predictor_values_as_initial_guess ()
void newton_solve ()
Use Newton method to solve the problem.
void enable_globally_convergent_newton_method ()
enable globally convergent Newton method
void disable_globally_convergent_newton_method ()
disable globally convergent Newton method
void newton_solve (unsigned const &max_adapt)
void steady_newton_solve (unsigned const &max_adapt=0)
void copy (Problem *orig_problem_pt)
virtual Problem * make_copy ()
virtual void read (std::ifstream &restart_file, bool &unsteady_restart)
virtual void read (std::ifstream &restart_file)
virtual void dump (std::ofstream &dump_file) const
void dump (const std::string &dump_file_name) const
void delete_all_external_storage ()
virtual void symmetrise_eigenfunction_for_adaptive_pitchfork_tracking ()
double * bifurcation_parameter_pt () const
void get_bifurcation_eigenfunction (Vector< DoubleVector > &eigenfunction)
void activate_fold_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const DoubleVector &normalisation, const bool &block_solve=true)
void activate_pitchfork_tracking (double *const &parameter_pt, const DoubleVector &symmetry_vector, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const double &omega, const DoubleVector &null_real, const DoubleVector &null_imag, const bool &block_solve=true)
void deactivate_bifurcation_tracking ()
void reset_assembly_handler_to_default ()
Reset the system to the standard non-augemented state.
double arc_length_step_solve (double *const &parameter_pt, const double &ds, const unsigned &max_adapt=0)
double arc_length_step_solve (Data *const &data_pt, const unsigned &data_index, const double &ds, const unsigned &max_adapt=0)
void reset_arc_length_parameters ()
int & sign_of_jacobian ()
void explicit_timestep (const double &dt, const bool &shift_values=true)
Take an explicit timestep of size dt.
void unsteady_newton_solve (const double &dt)
void unsteady_newton_solve (const double &dt, const bool &shift_values)
void unsteady_newton_solve (const double &dt, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const unsigned &suppress_resolve_after_spatial_adapt_flag, const bool &first, const bool &shift=true)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon, const bool &shift_values)
void assign_initial_values_impulsive ()
void assign_initial_values_impulsive (const double &dt)
void calculate_predictions ()
Calculate predictions.
void enable_mass_matrix_reuse ()
void disable_mass_matrix_reuse ()
bool mass_matrix_reuse_is_enabled ()
Return whether the mass matrix is being reused.
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly (DocInfo &doc_info)
void refine_uniformly_and_prune (DocInfo &doc_info)
void refine_uniformly ()
void refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform refinement for submesh i_mesh with documentation.
void refine_uniformly (const unsigned &i_mesh)
Do uniform refinement for submesh i_mesh without documentation.
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly (DocInfo &doc_info)
void p_refine_uniformly_and_prune (DocInfo &doc_info)
void p_refine_uniformly ()
void p_refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-refinement for submesh i_mesh with documentation.
void p_refine_uniformly (const unsigned &i_mesh)
Do uniform p-refinement for submesh i_mesh without documentation.
void refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const unsigned &i_mesh, const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void refine_selected_elements (const Vector< Vector< RefineableElement * >> &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void p_refine_selected_elements (const Vector< Vector< PRefineableElement * >> &elements_to_be_refined_pt)
unsigned unrefine_uniformly ()
unsigned unrefine_uniformly (const unsigned &i_mesh)
void p_unrefine_uniformly (DocInfo &doc_info)
void p_unrefine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-unrefinement for submesh i_mesh without documentation.
void adapt (unsigned &n_refined, unsigned &n_unrefined)
void adapt ()
void p_adapt (unsigned &n_refined, unsigned &n_unrefined)
void p_adapt ()
void adapt_based_on_error_estimates (unsigned &n_refined, unsigned &n_unrefined, Vector< Vector< double >> &elemental_error)
void adapt_based_on_error_estimates (Vector< Vector< double >> &elemental_error)
void get_all_error_estimates (Vector< Vector< double >> &elemental_error)
void doc_errors (DocInfo &doc_info)
Get max and min error for all elements in submeshes.
void doc_errors ()
Get max and min error for all elements in submeshes.
void enable_info_in_newton_solve ()
void disable_info_in_newton_solve ()
Disable the output of information when in the newton solver.
Public Member Functions inherited from oomph::ExplicitTimeSteppableObject
ExplicitTimeSteppableObject ()
Empty constructor.
ExplicitTimeSteppableObject (const ExplicitTimeSteppableObject &)=delete
Broken copy constructor.
void operator= (const ExplicitTimeSteppableObject &)=delete
Broken assignment operator.
virtual ~ExplicitTimeSteppableObject ()
Empty destructor.
virtual void actions_before_explicit_stage ()
virtual void actions_after_explicit_stage ()
Private Types
enum { Diagonal_preconditioner =0 , Lower_triangular_preconditioner =1 }
enum {
Lower_wall_boundary_id =0 , Outflow_boundary_id =1 , Upper_wall_boundary_id =2 , Inflow_boundary_id =3 ,
Cylinder_surface_boundary_id =4 , Initial_time_boundary_id =5 , Final_time_boundary_id =6
}
Private Attributes
DocInfo Doc_info
Doc info object.
IterativeLinearSolver * Solver_pt
Oomph-lib iterative linear solver.
Preconditioner * Prec_pt
Preconditioner.
ExtrudedCubeMeshFromQuadMesh< ELEMENT > * Bulk_mesh_pt
Pointer to the space-time mesh.
RefineableQuadMeshWithMovingCylinder< MyRefineableQTaylorHoodElement > * Spatial_mesh_pt
bool Periodicity_has_been_enforced
Additional Inherited Members
Public Types inherited from oomph::Problem
typedef void(* SpatialErrorEstimatorFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error)
Function pointer for spatial error estimator.
typedef void(* SpatialErrorEstimatorWithDocFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error, DocInfo &doc_info)
Function pointer for spatial error estimator with doc.
Public Attributes inherited from oomph::Problem
bool Shut_up_in_newton_solve
Static Public Attributes inherited from oomph::Problem
static bool Suppress_warning_about_actions_before_read_unstructured_meshes
Protected Types inherited from oomph::Problem
enum Assembly_method {
Perform_assembly_using_vectors_of_pairs , Perform_assembly_using_two_vectors , Perform_assembly_using_maps , Perform_assembly_using_lists ,
Perform_assembly_using_two_arrays
}
Enumerated flags to determine which sparse assembly method is used.
Protected Member Functions inherited from oomph::Problem
unsigned setup_element_count_per_dof ()
virtual void sparse_assemble_row_or_column_compressed (Vector< int * > &column_or_row_index, Vector< int * > &row_or_column_start, Vector< double * > &value, Vector< unsigned > &nnz, Vector< double * > &residual, bool compressed_row_flag)
virtual void actions_before_newton_convergence_check ()
virtual void actions_before_newton_step ()
virtual void actions_after_newton_step ()
virtual void actions_before_implicit_timestep ()
virtual void actions_after_implicit_timestep ()
virtual void actions_after_implicit_timestep_and_error_estimation ()
virtual void actions_before_explicit_timestep ()
Actions that should be performed before each explicit time step.
virtual void actions_after_explicit_timestep ()
Actions that should be performed after each explicit time step.
virtual void actions_before_read_unstructured_meshes ()
virtual void actions_after_read_unstructured_meshes ()
virtual void actions_after_change_in_global_parameter (double *const &parameter_pt)
virtual void actions_after_change_in_bifurcation_parameter ()
double & dof_derivative (const unsigned &i)
double & dof_current (const unsigned &i)
virtual void set_initial_condition ()
virtual double global_temporal_error_norm ()
unsigned newton_solve_continuation (double *const &parameter_pt)
unsigned newton_solve_continuation (double *const &parameter_pt, DoubleVector &z)
void calculate_continuation_derivatives (double *const &parameter_pt)
void calculate_continuation_derivatives (const DoubleVector &z)
void calculate_continuation_derivatives_fd (double *const &parameter_pt)
bool does_pointer_correspond_to_problem_data (double *const &parameter_pt)
void set_consistent_pinned_values_for_continuation ()
Protected Attributes inherited from oomph::Problem
Vector< Problem * > Copy_of_problem_pt
std::map< double *, bool > Calculate_dparameter_analytic
bool Calculate_hessian_products_analytic
LinearAlgebraDistribution * Dof_distribution_pt
Vector< double * > Dof_pt
Vector of pointers to dofs.
DoubleVectorWithHaloEntries Element_count_per_dof
double Relaxation_factor
double Newton_solver_tolerance
unsigned Max_newton_iterations
Maximum number of Newton iterations.
unsigned Nnewton_iter_taken
Vector< double > Max_res
Maximum residuals at start and after each newton iteration.
double Max_residuals
bool Time_adaptive_newton_crash_on_solve_fail
bool Jacobian_reuse_is_enabled
Is re-use of Jacobian in Newton iteration enabled? Default: false.
bool Jacobian_has_been_computed
bool Problem_is_nonlinear
bool Pause_at_end_of_sparse_assembly
bool Doc_time_in_distribute
unsigned Sparse_assembly_method
unsigned Sparse_assemble_with_arrays_initial_allocation
unsigned Sparse_assemble_with_arrays_allocation_increment
Vector< Vector< unsigned > > Sparse_assemble_with_arrays_previous_allocation
double Numerical_zero_for_sparse_assembly
double FD_step_used_in_get_hessian_vector_products
bool Mass_matrix_reuse_is_enabled
bool Mass_matrix_has_been_computed
bool Discontinuous_element_formulation
double Minimum_dt
Minimum desired dt: if dt falls below this value, exit.
double Maximum_dt
Maximum desired dt.
double DTSF_max_increase
double DTSF_min_decrease
double Minimum_dt_but_still_proceed
bool Scale_arc_length
Boolean to control whether arc-length should be scaled.
double Desired_proportion_of_arc_length
Proportion of the arc-length to taken by the parameter.
double Theta_squared
int Sign_of_jacobian
Storage for the sign of the global Jacobian.
double Continuation_direction
double Parameter_derivative
Storage for the derivative of the global parameter wrt arc-length.
double Parameter_current
Storage for the present value of the global parameter.
bool Use_continuation_timestepper
Boolean to control original or new storage of dof stuff.
unsigned Dof_derivative_offset
unsigned Dof_current_offset
Vector< double > Dof_derivative
Storage for the derivative of the problem variables wrt arc-length.
Vector< double > Dof_current
Storage for the present values of the variables.
double Ds_current
Storage for the current step value.
unsigned Desired_newton_iterations_ds
double Minimum_ds
Minimum desired value of arc-length.
bool Bifurcation_detection
Boolean to control bifurcation detection via determinant of Jacobian.
bool Bisect_to_find_bifurcation
Boolean to control wheter bisection is used to located bifurcation.
bool First_jacobian_sign_change
Boolean to indicate whether a sign change has occured in the Jacobian.
bool Arc_length_step_taken
Boolean to indicate whether an arc-length step has been taken.
bool Use_finite_differences_for_continuation_derivatives
OomphCommunicator * Communicator_pt
The communicator for this problem.
bool Always_take_one_newton_step
double Timestep_reduction_factor_after_nonconvergence
bool Keep_temporal_error_below_tolerance
Static Protected Attributes inherited from oomph::Problem
static ContinuationStorageScheme Continuation_time_stepper
Storage for the single static continuation timestorage object.
Detailed Description
template<class ELEMENT>
class NavierStokesProblem< ELEMENT >
Entry flow problem in quarter tube domain.
NavierStokes problem.
Member Enumeration Documentation
anonymous enum
template<class ELEMENT > anonymous enum private
Enumerator
Diagonal_preconditioner
Lower_triangular_preconditioner
   {
     Diagonal_preconditioner=0,
     Lower_triangular_preconditioner=1
   };
anonymous enum
template<class ELEMENT > anonymous enum private
Enumerator
Lower_wall_boundary_id
Outflow_boundary_id
Upper_wall_boundary_id
Inflow_boundary_id
Cylinder_surface_boundary_id
Initial_time_boundary_id
Final_time_boundary_id
   {
     Lower_wall_boundary_id=0,
     Outflow_boundary_id=1,
     Upper_wall_boundary_id=2,
     Inflow_boundary_id=3,
     Cylinder_surface_boundary_id=4,
     Initial_time_boundary_id=5,
     Final_time_boundary_id=6
   };
Constructor & Destructor Documentation
NavierStokesProblem() [1/2]
template<class ELEMENT > NavierStokesProblem< ELEMENT >::NavierStokesProblem (DocInfo & doc_info, const string & node_file_name, const string & element_file_name, const string & face_file_name)
Constructor: Pass DocInfo object and file names.
Constructor: Pass DocInfo object mesh files.
  : Doc_info(doc_info)
 {
  //Create mesh
  Problem::mesh_pt() = new TetgenMesh<ELEMENT>(node_file_name,
                                               element_file_name,
                                               face_file_name);
  //Doc the boundaries
  ofstream some_file;
  char filename[100];
  sprintf(filename,"boundaries.dat");
  some_file.open(filename);
  mesh_pt()->output_boundaries(some_file);
  some_file.close();
  // Set the boundary conditions for this problem: All nodal values are
  // free by default -- just pin the ones that have Dirichlet conditions
  // Pin transverse velocities on outer walls -- the outer boundary
  // behaves like a channel (open along the x-axis) with slippery walls
  // on the transverse boundaries
  {
   unsigned ibound=0;
    {
     unsigned num_nod= mesh_pt()->nboundary_node(ibound);
     for (unsigned inod=0;inod<num_nod;inod++)
     {
      mesh_pt()->boundary_node_pt(ibound,inod)->pin(1);
      mesh_pt()->boundary_node_pt(ibound,inod)->pin(2);
     }
    }
  }
  // Pin all velocity components on internal block -- behaves like
  // a rigid body
  {
   unsigned ibound=1;
    {
     unsigned num_nod= mesh_pt()->nboundary_node(ibound);
     for (unsigned inod=0;inod<num_nod;inod++)
     {
      mesh_pt()->boundary_node_pt(ibound,inod)->pin(0);
      mesh_pt()->boundary_node_pt(ibound,inod)->pin(1);
      mesh_pt()->boundary_node_pt(ibound,inod)->pin(2);
     }
    }
  }
  // Loop over the elements to set up element-specific
  // things that cannot be handled by constructor
  unsigned n_element = mesh_pt()->nelement();
  for(unsigned i=0;i<n_element;i++)
   {
    // Upcast from GeneralisedElement to the present element
    ELEMENT* el_pt = dynamic_cast<ELEMENT*>(mesh_pt()->element_pt(i));
    //Set the Reynolds number, etc
    el_pt->re_pt() = &Global_Physical_Variables::Re;
   }
  //Do equation numbering
  cout <<"Number of equations: " << assign_eqn_numbers() << std::endl;
 } // end_of_constructor
References oomph::Problem::assign_eqn_numbers(), MergeRestartFiles::filename, i, NavierStokesProblem< ELEMENT >::mesh_pt(), and Global_Physical_Variables::Re.
~NavierStokesProblem() [1/2]
template<class ELEMENT > NavierStokesProblem< ELEMENT >::~NavierStokesProblem inline
Destructor (empty)
Destructor for NavierStokes problem in cubic domain.
 {}
NavierStokesProblem() [2/2]
template<class ELEMENT > NavierStokesProblem< ELEMENT >::NavierStokesProblem
Constructor.
Constructor for NavierStokes problem in cubic domain.
                                                   :
   Solver_pt(0),
   Prec_pt(0),
   Bulk_mesh_pt(0),
   Spatial_mesh_pt(0),
   Periodicity_has_been_enforced(false)
 {
   // Update the mesh-related parameters
   GlobalParameters::update_mesh_parameters();
   // Update the physical parameters
   GlobalParameters::update_physical_parameters();
   // Generate the space-time mesh (stored as Bulk_mesh_pt)
   create_spacetime_mesh();
   // Assign the appropriate boundary conditions
   apply_boundary_conditions();
   // Assign the time-slice ID to each element
   // NOTE: This must be done after the boundary conditions have been assigned
   // otherwise it won't know about the periodicity.)
   assign_time_slice_id();
   // Complete the problem setup to make the elements fully functional
   complete_problem_setup();
   // Make it pseudo-traction-free
   SpaceTimeNavierStokesMixedOrderEquations<2>::Gamma[0]=0.0;
   SpaceTimeNavierStokesMixedOrderEquations<2>::Gamma[1]=0.0;
   // Use the block lower triangular preconditioner
   GlobalParameters::Preconditioner=Lower_triangular_preconditioner;
   // Call the auxiliary solver setup function
   set_up_spacetime_solver();
   // Assign equation numbers
   oomph_info << "\nNumber of equations: " << assign_eqn_numbers() << std::endl;
 } // End of NavierStokesProblem
References NavierStokesProblem< ELEMENT >::apply_boundary_conditions(), oomph::Problem::assign_eqn_numbers(), NavierStokesProblem< ELEMENT >::assign_time_slice_id(), NavierStokesProblem< ELEMENT >::complete_problem_setup(), NavierStokesProblem< ELEMENT >::create_spacetime_mesh(), NavierStokesProblem< ELEMENT >::Lower_triangular_preconditioner, oomph::oomph_info, GlobalParameters::Preconditioner, NavierStokesProblem< ELEMENT >::set_up_spacetime_solver(), GlobalParameters::update_mesh_parameters(), and GlobalParameters::update_physical_parameters().
~NavierStokesProblem() [2/2]
template<class ELEMENT > NavierStokesProblem< ELEMENT >::~NavierStokesProblem ()
Destructor.
Member Function Documentation
actions_after_newton_solve() [1/2]
template<class ELEMENT > void NavierStokesProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Doc the solution after solve.
Reimplemented from oomph::Problem.
   {
    // Doc solution after solving
    doc_solution();
    // Increment label for output files
    Doc_info.number()++;
   }
References GlobalParameters::Doc_info, and oomph::DocInfo::number().
actions_after_newton_solve() [2/2]
template<class ELEMENT > void NavierStokesProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_parameter_increase()
template<class ELEMENT > void NavierStokesProblem< ELEMENT >::actions_after_parameter_increase (double *const & parameter_pt) virtual
Update the problem specs after an increase in a parameter.
Reimplemented from oomph::Problem.
 {
   // If we have been passed a pointer to the Reynolds number or period ratio
   if ((parameter_pt==&GlobalParameters::Re)||
       (parameter_pt==&GlobalParameters::Period_ratio))
   {
     // Call the physical parameters update function
     GlobalParameters::update_physical_parameters();
     // Update the boundary conditions (for the update of the velocities on
     // the cylinder boundary)
     apply_boundary_conditions();
   }
   else if (parameter_pt==&GlobalParameters::Amplitude)
   {
     // Update the nodal positions
     Bulk_mesh_pt->node_update();
     // Update the boundary conditions (for the update of the velocities on
     // the cylinder boundary)
     apply_boundary_conditions();
   }
   else
   {
     // Tell the user
     oomph_info << "\nCalled actions_after_parameter_increase(...) but I"
                << "\ndon't know what to do for this parameter. I'm going to "
                << "\nassume I'm not meant to do anything here. I hope you know"
                << "\nwhat you're doing...\n" << std::endl;
   }
 } // End of actions_after_parameter_increase
References GlobalParameters::Amplitude, oomph::oomph_info, GlobalParameters::Period_ratio, GlobalParameters::Re, and GlobalParameters::update_physical_parameters().
actions_before_newton_solve() [1/2]
template<class ELEMENT > void NavierStokesProblem< ELEMENT >::actions_before_newton_solve virtual
Update the problem specs before solve.
Set the inflow boundary conditions.
Reimplemented from oomph::Problem.
 {
  // Apply conditions on obstacle
  unsigned ibound=1;
  unsigned num_nod= mesh_pt()->nboundary_node(ibound);
  for (unsigned inod=0;inod<num_nod;inod++)
   {
    // Block moves in z-direction
    mesh_pt()->boundary_node_pt(ibound,inod)->set_value(2,1.0);
   }
 } // end_of_actions_before_newton_solve
actions_before_newton_solve() [2/2]
template<class ELEMENT > void NavierStokesProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
 {}
apply_boundary_conditions()
template<class ELEMENT > void NavierStokesProblem< ELEMENT >::apply_boundary_conditions
Assign the appropriate boundary conditions and enforce periodicity in the time direction
Assign the appropriate boundary conditions, i.e. periodicity in the t-direction. In the x and y-direction apply Dirichlet boundary conditions. In summary: Boundary 0 (t=0) – Periodic in time (with boundary 5) Boundary 1 (y=0) – Dirichlet Boundary 2 (x=1) – Dirichlet Boundary 3 (y=1) – Dirichlet Boundary 4 (x=0) – Dirichlet Boundary 5 (t=1) – Periodic in time (with boundary 0)
 {
   // Get the start time
   double start_t=TimingHelpers::timer();
   // Number of SPATIAL dimensions
   unsigned n_dim=3;
   // Storage for the spatial coordinates
   Vector<double> spatial_coordinates(n_dim-1,0.0);
   // Storage for the solution (also passes the pressure field)
   Vector<double> u_exact(n_dim,0.0);
   // Number of nodes on t=0 boundary
   unsigned n_boundary0_node=Bulk_mesh_pt->
                             nboundary_node(Initial_time_boundary_id);
   // Number of nodes on t=1 boundary
   unsigned n_boundary1_node=Bulk_mesh_pt->
                             nboundary_node(Final_time_boundary_id);
   // Get the number of boundaries in the mesh
   unsigned n_boundary=Bulk_mesh_pt->nboundary();
   // Loop over the boundaries
   for (unsigned b=0; b<n_boundary; b++)
   {
     // Get the number of nodes on the b-th boundary
     unsigned n_node=Bulk_mesh_pt->nboundary_node(b);
     // If we're on either of the time boundaries
     if ((b==Initial_time_boundary_id)||(b==Final_time_boundary_id))
     {
       // If we need to set up periodicity
       if (!Periodicity_has_been_enforced)
       {
         //----------------------------
         // Establish nodal periodicity
         //----------------------------
         // Make sure there are as many nodes on boundary 0 as there are on
         // boundary (n_boundary-1)
         if (n_boundary0_node!=n_boundary1_node)
         {
           // Create an output stream
           std::ofstream output_file;
           // Open a file
           output_file.open("RESLT/nodes_b0.csv");
           // Loop over the nodes on the t=0 boundary
           for (unsigned i=0; i<n_boundary0_node; i++)
           {
             // Output the coordinates of the i-th node on the t=0 boundary
             Bulk_mesh_pt->boundary_node_pt(Initial_time_boundary_id,i)->
             output(output_file);
           }
           // Close the file
           output_file.close();
           // Open a file
           output_file.open("RESLT/nodes_b1.csv");
           // Loop over the nodes on the t=0 boundary
           for (unsigned i=0; i<n_boundary1_node; i++)
           {
             // Output the coordinates of the i-th node on the t=1 boundary
             Bulk_mesh_pt->boundary_node_pt(Final_time_boundary_id,i)->
             output(output_file);
           }
           // Close the file
           output_file.close();
           // Create an output stream
           std::ostringstream error_message_stream;
           // Create an error message
           error_message_stream << "Different number of nodes on t=0 and t=1 "
                                << "boundary!\nThere are " << n_boundary0_node
                                << " nodes on boundary " << Initial_time_boundary_id
                                << " and " << n_boundary1_node
                                << " nodes on boundary " << Final_time_boundary_id
                                << "!" << std::endl;
           // Throw an error
           throw OomphLibError(error_message_stream.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
         // Loop over the nodes on the t=0 boundary
         for (unsigned i=0; i<n_boundary0_node; i++)
         {
           // Get the pointer to the associated node
           Node* node0_pt=Bulk_mesh_pt->boundary_node_pt(Initial_time_boundary_id,i);
           // Boolean to indicate whether or not the neighbour has been found
           bool has_neighbour_node_been_found=false;
           // Loop over the nodes on the t=1 boundary
           for (unsigned j=0; i<n_boundary1_node; j++)
           {
             // Get the pointer to the associated node
             Node* node1_pt=Bulk_mesh_pt->boundary_node_pt(Final_time_boundary_id,j);
             // Distance value
             double distance=0.0;
             // Loop over the entries of x
             for (unsigned k=0; k<n_dim-1; k++)
             {
               // Update the distance (2 norm)
               distance+=pow(((node0_pt->x(k))-(node1_pt->x(k))),2.0);
             }
             // Square root it
             distance=std::sqrt(distance);
             // Check if it matches to within a reasonable tolerance
             if (std::fabs(distance)<Tree::max_neighbour_finding_tolerance())
             {
               // Make the nodes periodic; the node on the t=1 boundary now points
               // to the node on the t=0 boundary.
               node1_pt->make_periodic(node0_pt);
               // We've found the neighbouring node
               has_neighbour_node_been_found=true;
               // We're done; break out!
               break;
             }
           } // for (unsigned i=0;i<n_boundary0_node;i++)
           // If we get here and we haven't found the neighbouring node, something's
           // wrong so throw an error
           if (!has_neighbour_node_been_found)
           {
             // Throw an error
             throw OomphLibError("Couldn't find neighbouring node!",
                                 OOMPH_CURRENT_FUNCTION,
                                 OOMPH_EXCEPTION_LOCATION);
           }
         } // for (unsigned i=0;i<n_boundary0_node;i++)
         // If we've got here then the periodicity has been set up
         Periodicity_has_been_enforced=true;
       } // if (!Periodicity_has_been_enforced)
     }
     // If we're not on the time boundaries
     else
     {
       // If we're on the lower/upper wall
       if ((b==Lower_wall_boundary_id)||(b==Upper_wall_boundary_id))
       {
         // Loop over the nodes on the b-th boundary
         for (unsigned n=0; n<n_node; n++)
         {
           // Get a pointer to the n-th node on the b-th boundary
           Node* node_pt=Bulk_mesh_pt->boundary_node_pt(b,n);
           // Loop over the velocity components
           for (unsigned i=0; i<n_dim-1; i++)
           {
             // Pin the i-th velocity component
             node_pt->pin(i);
           }
           // Apply tow-tank boundary conditions (nonzero horizontal velocity)
           node_pt->set_value(0,1.0);
           // Apply tow-tank boundary conditions (no vertical velocity)
           node_pt->set_value(1,0.0);
         } // for (unsigned n=0;n<n_node;n++)
       }
       // If we're at the outflow boundary
       else if (b==Outflow_boundary_id)
       {
         // Don't actually do anything; it's better than forcing parallel flow
         // at the outlet (no numerical oscillations/boundary layer near exit)
       }
       // If we're at the inflow boundary
       else if (b==Inflow_boundary_id)
       {
         // Loop over the nodes
         for (unsigned n=0; n<n_node; n++)
         {
           // Pointer to the boundary node
           Node* boundary_node_pt=Bulk_mesh_pt->boundary_node_pt(b,n);
           // Pin the horizontal velocity
           boundary_node_pt->pin(0);
           // Pin the vertical velocity
           boundary_node_pt->pin(1);
           // Uniform flow
           boundary_node_pt->set_value(0,1.0);
           // Parallel flow means no vertical velocity component
           boundary_node_pt->set_value(1,0.0);
         }
       }
       // If we're dealing with the cylinder surface (apply no-slip conditions)
       else if (b==Cylinder_surface_boundary_id)
       {
         // Loop over the nodes
         for (unsigned i_nod=0; i_nod<n_node; i_nod++)
         {
           // Pointer to the boundary node
           Node* boundary_node_pt=Bulk_mesh_pt->boundary_node_pt(b,i_nod);
           // Pin the horizontal velocity at every node
           boundary_node_pt->pin(0);
           // Pin the vertical velocity at every node
           boundary_node_pt->pin(1);
           // Get the time value associated with this node
           double time=boundary_node_pt->x(n_dim-1);
           // Storage for the cylinder velocity
           Vector<double> u(2,0.0);
           // Get the velocity of the cylinder at this point in time
           GlobalParameters::Cylinder_pt->velocity(time,u);
           //--------------------------------------------------------------------
           // Apply no-slip condition for NS on a moving wall node noting:
           //        Uu = (D/T_e) dR/dt => u = St dR/dt = St dR_cyl/dt,
           // where the Strouhal number is defined as St = D/(UT_e).
           //--------------------------------------------------------------------
           // Set the horizontal velocity value
           boundary_node_pt->set_value(0,GlobalParameters::St*u[0]);
           // Set the vertical velocity value
           boundary_node_pt->set_value(1,GlobalParameters::St*u[1]);
         }
       } // if ((b==Lower_wall_boundary_id)||(b==Upper_wall_boundary_id))
     } // if ((b==Initial_time_boundary_id)||(b==Final_time_boundary_id))
   } // for (unsigned b=0;b<n_bound;b++)
   // Record the end time
   double end_t=TimingHelpers::timer();
   // Compute the time taken
   double boundary_condition_application_time=end_t-start_t;
   // Output the setup time to the screen
   oomph_info << "Time taken for application of boundary conditions [sec]: "
              << boundary_condition_application_time << std::endl;
 } // End of apply_boundary_conditions
References b, GlobalParameters::Cylinder_pt, boost::multiprecision::fabs(), i, j, k, oomph::Node::make_periodic(), n, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::oomph_info, output(), oomph::Data::pin(), Eigen::ArrayBase< Derived >::pow(), oomph::Data::set_value(), sqrt(), GlobalParameters::St, OscillatingCylinder::velocity(), and oomph::Node::x().
Referenced by NavierStokesProblem< ELEMENT >::NavierStokesProblem().
assign_time_slice_id()
template<class ELEMENT > void NavierStokesProblem< ELEMENT >::assign_time_slice_id
Assign the time slice number to each element.
Set up the map which maps a given element e to it's (i,j,k) coordinates in the mesh where i,j and k are integers (such that 0<=i<N_x, 0<=j<N_y, 0<=k<N_t).
 {
   // Number of dimensions
   unsigned n_dim=3;
   // Space for the local coordinates (at the center of the element)
   Vector<double> s(n_dim,0.0);
   // The ID of the coordinate we want, i.e. the ID of the time-direction
   unsigned time_index=n_dim-1;
   // Storage for the time coordinate
   double t=0.0;
   // Get the number of elements in the mesh
   unsigned n_element=Bulk_mesh_pt->nelement();
   // Loop over the elements
   for (unsigned i=0; i<n_element; i++)
   {
     // Get the Eulerian coordinates at the center of the element
     t=Bulk_mesh_pt->finite_element_pt(i)->interpolated_x(s,time_index);
     // The length of an element in the time direction
     double el_length=GlobalParameters::L_t/double(GlobalParameters::N_t);
     // Subtract the length of half an element off (since we're at the centre
     // of the element using s=(0,0,0))
     t-=el_length/2.0;
     // Divide by the length of an element
     t/=el_length;
     // Store it (have to round first otherwise 0.999 would become 0)
     unsigned id=unsigned(GlobalParameters::round(t));
     // Upcast the element
     ELEMENT* el_pt=dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(i));
     // Assign the time slice ID
     el_pt->set_time_slab_id(id);
     // There are 5 unique dofs per element 3 in common with neighbouring
     // time slices (i.e. u, v and p) so 3 unique ones per element. We can
     // either use an impulsive start (i.e. pin dofs in the first time slice)
     // or periodic boundary conditions (the dofs in the final time slice
     // are the dofs in the first time slice) so the actual number of dof
     // types is always the same
     GlobalParameters::N_dof_type=3*GlobalParameters::N_t;
     // Finally, tell it how many dof types there are in the mesh
     el_pt->set_ndof_types(GlobalParameters::N_dof_type);
   } // for (unsigned i=0;i<n_element;i++)
 } // End of assign_time_slice_id
References i, GlobalParameters::L_t, GlobalParameters::N_dof_type, GlobalParameters::N_t, GlobalParameters::round(), s, and plotPSD::t.
Referenced by NavierStokesProblem< ELEMENT >::NavierStokesProblem().
complete_problem_setup()
template<class ELEMENT > void NavierStokesProblem< ELEMENT >::complete_problem_setup
Complete problem setup: pass pointers to physical variables.
Complete problem setup: do anything else that's needed to make the elements fully functional (e.g. pass pointers to problem parameters)
 {
   // Get the number of elements in the bulk mesh
   unsigned n_bulk_element=Bulk_mesh_pt->nelement();
   // Loop over the bulk elements
   for (unsigned e=0; e<n_bulk_element; e++)
   {
     // Upcast to a fluid element
     ELEMENT* el_pt=dynamic_cast<ELEMENT*>(mesh_pt()->element_pt(e));
     // Set the Reynolds number (set equal to the Womersley number)
     el_pt->re_pt()=&GlobalParameters::Re;
     // Set the Strouhal number
     el_pt->re_st_pt()=&GlobalParameters::ReSt;
   }
 } // End of complete_problem_setup
References e(), GlobalParameters::Re, and GlobalParameters::ReSt.
Referenced by NavierStokesProblem< ELEMENT >::NavierStokesProblem().
create_spacetime_mesh()
template<class ELEMENT > void NavierStokesProblem< ELEMENT >::create_spacetime_mesh
Create the space-time mesh with the chosen number of elements in the time direction and the chosen spatial resolution
Helper function to create the space-time mesh (to be assigned to Bulk_mesh_pt) with the chosen number of elements in the time direction and an appropriate spatial resolution (to capture the time-periodic solution properly).
 {
   // Storage for the start time
   double start_t=0.0;
   //--------------------------
   // Generate 2D spatial mesh:
   //--------------------------
   // Record the start time
   start_t=TimingHelpers::timer();
   // Use BDF2
   add_time_stepper_pt(new Steady<0>);
   // Make a new cylinder
   GlobalParameters::Cylinder_pt=
     new OscillatingCylinder(&GlobalParameters::Radius,
                             &GlobalParameters::Amplitude,
                             time_pt());
   // Make a new mesh and assign its pointer
   Spatial_mesh_pt=
     new RefineableQuadMeshWithMovingCylinder<MyRefineableQTaylorHoodElement>(
     GlobalParameters::Cylinder_pt,
     GlobalParameters::Annular_region_radius,
     GlobalParameters::Length_of_central_box,
     GlobalParameters::X_left,
     GlobalParameters::X_right,
     GlobalParameters::Height);
   // Loop over the refinements
   for (unsigned i=0; i<GlobalParameters::N_uniform_refinement_before_solve; i++)
   {
     // Refine the mesh
     Spatial_mesh_pt->refine_uniformly();
   }
   // Quick statistics about the mesh and it's setup
   oomph_info << "\nNumber of nodes in spatial mesh: "
              << Spatial_mesh_pt->nnode()
              << "\nNumber of elements in spatial mesh: "
              << Spatial_mesh_pt->nelement()
              << "\nTime taken to generate refined spatial mesh [sec]: "
              << TimingHelpers::timer()-start_t << std::endl;
   //---------------------------------
   // Generate the 3D space-time mesh:
   //---------------------------------
   // Indicate that we want the mesh extrusion time to be doc-ed
   MeshExtrusionHelpers::Mesh_extrusion_helper.enable_doc_mesh_setup_time();
   // Create the extruded mesh
   Bulk_mesh_pt=new ExtrudedCubeMeshFromQuadMesh<ELEMENT>
   (Spatial_mesh_pt,GlobalParameters::N_t,GlobalParameters::L_t);
   // The created space-time mesh is the only mesh so assign it
   Problem::mesh_pt()=Bulk_mesh_pt;
   // Record the start time
   start_t=TimingHelpers::timer();
   // Pin the redundant temporal nodes
   pin_redundant_temporal_nodes();
   // Reorder the nodes (don't use the regular setup ordering)
   NodeReordering::reorder_nodes(Bulk_mesh_pt,false);
   // Document the setup time
   oomph_info << "\nTime taken for redundant node pinning/node reordering [sec]: "
              << TimingHelpers::timer()-start_t << std::endl;
   // Check the maximum deformation of the mesh due to the cylinder motion
   GlobalParameters::doc_maximum_central_box_deformation();
   // Tell the user we've finished
   oomph_info << "\nCompleted mesh generation and documentation!" << std::endl;
 } // End of create_spacetime_mesh
References GlobalParameters::Amplitude, GlobalParameters::Annular_region_radius, GlobalParameters::Cylinder_pt, GlobalParameters::doc_maximum_central_box_deformation(), oomph::MeshExtrusionHelpers::ExtrusionHelper::enable_doc_mesh_setup_time(), GlobalParameters::Height, i, GlobalParameters::L_t, GlobalParameters::Length_of_central_box, oomph::MeshExtrusionHelpers::Mesh_extrusion_helper, GlobalParameters::N_t, GlobalParameters::N_uniform_refinement_before_solve, oomph::oomph_info, GlobalParameters::Radius, NodeReordering::reorder_nodes(), GlobalParameters::X_left, and GlobalParameters::X_right.
Referenced by NavierStokesProblem< ELEMENT >::NavierStokesProblem().
doc_solution() [1/2]
template<class ELEMENT > void NavierStokesProblem< ELEMENT >::doc_solution
Doc the solution.
 {
  ofstream some_file;
  char filename[100];
  // Number of plot points
  unsigned npts;
  npts=5;
  // Output solution
  sprintf(filename,"%s/soln%i.dat",Doc_info.directory().c_str(),
          Doc_info.number());
  some_file.open(filename);
  mesh_pt()->output(some_file,npts);
  some_file.close();
 } // end_of_doc_solution
References oomph::DocInfo::directory(), GlobalParameters::Doc_info, MergeRestartFiles::filename, and oomph::DocInfo::number().
doc_solution() [2/2]
template<class ELEMENT > void NavierStokesProblem< ELEMENT >::doc_solution (const bool & doc_spacetime_soln = false)
Doc the solution.
Document the solution.
 {
   // Start the clock
   double timer_s=TimingHelpers::timer();
   // Make an ofstream object to output the solution
   std::ofstream some_file;
   // Storage for the filename
   char filename[100];
   // Number of plot points to use for the big space-time solution
   unsigned n_plot_point=3;
   //-----------------
   // Output solution:
   //-----------------
   // Create the filename suffix
   sprintf(filename,"%s/soln%i",
           GlobalParameters::Doc_info.directory().c_str(),
           GlobalParameters::Doc_info.number());
   // Convert it to a string to allow ease of replacing dots
   std::string filename_as_string(filename);
   // Replace all dots with the string "pt"
   std::replace(filename_as_string.begin(),filename_as_string.end(),'.','p');
   // Now append the filename extension
   filename_as_string+=".dat";
   // Open a file with the constructed filename
   some_file.open(filename_as_string.c_str());
   // Set the precision of the outputted data
   some_file.precision(20);
   // Output the (numerically) approximated solution
   Bulk_mesh_pt->output(some_file,n_plot_point);
   // We're done; close the file
   some_file.close();
   // Finally, output the time taken
   oomph_info << "Total time for documentation [sec]: "
              << TimingHelpers::timer()-timer_s << std::endl;
   // Increment counter for solutions
   GlobalParameters::Doc_info.number()++;
 } // End of doc_solution
References GlobalParameters::Doc_info, MergeRestartFiles::filename, oomph::DocInfo::number(), oomph::oomph_info, and oomph::Global_string_for_annotation::string().
mesh_pt()
template<class ELEMENT > TetgenMesh<ELEMENT>* NavierStokesProblem< ELEMENT >::mesh_pt () inline
   {
    return dynamic_cast<TetgenMesh<ELEMENT>*>(Problem::mesh_pt());
   }
Referenced by NavierStokesProblem< ELEMENT >::NavierStokesProblem().
pin_redundant_temporal_nodes()
template<class ELEMENT > void NavierStokesProblem< ELEMENT >::pin_redundant_temporal_nodes
The mixed order elements use linear interpolation in time so the only nodes which contribute to the unknowns in the system are those that lie on the temporal boundaries of the elements. Thus, all nodes that do not lie on these boundaries need to be pinned (otherwise we'd get zero rows in the system matrix making it singular...).
 {
   // Number of nodes in each direction
   unsigned n_node_1d=Bulk_mesh_pt->finite_element_pt(0)->nnode_1d();
   // Number of nodes in a space-time element
   unsigned n_el_node=Bulk_mesh_pt->finite_element_pt(0)->nnode();
   // Sanity check: only works for 3D space-time elements (2D space + 1D time)
   if (n_el_node!=std::pow(n_node_1d,3))
   {
     // Throw an error
     throw OomphLibError("Can currently only deal with 3D space-time elements!",
                         OOMPH_CURRENT_FUNCTION,
                         OOMPH_EXCEPTION_LOCATION);
   }
   // Get the number of elements in the mesh
   unsigned n_element=Bulk_mesh_pt->nelement();
   // Loop over the elements
   for (unsigned i=0; i<n_element; i++)
   {
     // Loop over the nodes
     for (unsigned j=0; j<n_el_node; j++)
     {
       // Storage for the local time slice ID (0<=i_temporal<=NNODE_1D-1)
       unsigned j_temporal=0;
       // The spatial node number
       unsigned j_spatial=j%(n_node_1d*n_node_1d);
       // Which local time slice are we in?
       j_temporal=(j-j_spatial)/(n_node_1d*n_node_1d);
       // If we're not on first/final elemental time slice
       if ((j_temporal!=0)&&(j_temporal!=n_node_1d-1))
       {
         // Get a pointer to the j-th node in the i-th element
         Node* node_pt=Bulk_mesh_pt->finite_element_pt(i)->node_pt(j);
         // Get the number of unknowns at this node
         unsigned n_value=node_pt->nvalue();
         // Loop over the unknowns
         for (unsigned k=0; k<n_value; k++)
         {
           // Pin the k-th unknown at this node
           node_pt->pin(k);
         }
       } // if ((j_temporal!=0)&&(j_temporal!=n_node_1d-1))
     } // for (unsigned j=0;j<n_el_node;j++)
   } // for (unsigned i=0;i<n_element;i++)
 } // End of pin_redundant_temporal_nodes
References i, j, k, oomph::Data::nvalue(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::Data::pin(), and Eigen::bfloat16_impl::pow().
run_natural_continuation()
template<class ELEMENT > void NavierStokesProblem< ELEMENT >::run_natural_continuation (double & parameter, const double & parameter_target, const unsigned & max_n_parameter_step)
Use continuation in a particular parameter. This should make things sufficiently generic so natural continuation can be used interchangeably with ease for any given input parameter. NOTE: It's important that the function:
       actions_after_parameter_increase(...)
be overloaded so that anything that needs to be updated after a change in the input parameter is indeed updated.
Use continuation in a particular parameter. This should make things sufficiently generic so natural/arc-length continuation can be used interchangeably with ease for any given input parameter. NOTE: It's important that the function:
       actions_after_parameter_increase(...)
be overloaded so that anything that needs to be updated after a change in the input parameter is indeed updated.
Inputs:
(1) The parameter that we're running continuation in; (2) The target parameter value; (4) The max. number of steps used to reach parameter_target; (5) (Optional) Whether or not to document the solution at each step.
 {
   // If we can actually do anything
   if ((std::fabs(parameter_target-parameter)>=1.0e-14)&&
       (max_n_parameter_step!=0))
   {
     // Store the string used to denote the input parameter
     std::string parameter_string=
       GlobalParameters::parameter_to_string(&parameter);
     // Copy the initial parameter value
     double initial_parameter=parameter;
     // The size of the amplitude value increment
     double parameter_increment=((parameter_target-parameter)/
                                 double(max_n_parameter_step));
     // Tell the user what we're doing
     oomph_info << ANSIEscapeCode::Red
                << "\nStarting natural continuation process for "
                << parameter_string << "!" << ANSIEscapeCode::Reset
                << "\n\nInitial " << parameter_string << " value: " << parameter
                << "\nTarget " << parameter_string << " value: "
                << parameter_target << "\nMax. number of parameter steps: "
                << max_n_parameter_step << "\n\n"
                << ANSIEscapeCode::Red
                << "Parameter value cases (" << parameter_string << "): "
                << ANSIEscapeCode::Reset << std::endl;
     // Loop over the increments
     for (unsigned i=0; i<max_n_parameter_step+1; i++)
     {
       // Tell the user
       oomph_info << " (" << i << ") "
                  << initial_parameter+i*parameter_increment
                  << std::endl;
     } // for (unsigned i=0;i<max_n_parameter_step+1;i++)
     // Vector to contain the Problem dofs
     DoubleVector dofs_backup;
     // The maximum number of times tono halve the parameter increment
     unsigned max_n_reattempt=30;
     // The number of times we've halved the parameter increment
     unsigned n_reattempt=0;
     // Loop over the increments
     while (std::fabs(parameter_target-parameter)>1.0e-14)
     {
       // Get the dofs
       get_dofs(dofs_backup);
       // Increment the parameter value
       parameter+=parameter_increment;
       // Tell the user
       oomph_info << "\n" << ANSIEscapeCode::Red
                  << "Solving for " << parameter_string << " value: "
                  << ANSIEscapeCode::Reset << parameter << std::endl;
       // Update anything that needs to be changed after a change in this parameter
       actions_after_parameter_increase(&parameter);
       // Try doing a solve
       try
       {
         // Solve for this parameter value
         newton_solve();
       }
       // If the simulation threw up an error
       catch (NewtonSolverError& error)
       {
         // Make sure we haven't had to try too many times
         if (n_reattempt<max_n_reattempt)
         {
           // Decrement the parameter value
           parameter-=parameter_increment;
           // Make all the necessary updates after a change in this parameter
           actions_after_parameter_increase(&parameter);
           // Reset the dofs
           set_dofs(dofs_backup);
           // Half the parameter increment
           parameter_increment*=0.5;
           // Tell the user
           oomph_info << "\n" << ANSIEscapeCode::Red
                      << "Solve failed! Re-attempt " << n_reattempt+1
                      << " -- halving parameter increment (for "
                      << parameter_string << ") to: "
                      << ANSIEscapeCode::Reset;
           // The parameter increment is actually just this increment
           oomph_info << parameter_increment << std::endl;
           // Indicate that we're trying again
           n_reattempt++;
           // Try again...
           continue;
         }
         // If we've had to try too many times
         else
         {
           // Create an output stream
           std::ostringstream error_message_stream;
           // Create the error message
           error_message_stream << "Re-attempted a solve too many times. "
                                << "Exiting here!" << std::endl;
           // Throw an error
           throw OomphLibError(error_message_stream.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         } // if (n_reattempt<max_n_reattempt)
       } // try
     } // while (std::fabs(parameter_target-parameter)<1.0e-08)
   } // if ((std::fabs(parameter_target-parameter)>1.0e-10)&&(max...
 } // End of run_natural_continuation
References calibrate::error, boost::multiprecision::fabs(), i, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::oomph_info, GlobalParameters::parameter_to_string(), oomph::ANSIEscapeCode::Red, oomph::ANSIEscapeCode::Reset, and oomph::Global_string_for_annotation::string().
set_up_spacetime_solver()
template<class ELEMENT > void NavierStokesProblem< ELEMENT >::set_up_spacetime_solver
Set up the solver for this Problem.
Assign the chosen solver to this Problem (and preconditioner if so desired)
 {
   // Create oomph-lib iterative linear solver
   Solver_pt=new GMRES<CRDoubleMatrix>;
   // Use RHS preconditioning
   //dynamic_cast<GMRES<CRDoubleMatrix>*>(Solver_pt)->set_preconditioner_RHS();
   dynamic_cast<GMRES<CRDoubleMatrix>*>(Solver_pt)->set_preconditioner_LHS();
   // Set the tolerance
   Solver_pt->tolerance()=1.0e-10;
   // Maximum number of iterations
   Solver_pt->max_iter()=200;
   // Set linear solver
   linear_solver_pt()=Solver_pt;
   //-----------------------------------------
   // Create the master-level preconditioners:
   //-----------------------------------------
   // Do we want to document the memory usage?
   bool document_memory_usage=true;
   // Solve the diagonal blocks associated with each time-slice separately
   if (GlobalParameters::Preconditioner==Diagonal_preconditioner)
   {
     // Create a new instance of the space-time preconditioner
     Prec_pt=new BlockDiagonalPreconditioner<CRDoubleMatrix>;
   }
   // Solve the block lower-triangular part of the system matrix
   else if (GlobalParameters::Preconditioner==Lower_triangular_preconditioner)
   {
     // Create a new instance of the space-time preconditioner
     Prec_pt=new BandedBlockTriangularPreconditioner<CRDoubleMatrix>;
     // Indicate that we're using a block lower triangular solve
     dynamic_cast<BandedBlockTriangularPreconditioner<CRDoubleMatrix>*>
     (Prec_pt)->lower_triangular();
     // The order of the interpolation in the time direction (linear)
     unsigned temporal_order=1;
     // Provide the bandwidth; only subdiagonal block entries
     dynamic_cast<BandedBlockTriangularPreconditioner<CRDoubleMatrix>*>
     (Prec_pt)->set_block_bandwidth(temporal_order);
     // If we want to document the memory usage
     if (document_memory_usage)
     {
       dynamic_cast<BandedBlockTriangularPreconditioner<CRDoubleMatrix>*>
       (Prec_pt)->enable_doc_memory_usage();
     }
   }
   // If the user provided an invalid input
   else
   {
     // Throw an error
     throw OomphLibError("Invalid choice of preconditioner.",
                         OOMPH_CURRENT_FUNCTION,
                         OOMPH_EXCEPTION_LOCATION);
   }
   // Allocate space for the DOF to block map; this tells the master block
   // preconditioner which DOF types to aggregate
   Vector<unsigned> dof_to_block_map;
   // Call the auxiliary function which sets up the mapping
   GlobalParameters::set_up_dof_to_block_mapping(dof_to_block_map);
   // Create an upcasted pointer to the master preconditioner
   GeneralPurposeBlockPreconditioner<CRDoubleMatrix>* upcasted_master_prec_pt=
     dynamic_cast<GeneralPurposeBlockPreconditioner<CRDoubleMatrix>*>(Prec_pt);
   // Build silently!
   upcasted_master_prec_pt->enable_silent_preconditioner_setup();
   // Pass the DOF-to-block map to the preconditioner
   upcasted_master_prec_pt->set_dof_to_block_map(dof_to_block_map);
   // Specify the subsidiary block preconditioner
   upcasted_master_prec_pt->set_subsidiary_preconditioner_function(
     SubsidiaryPreconditionerHelper::get_new_preconditioner);
   // Pass a pointer to the (space-time) mesh
   upcasted_master_prec_pt->add_mesh(Bulk_mesh_pt);
   // Now assign the preconditioner to the linear solver
   Solver_pt->preconditioner_pt()=Prec_pt;
 } // End of set_up_spacetime_solver
References oomph::GeneralPurposeBlockPreconditioner< MATRIX >::add_mesh(), oomph::Preconditioner::enable_silent_preconditioner_setup(), SubsidiaryPreconditionerHelper::get_new_preconditioner(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, GlobalParameters::Preconditioner, oomph::GeneralPurposeBlockPreconditioner< MATRIX >::set_dof_to_block_map(), oomph::GeneralPurposeBlockPreconditioner< MATRIX >::set_subsidiary_preconditioner_function(), and GlobalParameters::set_up_dof_to_block_mapping().
Referenced by NavierStokesProblem< ELEMENT >::NavierStokesProblem().
Member Data Documentation
Bulk_mesh_pt
template<class ELEMENT > ExtrudedCubeMeshFromQuadMesh<ELEMENT>* NavierStokesProblem< ELEMENT >::Bulk_mesh_pt private
Pointer to the space-time mesh.
Doc_info
template<class ELEMENT > DocInfo NavierStokesProblem< ELEMENT >::Doc_info private
Doc info object.
Periodicity_has_been_enforced
template<class ELEMENT > bool NavierStokesProblem< ELEMENT >::Periodicity_has_been_enforced private
Prec_pt
template<class ELEMENT > Preconditioner* NavierStokesProblem< ELEMENT >::Prec_pt private
Preconditioner.
Solver_pt
template<class ELEMENT > IterativeLinearSolver* NavierStokesProblem< ELEMENT >::Solver_pt private
Oomph-lib iterative linear solver.
Spatial_mesh_pt
template<class ELEMENT > RefineableQuadMeshWithMovingCylinder< MyRefineableQTaylorHoodElement>* NavierStokesProblem< ELEMENT >::Spatial_mesh_pt private
Pointer to the spatial mesh. NOTE: We keep this so that we retain a pointer to the Domain which will tell the ExtrudedDomain how to move the nodes when we want to do a parameter sweep in the cylinder oscillation amplitude...
The documentation for this class was generated from the following files:
mesh_from_tetgen_navier_stokes.cc
space_time_oscillating_cylinder.cc