MercuryDPM: Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, InnerProduct > Struct Template Reference
Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, InnerProduct > Struct Template Reference
#include <ProductEvaluators.h>
Public Types
using impl = default_inner_product_impl< Lhs, Rhs, false >
Static Public Member Functions
template<typename Dst >
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void evalTo (Dst &dst, const Lhs &lhs, const Rhs &rhs)
template<typename Dst >
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void addTo (Dst &dst, const Lhs &lhs, const Rhs &rhs)
template<typename Dst >
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void subTo (Dst &dst, const Lhs &lhs, const Rhs &rhs)
Member Typedef Documentation
impl
template<typename Lhs , typename Rhs > using Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, InnerProduct >::impl = default_inner_product_impl<Lhs, Rhs, false>
Member Function Documentation
addTo()
template<typename Lhs , typename Rhs > template<typename Dst > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, InnerProduct >::addTo (Dst & dst, const Lhs & lhs, const Rhs & rhs) inline static
{
     dst.coeffRef(0, 0) += impl::run(lhs, rhs);
   }
References run().
evalTo()
template<typename Lhs , typename Rhs > template<typename Dst > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, InnerProduct >::evalTo (Dst & dst, const Lhs & lhs, const Rhs & rhs) inline static
{
     dst.coeffRef(0, 0) = impl::run(lhs, rhs);
   }
References run().
subTo()
template<typename Lhs , typename Rhs > template<typename Dst > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::generic_product_impl< Lhs, Rhs, DenseShape, DenseShape, InnerProduct >::subTo (Dst & dst, const Lhs & lhs, const Rhs & rhs) inline static
{
     dst.coeffRef(0, 0) -= impl::run(lhs, rhs);
   }
References run().
The documentation for this struct was generated from the following file:
ProductEvaluators.h