MercuryDPM: Tutorial7_ParticleIn2DBox.cpp File Reference
Tutorial7_ParticleIn2DBox.cpp File Reference
#include <Species/LinearViscoelasticSpecies.h>
#include <Mercury3D.h>
#include <Walls/InfiniteWall.h>
Classes
class Tutorial7
[T7:headers]
Functions
int main (int argc, char *argv[])
[T7:class]
Function Documentation
main()
int main (int argc , char * argv[])
[T7:class]
[T7:main]
[T7:speciesProp]
[T7:speciesProp]
[T7:visualOutput]
 {
     // Problem setup
     Tutorial7 problem; // instantiate an object of class Tutorial 7
     problem.setName("Tutorial7");
     problem.setGravity(Vec3D(0.0, 0.0, 0.0));
     problem.setXMax(1);
     problem.setYMax(0.5);
     problem.setZMax(1.0);
     problem.setTimeMax(2.5);
     // The normal spring stiffness and normal dissipation is computed and set as
     // For collision time tc=0.005 and restitution coefficient rc=1.0,
     LinearViscoelasticSpecies species;
     species.setDensity(2500.0); //sets the species type_0 density
     species.setStiffness(258.5);//sets the spring stiffness.
     species.setDissipation(0.0); //sets the dissipation.
     problem.speciesHandler.copyAndAddObject(species);
     problem.setSaveCount(50);
     problem.dataFile.setFileType(FileType::ONE_FILE);
     problem.restartFile.setFileType(FileType::ONE_FILE);
     problem.fStatFile.setFileType(FileType::NO_FILE);
     problem.eneFile.setFileType(FileType::NO_FILE);
     problem.wallHandler.setWriteVTK(FileType::ONE_FILE);
     problem.setParticlesWriteVTK(true);
     problem.setTimeStep(0.005 / 50.0);// (collision time)/50.0
     problem.solve(argc, argv);
     return 0;
 }
References NO_FILE, ONE_FILE, problem, ParticleSpecies::setDensity(), LinearViscoelasticNormalSpecies::setDissipation(), and LinearViscoelasticNormalSpecies::setStiffness().