MercuryDPM: Beam Class Reference
Beam Class Reference
Defines a SolidProblem of element type RefineableQDPVDElement<3,2>. Add functionality to write output.
Public Member Functions
Beam ()
void checkBeamDeflection ()
Public Member Functions inherited from SolidProblem< RefineableQDPVDElement< 3, 2 > >
SolidProblem ()
Constructor: set default constitutive law and time stepper.
void setName (const std::string &name)
set function for name_
std::string getName () const
get function for name_
void setElasticModulus (double elasticModulus)
set function for elasticModulus_
double getElasticModulus () const
get function for elasticModulus_
void addDissipation (double dissipation)
void setupRefinementParameters (const double &min_error_target, const double &max_error_target, Z2ErrorEstimator *&error_estimator_pt)
void addAnisotropy (double Ex, double Ey, double Ez)
void setOomphGravity (double gravity)
set function for elasticModulus_
double getOomphGravity () const
get function for gravity_
void setPoissonRatio (double poissonRatio)
set function for poissonRatio_
double getPoissonRatio () const
get function for poissonRatio_
void setDensity (double density)
set function for density_
double getDensity () const
get function for density_
void setBodyForceAsGravity (double gravity=9.8)
set function for body_force_pt
void setIsPinned (std::function< bool(SolidNode *, unsigned)> isPinned)
set function for isPinned_
void pinBoundary (unsigned b)
void pinBoundaries (std::vector< unsigned > b)
std::enable_if< std::is_base_of< RefineableQDPVDElement< 3, 2 >, ELEMENT >::value, void > setDissipation (double dissipation)
Sets the dissipation coefficient for all elements.
void setNewtonSolverTolerance (double Newton_solver_tolerance)
set function for Newton_solver_tolerance
void setMaxNewtonIterations (unsigned Max_newton_iterations)
set function for Max_newton_iterations
void setOomphTimeStep (double dt)
set function for time step
double getOomphTimeStep () const
get function for time step
double getOomphTime () const
get function for current time
SolidMesh *& solid_mesh_pt ()
Get function for the solid mesh pointer.
SolidMesh *const & solid_mesh_pt () const
Get function for the solid mesh pointer.
SolidMesh *& traction_mesh_pt ()
Get function for the traction mesh pointer.
SolidMesh *const & traction_mesh_pt () const
Get function for the traction mesh pointer.
void getDomainSize (std::array< double, 3 > &min, std::array< double, 3 > &max) const
Computes the domain size (min/max of the nodal positions in x/y/z)
void prepareForSolve ()
void countPinned ()
returns statistics about pinned nodes to the console
void solveSteady (const unsigned &max_adapt=0)
void solveUnsteady (double timeMax, double dt, unsigned saveCount=10, const unsigned &max_adapt=0)
void solveUnsteadyForgiving (double timeMax, double timeMaxMin, double dt, unsigned saveCount=10)
void removeOldFiles () const
void get_x (const Vector< double > &xi, Vector< double > &x) const
double getDeflection (Vector< double > xi, unsigned d) const
void setSolidCubicMesh (const unsigned &nx, const unsigned &ny, const unsigned &nz, const double &xMin, const double &xMax, const double &yMin, const double &yMax, const double &zMin, const double &zMax)
void saveSolidMesh ()
void loadSolidMesh (std::string infileName, bool cubic=true)
void writeToVTK ()
void getMassMomentumEnergy (double &mass, Vector< double > &com, Vector< double > &linearMomentum, Vector< double > &angularMomentum, double &elasticEnergy, double &kineticEnergy) const
See PVDEquationsBase<DIM>::get_energy.
Private Member Functions
void actionsBeforeSolve () override
Write header of output file.
void actionsAfterSolve () override
Write header of output file.
void actionsBeforeOomphTimeStep () override
Each time step, compute deflection, elastic, kinetic and gravitational energy, and write to output file.
double getBeamDeflection () const
Computes beam deflection.
void actionsBeforeSolve () override
Write header of output file.
void actionsBeforeOomphTimeStep () override
Each time step, compute deflection, elastic, kinetic and gravitational energy, and write to output file.
double getBeamDeflection () const
Computes beam deflection.
Private Attributes
double length = 20.0
double distance = 0.4
double bulkDensity = 1309
double elasticModulus = 1e8
std::function< Vec3D(double)> velocityAtBoundary
std::ofstream out
output file stream
Additional Inherited Members
Public Types inherited from SolidProblem< RefineableQDPVDElement< 3, 2 > >
enum Boundary
Protected Types inherited from SolidProblem< RefineableQDPVDElement< 3, 2 > >
typedef RefineableQDPVDElement< 3, 2 > ELEMENT
Protected Attributes inherited from SolidProblem< RefineableQDPVDElement< 3, 2 > >
std::string name_
double elasticModulus_
Elastic modulus (set via setSolid)
double poissonRatio_
Poisson's ratio (set via setSolid)
double density_
Density.
double gravity_
Density.
void(* body_force_fct)(const double &time, const Vector< double > &xi, Vector< double > &b)
Pointer to the body force function.
ConstitutiveLaw * constitutive_law_pt
Pointer to constitutive law (should be set in constructor)
SolidMesh * Solid_mesh_pt
Pointer to solid mesh.
SolidMesh * Traction_mesh_pt
Pointer to mesh of traction elements.
std::function< bool(SolidNode *, unsigned)> isPinned_
Function to determine which nodal positions are pinned.
Detailed Description
Defines a SolidProblem of element type RefineableQDPVDElement<3,2>. Add functionality to write output.
Defines a SolidProblem of element type RefineableQDPVDElement<3,2>.
Constructor & Destructor Documentation
Beam()
Beam::Beam () inline
            {
         setName("SolidBeam");
         removeOldFiles();
         setElasticModulus(elasticModulus);
         setDensity(bulkDensity);
         setSolidCubicMesh(length/distance, 2, 2,
                           0, length, -distance, distance, distance, 3.0*distance);
         pinBoundaries({Beam::Boundary::X_MIN});
         setNewtonSolverTolerance(1e-2);
         prepareForSolve();
         linear_solver_pt()->disable_doc_time();
         // simulate two oscillations, check energy balance
         double waveSpeed = sqrt(getElasticModulus()/getDensity());
         double propagationTime = length/waveSpeed;
         double timeMax = 1.25*propagationTime;
         solveUnsteady(timeMax, 0.01*timeMax, 1);
     }
References bulkDensity, distance, e(), elasticModulus, SolidProblem< RefineableQDPVDElement< 3, 2 > >::getDensity(), SolidProblem< RefineableQDPVDElement< 3, 2 > >::getElasticModulus(), length, SolidProblem< RefineableQDPVDElement< 3, 2 > >::pinBoundaries(), SolidProblem< RefineableQDPVDElement< 3, 2 > >::prepareForSolve(), SolidProblem< RefineableQDPVDElement< 3, 2 > >::removeOldFiles(), SolidProblem< RefineableQDPVDElement< 3, 2 > >::setDensity(), SolidProblem< RefineableQDPVDElement< 3, 2 > >::setElasticModulus(), SolidProblem< RefineableQDPVDElement< 3, 2 > >::setName(), SolidProblem< RefineableQDPVDElement< 3, 2 > >::setNewtonSolverTolerance(), SolidProblem< RefineableQDPVDElement< 3, 2 > >::setSolidCubicMesh(), SolidProblem< RefineableQDPVDElement< 3, 2 > >::solveUnsteady(), and sqrt().
Member Function Documentation
actionsAfterSolve()
void Beam::actionsAfterSolve () inline override private virtual
Write header of output file.
Reimplemented from SolidProblem< RefineableQDPVDElement< 3, 2 > >.
{
         out.close();
     }
References out.
actionsBeforeOomphTimeStep() [1/2]
void Beam::actionsBeforeOomphTimeStep () inline override private virtual
Each time step, compute deflection, elastic, kinetic and gravitational energy, and write to output file.
Reimplemented from SolidProblem< RefineableQDPVDElement< 3, 2 > >.
{
         double mass, elasticEnergy, kineticEnergy;
         Vector<double> com(3), linearMomentum(3), angularMomentum(3);
         getMassMomentumEnergy(mass, com, linearMomentum, angularMomentum, elasticEnergy, kineticEnergy);
         static double comZ0 = com[2];
         double gravEnergy = 9.8*mass*(com[2]-comZ0);
         out << getOomphTime() << ' ' << getBeamDeflection() << ' ' << elasticEnergy << ' ' << kineticEnergy << ' ' << gravEnergy << std::endl;
         std::cout << getOomphTime() << ' ' << getBeamDeflection() << ' ' << elasticEnergy << ' ' << kineticEnergy << ' ' << gravEnergy << '\n';
         // set new position
         static Vec3D positionAtBoundary {0,0,0};
         Vec3D velocity = velocityAtBoundary(getOomphTime());
         positionAtBoundary += velocity * getOomphTimeStep();
         for (int n = 0; n < mesh_pt()->nboundary_node(Boundary::X_MIN); ++n) {
             SolidNode* node_pt = dynamic_cast<SolidNode*>(mesh_pt()->boundary_node_pt(Boundary::X_MIN,n));
             node_pt->x(0) = positionAtBoundary.X;
         }
     }
References getBeamDeflection(), SolidProblem< RefineableQDPVDElement< 3, 2 > >::getMassMomentumEnergy(), SolidProblem< RefineableQDPVDElement< 3, 2 > >::getOomphTime(), SolidProblem< RefineableQDPVDElement< 3, 2 > >::getOomphTimeStep(), n, out, Jeffery_Solution::velocity(), velocityAtBoundary, and oomph::Node::x().
actionsBeforeOomphTimeStep() [2/2]
void Beam::actionsBeforeOomphTimeStep () inline override private virtual
Each time step, compute deflection, elastic, kinetic and gravitational energy, and write to output file.
Reimplemented from SolidProblem< RefineableQDPVDElement< 3, 2 > >.
{
         double mass, elasticEnergy, kineticEnergy;
         Vector<double> com(3), linearMomentum(3), angularMomentum(3);
         getMassMomentumEnergy(mass, com, linearMomentum, angularMomentum, elasticEnergy, kineticEnergy);
         static double comZ0 = com[2];
         double gravEnergy = 9.8*mass*(com[2]-comZ0);
         out << getOomphTime() << ' ' << getBeamDeflection() << ' ' << elasticEnergy << ' ' << kineticEnergy << ' ' << gravEnergy << std::endl;
         std::cout << getOomphTime() << ' ' << getBeamDeflection() << ' ' << elasticEnergy << ' ' << kineticEnergy << ' ' << gravEnergy << '\n';
     }
References getBeamDeflection(), SolidProblem< RefineableQDPVDElement< 3, 2 > >::getMassMomentumEnergy(), SolidProblem< RefineableQDPVDElement< 3, 2 > >::getOomphTime(), and out.
actionsBeforeSolve() [1/2]
void Beam::actionsBeforeSolve () inline override private virtual
Write header of output file.
Reimplemented from SolidProblem< RefineableQDPVDElement< 3, 2 > >.
{
         helpers::writeToFile(getName()+".gnu", "set key autotitle columnheader\n"
                                                "p 'SolidBeamUnsteady.out' u 1:3 w l, '' u 1:4 w l, '' u 1:5 w l, '' u 1:($3+$4+$5) t 'totalEnergy' w l");
         out.open(getName()+".out");
         out << "time deflection elasticEnergy kineticEnergy gravEnergy\n";
     }
References SolidProblem< RefineableQDPVDElement< 3, 2 > >::getName(), out, and helpers::writeToFile().
actionsBeforeSolve() [2/2]
void Beam::actionsBeforeSolve () inline override private virtual
Write header of output file.
Reimplemented from SolidProblem< RefineableQDPVDElement< 3, 2 > >.
{
         helpers::writeToFile(getName()+".gnu", "set key autotitle columnheader\n"
            "p 'SolidBeamUnsteady.out' u 1:3 w l, '' u 1:4 w l, '' u 1:5 w l, '' u 1:($3+$4+$5) t 'totalEnergy' w l");
         out.open(getName()+".out");
         out << "time deflection elasticEnergy kineticEnergy gravEnergy\n";
     }
References SolidProblem< RefineableQDPVDElement< 3, 2 > >::getName(), out, and helpers::writeToFile().
checkBeamDeflection()
void Beam::checkBeamDeflection () inline
Checks the beam deflection against an analytical solution: https://autofem.com/examples/deflection_of_a_plate_under_theg.html
     {
         std::array<double,3> min, max;
         getDomainSize(min, max);
         double length = max[0]-min[0];
         double height = max[2]-min[2];
         logger(INFO, "Deflection should be -3*rho*g*L^4/(2*E*h^2) = % (in practice: %)",
                -3. * 9.8 * density_ * pow(length, 4) / ( 2. * elasticModulus_ * pow(height, 2) ), -0.00131642);
         Vector<double> xi(3);
         xi[0] = max[0];
         xi[1] = 0.5*(max[1]+min[1]);
         xi[2] = 0.5*(max[2]+min[2]);
         double deflection = getDeflection(xi,2);
         logger(INFO, "Beam deflection at right end (% % %) is %",
                xi[0], xi[1],xi[2], deflection);
         double mass, elasticEnergy, kineticEnergy;
         Vector<double> com(3), linearMomentum(3), angularMomentum(3);
         getMassMomentumEnergy(mass, com, linearMomentum, angularMomentum, elasticEnergy, kineticEnergy);
         logger(INFO, "mass %, linearMomentum %, angularMomentum %, elasticEnergy %, kineticEnergy %",
                mass, linearMomentum, angularMomentum, elasticEnergy, kineticEnergy);
         helpers::check(deflection,-0.00131642,1e-8,"Checking deflection");
     }
References helpers::check(), SolidProblem< RefineableQDPVDElement< 3, 2 > >::density_, e(), SolidProblem< RefineableQDPVDElement< 3, 2 > >::elasticModulus_, SolidProblem< RefineableQDPVDElement< 3, 2 > >::getDeflection(), SolidProblem< RefineableQDPVDElement< 3, 2 > >::getDomainSize(), SolidProblem< RefineableQDPVDElement< 3, 2 > >::getMassMomentumEnergy(), Global_Physical_Variables::height(), INFO, length, logger, max, min, and Eigen::bfloat16_impl::pow().
getBeamDeflection() [1/2]
double Beam::getBeamDeflection () const inline private
Computes beam deflection.
{
         std::array<double, 3> min, max;
         getDomainSize(min, max);
         Vector<double> xi(3);
         xi[0] = max[0];
         xi[1] = 0.5 * (max[1] + min[1]);
         xi[2] = 0.5 * (max[2] + min[2]);
         return getDeflection(xi, 2);
     }
References SolidProblem< RefineableQDPVDElement< 3, 2 > >::getDeflection(), SolidProblem< RefineableQDPVDElement< 3, 2 > >::getDomainSize(), max, and min.
Referenced by actionsBeforeOomphTimeStep().
getBeamDeflection() [2/2]
double Beam::getBeamDeflection () const inline private
Computes beam deflection.
{
         std::array<double, 3> min, max;
         getDomainSize(min, max);
         Vector<double> xi(3);
         xi[0] = max[0];
         xi[1] = 0.5 * (max[1] + min[1]);
         xi[2] = 0.5 * (max[2] + min[2]);
         return getDeflection(xi, 2);
     }
References SolidProblem< RefineableQDPVDElement< 3, 2 > >::getDeflection(), SolidProblem< RefineableQDPVDElement< 3, 2 > >::getDomainSize(), max, and min.
Member Data Documentation
bulkDensity
double Beam::bulkDensity = 1309 private
Referenced by Beam().
distance
double Beam::distance = 0.4 private
Referenced by Beam().
elasticModulus
double Beam::elasticModulus = 1e8 private
Referenced by Beam().
length
double Beam::length = 20.0 private
Referenced by Beam(), and checkBeamDeflection().
out
std::ofstream Beam::out private
output file stream
Referenced by actionsAfterSolve(), actionsBeforeOomphTimeStep(), and actionsBeforeSolve().
velocityAtBoundary
std::function<Vec3D(double)> Beam::velocityAtBoundary private
Initial value:
=
        [] (double) {return Vec3D(0.1,0,0);}
Referenced by actionsBeforeOomphTimeStep().
The documentation for this class was generated from the following files:
SolidBeam.cpp
SolidBeamUnsteady.cpp
SolidBeamUnitTest.cpp