MercuryDPM: oomph::IterativeLinearSolver Class Reference
oomph::IterativeLinearSolver Class Reference abstract
#include <iterative_linear_solver.h>
Public Member Functions
IterativeLinearSolver ()
IterativeLinearSolver (const IterativeLinearSolver &)=delete
Broken copy constructor.
void operator= (const IterativeLinearSolver &)=delete
Broken assignment operator.
virtual ~IterativeLinearSolver ()
Destructor (empty)
Preconditioner *& preconditioner_pt ()
Access function to preconditioner.
Preconditioner *const & preconditioner_pt () const
Access function to preconditioner (const version)
double & tolerance ()
Access to convergence tolerance.
unsigned & max_iter ()
Access to max. number of iterations.
virtual unsigned iterations () const =0
Number of iterations taken.
void enable_doc_convergence_history ()
Enable documentation of the convergence history.
void disable_doc_convergence_history ()
Disable documentation of the convergence history.
void open_convergence_history_file_stream (const std::string &file_name, const std::string &zone_title="")
void close_convergence_history_file_stream ()
Close convergence history output stream.
double jacobian_setup_time () const
double linear_solver_solution_time () const
return the time taken to solve the linear system
virtual double preconditioner_setup_time () const
returns the the time taken to setup the preconditioner
void enable_setup_preconditioner_before_solve ()
Setup the preconditioner before the solve.
void disable_setup_preconditioner_before_solve ()
Don't set up the preconditioner before the solve.
void enable_error_after_max_iter ()
Throw an error if we don't converge within max_iter.
void disable_error_after_max_iter ()
Don't throw an error if we don't converge within max_iter (default).
void enable_iterative_solver_as_preconditioner ()
void disable_iterative_solver_as_preconditioner ()
Public Member Functions inherited from oomph::LinearSolver
LinearSolver ()
Empty constructor, initialise the member data.
LinearSolver (const LinearSolver &dummy)=delete
Broken copy constructor.
void operator= (const LinearSolver &)=delete
Broken assignment operator.
virtual ~LinearSolver ()
Empty virtual destructor.
void enable_doc_time ()
Enable documentation of solve times.
void disable_doc_time ()
Disable documentation of solve times.
bool is_doc_time_enabled () const
Is documentation of solve times enabled?
bool is_resolve_enabled () const
Boolean flag indicating if resolves are enabled.
virtual void enable_resolve ()
virtual void disable_resolve ()
virtual void solve (Problem *const &problem_pt, DoubleVector &result)=0
virtual void solve (DoubleMatrixBase *const &matrix_pt, const DoubleVector &rhs, DoubleVector &result)
virtual void solve (DoubleMatrixBase *const &matrix_pt, const Vector< double > &rhs, Vector< double > &result)
virtual void solve_transpose (Problem *const &problem_pt, DoubleVector &result)
virtual void solve_transpose (DoubleMatrixBase *const &matrix_pt, const DoubleVector &rhs, DoubleVector &result)
virtual void solve_transpose (DoubleMatrixBase *const &matrix_pt, const Vector< double > &rhs, Vector< double > &result)
virtual void resolve (const DoubleVector &rhs, DoubleVector &result)
virtual void resolve_transpose (const DoubleVector &rhs, DoubleVector &result)
virtual void clean_up_memory ()
virtual void enable_computation_of_gradient ()
void disable_computation_of_gradient ()
void reset_gradient ()
void get_gradient (DoubleVector &gradient)
function to access the gradient, provided it has been computed
Public Member Functions inherited from oomph::DistributableLinearAlgebraObject
DistributableLinearAlgebraObject ()
Default constructor - create a distribution.
DistributableLinearAlgebraObject (const DistributableLinearAlgebraObject &matrix)=delete
Broken copy constructor.
void operator= (const DistributableLinearAlgebraObject &)=delete
Broken assignment operator.
virtual ~DistributableLinearAlgebraObject ()
Destructor.
LinearAlgebraDistribution * distribution_pt () const
access to the LinearAlgebraDistribution
unsigned nrow () const
access function to the number of global rows.
unsigned nrow_local () const
access function for the num of local rows on this processor.
unsigned nrow_local (const unsigned &p) const
access function for the num of local rows on this processor.
unsigned first_row () const
access function for the first row on this processor
unsigned first_row (const unsigned &p) const
access function for the first row on this processor
bool distributed () const
distribution is serial or distributed
bool distribution_built () const
void build_distribution (const LinearAlgebraDistribution *const dist_pt)
void build_distribution (const LinearAlgebraDistribution &dist)
Protected Attributes
bool Doc_convergence_history
std::ofstream Output_file_stream
Output file stream for convergence history.
double Tolerance
Convergence tolerance.
unsigned Max_iter
Maximum number of iterations.
Preconditioner * Preconditioner_pt
Pointer to the preconditioner.
double Jacobian_setup_time
Jacobian setup time.
double Solution_time
linear solver solution time
double Preconditioner_setup_time
Preconditioner setup time.
bool Setup_preconditioner_before_solve
bool Throw_error_after_max_iter
bool Use_iterative_solver_as_preconditioner
Use the iterative solver as preconditioner.
bool First_time_solve_when_used_as_preconditioner
Protected Attributes inherited from oomph::LinearSolver
bool Enable_resolve
bool Doc_time
Boolean flag that indicates whether the time taken.
bool Compute_gradient
bool Gradient_has_been_computed
flag that indicates whether the gradient was computed or not
DoubleVector Gradient_for_glob_conv_newton_solve
Static Protected Attributes
static IdentityPreconditioner Default_preconditioner
Additional Inherited Members
Protected Member Functions inherited from oomph::DistributableLinearAlgebraObject
void clear_distribution ()
Detailed Description
Base class for all linear iterative solvers. This merely defines standard interfaces for linear iterative solvers, so that different solvers can be used in a clean and transparent manner.
Constructor & Destructor Documentation
IterativeLinearSolver() [1/2]
oomph::IterativeLinearSolver::IterativeLinearSolver () inline
Constructor: Set (default) trivial preconditioner and set defaults for tolerance and max. number of iterations
                             : Preconditioner_setup_time(0)
     {
       // Set pointer to default preconditioner
       Preconditioner_pt = &Default_preconditioner;
       // Set default convergence tolerance
       Tolerance = 1.0e-8;
       // Set maximum number of iterations
       Max_iter = 100;
       // set default for document convergence history
       Doc_convergence_history = false;
       // set default
       Setup_preconditioner_before_solve = true;
       Throw_error_after_max_iter = false;
       // By default the iterative solver is not used as preconditioner
       Use_iterative_solver_as_preconditioner = false;
       // Indicates whether this is the first time we call the solve
       // method
       First_time_solve_when_used_as_preconditioner = true;
     }
References Default_preconditioner, Doc_convergence_history, First_time_solve_when_used_as_preconditioner, Max_iter, Preconditioner_pt, Setup_preconditioner_before_solve, Throw_error_after_max_iter, Tolerance, and Use_iterative_solver_as_preconditioner.
IterativeLinearSolver() [2/2]
oomph::IterativeLinearSolver::IterativeLinearSolver (const IterativeLinearSolver &) delete
Broken copy constructor.
~IterativeLinearSolver()
virtual oomph::IterativeLinearSolver::~IterativeLinearSolver () inline virtual
Destructor (empty)
 {}
Member Function Documentation
close_convergence_history_file_stream()
void oomph::IterativeLinearSolver::close_convergence_history_file_stream () inline
Close convergence history output stream.
     {
       if (Output_file_stream.is_open()) Output_file_stream.close();
     }
References Output_file_stream.
Referenced by PreconditionedFSICollapsibleChannelProblem< ELEMENT >::actions_after_newton_solve(), and PreconditionedFSICollapsibleChannelProblem< ELEMENT >::actions_before_newton_convergence_check().
disable_doc_convergence_history()
void oomph::IterativeLinearSolver::disable_doc_convergence_history () inline
Disable documentation of the convergence history.
     {
       Doc_convergence_history = false;
     }
References Doc_convergence_history.
disable_error_after_max_iter()
void oomph::IterativeLinearSolver::disable_error_after_max_iter () inline
Don't throw an error if we don't converge within max_iter (default).
     {
       Throw_error_after_max_iter = false;
     }
References Throw_error_after_max_iter.
disable_iterative_solver_as_preconditioner()
void oomph::IterativeLinearSolver::disable_iterative_solver_as_preconditioner () inline
Disables the iterative solver be used as preconditioner (when calling the solve method it bypass the setup solver method – currently only used by Trilinos solver —)
     {
       Use_iterative_solver_as_preconditioner = false;
     }
References Use_iterative_solver_as_preconditioner.
disable_setup_preconditioner_before_solve()
void oomph::IterativeLinearSolver::disable_setup_preconditioner_before_solve () inline
Don't set up the preconditioner before the solve.
     {
       Setup_preconditioner_before_solve = false;
     }
References Setup_preconditioner_before_solve.
enable_doc_convergence_history()
void oomph::IterativeLinearSolver::enable_doc_convergence_history () inline
Enable documentation of the convergence history.
     {
       Doc_convergence_history = true;
     }
References Doc_convergence_history.
Referenced by main().
enable_error_after_max_iter()
void oomph::IterativeLinearSolver::enable_error_after_max_iter () inline
Throw an error if we don't converge within max_iter.
     {
       Throw_error_after_max_iter = true;
     }
References Throw_error_after_max_iter.
Referenced by oomph::MyProblem::build().
enable_iterative_solver_as_preconditioner()
void oomph::IterativeLinearSolver::enable_iterative_solver_as_preconditioner () inline
Enables the iterative solver be used as preconditioner (when calling the solve method it bypass the setup solver method – currently only used by Trilinos solver —)
     {
       Use_iterative_solver_as_preconditioner = true;
     }
References Use_iterative_solver_as_preconditioner.
enable_setup_preconditioner_before_solve()
void oomph::IterativeLinearSolver::enable_setup_preconditioner_before_solve () inline
Setup the preconditioner before the solve.
     {
       Setup_preconditioner_before_solve = true;
     }
References Setup_preconditioner_before_solve.
iterations()
virtual unsigned oomph::IterativeLinearSolver::iterations () const pure virtual
Number of iterations taken.
Implemented in oomph::GMRESBlockPreconditioner, oomph::GMRESBlockPreconditioner, oomph::HelmholtzGMRESMG< MATRIX >, oomph::ComplexGMRES< MATRIX >, oomph::ComplexDampedJacobi< MATRIX >, oomph::TrilinosAztecOOSolver, oomph::AugmentedProblemGMRES, oomph::GMRES< MATRIX >, oomph::DampedJacobi< MATRIX >, oomph::GS< CRDoubleMatrix >, oomph::GS< MATRIX >, oomph::BiCGStab< MATRIX >, oomph::CG< MATRIX >, and oomph::MGSolver< DIM >.
Referenced by oomph::MyProblem::actions_after_explicit_stage(), TiltedCavityProblem< ELEMENT >::actions_after_newton_step(), and oomph::MyProblem::actions_after_newton_step().
jacobian_setup_time()
double oomph::IterativeLinearSolver::jacobian_setup_time () const inline virtual
returns the time taken to assemble the jacobian matrix and residual vector
Reimplemented from oomph::LinearSolver.
     {
       return Jacobian_setup_time;
     }
References Jacobian_setup_time.
linear_solver_solution_time()
double oomph::IterativeLinearSolver::linear_solver_solution_time () const inline virtual
return the time taken to solve the linear system
Reimplemented from oomph::LinearSolver.
     {
       return Solution_time;
     }
References Solution_time.
max_iter()
unsigned& oomph::IterativeLinearSolver::max_iter () inline
Access to max. number of iterations.
     {
       return Max_iter;
     }
References Max_iter.
Referenced by oomph::MyProblem::build(), FSIChannelWithLeafletProblem< ELEMENT >::FSIChannelWithLeafletProblem(), main(), PreconditionedFSICollapsibleChannelProblem< ELEMENT >::PreconditionedFSICollapsibleChannelProblem(), run_it(), PMLStructuredCubicHelmholtz< ELEMENT >::set_gmres_multigrid_solver(), PMLHelmholtzMGProblem< ELEMENT >::set_gmres_multigrid_solver(), RefineableConvectionProblem< NST_ELEMENT, AD_ELEMENT >::switch_to_iterative_linear_solver(), TorusProblem< ELEMENT >::TorusProblem(), and TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::TurekProblem().
open_convergence_history_file_stream()
void oomph::IterativeLinearSolver::open_convergence_history_file_stream (const std::string & file_name, const std::string & zone_title = "") inline
Write convergence history into file with specified filename (automatically switches on doc). Optional second argument is a string that can be used (as a zone title) to identify what case we're running (e.g. what combination of linear solver and preconditioner or parameter values are used).
     {
       // start docing
       Doc_convergence_history = true;
       // Close if it's open
       if (Output_file_stream.is_open())
       {
         Output_file_stream.close();
       }
       // Open new one
       Output_file_stream.open(file_name.c_str());
       // Write tecplot zone header
       Output_file_stream << "VARIABLES=\"iterations\", \"scaled residual\""
                          << std::endl;
       Output_file_stream << "ZONE T=\"" << zone_title << "\"" << std::endl;
       Output_file_stream << 0 << " " << 1.0 << std::endl;
     }
References Doc_convergence_history, Particles2023AnalysisHung::file_name, and Output_file_stream.
Referenced by PreconditionedFSICollapsibleChannelProblem< ELEMENT >::actions_before_newton_convergence_check(), MultiPoissonProblem< ELEMENT >::MultiPoissonProblem(), PMLStructuredCubicHelmholtz< ELEMENT >::set_gmres_multigrid_solver(), PMLHelmholtzMGProblem< ELEMENT >::set_gmres_multigrid_solver(), FluxPoissonMGProblem< ELEMENT, MESH >::set_multigrid_solver(), and UnitCubePoissonMGProblem< ELEMENT, MESH >::set_multigrid_solver().
operator=()
void oomph::IterativeLinearSolver::operator= (const IterativeLinearSolver &) delete
Broken assignment operator.
preconditioner_pt() [1/2]
Preconditioner*& oomph::IterativeLinearSolver::preconditioner_pt () inline
Access function to preconditioner.
     {
       return Preconditioner_pt;
     }
References Preconditioner_pt.
Referenced by oomph::AugmentedProblemGMRES::apply_schur_complement_preconditioner(), oomph::MyProblem::build(), oomph::TrilinosAztecOOSolver::clean_up_memory(), FSIChannelWithLeafletProblem< ELEMENT >::FSIChannelWithLeafletProblem(), main(), MultiPoissonProblem< ELEMENT >::MultiPoissonProblem(), parallel_test(), PreconditionedFSICollapsibleChannelProblem< ELEMENT >::PreconditionedFSICollapsibleChannelProblem(), PrescribedBoundaryDisplacementProblem< ELEMENT >::PrescribedBoundaryDisplacementProblem(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::project(), PMLStructuredCubicHelmholtz< ELEMENT >::set_gmres_multigrid_solver(), PMLHelmholtzMGProblem< ELEMENT >::set_gmres_multigrid_solver(), FSIChannelWithLeafletProblem< ELEMENT >::set_iterative_solver(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::set_pseudo_elastic_fsi_solver(), set_pseudo_elastic_fsi_solver(), oomph::AugmentedProblemGMRES::solve_helper(), RefineableConvectionProblem< NST_ELEMENT, AD_ELEMENT >::switch_to_iterative_linear_solver(), TorusProblem< ELEMENT >::TorusProblem(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::TurekProblem(), oomph::GMRES< MATRIX >::update(), oomph::HelmholtzGMRESMG< MATRIX >::update(), and RefineableConvectionProblem< NST_ELEMENT, AD_ELEMENT >::~RefineableConvectionProblem().
preconditioner_pt() [2/2]
Preconditioner* const& oomph::IterativeLinearSolver::preconditioner_pt () const inline
Access function to preconditioner (const version)
     {
       return Preconditioner_pt;
     }
References Preconditioner_pt.
preconditioner_setup_time()
virtual double oomph::IterativeLinearSolver::preconditioner_setup_time () const inline virtual
returns the the time taken to setup the preconditioner
Reimplemented in oomph::GS< CRDoubleMatrix >, and oomph::GS< MATRIX >.
     {
       return Preconditioner_setup_time;
     }
References Preconditioner_setup_time.
Referenced by oomph::MyProblem::actions_after_explicit_stage(), and oomph::MyProblem::actions_after_newton_step().
tolerance()
double& oomph::IterativeLinearSolver::tolerance () inline
Access to convergence tolerance.
     {
       return Tolerance;
     }
References Tolerance.
Referenced by oomph::ComplexDampedJacobi< MATRIX >::calculate_omega(), oomph::ComplexGMRES< MATRIX >::generate_plane_rotation(), oomph::HelmholtzGMRESMG< MATRIX >::generate_plane_rotation(), main(), MultiPoissonProblem< ELEMENT >::MultiPoissonProblem(), PreconditionedFSICollapsibleChannelProblem< ELEMENT >::PreconditionedFSICollapsibleChannelProblem(), PMLStructuredCubicHelmholtz< ELEMENT >::set_gmres_multigrid_solver(), PMLHelmholtzMGProblem< ELEMENT >::set_gmres_multigrid_solver(), set_pseudo_elastic_fsi_solver(), oomph::MGSolver< DIM >::setup_smoothers(), oomph::HelmholtzMGPreconditioner< DIM >::setup_smoothers(), RefineableConvectionProblem< NST_ELEMENT, AD_ELEMENT >::switch_to_iterative_linear_solver(), TiltedCavityProblem< ELEMENT >::TiltedCavityProblem(), TorusProblem< ELEMENT >::TorusProblem(), and TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::TurekProblem().
Member Data Documentation
Default_preconditioner
IdentityPreconditioner oomph::IterativeLinearSolver::Default_preconditioner static protected
Default preconditioner: The base class for preconditioners is a fully functional (if trivial!) preconditioner.
Default preconditioner for iterative solvers: The base class for preconditioners is a fully functional (if trivial!) preconditioner.
Referenced by IterativeLinearSolver().
Doc_convergence_history
bool oomph::IterativeLinearSolver::Doc_convergence_history protected
Flag indicating if the convergence history is to be documented
Referenced by disable_doc_convergence_history(), enable_doc_convergence_history(), IterativeLinearSolver(), open_convergence_history_file_stream(), oomph::GMRESBlockPreconditioner::preconditioner_solve(), oomph::GS< CRDoubleMatrix >::solve_helper(), and oomph::AugmentedProblemGMRES::solve_helper().
First_time_solve_when_used_as_preconditioner
bool oomph::IterativeLinearSolver::First_time_solve_when_used_as_preconditioner protected
When the iterative solver is used a preconditioner then we call the setup of solver method only once (the first time the solve method is called)
Referenced by IterativeLinearSolver(), and oomph::TrilinosAztecOOSolver::solve().
Jacobian_setup_time
double oomph::IterativeLinearSolver::Jacobian_setup_time protected
Jacobian setup time.
Referenced by jacobian_setup_time(), oomph::GS< CRDoubleMatrix >::solve(), oomph::AugmentedProblemGMRES::solve(), oomph::HelmholtzGMRESMG< MATRIX >::solve(), and oomph::HelmholtzFGMRESMG< MATRIX >::solve().
Max_iter
unsigned oomph::IterativeLinearSolver::Max_iter protected
Maximum number of iterations.
Referenced by IterativeLinearSolver(), max_iter(), oomph::TrilinosAztecOOSolver::max_iter(), oomph::GMRESBlockPreconditioner::preconditioner_solve(), oomph::GS< CRDoubleMatrix >::solve_helper(), oomph::AugmentedProblemGMRES::solve_helper(), oomph::TrilinosAztecOOSolver::solve_using_AztecOO(), and oomph::TrilinosAztecOOSolver::solver_setup().
Output_file_stream
std::ofstream oomph::IterativeLinearSolver::Output_file_stream protected
Output file stream for convergence history.
Referenced by close_convergence_history_file_stream(), open_convergence_history_file_stream(), oomph::GMRESBlockPreconditioner::preconditioner_solve(), oomph::GS< CRDoubleMatrix >::solve_helper(), and oomph::AugmentedProblemGMRES::solve_helper().
Preconditioner_pt
Preconditioner* oomph::IterativeLinearSolver::Preconditioner_pt protected
Pointer to the preconditioner.
Referenced by IterativeLinearSolver(), preconditioner_pt(), and oomph::TrilinosAztecOOSolver::solver_setup().
Preconditioner_setup_time
double oomph::IterativeLinearSolver::Preconditioner_setup_time protected
Preconditioner setup time.
Referenced by preconditioner_setup_time(), and oomph::AugmentedProblemGMRES::solve_helper().
Setup_preconditioner_before_solve
bool oomph::IterativeLinearSolver::Setup_preconditioner_before_solve protected
indicates whether the preconditioner should be setup before solve. Default = true;
Referenced by disable_setup_preconditioner_before_solve(), enable_setup_preconditioner_before_solve(), IterativeLinearSolver(), oomph::AugmentedProblemGMRES::solve_helper(), and oomph::TrilinosAztecOOSolver::solver_setup().
Solution_time
double oomph::IterativeLinearSolver::Solution_time protected
linear solver solution time
Referenced by linear_solver_solution_time(), oomph::GMRESBlockPreconditioner::preconditioner_solve(), oomph::GS< CRDoubleMatrix >::solve_helper(), and oomph::AugmentedProblemGMRES::solve_helper().
Throw_error_after_max_iter
bool oomph::IterativeLinearSolver::Throw_error_after_max_iter protected
Should we throw an error instead of just returning when we hit the max iterations?
Referenced by disable_error_after_max_iter(), enable_error_after_max_iter(), IterativeLinearSolver(), oomph::GMRESBlockPreconditioner::preconditioner_solve(), oomph::GS< CRDoubleMatrix >::solve_helper(), and oomph::AugmentedProblemGMRES::solve_helper().
Tolerance
double oomph::IterativeLinearSolver::Tolerance protected
Convergence tolerance.
Referenced by IterativeLinearSolver(), oomph::MGSolver< DIM >::MGSolver(), oomph::GMRESBlockPreconditioner::preconditioner_solve(), oomph::GS< CRDoubleMatrix >::solve_helper(), oomph::AugmentedProblemGMRES::solve_helper(), oomph::TrilinosAztecOOSolver::solve_using_AztecOO(), tolerance(), oomph::TrilinosAztecOOSolver::tolerance(), and oomph::TrilinosAztecOOSolver::TrilinosAztecOOSolver().
Use_iterative_solver_as_preconditioner
bool oomph::IterativeLinearSolver::Use_iterative_solver_as_preconditioner protected
Use the iterative solver as preconditioner.
Referenced by disable_iterative_solver_as_preconditioner(), enable_iterative_solver_as_preconditioner(), IterativeLinearSolver(), and oomph::TrilinosAztecOOSolver::solve().
The documentation for this class was generated from the following files:
iterative_linear_solver.h
iterative_linear_solver.cc