MercuryDPM: Eigen::SparseLUMatrixLReturnType< MappedSupernodalType > Struct Template Reference
Eigen::SparseLUMatrixLReturnType< MappedSupernodalType > Struct Template Reference
#include <SparseLU.h>
Public Types
typedef MappedSupernodalType::Scalar Scalar
Public Member Functions
SparseLUMatrixLReturnType (const MappedSupernodalType &mapL)
Index rows () const
Index cols () const
template<typename Dest >
void solveInPlace (MatrixBase< Dest > &X) const
template<bool Conjugate, typename Dest >
void solveTransposedInPlace (MatrixBase< Dest > &X) const
SparseMatrix< Scalar, ColMajor, Index > toSparse () const
Public Attributes
const MappedSupernodalType & m_mapL
Member Typedef Documentation
Scalar
template<typename MappedSupernodalType > typedef MappedSupernodalType::Scalar Eigen::SparseLUMatrixLReturnType< MappedSupernodalType >::Scalar
Constructor & Destructor Documentation
SparseLUMatrixLReturnType()
template<typename MappedSupernodalType > Eigen::SparseLUMatrixLReturnType< MappedSupernodalType >::SparseLUMatrixLReturnType (const MappedSupernodalType & mapL) inline explicit
 : m_mapL(mapL) {}
Member Function Documentation
cols()
template<typename MappedSupernodalType > Index Eigen::SparseLUMatrixLReturnType< MappedSupernodalType >::cols () const inline
 { return m_mapL.cols(); }
References Eigen::SparseLUMatrixLReturnType< MappedSupernodalType >::m_mapL.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and Eigen::SparseLUMatrixLReturnType< MappedSupernodalType >::toSparse().
rows()
template<typename MappedSupernodalType > Index Eigen::SparseLUMatrixLReturnType< MappedSupernodalType >::rows () const inline
 { return m_mapL.rows(); }
References Eigen::SparseLUMatrixLReturnType< MappedSupernodalType >::m_mapL.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and Eigen::SparseLUMatrixLReturnType< MappedSupernodalType >::toSparse().
solveInPlace()
template<typename MappedSupernodalType > template<typename Dest > void Eigen::SparseLUMatrixLReturnType< MappedSupernodalType >::solveInPlace (MatrixBase< Dest > & X) const inline
{
     m_mapL.solveInPlace(X);
   }
References Eigen::SparseLUMatrixLReturnType< MappedSupernodalType >::m_mapL, and X.
solveTransposedInPlace()
template<typename MappedSupernodalType > template<bool Conjugate, typename Dest > void Eigen::SparseLUMatrixLReturnType< MappedSupernodalType >::solveTransposedInPlace (MatrixBase< Dest > & X) const inline
{
     m_mapL.template solveTransposedInPlace<Conjugate>(X);
   }
References Eigen::SparseLUMatrixLReturnType< MappedSupernodalType >::m_mapL, and X.
toSparse()
template<typename MappedSupernodalType > SparseMatrix<Scalar, ColMajor, Index> Eigen::SparseLUMatrixLReturnType< MappedSupernodalType >::toSparse () const inline
{
     ArrayXi colCount = ArrayXi::Ones(cols());
     for (Index i = 0; i < cols(); i++) {
       typename MappedSupernodalType::InnerIterator iter(m_mapL, i);
       for (; iter; ++iter) {
         if (iter.row() > iter.col()) {
           colCount(iter.col())++;
         }
       }
     }
     SparseMatrix<Scalar, ColMajor, Index> sL(rows(), cols());
     sL.reserve(colCount);
     for (Index i = 0; i < cols(); i++) {
       sL.insert(i, i) = 1.0;
       typename MappedSupernodalType::InnerIterator iter(m_mapL, i);
       for (; iter; ++iter) {
         if (iter.row() > iter.col()) {
           sL.insert(iter.row(), iter.col()) = iter.value();
         }
       }
     }
     sL.makeCompressed();
     return sL;
   }
References Eigen::SparseLUMatrixLReturnType< MappedSupernodalType >::cols(), i, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insert(), Eigen::SparseLUMatrixLReturnType< MappedSupernodalType >::m_mapL, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::makeCompressed(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::reserve(), and Eigen::SparseLUMatrixLReturnType< MappedSupernodalType >::rows().
Member Data Documentation
m_mapL
template<typename MappedSupernodalType > const MappedSupernodalType& Eigen::SparseLUMatrixLReturnType< MappedSupernodalType >::m_mapL
Referenced by Eigen::SparseLUMatrixLReturnType< MappedSupernodalType >::cols(), Eigen::SparseLUMatrixLReturnType< MappedSupernodalType >::rows(), Eigen::SparseLUMatrixLReturnType< MappedSupernodalType >::solveInPlace(), Eigen::SparseLUMatrixLReturnType< MappedSupernodalType >::solveTransposedInPlace(), and Eigen::SparseLUMatrixLReturnType< MappedSupernodalType >::toSparse().
The documentation for this struct was generated from the following file:
SparseLU.h