MercuryDPM: SinterBed0SelfTest.cpp File Reference
SinterBed0SelfTest.cpp File Reference
#include "Mercury3D.h"
#include "Species/SinterFrictionSpecies.h"
#include "Walls/InfiniteWall.h"
#include "Boundaries/PeriodicBoundary.h"
#include "Walls/AxisymmetricIntersectionOfWalls.h"
Classes
class InitialConditions< SpeciesType >
One particle, sintering slowly to a wall.
Functions
int main (int argc UNUSED, char *argv[] UNUSED)
Function Documentation
main()
int main (int argc UNUSED, char *argv[] UNUSED)
Todo:
TW automatically measure simulation time
 {
     const Mdouble radius = readFromFile("in","radius",6e-6);
     const Mdouble domainRadius = readFromFile("in","domainDiameterOverParticleDiameter",5.0) * radius;
     const Mdouble domainHeight = readFromFile("in","domainHeightOverParticleDiameter",5.0) * 2.0 * radius;
     const unsigned dimensions = static_cast<const unsigned int>(readFromFile("in", "dimensions", 2));
     InitialConditions<SinterFrictionSpecies> ic(radius, domainRadius, domainHeight,dimensions);
     const unsigned long int random = readFromFile("in","random",0);
     ic.random.setRandomSeed(random);
     ic.scaleMass(1e12);
     //set species properties
     const Mdouble kMax=readFromFile("in","kMax",20000);
     const Mdouble kL = readFromFile("in","kL",0.1*kMax);
     ic.species->setPlasticParameters(kL, kMax, kL, 0.16);
     const Mdouble mass = ic.species->getSmallestParticleMass();
     ic.species->setStiffnessAndRestitutionCoefficient(ic.species->getLoadingStiffness(),0.5,mass);
     ic.species->setSinterType(SINTERTYPE::CONSTANT_RATE);
     ic.species->setSinterRate(0.0);
     ic.species->setSinterAdhesion(1200e-9/radius);
     ic.species->setSlidingDissipation(2./7.*ic.species->getDissipation());
     ic.species->setSlidingStiffness(2./7.*ic.species->getLoadingStiffness());
     ic.species->setRollingDissipation(2./7.*ic.species->getDissipation());
     ic.species->setRollingStiffness(2./7.*ic.species->getLoadingStiffness());
     ic.species->setTorsionDissipation(2./7.*ic.species->getDissipation());
     ic.species->setTorsionStiffness(2./7.*ic.species->getLoadingStiffness());
     ic.setTimeMax(1e20);
 //    ic.interactionHandler.setWriteVTK(FileType::MULTIPLE_FILES);
 //    ic.setParticlesWriteVTK(true);
 //    ic.wallHandler.setWriteVTK(FileType::MULTIPLE_FILES);
     ic.solve();
     return 0;
     //r=3 -> 220 particles
 }
References CONSTANT_RATE, e(), UniformPSDSelfTest::radius, DPMBase::random, helpers::readFromFile(), InitialConditions< SpeciesType >::scaleMass(), RNG::setRandomSeed(), DPMBase::setTimeMax(), DPMBase::solve(), and InitialConditions< SpeciesType >::species.