MercuryDPM: two_d_multi_poisson.cc File Reference
mpi/solvers/two_d_multi_poisson.cc File Reference
#include <fenv.h>
#include "generic.h"
#include "../../linear_solvers/multi_poisson_elements.h"
#include "meshes/simple_rectangular_quadmesh.h"
#include "../../linear_solvers/multi_poisson_block_preconditioners.h"
Classes
class MultiPoissonProblem< ELEMENT >
Namespaces
TanhSolnForMultiPoisson
Namespace for exact solution for MultiPoisson equation with "sharp step".
Macros
#define N_FIELD 5
Functions
double TanhSolnForMultiPoisson::scalar_soln (const Vector< double > &x)
Scalar solution.
double TanhSolnForMultiPoisson::scalar_source (const Vector< double > &x)
Scalar source.
void TanhSolnForMultiPoisson::get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void TanhSolnForMultiPoisson::source_function (const Vector< double > &x, Vector< double > &source)
Source function required to make the solution above an exact solution.
int main (int argc, char *argv[])
Driver code for 2D MultiPoisson problem.
Macro Definition Documentation
N_FIELD
#define N_FIELD 5
Function Documentation
main()
int main (int argc , char * argv[])
Driver code for 2D MultiPoisson problem.
 {
 // feenableexcept(FE_INVALID|FE_DIVBYZERO|FE_OVERFLOW|FE_UNDERFLOW);
 #ifdef OOMPH_HAS_MPI
  // Initialise MPI
  MPI_Helpers::init(argc,argv);
 #endif
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Define possible command line arguments and parse the ones that
  // were actually specified
  CommandLineArgs::specify_command_line_flag("--simple");
  CommandLineArgs::specify_command_line_flag
   ("--upper_triangular");
  CommandLineArgs::specify_command_line_flag
   ("--two_plus_three");
  CommandLineArgs::specify_command_line_flag
   ("--two_plus_three_upper_triangular");
  CommandLineArgs::specify_command_line_flag
   ("--two_plus_three_upper_triangular_with_sub");
  CommandLineArgs::specify_command_line_flag
   ("--two_plus_three_upper_triangular_with_two_sub");
  CommandLineArgs::specify_command_line_flag
   ("--two_plus_three_upper_triangular_with_replace");
  CommandLineArgs::specify_command_line_flag
   ("--coarse_two_plus_two_plus_one");
  CommandLineArgs::specify_command_line_flag
   ("--one_plus_four_with_two_coarse");
  CommandLineArgs::specify_command_line_flag
   ("--use_validation_distribution");
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  // Create the problem with 2D nine-node elements from the
  // QMultiPoissonElement family.
  MultiPoissonProblem<QMultiPoissonElement<2,3,N_FIELD> > problem;
  // Create label for output
  DocInfo doc_info;
  // Set output directory
  doc_info.set_directory("RESLT");
  // Step number
  doc_info.number()=0;
  cout << "\n\nSolving for TanhSolnForMultiPoisson::Alpha="
       << TanhSolnForMultiPoisson::Alpha << std::endl << std::endl;
 #ifdef OOMPH_HAS_MPI
  if (CommandLineArgs::command_line_flag_has_been_set(
       "--use_validation_distribution"))
   {
    // Create storage for pre-determined partitioning
    const unsigned n_element=problem.mesh_pt()->nelement();
    Vector<unsigned> element_partition(n_element);
    // Read in partitioning from disk
    std::ifstream input_file;
    char filename[100];
    sprintf(filename,"multi_poisson_partition.dat");
    input_file.open(filename);
    std::string input_string;
    for (unsigned e=0;e<n_element;e++)
     {
      getline(input_file,input_string,'\n');
      element_partition[e]=atoi(input_string.c_str());
     }
    // Now perform the distribution and document it
    bool report_stats=true;
    problem.distribute(element_partition,report_stats);
   }
  // Create new partition.
  else
   {
    // Provide storage for each element's partition number
    const unsigned n_element=problem.mesh_pt()->nelement();
    Vector<unsigned> out_element_partition(n_element);
    // Distribute the problem
    bool report_stats=true;
    out_element_partition=problem.distribute(report_stats);
    // Write partition to disk
    std::ofstream output_file;
    char filename[100];
    sprintf(filename,"out_multi_poisson_partition.dat");
    output_file.open(filename);
    for (unsigned e=0;e<n_element;e++)
     {
      output_file << out_element_partition[e] << std::endl;
     }
   }
 #endif
  // Solve the problem
  problem.newton_solve();
  //Output the solution
  problem.doc_solution(doc_info);
 // Finalise MPI
 #ifdef OOMPH_HAS_MPI
  MPI_Helpers::finalize();
 #endif
 } //end of main
References TanhSolnForMultiPoisson::Alpha, oomph::CommandLineArgs::command_line_flag_has_been_set(), oomph::CommandLineArgs::doc_specified_flags(), e(), MergeRestartFiles::filename, oomph::DocInfo::number(), oomph::CommandLineArgs::parse_and_assign(), problem, oomph::DocInfo::set_directory(), Flag_definition::setup(), oomph::CommandLineArgs::specify_command_line_flag(), and oomph::Global_string_for_annotation::string().