MercuryDPM: Eigen::internal::IndexedViewHelper< Indices, EnableIf > Struct Template Reference
Eigen::internal::IndexedViewHelper< Indices, EnableIf > Struct Template Reference
#include <IndexedViewHelper.h>
Static Public Member Functions
static constexpr Index first (const Indices &indices)
static constexpr Index size (const Indices &indices)
static constexpr Index incr (const Indices &)
Static Public Attributes
static constexpr Index FirstAtCompileTime = Undefined
static constexpr Index SizeAtCompileTime = array_size<Indices>::value
static constexpr Index IncrAtCompileTime = Undefined
Member Function Documentation
first()
template<typename Indices , typename EnableIf = void> static constexpr Index Eigen::internal::IndexedViewHelper< Indices, EnableIf >::first (const Indices & indices) inline static constexpr
 { return static_cast<Index>(indices[0]); }
incr()
template<typename Indices , typename EnableIf = void> static constexpr Index Eigen::internal::IndexedViewHelper< Indices, EnableIf >::incr (const Indices &) inline static constexpr
 { return Undefined; }
References Eigen::Undefined.
Referenced by Eigen::internal::IndexedViewImpl< XprType, RowIndices, ColIndices, StorageKind, true >::colIncrement(), and Eigen::internal::IndexedViewImpl< XprType, RowIndices, ColIndices, StorageKind, true >::rowIncrement().
size()
template<typename Indices , typename EnableIf = void> static constexpr Index Eigen::internal::IndexedViewHelper< Indices, EnableIf >::size (const Indices & indices) inline static constexpr
 { return index_list_size(indices); }
References Eigen::internal::index_list_size().
Referenced by Eigen::internal::IndexedViewImpl< XprType, RowIndices, ColIndices, StorageKind, DirectAccess >::cols(), and Eigen::internal::IndexedViewImpl< XprType, RowIndices, ColIndices, StorageKind, DirectAccess >::rows().
Member Data Documentation
FirstAtCompileTime
template<typename Indices , typename EnableIf = void> constexpr Index Eigen::internal::IndexedViewHelper< Indices, EnableIf >::FirstAtCompileTime = Undefined static constexpr
IncrAtCompileTime
template<typename Indices , typename EnableIf = void> constexpr Index Eigen::internal::IndexedViewHelper< Indices, EnableIf >::IncrAtCompileTime = Undefined static constexpr
Referenced by Eigen::internal::IndexedViewHelper< SingleRange< ValueAtCompileTime >, void >::incr().
SizeAtCompileTime
template<typename Indices , typename EnableIf = void> constexpr Index Eigen::internal::IndexedViewHelper< Indices, EnableIf >::SizeAtCompileTime = array_size<Indices>::value static constexpr
Referenced by Eigen::internal::IndexedViewHelper< SingleRange< ValueAtCompileTime >, void >::size().
The documentation for this struct was generated from the following file:
IndexedViewHelper.h