MercuryDPM: oomph::VectorMatrix< VALUE_TYPE > Class Template Reference
oomph::VectorMatrix< VALUE_TYPE > Class Template Reference
#include <vector_matrix.h>
Public Member Functions
VectorMatrix ()
Default constructor - constructs an empty matrix.
VectorMatrix (const unsigned &n, const unsigned &m, const VALUE_TYPE &val)
Constructor - constructs an n by m matrix with value val.
VectorMatrix (const unsigned &n, const unsigned &m)
virtual ~VectorMatrix ()
Default virtual destructor.
const unsigned nrow () const
returns the number of rows. This is the outer Vector size.
const unsigned ncol () const
Vector< VALUE_TYPE > & operator[] (const size_t i)
[] access function to the i-th inner vector.
const Vector< VALUE_TYPE > & operator[] (const size_t i) const
[] access function to the i-th inner vector const version
void clear ()
void resize (const size_t &n, const size_t &m, VALUE_TYPE val=VALUE_TYPE())
void assign (const size_t &n, const size_t &m, const VALUE_TYPE &val)
Protected Member Functions
void build_vectors (const unsigned &n, const unsigned &m)
Builds an n by m VectorMatrix with default VALUE_TYPE.
void build_vectors_and_value (const unsigned &n, const unsigned &m, const VALUE_TYPE &val)
Build an m by n VectorMatrix with VALUE_TYPE val.
Protected Attributes
Vector< Vector< VALUE_TYPE > > Vector_matrix
Detailed Description
template<class VALUE_TYPE>
class oomph::VectorMatrix< VALUE_TYPE >
VectorMatrix is a generalised, STL-map-based, matrix based on a Vector of Vectors.
Example of usage:
     // Assume we have a Vector of pointers to objects:
     VectorMatrix<int> vector_matrix(4,5,-1);
     // This is a 4 by 5 matrix with all entries set to -1.
     std::cout << vector_matrix[3][3] << " "
//             << vector_matrix.nrow() << " "
//             << vector_matrix.col() << std::endl;
     // Output:
     // -1 4 5
     vector_matrix[3][3] = 42;
     std::cout << vector_matrix[3][3] << " "
               << vector_matrix.nrow() << " "
               << vector_matrix.col() << std::endl;
     // Output:
     // 42 4 5
Constructor & Destructor Documentation
VectorMatrix() [1/3]
template<class VALUE_TYPE > oomph::VectorMatrix< VALUE_TYPE >::VectorMatrix () inline
Default constructor - constructs an empty matrix.
     {
       Vector_matrix.resize(0);
     }
References oomph::VectorMatrix< VALUE_TYPE >::Vector_matrix.
VectorMatrix() [2/3]
template<class VALUE_TYPE > oomph::VectorMatrix< VALUE_TYPE >::VectorMatrix (const unsigned & n, const unsigned & m, const VALUE_TYPE & val) inline
Constructor - constructs an n by m matrix with value val.
     {
       this->build_vectors_and_value(n, m, val);
     }
References oomph::VectorMatrix< VALUE_TYPE >::build_vectors_and_value(), m, and calibrate::val.
VectorMatrix() [3/3]
template<class VALUE_TYPE > oomph::VectorMatrix< VALUE_TYPE >::VectorMatrix (const unsigned & n, const unsigned & m) inline
Constructor - constructs an n by m matrix, the value is defined by the default initialisation of VALUE_TYPE.
     {
       this->build_vectors(n, m);
     }
References oomph::VectorMatrix< VALUE_TYPE >::build_vectors(), and m.
~VectorMatrix()
template<class VALUE_TYPE > virtual oomph::VectorMatrix< VALUE_TYPE >::~VectorMatrix () inline virtual
Default virtual destructor.
     {
       this->clear();
     }
References oomph::VectorMatrix< VALUE_TYPE >::clear().
Member Function Documentation
assign()
template<class VALUE_TYPE > void oomph::VectorMatrix< VALUE_TYPE >::assign (const size_t & n, const size_t & m, const VALUE_TYPE & val) inline
Any elements held in the container before the call are destroyed and replaced by newly constructed elements (no assignments of elements take place). This causes an automatic reallocation of the allocated storage space if -and only if- the new vector size surpasses the current vector capacity. This invokes std::assign on both the outer vector and the inner vectors.
     {
       Vector_matrix.assign(n, Vector<VALUE_TYPE>(m, val));
     }
References m, n, calibrate::val, and oomph::VectorMatrix< VALUE_TYPE >::Vector_matrix.
Referenced by main().
build_vectors()
template<class VALUE_TYPE > void oomph::VectorMatrix< VALUE_TYPE >::build_vectors (const unsigned & n, const unsigned & m) inline protected
Builds an n by m VectorMatrix with default VALUE_TYPE.
     {
       Vector_matrix.resize(n, Vector<VALUE_TYPE>(m));
     }
References m, n, and oomph::VectorMatrix< VALUE_TYPE >::Vector_matrix.
Referenced by oomph::VectorMatrix< VALUE_TYPE >::VectorMatrix().
build_vectors_and_value()
template<class VALUE_TYPE > void oomph::VectorMatrix< VALUE_TYPE >::build_vectors_and_value (const unsigned & n, const unsigned & m, const VALUE_TYPE & val) inline protected
Build an m by n VectorMatrix with VALUE_TYPE val.
     {
       Vector_matrix.resize(n, Vector<VALUE_TYPE>(m, val));
     }
References m, n, calibrate::val, and oomph::VectorMatrix< VALUE_TYPE >::Vector_matrix.
Referenced by oomph::VectorMatrix< VALUE_TYPE >::VectorMatrix().
clear()
template<class VALUE_TYPE > void oomph::VectorMatrix< VALUE_TYPE >::clear () inline
Clears the outer vector. Calling Vector::clear() will invoke the destructor of all the inner Vectors.
     {
       Vector_matrix.clear();
     }
References oomph::VectorMatrix< VALUE_TYPE >::Vector_matrix.
Referenced by main(), and oomph::VectorMatrix< VALUE_TYPE >::~VectorMatrix().
ncol()
template<class VALUE_TYPE > const unsigned oomph::VectorMatrix< VALUE_TYPE >::ncol () const inline
return the number of columns. This is the size of the first inner vectors, or returns 0 if the outer vector is of size 0 (this->nrow() is 0).
     {
 #ifdef PARANOID
       // Inner vector size consistency check: All inner vectors must be the same
       // size.
       const unsigned para_nrow = this->nrow();
       if (para_nrow > 0)
       {
         // There is at least one inner vector
         unsigned inner_vector0_size = Vector_matrix[0].size();
         for (unsigned row_i = 0; row_i < para_nrow; row_i++)
         {
           unsigned current_inner_vector_size = Vector_matrix[row_i].size();
           if (current_inner_vector_size != inner_vector0_size)
           {
             std::ostringstream err_msg;
             err_msg << "The size of the inner vectors are not consistent.\n"
                     << "Vector_matrix[0].size() is " << inner_vector0_size
                     << "\n"
                     << "Vector_matrix[" << row_i << "] is "
                     << current_inner_vector_size << "\n";
             throw OomphLibError(
               err_msg.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
           }
         }
       }
 #endif
       if (this->nrow() == 0)
       {
         return 0;
       }
       else
       {
         return Vector_matrix[0].size();
       }
     }
References oomph::VectorMatrix< VALUE_TYPE >::nrow(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::VectorMatrix< VALUE_TYPE >::Vector_matrix.
Referenced by oomph::BlockPreconditioner< MATRIX >::get_concatenated_block(), and main().
nrow()
template<class VALUE_TYPE > const unsigned oomph::VectorMatrix< VALUE_TYPE >::nrow () const inline
returns the number of rows. This is the outer Vector size.
     {
 #ifdef PARANOID
       // Inner vector size consistency check: All inner vectors must be the same
       // size. Although the size of the inner vectors are not directly used to
       // calculate the nrow(), we perform this check here in case the user has
       // done something dodgy.
       const unsigned para_nrow = Vector_matrix.size();
       if (para_nrow > 0)
       {
         // There is at least one inner vector
         unsigned inner_vector0_size = Vector_matrix[0].size();
         for (unsigned row_i = 0; row_i < para_nrow; row_i++)
         {
           unsigned current_inner_vector_size = Vector_matrix[row_i].size();
           if (current_inner_vector_size != inner_vector0_size)
           {
             std::ostringstream err_msg;
             err_msg << "The size of the inner vectors are not consistent.\n"
                     << "Vector_matrix[0].size() is " << inner_vector0_size
                     << "\n"
                     << "Vector_matrix[" << row_i << "] is "
                     << current_inner_vector_size << "\n";
             throw OomphLibError(
               err_msg.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
           }
         }
       }
 #endif
       return Vector_matrix.size();
     }
References OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::VectorMatrix< VALUE_TYPE >::Vector_matrix.
Referenced by oomph::BlockPreconditioner< MATRIX >::get_concatenated_block(), main(), and oomph::VectorMatrix< VALUE_TYPE >::ncol().
operator[]() [1/2]
template<class VALUE_TYPE > Vector<VALUE_TYPE>& oomph::VectorMatrix< VALUE_TYPE >::operator[] (const size_t i) inline
[] access function to the i-th inner vector.
     {
       return Vector_matrix[i];
     }
References i, and oomph::VectorMatrix< VALUE_TYPE >::Vector_matrix.
operator[]() [2/2]
template<class VALUE_TYPE > const Vector<VALUE_TYPE>& oomph::VectorMatrix< VALUE_TYPE >::operator[] (const size_t i) const inline
[] access function to the i-th inner vector const version
     {
       return Vector_matrix[i];
     }
References i, and oomph::VectorMatrix< VALUE_TYPE >::Vector_matrix.
resize()
template<class VALUE_TYPE > void oomph::VectorMatrix< VALUE_TYPE >::resize (const size_t & n, const size_t & m, VALUE_TYPE val = VALUE_TYPE()) inline
Resize the existing VectorMatrix. WARNING: This invokes the resize function in std::vector, as such, only new values are assigned, old values as kept. e.g. if vec = [2,2,2], then vec.resize(5,3) gives vec = [2, 2, 2, 3, 3].
     {
       Vector_matrix.resize(n);
       for (unsigned i = 0; i < n; i++)
       {
         Vector_matrix[i].resize(m, val);
       }
     }
References i, m, n, calibrate::val, and oomph::VectorMatrix< VALUE_TYPE >::Vector_matrix.
Referenced by main().
Member Data Documentation
Vector_matrix
template<class VALUE_TYPE > Vector<Vector<VALUE_TYPE> > oomph::VectorMatrix< VALUE_TYPE >::Vector_matrix protected
Here's the generalised matrix structure: A Vector of Vector to templated by VALUE_TYPE.
Referenced by oomph::VectorMatrix< VALUE_TYPE >::assign(), oomph::VectorMatrix< VALUE_TYPE >::build_vectors(), oomph::VectorMatrix< VALUE_TYPE >::build_vectors_and_value(), oomph::VectorMatrix< VALUE_TYPE >::clear(), oomph::VectorMatrix< VALUE_TYPE >::ncol(), oomph::VectorMatrix< VALUE_TYPE >::nrow(), oomph::VectorMatrix< VALUE_TYPE >::operator[](), oomph::VectorMatrix< VALUE_TYPE >::resize(), and oomph::VectorMatrix< VALUE_TYPE >::VectorMatrix().
The documentation for this class was generated from the following file:
vector_matrix.h