MercuryDPM: oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT > Class Template Reference
oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT > Class Template Reference
#include <pml_helmholtz_time_harmonic_linear_elasticity_interaction.h>
Public Member Functions
TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement (FiniteElement *const &element_pt, const int &face_index)
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Return the residuals.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Fill in contribution from Jacobian.
const double & q () const
double *& q_pt ()
void output (std::ostream &outfile)
Output function.
void output (std::ostream &outfile, const unsigned &n_plot)
void output (FILE *file_pt)
C_style output function.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function.
std::complex< double > global_flux_contribution_from_solid ()
std::complex< double > global_flux_contribution_from_solid (std::ofstream &outfile)
std::complex< double > global_flux_contribution_from_helmholtz ()
std::complex< double > global_flux_contribution_from_helmholtz (std::ofstream &outfile)
Public Member Functions inherited from oomph::FaceElement
FaceElement ()
Constructor: Initialise all appropriate member data.
virtual ~FaceElement ()
Empty virtual destructor.
FaceElement (const FaceElement &)=delete
Broken copy constructor.
const unsigned & boundary_number_in_bulk_mesh () const
Broken assignment operator.
void set_boundary_number_in_bulk_mesh (const unsigned &b)
Set function for the boundary number in bulk mesh.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
double J_eulerian (const Vector< double > &s) const
double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
double interpolated_x (const Vector< double > &s, const unsigned &i) const
double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
void interpolated_x (const Vector< double > &s, Vector< double > &x) const
void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
int & normal_sign ()
int normal_sign () const
int & face_index ()
int face_index () const
const Vector< double > * tangent_direction_pt () const
Public access function for the tangent direction pointer.
void set_tangent_direction (Vector< double > *tangent_direction_pt)
Set the tangent direction vector.
void turn_on_warning_for_discontinuous_tangent ()
void turn_off_warning_for_discontinuous_tangent ()
void continuous_tangent_and_outer_unit_normal (const Vector< double > &s, Vector< Vector< double >> &tang_vec, Vector< double > &unit_normal) const
void continuous_tangent_and_outer_unit_normal (const unsigned &ipt, Vector< Vector< double >> &tang_vec, Vector< double > &unit_normal) const
void outer_unit_normal (const Vector< double > &s, Vector< double > &unit_normal) const
Compute outer unit normal at the specified local coordinate.
void outer_unit_normal (const unsigned &ipt, Vector< double > &unit_normal) const
Compute outer unit normal at ipt-th integration point.
FiniteElement *& bulk_element_pt ()
Pointer to higher-dimensional "bulk" element.
FiniteElement * bulk_element_pt () const
Pointer to higher-dimensional "bulk" element (const version)
CoordinateMappingFctPt & face_to_bulk_coordinate_fct_pt ()
CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt () const
BulkCoordinateDerivativesFctPt & bulk_coordinate_derivatives_fct_pt ()
BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt () const
Vector< double > local_coordinate_in_bulk (const Vector< double > &s) const
void get_local_coordinate_in_bulk (const Vector< double > &s, Vector< double > &s_bulk) const
void get_ds_bulk_ds_face (const Vector< double > &s, DenseMatrix< double > &dsbulk_dsface, unsigned &interior_direction) const
unsigned & bulk_position_type (const unsigned &i)
const unsigned & bulk_position_type (const unsigned &i) const
void bulk_node_number_resize (const unsigned &i)
Resize the storage for the bulk node numbers.
unsigned & bulk_node_number (const unsigned &n)
const unsigned & bulk_node_number (const unsigned &n) const
void bulk_position_type_resize (const unsigned &i)
Resize the storage for bulk_position_type to i entries.
unsigned & nbulk_value (const unsigned &n)
unsigned nbulk_value (const unsigned &n) const
void nbulk_value_resize (const unsigned &i)
void resize_nodes (Vector< unsigned > &nadditional_data_values)
void output_zeta (std::ostream &outfile, const unsigned &nplot)
Output boundary coordinate zeta.
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
virtual void disable_ALE ()
virtual void enable_ALE ()
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual unsigned nvertex_node () const
virtual Node * vertex_node_pt (const unsigned &j) const
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output an exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output a time-dependent exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::ElementWithExternalElement
ElementWithExternalElement ()
virtual ~ElementWithExternalElement ()
The destructor, clean up any allocated memory.
ElementWithExternalElement (const ElementWithExternalElement &)=delete
Broken copy constructor.
void operator= (const ElementWithExternalElement &)=delete
Broken assignment operator.
bool storage_has_been_allocated () const
Helper function to check if storage has actually been allocated.
FiniteElement *& external_element_pt (const unsigned &interaction_index, const unsigned &ipt)
FiniteElement *const & external_element_pt (const unsigned &interaction_index, const unsigned &ipt) const
Access function to source element, const version.
Vector< double > & external_element_local_coord (const unsigned &interaction_index, const unsigned &ipt)
Vector< double > const & external_element_local_coord (const unsigned &interaction_index, const unsigned &ipt) const
Access function to get source element's coords, const version.
void output_external_elements (std::ostream &outfile, const unsigned &interaction_index)
void initialise_external_element_storage ()
void flush_all_external_element_storage ()
Flush the storage for external elements.
void set_ninteraction (const unsigned &n_interaction)
unsigned ninteraction () const
Return the number of interactions in the element.
virtual void identify_all_field_data_for_external_interaction (Vector< std::set< FiniteElement * >> const &external_elements_pt, std::set< std::pair< Data *, unsigned >> &paired_interaction_data)
virtual void identify_all_geometric_data_for_external_interaction (Vector< std::set< FiniteElement * >> const &external_elements_pt, std::set< Data * > &external_geometric_data_pt)
unsigned nexternal_interaction_field_data () const
Vector< Data * > external_interaction_field_data_pt () const
unsigned nexternal_interaction_geometric_data () const
bool add_external_geometric_data ()
Are we including external geometric data in the element's Jacobian.
bool add_external_interaction_data ()
Are we including external data in the element's Jacobian.
Vector< Data * > external_interaction_geometric_data_pt () const
void ignore_external_geometric_data ()
void ignore_external_interaction_data ()
void include_external_geometric_data ()
void include_external_interaction_data ()
bool external_geometric_data_is_included () const
void describe_local_dofs (std::ostream &out, const std::string &curr_string) const
Protected Member Functions
void fill_in_contribution_to_residuals_helmholtz_traction (Vector< double > &residuals)
Helper function that actually calculates the residuals.
Protected Member Functions inherited from oomph::FaceElement
void add_additional_values (const Vector< unsigned > &nadditional_values, const unsigned &id)
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Member Functions inherited from oomph::ElementWithExternalElement
void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
void assign_external_interaction_data_local_eqn_numbers (const bool &store_local_dof_pt)
void fill_in_jacobian_from_external_interaction_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_external_interaction_by_fd (DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_external_interaction_field_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_external_interaction_field_by_fd (DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_external_interaction_geometric_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_external_interaction_geometric_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_external_interaction_field_fd ()
virtual void reset_after_external_interaction_field_fd ()
virtual void update_in_external_interaction_field_fd (const unsigned &i)
virtual void reset_in_external_interaction_field_fd (const unsigned &i)
virtual void update_before_external_interaction_geometric_fd ()
virtual void reset_after_external_interaction_geometric_fd ()
virtual void update_in_external_interaction_geometric_fd (const unsigned &i)
virtual void reset_in_external_interaction_geometric_fd (const unsigned &i)
Protected Attributes
double * Q_pt
Vector< std::complex< unsigned > > U_index_time_harmonic_linear_elasticity_helmholtz_traction
Index at which the i-th displacement component is stored.
Protected Attributes inherited from oomph::FaceElement
unsigned Boundary_number_in_bulk_mesh
The boundary number in the bulk mesh to which this element is attached.
FiniteElement * Bulk_element_pt
Pointer to the associated higher-dimensional "bulk" element.
Vector< unsigned > Bulk_node_number
Vector< unsigned > Nbulk_value
Vector< double > * Tangent_direction_pt
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Protected Attributes inherited from oomph::ElementWithExternalElement
bool Add_external_interaction_data
Boolean flag to indicate whether to include the external data.
bool Add_external_geometric_data
Boolean flag to indicate whether to include the external geometric data.
Data ** External_interaction_field_data_pt
Data ** External_interaction_geometric_data_pt
Static Protected Attributes
static double Default_Q_Value = 1.0
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Additional Inherited Members
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Detailed Description
template<class ELASTICITY_BULK_ELEMENT, class HELMHOLTZ_BULK_ELEMENT>
class oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >
A class for elements that allow the imposition of an applied traction in the equations of time-harmonic linear elasticity from a PMLHelmholtz potential (interpreted as a displacement potential for the fluid in a quasi-steady, linearised FSI problem.) The geometrical information can be read from the FaceGeometry<ELEMENT> class and thus, we can be generic enough without the need to have a separate equations class.
Constructor & Destructor Documentation
TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement()
template<class ELASTICITY_BULK_ELEMENT , class HELMHOLTZ_BULK_ELEMENT > oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement (FiniteElement *const & element_pt, const int & face_index) inline
Constructor, which takes a "bulk" element and the value of the index and its limit
       : FaceGeometry<ELASTICITY_BULK_ELEMENT>(),
         FaceElement(),
         Q_pt(&Default_Q_Value)
     {
       // Attach the geometrical information to the element. N.B. This function
       // also assigns nbulk_value from the required_nvalue of the bulk element
       element_pt->build_face_element(face_index, this);
 #ifdef PARANOID
       {
         // Check that the element is not a refineable 3d element
         ELASTICITY_BULK_ELEMENT* elem_pt =
           dynamic_cast<ELASTICITY_BULK_ELEMENT*>(element_pt);
         // If it's three-d
         if (elem_pt->dim() == 3)
         {
           // Is it refineable
           RefineableElement* ref_el_pt =
             dynamic_cast<RefineableElement*>(elem_pt);
           if (ref_el_pt != 0)
           {
             if (this->has_hanging_nodes())
             {
               throw OomphLibError("This flux element will not work correctly "
                                   "if nodes are hanging\n",
                                   OOMPH_CURRENT_FUNCTION,
                                   OOMPH_EXCEPTION_LOCATION);
             }
           }
         }
       }
 #endif
       // Set source element storage: one interaction with an external
       // element -- the PMLHelmholtz bulk element that provides
       // the pressure
       this->set_ninteraction(1);
       // Find the dimension of the problem
       unsigned n_dim = element_pt->nodal_dimension();
       // Find the index at which the displacement unknowns are stored
       ELASTICITY_BULK_ELEMENT* cast_element_pt =
         dynamic_cast<ELASTICITY_BULK_ELEMENT*>(element_pt);
       this->U_index_time_harmonic_linear_elasticity_helmholtz_traction.resize(
         n_dim);
       for (unsigned i = 0; i < n_dim; i++)
       {
         this->U_index_time_harmonic_linear_elasticity_helmholtz_traction[i] =
           cast_element_pt->u_index_time_harmonic_linear_elasticity(i);
       }
     }
References oomph::FiniteElement::build_face_element(), oomph::FaceElement::face_index(), oomph::FiniteElement::has_hanging_nodes(), i, oomph::FiniteElement::nodal_dimension(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::ElementWithExternalElement::set_ninteraction(), and oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::U_index_time_harmonic_linear_elasticity_helmholtz_traction.
Member Function Documentation
fill_in_contribution_to_jacobian()
template<class ELASTICITY_BULK_ELEMENT , class HELMHOLTZ_BULK_ELEMENT > void oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline virtual
Fill in contribution from Jacobian.
Reimplemented from oomph::ElementWithExternalElement.
     {
       // Call the residuals
       fill_in_contribution_to_residuals_helmholtz_traction(residuals);
       // Derivatives w.r.t. external data
       fill_in_jacobian_from_external_interaction_by_fd(residuals, jacobian);
     }
References oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::fill_in_contribution_to_residuals_helmholtz_traction(), and oomph::ElementWithExternalElement::fill_in_jacobian_from_external_interaction_by_fd().
fill_in_contribution_to_residuals()
template<class ELASTICITY_BULK_ELEMENT , class HELMHOLTZ_BULK_ELEMENT > void oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) inline virtual
Return the residuals.
Reimplemented from oomph::GeneralisedElement.
     {
       fill_in_contribution_to_residuals_helmholtz_traction(residuals);
     }
References oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::fill_in_contribution_to_residuals_helmholtz_traction().
fill_in_contribution_to_residuals_helmholtz_traction()
template<class ELASTICITY_BULK_ELEMENT , class HELMHOLTZ_BULK_ELEMENT > void oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::fill_in_contribution_to_residuals_helmholtz_traction (Vector< double > & residuals) protected
Helper function that actually calculates the residuals.
Return the residuals.
   {
     // Find out how many nodes there are
     unsigned n_node = nnode();
 #ifdef PARANOID
     // Find out how many positional dofs there are
     unsigned n_position_type = this->nnodal_position_type();
     if (n_position_type != 1)
     {
       throw OomphLibError("LinearElasticity is not yet implemented for more "
                           "than one position type.",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Find out the dimension of the node
     const unsigned n_dim = this->nodal_dimension();
     // Cache the nodal indices at which the displacement components are stored
     std::complex<unsigned> u_nodal_index[n_dim];
     for (unsigned i = 0; i < n_dim; i++)
     {
       u_nodal_index[i] =
         this->U_index_time_harmonic_linear_elasticity_helmholtz_traction[i];
     }
     // Integer to hold the local equation number
     int local_eqn = 0;
     // Set up memory for the shape functions
     Shape psi(n_node);
     DShape dpsids(n_node, n_dim - 1);
     // Get FSI parameter
     const double q_value = q();
     // Storage for traction
     Vector<std::complex<double>> traction(2);
     // Set the value of n_intpt
     unsigned n_intpt = integral_pt()->nweight();
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Only need to call the local derivatives
       dshape_local_at_knot(ipt, psi, dpsids);
       // Calculate the coordinates
       Vector<double> interpolated_x(n_dim, 0.0);
       // Also calculate the surface tangent vectors
       DenseMatrix<double> interpolated_A(n_dim - 1, n_dim, 0.0);
       // Calculate displacements and derivatives
       for (unsigned l = 0; l < n_node; l++)
       {
         // Loop over directions
         for (unsigned i = 0; i < n_dim; i++)
         {
           // Calculate the Eulerian coords
           const double x_local = nodal_position(l, i);
           interpolated_x[i] += x_local * psi(l);
           // Loop over LOCAL derivative directions, to calculate the tangent(s)
           for (unsigned j = 0; j < n_dim - 1; j++)
           {
             interpolated_A(j, i) += x_local * dpsids(l, j);
           }
         }
       }
       // Now find the local metric tensor from the tangent Vectors
       DenseMatrix<double> A(n_dim - 1);
       for (unsigned i = 0; i < n_dim - 1; i++)
       {
         for (unsigned j = 0; j < n_dim - 1; j++)
         {
           // Initialise surface metric tensor to zero
           A(i, j) = 0.0;
           // Take the dot product
           for (unsigned k = 0; k < n_dim; k++)
           {
             A(i, j) += interpolated_A(i, k) * interpolated_A(j, k);
           }
         }
       }
       // Get the outer unit normal
       Vector<double> interpolated_normal(n_dim);
       outer_unit_normal(ipt, interpolated_normal);
       // Find the determinant of the metric tensor
       double Adet = 0.0;
       switch (n_dim)
       {
         case 2:
           Adet = A(0, 0);
           break;
         case 3:
           Adet = A(0, 0) * A(1, 1) - A(0, 1) * A(1, 0);
           break;
         default:
           throw OomphLibError(
             "Wrong dimension in TimeHarmonicLinElastLoadedByPressureElement",
             OOMPH_CURRENT_FUNCTION,
             OOMPH_EXCEPTION_LOCATION);
       }
       // Premultiply the weights and the square-root of the determinant of
       // the metric tensor
       double W = w * sqrt(Adet);
       // Get bulk element for potential
       HELMHOLTZ_BULK_ELEMENT* ext_el_pt =
         dynamic_cast<HELMHOLTZ_BULK_ELEMENT*>(external_element_pt(0, ipt));
       Vector<double> s_ext(external_element_local_coord(0, ipt));
       // Traction: Pressure is proportional to POSITIVE potential
       std::complex<double> u_helmholtz =
         ext_el_pt->interpolated_u_pml_helmholtz(s_ext);
       traction[0] = -q_value * interpolated_normal[0] * u_helmholtz;
       traction[1] = -q_value * interpolated_normal[1] * u_helmholtz;
       // Loop over the test functions, nodes of the element
       for (unsigned l = 0; l < n_node; l++)
       {
         // Loop over the displacement components
         for (unsigned i = 0; i < n_dim; i++)
         {
           local_eqn = this->nodal_local_eqn(l, u_nodal_index[i].real());
           /*IF it's not a boundary condition*/
           if (local_eqn >= 0)
           {
             // Add the loading terms to the residuals
             residuals[local_eqn] -= traction[i].real() * psi(l) * W;
           }
           local_eqn = this->nodal_local_eqn(l, u_nodal_index[i].imag());
           /*IF it's not a boundary condition*/
           if (local_eqn >= 0)
           {
             // Add the loading terms to the residuals
             residuals[local_eqn] -= traction[i].imag() * psi(l) * W;
           }
         } // End of if not boundary condition
       } // End of loop over shape functions
     } // End of loop over integration points
   }
References i, imag(), j, k, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, Eigen::numext::q, sqrt(), w, and oomph::QuadTreeNames::W.
Referenced by oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::fill_in_contribution_to_jacobian(), and oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::fill_in_contribution_to_residuals().
global_flux_contribution_from_helmholtz() [1/2]
template<class ELASTICITY_BULK_ELEMENT , class HELMHOLTZ_BULK_ELEMENT > std::complex<double> oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::global_flux_contribution_from_helmholtz () inline
Compute the global_flux_contribution through the helmholtz elements : we compute dphidn.n
     {
       // Dummy output file
       std::ofstream outfile;
       return global_flux_contribution_from_helmholtz(outfile);
     }
global_flux_contribution_from_helmholtz() [2/2]
template<class ELASTICITY_BULK_ELEMENT , class HELMHOLTZ_BULK_ELEMENT > std::complex<double> oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::global_flux_contribution_from_helmholtz (std::ofstream & outfile) inline
Compute the element's contribution to the integral of the flux over the artificial boundary. Also output the flux in the specified output file if it's open.
     {
       // Get the dim of this element
       const unsigned local_dim = this->dim();
       // Set the value of n_intpt
       const unsigned n_intpt = integral_pt()->nweight();
       // Set the Vector to hold local coordinates
       Vector<double> s(local_dim);
       std::complex<double> flux(0.0, 0.0);
       // Output?
       if (outfile.is_open())
       {
         outfile << "ZONE\n";
       }
       // Loop over the integration points
       //--------------------------------
       for (unsigned ipt = 0; ipt < n_intpt; ipt++)
       {
         // Assign values of s
         for (unsigned i = 0; i < local_dim; i++)
         {
           s[i] = integral_pt()->knot(ipt, i);
         }
         // Get local coordinates in bulk element by copy construction
         Vector<double> s_bulk(local_coordinate_in_bulk(s));
         // Get external element for potential
         HELMHOLTZ_BULK_ELEMENT* ext_el_pt =
           dynamic_cast<HELMHOLTZ_BULK_ELEMENT*>(external_element_pt(0, ipt));
         // number of nodes in ext element
         unsigned nnode_ext = ext_el_pt->nnode();
         // get the dim of the external nodes
         const unsigned ext_dim = ext_el_pt->dim();
         // Set up memory for the external shape function
         Shape psi_ext(nnode_ext);
         DShape dpsi_ext_dx(nnode_ext, ext_dim);
         // Call the derivatives of the shape  functions
         // in the external element -- must do this via s because this point
         // is not an integration point the bulk element!
         (void)ext_el_pt->dshape_eulerian(s_bulk, psi_ext, dpsi_ext_dx);
         // Set up memory for the outer unit normal
         Vector<double> unit_normal(ext_dim);
         // get the outer_unit_ext vector
         this->outer_unit_normal(s, unit_normal);
         // Get the integral weight
         double w = integral_pt()->weight(ipt);
         // Get jacobian of mapping
         double J = J_eulerian(s);
         // Premultiply the weights and the Jacobian
         double W = w * J;
         // Global gradient
         Vector<std::complex<double>> interpolated_dphidx(
           ext_dim, std::complex<double>(0.0, 0.0));
         for (unsigned l = 0; l < nnode_ext; l++)
         {
           // Get the nodal value of the helmholtz unknown
           const std::complex<double> phi_value(
             ext_el_pt->nodal_value(l, ext_el_pt->u_index_helmholtz().real()),
             ext_el_pt->nodal_value(l, ext_el_pt->u_index_helmholtz().imag()));
           // Loop over directions
           for (unsigned i = 0; i < ext_dim; i++)
           {
             interpolated_dphidx[i] += phi_value * dpsi_ext_dx(l, i);
           }
         }
         // define dphi_dn
         std::complex<double> dphi_dn(0.0, 0.0);
         for (unsigned i = 0; i < ext_dim; i++)
         {
           dphi_dn += interpolated_dphidx[i] * unit_normal[i];
         }
 #ifdef PARANOID
         double max_permitted_discrepancy = 1.0e-10;
         double diff = sqrt(
           pow(ext_el_pt->interpolated_x(s_bulk, 0) - interpolated_x(s, 0), 2) +
           pow(ext_el_pt->interpolated_x(s_bulk, 1) - interpolated_x(s, 1), 2));
         if (diff > max_permitted_discrepancy)
         {
           std::ostringstream error_stream;
           error_stream
             << "Position computed by external el and face element differ by "
             << diff << " which is more than the acceptable tolerance "
             << max_permitted_discrepancy << std::endl;
           throw OomphLibError(error_stream.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
 #endif
         // Output?
         if (outfile.is_open())
         {
           Vector<double> x(ext_dim);
           interpolated_x(s, x);
           outfile << x[0] << " " << x[1] << " " << dphi_dn.real() << " "
                   << dphi_dn.imag() << " "
                   << "\n";
         }
         // ...add to integral
         flux += dphi_dn * W;
       }
       return flux;
     }
References oomph::FiniteElement::dim(), oomph::ElementWithExternalElement::external_element_pt(), ProblemParameters::flux(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), J, oomph::FaceElement::J_eulerian(), oomph::Integral::knot(), oomph::FaceElement::local_coordinate_in_bulk(), oomph::Integral::nweight(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::FaceElement::outer_unit_normal(), Eigen::bfloat16_impl::pow(), s, sqrt(), w, oomph::QuadTreeNames::W, oomph::Integral::weight(), and plotDoE::x.
global_flux_contribution_from_solid() [1/2]
template<class ELASTICITY_BULK_ELEMENT , class HELMHOLTZ_BULK_ELEMENT > std::complex<double> oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::global_flux_contribution_from_solid () inline
Compute the global_flux_contribution through the template elasticity elements : we compute u.n
     {
       // Dummy output file
       std::ofstream outfile;
       return global_flux_contribution_from_solid(outfile);
     }
global_flux_contribution_from_solid() [2/2]
template<class ELASTICITY_BULK_ELEMENT , class HELMHOLTZ_BULK_ELEMENT > std::complex<double> oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::global_flux_contribution_from_solid (std::ofstream & outfile) inline
Compute the element's contribution to the integral of the flux over the artificial boundary. Also output the flux in the specified output file if it's open.
     {
       // pointer to the corresponding elasticity bulk element
       ELASTICITY_BULK_ELEMENT* bulk_elem_pt =
         dynamic_cast<ELASTICITY_BULK_ELEMENT*>(this->bulk_element_pt());
       // get the dim of the bulk and local nodes
       const unsigned bulk_dim = bulk_elem_pt->dim();
       const unsigned local_dim = this->dim();
       // Set up memory for the outer unit normal
       Vector<double> unit_normal(bulk_dim);
       // Set the value of n_intpt
       const unsigned n_intpt = integral_pt()->nweight();
       // Set the Vector to hold local coordinates
       Vector<double> s(local_dim);
       std::complex<double> flux(0.0, 0.0);
       Vector<std::complex<double>> u(bulk_dim);
       // Output?
       if (outfile.is_open())
       {
         outfile << "ZONE\n";
       }
       // Loop over the integration points
       //--------------------------------
       for (unsigned ipt = 0; ipt < n_intpt; ipt++)
       {
         // Assign values of s
         for (unsigned i = 0; i < local_dim; i++)
         {
           s[i] = integral_pt()->knot(ipt, i);
         }
         // get the outer_unit_ext vector
         this->outer_unit_normal(s, unit_normal);
         // Get the integral weight
         double w = integral_pt()->weight(ipt);
         // Get jacobian of mapping
         double J = J_eulerian(s);
         // Premultiply the weights and the Jacobian
         double W = w * J;
         // Get local coordinates in bulk element by copy construction
         Vector<double> s_bulk(local_coordinate_in_bulk(s));
         // Get the displacement from the bulk element
         bulk_elem_pt->interpolated_u_time_harmonic_linear_elasticity(s_bulk, u);
         // Compute normal displacement u.n
         std::complex<double> u_dot_n(0.0, 0.0);
         for (unsigned i = 0; i < bulk_dim; i++)
         {
           u_dot_n += u[i] * unit_normal[i];
         }
         // Output?
         if (outfile.is_open())
         {
           Vector<double> x(bulk_dim);
           interpolated_x(s, x);
           outfile << x[0] << " " << x[1] << " " << u_dot_n.real() << " "
                   << u_dot_n.imag() << "\n";
         }
         // ...add to integral
         flux += u_dot_n * W;
       }
       return flux;
     }
References oomph::FaceElement::bulk_element_pt(), oomph::FiniteElement::dim(), ProblemParameters::flux(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), J, oomph::FaceElement::J_eulerian(), oomph::Integral::knot(), oomph::FaceElement::local_coordinate_in_bulk(), oomph::Integral::nweight(), oomph::FaceElement::outer_unit_normal(), s, w, oomph::QuadTreeNames::W, oomph::Integral::weight(), and plotDoE::x.
output() [1/4]
template<class ELASTICITY_BULK_ELEMENT , class HELMHOLTZ_BULK_ELEMENT > void oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::output (FILE * file_pt) inline virtual
C_style output function.
Reimplemented from oomph::FiniteElement.
     {
       FaceGeometry<ELASTICITY_BULK_ELEMENT>::output(file_pt);
     }
References output().
output() [2/4]
template<class ELASTICITY_BULK_ELEMENT , class HELMHOLTZ_BULK_ELEMENT > void oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::output (FILE * file_pt, const unsigned & n_plot) inline virtual
C-style output function.
Reimplemented from oomph::FiniteElement.
     {
       FaceGeometry<ELASTICITY_BULK_ELEMENT>::output(file_pt, n_plot);
     }
References output().
output() [3/4]
template<class ELASTICITY_BULK_ELEMENT , class HELMHOLTZ_BULK_ELEMENT > void oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::output (std::ostream & outfile) inline virtual
Output function.
Dummy
Reimplemented from oomph::FiniteElement.
     {
       unsigned nplot = 0;
       output(outfile, nplot);
     }
output() [4/4]
template<class ELASTICITY_BULK_ELEMENT , class HELMHOLTZ_BULK_ELEMENT > void oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::output (std::ostream & outfile, const unsigned & n_plot) inline virtual
Output function: Plot traction etc at Gauss points nplot is ignored.
Reimplemented from oomph::FiniteElement.
     {
       // Dimension
       unsigned n_dim = this->nodal_dimension();
       // Storage for traction
       Vector<std::complex<double>> traction(n_dim);
       // Get FSI parameter
       const double q_value = q();
       outfile << "ZONE\n";
       // Set the value of n_intpt
       unsigned n_intpt = integral_pt()->nweight();
       // Loop over the integration points
       for (unsigned ipt = 0; ipt < n_intpt; ipt++)
       {
         Vector<double> s_int(n_dim - 1);
         for (unsigned i = 0; i < n_dim - 1; i++)
         {
           s_int[i] = integral_pt()->knot(ipt, i);
         }
         // Get the outer unit normal
         Vector<double> interpolated_normal(n_dim);
         outer_unit_normal(ipt, interpolated_normal);
         // Boundary coordinate
         Vector<double> zeta(1);
         interpolated_zeta(s_int, zeta);
         // Get external element for potential
         HELMHOLTZ_BULK_ELEMENT* ext_el_pt =
           dynamic_cast<HELMHOLTZ_BULK_ELEMENT*>(external_element_pt(0, ipt));
         Vector<double> s_ext(external_element_local_coord(0, ipt));
         std::complex<double> u_helmholtz =
           ext_el_pt->interpolated_u_pml_helmholtz(s_ext);
         // Traction: Pressure is proportional to POSITIVE potential
         ext_el_pt->interpolated_u_pml_helmholtz(s_ext);
         traction[0] = -q_value * interpolated_normal[0] * u_helmholtz;
         traction[1] = -q_value * interpolated_normal[1] * u_helmholtz;
         outfile << ext_el_pt->interpolated_x(s_ext, 0) << " "
                 << ext_el_pt->interpolated_x(s_ext, 1) << " "
                 << traction[0].real() << " " << traction[1].real() << " "
                 << traction[0].imag() << " " << traction[1].imag() << " "
                 << interpolated_normal[0] << " " << interpolated_normal[1]
                 << " " << u_helmholtz.real() << " " << u_helmholtz.imag() << " "
                 << interpolated_x(s_int, 0) << " " << interpolated_x(s_int, 1)
                 << " "
                 << sqrt(pow(ext_el_pt->interpolated_x(s_ext, 0) -
                               interpolated_x(s_int, 0),
                             2) +
                         pow(ext_el_pt->interpolated_x(s_ext, 1) -
                               interpolated_x(s_int, 1),
                             2))
                 << " " << zeta[0] << std::endl;
       }
     }
References oomph::ElementWithExternalElement::external_element_local_coord(), oomph::ElementWithExternalElement::external_element_pt(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), oomph::FiniteElement::interpolated_zeta(), oomph::Integral::knot(), oomph::FiniteElement::nodal_dimension(), oomph::Integral::nweight(), oomph::FaceElement::outer_unit_normal(), Eigen::bfloat16_impl::pow(), oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::q(), sqrt(), and Eigen::zeta().
q()
template<class ELASTICITY_BULK_ELEMENT , class HELMHOLTZ_BULK_ELEMENT > const double& oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::q () const inline
Return the ratio of the stress scales used to non-dimensionalise the fluid and elasticity equations. E.g. \(Q = (\omega a)^2 \rho/E \), i.e. the ratio between the inertial fluid stress and the solid's elastic modulus E.
     {
       return *Q_pt;
     }
References oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::Q_pt.
Referenced by oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::output().
q_pt()
template<class ELASTICITY_BULK_ELEMENT , class HELMHOLTZ_BULK_ELEMENT > double*& oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::q_pt () inline
Return a pointer the ratio of stress scales used to non-dimensionalise the fluid and solid equations.
     {
       return Q_pt;
     }
References oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::Q_pt.
Member Data Documentation
Default_Q_Value
template<class ELASTICITY_BULK_ELEMENT , class HELMHOLTZ_BULK_ELEMENT > double oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::Default_Q_Value = 1.0 static protected
Static default value for the ratio of stress scales used in the fluid and solid equations (default is 1.0)
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// Static default value for the ragoogletio of stress scales used in the fluid and solid equations (default is 1.0)
Q_pt
template<class ELASTICITY_BULK_ELEMENT , class HELMHOLTZ_BULK_ELEMENT > double* oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::Q_pt protected
Pointer to the ratio, \(Q \) , of the stress used to non-dimensionalise the fluid stresses to the stress used to non-dimensionalise the solid stresses.
Referenced by oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::q(), and oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::q_pt().
U_index_time_harmonic_linear_elasticity_helmholtz_traction
template<class ELASTICITY_BULK_ELEMENT , class HELMHOLTZ_BULK_ELEMENT > Vector<std::complex<unsigned> > oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::U_index_time_harmonic_linear_elasticity_helmholtz_traction protected
Index at which the i-th displacement component is stored.
Referenced by oomph::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement< ELASTICITY_BULK_ELEMENT, HELMHOLTZ_BULK_ELEMENT >::TimeHarmonicLinElastLoadedByPMLHelmholtzPressureBCElement().
The documentation for this class was generated from the following file:
pml_helmholtz_time_harmonic_linear_elasticity_interaction.h