MercuryDPM: oomph::ClampedHermiteShellBoundaryConditionElement Class Reference
oomph::ClampedHermiteShellBoundaryConditionElement Class Reference
#include <shell_elements.h>
Public Member Functions
ClampedHermiteShellBoundaryConditionElement (FiniteElement *const &bulk_el_pt, const int &face_index)
ClampedHermiteShellBoundaryConditionElement ()
Broken empty constructor.
ClampedHermiteShellBoundaryConditionElement (const ClampedHermiteShellBoundaryConditionElement &dummy)=delete
Broken copy constructor.
void operator= (const ClampedHermiteShellBoundaryConditionElement &)=delete
Broken assignment operator.
void set_symmetry_line (const Vector< double > &normal_to_clamping_plane)
Set normal vector to clamping plane.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Fill in the element's contribution to its residual vector.
void shape (const Vector< double > &s, Shape &psi) const
void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
void output (std::ostream &outfile)
void output (std::ostream &outfile, const unsigned &n_plot)
Output function.
void output (FILE *file_pt)
void output (FILE *file_pt, const unsigned &n_plot)
unsigned ndof_types () const
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::FaceGeometry< HermiteShellElement >
FaceGeometry ()
Public Member Functions inherited from oomph::SolidQHermiteElement< 1 >
SolidQHermiteElement ()
Constructor.
SolidQHermiteElement (const SolidQHermiteElement &dummy)=delete
Broken copy constructor.
void operator= (const SolidQHermiteElement &)=delete
Broken assignment operator.
void output (std::ostream &outfile)
Overload the output function.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at n_plot points.
void output (FILE *file_pt)
C-style output.
void output (FILE *file_pt, const unsigned &n_plot)
C_style output at n_plot points.
void output (std::ostream &outfile, const unsigned &n_plot)
void output (FILE *file_pt, const unsigned &n_plot)
void output (std::ostream &outfile, const unsigned &n_p)
The output function for any number of points per element.
void output (FILE *file_pt, const unsigned &n_plot)
The C-style output function for any number of points per element.
void build_face_element (const int &face_index, FaceElement *face_element_pt)
Public Member Functions inherited from oomph::QHermiteElement< DIM >
QHermiteElement ()
Constructor.
QHermiteElement (const QHermiteElement &dummy)=delete
Broken copy constructor.
void operator= (const QHermiteElement &)=delete
Broken assignment operator.
bool local_coord_is_valid (const Vector< double > &s)
Check whether the local coordinate are valid or not.
void move_local_coord_back_into_element (Vector< double > &s) const
void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
double s_min () const
Min. value of local coordinate.
double s_max () const
Max. value of local coordinate.
void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
Get local coordinates of node j in the element; vector sets its own size.
void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
Get local fraction of node j in the element; vector sets its own size.
double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
unsigned nnode_1d () const
Return number of nodes along each element edge.
void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &use_equally_spaced_interior_sample_points=false) const
std::string tecplot_zone_string (const unsigned &nplot) const
unsigned nplot_points (const unsigned &nplot) const
void shape (const Vector< double > &s, Shape &psi) const
Shape function for specific QHermiteElement<1>
void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
Derivatives of shape functions for specific QHermiteElement<1>
void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
void shape (const Vector< double > &s, Shape &psi) const
Shape function for specific QHermiteElement<2>
void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
Derivatives of shape functions for specific QHermiteElement<2>
void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &use_equally_spaced_interior_sample_points) const
std::string tecplot_zone_string (const unsigned &nplot) const
unsigned nplot_points (const unsigned &nplot) const
void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &use_equally_spaced_interior_sample_points) const
std::string tecplot_zone_string (const unsigned &nplot) const
unsigned nplot_points (const unsigned &nplot) const
Public Member Functions inherited from oomph::QHermiteElementBase
QHermiteElementBase ()
Empty default constructor.
QHermiteElementBase (const QHermiteElementBase &)=delete
Broken copy constructor.
void operator= (const QHermiteElementBase &)=delete
Broken assignment operator.
Public Member Functions inherited from oomph::QElementGeometricBase
QElementGeometricBase ()
Empty default constructor.
QElementGeometricBase (const QElementGeometricBase &)=delete
Broken copy constructor.
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
virtual void disable_ALE ()
virtual void enable_ALE ()
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual unsigned nvertex_node () const
virtual Node * vertex_node_pt (const unsigned &j) const
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output an exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output a time-dependent exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::SolidFiniteElement
void set_lagrangian_dimension (const unsigned &lagrangian_dimension)
virtual bool has_internal_solid_data ()
SolidFiniteElement ()
Constructor: Set defaults.
virtual ~SolidFiniteElement ()
Destructor to clean up any allocated memory.
SolidFiniteElement (const SolidFiniteElement &)=delete
Broken copy constructor.
unsigned ngeom_data () const
Broken assignment operator.
Data * geom_data_pt (const unsigned &j)
void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual void get_x_and_xi (const Vector< double > &s, Vector< double > &x_fe, Vector< double > &x, Vector< double > &xi_fe, Vector< double > &xi) const
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt, MacroElement *undeformed_macro_elem_pt)
void set_undeformed_macro_elem_pt (MacroElement *undeformed_macro_elem_pt)
MacroElement * undeformed_macro_elem_pt ()
Access function to pointer to "undeformed" macro element.
double dshape_lagrangian (const Vector< double > &s, Shape &psi, DShape &dpsidxi) const
virtual double dshape_lagrangian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidxi) const
double d2shape_lagrangian (const Vector< double > &s, Shape &psi, DShape &dpsidxi, DShape &d2psidxi) const
virtual double d2shape_lagrangian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidxi, DShape &d2psidxi) const
unsigned lagrangian_dimension () const
unsigned nnodal_lagrangian_type () const
Node * construct_node (const unsigned &n)
Construct the local node n and return a pointer to it.
Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
Node * construct_boundary_node (const unsigned &n)
Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
double raw_lagrangian_position (const unsigned &n, const unsigned &i) const
double raw_lagrangian_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double lagrangian_position (const unsigned &n, const unsigned &i) const
Return i-th Lagrangian coordinate at local node n.
double lagrangian_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void interpolated_dxids (const Vector< double > &s, DenseMatrix< double > &dxids) const
virtual void J_lagrangian (const Vector< double > &s) const
virtual double J_lagrangian_at_knot (const unsigned &ipt) const
SolidInitialCondition *& solid_ic_pt ()
Pointer to object that describes the initial condition.
void enable_solve_for_consistent_newmark_accel ()
void disable_solve_for_consistent_newmark_accel ()
Set to reset the problem being solved to be the standard problem.
MultiplierFctPt & multiplier_fct_pt ()
MultiplierFctPt multiplier_fct_pt () const
virtual void get_residuals_for_solid_ic (Vector< double > &residuals)
void fill_in_residuals_for_solid_ic (Vector< double > &residuals)
void fill_in_jacobian_for_solid_ic (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_for_newmark_accel (DenseMatrix< double > &jacobian)
void compute_norm (double &el_norm)
int position_local_eqn (const unsigned &n, const unsigned &k, const unsigned &j) const
Public Member Functions inherited from oomph::SolidFaceElement
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
double interpolated_xi (const Vector< double > &s, const unsigned &i) const
void interpolated_xi (const Vector< double > &s, Vector< double > &xi) const
Public Member Functions inherited from oomph::FaceElement
FaceElement ()
Constructor: Initialise all appropriate member data.
virtual ~FaceElement ()
Empty virtual destructor.
FaceElement (const FaceElement &)=delete
Broken copy constructor.
const unsigned & boundary_number_in_bulk_mesh () const
Broken assignment operator.
void set_boundary_number_in_bulk_mesh (const unsigned &b)
Set function for the boundary number in bulk mesh.
double J_eulerian (const Vector< double > &s) const
double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
double interpolated_x (const Vector< double > &s, const unsigned &i) const
double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
void interpolated_x (const Vector< double > &s, Vector< double > &x) const
void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
int & normal_sign ()
int normal_sign () const
int & face_index ()
int face_index () const
const Vector< double > * tangent_direction_pt () const
Public access function for the tangent direction pointer.
void set_tangent_direction (Vector< double > *tangent_direction_pt)
Set the tangent direction vector.
void turn_on_warning_for_discontinuous_tangent ()
void turn_off_warning_for_discontinuous_tangent ()
void continuous_tangent_and_outer_unit_normal (const Vector< double > &s, Vector< Vector< double >> &tang_vec, Vector< double > &unit_normal) const
void continuous_tangent_and_outer_unit_normal (const unsigned &ipt, Vector< Vector< double >> &tang_vec, Vector< double > &unit_normal) const
void outer_unit_normal (const Vector< double > &s, Vector< double > &unit_normal) const
Compute outer unit normal at the specified local coordinate.
void outer_unit_normal (const unsigned &ipt, Vector< double > &unit_normal) const
Compute outer unit normal at ipt-th integration point.
FiniteElement *& bulk_element_pt ()
Pointer to higher-dimensional "bulk" element.
FiniteElement * bulk_element_pt () const
Pointer to higher-dimensional "bulk" element (const version)
CoordinateMappingFctPt & face_to_bulk_coordinate_fct_pt ()
CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt () const
BulkCoordinateDerivativesFctPt & bulk_coordinate_derivatives_fct_pt ()
BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt () const
Vector< double > local_coordinate_in_bulk (const Vector< double > &s) const
void get_local_coordinate_in_bulk (const Vector< double > &s, Vector< double > &s_bulk) const
void get_ds_bulk_ds_face (const Vector< double > &s, DenseMatrix< double > &dsbulk_dsface, unsigned &interior_direction) const
unsigned & bulk_position_type (const unsigned &i)
const unsigned & bulk_position_type (const unsigned &i) const
void bulk_node_number_resize (const unsigned &i)
Resize the storage for the bulk node numbers.
unsigned & bulk_node_number (const unsigned &n)
const unsigned & bulk_node_number (const unsigned &n) const
void bulk_position_type_resize (const unsigned &i)
Resize the storage for bulk_position_type to i entries.
unsigned & nbulk_value (const unsigned &n)
unsigned nbulk_value (const unsigned &n) const
void nbulk_value_resize (const unsigned &i)
void resize_nodes (Vector< unsigned > &nadditional_data_values)
void output_zeta (std::ostream &outfile, const unsigned &nplot)
Output boundary coordinate zeta.
Private Attributes
Vector< double > Normal_to_clamping_plane
Normal vector to the clamping plane.
Additional Inherited Members
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Public Types inherited from oomph::SolidFiniteElement
typedef double(* MultiplierFctPt) (const Vector< double > &xi)
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Member Functions inherited from oomph::SolidFiniteElement
void fill_in_generic_jacobian_for_solid_ic (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
void set_nnodal_lagrangian_type (const unsigned &nlagrangian_type)
virtual double local_to_lagrangian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_lagrangian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_lagrangian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void assign_solid_local_eqn_numbers (const bool &store_local_dof)
Assign local equation numbers for the solid equations in the element.
void describe_solid_local_dofs (std::ostream &out, const std::string &current_string) const
Classifies dofs locally for solid specific aspects.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void fill_in_jacobian_from_solid_position_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_solid_position_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_solid_position_fd ()
virtual void reset_after_solid_position_fd ()
virtual void update_in_solid_position_fd (const unsigned &i)
virtual void reset_in_solid_position_fd (const unsigned &i)
Protected Member Functions inherited from oomph::FaceElement
void add_additional_values (const Vector< unsigned > &nadditional_values, const unsigned &id)
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Protected Attributes inherited from oomph::SolidFiniteElement
MacroElement * Undeformed_macro_elem_pt
Pointer to the element's "undeformed" macro element (NULL by default)
SolidInitialCondition * Solid_ic_pt
Pointer to object that specifies the initial condition.
bool Solve_for_consistent_newmark_accel_flag
Protected Attributes inherited from oomph::FaceElement
unsigned Boundary_number_in_bulk_mesh
The boundary number in the bulk mesh to which this element is attached.
FiniteElement * Bulk_element_pt
Pointer to the associated higher-dimensional "bulk" element.
Vector< unsigned > Bulk_node_number
Vector< unsigned > Nbulk_value
Vector< double > * Tangent_direction_pt
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// Element that allows the imposition of boundary conditions for a shell that is clamped to a 2D plane that is specified by its normal. Constraint is applied by a Lagrange multiplier.
Note 1: Note that the introduction of the Lagrange multiplier adds two additional values (relative to the number of values before the addition of the FaceElement) to the nodes. This ensures that nodes that are shared by adjacent FaceElements are not resized repeatedly but also means that this won't work if two "edges" of the shell (that share a node) are subject to different constraints, each applied with its own independent Lagrange multiplier. In such cases a modified version of this class must be written.
Note 2: The FaceGeometry for a HermiteShellElement is the 1D two-node element SolidQHermiteElement<1> which has four shape functions (two nodes, two types – representing the shape functions that interpolate the value and the derivative). These are the "correct" shape functions for the interpolation of the Lagrange multiplier and the isoparametric representation of the geometry. However, when applying the contribution from the constraint equation to the bulk equations, we have to take all four types of dof into account so the element has to reset the number of positional dofs to four. To avoid any clashes we overload (the relevant subset of) the access functions to the shape functions and their derivatives and set the shape functions associated with the spurious positional dofs to zero. This is a bit hacky but the only way (?) this can be done...
Constructor & Destructor Documentation
ClampedHermiteShellBoundaryConditionElement() [1/3]
oomph::ClampedHermiteShellBoundaryConditionElement::ClampedHermiteShellBoundaryConditionElement (FiniteElement *const & bulk_el_pt, const int & face_index)
Constructor, takes the pointer to the "bulk" element and the face index.
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// Constructor, takes the pointer to the "bulk" element, the index of the fixed local coordinate and its value represented by an integer (+/- 1), indicating that the face is located at the max. or min. value of the "fixed" local coordinate in the bulk element.
     : FaceGeometry<HermiteShellElement>(), FaceElement()
   {
     // Let the bulk element build the FaceElement, i.e. setup the pointers
     // to its nodes (by referring to the appropriate nodes in the bulk
     // element), etc.
     bulk_el_pt->build_face_element(face_index, this);
     // Overwrite default assignments:
     // Number of position types (for automatic local equation numbering)
     // must be re-set to the shell case because the constraint
     // equation makes contributions to all 3 (coordinate directions) x
     // 4 (types of positional dofs) = 12 dofs associated with each node in the
     // shell element. But keep reading...
     set_nnodal_position_type(4);
     // The trouble with the above is that the parametrisation of the
     // element geometry (used in J_eulerian and elsewhere)
     // is based on the 4 (2 nodes x 2 types -- value and slope) shape functions
     // in the 1D element. In general this is done by looping over the
     // nodal position types (2 per node) and referring to the
     // relevant position Data at the nodes indirectly via the
     // bulk_position_type(...) function. This is now screwed up
     // because we've bumped up the number of nodal position types
     // to four! The slightly hacky way around this is resize
     // the lookup scheme underlying the bulk_position_type(...)
     // to four types of degree of freedom per node so it's consistent
     // with the above assignement. However, we only have shape
     // functions associated with the two types of degree of freedom,
     // so (below) we overload shape(...) and dshape_local(...)
     // to that it returns zero for all "superfluous" shape functions.
     bulk_position_type_resize(4);
     // Make some dummy assigments to the position types that
     // correspond to the two superfluous ones -- the values associated
     // with these will never be used since we're setting the
     // associated shape functions to zero!
     bulk_position_type(2) = 0;
     bulk_position_type(3) = 0;
     // Resize normal to clamping plane and initialise for clamping
     // being applied in a plane where z=const.
     Normal_to_clamping_plane.resize(3);
     Normal_to_clamping_plane[0] = 0.0;
     Normal_to_clamping_plane[1] = 0.0;
     Normal_to_clamping_plane[2] = 1.0;
     // We need two additional values (for the two types of the Lagrange
     // multiplier interpolated by the 1D Hermite basis functions)
     // at the element's two nodes
     Vector<unsigned> nadditional_data_values(2);
     nadditional_data_values[0] = 2;
     nadditional_data_values[1] = 2;
     resize_nodes(nadditional_data_values);
   }
References oomph::FiniteElement::build_face_element(), oomph::FaceElement::bulk_position_type(), oomph::FaceElement::bulk_position_type_resize(), oomph::FaceElement::face_index(), Normal_to_clamping_plane, oomph::FaceElement::resize_nodes(), and oomph::FiniteElement::set_nnodal_position_type().
ClampedHermiteShellBoundaryConditionElement() [2/3]
oomph::ClampedHermiteShellBoundaryConditionElement::ClampedHermiteShellBoundaryConditionElement () inline
Broken empty constructor.
     {
       throw OomphLibError("Don't call empty constructor for "
                           "ClampedHermiteShellBoundaryConditionElement",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
ClampedHermiteShellBoundaryConditionElement() [3/3]
oomph::ClampedHermiteShellBoundaryConditionElement::ClampedHermiteShellBoundaryConditionElement (const ClampedHermiteShellBoundaryConditionElement & dummy) delete
Broken copy constructor.
Member Function Documentation
dshape_local()
void oomph::ClampedHermiteShellBoundaryConditionElement::dshape_local (const Vector< double > & s, Shape & psi, DShape & dpsids) const inline virtual
Calculate the geometric shape functions at local coordinate s. Set any "superfluous" shape functions to zero.
Reimplemented from oomph::FiniteElement.
     {
       // Initialise all of them to zero
       unsigned n = psi.nindex1();
       unsigned m = psi.nindex2();
       for (unsigned i = 0; i < n; i++)
       {
         for (unsigned j = 0; j < m; j++)
         {
           psi(i, j) = 0.0;
         }
       }
       unsigned n1 = dpsids.nindex1();
       unsigned n2 = dpsids.nindex2();
       unsigned n3 = dpsids.nindex3();
       for (unsigned i = 0; i < n1; i++)
       {
         for (unsigned j = 0; j < n2; j++)
         {
           for (unsigned k = 0; k < n3; k++)
           {
             dpsids(i, j, k) = 0.0;
           }
         }
       }
       FaceGeometry<HermiteShellElement>::dshape_local(s, psi, dpsids);
     }
References i, j, k, m, n, oomph::Shape::nindex1(), oomph::DShape::nindex1(), oomph::Shape::nindex2(), oomph::DShape::nindex2(), oomph::DShape::nindex3(), and s.
fill_in_contribution_to_residuals()
void oomph::ClampedHermiteShellBoundaryConditionElement::fill_in_contribution_to_residuals (Vector< double > & residuals) virtual
Fill in the element's contribution to its residual vector.
Add the element's contribution to its residual vector.
Reimplemented from oomph::GeneralisedElement.
   {
     // Get position vector to and normal vector on wall (from bulk element)
     HermiteShellElement* bulk_el_pt =
       dynamic_cast<HermiteShellElement*>(bulk_element_pt());
     // Local coordinates in bulk
     Vector<double> s_bulk(2);
     // Local coordinate in FaceElement:
     Vector<double> s(1);
     // Normal to shell
     Vector<double> shell_normal(3);
     Vector<double> shell_normal_plus(3);
     // Find out how many nodes there are
     const unsigned n_node = nnode();
     // Types of (nonzero) shape/test fcts (for Lagrange multiplier) in
     // this element
     unsigned n_type = 2;
     // Integer to store the local equation number
     int local_eqn = 0;
     // Set up memory for the shape functions:
     // Shape fcts
     Shape psi(n_node, n_type);
     // Set # of integration points
     const unsigned n_intpt = integral_pt()->nweight();
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Get integration point in local coordinates
       s[0] = integral_pt()->knot(ipt, 0);
       // Get shape functions
       shape(s, psi);
       // Get jacobian
       double J = J_eulerian(s);
       // Assemble the Lagrange multiplier
       double lambda = 0.0;
       for (unsigned j = 0; j < n_node; j++)
       {
         for (unsigned k = 0; k < n_type; k++)
         {
           // The (additional) Lagrange multiplier values are stored
           // after those that were created by the bulk elements:
           lambda += node_pt(j)->value(Nbulk_value[j] + k) * psi(j, k);
         }
       }
       // Get vector of coordinates in bulk element
       s_bulk = local_coordinate_in_bulk(s);
       // Get unit normal on bulk shell element
       bulk_el_pt->get_normal(s_bulk, shell_normal);
       // Premultiply the weights and the Jacobian
       double W = w * J;
       // Here's the actual constraint
       double constraint_residual =
         shell_normal[0] * Normal_to_clamping_plane[0] +
         shell_normal[1] * Normal_to_clamping_plane[1] +
         shell_normal[2] * Normal_to_clamping_plane[2];
       // Assemble residual for Lagrange multiplier:
       //-------------------------------------------
       // Loop over the number of nodes
       for (unsigned j = 0; j < n_node; j++)
       {
         // Loop over the type of degree of freedom
         for (unsigned k = 0; k < n_type; k++)
         {
           // Local eqn number. Recall that the
           // (additional) Lagrange multiplier values are stored
           // after those that were created by the bulk elements:
           local_eqn = nodal_local_eqn(j, Nbulk_value[j] + k);
           if (local_eqn >= 0)
           {
             residuals[local_eqn] += constraint_residual * psi(j, k) * W;
           }
         }
       }
       // Add Lagrange multiplier contribution to bulk equations
       //-------------------------------------------------------
       // Derivatives of constraint equations w.r.t. positional values
       // is done by finite differencing
       double fd_step = 1.0e-8;
       // Loop over the number of nodes
       for (unsigned j = 0; j < n_node; j++)
       {
         Node* nod_pt = node_pt(j);
         // Loop over directions
         for (unsigned i = 0; i < 3; i++)
         {
           // Loop over the type of degree of freedom
           for (unsigned k = 0; k < 4; k++)
           {
             // Local eqn number: Node, type, direction
             local_eqn = position_local_eqn(j, k, i);
             if (local_eqn >= 0)
             {
               // Backup
               double backup = nod_pt->x_gen(k, i);
               // Increment
               nod_pt->x_gen(k, i) += fd_step;
               // Re-evaluate unit normal on bulk shell element
               bulk_el_pt->get_normal(s_bulk, shell_normal_plus);
               // Re-evaluate the constraint
               double constraint_residual_plus =
                 shell_normal_plus[0] * Normal_to_clamping_plane[0] +
                 shell_normal_plus[1] * Normal_to_clamping_plane[1] +
                 shell_normal_plus[2] * Normal_to_clamping_plane[2];
               // Derivarive of constraint w.r.t. to current discrete
               // displacement
               double dres_dx =
                 (constraint_residual_plus - constraint_residual) / fd_step;
               // Add to residual
               residuals[local_eqn] += lambda * dres_dx * W;
               // Reset
               nod_pt->x_gen(k, i) = backup;
             }
           }
         }
       }
     } // End of loop over the integration points
     // Loop over integration points
   }
References oomph::FaceElement::bulk_element_pt(), oomph::KirchhoffLoveShellEquations::get_normal(), i, oomph::FiniteElement::integral_pt(), J, j, oomph::FaceElement::J_eulerian(), k, oomph::Integral::knot(), lambda, oomph::FaceElement::local_coordinate_in_bulk(), oomph::FaceElement::Nbulk_value, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), Normal_to_clamping_plane, oomph::Integral::nweight(), oomph::SolidFiniteElement::position_local_eqn(), s, shape(), oomph::Node::value(), w, oomph::QuadTreeNames::W, oomph::Integral::weight(), and oomph::Node::x_gen().
get_dof_numbers_for_unknowns()
void oomph::ClampedHermiteShellBoundaryConditionElement::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> & dof_lookup_list) const virtual
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the "DOF types" that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the "DOF types" that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) This element is only in charge of the solid dofs.
Reimplemented from oomph::GeneralisedElement.
   {
     // temporary pair (used to store dof lookup prior to being added to list)
     std::pair<unsigned long, unsigned> dof_lookup;
     // number of nodes
     const unsigned n_node = this->nnode();
     // Get the number of position dofs and dimensions at the node
     const unsigned n_position_type = nnodal_position_type();
     const unsigned nodal_dim = nodal_dimension();
     // Integer storage for local unknown
     int local_unknown = 0;
     // Loop over the nodes
     for (unsigned n = 0; n < n_node; n++)
     {
       Node* nod_pt = this->node_pt(n);
       // Loop over position dofs
       for (unsigned k = 0; k < n_position_type; k++)
       {
         // Loop over dimension
         for (unsigned i = 0; i < nodal_dim; i++)
         {
           // If the variable is free
           local_unknown = position_local_eqn(n, k, i);
           // ignore pinned values
           if (local_unknown >= 0)
           {
             // store dof lookup in temporary pair: First entry in pair
             // is global equation number; second entry is dof type
             dof_lookup.first = this->eqn_number(local_unknown);
             dof_lookup.second = 0;
             // add to list
             dof_lookup_list.push_front(dof_lookup);
           }
         }
       }
       // Loop over values
       unsigned n_val = nod_pt->nvalue();
       for (unsigned j = 0; j < n_val; j++)
       {
         // If the variable is free
         local_unknown = nodal_local_eqn(n, j);
         // ignore pinned values
         if (local_unknown >= 0)
         {
           // store dof lookup in temporary pair: First entry in pair
           // is global equation number; second entry is dof type
           dof_lookup.first = this->eqn_number(local_unknown);
           dof_lookup.second = 0;
           // add to list
           dof_lookup_list.push_front(dof_lookup);
         }
       }
     }
   }
References oomph::GeneralisedElement::eqn_number(), i, j, k, n, oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_dimension(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), oomph::Data::nvalue(), and oomph::SolidFiniteElement::position_local_eqn().
ndof_types()
unsigned oomph::ClampedHermiteShellBoundaryConditionElement::ndof_types () const inline virtual
The number of "DOF types" that degrees of freedom in this element are sub-divided into: Just the solid degrees of freedom themselves.
Reimplemented from oomph::GeneralisedElement.
     {
       return 1;
     }
operator=()
void oomph::ClampedHermiteShellBoundaryConditionElement::operator= (const ClampedHermiteShellBoundaryConditionElement &) delete
Broken assignment operator.
output() [1/4]
void oomph::ClampedHermiteShellBoundaryConditionElement::output (FILE * file_pt) inline virtual
C-style output function – forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
     {
       FiniteElement::output(file_pt);
     }
References oomph::FiniteElement::output().
output() [2/4]
void oomph::ClampedHermiteShellBoundaryConditionElement::output (FILE * file_pt, const unsigned & n_plot) inline virtual
C-style output function – forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
     {
       FiniteElement::output(file_pt, n_plot);
     }
References oomph::FiniteElement::output().
output() [3/4]
void oomph::ClampedHermiteShellBoundaryConditionElement::output (std::ostream & outfile) inline virtual
Output function – forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
     {
       FiniteElement::output(outfile);
     }
References oomph::FiniteElement::output().
output() [4/4]
void oomph::ClampedHermiteShellBoundaryConditionElement::output (std::ostream & outfile, const unsigned & n_plot) virtual
Output function.
Reimplemented from oomph::FiniteElement.
   {
     // Get bulk element
     HermiteShellElement* bulk_el_pt =
       dynamic_cast<HermiteShellElement*>(bulk_element_pt());
     // Local coord
     Vector<double> s(1);
     // Coordinate in bulk
     Vector<double> s_bulk(2);
     // Normal vector
     Vector<double> shell_normal(3);
     // # of nodes, # of dof types
     Shape psi(2, 2);
     // Tecplot header info
     outfile << "ZONE I=" << n_plot << std::endl;
     // Loop over plot points
     for (unsigned l = 0; l < n_plot; l++)
     {
       s[0] = -1.0 + l * 2.0 / (n_plot - 1);
       // Get vector of coordinates in bulk element
       s_bulk = local_coordinate_in_bulk(s);
       // Get unit normal on bulk shell element
       bulk_el_pt->get_normal(s_bulk, shell_normal);
       // Get shape function
       shape(s, psi);
       // Assemble the Lagrange multiplier
       double lambda = 0.0;
       for (unsigned j = 0; j < 2; j++)
       {
         for (unsigned k = 0; k < 2; k++)
         {
           // The (additional) Lagrange multiplier values are stored
           // after those that were created by the bulk elements:
           lambda += node_pt(j)->value(Nbulk_value[j] + k) * psi(j, k);
         }
       }
       double dot_product = shell_normal[0] * Normal_to_clamping_plane[0] +
                            shell_normal[1] * Normal_to_clamping_plane[1] +
                            shell_normal[2] * Normal_to_clamping_plane[2];
       // Output stuff
       outfile << s[0] << " " << interpolated_xi(s, 0) << " "
               << interpolated_xi(s, 1) << " " << interpolated_x(s, 0) << " "
               << interpolated_x(s, 1) << " " << interpolated_x(s, 2) << " "
               << J_eulerian(s) << " " << bulk_el_pt->interpolated_xi(s_bulk, 0)
               << " " << bulk_el_pt->interpolated_xi(s_bulk, 1) << " "
               << bulk_el_pt->interpolated_x(s_bulk, 0) << " "
               << bulk_el_pt->interpolated_x(s_bulk, 1) << " "
               << bulk_el_pt->interpolated_x(s_bulk, 2) << " " << lambda << " "
               << shell_normal[0] << " " << shell_normal[1] << " "
               << shell_normal[2] << " " << Normal_to_clamping_plane[0] << " "
               << Normal_to_clamping_plane[1] << " "
               << Normal_to_clamping_plane[2] << " " << dot_product << " "
               << std::endl;
     }
     // Initialise error
     const bool check_error = false;
     if (check_error)
     {
       double max_error = 0.0;
       // Set # of integration points
       const unsigned n_intpt = integral_pt()->nweight();
       // Loop over the integration points
       for (unsigned ipt = 0; ipt < n_intpt; ipt++)
       {
         // Get integration point in local coordinates
         s[0] = integral_pt()->knot(ipt, 0);
         // Get eulerian jacobian via s
         double J_via_s = J_eulerian(s);
         // Get eulerian jacobian via ipt
         double J_via_ipt = J_eulerian_at_knot(ipt);
         double error = std::fabs(J_via_s - J_via_ipt);
         if (error > max_error) max_error = error;
       }
       if (max_error > 1.0e-14)
       {
         oomph_info << "Warning: Max. error between J_via_s J_via_ipt "
                    << max_error << std::endl;
       }
     }
   }
References oomph::FaceElement::bulk_element_pt(), calibrate::error, boost::multiprecision::fabs(), oomph::KirchhoffLoveShellEquations::get_normal(), oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), oomph::FaceElement::interpolated_x(), oomph::SolidFiniteElement::interpolated_xi(), oomph::SolidFaceElement::interpolated_xi(), j, oomph::FaceElement::J_eulerian(), oomph::FaceElement::J_eulerian_at_knot(), k, oomph::Integral::knot(), lambda, oomph::FaceElement::local_coordinate_in_bulk(), MeshRefinement::max_error, oomph::FaceElement::Nbulk_value, oomph::FiniteElement::node_pt(), Normal_to_clamping_plane, oomph::Integral::nweight(), oomph::oomph_info, s, shape(), and oomph::Node::value().
set_symmetry_line()
void oomph::ClampedHermiteShellBoundaryConditionElement::set_symmetry_line (const Vector< double > & normal_to_clamping_plane) inline
Set normal vector to clamping plane.
     {
       Normal_to_clamping_plane[0] = normal_to_clamping_plane[0];
       Normal_to_clamping_plane[1] = normal_to_clamping_plane[1];
       Normal_to_clamping_plane[2] = normal_to_clamping_plane[2];
     }
References Normal_to_clamping_plane.
shape()
void oomph::ClampedHermiteShellBoundaryConditionElement::shape (const Vector< double > & s, Shape & psi) const inline virtual
Calculate the geometric shape functions at local coordinate s. Set any "superfluous" shape functions to zero.
Implements oomph::FiniteElement.
     {
       // Initialise all of them to zero
       unsigned n = psi.nindex1();
       unsigned m = psi.nindex2();
       for (unsigned i = 0; i < n; i++)
       {
         for (unsigned j = 0; j < m; j++)
         {
           psi(i, j) = 0.0;
         }
       }
       FaceGeometry<HermiteShellElement>::shape(s, psi);
     }
References i, j, m, n, oomph::Shape::nindex1(), oomph::Shape::nindex2(), s, and oomph::OneDimLagrange::shape().
Referenced by fill_in_contribution_to_residuals(), and output().
Member Data Documentation
Normal_to_clamping_plane
Vector<double> oomph::ClampedHermiteShellBoundaryConditionElement::Normal_to_clamping_plane private
Normal vector to the clamping plane.
Referenced by ClampedHermiteShellBoundaryConditionElement(), fill_in_contribution_to_residuals(), output(), and set_symmetry_line().
The documentation for this class was generated from the following files:
shell_elements.h
shell_elements.cc