MercuryDPM: ParticleVtkWriter Class Reference
ParticleVtkWriter Class Reference abstract
#include <ParticleVtkWriter.h>
Public Member Functions
ParticleVtkWriter (ParticleHandler &particleHandler)
virtual ~ParticleVtkWriter ()=default
virtual std::string getName () const =0
Public Member Functions inherited from BaseVTKWriter< ParticleHandler >
BaseVTKWriter (ParticleHandler &handler)
BaseVTKWriter (const BaseVTKWriter &other)
virtual void writeVTK () const=0
unsigned getFileCounter () const
void setFileCounter (unsigned fileCounter)
void setOutputDirectory (const std::string &dir)
const std::string & getOutputDirectory () const
std::string getFileName () const
Protected Member Functions
void writeExtraFields (std::fstream &file) const
void writeVTKIndSpecies (std::fstream &file) const
void writeVTKPositions (std::fstream &file) const
bool particleMustBeWritten (BaseParticle *particle) const
Protected Member Functions inherited from BaseVTKWriter< ParticleHandler >
std::fstream makeVTKFileWithHeader () const
void writeVTKFooterAndClose (std::fstream &file) const
Additional Inherited Members
Protected Attributes inherited from BaseVTKWriter< ParticleHandler >
ParticleHandler & handler_
particle handler from which the particles should be written
unsigned int fileCounter
std::string outputDirectory_
Constructor & Destructor Documentation
ParticleVtkWriter()
ParticleVtkWriter::ParticleVtkWriter (ParticleHandler & particleHandler) inline explicit
                                                                  : BaseVTKWriter(particleHandler)
     {}
~ParticleVtkWriter()
virtual ParticleVtkWriter::~ParticleVtkWriter () virtual default
Member Function Documentation
getName()
virtual std::string ParticleVtkWriter::getName () const pure virtual
Implemented in SuperQuadricParticleVtkWriter, and SphericalParticleVtkWriter.
particleMustBeWritten()
bool ParticleVtkWriter::particleMustBeWritten (BaseParticle * particle) const inline protected
     {
         return !(particle->isMPIParticle() || particle->isPeriodicGhostParticle());
     }
References BaseParticle::isMPIParticle(), and BaseParticle::isPeriodicGhostParticle().
Referenced by writeExtraFields(), SphericalParticleVtkWriter::writeVTKAngularVelocity(), SphericalParticleVtkWriter::writeVTKId(), writeVTKIndSpecies(), writeVTKPositions(), SphericalParticleVtkWriter::writeVTKRadius(), and SphericalParticleVtkWriter::writeVTKVelocity().
writeExtraFields()
void ParticleVtkWriter::writeExtraFields (std::fstream & file) const protected
 {
     //check if this type of Interaction has extra fields
     if (handler_.getSize() != 0)
     {
         for (unsigned i = 0; i < handler_.getLastObject()->getNumberOfFieldsVTK(); i++)
         {
             file << "  <DataArray type=\"" << handler_.getLastObject()->getTypeVTK(i) << "\" Name=\""
                  << handler_.getLastObject()->getNameVTK(i) << "\" format=\"ascii\">\n";
             // Add species type
             for (const auto& p: handler_)
             {
                 for (auto f : p->getFieldVTK(i)) {
 #ifdef MERCURYDPM_USE_MPI
                     if (particleMustBeWritten(p))
                     {
                         file << '\t' << (float)f << '\n';
                     }
 #else
                     file << '\t' << (float)f << '\n';
 #endif
                 }
             }
             file << "  </DataArray>\n";
         }
     }
 }
References f(), BaseHandler< T >::getLastObject(), BaseParticle::getNameVTK(), BaseHandler< T >::getSize(), BaseParticle::getTypeVTK(), BaseVTKWriter< ParticleHandler >::handler_, i, p, and particleMustBeWritten().
Referenced by SphericalParticleVtkWriter::writeVTK().
writeVTKIndSpecies()
void ParticleVtkWriter::writeVTKIndSpecies (std::fstream & file) const protected
 {
     file << "  <DataArray type=\"Float32\" Name=\"speciesType\" format=\"ascii\">\n";
     // Add species type
     for (const auto& p: handler_)
     {
 #ifdef MERCURYDPM_USE_MPI
         if (particleMustBeWritten(p))
         {
             file << '\t' << p->getIndSpecies() << '\n';
         }
 #else
         file << '\t' << p->getIndSpecies() << '\n';
 #endif
     }
     file << "  </DataArray>\n";
 }
References BaseVTKWriter< ParticleHandler >::handler_, p, and particleMustBeWritten().
Referenced by SphericalParticleVtkWriter::writeVTK(), and SuperQuadricParticleVtkWriter::writeVTK().
writeVTKPositions()
void ParticleVtkWriter::writeVTKPositions (std::fstream & file) const protected
 {
     file << "<Points>\n";
     file << "  <DataArray type=\"Float32\" Name=\"Position\" NumberOfComponents=\"3\" format=\"ascii\">\n";
     for (const auto& p: handler_)
     {
 #ifdef MERCURYDPM_USE_MPI
         if (particleMustBeWritten(p))
         {
             file << '\t' << p->getPosition() << '\n';
         }
 #else
         file << '\t' << (float)p->getPosition().X << ' ' << (float)p->getPosition().Y << ' ' << (float)p->getPosition().Z << '\n';
 #endif
     }
     file << "  </DataArray>\n";
     file << "</Points>\n";
 }
References BaseVTKWriter< ParticleHandler >::handler_, p, and particleMustBeWritten().
Referenced by SphericalParticleVtkWriter::writeVTK(), and SuperQuadricParticleVtkWriter::writeVTK().
The documentation for this class was generated from the following files:
ParticleVtkWriter.h
ParticleVtkWriter.cc