MercuryDPM: mesh_from_geompack_poisson.cc File Reference
mesh_from_geompack_poisson.cc File Reference
#include "generic.h"
#include "poisson.h"
#include "meshes/geompack_mesh.h"
Classes
class PoissonProblem< ELEMENT >
Micky mouse Poisson problem.
Namespaces
TanhSolnForPoisson
Namespace for exact solution for Poisson equation with "sharp step".
Functions
void TanhSolnForPoisson::get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void TanhSolnForPoisson::get_exact_u (const Vector< double > &x, double &u)
Exact solution as a scalar.
void TanhSolnForPoisson::get_source (const Vector< double > &x, double &source)
Source function to make it an exact solution.
int main (int argc, char *argv[])
Demonstrate how to solve Poisson problem.
Variables
double TanhSolnForPoisson::Beta
Parameter for angle of step.
Function Documentation
main()
int main (int argc , char * argv[])
Demonstrate how to solve Poisson problem.
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Label for output
 {
 // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Check number of command line arguments: Need exactly two.
  if (argc!=3)
   {
    std::string error_message =
     "Wrong number of command line arguments.\n";
    error_message +=
     "Must specify the following file names  \n";
    error_message +=
     "filename.mh2 then filename.cs2\n";
    throw OomphLibError(error_message,
                        OOMPH_CURRENT_FUNCTION,
                        OOMPH_EXCEPTION_LOCATION);
   }
  // Convert arguments to strings that specify the input file names
  string mesh_file_name(argv[1]);
  string curve_file_name(argv[2]);
  //Set up the problem
  PoissonProblem<QPoissonElement<2,2> >
   problem(&TanhSolnForPoisson::get_source,
           mesh_file_name,curve_file_name);
  DocInfo doc_info;
  // Output directory
  doc_info.set_directory("RESLT");
  // Solve the problem
  problem.newton_solve();
  //Output solution
  problem.doc_solution(doc_info);
 }
References TanhSolnForPoisson::get_source(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, problem, oomph::DocInfo::set_directory(), Flag_definition::setup(), and oomph::Global_string_for_annotation::string().