MercuryDPM: oomph::MyTaylorHoodElement< DIM > Class Template Reference
oomph::MyTaylorHoodElement< DIM > Class Template Reference
Overload TaylorHood element to modify output.
#include <my_taylor_hood_elements.h>
Public Member Functions
MyTaylorHoodElement ()
Constructor initialise error.
void output (std::ostream &outfile, const unsigned &nplot)
Overload output function.
MyTaylorHoodElement ()
Constructor initialise error.
void set_error (const double &error)
Set error value for post-processing.
std::string variable_identifier ()
Return variable identifier.
void output (std::ostream &outfile, const unsigned &nplot)
Overload output function.
double square_of_l2_norm ()
Get square of L2 norm of velocity.
MyTaylorHoodElement ()
Constructor initialise error.
void set_error (const double &error)
Set error value for post-processing.
std::string variable_identifier ()
Return variable identifier.
void output (std::ostream &outfile, const unsigned &nplot)
Overload output function.
double square_of_l2_norm ()
Get square of L2 norm of velocity.
MyTaylorHoodElement ()
Constructor initialise error.
void set_error (const double &error)
Set error value for post-processing.
std::string variable_identifier ()
Return variable identifier.
void output (std::ostream &outfile, const unsigned &nplot)
Overload output function.
double square_of_l2_norm ()
Get square of L2 norm of velocity.
Public Member Functions inherited from oomph::PseudoSolidNodeUpdateElement< AxisymmetricTTaylorHoodElement, TPVDElement< 2, 3 > >
PseudoSolidNodeUpdateElement ()
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void compute_norm (double &el_norm)
unsigned required_nvalue (const unsigned &n) const
The required number of values is the sum of the two.
int solid_p_nodal_index () const
void fill_in_contribution_to_residuals (Vector< double > &residuals)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
void evaluate_shape_derivs_by_direct_fd ()
Evaluate shape derivatives by direct finite differencing.
void evaluate_shape_derivs_by_chain_rule ()
Evaluate shape derivatives by chain rule.
void fill_in_shape_derivatives (DenseMatrix< double > &jacobian)
void fill_in_shape_derivatives_by_fd (DenseMatrix< double > &jacobian)
void identify_geometric_data (std::set< Data * > &geometric_data_pt)
void output (std::ostream &outfile)
Overload the output function: Call that of the basic element.
void output (std::ostream &outfile, const unsigned &n_p)
void output (FILE *file_pt)
Overload the output function: Call that of the basic element.
void output (FILE *file_pt, const unsigned &n_p)
Output function is just the same as the basic equations.
unsigned num_Z2_flux_terms ()
void compute_exact_Z2_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_flux_pt, double &error, double &norm)
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
unsigned nrecovery_order ()
unsigned ndof_types () const
unsigned nbasic_dof_types () const
unsigned nsolid_dof_types () const
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::AxisymmetricTTaylorHoodElement
AxisymmetricTTaylorHoodElement ()
Constructor, no internal data points.
AxisymmetricTTaylorHoodElement (const AxisymmetricTTaylorHoodElement &dummy)=delete
Broken copy constructor.
void pshape_axi_nst (const Vector< double > &s, Shape &psi) const
Test whether the pressure dof p_dof hanging or not?
void pshape_axi_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Pressure shape and test functions at local coordinte s.
unsigned p_index_axi_nst ()
Which nodal value represents the pressure?
int p_local_eqn (const unsigned &n) const
Pointer to n_p-th pressure node.
double p_axi_nst (const unsigned &n_p) const
int p_nodal_index_axi_nst () const
Set the value at which the pressure is stored in the nodes.
unsigned npres_axi_nst () const
Return number of pressure values.
void fix_pressure (const unsigned &p_dof, const double &p_value)
Pin p_dof-th pressure dof and set it to value specified by p_value.
void identify_load_data (std::set< std::pair< Data *, unsigned >> &paired_load_data)
void identify_pressure_data (std::set< std::pair< Data *, unsigned >> &paired_pressure_data)
Public Member Functions inherited from oomph::TElement< 2, 3 >
const unsigned Node_on_face [3][2]
Assign the nodal translation schemes.
const unsigned Node_on_face [3][3]
const unsigned Node_on_face [3][4]
const unsigned Node_on_face [4][3]
Assign the nodal translation scheme for linear elements.
const unsigned Node_on_face [4][6]
Assign the nodal translation scheme for quadratic elements.
Public Member Functions inherited from oomph::AxisymmetricNavierStokesEquations
AxisymmetricNavierStokesEquations ()
Constructor: NULL the body force and source function.
const double & re () const
Reynolds number.
const double & re_st () const
Product of Reynolds and Strouhal number (=Womersley number)
double *& re_pt ()
Pointer to Reynolds number.
double *& re_st_pt ()
Pointer to product of Reynolds and Strouhal number (=Womersley number)
const double & re_invfr () const
Global inverse Froude number.
double *& re_invfr_pt ()
Pointer to global inverse Froude number.
const double & re_invro () const
Global Reynolds number multiplied by inverse Rossby number.
double *& re_invro_pt ()
Pointer to global inverse Froude number.
const Vector< double > & g () const
Vector of gravitational components.
Vector< double > *& g_pt ()
Pointer to Vector of gravitational components.
const double & density_ratio () const
double *& density_ratio_pt ()
Pointer to Density ratio.
const double & viscosity_ratio () const
double *& viscosity_ratio_pt ()
Pointer to Viscosity Ratio.
virtual unsigned u_index_axi_nst (const unsigned &i) const
unsigned u_index_nst (const unsigned &i) const
unsigned n_u_nst () const
double du_dt_axi_nst (const unsigned &n, const unsigned &i) const
void disable_ALE ()
void enable_ALE ()
double pressure_integral () const
Integral of pressure over element.
double dissipation () const
Return integral of dissipation over element.
double dissipation (const Vector< double > &s) const
Return dissipation at local coordinate s.
double kin_energy () const
Get integral of kinetic energy over element.
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
Strain-rate tensor: \(e_{ij} \) where \(i,j = r,z,\theta \) (in that order)
void traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction) const
void get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > &press_mass_diag, Vector< double > &veloc_mass_diag, const unsigned &which_one=0)
unsigned nscalar_paraview () const
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
std::string scalar_name_paraview (const unsigned &i) const
void point_output_data (const Vector< double > &s, Vector< double > &data)
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
Compute the element's residual Vector.
void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
void interpolated_u_axi_nst (const Vector< double > &s, Vector< double > &veloc) const
Compute vector of FE interpolated velocity u at local coordinate s.
double interpolated_u_axi_nst (const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s.
double interpolated_u_axi_nst (const unsigned &t, const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s.
virtual void dinterpolated_u_axi_nst_ddata (const Vector< double > &s, const unsigned &i, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
double interpolated_p_axi_nst (const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s.
double interpolated_duds_axi_nst (const Vector< double > &s, const unsigned &i, const unsigned &j) const
double interpolated_dudx_axi_nst (const Vector< double > &s, const unsigned &i, const unsigned &j) const
double interpolated_dudt_axi_nst (const Vector< double > &s, const unsigned &i) const
double interpolated_d_dudx_dX_axi_nst (const Vector< double > &s, const unsigned &p, const unsigned &q, const unsigned &i, const unsigned &k) const
double compute_physical_size () const
Compute the volume of the element.
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::NavierStokesElementWithDiagonalMassMatrices
NavierStokesElementWithDiagonalMassMatrices ()
Empty constructor.
virtual ~NavierStokesElementWithDiagonalMassMatrices ()
Virtual destructor.
NavierStokesElementWithDiagonalMassMatrices (const NavierStokesElementWithDiagonalMassMatrices &)=delete
Broken copy constructor.
void operator= (const NavierStokesElementWithDiagonalMassMatrices &)=delete
Broken assignment operator.
Public Member Functions inherited from oomph::ElementWithZ2ErrorEstimator
ElementWithZ2ErrorEstimator ()
Default empty constructor.
ElementWithZ2ErrorEstimator (const ElementWithZ2ErrorEstimator &)=delete
Broken copy constructor.
void operator= (const ElementWithZ2ErrorEstimator &)=delete
Broken assignment operator.
virtual unsigned ncompound_fluxes ()
virtual void get_Z2_compound_flux_indices (Vector< unsigned > &flux_index)
virtual double geometric_jacobian (const Vector< double > &x)
Public Member Functions inherited from oomph::TPVDElement< DIM, NNODE_1D >
TPVDElement ()
Constructor, there are no internal data points.
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
Public Member Functions inherited from oomph::PVDEquations< DIM >
PVDEquations ()
Constructor.
void get_stress (const Vector< double > &s, DenseMatrix< double > &sigma)
void extended_output (std::ostream &outfile, const unsigned &n_plot)
Output: x,y,[z],xi0,xi1,[xi2],gamma strain and stress components.
Public Member Functions inherited from oomph::PVDEquationsBase< DIM >
PVDEquationsBase ()
ConstitutiveLaw *& constitutive_law_pt ()
Return the constitutive law pointer.
const double & lambda_sq () const
Access function for timescale ratio (nondim density)
double *& lambda_sq_pt ()
Access function for pointer to timescale ratio (nondim density)
IsotropicGrowthFctPt & isotropic_growth_fct_pt ()
Access function: Pointer to isotropic growth function.
PrestressFctPt & prestress_fct_pt ()
Access function: Pointer to pre-stress function.
IsotropicGrowthFctPt isotropic_growth_fct_pt () const
Access function: Pointer to isotropic growth function (const version)
BodyForceFctPt & body_force_fct_pt ()
Access function: Pointer to body force function.
BodyForceFctPt body_force_fct_pt () const
Access function: Pointer to body force function (const version)
void enable_inertia ()
Switch on solid inertia.
void disable_inertia ()
Switch off solid inertia.
bool is_inertia_enabled () const
Access function to flag that switches inertia on/off (const version)
virtual unsigned npres_solid () const
virtual int solid_p_local_eqn (const unsigned &i) const
virtual void pin_elemental_redundant_nodal_solid_pressures ()
Pin the element's redundant solid pressures (needed for refinement)
void get_strain (const Vector< double > &s, DenseMatrix< double > &strain) const
Return the strain tensor.
void get_energy (double &pot_en, double &kin_en)
Get potential (strain) and kinetic energy.
void get_deformed_covariant_basis_vectors (const Vector< double > &s, DenseMatrix< double > &def_covariant_basis)
void get_principal_stress (const Vector< double > &s, DenseMatrix< double > &principal_stress_vector, Vector< double > &principal_stress)
virtual void get_isotropic_growth (const unsigned &ipt, const Vector< double > &s, const Vector< double > &xi, double &gamma) const
void body_force (const Vector< double > &xi, Vector< double > &b) const
void enable_evaluate_jacobian_by_fd ()
Set Jacobian to be evaluated by FD? Else: Analytically.
void disable_evaluate_jacobian_by_fd ()
Set Jacobian to be evaluated analytically Else: by FD.
bool is_jacobian_evaluated_by_fd () const
Return the flag indicating whether the jacobian is evaluated by fd.
double prestress (const unsigned &i, const unsigned &j, const Vector< double > xi)
Public Member Functions inherited from oomph::SolidFiniteElement
void set_lagrangian_dimension (const unsigned &lagrangian_dimension)
virtual bool has_internal_solid_data ()
SolidFiniteElement ()
Constructor: Set defaults.
virtual ~SolidFiniteElement ()
Destructor to clean up any allocated memory.
SolidFiniteElement (const SolidFiniteElement &)=delete
Broken copy constructor.
unsigned ngeom_data () const
Broken assignment operator.
Data * geom_data_pt (const unsigned &j)
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_x_and_xi (const Vector< double > &s, Vector< double > &x_fe, Vector< double > &x, Vector< double > &xi_fe, Vector< double > &xi) const
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt, MacroElement *undeformed_macro_elem_pt)
void set_undeformed_macro_elem_pt (MacroElement *undeformed_macro_elem_pt)
MacroElement * undeformed_macro_elem_pt ()
Access function to pointer to "undeformed" macro element.
double dshape_lagrangian (const Vector< double > &s, Shape &psi, DShape &dpsidxi) const
virtual double dshape_lagrangian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidxi) const
double d2shape_lagrangian (const Vector< double > &s, Shape &psi, DShape &dpsidxi, DShape &d2psidxi) const
virtual double d2shape_lagrangian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidxi, DShape &d2psidxi) const
unsigned lagrangian_dimension () const
unsigned nnodal_lagrangian_type () const
Node * construct_node (const unsigned &n)
Construct the local node n and return a pointer to it.
Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
Node * construct_boundary_node (const unsigned &n)
Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
double raw_lagrangian_position (const unsigned &n, const unsigned &i) const
double raw_lagrangian_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double lagrangian_position (const unsigned &n, const unsigned &i) const
Return i-th Lagrangian coordinate at local node n.
double lagrangian_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
virtual double interpolated_xi (const Vector< double > &s, const unsigned &i) const
virtual void interpolated_xi (const Vector< double > &s, Vector< double > &xi) const
virtual void interpolated_dxids (const Vector< double > &s, DenseMatrix< double > &dxids) const
virtual void J_lagrangian (const Vector< double > &s) const
virtual double J_lagrangian_at_knot (const unsigned &ipt) const
SolidInitialCondition *& solid_ic_pt ()
Pointer to object that describes the initial condition.
void enable_solve_for_consistent_newmark_accel ()
void disable_solve_for_consistent_newmark_accel ()
Set to reset the problem being solved to be the standard problem.
MultiplierFctPt & multiplier_fct_pt ()
MultiplierFctPt multiplier_fct_pt () const
virtual void get_residuals_for_solid_ic (Vector< double > &residuals)
void fill_in_residuals_for_solid_ic (Vector< double > &residuals)
void fill_in_jacobian_for_solid_ic (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_for_newmark_accel (DenseMatrix< double > &jacobian)
int position_local_eqn (const unsigned &n, const unsigned &k, const unsigned &j) const
Public Member Functions inherited from oomph::PseudoSolidNodeUpdateElement< GeneralisedNewtonianAxisymmetricTTaylorHoodElement, TPVDElement< 2, 3 > >
PseudoSolidNodeUpdateElement ()
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void compute_norm (double &el_norm)
unsigned required_nvalue (const unsigned &n) const
The required number of values is the sum of the two.
int solid_p_nodal_index () const
void fill_in_contribution_to_residuals (Vector< double > &residuals)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
void evaluate_shape_derivs_by_direct_fd ()
Evaluate shape derivatives by direct finite differencing.
void evaluate_shape_derivs_by_chain_rule ()
Evaluate shape derivatives by chain rule.
void fill_in_shape_derivatives (DenseMatrix< double > &jacobian)
void fill_in_shape_derivatives_by_fd (DenseMatrix< double > &jacobian)
void identify_geometric_data (std::set< Data * > &geometric_data_pt)
void output (std::ostream &outfile)
Overload the output function: Call that of the basic element.
void output (std::ostream &outfile, const unsigned &n_p)
void output (FILE *file_pt)
Overload the output function: Call that of the basic element.
void output (FILE *file_pt, const unsigned &n_p)
Output function is just the same as the basic equations.
unsigned num_Z2_flux_terms ()
void compute_exact_Z2_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_flux_pt, double &error, double &norm)
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
unsigned nrecovery_order ()
unsigned ndof_types () const
unsigned nbasic_dof_types () const
unsigned nsolid_dof_types () const
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement
GeneralisedNewtonianAxisymmetricTTaylorHoodElement ()
Constructor, no internal data points.
GeneralisedNewtonianAxisymmetricTTaylorHoodElement (const GeneralisedNewtonianAxisymmetricTTaylorHoodElement &dummy)=delete
Broken copy constructor.
void operator= (const GeneralisedNewtonianAxisymmetricTTaylorHoodElement &)=delete
Broken assignment operator.
void pshape_axi_nst (const Vector< double > &s, Shape &psi) const
Test whether the pressure dof p_dof hanging or not?
void pshape_axi_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Pressure shape and test functions at local coordinte s.
unsigned p_index_axi_nst ()
Which nodal value represents the pressure?
int p_local_eqn (const unsigned &n) const
Pointer to n_p-th pressure node.
double p_axi_nst (const unsigned &n_p) const
int p_nodal_index_axi_nst () const
Set the value at which the pressure is stored in the nodes.
unsigned npres_axi_nst () const
Return number of pressure values.
void fix_pressure (const unsigned &p_dof, const double &p_value)
Pin p_dof-th pressure dof and set it to value specified by p_value.
void identify_load_data (std::set< std::pair< Data *, unsigned >> &paired_load_data)
void identify_pressure_data (std::set< std::pair< Data *, unsigned >> &paired_pressure_data)
Public Member Functions inherited from oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations
GeneralisedNewtonianAxisymmetricNavierStokesEquations ()
Constructor: NULL the body force and source function.
const double & re () const
Reynolds number.
const double & re_st () const
Product of Reynolds and Strouhal number (=Womersley number)
double *& re_pt ()
Pointer to Reynolds number.
double *& re_st_pt ()
Pointer to product of Reynolds and Strouhal number (=Womersley number)
const double & re_invfr () const
Global inverse Froude number.
double *& re_invfr_pt ()
Pointer to global inverse Froude number.
const double & re_invro () const
Global Reynolds number multiplied by inverse Rossby number.
double *& re_invro_pt ()
Pointer to global inverse Froude number.
const Vector< double > & g () const
Vector of gravitational components.
Vector< double > *& g_pt ()
Pointer to Vector of gravitational components.
const double & density_ratio () const
double *& density_ratio_pt ()
Pointer to Density ratio.
const double & viscosity_ratio () const
double *& viscosity_ratio_pt ()
Pointer to Viscosity Ratio.
GeneralisedNewtonianConstitutiveEquation< 3 > *& constitutive_eqn_pt ()
Access function for the constitutive equation pointer.
void use_current_strainrate_to_compute_second_invariant ()
Switch to fully implict evaluation of non-Newtonian const eqn.
void use_extrapolated_strainrate_to_compute_second_invariant ()
Use extrapolation for non-Newtonian const eqn.
virtual unsigned u_index_axi_nst (const unsigned &i) const
unsigned u_index_nst (const unsigned &i) const
unsigned n_u_nst () const
double du_dt_axi_nst (const unsigned &n, const unsigned &i) const
void disable_ALE ()
void enable_ALE ()
double pressure_integral () const
Integral of pressure over element.
void max_and_min_invariant_and_viscosity (double &min_invariant, double &max_invariant, double &min_viscosity, double &max_viscosity) const
double dissipation () const
Return integral of dissipation over element.
double dissipation (const Vector< double > &s) const
Return dissipation at local coordinate s.
double kin_energy () const
Get integral of kinetic energy over element.
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
void strain_rate (const unsigned &t, const Vector< double > &s, DenseMatrix< double > &strain_rate) const
virtual void extrapolated_strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
virtual void extrapolated_strain_rate (const unsigned &ipt, DenseMatrix< double > &strain_rate) const
void traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction) const
void get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > &press_mass_diag, Vector< double > &veloc_mass_diag, const unsigned &which_one=0)
unsigned nscalar_paraview () const
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
std::string scalar_name_paraview (const unsigned &i) const
void point_output_data (const Vector< double > &s, Vector< double > &data)
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
Compute the element's residual Vector.
void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
void interpolated_u_axi_nst (const Vector< double > &s, Vector< double > &veloc) const
Compute vector of FE interpolated velocity u at local coordinate s.
double interpolated_u_axi_nst (const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s.
double interpolated_u_axi_nst (const unsigned &t, const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s.
virtual void dinterpolated_u_axi_nst_ddata (const Vector< double > &s, const unsigned &i, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
double interpolated_p_axi_nst (const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s.
double interpolated_duds_axi_nst (const Vector< double > &s, const unsigned &i, const unsigned &j) const
double interpolated_dudx_axi_nst (const Vector< double > &s, const unsigned &i, const unsigned &j) const
double interpolated_dudt_axi_nst (const Vector< double > &s, const unsigned &i) const
double interpolated_d_dudx_dX_axi_nst (const Vector< double > &s, const unsigned &p, const unsigned &q, const unsigned &i, const unsigned &k) const
double compute_physical_size () const
Compute the volume of the element.
Public Member Functions inherited from oomph::PseudoSolidNodeUpdateElement< GeneralisedNewtonianTTaylorHoodElement< 2 >, TPVDElement< 2, 3 > >
PseudoSolidNodeUpdateElement ()
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void compute_norm (double &el_norm)
unsigned required_nvalue (const unsigned &n) const
The required number of values is the sum of the two.
int solid_p_nodal_index () const
void fill_in_contribution_to_residuals (Vector< double > &residuals)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
void evaluate_shape_derivs_by_direct_fd ()
Evaluate shape derivatives by direct finite differencing.
void evaluate_shape_derivs_by_chain_rule ()
Evaluate shape derivatives by chain rule.
void fill_in_shape_derivatives (DenseMatrix< double > &jacobian)
void fill_in_shape_derivatives_by_fd (DenseMatrix< double > &jacobian)
void identify_geometric_data (std::set< Data * > &geometric_data_pt)
void output (std::ostream &outfile)
Overload the output function: Call that of the basic element.
void output (std::ostream &outfile, const unsigned &n_p)
void output (FILE *file_pt)
Overload the output function: Call that of the basic element.
void output (FILE *file_pt, const unsigned &n_p)
Output function is just the same as the basic equations.
unsigned num_Z2_flux_terms ()
void compute_exact_Z2_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_flux_pt, double &error, double &norm)
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
unsigned nrecovery_order ()
unsigned ndof_types () const
unsigned nbasic_dof_types () const
unsigned nsolid_dof_types () const
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >
GeneralisedNewtonianTTaylorHoodElement ()
Constructor, no internal data points.
GeneralisedNewtonianTTaylorHoodElement (const GeneralisedNewtonianTTaylorHoodElement< DIM > &dummy)=delete
Broken copy constructor.
void pshape_nst (const Vector< double > &s, Shape &psi) const
Test whether the pressure dof p_dof hanging or not?
void pshape_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Pressure shape and test functions at local coordinte s.
unsigned p_index_nst ()
Which nodal value represents the pressure?
int p_local_eqn (const unsigned &n) const
Pointer to n_p-th pressure node.
double p_nst (const unsigned &n_p) const
double p_nst (const unsigned &t, const unsigned &n_p) const
int p_nodal_index_nst () const
Set the value at which the pressure is stored in the nodes.
unsigned npres_nst () const
Return number of pressure values.
void fix_pressure (const unsigned &p_dof, const double &p_value)
Pin p_dof-th pressure dof and set it to value specified by p_value.
void identify_load_data (std::set< std::pair< Data *, unsigned >> &paired_load_data)
void identify_pressure_data (std::set< std::pair< Data *, unsigned >> &paired_pressure_data)
unsigned npres_nst () const
unsigned npres_nst () const
void pshape_nst (const Vector< double > &s, Shape &psi) const
void pshape_nst (const Vector< double > &s, Shape &psi) const
Public Member Functions inherited from oomph::TElement< DIM, 3 >
const unsigned Node_on_face [3][2]
Assign the nodal translation schemes.
const unsigned Node_on_face [3][3]
const unsigned Node_on_face [3][4]
const unsigned Node_on_face [4][3]
Assign the nodal translation scheme for linear elements.
const unsigned Node_on_face [4][6]
Assign the nodal translation scheme for quadratic elements.
Public Member Functions inherited from oomph::GeneralisedNewtonianNavierStokesEquations< DIM >
GeneralisedNewtonianNavierStokesEquations ()
const double & re () const
Reynolds number.
const double & re_st () const
Product of Reynolds and Strouhal number (=Womersley number)
double *& re_pt ()
Pointer to Reynolds number.
double *& re_st_pt ()
Pointer to product of Reynolds and Strouhal number (=Womersley number)
const double & viscosity_ratio () const
double *& viscosity_ratio_pt ()
Pointer to Viscosity Ratio.
const double & density_ratio () const
double *& density_ratio_pt ()
Pointer to Density ratio.
const double & re_invfr () const
Global inverse Froude number.
double *& re_invfr_pt ()
Pointer to global inverse Froude number.
const Vector< double > & g () const
Vector of gravitational components.
Vector< double > *& g_pt ()
Pointer to Vector of gravitational components.
NavierStokesBodyForceFctPt & body_force_fct_pt ()
Access function for the body-force pointer.
NavierStokesBodyForceFctPt body_force_fct_pt () const
Access function for the body-force pointer. Const version.
NavierStokesSourceFctPt & source_fct_pt ()
Access function for the source-function pointer.
NavierStokesSourceFctPt source_fct_pt () const
Access function for the source-function pointer. Const version.
GeneralisedNewtonianConstitutiveEquation< DIM > *& constitutive_eqn_pt ()
Access function for the constitutive equation pointer.
void use_current_strainrate_to_compute_second_invariant ()
Switch to fully implict evaluation of non-Newtonian const eqn.
void use_extrapolated_strainrate_to_compute_second_invariant ()
Use extrapolation for non-Newtonian const eqn.
double u_nst (const unsigned &n, const unsigned &i) const
double u_nst (const unsigned &t, const unsigned &n, const unsigned &i) const
virtual unsigned u_index_nst (const unsigned &i) const
unsigned n_u_nst () const
double du_dt_nst (const unsigned &n, const unsigned &i) const
void disable_ALE ()
void enable_ALE ()
double pressure_integral () const
Integral of pressure over element.
void max_and_min_invariant_and_viscosity (double &min_invariant, double &max_invariant, double &min_viscosity, double &max_viscosity) const
double dissipation () const
Return integral of dissipation over element.
double dissipation (const Vector< double > &s) const
Return dissipation at local coordinate s.
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
Compute the vorticity vector at local coordinate s.
double kin_energy () const
Get integral of kinetic energy over element.
double d_kin_energy_dt () const
Get integral of time derivative of kinetic energy over element.
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
Strain-rate tensor: 1/2 (du_i/dx_j + du_j/dx_i)
void strain_rate (const unsigned &t, const Vector< double > &s, DenseMatrix< double > &strain_rate) const
virtual void extrapolated_strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
virtual void extrapolated_strain_rate (const unsigned &ipt, DenseMatrix< double > &strain_rate) const
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction)
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction_p, Vector< double > &traction_visc_n, Vector< double > &traction_visc_t)
void get_load (const Vector< double > &s, const Vector< double > &N, Vector< double > &load)
void get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > &press_mass_diag, Vector< double > &veloc_mass_diag, const unsigned &which_one=0)
unsigned nscalar_paraview () const
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
std::string scalar_name_paraview (const unsigned &i) const
void full_output (std::ostream &outfile)
void full_output (std::ostream &outfile, const unsigned &nplot)
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
void output_vorticity (std::ostream &outfile, const unsigned &nplot)
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
Compute the element's residual Vector.
void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
void pin_all_non_pressure_dofs (std::map< Data *, std::vector< int >> &eqn_number_backup)
Pin all non-pressure dofs and backup eqn numbers.
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
void interpolated_u_nst (const Vector< double > &s, Vector< double > &veloc) const
Compute vector of FE interpolated velocity u at local coordinate s.
double interpolated_u_nst (const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s.
double interpolated_u_nst (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void dinterpolated_u_nst_ddata (const Vector< double > &s, const unsigned &i, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
virtual double interpolated_p_nst (const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s.
double interpolated_p_nst (const unsigned &t, const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s at time level t.
void point_output_data (const Vector< double > &s, Vector< double > &data)
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
Compute 3D vorticity vector at local coordinate s.
Public Member Functions inherited from oomph::FSIFluidElement
FSIFluidElement ()
Constructor.
FSIFluidElement (const FSIFluidElement &)=delete
Broken copy constructor.
void operator= (const FSIFluidElement &)=delete
Broken assignment operator.
Public Member Functions inherited from oomph::GeneralisedNewtonianTemplateFreeNavierStokesEquationsBase
GeneralisedNewtonianTemplateFreeNavierStokesEquationsBase ()
Constructor (empty)
virtual ~GeneralisedNewtonianTemplateFreeNavierStokesEquationsBase ()
Virtual destructor (empty)
Public Member Functions inherited from oomph::QTaylorHoodElement< DIM >
QTaylorHoodElement ()
Constructor, no internal data points.
virtual unsigned required_nvalue (const unsigned &n) const
void pshape_nst (const Vector< double > &s, Shape &psi) const
Pressure shape functions at local coordinate s.
void pshape_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Pressure shape and test functions at local coordinte s.
virtual int p_nodal_index_nst () const
Set the value at which the pressure is stored in the nodes.
int p_local_eqn (const unsigned &n) const
Return the local equation numbers for the pressure values.
double p_nst (const unsigned &n_p) const
double p_nst (const unsigned &t, const unsigned &n_p) const
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
unsigned npres_nst () const
Return number of pressure values.
bool is_pressure_node (const unsigned &n) const
Deduce whether or not the provided node is a pressure node.
void fix_pressure (const unsigned &p_dof, const double &p_value)
Pin p_dof-th pressure dof and set it to value specified by p_value.
void build_fp_press_adv_diff_robin_bc_element (const unsigned &face_index)
void identify_load_data (std::set< std::pair< Data *, unsigned >> &paired_load_data)
void identify_pressure_data (std::set< std::pair< Data *, unsigned >> &paired_pressure_data)
void output (std::ostream &outfile)
Redirect output to NavierStokesEquations output.
void output (std::ostream &outfile, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt, const unsigned &nplot)
Redirect output to NavierStokesEquations output.
unsigned ndof_types () const
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
void pshape_nst (const Vector< double > &s, Shape &psi) const
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
void pshape_nst (const Vector< double > &s, Shape &psi) const
Public Member Functions inherited from oomph::NavierStokesEquations< DIM >
NavierStokesEquations ()
const double & re () const
Reynolds number.
const double & re_st () const
Product of Reynolds and Strouhal number (=Womersley number)
double *& re_pt ()
Pointer to Reynolds number.
double *& re_st_pt ()
Pointer to product of Reynolds and Strouhal number (=Womersley number)
const double & viscosity_ratio () const
double *& viscosity_ratio_pt ()
Pointer to Viscosity Ratio.
const double & density_ratio () const
double *& density_ratio_pt ()
Pointer to Density ratio.
const double & re_invfr () const
Global inverse Froude number.
double *& re_invfr_pt ()
Pointer to global inverse Froude number.
const Vector< double > & g () const
Vector of gravitational components.
Vector< double > *& g_pt ()
Pointer to Vector of gravitational components.
NavierStokesBodyForceFctPt & body_force_fct_pt ()
Access function for the body-force pointer.
NavierStokesBodyForceFctPt body_force_fct_pt () const
Access function for the body-force pointer. Const version.
NavierStokesSourceFctPt & source_fct_pt ()
Access function for the source-function pointer.
NavierStokesSourceFctPt source_fct_pt () const
Access function for the source-function pointer. Const version.
NavierStokesPressureAdvDiffSourceFctPt & source_fct_for_pressure_adv_diff ()
NavierStokesPressureAdvDiffSourceFctPt source_fct_for_pressure_adv_diff () const
int & pinned_fp_pressure_eqn ()
double u_nst (const unsigned &n, const unsigned &i) const
double u_nst (const unsigned &t, const unsigned &n, const unsigned &i) const
virtual unsigned u_index_nst (const unsigned &i) const
unsigned n_u_nst () const
double du_dt_nst (const unsigned &n, const unsigned &i) const
void disable_ALE ()
void enable_ALE ()
double pressure_integral () const
Integral of pressure over element.
double dissipation () const
Return integral of dissipation over element.
double dissipation (const Vector< double > &s) const
Return dissipation at local coordinate s.
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
Compute the vorticity vector at local coordinate s.
void get_vorticity (const Vector< double > &s, double &vorticity) const
Compute the scalar vorticity at local coordinate s (2D)
double kin_energy () const
Get integral of kinetic energy over element.
double d_kin_energy_dt () const
Get integral of time derivative of kinetic energy over element.
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
Strain-rate tensor: 1/2 (du_i/dx_j + du_j/dx_i)
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction)
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction_p, Vector< double > &traction_visc_n, Vector< double > &traction_visc_t)
void get_load (const Vector< double > &s, const Vector< double > &N, Vector< double > &load)
void get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > &press_mass_diag, Vector< double > &veloc_mass_diag, const unsigned &which_one=0)
unsigned nscalar_paraview () const
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
std::string scalar_name_paraview (const unsigned &i) const
void full_output (std::ostream &outfile)
void full_output (std::ostream &outfile, const unsigned &nplot)
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
void output_vorticity (std::ostream &outfile, const unsigned &nplot)
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
void compute_norm (Vector< double > &norm)
Compute the vector norm of the FEM solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
Compute the element's residual Vector.
void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
void fill_in_pressure_advection_diffusion_residuals (Vector< double > &residuals)
void fill_in_pressure_advection_diffusion_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void pin_all_non_pressure_dofs (std::map< Data *, std::vector< int >> &eqn_number_backup)
Pin all non-pressure dofs and backup eqn numbers.
void output_pressure_advection_diffusion_robin_elements (std::ostream &outfile)
void delete_pressure_advection_diffusion_robin_elements ()
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
void interpolated_u_nst (const Vector< double > &s, Vector< double > &veloc) const
Compute vector of FE interpolated velocity u at local coordinate s.
double interpolated_u_nst (const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s.
double interpolated_u_nst (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void dinterpolated_u_nst_ddata (const Vector< double > &s, const unsigned &i, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
virtual double interpolated_p_nst (const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s.
double interpolated_p_nst (const unsigned &t, const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s at time level t.
double interpolated_dudx_nst (const Vector< double > &s, const unsigned &i, const unsigned &j) const
void point_output_data (const Vector< double > &s, Vector< double > &data)
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
void get_vorticity (const Vector< double > &s, double &vorticity) const
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
Compute 3D vorticity vector at local coordinate s.
Public Member Functions inherited from oomph::TemplateFreeNavierStokesEquationsBase
TemplateFreeNavierStokesEquationsBase ()
Constructor (empty)
virtual ~TemplateFreeNavierStokesEquationsBase ()
Virtual destructor (empty)
Public Member Functions inherited from oomph::PseudoSolidNodeUpdateElement< TTaylorHoodElement< 2 >, TPVDElement< 2, 3 > >
PseudoSolidNodeUpdateElement ()
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void compute_norm (double &el_norm)
unsigned required_nvalue (const unsigned &n) const
The required number of values is the sum of the two.
int solid_p_nodal_index () const
void fill_in_contribution_to_residuals (Vector< double > &residuals)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
void evaluate_shape_derivs_by_direct_fd ()
Evaluate shape derivatives by direct finite differencing.
void evaluate_shape_derivs_by_chain_rule ()
Evaluate shape derivatives by chain rule.
void fill_in_shape_derivatives (DenseMatrix< double > &jacobian)
void fill_in_shape_derivatives_by_fd (DenseMatrix< double > &jacobian)
void identify_geometric_data (std::set< Data * > &geometric_data_pt)
void output (std::ostream &outfile)
Overload the output function: Call that of the basic element.
void output (std::ostream &outfile, const unsigned &n_p)
void output (FILE *file_pt)
Overload the output function: Call that of the basic element.
void output (FILE *file_pt, const unsigned &n_p)
Output function is just the same as the basic equations.
unsigned num_Z2_flux_terms ()
void compute_exact_Z2_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_flux_pt, double &error, double &norm)
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
unsigned nrecovery_order ()
unsigned ndof_types () const
unsigned nbasic_dof_types () const
unsigned nsolid_dof_types () const
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::TTaylorHoodElement< DIM >
TTaylorHoodElement ()
Constructor, no internal data points.
TTaylorHoodElement (const TTaylorHoodElement< DIM > &dummy)=delete
Broken copy constructor.
void pshape_nst (const Vector< double > &s, Shape &psi) const
Test whether the pressure dof p_dof hanging or not?
void pshape_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Pressure shape and test functions at local coordinte s.
unsigned p_index_nst ()
Which nodal value represents the pressure?
int p_local_eqn (const unsigned &n) const
Pointer to n_p-th pressure node.
double p_nst (const unsigned &n_p) const
double p_nst (const unsigned &t, const unsigned &n_p) const
int p_nodal_index_nst () const
Set the value at which the pressure is stored in the nodes.
unsigned npres_nst () const
Return number of pressure values.
void fix_pressure (const unsigned &p_dof, const double &p_value)
Pin p_dof-th pressure dof and set it to value specified by p_value.
void build_fp_press_adv_diff_robin_bc_element (const unsigned &face_index)
void identify_load_data (std::set< std::pair< Data *, unsigned >> &paired_load_data)
void identify_pressure_data (std::set< std::pair< Data *, unsigned >> &paired_pressure_data)
unsigned npres_nst () const
unsigned npres_nst () const
void pshape_nst (const Vector< double > &s, Shape &psi) const
void pshape_nst (const Vector< double > &s, Shape &psi) const
Private Member Functions
unsigned ndof_types () const
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > &dof_lookup_list) const
Private Attributes
double Error
Storage for elemental error estimate – used for post-processing.
Additional Inherited Members
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Public Types inherited from oomph::PVDEquationsBase< DIM >
typedef void(* IsotropicGrowthFctPt) (const Vector< double > &xi, double &gamma)
typedef double(* PrestressFctPt) (const unsigned &i, const unsigned &j, const Vector< double > &xi)
typedef void(* BodyForceFctPt) (const double &t, const Vector< double > &xi, Vector< double > &b)
Public Types inherited from oomph::SolidFiniteElement
typedef double(* MultiplierFctPt) (const Vector< double > &xi)
Public Types inherited from oomph::GeneralisedNewtonianNavierStokesEquations< DIM >
typedef void(* NavierStokesBodyForceFctPt) (const double &time, const Vector< double > &x, Vector< double > &body_force)
typedef double(* NavierStokesSourceFctPt) (const double &time, const Vector< double > &x)
typedef double(* NavierStokesPressureAdvDiffSourceFctPt) (const Vector< double > &x)
Public Types inherited from oomph::NavierStokesEquations< DIM >
typedef void(* NavierStokesBodyForceFctPt) (const double &time, const Vector< double > &x, Vector< double > &body_force)
typedef double(* NavierStokesSourceFctPt) (const double &time, const Vector< double > &x)
typedef double(* NavierStokesPressureAdvDiffSourceFctPt) (const Vector< double > &x)
Static Public Member Functions inherited from oomph::PVDEquationsBase< DIM >
static void pin_redundant_nodal_solid_pressures (const Vector< GeneralisedElement * > &element_pt)
static void unpin_all_solid_pressure_dofs (const Vector< GeneralisedElement * > &element_pt)
Unpin all pressure dofs in elements listed in vector.
Public Attributes inherited from oomph::AxisymmetricNavierStokesEquations
void(*&)(const double &time, const Vector< double > &x, Vector< double > &f) axi_nst_body_force_fct_pt ()
Access function for the body-force pointer.
double(*&)(const double &time, const Vector< double > &x) source_fct_pt ()
Access function for the source-function pointer.
Public Attributes inherited from oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations
void(*&)(const double &time, const Vector< double > &x, Vector< double > &f) axi_nst_body_force_fct_pt ()
Access function for the body-force pointer.
double(*&)(const double &time, const Vector< double > &x) source_fct_pt ()
Access function for the source-function pointer.
Static Public Attributes inherited from oomph::AxisymmetricNavierStokesEquations
static Vector< double > Gamma
Vector to decide whether the stress-divergence form is used or not.
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Static Public Attributes inherited from oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations
static Vector< double > Gamma
Vector to decide whether the stress-divergence form is used or not.
Static Public Attributes inherited from oomph::GeneralisedNewtonianNavierStokesEquations< DIM >
static Vector< double > Gamma
Vector to decide whether the stress-divergence form is used or not.
Static Public Attributes inherited from oomph::NavierStokesEquations< DIM >
static Vector< double > Gamma
Vector to decide whether the stress-divergence form is used or not.
Static Public Attributes inherited from oomph::TTaylorHoodElement< DIM >
static const unsigned TEMPLATE_PARAMETER_DIM = DIM
Publicly exposed template parameter.
static const unsigned TEMPLATE_PARAMETER_NNODE_1D = 3
Publicly exposed template parameter.
Protected Member Functions inherited from oomph::AxisymmetricTTaylorHoodElement
double dshape_and_dtest_eulerian_axi_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
virtual double dpshape_and_dptest_eulerian_axi_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
void unpin_all_nodal_pressure_dofs ()
Unpin all pressure dofs.
void pin_all_nodal_pressure_dofs ()
Pin all nodal pressure dofs.
void unpin_proper_nodal_pressure_dofs ()
Unpin the proper nodal pressure dofs.
Protected Member Functions inherited from oomph::AxisymmetricNavierStokesEquations
virtual void get_body_force_axi_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &result)
Calculate the body force fct at a given time and Eulerian position.
virtual void get_body_force_gradient_axi_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, DenseMatrix< double > &d_body_force_dx)
double get_source_fct (const double &time, const unsigned &ipt, const Vector< double > &x)
Calculate the source fct at given time and Eulerian position.
virtual void get_source_fct_gradient (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &gradient)
virtual void get_viscosity_ratio_axisym_nst (const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, double &visc_ratio)
virtual void fill_in_generic_residual_contribution_axi_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
virtual void fill_in_generic_dresidual_contribution_axi_nst (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam, unsigned flag)
void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Member Functions inherited from oomph::PVDEquations< DIM >
virtual void fill_in_generic_contribution_to_residuals_pvd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
void get_stress (const DenseMatrix< double > &g, const DenseMatrix< double > &G, DenseMatrix< double > &sigma)
void get_d_stress_dG_upper (const DenseMatrix< double > &g, const DenseMatrix< double > &G, const DenseMatrix< double > &sigma, RankFourTensor< double > &d_sigma_dG)
Protected Member Functions inherited from oomph::SolidFiniteElement
void fill_in_generic_jacobian_for_solid_ic (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
void set_nnodal_lagrangian_type (const unsigned &nlagrangian_type)
virtual double local_to_lagrangian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_lagrangian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_lagrangian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void assign_solid_local_eqn_numbers (const bool &store_local_dof)
Assign local equation numbers for the solid equations in the element.
void describe_solid_local_dofs (std::ostream &out, const std::string &current_string) const
Classifies dofs locally for solid specific aspects.
virtual void fill_in_jacobian_from_solid_position_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_solid_position_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_solid_position_fd ()
virtual void reset_after_solid_position_fd ()
virtual void update_in_solid_position_fd (const unsigned &i)
virtual void reset_in_solid_position_fd (const unsigned &i)
Protected Member Functions inherited from oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement
double dshape_and_dtest_eulerian_axi_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
virtual double dpshape_and_dptest_eulerian_axi_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
void unpin_all_nodal_pressure_dofs ()
Unpin all pressure dofs.
void pin_all_nodal_pressure_dofs ()
Pin all nodal pressure dofs.
void unpin_proper_nodal_pressure_dofs ()
Unpin the proper nodal pressure dofs.
Protected Member Functions inherited from oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations
virtual void get_body_force_axi_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &result)
Calculate the body force fct at a given time and Eulerian position.
virtual void get_body_force_gradient_axi_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, DenseMatrix< double > &d_body_force_dx)
double get_source_fct (const double &time, const unsigned &ipt, const Vector< double > &x)
Calculate the source fct at given time and Eulerian position.
virtual void get_source_fct_gradient (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &gradient)
virtual void get_viscosity_ratio_axisym_nst (const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, double &visc_ratio)
virtual void fill_in_generic_residual_contribution_axi_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
virtual void fill_in_generic_dresidual_contribution_axi_nst (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam, unsigned flag)
void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
Protected Member Functions inherited from oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >
double dshape_and_dtest_eulerian_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
virtual double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
void unpin_all_nodal_pressure_dofs ()
Unpin all pressure dofs.
void pin_all_nodal_pressure_dofs ()
Pin all nodal pressure dofs.
void unpin_proper_nodal_pressure_dofs ()
Unpin the proper nodal pressure dofs.
const unsigned Pconv [3]
const unsigned Pconv [4]
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
Protected Member Functions inherited from oomph::GeneralisedNewtonianNavierStokesEquations< DIM >
virtual void get_body_force_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &result)
virtual void get_body_force_gradient_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, DenseMatrix< double > &d_body_force_dx)
virtual double get_source_nst (const double &time, const unsigned &ipt, const Vector< double > &x)
virtual void get_source_gradient_nst (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &gradient)
virtual void fill_in_generic_residual_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
virtual void fill_in_generic_dresidual_contribution_nst (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam, unsigned flag)
void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
Protected Member Functions inherited from oomph::QTaylorHoodElement< DIM >
double dshape_and_dtest_eulerian_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
const unsigned Pconv [4]
const unsigned Pconv [8]
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
Protected Member Functions inherited from oomph::NavierStokesEquations< DIM >
virtual void get_body_force_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &result)
virtual void get_body_force_gradient_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, DenseMatrix< double > &d_body_force_dx)
virtual double get_source_nst (const double &time, const unsigned &ipt, const Vector< double > &x)
virtual void get_source_gradient_nst (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &gradient)
virtual void fill_in_generic_residual_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
virtual void fill_in_generic_pressure_advection_diffusion_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
virtual void fill_in_generic_dresidual_contribution_nst (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam, unsigned flag)
void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
Protected Member Functions inherited from oomph::TTaylorHoodElement< DIM >
double dshape_and_dtest_eulerian_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
virtual double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
void unpin_all_nodal_pressure_dofs ()
Unpin all pressure dofs.
void pin_all_nodal_pressure_dofs ()
Pin all nodal pressure dofs.
void unpin_proper_nodal_pressure_dofs ()
Unpin the proper nodal pressure dofs.
const unsigned Pconv [3]
const unsigned Pconv [4]
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
Protected Attributes inherited from oomph::AxisymmetricNavierStokesEquations
double * Viscosity_Ratio_pt
double * Density_Ratio_pt
double * Re_pt
Pointer to global Reynolds number.
double * ReSt_pt
Pointer to global Reynolds number x Strouhal number (=Womersley)
double * ReInvFr_pt
double * ReInvRo_pt
Vector< double > * G_pt
Pointer to global gravity Vector.
void(* Body_force_fct_pt)(const double &time, const Vector< double > &x, Vector< double > &result)
Pointer to body force function.
double(* Source_fct_pt)(const double &time, const Vector< double > &x)
Pointer to volumetric source function.
bool ALE_is_disabled
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Protected Attributes inherited from oomph::PVDEquationsBase< DIM >
IsotropicGrowthFctPt Isotropic_growth_fct_pt
Pointer to isotropic growth function.
PrestressFctPt Prestress_fct_pt
Pointer to prestress function.
ConstitutiveLaw * Constitutive_law_pt
Pointer to the constitutive law.
double * Lambda_sq_pt
Timescale ratio (non-dim. density)
bool Unsteady
Flag that switches inertia on/off.
BodyForceFctPt Body_force_fct_pt
Pointer to body force function.
bool Evaluate_jacobian_by_fd
Use FD to evaluate Jacobian.
Protected Attributes inherited from oomph::SolidFiniteElement
MacroElement * Undeformed_macro_elem_pt
Pointer to the element's "undeformed" macro element (NULL by default)
SolidInitialCondition * Solid_ic_pt
Pointer to object that specifies the initial condition.
bool Solve_for_consistent_newmark_accel_flag
Protected Attributes inherited from oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations
double * Viscosity_Ratio_pt
double * Density_Ratio_pt
double * Re_pt
Pointer to global Reynolds number.
double * ReSt_pt
Pointer to global Reynolds number x Strouhal number (=Womersley)
double * ReInvFr_pt
double * ReInvRo_pt
Vector< double > * G_pt
Pointer to global gravity Vector.
void(* Body_force_fct_pt)(const double &time, const Vector< double > &x, Vector< double > &result)
Pointer to body force function.
double(* Source_fct_pt)(const double &time, const Vector< double > &x)
Pointer to volumetric source function.
GeneralisedNewtonianConstitutiveEquation< 3 > * Constitutive_eqn_pt
Pointer to the generalised Newtonian constitutive equation.
bool Use_extrapolated_strainrate_to_compute_second_invariant
bool ALE_is_disabled
Protected Attributes inherited from oomph::GeneralisedNewtonianNavierStokesEquations< DIM >
double * Viscosity_Ratio_pt
double * Density_Ratio_pt
double * Re_pt
Pointer to global Reynolds number.
double * ReSt_pt
Pointer to global Reynolds number x Strouhal number (=Womersley)
double * ReInvFr_pt
Vector< double > * G_pt
Pointer to global gravity Vector.
NavierStokesBodyForceFctPt Body_force_fct_pt
Pointer to body force function.
NavierStokesSourceFctPt Source_fct_pt
Pointer to volumetric source function.
GeneralisedNewtonianConstitutiveEquation< DIM > * Constitutive_eqn_pt
Pointer to the generalised Newtonian constitutive equation.
bool Use_extrapolated_strainrate_to_compute_second_invariant
bool ALE_is_disabled
Protected Attributes inherited from oomph::NavierStokesEquations< DIM >
double * Viscosity_Ratio_pt
double * Density_Ratio_pt
double * Re_pt
Pointer to global Reynolds number.
double * ReSt_pt
Pointer to global Reynolds number x Strouhal number (=Womersley)
double * ReInvFr_pt
Vector< double > * G_pt
Pointer to global gravity Vector.
NavierStokesBodyForceFctPt Body_force_fct_pt
Pointer to body force function.
NavierStokesSourceFctPt Source_fct_pt
Pointer to volumetric source function.
NavierStokesPressureAdvDiffSourceFctPt Press_adv_diff_source_fct_pt
bool ALE_is_disabled
Vector< FpPressureAdvDiffRobinBCElementBase * > Pressure_advection_diffusion_robin_element_pt
int Pinned_fp_pressure_eqn
Static Protected Attributes inherited from oomph::AxisymmetricTTaylorHoodElement
static const unsigned Pconv [] = {0, 1, 2}
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Static Protected Attributes inherited from oomph::PVDEquationsBase< DIM >
static double Default_lambda_sq_value = 1.0
Static default value for timescale ratio (1.0 – for natural scaling)
Static Protected Attributes inherited from oomph::GeneralisedNewtonianAxisymmetricTTaylorHoodElement
static const unsigned Pconv []
Static Protected Attributes inherited from oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations
static bool Pre_multiply_by_viscosity_ratio
Static Protected Attributes inherited from oomph::GeneralisedNewtonianTTaylorHoodElement< DIM >
static const unsigned Pconv []
Static Protected Attributes inherited from oomph::GeneralisedNewtonianNavierStokesEquations< DIM >
static bool Pre_multiply_by_viscosity_ratio = false
Static Protected Attributes inherited from oomph::QTaylorHoodElement< DIM >
static const unsigned Pconv []
Static Protected Attributes inherited from oomph::TTaylorHoodElement< DIM >
static const unsigned Pconv []
Detailed Description
template<unsigned DIM>
class oomph::MyTaylorHoodElement< DIM >
Overload TaylorHood element to modify output.
Overload Navier-Stokes Taylor Hood element to make block preconditionable (again – simply overwrites code that already exists in library to make it more visible for documentation)
Constructor & Destructor Documentation
MyTaylorHoodElement() [1/4]
template<unsigned DIM> oomph::MyTaylorHoodElement< DIM >::MyTaylorHoodElement () inline
Constructor initialise error.
 {}
MyTaylorHoodElement() [2/4]
template<unsigned DIM> oomph::MyTaylorHoodElement< DIM >::MyTaylorHoodElement () inline
Constructor initialise error.
    {
     Error=0.0;
    }
References oomph::MyTaylorHoodElement< DIM >::Error.
MyTaylorHoodElement() [3/4]
template<unsigned DIM> oomph::MyTaylorHoodElement< DIM >::MyTaylorHoodElement () inline
Constructor initialise error.
    {
     Error=0.0;
    }
References Error.
MyTaylorHoodElement() [4/4]
template<unsigned DIM> oomph::MyTaylorHoodElement< DIM >::MyTaylorHoodElement () inline
Constructor initialise error.
    {
     Error=0.0;
    }
References Error.
Member Function Documentation
get_dof_numbers_for_unknowns()
template<unsigned DIM> void oomph::MyTaylorHoodElement< DIM >::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > & dof_lookup_list) const inline private
Create a list of pairs for all unknowns in this element, so the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the "DOF type" that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
   {
    // number of nodes
    unsigned n_node = this->nnode();
    // temporary pair (used to store dof lookup prior to being added to list)
    std::pair<unsigned,unsigned> dof_lookup;
    // loop over the nodes
    for (unsigned j=0;j<n_node;j++)
     {
      // Number of values
      unsigned nvalue=this->node_pt(j)->nvalue();
      //loop over these values
      for (unsigned i=0;i<nvalue;i++)
       {
        // determine local eqn number
        int local_eqn_number = this->nodal_local_eqn(j,i);
        // ignore pinned values - far away degrees of freedom resulting
        // from hanging nodes can be ignored since these are be dealt
        // with by the element containing their master nodes
        if (local_eqn_number >= 0)
         {
          // store dof lookup in temporary pair: Global equation number
          // is the first entry in pair
          dof_lookup.first = this->eqn_number(local_eqn_number);
          // set dof numbers: Dof number is the second entry in pair
          dof_lookup.second = i;
          // add to list
          dof_lookup_list.push_front(dof_lookup);
         }
       }
     }
   }
References i, and j.
ndof_types()
template<unsigned DIM> unsigned oomph::MyTaylorHoodElement< DIM >::ndof_types () const inline private virtual
The number of "DOF types" that degrees of freedom in this element are sub-divided into: Velocity and pressure.
Reimplemented from oomph::GeneralisedElement.
   {
    return DIM+1;
   }
References DIM.
output() [1/4]
template<unsigned DIM> void oomph::MyTaylorHoodElement< DIM >::output (std::ostream & outfile, const unsigned & nplot) inline virtual
Overload output function.
Reimplemented from oomph::FiniteElement.
    {
     // Assign dimension
     unsigned el_dim=2;
     // Vector of local coordinates
     Vector<double> s(el_dim);
     // Tecplot header info
     outfile << tecplot_zone_string(nplot);
     // Find out how many nodes there are
     unsigned n_node = nnode();
     //Set up memory for the shape functions
     Shape psif(n_node);
     DShape dpsifdx(n_node,el_dim);
     // Loop over plot points
     unsigned num_plot_points=nplot_points(nplot);
     for (unsigned iplot=0;iplot<num_plot_points;iplot++)
      {
       // Get local coordinates of plot point
       get_s_plot(iplot,nplot,s);
       // Coordinates
       for(unsigned i=0;i<el_dim;i++)
        {
         outfile << interpolated_x(s,i) << " ";
        }
       for(unsigned i=0;i<el_dim;i++)
        {
         outfile << interpolated_xi(s,i) << " ";
        }
       // Velocities
       for(unsigned i=0;i<3;i++)
        {
         outfile << interpolated_u_axi_nst(s,i) << " ";
        }
       // Pressure
       outfile << interpolated_p_axi_nst(s)  << " ";
       // History values of coordinates
       unsigned n_prev=node_pt(0)->position_time_stepper_pt()->ntstorage();
       for (unsigned t=1;t<n_prev;t++)
        {
         for(unsigned i=0;i<el_dim;i++)
          {
           outfile << interpolated_x(t,s,i) << " ";
          }
        }
       // History values of velocities
       n_prev=node_pt(0)->time_stepper_pt()->ntstorage();
       for (unsigned t=1;t<n_prev;t++)
        {
         for(unsigned i=0;i<3;i++)
          {
           outfile << interpolated_u_axi_nst(t,s,i) << " ";
          }
        }
      }
     // Write tecplot footer (e.g. FE connectivity lists)
     write_tecplot_zone_footer(outfile,nplot);
     }
References el_dim, i, s, and plotPSD::t.
output() [2/4]
template<unsigned DIM> void oomph::MyTaylorHoodElement< DIM >::output (std::ostream & outfile, const unsigned & nplot) inline virtual
Overload output function.
Reimplemented from oomph::FiniteElement.
    {
     // Assign dimension
     unsigned el_dim=2;
     // Vector of local coordinates
     Vector<double> s(el_dim);
     // Acceleration
     Vector<double> dudt(el_dim);
     // Mesh elocity
     Vector<double> mesh_veloc(el_dim,0.0);
     // Tecplot header info
     outfile << tecplot_zone_string(nplot);
     // Find out how many nodes there are
     unsigned n_node = nnode();
     //Set up memory for the shape functions
     Shape psif(n_node);
     DShape dpsifdx(n_node,el_dim);
     // Loop over plot points
     unsigned num_plot_points=nplot_points(nplot);
     for (unsigned iplot=0;iplot<num_plot_points;iplot++)
      {
       // Get local coordinates of plot point
       get_s_plot(iplot,nplot,s);
       //Call the derivatives of the shape and test functions
       dshape_eulerian(s,psif,dpsifdx);
       //Allocate storage
       Vector<double> mesh_veloc(el_dim);
       Vector<double> dudt(el_dim);
       Vector<double> dudt_ALE(el_dim);
       DenseMatrix<double> interpolated_dudx(el_dim,el_dim);
       //Initialise everything to zero
       for(unsigned i=0;i<el_dim;i++)
        {
         mesh_veloc[i]=0.0;
         dudt[i]=0.0;
         dudt_ALE[i]=0.0;
         for(unsigned j=0;j<el_dim;j++)
          {
           interpolated_dudx(i,j) = 0.0;
          }
        }
       //Calculate velocities and derivatives
       //Loop over directions
       for(unsigned i=0;i<el_dim;i++)
        {
         //Get the index at which velocity i is stored
         unsigned u_nodal_index = u_index_nst(i);
         // Loop over nodes
         for(unsigned l=0;l<n_node;l++)
          {
           dudt[i]+=du_dt_nst(l,u_nodal_index)*psif[l];
           mesh_veloc[i]+=dnodal_position_dt(l,i)*psif[l];
           //Loop over derivative directions for velocity gradients
           for(unsigned j=0;j<el_dim;j++)
            {
             interpolated_dudx(i,j) += nodal_value(l,u_nodal_index)*
              dpsifdx(l,j);
            }
          }
        }
       // Get dudt in ALE form (incl mesh veloc)
       for(unsigned i=0;i<el_dim;i++)
        {
         dudt_ALE[i]=dudt[i];
         for (unsigned k=0;k<el_dim;k++)
          {
           dudt_ALE[i]-=mesh_veloc[k]*interpolated_dudx(i,k);
          }
        }
       // Coordinates
       for(unsigned i=0;i<el_dim;i++)
        {
         outfile << interpolated_x(s,i) << " ";
        }
       // Velocities
       for(unsigned i=0;i<el_dim;i++)
        {
         outfile << interpolated_u_nst(s,i) << " ";
        }
       // Pressure
       outfile << interpolated_p_nst(s)  << " ";
       // Accelerations
       for(unsigned i=0;i<el_dim;i++)
        {
         outfile << dudt_ALE[i] << " ";
        }
       // Mesh velocity
       for(unsigned i=0;i<el_dim;i++)
        {
         outfile << mesh_veloc[i] << " ";
        }
       // History values of coordinates
       unsigned n_prev=node_pt(0)->position_time_stepper_pt()->ntstorage();
       for (unsigned t=1;t<n_prev;t++)
        {
         for(unsigned i=0;i<el_dim;i++)
          {
           outfile << interpolated_x(t,s,i) << " ";
          }
        }
       // History values of velocities
       n_prev=node_pt(0)->time_stepper_pt()->ntstorage();
       for (unsigned t=1;t<n_prev;t++)
        {
         for(unsigned i=0;i<el_dim;i++)
          {
           outfile << interpolated_u_nst(t,s,i) << " ";
          }
        }
       outfile << Error << " "
               << size() << std::endl;
      }
     // Write tecplot footer (e.g. FE connectivity lists)
     write_tecplot_zone_footer(outfile,nplot);
     }
References oomph::FiniteElement::dnodal_position_dt(), oomph::FiniteElement::dshape_eulerian(), oomph::NavierStokesEquations< DIM >::du_dt_nst(), el_dim, oomph::MyTaylorHoodElement< DIM >::Error, oomph::FiniteElement::get_s_plot(), i, oomph::NavierStokesEquations< DIM >::interpolated_p_nst(), oomph::NavierStokesEquations< DIM >::interpolated_u_nst(), oomph::FiniteElement::interpolated_x(), j, k, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::nplot_points(), oomph::TimeStepper::ntstorage(), oomph::Node::position_time_stepper_pt(), s, oomph::FiniteElement::size(), plotPSD::t, oomph::FiniteElement::tecplot_zone_string(), oomph::Data::time_stepper_pt(), oomph::NavierStokesEquations< DIM >::u_index_nst(), and oomph::FiniteElement::write_tecplot_zone_footer().
output() [3/4]
template<unsigned DIM> void oomph::MyTaylorHoodElement< DIM >::output (std::ostream & outfile, const unsigned & nplot) inline virtual
Overload output function.
Reimplemented from oomph::FiniteElement.
    {
     // Assign dimension
     unsigned el_dim=2;
     // Vector of local coordinates
     Vector<double> s(el_dim);
     // Acceleration
     Vector<double> dudt(el_dim);
     // Mesh elocity
     Vector<double> mesh_veloc(el_dim,0.0);
     // Tecplot header info
     outfile << tecplot_zone_string(nplot);
     // Find out how many nodes there are
     unsigned n_node = nnode();
     //Set up memory for the shape functions
     Shape psif(n_node);
     DShape dpsifdx(n_node,el_dim);
     // Loop over plot points
     unsigned num_plot_points=nplot_points(nplot);
     for (unsigned iplot=0;iplot<num_plot_points;iplot++)
      {
       // Get local coordinates of plot point
       get_s_plot(iplot,nplot,s);
       //Call the derivatives of the shape and test functions
       dshape_eulerian(s,psif,dpsifdx);
       //Allocate storage
       Vector<double> mesh_veloc(el_dim);
       Vector<double> dudt(el_dim);
       Vector<double> dudt_ALE(el_dim);
       DenseMatrix<double> interpolated_dudx(el_dim,el_dim);
       //Initialise everything to zero
       for(unsigned i=0;i<el_dim;i++)
        {
         mesh_veloc[i]=0.0;
         dudt[i]=0.0;
         dudt_ALE[i]=0.0;
         for(unsigned j=0;j<el_dim;j++)
          {
           interpolated_dudx(i,j) = 0.0;
          }
        }
       //Calculate velocities and derivatives
       //Loop over directions
       for(unsigned i=0;i<el_dim;i++)
        {
         //Get the index at which velocity i is stored
         unsigned u_nodal_index = u_index_nst(i);
         // Loop over nodes
         for(unsigned l=0;l<n_node;l++)
          {
           dudt[i]+=du_dt_nst(l,u_nodal_index)*psif[l];
           mesh_veloc[i]+=dnodal_position_dt(l,i)*psif[l];
           //Loop over derivative directions for velocity gradients
           for(unsigned j=0;j<el_dim;j++)
            {
             interpolated_dudx(i,j) += nodal_value(l,u_nodal_index)*
              dpsifdx(l,j);
            }
          }
        }
       // Get dudt in ALE form (incl mesh veloc)
       for(unsigned i=0;i<el_dim;i++)
        {
         dudt_ALE[i]=dudt[i];
         for (unsigned k=0;k<el_dim;k++)
          {
           dudt_ALE[i]-=mesh_veloc[k]*interpolated_dudx(i,k);
          }
        }
       // Coordinates
       for(unsigned i=0;i<el_dim;i++)
        {
         outfile << interpolated_x(s,i) << " ";
        }
       // Velocities
       for(unsigned i=0;i<el_dim;i++)
        {
         outfile << interpolated_u_nst(s,i) << " ";
        }
       // Pressure
       outfile << interpolated_p_nst(s)  << " ";
       // Accelerations
       for(unsigned i=0;i<el_dim;i++)
        {
         outfile << dudt_ALE[i] << " ";
        }
       // Mesh velocity
       for(unsigned i=0;i<el_dim;i++)
        {
         outfile << mesh_veloc[i] << " ";
        }
       // History values of coordinates
       unsigned n_prev=node_pt(0)->position_time_stepper_pt()->ntstorage();
       for (unsigned t=1;t<n_prev;t++)
        {
         for(unsigned i=0;i<el_dim;i++)
          {
           outfile << interpolated_x(t,s,i) << " ";
          }
        }
       // History values of velocities
       n_prev=node_pt(0)->time_stepper_pt()->ntstorage();
       for (unsigned t=1;t<n_prev;t++)
        {
         for(unsigned i=0;i<el_dim;i++)
          {
           outfile << interpolated_u_nst(t,s,i) << " ";
          }
        }
       outfile << Error << " "
               << size() << std::endl;
      }
     // Write tecplot footer (e.g. FE connectivity lists)
     write_tecplot_zone_footer(outfile,nplot);
    }
References el_dim, Error, i, j, k, s, size, and plotPSD::t.
output() [4/4]
template<unsigned DIM> void oomph::MyTaylorHoodElement< DIM >::output (std::ostream & outfile, const unsigned & nplot) inline virtual
Overload output function.
Reimplemented from oomph::FiniteElement.
    {
     // Assign dimension
     unsigned el_dim=2;
     // Vector of local coordinates
     Vector<double> s(el_dim);
     // Acceleration
     Vector<double> dudt(el_dim);
     // Mesh elocity
     Vector<double> mesh_veloc(el_dim,0.0);
     // Tecplot header info
     outfile << tecplot_zone_string(nplot);
     // Find out how many nodes there are
     unsigned n_node = nnode();
     //Set up memory for the shape functions
     Shape psif(n_node);
     DShape dpsifdx(n_node,el_dim);
     // Loop over plot points
     unsigned num_plot_points=nplot_points(nplot);
     for (unsigned iplot=0;iplot<num_plot_points;iplot++)
      {
       // Get local coordinates of plot point
       get_s_plot(iplot,nplot,s);
       //Call the derivatives of the shape and test functions
       dshape_eulerian(s,psif,dpsifdx);
       //Allocate storage
       Vector<double> mesh_veloc(el_dim);
       Vector<double> dudt(el_dim);
       Vector<double> dudt_ALE(el_dim);
       DenseMatrix<double> interpolated_dudx(el_dim,el_dim);
       //Initialise everything to zero
       for(unsigned i=0;i<el_dim;i++)
        {
         mesh_veloc[i]=0.0;
         dudt[i]=0.0;
         dudt_ALE[i]=0.0;
         for(unsigned j=0;j<el_dim;j++)
          {
           interpolated_dudx(i,j) = 0.0;
          }
        }
       //Calculate velocities and derivatives
       //Loop over directions
       for(unsigned i=0;i<el_dim;i++)
        {
         //Get the index at which velocity i is stored
         unsigned u_nodal_index = u_index_nst(i);
         // Loop over nodes
         for(unsigned l=0;l<n_node;l++)
          {
           dudt[i]+=du_dt_nst(l,u_nodal_index)*psif[l];
           mesh_veloc[i]+=dnodal_position_dt(l,i)*psif[l];
           //Loop over derivative directions for velocity gradients
           for(unsigned j=0;j<el_dim;j++)
            {
             interpolated_dudx(i,j) += nodal_value(l,u_nodal_index)*
              dpsifdx(l,j);
            }
          }
        }
       // Get dudt in ALE form (incl mesh veloc)
       for(unsigned i=0;i<el_dim;i++)
        {
         dudt_ALE[i]=dudt[i];
         for (unsigned k=0;k<el_dim;k++)
          {
           dudt_ALE[i]-=mesh_veloc[k]*interpolated_dudx(i,k);
          }
        }
       // Coordinates
       for(unsigned i=0;i<el_dim;i++)
        {
         outfile << interpolated_x(s,i) << " ";
        }
       // Velocities
       for(unsigned i=0;i<el_dim;i++)
        {
         outfile << interpolated_u_nst(s,i) << " ";
        }
       // Pressure
       outfile << interpolated_p_nst(s)  << " ";
       // Accelerations
       for(unsigned i=0;i<el_dim;i++)
        {
         outfile << dudt_ALE[i] << " ";
        }
       // Mesh velocity
       for(unsigned i=0;i<el_dim;i++)
        {
         outfile << mesh_veloc[i] << " ";
        }
       // History values of coordinates
       unsigned n_prev=node_pt(0)->position_time_stepper_pt()->ntstorage();
       for (unsigned t=1;t<n_prev;t++)
        {
         for(unsigned i=0;i<el_dim;i++)
          {
           outfile << interpolated_x(t,s,i) << " ";
          }
        }
       // History values of velocities
       n_prev=node_pt(0)->time_stepper_pt()->ntstorage();
       for (unsigned t=1;t<n_prev;t++)
        {
         for(unsigned i=0;i<el_dim;i++)
          {
           outfile << interpolated_u_nst(t,s,i) << " ";
          }
        }
       // Velocity gradients
       for(unsigned i=0;i<el_dim;i++)
        {
         for(unsigned j=0;j<el_dim;j++)
          {
           outfile << interpolated_dudx(i,j) << " ";
          }
        }
       outfile << Error << " "
               << size() << std::endl;
      }
     // Write tecplot footer (e.g. FE connectivity lists)
     write_tecplot_zone_footer(outfile,nplot);
     }
References el_dim, Error, i, j, k, s, size, and plotPSD::t.
set_error() [1/3]
template<unsigned DIM> void oomph::MyTaylorHoodElement< DIM >::set_error (const double & error) inline
Set error value for post-processing.
 {Error=error;}
References calibrate::error, and oomph::MyTaylorHoodElement< DIM >::Error.
set_error() [2/3]
template<unsigned DIM> void oomph::MyTaylorHoodElement< DIM >::set_error (const double & error) inline
Set error value for post-processing.
 {Error=error;}
References calibrate::error, and Error.
set_error() [3/3]
template<unsigned DIM> void oomph::MyTaylorHoodElement< DIM >::set_error (const double & error) inline
Set error value for post-processing.
 {Error=error;}
References calibrate::error, and Error.
square_of_l2_norm() [1/3]
template<unsigned DIM> double oomph::MyTaylorHoodElement< DIM >::square_of_l2_norm () inline
Get square of L2 norm of velocity.
    {
     // Assign dimension
     unsigned el_dim=2;
     // Initalise
     double sum=0.0;
     //Find out how many nodes there are
     unsigned n_node = nnode();
     //Find the indices at which the local velocities are stored
     unsigned u_nodal_index[el_dim];
     for(unsigned i=0;i<el_dim;i++) {u_nodal_index[i] = u_index_nst(i);}
     //Set up memory for the velocity shape fcts
     Shape psif(n_node);
     DShape dpsidx(n_node,el_dim);
     //Number of integration points
     unsigned n_intpt = integral_pt()->nweight();
     //Set the Vector to hold local coordinates
     Vector<double> s(el_dim);
     //Loop over the integration points
     for(unsigned ipt=0;ipt<n_intpt;ipt++)
      {
       //Assign values of s
       for(unsigned i=0;i<el_dim;i++) s[i] = integral_pt()->knot(ipt,i);
       //Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Call the derivatives of the veloc shape functions
       // (Derivs not needed but they are free)
       double J = this->dshape_eulerian_at_knot(ipt,psif,dpsidx);
       //Premultiply the weights and the Jacobian
       double W = w*J;
       //Calculate velocities
       Vector<double> interpolated_u(el_dim,0.0);
       // Loop over nodes
       for(unsigned l=0;l<n_node;l++)
        {
         //Loop over directions
         for(unsigned i=0;i<el_dim;i++)
          {
           //Get the nodal value
           double u_value = raw_nodal_value(l,u_nodal_index[i]);
           interpolated_u[i] += u_value*psif[l];
          }
        }
       //Assemble square of L2 norm
       for(unsigned i=0;i<el_dim;i++)
        {
         sum+=interpolated_u[i]*interpolated_u[i]*W;
        }
      }
     return sum;
    }
References oomph::FiniteElement::dshape_eulerian_at_knot(), el_dim, i, oomph::FiniteElement::integral_pt(), J, oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::Integral::nweight(), oomph::FiniteElement::raw_nodal_value(), s, oomph::NavierStokesEquations< DIM >::u_index_nst(), w, oomph::QuadTreeNames::W, and oomph::Integral::weight().
square_of_l2_norm() [2/3]
template<unsigned DIM> double oomph::MyTaylorHoodElement< DIM >::square_of_l2_norm () inline
Get square of L2 norm of velocity.
    {
     // Assign dimension
     unsigned el_dim=2;
     // Initalise
     double sum=0.0;
     //Find out how many nodes there are
     unsigned n_node = nnode();
     //Find the indices at which the local velocities are stored
     unsigned u_nodal_index[el_dim];
     for(unsigned i=0;i<el_dim;i++) {u_nodal_index[i] = u_index_nst(i);}
     //Set up memory for the velocity shape fcts
     Shape psif(n_node);
     DShape dpsidx(n_node,el_dim);
     //Number of integration points
     unsigned n_intpt = integral_pt()->nweight();
     //Set the Vector to hold local coordinates
     Vector<double> s(el_dim);
     //Loop over the integration points
     for(unsigned ipt=0;ipt<n_intpt;ipt++)
      {
       //Assign values of s
       for(unsigned i=0;i<el_dim;i++) s[i] = integral_pt()->knot(ipt,i);
       //Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Call the derivatives of the veloc shape functions
       // (Derivs not needed but they are free)
       double J = this->dshape_eulerian_at_knot(ipt,psif,dpsidx);
       //Premultiply the weights and the Jacobian
       double W = w*J;
       //Calculate velocities
       Vector<double> interpolated_u(el_dim,0.0);
       // Loop over nodes
       for(unsigned l=0;l<n_node;l++)
        {
         //Loop over directions
         for(unsigned i=0;i<el_dim;i++)
          {
           //Get the nodal value
           double u_value = raw_nodal_value(l,u_nodal_index[i]);
           interpolated_u[i] += u_value*psif[l];
          }
        }
       //Assemble square of L2 norm
       for(unsigned i=0;i<el_dim;i++)
        {
         sum+=interpolated_u[i]*interpolated_u[i]*W;
        }
      }
     return sum;
    }
References el_dim, i, J, s, w, and oomph::QuadTreeNames::W.
square_of_l2_norm() [3/3]
template<unsigned DIM> double oomph::MyTaylorHoodElement< DIM >::square_of_l2_norm () inline
Get square of L2 norm of velocity.
    {
     // Assign dimension
     unsigned el_dim=2;
     // Initalise
     double sum=0.0;
     //Find out how many nodes there are
     unsigned n_node = nnode();
     //Find the indices at which the local velocities are stored
     unsigned u_nodal_index[el_dim];
     for(unsigned i=0;i<el_dim;i++) {u_nodal_index[i] = u_index_nst(i);}
     //Set up memory for the velocity shape fcts
     Shape psif(n_node);
     DShape dpsidx(n_node,el_dim);
     //Number of integration points
     unsigned n_intpt = integral_pt()->nweight();
     //Set the Vector to hold local coordinates
     Vector<double> s(el_dim);
     //Loop over the integration points
     for(unsigned ipt=0;ipt<n_intpt;ipt++)
      {
       //Assign values of s
       for(unsigned i=0;i<el_dim;i++) s[i] = integral_pt()->knot(ipt,i);
       //Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Call the derivatives of the veloc shape functions
       // (Derivs not needed but they are free)
       double J = this->dshape_eulerian_at_knot(ipt,psif,dpsidx);
       //Premultiply the weights and the Jacobian
       double W = w*J;
       //Calculate velocities
       Vector<double> interpolated_u(el_dim,0.0);
       // Loop over nodes
       for(unsigned l=0;l<n_node;l++)
        {
         //Loop over directions
         for(unsigned i=0;i<el_dim;i++)
          {
           //Get the nodal value
           double u_value = raw_nodal_value(l,u_nodal_index[i]);
           interpolated_u[i] += u_value*psif[l];
          }
        }
       //Assemble square of L2 norm
       for(unsigned i=0;i<el_dim;i++)
        {
         sum+=interpolated_u[i]*interpolated_u[i]*W;
        }
      }
     return sum;
    }
References el_dim, i, J, s, w, and oomph::QuadTreeNames::W.
variable_identifier() [1/3]
template<unsigned DIM> std::string oomph::MyTaylorHoodElement< DIM >::variable_identifier () inline
Return variable identifier.
    {
     std::string txt="VARIABLES=";
     txt+="\"x\",";
     txt+="\"y\",";
     txt+="\"u\",";
     txt+="\"v\",";
     txt+="\"p\",";
     txt+="\"du/dt\",";
     txt+="\"dv/dt\",";
     txt+="\"u_m\",";
     txt+="\"v_m\",";
     txt+="\"x_h1\",";
     txt+="\"y_h1\",";
     txt+="\"x_h2\",";
     txt+="\"y_h2\",";
     txt+="\"u_h1\",";
     txt+="\"v_h1\",";
     txt+="\"u_h2\",";
     txt+="\"v_h2\",";
     txt+="\"error\",";
     txt+="\"size\",";
     txt+="\n";
     return txt;
    }
References oomph::Global_string_for_annotation::string().
variable_identifier() [2/3]
template<unsigned DIM> std::string oomph::MyTaylorHoodElement< DIM >::variable_identifier () inline
Return variable identifier.
    {
     std::string txt="VARIABLES=";
     txt+="\"x\",";
     txt+="\"y\",";
     txt+="\"u\",";
     txt+="\"v\",";
     txt+="\"p\",";
     txt+="\"du/dt\",";
     txt+="\"dv/dt\",";
     txt+="\"u_m\",";
     txt+="\"v_m\",";
     txt+="\"x_h1\",";
     txt+="\"y_h1\",";
     txt+="\"x_h2\",";
     txt+="\"y_h2\",";
     txt+="\"u_h1\",";
     txt+="\"v_h1\",";
     txt+="\"u_h2\",";
     txt+="\"v_h2\",";
     txt+="\"error\",";
     txt+="\"size\",";
     txt+="\n";
     return txt;
    }
References oomph::Global_string_for_annotation::string().
variable_identifier() [3/3]
template<unsigned DIM> std::string oomph::MyTaylorHoodElement< DIM >::variable_identifier () inline
Return variable identifier.
    {
     std::string txt="VARIABLES=";
     txt+="\"x\",";
     txt+="\"y\",";
     txt+="\"u\",";
     txt+="\"v\",";
     txt+="\"p\",";
     txt+="\"du/dt\",";
     txt+="\"dv/dt\",";
     txt+="\"u_m\",";
     txt+="\"v_m\",";
     txt+="\"x_h1\",";
     txt+="\"y_h1\",";
     txt+="\"x_h2\",";
     txt+="\"y_h2\",";
     txt+="\"u_h1\",";
     txt+="\"v_h1\",";
     txt+="\"u_h2\",";
     txt+="\"v_h2\",";
     txt+="\"du/dx\",";
     txt+="\"du/dy\",";
     txt+="\"dv/dx\",";
     txt+="\"dv/dy\",";
     txt+="\"error\",";
     txt+="\"size\",";
     txt+="\n";
     return txt;
    }
References oomph::Global_string_for_annotation::string().
Member Data Documentation
Error
template<unsigned DIM> double MyTaylorHoodElement::Error private
Storage for elemental error estimate – used for post-processing.
Referenced by oomph::MyTaylorHoodElement< DIM >::MyTaylorHoodElement(), oomph::MyTaylorHoodElement< DIM >::output(), and oomph::MyTaylorHoodElement< DIM >::set_error().
The documentation for this class was generated from the following files:
pressure_driven_torus.cc
my_taylor_hood_elements.h
unstructured_adaptive_ALE.cc
adaptive_bubble_in_channel.cc
driven_cavity_with_simple_lsc_preconditioner.cc