MercuryDPM: oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM > Class Template Reference
oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM > Class Template Reference abstract
#include <advection_diffusion_reaction_elements.h>
Public Types
typedef void(* AdvectionDiffusionReactionSourceFctPt) (const Vector< double > &x, Vector< double > &f)
typedef void(* AdvectionDiffusionReactionReactionFctPt) (const Vector< double > &c, Vector< double > &R)
Function pointer to reaction terms.
typedef void(* AdvectionDiffusionReactionReactionDerivFctPt) (const Vector< double > &c, DenseMatrix< double > &dRdC)
Function pointer to derivative of reaction terms.
typedef void(* AdvectionDiffusionReactionWindFctPt) (const double &time, const Vector< double > &x, Vector< double > &wind)
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Public Member Functions
AdvectionDiffusionReactionEquations ()
AdvectionDiffusionReactionEquations (const AdvectionDiffusionReactionEquations &dummy)=delete
Broken copy constructor.
void operator= (const AdvectionDiffusionReactionEquations &)=delete
Broken assignment operator.
virtual unsigned c_index_adv_diff_react (const unsigned &i) const
double dc_dt_adv_diff_react (const unsigned &n, const unsigned &r) const
void dc_dt_adv_diff_react (const unsigned &n, Vector< double > &dc_dt) const
void disable_ALE ()
void enable_ALE ()
void output (std::ostream &outfile)
Output with default number of plot points.
void output (std::ostream &outfile, const unsigned &nplot)
void output (FILE *file_pt)
C_style output with default number of plot points.
void output (FILE *file_pt, const unsigned &n_plot)
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: x,y,u_exact or x,y,z,u_exact at nplot^DIM plot points.
virtual void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
void compute_norm (double &norm)
Compute norm of the solution: sum of squares of L2 norms for reagents.
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Get error against and norm of exact solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Dummy, time dependent error checker.
AdvectionDiffusionReactionSourceFctPt & source_fct_pt ()
Access function: Pointer to source function.
AdvectionDiffusionReactionSourceFctPt source_fct_pt () const
Access function: Pointer to source function. Const version.
AdvectionDiffusionReactionWindFctPt & wind_fct_pt ()
Access function: Pointer to wind function.
AdvectionDiffusionReactionWindFctPt wind_fct_pt () const
Access function: Pointer to reaction function. Const version.
AdvectionDiffusionReactionReactionFctPt & reaction_fct_pt ()
Access function: Pointer to reaction function.
AdvectionDiffusionReactionReactionFctPt reaction_fct_pt () const
Access function: Pointer to reaction function. Const version.
AdvectionDiffusionReactionReactionDerivFctPt & reaction_deriv_fct_pt ()
Access function: Pointer to reaction derivatives function.
AdvectionDiffusionReactionReactionDerivFctPt reaction_deriv_fct_pt () const
Access function: Pointer to reaction function. Const version.
const Vector< double > & diff () const
Vector of diffusion coefficients.
Vector< double > *& diff_pt ()
Pointer to vector of diffusion coefficients.
const Vector< double > & tau () const
Vector of dimensionless timescales.
Vector< double > *& tau_pt ()
Pointer to vector of dimensionless timescales.
virtual void get_source_adv_diff_react (const unsigned &ipt, const Vector< double > &x, Vector< double > &source) const
virtual void get_wind_adv_diff_react (const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &wind) const
virtual void get_reaction_adv_diff_react (const unsigned &ipt, const Vector< double > &C, Vector< double > &R) const
virtual void get_reaction_deriv_adv_diff_react (const unsigned &ipt, const Vector< double > &C, DenseMatrix< double > &dRdC) const
void get_flux (const Vector< double > &s, Vector< double > &flux) const
Get flux: \(\mbox{flux}[DIM r + i] = \mbox{d}C_{r} / \mbox{d}x_i \).
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector (wrapper)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
double interpolated_c_adv_diff_react (const Vector< double > &s, const unsigned &i) const
Return FE representation of function value c_i(s) at local coordinate s.
unsigned self_test ()
Self-test: Return 0 for OK.
void integrate_reagents (Vector< double > &C) const
Return the integrated reagent concentrations.
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual unsigned nvertex_node () const
virtual Node * vertex_node_pt (const unsigned &j) const
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Protected Member Functions
virtual double dshape_and_dtest_eulerian_adv_diff_react (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
virtual double dshape_and_dtest_eulerian_at_knot_adv_diff_react (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
virtual void fill_in_generic_residual_contribution_adv_diff_react (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Attributes
Vector< double > * Diff_pt
Pointer to global diffusion coefficients.
Vector< double > * Tau_pt
Pointer to global timescales.
AdvectionDiffusionReactionSourceFctPt Source_fct_pt
Pointer to source function:
AdvectionDiffusionReactionWindFctPt Wind_fct_pt
Pointer to wind function:
AdvectionDiffusionReactionReactionFctPt Reaction_fct_pt
Pointer to reaction function.
AdvectionDiffusionReactionReactionDerivFctPt Reaction_deriv_fct_pt
Pointer to reaction derivatives.
bool ALE_is_disabled
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Static Protected Attributes
static const unsigned N_reagent
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Static Private Attributes
static Vector< double > Default_dimensionless_number
Static default value for the dimensionless numbers.
Additional Inherited Members
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Detailed Description
template<unsigned NREAGENT, unsigned DIM>
class oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >
A class for all elements that solve the Advection Diffusion Reaction equations using isoparametric elements.
\[ \tau_{i} \frac{\partial C_{i}}{\partial t} + w_{j} \frac{\partial C_{i}}{\partial x_{j}} = D_{i}\frac{\partial^2 C_{i}}{\partial x_j^2} = - R_{i}(C_{i}) + f_{i} \]
This contains the generic maths. Shape functions, geometric mapping etc. must get implemented in derived class.
Member Typedef Documentation
AdvectionDiffusionReactionReactionDerivFctPt
template<unsigned NREAGENT, unsigned DIM> typedef void(* oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::AdvectionDiffusionReactionReactionDerivFctPt) (const Vector< double > &c, DenseMatrix< double > &dRdC)
Function pointer to derivative of reaction terms.
AdvectionDiffusionReactionReactionFctPt
template<unsigned NREAGENT, unsigned DIM> typedef void(* oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::AdvectionDiffusionReactionReactionFctPt) (const Vector< double > &c, Vector< double > &R)
Function pointer to reaction terms.
AdvectionDiffusionReactionSourceFctPt
template<unsigned NREAGENT, unsigned DIM> typedef void(* oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::AdvectionDiffusionReactionSourceFctPt) (const Vector< double > &x, Vector< double > &f)
Function pointer to source function fct(x,f(x)) – x is a Vector!
AdvectionDiffusionReactionWindFctPt
template<unsigned NREAGENT, unsigned DIM> typedef void(* oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::AdvectionDiffusionReactionWindFctPt) (const double &time, const Vector< double > &x, Vector< double > &wind)
Function pointer to wind function fct(x,w(x)) – x is a Vector!
Constructor & Destructor Documentation
AdvectionDiffusionReactionEquations() [1/2]
template<unsigned NREAGENT, unsigned DIM> oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::AdvectionDiffusionReactionEquations () inline
Constructor: Initialise the Source_fct_pt, Wind_fct_pt, Reaction_fct_pt to null and initialise the dimensionless timescale and diffusion ratios
       : Source_fct_pt(0),
         Wind_fct_pt(0),
         Reaction_fct_pt(0),
         Reaction_deriv_fct_pt(0),
         ALE_is_disabled(false)
     {
       // Set diffusion coefficients to default
       Diff_pt = &Default_dimensionless_number;
       // Set timescales to default
       Tau_pt = &Default_dimensionless_number;
     }
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::Default_dimensionless_number, oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::Diff_pt, and oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::Tau_pt.
AdvectionDiffusionReactionEquations() [2/2]
template<unsigned NREAGENT, unsigned DIM> oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::AdvectionDiffusionReactionEquations (const AdvectionDiffusionReactionEquations< NREAGENT, DIM > & dummy) delete
Broken copy constructor.
Member Function Documentation
c_index_adv_diff_react()
template<unsigned NREAGENT, unsigned DIM> virtual unsigned oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::c_index_adv_diff_react (const unsigned & i) const inline virtual
Return the index at which the unknown i-th reagent is stored. The default value, i, is appropriate for single-physics problems, when there are only i variables, the values that satisfies the advection-diffusion-reaction equation. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknown is always stored at the same index at each node.
Reimplemented in oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, and oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >.
     {
       return i;
     }
References i.
Referenced by oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::dc_dt_adv_diff_react(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::get_flux(), oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >::get_interpolated_values(), and oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::interpolated_c_adv_diff_react().
compute_error() [1/2]
template<unsigned NREAGENT, unsigned DIM> void oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) virtual
Get error against and norm of exact solution.
Validate against exact solution
Solution is provided via function pointer. Plot error at a given number of plot points.
Reimplemented from oomph::FiniteElement.
   {
     // Initialise
     error = 0.0;
     norm = 0.0;
     // Vector of local coordinates
     Vector<double> s(DIM);
     // Vector for coordintes
     Vector<double> x(DIM);
     // Find out how many nodes there are in the element
     unsigned n_node = nnode();
     Shape psi(n_node);
     // Set the value of n_intpt
     unsigned n_intpt = integral_pt()->nweight();
     // Tecplot header info
     outfile << "ZONE" << std::endl;
     // Exact solution Vector (here a scalar)
     Vector<double> exact_soln(1);
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Assign values of s
       for (unsigned i = 0; i < DIM; i++)
       {
         s[i] = integral_pt()->knot(ipt, i);
       }
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Get jacobian of mapping
       double J = J_eulerian(s);
       // Premultiply the weights and the Jacobian
       double W = w * J;
       // Get x position as Vector
       interpolated_x(s, x);
       // Get FE function value
       double u_fe = interpolated_c_adv_diff_react(s, 0);
       // Get exact solution at this point
       (*exact_soln_pt)(x, exact_soln);
       // Output x,y,...,error
       for (unsigned i = 0; i < DIM; i++)
       {
         outfile << x[i] << " ";
       }
       outfile << exact_soln[0] << " " << exact_soln[0] - u_fe << std::endl;
       // Add to error and norm
       norm += exact_soln[0] * exact_soln[0] * W;
       error += (exact_soln[0] - u_fe) * (exact_soln[0] - u_fe) * W;
     }
   }
References DIM, calibrate::error, ProblemParameters::exact_soln(), i, J, s, w, oomph::QuadTreeNames::W, and plotDoE::x.
compute_error() [2/2]
template<unsigned NREAGENT, unsigned DIM> void oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) inline virtual
Dummy, time dependent error checker.
Reimplemented from oomph::FiniteElement.
     {
       throw OomphLibError(
         "No time-dependent compute_error() for Advection Diffusion elements",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
compute_norm()
template<unsigned NREAGENT, unsigned DIM> void oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::compute_norm (double & norm) virtual
Compute norm of the solution: sum of squares of L2 norms for reagents.
Compute norm of the solution: sum of squares of the L2 norm for each reagent
Reimplemented from oomph::GeneralisedElement.
   {
     // Initialise
     norm = 0.0;
     // Vector of local coordinates
     Vector<double> s(DIM);
     // Solution
     double c = 0.0;
     // Find out how many nodes there are in the element
     unsigned n_node = this->nnode();
     Shape psi(n_node);
     // Set the value of n_intpt
     unsigned n_intpt = this->integral_pt()->nweight();
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Assign values of s
       for (unsigned i = 0; i < DIM; i++)
       {
         s[i] = this->integral_pt()->knot(ipt, i);
       }
       // Get the integral weight
       double w = this->integral_pt()->weight(ipt);
       // Get jacobian of mapping
       double J = this->J_eulerian(s);
       // Premultiply the weights and the Jacobian
       double W = w * J;
       // Loop over all reagents
       for (unsigned r = 0; r < NREAGENT; ++r)
       {
         // Get FE function value
         c = this->interpolated_c_adv_diff_react(s, r);
         // Add to  norm
         norm += c * c * W;
       }
     }
   }
References calibrate::c, DIM, i, J, UniformPSDSelfTest::r, s, w, and oomph::QuadTreeNames::W.
dc_dt_adv_diff_react() [1/2]
template<unsigned NREAGENT, unsigned DIM> double oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::dc_dt_adv_diff_react (const unsigned & n, const unsigned & r) const inline
dc_r/dt at local node n. Uses suitably interpolated value for hanging nodes.
     {
       // Get the data's timestepper
       TimeStepper* time_stepper_pt = this->node_pt(n)->time_stepper_pt();
       // Initialise dudt
       double dudt = 0.0;
       // Loop over the timesteps, if there is a non Steady timestepper
       if (!time_stepper_pt->is_steady())
       {
         // Find the index at which the variable is stored
         const unsigned c_nodal_index = c_index_adv_diff_react(r);
         // Number of timsteps (past & present)
         const unsigned n_time = time_stepper_pt->ntstorage();
         for (unsigned t = 0; t < n_time; t++)
         {
           dudt +=
             time_stepper_pt->weight(1, t) * nodal_value(t, n, c_nodal_index);
         }
       }
       return dudt;
     }
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::c_index_adv_diff_react(), oomph::TimeStepper::is_steady(), n, oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), UniformPSDSelfTest::r, plotPSD::t, oomph::GeomObject::time_stepper_pt(), oomph::Data::time_stepper_pt(), and oomph::TimeStepper::weight().
dc_dt_adv_diff_react() [2/2]
template<unsigned NREAGENT, unsigned DIM> void oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::dc_dt_adv_diff_react (const unsigned & n, Vector< double > & dc_dt) const inline
dc/dt at local node n. Uses suitably interpolated value for hanging nodes.
     {
       // Get the data's timestepper
       TimeStepper* time_stepper_pt = this->node_pt(n)->time_stepper_pt();
       // Initialise to zero
       for (unsigned r = 0; r < NREAGENT; r++)
       {
         dc_dt[r] = 0.0;
       }
       // Loop over the timesteps, if there is a non Steady timestepper
       if (!time_stepper_pt->is_steady())
       {
         // Number of timsteps (past & present)
         const unsigned n_time = time_stepper_pt->ntstorage();
         // Local storage (cache) for the weights
         double weight[n_time];
         for (unsigned t = 0; t < n_time; t++)
         {
           weight[t] = time_stepper_pt->weight(1, t);
         }
         // Loop over the reagents
         for (unsigned r = 0; r < NREAGENT; r++)
         {
           // Find the index at which the variable is stored
           const unsigned c_nodal_index = c_index_adv_diff_react(r);
           for (unsigned t = 0; t < n_time; t++)
           {
             dc_dt[r] += weight[t] * nodal_value(t, n, c_nodal_index);
           }
         }
       }
     }
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::c_index_adv_diff_react(), oomph::TimeStepper::is_steady(), n, oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), UniformPSDSelfTest::r, plotPSD::t, oomph::GeomObject::time_stepper_pt(), oomph::Data::time_stepper_pt(), and oomph::TimeStepper::weight().
diff()
template<unsigned NREAGENT, unsigned DIM> const Vector<double>& oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::diff () const inline
Vector of diffusion coefficients.
     {
       return *Diff_pt;
     }
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::Diff_pt.
diff_pt()
template<unsigned NREAGENT, unsigned DIM> Vector<double>*& oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::diff_pt () inline
Pointer to vector of diffusion coefficients.
     {
       return Diff_pt;
     }
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::Diff_pt.
Referenced by oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >::further_build().
disable_ALE()
template<unsigned NREAGENT, unsigned DIM> void oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::disable_ALE () inline virtual
Disable ALE, i.e. assert the mesh is not moving – you do this at your own risk!
Reimplemented from oomph::FiniteElement.
     {
       ALE_is_disabled = true;
     }
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::ALE_is_disabled.
Referenced by oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::disable_ALE(), and oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >::disable_ALE().
dshape_and_dtest_eulerian_adv_diff_react()
template<unsigned NREAGENT, unsigned DIM> virtual double oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::dshape_and_dtest_eulerian_adv_diff_react (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const protected pure virtual
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping
Implemented in oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, oomph::QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, and oomph::QAdvectionDiffusionReactionElement< 2, DIM, 3 >.
dshape_and_dtest_eulerian_at_knot_adv_diff_react()
template<unsigned NREAGENT, unsigned DIM> virtual double oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::dshape_and_dtest_eulerian_at_knot_adv_diff_react (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const protected pure virtual
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping
Implemented in oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, oomph::QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, and oomph::QAdvectionDiffusionReactionElement< 2, DIM, 3 >.
enable_ALE()
template<unsigned NREAGENT, unsigned DIM> void oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::enable_ALE () inline virtual
(Re-)enable ALE, i.e. take possible mesh motion into account when evaluating the time-derivative. Note: By default, ALE is enabled, at the expense of possibly creating unnecessary work in problems where the mesh is, in fact, stationary.
Reimplemented from oomph::FiniteElement.
     {
       ALE_is_disabled = false;
     }
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::ALE_is_disabled.
Referenced by oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::enable_ALE(), and oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >::enable_ALE().
fill_in_contribution_to_jacobian()
template<unsigned NREAGENT, unsigned DIM> void oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline virtual
Add the element's contribution to its residual vector and the element Jacobian matrix (wrapper)
Reimplemented from oomph::GeneralisedElement.
     {
       // Call the generic routine with the flag set to 1
       fill_in_generic_residual_contribution_adv_diff_react(
         residuals, jacobian, GeneralisedElement::Dummy_matrix, 1);
     }
References oomph::GeneralisedElement::Dummy_matrix, and oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::fill_in_generic_residual_contribution_adv_diff_react().
Referenced by oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_jacobian(), and oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_jacobian().
fill_in_contribution_to_jacobian_and_mass_matrix()
template<unsigned NREAGENT, unsigned DIM> void oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) inline virtual
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix
Reimplemented from oomph::GeneralisedElement.
     {
       // Call the generic routine with the flag set to 2
       fill_in_generic_residual_contribution_adv_diff_react(
         residuals, jacobian, mass_matrix, 2);
     }
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::fill_in_generic_residual_contribution_adv_diff_react().
Referenced by oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix(), and oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_jacobian_and_mass_matrix().
fill_in_contribution_to_residuals()
template<unsigned NREAGENT, unsigned DIM> void oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::fill_in_contribution_to_residuals (Vector< double > & residuals) inline virtual
Add the element's contribution to its residual vector (wrapper)
Reimplemented from oomph::GeneralisedElement.
     {
       // Call the generic residuals function with flag set to 0 and using
       // a dummy matrix
       fill_in_generic_residual_contribution_adv_diff_react(
         residuals,
         GeneralisedElement::Dummy_matrix,
         GeneralisedElement::Dummy_matrix,
         0);
     }
References oomph::GeneralisedElement::Dummy_matrix, and oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::fill_in_generic_residual_contribution_adv_diff_react().
Referenced by oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_residuals(), oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >::fill_in_contribution_to_residuals(), oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_by_fd(), and oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >::fill_in_off_diagonal_jacobian_blocks_by_fd().
fill_in_generic_residual_contribution_adv_diff_react()
template<unsigned NREAGENT, unsigned DIM> void oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::fill_in_generic_residual_contribution_adv_diff_react (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, unsigned flag) protected virtual
Add the element's contribution to its residual vector only (if flag=and/or element Jacobian matrix
Compute element residual Vector and/or element Jacobian matrix and/or the mass matrix
flag=2: compute Jacobian, residuals and mass matrix flag=1: compute Jacobian and residuals flag=0: compute only residual Vector
Pure version without hanging nodes
Reimplemented in oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >.
   {
     // Find out how many nodes there are
     const unsigned n_node = nnode();
     // Get the nodal index at which the unknown is stored
     unsigned c_nodal_index[NREAGENT];
     for (unsigned r = 0; r < NREAGENT; r++)
     {
       c_nodal_index[r] = c_index_adv_diff_react(r);
     }
     // Set up memory for the shape and test functions
     Shape psi(n_node), test(n_node);
     DShape dpsidx(n_node, DIM), dtestdx(n_node, DIM);
     // Set the value of n_intpt
     unsigned n_intpt = integral_pt()->nweight();
     // Set the Vector to hold local coordinates
     Vector<double> s(DIM);
     // Get diffusion coefficients
     Vector<double> D = diff();
     // Get the timescales
     Vector<double> T = tau();
     // Integers used to store the local equation number and local unknown
     // indices for the residuals and jacobians
     int local_eqn = 0, local_unknown = 0;
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Assign values of s
       for (unsigned i = 0; i < DIM; i++) s[i] = integral_pt()->knot(ipt, i);
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Call the derivatives of the shape and test functions
       double J = dshape_and_dtest_eulerian_at_knot_adv_diff_react(
         ipt, psi, dpsidx, test, dtestdx);
       // Premultiply the weights and the Jacobian
       double W = w * J;
       // Calculate local values of the solution and its derivatives
       // Allocate
       Vector<double> interpolated_c(NREAGENT, 0.0);
       Vector<double> dcdt(NREAGENT, 0.0);
       Vector<double> interpolated_x(DIM, 0.0);
       DenseMatrix<double> interpolated_dcdx(NREAGENT, DIM, 0.0);
       Vector<double> mesh_velocity(DIM, 0.0);
       // Calculate function value and derivatives:
       // Loop over nodes
       for (unsigned l = 0; l < n_node; l++)
       {
         // Loop over directions to calculate the position
         for (unsigned j = 0; j < DIM; j++)
         {
           interpolated_x[j] += raw_nodal_position(l, j) * psi(l);
         }
         // Loop over the unknown reagents
         for (unsigned r = 0; r < NREAGENT; r++)
         {
           // Get the value at the node
           const double c_value = raw_nodal_value(l, c_nodal_index[r]);
           // Calculate the interpolated value
           interpolated_c[r] += c_value * psi(l);
           dcdt[r] += dc_dt_adv_diff_react(l, r) * psi(l);
           // Loop over directions to calculate the derivatie
           for (unsigned j = 0; j < DIM; j++)
           {
             interpolated_dcdx(r, j) += c_value * dpsidx(l, j);
           }
         }
       }
       // Mesh velocity?
       if (!ALE_is_disabled)
       {
         for (unsigned l = 0; l < n_node; l++)
         {
           for (unsigned j = 0; j < DIM; j++)
           {
             mesh_velocity[j] += raw_dnodal_position_dt(l, j) * psi(l);
           }
         }
       }
       // Get source function
       Vector<double> source(NREAGENT);
       get_source_adv_diff_react(ipt, interpolated_x, source);
       // Get wind
       Vector<double> wind(DIM);
       get_wind_adv_diff_react(ipt, s, interpolated_x, wind);
       // Get reaction terms
       Vector<double> R(NREAGENT);
       get_reaction_adv_diff_react(ipt, interpolated_c, R);
       // If we are getting the jacobian the get the derivative terms
       DenseMatrix<double> dRdC(NREAGENT);
       if (flag)
       {
         get_reaction_deriv_adv_diff_react(ipt, interpolated_c, dRdC);
       }
       // Assemble residuals and Jacobian
       //--------------------------------
       // Loop over the test functions
       for (unsigned l = 0; l < n_node; l++)
       {
         // Loop over the reagents
         for (unsigned r = 0; r < NREAGENT; r++)
         {
           // Set the local equation number
           local_eqn = nodal_local_eqn(l, c_nodal_index[r]);
           /*IF it's not a boundary condition*/
           if (local_eqn >= 0)
           {
             // Add body force/source/reaction term and time derivative
             residuals[local_eqn] -=
               (T[r] * dcdt[r] + source[r] + R[r]) * test(l) * W;
             // The Advection Diffusion bit itself
             for (unsigned k = 0; k < DIM; k++)
             {
               // Terms that multiply the test function
               double tmp = wind[k];
               // If the mesh is moving need to subtract the mesh velocity
               if (!ALE_is_disabled)
               {
                 tmp -= T[r] * mesh_velocity[k];
               }
               // Now construct the contribution to the residuals
               residuals[local_eqn] -= interpolated_dcdx(r, k) *
                                       (tmp * test(l) + D[r] * dtestdx(l, k)) *
                                       W;
             }
             // Calculate the jacobian
             //-----------------------
             if (flag)
             {
               // Loop over the velocity shape functions again
               for (unsigned l2 = 0; l2 < n_node; l2++)
               {
                 // Loop over the reagents again
                 for (unsigned r2 = 0; r2 < NREAGENT; r2++)
                 {
                   // Set the number of the unknown
                   local_unknown = nodal_local_eqn(l2, c_nodal_index[r2]);
                   // If at a non-zero degree of freedom add in the entry
                   if (local_unknown >= 0)
                   {
                     // Diagonal terms (i.e. the basic equations)
                     if (r2 == r)
                     {
                       // Mass matrix term
                       jacobian(local_eqn, local_unknown) -=
                         T[r] * test(l) * psi(l2) *
                         node_pt(l2)->time_stepper_pt()->weight(1, 0) * W;
                       // Add the mass matrix term
                       if (flag == 2)
                       {
                         mass_matrix(local_eqn, local_unknown) +=
                           T[r] * test(l) * psi(l2) * W;
                       }
                       // Add contribution to Elemental Matrix
                       for (unsigned i = 0; i < DIM; i++)
                       {
                         // Temporary term used in assembly
                         double tmp = wind[i];
                         if (!ALE_is_disabled) tmp -= T[r] * mesh_velocity[i];
                         // Now assemble Jacobian term
                         jacobian(local_eqn, local_unknown) -=
                           dpsidx(l2, i) *
                           (tmp * test(l) + D[r] * dtestdx(l, i)) * W;
                       }
                     } // End of diagonal terms
                     // Now add the cross-reaction terms
                     jacobian(local_eqn, local_unknown) -=
                       dRdC(r, r2) * psi(l2) * test(l) * W;
                   }
                 }
               }
             } // End of jacobian
           }
         } // End of loop over reagents
       } // End of loop over nodes
     } // End of loop over integration points
   }
References oomph::ALE_is_disabled, D, DIM, i, J, j, k, UniformPSDSelfTest::r, R, s, TestProblem::source(), Eigen::test, tmp, w, and oomph::QuadTreeNames::W.
Referenced by oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::fill_in_contribution_to_jacobian(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::fill_in_contribution_to_jacobian_and_mass_matrix(), and oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::fill_in_contribution_to_residuals().
get_flux()
template<unsigned NREAGENT, unsigned DIM> void oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::get_flux (const Vector< double > & s, Vector< double > & flux) const inline
Get flux: \(\mbox{flux}[DIM r + i] = \mbox{d}C_{r} / \mbox{d}x_i \).
     {
       // Find out how many nodes there are in the element
       const unsigned n_node = nnode();
       // Set up memory for the shape and test functions
       Shape psi(n_node);
       DShape dpsidx(n_node, DIM);
       // Call the derivatives of the shape and test functions
       dshape_eulerian(s, psi, dpsidx);
       // Initialise to zero
       for (unsigned j = 0; j < DIM * NREAGENT; j++)
       {
         flux[j] = 0.0;
       }
       // Loop over the reagent terms
       for (unsigned r = 0; r < NREAGENT; r++)
       {
         unsigned c_nodal_index = c_index_adv_diff_react(r);
         // Loop over derivative directions
         for (unsigned j = 0; j < DIM; j++)
         {
           unsigned index = r * DIM + j;
           // Loop over the nodes
           for (unsigned l = 0; l < n_node; l++)
           {
             flux[index] += nodal_value(l, c_nodal_index) * dpsidx(l, j);
           }
         }
       }
     }
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::c_index_adv_diff_react(), DIM, oomph::FiniteElement::dshape_eulerian(), ProblemParameters::flux(), j, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), UniformPSDSelfTest::r, and s.
Referenced by oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >::get_Z2_flux(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::get_Z2_flux().
get_reaction_adv_diff_react()
template<unsigned NREAGENT, unsigned DIM> virtual void oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::get_reaction_adv_diff_react (const unsigned & ipt, const Vector< double > & C, Vector< double > & R) const inline virtual
Get reaction as a function of the given reagent concentrations This function is virtual to allow overloading in multi-physics problems where the reaction function might be determined by another system of equations
Reimplemented in oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >, and oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >.
     {
       // If no wind function has been set, return zero
       if (Reaction_fct_pt == 0)
       {
         for (unsigned r = 0; r < NREAGENT; r++)
         {
           R[r] = 0.0;
         }
       }
       else
       {
         // Get reaction terms
         (*Reaction_fct_pt)(C, R);
       }
     }
References UniformPSDSelfTest::r, R, and oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::Reaction_fct_pt.
get_reaction_deriv_adv_diff_react()
template<unsigned NREAGENT, unsigned DIM> virtual void oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::get_reaction_deriv_adv_diff_react (const unsigned & ipt, const Vector< double > & C, DenseMatrix< double > & dRdC) const inline virtual
Get the derivatives of the reaction terms with respect to the concentration variables. If no explicit function pointer is set, these will be calculated by finite differences
Reimplemented in oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >, and oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >.
     {
       // If no reaction pointer set, return zero
       if (Reaction_fct_pt == 0)
       {
         for (unsigned r = 0; r < NREAGENT; r++)
         {
           for (unsigned p = 0; p < NREAGENT; p++)
           {
             dRdC(r, p) = 0.0;
           }
         }
       }
       else
       {
         // If no function pointer get finite differences
         if (Reaction_deriv_fct_pt == 0)
         {
           // Local copy of the unknowns
           Vector<double> C_local = C;
           // Finite differences
           Vector<double> R(NREAGENT), R_plus(NREAGENT), R_minus(NREAGENT);
           // Get the initial reaction terms
           //(*Reaction_fct_pt)(C,R);
           const double fd_step = GeneralisedElement::Default_fd_jacobian_step;
           // Now loop over all the reagents
           for (unsigned p = 0; p < NREAGENT; p++)
           {
             // Store the old value
             double old_var = C_local[p];
             // Increment the value
             C_local[p] += fd_step;
             // Get the new values
             (*Reaction_fct_pt)(C_local, R_plus);
             // Reset the value
             C_local[p] = old_var;
             // Decrement the value
             C_local[p] -= fd_step;
             // Get the new values
             (*Reaction_fct_pt)(C_local, R_minus);
             // Assemble the column of the jacobian
             for (unsigned r = 0; r < NREAGENT; r++)
             {
               dRdC(r, p) = (R_plus[r] - R_minus[r]) / (2.0 * fd_step);
             }
             // Reset the value
             C_local[p] = old_var;
           }
         }
         // Otherwise get the terms from the function
         else
         {
           (*Reaction_deriv_fct_pt)(C, dRdC);
         }
       }
     }
References oomph::GeneralisedElement::Default_fd_jacobian_step, p, UniformPSDSelfTest::r, R, oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::Reaction_deriv_fct_pt, and oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::Reaction_fct_pt.
get_source_adv_diff_react()
template<unsigned NREAGENT, unsigned DIM> virtual void oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::get_source_adv_diff_react (const unsigned & ipt, const Vector< double > & x, Vector< double > & source) const inline virtual
Get source term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations
     {
       // If no source function has been set, return zero
       if (Source_fct_pt == 0)
       {
         for (unsigned r = 0; r < NREAGENT; r++)
         {
           source[r] = 0.0;
         }
       }
       else
       {
         // Get source strength
         (*Source_fct_pt)(x, source);
       }
     }
References UniformPSDSelfTest::r, TestProblem::source(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::Source_fct_pt, and plotDoE::x.
get_wind_adv_diff_react()
template<unsigned NREAGENT, unsigned DIM> virtual void oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::get_wind_adv_diff_react (const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, Vector< double > & wind) const inline virtual
Get wind at (Eulerian) position x and/or local coordinate s. This function is virtual to allow overloading in multi-physics problems where the wind function might be determined by another system of equations
Reimplemented in oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, and oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >.
     {
       // If no wind function has been set, return zero
       if (Wind_fct_pt == 0)
       {
         for (unsigned i = 0; i < DIM; i++)
         {
           wind[i] = 0.0;
         }
       }
       else
       {
         // Get continuous time from timestepper of first node
         double time = node_pt(0)->time_stepper_pt()->time_pt()->time();
         // Get wind
         (*Wind_fct_pt)(time, x, wind);
       }
     }
References DIM, i, oomph::FiniteElement::node_pt(), oomph::Time::time(), oomph::TimeStepper::time_pt(), oomph::Data::time_stepper_pt(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::Wind_fct_pt, and plotDoE::x.
integrate_reagents()
template<unsigned NREAGENT, unsigned DIM> void oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::integrate_reagents (Vector< double > & C) const
Return the integrated reagent concentrations.
Integrate the reagent concentrations over the element.
   {
     // Find out how many nodes there are
     const unsigned n_node = nnode();
     // Get the nodal index at which the unknown is stored
     unsigned c_nodal_index[NREAGENT];
     for (unsigned r = 0; r < NREAGENT; r++)
     {
       c_nodal_index[r] = c_index_adv_diff_react(r);
     }
     // Set up memory for the shape and test functions
     Shape psi(n_node);
     DShape dpsidx(n_node, DIM);
     // Set the value of n_intpt
     unsigned n_intpt = integral_pt()->nweight();
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Call the derivatives of the shape and test functions
       double J = dshape_eulerian_at_knot(ipt, psi, dpsidx);
       // Premultiply the weights and the Jacobian
       double W = w * J;
       // Calculate local values of the solution and its derivatives
       // Allocate
       Vector<double> interpolated_c(NREAGENT, 0.0);
       // Calculate function value and derivatives:
       // Loop over nodes
       for (unsigned l = 0; l < n_node; l++)
       {
         // Loop over the unknown reagents
         for (unsigned r = 0; r < NREAGENT; r++)
         {
           // Get the value at the node
           const double c_value = raw_nodal_value(l, c_nodal_index[r]);
           // Calculate the interpolated value
           interpolated_c[r] += c_value * psi(l);
         }
       }
       for (unsigned r = 0; r < NREAGENT; r++)
       {
         C[r] += interpolated_c[r] * W;
       }
     } // End of loop over integration points
   }
References DIM, J, UniformPSDSelfTest::r, w, and oomph::QuadTreeNames::W.
interpolated_c_adv_diff_react()
template<unsigned NREAGENT, unsigned DIM> double oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::interpolated_c_adv_diff_react (const Vector< double > & s, const unsigned & i) const inline
Return FE representation of function value c_i(s) at local coordinate s.
     {
       // Find number of nodes
       unsigned n_node = nnode();
       // Get the nodal index at which the unknown is stored
       unsigned c_nodal_index = c_index_adv_diff_react(i);
       // Local shape function
       Shape psi(n_node);
       // Find values of shape function
       shape(s, psi);
       // Initialise value of u
       double interpolated_c = 0.0;
       // Loop over the local nodes and sum
       for (unsigned l = 0; l < n_node; l++)
       {
         interpolated_c += nodal_value(l, c_nodal_index) * psi[l];
       }
       return (interpolated_c);
     }
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::c_index_adv_diff_react(), i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, and oomph::FiniteElement::shape().
Referenced by oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >::output(), and oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >::output().
operator=()
template<unsigned NREAGENT, unsigned DIM> void oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::operator= (const AdvectionDiffusionReactionEquations< NREAGENT, DIM > &) delete
Broken assignment operator.
output() [1/4]
template<unsigned NREAGENT, unsigned DIM> void oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::output (FILE * file_pt) inline virtual
C_style output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, oomph::QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, and oomph::QAdvectionDiffusionReactionElement< 2, DIM, 3 >.
     {
       unsigned n_plot = 5;
       output(file_pt, n_plot);
     }
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::output().
output() [2/4]
template<unsigned NREAGENT, unsigned DIM> void oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::output (FILE * file_pt, const unsigned & nplot) virtual
C-style output FE representation of soln: x,y,u or x,y,z,u at n_plot^DIM plot points
C-style output function:
x,y,u or x,y,z,u
nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, oomph::QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, and oomph::QAdvectionDiffusionReactionElement< 2, DIM, 3 >.
   {
     // Vector of local coordinates
     Vector<double> s(DIM);
     // Tecplot header info
     fprintf(file_pt, "%s", tecplot_zone_string(nplot).c_str());
     // Loop over plot points
     unsigned num_plot_points = nplot_points(nplot);
     for (unsigned iplot = 0; iplot < num_plot_points; iplot++)
     {
       // Get local coordinates of plot point
       get_s_plot(iplot, nplot, s);
       for (unsigned i = 0; i < DIM; i++)
       {
         fprintf(file_pt, "%g ", interpolated_x(s, i));
       }
       for (unsigned i = 0; i < NREAGENT; i++)
       {
         fprintf(file_pt, "%g \n", interpolated_c_adv_diff_react(s, i));
       }
     }
     // Write tecplot footer (e.g. FE connectivity lists)
     write_tecplot_zone_footer(file_pt, nplot);
   }
References DIM, i, and s.
output() [3/4]
template<unsigned NREAGENT, unsigned DIM> void oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::output (std::ostream & outfile) inline virtual
Output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, oomph::QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, and oomph::QAdvectionDiffusionReactionElement< 2, DIM, 3 >.
     {
       unsigned nplot = 5;
       output(outfile, nplot);
     }
Referenced by oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::output(), oomph::QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::output(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::output().
output() [4/4]
template<unsigned NREAGENT, unsigned DIM> void oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::output (std::ostream & outfile, const unsigned & nplot) virtual
Output FE representation of soln: x,y,u or x,y,z,u at nplot^DIM plot points
Output function:
x,y,u,w_x,w_y or x,y,z,u,w_x,w_y,w_z
nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, oomph::QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, and oomph::QAdvectionDiffusionReactionElement< 2, DIM, 3 >.
   {
     // Vector of local coordinates
     Vector<double> s(DIM);
     // Tecplot header info
     outfile << tecplot_zone_string(nplot);
     // Loop over plot points
     unsigned num_plot_points = nplot_points(nplot);
     for (unsigned iplot = 0; iplot < num_plot_points; iplot++)
     {
       // Get local coordinates of plot point
       get_s_plot(iplot, nplot, s);
       // Get Eulerian coordinate of plot point
       Vector<double> x(DIM);
       interpolated_x(s, x);
       for (unsigned i = 0; i < DIM; i++)
       {
         outfile << x[i] << " ";
       }
       for (unsigned i = 0; i < NREAGENT; i++)
       {
         outfile << interpolated_c_adv_diff_react(s, i) << " ";
       }
       // Get the wind
       Vector<double> wind(DIM);
       // Dummy integration point needed
       unsigned ipt = 0;
       get_wind_adv_diff_react(ipt, s, x, wind);
       for (unsigned i = 0; i < DIM; i++)
       {
         outfile << wind[i] << " ";
       }
       outfile << std::endl;
     }
     // Write tecplot footer (e.g. FE connectivity lists)
     write_tecplot_zone_footer(outfile, nplot);
   }
References DIM, i, s, and plotDoE::x.
output_fct() [1/2]
template<unsigned NREAGENT, unsigned DIM> virtual void oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::output_fct (std::ostream & outfile, const unsigned & nplot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) inline virtual
Output exact soln: x,y,u_exact or x,y,z,u_exact at nplot^DIM plot points (dummy time-dependent version to keep intel compiler happy)
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::DoubleBuoyantQCrouzeixRaviartElement< DIM >, oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, oomph::QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, and oomph::QAdvectionDiffusionReactionElement< 2, DIM, 3 >.
     {
       throw OomphLibError("There is no time-dependent output_fct() for "
                           "Advection Diffusion elements",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
output_fct() [2/2]
template<unsigned NREAGENT, unsigned DIM> void oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) virtual
Output exact soln: x,y,u_exact or x,y,z,u_exact at nplot^DIM plot points.
Output exact solution
Solution is provided via function pointer. Plot at a given number of plot points.
x,y,u_exact or x,y,z,u_exact
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, oomph::QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >, and oomph::QAdvectionDiffusionReactionElement< 2, DIM, 3 >.
   {
     // Vector of local coordinates
     Vector<double> s(DIM);
     // Vector for coordintes
     Vector<double> x(DIM);
     // Tecplot header info
     outfile << tecplot_zone_string(nplot);
     // Exact solution Vector (here a scalar)
     Vector<double> exact_soln(1);
     // Loop over plot points
     unsigned num_plot_points = nplot_points(nplot);
     for (unsigned iplot = 0; iplot < num_plot_points; iplot++)
     {
       // Get local coordinates of plot point
       get_s_plot(iplot, nplot, s);
       // Get x position as Vector
       interpolated_x(s, x);
       // Get exact solution at this point
       (*exact_soln_pt)(x, exact_soln);
       // Output x,y,...,u_exact
       for (unsigned i = 0; i < DIM; i++)
       {
         outfile << x[i] << " ";
       }
       outfile << exact_soln[0] << std::endl;
     }
     // Write tecplot footer (e.g. FE connectivity lists)
     write_tecplot_zone_footer(outfile, nplot);
   }
References DIM, ProblemParameters::exact_soln(), i, s, and plotDoE::x.
Referenced by oomph::QAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::output_fct(), and oomph::TAdvectionDiffusionReactionElement< NREAGENT, DIM, NNODE_1D >::output_fct().
reaction_deriv_fct_pt() [1/2]
template<unsigned NREAGENT, unsigned DIM> AdvectionDiffusionReactionReactionDerivFctPt& oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::reaction_deriv_fct_pt () inline
Access function: Pointer to reaction derivatives function.
     {
       return Reaction_deriv_fct_pt;
     }
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::Reaction_deriv_fct_pt.
Referenced by oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >::further_build().
reaction_deriv_fct_pt() [2/2]
template<unsigned NREAGENT, unsigned DIM> AdvectionDiffusionReactionReactionDerivFctPt oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::reaction_deriv_fct_pt () const inline
Access function: Pointer to reaction function. Const version.
     {
       return Reaction_deriv_fct_pt;
     }
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::Reaction_deriv_fct_pt.
reaction_fct_pt() [1/2]
template<unsigned NREAGENT, unsigned DIM> AdvectionDiffusionReactionReactionFctPt& oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::reaction_fct_pt () inline
Access function: Pointer to reaction function.
     {
       return Reaction_fct_pt;
     }
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::Reaction_fct_pt.
Referenced by oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >::further_build().
reaction_fct_pt() [2/2]
template<unsigned NREAGENT, unsigned DIM> AdvectionDiffusionReactionReactionFctPt oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::reaction_fct_pt () const inline
Access function: Pointer to reaction function. Const version.
     {
       return Reaction_fct_pt;
     }
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::Reaction_fct_pt.
self_test()
template<unsigned NREAGENT, unsigned DIM> unsigned oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::self_test virtual
Self-test: Return 0 for OK.
Reimplemented from oomph::FiniteElement.
   {
     bool passed = true;
     // Check lower-level stuff
     if (FiniteElement::self_test() != 0)
     {
       passed = false;
     }
     // Return verdict
     if (passed)
     {
       return 0;
     }
     else
     {
       return 1;
     }
   }
References oomph::FiniteElement::self_test().
source_fct_pt() [1/2]
template<unsigned NREAGENT, unsigned DIM> AdvectionDiffusionReactionSourceFctPt& oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::source_fct_pt () inline
Access function: Pointer to source function.
     {
       return Source_fct_pt;
     }
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::Source_fct_pt.
Referenced by oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >::further_build().
source_fct_pt() [2/2]
template<unsigned NREAGENT, unsigned DIM> AdvectionDiffusionReactionSourceFctPt oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::source_fct_pt () const inline
Access function: Pointer to source function. Const version.
     {
       return Source_fct_pt;
     }
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::Source_fct_pt.
tau()
template<unsigned NREAGENT, unsigned DIM> const Vector<double>& oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::tau () const inline
Vector of dimensionless timescales.
     {
       return *Tau_pt;
     }
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::Tau_pt.
tau_pt()
template<unsigned NREAGENT, unsigned DIM> Vector<double>*& oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::tau_pt () inline
Pointer to vector of dimensionless timescales.
     {
       return Tau_pt;
     }
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::Tau_pt.
Referenced by oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >::further_build().
wind_fct_pt() [1/2]
template<unsigned NREAGENT, unsigned DIM> AdvectionDiffusionReactionWindFctPt& oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::wind_fct_pt () inline
Access function: Pointer to wind function.
     {
       return Wind_fct_pt;
     }
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::Wind_fct_pt.
Referenced by oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >::further_build().
wind_fct_pt() [2/2]
template<unsigned NREAGENT, unsigned DIM> AdvectionDiffusionReactionWindFctPt oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::wind_fct_pt () const inline
Access function: Pointer to reaction function. Const version.
     {
       return Wind_fct_pt;
     }
References oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::Wind_fct_pt.
Member Data Documentation
ALE_is_disabled
template<unsigned NREAGENT, unsigned DIM> bool oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::ALE_is_disabled protected
Boolean flag to indicate if ALE formulation is disabled when time-derivatives are computed. Only set to true if you're sure that the mesh is stationary.
Referenced by oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::disable_ALE(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::enable_ALE(), and oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >::further_build().
Default_dimensionless_number
template<unsigned NREAGENT, unsigned DIM> Vector< double > oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::Default_dimensionless_number static private
Static default value for the dimensionless numbers.
2D Advection Diffusion elements
Default value for Peclet number
Referenced by oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::AdvectionDiffusionReactionEquations().
Diff_pt
template<unsigned NREAGENT, unsigned DIM> Vector<double>* oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::Diff_pt protected
Pointer to global diffusion coefficients.
Referenced by oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::AdvectionDiffusionReactionEquations(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::diff(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::diff_pt(), and oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >::further_build().
N_reagent
template<unsigned NREAGENT, unsigned DIM> const unsigned oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::N_reagent static protected
Initial value:
=
    NREAGENT
Reaction_deriv_fct_pt
template<unsigned NREAGENT, unsigned DIM> AdvectionDiffusionReactionReactionDerivFctPt oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::Reaction_deriv_fct_pt protected
Pointer to reaction derivatives.
Referenced by oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >::further_build(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::get_reaction_deriv_adv_diff_react(), and oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::reaction_deriv_fct_pt().
Reaction_fct_pt
template<unsigned NREAGENT, unsigned DIM> AdvectionDiffusionReactionReactionFctPt oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::Reaction_fct_pt protected
Pointer to reaction function.
Referenced by oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >::further_build(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::get_reaction_adv_diff_react(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::get_reaction_deriv_adv_diff_react(), and oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::reaction_fct_pt().
Source_fct_pt
template<unsigned NREAGENT, unsigned DIM> AdvectionDiffusionReactionSourceFctPt oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::Source_fct_pt protected
Pointer to source function:
Referenced by oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >::further_build(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::get_source_adv_diff_react(), and oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::source_fct_pt().
Tau_pt
template<unsigned NREAGENT, unsigned DIM> Vector<double>* oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::Tau_pt protected
Pointer to global timescales.
Referenced by oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::AdvectionDiffusionReactionEquations(), oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >::further_build(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::tau(), and oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::tau_pt().
Wind_fct_pt
template<unsigned NREAGENT, unsigned DIM> AdvectionDiffusionReactionWindFctPt oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::Wind_fct_pt protected
Pointer to wind function:
Referenced by oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >::further_build(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::get_wind_adv_diff_react(), and oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::wind_fct_pt().
The documentation for this class was generated from the following files:
advection_diffusion_reaction_elements.h
advection_diffusion_reaction_elements.cc