MercuryDPM: Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device > Struct Template Reference
Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device > Struct Template Reference
#include <TensorConvolution.h>
Public Types
enum {
IsAligned , PacketAccess , BlockAccess = false , PreferBlockAccess = false ,
CoordAccess = false , RawAccess = false
}
typedef TensorConvolutionOp< Indices, InputArgType, KernelArgType > XprType
typedef XprType::Index Index
typedef DSizes< Index, NumDims > Dimensions
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef StorageMemory< Scalar, Device > Storage
typedef Storage::Type EvaluatorPointerType
typedef internal::TensorBlockNotImplemented TensorBlock
Public Member Functions
EIGEN_STRONG_INLINE TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions & dimensions () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (Scalar *)
EIGEN_STRONG_INLINE void cleanup ()
void evalTo (typename XprType::Scalar *buffer)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC PacketReturnType packet (const Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
EIGEN_DEVICE_FUNC EvaluatorPointerType data () const
Static Public Attributes
static constexpr int NumDims
static constexpr int NumKernelDims = internal::array_size<Indices>::value
static constexpr int PacketSize = PacketType<CoeffReturnType, Device>::size
static constexpr int Layout = TensorEvaluator<InputArgType, Device>::Layout
Private Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index firstInput (Index index) const
EIGEN_DEVICE_FUNC void convolve (Index firstIndex, Index firstKernel, int DimIndex, CoeffReturnType &accum) const
template<typename Packet >
EIGEN_DEVICE_FUNC void convolvePacket (Index firstIndex, Index firstKernel, int DimIndex, Packet &accum) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void preloadKernel ()
Private Attributes
array< Index, NumDims > m_inputStride
array< Index, NumDims > m_outputStride
array< Index, NumKernelDims > m_indexStride
array< Index, NumKernelDims > m_kernelStride
TensorEvaluator< InputArgType, Device > m_inputImpl
TensorEvaluator< KernelArgType, Device > m_kernelImpl
Dimensions m_dimensions
KernelArgType m_kernelArg
const Scalar * m_kernel
bool m_local_kernel
const Device EIGEN_DEVICE_REF m_device
Member Typedef Documentation
CoeffReturnType
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > typedef XprType::CoeffReturnType Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::CoeffReturnType
Dimensions
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > typedef DSizes<Index, NumDims> Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::Dimensions
EvaluatorPointerType
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > typedef Storage::Type Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::EvaluatorPointerType
Index
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > typedef XprType::Index Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::Index
PacketReturnType
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::PacketReturnType
Scalar
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > typedef XprType::Scalar Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::Scalar
Storage
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > typedef StorageMemory<Scalar, Device> Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::Storage
TensorBlock
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > typedef internal::TensorBlockNotImplemented Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::TensorBlock
XprType
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > typedef TensorConvolutionOp<Indices, InputArgType, KernelArgType> Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::XprType
Member Enumeration Documentation
anonymous enum
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
BlockAccess
PreferBlockAccess
CoordAccess
RawAccess
        {
     IsAligned =
         int(TensorEvaluator<InputArgType, Device>::IsAligned) & int(TensorEvaluator<KernelArgType, Device>::IsAligned),
     PacketAccess = int(TensorEvaluator<InputArgType, Device>::PacketAccess) &
                    int(TensorEvaluator<KernelArgType, Device>::PacketAccess),
     BlockAccess = false,
     PreferBlockAccess = false,
     CoordAccess = false,  // to be implemented
     RawAccess = false
   };
Constructor & Destructor Documentation
TensorEvaluator()
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > EIGEN_STRONG_INLINE Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::TensorEvaluator (const XprType & op, const Device & device) inline
       : m_inputImpl(op.inputExpression(), device),
         m_kernelImpl(op.kernelExpression(), device),
         m_kernelArg(op.kernelExpression()),
         m_kernel(NULL),
         m_local_kernel(false),
         m_device(device) {
     EIGEN_STATIC_ASSERT((static_cast<int>(TensorEvaluator<InputArgType, Device>::Layout) ==
                          static_cast<int>(TensorEvaluator<KernelArgType, Device>::Layout)),
                         YOU_MADE_A_PROGRAMMING_MISTAKE);
     const typename TensorEvaluator<InputArgType, Device>::Dimensions& input_dims = m_inputImpl.dimensions();
     const typename TensorEvaluator<KernelArgType, Device>::Dimensions& kernel_dims = m_kernelImpl.dimensions();
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       m_inputStride[0] = 1;
       for (int i = 1; i < NumDims; ++i) {
         m_inputStride[i] = m_inputStride[i - 1] * input_dims[i - 1];
       }
     } else {
       m_inputStride[NumDims - 1] = 1;
       for (int i = NumDims - 2; i >= 0; --i) {
         m_inputStride[i] = m_inputStride[i + 1] * input_dims[i + 1];
       }
     }
     m_dimensions = m_inputImpl.dimensions();
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       for (int i = 0; i < NumKernelDims; ++i) {
         const Index index = op.indices()[i];
         const Index input_dim = input_dims[index];
         const Index kernel_dim = kernel_dims[i];
         const Index result_dim = input_dim - kernel_dim + 1;
         m_dimensions[index] = result_dim;
         if (i > 0) {
           m_kernelStride[i] = m_kernelStride[i - 1] * kernel_dims[i - 1];
         } else {
           m_kernelStride[0] = 1;
         }
         m_indexStride[i] = m_inputStride[index];
       }
       m_outputStride[0] = 1;
       for (int i = 1; i < NumDims; ++i) {
         m_outputStride[i] = m_outputStride[i - 1] * m_dimensions[i - 1];
       }
     } else {
       for (int i = NumKernelDims - 1; i >= 0; --i) {
         const Index index = op.indices()[i];
         const Index input_dim = input_dims[index];
         const Index kernel_dim = kernel_dims[i];
         const Index result_dim = input_dim - kernel_dim + 1;
         m_dimensions[index] = result_dim;
         if (i < NumKernelDims - 1) {
           m_kernelStride[i] = m_kernelStride[i + 1] * kernel_dims[i + 1];
         } else {
           m_kernelStride[NumKernelDims - 1] = 1;
         }
         m_indexStride[i] = m_inputStride[index];
       }
       m_outputStride[NumDims - 1] = 1;
       for (int i = NumDims - 2; i >= 0; --i) {
         m_outputStride[i] = m_outputStride[i + 1] * m_dimensions[i + 1];
       }
     }
   }
References Eigen::ColMajor, Eigen::TensorEvaluator< Derived, Device >::dimensions(), EIGEN_STATIC_ASSERT, i, Eigen::TensorEvaluator< Derived, Device >::Layout, and op.
Member Function Documentation
cleanup()
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::cleanup () inline
{
     m_inputImpl.cleanup();
     if (m_local_kernel) {
       m_device.deallocate((void*)m_kernel);
       m_local_kernel = false;
     }
     m_kernel = NULL;
   }
References Eigen::TensorEvaluator< Derived, Device >::m_device.
Referenced by framework.Frame::__init__().
coeff()
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::coeff (Index index) const inline
{
     CoeffReturnType result = CoeffReturnType(0);
     convolve(firstInput(index), 0, NumKernelDims - 1, result);
     return result;
   }
convolve()
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > EIGEN_DEVICE_FUNC void Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::convolve (Index firstIndex, Index firstKernel, int DimIndex, CoeffReturnType & accum) const inline private
{
     for (int j = 0; j < m_kernelImpl.dimensions()[DimIndex]; ++j) {
       const Index input = firstIndex + j * m_indexStride[DimIndex];
       const Index kernel = firstKernel + j * m_kernelStride[DimIndex];
       if (DimIndex > 0) {
         convolve(input, kernel, DimIndex - 1, accum);
       } else {
         accum += m_inputImpl.coeff(input) * m_kernel[kernel];
       }
     }
   }
References j.
convolvePacket()
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > template<typename Packet > EIGEN_DEVICE_FUNC void Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::convolvePacket (Index firstIndex, Index firstKernel, int DimIndex, Packet & accum) const inline private
{
     for (int j = 0; j < m_kernelImpl.dimensions()[DimIndex]; ++j) {
       const Index input = firstIndex + j * m_indexStride[DimIndex];
       const Index kernel = firstKernel + j * m_kernelStride[DimIndex];
       if (DimIndex > 0) {
         convolvePacket(input, kernel, DimIndex - 1, accum);
       } else {
         accum = internal::pmadd<Packet>(m_inputImpl.template packet<Unaligned>(input),
                                         internal::pset1<Packet>(m_kernel[kernel]), accum);
       }
     }
   }
References j.
costPerCoeff()
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::costPerCoeff (bool vectorized) const inline
{
     const double kernel_size = m_kernelImpl.dimensions().TotalSize();
     // We ignore the use of fused multiply-add.
     const double convolve_compute_cost = TensorOpCost::AddCost<Scalar>() + TensorOpCost::MulCost<Scalar>();
     const double firstIndex_compute_cost =
         NumDims *
         (2 * TensorOpCost::AddCost<Index>() + 2 * TensorOpCost::MulCost<Index>() + TensorOpCost::DivCost<Index>());
     return TensorOpCost(0, 0, firstIndex_compute_cost, vectorized, PacketSize) +
            kernel_size * (m_inputImpl.costPerCoeff(vectorized) + m_kernelImpl.costPerCoeff(vectorized) +
                           TensorOpCost(0, 0, convolve_compute_cost, vectorized, PacketSize));
   }
References Eigen::TensorEvaluator< Derived, Device >::PacketSize.
data()
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > EIGEN_DEVICE_FUNC EvaluatorPointerType Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::data () const inline
 { return NULL; }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
dimensions()
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions& Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::dimensions () const inline
 { return m_dimensions; }
evalSubExprsIfNeeded()
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::evalSubExprsIfNeeded (Scalar *) inline
{
     m_inputImpl.evalSubExprsIfNeeded(NULL);
     preloadKernel();
     return true;
   }
evalTo()
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > void Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::evalTo (typename XprType::Scalar * buffer) inline
{
     evalSubExprsIfNeeded(NULL);
     for (int i = 0; i < dimensions().TotalSize(); ++i) {
       buffer[i] += coeff(i);
     }
     cleanup();
   }
References Eigen::TensorEvaluator< Derived, Device >::cleanup(), Eigen::TensorEvaluator< Derived, Device >::coeff(), Eigen::TensorEvaluator< Derived, Device >::dimensions(), Eigen::TensorEvaluator< Derived, Device >::evalSubExprsIfNeeded(), and i.
firstInput()
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::firstInput (Index index) const inline private
{
     Index startInput = 0;
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       for (int i = NumDims - 1; i > 0; --i) {
         const Index idx = index / m_outputStride[i];
         startInput += idx * m_inputStride[i];
         index -= idx * m_outputStride[i];
       }
     } else {
       for (int i = 0; i < NumDims - 1; ++i) {
         const Index idx = index / m_outputStride[i];
         startInput += idx * m_inputStride[i];
         index -= idx * m_outputStride[i];
       }
     }
     startInput += index;
     return startInput;
   }
References Eigen::ColMajor, i, and Eigen::TensorEvaluator< Derived, Device >::Layout.
packet()
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > template<int LoadMode> EIGEN_DEVICE_FUNC PacketReturnType Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::packet (const Index index) const inline
{
     Index indices[2] = {index, index + PacketSize - 1};
     Index startInputs[2] = {0, 0};
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       for (int i = NumDims - 1; i > 0; --i) {
         const Index idx0 = indices[0] / m_outputStride[i];
         const Index idx1 = indices[1] / m_outputStride[i];
         startInputs[0] += idx0 * m_inputStride[i];
         startInputs[1] += idx1 * m_inputStride[i];
         indices[0] -= idx0 * m_outputStride[i];
         indices[1] -= idx1 * m_outputStride[i];
       }
     } else {
       for (int i = 0; i < NumDims - 1; ++i) {
         const Index idx0 = indices[0] / m_outputStride[i];
         const Index idx1 = indices[1] / m_outputStride[i];
         startInputs[0] += idx0 * m_inputStride[i];
         startInputs[1] += idx1 * m_inputStride[i];
         indices[0] -= idx0 * m_outputStride[i];
         indices[1] -= idx1 * m_outputStride[i];
       }
     }
     startInputs[0] += indices[0];
     startInputs[1] += indices[1];
     if (startInputs[1] - startInputs[0] == PacketSize - 1) {
       PacketReturnType result = internal::pset1<PacketReturnType>(0);
       convolvePacket(startInputs[0], 0, NumKernelDims - 1, result);
       return result;
     } else {
       EIGEN_ALIGN_MAX Scalar data[PacketSize];
       data[0] = Scalar(0);
       convolve(startInputs[0], 0, NumKernelDims - 1, data[0]);
       for (int i = 1; i < PacketSize - 1; ++i) {
         data[i] = Scalar(0);
         convolve(firstInput(index + i), 0, NumKernelDims - 1, data[i]);
       }
       data[PacketSize - 1] = Scalar(0);
       convolve(startInputs[1], 0, NumKernelDims - 1, data[PacketSize - 1]);
       return internal::pload<PacketReturnType>(data);
     }
   }
References Eigen::ColMajor, Eigen::TensorEvaluator< Derived, Device >::data(), EIGEN_ALIGN_MAX, i, Eigen::TensorEvaluator< Derived, Device >::Layout, and Eigen::TensorEvaluator< Derived, Device >::PacketSize.
preloadKernel()
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::preloadKernel () inline private
{
     // Don't make a local copy of the kernel unless we have to (i.e. it's an
     // expression that needs to be evaluated)
     const Scalar* in_place = m_kernelImpl.data();
     if (in_place) {
       m_kernel = in_place;
       m_local_kernel = false;
     } else {
       size_t kernel_sz = m_kernelImpl.dimensions().TotalSize() * sizeof(Scalar);
       Scalar* local = (Scalar*)m_device.allocate_temp(kernel_sz);
       typedef TensorEvalToOp<const KernelArgType> EvalTo;
       EvalTo evalToTmp(local, m_kernelArg);
       const bool Vectorize = internal::IsVectorizable<Device, KernelArgType>::value;
       internal::TensorExecutor<const EvalTo, Device, Vectorize>::run(evalToTmp, m_device);
       m_kernel = local;
       m_local_kernel = true;
     }
   }
References fix_broken_doxygen_formulae::in_place, Eigen::TensorEvaluator< Derived, Device >::m_device, and Eigen::internal::TensorExecutor< Expression, Device, Vectorizable, Tiling >::run().
Member Data Documentation
Layout
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::Layout = TensorEvaluator<InputArgType, Device>::Layout static constexpr
m_device
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > const Device EIGEN_DEVICE_REF Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::m_device private
m_dimensions
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > Dimensions Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::m_dimensions private
m_indexStride
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > array<Index, NumKernelDims> Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::m_indexStride private
m_inputImpl
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > TensorEvaluator<InputArgType, Device> Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::m_inputImpl private
m_inputStride
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > array<Index, NumDims> Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::m_inputStride private
m_kernel
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > const Scalar* Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::m_kernel private
m_kernelArg
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > KernelArgType Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::m_kernelArg private
m_kernelImpl
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > TensorEvaluator<KernelArgType, Device> Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::m_kernelImpl private
m_kernelStride
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > array<Index, NumKernelDims> Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::m_kernelStride private
m_local_kernel
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > bool Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::m_local_kernel private
m_outputStride
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > array<Index, NumDims> Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::m_outputStride private
NumDims
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::NumDims static constexpr
Initial value:
=
      internal::array_size<typename TensorEvaluator<InputArgType, Device>::Dimensions>::value
NumKernelDims
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::NumKernelDims = internal::array_size<Indices>::value static constexpr
PacketSize
template<typename Indices , typename InputArgType , typename KernelArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::PacketSize = PacketType<CoeffReturnType, Device>::size static constexpr
The documentation for this struct was generated from the following file:
TensorConvolution.h