MercuryDPM: oomph::GmshTetMesh< ELEMENT > Class Template Reference
oomph::GmshTetMesh< ELEMENT > Class Template Reference
Forward declaration.
#include <gmsh_tet_mesh.template.h>
Public Member Functions
GmshTetMesh (GmshParameters *gmsh_parameters_pt, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor.
GmshTetMesh (GmshParameters *gmsh_parameters_pt, const bool &use_mesh_grading_from_file, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Public Member Functions inherited from oomph::TetMeshBase
TetMeshBase ()
Constructor.
TetMeshBase (const TetMeshBase &node)=delete
Broken copy constructor.
void operator= (const TetMeshBase &)=delete
Broken assignment operator.
virtual ~TetMeshBase ()
Destructor (empty)
void assess_mesh_quality (std::ofstream &some_file)
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b)
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b, const bool &switch_normal)
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b, const bool &switch_normal, std::ofstream &outfile)
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b, std::ofstream &outfile)
unsigned nboundary_element_in_region (const unsigned &b, const unsigned &r) const
Return the number of elements adjacent to boundary b in region r.
FiniteElement * boundary_element_in_region_pt (const unsigned &b, const unsigned &r, const unsigned &e) const
Return pointer to the e-th element adjacent to boundary b in region r.
int face_index_at_boundary_in_region (const unsigned &b, const unsigned &r, const unsigned &e) const
Return face index of the e-th element adjacent to boundary b in region r.
unsigned nregion ()
Return the number of regions specified by attributes.
unsigned nregion_element (const unsigned &r)
Return the number of elements in region r.
double region_attribute (const unsigned &i)
FiniteElement * region_element_pt (const unsigned &r, const unsigned &e)
Return the e-th element in the r-th region.
template<class ELEMENT >
void snap_to_quadratic_surface (const Vector< unsigned > &boundary_id, const std::string &quadratic_surface_file_name, const bool &switch_normal, DocInfo &doc_info)
template<class ELEMENT >
void snap_to_quadratic_surface (const Vector< unsigned > &boundary_id, const std::string &quadratic_surface_file_name, const bool &switch_normal)
void snap_nodes_onto_geometric_objects ()
template<class ELEMENT >
void split_elements_in_corners (TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
void setup_boundary_element_info ()
void setup_boundary_element_info (std::ostream &outfile)
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void node_update (const bool &update_all_solid_nodes=false)
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Protected Attributes
GmshParameters * Gmsh_parameters_pt
Parameters.
Protected Attributes inherited from oomph::TetMeshBase
Vector< Vector< FiniteElement * > > Region_element_pt
Vector< double > Region_attribute
Vector< std::map< unsigned, Vector< FiniteElement * > > > Boundary_region_element_pt
Storage for elements adjacent to a boundary in a particular region.
Vector< std::map< unsigned, Vector< int > > > Face_index_region_at_boundary
TetMeshFacetedClosedSurface * Outer_boundary_pt
Faceted surface that defines outer boundaries.
Vector< TetMeshFacetedSurface * > Internal_surface_pt
Vector to faceted surfaces that define internal boundaries.
std::map< unsigned, TetMeshFacetedSurface * > Tet_mesh_faceted_surface_pt
std::map< unsigned, TetMeshFacet * > Tet_mesh_facet_pt
std::map< unsigned, Vector< Vector< double > > > Triangular_facet_vertex_boundary_coordinate
TimeStepper * Time_stepper_pt
Timestepper used to build nodes.
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Private Member Functions
void build_it (TimeStepper *time_stepper_pt, const bool &use_mesh_grading_from_file)
void build_from_scaffold (GmshTetScaffoldMesh *tmp_scaffold_mesh_pt, TimeStepper *time_stepper_pt)
Build unstructured tet gmesh mesh based on output from scaffold.
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::TetMeshBase
static double Tolerance_for_boundary_finding = 1.0e-5
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Detailed Description
template<class ELEMENT>
class oomph::GmshTetMesh< ELEMENT >
Forward declaration.
/////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////
Constructor & Destructor Documentation
GmshTetMesh() [1/2]
template<class ELEMENT > oomph::GmshTetMesh< ELEMENT >::GmshTetMesh (GmshParameters * gmsh_parameters_pt, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) inline
Constructor.
       : Gmsh_parameters_pt(gmsh_parameters_pt)
     {
       bool use_mesh_grading_from_file = false;
       build_it(time_stepper_pt, use_mesh_grading_from_file);
     }
References oomph::GmshTetMesh< ELEMENT >::build_it().
GmshTetMesh() [2/2]
template<class ELEMENT > oomph::GmshTetMesh< ELEMENT >::GmshTetMesh (GmshParameters * gmsh_parameters_pt, const bool & use_mesh_grading_from_file, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) inline
Constructor. If boolean is set to true, the target element sizes are read from file (used during adaptation; otherwise uniform target size is used).
       : Gmsh_parameters_pt(gmsh_parameters_pt)
     {
       build_it(time_stepper_pt, use_mesh_grading_from_file);
     }
References oomph::GmshTetMesh< ELEMENT >::build_it().
Member Function Documentation
build_from_scaffold()
template<class ELEMENT > void oomph::GmshTetMesh< ELEMENT >::build_from_scaffold (GmshTetScaffoldMesh * tmp_scaffold_mesh_pt, TimeStepper * time_stepper_pt) inline private
Build unstructured tet gmesh mesh based on output from scaffold.
     {
       // Mesh can only be built with 3D Telements.
       MeshChecker::assert_geometric_element<TElementGeometricBase, ELEMENT>(3);
       // Create space for elements
       unsigned nelem = tmp_scaffold_mesh_pt->nelement();
       Element_pt.resize(nelem);
       // Relation between elements pointers and numbers in old mesh
       std::map<FiniteElement*, unsigned> scaffold_mesh_element_number;
       // Create space for nodes
       unsigned nnode_scaffold = tmp_scaffold_mesh_pt->nnode();
       Node_pt.resize(nnode_scaffold);
       // Set number of boundaries
       unsigned nbound = tmp_scaffold_mesh_pt->nboundary();
       set_nboundary(nbound);
       // Resize boundary info stuff
       Boundary_element_pt.resize(nbound); // hierher   shouldn't this be a map?
       Face_index_at_boundary.resize(nbound); // hierher shouldn't this be a map?
       Boundary_region_element_pt.resize(nbound);
       Face_index_region_at_boundary.resize(nbound);
       // Build elements
       for (unsigned e = 0; e < nelem; e++)
       {
         Element_pt[e] = new ELEMENT;
       }
       // Number of nodes per element
       unsigned nnod_el = tmp_scaffold_mesh_pt->finite_element_pt(0)->nnode();
       // Setup map to check the (pseudo-)global node number
       // Nodes whose number is zero haven't been copied across
       // into the mesh yet.
       std::map<Node*, unsigned> global_number;
       unsigned global_count = 0;
       // Loop over elements in scaffold mesh, visit their nodes
       for (unsigned e = 0; e < nelem; e++)
       {
         // Setup reverse lookup scheme to decipher lookup schemes from
         // scaffold mesh
         scaffold_mesh_element_number[tmp_scaffold_mesh_pt->finite_element_pt(
           e)] = e;
         // Loop over all nodes in element
         for (unsigned j = 0; j < nnod_el; j++)
         {
           // Pointer to node in the scaffold mesh
           Node* scaffold_node_pt =
             tmp_scaffold_mesh_pt->finite_element_pt(e)->node_pt(j);
           // Get the (pseudo-)global node number in scaffold mesh
           // (It's zero [=default] if not visited this one yet)
           unsigned j_global = global_number[scaffold_node_pt];
           // Haven't done this one yet
           if (j_global == 0)
           {
             // Get pointer to set of mesh boundaries that this
             // scaffold node occupies; NULL if the node is not on any boundary
             std::set<unsigned>* boundaries_pt;
             scaffold_node_pt->get_boundaries_pt(boundaries_pt);
             // Is it on boundaries?
             if (boundaries_pt != 0)
             {
               // Create new boundary node
               Node* new_node_pt = finite_element_pt(e)->construct_boundary_node(
                 j, time_stepper_pt);
               // Give it a number (not necessarily the global node
               // number in the scaffold mesh -- we just need something
               // to keep track...)
               global_count++;
               global_number[scaffold_node_pt] = global_count;
               // Add to boundaries
               for (std::set<unsigned>::iterator it = boundaries_pt->begin();
                    it != boundaries_pt->end();
                    ++it)
               {
                 add_boundary_node(*it, new_node_pt);
               }
             }
             // Build normal node
             else
             {
               // Create new normal node
               finite_element_pt(e)->construct_node(j, time_stepper_pt);
               // Give it a number (not necessarily the global node
               // number in the scaffold mesh -- we just need something
               // to keep track...)
               global_count++;
               global_number[scaffold_node_pt] = global_count;
             }
             // Copy new node, created using the NEW element's construct_node
             // function into global storage, using the same global
             // node number that we've just associated with the
             // corresponding node in the scaffold mesh
             Node_pt[global_count - 1] = finite_element_pt(e)->node_pt(j);
             // Assign coordinates
             Node_pt[global_count - 1]->x(0) = scaffold_node_pt->x(0);
             Node_pt[global_count - 1]->x(1) = scaffold_node_pt->x(1);
             Node_pt[global_count - 1]->x(2) = scaffold_node_pt->x(2);
           }
           // This one has already been done: Copy across
           else
           {
             finite_element_pt(e)->node_pt(j) = Node_pt[j_global - 1];
           }
         }
         // Now figure out which boundaries the faces are on
         FiniteElement* fe_pt = finite_element_pt(e);
         for (unsigned f = 0; f < 4; f++)
         {
           Node* face_node0_pt = 0;
           Node* face_node1_pt = 0;
           Node* face_node2_pt = 0;
           switch (f)
           {
             case 0:
               face_node0_pt = fe_pt->node_pt(1);
               face_node1_pt = fe_pt->node_pt(2);
               face_node2_pt = fe_pt->node_pt(3);
               break;
             case 1:
               face_node0_pt = fe_pt->node_pt(0);
               face_node1_pt = fe_pt->node_pt(2);
               face_node2_pt = fe_pt->node_pt(3);
               break;
             case 2:
               face_node0_pt = fe_pt->node_pt(0);
               face_node1_pt = fe_pt->node_pt(1);
               face_node2_pt = fe_pt->node_pt(3);
               break;
             case 3:
               face_node0_pt = fe_pt->node_pt(0);
               face_node1_pt = fe_pt->node_pt(1);
               face_node2_pt = fe_pt->node_pt(2);
               break;
             default:
               std::ostringstream error_message;
               error_message << "Wrong face number " << f << std::endl;
               throw OomphLibError(error_message.str(),
                                   OOMPH_CURRENT_FUNCTION,
                                   OOMPH_EXCEPTION_LOCATION);
           }
           // If any of the boundary sets are empty we don't have
           // three nodes on the boundary...
           std::set<unsigned>* bc0_pt;
           face_node0_pt->get_boundaries_pt(bc0_pt);
           if (bc0_pt != 0)
           {
             std::set<unsigned>* bc1_pt;
             face_node1_pt->get_boundaries_pt(bc1_pt);
             if (bc1_pt != 0)
             {
               std::set<unsigned>* bc2_pt;
               face_node2_pt->get_boundaries_pt(bc2_pt);
               if (bc2_pt != 0)
               {
                 std::set<unsigned> common_bound_0_and_1;
                 std::set_intersection(
                   bc0_pt->begin(),
                   bc0_pt->end(),
                   bc1_pt->begin(),
                   bc1_pt->end(),
                   std::inserter(common_bound_0_and_1,
                                 common_bound_0_and_1.begin()));
                 std::set<unsigned> common_bound_0_and_1_and_2;
                 std::set_intersection(
                   common_bound_0_and_1.begin(),
                   common_bound_0_and_1.end(),
                   bc2_pt->begin(),
                   bc2_pt->end(),
                   std::inserter(common_bound_0_and_1_and_2,
                                 common_bound_0_and_1_and_2.begin()));
                 for (std::set<unsigned>::iterator it =
                        common_bound_0_and_1_and_2.begin();
                      it != common_bound_0_and_1_and_2.end();
                      it++)
                 {
                   Boundary_element_pt[(*it)].push_back(fe_pt);
                   Face_index_at_boundary[(*it)].push_back(f);
                 }
               }
             }
           }
         }
       }
       // Copy across region information (scaffold mesh is a friend)
       unsigned nr = tmp_scaffold_mesh_pt->Region_element_pt.size();
       Region_attribute.resize(nr);
       Region_element_pt.resize(nr);
       for (unsigned i = 0; i < nr; i++)
       { //--
         Region_attribute[i] = tmp_scaffold_mesh_pt->Region_attribute[i];
         unsigned nel = tmp_scaffold_mesh_pt->Region_element_pt[i].size();
         Region_element_pt[i].resize(nel);
         for (unsigned e = 0; e < nel; e++)
         {
           FiniteElement* scaff_el_pt =
             tmp_scaffold_mesh_pt->Region_element_pt[i][e];
           unsigned scaff_el_number = scaffold_mesh_element_number[scaff_el_pt];
           Region_element_pt[i][e] =
             dynamic_cast<FiniteElement*>(Element_pt[scaff_el_number]);
           // Now figure out which boundaries the faces are on (again!)
           FiniteElement* fe_pt = Region_element_pt[i][e];
           for (unsigned f = 0; f < 4; f++)
           {
             Node* face_node0_pt = 0;
             Node* face_node1_pt = 0;
             Node* face_node2_pt = 0;
             switch (f)
             {
               case 0:
                 face_node0_pt = fe_pt->node_pt(1);
                 face_node1_pt = fe_pt->node_pt(2);
                 face_node2_pt = fe_pt->node_pt(3);
                 break;
               case 1:
                 face_node0_pt = fe_pt->node_pt(0);
                 face_node1_pt = fe_pt->node_pt(2);
                 face_node2_pt = fe_pt->node_pt(3);
                 break;
               case 2:
                 face_node0_pt = fe_pt->node_pt(0);
                 face_node1_pt = fe_pt->node_pt(1);
                 face_node2_pt = fe_pt->node_pt(3);
                 break;
               case 3:
                 face_node0_pt = fe_pt->node_pt(0);
                 face_node1_pt = fe_pt->node_pt(1);
                 face_node2_pt = fe_pt->node_pt(2);
                 break;
               default:
                 std::ostringstream error_message;
                 error_message << "Wrong face number " << f << std::endl;
                 throw OomphLibError(error_message.str(),
                                     OOMPH_CURRENT_FUNCTION,
                                     OOMPH_EXCEPTION_LOCATION);
             }
             // If any of the boundary sets are empty we don't have
             // three nodes on the boundary...
             std::set<unsigned>* bc0_pt;
             face_node0_pt->get_boundaries_pt(bc0_pt);
             if (bc0_pt != 0)
             {
               std::set<unsigned>* bc1_pt;
               face_node1_pt->get_boundaries_pt(bc1_pt);
               if (bc1_pt != 0)
               {
                 std::set<unsigned>* bc2_pt;
                 face_node2_pt->get_boundaries_pt(bc2_pt);
                 if (bc2_pt != 0)
                 {
                   std::set<unsigned> common_bound_0_and_1;
                   std::set_intersection(
                     bc0_pt->begin(),
                     bc0_pt->end(),
                     bc1_pt->begin(),
                     bc1_pt->end(),
                     std::inserter(common_bound_0_and_1,
                                   common_bound_0_and_1.begin()));
                   std::set<unsigned> common_bound_0_and_1_and_2;
                   std::set_intersection(
                     common_bound_0_and_1.begin(),
                     common_bound_0_and_1.end(),
                     bc2_pt->begin(),
                     bc2_pt->end(),
                     std::inserter(common_bound_0_and_1_and_2,
                                   common_bound_0_and_1_and_2.begin()));
                   for (std::set<unsigned>::iterator it =
                          common_bound_0_and_1_and_2.begin();
                        it != common_bound_0_and_1_and_2.end();
                        it++)
                   {
                     Boundary_region_element_pt[(*it)][Region_attribute[i]]
                       .push_back(fe_pt);
                     Face_index_region_at_boundary[(*it)][Region_attribute[i]]
                       .push_back(f);
                   }
                 }
               }
             }
           }
         }
       }
       // Lookup scheme has now been setup
       Lookup_for_elements_next_boundary_is_setup = true;
       // At this point we've created all the elements and
       // created their vertex nodes. Now we need to create
       // the additional (midside and internal) nodes!
       // Get number of nodes along element edge
       unsigned n_node_1d = finite_element_pt(0)->nnode_1d();
       // At the moment we're only able to deal with nnode_1d=2 or 3.
       if ((n_node_1d != 2) && (n_node_1d != 3))
       {
         std::ostringstream error_message;
         error_message << "Mesh generation from gmsh currently only works\n";
         error_message << "for nnode_1d = 2 or 3. You're trying to use it\n";
         error_message << "for nnode_1d=" << n_node_1d << std::endl;
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
       // Storage for the local coordinate of the new node
       Vector<double> s(3);
       // Map associating edge with midside node
       std::map<std::pair<Node*, Node*>, Node*> midside_node_pt;
       // Loop over all elements
       for (unsigned e = 0; e < nelem; e++)
       {
         // Cache pointers to the elements
         FiniteElement* const el_pt = this->finite_element_pt(e);
         FiniteElement* const simplex_el_pt =
           tmp_scaffold_mesh_pt->finite_element_pt(e);
         // Loop over the edges
         for (unsigned j = 0; j < 6; ++j)
         {
           Node* nod0_pt = 0;
           Node* nod1_pt = 0;
           unsigned new_node_number = 0;
           std::pair<Node*, Node*> edge;
           switch (j)
           {
             case 0:
               nod0_pt = el_pt->node_pt(0);
               nod1_pt = el_pt->node_pt(1);
               new_node_number = 4;
               break;
             case 1:
               nod0_pt = el_pt->node_pt(0);
               nod1_pt = el_pt->node_pt(2);
               new_node_number = 5;
               break;
             case 2:
               nod0_pt = el_pt->node_pt(0);
               nod1_pt = el_pt->node_pt(3);
               new_node_number = 6;
               break;
             case 3:
               nod0_pt = el_pt->node_pt(1);
               nod1_pt = el_pt->node_pt(2);
               new_node_number = 7;
               break;
             case 4:
               nod0_pt = el_pt->node_pt(2);
               nod1_pt = el_pt->node_pt(3);
               new_node_number = 8;
               break;
             case 5:
               nod0_pt = el_pt->node_pt(1);
               nod1_pt = el_pt->node_pt(3);
               new_node_number = 9;
               break;
             default:
               std::ostringstream error_message;
               error_message << "Wrong edge number " << j << std::endl;
               throw OomphLibError(error_message.str(),
                                   OOMPH_CURRENT_FUNCTION,
                                   OOMPH_EXCEPTION_LOCATION);
           }
           // Identify existence of node via edge
           edge = std::make_pair(std::min(nod0_pt, nod1_pt),
                                 std::max(nod0_pt, nod1_pt));
           Node* existing_node_pt = midside_node_pt[edge];
           if (existing_node_pt == 0)
           {
             // If any of the boundary sets are empty we don't have
             // two edge nodes on the boundary...
             std::set<unsigned> common_bound_0_and_1;
             std::set<unsigned>* bc0_pt;
             nod0_pt->get_boundaries_pt(bc0_pt);
             if (bc0_pt != 0)
             {
               std::set<unsigned>* bc1_pt;
               nod1_pt->get_boundaries_pt(bc1_pt);
               if (bc1_pt != 0)
               {
                 std::set_intersection(
                   bc0_pt->begin(),
                   bc0_pt->end(),
                   bc1_pt->begin(),
                   bc1_pt->end(),
                   std::inserter(common_bound_0_and_1,
                                 common_bound_0_and_1.begin()));
               }
             }
             // Storage for the new node
             Node* new_node_pt = 0;
             // New non-boundary node:
             if (common_bound_0_and_1.size() == 0)
             {
               new_node_pt =
                 el_pt->construct_node(new_node_number, time_stepper_pt);
             }
             // New boundary node
             else
             {
               new_node_pt = el_pt->construct_boundary_node(new_node_number,
                                                            time_stepper_pt);
               for (std::set<unsigned>::iterator it =
                      common_bound_0_and_1.begin();
                    it != common_bound_0_and_1.end();
                    it++)
               {
                 this->add_boundary_node((*it), new_node_pt);
               }
             }
             // Find the local coordinates of the node
             el_pt->local_coordinate_of_node(new_node_number, s);
             // Find the coordinates of the new node from the existing
             // and fully-functional element in the scaffold mesh
             for (unsigned i = 0; i < 3; i++)
             {
               new_node_pt->x(i) = simplex_el_pt->interpolated_x(s, i);
             }
             // Associate node with edge
             midside_node_pt[edge] = new_node_pt;
             // Add node to mesh
             Node_pt.push_back(new_node_pt);
           }
           // Node already exists
           else
           {
             el_pt->node_pt(new_node_number) = existing_node_pt;
           }
         }
       }
     }
References oomph::Mesh::add_boundary_node(), oomph::Mesh::Boundary_element_pt, oomph::TetMeshBase::Boundary_region_element_pt, oomph::FiniteElement::construct_boundary_node(), oomph::FiniteElement::construct_node(), e(), oomph::Mesh::Element_pt, f(), oomph::Mesh::Face_index_at_boundary, oomph::TetMeshBase::Face_index_region_at_boundary, oomph::Mesh::finite_element_pt(), oomph::Node::get_boundaries_pt(), i, oomph::FiniteElement::interpolated_x(), j, oomph::FiniteElement::local_coordinate_of_node(), oomph::Mesh::Lookup_for_elements_next_boundary_is_setup, max, min, oomph::Mesh::nboundary(), oomph::Mesh::nelement(), oomph::FiniteElement::nnode(), oomph::Mesh::nnode(), oomph::FiniteElement::nnode_1d(), oomph::FiniteElement::node_pt(), oomph::Mesh::Node_pt, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::TetMeshBase::Region_attribute, oomph::TetMeshBase::Region_element_pt, s, oomph::Mesh::set_nboundary(), and oomph::Node::x().
Referenced by oomph::GmshTetMesh< ELEMENT >::build_it().
build_it()
template<class ELEMENT > void oomph::GmshTetMesh< ELEMENT >::build_it (TimeStepper * time_stepper_pt, const bool & use_mesh_grading_from_file) inline private
     {
       // Mesh can only be built with 3D Telements.
       MeshChecker::assert_geometric_element<TElementGeometricBase, ELEMENT>(3);
       // Transfer data from parameters
       TetMeshFacetedClosedSurface* outer_boundary_pt =
         Gmsh_parameters_pt->outer_boundary_pt();
       Vector<TetMeshFacetedSurface*> internal_surface_pt =
         Gmsh_parameters_pt->internal_surface_pt();
       // Remember timestepper
       Time_stepper_pt = time_stepper_pt;
       // Store the boundary
       Outer_boundary_pt = outer_boundary_pt;
       // Setup reverse lookup scheme
       {
         unsigned n_facet = Outer_boundary_pt->nfacet();
         for (unsigned f = 0; f < n_facet; f++)
         {
           unsigned b = Outer_boundary_pt->one_based_facet_boundary_id(f);
           if (b != 0)
           {
             Tet_mesh_faceted_surface_pt[b - 1] = Outer_boundary_pt;
             Tet_mesh_facet_pt[b - 1] = Outer_boundary_pt->facet_pt(f);
           }
           else
           {
             std::ostringstream error_message;
             error_message << "Boundary IDs have to be one-based. Yours is " << b
                           << "\n";
             throw OomphLibError(error_message.str(),
                                 OOMPH_CURRENT_FUNCTION,
                                 OOMPH_EXCEPTION_LOCATION);
           }
         }
       }
       // Store the internal boundary
       Internal_surface_pt = internal_surface_pt;
       // Setup reverse lookup scheme
       {
         unsigned n = Internal_surface_pt.size();
         for (unsigned i = 0; i < n; i++)
         {
           unsigned n_facet = Internal_surface_pt[i]->nfacet();
           for (unsigned f = 0; f < n_facet; f++)
           {
             unsigned b = Internal_surface_pt[i]->one_based_facet_boundary_id(f);
             if (b != 0)
             {
               Tet_mesh_faceted_surface_pt[b - 1] = Internal_surface_pt[i];
               Tet_mesh_facet_pt[b - 1] = Internal_surface_pt[i]->facet_pt(f);
             }
             else
             {
               std::ostringstream error_message;
               error_message << "Boundary IDs have to be one-based. Yours is "
                             << b << "\n";
               throw OomphLibError(error_message.str(),
                                   OOMPH_CURRENT_FUNCTION,
                                   OOMPH_EXCEPTION_LOCATION);
             }
           }
         }
       }
       // Build scaffold
       GmshTetScaffoldMesh* tmp_scaffold_mesh_pt =
         new GmshTetScaffoldMesh(Gmsh_parameters_pt, use_mesh_grading_from_file);
       // Convert mesh from scaffold to actual mesh
       build_from_scaffold(tmp_scaffold_mesh_pt, time_stepper_pt);
       // Kill the scaffold
       delete tmp_scaffold_mesh_pt;
       tmp_scaffold_mesh_pt = 0;
       // Setup boundary coordinates
       unsigned nb = nboundary();
       for (unsigned b = 0; b < nb; b++)
       {
         bool switch_normal = false;
         setup_boundary_coordinates<ELEMENT>(b, switch_normal);
       }
       // Now snap onto geometric objects associated with triangular facets
       // (if any!)
       snap_nodes_onto_geometric_objects();
     }
References b, oomph::GmshTetMesh< ELEMENT >::build_from_scaffold(), f(), oomph::TetMeshFacetedSurface::facet_pt(), oomph::GmshTetMesh< ELEMENT >::Gmsh_parameters_pt, i, oomph::TetMeshBase::Internal_surface_pt, oomph::GmshParameters::internal_surface_pt(), n, nb, oomph::Mesh::nboundary(), oomph::TetMeshFacetedSurface::nfacet(), oomph::TetMeshFacetedSurface::one_based_facet_boundary_id(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::TetMeshBase::Outer_boundary_pt, oomph::GmshParameters::outer_boundary_pt(), oomph::TetMeshBase::snap_nodes_onto_geometric_objects(), oomph::TetMeshBase::Tet_mesh_facet_pt, oomph::TetMeshBase::Tet_mesh_faceted_surface_pt, and oomph::TetMeshBase::Time_stepper_pt.
Referenced by oomph::GmshTetMesh< ELEMENT >::GmshTetMesh().
Member Data Documentation
Gmsh_parameters_pt
template<class ELEMENT > GmshParameters* oomph::GmshTetMesh< ELEMENT >::Gmsh_parameters_pt protected
Parameters.
Referenced by oomph::GmshTetMesh< ELEMENT >::build_it(), and oomph::RefineableGmshTetMesh< ELEMENT >::initialise_adaptation_data().
The documentation for this class was generated from the following file:
gmsh_tet_mesh.template.h