MercuryDPM: t_convergence_2d.cc File Reference
t_convergence_2d.cc File Reference
#include "generic.h"
#include "poisson.h"
#include "meshes/simple_rectangular_tri_mesh.h"
Classes
class PoissonProblem< ELEMENT >
Micky mouse Poisson problem.
Namespaces
TanhSolnForPoisson
Namespace for exact solution for Poisson equation with "sharp step".
Functions
void TanhSolnForPoisson::get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void TanhSolnForPoisson::get_exact_u (const Vector< double > &x, double &u)
Exact solution as a scalar.
void TanhSolnForPoisson::get_source (const Vector< double > &x, double &source)
Source function to make it an exact solution.
int main (int argc, char *argv[])
Demonstrate how to solve Poisson problem.
Function Documentation
main()
int main (int argc , char * argv[])
Demonstrate how to solve Poisson problem.
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Label for output
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  DocInfo doc_info;
  // Output directory
  doc_info.set_directory("RESLT");
  // Step number
  doc_info.number()=0;
  //Set step orientation
  TanhSolnForPoisson::Beta=0.4;
  // Number of steps (reduced for validation)
  unsigned nstep = 7;
  if (CommandLineArgs::Argc>1)
   {
    nstep=3;
   }
  // Output for convergence data
  ofstream convergence_file("RESLT/convergence.dat");
  convergence_file << "VARIABLES=\"log h\",\"log e\",\"theory\",\"log u\" "
                   << std::endl;
  cout << "Linear elements " << std::endl;
  cout << "================" << std::endl << std::endl;
  //Tecplot output separator for convergence results
  convergence_file << "ZONE T=\"Linear element\"" << std::endl;
  for (unsigned h_power=1;h_power<nstep+1;h_power++)
   {
    //Set up the problem
    PoissonProblem<TPoissonElement<2,2> >
     problem(&TanhSolnForPoisson::get_source,h_power);
    // Solve the problem
    problem.newton_solve();
    //Output solution & convergence data
    problem.doc_solution(doc_info,convergence_file);
    //Increment counter for solutions
    doc_info.number()++;
   }
  cout << "Quadratic elements " << std::endl;
  cout << "==================" << std::endl << std::endl;
  //Tecplot output separator for convergence results
  convergence_file << "ZONE T=\"Quadratic element\"" << std::endl;
  for (unsigned h_power=1;h_power<nstep+1;h_power++)
   {
    //Set up the problem
    PoissonProblem<TPoissonElement<2,3> >
     problem(&TanhSolnForPoisson::get_source,h_power);
    // Solve the problem
    problem.newton_solve();
    //Output solution & convergence data
    problem.doc_solution(doc_info,convergence_file);
    //Increment counter for solutions
    doc_info.number()++;
   }
  cout << "Cubicc elements " << std::endl;
  cout << "================" << std::endl << std::endl;
  //Tecplot output separator for convergence results
  convergence_file << "ZONE T=\"Cubic element\"" << std::endl;
  for (unsigned h_power=1;h_power<nstep+1;h_power++)
   {
    //Set up the problem
    PoissonProblem<TPoissonElement<2,4> >
     problem(&TanhSolnForPoisson::get_source,h_power);
    // Solve the problem
    problem.newton_solve();
    //Output solution & convergence data
    problem.doc_solution(doc_info,convergence_file);
    //Increment counter for solutions
    doc_info.number()++;
   }
  convergence_file.close();
 }
References oomph::CommandLineArgs::Argc, TanhSolnForPoisson::Beta, TanhSolnForPoisson::get_source(), oomph::DocInfo::number(), problem, oomph::DocInfo::set_directory(), and Flag_definition::setup().