MercuryDPM: Eigen::internal::visitor_impl< Visitor, Derived, Dynamic, false, false, ShortCircuitEvaluation > Struct Template Reference
Eigen::internal::visitor_impl< Visitor, Derived, Dynamic, false, false, ShortCircuitEvaluation > Struct Template Reference
#include <Visitor.h>
Public Types
using short_circuit = short_circuit_eval_impl< Visitor, ShortCircuitEvaluation >
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void run (const Derived &mat, Visitor &visitor)
Static Public Attributes
static constexpr bool RowMajor = Derived::IsRowMajor
Member Typedef Documentation
short_circuit
template<typename Visitor , typename Derived , bool ShortCircuitEvaluation> using Eigen::internal::visitor_impl< Visitor, Derived, Dynamic, false, false, ShortCircuitEvaluation >::short_circuit = short_circuit_eval_impl<Visitor, ShortCircuitEvaluation>
Member Function Documentation
run()
template<typename Visitor , typename Derived , bool ShortCircuitEvaluation> static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::visitor_impl< Visitor, Derived, Dynamic, false, false, ShortCircuitEvaluation >::run (const Derived & mat, Visitor & visitor) inline static
{
     const Index innerSize = RowMajor ? mat.cols() : mat.rows();
     const Index outerSize = RowMajor ? mat.rows() : mat.cols();
     if (innerSize == 0 || outerSize == 0) return;
     {
       visitor.init(mat.coeff(0, 0), 0, 0);
       if (short_circuit::run(visitor)) return;
       for (Index i = 1; i < innerSize; ++i) {
         Index r = RowMajor ? 0 : i;
         Index c = RowMajor ? i : 0;
         visitor(mat.coeff(r, c), r, c);
         if EIGEN_PREDICT_FALSE (short_circuit::run(visitor)) return;
       }
     }
     for (Index j = 1; j < outerSize; j++) {
       for (Index i = 0; i < innerSize; ++i) {
         Index r = RowMajor ? j : i;
         Index c = RowMajor ? i : j;
         visitor(mat.coeff(r, c), r, c);
         if EIGEN_PREDICT_FALSE (short_circuit::run(visitor)) return;
       }
     }
   }
References calibrate::c, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::coeff(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::cols(), EIGEN_PREDICT_FALSE, i, j, UniformPSDSelfTest::r, Eigen::RowMajor, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::rows(), and run().
Member Data Documentation
RowMajor
template<typename Visitor , typename Derived , bool ShortCircuitEvaluation> constexpr bool Eigen::internal::visitor_impl< Visitor, Derived, Dynamic, false, false, ShortCircuitEvaluation >::RowMajor = Derived::IsRowMajor static constexpr
The documentation for this struct was generated from the following file:
Visitor.h