MercuryDPM: Eigen::TensorSycl::internal::PacketWrapper< PacketReturnType, PacketSize > Struct Template Reference
Eigen::TensorSycl::internal::PacketWrapper< PacketReturnType, PacketSize > Struct Template Reference
#include <InteropHeaders.h>
Public Types
typedef ::Eigen::internal::unpacket_traits< PacketReturnType >::type Scalar
Static Public Member Functions
template<typename Index >
static EIGEN_DEVICE_FUNC Scalar scalarize (Index, PacketReturnType &)
static EIGEN_DEVICE_FUNC PacketReturnType convert_to_packet_type (Scalar in, Scalar)
static EIGEN_DEVICE_FUNC void set_packet (PacketReturnType, Scalar *)
Member Typedef Documentation
Scalar
template<typename PacketReturnType , int PacketSize> typedef ::Eigen::internal::unpacket_traits<PacketReturnType>::type Eigen::TensorSycl::internal::PacketWrapper< PacketReturnType, PacketSize >::Scalar
Member Function Documentation
convert_to_packet_type()
template<typename PacketReturnType , int PacketSize> static EIGEN_DEVICE_FUNC PacketReturnType Eigen::TensorSycl::internal::PacketWrapper< PacketReturnType, PacketSize >::convert_to_packet_type (Scalar in, Scalar) inline static
{
     return ::Eigen::internal::template plset<PacketReturnType>(in);
   }
scalarize()
template<typename PacketReturnType , int PacketSize> template<typename Index > static EIGEN_DEVICE_FUNC Scalar Eigen::TensorSycl::internal::PacketWrapper< PacketReturnType, PacketSize >::scalarize (Index , PacketReturnType &) inline static
{
     eigen_assert(false && "THERE IS NO PACKETIZE VERSION FOR  THE CHOSEN TYPE");
     abort();
   }
References eigen_assert.
Referenced by Eigen::TensorSycl::internal::TensorContractionKernel< OutScalar, LhsScalar, RhsScalar, OutAccessor, LhsMapper, RhsMapper, StorageIndex, Properties, TripleDim, Vectorizable, input_mapper_properties, IsFinal, contraction_tp >::store(), and Eigen::TensorSycl::internal::write().
set_packet()
template<typename PacketReturnType , int PacketSize> static EIGEN_DEVICE_FUNC void Eigen::TensorSycl::internal::PacketWrapper< PacketReturnType, PacketSize >::set_packet (PacketReturnType , Scalar *) inline static
{
     eigen_assert(false && "THERE IS NO PACKETIZE VERSION FOR  THE CHOSEN TYPE");
     abort();
   }
References eigen_assert.
Referenced by Eigen::TensorSycl::internal::TensorContractionKernel< OutScalar, LhsScalar, RhsScalar, OutAccessor, LhsMapper, RhsMapper, StorageIndex, Properties, TripleDim, Vectorizable, input_mapper_properties, IsFinal, contraction_tp >::compute_block_per_tile().
The documentation for this struct was generated from the following file:
InteropHeaders.h