MercuryDPM: TestProblem Namespace Reference
TestProblem Namespace Reference
Namespace for exact solution and problem parameters.
Functions
void source (const Vector< double > &x, Vector< double > &f)
Source function.
void mass_source (const Vector< double > &x, double &m)
Mass source.
void boundary_pressure (const double &time, const Vector< double > &x, const Vector< double > &n, double &result)
Pressure around the boundary of the domain.
void exact_soln (const Vector< double > &x, Vector< double > &soln)
Exact solution: q1,q2,div_q,p.
template<class ELEMENT >
void edge_sign_setup (Mesh *mesh_pt)
Variables
bool Use_point_source_solution =false
double Mass_source_strength =1000.0
Mass source strength.
double Mass_source_decay_exponent =50.0
Mass source strength.
double Element_area =0.01
Target element area for Triangle.
std::string Directory ="RESLT"
The directory in which the solution is output.
Detailed Description
Namespace for exact solution and problem parameters.
Function Documentation
boundary_pressure()
void TestProblem::boundary_pressure (const double & time, const Vector< double > & x, const Vector< double > & n, double & result)
Pressure around the boundary of the domain.
   {
    if (Use_point_source_solution)
     {
      result=0.0;
     }
    else
     {
      result=2*x[0]+3*x[1]-3.0/2.0;
     }
   }
References Use_point_source_solution, and plotDoE::x.
Referenced by DarcyProblem< ELEMENT >::create_pressure_elements().
edge_sign_setup()
template<class ELEMENT > void TestProblem::edge_sign_setup (Mesh * mesh_pt)
Global function that completes the edge sign setup – has to be called before projection in unstructured adaptation
  {
   // The dictionary keeping track of edge signs
   std::map<Edge,unsigned> assignments;
   // Loop over all elements
   unsigned n_element = mesh_pt->nelement();
   for(unsigned e=0;e<n_element;e++)
    {
     ELEMENT* el_pt = dynamic_cast<ELEMENT*>(mesh_pt->element_pt(e));
     // Assign edge signs: Loop over the vertex nodes (always
     // first 3 nodes for triangles)
     for(unsigned i=0;i<3;i++)
      {
       Node *nod_pt1, *nod_pt2;
       nod_pt1 = el_pt->node_pt(i);
       nod_pt2 = el_pt->node_pt((i+1)%3);
       Edge edge(nod_pt1,nod_pt2);
       unsigned status = assignments[edge];
       // This relies on the default value for an int being 0 in a map
       switch(status)
        {
         // If not assigned on either side, give it a + on current side
        case 0:
         assignments[edge]=1;
         break;
         // If assigned + on other side, give it a - on current side
        case 1:
         assignments[edge]=2;
         el_pt->sign_edge(i)=-1;
         break;
         // If assigned - on other side, give it a + on current side
        case 2:
         assignments[edge]=1;
         break;
        }
      } // end of loop over vertex nodes
    } // end of loop over elements
  }
References anonymous_namespace{skew_symmetric_matrix3.cpp}::assignments(), e(), oomph::Mesh::element_pt(), i, and oomph::Mesh::nelement().
exact_soln()
void TestProblem::exact_soln (const Vector< double > & x, Vector< double > & soln)
Exact solution: q1,q2,div_q,p.
   {
    if (Use_point_source_solution)
     {
      // q[0]
      soln[0]=0.0;
      // q[1]
      soln[1]=0.0;
      // div q
      soln[2]=0.0;
      // p
      soln[3]=0.0;
     }
    else
     {
      // q[0]
      soln[0]=x[0]*x[1]-x[1]*x[1];
      // q[1]
      soln[1]=x[0]+x[0]*x[0]-0.5*x[1]*x[1];
      // div q
      soln[2]=0;
      // p
      soln[3]=2*x[0]+3*x[1]-3.0/2.0;
     }
   }
References Use_point_source_solution, and plotDoE::x.
Referenced by DarcyProblem< ELEMENT >::complete_problem_setup(), and DarcyProblem< ELEMENT >::doc_solution().
mass_source()
void TestProblem::mass_source (const Vector< double > & x, double & m)
Mass source.
   {
    if (Use_point_source_solution)
     {
      double r=sqrt(x[0]*x[0]+x[1]*x[1]);
      m=Mass_source_strength*exp(-r*Mass_source_decay_exponent);
     }
    else
     {
      m=0.0;
     }
   }
References Eigen::bfloat16_impl::exp(), m, Mass_source_decay_exponent, Mass_source_strength, UniformPSDSelfTest::r, sqrt(), Use_point_source_solution, and plotDoE::x.
Referenced by DarcyProblem< ELEMENT >::complete_problem_setup().
source()
void TestProblem::source (const Vector< double > & x, Vector< double > & f)
Source function.
   {
    if (Use_point_source_solution)
     {
      f[0]=0.0;
      f[1]=0.0;
     }
    else
     {
      f[0]=x[0]*x[1]-x[1]*x[1]+2;
      f[1]=x[0]+x[0]*x[0]-0.5*x[1]*x[1]+3;
     }
   }
References f(), Use_point_source_solution, and plotDoE::x.
Referenced by ModalPoissonEquations< DIM >::add_generic_residual_contribution(), DarcyProblem< ELEMENT >::complete_problem_setup(), oomph::PoissonEquations< 1 >::compute_error(), c_interface_base< real >::copy_matrix(), c_interface_base< real >::copy_vector(), GelfandBratuElement< NNODE_1D >::fill_in_generic_dresidual_contribution(), oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst(), oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst(), oomph::SpaceTimeNavierStokesEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst(), oomph::NavierStokesEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst(), oomph::RefineableNavierStokesEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst(), GelfandBratuElement< NNODE_1D >::fill_in_generic_residual_contribution(), oomph::AdvectionDiffusionEquations< DIM >::fill_in_generic_residual_contribution_adv_diff(), oomph::RefineableAdvectionDiffusionEquations< DIM >::fill_in_generic_residual_contribution_adv_diff(), oomph::SteadyAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_adv_diff(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::fill_in_generic_residual_contribution_adv_diff_react(), oomph::RefineableAdvectionDiffusionReactionEquations< NREAGENT, DIM >::fill_in_generic_residual_contribution_adv_diff_react(), oomph::AxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), oomph::RefineableAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_axi_adv_diff(), oomph::AxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::BiharmonicEquations< DIM >::fill_in_generic_residual_contribution_biharmonic(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::fill_in_generic_residual_contribution_cons_adv_diff(), oomph::RefineableGeneralisedAdvectionDiffusionEquations< DIM >::fill_in_generic_residual_contribution_cons_adv_diff(), oomph::RefineableGeneralisedAxisymAdvectionDiffusionEquations::fill_in_generic_residual_contribution_cons_axisym_adv_diff(), oomph::FourierDecomposedHelmholtzEquations::fill_in_generic_residual_contribution_fourier_decomposed_helmholtz(), oomph::HelmholtzEquations< DIM >::fill_in_generic_residual_contribution_helmholtz(), oomph::RefineableHelmholtzEquations< DIM >::fill_in_generic_residual_contribution_helmholtz(), oomph::PMLHelmholtzEquations< DIM >::fill_in_generic_residual_contribution_helmholtz(), oomph::RefineablePMLHelmholtzEquations< DIM >::fill_in_generic_residual_contribution_helmholtz(), oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_lin_axi_nst(), oomph::LinearWaveEquations< DIM >::fill_in_generic_residual_contribution_lin_wave(), oomph::RefineableLinearWaveEquations< DIM >::fill_in_generic_residual_contribution_lin_wave(), oomph::MultiPoissonEquations< DIM, NFIELDS >::fill_in_generic_residual_contribution_multi_poisson(), oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::SpaceTimeNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::NavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::RefineableNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::PMLFourierDecomposedHelmholtzEquations::fill_in_generic_residual_contribution_pml_fourier_decomposed_helmholtz(), oomph::PoissonEquations< DIM >::fill_in_generic_residual_contribution_poisson(), oomph::RefineablePoissonEquations< DIM >::fill_in_generic_residual_contribution_poisson(), oomph::RefineableSphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), oomph::SphericalAdvectionDiffusionEquations::fill_in_generic_residual_contribution_spherical_adv_diff(), oomph::RefineableSpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::fill_in_generic_residual_contribution_ust_heat(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::fill_in_generic_residual_contribution_ust_heat(), oomph::RefineableSpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::fill_in_generic_residual_contribution_ust_heat(), oomph::RefineableUnsteadyHeatEquations< DIM >::fill_in_generic_residual_contribution_ust_heat(), oomph::UnsteadyHeatEquations< DIM >::fill_in_generic_residual_contribution_ust_heat(), RefineableModalPoissonEquations< DIM >::get_dresidual_dnodal_coordinates(), oomph::AxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::RefineableAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::get_dresidual_dnodal_coordinates(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::get_dresidual_dnodal_coordinates(), oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::get_dresidual_dnodal_coordinates(), oomph::NavierStokesEquations< DIM >::get_dresidual_dnodal_coordinates(), oomph::RefineableNavierStokesEquations< DIM >::get_dresidual_dnodal_coordinates(), oomph::PoissonEquations< DIM >::get_dresidual_dnodal_coordinates(), oomph::RefineablePoissonEquations< DIM >::get_dresidual_dnodal_coordinates(), oomph::SpaceTimeNavierStokesEquations< DIM >::get_dresidual_dnodal_coordinates(), oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::get_dresidual_dnodal_coordinates(), TwoNodePoissonElement::get_residuals(), SinSolution::get_source(), ExactSolnForUnsteadyHeat::get_source(), TanhSolnForLinearWave::get_source(), TanhSolnForUnsteadyHeat::get_source(), oomph::BiharmonicEquations< DIM >::get_source(), TanhSolnForPoisson::get_source(), ConstSourceForPoisson::get_source(), ArcTanSolnForPoisson::get_source(), GlobalParameters::get_source(), oomph::AdvectionDiffusionEquations< DIM >::get_source_adv_diff(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >::get_source_adv_diff_react(), oomph::AxisymAdvectionDiffusionEquations::get_source_axi_adv_diff(), oomph::SteadyAxisymAdvectionDiffusionEquations::get_source_axisym_adv_diff(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >::get_source_cons_adv_diff(), oomph::get_source_cons_axisym_adv_diff(), oomph::AxisymmetricNavierStokesEquations::get_source_fct_gradient(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::get_source_fct_gradient(), ExactSolution::get_source_for_unsteady_heat_validation(), oomph::FourierDecomposedHelmholtzEquations::get_source_fourier_decomposed_helmholtz(), oomph::LinearisedAxisymmetricNavierStokesEquations::get_source_gradient_base_flow(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::get_source_gradient_nst(), oomph::NavierStokesEquations< DIM >::get_source_gradient_nst(), oomph::SpaceTimeNavierStokesEquations< DIM >::get_source_gradient_nst(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::get_source_gradient_nst(), oomph::PoissonEquations< DIM >::get_source_gradient_poisson(), oomph::HelmholtzEquations< DIM >::get_source_helmholtz(), oomph::PMLHelmholtzEquations< DIM >::get_source_helmholtz(), oomph::LinearWaveEquations< DIM >::get_source_lin_wave(), oomph::MultiPoissonEquations< DIM, NFIELDS >::get_source_multi_poisson(), oomph::PMLFourierDecomposedHelmholtzEquations::get_source_pml_fourier_decomposed_helmholtz(), oomph::PoissonEquations< DIM >::get_source_poisson(), ModalPoissonEquations< DIM >::get_source_poisson(), oomph::SphericalAdvectionDiffusionEquations::get_source_spherical_adv_diff(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >::get_source_ust_heat(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::get_source_ust_heat(), oomph::UnsteadyHeatEquations< DIM >::get_source_ust_heat(), Global_parameters::source_function(), FishSolnOneDPoisson::source_function(), TanhSolnForPoisson::source_function(), ConstSourceForPoisson::source_function(), SolnForPoisson::source_function(), TanhSolnForMultiPoisson::source_function(), oomph::PressureAdvectionDiffusionValidation::source_function(), TanhSolnForAdvectionDiffusion::source_function(), GlobalPhysicalParameters::source_function(), TanhSolnForSteadyAxisymAdvectionDiffusion::source_function(), test_empty_fixed_size_tensor(), and test_empty_tensor().
Variable Documentation
Directory
std::string TestProblem::Directory ="RESLT"
The directory in which the solution is output.
Referenced by DarcyProblem< ELEMENT >::DarcyProblem(), DarcyProblem< ELEMENT >::doc_shape_functions(), DarcyProblem< ELEMENT >::doc_solution(), and main().
Element_area
double TestProblem::Element_area =0.01
Target element area for Triangle.
Referenced by DarcyProblem< ELEMENT >::DarcyProblem(), DarcyProblem< ELEMENT >::doc_solution(), and main().
Mass_source_decay_exponent
double TestProblem::Mass_source_decay_exponent =50.0
Mass source strength.
Referenced by mass_source().
Mass_source_strength
double TestProblem::Mass_source_strength =1000.0
Mass source strength.
Referenced by mass_source().
Use_point_source_solution
bool TestProblem::Use_point_source_solution =false
Flag to indicate that we want the forced solution a "point source" in the mass flux
Referenced by boundary_pressure(), DarcyProblem< ELEMENT >::DarcyProblem(), exact_soln(), main(), mass_source(), and source().