MercuryDPM: Eigen::SkewSymmetricMatrix3< Scalar_ > Class Template Reference
Eigen::SkewSymmetricMatrix3< Scalar_ > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
Represents a 3x3 skew symmetric matrix with its storage.
#include <SkewSymmetricMatrix3.h>
Public Types
typedef internal::traits< SkewSymmetricMatrix3 >::SkewSymmetricVectorType SkewSymmetricVectorType
typedef const SkewSymmetricMatrix3 & Nested
typedef Scalar_ Scalar
typedef internal::traits< SkewSymmetricMatrix3 >::StorageKind StorageKind
typedef internal::traits< SkewSymmetricMatrix3 >::StorageIndex StorageIndex
typedef SkewSymmetricWrapper< const CwiseNullaryOp< internal::scalar_constant_op< Scalar >, SkewSymmetricVectorType > > InitializeReturnType
Public Types inherited from Eigen::SkewSymmetricBase< SkewSymmetricMatrix3< Scalar_ > >
enum
typedef internal::traits< SkewSymmetricMatrix3< Scalar_ > >::SkewSymmetricVectorType SkewSymmetricVectorType
typedef SkewSymmetricVectorType::Scalar Scalar
typedef SkewSymmetricVectorType::RealScalar RealScalar
typedef internal::traits< SkewSymmetricMatrix3< Scalar_ > >::StorageKind StorageKind
typedef internal::traits< SkewSymmetricMatrix3< Scalar_ > >::StorageIndex StorageIndex
typedef Matrix< Scalar, RowsAtCompileTime, ColsAtCompileTime, 0, MaxRowsAtCompileTime, MaxColsAtCompileTime > DenseMatrixType
typedef DenseMatrixType DenseType
typedef SkewSymmetricMatrix3< Scalar > PlainObject
using SkewSymmetricProductReturnType = SkewSymmetricWrapper< const EIGEN_CWISE_BINARY_RETURN_TYPE(SkewSymmetricVectorType, typename OtherDerived::SkewSymmetricVectorType, product)>
using SkewSymmetricScaleReturnType = SkewSymmetricWrapper< const EIGEN_EXPR_BINARYOP_SCALAR_RETURN_TYPE(SkewSymmetricVectorType, Scalar, product)>
using ScaleSkewSymmetricReturnType = SkewSymmetricWrapper< const EIGEN_SCALAR_BINARYOP_EXPR_RETURN_TYPE(Scalar, SkewSymmetricVectorType, product)>
using SkewSymmetricSumReturnType = SkewSymmetricWrapper< const EIGEN_CWISE_BINARY_RETURN_TYPE(SkewSymmetricVectorType, typename OtherDerived::SkewSymmetricVectorType, sum)>
using SkewSymmetricDifferenceReturnType = SkewSymmetricWrapper< const EIGEN_CWISE_BINARY_RETURN_TYPE(SkewSymmetricVectorType, typename OtherDerived::SkewSymmetricVectorType, difference)>
Public Types inherited from Eigen::EigenBase< Derived >
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< Derived >::StorageKind StorageKind
Public Member Functions
EIGEN_DEVICE_FUNC const SkewSymmetricVectorType & vector () const
EIGEN_DEVICE_FUNC SkewSymmetricVectorType & vector ()
EIGEN_DEVICE_FUNC SkewSymmetricMatrix3 ()
EIGEN_DEVICE_FUNC SkewSymmetricMatrix3 (const Scalar &x, const Scalar &y, const Scalar &z)
EIGEN_DEVICE_FUNC SkewSymmetricMatrix3 (SkewSymmetricVectorType &&vec)
Constructs a SkewSymmetricMatrix3 from an r-value vector type.
template<typename OtherDerived >
EIGEN_DEVICE_FUNC SkewSymmetricMatrix3 (const MatrixBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC SkewSymmetricMatrix3 (const SkewSymmetricBase< OtherDerived > &other)
SkewSymmetricMatrix3 (const SkewSymmetricMatrix3 &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC SkewSymmetricMatrix3 & operator= (const SkewSymmetricBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC SkewSymmetricMatrix3 & operator= (const SkewSymmetricMatrix3 &other)
EIGEN_DEVICE_FUNC void setZero ()
Public Member Functions inherited from Eigen::SkewSymmetricBase< SkewSymmetricMatrix3< Scalar_ > >
EIGEN_DEVICE_FUNC const SkewSymmetricMatrix3< Scalar_ > & derived () const
EIGEN_DEVICE_FUNC SkewSymmetricMatrix3< Scalar_ > & derived ()
EIGEN_DEVICE_FUNC DenseMatrixType toDenseMatrix () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Scalar determinant () const
EIGEN_DEVICE_FUNC PlainObject transpose () const
EIGEN_DEVICE_FUNC DenseMatrixType exponential () const
EIGEN_DEVICE_FUNC const SkewSymmetricVectorType & vector () const
EIGEN_DEVICE_FUNC SkewSymmetricVectorType & vector ()
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const
EIGEN_DEVICE_FUNC Product< SkewSymmetricMatrix3< Scalar_ >, MatrixDerived, LazyProduct > operator* (const MatrixBase< MatrixDerived > &matrix) const
EIGEN_DEVICE_FUNC Product< SkewSymmetricMatrix3< Scalar_ >, MatrixDerived, LazyProduct > operator* (const SkewSymmetricBase< MatrixDerived > &matrix) const
EIGEN_DEVICE_FUNC SkewSymmetricScaleReturnType operator* (const Scalar &scalar) const
EIGEN_DEVICE_FUNC SkewSymmetricProductReturnType< OtherDerived > wedge (const SkewSymmetricBase< OtherDerived > &other) const
EIGEN_DEVICE_FUNC SkewSymmetricSumReturnType< OtherDerived > operator+ (const SkewSymmetricBase< OtherDerived > &other) const
EIGEN_DEVICE_FUNC SkewSymmetricDifferenceReturnType< OtherDerived > operator- (const SkewSymmetricBase< OtherDerived > &other) const
Public Member Functions inherited from Eigen::EigenBase< Derived >
constexpr EIGEN_DEVICE_FUNC Derived & derived ()
constexpr EIGEN_DEVICE_FUNC const Derived & derived () const
EIGEN_DEVICE_FUNC Derived & const_cast_derived () const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index size () const EIGEN_NOEXCEPT
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
template<typename Device >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< Derived, Device > device (Device &device)
template<typename Device >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< const Derived, Device > device (Device &device) const
Static Public Member Functions
static EIGEN_DEVICE_FUNC InitializeReturnType Zero ()
Protected Attributes
SkewSymmetricVectorType m_vector
Detailed Description
template<typename Scalar_>
class Eigen::SkewSymmetricMatrix3< Scalar_ >
Represents a 3x3 skew symmetric matrix with its storage.
Template Parameters
Scalar_ the type of coefficients
See also
class SkewSymmetricBase, class SkewSymmetricWrapper
Member Typedef Documentation
InitializeReturnType
template<typename Scalar_ > typedef SkewSymmetricWrapper<const CwiseNullaryOp<internal::scalar_constant_op<Scalar>, SkewSymmetricVectorType> > Eigen::SkewSymmetricMatrix3< Scalar_ >::InitializeReturnType
Nested
template<typename Scalar_ > typedef const SkewSymmetricMatrix3& Eigen::SkewSymmetricMatrix3< Scalar_ >::Nested
Scalar
template<typename Scalar_ > typedef Scalar_ Eigen::SkewSymmetricMatrix3< Scalar_ >::Scalar
SkewSymmetricVectorType
template<typename Scalar_ > typedef internal::traits<SkewSymmetricMatrix3>::SkewSymmetricVectorType Eigen::SkewSymmetricMatrix3< Scalar_ >::SkewSymmetricVectorType
StorageIndex
template<typename Scalar_ > typedef internal::traits<SkewSymmetricMatrix3>::StorageIndex Eigen::SkewSymmetricMatrix3< Scalar_ >::StorageIndex
StorageKind
template<typename Scalar_ > typedef internal::traits<SkewSymmetricMatrix3>::StorageKind Eigen::SkewSymmetricMatrix3< Scalar_ >::StorageKind
Constructor & Destructor Documentation
SkewSymmetricMatrix3() [1/6]
template<typename Scalar_ > EIGEN_DEVICE_FUNC Eigen::SkewSymmetricMatrix3< Scalar_ >::SkewSymmetricMatrix3 () inline
Default constructor without initialization
 {}
SkewSymmetricMatrix3() [2/6]
template<typename Scalar_ > EIGEN_DEVICE_FUNC Eigen::SkewSymmetricMatrix3< Scalar_ >::SkewSymmetricMatrix3 (const Scalar & x, const Scalar & y, const Scalar & z) inline
Constructor from three scalars
       : m_vector(x, y, z) {}
SkewSymmetricMatrix3() [3/6]
template<typename Scalar_ > EIGEN_DEVICE_FUNC Eigen::SkewSymmetricMatrix3< Scalar_ >::SkewSymmetricMatrix3 (SkewSymmetricVectorType && vec) inline explicit
Constructs a SkewSymmetricMatrix3 from an r-value vector type.
 : m_vector(std::move(vec)) {}
SkewSymmetricMatrix3() [4/6]
template<typename Scalar_ > template<typename OtherDerived > EIGEN_DEVICE_FUNC Eigen::SkewSymmetricMatrix3< Scalar_ >::SkewSymmetricMatrix3 (const MatrixBase< OtherDerived > & other) inline explicit
generic constructor from expression of the coefficients
 : m_vector(other) {}
SkewSymmetricMatrix3() [5/6]
template<typename Scalar_ > template<typename OtherDerived > EIGEN_DEVICE_FUNC Eigen::SkewSymmetricMatrix3< Scalar_ >::SkewSymmetricMatrix3 (const SkewSymmetricBase< OtherDerived > & other) inline
Copy constructor.
       : m_vector(other.vector()) {}
SkewSymmetricMatrix3() [6/6]
template<typename Scalar_ > Eigen::SkewSymmetricMatrix3< Scalar_ >::SkewSymmetricMatrix3 (const SkewSymmetricMatrix3< Scalar_ > & other) inline
copy constructor. prevent a default copy constructor from hiding the other templated constructor
 : m_vector(other.vector()) {}
Member Function Documentation
operator=() [1/2]
template<typename Scalar_ > template<typename OtherDerived > EIGEN_DEVICE_FUNC SkewSymmetricMatrix3& Eigen::SkewSymmetricMatrix3< Scalar_ >::operator= (const SkewSymmetricBase< OtherDerived > & other) inline
Copy operator.
{
     m_vector = other.vector();
     return *this;
   }
References Eigen::SkewSymmetricMatrix3< Scalar_ >::m_vector, and Eigen::SkewSymmetricBase< Derived >::vector().
operator=() [2/2]
template<typename Scalar_ > EIGEN_DEVICE_FUNC SkewSymmetricMatrix3& Eigen::SkewSymmetricMatrix3< Scalar_ >::operator= (const SkewSymmetricMatrix3< Scalar_ > & other) inline
This is a special case of the templated operator=. Its purpose is to prevent a default operator= from hiding the templated operator=.
{
     m_vector = other.vector();
     return *this;
   }
References Eigen::SkewSymmetricMatrix3< Scalar_ >::m_vector, and Eigen::SkewSymmetricMatrix3< Scalar_ >::vector().
setZero()
template<typename Scalar_ > EIGEN_DEVICE_FUNC void Eigen::SkewSymmetricMatrix3< Scalar_ >::setZero () inline
Sets all coefficients to zero.
 { m_vector.setZero(); }
References Eigen::SkewSymmetricMatrix3< Scalar_ >::m_vector.
vector() [1/2]
template<typename Scalar_ > EIGEN_DEVICE_FUNC SkewSymmetricVectorType& Eigen::SkewSymmetricMatrix3< Scalar_ >::vector () inline
Returns
a reference to the stored vector of coefficients.
 { return m_vector; }
References Eigen::SkewSymmetricMatrix3< Scalar_ >::m_vector.
vector() [2/2]
template<typename Scalar_ > EIGEN_DEVICE_FUNC const SkewSymmetricVectorType& Eigen::SkewSymmetricMatrix3< Scalar_ >::vector () const inline
const version of vector().
 { return m_vector; }
References Eigen::SkewSymmetricMatrix3< Scalar_ >::m_vector.
Referenced by anonymous_namespace{skew_symmetric_matrix3.cpp}::assignments(), anonymous_namespace{skew_symmetric_matrix3.cpp}::constructors(), anonymous_namespace{skew_symmetric_matrix3.cpp}::multiplyScale(), and Eigen::SkewSymmetricMatrix3< Scalar_ >::operator=().
Zero()
template<typename Scalar_ > static EIGEN_DEVICE_FUNC InitializeReturnType Eigen::SkewSymmetricMatrix3< Scalar_ >::Zero () inline static
Initializes a skew symmetric matrix with coefficients set to zero
 { return SkewSymmetricVectorType::Zero().asSkewSymmetric(); }
References oomph::PseudoSolidHelper::Zero.
Member Data Documentation
m_vector
template<typename Scalar_ > SkewSymmetricVectorType Eigen::SkewSymmetricMatrix3< Scalar_ >::m_vector protected
Referenced by Eigen::SkewSymmetricMatrix3< Scalar_ >::operator=(), Eigen::SkewSymmetricMatrix3< Scalar_ >::setZero(), and Eigen::SkewSymmetricMatrix3< Scalar_ >::vector().
The documentation for this class was generated from the following file:
SkewSymmetricMatrix3.h