MercuryDPM: doc_sparse_macro_node_update.cc File Reference
doc_sparse_macro_node_update.cc File Reference
#include "generic.h"
#include "poisson.h"
#include "meshes/fish_mesh.h"
#include "circle_as_generalised_element.h"
Functions
int main ()
Driver to document sparse MacroElement-based node update.
Function Documentation
main()
int main ()
Driver to document sparse MacroElement-based node update.
 {
  // Shorthand for element type
  typedef MacroElementNodeUpdateElement<RefineableQPoissonElement<2,3> >
   ELEMENT;
  // Set coordinates and radius for the circle that will become the fish back
  double x_c=0.5;
  double y_c=-0.2;
  double r_back=1.0;
  // Build geometric object that will become the fish back
   ElasticallySupportedRingElement* Fish_back_pt=
    new ElasticallySupportedRingElement(x_c,y_c,r_back);
  // Build fish mesh with geometric object that specifies the fish back
  MacroElementNodeUpdateRefineableFishMesh<ELEMENT>* Fish_mesh_pt=new
   MacroElementNodeUpdateRefineableFishMesh<ELEMENT>(Fish_back_pt);
  // Number of plot points in each coordinate direction.
  unsigned npts=11;
  ofstream some_file;
  char filename[100];
  // Output initial mesh
  unsigned count=0;
  sprintf(filename,"RESLT/soln%i.dat",count);
  some_file.open(filename);
  Fish_mesh_pt->output(some_file,npts);
  some_file.close();
  count++;
  // Increment y_c
  Fish_back_pt->y_c()+=0.2;
  // Adjust each node in turn and doc
  unsigned nnod=Fish_mesh_pt->nnode();
  for (unsigned i=0;i<nnod;i++)
   {
    // Update individual nodal position
    Fish_mesh_pt->node_pt(i)->node_update();
    // Doc mesh
    sprintf(filename,"RESLT/soln%i.dat",count);
    some_file.open(filename);
    Fish_mesh_pt->output(some_file,npts);
    some_file.close();
    count++;
   }
 } // end of main
References MergeRestartFiles::filename, i, oomph::Mesh::nnode(), oomph::Mesh::node_pt(), oomph::Node::node_update(), oomph::Mesh::output(), and oomph::GeneralCircle::y_c().