MercuryDPM: benchmark.h File Reference
benchmark.h File Reference
#include <stddef.h>
#include <stdint.h>
#include <vector>
Classes
class testing::Benchmark
Namespaces
testing
Macros
#define BENCHMARK(f) static ::testing::Benchmark* _benchmark_##f __attribute__((unused)) = (new ::testing::Benchmark(#f, f))
Functions
void SetBenchmarkFlopsProcessed (int64_t)
void StopBenchmarkTiming ()
void StartBenchmarkTiming ()
Macro Definition Documentation
BENCHMARK
#define BENCHMARK (f) static ::testing::Benchmark* _benchmark_##f __attribute__((unused)) = (new ::testing::Benchmark(#f, f))
Function Documentation
SetBenchmarkFlopsProcessed()
void SetBenchmarkFlopsProcessed (int64_t x)
 { g_flops_processed = x; }
References g_flops_processed, and plotDoE::x.
Referenced by BenchmarkSuite< Device, T >::finalizeBenchmark().
StartBenchmarkTiming()
void StartBenchmarkTiming ()
{
   if (g_benchmark_start_time_ns == 0) {
     g_benchmark_start_time_ns = NanoTime();
   }
 }
References g_benchmark_start_time_ns, and NanoTime().
Referenced by BenchmarkSuite< Device, T >::algebraicFunc(), BenchmarkSuite< Device, T >::broadcasting(), BenchmarkSuite< Device, T >::coeffWiseOp(), BenchmarkSuite< Device, T >::colChip(), BenchmarkSuite< Device, T >::colReduction(), BenchmarkSuite< Device, T >::contraction(), BenchmarkSuite< Device, T >::convolution(), BenchmarkSuite< Device, T >::fullReduction(), BenchmarkSuite< Device, T >::memcpy(), BenchmarkSuite< Device, T >::padding(), BenchmarkSuite< Device, T >::random(), BenchmarkSuite< Device, T >::rowChip(), BenchmarkSuite< Device, T >::rowReduction(), BenchmarkSuite< Device, T >::shuffling(), BenchmarkSuite< Device, T >::slicing(), BenchmarkSuite< Device, T >::striding(), BenchmarkSuite< Device, T >::transcendentalFunc(), and BenchmarkSuite< Device, T >::typeCasting().
StopBenchmarkTiming()
void StopBenchmarkTiming ()
{
   if (g_benchmark_start_time_ns != 0) {
     g_benchmark_total_time_ns += NanoTime() - g_benchmark_start_time_ns;
   }
   g_benchmark_start_time_ns = 0;
 }
References g_benchmark_start_time_ns, g_benchmark_total_time_ns, and NanoTime().
Referenced by BenchmarkSuite< Device, T >::finalizeBenchmark().