MercuryDPM: Tutorial11_AxisymmetricWalls.cpp File Reference
Tutorial11_AxisymmetricWalls.cpp File Reference
#include "Mercury3D.h"
#include "Walls/IntersectionOfWalls.h"
#include "Walls/AxisymmetricIntersectionOfWalls.h"
#include "Species/LinearViscoelasticSpecies.h"
Classes
class Tutorial11
[T11:headers]
Functions
int main (int argc, char *argv[])
[T11:class]
Function Documentation
main()
int main (int argc , char * argv[])
[T11:class]
[T11:main]
[T11: domain]
[T11: domain]
[T11: other specifications]
[T11: other specifications]
[T11: species configuration]
[T11: species configuration]
[T11: tests]
[T11: tests]
[T11: time]
[T11: time]
[T11: solve]
[T11: solve]
 {
     Mdouble width = 10e-2; // 10cm
     Mdouble height = 60e-2; // 60cm
     //Point the object HG to class
     Tutorial11 HG(width,height);
     //Specify particle radius:
     //these parameters are needed in setupInitialConditions()
     HG.minParticleRadius = 6e-3; // 6mm
     HG.maxParticleRadius = 10e-3; //10mm
     //Specify the number of particles
     //specify how big the wedge of the contraction should be
     const Mdouble contractionWidth = 2.5e-2; //2.5cm
     const Mdouble contractionHeight = 5e-2; //5cm
     HG.contractionWidth = contractionWidth;
     HG.contractionHeight = contractionHeight;
     //make the species of the particle and wall
     LinearViscoelasticSpecies species;
     species.setDensity(2000);
     species.setStiffness(1e5);
     species.setDissipation(0.63);
     HG.speciesHandler.copyAndAddObject(species);
     //test normal forces
     const Mdouble minParticleMass = species.getDensity() * 4.0 / 3.0 * constants::pi * mathsFunc::cubic(HG.minParticleRadius);
     //Calculates collision time for two copies of a particle of given dissipation_, k, effective mass
     logger(INFO, "minParticleMass = %", minParticleMass);
     //Calculates collision time for two copies of a particle of given dissipation_, k, effective mass
     const Mdouble tc = species.getCollisionTime(minParticleMass);
     logger(INFO, "tc  = %", tc);
     //Calculates restitution coefficient for two copies of given dissipation_, k, effective mass
     const Mdouble r = species.getRestitutionCoefficient(minParticleMass);
     logger(INFO, "restitution coefficient = %", r);
     //time integration parameters
     HG.setTimeStep(tc / 10.0);
     HG.setTimeMax(5.0);
     HG.setSaveCount(500);
     HG.solve(argc, argv);
     return 0;
 }
References Tutorial11::contractionHeight, Tutorial11::contractionWidth, BaseHandler< T >::copyAndAddObject(), mathsFunc::cubic(), e(), LinearViscoelasticNormalSpecies::getCollisionTime(), ParticleSpecies::getDensity(), LinearViscoelasticNormalSpecies::getRestitutionCoefficient(), Global_Physical_Variables::height(), INFO, logger, Tutorial11::maxParticleRadius, Tutorial11::minParticleRadius, constants::pi, UniformPSDSelfTest::r, ParticleSpecies::setDensity(), LinearViscoelasticNormalSpecies::setDissipation(), DPMBase::setSaveCount(), LinearViscoelasticNormalSpecies::setStiffness(), DPMBase::setTimeMax(), DPMBase::setTimeStep(), DPMBase::solve(), and DPMBase::speciesHandler.