MercuryDPM: Eigen::internal::minmax_compare< Scalar, NaNPropagation, is_min > Struct Template Reference
Eigen::internal::minmax_compare< Scalar, NaNPropagation, is_min > Struct Template Reference
#include <Visitor.h>
Public Types
typedef packet_traits< Scalar >::type Packet
Static Public Member Functions
static EIGEN_DEVICE_FUNC bool compare (Scalar a, Scalar b)
static EIGEN_DEVICE_FUNC Scalar predux (const Packet &p)
Member Typedef Documentation
Packet
template<typename Scalar , int NaNPropagation, bool is_min = true> typedef packet_traits<Scalar>::type Eigen::internal::minmax_compare< Scalar, NaNPropagation, is_min >::Packet
Member Function Documentation
compare()
template<typename Scalar , int NaNPropagation, bool is_min = true> static EIGEN_DEVICE_FUNC bool Eigen::internal::minmax_compare< Scalar, NaNPropagation, is_min >::compare (Scalar a, Scalar b) inline static
 { return a < b; }
References a, and b.
Referenced by Eigen::internal::minmax_coeff_visitor< Derived, is_min, NaNPropagation, isInt >::operator()(), Eigen::internal::minmax_coeff_visitor< Derived, is_min, PropagateNumbers, false >::operator()(), Eigen::internal::minmax_coeff_visitor< Derived, is_min, NaNPropagation, false >::operator()(), Eigen::internal::minmax_coeff_visitor< Derived, is_min, PropagateNumbers, false >::packet(), and Eigen::internal::minmax_coeff_visitor< Derived, is_min, NaNPropagation, false >::packet().
predux()
template<typename Scalar , int NaNPropagation, bool is_min = true> static EIGEN_DEVICE_FUNC Scalar Eigen::internal::minmax_compare< Scalar, NaNPropagation, is_min >::predux (const Packet & p) inline static
 { return predux_min<NaNPropagation>(p); }
References p.
Referenced by Eigen::internal::minmax_coeff_visitor< Derived, is_min, NaNPropagation, isInt >::initpacket(), Eigen::internal::minmax_coeff_visitor< Derived, is_min, NaNPropagation, false >::initpacket(), Eigen::internal::minmax_coeff_visitor< Derived, is_min, NaNPropagation, isInt >::packet(), Eigen::internal::minmax_coeff_visitor< Derived, is_min, PropagateNumbers, false >::packet(), and Eigen::internal::minmax_coeff_visitor< Derived, is_min, NaNPropagation, false >::packet().
The documentation for this struct was generated from the following file:
Visitor.h