MercuryDPM: oomph::QMacroElement< 2 > Class Reference
oomph::QMacroElement< 2 > Class Reference
#include <macro_element.h>
Public Member Functions
QMacroElement (Domain *domain_pt, const unsigned &macro_element_number)
QMacroElement ()
Default constructor (empty and broken)
QMacroElement (const QMacroElement &dummy)=delete
Broken copy constructor.
void operator= (const QMacroElement &)=delete
Broken assignment operator.
virtual ~QMacroElement ()
Empty destructor.
void output (const unsigned &t, std::ostream &outfile, const unsigned &nplot)
void output_macro_element_boundaries (std::ostream &outfile, const unsigned &nplot)
Output all macro element boundaries as tecplot zones.
void macro_map (const unsigned &t, const Vector< double > &S, Vector< double > &r)
void macro_map (const double &t, const Vector< double > &s, Vector< double > &r)
Get global position r(s) at continuous time value, t.
virtual void assemble_macro_to_eulerian_jacobian (const unsigned &t, const Vector< double > &s, DenseMatrix< double > &jacobian)
virtual void assemble_macro_to_eulerian_jacobian2 (const unsigned &t, const Vector< double > &s, DenseMatrix< double > &jacobian2)
Public Member Functions inherited from oomph::MacroElement
MacroElement (Domain *domain_pt, const unsigned &macro_element_number)
MacroElement ()
Default constructor (empty and broken)
MacroElement (const MacroElement &dummy)=delete
Broken copy constructor.
void operator= (const MacroElement &)=delete
Broken assignment operator.
virtual ~MacroElement ()
Empty destructor.
void output (std::ostream &outfile, const int &nplot)
void macro_map (const Vector< double > &s, Vector< double > &r)
The mapping from local to global coordinates at the current time : r(s)
void assemble_macro_to_eulerian_jacobian (const Vector< double > &s, DenseMatrix< double > &jacobian)
void assemble_macro_to_eulerian_jacobian2 (const Vector< double > &s, DenseMatrix< double > &jacobian2)
unsigned & macro_element_number ()
Access function to the Macro_element_number.
Domain *& domain_pt ()
Access function to the Domain_pt.
Additional Inherited Members
Protected Attributes inherited from oomph::MacroElement
Domain * Domain_pt
Pointer to domain.
unsigned Macro_element_number
What is the number of the current macro element within its domain.
Detailed Description
QMacroElement specialised to 2 spatial dimensions.
The macro element mapping is based on the member function pointer to the associated Domain 's
Domain::macro_element_boundary(...)
function which provides a parametrisation of the macro element's boundaries in the form:
\[ {\bf f}_{i} (t,{\bf S}) \]
where
\(i \) labels the boundary (N/S/W/E)
\({\bf S} \in [-1,1]^1 \) is the (1D) Vector of local coordinate(s) along the boundary.
\({\bf f} \) is the position Vector to the boundary.
\(t \) is the time level (t=0: current; t>0 previous timestep)
Constructor & Destructor Documentation
QMacroElement() [1/3]
oomph::QMacroElement< 2 >::QMacroElement (Domain * domain_pt, const unsigned & macro_element_number) inline
Constructor: Pass the pointer to the domain and the macro element's number within this domain
       : MacroElement(domain_pt, macro_element_number){};
QMacroElement() [2/3]
oomph::QMacroElement< 2 >::QMacroElement () inline
Default constructor (empty and broken)
     {
       throw OomphLibError("Don't call empty constructor for QMacroElement!",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
QMacroElement() [3/3]
oomph::QMacroElement< 2 >::QMacroElement (const QMacroElement< 2 > & dummy) delete
Broken copy constructor.
~QMacroElement()
virtual oomph::QMacroElement< 2 >::~QMacroElement () inline virtual
Empty destructor.
 {};
Member Function Documentation
assemble_macro_to_eulerian_jacobian()
void oomph::QMacroElement< 2 >::assemble_macro_to_eulerian_jacobian (const unsigned & t, const Vector< double > & S, DenseMatrix< double > & jacobian) virtual
assemble the jacobian of the mapping from the macro coordinates to the global coordinates
Assembles the jacobian of the mapping from the macro coordinates to the global coordinates
Reimplemented from oomph::MacroElement.
   {
     using namespace QuadTreeNames;
     Vector<double> bound_N(2);
     Vector<double> bound_S(2);
     Vector<double> bound_W(2);
     Vector<double> bound_E(2);
     Vector<double> dbound_N(2);
     Vector<double> dbound_S(2);
     Vector<double> dbound_E(2);
     Vector<double> dbound_W(2);
     Vector<double> corner_SE(2);
     Vector<double> corner_SW(2);
     Vector<double> corner_NE(2);
     Vector<double> corner_NW(2);
     Vector<double> zeta(1);
     // Determine Vectors to corners
     zeta[0] = 1.0;
     Domain_pt->macro_element_boundary(
       t, Macro_element_number, QuadTreeNames::S, zeta, corner_SE);
     zeta[0] = -1.0;
     Domain_pt->macro_element_boundary(
       t, Macro_element_number, QuadTreeNames::S, zeta, corner_SW);
     zeta[0] = 1.0;
     Domain_pt->macro_element_boundary(
       t, Macro_element_number, QuadTreeNames::N, zeta, corner_NE);
     zeta[0] = -1.0;
     Domain_pt->macro_element_boundary(
       t, Macro_element_number, QuadTreeNames::N, zeta, corner_NW);
     // Get the position and first derivativeson the N/S/W/E edges
     zeta[0] = S[0];
     Domain_pt->macro_element_boundary(
       t, Macro_element_number, QuadTreeNames::N, zeta, bound_N);
     Domain_pt->dmacro_element_boundary(
       t, Macro_element_number, QuadTreeNames::N, zeta, dbound_N);
     zeta[0] = S[0];
     Domain_pt->macro_element_boundary(
       t, Macro_element_number, QuadTreeNames::S, zeta, bound_S);
     Domain_pt->dmacro_element_boundary(
       t, Macro_element_number, QuadTreeNames::S, zeta, dbound_S);
     zeta[0] = S[1];
     Domain_pt->macro_element_boundary(
       t, Macro_element_number, QuadTreeNames::W, zeta, bound_W);
     Domain_pt->dmacro_element_boundary(
       t, Macro_element_number, QuadTreeNames::W, zeta, dbound_W);
     zeta[0] = S[1];
     Domain_pt->macro_element_boundary(
       t, Macro_element_number, QuadTreeNames::E, zeta, bound_E);
     Domain_pt->dmacro_element_boundary(
       t, Macro_element_number, QuadTreeNames::E, zeta, dbound_E);
     // dr0/dm0
     jacobian(0, 0) =
       0.25 * (corner_SW[0] - corner_SE[0] + corner_NW[0] - corner_NE[0] -
               corner_NE[0] * S[1] + corner_NW[0] * S[1] + corner_SE[0] * S[1] -
               corner_SW[0] * S[1]) +
       0.5 * (dbound_S[0] + dbound_N[0] - bound_W[0] + bound_E[0] -
              dbound_S[0] * S[1] + dbound_N[0] * S[1]);
     // dr1/dm0
     jacobian(0, 1) =
       0.25 * (corner_SW[1] - corner_SE[1] + corner_NW[1] - corner_NE[1] -
               corner_NE[1] * S[1] + corner_NW[1] * S[1] + corner_SE[1] * S[1] -
               corner_SW[1] * S[1]) +
       0.5 * (dbound_S[1] + dbound_N[1] - bound_W[1] + bound_E[1] -
              dbound_S[1] * S[1] + dbound_N[1] * S[1]);
     // dr0/dm1
     jacobian(1, 0) =
       0.25 * (corner_SW[0] + corner_SE[0] - corner_NW[0] - corner_NE[0] +
               corner_SE[0] * S[0] - corner_SW[0] * S[0] - corner_NE[0] * S[0] +
               corner_NW[0] * S[0]) +
       0.5 * (-bound_S[0] + bound_N[0] + dbound_W[0] + dbound_E[0] -
              dbound_W[0] * S[0] + dbound_E[0] * S[0]);
     // dr1/dm1
     jacobian(1, 1) =
       0.25 * (corner_SW[1] + corner_SE[1] - corner_NW[1] - corner_NE[1] +
               corner_SE[1] * S[0] - corner_SW[1] * S[0] - corner_NE[1] * S[0] +
               corner_NW[1] * S[0]) +
       0.5 * (-bound_S[1] + bound_N[1] + dbound_W[1] + dbound_E[1] -
              dbound_W[1] * S[0] + dbound_E[1] * S[0]);
   }
References oomph::Domain::dmacro_element_boundary(), oomph::MacroElement::Domain_pt, oomph::QuadTreeNames::E, oomph::Domain::macro_element_boundary(), oomph::MacroElement::Macro_element_number, oomph::QuadTreeNames::N, oomph::QuadTreeNames::S, plotPSD::t, oomph::QuadTreeNames::W, and Eigen::zeta().
assemble_macro_to_eulerian_jacobian2()
void oomph::QMacroElement< 2 >::assemble_macro_to_eulerian_jacobian2 (const unsigned & t, const Vector< double > & S, DenseMatrix< double > & jacobian2) virtual
Assembles the second derivative jacobian of the mapping from the macro coordinates to global coordinates x
Reimplemented from oomph::MacroElement.
   {
     using namespace QuadTreeNames;
     Vector<double> bound_N(2);
     Vector<double> bound_S(2);
     Vector<double> bound_W(2);
     Vector<double> bound_E(2);
     Vector<double> dbound_N(2);
     Vector<double> dbound_S(2);
     Vector<double> dbound_E(2);
     Vector<double> dbound_W(2);
     Vector<double> d2bound_N(2);
     Vector<double> d2bound_S(2);
     Vector<double> d2bound_E(2);
     Vector<double> d2bound_W(2);
     Vector<double> corner_SE(2);
     Vector<double> corner_SW(2);
     Vector<double> corner_NE(2);
     Vector<double> corner_NW(2);
     Vector<double> zeta(1);
     // Determine Vectors to corners
     zeta[0] = 1.0;
     Domain_pt->macro_element_boundary(
       t, Macro_element_number, QuadTreeNames::S, zeta, corner_SE);
     zeta[0] = -1.0;
     Domain_pt->macro_element_boundary(
       t, Macro_element_number, QuadTreeNames::S, zeta, corner_SW);
     zeta[0] = 1.0;
     Domain_pt->macro_element_boundary(
       t, Macro_element_number, QuadTreeNames::N, zeta, corner_NE);
     zeta[0] = -1.0;
     Domain_pt->macro_element_boundary(
       t, Macro_element_number, QuadTreeNames::N, zeta, corner_NW);
     // Get the position and first derivativeson the N/S/W/E edges
     zeta[0] = S[0];
     Domain_pt->macro_element_boundary(
       t, Macro_element_number, QuadTreeNames::N, zeta, bound_N);
     Domain_pt->dmacro_element_boundary(
       t, Macro_element_number, QuadTreeNames::N, zeta, dbound_N);
     Domain_pt->d2macro_element_boundary(
       t, Macro_element_number, QuadTreeNames::N, zeta, d2bound_N);
     zeta[0] = S[0];
     Domain_pt->macro_element_boundary(
       t, Macro_element_number, QuadTreeNames::S, zeta, bound_S);
     Domain_pt->dmacro_element_boundary(
       t, Macro_element_number, QuadTreeNames::S, zeta, dbound_S);
     Domain_pt->d2macro_element_boundary(
       t, Macro_element_number, QuadTreeNames::S, zeta, d2bound_S);
     zeta[0] = S[1];
     Domain_pt->macro_element_boundary(
       t, Macro_element_number, QuadTreeNames::W, zeta, bound_W);
     Domain_pt->dmacro_element_boundary(
       t, Macro_element_number, QuadTreeNames::W, zeta, dbound_W);
     Domain_pt->d2macro_element_boundary(
       t, Macro_element_number, QuadTreeNames::W, zeta, d2bound_W);
     zeta[0] = S[1];
     Domain_pt->macro_element_boundary(
       t, Macro_element_number, QuadTreeNames::E, zeta, bound_E);
     Domain_pt->dmacro_element_boundary(
       t, Macro_element_number, QuadTreeNames::E, zeta, dbound_E);
     Domain_pt->d2macro_element_boundary(
       t, Macro_element_number, QuadTreeNames::E, zeta, d2bound_E);
     // d2x0/dm0^2
     jacobian2(0, 0) = 0.5 * (d2bound_S[0] + d2bound_N[0] - d2bound_S[0] * S[1] +
                              d2bound_N[0] * S[1]);
     // d2x0/dm1^2
     jacobian2(1, 0) = 0.5 * (d2bound_W[0] + d2bound_E[0] - d2bound_W[0] * S[0] +
                              d2bound_E[0] * S[0]);
     // d2x0/dm0dm1
     jacobian2(2, 0) =
       0.25 * (-corner_NE[0] + corner_NW[0] + corner_SE[0] - corner_SW[0]) +
       0.5 * (-dbound_W[0] + dbound_E[0] - dbound_S[0] + dbound_N[0]);
     // d2x1/dm0^2
     jacobian2(0, 1) = 0.5 * (d2bound_S[1] + d2bound_N[1] - d2bound_S[1] * S[1] +
                              d2bound_N[1] * S[1]);
     // d2x1/dm1^2
     jacobian2(1, 1) = 0.5 * (d2bound_W[1] + d2bound_E[1] - d2bound_W[1] * S[0] +
                              d2bound_E[1] * S[0]);
     // d2x1/dm0dm1
     jacobian2(2, 1) =
       0.25 * (-corner_NE[1] + corner_NW[1] + corner_SE[1] - corner_SW[1]) +
       0.5 * (-dbound_W[1] + dbound_E[1] - dbound_S[1] + dbound_N[1]);
   }
References oomph::Domain::d2macro_element_boundary(), oomph::Domain::dmacro_element_boundary(), oomph::MacroElement::Domain_pt, oomph::QuadTreeNames::E, oomph::Domain::macro_element_boundary(), oomph::MacroElement::Macro_element_number, oomph::QuadTreeNames::N, oomph::QuadTreeNames::S, plotPSD::t, oomph::QuadTreeNames::W, and Eigen::zeta().
macro_map() [1/2]
void oomph::QMacroElement< 2 >::macro_map (const double & t, const Vector< double > & s, Vector< double > & r) virtual
Get global position r(s) at continuous time value, t.
Get global position r(S) at discrete time level t. t=0: Present time; t>0: previous timestep.
Reimplemented from oomph::MacroElement.
   {
     using namespace QuadTreeNames;
     Vector<double> bound_N(2);
     Vector<double> bound_S(2);
     Vector<double> bound_W(2);
     Vector<double> bound_E(2);
     Vector<double> diff_N(2);
     Vector<double> diff_S(2);
     Vector<double> diff_W(2);
     Vector<double> diff_E(2);
     Vector<double> f_rect(2);
     Vector<double> corner_SE(2);
     Vector<double> corner_SW(2);
     Vector<double> corner_NE(2);
     Vector<double> corner_NW(2);
     Vector<double> edge_N(2);
     Vector<double> edge_S(2);
     Vector<double> zeta(1);
     // Determine Vectors to corners
     zeta[0] = 1.0;
     Domain_pt->macro_element_boundary(
       t, Macro_element_number, QuadTreeNames::S, zeta, corner_SE);
     zeta[0] = -1.0;
     Domain_pt->macro_element_boundary(
       t, Macro_element_number, QuadTreeNames::S, zeta, corner_SW);
     zeta[0] = 1.0;
     Domain_pt->macro_element_boundary(
       t, Macro_element_number, QuadTreeNames::N, zeta, corner_NE);
     zeta[0] = -1.0;
     Domain_pt->macro_element_boundary(
       t, Macro_element_number, QuadTreeNames::N, zeta, corner_NW);
     // Get the position on the N/S/W/E edges
     zeta[0] = s[0];
     Domain_pt->macro_element_boundary(
       t, Macro_element_number, QuadTreeNames::N, zeta, bound_N);
     zeta[0] = s[0];
     Domain_pt->macro_element_boundary(
       t, Macro_element_number, QuadTreeNames::S, zeta, bound_S);
     zeta[0] = s[1];
     Domain_pt->macro_element_boundary(
       t, Macro_element_number, QuadTreeNames::W, zeta, bound_W);
     zeta[0] = s[1];
     Domain_pt->macro_element_boundary(
       t, Macro_element_number, QuadTreeNames::E, zeta, bound_E);
     for (int i = 0; i < 2; i++)
     {
       // Position on the straight S/W edges of the rectangle formed
       // by the corner points
       edge_S[i] =
         corner_SW[i] + (corner_SE[i] - corner_SW[i]) * 0.5 * (s[0] + 1.0);
       edge_N[i] =
         corner_NW[i] + (corner_NE[i] - corner_NW[i]) * 0.5 * (s[0] + 1.0);
       // Position inside rectangle
       f_rect[i] = edge_S[i] + (edge_N[i] - edge_S[i]) * 0.5 * (s[1] + 1.0);
       // Get difference between curved edge and point in rectangle
       diff_N[i] = bound_N[i] - f_rect[i];
       diff_S[i] = bound_S[i] - f_rect[i];
       diff_E[i] = bound_E[i] - f_rect[i];
       diff_W[i] = bound_W[i] - f_rect[i];
       // Map it...
       r[i] = f_rect[i] + diff_S[i] * (1.0 - 0.5 * (s[1] + 1.0)) +
              diff_N[i] * 0.5 * (s[1] + 1.0) +
              diff_W[i] * (1.0 - 0.5 * (s[0] + 1.0)) +
              diff_E[i] * 0.5 * (s[0] + 1.0);
     }
   }
References oomph::MacroElement::Domain_pt, oomph::QuadTreeNames::E, i, oomph::Domain::macro_element_boundary(), oomph::MacroElement::Macro_element_number, oomph::QuadTreeNames::N, UniformPSDSelfTest::r, s, oomph::QuadTreeNames::S, plotPSD::t, oomph::QuadTreeNames::W, and Eigen::zeta().
macro_map() [2/2]
void oomph::QMacroElement< 2 >::macro_map (const unsigned & t, const Vector< double > & S, Vector< double > & r) virtual
Get global position r(S) at discrete time level t. t=0: Present time; t>0: previous timestep.
Implements oomph::MacroElement.
   {
     using namespace QuadTreeNames;
     Vector<double> bound_N(2);
     Vector<double> bound_S(2);
     Vector<double> bound_W(2);
     Vector<double> bound_E(2);
     Vector<double> diff_N(2);
     Vector<double> diff_S(2);
     Vector<double> diff_W(2);
     Vector<double> diff_E(2);
     Vector<double> f_rect(2);
     Vector<double> corner_SE(2);
     Vector<double> corner_SW(2);
     Vector<double> corner_NE(2);
     Vector<double> corner_NW(2);
     Vector<double> edge_N(2);
     Vector<double> edge_S(2);
     Vector<double> zeta(1);
     // Determine Vectors to corners
     zeta[0] = 1.0;
     Domain_pt->macro_element_boundary(
       t, Macro_element_number, QuadTreeNames::S, zeta, corner_SE);
     zeta[0] = -1.0;
     Domain_pt->macro_element_boundary(
       t, Macro_element_number, QuadTreeNames::S, zeta, corner_SW);
     zeta[0] = 1.0;
     Domain_pt->macro_element_boundary(
       t, Macro_element_number, QuadTreeNames::N, zeta, corner_NE);
     zeta[0] = -1.0;
     Domain_pt->macro_element_boundary(
       t, Macro_element_number, QuadTreeNames::N, zeta, corner_NW);
     // Get the position on the N/S/W/E edges
     zeta[0] = S[0];
     Domain_pt->macro_element_boundary(
       t, Macro_element_number, QuadTreeNames::N, zeta, bound_N);
     zeta[0] = S[0];
     Domain_pt->macro_element_boundary(
       t, Macro_element_number, QuadTreeNames::S, zeta, bound_S);
     zeta[0] = S[1];
     Domain_pt->macro_element_boundary(
       t, Macro_element_number, QuadTreeNames::W, zeta, bound_W);
     zeta[0] = S[1];
     Domain_pt->macro_element_boundary(
       t, Macro_element_number, QuadTreeNames::E, zeta, bound_E);
     for (int i = 0; i < 2; i++)
     {
       // Position on the straight S/W edges of the rectangle formed
       // by the corner points
       edge_S[i] =
         corner_SW[i] + (corner_SE[i] - corner_SW[i]) * 0.5 * (S[0] + 1.0);
       edge_N[i] =
         corner_NW[i] + (corner_NE[i] - corner_NW[i]) * 0.5 * (S[0] + 1.0);
       // Position inside rectangle
       f_rect[i] = edge_S[i] + (edge_N[i] - edge_S[i]) * 0.5 * (S[1] + 1.0);
       // Get difference between curved edge and point in rectangle
       diff_N[i] = bound_N[i] - f_rect[i];
       diff_S[i] = bound_S[i] - f_rect[i];
       diff_E[i] = bound_E[i] - f_rect[i];
       diff_W[i] = bound_W[i] - f_rect[i];
       // Map it...
       r[i] = f_rect[i] + diff_S[i] * (1.0 - 0.5 * (S[1] + 1.0)) +
              diff_N[i] * 0.5 * (S[1] + 1.0) +
              diff_W[i] * (1.0 - 0.5 * (S[0] + 1.0)) +
              diff_E[i] * 0.5 * (S[0] + 1.0);
     }
   }
References oomph::MacroElement::Domain_pt, oomph::QuadTreeNames::E, i, oomph::Domain::macro_element_boundary(), oomph::MacroElement::Macro_element_number, oomph::QuadTreeNames::N, UniformPSDSelfTest::r, oomph::QuadTreeNames::S, plotPSD::t, oomph::QuadTreeNames::W, and Eigen::zeta().
operator=()
void oomph::QMacroElement< 2 >::operator= (const QMacroElement< 2 > &) delete
Broken assignment operator.
output()
void oomph::QMacroElement< 2 >::output (const unsigned & t, std::ostream & outfile, const unsigned & nplot) inline virtual
Plot: x,y in tecplot format at time level t (t=0: current; t>0: previous)
Implements oomph::MacroElement.
     {
       Vector<double> x(2), f(2);
       outfile << "ZONE I=" << nplot << ", J=" << nplot << std::endl;
       for (unsigned i = 0; i < nplot; i++)
       {
         x[1] = -1.0 + 2.0 * double(i) / double(nplot - 1);
         for (unsigned j = 0; j < nplot; j++)
         {
           x[0] = -1.0 + 2.0 * double(j) / double(nplot - 1);
           macro_map(t, x, f);
           outfile << f[0] << " " << f[1] << std::endl;
         }
       }
     }
References f(), i, j, oomph::MacroElement::macro_map(), plotPSD::t, and plotDoE::x.
output_macro_element_boundaries()
void oomph::QMacroElement< 2 >::output_macro_element_boundaries (std::ostream & outfile, const unsigned & nplot) virtual
Output all macro element boundaries as tecplot zones.
Implements oomph::MacroElement.
   {
     using namespace QuadTreeNames;
     Vector<double> s(1);
     Vector<double> f(2);
     // Dump at present time
     unsigned t = 0;
     for (unsigned idirect = N; idirect <= W; idirect++)
     {
       outfile << "ZONE I=" << nplot << std::endl;
       for (unsigned j = 0; j < nplot; j++)
       {
         s[0] = -1.0 + 2.0 * double(j) / double(nplot - 1);
         Domain_pt->macro_element_boundary(
           t, Macro_element_number, idirect, s, f);
         outfile << f[0] << " " << f[1] << std::endl;
       }
     }
   }
References oomph::MacroElement::Domain_pt, f(), j, oomph::Domain::macro_element_boundary(), oomph::MacroElement::Macro_element_number, N, s, plotPSD::t, and oomph::QuadTreeNames::W.
The documentation for this class was generated from the following files:
macro_element.h
macro_element.cc