MercuryDPM: spherical_cap_in_cylinder.cc File Reference
spherical_cap_in_cylinder.cc File Reference
#include "generic.h"
#include "young_laplace.h"
#include "meshes/quarter_circle_sector_mesh.h"
#include "common_young_laplace_stuff.h"
Classes
class RefineableYoungLaplaceProblem< ELEMENT >
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
Driver code for 2D RefineableYoungLaplace problem. Input arguments: none (for validation) or number of steps.
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // No command line args: Running with limited number of steps
  if (CommandLineArgs::Argc==1)
   {
    std::cout
     << "Running with limited number of steps for validation"
     << std::endl;
    // Number of steps
    GlobalParameters::Nsteps=2;
   }
  else
   {
    // Number of steps
    GlobalParameters::Nsteps=atoi(argv[1]);
   }
  // Create label for output
  //------------------------
  DocInfo doc_info;
  // Set outputs
  //------------
  // Trace file
  ofstream trace_file;
 // Set output directory
  doc_info.set_directory("RESLT_adapt_pinned_spherical_cap_in_cylinder");
 //Open a trace file
  char filename[100];
  sprintf(filename,"%s/trace.dat",doc_info.directory().c_str());
  trace_file.open(filename);
  trace_file
   << "VARIABLES=\"<GREEK>k</GREEK>\",\"<GREEK>k</GREEK>_{exact}\",\"h\""
   << std::endl;
  trace_file << "ZONE" << std::endl;
  // Set case
  GlobalParameters::Case=GlobalParameters::Spherical_cap_in_cylinder_pinned;
  // Run with spines
  GlobalParameters::Use_spines=true;
  //Set up the problem
  //------------------
  // Create the problem with 2D nine-node elements from the
  // RefineableQYoungLaplaceElement family.
  RefineableYoungLaplaceProblem<RefineableQYoungLaplaceElement<3> > problem;
  //Output the solution
  problem.doc_solution(doc_info,trace_file);
  //Increment counter for solutions
  doc_info.number()++;
  // Parameter incrementation
  //-------------------------
  // Loop over steps
  for (unsigned istep=0;istep<GlobalParameters::Nsteps;istep++)
   {
    // Solve the problem
    unsigned max_adapt=1;
    problem.newton_solve(max_adapt);
    //Output the solution
    problem.doc_solution(doc_info,trace_file);
    //Increment counter for solutions
    doc_info.number()++;
    // Increase the parameters
    problem.increment_parameters();
   }
  // Close output file
  trace_file.close();
 } //end of main
References oomph::CommandLineArgs::Argc, GlobalParameters::Case, oomph::DocInfo::directory(), MergeRestartFiles::filename, GlobalParameters::Nsteps, oomph::DocInfo::number(), problem, oomph::DocInfo::set_directory(), Flag_definition::setup(), GlobalParameters::Spherical_cap_in_cylinder_pinned, and GlobalParameters::Use_spines.