MercuryDPM: oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D > Class Template Reference
oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D > Class Template Reference
#include <discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h>
Public Member Functions
QUnsteadyHeatMixedOrderSpaceTimeElement ()
QUnsteadyHeatMixedOrderSpaceTimeElement (const QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D > &dummy)=delete
Broken copy constructor.
unsigned required_nvalue (const unsigned &n) const
Required number of 'values' (pinned or dofs) at node n.
void output (std::ostream &outfile)
void output (std::ostream &outfile, const unsigned &n_plot)
void output (FILE *file_pt)
void output (FILE *file_pt, const unsigned &n_plot)
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
double dshape_and_dtest_eulerian_ust_heat (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Shape/test functions & derivs. w.r.t. to global coords. Return Jacobian.
double dshape_and_dtest_eulerian_at_knot_ust_heat (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Public Member Functions inherited from oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >
SpaceTimeUnsteadyHeatMixedOrderEquations ()
SpaceTimeUnsteadyHeatMixedOrderEquations (const SpaceTimeUnsteadyHeatMixedOrderEquations &dummy)=delete
Broken copy constructor.
void disable_ALE ()
void enable_ALE ()
void compute_norm (double &norm)
Compute norm of FE solution.
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Get error and norm against exact solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Get error and norm against exact solution.
void output_element_paraview (std::ofstream &outfile, const unsigned &nplot)
unsigned nscalar_paraview () const
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
std::string scalar_name_paraview (const unsigned &i) const
SpaceTimeUnsteadyHeatSourceFctPt & source_fct_pt ()
Access function: Pointer to source function.
SpaceTimeUnsteadyHeatSourceFctPt source_fct_pt () const
Access function: Pointer to source function. Const version.
virtual void get_source_ust_heat (const double &t, const unsigned &ipt, const Vector< double > &x, double &source) const
const double & alpha () const
Alpha parameter (thermal inertia)
double *& alpha_pt ()
Pointer to Alpha parameter (thermal inertia)
const double & beta () const
Beta parameter (thermal conductivity)
double *& beta_pt ()
Pointer to Beta parameter (thermal conductivity)
void get_flux (const Vector< double > &s, Vector< double > &flux) const
Get flux: flux[i]=du/dx_i.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute element residual Vector (wrapper)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute element residual Vector and element Jacobian matrix (wrapper)
double interpolated_u_ust_heat (const Vector< double > &s) const
Return FE representation of function value u(s) at local coordinate s.
virtual unsigned u_index_ust_heat () const
double interpolated_u_ust_heat (const unsigned &t, const Vector< double > &s) const
double du_dt_ust_heat (const unsigned &n) const
double interpolated_du_dt_ust_heat (const Vector< double > &s) const
unsigned self_test ()
Self-test: Return 0 for OK.
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual unsigned nvertex_node () const
virtual Node * vertex_node_pt (const unsigned &j) const
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Protected Member Functions
void shape_ust_heat (const Vector< double > &s, Shape &psi) const
Shape functions w.r.t. to local coords.
void dshape_local_ust_heat (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
Shape functions & derivs. w.r.t. to local coords.
void dtest_local_ust_heat (const Vector< double > &s, Shape &test, DShape &dtestdx) const
Test functions & derivs. w.r.t. to local coords.
Protected Member Functions inherited from oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >
virtual void fill_in_generic_residual_contribution_ust_heat (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Static Private Attributes
static const unsigned Initial_Nvalue = 1
Additional Inherited Members
Public Types inherited from oomph::SpaceTimeUnsteadyHeatEquationsBase
typedef void(* SpaceTimeUnsteadyHeatSourceFctPt) (const double &time, const Vector< double > &x, double &u)
typedef void(* SpaceTimeUnsteadyHeatSourceFctPt) (const double &time, const Vector< double > &x, double &u)
typedef void(* SpaceTimeUnsteadyHeatSourceFctPt) (const double &time, const Vector< double > &x, double &u)
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Protected Attributes inherited from oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >
SpaceTimeUnsteadyHeatSourceFctPt Source_fct_pt
Pointer to source function:
bool ALE_is_disabled
double * Alpha_pt
Pointer to Alpha parameter (thermal inertia)
double * Beta_pt
Pointer to Beta parameter (thermal conductivity)
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
template<unsigned SPATIAL_DIM, unsigned NNODE_1D>
class oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >
//////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////// QUnsteadyHeatMixedOrderSpaceTimeElement elements are quadrilateral/brick- shaped UnsteadyHeatMixedOrder elements with isoparametric interpolation for the function.
Constructor & Destructor Documentation
QUnsteadyHeatMixedOrderSpaceTimeElement() [1/2]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D> oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::QUnsteadyHeatMixedOrderSpaceTimeElement () inline
Constructor: Call constructors for QElement and SpaceTimeUnsteadyHeatMixedOrder equations
       : QElement<SPATIAL_DIM + 1, NNODE_1D>(),
         SpaceTimeUnsteadyHeatMixedOrderEquations<SPATIAL_DIM>()
     {
     }
QUnsteadyHeatMixedOrderSpaceTimeElement() [2/2]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D> oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::QUnsteadyHeatMixedOrderSpaceTimeElement (const QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D > & dummy) delete
Broken copy constructor.
Member Function Documentation
dshape_and_dtest_eulerian_at_knot_ust_heat()
template<unsigned SPATIAL_DIM, unsigned NNODE_1D> double oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::dshape_and_dtest_eulerian_at_knot_ust_heat (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const inline virtual
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions=shape functions
Implements oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >.
   {
     // Find the element dimension
     const unsigned el_dim = SPATIAL_DIM + 1;
     // Storage for the local coordinates of the integration point
     Vector<double> s(el_dim, 0.0);
     // Set the local coordinate
     for (unsigned i = 0; i < el_dim; i++)
     {
       // Calculate the i-th local coordinate at the ipt-th knot point
       s[i] = this->integral_pt()->knot(ipt, i);
     }
     // Return the Jacobian of the geometrical shape functions and derivatives
     return dshape_and_dtest_eulerian_ust_heat(s, psi, dpsidx, test, dtestdx);
   } // End of dshape_and_dtest_eulerian_at_knot_ust_heat
References el_dim, i, and s.
dshape_and_dtest_eulerian_ust_heat()
template<unsigned SPATIAL_DIM, unsigned NNODE_1D> double oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::dshape_and_dtest_eulerian_ust_heat (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const inline virtual
Shape/test functions & derivs. w.r.t. to global coords. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions=shape functions
Implements oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >.
   {
     //--------------------------
     // Call the shape functions:
     //--------------------------
     // Find the element dimension
     const unsigned el_dim = this->dim();
     // Make sure we're using 3D space-time elements
     if (el_dim != 3)
     {
       // Create an output stream
       std::ostringstream error_message_stream;
       // Create an error message
       error_message_stream << "Need 3D space-time elements for this to work!"
                            << std::endl;
       // Throw the error message
       throw OomphLibError(error_message_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
     // Compute the geometric shape functions and also first derivatives
     // w.r.t. local coordinates at local coordinate s
     dshape_local_ust_heat(s, psi, dpsidx);
     // Allocate memory for the inverse jacobian
     DenseMatrix<double> inverse_jacobian(el_dim);
     // Now calculate the inverse jacobian
     const double det =
       this->local_to_eulerian_mapping(dpsidx, inverse_jacobian);
     // Now set the values of the derivatives to be dpsidx
     this->transform_derivatives(inverse_jacobian, dpsidx);
     //-------------------------
     // Call the test functions:
     //-------------------------
     // Compute the geometric test functions and also first derivatives
     // w.r.t. local coordinates at local coordinate s
     dtest_local_ust_heat(s, test, dtestdx);
     // Transform derivatives from dtest/ds to dtest/dx
     this->transform_derivatives(inverse_jacobian, dtestdx);
     // Return the determinant value
     return det;
   } // End of dshape_and_dtest_eulerian_ust_heat
References el_dim, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and s.
dshape_local_ust_heat()
template<unsigned SPATIAL_DIM, unsigned NNODE_1D> void oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::dshape_local_ust_heat (const Vector< double > & s, Shape & psi, DShape & dpsidx) const inline protected virtual
Shape functions & derivs. w.r.t. to local coords.
Define the shape functions and test functions and derivatives w.r.t. local coordinates
Galerkin: Test functions=shape functions
Implements oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >.
   {
     // Local storage (for 3D = 2D space + 1D time)
     double psi_values[3][NNODE_1D];
     double dpsi_values[3][NNODE_1D];
     // Index of the total shape function
     unsigned index = 0;
     // Call the 1D shape functions and derivatives
     OneDimLagrange::shape<NNODE_1D>(s[0], psi_values[0]);
     OneDimLagrange::shape<NNODE_1D>(s[1], psi_values[1]);
     OneDimLagrange::dshape<NNODE_1D>(s[0], dpsi_values[0]);
     OneDimLagrange::dshape<NNODE_1D>(s[1], dpsi_values[1]);
     // Set the time discretisation
     OneDimDiscontinuousGalerkinMixedOrderBasis::shape<NNODE_1D>(s[2],
                                                                 psi_values[2]);
     OneDimDiscontinuousGalerkinMixedOrderBasis::dshape<NNODE_1D>(
       s[2], dpsi_values[2]);
     // Loop over the nodes in the third local coordinate direction
     for (unsigned k = 0; k < NNODE_1D; k++)
     {
       // Loop over the nodes in the second local coordinate direction
       for (unsigned j = 0; j < NNODE_1D; j++)
       {
         // Loop over the nodes in the first local coordinate direction
         for (unsigned i = 0; i < NNODE_1D; i++)
         {
           // Calculate dpsi/ds_0
           dpsidx(index, 0) =
             dpsi_values[0][i] * psi_values[1][j] * psi_values[2][k];
           // Calculate dpsi/ds_1
           dpsidx(index, 1) =
             psi_values[0][i] * dpsi_values[1][j] * psi_values[2][k];
           // Calculate dpsi/ds_2
           dpsidx(index, 2) =
             psi_values[0][i] * psi_values[1][j] * dpsi_values[2][k];
           // Calculate the index-th entry of psi
           psi[index] = psi_values[0][i] * psi_values[1][j] * psi_values[2][k];
           // Increment the index
           index++;
         }
       } // for (unsigned j=0;j<NNODE_1D;j++)
     } // for (unsigned k=0;k<NNODE_1D;k++)
   } // End of dshape_local_ust_heat
References i, j, k, and s.
dtest_local_ust_heat()
template<unsigned SPATIAL_DIM, unsigned NNODE_1D> void oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::dtest_local_ust_heat (const Vector< double > & s, Shape & test, DShape & dtestdx) const inline protected virtual
Test functions & derivs. w.r.t. to local coords.
Define the test functions and derivatives w.r.t. local coordinates.
Implements oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >.
   {
     // Local storage (for 3D = 2D space + 1D time)
     double test_values[3][NNODE_1D];
     double dtest_values[3][NNODE_1D];
     // Index of the total shape function
     unsigned index = 0;
     // Call the 1D shape functions and derivatives
     OneDimLagrange::shape<NNODE_1D>(s[0], test_values[0]);
     OneDimLagrange::shape<NNODE_1D>(s[1], test_values[1]);
     OneDimLagrange::dshape<NNODE_1D>(s[0], dtest_values[0]);
     OneDimLagrange::dshape<NNODE_1D>(s[1], dtest_values[1]);
     // Set the time discretisation
     OneDimDiscontinuousGalerkinMixedOrderTest::shape<NNODE_1D>(s[2],
                                                                test_values[2]);
     OneDimDiscontinuousGalerkinMixedOrderTest::dshape<NNODE_1D>(
       s[2], dtest_values[2]);
     // Loop over the nodes in the third local coordinate direction
     for (unsigned k = 0; k < NNODE_1D; k++)
     {
       // Loop over the nodes in the second local coordinate direction
       for (unsigned j = 0; j < NNODE_1D; j++)
       {
         // Loop over the nodes in the first local coordinate direction
         for (unsigned i = 0; i < NNODE_1D; i++)
         {
           // Calculate dtest/ds_0
           dtestdx(index, 0) =
             dtest_values[0][i] * test_values[1][j] * test_values[2][k];
           // Calculate dtest/ds_1
           dtestdx(index, 1) =
             test_values[0][i] * dtest_values[1][j] * test_values[2][k];
           // Calculate dtest/ds_2
           dtestdx(index, 2) =
             test_values[0][i] * test_values[1][j] * dtest_values[2][k];
           // Calculate the index-th entry of test
           test[index] =
             test_values[0][i] * test_values[1][j] * test_values[2][k];
           // Increment the index
           index++;
         }
       } // for (unsigned j=0;j<NNODE_1D;j++)
     } // for (unsigned k=0;k<NNODE_1D;k++)
   } // End of dtest_local_ust_heat
References i, j, k, and s.
output() [1/4]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D> void oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::output (FILE * file_pt) inline virtual
C-style output function: x,t,u or x,y,t,u
Reimplemented from oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >.
     {
       // Call the function in the base class
       SpaceTimeUnsteadyHeatMixedOrderEquations<SPATIAL_DIM>::output(file_pt);
     } // End of output
References oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::output().
output() [2/4]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D> void oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) inline virtual
C-style output function: x,t,u or x,y,t,u at n_plot^(SPATIAL_DIM+1) plot points
Reimplemented from oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >.
     {
       // Call the function in the base class
       SpaceTimeUnsteadyHeatMixedOrderEquations<SPATIAL_DIM>::output(file_pt,
                                                                     n_plot);
     } // End of output
References oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::output().
output() [3/4]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D> void oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::output (std::ostream & outfile) inline virtual
Output function: x,t,u or x,y,t,u
Reimplemented from oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >.
     {
       // Call the function in the base class
       SpaceTimeUnsteadyHeatMixedOrderEquations<SPATIAL_DIM>::output(outfile);
     } // End of output
References oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::output().
output() [4/4]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D> void oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::output (std::ostream & outfile, const unsigned & n_plot) inline virtual
Output function: x,t,u or x,y,t,u at n_plot^(SPATIAL_DIM+1) plot points
Reimplemented from oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >.
     {
       // Call the function in the base class
       SpaceTimeUnsteadyHeatMixedOrderEquations<SPATIAL_DIM>::output(outfile,
                                                                     n_plot);
     } // End of output
References oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::output().
output_fct() [1/2]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D> void oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) inline virtual
Output function for a time-dependent exact solution. x,t,u_exact or x,y,t,u_exact at n_plot^(SPATIAL_DIM+1) plot points (Calls the unsteady version)
Reimplemented from oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >.
     {
       // Call the function in the base class
       SpaceTimeUnsteadyHeatMixedOrderEquations<SPATIAL_DIM>::output_fct(
         outfile, n_plot, time, exact_soln_pt);
     } // End of output_fct
References oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::output_fct().
output_fct() [2/2]
template<unsigned SPATIAL_DIM, unsigned NNODE_1D> void oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) inline virtual
Output function for an exact solution: x,t,u_exact or x,y,t,u_exact at n_plot^(SPATIAL_DIM+1) plot points
Reimplemented from oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >.
     {
       // Call the function in the base class
       SpaceTimeUnsteadyHeatMixedOrderEquations<SPATIAL_DIM>::output_fct(
         outfile, n_plot, exact_soln_pt);
     } // End of output_fct
References oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >::output_fct().
required_nvalue()
template<unsigned SPATIAL_DIM, unsigned NNODE_1D> unsigned oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::required_nvalue (const unsigned & n) const inline virtual
Required number of 'values' (pinned or dofs) at node n.
Reimplemented from oomph::FiniteElement.
     {
       // Return the appropriate value
       return Initial_Nvalue;
     } // End of required_nvalue
References oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::Initial_Nvalue.
shape_ust_heat()
template<unsigned SPATIAL_DIM, unsigned NNODE_1D> void oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::shape_ust_heat (const Vector< double > & s, Shape & psi) const inline protected virtual
Shape functions w.r.t. to local coords.
Define the shape functions and test functions and derivatives w.r.t. local coordinates
Galerkin: Test functions=shape functions
Implements oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >.
   {
     // Local storage (for 3D = 2D space + 1D time)
     double psi_values[3][NNODE_1D];
     // Index of the total shape function
     unsigned index = 0;
     // Call the 1D shape functions and derivatives
     OneDimLagrange::shape<NNODE_1D>(s[0], psi_values[0]);
     OneDimLagrange::shape<NNODE_1D>(s[1], psi_values[1]);
     // Set the time discretisation
     OneDimDiscontinuousGalerkinMixedOrderBasis::shape<NNODE_1D>(s[2],
                                                                 psi_values[2]);
     // Loop over the nodes in the third local coordinate direction
     for (unsigned k = 0; k < NNODE_1D; k++)
     {
       // Loop over the nodes in the second local coordinate direction
       for (unsigned j = 0; j < NNODE_1D; j++)
       {
         // Loop over the nodes in the first local coordinate direction
         for (unsigned i = 0; i < NNODE_1D; i++)
         {
           // Calculate the index-th entry of psi
           psi[index] = psi_values[0][i] * psi_values[1][j] * psi_values[2][k];
           // Increment the index
           index++;
         }
       } // for (unsigned j=0;j<NNODE_1D;j++)
     } // for (unsigned k=0;k<NNODE_1D;k++)
   } // End of shape_ust_heat
References i, j, k, and s.
Member Data Documentation
Initial_Nvalue
template<unsigned SPATIAL_DIM, unsigned NNODE_1D> const unsigned oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::Initial_Nvalue = 1 static private
Static array of ints to hold number of variables at nodes: Initial_Nvalue[n]
Referenced by oomph::QUnsteadyHeatMixedOrderSpaceTimeElement< SPATIAL_DIM, NNODE_1D >::required_nvalue().
The documentation for this class was generated from the following files:
discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.h
discontinuous_galerkin_space_time_unsteady_heat_mixed_order_elements.cc