MercuryDPM: CylinderInsertionBoundary Class Reference
CylinderInsertionBoundary Class Reference
Inserts particles in a cylinder with a given radius, height and azimuthal radius at a specific origin which is 0 by default.
#include <CylinderInsertionBoundary.h>
Public Member Functions
CylinderInsertionBoundary ()
Constructor; sets everything to 0.
CylinderInsertionBoundary (const CylinderInsertionBoundary &other)
Copy constructor with deep copy.
~CylinderInsertionBoundary () override
Destructor: default destructor.
CylinderInsertionBoundary * copy () const override
Creates a copy on the heap and returns a pointer.
void set (BaseParticle *particleToCopy, unsigned int maxFailed, Mdouble rMin, Mdouble rMax, Mdouble hMin, Mdouble hMax, Vec3D normal={0, 0, 1}, Mdouble thetaMin=-constants::pi, Mdouble thetaMax=constants::pi, Vec3D velMin={0, 0, 0}, Vec3D velMax={0, 0, 0})
Sets the properties of the InsertionBoundary for mutliple different particle types.
void set (BaseParticle &particleToCopy, unsigned int maxFailed, Mdouble rMin, Mdouble rMax, Mdouble hMin, Mdouble hMax, Vec3D normal={0, 0, 1}, Mdouble thetaMin=-constants::pi, Mdouble thetaMax=constants::pi, Vec3D velMin={0, 0, 0}, Vec3D velMax={0, 0, 0})
void set (std::vector< BaseParticle * > particleToCopy, unsigned int maxFailed, Mdouble rMin, Mdouble rMax, Mdouble hMin, Mdouble hMax, Vec3D normal={0, 0, 1}, Mdouble thetaMin=-constants::pi, Mdouble thetaMax=constants::pi, Vec3D velMin={0, 0, 0}, Vec3D velMax={0, 0, 0})
Sets the properties of the InsertionBoundary for a single particle type.
void set (BaseParticle *particleToCopy, unsigned int maxFailed, Mdouble radMin, Mdouble radMax, Mdouble hMin, Mdouble hMax, Vec3D normal, Mdouble thetaMin, Mdouble thetaMax, Vec3D velMin, Vec3D velMax, Mdouble particleRMin, Mdouble particleRMax)
old style set function which assumes a uniform psd.
void set (BaseParticle &particleToCopy, unsigned int maxFailed, Mdouble radMin, Mdouble radMax, Mdouble hMin, Mdouble hMax, Vec3D normal, Mdouble thetaMin, Mdouble thetaMax, Vec3D velMin, Vec3D velMax, Mdouble particleRMin, Mdouble particleRMax)
old style set function which assumes a uniform psd.
void setGeometry (Mdouble rMin, Mdouble rMax, Mdouble hMin, Mdouble hMax, Mdouble thetaMin, Mdouble thetaMax, Vec3D normal)
Sets the geometry (position and orientation) of the CylinderInsertionBoundary.
void setOrientation (Vec3D normal)
sets the orientation of the Cylinder
Matrix3D getRotationMatrixX (Mdouble rotationAngle)
gets the rotationMatrix for a rotation around the X axis by a certain angle
Matrix3D getRotationMatrixY (Mdouble rotationAngle)
gets the rotationMatrix for a rotation around the Y axis by a certain angle
Matrix3D getRotationMatrixZ (Mdouble rotationAngle)
gets the rotationMatrix for a rotation around the Z axis by a certain angle
Vec3D getOrigin () const
Returns the origin of the cylinders coordinate system.
Matrix3D getOrientationMatrix () const
Returns the orientation matrix of the cylinder.
void shiftBoundary (Vec3D shift) override
shift the origin of the cylinder in the cartesian coordinate system
void rotateBoundary (Vec3D angle) override
rotate the cylinder around its origin
void placeParticle (BaseParticle *p, RNG &random) override
Generates a random position, velocity for the particle p.
void read (std::istream &is) override
reads boundary properties from istream
void write (std::ostream &os) const override
writes boundary properties to ostream
Public Member Functions inherited from InsertionBoundary
InsertionBoundary ()
InsertionBoundary (const InsertionBoundary &other)
Copy constructor (with deep copy)
~InsertionBoundary () override
Destructor: delete the particle that has to be copied at every insertion.
virtual BaseParticle * generateParticle (RNG &random)
Sets the properties of the InsertionBoundary for a single particle type ‍/ virtual void set(BaseParticle* particleToCopy, unsigned int maxFailed, Vec3D velMin, Vec3D velMax, double radMin, double radMax)=0;.
void checkBoundaryBeforeTimeStep (DPMBase *md) override
Fills the boundary with particles.
void insertParticles (DPMBase *md)
Fill a certain domain with particles.
unsigned int getNumberOfParticlesInserted () const
Gets the number of particles inserted by the boundary.
Mdouble getMassOfParticlesInserted () const
Gets the mass of particles inserted by the boundary.
Mdouble getVolumeOfParticlesInserted () const
Gets the volume of particles inserted by the boundary.
void reset ()
resets particle property counter variables.
void activate ()
Turns on the InsertionBoundary.
void deactivate ()
Turns off the InsertionBoundary.
bool isActivated ()
Returns whether the InsertionBoundary is activated.
unsigned int getMaxFailed () const
Gets the number of times that the boundary may fail to insert a particle.
void setParticleToCopy (std::vector< BaseParticle * > particleToCopy)
Sets multiple different particles that will be inserted through the insertion boundary.
void setParticleToCopy (BaseParticle *particleToCopy)
Sets the particle that will be inserted through the insertion boundary.
std::vector< BaseParticle * > getParticleToCopy ()
Gets the particles that will be inserted through the insertion boundary.
void read (std::istream &is) override
Reads the boundary's id_ and maxFailed_.
void write (std::ostream &os) const override
Writes the boundary's id_ and maxFailed_.
Mdouble getVolumeFlowRate () const
Gets the volume flow rate of the insertion routine.
void setVolumeFlowRate (Mdouble volumeFlowRate)
Sets the volume flow rate of the insertion routine.
Mdouble getInitialVolume () const
Gets the initialVolume() .
void setInitialVolume (Mdouble initialVolume)
Gets the Volume which should be inserted by the insertion routine.
void setPSD (const PSD psd)
Sets the range of particle radii that may be generated from a user defined PSD.
void setPSD (std::vector< PSD > psd, std::vector< Mdouble > probability)
Sets the ranges of particle radii that may be generated from user defined PSDs.
std::vector< PSD > getPSD ()
Gets the particle size distributions set by the user.
void setVariableVolumeFlowRate (const std::vector< Mdouble > &variableCumulativeVolumeFlowRate, Mdouble samplingInterval)
Sets a variable volume flow rate.
bool insertParticle (Mdouble time)
Checks the inserted total volume and returns if a particle is still allowed to be inserted.
bool getCheckParticleForInteraction () const
Gets the variable that checks if a particle has an interaction.
void setCheckParticleForInteraction (bool checkParticleForInteraction)
Sets the variable that checks if a particle has an interaction.
void setManualInsertion (bool manualInsertion)
Set the flag for a manual PSD insertion routine.
Public Member Functions inherited from BaseBoundary
BaseBoundary ()
default constructor.
BaseBoundary (const BaseBoundary &b)
copy constructor
~BaseBoundary () override
destructor
virtual void createPeriodicParticle (BaseParticle *p UNUSED, ParticleHandler &pH UNUSED)
Creates a periodic particle in case of periodic boundaries in serial build.
virtual void createPeriodicParticles (ParticleHandler &pH UNUSED)
Creates periodic copies of given particle in case of periodic boundaries.
virtual void checkBoundaryAfterParticlesMove (ParticleHandler &pH)
Virtual function that does things to particles, each time step after particles have moved.
virtual void actionsBeforeTimeLoop ()
Virtual function that does something after DPMBase::setupInitialConditions but before the first time step.
virtual void modifyGhostAfterCreation (BaseParticle *particle, int i)
virtual void writeVTK (std::fstream &file)
void setHandler (BoundaryHandler *handler)
Sets the boundary's BoundaryHandler.
BoundaryHandler * getHandler () const
Returns the boundary's BoundaryHandler.
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Protected Attributes
Mdouble thetaMin_
Minimal and maximal azimuth angle in range [-pi,pi] defining the circle of the cylinder in which insertion should happen.
Mdouble thetaMax_
Mdouble radMin_
Minimal and maximal radius defining the inner and outer circle of the cylinder in which insertion should happen.
Mdouble radMax_
Mdouble hMin_
Minimal and maximal height defining the cylinder in which insertion should happen.
Mdouble hMax_
Matrix3D orientationMatrix_
Orientation matrix which rotates the cylinder based on the chosen normal axis (the height axis of the cylinder).
Vec3D origin_
origin of the cylinder.
Private Member Functions
std::string getName () const override
Returns the name of the object.
Additional Inherited Members
Public Attributes inherited from InsertionBoundary
std::vector< BaseParticle * > particleToCopy_
read Distribution class from file. ‍/ friend std::istream& operator>>(std::istream& is, InsertionBoundary::Distribution& type);
unsigned int maxFailed_
Number of times that the wall may fail to insert a particle.
unsigned int numberOfParticlesInserted_
Number of particles that are already inserted.
Mdouble massInserted_
Total mass of particles inserted.
Mdouble volumeInserted_
Total volume of particles inserted.
bool isActivated_
The InsertionBoundary is activated by default. If the InsertionBoundary is deactivated, then it introduces no particles (useful for trying to maintain a certain insertion rate).
Mdouble volumeFlowRate_
Mdouble initialVolume_
std::vector< Mdouble > variableCumulativeVolumeFlowRate_
Mdouble samplingInterval_
bool checkParticleForInteraction_
Checks if a particle has an interaction with a wall or other particles.
std::vector< PSD > particleSizeDistributionVector_
Defines a particle size distribution as an object of the PSD class; if particleSizeDistributionVector_ is empty, distribution_ is used instead.
Vec3D velMin_
Minimum and maximum velocity of the particles to be inserted.
Vec3D velMax_
bool isManuallyInserting_
A flag to enable a top-down class-by-class manual insertion of a PSD; default is FALSE.
std::vector< Mdouble > probability_
vector of probabilities in range [0,1] which determine the mixing ratio of partice size distributions.
int chosenSpecies_
stores the chosen species for each timestep.
BaseParticle * p0 = nullptr
pointer to the next particle that should be inserted (needs to be stored across time steps).
Detailed Description
Inserts particles in a cylinder with a given radius, height and azimuthal radius at a specific origin which is 0 by default.
Constructor & Destructor Documentation
CylinderInsertionBoundary() [1/2]
CylinderInsertionBoundary::CylinderInsertionBoundary ()
Constructor; sets everything to 0.
Default constructor; sets every data member to 0.
                                                      : InsertionBoundary()
 {
     radMin_ = 0.0;
     radMax_ = 0.0;
     hMin_ = 0.0;
     hMax_ = 0.0;
     thetaMin_ = 0.0;
     thetaMax_ = 0.0;
     origin_.setZero();
     orientationMatrix_.setZero();
 }
References hMax_, hMin_, orientationMatrix_, origin_, radMax_, radMin_, Matrix3D::setZero(), Vec3D::setZero(), thetaMax_, and thetaMin_.
Referenced by copy().
CylinderInsertionBoundary() [2/2]
CylinderInsertionBoundary::CylinderInsertionBoundary (const CylinderInsertionBoundary & other)
Copy constructor with deep copy.
Copy constructor
         : InsertionBoundary(other)
 {
     radMin_ = other.radMin_;
     radMax_ = other.radMax_;
     hMin_ = other.hMin_;
     hMax_ = other.hMax_;
     thetaMin_ = other.thetaMin_;
     thetaMax_ = other.thetaMax_;
     origin_ = other.origin_;
     orientationMatrix_ = other.orientationMatrix_;
 }
References hMax_, hMin_, orientationMatrix_, origin_, radMax_, radMin_, thetaMax_, and thetaMin_.
~CylinderInsertionBoundary()
CylinderInsertionBoundary::~CylinderInsertionBoundary () override default
Destructor: default destructor.
Destructor. Since there are no pointers in this class, there is no need for any actions here.
Member Function Documentation
copy()
CylinderInsertionBoundary * CylinderInsertionBoundary::copy () const override virtual
Creates a copy on the heap and returns a pointer.
Copy method; creates a copy on the heap and returns its pointer.
Returns
pointer to the copy on the heap
Implements BaseBoundary.
 {
 #ifdef DEBUG_CONSTRUCTOR
     std::cout << "CylinderInsertionBoundary::copy() const finished" << std::endl;
 #endif
     return new CylinderInsertionBoundary(*this);
 }
References CylinderInsertionBoundary().
getName()
std::string CylinderInsertionBoundary::getName () const override private virtual
Returns the name of the object.
Returns the name of the object class
Returns
the object's class' name, i.e. 'CylinderInsertionBoundary'
Implements BaseObject.
 {
     return "CylinderInsertionBoundary";
 }
getOrientationMatrix()
Matrix3D CylinderInsertionBoundary::getOrientationMatrix () const
Returns the orientation matrix of the cylinder.
Returns the orientation matrix of the cylinder
Returns
orientationMatrix_ the orientation matrix which rotates the particles inserted into the cylinder to the right spot
 {
     return orientationMatrix_;
 }
References orientationMatrix_.
Referenced by PSDSelfTest::setupInitialConditions().
getOrigin()
Vec3D CylinderInsertionBoundary::getOrigin () const
Returns the origin of the cylinders coordinate system.
Returns the origin of the cylinders coordinate system
Returns
origin_ the origin of the cylinders coordinate system
 {
     return origin_;
 }
References origin_.
Referenced by PSDSelfTest::setupInitialConditions().
getRotationMatrixX()
Matrix3D CylinderInsertionBoundary::getRotationMatrixX (Mdouble rotationAngle)
gets the rotationMatrix for a rotation around the X axis by a certain angle
gets the rotationMatrix for a rotation around the X axis by a certain angle
Parameters
[in] rotationAngle the angle by which the rotation should happen
Returns
the rotation matrix in X direction
{
     Matrix3D rotationMatrix;
     rotationMatrix.XX = 1.0;
     rotationMatrix.YY = cos(rotationAngle);
     rotationMatrix.YZ = -sin(rotationAngle);
     rotationMatrix.ZY = sin(rotationAngle);
     rotationMatrix.ZZ = cos(rotationAngle);
     return rotationMatrix;
 }
References cos(), sin(), Matrix3D::XX, Matrix3D::YY, Matrix3D::YZ, Matrix3D::ZY, and Matrix3D::ZZ.
Referenced by rotateBoundary(), and setOrientation().
getRotationMatrixY()
Matrix3D CylinderInsertionBoundary::getRotationMatrixY (Mdouble rotationAngle)
gets the rotationMatrix for a rotation around the Y axis by a certain angle
gets the rotationMatrix for a rotation around the Y axis by a certain angle
Parameters
[in] rotationAngle the angle by which the rotation should happen
Returns
the rotation matrix in Y direction
{
     Matrix3D rotationMatrix;
     rotationMatrix.XX = cos(rotationAngle);
     rotationMatrix.XZ = sin(rotationAngle);
     rotationMatrix.YY = 1.0;
     rotationMatrix.ZX = -sin(rotationAngle);
     rotationMatrix.ZZ = cos(rotationAngle);
     return rotationMatrix;
 }
References cos(), sin(), Matrix3D::XX, Matrix3D::XZ, Matrix3D::YY, Matrix3D::ZX, and Matrix3D::ZZ.
Referenced by rotateBoundary(), and setOrientation().
getRotationMatrixZ()
Matrix3D CylinderInsertionBoundary::getRotationMatrixZ (Mdouble rotationAngle)
gets the rotationMatrix for a rotation around the Z axis by a certain angle
gets the rotationMatrix for a rotation around the Z axis by a certain angle
Parameters
[in] rotationAngle the angle by which the rotation should happen
Returns
the rotation matrix in Z direction
{
     Matrix3D rotationMatrix;
     rotationMatrix.XX = cos(rotationAngle);
     rotationMatrix.XY = -sin(rotationAngle);
     rotationMatrix.YX = sin(rotationAngle);
     rotationMatrix.YY = cos(rotationAngle);
     rotationMatrix.ZZ = 1.0;
     return rotationMatrix;
 }
References cos(), sin(), Matrix3D::XX, Matrix3D::XY, Matrix3D::YX, Matrix3D::YY, and Matrix3D::ZZ.
Referenced by rotateBoundary(), and setOrientation().
placeParticle()
void CylinderInsertionBoundary::placeParticle (BaseParticle * p, RNG & random) override virtual
Generates a random position, velocity for the particle p.
places a particle with random position (although within the boundary, of course), velocity and radius and returns its pointer.
Parameters
[in] random Random number generator
Implements InsertionBoundary.
 {
     // create vectors for cartesian position and velocity and cylindrical position
     Vec3D pos, vel, posCylindrical;
     // draw random numbers in cartesian coordinates and make sure they are inside the cylinder sphere
     do
     {
         pos.X = random.getRandomNumber(-radMax_,radMax_);
         pos.Y = random.getRandomNumber(-radMax_,radMax_);
         pos.Z = random.getRandomNumber(hMin_, hMax_);
         posCylindrical = pos.getCylindricalCoordinates();
     }
     // make sure particle stay inside the sphere of our cylinder
     while (posCylindrical.X > radMax_ ||
            posCylindrical.X < radMin_ ||
            posCylindrical.Y < thetaMin_ ||
            posCylindrical.Y >= thetaMax_);
     // rotate cylindrical coordinates by the orientationMatrix
     pos = orientationMatrix_*pos;
     // set the velocity in cartesian coordinates
     vel.X = random.getRandomNumber(velMin_.X, velMax_.X);
     vel.Y = random.getRandomNumber(velMin_.Y, velMax_.Y);
     vel.Z = random.getRandomNumber(velMin_.Z, velMax_.Z);
     p->setPosition(pos + origin_);
     p->setVelocity(vel);
 }
References Vec3D::getCylindricalCoordinates(), RNG::getRandomNumber(), hMax_, hMin_, orientationMatrix_, origin_, p, radMax_, radMin_, thetaMax_, thetaMin_, InsertionBoundary::velMax_, InsertionBoundary::velMin_, Vec3D::X, Vec3D::Y, and Vec3D::Z.
read()
void CylinderInsertionBoundary::read (std::istream & is) override virtual
reads boundary properties from istream
Reads the boundary properties from an istream
Parameters
[in,out] is the istream
Implements BaseBoundary.
 {
     InsertionBoundary::read(is);
     std::string dummy;
     is >> dummy >> radMin_
        >> dummy >> radMax_;
     is >> dummy >> hMin_
        >> dummy >> hMax_;
     is >> dummy >> thetaMin_
        >> dummy >> thetaMax_;
     is >> dummy >> orientationMatrix_;
     is >> dummy >> velMin_
        >> dummy >> velMax_;
     is >> dummy >> origin_;
 }
References hMax_, hMin_, orientationMatrix_, origin_, radMax_, radMin_, InsertionBoundary::read(), oomph::Global_string_for_annotation::string(), thetaMax_, thetaMin_, InsertionBoundary::velMax_, and InsertionBoundary::velMin_.
rotateBoundary()
void CylinderInsertionBoundary::rotateBoundary (Vec3D angle) override virtual
rotate the cylinder around its origin
rotate the cylinder around its origin by an XYZ rotation. The cylinder first gets rotated around X axis by angle.X then around the Y axis by angle.Y and finally around the Z axis by angle.Z.
Parameters
[in] angle Defines the angles of rotation in rad
Reimplemented from InsertionBoundary.
 {
     orientationMatrix_ = getRotationMatrixZ(angle.Z) * getRotationMatrixY(angle.Y) * getRotationMatrixX(angle.X)*orientationMatrix_;
 }
References Jeffery_Solution::angle(), getRotationMatrixX(), getRotationMatrixY(), getRotationMatrixZ(), and orientationMatrix_.
Referenced by PSDSelfTest::setupInitialConditions().
set() [1/5]
void CylinderInsertionBoundary::set (BaseParticle & particleToCopy, unsigned int maxFailed, Mdouble radMin, Mdouble radMax, Mdouble hMin, Mdouble hMax, Vec3D normal, Mdouble thetaMin, Mdouble thetaMax, Vec3D velMin, Vec3D velMax, Mdouble particleRMin, Mdouble particleRMax)
old style set function which assumes a uniform psd.
 {
     PSD uniformPSD;
     uniformPSD.setDistributionUniform(particleRMin, particleRMax, 2);
     setPSD(uniformPSD);
     set(particleToCopy, maxFailed, radMin, radMax, hMin, hMax, normal, thetaMin, thetaMax, velMin, velMax);
 }
References WallFunction::normal(), set(), PSD::setDistributionUniform(), and InsertionBoundary::setPSD().
set() [2/5]
void CylinderInsertionBoundary::set (BaseParticle & particleToCopy, unsigned int maxFailed, Mdouble rMin, Mdouble rMax, Mdouble hMin, Mdouble hMax, Vec3D normal = {0, 0, 1}, Mdouble thetaMin = -constants::pi, Mdouble thetaMax = constants::pi, Vec3D velMin = {0, 0, 0}, Vec3D velMax = {0, 0, 0})
 {
     set(&particleToCopy, maxFailed, radMin, radMax, hMin, hMax, normal, thetaMin, thetaMax, velMin, velMax);
 }
References WallFunction::normal(), and set().
set() [3/5]
void CylinderInsertionBoundary::set (BaseParticle * particleToCopy, unsigned int maxFailed, Mdouble radMin, Mdouble radMax, Mdouble hMin, Mdouble hMax, Vec3D normal, Mdouble thetaMin, Mdouble thetaMax, Vec3D velMin, Vec3D velMax, Mdouble particleRMin, Mdouble particleRMax)
old style set function which assumes a uniform psd.
old style set function which also assumes a uniform psd. Note if you want a specific PSD do not use but this is quicker for a uniform in size PSD
 {
     PSD uniformPSD;
     uniformPSD.setDistributionUniform(particleRMin, particleRMax, 2);
     setPSD(uniformPSD);
     set(particleToCopy, maxFailed, radMin, radMax, hMin, hMax, normal, thetaMin, thetaMax, velMin, velMax);
 }
References WallFunction::normal(), set(), PSD::setDistributionUniform(), and InsertionBoundary::setPSD().
set() [4/5]
void CylinderInsertionBoundary::set (BaseParticle * particleToCopy, unsigned int maxFailed, Mdouble radMin, Mdouble radMax, Mdouble hMin, Mdouble hMax, Vec3D normal = {0, 0, 1}, Mdouble thetaMin = -constants::pi, Mdouble thetaMax = constants::pi, Vec3D velMin = {0, 0, 0}, Vec3D velMax = {0, 0, 0})
Sets the properties of the InsertionBoundary for mutliple different particle types.
Sets all the properties of the cylindrical insertion boundary.
Parameters
[in] particleToCopy Pointer to the BaseParticle which is used as a basis for the particles to be inserted
[in] maxFailed The maximum number of times the insertion of a particle may be tried and failed before the insertion of particles is considered done NB: this property is used in the parent's InsertionBoundary::checkBoundaryBeforeTimeStep().
[in] radMin minimal radius defining of the cylinder boundary
[in] radMax maximal radius of the cylinder boundary
[in] hMin minimal height of the cylinder boundary
[in] hMax maximal height of the cylinder boundary
[in] thetaMin minimal azimuth angle of the cylinder boundary
[in] thetaMax maximal azimuth angle of the cylinder boundary
[in] normal normal position of the Z-axis (height) of the cylinder
[in] velMin Minimum velocity of inserted particles
[in] velMax Maximum velocity of inserted particles
 {
     velMin_ = velMin;
     velMax_ = velMax;
     maxFailed_ = maxFailed;
     setParticleToCopy(particleToCopy);
     setGeometry(radMin, radMax, hMin, hMax, thetaMin, thetaMax, normal);
 }
References InsertionBoundary::maxFailed_, WallFunction::normal(), setGeometry(), InsertionBoundary::setParticleToCopy(), InsertionBoundary::velMax_, and InsertionBoundary::velMin_.
Referenced by set(), InsertionBoundarySelfTest::setupInitialConditions(), and PSDSelfTest::setupInitialConditions().
set() [5/5]
void CylinderInsertionBoundary::set (std::vector< BaseParticle * > particleToCopy, unsigned int maxFailed, Mdouble radMin, Mdouble radMax, Mdouble hMin, Mdouble hMax, Vec3D normal = {0, 0, 1}, Mdouble thetaMin = -constants::pi, Mdouble thetaMax = constants::pi, Vec3D velMin = {0, 0, 0}, Vec3D velMax = {0,0,0})
Sets the properties of the InsertionBoundary for a single particle type.
Sets all the properties of the cylindrical insertion boundary.
Parameters
[in] particleToCopy vector of pointers to the BaseParticles which are used as a basis for the particle types (species) to be inserted
[in] maxFailed The maximum number of times the insertion of a particle may be tried and failed before the insertion of particles is considered done NB: this property is used in the parent's InsertionBoundary::checkBoundaryBeforeTimeStep().
[in] radMin minimal radius defining of the cylinder boundary
[in] radMax maximal radius of the cylinder boundary
[in] hMin minimal height of the cylinder boundary
[in] hMax maximal height of the cylinder boundary
[in] thetaMin minimal azimuth angle of the cylinder boundary
[in] thetaMax maximal azimuth angle of the cylinder boundary
[in] normal normal position of the Z-axis (height) of the cylinder
[in] velMin Minimum velocity of inserted particles
[in] velMax Maximum velocity of inserted particles
 {
     velMin_ = velMin;
     velMax_ = velMax;
     maxFailed_ = maxFailed;
     setParticleToCopy(particleToCopy);
     setGeometry(radMin, radMax, hMin, hMax, thetaMin, thetaMax, normal);
 }
References InsertionBoundary::maxFailed_, WallFunction::normal(), setGeometry(), InsertionBoundary::setParticleToCopy(), InsertionBoundary::velMax_, and InsertionBoundary::velMin_.
setGeometry()
void CylinderInsertionBoundary::setGeometry (Mdouble rMin, Mdouble rMax, Mdouble hMin, Mdouble hMax, Mdouble thetaMin, Mdouble thetaMax, Vec3D normal)
Sets the geometry (position and orientation) of the CylinderInsertionBoundary.
set the geometry of the Cylindrical insertion boundary by setting the position and orientation.
Parameters
[in] rMin minimal radius defining an inner radius of the cylinder boundary
[in] rMax maximal outer radius of the cylinder boundary
[in] hMin minimal height of the cylinder boundary
[in] hMax maximal height of the cylinder boundary
[in] thetaMin minimal azimuth angle of the cylinder boundary
[in] thetaMax maximal azimuth angle of the cylinder boundary
[in] normal normal position of the Z-axis (height) of the cylinder
 {
     radMin_ = rMin;
     radMax_ = rMax;
     hMin_ = hMin;
     hMax_ = hMax;
     thetaMin_ = thetaMin;
     thetaMax_ = thetaMax;
     setOrientation(normal);
 }
References hMax_, hMin_, WallFunction::normal(), radMax_, radMin_, setOrientation(), thetaMax_, and thetaMin_.
Referenced by set().
setOrientation()
void CylinderInsertionBoundary::setOrientation (Vec3D normal)
sets the orientation of the Cylinder
set the orientation of the cylinder by rotating it around the X, Y and Z axis. The order of rotation is first X, then Y, then Z.
Parameters
[in] normal Defines the angle of rotation in rad
 {
     logger.assert_always(!normal.isZero(),"no normal vector defined. Please define a normal vector to determine the coordinate system for the cylinder");
     logger.assert_always(normal.X == 0 || normal.X == 1,"the normal in X direction has to be either set to 0 or 1");
     logger.assert_always(normal.Y == 0 || normal.Y == 1,"the normal in Y direction has to be either set to 0 or 1");
     logger.assert_always(normal.Z == 0 || normal.Z == 1,"the normal in Z direction has to be either set to 0 or 1");
     logger.assert_always(normal.getLength() == 1, "The normal can only point to a single direction. Please set the normal to point to the X, Y or Z coordinate.");
     if (normal.Z)
     {
         // do nothing
         orientationMatrix_ = getRotationMatrixZ(0);
     }
     if (normal.Y)
     {
         // rotate around X to get the Z coordinate pointing to Y
         orientationMatrix_ = getRotationMatrixX(constants::pi/2.0);
     }
     if (normal.X)
     {
         // rotate around Y to get the Z coordinate pointing to X
         orientationMatrix_ = getRotationMatrixY(constants::pi/2.0);
     }
 }
References getRotationMatrixX(), getRotationMatrixY(), getRotationMatrixZ(), logger, WallFunction::normal(), orientationMatrix_, and constants::pi.
Referenced by setGeometry().
shiftBoundary()
void CylinderInsertionBoundary::shiftBoundary (Vec3D shift) override virtual
shift the origin of the cylinder in the cartesian coordinate system
shifts the cylinder by a translation vector in the cartesian coordinate system
Parameters
[in] shift translation vector which shifts the cylinder by certain X,Y,Z coordinates
Reimplemented from InsertionBoundary.
 {
     origin_ += shift;
 }
References origin_.
Referenced by PSDSelfTest::setupInitialConditions().
write()
void CylinderInsertionBoundary::write (std::ostream & os) const override virtual
writes boundary properties to ostream
Writes boundary's properties to an ostream
Parameters
[in] os the ostream
Implements BaseBoundary.
 {
     InsertionBoundary::write(os);
     os << " radMin " << radMin_
        << " radMax " << radMax_
        << " hMin " << hMin_
        << " hMax " << hMax_
        << " thetaMin " << thetaMin_
        << " thetaMax " << thetaMax_
        << " orientationMatrix " << orientationMatrix_
        << " velMin " << velMin_
        << " velMax " << velMax_
        << " origin " << origin_;
 }
References hMax_, hMin_, orientationMatrix_, origin_, radMax_, radMin_, thetaMax_, thetaMin_, InsertionBoundary::velMax_, InsertionBoundary::velMin_, and InsertionBoundary::write().
Member Data Documentation
hMax_
Mdouble CylinderInsertionBoundary::hMax_ protected
Referenced by CylinderInsertionBoundary(), placeParticle(), read(), setGeometry(), and write().
hMin_
Mdouble CylinderInsertionBoundary::hMin_ protected
Minimal and maximal height defining the cylinder in which insertion should happen.
Referenced by CylinderInsertionBoundary(), placeParticle(), read(), setGeometry(), and write().
orientationMatrix_
Matrix3D CylinderInsertionBoundary::orientationMatrix_ protected
Orientation matrix which rotates the cylinder based on the chosen normal axis (the height axis of the cylinder).
Referenced by CylinderInsertionBoundary(), getOrientationMatrix(), placeParticle(), read(), rotateBoundary(), setOrientation(), and write().
origin_
Vec3D CylinderInsertionBoundary::origin_ protected
origin of the cylinder.
Referenced by CylinderInsertionBoundary(), getOrigin(), placeParticle(), read(), shiftBoundary(), and write().
radMax_
Mdouble CylinderInsertionBoundary::radMax_ protected
Referenced by CylinderInsertionBoundary(), placeParticle(), read(), setGeometry(), and write().
radMin_
Mdouble CylinderInsertionBoundary::radMin_ protected
Minimal and maximal radius defining the inner and outer circle of the cylinder in which insertion should happen.
Referenced by CylinderInsertionBoundary(), placeParticle(), read(), setGeometry(), and write().
thetaMax_
Mdouble CylinderInsertionBoundary::thetaMax_ protected
Referenced by CylinderInsertionBoundary(), placeParticle(), read(), setGeometry(), and write().
thetaMin_
Mdouble CylinderInsertionBoundary::thetaMin_ protected
Minimal and maximal azimuth angle in range [-pi,pi] defining the circle of the cylinder in which insertion should happen.
Referenced by CylinderInsertionBoundary(), placeParticle(), read(), setGeometry(), and write().
The documentation for this class was generated from the following files:
CylinderInsertionBoundary.h
CylinderInsertionBoundary.cc