MercuryDPM: Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::Storage Class Reference
Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::Storage Class Reference
#include <TensorBlock.h>
Public Member Functions
Scalar * data () const
const Dimensions & dimensions () const
const Dimensions & strides () const
TensorMaterializedBlock AsTensorMaterializedBlock () const
Private Member Functions
Storage (Scalar *data, const Dimensions &dimensions, const Dimensions &strides, bool materialized_in_output, bool strided_storage)
Private Attributes
Scalar * m_data
Dimensions m_dimensions
Dimensions m_strides
bool m_materialized_in_output
bool m_strided_storage
Friends
class TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >
Constructor & Destructor Documentation
Storage()
template<typename Scalar , int NumDims, int Layout, typename IndexType = Eigen::Index> Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::Storage::Storage (Scalar * data, const Dimensions & dimensions, const Dimensions & strides, bool materialized_in_output, bool strided_storage) inline private
         : m_data(data),
           m_dimensions(dimensions),
           m_strides(strides),
           m_materialized_in_output(materialized_in_output),
           m_strided_storage(strided_storage) {}
Member Function Documentation
AsTensorMaterializedBlock()
template<typename Scalar , int NumDims, int Layout, typename IndexType = Eigen::Index> TensorMaterializedBlock Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::Storage::AsTensorMaterializedBlock () const inline
{
       return TensorMaterializedBlock(m_materialized_in_output ? internal::TensorBlockKind::kMaterializedInOutput
                                                               : internal::TensorBlockKind::kMaterializedInScratch,
                                      m_data, m_dimensions, !m_strided_storage);
     }
References Eigen::internal::kMaterializedInOutput, Eigen::internal::kMaterializedInScratch, Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::Storage::m_data, Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::Storage::m_dimensions, Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::Storage::m_materialized_in_output, Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::Storage::m_strided_storage, and Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::TensorMaterializedBlock().
Referenced by Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::block(), Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::block(), Eigen::TensorEvaluator< const TensorBroadcastingOp< Broadcast, ArgType >, Device >::block(), Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::block(), Eigen::TensorEvaluator< const TensorPaddingOp< PaddingDimensions, ArgType >, Device >::block(), Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::block(), and Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::materialize().
data()
template<typename Scalar , int NumDims, int Layout, typename IndexType = Eigen::Index> Scalar* Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::Storage::data () const inline
 { return m_data; }
References Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::Storage::m_data.
Referenced by Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::block(), Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::block(), Eigen::TensorEvaluator< const TensorBroadcastingOp< Broadcast, ArgType >, Device >::block(), Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::block(), Eigen::TensorEvaluator< const TensorPaddingOp< PaddingDimensions, ArgType >, Device >::block(), Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::block(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::materialize(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
dimensions()
template<typename Scalar , int NumDims, int Layout, typename IndexType = Eigen::Index> const Dimensions& Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::Storage::dimensions () const inline
 { return m_dimensions; }
References Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::Storage::m_dimensions.
Referenced by Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::block(), and Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::materialize().
strides()
template<typename Scalar , int NumDims, int Layout, typename IndexType = Eigen::Index> const Dimensions& Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::Storage::strides () const inline
 { return m_strides; }
References Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::Storage::m_strides.
Referenced by Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >::block(), and Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::materialize().
Friends And Related Function Documentation
TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >
template<typename Scalar , int NumDims, int Layout, typename IndexType = Eigen::Index> friend class TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType > friend
Member Data Documentation
m_data
template<typename Scalar , int NumDims, int Layout, typename IndexType = Eigen::Index> Scalar* Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::Storage::m_data private
Referenced by Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::Storage::AsTensorMaterializedBlock(), and Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::Storage::data().
m_dimensions
template<typename Scalar , int NumDims, int Layout, typename IndexType = Eigen::Index> Dimensions Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::Storage::m_dimensions private
Referenced by Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::Storage::AsTensorMaterializedBlock(), and Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::Storage::dimensions().
m_materialized_in_output
template<typename Scalar , int NumDims, int Layout, typename IndexType = Eigen::Index> bool Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::Storage::m_materialized_in_output private
Referenced by Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::Storage::AsTensorMaterializedBlock().
m_strided_storage
template<typename Scalar , int NumDims, int Layout, typename IndexType = Eigen::Index> bool Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::Storage::m_strided_storage private
Referenced by Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::Storage::AsTensorMaterializedBlock().
m_strides
template<typename Scalar , int NumDims, int Layout, typename IndexType = Eigen::Index> Dimensions Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::Storage::m_strides private
Referenced by Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::Storage::strides().
The documentation for this class was generated from the following file:
TensorBlock.h