MercuryDPM: oomph::Shape Class Reference
oomph::Shape Class Reference
#include <shape.h>
Public Member Functions
Shape (const unsigned &N)
Constructor for a single-index set of shape functions.
Shape (const unsigned &N, const unsigned &M)
Constructor for a two-index set of shape functions.
Shape (const Shape &shape)=delete
Broken copy constructor.
Shape ()
void operator= (const Shape &shape)
void operator= (Shape *const &shape_pt)
~Shape ()
Destructor, clear up the memory allocated by the object.
void resize (const unsigned &N, const unsigned &M=1)
Change the size of the storage.
double & operator[] (const unsigned &i)
Overload the bracket operator to provide access to values.
const double & operator[] (const unsigned &i) const
Overload the bracket operator (const version)
double & operator() (const unsigned &i)
Overload the round bracket operator to provide access to values.
const double & operator() (const unsigned &i) const
Overload the round bracket operator (const version)
double & operator() (const unsigned &i, const unsigned &j)
Overload the round bracket operator, allowing for two indices.
const double & operator() (const unsigned &i, const unsigned &j) const
unsigned nindex1 () const
Return the range of index 1 of the shape function object.
unsigned nindex2 () const
Return the range of index 2 of the shape function object.
Protected Member Functions
void range_check (const unsigned &i, const unsigned &j) const
Private function that checks whether the index is in range.
Protected Attributes
double * Psi
double * Allocated_storage
unsigned Index1
Size of the first index of the shape function.
unsigned Index2
Size of the second index of the shape function.
Detailed Description
A Class for shape functions. In simple cases, the shape functions have only one index that can be thought of as corresponding to the nodal points. In general, however, when quantities and their gradients are interpolated separately, the shape function have two indices: one corresponding to the nodal points, and the other to the "type" of quantity being interpolated: function, derivative, &c The second index can also represent the vector coordinate for vector-valued (Nedelec) shape functions.
The implementation of Shape functions is designed to permit fast copying of entire sets of values by resetting the internal pointer to the data, Psi; functionality that is required, for example, when setting the test functions in Galerkin elements and when reading pre-computed values of the shape functions. In general, we cannot know at construction time whether the pointer to the values will be reset or not and, therefore, whether the storage for values should be allocated by the object. We choose to allocate storage on construction and store an additional pointer Allocated_data that always addresses the storage allocated by the object. If the Psi pointer is reset then this storage will be "wasted", but only for the lifetime of the object. The cost for non-copied Shape functions is one additional pointer.
Constructor & Destructor Documentation
Shape() [1/4]
oomph::Shape::Shape (const unsigned & N) inline
Constructor for a single-index set of shape functions.
                              : Index1(N), Index2(1)
     {
       Allocated_storage = new double[N];
       Psi = Allocated_storage;
     }
References Allocated_storage, N, and Psi.
Shape() [2/4]
oomph::Shape::Shape (const unsigned & N, const unsigned & M) inline
Constructor for a two-index set of shape functions.
                                                 : Index1(N), Index2(M)
     {
       Allocated_storage = new double[N * M];
       Psi = Allocated_storage;
     }
References Allocated_storage, N, and Psi.
Shape() [3/4]
oomph::Shape::Shape (const Shape & shape) delete
Broken copy constructor.
Shape() [4/4]
oomph::Shape::Shape () inline
Default constructor - just assigns a null pointers and zero index sizes.
 : Psi(0), Allocated_storage(0), Index1(0), Index2(0) {}
~Shape()
oomph::Shape::~Shape () inline
Destructor, clear up the memory allocated by the object.
     {
       delete[] Allocated_storage;
       Allocated_storage = 0;
     }
References Allocated_storage.
Member Function Documentation
nindex1()
unsigned oomph::Shape::nindex1 () const inline
Return the range of index 1 of the shape function object.
     {
       return Index1;
     }
References Index1.
Referenced by oomph::LineDerivatives::compute_surface_derivatives(), oomph::AxisymmetricDerivatives::compute_surface_derivatives(), oomph::SurfaceDerivatives::compute_surface_derivatives(), oomph::ClampedHermiteShellBoundaryConditionElement::dshape_local(), and oomph::ClampedHermiteShellBoundaryConditionElement::shape().
nindex2()
unsigned oomph::Shape::nindex2 () const inline
Return the range of index 2 of the shape function object.
     {
       return Index2;
     }
References Index2.
Referenced by oomph::ClampedHermiteShellBoundaryConditionElement::dshape_local(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::scale_basis(), oomph::TRaviartThomasDarcyElement< ORDER >::scale_basis(), oomph::TPoroelasticityElement< ORDER >::scale_basis(), and oomph::ClampedHermiteShellBoundaryConditionElement::shape().
operator()() [1/4]
double& oomph::Shape::operator() (const unsigned & i) inline
Overload the round bracket operator to provide access to values.
     {
 #ifdef RANGE_CHECKING
       range_check(i, 0);
 #endif
       return Psi[i * Index2];
     }
References i, Index2, Psi, and range_check().
operator()() [2/4]
const double& oomph::Shape::operator() (const unsigned & i) const inline
Overload the round bracket operator (const version)
     {
 #ifdef RANGE_CHECKING
       range_check(i, 0);
 #endif
       return Psi[i * Index2];
     }
References i, Index2, Psi, and range_check().
operator()() [3/4]
double& oomph::Shape::operator() (const unsigned & i, const unsigned & j) inline
Overload the round bracket operator, allowing for two indices.
     {
 #ifdef RANGE_CHECKING
       range_check(i, j);
 #endif
       return Psi[i * Index2 + j];
     }
References i, Index2, j, Psi, and range_check().
operator()() [4/4]
const double& oomph::Shape::operator() (const unsigned & i, const unsigned & j) const inline
Overload the round bracket operator, allowing for two indices (const version)
     {
 #ifdef RANGE_CHECKING
       range_check(i, j);
 #endif
       return Psi[i * Index2 + j];
     }
References i, Index2, j, Psi, and range_check().
operator=() [1/2]
void oomph::Shape::operator= (const Shape & shape) inline
The assignment operator does a shallow copy (resets the pointer to the data)
     {
 #ifdef PARANOID
       // Check the dimensions
       if ((shape.Index1 != Index1) || (shape.Index2 != Index2))
       {
         std::ostringstream error_stream;
         error_stream << "Cannot assign Shape object:" << std::endl
                      << "Indices do not match "
                      << "LHS: " << Index1 << " " << Index2
                      << ", RHS: " << shape.Index1 << " " << shape.Index2
                      << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       Psi = shape.Psi;
     }
References Index1, Index2, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, Psi, and oomph::OneDimHermite::shape().
operator=() [2/2]
void oomph::Shape::operator= (Shape *const & shape_pt) inline
The assignment operator does a shallow copy (resets the pointer to the data)
     {
 #ifdef PARANOID
       // Check the dimensions
       if ((shape_pt->Index1 != Index1) || (shape_pt->Index2 != Index2))
       {
         std::ostringstream error_stream;
         error_stream << "Cannot assign Shape object:" << std::endl
                      << "Indices do not match "
                      << "LHS: " << Index1 << " " << Index2
                      << ", RHS: " << shape_pt->Index1 << " " << shape_pt->Index2
                      << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       Psi = shape_pt->Psi;
     }
References Index1, Index2, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and Psi.
operator[]() [1/2]
double& oomph::Shape::operator[] (const unsigned & i) inline
Overload the bracket operator to provide access to values.
     {
 #ifdef RANGE_CHECKING
       range_check(i, 0);
 #endif
       return Psi[i * Index2];
     }
References i, Index2, Psi, and range_check().
operator[]() [2/2]
const double& oomph::Shape::operator[] (const unsigned & i) const inline
Overload the bracket operator (const version)
     {
 #ifdef RANGE_CHECKING
       range_check(i, 0);
 #endif
       return Psi[i * Index2];
     }
References i, Index2, Psi, and range_check().
range_check()
void oomph::Shape::range_check (const unsigned & i, const unsigned & j) const inline protected
Private function that checks whether the index is in range.
     {
       // If an index is out of range, throw an error
       if ((i >= Index1) || (j >= Index2))
       {
         std::ostringstream error_stream;
         error_stream << "Range Error: ";
         if (i >= Index1)
         {
           error_stream << i << " is not in the range (0," << Index1 - 1 << ")"
                        << std::endl;
         }
         if (j >= Index2)
         {
           error_stream << j << " is not in the range (0," << Index2 - 1 << ")"
                        << std::endl;
         }
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
     }
References i, Index1, Index2, j, OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by operator()(), and operator[]().
resize()
void oomph::Shape::resize (const unsigned & N, const unsigned & M = 1) inline
Change the size of the storage.
     {
       // Clear old storage
       delete[] Allocated_storage;
       Allocated_storage = 0;
       Psi = 0;
       // Allocate new storage
       Index1 = N;
       Index2 = M;
       Allocated_storage = new double[N * M];
       Psi = Allocated_storage;
     }
References Allocated_storage, Index1, Index2, N, and Psi.
Member Data Documentation
Allocated_storage
double* oomph::Shape::Allocated_storage protected
Pointer that addresses the storage allocated by the object on construction. This will be the same as Psi if the object is not copied.
Referenced by resize(), Shape(), ~Shape(), and oomph::ShapeWithDeepCopy::~ShapeWithDeepCopy().
Index1
unsigned oomph::Shape::Index1 protected
Size of the first index of the shape function.
Referenced by nindex1(), operator=(), range_check(), resize(), and oomph::ShapeWithDeepCopy::ShapeWithDeepCopy().
Index2
unsigned oomph::Shape::Index2 protected
Size of the second index of the shape function.
Referenced by nindex2(), operator()(), operator=(), operator[](), range_check(), resize(), and oomph::ShapeWithDeepCopy::ShapeWithDeepCopy().
Psi
double* oomph::Shape::Psi protected
Pointer that addresses the storage that will be used to read and set the shape functions. The shape functions are packed into a flat array of doubles.
Referenced by operator()(), operator=(), operator[](), resize(), Shape(), and oomph::ShapeWithDeepCopy::ShapeWithDeepCopy().
The documentation for this class was generated from the following file:
shape.h