MercuryDPM: Eigen::internal::matrix_exp_computeUV< MatrixType, long double > Struct Template Reference
Eigen::internal::matrix_exp_computeUV< MatrixType, long double > Struct Template Reference
#include <MatrixExponential.h>
Static Public Member Functions
template<typename ArgType >
static void run (const ArgType &arg, MatrixType &U, MatrixType &V, int &squarings)
Member Function Documentation
run()
template<typename MatrixType > template<typename ArgType > static void Eigen::internal::matrix_exp_computeUV< MatrixType, long double >::run (const ArgType & arg, MatrixType & U, MatrixType & V, int & squarings) inline static
{
 #if LDBL_MANT_DIG == 53  // double precision
     matrix_exp_computeUV<MatrixType, double>::run(arg, U, V, squarings);
 #else
     using std::frexp;
     using std::pow;
     const long double l1norm = arg.cwiseAbs().colwise().sum().maxCoeff();
     squarings = 0;
 #if LDBL_MANT_DIG <= 64  // extended precision
     if (l1norm < 4.1968497232266989671e-003L) {
       matrix_exp_pade3(arg, U, V);
     } else if (l1norm < 1.1848116734693823091e-001L) {
       matrix_exp_pade5(arg, U, V);
     } else if (l1norm < 5.5170388480686700274e-001L) {
       matrix_exp_pade7(arg, U, V);
     } else if (l1norm < 1.3759868875587845383e+000L) {
       matrix_exp_pade9(arg, U, V);
     } else {
       const long double maxnorm = 4.0246098906697353063L;
       frexp(l1norm / maxnorm, &squarings);
       if (squarings < 0) squarings = 0;
       MatrixType A = arg.unaryExpr(MatrixExponentialScalingOp<long double>(squarings));
       matrix_exp_pade13(A, U, V);
     }
 #elif LDBL_MANT_DIG <= 106  // double-double
     if (l1norm < 3.2787892205607026992947488108213e-005L) {
       matrix_exp_pade3(arg, U, V);
     } else if (l1norm < 6.4467025060072760084130906076332e-003L) {
       matrix_exp_pade5(arg, U, V);
     } else if (l1norm < 6.8988028496595374751374122881143e-002L) {
       matrix_exp_pade7(arg, U, V);
     } else if (l1norm < 2.7339737518502231741495857201670e-001L) {
       matrix_exp_pade9(arg, U, V);
     } else if (l1norm < 1.3203382096514474905666448850278e+000L) {
       matrix_exp_pade13(arg, U, V);
     } else {
       const long double maxnorm = 3.2579440895405400856599663723517L;
       frexp(l1norm / maxnorm, &squarings);
       if (squarings < 0) squarings = 0;
       MatrixType A = arg.unaryExpr(MatrixExponentialScalingOp<long double>(squarings));
       matrix_exp_pade17(A, U, V);
     }
 #elif LDBL_MANT_DIG <= 113  // quadruple precision
     if (l1norm < 1.639394610288918690547467954466970e-005L) {
       matrix_exp_pade3(arg, U, V);
     } else if (l1norm < 4.253237712165275566025884344433009e-003L) {
       matrix_exp_pade5(arg, U, V);
     } else if (l1norm < 5.125804063165764409885122032933142e-002L) {
       matrix_exp_pade7(arg, U, V);
     } else if (l1norm < 2.170000765161155195453205651889853e-001L) {
       matrix_exp_pade9(arg, U, V);
     } else if (l1norm < 1.125358383453143065081397882891878e+000L) {
       matrix_exp_pade13(arg, U, V);
     } else {
       const long double maxnorm = 2.884233277829519311757165057717815L;
       frexp(l1norm / maxnorm, &squarings);
       if (squarings < 0) squarings = 0;
       MatrixType A = arg.unaryExpr(MatrixExponentialScalingOp<long double>(squarings));
       matrix_exp_pade17(A, U, V);
     }
 #else
     // this case should be handled in compute()
     eigen_assert(false && "Bug in MatrixExponential");
 #endif
 #endif  // LDBL_MANT_DIG
   }
References eigen_assert, Eigen::internal::matrix_exp_pade13(), Eigen::internal::matrix_exp_pade3(), Eigen::internal::matrix_exp_pade5(), Eigen::internal::matrix_exp_pade7(), Eigen::internal::matrix_exp_pade9(), Eigen::bfloat16_impl::pow(), Eigen::internal::matrix_exp_computeUV< MatrixType, RealScalar >::run(), RachelsAdvectionDiffusion::U, and V.
The documentation for this struct was generated from the following file:
MatrixExponential.h