MercuryDPM: oomph::DiskLikeGeomObjectWithBoundaries Class Reference
oomph::DiskLikeGeomObjectWithBoundaries Class Reference
#include <geom_obj_with_boundary.h>
Public Member Functions
DiskLikeGeomObjectWithBoundaries ()
Constructor.
unsigned nboundary () const
How many boundaries do we have?
void position_on_boundary (const unsigned &b, const double &zeta_bound, Vector< double > &r) const
void zeta_on_boundary (const unsigned &b, const double &zeta_bound, Vector< double > &zeta) const
GeomObject * boundary_parametrising_geom_object_pt (const unsigned &b) const
double zeta_boundary_start (const unsigned &b) const
double zeta_boundary_end (const unsigned &b) const
virtual void boundary_triad (const unsigned &b, const double &zeta_bound, Vector< double > &r, Vector< double > &tangent, Vector< double > &normal, Vector< double > &binormal)
void output_boundaries (const unsigned &nplot, std::ofstream &two_d_boundaries_file, std::ofstream &three_d_boundaries_file)
void output_boundaries_and_triads (const unsigned &nplot, std::ofstream &two_d_boundaries_file, std::ofstream &three_d_boundaries_file, std::ofstream &boundaries_tangent_file, std::ofstream &boundaries_normal_file, std::ofstream &boundaries_binormal_file)
void add_region_coordinates (const unsigned &r, Vector< double > &zeta_in_region)
std::map< unsigned, Vector< double > > zeta_in_region () const
Return map that stores zeta coordinates of points that identify regions.
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual unsigned ngeom_data () const
virtual Data * geom_data_pt (const unsigned &j)
virtual void position (const Vector< double > &zeta, Vector< double > &r) const =0
Parametrised position on object at current time: r(zeta).
virtual void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition_dt (const Vector< double > &zeta, const unsigned &j, Vector< double > &drdt)
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
virtual void locate_zeta (const Vector< double > &zeta, GeomObject *&sub_geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
Protected Attributes
Vector< double > Zeta_boundary_start
Vector< double > Zeta_boundary_end
Vector< GeomObject * > Boundary_parametrising_geom_object_pt
std::map< unsigned, Vector< double > > Zeta_in_region
Map to store zeta coordinates of points that identify regions.
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Detailed Description
Base class for upgraded disk-like GeomObject (i.e. 2D surface in 3D space) with specification of boundaries. The GeomObject's position(...) function computes the 3D (Eulerian) position vector r as a function of the 2D intrinsic (Lagrangian) coordinates, zeta, without reference to any boundaries. This class specifies the boundaries by specifying a mapping from a 1D intrinsic boundary coordinate, zeta_bound, to the 2D intrinsic (Lagrangian) coordinates, zeta.
The class is made functional by provision (in the derived class!) of:
a pointer to a GeomObject<1,2> that parametrises the 2D intrinisic coordinates zeta along boundary b in terms of the 1D boundary coordinate, zeta_bound,
the initial value of the 1D boundary coordinate zeta_bound on boundary b,
the final value of the 1D boundary coordinate zeta_bound on boundary b
for each of these boundaries. All three containers for these must be resized (consistently) and populated in the derived class. Number of boundaries is inferred from their size.
Class also provides broken virtual function to specify boundary triads, and various output functions.
Constructor & Destructor Documentation
DiskLikeGeomObjectWithBoundaries()
oomph::DiskLikeGeomObjectWithBoundaries::DiskLikeGeomObjectWithBoundaries () inline
Constructor.
 : GeomObject(2, 3) {}
Member Function Documentation
add_region_coordinates()
void oomph::DiskLikeGeomObjectWithBoundaries::add_region_coordinates (const unsigned & r, Vector< double > & zeta_in_region) inline
Specify intrinsic coordinates of a point within a specified region – region ID, r, should be positive.
     {
       // Verify if not using the default region number (zero)
       if (r == 0)
       {
         std::ostringstream error_message;
         error_message
           << "Please use another region id different from zero.\n"
           << "It is internally used as the default region number.\n";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
       // Need two coordinates
       unsigned n = zeta_in_region.size();
       if (n != 2)
       {
         std::ostringstream error_message;
         error_message << "Vector specifying zeta coordinates of point in\n"
                       << "region has be length 2; yours has length " << n
                       << std::endl;
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
       // First check if the region with the specified id does not already exist
       std::map<unsigned, Vector<double>>::iterator it;
       it = Zeta_in_region.find(r);
       // If it is already a region defined with that id throw an error
       if (it != Zeta_in_region.end())
       {
         std::ostringstream error_message;
         error_message << "The region id (" << r << ") that you are using for"
                       << "defining\n"
                       << "your region is already in use. Use another\n"
                       << "region id and verify that you are not re-using\n"
                       << " previously defined regions ids.\n"
                       << std::endl;
         OomphLibWarning(error_message.str(),
                         OOMPH_CURRENT_FUNCTION,
                         OOMPH_EXCEPTION_LOCATION);
       }
       // If it does not exist then create the map
       Zeta_in_region[r] = zeta_in_region;
     }
References n, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, UniformPSDSelfTest::r, zeta_in_region(), and Zeta_in_region.
Referenced by oomph::WarpedCircularDiskWithAnnularInternalBoundary::WarpedCircularDiskWithAnnularInternalBoundary().
boundary_parametrising_geom_object_pt()
GeomObject* oomph::DiskLikeGeomObjectWithBoundaries::boundary_parametrising_geom_object_pt (const unsigned & b) const inline
Pointer to GeomObject<1,2> that parametrises intrinisc coordinates along boundary b
     {
       return Boundary_parametrising_geom_object_pt[b];
     }
References b, and Boundary_parametrising_geom_object_pt.
boundary_triad()
virtual void oomph::DiskLikeGeomObjectWithBoundaries::boundary_triad (const unsigned & b, const double & zeta_bound, Vector< double > & r, Vector< double > & tangent, Vector< double > & normal, Vector< double > & binormal) inline virtual
Boundary triad on boundary b at boundary coordinate zeta_bound. Broken virtual.
Reimplemented in oomph::WarpedCircularDisk.
     {
       std::ostringstream error_message;
       error_message << "Broken virtual function; please implement for your\n"
                     << "derived version of this class!" << std::endl;
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::DiskWithTorusAroundEdgeTetMeshFacetedSurface::DiskWithTorusAroundEdgeTetMeshFacetedSurface(), and output_boundaries_and_triads().
nboundary()
unsigned oomph::DiskLikeGeomObjectWithBoundaries::nboundary () const inline
How many boundaries do we have?
     {
       return Boundary_parametrising_geom_object_pt.size();
     }
References Boundary_parametrising_geom_object_pt.
Referenced by oomph::DiskTetMeshFacetedSurface::DiskTetMeshFacetedSurface(), output_boundaries_and_triads(), and oomph::WarpedCircularDisk::~WarpedCircularDisk().
output_boundaries()
void oomph::DiskLikeGeomObjectWithBoundaries::output_boundaries (const unsigned & nplot, std::ofstream & two_d_boundaries_file, std::ofstream & three_d_boundaries_file) inline
Output boundaries at nplot plot points. Streams:
two_d_boundaries_file: zeta_0, zeta_1, zeta_bound
three_d_boundaries_file : x, y, z, zeta_0, zeta_1, zeta_bound
     {
       std::ofstream boundaries_tangent_file;
       std::ofstream boundaries_normal_file;
       std::ofstream boundaries_binormal_file;
       output_boundaries_and_triads(nplot,
                                    two_d_boundaries_file,
                                    three_d_boundaries_file,
                                    boundaries_tangent_file,
                                    boundaries_normal_file,
                                    boundaries_binormal_file);
     }
References output_boundaries_and_triads().
output_boundaries_and_triads()
void oomph::DiskLikeGeomObjectWithBoundaries::output_boundaries_and_triads (const unsigned & nplot, std::ofstream & two_d_boundaries_file, std::ofstream & three_d_boundaries_file, std::ofstream & boundaries_tangent_file, std::ofstream & boundaries_normal_file, std::ofstream & boundaries_binormal_file) inline
Output boundaries and triad at nplot plot points. Streams:
two_d_boundaries_file: zeta_0, zeta_1, zeta_bound
three_d_boundaries_file : x, y, z, zeta_0, zeta_1, zeta_bound
boundaries_tangent_file : x, y, z, t_x, t_y, t_z
boundaries_normal_file : x, y, z, n_x, n_y, n_z
boundaries_binormal_file: x, y, z, N_x, N_y, N_z
     {
       Vector<double> r(3);
       Vector<double> zeta(2);
       double zeta_bound = 0.0;
       Vector<double> tangent(3);
       Vector<double> normal(3);
       Vector<double> binormal(3);
       unsigned nb = nboundary();
       for (unsigned b = 0; b < nb; b++)
       {
         two_d_boundaries_file << "ZONE" << std::endl;
         three_d_boundaries_file << "ZONE" << std::endl;
         boundaries_tangent_file << "ZONE" << std::endl;
         boundaries_normal_file << "ZONE" << std::endl;
         boundaries_binormal_file << "ZONE" << std::endl;
         double zeta_min = zeta_boundary_start(b);
         double zeta_max = zeta_boundary_end(b);
         unsigned n = 100;
         for (unsigned i = 0; i < n; i++)
         {
           zeta_bound =
             zeta_min + (zeta_max - zeta_min) * double(i) / double(n - 1);
           position_on_boundary(b, zeta_bound, r);
           zeta_on_boundary(b, zeta_bound, zeta);
           boundary_triad(b, zeta_bound, r, tangent, normal, binormal);
           two_d_boundaries_file << zeta[0] << " " << zeta[1] << " "
                                 << zeta_bound << " " << std::endl;
           three_d_boundaries_file << r[0] << " " << r[1] << " " << r[2] << " "
                                   << zeta[0] << " " << zeta[1] << " "
                                   << zeta_bound << " " << std::endl;
           boundaries_tangent_file << r[0] << " " << r[1] << " " << r[2] << " "
                                   << tangent[0] << " " << tangent[1] << " "
                                   << tangent[2] << " " << std::endl;
           boundaries_normal_file << r[0] << " " << r[1] << " " << r[2] << " "
                                  << normal[0] << " " << normal[1] << " "
                                  << normal[2] << " " << std::endl;
           boundaries_binormal_file << r[0] << " " << r[1] << " " << r[2] << " "
                                    << binormal[0] << " " << binormal[1] << " "
                                    << binormal[2] << " " << std::endl;
         }
       }
     }
References b, boundary_triad(), i, n, nb, nboundary(), WallFunction::normal(), position_on_boundary(), UniformPSDSelfTest::r, Eigen::zeta(), zeta_boundary_end(), zeta_boundary_start(), and zeta_on_boundary().
Referenced by main(), and output_boundaries().
position_on_boundary()
void oomph::DiskLikeGeomObjectWithBoundaries::position_on_boundary (const unsigned & b, const double & zeta_bound, Vector< double > & r) const inline
Compute 3D vector of Eulerian coordinates at 1D boundary coordinate zeta_bound on boundary b:
     {
       Vector<double> zeta(2);
       zeta_on_boundary(b, zeta_bound, zeta);
       position(zeta, r);
     }
References b, oomph::GeomObject::position(), UniformPSDSelfTest::r, Eigen::zeta(), and zeta_on_boundary().
Referenced by output_boundaries_and_triads().
zeta_boundary_end()
double oomph::DiskLikeGeomObjectWithBoundaries::zeta_boundary_end (const unsigned & b) const inline
Final value of 1D boundary coordinate zeta_bound on boundary b:
     {
       return Zeta_boundary_end[b];
     }
References b, and Zeta_boundary_end.
Referenced by oomph::DiskWithTorusAroundEdgeTetMeshFacetedSurface::DiskWithTorusAroundEdgeTetMeshFacetedSurface(), and output_boundaries_and_triads().
zeta_boundary_start()
double oomph::DiskLikeGeomObjectWithBoundaries::zeta_boundary_start (const unsigned & b) const inline
Initial value of 1D boundary coordinate zeta_bound on boundary b:
     {
       return Zeta_boundary_start[b];
     }
References b, and Zeta_boundary_start.
Referenced by output_boundaries_and_triads().
zeta_in_region()
std::map<unsigned, Vector<double> > oomph::DiskLikeGeomObjectWithBoundaries::zeta_in_region () const inline
Return map that stores zeta coordinates of points that identify regions.
     {
       return Zeta_in_region;
     }
References Zeta_in_region.
Referenced by add_region_coordinates(), oomph::DiskTetMeshFacetedSurface::DiskTetMeshFacetedSurface(), and oomph::WarpedCircularDiskWithAnnularInternalBoundary::WarpedCircularDiskWithAnnularInternalBoundary().
zeta_on_boundary()
void oomph::DiskLikeGeomObjectWithBoundaries::zeta_on_boundary (const unsigned & b, const double & zeta_bound, Vector< double > & zeta) const inline
Compute 2D vector of intrinsic coordinates at 1D boundary coordinate zeta_bound on boundary b:
     {
 #ifdef PARANOID
       if (Boundary_parametrising_geom_object_pt[b] == 0)
       {
         std::ostringstream error_message;
         error_message << "You must create a <1,2> Geom Object that provides a\n"
                       << "mapping from the 1D boundary coordinate to the 2D\n"
                       << "intrinsic Lagrangian coordinate of disk-like object\n"
                       << std::endl;
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
       if (Boundary_parametrising_geom_object_pt[b]->nlagrangian() != 1)
       {
         std::ostringstream error_message;
         error_message << "Boundary_parametrising_geom_object_pt must point to\n"
                       << "GeomObject with one Lagrangian coordinate. Yours has "
                       << Boundary_parametrising_geom_object_pt[b]->nlagrangian()
                       << std::endl;
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
       if (Boundary_parametrising_geom_object_pt[b]->ndim() != 2)
       {
         std::ostringstream error_message;
         error_message << "Boundary_parametrising_geom_object_pt must point to\n"
                       << "GeomObject with two Eulerian coordinates. Yours has "
                       << Boundary_parametrising_geom_object_pt[b]->ndim()
                       << std::endl;
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       Vector<double> zeta_bound_vector(1, zeta_bound);
       Boundary_parametrising_geom_object_pt[b]->position(zeta_bound_vector,
                                                          zeta);
     }
References b, Boundary_parametrising_geom_object_pt, oomph::GeomObject::ndim(), oomph::GeomObject::nlagrangian(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and Eigen::zeta().
Referenced by oomph::DiskTetMeshFacetedSurface::boundary_zeta01(), output_boundaries_and_triads(), and position_on_boundary().
Member Data Documentation
Boundary_parametrising_geom_object_pt
Vector<GeomObject*> oomph::DiskLikeGeomObjectWithBoundaries::Boundary_parametrising_geom_object_pt protected
Pointer to GeomObject<1,2> that parametrises intrinisc coordinates along boundary b; essentially provides a wrapper to zeta_on_boundary(...)
Referenced by boundary_parametrising_geom_object_pt(), nboundary(), oomph::WarpedCircularDisk::WarpedCircularDisk(), oomph::WarpedCircularDiskWithAnnularInternalBoundary::WarpedCircularDiskWithAnnularInternalBoundary(), zeta_on_boundary(), and oomph::WarpedCircularDisk::~WarpedCircularDisk().
Zeta_boundary_end
Vector<double> oomph::DiskLikeGeomObjectWithBoundaries::Zeta_boundary_end protected
Storage for final value of 1D boundary coordinate on boundary b:
Referenced by oomph::WarpedCircularDisk::WarpedCircularDisk(), oomph::WarpedCircularDiskWithAnnularInternalBoundary::WarpedCircularDiskWithAnnularInternalBoundary(), and zeta_boundary_end().
Zeta_boundary_start
Vector<double> oomph::DiskLikeGeomObjectWithBoundaries::Zeta_boundary_start protected
Storage for initial value of 1D boundary coordinate on boundary b:
Referenced by oomph::WarpedCircularDisk::WarpedCircularDisk(), oomph::WarpedCircularDiskWithAnnularInternalBoundary::WarpedCircularDiskWithAnnularInternalBoundary(), and zeta_boundary_start().
Zeta_in_region
std::map<unsigned, Vector<double> > oomph::DiskLikeGeomObjectWithBoundaries::Zeta_in_region protected
Map to store zeta coordinates of points that identify regions.
Referenced by add_region_coordinates(), and zeta_in_region().
The documentation for this class was generated from the following file:
geom_obj_with_boundary.h