MercuryDPM: Eigen::LeastSquareDiagonalPreconditioner< Scalar_ > Class Template Reference
Eigen::LeastSquareDiagonalPreconditioner< Scalar_ > Class Template Reference
Sparse linear algebra » Reference » IterativeLinearSolvers_Module
Jacobi preconditioner for LeastSquaresConjugateGradient.
#include <BasicPreconditioners.h>
Public Member Functions
LeastSquareDiagonalPreconditioner ()
template<typename MatType >
LeastSquareDiagonalPreconditioner (const MatType &mat)
template<typename MatType >
LeastSquareDiagonalPreconditioner & analyzePattern (const MatType &)
template<typename MatType >
LeastSquareDiagonalPreconditioner & factorize (const MatType &mat)
template<typename MatType >
LeastSquareDiagonalPreconditioner & compute (const MatType &mat)
ComputationInfo info ()
Public Member Functions inherited from Eigen::DiagonalPreconditioner< Scalar_ >
DiagonalPreconditioner ()
template<typename MatType >
DiagonalPreconditioner (const MatType &mat)
EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
template<typename MatType >
DiagonalPreconditioner & analyzePattern (const MatType &)
template<typename MatType >
DiagonalPreconditioner & factorize (const MatType &mat)
template<typename MatType >
DiagonalPreconditioner & compute (const MatType &mat)
template<typename Rhs , typename Dest >
void _solve_impl (const Rhs &b, Dest &x) const
template<typename Rhs >
const Solve< DiagonalPreconditioner, Rhs > solve (const MatrixBase< Rhs > &b) const
ComputationInfo info ()
Private Types
typedef Scalar_ Scalar
typedef NumTraits< Scalar >::Real RealScalar
typedef DiagonalPreconditioner< Scalar_ > Base
Private Attributes
Vector m_invdiag
Additional Inherited Members
Public Types inherited from Eigen::DiagonalPreconditioner< Scalar_ >
enum { ColsAtCompileTime = Dynamic , MaxColsAtCompileTime = Dynamic }
typedef Vector::StorageIndex StorageIndex
Protected Attributes inherited from Eigen::DiagonalPreconditioner< Scalar_ >
Vector m_invdiag
bool m_isInitialized
Detailed Description
template<typename Scalar_>
class Eigen::LeastSquareDiagonalPreconditioner< Scalar_ >
Jacobi preconditioner for LeastSquaresConjugateGradient.
This class allows to approximately solve for A' A x = A' b problems assuming A' A is a diagonal matrix. In other words, this preconditioner neglects all off diagonal entries and, in Eigen's language, solves for:
(A.adjoint() * A).diagonal().asDiagonal() * x = b
Template Parameters
Scalar_ the type of the scalar.
\implsparsesolverconcept
The diagonal entries are pre-inverted and stored into a dense vector.
See also
class LeastSquaresConjugateGradient, class DiagonalPreconditioner
Member Typedef Documentation
Base
template<typename Scalar_ > typedef DiagonalPreconditioner<Scalar_> Eigen::LeastSquareDiagonalPreconditioner< Scalar_ >::Base private
RealScalar
template<typename Scalar_ > typedef NumTraits<Scalar>::Real Eigen::LeastSquareDiagonalPreconditioner< Scalar_ >::RealScalar private
Scalar
template<typename Scalar_ > typedef Scalar_ Eigen::LeastSquareDiagonalPreconditioner< Scalar_ >::Scalar private
Constructor & Destructor Documentation
LeastSquareDiagonalPreconditioner() [1/2]
template<typename Scalar_ > Eigen::LeastSquareDiagonalPreconditioner< Scalar_ >::LeastSquareDiagonalPreconditioner () inline
 : Base() {}
LeastSquareDiagonalPreconditioner() [2/2]
template<typename Scalar_ > template<typename MatType > Eigen::LeastSquareDiagonalPreconditioner< Scalar_ >::LeastSquareDiagonalPreconditioner (const MatType & mat) inline explicit
                                                                  : Base() {
     compute(mat);
   }
References Eigen::LeastSquareDiagonalPreconditioner< Scalar_ >::compute().
Member Function Documentation
analyzePattern()
template<typename Scalar_ > template<typename MatType > LeastSquareDiagonalPreconditioner& Eigen::LeastSquareDiagonalPreconditioner< Scalar_ >::analyzePattern (const MatType &) inline
{
     return *this;
   }
compute()
template<typename Scalar_ > template<typename MatType > LeastSquareDiagonalPreconditioner& Eigen::LeastSquareDiagonalPreconditioner< Scalar_ >::compute (const MatType & mat) inline
{
     return factorize(mat);
   }
References Eigen::LeastSquareDiagonalPreconditioner< Scalar_ >::factorize().
Referenced by Eigen::LeastSquareDiagonalPreconditioner< Scalar_ >::LeastSquareDiagonalPreconditioner().
factorize()
template<typename Scalar_ > template<typename MatType > LeastSquareDiagonalPreconditioner& Eigen::LeastSquareDiagonalPreconditioner< Scalar_ >::factorize (const MatType & mat) inline
{
     // Compute the inverse squared-norm of each column of mat
     m_invdiag.resize(mat.cols());
     if (MatType::IsRowMajor) {
       m_invdiag.setZero();
       for (Index j = 0; j < mat.outerSize(); ++j) {
         for (typename MatType::InnerIterator it(mat, j); it; ++it) m_invdiag(it.index()) += numext::abs2(it.value());
       }
       for (Index j = 0; j < mat.cols(); ++j)
         if (numext::real(m_invdiag(j)) > RealScalar(0)) m_invdiag(j) = RealScalar(1) / numext::real(m_invdiag(j));
     } else {
       for (Index j = 0; j < mat.outerSize(); ++j) {
         RealScalar sum = mat.col(j).squaredNorm();
         if (sum > RealScalar(0))
           m_invdiag(j) = RealScalar(1) / sum;
         else
           m_invdiag(j) = RealScalar(1);
       }
     }
     Base::m_isInitialized = true;
     return *this;
   }
References Eigen::numext::abs2(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::cols(), j, Eigen::LeastSquareDiagonalPreconditioner< Scalar_ >::m_invdiag, Eigen::DiagonalPreconditioner< Scalar_ >::m_isInitialized, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::outerSize(), Eigen::PlainObjectBase< Derived >::resize(), Eigen::PlainObjectBase< Derived >::setZero(), and Eigen::SparseMatrixBase< Derived >::squaredNorm().
Referenced by Eigen::LeastSquareDiagonalPreconditioner< Scalar_ >::compute().
info()
template<typename Scalar_ > ComputationInfo Eigen::LeastSquareDiagonalPreconditioner< Scalar_ >::info () inline
 { return Success; }
References Eigen::Success.
Member Data Documentation
m_invdiag
template<typename Scalar_ > Vector Eigen::DiagonalPreconditioner< Scalar_ >::m_invdiag private
Referenced by Eigen::LeastSquareDiagonalPreconditioner< Scalar_ >::factorize().
The documentation for this class was generated from the following file:
BasicPreconditioners.h