MercuryDPM: InfiniteWallWithHole Class Reference
InfiniteWallWithHole Class Reference
#include <InfiniteWallWithHole.h>
Public Member Functions
InfiniteWallWithHole ()
default constructor
InfiniteWallWithHole (Vec3D normal, Mdouble position, Mdouble holeRadius)
InfiniteWallWithHole (const InfiniteWallWithHole &p)
InfiniteWallWithHole * copy () const override
Wall copy method. It calls the copy contrustor of this Wall, usefull for polymorfism.
void set (Vec3D normal, Mdouble position, Mdouble holeRadius)
Defines a standard wall, given an outward normal vector s. t. normal*x=position.
void moveTo (Mdouble position)
Allows the wall to be moved to a new position.
void move_time (Mdouble dt)
Mdouble getWallDistance (const Vec3D &position) const
Returns the distance of the wall to the particle.
Mdouble getHoleDistance (const Vec3D &position) const
bool getDistanceAndNormal (const BaseParticle &P, Mdouble &distance, Vec3D &normal_return) const override
Since this function should be called before calculating any Particle-Wall interactions, it can also be used to set the normal vector in case of curved walls.
void read (std::istream &is) override
reads wall
void oldRead (std::istream &is)
reads wall
void write (std::ostream &os) const override
outputs wall
std::string getName () const override
Returns the name of the object.
Vec3D getNormal ()
access function for normal
Mdouble getPosition ()
access function for position
Public Member Functions inherited from BaseWall
BaseWall ()
Default constructor.
BaseWall (const BaseWall &w)
Copy constructor.
~BaseWall () override
Default destructor.
virtual bool getDistanceNormalOverlap (const BaseParticle &P, Mdouble &distance, Vec3D &normal_return, Mdouble &overlap) const
virtual bool getDistanceNormalOverlapSuperquadric (const SuperQuadricParticle &p, Mdouble &distance, Vec3D &normal_return, Mdouble &overlap) const
virtual Vec3D getFurthestPointSuperQuadric (const Vec3D &normalBodyFixed, const Vec3D &axes, Mdouble eps1, Mdouble eps2) const
virtual void setHandler (WallHandler *handler)
A function which sets the WallHandler for this BaseWall.
WallHandler * getHandler () const
A function which returns the WallHandler that handles this BaseWall.
void setIndSpecies (unsigned int indSpecies) override
Define the species of this wall using the index of the species in the SpeciesHandler in this DPMBase.
void setSpecies (const ParticleSpecies *species)
Defines the species of the current wall.
bool isFixed () const override
void setForceControl (Vec3D forceGoal, Vec3D gainFactor, Vec3D baseVelocity={0, 0, 0})
Slowly adjusts the force on a wall towards a specified goal, by adjusting (prescribing) the velocity of the wall.
virtual bool isLocal (Vec3D &min, Vec3D &max) const
bool getLinePlaneIntersect (Vec3D &intersect, const Vec3D &p0, const Vec3D &p1, const Vec3D &n, const Vec3D &p)
bool isInsideWallVTK (const Vec3D &point, const Vec3D &normal, const Vec3D &position) const
void projectOntoWallVTK (Vec3D &point0, const Vec3D &point1, const Vec3D &normal, const Vec3D &position) const
void intersectVTK (std::vector< Vec3D > &points, Vec3D normal, Vec3D position) const
virtual BaseInteraction * getInteractionWithSuperQuad (SuperQuadricParticle *p, unsigned timeStamp, InteractionHandler *interactionHandler)
virtual void writeVTK (VTKContainer &vtk) const
void getVTK (std::vector< Vec3D > &points, std::vector< std::vector< double >> &triangleStrips)
const Vec3D getAxis () const
BaseInteraction * getInteractionWith (BaseParticle *p, unsigned timeStamp, InteractionHandler *interactionHandler) override
Returns the interaction between this wall and a given particle, nullptr if there is no interaction.
virtual void actionsOnRestart ()
No implementation but can be overidden in its derived classes.
virtual void actionsAfterParticleGhostUpdate ()
No implementation but can be overidden in its derived classes.
virtual void handleParticleAddition (unsigned int id, BaseParticle *p)
Handles the addition of particles to the particleHandler.
virtual void handleParticleRemoval (unsigned int id)
Handles the addition of particles to the particleHandler.
virtual void checkInteractions (InteractionHandler *interactionHandler, unsigned int timeStamp)
Check if all interactions are valid.
bool getVTKVisibility () const
void setVTKVisibility (bool vtkVisibility)
void addRenderedWall (BaseWall *w)
BaseWall * getRenderedWall (size_t i) const
std::vector< BaseWall * > getRenderedWalls () const
void removeRenderedWalls ()
void renderWall (VTKContainer &vtk)
void addParticlesAtWall (unsigned numElements=50)
void setVelocityControl (Vec3D forceGoal, Vec3D gainFactor, Vec3D baseVelocity)
virtual void writeWallDetailsVTK (VTKData &data) const
virtual void computeWear ()
Public Member Functions inherited from BaseInteractable
BaseInteractable ()
Default BaseInteractable constructor.
BaseInteractable (const BaseInteractable &p)
Copy constructor.
~BaseInteractable () override
Destructor, it simply destructs the BaseInteractable and all the objects it contains.
unsigned int getIndSpecies () const
Returns the index of the species associated with the interactable object.
const ParticleSpecies * getSpecies () const
Returns a pointer to the species of this BaseInteractable.
void setSpecies (const ParticleSpecies *species)
Sets the species of this BaseInteractable.
const Vec3D & getForce () const
Returns the force on this BaseInteractable.
const Vec3D & getTorque () const
Returns the torque on this BaseInteractable.
void setForce (const Vec3D &force)
Sets the force on this BaseInteractable.
void setTorque (const Vec3D &torque)
Sets the torque on this BaseInteractable.
void addForce (const Vec3D &addForce)
Adds an amount to the force on this BaseInteractable.
void addTorque (const Vec3D &addTorque)
Adds an amount to the torque on this BaseInteractable.
virtual void resetForceTorque (int numberOfOMPthreads)
void sumForceTorqueOMP ()
const Vec3D & getPosition () const
Returns the position of this BaseInteractable.
const Quaternion & getOrientation () const
Returns the orientation of this BaseInteractable.
virtual void setPosition (const Vec3D &position)
Sets the position of this BaseInteractable.
void setOrientationViaNormal (Vec3D normal)
Sets the orientation of this BaseInteractable by defining the vector that results from the rotation of the (1,0,0) vector.
void setOrientationViaEuler (Vec3D eulerAngle)
Sets the orientation of this BaseInteractable by defining the euler angles.
virtual void setOrientation (const Quaternion &orientation)
Sets the orientation of this BaseInteractable.
virtual void move (const Vec3D &move)
Moves this BaseInteractable by adding an amount to the position.
virtual void rotate (const Vec3D &angularVelocityDt)
Rotates this BaseInteractable.
const std::vector< BaseInteraction * > & getInteractions () const
Returns a list of interactions which belong to this interactable.
void addInteraction (BaseInteraction *I)
Adds an interaction to this BaseInteractable.
bool removeInteraction (BaseInteraction *I)
Removes an interaction from this BaseInteractable.
void copyInteractionsForPeriodicParticles (const BaseInteractable &p)
Copies interactions to this BaseInteractable whenever a periodic copy made.
void setVelocity (const Vec3D &velocity)
set the velocity of the BaseInteractable.
void setAngularVelocity (const Vec3D &angularVelocity)
set the angular velocity of the BaseInteractble.
void addVelocity (const Vec3D &velocity)
adds an increment to the velocity.
void addAngularVelocity (const Vec3D &angularVelocity)
add an increment to the angular velocity.
virtual const Vec3D & getVelocity () const
Returns the velocity of this interactable.
virtual const Vec3D & getAngularVelocity () const
Returns the angular velocity of this interactable.
void setPrescribedPosition (const std::function< Vec3D(double)> &prescribedPosition)
Allows the position of an infinite mass interactable to be prescribed.
void applyPrescribedPosition (double time)
Computes the position from the user defined prescribed position function.
void setPrescribedVelocity (const std::function< Vec3D(double)> &prescribedVelocity)
Allows the velocity of an infinite mass interactable to be prescribed.
void applyPrescribedVelocity (double time)
Computes the velocity from the user defined prescribed velocity function.
void setPrescribedOrientation (const std::function< Quaternion(double)> &prescribedOrientation)
Allows the orientation of the infinite mass interactbale to be prescribed.
void applyPrescribedOrientation (double time)
Computes the orientation from the user defined prescribed orientation function.
void setPrescribedAngularVelocity (const std::function< Vec3D(double)> &prescribedAngularVelocity)
Allows the angular velocity of the infinite mass interactable to be prescribed.
void applyPrescribedAngularVelocity (double time)
Computes the angular velocity from the user defined prescribed angular velocity.
virtual const Vec3D getVelocityAtContact (const Vec3D &contact) const
Returns the velocity at the contact point, use by many force laws.
void integrateBeforeForceComputation (double time, double timeStep)
This is part of integrate routine for objects with infinite mass.
void integrateAfterForceComputation (double time, double timeStep)
This is part of the integration routine for objects with infinite mass.
virtual Mdouble getInvMass () const
virtual Mdouble getCurvature (const Vec3D &labFixedCoordinates) const
virtual bool isFaceContact (const Vec3D &normal) const
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Private Attributes
Vec3D normal_
Outward normal vector, does not have to be a unit vector.
Mdouble factor_
Mdouble position_
position n*x=p
Mdouble holeRadius_
Additional Inherited Members
Static Public Member Functions inherited from BaseWall
static void addToVTK (const std::vector< Vec3D > &points, VTKContainer &vtk)
Takes the points provided and adds a triangle strip connecting these points to the vtk container.
Detailed Description
Deprecated:
Use AxisymmetricIntersectionOfWalls instead.
Constructor & Destructor Documentation
InfiniteWallWithHole() [1/3]
InfiniteWallWithHole::InfiniteWallWithHole ()
default constructor
         : BaseWall()
 {
     factor_ = std::numeric_limits<double>::quiet_NaN();
     position_ = std::numeric_limits<double>::quiet_NaN();
     holeRadius_ = std::numeric_limits<double>::quiet_NaN();
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"InfiniteWall () finished"<<std::endl;
 #endif
 }
References factor_, holeRadius_, and position_.
Referenced by copy().
InfiniteWallWithHole() [2/3]
InfiniteWallWithHole::InfiniteWallWithHole (Vec3D normal, Mdouble position, Mdouble holeRadius)
         : BaseWall()
 {
     set(normal, position, holeRadius);
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"InfiniteWallWithHole(Vec3D normal, Mdouble position, Mdouble holeRadius) finished"<<std::endl;
 #endif
 }
References WallFunction::normal(), and set().
InfiniteWallWithHole() [3/3]
InfiniteWallWithHole::InfiniteWallWithHole (const InfiniteWallWithHole & p)
         : BaseWall(p)
 {
     normal_ = p.normal_;
     position_ = p.position_;
     factor_ = p.factor_;
     holeRadius_ = p.holeRadius_;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"InfiniteWall (const InfiniteWall &p) finished"<<std::endl;
 #endif
 }
References factor_, holeRadius_, normal_, p, and position_.
Member Function Documentation
copy()
InfiniteWallWithHole * InfiniteWallWithHole::copy () const override virtual
Wall copy method. It calls the copy contrustor of this Wall, usefull for polymorfism.
Implements BaseWall.
 {
     return new InfiniteWallWithHole(*this);
 }
References InfiniteWallWithHole().
getDistanceAndNormal()
bool InfiniteWallWithHole::getDistanceAndNormal (const BaseParticle & P, Mdouble & distance, Vec3D & normal_return) const override virtual
Since this function should be called before calculating any Particle-Wall interactions, it can also be used to set the normal vector in case of curved walls.
Implements BaseWall.
 {
     double wallDistance = getWallDistance(P.getPosition());
     if (wallDistance >= P.getRadius())
         return false;
     double holeDistance = getHoleDistance(P.getPosition());
     if (holeDistance >= P.getRadius())
         return false;
     if (wallDistance > 0 && holeDistance > 0)
     {
         distance = sqrt(pow(wallDistance, 2) + pow(holeDistance, 2));
         Vec3D ContactPoint;
         double alpha = atan2(P.getPosition().Y, P.getPosition().X);
         ContactPoint.X = holeRadius_ * cos(alpha);
         ContactPoint.Y = holeRadius_ * sin(alpha);
         ContactPoint.Z = position_;
         //std::cout<<"ContactPoint="<<ContactPoint<<" Particle position="<<P.getPosition()<<std::endl;
         normal_return = ContactPoint - P.getPosition();
         normal_return /= normal_return.getLength();
         //std::cout<<"Corner collision normal="<<normal_return<<std::endl;
         return true;
     }
     else if (wallDistance > holeDistance)
     {
         distance = wallDistance;
         normal_return = normal_;
         //std::cout<<"Wall collision normal="<<normal_return<<std::endl;
         return true;
     }
     else
     {
         distance = holeDistance;
         normal_return.X = P.getPosition().X / (holeRadius_ - holeDistance);
         normal_return.Y = P.getPosition().Y / (holeRadius_ - holeDistance);
         normal_return.Z = 0;
         //std::cout<<"Hole collision normal="<<normal_return<<std::endl;
         return true;
     }
 }
References alpha, atan2(), cos(), getHoleDistance(), Vec3D::getLength(), getWallDistance(), holeRadius_, normal_, Global_Physical_Variables::P, position_, Eigen::bfloat16_impl::pow(), sin(), sqrt(), Vec3D::X, Vec3D::Y, and Vec3D::Z.
getHoleDistance()
Mdouble InfiniteWallWithHole::getHoleDistance (const Vec3D & position) const
 {
     return holeRadius_ - sqrt(pow(position.X, 2) + pow(position.Y, 2));
 }
References holeRadius_, Eigen::bfloat16_impl::pow(), sqrt(), Vec3D::X, and Vec3D::Y.
Referenced by getDistanceAndNormal().
getName()
std::string InfiniteWallWithHole::getName () const override virtual
Returns the name of the object.
Implements BaseObject.
 {
     return "InfiniteWallWithHole";
 }
getNormal()
Vec3D InfiniteWallWithHole::getNormal ()
access function for normal
 {
     return normal_;
 }
References normal_.
getPosition()
Mdouble InfiniteWallWithHole::getPosition ()
access function for position
 {
     return position_;
 }
References position_.
getWallDistance()
Mdouble InfiniteWallWithHole::getWallDistance (const Vec3D & position) const
Returns the distance of the wall to the particle.
 {
     return position_ - Vec3D::dot(position, normal_);
 }
References Vec3D::dot(), normal_, and position_.
Referenced by getDistanceAndNormal().
move_time()
void InfiniteWallWithHole::move_time (Mdouble dt)
     \brief Allows the wall to be moved to a new position (also orthogonal to the normal), and setting the velocity
     note: I commented this function out as it does not add new functionality (instead, BaseInteractable::move(velocity*dt) can be used),
     and it hides the virtual function BaseInteractable::move. If this is really needed, please add it again. \author weinhartt
    &zwj;/
void move(Vec3D velocity, Mdouble dt);
/*!
   \brief Allows the wall to be moved with time
Todo:
TW: generalize the move function for all walls Allows the wall to be moved with time
 {
     position_ += Vec3D::dot(getVelocity(), normal_) * dt;
 }
References Vec3D::dot(), BaseInteractable::getVelocity(), normal_, and position_.
moveTo()
void InfiniteWallWithHole::moveTo (Mdouble position)
Allows the wall to be moved to a new position.
 {
     position_ = position * factor_;
 }
References factor_, and position_.
oldRead()
void InfiniteWallWithHole::oldRead (std::istream & is)
reads wall
 {
     std::string dummy;
     Vec3D velocity;
     is >> dummy >> normal_ >> dummy >> position_ >> dummy >> velocity;
     setVelocity(velocity);
 }
References normal_, position_, BaseInteractable::setVelocity(), oomph::Global_string_for_annotation::string(), and Jeffery_Solution::velocity().
read()
void InfiniteWallWithHole::read (std::istream & is) override virtual
reads wall
Reimplemented from BaseWall.
 {
     BaseWall::read(is);
     std::string dummy;
     is >> dummy >> normal_
        >> dummy >> factor_
        >> dummy >> position_
        >> dummy >> holeRadius_;
 }
References factor_, holeRadius_, normal_, position_, BaseWall::read(), and oomph::Global_string_for_annotation::string().
set()
void InfiniteWallWithHole::set (Vec3D normal, Mdouble position, Mdouble holeRadius)
Defines a standard wall, given an outward normal vector s. t. normal*x=position.
Defines a standard wall, given an outward normal vector s. t. normal*x=position
Todo:
Since InfiniteWall:set is deprecated, should we deprecate this format as well (and similar formats in other walls)?
Author
weinhartt
 {
     //factor is used to set n to unit length
     factor_ = 1. / sqrt(Vec3D::dot(normal, normal));
     normal_ = normal * factor_;
     position_ = position * factor_;
     holeRadius_ = holeRadius;
 }
References Vec3D::dot(), factor_, holeRadius_, WallFunction::normal(), normal_, position_, and sqrt().
Referenced by InfiniteWallWithHole(), CoilSelfTest::setupInitialConditions(), and FullRestartTest::setupInitialConditions().
write()
void InfiniteWallWithHole::write (std::ostream & os) const override virtual
outputs wall
Reimplemented from BaseWall.
 {
     BaseWall::write(os);
     os << " normal " << normal_
        << " factor " << factor_
        << " position " << position_
        << " holeRadius " << holeRadius_;
 }
References factor_, holeRadius_, normal_, position_, and BaseWall::write().
Member Data Documentation
factor_
Mdouble InfiniteWallWithHole::factor_ private
The factor that needs to be multiplied with normal_ to make it a unit vector.
Referenced by InfiniteWallWithHole(), moveTo(), read(), set(), and write().
holeRadius_
Mdouble InfiniteWallWithHole::holeRadius_ private
Referenced by getDistanceAndNormal(), getHoleDistance(), InfiniteWallWithHole(), read(), set(), and write().
normal_
Vec3D InfiniteWallWithHole::normal_ private
Outward normal vector, does not have to be a unit vector.
Referenced by getDistanceAndNormal(), getNormal(), getWallDistance(), InfiniteWallWithHole(), move_time(), oldRead(), read(), set(), and write().
position_
Mdouble InfiniteWallWithHole::position_ private
position n*x=p
Referenced by getDistanceAndNormal(), getPosition(), getWallDistance(), InfiniteWallWithHole(), move_time(), moveTo(), oldRead(), read(), set(), and write().
The documentation for this class was generated from the following files:
InfiniteWallWithHole.h
InfiniteWallWithHole.cc