MercuryDPM: Eigen::internal::pointer_based_stl_iterator< XprType > Class Template Reference
Eigen::internal::pointer_based_stl_iterator< XprType > Class Template Reference
#include <StlIterators.h>
Public Types
typedef Index difference_type
typedef XprType::Scalar value_type
typedef std::random_access_iterator_tag iterator_category
typedef std::conditional_t< bool(is_lvalue), value_type *, const value_type * > pointer
typedef std::conditional_t< bool(is_lvalue), value_type &, const value_type & > reference
Public Member Functions
pointer_based_stl_iterator () EIGEN_NO_THROW
pointer_based_stl_iterator (XprType &xpr, Index index) EIGEN_NO_THROW
pointer_based_stl_iterator (const non_const_iterator &other) EIGEN_NO_THROW
pointer_based_stl_iterator & operator= (const non_const_iterator &other) EIGEN_NO_THROW
reference operator* () const
reference operator[] (Index i) const
pointer operator-> () const
pointer_based_stl_iterator & operator++ ()
pointer_based_stl_iterator & operator-- ()
pointer_based_stl_iterator operator++ (int)
pointer_based_stl_iterator operator-- (int)
pointer_based_stl_iterator & operator+= (Index b)
pointer_based_stl_iterator & operator-= (Index b)
difference_type operator- (const pointer_based_stl_iterator &other) const
difference_type operator- (const other_iterator &other) const
bool operator== (const pointer_based_stl_iterator &other) const
bool operator!= (const pointer_based_stl_iterator &other) const
bool operator< (const pointer_based_stl_iterator &other) const
bool operator<= (const pointer_based_stl_iterator &other) const
bool operator> (const pointer_based_stl_iterator &other) const
bool operator>= (const pointer_based_stl_iterator &other) const
bool operator== (const other_iterator &other) const
bool operator!= (const other_iterator &other) const
bool operator< (const other_iterator &other) const
bool operator<= (const other_iterator &other) const
bool operator> (const other_iterator &other) const
bool operator>= (const other_iterator &other) const
Protected Attributes
pointer m_ptr
internal::variable_if_dynamic< Index, XprType::InnerStrideAtCompileTime > m_incr
Private Types
enum { is_lvalue = internal::is_lvalue<XprType>::value }
typedef pointer_based_stl_iterator< std::remove_const_t< XprType > > non_const_iterator
typedef pointer_based_stl_iterator< std::add_const_t< XprType > > const_iterator
typedef std::conditional_t< internal::is_const< XprType >::value, non_const_iterator, const_iterator > other_iterator
Friends
class pointer_based_stl_iterator< std::add_const_t< XprType > >
class pointer_based_stl_iterator< std::remove_const_t< XprType > >
pointer_based_stl_iterator operator+ (const pointer_based_stl_iterator &a, Index b)
pointer_based_stl_iterator operator- (const pointer_based_stl_iterator &a, Index b)
pointer_based_stl_iterator operator+ (Index a, const pointer_based_stl_iterator &b)
pointer_based_stl_iterator operator- (Index a, const pointer_based_stl_iterator &b)
Member Typedef Documentation
const_iterator
template<typename XprType > typedef pointer_based_stl_iterator<std::add_const_t<XprType> > Eigen::internal::pointer_based_stl_iterator< XprType >::const_iterator private
difference_type
template<typename XprType > typedef Index Eigen::internal::pointer_based_stl_iterator< XprType >::difference_type
iterator_category
template<typename XprType > typedef std::random_access_iterator_tag Eigen::internal::pointer_based_stl_iterator< XprType >::iterator_category
non_const_iterator
template<typename XprType > typedef pointer_based_stl_iterator<std::remove_const_t<XprType> > Eigen::internal::pointer_based_stl_iterator< XprType >::non_const_iterator private
other_iterator
template<typename XprType > typedef std::conditional_t<internal::is_const<XprType>::value, non_const_iterator, const_iterator> Eigen::internal::pointer_based_stl_iterator< XprType >::other_iterator private
pointer
template<typename XprType > typedef std::conditional_t<bool(is_lvalue), value_type*, const value_type*> Eigen::internal::pointer_based_stl_iterator< XprType >::pointer
reference
template<typename XprType > typedef std::conditional_t<bool(is_lvalue), value_type&, const value_type&> Eigen::internal::pointer_based_stl_iterator< XprType >::reference
value_type
template<typename XprType > typedef XprType::Scalar Eigen::internal::pointer_based_stl_iterator< XprType >::value_type
Member Enumeration Documentation
anonymous enum
template<typename XprType > anonymous enum private
Enumerator
is_lvalue
 { is_lvalue = internal::is_lvalue<XprType>::value };
Constructor & Destructor Documentation
pointer_based_stl_iterator() [1/3]
template<typename XprType > Eigen::internal::pointer_based_stl_iterator< XprType >::pointer_based_stl_iterator () inline
 : m_ptr(0) {}
pointer_based_stl_iterator() [2/3]
template<typename XprType > Eigen::internal::pointer_based_stl_iterator< XprType >::pointer_based_stl_iterator (XprType & xpr, Index index) inline
                                                                        : m_incr(xpr.innerStride()) {
     m_ptr = xpr.data() + index * m_incr.value();
   }
References Eigen::internal::pointer_based_stl_iterator< XprType >::m_incr, Eigen::internal::pointer_based_stl_iterator< XprType >::m_ptr, and Eigen::internal::variable_if_dynamic< T, Value >::value().
pointer_based_stl_iterator() [3/3]
template<typename XprType > Eigen::internal::pointer_based_stl_iterator< XprType >::pointer_based_stl_iterator (const non_const_iterator & other) inline
                                                                              : m_ptr(other.m_ptr),
                                                                                m_incr(other.m_incr) {}
Member Function Documentation
operator!=() [1/2]
template<typename XprType > bool Eigen::internal::pointer_based_stl_iterator< XprType >::operator!= (const other_iterator & other) const inline
 { return m_ptr != other.m_ptr; }
References Eigen::internal::pointer_based_stl_iterator< XprType >::m_ptr.
operator!=() [2/2]
template<typename XprType > bool Eigen::internal::pointer_based_stl_iterator< XprType >::operator!= (const pointer_based_stl_iterator< XprType > & other) const inline
 { return m_ptr != other.m_ptr; }
References Eigen::internal::pointer_based_stl_iterator< XprType >::m_ptr.
operator*()
template<typename XprType > reference Eigen::internal::pointer_based_stl_iterator< XprType >::operator* () const inline
 { return *m_ptr; }
References Eigen::internal::pointer_based_stl_iterator< XprType >::m_ptr.
operator++() [1/2]
template<typename XprType > pointer_based_stl_iterator& Eigen::internal::pointer_based_stl_iterator< XprType >::operator++ () inline
{
     m_ptr += m_incr.value();
     return *this;
   }
References Eigen::internal::pointer_based_stl_iterator< XprType >::m_incr, Eigen::internal::pointer_based_stl_iterator< XprType >::m_ptr, and Eigen::internal::variable_if_dynamic< T, Value >::value().
Referenced by Eigen::internal::pointer_based_stl_iterator< XprType >::operator++().
operator++() [2/2]
template<typename XprType > pointer_based_stl_iterator Eigen::internal::pointer_based_stl_iterator< XprType >::operator++ (int) inline
{
     pointer_based_stl_iterator prev(*this);
     operator++();
     return prev;
   }
References Eigen::internal::pointer_based_stl_iterator< XprType >::operator++().
operator+=()
template<typename XprType > pointer_based_stl_iterator& Eigen::internal::pointer_based_stl_iterator< XprType >::operator+= (Index b) inline
{
     m_ptr += b * m_incr.value();
     return *this;
   }
References b, Eigen::internal::pointer_based_stl_iterator< XprType >::m_incr, Eigen::internal::pointer_based_stl_iterator< XprType >::m_ptr, and Eigen::internal::variable_if_dynamic< T, Value >::value().
operator-() [1/2]
template<typename XprType > difference_type Eigen::internal::pointer_based_stl_iterator< XprType >::operator- (const other_iterator & other) const inline
 { return (m_ptr - other.m_ptr) / m_incr.value(); }
References Eigen::internal::pointer_based_stl_iterator< XprType >::m_incr, Eigen::internal::pointer_based_stl_iterator< XprType >::m_ptr, and Eigen::internal::variable_if_dynamic< T, Value >::value().
operator-() [2/2]
template<typename XprType > difference_type Eigen::internal::pointer_based_stl_iterator< XprType >::operator- (const pointer_based_stl_iterator< XprType > & other) const inline
{
     return (m_ptr - other.m_ptr) / m_incr.value();
   }
References Eigen::internal::pointer_based_stl_iterator< XprType >::m_incr, Eigen::internal::pointer_based_stl_iterator< XprType >::m_ptr, and Eigen::internal::variable_if_dynamic< T, Value >::value().
operator--() [1/2]
template<typename XprType > pointer_based_stl_iterator& Eigen::internal::pointer_based_stl_iterator< XprType >::operator-- () inline
{
     m_ptr -= m_incr.value();
     return *this;
   }
References Eigen::internal::pointer_based_stl_iterator< XprType >::m_incr, Eigen::internal::pointer_based_stl_iterator< XprType >::m_ptr, and Eigen::internal::variable_if_dynamic< T, Value >::value().
Referenced by Eigen::internal::pointer_based_stl_iterator< XprType >::operator--().
operator--() [2/2]
template<typename XprType > pointer_based_stl_iterator Eigen::internal::pointer_based_stl_iterator< XprType >::operator-- (int) inline
{
     pointer_based_stl_iterator prev(*this);
     operator--();
     return prev;
   }
References Eigen::internal::pointer_based_stl_iterator< XprType >::operator--().
operator-=()
template<typename XprType > pointer_based_stl_iterator& Eigen::internal::pointer_based_stl_iterator< XprType >::operator-= (Index b) inline
{
     m_ptr -= b * m_incr.value();
     return *this;
   }
References b, Eigen::internal::pointer_based_stl_iterator< XprType >::m_incr, Eigen::internal::pointer_based_stl_iterator< XprType >::m_ptr, and Eigen::internal::variable_if_dynamic< T, Value >::value().
operator->()
template<typename XprType > pointer Eigen::internal::pointer_based_stl_iterator< XprType >::operator-> () const inline
 { return m_ptr; }
References Eigen::internal::pointer_based_stl_iterator< XprType >::m_ptr.
operator<() [1/2]
template<typename XprType > bool Eigen::internal::pointer_based_stl_iterator< XprType >::operator< (const other_iterator & other) const inline
 { return m_ptr < other.m_ptr; }
References Eigen::internal::pointer_based_stl_iterator< XprType >::m_ptr.
operator<() [2/2]
template<typename XprType > bool Eigen::internal::pointer_based_stl_iterator< XprType >::operator< (const pointer_based_stl_iterator< XprType > & other) const inline
 { return m_ptr < other.m_ptr; }
References Eigen::internal::pointer_based_stl_iterator< XprType >::m_ptr.
operator<=() [1/2]
template<typename XprType > bool Eigen::internal::pointer_based_stl_iterator< XprType >::operator<= (const other_iterator & other) const inline
 { return m_ptr <= other.m_ptr; }
References Eigen::internal::pointer_based_stl_iterator< XprType >::m_ptr.
operator<=() [2/2]
template<typename XprType > bool Eigen::internal::pointer_based_stl_iterator< XprType >::operator<= (const pointer_based_stl_iterator< XprType > & other) const inline
 { return m_ptr <= other.m_ptr; }
References Eigen::internal::pointer_based_stl_iterator< XprType >::m_ptr.
operator=()
template<typename XprType > pointer_based_stl_iterator& Eigen::internal::pointer_based_stl_iterator< XprType >::operator= (const non_const_iterator & other) inline
{
     m_ptr = other.m_ptr;
     m_incr.setValue(other.m_incr);
     return *this;
   }
References Eigen::internal::pointer_based_stl_iterator< XprType >::m_incr, Eigen::internal::pointer_based_stl_iterator< XprType >::m_ptr, and Eigen::internal::variable_if_dynamic< T, Value >::setValue().
operator==() [1/2]
template<typename XprType > bool Eigen::internal::pointer_based_stl_iterator< XprType >::operator== (const other_iterator & other) const inline
 { return m_ptr == other.m_ptr; }
References Eigen::internal::pointer_based_stl_iterator< XprType >::m_ptr.
operator==() [2/2]
template<typename XprType > bool Eigen::internal::pointer_based_stl_iterator< XprType >::operator== (const pointer_based_stl_iterator< XprType > & other) const inline
 { return m_ptr == other.m_ptr; }
References Eigen::internal::pointer_based_stl_iterator< XprType >::m_ptr.
operator>() [1/2]
template<typename XprType > bool Eigen::internal::pointer_based_stl_iterator< XprType >::operator> (const other_iterator & other) const inline
 { return m_ptr > other.m_ptr; }
References Eigen::internal::pointer_based_stl_iterator< XprType >::m_ptr.
operator>() [2/2]
template<typename XprType > bool Eigen::internal::pointer_based_stl_iterator< XprType >::operator> (const pointer_based_stl_iterator< XprType > & other) const inline
 { return m_ptr > other.m_ptr; }
References Eigen::internal::pointer_based_stl_iterator< XprType >::m_ptr.
operator>=() [1/2]
template<typename XprType > bool Eigen::internal::pointer_based_stl_iterator< XprType >::operator>= (const other_iterator & other) const inline
 { return m_ptr >= other.m_ptr; }
References Eigen::internal::pointer_based_stl_iterator< XprType >::m_ptr.
operator>=() [2/2]
template<typename XprType > bool Eigen::internal::pointer_based_stl_iterator< XprType >::operator>= (const pointer_based_stl_iterator< XprType > & other) const inline
 { return m_ptr >= other.m_ptr; }
References Eigen::internal::pointer_based_stl_iterator< XprType >::m_ptr.
operator[]()
template<typename XprType > reference Eigen::internal::pointer_based_stl_iterator< XprType >::operator[] (Index i) const inline
 { return *(m_ptr + i * m_incr.value()); }
References i, Eigen::internal::pointer_based_stl_iterator< XprType >::m_incr, Eigen::internal::pointer_based_stl_iterator< XprType >::m_ptr, and Eigen::internal::variable_if_dynamic< T, Value >::value().
Friends And Related Function Documentation
operator+ [1/2]
template<typename XprType > pointer_based_stl_iterator operator+ (const pointer_based_stl_iterator< XprType > & a, Index b) friend
{
     pointer_based_stl_iterator ret(a);
     ret += b;
     return ret;
   }
operator+ [2/2]
template<typename XprType > pointer_based_stl_iterator operator+ (Index a, const pointer_based_stl_iterator< XprType > & b) friend
{
     pointer_based_stl_iterator ret(b);
     ret += a;
     return ret;
   }
operator- [1/2]
template<typename XprType > pointer_based_stl_iterator operator- (const pointer_based_stl_iterator< XprType > & a, Index b) friend
{
     pointer_based_stl_iterator ret(a);
     ret -= b;
     return ret;
   }
operator- [2/2]
template<typename XprType > pointer_based_stl_iterator operator- (Index a, const pointer_based_stl_iterator< XprType > & b) friend
{
     pointer_based_stl_iterator ret(b);
     ret -= a;
     return ret;
   }
pointer_based_stl_iterator< std::add_const_t< XprType > >
template<typename XprType > friend class pointer_based_stl_iterator< std::add_const_t< XprType > > friend
pointer_based_stl_iterator< std::remove_const_t< XprType > >
template<typename XprType > friend class pointer_based_stl_iterator< std::remove_const_t< XprType > > friend
Member Data Documentation
m_incr
template<typename XprType > internal::variable_if_dynamic<Index, XprType::InnerStrideAtCompileTime> Eigen::internal::pointer_based_stl_iterator< XprType >::m_incr protected
Referenced by Eigen::internal::pointer_based_stl_iterator< XprType >::operator++(), Eigen::internal::pointer_based_stl_iterator< XprType >::operator+=(), Eigen::internal::pointer_based_stl_iterator< XprType >::operator-(), Eigen::internal::pointer_based_stl_iterator< XprType >::operator--(), Eigen::internal::pointer_based_stl_iterator< XprType >::operator-=(), Eigen::internal::pointer_based_stl_iterator< XprType >::operator=(), Eigen::internal::pointer_based_stl_iterator< XprType >::operator[](), and Eigen::internal::pointer_based_stl_iterator< XprType >::pointer_based_stl_iterator().
m_ptr
template<typename XprType > pointer Eigen::internal::pointer_based_stl_iterator< XprType >::m_ptr protected
Referenced by Eigen::internal::pointer_based_stl_iterator< XprType >::operator!=(), Eigen::internal::pointer_based_stl_iterator< XprType >::operator*(), Eigen::internal::pointer_based_stl_iterator< XprType >::operator++(), Eigen::internal::pointer_based_stl_iterator< XprType >::operator+=(), Eigen::internal::pointer_based_stl_iterator< XprType >::operator-(), Eigen::internal::pointer_based_stl_iterator< XprType >::operator--(), Eigen::internal::pointer_based_stl_iterator< XprType >::operator-=(), Eigen::internal::pointer_based_stl_iterator< XprType >::operator->(), Eigen::internal::pointer_based_stl_iterator< XprType >::operator<(), Eigen::internal::pointer_based_stl_iterator< XprType >::operator<=(), Eigen::internal::pointer_based_stl_iterator< XprType >::operator=(), Eigen::internal::pointer_based_stl_iterator< XprType >::operator==(), Eigen::internal::pointer_based_stl_iterator< XprType >::operator>(), Eigen::internal::pointer_based_stl_iterator< XprType >::operator>=(), Eigen::internal::pointer_based_stl_iterator< XprType >::operator[](), and Eigen::internal::pointer_based_stl_iterator< XprType >::pointer_based_stl_iterator().
The documentation for this class was generated from the following file:
StlIterators.h