MercuryDPM: rayleigh_channel.cc File Reference
navier_stokes/rayleigh_channel/rayleigh_channel.cc File Reference
#include "generic.h"
#include "navier_stokes.h"
#include "meshes/rectangular_quadmesh.h"
Classes
class RayleighProblem< ELEMENT, TIMESTEPPER >
Namespaces
Global_Parameters
Namespace for global parameters.
ExactSoln
Namespace for exact solution.
Functions
void ExactSoln::get_exact_u (const double &t, const Vector< double > &x, Vector< double > &u)
Exact solution of the problem as a vector.
void ExactSoln::get_exact_u (const double &t, const double &y, double &u)
Exact solution of the problem as a scalar.
int main (int argc, char *argv[])
Driver code for Rayleigh channel problem.
Variables
unsigned Global_Parameters::Long_run_flag =1
Flag for long/short run: Default = perform long run.
unsigned Global_Parameters::Impulsive_start_flag =0
Function Documentation
main()
int main (int argc , char * argv[])
Driver code for Rayleigh channel problem.
Convert command line arguments (if any) into flags:
Flag for impulsive start
 {
  if (argc==1)
   {
    cout << "No command line arguments specified -- using defaults."
         << std::endl;
   }
  else if (argc==3)
   {
    cout << "Two command line arguments specified:" << std::endl;
    // Flag for long run
    Global_Parameters::Long_run_flag=atoi(argv[1]);
    Global_Parameters::Impulsive_start_flag=atoi(argv[2]);
   }
  else
   {
    std::string error_message =
     "Wrong number of command line arguments. Specify none or two.\n";
    error_message +=
     "Arg1: Long_run_flag [0/1]\n";
    error_message +=
     "Arg2: Impulsive_start_flag [0/1]\n";
    throw OomphLibError(error_message,
                        OOMPH_CURRENT_FUNCTION,
                        OOMPH_EXCEPTION_LOCATION);
   }
  cout << "Long run flag: "
       <<  Global_Parameters::Long_run_flag << std::endl;
  cout << "Impulsive start flag: "
       <<  Global_Parameters::Impulsive_start_flag << std::endl;
  // Set physical parameters:
  // Womersley number = Reynolds number (St = 1)
  Global_Parameters::ReSt = 10.0;
  Global_Parameters::Re = Global_Parameters::ReSt;
  //Horizontal length of domain
  double lx = 1.0;
  //Vertical length of domain
  double ly = 1.0;
  // Number of elements in x-direction
  unsigned nx=5;
  // Number of elements in y-direction
  unsigned ny=10;
  // Solve with Crouzeix-Raviart elements
  {
   // Set up doc info
   DocInfo doc_info;
   doc_info.number()=0;
   doc_info.set_directory("RESLT_CR");
   //Set up problem
   RayleighProblem<QCrouzeixRaviartElement<2>,BDF<2> > problem(nx,ny,lx,ly);
   // Run the unsteady simulation
   problem.unsteady_run(doc_info);
  }
  // Solve with Taylor-Hood elements
  {
   // Set up doc info
   DocInfo doc_info;
   doc_info.number()=0;
   doc_info.set_directory("RESLT_TH");
   //Set up problem
   RayleighProblem<QTaylorHoodElement<2>,BDF<2> > problem(nx,ny,lx,ly);
   // Run the unsteady simulation
   problem.unsteady_run(doc_info);
  }
 } // end of main
References Global_Parameters::Impulsive_start_flag, Global_Parameters::Long_run_flag, Mesh_Parameters::lx, Mesh_Parameters::ly, oomph::DocInfo::number(), Mesh_Parameters::nx, Mesh_Parameters::ny, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, problem, Global_Parameters::Re, Global_Parameters::ReSt, oomph::DocInfo::set_directory(), and oomph::Global_string_for_annotation::string().