MercuryDPM: airy_cantilever.cc File Reference
mpi/solvers/airy_cantilever.cc File Reference
#include "generic.h"
#include "solid.h"
#include "constitutive.h"
#include "meshes/rectangular_quadmesh.h"
Classes
class oomph::MySolidElement< ELEMENT >
Wrapper class for solid element to modify the output.
class oomph::FaceGeometry< MySolidElement< ELEMENT > >
FaceGeometry of wrapped element is the same as the underlying element.
class CantileverProblem< ELEMENT >
Problem class for the cantilever "beam" structure.
Namespaces
oomph
DRAIG: Change all instances of (SPATIAL_DIM) to (DIM-1).
Global_Physical_Variables
Global variables.
Functions
void Global_Physical_Variables::constant_pressure (const Vector< double > &xi, const Vector< double > &x, const Vector< double > &n, Vector< double > &traction)
Constant pressure load.
void Global_Physical_Variables::gravity (const double &time, const Vector< double > &xi, Vector< double > &b)
Non-dimensional gravity as body force.
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
Driver for cantilever beam loaded by surface traction and/or gravity
 {
 #ifdef OOMPH_HAS_MPI
  MPI_Helpers::init(argc,argv);
 #endif
  // switch off oomph_info output for all processors but rank 0
  if (MPI_Helpers::communicator_pt()->my_rank()!=0)
   {
    oomph_info.stream_pt() = &oomph_nullstream;
    OomphLibWarning::set_stream_pt(&oomph_nullstream);
    OomphLibError::set_stream_pt(&oomph_nullstream);
   }
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // check that there is one command line argument
  if (CommandLineArgs::Argc!=2)
   {
    oomph_info << "This driver required ONE command line argument" << std::endl;
    abort();
   }
  // get the preconditioning method
  int prec = atoi(CommandLineArgs::Argv[1]);
  switch (prec)
   {
   case 0:
    oomph_info << "Using BlockDiagonalPreconditioner" << std::endl;
    break;
   case 1:
    oomph_info << "Using BlockDiagonalPreconditioner with two level "
               << "parallelisation" << std::endl;
    break;
   case 2:
    oomph_info << "Using BlockTriangularPreconditioner (upper triangular)"
               << std::endl;
    break;
   case 3:
    oomph_info << "Using BlockTriangularPreconditioner (lower triangular)"
               << std::endl;
    break;
   default:
    oomph_info
     << "Command line argument must be 0, 1, or 2\n"
     << "0: BlockDiagonalPreconditioner\n"
     << "1: BlockDiagonalPreconditioner w/ two level parallelisation\n"
     << "2: BlockTriangularPreconditioner (upper triangular)\n"
     << "3: BlockTriangularPreconditioner (lower triangular)\n";
    abort();
    break;
   }
  // Set output directory
  DocInfo doc_info;
  doc_info.set_directory("RESLT");
  doc_info.number() = prec;
  // Create generalised Hookean constitutive equations
  Global_Physical_Variables::Constitutive_law_pt =
   new GeneralisedHookean(&Global_Physical_Variables::Nu,
                          &Global_Physical_Variables::E);
  //Set up the problem
  CantileverProblem<MySolidElement<RefineableQPVDElement<2,3> > > problem;
  // Initial values for parameter values
  Global_Physical_Variables::P=1.0e-5;
  Global_Physical_Variables::Gravity=0.0;
  // use trilinos gmres if available
 #ifdef OOMPH_HAS_TRILINOS
  TrilinosAztecOOSolver* solver_pt = new TrilinosAztecOOSolver;
  solver_pt->solver_type() = TrilinosAztecOOSolver::GMRES;
 #else
  GMRES<CRDoubleMatrix>* solver_pt = new GMRES<CRDoubleMatrix>;
 #endif
  problem.linear_solver_pt() = solver_pt;
  solver_pt->tolerance() = 10e-5;
  solver_pt->enable_doc_convergence_history();
  // Pointer to general purpose block preconditioner base class
  GeneralPurposeBlockPreconditioner<CRDoubleMatrix>* prec_pt = 0;
  // Choose the preconditioner type
  switch (prec)
   {
   case 0:
    // Standard Block Diagonal
    prec_pt = new BlockDiagonalPreconditioner<CRDoubleMatrix>;
    break;
   case 1:
    // Two Level Block Diagonal
    prec_pt = new BlockDiagonalPreconditioner<CRDoubleMatrix>;
    dynamic_cast<BlockDiagonalPreconditioner<CRDoubleMatrix>* >
     (prec_pt)->enable_two_level_parallelisation();
    break;
   case 2:
    // Block Upper Triangular
    prec_pt = new BlockTriangularPreconditioner<CRDoubleMatrix>;
    dynamic_cast<BlockTriangularPreconditioner<CRDoubleMatrix>* >
     (prec_pt)->upper_triangular();
    break;
   case 3:
    // Block Lower Triangular
    prec_pt = new BlockTriangularPreconditioner<CRDoubleMatrix>;
    dynamic_cast<BlockTriangularPreconditioner<CRDoubleMatrix>* >
     (prec_pt)->lower_triangular();
    break;
   }
 #ifdef OOMPH_HAS_HYPRE
  // Specify Hypre as the subsidiary block preconditioner
  prec_pt->set_subsidiary_preconditioner_function
    (Hypre_Subsidiary_Preconditioner_Helper::get_hypre_preconditioner);
 #endif
  // The preconditioner only requires the bulk mesh since its
  // elements are capable of classifying all degrees of freedom
  // prec_pt is a GeneralPurposeBlockPreconditioner, so we call the function
  // add_mesh(...).
  prec_pt->add_mesh(problem.solid_mesh_pt());
  // pass the preconditioner to the solver
  solver_pt->preconditioner_pt() = prec_pt;
  // solve the problem
  problem.newton_solve();
  // Doc solution
  problem.doc_solution(doc_info);
 #ifdef OOMPH_HAS_MPI
  MPI_Helpers::finalize();
 #endif
 } //end of main
References oomph::GeneralPurposeBlockPreconditioner< MATRIX >::add_mesh(), oomph::CommandLineArgs::Argc, oomph::CommandLineArgs::Argv, Global_Physical_Variables::Constitutive_law_pt, Global_Physical_Variables::E, e(), oomph::IterativeLinearSolver::enable_doc_convergence_history(), Global_Physical_Variables::Gravity, Global_Physical_Variables::Nu, oomph::DocInfo::number(), oomph::oomph_info, oomph::oomph_nullstream, Global_Physical_Variables::P, oomph::IterativeLinearSolver::preconditioner_pt(), problem, oomph::DocInfo::set_directory(), oomph::GeneralPurposeBlockPreconditioner< MATRIX >::set_subsidiary_preconditioner_function(), Flag_definition::setup(), oomph::TrilinosAztecOOSolver::solver_type(), oomph::OomphInfo::stream_pt(), and oomph::TrilinosAztecOOSolver::tolerance().