MercuryDPM: Eigen::internal::cephes_helper< Scalar > Struct Template Reference
Eigen::internal::cephes_helper< Scalar > Struct Template Reference
#include <SpecialFunctionsImpl.h>
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar machep ()
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar big ()
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar biginv ()
Member Function Documentation
big()
template<typename Scalar > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar Eigen::internal::cephes_helper< Scalar >::big () inline static
{
     eigen_assert(false && "big not supported for this type");
     return 0.0;
   }
References eigen_assert.
Referenced by Eigen::internal::igammac_cf_impl< Scalar, mode >::run().
biginv()
template<typename Scalar > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar Eigen::internal::cephes_helper< Scalar >::biginv () inline static
{
     eigen_assert(false && "biginv not supported for this type");
     return 0.0;
   }
References eigen_assert.
Referenced by Eigen::internal::igammac_cf_impl< Scalar, mode >::run().
machep()
template<typename Scalar > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar Eigen::internal::cephes_helper< Scalar >::machep () inline static
{
     eigen_assert(false && "machep not supported for this type");
     return 0.0;
   }
References eigen_assert.
Referenced by Eigen::internal::cephes_helper< float >::biginv(), Eigen::internal::igammac_cf_impl< Scalar, mode >::run(), Eigen::internal::igamma_series_impl< Scalar, mode >::run(), and Eigen::internal::zeta_impl< Scalar >::run().
The documentation for this struct was generated from the following file:
SpecialFunctionsImpl.h