MercuryDPM: HGrid Class Reference
HGrid Class Reference
In the HGrid class, here all information about the HGrid is stored.
#include <HGrid.h>
Public Member Functions
HGrid ()
Default constructor, it sets the parameters to some sensible defaults.
HGrid (unsigned int num_buckets, double cellOverSizeRatio, std::vector< double > &cellSizes)
Constructor: initialises parameters and allocates space for internal variables.
~HGrid ()
Destructor.
void insertParticleToHgrid (BaseParticle *obj)
Inserts the given BaseParticle in to the HGrid.
unsigned int computeHashBucketIndex (int x, int y, int z, unsigned int l) const
Computes hash bucket index in range [0, NUM_BUCKETS-1] for a 3D domain.
unsigned int computeHashBucketIndex (HGridCell hGridCell) const
Computes hash bucket index in range [0, NUM_BUCKETS-1] for a 3D domain.
unsigned int computeHashBucketIndex (int x, int y, unsigned int l) const
Computes hash bucket index in range [0, NUM_BUCKETS-1] for a 2D domain.
void clearBucketIsChecked ()
Sets all buckets to not-checked.
void clearFirstBaseParticleInBucket ()
For all buckets, it removes the pointer to the first BaseParticle in it, practically emptying the buckets.
void setFirstBaseParticleInBucket (unsigned int i, BaseParticle *p)
Sets the first particle in bucket i to be the given BaseParticle.
void setBucketIsChecked (unsigned int i)
Sets that the bucket with the given index is checked to true.
bool getBucketIsChecked (unsigned int i) const
Gets whether or not the bucket with index i is checked.
Mdouble getCellOverSizeRatio () const
Gets the maximum ratio of the cell to a particle it contains.
double getCellSize (unsigned int i) const
Gets the size of the cells at the given level.
const std::vector< double > & getCellSizes () const
Gets the sizes of the cells at all levels as a vector.
const BaseParticle * getFirstBaseParticleInBucket (unsigned int i) const
Gets the first BaseParticle in the given bucket, const version.
BaseParticle * getFirstBaseParticleInBucket (unsigned int i)
Gets the first BaseParticle in the given bucket.
double getInvCellSize (unsigned int i) const
Gets 1/cellSize for the cells on level i.
const std::vector< double > & getInvCellSizes () const
Gets all the inverse cell sizes (1/cellSize) for all levels as a vector.
bool getNeedsRebuilding () const
Gets whether or not the grid needs to be rebuilt before something else is done with it.
unsigned int getNumberOfBuckets () const
Gets the number of buckets of this HGrid.
unsigned long getNumberOfLevels () const
Gets the number of levels of this HGrid.
int getOccupiedLevelsMask () const
Gets the integer that represents which levels are occupied.
void info () const
Displays the member variables of the hGrid object. This function is intended for debugging the hGrid, therefore the variables are displayed next to the variable names instead of putting it in a user-friendly format.
Private Attributes
bool needsRebuilding_
Flag sets if the HGrid needs to be rebuilt.
unsigned int numberOfBuckets_
The number of buckets in the current HGrid.
Mdouble cellOverSizeRatio_
The maximum ratio between the size of the cell and the size of a particle it contains.
int occupiedLevelsMask_
Marks if there are particles at certain levels.
std::vector< double > cellSizes_
The sizes of the cells in the different grids.
std::vector< double > invCellSizes_
The inverse sizes of the cells in the different grids, where the inverse is defined as 1/cellSizes_.
std::vector< BaseParticle * > firstBaseParticleInBucket_
Stores a pointer to first element in hash bucket b.
std::vector< bool > bucketIsChecked_
BucketIsChecked stores if hash bucket b is checked already; initially all false.
Detailed Description
In the HGrid class, here all information about the HGrid is stored.
In particular, the hashing the grid is done in this class, the cell sizes of the different levels are stored, it is stored whether or not there are BaseParticle on each level and there is a flag to see if the HGrid needs to be rebuilt.
Constructor & Destructor Documentation
HGrid() [1/2]
HGrid::HGrid ()
Default constructor, it sets the parameters to some sensible defaults.
 {
     needsRebuilding_ = true;
     numberOfBuckets_ = 10;
     cellOverSizeRatio_ = 1.0;
     occupiedLevelsMask_ = 0;
     logger(DEBUG, "HGrid::HGrid() finished");
 }
References cellOverSizeRatio_, DEBUG, logger, needsRebuilding_, numberOfBuckets_, and occupiedLevelsMask_.
HGrid() [2/2]
HGrid::HGrid (unsigned int num_buckets, double cellOverSizeRatio, std::vector< double > & cellSizes)
Constructor: initialises parameters and allocates space for internal variables.
Parameters
[in] num_buckets The number of buckets that are used by this HGrid.
[in] cellOverSizeRatio The maximum ratio between the size of the cell over the size of the particle.
[in] cellSizes The sizes of the cells we want to set.
Constructor: initialises parameters and allocates space for internal variables.
 {
     needsRebuilding_ = false;
     numberOfBuckets_ = num_buckets;
     cellOverSizeRatio_ = cellOverSizeRatio;
     occupiedLevelsMask_ = 0;
     firstBaseParticleInBucket_.resize(numberOfBuckets_, nullptr);
     bucketIsChecked_.resize(numberOfBuckets_, false);
     //std::cout<<"Creating HGrid "<<cellSizes.size()<<" levels:"<<std::endl;
     for (double cellSize : cellSizes)
     {
         //std::cout<<"Level="<<i<<" size="<<cellSizes[i]<<std::endl;
         cellSizes_.push_back(cellSize);
         invCellSizes_.push_back(1.0 / cellSize);
     }
     logger(DEBUG, "HGrid::HGrid(unsigned int, double, vector<double>&) constructor finished.");
     /*  std::cout << "HGrid::HGrid(" << num_buckets << ", " << cellOverSizeRatio << ", [";
         for (auto p: cellSizes) std::cout << p << " ";
         std::cout << "]) finished" << std::endl;*/
 }
References bucketIsChecked_, cellOverSizeRatio_, cellSizes_, DEBUG, firstBaseParticleInBucket_, invCellSizes_, logger, needsRebuilding_, numberOfBuckets_, and occupiedLevelsMask_.
~HGrid()
HGrid::~HGrid ()
Destructor.
 {
     logger(DEBUG, "HGrid::~HGrid() destructor finished");
 }
References DEBUG, and logger.
Member Function Documentation
clearBucketIsChecked()
void HGrid::clearBucketIsChecked ()
Sets all buckets to not-checked.
 {
     std::fill(bucketIsChecked_.begin(), bucketIsChecked_.end(), false);
 }
References bucketIsChecked_.
Referenced by MercuryBase::hGridActionsBeforeTimeStep().
clearFirstBaseParticleInBucket()
void HGrid::clearFirstBaseParticleInBucket ()
For all buckets, it removes the pointer to the first BaseParticle in it, practically emptying the buckets.
 {
     std::fill(firstBaseParticleInBucket_.begin(), firstBaseParticleInBucket_.end(), nullptr);
 }
References firstBaseParticleInBucket_.
Referenced by MercuryBase::hGridActionsBeforeTimeStep().
computeHashBucketIndex() [1/3]
unsigned int HGrid::computeHashBucketIndex (HGridCell hGridCell) const inline
Computes hash bucket index in range [0, NUM_BUCKETS-1] for a 3D domain.
     {
         return computeHashBucketIndex(hGridCell.getHGridX(),
                                       hGridCell.getHGridY(),
                                       hGridCell.getHGridZ(),
                                       hGridCell.getHGridLevel());
     }
References computeHashBucketIndex(), HGridCell::getHGridLevel(), HGridCell::getHGridX(), HGridCell::getHGridY(), and HGridCell::getHGridZ().
computeHashBucketIndex() [2/3]
unsigned int HGrid::computeHashBucketIndex (int x, int y, int z, unsigned int l) const inline
Computes hash bucket index in range [0, NUM_BUCKETS-1] for a 3D domain.
Computes a hash from parameters, the result is in range [0, numberOfBuckets_-1]. Inline for performance reasons: this method is called VERY often.
Parameters
[in] x The coordinate of the cell in x direction for which the hash must be computed.
[in] y The coordinate of the cell in y direction for which the hash must be computed.
[in] z The coordinate of the cell in z direction for which the hash must be computed.
[in] l The level in the HGrid of the cell for which the hash must be computed.
Returns
The hash value for the given cell (x,y,z,l), which is in the range [0,numberOfBuckets_-1].
Todo:
consider moving to HGridCell, which might give better performance.
     {
         static const unsigned int h1 = 0x8da6b343u; // Large multiplicative constants;
         static const unsigned int h2 = 0xd8163841u; // here arbitrarily chosen primes
         static const unsigned int h3 = 0xcb1ab31fu;
         static const unsigned int h4 = 0x165667b1u;
         return (h1 * x + h2 * y + h3 * z + h4 * l) % numberOfBuckets_;
     }
References numberOfBuckets_, plotDoE::x, and y.
Referenced by computeHashBucketIndex(), DPM::computeLocalCGHGrid(), DPM::computeLocalVolumeFractionHGrid(), Mercury3D::computeWallForces(), Mercury3D::hGridFindContactsWithinTargetCell(), Mercury2D::hGridFindContactsWithinTargetCell(), Mercury3D::hGridFindContactsWithTargetCell(), Mercury2D::hGridFindContactsWithTargetCell(), Mercury2D::hGridFindParticleContacts(), Mercury3D::hGridFindParticleContacts(), Mercury3D::hGridFindParticlesWithTargetCell(), Mercury2D::hGridFindParticlesWithTargetCell(), Mercury3D::hGridHasContactsInTargetCell(), Mercury2D::hGridHasContactsInTargetCell(), Mercury2D::hGridRemoveParticle(), Mercury3D::hGridRemoveParticle(), Mercury2D::hGridUpdateParticle(), and Mercury3D::hGridUpdateParticle().
computeHashBucketIndex() [3/3]
unsigned int HGrid::computeHashBucketIndex (int x, int y, unsigned int l) const
Computes hash bucket index in range [0, NUM_BUCKETS-1] for a 2D domain.
Computes a hash from parameters, the result is in range [0, numberOfBuckets_-1].
Parameters
[in] x The coordinate of the cell in x direction for which the hash must be computed.
[in] y The coordinate of the cell in y direction for which the hash must be computed.
[in] l The level in the HGrid of the cell for which the hash must be computed.
Returns
The hash value for the given cell (x,y,l), which is in the range [0,numberOfBuckets_-1].
 {
     const unsigned int h1 = 0x8da6b343u; // Large multiplicative constants;
     const unsigned int h2 = 0xd8163841u; // here arbitrarily chosen primes
     const unsigned int h4 = 0x165667b1u;
     unsigned long int n = h1 * x + h2 * y + h4 * l;
     n = n % numberOfBuckets_;
     return static_cast<unsigned int>(n);
 }
References n, numberOfBuckets_, plotDoE::x, and y.
getBucketIsChecked()
bool HGrid::getBucketIsChecked (unsigned int i) const inline
Gets whether or not the bucket with index i is checked.
Parameters
[in] i The ordinal number of the bucket we want to know for whether or not it has been checked.
Returns
A boolean which is true if the bucket is checked and false otherwise.
     { return bucketIsChecked_[i]; }
References bucketIsChecked_, and i.
Referenced by Mercury3D::hGridFindContactsWithinTargetCell(), and Mercury2D::hGridFindContactsWithinTargetCell().
getCellOverSizeRatio()
Mdouble HGrid::getCellOverSizeRatio () const inline
Gets the maximum ratio of the cell to a particle it contains.
Returns
The ratio between the size of the smallest cell and the smallest BaseParticle.
     { return cellOverSizeRatio_; }
References cellOverSizeRatio_.
Referenced by MercuryBase::hGridNeedsRebuilding().
getCellSize()
double HGrid::getCellSize (unsigned int i) const inline
Gets the size of the cells at the given level.
Parameters
[in] i The level we want to know the cell size of.
Returns
The size of the cells at the given level.
     { return cellSizes_[i]; }
References cellSizes_, and i.
getCellSizes()
const std::vector<double>& HGrid::getCellSizes () const inline
Gets the sizes of the cells at all levels as a vector.
Returns
A vector with the sizes of the cells of different levels.
     { return cellSizes_; }
References cellSizes_.
Referenced by MercuryBase::hGridInfo(), and MercuryBase::hGridNeedsRebuilding().
getFirstBaseParticleInBucket() [1/2]
BaseParticle* HGrid::getFirstBaseParticleInBucket (unsigned int i) inline
Gets the first BaseParticle in the given bucket.
Parameters
[in] i The ordinal number of the bucket for which we want to get the first particle of.
Returns
A pointer to the (constant) BaseParticle which is the first Baseparticle in the given bucket.
     { return firstBaseParticleInBucket_[i]; }
References firstBaseParticleInBucket_, and i.
getFirstBaseParticleInBucket() [2/2]
const BaseParticle* HGrid::getFirstBaseParticleInBucket (unsigned int i) const inline
Gets the first BaseParticle in the given bucket, const version.
Parameters
[in] i The ordinal number of the bucket for which we want to get the first particle of.
Returns
A pointer to the (constant) BaseParticle which is the first Baseparticle in the given bucket.
     { return firstBaseParticleInBucket_[i]; }
References firstBaseParticleInBucket_, and i.
Referenced by DPM::computeLocalCGHGrid(), DPM::computeLocalVolumeFractionHGrid(), Mercury3D::computeWallForces(), Mercury3D::hGridFindContactsWithinTargetCell(), Mercury2D::hGridFindContactsWithinTargetCell(), Mercury3D::hGridFindContactsWithTargetCell(), Mercury2D::hGridFindContactsWithTargetCell(), Mercury2D::hGridFindParticleContacts(), Mercury3D::hGridFindParticleContacts(), Mercury3D::hGridFindParticlesWithTargetCell(), Mercury2D::hGridFindParticlesWithTargetCell(), Mercury3D::hGridHasContactsInTargetCell(), Mercury2D::hGridHasContactsInTargetCell(), Mercury3D::hGridRemoveParticle(), Mercury2D::hGridUpdateParticle(), and Mercury3D::hGridUpdateParticle().
getInvCellSize()
double HGrid::getInvCellSize (unsigned int i) const inline
Gets 1/cellSize for the cells on level i.
Parameters
[in] i The level we want to know the inverse cell size of.
Returns
The inverse size, i.e. 1/size, of the cells at the given level.
     {
         logger.assert_debug(i<invCellSizes_.size(),"Error in getInvCellSize %<%", i, invCellSizes_.size());
         return invCellSizes_[i];
     }
References i, invCellSizes_, and logger.
Referenced by Mercury2D::computeInternalForces(), Mercury3D::computeInternalForces(), DPM::computeLocalCGHGrid(), DPM::computeLocalVolumeFractionHGrid(), Mercury3D::computeWallForces(), Mercury2D::hGridFindParticleContacts(), Mercury3D::hGridFindParticleContacts(), Mercury2D::hGridGetInteractingParticleList(), Mercury3D::hGridGetInteractingParticleList(), Mercury2D::hGridHasParticleContacts(), Mercury3D::hGridHasParticleContacts(), Mercury2D::hGridUpdateParticle(), and Mercury3D::hGridUpdateParticle().
getInvCellSizes()
const std::vector<double>& HGrid::getInvCellSizes () const inline
Gets all the inverse cell sizes (1/cellSize) for all levels as a vector.
Returns
A vector with the inverse sizes (1/size) of the cells of different levels.
     { return invCellSizes_; }
References invCellSizes_.
getNeedsRebuilding()
bool HGrid::getNeedsRebuilding () const inline
Gets whether or not the grid needs to be rebuilt before something else is done with it.
Returns
A boolean which indicates whether or not the HGrid needs rebuilding.
     { return needsRebuilding_; }
References needsRebuilding_.
Referenced by MercuryBase::hGridNeedsRebuilding().
getNumberOfBuckets()
unsigned int HGrid::getNumberOfBuckets () const inline
Gets the number of buckets of this HGrid.
Returns
The number of buckets in this HGrid.
     { return numberOfBuckets_; }
References numberOfBuckets_.
Referenced by MercuryBase::hGridInfo(), and MercuryBase::hGridNeedsRebuilding().
getNumberOfLevels()
unsigned long HGrid::getNumberOfLevels () const inline
Gets the number of levels of this HGrid.
Returns
The number of levels in this HGrid.
     { return cellSizes_.size(); }
References cellSizes_.
Referenced by Mercury2D::computeInternalForces(), Mercury3D::computeInternalForces(), Mercury3D::computeWallForces(), Mercury2D::hGridFindParticleContacts(), Mercury3D::hGridFindParticleContacts(), Mercury2D::hGridGetInteractingParticleList(), Mercury3D::hGridGetInteractingParticleList(), Mercury2D::hGridHasParticleContacts(), and Mercury3D::hGridHasParticleContacts().
getOccupiedLevelsMask()
int HGrid::getOccupiedLevelsMask () const inline
Gets the integer that represents which levels are occupied.
Returns
The integer that represents the bit-vector that indicates which levels have at least one particle.
     { return occupiedLevelsMask_; }
References occupiedLevelsMask_.
Referenced by Mercury2D::computeInternalForces(), Mercury3D::computeInternalForces(), DPM::computeLocalCGHGrid(), DPM::computeLocalVolumeFractionHGrid(), Mercury3D::computeWallForces(), Mercury2D::hGridFindParticleContacts(), Mercury3D::hGridFindParticleContacts(), Mercury2D::hGridGetInteractingParticleList(), Mercury3D::hGridGetInteractingParticleList(), Mercury2D::hGridHasParticleContacts(), and Mercury3D::hGridHasParticleContacts().
info()
void HGrid::info () const
Displays the member variables of the hGrid object. This function is intended for debugging the hGrid, therefore the variables are displayed next to the variable names instead of putting it in a user-friendly format.
Todo:
use logger everywhere
 {
     logger(INFO, "  numberOfBuckets %\n", Flusher::NO_FLUSH, numberOfBuckets_);
     logger(INFO, "  cellOverSizeRatio %\n", Flusher::NO_FLUSH, cellOverSizeRatio_);
     logger(INFO, "  cellSizes\n", Flusher::NO_FLUSH);
     for (auto p: cellSizes_)
     {
         logger(INFO, " %\n", p, Flusher::NO_FLUSH);
     }
     logger(INFO, "");
 }
References cellOverSizeRatio_, cellSizes_, INFO, logger, NO_FLUSH, numberOfBuckets_, and p.
Referenced by EllipsoidsBouncingOnWallDemo::actionsAfterSolve(), EllipticalSuperQuadricCollision::actionsAfterSolve(), SphericalSuperQuadricCollision::actionsAfterSolve(), and VisualisationTest::actionsAfterSolve().
insertParticleToHgrid()
void HGrid::insertParticleToHgrid (BaseParticle * obj)
Inserts the given BaseParticle in to the HGrid.
Parameters
[in] obj A pointer to the BaseParticle we want to add to the HGrid.
Inserts the given BaseParticle into the HGrid, i.e. it sets up the particle grid properties and updates the level information on the grid. First find which level is big enough to fit the BaseParticle in, then add the BaseParticle to that level and set that level as occupied in the occupiedLevelsMask_.
Bug:
What happens if the particle is too big for the biggest cell? It just says that it needs to rebuild the HGrid, but the particle is not inserted and there seems to be no indication to the rest of the code that it has not been inserted. For now giving a warning, since code of users may rely on it that nothing happens.
 {
     if (!needsRebuilding_)
     {
         // Find lowest level where object fully fits inside cell, taking cellOverSizeRatio_ into account
         Mdouble diameter = obj->getMaxInteractionRadius() * 2.0;
         unsigned int level = 0;
         while (level <= (cellSizes_.size() - 1) && cellSizes_[level] <= diameter * cellOverSizeRatio_)
         {
             level++;
         }
         //Check if the size of the particle is larger than the required grid
         if (level >= cellSizes_.size())
         {
             logger(WARN, "WARNING: object (id = %, index = %) is larger (d = %, cellOverSizeRatio = %) than largest "
                          "grid cell (%) allows.",
                    obj->getId(), obj->getIndex(), diameter, cellOverSizeRatio_, cellSizes_.back());
             needsRebuilding_ = true;
             level--;
         }
         obj->setHGridLevel(level);
         // indicate level is in use - not levels with no particles no collision detection is performed
         this->occupiedLevelsMask_ |= (1 << level);
     }
     else
     {
         logger(WARN, "WARNING: the HGrid needs to be rebuilt before insertParticleToHgrid may be called!");
     }
 }
References cellOverSizeRatio_, cellSizes_, BaseObject::getId(), BaseObject::getIndex(), BaseParticle::getMaxInteractionRadius(), logger, needsRebuilding_, occupiedLevelsMask_, BaseParticle::setHGridLevel(), and WARN.
Referenced by MercuryBase::hGridInsertParticle().
setBucketIsChecked()
void HGrid::setBucketIsChecked (unsigned int i) inline
Sets that the bucket with the given index is checked to true.
Parameters
[in] i The ordinal number of the bucket we want to mark as checked.
     { bucketIsChecked_[i] = true; }
References bucketIsChecked_, and i.
Referenced by Mercury3D::hGridFindContactsWithinTargetCell(), and Mercury2D::hGridFindContactsWithinTargetCell().
setFirstBaseParticleInBucket()
void HGrid::setFirstBaseParticleInBucket (unsigned int i, BaseParticle * p) inline
Sets the first particle in bucket i to be the given BaseParticle.
Parameters
[in] i The ordinal number of the bucket we want to set the first BaseParticle for.
[in] p A pointer to the BaseParticle we want to place in the given bucket.
     { firstBaseParticleInBucket_[i] = p; }
References firstBaseParticleInBucket_, i, and p.
Referenced by Mercury2D::hGridRemoveParticle(), Mercury3D::hGridRemoveParticle(), Mercury2D::hGridUpdateParticle(), and Mercury3D::hGridUpdateParticle().
Member Data Documentation
bucketIsChecked_
std::vector<bool> HGrid::bucketIsChecked_ private
BucketIsChecked stores if hash bucket b is checked already; initially all false.
Referenced by clearBucketIsChecked(), getBucketIsChecked(), HGrid(), and setBucketIsChecked().
cellOverSizeRatio_
Mdouble HGrid::cellOverSizeRatio_ private
The maximum ratio between the size of the cell and the size of a particle it contains.
Referenced by getCellOverSizeRatio(), HGrid(), info(), and insertParticleToHgrid().
cellSizes_
std::vector<double> HGrid::cellSizes_ private
The sizes of the cells in the different grids.
The sizes of the cells in the different grids are saved in a vector of double. The smaller the index in the vector, the smaller the cells.
Referenced by getCellSize(), getCellSizes(), getNumberOfLevels(), HGrid(), info(), and insertParticleToHgrid().
firstBaseParticleInBucket_
std::vector<BaseParticle*> HGrid::firstBaseParticleInBucket_ private
Stores a pointer to first element in hash bucket b.
The pointer to the first element in a certain bucket, initially a nullptr, is the pointer to the first BaseParticle in the first cell in the bucket.
Referenced by clearFirstBaseParticleInBucket(), getFirstBaseParticleInBucket(), HGrid(), and setFirstBaseParticleInBucket().
invCellSizes_
std::vector<double> HGrid::invCellSizes_ private
The inverse sizes of the cells in the different grids, where the inverse is defined as 1/cellSizes_.
Referenced by getInvCellSize(), getInvCellSizes(), and HGrid().
needsRebuilding_
bool HGrid::needsRebuilding_ private
Flag sets if the HGrid needs to be rebuilt.
Referenced by getNeedsRebuilding(), HGrid(), and insertParticleToHgrid().
numberOfBuckets_
unsigned int HGrid::numberOfBuckets_ private
The number of buckets in the current HGrid.
The number of buckets is the number of possible "results" of the hash function for the grid.
Referenced by computeHashBucketIndex(), getNumberOfBuckets(), HGrid(), and info().
occupiedLevelsMask_
int HGrid::occupiedLevelsMask_ private
Marks if there are particles at certain levels.
The l-th bit of occupiedLevelsMask_ is 1 if level l is contains particles (Implies max 32 hgrid levels) and 0 if it contains none.
Referenced by getOccupiedLevelsMask(), HGrid(), and insertParticleToHgrid().
The documentation for this class was generated from the following files:
HGrid.h
HGrid.cc