MercuryDPM: rapidjson::BaseReaderHandler< Encoding > Struct Template Reference
rapidjson::BaseReaderHandler< Encoding > Struct Template Reference
Default implementation of Handler.
#include <reader.h>
Public Types
typedef Encoding::Ch Ch
Public Member Functions
void Default ()
void Null_ ()
void Bool_ (bool)
void Int (int)
void Uint (unsigned)
void Int64 (int64_t)
void Uint64 (uint64_t)
void Double (double)
void String (const Ch *, SizeType, bool)
void StartObject ()
void EndObject (SizeType)
void StartArray ()
void EndArray (SizeType)
Detailed Description
template<typename Encoding = UTF8<>>
struct rapidjson::BaseReaderHandler< Encoding >
Default implementation of Handler.
This can be used as base class of any reader handler.
Member Typedef Documentation
Ch
template<typename Encoding = UTF8<>> typedef Encoding::Ch rapidjson::BaseReaderHandler< Encoding >::Ch
Member Function Documentation
Bool_()
template<typename Encoding = UTF8<>> void rapidjson::BaseReaderHandler< Encoding >::Bool_ (bool) inline
 { Default(); }
References rapidjson::BaseReaderHandler< Encoding >::Default().
Default()
template<typename Encoding = UTF8<>> void rapidjson::BaseReaderHandler< Encoding >::Default () inline
 {}
Referenced by rapidjson::BaseReaderHandler< Encoding >::Bool_(), rapidjson::BaseReaderHandler< Encoding >::Double(), rapidjson::BaseReaderHandler< Encoding >::EndArray(), rapidjson::BaseReaderHandler< Encoding >::EndObject(), rapidjson::BaseReaderHandler< Encoding >::Int(), rapidjson::BaseReaderHandler< Encoding >::Int64(), rapidjson::BaseReaderHandler< Encoding >::Null_(), rapidjson::BaseReaderHandler< Encoding >::StartArray(), rapidjson::BaseReaderHandler< Encoding >::StartObject(), rapidjson::BaseReaderHandler< Encoding >::String(), rapidjson::BaseReaderHandler< Encoding >::Uint(), and rapidjson::BaseReaderHandler< Encoding >::Uint64().
Double()
template<typename Encoding = UTF8<>> void rapidjson::BaseReaderHandler< Encoding >::Double (double) inline
 { Default(); }
References rapidjson::BaseReaderHandler< Encoding >::Default().
EndArray()
template<typename Encoding = UTF8<>> void rapidjson::BaseReaderHandler< Encoding >::EndArray (SizeType) inline
 { Default(); }
References rapidjson::BaseReaderHandler< Encoding >::Default().
EndObject()
template<typename Encoding = UTF8<>> void rapidjson::BaseReaderHandler< Encoding >::EndObject (SizeType) inline
 { Default(); }
References rapidjson::BaseReaderHandler< Encoding >::Default().
Int()
template<typename Encoding = UTF8<>> void rapidjson::BaseReaderHandler< Encoding >::Int (int) inline
 { Default(); }
References rapidjson::BaseReaderHandler< Encoding >::Default().
Int64()
template<typename Encoding = UTF8<>> void rapidjson::BaseReaderHandler< Encoding >::Int64 (int64_t) inline
 { Default(); }
References rapidjson::BaseReaderHandler< Encoding >::Default().
Null_()
template<typename Encoding = UTF8<>> void rapidjson::BaseReaderHandler< Encoding >::Null_ () inline
 { Default(); }
References rapidjson::BaseReaderHandler< Encoding >::Default().
StartArray()
template<typename Encoding = UTF8<>> void rapidjson::BaseReaderHandler< Encoding >::StartArray () inline
 { Default(); }
References rapidjson::BaseReaderHandler< Encoding >::Default().
StartObject()
template<typename Encoding = UTF8<>> void rapidjson::BaseReaderHandler< Encoding >::StartObject () inline
 { Default(); }
References rapidjson::BaseReaderHandler< Encoding >::Default().
String()
template<typename Encoding = UTF8<>> void rapidjson::BaseReaderHandler< Encoding >::String (const Ch * , SizeType , bool) inline
 { Default(); }
References rapidjson::BaseReaderHandler< Encoding >::Default().
Uint()
template<typename Encoding = UTF8<>> void rapidjson::BaseReaderHandler< Encoding >::Uint (unsigned) inline
 { Default(); }
References rapidjson::BaseReaderHandler< Encoding >::Default().
Uint64()
template<typename Encoding = UTF8<>> void rapidjson::BaseReaderHandler< Encoding >::Uint64 (uint64_t) inline
 { Default(); }
References rapidjson::BaseReaderHandler< Encoding >::Default().
The documentation for this struct was generated from the following file:
reader.h