MercuryDPM: class_CwiseUnaryOp_ptrfun.cpp File Reference
class_CwiseUnaryOp_ptrfun.cpp File Reference
#include <Eigen/Core>
#include <iostream>
Functions
double ramp (double x)
int main (int, char **)
Function Documentation
main()
int main (int , char **)
                       {
   Eigen::Matrix4d m1 = Eigen::Matrix4d::Random();
   std::cout << m1 << std::endl << "becomes: " << std::endl << m1.unaryExpr(std::ptr_fun(ramp)) << std::endl;
   return 0;
 }
References m1, and ramp().
ramp()
double ramp (double x)
                       {
   if (x > 0)
     return x;
   else
     return 0;
 }
References plotDoE::x.
Referenced by main(), OscillatingWall::position(), and UnstructuredImmersedEllipseProblem< ELEMENT >::set_boundary_velocity().