MercuryDPM: EulerAngles< Scalar_ > Class Template Reference
EulerAngles< Scalar_ > Class Template Reference
Public Types
enum { Dim = 3 }
typedef Scalar_ Scalar
typedef Matrix< Scalar, 3, 3 > Matrix3
typedef Matrix< Scalar, 3, 1 > Vector3
typedef Quaternion< Scalar > QuaternionType
Public Member Functions
EulerAngles ()
EulerAngles (Scalar a0, Scalar a1, Scalar a2)
EulerAngles (const QuaternionType &q)
const Vector3 & coeffs () const
Vector3 & coeffs ()
EulerAngles & operator= (const QuaternionType &q)
EulerAngles & operator= (const Matrix3 &m)
Matrix3 toRotationMatrix (void) const
operator QuaternionType ()
Protected Attributes
Vector3 m_angles
Member Typedef Documentation
Matrix3
template<typename Scalar_ > typedef Matrix<Scalar, 3, 3> EulerAngles< Scalar_ >::Matrix3
QuaternionType
template<typename Scalar_ > typedef Quaternion<Scalar> EulerAngles< Scalar_ >::QuaternionType
Scalar
template<typename Scalar_ > typedef Scalar_ EulerAngles< Scalar_ >::Scalar
Vector3
template<typename Scalar_ > typedef Matrix<Scalar, 3, 1> EulerAngles< Scalar_ >::Vector3
Member Enumeration Documentation
anonymous enum
template<typename Scalar_ > anonymous enum
Enumerator
Dim
 { Dim = 3 };
Constructor & Destructor Documentation
EulerAngles() [1/3]
template<typename Scalar_ > EulerAngles< Scalar_ >::EulerAngles () inline
 {}
EulerAngles() [2/3]
template<typename Scalar_ > EulerAngles< Scalar_ >::EulerAngles (Scalar a0, Scalar a1, Scalar a2) inline
 : m_angles(a0, a1, a2) {}
EulerAngles() [3/3]
template<typename Scalar_ > EulerAngles< Scalar_ >::EulerAngles (const QuaternionType & q) inline
 { *this = q; }
References Eigen::numext::q.
Member Function Documentation
coeffs() [1/2]
template<typename Scalar_ > Vector3& EulerAngles< Scalar_ >::coeffs () inline
 { return m_angles; }
References Eigen::EulerAngles< Scalar_, _System >::m_angles.
coeffs() [2/2]
template<typename Scalar_ > const Vector3& EulerAngles< Scalar_ >::coeffs () const inline
 { return m_angles; }
References Eigen::EulerAngles< Scalar_, _System >::m_angles.
operator QuaternionType()
template<typename Scalar_ > EulerAngles< Scalar_ >::operator QuaternionType () inline
 { return QuaternionType(toRotationMatrix()); }
References Eigen::EulerAngles< Scalar_, _System >::toRotationMatrix().
operator=() [1/2]
template<typename Scalar_ > EulerAngles& EulerAngles< Scalar_ >::operator= (const Matrix3 & m) inline
{
     // mat =  cy*cz          -cy*sz           sy
     //        cz*sx*sy+cx*sz  cx*cz-sx*sy*sz -cy*sx
     //       -cx*cz*sy+sx*sz  cz*sx+cx*sy*sz  cx*cy
     m_angles.coeffRef(1) = std::asin(m.coeff(0, 2));
     m_angles.coeffRef(0) = std::atan2(-m.coeff(1, 2), m.coeff(2, 2));
     m_angles.coeffRef(2) = std::atan2(-m.coeff(0, 1), m.coeff(0, 0));
     return *this;
   }
References Eigen::bfloat16_impl::asin(), atan2(), Eigen::Matrix< Scalar_, Rows_, Cols_, Options_, MaxRows_, MaxCols_ >::coeffRef(), m, and Eigen::EulerAngles< Scalar_, _System >::m_angles.
operator=() [2/2]
template<typename Scalar_ > EulerAngles& EulerAngles< Scalar_ >::operator= (const QuaternionType & q) inline
{
     Matrix3 m = q.toRotationMatrix();
     return *this = m;
   }
References m, and Eigen::numext::q.
toRotationMatrix()
template<typename Scalar_ > Matrix3 EulerAngles< Scalar_ >::toRotationMatrix (void) const inline
{
     Vector3 c = m_angles.array().cos();
     Vector3 s = m_angles.array().sin();
     Matrix3 res;
     res << c.y() * c.z(), -c.y() * s.z(), s.y(), c.z() * s.x() * s.y() + c.x() * s.z(),
         c.x() * c.z() - s.x() * s.y() * s.z(), -c.y() * s.x(), -c.x() * c.z() * s.y() + s.x() * s.z(),
         c.z() * s.x() + c.x() * s.y() * s.z(), c.x() * c.y();
     return res;
   }
References calibrate::c, Eigen::EulerAngles< Scalar_, _System >::m_angles, res, and s.
Member Data Documentation
m_angles
template<typename Scalar_ > Vector3 EulerAngles< Scalar_ >::m_angles protected
The documentation for this class was generated from the following file:
quaternion_demo.cpp