MercuryDPM: pastix_support.cpp File Reference
pastix_support.cpp File Reference
#include "sparse_solver.h"
#include <Eigen/PaStiXSupport>
#include <unsupported/Eigen/SparseExtra>
Macros
#define EIGEN_NO_DEBUG_SMALL_PRODUCT_BLOCKS
Functions
template<typename T >
void test_pastix_T ()
template<typename T >
void test_pastix_T_LU ()
EIGEN_DECLARE_TEST (pastix_support)
Macro Definition Documentation
EIGEN_NO_DEBUG_SMALL_PRODUCT_BLOCKS
#define EIGEN_NO_DEBUG_SMALL_PRODUCT_BLOCKS
Function Documentation
EIGEN_DECLARE_TEST()
EIGEN_DECLARE_TEST (pastix_support)
{
   CALL_SUBTEST_1(test_pastix_T<float>());
   CALL_SUBTEST_2(test_pastix_T<double>());
   CALL_SUBTEST_3((test_pastix_T_LU<std::complex<float> >()));
   CALL_SUBTEST_4(test_pastix_T_LU<std::complex<double> >());
 }
References CALL_SUBTEST_1, CALL_SUBTEST_2, CALL_SUBTEST_3, CALL_SUBTEST_4, and test_pastix_T_LU().
test_pastix_T()
template<typename T > void test_pastix_T ()
                      {
   PastixLLT<SparseMatrix<T, ColMajor>, Eigen::Lower> pastix_llt_lower;
   PastixLDLT<SparseMatrix<T, ColMajor>, Eigen::Lower> pastix_ldlt_lower;
   PastixLLT<SparseMatrix<T, ColMajor>, Eigen::Upper> pastix_llt_upper;
   PastixLDLT<SparseMatrix<T, ColMajor>, Eigen::Upper> pastix_ldlt_upper;
   PastixLU<SparseMatrix<T, ColMajor> > pastix_lu;
   check_sparse_spd_solving(pastix_llt_lower);
   check_sparse_spd_solving(pastix_ldlt_lower);
   check_sparse_spd_solving(pastix_llt_upper);
   check_sparse_spd_solving(pastix_ldlt_upper);
   check_sparse_square_solving(pastix_lu);
   // Some compilation check:
   pastix_llt_lower.iparm();
   pastix_llt_lower.dparm();
   pastix_ldlt_lower.iparm();
   pastix_ldlt_lower.dparm();
   pastix_lu.iparm();
   pastix_lu.dparm();
 }
References check_sparse_spd_solving(), check_sparse_square_solving(), Eigen::PastixBase< Derived >::dparm(), Eigen::PastixBase< Derived >::iparm(), Eigen::Lower, and Eigen::Upper.
test_pastix_T_LU()
template<typename T > void test_pastix_T_LU ()
{
   PastixLU<SparseMatrix<T, ColMajor> > pastix_lu;
   check_sparse_square_solving(pastix_lu);
 }
References check_sparse_square_solving().
Referenced by EIGEN_DECLARE_TEST().