MercuryDPM: jacobi.cpp File Reference
jacobi.cpp File Reference
#include "main.h"
#include <Eigen/SVD>
Functions
template<typename MatrixType , typename JacobiScalar >
void jacobi (const MatrixType &m=MatrixType())
EIGEN_DECLARE_TEST (jacobi)
Function Documentation
EIGEN_DECLARE_TEST()
EIGEN_DECLARE_TEST (jacobi)
{
   for (int i = 0; i < g_repeat; i++) {
     CALL_SUBTEST_1((jacobi<Matrix3f, float>()));
     CALL_SUBTEST_2((jacobi<Matrix4d, double>()));
     CALL_SUBTEST_3((jacobi<Matrix4cf, float>()));
     CALL_SUBTEST_3((jacobi<Matrix4cf, std::complex<float> >()));
     CALL_SUBTEST_1((jacobi<Matrix<float, 3, 3, RowMajor>, float>()));
     CALL_SUBTEST_2((jacobi<Matrix<double, 4, 4, RowMajor>, double>()));
     CALL_SUBTEST_3((jacobi<Matrix<std::complex<float>, 4, 4, RowMajor>, float>()));
     CALL_SUBTEST_3((jacobi<Matrix<std::complex<float>, 4, 4, RowMajor>, std::complex<float> >()));
     int r = internal::random<int>(2, internal::random<int>(1, EIGEN_TEST_MAX_SIZE) / 2),
         c = internal::random<int>(2, internal::random<int>(1, EIGEN_TEST_MAX_SIZE) / 2);
     CALL_SUBTEST_4((jacobi<MatrixXf, float>(MatrixXf(r, c))));
     CALL_SUBTEST_5((jacobi<MatrixXcd, double>(MatrixXcd(r, c))));
     CALL_SUBTEST_5((jacobi<MatrixXcd, std::complex<double> >(MatrixXcd(r, c))));
     // complex<float> is really important to test as it is the only way to cover conjugation issues in certain unaligned
     // paths
     CALL_SUBTEST_6((jacobi<MatrixXcf, float>(MatrixXcf(r, c))));
     CALL_SUBTEST_6((jacobi<MatrixXcf, std::complex<float> >(MatrixXcf(r, c))));
     TEST_SET_BUT_UNUSED_VARIABLE(r);
     TEST_SET_BUT_UNUSED_VARIABLE(c);
   }
 }
References calibrate::c, CALL_SUBTEST_1, CALL_SUBTEST_2, CALL_SUBTEST_3, CALL_SUBTEST_4, CALL_SUBTEST_5, CALL_SUBTEST_6, EIGEN_TEST_MAX_SIZE, Eigen::g_repeat, i, jacobi(), UniformPSDSelfTest::r, Eigen::RowMajor, and TEST_SET_BUT_UNUSED_VARIABLE.
jacobi()
template<typename MatrixType , typename JacobiScalar > void jacobi (const MatrixType & m = MatrixType())
{
   Index rows = m.rows();
   Index cols = m.cols();
   enum { RowsAtCompileTime = MatrixType::RowsAtCompileTime, ColsAtCompileTime = MatrixType::ColsAtCompileTime };
   typedef Matrix<JacobiScalar, 2, 1> JacobiVector;
   const MatrixType a(MatrixType::Random(rows, cols));
   JacobiVector v = JacobiVector::Random().normalized();
   JacobiScalar c = v.x(), s = v.y();
   JacobiRotation<JacobiScalar> rot(c, s);
   {
     Index p = internal::random<Index>(0, rows - 1);
     Index q;
     do {
       q = internal::random<Index>(0, rows - 1);
     } while (q == p);
     MatrixType b = a;
     b.applyOnTheLeft(p, q, rot);
     VERIFY_IS_APPROX(b.row(p), c * a.row(p) + numext::conj(s) * a.row(q));
     VERIFY_IS_APPROX(b.row(q), -s * a.row(p) + numext::conj(c) * a.row(q));
   }
   {
     Index p = internal::random<Index>(0, cols - 1);
     Index q;
     do {
       q = internal::random<Index>(0, cols - 1);
     } while (q == p);
     MatrixType b = a;
     b.applyOnTheRight(p, q, rot);
     VERIFY_IS_APPROX(b.col(p), c * a.col(p) - s * a.col(q));
     VERIFY_IS_APPROX(b.col(q), numext::conj(s) * a.col(p) + numext::conj(c) * a.col(q));
   }
 }
References a, b, calibrate::c, cols, conj(), m, p, Eigen::numext::q, rot(), rows, s, v, and VERIFY_IS_APPROX.
Referenced by EIGEN_DECLARE_TEST().