MercuryDPM: eckerle4_functor Struct Reference
eckerle4_functor Struct Reference
Public Member Functions
eckerle4_functor (void)
int operator() (const VectorXd &b, VectorXd &fvec)
int df (const VectorXd &b, MatrixXd &fjac)
eckerle4_functor (void)
int operator() (const VectorXd &b, VectorXd &fvec)
int df (const VectorXd &b, MatrixXd &fjac)
Public Member Functions inherited from Eigen::DenseFunctor< double >
DenseFunctor ()
DenseFunctor (int inputs, int values)
int inputs () const
int values () const
Public Member Functions inherited from Functor< double >
Functor ()
Functor (int inputs, int values)
Functor ()
Functor (int inputs_, int values_)
int inputs () const
int inputs () const
int values () const
int values () const
Static Public Attributes
static const double x [35]
static const double y [35]
Additional Inherited Members
Public Types inherited from Eigen::DenseFunctor< double >
enum
typedef double Scalar
typedef Matrix< Scalar, InputsAtCompileTime, 1 > InputType
typedef Matrix< Scalar, ValuesAtCompileTime, 1 > ValueType
typedef Matrix< Scalar, ValuesAtCompileTime, InputsAtCompileTime > JacobianType
typedef ColPivHouseholderQR< JacobianType > QRSolver
Public Types inherited from Functor< double >
enum
enum
typedef double Scalar
typedef double Scalar
typedef Matrix< Scalar, InputsAtCompileTime, 1 > InputType
typedef Matrix< Scalar, InputsAtCompileTime, 1 > InputType
typedef Matrix< Scalar, ValuesAtCompileTime, 1 > ValueType
typedef Matrix< Scalar, ValuesAtCompileTime, 1 > ValueType
typedef Matrix< Scalar, ValuesAtCompileTime, InputsAtCompileTime > JacobianType
typedef Matrix< Scalar, ValuesAtCompileTime, InputsAtCompileTime > JacobianType
Public Attributes inherited from Eigen::DenseFunctor< double >
const int m_inputs
const int m_values
Public Attributes inherited from Functor< double >
const int m_inputs
int m_inputs
const int m_values
int m_values
Constructor & Destructor Documentation
eckerle4_functor() [1/2]
eckerle4_functor::eckerle4_functor (void) inline
 : DenseFunctor<double>(3, 35) {}
eckerle4_functor() [2/2]
eckerle4_functor::eckerle4_functor (void) inline
 : Functor<double>(3, 35) {}
Member Function Documentation
df() [1/2]
int eckerle4_functor::df (const VectorXd & b, MatrixXd & fjac) inline
{
     assert(b.size() == 3);
     assert(fjac.rows() == 35);
     assert(fjac.cols() == 3);
     for (int i = 0; i < 35; i++) {
       double b12 = b[1] * b[1];
       double e = exp(-0.5 * (x[i] - b[2]) * (x[i] - b[2]) / b12);
       fjac(i, 0) = e / b[1];
       fjac(i, 1) = ((x[i] - b[2]) * (x[i] - b[2]) / b12 - 1.) * b[0] * e / b12;
       fjac(i, 2) = (x[i] - b[2]) * e * b[0] / b[1] / b12;
     }
     return 0;
   }
References assert, b, e(), Eigen::bfloat16_impl::exp(), i, and x.
df() [2/2]
int eckerle4_functor::df (const VectorXd & b, MatrixXd & fjac) inline
{
     assert(b.size() == 3);
     assert(fjac.rows() == 35);
     assert(fjac.cols() == 3);
     for (int i = 0; i < 35; i++) {
       double b12 = b[1] * b[1];
       double e = exp(-0.5 * (x[i] - b[2]) * (x[i] - b[2]) / b12);
       fjac(i, 0) = e / b[1];
       fjac(i, 1) = ((x[i] - b[2]) * (x[i] - b[2]) / b12 - 1.) * b[0] * e / b12;
       fjac(i, 2) = (x[i] - b[2]) * e * b[0] / b[1] / b12;
     }
     return 0;
   }
References assert, b, e(), Eigen::bfloat16_impl::exp(), i, and x.
operator()() [1/2]
int eckerle4_functor::operator() (const VectorXd & b, VectorXd & fvec) inline
{
     assert(b.size() == 3);
     assert(fvec.size() == 35);
     for (int i = 0; i < 35; i++)
       fvec[i] = b[0] / b[1] * exp(-0.5 * (x[i] - b[2]) * (x[i] - b[2]) / (b[1] * b[1])) - y[i];
     return 0;
   }
References assert, b, Eigen::bfloat16_impl::exp(), i, x, and y.
operator()() [2/2]
int eckerle4_functor::operator() (const VectorXd & b, VectorXd & fvec) inline
{
     assert(b.size() == 3);
     assert(fvec.size() == 35);
     for (int i = 0; i < 35; i++)
       fvec[i] = b[0] / b[1] * exp(-0.5 * (x[i] - b[2]) * (x[i] - b[2]) / (b[1] * b[1])) - y[i];
     return 0;
   }
References assert, b, Eigen::bfloat16_impl::exp(), i, x, and y.
Member Data Documentation
x
const double eckerle4_functor::x static
Initial value:
= {400.0, 405.0, 410.0, 415.0, 420.0, 425.0, 430.0, 435.0, 436.5,
                                        438.0, 439.5, 441.0, 442.5, 444.0, 445.5, 447.0, 448.5, 450.0,
                                        451.5, 453.0, 454.5, 456.0, 457.5, 459.0, 460.5, 462.0, 463.5,
                                        465.0, 470.0, 475.0, 480.0, 485.0, 490.0, 495.0, 500.0}
Referenced by df(), and operator()().
y
const double eckerle4_functor::y static
Initial value:
= {0.0001575, 0.0001699, 0.0002350, 0.0003102, 0.0004917, 0.0008710, 0.0017418,
                                        0.0046400, 0.0065895, 0.0097302, 0.0149002, 0.0237310, 0.0401683, 0.0712559,
                                        0.1264458, 0.2073413, 0.2902366, 0.3445623, 0.3698049, 0.3668534, 0.3106727,
                                        0.2078154, 0.1164354, 0.0616764, 0.0337200, 0.0194023, 0.0117831, 0.0074357,
                                        0.0022732, 0.0008800, 0.0004579, 0.0002345, 0.0001586, 0.0001143, 0.0000710}
Referenced by operator()().
The documentation for this struct was generated from the following files:
levenberg_marquardt.cpp
NonLinearOptimization.cpp