MercuryDPM: Eigen::ComplexEigenSolver< MatrixType_ > Class Template Reference
Eigen::ComplexEigenSolver< MatrixType_ > Class Template Reference
Dense linear problems and decompositions » Reference » Eigenvalues_Module
Computes eigenvalues and eigenvectors of general complex matrices.
#include <ComplexEigenSolver.h>
Public Types
enum {
RowsAtCompileTime = MatrixType::RowsAtCompileTime , ColsAtCompileTime = MatrixType::ColsAtCompileTime , Options = internal::traits<MatrixType>::Options , MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime ,
MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime
}
typedef MatrixType_ MatrixType
Synonym for the template parameter MatrixType_.
typedef MatrixType::Scalar Scalar
Scalar type for matrices of type MatrixType.
typedef NumTraits< Scalar >::Real RealScalar
typedef Eigen::Index Index
typedef std::complex< RealScalar > ComplexScalar
Complex scalar type for MatrixType.
typedef Matrix< ComplexScalar, ColsAtCompileTime, 1, Options &(~RowMajor), MaxColsAtCompileTime, 1 > EigenvalueType
Type for vector of eigenvalues as returned by eigenvalues().
typedef Matrix< ComplexScalar, RowsAtCompileTime, ColsAtCompileTime, Options, MaxRowsAtCompileTime, MaxColsAtCompileTime > EigenvectorType
Type for matrix of eigenvectors as returned by eigenvectors().
Public Member Functions
ComplexEigenSolver ()
Default constructor.
ComplexEigenSolver (Index size)
Default Constructor with memory preallocation.
template<typename InputType >
ComplexEigenSolver (const EigenBase< InputType > &matrix, bool computeEigenvectors=true)
Constructor; computes eigendecomposition of given matrix.
const EigenvectorType & eigenvectors () const
Returns the eigenvectors of given matrix.
const EigenvalueType & eigenvalues () const
Returns the eigenvalues of given matrix.
template<typename InputType >
ComplexEigenSolver & compute (const EigenBase< InputType > &matrix, bool computeEigenvectors=true)
Computes eigendecomposition of given matrix.
ComputationInfo info () const
Reports whether previous computation was successful.
ComplexEigenSolver & setMaxIterations (Index maxIters)
Sets the maximum number of iterations allowed.
Index getMaxIterations ()
Returns the maximum number of iterations.
template<typename InputType >
ComplexEigenSolver< MatrixType > & compute (const EigenBase< InputType > &matrix, bool computeEigenvectors)
Protected Attributes
EigenvectorType m_eivec
EigenvalueType m_eivalues
ComplexSchur< MatrixType > m_schur
bool m_isInitialized
bool m_eigenvectorsOk
EigenvectorType m_matX
Private Member Functions
void doComputeEigenvectors (RealScalar matrixnorm)
void sortEigenvalues (bool computeEigenvectors)
Detailed Description
template<typename MatrixType_>
class Eigen::ComplexEigenSolver< MatrixType_ >
Computes eigenvalues and eigenvectors of general complex matrices.
\eigenvalues_module
Template Parameters
MatrixType_ the type of the matrix of which we are computing the eigendecomposition; this is expected to be an instantiation of the Matrix class template.
The eigenvalues and eigenvectors of a matrix \(A \) are scalars \(\lambda \) and vectors \(v \) such that \(Av = \lambda v \). If \(D \) is a diagonal matrix with the eigenvalues on the diagonal, and \(V \) is a matrix with the eigenvectors as its columns, then \(A V = V D \). The matrix \(V \) is almost always invertible, in which case we have \(A = V D V^{-1} \). This is called the eigendecomposition.
The main function in this class is compute(), which computes the eigenvalues and eigenvectors of a given function. The documentation for that function contains an example showing the main features of the class.
See also
class EigenSolver, class SelfAdjointEigenSolver
Member Typedef Documentation
ComplexScalar
template<typename MatrixType_ > typedef std::complex<RealScalar> Eigen::ComplexEigenSolver< MatrixType_ >::ComplexScalar
Complex scalar type for MatrixType.
This is std::complex<Scalar> if Scalar is real (e.g., float or double) and just Scalar if Scalar is complex.
EigenvalueType
template<typename MatrixType_ > typedef Matrix<ComplexScalar, ColsAtCompileTime, 1, Options & (~RowMajor), MaxColsAtCompileTime, 1> Eigen::ComplexEigenSolver< MatrixType_ >::EigenvalueType
Type for vector of eigenvalues as returned by eigenvalues().
This is a column vector with entries of type ComplexScalar. The length of the vector is the size of MatrixType.
EigenvectorType
template<typename MatrixType_ > typedef Matrix<ComplexScalar, RowsAtCompileTime, ColsAtCompileTime, Options, MaxRowsAtCompileTime, MaxColsAtCompileTime> Eigen::ComplexEigenSolver< MatrixType_ >::EigenvectorType
Type for matrix of eigenvectors as returned by eigenvectors().
This is a square matrix with entries of type ComplexScalar. The size is the same as the size of MatrixType.
Index
template<typename MatrixType_ > typedef Eigen::Index Eigen::ComplexEigenSolver< MatrixType_ >::Index
Deprecated:
since Eigen 3.3
MatrixType
template<typename MatrixType_ > typedef MatrixType_ Eigen::ComplexEigenSolver< MatrixType_ >::MatrixType
Synonym for the template parameter MatrixType_.
RealScalar
template<typename MatrixType_ > typedef NumTraits<Scalar>::Real Eigen::ComplexEigenSolver< MatrixType_ >::RealScalar
Scalar
template<typename MatrixType_ > typedef MatrixType::Scalar Eigen::ComplexEigenSolver< MatrixType_ >::Scalar
Scalar type for matrices of type MatrixType.
Member Enumeration Documentation
anonymous enum
template<typename MatrixType_ > anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
Options
MaxRowsAtCompileTime
MaxColsAtCompileTime
        {
     RowsAtCompileTime = MatrixType::RowsAtCompileTime,
     ColsAtCompileTime = MatrixType::ColsAtCompileTime,
     Options = internal::traits<MatrixType>::Options,
     MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime,
     MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime
   };
Constructor & Destructor Documentation
ComplexEigenSolver() [1/3]
template<typename MatrixType_ > Eigen::ComplexEigenSolver< MatrixType_ >::ComplexEigenSolver () inline
Default constructor.
The default constructor is useful in cases in which the user intends to perform decompositions via compute().
       : m_eivec(), m_eivalues(), m_schur(), m_isInitialized(false), m_eigenvectorsOk(false), m_matX() {}
ComplexEigenSolver() [2/3]
template<typename MatrixType_ > Eigen::ComplexEigenSolver< MatrixType_ >::ComplexEigenSolver (Index size) inline explicit
Default Constructor with memory preallocation.
Like the default constructor but with preallocation of the internal data according to the specified problem size.
See also
ComplexEigenSolver()
       : m_eivec(size, size),
         m_eivalues(size),
         m_schur(size),
         m_isInitialized(false),
         m_eigenvectorsOk(false),
         m_matX(size, size) {}
ComplexEigenSolver() [3/3]
template<typename MatrixType_ > template<typename InputType > Eigen::ComplexEigenSolver< MatrixType_ >::ComplexEigenSolver (const EigenBase< InputType > & matrix, bool computeEigenvectors = true) inline explicit
Constructor; computes eigendecomposition of given matrix.
Parameters
[in] matrix Square matrix whose eigendecomposition is to be computed.
[in] computeEigenvectors If true, both the eigenvectors and the eigenvalues are computed; if false, only the eigenvalues are computed.
This constructor calls compute() to compute the eigendecomposition.
       : m_eivec(matrix.rows(), matrix.cols()),
         m_eivalues(matrix.cols()),
         m_schur(matrix.rows()),
         m_isInitialized(false),
         m_eigenvectorsOk(false),
         m_matX(matrix.rows(), matrix.cols()) {
     compute(matrix.derived(), computeEigenvectors);
   }
References Eigen::ComplexEigenSolver< MatrixType_ >::compute(), and matrix().
Member Function Documentation
compute() [1/2]
template<typename MatrixType_ > template<typename InputType > ComplexEigenSolver<MatrixType>& Eigen::ComplexEigenSolver< MatrixType_ >::compute (const EigenBase< InputType > & matrix, bool computeEigenvectors)
{
   // this code is inspired from Jampack
   eigen_assert(matrix.cols() == matrix.rows());
   // Do a complex Schur decomposition, A = U T U^*
   // The eigenvalues are on the diagonal of T.
   m_schur.compute(matrix.derived(), computeEigenvectors);
   if (m_schur.info() == Success) {
     m_eivalues = m_schur.matrixT().diagonal();
     if (computeEigenvectors) doComputeEigenvectors(m_schur.matrixT().norm());
     sortEigenvalues(computeEigenvectors);
   }
   m_isInitialized = true;
   m_eigenvectorsOk = computeEigenvectors;
   return *this;
 }
References Eigen::ComplexSchur< MatrixType_ >::compute(), Eigen::ComplexEigenSolver< MatrixType_ >::doComputeEigenvectors(), eigen_assert, Eigen::ComplexSchur< MatrixType_ >::info(), Eigen::ComplexEigenSolver< MatrixType_ >::m_eigenvectorsOk, Eigen::ComplexEigenSolver< MatrixType_ >::m_eivalues, Eigen::ComplexEigenSolver< MatrixType_ >::m_isInitialized, Eigen::ComplexEigenSolver< MatrixType_ >::m_schur, matrix(), Eigen::ComplexSchur< MatrixType_ >::matrixT(), Eigen::ComplexEigenSolver< MatrixType_ >::sortEigenvalues(), and Eigen::Success.
compute() [2/2]
template<typename MatrixType_ > template<typename InputType > ComplexEigenSolver& Eigen::ComplexEigenSolver< MatrixType_ >::compute (const EigenBase< InputType > & matrix, bool computeEigenvectors = true)
Computes eigendecomposition of given matrix.
Parameters
[in] matrix Square matrix whose eigendecomposition is to be computed.
[in] computeEigenvectors If true, both the eigenvectors and the eigenvalues are computed; if false, only the eigenvalues are computed.
Returns
Reference to *this
This function computes the eigenvalues of the complex matrix matrix. The eigenvalues() function can be used to retrieve them. If computeEigenvectors is true, then the eigenvectors are also computed and can be retrieved by calling eigenvectors().
The matrix is first reduced to Schur form using the ComplexSchur class. The Schur decomposition is then used to compute the eigenvalues and eigenvectors.
The cost of the computation is dominated by the cost of the Schur decomposition, which is \(O(n^3) \) where \(n \) is the size of the matrix.
Example:
MatrixXcf A = MatrixXcf::Random(4, 4);
cout << "Here is a random 4x4 matrix, A:" << endl << A << endl << endl;
ComplexEigenSolver<MatrixXcf> ces;
ces.compute(A);
cout << "The eigenvalues of A are:" << endl << ces.eigenvalues() << endl;
cout << "The matrix of eigenvectors, V, is:" << endl << ces.eigenvectors() << endl << endl;
complex<float> lambda = ces.eigenvalues()[0];
cout << "Consider the first eigenvalue, lambda = " << lambda << endl;
VectorXcf v = ces.eigenvectors().col(0);
cout << "If v is the corresponding eigenvector, then lambda * v = " << endl << lambda * v << endl;
cout << "... and A * v = " << endl << A * v << endl << endl;
cout << "Finally, V * D * V^(-1) = " << endl
     << ces.eigenvectors() * ces.eigenvalues().asDiagonal() * ces.eigenvectors().inverse() << endl;
Output:
Referenced by Eigen::ComplexEigenSolver< MatrixType_ >::ComplexEigenSolver(), ctms_decompositions(), eigensolver(), and eigensolver_verify_assert().
doComputeEigenvectors()
template<typename MatrixType > void Eigen::ComplexEigenSolver< MatrixType >::doComputeEigenvectors (RealScalar matrixnorm) private
{
   const Index n = m_eivalues.size();
   matrixnorm = numext::maxi(matrixnorm, (std::numeric_limits<RealScalar>::min)());
   // Compute X such that T = X D X^(-1), where D is the diagonal of T.
   // The matrix X is unit triangular.
   m_matX = EigenvectorType::Zero(n, n);
   for (Index k = n - 1; k >= 0; k--) {
     m_matX.coeffRef(k, k) = ComplexScalar(1.0, 0.0);
     // Compute X(i,k) using the (i,k) entry of the equation X T = D X
     for (Index i = k - 1; i >= 0; i--) {
       m_matX.coeffRef(i, k) = -m_schur.matrixT().coeff(i, k);
       if (k - i - 1 > 0)
         m_matX.coeffRef(i, k) -=
             (m_schur.matrixT().row(i).segment(i + 1, k - i - 1) * m_matX.col(k).segment(i + 1, k - i - 1)).value();
       ComplexScalar z = m_schur.matrixT().coeff(i, i) - m_schur.matrixT().coeff(k, k);
       if (z == ComplexScalar(0)) {
         // If the i-th and k-th eigenvalue are equal, then z equals 0.
         // Use a small value instead, to prevent division by zero.
         numext::real_ref(z) = NumTraits<RealScalar>::epsilon() * matrixnorm;
       }
       m_matX.coeffRef(i, k) = m_matX.coeff(i, k) / z;
     }
   }
   // Compute V as V = U X; now A = U T U^* = U X D X^(-1) U^* = V D V^(-1)
   m_eivec.noalias() = m_schur.matrixU() * m_matX;
   // .. and normalize the eigenvectors
   for (Index k = 0; k < n; k++) {
     m_eivec.col(k).stableNormalize();
   }
 }
References Eigen::PlainObjectBase< Derived >::coeff(), Eigen::Matrix< Scalar_, Rows_, Cols_, Options_, MaxRows_, MaxCols_ >::coeffRef(), oomph::SarahBL::epsilon, i, k, Eigen::ComplexEigenSolver< MatrixType_ >::m_eivalues, Eigen::ComplexEigenSolver< MatrixType_ >::m_eivec, Eigen::ComplexEigenSolver< MatrixType_ >::m_matX, Eigen::ComplexEigenSolver< MatrixType_ >::m_schur, Eigen::ComplexSchur< MatrixType_ >::matrixT(), Eigen::ComplexSchur< MatrixType_ >::matrixU(), Eigen::numext::maxi(), min, n, Eigen::numext::real_ref(), Eigen::value, and oomph::PseudoSolidHelper::Zero.
Referenced by Eigen::ComplexEigenSolver< MatrixType_ >::compute().
eigenvalues()
template<typename MatrixType_ > const EigenvalueType& Eigen::ComplexEigenSolver< MatrixType_ >::eigenvalues () const inline
Returns the eigenvalues of given matrix.
Returns
A const reference to the column vector containing the eigenvalues.
Precondition
Either the constructor ComplexEigenSolver(const MatrixType& matrix, bool) or the member function compute(const MatrixType& matrix, bool) has been called before to compute the eigendecomposition of a matrix.
This function returns a column vector containing the eigenvalues. Eigenvalues are repeated according to their algebraic multiplicity, so there are as many eigenvalues as rows in the matrix. The eigenvalues are not sorted in any particular order.
Example:
MatrixXcf ones = MatrixXcf::Ones(3, 3);
ComplexEigenSolver<MatrixXcf> ces(ones, /* computeEigenvectors = */ false);
cout << "The eigenvalues of the 3x3 matrix of ones are:" << endl << ces.eigenvalues() << endl;
Output:
{
     eigen_assert(m_isInitialized && "ComplexEigenSolver is not initialized.");
     return m_eivalues;
   }
References eigen_assert, Eigen::ComplexEigenSolver< MatrixType_ >::m_eivalues, and Eigen::ComplexEigenSolver< MatrixType_ >::m_isInitialized.
Referenced by eigensolver(), eigensolver_verify_assert(), and Eigen::internal::eigenvalues_selector< Derived, IsComplex >::run().
eigenvectors()
template<typename MatrixType_ > const EigenvectorType& Eigen::ComplexEigenSolver< MatrixType_ >::eigenvectors () const inline
Returns the eigenvectors of given matrix.
Returns
A const reference to the matrix whose columns are the eigenvectors.
Precondition
Either the constructor ComplexEigenSolver(const MatrixType& matrix, bool) or the member function compute(const MatrixType& matrix, bool) has been called before to compute the eigendecomposition of a matrix, and computeEigenvectors was set to true (the default).
This function returns a matrix whose columns are the eigenvectors. Column \(k \) is an eigenvector corresponding to eigenvalue number \(k \) as returned by eigenvalues(). The eigenvectors are normalized to have (Euclidean) norm equal to one. The matrix returned by this function is the matrix \(V \) in the eigendecomposition \(A = V D V^{-1} \), if it exists.
Example:
MatrixXcf ones = MatrixXcf::Ones(3, 3);
ComplexEigenSolver<MatrixXcf> ces(ones);
cout << "The first eigenvector of the 3x3 matrix of ones is:" << endl << ces.eigenvectors().col(0) << endl;
Output:
{
     eigen_assert(m_isInitialized && "ComplexEigenSolver is not initialized.");
     eigen_assert(m_eigenvectorsOk && "The eigenvectors have not been computed together with the eigenvalues.");
     return m_eivec;
   }
References eigen_assert, Eigen::ComplexEigenSolver< MatrixType_ >::m_eigenvectorsOk, Eigen::ComplexEigenSolver< MatrixType_ >::m_eivec, and Eigen::ComplexEigenSolver< MatrixType_ >::m_isInitialized.
Referenced by eigensolver(), and eigensolver_verify_assert().
getMaxIterations()
template<typename MatrixType_ > Index Eigen::ComplexEigenSolver< MatrixType_ >::getMaxIterations () inline
Returns the maximum number of iterations.
 { return m_schur.getMaxIterations(); }
References Eigen::ComplexSchur< MatrixType_ >::getMaxIterations(), and Eigen::ComplexEigenSolver< MatrixType_ >::m_schur.
Referenced by eigensolver().
info()
template<typename MatrixType_ > ComputationInfo Eigen::ComplexEigenSolver< MatrixType_ >::info () const inline
Reports whether previous computation was successful.
Returns
Success if computation was successful, NoConvergence otherwise.
{
     eigen_assert(m_isInitialized && "ComplexEigenSolver is not initialized.");
     return m_schur.info();
   }
References eigen_assert, Eigen::ComplexSchur< MatrixType_ >::info(), Eigen::ComplexEigenSolver< MatrixType_ >::m_isInitialized, and Eigen::ComplexEigenSolver< MatrixType_ >::m_schur.
Referenced by eigensolver().
setMaxIterations()
template<typename MatrixType_ > ComplexEigenSolver& Eigen::ComplexEigenSolver< MatrixType_ >::setMaxIterations (Index maxIters) inline
Sets the maximum number of iterations allowed.
{
     m_schur.setMaxIterations(maxIters);
     return *this;
   }
References Eigen::ComplexEigenSolver< MatrixType_ >::m_schur, and Eigen::ComplexSchur< MatrixType_ >::setMaxIterations().
Referenced by eigensolver().
sortEigenvalues()
template<typename MatrixType > void Eigen::ComplexEigenSolver< MatrixType >::sortEigenvalues (bool computeEigenvectors) private
{
   const Index n = m_eivalues.size();
   for (Index i = 0; i < n; i++) {
     Index k;
     m_eivalues.cwiseAbs().tail(n - i).minCoeff(&k);
     if (k != 0) {
       k += i;
       std::swap(m_eivalues[k], m_eivalues[i]);
       if (computeEigenvectors) m_eivec.col(i).swap(m_eivec.col(k));
     }
   }
 }
References i, k, Eigen::ComplexEigenSolver< MatrixType_ >::m_eivalues, Eigen::ComplexEigenSolver< MatrixType_ >::m_eivec, n, Eigen::PlainObjectBase< Derived >::swap(), and swap().
Referenced by Eigen::ComplexEigenSolver< MatrixType_ >::compute().
Member Data Documentation
m_eigenvectorsOk
template<typename MatrixType_ > bool Eigen::ComplexEigenSolver< MatrixType_ >::m_eigenvectorsOk protected
Referenced by Eigen::ComplexEigenSolver< MatrixType_ >::compute(), and Eigen::ComplexEigenSolver< MatrixType_ >::eigenvectors().
m_eivalues
template<typename MatrixType_ > EigenvalueType Eigen::ComplexEigenSolver< MatrixType_ >::m_eivalues protected
Referenced by Eigen::ComplexEigenSolver< MatrixType_ >::compute(), Eigen::ComplexEigenSolver< MatrixType_ >::doComputeEigenvectors(), Eigen::ComplexEigenSolver< MatrixType_ >::eigenvalues(), and Eigen::ComplexEigenSolver< MatrixType_ >::sortEigenvalues().
m_eivec
template<typename MatrixType_ > EigenvectorType Eigen::ComplexEigenSolver< MatrixType_ >::m_eivec protected
Referenced by Eigen::ComplexEigenSolver< MatrixType_ >::doComputeEigenvectors(), Eigen::ComplexEigenSolver< MatrixType_ >::eigenvectors(), and Eigen::ComplexEigenSolver< MatrixType_ >::sortEigenvalues().
m_isInitialized
template<typename MatrixType_ > bool Eigen::ComplexEigenSolver< MatrixType_ >::m_isInitialized protected
Referenced by Eigen::ComplexEigenSolver< MatrixType_ >::compute(), Eigen::ComplexEigenSolver< MatrixType_ >::eigenvalues(), Eigen::ComplexEigenSolver< MatrixType_ >::eigenvectors(), and Eigen::ComplexEigenSolver< MatrixType_ >::info().
m_matX
template<typename MatrixType_ > EigenvectorType Eigen::ComplexEigenSolver< MatrixType_ >::m_matX protected
Referenced by Eigen::ComplexEigenSolver< MatrixType_ >::doComputeEigenvectors().
m_schur
template<typename MatrixType_ > ComplexSchur<MatrixType> Eigen::ComplexEigenSolver< MatrixType_ >::m_schur protected
Referenced by Eigen::ComplexEigenSolver< MatrixType_ >::compute(), Eigen::ComplexEigenSolver< MatrixType_ >::doComputeEigenvectors(), Eigen::ComplexEigenSolver< MatrixType_ >::getMaxIterations(), Eigen::ComplexEigenSolver< MatrixType_ >::info(), and Eigen::ComplexEigenSolver< MatrixType_ >::setMaxIterations().
The documentation for this class was generated from the following file:
ComplexEigenSolver.h