MercuryDPM: oomph::UnstructuredTwoDMeshGeometryBase Class Reference
oomph::UnstructuredTwoDMeshGeometryBase Class Reference
#include <unstructured_two_d_mesh_geometry_base.h>
Public Member Functions
UnstructuredTwoDMeshGeometryBase ()
Empty constructor.
UnstructuredTwoDMeshGeometryBase (const UnstructuredTwoDMeshGeometryBase &dummy)=delete
Broken copy constructor.
void operator= (const UnstructuredTwoDMeshGeometryBase &)=delete
Broken assignment operator.
~UnstructuredTwoDMeshGeometryBase ()
Empty destructor.
unsigned nregion ()
Return the number of regions specified by attributes.
unsigned nregion_element (const unsigned &i)
Return the number of elements in the i-th region.
FiniteElement * region_element_pt (const unsigned &i, const unsigned &e)
Return the e-th element in the i-th region.
unsigned nregion_attribute ()
Return the number of attributes used in the mesh.
double region_attribute (const unsigned &i)
Return the attribute associated with region i.
GeomObject * boundary_geom_object_pt (const unsigned &b)
std::map< unsigned, GeomObject * > & boundary_geom_object_pt ()
Return direct access to the geometric object storage.
std::map< unsigned, Vector< double > > & boundary_coordinate_limits ()
Vector< double > & boundary_coordinate_limits (const unsigned &b)
unsigned nboundary_element_in_region (const unsigned &b, const unsigned &r) const
Return the number of elements adjacent to boundary b in region r.
FiniteElement * boundary_element_in_region_pt (const unsigned &b, const unsigned &r, const unsigned &e) const
Return pointer to the e-th element adjacent to boundary b in region r.
int face_index_at_boundary_in_region (const unsigned &b, const unsigned &r, const unsigned &e) const
Return face index of the e-th element adjacent to boundary b in region r.
TriangleMeshPolyLine * boundary_polyline_pt (const unsigned &b)
std::map< unsigned, std::set< Node * > > & nodes_on_boundary_pt ()
const bool get_connected_vertex_number_on_destination_polyline (TriangleMeshPolyLine *dst_polyline_pt, Vector< double > &vertex_coordinates, unsigned &vertex_number)
void check_contiguousness_on_polylines_helper (Vector< TriangleMeshPolyLine * > &polylines_pt, unsigned &index)
void check_contiguousness_on_polylines_helper (Vector< TriangleMeshPolyLine * > &polylines_pt, unsigned &index_halo_start, unsigned &index_halo_end)
bool is_point_inside_polygon_helper (Vector< Vector< double >> polygon_vertices, Vector< double > point)
Helper function that checks if a given point is inside a polygon.
void enable_automatic_creation_of_vertices_on_boundaries ()
void disable_automatic_creation_of_vertices_on_boundaries ()
bool is_automatic_creation_of_vertices_on_boundaries_allowed ()
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b)
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b, std::ofstream &outfile)
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void setup_boundary_element_info ()
virtual void setup_boundary_element_info (std::ostream &outfile)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void node_update (const bool &update_all_solid_nodes=false)
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Static Public Attributes
static bool Suppress_warning_about_regions_and_boundaries
Public static flag to suppress warning; defaults to false.
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Protected Member Functions
void snap_nodes_onto_geometric_objects ()
void copy_connection_information (TriangleMeshCurveSection *input_curve_pt, TriangleMeshCurveSection *output_curve_pt)
void copy_connection_information_to_sub_polylines (TriangleMeshCurveSection *input_curve_pt, TriangleMeshCurveSection *output_curve_pt)
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Protected Attributes
bool Allow_automatic_creation_of_vertices_on_boundaries
std::map< unsigned, Vector< FiniteElement * > > Region_element_pt
Vector< double > Region_attribute
Vector of attributes associated with the elements in each region.
std::map< unsigned, GeomObject * > Boundary_geom_object_pt
Storage for the geometric objects associated with any boundaries.
std::map< unsigned, Vector< double > > Boundary_coordinate_limits
Vector< TriangleMeshPolygon * > Outer_boundary_pt
Polygon that defines outer boundaries.
Vector< TriangleMeshPolygon * > Internal_polygon_pt
Vector of polygons that define internal polygons.
Vector< TriangleMeshOpenCurve * > Internal_open_curve_pt
Vector of open polylines that define internal curves.
Vector< Vector< double > > Extra_holes_coordinates
Storage for extra coordinates for holes.
std::map< unsigned, Vector< double > > Regions_coordinates
std::map< unsigned, TriangleMeshCurveSection * > Boundary_curve_section_pt
Vector< std::map< unsigned, Vector< FiniteElement * > > > Boundary_region_element_pt
Storage for elements adjacent to a boundary in a particular region.
Vector< std::map< unsigned, Vector< int > > > Face_index_region_at_boundary
Storage for the face index adjacent to a boundary in a particular region.
std::map< unsigned, Vector< std::pair< double, double > > > Polygonal_vertex_arclength_info
std::map< unsigned, std::set< Node * > > Nodes_on_boundary_pt
std::set< TriangleMeshCurveSection * > Free_curve_section_pt
std::set< TriangleMeshPolygon * > Free_polygon_pt
std::set< TriangleMeshOpenCurve * > Free_open_curve_pt
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Detailed Description
Contains functions which define the geometry of the mesh, i.e. regions, boundaries, etc.
Constructor & Destructor Documentation
UnstructuredTwoDMeshGeometryBase() [1/2]
oomph::UnstructuredTwoDMeshGeometryBase::UnstructuredTwoDMeshGeometryBase () inline
Empty constructor.
 {}
UnstructuredTwoDMeshGeometryBase() [2/2]
oomph::UnstructuredTwoDMeshGeometryBase::UnstructuredTwoDMeshGeometryBase (const UnstructuredTwoDMeshGeometryBase & dummy) delete
Broken copy constructor.
~UnstructuredTwoDMeshGeometryBase()
oomph::UnstructuredTwoDMeshGeometryBase::~UnstructuredTwoDMeshGeometryBase () inline
Empty destructor.
 {}
Member Function Documentation
boundary_coordinate_limits() [1/2]
std::map<unsigned, Vector<double> >& oomph::UnstructuredTwoDMeshGeometryBase::boundary_coordinate_limits () inline
Return access to the vector of boundary coordinates associated with each geometric object
     {
       return Boundary_coordinate_limits;
     }
References Boundary_coordinate_limits.
Referenced by setup_boundary_coordinates().
boundary_coordinate_limits() [2/2]
Vector<double>& oomph::UnstructuredTwoDMeshGeometryBase::boundary_coordinate_limits (const unsigned & b) inline
Return access to the coordinate limits associated with the geometric object associated with boundary b
     {
       std::map<unsigned, Vector<double>>::iterator it;
       it = Boundary_coordinate_limits.find(b);
       if (it == Boundary_coordinate_limits.end())
       {
         throw OomphLibError(
           "No coordinate limits associated with this boundary\n",
           OOMPH_CURRENT_FUNCTION,
           OOMPH_EXCEPTION_LOCATION);
       }
       else
       {
         return (*it).second;
       }
     }
References b, Boundary_coordinate_limits, OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
boundary_element_in_region_pt()
FiniteElement* oomph::UnstructuredTwoDMeshGeometryBase::boundary_element_in_region_pt (const unsigned & b, const unsigned & r, const unsigned & e) const inline
Return pointer to the e-th element adjacent to boundary b in region r.
     {
       // Use a constant iterator here to keep function "const" overall
       std::map<unsigned, Vector<FiniteElement*>>::const_iterator it =
         Boundary_region_element_pt[b].find(r);
       if (it != Boundary_region_element_pt[b].end())
       {
         return (it->second)[e];
       }
       else
       {
         return 0;
       }
     }
References b, Boundary_region_element_pt, e(), Eigen::placeholders::end, and UniformPSDSelfTest::r.
Referenced by setup_boundary_coordinates().
boundary_geom_object_pt() [1/2]
std::map<unsigned, GeomObject*>& oomph::UnstructuredTwoDMeshGeometryBase::boundary_geom_object_pt () inline
Return direct access to the geometric object storage.
     {
       return Boundary_geom_object_pt;
     }
References Boundary_geom_object_pt.
Referenced by setup_boundary_coordinates(), and snap_nodes_onto_geometric_objects().
boundary_geom_object_pt() [2/2]
GeomObject* oomph::UnstructuredTwoDMeshGeometryBase::boundary_geom_object_pt (const unsigned & b) inline
Return the geometric object associated with the b-th boundary or null if the boundary has associated geometric object.
     {
       std::map<unsigned, GeomObject*>::iterator it;
       it = Boundary_geom_object_pt.find(b);
       if (it == Boundary_geom_object_pt.end())
       {
         return 0;
       }
       else
       {
         return (*it).second;
       }
     }
References b, and Boundary_geom_object_pt.
boundary_polyline_pt()
TriangleMeshPolyLine* oomph::UnstructuredTwoDMeshGeometryBase::boundary_polyline_pt (const unsigned & b) inline
Return pointer to the current polyline that describes the b-th mesh boundary
     {
       std::map<unsigned, TriangleMeshCurveSection*>::iterator it =
         Boundary_curve_section_pt.find(b);
       // Search for the polyline associated with the given boundary
       if (it != Boundary_curve_section_pt.end())
       {
         return dynamic_cast<TriangleMeshPolyLine*>(
           Boundary_curve_section_pt[b]);
       }
       // If the boundary was not established then return 0, or a null pointer
       return 0;
     }
References b, and Boundary_curve_section_pt.
Referenced by ContactProblem< ELEMENT >::actions_before_adapt().
check_contiguousness_on_polylines_helper() [1/2]
void oomph::UnstructuredTwoDMeshGeometryBase::check_contiguousness_on_polylines_helper (Vector< TriangleMeshPolyLine * > & polylines_pt, unsigned & index)
Sort the polylines coming from joining them. Check whether it is necessary to reverse them or not. Used when joining two curve polylines in order to create a polygon
check_contiguousness_on_polylines_helper() [2/2]
void oomph::UnstructuredTwoDMeshGeometryBase::check_contiguousness_on_polylines_helper (Vector< TriangleMeshPolyLine * > & polylines_pt, unsigned & index_halo_start, unsigned & index_halo_end)
Sort the polylines coming from joining them. Check whether it is necessary to reverse them or not. Used when joining polylines and they still do not create a polygon
copy_connection_information()
void oomph::UnstructuredTwoDMeshGeometryBase::copy_connection_information (TriangleMeshCurveSection * input_curve_pt, TriangleMeshCurveSection * output_curve_pt) protected
Helper function to copy the connection information from the input curve(polyline or curviline) to the output polyline
copy_connection_information_to_sub_polylines()
void oomph::UnstructuredTwoDMeshGeometryBase::copy_connection_information_to_sub_polylines (TriangleMeshCurveSection * input_curve_pt, TriangleMeshCurveSection * output_curve_pt) protected
Helper function to copy the connection information from the input curve(polyline or curviline) to the output sub-polyline
disable_automatic_creation_of_vertices_on_boundaries()
void oomph::UnstructuredTwoDMeshGeometryBase::disable_automatic_creation_of_vertices_on_boundaries () inline
Disables the creation of points (by Triangle) on the outer and internal boundaries
     {
       Allow_automatic_creation_of_vertices_on_boundaries = false;
     }
References Allow_automatic_creation_of_vertices_on_boundaries.
enable_automatic_creation_of_vertices_on_boundaries()
void oomph::UnstructuredTwoDMeshGeometryBase::enable_automatic_creation_of_vertices_on_boundaries () inline
Enables the creation of points (by Triangle) on the outer and internal boundaries
     {
       Allow_automatic_creation_of_vertices_on_boundaries = true;
     }
References Allow_automatic_creation_of_vertices_on_boundaries.
face_index_at_boundary_in_region()
int oomph::UnstructuredTwoDMeshGeometryBase::face_index_at_boundary_in_region (const unsigned & b, const unsigned & r, const unsigned & e) const inline
Return face index of the e-th element adjacent to boundary b in region r.
     {
       // Use a constant iterator here to keep function "const" overall
       std::map<unsigned, Vector<int>>::const_iterator it =
         Face_index_region_at_boundary[b].find(r);
       if (it != Face_index_region_at_boundary[b].end())
       {
         return (it->second)[e];
       }
       else
       {
         std::ostringstream error_message;
         error_message << "Face indices not set up for boundary " << b
                       << " in region " << r << "\n";
         error_message << "This probably means that the boundary is not "
                          "adjacent to region\n";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
     }
References b, e(), Eigen::placeholders::end, Face_index_region_at_boundary, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and UniformPSDSelfTest::r.
Referenced by setup_boundary_coordinates().
get_connected_vertex_number_on_destination_polyline()
const bool oomph::UnstructuredTwoDMeshGeometryBase::get_connected_vertex_number_on_destination_polyline (TriangleMeshPolyLine * dst_polyline_pt, Vector< double > & vertex_coordinates, unsigned & vertex_number)
Gets the vertex number on the destination polyline (used to create the connections among shared boundaries)
Gets the vertex number on the destination polyline (used / to create the connections among shared boundaries)
   {
     // The returning flag indicating that the vertex was found in the
     // destination boundary
     bool found_vertex_number = false;
     // Get the number of vertices in the destination polyline
     const unsigned n_vertices = dst_polyline_pt->nvertex();
     // Loop over the vertices and return the closest vertex
     // to the given vertex coordinates
     for (unsigned i = 0; i < n_vertices; i++)
     {
       // Get the i-vertex on the polyline
       Vector<double> current_vertex = dst_polyline_pt->vertex_coordinate(i);
       // Compute the distance to the input vertex
       double dist = (vertex_coordinates[0] - current_vertex[0]) *
                       (vertex_coordinates[0] - current_vertex[0]) +
                     (vertex_coordinates[1] - current_vertex[1]) *
                       (vertex_coordinates[1] - current_vertex[1]);
       dist = sqrt(dist);
       // Have we found the vertex?
       if (dist < ToleranceForVertexMismatchInPolygons::Tolerable_error)
       {
         // Set the vertex index
         vertex_number = i;
         // Set the flag to found
         found_vertex_number = true;
         // Break the serching
         break;
       }
     } // for (i < n_vertices)
     // Return if the connection was found
     return found_vertex_number;
   }
References i, oomph::TriangleMeshPolyLine::nvertex(), sqrt(), oomph::ToleranceForVertexMismatchInPolygons::Tolerable_error, and oomph::TriangleMeshPolyLine::vertex_coordinate().
is_automatic_creation_of_vertices_on_boundaries_allowed()
bool oomph::UnstructuredTwoDMeshGeometryBase::is_automatic_creation_of_vertices_on_boundaries_allowed () inline
Returns the status of the variable Allow_automatic_creation_of_vertices_on_boundaries
     {
       return Allow_automatic_creation_of_vertices_on_boundaries;
     }
References Allow_automatic_creation_of_vertices_on_boundaries.
is_point_inside_polygon_helper()
bool oomph::UnstructuredTwoDMeshGeometryBase::is_point_inside_polygon_helper (Vector< Vector< double >> polygon_vertices, Vector< double > point)
Helper function that checks if a given point is inside a polygon.
Helper function that checks if a given point is inside a polygon (a set of sorted vertices that connected create a polygon)
   {
     // Total number of vertices (the first and last vertex should be the same)
     const unsigned n_vertex = polygon_vertices.size();
     // Check if internal point is actually located in bounding polygon
     // Reference: http://paulbourke.net/geometry/insidepoly/
     // Counter for number of intersections
     unsigned intersect_counter = 0;
     // Get first vertex
     Vector<double> p1 = polygon_vertices[0];
     for (unsigned i = 1; i <= n_vertex; i++)
     {
       // Get second vertex by wrap-around
       Vector<double> p2 = polygon_vertices[i % n_vertex];
       if (point[1] > std::min(p1[1], p2[1]))
       {
         if (point[1] <= std::max(p1[1], p2[1]))
         {
           if (point[0] <= std::max(p1[0], p2[0]))
           {
             if (p1[1] != p2[1])
             {
               double xintersect =
                 (point[1] - p1[1]) * (p2[0] - p1[0]) / (p2[1] - p1[1]) + p1[0];
               if ((p1[0] == p2[0]) || (point[0] <= xintersect))
               {
                 intersect_counter++;
               }
             }
           }
         }
       }
       p1 = p2;
     }
     // Even number of intersections: outside
     if (intersect_counter % 2 == 0)
     {
       return false;
     }
     else
     {
       return true;
     }
   }
References i, max, min, and p1.
nboundary_element_in_region()
unsigned oomph::UnstructuredTwoDMeshGeometryBase::nboundary_element_in_region (const unsigned & b, const unsigned & r) const inline
Return the number of elements adjacent to boundary b in region r.
     {
       // Need to use a constant iterator here to keep the function "const".
       // Return an iterator to the appropriate entry, if we find it
       std::map<unsigned, Vector<FiniteElement*>>::const_iterator it =
         Boundary_region_element_pt[b].find(r);
       if (it != Boundary_region_element_pt[b].end())
       {
         return (it->second).size();
       }
       // Otherwise there are no elements adjacent to boundary b in the region r
       else
       {
         return 0;
       }
     }
References b, Boundary_region_element_pt, Eigen::placeholders::end, and UniformPSDSelfTest::r.
Referenced by setup_boundary_coordinates().
nodes_on_boundary_pt()
std::map<unsigned, std::set<Node*> >& oomph::UnstructuredTwoDMeshGeometryBase::nodes_on_boundary_pt () inline
Gets a pointer to a set with all the nodes related with a boundary
     {
       return Nodes_on_boundary_pt;
     }
References Nodes_on_boundary_pt.
nregion()
unsigned oomph::UnstructuredTwoDMeshGeometryBase::nregion () inline
Return the number of regions specified by attributes.
     {
       return Region_element_pt.size();
     }
References Region_element_pt.
Referenced by setup_boundary_coordinates().
nregion_attribute()
unsigned oomph::UnstructuredTwoDMeshGeometryBase::nregion_attribute () inline
Return the number of attributes used in the mesh.
     {
       return Region_attribute.size();
     }
References Region_attribute.
nregion_element()
unsigned oomph::UnstructuredTwoDMeshGeometryBase::nregion_element (const unsigned & i) inline
Return the number of elements in the i-th region.
     {
       // Create an iterator to iterate over Region_element_pt
       std::map<unsigned, Vector<FiniteElement*>>::iterator it;
       // Find the entry of Region_element_pt associated with the i-th region
       it = Region_element_pt.find(i);
       // If there is an entry associated with the i-th region
       if (it != Region_element_pt.end())
       {
         return (it->second).size();
       }
       else
       {
         return 0;
       }
     } // End of nregion_element
References i, and Region_element_pt.
operator=()
void oomph::UnstructuredTwoDMeshGeometryBase::operator= (const UnstructuredTwoDMeshGeometryBase &) delete
Broken assignment operator.
region_attribute()
double oomph::UnstructuredTwoDMeshGeometryBase::region_attribute (const unsigned & i) inline
Return the attribute associated with region i.
     {
       return Region_attribute[i];
     }
References i, and Region_attribute.
region_element_pt()
FiniteElement* oomph::UnstructuredTwoDMeshGeometryBase::region_element_pt (const unsigned & i, const unsigned & e) inline
Return the e-th element in the i-th region.
     {
       // Create an iterator to iterate over Region_element_pt
       std::map<unsigned, Vector<FiniteElement*>>::iterator it;
       // Find the entry of Region_element_pt associated with the i-th region
       it = Region_element_pt.find(i);
       // If there is an entry associated with the i-th region
       if (it != Region_element_pt.end())
       {
         // Return a pointer to the e-th element in the i-th region
         return (it->second)[e];
       }
       else
       {
         // Create a stringstream object
         std::stringstream error_message;
         // Create the error message
         error_message << "There are no regions associated with "
                       << "region ID " << i << ".";
         // Throw an error
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
     } // End of region_element_pt
References e(), i, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and Region_element_pt.
setup_boundary_coordinates() [1/2]
template<class ELEMENT > void oomph::UnstructuredTwoDMeshGeometryBase::setup_boundary_coordinates (const unsigned & b) inline
Setup boundary coordinate on boundary b. Boundary coordinate increases continously along polygonal boundary. It's zero at the lowest left node on the boundary.
     {
       // Dummy file
       std::ofstream some_file;
       setup_boundary_coordinates<ELEMENT>(b, some_file);
     }
References b.
setup_boundary_coordinates() [2/2]
template<class ELEMENT > void oomph::UnstructuredTwoDMeshGeometryBase::setup_boundary_coordinates (const unsigned & b, std::ofstream & outfile)
Setup boundary coordinate on boundary b. Doc Faces in outfile. Boundary coordinate increases continously along polygonal boundary. It's zero at the lowest left node on the boundary.
Setup boundary coordinate on boundary b. Doc Faces in outfile. Boundary coordinate increases continously along polygonal boundary. It's zero at the lexicographically smallest node on the boundary.
   {
     // Temporary storage for face elements
     Vector<FiniteElement*> face_el_pt;
     // Temporary storage for number of elements adjacent to the boundary
     unsigned nel = 0;
     // =================================================================
     // BEGIN: Get face elements from boundary elements
     // =================================================================
     // Temporary storage for elements adjacent to the boundary that have
     // an common edge (related with internal boundaries)
     unsigned n_repeated_ele = 0;
     unsigned n_regions = this->nregion();
 #ifdef OOMPH_HAS_MPI
     // map to associate the face element to the bulk element, this info.
     // is only necessary for the setup of boundary coordinates in a
     // distributed mesh when we need to extract the halo/haloed info.
     std::map<FiniteElement*, FiniteElement*> face_to_bulk_element_pt;
 #endif
     // Temporary storage for already done nodes
     Vector<std::pair<Node*, Node*>> done_nodes_pt;
     // If there is more than one region then only use boundary
     // coordinates from the bulk side (region 0)
     if (n_regions > 1)
     {
       for (unsigned rr = 0; rr < n_regions; rr++)
       {
         unsigned region_id = static_cast<unsigned>(this->Region_attribute[rr]);
 #ifdef PARANOID
         double diff =
           fabs(Region_attribute[rr] - static_cast<double>(static_cast<unsigned>(
                                         this->Region_attribute[rr])));
         if (diff > 0.0)
         {
           std::ostringstream error_message;
           error_message << "Region attributes should be unsigneds because we \n"
                         << "only use them to set region ids\n";
           throw OomphLibError(error_message.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
 #endif
         // Loop over all elements on boundaries in region rr
         unsigned nel_in_region =
           this->nboundary_element_in_region(b, region_id);
         unsigned nel_repeated_in_region = 0;
 #ifdef PARANOID
         if (!Suppress_warning_about_regions_and_boundaries)
         {
           if (nel_in_region == 0)
           {
             std::ostringstream warning_message;
             std::string output_string =
               "UnstructuredTwoDMeshGeometryBase::setup_boundary_coordinates()";
             warning_message
               << "There are no elements associated with boundary (" << b
               << ")\n"
               << "in region (" << region_id << "). This could happen because:\n"
               << "1) You did not specify boundaries with this boundary id.\n"
               << "---- Review carefully the indexing of your boundaries.\n"
               << "2) The boundary (" << b << ") is not associated with region ("
               << region_id << ").\n"
               << "---- The boundary does not touch the region.\n"
               << "You can suppress this warning by setting the static public "
                  "bool\n\n"
               << "   "
                  "UnstructuredTwoDMeshGeometryBase::Suppress_warning_about_"
                  "regions_and_boundaries\n\n"
               << "to true.\n";
             OomphLibWarning(
               warning_message.str(), output_string, OOMPH_EXCEPTION_LOCATION);
           }
         }
 #endif
         // Only bother to do anything else, if there are elements
         // associated with the boundary and the current region
         if (nel_in_region > 0)
         {
           // Flag that activates when a repeated face element is found,
           // possibly because we are dealing with an internal boundary
           bool repeated = false;
           // Loop over the bulk elements adjacent to boundary b
           for (unsigned e = 0; e < nel_in_region; e++)
           {
             // Get pointer to the bulk element that is adjacent to boundary b
             FiniteElement* bulk_elem_pt =
               this->boundary_element_in_region_pt(b, region_id, e);
 #ifdef OOMPH_HAS_MPI
             // In a distributed mesh only work with nonhalo elements
             if (this->is_mesh_distributed() && bulk_elem_pt->is_halo())
             {
               // Increase the number of repeated elements
               n_repeated_ele++;
               // Skip this element and go for the next one
               continue;
             }
 #endif
             // Find the index of the face of element e along boundary b
             int face_index =
               this->face_index_at_boundary_in_region(b, region_id, e);
             // Before adding the new element we need to be sure that
             // the edge that this element represent has not been
             // already added
             FiniteElement* tmp_ele_pt =
               new DummyFaceElement<ELEMENT>(bulk_elem_pt, face_index);
             const unsigned n_nodes = tmp_ele_pt->nnode();
             std::pair<Node*, Node*> tmp_pair = std::make_pair(
               tmp_ele_pt->node_pt(0), tmp_ele_pt->node_pt(n_nodes - 1));
             std::pair<Node*, Node*> tmp_pair_inverse = std::make_pair(
               tmp_ele_pt->node_pt(n_nodes - 1), tmp_ele_pt->node_pt(0));
             // Search for repeated nodes
             const unsigned n_done_nodes = done_nodes_pt.size();
             for (unsigned l = 0; l < n_done_nodes; l++)
             {
               if (tmp_pair == done_nodes_pt[l] ||
                   tmp_pair_inverse == done_nodes_pt[l])
               {
                 nel_repeated_in_region++;
                 repeated = true;
                 break;
               }
             }
             // Create new face element?
             if (!repeated)
             {
               // Add the pair of nodes (edge) to the node dones
               done_nodes_pt.push_back(tmp_pair);
 #ifdef OOMPH_HAS_MPI
               // If the mesh is distributed then create a map from the
               // temporary face element to the bulk element, further
               // info. will be extracted from the bulk element for setup
               // of boundary coordinates in a distributed mesh
               if (this->is_mesh_distributed())
               {
                 face_to_bulk_element_pt[tmp_ele_pt] = bulk_elem_pt;
               }
 #endif
               // Add the face element to the storage
               face_el_pt.push_back(tmp_ele_pt);
             }
             else
             {
               // Clean up
               delete tmp_ele_pt;
               tmp_ele_pt = 0;
             }
             // Re-start
             repeated = false;
             // Output faces?
             if (outfile.is_open())
             {
               face_el_pt[face_el_pt.size() - 1]->output(outfile);
             }
           } // for nel
           nel += nel_in_region;
           n_repeated_ele += nel_repeated_in_region;
         } // if (nel_in_region > 0)
       } // for (rr < n_regions)
     } // if (n_regions > 1)
     // Otherwise it's just the normal boundary functions
     else
     {
       // Loop over all elements on boundaries
       nel = this->nboundary_element(b);
 #ifdef PARANOID
       if (!Suppress_warning_about_regions_and_boundaries)
       {
         if (nel == 0)
         {
           std::ostringstream warning_message;
           std::string output_string =
             "UnstructuredTwoDMeshGeometryBase::setup_boundary_coordinates()";
           warning_message
             << "There are no elements associated with boundary (" << b << ").\n"
             << "This could happen because you did not specify boundaries with\n"
             << "this boundary id. Review carefully the indexing of your\n"
             << "boundaries.";
           OomphLibWarning(
             warning_message.str(), output_string, OOMPH_EXCEPTION_LOCATION);
         }
       }
 #endif
       // Only bother to do anything else, if there are elements
       if (nel > 0)
       {
         // Flag that activates when a repeated face element is found,
         // possibly because we are dealing with an internal boundary
         bool repeated = false;
         // Loop over the bulk elements adjacent to boundary b
         for (unsigned e = 0; e < nel; e++)
         {
           // Get pointer to the bulk element that is adjacent to boundary b
           FiniteElement* bulk_elem_pt = this->boundary_element_pt(b, e);
 #ifdef OOMPH_HAS_MPI
           // In a distributed mesh only work with nonhalo elements
           if (this->is_mesh_distributed() && bulk_elem_pt->is_halo())
           {
             // Increase the number of repeated elements
             n_repeated_ele++;
             // Skip this element and go for the next one
             continue;
           }
 #endif
           // Find the index of the face of element e along boundary b
           int face_index = this->face_index_at_boundary(b, e);
           // Before adding the new element we need to be sure that the
           // edge that this element represent has not been already added
           FiniteElement* tmp_ele_pt =
             new DummyFaceElement<ELEMENT>(bulk_elem_pt, face_index);
           const unsigned n_nodes = tmp_ele_pt->nnode();
           std::pair<Node*, Node*> tmp_pair = std::make_pair(
             tmp_ele_pt->node_pt(0), tmp_ele_pt->node_pt(n_nodes - 1));
           std::pair<Node*, Node*> tmp_pair_inverse = std::make_pair(
             tmp_ele_pt->node_pt(n_nodes - 1), tmp_ele_pt->node_pt(0));
           // Search for repeated nodes
           const unsigned n_done_nodes = done_nodes_pt.size();
           for (unsigned l = 0; l < n_done_nodes; l++)
           {
             if (tmp_pair == done_nodes_pt[l] ||
                 tmp_pair_inverse == done_nodes_pt[l])
             {
               n_repeated_ele++;
               repeated = true;
               break;
             }
           }
           // Create new face element
           if (!repeated)
           {
             // Add the pair of nodes (edge) to the node dones
             done_nodes_pt.push_back(tmp_pair);
 #ifdef OOMPH_HAS_MPI
             // Create a map from the temporary face element to the bulk
             // element, further info. will be extracted from the bulk
             // element for setup of boundary coordinates in a
             // distributed mesh
             if (this->is_mesh_distributed())
             {
               face_to_bulk_element_pt[tmp_ele_pt] = bulk_elem_pt;
             }
 #endif
             face_el_pt.push_back(tmp_ele_pt);
           }
           else
           {
             // Free the repeated bulk element!!
             delete tmp_ele_pt;
             tmp_ele_pt = 0;
           }
           // Re-start
           repeated = false;
           // Output faces?
           if (outfile.is_open())
           {
             face_el_pt[face_el_pt.size() - 1]->output(outfile);
           }
         } // for (e < nel)
       } // if (nel > 0)
     } // else if (n_regions > 1)
     // Do not consider the repeated elements
     nel -= n_repeated_ele;
 #ifdef PARANOID
     if (nel != face_el_pt.size())
     {
       std::ostringstream error_message;
       error_message
         << "The independent counting of face elements (" << nel << ") for "
         << "boundary (" << b << ") is different\n"
         << "from the real number of face elements in the container ("
         << face_el_pt.size() << ")\n";
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // =================================================================
     // END: Get face elements from boundary elements
     // =================================================================
     // Only bother to do anything else, if there are elements
     if (nel > 0)
     {
       // A flag vector to mark those face elements that are considered
       // as halo in the current processor
       std::vector<bool> is_halo_face_element(nel, false);
       // Count the total number of non halo face elements
       unsigned nnon_halo_face_elements = 0;
 #ifdef OOMPH_HAS_MPI
       // Only mark the face elements as halo if the mesh is marked as
       // distributed
       if (this->is_mesh_distributed())
       {
         for (unsigned ie = 0; ie < nel; ie++)
         {
           FiniteElement* face_ele_pt = face_el_pt[ie];
           // Get the bulk element
           FiniteElement* tmp_bulk_ele_pt = face_to_bulk_element_pt[face_ele_pt];
           // Check if the bulk element is halo
           if (!tmp_bulk_ele_pt->is_halo())
           {
             // Mark the face element as nonhalo
             is_halo_face_element[ie] = false;
             // Increase the counter for nonhalo elements
             nnon_halo_face_elements++;
           }
           else
           {
             // Mark the face element as halo
             is_halo_face_element[ie] = true;
           }
         } // for (ie < nel)
       } // if (this->is_mesh_distributed())
       else
       {
 #endif // OOMPH_HAS_MPI
         // If the mesh is not distributed then the number of non halo
         // elements is the same as the number of elements
         nnon_halo_face_elements = nel;
 #ifdef OOMPH_HAS_MPI
       } // else if (this->is_mesh_distributed())
 #endif
 #ifdef PARANOID
       // Get the total number of halo face elements
       const unsigned nhalo_face_element = nel - nnon_halo_face_elements;
       if (nhalo_face_element > 0)
       {
         std::ostringstream error_message;
         error_message
           << "There should not be halo face elements since they were not\n"
           << "considered when computing the face elements.\n"
           << "The number of found halo face elements is: ("
           << nhalo_face_element << ").\n\n";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // =================================================================
       // BEGIN: Sort face elements
       // =================================================================
       // The vector of lists to store the "segments" that compound the
       // boundaries (segments may appear only in a distributed mesh
       // because the boundary may have been split across multiple
       // processors)
       Vector<std::list<FiniteElement*>> segment_sorted_ele_pt;
       // Number of already sorted face elements (only nonhalo face
       // elements for a distributed mesh)
       unsigned nsorted_face_elements = 0;
       // Keep track of who's done (in a distributed mesh this apply to
       // nonhalo only)
       std::map<FiniteElement*, bool> done_el;
       // Keep track of which element is inverted (in distributed mesh
       // the elements may be inverted with respect to the segment they
       // belong)
       std::map<FiniteElement*, bool> is_inverted;
       // Iterate until all possible segments have been created. In a
       // non distributed mesh there is only one segment which defines
       // the complete boundary
       while (nsorted_face_elements < nnon_halo_face_elements)
       {
         // The sorted list of face elements (in a distributed mesh a
         // collection of continuous face elements define a segment)
         std::list<FiniteElement*> sorted_el_pt;
         FiniteElement* ele_face_pt = 0;
 #ifdef PARANOID
         // Select an initial element for the segment
         bool found_initial_face_element = false;
 #endif
         // Store the index of the initial face element
         unsigned iface = 0;
 #ifdef OOMPH_HAS_MPI
         if (this->is_mesh_distributed())
         {
           for (iface = 0; iface < nel; iface++)
           {
             // Only work with nonhalo face elements
             if (!is_halo_face_element[iface])
             {
               ele_face_pt = face_el_pt[iface];
               // If not done then take it as initial face element
               if (!done_el[ele_face_pt])
               {
 #ifdef PARANOID
                 // Set the flag to indicate the initial element was
                 // found
                 found_initial_face_element = true;
 #endif
                 // Increase the number of sorted face elements
                 nsorted_face_elements++;
                 // Set the index to the next face element
                 iface++;
                 // Add the face element in the container
                 sorted_el_pt.push_back(ele_face_pt);
                 // Mark as done
                 done_el[ele_face_pt] = true;
                 break;
               } // if (!done_el[ele_face_pt])
             } // if (!is_halo_face_element[iface])
           } // for (iface < nel)
         } // if (this->is_mesh_distributed())
         else
         {
 #endif // #ifdef OOMPH_HAS_MPI
           // When the mesh is not distributed just take the first
           // element and put it in the sorted list
           ele_face_pt = face_el_pt[0];
 #ifdef PARANOID
           // Set the flag to indicate the initial element was found
           found_initial_face_element = true;
 #endif
           // Increase the number of sorted face elements
           nsorted_face_elements++;
           // Set the index to the next face element
           iface = 1;
           // Add the face element in the container
           sorted_el_pt.push_back(ele_face_pt);
           // Mark as done
           done_el[ele_face_pt] = true;
 #ifdef OOMPH_HAS_MPI
         } // else if (this->is_mesh_distributed())
 #endif
 #ifdef PARANOID
         if (!found_initial_face_element)
         {
           std::ostringstream error_message;
           error_message << "Could not find an initial face element for the "
                            "current segment\n";
           throw OomphLibError(error_message.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
 #endif
         // Number of nodes of the initial face element
         const unsigned nnod = ele_face_pt->nnode();
         // Left and rightmost nodes (the left and right nodes of the
         // current face element)
         Node* left_node_pt = ele_face_pt->node_pt(0);
         Node* right_node_pt = ele_face_pt->node_pt(nnod - 1);
         // Continue iterating if a new face element has been added to
         // the list
         bool face_element_added = false;
         // While a new face element has been added to the set of sorted
         // face elements continue iterating
         do
         {
           // Start from the next face element since we have already
           // added the previous one as the initial face element (any
           // previous face element had to be added on previous
           // iterations)
           for (unsigned iiface = iface; iiface < nel; iiface++)
           {
             // Re-start flag
             face_element_added = false;
             // Get the candidate element
             ele_face_pt = face_el_pt[iiface];
             // Check that the candidate element has not been done and
             // is not a halo element
             if (!(done_el[ele_face_pt] || is_halo_face_element[iiface]))
             {
               // Get the left and right nodes of the current element
               Node* local_left_node_pt = ele_face_pt->node_pt(0);
               Node* local_right_node_pt = ele_face_pt->node_pt(nnod - 1);
               // New element fits at the left of segment and is not inverted
               if (left_node_pt == local_right_node_pt)
               {
                 left_node_pt = local_left_node_pt;
                 sorted_el_pt.push_front(ele_face_pt);
                 is_inverted[ele_face_pt] = false;
                 face_element_added = true;
               }
               // New element fits at the left of segment and is inverted
               else if (left_node_pt == local_left_node_pt)
               {
                 left_node_pt = local_right_node_pt;
                 sorted_el_pt.push_front(ele_face_pt);
                 is_inverted[ele_face_pt] = true;
                 face_element_added = true;
               }
               // New element fits on the right of segment and is not inverted
               else if (right_node_pt == local_left_node_pt)
               {
                 right_node_pt = local_right_node_pt;
                 sorted_el_pt.push_back(ele_face_pt);
                 is_inverted[ele_face_pt] = false;
                 face_element_added = true;
               }
               // New element fits on the right of segment and is inverted
               else if (right_node_pt == local_right_node_pt)
               {
                 right_node_pt = local_left_node_pt;
                 sorted_el_pt.push_back(ele_face_pt);
                 is_inverted[ele_face_pt] = true;
                 face_element_added = true;
               }
               if (face_element_added)
               {
                 done_el[ele_face_pt] = true;
                 nsorted_face_elements++;
                 break;
               }
             } // if (!(done_el[ele_face_pt] || is_halo_face_element[iiface]))
           } // for (iiface<nnon_halo_face_element)
         } while (face_element_added &&
                  (nsorted_face_elements < nnon_halo_face_elements));
         // Store the created segment in the vector of segments
         segment_sorted_ele_pt.push_back(sorted_el_pt);
       } // while(nsorted_face_elements < nnon_halo_face_elements);
 #ifdef OOMPH_HAS_MPI
       if (!this->is_mesh_distributed())
       {
 #endif
         // Are we done?
         if (nsorted_face_elements != nel || segment_sorted_ele_pt.size() != 1)
         {
           std::ostringstream error_message;
           error_message << "Was only able to setup boundary coordinate on "
                         << "boundary " << b << "\nfor " << nsorted_face_elements
                         << " of " << nel
                         << " face elements. This usually means\n"
                         << "that the boundary is not simply connected.\n\n"
                         << "Re-run the setup_boundary_coordintes() function\n"
                         << "with an output file specified "
                         << "as the second argument.\n"
                         << "This file will contain FaceElements that\n"
                         << "oomph-lib believes to be located on the boundary.\n"
                         << std::endl;
           throw OomphLibError(error_message.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
 #ifdef OOMPH_HAS_MPI
       } // if (!this->is_mesh_distributed())
 #endif
       // =================================================================
       // END: Sort face elements
       // =================================================================
       // ----------------------------------------------------------------
       // =================================================================
       // BEGIN: Assign global/local (non distributed mesh/distributed
       // mesh) boundary coordinates to nodes
       // =================================================================
       // Compute the (local) boundary coordinates of the nodes in the
       // segments. In a distributed mesh this info. will be used by a
       // root processor to compute the (global) boundary coordinates.
       // Vector of sets that stores the nodes of each segment based on
       // a lexicographically order starting from the bottom left node
       // of each segment
       Vector<std::set<Node*>> segment_all_nodes_pt;
       // The number of segments in this processor
       const unsigned nsegments = segment_sorted_ele_pt.size();
 #ifdef PARANOID
       if (nnon_halo_face_elements > 0 && nsegments == 0)
       {
         std::ostringstream error_message;
         error_message
           << "The number of segments is zero, but the number of nonhalo\n"
           << "elements is: (" << nnon_halo_face_elements << ")\n";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       } // if (nnon_halo_face_elements > 0 && nsegments == 0)
 #endif
       // Store the arclength of each segment in the current processor
       Vector<double> segment_arclength(nsegments);
 #ifdef OOMPH_HAS_MPI
       // Clear the boundary segment nodes storage
       this->flush_boundary_segment_node(b);
       // Set the number of segments for the current boundary
       this->set_nboundary_segment_node(b, nsegments);
 #endif // #ifdef OOMPH_HAS_MPI
       // Go through all the segments and compute their (local) boundary
       // coordinates
       for (unsigned is = 0; is < nsegments; is++)
       {
 #ifdef PARANOID
         if (segment_sorted_ele_pt[is].size() == 0)
         {
           std::ostringstream error_message;
           std::string output_string =
             "UnstructuredTwoDMeshGeometryBase::setup_boundary_coordinates()";
           error_message << "The (" << is << ")-th segment has no elements\n";
           throw OomphLibError(
             error_message.str(), output_string, OOMPH_EXCEPTION_LOCATION);
         } // if (segment_sorted_ele_pt[is].size() == 0)
 #endif
         // Get access to the first element on the segment
         FiniteElement* first_ele_pt = segment_sorted_ele_pt[is].front();
         // Number of nodes
         unsigned nnod = first_ele_pt->nnode();
         // Get the first node of the current segment
         Node* first_node_pt = first_ele_pt->node_pt(0);
         if (is_inverted[first_ele_pt])
         {
           first_node_pt = first_ele_pt->node_pt(nnod - 1);
         }
         // Coordinates of left node
         double x_left = first_node_pt->x(0);
         double y_left = first_node_pt->x(1);
         // Initialise boundary coordinate (local boundary coordinate
         // for boundaries with more than one segment)
         Vector<double> zeta(1, 0.0);
         // Set boundary coordinate
         first_node_pt->set_coordinates_on_boundary(b, zeta);
         // Lexicographically bottom left node
         std::set<Node*> local_nodes_pt;
         local_nodes_pt.insert(first_node_pt);
 #ifdef OOMPH_HAS_MPI
         // Insert the node in the look-up scheme for nodes in segments
         this->add_boundary_segment_node(b, is, first_node_pt);
 #endif // #ifdef OOMPH_HAS_MPI
         // Now loop over nodes in order
         for (std::list<FiniteElement*>::iterator it =
                segment_sorted_ele_pt[is].begin();
              it != segment_sorted_ele_pt[is].end();
              it++)
         {
           // Get element
           FiniteElement* el_pt = *it;
           // Start node and increment
           unsigned k_nod = 1;
           int nod_diff = 1;
           if (is_inverted[el_pt])
           {
             k_nod = nnod - 2;
             nod_diff = -1;
           }
           // Loop over nodes
           for (unsigned j = 1; j < nnod; j++)
           {
             Node* nod_pt = el_pt->node_pt(k_nod);
             k_nod += nod_diff;
             // Coordinates of right node
             double x_right = nod_pt->x(0);
             double y_right = nod_pt->x(1);
             // Increment boundary coordinate
             zeta[0] += sqrt((x_right - x_left) * (x_right - x_left) +
                             (y_right - y_left) * (y_right - y_left));
             // Set boundary coordinate
             nod_pt->set_coordinates_on_boundary(b, zeta);
             // Increment reference coordinate
             x_left = x_right;
             y_left = y_right;
             // Get lexicographically bottom left node but only
             // use vertex nodes as candidates
             local_nodes_pt.insert(nod_pt);
 #ifdef OOMPH_HAS_MPI
             // Insert the node in the look-up scheme for nodes in segments
             this->add_boundary_segment_node(b, is, nod_pt);
 #endif // #ifdef OOMPH_HAS_MPI
           } // for (j < nnod)
         } // iterator over the elements in the segment
         // Assign the arclength of the current segment
         segment_arclength[is] = zeta[0];
         // Add the nodes for the corresponding segment in the container
         segment_all_nodes_pt.push_back(local_nodes_pt);
       } // for (is < nsegments)
       // =================================================================
       // END: Assign global/local (non distributed mesh/distributed
       // mesh) boundary coordinates to nodes
       // =================================================================
       // Store the initial arclength for each segment of boundary in
       // the current processor, initialise to zero in case we have a
       // non distributed mesh
       Vector<double> initial_segment_arclength(nsegments, 0.0);
       // Store the final arclength for each segment of boundary in the
       // current processor, initalise to zero in case we have a non
       // distributed mesh
       Vector<double> final_segment_arclength(nsegments, 0.0);
       // Store the initial zeta for each segment of boundary in the
       // current processor, initalise to zero in case we have a non
       // distributed mesh
       Vector<double> initial_segment_zeta(nsegments, 0.0);
       // Store the final zeta for each segment of boundary in the
       // current processor, initalise to zero in case we have a non
       // distributed mesh
       Vector<double> final_segment_zeta(nsegments, 0.0);
       // --------------------------------------------------------------
       // DISTRIBUTED MESH: BEGIN - Check orientation of boundaries and
       // assign boundary coordinates accordingly
       // --------------------------------------------------------------
 #ifdef OOMPH_HAS_MPI
       // Check that the mesh is distributed and that the initial zeta
       // values for the boundary segments have been already
       // assigned. When the method is called by the first time (when
       // the mesh is just created) the initial zeta values for the
       // boundary segments are not available
       if (this->is_mesh_distributed() &&
           Assigned_segments_initial_zeta_values[b])
       {
         // Get the initial and final coordinates of each segment
         // For each segment in the processor check whether it was
         // inverted in the root processor, if that is the case then it
         // is necessary to re-sort the face elements and invert them
         for (unsigned is = 0; is < nsegments; is++)
         {
           // Check if we need/or not to invert the current zeta values
           // on the segment (only apply for boundaries with GeomObject
           // associated)
           // Does the boundary HAS a GeomObject associated?
           if (this->boundary_geom_object_pt(b) != 0)
           {
             // Get the first and last node of the current segment and
             // their zeta values
             // Get access to the first element on the segment
             FiniteElement* first_ele_pt = segment_sorted_ele_pt[is].front();
             // Number of nodes
             const unsigned nnod = first_ele_pt->nnode();
             // Get the first node of the current segment
             Node* first_node_pt = first_ele_pt->node_pt(0);
             if (is_inverted[first_ele_pt])
             {
               first_node_pt = first_ele_pt->node_pt(nnod - 1);
             }
             // Get access to the last element on the segment
             FiniteElement* last_ele_pt = segment_sorted_ele_pt[is].back();
             // Get the last node of the current segment
             Node* last_node_pt = last_ele_pt->node_pt(nnod - 1);
             if (is_inverted[last_ele_pt])
             {
               last_node_pt = last_ele_pt->node_pt(0);
             }
             // Get the zeta coordinates for the first and last node
             Vector<double> current_segment_initial_zeta(1);
             Vector<double> current_segment_final_zeta(1);
             first_node_pt->get_coordinates_on_boundary(
               b, current_segment_initial_zeta);
             last_node_pt->get_coordinates_on_boundary(
               b, current_segment_final_zeta);
 #ifdef PARANOID
             // Check whether the zeta values in the segment are in
             // increasing or decreasing order
             if (current_segment_initial_zeta[0] < current_segment_final_zeta[0])
             {
               // do nothing
             }
             else if (current_segment_initial_zeta[0] >
                      current_segment_final_zeta[0])
             {
               std::stringstream error_message;
               std::string output_string = "UnstructuredTwoDMeshGeometryBase::"
                                           "setup_boundary_coordinates()";
               error_message
                 << "The zeta values are in decreasing order, this is weird\n"
                 << "since they have just been set-up in increasing order few\n"
                 << "lines above\n"
                 << "Boundary: (" << b << ")\n"
                 << "Segment: (" << is << ")\n"
                 << "Initial zeta value: (" << current_segment_initial_zeta[0]
                 << ")\n"
                 << "Initial coordinate: (" << first_node_pt->x(0) << ", "
                 << first_node_pt->x(1) << ")\n"
                 << "Final zeta value: (" << current_segment_final_zeta[0]
                 << ")\n"
                 << "Initial coordinate: (" << last_node_pt->x(0) << ", "
                 << last_node_pt->x(1) << ")\n";
               throw OomphLibError(
                 error_message.str(), output_string, OOMPH_EXCEPTION_LOCATION);
             }
             else
             {
               std::stringstream error_message;
               std::string output_string = "UnstructuredTwoDMeshGeometryBase::"
                                           "setup_boundary_coordinates()";
               error_message
                 << "It was not possible to determine whether the zeta values on"
                 << "the current segment\nof the boundary are in"
                 << "increasing or decreasing order\n\n"
                 << "Boundary: (" << b << ")\n"
                 << "Segment: (" << is << ")\n"
                 << "Arclength: (" << segment_arclength[is] << "\n"
                 << "Initial zeta value: (" << current_segment_initial_zeta[0]
                 << ")\n"
                 << "Initial coordinate: (" << first_node_pt->x(0) << ", "
                 << first_node_pt->x(1) << ")\n"
                 << "Final zeta value: (" << current_segment_final_zeta[0]
                 << ")\n"
                 << "Initial coordinate: (" << last_node_pt->x(0) << ", "
                 << last_node_pt->x(1) << ")\n";
               throw OomphLibError(
                 error_message.str(), output_string, OOMPH_EXCEPTION_LOCATION);
             }
 #endif // #ifdef PARANOID
             // Now get the original zeta values and check if they are in
             // increasing or decreasing order
             const double original_segment_initial_zeta =
               boundary_segment_initial_zeta(b)[is];
             const double original_segment_final_zeta =
               boundary_segment_final_zeta(b)[is];
             // Now check if the zeta values go in increase or decrease
             // order
             if (original_segment_final_zeta > original_segment_initial_zeta)
             {
               // The original values go in increasing order, only need
               // to change the values if the original segment is marked
               // as inverted
               if (boundary_segment_inverted(b)[is])
               {
                 // The original segment is inverted, then we need to
                 // reverse the boundary coordinates. Go through all the
                 // nodes and reverse its value
                 std::set<Node*> all_nodes_pt = segment_all_nodes_pt[is];
                 for (std::set<Node*>::iterator it = all_nodes_pt.begin();
                      it != all_nodes_pt.end();
                      it++)
                 {
                   Vector<double> zeta(1);
                   // Get the node
                   Node* nod_pt = (*it);
                   // Get the boundary coordinate associated to the node
                   nod_pt->get_coordinates_on_boundary(b, zeta);
                   // Compute its new value
                   zeta[0] = segment_arclength[is] - zeta[0];
                   // Set the new boundary coordinate value
                   nod_pt->set_coordinates_on_boundary(b, zeta);
                 } // Loop over the nodes in the segment
               } // if (boundary_segment_inverted(b)[is])
               else
               {
                 // The boundary is not inverted, do nothing!!!
               }
             } // original zeta values in increasing order
             else if (original_segment_final_zeta <
                      original_segment_initial_zeta)
             {
               // The original values go in decreasing order, only need
               // to change the values if the original segment is NOT
               // marked as inverted
               if (boundary_segment_inverted(b)[is])
               {
                 // The boundary is inverted, do nothing!!!
               }
               else
               {
                 // The original segment is NOT inverted, then we need
                 // to reverse the boundary coordinates. Go through all
                 // the nodes and reverse its value
                 std::set<Node*> all_nodes_pt = segment_all_nodes_pt[is];
                 for (std::set<Node*>::iterator it = all_nodes_pt.begin();
                      it != all_nodes_pt.end();
                      it++)
                 {
                   Vector<double> zeta(1);
                   // Get the node
                   Node* nod_pt = (*it);
                   // Get the boundary coordinate associated to the node
                   nod_pt->get_coordinates_on_boundary(b, zeta);
                   // Compute its new value
                   zeta[0] = segment_arclength[is] - zeta[0];
                   // Set the new boundary coordinate value
                   nod_pt->set_coordinates_on_boundary(b, zeta);
                 } // Loop over the nodes in the segment
               } // else if (boundary_segment_inverted(b)[is])
             } // original zeta values in decreasing order
 #ifdef PARANOID
             else
             {
               std::stringstream error_message;
               std::string output_string = "UnstructuredTwoDMeshGeometryBase::"
                                           "setup_boundary_coordinates()";
               error_message
                 << "It was not possible to identify if the zeta values on the\n"
                 << "current segment in the boundary should go in increasing\n"
                 << "or decreasing order.\n\n"
                 << "Boundary: (" << b << ")\n"
                 << "Segment: (" << is << ")\n"
                 << "Initial zeta value: (" << original_segment_initial_zeta
                 << ")\n"
                 << "Final zeta value: (" << original_segment_final_zeta
                 << ")\n";
               throw OomphLibError(
                 error_message.str(), output_string, OOMPH_EXCEPTION_LOCATION);
             }
 #endif
           } // if (this->boundary_geom_object_pt(b)!=0)
           else
           {
             // No GeomObject associated, do nothing!!!
           } // else if (this->boundary_geom_object_pt(b)!=0)
         } // for (is < nsegments)
       } // if (this->is_mesh_distributed() &&
       // Assigned_segments_initial_zeta_values[b])
 #endif // #ifdef OOMPH_HAS_MPI
       // Get the number of sets for nodes
 #ifdef PARANOID
       if (segment_all_nodes_pt.size() != nsegments)
       {
         std::ostringstream error_message;
         std::string output_string =
           "UnstructuredTwoDMeshGeometryBase::setup_boundary_coordinates()";
         error_message << "The number of segments (" << nsegments
                       << ") and the number of "
                       << "sets of nodes (" << segment_all_nodes_pt.size()
                       << ") representing\n"
                       << "the\nsegments is different!!!\n\n";
         throw OomphLibError(
           error_message.str(), output_string, OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // --------------------------------------------------------------
       // DISTRIBUTED MESH: END - Check orientation of boundaries and
       // assign boundary coordinates accordingly
       // --------------------------------------------------------------
       // =================================================================
       // BEGIN: Get the lenght of the boundaries or segments of the
       // boundary
       // =================================================================
       // The nodes have been assigned arc-length coordinates from one
       // end or the other of the segments. If the mesh is distributed
       // the values are set so that they agree with the increasing or
       // decreasing order of the zeta values for the segments
       // Storage for the coordinates of the first and last nodes
       Vector<double> first_coordinate(2);
       Vector<double> last_coordinate(2);
       // Storage for the zeta coordinate of the first and last nodes
       Vector<double> first_node_zeta_coordinate(1, 0.0);
       Vector<double> last_node_zeta_coordinate(1, 0.0);
       // Store the accumulated arclength, used at the end to check the
       // max arclength of the boundary
       double boundary_arclength = 0.0;
       // If the mesh is marked as distributed and the initial zeta
       // values for the segments have been computed then get the
       // info. regarding the initial and final nodes coordinates, same
       // as the zeta boundary values for those nodes
 #ifdef OOMPH_HAS_MPI
       if (this->is_mesh_distributed() &&
           Assigned_segments_initial_zeta_values[b])
       {
         // --------------------------------------------------------------
         // DISTRIBUTED MESH: BEGIN
         // --------------------------------------------------------------
         // Get the initial and final coordinates for the complete boundary
         first_coordinate = boundary_initial_coordinate(b);
         last_coordinate = boundary_final_coordinate(b);
         // Get the initial and final zeta values for the boundary
         // (arclength)
         first_node_zeta_coordinate = boundary_initial_zeta_coordinate(b);
         last_node_zeta_coordinate = boundary_final_zeta_coordinate(b);
         // The total arclength is the maximum between the initial and
         // final zeta coordinate
         boundary_arclength =
           std::max(first_node_zeta_coordinate[0], last_node_zeta_coordinate[0]);
 #ifdef PARANOID
         if (boundary_arclength == 0)
         {
           std::ostringstream error_message;
           std::string output_string =
             "UnstructuredTwoDMeshGeometryBase::setup_boundary_coordinates()";
           error_message << "The boundary arclength is zero for boundary (" << b
                         << ")\n";
           throw OomphLibError(
             error_message.str(), output_string, OOMPH_EXCEPTION_LOCATION);
         }
 #endif
         // Check if there is a GeomObject associated to the boundary,
         // and assign the corresponding zeta (arclength) values
         if (this->boundary_geom_object_pt(b) != 0)
         {
           initial_segment_zeta = boundary_segment_initial_zeta(b);
           final_segment_zeta = boundary_segment_final_zeta(b);
         }
         else
         {
           initial_segment_arclength = boundary_segment_initial_arclength(b);
           final_segment_arclength = boundary_segment_final_arclength(b);
         }
         // --------------------------------------------------------------
         // DISTRIBUTED MESH: END
         // --------------------------------------------------------------
       } // if (this->is_mesh_distributed() &&
       //     Assigned_segments_initial_zeta_values[b])
       else
       {
 #endif // #ifdef OOMPH_HAS_MPI
         // If the mesh is NOT distributed or the initial and final zeta
         // values of the segments have not been assigned then perform
         // as in the serial case
         if (this->boundary_geom_object_pt(b) != 0)
         {
           initial_segment_zeta[0] = this->boundary_coordinate_limits(b)[0];
           final_segment_zeta[0] = this->boundary_coordinate_limits(b)[1];
         }
         else
         {
           // When the mesh is or not distributed but the initial
           // segment's zeta values HAVE NOT been established then
           // initalize the initial segment to zero
           initial_segment_arclength[0] = 0.0;
         }
 #ifdef OOMPH_HAS_MPI
       } // The mesh is NOT distributed or the zeta values for the
       // segments have not been established
 #endif // #ifdef OOMPH_HAS_MPI
       // =================================================================
       // END: Get the lenght of the boundaries or segments of the
       // boundary
       // =================================================================
       // =================================================================
       // BEGIN: Scale the boundary coordinates based on whether the
       // boundary has an associated GeomObj or not
       // =================================================================
       // Go through all the segments and assign the scaled boundary
       // coordinates
       for (unsigned is = 0; is < nsegments; is++)
       {
 #ifdef PARANOID
         if (segment_sorted_ele_pt[is].size() == 0)
         {
           std::ostringstream error_message;
           std::string output_string =
             "UnstructuredTwoDMeshGeometryBase::setup_boundary_coordinates()";
           error_message << "The (" << is << ")-th segment has no elements\n";
           throw OomphLibError(
             error_message.str(), output_string, OOMPH_EXCEPTION_LOCATION);
         } // if (segment_sorted_ele_pt[is].size() == 0)x
 #endif
         // Get the first and last nodes coordinates for the current
         // segment
 #ifdef OOMPH_HAS_MPI
         // Check if the initial zeta values of the segments have been
         // established, if they have not then get the first and last
         // coordinates from the current segments, same as the zeta
         // values
         if (!Assigned_segments_initial_zeta_values[b])
         {
 #endif // #ifdef OOMPH_HAS_MPI
           // Get access to the first element on the segment
           FiniteElement* first_ele_pt = segment_sorted_ele_pt[is].front();
           // Number of nodes
           const unsigned nnod = first_ele_pt->nnode();
           // Get the first node of the current segment
           Node* first_node_pt = first_ele_pt->node_pt(0);
           if (is_inverted[first_ele_pt])
           {
             first_node_pt = first_ele_pt->node_pt(nnod - 1);
           }
           // Get access to the last element on the segment
           FiniteElement* last_ele_pt = segment_sorted_ele_pt[is].back();
           // Get the last node of the current segment
           Node* last_node_pt = last_ele_pt->node_pt(nnod - 1);
           if (is_inverted[last_ele_pt])
           {
             last_node_pt = last_ele_pt->node_pt(0);
           }
           // Get the coordinates for the first and last node
           for (unsigned i = 0; i < 2; i++)
           {
             first_coordinate[i] = first_node_pt->x(i);
             last_coordinate[i] = last_node_pt->x(i);
           }
           // Get the zeta coordinates for the first and last node
           first_node_pt->get_coordinates_on_boundary(
             b, first_node_zeta_coordinate);
           last_node_pt->get_coordinates_on_boundary(b,
                                                     last_node_zeta_coordinate);
 #ifdef OOMPH_HAS_MPI
         } // if (!Assigned_segments_initial_zeta_values[b])
 #endif // #ifdef OOMPH_HAS_MPI
         // Get the nodes of the current segment
         std::set<Node*> all_nodes_pt = segment_all_nodes_pt[is];
         // If the boundary has a geometric object representation then
         // scale the coordinates to match those of the geometric object
         GeomObject* const geom_object_pt = this->boundary_geom_object_pt(b);
         if (geom_object_pt != 0)
         {
           Vector<double> bound_coord_limits =
             this->boundary_coordinate_limits(b);
           // Get the position of the ends of the geometric object
           Vector<double> zeta(1);
           Vector<double> first_geom_object_location(2);
           Vector<double> last_geom_object_location(2);
           // Get the zeta value for the initial coordinates of the
           // GeomObject
           zeta[0] = bound_coord_limits[0];
           // zeta[0] = initial_segment_zeta[is];
           // Get the coordinates from the initial zeta value from the
           // GeomObject
           geom_object_pt->position(zeta, first_geom_object_location);
           // Get the zeta value for the final coordinates of the
           // GeomObject
           zeta[0] = bound_coord_limits[1];
           // zeta[0] = final_segment_zeta[is];
           // Get the coordinates from the final zeta value from the
           // GeomObject
           geom_object_pt->position(zeta, last_geom_object_location);
           // Calculate the errors in position between the first and
           // last nodes and the endpoints of the geometric object
           double error = 0.0;
           double tmp_error = 0.0;
           for (unsigned i = 0; i < 2; i++)
           {
             const double dist =
               first_geom_object_location[i] - first_coordinate[i];
             tmp_error += dist * dist;
           }
           error += sqrt(tmp_error);
           tmp_error = 0.0;
           for (unsigned i = 0; i < 2; i++)
           {
             const double dist =
               last_geom_object_location[i] - last_coordinate[i];
             tmp_error += dist * dist;
           }
           error += sqrt(tmp_error);
           // Calculate the errors in position between the first and
           // last nodes and the endpoints of the geometric object if
           // reversed
           double rev_error = 0.0;
           tmp_error = 0.0;
           for (unsigned i = 0; i < 2; i++)
           {
             const double dist =
               first_geom_object_location[i] - last_coordinate[i];
             tmp_error += dist * dist;
           }
           rev_error += sqrt(tmp_error);
           tmp_error = 0.0;
           for (unsigned i = 0; i < 2; i++)
           {
             const double dist =
               last_geom_object_location[i] - first_coordinate[i];
             tmp_error += dist * dist;
           }
           rev_error += sqrt(tmp_error);
           // Number of polyline vertices along this boundary
           const unsigned n_vertex = Polygonal_vertex_arclength_info[b].size();
           // Get polygonal vertex data
           Vector<std::pair<double, double>> polygonal_vertex_arclength =
             Polygonal_vertex_arclength_info[b];
           // If the (normal) error is small than reversed then we have
           // the coordinate direction correct. If not then we must
           // reverse it bool reversed = false;
           if (error < rev_error)
           {
             // Coordinates are aligned (btw: don't delete this block --
             // there's a final else below to catch errors!)
             // reversed = false;
           }
           else if (error > rev_error)
           {
             // reversed = true;
             // Reverse the limits of the boundary coordinates along the
             // geometric object
             double temp = bound_coord_limits[0];
             bound_coord_limits[0] = bound_coord_limits[1];
             bound_coord_limits[1] = temp;
 #ifdef OOMPH_HAS_MPI
             // If we are working with a NON distributed mesh then
             // re-assign the initial and final zeta values
             if (!this->is_mesh_distributed())
             {
 #endif
               temp = initial_segment_zeta[is];
               initial_segment_zeta[is] = final_segment_zeta[is];
               final_segment_zeta[is] = temp;
 #ifdef OOMPH_HAS_MPI
             }
 #endif
             // Reverse the vertices information
             for (unsigned v = 0; v < n_vertex; v++)
             {
               polygonal_vertex_arclength[v].first =
                 Polygonal_vertex_arclength_info[b][v].first;
               polygonal_vertex_arclength[v].second =
                 Polygonal_vertex_arclength_info[b][n_vertex - v - 1].second;
             } // for (v < n_vertex)
           }
           else
           {
             std::ostringstream error_stream;
             std::string output_string =
               "UnstructuredTwoDMeshGeometryBase::setup_boundary_coordinates()";
             error_stream
               << "Something very strange has happened.\n"
               << "The error between the endpoints of the geometric object\n"
               << "and the first and last nodes on the boundary is the same\n"
               << "irrespective of the direction of the coordinate.\n"
               << "This probably means that things are way off.\n"
               << "The errors are " << error << " and " << rev_error << "\n";
             std::cout << error_stream.str();
             throw OomphLibError(
               error_stream.str(), output_string, OOMPH_EXCEPTION_LOCATION);
           }
           // Get the total arclength of the edge
           // last_node_pt->get_coordinates_on_boundary(b, zeta);
           // double zeta_old_range=zeta[0];
           // Store the arclength of the segment (not yet mapped to the
           // boundary coordinates defined by the GeomObject)
           const double zeta_old_range = segment_arclength[is];
           // double zeta_new_range=bound_coord_limits[1]-bound_coord_limits[0];
           // The range to map the zeta values
           double zeta_new_range =
             final_segment_zeta[is] - initial_segment_zeta[is];
           // The initial zeta value for the current segment
           double initial_local_segment_zeta = initial_segment_zeta[is];
 #ifdef OOMPH_HAS_MPI
           // If we are working with a distributed mes and the initial
           // and final zeta values for the segments have been
           // established then reset the range to map
           if (this->is_mesh_distributed() &&
               Assigned_segments_initial_zeta_values[b])
           {
             // Re-set the range to map the zeta values
             zeta_new_range =
               std::fabs(final_segment_zeta[is] - initial_segment_zeta[is]);
             // Re-set the initial zeta value of the segment
             initial_local_segment_zeta =
               std::min(initial_segment_zeta[is], final_segment_zeta[is]);
           }
 #endif
           // Re-assign boundary coordinate for the case where boundary
           // is represented by polygon
           unsigned use_old = false;
           if (n_vertex == 0) use_old = true;
           // Now scale the coordinates accordingly
           for (std::set<Node*>::iterator it = all_nodes_pt.begin();
                it != all_nodes_pt.end();
                it++)
           {
             // Get the node
             Node* nod_pt = (*it);
             // Get coordinate based on arclength along polygonal repesentation
             nod_pt->get_coordinates_on_boundary(b, zeta);
             if (use_old)
             {
               // Boundary is actually a polygon -- simply rescale
               zeta[0] = initial_local_segment_zeta +
                         (zeta_new_range / zeta_old_range) * (zeta[0]);
             }
             else
             {
               // Scale such that vertex nodes stay where they were
               bool found = false;
               // Loop over vertex nodes
               for (unsigned v = 1; v < n_vertex; v++)
               {
                 if ((zeta[0] >= polygonal_vertex_arclength[v - 1].first) &&
                     (zeta[0] <= polygonal_vertex_arclength[v].first))
                 {
                   // Increment in intrinsic coordinate along geom object
                   double delta_zeta =
                     (polygonal_vertex_arclength[v].second -
                      polygonal_vertex_arclength[v - 1].second);
                   // Increment in arclength along segment
                   double delta_polyarc =
                     (polygonal_vertex_arclength[v].first -
                      polygonal_vertex_arclength[v - 1].first);
                   // Mapped arclength coordinate
                   double zeta_new =
                     polygonal_vertex_arclength[v - 1].second +
                     delta_zeta *
                       (zeta[0] - polygonal_vertex_arclength[v - 1].first) /
                       delta_polyarc;
                   zeta[0] = zeta_new;
                   // Success!
                   found = true;
                   // Bail out
                   break;
                 }
               } // for (v < n_vertex)
               // If we still haven't found it's probably the last point along
               if (!found)
               {
 #ifdef PARANOID
                 double diff = std::fabs(
                   zeta[0] - polygonal_vertex_arclength[n_vertex - 1].first);
                 if (diff >
                     ToleranceForVertexMismatchInPolygons::Tolerable_error)
                 {
                   std::ostringstream error_stream;
                   error_stream
                     << "Wasn't able to locate the polygonal arclength exactly\n"
                     << "during re-setup of boundary coordinates and have\n"
                     << "assumed that we're dealing with the final point along\n"
                     << "the curvilinear segment and encountered some roundoff\n"
                     << "However,the difference in the polygonal zeta "
                        "coordinates\n"
                     << "between zeta[0] " << zeta[0]
                     << " and the originallly stored value "
                     << polygonal_vertex_arclength[n_vertex - 1].first << "\n"
                     << "is " << diff
                     << " which exceeds the threshold specified\n"
                     << "in the publically modifiable variable\n"
                     << "ToleranceForVertexMismatchInPolygons::Tolerable_error\n"
                     << "whose current value is: "
                     << ToleranceForVertexMismatchInPolygons::Tolerable_error
                     << "\nPlease check your mesh carefully and increase the\n"
                     << "threshold if you're sure this is appropriate\n";
                   throw OomphLibError(error_stream.str(),
                                       OOMPH_CURRENT_FUNCTION,
                                       OOMPH_EXCEPTION_LOCATION);
                 }
 #endif
                 zeta[0] = polygonal_vertex_arclength[n_vertex - 1].second;
               }
             }
             // Assign updated coordinate
             nod_pt->set_coordinates_on_boundary(b, zeta);
           }
         } // if (geom_object_pt != 0)
         else
         {
           // Establish the initial zeta value for this segment
           double z_initial = initial_segment_arclength[is];
           // Only use end points of the whole boundary and pick the
           // bottom left node
           // Set the bottom left coordinate as the first coordinates
           Vector<double> bottom_left_coordinate(2);
           bottom_left_coordinate = first_coordinate;
           // ... do the same with the zeta value
           Vector<double> bottom_left_zeta_coordinate(1);
           bottom_left_zeta_coordinate = first_node_zeta_coordinate;
           // Is the last y-coordinate smaller than y-coordinate of the
           // current bottom left coordinate
           if (last_coordinate[1] < bottom_left_coordinate[1])
           {
             // Re-set the bottom-left coordinate as the last coordinate
             bottom_left_coordinate = last_coordinate;
             // ... do the same with the zeta value
             bottom_left_zeta_coordinate = last_node_zeta_coordinate;
           }
           // The y-coordinates are the same
           else if (last_coordinate[1] == bottom_left_coordinate[1])
           {
             // Then check for the x-coordinate, which is the most-left
             if (last_coordinate[0] < bottom_left_coordinate[0])
             {
               // Re-set the bottom-left coordinate as the last
               // coordinate
               bottom_left_coordinate = last_coordinate;
               // ... do the same with the zeta value
               bottom_left_zeta_coordinate = last_node_zeta_coordinate;
             }
           } // else (The y-coordinates are the same)
           Vector<double> zeta(1, 0.0);
           // Now adjust boundary coordinate so that the bottom left
           // node has a boundary coordinate of 0.0 and that zeta
           // increases away from that point
           zeta = bottom_left_zeta_coordinate;
           const double zeta_ref = zeta[0];
           // Also get the maximum zeta value
           double zeta_max = 0.0;
           for (std::set<Node*>::iterator it = all_nodes_pt.begin();
                it != all_nodes_pt.end();
                it++)
           {
             Node* nod_pt = (*it);
             nod_pt->get_coordinates_on_boundary(b, zeta);
 #ifdef OOMPH_HAS_MPI
             // If the mesh is distributed and the initial and final
             // zeta values for the segment have been assigned then
             // check if the segment is inverted, we need to consider
             // that to correctly assgin the zeta values for the segment
             if (this->is_mesh_distributed() &&
                 Assigned_segments_initial_zeta_values[b])
             {
               // Is the segment inverted, if that is the case then
               // invert the zeta values
               if (boundary_segment_inverted(b)[is])
               {
                 zeta[0] = segment_arclength[is] - zeta[0];
               } // if (boundary_segment_inverted(b)[is])
             }
 #endif // #ifdef OOMPH_HAS_MPI
             // Set the zeta value
             zeta[0] += z_initial;
             // Adjust the value based on the bottom-left condition
             zeta[0] -= zeta_ref;
             // If direction is reversed, then take absolute value
             if (zeta[0] < 0.0)
             {
               zeta[0] = std::fabs(zeta[0]);
             }
             // Get the max zeta value (we will use it to scale the
             // values to [0,1])
             if (zeta[0] > zeta_max)
             {
               zeta_max = zeta[0];
             }
             nod_pt->set_coordinates_on_boundary(b, zeta);
           } // Loop through the nodes in the segment (boundary)
 #ifdef OOMPH_HAS_MPI
           // After assigning boundary coordinates, BUT before scaling,
           // copy the initial and final segment arclengths so that we
           // know if the values go in increasing or decreasing
           // order. This will be used to identify the correct direction
           // of the segments in the new meshes created in the
           // adaptation method.
           if (this->is_mesh_distributed() &&
               Assigned_segments_initial_zeta_values[b])
           {
             // Get the first face element
             FiniteElement* first_seg_ele_pt = segment_sorted_ele_pt[is].front();
 #ifdef PARANOID
             // Check if the face element is nonhalo, it shouldn't, but
             // better check
             if (first_seg_ele_pt->is_halo())
             {
               std::ostringstream error_message;
               std::string output_string = "UnstructuredTwoDMeshGeometryBase::"
                                           "setup_boundary_coordinates()";
               error_message << "The first face element in the (" << is
                             << ")-th segment"
                             << " is halo\n";
               throw OomphLibError(
                 error_message.str(), output_string, OOMPH_EXCEPTION_LOCATION);
             } // if (first_seg_ele_pt->is_halo())
 #endif
             // Number of nodes
             const unsigned nnod = first_seg_ele_pt->nnode();
             // Get the first node of the current segment
             Node* first_seg_node_pt = first_seg_ele_pt->node_pt(0);
             if (is_inverted[first_seg_ele_pt])
             {
               first_seg_node_pt = first_seg_ele_pt->node_pt(nnod - 1);
             }
             // Get the last face element
             FiniteElement* last_seg_ele_pt = segment_sorted_ele_pt[is].back();
 #ifdef PARANOID
             // Check if the face element is nonhalo, it shouldn't, but
             // better check
             if (last_seg_ele_pt->is_halo())
             {
               std::ostringstream error_message;
               std::string output_string = "UnstructuredTwoDMeshGeometryBase::"
                                           "setup_boundary_coordinates()";
               error_message << "The last face element in the (" << is
                             << ")-th segment"
                             << " is halo\n";
               throw OomphLibError(
                 error_message.str(), output_string, OOMPH_EXCEPTION_LOCATION);
             } // if (last_seg_ele_pt->is_halo())
 #endif
             // Get the last node of the current segment
             Node* last_seg_node_pt = last_seg_ele_pt->node_pt(nnod - 1);
             if (is_inverted[last_seg_ele_pt])
             {
               last_seg_node_pt = last_seg_ele_pt->node_pt(0);
             }
             // Now get the first and last node boundary coordinate values
             Vector<double> first_seg_arclen(1);
             Vector<double> last_seg_arclen(1);
             first_seg_node_pt->get_coordinates_on_boundary(b, first_seg_arclen);
             last_seg_node_pt->get_coordinates_on_boundary(b, last_seg_arclen);
             // Update the initial and final segments arclength
             boundary_segment_initial_arclength(b)[is] = first_seg_arclen[0];
             boundary_segment_final_arclength(b)[is] = last_seg_arclen[0];
             // Update the initial and final coordinates
             Vector<double> updated_segment_initial_coord(2);
             Vector<double> updated_segment_final_coord(2);
             for (unsigned k = 0; k < 2; k++)
             {
               updated_segment_initial_coord[k] = first_seg_node_pt->x(k);
               updated_segment_final_coord[k] = last_seg_node_pt->x(k);
             }
             // Set the updated initial coordinate
             boundary_segment_initial_coordinate(b)[is] =
               updated_segment_initial_coord;
             // Set the updated final coordinate
             boundary_segment_final_coordinate(b)[is] =
               updated_segment_final_coord;
           } // if (this->is_mesh_distributed() &&
           // Assigned_segments_initial_zeta_values[b])
 #endif // #ifdef OOMPH_HAS_MPI
           // The max. value will be incorrect if we are working with
           // distributed meshes where the current boundary has been
           // split by the distribution process. Here correct the
           // maximum value
           if (zeta_max < boundary_arclength)
           {
             zeta_max = boundary_arclength;
           }
           // Scale all surface coordinates so that all the points be on
           // the range [0, 1]
           for (std::set<Node*>::iterator it = all_nodes_pt.begin();
                it != all_nodes_pt.end();
                it++)
           {
             // Get the node
             Node* nod_pt = (*it);
             // Get the boundary coordinate
             nod_pt->get_coordinates_on_boundary(b, zeta);
             // Scale the value of the current node
             zeta[0] /= zeta_max;
             // Set the new scaled value
             nod_pt->set_coordinates_on_boundary(b, zeta);
           } // Loop over the nodes
         } // else if (geom_object_pt != 0)
       } // for (is < nsegments)
       // =================================================================
       // END: Scale the boundary coordinates based on whether the
       // boundary has an associated GeomObj or not
       // =================================================================
       // Cleanup
       for (unsigned e = 0; e < nel; e++)
       {
         delete face_el_pt[e];
         face_el_pt[e] = 0;
       }
     } // if (nel > 0), from the beginning of the method
     // Indicate that boundary coordinate has been set up
     Boundary_coordinate_exists[b] = true;
   }
References b, oomph::Mesh::Boundary_coordinate_exists, boundary_coordinate_limits(), boundary_element_in_region_pt(), oomph::Mesh::boundary_element_pt(), boundary_geom_object_pt(), e(), calibrate::error, boost::multiprecision::fabs(), oomph::Mesh::face_index_at_boundary(), face_index_at_boundary_in_region(), MergeRestartFiles::found, oomph::Node::get_coordinates_on_boundary(), i, oomph::Mesh::is_mesh_distributed(), j, k, max, min, oomph::Mesh::nboundary_element(), nboundary_element_in_region(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), nregion(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, Polygonal_vertex_arclength_info, oomph::GeomObject::position(), Region_attribute, oomph::Node::set_coordinates_on_boundary(), size, sqrt(), oomph::Global_string_for_annotation::string(), Suppress_warning_about_regions_and_boundaries, oomph::ToleranceForVertexMismatchInPolygons::Tolerable_error, v, oomph::Node::x(), and Eigen::zeta().
snap_nodes_onto_geometric_objects()
void oomph::UnstructuredTwoDMeshGeometryBase::snap_nodes_onto_geometric_objects () protected
Snap the boundary nodes onto any curvilinear boundaries defined by geometric objects
Move the nodes on boundaries with associated Geometric Objects so that they exactly coincide with the geometric object. This requires that the boundary coordinates are set up consistently
   {
     // Loop over all boundaries
     unsigned n_bound = this->nboundary();
     for (unsigned b = 0; b < n_bound; b++)
     {
       // Find the geometric object
       GeomObject* const geom_object_pt = this->boundary_geom_object_pt(b);
       // If there is one
       if (geom_object_pt != 0)
       {
         Vector<double> b_coord(1);
         Vector<double> new_x(2);
         const unsigned n_boundary_node = this->nboundary_node(b);
         for (unsigned n = 0; n < n_boundary_node; ++n)
         {
           // Get the boundary node and coordinates
           Node* const nod_pt = this->boundary_node_pt(b, n);
           nod_pt->get_coordinates_on_boundary(b, b_coord);
           // Get the position and time history according to the underlying
           // geometric object, assuming that it has the same timestepper
           // as the nodes....
           unsigned n_tvalues =
             1 + nod_pt->position_time_stepper_pt()->nprev_values();
           for (unsigned t = 0; t < n_tvalues; ++t)
           {
             // Get the position according to the underlying geometric object
             geom_object_pt->position(t, b_coord, new_x);
             // Move the node
             for (unsigned i = 0; i < 2; i++)
             {
               nod_pt->x(t, i) = new_x[i];
             }
           }
         }
       }
     }
   }
References b, boundary_geom_object_pt(), oomph::Mesh::boundary_node_pt(), oomph::Node::get_coordinates_on_boundary(), i, n, oomph::Mesh::nboundary(), oomph::Mesh::nboundary_node(), oomph::TimeStepper::nprev_values(), oomph::GeomObject::position(), oomph::Node::position_time_stepper_pt(), plotPSD::t, and oomph::Node::x().
Member Data Documentation
Allow_automatic_creation_of_vertices_on_boundaries
bool oomph::UnstructuredTwoDMeshGeometryBase::Allow_automatic_creation_of_vertices_on_boundaries protected
Flag to indicate whether the automatic creation of vertices along the boundaries by Triangle is allowed
Referenced by disable_automatic_creation_of_vertices_on_boundaries(), enable_automatic_creation_of_vertices_on_boundaries(), is_automatic_creation_of_vertices_on_boundaries_allowed(), oomph::QuadFromTriangleMesh< ELEMENT >::QuadFromTriangleMesh(), and oomph::TriangleMesh< ELEMENT >::TriangleMesh().
Boundary_coordinate_limits
std::map<unsigned, Vector<double> > oomph::UnstructuredTwoDMeshGeometryBase::Boundary_coordinate_limits protected
Storage for the limits of the boundary coordinates defined by the use of geometric objects. Only used for curvilinear boundaries.
Referenced by boundary_coordinate_limits().
Boundary_curve_section_pt
std::map<unsigned, TriangleMeshCurveSection*> oomph::UnstructuredTwoDMeshGeometryBase::Boundary_curve_section_pt protected
A map that stores the associated curve section of the specified boundary id
Referenced by boundary_polyline_pt().
Boundary_geom_object_pt
std::map<unsigned, GeomObject*> oomph::UnstructuredTwoDMeshGeometryBase::Boundary_geom_object_pt protected
Storage for the geometric objects associated with any boundaries.
Referenced by boundary_geom_object_pt().
Boundary_region_element_pt
Vector<std::map<unsigned, Vector<FiniteElement*> > > oomph::UnstructuredTwoDMeshGeometryBase::Boundary_region_element_pt protected
Storage for elements adjacent to a boundary in a particular region.
Referenced by boundary_element_in_region_pt(), and nboundary_element_in_region().
Extra_holes_coordinates
Vector<Vector<double> > oomph::UnstructuredTwoDMeshGeometryBase::Extra_holes_coordinates protected
Storage for extra coordinates for holes.
Face_index_region_at_boundary
Vector<std::map<unsigned, Vector<int> > > oomph::UnstructuredTwoDMeshGeometryBase::Face_index_region_at_boundary protected
Storage for the face index adjacent to a boundary in a particular region.
Referenced by face_index_at_boundary_in_region().
Free_curve_section_pt
std::set<TriangleMeshCurveSection*> oomph::UnstructuredTwoDMeshGeometryBase::Free_curve_section_pt protected
A set that contains the curve sections created by this object therefore it is necessary to free their associated memory
Referenced by oomph::QuadFromTriangleMesh< ELEMENT >::~QuadFromTriangleMesh(), and oomph::TriangleMesh< ELEMENT >::~TriangleMesh().
Free_open_curve_pt
std::set<TriangleMeshOpenCurve*> oomph::UnstructuredTwoDMeshGeometryBase::Free_open_curve_pt protected
A set that contains the open curves created by this object therefore it is necessary to free their associated memory
Referenced by oomph::QuadFromTriangleMesh< ELEMENT >::~QuadFromTriangleMesh(), and oomph::TriangleMesh< ELEMENT >::~TriangleMesh().
Free_polygon_pt
std::set<TriangleMeshPolygon*> oomph::UnstructuredTwoDMeshGeometryBase::Free_polygon_pt protected
A set that contains the polygons created by this object therefore it is necessary to free their associated memory
Referenced by oomph::QuadFromTriangleMesh< ELEMENT >::~QuadFromTriangleMesh(), and oomph::TriangleMesh< ELEMENT >::~TriangleMesh().
Internal_open_curve_pt
Vector<TriangleMeshOpenCurve*> oomph::UnstructuredTwoDMeshGeometryBase::Internal_open_curve_pt protected
Vector of open polylines that define internal curves.
Internal_polygon_pt
Vector<TriangleMeshPolygon*> oomph::UnstructuredTwoDMeshGeometryBase::Internal_polygon_pt protected
Vector of polygons that define internal polygons.
Nodes_on_boundary_pt
std::map<unsigned, std::set<Node*> > oomph::UnstructuredTwoDMeshGeometryBase::Nodes_on_boundary_pt protected
Stores a pointer to a set with all the nodes related with a boundary
Referenced by nodes_on_boundary_pt().
Outer_boundary_pt
Vector<TriangleMeshPolygon*> oomph::UnstructuredTwoDMeshGeometryBase::Outer_boundary_pt protected
Polygon that defines outer boundaries.
Polygonal_vertex_arclength_info
std::map<unsigned, Vector<std::pair<double, double> > > oomph::UnstructuredTwoDMeshGeometryBase::Polygonal_vertex_arclength_info protected
Storage for pairs of doubles representing: .first: the arclength along the polygonal representation of the curviline .second: the corresponding intrinsic coordinate on the associated geometric object at which the vertices on the specified boundary are located. Only used for boundaries represented by geom objects.
Referenced by setup_boundary_coordinates().
Region_attribute
Vector<double> oomph::UnstructuredTwoDMeshGeometryBase::Region_attribute protected
Vector of attributes associated with the elements in each region.
Referenced by nregion_attribute(), region_attribute(), and setup_boundary_coordinates().
Region_element_pt
std::map<unsigned, Vector<FiniteElement*> > oomph::UnstructuredTwoDMeshGeometryBase::Region_element_pt protected
Vector of elements in each region differentiated by attribute (the key of the map is the attribute)
Referenced by nregion(), nregion_element(), and region_element_pt().
Regions_coordinates
std::map<unsigned, Vector<double> > oomph::UnstructuredTwoDMeshGeometryBase::Regions_coordinates protected
Storage for extra coordinates for regions. The key on the map is the region id
Suppress_warning_about_regions_and_boundaries
bool oomph::UnstructuredTwoDMeshGeometryBase::Suppress_warning_about_regions_and_boundaries static
Public static flag to suppress warning; defaults to false.
Referenced by setup_boundary_coordinates().
The documentation for this class was generated from the following files:
unstructured_two_d_mesh_geometry_base.h
unstructured_two_d_mesh_geometry_base.cc