MercuryDPM: LiquidMigrationPeriodicBoundaryUnitTest.cpp File Reference
LiquidMigrationPeriodicBoundaryUnitTest.cpp File Reference
#include "DPMBase.h"
#include "Particles/LiquidFilmParticle.h"
#include "Boundaries/PeriodicBoundary.h"
#include <Species/LinearViscoelasticFrictionLiquidMigrationWilletSpecies.h>
Classes
class LiquidMigrationPeriodicBoundaryInteraction
Functions
int main ()
Function Documentation
main()
int main ()
 {
     logger(INFO,"This unit test checks that liquid bridge migration is not affected by the slight inaccuracy created "
      "by having ghost particles. A pair of particles is created that touches right at the periodic boundary.");
     logger(INFO,"Testing formation");
     LiquidMigrationPeriodicBoundaryInteraction dpm;
     //set dpm properties
     {
         dpm.setName("LiquidMigrationPeriodicBoundaryInteraction");
         dpm.setTimeStep(1e-4);
         dpm.setTimeMax(5e-4);
         dpm.setMin({0,-.5,-.5});
         dpm.setMax({5,.5,.5});
         dpm.setSaveCount(1);
         dpm.setGravity({0,0,0});
     }
     //add species
     {
         LinearViscoelasticFrictionLiquidMigrationWilletSpecies s;
         s.setDensity(6. / constants::pi);
         s.setCollisionTimeAndRestitutionCoefficient(50*dpm.getTimeStep(), .9, 1);
         s.setLiquidBridgeVolumeMax(1.1);
         dpm.speciesHandler.copyAndAddObject(s);
     }
     //add boundary
     {
         PeriodicBoundary b;
         b.set({1,0,0},-.5,4.5);
         dpm.boundaryHandler.copyAndAddObject(b);
     }
     //add particles
     {
         LiquidFilmParticle p;
         p.setRadius(.5);
         p.setSpecies(dpm.speciesHandler.getLastObject());
         p.setLiquidVolume(.5);
         p.setPosition({4,0,0});
         dpm.particleHandler.copyAndAddObject(p);
         //p.setPosition({0,0,0});
         p.setPosition({2*pow(2,-52),0,0}); //touches on left boundary, but not on right
         dpm.particleHandler.copyAndAddObject(p);
     }
     //solve should cause a bridge to form
     Mdouble initialLiquidVolume = dpm.getLiquidVolume();
     dpm.printTime();
     dpm.solve();
     logger.assert_always(isEqual(dpm.getLiquidVolume(), initialLiquidVolume, 1e-14),
                          "Liquid Volume not conserved (%!=%)", dpm.getLiquidVolume(), initialLiquidVolume);
     logger(INFO,"Testing rupture");
     //move particles, causing a rupture
     {
         BaseParticle* p = dpm.particleHandler.getObject(0);
         p->setPosition({3,0,0});
     }
     //solve should cause a bridge to rupture
     dpm.setRestarted(true);
     dpm.setTimeMax(2.0*dpm.getTimeMax());
     dpm.printTime();
     dpm.solve();
     logger.assert_always(isEqual(dpm.getLiquidVolume(), initialLiquidVolume, 1e-14),
                          "Liquid Volume not conserved (%!=%)", dpm.getLiquidVolume(), initialLiquidVolume);
     return 0;
 }
References b, DPMBase::boundaryHandler, BaseHandler< T >::copyAndAddObject(), e(), BaseHandler< T >::getLastObject(), LiquidMigrationPeriodicBoundaryInteraction::getLiquidVolume(), BaseHandler< T >::getObject(), DPMBase::getTimeMax(), DPMBase::getTimeStep(), INFO, isEqual(), logger, p, DPMBase::particleHandler, constants::pi, Eigen::ArrayBase< Derived >::pow(), LiquidMigrationPeriodicBoundaryInteraction::printTime(), s, DPMBase::setGravity(), DPMBase::setMax(), DPMBase::setMin(), DPMBase::setName(), DPMBase::setRestarted(), DPMBase::setSaveCount(), DPMBase::setTimeMax(), DPMBase::setTimeStep(), DPMBase::solve(), and DPMBase::speciesHandler.