MercuryDPM: Eigen::NoAlias< ExpressionType, StorageBase > Class Template Reference
Eigen::NoAlias< ExpressionType, StorageBase > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
Pseudo expression providing an operator = assuming no aliasing.
#include <NoAlias.h>
Public Types
typedef ExpressionType::Scalar Scalar
Public Member Functions
EIGEN_DEVICE_FUNC NoAlias (ExpressionType &expression)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ExpressionType & operator= (const StorageBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ExpressionType & operator+= (const StorageBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ExpressionType & operator-= (const StorageBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC ExpressionType & expression () const
Protected Attributes
ExpressionType & m_expression
Detailed Description
template<typename ExpressionType, template< typename > class StorageBase>
class Eigen::NoAlias< ExpressionType, StorageBase >
Pseudo expression providing an operator = assuming no aliasing.
Template Parameters
ExpressionType the type of the object on which to do the lazy assignment
This class represents an expression with special assignment operators assuming no aliasing between the target expression and the source expression. More precisely it alloas to bypass the EvalBeforeAssignBit flag of the source expression. It is the return type of MatrixBase::noalias() and most of the time this is the only way it is used.
See also
MatrixBase::noalias()
Member Typedef Documentation
Scalar
template<typename ExpressionType , template< typename > class StorageBase> typedef ExpressionType::Scalar Eigen::NoAlias< ExpressionType, StorageBase >::Scalar
Constructor & Destructor Documentation
NoAlias()
template<typename ExpressionType , template< typename > class StorageBase> EIGEN_DEVICE_FUNC Eigen::NoAlias< ExpressionType, StorageBase >::NoAlias (ExpressionType & expression) inline explicit
 : m_expression(expression) {}
Member Function Documentation
expression()
template<typename ExpressionType , template< typename > class StorageBase> EIGEN_DEVICE_FUNC ExpressionType& Eigen::NoAlias< ExpressionType, StorageBase >::expression () const inline
 { return m_expression; }
References Eigen::NoAlias< ExpressionType, StorageBase >::m_expression.
Referenced by Eigen::internal::call_assignment(), Eigen::internal::call_restricted_packet_assignment(), and Eigen::copy_using_evaluator().
operator+=()
template<typename ExpressionType , template< typename > class StorageBase> template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ExpressionType& Eigen::NoAlias< ExpressionType, StorageBase >::operator+= (const StorageBase< OtherDerived > & other) inline
{
     call_assignment_no_alias(m_expression, other.derived(),
                              internal::add_assign_op<Scalar, typename OtherDerived::Scalar>());
     return m_expression;
   }
References Eigen::internal::call_assignment_no_alias(), and Eigen::NoAlias< ExpressionType, StorageBase >::m_expression.
operator-=()
template<typename ExpressionType , template< typename > class StorageBase> template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ExpressionType& Eigen::NoAlias< ExpressionType, StorageBase >::operator-= (const StorageBase< OtherDerived > & other) inline
{
     call_assignment_no_alias(m_expression, other.derived(),
                              internal::sub_assign_op<Scalar, typename OtherDerived::Scalar>());
     return m_expression;
   }
References Eigen::internal::call_assignment_no_alias(), and Eigen::NoAlias< ExpressionType, StorageBase >::m_expression.
operator=()
template<typename ExpressionType , template< typename > class StorageBase> template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ExpressionType& Eigen::NoAlias< ExpressionType, StorageBase >::operator= (const StorageBase< OtherDerived > & other) inline
{
     call_assignment_no_alias(m_expression, other.derived(),
                              internal::assign_op<Scalar, typename OtherDerived::Scalar>());
     return m_expression;
   }
References Eigen::internal::call_assignment_no_alias(), and Eigen::NoAlias< ExpressionType, StorageBase >::m_expression.
Member Data Documentation
m_expression
template<typename ExpressionType , template< typename > class StorageBase> ExpressionType& Eigen::NoAlias< ExpressionType, StorageBase >::m_expression protected
Referenced by Eigen::NoAlias< ExpressionType, StorageBase >::expression(), Eigen::NoAlias< ExpressionType, StorageBase >::operator+=(), Eigen::NoAlias< ExpressionType, StorageBase >::operator-=(), and Eigen::NoAlias< ExpressionType, StorageBase >::operator=().
The documentation for this class was generated from the following file:
NoAlias.h