MercuryDPM: ContactProblem< ELEMENT > Class Template Reference
ContactProblem< ELEMENT > Class Template Reference
Problem class.
Public Member Functions
ContactProblem ()
Constructor.
~ContactProblem ()
Destructor (empty)
void actions_before_implicit_timestep ()
Actions before timestep.
void actions_after_newton_solve ()
Update the problem specs after solve (empty)
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_before_adapt ()
Actions before adapt: wipe contact elements.
void actions_after_adapt ()
void switch_to_displ_control ()
Switch to displ control.
void switch_to_force_control ()
Switch to force control.
void doc_solution ()
Doc the solution.
ContactProblem ()
Constructor.
~ContactProblem ()
Destructor (empty)
void actions_after_newton_solve ()
Update the problem specs after solve (empty)
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_before_adapt ()
Actions before adapt: wipe contact elements.
void actions_after_adapt ()
void switch_to_displ_control ()
Switch to displ control.
void switch_to_force_control ()
Switch to force control.
void doc_solution ()
Doc the solution.
ContactProblem ()
Constructor.
~ContactProblem ()
Destructor (empty)
void actions_after_newton_solve ()
Update the problem specs after solve (empty)
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_before_implicit_timestep ()
Actions before next timestep.
void actions_before_adapt ()
Actions before adapt: wipe contact elements.
void actions_after_adapt ()
void doc_solution ()
Doc the solution.
double global_temporal_error_norm ()
Dummy global error norm for adaptive time-stepping.
ContactProblem ()
Constructor.
~ContactProblem ()
Destructor (empty)
void actions_after_newton_solve ()
Update the problem specs after solve (empty)
void actions_before_newton_solve ()
Update the problem specs before solve (empty)
void actions_before_adapt ()
Actions before adapt: wipe contact elements.
void actions_after_adapt ()
void switch_to_displ_control ()
Switch to displ control.
void switch_to_force_control ()
Switch to force control.
void doc_solution ()
Doc the solution.
Public Member Functions inherited from oomph::Problem
virtual void debug_hook_fct (const unsigned &i)
void set_analytic_dparameter (double *const &parameter_pt)
void unset_analytic_dparameter (double *const &parameter_pt)
bool is_dparameter_calculated_analytically (double *const &parameter_pt)
void set_analytic_hessian_products ()
void unset_analytic_hessian_products ()
bool are_hessian_products_calculated_analytically ()
void set_pinned_values_to_zero ()
bool distributed () const
OomphCommunicator * communicator_pt ()
access function to the oomph-lib communicator
const OomphCommunicator * communicator_pt () const
access function to the oomph-lib communicator, const version
Problem ()
Problem (const Problem &dummy)=delete
Broken copy constructor.
void operator= (const Problem &)=delete
Broken assignment operator.
virtual ~Problem ()
Virtual destructor to clean up memory.
Mesh *& mesh_pt ()
Return a pointer to the global mesh.
Mesh *const & mesh_pt () const
Return a pointer to the global mesh (const version)
Mesh *& mesh_pt (const unsigned &imesh)
Mesh *const & mesh_pt (const unsigned &imesh) const
Return a pointer to the i-th submesh (const version)
unsigned nsub_mesh () const
Return number of submeshes.
unsigned add_sub_mesh (Mesh *const &mesh_pt)
void flush_sub_meshes ()
void build_global_mesh ()
void rebuild_global_mesh ()
LinearSolver *& linear_solver_pt ()
Return a pointer to the linear solver object.
LinearSolver *const & linear_solver_pt () const
Return a pointer to the linear solver object (const version)
LinearSolver *& mass_matrix_solver_for_explicit_timestepper_pt ()
LinearSolver * mass_matrix_solver_for_explicit_timestepper_pt () const
EigenSolver *& eigen_solver_pt ()
Return a pointer to the eigen solver object.
EigenSolver *const & eigen_solver_pt () const
Return a pointer to the eigen solver object (const version)
Time *& time_pt ()
Return a pointer to the global time object.
Time * time_pt () const
Return a pointer to the global time object (const version).
double & time ()
Return the current value of continuous time.
double time () const
Return the current value of continuous time (const version)
TimeStepper *& time_stepper_pt ()
const TimeStepper * time_stepper_pt () const
TimeStepper *& time_stepper_pt (const unsigned &i)
Return a pointer to the i-th timestepper.
ExplicitTimeStepper *& explicit_time_stepper_pt ()
Return a pointer to the explicit timestepper.
unsigned long set_timestepper_for_all_data (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data=false)
virtual void shift_time_values ()
Shift all values along to prepare for next timestep.
AssemblyHandler *& assembly_handler_pt ()
Return a pointer to the assembly handler object.
AssemblyHandler *const & assembly_handler_pt () const
Return a pointer to the assembly handler object (const version)
double & minimum_dt ()
Access function to min timestep in adaptive timestepping.
double & maximum_dt ()
Access function to max timestep in adaptive timestepping.
unsigned & max_newton_iterations ()
Access function to max Newton iterations before giving up.
void problem_is_nonlinear (const bool &prob_lin)
Access function to Problem_is_nonlinear.
double & max_residuals ()
bool & time_adaptive_newton_crash_on_solve_fail ()
Access function for Time_adaptive_newton_crash_on_solve_fail.
double & newton_solver_tolerance ()
void add_time_stepper_pt (TimeStepper *const &time_stepper_pt)
void set_explicit_time_stepper_pt (ExplicitTimeStepper *const &explicit_time_stepper_pt)
void initialise_dt (const double &dt)
void initialise_dt (const Vector< double > &dt)
Data *& global_data_pt (const unsigned &i)
Return a pointer to the the i-th global data object.
void add_global_data (Data *const &global_data_pt)
void flush_global_data ()
LinearAlgebraDistribution *const & dof_distribution_pt () const
Return the pointer to the dof distribution (read-only)
unsigned long ndof () const
Return the number of dofs.
unsigned ntime_stepper () const
Return the number of time steppers.
unsigned nglobal_data () const
Return the number of global data values.
unsigned self_test ()
Self-test: Check meshes and global data. Return 0 for OK.
void enable_store_local_dof_pt_in_elements ()
void disable_store_local_dof_pt_in_elements ()
unsigned long assign_eqn_numbers (const bool &assign_local_eqn_numbers=true)
void describe_dofs (std::ostream &out= *(oomph_info.stream_pt())) const
void enable_discontinuous_formulation ()
void disable_discontinuous_formulation ()
void get_dofs (DoubleVector &dofs) const
void get_dofs (const unsigned &t, DoubleVector &dofs) const
Return vector of the t'th history value of all dofs.
void set_dofs (const DoubleVector &dofs)
Set the values of the dofs.
void set_dofs (const unsigned &t, DoubleVector &dofs)
Set the history values of the dofs.
void set_dofs (const unsigned &t, Vector< double * > &dof_pt)
void add_to_dofs (const double &lambda, const DoubleVector &increment_dofs)
Add lambda x incremenet_dofs[l] to the l-th dof.
double * global_dof_pt (const unsigned &i)
double & dof (const unsigned &i)
i-th dof in the problem
double dof (const unsigned &i) const
i-th dof in the problem (const version)
double *& dof_pt (const unsigned &i)
Pointer to i-th dof in the problem.
double * dof_pt (const unsigned &i) const
Pointer to i-th dof in the problem (const version)
virtual void get_inverse_mass_matrix_times_residuals (DoubleVector &Mres)
virtual void get_dvaluesdt (DoubleVector &f)
virtual void get_residuals (DoubleVector &residuals)
Get the total residuals Vector for the problem.
virtual void get_jacobian (DoubleVector &residuals, DenseDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CRDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CCDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, SumOfMatrices &jacobian)
void get_fd_jacobian (DoubleVector &residuals, DenseMatrix< double > &jacobian)
Get the full Jacobian by finite differencing.
void get_derivative_wrt_global_parameter (double *const &parameter_pt, DoubleVector &result)
void get_hessian_vector_products (DoubleVectorWithHaloEntries const &Y, Vector< DoubleVectorWithHaloEntries > const &C, Vector< DoubleVectorWithHaloEntries > &product)
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, Vector< DoubleVector > &eigenvector, const bool &steady=true)
Solve the eigenproblem.
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, const bool &steady=true)
virtual void get_eigenproblem_matrices (CRDoubleMatrix &mass_matrix, CRDoubleMatrix &main_matrix, const double &shift=0.0)
void assign_eigenvector_to_dofs (DoubleVector &eigenvector)
Assign the eigenvector passed to the function to the dofs.
void add_eigenvector_to_dofs (const double &epsilon, const DoubleVector &eigenvector)
void store_current_dof_values ()
Store the current values of the degrees of freedom.
void restore_dof_values ()
Restore the stored values of the degrees of freedom.
void enable_jacobian_reuse ()
void disable_jacobian_reuse ()
Disable recycling of Jacobian in Newton iteration.
bool jacobian_reuse_is_enabled ()
Is recycling of Jacobian in Newton iteration enabled?
bool & use_predictor_values_as_initial_guess ()
void newton_solve ()
Use Newton method to solve the problem.
void enable_globally_convergent_newton_method ()
enable globally convergent Newton method
void disable_globally_convergent_newton_method ()
disable globally convergent Newton method
void newton_solve (unsigned const &max_adapt)
void steady_newton_solve (unsigned const &max_adapt=0)
void copy (Problem *orig_problem_pt)
virtual Problem * make_copy ()
virtual void read (std::ifstream &restart_file, bool &unsteady_restart)
virtual void read (std::ifstream &restart_file)
virtual void dump (std::ofstream &dump_file) const
void dump (const std::string &dump_file_name) const
void delete_all_external_storage ()
virtual void symmetrise_eigenfunction_for_adaptive_pitchfork_tracking ()
double * bifurcation_parameter_pt () const
void get_bifurcation_eigenfunction (Vector< DoubleVector > &eigenfunction)
void activate_fold_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const DoubleVector &normalisation, const bool &block_solve=true)
void activate_pitchfork_tracking (double *const &parameter_pt, const DoubleVector &symmetry_vector, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const double &omega, const DoubleVector &null_real, const DoubleVector &null_imag, const bool &block_solve=true)
void deactivate_bifurcation_tracking ()
void reset_assembly_handler_to_default ()
Reset the system to the standard non-augemented state.
double arc_length_step_solve (double *const &parameter_pt, const double &ds, const unsigned &max_adapt=0)
double arc_length_step_solve (Data *const &data_pt, const unsigned &data_index, const double &ds, const unsigned &max_adapt=0)
void reset_arc_length_parameters ()
int & sign_of_jacobian ()
void explicit_timestep (const double &dt, const bool &shift_values=true)
Take an explicit timestep of size dt.
void unsteady_newton_solve (const double &dt)
void unsteady_newton_solve (const double &dt, const bool &shift_values)
void unsteady_newton_solve (const double &dt, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const unsigned &suppress_resolve_after_spatial_adapt_flag, const bool &first, const bool &shift=true)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon, const bool &shift_values)
void assign_initial_values_impulsive ()
void assign_initial_values_impulsive (const double &dt)
void calculate_predictions ()
Calculate predictions.
void enable_mass_matrix_reuse ()
void disable_mass_matrix_reuse ()
bool mass_matrix_reuse_is_enabled ()
Return whether the mass matrix is being reused.
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly (DocInfo &doc_info)
void refine_uniformly_and_prune (DocInfo &doc_info)
void refine_uniformly ()
void refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform refinement for submesh i_mesh with documentation.
void refine_uniformly (const unsigned &i_mesh)
Do uniform refinement for submesh i_mesh without documentation.
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly (DocInfo &doc_info)
void p_refine_uniformly_and_prune (DocInfo &doc_info)
void p_refine_uniformly ()
void p_refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-refinement for submesh i_mesh with documentation.
void p_refine_uniformly (const unsigned &i_mesh)
Do uniform p-refinement for submesh i_mesh without documentation.
void refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const unsigned &i_mesh, const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void refine_selected_elements (const Vector< Vector< RefineableElement * >> &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void p_refine_selected_elements (const Vector< Vector< PRefineableElement * >> &elements_to_be_refined_pt)
unsigned unrefine_uniformly ()
unsigned unrefine_uniformly (const unsigned &i_mesh)
void p_unrefine_uniformly (DocInfo &doc_info)
void p_unrefine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-unrefinement for submesh i_mesh without documentation.
void adapt (unsigned &n_refined, unsigned &n_unrefined)
void adapt ()
void p_adapt (unsigned &n_refined, unsigned &n_unrefined)
void p_adapt ()
void adapt_based_on_error_estimates (unsigned &n_refined, unsigned &n_unrefined, Vector< Vector< double >> &elemental_error)
void adapt_based_on_error_estimates (Vector< Vector< double >> &elemental_error)
void get_all_error_estimates (Vector< Vector< double >> &elemental_error)
void doc_errors (DocInfo &doc_info)
Get max and min error for all elements in submeshes.
void doc_errors ()
Get max and min error for all elements in submeshes.
void enable_info_in_newton_solve ()
void disable_info_in_newton_solve ()
Disable the output of information when in the newton solver.
Public Member Functions inherited from oomph::ExplicitTimeSteppableObject
ExplicitTimeSteppableObject ()
Empty constructor.
ExplicitTimeSteppableObject (const ExplicitTimeSteppableObject &)=delete
Broken copy constructor.
void operator= (const ExplicitTimeSteppableObject &)=delete
Broken assignment operator.
virtual ~ExplicitTimeSteppableObject ()
Empty destructor.
virtual void actions_before_explicit_stage ()
virtual void actions_after_explicit_stage ()
Private Types
enum {
Bottom_boundary_id , Right_boundary_id , Contact_boundary_id , Left_boundary_id ,
Right_top_boundary_id , Left_top_boundary_id , Boulder_top_boundary_id , Boulder_bottom_boundary_id
}
enum {
Bottom_boundary_id , Right_boundary_id , Contact_boundary_id , Left_boundary_id ,
Right_top_boundary_id , Left_top_boundary_id
}
Private Member Functions
void create_displ_imposition_elements ()
void delete_displ_imposition_elements ()
void create_contact_heat_elements_on_boulder ()
Create "contact" heat flux elements on surface of boulder.
void create_imposed_heat_flux_elements_on_boulder ()
Create imposed heat flux elements on surface of boulder.
void create_contact_elements ()
Create contact elements.
void delete_contact_elements ()
Delete contact elements.
void complete_problem_setup ()
void create_displ_imposition_elements ()
void delete_displ_imposition_elements ()
void create_contact_elements ()
Create contact elements.
void delete_contact_elements ()
Delete contact elements.
void complete_problem_setup ()
void create_contact_elements ()
Create contact elements.
void delete_contact_elements ()
Delete contact elements.
void complete_problem_setup ()
void create_contact_elements ()
Create contact elements.
void delete_contact_elements ()
Delete contact elements.
void complete_problem_setup ()
Private Attributes
RefineableTriangleMesh< ProjectableUnsteadyHeatElement< TUnsteadyHeatElement< 2, 3 > > > * Boulder_mesh_pt
Pointer to boulder mesh.
RefineableSolidTriangleMesh< ELEMENT > * Bulk_mesh_pt
Pointer to bulk mesh.
Mesh * Surface_contact_mesh_pt
Pointer to the "surface" contact mesh.
SolidMesh * Displ_imposition_mesh_pt
Mesh * Boulder_surface_heat_flux_mesh_pt
Mesh of elements that imposed unit heat flux on top of boulder.
Mesh * Penetrator_mesh_pt
Penetrator mesh.
Mesh * Boulder_surface_contact_mesh_pt
ofstream Trace_file
Trace file.
DocInfo Doc_info
BackupMeshForProjection< TElement< 1, 3 > > * Backed_up_surface_contact_mesh_pt
SolidNode * Control_node_pt
double Xc_old
x coordinate of old control node
unsigned Contact_id
double X_ll
x coordinate of lower left corner
double X_ur
x coordinate of upper right corner
double Y_ll
y coordinate of lower left corner
double Y_ur
y coordinate of upper right corner
TriangleMeshPolyLine * Contact_boundary_pt
Contact boundary in its poly line representation.
double Maximum_element_length_on_contact_boundary
Max. element length on contact boundary.
double Maximum_element_length_on_boulder_boundary
unsigned Contact_boundary_id
ID of contact boundary.
unsigned Bottom_boundary_id
ID of bottom boundary.
unsigned Left_boundary_id
ID of left boundary.
unsigned Right_boundary_id
ID of right boundary.
unsigned Left_top_boundary_id
ID of top left boundary.
unsigned Right_top_boundary_id
ID of top right boundary.
Additional Inherited Members
Public Types inherited from oomph::Problem
typedef void(* SpatialErrorEstimatorFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error)
Function pointer for spatial error estimator.
typedef void(* SpatialErrorEstimatorWithDocFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error, DocInfo &doc_info)
Function pointer for spatial error estimator with doc.
Public Attributes inherited from oomph::Problem
bool Shut_up_in_newton_solve
Static Public Attributes inherited from oomph::Problem
static bool Suppress_warning_about_actions_before_read_unstructured_meshes
Protected Types inherited from oomph::Problem
enum Assembly_method {
Perform_assembly_using_vectors_of_pairs , Perform_assembly_using_two_vectors , Perform_assembly_using_maps , Perform_assembly_using_lists ,
Perform_assembly_using_two_arrays
}
Enumerated flags to determine which sparse assembly method is used.
Protected Member Functions inherited from oomph::Problem
unsigned setup_element_count_per_dof ()
virtual void sparse_assemble_row_or_column_compressed (Vector< int * > &column_or_row_index, Vector< int * > &row_or_column_start, Vector< double * > &value, Vector< unsigned > &nnz, Vector< double * > &residual, bool compressed_row_flag)
virtual void actions_before_newton_convergence_check ()
virtual void actions_before_newton_step ()
virtual void actions_after_newton_step ()
virtual void actions_after_implicit_timestep ()
virtual void actions_after_implicit_timestep_and_error_estimation ()
virtual void actions_before_explicit_timestep ()
Actions that should be performed before each explicit time step.
virtual void actions_after_explicit_timestep ()
Actions that should be performed after each explicit time step.
virtual void actions_before_read_unstructured_meshes ()
virtual void actions_after_read_unstructured_meshes ()
virtual void actions_after_change_in_global_parameter (double *const &parameter_pt)
virtual void actions_after_change_in_bifurcation_parameter ()
virtual void actions_after_parameter_increase (double *const &parameter_pt)
double & dof_derivative (const unsigned &i)
double & dof_current (const unsigned &i)
virtual void set_initial_condition ()
unsigned newton_solve_continuation (double *const &parameter_pt)
unsigned newton_solve_continuation (double *const &parameter_pt, DoubleVector &z)
void calculate_continuation_derivatives (double *const &parameter_pt)
void calculate_continuation_derivatives (const DoubleVector &z)
void calculate_continuation_derivatives_fd (double *const &parameter_pt)
bool does_pointer_correspond_to_problem_data (double *const &parameter_pt)
void set_consistent_pinned_values_for_continuation ()
Protected Attributes inherited from oomph::Problem
Vector< Problem * > Copy_of_problem_pt
std::map< double *, bool > Calculate_dparameter_analytic
bool Calculate_hessian_products_analytic
LinearAlgebraDistribution * Dof_distribution_pt
Vector< double * > Dof_pt
Vector of pointers to dofs.
DoubleVectorWithHaloEntries Element_count_per_dof
double Relaxation_factor
double Newton_solver_tolerance
unsigned Max_newton_iterations
Maximum number of Newton iterations.
unsigned Nnewton_iter_taken
Vector< double > Max_res
Maximum residuals at start and after each newton iteration.
double Max_residuals
bool Time_adaptive_newton_crash_on_solve_fail
bool Jacobian_reuse_is_enabled
Is re-use of Jacobian in Newton iteration enabled? Default: false.
bool Jacobian_has_been_computed
bool Problem_is_nonlinear
bool Pause_at_end_of_sparse_assembly
bool Doc_time_in_distribute
unsigned Sparse_assembly_method
unsigned Sparse_assemble_with_arrays_initial_allocation
unsigned Sparse_assemble_with_arrays_allocation_increment
Vector< Vector< unsigned > > Sparse_assemble_with_arrays_previous_allocation
double Numerical_zero_for_sparse_assembly
double FD_step_used_in_get_hessian_vector_products
bool Mass_matrix_reuse_is_enabled
bool Mass_matrix_has_been_computed
bool Discontinuous_element_formulation
double Minimum_dt
Minimum desired dt: if dt falls below this value, exit.
double Maximum_dt
Maximum desired dt.
double DTSF_max_increase
double DTSF_min_decrease
double Minimum_dt_but_still_proceed
bool Scale_arc_length
Boolean to control whether arc-length should be scaled.
double Desired_proportion_of_arc_length
Proportion of the arc-length to taken by the parameter.
double Theta_squared
int Sign_of_jacobian
Storage for the sign of the global Jacobian.
double Continuation_direction
double Parameter_derivative
Storage for the derivative of the global parameter wrt arc-length.
double Parameter_current
Storage for the present value of the global parameter.
bool Use_continuation_timestepper
Boolean to control original or new storage of dof stuff.
unsigned Dof_derivative_offset
unsigned Dof_current_offset
Vector< double > Dof_derivative
Storage for the derivative of the problem variables wrt arc-length.
Vector< double > Dof_current
Storage for the present values of the variables.
double Ds_current
Storage for the current step value.
unsigned Desired_newton_iterations_ds
double Minimum_ds
Minimum desired value of arc-length.
bool Bifurcation_detection
Boolean to control bifurcation detection via determinant of Jacobian.
bool Bisect_to_find_bifurcation
Boolean to control wheter bisection is used to located bifurcation.
bool First_jacobian_sign_change
Boolean to indicate whether a sign change has occured in the Jacobian.
bool Arc_length_step_taken
Boolean to indicate whether an arc-length step has been taken.
bool Use_finite_differences_for_continuation_derivatives
OomphCommunicator * Communicator_pt
The communicator for this problem.
bool Always_take_one_newton_step
double Timestep_reduction_factor_after_nonconvergence
bool Keep_temporal_error_below_tolerance
Static Protected Attributes inherited from oomph::Problem
static ContinuationStorageScheme Continuation_time_stepper
Storage for the single static continuation timestorage object.
Detailed Description
template<class ELEMENT>
class ContactProblem< ELEMENT >
Problem class.
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Member Enumeration Documentation
anonymous enum
template<class ELEMENT > anonymous enum private
Enumerator
Bottom_boundary_id
ID of bottom boundary.
Right_boundary_id
ID of right boundary.
Contact_boundary_id
ID of contact boundary.
Left_boundary_id
ID of left boundary.
Right_top_boundary_id
Left_top_boundary_id
Boulder_top_boundary_id
Boulder_bottom_boundary_id
      {
   Bottom_boundary_id,
   Right_boundary_id,
   Contact_boundary_id,
   Left_boundary_id,
   Right_top_boundary_id,
   Left_top_boundary_id,
   Boulder_top_boundary_id,
   Boulder_bottom_boundary_id
  };
anonymous enum
template<class ELEMENT > anonymous enum private
Enumerator
Bottom_boundary_id
ID of bottom boundary.
Right_boundary_id
ID of right boundary.
Contact_boundary_id
ID of contact boundary.
Left_boundary_id
ID of left boundary.
Right_top_boundary_id
Left_top_boundary_id
      {
   Bottom_boundary_id,
   Right_boundary_id,
   Contact_boundary_id,
   Left_boundary_id,
   Right_top_boundary_id,
   Left_top_boundary_id
  };
Constructor & Destructor Documentation
ContactProblem() [1/4]
template<class ELEMENT > ContactProblem< ELEMENT >::ContactProblem
Constructor.
Constructor for contact problem in square domain.
 {
  // Allow for crap initial guess or convergence problems...
  Problem::Max_newton_iterations=50;
  // Initialise
  Control_node_pt=0;
  // Initialise x coordinate of old control node (will be overwritten
  // when needed)
  Xc_old=0.0;
  // ID of additional nodal values created by contact elements to store
  // contact pressure/Lagr. mult.
  Contact_id=1;
  // Initialise
  Backed_up_surface_contact_mesh_pt=0;
  // Output directory
  Doc_info.set_directory("RESLT");
  // Output number
  Doc_info.number()=0;
  // Open trace file
  Trace_file.open("RESLT/trace.dat");
  // Set boundaries of domain
  X_ll=0.0;;
  X_ur=1.0;
  Y_ll=0.0;
  Y_ur=1.0;
  // Allocate the timestepper -- this constructs the Problem's
  // time object with a sufficient amount of storage to store the
  // previous timsteps.
  add_time_stepper_pt(new NewmarkBDF<2>);
  // Create boulder mesh
  //--------------------
  // Create circle representing outer boundary
  Circle* boulder_boundary_circle_pt=new Circle(ProblemParameters::Centre[0],
                                                ProblemParameters::Centre[1],
                                                ProblemParameters::Radius);
  // Provide storage for pointers to the two parts of the curvilinear boundary
  Vector<TriangleMeshCurveSection*> boulder_outer_curvilinear_boundary_pt(2);
  // First bit
  double zeta_start=0.0;
  double zeta_end=MathematicalConstants::Pi;
  unsigned n_seg_boulder=1000;
  boulder_outer_curvilinear_boundary_pt[0]=new TriangleMeshCurviLine(
   boulder_boundary_circle_pt,zeta_start,zeta_end,n_seg_boulder,
   Boulder_top_boundary_id);
  // Second bit
  zeta_start=MathematicalConstants::Pi;
  zeta_end=2.0*MathematicalConstants::Pi;
  boulder_outer_curvilinear_boundary_pt[1]=new TriangleMeshCurviLine(
   boulder_boundary_circle_pt,zeta_start,zeta_end,n_seg_boulder,
   Boulder_bottom_boundary_id);
  // Combine to curvilinear boundary and define the
  // outer boundary
  TriangleMeshClosedCurve* boulder_outer_boundary_pt=
   new TriangleMeshClosedCurve(boulder_outer_curvilinear_boundary_pt);
  // Use the TriangleMeshParameters object for helping on the manage
  // of the TriangleMesh parameters. The only parameter that needs to take
  // is the outer boundary.
  TriangleMeshParameters boulder_triangle_mesh_parameters(
   boulder_outer_boundary_pt);
  // Target element size in boulder mesh
  boulder_triangle_mesh_parameters.element_area() =
   ProblemParameters::El_area;
  // Build boulder mesh
  Boulder_mesh_pt=new RefineableTriangleMesh<
   ProjectableUnsteadyHeatElement
   <TUnsteadyHeatElement<2,3> > >(
    boulder_triangle_mesh_parameters,
    time_stepper_pt());
  // Set error estimator for bulk mesh
  Z2ErrorEstimator* boulder_error_estimator_pt=new Z2ErrorEstimator;
  Boulder_mesh_pt->spatial_error_estimator_pt()=boulder_error_estimator_pt;
  // Set element size limits (faire: just uncommented both of these)
  Boulder_mesh_pt->max_element_size()=ProblemParameters::El_area;
  Boulder_mesh_pt->min_element_size()=0.1*ProblemParameters::El_area;
 #ifdef STRUCTURED_MESH
  // Create the mesh
  // # of elements in x-direction
  unsigned n_x=11;
  // # of elements in y-direction
  unsigned n_y=10;
  // Domain length in x-direction
  double l_x=1.0;
  // Domain length in y-direction
  double l_y=1.0;
  //Now create the mesh
  Bulk_mesh_pt = new ElasticRefineableRectangularQuadMesh<ELEMENT>
   (n_x,n_y,l_x,l_y,time_stepper_pt());
 #else
  // Pointer to the closed curve that defines the outer boundary
  TriangleMeshClosedCurve* closed_curve_pt=0;
  // Build outer boundary as Polygon
  // The boundary is bounded by five distinct boundaries, each
  // represented by its own polyline
  Vector<TriangleMeshCurveSection*> boundary_polyline_pt(6);
  // Vertex coordinates on boundary
  Vector<Vector<double> > bound_coords(2);
  // Left boundary
  bound_coords[0].resize(2);
  bound_coords[0][0]=X_ll;
  bound_coords[0][1]=Y_ur;
  bound_coords[1].resize(2);
  bound_coords[1][0]=X_ll;
  bound_coords[1][1]=Y_ll;
  // Build the boundary polyline
  boundary_polyline_pt[0]=new TriangleMeshPolyLine(bound_coords,
                                                   Left_boundary_id);
  // Bottom boundary
  bound_coords[0].resize(2);
  bound_coords[0][0]=X_ll;
  bound_coords[0][1]=Y_ll;
  bound_coords[1].resize(2);
  bound_coords[1][0]=X_ur;
  bound_coords[1][1]=Y_ll;
  // Build the boundary polyline
  boundary_polyline_pt[1]=new TriangleMeshPolyLine(bound_coords,
                                                   Bottom_boundary_id);
  // Right boundary
  bound_coords[0].resize(2);
  bound_coords[0][0]=X_ur;
  bound_coords[0][1]=Y_ll;
  bound_coords[1].resize(2);
  bound_coords[1][0]=X_ur;
  bound_coords[1][1]=Y_ur;
  // Build the boundary polyline
  boundary_polyline_pt[2]=new TriangleMeshPolyLine(bound_coords,
                                                   Right_boundary_id);
  // Right top boundary
  unsigned npt_right=10;
  Vector<Vector<double> > right_top_bound_coords(npt_right);
  right_top_bound_coords[0].resize(2);
  right_top_bound_coords[0][0]=X_ur;
  right_top_bound_coords[0][1]=Y_ur;
  for (unsigned j=1;j<npt_right;j++)
   {
    right_top_bound_coords[j].resize(2);
    double x=X_ur-(X_ur-ProblemParameters::X_contact_end_right)*double(j)/
     double(npt_right-1);
    double y=Y_ur;
    right_top_bound_coords[j][0]=x;
    right_top_bound_coords[j][1]=y;
   }
  // Build boundary poly line
  TriangleMeshPolyLine* right_top_boundary_pt=
   new TriangleMeshPolyLine(right_top_bound_coords,
                            Right_top_boundary_id);
  boundary_polyline_pt[3]=right_top_boundary_pt;
  // Contact boundary
  unsigned npt_contact=200; // hierher 20;
  Vector<Vector<double> > contact_bound_coords(npt_contact);
  contact_bound_coords[0].resize(2);
  contact_bound_coords[0][0]=right_top_bound_coords[npt_right-1][0];
  contact_bound_coords[0][1]=right_top_bound_coords[npt_right-1][1];
  for (unsigned j=1;j<npt_contact;j++)
   {
    contact_bound_coords[j].resize(2);
    double x=ProblemParameters::X_contact_end_right-
     (ProblemParameters::X_contact_end_right-
      ProblemParameters::X_contact_end_left)*double(j)/double(npt_contact-1);
    double y=Y_ur;
    contact_bound_coords[j][0]=x;
    contact_bound_coords[j][1]=y;
   }
  // Build boundary poly line
  Contact_boundary_pt=
   new TriangleMeshPolyLine(contact_bound_coords,
                            Contact_boundary_id);
  boundary_polyline_pt[4]=Contact_boundary_pt;
  // Keep elements near boundary nice and small
  Maximum_element_length_on_contact_boundary=(X_ur-X_ll)/double(npt_contact);
  Contact_boundary_pt->set_maximum_length(
   Maximum_element_length_on_contact_boundary);
  // Left top boundary
  unsigned npt_left=15;
  Vector<Vector<double> > top_left_bound_coords(npt_left);
  top_left_bound_coords[0].resize(2);
  top_left_bound_coords[0][0]=contact_bound_coords[npt_contact-1][0];
  top_left_bound_coords[0][1]=contact_bound_coords[npt_contact-1][1];
  for (unsigned j=1;j<npt_left-1;j++)
   {
    top_left_bound_coords[j].resize(2);
    double x=ProblemParameters::X_contact_end_left-
     (ProblemParameters::X_contact_end_left-X_ll)*
     double(j)/double(npt_left-1);
    double y=Y_ur;
    top_left_bound_coords[j][0]=x;
    top_left_bound_coords[j][1]=y;
   }
  top_left_bound_coords[npt_left-1].resize(2);
  top_left_bound_coords[npt_left-1][0]=X_ll;
  top_left_bound_coords[npt_left-1][1]=Y_ur;
  // Build boundary poly line
  TriangleMeshPolyLine* top_left_boundary_pt=
   new TriangleMeshPolyLine(top_left_bound_coords,
                            Left_top_boundary_id);
  boundary_polyline_pt[5]=top_left_boundary_pt;
  // Create the triangle mesh polygon for outer boundary
  //----------------------------------------------------
  TriangleMeshPolygon *outer_polygon =
   new TriangleMeshPolygon(boundary_polyline_pt);
  // Set the pointer
  closed_curve_pt = outer_polygon;
  // Now build the mesh
  //===================
  // Use the TriangleMeshParameters object for helping on the manage of the
  // TriangleMesh parameters
  TriangleMeshParameters triangle_mesh_parameters(closed_curve_pt);
  // Specify the maximum area element
  double uniform_element_area=ProblemParameters::El_area;
  triangle_mesh_parameters.element_area() = uniform_element_area;
  // Create the mesh
  Bulk_mesh_pt=
   new RefineableSolidTriangleMesh<ELEMENT>(triangle_mesh_parameters,
                                            time_stepper_pt());
 #endif
 #ifdef STRUCTURED_MESH
  Vector<double> lower_left(2);
  lower_left[0]=0.3;
  lower_left[1]=0.8;
  Vector<double> upper_right(2);
  upper_right[0]=0.7;
  upper_right[1]=1.0;
  unsigned central_node_number=4;
  Bulk_mesh_pt->spatial_error_estimator_pt()=
   new DummyErrorEstimator(Bulk_mesh_pt,
                           lower_left,
                           upper_right,
                           central_node_number);
 #else
  // Set error estimator for bulk mesh
  Z2ErrorEstimator* error_estimator_pt=new Z2ErrorEstimator;
  Bulk_mesh_pt->spatial_error_estimator_pt()=error_estimator_pt;
  // Set element size limits
  Bulk_mesh_pt->max_element_size()=ProblemParameters::El_area;
  Bulk_mesh_pt->min_element_size()=0.1*ProblemParameters::El_area;
 #endif
  // Create "surface" mesh on boulder that applies contact heat flux boundary
  // condition to boulder
  Boulder_surface_contact_mesh_pt=new Mesh;
  create_contact_heat_elements_on_boulder();
  // Create "surface" mesh on boulder that applies flux boundary
  // condition to boulder
  Boulder_surface_heat_flux_mesh_pt=new Mesh;
  create_imposed_heat_flux_elements_on_boulder();
  // Create contact elements
  Surface_contact_mesh_pt=new Mesh;
  create_contact_elements();
  // Create elements that enforce prescribed boundary motion
  // by Lagrange multipliers
  Displ_imposition_mesh_pt=new SolidMesh;
  create_displ_imposition_elements();
  // Create mesh for penetrator element
  Penetrator_mesh_pt=new Mesh;
  // Set boundary condition and complete the build of all elements
  complete_problem_setup();
  // Initial assigment
  ProblemParameters::Y_c=Control_node_pt->x(1);
  // Add the sub meshes to the problem
  add_sub_mesh(Bulk_mesh_pt);
  add_sub_mesh(Surface_contact_mesh_pt);
  add_sub_mesh(Displ_imposition_mesh_pt);
  add_sub_mesh(Penetrator_mesh_pt);
  add_sub_mesh(Boulder_mesh_pt);
  add_sub_mesh(Boulder_surface_contact_mesh_pt);
  add_sub_mesh(Boulder_surface_heat_flux_mesh_pt);
  // Combine all submeshes into a single global Mesh
  build_global_mesh();
  // hierher
  //Problem::Newton_solver_tolerance=1.0e-6;
  // hierher
  //linear_solver_pt()=new FD_LU;
  // Do equation numbering
  cout <<"Number of equations: " << assign_eqn_numbers() << std::endl;
 } // end of constructor
References ProblemParameters::Centre, GlobalParameters::Doc_info, ProblemParameters::El_area, oomph::TriangleMeshParameters::element_area(), MeshRefinement::error_estimator_pt, j, oomph::Locate_zeta_helpers::Max_newton_iterations, oomph::DocInfo::number(), BiharmonicTestFunctions2::Pi, ProblemParameters::Radius, oomph::DocInfo::set_directory(), oomph::Problem_Parameter::Trace_file, plotDoE::x, ProblemParameters::X_contact_end_left, ProblemParameters::X_contact_end_right, y, and ProblemParameters::Y_c.
~ContactProblem() [1/4]
template<class ELEMENT > ContactProblem< ELEMENT >::~ContactProblem () inline
Destructor (empty)
 {}
ContactProblem() [2/4]
template<class ELEMENT > ContactProblem< ELEMENT >::ContactProblem ()
Constructor.
~ContactProblem() [2/4]
template<class ELEMENT > ContactProblem< ELEMENT >::~ContactProblem () inline
Destructor (empty)
 {}
ContactProblem() [3/4]
template<class ELEMENT > ContactProblem< ELEMENT >::ContactProblem ()
Constructor.
~ContactProblem() [3/4]
template<class ELEMENT > ContactProblem< ELEMENT >::~ContactProblem () inline
Destructor (empty)
 {}
ContactProblem() [4/4]
template<class ELEMENT > ContactProblem< ELEMENT >::ContactProblem ()
Constructor.
~ContactProblem() [4/4]
template<class ELEMENT > ContactProblem< ELEMENT >::~ContactProblem () inline
Destructor (empty)
 {}
Member Function Documentation
actions_after_adapt() [1/4]
template<class ELEMENT > void ContactProblem< ELEMENT >::actions_after_adapt () inline virtual
Actions after adapt: Setup the problem again – remember that the mesh has been completely rebuilt and its element's don't have any pointers to source fcts etc. yet
Reimplemented from oomph::Problem.
   {
    // Create "contact" heat flux elements on surface of boulder
    create_contact_heat_elements_on_boulder();
    // Create normal heat flux elements on surface of boulder
    create_imposed_heat_flux_elements_on_boulder();
    // Create contact elements
    create_contact_elements();
    // Create elements that impose displacement of melt line
    create_displ_imposition_elements();
    // Now project from backup of original contact mesh to new one
    Backed_up_surface_contact_mesh_pt->project_onto_new_mesh(
     Surface_contact_mesh_pt);
    // For maximum stability: Reset the current nodal positions to be
    // the "stress-free" ones -- this assignment means that the
    // parameter study no longer corresponds to a physical experiment
    // but is what we'd do if we wanted to use the solid solve
    // to update a fluid mesh in an FSI problem, say.
    Bulk_mesh_pt->set_lagrangian_nodal_coordinates();
    // Rebuild elements
    complete_problem_setup();
    // Rebuild the Problem's global mesh from its various sub-meshes
    rebuild_global_mesh();
    // Kill backed up mesh
    delete Backed_up_surface_contact_mesh_pt;
    Backed_up_surface_contact_mesh_pt=0;
    // Output impose displ elements
    ofstream some_file;
    char filename[100];
    sprintf(filename,"impose_after.dat");
    some_file.open(filename);
    Displ_imposition_mesh_pt->output(some_file);
    some_file.close();
   }
References ContactProblem< ELEMENT >::Backed_up_surface_contact_mesh_pt, ContactProblem< ELEMENT >::Bulk_mesh_pt, ContactProblem< ELEMENT >::complete_problem_setup(), ContactProblem< ELEMENT >::create_contact_elements(), ContactProblem< ELEMENT >::create_contact_heat_elements_on_boulder(), ContactProblem< ELEMENT >::create_displ_imposition_elements(), ContactProblem< ELEMENT >::create_imposed_heat_flux_elements_on_boulder(), ContactProblem< ELEMENT >::Displ_imposition_mesh_pt, MergeRestartFiles::filename, oomph::Mesh::output(), oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT >::project_onto_new_mesh(), oomph::Problem::rebuild_global_mesh(), and ContactProblem< ELEMENT >::Surface_contact_mesh_pt.
actions_after_adapt() [2/4]
template<class ELEMENT > void ContactProblem< ELEMENT >::actions_after_adapt () inline virtual
Actions after adapt: Setup the problem again – remember that the mesh has been completely rebuilt and its element's don't have any pointers to source fcts etc. yet
Reimplemented from oomph::Problem.
   {
    // Create contact elements
    create_contact_elements();
    // Create elements that impose displacement of melt line
    create_displ_imposition_elements();
    // Now project from backup of original contact mesh to new one
    Backed_up_surface_contact_mesh_pt->project_onto_new_mesh(
     Surface_contact_mesh_pt);
    // For maximum stability: Reset the current nodal positions to be
    // the "stress-free" ones -- this assignment means that the
    // parameter study no longer corresponds to a physical experiment
    // but is what we'd do if we wanted to use the solid solve
    // to update a fluid mesh in an FSI problem, say.
    Bulk_mesh_pt->set_lagrangian_nodal_coordinates();
    // Rebuild elements
    complete_problem_setup();
    // Rebuild the Problem's global mesh from its various sub-meshes
    rebuild_global_mesh();
    // Kill backed up mesh
    delete Backed_up_surface_contact_mesh_pt;
    Backed_up_surface_contact_mesh_pt=0;
    // Output impose displ elements
    ofstream some_file;
    char filename[100];
    sprintf(filename,"impose_after.dat");
    some_file.open(filename);
    Displ_imposition_mesh_pt->output(some_file);
    some_file.close();
   }
References MergeRestartFiles::filename.
actions_after_adapt() [3/4]
template<class ELEMENT > void ContactProblem< ELEMENT >::actions_after_adapt () inline virtual
Actions after adapt: Setup the problem again – remember that the mesh has been completely rebuilt and its element's don't have any pointers to source fcts etc. yet
Reimplemented from oomph::Problem.
   {
    // Create contact elements
    create_contact_elements();
    // Rebuild the Problem's global mesh from its various sub-meshes
    rebuild_global_mesh();
    // Rebuild elements
    complete_problem_setup();
    // Now project from backup of original contact mesh to new one
    oomph_info << "Projecting contact pressure.\n";
    Backed_up_surface_contact_mesh_pt->project_onto_new_mesh(
     Surface_contact_mesh_pt);
    // Kill backed up mesh
    delete Backed_up_surface_contact_mesh_pt;
    Backed_up_surface_contact_mesh_pt=0;
    // // Output contact elements
    // ofstream some_file;
    // char filename[100];
    // sprintf(filename,"contact_after.dat");
    // some_file.open(filename);
    // unsigned nel=Surface_contact_mesh_pt->nelement();
    // for (unsigned e=0;e<nel;e++)
    //  {
    //   dynamic_cast<NonlinearSurfaceContactElement<ELEMENT>* >(
    //    Surface_contact_mesh_pt->element_pt(e))->output(some_file);
    //  }
    // some_file.close();
    // //pause("done");
   }
References oomph::oomph_info.
actions_after_adapt() [4/4]
template<class ELEMENT > void ContactProblem< ELEMENT >::actions_after_adapt () inline virtual
Actions after adapt: Setup the problem again – remember that the mesh has been completely rebuilt and its element's don't have any pointers to source fcts etc. yet
Reimplemented from oomph::Problem.
   {
    // Create contact elements
    create_contact_elements();
    // Now project from backup of original contact mesh to new one
    Backed_up_surface_contact_mesh_pt->project_onto_new_mesh(
     Surface_contact_mesh_pt);
    // Rebuild elements
    complete_problem_setup();
    // Rebuild the Problem's global mesh from its various sub-meshes
    rebuild_global_mesh();
    // Kill backed up mesh
    delete Backed_up_surface_contact_mesh_pt;
    Backed_up_surface_contact_mesh_pt=0;
    // // Output contact elements
    // ofstream some_file;
    // char filename[100];
    // sprintf(filename,"contact_after.dat");
    // some_file.open(filename);
    // unsigned nel=Surface_contact_mesh_pt->nelement();
    // for (unsigned e=0;e<nel;e++)
    //  {
    //   dynamic_cast<NonlinearSurfaceContactElement<ELEMENT>* >(
    //    Surface_contact_mesh_pt->element_pt(e))->output(some_file);
    //  }
    // some_file.close();
   }
actions_after_newton_solve() [1/4]
template<class ELEMENT > void ContactProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update the problem specs after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [2/4]
template<class ELEMENT > void ContactProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update the problem specs after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [3/4]
template<class ELEMENT > void ContactProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update the problem specs after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [4/4]
template<class ELEMENT > void ContactProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update the problem specs after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_adapt() [1/4]
template<class ELEMENT > void ContactProblem< ELEMENT >::actions_before_adapt () inline virtual
Actions before adapt: wipe contact elements.
Reimplemented from oomph::Problem.
   {
    // Backup x coordinate of old control node
    Xc_old=Control_node_pt->x(0);
 #ifdef STRUCTURED_MESH
    // Make backup of surface mesh
    Backed_up_surface_contact_mesh_pt=
     new BackupMeshForProjection<QElement<1,3> >(Surface_contact_mesh_pt,
                                                 Contact_boundary_id);
 #else
    //double max_el_length=Maximum_element_length_on_contact_boundary*
    //ProblemParameters::Element_length_factor;
    //Impose max_el_length from el_area, ie derive average element length from El_area then
    //apply multiplier
    double max_el_length = ProblemParameters::Element_length_factor*
     (2*sqrt(sqrt(3))*sqrt(ProblemParameters::El_area));
    Bulk_mesh_pt->boundary_polyline_pt(Contact_boundary_id)
     ->set_maximum_length(max_el_length);
    Boulder_mesh_pt->boundary_polyline_pt(Boulder_bottom_boundary_id)
     ->set_maximum_length(max_el_length);
    // Make backup of surface mesh
    Backed_up_surface_contact_mesh_pt=
     new BackupMeshForProjection<TElement<1,3> >(Surface_contact_mesh_pt,
                                                 Contact_boundary_id);
 #endif
    // // Output contact elements
    // ofstream some_file;
    // char filename[100];
    // sprintf(filename,"contact_before.dat");
    // some_file.open(filename);
    // unsigned nel=Surface_contact_mesh_pt->nelement();
    // for (unsigned e=0;e<nel;e++)
    //  {
    //   dynamic_cast<HeatedLinearSurfaceContactElement<ELEMENT>* >(
    //    Surface_contact_mesh_pt->element_pt(e))->output(some_file);
    //  }
    // some_file.close();
    // Output impose displ elements
    ofstream some_file;
    char filename[100];
    sprintf(filename,"impose_before.dat");
    some_file.open(filename);
    Displ_imposition_mesh_pt->output(some_file);
    some_file.close();
    // // Kill the  elements and wipe surface mesh
    delete_contact_elements();
    delete_displ_imposition_elements();
    // Wipe the mesh
    Penetrator_mesh_pt->flush_element_and_node_storage();
    // Rebuild the Problem's global mesh from its various sub-meshes
    rebuild_global_mesh();
   }
References ContactProblem< ELEMENT >::Backed_up_surface_contact_mesh_pt, ContactProblem< ELEMENT >::Boulder_bottom_boundary_id, ContactProblem< ELEMENT >::Boulder_mesh_pt, oomph::UnstructuredTwoDMeshGeometryBase::boundary_polyline_pt(), ContactProblem< ELEMENT >::Bulk_mesh_pt, ContactProblem< ELEMENT >::Contact_boundary_id, ContactProblem< ELEMENT >::Control_node_pt, ContactProblem< ELEMENT >::delete_contact_elements(), ContactProblem< ELEMENT >::delete_displ_imposition_elements(), ContactProblem< ELEMENT >::Displ_imposition_mesh_pt, ProblemParameters::El_area, ProblemParameters::Element_length_factor, MergeRestartFiles::filename, oomph::Mesh::flush_element_and_node_storage(), oomph::Mesh::output(), ContactProblem< ELEMENT >::Penetrator_mesh_pt, oomph::Problem::rebuild_global_mesh(), oomph::TriangleMeshCurveSection::set_maximum_length(), sqrt(), ContactProblem< ELEMENT >::Surface_contact_mesh_pt, oomph::Node::x(), and ContactProblem< ELEMENT >::Xc_old.
actions_before_adapt() [2/4]
template<class ELEMENT > void ContactProblem< ELEMENT >::actions_before_adapt () inline virtual
Actions before adapt: wipe contact elements.
Reimplemented from oomph::Problem.
   {
    // Backup x coordinate of old control node
    Xc_old=Control_node_pt->x(0);
 #ifdef STRUCTURED_MESH
    // Make backup of surface mesh
    Backed_up_surface_contact_mesh_pt=
     new BackupMeshForProjection<QElement<1,3> >(Surface_contact_mesh_pt,
                                                 Contact_boundary_id);
 #else
    Bulk_mesh_pt->boundary_polyline_pt(Contact_boundary_id)->set_maximum_length(
     Maximum_element_length_on_contact_boundary*
     ProblemParameters::Element_length_factor);
    // Make backup of surface mesh
    Backed_up_surface_contact_mesh_pt=
     new BackupMeshForProjection<TElement<1,3> >(Surface_contact_mesh_pt,
                                                 Contact_boundary_id);
 #endif
    // // Output contact elements
    // ofstream some_file;
    // char filename[100];
    // sprintf(filename,"contact_before.dat");
    // some_file.open(filename);
    // unsigned nel=Surface_contact_mesh_pt->nelement();
    // for (unsigned e=0;e<nel;e++)
    //  {
    //   dynamic_cast<LinearSurfaceContactElement<ELEMENT>* >(
    //    Surface_contact_mesh_pt->element_pt(e))->output(some_file);
    //  }
    // some_file.close();
    // Output impose displ elements
    ofstream some_file;
    char filename[100];
    sprintf(filename,"impose_before.dat");
    some_file.open(filename);
    Displ_imposition_mesh_pt->output(some_file);
    some_file.close();
    // // Kill the  elements and wipe surface mesh
    delete_contact_elements();
    delete_displ_imposition_elements();
    // Wipe the mesh
    Penetrator_mesh_pt->flush_element_and_node_storage();
    // Rebuild the Problem's global mesh from its various sub-meshes
    rebuild_global_mesh();
   }
References ProblemParameters::Element_length_factor, MergeRestartFiles::filename, and oomph::Mesh::output().
actions_before_adapt() [3/4]
template<class ELEMENT > void ContactProblem< ELEMENT >::actions_before_adapt () inline virtual
Actions before adapt: wipe contact elements.
Reimplemented from oomph::Problem.
   {
    // Make backup of surface mesh
    Backed_up_surface_contact_mesh_pt=
     new BackupMeshForProjection<TElement<1,3> >(
      Surface_contact_mesh_pt,Contact_boundary_id);
    // // Output contact elements
    // ofstream some_file;
    // char filename[100];
    // sprintf(filename,"contact_before.dat");
    // some_file.open(filename);
    // unsigned nel=Surface_contact_mesh_pt->nelement();
    // for (unsigned e=0;e<nel;e++)
    //  {
    //   dynamic_cast<NonlinearSurfaceContactElement<ELEMENT>* >(
    //    Surface_contact_mesh_pt->element_pt(e))->output(some_file);
    //  }
    // some_file.close();
    // // Kill the  elements and wipe surface mesh
    delete_contact_elements();
    // Rebuild the Problem's global mesh from its various sub-meshes
    rebuild_global_mesh();
   }
actions_before_adapt() [4/4]
template<class ELEMENT > void ContactProblem< ELEMENT >::actions_before_adapt () inline virtual
Actions before adapt: wipe contact elements.
Reimplemented from oomph::Problem.
   {
    // Backup x coordinate of old control node
    Xc_old=Control_node_pt->x(0);
 #ifdef STRUCTURED_MESH
    // Make backup of surface mesh
    Backed_up_surface_contact_mesh_pt=
     new BackupMeshForProjection<QElement<1,3> >(Surface_contact_mesh_pt,
                                                 Contact_boundary_id);
 #else
    Bulk_mesh_pt->boundary_polyline_pt(Contact_boundary_id)->set_maximum_length(
     Maximum_element_length_on_contact_boundary*
     ProblemParameters::Element_length_factor);
    // Make backup of surface mesh
    Backed_up_surface_contact_mesh_pt=
     new BackupMeshForProjection<TElement<1,3> >(Surface_contact_mesh_pt,
                                                 Contact_boundary_id);
 #endif
    // // Output contact elements
    // ofstream some_file;
    // char filename[100];
    // sprintf(filename,"contact_before.dat");
    // some_file.open(filename);
    // unsigned nel=Surface_contact_mesh_pt->nelement();
    // for (unsigned e=0;e<nel;e++)
    //  {
    //   dynamic_cast<NonlinearSurfaceContactElement<ELEMENT>* >(
    //    Surface_contact_mesh_pt->element_pt(e))->output(some_file);
    //  }
    // some_file.close();
    // // Kill the  elements and wipe surface mesh
    delete_contact_elements();
    // Wipe the mesh
    Penetrator_mesh_pt->flush_element_and_node_storage();
    // Rebuild the Problem's global mesh from its various sub-meshes
    rebuild_global_mesh();
   }
References ProblemParameters::Element_length_factor.
actions_before_implicit_timestep() [1/2]
template<class ELEMENT > void ContactProblem< ELEMENT >::actions_before_implicit_timestep () inline virtual
Actions before timestep.
Reimplemented from oomph::Problem.
   {
    double dyc=0.00024;
    ProblemParameters::Centre[1]-=dyc;
    oomph_info << "Re-solving imposed circle pos for yc="
               << ProblemParameters::Centre[1]
               << std::endl;
    unsigned b=Contact_boundary_id;
    unsigned nnod=Bulk_mesh_pt->nboundary_node(b);
    for (unsigned j=0;j<nnod;j++)
     {
      SolidNode* nod_pt=Bulk_mesh_pt->boundary_node_pt(b,j);
      // hierher index read out from element, though
      // this shouldn't actually be set at all. Kill
      nod_pt->set_value(2,ProblemParameters::T_contact);
     }
   }
References b, ContactProblem< ELEMENT >::Bulk_mesh_pt, ProblemParameters::Centre, ContactProblem< ELEMENT >::Contact_boundary_id, j, oomph::oomph_info, oomph::Data::set_value(), and ProblemParameters::T_contact.
actions_before_implicit_timestep() [2/2]
template<class ELEMENT > void ContactProblem< ELEMENT >::actions_before_implicit_timestep () inline virtual
Actions before next timestep.
Reimplemented from oomph::Problem.
   {
    // Amplitude of oscillation
    double amplitude=0.1;
    // Update position of centre -- amplitude of oscillation increases
    // by 5% per period...
    double time=time_pt()->time();
    ProblemParameters::Centre[1]=ProblemParameters::Y_c_max-amplitude*
     (1.0+0.05*time)*0.5*(1.0-cos(2.0*MathematicalConstants::Pi*time));
    oomph_info << "Solving for y_c = "
               << ProblemParameters::Centre[1]
               << " for time: " << time << std::endl;
   }
References ProblemParameters::Centre, cos(), oomph::oomph_info, BiharmonicTestFunctions2::Pi, and ProblemParameters::Y_c_max.
actions_before_newton_solve() [1/4]
template<class ELEMENT > void ContactProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
   {
    // For maximum stability: Reset the current nodal positions to be
    // the "stress-free" ones -- this assignment means that the
    // parameter study no longer corresponds to a physical experiment
    // but is what we'd do if we wanted to use the solid solve
    // to update a fluid mesh in an FSI problem, say.
    Bulk_mesh_pt->set_lagrangian_nodal_coordinates();
    // DoubleVector r;
    // CRDoubleMatrix jac;
    // oomph_info << "SETTING UP JAC FOR OUTPUT OF MOST RECENT JAC\n";
    // get_jacobian(r,jac);
    // oomph_info << "DONE SETTING UP JAC FOR OUTPUT OF MOST RECENT JAC\n";
    // jac.sparse_indexed_output("most_recent_jacobian.dat");
    // ofstream descr_file;
    // descr_file.open("most_recent_description.dat");
    // describe_dofs(descr_file);
    // descr_file.close();
   }
References ContactProblem< ELEMENT >::Bulk_mesh_pt.
actions_before_newton_solve() [2/4]
template<class ELEMENT > void ContactProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
   {
    // For maximum stability: Reset the current nodal positions to be
    // the "stress-free" ones -- this assignment means that the
    // parameter study no longer corresponds to a physical experiment
    // but is what we'd do if we wanted to use the solid solve
    // to update a fluid mesh in an FSI problem, say.
    Bulk_mesh_pt->set_lagrangian_nodal_coordinates();
   }
actions_before_newton_solve() [3/4]
template<class ELEMENT > void ContactProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [4/4]
template<class ELEMENT > void ContactProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
 {}
complete_problem_setup() [1/4]
template<class ELEMENT > void ContactProblem< ELEMENT >::complete_problem_setup () inline private
Helper function to (re-)set boundary condition and complete the build of all elements
   {
    // Set (pseudo-)solid mechanics properties for all elements
    //---------------------------------------------------------
    unsigned n_element = Bulk_mesh_pt->nelement();
    for(unsigned e=0;e<n_element;e++)
     {
      //Cast to a solid element
      ELEMENT *el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(e));
      // Set the constitutive law
      el_pt->constitutive_law_pt() =
       ProblemParameters::Constitutive_law_pt;
      // Set density to zero
      el_pt->LinearElasticityEquations<2>::lambda_sq_pt()=
       &ProblemParameters::Lambda_sq;
      // Set density to zero
      el_pt->PVDEquationsBase<2>::lambda_sq_pt()=
       &ProblemParameters::Lambda_sq;
      // Set the elasticity tensor
      el_pt->elasticity_tensor_pt() = &ProblemParameters::E;
      // Disable inertia
      el_pt->LinearElasticityEquations<2>::disable_inertia();
      // Disable inertia
      el_pt->PVDEquationsBase<2>::disable_inertia();
     }
    // Apply boundary conditions for solid
    //------------------------------------
    // Bottom: completely pinned
    unsigned b=Bottom_boundary_id;
    unsigned nnod=Bulk_mesh_pt->nboundary_node(b);
    for (unsigned j=0;j<nnod;j++)
     {
      SolidNode* nod_pt=Bulk_mesh_pt->boundary_node_pt(b,j);
      nod_pt->pin_position(0);
      nod_pt->pin_position(1);
      nod_pt->pin(0);
      nod_pt->pin(1);
     }
    // Sides: Symmetry bcs
    b=Left_boundary_id;
    nnod=Bulk_mesh_pt->nboundary_node(b);
    for (unsigned j=0;j<nnod;j++)
     {
      SolidNode* nod_pt=Bulk_mesh_pt->boundary_node_pt(b,j);
      nod_pt->pin_position(0);
      nod_pt->pin(0);
     }
    b=Right_boundary_id;
    nnod=Bulk_mesh_pt->nboundary_node(b);
    for (unsigned j=0;j<nnod;j++)
     {
      SolidNode* nod_pt=Bulk_mesh_pt->boundary_node_pt(b,j);
      nod_pt->pin_position(0);
      nod_pt->pin(0);
     }
    // Enforce contact at most central or most heavily loaded node
    //------------------------------------------------------------
    {
     // Update angle?
     bool update_angle=false;
     double phi_old=0.0;
     HeatedCircularPenetratorElement* pen_el_pt=
      dynamic_cast<HeatedCircularPenetratorElement*>(
       ProblemParameters::Penetrator_pt);
     if (pen_el_pt!=0)
      {
       update_angle=true;
       phi_old=pen_el_pt->angle();
      }
     // Find closest/most loaded node
     double x_c=0.5;
     Control_node_pt=0;
     SolidNode* most_central_node_pt=0;
     SolidNode* most_loaded_node_pt=0;
     double dist_min=DBL_MAX;
     double load_max=0.0;
     unsigned b=Contact_boundary_id;
     unsigned nnod=Bulk_mesh_pt->nboundary_node(b);
     for (unsigned j=0;j<nnod;j++)
      {
       SolidNode* nod_pt=Bulk_mesh_pt->boundary_node_pt(b,j);
       // Find closest node
       double dist=std::fabs(nod_pt->x(0)-x_c);
       if (dist<dist_min)
        {
         dist_min=dist;
         most_central_node_pt=nod_pt;
        }
       // Find most loaded node
       BoundaryNodeBase *bnod_pt=dynamic_cast<BoundaryNodeBase*>(nod_pt);
       unsigned index_of_contact_pressure=
        bnod_pt->index_of_first_value_assigned_by_face_element(Contact_id);
       if (nod_pt->value(index_of_contact_pressure)>load_max)
        {
         load_max=nod_pt->value(index_of_contact_pressure);
         most_loaded_node_pt=nod_pt;
        }
      }
     // No load
     if (most_loaded_node_pt==0)
      {
       oomph_info << "Choosing most central node as control node\n";
       Control_node_pt=most_central_node_pt;
      }
     else
      {
       oomph_info << "Choosing most loaded node as control node\n";
       Control_node_pt=most_loaded_node_pt;
      }
     oomph_info << "Control node located at: "
                << Control_node_pt->x(0) << " "
                << Control_node_pt->x(1) << " "
                << std::endl;
     // Update angle
     if (update_angle)
      {
       double phi_new=asin((Xc_old-Control_node_pt->x(0))/
                           ProblemParameters::Radius+sin(phi_old));
       dynamic_cast<HeatedCircularPenetratorElement*>(
        ProblemParameters::Penetrator_pt)->set_angle(phi_new);
       oomph_info << "Old/new angle: " << phi_old << " "
                  << phi_new << std::endl;
      }
     //...............................................................
     // Set target vertical position of control node to its current
     // position. This is fine as initial assignment; it's then over-written
     // before the next solve (if the displacement is controlled).
     // If/when this function is called during adaptation it's fine too
     // because it doesn't impose another displacement increment -- it simply
     // maintains the position that was obtained on the previous solve.
     unsigned index_of_vertical_displacement=1;
     ProblemParameters::Y_c=Control_node_pt->x(1)+
      Control_node_pt->value(index_of_vertical_displacement);
     // Index of nodal value at control node that stores the traded
     // contact pressure
     unsigned index_of_traded_contact_pressure=UINT_MAX;
     // Impose position of centre when penetrator position directly imposed
     //--------------------------------------------------------------------
     if (ProblemParameters::Impose_position_of_centre)
      {
       // Delete old one
       delete ProblemParameters::Penetrator_pt;
       // Make new one
       ProblemParameters::Penetrator_pt =
        new HeatedCircularPenetrator(&ProblemParameters::Centre,
                                     ProblemParameters::Radius);
      }
     // Compute penetrator position as part of the solution, either by
     // --------------------------------------------------------------
     // prescribing nodal position or weight
     // ------------------------------------
     else //--
      {
       // Loop over face elements to identify the ones that contain
       // the control node
       unsigned nel=Surface_contact_mesh_pt->nelement();
       bool found=false;
       for (unsigned e=0;e<nel;e++)
        {
         HeatedLinearSurfaceContactElement<ELEMENT>* el_pt=
          dynamic_cast<HeatedLinearSurfaceContactElement<ELEMENT>*>(
           Surface_contact_mesh_pt->element_pt(e));
         unsigned nnod=el_pt->nnode();
         for (unsigned j=0;j<nnod;j++)
          {
           SolidNode* solid_nod_pt=dynamic_cast<SolidNode*>(el_pt->node_pt(j));
           if (solid_nod_pt==Control_node_pt)
            {
             // Got it!
             found=true;
             // Find index at which contact pressure/Lagrange multiplier
             // is stored
             BoundaryNodeBase *bnod_pt =
              dynamic_cast<BoundaryNodeBase*>(solid_nod_pt);
             // Get the index of the first nodal value associated with
             // this FaceElement
             unsigned new_index_of_traded_contact_pressure=
              bnod_pt->index_of_first_value_assigned_by_face_element(Contact_id);
             // Copy across
 #ifdef PARANOID
             if (index_of_traded_contact_pressure!=UINT_MAX)
              {
               if (new_index_of_traded_contact_pressure!=
                   index_of_traded_contact_pressure)
                {
                 std::stringstream junk;
                 junk << "Inconsistency in identification of index of traded"
                      << "contact pressure: "
                      << new_index_of_traded_contact_pressure
                      << " != " << index_of_traded_contact_pressure;
                 throw OomphLibError(
                  junk.str(),
                  OOMPH_CURRENT_FUNCTION,
                  OOMPH_EXCEPTION_LOCATION);
                }
              }
 #endif
             index_of_traded_contact_pressure=
              new_index_of_traded_contact_pressure;
            }
          }
        }
       if (!found)
        {
         std::stringstream junk;
         junk << "Control node not found!";
         throw OomphLibError(
          junk.str(),
          OOMPH_CURRENT_FUNCTION,
          OOMPH_EXCEPTION_LOCATION);
        }
       // Back up old penetrator (if it existed)
       HeatedCircularPenetratorElement* old_penetrator_pt=
        dynamic_cast<HeatedCircularPenetratorElement*>(
         ProblemParameters::Penetrator_pt);
       // Make new one
       unsigned index_of_horizontal_displacement=0;
       unsigned index_of_vertical_displacement=1;
       ProblemParameters::Penetrator_pt =
        new HeatedCircularPenetratorElement(Control_node_pt,
                                            index_of_traded_contact_pressure,
                                            index_of_horizontal_displacement,
                                            index_of_vertical_displacement,
                                            &ProblemParameters::Radius);
       // Displacement or weight imposed?
       bool impose_displ=true;
       if (old_penetrator_pt!=0)
        {
         if (!old_penetrator_pt->yc_is_imposed())
          {
           impose_displ=false;
          }
        }
       if (impose_displ)
        {
         dynamic_cast<HeatedCircularPenetratorElement*>(
          ProblemParameters::Penetrator_pt)->impose_yc(&ProblemParameters::Y_c);
        }
       else
        {
         dynamic_cast<HeatedCircularPenetratorElement*>(
          ProblemParameters::Penetrator_pt)->impose_weight(
           &ProblemParameters::Weight);
        }
       // Angle or horizontal force imposed?
       bool impose_angle=true;
       if (old_penetrator_pt!=0)
        {
         if (!old_penetrator_pt->rotation_angle_is_imposed())
          {
           impose_angle=false;
          }
        }
       if (impose_angle)
        {
         dynamic_cast<HeatedCircularPenetratorElement*>(
          ProblemParameters::Penetrator_pt)->impose_rotation_angle(
           &ProblemParameters::Rotation_angle);
        }
       else
        {
         dynamic_cast<HeatedCircularPenetratorElement*>(
          ProblemParameters::Penetrator_pt)->impose_horizontal_force(
           &ProblemParameters::Horizontal_force);
         dynamic_cast<HeatedCircularPenetratorElement*>(
          ProblemParameters::Penetrator_pt)->set_angle(
           old_penetrator_pt->angle());
        }
       // Now kill the old one!
       delete old_penetrator_pt;
       // Add to mesh
       Penetrator_mesh_pt->add_element_pt(
        dynamic_cast<HeatedCircularPenetratorElement*>(
         ProblemParameters::Penetrator_pt));
      }
     // Pass contact elements to penetrator element and declare their
     // positions and Lagrange multiplier (contact pressure) values
     // to be external data.
     HeatedCircularPenetratorElement* el_pt=
      dynamic_cast<HeatedCircularPenetratorElement*>(
      ProblemParameters::Penetrator_pt);
     if (el_pt!=0)
      {
       el_pt->set_contact_element_mesh_pt(Surface_contact_mesh_pt);
      }
    } // end of penetrator position computed as part of the solution
      // (directly or indirectly)
    // Loop over the contact elements to pass pointer to penetrator
    //-------------------------------------------------------------
    n_element=Surface_contact_mesh_pt->nelement();
    for(unsigned e=0;e<n_element;e++)
     {
      // Upcast from GeneralisedElement
      HeatedLinearSurfaceContactElement<ELEMENT> *el_pt =
       dynamic_cast<HeatedLinearSurfaceContactElement<ELEMENT>*>(
        Surface_contact_mesh_pt->element_pt(e));
      // Set pointer to penetrator
      el_pt->set_penetrator_pt(ProblemParameters::Penetrator_pt);
     }
    // Find external elements (heated contact elements) that provide
    // the heat flux onto the boulder to maintain continuity of
    // temperature
    Multi_domain_functions::
     Accept_failed_locate_zeta_in_setup_multi_domain_interaction=true;
    Multi_domain_functions::setup_multi_domain_interaction
     <HeatedLinearSurfaceContactElement<ELEMENT> >
     (this,Boulder_surface_contact_mesh_pt,Surface_contact_mesh_pt);
    Multi_domain_functions::
     Accept_failed_locate_zeta_in_setup_multi_domain_interaction=false;
    // Find external elements (penetrator flux elements) that provide
    // the target temperature
    Multi_domain_functions::
     Accept_failed_locate_zeta_in_setup_multi_domain_interaction=true;
    Multi_domain_functions::setup_multi_domain_interaction
     <HeatedPenetratorFluxElement
      <ProjectableUnsteadyHeatElement<TUnsteadyHeatElement<2,3> > > >
     (this,Surface_contact_mesh_pt,Boulder_surface_contact_mesh_pt);
    Multi_domain_functions::
     Accept_failed_locate_zeta_in_setup_multi_domain_interaction=false;
    // hierher setup interaction
   //  // Loop over the heat contact elements to pass pointer to flux
   //  //------------------------------------------------------------
   //  n_element=Boulder_surface_contact_mesh_pt->nelement();
   //  for(unsigned e=0;e<n_element;e++)
   //   {
   //    // Upcast from GeneralisedElement
   //    HeatedPenetratorFluxElement
   //     <ProjectableUnsteadyHeatElement<TUnsteadyHeatElement<2,3> > >* el_pt =
   //     dynamic_cast<HeatedPenetratorFluxElement
   //     <ProjectableUnsteadyHeatElement<TUnsteadyHeatElement<2,3> > >*>(
   //      Boulder_surface_contact_mesh_pt->element_pt(e));
   //  // Set the pointer to the prescribed flux function
   //  // hierher setup interaction el_pt->flux_fct_pt() = &ProblemParameters::unit_flux;
   // }
   }
References oomph::Mesh::add_element_pt(), HeatedCircularPenetratorElement::angle(), Eigen::bfloat16_impl::asin(), b, ContactProblem< ELEMENT >::Bottom_boundary_id, ContactProblem< ELEMENT >::Boulder_surface_contact_mesh_pt, ContactProblem< ELEMENT >::Bulk_mesh_pt, ProblemParameters::Centre, ProblemParameters::Constitutive_law_pt, ContactProblem< ELEMENT >::Contact_boundary_id, ContactProblem< ELEMENT >::Contact_id, ContactProblem< ELEMENT >::Control_node_pt, e(), ProblemParameters::E, oomph::Mesh::element_pt(), boost::multiprecision::fabs(), MergeRestartFiles::found, ProblemParameters::Horizontal_force, ProblemParameters::Impose_position_of_centre, oomph::BoundaryNodeBase::index_of_first_value_assigned_by_face_element(), j, ProblemParameters::Lambda_sq, ContactProblem< ELEMENT >::Left_boundary_id, oomph::Mesh::nelement(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::oomph_info, ContactProblem< ELEMENT >::Penetrator_mesh_pt, ProblemParameters::Penetrator_pt, oomph::Data::pin(), oomph::SolidNode::pin_position(), ProblemParameters::Radius, ContactProblem< ELEMENT >::Right_boundary_id, ProblemParameters::Rotation_angle, HeatedCircularPenetratorElement::rotation_angle_is_imposed(), HeatedCircularPenetratorElement::set_contact_element_mesh_pt(), oomph::SurfaceContactElementBase< ELEMENT >::set_penetrator_pt(), oomph::Multi_domain_functions::setup_multi_domain_interaction(), sin(), ContactProblem< ELEMENT >::Surface_contact_mesh_pt, oomph::Node::value(), ProblemParameters::Weight, oomph::Node::x(), ContactProblem< ELEMENT >::Xc_old, ProblemParameters::Y_c, and HeatedCircularPenetratorElement::yc_is_imposed().
Referenced by ContactProblem< ELEMENT >::actions_after_adapt().
complete_problem_setup() [2/4]
template<class ELEMENT > void ContactProblem< ELEMENT >::complete_problem_setup () inline private
Helper function to (re-)set boundary condition and complete the build of all elements
   {
    // Set (pseudo-)solid mechanics properties for all elements
    //---------------------------------------------------------
    unsigned n_element = Bulk_mesh_pt->nelement();
    for(unsigned e=0;e<n_element;e++)
     {
      //Cast to a solid element
      ELEMENT *el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(e));
      // Set the constitutive law
      el_pt->constitutive_law_pt() =
       ProblemParameters::Constitutive_law_pt;
      // Set density to zero
      el_pt->LinearElasticityEquations<2>::lambda_sq_pt()=
       &ProblemParameters::Lambda_sq;
      // Set density to zero
      el_pt->PVDEquationsBase<2>::lambda_sq_pt()=
       &ProblemParameters::Lambda_sq;
      // Set the elasticity tensor
      el_pt->elasticity_tensor_pt() = &ProblemParameters::E;
      // Disable inertia
      el_pt->LinearElasticityEquations<2>::disable_inertia();
      // Disable inertia
      el_pt->PVDEquationsBase<2>::disable_inertia();
      // Set body force for real solid
      el_pt->LinearElasticityEquations<2>::body_force_fct_pt() =
       &ProblemParameters::body_force;
     }
    // Apply boundary conditions for solid
    //------------------------------------
    // Bottom: completely pinned
    unsigned b=Bottom_boundary_id;
    unsigned nnod=Bulk_mesh_pt->nboundary_node(b);
    for (unsigned j=0;j<nnod;j++)
     {
      SolidNode* nod_pt=Bulk_mesh_pt->boundary_node_pt(b,j);
      nod_pt->pin_position(0);
      nod_pt->pin_position(1);
      nod_pt->pin(0);
      nod_pt->pin(1);
     }
    // Sides: Symmetry bcs
    b=Left_boundary_id;
    nnod=Bulk_mesh_pt->nboundary_node(b);
    for (unsigned j=0;j<nnod;j++)
     {
      SolidNode* nod_pt=Bulk_mesh_pt->boundary_node_pt(b,j);
      nod_pt->pin_position(0);
      nod_pt->pin(0);
     }
    b=Right_boundary_id;
    nnod=Bulk_mesh_pt->nboundary_node(b);
    for (unsigned j=0;j<nnod;j++)
     {
      SolidNode* nod_pt=Bulk_mesh_pt->boundary_node_pt(b,j);
      nod_pt->pin_position(0);
      nod_pt->pin(0);
     }
    // Enforce contact at most central or most heavily loaded node
    //------------------------------------------------------------
    {
     // Update angle?
     bool update_angle=false;
     double phi_old=0.0;
     CircularPenetratorElement* pen_el_pt=
      dynamic_cast<CircularPenetratorElement*>(
       ProblemParameters::Penetrator_pt);
     if (pen_el_pt!=0)
      {
       update_angle=true;
       phi_old=pen_el_pt->angle();
      }
     // Find closest/most loaded node
     double x_c=0.5;
     Control_node_pt=0;
     SolidNode* most_central_node_pt=0;
     SolidNode* most_loaded_node_pt=0;
     double dist_min=DBL_MAX;
     double load_max=0.0;
     unsigned b=Contact_boundary_id;
     unsigned nnod=Bulk_mesh_pt->nboundary_node(b);
     for (unsigned j=0;j<nnod;j++)
      {
       SolidNode* nod_pt=Bulk_mesh_pt->boundary_node_pt(b,j);
       // Find closest node
       double dist=std::fabs(nod_pt->x(0)-x_c);
       if (dist<dist_min)
        {
         dist_min=dist;
         most_central_node_pt=nod_pt;
        }
       // Find most loaded node
       BoundaryNodeBase *bnod_pt=dynamic_cast<BoundaryNodeBase*>(nod_pt);
       unsigned index_of_contact_pressure=
        bnod_pt->index_of_first_value_assigned_by_face_element(Contact_id);
       if (nod_pt->value(index_of_contact_pressure)>load_max)
        {
         load_max=nod_pt->value(index_of_contact_pressure);
         most_loaded_node_pt=nod_pt;
        }
      }
     // No load
     if (most_loaded_node_pt==0)
      {
       oomph_info << "Choosing most central node as control node\n";
       Control_node_pt=most_central_node_pt;
      }
     else
      {
       oomph_info << "Choosing most loaded node as control node\n";
       Control_node_pt=most_loaded_node_pt;
      }
     oomph_info << "Control node located at: "
                << Control_node_pt->x(0) << " "
                << Control_node_pt->x(1) << " "
                << std::endl;
     // Update angle
     if (update_angle)
      {
       double phi_new=asin((Xc_old-Control_node_pt->x(0))/
                           ProblemParameters::Radius+sin(phi_old));
       dynamic_cast<CircularPenetratorElement*>(
        ProblemParameters::Penetrator_pt)->set_angle(phi_new);
       oomph_info << "Old/new angle: " << phi_old << " "
                  << phi_new << std::endl;
      }
     //...............................................................
     // Set target vertical position of control node to its current
     // position. This is fine as initial assignment; it's then over-written
     // before the next solve (if the displacement is controlled).
     // If/when this function is called during adaptation it's fine too
     // because it doesn't impose another displacement increment -- it simply
     // maintains the position that was obtained on the previous solve.
     unsigned index_of_vertical_displacement=1;
     ProblemParameters::Y_c=Control_node_pt->x(1)+
      Control_node_pt->value(index_of_vertical_displacement);
     // Index of nodal value at control node that stores the traded
     // contact pressure
     unsigned index_of_traded_contact_pressure=UINT_MAX;
     // Impose position of centre when penetrator position directly imposed
     //--------------------------------------------------------------------
     if (ProblemParameters::Impose_position_of_centre)
      {
       // Delete old one
       delete ProblemParameters::Penetrator_pt;
       // Make new one
       ProblemParameters::Penetrator_pt =
        new CircularPenetrator(&ProblemParameters::Centre,
                               ProblemParameters::Radius);
      }
     // Compute penetrator position as part of the solution, either by
     // --------------------------------------------------------------
     // prescribing nodal position or weight
     // ------------------------------------
     else
      {
       // Loop over face elements to identify the ones that contain
       // the control node
       unsigned nel=Surface_contact_mesh_pt->nelement();
       bool found=false;
       for (unsigned e=0;e<nel;e++)
        {
         LinearSurfaceContactElement<ELEMENT>* el_pt=
          dynamic_cast<LinearSurfaceContactElement<ELEMENT>*>(
           Surface_contact_mesh_pt->element_pt(e));
         unsigned nnod=el_pt->nnode();
         for (unsigned j=0;j<nnod;j++)
          {
           SolidNode* solid_nod_pt=dynamic_cast<SolidNode*>(el_pt->node_pt(j));
           if (solid_nod_pt==Control_node_pt)
            {
             // Got it!
             found=true;
             // Find index at which contact pressure/Lagrange multiplier
             // is stored
             BoundaryNodeBase *bnod_pt =
              dynamic_cast<BoundaryNodeBase*>(solid_nod_pt);
             // Get the index of the first nodal value associated with
             // this FaceElement
             unsigned new_index_of_traded_contact_pressure=
              bnod_pt->index_of_first_value_assigned_by_face_element(Contact_id);
             // Copy across
 #ifdef PARANOID
             if (index_of_traded_contact_pressure!=UINT_MAX)
              {
               if (new_index_of_traded_contact_pressure!=
                   index_of_traded_contact_pressure)
                {
                 std::stringstream junk;
                 junk << "Inconsistency in identification of index of traded"
                      << "contact pressure: "
                      << new_index_of_traded_contact_pressure
                      << " != " << index_of_traded_contact_pressure;
                 throw OomphLibError(
                  junk.str(),
                  OOMPH_CURRENT_FUNCTION,
                  OOMPH_EXCEPTION_LOCATION);
                }
              }
 #endif
             index_of_traded_contact_pressure=
              new_index_of_traded_contact_pressure;
            }
          }
        }
       if (!found)
        {
         std::stringstream junk;
         junk << "Control node not found!";
         throw OomphLibError(
          junk.str(),
          OOMPH_CURRENT_FUNCTION,
          OOMPH_EXCEPTION_LOCATION);
        }
       // Back up old penetrator (if it existed)
       CircularPenetratorElement* old_penetrator_pt=
        dynamic_cast<CircularPenetratorElement*>(
         ProblemParameters::Penetrator_pt);
       // Make new one
       unsigned index_of_horizontal_displacement=0;
       unsigned index_of_vertical_displacement=1;
       ProblemParameters::Penetrator_pt =
        new CircularPenetratorElement(Control_node_pt,
                                      index_of_traded_contact_pressure,
                                      index_of_horizontal_displacement,
                                      index_of_vertical_displacement,
                                      &ProblemParameters::Radius);
       // Displacement or weight imposed?
       bool impose_displ=true;
       if (old_penetrator_pt!=0)
        {
         if (!old_penetrator_pt->yc_is_imposed())
          {
           impose_displ=false;
          }
        }
       if (impose_displ)
        {
         dynamic_cast<CircularPenetratorElement*>(
          ProblemParameters::Penetrator_pt)->impose_yc(&ProblemParameters::Y_c);
        }
       else
        {
         dynamic_cast<CircularPenetratorElement*>(
          ProblemParameters::Penetrator_pt)->impose_weight(
           &ProblemParameters::Weight);
        }
       // Angle or horizontal force imposed?
       bool impose_angle=true;
       if (old_penetrator_pt!=0)
        {
         if (!old_penetrator_pt->rotation_angle_is_imposed())
          {
           impose_angle=false;
          }
        }
       if (impose_angle)
        {
         dynamic_cast<CircularPenetratorElement*>(
          ProblemParameters::Penetrator_pt)->impose_rotation_angle(
           &ProblemParameters::Rotation_angle);
        }
       else
        {
         dynamic_cast<CircularPenetratorElement*>(
          ProblemParameters::Penetrator_pt)->impose_horizontal_force(
           &ProblemParameters::Horizontal_force);
         dynamic_cast<CircularPenetratorElement*>(
          ProblemParameters::Penetrator_pt)->set_angle(
           old_penetrator_pt->angle());
        }
       // Now kill the old one!
       delete old_penetrator_pt;
       // Add to mesh
       Penetrator_mesh_pt->add_element_pt(
        dynamic_cast<CircularPenetratorElement*>(
         ProblemParameters::Penetrator_pt));
      }
     // Pass contact elements to penetrator element and declare their
     // positions and Lagrange multiplier (contact pressure) values
     // to be external data.
     CircularPenetratorElement* el_pt=dynamic_cast<CircularPenetratorElement*>(
      ProblemParameters::Penetrator_pt);
     if (el_pt!=0)
      {
       el_pt->set_contact_element_mesh_pt(Surface_contact_mesh_pt);
      }
    } // end of penetrator position computed as part of the solution
      // (directly or indirectly)
    // Loop over the contact elements to pass pointer to penetrator
    //-------------------------------------------------------------
    n_element=Surface_contact_mesh_pt->nelement();
    for(unsigned e=0;e<n_element;e++)
     {
      // Upcast from GeneralisedElement
      LinearSurfaceContactElement<ELEMENT> *el_pt =
       dynamic_cast<LinearSurfaceContactElement<ELEMENT>*>(
        Surface_contact_mesh_pt->element_pt(e));
      // Set pointer to penetrator
      el_pt->set_penetrator_pt(ProblemParameters::Penetrator_pt);
     }
   }
References CircularPenetratorElement::angle(), Eigen::bfloat16_impl::asin(), b, ProblemParameters::body_force(), ProblemParameters::Centre, ProblemParameters::Constitutive_law_pt, e(), ProblemParameters::E, boost::multiprecision::fabs(), MergeRestartFiles::found, ProblemParameters::Horizontal_force, ProblemParameters::Impose_position_of_centre, oomph::BoundaryNodeBase::index_of_first_value_assigned_by_face_element(), j, ProblemParameters::Lambda_sq, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::oomph_info, ProblemParameters::Penetrator_pt, oomph::Data::pin(), oomph::SolidNode::pin_position(), ProblemParameters::Radius, ProblemParameters::Rotation_angle, CircularPenetratorElement::rotation_angle_is_imposed(), CircularPenetratorElement::set_contact_element_mesh_pt(), oomph::SurfaceContactElementBase< ELEMENT >::set_penetrator_pt(), sin(), oomph::Node::value(), ProblemParameters::Weight, oomph::Node::x(), ProblemParameters::Y_c, and CircularPenetratorElement::yc_is_imposed().
complete_problem_setup() [3/4]
template<class ELEMENT > void ContactProblem< ELEMENT >::complete_problem_setup () inline private
Helper function to (re-)set boundary condition and complete the build of all elements
   {
    // Set (pseudo-)solid mechanics properties for all elements
    //---------------------------------------------------------
    unsigned n_element = Bulk_mesh_pt->nelement();
    for(unsigned e=0;e<n_element;e++)
     {
      //Cast to a solid element
      ELEMENT *el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(e));
      // Set the constitutive law
      el_pt->constitutive_law_pt() =
       ProblemParameters::Constitutive_law_pt;
      // Set density to zero
      el_pt->lambda_sq_pt()=&ProblemParameters::Lambda_sq;
      // Disable inertia
      el_pt->disable_inertia();
     }
    // Apply boundary conditions for solid
    //------------------------------------
    // Bottom: completely pinned
    unsigned b=Bottom_boundary_id;
    unsigned nnod=Bulk_mesh_pt->nboundary_node(b);
    for (unsigned j=0;j<nnod;j++)
     {
      SolidNode* nod_pt=Bulk_mesh_pt->boundary_node_pt(b,j);
      nod_pt->pin_position(0);
      nod_pt->pin_position(1);
     }
    // Sides: Symmetry bcs
    b=Left_boundary_id;
    nnod=Bulk_mesh_pt->nboundary_node(b);
    for (unsigned j=0;j<nnod;j++)
     {
      SolidNode* nod_pt=Bulk_mesh_pt->boundary_node_pt(b,j);
      nod_pt->pin_position(0);
     }
    b=Right_boundary_id;
    nnod=Bulk_mesh_pt->nboundary_node(b);
    for (unsigned j=0;j<nnod;j++)
     {
      SolidNode* nod_pt=Bulk_mesh_pt->boundary_node_pt(b,j);
      nod_pt->pin_position(0);
     }
    // hierher
    // if (!CommandLineArgs::command_line_flag_has_been_set("--proper_elasticity"))
    //  {
    //   // Assign the Lagrangian coordinates -- sensible
    //   // because we've completely rebuilt the mesh
    //   // and haven't copied across any Lagrange multipliers
    //   Bulk_mesh_pt->set_lagrangian_nodal_coordinates();
    //  }
    // Loop over the contact elements to pass pointer to penetrator
    //-------------------------------------------------------------
    n_element=Surface_contact_mesh_pt->nelement();
    for(unsigned e=0;e<n_element;e++)
     {
      // Upcast from GeneralisedElement
      NonlinearSurfaceContactElement<ELEMENT> *el_pt =
       dynamic_cast<NonlinearSurfaceContactElement<ELEMENT>*>(
        Surface_contact_mesh_pt->element_pt(e));
      // Set pointer to penetrator
      el_pt->set_penetrator_pt(ProblemParameters::Penetrator_pt);
     }
   }
References b, ProblemParameters::Constitutive_law_pt, e(), j, ProblemParameters::Lambda_sq, ProblemParameters::Penetrator_pt, oomph::SolidNode::pin_position(), and oomph::SurfaceContactElementBase< ELEMENT >::set_penetrator_pt().
complete_problem_setup() [4/4]
template<class ELEMENT > void ContactProblem< ELEMENT >::complete_problem_setup () inline private
Helper function to (re-)set boundary condition and complete the build of all elements
   {
    // Set (pseudo-)solid mechanics properties for all elements
    //---------------------------------------------------------
    unsigned n_element = Bulk_mesh_pt->nelement();
    for(unsigned e=0;e<n_element;e++)
     {
      //Cast to a solid element
      ELEMENT *el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(e));
      // Set the constitutive law
      el_pt->constitutive_law_pt() =
       ProblemParameters::Constitutive_law_pt;
      // Set density to zero
      el_pt->lambda_sq_pt()=&ProblemParameters::Lambda_sq;
      // Disable inertia
      el_pt->disable_inertia();
      // Set body force
      el_pt->body_force_fct_pt() = &ProblemParameters::body_force;
     }
    // Apply boundary conditions for solid
    //------------------------------------
    // Bottom: completely pinned
    unsigned b=Bottom_boundary_id;
    unsigned nnod=Bulk_mesh_pt->nboundary_node(b);
    for (unsigned j=0;j<nnod;j++)
     {
      SolidNode* nod_pt=Bulk_mesh_pt->boundary_node_pt(b,j);
      nod_pt->pin_position(0);
      nod_pt->pin_position(1);
     }
    // Sides: Symmetry bcs
    b=Left_boundary_id;
    nnod=Bulk_mesh_pt->nboundary_node(b);
    for (unsigned j=0;j<nnod;j++)
     {
      SolidNode* nod_pt=Bulk_mesh_pt->boundary_node_pt(b,j);
      nod_pt->pin_position(0);
     }
    b=Right_boundary_id;
    nnod=Bulk_mesh_pt->nboundary_node(b);
    for (unsigned j=0;j<nnod;j++)
     {
      SolidNode* nod_pt=Bulk_mesh_pt->boundary_node_pt(b,j);
      nod_pt->pin_position(0);
     }
    // Enforce contact at most central or most heavily loaded node
    //------------------------------------------------------------
    {
     // Update angle?
     bool update_angle=false;
     double phi_old=0.0;
     CircularPenetratorElement* pen_el_pt=
      dynamic_cast<CircularPenetratorElement*>(
       ProblemParameters::Penetrator_pt);
     if (pen_el_pt!=0)
      {
       update_angle=true;
       phi_old=pen_el_pt->angle();
      }
     double x_c=0.5;
     Control_node_pt=0;
     SolidNode* most_central_node_pt=0;
     SolidNode* most_loaded_node_pt=0;
     double dist_min=DBL_MAX;
     double load_max=0.0;
     unsigned b=Contact_boundary_id;
     unsigned nnod=Bulk_mesh_pt->nboundary_node(b);
     for (unsigned j=0;j<nnod;j++)
      {
       SolidNode* nod_pt=Bulk_mesh_pt->boundary_node_pt(b,j);
       // Find closest node
       double dist=std::fabs(nod_pt->x(0)-x_c);
       if (dist<dist_min)
        {
         dist_min=dist;
         most_central_node_pt=nod_pt;
        }
       // Find most loaded node
       BoundaryNodeBase *bnod_pt=dynamic_cast<BoundaryNodeBase*>(nod_pt);
       unsigned index_of_contact_pressure=
        bnod_pt->index_of_first_value_assigned_by_face_element(Contact_id);
       if (nod_pt->value(index_of_contact_pressure)>load_max)
        {
         load_max=nod_pt->value(index_of_contact_pressure);
         most_loaded_node_pt=nod_pt;
        }
      }
     // No load
     if (most_loaded_node_pt==0)
      {
       oomph_info << "Choosing most central node as control node\n";
       Control_node_pt=most_central_node_pt;
      }
     else
      {
       oomph_info << "Choosing most loaded node as control node\n";
       Control_node_pt=most_loaded_node_pt;
      }
     oomph_info << "Control node located at: "
                << Control_node_pt->x(0) << " "
                << Control_node_pt->x(1) << " "
                << std::endl;
     // Update angle
     if (update_angle)
      {
       double phi_new=asin((Xc_old-Control_node_pt->x(0))/
                           ProblemParameters::Radius+sin(phi_old));
       dynamic_cast<CircularPenetratorElement*>(
        ProblemParameters::Penetrator_pt)->set_angle(phi_new);
       oomph_info << "Old/new angle: " << phi_old << " "
                  << phi_new << std::endl;
      }
     // Set target vertical position of control node to its current
     // position. This is fine as initial assignment; it's then over-written
     // before the next solve (if the displacement is controlled).
     // If/when this function is called during adaptation it's fine too
     // because it doesn't impose another displacement increment -- it simply
     // maintains the position that was obtained on the previous solve.
     ProblemParameters::Y_c=Control_node_pt->x(1);
     // Index of nodal value at control node that stores the traded
     // contact pressure
     unsigned index_of_traded_contact_pressure=UINT_MAX;
     // Impose position of centre when penetrator position directly imposed
     //--------------------------------------------------------------------
     if (ProblemParameters::Impose_position_of_centre)
      {
       // Delete old one
       delete ProblemParameters::Penetrator_pt;
       // Make new one
       ProblemParameters::Penetrator_pt =
        new CircularPenetrator(&ProblemParameters::Centre,
                               ProblemParameters::Radius);
      }
     // Compute penetrator position as part of the solution, either by
     // --------------------------------------------------------------
     // prescribing nodal position or weight
     // ------------------------------------
     else
      {
       // Loop over face elements to identify the ones that contain
       // the control node
       unsigned nel=Surface_contact_mesh_pt->nelement();
       bool found=false;
       for (unsigned e=0;e<nel;e++)
        {
         NonlinearSurfaceContactElement<ELEMENT>* el_pt=
          dynamic_cast<NonlinearSurfaceContactElement<ELEMENT>*>(
           Surface_contact_mesh_pt->element_pt(e));
         unsigned nnod=el_pt->nnode();
         for (unsigned j=0;j<nnod;j++)
          {
           SolidNode* solid_nod_pt=dynamic_cast<SolidNode*>(el_pt->node_pt(j));
           if (solid_nod_pt==Control_node_pt)
            {
             // Got it!
             found=true;
             // Find index at which contact pressure/Lagrange multiplier
             // is stored
             BoundaryNodeBase *bnod_pt =
              dynamic_cast<BoundaryNodeBase*>(solid_nod_pt);
             // Get the index of the first nodal value associated with
             // this FaceElement
             unsigned new_index_of_traded_contact_pressure=
              bnod_pt->index_of_first_value_assigned_by_face_element(Contact_id);
             // Copy across
 #ifdef PARANOID
             if (index_of_traded_contact_pressure!=UINT_MAX)
              {
               if (new_index_of_traded_contact_pressure!=
                   index_of_traded_contact_pressure)
                {
                 std::stringstream junk;
                 junk << "Inconsistency in identification of index of traded"
                      << "contact pressure: "
                      << new_index_of_traded_contact_pressure
                      << " != " << index_of_traded_contact_pressure;
                 throw OomphLibError(
                  junk.str(),
                  OOMPH_CURRENT_FUNCTION,
                  OOMPH_EXCEPTION_LOCATION);
                }
              }
 #endif
             index_of_traded_contact_pressure=
              new_index_of_traded_contact_pressure;
            }
          }
        }
       if (!found)
        {
         std::stringstream junk;
         junk << "Control node not found!";
         throw OomphLibError(
          junk.str(),
          OOMPH_CURRENT_FUNCTION,
          OOMPH_EXCEPTION_LOCATION);
        }
       // Back up old penetrator (if it existed)
       CircularPenetratorElement* old_penetrator_pt=
        dynamic_cast<CircularPenetratorElement*>(
         ProblemParameters::Penetrator_pt);
       // Make new one
       ProblemParameters::Penetrator_pt =
        new CircularPenetratorElement(Control_node_pt,
                                      index_of_traded_contact_pressure,
                                      &ProblemParameters::Radius);
       // Displacement or weight imposed?
       bool impose_displ=true;
       if (old_penetrator_pt!=0)
        {
         if (!old_penetrator_pt->yc_is_imposed())
          {
           impose_displ=false;
          }
        }
       if (impose_displ)
        {
         dynamic_cast<CircularPenetratorElement*>(
          ProblemParameters::Penetrator_pt)->impose_yc(&ProblemParameters::Y_c);
        }
       else
        {
         dynamic_cast<CircularPenetratorElement*>(
          ProblemParameters::Penetrator_pt)->impose_weight(
           &ProblemParameters::Weight);
        }
       // Angle or horizontal force imposed?
       bool impose_angle=true;
       if (old_penetrator_pt!=0)
        {
         if (!old_penetrator_pt->rotation_angle_is_imposed())
          {
           impose_angle=false;
          }
        }
       if (impose_angle)
        {
         dynamic_cast<CircularPenetratorElement*>(
          ProblemParameters::Penetrator_pt)->impose_rotation_angle(
           &ProblemParameters::Rotation_angle);
        }
       else
        {
         dynamic_cast<CircularPenetratorElement*>(
          ProblemParameters::Penetrator_pt)->impose_horizontal_force(
           &ProblemParameters::Horizontal_force);
         dynamic_cast<CircularPenetratorElement*>(
          ProblemParameters::Penetrator_pt)->set_angle(
           old_penetrator_pt->angle());
        }
       // Now kill the old one!
       delete old_penetrator_pt;
       // Add to mesh
       Penetrator_mesh_pt->add_element_pt(
        dynamic_cast<CircularPenetratorElement*>(
         ProblemParameters::Penetrator_pt));
      }
     // Pass contact elements to penetrator element and declare their
     // positions and Lagrange multiplier (contact pressure) values
     // to be external data.
     CircularPenetratorElement* el_pt=dynamic_cast<CircularPenetratorElement*>(
      ProblemParameters::Penetrator_pt);
     if (el_pt!=0)
      {
       el_pt->set_contact_element_mesh_pt(Surface_contact_mesh_pt);
      }
    } // end of penetrator position computed as part of the solution
      // (directly or indirectly)
    // Loop over the contact elements to pass pointer to penetrator
    //-------------------------------------------------------------
    n_element=Surface_contact_mesh_pt->nelement();
    for(unsigned e=0;e<n_element;e++)
     {
      // Upcast from GeneralisedElement
      NonlinearSurfaceContactElement<ELEMENT> *el_pt =
       dynamic_cast<NonlinearSurfaceContactElement<ELEMENT>*>(
        Surface_contact_mesh_pt->element_pt(e));
      // Set pointer to penetrator
      el_pt->set_penetrator_pt(ProblemParameters::Penetrator_pt);
     }
   }
References CircularPenetratorElement::angle(), Eigen::bfloat16_impl::asin(), b, ProblemParameters::body_force(), ProblemParameters::Centre, ProblemParameters::Constitutive_law_pt, e(), boost::multiprecision::fabs(), MergeRestartFiles::found, ProblemParameters::Horizontal_force, ProblemParameters::Impose_position_of_centre, oomph::BoundaryNodeBase::index_of_first_value_assigned_by_face_element(), j, ProblemParameters::Lambda_sq, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::oomph_info, ProblemParameters::Penetrator_pt, oomph::SolidNode::pin_position(), ProblemParameters::Radius, ProblemParameters::Rotation_angle, CircularPenetratorElement::rotation_angle_is_imposed(), CircularPenetratorElement::set_contact_element_mesh_pt(), oomph::SurfaceContactElementBase< ELEMENT >::set_penetrator_pt(), sin(), oomph::Node::value(), ProblemParameters::Weight, oomph::Node::x(), ProblemParameters::Y_c, and CircularPenetratorElement::yc_is_imposed().
create_contact_elements() [1/4]
template<class ELEMENT > void ContactProblem< ELEMENT >::create_contact_elements () inline private
Create contact elements.
   {
    // How many bulk elements are adjacent to boundary b?
    unsigned b=Contact_boundary_id;
    unsigned n_element = Bulk_mesh_pt->nboundary_element(b);
    // Loop over the bulk elements adjacent to boundary b?
    for(unsigned e=0;e<n_element;e++)
     {
      // Get pointer to the bulk element that is adjacent to boundary b
      ELEMENT* bulk_elem_pt = dynamic_cast<ELEMENT*>(
       Bulk_mesh_pt->boundary_element_pt(b,e));
      //What is the face index of element e along boundary b
      int face_index = Bulk_mesh_pt->face_index_at_boundary(b,e);
      // Build the corresponding contact element
      HeatedLinearSurfaceContactElement<ELEMENT>* contact_element_pt = new
       HeatedLinearSurfaceContactElement<ELEMENT>(bulk_elem_pt,face_index,
                                            Contact_id);
      // Pass pointer to penetrator
      contact_element_pt->set_penetrator_pt(ProblemParameters::Penetrator_pt);
      //Add the contact element to the surface mesh
      Surface_contact_mesh_pt->add_element_pt(contact_element_pt);
     } //end of loop over bulk elements adjacent to boundary b
   }
References oomph::Mesh::add_element_pt(), b, ContactProblem< ELEMENT >::Bulk_mesh_pt, ContactProblem< ELEMENT >::Contact_boundary_id, ContactProblem< ELEMENT >::Contact_id, e(), ProblemParameters::Penetrator_pt, oomph::SurfaceContactElementBase< ELEMENT >::set_penetrator_pt(), and ContactProblem< ELEMENT >::Surface_contact_mesh_pt.
Referenced by ContactProblem< ELEMENT >::actions_after_adapt().
create_contact_elements() [2/4]
template<class ELEMENT > void ContactProblem< ELEMENT >::create_contact_elements () inline private
Create contact elements.
   {
    // How many bulk elements are adjacent to boundary b?
    unsigned b=Contact_boundary_id;
    unsigned n_element = Bulk_mesh_pt->nboundary_element(b);
    // Loop over the bulk elements adjacent to boundary b?
    for(unsigned e=0;e<n_element;e++)
     {
      // Get pointer to the bulk element that is adjacent to boundary b
      ELEMENT* bulk_elem_pt = dynamic_cast<ELEMENT*>(
       Bulk_mesh_pt->boundary_element_pt(b,e));
      //What is the face index of element e along boundary b
      int face_index = Bulk_mesh_pt->face_index_at_boundary(b,e);
      // Build the corresponding contact element
      LinearSurfaceContactElement<ELEMENT>* contact_element_pt = new
       LinearSurfaceContactElement<ELEMENT>(bulk_elem_pt,face_index,
                                            Contact_id);
      //Add the contact element to the surface mesh
      Surface_contact_mesh_pt->add_element_pt(contact_element_pt);
     } //end of loop over bulk elements adjacent to boundary b
   }
References b, and e().
create_contact_elements() [3/4]
template<class ELEMENT > void ContactProblem< ELEMENT >::create_contact_elements () inline private
Create contact elements.
   {
    // How many bulk elements are adjacent to boundary b?
    unsigned b=Contact_boundary_id;
    unsigned n_element = Bulk_mesh_pt->nboundary_element(b);
    // Loop over the bulk elements adjacent to boundary b?
    for(unsigned e=0;e<n_element;e++)
     {
      // Get pointer to the bulk element that is adjacent to boundary b
      ELEMENT* bulk_elem_pt = dynamic_cast<ELEMENT*>(
       Bulk_mesh_pt->boundary_element_pt(b,e));
      //What is the face index of element e along boundary b
      int face_index = Bulk_mesh_pt->face_index_at_boundary(b,e);
      // Build the corresponding contact element
      NonlinearSurfaceContactElement<ELEMENT>* contact_element_pt = new
       NonlinearSurfaceContactElement<ELEMENT>(bulk_elem_pt,face_index);
      //Add the contact element to the surface mesh
      Surface_contact_mesh_pt->add_element_pt(contact_element_pt);
     } //end of loop over bulk elements adjacent to boundary b
   }
References b, and e().
create_contact_elements() [4/4]
template<class ELEMENT > void ContactProblem< ELEMENT >::create_contact_elements () inline private
Create contact elements.
   {
    // How many bulk elements are adjacent to boundary b?
    unsigned b=Contact_boundary_id;
    unsigned n_element = Bulk_mesh_pt->nboundary_element(b);
    // Loop over the bulk elements adjacent to boundary b?
    for(unsigned e=0;e<n_element;e++)
     {
      // Get pointer to the bulk element that is adjacent to boundary b
      ELEMENT* bulk_elem_pt = dynamic_cast<ELEMENT*>(
       Bulk_mesh_pt->boundary_element_pt(b,e));
      //What is the face index of element e along boundary b
      int face_index = Bulk_mesh_pt->face_index_at_boundary(b,e);
      // Build the corresponding contact element
      NonlinearSurfaceContactElement<ELEMENT>* contact_element_pt = new
       NonlinearSurfaceContactElement<ELEMENT>(bulk_elem_pt,face_index,
                                                 Contact_id);
      //Add the contact element to the surface mesh
      Surface_contact_mesh_pt->add_element_pt(contact_element_pt);
     } //end of loop over bulk elements adjacent to boundary b
   }
References b, and e().
create_contact_heat_elements_on_boulder()
template<class ELEMENT > void ContactProblem< ELEMENT >::create_contact_heat_elements_on_boulder () inline private
Create "contact" heat flux elements on surface of boulder.
   {
    // How many bulk elements are adjacent to boundary b?
    unsigned b=Boulder_bottom_boundary_id;
    unsigned n_element = Boulder_mesh_pt->nboundary_element(b);
    // Loop over the bulk elements adjacent to boundary b?
    for(unsigned e=0;e<n_element;e++)
     {
      // Get pointer to the bulk element that is adjacent to boundary b
      ProjectableUnsteadyHeatElement<TUnsteadyHeatElement<2,3> >* bulk_elem_pt =
       dynamic_cast<ProjectableUnsteadyHeatElement<TUnsteadyHeatElement<2,3> >*>(
        Boulder_mesh_pt->boundary_element_pt(b,e));
      //What is the face index of element e along boundary b
      int face_index = Boulder_mesh_pt->face_index_at_boundary(b,e);
      // Build the corresponding contact element
      HeatedPenetratorFluxElement
       <ProjectableUnsteadyHeatElement<TUnsteadyHeatElement<2,3> > >*
       contact_element_pt = new
       HeatedPenetratorFluxElement
       <ProjectableUnsteadyHeatElement<TUnsteadyHeatElement<2,3> > >(
        bulk_elem_pt,face_index);
      // Pass pointer to penetrator
      contact_element_pt->set_penetrator_pt(ProblemParameters::Penetrator_pt);
      //Add the contact element to the surface mesh
      Boulder_surface_contact_mesh_pt->add_element_pt(contact_element_pt);
     } //end of loop over bulk elements adjacent to boundary b
   }
References oomph::Mesh::add_element_pt(), b, ContactProblem< ELEMENT >::Boulder_bottom_boundary_id, ContactProblem< ELEMENT >::Boulder_mesh_pt, ContactProblem< ELEMENT >::Boulder_surface_contact_mesh_pt, oomph::Mesh::boundary_element_pt(), e(), oomph::Mesh::face_index_at_boundary(), oomph::Mesh::nboundary_element(), and ProblemParameters::Penetrator_pt.
Referenced by ContactProblem< ELEMENT >::actions_after_adapt().
create_displ_imposition_elements() [1/2]
template<class ELEMENT > void ContactProblem< ELEMENT >::create_displ_imposition_elements () inline private
Create elements that enforce prescribed boundary motion by Lagrange multipliers
   {
    Vector<unsigned> boundary_id;
    boundary_id.push_back(Contact_boundary_id);
 #ifndef STRUCTURED_MESH
    Node* left_contact_node_pt=0;
    Node* right_contact_node_pt=0;
    Node* left_left_top_node_pt=0;
    Node* right_left_top_node_pt=0;
    Node* left_right_top_node_pt=0;
    Node* right_right_top_node_pt=0;
    boundary_id.push_back(Left_top_boundary_id);
    boundary_id.push_back(Right_top_boundary_id);
 #endif
    unsigned nb=boundary_id.size();
    for (unsigned bb=0;bb<nb;bb++)
     {
      unsigned b=boundary_id[bb];
      // How many bulk elements are adjacent to boundary b?
      unsigned n_element = Bulk_mesh_pt->nboundary_element(b);
      // Loop over the bulk elements adjacent to boundary b?
      for(unsigned e=0;e<n_element;e++)
       {
        // Get pointer to the bulk element that is adjacent to boundary b
        ELEMENT* bulk_elem_pt = dynamic_cast<ELEMENT*>(
         Bulk_mesh_pt->boundary_element_pt(b,e));
        //Find the index of the face of element e along boundary b
        int face_index = Bulk_mesh_pt->face_index_at_boundary(b,e);
        // Create new element
        ImposeDisplacementByLagrangeMultiplierElement<ELEMENT>* el_pt=
         new ImposeDisplacementByLagrangeMultiplierElement<ELEMENT>(
          bulk_elem_pt,face_index);
        // Add to mesh
        Displ_imposition_mesh_pt->add_element_pt(el_pt);
 #ifdef STRUCTURED_MESH
        // Set the GeomObject that defines the boundary shape and
        // specify which bulk boundary we are attached to (needed to extract
        // the boundary coordinate from the bulk nodes)
        el_pt->set_boundary_shape_geom_object_pt(
         &ProblemParameters::Boundary_geom_object,b);
 #else
        switch(b)
         {
         case Contact_boundary_id:
          // Set the GeomObject that defines the boundary shape and
          // specify which bulk boundary we are attached to (needed to extract
          // the boundary coordinate from the bulk nodes)
          el_pt->set_boundary_shape_geom_object_pt(
           &ProblemParameters::Boundary_geom_object_contact,b);
          {
           unsigned nnod=el_pt->nnode();
           for (unsigned j=0;j<nnod;j++)
            {
             Node* nod_pt=el_pt->node_pt(j);
             if (nod_pt->is_on_boundary(Left_top_boundary_id))
              {
               left_contact_node_pt=nod_pt;
              }
             else if (nod_pt->is_on_boundary(Right_top_boundary_id))
              {
               right_contact_node_pt=nod_pt;
              }
            }
          }
          break;
         case Left_top_boundary_id:
          // Set the GeomObject that defines the boundary shape and
          // specify which bulk boundary we are attached to (needed to extract
          // the boundary coordinate from the bulk nodes)
          el_pt->set_boundary_shape_geom_object_pt(
           &ProblemParameters::Boundary_geom_object_left,b);
          {
           unsigned nnod=el_pt->nnode();
           for (unsigned j=0;j<nnod;j++)
            {
             Node* nod_pt=el_pt->node_pt(j);
             if (nod_pt->is_on_boundary(Left_boundary_id))
              {
               left_left_top_node_pt=nod_pt;
              }
             else if (nod_pt->is_on_boundary(Contact_boundary_id))
              {
               right_left_top_node_pt=nod_pt;
              }
            }
          }
          break;
         case Right_top_boundary_id:
          // Set the GeomObject that defines the boundary shape and
          // specify which bulk boundary we are attached to (needed to extract
          // the boundary coordinate from the bulk nodes)
          el_pt->set_boundary_shape_geom_object_pt(
           &ProblemParameters::Boundary_geom_object_right,b);
          {
           unsigned nnod=el_pt->nnode();
           for (unsigned j=0;j<nnod;j++)
            {
             Node* nod_pt=el_pt->node_pt(j);
             if (nod_pt->is_on_boundary(Right_boundary_id))
              {
               right_right_top_node_pt=nod_pt;
              }
             else if (nod_pt->is_on_boundary(Contact_boundary_id))
              {
               left_right_top_node_pt=nod_pt;
              }
            }
          }
          break;
         default:
          // Never get here...
          oomph_info << "Never get here! b = " << b << "\n";
          abort();
         }
 #endif
        // Loop over the nodes
        unsigned nnod=el_pt->nnode();
        for (unsigned j=0;j<nnod;j++)
         {
          Node* nod_pt = el_pt->node_pt(j);
          // Is the node also on side boundaries?
          if ((nod_pt->is_on_boundary(Left_boundary_id))||
              (nod_pt->is_on_boundary(Right_boundary_id)))
           {
            // How many nodal values were used by the "bulk" element
            // that originally created this node?
            unsigned n_bulk_value=el_pt->nbulk_value(j);
            // hierher: this statement is unlikely to be true. Fix!
            // The remaining ones are Lagrange multipliers and we pin them.
            unsigned nval=nod_pt->nvalue();
            for (unsigned j=n_bulk_value;j<nval;j++)
             {
              nod_pt->pin(j);
             }
           }
         }
       }
     }
 #ifndef STRUCTURED_MESH
    Vector<double> zeta_left(1);
    Vector<double> zeta_right(1);
    left_left_top_node_pt->get_coordinates_on_boundary(Left_top_boundary_id,
                                                       zeta_left);
    right_left_top_node_pt->get_coordinates_on_boundary(Left_top_boundary_id,
                                                        zeta_right);
    if (zeta_left[0]>zeta_right[0])
     {
      ProblemParameters::Boundary_geom_object_left.set_reversed();
      oomph_info << "left top is reversed\n";
     }
    else
     {
      ProblemParameters::Boundary_geom_object_left.set_non_reversed();
      oomph_info << "left top is not reversed\n";
     }
    left_contact_node_pt->get_coordinates_on_boundary(Contact_boundary_id,
                                                      zeta_left);
    right_contact_node_pt->get_coordinates_on_boundary(Contact_boundary_id,
                                                       zeta_right);
    if (zeta_left[0]>zeta_right[0])
     {
      ProblemParameters::Boundary_geom_object_contact.set_reversed();
      oomph_info << "contact is reversed\n";
     }
    else
     {
      ProblemParameters::Boundary_geom_object_contact.set_non_reversed();
      oomph_info << "contact is not reversed\n";
     }
    left_right_top_node_pt->get_coordinates_on_boundary(Right_top_boundary_id,
                                                        zeta_left);
    right_right_top_node_pt->get_coordinates_on_boundary(Right_top_boundary_id,
                                                         zeta_right);
    if (zeta_left[0]>zeta_right[0])
     {
      ProblemParameters::Boundary_geom_object_right.set_reversed();
      oomph_info << "right top is reversed\n";
     }
    else
     {
      ProblemParameters::Boundary_geom_object_right.set_non_reversed();
      oomph_info << "right top is not reversed\n";
     }
 #endif
   } // end of create_displ_imposition_elements
References oomph::Mesh::add_element_pt(), b, Global_Physical_Variables::Boundary_geom_object, ProblemParameters::Boundary_geom_object_contact, ProblemParameters::Boundary_geom_object_left, ProblemParameters::Boundary_geom_object_right, ContactProblem< ELEMENT >::Bulk_mesh_pt, ContactProblem< ELEMENT >::Contact_boundary_id, ContactProblem< ELEMENT >::Displ_imposition_mesh_pt, e(), oomph::Node::get_coordinates_on_boundary(), oomph::Node::is_on_boundary(), j, ContactProblem< ELEMENT >::Left_boundary_id, ContactProblem< ELEMENT >::Left_top_boundary_id, nb, oomph::FaceElement::nbulk_value(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::Data::nvalue(), oomph::oomph_info, oomph::Data::pin(), ContactProblem< ELEMENT >::Right_boundary_id, ContactProblem< ELEMENT >::Right_top_boundary_id, oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::set_boundary_shape_geom_object_pt(), WarpedLine::set_non_reversed(), and WarpedLine::set_reversed().
Referenced by ContactProblem< ELEMENT >::actions_after_adapt().
create_displ_imposition_elements() [2/2]
template<class ELEMENT > void ContactProblem< ELEMENT >::create_displ_imposition_elements () inline private
Create elements that enforce prescribed boundary motion by Lagrange multipliers
   {
    Vector<unsigned> boundary_id;
    boundary_id.push_back(Contact_boundary_id);
 #ifndef STRUCTURED_MESH
    Node* left_contact_node_pt=0;
    Node* right_contact_node_pt=0;
    Node* left_left_top_node_pt=0;
    Node* right_left_top_node_pt=0;
    Node* left_right_top_node_pt=0;
    Node* right_right_top_node_pt=0;
    boundary_id.push_back(Left_top_boundary_id);
    boundary_id.push_back(Right_top_boundary_id);
 #endif
    unsigned nb=boundary_id.size();
    for (unsigned bb=0;bb<nb;bb++)
     {
      unsigned b=boundary_id[bb];
      // How many bulk elements are adjacent to boundary b?
      unsigned n_element = Bulk_mesh_pt->nboundary_element(b);
      // Loop over the bulk elements adjacent to boundary b?
      for(unsigned e=0;e<n_element;e++)
       {
        // Get pointer to the bulk element that is adjacent to boundary b
        ELEMENT* bulk_elem_pt = dynamic_cast<ELEMENT*>(
         Bulk_mesh_pt->boundary_element_pt(b,e));
        //Find the index of the face of element e along boundary b
        int face_index = Bulk_mesh_pt->face_index_at_boundary(b,e);
        // Create new element
        ImposeDisplacementByLagrangeMultiplierElement<ELEMENT>* el_pt=
         new ImposeDisplacementByLagrangeMultiplierElement<ELEMENT>(
          bulk_elem_pt,face_index);
        // Add to mesh
        Displ_imposition_mesh_pt->add_element_pt(el_pt);
 #ifdef STRUCTURED_MESH
        // Set the GeomObject that defines the boundary shape and
        // specify which bulk boundary we are attached to (needed to extract
        // the boundary coordinate from the bulk nodes)
        el_pt->set_boundary_shape_geom_object_pt(
         &ProblemParameters::Boundary_geom_object,b);
 #else
        switch(b)
         {
         case Contact_boundary_id:
          // Set the GeomObject that defines the boundary shape and
          // specify which bulk boundary we are attached to (needed to extract
          // the boundary coordinate from the bulk nodes)
          el_pt->set_boundary_shape_geom_object_pt(
           &ProblemParameters::Boundary_geom_object_contact,b);
          {
           unsigned nnod=el_pt->nnode();
           for (unsigned j=0;j<nnod;j++)
            {
             Node* nod_pt=el_pt->node_pt(j);
             if (nod_pt->is_on_boundary(Left_top_boundary_id))
              {
               left_contact_node_pt=nod_pt;
              }
             else if (nod_pt->is_on_boundary(Right_top_boundary_id))
              {
               right_contact_node_pt=nod_pt;
              }
            }
          }
          break;
         case Left_top_boundary_id:
          // Set the GeomObject that defines the boundary shape and
          // specify which bulk boundary we are attached to (needed to extract
          // the boundary coordinate from the bulk nodes)
          el_pt->set_boundary_shape_geom_object_pt(
           &ProblemParameters::Boundary_geom_object_left,b);
          {
           unsigned nnod=el_pt->nnode();
           for (unsigned j=0;j<nnod;j++)
            {
             Node* nod_pt=el_pt->node_pt(j);
             if (nod_pt->is_on_boundary(Left_boundary_id))
              {
               left_left_top_node_pt=nod_pt;
              }
             else if (nod_pt->is_on_boundary(Contact_boundary_id))
              {
               right_left_top_node_pt=nod_pt;
              }
            }
          }
          break;
         case Right_top_boundary_id:
          // Set the GeomObject that defines the boundary shape and
          // specify which bulk boundary we are attached to (needed to extract
          // the boundary coordinate from the bulk nodes)
          el_pt->set_boundary_shape_geom_object_pt(
           &ProblemParameters::Boundary_geom_object_right,b);
          {
           unsigned nnod=el_pt->nnode();
           for (unsigned j=0;j<nnod;j++)
            {
             Node* nod_pt=el_pt->node_pt(j);
             if (nod_pt->is_on_boundary(Right_boundary_id))
              {
               right_right_top_node_pt=nod_pt;
              }
             else if (nod_pt->is_on_boundary(Contact_boundary_id))
              {
               left_right_top_node_pt=nod_pt;
              }
            }
          }
          break;
         default:
          // Never get here...
          oomph_info << "Never get here! b = " << b << "\n";
          abort();
         }
 #endif
        // Loop over the nodes
        unsigned nnod=el_pt->nnode();
        for (unsigned j=0;j<nnod;j++)
         {
          Node* nod_pt = el_pt->node_pt(j);
          // Is the node also on side boundaries?
          if ((nod_pt->is_on_boundary(Left_boundary_id))||
              (nod_pt->is_on_boundary(Right_boundary_id)))
           {
            // How many nodal values were used by the "bulk" element
            // that originally created this node?
            unsigned n_bulk_value=el_pt->nbulk_value(j);
            // The remaining ones are Lagrange multipliers and we pin them.
            unsigned nval=nod_pt->nvalue();
            for (unsigned j=n_bulk_value;j<nval;j++)
             {
              nod_pt->pin(j);
             }
           }
         }
       }
     }
 #ifndef STRUCTURED_MESH
    Vector<double> zeta_left(1);
    Vector<double> zeta_right(1);
    left_left_top_node_pt->get_coordinates_on_boundary(Left_top_boundary_id,
                                                       zeta_left);
    right_left_top_node_pt->get_coordinates_on_boundary(Left_top_boundary_id,
                                                        zeta_right);
    if (zeta_left[0]>zeta_right[0])
     {
      ProblemParameters::Boundary_geom_object_left.set_reversed();
      oomph_info << "left top is reversed\n";
     }
    else
     {
      ProblemParameters::Boundary_geom_object_left.set_non_reversed();
      oomph_info << "left top is not reversed\n";
     }
    left_contact_node_pt->get_coordinates_on_boundary(Contact_boundary_id,
                                                      zeta_left);
    right_contact_node_pt->get_coordinates_on_boundary(Contact_boundary_id,
                                                       zeta_right);
    if (zeta_left[0]>zeta_right[0])
     {
      ProblemParameters::Boundary_geom_object_contact.set_reversed();
      oomph_info << "contact is reversed\n";
     }
    else
     {
      ProblemParameters::Boundary_geom_object_contact.set_non_reversed();
      oomph_info << "contact is not reversed\n";
     }
    left_right_top_node_pt->get_coordinates_on_boundary(Right_top_boundary_id,
                                                        zeta_left);
    right_right_top_node_pt->get_coordinates_on_boundary(Right_top_boundary_id,
                                                         zeta_right);
    if (zeta_left[0]>zeta_right[0])
     {
      ProblemParameters::Boundary_geom_object_right.set_reversed();
      oomph_info << "right top is reversed\n";
     }
    else
     {
      ProblemParameters::Boundary_geom_object_right.set_non_reversed();
      oomph_info << "right top is not reversed\n";
     }
 #endif
   } // end of create_displ_imposition_elements
References b, Global_Physical_Variables::Boundary_geom_object, ProblemParameters::Boundary_geom_object_contact, ProblemParameters::Boundary_geom_object_left, ProblemParameters::Boundary_geom_object_right, e(), oomph::Node::get_coordinates_on_boundary(), oomph::Node::is_on_boundary(), j, nb, oomph::FaceElement::nbulk_value(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::Data::nvalue(), oomph::oomph_info, oomph::Data::pin(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::set_boundary_shape_geom_object_pt(), WarpedLine::set_non_reversed(), and WarpedLine::set_reversed().
create_imposed_heat_flux_elements_on_boulder()
template<class ELEMENT > void ContactProblem< ELEMENT >::create_imposed_heat_flux_elements_on_boulder () inline private
Create imposed heat flux elements on surface of boulder.
   {
    // How many bulk elements are adjacent to boundary b?
    unsigned b=Boulder_top_boundary_id;
    unsigned n_element = Boulder_mesh_pt->nboundary_element(b);
    // Loop over the bulk elements adjacent to boundary b?
    for(unsigned e=0;e<n_element;e++)
     {
      // Get pointer to the bulk element that is adjacent to boundary b
      ProjectableUnsteadyHeatElement<TUnsteadyHeatElement<2,3> >* bulk_elem_pt =
       dynamic_cast<ProjectableUnsteadyHeatElement<TUnsteadyHeatElement<2,3> >*>(
        Boulder_mesh_pt->boundary_element_pt(b,e));
      //What is the face index of element e along boundary b
      int face_index = Boulder_mesh_pt->face_index_at_boundary(b,e);
      // Build the corresponding flux element
      UnsteadyHeatFluxElement
       <ProjectableUnsteadyHeatElement<TUnsteadyHeatElement<2,3> > >*
       flux_element_pt = new
       UnsteadyHeatFluxElement
       <ProjectableUnsteadyHeatElement<TUnsteadyHeatElement<2,3> > >(
        bulk_elem_pt,face_index);
      // Pass pointer to heat flux
      flux_element_pt->flux_fct_pt() = &ProblemParameters::unit_flux;
      //Add the contact element to the surface mesh
      Boulder_surface_heat_flux_mesh_pt->add_element_pt(flux_element_pt);
     } //end of loop over bulk elements adjacent to boundary b
   }
References oomph::Mesh::add_element_pt(), b, ContactProblem< ELEMENT >::Boulder_mesh_pt, ContactProblem< ELEMENT >::Boulder_surface_heat_flux_mesh_pt, ContactProblem< ELEMENT >::Boulder_top_boundary_id, oomph::Mesh::boundary_element_pt(), e(), oomph::Mesh::face_index_at_boundary(), oomph::Mesh::nboundary_element(), and ProblemParameters::unit_flux().
Referenced by ContactProblem< ELEMENT >::actions_after_adapt().
delete_contact_elements() [1/4]
template<class ELEMENT > void ContactProblem< ELEMENT >::delete_contact_elements () inline private
Delete contact elements.
   {
    // How many surface elements are in the surface mesh
    unsigned n_element = Surface_contact_mesh_pt->nelement();
    // Loop over the surface elements
    for(unsigned e=0;e<n_element;e++)
     {
      // Kill surface element
      delete Surface_contact_mesh_pt->element_pt(e);
     }
    // Wipe the mesh
    Surface_contact_mesh_pt->flush_element_and_node_storage();
    // How many surface elements are in the surface mesh
    n_element = Boulder_surface_contact_mesh_pt->nelement();
    // Loop over the surface elements
    for(unsigned e=0;e<n_element;e++)
     {
      // Kill surface element
      delete Boulder_surface_contact_mesh_pt->element_pt(e);
     }
    // Wipe the mesh
    Boulder_surface_contact_mesh_pt->flush_element_and_node_storage();
    // How many surface elements are in the surface mesh
    n_element = Boulder_surface_heat_flux_mesh_pt->nelement();
    // Loop over the surface elements
    for(unsigned e=0;e<n_element;e++)
     {
      // Kill surface element
      delete Boulder_surface_heat_flux_mesh_pt->element_pt(e);
     }
    // Wipe the mesh
    Boulder_surface_heat_flux_mesh_pt->flush_element_and_node_storage();
   }
References ContactProblem< ELEMENT >::Boulder_surface_contact_mesh_pt, ContactProblem< ELEMENT >::Boulder_surface_heat_flux_mesh_pt, e(), oomph::Mesh::element_pt(), oomph::Mesh::flush_element_and_node_storage(), oomph::Mesh::nelement(), and ContactProblem< ELEMENT >::Surface_contact_mesh_pt.
Referenced by ContactProblem< ELEMENT >::actions_before_adapt().
delete_contact_elements() [2/4]
template<class ELEMENT > void ContactProblem< ELEMENT >::delete_contact_elements () inline private
Delete contact elements.
   {
    // How many surface elements are in the surface mesh
    unsigned n_element = Surface_contact_mesh_pt->nelement();
    // Loop over the surface elements
    for(unsigned e=0;e<n_element;e++)
     {
      // Kill surface element
      delete Surface_contact_mesh_pt->element_pt(e);
     }
    // Wipe the mesh
    Surface_contact_mesh_pt->flush_element_and_node_storage();
   }
References e().
delete_contact_elements() [3/4]
template<class ELEMENT > void ContactProblem< ELEMENT >::delete_contact_elements () inline private
Delete contact elements.
   {
    // How many surface elements are in the surface mesh
    unsigned n_element = Surface_contact_mesh_pt->nelement();
    // Loop over the surface elements
    for(unsigned e=0;e<n_element;e++)
     {
      // Kill surface element
      delete Surface_contact_mesh_pt->element_pt(e);
     }
    // Wipe the mesh
    Surface_contact_mesh_pt->flush_element_and_node_storage();
   }
References e().
delete_contact_elements() [4/4]
template<class ELEMENT > void ContactProblem< ELEMENT >::delete_contact_elements () inline private
Delete contact elements.
   {
    // How many surface elements are in the surface mesh
    unsigned n_element = Surface_contact_mesh_pt->nelement();
    // Loop over the surface elements
    for(unsigned e=0;e<n_element;e++)
     {
      // Kill surface element
      delete Surface_contact_mesh_pt->element_pt(e);
     }
    // Wipe the mesh
    Surface_contact_mesh_pt->flush_element_and_node_storage();
   }
References e().
delete_displ_imposition_elements() [1/2]
template<class ELEMENT > void ContactProblem< ELEMENT >::delete_displ_imposition_elements () inline private
Delete elements that enforce prescribed boundary motion by Lagrange multiplliers
   {
    // How many surface elements are in the surface mesh
    unsigned n_element = Displ_imposition_mesh_pt->nelement();
    // Loop over the surface elements
    for(unsigned e=0;e<n_element;e++)
     {
      // Kill surface element
      delete Displ_imposition_mesh_pt->element_pt(e);
     }
    // Wipe the mesh
    Displ_imposition_mesh_pt->flush_element_and_node_storage();
   }
References ContactProblem< ELEMENT >::Displ_imposition_mesh_pt, e(), oomph::Mesh::element_pt(), oomph::Mesh::flush_element_and_node_storage(), and oomph::Mesh::nelement().
Referenced by ContactProblem< ELEMENT >::actions_before_adapt().
delete_displ_imposition_elements() [2/2]
template<class ELEMENT > void ContactProblem< ELEMENT >::delete_displ_imposition_elements () inline private
Delete elements that enforce prescribed boundary motion by Lagrange multiplliers
   {
    // How many surface elements are in the surface mesh
    unsigned n_element = Displ_imposition_mesh_pt->nelement();
    // Loop over the surface elements
    for(unsigned e=0;e<n_element;e++)
     {
      // Kill surface element
      delete Displ_imposition_mesh_pt->element_pt(e);
     }
    // Wipe the mesh
    Displ_imposition_mesh_pt->flush_element_and_node_storage();
   }
References e().
doc_solution() [1/4]
template<class ELEMENT > void ContactProblem< ELEMENT >::doc_solution
Doc the solution.
 {
  oomph_info << "Outputting for step: " << Doc_info.number() << std::endl;
  ofstream some_file;
  char filename[100];
  // Write restart file
 /* sprintf(filename,"%s/restart%i.dat",doc_info.directory().c_str(),
          doc_info.number());
  some_file.open(filename);
  dump(some_file);
  some_file.close();*/
  // Number of plot points
  unsigned npts;
  npts=3;
  // Output solution
  sprintf(filename,"%s/soln%i.dat",Doc_info.directory().c_str(),
          Doc_info.number());
  some_file.open(filename);
  Bulk_mesh_pt->output(some_file,npts);
  some_file.close();
  // Output solution coarsely (only element vertices for easier
  // mesh visualisation)
  sprintf(filename,"%s/coarse_soln%i.dat",Doc_info.directory().c_str(),
          Doc_info.number());
  some_file.open(filename);
  Bulk_mesh_pt->output(some_file,2);
  some_file.close();
  // Output solution
  sprintf(filename,"%s/boulder_soln%i.dat",Doc_info.directory().c_str(),
          Doc_info.number());
  some_file.open(filename);
  Boulder_mesh_pt->output(some_file,npts);
  some_file.close();
   // Output contact region on boulder
  sprintf(filename,"%s/boulder_contact%i.dat",Doc_info.directory().c_str(),
          Doc_info.number());
  some_file.open(filename);
  Boulder_surface_contact_mesh_pt->output(some_file,npts);
  some_file.close();
   // Output contact region on boulder
  sprintf(filename,"%s/boulder_heat_flux%i.dat",Doc_info.directory().c_str(),
          Doc_info.number());
  some_file.open(filename);
  Boulder_surface_heat_flux_mesh_pt->output(some_file,npts);
  some_file.close();
  // Output solution coarsely (only element vertices for easier
  // mesh visualisation)
  sprintf(filename,"%s/boulder_coarse_soln%i.dat",Doc_info.directory().c_str(),
          Doc_info.number());
  some_file.open(filename);
  Boulder_mesh_pt->output(some_file,2);
  some_file.close();
  // Output contact elements
  sprintf(filename,"%s/imposed_displ%i.dat",Doc_info.directory().c_str(),
          Doc_info.number());
  some_file.open(filename);
  Displ_imposition_mesh_pt->output(some_file);
  some_file.close();
  // Output contact elements
  sprintf(filename,"%s/contact%i.dat",Doc_info.directory().c_str(),
          Doc_info.number());
  some_file.open(filename);
  unsigned nel=Surface_contact_mesh_pt->nelement();
  for (unsigned e=0;e<nel;e++)
   {
    dynamic_cast<HeatedLinearSurfaceContactElement<ELEMENT>* >(
     Surface_contact_mesh_pt->element_pt(e))->output(some_file,3);
   }
  some_file.close();
  // Output integration points of contact elements
  sprintf(filename,"%s/contact_integration_points%i.dat",
          Doc_info.directory().c_str(),
          Doc_info.number());
  some_file.open(filename);
  Vector<double> s(1);
  Vector<double> x(2);
  nel=Surface_contact_mesh_pt->nelement();
  for (unsigned e=0;e<nel;e++)
   {
    HeatedLinearSurfaceContactElement<ELEMENT>* el_pt=
     dynamic_cast<HeatedLinearSurfaceContactElement<ELEMENT>* >(
      Surface_contact_mesh_pt->element_pt(e));
    unsigned nint=el_pt->integral_pt()->nweight();
    for (unsigned j=0;j<nint;j++)
     {
      s[0]=el_pt->integral_pt()->knot(j,0);
      el_pt->interpolated_x(s,x);
      some_file << x[0] << " " << x[1] << std::endl;
     }
   }
  some_file.close();
  // Output penetrator
  sprintf(filename,"%s/penetrator%i.dat",Doc_info.directory().c_str(),
          Doc_info.number());
  some_file.open(filename);
  unsigned n=500;
  ProblemParameters::Penetrator_pt->output(some_file,n);
  some_file.close();
  // Output contact elements and assemble total resulting force
  Vector<double> total_contact_force(2,0.0);
  Vector<double> contact_force(2,0.0);
  sprintf(filename,"%s/contact%i.dat",Doc_info.directory().c_str(),
          Doc_info.number());
  some_file.open(filename);
  nel=Surface_contact_mesh_pt->nelement();
  for (unsigned e=0;e<nel;e++)
   {
    HeatedLinearSurfaceContactElement<ELEMENT>* el_pt=
     dynamic_cast<HeatedLinearSurfaceContactElement<ELEMENT>*>(
      Surface_contact_mesh_pt->element_pt(e));
    el_pt->output(some_file,3);
    el_pt->resulting_contact_force(contact_force);
    total_contact_force[0]+=contact_force[0];
    total_contact_force[1]+=contact_force[1];
   }
  some_file.close();
  double radius_of_elastic_body=0.0;
 #ifdef STRUCTURED_MESH
  radius_of_elastic_body=
   ProblemParameters::Boundary_geom_object.radius();
 #else
  radius_of_elastic_body=
   ProblemParameters::Boundary_geom_object_contact.radius();
 #endif
  // Get half-width of Hertz contact region
  double b_hertz=0.0;
  if (std::fabs(total_contact_force[1])>1.0e-16)
   {
    b_hertz=sqrt(4.0*(1.0-ProblemParameters::Nu*ProblemParameters::Nu)/
                 (MathematicalConstants::Pi*
                  (-1.0/radius_of_elastic_body+
                   1.0/ProblemParameters::Radius))*
                 (-total_contact_force[1]));
   }
  oomph_info << "b_hertz " << b_hertz <<  std::endl;
  double p_max_hertz = 0.0;
  if(b_hertz!=0.0)
   {
    p_max_hertz=2.0*total_contact_force[1]/
    (MathematicalConstants::Pi*b_hertz);
   }
  // Output Hertzian pressure contact distribution
  sprintf(filename,"%s/hertz%i.dat",Doc_info.directory().c_str(),
          Doc_info.number());
  some_file.open(filename);
  n=500;
  HeatedCircularPenetratorElement* pen_el_pt=
   dynamic_cast<HeatedCircularPenetratorElement*>(
    ProblemParameters::Penetrator_pt);
  Vector<double> centre(2);
  if (pen_el_pt!=0)
   {
    Vector<double> my_centre(pen_el_pt->centre());
    centre[0]=my_centre[0];
    centre[1]=my_centre[1];
   }
  else
   {
    centre[0]=ProblemParameters::Centre[0];
    centre[1]=ProblemParameters::Centre[1];
   }
  double x_c=centre[0];
  double width=2.0*b_hertz;
  for (unsigned j=0;j<n;j++)
   {
    double x=x_c-0.5*width+width*double(j)/double(n-1);
    double p=0.0;
    if (abs((x-x_c))<b_hertz)
     {
      p=p_max_hertz*sqrt(1.0-pow((x-x_c)/b_hertz,2));
     }
    some_file << x << " 0.0 " << p << std::endl;
   }
  some_file.close();
  double target_weight=0.0;
  if (pen_el_pt!=0)
   {
    target_weight=pen_el_pt->target_weight();
   }
  // double angle=0.0;
  // if (pen_el_pt!=0)
  //  {
  //   angle=pen_el_pt->angle();
  //  }
  // Write trace file
  Trace_file << total_contact_force[0] << " "
             << total_contact_force[1] << " "
             << centre[0] << " "
             << centre[1] << " "
             << target_weight << " "
   //ALH/hierher Suppressed so that validation tests pass
   //For small changes in loading a different contact point can be selected
   //which means that different angles are computed
   // << angle << " "
             << std::endl;
  //Increment counter for solutions
  Doc_info.number()++;
 } // end of doc_solution
References abs(), Global_Physical_Variables::Boundary_geom_object, ProblemParameters::Boundary_geom_object_contact, ProblemParameters::Centre, HeatedCircularPenetratorElement::centre(), oomph::DocInfo::directory(), GlobalParameters::Doc_info, e(), boost::multiprecision::fabs(), MergeRestartFiles::filename, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), j, oomph::Integral::knot(), n, ProblemParameters::Nu, oomph::DocInfo::number(), oomph::Integral::nweight(), oomph::oomph_info, oomph::HeatedLinearSurfaceContactElement< ELEMENT >::output(), output(), oomph::Penetrator::output(), p, ProblemParameters::Penetrator_pt, BiharmonicTestFunctions2::Pi, Eigen::ArrayBase< Derived >::pow(), ProblemParameters::Radius, WarpedLine::radius(), oomph::LinearSurfaceContactElement< ELEMENT >::resulting_contact_force(), s, sqrt(), HeatedCircularPenetratorElement::target_weight(), oomph::Problem_Parameter::Trace_file, and plotDoE::x.
doc_solution() [2/4]
template<class ELEMENT > void ContactProblem< ELEMENT >::doc_solution ()
Doc the solution.
doc_solution() [3/4]
template<class ELEMENT > void ContactProblem< ELEMENT >::doc_solution ()
Doc the solution.
doc_solution() [4/4]
template<class ELEMENT > void ContactProblem< ELEMENT >::doc_solution ()
Doc the solution.
global_temporal_error_norm()
template<class ELEMENT > double ContactProblem< ELEMENT >::global_temporal_error_norm () inline virtual
Dummy global error norm for adaptive time-stepping.
Reimplemented from oomph::Problem.
 {return 0.0;}
switch_to_displ_control() [1/3]
template<class ELEMENT > void ContactProblem< ELEMENT >::switch_to_displ_control () inline
Switch to displ control.
   {
    dynamic_cast<HeatedCircularPenetratorElement*>(
     ProblemParameters::Penetrator_pt)->impose_yc(&ProblemParameters::Y_c);
    dynamic_cast<HeatedCircularPenetratorElement*>(
     ProblemParameters::Penetrator_pt)->impose_rotation_angle(
     &ProblemParameters::Rotation_angle);
    ProblemParameters::Y_c=Control_node_pt->x(1)+Control_node_pt->value(1);
   }
References ContactProblem< ELEMENT >::Control_node_pt, ProblemParameters::Penetrator_pt, ProblemParameters::Rotation_angle, oomph::Node::value(), oomph::Node::x(), and ProblemParameters::Y_c.
switch_to_displ_control() [2/3]
template<class ELEMENT > void ContactProblem< ELEMENT >::switch_to_displ_control () inline
Switch to displ control.
   {
    dynamic_cast<CircularPenetratorElement*>(
     ProblemParameters::Penetrator_pt)->impose_yc(&ProblemParameters::Y_c);
    dynamic_cast<CircularPenetratorElement*>(
     ProblemParameters::Penetrator_pt)->impose_rotation_angle(
     &ProblemParameters::Rotation_angle);
    ProblemParameters::Y_c=Control_node_pt->x(1)+Control_node_pt->value(1);
   }
References ProblemParameters::Penetrator_pt, ProblemParameters::Rotation_angle, and ProblemParameters::Y_c.
switch_to_displ_control() [3/3]
template<class ELEMENT > void ContactProblem< ELEMENT >::switch_to_displ_control () inline
Switch to displ control.
   {
    dynamic_cast<CircularPenetratorElement*>(
     ProblemParameters::Penetrator_pt)->impose_yc(&ProblemParameters::Y_c);
    dynamic_cast<CircularPenetratorElement*>(
     ProblemParameters::Penetrator_pt)->impose_rotation_angle(
     &ProblemParameters::Rotation_angle);
    ProblemParameters::Y_c=Control_node_pt->x(1);
   }
References ProblemParameters::Penetrator_pt, ProblemParameters::Rotation_angle, and ProblemParameters::Y_c.
switch_to_force_control() [1/3]
template<class ELEMENT > void ContactProblem< ELEMENT >::switch_to_force_control () inline
Switch to force control.
   {
    dynamic_cast<HeatedCircularPenetratorElement*>(
     ProblemParameters::Penetrator_pt)->impose_weight(
      &ProblemParameters::Weight);
    dynamic_cast<HeatedCircularPenetratorElement*>(
     ProblemParameters::Penetrator_pt)->impose_horizontal_force(
      &ProblemParameters::Horizontal_force);
    dynamic_cast<HeatedCircularPenetratorElement*>(
     ProblemParameters::Penetrator_pt)->set_equilibrium_target_forces();
    // Re-set contact mesh -- we now need to treat the positions
    // and penalty pressures of all nodes as external data of the
    // penetrator element!
    dynamic_cast<HeatedCircularPenetratorElement*>(
     ProblemParameters::Penetrator_pt)->set_contact_element_mesh_pt(
     Surface_contact_mesh_pt);
    // Reset penetrator because its equilibrium data (which is external
    // data for contact elements) has changed
    unsigned n_element=Surface_contact_mesh_pt->nelement();
    for(unsigned e=0;e<n_element;e++)
     {
      // Upcast from GeneralisedElement
      HeatedLinearSurfaceContactElement<ELEMENT> *el_pt =
       dynamic_cast<HeatedLinearSurfaceContactElement<ELEMENT>*>(
        Surface_contact_mesh_pt->element_pt(e));
      // Set pointer to penetrator
      el_pt->set_penetrator_pt(ProblemParameters::Penetrator_pt);
     }
    cout <<"New number of equations: " << assign_eqn_numbers() << std::endl;
   }
References oomph::Problem::assign_eqn_numbers(), e(), oomph::Mesh::element_pt(), ProblemParameters::Horizontal_force, oomph::Mesh::nelement(), ProblemParameters::Penetrator_pt, oomph::SurfaceContactElementBase< ELEMENT >::set_penetrator_pt(), ContactProblem< ELEMENT >::Surface_contact_mesh_pt, and ProblemParameters::Weight.
switch_to_force_control() [2/3]
template<class ELEMENT > void ContactProblem< ELEMENT >::switch_to_force_control () inline
Switch to force control.
   {
    dynamic_cast<CircularPenetratorElement*>(
     ProblemParameters::Penetrator_pt)->impose_weight(
      &ProblemParameters::Weight);
    dynamic_cast<CircularPenetratorElement*>(
     ProblemParameters::Penetrator_pt)->impose_horizontal_force(
      &ProblemParameters::Horizontal_force);
    dynamic_cast<CircularPenetratorElement*>(
     ProblemParameters::Penetrator_pt)->set_equilibrium_target_forces();
    // Re-set contact mesh -- we now need to treat the positions
    // and penalty pressures of all nodes as external data of the
    // penetrator element!
    dynamic_cast<CircularPenetratorElement*>(
     ProblemParameters::Penetrator_pt)->set_contact_element_mesh_pt(
     Surface_contact_mesh_pt);
    // Reset penetrator because its equilibrium data (which is external
    // data for contact elements) has changed
    unsigned n_element=Surface_contact_mesh_pt->nelement();
    for(unsigned e=0;e<n_element;e++)
     {
      // Upcast from GeneralisedElement
      LinearSurfaceContactElement<ELEMENT> *el_pt =
       dynamic_cast<LinearSurfaceContactElement<ELEMENT>*>(
        Surface_contact_mesh_pt->element_pt(e));
      // Set pointer to penetrator
      el_pt->set_penetrator_pt(ProblemParameters::Penetrator_pt);
     }
    cout <<"New number of equations: " << assign_eqn_numbers() << std::endl;
   }
References e(), ProblemParameters::Horizontal_force, ProblemParameters::Penetrator_pt, oomph::SurfaceContactElementBase< ELEMENT >::set_penetrator_pt(), and ProblemParameters::Weight.
switch_to_force_control() [3/3]
template<class ELEMENT > void ContactProblem< ELEMENT >::switch_to_force_control () inline
Switch to force control.
   {
    dynamic_cast<CircularPenetratorElement*>(
     ProblemParameters::Penetrator_pt)->impose_weight(
      &ProblemParameters::Weight);
    dynamic_cast<CircularPenetratorElement*>(
     ProblemParameters::Penetrator_pt)->impose_horizontal_force(
      &ProblemParameters::Horizontal_force);
    dynamic_cast<CircularPenetratorElement*>(
     ProblemParameters::Penetrator_pt)->set_equilibrium_target_forces();
    // Re-set contact mesh -- we now need to treat the positions
    // and penalty pressures of all nodes as external data of the
    // penetrator element!
    dynamic_cast<CircularPenetratorElement*>(
     ProblemParameters::Penetrator_pt)->set_contact_element_mesh_pt(
     Surface_contact_mesh_pt);
    // Reset penetrator because its equilibrium data (which is external
    // data for contact elements) has changed
    unsigned n_element=Surface_contact_mesh_pt->nelement();
    for(unsigned e=0;e<n_element;e++)
     {
      // Upcast from GeneralisedElement
      NonlinearSurfaceContactElement<ELEMENT> *el_pt =
       dynamic_cast<NonlinearSurfaceContactElement<ELEMENT>*>(
        Surface_contact_mesh_pt->element_pt(e));
      // Set pointer to penetrator
      el_pt->set_penetrator_pt(ProblemParameters::Penetrator_pt);
     }
    cout <<"New number of equations: " << assign_eqn_numbers() << std::endl;
   }
References e(), ProblemParameters::Horizontal_force, ProblemParameters::Penetrator_pt, oomph::SurfaceContactElementBase< ELEMENT >::set_penetrator_pt(), and ProblemParameters::Weight.
Member Data Documentation
Backed_up_surface_contact_mesh_pt
template<class ELEMENT > BackupMeshForProjection< TElement< 1, 3 > > * ContactProblem< ELEMENT >::Backed_up_surface_contact_mesh_pt private
Backup of Surface_contact_mesh_pt so the Lagrange multipliers can be projected across
Referenced by ContactProblem< ELEMENT >::actions_after_adapt(), and ContactProblem< ELEMENT >::actions_before_adapt().
Bottom_boundary_id
template<class ELEMENT > unsigned ContactProblem< ELEMENT >::Bottom_boundary_id private
ID of bottom boundary.
Boulder_mesh_pt
template<class ELEMENT > RefineableTriangleMesh<ProjectableUnsteadyHeatElement <TUnsteadyHeatElement<2,3> > >* ContactProblem< ELEMENT >::Boulder_mesh_pt private
Pointer to boulder mesh.
Referenced by ContactProblem< ELEMENT >::actions_before_adapt(), ContactProblem< ELEMENT >::create_contact_heat_elements_on_boulder(), and ContactProblem< ELEMENT >::create_imposed_heat_flux_elements_on_boulder().
Boulder_surface_contact_mesh_pt
template<class ELEMENT > Mesh* ContactProblem< ELEMENT >::Boulder_surface_contact_mesh_pt private
Pointer to the "surface" mesh on boulder that applies flux boundary condition to boulder
Referenced by ContactProblem< ELEMENT >::complete_problem_setup(), ContactProblem< ELEMENT >::create_contact_heat_elements_on_boulder(), and ContactProblem< ELEMENT >::delete_contact_elements().
Boulder_surface_heat_flux_mesh_pt
template<class ELEMENT > Mesh* ContactProblem< ELEMENT >::Boulder_surface_heat_flux_mesh_pt private
Mesh of elements that imposed unit heat flux on top of boulder.
Referenced by ContactProblem< ELEMENT >::create_imposed_heat_flux_elements_on_boulder(), and ContactProblem< ELEMENT >::delete_contact_elements().
Bulk_mesh_pt
template<class ELEMENT > RefineableSolidTriangleMesh< ELEMENT > * ContactProblem< ELEMENT >::Bulk_mesh_pt private
Pointer to bulk mesh.
Referenced by ContactProblem< ELEMENT >::actions_after_adapt(), ContactProblem< ELEMENT >::actions_before_adapt(), ContactProblem< ELEMENT >::actions_before_implicit_timestep(), ContactProblem< ELEMENT >::actions_before_newton_solve(), ContactProblem< ELEMENT >::complete_problem_setup(), ContactProblem< ELEMENT >::create_contact_elements(), and ContactProblem< ELEMENT >::create_displ_imposition_elements().
Contact_boundary_id
template<class ELEMENT > unsigned ContactProblem< ELEMENT >::Contact_boundary_id private
ID of contact boundary.
Contact_boundary_pt
template<class ELEMENT > TriangleMeshPolyLine * ContactProblem< ELEMENT >::Contact_boundary_pt private
Contact boundary in its poly line representation.
Contact_id
template<class ELEMENT > unsigned ContactProblem< ELEMENT >::Contact_id private
ID of additional nodal values created by contact elements to store contact pressure/Lagr. mult.
Referenced by ContactProblem< ELEMENT >::complete_problem_setup(), and ContactProblem< ELEMENT >::create_contact_elements().
Control_node_pt
template<class ELEMENT > SolidNode * ContactProblem< ELEMENT >::Control_node_pt private
Pointer to control node where Lagrange multiplier (contact pressure) is "pseudo-hijacked" to impose either displacement or weight constraint.
Referenced by ContactProblem< ELEMENT >::actions_before_adapt(), ContactProblem< ELEMENT >::complete_problem_setup(), and ContactProblem< ELEMENT >::switch_to_displ_control().
Displ_imposition_mesh_pt
template<class ELEMENT > SolidMesh * ContactProblem< ELEMENT >::Displ_imposition_mesh_pt private
Pointers to meshes of Lagrange multiplier elements to impose displacement of top boundary
Referenced by ContactProblem< ELEMENT >::actions_after_adapt(), ContactProblem< ELEMENT >::actions_before_adapt(), ContactProblem< ELEMENT >::create_displ_imposition_elements(), and ContactProblem< ELEMENT >::delete_displ_imposition_elements().
Doc_info
template<class ELEMENT > DocInfo ContactProblem< ELEMENT >::Doc_info private
Left_boundary_id
template<class ELEMENT > unsigned ContactProblem< ELEMENT >::Left_boundary_id private
ID of left boundary.
Left_top_boundary_id
template<class ELEMENT > unsigned ContactProblem< ELEMENT >::Left_top_boundary_id private
ID of top left boundary.
Maximum_element_length_on_boulder_boundary
template<class ELEMENT > double ContactProblem< ELEMENT >::Maximum_element_length_on_boulder_boundary private
Maximum_element_length_on_contact_boundary
template<class ELEMENT > double ContactProblem< ELEMENT >::Maximum_element_length_on_contact_boundary private
Max. element length on contact boundary.
Penetrator_mesh_pt
template<class ELEMENT > Mesh * ContactProblem< ELEMENT >::Penetrator_mesh_pt private
Penetrator mesh.
Referenced by ContactProblem< ELEMENT >::actions_before_adapt(), and ContactProblem< ELEMENT >::complete_problem_setup().
Right_boundary_id
template<class ELEMENT > unsigned ContactProblem< ELEMENT >::Right_boundary_id private
ID of right boundary.
Right_top_boundary_id
template<class ELEMENT > unsigned ContactProblem< ELEMENT >::Right_top_boundary_id private
ID of top right boundary.
Surface_contact_mesh_pt
template<class ELEMENT > Mesh * ContactProblem< ELEMENT >::Surface_contact_mesh_pt private
Pointer to the "surface" contact mesh.
Pointer to the "surface" mesh.
Referenced by ContactProblem< ELEMENT >::actions_after_adapt(), ContactProblem< ELEMENT >::actions_before_adapt(), ContactProblem< ELEMENT >::complete_problem_setup(), ContactProblem< ELEMENT >::create_contact_elements(), ContactProblem< ELEMENT >::delete_contact_elements(), and ContactProblem< ELEMENT >::switch_to_force_control().
Trace_file
template<class ELEMENT > ofstream ContactProblem< ELEMENT >::Trace_file private
Trace file.
X_ll
template<class ELEMENT > double ContactProblem< ELEMENT >::X_ll private
x coordinate of lower left corner
X_ur
template<class ELEMENT > double ContactProblem< ELEMENT >::X_ur private
x coordinate of upper right corner
Xc_old
template<class ELEMENT > double ContactProblem< ELEMENT >::Xc_old private
x coordinate of old control node
Referenced by ContactProblem< ELEMENT >::actions_before_adapt(), and ContactProblem< ELEMENT >::complete_problem_setup().
Y_ll
template<class ELEMENT > double ContactProblem< ELEMENT >::Y_ll private
y coordinate of lower left corner
Y_ur
template<class ELEMENT > double ContactProblem< ELEMENT >::Y_ur private
y coordinate of upper right corner
The documentation for this class was generated from the following files:
heated_linear_solid_contact_with_gravity.cc
linear_solid_contact_with_gravity.cc
solid_contact.cc
solid_contact_with_gravity.cc