MercuryDPM: Eigen::internal::kernel_retval< FullPivLU< MatrixType_, PermutationIndex_ > > Struct Template Reference
Eigen::internal::kernel_retval< FullPivLU< MatrixType_, PermutationIndex_ > > Struct Template Reference
#include <FullPivLU.h>
Public Types
enum { MaxSmallDimAtCompileTime = min_size_prefer_fixed(MatrixType::MaxColsAtCompileTime, MatrixType::MaxRowsAtCompileTime) }
using DecompositionType = FullPivLU< MatrixType_, PermutationIndex_ >
Public Types inherited from Eigen::internal::kernel_retval_base< FullPivLU< MatrixType_, PermutationIndex_ > >
typedef FullPivLU< MatrixType_, PermutationIndex_ > DecompositionType
typedef ReturnByValue< kernel_retval_base > Base
Public Types inherited from Eigen::ReturnByValue< Derived >
typedef internal::traits< Derived >::ReturnType ReturnType
typedef internal::dense_xpr_base< ReturnByValue >::type Base
Public Member Functions
template<typename Dest >
void evalTo (Dest &dst) const
Public Member Functions inherited from Eigen::internal::kernel_retval_base< FullPivLU< MatrixType_, PermutationIndex_ > >
kernel_retval_base (const DecompositionType &dec)
Index rows () const
Index cols () const
Index rank () const
const DecompositionType & dec () const
void evalTo (Dest &dst) const
Public Member Functions inherited from Eigen::ReturnByValue< Derived >
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
const Unusable & coeff (Index) const
const Unusable & coeff (Index, Index) const
Unusable & coeffRef (Index)
Unusable & coeffRef (Index, Index)
Additional Inherited Members
Protected Attributes inherited from Eigen::internal::kernel_retval_base< FullPivLU< MatrixType_, PermutationIndex_ > >
const DecompositionType & m_dec
Index m_rank
Index m_cols
Member Typedef Documentation
DecompositionType
template<typename MatrixType_ , typename PermutationIndex_ > using Eigen::internal::kernel_retval< FullPivLU< MatrixType_, PermutationIndex_ > >::DecompositionType = FullPivLU<MatrixType_, PermutationIndex_>
Member Enumeration Documentation
anonymous enum
template<typename MatrixType_ , typename PermutationIndex_ > anonymous enum
Enumerator
MaxSmallDimAtCompileTime
        {
     MaxSmallDimAtCompileTime = min_size_prefer_fixed(MatrixType::MaxColsAtCompileTime, MatrixType::MaxRowsAtCompileTime)
   };
Member Function Documentation
evalTo()
template<typename MatrixType_ , typename PermutationIndex_ > template<typename Dest > void Eigen::internal::kernel_retval< FullPivLU< MatrixType_, PermutationIndex_ > >::evalTo (Dest & dst) const inline
{
     using std::abs;
     const Index cols = dec().matrixLU().cols(), dimker = cols - rank();
     if (dimker == 0) {
       // The Kernel is just {0}, so it doesn't have a basis properly speaking, but let's
       // avoid crashing/asserting as that depends on floating point calculations. Let's
       // just return a single column vector filled with zeros.
       dst.setZero();
       return;
     }
     /* Let us use the following lemma:
      *
      * Lemma: If the matrix A has the LU decomposition PAQ = LU,
      * then Ker A = Q(Ker U).
      *
      * Proof: trivial: just keep in mind that P, Q, L are invertible.
      */
     /* Thus, all we need to do is to compute Ker U, and then apply Q.
      *
      * U is upper triangular, with eigenvalues sorted so that any zeros appear at the end.
      * Thus, the diagonal of U ends with exactly
      * dimKer zero's. Let us use that to construct dimKer linearly
      * independent vectors in Ker U.
      */
     Matrix<Index, Dynamic, 1, 0, MaxSmallDimAtCompileTime, 1> pivots(rank());
     RealScalar premultiplied_threshold = dec().maxPivot() * dec().threshold();
     Index p = 0;
     for (Index i = 0; i < dec().nonzeroPivots(); ++i)
       if (abs(dec().matrixLU().coeff(i, i)) > premultiplied_threshold) pivots.coeffRef(p++) = i;
     eigen_internal_assert(p == rank());
     // we construct a temporaty trapezoid matrix m, by taking the U matrix and
     // permuting the rows and cols to bring the nonnegligible pivots to the top of
     // the main diagonal. We need that to be able to apply our triangular solvers.
     // FIXME when we get triangularView-for-rectangular-matrices, this can be simplified
     Matrix<typename MatrixType::Scalar, Dynamic, Dynamic, traits<MatrixType>::Options, MaxSmallDimAtCompileTime,
            MatrixType::MaxColsAtCompileTime>
         m(dec().matrixLU().block(0, 0, rank(), cols));
     for (Index i = 0; i < rank(); ++i) {
       if (i) m.row(i).head(i).setZero();
       m.row(i).tail(cols - i) = dec().matrixLU().row(pivots.coeff(i)).tail(cols - i);
     }
     m.block(0, 0, rank(), rank());
     m.block(0, 0, rank(), rank()).template triangularView<StrictlyLower>().setZero();
     for (Index i = 0; i < rank(); ++i) m.col(i).swap(m.col(pivots.coeff(i)));
     // ok, we have our trapezoid matrix, we can apply the triangular solver.
     // notice that the math behind this suggests that we should apply this to the
     // negative of the RHS, but for performance we just put the negative sign elsewhere, see below.
     m.topLeftCorner(rank(), rank()).template triangularView<Upper>().solveInPlace(m.topRightCorner(rank(), dimker));
     // now we must undo the column permutation that we had applied!
     for (Index i = rank() - 1; i >= 0; --i) m.col(i).swap(m.col(pivots.coeff(i)));
     // see the negative sign in the next line, that's what we were talking about above.
     for (Index i = 0; i < rank(); ++i) dst.row(dec().permutationQ().indices().coeff(i)) = -m.row(i).tail(dimker);
     for (Index i = rank(); i < cols; ++i) dst.row(dec().permutationQ().indices().coeff(i)).setZero();
     for (Index k = 0; k < dimker; ++k) dst.coeffRef(dec().permutationQ().indices().coeff(rank() + k), k) = Scalar(1);
   }
References abs(), block(), Eigen::PlainObjectBase< Derived >::coeff(), Eigen::Matrix< Scalar_, Rows_, Cols_, Options_, MaxRows_, MaxCols_ >::coeffRef(), cols, eigen_internal_assert, i, k, m, p, and setZero().
The documentation for this struct was generated from the following file:
FullPivLU.h