MercuryDPM: two_d_unsteady_heat.cc File Reference
unsteady_heat/two_d_unsteady_heat/two_d_unsteady_heat.cc File Reference
#include "generic.h"
#include "unsteady_heat.h"
#include "meshes/rectangular_quadmesh.h"
Classes
class UnsteadyHeatProblem< ELEMENT >
UnsteadyHeat problem.
Namespaces
ExactSolnForUnsteadyHeat
Namespace for unforced exact solution for UnsteadyHeat equation.
Functions
void ExactSolnForUnsteadyHeat::get_exact_u (const double &time, const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void ExactSolnForUnsteadyHeat::get_exact_u (const double &time, const Vector< double > &x, double &u)
Exact solution as a scalar.
void ExactSolnForUnsteadyHeat::get_source (const double &time, const Vector< double > &x, double &source)
Source function to make it an exact solution.
int main ()
Driver code for unsteady heat equation.
Function Documentation
main()
int main ()
Driver code for unsteady heat equation.
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
 {
  // Build problem
  UnsteadyHeatProblem<QUnsteadyHeatElement<2,4> >
   problem(&ExactSolnForUnsteadyHeat::get_source);
  // Setup labels for output
  DocInfo doc_info;
  // Output directory
  doc_info.set_directory("RESLT");
  // Output number
  doc_info.number()=0;
  // Open a trace file
  ofstream trace_file;
  char filename[100];
  sprintf(filename,"%s/trace.dat",doc_info.directory().c_str());
  trace_file.open(filename);
  trace_file << "VARIABLES=\"time\",\"u<SUB>FE</SUB>\","
             << "\"u<SUB>exact</SUB>\",\"norm of error\",\"norm of solution\""
             << std::endl;
  // Choose simulation interval and timestep
  double t_max=0.5;
  double dt=0.01;
  // Initialise timestep -- also sets the weights for all timesteppers
  // in the problem.
  problem.initialise_dt(dt);
  // Set IC
  problem.set_initial_condition();
  //Output initial condition
  problem.doc_solution(doc_info,trace_file);
  //Increment counter for solutions
  doc_info.number()++;
  // Find number of steps
  unsigned nstep = unsigned(t_max/dt);
  // Timestepping loop
  for (unsigned istep=0;istep<nstep;istep++)
   {
    cout << " Timestep " << istep << std::endl;
    // Take timestep
    problem.unsteady_newton_solve(dt);
    //Output solution
    problem.doc_solution(doc_info,trace_file);
    //Increment counter for solutions
    doc_info.number()++;
   }
  // Close trace file
  trace_file.close();
 }; // end of main
References oomph::DocInfo::directory(), MergeRestartFiles::filename, ExactSolnForUnsteadyHeat::get_source(), oomph::DocInfo::number(), problem, and oomph::DocInfo::set_directory().