MercuryDPM: TanhSolnForMultiPoisson Namespace Reference
TanhSolnForMultiPoisson Namespace Reference
Namespace for exact solution for MultiPoisson equation with "sharp step".
Functions
double scalar_soln (const Vector< double > &x)
Scalar solution.
double scalar_source (const Vector< double > &x)
Scalar source.
void get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void source_function (const Vector< double > &x, Vector< double > &source)
Source function required to make the solution above an exact solution.
Variables
double Alpha =5.0
Parameter for steepness of "step".
double TanPhi =1.0
Parameter for angle Phi of "step" (45 degrees)
double Beta =1.0
Interaction parameter.
Detailed Description
Namespace for exact solution for MultiPoisson equation with "sharp step".
Function Documentation
get_exact_u()
void TanhSolnForMultiPoisson::get_exact_u (const Vector< double > & x, Vector< double > & u)
Exact solution as a Vector.
  {
   double u_scalar=scalar_soln(x);
   for (unsigned i=0;i<N_FIELD;i++)
    {
     u[i]=double(i+1)*u_scalar;
    }
  }
References i, N_FIELD, scalar_soln(), and plotDoE::x.
Referenced by MultiPoissonProblem< ELEMENT >::actions_before_newton_solve(), and MultiPoissonProblem< ELEMENT >::doc_solution().
scalar_soln()
double TanhSolnForMultiPoisson::scalar_soln (const Vector< double > & x)
Scalar solution.
  {
   return tanh(1.0-Alpha*(TanPhi*x[0]-x[1]));
  }
References Alpha, Eigen::bfloat16_impl::tanh(), TanPhi, and plotDoE::x.
Referenced by get_exact_u(), and source_function().
scalar_source()
double TanhSolnForMultiPoisson::scalar_source (const Vector< double > & x)
Scalar source.
  {
   return 2.0*tanh(-1.0+Alpha*(TanPhi*x[0]-x[1]))*
    (1.0-pow(tanh(-1.0+Alpha*(TanPhi*x[0]-x[1])),2.0))*
    Alpha*Alpha*TanPhi*TanPhi+2.0*tanh(-1.0+Alpha*(TanPhi*x[0]-x[1]))*
    (1.0-pow(tanh(-1.0+Alpha*(TanPhi*x[0]-x[1])),2.0))*Alpha*Alpha;
  }
References Alpha, Eigen::bfloat16_impl::pow(), Eigen::bfloat16_impl::tanh(), TanPhi, and plotDoE::x.
Referenced by source_function().
source_function()
void TanhSolnForMultiPoisson::source_function (const Vector< double > & x, Vector< double > & source)
Source function required to make the solution above an exact solution.
  {
   double scalar_f=scalar_source(x);
   double scalar_u=scalar_soln(x);
   for (unsigned i=0;i<N_FIELD;i++)
    {
     source[i] = double(i+1)*scalar_f;
     for (unsigned k=0;k<N_FIELD;k++)
      {
       source[i]+=Beta*double(k+1)*scalar_u;
      }
     source[i]*=double(i+1);
    }
  }
References Beta, i, k, N_FIELD, scalar_soln(), scalar_source(), TestProblem::source(), and plotDoE::x.
Referenced by MultiPoissonProblem< ELEMENT >::MultiPoissonProblem().
Variable Documentation
Alpha
double TanhSolnForMultiPoisson::Alpha =5.0
Parameter for steepness of "step".
Referenced by main(), scalar_soln(), and scalar_source().
Beta
double TanhSolnForMultiPoisson::Beta =1.0
Interaction parameter.
Referenced by MultiPoissonProblem< ELEMENT >::MultiPoissonProblem(), and source_function().
TanPhi
double TanhSolnForMultiPoisson::TanPhi =1.0
Parameter for angle Phi of "step" (45 degrees)
Referenced by scalar_soln(), and scalar_source().