MercuryDPM: oomph::Circle Class Reference
oomph::Circle Class Reference
#include <geom_objects.h>
Public Member Functions
Circle (const double &x_c, const double &y_c, const double &r)
Constructor: Pass x and y-coords of centre and radius (all pinned)
Circle (const double &x_c, const double &y_c, const double &r, TimeStepper *time_stepper_pt)
Circle (const Vector< Data * > &geom_data_pt)
Circle (const Circle &dummy)=delete
Broken copy constructor.
void operator= (const Circle &)=delete
Broken assignment operator.
virtual ~Circle ()
Destructor: Clean up if necessary.
void position (const Vector< double > &zeta, Vector< double > &r) const
Position Vector at Lagrangian coordinate zeta.
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
double & x_c ()
Access function to x-coordinate of centre of circle.
double & y_c ()
Access function to y-coordinate of centre of circle.
double & R ()
Access function to radius of circle.
unsigned ngeom_data () const
How many items of Data does the shape of the object depend on?
Data * geom_data_pt (const unsigned &j)
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition_dt (const Vector< double > &zeta, const unsigned &j, Vector< double > &drdt)
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
virtual void locate_zeta (const Vector< double > &zeta, GeomObject *&sub_geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
Protected Attributes
Vector< Data * > Geom_data_pt
Vector of pointers to Data items that affects the object's shape.
bool Must_clean_up
Do I need to clean up?
bool Is_time_dependent
Genuine time-dependence?
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Detailed Description
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// Circle in 2D space.
\[ x = X_c + R \cos(\zeta) \]
\[ y = Y_c + R \sin(\zeta) \]
Constructor & Destructor Documentation
Circle() [1/4]
oomph::Circle::Circle (const double & x_c, const double & y_c, const double & r) inline
Constructor: Pass x and y-coords of centre and radius (all pinned)
       : GeomObject(1, 2)
     {
       // Create Data:
       Geom_data_pt.resize(1);
       Geom_data_pt[0] = new Data(3);
       // No time-dependence
       Is_time_dependent = false;
       // Assign data: X_c; no timedependence, free by default
       // Pin the data
       Geom_data_pt[0]->pin(0);
       // Give it a value:
       Geom_data_pt[0]->set_value(0, x_c);
       // Assign data: Y_c; no timedependence, free by default
       // Pin the data
       Geom_data_pt[0]->pin(1);
       // Give it a value:
       Geom_data_pt[0]->set_value(1, y_c);
       // Assign data: R; no timedependence, free by default
       // Pin the data
       Geom_data_pt[0]->pin(2);
       // Give it a value:
       Geom_data_pt[0]->set_value(2, r);
       // I've created the data, I need to clean up
       Must_clean_up = true;
     }
References Geom_data_pt, Is_time_dependent, Must_clean_up, UniformPSDSelfTest::r, x_c(), and y_c().
Circle() [2/4]
oomph::Circle::Circle (const double & x_c, const double & y_c, const double & r, TimeStepper * time_stepper_pt) inline
Constructor: Pass x and y-coords of centre and radius (all pinned) Circle is static but can be used in time-dependent runs with specified timestepper.
       : GeomObject(1, 2, time_stepper_pt)
     {
       // Create Data:
       Geom_data_pt.resize(1);
       Geom_data_pt[0] = new Data(time_stepper_pt, 3);
       // We have time-dependence
       Is_time_dependent = true;
       // Assign data: X_c; no timedependence, free by default
       // Pin the data
       Geom_data_pt[0]->pin(0);
       // Give it a value:
       Geom_data_pt[0]->set_value(0, x_c);
       // Assign data: Y_c; no timedependence, free by default
       // Pin the data
       Geom_data_pt[0]->pin(1);
       // Give it a value:
       Geom_data_pt[0]->set_value(1, y_c);
       // Assign data: R; no timedependence, free by default
       // Pin the data
       Geom_data_pt[0]->pin(2);
       // Give it a value:
       Geom_data_pt[0]->set_value(2, r);
       // "Impulsive" start because there isn't any time-dependence
       time_stepper_pt->assign_initial_values_impulsive(Geom_data_pt[0]);
       // I've created the data, I need to clean up
       Must_clean_up = true;
     }
References oomph::TimeStepper::assign_initial_values_impulsive(), Geom_data_pt, Is_time_dependent, Must_clean_up, UniformPSDSelfTest::r, oomph::GeomObject::time_stepper_pt(), x_c(), and y_c().
Circle() [3/4]
oomph::Circle::Circle (const Vector< Data * > & geom_data_pt) inline
Constructor: Pass x and y-coords of centre and radius (all as Data)
Geom_data_pt[0]->value(0) = X_c;
Geom_data_pt[0]->value(1) = Y_c;
Geom_data_pt[0]->value(2) = R;
                                               : GeomObject(1, 2)
     {
 #ifdef PARANOID
       if (geom_data_pt.size() != 1)
       {
         std::ostringstream error_message;
         error_message << "geom_data_pt should have size 1, not "
                       << geom_data_pt.size() << std::endl;
         if (geom_data_pt[0]->nvalue() != 3)
         {
           error_message << "geom_data_pt[0] should have 3 values, not "
                         << geom_data_pt[0]->nvalue() << std::endl;
         }
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // We have time-dependence
       if (geom_data_pt[0]->time_stepper_pt()->nprev_values() > 0)
       {
         Is_time_dependent = true;
       }
       else
       {
         Is_time_dependent = false;
       }
       Geom_data_pt.resize(1);
       Geom_data_pt[0] = geom_data_pt[0];
       // Data has been created externally: Must not clean up
       Must_clean_up = false;
     }
References geom_data_pt(), Geom_data_pt, Is_time_dependent, Must_clean_up, oomph::Data::nvalue(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::GeomObject::time_stepper_pt().
Circle() [4/4]
oomph::Circle::Circle (const Circle & dummy) delete
Broken copy constructor.
~Circle()
virtual oomph::Circle::~Circle () inline virtual
Destructor: Clean up if necessary.
     {
       // Do I need to clean up?
       if (Must_clean_up)
       {
         unsigned ngeom_data = Geom_data_pt.size();
         for (unsigned i = 0; i < ngeom_data; i++)
         {
           delete Geom_data_pt[i];
           Geom_data_pt[i] = 0;
         }
       }
     }
References Geom_data_pt, i, Must_clean_up, and ngeom_data().
Member Function Documentation
geom_data_pt()
Data* oomph::Circle::geom_data_pt (const unsigned & j) inline virtual
Return pointer to the j-th Data item that the object's shape depends on
Reimplemented from oomph::GeomObject.
     {
       return Geom_data_pt[j];
     }
References Geom_data_pt, and j.
Referenced by Circle().
ngeom_data()
unsigned oomph::Circle::ngeom_data () const inline virtual
How many items of Data does the shape of the object depend on?
Reimplemented from oomph::GeomObject.
     {
       return Geom_data_pt.size();
     }
References Geom_data_pt.
Referenced by ~Circle().
operator=()
void oomph::Circle::operator= (const Circle &) delete
Broken assignment operator.
position() [1/2]
void oomph::Circle::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const inline virtual
Parametrised position on object: r(zeta). Evaluated at previous timestep. t=0: current time; t>0: previous timestep.
Reimplemented from oomph::GeomObject.
     {
       // Genuine time-dependence?
       if (!Is_time_dependent)
       {
         position(zeta, r);
       }
       else
       {
 #ifdef PARANOID
         if (t > Geom_data_pt[0]->time_stepper_pt()->nprev_values())
         {
           std::ostringstream error_message;
           error_message << "t > nprev_values() " << t << " "
                         << Geom_data_pt[0]->time_stepper_pt()->nprev_values()
                         << std::endl;
           throw OomphLibError(error_message.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
 #endif
         // Extract data
         double X_c = Geom_data_pt[0]->value(t, 0);
         double Y_c = Geom_data_pt[0]->value(t, 1);
         double R = Geom_data_pt[0]->value(t, 2);
         // Position Vector
         r[0] = X_c + R * cos(zeta[0]);
         r[1] = Y_c + R * sin(zeta[0]);
       }
     }
References cos(), Geom_data_pt, Is_time_dependent, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, position(), UniformPSDSelfTest::r, R(), sin(), plotPSD::t, oomph::GeomObject::time_stepper_pt(), ProblemParameters::Y_c, and Eigen::zeta().
position() [2/2]
void oomph::Circle::position (const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position Vector at Lagrangian coordinate zeta.
Implements oomph::GeomObject.
     {
       // Extract data
       double X_c = Geom_data_pt[0]->value(0);
       double Y_c = Geom_data_pt[0]->value(1);
       double R = Geom_data_pt[0]->value(2);
       // Position Vector
       r[0] = X_c + R * cos(zeta[0]);
       r[1] = Y_c + R * sin(zeta[0]);
     }
References cos(), Geom_data_pt, UniformPSDSelfTest::r, R(), sin(), ProblemParameters::Y_c, and Eigen::zeta().
Referenced by oomph::CylinderWithFlagDomain::macro_element_boundary(), and position().
R()
double& oomph::Circle::R () inline
Access function to radius of circle.
     {
       return *Geom_data_pt[0]->value_pt(2);
     }
References Geom_data_pt.
Referenced by position().
x_c()
double& oomph::Circle::x_c () inline
Access function to x-coordinate of centre of circle.
     {
       return *Geom_data_pt[0]->value_pt(0);
     }
References Geom_data_pt.
Referenced by Circle().
y_c()
double& oomph::Circle::y_c () inline
Access function to y-coordinate of centre of circle.
     {
       return *Geom_data_pt[0]->value_pt(1);
     }
References Geom_data_pt.
Referenced by Circle().
Member Data Documentation
Geom_data_pt
Vector<Data*> oomph::Circle::Geom_data_pt protected
Vector of pointers to Data items that affects the object's shape.
Referenced by Circle(), geom_data_pt(), ngeom_data(), position(), R(), x_c(), y_c(), and ~Circle().
Is_time_dependent
bool oomph::Circle::Is_time_dependent protected
Genuine time-dependence?
Referenced by Circle(), and position().
Must_clean_up
bool oomph::Circle::Must_clean_up protected
Do I need to clean up?
Referenced by Circle(), and ~Circle().
The documentation for this class was generated from the following file:
geom_objects.h