MercuryDPM: MeshDeformation Namespace Reference
MeshDeformation Namespace Reference
Namespace for the functions associated with the mesh deformation.
Functions
void deform_mesh (Mesh *const &mesh_pt)
Deform the cubic mesh so that its six sides are all parabolic.
void exact_normal (const unsigned &face, const Vector< double > &x, Vector< double > &n)
The exact normal vector for each face at global coordinate x.
Detailed Description
Namespace for the functions associated with the mesh deformation.
Namespace for function that represents the exact (quadratically-varying) outer unit normal. and the function the deforms the mesh
Namespace for functions that deform the cubic mesh into a shape with parabolic sides.
Function Documentation
deform_mesh()
void MeshDeformation::deform_mesh (Mesh *const & mesh_pt)
Deform the cubic mesh so that its six sides are all parabolic.
  {
   unsigned n_node = mesh_pt->nnode();
   for(unsigned n=0;n<n_node;n++)
    {
     Node* nod_pt = mesh_pt->node_pt(n);
     double x = nod_pt->x(0) - 4;
     double y = nod_pt->x(1) - 4;
     double X_new = 5 - y*y/16;
     double Y_new = 3 + x*x/16;
     nod_pt->x(0) = X_new*x/4.0 + 4;
     nod_pt->x(1) = Y_new*y/4.0 + 4;
    }
  }
References n, oomph::Mesh::nnode(), oomph::Mesh::node_pt(), plotDoE::x, oomph::Node::x(), and y.
Referenced by QFaceTestProblem< ELEMENT >::QFaceTestProblem(), TFaceTestProblem< ELEMENT >::TFaceTestProblem(), and TriangleFaceTestProblem< ELEMENT >::TriangleFaceTestProblem().
exact_normal()
void MeshDeformation::exact_normal (const unsigned & face, const Vector< double > & x, Vector< double > & n)
The exact normal vector for each face at global coordinate x.
The outer unit normal of the mesh boundaries that have been deformed into parabolas. The normal is different for each boundary, so the input arguments are the boundary and the global Cartesian coordinate on that boundary, x. The outer unit normal is returned in the vector n.
Return the exact normal on the given face of the cubic mesh N.B. This is slightly different than the case in q_faces_3d.cc because the faces are labelled differently (DOH).
  {
   double N[2] = {0.0,0.0};
   switch(face)
    {
    case 0:
     N[0] = -(x[0]-4.0)/8.0;
     N[1] = -1.0;
     break;
    case 1:
     N[0] = 1.0;
     N[1] = (x[1]-4)/8.0;
     break;
    case 2:
     N[0] = -(x[0]-4)/8.0;
     N[1] = 1.0;
     break;
    case 3:
     N[0] = -1.0;
     N[1] = (x[1]-4)/8.0;
     break;
    }
   double length = sqrt(N[0]*N[0] + N[1]*N[1]);
   n[0] = N[0]/length;
   n[1] = N[1]/length;
  }
References n, N, sqrt(), and plotDoE::x.
Referenced by QFaceTestProblem< ELEMENT >::QFaceTestProblem(), TFaceTestProblem< ELEMENT >::TFaceTestProblem(), and TriangleFaceTestProblem< ELEMENT >::TriangleFaceTestProblem().