MercuryDPM: MercuryCGSelfTest.cpp File Reference
MercuryCGSelfTest.cpp File Reference
#include "Mercury3D.h"
#include "StatisticsVector.h"
#include "Walls/InfiniteWall.h"
#include <cmath>
#include <iostream>
#include <iomanip>
#include <Species/LinearViscoelasticSpecies.h>
#include <CG/Functions/Heaviside.h>
#include <Species/LinearViscoelasticReversibleAdhesiveSpecies.h>
#include <CG/TimeAveragedCG.h>
#include "MercuryTime.h"
#include "CG/CG.h"
Classes
struct MercuryCGSelfTest
In this file a cubic packing of 5^3 particles in a tri-axial box is created and allowed to settle under small gravity. After that Z statistics are calculated.
Functions
int main (int argc UNUSED, char *argv[] UNUSED)
Function Documentation
main()
int main (int argc UNUSED, char *argv[] UNUSED)
 {
     unsigned n = 2;
     MercuryCGSelfTest problem(n);
     problem.solve();
     Mercury3D cg;
     auto c0 = cg.cgHandler.copyAndAddObject(TimeAveragedCG<CGCoordinates::XYZ,CGFunctions::Heaviside>());
     //c0->setX(-0.5,n+0.5);
     c0->setNX(250);
     c0->setNY(1);
     c0->setNZ(1);
     c0->setWidth(0.3);
     //c0->selectSpecies(0);
     //cg.cgHandler.copyAndAddObject(CG<CGCoordinates::O>());
     cg.cgHandler.restartAndEvaluateDataFiles("MercuryCGSelfTest");
     helpers::more(cg.cgHandler.getLastObject()->statFile.getName(),3);
     logger(INFO,"Run 'sp 'MercuryCGSelfTest.0.stat' u ($4==0.5?$2:NaN):3:16' in gnuplot to view the output");
     helpers::writeToFile("MercuryCGSelfTest.gnu","set multiplot layout 1,2\n"
      "set xlabel 'x'\n"
      //"set ylabel 'y'\n"
      "set ylabel rotate\n"
      "unset key\n"
      "set ylabel 'Density at z=0.5'\n"
      //"sp 'MercuryCGSelfTest.0.stat' u ($4==0.5?$2:NaN):3:6\n"
      "p 'MercuryCGSelfTest.0.stat' u ($4==0.5&&$3==0.5?$2:NaN):6 w lp\n"
      "unset key\n"
      "set ylabel 'Normal Contact Stress in x at z=0.5'\n"
      //"sp 'MercuryCGSelfTest.0.stat' u ($4==0.5?$2:NaN):3:16\n"
      "p 'MercuryCGSelfTest.0.stat' u ($4==0.5&&$3==0.5?$2:NaN):16 w lp\n"
      "unset multiplot\n");
 }
References DPMBase::cgHandler, BaseHandler< T >::copyAndAddObject(), BaseHandler< T >::getLastObject(), File::getName(), INFO, logger, helpers::more(), n, problem, CGHandler::restartAndEvaluateDataFiles(), BaseCG::statFile, and helpers::writeToFile().