MercuryDPM: ref_7.cpp File Reference
ref_7.cpp File Reference
#include "../Eigen/Core"
Functions
void call_ref (Ref< const Matrix3f, 0, OuterStride< 2 >>)
int main ()
Function Documentation
call_ref()
void call_ref (Ref< const Matrix3f, 0, OuterStride< 2 >>)
 {}
Referenced by main().
main()
int main ()
            {
   MatrixXf a(6, 2);
   Map<const Matrix3f, 0, OuterStride<Dynamic>> md(a.data(), OuterStride<Dynamic>(2));
   Map<const Matrix3f, 0, OuterStride<2>> m2(a.data());
 #ifdef EIGEN_SHOULD_FAIL_TO_BUILD
   call_ref(md);
 #else
   call_ref(m2);
 #endif
 }
References a, call_ref(), m2(), and md.