var AdvancedTutorials =
[
    [ "Overview", "d7/db9/AdvancedTutorials.html#AdvancedOverview", null ],
    [ "Particles driven by a rotating coil", "d0/d46/CoilSelfTest.html", null ],
    [ "Flow through a 2D hourglass/silo", "da/d72/HourGlass2DDemo.html", null ],
    [ "Flow through a 3D hourglass/silo", "da/d7e/HourGlass3DDemo.html", null ],
    [ "Free cooling granular system (2D)", "d1/d52/FreeCoolingDemo.html", null ],
    [ "Free cooling granular system (2D) in walls", "da/dd0/FreeCooling2DinWallsDemo.html", null ],
    [ "Free cooling granular system (3D)", "d2/dfa/FreeCooling3DDemo.html", null ],
    [ "Free cooling granular system (3D) in walls", "dc/ddf/FreeCooling3DinWallsDemo.html", null ],
    [ "Marble Run (with seesaw)", "db/de6/MarbleRunWithSeesaw.html", null ],
    [ "Particles on an inclined chute", "d1/db0/ChuteDemo.html", null ],
    [ "Chute with hopper", "d4/deb/ChuteWithHopper.html", null ],
    [ "Five Particles", "da/d0e/FiveParticles.html", null ],
    [ "Lees Edward", "de/d3e/LeesEdwards.html", null ],
    [ "Simple sintering process", "d0/d67/SinteringDemos.html", null ],
    [ "Isotropic compression of a cuboidal REV", "de/d51/IsoCompression.html", null ],
    [ "Pure shear (constant volume) of a cuboidal REV", "d6/d80/PureShear.html", null ],
    [ "Simple shear (constant stress) of a cuboidal REV", "d4/da6/SimpleShear.html", null ],
    [ "Parameter study in 1D parameter space", "d9/d2b/ParameterStudy1D.html", null ],
    [ "Parameter study in 2D parameter space", "d6/daa/ParameterStudy2D.html", null ],
    [ "Parameter study in 3D parameter space", "d9/db2/ParameterStudy3D.html", null ],
    [ "Parameter study using a protective wall", "dd/d7d/ProtectiveWall.html", null ],
    [ "Parallel processing using OpenMP", "de/d40/openmpDemo.html", null ],
    [ "Parallel processing using MPI", "d0/db4/mpiDemo.html", null ],
    [ "Parallel processing for Input-Output, I/O files", "db/d3c/parallelInputOutputDemo.html", null ],
    [ "Gomboc (Rigid_clumps)", "df/d20/Gomboc.html", null ],
    [ "Domino effect", "d3/dc6/DominoParticle.html", null ],
    [ "Tennisracket or Dzhanibekov theorem", "d5/d5d/TBar.html", null ]
];