MercuryDPM: mesh_from_tetgen_navier_stokes.cc File Reference
mesh_from_tetgen_navier_stokes.cc File Reference
#include "generic.h"
#include "navier_stokes.h"
#include "meshes/tetgen_mesh.h"
Classes
class NavierStokesProblem< ELEMENT >
Entry flow problem in quarter tube domain.
Namespaces
Global_Physical_Variables
Global variables.
Functions
int main (int argc, char *argv[])
3D Navier Stokes on an unstructured mesh
Function Documentation
main()
int main (int argc , char * argv[])
3D Navier Stokes on an unstructured mesh
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Check number of command line arguments: Need exactly three.
  if (argc!=4)
   {
    std::string error_message =
     "Wrong number of command line arguments.\n";
    error_message +=
     "Must specify the following file names  \n";
    error_message +=
     "filename.node then filename.ele then filename.face\n";
    throw OomphLibError(error_message,
                        OOMPH_CURRENT_FUNCTION,
                        OOMPH_EXCEPTION_LOCATION);
   }
  // Convert arguments to strings that specify the input file names
  string node_file_name(argv[1]);
  string element_file_name(argv[2]);
  string face_file_name(argv[3]);
  // Set up doc info
  DocInfo doc_info;
  // Set output directory
  doc_info.set_directory("RESLT");
  // Build problem
  NavierStokesProblem<TTaylorHoodElement<3> >
   problem(doc_info,node_file_name,element_file_name,face_file_name);
  // Solve the problem
  problem.newton_solve();
 } // end_of_main
References OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, problem, oomph::DocInfo::set_directory(), Flag_definition::setup(), and oomph::Global_string_for_annotation::string().