MercuryDPM: MatrixBase_all.cpp File Reference
MatrixBase_all.cpp File Reference
Functions
Vector3f boxMin (Vector3f::Zero())
Vector3f boxMax (Vector3f::Ones())
Variables
Vector3f p0 = Vector3f::Random()
Vector3f p1 = Vector3f::Random().cwiseAbs()
Function Documentation
boxMax()
Vector3f boxMax (Vector3f::Ones())
boxMin()
Vector3f boxMin (Vector3f::Zero())
Variable Documentation
p0
Vector3f p0 = Vector3f::Random()
Referenced by ClumpParticle::actionsAfterAddObject(), SmoothChute::actionsBeforeTimeStep(), Chute::addFlowParticlesCompactly(), NautaMixer::addParticles(), NautaMixer::addParticlesAtWall(), alignedbox(), alignedboxCastTests(), CRBond_Bessel::bessjy01a(), CRBond_Bessel::bessjy01b(), CRBond_Bessel::bessjynb(), Membrane::buildMesh(), ParticleHandler::clear(), Eigen::EigenSolver< MatrixType_ >::compute(), BaseCluster::computeInternalStructure(), MercuryLogo::constructTextAsParticles(), Slide::create_rough_wall(), Chute::createFlowParticle(), ChuteWithWedge::createFlowParticle(), Membrane::createVertexParticles(), ABCElement::fill_in_generic_residual_contribution(), MembraneDemo::fixMembraneEdges(), MembraneSelfTest::fixMembraneEdges(), Eigen::internal::generic_ndtri_gt_exp_neg_two(), Quaternion::getDistance(), BaseWall::getLinePlaneIntersect(), Eigen::internal::gmres(), hyperplane(), PSDContinuous::interpolateCSD(), HorizontalMixer::introduceParticlesAtWall(), HorizontalMixer::introduceParticlesInDomain(), HorizontalMixer::introduceSingleParticle(), Membrane::loadFromSTL(), main(), Eigen::internal::pacos_float(), parametrizedline(), BaseCluster::particleInsertionSuccessful(), planes(), OneParticleHeatingSelfTest::printTime(), OneParticleCoolingSelfTest::printTime(), EvaporationAndHeatTest::printTime(), Domain::processReceivedBoundaryParticleData(), Eigen::internal::ptranspose(), InteractionHandler::readAndAddObject(), Membrane::saveVertexPositions(), MercuryLogo::setupInitialConditions(), SmoothChute::setupInitialConditions(), ChangingTOIParticle::setupInitialConditions(), MembraneDemo::setupInitialConditions(), Binary::setupInitialConditions(), my_problem::setupInitialConditions(), MaserRepeatedOutInMPI2Test::setupInitialConditions(), PeriodicBounaryEnteringMPIDomainTest::setupInitialConditions(), SubcriticalMaserBoundaryTESTMPI2Test::setupInitialConditions(), FreeCooling2DinWallsDemo::setupInitialConditions(), FreeCooling3DDemoProblem::setupInitialConditions(), FreeCooling3DinWallsDemo::setupInitialConditions(), FreeCoolingDemoProblem::setupInitialConditions(), HeaterBoundaryTest::setupInitialConditions(), HourGlass2D::setupInitialConditions(), HourGlass::setupInitialConditions(), MinimalExampleDrum::setupInitialConditions(), ShiftingConstantMassFlowMaserBoundarySelfTest::setupInitialConditions(), ShiftingMaserBoundarySelfTest::setupInitialConditions(), FiveParticles::setupInitialConditions(), Cstatic2d::setupInitialConditions(), Cstatic3D::setupInitialConditions(), MeltableForceLaw2SelfTest::setupInitialConditions(), MeltableForceLawSelfTest::setupInitialConditions(), ThermalConductionSelfTest::setupInitialConditions(), Chutebelt::setupInitialConditions(), DistributionPhiNormalSelfTest::setupInitialConditions(), clumpTest::setupInitialConditions(), SubcriticalMaserBoundarySelfTest::setupInitialConditions(), my_problem_HGRID::setupInitialConditions(), FreeFallInteractionSelfTest::setupInitialConditions(), FreeFallSelfTest::setupInitialConditions(), HertzianBSHPInteractionTwoParticleElasticCollision::setupInitialConditions(), ObliqueImpactSelfTest::setupInitialConditions(), TwoParticleBagheriCollision::setupInitialConditions(), TwoParticleClassicalWilletCollision::setupInitialConditions(), TwoParticleCollisionInteraction::setupInitialConditions(), TwoParticleElasticCollision::setupInitialConditions(), CoilSelfTest::setupInitialConditions(), MembraneSelfTest::setupInitialConditions(), DrumRot::setupInitialConditions(), ScalingTestInitialConditionsRelax::setupInitialConditions(), Contact::setupInitialConditions(), BouncingSuperQuadric::setupInitialConditions(), EllipsoidsBouncingOnWallDemo::setupInitialConditions(), EllipticalSuperQuadricCollision::setupInitialConditions(), SlidingSpheresUnitTest::setupInitialConditions(), SphericalSuperQuadricCollision::setupInitialConditions(), ContactDetectionNormalSpheresTest::setupInitialConditions(), ContactDetectionRotatedSpheresTest::setupInitialConditions(), VisualisationTest::setupInitialConditions(), MercuryProblem::setupInitialConditions(), Tutorial11::setupInitialConditions(), Tutorial12::setupInitialConditions(), Tutorial1::setupInitialConditions(), Tutorial2::setupInitialConditions(), Tutorial3::setupInitialConditions(), Tutorial4::setupInitialConditions(), Tutorial5::setupInitialConditions(), Tutorial6::setupInitialConditions(), Tutorial7::setupInitialConditions(), Tutorial8::setupInitialConditions(), Tutorial9::setupInitialConditions(), CGDisplacementFieldUnitTest::setupInitialConditions(), CGExactOverlapUnitTest::setupInitialConditions(), CGForceDensityUnitTest::setupInitialConditions(), ConsistencyInitialParticleWallOverlapUnitTest::setupInitialConditions(), DrivenParticleClass::setupInitialConditions(), ExtremeOverlapWithWallsUnitTest::setupInitialConditions(), FluxBoundaryPrescribedDistanceUnitTest::setupInitialConditions(), FluxBoundaryUnitTest::setupInitialConditions(), FreeFallHertzMindlinUnitTest::setupInitialConditions(), FreeFall::setupInitialConditions(), HertzContactRestitutionUnitTest::setupInitialConditions(), MD_demo::setupInitialConditions(), InclinedPlane::setupInitialConditions(), MpiMaserChuteTest::setupInitialConditions(), MultiParticlesInsertion::setupInitialConditions(), MpiPeriodicBoundaryUnitTest::setupInitialConditions(), SetDistributionPhiNormalSelfTest::setupInitialConditions(), MembraneDemo::setUpMembrane(), MembraneSelfTest::setUpMembrane(), Siegen::Siegen(), Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::Through(), and Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::Through().
p1
Vector3f p1 = Vector3f::Random().cwiseAbs()
Referenced by MeltableForceLaw2SelfTest::actionsBeforeTimeStep(), MeltableForceLawSelfTest::actionsBeforeTimeStep(), ThermalConductionSelfTest::actionsBeforeTimeStep(), NautaMixer::addParticlesAtWall(), alignedbox(), alignedboxCastTests(), CRBond_Bessel::bessjy01a(), CRBond_Bessel::bessjy01b(), CRBond_Bessel::bessjynb(), SuperQuadricParticle::computeContactPoint(), SuperQuadricParticle::computeResidualContactDetection(), tetgenmesh::distance(), ABCElement::fill_in_generic_residual_contribution(), oomph::Multi_domain_functions::first_closer_than_second(), Eigen::internal::generic_ndtri_lt_exp_neg_two(), SuperQuadricParticle::getContactPointPlanB(), SuperQuadricParticle::getJacobianOfContactDetectionObjective(), BaseWall::getLinePlaneIntersect(), WearableNurbsWall::getVolumeUnderSurface(), WearableNurbsWall::getVolumeUnderSurfaceX(), Mercury3D::hGridFindContactsWithinTargetCell(), Mercury2D::hGridFindContactsWithinTargetCell(), hyperplane(), hyperplane_alignment(), HorizontalMixer::introduceParticlesAtWall(), oomph::UnstructuredTwoDMeshGeometryBase::is_point_inside_polygon_helper(), main(), Eigen::JacobiRotation< Scalar >::makeGivens(), Eigen::internal::minimum_degree_ordering(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::node_update_IV(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::node_update_V(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::node_update_VI(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::node_update_VII(), Eigen::internal::pacos_float(), parametrizedline(), parametrizedline_alignment(), oomph::PolygonHelper::point_is_in_polygon(), EvaporationAndHeatTest::printTime(), Eigen::internal::ptranspose(), FileReader::read(), InteractionHandler::readAndAddObject(), MercuryLogo::setupInitialConditions(), Cstatic2d::setupInitialConditions(), MeltableForceLaw2SelfTest::setupInitialConditions(), MeltableForceLawSelfTest::setupInitialConditions(), ThermalConductionSelfTest::setupInitialConditions(), HertzianBSHPInteractionTwoParticleElasticCollision::setupInitialConditions(), TwoParticleBagheriCollision::setupInitialConditions(), TwoParticleClassicalWilletCollision::setupInitialConditions(), TwoParticleElasticCollision::setupInitialConditions(), EllipsoidsBouncingOnWallDemo::setupInitialConditions(), EllipticalSuperQuadricCollision::setupInitialConditions(), SlidingSpheresUnitTest::setupInitialConditions(), SphericalSuperQuadricCollision::setupInitialConditions(), ContactDetectionNormalSpheresTest::setupInitialConditions(), ContactDetectionRotatedSpheresTest::setupInitialConditions(), CGDisplacementFieldUnitTest::setupInitialConditions(), CGExactOverlapUnitTest::setupInitialConditions(), HertzContactRestitutionUnitTest::setupInitialConditions(), MultiParticlesInsertion::setupInitialConditions(), ChuteWithHopper::setupInitialConditions(), Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::Through(), Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >::Through(), transform_alignment(), oomph::TriangleMeshPolygon::TriangleMeshPolygon(), SuperQuadricParticle::writeDebugMessageMiddleOfLoop(), WallVTKWriter::writeVTKSurfaceArea(), Eigen::internal::detail::zip_in_place< Packet16c >(), Eigen::internal::detail::zip_in_place< Packet16uc >(), Eigen::internal::detail::zip_in_place< Packet2f >(), Eigen::internal::detail::zip_in_place< Packet2i >(), Eigen::internal::detail::zip_in_place< Packet2ui >(), Eigen::internal::detail::zip_in_place< Packet4bf >(), Eigen::internal::detail::zip_in_place< Packet4f >(), Eigen::internal::detail::zip_in_place< Packet4i >(), Eigen::internal::detail::zip_in_place< Packet4s >(), Eigen::internal::detail::zip_in_place< Packet4ui >(), Eigen::internal::detail::zip_in_place< Packet4us >(), Eigen::internal::detail::zip_in_place< Packet8c >(), Eigen::internal::detail::zip_in_place< Packet8s >(), Eigen::internal::detail::zip_in_place< Packet8uc >(), and Eigen::internal::detail::zip_in_place< Packet8us >().