MercuryDPM: Eigen::internal::qr_preconditioner_impl< MatrixType, Options, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true > Class Template Reference
Eigen::internal::qr_preconditioner_impl< MatrixType, Options, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true > Class Template Reference
#include <JacobiSVD.h>
Public Types
enum {
RowsAtCompileTime = MatrixType::RowsAtCompileTime , ColsAtCompileTime = MatrixType::ColsAtCompileTime , MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime , MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime ,
MatrixOptions = internal::traits<MatrixType>::Options , WorkspaceSize = internal::traits<SVDType>::MatrixVColsAtCompileTime , MaxWorkspaceSize = internal::traits<SVDType>::MatrixVMaxColsAtCompileTime
}
typedef MatrixType::Scalar Scalar
typedef JacobiSVD< MatrixType, Options > SVDType
typedef Matrix< Scalar, WorkspaceSize, 1, ColMajor, MaxWorkspaceSize, 1 > WorkspaceType
typedef internal::make_proper_matrix_type< Scalar, ColsAtCompileTime, RowsAtCompileTime, MatrixOptions, MaxColsAtCompileTime, MaxRowsAtCompileTime >::type TransposeTypeWithSameStorageOrder
Public Member Functions
void allocate (const SVDType &svd)
template<typename Xpr >
bool run (SVDType &svd, const Xpr &matrix)
Private Types
typedef ColPivHouseholderQR< TransposeTypeWithSameStorageOrder > QRType
Private Attributes
QRType m_qr
WorkspaceType m_workspace
Member Typedef Documentation
QRType
template<typename MatrixType , int Options> typedef ColPivHouseholderQR<TransposeTypeWithSameStorageOrder> Eigen::internal::qr_preconditioner_impl< MatrixType, Options, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::QRType private
Scalar
template<typename MatrixType , int Options> typedef MatrixType::Scalar Eigen::internal::qr_preconditioner_impl< MatrixType, Options, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::Scalar
SVDType
template<typename MatrixType , int Options> typedef JacobiSVD<MatrixType, Options> Eigen::internal::qr_preconditioner_impl< MatrixType, Options, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::SVDType
TransposeTypeWithSameStorageOrder
template<typename MatrixType , int Options> typedef internal::make_proper_matrix_type<Scalar, ColsAtCompileTime, RowsAtCompileTime, MatrixOptions, MaxColsAtCompileTime, MaxRowsAtCompileTime>::type Eigen::internal::qr_preconditioner_impl< MatrixType, Options, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::TransposeTypeWithSameStorageOrder
WorkspaceType
template<typename MatrixType , int Options> typedef Matrix<Scalar, WorkspaceSize, 1, ColMajor, MaxWorkspaceSize, 1> Eigen::internal::qr_preconditioner_impl< MatrixType, Options, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::WorkspaceType
Member Enumeration Documentation
anonymous enum
template<typename MatrixType , int Options> anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
MatrixOptions
WorkspaceSize
MaxWorkspaceSize
        {
     RowsAtCompileTime = MatrixType::RowsAtCompileTime,
     ColsAtCompileTime = MatrixType::ColsAtCompileTime,
     MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime,
     MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime,
     MatrixOptions = internal::traits<MatrixType>::Options,
     WorkspaceSize = internal::traits<SVDType>::MatrixVColsAtCompileTime,
     MaxWorkspaceSize = internal::traits<SVDType>::MatrixVMaxColsAtCompileTime
   };
Member Function Documentation
allocate()
template<typename MatrixType , int Options> void Eigen::internal::qr_preconditioner_impl< MatrixType, Options, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::allocate (const SVDType & svd) inline
{
     if (svd.cols() != m_qr.rows() || svd.rows() != m_qr.cols()) {
       internal::destroy_at(&m_qr);
       internal::construct_at(&m_qr, svd.cols(), svd.rows());
     }
     if (svd.m_computeFullV)
       m_workspace.resize(svd.cols());
     else if (svd.m_computeThinV)
       m_workspace.resize(svd.rows());
   }
References Eigen::internal::construct_at(), Eigen::internal::destroy_at(), and svd().
run()
template<typename MatrixType , int Options> template<typename Xpr > bool Eigen::internal::qr_preconditioner_impl< MatrixType, Options, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run (SVDType & svd, const Xpr & matrix) inline
{
     if (matrix.cols() > matrix.rows()) {
       m_qr.compute(matrix.adjoint());
       svd.m_workMatrix =
           m_qr.matrixQR().block(0, 0, matrix.rows(), matrix.rows()).template triangularView<Upper>().adjoint();
       if (svd.m_computeFullV)
         m_qr.householderQ().evalTo(svd.m_matrixV, m_workspace);
       else if (svd.m_computeThinV) {
         svd.m_matrixV.setIdentity(matrix.cols(), matrix.rows());
         m_qr.householderQ().applyThisOnTheLeft(svd.m_matrixV, m_workspace);
       }
       if (svd.computeU()) svd.m_matrixU = m_qr.colsPermutation();
       return true;
     } else
       return false;
   }
References matrix(), and svd().
Member Data Documentation
m_qr
template<typename MatrixType , int Options> QRType Eigen::internal::qr_preconditioner_impl< MatrixType, Options, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::m_qr private
m_workspace
template<typename MatrixType , int Options> WorkspaceType Eigen::internal::qr_preconditioner_impl< MatrixType, Options, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::m_workspace private
The documentation for this class was generated from the following file:
JacobiSVD.h