MercuryDPM: three_d_prescribed_displ_lagr_mult.cc File Reference
mpi/distribution/three_d_prescribed_displ_lagr_mult/three_d_prescribed_displ_lagr_mult.cc File Reference
#include "generic.h"
#include "solid.h"
#include "constitutive.h"
#include "meshes/simple_cubic_mesh.h"
Classes
class FiniteElementComp
class WarpedPlane
Warped plane in 3D space.
class RefineableElasticCubicMesh< ELEMENT >
Simple cubic mesh upgraded to become a solid mesh.
class PrescribedBoundaryDisplacementProblem< ELEMENT >
Namespaces
Global_Physical_Variables
Global variables.
Functions
int main (int argc, char **argv)
Driver code.
Variables
WarpedLine Global_Physical_Variables::Boundary_geom_object (0.0)
GeomObject specifying the shape of the boundary: Initially it's flat.
Function Documentation
main()
int main (int argc , char ** argv)
Driver code.
 {
 #ifdef OOMPH_HAS_MPI
    MPI_Helpers::init(argc,argv);
 #endif
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  //Set up the problem
  PrescribedBoundaryDisplacementProblem<RefineableQPVDElement<3,3> > problem;
  // Distribute problem
  // Manufacture distribution so that domain is split in two
  if (problem.communicator_pt()->nproc()==2)
   {
    unsigned nel=problem.mesh_pt()->nelement();
    Vector<unsigned> element_partition(nel);
    for (unsigned e=0;e<nel;e++)
     {
      if (problem.mesh_pt()->finite_element_pt(e)->node_pt(0)->x(1)<0.49)
       {
        element_partition[e]=0;
       }
      else
       {
        element_partition[e]=1;
       }
     }
    bool report_stats=true;
    problem.distribute(element_partition,report_stats);
   }
  else
   {
    // Distribute the problem with METIS
    bool report_stats=true;
    problem.distribute(report_stats);
   }
  // Adapt twice to produce doubly hanging nodes
  problem.adapt();
  problem.adapt();
  // Doc initial domain shape
  problem.doc_solution();
  //Parameter incrementation
  unsigned nstep=10;
  if (CommandLineArgs::Argc!=1)
   {
    std::cout << "Validation -- only doing one step" << std::endl;
    nstep=1;
   }
  for(unsigned i=0;i<nstep;i++)
   {
    // Increment imposed boundary displacement
    Global_Physical_Variables::Boundary_geom_object.ampl()+=0.02;
    // Solve the problem with Newton's method
    problem.newton_solve();
    // Doc solution
    problem.doc_solution();
    // For maximum stability: Reset the current nodal positions to be
    // the "stress-free" ones -- this assignment means that the
    // parameter study no longer corresponds to a physical experiment
    // but is what we'd do if we wanted to use the solid solve
    // to update a fluid mesh in an FSI problem, say.
    problem.solid_mesh_pt()->set_lagrangian_nodal_coordinates();
   }
 #ifdef OOMPH_HAS_MPI
  MPI_Helpers::finalize();
 #endif
 } //end of main
References WarpedLine::ampl(), oomph::CommandLineArgs::Argc, Global_Physical_Variables::Boundary_geom_object, e(), i, problem, and Flag_definition::setup().