MercuryDPM: Eigen::KLU< MatrixType_ > Class Template Reference
Eigen::KLU< MatrixType_ > Class Template Reference
#include <KLUSupport.h>
Public Types
enum { ColsAtCompileTime = MatrixType::ColsAtCompileTime , MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime }
typedef MatrixType_ MatrixType
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
typedef MatrixType::StorageIndex StorageIndex
typedef Matrix< Scalar, Dynamic, 1 > Vector
typedef Matrix< int, 1, MatrixType::ColsAtCompileTime > IntRowVectorType
typedef Matrix< int, MatrixType::RowsAtCompileTime, 1 > IntColVectorType
typedef SparseMatrix< Scalar > LUMatrixType
typedef SparseMatrix< Scalar, ColMajor, int > KLUMatrixType
typedef Ref< const KLUMatrixType, StandardCompressedFormat > KLUMatrixRef
Public Member Functions
KLU ()
template<typename InputMatrixType >
KLU (const InputMatrixType &matrix)
~KLU ()
EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
ComputationInfo info () const
Reports whether previous computation was successful.
template<typename InputMatrixType >
void compute (const InputMatrixType &matrix)
template<typename InputMatrixType >
void analyzePattern (const InputMatrixType &matrix)
const klu_common & kluCommon () const
klu_common & kluCommon ()
template<typename InputMatrixType >
void factorize (const InputMatrixType &matrix)
template<typename BDerived , typename XDerived >
bool _solve_impl (const MatrixBase< BDerived > &b, MatrixBase< XDerived > &x) const
Public Member Functions inherited from Eigen::SparseSolverBase< KLU< MatrixType_ > >
SparseSolverBase ()
SparseSolverBase (SparseSolverBase &&other)
~SparseSolverBase ()
KLU< MatrixType_ > & derived ()
const KLU< MatrixType_ > & derived () const
const Solve< KLU< MatrixType_ >, Rhs > solve (const MatrixBase< Rhs > &b) const
const Solve< KLU< MatrixType_ >, Rhs > solve (const SparseMatrixBase< Rhs > &b) const
void _solve_impl (const SparseMatrixBase< Rhs > &b, SparseMatrixBase< Dest > &dest) const
Protected Types
typedef SparseSolverBase< KLU< MatrixType_ > > Base
Protected Member Functions
void init ()
void analyzePattern_impl ()
void factorize_impl ()
template<typename MatrixDerived >
void grab (const EigenBase< MatrixDerived > &A)
void grab (const KLUMatrixRef &A)
Protected Attributes
KLUMatrixType m_dummy
KLUMatrixRef mp_matrix
klu_numeric * m_numeric
klu_symbolic * m_symbolic
klu_common m_common
ComputationInfo m_info
int m_factorizationIsOk
int m_analysisIsOk
bool m_extractedDataAreDirty
Protected Attributes inherited from Eigen::SparseSolverBase< KLU< MatrixType_ > >
bool m_isInitialized
Private Member Functions
KLU (const KLU &)
Member Typedef Documentation
Base
template<typename MatrixType_ > typedef SparseSolverBase<KLU<MatrixType_> > Eigen::KLU< MatrixType_ >::Base protected
IntColVectorType
template<typename MatrixType_ > typedef Matrix<int, MatrixType::RowsAtCompileTime, 1> Eigen::KLU< MatrixType_ >::IntColVectorType
IntRowVectorType
template<typename MatrixType_ > typedef Matrix<int, 1, MatrixType::ColsAtCompileTime> Eigen::KLU< MatrixType_ >::IntRowVectorType
KLUMatrixRef
template<typename MatrixType_ > typedef Ref<const KLUMatrixType, StandardCompressedFormat> Eigen::KLU< MatrixType_ >::KLUMatrixRef
KLUMatrixType
template<typename MatrixType_ > typedef SparseMatrix<Scalar, ColMajor, int> Eigen::KLU< MatrixType_ >::KLUMatrixType
LUMatrixType
template<typename MatrixType_ > typedef SparseMatrix<Scalar> Eigen::KLU< MatrixType_ >::LUMatrixType
MatrixType
template<typename MatrixType_ > typedef MatrixType_ Eigen::KLU< MatrixType_ >::MatrixType
RealScalar
template<typename MatrixType_ > typedef MatrixType::RealScalar Eigen::KLU< MatrixType_ >::RealScalar
Scalar
template<typename MatrixType_ > typedef MatrixType::Scalar Eigen::KLU< MatrixType_ >::Scalar
StorageIndex
template<typename MatrixType_ > typedef MatrixType::StorageIndex Eigen::KLU< MatrixType_ >::StorageIndex
Vector
template<typename MatrixType_ > typedef Matrix<Scalar, Dynamic, 1> Eigen::KLU< MatrixType_ >::Vector
Member Enumeration Documentation
anonymous enum
template<typename MatrixType_ > anonymous enum
Enumerator
ColsAtCompileTime
MaxColsAtCompileTime
 { ColsAtCompileTime = MatrixType::ColsAtCompileTime, MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime };
Constructor & Destructor Documentation
KLU() [1/3]
template<typename MatrixType_ > Eigen::KLU< MatrixType_ >::KLU () inline
 : m_dummy(0, 0), mp_matrix(m_dummy) { init(); }
References Eigen::KLU< MatrixType_ >::init().
KLU() [2/3]
template<typename MatrixType_ > template<typename InputMatrixType > Eigen::KLU< MatrixType_ >::KLU (const InputMatrixType & matrix) inline explicit
                                               : mp_matrix(matrix) {
     init();
     compute(matrix);
   }
References Eigen::KLU< MatrixType_ >::compute(), Eigen::KLU< MatrixType_ >::init(), and matrix().
~KLU()
template<typename MatrixType_ > Eigen::KLU< MatrixType_ >::~KLU () inline
          {
     if (m_symbolic) klu_free_symbolic(&m_symbolic, &m_common);
     if (m_numeric) klu_free_numeric(&m_numeric, &m_common);
   }
References Eigen::KLU< MatrixType_ >::m_common, Eigen::KLU< MatrixType_ >::m_numeric, and Eigen::KLU< MatrixType_ >::m_symbolic.
KLU() [3/3]
template<typename MatrixType_ > Eigen::KLU< MatrixType_ >::KLU (const KLU< MatrixType_ > &) inline private
 {}
Member Function Documentation
_solve_impl()
template<typename MatrixType > template<typename BDerived , typename XDerived > bool Eigen::KLU< MatrixType >::_solve_impl (const MatrixBase< BDerived > & b, MatrixBase< XDerived > & x) const
{
   Index rhsCols = b.cols();
   EIGEN_STATIC_ASSERT((XDerived::Flags & RowMajorBit) == 0, THIS_METHOD_IS_ONLY_FOR_COLUMN_MAJOR_MATRICES);
   eigen_assert(m_factorizationIsOk &&
                "The decomposition is not in a valid state for solving, you must first call either compute() or "
                "analyzePattern()/factorize()");
   x = b;
   int info = klu_solve(m_symbolic, m_numeric, b.rows(), rhsCols, x.const_cast_derived().data(),
                        const_cast<klu_common *>(&m_common), Scalar());
   m_info = info != 0 ? Success : NumericalIssue;
   return true;
 }
References b, eigen_assert, EIGEN_STATIC_ASSERT, info, Eigen::klu_solve(), Eigen::NumericalIssue, Eigen::RowMajorBit, Eigen::Success, and plotDoE::x.
analyzePattern()
template<typename MatrixType_ > template<typename InputMatrixType > void Eigen::KLU< MatrixType_ >::analyzePattern (const InputMatrixType & matrix) inline
Performs a symbolic decomposition on the sparcity of matrix.
This function is particularly useful when solving for several problems having the same structure.
See also
factorize(), compute()
{
     if (m_symbolic) klu_free_symbolic(&m_symbolic, &m_common);
     if (m_numeric) klu_free_numeric(&m_numeric, &m_common);
     grab(matrix.derived());
     analyzePattern_impl();
   }
References Eigen::KLU< MatrixType_ >::analyzePattern_impl(), Eigen::KLU< MatrixType_ >::grab(), Eigen::KLU< MatrixType_ >::m_common, Eigen::KLU< MatrixType_ >::m_numeric, Eigen::KLU< MatrixType_ >::m_symbolic, and matrix().
analyzePattern_impl()
template<typename MatrixType_ > void Eigen::KLU< MatrixType_ >::analyzePattern_impl () inline protected
{
     m_info = InvalidInput;
     m_analysisIsOk = false;
     m_factorizationIsOk = false;
     m_symbolic = klu_analyze(internal::convert_index<int>(mp_matrix.rows()),
                              const_cast<StorageIndex *>(mp_matrix.outerIndexPtr()),
                              const_cast<StorageIndex *>(mp_matrix.innerIndexPtr()), &m_common);
     if (m_symbolic) {
       m_isInitialized = true;
       m_info = Success;
       m_analysisIsOk = true;
       m_extractedDataAreDirty = true;
     }
   }
References Eigen::InvalidInput, Eigen::KLU< MatrixType_ >::m_analysisIsOk, Eigen::KLU< MatrixType_ >::m_common, Eigen::KLU< MatrixType_ >::m_extractedDataAreDirty, Eigen::KLU< MatrixType_ >::m_factorizationIsOk, Eigen::KLU< MatrixType_ >::m_info, Eigen::SparseSolverBase< KLU< MatrixType_ > >::m_isInitialized, Eigen::KLU< MatrixType_ >::m_symbolic, Eigen::KLU< MatrixType_ >::mp_matrix, and Eigen::Success.
Referenced by Eigen::KLU< MatrixType_ >::analyzePattern(), and Eigen::KLU< MatrixType_ >::compute().
cols()
template<typename MatrixType_ > EIGEN_CONSTEXPR Index Eigen::KLU< MatrixType_ >::cols () const inline
 { return mp_matrix.cols(); }
References Eigen::KLU< MatrixType_ >::mp_matrix.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
compute()
template<typename MatrixType_ > template<typename InputMatrixType > void Eigen::KLU< MatrixType_ >::compute (const InputMatrixType & matrix) inline
Computes the sparse Cholesky decomposition of matrix Note that the matrix should be column-major, and in compressed format for best performance.
See also
SparseMatrix::makeCompressed().
{
     if (m_symbolic) klu_free_symbolic(&m_symbolic, &m_common);
     if (m_numeric) klu_free_numeric(&m_numeric, &m_common);
     grab(matrix.derived());
     analyzePattern_impl();
     factorize_impl();
   }
References Eigen::KLU< MatrixType_ >::analyzePattern_impl(), Eigen::KLU< MatrixType_ >::factorize_impl(), Eigen::KLU< MatrixType_ >::grab(), Eigen::KLU< MatrixType_ >::m_common, Eigen::KLU< MatrixType_ >::m_numeric, Eigen::KLU< MatrixType_ >::m_symbolic, and matrix().
Referenced by Eigen::KLU< MatrixType_ >::KLU().
factorize()
template<typename MatrixType_ > template<typename InputMatrixType > void Eigen::KLU< MatrixType_ >::factorize (const InputMatrixType & matrix) inline
Performs a numeric decomposition of matrix
The given matrix must has the same sparcity than the matrix on which the pattern anylysis has been performed.
See also
analyzePattern(), compute()
{
     eigen_assert(m_analysisIsOk && "KLU: you must first call analyzePattern()");
     if (m_numeric) klu_free_numeric(&m_numeric, &m_common);
     grab(matrix.derived());
     factorize_impl();
   }
References eigen_assert, Eigen::KLU< MatrixType_ >::factorize_impl(), Eigen::KLU< MatrixType_ >::grab(), Eigen::KLU< MatrixType_ >::m_analysisIsOk, Eigen::KLU< MatrixType_ >::m_common, Eigen::KLU< MatrixType_ >::m_numeric, and matrix().
factorize_impl()
template<typename MatrixType_ > void Eigen::KLU< MatrixType_ >::factorize_impl () inline protected
{
     m_numeric = klu_factor(const_cast<StorageIndex *>(mp_matrix.outerIndexPtr()),
                            const_cast<StorageIndex *>(mp_matrix.innerIndexPtr()),
                            const_cast<Scalar *>(mp_matrix.valuePtr()), m_symbolic, &m_common, Scalar());
     m_info = m_numeric ? Success : NumericalIssue;
     m_factorizationIsOk = m_numeric ? 1 : 0;
     m_extractedDataAreDirty = true;
   }
References Eigen::klu_factor(), Eigen::KLU< MatrixType_ >::m_common, Eigen::KLU< MatrixType_ >::m_extractedDataAreDirty, Eigen::KLU< MatrixType_ >::m_factorizationIsOk, Eigen::KLU< MatrixType_ >::m_info, Eigen::KLU< MatrixType_ >::m_numeric, Eigen::KLU< MatrixType_ >::m_symbolic, Eigen::KLU< MatrixType_ >::mp_matrix, Eigen::NumericalIssue, and Eigen::Success.
Referenced by Eigen::KLU< MatrixType_ >::compute(), and Eigen::KLU< MatrixType_ >::factorize().
grab() [1/2]
template<typename MatrixType_ > template<typename MatrixDerived > void Eigen::KLU< MatrixType_ >::grab (const EigenBase< MatrixDerived > & A) inline protected
{
     internal::destroy_at(&mp_matrix);
     internal::construct_at(&mp_matrix, A.derived());
   }
References Eigen::internal::construct_at(), Eigen::internal::destroy_at(), and Eigen::KLU< MatrixType_ >::mp_matrix.
Referenced by Eigen::KLU< MatrixType_ >::analyzePattern(), Eigen::KLU< MatrixType_ >::compute(), and Eigen::KLU< MatrixType_ >::factorize().
grab() [2/2]
template<typename MatrixType_ > void Eigen::KLU< MatrixType_ >::grab (const KLUMatrixRef & A) inline protected
{
     if (&(A.derived()) != &mp_matrix) {
       internal::destroy_at(&mp_matrix);
       internal::construct_at(&mp_matrix, A);
     }
   }
References Eigen::internal::construct_at(), Eigen::internal::destroy_at(), and Eigen::KLU< MatrixType_ >::mp_matrix.
info()
template<typename MatrixType_ > ComputationInfo Eigen::KLU< MatrixType_ >::info () const inline
Reports whether previous computation was successful.
Returns
Success if computation was successful, NumericalIssue if the matrix.appears to be negative.
{
     eigen_assert(m_isInitialized && "Decomposition is not initialized.");
     return m_info;
   }
References eigen_assert, Eigen::KLU< MatrixType_ >::m_info, and Eigen::SparseSolverBase< KLU< MatrixType_ > >::m_isInitialized.
init()
template<typename MatrixType_ > void Eigen::KLU< MatrixType_ >::init () inline protected
               {
     m_info = InvalidInput;
     m_isInitialized = false;
     m_numeric = 0;
     m_symbolic = 0;
     m_extractedDataAreDirty = true;
     klu_defaults(&m_common);
   }
References Eigen::InvalidInput, Eigen::KLU< MatrixType_ >::m_common, Eigen::KLU< MatrixType_ >::m_extractedDataAreDirty, Eigen::KLU< MatrixType_ >::m_info, Eigen::SparseSolverBase< KLU< MatrixType_ > >::m_isInitialized, Eigen::KLU< MatrixType_ >::m_numeric, and Eigen::KLU< MatrixType_ >::m_symbolic.
Referenced by Eigen::KLU< MatrixType_ >::KLU().
kluCommon() [1/2]
template<typename MatrixType_ > klu_common& Eigen::KLU< MatrixType_ >::kluCommon () inline
Provides access to the control settings array used by UmfPack.
If this array contains NaN's, the default values are used.
See KLU documentation for details.
 { return m_common; }
References Eigen::KLU< MatrixType_ >::m_common.
kluCommon() [2/2]
template<typename MatrixType_ > const klu_common& Eigen::KLU< MatrixType_ >::kluCommon () const inline
Provides access to the control settings array used by KLU.
See KLU documentation for details.
 { return m_common; }
References Eigen::KLU< MatrixType_ >::m_common.
rows()
template<typename MatrixType_ > EIGEN_CONSTEXPR Index Eigen::KLU< MatrixType_ >::rows () const inline
 { return mp_matrix.rows(); }
References Eigen::KLU< MatrixType_ >::mp_matrix.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
Member Data Documentation
m_analysisIsOk
template<typename MatrixType_ > int Eigen::KLU< MatrixType_ >::m_analysisIsOk protected
Referenced by Eigen::KLU< MatrixType_ >::analyzePattern_impl(), and Eigen::KLU< MatrixType_ >::factorize().
m_common
template<typename MatrixType_ > klu_common Eigen::KLU< MatrixType_ >::m_common protected
Referenced by Eigen::KLU< MatrixType_ >::analyzePattern(), Eigen::KLU< MatrixType_ >::analyzePattern_impl(), Eigen::KLU< MatrixType_ >::compute(), Eigen::KLU< MatrixType_ >::factorize(), Eigen::KLU< MatrixType_ >::factorize_impl(), Eigen::KLU< MatrixType_ >::init(), Eigen::KLU< MatrixType_ >::kluCommon(), and Eigen::KLU< MatrixType_ >::~KLU().
m_dummy
template<typename MatrixType_ > KLUMatrixType Eigen::KLU< MatrixType_ >::m_dummy protected
m_extractedDataAreDirty
template<typename MatrixType_ > bool Eigen::KLU< MatrixType_ >::m_extractedDataAreDirty mutable protected
Referenced by Eigen::KLU< MatrixType_ >::analyzePattern_impl(), Eigen::KLU< MatrixType_ >::factorize_impl(), and Eigen::KLU< MatrixType_ >::init().
m_factorizationIsOk
template<typename MatrixType_ > int Eigen::KLU< MatrixType_ >::m_factorizationIsOk protected
Referenced by Eigen::KLU< MatrixType_ >::analyzePattern_impl(), and Eigen::KLU< MatrixType_ >::factorize_impl().
m_info
template<typename MatrixType_ > ComputationInfo Eigen::KLU< MatrixType_ >::m_info mutable protected
Referenced by Eigen::KLU< MatrixType_ >::analyzePattern_impl(), Eigen::KLU< MatrixType_ >::factorize_impl(), Eigen::KLU< MatrixType_ >::info(), and Eigen::KLU< MatrixType_ >::init().
m_numeric
template<typename MatrixType_ > klu_numeric* Eigen::KLU< MatrixType_ >::m_numeric protected
Referenced by Eigen::KLU< MatrixType_ >::analyzePattern(), Eigen::KLU< MatrixType_ >::compute(), Eigen::KLU< MatrixType_ >::factorize(), Eigen::KLU< MatrixType_ >::factorize_impl(), Eigen::KLU< MatrixType_ >::init(), and Eigen::KLU< MatrixType_ >::~KLU().
m_symbolic
template<typename MatrixType_ > klu_symbolic* Eigen::KLU< MatrixType_ >::m_symbolic protected
Referenced by Eigen::KLU< MatrixType_ >::analyzePattern(), Eigen::KLU< MatrixType_ >::analyzePattern_impl(), Eigen::KLU< MatrixType_ >::compute(), Eigen::KLU< MatrixType_ >::factorize_impl(), Eigen::KLU< MatrixType_ >::init(), and Eigen::KLU< MatrixType_ >::~KLU().
mp_matrix
template<typename MatrixType_ > KLUMatrixRef Eigen::KLU< MatrixType_ >::mp_matrix protected
Referenced by Eigen::KLU< MatrixType_ >::analyzePattern_impl(), Eigen::KLU< MatrixType_ >::cols(), Eigen::KLU< MatrixType_ >::factorize_impl(), Eigen::KLU< MatrixType_ >::grab(), and Eigen::KLU< MatrixType_ >::rows().
The documentation for this class was generated from the following file:
KLUSupport.h