MercuryDPM: Eigen::internal::trmv_selector< Mode, ColMajor > Struct Template Reference
Eigen::internal::trmv_selector< Mode, ColMajor > Struct Template Reference
#include <TriangularMatrixVector.h>
Static Public Member Functions
template<typename Lhs , typename Rhs , typename Dest >
static void run (const Lhs &lhs, const Rhs &rhs, Dest &dest, const typename Dest::Scalar &alpha)
Member Function Documentation
run()
template<int Mode> template<typename Lhs , typename Rhs , typename Dest > static void Eigen::internal::trmv_selector< Mode, ColMajor >::run (const Lhs & lhs, const Rhs & rhs, Dest & dest, const typename Dest::Scalar & alpha) inline static
{
     typedef typename Lhs::Scalar LhsScalar;
     typedef typename Rhs::Scalar RhsScalar;
     typedef typename Dest::Scalar ResScalar;
     typedef internal::blas_traits<Lhs> LhsBlasTraits;
     typedef typename LhsBlasTraits::DirectLinearAccessType ActualLhsType;
     typedef internal::blas_traits<Rhs> RhsBlasTraits;
     typedef typename RhsBlasTraits::DirectLinearAccessType ActualRhsType;
     constexpr int Alignment = (std::min)(int(AlignedMax), int(internal::packet_traits<ResScalar>::size));
     typedef Map<Matrix<ResScalar, Dynamic, 1>, Alignment> MappedDest;
     add_const_on_value_type_t<ActualLhsType> actualLhs = LhsBlasTraits::extract(lhs);
     add_const_on_value_type_t<ActualRhsType> actualRhs = RhsBlasTraits::extract(rhs);
     LhsScalar lhs_alpha = LhsBlasTraits::extractScalarFactor(lhs);
     RhsScalar rhs_alpha = RhsBlasTraits::extractScalarFactor(rhs);
     ResScalar actualAlpha = alpha * lhs_alpha * rhs_alpha;
     // FIXME find a way to allow an inner stride on the result if packet_traits<Scalar>::size==1
     // on, the other hand it is good for the cache to pack the vector anyways...
     constexpr bool EvalToDestAtCompileTime = Dest::InnerStrideAtCompileTime == 1;
     constexpr bool ComplexByReal = (NumTraits<LhsScalar>::IsComplex) && (!NumTraits<RhsScalar>::IsComplex);
     constexpr bool MightCannotUseDest = (Dest::InnerStrideAtCompileTime != 1) || ComplexByReal;
     gemv_static_vector_if<ResScalar, Dest::SizeAtCompileTime, Dest::MaxSizeAtCompileTime, MightCannotUseDest>
         static_dest;
     bool alphaIsCompatible = (!ComplexByReal) || numext::is_exactly_zero(numext::imag(actualAlpha));
     bool evalToDest = EvalToDestAtCompileTime && alphaIsCompatible;
     RhsScalar compatibleAlpha = get_factor<ResScalar, RhsScalar>::run(actualAlpha);
     ei_declare_aligned_stack_constructed_variable(ResScalar, actualDestPtr, dest.size(),
                                                   evalToDest ? dest.data() : static_dest.data());
     if (!evalToDest) {
 #ifdef EIGEN_DENSE_STORAGE_CTOR_PLUGIN
       constexpr int Size = Dest::SizeAtCompileTime;
       Index size = dest.size();
       EIGEN_DENSE_STORAGE_CTOR_PLUGIN
 #endif
       if (!alphaIsCompatible) {
         MappedDest(actualDestPtr, dest.size()).setZero();
         compatibleAlpha = RhsScalar(1);
       } else
         MappedDest(actualDestPtr, dest.size()) = dest;
     }
     internal::triangular_matrix_vector_product<Index, Mode, LhsScalar, LhsBlasTraits::NeedToConjugate, RhsScalar,
                                                RhsBlasTraits::NeedToConjugate, ColMajor>::run(actualLhs.rows(),
                                                                                               actualLhs.cols(),
                                                                                               actualLhs.data(),
                                                                                               actualLhs.outerStride(),
                                                                                               actualRhs.data(),
                                                                                               actualRhs.innerStride(),
                                                                                               actualDestPtr, 1,
                                                                                               compatibleAlpha);
     if (!evalToDest) {
       if (!alphaIsCompatible)
         dest += actualAlpha * MappedDest(actualDestPtr, dest.size());
       else
         dest = MappedDest(actualDestPtr, dest.size());
     }
     if (((Mode & UnitDiag) == UnitDiag) && !numext::is_exactly_one(lhs_alpha)) {
       Index diagSize = (std::min)(lhs.rows(), lhs.cols());
       dest.head(diagSize) -= (lhs_alpha - LhsScalar(1)) * rhs.head(diagSize);
     }
   }
References Eigen::AlignedMax, alpha, Eigen::ColMajor, ei_declare_aligned_stack_constructed_variable, imag(), int(), Eigen::numext::is_exactly_one(), Eigen::numext::is_exactly_zero(), min, Eigen::internal::get_factor< From, To >::run(), Eigen::run(), size, and Eigen::UnitDiag.
The documentation for this struct was generated from the following file:
TriangularMatrixVector.h