MercuryDPM: AutoSingle.cpp File Reference
AutoSingle.cpp File Reference
#include <cstdio>
#include <iostream>
#include <memory>
#include <stdexcept>
#include <string>
#include <array>
#include <CMakeDefinitions.h>
Functions
std::string ExecCommand (const char *cmd)
int main (int argc, char *argv[])
Function Documentation
ExecCommand()
std::string ExecCommand (const char * cmd)
{
     std::array<char, 256> buffer;
     std::string result;
     // Prepare a pipe to write a to execute a systm command and read the result
     std::unique_ptr<FILE, int(*)(FILE*)> pipe(popen(cmd, "r"), pclose);
     if (!pipe) {
         throw std::runtime_error("popen() failed!");
     }
     while (fgets(buffer.data(), buffer.size(), pipe.get()) != nullptr) {
         result += buffer.data();
     }
     return result;
 }
References int(), and oomph::Global_string_for_annotation::string().
Referenced by main().
main()
int main (int argc , char * argv[])
 {
     // Automatic script to clean working directories, recompile the code and post-process the output for Paraview
     std::string command;
     std::string name = "Single";
     // Remove data for stl sequence (Blender) visualizations
     //command = "rm ClumpSeq.txt";
     //ExecCommand(command.c_str());
     // Make
     command = "make " + name;
     ExecCommand(command.c_str());
     // Run
     command = "./" + name;
     ExecCommand(command.c_str());
     // Clean the old paraview output directory
     command = "rm -rf paraview_" + name;
     ExecCommand(command.c_str());
     // Create new paraview output directory
     command = "mkdir paraview_" + name;
     ExecCommand(command.c_str());
     // Data2pvd tool run
     command = "../../../Tools/data2pvd " + name + ".data paraview_" + name + "/" + name;
     ExecCommand(command.c_str());
     // Paraview energy data postprocessing tool
     command = "python " + getMercuryDPMSourceDir() + "/Tools/MClump/PlotEnergies.py " +
             getMercuryDPMBuildDir() + "/Drivers/Clump/" + name + "/ " + name;
     ExecCommand(command.c_str());
     return 0;
 }
References ExecCommand(), getMercuryDPMBuildDir(), getMercuryDPMSourceDir(), plotDoE::name, and oomph::Global_string_for_annotation::string().