MercuryDPM: barrel.cc File Reference
barrel.cc File Reference
#include "generic.h"
#include "young_laplace.h"
#include "meshes/simple_rectangular_quadmesh.h"
Classes
class YoungLaplaceProblem< ELEMENT >
Namespaces
GlobalParameters
Global parameters.
Functions
double GlobalParameters::get_exact_kappa ()
Exact kappa.
void GlobalParameters::spine_base_function (const Vector< double > &x, Vector< double > &spine_B, Vector< Vector< double > > &dspine_B)
void GlobalParameters::spine_function (const Vector< double > &x, Vector< double > &spine, Vector< Vector< double > > &dspine)
int main ()
Driver code.
Variables
double GlobalParameters::Controlled_height = 0.0
Height control value.
double GlobalParameters::Alpha_min = MathematicalConstants::Pi/2.0*1.5
Min. spine angle against horizontal plane.
double GlobalParameters::Alpha_max = MathematicalConstants::Pi/2.0*0.5
Max. spine angle against horizontal plane.
Function Documentation
main()
int main ()
Driver code.
 {
  // Create label for output
  DocInfo doc_info;
  // Set output directory
  doc_info.set_directory("RESLT");
  //Open a trace file
  ofstream trace_file;
  char filename[100];
  sprintf(filename,"%s/trace.dat",doc_info.directory().c_str());
  trace_file.open(filename);
  // Write kappa, exact kappa and height values
  trace_file
   << "VARIABLES=\"<GREEK>k</GREEK>\",\"<GREEK>k</GREEK>_{ex}\",\"h\""
   << std::endl;
  trace_file << "ZONE" << std::endl;
  // Create the problem
  //-------------------
  // Create the problem with 2D nine-node elements from the
  // QYoungLaplaceElement family.
  YoungLaplaceProblem<QYoungLaplaceElement<3> > problem;
  //Output the solution
  problem.doc_solution(doc_info,trace_file);
  //Increment counter for solutions
  doc_info.number()++;
  // Parameter incrementation
  //-------------------------
  double increment=0.1;
  // Loop over steps
  unsigned nstep=2; // 10;
  for (unsigned istep=0;istep<nstep;istep++)
   {
    // Increment prescribed height value
    GlobalParameters::Controlled_height+=increment;
    // Solve the problem
    problem.newton_solve();
    //Output the solution
    problem.doc_solution(doc_info,trace_file);
    //Increment counter for solutions
    doc_info.number()++;
   }
  // Close output file
  trace_file.close();
 } // end of main
References GlobalParameters::Controlled_height, oomph::DocInfo::directory(), MergeRestartFiles::filename, oomph::DocInfo::number(), problem, and oomph::DocInfo::set_directory().