MercuryDPM: Eigen::internal::TensorContractionKernel< ResScalar, LhsScalar, RhsScalar, StorageIndex, OutputMapper, LhsMapper, RhsMapper > Struct Template Reference
Eigen::internal::TensorContractionKernel< ResScalar, LhsScalar, RhsScalar, StorageIndex, OutputMapper, LhsMapper, RhsMapper > Struct Template Reference
#include <TensorContraction.h>
Public Types
enum { HasBeta = false }
typedef LhsScalar * LhsBlock
typedef RhsScalar * RhsBlock
typedef TensorContractionBlockMemAllocator< LhsScalar, RhsScalar > BlockMemAllocator
typedef BlockMemAllocator::BlockMemHandle BlockMemHandle
typedef internal::gebp_traits< LhsScalar, RhsScalar > Traits
typedef internal::gemm_pack_lhs< LhsScalar, StorageIndex, typename LhsMapper::SubMapper, Traits::mr, Traits::LhsProgress, typename Traits::LhsPacket4Packing, ColMajor > LhsPacker
typedef internal::gemm_pack_rhs< RhsScalar, StorageIndex, typename RhsMapper::SubMapper, Traits::nr, ColMajor > RhsPacker
typedef internal::gebp_kernel< LhsScalar, RhsScalar, StorageIndex, OutputMapper, Traits::mr, Traits::nr, false, false > GebpKernel
Public Member Functions
EIGEN_DEVICE_FUNC TensorContractionKernel (StorageIndex m_, StorageIndex k_, StorageIndex n_, StorageIndex bm_, StorageIndex bk_, StorageIndex bn_)
template<typename Device >
EIGEN_DEVICE_FUNC BlockMemHandle allocate (Device &d, LhsBlock *lhs_block, RhsBlock *rhs_block)
template<typename Device >
EIGEN_DEVICE_FUNC BlockMemHandle allocateSlices (Device &d, const StorageIndex num_lhs, const StorageIndex num_rhs, const StorageIndex num_slices, std::vector< LhsBlock > *lhs_blocks, std::vector< RhsBlock > *rhs_blocks)
EIGEN_DEVICE_FUNC EIGEN_DONT_INLINE void packLhs (LhsBlock *lhsBlock, const typename LhsMapper::SubMapper &data_mapper, const StorageIndex depth, const StorageIndex rows)
EIGEN_DEVICE_FUNC EIGEN_DONT_INLINE void packRhs (RhsBlock *rhsBlock, const typename RhsMapper::SubMapper &data_mapper, const StorageIndex depth, const StorageIndex cols)
EIGEN_DEVICE_FUNC EIGEN_DONT_INLINE void invoke (const OutputMapper &output_mapper, const LhsBlock &lhsBlock, const RhsBlock &rhsBlock, const StorageIndex rows, const StorageIndex depth, const StorageIndex cols, const ResScalar alpha, const ResScalar beta)
Static Public Member Functions
template<typename Device >
static EIGEN_DEVICE_FUNC void deallocate (Device &d, BlockMemHandle handle)
Private Attributes
const StorageIndex m
const StorageIndex k
const StorageIndex n
const StorageIndex bm
const StorageIndex bk
const StorageIndex bn
Member Typedef Documentation
BlockMemAllocator
template<typename ResScalar , typename LhsScalar , typename RhsScalar , typename StorageIndex , typename OutputMapper , typename LhsMapper , typename RhsMapper > typedef TensorContractionBlockMemAllocator<LhsScalar, RhsScalar> Eigen::internal::TensorContractionKernel< ResScalar, LhsScalar, RhsScalar, StorageIndex, OutputMapper, LhsMapper, RhsMapper >::BlockMemAllocator
BlockMemHandle
template<typename ResScalar , typename LhsScalar , typename RhsScalar , typename StorageIndex , typename OutputMapper , typename LhsMapper , typename RhsMapper > typedef BlockMemAllocator::BlockMemHandle Eigen::internal::TensorContractionKernel< ResScalar, LhsScalar, RhsScalar, StorageIndex, OutputMapper, LhsMapper, RhsMapper >::BlockMemHandle
GebpKernel
template<typename ResScalar , typename LhsScalar , typename RhsScalar , typename StorageIndex , typename OutputMapper , typename LhsMapper , typename RhsMapper > typedef internal::gebp_kernel<LhsScalar, RhsScalar, StorageIndex, OutputMapper, Traits::mr, Traits::nr, false, false> Eigen::internal::TensorContractionKernel< ResScalar, LhsScalar, RhsScalar, StorageIndex, OutputMapper, LhsMapper, RhsMapper >::GebpKernel
LhsBlock
template<typename ResScalar , typename LhsScalar , typename RhsScalar , typename StorageIndex , typename OutputMapper , typename LhsMapper , typename RhsMapper > typedef LhsScalar* Eigen::internal::TensorContractionKernel< ResScalar, LhsScalar, RhsScalar, StorageIndex, OutputMapper, LhsMapper, RhsMapper >::LhsBlock
LhsPacker
template<typename ResScalar , typename LhsScalar , typename RhsScalar , typename StorageIndex , typename OutputMapper , typename LhsMapper , typename RhsMapper > typedef internal::gemm_pack_lhs<LhsScalar, StorageIndex, typename LhsMapper::SubMapper, Traits::mr, Traits::LhsProgress, typename Traits::LhsPacket4Packing, ColMajor> Eigen::internal::TensorContractionKernel< ResScalar, LhsScalar, RhsScalar, StorageIndex, OutputMapper, LhsMapper, RhsMapper >::LhsPacker
RhsBlock
template<typename ResScalar , typename LhsScalar , typename RhsScalar , typename StorageIndex , typename OutputMapper , typename LhsMapper , typename RhsMapper > typedef RhsScalar* Eigen::internal::TensorContractionKernel< ResScalar, LhsScalar, RhsScalar, StorageIndex, OutputMapper, LhsMapper, RhsMapper >::RhsBlock
RhsPacker
template<typename ResScalar , typename LhsScalar , typename RhsScalar , typename StorageIndex , typename OutputMapper , typename LhsMapper , typename RhsMapper > typedef internal::gemm_pack_rhs<RhsScalar, StorageIndex, typename RhsMapper::SubMapper, Traits::nr, ColMajor> Eigen::internal::TensorContractionKernel< ResScalar, LhsScalar, RhsScalar, StorageIndex, OutputMapper, LhsMapper, RhsMapper >::RhsPacker
Traits
template<typename ResScalar , typename LhsScalar , typename RhsScalar , typename StorageIndex , typename OutputMapper , typename LhsMapper , typename RhsMapper > typedef internal::gebp_traits<LhsScalar, RhsScalar> Eigen::internal::TensorContractionKernel< ResScalar, LhsScalar, RhsScalar, StorageIndex, OutputMapper, LhsMapper, RhsMapper >::Traits
Member Enumeration Documentation
anonymous enum
template<typename ResScalar , typename LhsScalar , typename RhsScalar , typename StorageIndex , typename OutputMapper , typename LhsMapper , typename RhsMapper > anonymous enum
Enumerator
HasBeta
 { HasBeta = false };
Constructor & Destructor Documentation
TensorContractionKernel()
template<typename ResScalar , typename LhsScalar , typename RhsScalar , typename StorageIndex , typename OutputMapper , typename LhsMapper , typename RhsMapper > EIGEN_DEVICE_FUNC Eigen::internal::TensorContractionKernel< ResScalar, LhsScalar, RhsScalar, StorageIndex, OutputMapper, LhsMapper, RhsMapper >::TensorContractionKernel (StorageIndex m_, StorageIndex k_, StorageIndex n_, StorageIndex bm_, StorageIndex bk_, StorageIndex bn_) inline
       : m(m_), k(k_), n(n_), bm(bm_), bk(bk_), bn(bn_) {}
Member Function Documentation
allocate()
template<typename ResScalar , typename LhsScalar , typename RhsScalar , typename StorageIndex , typename OutputMapper , typename LhsMapper , typename RhsMapper > template<typename Device > EIGEN_DEVICE_FUNC BlockMemHandle Eigen::internal::TensorContractionKernel< ResScalar, LhsScalar, RhsScalar, StorageIndex, OutputMapper, LhsMapper, RhsMapper >::allocate (Device & d, LhsBlock * lhs_block, RhsBlock * rhs_block) inline
{
     return BlockMemAllocator::allocate(d, bm, bk, bn, lhs_block, rhs_block);
   }
References Eigen::internal::TensorContractionBlockMemAllocator< LhsScalar, RhsScalar >::allocate(), Eigen::internal::TensorContractionKernel< ResScalar, LhsScalar, RhsScalar, StorageIndex, OutputMapper, LhsMapper, RhsMapper >::bk, Eigen::internal::TensorContractionKernel< ResScalar, LhsScalar, RhsScalar, StorageIndex, OutputMapper, LhsMapper, RhsMapper >::bm, and Eigen::internal::TensorContractionKernel< ResScalar, LhsScalar, RhsScalar, StorageIndex, OutputMapper, LhsMapper, RhsMapper >::bn.
allocateSlices()
template<typename ResScalar , typename LhsScalar , typename RhsScalar , typename StorageIndex , typename OutputMapper , typename LhsMapper , typename RhsMapper > template<typename Device > EIGEN_DEVICE_FUNC BlockMemHandle Eigen::internal::TensorContractionKernel< ResScalar, LhsScalar, RhsScalar, StorageIndex, OutputMapper, LhsMapper, RhsMapper >::allocateSlices (Device & d, const StorageIndex num_lhs, const StorageIndex num_rhs, const StorageIndex num_slices, std::vector< LhsBlock > * lhs_blocks, std::vector< RhsBlock > * rhs_blocks) inline
{
     return BlockMemAllocator::allocateSlices(d, bm, bk, bn, num_lhs, num_rhs, num_slices, lhs_blocks, rhs_blocks);
   }
References Eigen::internal::TensorContractionBlockMemAllocator< LhsScalar, RhsScalar >::allocateSlices(), Eigen::internal::TensorContractionKernel< ResScalar, LhsScalar, RhsScalar, StorageIndex, OutputMapper, LhsMapper, RhsMapper >::bk, Eigen::internal::TensorContractionKernel< ResScalar, LhsScalar, RhsScalar, StorageIndex, OutputMapper, LhsMapper, RhsMapper >::bm, and Eigen::internal::TensorContractionKernel< ResScalar, LhsScalar, RhsScalar, StorageIndex, OutputMapper, LhsMapper, RhsMapper >::bn.
deallocate()
template<typename ResScalar , typename LhsScalar , typename RhsScalar , typename StorageIndex , typename OutputMapper , typename LhsMapper , typename RhsMapper > template<typename Device > static EIGEN_DEVICE_FUNC void Eigen::internal::TensorContractionKernel< ResScalar, LhsScalar, RhsScalar, StorageIndex, OutputMapper, LhsMapper, RhsMapper >::deallocate (Device & d, BlockMemHandle handle) inline static
{
     BlockMemAllocator::deallocate(d, handle);
   }
References Eigen::internal::TensorContractionBlockMemAllocator< LhsScalar, RhsScalar >::deallocate().
invoke()
template<typename ResScalar , typename LhsScalar , typename RhsScalar , typename StorageIndex , typename OutputMapper , typename LhsMapper , typename RhsMapper > EIGEN_DEVICE_FUNC EIGEN_DONT_INLINE void Eigen::internal::TensorContractionKernel< ResScalar, LhsScalar, RhsScalar, StorageIndex, OutputMapper, LhsMapper, RhsMapper >::invoke (const OutputMapper & output_mapper, const LhsBlock & lhsBlock, const RhsBlock & rhsBlock, const StorageIndex rows, const StorageIndex depth, const StorageIndex cols, const ResScalar alpha, const ResScalar beta) inline
{
     // Default GEBP kernel does not support beta.
     eigen_assert(beta == ResScalar(1));
     static const int kComputeStrideFromBlockDimensions = -1;
     GebpKernel()(output_mapper, lhsBlock, rhsBlock, rows, depth, cols, alpha,
                  /*strideA*/ kComputeStrideFromBlockDimensions,
                  /*strideB*/ kComputeStrideFromBlockDimensions,
                  /*offsetA*/ 0, /*offsetB*/ 0);
   }
References alpha, beta, cols, eigen_assert, and rows.
packLhs()
template<typename ResScalar , typename LhsScalar , typename RhsScalar , typename StorageIndex , typename OutputMapper , typename LhsMapper , typename RhsMapper > EIGEN_DEVICE_FUNC EIGEN_DONT_INLINE void Eigen::internal::TensorContractionKernel< ResScalar, LhsScalar, RhsScalar, StorageIndex, OutputMapper, LhsMapper, RhsMapper >::packLhs (LhsBlock * lhsBlock, const typename LhsMapper::SubMapper & data_mapper, const StorageIndex depth, const StorageIndex rows) inline
{
     LhsPacker()(*lhsBlock, data_mapper, depth, rows, /*stride*/ 0,
                 /*offset*/ 0);
   }
References rows.
packRhs()
template<typename ResScalar , typename LhsScalar , typename RhsScalar , typename StorageIndex , typename OutputMapper , typename LhsMapper , typename RhsMapper > EIGEN_DEVICE_FUNC EIGEN_DONT_INLINE void Eigen::internal::TensorContractionKernel< ResScalar, LhsScalar, RhsScalar, StorageIndex, OutputMapper, LhsMapper, RhsMapper >::packRhs (RhsBlock * rhsBlock, const typename RhsMapper::SubMapper & data_mapper, const StorageIndex depth, const StorageIndex cols) inline
{
     RhsPacker()(*rhsBlock, data_mapper, depth, cols);
   }
References cols.
Member Data Documentation
bk
template<typename ResScalar , typename LhsScalar , typename RhsScalar , typename StorageIndex , typename OutputMapper , typename LhsMapper , typename RhsMapper > const StorageIndex Eigen::internal::TensorContractionKernel< ResScalar, LhsScalar, RhsScalar, StorageIndex, OutputMapper, LhsMapper, RhsMapper >::bk private
Referenced by Eigen::internal::TensorContractionKernel< ResScalar, LhsScalar, RhsScalar, StorageIndex, OutputMapper, LhsMapper, RhsMapper >::allocate(), and Eigen::internal::TensorContractionKernel< ResScalar, LhsScalar, RhsScalar, StorageIndex, OutputMapper, LhsMapper, RhsMapper >::allocateSlices().
bm
template<typename ResScalar , typename LhsScalar , typename RhsScalar , typename StorageIndex , typename OutputMapper , typename LhsMapper , typename RhsMapper > const StorageIndex Eigen::internal::TensorContractionKernel< ResScalar, LhsScalar, RhsScalar, StorageIndex, OutputMapper, LhsMapper, RhsMapper >::bm private
Referenced by Eigen::internal::TensorContractionKernel< ResScalar, LhsScalar, RhsScalar, StorageIndex, OutputMapper, LhsMapper, RhsMapper >::allocate(), and Eigen::internal::TensorContractionKernel< ResScalar, LhsScalar, RhsScalar, StorageIndex, OutputMapper, LhsMapper, RhsMapper >::allocateSlices().
bn
template<typename ResScalar , typename LhsScalar , typename RhsScalar , typename StorageIndex , typename OutputMapper , typename LhsMapper , typename RhsMapper > const StorageIndex Eigen::internal::TensorContractionKernel< ResScalar, LhsScalar, RhsScalar, StorageIndex, OutputMapper, LhsMapper, RhsMapper >::bn private
Referenced by Eigen::internal::TensorContractionKernel< ResScalar, LhsScalar, RhsScalar, StorageIndex, OutputMapper, LhsMapper, RhsMapper >::allocate(), and Eigen::internal::TensorContractionKernel< ResScalar, LhsScalar, RhsScalar, StorageIndex, OutputMapper, LhsMapper, RhsMapper >::allocateSlices().
k
template<typename ResScalar , typename LhsScalar , typename RhsScalar , typename StorageIndex , typename OutputMapper , typename LhsMapper , typename RhsMapper > const StorageIndex Eigen::internal::TensorContractionKernel< ResScalar, LhsScalar, RhsScalar, StorageIndex, OutputMapper, LhsMapper, RhsMapper >::k private
m
template<typename ResScalar , typename LhsScalar , typename RhsScalar , typename StorageIndex , typename OutputMapper , typename LhsMapper , typename RhsMapper > const StorageIndex Eigen::internal::TensorContractionKernel< ResScalar, LhsScalar, RhsScalar, StorageIndex, OutputMapper, LhsMapper, RhsMapper >::m private
n
template<typename ResScalar , typename LhsScalar , typename RhsScalar , typename StorageIndex , typename OutputMapper , typename LhsMapper , typename RhsMapper > const StorageIndex Eigen::internal::TensorContractionKernel< ResScalar, LhsScalar, RhsScalar, StorageIndex, OutputMapper, LhsMapper, RhsMapper >::n private
The documentation for this struct was generated from the following file:
TensorContraction.h