MercuryDPM: oomph::FishDomain Class Reference
oomph::FishDomain Class Reference
#include <fish_domain.h>
Public Member Functions
FishDomain (GeomObject *back_pt, const double &xi_nose, const double &xi_tail)
FishDomain (const FishDomain &)=delete
Broken copy constructor.
void operator= (const FishDomain &)=delete
Broken assignment operator.
virtual ~FishDomain ()
Destructor for FishDomain: Empty; cleanup done in base class.
double & x_fin ()
x-position of fin tip
double & y_fin ()
y-position of fin tip
double & x_mouth ()
x-position of mouth
double & xi_nose ()
Start coordinate on wall (near nose)
double & xi_tail ()
End coordinate on wall (near tail)
void macro_element_boundary (const unsigned &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &zeta, Vector< double > &r)
Public Member Functions inherited from oomph::Domain
Domain ()
Constructor.
Domain (const Domain &)=delete
Broken copy constructor.
void operator= (const Domain &)=delete
Broken assignment operator.
virtual ~Domain ()
MacroElement * macro_element_pt (const unsigned &i)
Access to i-th macro element.
unsigned nmacro_element ()
Number of macro elements in domain.
void output (const std::string &filename, const unsigned &nplot)
Output macro elements.
void output (std::ostream &outfile, const unsigned &nplot)
Output macro elements.
virtual void macro_element_boundary (const double &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void macro_element_boundary (const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void output_macro_element_boundaries (const std::string &filename, const unsigned &nplot)
Output all macro element boundaries as tecplot zones.
void output_macro_element_boundaries (std::ostream &outfile, const unsigned &nplot)
Output all macro element boundaries as tecplot zones.
virtual void dmacro_element_boundary (const unsigned &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
virtual void dmacro_element_boundary (const double &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void dmacro_element_boundary (const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
virtual void d2macro_element_boundary (const unsigned &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
virtual void d2macro_element_boundary (const double &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void d2macro_element_boundary (const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
Private Member Functions
void r_upper_body_N (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
Boundary of upper body macro element zeta \(\in [-1,1] \).
void r_upper_body_W (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
Boundary of upper body macro element zeta \(\in [-1,1] \).
void r_upper_body_S (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
Boundary of upper body macro element zeta \(\in [-1,1] \).
void r_upper_body_E (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
Boundary of upper body macro element zeta \(\in [-1,1] \).
void r_upper_fin_N (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
Boundary of upper fin macro element zeta \(\in [-1,1] \).
void r_upper_fin_W (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
Boundary of upper fin macro element zeta \(\in [-1,1] \).
void r_upper_fin_S (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
Boundary of upper fin macro element zeta \(\in [-1,1] \).
void r_upper_fin_E (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
Boundary of upper fin macro element zeta \(\in [-1,1] \).
void r_lower_body_N (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
Boundary of lower body macro element zeta \(\in [-1,1] \).
void r_lower_body_W (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
Boundary of lower body macro element zeta \(\in [-1,1] \).
void r_lower_body_S (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
Southern boundary of lower body macro element zeta \(\in [-1,1] \).
void r_lower_body_E (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
Boundary of lower body macro element zeta \(\in [-1,1] \).
void r_lower_fin_N (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
Boundary of lower fin macro element zeta \(\in [-1,1] \).
void r_lower_fin_W (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
Boundary of lower fin macro element zeta \(\in [-1,1] \).
void r_lower_fin_S (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
Boundary of lower fin macro element zeta \(\in [-1,1] \).
void r_lower_fin_E (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
Boundary of lower fin macro element zeta \(\in [-1,1] \).
Private Attributes
double Xi_nose
"Nose" limit for the (1D) coordinates along the wall
double Xi_tail
"Tail" limit for the (1D) coordinates along the wall
double X_fin
X coordinate of fin tip.
double Y_fin
Y coordinate of fin tip.
double X_mouth
X coordinate of corner of mouth.
GeomObject * Back_pt
Pointer to the fish's back.
Additional Inherited Members
Protected Attributes inherited from oomph::Domain
Vector< MacroElement * > Macro_element_pt
Vector of pointers to macro elements.
Detailed Description
Fish shaped domain, represented by four MacroElements. Shape is parametrised by GeomObject that represents the fish's back.
Constructor & Destructor Documentation
FishDomain() [1/2]
oomph::FishDomain::FishDomain (GeomObject * back_pt, const double & xi_nose, const double & xi_tail) inline
Constructor: Pass pointer to GeomObject that represents the (upper) curved boundary of the fish's body, and the start and end values of the Lagrangian coordinates along the GeomObject.
       : Xi_nose(xi_nose), Xi_tail(xi_tail), Back_pt(back_pt)
     {
       // Set values for private data members that are describe
       // geometric features of the fish: x-coordinate of the fin,
       // (half-)height of the fin, and x-position of the mouth.
       X_fin = 1.7;
       Y_fin = 0.9;
       X_mouth = 0.0;
       // There are four macro elements
       unsigned nmacro = 4;
       Macro_element_pt.resize(nmacro);
       // Build them
       for (unsigned i = 0; i < nmacro; i++)
       {
         Macro_element_pt[i] = new QMacroElement<2>(this, i);
       }
     } // end of constructor
References i, oomph::Domain::Macro_element_pt, X_fin, X_mouth, and Y_fin.
FishDomain() [2/2]
oomph::FishDomain::FishDomain (const FishDomain &) delete
Broken copy constructor.
~FishDomain()
virtual oomph::FishDomain::~FishDomain () inline virtual
Destructor for FishDomain: Empty; cleanup done in base class.
 {}
Member Function Documentation
macro_element_boundary()
void oomph::FishDomain::macro_element_boundary (const unsigned & t, const unsigned & imacro, const unsigned & idirect, const Vector< double > & zeta, Vector< double > & r) virtual
Vector representation of the i_macro-th macro element boundary i_direct (N/S/W/E) at the discrete time level t (t=0: present; t>0: previous): \({\bf r}({\bf zeta}) \) Note that the local coordinate zeta is a 1D Vector rather than a scalar – this is unavoidable because this function implements the pure virtual function in the Domain base class.
////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////// Vector representation of the imacro-th macro element boundary idirect (N/S/W/E) at time level t (t=0: present; t>0: previous): \({\bf r}({\bf zeta}) \) Note that the local coordinate zeta is a 1D Vector rather than a scalar – this is unavoidable because this function implements the pure virtual function in the Domain base class.
Implements oomph::Domain.
   {
     using namespace QuadTreeNames;
 #ifdef WARN_ABOUT_SUBTLY_CHANGED_OOMPH_INTERFACES
     // Warn about time argument being moved to the front
     OomphLibWarning(
       "Order of function arguments has changed between versions 0.8 and 0.85",
       "FishDomain::macro_element_boundary(...)",
       OOMPH_EXCEPTION_LOCATION);
 #endif
     // Which macro element?
     // --------------------
     switch (imacro)
     {
         // Macro element 0: Lower body
       case 0:
         // Which direction?
         if (idirect == N)
         {
           FishDomain::r_lower_body_N(t, zeta, r);
         }
         else if (idirect == S)
         {
           FishDomain::r_lower_body_S(t, zeta, r);
         }
         else if (idirect == W)
         {
           FishDomain::r_lower_body_W(t, zeta, r);
         }
         else if (idirect == E)
         {
           FishDomain::r_lower_body_E(t, zeta, r);
         }
         else
         {
           std::ostringstream error_stream;
           error_stream << "idirect is " << idirect << " not one of N, S, E, W"
                        << std::endl;
           throw OomphLibError(error_stream.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
         break;
         // Macro element 1: Lower Fin
       case 1:
         // Which direction?
         if (idirect == N)
         {
           FishDomain::r_lower_fin_N(t, zeta, r);
         }
         else if (idirect == S)
         {
           FishDomain::r_lower_fin_S(t, zeta, r);
         }
         else if (idirect == W)
         {
           FishDomain::r_lower_fin_W(t, zeta, r);
         }
         else if (idirect == E)
         {
           FishDomain::r_lower_fin_E(t, zeta, r);
         }
         else
         {
           std::ostringstream error_stream;
           error_stream << "idirect is " << idirect << " not one of N, S, E, W"
                        << std::endl;
           throw OomphLibError(error_stream.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
         break;
         // Macro element 2: Upper body
       case 2:
         // Which direction?
         if (idirect == N)
         {
           FishDomain::r_upper_body_N(t, zeta, r);
         }
         else if (idirect == S)
         {
           FishDomain::r_upper_body_S(t, zeta, r);
         }
         else if (idirect == W)
         {
           FishDomain::r_upper_body_W(t, zeta, r);
         }
         else if (idirect == E)
         {
           FishDomain::r_upper_body_E(t, zeta, r);
         }
         else
         {
           std::ostringstream error_stream;
           error_stream << "idirect is " << idirect << " not one of N, S, E, W"
                        << std::endl;
           throw OomphLibError(error_stream.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
         break;
         // Macro element 3: Upper Fin
       case 3:
         // Which direction?
         if (idirect == N)
         {
           FishDomain::r_upper_fin_N(t, zeta, r);
         }
         else if (idirect == S)
         {
           FishDomain::r_upper_fin_S(t, zeta, r);
         }
         else if (idirect == W)
         {
           FishDomain::r_upper_fin_W(t, zeta, r);
         }
         else if (idirect == E)
         {
           FishDomain::r_upper_fin_E(t, zeta, r);
         }
         else
         {
           std::ostringstream error_stream;
           error_stream << "idirect is " << idirect << " not one of N, S, E, W"
                        << std::endl;
           throw OomphLibError(error_stream.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
         break;
       default:
         // Error
         std::ostringstream error_stream;
         error_stream << "Wrong imacro " << imacro << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
   } // end of macro_element_boundary
References Global_Physical_Variables::E, N, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, UniformPSDSelfTest::r, r_lower_body_E(), r_lower_body_N(), r_lower_body_S(), r_lower_body_W(), r_lower_fin_E(), r_lower_fin_N(), r_lower_fin_S(), r_lower_fin_W(), r_upper_body_E(), r_upper_body_N(), r_upper_body_S(), r_upper_body_W(), r_upper_fin_E(), r_upper_fin_N(), r_upper_fin_S(), r_upper_fin_W(), oomph::QuadTreeNames::S, plotPSD::t, oomph::QuadTreeNames::W, and Eigen::zeta().
operator=()
void oomph::FishDomain::operator= (const FishDomain &) delete
Broken assignment operator.
r_lower_body_E()
void oomph::FishDomain::r_lower_body_E (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) inline private
Boundary of lower body macro element zeta \(\in [-1,1] \).
     {
       // East of lower body is element is east of upper one.
       // Direction of the coordinate is inverted.
       Vector<double> zeta_new(1);
       zeta_new[0] = -zeta[0];
       r_upper_body_E(t, zeta_new, f);
       // Vertical coordinate is reflected
       f[1] = -f[1];
     }
References f(), r_upper_body_E(), plotPSD::t, and Eigen::zeta().
Referenced by macro_element_boundary().
r_lower_body_N()
void oomph::FishDomain::r_lower_body_N (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) inline private
Boundary of lower body macro element zeta \(\in [-1,1] \).
     {
       // North of lower body is element is south of upper one.
       // Direction of the coordinate stays the same.
       r_upper_body_S(t, zeta, f);
       // Reflect vertical position
       f[1] = -f[1];
     }
References f(), r_upper_body_S(), plotPSD::t, and Eigen::zeta().
Referenced by macro_element_boundary().
r_lower_body_S()
void oomph::FishDomain::r_lower_body_S (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) inline private
Southern boundary of lower body macro element zeta \(\in [-1,1] \).
     {
       // South of lower body is element is north of upper one.
       // Direction of the coordinate stays the same.
       r_upper_body_N(t, zeta, f);
       // Reflect vertical position
       f[1] = -f[1];
     }
References f(), r_upper_body_N(), plotPSD::t, and Eigen::zeta().
Referenced by macro_element_boundary().
r_lower_body_W()
void oomph::FishDomain::r_lower_body_W (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) inline private
Boundary of lower body macro element zeta \(\in [-1,1] \).
     {
       // West of lower body is element is west of upper one.
       // Direction of the coordinate is inverted
       Vector<double> zeta_new(1);
       zeta_new[0] = -zeta[0];
       r_upper_body_W(t, zeta_new, f);
       // Vertical coordinate is reflected
       f[1] = -f[1];
     }
References f(), r_upper_body_W(), plotPSD::t, and Eigen::zeta().
Referenced by macro_element_boundary().
r_lower_fin_E()
void oomph::FishDomain::r_lower_fin_E (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) inline private
Boundary of lower fin macro element zeta \(\in [-1,1] \).
     {
       // East of lower fin is element is east of upper one.
       // Direction of the coordinate is inverted.
       Vector<double> zeta_new(1);
       zeta_new[0] = -zeta[0];
       r_upper_fin_E(t, zeta_new, f);
       // Vertical coordinate is reflected
       f[1] = -f[1];
     }
References f(), r_upper_fin_E(), plotPSD::t, and Eigen::zeta().
Referenced by macro_element_boundary().
r_lower_fin_N()
void oomph::FishDomain::r_lower_fin_N (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) inline private
Boundary of lower fin macro element zeta \(\in [-1,1] \).
     {
       // North of lower fin is element is south of upper one.
       // Direction of the coordinate stays the same.
       r_upper_fin_S(t, zeta, f);
       // Reflect vertical position
       f[1] = -f[1];
     }
References f(), r_upper_fin_S(), plotPSD::t, and Eigen::zeta().
Referenced by macro_element_boundary().
r_lower_fin_S()
void oomph::FishDomain::r_lower_fin_S (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) inline private
Boundary of lower fin macro element zeta \(\in [-1,1] \).
     {
       // South of lower fin is element is north of upper one.
       // Direction of the coordinate stays the same.
       r_upper_fin_N(t, zeta, f);
       // Reflect vertical position
       f[1] = -f[1];
     }
References f(), r_upper_fin_N(), plotPSD::t, and Eigen::zeta().
Referenced by macro_element_boundary().
r_lower_fin_W()
void oomph::FishDomain::r_lower_fin_W (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) inline private
Boundary of lower fin macro element zeta \(\in [-1,1] \).
     {
       // West of lower fin is element is west of upper one.
       // Direction of the coordinate is inverted
       Vector<double> zeta_new(1);
       zeta_new[0] = -zeta[0];
       r_upper_fin_W(t, zeta_new, f);
       // Vertical coordinate is reflected
       f[1] = -f[1];
     }
References f(), r_upper_fin_W(), plotPSD::t, and Eigen::zeta().
Referenced by macro_element_boundary().
r_upper_body_E()
void oomph::FishDomain::r_upper_body_E (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of upper body macro element zeta \(\in [-1,1] \).
Eastern edge of upper body macro element; \(\zeta \in [-1,1] \).
   {
     // Top right corner (tail end) of body
     Vector<double> r_top(2);
     Vector<double> x(1);
     x[0] = Xi_tail;
     Back_pt->position(t, x, r_top);
     // Corresponding point on the x-axis
     Vector<double> r_back(2);
     r_back[0] = r_top[0];
     r_back[1] = 0.0;
     r[0] = r_back[0] + (r_top[0] - r_back[0]) * 0.5 * (zeta[0] + 1.0);
     r[1] = r_back[1] + (r_top[1] - r_back[1]) * 0.5 * (zeta[0] + 1.0);
   } // end of r_upper_body_E
References Back_pt, oomph::GeomObject::position(), UniformPSDSelfTest::r, plotPSD::t, plotDoE::x, Xi_tail, and Eigen::zeta().
Referenced by macro_element_boundary(), and r_lower_body_E().
r_upper_body_N()
void oomph::FishDomain::r_upper_body_N (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of upper body macro element zeta \(\in [-1,1] \).
Northern edge of upper body macro element; \(\zeta \in [-1,1] \).
   {
     // Lagrangian coordinate along curved "back"
     Vector<double> x(1);
     x[0] = Xi_nose + (Xi_tail - Xi_nose) * 0.5 * (zeta[0] + 1.0);
     // Get position on curved back
     Back_pt->position(t, x, r);
   } // end of r_upper_body_N
References Back_pt, oomph::GeomObject::position(), UniformPSDSelfTest::r, plotPSD::t, plotDoE::x, Xi_nose, Xi_tail, and Eigen::zeta().
Referenced by macro_element_boundary(), and r_lower_body_S().
r_upper_body_S()
void oomph::FishDomain::r_upper_body_S (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of upper body macro element zeta \(\in [-1,1] \).
Southern edge of upper body macro element; \(\zeta \in [-1,1] \).
   {
     // Top right (tail) corner of fish body
     Vector<double> r_top(2);
     Vector<double> x(1);
     x[0] = Xi_tail;
     Back_pt->position(t, x, r_top);
     // Straight line from mouth to start of fin (=end of body)
     r[0] = X_mouth + (r_top[0] - X_mouth) * 0.5 * (zeta[0] + 1.0);
     r[1] = 0.0;
   } // end of r_upper_body_S
References Back_pt, oomph::GeomObject::position(), UniformPSDSelfTest::r, plotPSD::t, plotDoE::x, X_mouth, Xi_tail, and Eigen::zeta().
Referenced by macro_element_boundary(), and r_lower_body_N().
r_upper_body_W()
void oomph::FishDomain::r_upper_body_W (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of upper body macro element zeta \(\in [-1,1] \).
Western edge of upper body macro element; \(\zeta \in [-1,1] \).
   {
     // Top left (mouth) corner of curved boundary of upper body
     Vector<double> r_top(2);
     Vector<double> x(1);
     x[0] = Xi_nose;
     Back_pt->position(t, x, r_top);
     // The "mouth"
     Vector<double> r_mouth(2);
     r_mouth[0] = X_mouth;
     r_mouth[1] = 0.0;
     // Straight line from mouth to leftmost corner on curved boundary
     // of upper body
     r[0] = r_mouth[0] + (r_top[0] - r_mouth[0]) * 0.5 * (zeta[0] + 1.0);
     r[1] = r_mouth[1] + (r_top[1] - r_mouth[1]) * 0.5 * (zeta[0] + 1.0);
   } // end of r_upper_body_W
References Back_pt, oomph::GeomObject::position(), UniformPSDSelfTest::r, plotPSD::t, plotDoE::x, X_mouth, Xi_nose, and Eigen::zeta().
Referenced by macro_element_boundary(), and r_lower_body_W().
r_upper_fin_E()
void oomph::FishDomain::r_upper_fin_E (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of upper fin macro element zeta \(\in [-1,1] \).
Eastern edge of upper fin macro element; \(\zeta \in [-1,1] \).
   {
     // Straight vertical line from top of fin
     r[0] = X_fin;
     r[1] = Y_fin * 0.5 * (zeta[0] + 1.0);
   }
References UniformPSDSelfTest::r, X_fin, Y_fin, and Eigen::zeta().
Referenced by macro_element_boundary(), and r_lower_fin_E().
r_upper_fin_N()
void oomph::FishDomain::r_upper_fin_N (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of upper fin macro element zeta \(\in [-1,1] \).
Northern edge of upper fin macro element; \(\zeta \in [-1,1] \).
   {
     // Right end of fish back
     Vector<double> x(1);
     x[0] = Xi_tail;
     Vector<double> r_fish(2);
     Back_pt->position(t, x, r_fish);
     // Top end of fin
     Vector<double> r_fin(2);
     r_fin[0] = X_fin;
     r_fin[1] = Y_fin;
     // Straight line along upper fin
     r[0] = r_fish[0] + (r_fin[0] - r_fish[0]) * 0.5 * (zeta[0] + 1.0);
     r[1] = r_fish[1] + (r_fin[1] - r_fish[1]) * 0.5 * (zeta[0] + 1.0);
   }
References Back_pt, oomph::GeomObject::position(), UniformPSDSelfTest::r, plotPSD::t, plotDoE::x, X_fin, Xi_tail, Y_fin, and Eigen::zeta().
Referenced by macro_element_boundary(), and r_lower_fin_S().
r_upper_fin_S()
void oomph::FishDomain::r_upper_fin_S (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of upper fin macro element zeta \(\in [-1,1] \).
Southern edge of upper fin macro element; \(\zeta \in [-1,1] \).
   {
     // Right end of fish back
     Vector<double> x(1);
     x[0] = Xi_tail;
     Vector<double> r_fish(2);
     Back_pt->position(t, x, r_fish);
     r[0] = r_fish[0] * 0.5 * (zeta[0] + 1.0);
     r[1] = 0.0;
   }
References Back_pt, oomph::GeomObject::position(), UniformPSDSelfTest::r, plotPSD::t, plotDoE::x, Xi_tail, and Eigen::zeta().
Referenced by macro_element_boundary(), and r_lower_fin_N().
r_upper_fin_W()
void oomph::FishDomain::r_upper_fin_W (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of upper fin macro element zeta \(\in [-1,1] \).
Western edge of upper fin macro element; \(\zeta \in [-1,1] \).
   {
     // Right end of fish back
     Vector<double> x(1);
     x[0] = Xi_tail;
     Vector<double> r_fish(2);
     Back_pt->position(t, x, r_fish);
     r[0] = r_fish[0];
     r[1] = r_fish[1] * 0.5 * (zeta[0] + 1.0);
   }
References Back_pt, oomph::GeomObject::position(), UniformPSDSelfTest::r, plotPSD::t, plotDoE::x, Xi_tail, and Eigen::zeta().
Referenced by macro_element_boundary(), and r_lower_fin_W().
x_fin()
double& oomph::FishDomain::x_fin () inline
x-position of fin tip
     {
       return X_fin;
     }
References X_fin.
x_mouth()
double& oomph::FishDomain::x_mouth () inline
x-position of mouth
     {
       return X_mouth;
     }
References X_mouth.
xi_nose()
double& oomph::FishDomain::xi_nose () inline
Start coordinate on wall (near nose)
     {
       return Xi_nose;
     }
References Xi_nose.
Referenced by oomph::AlgebraicFishMesh< ELEMENT >::update_node_update().
xi_tail()
double& oomph::FishDomain::xi_tail () inline
End coordinate on wall (near tail)
     {
       return Xi_tail;
     }
References Xi_tail.
Referenced by oomph::AlgebraicFishMesh< ELEMENT >::update_node_update().
y_fin()
double& oomph::FishDomain::y_fin () inline
y-position of fin tip
     {
       return Y_fin;
     }
References Y_fin.
Member Data Documentation
Back_pt
GeomObject* oomph::FishDomain::Back_pt private
Pointer to the fish's back.
Referenced by r_upper_body_E(), r_upper_body_N(), r_upper_body_S(), r_upper_body_W(), r_upper_fin_N(), r_upper_fin_S(), and r_upper_fin_W().
X_fin
double oomph::FishDomain::X_fin private
X coordinate of fin tip.
Referenced by FishDomain(), r_upper_fin_E(), r_upper_fin_N(), and x_fin().
X_mouth
double oomph::FishDomain::X_mouth private
X coordinate of corner of mouth.
Referenced by FishDomain(), r_upper_body_S(), r_upper_body_W(), and x_mouth().
Xi_nose
double oomph::FishDomain::Xi_nose private
"Nose" limit for the (1D) coordinates along the wall
Referenced by r_upper_body_N(), r_upper_body_W(), and xi_nose().
Xi_tail
double oomph::FishDomain::Xi_tail private
"Tail" limit for the (1D) coordinates along the wall
Referenced by r_upper_body_E(), r_upper_body_N(), r_upper_body_S(), r_upper_fin_N(), r_upper_fin_S(), r_upper_fin_W(), and xi_tail().
Y_fin
double oomph::FishDomain::Y_fin private
Y coordinate of fin tip.
Referenced by FishDomain(), r_upper_fin_E(), r_upper_fin_N(), and y_fin().
The documentation for this class was generated from the following file:
fish_domain.h