MercuryDPM: CompareNodes Class Reference
CompareNodes Class Reference
Public Member Functions
int operator() (Node *const &node1_pt, Node *const &node2_pt)
Define the comparison operator using the round brackets.
Detailed Description
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// A class to do comparison of the nodes based on lexicographical ordering in the Cartesian coordinates. This is required to symmetrise eigenfunction (which is a bit of a hack)
Member Function Documentation
operator()()
int CompareNodes::operator() (Node *const & node1_pt, Node *const & node2_pt) inline
Define the comparison operator using the round brackets.
    {
     //Find the dimension of the node
      unsigned n_dim = node1_pt->ndim();
      //Check that the dimensions of both nodes are the same
      {
       unsigned n_dim2 = node2_pt->ndim();
       //If not issue a warning
       if(n_dim != n_dim2)
        {
         std::ostringstream warn_message;
         warn_message
          << "Warning: Two nodess do not have the same dimension"
          << n_dim << " and " << n_dim2 << ". They cannot be compared\n";
         OomphLibWarning(warn_message.str(),
                         "CompareNodes::()",
                         OOMPH_EXCEPTION_LOCATION);
        }
      }
      //Get the global coordinates of the nodes
      Vector<double> x1(n_dim), x2(n_dim);
      for(unsigned i=0;i<n_dim;i++)
       {
        x1[i] = node1_pt->x(i);
        x2[i] = node2_pt->x(i);
       }
      //This is the Stroustrup-approved way to do lexicographical ordering
      //Loop over the components until they are not equal
      //to within a given tolerance
      {
       unsigned i=0; double tol = 1.0e-14;
       while(i!=n_dim && (std::abs(x1[i]-x2[i]) < tol)){ ++i;}
       //If we've reached the end, the coordinates are equal, return false
       if(i==n_dim) {return 0;}
       //Otherwise, return the ordering on the final component
       return x1[i] < x2[i];
      }
     }
References abs(), i, oomph::Node::ndim(), OOMPH_EXCEPTION_LOCATION, oomph::Node::x(), Global_parameters::x1(), and Global_parameters::x2().
The documentation for this class was generated from the following file:
adaptive_pitchfork.cc