MercuryDPM: Binary.cpp File Reference
Binary.cpp File Reference
#include <iostream>
#include <Species/LinearViscoelasticSlidingFrictionSpecies.h>
#include "Mercury3D.h"
#include "Walls/InfiniteWall.h"
Classes
class Binary
Functions
int main ()
Function Documentation
main()
int main ()
            {
     // Set up a problem of type binary
     Binary dpm;
     // Set name of output files
     dpm.setName("Binary");
     // Set simulation time
     dpm.setTimeMax(21);
     // Set container size
     dpm.setMax({0.1,0.025,0.4});
     // Set particle and wall properties (5mm glass particles)
     // number of particles
     dpm.setNumberOfParticles(250);
     // radius of particles species 1/2
     dpm.setParticleRadius(2.50002e-3, 2.5e-3);
     // density of particles species 1/2
     dpm.setParticleDensity(2500, 2500); //2500 & 7850 --> glass & steel.
     // set stiffness and dissipation such that you get a constant collision time and coefficient of restitution
     double tc = 1e-4;
     dpm.setCollisionTime(tc);
     // coefficient of restitution or particle - particle collisions (for species 1-1, 1-2, and 2-2)
     dpm.setParticleRestitution(0.91, 0.91, 0.91); //(11, 22, 12) OR just leave as a single value for equal Restitution.
     // coefficient of restitution or particle - base collisions (for all species)
     dpm.setBaseRestitution(0.6);
     // coefficient of restitution or particle - side wall collisions (for all species)
     dpm.setWallRestitution(0.7);
     // friction coefficient of walls
     dpm.setWallFriction(0.0); //
     // frequency of base
     dpm.setFrequency(70);
     // amplitude of base
     dpm.setInitialAmplitude(0.862e-3); //normally 0.862
     // at a certain time, switch amplitude
     //dpm.setSwitchPlateAmplitude(3.0, 0.862e-3); //(time, new amplitude)
     // uncomment to number your output files (prevents old simulations from being overwritten by new simulations)
     //dpm.autoNumber();
     // set time step
     dpm.setTimeStep(tc / 50);
     // set frequency of writing output
     dpm.setSaveCount(21000);
     // randomise seed //TURN THIS OFF IF I WANT REPRODUCIBLE DATA!!
     //random.randomise();
     // start the solver
     dpm.solve();
 }
References e(), Binary::setBaseRestitution(), Binary::setCollisionTime(), Binary::setFrequency(), Binary::setInitialAmplitude(), DPMBase::setMax(), DPMBase::setName(), Binary::setNumberOfParticles(), Binary::setParticleDensity(), Binary::setParticleRadius(), Binary::setParticleRestitution(), DPMBase::setSaveCount(), DPMBase::setTimeMax(), DPMBase::setTimeStep(), Binary::setWallFriction(), Binary::setWallRestitution(), and DPMBase::solve().