MercuryDPM: EnergyUnitTest.cpp File Reference
EnergyUnitTest.cpp File Reference
#include "Species/LinearViscoelasticIrreversibleAdhesiveSpecies.h"
#include "Species/LinearViscoelasticReversibleAdhesiveSpecies.h"
#include "DPMBase.h"
#include "Logger.h"
#include "Species/LinearPlasticViscoelasticReversibleAdhesiveSpecies.h"
Classes
class EnergyUnitTest
Functions
int main (int argc UNUSED, char *argv[] UNUSED)
Function Documentation
main()
int main (int argc UNUSED, char *argv[] UNUSED)
Todo:
TW The inaccuracy of the calculation is much worse for the irreversible force model, as there is a jump in force at zero overlap; we should correct for that in the time stepping algorithm (i.e. find out what the mean force was over the duration of the time step, not using a left Riemann sum.
 {
     logger(INFO, "Test if the LinearViscoelasticReversibleAdhesiveInteraction conserves energy");
     EnergyUnitTest energyUnitTest;
     energyUnitTest.setName("ReversibleAdhesiveEnergyUnitTest");
     LinearViscoelasticReversibleAdhesiveSpecies species1;
     species1.setDensity(6.0 / constants::pi);
     species1.setStiffness(500);
     species1.setAdhesionStiffness(100);
     species1.setAdhesionForceMax(10);
     //std::cout << "maxVelocity=" << species1.getMaximumVelocity(0.5, 1.0) << std::endl;
     energyUnitTest.setTimeStep(0.002 * species1.getCollisionTime(1.0));
     //std::cout << "timeStep=" << energyUnitTest.getTimeStep() << std::endl;
     energyUnitTest.setSaveCount(3);
     energyUnitTest.setTimeMax(0.4);
     energyUnitTest.speciesHandler.copyAndAddObject(species1);
     energyUnitTest.solve();
     Mdouble lostEnergy = mathsFunc::square(0.7) - energyUnitTest.getElasticEnergy() - energyUnitTest.getKineticEnergy();
     if (!mathsFunc::isEqual(lostEnergy, 0.0, 1e-6))
     {
         logger(ERROR, "energy loss is %, but should be %", lostEnergy, 0.0);
     }
     logger(INFO, "Test if the LinearViscoelasticIrreversibleAdhesiveInteraction looses the right amount of energy\n",
            Flusher::NO_FLUSH);
     EnergyUnitTest energyUnitTest2;
     energyUnitTest2.setName("IrreversibleAdhesiveEnergyUnitTest");
     LinearViscoelasticIrreversibleAdhesiveSpecies species2;
     species2.setDensity(6.0 / constants::pi);
     species2.setStiffness(500);
     species2.setAdhesionStiffness(100);
     species2.setAdhesionForceMax(10);
     logger(INFO, "maxVelocity=%\n", species2.getMaximumVelocity(0.5, 1.0), Flusher::NO_FLUSH);
     //this test is 10 times more accurate than the previous one, as the error is so much bigger.
     energyUnitTest2.setTimeStep(0.0002 * species2.getCollisionTime(1.0));
     logger(INFO, "timeStep=%\n", energyUnitTest2.getTimeStep());
     energyUnitTest2.setSaveCount(3);
     energyUnitTest2.setTimeMax(0.2);
     energyUnitTest2.speciesHandler.copyAndAddObject(species2);
     energyUnitTest2.solve();
     lostEnergy = mathsFunc::square(0.7)-energyUnitTest2.getElasticEnergy()-energyUnitTest2.getKineticEnergy();
     if (!mathsFunc::isEqual(lostEnergy, 0.5, 1e-4))
     {
         logger(ERROR, "energy loss is %, but should be %", lostEnergy, 0.5);
     }
     return 0;
 }
References BaseHandler< T >::copyAndAddObject(), e(), ERROR, DPMBase::getElasticEnergy(), DPMBase::getKineticEnergy(), DPMBase::getTimeStep(), INFO, mathsFunc::isEqual(), logger, NO_FLUSH, constants::pi, ParticleSpecies::setDensity(), DPMBase::setName(), DPMBase::setSaveCount(), DPMBase::setTimeMax(), DPMBase::setTimeStep(), DPMBase::solve(), DPMBase::speciesHandler, and mathsFunc::square().