MercuryDPM: circular_disk.cc File Reference
all_foeppl_von_karman/circular_disk.cc File Reference
#include <fenv.h>
#include "generic.h"
#include "foeppl_von_karman.h"
#include "meshes/triangle_mesh.h"
Classes
class UnstructuredFvKProblem< ELEMENT >
Class definition.
Namespaces
GlobalParameters
Global parameters.
Functions
void GlobalParameters::get_pressure (const Vector< double > &x, double &pressure)
Pressure depending on the position (x,y)
void GlobalParameters::zero (const Vector< double > &x, Vector< double > &u)
int main (int argc, char **argv)
Driver code for demo of inline triangle mesh generation.
Variables
double GlobalParameters::Eta = 2.39e6
FvK parameter.
double GlobalParameters::R_b = 0.1
The "bubble" radius.
double GlobalParameters::Pressure =0.0
The pressure.
Function Documentation
main()
int main (int argc , char ** argv)
Driver code for demo of inline triangle mesh generation.
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Define possible command line arguments and parse the ones that
  // were actually specified
  CommandLineArgs::specify_command_line_flag("--validation");
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  // Problem instance
  UnstructuredFvKProblem<TFoepplvonKarmanElement<3> >
   problem(0.01);
  double dp=0.1;
  unsigned n_step=10;
  if (CommandLineArgs::command_line_flag_has_been_set("--validation"))
   {
    n_step=2;
   }
  for (unsigned i=0;i<n_step;i++)
   {
    oomph_info << "Solving for p = " << GlobalParameters::Pressure << std::endl;
    // Solve the problem
    problem.newton_solve();
    //Output solution
    problem.doc_solution();
    // Increment pressure
    GlobalParameters::Pressure+=dp;
   }
 } //End of main
References oomph::CommandLineArgs::command_line_flag_has_been_set(), oomph::CommandLineArgs::doc_specified_flags(), i, oomph::oomph_info, oomph::CommandLineArgs::parse_and_assign(), GlobalParameters::Pressure, problem, Flag_definition::setup(), and oomph::CommandLineArgs::specify_command_line_flag().