MercuryDPM: HeaterBoundary Class Reference
HeaterBoundary Class Reference
Supplies a 'constant heat flux' to a cuboidal region (specified by two corner points) by adding a random velocity at each time step to each particle therein, increasing the granular temperature (velocity variance).
#include <HeaterBoundary.h>
Public Member Functions
HeaterBoundary ()
HeaterBoundary (const HeaterBoundary &other)
~HeaterBoundary () override
HeaterBoundary * copy () const override
Used to create a copy of the object NB: purely virtual function.
void set (Vec3D posMin, Vec3D posMax, Vec3D specificHeatStrength)
void set2D (Vec3D posMin, Vec3D posMax, Mdouble specificHeatStrength)
void set3D (Vec3D posMin, Vec3D posMax, Mdouble specificHeatStrength)
void setStrength (Vec3D specificHeatStrength)
void setStrength2D (Mdouble specificHeatStrength)
void setStrength3D (Mdouble specificHeatStrength)
Mdouble getVolume () const
Returns the volume of the HeaterBoundary cuboid.
Mdouble getDistance (const Vec3D &position) const
Returns a negative value if and only if the position is inside the boundary (and therefore the particle to be heated).
void checkBoundaryAfterParticlesMove (ParticleHandler &pH) override
Runs at the end of each time step.
bool checkBoundaryAfterParticleMoved (BaseParticle *p, ParticleHandler &pH)
Checks if a given particle is inside the HeaterBoundary. If so, heats it.
void read (std::istream &is) override
Reads some boundary properties from an std::istream.
void write (std::ostream &os) const override
Writes the boundary properties to an std::ostream.
std::string getName () const override
Public Member Functions inherited from BaseBoundary
BaseBoundary ()
default constructor.
BaseBoundary (const BaseBoundary &b)
copy constructor
~BaseBoundary () override
destructor
virtual void createPeriodicParticle (BaseParticle *p UNUSED, ParticleHandler &pH UNUSED)
Creates a periodic particle in case of periodic boundaries in serial build.
virtual void createPeriodicParticles (ParticleHandler &pH UNUSED)
Creates periodic copies of given particle in case of periodic boundaries.
virtual void checkBoundaryBeforeTimeStep (DPMBase *md)
Virtual function that does things before each time step.
virtual void actionsBeforeTimeLoop ()
Virtual function that does something after DPMBase::setupInitialConditions but before the first time step.
virtual void modifyGhostAfterCreation (BaseParticle *particle, int i)
virtual void writeVTK (std::fstream &file)
void setHandler (BoundaryHandler *handler)
Sets the boundary's BoundaryHandler.
BoundaryHandler * getHandler () const
Returns the boundary's BoundaryHandler.
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Private Attributes
Vec3D posMin_
Vec3D posMax_
Vec3D specificHeatStrength_
The specific heat strengths have units of energy (mass)^{-1} (time)^{-1) = m^2 s^{-3} For isotropic heating, take a vector proportional to (s/3, s/3, s/3).
Detailed Description
Supplies a 'constant heat flux' to a cuboidal region (specified by two corner points) by adding a random velocity at each time step to each particle therein, increasing the granular temperature (velocity variance).
Constructor & Destructor Documentation
HeaterBoundary() [1/2]
HeaterBoundary::HeaterBoundary ()
                                : BaseBoundary()
 {
     posMin_ = Vec3D(0, 0, 0);
     posMax_ = Vec3D(0, 0, 0);
     specificHeatStrength_ = Vec3D(0, 0, 0);
 }
References posMax_, posMin_, and specificHeatStrength_.
Referenced by copy().
HeaterBoundary() [2/2]
HeaterBoundary::HeaterBoundary (const HeaterBoundary & other)
                                                           : BaseBoundary(other)
 {
     posMin_ = other.posMin_;
     posMax_ = other.posMax_;
     specificHeatStrength_ = other.specificHeatStrength_;
 }
References posMax_, posMin_, and specificHeatStrength_.
~HeaterBoundary()
HeaterBoundary::~HeaterBoundary () override
 {
     logger(VERBOSE, "A HeaterBoundary has been destroyed.");
 }
References logger, and VERBOSE.
Member Function Documentation
checkBoundaryAfterParticleMoved()
bool HeaterBoundary::checkBoundaryAfterParticleMoved (BaseParticle * p, ParticleHandler & pH)
Checks if a given particle is inside the HeaterBoundary. If so, heats it.
Todo:
JMFT: Make a 2D version of this
 {
     if (!(p->isFixed()) && (getDistance(p->getPosition()) < 0))
     {
         // fprintf(stderr, "heating a particle\n");
         // Mdouble noise = heatStrength_ / p->getMass() * pow(pH.getDPMBase()->getTimeStep(),0.5) ;
         // We need a factor of sqrt(3) in front because we are generating random
         // numbers using a uniformly distributed random variable, not a normal one.
         Mdouble noiseX = sqrt(2. * pH.getDPMBase()->getTimeStep() * specificHeatStrength_.X);
         Mdouble noiseY = sqrt(2. * pH.getDPMBase()->getTimeStep() * specificHeatStrength_.Y);
         Mdouble noiseZ = sqrt(2. * pH.getDPMBase()->getTimeStep() * specificHeatStrength_.Z);
         Vec3D brownianMotion = Vec3D(
                 noiseX * pH.getDPMBase()->random.getRandomNumber(-1, 1),
                 noiseY * pH.getDPMBase()->random.getRandomNumber(-1, 1),
                 noiseZ * pH.getDPMBase()->random.getRandomNumber(-1, 1));
         p->setVelocity(p->getVelocity() + brownianMotion);
     }
     return true;
 }
References getDistance(), BaseHandler< T >::getDPMBase(), RNG::getRandomNumber(), DPMBase::getTimeStep(), p, DPMBase::random, specificHeatStrength_, sqrt(), Vec3D::X, Vec3D::Y, and Vec3D::Z.
Referenced by checkBoundaryAfterParticlesMove().
checkBoundaryAfterParticlesMove()
void HeaterBoundary::checkBoundaryAfterParticlesMove (ParticleHandler & pH) override virtual
Runs at the end of each time step.
Reimplemented from BaseBoundary.
 {
     for (auto p = pH.begin(); p != pH.end(); ++p)
         checkBoundaryAfterParticleMoved(*p, pH);
 }
References BaseHandler< T >::begin(), checkBoundaryAfterParticleMoved(), BaseHandler< T >::end(), and p.
copy()
HeaterBoundary * HeaterBoundary::copy () const override virtual
Used to create a copy of the object NB: purely virtual function.
Implements BaseBoundary.
 {
     return new HeaterBoundary(*this);
 }
References HeaterBoundary().
getDistance()
Mdouble HeaterBoundary::getDistance (const Vec3D & position) const
Returns a negative value if and only if the position is inside the boundary (and therefore the particle to be heated).
Todo:
JMFT: Calculate the distance properly, not just 1 or -1.
 {
     // std::cerr << "Checking a particle position " << position << " against " << posMin_ << " and " << posMax_ << std::endl;
     if (posMin_.X <= position.X && position.X <= posMax_.X
         && posMin_.Y <= position.Y && position.Y <= posMax_.Y
         && posMin_.Z <= position.Z && position.Z <= posMax_.Z
             )
     {
         // std::cerr << "Yes\n";
         return -1;
     }
     else
     {
         // std::cerr << "No\n";
         return 1;
     }
 }
References posMax_, posMin_, Vec3D::X, Vec3D::Y, and Vec3D::Z.
Referenced by checkBoundaryAfterParticleMoved().
getName()
std::string HeaterBoundary::getName () const override virtual
Returns the object's class name (i.e. 'HeaterBoundary').
Returns
the object's class name
Implements BaseObject.
 {
     return "HeaterBoundary";
 }
getVolume()
Mdouble HeaterBoundary::getVolume () const inline
Returns the volume of the HeaterBoundary cuboid.
 {
     return ((posMax_.X - posMin_.X) * (posMax_.Y - posMin_.Y) * (posMax_.Z - posMin_.Z));
 }
References posMax_, posMin_, Vec3D::X, Vec3D::Y, and Vec3D::Z.
read()
void HeaterBoundary::read (std::istream & is) override virtual
Reads some boundary properties from an std::istream.
Reads a number of boundary properties from the given std::istream.
Parameters
[in,out] is the istream
Implements BaseBoundary.
 {
     BaseBoundary::read(is);
     std::string dummy;
     is >> dummy >> posMin_
        >> dummy >> posMax_
        >> dummy >> specificHeatStrength_;
 }
References posMax_, posMin_, BaseBoundary::read(), specificHeatStrength_, and oomph::Global_string_for_annotation::string().
set()
void HeaterBoundary::set (Vec3D posMin, Vec3D posMax, Vec3D specificHeatStrength)
 {
     posMin_ = posMin;
     posMax_ = posMax;
     setStrength(specificHeatStrength);
 }
References posMax_, posMin_, and setStrength().
set2D()
void HeaterBoundary::set2D (Vec3D posMin, Vec3D posMax, Mdouble specificHeatStrength)
 {
     posMin_ = posMin;
     posMax_ = posMax;
     setStrength2D(specificHeatStrength);
 }
References posMax_, posMin_, and setStrength2D().
set3D()
void HeaterBoundary::set3D (Vec3D posMin, Vec3D posMax, Mdouble specificHeatStrength)
 {
     posMin_ = posMin;
     posMax_ = posMax;
     setStrength3D(specificHeatStrength);
 }
References posMax_, posMin_, and setStrength3D().
Referenced by HeaterBoundaryTest::setupInitialConditions().
setStrength()
void HeaterBoundary::setStrength (Vec3D specificHeatStrength)
 {
     specificHeatStrength_ = specificHeatStrength;
 }
References specificHeatStrength_.
Referenced by set().
setStrength2D()
void HeaterBoundary::setStrength2D (Mdouble specificHeatStrength)
 {
     specificHeatStrength_.X = specificHeatStrength / sqrt(2.);
     specificHeatStrength_.Y = specificHeatStrength / sqrt(2.);
     specificHeatStrength_.Z = 0;
 }
References specificHeatStrength_, sqrt(), Vec3D::X, Vec3D::Y, and Vec3D::Z.
Referenced by set2D().
setStrength3D()
void HeaterBoundary::setStrength3D (Mdouble specificHeatStrength)
 {
     specificHeatStrength_.X = specificHeatStrength / sqrt(3.);
     specificHeatStrength_.Y = specificHeatStrength / sqrt(3.);
     specificHeatStrength_.Z = specificHeatStrength / sqrt(3.);
 }
References specificHeatStrength_, sqrt(), Vec3D::X, Vec3D::Y, and Vec3D::Z.
Referenced by set3D().
write()
void HeaterBoundary::write (std::ostream & os) const override virtual
Writes the boundary properties to an std::ostream.
Writes the boundary properties to an std::ostream.
Parameters
[out] os the ostream the properties are to be written to.
Implements BaseBoundary.
 {
     BaseBoundary::write(os);
     os << " posMin " << posMin_
        << " posMax " << posMax_
        << " specificHeatStrength " << specificHeatStrength_;
 }
References posMax_, posMin_, specificHeatStrength_, and BaseBoundary::write().
Member Data Documentation
posMax_
Vec3D HeaterBoundary::posMax_ private
Referenced by getDistance(), getVolume(), HeaterBoundary(), read(), set(), set2D(), set3D(), and write().
posMin_
Vec3D HeaterBoundary::posMin_ private
Referenced by getDistance(), getVolume(), HeaterBoundary(), read(), set(), set2D(), set3D(), and write().
specificHeatStrength_
Vec3D HeaterBoundary::specificHeatStrength_ private
The specific heat strengths have units of energy (mass)^{-1} (time)^{-1) = m^2 s^{-3} For isotropic heating, take a vector proportional to (s/3, s/3, s/3).
Referenced by checkBoundaryAfterParticleMoved(), HeaterBoundary(), read(), setStrength(), setStrength2D(), setStrength3D(), and write().
The documentation for this class was generated from the following files:
HeaterBoundary.h
HeaterBoundary.cc