MercuryDPM: Eigen::TensorEvaluator< const TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device > Struct Template Reference
Eigen::TensorEvaluator< const TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device > Struct Template Reference
#include <TensorConcatenation.h>
Public Types
enum {
IsAligned = false , PacketAccess , BlockAccess = false , PreferBlockAccess ,
RawAccess = false
}
typedef TensorConcatenationOp< Axis, LeftArgType, RightArgType > XprType
typedef XprType::Index Index
typedef DSizes< Index, NumDims > Dimensions
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef StorageMemory< CoeffReturnType, Device > Storage
typedef Storage::Type EvaluatorPointerType
typedef internal::TensorBlockNotImplemented TensorBlock
Public Member Functions
EIGEN_STRONG_INLINE TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions & dimensions () const
EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (EvaluatorPointerType)
EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType packet (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
EIGEN_DEVICE_FUNC EvaluatorPointerType data () const
Static Public Attributes
static constexpr int NumDims = internal::array_size<typename TensorEvaluator<LeftArgType, Device>::Dimensions>::value
static constexpr int RightNumDims
static constexpr int Layout = TensorEvaluator<LeftArgType, Device>::Layout
Protected Attributes
Dimensions m_dimensions
array< Index, NumDims > m_outputStrides
array< Index, NumDims > m_leftStrides
array< Index, NumDims > m_rightStrides
TensorEvaluator< LeftArgType, Device > m_leftImpl
TensorEvaluator< RightArgType, Device > m_rightImpl
const Axis m_axis
Member Typedef Documentation
CoeffReturnType
template<typename Axis , typename LeftArgType , typename RightArgType , typename Device > typedef XprType::CoeffReturnType Eigen::TensorEvaluator< const TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device >::CoeffReturnType
Dimensions
template<typename Axis , typename LeftArgType , typename RightArgType , typename Device > typedef DSizes<Index, NumDims> Eigen::TensorEvaluator< const TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device >::Dimensions
EvaluatorPointerType
template<typename Axis , typename LeftArgType , typename RightArgType , typename Device > typedef Storage::Type Eigen::TensorEvaluator< const TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device >::EvaluatorPointerType
Index
template<typename Axis , typename LeftArgType , typename RightArgType , typename Device > typedef XprType::Index Eigen::TensorEvaluator< const TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device >::Index
PacketReturnType
template<typename Axis , typename LeftArgType , typename RightArgType , typename Device > typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorEvaluator< const TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device >::PacketReturnType
Scalar
template<typename Axis , typename LeftArgType , typename RightArgType , typename Device > typedef XprType::Scalar Eigen::TensorEvaluator< const TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device >::Scalar
Storage
template<typename Axis , typename LeftArgType , typename RightArgType , typename Device > typedef StorageMemory<CoeffReturnType, Device> Eigen::TensorEvaluator< const TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device >::Storage
TensorBlock
template<typename Axis , typename LeftArgType , typename RightArgType , typename Device > typedef internal::TensorBlockNotImplemented Eigen::TensorEvaluator< const TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device >::TensorBlock
XprType
template<typename Axis , typename LeftArgType , typename RightArgType , typename Device > typedef TensorConcatenationOp<Axis, LeftArgType, RightArgType> Eigen::TensorEvaluator< const TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device >::XprType
Member Enumeration Documentation
anonymous enum
template<typename Axis , typename LeftArgType , typename RightArgType , typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
BlockAccess
PreferBlockAccess
RawAccess
        {
     IsAligned = false,
     PacketAccess =
         TensorEvaluator<LeftArgType, Device>::PacketAccess && TensorEvaluator<RightArgType, Device>::PacketAccess,
     BlockAccess = false,
     PreferBlockAccess = TensorEvaluator<LeftArgType, Device>::PreferBlockAccess ||
                         TensorEvaluator<RightArgType, Device>::PreferBlockAccess,
     RawAccess = false
   };
Constructor & Destructor Documentation
TensorEvaluator()
template<typename Axis , typename LeftArgType , typename RightArgType , typename Device > EIGEN_STRONG_INLINE Eigen::TensorEvaluator< const TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device >::TensorEvaluator (const XprType & op, const Device & device) inline
       : m_leftImpl(op.lhsExpression(), device), m_rightImpl(op.rhsExpression(), device), m_axis(op.axis()) {
     EIGEN_STATIC_ASSERT((static_cast<int>(TensorEvaluator<LeftArgType, Device>::Layout) ==
                              static_cast<int>(TensorEvaluator<RightArgType, Device>::Layout) ||
                          NumDims == 1),
                         YOU_MADE_A_PROGRAMMING_MISTAKE);
     EIGEN_STATIC_ASSERT((NumDims == RightNumDims), YOU_MADE_A_PROGRAMMING_MISTAKE);
     EIGEN_STATIC_ASSERT((NumDims > 0), YOU_MADE_A_PROGRAMMING_MISTAKE);
     eigen_assert(0 <= m_axis && m_axis < NumDims);
     const Dimensions& lhs_dims = m_leftImpl.dimensions();
     const Dimensions& rhs_dims = m_rightImpl.dimensions();
     {
       int i = 0;
       for (; i < m_axis; ++i) {
         eigen_assert(lhs_dims[i] > 0);
         eigen_assert(lhs_dims[i] == rhs_dims[i]);
         m_dimensions[i] = lhs_dims[i];
       }
       eigen_assert(lhs_dims[i] > 0);  // Now i == m_axis.
       eigen_assert(rhs_dims[i] > 0);
       m_dimensions[i] = lhs_dims[i] + rhs_dims[i];
       for (++i; i < NumDims; ++i) {
         eigen_assert(lhs_dims[i] > 0);
         eigen_assert(lhs_dims[i] == rhs_dims[i]);
         m_dimensions[i] = lhs_dims[i];
       }
     }
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       m_leftStrides[0] = 1;
       m_rightStrides[0] = 1;
       m_outputStrides[0] = 1;
       for (int j = 1; j < NumDims; ++j) {
         m_leftStrides[j] = m_leftStrides[j - 1] * lhs_dims[j - 1];
         m_rightStrides[j] = m_rightStrides[j - 1] * rhs_dims[j - 1];
         m_outputStrides[j] = m_outputStrides[j - 1] * m_dimensions[j - 1];
       }
     } else {
       m_leftStrides[NumDims - 1] = 1;
       m_rightStrides[NumDims - 1] = 1;
       m_outputStrides[NumDims - 1] = 1;
       for (int j = NumDims - 2; j >= 0; --j) {
         m_leftStrides[j] = m_leftStrides[j + 1] * lhs_dims[j + 1];
         m_rightStrides[j] = m_rightStrides[j + 1] * rhs_dims[j + 1];
         m_outputStrides[j] = m_outputStrides[j + 1] * m_dimensions[j + 1];
       }
     }
   }
References Eigen::ColMajor, eigen_assert, EIGEN_STATIC_ASSERT, i, j, and Eigen::TensorEvaluator< Derived, Device >::Layout.
Member Function Documentation
cleanup()
template<typename Axis , typename LeftArgType , typename RightArgType , typename Device > EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device >::cleanup () inline
{
     m_leftImpl.cleanup();
     m_rightImpl.cleanup();
   }
Referenced by framework.Frame::__init__().
coeff()
template<typename Axis , typename LeftArgType , typename RightArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::TensorEvaluator< const TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device >::coeff (Index index) const inline
{
     // Collect dimension-wise indices (subs).
     array<Index, NumDims> subs;
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       for (int i = NumDims - 1; i > 0; --i) {
         subs[i] = index / m_outputStrides[i];
         index -= subs[i] * m_outputStrides[i];
       }
       subs[0] = index;
     } else {
       for (int i = 0; i < NumDims - 1; ++i) {
         subs[i] = index / m_outputStrides[i];
         index -= subs[i] * m_outputStrides[i];
       }
       subs[NumDims - 1] = index;
     }
     const Dimensions& left_dims = m_leftImpl.dimensions();
     if (subs[m_axis] < left_dims[m_axis]) {
       Index left_index;
       if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
         left_index = subs[0];
         EIGEN_UNROLL_LOOP
         for (int i = 1; i < NumDims; ++i) {
           left_index += (subs[i] % left_dims[i]) * m_leftStrides[i];
         }
       } else {
         left_index = subs[NumDims - 1];
         EIGEN_UNROLL_LOOP
         for (int i = NumDims - 2; i >= 0; --i) {
           left_index += (subs[i] % left_dims[i]) * m_leftStrides[i];
         }
       }
       return m_leftImpl.coeff(left_index);
     } else {
       subs[m_axis] -= left_dims[m_axis];
       const Dimensions& right_dims = m_rightImpl.dimensions();
       Index right_index;
       if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
         right_index = subs[0];
         EIGEN_UNROLL_LOOP
         for (int i = 1; i < NumDims; ++i) {
           right_index += (subs[i] % right_dims[i]) * m_rightStrides[i];
         }
       } else {
         right_index = subs[NumDims - 1];
         EIGEN_UNROLL_LOOP
         for (int i = NumDims - 2; i >= 0; --i) {
           right_index += (subs[i] % right_dims[i]) * m_rightStrides[i];
         }
       }
       return m_rightImpl.coeff(right_index);
     }
   }
References Eigen::ColMajor, EIGEN_UNROLL_LOOP, i, and Eigen::TensorEvaluator< Derived, Device >::Layout.
costPerCoeff()
template<typename Axis , typename LeftArgType , typename RightArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorEvaluator< const TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device >::costPerCoeff (bool vectorized) const inline
{
     const double compute_cost = NumDims * (2 * TensorOpCost::AddCost<Index>() + 2 * TensorOpCost::MulCost<Index>() +
                                            TensorOpCost::DivCost<Index>() + TensorOpCost::ModCost<Index>());
     const double lhs_size = m_leftImpl.dimensions().TotalSize();
     const double rhs_size = m_rightImpl.dimensions().TotalSize();
     return (lhs_size / (lhs_size + rhs_size)) * m_leftImpl.costPerCoeff(vectorized) +
            (rhs_size / (lhs_size + rhs_size)) * m_rightImpl.costPerCoeff(vectorized) + TensorOpCost(0, 0, compute_cost);
   }
data()
template<typename Axis , typename LeftArgType , typename RightArgType , typename Device > EIGEN_DEVICE_FUNC EvaluatorPointerType Eigen::TensorEvaluator< const TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device >::data () const inline
 { return NULL; }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
dimensions()
template<typename Axis , typename LeftArgType , typename RightArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions& Eigen::TensorEvaluator< const TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device >::dimensions () const inline
 { return m_dimensions; }
evalSubExprsIfNeeded()
template<typename Axis , typename LeftArgType , typename RightArgType , typename Device > EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device >::evalSubExprsIfNeeded (EvaluatorPointerType) inline
{
     m_leftImpl.evalSubExprsIfNeeded(NULL);
     m_rightImpl.evalSubExprsIfNeeded(NULL);
     return true;
   }
packet()
template<typename Axis , typename LeftArgType , typename RightArgType , typename Device > template<int LoadMode> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType Eigen::TensorEvaluator< const TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device >::packet (Index index) const inline
{
     const int packetSize = PacketType<CoeffReturnType, Device>::size;
     EIGEN_STATIC_ASSERT((packetSize > 1), YOU_MADE_A_PROGRAMMING_MISTAKE)
     eigen_assert(index + packetSize - 1 < dimensions().TotalSize());
     EIGEN_ALIGN_MAX CoeffReturnType values[packetSize];
     EIGEN_UNROLL_LOOP
     for (int i = 0; i < packetSize; ++i) {
       values[i] = coeff(index + i);
     }
     PacketReturnType rslt = internal::pload<PacketReturnType>(values);
     return rslt;
   }
References Eigen::TensorEvaluator< Derived, Device >::coeff(), Eigen::TensorEvaluator< Derived, Device >::dimensions(), EIGEN_ALIGN_MAX, eigen_assert, EIGEN_STATIC_ASSERT, EIGEN_UNROLL_LOOP, and i.
Member Data Documentation
Layout
template<typename Axis , typename LeftArgType , typename RightArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device >::Layout = TensorEvaluator<LeftArgType, Device>::Layout static constexpr
m_axis
template<typename Axis , typename LeftArgType , typename RightArgType , typename Device > const Axis Eigen::TensorEvaluator< const TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device >::m_axis protected
m_dimensions
template<typename Axis , typename LeftArgType , typename RightArgType , typename Device > Dimensions Eigen::TensorEvaluator< const TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device >::m_dimensions protected
m_leftImpl
template<typename Axis , typename LeftArgType , typename RightArgType , typename Device > TensorEvaluator<LeftArgType, Device> Eigen::TensorEvaluator< const TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device >::m_leftImpl protected
m_leftStrides
template<typename Axis , typename LeftArgType , typename RightArgType , typename Device > array<Index, NumDims> Eigen::TensorEvaluator< const TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device >::m_leftStrides protected
m_outputStrides
template<typename Axis , typename LeftArgType , typename RightArgType , typename Device > array<Index, NumDims> Eigen::TensorEvaluator< const TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device >::m_outputStrides protected
m_rightImpl
template<typename Axis , typename LeftArgType , typename RightArgType , typename Device > TensorEvaluator<RightArgType, Device> Eigen::TensorEvaluator< const TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device >::m_rightImpl protected
m_rightStrides
template<typename Axis , typename LeftArgType , typename RightArgType , typename Device > array<Index, NumDims> Eigen::TensorEvaluator< const TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device >::m_rightStrides protected
NumDims
template<typename Axis , typename LeftArgType , typename RightArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device >::NumDims = internal::array_size<typename TensorEvaluator<LeftArgType, Device>::Dimensions>::value static constexpr
RightNumDims
template<typename Axis , typename LeftArgType , typename RightArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorConcatenationOp< Axis, LeftArgType, RightArgType >, Device >::RightNumDims static constexpr
Initial value:
=
      internal::array_size<typename TensorEvaluator<RightArgType, Device>::Dimensions>::value
The documentation for this struct was generated from the following file:
TensorConcatenation.h