MercuryDPM: Eigen::internal::generic_i0e< T, float > Struct Template Reference
Eigen::internal::generic_i0e< T, float > Struct Template Reference
#include <BesselFunctionsImpl.h>
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T run (const T &x)
Member Function Documentation
run()
template<typename T > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T Eigen::internal::generic_i0e< T, float >::run (const T & x) inline static
{
     /*  i0ef.c
      *
      *  Modified Bessel function of order zero,
      *  exponentially scaled
      *
      *
      *
      * SYNOPSIS:
      *
      * float x, y, i0ef();
      *
      * y = i0ef( x );
      *
      *
      *
      * DESCRIPTION:
      *
      * Returns exponentially scaled modified Bessel function
      * of order zero of the argument.
      *
      * The function is defined as i0e(x) = exp(-|x|) j0( ix ).
      *
      *
      *
      * ACCURACY:
      *
      *                      Relative error:
      * arithmetic   domain     # trials      peak         rms
      *    IEEE      0,30        100000      3.7e-7      7.0e-8
      * See i0f().
      *
      */
     const float A[] = {-1.30002500998624804212E-8f, 6.04699502254191894932E-8f,  -2.67079385394061173391E-7f,
                        1.11738753912010371815E-6f,  -4.41673835845875056359E-6f, 1.64484480707288970893E-5f,
                        -5.75419501008210370398E-5f, 1.88502885095841655729E-4f,  -5.76375574538582365885E-4f,
                        1.63947561694133579842E-3f,  -4.32430999505057594430E-3f, 1.05464603945949983183E-2f,
                        -2.37374148058994688156E-2f, 4.93052842396707084878E-2f,  -9.49010970480476444210E-2f,
                        1.71620901522208775349E-1f,  -3.04682672343198398683E-1f, 6.76795274409476084995E-1f};
     const float B[] = {3.39623202570838634515E-9f, 2.26666899049817806459E-8f, 2.04891858946906374183E-7f,
                        2.89137052083475648297E-6f, 6.88975834691682398426E-5f, 3.36911647825569408990E-3f,
                        8.04490411014108831608E-1f};
     T y = pabs(x);
     T y_le_eight = internal::pchebevl<T, 18>::run(pmadd(pset1<T>(0.5f), y, pset1<T>(-2.0f)), A);
     T y_gt_eight = pmul(internal::pchebevl<T, 7>::run(psub(pdiv(pset1<T>(32.0f), y), pset1<T>(2.0f)), B), prsqrt(y));
     // TODO: Perhaps instead check whether all packet elements are in
     // [-8, 8] and evaluate a branch based off of that. It's possible
     // in practice most elements are in this region.
     return pselect(pcmp_le(y, pset1<T>(8.0f)), y_le_eight, y_gt_eight);
   }
References Eigen::internal::pabs(), Eigen::internal::pcmp_le(), Eigen::internal::pdiv(), Eigen::internal::pmadd(), Eigen::internal::pmul(), Eigen::internal::prsqrt(), Eigen::internal::pselect(), Eigen::internal::psub(), Eigen::internal::pchebevl< Packet, N >::run(), plotDoE::x, and Eigen::internal::y.
The documentation for this struct was generated from the following file:
BesselFunctionsImpl.h