MercuryDPM: Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased > Struct Template Reference
Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased > Struct Template Reference
#include <CoreEvaluators.h>
Public Types
enum { CoeffReadCost = evaluator<ArgType>::CoeffReadCost , Flags = evaluator<ArgType>::Flags ^ RowMajorBit , Alignment = evaluator<ArgType>::Alignment }
typedef Transpose< ArgType > XprType
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
Public Types inherited from Eigen::internal::evaluator_base< Transpose< ArgType > >
enum
typedef traits< Transpose< ArgType > > ExpressionTraits
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE unary_evaluator (const XprType &t)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index row, Index col)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE XprType::Scalar & coeffRef (Index index)
template<int LoadMode, typename PacketType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType packet (Index row, Index col) const
template<int LoadMode, typename PacketType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType packet (Index index) const
template<int StoreMode, typename PacketType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void writePacket (Index row, Index col, const PacketType &x)
template<int StoreMode, typename PacketType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void writePacket (Index index, const PacketType &x)
Public Member Functions inherited from Eigen::internal::evaluator_base< Transpose< ArgType > >
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE evaluator_base ()=default
Protected Attributes
evaluator< ArgType > m_argImpl
Member Typedef Documentation
CoeffReturnType
template<typename ArgType > typedef XprType::CoeffReturnType Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::CoeffReturnType
Scalar
template<typename ArgType > typedef XprType::Scalar Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::Scalar
XprType
template<typename ArgType > typedef Transpose<ArgType> Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::XprType
Member Enumeration Documentation
anonymous enum
template<typename ArgType > anonymous enum
Enumerator
CoeffReadCost
Flags
Alignment
        {
     CoeffReadCost = evaluator<ArgType>::CoeffReadCost,
     Flags = evaluator<ArgType>::Flags ^ RowMajorBit,
     Alignment = evaluator<ArgType>::Alignment
   };
Constructor & Destructor Documentation
unary_evaluator()
template<typename ArgType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::unary_evaluator (const XprType & t) inline explicit
 : m_argImpl(t.nestedExpression()) {}
Member Function Documentation
coeff() [1/2]
template<typename ArgType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::coeff (Index index) const inline
 { return m_argImpl.coeff(index); }
coeff() [2/2]
template<typename ArgType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::coeff (Index row, Index col) const inline
{
     return m_argImpl.coeff(col, row);
   }
References col(), and row().
coeffRef() [1/2]
template<typename ArgType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE XprType::Scalar& Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::coeffRef (Index index) inline
{
     return m_argImpl.coeffRef(index);
   }
coeffRef() [2/2]
template<typename ArgType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::coeffRef (Index row, Index col) inline
 { return m_argImpl.coeffRef(col, row); }
References col(), and row().
packet() [1/2]
template<typename ArgType > template<int LoadMode, typename PacketType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::packet (Index index) const inline
{
     return m_argImpl.template packet<LoadMode, PacketType>(index);
   }
packet() [2/2]
template<typename ArgType > template<int LoadMode, typename PacketType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::packet (Index row, Index col) const inline
{
     return m_argImpl.template packet<LoadMode, PacketType>(col, row);
   }
References col(), and row().
writePacket() [1/2]
template<typename ArgType > template<int StoreMode, typename PacketType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::writePacket (Index index, const PacketType & x) inline
{
     m_argImpl.template writePacket<StoreMode, PacketType>(index, x);
   }
References plotDoE::x.
writePacket() [2/2]
template<typename ArgType > template<int StoreMode, typename PacketType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::writePacket (Index row, Index col, const PacketType & x) inline
{
     m_argImpl.template writePacket<StoreMode, PacketType>(col, row, x);
   }
References col(), row(), and plotDoE::x.
Member Data Documentation
m_argImpl
template<typename ArgType > evaluator<ArgType> Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::m_argImpl protected
The documentation for this struct was generated from the following file:
CoreEvaluators.h