MercuryDPM: StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT > Class Template Reference
StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT > Class Template Reference
Public Member Functions
StabilityProblem (const unsigned &base_n_r, const unsigned &base_n_z, const unsigned &perturbed_n_r, const unsigned &perturbed_n_z, const double &domain_height)
Constructor: Build base and perturbed state problems.
~StabilityProblem ()
Destructor (empty)
void set_initial_condition ()
Set initial conditions.
void unsteady_run (const double &dt, const unsigned &n_timesteps, DocInfo &doc_info)
Integrate forwards in time with timestep dt for n_timesteps.
unsigned perform_power_method (const double &dt, const unsigned &n_timesteps, DocInfo &doc_info, const double &tolerance, const unsigned &max_iter, double &calc_eigenvalue, DoubleVector &input)
BaseStateProblem< BASE_ELEMENT > * base_state_problem_pt () const
Access function for base state problem.
PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT > * perturbed_state_problem_pt () const
Access function for perturbed state problem.
StabilityProblem (const unsigned &base_n_r, const unsigned &base_n_z, const unsigned &perturbed_n_r, const unsigned &perturbed_n_z, const double &domain_height)
Constructor: Build base and perturbed state problems.
~StabilityProblem ()
Destructor (empty)
void set_initial_condition ()
Set initial conditions.
void unsteady_run (const double &dt, const unsigned &n_timesteps, DocInfo &doc_info)
Integrate forwards in time with timestep dt for n_timesteps.
unsigned perform_power_method (const double &dt, const unsigned &n_timesteps, DocInfo &doc_info, const double &tolerance, const unsigned &max_iter, double &calc_eigenvalue, DoubleVector &input)
BaseStateProblem< BASE_ELEMENT > * base_state_problem_pt () const
Access function for base state problem.
PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT > * perturbed_state_problem_pt () const
Access function for perturbed state problem.
StabilityProblem (const unsigned &base_n_r, const unsigned &base_n_z, const unsigned &perturbed_n_r, const unsigned &perturbed_n_z, const double &domain_height)
Constructor: Build base and perturbed state problems.
~StabilityProblem ()
Destructor (empty)
void create_trace_files (DocInfo &doc_info)
Create trace files.
void initialise_trace_files ()
Initialise trace files (creates column headings)
void close_trace_files ()
Clear and close trace files.
void initialise_dt (const double &dt)
Initialise timestep (single dt version)
void initialise_dt (const Vector< double > &dt)
Initialise timestep (vector of dts version)
void set_initial_condition ()
Set initial conditions.
void doc_solution (DocInfo &doc_info, const bool &output_base_soln, const bool &output_perturbed_soln)
Document base and perturbed state solutions.
void pass_updated_nondim_parameters_to_elements ()
unsigned perform_power_method (const double &dt, DocInfo &doc_info, const double &tolerance, const unsigned &max_iter, double &calc_eigenvalue, DoubleVector &input)
void base_flow_steady_newton_solve ()
void get_perturbed_state_problem_dofs (DoubleVector &d)
Get perturbed state dofs.
void reset_global_time_to_zero ()
(Re-)set the global time in both problems to zero
BaseStateProblem< BASE_ELEMENT > * base_state_problem_pt () const
Access function for base state problem.
PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT > * perturbed_state_problem_pt () const
Access function for perturbed state problem.
StabilityProblem (const unsigned &base_n_r, const unsigned &base_n_z, const unsigned &perturbed_n_r, const unsigned &perturbed_n_z, const double &domain_height)
Constructor: Build base and perturbed state problems.
~StabilityProblem ()
Destructor (empty)
void create_trace_files (DocInfo &doc_info)
Create trace files.
void initialise_trace_files ()
Initialise trace files (creates column headings)
void close_trace_files ()
Clear and close trace files.
void initialise_dt (const double &dt)
Initialise timestep (single dt version)
void initialise_dt (const Vector< double > &dt)
Initialise timestep (vector of dts version)
void set_initial_condition ()
Set initial conditions.
void doc_solution (DocInfo &doc_info, const bool &output_base_soln, const bool &output_perturbed_soln)
Document base and perturbed state solutions.
void pass_updated_nondim_parameters_to_elements ()
unsigned perform_power_method (const double &dt, DocInfo &doc_info, const double &tolerance, const unsigned &max_iter, double &calc_eigenvalue, DoubleVector &input)
void base_flow_steady_newton_solve ()
void get_perturbed_state_problem_dofs (DoubleVector &d)
Get perturbed state dofs.
void reset_global_time_to_zero ()
(Re-)set the global time in both problems to zero
BaseStateProblem< BASE_ELEMENT > * base_state_problem_pt () const
Access function for base state problem.
PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT > * perturbed_state_problem_pt () const
Access function for perturbed state problem.
StabilityProblem (const unsigned &base_n_r, const unsigned &base_n_z, const unsigned &perturbed_n_r, const unsigned &perturbed_n_z, const double &radius_inner_cylinder, const double &radius_outer_cylinder, const double &l_z)
Constructor: Build base and perturbed state problems.
~StabilityProblem ()
Destructor (empty)
void create_trace_files (DocInfo &doc_info)
Create trace files.
void initialise_trace_files ()
Initialise trace files (creates column headings)
void close_trace_files ()
Clear and close trace files.
void initialise_dt (const double &dt)
Initialise timestep (single dt version)
void initialise_dt (const Vector< double > &dt)
Initialise timestep (vector of dts version)
void set_initial_condition ()
Set initial conditions.
void doc_solution (DocInfo &doc_info, const bool &output_base_soln, const bool &output_perturbed_soln)
Document base and perturbed state solutions.
void unsteady_run (const double &dt, const unsigned &n_timesteps, DocInfo &doc_info, const bool &output_base_soln, Vector< DoubleVector > &perturbed_state_dofs_over_period, Vector< DoubleVector > &base_state_dofs_over_period)
Integrate forwards in time with timestep dt for n_timesteps.
void unsteady_run_for_power_method (const double &dt, const unsigned &n_timesteps, DocInfo &doc_info, const DoubleVector &input_perturbed_state_dofs, DoubleVector &output_perturbed_state_dofs, const bool &output_base_soln, Vector< DoubleVector > &perturbed_state_dofs_over_period, Vector< DoubleVector > &base_state_dofs_over_period)
unsigned set_up_periodic_base_flow (const double &dt, const unsigned &n_timesteps, DocInfo &doc_info, const double &tolerance)
unsigned perform_power_method (const double &dt, const unsigned &n_timesteps, DocInfo &doc_info, const double &tolerance, const unsigned &max_iter, double &calc_eigenvalue, DoubleVector &input, Vector< DoubleVector > &base_state_dofs_over_period)
void get_perturbed_state_problem_dofs (DoubleVector &d)
Get perturbed state dofs.
void reset_global_time_to_zero ()
(Re-)set the global time in both problems to zero
const BaseStateProblem< BASE_ELEMENT > * base_state_problem_pt ()
Access function for base state problem.
const PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT > * perturbed_state_problem_pt ()
Access function for perturbed state problem.
void set_first_power_method_iteration_flag_to_true ()
Switch on flag.
void set_first_power_method_iteration_flag_to_false ()
Switch off flag.
Private Member Functions
void set_perturbed_state_time_equal_to_base_state_time ()
void set_perturbed_state_time_equal_to_base_state_time ()
void set_perturbed_state_time_equal_to_base_state_time ()
Private Attributes
BaseStateProblem< BASE_ELEMENT > * Base_state_problem_pt
Pointer to base state problem class.
PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT > * Perturbed_state_problem_pt
Pointer to perturbed state problem class.
ofstream Trace_file_periodic_base_flow
ofstream Trace_file_power_method
Trace file which documents the convergence of the power method.
bool First_power_method_iteration
Detailed Description
template<class BASE_ELEMENT, class PERTURBED_ELEMENT>
class StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >
////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////// Container class for the Tuckerman counter-rotating lids stability problem
////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////// Container class for the time-periodic Taylor–Couette stability problem
Constructor & Destructor Documentation
StabilityProblem() [1/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::StabilityProblem (const unsigned & base_n_r, const unsigned & base_n_z, const unsigned & perturbed_n_r, const unsigned & perturbed_n_z, const double & domain_height) inline
Constructor: Build base and perturbed state problems.
   {
    // Build base state problem
    Base_state_problem_pt = new BaseStateProblem<BASE_ELEMENT>
     (base_n_r,base_n_z,domain_height);
    // Build perturbed state problem
    Perturbed_state_problem_pt = new PerturbedStateProblem
     <BASE_ELEMENT,PERTURBED_ELEMENT>
     (perturbed_n_r,perturbed_n_z,domain_height,
      Base_state_problem_pt->mesh_pt());
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt, and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt.
~StabilityProblem() [1/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::~StabilityProblem () inline
Destructor (empty)
 {}
StabilityProblem() [2/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::StabilityProblem (const unsigned & base_n_r, const unsigned & base_n_z, const unsigned & perturbed_n_r, const unsigned & perturbed_n_z, const double & domain_height) inline
Constructor: Build base and perturbed state problems.
   {
    // Build base state problem
    Base_state_problem_pt = new BaseStateProblem<BASE_ELEMENT>
     (base_n_r,base_n_z,domain_height);
    // Build perturbed state problem
    Perturbed_state_problem_pt = new PerturbedStateProblem
     <BASE_ELEMENT,PERTURBED_ELEMENT>
     (perturbed_n_r,perturbed_n_z,domain_height,
      Base_state_problem_pt->mesh_pt());
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt, and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt.
~StabilityProblem() [2/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::~StabilityProblem () inline
Destructor (empty)
 {}
StabilityProblem() [3/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::StabilityProblem (const unsigned & base_n_r, const unsigned & base_n_z, const unsigned & perturbed_n_r, const unsigned & perturbed_n_z, const double & domain_height) inline
Constructor: Build base and perturbed state problems.
   {
    // Build base state problem
    Base_state_problem_pt = new BaseStateProblem<BASE_ELEMENT>
     (base_n_r,base_n_z,domain_height);
    // Build perturbed state problem
    Perturbed_state_problem_pt = new PerturbedStateProblem
     <BASE_ELEMENT,PERTURBED_ELEMENT>
     (perturbed_n_r,perturbed_n_z,domain_height,
      Base_state_problem_pt->mesh_pt());
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt, and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt.
~StabilityProblem() [3/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::~StabilityProblem () inline
Destructor (empty)
 {}
StabilityProblem() [4/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::StabilityProblem (const unsigned & base_n_r, const unsigned & base_n_z, const unsigned & perturbed_n_r, const unsigned & perturbed_n_z, const double & domain_height) inline
Constructor: Build base and perturbed state problems.
   {
    // Build base state problem
    Base_state_problem_pt = new BaseStateProblem<BASE_ELEMENT>
     (base_n_r,base_n_z,domain_height);
    // Build perturbed state problem
    Perturbed_state_problem_pt = new PerturbedStateProblem
     <BASE_ELEMENT,PERTURBED_ELEMENT>
     (perturbed_n_r,perturbed_n_z,domain_height,
      Base_state_problem_pt->mesh_pt());
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt, and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt.
~StabilityProblem() [4/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::~StabilityProblem () inline
Destructor (empty)
 {}
StabilityProblem() [5/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::StabilityProblem (const unsigned & base_n_r, const unsigned & base_n_z, const unsigned & perturbed_n_r, const unsigned & perturbed_n_z, const double & radius_inner_cylinder, const double & radius_outer_cylinder, const double & l_z) inline
Constructor: Build base and perturbed state problems.
   {
    // Build base state problem
    Base_state_problem_pt = new BaseStateProblem<BASE_ELEMENT>
     (base_n_r,base_n_z,radius_inner_cylinder,radius_outer_cylinder,l_z);
    // Build perturbed state problem
    Perturbed_state_problem_pt =
     new PerturbedStateProblem<BASE_ELEMENT,PERTURBED_ELEMENT>
     (perturbed_n_r,perturbed_n_z,radius_inner_cylinder,
      radius_outer_cylinder,l_z,Base_state_problem_pt->mesh_pt());
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt, and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt.
~StabilityProblem() [5/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::~StabilityProblem () inline
Destructor (empty)
 {}
Member Function Documentation
base_flow_steady_newton_solve() [1/2]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::base_flow_steady_newton_solve () inline
   {
    Base_state_problem_pt->set_boundary_conditions();
    Base_state_problem_pt->steady_newton_solve();
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt.
base_flow_steady_newton_solve() [2/2]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::base_flow_steady_newton_solve () inline
   {
    Base_state_problem_pt->set_boundary_conditions();
    Base_state_problem_pt->steady_newton_solve();
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt.
base_state_problem_pt() [1/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > const BaseStateProblem<BASE_ELEMENT>* StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::base_state_problem_pt () inline
Access function for base state problem.
   { return Base_state_problem_pt; }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt.
base_state_problem_pt() [2/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > BaseStateProblem<BASE_ELEMENT>* StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::base_state_problem_pt () const inline
Access function for base state problem.
 { return Base_state_problem_pt; }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt.
base_state_problem_pt() [3/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > BaseStateProblem<BASE_ELEMENT>* StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::base_state_problem_pt () const inline
Access function for base state problem.
 { return Base_state_problem_pt; }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt.
base_state_problem_pt() [4/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > BaseStateProblem<BASE_ELEMENT>* StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::base_state_problem_pt () const inline
Access function for base state problem.
 { return Base_state_problem_pt; }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt.
base_state_problem_pt() [5/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > BaseStateProblem<BASE_ELEMENT>* StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::base_state_problem_pt () const inline
Access function for base state problem.
 { return Base_state_problem_pt; }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt.
close_trace_files() [1/3]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::close_trace_files () inline
Clear and close trace files.
   {
    // Initialise base and perturbed state trace files
    Base_state_problem_pt->close_trace_file();
    Perturbed_state_problem_pt->close_trace_file();
    // Initialise stability problem trace files
    Trace_file_power_method.clear();
    Trace_file_power_method.close();
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt, StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt, and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Trace_file_power_method.
close_trace_files() [2/3]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::close_trace_files () inline
Clear and close trace files.
   {
    // Initialise base and perturbed state trace files
    Base_state_problem_pt->close_trace_file();
    Perturbed_state_problem_pt->close_trace_file();
    // Initialise stability problem trace files
    Trace_file_power_method.clear();
    Trace_file_power_method.close();
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt, StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt, and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Trace_file_power_method.
close_trace_files() [3/3]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::close_trace_files () inline
Clear and close trace files.
   {
    // Initialise base and perturbed state trace files
    Base_state_problem_pt->close_trace_file();
    Perturbed_state_problem_pt->close_trace_file();
    // Initialise stability problem trace files
    Trace_file_periodic_base_flow.clear();
    Trace_file_periodic_base_flow.close();
    Trace_file_power_method.clear();
    Trace_file_power_method.close();
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt, StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt, StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Trace_file_periodic_base_flow, and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Trace_file_power_method.
create_trace_files() [1/3]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::create_trace_files (DocInfo & doc_info) inline
Create trace files.
   {
    // Set up base and perturbed state trace files
    Base_state_problem_pt->create_trace_file(doc_info);
    Perturbed_state_problem_pt->create_trace_file(doc_info);
    // Set up stability problem trace files
    char filename[256];
    sprintf(filename,"%s/power_method_trace_k%i_Re%4.2f.dat",
            doc_info.directory().c_str(),
            GlobalPhysicalVariables::k,
            GlobalPhysicalVariables::Re_current);
    Trace_file_power_method.open(filename);
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt, oomph::DocInfo::directory(), MergeRestartFiles::filename, GlobalPhysicalVariables::k, StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt, GlobalPhysicalVariables::Re_current, and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Trace_file_power_method.
create_trace_files() [2/3]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::create_trace_files (DocInfo & doc_info) inline
Create trace files.
   {
    // Set up base and perturbed state trace files
    Base_state_problem_pt->create_trace_file(doc_info);
    Perturbed_state_problem_pt->create_trace_file(doc_info);
    // Set up stability problem trace files
    char filename[256];
    sprintf(filename,"%s/power_method_trace_k%i_Re%4.2f.dat",
            doc_info.directory().c_str(),
            GlobalPhysicalVariables::k,
            GlobalPhysicalVariables::Re_current);
    Trace_file_power_method.open(filename);
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt, oomph::DocInfo::directory(), MergeRestartFiles::filename, GlobalPhysicalVariables::k, StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt, GlobalPhysicalVariables::Re_current, and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Trace_file_power_method.
create_trace_files() [3/3]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::create_trace_files (DocInfo & doc_info) inline
Create trace files.
   {
    // Set up base and perturbed state trace files
    Base_state_problem_pt->create_trace_file(doc_info);
    Perturbed_state_problem_pt->create_trace_file(doc_info);
    // Set up stability problem trace files
    char filename[256];
    sprintf(filename,"%s/periodic_base_flow_trace_epsilon%2.1f_Re%4.2f.dat",
            doc_info.directory().c_str(),
            GlobalPhysicalVariables::Epsilon,
            GlobalPhysicalVariables::MMC_Re_current);
    Trace_file_periodic_base_flow.open(filename);
    sprintf(filename,"%s/power_method_trace_epsilon%2.1f_Re%4.2f.dat",
            doc_info.directory().c_str(),
            GlobalPhysicalVariables::Epsilon,
            GlobalPhysicalVariables::MMC_Re_current);
    Trace_file_power_method.open(filename);
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt, oomph::DocInfo::directory(), GlobalPhysicalVariables::Epsilon, MergeRestartFiles::filename, GlobalPhysicalVariables::MMC_Re_current, StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt, StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Trace_file_periodic_base_flow, and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Trace_file_power_method.
doc_solution() [1/3]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::doc_solution (DocInfo & doc_info, const bool & output_base_soln, const bool & output_perturbed_soln) inline
Document base and perturbed state solutions.
   {
    Base_state_problem_pt->doc_solution(doc_info,output_base_soln);
    Perturbed_state_problem_pt->doc_solution(doc_info,output_perturbed_soln);
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt, and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt.
Referenced by StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::doc_solution().
doc_solution() [2/3]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::doc_solution (DocInfo & doc_info, const bool & output_base_soln, const bool & output_perturbed_soln) inline
Document base and perturbed state solutions.
   {
    Base_state_problem_pt->doc_solution(doc_info,output_base_soln);
    Perturbed_state_problem_pt->doc_solution(doc_info,output_perturbed_soln);
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt, and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt.
doc_solution() [3/3]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::doc_solution (DocInfo & doc_info, const bool & output_base_soln, const bool & output_perturbed_soln) inline
Document base and perturbed state solutions.
   {
    Base_state_problem_pt->
     doc_solution(doc_info,output_base_soln);
    Perturbed_state_problem_pt->doc_solution(doc_info,output_perturbed_soln);
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt, StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::doc_solution(), and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt.
get_perturbed_state_problem_dofs() [1/3]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::get_perturbed_state_problem_dofs (DoubleVector & d) inline
Get perturbed state dofs.
   {
    Perturbed_state_problem_pt->get_dofs(d);
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt.
get_perturbed_state_problem_dofs() [2/3]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::get_perturbed_state_problem_dofs (DoubleVector & d) inline
Get perturbed state dofs.
   {
    Perturbed_state_problem_pt->get_dofs(d);
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt.
get_perturbed_state_problem_dofs() [3/3]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::get_perturbed_state_problem_dofs (DoubleVector & d) inline
Get perturbed state dofs.
   {
    Perturbed_state_problem_pt->get_dofs(d);
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt.
initialise_dt() [1/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::initialise_dt (const double & dt) inline
Initialise timestep (single dt version)
   {
    Base_state_problem_pt->initialise_dt(dt);
    Perturbed_state_problem_pt->initialise_dt(dt);
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt, and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt.
initialise_dt() [2/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::initialise_dt (const double & dt) inline
Initialise timestep (single dt version)
   {
    Base_state_problem_pt->initialise_dt(dt);
    Perturbed_state_problem_pt->initialise_dt(dt);
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt, and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt.
initialise_dt() [3/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::initialise_dt (const double & dt) inline
Initialise timestep (single dt version)
   {
    Base_state_problem_pt->initialise_dt(dt);
    Perturbed_state_problem_pt->initialise_dt(dt);
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt, and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt.
initialise_dt() [4/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::initialise_dt (const Vector< double > & dt) inline
Initialise timestep (vector of dts version)
   {
    Base_state_problem_pt->initialise_dt(dt);
    Perturbed_state_problem_pt->initialise_dt(dt);
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt, and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt.
initialise_dt() [5/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::initialise_dt (const Vector< double > & dt) inline
Initialise timestep (vector of dts version)
   {
    Base_state_problem_pt->initialise_dt(dt);
    Perturbed_state_problem_pt->initialise_dt(dt);
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt, and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt.
initialise_dt() [6/6]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::initialise_dt (const Vector< double > & dt) inline
Initialise timestep (vector of dts version)
   {
    Base_state_problem_pt->initialise_dt(dt);
    Perturbed_state_problem_pt->initialise_dt(dt);
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt, and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt.
initialise_trace_files() [1/3]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::initialise_trace_files () inline
Initialise trace files (creates column headings)
   {
    // Initialise base and perturbed state trace files
    Base_state_problem_pt->initialise_trace_file();
    Perturbed_state_problem_pt->initialise_trace_file();
    // Initialise stability problem trace files
    Trace_file_power_method << "time, convergence_criterion, "
                            << "tolerance*abs(eigenvalue)" << std::endl;
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt, StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt, and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Trace_file_power_method.
initialise_trace_files() [2/3]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::initialise_trace_files () inline
Initialise trace files (creates column headings)
   {
    // Initialise base and perturbed state trace files
    Base_state_problem_pt->initialise_trace_file();
    Perturbed_state_problem_pt->initialise_trace_file();
    // Initialise stability problem trace files
    Trace_file_power_method << "time, convergence_criterion, "
                            << "tolerance*abs(eigenvalue)" << std::endl;
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt, StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt, and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Trace_file_power_method.
initialise_trace_files() [3/3]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::initialise_trace_files () inline
Initialise trace files (creates column headings)
   {
    // Initialise base and perturbed state trace files
    Base_state_problem_pt->initialise_trace_file();
    Perturbed_state_problem_pt->initialise_trace_file();
    // Initialise stability problem trace files
    Trace_file_periodic_base_flow << "time, norm, tolerance" << std::endl;
    Trace_file_power_method << "time, convergence_criterion, "
                            << "tolerance*abs(eigenvalue)" << std::endl;
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt, StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt, StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Trace_file_periodic_base_flow, and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Trace_file_power_method.
pass_updated_nondim_parameters_to_elements() [1/2]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::pass_updated_nondim_parameters_to_elements () inline
Pass updated nondimensional parameters to the elements of both problems
   {
    Base_state_problem_pt->pass_updated_nondim_parameters_to_elements();
    Perturbed_state_problem_pt->pass_updated_nondim_parameters_to_elements();
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt, and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt.
pass_updated_nondim_parameters_to_elements() [2/2]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::pass_updated_nondim_parameters_to_elements () inline
Pass updated nondimensional parameters to the elements of both problems
   {
    Base_state_problem_pt->pass_updated_nondim_parameters_to_elements();
    Perturbed_state_problem_pt->pass_updated_nondim_parameters_to_elements();
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt, and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt.
perform_power_method() [1/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > unsigned StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::perform_power_method (const double & dt, const unsigned & n_timesteps, DocInfo & doc_info, const double & tolerance, const unsigned & max_iter, double & calc_eigenvalue, DoubleVector & input)
Perform a power method with a maximum of max_iter iterations. This function requires an initial guess for the dominant eigenvector "input"and a tolerance which controls at which point the dominant eigenvalue will be deemed converged. At this point the calculated value of this eigenvalue "calc_eigenvalue" and its corresponding eigenvector "input" will be returned. The return value of this function is the number of power method iterations which were performed.
Perform a power method with a maximum of max_iter iterations. This function requires an initial guess for the dominant eigenvector "input" and a tolerance which controls at which point the dominant eigenvalue will be deemed converged. At this point the calculated value of this eigenvalue "calc_eigenvalue" and its corresponding eigenvector "input" will be returned. The return value of this function is the number of power method iterations which were performed.
 {
  // Determine number of degrees of freedom in perturbed state problem
  const unsigned n_dof_perturbed = Perturbed_state_problem_pt->ndof();
  // Begin power method loop
  for(unsigned p=0;p<max_iter;p++)
   {
    cout << "\nThis is power method loop number " << p+1
         << " of a maximum " << max_iter << "." << endl;
    // Normalise input vector
    const double inv_norm = 1.0/input.norm();
    for(unsigned i=0;i<n_dof_perturbed;i++) { input[i] *= inv_norm; }
    // Set up storage for output vector
    DoubleVector output;
    // Re-set the starting dof vector for the perturbed state problem
    Perturbed_state_problem_pt->set_dofs(input);
    // Perform unsteady run for n_timesteps
    this->unsteady_run(dt,n_timesteps,doc_info);
    // Get dofs from perturbed state problem
    Perturbed_state_problem_pt->get_dofs(output);
    // Calculate eigenvalue (scalar product of input and output vectors)
    calc_eigenvalue = input.dot(output);
    // Calculate L2 norm of (output - eigenvalue*input)
    // divided by the square root of the number of degrees of freedom
    double convergence_criterion = 0.0;
    for(unsigned i=0;i<n_dof_perturbed;i++)
     {
      convergence_criterion +=
       (output[i] - calc_eigenvalue*input[i])
       *(output[i] - calc_eigenvalue*input[i]);
     }
    convergence_criterion = sqrt(convergence_criterion/n_dof_perturbed);
    // Print convergence criterion and threshold
    cout << "\nConvergence criterion     = " << convergence_criterion
         << "\ntolerance*abs(eigenvalue) = " << tolerance*abs(calc_eigenvalue)
         << endl;
    // Check for convergence
    if(convergence_criterion <= tolerance*abs(calc_eigenvalue))
     {
      cout << "\nPower method has converged to within a tolerance of "
           << tolerance << "\nin " << p+1
           << " iterations of the power method.\n" << endl;
      // Output the dominant eigenvector
      Perturbed_state_problem_pt->doc_solution(doc_info);
      // Return the number of iterations of the power method
      return p+1;
     }
    else
     {
      input = output;
      output.clear();
     }
   }
  // If we reach here, the power method has failed to converge in max_iter
  // iterations.
  cout << "\nPower method has failed to converge to within a tolerance of "
       << tolerance << "\nin " << max_iter
       << " iterations of the power method" << endl;
  // Output the dominant eigenvector
  Perturbed_state_problem_pt->doc_solution(doc_info);
  return max_iter;
 } // End of perform_power_method
References abs(), oomph::DoubleVector::dot(), i, oomph::DoubleVector::norm(), output(), p, and sqrt().
perform_power_method() [2/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > unsigned StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::perform_power_method (const double & dt, const unsigned & n_timesteps, DocInfo & doc_info, const double & tolerance, const unsigned & max_iter, double & calc_eigenvalue, DoubleVector & input)
Perform a power method with a maximum of max_iter iterations. This function requires an initial guess for the dominant eigenvector "input"and a tolerance which controls at which point the dominant eigenvalue will be deemed converged. At this point the calculated value of this eigenvalue "calc_eigenvalue" and its corresponding eigenvector "input" will be returned. The return value of this function is the number of power method iterations which were performed.
perform_power_method() [3/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > unsigned StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::perform_power_method (const double & dt, const unsigned & n_timesteps, DocInfo & doc_info, const double & tolerance, const unsigned & max_iter, double & calc_eigenvalue, DoubleVector & input, Vector< DoubleVector > & base_state_dofs_over_period)
Perform a power method with a maximum of max_iter iterations. This function requires an initial guess for the dominant eigenvector "input"and a tolerance which controls at which point the dominant eigenvalue will be deemed converged. At this point the calculated value of this eigenvalue "calc_eigenvalue" and its corresponding eigenvector "input" will be returned. The return value of this function is the number of power method iterations which were performed.
 {
  // Initialise output_base_state_solution flag to true
  bool output_base_state_solution = true;
  // Reset the solution counter to zero
  doc_info.number()=0;
  // Determine number of degrees of freedom in perturbed state problem
  const unsigned n_dof_perturbed = Perturbed_state_problem_pt->ndof();
  // Set up external storage for the dofs over one period
  Vector<DoubleVector> dofs_over_period(n_timesteps);
  // Set flag to true
  this->set_first_power_method_iteration_flag_to_true();
  // Begin power method loop
  for(unsigned p=0;p<max_iter;p++)
   {
    cout << "\nThis is power method loop number " << p+1
         << " of a maximum " << max_iter << "." << endl;
    // Normalise input vector
    const double inv_norm = 1.0/input.norm();
    for(unsigned i=0;i<n_dof_perturbed;i++) { input[i] *= inv_norm; }
    // Set up storage for output vector from Arnoldi method
    DoubleVector output;
    // Perform unsteady run over this period
    unsteady_run_for_power_method(dt,n_timesteps,doc_info,input,output,
                                  output_base_state_solution,dofs_over_period,
                                  base_state_dofs_over_period);
    // Calculate eigenvalue (scalar product of input and output vectors)
    calc_eigenvalue = input.dot(output);
    // Calculate L2 norm of (output - eigenvalue*input)
    double convergence_criterion = 0.0;
    for(unsigned i=0;i<n_dof_perturbed;i++)
     {
      convergence_criterion +=
       (output[i] - calc_eigenvalue*input[i])
       *(output[i] - calc_eigenvalue*input[i]);
     }
    convergence_criterion = sqrt(convergence_criterion);
    cout << "\nConvergence criterion     = " << convergence_criterion << endl;
    cout << "tolerance*abs(eigenvalue) = " << tolerance*abs(calc_eigenvalue)
         << endl;
    // Document convergence criterion and tolerance*eigenvalue in trace file
    Trace_file_power_method << Perturbed_state_problem_pt->time_pt()->time()
                            << " " << convergence_criterion << " "
                            << tolerance*abs(calc_eigenvalue) << std::endl;
    // We only wish to output the base state solution during the first
    // iteration of the power method (so that we can see what it looks like
    // when converged)
    output_base_state_solution = false;
    // Check for convergence
    if(convergence_criterion <= tolerance*abs(calc_eigenvalue))
     {
      cout << "\nPower method has converged to within a tolerance of "
           << tolerance << "\nin " << p+1
           << " iterations of the power method.\n" << endl;
      // Reset the solution counter to zero
      doc_info.number()=0;
      // Output the dominant eigenvector over an entire period
      for(unsigned i=0;i<n_timesteps;i++)
       {
        // Populate perturbed state problem with dofs which have been stored
        // over the last period
        Perturbed_state_problem_pt->
         assign_eigenvector_to_dofs(dofs_over_period[i]);
        // Output the perturbed state solution
        this->doc_solution(doc_info,false,true);
        // Increment counter for solutions
        doc_info.number()++;
       }
      // Return the number of iterations of the power method
      return p+1;
     }
    else
     {
      input = output;
      output.clear();
     }
    // Set flag to false
    this->set_first_power_method_iteration_flag_to_false();
   }
  // If we reach here, the power method has failed to converge in max_iter
  // iterations.
  cout << "\nPower method has failed to converge to within a tolerance of "
       << tolerance << "\nin " << max_iter
       << " iterations of the power method" << endl;
  // Reset the solution counter to zero
  doc_info.number()=0;
  // Output the dominant eigenvector over an entire period
  for(unsigned i=0;i<n_timesteps;i++)
   {
    // Populate perturbed state problem with dofs which have been stored
    // over the last period
    Perturbed_state_problem_pt->
     assign_eigenvector_to_dofs(dofs_over_period[i]);
    // Output the perturbed state solution
    this->doc_solution(doc_info,false,true);
    // Increment counter for solutions
    doc_info.number()++;
   }
  return max_iter;
 } // End of perform_power_method
References abs(), oomph::DoubleVector::dot(), i, oomph::DoubleVector::norm(), oomph::DocInfo::number(), output(), p, and sqrt().
perform_power_method() [4/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > unsigned StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::perform_power_method (const double & dt, DocInfo & doc_info, const double & tolerance, const unsigned & max_iter, double & calc_eigenvalue, DoubleVector & input)
Perform a power method with a maximum of max_iter iterations. This function requires an initial guess for the dominant eigenvector "input"and a tolerance which controls at which point the dominant eigenvalue will be deemed converged. At this point the calculated value of this eigenvalue "calc_eigenvalue" and its corresponding eigenvector "input" will be returned. The return value of this function is the number of power method iterations which were performed.
 {
  // Initialise output_base_state_solution flag to true
  bool output_base_state_solution = true;
  // Reset the solution counter to zero
  doc_info.number()=0;
  // Determine number of degrees of freedom in perturbed state problem
  const unsigned n_dof_perturbed = Perturbed_state_problem_pt->ndof();
  // Begin power method loop
  for(unsigned p=0;p<max_iter;p++)
   {
    cout << "\nThis is power method loop number " << p+1
         << " of a maximum " << max_iter << "." << endl;
    // Normalise input vector
    const double inv_norm = 1.0/input.norm();
    for(unsigned i=0;i<n_dof_perturbed;i++) { input[i] *= inv_norm; }
    // Set up storage for output vector
    DoubleVector output;
    // Re-set the starting dof vector for the perturbed state problem
    Perturbed_state_problem_pt->set_dofs(input);
    // Set the perturbed state problem's timestepper to work in BDF1 mode
    Perturbed_state_problem_pt->time_stepper_pt()->turn_on_bdf1_mode();
    // Initialise timestep (also sets timestepper weights)
    this->initialise_dt(dt);
    // Take timestep
    Perturbed_state_problem_pt->unsteady_newton_solve(dt);
    // Doc info in trace file and output base state solution
    // (if flag is set appropriately)
    this->doc_solution(doc_info,output_base_state_solution,false);
    // Increment counter for solutions
    doc_info.number()++;
    // Get dofs from perturbed state problem
    Perturbed_state_problem_pt->get_dofs(output);
    // Calculate eigenvalue (scalar product of input and output vectors)
    calc_eigenvalue = input.dot(output);
    // Calculate L2 norm of (output - eigenvalue*input)
    // divided by the square root of the number of degrees of freedom
    double convergence_criterion = 0.0;
    for(unsigned i=0;i<n_dof_perturbed;i++)
     {
      convergence_criterion +=
       (output[i] - calc_eigenvalue*input[i])
       *(output[i] - calc_eigenvalue*input[i]);
     }
    convergence_criterion = sqrt(convergence_criterion/n_dof_perturbed);
    // Print convergence criterion and threshold
    cout << "\nConvergence criterion     = " << convergence_criterion << endl;
    cout << "tolerance*abs(eigenvalue) = " << tolerance*abs(calc_eigenvalue)
         << endl;
    // Document convergence criterion and threshold in trace file
    Trace_file_power_method << Perturbed_state_problem_pt->time_pt()->time()
                            << " " << convergence_criterion << " "
                            << tolerance*abs(calc_eigenvalue) << std::endl;
    // We only wish to output the base state solution during the first
    // iteration of the power method (so that we can see what it looks like
    // when converged)
    output_base_state_solution = false;
    // Check for convergence
    if(convergence_criterion <= tolerance*abs(calc_eigenvalue))
     {
      cout << "\nPower method has converged to within a tolerance of "
           << tolerance << "\nin " << p+1
           << " iterations of the power method.\n" << endl;
      // Reset the solution counter to zero
      doc_info.number()=0;
      // Output the dominant eigenvector (perturbed state solution)
      this->doc_solution(doc_info,false,true);
      // Return the number of iterations of the power method
      return p+1;
     }
    else
     {
      input = output;
      output.clear();
     }
   }
  // If we reach here, the power method has failed to converge in max_iter
  // iterations.
  cout << "\nPower method has failed to converge to within a tolerance of "
       << tolerance << "\nin " << max_iter
       << " iterations of the power method" << endl;
  // Reset the solution counter to zero
  doc_info.number()=0;
  // Output the dominant eigenvector (perturbed state solution)
  this->doc_solution(doc_info,false,true);
  return max_iter;
 } // End of perform_power_method
References abs(), oomph::DoubleVector::dot(), i, oomph::DoubleVector::norm(), oomph::DocInfo::number(), output(), p, and sqrt().
perform_power_method() [5/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > unsigned StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::perform_power_method (const double & dt, DocInfo & doc_info, const double & tolerance, const unsigned & max_iter, double & calc_eigenvalue, DoubleVector & input)
Perform a power method with a maximum of max_iter iterations. This function requires an initial guess for the dominant eigenvector "input"and a tolerance which controls at which point the dominant eigenvalue will be deemed converged. At this point the calculated value of this eigenvalue "calc_eigenvalue" and its corresponding eigenvector "input" will be returned. The return value of this function is the number of power method iterations which were performed.
perturbed_state_problem_pt() [1/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > const PerturbedStateProblem<BASE_ELEMENT,PERTURBED_ELEMENT>* StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::perturbed_state_problem_pt () inline
Access function for perturbed state problem.
 { return Perturbed_state_problem_pt; }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt.
perturbed_state_problem_pt() [2/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > PerturbedStateProblem<BASE_ELEMENT,PERTURBED_ELEMENT>* StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::perturbed_state_problem_pt () const inline
Access function for perturbed state problem.
 { return Perturbed_state_problem_pt; }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt.
perturbed_state_problem_pt() [3/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > PerturbedStateProblem<BASE_ELEMENT,PERTURBED_ELEMENT>* StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::perturbed_state_problem_pt () const inline
Access function for perturbed state problem.
 { return Perturbed_state_problem_pt; }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt.
perturbed_state_problem_pt() [4/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > PerturbedStateProblem<BASE_ELEMENT,PERTURBED_ELEMENT>* StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::perturbed_state_problem_pt () const inline
Access function for perturbed state problem.
 { return Perturbed_state_problem_pt; }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt.
perturbed_state_problem_pt() [5/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > PerturbedStateProblem<BASE_ELEMENT,PERTURBED_ELEMENT>* StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::perturbed_state_problem_pt () const inline
Access function for perturbed state problem.
 { return Perturbed_state_problem_pt; }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt.
reset_global_time_to_zero() [1/3]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::reset_global_time_to_zero () inline
(Re-)set the global time in both problems to zero
   {
    Base_state_problem_pt->time_pt()->time() = 0.0;
    Perturbed_state_problem_pt->time_pt()->time() = 0.0;
    cout << "\nReset global time to zero in both problems.\n" << endl;
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt, and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt.
reset_global_time_to_zero() [2/3]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::reset_global_time_to_zero () inline
(Re-)set the global time in both problems to zero
   {
    Base_state_problem_pt->time_pt()->time() = 0.0;
    Perturbed_state_problem_pt->time_pt()->time() = 0.0;
    cout << "\nReset global time to zero in both problems.\n" << endl;
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt, and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt.
reset_global_time_to_zero() [3/3]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::reset_global_time_to_zero () inline
(Re-)set the global time in both problems to zero
   {
    Base_state_problem_pt->time_pt()->time() = 0.0;
    Perturbed_state_problem_pt->time_pt()->time() = 0.0;
    cout << "\nReset global time to zero in both problems.\n" << endl;
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt, and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt.
set_first_power_method_iteration_flag_to_false()
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::set_first_power_method_iteration_flag_to_false () inline
Switch off flag.
   { First_power_method_iteration = false; }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::First_power_method_iteration.
set_first_power_method_iteration_flag_to_true()
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::set_first_power_method_iteration_flag_to_true () inline
Switch on flag.
   { First_power_method_iteration = true; }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::First_power_method_iteration.
set_initial_condition() [1/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::set_initial_condition () inline
Set initial conditions.
   {
    Base_state_problem_pt->set_initial_condition();
    Perturbed_state_problem_pt->set_initial_condition();
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt, and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt.
set_initial_condition() [2/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::set_initial_condition () inline
Set initial conditions.
   {
    Base_state_problem_pt->set_initial_condition();
    Perturbed_state_problem_pt->set_initial_condition();
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt, and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt.
set_initial_condition() [3/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::set_initial_condition () inline
Set initial conditions.
   {
    Base_state_problem_pt->set_initial_condition();
    Perturbed_state_problem_pt->set_initial_condition();
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt, and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt.
set_initial_condition() [4/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::set_initial_condition () inline
Set initial conditions.
   {
    Base_state_problem_pt->set_initial_condition();
    Perturbed_state_problem_pt->set_initial_condition();
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt, and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt.
set_initial_condition() [5/5]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::set_initial_condition () inline
Set initial conditions.
   {
    Base_state_problem_pt->set_initial_condition();
    Perturbed_state_problem_pt->set_initial_condition();
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt, and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt.
set_perturbed_state_time_equal_to_base_state_time() [1/3]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::set_perturbed_state_time_equal_to_base_state_time () inline private
(Re-)set the global time in the perturbed state problem to be equal to the global time in the base state problem
   {
    // Get current global time according to base state problem
    const double base_state_time = Base_state_problem_pt->time_pt()->time();
    // Set perturbed state problem's global time
    Perturbed_state_problem_pt->time_pt()->time() = base_state_time;
    cout << "\nReset perturbed state problem's global time to "
         << base_state_time << endl;
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt, and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt.
set_perturbed_state_time_equal_to_base_state_time() [2/3]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::set_perturbed_state_time_equal_to_base_state_time () inline private
(Re-)set the global time in the perturbed state problem to be equal to the global time in the base state problem
   {
    // Get current global time according to base state problem
    const double base_state_time = Base_state_problem_pt->time_pt()->time();
    // Set perturbed state problem's global time
    Perturbed_state_problem_pt->time_pt()->time() = base_state_time;
    cout << "\nReset perturbed state problem's global time to "
         << base_state_time << endl;
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt, and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt.
set_perturbed_state_time_equal_to_base_state_time() [3/3]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::set_perturbed_state_time_equal_to_base_state_time () inline private
(Re-)set the global time in the perturbed state problem to be equal to the global time in the base state problem
   {
    // Get current global time according to base state problem
    const double base_state_time = Base_state_problem_pt->time_pt()->time();
    // Set perturbed state problem's global time
    Perturbed_state_problem_pt->time_pt()->time() = base_state_time;
    cout << "\nReset perturbed state problem's global time to "
         << base_state_time << endl;
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt, and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt.
set_up_periodic_base_flow()
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > unsigned StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::set_up_periodic_base_flow (const double & dt, const unsigned & n_timesteps, DocInfo & doc_info, const double & tolerance)
Integrate just the base state problem forwards in time with timestep dt for n_timesteps. Once a periodic state has been reached, set perturbed state problem's global time to be equal to the base state problem's global time and begin solving the perturbed state problem also. This function returns the number of periods taken to satisfy the "periodic state" exit criteria.
 {
  // Check that base state timestepper is working in BDF2 mode
  if(Base_state_problem_pt->time_stepper_pt()->bdf1_mode())
   {
    std::cout << "Base state problem's timestepper is not in BDF2 mode."
              << "\n Exiting...\n" << std::endl;
    exit(1);
   }
  // Initialise timestep (also sets timestepper weights)
  this->initialise_dt(dt);
  // Set up storage for base state problem's dof vectors at the end of the
  // previous period and at the end of the current period
  Vector<double> previous_dofs;
  Vector<double> current_dofs;
  // Determine number of nodes in base state problem
  const unsigned n_node = Base_state_problem_pt->mesh_pt()->nnode();
  // Set up storage for norm of vector of differences between current
  // dofs and dofs from one period ago (initialise to 1.0)
  double norm_over_ndof = 1.0;
  // Set up storage for loop counter
  unsigned loop_counter = 0;
  // While this norm is greater than the base state convergence criterion
  while(norm_over_ndof > tolerance)
   {
    // Record the dofs corresponding to the azimuthal velocity at the end
    // of the previous period (equivalent to recording them at the start
    // of the current period, as we do here)
    for(unsigned n=0;n<n_node;n++)
     {
      previous_dofs.push_back
       (Base_state_problem_pt->mesh_pt()->node_pt(n)->value(2));
     }
    // Timestepping loop
    for(unsigned i=0;i<n_timesteps;i++)
     {
      // Output timestep and global time
      std::cout << "  Timestep " << i+1 << " of " << n_timesteps
                << "; Time is " << Base_state_problem_pt->time_pt()->time()
                << " (base)" << std::endl;
      // Take timestep
      Base_state_problem_pt->unsteady_newton_solve(dt);
      // Output solution
      Base_state_problem_pt->doc_solution(doc_info,false);
      // Increment counter for solutions
      doc_info.number()++;
     }
    // Get dofs from base state problem at the end of this period
    for(unsigned n=0;n<n_node;n++)
     {
      current_dofs.push_back
       (Base_state_problem_pt->mesh_pt()->node_pt(n)->value(2));
     }
    // Find difference between each current dof and the corresponding
    // previous dof from one period ago
    for(unsigned i=0;i<n_node;i++) { current_dofs[i] -= previous_dofs[i]; }
    // Evaluate L2 norm of this vector over number of dofs
    norm_over_ndof = 0.0;
    for(unsigned i=0;i<n_node;i++)
     {
      norm_over_ndof += (current_dofs[i]*current_dofs[i]);
     }
    norm_over_ndof = sqrt(norm_over_ndof);
    norm_over_ndof = norm_over_ndof/n_node;
    ios_base::fmtflags flags =  cout.flags(); // Save old flags
    cout << "    ==>  norm_over_ndof = " << scientific << norm_over_ndof
         << ", tolerance = " << tolerance << endl;
    cout.flags(flags);  // Set the flags to the way they were
    // Document norm and tolerance in trace file
    Trace_file_periodic_base_flow << Base_state_problem_pt->time_pt()->time()
                                  << " " << norm_over_ndof
                                  << " " << tolerance << std::endl;
    // Clear the Vector<double>s
    previous_dofs.clear();
    current_dofs.clear();
    // Increment loop counter
    loop_counter++;
   } // End of while loop
  cout << "\nI have broken out of the base state loop after "
       << loop_counter << " periods.\n" << endl;
  // (Re-)set the perturbed state problem's global time to correspond
  // to the base state problem's global time
  this->set_perturbed_state_time_equal_to_base_state_time();
  // Return the number of periods required to reach a periodic flow
  return loop_counter;
 } // End of set_up_periodic_base_flow
References i, n, oomph::DocInfo::number(), and sqrt().
unsteady_run() [1/3]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::unsteady_run (const double & dt, const unsigned & n_timesteps, DocInfo & doc_info)
Integrate forwards in time with timestep dt for n_timesteps.
 {
  // Timestepping loop
  for(unsigned i=0;i<n_timesteps;i++)
   {
    // Output timestep and global time
    std::cout << "  Timestep " << i+1 << " of " << n_timesteps
              << "; Time is " << Perturbed_state_problem_pt->time_pt()->time()
              << std::endl;
    // Take timestep
    Perturbed_state_problem_pt->unsteady_newton_solve(dt);
   } // End of loop over timesteps
 } // End of unsteady_run
References i.
Referenced by StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::unsteady_run_for_power_method().
unsteady_run() [2/3]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::unsteady_run (const double & dt, const unsigned & n_timesteps, DocInfo & doc_info)
Integrate forwards in time with timestep dt for n_timesteps.
unsteady_run() [3/3]
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::unsteady_run (const double & dt, const unsigned & n_timesteps, DocInfo & doc_info, const bool & output_base_soln, Vector< DoubleVector > & perturbed_state_dofs_over_period, Vector< DoubleVector > & base_state_dofs_over_period)
Integrate forwards in time with timestep dt for n_timesteps.
Integrate forwards in time with timestep dt for n_timesteps Record an entire period's worth of the perturbed state problem solution in perturbed_state_dofs_over_period
 {
  // "Outer" timestepping loop
  for(unsigned i=0;i<n_timesteps;i++)
   {
    // Output timestep and global time
    std::cout << "  Timestep " << i+1 << " of " << n_timesteps
              << "; Time is " << Base_state_problem_pt->time_pt()->time()
              << " (base), " << Perturbed_state_problem_pt->time_pt()->time()
              << " (perturbed)" << std::endl;
    // On the first "timestep", perform n_timesteps BDF1 timesteps
    if(i==0)
     {
      // Set the perturbed state problem's timestepper to work in BDF1 mode
      Base_state_problem_pt->time_stepper_pt()->turn_on_bdf1_mode();
      Perturbed_state_problem_pt->time_stepper_pt()->turn_on_bdf1_mode();
      // Determine the BDF1 timestep
      const double dt_bdf1 = dt/n_timesteps;
      // Initialise timestep (also sets timestepper weights)
      this->initialise_dt(dt_bdf1);
      // BDF1 timestepping loop
      for(unsigned j=0;j<n_timesteps;j++)
       {
        cout << "    - BDF1 loop: Timestep " << j+1 << " of " << n_timesteps
             << "; Time (before advance) is "
             << Base_state_problem_pt->time_pt()->time()
             << " (base), "
             << Perturbed_state_problem_pt->time_pt()->time()
             << " (perturbed)" << std::endl;
        // Take timestep
        if(First_power_method_iteration)
         {
          Base_state_problem_pt->unsteady_newton_solve(dt_bdf1);
          Base_state_problem_pt->get_dofs(base_state_dofs_over_period[j]);
         }
        else
         {
          Base_state_problem_pt
           ->assign_eigenvector_to_dofs(base_state_dofs_over_period[j]);
         }
        Perturbed_state_problem_pt->unsteady_newton_solve(dt_bdf1);
        // Document in trace file on all steps other than the last
        // (when documentation is performed in outer loop)
        if(j!=(n_timesteps-1))
         {
          this->doc_solution(doc_info,false,false);
         }
       } // End of BDF1 timestepping loop
      // Now set the timestepper back to BDF2 mode
      Base_state_problem_pt->time_stepper_pt()->turn_off_bdf1_mode();
      Perturbed_state_problem_pt->time_stepper_pt()->turn_off_bdf1_mode();
     }
    // On the second "timestep", use a timestep that's twice as big as
    // used during the BDF1 timestepping loop
    else if(i==1)
     {
      // Determine the timestep and number of timesteps for this loop
      const double dt_thisloop = 2*dt/n_timesteps;
      const double n_timesteps_thisloop = 0.5*n_timesteps;
      // Determine the timestep for the previous loop
      const double dt_prevloop = dt/n_timesteps;
      Vector<double> dt_vector;
      dt_vector.push_back(dt_prevloop);
      dt_vector.push_back(dt_thisloop);
      // Initialise timestep for first time around this timestepping loop
      // (also sets timestepper weights)
      this->initialise_dt(dt_vector);
      // Timestepping loop
      for(unsigned j=0;j<n_timesteps_thisloop;j++)
       {
        std::cout << "    - nstep/2 loop: Timestep " << j+1
                  << " of " << n_timesteps_thisloop
                  << "; Time (before advance) is "
                  << Base_state_problem_pt->time_pt()->time()
                  << " (base), "
                  << Perturbed_state_problem_pt->time_pt()->time()
                  << " (perturbed)" << std::endl;
        // Take timestep
        if(First_power_method_iteration)
         {
          Base_state_problem_pt->unsteady_newton_solve(dt_thisloop);
          Base_state_problem_pt
           ->get_dofs(base_state_dofs_over_period[(n_timesteps+j)]);
         }
        else
         {
          Base_state_problem_pt->assign_eigenvector_to_dofs
           (base_state_dofs_over_period[(n_timesteps+j)]);
         }
        Perturbed_state_problem_pt->unsteady_newton_solve(dt_thisloop);
        // Document in trace file on all steps other than the last
        // (when documentation is performed in outer loop)
        if(j!=(n_timesteps_thisloop-1))
         {
          this->doc_solution(doc_info,false,false);
         }
        // On the first time through this loop, initialise the timestep
        // again with equal timesteps
        if(j==0) { this->initialise_dt(dt_thisloop); }
       }
     }
    // On the third "timestep", use a timestep that's five times as big as
    // used during the BDF1 timestepping loop
    else if(i==2)
     {
      // Determine the timestep and number of timesteps for this loop
      const double dt_thisloop = 5*dt/n_timesteps;
      const double n_timesteps_thisloop = 0.2*n_timesteps;
      // Determine the timestep for the previous loop
      const double dt_prevloop = 2*dt/n_timesteps;
      Vector<double> dt_vector;
      dt_vector.push_back(dt_prevloop);
      dt_vector.push_back(dt_thisloop);
      // Initialise timestep for first time around this timestepping loop
      // (also sets timestepper weights)
      this->initialise_dt(dt_vector);
      // Timestepping loop
      for(unsigned j=0;j<n_timesteps_thisloop;j++)
       {
        std::cout << "    - nstep/2 loop: Timestep " << j+1
                  << " of " << n_timesteps_thisloop
                  << "; Time (before advance) is "
                  << Base_state_problem_pt->time_pt()->time()
                  << " (base), "
                  << Perturbed_state_problem_pt->time_pt()->time()
                  << " (perturbed)" << std::endl;
        // Take timestep
        if(First_power_method_iteration)
         {
          Base_state_problem_pt->unsteady_newton_solve(dt_thisloop);
          Base_state_problem_pt
           ->get_dofs(base_state_dofs_over_period[((n_timesteps*1.5)+j)]);
         }
        else
         {
          Base_state_problem_pt->assign_eigenvector_to_dofs
           (base_state_dofs_over_period[((n_timesteps*1.5)+j)]);
         }
        Perturbed_state_problem_pt->unsteady_newton_solve(dt_thisloop);
        // Document in trace file on all steps other than the last
        // (when documentation is performed in outer loop)
        if(j!=(n_timesteps_thisloop-1))
         {
          this->doc_solution(doc_info,false,false);
         }
        // On the first time through this loop, initialise the timestep
        // again with equal timesteps
        if(j==0) { this->initialise_dt(dt_thisloop); }
       }
     }
    // On the fourth "timestep", use the actual timestep dt but need to
    // specify past dts as changing step size from last time
    else if(i==3)
     {
      // Determine the timestep for the previous loop
      const double dt_prevloop = 5*dt/n_timesteps;
      Vector<double> dt_vector;
      dt_vector.push_back(dt_prevloop);
      dt_vector.push_back(dt);
      // Initialise timestep for first time around this timestepping loop
      // (also sets timestepper weights)
      this->initialise_dt(dt_vector);
      // Take timestep
      if(First_power_method_iteration)
       {
        Base_state_problem_pt->unsteady_newton_solve(dt);
        Base_state_problem_pt
         ->get_dofs(base_state_dofs_over_period
                    [((n_timesteps*1.5)+(n_timesteps*0.2))]);
       }
      else
       {
        Base_state_problem_pt->assign_eigenvector_to_dofs
         (base_state_dofs_over_period[((n_timesteps*1.5)+(n_timesteps*0.2))]);
       }
      Perturbed_state_problem_pt->unsteady_newton_solve(dt);
      // Initialise timestep back to equal timesteps of length dt
      // (also sets timestepper weights)
      this->initialise_dt(dt);
     }
    // On all subsequent timesteps perform normal BDF2 timestepping
    else
     {
      // Take timestep
      if(First_power_method_iteration)
       {
        Base_state_problem_pt->unsteady_newton_solve(dt);
        Base_state_problem_pt
         ->get_dofs(base_state_dofs_over_period
                    [((n_timesteps*1.5)+(n_timesteps*0.2)+(i-3))]);
       }
      else
       {
        Base_state_problem_pt->assign_eigenvector_to_dofs
         (base_state_dofs_over_period
          [((n_timesteps*1.5)+(n_timesteps*0.2)+(i-3))]);
       }
      Perturbed_state_problem_pt->unsteady_newton_solve(dt);
     }
    // At end of each "outer" timestep, document info in trace file
    // and also output base state solution (if flag is set appropriately)
    this->doc_solution(doc_info,output_base_soln,false);
    // Store perturbed state problems dofs so that eigenvector over one
    // period can be outputted at the end of the power method
    Perturbed_state_problem_pt->get_dofs(perturbed_state_dofs_over_period[i]);
    // Increment counter for solutions
    doc_info.number()++;
   } // End of loop over "outer timesteps"
 } // End of unsteady run
References i, j, and oomph::DocInfo::number().
unsteady_run_for_power_method()
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > void StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::unsteady_run_for_power_method (const double & dt, const unsigned & n_timesteps, DocInfo & doc_info, const DoubleVector & input_perturbed_state_dofs, DoubleVector & output_perturbed_state_dofs, const bool & output_base_soln, Vector< DoubleVector > & perturbed_state_dofs_over_period, Vector< DoubleVector > & base_state_dofs_over_period) inline
Integrate forwards in time with timestep dt for n_timesteps. Re-set the initial conditions for the perturbed state problem to be input_perturbed_state_dofs and, at the end of the timestepping loop, return the perturbed state problem's dofs
   {
    // Re-set the starting dof vector for the perturbed state problem
    Perturbed_state_problem_pt->set_dofs(input_perturbed_state_dofs);
    // Perform standard unsteady run
    this->unsteady_run(dt,n_timesteps,doc_info,
                       output_base_soln,perturbed_state_dofs_over_period,
                       base_state_dofs_over_period);
    // Get dofs from perturbed state problem
    Perturbed_state_problem_pt->get_dofs(output_perturbed_state_dofs);
   }
References StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt, and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::unsteady_run().
Member Data Documentation
Base_state_problem_pt
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > BaseStateProblem< BASE_ELEMENT > * StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Base_state_problem_pt private
Pointer to base state problem class.
Referenced by StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::base_flow_steady_newton_solve(), StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::base_state_problem_pt(), StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::close_trace_files(), StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::create_trace_files(), StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::doc_solution(), StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::initialise_dt(), StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::initialise_trace_files(), StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::pass_updated_nondim_parameters_to_elements(), StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::reset_global_time_to_zero(), StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::set_initial_condition(), StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::set_perturbed_state_time_equal_to_base_state_time(), and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::StabilityProblem().
First_power_method_iteration
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > bool StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::First_power_method_iteration private
Flag to indicate whether or not we are doing the first iteration of the power method
Referenced by StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::set_first_power_method_iteration_flag_to_false(), and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::set_first_power_method_iteration_flag_to_true().
Perturbed_state_problem_pt
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT > * StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Perturbed_state_problem_pt private
Pointer to perturbed state problem class.
Referenced by StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::close_trace_files(), StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::create_trace_files(), StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::doc_solution(), StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::get_perturbed_state_problem_dofs(), StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::initialise_dt(), StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::initialise_trace_files(), StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::pass_updated_nondim_parameters_to_elements(), StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::perturbed_state_problem_pt(), StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::reset_global_time_to_zero(), StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::set_initial_condition(), StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::set_perturbed_state_time_equal_to_base_state_time(), StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::StabilityProblem(), and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::unsteady_run_for_power_method().
Trace_file_periodic_base_flow
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > ofstream StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Trace_file_periodic_base_flow private
Trace file which documents the convergence of the base flow to a periodic state
Referenced by StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::close_trace_files(), StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::create_trace_files(), and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::initialise_trace_files().
Trace_file_power_method
template<class BASE_ELEMENT , class PERTURBED_ELEMENT > ofstream StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::Trace_file_power_method private
Trace file which documents the convergence of the power method.
Referenced by StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::close_trace_files(), StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::create_trace_files(), and StabilityProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::initialise_trace_files().
The documentation for this class was generated from the following files:
axisym_navier_stokes/counter_rotating_disks/counter_rotating_disks.cc
axisym_navier_stokes/counter_rotating_disks/counter_rotating_disks_ref.cc
time_periodic_taylor_couette.cc