MercuryDPM: ChangingTOI.cpp File Reference
ChangingTOI.cpp File Reference
#include "Mercury3D.h"
#include "Walls/InfiniteWall.h"
#include "Species/LinearViscoelasticFrictionSpecies.h"
#include "Particles/ClumpParticle.h"
#include "../ClumpHeaders/ClumpInput.h"
#include "../ClumpHeaders/Mercury3DClump.h"
#include <stdlib.h>
#include <CMakeDefinitions.h>
#include <memory>
Classes
class ChangingTOIParticle
Functions
std::string ExecCommand (const char *cmd)
Vec3D LoadInitOrient ()
Vec3D LoadFinalOrient ()
Double2DVector LoadIProfiles ()
int main (int argc, char *argv[])
Variables
Mdouble f_min = -10
Mdouble f_max = 10
Function Documentation
ExecCommand()
std::string ExecCommand (const char * cmd)
{
     std::array<char, 256> buffer;
     std::string result;
     // Prepare a pipe to write a to execute a system command and read the result
     std::unique_ptr<FILE, int(*)(FILE*)> pipe(popen(cmd, "r"), pclose);
     if (!pipe) {
         throw std::runtime_error("popen() failed!");
     }
     while (fgets(buffer.data(), buffer.size(), pipe.get()) != nullptr) {
         result += buffer.data();
     }
     return result;
 }
References int(), and oomph::Global_string_for_annotation::string().
Referenced by main().
LoadFinalOrient()
Vec3D LoadFinalOrient ()
 {
     std::cout<<"Read final orientation"<<std::endl;
     // Load final orientation
     std::ifstream infile((getMercuryDPMBuildDir() + "/Drivers/Clump/ChangingTOI/opt/final_orientation.txt").c_str(), std::ios::in | std::ios::binary);
     char lin[256];
     infile.getline(lin, 256, '\n');
     std::string line(lin);
     Mdouble theta = std::stof(line);
     infile.getline(lin, 256, '\n');
     std::string line2(lin);
     Mdouble phi = std::stof(line2);
     infile.close();
     std::cout<<"LOADED FINAL ORIENTATION: theta = "<<theta<<", phi = "<<phi<<std::endl;
     return Vec3D(sin(theta) * cos(phi), sin(theta) * sin(phi), cos(theta));
 }
References cos(), getMercuryDPMBuildDir(), calibrate::line, sin(), oomph::Global_string_for_annotation::string(), and BiharmonicTestFunctions2::theta.
Referenced by main().
LoadInitOrient()
Vec3D LoadInitOrient ()
 {
     std::cout<<"Read init orientation"<<std::endl;
     // Load init orientation
     std::ifstream infile((getMercuryDPMBuildDir() + "/Drivers/Clump/ChangingTOI/opt/init_orientation.txt").c_str(), std::ios::in | std::ios::binary);
     char lin[256];
     infile.getline(lin, 256, '\n');
     std::string line(lin);
     Mdouble theta = std::stof(line);
     infile.getline(lin, 256, '\n');
     std::string line2(lin);
     Mdouble phi = std::stof(line2);
     infile.close();
     return Vec3D(sin(theta) * cos(phi), sin(theta) * sin(phi), cos(theta));
 }
References cos(), getMercuryDPMBuildDir(), calibrate::line, sin(), oomph::Global_string_for_annotation::string(), and BiharmonicTestFunctions2::theta.
Referenced by main().
LoadIProfiles()
Double2DVector LoadIProfiles ()
 {
     std::cout<<"read inertia profile"<<std::endl;
     // Load goal orientation
     std::ifstream infile((getMercuryDPMBuildDir() + "/Drivers/Clump/ChangingTOI/opt/inertia_profiles.txt").c_str(), std::ios::in | std::ios::binary);
     char lin[256];
     Double2DVector i_profiles;
     while (infile.getline(lin, 256, '\n')){
             StringVector val;
             std::string line(lin);
             line+=" ";
             std::string buffer = "";
             for ( int j = 0; j < line.size(); j++){
                 if (line[j] != ' ') {buffer += line[j];}
                 else {val.push_back(buffer); buffer = "";}
             }
             DoubleVector row;
             for (int i = 0; i < 7; i++){ row.push_back(std::stof(val[i])); }
             i_profiles.push_back(row);
         }
         infile.close();
     return i_profiles;
 }
References getMercuryDPMBuildDir(), i, j, calibrate::line, row(), oomph::Global_string_for_annotation::string(), and calibrate::val.
Referenced by main().
main()
int main (int argc , char * argv[])
 {
     ChangingTOIParticle problem;
     problem.init_orientation = LoadInitOrient();
     problem.final_orientation = LoadFinalOrient();
     problem.inertia_profiles = LoadIProfiles();
     // Get parameters passed through the command line
     std::string a;
     problem.progDuration = stod(helpers::readFromCommandLine(argc, argv, "-p1", a));
     problem.symDuration = stod(helpers::readFromCommandLine(argc, argv, "-p2", a));
     problem.baseAngVel = stod(helpers::readFromCommandLine(argc, argv, "-p3", a));
     auto species = problem.speciesHandler.copyAndAddObject(LinearViscoelasticFrictionSpecies());
     species->setDensity(1.0); // sets the species type-0 density
     species->setDissipation(0.0);
     species->setStiffness(1e6);
     const Mdouble collisionTime = species->getCollisionTime(problem.getClumpMass());
     problem.setClumpDamping(0);
     problem.setTimeStep(collisionTime/50 );
     std::cout<<"TIMESTEP: "<< collisionTime/50  << std::endl;
     // Quick demonstration
     problem.setSaveCount(500);
     problem.setTimeMax(problem.symDuration);
     problem.removeOldFiles();
     problem.solve();
     // Paraview data
     ExecCommand("rm -rf paraview_ChangingTOI/");
     ExecCommand("mkdir paraview_ChangingTOI/");
     ExecCommand("../../../Tools/data2pvd ChangingTOI.data paraview_ChangingTOI/ChangingTOI");
     std::string command;
     command = "python " + getMercuryDPMSourceDir() + "/Tools/MClump/PlotEnergies.py " + getMercuryDPMBuildDir() + "/Drivers/Clump/ChangingTOI/ " + "ChangingTOI";
     ExecCommand(command.c_str());
     // Return the functional via the text file
     std::ofstream funct;  funct.open ("opt/functional.txt");
     funct << problem.functional;
     funct.close();
     // Return current angles
     std::ofstream angl;  angl.open ("opt/angles.txt");
     angl << problem.c_theta << std::endl;
     angl << problem.c_phi <<std::endl;
     angl.close();
     // Return the log of the angular momentum
     std::ofstream mom;  mom.open ("opt/momentum.txt");
     for (int i = 0; i<problem.angularMomentumLog.size(); i+=500){mom <<problem.angularMomentumLog[i]<<std::endl;}
     mom.close();
     return 0;
 }
References a, ExecCommand(), getMercuryDPMBuildDir(), getMercuryDPMSourceDir(), i, LoadFinalOrient(), LoadInitOrient(), LoadIProfiles(), problem, helpers::readFromCommandLine(), and oomph::Global_string_for_annotation::string().
Variable Documentation
f_max
Mdouble f_max = 10
Referenced by ChangingTOIParticle::ChangingTOIParticle().
f_min
Mdouble f_min = -10
Referenced by ChangingTOIParticle::ChangingTOIParticle().