MercuryDPM: REVIsotropicCompressionDemo.cpp File Reference
REVIsotropicCompressionDemo.cpp File Reference
#include <Mercury3D.h>
#include <Species/LinearViscoelasticSpecies.h>
#include <Boundaries/StressStrainControlBoundary.h>
#include <Boundaries/CubeInsertionBoundary.h>
Classes
class StressStrainControl
[REV_ISO:headers]
Functions
int main (int argc UNUSED, char *argv[] UNUSED)
[REV_ISO:class]
Function Documentation
main()
int main (int argc UNUSED, char *argv[] UNUSED)
[REV_ISO:class]
[REV_ISO:main]
 {
     //We want strainrate control, so here we set the target Stress to free, all to zero
     Matrix3D stressGoal;
     stressGoal.XX = 0.0;
     stressGoal.YY = 0.0;
     stressGoal.ZZ = 0.0;
     stressGoal.XY = 0.0;
     //Here we set the isotropic strainrate tensor, negative sign means compression
     Matrix3D strainRate;
     strainRate.XX = -0.02;
     strainRate.YY = -0.02;
     strainRate.ZZ = -0.02;
     strainRate.XY = 0.0;
     //This is default gainFactor, if you choose to use stress control, you might want to tune this one
     Matrix3D gainFactor;
     gainFactor.XY = 0.0001;
     gainFactor.XX = 0.0001;
     gainFactor.YY = 0.0001;
     gainFactor.ZZ = 0.0001;
     //This is by default set to true, so particles are controlled by affine movement.
     //If set it to false, then the particles will only follow the boundary movement.
     bool isStrainRateControlled = true;
     //Define the object and problem to solve
     StressStrainControl dpm(stressGoal, strainRate, gainFactor, isStrainRateControlled);
     //Set name
     dpm.setName("Tutorial_IsotropicCompression");
     //Set output and time stepping properties
     dpm.setTimeMax(10);
     //Set the SaveCount, i.e. 100 timesteps saving one snapshot
     dpm.setSaveCount(100);
     //Currently all the normal file outputs are switched off, simply switch it on by replacing NO_FILE to ONE_FILE
 //    dpm.dataFile.setFileType(FileType::NO_FILE);
 //    dpm.restartFile.setFileType(FileType::NO_FILE);
 //    dpm.fStatFile.setFileType(FileType::NO_FILE);
 //    dpm.eneFile.setFileType(FileType::NO_FILE);
     //Set output the particle information in VTK for ParaView Visualisation
     dpm.setParticlesWriteVTK(true);
     //Because of periodic boundary, out put wall files is not necessary in this case
     //dpm.wallHandler.setWriteVTK(true);
     //Solve the problem
     dpm.solve();
 }
References DPMBase::setName(), DPMBase::setParticlesWriteVTK(), DPMBase::setSaveCount(), DPMBase::setTimeMax(), DPMBase::solve(), Matrix3D::XX, Matrix3D::XY, Matrix3D::YY, and Matrix3D::ZZ.