MercuryDPM: Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device > Struct Template Reference
Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device > Struct Template Reference
#include <TensorChipping.h>
Public Types
enum {
IsAligned = false , PacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess , BlockAccess = TensorEvaluator<ArgType, Device>::BlockAccess , IsOuterChipping = (Layout == ColMajor && DimId == NumInputDims - 1) || (Layout == RowMajor && DimId == 0) ,
IsInnerChipping = (Layout == ColMajor && DimId == 0) || (Layout == RowMajor && DimId == NumInputDims - 1) , PreferBlockAccess = TensorEvaluator<ArgType, Device>::PreferBlockAccess || !IsOuterChipping , CoordAccess = false , RawAccess = false
}
typedef TensorChippingOp< DimId, ArgType > XprType
typedef XprType::Index Index
typedef DSizes< Index, NumDims > Dimensions
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef StorageMemory< CoeffReturnType, Device > Storage
typedef Storage::Type EvaluatorPointerType
typedef std::remove_const_t< Scalar > ScalarNoConst
typedef internal::TensorBlockDescriptor< NumDims, Index > TensorBlockDesc
typedef internal::TensorBlockScratchAllocator< Device > TensorBlockScratch
typedef internal::TensorBlockDescriptor< NumInputDims, Index > ArgTensorBlockDesc
typedef TensorEvaluator< const ArgType, Device >::TensorBlock ArgTensorBlock
typedef internal::TensorMaterializedBlock< ScalarNoConst, NumDims, Layout, Index > TensorBlock
Public Member Functions
EIGEN_STRONG_INLINE TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions & dimensions () const
EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (EvaluatorPointerType)
EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType packet (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::TensorBlockResourceRequirements getResourceRequirements () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorBlock block (TensorBlockDesc &desc, TensorBlockScratch &scratch, bool root_of_expr_ast=false) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Storage::Type data () const
Static Public Attributes
static constexpr int NumInputDims
static constexpr int NumDims = NumInputDims - 1
static constexpr int PacketSize = PacketType<CoeffReturnType, Device>::size
static constexpr int Layout = TensorEvaluator<ArgType, Device>::Layout
Protected Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index srcCoeff (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool isInnerChipping () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool isOuterChipping () const
Protected Attributes
Dimensions m_dimensions
Index m_stride
Index m_inputOffset
Index m_inputStride
TensorEvaluator< ArgType, Device > m_impl
const internal::DimensionId< DimId > m_dim
const Device EIGEN_DEVICE_REF m_device
bool m_isEffectivelyInnerChipping
bool m_isEffectivelyOuterChipping
Member Typedef Documentation
ArgTensorBlock
template<DenseIndex DimId, typename ArgType , typename Device > typedef TensorEvaluator<const ArgType, Device>::TensorBlock Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::ArgTensorBlock
ArgTensorBlockDesc
template<DenseIndex DimId, typename ArgType , typename Device > typedef internal::TensorBlockDescriptor<NumInputDims, Index> Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::ArgTensorBlockDesc
CoeffReturnType
template<DenseIndex DimId, typename ArgType , typename Device > typedef XprType::CoeffReturnType Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::CoeffReturnType
Dimensions
template<DenseIndex DimId, typename ArgType , typename Device > typedef DSizes<Index, NumDims> Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::Dimensions
EvaluatorPointerType
template<DenseIndex DimId, typename ArgType , typename Device > typedef Storage::Type Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::EvaluatorPointerType
Index
template<DenseIndex DimId, typename ArgType , typename Device > typedef XprType::Index Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::Index
PacketReturnType
template<DenseIndex DimId, typename ArgType , typename Device > typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::PacketReturnType
Scalar
template<DenseIndex DimId, typename ArgType , typename Device > typedef XprType::Scalar Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::Scalar
ScalarNoConst
template<DenseIndex DimId, typename ArgType , typename Device > typedef std::remove_const_t<Scalar> Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::ScalarNoConst
Storage
template<DenseIndex DimId, typename ArgType , typename Device > typedef StorageMemory<CoeffReturnType, Device> Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::Storage
TensorBlock
template<DenseIndex DimId, typename ArgType , typename Device > typedef internal::TensorMaterializedBlock<ScalarNoConst, NumDims, Layout, Index> Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::TensorBlock
TensorBlockDesc
template<DenseIndex DimId, typename ArgType , typename Device > typedef internal::TensorBlockDescriptor<NumDims, Index> Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::TensorBlockDesc
TensorBlockScratch
template<DenseIndex DimId, typename ArgType , typename Device > typedef internal::TensorBlockScratchAllocator<Device> Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::TensorBlockScratch
XprType
template<DenseIndex DimId, typename ArgType , typename Device > typedef TensorChippingOp<DimId, ArgType> Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::XprType
Member Enumeration Documentation
anonymous enum
template<DenseIndex DimId, typename ArgType , typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
BlockAccess
IsOuterChipping
IsInnerChipping
PreferBlockAccess
CoordAccess
RawAccess
        {
     // Alignment can't be guaranteed at compile time since it depends on the
     // slice offsets.
     IsAligned = false,
     PacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess,
     BlockAccess = TensorEvaluator<ArgType, Device>::BlockAccess,
     // Chipping of outer-most dimension is a trivial operation, because we can
     // read and write directly from the underlying tensor using single offset.
     IsOuterChipping = (Layout == ColMajor && DimId == NumInputDims - 1) || (Layout == RowMajor && DimId == 0),
     // Chipping inner-most dimension.
     IsInnerChipping = (Layout == ColMajor && DimId == 0) || (Layout == RowMajor && DimId == NumInputDims - 1),
     // Prefer block access if the underlying expression prefers it, otherwise
     // only if chipping is not trivial.
     PreferBlockAccess = TensorEvaluator<ArgType, Device>::PreferBlockAccess || !IsOuterChipping,
     CoordAccess = false,  // to be implemented
     RawAccess = false
   };
Constructor & Destructor Documentation
TensorEvaluator()
template<DenseIndex DimId, typename ArgType , typename Device > EIGEN_STRONG_INLINE Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::TensorEvaluator (const XprType & op, const Device & device) inline
       : m_impl(op.expression(), device), m_dim(op.dim()), m_device(device) {
     EIGEN_STATIC_ASSERT((NumInputDims >= 1), YOU_MADE_A_PROGRAMMING_MISTAKE);
     eigen_assert(NumInputDims > m_dim.actualDim());
     const typename TensorEvaluator<ArgType, Device>::Dimensions& input_dims = m_impl.dimensions();
     eigen_assert(op.offset() < input_dims[m_dim.actualDim()]);
     int j = 0;
     for (int i = 0; i < NumInputDims; ++i) {
       if (i != m_dim.actualDim()) {
         m_dimensions[j] = input_dims[i];
         ++j;
       }
     }
     m_stride = 1;
     m_inputStride = 1;
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       for (int i = 0; i < m_dim.actualDim(); ++i) {
         m_stride *= input_dims[i];
         m_inputStride *= input_dims[i];
       }
     } else {
       for (int i = NumInputDims - 1; i > m_dim.actualDim(); --i) {
         m_stride *= input_dims[i];
         m_inputStride *= input_dims[i];
       }
     }
     m_inputStride *= input_dims[m_dim.actualDim()];
     m_inputOffset = m_stride * op.offset();
     // Check if chipping is effectively inner or outer: products of dimensions
     // before or after the chipped dimension is `1`.
     Index after_chipped_dim_product = 1;
     for (int i = static_cast<int>(m_dim.actualDim()) + 1; i < NumInputDims; ++i) {
       after_chipped_dim_product *= input_dims[i];
     }
     Index before_chipped_dim_product = 1;
     for (int i = 0; i < m_dim.actualDim(); ++i) {
       before_chipped_dim_product *= input_dims[i];
     }
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       m_isEffectivelyInnerChipping = before_chipped_dim_product == 1;
       m_isEffectivelyOuterChipping = after_chipped_dim_product == 1;
     } else {
       m_isEffectivelyInnerChipping = after_chipped_dim_product == 1;
       m_isEffectivelyOuterChipping = before_chipped_dim_product == 1;
     }
   }
References Eigen::ColMajor, Eigen::TensorEvaluator< Derived, Device >::dimensions(), eigen_assert, EIGEN_STATIC_ASSERT, i, j, Eigen::TensorEvaluator< Derived, Device >::Layout, and op.
Member Function Documentation
block()
template<DenseIndex DimId, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorBlock Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::block (TensorBlockDesc & desc, TensorBlockScratch & scratch, bool root_of_expr_ast = false) const inline
{
     const Index chip_dim = m_dim.actualDim();
     DSizes<Index, NumInputDims> input_block_dims;
     for (int i = 0; i < NumInputDims; ++i) {
       input_block_dims[i] = i < chip_dim ? desc.dimension(i) : i > chip_dim ? desc.dimension(i - 1) : 1;
     }
     ArgTensorBlockDesc arg_desc(srcCoeff(desc.offset()), input_block_dims);
     // Try to reuse destination buffer for materializing argument block.
     if (desc.HasDestinationBuffer()) {
       DSizes<Index, NumInputDims> arg_destination_strides;
       for (int i = 0; i < NumInputDims; ++i) {
         arg_destination_strides[i] = i < chip_dim   ? desc.destination().strides()[i]
                                      : i > chip_dim ? desc.destination().strides()[i - 1]
                                                     : 0;  // for dimensions of size `1` stride should never be used.
       }
       arg_desc.template AddDestinationBuffer<Layout>(desc.destination().template data<ScalarNoConst>(),
                                                      arg_destination_strides);
     }
     ArgTensorBlock arg_block = m_impl.block(arg_desc, scratch, root_of_expr_ast);
     if (!arg_desc.HasDestinationBuffer()) desc.DropDestinationBuffer();
     if (arg_block.data() != NULL) {
       // Forward argument block buffer if possible.
       return TensorBlock(arg_block.kind(), arg_block.data(), desc.dimensions());
     } else {
       // Assign argument block expression to a buffer.
       // Prepare storage for the materialized chipping result.
       const typename TensorBlock::Storage block_storage = TensorBlock::prepareStorage(desc, scratch);
       typedef internal::TensorBlockAssignment<ScalarNoConst, NumInputDims, typename ArgTensorBlock::XprType, Index>
           TensorBlockAssignment;
       TensorBlockAssignment::Run(
           TensorBlockAssignment::target(arg_desc.dimensions(), internal::strides<Layout>(arg_desc.dimensions()),
                                         block_storage.data()),
           arg_block.expr());
       return block_storage.AsTensorMaterializedBlock();
     }
   }
References Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::Storage::AsTensorMaterializedBlock(), Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::data(), Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::Storage::data(), Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::destination(), Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::dimension(), Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::dimensions(), Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::DropDestinationBuffer(), Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::expr(), Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::HasDestinationBuffer(), i, Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::kind(), Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::offset(), and Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::prepareStorage().
cleanup()
template<DenseIndex DimId, typename ArgType , typename Device > EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::cleanup () inline
 { m_impl.cleanup(); }
Referenced by framework.Frame::__init__().
coeff()
template<DenseIndex DimId, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::coeff (Index index) const inline
{
     return m_impl.coeff(srcCoeff(index));
   }
costPerCoeff()
template<DenseIndex DimId, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::costPerCoeff (bool vectorized) const inline
{
     double cost = 0;
     if ((static_cast<int>(Layout) == static_cast<int>(ColMajor) && m_dim.actualDim() == 0) ||
         (static_cast<int>(Layout) == static_cast<int>(RowMajor) && m_dim.actualDim() == NumInputDims - 1)) {
       cost += TensorOpCost::MulCost<Index>() + TensorOpCost::AddCost<Index>();
     } else if ((static_cast<int>(Layout) == static_cast<int>(ColMajor) && m_dim.actualDim() == NumInputDims - 1) ||
                (static_cast<int>(Layout) == static_cast<int>(RowMajor) && m_dim.actualDim() == 0)) {
       cost += TensorOpCost::AddCost<Index>();
     } else {
       cost += 3 * TensorOpCost::MulCost<Index>() + TensorOpCost::DivCost<Index>() + 3 * TensorOpCost::AddCost<Index>();
     }
     return m_impl.costPerCoeff(vectorized) + TensorOpCost(0, 0, cost, vectorized, PacketSize);
   }
References Eigen::ColMajor, Eigen::TensorEvaluator< Derived, Device >::Layout, Eigen::TensorEvaluator< Derived, Device >::PacketSize, and Eigen::RowMajor.
data()
template<DenseIndex DimId, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Storage::Type Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::data () const inline
{
     typename Storage::Type result = constCast(m_impl.data());
     if (isOuterChipping() && result) {
       return result + m_inputOffset;
     } else {
       return NULL;
     }
   }
References Eigen::constCast().
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
dimensions()
template<DenseIndex DimId, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions& Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::dimensions () const inline
 { return m_dimensions; }
evalSubExprsIfNeeded()
template<DenseIndex DimId, typename ArgType , typename Device > EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::evalSubExprsIfNeeded (EvaluatorPointerType) inline
{
     m_impl.evalSubExprsIfNeeded(NULL);
     return true;
   }
getResourceRequirements()
template<DenseIndex DimId, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::TensorBlockResourceRequirements Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::getResourceRequirements () const inline
{
     const size_t target_size = m_device.lastLevelCacheSize();
     return internal::TensorBlockResourceRequirements::merge(
         internal::TensorBlockResourceRequirements::skewed<Scalar>(target_size), m_impl.getResourceRequirements());
   }
References Eigen::TensorEvaluator< Derived, Device >::m_device, and Eigen::internal::TensorBlockResourceRequirements::merge().
isInnerChipping()
template<DenseIndex DimId, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::isInnerChipping () const inline protected
{
     return IsInnerChipping || m_isEffectivelyInnerChipping;
   }
isOuterChipping()
template<DenseIndex DimId, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::isOuterChipping () const inline protected
{
     return IsOuterChipping || m_isEffectivelyOuterChipping;
   }
packet()
template<DenseIndex DimId, typename ArgType , typename Device > template<int LoadMode> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::packet (Index index) const inline
{
     eigen_assert(index + PacketSize - 1 < dimensions().TotalSize());
     if (isInnerChipping()) {
       // m_stride is equal to 1, so let's avoid the integer division.
       eigen_assert(m_stride == 1);
       Index inputIndex = index * m_inputStride + m_inputOffset;
       EIGEN_ALIGN_MAX std::remove_const_t<CoeffReturnType> values[PacketSize];
       EIGEN_UNROLL_LOOP
       for (int i = 0; i < PacketSize; ++i) {
         values[i] = m_impl.coeff(inputIndex);
         inputIndex += m_inputStride;
       }
       PacketReturnType rslt = internal::pload<PacketReturnType>(values);
       return rslt;
     } else if (isOuterChipping()) {
       // m_stride is always greater than index, so let's avoid the integer division.
       eigen_assert(m_stride > index);
       return m_impl.template packet<LoadMode>(index + m_inputOffset);
     } else {
       const Index idx = index / m_stride;
       const Index rem = index - idx * m_stride;
       if (rem + PacketSize <= m_stride) {
         Index inputIndex = idx * m_inputStride + m_inputOffset + rem;
         return m_impl.template packet<LoadMode>(inputIndex);
       } else {
         // Cross the stride boundary. Fallback to slow path.
         EIGEN_ALIGN_MAX std::remove_const_t<CoeffReturnType> values[PacketSize];
         EIGEN_UNROLL_LOOP
         for (int i = 0; i < PacketSize; ++i) {
           values[i] = coeff(index);
           ++index;
         }
         PacketReturnType rslt = internal::pload<PacketReturnType>(values);
         return rslt;
       }
     }
   }
References Eigen::TensorEvaluator< Derived, Device >::coeff(), Eigen::TensorEvaluator< Derived, Device >::dimensions(), EIGEN_ALIGN_MAX, eigen_assert, EIGEN_UNROLL_LOOP, i, and Eigen::TensorEvaluator< Derived, Device >::PacketSize.
srcCoeff()
template<DenseIndex DimId, typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::srcCoeff (Index index) const inline protected
{
     Index inputIndex;
     if (isInnerChipping()) {
       // m_stride is equal to 1, so let's avoid the integer division.
       eigen_assert(m_stride == 1);
       inputIndex = index * m_inputStride + m_inputOffset;
     } else if (isOuterChipping()) {
       // m_stride is always greater than index, so let's avoid the integer
       // division.
       eigen_assert(m_stride > index);
       inputIndex = index + m_inputOffset;
     } else {
       const Index idx = index / m_stride;
       inputIndex = idx * m_inputStride + m_inputOffset;
       index -= idx * m_stride;
       inputIndex += index;
     }
     return inputIndex;
   }
References eigen_assert.
Member Data Documentation
Layout
template<DenseIndex DimId, typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::Layout = TensorEvaluator<ArgType, Device>::Layout static constexpr
m_device
template<DenseIndex DimId, typename ArgType , typename Device > const Device EIGEN_DEVICE_REF Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::m_device protected
m_dim
template<DenseIndex DimId, typename ArgType , typename Device > const internal::DimensionId<DimId> Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::m_dim protected
m_dimensions
template<DenseIndex DimId, typename ArgType , typename Device > Dimensions Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::m_dimensions protected
m_impl
template<DenseIndex DimId, typename ArgType , typename Device > TensorEvaluator<ArgType, Device> Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::m_impl protected
m_inputOffset
template<DenseIndex DimId, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::m_inputOffset protected
m_inputStride
template<DenseIndex DimId, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::m_inputStride protected
m_isEffectivelyInnerChipping
template<DenseIndex DimId, typename ArgType , typename Device > bool Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::m_isEffectivelyInnerChipping protected
m_isEffectivelyOuterChipping
template<DenseIndex DimId, typename ArgType , typename Device > bool Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::m_isEffectivelyOuterChipping protected
m_stride
template<DenseIndex DimId, typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::m_stride protected
NumDims
template<DenseIndex DimId, typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::NumDims = NumInputDims - 1 static constexpr
NumInputDims
template<DenseIndex DimId, typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::NumInputDims static constexpr
Initial value:
=
      internal::array_size<typename TensorEvaluator<ArgType, Device>::Dimensions>::value
PacketSize
template<DenseIndex DimId, typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorChippingOp< DimId, ArgType >, Device >::PacketSize = PacketType<CoeffReturnType, Device>::size static constexpr
The documentation for this struct was generated from the following file:
TensorChipping.h