MercuryDPM: TwoParticleElasticCollisionInteractionWithLiquidMigrationLSSelfTest.cpp File Reference
TwoParticleElasticCollisionInteractionWithLiquidMigrationLSSelfTest.cpp File Reference
#include "Mercury2D.h"
#include "Walls/InfiniteWall.h"
#include "Species/Species.h"
#include "Particles/LiquidFilmParticle.h"
#include "Species/LinearViscoelasticFrictionLiquidMigrationLSSpecies.h"
Classes
class TwoParticleElasticCollisionInteraction
In this file two particles are symmetrically placed in a bi-axial box are allowed to jump around under gravity. It tests walls gravity and symmetry.
Functions
int main (int argc UNUSED, char *argv[] UNUSED)
Function Documentation
main()
int main (int argc UNUSED, char *argv[] UNUSED)
 {
     TwoParticleElasticCollisionInteraction twoParticleElasticCollisionInteractionProblem;
     twoParticleElasticCollisionInteractionProblem.setName("TwoParticleElasticCollisionInteractionwithLiquidMigrationLSSelfTest");
     twoParticleElasticCollisionInteractionProblem.radius = 0.0002;
     twoParticleElasticCollisionInteractionProblem.setTimeMax(0.05);
     twoParticleElasticCollisionInteractionProblem.setSaveCount(10);
     twoParticleElasticCollisionInteractionProblem.setTimeStep(1e-5);
     twoParticleElasticCollisionInteractionProblem.fStatFile.setFileType(FileType::ONE_FILE);
     twoParticleElasticCollisionInteractionProblem.getInteractionFile().setFileType(FileType::ONE_FILE);
     twoParticleElasticCollisionInteractionProblem.setParticlesWriteVTK(true);
     twoParticleElasticCollisionInteractionProblem.interactionHandler.setWriteVTK(true);
     twoParticleElasticCollisionInteractionProblem.wallHandler.setWriteVTK(FileType::ONE_FILE);
     twoParticleElasticCollisionInteractionProblem.solve();
 }
References e(), DPMBase::fStatFile, DPMBase::getInteractionFile(), DPMBase::interactionHandler, ONE_FILE, TwoParticleElasticCollisionInteraction::radius, File::setFileType(), DPMBase::setName(), DPMBase::setParticlesWriteVTK(), DPMBase::setSaveCount(), DPMBase::setTimeMax(), DPMBase::setTimeStep(), InteractionHandler::setWriteVTK(), WallHandler::setWriteVTK(), DPMBase::solve(), and DPMBase::wallHandler.