MercuryDPM: oomph::AlgebraicMesh Class Reference
oomph::AlgebraicMesh Class Reference abstract
#include <algebraic_elements.h>
Public Member Functions
AlgebraicMesh ()
AlgebraicMesh (const AlgebraicMesh &)=delete
Broken copy constructor.
~AlgebraicMesh ()
Broken assignment operator.
AlgebraicNode * node_pt (const unsigned long &n)
Return a pointer to the n-th global AlgebraicNode.
virtual void algebraic_node_update (const unsigned &t, AlgebraicNode *&node_pt)=0
virtual void update_node_update (AlgebraicNode *&node_pt)=0
void node_update (const bool &update_all_solid_nodes=false)
unsigned self_test ()
Self test: check consistentency of multiple node updates.
void add_geom_object_list_pt (GeomObject *geom_object_pt)
unsigned ngeom_object_list_pt ()
Return number of geometric objects associated with AlgebraicMesh.
GeomObject * geom_object_list_pt (const unsigned &i)
Access function to the ith GeomObject.
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void setup_boundary_element_info ()
virtual void setup_boundary_element_info (std::ostream &outfile)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Private Attributes
Vector< GeomObject * > Geom_object_list_pt
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Detailed Description
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// Algebraic meshes contain AlgebraicElements and AlgebraicNodes. They implement the node update functions that are used by the AlgebraicNodes to update their positions.
Constructor & Destructor Documentation
AlgebraicMesh() [1/2]
oomph::AlgebraicMesh::AlgebraicMesh () inline
Constructor: create a null zeroth entry in the Geom_object_list_pt Vector (each AlgebraicMesh's constructor should add any other geometric objects to this list)
     {
       add_geom_object_list_pt(0);
     }
References add_geom_object_list_pt().
AlgebraicMesh() [2/2]
oomph::AlgebraicMesh::AlgebraicMesh (const AlgebraicMesh &) delete
Broken copy constructor.
~AlgebraicMesh()
oomph::AlgebraicMesh::~AlgebraicMesh () inline
Broken assignment operator.
Surely a proper destructor is required... ?
 {}
Member Function Documentation
add_geom_object_list_pt()
void oomph::AlgebraicMesh::add_geom_object_list_pt (GeomObject * geom_object_pt) inline
Add the specified GeomObject to the list of geometric objects associated with this AlgebraicMesh; remembering that the zeroth entry is null (set in the constructor above)
     {
       Geom_object_list_pt.push_back(geom_object_pt);
     }
References Geom_object_list_pt.
Referenced by oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::AlgebraicChannelWithLeafletMesh(), oomph::AlgebraicCollapsibleChannelMesh< ELEMENT >::AlgebraicCollapsibleChannelMesh(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::AlgebraicCylinderWithFlagMesh(), oomph::AlgebraicFishMesh< ELEMENT >::AlgebraicFishMesh(), oomph::AlgebraicFSIDrivenCavityMesh< ELEMENT >::AlgebraicFSIDrivenCavityMesh(), AlgebraicMesh(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::AlgebraicRefineableQuarterCircleSectorMesh(), and oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::AlgebraicRefineableQuarterTubeMesh().
algebraic_node_update()
virtual void oomph::AlgebraicMesh::algebraic_node_update (const unsigned & t, AlgebraicNode *& node_pt) pure virtual
Update the nodal position posn at time level t (t=0: present; t>0: previous). Must be implemented for every specific algebraic mesh.
Implemented in oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >, oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >, oomph::AlgebraicRefineableQuarterCircleSectorMesh< FLUID_ELEMENT >, oomph::AlgebraicFSIDrivenCavityMesh< ELEMENT >, oomph::AlgebraicFishMesh< ELEMENT >, oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >, oomph::AlgebraicCollapsibleChannelMesh< ELEMENT >, oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >, oomph::DummyAlgebraicMesh, and oomph::MyAlgebraicCollapsibleChannelMesh< ELEMENT >.
Referenced by oomph::AlgebraicNode::node_update().
geom_object_list_pt()
GeomObject* oomph::AlgebraicMesh::geom_object_list_pt (const unsigned & i) inline
Access function to the ith GeomObject.
     {
       // Probably should be a range check in here...
       return Geom_object_list_pt[i];
     }
References Geom_object_list_pt, and i.
ngeom_object_list_pt()
unsigned oomph::AlgebraicMesh::ngeom_object_list_pt () inline
Return number of geometric objects associated with AlgebraicMesh.
     {
       return Geom_object_list_pt.size();
     }
References Geom_object_list_pt.
node_pt()
AlgebraicNode* oomph::AlgebraicMesh::node_pt (const unsigned long & n) inline
Return a pointer to the n-th global AlgebraicNode.
     {
 #ifdef PARANOID
       if (!dynamic_cast<AlgebraicNode*>(Node_pt[n]))
       {
         std::ostringstream error_stream;
         error_stream << "Error: Node " << n << "is a "
                      << typeid(Node_pt[n]).name() << ", not an AlgebraicNode"
                      << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // Return a cast to the Node_pt
       return (dynamic_cast<AlgebraicNode*>(Node_pt[n]));
     }
References n, plotDoE::name, oomph::Mesh::Node_pt, OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::AlgebraicFishMesh< ELEMENT >::algebraic_node_update(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::algebraic_node_update(), oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::algebraic_node_update(), node_update(), self_test(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::TurekProblem(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::update_node_update(), and oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::update_node_update().
node_update()
void oomph::AlgebraicMesh::node_update (const bool & update_all_solid_nodes = false) inline virtual
Update all nodal positions via algebraic node update functions [Doesn't make sense to use this mesh with SolidElements anyway, so we buffer the case if update_all_solid_nodes is set to true.]
Reimplemented from oomph::Mesh.
Reimplemented in oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >, oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >, oomph::AlgebraicRefineableQuarterCircleSectorMesh< FLUID_ELEMENT >, oomph::AlgebraicRefineableFishMesh< ELEMENT >, and oomph::AlgebraicFishMesh< ELEMENT >.
     {
 #ifdef PARANOID
       if (update_all_solid_nodes)
       {
         std::string error_message =
           "Doesn't make sense to use an AlgebraicMesh with\n";
         error_message +=
           "SolidElements so specifying update_all_solid_nodes=true\n";
         error_message += "doesn't make sense either\n";
         throw OomphLibError(
           error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // Initial loop over ALL nodes to setup (need to place at least
       // all master nodes before we can update the position of the
       // hanging ones)
       AlgebraicNode* alg_nod_pt = 0;
       unsigned n_node = nnode();
       // In parallel there may be no nodes on a particular process
       if (n_node > 0)
       {
         for (unsigned n = 0; n < n_node; n++)
         {
           alg_nod_pt = static_cast<AlgebraicNode*>(node_pt(n));
           alg_nod_pt->node_update();
         }
         // Figure out spatial dimension of node
         unsigned n_dim = alg_nod_pt->ndim();
         // Now loop over hanging nodes and adjust their nodal positions
         // to reflect the hanging node constraints
         for (unsigned n = 0; n < n_node; n++)
         {
           Node* nod_pt = node_pt(n);
           if (nod_pt->is_hanging())
           {
             // Initialise
             Vector<double> x(n_dim);
             for (unsigned i = 0; i < n_dim; i++)
             {
               x[i] = 0.0;
             }
             // Loop over master nodes
             unsigned nmaster = nod_pt->hanging_pt()->nmaster();
             for (unsigned imaster = 0; imaster < nmaster; imaster++)
             {
               // Loop over directions
               for (unsigned i = 0; i < n_dim; i++)
               {
                 x[i] += nod_pt->hanging_pt()->master_node_pt(imaster)->x(i) *
                         nod_pt->hanging_pt()->master_weight(imaster);
               }
             }
             // Copy across
             for (unsigned i = 0; i < n_dim; i++)
             {
               nod_pt->x(i) = x[i];
             }
             nod_pt->perform_auxiliary_node_update_fct();
           }
         }
       } // end if (n_node>0)
 #ifdef OOMPH_HAS_MPI
       // Update positions for external halo nodes attached to this mesh
       // Loop over processors
       for (std::map<unsigned, Vector<Node*>>::iterator it =
              External_halo_node_pt.begin();
            it != External_halo_node_pt.end();
            it++)
       {
         int iproc = (*it).first;
         AlgebraicNode* alg_nod_pt = 0;
         unsigned n_ext_halo_node = nexternal_halo_node(iproc);
         // Only act if there are any external halo nodes
         if (n_ext_halo_node > 0)
         {
           for (unsigned n = 0; n < n_ext_halo_node; n++)
           {
             alg_nod_pt =
               static_cast<AlgebraicNode*>(external_halo_node_pt(iproc, n));
             alg_nod_pt->node_update();
           }
           // Figure out spatial dimension of node
           unsigned n_dim = alg_nod_pt->ndim();
           // Now loop over hanging nodes and adjust their nodal positions
           // to reflect the hanging node constraints
           for (unsigned n = 0; n < n_ext_halo_node; n++)
           {
             Node* nod_pt = external_halo_node_pt(iproc, n);
             if (nod_pt->is_hanging())
             {
               // Initialise
               Vector<double> x(n_dim);
               for (unsigned i = 0; i < n_dim; i++)
               {
                 x[i] = 0.0;
               }
               // Loop over master nodes
               unsigned nmaster = nod_pt->hanging_pt()->nmaster();
               for (unsigned imaster = 0; imaster < nmaster; imaster++)
               {
                 // Loop over directions
                 for (unsigned i = 0; i < n_dim; i++)
                 {
                   x[i] += nod_pt->hanging_pt()->master_node_pt(imaster)->x(i) *
                           nod_pt->hanging_pt()->master_weight(imaster);
                 }
               }
               // Copy across
               for (unsigned i = 0; i < n_dim; i++)
               {
                 nod_pt->x(i) = x[i];
               }
             }
           }
         }
       } // end loop over processors
 #endif
     }
References oomph::Node::hanging_pt(), i, oomph::Node::is_hanging(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), n, oomph::Node::ndim(), oomph::HangInfo::nmaster(), oomph::Mesh::nnode(), node_pt(), oomph::AlgebraicNode::node_update(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::Node::perform_auxiliary_node_update_fct(), oomph::Global_string_for_annotation::string(), plotDoE::x, and oomph::Node::x().
Referenced by oomph::AlgebraicFishMesh< ELEMENT >::node_update(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::node_update(), and oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::node_update().
self_test()
unsigned oomph::AlgebraicMesh::self_test () inline
Self test: check consistentency of multiple node updates.
     {
       // Initialise
       bool passed = true;
       unsigned test = Mesh::self_test();
       if (test != 0)
       {
         passed = false;
       }
       // Loop over nodes
       unsigned n_node = nnode();
       for (unsigned n = 0; n < n_node; n++)
       {
         if (static_cast<AlgebraicNode*>(node_pt(n))->self_test() != 0)
         {
           passed = false;
         }
       }
       oomph_info << "Done algnode selftest in mesh" << std::endl;
       // Return verdict
       if (passed)
       {
         return 0;
       }
       else
       {
         return 1;
       }
     }
References n, oomph::Mesh::nnode(), node_pt(), oomph::oomph_info, and oomph::Mesh::self_test().
Referenced by oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >::self_test(), and oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::self_test().
update_node_update()
virtual void oomph::AlgebraicMesh::update_node_update (AlgebraicNode *& node_pt) pure virtual
Update the node update info for given node, following mesh adaptation. Must be implemented for every specific algebraic mesh, though it may, of course, be left empty.
Implemented in oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >, oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >, oomph::AlgebraicRefineableQuarterCircleSectorMesh< FLUID_ELEMENT >, oomph::RefineableAlgebraicFSIDrivenCavityMesh< ELEMENT >, oomph::AlgebraicFSIDrivenCavityMesh< ELEMENT >, oomph::AlgebraicFishMesh< ELEMENT >, oomph::RefineableAlgebraicCylinderWithFlagMesh< ELEMENT >, oomph::RefineableAlgebraicCylinderWithFlagMesh< FLUID_ELEMENT >, oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >, oomph::RefineableAlgebraicCollapsibleChannelMesh< ELEMENT >, oomph::AlgebraicCollapsibleChannelMesh< ELEMENT >, oomph::RefineableAlgebraicChannelWithLeafletMesh< ELEMENT >, oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >, oomph::DummyAlgebraicMesh, and oomph::MyAlgebraicCollapsibleChannelMesh< ELEMENT >.
Referenced by oomph::AlgebraicElementBase::setup_algebraic_node_update().
Member Data Documentation
Geom_object_list_pt
Vector<GeomObject*> oomph::AlgebraicMesh::Geom_object_list_pt private
Vector of GeomObjects associated with this AlgebraicMesh The zeroth entry is null, proper entries from the 1st index onwards...
Referenced by add_geom_object_list_pt(), geom_object_list_pt(), and ngeom_object_list_pt().
The documentation for this class was generated from the following file:
algebraic_elements.h