MercuryDPM: ExactSolution Namespace Reference
ExactSolution Namespace Reference
Namespace for exact solution.
Functions
void get_exact_u_for_unsteady_heat_validation (const double &t, const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void get_exact_u_for_unsteady_heat_validation (const double &t, const Vector< double > &x, double &u)
Exact solution as a scalar.
void get_source_for_unsteady_heat_validation (const double &t, const Vector< double > &x, double &source)
Source function to make it an exact solution.
double melting_surface_height (const double &t, const double &x)
Height of melting surface.
void analytical_outer_unit_normal (const double &t, const Vector< double > &x, double &nx, double &ny)
Analytical outer unit normal.
void flux_into_bulk (const double &t, const Vector< double > &x, const Vector< double > &n, const double &u, double &flux)
void prescribed_flux_for_unsteady_heat_validation (const double &t, const Vector< double > &x, const Vector< double > &n, const double &u, double &flux)
void rigid_body_rotation (const Vector< double > &x, Vector< double > &u)
The rigid-body rotation solution.
void rigid_body_rotation_dr (const Vector< double > &x, Vector< double > &u)
The r-derivative of the rigid-body rotation solution.
void rigid_body_rotation_dtheta (const Vector< double > &x, Vector< double > &u)
The theta-derivative of the rigid-body rotation solution.
Variables
double U0 =0.0
Constant/initial temperature.
double Growth_rate =1.0
Growth rate for interface.
bool Use_analytical_outer_unit_normal =true
Use analytical outer unit normal when computing fluxes?
double Omega_cos =0.0
Detailed Description
Namespace for exact solution.
Namespace for the exact rigid-body-rotation solution.
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Function Documentation
analytical_outer_unit_normal()
void ExactSolution::analytical_outer_unit_normal (const double & t, const Vector< double > & x, double & nx, double & ny)
Analytical outer unit normal.
  {
   double X=x[0];
   double t0=0.0;
       t0 = 2.0*Growth_rate*t*t*sin(2.0*X*0.3141592653589793E1)*
 0.3141592653589793E1/sqrt(1.0+4.0*Growth_rate*Growth_rate*t*t*t*t*pow(sin(2.0*X
 *0.3141592653589793E1),2.0)*0.3141592653589793E1*0.3141592653589793E1);
       nx=t0;
       t0 = 1/(sqrt(1.0+4.0*Growth_rate*Growth_rate*t*t*t*t*pow(sin(2.0*X*
 0.3141592653589793E1),2.0)*0.3141592653589793E1*0.3141592653589793E1));
       ny=t0;
  }
References Growth_rate, Mesh_Parameters::nx, Mesh_Parameters::ny, Eigen::bfloat16_impl::pow(), sin(), sqrt(), plotPSD::t, plotDoE::x, and X.
Referenced by flux_into_bulk().
flux_into_bulk()
void ExactSolution::flux_into_bulk (const double & t, const Vector< double > & x, const Vector< double > & n, const double & u, double & flux)
Flux into bulk required by the exact solution on a boundary with outer unit normal n. No dependence on temperature u.
  {
   double X=x[0];
   double Y=x[1];
   //The outer unit normal
   double Nx =  n[0];
   double Ny =  n[1];
   // Use analytical outer unit normal?
   if (Use_analytical_outer_unit_normal)
    {
     analytical_outer_unit_normal(t,x,Nx,Ny);
     Y=melting_surface_height(t,x[0]);
    }
   //The flux in terms of the normal is
   flux=(2.0*t*t*t*t*Y*Y*Growth_rate*sin(2.0*X*0.3141592653589793E1)*
 0.3141592653589793E1*cos(2.0*X*0.3141592653589793E1)-2.0*t*t*Y*Y*(Y-1.0+
 Growth_rate*t*t*(1.0-cos(2.0*X*0.3141592653589793E1)))*sin(2.0*X*
 0.3141592653589793E1)*0.3141592653589793E1)*Nx+(2.0*t*t*Y*(Y-1.0+Growth_rate*t*
 t*(1.0-cos(2.0*X*0.3141592653589793E1)))*cos(2.0*X*0.3141592653589793E1)+t*t*Y*
 Y*cos(2.0*X*0.3141592653589793E1))*Ny;
  }
References analytical_outer_unit_normal(), cos(), ProblemParameters::flux(), Growth_rate, melting_surface_height(), n, GlobalParameters::Nx, GlobalParameters::Ny, sin(), plotPSD::t, Use_analytical_outer_unit_normal, plotDoE::x, X, and Y.
Referenced by MeltContactProblem< ELEMENT >::complete_problem_setup(), and prescribed_flux_for_unsteady_heat_validation().
get_exact_u_for_unsteady_heat_validation() [1/2]
void ExactSolution::get_exact_u_for_unsteady_heat_validation (const double & t, const Vector< double > & x, double & u)
Exact solution as a scalar.
  {
   Vector<double> u_vect(1);
   get_exact_u_for_unsteady_heat_validation(t,x,u_vect);
   u=u_vect[0];
  }
References plotPSD::t, and plotDoE::x.
get_exact_u_for_unsteady_heat_validation() [2/2]
void ExactSolution::get_exact_u_for_unsteady_heat_validation (const double & t, const Vector< double > & x, Vector< double > & u)
Exact solution as a Vector.
  {
   double X=x[0];
   double Y=x[1];
   u[0]=U0+t*t*Y*Y*(Y-1.0+Growth_rate*t*t*(1.0-cos(2.0*X*
 0.3141592653589793E1)))*cos(2.0*X*0.3141592653589793E1);
  }
References cos(), Growth_rate, plotPSD::t, U0, plotDoE::x, X, and Y.
Referenced by MeltContactProblem< ELEMENT >::doc_solution(), SolarRadiationProblem< ELEMENT >::doc_solution(), and UnsteadyHeatMeltProblem< ELEMENT >::doc_solution().
get_source_for_unsteady_heat_validation()
void ExactSolution::get_source_for_unsteady_heat_validation (const double & t, const Vector< double > & x, double & source)
Source function to make it an exact solution.
  {
   double X=x[0];
   double Y=x[1];
   source = -2.0*t*Y*Y*(Y-1.0+Growth_rate*t*t*(1.0-cos(2.0*X*
 0.3141592653589793E1)))*cos(2.0*X*0.3141592653589793E1)-2.0*t*t*t*Y*Y*
 Growth_rate*(1.0-cos(2.0*X*0.3141592653589793E1))*cos(2.0*X*
 0.3141592653589793E1)+4.0*t*t*t*t*Y*Y*Growth_rate*pow(cos(2.0*X*
 0.3141592653589793E1),2.0)*0.3141592653589793E1*0.3141592653589793E1-8.0*t*t*t*
 t*Y*Y*Growth_rate*pow(sin(2.0*X*0.3141592653589793E1),2.0)*0.3141592653589793E1
 *0.3141592653589793E1-4.0*t*t*Y*Y*(Y-1.0+Growth_rate*t*t*(1.0-cos(2.0*X*
 0.3141592653589793E1)))*cos(2.0*X*0.3141592653589793E1)*0.3141592653589793E1*
 0.3141592653589793E1+2.0*t*t*(Y-1.0+Growth_rate*t*t*(1.0-cos(2.0*X*
 0.3141592653589793E1)))*cos(2.0*X*0.3141592653589793E1)+4.0*t*t*Y*cos(2.0*X*
 0.3141592653589793E1);
  }
References cos(), Growth_rate, Eigen::bfloat16_impl::pow(), sin(), TestProblem::source(), plotPSD::t, plotDoE::x, X, and Y.
Referenced by MeltContactProblem< ELEMENT >::complete_problem_setup(), and UnsteadyHeatMeltProblem< ELEMENT >::complete_problem_setup().
melting_surface_height()
double ExactSolution::melting_surface_height (const double & t, const double & x)
Height of melting surface.
  {
   return 1.0-Growth_rate*t*t*(1.0-cos(2.0*x*0.3141592653589793E1));
  }
References cos(), Growth_rate, plotPSD::t, and plotDoE::x.
Referenced by MeltContactProblem< ELEMENT >::doc_solution(), UnsteadyHeatMeltProblem< ELEMENT >::doc_solution(), and flux_into_bulk().
prescribed_flux_for_unsteady_heat_validation()
void ExactSolution::prescribed_flux_for_unsteady_heat_validation (const double & t, const Vector< double > & x, const Vector< double > & n, const double & u, double & flux)
Total flux (into bulk + melt) required by the exact solution on a boundary with outer unit normal n. No dependence on temperature u.
Flux required by the exact solution on a boundary with outer unit normal n. No dependence on temperature u.
  {
   double X=x[0];
   //The flux into bulk
   flux_into_bulk(t,x,n,u,flux);
   // Add melt flux
   double melt_flux=
    2.0*Growth_rate*t*(1.0-cos(2.0*X*0.3141592653589793E1))/sqrt(1.0+4.0
 *Growth_rate*Growth_rate*t*t*t*t*pow(sin(2.0*X*0.3141592653589793E1),2.0)*
 0.3141592653589793E1*0.3141592653589793E1);
   flux+=melt_flux*cos(Omega_cos*t);
  }
References cos(), ProblemParameters::flux(), flux_into_bulk(), Growth_rate, GlobalParameters::melt_flux(), n, Omega_cos, Eigen::bfloat16_impl::pow(), sin(), sqrt(), plotPSD::t, plotDoE::x, and X.
Referenced by MeltContactProblem< ELEMENT >::complete_problem_setup(), and UnsteadyHeatMeltProblem< ELEMENT >::complete_problem_setup().
rigid_body_rotation()
void ExactSolution::rigid_body_rotation (const Vector< double > & x, Vector< double > & u)
The rigid-body rotation solution.
  {
   //store r sin(theta)
   double r_sin_theta = x[0]*sin(x[1]);
   u[0] = 0.0;
   u[1] = 0.0;
   //Only azimuthal velocity
   u[2] = r_sin_theta;
   //The pressure is the only part the involves the Reynolds number
   u[3] = 0.5*Global_Physical_Variables::Re*r_sin_theta*r_sin_theta;
  }
References Global_Physical_Variables::Re, sin(), and plotDoE::x.
Referenced by SphericalSteadyRotationProblem< ELEMENT >::parameter_study().
rigid_body_rotation_dr()
void ExactSolution::rigid_body_rotation_dr (const Vector< double > & x, Vector< double > & u)
The r-derivative of the rigid-body rotation solution.
  {
   //store  sin(theta)
   double sin_theta = sin(x[1]);
   u[0] = 0.0;
   u[1] = 0.0;
   //Only azimuthal velocity
   u[2] = sin_theta;
   //The pressure is the only part the involves the Reynolds number
   u[3] = Global_Physical_Variables::Re*x[0]*sin_theta*sin_theta;
  }
References Global_Physical_Variables::Re, sin(), and plotDoE::x.
Referenced by SphericalSteadyRotationProblem< ELEMENT >::parameter_study().
rigid_body_rotation_dtheta()
void ExactSolution::rigid_body_rotation_dtheta (const Vector< double > & x, Vector< double > & u)
The theta-derivative of the rigid-body rotation solution.
  {
   //store  sin(theta)
   u[0] = 0.0;
   u[1] = 0.0;
   //Only azimuthal velocity
   u[2] = x[0]*cos(x[1]);
   //The pressure is the only part the involves the Reynolds number
   u[3] = Global_Physical_Variables::Re*x[0]*x[0]*sin(x[1])*cos(x[1]);
  }
References cos(), Global_Physical_Variables::Re, sin(), and plotDoE::x.
Referenced by SphericalSteadyRotationProblem< ELEMENT >::parameter_study().
Variable Documentation
Growth_rate
double ExactSolution::Growth_rate =1.0
Growth rate for interface.
Referenced by analytical_outer_unit_normal(), flux_into_bulk(), get_exact_u_for_unsteady_heat_validation(), get_source_for_unsteady_heat_validation(), melting_surface_height(), and prescribed_flux_for_unsteady_heat_validation().
Omega_cos
double ExactSolution::Omega_cos =0.0
Frequency of co-sinusoidal oscillation of incoming heat flux (to assess suppression of re-freezing). Set to zero for validation.
Referenced by main(), and prescribed_flux_for_unsteady_heat_validation().
U0
double ExactSolution::U0 =0.0
Constant/initial temperature.
Referenced by oomph::Newmark< NSTEPS >::assign_initial_data_values(), oomph::Newmark< NSTEPS >::assign_initial_data_values_stage2(), get_exact_u_for_unsteady_heat_validation(), GlobalParameters::incoming_sb_inside(), GlobalParameters::incoming_sb_outside(), main(), MeltContactProblem< ELEMENT >::MeltContactProblem(), SolarRadiationProblem< ELEMENT >::SolarRadiationProblem(), and UnsteadyHeatMeltProblem< ELEMENT >::UnsteadyHeatMeltProblem().
Use_analytical_outer_unit_normal
bool ExactSolution::Use_analytical_outer_unit_normal =true
Use analytical outer unit normal when computing fluxes?
Referenced by flux_into_bulk().