MercuryDPM: Eigen::internal::visitor_impl< Visitor, Derived, Dynamic, true, false, ShortCircuitEvaluation > Struct Template Reference
Eigen::internal::visitor_impl< Visitor, Derived, Dynamic, true, false, ShortCircuitEvaluation > Struct Template Reference
#include <Visitor.h>
Public Types
using Scalar = typename Derived::Scalar
using Packet = typename packet_traits< Scalar >::type
using short_circuit = short_circuit_eval_impl< Visitor, ShortCircuitEvaluation >
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void run (const Derived &mat, Visitor &visitor)
Static Public Attributes
static constexpr int PacketSize = packet_traits<Scalar>::size
static constexpr bool RowMajor = Derived::IsRowMajor
Member Typedef Documentation
Packet
template<typename Visitor , typename Derived , bool ShortCircuitEvaluation> using Eigen::internal::visitor_impl< Visitor, Derived, Dynamic, true, false, ShortCircuitEvaluation >::Packet = typename packet_traits<Scalar>::type
Scalar
template<typename Visitor , typename Derived , bool ShortCircuitEvaluation> using Eigen::internal::visitor_impl< Visitor, Derived, Dynamic, true, false, ShortCircuitEvaluation >::Scalar = typename Derived::Scalar
short_circuit
template<typename Visitor , typename Derived , bool ShortCircuitEvaluation> using Eigen::internal::visitor_impl< Visitor, Derived, Dynamic, true, false, ShortCircuitEvaluation >::short_circuit = short_circuit_eval_impl<Visitor, ShortCircuitEvaluation>
Member Function Documentation
run()
template<typename Visitor , typename Derived , bool ShortCircuitEvaluation> static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::visitor_impl< Visitor, Derived, Dynamic, true, false, ShortCircuitEvaluation >::run (const Derived & mat, Visitor & visitor) inline static
{
     const Index innerSize = RowMajor ? mat.cols() : mat.rows();
     const Index outerSize = RowMajor ? mat.rows() : mat.cols();
     if (innerSize == 0 || outerSize == 0) return;
     {
       Index i = 0;
       if (innerSize < PacketSize) {
         visitor.init(mat.coeff(0, 0), 0, 0);
         i = 1;
       } else {
         Packet p = mat.template packet<Packet>(0, 0);
         visitor.initpacket(p, 0, 0);
         i = PacketSize;
       }
       if EIGEN_PREDICT_FALSE (short_circuit::run(visitor)) return;
       for (; i + PacketSize - 1 < innerSize; i += PacketSize) {
         Index r = RowMajor ? 0 : i;
         Index c = RowMajor ? i : 0;
         Packet p = mat.template packet<Packet>(r, c);
         visitor.packet(p, r, c);
         if EIGEN_PREDICT_FALSE (short_circuit::run(visitor)) return;
       }
       for (; i < innerSize; ++i) {
         Index r = RowMajor ? 0 : i;
         Index c = RowMajor ? i : 0;
         visitor(mat.coeff(r, c), r, c);
         if EIGEN_PREDICT_FALSE (short_circuit::run(visitor)) return;
       }
     }
     for (Index j = 1; j < outerSize; j++) {
       Index i = 0;
       for (; i + PacketSize - 1 < innerSize; i += PacketSize) {
         Index r = RowMajor ? j : i;
         Index c = RowMajor ? i : j;
         Packet p = mat.template packet<Packet>(r, c);
         visitor.packet(p, r, c);
         if EIGEN_PREDICT_FALSE (short_circuit::run(visitor)) return;
       }
       for (; i < innerSize; ++i) {
         Index r = RowMajor ? j : i;
         Index c = RowMajor ? i : j;
         visitor(mat.coeff(r, c), r, c);
         if EIGEN_PREDICT_FALSE (short_circuit::run(visitor)) return;
       }
     }
   }
References calibrate::c, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::coeff(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::cols(), EIGEN_PREDICT_FALSE, i, j, p, UniformPSDSelfTest::r, Eigen::RowMajor, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::rows(), and run().
Member Data Documentation
PacketSize
template<typename Visitor , typename Derived , bool ShortCircuitEvaluation> constexpr int Eigen::internal::visitor_impl< Visitor, Derived, Dynamic, true, false, ShortCircuitEvaluation >::PacketSize = packet_traits<Scalar>::size static constexpr
RowMajor
template<typename Visitor , typename Derived , bool ShortCircuitEvaluation> constexpr bool Eigen::internal::visitor_impl< Visitor, Derived, Dynamic, true, false, ShortCircuitEvaluation >::RowMajor = Derived::IsRowMajor static constexpr
The documentation for this struct was generated from the following file:
Visitor.h