MercuryDPM: Eigen::ArrayBase< Derived > Class Template Reference
Eigen::ArrayBase< Derived > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
Base class for all 1D and 2D array, and related expressions.
#include <ArrayBase.h>
Public Types
typedef ArrayBase StorageBaseType
typedef ArrayBase Eigen_BaseClassForSpecializationOfGlobalMathFuncImpl
typedef internal::traits< Derived >::StorageKind StorageKind
typedef internal::traits< Derived >::Scalar Scalar
typedef internal::packet_traits< Scalar >::type PacketScalar
typedef NumTraits< Scalar >::Real RealScalar
typedef DenseBase< Derived > Base
typedef Base::CoeffReturnType CoeffReturnType
typedef Base::PlainObject PlainObject
typedef CwiseNullaryOp< internal::scalar_constant_op< Scalar >, PlainObject > ConstantReturnType
Public Types inherited from Eigen::DenseBase< Derived >
enum {
RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime , ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime , SizeAtCompileTime = (internal::size_of_xpr_at_compile_time<Derived>::ret) , MaxRowsAtCompileTime = internal::traits<Derived>::MaxRowsAtCompileTime ,
MaxColsAtCompileTime = internal::traits<Derived>::MaxColsAtCompileTime , MaxSizeAtCompileTime , IsVectorAtCompileTime , NumDimensions ,
Flags = internal::traits<Derived>::Flags , IsRowMajor = int(Flags) & RowMajorBit , InnerSizeAtCompileTime , InnerStrideAtCompileTime = internal::inner_stride_at_compile_time<Derived>::ret ,
OuterStrideAtCompileTime = internal::outer_stride_at_compile_time<Derived>::ret
}
enum { IsPlainObjectBase = 0 }
typedef Eigen::InnerIterator< Derived > InnerIterator
typedef internal::traits< Derived >::StorageKind StorageKind
typedef internal::traits< Derived >::StorageIndex StorageIndex
The type used to store indices.
typedef internal::traits< Derived >::Scalar Scalar
typedef Scalar value_type
typedef NumTraits< Scalar >::Real RealScalar
typedef DenseCoeffsBase< Derived, internal::accessors_level< Derived >::value > Base
typedef Base::CoeffReturnType CoeffReturnType
typedef internal::find_best_packet< Scalar, SizeAtCompileTime >::type PacketScalar
typedef Matrix< typename internal::traits< Derived >::Scalar, internal::traits< Derived >::RowsAtCompileTime, internal::traits< Derived >::ColsAtCompileTime, AutoAlign|(internal::traits< Derived >::Flags &RowMajorBit ? RowMajor :ColMajor), internal::traits< Derived >::MaxRowsAtCompileTime, internal::traits< Derived >::MaxColsAtCompileTime > PlainMatrix
typedef Array< typename internal::traits< Derived >::Scalar, internal::traits< Derived >::RowsAtCompileTime, internal::traits< Derived >::ColsAtCompileTime, AutoAlign|(internal::traits< Derived >::Flags &RowMajorBit ? RowMajor :ColMajor), internal::traits< Derived >::MaxRowsAtCompileTime, internal::traits< Derived >::MaxColsAtCompileTime > PlainArray
typedef std::conditional_t< internal::is_same< typename internal::traits< Derived >::XprKind, MatrixXpr >::value, PlainMatrix, PlainArray > PlainObject
The plain matrix or array type corresponding to this expression.
typedef CwiseNullaryOp< internal::scalar_constant_op< Scalar >, PlainObject > ConstantReturnType
typedef CwiseNullaryOp< internal::scalar_zero_op< Scalar >, PlainObject > ZeroReturnType
typedef CwiseNullaryOp< internal::linspaced_op< Scalar >, PlainObject > RandomAccessLinSpacedReturnType
typedef CwiseNullaryOp< internal::equalspaced_op< Scalar >, PlainObject > RandomAccessEqualSpacedReturnType
typedef Matrix< typename NumTraits< typename internal::traits< Derived >::Scalar >::Real, internal::traits< Derived >::ColsAtCompileTime, 1 > EigenvaluesReturnType
typedef Transpose< Derived > TransposeReturnType
typedef Transpose< const Derived > ConstTransposeReturnType
typedef internal::add_const_on_value_type_t< typename internal::eval< Derived >::type > EvalReturnType
typedef VectorwiseOp< Derived, Horizontal > RowwiseReturnType
typedef const VectorwiseOp< const Derived, Horizontal > ConstRowwiseReturnType
typedef VectorwiseOp< Derived, Vertical > ColwiseReturnType
typedef const VectorwiseOp< const Derived, Vertical > ConstColwiseReturnType
typedef CwiseNullaryOp< internal::scalar_random_op< Scalar >, PlainObject > RandomReturnType
typedef Reverse< Derived, BothDirections > ReverseReturnType
typedef const Reverse< const Derived, BothDirections > ConstReverseReturnType
typedef std::conditional_t<(Flags &DirectAccessBit)==DirectAccessBit, internal::pointer_based_stl_iterator< Derived >, internal::generic_randaccess_stl_iterator< Derived > > iterator_type
typedef std::conditional_t<(Flags &DirectAccessBit)==DirectAccessBit, internal::pointer_based_stl_iterator< const Derived >, internal::generic_randaccess_stl_iterator< const Derived > > const_iterator_type
typedef std::conditional_t< IsVectorAtCompileTime, iterator_type, void > iterator
typedef std::conditional_t< IsVectorAtCompileTime, const_iterator_type, void > const_iterator
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator= (const ArrayBase &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator= (const Scalar &value)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator+= (const Scalar &scalar)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator-= (const Scalar &scalar)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator+= (const ArrayBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator-= (const ArrayBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator*= (const ArrayBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator/= (const ArrayBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC ArrayBase< Derived > & array ()
EIGEN_DEVICE_FUNC const ArrayBase< Derived > & array () const
EIGEN_DEVICE_FUNC MatrixWrapper< Derived > matrix ()
EIGEN_DEVICE_FUNC const MatrixWrapper< const Derived > matrix () const
template<typename OtherDerived >
EIGEN_DEPRECATED EIGEN_DEVICE_FUNC Derived & lazyAssign (const DenseBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & lazyAssign (const DenseBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator= (const DenseBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator= (const DenseBase &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator= (const EigenBase< OtherDerived > &other)
Copies the generic expression other into *this.
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator= (const ReturnByValue< OtherDerived > &func)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator+= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator-= (const EigenBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator*= (const Scalar &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator/= (const Scalar &other)
Public Member Functions inherited from Eigen::DenseBase< Derived >
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index outerSize () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index innerSize () const
EIGEN_DEVICE_FUNC void resize (Index newSize)
EIGEN_DEVICE_FUNC void resize (Index rows, Index cols)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator= (const DenseBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator= (const DenseBase &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator= (const EigenBase< OtherDerived > &other)
Copies the generic expression other into *this.
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator+= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator-= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator= (const ReturnByValue< OtherDerived > &func)
template<typename OtherDerived >
EIGEN_DEPRECATED EIGEN_DEVICE_FUNC Derived & lazyAssign (const DenseBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC CommaInitializer< Derived > operator<< (const Scalar &s)
template<unsigned int Added, unsigned int Removed>
EIGEN_DEPRECATED const Derived & flagged () const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC CommaInitializer< Derived > operator<< (const DenseBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC TransposeReturnType transpose ()
EIGEN_DEVICE_FUNC const ConstTransposeReturnType transpose () const
EIGEN_DEVICE_FUNC void transposeInPlace ()
EIGEN_DEVICE_FUNC void fill (const Scalar &value)
EIGEN_DEVICE_FUNC Derived & setConstant (const Scalar &value)
EIGEN_DEVICE_FUNC Derived & setLinSpaced (Index size, const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
EIGEN_DEVICE_FUNC Derived & setLinSpaced (const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
EIGEN_DEVICE_FUNC Derived & setEqualSpaced (Index size, const Scalar &low, const Scalar &step)
EIGEN_DEVICE_FUNC Derived & setEqualSpaced (const Scalar &low, const Scalar &step)
EIGEN_DEVICE_FUNC Derived & setZero ()
EIGEN_DEVICE_FUNC Derived & setOnes ()
EIGEN_DEVICE_FUNC Derived & setRandom ()
template<typename OtherDerived >
EIGEN_DEVICE_FUNC bool isApprox (const DenseBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isMuchSmallerThan (const RealScalar &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC bool isMuchSmallerThan (const DenseBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isApproxToConstant (const Scalar &value, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isConstant (const Scalar &value, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isZero (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isOnes (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool hasNaN () const
EIGEN_DEVICE_FUNC bool allFinite () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator*= (const Scalar &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator/= (const Scalar &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EvalReturnType eval () const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void swap (const DenseBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void swap (PlainObjectBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC const NestByValue< Derived > nestByValue () const
EIGEN_DEVICE_FUNC const ForceAlignedAccess< Derived > forceAlignedAccess () const
EIGEN_DEVICE_FUNC ForceAlignedAccess< Derived > forceAlignedAccess ()
template<bool Enable>
EIGEN_DEVICE_FUNC const std::conditional_t< Enable, ForceAlignedAccess< Derived >, Derived & > forceAlignedAccessIf () const
template<bool Enable>
EIGEN_DEVICE_FUNC std::conditional_t< Enable, ForceAlignedAccess< Derived >, Derived & > forceAlignedAccessIf ()
EIGEN_DEVICE_FUNC Scalar sum () const
EIGEN_DEVICE_FUNC Scalar mean () const
EIGEN_DEVICE_FUNC Scalar trace () const
EIGEN_DEVICE_FUNC Scalar prod () const
template<int NaNPropagation>
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff () const
template<int NaNPropagation>
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff () const
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff () const
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff () const
template<int NaNPropagation, typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff (IndexType *row, IndexType *col) const
template<int NaNPropagation, typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff (IndexType *row, IndexType *col) const
template<int NaNPropagation, typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff (IndexType *index) const
template<int NaNPropagation, typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff (IndexType *index) const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff (IndexType *row, IndexType *col) const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff (IndexType *row, IndexType *col) const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff (IndexType *index) const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff (IndexType *index) const
template<typename BinaryOp >
EIGEN_DEVICE_FUNC Scalar redux (const BinaryOp &func) const
template<typename Visitor >
EIGEN_DEVICE_FUNC void visit (Visitor &func) const
const WithFormat< Derived > format (const IOFormat &fmt) const
EIGEN_DEVICE_FUNC CoeffReturnType value () const
EIGEN_DEVICE_FUNC bool all () const
EIGEN_DEVICE_FUNC bool any () const
EIGEN_DEVICE_FUNC Index count () const
EIGEN_DEVICE_FUNC ConstRowwiseReturnType rowwise () const
EIGEN_DEVICE_FUNC RowwiseReturnType rowwise ()
EIGEN_DEVICE_FUNC ConstColwiseReturnType colwise () const
EIGEN_DEVICE_FUNC ColwiseReturnType colwise ()
template<typename ThenDerived , typename ElseDerived >
EIGEN_DEVICE_FUNC CwiseTernaryOp< internal::scalar_boolean_select_op< typename DenseBase< ThenDerived >::Scalar, typename DenseBase< ElseDerived >::Scalar, Scalar >, ThenDerived, ElseDerived, Derived > select (const DenseBase< ThenDerived > &thenMatrix, const DenseBase< ElseDerived > &elseMatrix) const
template<typename ThenDerived >
EIGEN_DEVICE_FUNC CwiseTernaryOp< internal::scalar_boolean_select_op< typename DenseBase< ThenDerived >::Scalar, typename DenseBase< ThenDerived >::Scalar, Scalar >, ThenDerived, typename DenseBase< ThenDerived >::ConstantReturnType, Derived > select (const DenseBase< ThenDerived > &thenMatrix, const typename DenseBase< ThenDerived >::Scalar &elseScalar) const
template<typename ElseDerived >
EIGEN_DEVICE_FUNC CwiseTernaryOp< internal::scalar_boolean_select_op< typename DenseBase< ElseDerived >::Scalar, typename DenseBase< ElseDerived >::Scalar, Scalar >, typename DenseBase< ElseDerived >::ConstantReturnType, ElseDerived, Derived > select (const typename DenseBase< ElseDerived >::Scalar &thenScalar, const DenseBase< ElseDerived > &elseMatrix) const
template<int p>
RealScalar lpNorm () const
template<int RowFactor, int ColFactor>
EIGEN_DEVICE_FUNC const Replicate< Derived, RowFactor, ColFactor > replicate () const
EIGEN_DEVICE_FUNC const Replicate< Derived, Dynamic, Dynamic > replicate (Index rowFactor, Index colFactor) const
EIGEN_DEVICE_FUNC ReverseReturnType reverse ()
EIGEN_DEVICE_FUNC ConstReverseReturnType reverse () const
EIGEN_DEVICE_FUNC void reverseInPlace ()
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
iterator end ()
const_iterator end () const
const_iterator cend () const
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & lazyAssign (const DenseBase< OtherDerived > &other)
template<typename CustomNullaryOp >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseNullaryOp< CustomNullaryOp, typename DenseBase< Derived >::PlainObject > NullaryExpr (Index rows, Index cols, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseNullaryOp< CustomNullaryOp, typename DenseBase< Derived >::PlainObject > NullaryExpr (Index size, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseNullaryOp< CustomNullaryOp, typename DenseBase< Derived >::PlainObject > NullaryExpr (const CustomNullaryOp &func)
template<typename Derived >
EIGEN_DEVICE_FUNC bool isMuchSmallerThan (const typename NumTraits< Scalar >::Real &other, const RealScalar &prec) const
template<typename Func >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar redux (const Func &func) const
template<typename ThenDerived , typename ElseDerived >
EIGEN_DEVICE_FUNC CwiseTernaryOp< internal::scalar_boolean_select_op< typename DenseBase< ThenDerived >::Scalar, typename DenseBase< ElseDerived >::Scalar, typename DenseBase< Derived >::Scalar >, ThenDerived, ElseDerived, Derived > select (const DenseBase< ThenDerived > &thenMatrix, const DenseBase< ElseDerived > &elseMatrix) const
template<typename ThenDerived >
EIGEN_DEVICE_FUNC CwiseTernaryOp< internal::scalar_boolean_select_op< typename DenseBase< ThenDerived >::Scalar, typename DenseBase< ThenDerived >::Scalar, typename DenseBase< Derived >::Scalar >, ThenDerived, typename DenseBase< ThenDerived >::ConstantReturnType, Derived > select (const DenseBase< ThenDerived > &thenMatrix, const typename DenseBase< ThenDerived >::Scalar &elseScalar) const
template<typename ElseDerived >
EIGEN_DEVICE_FUNC CwiseTernaryOp< internal::scalar_boolean_select_op< typename DenseBase< ElseDerived >::Scalar, typename DenseBase< ElseDerived >::Scalar, typename DenseBase< Derived >::Scalar >, typename DenseBase< ElseDerived >::ConstantReturnType, ElseDerived, Derived > select (const typename DenseBase< ElseDerived >::Scalar &thenScalar, const DenseBase< ElseDerived > &elseMatrix) const
Protected Member Functions
template<typename OtherDerived >
Derived & operator+= (const MatrixBase< OtherDerived > &)
template<typename OtherDerived >
Derived & operator-= (const MatrixBase< OtherDerived > &)
Protected Member Functions inherited from Eigen::DenseBase< Derived >
constexpr EIGEN_DEVICE_FUNC DenseBase ()=default
Private Member Functions
ArrayBase (Index)
ArrayBase (Index, Index)
template<typename OtherDerived >
ArrayBase (const ArrayBase< OtherDerived > &)
Related Functions
(Note that these are not member functions.)
template<typename Derived , typename ScalarExponent >
EIGEN_DEVICE_FUNC const GlobalUnaryPowReturnType< Derived, ScalarExponent > pow (const Eigen::ArrayBase< Derived > &x, const ScalarExponent &exponent)
template<typename Derived , typename ExponentDerived >
const Eigen::CwiseBinaryOp< Eigen::internal::scalar_pow_op< typename Derived::Scalar, typename ExponentDerived::Scalar >, const Derived, const ExponentDerived > pow (const Eigen::ArrayBase< Derived > &x, const Eigen::ArrayBase< ExponentDerived > &exponents)
template<typename Scalar , typename Derived >
#define EIGEN_SCALAR_BINARYOP_EXPR_RETURN_TYPE(SCALAR, EXPR, OPNAME)
Related Functions inherited from Eigen::DenseBase< Derived >
template<typename Derived >
std::ostream & operator<< (std::ostream &s, const DenseBase< Derived > &m)
Additional Inherited Members
Static Public Member Functions inherited from Eigen::DenseBase< Derived >
static EIGEN_DEVICE_FUNC const ConstantReturnType Constant (Index rows, Index cols, const Scalar &value)
static EIGEN_DEVICE_FUNC const ConstantReturnType Constant (Index size, const Scalar &value)
static EIGEN_DEVICE_FUNC const ConstantReturnType Constant (const Scalar &value)
EIGEN_DEPRECATED static EIGEN_DEVICE_FUNC const RandomAccessLinSpacedReturnType LinSpaced (Sequential_t, Index size, const Scalar &low, const Scalar &high)
EIGEN_DEPRECATED static EIGEN_DEVICE_FUNC const RandomAccessLinSpacedReturnType LinSpaced (Sequential_t, const Scalar &low, const Scalar &high)
static EIGEN_DEVICE_FUNC const RandomAccessLinSpacedReturnType LinSpaced (Index size, const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
static EIGEN_DEVICE_FUNC const RandomAccessLinSpacedReturnType LinSpaced (const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
static EIGEN_DEVICE_FUNC const RandomAccessEqualSpacedReturnType EqualSpaced (Index size, const Scalar &low, const Scalar &step)
static EIGEN_DEVICE_FUNC const RandomAccessEqualSpacedReturnType EqualSpaced (const Scalar &low, const Scalar &step)
template<typename CustomNullaryOp >
static EIGEN_DEVICE_FUNC const CwiseNullaryOp< CustomNullaryOp, PlainObject > NullaryExpr (Index rows, Index cols, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
static EIGEN_DEVICE_FUNC const CwiseNullaryOp< CustomNullaryOp, PlainObject > NullaryExpr (Index size, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
static EIGEN_DEVICE_FUNC const CwiseNullaryOp< CustomNullaryOp, PlainObject > NullaryExpr (const CustomNullaryOp &func)
static EIGEN_DEVICE_FUNC const ZeroReturnType Zero (Index rows, Index cols)
static EIGEN_DEVICE_FUNC const ZeroReturnType Zero (Index size)
static EIGEN_DEVICE_FUNC const ZeroReturnType Zero ()
static EIGEN_DEVICE_FUNC const ConstantReturnType Ones (Index rows, Index cols)
static EIGEN_DEVICE_FUNC const ConstantReturnType Ones (Index size)
static EIGEN_DEVICE_FUNC const ConstantReturnType Ones ()
static const RandomReturnType Random (Index rows, Index cols)
static const RandomReturnType Random (Index size)
static const RandomReturnType Random ()
Public Attributes inherited from Eigen::DenseBase< Derived >
EIGEN_DEPRECATED typedef CwiseNullaryOp< internal::linspaced_op< Scalar >, PlainObject > SequentialLinSpacedReturnType
Detailed Description
template<typename Derived>
class Eigen::ArrayBase< Derived >
Base class for all 1D and 2D array, and related expressions.
An array is similar to a dense vector or matrix. While matrices are mathematical objects with well defined linear algebra operators, an array is just a collection of scalar values arranged in a one or two dimensional fashion. As the main consequence, all operations applied to an array are performed coefficient wise. Furthermore, arrays support scalar math functions of the c++ standard library (e.g., std::sin(x)), and convenient constructors allowing to easily write generic code working for both scalar values and arrays.
This class is the base that is inherited by all array expression types.
Template Parameters
Derived is the derived type, e.g., an array or an expression type.
This class can be extended with the help of the plugin mechanism described on the page Extending MatrixBase (and other classes) by defining the preprocessor symbol EIGEN_ARRAYBASE_PLUGIN.
See also
class MatrixBase, The class hierarchy
Member Typedef Documentation
Base
template<typename Derived > typedef DenseBase<Derived> Eigen::ArrayBase< Derived >::Base
CoeffReturnType
template<typename Derived > typedef Base::CoeffReturnType Eigen::ArrayBase< Derived >::CoeffReturnType
ConstantReturnType
template<typename Derived > typedef CwiseNullaryOp<internal::scalar_constant_op<Scalar>, PlainObject> Eigen::ArrayBase< Derived >::ConstantReturnType
Represents a matrix with all coefficients equal to one another
Eigen_BaseClassForSpecializationOfGlobalMathFuncImpl
template<typename Derived > typedef ArrayBase Eigen::ArrayBase< Derived >::Eigen_BaseClassForSpecializationOfGlobalMathFuncImpl
PacketScalar
template<typename Derived > typedef internal::packet_traits<Scalar>::type Eigen::ArrayBase< Derived >::PacketScalar
PlainObject
template<typename Derived > typedef Base::PlainObject Eigen::ArrayBase< Derived >::PlainObject
RealScalar
template<typename Derived > typedef NumTraits<Scalar>::Real Eigen::ArrayBase< Derived >::RealScalar
Scalar
template<typename Derived > typedef internal::traits<Derived>::Scalar Eigen::ArrayBase< Derived >::Scalar
StorageBaseType
template<typename Derived > typedef ArrayBase Eigen::ArrayBase< Derived >::StorageBaseType
The base class for a given storage type.
StorageKind
template<typename Derived > typedef internal::traits<Derived>::StorageKind Eigen::ArrayBase< Derived >::StorageKind
Constructor & Destructor Documentation
ArrayBase() [1/3]
template<typename Derived > Eigen::ArrayBase< Derived >::ArrayBase (Index) explicit private
ArrayBase() [2/3]
template<typename Derived > Eigen::ArrayBase< Derived >::ArrayBase (Index , Index) private
ArrayBase() [3/3]
template<typename Derived > template<typename OtherDerived > Eigen::ArrayBase< Derived >::ArrayBase (const ArrayBase< OtherDerived > &) explicit private
Member Function Documentation
array() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC ArrayBase<Derived>& Eigen::ArrayBase< Derived >::array () inline
 { return *this; }
array() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC const ArrayBase<Derived>& Eigen::ArrayBase< Derived >::array () const inline
 { return *this; }
lazyAssign() [1/2]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived& Eigen::DenseBase< Derived >::lazyAssign (typename OtherDerived)
{
   enum { SameType = internal::is_same<typename Derived::Scalar, typename OtherDerived::Scalar>::value };
   EIGEN_STATIC_ASSERT_LVALUE(Derived)
   EIGEN_STATIC_ASSERT_SAME_MATRIX_SIZE(Derived, OtherDerived)
   EIGEN_STATIC_ASSERT(
       SameType,
       YOU_MIXED_DIFFERENT_NUMERIC_TYPES__YOU_NEED_TO_USE_THE_CAST_METHOD_OF_MATRIXBASE_TO_CAST_NUMERIC_TYPES_EXPLICITLY)
   eigen_assert(rows() == other.rows() && cols() == other.cols());
   internal::call_assignment_no_alias(derived(), other.derived());
   return derived();
 }
lazyAssign() [2/2]
template<typename Derived > template<typename OtherDerived > EIGEN_DEPRECATED EIGEN_DEVICE_FUNC Derived& Eigen::DenseBase< Derived >::lazyAssign (typename OtherDerived)
Copies other into *this without evaluating other.
Returns
a reference to *this.
Deprecated:
matrix() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC MatrixWrapper<Derived> Eigen::ArrayBase< Derived >::matrix () inline
Returns
an Matrix expression of this array
See also
MatrixBase::array()
 { return MatrixWrapper<Derived>(derived()); }
matrix() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC const MatrixWrapper<const Derived> Eigen::ArrayBase< Derived >::matrix () const inline
{
     return MatrixWrapper<const Derived>(derived());
   }
operator*=() [1/2]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::ArrayBase< Derived >::operator*= (const ArrayBase< OtherDerived > & other)
replaces *this by *this * other coefficient wise.
Returns
a reference to *this
{
   call_assignment(derived(), other.derived(), internal::mul_assign_op<Scalar, typename OtherDerived::Scalar>());
   return derived();
 }
References Eigen::internal::call_assignment().
operator*=() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::operator*=
{
   internal::call_assignment(this->derived(), PlainObject::Constant(rows(), cols(), other),
                             internal::mul_assign_op<Scalar, Scalar>());
   return derived();
 }
operator+=() [1/4]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::ArrayBase< Derived >::operator+= (const ArrayBase< OtherDerived > & other)
replaces *this by *this + other.
Returns
a reference to *this
{
   call_assignment(derived(), other.derived(), internal::add_assign_op<Scalar, typename OtherDerived::Scalar>());
   return derived();
 }
References Eigen::internal::call_assignment().
operator+=() [2/4]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC Derived & Eigen::DenseBase< Derived >::operator+= (typename OtherDerived)
{
   call_assignment(derived(), other.derived(), internal::add_assign_op<Scalar, typename OtherDerived::Scalar>());
   return derived();
 }
operator+=() [3/4]
template<typename Derived > template<typename OtherDerived > Derived& Eigen::ArrayBase< Derived >::operator+= (const MatrixBase< OtherDerived > &) inline protected
{
     EIGEN_STATIC_ASSERT(std::ptrdiff_t(sizeof(typename OtherDerived::Scalar)) == -1,
                         YOU_CANNOT_MIX_ARRAYS_AND_MATRICES);
     return *this;
   }
References EIGEN_STATIC_ASSERT.
operator+=() [4/4]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::ArrayBase< Derived >::operator+= (const Scalar & scalar)
{
   internal::call_assignment(this->derived(), PlainObject::Constant(rows(), cols(), other),
                             internal::add_assign_op<Scalar, Scalar>());
   return derived();
 }
References Eigen::internal::call_assignment(), cols, and rows.
operator-=() [1/4]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::ArrayBase< Derived >::operator-= (const ArrayBase< OtherDerived > & other)
replaces *this by *this - other.
Returns
a reference to *this
{
   call_assignment(derived(), other.derived(), internal::sub_assign_op<Scalar, typename OtherDerived::Scalar>());
   return derived();
 }
References Eigen::internal::call_assignment().
operator-=() [2/4]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC Derived & Eigen::DenseBase< Derived >::operator-= (typename OtherDerived)
{
   call_assignment(derived(), other.derived(), internal::sub_assign_op<Scalar, typename OtherDerived::Scalar>());
   return derived();
 }
operator-=() [3/4]
template<typename Derived > template<typename OtherDerived > Derived& Eigen::ArrayBase< Derived >::operator-= (const MatrixBase< OtherDerived > &) inline protected
{
     EIGEN_STATIC_ASSERT(std::ptrdiff_t(sizeof(typename OtherDerived::Scalar)) == -1,
                         YOU_CANNOT_MIX_ARRAYS_AND_MATRICES);
     return *this;
   }
References EIGEN_STATIC_ASSERT.
operator-=() [4/4]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::ArrayBase< Derived >::operator-= (const Scalar & scalar)
{
   internal::call_assignment(this->derived(), PlainObject::Constant(rows(), cols(), other),
                             internal::sub_assign_op<Scalar, Scalar>());
   return derived();
 }
References Eigen::internal::call_assignment(), cols, and rows.
operator/=() [1/2]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::ArrayBase< Derived >::operator/= (const ArrayBase< OtherDerived > & other)
replaces *this by *this / other coefficient wise.
Returns
a reference to *this
{
   call_assignment(derived(), other.derived(), internal::div_assign_op<Scalar, typename OtherDerived::Scalar>());
   return derived();
 }
References Eigen::internal::call_assignment().
operator/=() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::operator/=
{
   internal::call_assignment(this->derived(), PlainObject::Constant(rows(), cols(), other),
                             internal::div_assign_op<Scalar, Scalar>());
   return derived();
 }
operator=() [1/6]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived& Eigen::ArrayBase< Derived >::operator= (const ArrayBase< Derived > & other) inline
Special case of the template operator=, in order to prevent the compiler from generating a default operator= (issue hit with g++ 4.1)
{
     internal::call_assignment(derived(), other.derived());
     return derived();
   }
References Eigen::internal::call_assignment().
operator=() [2/6]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::operator=
Special case of the template operator=, in order to prevent the compiler from generating a default operator= (issue hit with g++ 4.1)
{
   internal::call_assignment(derived(), other.derived());
   return derived();
 }
operator=() [3/6]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::operator= (typename OtherDerived)
Copies other into *this.
Returns
a reference to *this.
{
   internal::call_assignment(derived(), other.derived());
   return derived();
 }
operator=() [4/6]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC Derived & Eigen::DenseBase< Derived >::operator= (typename OtherDerived)
Copies the generic expression other into *this.
The expression must provide a (templated) evalTo(Derived& dst) const function which does the actual job. In practice, this allows any user to write its own special matrix without having to modify MatrixBase
Returns
a reference to *this.
{
   call_assignment(derived(), other.derived());
   return derived();
 }
operator=() [5/6]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC Derived & Eigen::DenseBase< Derived >::operator= (typename OtherDerived)
{
   other.evalTo(derived());
   return derived();
 }
operator=() [6/6]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived& Eigen::ArrayBase< Derived >::operator= (const Scalar & value) inline
Set all the entries to value.
See also
DenseBase::setConstant(), DenseBase::fill()
{
     Base::setConstant(value);
     return derived();
   }
References Eigen::DenseBase< Derived >::setConstant(), and Eigen::DenseBase< Derived >::value().
Friends And Related Function Documentation
EIGEN_SCALAR_BINARYOP_EXPR_RETURN_TYPE
template<typename Scalar , typename Derived > #define EIGEN_SCALAR_BINARYOP_EXPR_RETURN_TYPE (typename internal::promote_scalar_arg< typename Derived::Scalar EIGEN_COMMA Scalar EIGEN_COMMA EIGEN_SCALAR_BINARY_SUPPORTED(pow, Scalar, typename Derived::Scalar)>::type, Derived, pow) const & related
Value:
  CwiseBinaryOp<EIGEN_CAT(EIGEN_CAT(internal::scalar_, OPNAME), _op) < SCALAR, \
                typename internal::traits<EXPR>::Scalar>,                      \
      const typename internal::plain_constant_type<EXPR, SCALAR>::type, const EXPR >
Returns
an expression of the coefficient-wise power of the scalar x to the given array of exponents.
This function computes the coefficient-wise power between a scalar and an array of exponents.
Template Parameters
Scalar is the scalar type of x. It must be compatible with the scalar type of the given array expression (Derived::Scalar).
Example:
Array<double, 1, 3> e(2, -3, 1. / 3.);
cout << "10^[" << e << "] = " << pow(10, e) << endl;
Output:
See also
ArrayBase::pow()
pow() [1/2]
template<typename Derived , typename ExponentDerived > const Eigen::CwiseBinaryOp< Eigen::internal::scalar_pow_op< typename Derived::Scalar, typename ExponentDerived::Scalar >, const Derived, const ExponentDerived > pow (const Eigen::ArrayBase< Derived > & x, const Eigen::ArrayBase< ExponentDerived > & exponents) related
Returns
an expression of the coefficient-wise power of x to the given array of exponents.
This function computes the coefficient-wise power.
Example:
Array<double, 1, 3> x(8, 25, 3), e(1. / 3., 0.5, 2.);
cout << "[" << x << "]^[" << e << "] = " << x.pow(e) << endl;   // using ArrayBase::pow
cout << "[" << x << "]^[" << e << "] = " << pow(x, e) << endl;  // using Eigen::pow
Output:
See also
ArrayBase::pow()
{
   return Eigen::CwiseBinaryOp<
       Eigen::internal::scalar_pow_op<typename Derived::Scalar, typename ExponentDerived::Scalar>, const Derived,
       const ExponentDerived>(x.derived(), exponents.derived());
 }
References Eigen::exponents, and plotDoE::x.
pow() [2/2]
template<typename Derived , typename ScalarExponent > EIGEN_DEVICE_FUNC const GlobalUnaryPowReturnType< Derived, ScalarExponent > pow (const Eigen::ArrayBase< Derived > & x, const ScalarExponent & exponent) related
Returns
an expression of the coefficient-wise power of x to the given constant exponent.
Template Parameters
ScalarExponent is the scalar type of exponent. It must be compatible with the scalar type of the given expression (Derived::Scalar).
See also
ArrayBase::pow()
{
   return GlobalUnaryPowReturnType<Derived, ScalarExponent>(
       x.derived(), internal::scalar_unary_pow_op<typename Derived::Scalar, ScalarExponent>(exponent));
 }
References plotDoE::x.
Referenced by MeltSpinningProblem< ELEMENT >::actions_before_newton_solve(), EntryFlowProblem< ELEMENT >::actions_before_newton_solve(), AxisymFreeSurfaceNozzleAdvDiffRobinProblem< ELEMENT >::actions_before_newton_solve(), SteadyCurvedTubeProblem< ELEMENT >::actions_before_newton_solve(), SteadyHelicalProblem< ELEMENT >::actions_before_newton_solve(), SteadyTubeProblem< ELEMENT >::actions_before_newton_solve(), NavierStokesProblem< ELEMENT >::apply_boundary_conditions(), array_generic(), array_real(), array_special_functions(), binary_ops_test(), check_locate_zeta(), mathsFunc::chi_squared(), ContactProblem< ELEMENT >::doc_solution(), ElasticRingProblem< ELEMENT >::doc_solution(), DiskOscillationProblem< ELEMENT >::doc_solution(), PoissonProblem< ELEMENT >::doc_solution(), EighthSpherePoissonProblem< ELEMENT >::doc_solution(), UnsteadyHeatProblem< ELEMENT >::enforce_time_periodic_boundary_conditions(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::find_distance_to_free_surface(), main(), ElasticRingProblem< ELEMENT >::parameter_study(), qr_invertible(), run_it(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::set_boundary_conditions(), oomph::BDF< NSTEPS >::set_error_weights(), LinearWaveProblem< ELEMENT, TIMESTEPPER >::set_initial_condition(), RefineableActivatorInhibitorProblem< ELEMENT >::set_initial_condition(), ShellProblem< ELEMENT >::solve(), svd_fill_random(), test2dRotation(), test3dRotation(), test_basic_functions(), test_nnls_random_problem(), and testGeneral().
The documentation for this class was generated from the following files:
ArrayBase.h
GlobalFunctions.h
SelfCwiseBinaryOp.h