MercuryDPM: InteractionVTKWriter Class Reference
InteractionVTKWriter Class Reference final
#include <InteractionVTKWriter.h>
Public Member Functions
InteractionVTKWriter (InteractionHandler &interactionHandler)
Non-default constructor; sets the handler and fileCounter.
InteractionVTKWriter (const InteractionVTKWriter &)=default
Default copy constructor.
void writeVTK () const override
writes a vtk file
std::string getName () const
the name of the class in the restart file
Public Member Functions inherited from BaseVTKWriter< InteractionHandler >
BaseVTKWriter (InteractionHandler &handler)
BaseVTKWriter (const BaseVTKWriter &other)
unsigned getFileCounter () const
void setFileCounter (unsigned fileCounter)
void setOutputDirectory (const std::string &dir)
const std::string & getOutputDirectory () const
std::string getFileName () const
Protected Member Functions
void writeVTKPoints (std::fstream &file) const
writes the point data to the vtu file (i.e. the vertices of the mesh displayed in paraview)
void writeVTKPointData (std::fstream &file) const
writes the point data to the vtu file (i.e. options how to color the interactions displayed in paraview)
Protected Member Functions inherited from BaseVTKWriter< InteractionHandler >
std::fstream makeVTKFileWithHeader () const
void writeVTKFooterAndClose (std::fstream &file) const
Additional Inherited Members
Protected Attributes inherited from BaseVTKWriter< InteractionHandler >
InteractionHandler & handler_
particle handler from which the particles should be written
unsigned int fileCounter
std::string outputDirectory_
Constructor & Destructor Documentation
InteractionVTKWriter() [1/2]
InteractionVTKWriter::InteractionVTKWriter (InteractionHandler & interactionHandler) inline explicit
Non-default constructor; sets the handler and fileCounter.
                                                                           : BaseVTKWriter(interactionHandler)
     {}
InteractionVTKWriter() [2/2]
InteractionVTKWriter::InteractionVTKWriter (const InteractionVTKWriter &) default
Default copy constructor.
Member Function Documentation
getName()
std::string InteractionVTKWriter::getName () const inline
the name of the class in the restart file
     {
         return "InteractionVTKWriter";
     }
writeVTK()
void InteractionVTKWriter::writeVTK () const override virtual
writes a vtk file
Implements BaseVTKWriter< InteractionHandler >.
 {
     std::fstream file = makeVTKFileWithHeader();
     file << "<Piece NumberOfPoints=\"" << handler_.getNumberOfObjects() << "\" NumberOfCells=\"" << 0 << "\">\n";
     file << "<Points>\n";
     writeVTKPoints(file);
     file << "</Points>\n";
     file << "<PointData  Vectors=\"vector\">\n";
     writeVTKPointData(file);
     file << "</PointData>\n";
     writeVTKFooterAndClose(file);
 }
References BaseHandler< T >::getNumberOfObjects(), BaseVTKWriter< InteractionHandler >::handler_, BaseVTKWriter< InteractionHandler >::makeVTKFileWithHeader(), BaseVTKWriter< InteractionHandler >::writeVTKFooterAndClose(), writeVTKPointData(), and writeVTKPoints().
Referenced by DPMBase::writeVTKFiles().
writeVTKPointData()
void InteractionVTKWriter::writeVTKPointData (std::fstream & file) const protected
writes the point data to the vtu file (i.e. options how to color the interactions displayed in paraview)
 {
     file << "  <DataArray type=\"Float32\" Name=\"Normal\" NumberOfComponents=\"3\" format=\"ascii\">\n";
     // Add velocity
     for (const auto& p: handler_)
     {
         file << '\t' << p->getNormal() << '\n';
     }
     file << "  </DataArray>\n";
     file << "  <DataArray type=\"Float32\" Name=\"Overlap\" format=\"ascii\">\n";
     // Add overlap
     for (const auto& p: handler_)
     {
         file << '\t' << p->getOverlap() << '\n';
     }
     file << "  </DataArray>\n";
     file << "  <DataArray type=\"Float32\" Name=\"ContactRadius\" format=\"ascii\">\n";
     // Add radius
     for (const auto& p: handler_)
     {
         file << '\t' << p->getContactRadius() << '\n';
     }
     file << "  </DataArray>\n";
     file << "  <DataArray type=\"Float32\" Name=\"Force\" NumberOfComponents=\"3\" format=\"ascii\">\n";
     // Add species type
     for (const auto& p: handler_)
     {
         file << '\t' << p->getForce() << '\n';
     }
     file << "  </DataArray>\n";
     file << "  <DataArray type=\"Float32\" Name=\"TangentialOverlap\" format=\"ascii\">\n";
     // Add species type
     for (const auto& p: handler_)
     {
         file << '\t' << p->getTangentialOverlap() << '\n';
     }
     file << "  </DataArray>\n";
     file << "  <DataArray type=\"Float32\" Name=\"Torque\" NumberOfComponents=\"3\" format=\"ascii\">\n";
     // Add species type
     for (const auto& p: handler_)
     {
         file << '\t' << p->getTorque() << '\n';
     }
     file << "  </DataArray>\n";
     //check if this type of Interaction has extra fields
     if (handler_.getSize() != 0)
     {
         for (unsigned i = 0; i < handler_.getLastObject()->getNumberOfFieldsVTK(); i++)
         {
             file << "  <DataArray type=\"" << handler_.getLastObject()->getTypeVTK(i) << "\" Name=\""
                  << handler_.getLastObject()->getNameVTK(i) << "\" format=\"ascii\">\n";
             // Add species type
             for (const auto& p: handler_)
             {
                 for (auto f : p->getFieldVTK(i))
                     file << '\t' << f << '\n';
             }
             file << "  </DataArray>\n";
         }
     }
 }
References f(), BaseHandler< T >::getLastObject(), BaseInteraction::getNameVTK(), BaseHandler< T >::getSize(), BaseInteraction::getTypeVTK(), BaseVTKWriter< InteractionHandler >::handler_, i, and p.
Referenced by writeVTK().
writeVTKPoints()
void InteractionVTKWriter::writeVTKPoints (std::fstream & file) const protected
writes the point data to the vtu file (i.e. the vertices of the mesh displayed in paraview)
 {
     file << "  <DataArray type=\"Float32\" Name=\"Position\" NumberOfComponents=\"3\" format=\"ascii\">\n";
     for (const auto& p: handler_)
     {
         file << '\t' << p->getContactPoint() << '\n';
     }
     file << "  </DataArray>\n";
 }
References BaseVTKWriter< InteractionHandler >::handler_, and p.
Referenced by writeVTK().
The documentation for this class was generated from the following files:
InteractionVTKWriter.h
InteractionVTKWriter.cc