MercuryDPM: vmtk_solid.cc File Reference
vmtk_solid.cc File Reference
#include "generic.h"
#include "solid.h"
#include "constitutive.h"
#include "meshes/tetgen_mesh.h"
Classes
class MySolidTetgenMesh< ELEMENT >
Tetgen-based mesh upgraded to become a solid mesh.
class UnstructuredSolidProblem< ELEMENT, MESH >
Unstructured solid problem.
Namespaces
Global_Parameters
Namespace for global parameters.
Functions
void Global_Parameters::gravity (const double &time, const Vector< double > &xi, Vector< double > &b)
Non-dimensional gravity as body force.
void Global_Parameters::constant_pressure (const Vector< double > &xi, const Vector< double > &x, const Vector< double > &n, Vector< double > &traction)
int main (int argc, char **argv)
Demonstrate how to solve an unstructured 3D solid problem.
Function Documentation
main()
int main (int argc , char ** argv)
Demonstrate how to solve an unstructured 3D solid problem.
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Label for output
  DocInfo doc_info;
  // Output directory
  doc_info.set_directory("RESLT");
  //Set up the problem
  UnstructuredSolidProblem<TPVDElement<3,3> > problem;
  //Output initial configuration
  problem.doc_solution(doc_info);
  doc_info.number()++;
   // Parameter study
  Global_Parameters::P=0.0;
  double g_increment=0.0;
  double p_increment=1.0e-2;
  unsigned nstep=4;
  if (CommandLineArgs::Argc!=1)
   {
    std::cout << "Validation -- only doing two steps" << std::endl;
    nstep=2;
   }
  // Do the parameter study
  for (unsigned istep=0;istep<nstep;istep++)
   {
    // Solve the problem
    problem.newton_solve();
    //Output solution
    problem.doc_solution(doc_info);
    doc_info.number()++;
    // Bump up load
    Global_Parameters::Gravity+=g_increment;
    Global_Parameters::P+=p_increment;
   }
 } // end main
References oomph::CommandLineArgs::Argc, Global_Parameters::Gravity, oomph::DocInfo::number(), Global_Parameters::P, problem, oomph::DocInfo::set_directory(), and Flag_definition::setup().