MercuryDPM: MembraneSelfTest.cpp File Reference
MembraneSelfTest.cpp File Reference
#include <Mercury3D.h>
#include <Species/HertzianViscoelasticMindlinSpecies.h>
#include <Walls/Membrane/Membrane.h>
#include <CMakeDefinitions.h>
#include <climits>
Classes
class MembraneSelfTest
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc , char ** argv)
 {
   MembraneSelfTest problem;
   problem.setTimeMax(0.2);
   problem.setGravity(Vec3D(0.0,0.0,-9.81));
   /* Make sure to add an (unique) name here */
   problem.setName("MembraneSelfTest");
   // problem.setFileType(FileType::ONE_FILE);
   problem.dataFile.setFileType(FileType::NO_FILE);
   problem.restartFile.setFileType(FileType::ONE_FILE);
   problem.fStatFile.setFileType(FileType::NO_FILE);
   problem.eneFile.setFileType(FileType::NO_FILE);
   //Add any configuration which is modified often below...
   problem.setTimeStep(1e-5);
   problem.setSaveCount(floor(1.0/problem.getTimeStep()));
   if (helpers::readFromCommandLine(argc, argv, "-vtk"))
   {
       helpers::removeFromCommandline(argc, argv, "-vtk", 0);
       problem.setSaveCount(floor(0.01/problem.getTimeStep()));
       problem.setParticlesWriteVTK(true);
       // Write one file per timestep
       problem.wallHandler.setWriteVTK(FileType::MULTIPLE_FILES);
   }
   problem.solve(argc,argv);
   return 0;
 }
References e(), Eigen::bfloat16_impl::floor(), MULTIPLE_FILES, NO_FILE, ONE_FILE, problem, helpers::readFromCommandLine(), and helpers::removeFromCommandline().