MercuryDPM: Eigen::RotationBase< Derived, Dim_ > Class Template Reference
Eigen::RotationBase< Derived, Dim_ > Class Template Reference
Common base class for compact rotation representations.
#include <RotationBase.h>
Public Types
enum { Dim = Dim_ }
typedef internal::traits< Derived >::Scalar Scalar
typedef Matrix< Scalar, Dim, Dim > RotationMatrixType
typedef Matrix< Scalar, Dim, 1 > VectorType
Public Member Functions
EIGEN_DEVICE_FUNC const Derived & derived () const
EIGEN_DEVICE_FUNC Derived & derived ()
EIGEN_DEVICE_FUNC RotationMatrixType toRotationMatrix () const
EIGEN_DEVICE_FUNC RotationMatrixType matrix () const
EIGEN_DEVICE_FUNC Derived inverse () const
EIGEN_DEVICE_FUNC Transform< Scalar, Dim, Isometry > operator* (const Translation< Scalar, Dim > &t) const
EIGEN_DEVICE_FUNC RotationMatrixType operator* (const UniformScaling< Scalar > &s) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::rotation_base_generic_product_selector< Derived, OtherDerived, OtherDerived::IsVectorAtCompileTime >::ReturnType operator* (const EigenBase< OtherDerived > &e) const
template<int Mode, int Options>
EIGEN_DEVICE_FUNC Transform< Scalar, Dim, Mode > operator* (const Transform< Scalar, Dim, Mode, Options > &t) const
template<typename OtherVectorType >
EIGEN_DEVICE_FUNC VectorType _transformVector (const OtherVectorType &v) const
Friends
template<typename OtherDerived >
EIGEN_DEVICE_FUNC RotationMatrixType operator* (const EigenBase< OtherDerived > &l, const Derived &r)
EIGEN_DEVICE_FUNC friend Transform< Scalar, Dim, Affine > operator* (const DiagonalMatrix< Scalar, Dim > &l, const Derived &r)
Detailed Description
template<typename Derived, int Dim_>
class Eigen::RotationBase< Derived, Dim_ >
Common base class for compact rotation representations.
Template Parameters
Derived is the derived type, i.e., a rotation type
Dim_ the dimension of the space
Member Typedef Documentation
RotationMatrixType
template<typename Derived , int Dim_> typedef Matrix<Scalar, Dim, Dim> Eigen::RotationBase< Derived, Dim_ >::RotationMatrixType
corresponding linear transformation matrix type
Scalar
template<typename Derived , int Dim_> typedef internal::traits<Derived>::Scalar Eigen::RotationBase< Derived, Dim_ >::Scalar
the scalar type of the coefficients
VectorType
template<typename Derived , int Dim_> typedef Matrix<Scalar, Dim, 1> Eigen::RotationBase< Derived, Dim_ >::VectorType
Member Enumeration Documentation
anonymous enum
template<typename Derived , int Dim_> anonymous enum
Enumerator
Dim
 { Dim = Dim_ };
Member Function Documentation
_transformVector()
template<typename Derived , int Dim_> template<typename OtherVectorType > EIGEN_DEVICE_FUNC VectorType Eigen::RotationBase< Derived, Dim_ >::_transformVector (const OtherVectorType & v) const inline
{
     return toRotationMatrix() * v;
   }
References Eigen::RotationBase< Derived, Dim_ >::toRotationMatrix(), and v.
derived() [1/2]
template<typename Derived , int Dim_> EIGEN_DEVICE_FUNC Derived& Eigen::RotationBase< Derived, Dim_ >::derived () inline
 { return *static_cast<Derived*>(this); }
derived() [2/2]
template<typename Derived , int Dim_> EIGEN_DEVICE_FUNC const Derived& Eigen::RotationBase< Derived, Dim_ >::derived () const inline
 { return *static_cast<const Derived*>(this); }
Referenced by Eigen::RotationBase< Derived, Dim_ >::inverse(), Eigen::RotationBase< Derived, Dim_ >::matrix(), Eigen::RotationBase< Derived, Dim_ >::operator*(), Eigen::QuaternionBase< Derived >::operator*=(), and Eigen::RotationBase< Derived, Dim_ >::toRotationMatrix().
inverse()
template<typename Derived , int Dim_> EIGEN_DEVICE_FUNC Derived Eigen::RotationBase< Derived, Dim_ >::inverse () const inline
Returns
the inverse rotation
 { return derived().inverse(); }
References Eigen::RotationBase< Derived, Dim_ >::derived().
matrix()
template<typename Derived , int Dim_> EIGEN_DEVICE_FUNC RotationMatrixType Eigen::RotationBase< Derived, Dim_ >::matrix () const inline
Returns
an equivalent rotation matrix This function is added to be conform with the Transform class' naming scheme.
 { return derived().toRotationMatrix(); }
References Eigen::RotationBase< Derived, Dim_ >::derived().
operator*() [1/4]
template<typename Derived , int Dim_> template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::rotation_base_generic_product_selector<Derived, OtherDerived, OtherDerived::IsVectorAtCompileTime>::ReturnType Eigen::RotationBase< Derived, Dim_ >::operator* (const EigenBase< OtherDerived > & e) const inline
Returns
the concatenation of the rotation *this with a generic expression e e can be:
a DimxDim linear transformation matrix
a DimxDim diagonal matrix (axis aligned scaling)
a vector of size Dim
{
     return internal::rotation_base_generic_product_selector<Derived, OtherDerived>::run(derived(), e.derived());
   }
References Eigen::RotationBase< Derived, Dim_ >::derived(), e(), and run().
operator*() [2/4]
template<typename Derived , int Dim_> template<int Mode, int Options> EIGEN_DEVICE_FUNC Transform<Scalar, Dim, Mode> Eigen::RotationBase< Derived, Dim_ >::operator* (const Transform< Scalar, Dim, Mode, Options > & t) const inline
Returns
the concatenation of the rotation *this with a transformation t
{
     return toRotationMatrix() * t;
   }
References plotPSD::t, and Eigen::RotationBase< Derived, Dim_ >::toRotationMatrix().
operator*() [3/4]
template<typename Derived , int Dim_> EIGEN_DEVICE_FUNC Transform<Scalar, Dim, Isometry> Eigen::RotationBase< Derived, Dim_ >::operator* (const Translation< Scalar, Dim > & t) const inline
Returns
the concatenation of the rotation *this with a translation t
{
     return Transform<Scalar, Dim, Isometry>(*this) * t;
   }
References plotPSD::t.
operator*() [4/4]
template<typename Derived , int Dim_> EIGEN_DEVICE_FUNC RotationMatrixType Eigen::RotationBase< Derived, Dim_ >::operator* (const UniformScaling< Scalar > & s) const inline
Returns
the concatenation of the rotation *this with a uniform scaling s
{
     return toRotationMatrix() * s.factor();
   }
References s, and Eigen::RotationBase< Derived, Dim_ >::toRotationMatrix().
toRotationMatrix()
template<typename Derived , int Dim_> EIGEN_DEVICE_FUNC RotationMatrixType Eigen::RotationBase< Derived, Dim_ >::toRotationMatrix (void) const inline
Returns
an equivalent rotation matrix
 { return derived().toRotationMatrix(); }
References Eigen::RotationBase< Derived, Dim_ >::derived().
Referenced by Eigen::RotationBase< Derived, Dim_ >::_transformVector(), and Eigen::RotationBase< Derived, Dim_ >::operator*().
Friends And Related Function Documentation
operator* [1/2]
template<typename Derived , int Dim_> EIGEN_DEVICE_FUNC friend Transform<Scalar, Dim, Affine> operator* (const DiagonalMatrix< Scalar, Dim > & l, const Derived & r) friend
Returns
the concatenation of a scaling l with the rotation r
{
     Transform<Scalar, Dim, Affine> res(r);
     res.linear().applyOnTheLeft(l);
     return res;
   }
operator* [2/2]
template<typename Derived , int Dim_> template<typename OtherDerived > EIGEN_DEVICE_FUNC RotationMatrixType operator* (const EigenBase< OtherDerived > & l, const Derived & r) friend
Returns
the concatenation of a linear transformation l with the rotation r
{
     return l.derived() * r.toRotationMatrix();
   }
The documentation for this class was generated from the following files:
ForwardDeclarations.h
RotationBase.h