MercuryDPM: Eigen::internal::TensorContractionBlocking< ResScalar, LhsScalar, RhsScalar, StorageIndex, ShardingType > Class Template Reference
Eigen::internal::TensorContractionBlocking< ResScalar, LhsScalar, RhsScalar, StorageIndex, ShardingType > Class Template Reference
#include <TensorContractionBlocking.h>
Public Member Functions
EIGEN_DEVICE_FUNC TensorContractionBlocking (StorageIndex k, StorageIndex m, StorageIndex n, StorageIndex num_threads=1)
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE StorageIndex kc () const
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE StorageIndex mc () const
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE StorageIndex nc () const
Private Attributes
StorageIndex kc_
StorageIndex mc_
StorageIndex nc_
Constructor & Destructor Documentation
TensorContractionBlocking()
template<typename ResScalar , typename LhsScalar , typename RhsScalar , typename StorageIndex , int ShardingType = ShardByCol> EIGEN_DEVICE_FUNC Eigen::internal::TensorContractionBlocking< ResScalar, LhsScalar, RhsScalar, StorageIndex, ShardingType >::TensorContractionBlocking (StorageIndex k, StorageIndex m, StorageIndex n, StorageIndex num_threads = 1) inline
       : kc_(k), mc_(m), nc_(n) {
     if (ShardingType == ShardByCol) {
       computeProductBlockingSizes<LhsScalar, RhsScalar, 1>(kc_, mc_, nc_, num_threads);
     } else {
       computeProductBlockingSizes<LhsScalar, RhsScalar, 1>(kc_, nc_, mc_, num_threads);
     }
     const int rhs_packet_size = internal::packet_traits<RhsScalar>::size;
     kc_ = (rhs_packet_size <= 8 || kc_ <= rhs_packet_size) ? kc_ : (kc_ / rhs_packet_size) * rhs_packet_size;
   }
References Eigen::internal::TensorContractionBlocking< ResScalar, LhsScalar, RhsScalar, StorageIndex, ShardingType >::kc_, Eigen::internal::TensorContractionBlocking< ResScalar, LhsScalar, RhsScalar, StorageIndex, ShardingType >::mc_, Eigen::internal::TensorContractionBlocking< ResScalar, LhsScalar, RhsScalar, StorageIndex, ShardingType >::nc_, and Eigen::internal::ShardByCol.
Member Function Documentation
kc()
template<typename ResScalar , typename LhsScalar , typename RhsScalar , typename StorageIndex , int ShardingType = ShardByCol> EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE StorageIndex Eigen::internal::TensorContractionBlocking< ResScalar, LhsScalar, RhsScalar, StorageIndex, ShardingType >::kc () const inline
 { return kc_; }
References Eigen::internal::TensorContractionBlocking< ResScalar, LhsScalar, RhsScalar, StorageIndex, ShardingType >::kc_.
Referenced by Eigen::TensorContractionEvaluatorBase< Derived >::evalGemmPartial().
mc()
template<typename ResScalar , typename LhsScalar , typename RhsScalar , typename StorageIndex , int ShardingType = ShardByCol> EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE StorageIndex Eigen::internal::TensorContractionBlocking< ResScalar, LhsScalar, RhsScalar, StorageIndex, ShardingType >::mc () const inline
 { return mc_; }
References Eigen::internal::TensorContractionBlocking< ResScalar, LhsScalar, RhsScalar, StorageIndex, ShardingType >::mc_.
Referenced by Eigen::TensorContractionEvaluatorBase< Derived >::evalGemmPartial().
nc()
template<typename ResScalar , typename LhsScalar , typename RhsScalar , typename StorageIndex , int ShardingType = ShardByCol> EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE StorageIndex Eigen::internal::TensorContractionBlocking< ResScalar, LhsScalar, RhsScalar, StorageIndex, ShardingType >::nc () const inline
 { return nc_; }
References Eigen::internal::TensorContractionBlocking< ResScalar, LhsScalar, RhsScalar, StorageIndex, ShardingType >::nc_.
Referenced by Eigen::TensorContractionEvaluatorBase< Derived >::evalGemmPartial().
Member Data Documentation
kc_
template<typename ResScalar , typename LhsScalar , typename RhsScalar , typename StorageIndex , int ShardingType = ShardByCol> StorageIndex Eigen::internal::TensorContractionBlocking< ResScalar, LhsScalar, RhsScalar, StorageIndex, ShardingType >::kc_ private
Referenced by Eigen::internal::TensorContractionBlocking< ResScalar, LhsScalar, RhsScalar, StorageIndex, ShardingType >::kc(), and Eigen::internal::TensorContractionBlocking< ResScalar, LhsScalar, RhsScalar, StorageIndex, ShardingType >::TensorContractionBlocking().
mc_
template<typename ResScalar , typename LhsScalar , typename RhsScalar , typename StorageIndex , int ShardingType = ShardByCol> StorageIndex Eigen::internal::TensorContractionBlocking< ResScalar, LhsScalar, RhsScalar, StorageIndex, ShardingType >::mc_ private
Referenced by Eigen::internal::TensorContractionBlocking< ResScalar, LhsScalar, RhsScalar, StorageIndex, ShardingType >::mc(), and Eigen::internal::TensorContractionBlocking< ResScalar, LhsScalar, RhsScalar, StorageIndex, ShardingType >::TensorContractionBlocking().
nc_
template<typename ResScalar , typename LhsScalar , typename RhsScalar , typename StorageIndex , int ShardingType = ShardByCol> StorageIndex Eigen::internal::TensorContractionBlocking< ResScalar, LhsScalar, RhsScalar, StorageIndex, ShardingType >::nc_ private
Referenced by Eigen::internal::TensorContractionBlocking< ResScalar, LhsScalar, RhsScalar, StorageIndex, ShardingType >::nc(), and Eigen::internal::TensorContractionBlocking< ResScalar, LhsScalar, RhsScalar, StorageIndex, ShardingType >::TensorContractionBlocking().
The documentation for this class was generated from the following file:
TensorContractionBlocking.h