MercuryDPM: Eigen::internal::count_bits_impl< BitsType, EnableIf > Struct Template Reference
Eigen::internal::count_bits_impl< BitsType, EnableIf > Struct Template Reference
#include <MathFunctions.h>
Static Public Member Functions
static EIGEN_DEVICE_FUNC int clz (BitsType bits)
static EIGEN_DEVICE_FUNC int ctz (BitsType bits)
Member Function Documentation
clz()
template<typename BitsType , typename EnableIf = void> static EIGEN_DEVICE_FUNC int Eigen::internal::count_bits_impl< BitsType, EnableIf >::clz (BitsType bits) inline static
{
     int n = CHAR_BIT * sizeof(BitsType);
     int shift = n / 2;
     while (bits > 0 && shift > 0) {
       BitsType y = bits >> shift;
       if (y > 0) {
         n -= shift;
         bits = y;
       }
       shift /= 2;
     }
     if (shift == 0) {
       --n;
     }
     return n;
   }
References Eigen::test::bits(), n, and Eigen::internal::y.
Referenced by Eigen::internal::clz().
ctz()
template<typename BitsType , typename EnableIf = void> static EIGEN_DEVICE_FUNC int Eigen::internal::count_bits_impl< BitsType, EnableIf >::ctz (BitsType bits) inline static
{
     int n = CHAR_BIT * sizeof(BitsType);
     int shift = n / 2;
     while (bits > 0 && shift > 0) {
       BitsType y = bits << shift;
       if (y > 0) {
         n -= shift;
         bits = y;
       }
       shift /= 2;
     }
     if (shift == 0) {
       --n;
     }
     return n;
   }
References Eigen::test::bits(), n, and Eigen::internal::y.
Referenced by Eigen::internal::ctz().
The documentation for this struct was generated from the following file:
MathFunctions.h