MercuryDPM: Eigen::Diagonal< MatrixType, DiagIndex_ > Class Template Reference
Eigen::Diagonal< MatrixType, DiagIndex_ > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
Expression of a diagonal/subdiagonal/superdiagonal in a matrix.
#include <Diagonal.h>
Public Types
enum { DiagIndex = DiagIndex_ }
typedef internal::dense_xpr_base< Diagonal >::type Base
typedef std::conditional_t< internal::is_lvalue< MatrixType >::value, Scalar, const Scalar > ScalarWithConstIfNotLvalue
Public Member Functions
EIGEN_DEVICE_FUNC Diagonal (MatrixType &matrix, Index a_index=DiagIndex)
EIGEN_DEVICE_FUNC Index rows () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index innerStride () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index outerStride () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC ScalarWithConstIfNotLvalue * data ()
EIGEN_DEVICE_FUNC const Scalar * data () const
EIGEN_DEVICE_FUNC Scalar & coeffRef (Index row, Index)
EIGEN_DEVICE_FUNC const Scalar & coeffRef (Index row, Index) const
EIGEN_DEVICE_FUNC CoeffReturnType coeff (Index row, Index) const
EIGEN_DEVICE_FUNC Scalar & coeffRef (Index idx)
EIGEN_DEVICE_FUNC const Scalar & coeffRef (Index idx) const
EIGEN_DEVICE_FUNC CoeffReturnType coeff (Index idx) const
EIGEN_DEVICE_FUNC const internal::remove_all_t< typename MatrixType::Nested > & nestedExpression () const
EIGEN_DEVICE_FUNC Index index () const
Protected Attributes
internal::ref_selector< MatrixType >::non_const_type m_matrix
const internal::variable_if_dynamicindex< Index, DiagIndex > m_index
Private Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EIGEN_CONSTEXPR Index absDiagIndex () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EIGEN_CONSTEXPR Index rowOffset () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EIGEN_CONSTEXPR Index colOffset () const EIGEN_NOEXCEPT
template<int LoadMode>
MatrixType::PacketReturnType packet (Index) const
template<int LoadMode>
MatrixType::PacketReturnType packet (Index, Index) const
Detailed Description
template<typename MatrixType, int DiagIndex_>
class Eigen::Diagonal< MatrixType, DiagIndex_ >
Expression of a diagonal/subdiagonal/superdiagonal in a matrix.
Template Parameters
MatrixType the type of the object in which we are taking a sub/main/super diagonal
DiagIndex the index of the sub/super diagonal. The default is 0 and it means the main diagonal. A positive value means a superdiagonal, a negative value means a subdiagonal. You can also use DynamicIndex so the index can be set at runtime.
The matrix is not required to be square.
This class represents an expression of the main diagonal, or any sub/super diagonal of a square matrix. It is the return type of MatrixBase::diagonal() and MatrixBase::diagonal(Index) and most of the time this is the only way it is used.
See also
MatrixBase::diagonal(), MatrixBase::diagonal(Index)
Member Typedef Documentation
Base
template<typename MatrixType , int DiagIndex_> typedef internal::dense_xpr_base<Diagonal>::type Eigen::Diagonal< MatrixType, DiagIndex_ >::Base
ScalarWithConstIfNotLvalue
template<typename MatrixType , int DiagIndex_> typedef std::conditional_t<internal::is_lvalue<MatrixType>::value, Scalar, const Scalar> Eigen::Diagonal< MatrixType, DiagIndex_ >::ScalarWithConstIfNotLvalue
Member Enumeration Documentation
anonymous enum
template<typename MatrixType , int DiagIndex_> anonymous enum
Enumerator
DiagIndex
 { DiagIndex = DiagIndex_ };
Constructor & Destructor Documentation
Diagonal()
template<typename MatrixType , int DiagIndex_> EIGEN_DEVICE_FUNC Eigen::Diagonal< MatrixType, DiagIndex_ >::Diagonal (MatrixType & matrix, Index a_index = DiagIndex) inline explicit
       : m_matrix(matrix), m_index(a_index) {
     eigen_assert(a_index <= m_matrix.cols() && -a_index <= m_matrix.rows());
   }
References eigen_assert.
Member Function Documentation
absDiagIndex()
template<typename MatrixType , int DiagIndex_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EIGEN_CONSTEXPR Index Eigen::Diagonal< MatrixType, DiagIndex_ >::absDiagIndex () const inline private
{
     return m_index.value() > 0 ? m_index.value() : -m_index.value();
   }
References Eigen::internal::variable_if_dynamicindex< T, Value >::value().
coeff() [1/2]
template<typename MatrixType , int DiagIndex_> EIGEN_DEVICE_FUNC CoeffReturnType Eigen::Diagonal< MatrixType, DiagIndex_ >::coeff (Index idx) const inline
{
     return m_matrix.coeff(idx + rowOffset(), idx + colOffset());
   }
coeff() [2/2]
template<typename MatrixType , int DiagIndex_> EIGEN_DEVICE_FUNC CoeffReturnType Eigen::Diagonal< MatrixType, DiagIndex_ >::coeff (Index row, Index) const inline
{
     return m_matrix.coeff(row + rowOffset(), row + colOffset());
   }
References row().
coeffRef() [1/4]
template<typename MatrixType , int DiagIndex_> EIGEN_DEVICE_FUNC Scalar& Eigen::Diagonal< MatrixType, DiagIndex_ >::coeffRef (Index idx) inline
{
     EIGEN_STATIC_ASSERT_LVALUE(MatrixType)
     return m_matrix.coeffRef(idx + rowOffset(), idx + colOffset());
   }
References EIGEN_STATIC_ASSERT_LVALUE.
coeffRef() [2/4]
template<typename MatrixType , int DiagIndex_> EIGEN_DEVICE_FUNC const Scalar& Eigen::Diagonal< MatrixType, DiagIndex_ >::coeffRef (Index idx) const inline
{
     return m_matrix.coeffRef(idx + rowOffset(), idx + colOffset());
   }
coeffRef() [3/4]
template<typename MatrixType , int DiagIndex_> EIGEN_DEVICE_FUNC Scalar& Eigen::Diagonal< MatrixType, DiagIndex_ >::coeffRef (Index row, Index) inline
{
     EIGEN_STATIC_ASSERT_LVALUE(MatrixType)
     return m_matrix.coeffRef(row + rowOffset(), row + colOffset());
   }
References EIGEN_STATIC_ASSERT_LVALUE, and row().
Referenced by foo().
coeffRef() [4/4]
template<typename MatrixType , int DiagIndex_> EIGEN_DEVICE_FUNC const Scalar& Eigen::Diagonal< MatrixType, DiagIndex_ >::coeffRef (Index row, Index) const inline
{
     return m_matrix.coeffRef(row + rowOffset(), row + colOffset());
   }
References row().
colOffset()
template<typename MatrixType , int DiagIndex_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EIGEN_CONSTEXPR Index Eigen::Diagonal< MatrixType, DiagIndex_ >::colOffset () const inline private
{
     return m_index.value() > 0 ? m_index.value() : 0;
   }
References Eigen::internal::variable_if_dynamicindex< T, Value >::value().
cols()
template<typename MatrixType , int DiagIndex_> EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::Diagonal< MatrixType, DiagIndex_ >::cols () const inline
 { return 1; }
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
data() [1/2]
template<typename MatrixType , int DiagIndex_> EIGEN_DEVICE_FUNC ScalarWithConstIfNotLvalue* Eigen::Diagonal< MatrixType, DiagIndex_ >::data () inline
 { return &(m_matrix.coeffRef(rowOffset(), colOffset())); }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
data() [2/2]
template<typename MatrixType , int DiagIndex_> EIGEN_DEVICE_FUNC const Scalar* Eigen::Diagonal< MatrixType, DiagIndex_ >::data () const inline
 { return &(m_matrix.coeffRef(rowOffset(), colOffset())); }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
index()
template<typename MatrixType , int DiagIndex_> EIGEN_DEVICE_FUNC Index Eigen::Diagonal< MatrixType, DiagIndex_ >::index () const inline
 { return m_index.value(); }
innerStride()
template<typename MatrixType , int DiagIndex_> EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::Diagonal< MatrixType, DiagIndex_ >::innerStride () const inline
{
     return m_matrix.outerStride() + 1;
   }
nestedExpression()
template<typename MatrixType , int DiagIndex_> EIGEN_DEVICE_FUNC const internal::remove_all_t<typename MatrixType::Nested>& Eigen::Diagonal< MatrixType, DiagIndex_ >::nestedExpression () const inline
{
     return m_matrix;
   }
outerStride()
template<typename MatrixType , int DiagIndex_> EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::Diagonal< MatrixType, DiagIndex_ >::outerStride () const inline
 { return 0; }
packet() [1/2]
template<typename MatrixType , int DiagIndex_> template<int LoadMode> MatrixType::PacketReturnType Eigen::Diagonal< MatrixType, DiagIndex_ >::packet (Index) const private
packet() [2/2]
template<typename MatrixType , int DiagIndex_> template<int LoadMode> MatrixType::PacketReturnType Eigen::Diagonal< MatrixType, DiagIndex_ >::packet (Index , Index) const private
rowOffset()
template<typename MatrixType , int DiagIndex_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EIGEN_CONSTEXPR Index Eigen::Diagonal< MatrixType, DiagIndex_ >::rowOffset () const inline private
{
     return m_index.value() > 0 ? 0 : -m_index.value();
   }
References Eigen::internal::variable_if_dynamicindex< T, Value >::value().
rows()
template<typename MatrixType , int DiagIndex_> EIGEN_DEVICE_FUNC Index Eigen::Diagonal< MatrixType, DiagIndex_ >::rows () const inline
{
     return m_index.value() < 0 ? numext::mini<Index>(m_matrix.cols(), m_matrix.rows() + m_index.value())
                                : numext::mini<Index>(m_matrix.rows(), m_matrix.cols() - m_index.value());
   }
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
Member Data Documentation
m_index
template<typename MatrixType , int DiagIndex_> const internal::variable_if_dynamicindex<Index, DiagIndex> Eigen::Diagonal< MatrixType, DiagIndex_ >::m_index protected
m_matrix
template<typename MatrixType , int DiagIndex_> internal::ref_selector<MatrixType>::non_const_type Eigen::Diagonal< MatrixType, DiagIndex_ >::m_matrix protected
The documentation for this class was generated from the following file:
Diagonal.h