MercuryDPM: Eigen::internal::ternary_evaluator< CwiseTernaryOp< TernaryOp, Arg1, Arg2, Arg3 >, IndexBased, IndexBased > Struct Template Reference
Eigen::internal::ternary_evaluator< CwiseTernaryOp< TernaryOp, Arg1, Arg2, Arg3 >, IndexBased, IndexBased > Struct Template Reference
#include <CoreEvaluators.h>
Classes
struct Data
Public Types
enum {
CoeffReadCost , Arg1Flags = evaluator<Arg1>::Flags , Arg2Flags = evaluator<Arg2>::Flags , Arg3Flags = evaluator<Arg3>::Flags ,
SameType , StorageOrdersAgree , Flags0 , Flags = (Flags0 & ~RowMajorBit) | (Arg1Flags & RowMajorBit) ,
Alignment
}
typedef CwiseTernaryOp< TernaryOp, Arg1, Arg2, Arg3 > XprType
typedef XprType::CoeffReturnType CoeffReturnType
Public Types inherited from Eigen::internal::evaluator_base< CwiseTernaryOp< TernaryOp, Arg1, Arg2, Arg3 > >
enum
typedef traits< CwiseTernaryOp< TernaryOp, Arg1, Arg2, Arg3 > > ExpressionTraits
Public Member Functions
EIGEN_DEVICE_FUNC ternary_evaluator (const XprType &xpr)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
template<int LoadMode, typename PacketType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType packet (Index row, Index col) const
template<int LoadMode, typename PacketType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType packet (Index index) const
Public Member Functions inherited from Eigen::internal::evaluator_base< CwiseTernaryOp< TernaryOp, Arg1, Arg2, Arg3 > >
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE evaluator_base ()=default
Protected Attributes
Data m_d
Member Typedef Documentation
CoeffReturnType
template<typename TernaryOp , typename Arg1 , typename Arg2 , typename Arg3 > typedef XprType::CoeffReturnType Eigen::internal::ternary_evaluator< CwiseTernaryOp< TernaryOp, Arg1, Arg2, Arg3 >, IndexBased, IndexBased >::CoeffReturnType
XprType
template<typename TernaryOp , typename Arg1 , typename Arg2 , typename Arg3 > typedef CwiseTernaryOp<TernaryOp, Arg1, Arg2, Arg3> Eigen::internal::ternary_evaluator< CwiseTernaryOp< TernaryOp, Arg1, Arg2, Arg3 >, IndexBased, IndexBased >::XprType
Member Enumeration Documentation
anonymous enum
template<typename TernaryOp , typename Arg1 , typename Arg2 , typename Arg3 > anonymous enum
Enumerator
CoeffReadCost
Arg1Flags
Arg2Flags
Arg3Flags
SameType
StorageOrdersAgree
Flags0
Flags
Alignment
        {
     CoeffReadCost = int(evaluator<Arg1>::CoeffReadCost) + int(evaluator<Arg2>::CoeffReadCost) +
                     int(evaluator<Arg3>::CoeffReadCost) + int(functor_traits<TernaryOp>::Cost),
     Arg1Flags = evaluator<Arg1>::Flags,
     Arg2Flags = evaluator<Arg2>::Flags,
     Arg3Flags = evaluator<Arg3>::Flags,
     SameType = is_same<typename Arg1::Scalar, typename Arg2::Scalar>::value &&
                is_same<typename Arg1::Scalar, typename Arg3::Scalar>::value,
     StorageOrdersAgree = (int(Arg1Flags) & RowMajorBit) == (int(Arg2Flags) & RowMajorBit) &&
                          (int(Arg1Flags) & RowMajorBit) == (int(Arg3Flags) & RowMajorBit),
     Flags0 = (int(Arg1Flags) | int(Arg2Flags) | int(Arg3Flags)) &
              (HereditaryBits |
               (int(Arg1Flags) & int(Arg2Flags) & int(Arg3Flags) &
                ((StorageOrdersAgree ? LinearAccessBit : 0) |
                 (functor_traits<TernaryOp>::PacketAccess && StorageOrdersAgree && SameType ? PacketAccessBit : 0)))),
     Flags = (Flags0 & ~RowMajorBit) | (Arg1Flags & RowMajorBit),
     Alignment = plain_enum_min(plain_enum_min(evaluator<Arg1>::Alignment, evaluator<Arg2>::Alignment),
                                evaluator<Arg3>::Alignment)
   };
Constructor & Destructor Documentation
ternary_evaluator()
template<typename TernaryOp , typename Arg1 , typename Arg2 , typename Arg3 > EIGEN_DEVICE_FUNC Eigen::internal::ternary_evaluator< CwiseTernaryOp< TernaryOp, Arg1, Arg2, Arg3 >, IndexBased, IndexBased >::ternary_evaluator (const XprType & xpr) inline explicit
                                                                    : m_d(xpr) {
     EIGEN_INTERNAL_CHECK_COST_VALUE(functor_traits<TernaryOp>::Cost);
     EIGEN_INTERNAL_CHECK_COST_VALUE(CoeffReadCost);
   }
References EIGEN_INTERNAL_CHECK_COST_VALUE.
Member Function Documentation
coeff() [1/2]
template<typename TernaryOp , typename Arg1 , typename Arg2 , typename Arg3 > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::ternary_evaluator< CwiseTernaryOp< TernaryOp, Arg1, Arg2, Arg3 >, IndexBased, IndexBased >::coeff (Index index) const inline
{
     return m_d.func()(m_d.arg1Impl.coeff(index), m_d.arg2Impl.coeff(index), m_d.arg3Impl.coeff(index));
   }
coeff() [2/2]
template<typename TernaryOp , typename Arg1 , typename Arg2 , typename Arg3 > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::ternary_evaluator< CwiseTernaryOp< TernaryOp, Arg1, Arg2, Arg3 >, IndexBased, IndexBased >::coeff (Index row, Index col) const inline
{
     return m_d.func()(m_d.arg1Impl.coeff(row, col), m_d.arg2Impl.coeff(row, col), m_d.arg3Impl.coeff(row, col));
   }
References col(), and row().
packet() [1/2]
template<typename TernaryOp , typename Arg1 , typename Arg2 , typename Arg3 > template<int LoadMode, typename PacketType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType Eigen::internal::ternary_evaluator< CwiseTernaryOp< TernaryOp, Arg1, Arg2, Arg3 >, IndexBased, IndexBased >::packet (Index index) const inline
{
     return m_d.func().packetOp(m_d.arg1Impl.template packet<LoadMode, PacketType>(index),
                                m_d.arg2Impl.template packet<LoadMode, PacketType>(index),
                                m_d.arg3Impl.template packet<LoadMode, PacketType>(index));
   }
packet() [2/2]
template<typename TernaryOp , typename Arg1 , typename Arg2 , typename Arg3 > template<int LoadMode, typename PacketType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType Eigen::internal::ternary_evaluator< CwiseTernaryOp< TernaryOp, Arg1, Arg2, Arg3 >, IndexBased, IndexBased >::packet (Index row, Index col) const inline
{
     return m_d.func().packetOp(m_d.arg1Impl.template packet<LoadMode, PacketType>(row, col),
                                m_d.arg2Impl.template packet<LoadMode, PacketType>(row, col),
                                m_d.arg3Impl.template packet<LoadMode, PacketType>(row, col));
   }
References col(), and row().
Member Data Documentation
m_d
template<typename TernaryOp , typename Arg1 , typename Arg2 , typename Arg3 > Data Eigen::internal::ternary_evaluator< CwiseTernaryOp< TernaryOp, Arg1, Arg2, Arg3 >, IndexBased, IndexBased >::m_d protected
The documentation for this struct was generated from the following file:
CoreEvaluators.h