MercuryDPM: InputData Namespace Reference
InputData Namespace Reference
Functions
def LoadPebbles (OPT, DATA)
def LoadMesh (OPT, DATA)
Function Documentation
LoadMesh()
def InputData.LoadMesh (OPT, DATA)
 def LoadMesh(OPT, DATA):
     from stl import mesh
     filename = OPT['stlInputDir'] + OPT['stlFileName']
     stl_mesh = mesh.Mesh.from_file(filename)
     DATA['stlMesh'] = stl_mesh
     return OPT, DATA
Referenced by MClump.main().
LoadPebbles()
def InputData.LoadPebbles (OPT, DATA)
 def LoadPebbles(OPT, DATA):
     import numpy as np
     # This function loads pebbles data in the CLUMP library (csv) format
     filename = OPT['clumpInputDir'] + OPT['clumpFileName']
     textfile = open(filename, "r")
     content_list = textfile.readlines()
     pebbles = np.zeros([len(content_list), 4])
     for i in range(len(content_list)):
         content_list[i] = content_list[i].replace("\n", "")
         word_list = content_list[i].split(',')
         for j in range (4):
             pebbles[i][j] = float(word_list[j])
     DATA['pebbles'] = pebbles
     if (OPT['verbose']): print(str(len(pebbles)) + " pebbles loaded \n")
     return OPT, DATA
References Eigen::internal.print(), oomph::DoubleVectorHelpers.split(), and compute_granudrum_aor.str.