MercuryDPM: SolidBeamUnsteady.cpp File Reference
SolidBeamUnsteady.cpp File Reference
#include "Oomph/SolidProblem.h"
#include "Math/Helpers.h"
Classes
class Beam
Defines a SolidProblem of element type RefineableQDPVDElement<3,2>. Add functionality to write output.
Functions
int main ()
Function Documentation
main()
int main ()
Simulates a cubic rod (20mm x 2mm x 2mm) of density 2500 kg/m^3, elastic modulus 100 MPa, fixed on left side, bent by gravity
 {
     // Solve the problem
     Beam problem;
     problem.setName("SolidBeamUnsteady");
     problem.setElasticModulus(1e8);
     problem.setDensity(2500);
     problem.setSolidCubicMesh(20, 2, 2, 0, 0.2, 0, 0.02, 0, 0.02);
     problem.pinBoundary(Beam::Boundary::X_MIN);
     problem.setBodyForceAsGravity();
     problem.setNewtonSolverTolerance(3e-8);
     problem.prepareForSolve();
     problem.linear_solver_pt()->disable_doc_time();
     //problem.disable_info_in_newton_solve();
     //set time scale of oscillation
     //https://vlab.amrita.edu/?sub=3&brch=175&sim=1080&cnt=1
     double b = 0.02, d = 0.02, l = 0.2;
     double inertia = b*d*d*d/12;
     double omega = 1.875*1.875*sqrt(problem.getElasticModulus()*inertia/(problem.getDensity()*b*d*std::pow(l,4)));
     double timeScale = 2*constants::pi/omega; //0.06
     // simulate two oscillations, check energy balance
     problem.solveUnsteady(2.0*timeScale, 0.04*timeScale, 10);
     return 0;
 }
References b, e(), Eigen::internal::omega(), constants::pi, Eigen::bfloat16_impl::pow(), problem, sqrt(), and Global_Physical_Variables::timeScale.