MercuryDPM: cxx11_tensor_custom_op.cpp File Reference
cxx11_tensor_custom_op.cpp File Reference
#include "main.h"
#include <Eigen/CXX11/Tensor>
Classes
struct InsertZeros< TensorType >
struct BatchMatMul< TensorType >
Functions
static void test_custom_unary_op ()
static void test_custom_binary_op ()
EIGEN_DECLARE_TEST (cxx11_tensor_custom_op)
Function Documentation
EIGEN_DECLARE_TEST()
EIGEN_DECLARE_TEST (cxx11_tensor_custom_op)
{
   CALL_SUBTEST(test_custom_unary_op());
   CALL_SUBTEST(test_custom_binary_op());
 }
References CALL_SUBTEST, test_custom_binary_op(), and test_custom_unary_op().
test_custom_binary_op()
static void test_custom_binary_op () static
{
   Tensor<float, 3> tensor1(2, 3, 5);
   tensor1.setRandom();
   Tensor<float, 3> tensor2(3, 7, 5);
   tensor2.setRandom();
   Tensor<float, 3> result = tensor1.customOp(tensor2, BatchMatMul());
   for (int i = 0; i < 5; ++i) {
     typedef Tensor<float, 3>::DimensionPair DimPair;
     array<DimPair, 1> dims;
     dims[0] = DimPair(1, 0);
     Tensor<float, 2> reference = tensor1.chip<2>(i).contract(tensor2.chip<2>(i), dims);
     TensorRef<Tensor<float, 2> > val = result.chip<2>(i);
     for (int j = 0; j < 2; ++j) {
       for (int k = 0; k < 7; ++k) {
         VERIFY_IS_APPROX(val(j, k), reference(j, k));
       }
     }
   }
 }
References Eigen::TensorBase< Derived, AccessLevel >::chip(), i, j, k, Eigen::TensorBase< Derived, AccessLevel >::setRandom(), calibrate::val, and VERIFY_IS_APPROX.
Referenced by EIGEN_DECLARE_TEST().
test_custom_unary_op()
static void test_custom_unary_op () static
{
   Tensor<float, 2> tensor(3, 5);
   tensor.setRandom();
   Tensor<float, 2> result = tensor.customOp(InsertZeros());
   VERIFY_IS_EQUAL(result.dimension(0), 6);
   VERIFY_IS_EQUAL(result.dimension(1), 10);
   for (int i = 0; i < 6; i += 2) {
     for (int j = 0; j < 10; j += 2) {
       VERIFY_IS_EQUAL(result(i, j), tensor(i / 2, j / 2));
     }
   }
   for (int i = 1; i < 6; i += 2) {
     for (int j = 1; j < 10; j += 2) {
       VERIFY_IS_EQUAL(result(i, j), 0);
     }
   }
 }
References Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::dimension(), i, j, Eigen::TensorBase< Derived, AccessLevel >::setRandom(), and VERIFY_IS_EQUAL.
Referenced by EIGEN_DECLARE_TEST().