MercuryDPM: File Class Reference
File Class Reference
#include <File.h>
Public Member Functions
File ()
constructor
File (const File &)
default copy constructor
virtual ~File ()
destructor
std::fstream & getFstream ()
Allows to access the member variable File::fstream_.
const std::string & getName () const
Allows to access the file name, e.g., "problem.data".
const std::string getFullName () const
Also allows to access the file name, however with additional information which is the file counter, e.g., "problem.data.0000".
const std::string getFullName (unsigned) const
Allows to access the file name, however with additional information which is the file counter, e.g., "problem.data.0000".
void setName (const std::string &name)
Sets the file name, e.g. "Name.data".
FileType getFileType () const
Gets the file type e.g. NOFILE, ONEFILE and MULTIPLE FILES. File::fileType_.
void setFileType (FileType fileType)
Sets the type of file needed to write into or read from. File::fileType_.
unsigned int getCounter () const
In case of multiple files, File::getCounter() returns the the number (FILE::Counter_) of the next file i.e. to be opened for reading or writing; NOTE: needed only if FILE::fileType_ is multiple files.
void setCounter (unsigned int counter)
Allows the user to set the file counter according to his need. Sets File::counter_.
void increaseCounter ()
void decreaseCounter ()
std::fstream::openmode getOpenMode () const
Allows the user to know the file mode i.e. gets File::openMode_.
void setOpenMode (std::fstream::openmode openMode)
Allows the user to Sets File::openMode_.
unsigned int getSaveCount () const
Gets File::saveCount_.
void writeFirstAndLastTimeStep ()
Sets File::saveCount_ to the highest possible value such that only the first and last time step is written.
void setSaveCount (unsigned int saveCount)
Sets File::saveCount_.
unsigned int getLastSavedTimeStep () const
Gets File::nextSavedTimeStep_.
void setLastSavedTimeStep (unsigned int lastSavedTimeStep)
Sets File::nextSavedTimeStep_.
bool saveCurrentTimeStep (unsigned int ntimeSteps)
determined if this time step has to be written; if so, opens the output file
bool saveCurrentTimeStepNoFileTypeCheck (unsigned int ntimeSteps)
void read (std::istream &is)
read function, which accepts an input stream std::istream.
void write (std::ostream &os) const
print function, which accepts an std::stringstream as input.
bool open ()
Checks if the file stream fstream_ has any issues while opening. Alongside, it also increments the nextSavedTimeStep and the counter. the counter is useful when the fileType_ is set to Multiple or Multiple with padded.
bool openWrite (unsigned)
First sets openmode to write (and append in some cases), then calls open().
bool openWriteNoAppend (unsigned)
bool open (std::fstream::openmode openMode)
First calls setOpenMode(openMode), then calls open().
void close ()
Closes the file by calling fstream_.close()
void setlogarithmicSaveCount (const Mdouble logarithmicSaveCountBase)
the function to set the user input base of logarithmic saving count
Private Attributes
std::string name_
name of the file.
std::fstream fstream_
Stream object used to read/write data files.
FileType fileType_
fileType_ indicates the type of the files. Whether it is No file, one file or multiple file as described in the description of the class.
unsigned int counter_
counts the number of already opened files, i.e. counter=1 means .0000 exists
std::fstream::openmode openMode_
A variable to indicate how the file should be opened i.e. in, out, ... see http://en.cppreference.com (std::fstream::out by default)
unsigned int saveCount_
Allows one to define the number of time steps to be skipped to make a snap shot. E.g. TMax = 100, saveCount_ = 10, timeStep = 1; It stores data at t={0,10,20,30,40...100}. And if TMax =101, it stores data at t={0,10,20,30,...100,101}.
Mdouble logarithmicSaveCountBase_
the switch allow user to set saveCount in logarithmic timescale with equal distance , the number is the base of log scale from user input
unsigned int lastSavedTimeStep_
the time step at which the next write or read operation has to happen.
Friends
std::ostream & operator<< (std::ostream &os, const File &o)
Operator overloading used to write data obtained from an object of class File into an output stream. It also returns a reference to the output stream.
std::istream & operator>> (std::istream &is, File &o)
Operator overloading used to read data from the input stream into member variables of an object of class File. It also returns a reference of type std::istream&.
Detailed Description
The instance of class File, for e.g. member variables of class Files (objects of type File) in Files.h, allows to manipulate the the input and output stream. In layman terms: In MercuryDPM, in order to read and write data into or from files we use the methods defined in Files.h. These methods implicitly calls the methods of class File and thereby allowing us to write or read data.
Constructor & Destructor Documentation
File() [1/2]
File::File ()
constructor
A File constructor which initialises FILE::saveCount_=0, sets the default filename as FILE::name_ = "", sets the default FileType to be as FileType::ONE_FILE and few other variables as listed below.
 {
     //sets the default for the number of time steps to be skipped
     //in between each saved "snapshot" of the system to zero
     //(i.e. records every time step by default)
     saveCount_ = 0;
     // file name has to be set by the user
     name_ = "out";
     // output into a single file by default
     fileType_ = FileType::ONE_FILE;
     // counter of currently open file set to 0 by default
     counter_ = 0;
     //stores the time step of the last write/read operation; NEVER by default
     lastSavedTimeStep_ = NEVER;
     //sets the default openMode to "out"
     //i.e. files will by default be written to, not read from.
     openMode_ = std::fstream::out;
     //sets the default logarithmicSaveCount to zero
     logarithmicSaveCountBase_ = 0;
 }
References counter_, fileType_, lastSavedTimeStep_, logarithmicSaveCountBase_, name_, NEVER, ONE_FILE, openMode_, out(), and saveCount_.
File() [2/2]
File::File (const File & f)
default copy constructor
Copy everything but the fstream object (which cannot be copied).
Parameters
[in] f the file object that is to be copied.
 {
     saveCount_ = f.saveCount_;
     name_ = f.name_;
     fileType_ = f.fileType_;
     counter_ = f.counter_;
     lastSavedTimeStep_ = f.lastSavedTimeStep_;
     openMode_ = f.openMode_;
     logarithmicSaveCountBase_ = f.logarithmicSaveCountBase_;
 }
References counter_, f(), fileType_, lastSavedTimeStep_, logarithmicSaveCountBase_, name_, openMode_, and saveCount_.
~File()
File::~File () virtual default
destructor
Destructor
Member Function Documentation
close()
void File::close ()
Closes the file by calling fstream_.close()
 {
     fstream_.close();
 }
References fstream_.
Referenced by DPMBase::closeFiles(), CGHandler::evaluateDataFiles(), CGHandler::evaluateRestartFiles(), DPMBase::readDataFile(), DPMBase::readRestartFile(), CSCInit::save(), RotatingDrumBidisperseInitialise::save(), ClosedCSCWalls::saveWalls(), CSCWalls::saveWalls(), DPMBase::writeDataFile(), DPMBase::writeEneFile(), DPMBase::writeFStatFile(), and DPMBase::writeRestartFile().
decreaseCounter()
void File::decreaseCounter () inline
 {counter_--;}
References counter_.
Referenced by CGHandler::restart().
getCounter()
unsigned int File::getCounter () const
In case of multiple files, File::getCounter() returns the the number (FILE::Counter_) of the next file i.e. to be opened for reading or writing; NOTE: needed only if FILE::fileType_ is multiple files.
Returns
unsigned int counter_
 {
     return counter_;
 }
References counter_.
Referenced by DPMBase::findNextExistingDataFile(), getFullName(), openWrite(), DPMBase::readDataFile(), SaveCountUnitTest::SaveCountUnitTest(), DPMBase::writeEneTimeStep(), Drum::writeEneTimeStep(), Penetration::writeEneTimeStep(), Silo::writeEneTimeStep(), and DPMBase::writeOutputFiles().
getFileType()
FileType File::getFileType () const
Gets the file type e.g. NOFILE, ONEFILE and MULTIPLE FILES. File::fileType_.
Returns
Returns the FileType (File::fileType_)
 {
     return fileType_;
 }
References fileType_.
Referenced by commandLineCG(), CGHandler::evaluateRestartFiles(), DPMBase::findNextExistingDataFile(), getFullName(), openWrite(), DPMBase::readDataFile(), saveCurrentTimeStep(), DPMBase::writeEneTimeStep(), DPMBase::writeOutputFiles(), and BaseInteraction::~BaseInteraction().
getFstream()
std::fstream & File::getFstream ()
Allows to access the member variable File::fstream_.
Returns fstream (file stream) of any file for input and output tasks.
Returns
std::fstream&
 {
     return fstream_;
 }
References fstream_.
Referenced by BaseCG::BaseCG(), ClosedCSCRestart::ClosedCSCRestart(), ChuteWithPeriodicInflow::computeInternalForces(), DPMBase::constructor(), CSCRestart::CSCRestart(), DPMBase::findNextExistingDataFile(), DPMBase::readDataFile(), DPMBase::readNextDataFile(), DPMBase::readNextFStatFile(), DPMBase::readRestartFile(), CSCInit::save(), RotatingDrumBidisperseInitialise::save(), ClosedCSCWalls::saveWalls(), CSCWalls::saveWalls(), DPMBase::writeDataFile(), DPMBase::writeEneFile(), DPMBase::writeFStatFile(), DPMBase::writeRestartFile(), and BaseInteraction::~BaseInteraction().
getFullName() [1/2]
const std::string File::getFullName () const
Also allows to access the file name, however with additional information which is the file counter, e.g., "problem.data.0000".
 {
     return getFullName(getCounter() - 1);
 }
References getCounter().
Referenced by ClosedCSCStats::ClosedCSCStats(), CSCStats::CSCStats(), CGHandler::evaluateDataFiles(), CGHandler::evaluateRestartFiles(), open(), DPMBase::readDataFile(), DPMBase::readNextDataFile(), DPMBase::readNextFStatFile(), DPMBase::readRestartFile(), CGHandler::restart(), write(), and ChuteWithPeriodicInflow::writeXBallsScript().
getFullName() [2/2]
const std::string File::getFullName (unsigned counter) const
Allows to access the file name, however with additional information which is the file counter, e.g., "problem.data.0000".
In case of FileType:fileType_== multiple files or multiple files padded, multiple files are generated and are named as problem.data.0, problem.data.1 or problem.data.0000, problem.data.0001
Returns
Returns a constant of type std::string
 {
     //get the full file name
     std::stringstream lastName("");
     lastName << name_;
     if (getFileType() == FileType::MULTIPLE_FILES)
     {
         lastName << "." << counter;
     }
     else if (getFileType() == FileType::MULTIPLE_FILES_PADDED)
     {
         lastName << "." << to_string_padded(counter);
     }
     return lastName.str();
 }
References getFileType(), MULTIPLE_FILES, MULTIPLE_FILES_PADDED, name_, and to_string_padded().
getLastSavedTimeStep()
unsigned int File::getLastSavedTimeStep () const
Gets File::nextSavedTimeStep_.
Returns the time step at which the next write or read operation has to happen
Returns
unsigned int nextSaveTimeStep_
 {
     return lastSavedTimeStep_;
 }
References lastSavedTimeStep_.
Referenced by SaveCountUnitTest::SaveCountUnitTest().
getName()
const std::string & File::getName () const
Allows to access the file name, e.g., "problem.data".
Returns
Returns a constant reference of type const std::string&
 {
     return name_;
 }
References name_.
Referenced by ParameterStudy1DDemo::actionsBeforeTimeLoop(), ParameterStudy2DDemo::actionsBeforeTimeLoop(), ParameterStudy3DDemo::actionsBeforeTimeLoop(), ClosedCSCRestart::ClosedCSCRestart(), commandLineCG(), CSCRestart::CSCRestart(), DPMBase::findNextExistingDataFile(), main(), DPMBase::read(), DPMBase::readDataFile(), Mercury3DRestart::readNextArgument(), CGHandler::restart(), FlowRule::run(), AngleOfRepose::run(), setName(), and CSCRun::setupInitialConditions().
getOpenMode()
std::fstream::openmode File::getOpenMode () const
Allows the user to know the file mode i.e. gets File::openMode_.
Returns
std::fstream::openmode
 {
     return openMode_;
 }
References openMode_.
getSaveCount()
unsigned int File::getSaveCount () const
Gets File::saveCount_.
Returns
unsigned int saveCount_
 {
     return saveCount_;
 }
References saveCount_.
Referenced by RotatingDrumWet::actionsAfterTimeStep(), OneParticleCoolingSelfTest::actionsAfterTimeStep(), ThermalConductionSelfTest::actionsBeforeTimeStep(), NautaMixer::addSpeciesAndSetTimeStepAndSaveCount(), ClosedCSCRun::ClosedCSCRun(), InitialBed::continueSolve(), InitialConditions< SpeciesType >::InitialConditions(), ChuteWithPeriodicInflow::integrateBeforeForceComputation(), main(), DPMBase::readNextArgument(), BaseWall::renderWall(), ClosedCSCStats::setupInitialConditions(), CSCStats::setupInitialConditions(), and SingleParticle< SpeciesType >::setupInitialConditions().
increaseCounter()
void File::increaseCounter () inline
 {counter_++;}
References counter_.
open() [1/2]
bool File::open ()
Checks if the file stream fstream_ has any issues while opening. Alongside, it also increments the nextSavedTimeStep and the counter. the counter is useful when the fileType_ is set to Multiple or Multiple with padded.
Returns a bool to check if the file is open or closed. It also increments the nextSavedTimeStep with the saveCount
Returns
bool (True or False)
Bug:
Deepak checked by using fstream_.fail() instead of !fstrea_.is_open(), however this breaks selftests, Thomas will look at this
 {
     //close old file if multi-file output
     if (fileType_ == FileType::MULTIPLE_FILES || fileType_ == FileType::MULTIPLE_FILES_PADDED)
     {
         fstream_.close();
     }
     counter_++;
     if (!fstream_.is_open())
     {
         fstream_.open(getFullName().c_str(), openMode_);
         if (!fstream_.is_open())
         {
             return false;
         }
     }
     return true;
 }
References counter_, fileType_, fstream_, getFullName(), MULTIPLE_FILES, MULTIPLE_FILES_PADDED, and openMode_.
Referenced by DPMBase::findNextExistingDataFile(), DPMBase::initialiseSolve(), open(), openWrite(), openWriteNoAppend(), DPMBase::readDataFile(), DPMBase::readNextDataFile(), DPMBase::readNextFStatFile(), DPMBase::readRestartFile(), CSCInit::save(), RotatingDrumBidisperseInitialise::save(), ClosedCSCWalls::saveWalls(), and CSCWalls::saveWalls().
open() [2/2]
bool File::open (std::fstream::openmode openMode)
First calls setOpenMode(openMode), then calls open().
Parameters
[in] openMode
 {
     setOpenMode(openMode);
     return open();
 }
References open(), and setOpenMode().
openWrite()
bool File::openWrite (unsigned nTimeSteps)
First sets openmode to write (and append in some cases), then calls open().
Parameters
[in] openMode
 {
     setLastSavedTimeStep(nTimeSteps);
     if (getFileType() == FileType::ONE_FILE && getCounter() != 0)
     {
         setOpenMode(std::fstream::out | std::fstream::app);
     }
     else
     {
         setOpenMode(std::fstream::out);
     }
     return open();
 }
References getCounter(), getFileType(), ONE_FILE, open(), out(), setLastSavedTimeStep(), and setOpenMode().
Referenced by DPMBase::writeDataFile(), DPMBase::writeEneFile(), and DPMBase::writeFStatFile().
openWriteNoAppend()
bool File::openWriteNoAppend (unsigned nTimeSteps)
Parameters
[in] openMode
 {
     setLastSavedTimeStep(nTimeSteps);
     return open(std::fstream::out);
 }
References open(), out(), and setLastSavedTimeStep().
Referenced by DPMBase::writeRestartFile().
read()
void File::read (std::istream & is)
read function, which accepts an input stream std::istream.
Read function, which accepts an input stream object as input and assigns the member variables i.e. name_, fileType_, saveCount_, counter_ and lastSavedTimeStep_
Parameters
[in,out] is
 {
     std::string dummy;
     is >> dummy;
     if (!dummy.compare("name"))
         is >> name_ >> dummy;
     is >> fileType_;
     is >> dummy >> saveCount_;
     is >> dummy >> counter_;
     if (counter_ != 0)
     {
         is >> dummy >> lastSavedTimeStep_;
     }
     else
     {
         lastSavedTimeStep_ = NEVER;
     }
     //if (dummy != "lastSavedTimeStep") lastSavedTimeStep_=SAVE;
 }
References counter_, fileType_, lastSavedTimeStep_, name_, NEVER, saveCount_, and oomph::Global_string_for_annotation::string().
saveCurrentTimeStep()
bool File::saveCurrentTimeStep (unsigned int ntimeSteps)
determined if this time step has to be written; if so, opens the output file
Parameters
[in] ntimeSteps
Returns
True or False (a bool)
{
     return getFileType() != FileType::NO_FILE && saveCurrentTimeStepNoFileTypeCheck(ntimeSteps);
 }
References getFileType(), NO_FILE, and saveCurrentTimeStepNoFileTypeCheck().
Referenced by CGHandler::evaluate(), and DPMBase::writeOutputFiles().
saveCurrentTimeStepNoFileTypeCheck()
bool File::saveCurrentTimeStepNoFileTypeCheck (unsigned int ntimeSteps)
 {
     /* check:
      * - if this time step should be written
      * - if the file type is not NO_FILE
      * - if file can be opened
      * in that case, change lastSavedTimeStep and return true;
      */
     if ((lastSavedTimeStep_ == NEVER || ntimeSteps >= lastSavedTimeStep_ + saveCount_))
     {
         //note: do not do the following at t = 0 because this makes no sense for a logarithm
         if (logarithmicSaveCountBase_ > 1 && ntimeSteps > 0 &&
             saveCount_ < ceil((logarithmicSaveCountBase_ - 1) * lastSavedTimeStep_))
         {
             /*calculate the new saveCount base on the user input logarithmicSaveCountBase,
              *and multiply by the actual number of time steps
              */
             saveCount_ = ceil((logarithmicSaveCountBase_ - 1) * lastSavedTimeStep_);
         }
         return true;
     } else {
         return false;
     }
 }
References Eigen::bfloat16_impl::ceil(), lastSavedTimeStep_, logarithmicSaveCountBase_, NEVER, and saveCount_.
Referenced by saveCurrentTimeStep(), and DPMBase::writeOutputFiles().
setCounter()
void File::setCounter (unsigned int counter)
Allows the user to set the file counter according to his need. Sets File::counter_.
Parameters
[in] counter
 {
     counter_ = counter;
 }
References counter_.
Referenced by CGHandler::evaluateDataFiles(), DPMBase::readDataFile(), DPMBase::readRestartFile(), and DPMBase::resetFileCounter().
setFileType()
void File::setFileType (FileType fileType)
Sets the type of file needed to write into or read from. File::fileType_.
Parameters
[in] fileType
 {
     fileType_ = fileType;
 }
References fileType_.
Referenced by ChuteRestartDemo::actionsOnRestart(), BaseCluster::actionsOnRestart(), AxisymmetricWallSelfTest::AxisymmetricWallSelfTest(), BoundariesSelfTest::BoundariesSelfTest(), ClosedCSCStats::ClosedCSCStats(), commandLineCG(), ChuteBottom::constructor(), DPMBase::constructor(), CSCStats::CSCStats(), FluxAndPeriodicBoundarySelfTest::FluxAndPeriodicBoundarySelfTest(), FluxBoundarySelfTest::FluxBoundarySelfTest(), ForceLawsMPI2Test::ForceLawsMPI2Test(), CLiveStatistics< T >::getLiveStatistics(), HorizontalMixer::HorizontalMixer(), InitialConditions< SpeciesType >::InitialConditions(), LeesEdwardsDemo::LeesEdwardsDemo(), LeesEdwardsSelfTest::LeesEdwardsSelfTest(), LiquidMigrationMPI2Test::LiquidMigrationMPI2Test(), main(), ParticleParticleCollision::ParticleParticleCollision(), DPMBase::readDataFile(), DPMBase::readNextArgument(), DPMBase::readOld(), FlowRule::run(), statistics_while_running< T >::run(), AngleOfRepose::run(), DPMBase::setFileType(), Calibration::setOutput(), ChutePeriodic::setup(), RandomClusterInsertionBoundarySelfTest::setupInitialConditions(), MarbleRun::setupInitialConditions(), ShiftingConstantMassFlowMaserBoundarySelfTest::setupInitialConditions(), ShiftingMaserBoundarySelfTest::setupInitialConditions(), ChutePeriodic::setupInitialConditions(), Cstatic3D::setupInitialConditions(), GetDistanceAndNormalForIntersectionOfWalls::setupInitialConditions(), GetDistanceAndNormalForScrew::setupInitialConditions(), GetDistanceAndNormalForTriangleWall::setupInitialConditions(), Drum::setupInitialConditions(), Penetration::setupInitialConditions(), Silo::setupInitialConditions(), CubeDeletionBoundarySelfTest::setupInitialConditions(), DeletionBoundarySelfTest::setupInitialConditions(), ContactDetectionIntersectionOfWallsTest::setupInitialConditions(), GetDistanceAndNormalForTriangleWalls::setupInitialConditions(), RollingOverTriangleWalls::setupInitialConditions(), Packing::setupInitialConditions(), HertzianSinterForceUnitTest::setupInitialConditions(), MovingWalls::setupInitialConditions(), BaseCluster::setupInitialConditions(), SilbertHstop::SilbertHstop(), SilbertPeriodic::SilbertPeriodic(), statistics_while_running< T >::statistics_while_running(), TimeDependentPeriodicBoundary3DSelfTest::TimeDependentPeriodicBoundary3DSelfTest(), TimeDependentPeriodicBoundaryTest::TimeDependentPeriodicBoundaryTest(), TriangulatedScrewSelfTest::TriangulatedScrewSelfTest(), TriangulatedStepWallSelfTest::TriangulatedStepWallSelfTest(), TriangulatedWallSelfTest::TriangulatedWallSelfTest(), Tutorial11::Tutorial11(), and TwoByTwoMPIDomainMPI4Test::TwoByTwoMPIDomainMPI4Test().
setLastSavedTimeStep()
void File::setLastSavedTimeStep (unsigned int lastSavedTimeStep)
Sets File::nextSavedTimeStep_.
Allows one to set the time step at which the next write or read operation has to happen
Parameters
[in] lastSavedTimeStep
 {
     lastSavedTimeStep_ = lastSavedTimeStep;
 }
References lastSavedTimeStep_.
Referenced by BaseCG::BaseCG(), CGHandler::evaluate(), CGHandler::finish(), openWrite(), openWriteNoAppend(), DPMBase::setLastSavedTimeStep(), and DPMBase::writeOutputFiles().
setlogarithmicSaveCount()
void File::setlogarithmicSaveCount (const Mdouble logarithmicSaveCountBase)
the function to set the user input base of logarithmic saving count
File::setlogarithmicSaveCount assigns the base of the saveCount on a logarithmic time scale
Parameters
[in] logarithmicSaveCountBase
 {
     logger.assert_always(logarithmicSaveCountBase > 1, "logarithmicSaveCountBase should always be larger than 1");
     logarithmicSaveCountBase_ = logarithmicSaveCountBase;
 }
References logarithmicSaveCountBase_, and logger.
Referenced by DPMBase::setLogarithmicSaveCount().
setName()
void File::setName (const std::string & name)
Sets the file name, e.g. "Name.data".
Note the file name is usually set by MD::setName(), which sets names for all file types (data, restart, fstat, stat, ene)
Parameters
[in] name (Takes in the to be name of the File)
 {
     logger.assert_always(!getName().empty(), "Error: Name cannot be empty");
     this->name_ = name;
 }
References getName(), logger, plotDoE::name, and name_.
Referenced by commandLineCG(), Indenter::Indenter(), main(), DPMBase::read(), DPMBase::readDataFile(), DPMBase::readRestartFile(), CGHandler::restart(), AngleOfRepose::set_study(), SilbertPeriodic::set_study(), setCGHandler(), FlowRule::setName(), and DPMBase::setName().
setOpenMode()
void File::setOpenMode (std::fstream::openmode openMode)
Allows the user to Sets File::openMode_.
Parameters
[in] openmode
 {
     openMode_ = openMode;
 }
References openMode_.
Referenced by DPMBase::initialiseSolve(), open(), openWrite(), and DPMBase::setOpenMode().
setSaveCount()
void File::setSaveCount (unsigned int saveCount)
Sets File::saveCount_.
File::setSaveCount assigns the number of time steps to be skipped before the data is written to an existing file or a new file.
Parameters
[in] saveCount
 {
     saveCount_ = saveCount;
 }
References saveCount_.
Referenced by commandLineCG(), InitialConditions< SpeciesType >::InitialConditions(), main(), MultiParticlesInsertion::MultiParticlesInsertion(), DPMBase::readNextArgument(), DPMBase::readOld(), DPMBase::readParAndIniFiles(), setCGHandler(), DPMBase::setSaveCount(), DistributionToPSDSelfTest::setupInitialConditions(), InsertionBoundarySelfTest::setupInitialConditions(), MultiplePSDSelfTest::setupInitialConditions(), PolydisperseInsertionBoundarySelfTest::setupInitialConditions(), PSDManualInsertionSelfTest::setupInitialConditions(), PSDSelfTest::setupInitialConditions(), RandomClusterInsertionBoundarySelfTest::setupInitialConditions(), SingleParticle< SpeciesType >::SingleParticle(), TriangulatedScrewSelfTest::TriangulatedScrewSelfTest(), TriangulatedStepSelfTest::TriangulatedStepSelfTest(), and TriangulatedWallSelfTest::TriangulatedWallSelfTest().
write()
void File::write (std::ostream & os) const
print function, which accepts an std::stringstream as input.
BaseParticle print function, which accepts an output stream object as input and writes the info to the std::ostream
Parameters
[in,out] os
Todo:
TW: openMode_ is not saved, maybe it should not even be stored but set every time you open a file
 {
     //only write name if it differs from the default name
     if (getFullName().compare(name_))
         os << "name " << name_ << " ";
     os << "fileType " << fileType_;
     os << " saveCount " << saveCount_;
     os << " counter " << counter_;
     if (counter_ != 0)
     {
         os << " lastSavedTimeStep " << lastSavedTimeStep_;
     }
 }
References compare(), counter_, fileType_, getFullName(), lastSavedTimeStep_, name_, and saveCount_.
writeFirstAndLastTimeStep()
void File::writeFirstAndLastTimeStep ()
Sets File::saveCount_ to the highest possible value such that only the first and last time step is written.
File::setSaveCount assigns the number of time steps to be skipped before the data is written to an existing file or a new file.
Parameters
[in] saveCount
 {
     saveCount_ = NEVER;
 }
References NEVER, and saveCount_.
Referenced by ForceLawsMPI2Test::ForceLawsMPI2Test(), LiquidMigrationMPI2Test::LiquidMigrationMPI2Test(), MarbleRun::setupInitialConditions(), Drum::setupInitialConditions(), HertzSelfTest::setupInitialConditions(), MindlinSelfTest::setupInitialConditions(), Penetration::setupInitialConditions(), Silo::setupInitialConditions(), UnionOfWalls::setupInitialConditions(), and TwoByTwoMPIDomainMPI4Test::TwoByTwoMPIDomainMPI4Test().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const File & o) friend
Operator overloading used to write data obtained from an object of class File into an output stream. It also returns a reference to the output stream.
Parameters
[in,out] os
[in] o
Returns
std::ostream& os
 {
     o.write(os);
     return os;
 }
operator>>
std::istream& operator>> (std::istream & is, File & o) friend
Operator overloading used to read data from the input stream into member variables of an object of class File. It also returns a reference of type std::istream&.
Parameters
[in,out] is
[in] o
Returns
std::istream&
 {
     o.read(is);
     return (is);
 }
Member Data Documentation
counter_
unsigned int File::counter_ private
counts the number of already opened files, i.e. counter=1 means .0000 exists
Referenced by decreaseCounter(), File(), getCounter(), increaseCounter(), open(), read(), setCounter(), and write().
fileType_
FileType File::fileType_ private
fileType_ indicates the type of the files. Whether it is No file, one file or multiple file as described in the description of the class.
Referenced by File(), getFileType(), open(), read(), setFileType(), and write().
fstream_
std::fstream File::fstream_ private
Stream object used to read/write data files.
Referenced by close(), getFstream(), and open().
lastSavedTimeStep_
unsigned int File::lastSavedTimeStep_ private
the time step at which the next write or read operation has to happen.
Referenced by File(), getLastSavedTimeStep(), read(), saveCurrentTimeStepNoFileTypeCheck(), setLastSavedTimeStep(), and write().
logarithmicSaveCountBase_
Mdouble File::logarithmicSaveCountBase_ private
the switch allow user to set saveCount in logarithmic timescale with equal distance , the number is the base of log scale from user input
Referenced by File(), saveCurrentTimeStepNoFileTypeCheck(), and setlogarithmicSaveCount().
name_
std::string File::name_ private
name of the file.
Referenced by File(), getFullName(), getName(), read(), setName(), and write().
openMode_
std::fstream::openmode File::openMode_ private
A variable to indicate how the file should be opened i.e. in, out, ... see http://en.cppreference.com (std::fstream::out by default)
Referenced by File(), getOpenMode(), open(), and setOpenMode().
saveCount_
unsigned int File::saveCount_ private
Allows one to define the number of time steps to be skipped to make a snap shot. E.g. TMax = 100, saveCount_ = 10, timeStep = 1; It stores data at t={0,10,20,30,40...100}. And if TMax =101, it stores data at t={0,10,20,30,...100,101}.
Referenced by File(), getSaveCount(), read(), saveCurrentTimeStepNoFileTypeCheck(), setSaveCount(), write(), and writeFirstAndLastTimeStep().
The documentation for this class was generated from the following files:
File.h
File.cc