MercuryDPM: Eigen::internal::DenseStorage_impl< T, Size, Dynamic, Dynamic, Options > Class Template Reference
Eigen::internal::DenseStorage_impl< T, Size, Dynamic, Dynamic, Options > Class Template Reference
#include <DenseStorage.h>
Public Member Functions
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE DenseStorage_impl ()=default
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE DenseStorage_impl (const DenseStorage_impl &other)
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE DenseStorage_impl (Index size, Index rows, Index cols)
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE DenseStorage_impl & operator= (const DenseStorage_impl &other)
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE void swap (DenseStorage_impl &other)
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE void conservativeResize (Index, Index rows, Index cols)
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE void resize (Index, Index rows, Index cols)
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE Index rows () const
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE Index cols () const
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE Index size () const
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE T * data ()
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE const T * data () const
Private Attributes
plain_array< T, Size, Options > m_data
Index m_rows = 0
Index m_cols = 0
Constructor & Destructor Documentation
DenseStorage_impl() [1/3]
template<typename T , int Size, int Options> EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE Eigen::internal::DenseStorage_impl< T, Size, Dynamic, Dynamic, Options >::DenseStorage_impl () constexpr default
DenseStorage_impl() [2/3]
template<typename T , int Size, int Options> EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE Eigen::internal::DenseStorage_impl< T, Size, Dynamic, Dynamic, Options >::DenseStorage_impl (const DenseStorage_impl< T, Size, Dynamic, Dynamic, Options > & other) inline constexpr
       : m_rows(other.m_rows), m_cols(other.m_cols) {
     EIGEN_INTERNAL_DENSE_STORAGE_CTOR_PLUGIN(Index size = other.size())
     smart_copy(other.m_data.array, other.m_data.array + other.size(), m_data.array);
   }
References EIGEN_INTERNAL_DENSE_STORAGE_CTOR_PLUGIN, Eigen::internal::DenseStorage_impl< T, Size, Rows, Cols, Options >::m_data, size, Eigen::internal::DenseStorage_impl< T, Size, Rows, Cols, Options >::size(), and Eigen::internal::smart_copy().
DenseStorage_impl() [3/3]
template<typename T , int Size, int Options> EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE Eigen::internal::DenseStorage_impl< T, Size, Dynamic, Dynamic, Options >::DenseStorage_impl (Index size, Index rows, Index cols) inline constexpr
       : m_rows(rows), m_cols(cols) {
     EIGEN_INTERNAL_DENSE_STORAGE_CTOR_PLUGIN({})
     EIGEN_UNUSED_VARIABLE(size)
   }
References EIGEN_INTERNAL_DENSE_STORAGE_CTOR_PLUGIN, EIGEN_UNUSED_VARIABLE, and size.
Member Function Documentation
cols()
template<typename T , int Size, int Options> EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE Index Eigen::internal::DenseStorage_impl< T, Size, Dynamic, Dynamic, Options >::cols () const inline constexpr
 { return m_cols; }
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
conservativeResize()
template<typename T , int Size, int Options> EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE void Eigen::internal::DenseStorage_impl< T, Size, Dynamic, Dynamic, Options >::conservativeResize (Index , Index rows, Index cols) inline constexpr
{
     m_rows = rows;
     m_cols = cols;
   }
References cols, and rows.
data() [1/2]
template<typename T , int Size, int Options> EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE T* Eigen::internal::DenseStorage_impl< T, Size, Dynamic, Dynamic, Options >::data () inline constexpr
 { return m_data.array; }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
data() [2/2]
template<typename T , int Size, int Options> EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE const T* Eigen::internal::DenseStorage_impl< T, Size, Dynamic, Dynamic, Options >::data () const inline constexpr
 { return m_data.array; }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
operator=()
template<typename T , int Size, int Options> EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE DenseStorage_impl& Eigen::internal::DenseStorage_impl< T, Size, Dynamic, Dynamic, Options >::operator= (const DenseStorage_impl< T, Size, Dynamic, Dynamic, Options > & other) inline constexpr
{
     smart_copy(other.m_data.array, other.m_data.array + other.size(), m_data.array);
     m_rows = other.m_rows;
     m_cols = other.m_cols;
     return *this;
   }
References Eigen::internal::DenseStorage_impl< T, Size, Rows, Cols, Options >::m_data, Eigen::internal::DenseStorage_impl< T, Size, Rows, Cols, Options >::size(), and Eigen::internal::smart_copy().
resize()
template<typename T , int Size, int Options> EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE void Eigen::internal::DenseStorage_impl< T, Size, Dynamic, Dynamic, Options >::resize (Index , Index rows, Index cols) inline constexpr
{
     m_rows = rows;
     m_cols = cols;
   }
References cols, and rows.
rows()
template<typename T , int Size, int Options> EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE Index Eigen::internal::DenseStorage_impl< T, Size, Dynamic, Dynamic, Options >::rows () const inline constexpr
 { return m_rows; }
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
size()
template<typename T , int Size, int Options> EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE Index Eigen::internal::DenseStorage_impl< T, Size, Dynamic, Dynamic, Options >::size () const inline constexpr
 { return m_rows * m_cols; }
swap()
template<typename T , int Size, int Options> EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE void Eigen::internal::DenseStorage_impl< T, Size, Dynamic, Dynamic, Options >::swap (DenseStorage_impl< T, Size, Dynamic, Dynamic, Options > & other) inline constexpr
{
     swap_plain_array(m_data, other.m_data, size(), other.size());
     numext::swap(m_rows, other.m_rows);
     numext::swap(m_cols, other.m_cols);
   }
References Eigen::internal::DenseStorage_impl< T, Size, Rows, Cols, Options >::m_data, size, Eigen::internal::DenseStorage_impl< T, Size, Rows, Cols, Options >::size(), Eigen::numext::swap(), and Eigen::internal::swap_plain_array().
Member Data Documentation
m_cols
template<typename T , int Size, int Options> Index Eigen::internal::DenseStorage_impl< T, Size, Dynamic, Dynamic, Options >::m_cols = 0 private
m_data
template<typename T , int Size, int Options> plain_array<T, Size, Options> Eigen::internal::DenseStorage_impl< T, Size, Dynamic, Dynamic, Options >::m_data private
m_rows
template<typename T , int Size, int Options> Index Eigen::internal::DenseStorage_impl< T, Size, Dynamic, Dynamic, Options >::m_rows = 0 private
The documentation for this class was generated from the following file:
DenseStorage.h