MercuryDPM: FullRestartSelfTest.cpp File Reference
FullRestartSelfTest.cpp File Reference
#include "DPMBase.h"
#include "Walls/Coil.h"
#include "Walls/CylindricalWall.h"
#include "Walls/AxisymmetricIntersectionOfWalls.h"
#include "Walls/IntersectionOfWalls.h"
#include "Walls/InfiniteWall.h"
#include "Walls/InfiniteWallWithHole.h"
#include "Walls/Screw.h"
#include "Boundaries/AngledPeriodicBoundary.h"
#include "Boundaries/ChuteInsertionBoundary.h"
#include "Boundaries/CubeInsertionBoundary.h"
#include "Boundaries/HopperInsertionBoundary.h"
#include "Boundaries/PeriodicBoundary.h"
#include "Boundaries/CircularPeriodicBoundary.h"
#include "Boundaries/DeletionBoundary.h"
#include "Boundaries/LeesEdwardsBoundary.h"
#include "Species/LinearViscoelasticSpecies.h"
#include "Species/LinearPlasticViscoelasticSpecies.h"
Classes
class FullRestartTest
Functions
int main ()
Function Documentation
main()
int main ()
 {
     FullRestartTest normal;
     normal.setName("FullRestartSelfTest");
     normal.setupInitialConditions();
     normal.writeRestartFile();
     normal.restartFile.setFileType(FileType::MULTIPLE_FILES);
     normal.setName("FullRestartWithCounterSelfTest");
     logger(INFO, "%", normal.restartFile.getFullName());
     normal.writeRestartFile();
     FullRestartTest restart;
     restart.readRestartFile("FullRestartSelfTest.restart");
     restart.setName("FullRestartSelfTestRestarted");
     restart.writeRestartFile();
     restart.write(std::cout);
     restart.readRestartFile("FullRestartWithCounterSelfTest.restart.1");
     restart.setName("FullRestartWithCounterSelfTestRestarted");
     restart.writeRestartFile();
 }
References INFO, logger, MULTIPLE_FILES, WallFunction::normal(), DPMBase::readRestartFile(), DPMBase::setName(), MercuryBase::write(), and DPMBase::writeRestartFile().