MercuryDPM: Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized > Class Template Reference
Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized > Class Template Reference
#include <Swap.h>
Public Types
typedef Base::Scalar Scalar
typedef Base::DstXprType DstXprType
typedef swap_assign_op< Scalar > Functor
Public Types inherited from Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar >, BuiltIn >
typedef DstEvaluatorTypeT DstEvaluatorType
typedef SrcEvaluatorTypeT SrcEvaluatorType
typedef DstEvaluatorType::Scalar Scalar
typedef copy_using_evaluator_traits< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar > > AssignmentTraits
typedef AssignmentTraits::PacketType PacketType
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE generic_dense_assignment_kernel (DstEvaluatorTypeT &dst, const SrcEvaluatorTypeT &src, const Functor &func, DstXprType &dstExpr)
template<int StoreMode, int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE void assignPacket (Index row, Index col)
template<int StoreMode, int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE void assignPacket (Index index)
template<int StoreMode, int LoadMode, typename PacketType >
EIGEN_STRONG_INLINE void assignPacketByOuterInner (Index outer, Index inner)
Public Member Functions inherited from Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar >, BuiltIn >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE generic_dense_assignment_kernel (DstEvaluatorType &dst, const SrcEvaluatorType &src, const swap_assign_op< DstEvaluatorTypeT::Scalar > &func, DstXprType &dstExpr)
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index size () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index innerSize () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index outerSize () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index outerStride () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC DstEvaluatorType & dstEvaluator () EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC const SrcEvaluatorType & srcEvaluator () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void assignCoeff (Index row, Index col)
Assign src(row,col) to dst(row,col) through the assignment functor.
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void assignCoeff (Index index)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void assignCoeffByOuterInner (Index outer, Index inner)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void assignPacket (Index row, Index col)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void assignPacket (Index index)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void assignPacketByOuterInner (Index outer, Index inner)
EIGEN_DEVICE_FUNC const Scalar * dstDataPtr () const
Protected Types
typedef generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, BuiltIn > Base
Protected Types inherited from Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar >, BuiltIn >
typedef DstEvaluatorTypeT::XprType DstXprType
typedef SrcEvaluatorTypeT::XprType SrcXprType
Protected Attributes
DstEvaluatorType & m_dst
const Functor & m_functor
const SrcEvaluatorType & m_src
Protected Attributes inherited from Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar >, BuiltIn >
DstEvaluatorType & m_dst
const SrcEvaluatorType & m_src
const swap_assign_op< DstEvaluatorTypeT::Scalar > & m_functor
DstXprType & m_dstExpr
Additional Inherited Members
Static Public Member Functions inherited from Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< DstEvaluatorTypeT::Scalar >, BuiltIn >
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index rowIndexByOuterInner (Index outer, Index inner)
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index colIndexByOuterInner (Index outer, Index inner)
Member Typedef Documentation
Base
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT > typedef generic_dense_assignment_kernel<DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op<typename DstEvaluatorTypeT::Scalar>, BuiltIn> Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >::Base protected
DstXprType
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT > typedef Base::DstXprType Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >::DstXprType
Functor
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT > typedef swap_assign_op<Scalar> Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >::Functor
Scalar
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT > typedef Base::Scalar Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >::Scalar
Constructor & Destructor Documentation
generic_dense_assignment_kernel()
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >::generic_dense_assignment_kernel (DstEvaluatorTypeT & dst, const SrcEvaluatorTypeT & src, const Functor & func, DstXprType & dstExpr) inline
       : Base(dst, src, func, dstExpr) {}
Member Function Documentation
assignPacket() [1/2]
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT > template<int StoreMode, int LoadMode, typename PacketType > EIGEN_STRONG_INLINE void Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >::assignPacket (Index index) inline
{
     PacketType tmp = m_src.template packet<LoadMode, PacketType>(index);
     const_cast<SrcEvaluatorTypeT &>(m_src).template writePacket<LoadMode>(
         index, m_dst.template packet<StoreMode, PacketType>(index));
     m_dst.template writePacket<StoreMode>(index, tmp);
   }
References Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::m_dst, Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::m_src, and tmp.
assignPacket() [2/2]
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT > template<int StoreMode, int LoadMode, typename PacketType > EIGEN_STRONG_INLINE void Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >::assignPacket (Index row, Index col) inline
{
     PacketType tmp = m_src.template packet<LoadMode, PacketType>(row, col);
     const_cast<SrcEvaluatorTypeT &>(m_src).template writePacket<LoadMode>(
         row, col, m_dst.template packet<StoreMode, PacketType>(row, col));
     m_dst.template writePacket<StoreMode>(row, col, tmp);
   }
References col(), Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::m_dst, Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::m_src, row(), and tmp.
assignPacketByOuterInner()
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT > template<int StoreMode, int LoadMode, typename PacketType > EIGEN_STRONG_INLINE void Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >::assignPacketByOuterInner (Index outer, Index inner) inline
{
     Index row = Base::rowIndexByOuterInner(outer, inner);
     Index col = Base::colIndexByOuterInner(outer, inner);
     assignPacket<StoreMode, LoadMode, PacketType>(row, col);
   }
References col(), and row().
Member Data Documentation
m_dst
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT > DstEvaluatorType& Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::m_dst protected
m_functor
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT > const Functor& Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::m_functor protected
m_src
template<typename DstEvaluatorTypeT , typename SrcEvaluatorTypeT > const SrcEvaluatorType& Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::m_src protected
The documentation for this class was generated from the following file:
Swap.h