MercuryDPM: InclinedPlaneUnitTest.cpp File Reference
InclinedPlaneUnitTest.cpp File Reference
#include "DPMBase.h"
#include "Particles/SphericalParticle.h"
#include "Walls/InfiniteWall.h"
#include <iostream>
#include <Species/LinearViscoelasticSlidingFrictionSpecies.h>
Classes
class InclinedPlane
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
Start off my solving the default problem
 {
     logger(INFO, "Single particle rolling on a bottom plate");
     InclinedPlane problem;
     auto species = problem.speciesHandler.copyAndAddObject(LinearViscoelasticSlidingFrictionSpecies());
     problem.setName("InclinedPlane");
     problem.setFileType(FileType::NO_FILE); //comment if you want file output
     problem.setSaveCount(50000);
     problem.setSystemDimensions(2);
     problem.setParticleDimensions(3);
     Mdouble theta = 15.0*constants::pi/180.0;
     problem.setGravity(9.8*Vec3D(std::sin(theta),-std::cos(theta),0.0));
     species->setDensity(2000);
     species->setStiffness(10000);
     species->setDissipation(0);
     species->setSlidingStiffness(10000);
     species->setSlidingDissipation(0);
     species->setSlidingFrictionCoefficient(0.5);
     //species->setRollingStiffness(10000);
     //species->setRollingDissipation(0);
     //species->setRollingFrictionCoefficient(0.5);
     //tc=7e-5
     problem.setTimeStep(0.02*species->getCollisionTime(species->getMassFromRadius(0.005)));
     problem.setTimeMax(1.0);
     problem.setXMax(0.1);
     problem.setYMax(0.1);
     problem.setZMax(0.1);
     problem.solve(argc, argv);
     //problem.write(std::cout, true);
     const Vec3D v = problem.particleHandler.getObject(0)->getVelocity();
     logger(INFO,"v_x(t_max)=% should be ~1.81",v.X);
     logger(INFO,"v_y(t_max)=% should be ~0",v.Y);
     helpers::check(v.X,1.81167,1e-4,"v_x");
     helpers::check(v.Y,0.00234107,1e-4,"v_y");
 }
References helpers::check(), cos(), e(), INFO, logger, NO_FILE, constants::pi, problem, sin(), BiharmonicTestFunctions2::theta, and v.