MercuryDPM: Eigen::internal::serialize_impl< N, T1, Ts... > Struct Template Reference
Eigen::internal::serialize_impl< N, T1, Ts... > Struct Template Reference
#include <Serializer.h>
Public Types
using Serializer = Eigen::Serializer< typename std::decay< T1 >::type >
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE size_t serialize_size (const T1 &value, const Ts &... args)
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE uint8_t * serialize (uint8_t *dest, uint8_t *end, const T1 &value, const Ts &... args)
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const uint8_t * deserialize (const uint8_t *src, const uint8_t *end, T1 &value, Ts &... args)
Member Typedef Documentation
Serializer
template<size_t N, typename T1 , typename... Ts> using Eigen::internal::serialize_impl< N, T1, Ts... >::Serializer = Eigen::Serializer<typename std::decay<T1>::type>
Member Function Documentation
deserialize()
template<size_t N, typename T1 , typename... Ts> static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const uint8_t* Eigen::internal::serialize_impl< N, T1, Ts... >::deserialize (const uint8_t * src, const uint8_t * end, T1 & value, Ts &... args) inline static
{
     Serializer serializer;
     src = serializer.deserialize(src, end, value);
     return serialize_impl<N - 1, Ts...>::deserialize(src, end, args...);
   }
References compute_granudrum_aor::args, Eigen::deserialize(), Eigen::placeholders::end, and Eigen::value.
serialize()
template<size_t N, typename T1 , typename... Ts> static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE uint8_t* Eigen::internal::serialize_impl< N, T1, Ts... >::serialize (uint8_t * dest, uint8_t * end, const T1 & value, const Ts &... args) inline static
{
     Serializer serializer;
     dest = serializer.serialize(dest, end, value);
     return serialize_impl<N - 1, Ts...>::serialize(dest, end, args...);
   }
References compute_granudrum_aor::args, Eigen::placeholders::end, serialize(), and Eigen::value.
serialize_size()
template<size_t N, typename T1 , typename... Ts> static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE size_t Eigen::internal::serialize_impl< N, T1, Ts... >::serialize_size (const T1 & value, const Ts &... args) inline static
{
     Serializer serializer;
     size_t size = serializer.size(value);
     return size + serialize_impl<N - 1, Ts...>::serialize_size(args...);
   }
References compute_granudrum_aor::args, Eigen::serialize_size(), size, and Eigen::value.
The documentation for this struct was generated from the following file:
Serializer.h