MercuryDPM: Eigen::internal::generic_k1< T, float > Struct Template Reference
Eigen::internal::generic_k1< T, float > Struct Template Reference
#include <BesselFunctionsImpl.h>
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T run (const T &x)
Member Function Documentation
run()
template<typename T > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T Eigen::internal::generic_k1< T, float >::run (const T & x) inline static
{
     /* k1f.c
      *  Modified Bessel function, third kind, order one
      *
      *
      *
      * SYNOPSIS:
      *
      * float x, y, k1f();
      *
      * y = k1f( x );
      *
      *
      *
      * DESCRIPTION:
      *
      * Computes the modified Bessel function of the third kind
      * of order one of the argument.
      *
      * The range is partitioned into the two intervals [0,2] and
      * (2, infinity).  Chebyshev polynomial expansions are employed
      * in each interval.
      *
      *
      *
      * ACCURACY:
      *
      *                      Relative error:
      * arithmetic   domain     # trials      peak         rms
      *    IEEE      0, 30       30000       4.6e-7      7.6e-8
      *
      * ERROR MESSAGES:
      *
      *   message         condition      value returned
      * k1 domain          x <= 0          MAXNUM
      *
      */
     const float A[] = {-2.21338763073472585583E-8f, -2.43340614156596823496E-6f, -1.73028895751305206302E-4f,
                        -6.97572385963986435018E-3f, -1.22611180822657148235E-1f, -3.53155960776544875667E-1f,
                        1.52530022733894777053E0f};
     const float B[] = {2.01504975519703286596E-9f,  -1.03457624656780970260E-8f, 5.74108412545004946722E-8f,
                        -3.50196060308781257119E-7f, 2.40648494783721712015E-6f,  -1.93619797416608296024E-5f,
                        1.95215518471351631108E-4f,  -2.85781685962277938680E-3f, 1.03923736576817238437E-1f,
                        2.72062619048444266945E0f};
     const T MAXNUM = pset1<T>(NumTraits<float>::infinity());
     const T two = pset1<T>(2.0);
     T x_le_two = pdiv(internal::pchebevl<T, 7>::run(pmadd(x, x, pset1<T>(-2.0)), A), x);
     x_le_two = pmadd(generic_i1<T, float>::run(x), plog(pmul(pset1<T>(0.5), x)), x_le_two);
     x_le_two = pselect(pcmp_le(x, pset1<T>(0.0)), MAXNUM, x_le_two);
     T x_gt_two =
         pmul(pexp(pnegate(x)), pmul(internal::pchebevl<T, 10>::run(psub(pdiv(pset1<T>(8.0), x), two), B), prsqrt(x)));
     return pselect(pcmp_le(x, two), x_le_two, x_gt_two);
   }
References Eigen::internal::pcmp_le(), Eigen::internal::pdiv(), Eigen::internal::pexp(), Eigen::internal::plog(), Eigen::internal::pmadd(), Eigen::internal::pmul(), Eigen::internal::pnegate(), Eigen::internal::prsqrt(), Eigen::internal::pselect(), Eigen::internal::psub(), and plotDoE::x.
The documentation for this struct was generated from the following file:
BesselFunctionsImpl.h