MercuryDPM: ScaleCoupling< M, O >::CoupledParticle Struct Reference
ScaleCoupling< M, O >::CoupledParticle Struct Reference
For all particles, stores coupling properties: coupling force, pointer to coupled element and location in coupled element.
Public Member Functions
void removeCoupledElement (BaseParticle *particle)
Removes particle from coupledParticle.coupledElement.particles and sets coupledParticle.coupledElement vector to null.
void setCoupledElement (CoupledElement *coupledElementNew, BaseParticle *particle)
Remove particle from coupledParticle.coupledElement.particles and set coupledParticle.coupledElement vector to null.
Public Attributes
Vec3D couplingForce
Coupling force.
CoupledElement * coupledElement_pt = nullptr
Element in which this particle resides (null if particle is not coupled)
Vector< double > s
Location of particle in coupled element, returned by locate zeta.
Detailed Description
template<class M, class O>
struct ScaleCoupling< M, O >::CoupledParticle
For all particles, stores coupling properties: coupling force, pointer to coupled element and location in coupled element.
Member Function Documentation
removeCoupledElement()
template<class M , class O > void ScaleCoupling< M, O >::CoupledParticle::removeCoupledElement (BaseParticle * particle) inline
Removes particle from coupledParticle.coupledElement.particles and sets coupledParticle.coupledElement vector to null.
{
             if (coupledElement_pt != nullptr) {
                 remove(coupledElement_pt->coupledParticles.begin(), coupledElement_pt->coupledParticles.end(), particle);
                 coupledElement_pt = nullptr;
                 logger(VERBOSE, "Removed particle % from element %", particle->getIndex(), coupledElement_pt);
             }
         }
References ScaleCoupling< M, O >::CoupledElement::coupledParticles, BaseObject::getIndex(), logger, and VERBOSE.
Referenced by ScaleCoupling< M, O >::updateCoupledElements().
setCoupledElement()
template<class M , class O > void ScaleCoupling< M, O >::CoupledParticle::setCoupledElement (CoupledElement * coupledElementNew, BaseParticle * particle) inline
Remove particle from coupledParticle.coupledElement.particles and set coupledParticle.coupledElement vector to null.
{
             if (coupledElement_pt != coupledElementNew) {
                 if (coupledElement_pt != nullptr) {
                     auto newEnd = remove(coupledElement_pt->coupledParticles.begin(), coupledElement_pt->coupledParticles.end(), particle);
                     coupledElement_pt->coupledParticles.erase(newEnd, coupledElement_pt->coupledParticles.end());
                     logger(VERBOSE, "Moved particle % from element % to %", particle->getIndex(), coupledElement_pt, coupledElementNew);
                 } else {
                     logger(VERBOSE,"Added particle % to element %", particle->getIndex(), coupledElementNew);
                 }
                 // add coupledElement to particle
                 coupledElement_pt = coupledElementNew;
                 // add particle to coupledElement
                 coupledElement_pt->coupledParticles.push_back(particle);
             }
         }
References ScaleCoupling< M, O >::CoupledElement::coupledParticles, BaseObject::getIndex(), logger, and VERBOSE.
Referenced by ScaleCoupling< M, O >::updateCoupledElements().
Member Data Documentation
coupledElement_pt
template<class M , class O > CoupledElement* ScaleCoupling< M, O >::CoupledParticle::coupledElement_pt = nullptr
Element in which this particle resides (null if particle is not coupled)
Referenced by ScaleCoupling< M, O >::updateCoupledElements().
couplingForce
template<class M , class O > Vec3D ScaleCoupling< M, O >::CoupledParticle::couplingForce
Coupling force.
Referenced by ScaleCoupling< M, O >::computeCouplingForce(), and ScaleCoupling< M, O >::computeExternalForces().
s
template<class M , class O > Vector<double> ScaleCoupling< M, O >::CoupledParticle::s
Location of particle in coupled element, returned by locate zeta.
Referenced by ScaleCoupling< M, O >::updateCoupledElements().
The documentation for this struct was generated from the following file:
ScaleCoupling.h