MercuryDPM: WarpedLine Class Reference
WarpedLine Class Reference
Warped line in 2D space.
Public Member Functions
WarpedLine (const double &ampl, const double &x_min, const double &x_max)
Constructor: Specify amplitude of deflection from straight horizontal line.
WarpedLine (const WarpedLine &dummy)
Broken copy constructor.
void operator= (const WarpedLine &)
Broken assignment operator.
~WarpedLine ()
Empty Destructor.
void position (const Vector< double > &zeta, Vector< double > &r) const
Position vector at Lagrangian coordinate zeta.
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
double radius () const
Return radius.
double y_c () const
Return y coordinate of centre.
double & ampl ()
Access to amplitude.
unsigned ngeom_data () const
void set_reversed ()
Local coordinates are reversed.
void set_non_reversed ()
Local coordinates are not reversed.
double & lift_off_amplitude ()
Lift off amplitude.
double & lift_off_alpha ()
Exponential factor for lift off (controls sharpness)
WarpedLine (const double &ampl, const double &x_min, const double &x_max)
Constructor: Specify amplitude of deflection from straight horizontal line.
WarpedLine (const WarpedLine &dummy)
Broken copy constructor.
~WarpedLine ()
Empty Destructor.
void position (const Vector< double > &zeta, Vector< double > &r) const
Position vector at Lagrangian coordinate zeta.
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
double radius () const
Return radius.
double y_c () const
Return y coordinate of centre.
double & ampl ()
Access to amplitude.
unsigned ngeom_data () const
void set_reversed ()
Local coordinates are reversed.
void set_non_reversed ()
Local coordinates are not reversed.
double & lift_off_amplitude ()
Lift off amplitude.
double & lift_off_alpha ()
Exponential factor for lift off (controls sharpness)
WarpedLine (const double &ampl)
Constructor: Specify amplitude of deflection from straight horizontal line.
WarpedLine (const WarpedLine &dummy)
Broken copy constructor.
void operator= (const WarpedLine &)
Broken assignment operator.
~WarpedLine ()
Empty Destructor.
void position (const Vector< double > &zeta, Vector< double > &r) const
Position vector at Lagrangian coordinate zeta.
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
double & ampl ()
Access to amplitude.
unsigned ngeom_data () const
WarpedLine (const double &ampl)
Constructor: Specify amplitude of deflection from straight horizontal line.
WarpedLine (const WarpedLine &dummy)
Broken copy constructor.
void operator= (const WarpedLine &)
Broken assignment operator.
~WarpedLine ()
Empty Destructor.
void position (const Vector< double > &zeta, Vector< double > &r) const
Position vector at Lagrangian coordinate zeta.
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
double & ampl ()
Access to amplitude.
unsigned ngeom_data () const
WarpedLine (const double &ampl)
Constructor: Specify amplitude of deflection from straight horizontal line.
WarpedLine (const WarpedLine &dummy)
Broken copy constructor.
void operator= (const WarpedLine &)
Broken assignment operator.
~WarpedLine ()
Empty Destructor.
void position (const Vector< double > &zeta, Vector< double > &r) const
Position vector at Lagrangian coordinate zeta.
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
double & ampl ()
Access to amplitude.
unsigned ngeom_data () const
WarpedLine (const double &ampl)
Constructor: Specify amplitude of deflection from straight horizontal line.
WarpedLine (const WarpedLine &dummy)
Broken copy constructor.
void operator= (const WarpedLine &)
Broken assignment operator.
~WarpedLine ()
Empty Destructor.
void position (const Vector< double > &zeta, Vector< double > &r) const
Position vector at Lagrangian coordinate zeta.
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
double & ampl ()
Access to amplitude.
WarpedLine (const double &ampl)
Constructor: Specify amplitude of deflection from straight horizontal line.
WarpedLine (const WarpedLine &dummy)
Broken copy constructor.
void operator= (const WarpedLine &)
Broken assignment operator.
~WarpedLine ()
Empty Destructor.
void position (const Vector< double > &zeta, Vector< double > &r) const
Position vector at Lagrangian coordinate zeta.
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
double & ampl ()
Access to amplitude.
unsigned ngeom_data () const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual Data * geom_data_pt (const unsigned &j)
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition_dt (const Vector< double > &zeta, const unsigned &j, Vector< double > &drdt)
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
virtual void locate_zeta (const Vector< double > &zeta, GeomObject *&sub_geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
Private Attributes
double Ampl
Amplitude of perturbation.
double X_min
Min zeta coordinate.
double X_max
Max zeta coordinate.
bool Reversed
Reverse?
double Lift_off_amplitude
Lift off amplitude.
double Lift_off_alpha
Exponential factor for lift off (controls sharpness)
Additional Inherited Members
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Detailed Description
Warped line in 2D space.
Constructor & Destructor Documentation
WarpedLine() [1/14]
WarpedLine::WarpedLine (const double & ampl, const double & x_min, const double & x_max) inline
Constructor: Specify amplitude of deflection from straight horizontal line.
   : GeomObject(1,2)
   {
    Ampl=ampl;
    X_min=x_min;
    X_max=x_max;
    Reversed=false;
    Lift_off_amplitude=0.0;
    Lift_off_alpha=100.0;
   }
References ampl(), Ampl, Lift_off_alpha, Lift_off_amplitude, Reversed, X_max, and X_min.
WarpedLine() [2/14]
WarpedLine::WarpedLine (const WarpedLine & dummy) inline
Broken copy constructor.
   {
    BrokenCopy::broken_copy("WarpedLine");
   }
References oomph::BrokenCopy::broken_copy().
~WarpedLine() [1/7]
WarpedLine::~WarpedLine () inline
Empty Destructor.
 {}
WarpedLine() [3/14]
WarpedLine::WarpedLine (const double & ampl, const double & x_min, const double & x_max) inline
Constructor: Specify amplitude of deflection from straight horizontal line.
   : GeomObject(1,2)
   {
    Ampl=ampl;
    X_min=x_min;
    X_max=x_max;
    Reversed=false;
    Lift_off_amplitude=0.0;
    Lift_off_alpha=10000.0;
   }
References RayParam::X_max, and RayParam::X_min.
WarpedLine() [4/14]
WarpedLine::WarpedLine (const WarpedLine & dummy) inline
Broken copy constructor.
   {
    BrokenCopy::broken_copy("WarpedLine");
   }
References oomph::BrokenCopy::broken_copy().
~WarpedLine() [2/7]
WarpedLine::~WarpedLine () inline
Empty Destructor.
 {}
WarpedLine() [5/14]
WarpedLine::WarpedLine (const double & ampl) inline
Constructor: Specify amplitude of deflection from straight horizontal line.
                                 : GeomObject(1,2)
   {
    Ampl=ampl;
   }
WarpedLine() [6/14]
WarpedLine::WarpedLine (const WarpedLine & dummy) inline
Broken copy constructor.
   {
    BrokenCopy::broken_copy("WarpedLine");
   }
References oomph::BrokenCopy::broken_copy().
~WarpedLine() [3/7]
WarpedLine::~WarpedLine () inline
Empty Destructor.
 {}
WarpedLine() [7/14]
WarpedLine::WarpedLine (const double & ampl) inline
Constructor: Specify amplitude of deflection from straight horizontal line.
                                 : GeomObject(1,2)
   {
    Ampl=ampl;
   }
WarpedLine() [8/14]
WarpedLine::WarpedLine (const WarpedLine & dummy) inline
Broken copy constructor.
   {
    BrokenCopy::broken_copy("WarpedLine");
   }
References oomph::BrokenCopy::broken_copy().
~WarpedLine() [4/7]
WarpedLine::~WarpedLine () inline
Empty Destructor.
 {}
WarpedLine() [9/14]
WarpedLine::WarpedLine (const double & ampl) inline
Constructor: Specify amplitude of deflection from straight horizontal line.
                                 : GeomObject(1,2)
   {
    Ampl=ampl;
   }
WarpedLine() [10/14]
WarpedLine::WarpedLine (const WarpedLine & dummy) inline
Broken copy constructor.
   {
    BrokenCopy::broken_copy("WarpedLine");
   }
References oomph::BrokenCopy::broken_copy().
~WarpedLine() [5/7]
WarpedLine::~WarpedLine () inline
Empty Destructor.
 {}
WarpedLine() [11/14]
WarpedLine::WarpedLine (const double & ampl) inline
Constructor: Specify amplitude of deflection from straight horizontal line.
                                 : GeomObject(1,2)
   {
    Ampl=ampl;
   }
WarpedLine() [12/14]
WarpedLine::WarpedLine (const WarpedLine & dummy) inline
Broken copy constructor.
   {
    BrokenCopy::broken_copy("WarpedLine");
   }
References oomph::BrokenCopy::broken_copy().
~WarpedLine() [6/7]
WarpedLine::~WarpedLine () inline
Empty Destructor.
 {}
WarpedLine() [13/14]
WarpedLine::WarpedLine (const double & ampl) inline
Constructor: Specify amplitude of deflection from straight horizontal line.
                                 : GeomObject(1,2)
   {
    Ampl=ampl;
   }
WarpedLine() [14/14]
WarpedLine::WarpedLine (const WarpedLine & dummy) inline
Broken copy constructor.
   {
    BrokenCopy::broken_copy("WarpedLine");
   }
References oomph::BrokenCopy::broken_copy().
~WarpedLine() [7/7]
WarpedLine::~WarpedLine () inline
Empty Destructor.
 {}
Member Function Documentation
ampl() [1/7]
double& WarpedLine::ampl () inline
Access to amplitude.
 {return Ampl;}
References Ampl.
Referenced by main(), and WarpedLine().
ampl() [2/7]
double& WarpedLine::ampl () inline
Access to amplitude.
 {return Ampl;}
ampl() [3/7]
double& WarpedLine::ampl () inline
Access to amplitude.
 {return Ampl;}
ampl() [4/7]
double& WarpedLine::ampl () inline
Access to amplitude.
 {return Ampl;}
ampl() [5/7]
double& WarpedLine::ampl () inline
Access to amplitude.
 {return Ampl;}
ampl() [6/7]
double& WarpedLine::ampl () inline
Access to amplitude.
 {return Ampl;}
ampl() [7/7]
double& WarpedLine::ampl () inline
Access to amplitude.
 {return Ampl;}
lift_off_alpha() [1/2]
double& WarpedLine::lift_off_alpha () inline
Exponential factor for lift off (controls sharpness)
   {
    return Lift_off_alpha;
   }
References Lift_off_alpha.
lift_off_alpha() [2/2]
double& WarpedLine::lift_off_alpha () inline
Exponential factor for lift off (controls sharpness)
   {
    return Lift_off_alpha;
   }
lift_off_amplitude() [1/2]
double& WarpedLine::lift_off_amplitude () inline
Lift off amplitude.
   {
    return Lift_off_amplitude;
   }
References Lift_off_amplitude.
Referenced by main().
lift_off_amplitude() [2/2]
double& WarpedLine::lift_off_amplitude () inline
Lift off amplitude.
   {
    return Lift_off_amplitude;
   }
ngeom_data() [1/6]
unsigned WarpedLine::ngeom_data () const inline virtual
How many items of Data does the shape of the object depend on? None.
Reimplemented from oomph::GeomObject.
   {
    return 0;
   }
ngeom_data() [2/6]
unsigned WarpedLine::ngeom_data () const inline virtual
How many items of Data does the shape of the object depend on? None.
Reimplemented from oomph::GeomObject.
   {
    return 0;
   }
ngeom_data() [3/6]
unsigned WarpedLine::ngeom_data () const inline virtual
How many items of Data does the shape of the object depend on? None.
Reimplemented from oomph::GeomObject.
   {
    return 0;
   }
ngeom_data() [4/6]
unsigned WarpedLine::ngeom_data () const inline virtual
How many items of Data does the shape of the object depend on? None.
Reimplemented from oomph::GeomObject.
   {
    return 0;
   }
ngeom_data() [5/6]
unsigned WarpedLine::ngeom_data () const inline virtual
How many items of Data does the shape of the object depend on? None.
Reimplemented from oomph::GeomObject.
   {
    return 0;
   }
ngeom_data() [6/6]
unsigned WarpedLine::ngeom_data () const inline virtual
How many items of Data does the shape of the object depend on? None.
Reimplemented from oomph::GeomObject.
   {
    return 0;
   }
operator=() [1/6]
void WarpedLine::operator= (const WarpedLine &) inline
Broken assignment operator.
   {
    BrokenCopy::broken_assign("WarpedLine");
   }
References oomph::BrokenCopy::broken_assign().
operator=() [2/6]
void WarpedLine::operator= (const WarpedLine &) inline
Broken assignment operator.
   {
    BrokenCopy::broken_assign("WarpedLine");
   }
References oomph::BrokenCopy::broken_assign().
operator=() [3/6]
void WarpedLine::operator= (const WarpedLine &) inline
Broken assignment operator.
   {
    BrokenCopy::broken_assign("WarpedLine");
   }
References oomph::BrokenCopy::broken_assign().
operator=() [4/6]
void WarpedLine::operator= (const WarpedLine &) inline
Broken assignment operator.
   {
    BrokenCopy::broken_assign("WarpedLine");
   }
References oomph::BrokenCopy::broken_assign().
operator=() [5/6]
void WarpedLine::operator= (const WarpedLine &) inline
Broken assignment operator.
   {
    BrokenCopy::broken_assign("WarpedLine");
   }
References oomph::BrokenCopy::broken_assign().
operator=() [6/6]
void WarpedLine::operator= (const WarpedLine &) inline
Broken assignment operator.
   {
    BrokenCopy::broken_assign("WarpedLine");
   }
References oomph::BrokenCopy::broken_assign().
position() [1/14]
void WarpedLine::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const inline virtual
Parametrised position on object: r(zeta). Evaluated at previous timestep. t=0: current time; t>0: previous timestep. Forward to steady version
Reimplemented from oomph::GeomObject.
   {
    position(zeta,r);
   }
References position(), UniformPSDSelfTest::r, and Eigen::zeta().
position() [2/14]
void WarpedLine::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const inline virtual
Parametrised position on object: r(zeta). Evaluated at previous timestep. t=0: current time; t>0: previous timestep. Forward to steady version
Reimplemented from oomph::GeomObject.
   {
    position(zeta,r);
   }
References UniformPSDSelfTest::r, and Eigen::zeta().
position() [3/14]
void WarpedLine::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const inline virtual
Parametrised position on object: r(zeta). Evaluated at previous timestep. t=0: current time; t>0: previous timestep. Forward to steady version
Reimplemented from oomph::GeomObject.
   {
    position(zeta,r);
   }
References UniformPSDSelfTest::r, and Eigen::zeta().
position() [4/14]
void WarpedLine::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const inline virtual
Parametrised position on object: r(zeta). Evaluated at previous timestep. t=0: current time; t>0: previous timestep. Forward to steady version
Reimplemented from oomph::GeomObject.
   {
    position(zeta,r);
   }
References UniformPSDSelfTest::r, and Eigen::zeta().
position() [5/14]
void WarpedLine::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const inline virtual
Parametrised position on object: r(zeta). Evaluated at previous timestep. t=0: current time; t>0: previous timestep. Forward to steady version
Reimplemented from oomph::GeomObject.
   {
    position(zeta,r);
   }
References UniformPSDSelfTest::r, and Eigen::zeta().
position() [6/14]
void WarpedLine::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const inline virtual
Parametrised position on object: r(zeta). Evaluated at previous timestep. t=0: current time; t>0: previous timestep. Forward to steady version
Reimplemented from oomph::GeomObject.
   {
    position(zeta,r);
   }
References UniformPSDSelfTest::r, and Eigen::zeta().
position() [7/14]
void WarpedLine::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const inline virtual
Parametrised position on object: r(zeta). Evaluated at previous timestep. t=0: current time; t>0: previous timestep. Forward to steady version
Reimplemented from oomph::GeomObject.
   {
    position(zeta,r);
   }
References UniformPSDSelfTest::r, and Eigen::zeta().
position() [8/14]
void WarpedLine::position (const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position vector at Lagrangian coordinate zeta.
Implements oomph::GeomObject.
   {
    double zetaa=X_min+zeta[0]*(X_max-X_min);
    if (Reversed)
     {
      zetaa=X_max+zeta[0]*(X_min-X_max);
     }
    double alpha=atan((4.0*Ampl)/(1.0+4.0*Ampl*Ampl));
    double y_c=1.0+1.0/(2.0*tan(alpha));
    double radius=1.0/(2.0*sin(alpha));
    // Position vector for circular shape
    r[0] = zetaa;
    r[1] = y_c-sqrt(radius*radius-(zetaa-0.5)*(zetaa-0.5));
    // Lift off
    r[1]-=Lift_off_amplitude*exp(-Lift_off_alpha*(zetaa-0.5)*(zetaa-0.5));
   }
References alpha, Ampl, Eigen::bfloat16_impl::atan(), Eigen::bfloat16_impl::exp(), Lift_off_alpha, Lift_off_amplitude, UniformPSDSelfTest::r, radius(), Reversed, sin(), sqrt(), Eigen::bfloat16_impl::tan(), X_max, X_min, y_c(), and Eigen::zeta().
Referenced by PrescribedBoundaryDisplacementProblem< ELEMENT >::actions_before_newton_solve(), and position().
position() [9/14]
void WarpedLine::position (const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position vector at Lagrangian coordinate zeta.
Implements oomph::GeomObject.
   {
    double zetaa=X_min+zeta[0]*(X_max-X_min);
    if (Reversed)
     {
      zetaa=X_max+zeta[0]*(X_min-X_max);
     }
    double alpha=atan((4.0*Ampl)/(1.0+4.0*Ampl*Ampl));
    double y_c=1.0+1.0/(2.0*tan(alpha));
    double radius=1.0/(2.0*sin(alpha));
    // Position vector for circular shape
    r[0] = zetaa;
    r[1] = y_c-sqrt(radius*radius-(zetaa-0.5)*(zetaa-0.5));
    // Lift off
    r[1]-=Lift_off_amplitude*exp(-Lift_off_alpha*(zetaa-0.5)*(zetaa-0.5));
   }
References alpha, Eigen::bfloat16_impl::atan(), Eigen::bfloat16_impl::exp(), UniformPSDSelfTest::r, UniformPSDSelfTest::radius, sin(), sqrt(), Eigen::bfloat16_impl::tan(), RayParam::X_max, RayParam::X_min, and Eigen::zeta().
position() [10/14]
void WarpedLine::position (const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position vector at Lagrangian coordinate zeta.
Implements oomph::GeomObject.
   {
    // Position vector
    r[0] = zeta[0]+5.0*Ampl*zeta[0]*(zeta[0]-1.0)*(zeta[0]-0.7);
    r[1] = 1.0+Ampl*0.5*(1.0-cos(2.0*MathematicalConstants::Pi*zeta[0]));
   }
References cos(), BiharmonicTestFunctions2::Pi, UniformPSDSelfTest::r, and Eigen::zeta().
position() [11/14]
void WarpedLine::position (const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position vector at Lagrangian coordinate zeta.
Implements oomph::GeomObject.
   {
    // Position vector
    r[0] = zeta[0]+5.0*Ampl*zeta[0]*(zeta[0]-0.4)*(zeta[0]-0.7);
    r[1] = 1.0+Ampl*0.5*(1.0-cos(2.0*MathematicalConstants::Pi*zeta[0]/0.4));
   }
References cos(), BiharmonicTestFunctions2::Pi, UniformPSDSelfTest::r, and Eigen::zeta().
position() [12/14]
void WarpedLine::position (const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position vector at Lagrangian coordinate zeta.
Implements oomph::GeomObject.
   {
    // Position vector
    r[0] = zeta[0]+5.0*Ampl*zeta[0]*(zeta[0]-1.0)*(zeta[0]-0.7);
    r[1] = 1.0+Ampl*0.5*(1.0-cos(2.0*MathematicalConstants::Pi*zeta[0]));
   }
References cos(), BiharmonicTestFunctions2::Pi, UniformPSDSelfTest::r, and Eigen::zeta().
position() [13/14]
void WarpedLine::position (const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position vector at Lagrangian coordinate zeta.
Implements oomph::GeomObject.
   {
    // Position vector
    r[0] = zeta[0]+5.0*Ampl*zeta[0]*(zeta[0]-1.0)*(zeta[0]-0.7);
    r[1] = 1.0+Ampl*0.5*(1.0-cos(2.0*MathematicalConstants::Pi*zeta[0]));
   }
References cos(), BiharmonicTestFunctions2::Pi, UniformPSDSelfTest::r, and Eigen::zeta().
position() [14/14]
void WarpedLine::position (const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position vector at Lagrangian coordinate zeta.
Implements oomph::GeomObject.
   {
    // Position vector
    r[0] = zeta[0]+5.0*Ampl*zeta[0]*(zeta[0]-1.0)*(zeta[0]-0.7);
    r[1] = 1.0+Ampl*0.5*(1.0-cos(2.0*MathematicalConstants::Pi*zeta[0]));
   }
References cos(), BiharmonicTestFunctions2::Pi, UniformPSDSelfTest::r, and Eigen::zeta().
radius() [1/2]
double WarpedLine::radius () const inline
Return radius.
   {
    double alpha=atan((4.0*Ampl)/(1.0+4.0*Ampl*Ampl));
    return 1.0/(2.0*sin(alpha));
   }
References alpha, Ampl, Eigen::bfloat16_impl::atan(), and sin().
Referenced by ContactProblem< ELEMENT >::doc_solution(), main(), and position().
radius() [2/2]
double WarpedLine::radius () const inline
Return radius.
   {
    double alpha=atan((4.0*Ampl)/(1.0+4.0*Ampl*Ampl));
    return 1.0/(2.0*sin(alpha));
   }
References alpha, Eigen::bfloat16_impl::atan(), and sin().
set_non_reversed() [1/2]
void WarpedLine::set_non_reversed () inline
Local coordinates are not reversed.
   {
    Reversed=false;
   }
References Reversed.
Referenced by ContactProblem< ELEMENT >::create_displ_imposition_elements().
set_non_reversed() [2/2]
void WarpedLine::set_non_reversed () inline
Local coordinates are not reversed.
   {
    Reversed=false;
   }
set_reversed() [1/2]
void WarpedLine::set_reversed () inline
Local coordinates are reversed.
   {
    Reversed=true;
   }
References Reversed.
Referenced by ContactProblem< ELEMENT >::create_displ_imposition_elements().
set_reversed() [2/2]
void WarpedLine::set_reversed () inline
Local coordinates are reversed.
   {
    Reversed=true;
   }
y_c() [1/2]
double WarpedLine::y_c () const inline
Return y coordinate of centre.
   {
    double alpha=atan((4.0*Ampl)/(1.0+4.0*Ampl*Ampl));
    return 1.0+1.0/(2.0*tan(alpha));
   }
References alpha, Ampl, Eigen::bfloat16_impl::atan(), and Eigen::bfloat16_impl::tan().
Referenced by main(), and position().
y_c() [2/2]
double WarpedLine::y_c () const inline
Return y coordinate of centre.
   {
    double alpha=atan((4.0*Ampl)/(1.0+4.0*Ampl*Ampl));
    return 1.0+1.0/(2.0*tan(alpha));
   }
References alpha, Eigen::bfloat16_impl::atan(), and Eigen::bfloat16_impl::tan().
Member Data Documentation
Ampl
double WarpedLine::Ampl private
Amplitude of perturbation.
Referenced by ampl(), position(), radius(), WarpedLine(), and y_c().
Lift_off_alpha
double WarpedLine::Lift_off_alpha private
Exponential factor for lift off (controls sharpness)
Referenced by lift_off_alpha(), position(), and WarpedLine().
Lift_off_amplitude
double WarpedLine::Lift_off_amplitude private
Lift off amplitude.
Referenced by lift_off_amplitude(), position(), and WarpedLine().
Reversed
bool WarpedLine::Reversed private
Reverse?
Referenced by position(), set_non_reversed(), set_reversed(), and WarpedLine().
X_max
double WarpedLine::X_max private
Max zeta coordinate.
Referenced by position(), and WarpedLine().
X_min
double WarpedLine::X_min private
Min zeta coordinate.
Referenced by position(), and WarpedLine().
The documentation for this class was generated from the following files:
heated_linear_solid_contact_with_gravity.cc
linear_solid_contact_with_gravity.cc
mpi/distribution/prescribed_displ_lagr_mult/prescribed_displ_lagr_mult.cc
resize_hanging_node_tester.cc
prescribed_displ_lagr_mult2.cc
prescribed_displ_lagr_mult_precond.cc