MercuryDPM: Eigen::internal::BandMatrixWrapper< CoefficientsType_, Rows_, Cols_, Supers_, Subs_, Options_ > Class Template Reference
Eigen::internal::BandMatrixWrapper< CoefficientsType_, Rows_, Cols_, Supers_, Subs_, Options_ > Class Template Reference
#include <BandMatrix.h>
Public Types
typedef internal::traits< BandMatrixWrapper >::Scalar Scalar
typedef internal::traits< BandMatrixWrapper >::CoefficientsType CoefficientsType
typedef internal::traits< BandMatrixWrapper >::StorageIndex StorageIndex
Public Types inherited from Eigen::internal::BandMatrixBase< BandMatrixWrapper< CoefficientsType_, Rows_, Cols_, Supers_, Subs_, Options_ > >
enum
typedef internal::traits< BandMatrixWrapper< CoefficientsType_, Rows_, Cols_, Supers_, Subs_, Options_ > >::Scalar Scalar
typedef Matrix< Scalar, RowsAtCompileTime, ColsAtCompileTime > DenseMatrixType
typedef DenseMatrixType::StorageIndex StorageIndex
typedef internal::traits< BandMatrixWrapper< CoefficientsType_, Rows_, Cols_, Supers_, Subs_, Options_ > >::CoefficientsType CoefficientsType
typedef EigenBase< BandMatrixWrapper< CoefficientsType_, Rows_, Cols_, Supers_, Subs_, Options_ > > Base
Public Types inherited from Eigen::EigenBase< BandMatrixWrapper< CoefficientsType_, Rows_, Cols_, Supers_, Subs_, Options_ > >
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< BandMatrixWrapper< CoefficientsType_, Rows_, Cols_, Supers_, Subs_, Options_ > >::StorageKind StorageKind
Public Member Functions
BandMatrixWrapper (const CoefficientsType &coeffs, Index rows=Rows_, Index cols=Cols_, Index supers=Supers_, Index subs=Subs_)
EIGEN_CONSTEXPR Index rows () const
EIGEN_CONSTEXPR Index cols () const
EIGEN_CONSTEXPR Index supers () const
EIGEN_CONSTEXPR Index subs () const
const CoefficientsType & coeffs () const
Public Member Functions inherited from Eigen::internal::BandMatrixBase< BandMatrixWrapper< CoefficientsType_, Rows_, Cols_, Supers_, Subs_, Options_ > >
Index supers () const
Index subs () const
const CoefficientsType & coeffs () const
CoefficientsType & coeffs ()
Block< CoefficientsType, Dynamic, 1 > col (Index i)
Block< CoefficientsType, 1, SizeAtCompileTime > diagonal ()
const Block< const CoefficientsType, 1, SizeAtCompileTime > diagonal () const
DiagonalIntReturnType< N >::Type diagonal ()
const DiagonalIntReturnType< N >::Type diagonal () const
Block< CoefficientsType, 1, Dynamic > diagonal (Index i)
const Block< const CoefficientsType, 1, Dynamic > diagonal (Index i) const
void evalTo (Dest &dst) const
DenseMatrixType toDenseMatrix () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
constexpr EIGEN_DEVICE_FUNC BandMatrixWrapper< CoefficientsType_, Rows_, Cols_, Supers_, Subs_, Options_ > & derived ()
constexpr EIGEN_DEVICE_FUNC const BandMatrixWrapper< CoefficientsType_, Rows_, Cols_, Supers_, Subs_, Options_ > & derived () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
Public Member Functions inherited from Eigen::EigenBase< BandMatrixWrapper< CoefficientsType_, Rows_, Cols_, Supers_, Subs_, Options_ > >
constexpr EIGEN_DEVICE_FUNC BandMatrixWrapper< CoefficientsType_, Rows_, Cols_, Supers_, Subs_, Options_ > & derived ()
constexpr EIGEN_DEVICE_FUNC const BandMatrixWrapper< CoefficientsType_, Rows_, Cols_, Supers_, Subs_, Options_ > & derived () const
EIGEN_DEVICE_FUNC BandMatrixWrapper< CoefficientsType_, Rows_, Cols_, Supers_, Subs_, Options_ > & const_cast_derived () const
EIGEN_DEVICE_FUNC const BandMatrixWrapper< CoefficientsType_, Rows_, Cols_, Supers_, Subs_, Options_ > & const_derived () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index size () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< BandMatrixWrapper< CoefficientsType_, Rows_, Cols_, Supers_, Subs_, Options_ >, Device > device (Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< const BandMatrixWrapper< CoefficientsType_, Rows_, Cols_, Supers_, Subs_, Options_ >, Device > device (Device &device) const
Protected Attributes
const CoefficientsType & m_coeffs
internal::variable_if_dynamic< Index, Rows_ > m_rows
internal::variable_if_dynamic< Index, Supers_ > m_supers
internal::variable_if_dynamic< Index, Subs_ > m_subs
Additional Inherited Members
Protected Types inherited from Eigen::internal::BandMatrixBase< BandMatrixWrapper< CoefficientsType_, Rows_, Cols_, Supers_, Subs_, Options_ > >
enum
Protected Member Functions inherited from Eigen::internal::BandMatrixBase< BandMatrixWrapper< CoefficientsType_, Rows_, Cols_, Supers_, Subs_, Options_ > >
Index diagonalLength (Index i) const
Member Typedef Documentation
CoefficientsType
template<typename CoefficientsType_ , int Rows_, int Cols_, int Supers_, int Subs_, int Options_> typedef internal::traits<BandMatrixWrapper>::CoefficientsType Eigen::internal::BandMatrixWrapper< CoefficientsType_, Rows_, Cols_, Supers_, Subs_, Options_ >::CoefficientsType
Scalar
template<typename CoefficientsType_ , int Rows_, int Cols_, int Supers_, int Subs_, int Options_> typedef internal::traits<BandMatrixWrapper>::Scalar Eigen::internal::BandMatrixWrapper< CoefficientsType_, Rows_, Cols_, Supers_, Subs_, Options_ >::Scalar
StorageIndex
template<typename CoefficientsType_ , int Rows_, int Cols_, int Supers_, int Subs_, int Options_> typedef internal::traits<BandMatrixWrapper>::StorageIndex Eigen::internal::BandMatrixWrapper< CoefficientsType_, Rows_, Cols_, Supers_, Subs_, Options_ >::StorageIndex
Constructor & Destructor Documentation
BandMatrixWrapper()
template<typename CoefficientsType_ , int Rows_, int Cols_, int Supers_, int Subs_, int Options_> Eigen::internal::BandMatrixWrapper< CoefficientsType_, Rows_, Cols_, Supers_, Subs_, Options_ >::BandMatrixWrapper (const CoefficientsType & coeffs, Index rows = Rows_, Index cols = Cols_, Index supers = Supers_, Index subs = Subs_) inline explicit
       : m_coeffs(coeffs), m_rows(rows), m_supers(supers), m_subs(subs) {
     EIGEN_UNUSED_VARIABLE(cols);
     // eigen_assert(coeffs.cols()==cols() && (supers()+subs()+1)==coeffs.rows());
   }
References Eigen::internal::BandMatrixBase< Derived >::cols(), and EIGEN_UNUSED_VARIABLE.
Member Function Documentation
coeffs()
template<typename CoefficientsType_ , int Rows_, int Cols_, int Supers_, int Subs_, int Options_> const CoefficientsType& Eigen::internal::BandMatrixWrapper< CoefficientsType_, Rows_, Cols_, Supers_, Subs_, Options_ >::coeffs () const inline
 { return m_coeffs; }
cols()
template<typename CoefficientsType_ , int Rows_, int Cols_, int Supers_, int Subs_, int Options_> EIGEN_CONSTEXPR Index Eigen::internal::BandMatrixWrapper< CoefficientsType_, Rows_, Cols_, Supers_, Subs_, Options_ >::cols () const inline
Returns
the number of rows
 { return m_coeffs.cols(); }
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
rows()
template<typename CoefficientsType_ , int Rows_, int Cols_, int Supers_, int Subs_, int Options_> EIGEN_CONSTEXPR Index Eigen::internal::BandMatrixWrapper< CoefficientsType_, Rows_, Cols_, Supers_, Subs_, Options_ >::rows () const inline
Returns
the number of columns
 { return m_rows.value(); }
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
subs()
template<typename CoefficientsType_ , int Rows_, int Cols_, int Supers_, int Subs_, int Options_> EIGEN_CONSTEXPR Index Eigen::internal::BandMatrixWrapper< CoefficientsType_, Rows_, Cols_, Supers_, Subs_, Options_ >::subs () const inline
Returns
the number of sub diagonals
 { return m_subs.value(); }
supers()
template<typename CoefficientsType_ , int Rows_, int Cols_, int Supers_, int Subs_, int Options_> EIGEN_CONSTEXPR Index Eigen::internal::BandMatrixWrapper< CoefficientsType_, Rows_, Cols_, Supers_, Subs_, Options_ >::supers () const inline
Returns
the number of super diagonals
 { return m_supers.value(); }
Member Data Documentation
m_coeffs
template<typename CoefficientsType_ , int Rows_, int Cols_, int Supers_, int Subs_, int Options_> const CoefficientsType& Eigen::internal::BandMatrixWrapper< CoefficientsType_, Rows_, Cols_, Supers_, Subs_, Options_ >::m_coeffs protected
m_rows
template<typename CoefficientsType_ , int Rows_, int Cols_, int Supers_, int Subs_, int Options_> internal::variable_if_dynamic<Index, Rows_> Eigen::internal::BandMatrixWrapper< CoefficientsType_, Rows_, Cols_, Supers_, Subs_, Options_ >::m_rows protected
m_subs
template<typename CoefficientsType_ , int Rows_, int Cols_, int Supers_, int Subs_, int Options_> internal::variable_if_dynamic<Index, Subs_> Eigen::internal::BandMatrixWrapper< CoefficientsType_, Rows_, Cols_, Supers_, Subs_, Options_ >::m_subs protected
m_supers
template<typename CoefficientsType_ , int Rows_, int Cols_, int Supers_, int Subs_, int Options_> internal::variable_if_dynamic<Index, Supers_> Eigen::internal::BandMatrixWrapper< CoefficientsType_, Rows_, Cols_, Supers_, Subs_, Options_ >::m_supers protected
The documentation for this class was generated from the following file:
BandMatrix.h