MercuryDPM: Vec3DUnitTest.cpp File Reference
Vec3DUnitTest.cpp File Reference
#include <Math/Vector.h>
#include <Math/Helpers.h>
#include "Logger.h"
Functions
int main ()
Function Documentation
main()
int main ()
 {
     logger(INFO,"Checks several Vec3D unit operations");
     Vec3D a = {1,2,3};
     Vec3D b = {4,5,6};
     Vec3D c;
     c = b - a; //same as c = b.operator-(a);
     helpers::check(c,{3,3,3},0,"Vector subtraction");
     c = - a; //same as c = operator-(a);
     helpers::check(c,{-1,-2,-3},0,"Negation of a vector");
     c -= a; //same as c.operator-=(a);
     helpers::check(c,{-2,-4,-6},0,"Vector self-subtraction");
     c = b + a; //same as c = b.operator-(a);
     helpers::check(c,{5,7,9},0,"Vector addition");
     c = a; //same as c = operator+(a); //missing operator
     //helpers::check(c,{1,2,3},0,"Plus-operation of a vector");
     c += a; //same as c.operator-=(a);
     helpers::check(c,{2,4,6},0,"Vector self-addition");
     helpers::check(Vec3D::dot(a,b),32,0,"Dot product");
     helpers::check(Vec3D::cross(a,b),{-3,6,-3},0,"Cross product");
     return 0;
 }
References a, b, calibrate::c, helpers::check(), Vec3D::cross(), Vec3D::dot(), INFO, and logger.