MercuryDPM: Eigen::internal::homogeneous_left_product_impl< Homogeneous< MatrixType, Vertical >, Lhs > Struct Template Reference
Eigen::internal::homogeneous_left_product_impl< Homogeneous< MatrixType, Vertical >, Lhs > Struct Template Reference
#include <Homogeneous.h>
Public Types
typedef traits< homogeneous_left_product_impl >::LhsMatrixType LhsMatrixType
typedef remove_all_t< LhsMatrixType > LhsMatrixTypeCleaned
typedef remove_all_t< typename LhsMatrixTypeCleaned::Nested > LhsMatrixTypeNested
Public Types inherited from Eigen::ReturnByValue< homogeneous_left_product_impl< Homogeneous< MatrixType, Vertical >, Lhs > >
typedef internal::traits< homogeneous_left_product_impl< Homogeneous< MatrixType, Vertical >, Lhs > >::ReturnType ReturnType
typedef internal::dense_xpr_base< ReturnByValue >::type Base
Public Member Functions
EIGEN_DEVICE_FUNC homogeneous_left_product_impl (const Lhs &lhs, const MatrixType &rhs)
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
Public Member Functions inherited from Eigen::ReturnByValue< homogeneous_left_product_impl< Homogeneous< MatrixType, Vertical >, Lhs > >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
const Unusable & coeff (Index) const
const Unusable & coeff (Index, Index) const
Unusable & coeffRef (Index)
Unusable & coeffRef (Index, Index)
Public Attributes
LhsMatrixTypeCleaned::Nested m_lhs
MatrixType::Nested m_rhs
Member Typedef Documentation
LhsMatrixType
template<typename MatrixType , typename Lhs > typedef traits<homogeneous_left_product_impl>::LhsMatrixType Eigen::internal::homogeneous_left_product_impl< Homogeneous< MatrixType, Vertical >, Lhs >::LhsMatrixType
LhsMatrixTypeCleaned
template<typename MatrixType , typename Lhs > typedef remove_all_t<LhsMatrixType> Eigen::internal::homogeneous_left_product_impl< Homogeneous< MatrixType, Vertical >, Lhs >::LhsMatrixTypeCleaned
LhsMatrixTypeNested
template<typename MatrixType , typename Lhs > typedef remove_all_t<typename LhsMatrixTypeCleaned::Nested> Eigen::internal::homogeneous_left_product_impl< Homogeneous< MatrixType, Vertical >, Lhs >::LhsMatrixTypeNested
Constructor & Destructor Documentation
homogeneous_left_product_impl()
template<typename MatrixType , typename Lhs > EIGEN_DEVICE_FUNC Eigen::internal::homogeneous_left_product_impl< Homogeneous< MatrixType, Vertical >, Lhs >::homogeneous_left_product_impl (const Lhs & lhs, const MatrixType & rhs) inline
       : m_lhs(take_matrix_for_product<Lhs>::run(lhs)), m_rhs(rhs) {}
Member Function Documentation
cols()
template<typename MatrixType , typename Lhs > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::internal::homogeneous_left_product_impl< Homogeneous< MatrixType, Vertical >, Lhs >::cols () const inline
 { return m_rhs.cols(); }
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
evalTo()
template<typename MatrixType , typename Lhs > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::internal::homogeneous_left_product_impl< Homogeneous< MatrixType, Vertical >, Lhs >::evalTo (Dest & dst) const inline
{
     // FIXME investigate how to allow lazy evaluation of this product when possible
     dst = Block < const LhsMatrixTypeNested, LhsMatrixTypeNested::RowsAtCompileTime,
     LhsMatrixTypeNested::ColsAtCompileTime == Dynamic
         ? Dynamic
         : LhsMatrixTypeNested::ColsAtCompileTime - 1 > (m_lhs, 0, 0, m_lhs.rows(), m_lhs.cols() - 1) * m_rhs;
     dst += m_lhs.col(m_lhs.cols() - 1).rowwise().template replicate<MatrixType::ColsAtCompileTime>(m_rhs.cols());
   }
References Eigen::Dynamic.
rows()
template<typename MatrixType , typename Lhs > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::internal::homogeneous_left_product_impl< Homogeneous< MatrixType, Vertical >, Lhs >::rows () const inline
 { return m_lhs.rows(); }
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
Member Data Documentation
m_lhs
template<typename MatrixType , typename Lhs > LhsMatrixTypeCleaned::Nested Eigen::internal::homogeneous_left_product_impl< Homogeneous< MatrixType, Vertical >, Lhs >::m_lhs
m_rhs
template<typename MatrixType , typename Lhs > MatrixType::Nested Eigen::internal::homogeneous_left_product_impl< Homogeneous< MatrixType, Vertical >, Lhs >::m_rhs
The documentation for this struct was generated from the following file:
Homogeneous.h