MercuryDPM: Eigen::Replicate< MatrixType, RowFactor, ColFactor > Class Template Reference
Eigen::Replicate< MatrixType, RowFactor, ColFactor > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
Expression of the multiple replication of a matrix or vector.
#include <Replicate.h>
Public Types
typedef internal::dense_xpr_base< Replicate >::type Base
typedef internal::remove_all_t< MatrixType > NestedExpression
Public Member Functions
template<typename OriginalMatrixType >
EIGEN_DEVICE_FUNC Replicate (const OriginalMatrixType &matrix)
template<typename OriginalMatrixType >
EIGEN_DEVICE_FUNC Replicate (const OriginalMatrixType &matrix, Index rowFactor, Index colFactor)
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const
EIGEN_DEVICE_FUNC const MatrixTypeNested_ & nestedExpression () const
Protected Attributes
MatrixTypeNested m_matrix
const internal::variable_if_dynamic< Index, RowFactor > m_rowFactor
const internal::variable_if_dynamic< Index, ColFactor > m_colFactor
Private Types
typedef internal::traits< Replicate >::MatrixTypeNested MatrixTypeNested
typedef internal::traits< Replicate >::MatrixTypeNested_ MatrixTypeNested_
Detailed Description
template<typename MatrixType, int RowFactor, int ColFactor>
class Eigen::Replicate< MatrixType, RowFactor, ColFactor >
Expression of the multiple replication of a matrix or vector.
Template Parameters
MatrixType the type of the object we are replicating
RowFactor number of repetitions at compile time along the vertical direction, can be Dynamic.
ColFactor number of repetitions at compile time along the horizontal direction, can be Dynamic.
This class represents an expression of the multiple replication of a matrix or vector. It is the return type of DenseBase::replicate() and most of the time this is the only way it is used.
See also
DenseBase::replicate()
Member Typedef Documentation
Base
template<typename MatrixType , int RowFactor, int ColFactor> typedef internal::dense_xpr_base<Replicate>::type Eigen::Replicate< MatrixType, RowFactor, ColFactor >::Base
MatrixTypeNested
template<typename MatrixType , int RowFactor, int ColFactor> typedef internal::traits<Replicate>::MatrixTypeNested Eigen::Replicate< MatrixType, RowFactor, ColFactor >::MatrixTypeNested private
MatrixTypeNested_
template<typename MatrixType , int RowFactor, int ColFactor> typedef internal::traits<Replicate>::MatrixTypeNested_ Eigen::Replicate< MatrixType, RowFactor, ColFactor >::MatrixTypeNested_ private
NestedExpression
template<typename MatrixType , int RowFactor, int ColFactor> typedef internal::remove_all_t<MatrixType> Eigen::Replicate< MatrixType, RowFactor, ColFactor >::NestedExpression
Constructor & Destructor Documentation
Replicate() [1/2]
template<typename MatrixType , int RowFactor, int ColFactor> template<typename OriginalMatrixType > EIGEN_DEVICE_FUNC Eigen::Replicate< MatrixType, RowFactor, ColFactor >::Replicate (const OriginalMatrixType & matrix) inline explicit
       : m_matrix(matrix), m_rowFactor(RowFactor), m_colFactor(ColFactor) {
     EIGEN_STATIC_ASSERT((internal::is_same<std::remove_const_t<MatrixType>, OriginalMatrixType>::value),
                         THE_MATRIX_OR_EXPRESSION_THAT_YOU_PASSED_DOES_NOT_HAVE_THE_EXPECTED_TYPE)
     eigen_assert(RowFactor != Dynamic && ColFactor != Dynamic);
   }
References Eigen::Dynamic, eigen_assert, EIGEN_STATIC_ASSERT, and Eigen::value.
Replicate() [2/2]
template<typename MatrixType , int RowFactor, int ColFactor> template<typename OriginalMatrixType > EIGEN_DEVICE_FUNC Eigen::Replicate< MatrixType, RowFactor, ColFactor >::Replicate (const OriginalMatrixType & matrix, Index rowFactor, Index colFactor) inline
       : m_matrix(matrix), m_rowFactor(rowFactor), m_colFactor(colFactor) {
     EIGEN_STATIC_ASSERT((internal::is_same<std::remove_const_t<MatrixType>, OriginalMatrixType>::value),
                         THE_MATRIX_OR_EXPRESSION_THAT_YOU_PASSED_DOES_NOT_HAVE_THE_EXPECTED_TYPE)
   }
References EIGEN_STATIC_ASSERT, and Eigen::value.
Member Function Documentation
cols()
template<typename MatrixType , int RowFactor, int ColFactor> EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::Replicate< MatrixType, RowFactor, ColFactor >::cols () const inline
 { return m_matrix.cols() * m_colFactor.value(); }
References Eigen::Replicate< MatrixType, RowFactor, ColFactor >::m_colFactor, Eigen::Replicate< MatrixType, RowFactor, ColFactor >::m_matrix, and Eigen::internal::variable_if_dynamic< T, Value >::value().
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
nestedExpression()
template<typename MatrixType , int RowFactor, int ColFactor> EIGEN_DEVICE_FUNC const MatrixTypeNested_& Eigen::Replicate< MatrixType, RowFactor, ColFactor >::nestedExpression () const inline
 { return m_matrix; }
References Eigen::Replicate< MatrixType, RowFactor, ColFactor >::m_matrix.
rows()
template<typename MatrixType , int RowFactor, int ColFactor> EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::Replicate< MatrixType, RowFactor, ColFactor >::rows () const inline
 { return m_matrix.rows() * m_rowFactor.value(); }
References Eigen::Replicate< MatrixType, RowFactor, ColFactor >::m_matrix, Eigen::Replicate< MatrixType, RowFactor, ColFactor >::m_rowFactor, and Eigen::internal::variable_if_dynamic< T, Value >::value().
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
Member Data Documentation
m_colFactor
template<typename MatrixType , int RowFactor, int ColFactor> const internal::variable_if_dynamic<Index, ColFactor> Eigen::Replicate< MatrixType, RowFactor, ColFactor >::m_colFactor protected
Referenced by Eigen::Replicate< MatrixType, RowFactor, ColFactor >::cols().
m_matrix
template<typename MatrixType , int RowFactor, int ColFactor> MatrixTypeNested Eigen::Replicate< MatrixType, RowFactor, ColFactor >::m_matrix protected
Referenced by Eigen::Replicate< MatrixType, RowFactor, ColFactor >::cols(), Eigen::Replicate< MatrixType, RowFactor, ColFactor >::nestedExpression(), and Eigen::Replicate< MatrixType, RowFactor, ColFactor >::rows().
m_rowFactor
template<typename MatrixType , int RowFactor, int ColFactor> const internal::variable_if_dynamic<Index, RowFactor> Eigen::Replicate< MatrixType, RowFactor, ColFactor >::m_rowFactor protected
Referenced by Eigen::Replicate< MatrixType, RowFactor, ColFactor >::rows().
The documentation for this class was generated from the following file:
Replicate.h