MercuryDPM: oomph::RefineableTetgenMesh< ELEMENT > Class Template Reference
oomph::RefineableTetgenMesh< ELEMENT > Class Template Reference
#include <refineable_tetgen_mesh.template.h>
Public Member Functions
RefineableTetgenMesh (TetMeshFacetedClosedSurface *const &outer_boundary_pt, Vector< TetMeshFacetedSurface * > &internal_closed_surface_pt, const double &element_volume, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper, const bool &use_attributes=false)
RefineableTetgenMesh (const Vector< double > &target_volume, tetgenio *const &tetgen_io_pt, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper, const bool &use_attributes=false)
virtual ~RefineableTetgenMesh ()
Empty Destructor.
Problem *& problem_pt ()
double & max_element_size ()
Max element size allowed during adaptation.
double & min_element_size ()
Min element size allowed during adaptation.
double & max_permitted_edge_ratio ()
Min angle before remesh gets triggered.
void doc_adaptivity_targets (std::ostream &outfile)
Doc the targets for mesh adaptation.
void refine_uniformly (DocInfo &doc_info)
Refine mesh uniformly and doc process.
unsigned unrefine_uniformly ()
void adapt (const Vector< double > &elem_error)
Adapt mesh, based on elemental error provided.
void setup_boundary_coordinates_generic (const unsigned &b, const bool &switch_normal, std::ofstream &outfile)
void update_faceted_surface_using_face_mesh (TetMeshFacetedClosedSurface *faceted_surface_pt)
virtual void surface_remesh_for_inner_hole_boundaries ()
void snap_nodes_onto_boundary (RefineableTetgenMesh< ELEMENT > *&new_mesh_pt, const unsigned &b)
Generate a new PSLG representation of the outer boundary.
void initialise_adaptation_data ()
Helper function to initialise data associated with adaptation.
double compute_volume_target (const Vector< double > &elem_error, Vector< double > &target_volume)
RefineableTetgenMesh (TetMeshFacetedClosedSurface *const &outer_boundary_pt, Vector< TetMeshFacetedSurface * > &internal_closed_surface_pt, const double &element_volume, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper, const bool &use_attributes=false, const bool &split_corner_elements=false, Vector< double > *const &target_element_volume_in_region_pt=nullptr)
virtual ~RefineableTetgenMesh ()
Empty Destructor.
void refine_uniformly (DocInfo &doc_info)
Refine mesh uniformly and doc process.
unsigned unrefine_uniformly ()
void adapt (const Vector< double > &elem_error)
Adapt mesh, based on elemental error provided.
bool projection_is_disabled ()
Is projection of old solution onto new mesh disabled?
void disable_projection ()
Disable projection of old solution onto new mesh.
void enable_projection ()
Disable projection of old solution onto new mesh.
Public Member Functions inherited from oomph::TetgenMesh< ELEMENT >
TetgenMesh ()
Empty constructor.
TetgenMesh (const std::string &node_file_name, const std::string &element_file_name, const std::string &face_file_name, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper, const bool &use_attributes=false)
Constructor with the input files.
TetgenMesh (tetgenio &tetgen_data, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper, const bool &use_attributes=false)
Constructor with tetgenio data structure.
TetgenMesh (const std::string &node_file_name, const std::string &element_file_name, const std::string &face_file_name, const bool &split_corner_elements, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper, const bool &use_attributes=false)
TetgenMesh (tetgenio &tetgen_data, const bool &split_corner_elements, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper, const bool &use_attributes=false)
TetgenMesh (TetMeshFacetedClosedSurface *const &outer_boundary_pt, Vector< TetMeshFacetedSurface * > &internal_surface_pt, const double &element_volume, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper, const bool &use_attributes=false, const bool &split_corner_elements=false, Vector< double > *const &target_element_volume_in_region_pt=nullptr)
void build_tetgenio (TetMeshFacetedSurface *const &outer_boundary_pt, Vector< TetMeshFacetedSurface * > &internal_surface_pt, Vector< double > *const &target_element_volume_in_region_pt, tetgenio &tetgen_io)
Build tetgenio object from the TetMeshFacetedSurfaces.
~TetgenMesh ()
Empty destructor.
void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
bool tetgenio_exists () const
Boolen defining whether tetgenio object has been built or not.
tetgenio *& tetgenio_pt ()
Access to the triangulateio representation of the mesh.
void set_deep_copy_tetgenio_pt (tetgenio *const &tetgenio_pt)
Set the tetgen pointer by a deep copy.
void deep_copy_of_tetgenio (tetgenio *const &input_pt, tetgenio *&output_pt)
Public Member Functions inherited from oomph::TetMeshBase
TetMeshBase ()
Constructor.
TetMeshBase (const TetMeshBase &node)=delete
Broken copy constructor.
void operator= (const TetMeshBase &)=delete
Broken assignment operator.
virtual ~TetMeshBase ()
Destructor (empty)
void assess_mesh_quality (std::ofstream &some_file)
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b)
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b, const bool &switch_normal)
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b, const bool &switch_normal, std::ofstream &outfile)
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b, std::ofstream &outfile)
unsigned nboundary_element_in_region (const unsigned &b, const unsigned &r) const
Return the number of elements adjacent to boundary b in region r.
FiniteElement * boundary_element_in_region_pt (const unsigned &b, const unsigned &r, const unsigned &e) const
Return pointer to the e-th element adjacent to boundary b in region r.
int face_index_at_boundary_in_region (const unsigned &b, const unsigned &r, const unsigned &e) const
Return face index of the e-th element adjacent to boundary b in region r.
unsigned nregion ()
Return the number of regions specified by attributes.
unsigned nregion_element (const unsigned &r)
Return the number of elements in region r.
double region_attribute (const unsigned &i)
FiniteElement * region_element_pt (const unsigned &r, const unsigned &e)
Return the e-th element in the r-th region.
template<class ELEMENT >
void snap_to_quadratic_surface (const Vector< unsigned > &boundary_id, const std::string &quadratic_surface_file_name, const bool &switch_normal, DocInfo &doc_info)
template<class ELEMENT >
void snap_to_quadratic_surface (const Vector< unsigned > &boundary_id, const std::string &quadratic_surface_file_name, const bool &switch_normal)
void snap_nodes_onto_geometric_objects ()
template<class ELEMENT >
void split_elements_in_corners (TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
void setup_boundary_element_info ()
void setup_boundary_element_info (std::ostream &outfile)
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void node_update (const bool &update_all_solid_nodes=false)
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Public Member Functions inherited from oomph::RefineableMeshBase
bool adapt_flag ()
RefineableMeshBase ()
RefineableMeshBase (const RefineableMeshBase &dummy)=delete
Broken copy constructor.
void operator= (const RefineableMeshBase &)=delete
Broken assignment operator.
virtual ~RefineableMeshBase ()
Empty Destructor:
unsigned nrefined ()
Access fct for number of elements that were refined.
unsigned nunrefined ()
Access fct for number of elements that were unrefined.
unsigned & nrefinement_overruled ()
unsigned & max_keep_unrefined ()
ErrorEstimator *& spatial_error_estimator_pt ()
Access to spatial error estimator.
ErrorEstimator * spatial_error_estimator_pt () const
Access to spatial error estimator (const version.
double & min_permitted_error ()
double & max_permitted_error ()
double & min_error ()
double & max_error ()
DocInfo *& doc_info_pt ()
Access fct for pointer to DocInfo.
void enable_adaptation ()
Enable adaptation.
void disable_adaptation ()
Disable adaptation.
void enable_p_adaptation ()
Enable adaptation.
void disable_p_adaptation ()
Disable adaptation.
void enable_additional_synchronisation_of_hanging_nodes ()
Enable additional synchronisation of hanging nodes.
void disable_additional_synchronisation_of_hanging_nodes ()
Disable additional synchronisation of hanging nodes.
bool is_adaptation_enabled () const
Return whether the mesh is to be adapted.
bool is_p_adaptation_enabled () const
Return whether the mesh is to be adapted.
bool is_additional_synchronisation_of_hanging_nodes_disabled () const
Return whether additional synchronisation is enabled.
DocInfo doc_info ()
Access fct for DocInfo.
virtual void p_adapt (const Vector< double > &elemental_error)
virtual void refine_uniformly ()
Refine mesh uniformly.
virtual void p_refine_uniformly (DocInfo &doc_info)
p-refine mesh uniformly and doc process
virtual void p_refine_uniformly ()
p-refine mesh uniformly
void p_unrefine_uniformly (DocInfo &doc_info)
p-unrefine mesh uniformly
Public Member Functions inherited from oomph::RefineableTetMeshBase
double & max_element_size ()
Max element size allowed during adaptation.
double & min_element_size ()
Min element size allowed during adaptation.
double & max_permitted_edge_ratio ()
Min edge ratio before remesh gets triggered.
void doc_adaptivity_targets (std::ostream &outfile)
Doc the targets for mesh adaptation.
double compute_volume_target (const Vector< double > &elem_error, Vector< double > &target_volume)
Public Attributes
Problem * Problem_pt
double Max_element_size
Max permitted element size.
double Min_element_size
Min permitted element size.
double Max_permitted_edge_ratio
Max edge ratio before remesh gets triggered.
Public Attributes inherited from oomph::RefineableTetMeshBase
double Max_element_size
Max permitted element size.
double Min_element_size
Min permitted element size.
double Max_permitted_edge_ratio
Max edge ratio before remesh gets triggered.
Protected Member Functions
RefineableTetgenMesh (const Vector< double > &target_volume, tetgenio *const &tetgen_io_pt, TetMeshFacetedClosedSurface *const &outer_boundary_pt, Vector< TetMeshFacetedSurface * > &internal_surface_pt, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper, const bool &use_attributes=false)
void initialise_adaptation_data ()
Helper function to initialise data associated with adaptation.
void update_faceted_surface_using_face_mesh (TetMeshFacetedSurface *&faceted_surface_pt)
void surface_remesh_for_inner_hole_boundaries ()
void snap_nodes_onto_boundary (RefineableTetgenMesh< ELEMENT > *&new_mesh_pt, const unsigned &b)
Snap the boundary nodes onto any curvilinear boundaries.
Protected Member Functions inherited from oomph::TetgenMesh< ELEMENT >
void build_from_scaffold (TimeStepper *time_stepper_pt, const bool &use_attributes)
Build mesh from scaffold.
void setup_reverse_lookup_schemes_for_faceted_surface (TetMeshFacetedSurface *const &faceted_surface_pt)
Function to setup the reverse look-up schemes.
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Protected Attributes
bool Projection_is_disabled
Disable projection of solution onto new mesh during adaptation.
bool Corner_elements_must_be_split
Protected Attributes inherited from oomph::TetgenMesh< ELEMENT >
TetgenScaffoldMesh * Tmp_mesh_pt
Temporary scaffold mesh.
bool Tetgenio_exists
tetgenio * Tetgenio_pt
Tetgen representation of mesh.
bool Use_attributes
Protected Attributes inherited from oomph::TetMeshBase
Vector< Vector< FiniteElement * > > Region_element_pt
Vector< double > Region_attribute
Vector< std::map< unsigned, Vector< FiniteElement * > > > Boundary_region_element_pt
Storage for elements adjacent to a boundary in a particular region.
Vector< std::map< unsigned, Vector< int > > > Face_index_region_at_boundary
TetMeshFacetedClosedSurface * Outer_boundary_pt
Faceted surface that defines outer boundaries.
Vector< TetMeshFacetedSurface * > Internal_surface_pt
Vector to faceted surfaces that define internal boundaries.
std::map< unsigned, TetMeshFacetedSurface * > Tet_mesh_faceted_surface_pt
std::map< unsigned, TetMeshFacet * > Tet_mesh_facet_pt
std::map< unsigned, Vector< Vector< double > > > Triangular_facet_vertex_boundary_coordinate
TimeStepper * Time_stepper_pt
Timestepper used to build nodes.
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Protected Attributes inherited from oomph::RefineableMeshBase
ErrorEstimator * Spatial_error_estimator_pt
Pointer to spatial error estimator.
double Max_permitted_error
Max. error (i.e. split elements if their error is larger)
double Min_permitted_error
Min. error (i.e. (try to) merge elements if their error is smaller)
double Min_error
Min.actual error.
double Max_error
Max. actual error.
unsigned Nrefined
Stats: Number of elements that were refined.
unsigned Nunrefined
Stats: Number of elements that were unrefined.
bool Adapt_flag
Flag that requests adaptation.
bool P_adapt_flag
Flag that requests p-adaptation.
bool Additional_synchronisation_of_hanging_nodes_not_required
Flag that disables additional synchronisation of hanging nodes.
DocInfo * Doc_info_pt
Pointer to DocInfo.
unsigned Max_keep_unrefined
unsigned Nrefinement_overruled
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::TetMeshBase
static double Tolerance_for_boundary_finding = 1.0e-5
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Constructor & Destructor Documentation
RefineableTetgenMesh() [1/4]
template<class ELEMENT > oomph::RefineableTetgenMesh< ELEMENT >::RefineableTetgenMesh (TetMeshFacetedClosedSurface *const & outer_boundary_pt, Vector< TetMeshFacetedSurface * > & internal_closed_surface_pt, const double & element_volume, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper, const bool & use_attributes = false) inline
Build mesh, based on a TetgenMeshClosedSurface that specifies the outer boundary of the domain and any number of internal closed curves, also specified by TriangleMeshClosedSurfaces. Also specify target area for uniform element size.
                                       :
     TetgenMesh<ELEMENT>(outer_boundary_pt,
                         internal_closed_surface_pt,
                         element_volume,
                         time_stepper_pt,
                         use_attributes)
     {
      // Initialise the data associated with adaptation
       initialise_adaptation_data();
     }
RefineableTetgenMesh() [2/4]
template<class ELEMENT > oomph::RefineableTetgenMesh< ELEMENT >::RefineableTetgenMesh (const Vector< double > & target_volume, tetgenio *const & tetgen_io_pt, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper, const bool & use_attributes = false) inline
Build mesh from specified triangulation and associated target volumes for elements in it
     {
      // Initialise the data associated with adaptation
      initialise_adaptation_data();
      // Store Timestepper used to build elements
      this->Time_stepper_pt=time_stepper_pt;
      // Triangulation has been created -- remember to wipe it!
      this->Tetgenio_exists =true;
      this->Tetgenio_pt = new tetgenio;
      // Add the volume constraints to the tetgenio data object
      // which may be bad because it's actually modifying things in the base
      //mesh
      //Create a local copy
      tetgenio *tetgen_input_pt = new tetgenio;;
      this->deep_copy_of_tetgenio(tetgen_io_pt,tetgen_input_pt);
      //Add volume constraints
      tetgen_input_pt->tetrahedronvolumelist =
       new double[tetgen_input_pt->numberoftetrahedra];
      for(int e=0;e<tetgen_input_pt->numberoftetrahedra;++e)
       {
        tetgen_input_pt->tetrahedronvolumelist[e] = target_volume[e];
       }
      // Input string for triangle
      std::stringstream input_string_stream;
      input_string_stream<< "Vqra";
      // Convert to a *char required by the triangulate function
      char tetswitches[100];
      sprintf(tetswitches,"%s",input_string_stream.str().c_str());
      // Build triangulateio refined object
      tetrahedralize(tetswitches, tetgen_input_pt, this->Tetgenio_pt);
      // Build scaffold
      this->Tmp_mesh_pt=new TetgenScaffoldMesh(*this->Tetgenio_pt);
      // Convert mesh from scaffold to actual mesh
      this->build_from_scaffold(time_stepper_pt,use_attributes);
      // Kill the scaffold
      delete this->Tmp_mesh_pt;
      this->Tmp_mesh_pt=0;
      //delete the input
      delete tetgen_input_pt;
      // Setup boundary coordinates for boundaries
      //unsigned nb=nboundary();
      //for (unsigned b=0;b<nb;b++)
      // {
      //  this->setup_boundary_coordinates(b);
      // }
     }
References e(), tetgenio::numberoftetrahedra, tetrahedralize(), and tetgenio::tetrahedronvolumelist.
~RefineableTetgenMesh() [1/2]
template<class ELEMENT > virtual oomph::RefineableTetgenMesh< ELEMENT >::~RefineableTetgenMesh () inline virtual
Empty Destructor.
 {}
RefineableTetgenMesh() [3/4]
template<class ELEMENT > oomph::RefineableTetgenMesh< ELEMENT >::RefineableTetgenMesh (TetMeshFacetedClosedSurface *const & outer_boundary_pt, Vector< TetMeshFacetedSurface * > & internal_closed_surface_pt, const double & element_volume, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper, const bool & use_attributes = false, const bool & split_corner_elements = false, Vector< double > *const & target_element_volume_in_region_pt = nullptr) inline
Build mesh, based on a TetMeshFacetedClosedSurface that specifies the outer boundary of the domain and any number of internal closed curves, specified by TetMeshFacetedSurfaces. Also specify target volume for uniform element size.
       : TetgenMesh<ELEMENT>(outer_boundary_pt,
                             internal_closed_surface_pt,
                             element_volume,
                             time_stepper_pt,
                             use_attributes,
                             split_corner_elements,
                             target_element_volume_in_region_pt),
         Corner_elements_must_be_split(split_corner_elements)
     {
       // Initialise the data associated with adaptation
       initialise_adaptation_data();
     }
References oomph::RefineableTetgenMesh< ELEMENT >::initialise_adaptation_data().
RefineableTetgenMesh() [4/4]
template<class ELEMENT > oomph::RefineableTetgenMesh< ELEMENT >::RefineableTetgenMesh (const Vector< double > & target_volume, tetgenio *const & tetgen_io_pt, TetMeshFacetedClosedSurface *const & outer_boundary_pt, Vector< TetMeshFacetedSurface * > & internal_surface_pt, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper, const bool & use_attributes = false) inline protected
Specialised constructor used during adaptation only. Element sizes are specified by vector tetgen_io is passed in from previous mesh (is then modified to build new mesh) Ditto with use_attributes, which comes from the previous mesh
     {
       // NOTE THERE IS A CERTAIN AMOUNT OF DUPLICATION BETWEEN THE
       // CODE IN HERE AND THE ONE IN THE CONSTRUCTOR OF THE TetgenMesh
       // BUT THE FACT THAT WE HAVE TO MODIFY THE TETGENIO STRUCTURE
       // MEANS WE CAN'T QUITE RECYCLE THIS.
       // Mesh can only be built with 3D Telements.
       MeshChecker::assert_geometric_element<TElementGeometricBase, ELEMENT>(3);
       // Initialise the data associated with adaptation
       initialise_adaptation_data();
       // Store Timestepper used to build elements
       this->Time_stepper_pt = time_stepper_pt;
       // Triangulation has been created -- remember to wipe it!
       this->Tetgenio_exists = true;
       this->Tetgenio_pt = new tetgenio;
       // Add the volume constraints to the tetgenio data object.
       // Note that since the tetgenio structure is referred to by pointer
       // we're also modifying the one associated with the (still existing)
       // original mesh. Bit naughty but shouldn't cause any problems
       // since that mesh is already built and about to go out of scope
       // anyway.
       // Create a local copy
       tetgenio* tetgen_input_pt = new tetgenio;
       ;
       this->deep_copy_of_tetgenio(tetgen_io_pt, tetgen_input_pt);
       // Add volume constraints
       tetgen_input_pt->tetrahedronvolumelist =
         new double[tetgen_input_pt->numberoftetrahedra];
       for (int e = 0; e < tetgen_input_pt->numberoftetrahedra; ++e)
       {
         tetgen_input_pt->tetrahedronvolumelist[e] = target_volume[e];
       }
       // Input string
       std::stringstream input_string_stream;
       input_string_stream << "Vqra";
       // Convert to a *char
       char tetswitches[100];
       sprintf(tetswitches, "%s", input_string_stream.str().c_str());
       // Build triangulateio refined object
       tetrahedralize(tetswitches, tetgen_input_pt, this->Tetgenio_pt);
       // Build scaffold
       this->Tmp_mesh_pt = new TetgenScaffoldMesh(*this->Tetgenio_pt);
       // Convert mesh from scaffold to actual mesh
       this->build_from_scaffold(time_stepper_pt, use_attributes);
       // Kill the scaffold
       delete this->Tmp_mesh_pt;
       this->Tmp_mesh_pt = 0;
       // delete the input
       delete tetgen_input_pt;
       // Store the boundary
       this->Outer_boundary_pt = outer_boundary_pt;
       // Setup the reverse lookup scheme
       this->setup_reverse_lookup_schemes_for_faceted_surface(
         this->Outer_boundary_pt);
       // Store the internal boundary
       this->Internal_surface_pt = internal_surface_pt;
       // Setup the reverse lookup schemes
       {
         unsigned n = this->Internal_surface_pt.size();
         for (unsigned i = 0; i < n; i++)
         {
           this->setup_reverse_lookup_schemes_for_faceted_surface(
             this->Internal_surface_pt[i]);
         }
       }
       // Setup boundary coordinates for boundaries
       unsigned nb = nboundary();
       for (unsigned b = 0; b < nb; b++)
       {
         this->template setup_boundary_coordinates<ELEMENT>(b);
       }
       // Now snap onto geometric objects associated with triangular facets
       // (if any!)
       this->snap_nodes_onto_geometric_objects();
     }
References b, oomph::TetgenMesh< ELEMENT >::build_from_scaffold(), oomph::TetgenMesh< ELEMENT >::deep_copy_of_tetgenio(), e(), i, oomph::RefineableTetgenMesh< ELEMENT >::initialise_adaptation_data(), oomph::TetMeshBase::Internal_surface_pt, n, nb, oomph::Mesh::nboundary(), tetgenio::numberoftetrahedra, oomph::TetMeshBase::Outer_boundary_pt, oomph::TetgenMesh< ELEMENT >::setup_reverse_lookup_schemes_for_faceted_surface(), oomph::TetMeshBase::snap_nodes_onto_geometric_objects(), oomph::TetgenMesh< ELEMENT >::Tetgenio_exists, oomph::TetgenMesh< ELEMENT >::Tetgenio_pt, tetrahedralize(), tetgenio::tetrahedronvolumelist, oomph::TetMeshBase::Time_stepper_pt, and oomph::TetgenMesh< ELEMENT >::Tmp_mesh_pt.
~RefineableTetgenMesh() [2/2]
template<class ELEMENT > virtual oomph::RefineableTetgenMesh< ELEMENT >::~RefineableTetgenMesh () inline virtual
Empty Destructor.
 {}
Member Function Documentation
adapt() [1/2]
template<class ELEMENT > void oomph::RefineableTetgenMesh< ELEMENT >::adapt (const Vector< double > & elem_error) virtual
Adapt mesh, based on elemental error provided.
Adapt problem based on specified elemental error estimates.
////////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////////
Implements oomph::RefineableMeshBase.
  {
   // Get refinement targets
   Vector<double> target_size(elem_error.size());
   double max_edge_ratio=compute_volume_target(elem_error,
                                               target_size);
   // Get maximum target volume
   unsigned n=target_size.size();
   double max_size=0.0;
   double min_size=DBL_MAX;
   for (unsigned e=0;e<n;e++)
    {
     if (target_size[e]>max_size) max_size=target_size[e];
     if (target_size[e]<min_size) min_size=target_size[e];
    }
   oomph_info << "Maximum target size: " << max_size << std::endl;
   oomph_info << "Minimum target size: " << min_size << std::endl;
   oomph_info << "Number of elements to be refined "
              << this->Nrefined << std::endl;
   oomph_info << "Number of elements to be unrefined "
              << this->Nunrefined << std::endl;
   oomph_info << "Max edge ratio "<< max_edge_ratio << std::endl;
   double orig_max_size, orig_min_size;
   this->max_and_min_element_size(orig_max_size, orig_min_size);
   oomph_info << "Max/min element size in original mesh: "
              << orig_max_size  << " "
              << orig_min_size << std::endl;
   // Should we bother to adapt?
   if ( (Nrefined > 0) || (Nunrefined > this->max_keep_unrefined()) ||
        (max_edge_ratio > this->max_permitted_edge_ratio()) )
    {
     if (! ( (Nrefined > 0) || (Nunrefined > max_keep_unrefined()) ) )
      {
       oomph_info
        << "Mesh regeneration triggered by edge ratio criterion\n";
      }
     //Generate a new 1D mesh representation of the inner hole boundaries
     this->surface_remesh_for_inner_hole_boundaries();
     //Update the representation of the outer boundary
     //this->surface_remesh_for_outer_boundary();
     //If there is not a geometric object associated with the boundary
     //the reset the boundary coordinates so that the lengths are consistent
     //in the new mesh and the old mesh.
     const  unsigned n_boundary = this->nboundary();
     for(unsigned b=0;b<n_boundary;++b)
      {
       //if(this->boundary_geom_object_pt(b)==0)
        {
         this->setup_boundary_coordinates(b);
        }
      }
     // Are we dealing with a solid mesh?
     SolidMesh* solid_mesh_pt=dynamic_cast<SolidMesh*>(this);
     // Build temporary uniform background mesh
     //----------------------------------------
     // with volume set by maximum required volume
     //---------------------------------------
     RefineableTetgenMesh<ELEMENT>* tmp_new_mesh_pt=0;
     /*  if (solid_mesh_pt!=0)
      {
       tmp_new_mesh_pt=new RefineableSolidTriangleMesh<ELEMENT>
        (closed_curve_pt,
         hole_pt,
         max_size,
         this->Time_stepper_pt,
         this->Use_attributes);
      }
      else*/
     {
      tmp_new_mesh_pt=new RefineableTetgenMesh<ELEMENT>
       (this->Outer_boundary_pt,
        this->Internal_surface_pt,
        max_size,
        this->Time_stepper_pt,
        this->Use_attributes);
     }
     // Snap to curvilinear boundaries (some code duplication as this
     // is repeated below but helper function would take so many
     // arguments that it's nearly as messy...
     //Pass the boundary  geometric objects to the new mesh
     //tmp_new_mesh_pt->boundary_geom_object_pt() =
     // this->boundary_geom_object_pt();
     //Reset the boundary coordinates if there is
     //a geometric object associated with the boundary
     //tmp_new_mesh_pt->boundary_coordinate_limits() =
     // this->boundary_coordinate_limits();
     //for (unsigned b=0;b<n_boundary;b++)
     // {
     //  if(tmp_new_mesh_pt->boundary_geom_object_pt(b)!=0)
     //   {
     //    tmp_new_mesh_pt->setup_boundary_coordinates(b);
     //   }
     // }
     //Output the mesh before any snapping takes place
     tmp_new_mesh_pt->output("pre_mesh_nodes_snapped_0.dat");
     //Move the nodes on the new boundary onto the
     //old curvilinear boundary
     //If the boundary is straight this will do precisely nothing
     //but will be somewhat inefficient
     for(unsigned b=0;b<n_boundary;b++)
      {
       this->snap_nodes_onto_boundary(tmp_new_mesh_pt,b);
      }
     //Output the mesh after the snapping has taken place
     tmp_new_mesh_pt->output("mesh_nodes_snapped_0.dat");
     // Get the tetgenio object associated with that mesh
     tetgenio *tmp_new_tetgenio_pt = tmp_new_mesh_pt->tetgenio_pt();
 #ifdef PARANOID
     if (this->Problem_pt==0)
      {
       throw OomphLibError("Problem pointer must be set with problem_pt()",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
      }
 #endif
     RefineableTetgenMesh<ELEMENT>* new_mesh_pt=0;
     // Map storing target sizes for elements in temporary
     // tetgenio mesh
     std::map<GeneralisedElement*,double> target_size_map;
     // NOTE: Repeated setup of multidomain interaction could
     // be avoided by setting up a sufficiently fine bin
     // for the original mesh and reading out the target
     // area information from there
     // Now start iterating to refine mesh recursively
     //-----------------------------------------------
     bool done=false;
     unsigned iter=0;
     while (!done)
      {
       // "Project" target volumes from current mesh onto uniform
       //------------------------------------------------------
       // background mesh
       //----------------
       // Temporarily switch on projection capabilities to allow
       // storage of pointer to external element.
       // Need to do this for both meshes to ensure that
       // matching is done based on Eulerian coordinates for both
       // (in case we're dealing with solid meshes where the
       // locate_zeta would otherwise use the Lagrangian coordintes).
       unsigned nelem=this->nelement();
       for (unsigned e=0;e<nelem;e++)
        {
         dynamic_cast<ELEMENT*>(this->element_pt(e))->enable_projection();
        }
       unsigned nelem2=tmp_new_mesh_pt->nelement();
       for (unsigned e=0;e<nelem2;e++)
        {
         dynamic_cast<ELEMENT*>(tmp_new_mesh_pt->element_pt(e))->
          enable_projection();
        }
       // Set up multi domain interactions so we can figure out
       // which element in the intermediate uniform mesh is co-located
       // with given element in current mesh (which is to be refined)
       Multi_domain_functions::setup_multi_domain_interaction
        <ELEMENT>(this->Problem_pt,this,tmp_new_mesh_pt);
       target_size_map.clear();
       for (unsigned e=0;e<nelem;e++)
        {
         ELEMENT* el_pt=dynamic_cast<ELEMENT*>(this->element_pt(e));
         unsigned nint=el_pt->integral_pt()->nweight();
         for (unsigned ipt=0;ipt<nint;ipt++)
          {
           GeneralisedElement* ext_el_pt=el_pt->external_element_pt(0,ipt);
           // Use max. rather than min area of any element overlapping the
           // the current element, otherwise we get a rapid outward diffusion
           // of small elements
           target_size_map[ext_el_pt]=std::max(target_size_map[ext_el_pt],
                                               target_size[e]);
          }
         // Switch off projection capability
         dynamic_cast<ELEMENT*>(this->element_pt(e))->disable_projection();
        }
       for (unsigned e=0;e<nelem2;e++)
        {
         dynamic_cast<ELEMENT*>(tmp_new_mesh_pt->element_pt(e))->
          disable_projection();
        }
       // Now copy into target area for temporary mesh but limit to
       // the equivalent of one sub-division per iteration
       done=true;
       unsigned nel_new=tmp_new_mesh_pt->nelement();
       Vector<double> new_target_size(nel_new);
       for (unsigned e=0;e<nel_new;e++)
        {
         // No target area found for this element -- keep its size
         // by setting target area to -1 for tetrahedron
         double new_size=target_size_map[tmp_new_mesh_pt->element_pt(e)];
         if (new_size<=0.0)
          {
           new_target_size[e]=-1.0;
          }
         else
          {
           // Limit target area to the equivalent of uniform
           // refinement during this stage of the iteration
           new_target_size[e]=new_size;
           if (new_target_size[e]<
               tmp_new_mesh_pt->finite_element_pt(e)->size()/4.0)
            {
             //ALH: It seems that tetgen "enlarges" the volume constraint
             //so this criterion can never be meet unless dividing by 1.2
             //as well.
             new_target_size[e]=
              tmp_new_mesh_pt->finite_element_pt(e)->size()/4.0;
             //This is the tetgen adjustment
             new_target_size[e] /= 1.2;
             // We'll need to give it another go later
             done=false;
            }
          }
        }
       // Now create the new mesh from TriangulateIO structure
       //-----------------------------------------------------
       // associated with uniform background mesh and the
       //------------------------------------------------
       // associated target element sizes.
       //---------------------------------
       // Solid mesh?
       /*if (solid_mesh_pt!=0)
        {
         new_mesh_pt=new RefineableSolidTriangleMesh<ELEMENT>
          (new_target_area,
           tmp_new_triangulateio,
           this->Time_stepper_pt,
           this->Use_attributes);
        }
       // No solid mesh
       else */
        {
         new_mesh_pt=new RefineableTetgenMesh<ELEMENT>
          (new_target_size,
           tmp_new_tetgenio_pt,
           this->Time_stepper_pt,
           this->Use_attributes);
        }
       // Snap to curvilinear boundaries (some code duplication as this
       // is repeated below but helper function would take so many
       // arguments that it's nearly as messy...
       //Pass the boundary  geometric objects to the new mesh
       //new_mesh_pt->boundary_geom_object_pt() =
       // this->boundary_geom_object_pt();
       // Reset the boundary coordinates if there is
       // a geometric object associated with the boundary
       //new_mesh_pt->boundary_coordinate_limits() =
       // this->boundary_coordinate_limits();
       //for (unsigned b=0;b<n_boundary;b++)
       // {
       //  if(new_mesh_pt->boundary_geom_object_pt(b)!=0)
       //   {
       //    new_mesh_pt->setup_boundary_coordinates(b);
       //   }
       // }
       //Output the mesh before any snapping takes place
       new_mesh_pt->output("pre_mesh_nodes_snapped_1.dat");
       //Move the nodes on the new boundary onto the
       //old curvilinear boundary
       //If the boundary is straight this will do precisely nothing
       //but will be somewhat inefficient
       for(unsigned b=0;b<n_boundary;b++)
        {
         this->snap_nodes_onto_boundary(new_mesh_pt,b);
        }
       //Output the mesh after the snapping has taken place
       new_mesh_pt->output("mesh_nodes_snapped_1.dat");
       // Not done: get ready for another iteration
       iter++;
       //Delete the temporary mesh
       delete tmp_new_mesh_pt;
       //Now transfer over the pointers
       if (!done)
        {
         tmp_new_mesh_pt=new_mesh_pt;
         tmp_new_tetgenio_pt=new_mesh_pt->tetgenio_pt();
        }
      } // end of iteration
     // Project current solution onto new mesh
     //---------------------------------------
     ProjectionProblem<ELEMENT>* project_problem_pt=
      new ProjectionProblem<ELEMENT>;
     project_problem_pt->mesh_pt()=new_mesh_pt;
     project_problem_pt->project(this);
     //this->output("pre_proj",5);
     //new_mesh_pt->output("post_proj.dat",5);
     //Flush the old mesh
     unsigned nnod=nnode();
     for(unsigned j=nnod;j>0;j--)
      {
       delete Node_pt[j-1];
       Node_pt[j-1] = 0;
      }
     unsigned nel=nelement();
     for(unsigned e=nel;e>0;e--)
      {
       delete Element_pt[e-1];
       Element_pt[e-1] = 0;
      }
     // Now copy back to current mesh
     //------------------------------
     nnod=new_mesh_pt->nnode();
     Node_pt.resize(nnod);
     nel=new_mesh_pt->nelement();
     Element_pt.resize(nel);
     for(unsigned j=0;j<nnod;j++)
      {
       Node_pt[j] = new_mesh_pt->node_pt(j);
      }
     for(unsigned e=0;e<nel;e++)
      {
       Element_pt[e] = new_mesh_pt->element_pt(e);
      }
     //Copy the boundary schemes
     unsigned nbound=new_mesh_pt->nboundary();
     Boundary_element_pt.resize(nbound);
     Face_index_at_boundary.resize(nbound);
     Boundary_node_pt.resize(nbound);
     for (unsigned b=0;b<nbound;b++)
      {
       unsigned nel=new_mesh_pt->nboundary_element(b);
       Boundary_element_pt[b].resize(nel);
       Face_index_at_boundary[b].resize(nel);
       for (unsigned e=0;e<nel;e++)
        {
         Boundary_element_pt[b][e]=new_mesh_pt->boundary_element_pt(b,e);
         Face_index_at_boundary[b][e]=new_mesh_pt->face_index_at_boundary(b,e);
        }
       unsigned nnod=new_mesh_pt->nboundary_node(b);
       Boundary_node_pt[b].resize(nnod);
       for (unsigned j=0;j<nnod;j++)
        {
         Boundary_node_pt[b][j]=new_mesh_pt->boundary_node_pt(b,j);
        }
      }
     //Also copy over the new boundary and region information
     unsigned n_region = new_mesh_pt->nregion();
     //Only bother if we have regions
     if(n_region > 1)
      {
       //Deal with the region information first
       this->Region_element_pt.resize(n_region);
       this->Region_attribute.resize(n_region);
       for(unsigned r=0;r<n_region;r++)
        {
         this->Region_attribute[r] = new_mesh_pt->region_attribute(r);
         //Find the number of elements in the region
         unsigned n_region_element = new_mesh_pt->nregion_element(r);
         this->Region_element_pt[r].resize(n_region_element);
         for(unsigned e=0;e<n_region_element;e++)
          {
           this->Region_element_pt[r][e] = new_mesh_pt->region_element_pt(r,e);
          }
        }
       //Now the boundary region information
       this->Boundary_region_element_pt.resize(nbound);
       this->Face_index_region_at_boundary.resize(nbound);
       //Now loop over the boundaries
       for(unsigned b=0;b<nbound;++b)
        {
         //Loop over the regions
         for(unsigned r=0;r<n_region;++r)
          {
           unsigned n_boundary_el_in_region =
            new_mesh_pt->nboundary_element_in_region(b,r);
           if(n_boundary_el_in_region > 0)
            {
             //Allocate storage in the map
             this->Boundary_region_element_pt[b][r].
              resize(n_boundary_el_in_region);
             this->Face_index_region_at_boundary[b][r].
              resize(n_boundary_el_in_region);
             //Copy over the information
             for(unsigned e=0;e<n_boundary_el_in_region;++e)
              {
               this->Boundary_region_element_pt[b][r][e]
                = new_mesh_pt->boundary_element_in_region_pt(b,r,e);
               this->Face_index_region_at_boundary[b][r][e]
                = new_mesh_pt->face_index_at_boundary_in_region(b,r,e);
              }
            }
          }
        } //End of loop over boundaries
      } //End of case when more than one region
     //Snap the newly created nodes onto any geometric objects
     //this->snap_nodes_onto_geometric_objects();
     // Copy the IDs of the vertex nodes
     //this->Oomph_vertex_nodes_id=new_mesh_pt->oomph_vertex_nodes_id();
     // Copy TriangulateIO representation
     //TriangleHelper::clear_triangulateio(this->Triangulateio);
     //bool quiet=true;
     //this->Triangulateio=
     // TriangleHelper::deep_copy_of_triangulateio_representation(
     //  new_mesh_pt->triangulateio_representation(),quiet);
     this->set_deep_copy_tetgenio_pt(new_mesh_pt->tetgenio_pt());
      //this->Tetgenio_pt = new_mesh_pt->tetgenio_pt();
     // Flush the mesh
     new_mesh_pt->flush_element_and_node_storage();
     // Delete the mesh and the problem
     delete new_mesh_pt;
     delete project_problem_pt;
     // Solid mesh?
     if (solid_mesh_pt!=0)
      {
       // Warning
       std::stringstream error_message;
       error_message
        << "Lagrangian coordinates are currently not projected but are\n"
        << "are re-set during adaptation. This is not appropriate for\n"
        << "real solid mechanics problems!\n";
       OomphLibWarning(error_message.str(),
                       "RefineableTriangleMesh::adapt()",
                       OOMPH_EXCEPTION_LOCATION);
       // Reset Lagrangian coordinates
       dynamic_cast<SolidMesh*>(this)->set_lagrangian_nodal_coordinates();
      }
     double max_area;
     double min_area;
     this->max_and_min_element_size(max_area, min_area);
     oomph_info << "Max/min element size in adapted mesh: "
                << max_area  << " "
                << min_area << std::endl;
    }
   else
    {
     oomph_info << "Not enough benefit in adaptation.\n";
     Nrefined=0;
     Nunrefined=0;
    }
  }
References b, oomph::TetMeshBase::boundary_element_in_region_pt(), oomph::Mesh::boundary_element_pt(), oomph::Mesh::boundary_node_pt(), e(), oomph::Mesh::element_pt(), oomph::Mesh::face_index_at_boundary(), oomph::TetMeshBase::face_index_at_boundary_in_region(), oomph::Mesh::finite_element_pt(), oomph::Mesh::flush_element_and_node_storage(), j, max, oomph::Problem::mesh_pt(), n, oomph::Mesh::nboundary(), oomph::Mesh::nboundary_element(), oomph::TetMeshBase::nboundary_element_in_region(), oomph::Mesh::nboundary_node(), oomph::Mesh::nelement(), oomph::Mesh::nnode(), oomph::Mesh::node_pt(), oomph::TetMeshBase::nregion(), oomph::TetMeshBase::nregion_element(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::oomph_info, oomph::Mesh::output(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::project(), UniformPSDSelfTest::r, oomph::TetMeshBase::region_attribute(), oomph::TetMeshBase::region_element_pt(), resize(), oomph::Multi_domain_functions::setup_multi_domain_interaction(), oomph::FiniteElement::size(), and oomph::TetgenMesh< ELEMENT >::tetgenio_pt().
adapt() [2/2]
template<class ELEMENT > void oomph::RefineableTetgenMesh< ELEMENT >::adapt (const Vector< double > & elem_error) virtual
Adapt mesh, based on elemental error provided.
Implements oomph::RefineableMeshBase.
compute_volume_target()
template<class ELEMENT > double oomph::RefineableTetgenMesh< ELEMENT >::compute_volume_target (const Vector< double > & elem_error, Vector< double > & target_volume) inline
Build a new tetgenio object from previous TriangulateIO based on target area for each element Compute target volume based on the element's error and the error target; return max edge ratio
     {
      double max_edge_ratio=0.0;
      unsigned count_unrefined=0;
      unsigned count_refined=0;
      this->Nrefinement_overruled=0;
      unsigned nel=this->nelement();
      for (unsigned e=0;e<nel;e++)
       {
        // Get element
        FiniteElement* el_pt=this->finite_element_pt(e);
        // Calculate the volume of the element
        double volume=el_pt->size();
        //Find the vertex coordinates
        // (vertices are enumerated first)
        double vertex[4][3];
        for(unsigned n=0;n<4;++n)
         {
          for(unsigned i=0;i<3;++i)
           {
            vertex[n][i] = el_pt->node_pt(n)->x(i);
           }
         }
        //Compute the radius of the circumsphere of the tetrahedron
        //Algorithm stolen from tetgen for consistency
        DenseDoubleMatrix A(3);
        for(unsigned i=0;i<3;++i)
         {
          A(0,i) = vertex[1][i] - vertex[0][i];
          A(1,i) = vertex[2][i] - vertex[0][i];
          A(2,i) = vertex[3][i] - vertex[0][i];
         }
        Vector<double> rhs(3);
        // Compute the right hand side vector b (3x1).
        for(unsigned i=0;i<3;++i)
         {
          rhs[i] = 0.0;
          for(unsigned k=0;k<3;++k)
           {
            rhs[i] += A(i,k)*A(i,k);
           }
          rhs[i] *= 0.5;
         }
        //Solve the linear system, in which the rhs is over-written with
        //the solution
        A.solve(rhs);
        //Calculate the circum-radius
        double circum_radius =
         sqrt(rhs[0]*rhs[0] + rhs[1]*rhs[1] + rhs[2]*rhs[2]);
        //Now find the shortest edge length
        Vector<double> edge(3);
        double min_length = DBL_MAX;
        for(unsigned start=0;start<4;++start)
         {
          for(unsigned end=start+1;end<4;++end)
           {
            for(unsigned i=0;i<3;++i)
             {
              edge[i] = vertex[start][i] - vertex[end][i];
             }
            double length =
             sqrt(edge[0]*edge[0] + edge[1]*edge[1] + edge[2]*edge[2]);
            if(length < min_length) {min_length = length;}
           }
         }
        //Now calculate the minimum edge ratio for this element
        double local_max_edge_ratio = circum_radius/min_length;
        if(local_max_edge_ratio > max_edge_ratio)
         {
          max_edge_ratio = local_max_edge_ratio;
         }
        // Mimick refinement in tree-based procedure: Target volumes
        // for elements that exceed permitted error is 1/4 of their
        // current volume, corresponding to a uniform sub-division.
        if (elem_error[e] > this->max_permitted_error())
         {
          target_volume[e]=std::max(volume/4.0,Min_element_size);
          if (target_volume[e]!=Min_element_size)
           {
            count_refined++;
           }
          else
           {
            this->Nrefinement_overruled++;
           }
         }
        else if (elem_error[e] < this->min_permitted_error())
         {
          target_volume[e]=std::min(4.0*volume,Max_element_size);
          if (target_volume[e]!=Max_element_size)
           {
            count_unrefined++;
           }
         }
        else
         {
          // Leave it alone
          target_volume[e] = std::max(volume,Min_element_size);
         }
       } //End of loop over elements
      // Tell everybody
      this->Nrefined=count_refined;
      this->Nunrefined=count_unrefined;
      return max_edge_ratio;
    }
References e(), Eigen::placeholders::end, i, k, max, TestArguments::Max_element_size, min, TestArguments::Min_element_size, n, oomph::FiniteElement::node_pt(), oomph::FiniteElement::size(), sqrt(), oomph::CumulativeTimings::start(), and oomph::Node::x().
disable_projection()
template<class ELEMENT > void oomph::RefineableTetgenMesh< ELEMENT >::disable_projection () inline
Disable projection of old solution onto new mesh.
     {
       Projection_is_disabled = true;
     }
References oomph::RefineableTetgenMesh< ELEMENT >::Projection_is_disabled.
doc_adaptivity_targets()
template<class ELEMENT > void oomph::RefineableTetgenMesh< ELEMENT >::doc_adaptivity_targets (std::ostream & outfile) inline virtual
Doc the targets for mesh adaptation.
Reimplemented from oomph::RefineableMeshBase.
    {
     outfile << std::endl;
     outfile << "Targets for mesh adaptation: " << std::endl;
     outfile << "---------------------------- " << std::endl;
     outfile << "Target for max. error: " << Max_permitted_error << std::endl;
     outfile << "Target for min. error: " << Min_permitted_error << std::endl;
     outfile << "Target max edge ratio: "
             << Max_permitted_edge_ratio << std::endl;
     outfile << "Min. allowed element size: " << Min_element_size << std::endl;
     outfile << "Max. allowed element size: " << Max_element_size << std::endl;
     outfile << "Don't unrefine if less than " << Max_keep_unrefined
             << " elements need unrefinement." << std::endl;
     outfile << std::endl;
    }
References TestArguments::Max_element_size, TestArguments::Max_permitted_error, TestArguments::Min_element_size, and TestArguments::Min_permitted_error.
enable_projection()
template<class ELEMENT > void oomph::RefineableTetgenMesh< ELEMENT >::enable_projection () inline
Disable projection of old solution onto new mesh.
     {
       Projection_is_disabled = false;
     }
References oomph::RefineableTetgenMesh< ELEMENT >::Projection_is_disabled.
initialise_adaptation_data() [1/2]
template<class ELEMENT > void oomph::RefineableTetgenMesh< ELEMENT >::initialise_adaptation_data () inline
Helper function to initialise data associated with adaptation.
    {
     // Set max and min targets for adaptation
     this->Max_element_size=1.0;
     this->Min_element_size=0.001;
     this->Max_permitted_edge_ratio=2.0;
     // Initialise problem pointer
     this->Problem_pt=0;
    }
References TestArguments::Max_element_size, and TestArguments::Min_element_size.
Referenced by oomph::RefineableTetgenMesh< ELEMENT >::RefineableTetgenMesh().
initialise_adaptation_data() [2/2]
template<class ELEMENT > void oomph::RefineableTetgenMesh< ELEMENT >::initialise_adaptation_data () inline protected
Helper function to initialise data associated with adaptation.
By default we project solution onto new mesh during adaptation
     {
       // Set max and min targets for adaptation
       this->Max_element_size = 1.0;
       this->Min_element_size = 0.001;
       this->Max_permitted_edge_ratio = 2.0;
       Projection_is_disabled = false;
     }
References oomph::RefineableTetgenMesh< ELEMENT >::Max_element_size, oomph::RefineableTetgenMesh< ELEMENT >::Max_permitted_edge_ratio, oomph::RefineableTetgenMesh< ELEMENT >::Min_element_size, and oomph::RefineableTetgenMesh< ELEMENT >::Projection_is_disabled.
max_element_size()
template<class ELEMENT > double& oomph::RefineableTetgenMesh< ELEMENT >::max_element_size () inline
Max element size allowed during adaptation.
 {return Max_element_size;}
References TestArguments::Max_element_size.
max_permitted_edge_ratio()
template<class ELEMENT > double& oomph::RefineableTetgenMesh< ELEMENT >::max_permitted_edge_ratio () inline
Min angle before remesh gets triggered.
 {return Max_permitted_edge_ratio;}
min_element_size()
template<class ELEMENT > double& oomph::RefineableTetgenMesh< ELEMENT >::min_element_size () inline
Min element size allowed during adaptation.
 {return Min_element_size;}
References TestArguments::Min_element_size.
problem_pt()
template<class ELEMENT > Problem*& oomph::RefineableTetgenMesh< ELEMENT >::problem_pt () inline
Problem pointer (needed for multi-domain machinery during adaptation)
 {return Problem_pt;}
projection_is_disabled()
template<class ELEMENT > bool oomph::RefineableTetgenMesh< ELEMENT >::projection_is_disabled () inline
Is projection of old solution onto new mesh disabled?
     {
       return Projection_is_disabled;
     }
References oomph::RefineableTetgenMesh< ELEMENT >::Projection_is_disabled.
refine_uniformly() [1/2]
template<class ELEMENT > void oomph::RefineableTetgenMesh< ELEMENT >::refine_uniformly (DocInfo & doc_info) inline virtual
Refine mesh uniformly and doc process.
Implements oomph::RefineableMeshBase.
    {
     throw OomphLibError("refine_uniformly() not implemented yet",
                         OOMPH_CURRENT_FUNCTION,
                         OOMPH_EXCEPTION_LOCATION);
    }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
refine_uniformly() [2/2]
template<class ELEMENT > void oomph::RefineableTetgenMesh< ELEMENT >::refine_uniformly (DocInfo & doc_info) inline virtual
Refine mesh uniformly and doc process.
Implements oomph::RefineableMeshBase.
     {
       // hierher do it
       throw OomphLibError("refine_uniformly() not implemented yet",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
setup_boundary_coordinates_generic()
template<class ELEMENT > void oomph::RefineableTetgenMesh< ELEMENT >::setup_boundary_coordinates_generic (const unsigned & b, const bool & switch_normal, std::ofstream & outfile) inline
Overload the standard setup of boundary coordinates to use area coordinates for triangles
     {
      std::cout << "Calling this local version\n";
     }
snap_nodes_onto_boundary() [1/2]
template<class ELEMENT > void oomph::RefineableTetgenMesh< ELEMENT >::snap_nodes_onto_boundary (RefineableTetgenMesh< ELEMENT > *& new_mesh_pt, const unsigned & b) inline
Generate a new PSLG representation of the outer boundary.
Snap the boundary nodes onto any curvilinear boundaries.
Snap the boundary nodes onto any curvilinear boundaries
     {
      // Quick return
      if (!Boundary_coordinate_exists[b])
       {
        oomph_info << "Not snapping nodes on boundary " << b
                   << " because no boundary coordinate has been set up.\n";
        return;
       }
      //Firstly we set the boundary coordinates of the new nodes
      //In case the mapping between the geometric object's intrinsic coordiante
      //and the arc-length coordinate is nonlinear.
      //This is only an approximation,
      //but it will ensure that the nodes that were input to triangle will
      //retain exactly the same boundary coordinates and
      //then linear interpolation
      //is used between those values for any newly created nodes.
      // Create a face mesh adjacent to the fluid mesh's b-th boundary.
      // The face mesh consists of FaceElements that may also be
      // interpreted as GeomObjects
      Mesh* face_mesh_pt = new Mesh;
      this->template build_face_mesh
       <ELEMENT,FaceElementAsGeomObject>(b, face_mesh_pt);
      // Loop over these new face elements and tell them the boundary number
      // from the bulk fluid mesh -- this is required to they can
      // get access to the boundary coordinates!
      unsigned n_face_element = face_mesh_pt->nelement();
      for(unsigned e=0;e<n_face_element;e++)
       {
        //Cast the element pointer to the correct thing!
        FaceElementAsGeomObject<ELEMENT>* el_pt=
         dynamic_cast<FaceElementAsGeomObject<ELEMENT>*>
         (face_mesh_pt->element_pt(e));
        // Set bulk boundary number
        el_pt->set_boundary_number_in_bulk_mesh(b);
       }
      //Now make the mesh as geometric object
      MeshAsGeomObject* mesh_geom_obj_pt = new MeshAsGeomObject(face_mesh_pt);
      //Now assign the new nodes positions based on the old meshes
      //potentially curvilinear boundary (its geom object incarnation)
      Vector<double> new_x(3);
      Vector<double> b_coord(2);
      unsigned n_new_boundary_node = new_mesh_pt->nboundary_node(b);
      for(unsigned n=0;n<n_new_boundary_node;n++)
       {
        //Get the boundary coordinate of all new nodes
        Node* const nod_pt = new_mesh_pt->boundary_node_pt(b,n);
        nod_pt->get_coordinates_on_boundary(b,b_coord);
        //Let's find boundary coordinates of the new node
        mesh_geom_obj_pt->position(b_coord,new_x);
        //Now snap to the boundary
        for(unsigned i=0;i<3;i++)
         {
          nod_pt->x(i) = new_x[i];
         }
       }
      //Delete the allocated memory for the geometric object and face mesh
      delete mesh_geom_obj_pt;
      face_mesh_pt->flush_element_and_node_storage();
      delete face_mesh_pt;
      //Loop over the elements adjacent to the boundary
      unsigned n_element = new_mesh_pt->nboundary_element(b);
      if(n_element > 0)
       {
        //Make a dummy simplex element
        TElement<3,2> dummy_four_node_element;
        //Make a dummy quadratic element
        TElement<3,3> dummy_ten_node_element;
        Vector<double> s(3);
        Vector<double> x_new(3);
        for(unsigned n=0;n<4;n++) {dummy_four_node_element.construct_node(n);}
        for(unsigned n=0;n<10;n++) {dummy_ten_node_element.construct_node(n);}
        for(unsigned e=0;e<n_element;e++)
         {
          //Cache the element pointer
          ELEMENT* elem_pt = dynamic_cast<ELEMENT*>(
           new_mesh_pt->boundary_element_pt(b,e));
          //Find the number of nodes
          const unsigned n_node = elem_pt->nnode();
          //Only do something if not simplex element
          if(n_node > 4)
           {
            //Copy the nodes into the dummy
            for(unsigned n=0;n<4;n++)
             {
              for(unsigned i=0;i<3;i++)
               {
                dummy_four_node_element.node_pt(n)->x(i) =
                 elem_pt->node_pt(n)->x(i);
               }
             }
            //Now sort out the mid-side nodes
            for(unsigned n=4;n<10;n++)
             {
              //If it's not on a boundary then reset to be interpolated
              //from the simplex
              if(!elem_pt->node_pt(n)->is_on_boundary())
               {
                elem_pt->local_coordinate_of_node(n,s);
                dummy_four_node_element.interpolated_x(s,x_new);
                for(unsigned i=0;i<3;i++) {elem_pt->node_pt(n)->x(i) = x_new[i];}
               }
             }
           }
          //If we have more than 10 nodes interpolate from the quadratic shape
          if(n_node > 10)
           {
            //Copy the nodes into the dummy
            for(unsigned n=0;n<10;n++)
             {
              for(unsigned i=0;i<3;i++)
               {
                dummy_ten_node_element.node_pt(n)->x(i) =
                 elem_pt->node_pt(n)->x(i);
               }
             }
            //Now sort out the mid-face and central nodes
            for(unsigned n=10;n<n_node;n++)
             {
              //If it's not on a boundary then reset to be interpolated
              //from the simplex
              if(!elem_pt->node_pt(n)->is_on_boundary())
               {
                elem_pt->local_coordinate_of_node(n,s);
                dummy_ten_node_element.interpolated_x(s,x_new);
                for(unsigned i=0;i<3;i++) {elem_pt->node_pt(n)->x(i) = x_new[i];}
               }
             }
           }
         }
       } //End of fix up of elements
     }
References b, oomph::Mesh::boundary_element_pt(), oomph::Mesh::boundary_node_pt(), e(), oomph::Mesh::element_pt(), oomph::Mesh::flush_element_and_node_storage(), oomph::Node::get_coordinates_on_boundary(), i, n, oomph::Mesh::nboundary_element(), oomph::Mesh::nboundary_node(), oomph::Mesh::nelement(), oomph::oomph_info, oomph::MeshAsGeomObject::position(), s, oomph::FaceElement::set_boundary_number_in_bulk_mesh(), and oomph::Node::x().
snap_nodes_onto_boundary() [2/2]
template<class ELEMENT > void oomph::RefineableTetgenMesh< ELEMENT >::snap_nodes_onto_boundary (RefineableTetgenMesh< ELEMENT > *& new_mesh_pt, const unsigned & b) protected
Snap the boundary nodes onto any curvilinear boundaries.
surface_remesh_for_inner_hole_boundaries() [1/2]
template<class ELEMENT > void oomph::RefineableTetgenMesh< ELEMENT >::surface_remesh_for_inner_hole_boundaries inline virtual
Generate a new faceted representation of the inner hole boundaries
     {
      //Loop over the number of internal boundarys
      unsigned n_hole = this->Internal_surface_pt.size();
      for(unsigned ihole=0;ihole<n_hole;ihole++)
       {
        //Cache the pointer to the representation
        TetgenMeshClosedFacetedSurface* const faceted_surface_pt =
         dynamic_cast<TetgenMeshClosedFacetedSurface*>(this->Internal_surface_pt[ihole]);
        //Now can the surface update its own representation goes in here
        //If not we have to generate it from the new mesh
        {
         //Update the faceted surface associated with the ihole-th hole
         this->update_faceted_surface_using_face_mesh(faceted_surface_pt);
         //Then sort out the hole coordinates
        }
       }
     }
surface_remesh_for_inner_hole_boundaries() [2/2]
template<class ELEMENT > void oomph::RefineableTetgenMesh< ELEMENT >::surface_remesh_for_inner_hole_boundaries () protected
unrefine_uniformly() [1/2]
template<class ELEMENT > unsigned oomph::RefineableTetgenMesh< ELEMENT >::unrefine_uniformly () inline virtual
Unrefine mesh uniformly: Return 0 for success, 1 for failure (if unrefinement has reached the coarsest permitted level)
Implements oomph::RefineableMeshBase.
    {
     throw OomphLibError("unrefine_uniformly() not implemented yet",
                         OOMPH_CURRENT_FUNCTION,
                         OOMPH_EXCEPTION_LOCATION);
     // dummy return
     return 0;
    }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
unrefine_uniformly() [2/2]
template<class ELEMENT > unsigned oomph::RefineableTetgenMesh< ELEMENT >::unrefine_uniformly () inline virtual
Unrefine mesh uniformly: Return 0 for success, 1 for failure (if unrefinement has reached the coarsest permitted level)
Implements oomph::RefineableMeshBase.
     {
       // hierher do it
       throw OomphLibError("unrefine_uniformly() not implemented yet",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
       // dummy return
       return 0;
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
update_faceted_surface_using_face_mesh() [1/2]
template<class ELEMENT > void oomph::RefineableTetgenMesh< ELEMENT >::update_faceted_surface_using_face_mesh (TetMeshFacetedClosedSurface * faceted_surface_pt) inline
Helper function that updates the input faceted surface by using the flattened elements from FaceMesh(es) that are constructed for the boundaries associated with the segments of the polygon.
List of vertex nodes
     {
      //The easiest thing to do is simply to update the
      //positions of the key control nodes, leaving the connectivity alone,
      //but that doesn't allow for any surface remeshing
      std::list<Node*> new_vertex_nodes;
      //List of facets and boundary ids
      std::list<std::pair<Vector<unsigned>, unsigned>  > new_facet_list;
      //Loop over the number of old facets
      unsigned n_old_facet = faceted_surface_pt->nfacet();
      for(unsigned f=0;f<n_old_facet;f++)
       {
        //Get the boundary id of the facet. Need to subtract one,
        //which is confusing now I think about it.
        //ALH: Should fix this.
        unsigned bound = faceted_surface_pt->one_based_facet_boundary_id(f) -1;
        // Create a face mesh adjacent to the fluid mesh's bound-th boundary.
        // The face mesh consists of FaceElements that may also be
        // interpreted as GeomObjects
        Mesh* face_mesh_pt = new Mesh;
        this->template build_face_mesh
         <ELEMENT,FaceElementAsGeomObject>(bound, face_mesh_pt);
        // Loop over these new face elements and tell them the boundary number
        // from the bulk fluid mesh -- this is required to they can
        // get access to the boundary coordinates!
        unsigned n_face_element = face_mesh_pt->nelement();
        for(unsigned e=0;e<n_face_element;e++)
         {
          //Cast the element pointer to the correct thing!
          FaceElementAsGeomObject<ELEMENT>* el_pt=
           dynamic_cast<FaceElementAsGeomObject<ELEMENT>*>
           (face_mesh_pt->element_pt(e));
          // Set bulk boundary number
          el_pt->set_boundary_number_in_bulk_mesh(bound);
         }
        //In order to set up the new faceted representation
        //Need to know the positions of the corner nodes
        //and the connectivity
        //Storage for the connectivity information
        Vector<unsigned> new_local_facet(3);
        //Now we have the face mesh loop over the face elements and
        //print out the end points
        for(unsigned e=0;e<n_face_element;++e)
         {
          //Cache pointer to the element
          FiniteElement const *elem_pt = face_mesh_pt->finite_element_pt(e);
          //Just use the three primary (corner) nodes to define the facet
          unsigned n_vertex_node = 3;
          for(unsigned n=0;n<n_vertex_node;n++)
           {
            //Cache the pointer to the node
            Node* const nod_pt = elem_pt->node_pt(n);
            //If the vertex node is in the list return the number
            unsigned counter=0; bool found_it=false;
            for(std::list<Node*>::iterator it = new_vertex_nodes.begin();
                it!=new_vertex_nodes.end();++it,++counter)
             {
              //If we have found the node then store it
              if(*it==nod_pt)
               {
                new_local_facet[n] = counter;
                found_it=true;
                break;
               }
             }
            //If we haven't found it
            //then add the node to the list and fill in the counter
            if(!found_it)
             {
              new_vertex_nodes.push_back(nod_pt);
              //We know where it is
              new_local_facet[n] = counter;
             }
           }
          //Add the new facet connectivity to the list
          new_facet_list.push_back(std::make_pair(new_local_facet,bound+1));
         }
       } //End of loop over old facets
      //Probably want the surface mesh in a better data structure so
      //that we can perform refinement or coarsening on it
      //i.e. want neighbours, edge flips all that fun stuff
      //That will go here!
      //Now sort out the facet nodes
      unsigned n_facet_vertex = new_vertex_nodes.size();
      Vector<Vector<double> > facet_point(n_facet_vertex);
      unsigned count=0;
      for(std::list<Node*>::iterator it=new_vertex_nodes.begin();
          it!=new_vertex_nodes.end();++it)
       {
        facet_point[count].resize(3);
        for(unsigned i=0;i<3;i++)
         {
          facet_point[count][i] = (*it)->x(i);
         }
        ++count;
       }
      //And also the facets
      unsigned n_facet = new_facet_list.size();
      Vector<Vector<unsigned> > new_facet(n_facet);
      Vector<unsigned> new_facet_boundary_id(n_facet);
      count=0;
      for(std::list<std::pair<Vector<unsigned>, unsigned> >::iterator
           it=new_facet_list.begin();it!=new_facet_list.end();++it)
       {
        new_facet[count] = (*it).first;
        new_facet_boundary_id[count] = (*it).second;
        ++count;
       }
      for(unsigned f=0;f<n_facet;f++)
       {
        for(unsigned i=0;i<3;i++)
         {
          oomph_info << new_facet[f][i] << " " ;
         }
        oomph_info << " : ";
        oomph_info << new_facet_boundary_id[f] << "\n";
       }
      //Now just create the new boundary
      delete faceted_surface_pt;
      faceted_surface_pt = new TetMeshFacetedClosedSurface(
       facet_point,new_facet,new_facet_boundary_id);
      //Take average to get a new hole position (Won't always work)
      Vector<double> inner_point(3,0.0);
      for(unsigned n=0;n<n_facet_vertex;n++)
       {
        for(unsigned i=0;i<3;i++)
         {
          inner_point[i] += facet_point[n][i];
         }
       }
      for(unsigned i=0;i<3;i++) {inner_point[i] /= n_facet_vertex;}
      //Now set the hole if required
      faceted_surface_pt->set_hole(inner_point);
     }
References e(), oomph::Mesh::element_pt(), f(), oomph::Mesh::finite_element_pt(), i, n, oomph::Mesh::nelement(), oomph::TetMeshFacetedSurface::nfacet(), oomph::FiniteElement::node_pt(), oomph::TetMeshFacetedSurface::one_based_facet_boundary_id(), oomph::oomph_info, and oomph::FaceElement::set_boundary_number_in_bulk_mesh().
update_faceted_surface_using_face_mesh() [2/2]
template<class ELEMENT > void oomph::RefineableTetgenMesh< ELEMENT >::update_faceted_surface_using_face_mesh (TetMeshFacetedSurface *& faceted_surface_pt) protected
Helper function that updates the input faceted surface by using the flattened elements from FaceMesh(es) that are constructed for the boundaries associated with the segments of the polygon.
List of vertex nodes
   {
     // The easiest thing to do is simply to update the
     // positions of the key control nodes, leaving the connectivity alone,
     // but that doesn't allow for any surface remeshing
     std::list<Node*> new_vertex_nodes;
     // List of facets and boundary ids
     std::list<std::pair<Vector<unsigned>, unsigned>> new_facet_list;
     // Loop over the number of old facets
     unsigned n_old_facet = faceted_surface_pt->nfacet();
     for (unsigned f = 0; f < n_old_facet; f++)
     {
       // Get the boundary id of the facet. Need to subtract one,
       // which is confusing now I think about it.
       // ALH: Should fix this.
       unsigned bound = faceted_surface_pt->one_based_facet_boundary_id(f) - 1;
       // Create a face mesh adjacent to the fluid mesh's bound-th boundary.
       // The face mesh consists of FaceElements that may also be
       // interpreted as GeomObjects
       Mesh* face_mesh_pt = new Mesh;
       this->template build_face_mesh<ELEMENT, FaceElementAsGeomObject>(
         bound, face_mesh_pt);
       // Loop over these new face elements and tell them the boundary number
       // from the bulk fluid mesh -- this is required to they can
       // get access to the boundary coordinates!
       unsigned n_face_element = face_mesh_pt->nelement();
       for (unsigned e = 0; e < n_face_element; e++)
       {
         // Cast the element pointer to the correct thing!
         FaceElementAsGeomObject<ELEMENT>* el_pt =
           dynamic_cast<FaceElementAsGeomObject<ELEMENT>*>(
             face_mesh_pt->element_pt(e));
         // Set bulk boundary number
         el_pt->set_boundary_number_in_bulk_mesh(bound);
       }
       // In order to set up the new faceted representation
       // Need to know the positions of the corner nodes
       // and the connectivity
       // Storage for the connectivity information
       Vector<unsigned> new_local_facet(3);
       // Now we have the face mesh loop over the face elements and
       // print out the end points
       for (unsigned e = 0; e < n_face_element; ++e)
       {
         // Cache pointer to the element
         FiniteElement const* elem_pt = face_mesh_pt->finite_element_pt(e);
         // Just use the three primary (corner) nodes to define the facet
         unsigned n_vertex_node = 3;
         for (unsigned n = 0; n < n_vertex_node; n++)
         {
           // Cache the pointer to the node
           Node* const nod_pt = elem_pt->node_pt(n);
           // If the vertex node is in the list return the number
           unsigned counter = 0;
           bool found_it = false;
           for (std::list<Node*>::iterator it = new_vertex_nodes.begin();
                it != new_vertex_nodes.end();
                ++it, ++counter)
           {
             // If we have found the node then store it
             if (*it == nod_pt)
             {
               new_local_facet[n] = counter;
               found_it = true;
               break;
             }
           }
           // If we haven't found it
           // then add the node to the list and fill in the counter
           if (!found_it)
           {
             new_vertex_nodes.push_back(nod_pt);
             // We know where it is
             new_local_facet[n] = counter;
           }
         }
         // Add the new facet connectivity to the list
         new_facet_list.push_back(std::make_pair(new_local_facet, bound + 1));
       }
     } // End of loop over old facets
     // Probably want the surface mesh in a better data structure so
     // that we can perform refinement or coarsening on it
     // i.e. want neighbours, edge flips all that fun stuff
     // That will go here!
     // Now we need to put the information into the appropriate data structures
     // for the Surface
     // Now sort out the facet nodes
     unsigned n_facet_vertex = new_vertex_nodes.size();
     // Vector<Vector<double> > facet_point(n_facet_vertex);
     Vector<Node*> facet_nodes_pt(n_facet_vertex);
     unsigned count = 0;
     for (std::list<Node*>::iterator it = new_vertex_nodes.begin();
          it != new_vertex_nodes.end();
          ++it)
     {
       facet_nodes_pt[count] = *it;
       // facet_point[count].resize(3);
       //   for(unsigned i=0;i<3;i++)
       //    {
       //     facet_point[count][i] = (*it)->x(i);
       //    }
       ++count;
     }
     // And also the facets
     unsigned n_facet = new_facet_list.size();
     Vector<Vector<unsigned>> new_facet(n_facet);
     Vector<unsigned> new_facet_boundary_id(n_facet);
     count = 0;
     for (std::list<std::pair<Vector<unsigned>, unsigned>>::iterator it =
            new_facet_list.begin();
          it != new_facet_list.end();
          ++it)
     {
       new_facet[count] = (*it).first;
       new_facet_boundary_id[count] = (*it).second;
       ++count;
     }
     for (unsigned f = 0; f < n_facet; f++)
     {
       for (unsigned i = 0; i < 3; i++)
       {
         oomph_info << new_facet[f][i] << " ";
       }
       oomph_info << " : ";
       oomph_info << new_facet_boundary_id[f] << "\n";
     }
     // Now just create the new boundary
     delete faceted_surface_pt;
     faceted_surface_pt = new TetMeshFacetedClosedSurfaceForRemesh(
       facet_nodes_pt, new_facet, new_facet_boundary_id);
     // Also need to setup the reverse look-up scheme again
     this->setup_reverse_lookup_schemes_for_faceted_surface(faceted_surface_pt);
     // Take average to get a new hole position (Won't always work)
     Vector<double> inner_point(3, 0.0);
     for (unsigned n = 0; n < n_facet_vertex; n++)
     {
       for (unsigned i = 0; i < 3; i++)
       {
         inner_point[i] += facet_nodes_pt[n]->x(i);
       }
     }
     for (unsigned i = 0; i < 3; i++)
     {
       inner_point[i] /= n_facet_vertex;
     }
     // Now set the hole if required
     dynamic_cast<TetMeshFacetedClosedSurface*>(faceted_surface_pt)
       ->set_hole_for_tetgen(inner_point);
   }
References e(), oomph::Mesh::element_pt(), f(), oomph::Mesh::finite_element_pt(), i, n, oomph::Mesh::nelement(), oomph::TetMeshFacetedSurface::nfacet(), oomph::FiniteElement::node_pt(), oomph::TetMeshFacetedSurface::one_based_facet_boundary_id(), oomph::oomph_info, and oomph::FaceElement::set_boundary_number_in_bulk_mesh().
Member Data Documentation
Corner_elements_must_be_split
template<class ELEMENT > bool oomph::RefineableTetgenMesh< ELEMENT >::Corner_elements_must_be_split protected
Corner elements which have all of their nodes on the outer boundary are to be split into elements which have some non-boundary nodes
Max_element_size
template<class ELEMENT > double oomph::RefineableTetgenMesh< ELEMENT >::Max_element_size
Max permitted element size.
Referenced by oomph::RefineableTetgenMesh< ELEMENT >::initialise_adaptation_data().
Max_permitted_edge_ratio
template<class ELEMENT > double oomph::RefineableTetgenMesh< ELEMENT >::Max_permitted_edge_ratio
Max edge ratio before remesh gets triggered.
Referenced by oomph::RefineableTetgenMesh< ELEMENT >::initialise_adaptation_data().
Min_element_size
template<class ELEMENT > double oomph::RefineableTetgenMesh< ELEMENT >::Min_element_size
Min permitted element size.
Referenced by oomph::RefineableTetgenMesh< ELEMENT >::initialise_adaptation_data().
Problem_pt
template<class ELEMENT > Problem* oomph::RefineableTetgenMesh< ELEMENT >::Problem_pt
Problem pointer (needed for multi-domain machinery during adaptation
Projection_is_disabled
template<class ELEMENT > bool oomph::RefineableTetgenMesh< ELEMENT >::Projection_is_disabled protected
Disable projection of solution onto new mesh during adaptation.
Referenced by oomph::RefineableTetgenMesh< ELEMENT >::disable_projection(), oomph::RefineableTetgenMesh< ELEMENT >::enable_projection(), oomph::RefineableTetgenMesh< ELEMENT >::initialise_adaptation_data(), and oomph::RefineableTetgenMesh< ELEMENT >::projection_is_disabled().
The documentation for this class was generated from the following files:
uns_adapt_3d_fs.cc
refineable_tetgen_mesh.template.h
refineable_tetgen_mesh.template.cc