MercuryDPM: oomph::TemplateFreeUnsteadyHeatBaseFaceElement Class Reference
oomph::TemplateFreeUnsteadyHeatBaseFaceElement Class Reference
#include <heat_transfer_and_melt_elements.h>
Public Types
typedef void(* UnsteadyHeatPrescribedFluxFctPt) (const double &time, const Vector< double > &x, const Vector< double > &n, const double &u, double &flux)
Public Member Functions
TemplateFreeUnsteadyHeatBaseFaceElement ()
Constructor.
virtual ~TemplateFreeUnsteadyHeatBaseFaceElement ()
Destrutor.
UnsteadyHeatPrescribedFluxFctPt & flux_fct_pt ()
Access function for the prescribed-flux function pointer.
Protected Member Functions
virtual void get_flux (const unsigned &ipt, const double &time, const Vector< double > &x, const Vector< double > &n, const double &u, double &flux)
Protected Attributes
unsigned U_index_ust_heat
Index at which temperature is stored.
unsigned Dim
The spatial dimension of the problem.
UnsteadyHeatPrescribedFluxFctPt Flux_fct_pt
Function pointer to the (global) prescribed-flux function.
Detailed Description
////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////// Template free base class for face elements that involve all kinds of heat transfer operation. Used to store spatial dim of problem and the index at which the temperature is stored in the bulk element
Member Typedef Documentation
UnsteadyHeatPrescribedFluxFctPt
typedef void(* oomph::TemplateFreeUnsteadyHeatBaseFaceElement::UnsteadyHeatPrescribedFluxFctPt) (const double &time, const Vector< double > &x, const Vector< double > &n, const double &u, double &flux)
Function pointer to the prescribed-flux function. Flux is allowed to depend on the spatial position, x, the outer unit normal, n, and the continuous time. We also allow a dependendence on actual local "temperature", u.
Constructor & Destructor Documentation
TemplateFreeUnsteadyHeatBaseFaceElement()
oomph::TemplateFreeUnsteadyHeatBaseFaceElement::TemplateFreeUnsteadyHeatBaseFaceElement () inline
Constructor.
                                              : U_index_ust_heat(0),
    Dim(0), Flux_fct_pt(0)
    {}
~TemplateFreeUnsteadyHeatBaseFaceElement()
virtual oomph::TemplateFreeUnsteadyHeatBaseFaceElement::~TemplateFreeUnsteadyHeatBaseFaceElement () inline virtual
Destrutor.
 {}
Member Function Documentation
flux_fct_pt()
UnsteadyHeatPrescribedFluxFctPt& oomph::TemplateFreeUnsteadyHeatBaseFaceElement::flux_fct_pt () inline
Access function for the prescribed-flux function pointer.
 {return Flux_fct_pt;}
References Flux_fct_pt.
Referenced by MeltContactProblem< ELEMENT >::complete_problem_setup(), and UnsteadyHeatMeltProblem< ELEMENT >::complete_problem_setup().
get_flux()
virtual void oomph::TemplateFreeUnsteadyHeatBaseFaceElement::get_flux (const unsigned & ipt, const double & time, const Vector< double > & x, const Vector< double > & n, const double & u, double & flux) inline protected virtual
Function to calculate the prescribed flux at a given spatial position, x, the outer unit normal, n, and the continuous time. We also allow an explicit dependendence on the integration point, ipt, and the actual local "temperature", u, in anticipation of Stefan Boltzmann radiation. Virtual so it can be overloaded. Note that the potential dependence on u makes the problem potentially nonlinear – Jacobian is currently worked out by finite differencing.
Reimplemented in oomph::StefanBoltzmannUnsteadyHeatFluxElement< ELEMENT >.
  {
   //If the function pointer is zero return zero
   if(Flux_fct_pt == 0)
    {
     flux=0.0;
    }
   //Otherwise call the function
   else
    {
     (*Flux_fct_pt)(time,x,n,u,flux);
    }
  }
References ProblemParameters::flux(), Flux_fct_pt, n, and plotDoE::x.
Referenced by oomph::UnsteadyHeatBaseFaceElement< ELEMENT >::output(), and oomph::SurfaceMeltElement< ELEMENT >::output_melt().
Member Data Documentation
Dim
unsigned oomph::TemplateFreeUnsteadyHeatBaseFaceElement::Dim protected
The spatial dimension of the problem.
Referenced by oomph::StefanBoltzmannUnsteadyHeatFluxElement< ELEMENT >::StefanBoltzmannUnsteadyHeatFluxElement(), oomph::SurfaceMeltElement< ELEMENT >::SurfaceMeltElement(), and oomph::UnsteadyHeatBaseFaceElement< ELEMENT >::UnsteadyHeatBaseFaceElement().
Flux_fct_pt
UnsteadyHeatPrescribedFluxFctPt oomph::TemplateFreeUnsteadyHeatBaseFaceElement::Flux_fct_pt protected
Function pointer to the (global) prescribed-flux function.
Referenced by flux_fct_pt(), get_flux(), and oomph::StefanBoltzmannUnsteadyHeatFluxElement< ELEMENT >::get_flux().
U_index_ust_heat
unsigned oomph::TemplateFreeUnsteadyHeatBaseFaceElement::U_index_ust_heat protected
Index at which temperature is stored.
Referenced by oomph::StefanBoltzmannRadiationBase::contribution_to_stefan_boltzmann_radiation(), oomph::UnsteadyHeatBaseFaceElement< ELEMENT >::interpolated_u(), and oomph::UnsteadyHeatBaseFaceElement< ELEMENT >::UnsteadyHeatBaseFaceElement().
The documentation for this class was generated from the following file:
heat_transfer_and_melt_elements.h