MercuryDPM: oomph::KirchhoffLoveShellEquations Class Reference
oomph::KirchhoffLoveShellEquations Class Reference
#include <shell_elements.h>
Public Member Functions
KirchhoffLoveShellEquations ()
Constructor: Initialise physical parameter values to defaults.
virtual void load_vector (const unsigned &intpt, const Vector< double > &xi, const Vector< double > &x, const Vector< double > &N, Vector< double > &load)
void set_prestress_pt (const unsigned &i, const unsigned &j, double *value_pt)
double prestress (const unsigned &i, const unsigned &j)
void disable_membrane_terms ()
Set to disable the calculation of membrane terms.
void enable_membrane_terms ()
Set to renable the calculation of membrane terms (default)
const double & nu () const
Return the Poisson's ratio.
const double & h () const
Return the wall thickness to undeformed radius ratio.
const double & lambda_sq () const
Return the timescale ratio (non-dimensional density)
double *& nu_pt ()
Return a pointer to the Poisson ratio.
double *& h_pt ()
Return a pointer to the non-dim wall thickness.
double *& lambda_sq_pt ()
Return a pointer to timescale ratio (nondim density)
GeomObject *& undeformed_midplane_pt ()
void get_normal (const Vector< double > &s, Vector< double > &N)
Get normal vector.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Overload the standard fill in residuals contribution.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Return the jacobian is calculated by finite differences by default,.
void get_energy (double &pot_en, double &kin_en)
Get potential (strain) and kinetic energy of the element.
std::pair< double, double > get_strain_and_bend (const Vector< double > &s, DenseDoubleMatrix &strain, DenseDoubleMatrix &bend)
Get strain and bending tensors.
double load_rate_of_work ()
void output (std::ostream &outfile)
Generic FiniteElement output function.
void output (std::ostream &outfile, const unsigned &n_plot)
Generic FiniteElement output function.
void output (FILE *file_pt)
Generic FiniteElement output function.
void output (FILE *file_pt, const unsigned &n_plot)
Generic FiniteElement output function.
Public Member Functions inherited from oomph::SolidFiniteElement
void set_lagrangian_dimension (const unsigned &lagrangian_dimension)
virtual bool has_internal_solid_data ()
SolidFiniteElement ()
Constructor: Set defaults.
virtual ~SolidFiniteElement ()
Destructor to clean up any allocated memory.
SolidFiniteElement (const SolidFiniteElement &)=delete
Broken copy constructor.
unsigned ngeom_data () const
Broken assignment operator.
Data * geom_data_pt (const unsigned &j)
void identify_geometric_data (std::set< Data * > &geometric_data_pt)
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_x_and_xi (const Vector< double > &s, Vector< double > &x_fe, Vector< double > &x, Vector< double > &xi_fe, Vector< double > &xi) const
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt, MacroElement *undeformed_macro_elem_pt)
void set_undeformed_macro_elem_pt (MacroElement *undeformed_macro_elem_pt)
MacroElement * undeformed_macro_elem_pt ()
Access function to pointer to "undeformed" macro element.
double dshape_lagrangian (const Vector< double > &s, Shape &psi, DShape &dpsidxi) const
virtual double dshape_lagrangian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidxi) const
double d2shape_lagrangian (const Vector< double > &s, Shape &psi, DShape &dpsidxi, DShape &d2psidxi) const
virtual double d2shape_lagrangian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidxi, DShape &d2psidxi) const
unsigned lagrangian_dimension () const
unsigned nnodal_lagrangian_type () const
Node * construct_node (const unsigned &n)
Construct the local node n and return a pointer to it.
Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
Node * construct_boundary_node (const unsigned &n)
Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
double raw_lagrangian_position (const unsigned &n, const unsigned &i) const
double raw_lagrangian_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double lagrangian_position (const unsigned &n, const unsigned &i) const
Return i-th Lagrangian coordinate at local node n.
double lagrangian_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
virtual double interpolated_xi (const Vector< double > &s, const unsigned &i) const
virtual void interpolated_xi (const Vector< double > &s, Vector< double > &xi) const
virtual void interpolated_dxids (const Vector< double > &s, DenseMatrix< double > &dxids) const
virtual void J_lagrangian (const Vector< double > &s) const
virtual double J_lagrangian_at_knot (const unsigned &ipt) const
SolidInitialCondition *& solid_ic_pt ()
Pointer to object that describes the initial condition.
void enable_solve_for_consistent_newmark_accel ()
void disable_solve_for_consistent_newmark_accel ()
Set to reset the problem being solved to be the standard problem.
MultiplierFctPt & multiplier_fct_pt ()
MultiplierFctPt multiplier_fct_pt () const
virtual void get_residuals_for_solid_ic (Vector< double > &residuals)
void fill_in_residuals_for_solid_ic (Vector< double > &residuals)
void fill_in_jacobian_for_solid_ic (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_for_newmark_accel (DenseMatrix< double > &jacobian)
void compute_norm (double &el_norm)
int position_local_eqn (const unsigned &n, const unsigned &k, const unsigned &j) const
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
virtual void disable_ALE ()
virtual void enable_ALE ()
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual unsigned nvertex_node () const
virtual Node * vertex_node_pt (const unsigned &j) const
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output an exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output a time-dependent exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Attributes
void(*&)(const Vector< double > &xi, const Vector< double > &x, const Vector< double > &N, Vector< double > &load) load_vector_fct_pt ()
Access to the load vector function pointer.
Protected Member Functions
double calculate_contravariant (double A[2][2], double Aup[2][2])
Invert a DIM by DIM matrix.
void fill_in_contribution_to_residuals_shell (Vector< double > &residuals)
Return the residuals for the equations of KL shell theory.
virtual void load_vector_for_rate_of_work_computation (const unsigned &intpt, const Vector< double > &xi, const Vector< double > &x, const Vector< double > &N, Vector< double > &load)
Protected Member Functions inherited from oomph::SolidFiniteElement
void fill_in_generic_jacobian_for_solid_ic (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
void set_nnodal_lagrangian_type (const unsigned &nlagrangian_type)
virtual double local_to_lagrangian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_lagrangian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_lagrangian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void assign_solid_local_eqn_numbers (const bool &store_local_dof)
Assign local equation numbers for the solid equations in the element.
void describe_solid_local_dofs (std::ostream &out, const std::string &current_string) const
Classifies dofs locally for solid specific aspects.
virtual void fill_in_jacobian_from_solid_position_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_solid_position_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_solid_position_fd ()
virtual void reset_after_solid_position_fd ()
virtual void update_in_solid_position_fd (const unsigned &i)
virtual void reset_in_solid_position_fd (const unsigned &i)
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Static Protected Member Functions
static void Zero_traction_fct (const Vector< double > &xi, const Vector< double > &x, const Vector< double > &N, Vector< double > &load)
Default load function (zero traction)
Protected Attributes
void(* Load_vector_fct_pt)(const Vector< double > &xi, const Vector< double > &x, const Vector< double > &N, Vector< double > &load)
GeomObject * Undeformed_midplane_pt
Protected Attributes inherited from oomph::SolidFiniteElement
MacroElement * Undeformed_macro_elem_pt
Pointer to the element's "undeformed" macro element (NULL by default)
SolidInitialCondition * Solid_ic_pt
Pointer to object that specifies the initial condition.
bool Solve_for_consistent_newmark_accel_flag
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Private Attributes
bool Ignore_membrane_terms
Boolean flag to ignore membrane terms.
double * Nu_pt
Pointer to Poisson's ratio.
double * H_pt
Pointer to dimensionless wall thickness.
double * Lambda_sq_pt
Pointer to timescale ratio (non-dimensional density)
DenseMatrix< double * > Prestress_pt
Static Private Attributes
static double Default_nu_value = 0.49
Static default value for the Poisson's ratio.
static double Default_lambda_sq_value = 1.0
Static default value for the timescale ratio (1.0 for natural scaling)
static double Default_h_value = 0.05
Static default value for the thickness ratio.
static double Zero_prestress = 0.0
Static default for prestress (set to zero)
Additional Inherited Members
Public Types inherited from oomph::SolidFiniteElement
typedef double(* MultiplierFctPt) (const Vector< double > &xi)
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
A class for elements that solves the equations of Kirchhoff Love shell thin-shell theory
Constructor & Destructor Documentation
KirchhoffLoveShellEquations()
oomph::KirchhoffLoveShellEquations::KirchhoffLoveShellEquations () inline
Constructor: Initialise physical parameter values to defaults.
                                   : Undeformed_midplane_pt(0)
     {
       // Set the default values of physical parameters
       Nu_pt = &Default_nu_value;
       Lambda_sq_pt = &Default_lambda_sq_value;
       H_pt = &Default_h_value;
       // Don't ignore membrane terms
       Ignore_membrane_terms = false;
       // Default load is zero traction
       Load_vector_fct_pt = &Zero_traction_fct;
       // Default prestress is zero
       Prestress_pt.resize(2, 2);
       Prestress_pt(0, 0) = &Zero_prestress;
       Prestress_pt(1, 0) = &Zero_prestress;
       Prestress_pt(0, 1) = &Zero_prestress;
       Prestress_pt(1, 1) = &Zero_prestress;
     }
References Default_h_value, Default_lambda_sq_value, Default_nu_value, H_pt, Ignore_membrane_terms, Lambda_sq_pt, Load_vector_fct_pt, Nu_pt, Prestress_pt, oomph::DenseMatrix< T >::resize(), Zero_prestress, and Zero_traction_fct().
Member Function Documentation
calculate_contravariant()
double oomph::KirchhoffLoveShellEquations::calculate_contravariant (double A[2][2], double Aup[2][2]) inline protected
Invert a DIM by DIM matrix.
Matrix inversion for 2 dimensions.
   {
     // Calculate determinant
     double det = A[0][0] * A[1][1] - A[0][1] * A[1][0];
     // Calculate entries of the inverse
     Aup[0][0] = A[1][1] / det;
     Aup[0][1] = -A[0][1] / det;
     Aup[1][0] = -A[1][0] / det;
     Aup[1][1] = A[0][0] / det;
     // Return determinant
     return (det);
   }
Referenced by fill_in_contribution_to_residuals_shell(), get_energy(), and get_strain_and_bend().
disable_membrane_terms()
void oomph::KirchhoffLoveShellEquations::disable_membrane_terms () inline
Set to disable the calculation of membrane terms.
     {
       Ignore_membrane_terms = true;
     }
References Ignore_membrane_terms.
enable_membrane_terms()
void oomph::KirchhoffLoveShellEquations::enable_membrane_terms () inline
Set to renable the calculation of membrane terms (default)
     {
       Ignore_membrane_terms = false;
     }
References Ignore_membrane_terms.
fill_in_contribution_to_jacobian()
void oomph::KirchhoffLoveShellEquations::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) virtual
Return the jacobian is calculated by finite differences by default,.
Reimplemented from oomph::SolidFiniteElement.
Reimplemented in oomph::FSIDiagHermiteShellElement.
   {
     // Call the element's residuals vector
     fill_in_contribution_to_residuals_shell(residuals);
     // Solve for the consistent acceleration in Newmark scheme?
     if (Solve_for_consistent_newmark_accel_flag)
     {
       fill_in_jacobian_for_newmark_accel(jacobian);
       return;
     }
     // Allocate storage for the full residuals of the element
     unsigned n_dof = ndof();
     Vector<double> full_residuals(n_dof);
     // Call the full residuals
     get_residuals(full_residuals);
     // Get the solid entries in the jacobian using finite differences
     SolidFiniteElement::fill_in_jacobian_from_solid_position_by_fd(
       full_residuals, jacobian);
     // Get the entries from the external data, usually load terms
     SolidFiniteElement::fill_in_jacobian_from_external_by_fd(full_residuals,
                                                              jacobian);
   }
References fill_in_contribution_to_residuals_shell(), oomph::SolidFiniteElement::fill_in_jacobian_for_newmark_accel(), oomph::GeneralisedElement::fill_in_jacobian_from_external_by_fd(), oomph::SolidFiniteElement::fill_in_jacobian_from_solid_position_by_fd(), oomph::GeneralisedElement::get_residuals(), oomph::GeneralisedElement::ndof(), and oomph::SolidFiniteElement::Solve_for_consistent_newmark_accel_flag.
Referenced by oomph::FSIDiagHermiteShellElement::fill_in_contribution_to_jacobian().
fill_in_contribution_to_residuals()
void oomph::KirchhoffLoveShellEquations::fill_in_contribution_to_residuals (Vector< double > & residuals) inline virtual
Overload the standard fill in residuals contribution.
Reimplemented from oomph::GeneralisedElement.
     {
       // Simply call the shell residuals
       fill_in_contribution_to_residuals_shell(residuals);
     }
References fill_in_contribution_to_residuals_shell().
fill_in_contribution_to_residuals_shell()
void oomph::KirchhoffLoveShellEquations::fill_in_contribution_to_residuals_shell (Vector< double > & residuals) protected
Return the residuals for the equations of KL shell theory.
Helper function to Return the residuals for the equations of KL shell theory. This is used to prevent a call of fill_in_contribution_to_residuals in the function fill_in_contribution_to_jacobian that can lead to virtual inheritance woes if this element is ever used as part of a multi-physics element.
   {
     // Set the dimension of the coordinates
     const unsigned n_dim = 3;
     // Set the number of lagrangian coordinates
     const unsigned n_lagrangian = 2;
     // Find out how many nodes there are
     const unsigned n_node = nnode();
     // Find out how many positional dofs there are
     const unsigned n_position_type = nnodal_position_type();
     // Set up memory for the shape functions
     Shape psi(n_node, n_position_type);
     DShape dpsidxi(n_node, n_position_type, n_lagrangian);
     // Could/Should we make this more general?
     DShape d2psidxi(n_node, n_position_type, 3);
     // Set the value of n_intpt
     const unsigned n_intpt = integral_pt()->nweight();
     // Get Physical Variables from Element
     // External pressure, Poisson ratio , and non-dim thickness h
     const double nu_cached = nu();
     const double h_cached = h();
     const double lambda_sq_cached = lambda_sq();
     // Integers used to store the local equation numbers
     int local_eqn = 0;
     const double bending_scale = (1.0 / 12.0) * h_cached * h_cached;
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Call the derivatives of the shape functions:
       // d2psidxi(i,0) = \f$ \partial^2 \psi_j / \partial^2 \xi_0^2 \f$
       // d2psidxi(i,1) = \f$ \partial^2 \psi_j / \partial^2 \xi_1^2 \f$
       // d2psidxi(i,2) = \f$ \partial^2 \psi_j/\partial \xi_0 \partial \xi_1 \f$
       double J = d2shape_lagrangian_at_knot(ipt, psi, dpsidxi, d2psidxi);
       // Premultiply the weights and the Jacobian
       double W = w * J;
       // Calculate local values of lagrangian position and
       // the derivative of global position wrt lagrangian coordinates
       Vector<double> interpolated_xi(2, 0.0), interpolated_x(3, 0.0);
       Vector<double> accel(3, 0.0);
       DenseMatrix<double> interpolated_A(2, 3);
       DenseMatrix<double> interpolated_dAdxi(3);
       // Initialise to zero
       for (unsigned i = 0; i < n_dim; i++)
       {
         for (unsigned j = 0; j < n_lagrangian; j++)
         {
           interpolated_A(j, i) = 0.0;
         }
         for (unsigned j = 0; j < 3; j++)
         {
           interpolated_dAdxi(i, j) = 0.0;
         }
       }
       // Calculate displacements and derivatives
       for (unsigned l = 0; l < n_node; l++)
       {
         // Loop over positional dofs
         for (unsigned k = 0; k < n_position_type; k++)
         {
           // Loop over lagrangian coordinate directions
           for (unsigned i = 0; i < n_lagrangian; i++)
           {
             interpolated_xi[i] +=
               raw_lagrangian_position_gen(l, k, i) * psi(l, k);
           }
           // Loop over displacement components (deformed position)
           for (unsigned i = 0; i < n_dim; i++)
           {
             double x_value = raw_nodal_position_gen(l, k, i);
             // Calculate interpolated (deformed) position
             interpolated_x[i] += x_value * psi(l, k);
             // Calculate the acceleration
             accel[i] += raw_dnodal_position_gen_dt(2, l, k, i) * psi(l, k);
             // Loop over derivative directions
             for (unsigned j = 0; j < n_lagrangian; j++)
             {
               interpolated_A(j, i) += x_value * dpsidxi(l, k, j);
             }
             // Loop over the second derivative directions
             for (unsigned j = 0; j < 3; j++)
             {
               interpolated_dAdxi(j, i) += x_value * d2psidxi(l, k, j);
             }
           }
         }
       }
       // Get the values of the undeformed parameters
       Vector<double> interpolated_R(3);
       DenseMatrix<double> interpolated_a(2, 3);
       RankThreeTensor<double> dadxi(2, 2, 3);
       // Read out the undeformed position from the geometric object
       Undeformed_midplane_pt->d2position(
         interpolated_xi, interpolated_R, interpolated_a, dadxi);
       // Copy the values of the second derivatives into a slightly
       // different data structure, where the mixed derivatives [0][1] and [1][0]
       // are given by the single index [2]
       DenseMatrix<double> interpolated_dadxi(3);
       for (unsigned i = 0; i < 3; i++)
       {
         interpolated_dadxi(0, i) = dadxi(0, 0, i);
         interpolated_dadxi(1, i) = dadxi(1, 1, i);
         interpolated_dadxi(2, i) = dadxi(0, 1, i);
       }
       // Declare and calculate the undeformed and deformed metric tensor,
       // the strain tensor
       double a[2][2], A[2][2], aup[2][2], Aup[2][2], gamma[2][2];
       // Assign values of A and gamma
       for (unsigned al = 0; al < 2; al++)
       {
         for (unsigned be = 0; be < 2; be++)
         {
           // Initialise a(al,be) and A(al,be) to zero
           a[al][be] = 0.0;
           A[al][be] = 0.0;
           // Now calculate the dot product
           for (unsigned k = 0; k < 3; k++)
           {
             a[al][be] += interpolated_a(al, k) * interpolated_a(be, k);
             A[al][be] += interpolated_A(al, k) * interpolated_A(be, k);
           }
           // Calculate strain tensor
           gamma[al][be] = 0.5 * (A[al][be] - a[al][be]);
         }
       }
       // Calculate the contravariant metric tensor
       double adet = calculate_contravariant(a, aup);
       double Adet = calculate_contravariant(A, Aup);
       // Square roots are expensive, so let's do them once here
       double sqrt_adet = sqrt(adet);
       double sqrt_Adet = sqrt(Adet);
       // Calculate the normal Vectors
       Vector<double> n(3), N(3);
       n[0] = (interpolated_a(0, 1) * interpolated_a(1, 2) -
               interpolated_a(0, 2) * interpolated_a(1, 1)) /
              sqrt_adet;
       n[1] = (interpolated_a(0, 2) * interpolated_a(1, 0) -
               interpolated_a(0, 0) * interpolated_a(1, 2)) /
              sqrt_adet;
       n[2] = (interpolated_a(0, 0) * interpolated_a(1, 1) -
               interpolated_a(0, 1) * interpolated_a(1, 0)) /
              sqrt_adet;
       N[0] = (interpolated_A(0, 1) * interpolated_A(1, 2) -
               interpolated_A(0, 2) * interpolated_A(1, 1)) /
              sqrt_Adet;
       N[1] = (interpolated_A(0, 2) * interpolated_A(1, 0) -
               interpolated_A(0, 0) * interpolated_A(1, 2)) /
              sqrt_Adet;
       N[2] = (interpolated_A(0, 0) * interpolated_A(1, 1) -
               interpolated_A(0, 1) * interpolated_A(1, 0)) /
              sqrt_Adet;
       // Calculate the curvature tensors
       double b[2][2], B[2][2];
       b[0][0] = n[0] * interpolated_dadxi(0, 0) +
                 n[1] * interpolated_dadxi(0, 1) +
                 n[2] * interpolated_dadxi(0, 2);
       // Off-diagonal terms are the same
       b[0][1] = b[1][0] = n[0] * interpolated_dadxi(2, 0) +
                           n[1] * interpolated_dadxi(2, 1) +
                           n[2] * interpolated_dadxi(2, 2);
       b[1][1] = n[0] * interpolated_dadxi(1, 0) +
                 n[1] * interpolated_dadxi(1, 1) +
                 n[2] * interpolated_dadxi(1, 2);
       // Deformed curvature tensor
       B[0][0] = N[0] * interpolated_dAdxi(0, 0) +
                 N[1] * interpolated_dAdxi(0, 1) +
                 N[2] * interpolated_dAdxi(0, 2);
       // Off-diagonal terms are the same
       B[0][1] = B[1][0] = N[0] * interpolated_dAdxi(2, 0) +
                           N[1] * interpolated_dAdxi(2, 1) +
                           N[2] * interpolated_dAdxi(2, 2);
       B[1][1] = N[0] * interpolated_dAdxi(1, 0) +
                 N[1] * interpolated_dAdxi(1, 1) +
                 N[2] * interpolated_dAdxi(1, 2);
       // Set up the change of curvature tensor
       double kappa[2][2];
       for (unsigned i = 0; i < 2; i++)
       {
         for (unsigned j = 0; j < 2; j++)
         {
           kappa[i][j] = b[i][j] - B[i][j];
         }
       }
       // Calculate the plane stress stiffness tensor
       double Et[2][2][2][2];
       // Premultiply some constants
       // NOTE C2 has 1.0-Nu in the denominator
       // double C1 = 1.0/(2.0*(1.0+nu_cached)), C2
       // = 2.0*nu_cached/(1.0-nu_cached);
       // Some constants
       double C1 = 0.5 * (1.0 - nu_cached);
       double C2 = nu_cached;
       // Loop over first index
       for (unsigned i = 0; i < 2; i++)
       {
         for (unsigned j = 0; j < 2; j++)
         {
           for (unsigned k = 0; k < 2; k++)
           {
             for (unsigned l = 0; l < 2; l++)
             {
               // Et[i][j][k][l] = C1*(aup[i][k]*aup[j][l] + aup[i][l]*aup[j][k]
               //                     + C2*aup[i][j]*aup[k][l]);
               Et[i][j][k][l] =
                 C1 * (aup[i][k] * aup[j][l] + aup[i][l] * aup[j][k]) +
                 C2 * aup[i][j] * aup[k][l];
             }
           }
         }
       }
       // Define the load Vector
       Vector<double> f(3);
       // Determine the load
       load_vector(ipt, interpolated_xi, interpolated_x, N, f);
       // Scale the load by the bending stiffness scale
       // for(unsigned i=0;i<3;i++){f[i] *=
       // bending_scale/(1.0-nu_cached*nu_cached);}
       // Allocate storage for variations of the the normal vector
       double normal_var[3][3];
       //=====EQUATIONS OF ELASTICITY FROM PRINCIPLE OF VIRTUAL
       // DISPLACEMENTS========
       // Little tensor to handle the mixed derivative terms
       unsigned mix[2][2] = {{0, 2}, {2, 1}};
       // Loop over the number of nodes
       for (unsigned l = 0; l < n_node; l++)
       {
         // Loop over the type of degree of freedom
         for (unsigned k = 0; k < n_position_type; k++)
         {
           // Setup components of variations in the normal vector
           normal_var[0][0] = 0.0;
           normal_var[0][1] = (-interpolated_A(1, 2) * dpsidxi(l, k, 0) +
                               interpolated_A(0, 2) * dpsidxi(l, k, 1)) /
                              sqrt_Adet;
           normal_var[0][2] = (interpolated_A(1, 1) * dpsidxi(l, k, 0) -
                               interpolated_A(0, 1) * dpsidxi(l, k, 1)) /
                              sqrt_Adet;
           normal_var[1][0] = (interpolated_A(1, 2) * dpsidxi(l, k, 0) -
                               interpolated_A(0, 2) * dpsidxi(l, k, 1)) /
                              sqrt_Adet;
           normal_var[1][1] = 0.0;
           normal_var[1][2] = (-interpolated_A(1, 0) * dpsidxi(l, k, 0) +
                               interpolated_A(0, 0) * dpsidxi(l, k, 1)) /
                              sqrt_Adet;
           normal_var[2][0] = (-interpolated_A(1, 1) * dpsidxi(l, k, 0) +
                               interpolated_A(0, 1) * dpsidxi(l, k, 1)) /
                              sqrt_Adet;
           normal_var[2][1] = (interpolated_A(1, 0) * dpsidxi(l, k, 0) -
                               interpolated_A(0, 0) * dpsidxi(l, k, 1)) /
                              sqrt_Adet;
           normal_var[2][2] = 0.0;
           // Loop over the coordinate direction
           for (unsigned i = 0; i < 3; i++)
           {
             // Get the local equation number
             local_eqn = position_local_eqn(l, k, i);
             // If it's not a boundary condition
             if (local_eqn >= 0)
             {
               // Temporary to hold a common part of the bending terms
               double bending_dot_product_multiplier =
                 ((A[1][1] * interpolated_A(0, i) -
                   A[1][0] * interpolated_A(1, i)) *
                    dpsidxi(l, k, 0) +
                  (A[0][0] * interpolated_A(1, i) -
                   A[0][1] * interpolated_A(0, i)) *
                    dpsidxi(l, k, 1)) /
                 Adet;
               // Combine the cross and dot product bending terms
               for (unsigned i2 = 0; i2 < 3; i2++)
               {
                 normal_var[i][i2] -= N[i2] * bending_dot_product_multiplier;
               }
               // Add in external forcing
               residuals[local_eqn] -=
                 f[i] / h_cached * psi(l, k) * W * sqrt_Adet;
               // Storage for all residual terms that are multipled by the
               // Jacobian and area of the undeformed shell
               // Start with the acceleration term
               double other_residual_terms =
                 lambda_sq_cached * accel[i] * psi(l, k);
               // Now need the loops over the Greek indicies
               for (unsigned al = 0; al < 2; al++)
               {
                 for (unsigned be = 0; be < 2; be++)
                 {
                   // Membrane prestress
                   other_residual_terms += *Prestress_pt(al, be) *
                                           interpolated_A(al, i) *
                                           dpsidxi(l, k, be);
                   // Remaining terms
                   for (unsigned ga = 0; ga < 2; ga++)
                   {
                     for (unsigned de = 0; de < 2; de++)
                     {
                       if (!Ignore_membrane_terms)
                       {
                         // Pure membrane term
                         other_residual_terms +=
                           Et[al][be][ga][de] * gamma[al][be] *
                           interpolated_A(ga, i) * dpsidxi(l, k, de);
                       }
                       // Bending terms
                       other_residual_terms -=
                         bending_scale * Et[al][be][ga][de] * kappa[al][be] *
                         (N[i] * d2psidxi(l, k, mix[ga][de])
                          // Cross and dot product terms
                          +
                          normal_var[i][0] * interpolated_dAdxi(mix[ga][de], 0) +
                          normal_var[i][1] * interpolated_dAdxi(mix[ga][de], 1) +
                          normal_var[i][2] * interpolated_dAdxi(mix[ga][de], 2));
                     }
                   }
                 }
               }
               residuals[local_eqn] += other_residual_terms * W * sqrt_adet;
             }
           }
         }
       }
     } // End of loop over the integration points
   }
References a, b, Global_Physical_Variables::C1, Global_Physical_Variables::C2, calculate_contravariant(), oomph::GeomObject::d2position(), oomph::SolidFiniteElement::d2shape_lagrangian_at_knot(), f(), mathsFunc::gamma(), h(), i, Ignore_membrane_terms, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), oomph::SolidFiniteElement::interpolated_xi(), J, j, k, lambda_sq(), load_vector(), n, N, oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), nu(), oomph::Integral::nweight(), oomph::SolidFiniteElement::position_local_eqn(), Prestress_pt, oomph::FiniteElement::raw_dnodal_position_gen_dt(), oomph::SolidFiniteElement::raw_lagrangian_position_gen(), oomph::FiniteElement::raw_nodal_position_gen(), sqrt(), Undeformed_midplane_pt, w, oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by fill_in_contribution_to_jacobian(), and fill_in_contribution_to_residuals().
get_energy()
void oomph::KirchhoffLoveShellEquations::get_energy (double & pot_en, double & kin_en)
Get potential (strain) and kinetic energy of the element.
Compute the potential (strain) and kinetic energy of the element.
   {
     // Initialise
     pot_en = 0.0;
     kin_en = 0.0;
     // Set the dimension of the coordinates
     const unsigned n_dim = Undeformed_midplane_pt->ndim();
     // Set the number of lagrangian coordinates
     const unsigned n_lagrangian = Undeformed_midplane_pt->nlagrangian();
     // Find out how many nodes there are
     const unsigned n_node = nnode();
     // Find out how many positional dofs there are
     const unsigned n_position_type = nnodal_position_type();
     // Set up memory for the shape functions
     Shape psi(n_node, n_position_type);
     DShape dpsidxi(n_node, n_position_type, n_lagrangian);
     DShape d2psidxi(n_node, n_position_type, 3);
     // Set the value of n_intpt
     const unsigned n_intpt = integral_pt()->nweight();
     // Get Physical Variables from Element
     // External pressure, Poisson ratio , and non-dim thickness h
     const double nu_cached = nu();
     const double h_cached = h();
     const double lambda_sq_cached = lambda_sq();
 #ifdef PARANOID
     // Check for non-zero prestress
     if ((prestress(0, 0) != 0) || (prestress(1, 0) != 0) ||
         (prestress(1, 1) != 0))
     {
       std::string error_message =
         "Warning: Not sure if the energy is computed correctly\n";
       error_message += " for nonzero prestress\n";
       oomph_info << error_message << std::endl;
       //    throw OomphLibWarning(error_message,
       //                          "KirchhoffLoveShellEquations::get_energy()",
       //                          OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Setup storage for various quantities
     Vector<double> veloc(n_dim);
     Vector<double> interpolated_xi(n_lagrangian);
     DenseMatrix<double> interpolated_A(n_lagrangian, n_dim);
     DenseMatrix<double> interpolated_dAdxi(3);
     const double bending_scale = (1.0 / 12.0) * h_cached * h_cached;
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Call the derivatives of the shape functions:
       double J = d2shape_lagrangian_at_knot(ipt, psi, dpsidxi, d2psidxi);
       // Premultiply the weights and the Jacobian
       double W = w * J;
       // Initialise values to zero
       for (unsigned i = 0; i < n_dim; i++)
       {
         veloc[i] = 0.0;
         for (unsigned j = 0; j < n_lagrangian; j++)
         {
           interpolated_A(j, i) = 0.0;
         }
         for (unsigned j = 0; j < 3; j++)
         {
           interpolated_dAdxi(i, j) = 0.0;
         }
       }
       for (unsigned j = 0; j < n_lagrangian; j++)
       {
         interpolated_xi[j] = 0.0;
       }
       // Calculate velocity and derivatives
       for (unsigned l = 0; l < n_node; l++)
       {
         // Loop over positional dofs
         for (unsigned k = 0; k < n_position_type; k++)
         {
           // Loop over lagrangian coordinate directions
           for (unsigned i = 0; i < n_lagrangian; i++)
           {
             interpolated_xi[i] += lagrangian_position_gen(l, k, i) * psi(l, k);
           }
           // Loop over displacement components
           for (unsigned i = 0; i < n_dim; i++)
           {
             veloc[i] += dnodal_position_gen_dt(1, l, k, i) * psi(l, k);
             double x_value = nodal_position_gen(l, k, i);
             // Loop over derivative directions
             for (unsigned j = 0; j < n_lagrangian; j++)
             {
               interpolated_A(j, i) += x_value * dpsidxi(l, k, j);
             }
             // Loop over the second derivative directions
             for (unsigned j = 0; j < 3; j++)
             {
               interpolated_dAdxi(j, i) += x_value * d2psidxi(l, k, j);
             }
           }
         }
       }
       // Get square of veloc
       double veloc_sq = 0;
       for (unsigned i = 0; i < n_dim; i++)
       {
         veloc_sq += veloc[i] * veloc[i];
       }
       // Get the values of the undeformed parameters
       Vector<double> interpolated_r(n_dim);
       DenseMatrix<double> interpolated_a(n_lagrangian, n_dim);
       RankThreeTensor<double> dadxi(n_lagrangian, n_lagrangian, n_dim);
       // Read out the undeformed position from the geometric object
       Undeformed_midplane_pt->d2position(
         interpolated_xi, interpolated_r, interpolated_a, dadxi);
       // Copy the values of the second derivatives into a slightly
       // different data structure, where the mixed derivatives [0][1] and [1][0]
       // are given by the single index [2]
       DenseMatrix<double> interpolated_dadxi(3);
       for (unsigned i = 0; i < 3; i++)
       {
         interpolated_dadxi(0, i) = dadxi(0, 0, i);
         interpolated_dadxi(1, i) = dadxi(1, 1, i);
         interpolated_dadxi(2, i) = dadxi(0, 1, i);
       }
       // Declare and calculate the undeformed and deformed metric tensor,
       // the strain tensor
       double a[2][2], A[2][2], aup[2][2], Aup[2][2], gamma[2][2];
       // Assign values of A and gamma
       for (unsigned al = 0; al < 2; al++)
       {
         for (unsigned be = 0; be < 2; be++)
         {
           // Initialise a(al,be) and A(al,be) to zero
           a[al][be] = 0.0;
           A[al][be] = 0.0;
           // Now calculate the dot product
           for (unsigned k = 0; k < n_dim; k++)
           {
             a[al][be] += interpolated_a(al, k) * interpolated_a(be, k);
             A[al][be] += interpolated_A(al, k) * interpolated_A(be, k);
           }
           // Calculate strain tensor
           gamma[al][be] = 0.5 * (A[al][be] - a[al][be]);
         }
       }
       // Calculate the contravariant metric tensor
       double adet = calculate_contravariant(a, aup);
       double Adet = calculate_contravariant(A, Aup);
       // Square roots are expensive, so let's do them once here
       double sqrt_adet = sqrt(adet);
       double sqrt_Adet = sqrt(Adet);
       // Calculate the normal Vectors
       Vector<double> n(3), N(3);
       n[0] = (interpolated_a(0, 1) * interpolated_a(1, 2) -
               interpolated_a(0, 2) * interpolated_a(1, 1)) /
              sqrt_adet;
       n[1] = (interpolated_a(0, 2) * interpolated_a(1, 0) -
               interpolated_a(0, 0) * interpolated_a(1, 2)) /
              sqrt_adet;
       n[2] = (interpolated_a(0, 0) * interpolated_a(1, 1) -
               interpolated_a(0, 1) * interpolated_a(1, 0)) /
              sqrt_adet;
       N[0] = (interpolated_A(0, 1) * interpolated_A(1, 2) -
               interpolated_A(0, 2) * interpolated_A(1, 1)) /
              sqrt_Adet;
       N[1] = (interpolated_A(0, 2) * interpolated_A(1, 0) -
               interpolated_A(0, 0) * interpolated_A(1, 2)) /
              sqrt_Adet;
       N[2] = (interpolated_A(0, 0) * interpolated_A(1, 1) -
               interpolated_A(0, 1) * interpolated_A(1, 0)) /
              sqrt_Adet;
       // Calculate the curvature tensors
       double b[2][2], B[2][2];
       b[0][0] = n[0] * interpolated_dadxi(0, 0) +
                 n[1] * interpolated_dadxi(0, 1) +
                 n[2] * interpolated_dadxi(0, 2);
       // Off-diagonal terms are the same
       b[0][1] = b[1][0] = n[0] * interpolated_dadxi(2, 0) +
                           n[1] * interpolated_dadxi(2, 1) +
                           n[2] * interpolated_dadxi(2, 2);
       b[1][1] = n[0] * interpolated_dadxi(1, 0) +
                 n[1] * interpolated_dadxi(1, 1) +
                 n[2] * interpolated_dadxi(1, 2);
       // Deformed curvature tensor
       B[0][0] = N[0] * interpolated_dAdxi(0, 0) +
                 N[1] * interpolated_dAdxi(0, 1) +
                 N[2] * interpolated_dAdxi(0, 2);
       // Off-diagonal terms are the same
       B[0][1] = B[1][0] = N[0] * interpolated_dAdxi(2, 0) +
                           N[1] * interpolated_dAdxi(2, 1) +
                           N[2] * interpolated_dAdxi(2, 2);
       B[1][1] = N[0] * interpolated_dAdxi(1, 0) +
                 N[1] * interpolated_dAdxi(1, 1) +
                 N[2] * interpolated_dAdxi(1, 2);
       // Set up the change of curvature tensor
       double kappa[2][2];
       for (unsigned i = 0; i < 2; i++)
       {
         for (unsigned j = 0; j < 2; j++)
         {
           kappa[i][j] = b[i][j] - B[i][j];
         }
       }
       // Calculate the plane stress stiffness tensor
       double Et[2][2][2][2];
       // Some constants
       double C1 = 0.5 * (1.0 - nu_cached);
       double C2 = nu_cached;
       // Loop over first index
       for (unsigned i = 0; i < 2; i++)
       {
         for (unsigned j = 0; j < 2; j++)
         {
           for (unsigned k = 0; k < 2; k++)
           {
             for (unsigned l = 0; l < 2; l++)
             {
               Et[i][j][k][l] =
                 C1 * (aup[i][k] * aup[j][l] + aup[i][l] * aup[j][k]) +
                 C2 * aup[i][j] * aup[k][l];
             }
           }
         }
       }
       // Add contributions to potential energy
       double pot_en_cont = 0.0;
       for (unsigned i = 0; i < 2; i++)
       {
         for (unsigned j = 0; j < 2; j++)
         {
           for (unsigned k = 0; k < 2; k++)
           {
             for (unsigned l = 0; l < 2; l++)
             {
               pot_en_cont +=
                 Et[i][j][k][l] * (gamma[i][j] * gamma[k][l] +
                                   bending_scale * kappa[i][j] * kappa[k][l]);
             }
           }
         }
       }
       pot_en += pot_en_cont * 0.5 * W * sqrt_adet;
       // Add contribution to kinetic energy
       kin_en += 0.5 * lambda_sq_cached * veloc_sq * W * sqrt_adet;
     } // End of loop over the integration points
   }
References a, b, Global_Physical_Variables::C1, Global_Physical_Variables::C2, calculate_contravariant(), oomph::GeomObject::d2position(), oomph::SolidFiniteElement::d2shape_lagrangian_at_knot(), oomph::FiniteElement::dnodal_position_gen_dt(), mathsFunc::gamma(), h(), i, oomph::FiniteElement::integral_pt(), oomph::SolidFiniteElement::interpolated_xi(), J, j, k, oomph::SolidFiniteElement::lagrangian_position_gen(), lambda_sq(), n, N, oomph::GeomObject::ndim(), oomph::GeomObject::nlagrangian(), oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_position_gen(), nu(), oomph::Integral::nweight(), oomph::oomph_info, prestress(), sqrt(), oomph::Global_string_for_annotation::string(), Undeformed_midplane_pt, w, oomph::QuadTreeNames::W, and oomph::Integral::weight().
get_normal()
void oomph::KirchhoffLoveShellEquations::get_normal (const Vector< double > & s, Vector< double > & N)
Get normal vector.
Get normal to the shell.
   {
     // Set the dimension of the coordinates
     const unsigned n_dim = 3;
     // Set the number of lagrangian coordinates
     const unsigned n_lagrangian = 2;
     // Find out how many nodes there are
     const unsigned n_node = nnode();
     // Find out how many positional dofs there are
     const unsigned n_position_type = nnodal_position_type();
     // Set up memory for the shape functions
     Shape psi(n_node, n_position_type);
     DShape dpsidxi(n_node, n_position_type, n_lagrangian);
     // Could/Should we make this more general?
     DShape d2psidxi(n_node, n_position_type, 3);
     // Call the derivatives of the shape functions:
     // d2psidxi(i,0) = \f$ \partial^2 \psi_j / \partial^2 \xi_0^2 \f$
     // d2psidxi(i,1) = \f$ \partial^2 \psi_j / \partial^2 \xi_1^2 \f$
     // d2psidxi(i,2) = \f$ \partial^2 \psi_j/\partial \xi_0 \partial \xi_1 \f$
     (void)dshape_lagrangian(s, psi, dpsidxi);
     // Calculate local values of lagrangian position and
     // the derivative of global position wrt lagrangian coordinates
     DenseMatrix<double> interpolated_A(2, 3);
     // Initialise to zero
     for (unsigned i = 0; i < n_dim; i++)
     {
       for (unsigned j = 0; j < n_lagrangian; j++)
       {
         interpolated_A(j, i) = 0.0;
       }
     }
     // Calculate displacements and derivatives
     for (unsigned l = 0; l < n_node; l++)
     {
       // Loop over positional dofs
       for (unsigned k = 0; k < n_position_type; k++)
       {
         // Loop over displacement components (deformed position)
         for (unsigned i = 0; i < n_dim; i++)
         {
           double x_value = raw_nodal_position_gen(l, k, i);
           // Loop over derivative directions
           for (unsigned j = 0; j < n_lagrangian; j++)
           {
             interpolated_A(j, i) += x_value * dpsidxi(l, k, j);
           }
         }
       }
     }
     // Unscaled normal
     N[0] = (interpolated_A(0, 1) * interpolated_A(1, 2) -
             interpolated_A(0, 2) * interpolated_A(1, 1));
     N[1] = (interpolated_A(0, 2) * interpolated_A(1, 0) -
             interpolated_A(0, 0) * interpolated_A(1, 2));
     N[2] = (interpolated_A(0, 0) * interpolated_A(1, 1) -
             interpolated_A(0, 1) * interpolated_A(1, 0));
     // Normalise
     double norm = 1.0 / sqrt(N[0] * N[0] + N[1] * N[1] + N[2] * N[2]);
     for (unsigned i = 0; i < 3; i++)
     {
       N[i] *= norm;
     }
   }
References oomph::SolidFiniteElement::dshape_lagrangian(), i, j, k, N, oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), oomph::FiniteElement::raw_nodal_position_gen(), s, and sqrt().
Referenced by oomph::ClampedHermiteShellBoundaryConditionElement::fill_in_contribution_to_residuals(), load_rate_of_work(), and oomph::ClampedHermiteShellBoundaryConditionElement::output().
get_strain_and_bend()
std::pair< double, double > oomph::KirchhoffLoveShellEquations::get_strain_and_bend (const Vector< double > & s, DenseDoubleMatrix & strain, DenseDoubleMatrix & bend)
Get strain and bending tensors.
Get strain and bending tensors; returns pair comprising the determinant of the undeformed (*.first) and deformed (*.second) midplane metric tensor.
   {
     // Set the dimension of the coordinates
     const unsigned n_dim = 3;
     // Set the number of lagrangian coordinates
     const unsigned n_lagrangian = 2;
     // Find out how many nodes there are
     const unsigned n_node = nnode();
     // Find out how many positional dofs there are
     const unsigned n_position_type = nnodal_position_type();
     // Set up memory for the shape functions
     Shape psi(n_node, n_position_type);
     DShape dpsidxi(n_node, n_position_type, n_lagrangian);
     // Could/Should we make this more general?
     DShape d2psidxi(n_node, n_position_type, 3);
     // Call the derivatives of the shape functions:
     // d2psidxi(i,0) = \f$ \partial^2 \psi_j / \partial^2 \xi_0^2 \f$
     // d2psidxi(i,1) = \f$ \partial^2 \psi_j / \partial^2 \xi_1^2 \f$
     // d2psidxi(i,2) = \f$ \partial^2 \psi_j/\partial \xi_0 \partial \xi_1 \f$
     (void)d2shape_lagrangian(s, psi, dpsidxi, d2psidxi);
     // Calculate local values of lagrangian position and
     // the derivative of global position wrt lagrangian coordinates
     Vector<double> interpolated_xi(2, 0.0), interpolated_x(3, 0.0);
     Vector<double> accel(3, 0.0);
     DenseMatrix<double> interpolated_A(2, 3);
     DenseMatrix<double> interpolated_dAdxi(3);
     // Initialise to zero
     for (unsigned i = 0; i < n_dim; i++)
     {
       for (unsigned j = 0; j < n_lagrangian; j++)
       {
         interpolated_A(j, i) = 0.0;
       }
       for (unsigned j = 0; j < 3; j++)
       {
         interpolated_dAdxi(i, j) = 0.0;
       }
     }
     // Calculate displacements and derivatives
     for (unsigned l = 0; l < n_node; l++)
     {
       // Loop over positional dofs
       for (unsigned k = 0; k < n_position_type; k++)
       {
         // Loop over lagrangian coordinate directions
         for (unsigned i = 0; i < n_lagrangian; i++)
         {
           interpolated_xi[i] +=
             raw_lagrangian_position_gen(l, k, i) * psi(l, k);
         }
         // Loop over displacement components (deformed position)
         for (unsigned i = 0; i < n_dim; i++)
         {
           double x_value = raw_nodal_position_gen(l, k, i);
           // Calculate interpolated (deformed) position
           interpolated_x[i] += x_value * psi(l, k);
           // Calculate the acceleration
           accel[i] += raw_dnodal_position_gen_dt(2, l, k, i) * psi(l, k);
           // Loop over derivative directions
           for (unsigned j = 0; j < n_lagrangian; j++)
           {
             interpolated_A(j, i) += x_value * dpsidxi(l, k, j);
           }
           // Loop over the second derivative directions
           for (unsigned j = 0; j < 3; j++)
           {
             interpolated_dAdxi(j, i) += x_value * d2psidxi(l, k, j);
           }
         }
       }
     }
     // Get the values of the undeformed parameters
     Vector<double> interpolated_R(3);
     DenseMatrix<double> interpolated_a(2, 3);
     RankThreeTensor<double> dadxi(2, 2, 3);
     // Read out the undeformed position from the geometric object
     Undeformed_midplane_pt->d2position(
       interpolated_xi, interpolated_R, interpolated_a, dadxi);
     // Copy the values of the second derivatives into a slightly
     // different data structure, where the mixed derivatives [0][1] and [1][0]
     // are given by the single index [2]
     DenseMatrix<double> interpolated_dadxi(3);
     for (unsigned i = 0; i < 3; i++)
     {
       interpolated_dadxi(0, i) = dadxi(0, 0, i);
       interpolated_dadxi(1, i) = dadxi(1, 1, i);
       interpolated_dadxi(2, i) = dadxi(0, 1, i);
     }
     // Declare and calculate the undeformed and deformed metric tensor
     double a[2][2], A[2][2], aup[2][2], Aup[2][2];
     // Assign values of A and gamma
     for (unsigned al = 0; al < 2; al++)
     {
       for (unsigned be = 0; be < 2; be++)
       {
         // Initialise a(al,be) and A(al,be) to zero
         a[al][be] = 0.0;
         A[al][be] = 0.0;
         // Now calculate the dot product
         for (unsigned k = 0; k < 3; k++)
         {
           a[al][be] += interpolated_a(al, k) * interpolated_a(be, k);
           A[al][be] += interpolated_A(al, k) * interpolated_A(be, k);
         }
         // Calculate strain tensor
         strain(al, be) = 0.5 * (A[al][be] - a[al][be]);
       }
     }
     // Calculate the contravariant metric tensor
     double adet = calculate_contravariant(a, aup);
     double Adet = calculate_contravariant(A, Aup);
     // Square roots are expensive, so let's do them once here
     double sqrt_adet = sqrt(adet);
     double sqrt_Adet = sqrt(Adet);
     // Calculate the normal Vectors
     Vector<double> n(3), N(3);
     n[0] = (interpolated_a(0, 1) * interpolated_a(1, 2) -
             interpolated_a(0, 2) * interpolated_a(1, 1)) /
            sqrt_adet;
     n[1] = (interpolated_a(0, 2) * interpolated_a(1, 0) -
             interpolated_a(0, 0) * interpolated_a(1, 2)) /
            sqrt_adet;
     n[2] = (interpolated_a(0, 0) * interpolated_a(1, 1) -
             interpolated_a(0, 1) * interpolated_a(1, 0)) /
            sqrt_adet;
     N[0] = (interpolated_A(0, 1) * interpolated_A(1, 2) -
             interpolated_A(0, 2) * interpolated_A(1, 1)) /
            sqrt_Adet;
     N[1] = (interpolated_A(0, 2) * interpolated_A(1, 0) -
             interpolated_A(0, 0) * interpolated_A(1, 2)) /
            sqrt_Adet;
     N[2] = (interpolated_A(0, 0) * interpolated_A(1, 1) -
             interpolated_A(0, 1) * interpolated_A(1, 0)) /
            sqrt_Adet;
     // Calculate the curvature tensors
     double b[2][2], B[2][2];
     b[0][0] = n[0] * interpolated_dadxi(0, 0) +
               n[1] * interpolated_dadxi(0, 1) + n[2] * interpolated_dadxi(0, 2);
     // Off-diagonal terms are the same
     b[0][1] = b[1][0] = n[0] * interpolated_dadxi(2, 0) +
                         n[1] * interpolated_dadxi(2, 1) +
                         n[2] * interpolated_dadxi(2, 2);
     b[1][1] = n[0] * interpolated_dadxi(1, 0) +
               n[1] * interpolated_dadxi(1, 1) + n[2] * interpolated_dadxi(1, 2);
     // Deformed curvature tensor
     B[0][0] = N[0] * interpolated_dAdxi(0, 0) +
               N[1] * interpolated_dAdxi(0, 1) + N[2] * interpolated_dAdxi(0, 2);
     // Off-diagonal terms are the same
     B[0][1] = B[1][0] = N[0] * interpolated_dAdxi(2, 0) +
                         N[1] * interpolated_dAdxi(2, 1) +
                         N[2] * interpolated_dAdxi(2, 2);
     B[1][1] = N[0] * interpolated_dAdxi(1, 0) +
               N[1] * interpolated_dAdxi(1, 1) + N[2] * interpolated_dAdxi(1, 2);
     // Set up the change of curvature tensor
     for (unsigned i = 0; i < 2; i++)
     {
       for (unsigned j = 0; j < 2; j++)
       {
         bend(i, j) = b[i][j] - B[i][j];
       }
     }
     // Return undeformed and deformed determinant of in-plane metric
     // tensor
     return std::make_pair(adet, Adet);
   }
References a, b, calculate_contravariant(), oomph::GeomObject::d2position(), oomph::SolidFiniteElement::d2shape_lagrangian(), i, oomph::FiniteElement::interpolated_x(), oomph::SolidFiniteElement::interpolated_xi(), j, k, n, N, oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), oomph::FiniteElement::raw_dnodal_position_gen_dt(), oomph::SolidFiniteElement::raw_lagrangian_position_gen(), oomph::FiniteElement::raw_nodal_position_gen(), s, sqrt(), and Undeformed_midplane_pt.
h()
const double& oomph::KirchhoffLoveShellEquations::h () const inline
Return the wall thickness to undeformed radius ratio.
     {
       return *H_pt;
     }
References H_pt.
Referenced by fill_in_contribution_to_residuals_shell(), get_energy(), and load_rate_of_work().
h_pt()
double*& oomph::KirchhoffLoveShellEquations::h_pt () inline
Return a pointer to the non-dim wall thickness.
     {
       return H_pt;
     }
References H_pt.
lambda_sq()
const double& oomph::KirchhoffLoveShellEquations::lambda_sq () const inline
Return the timescale ratio (non-dimensional density)
     {
       return *Lambda_sq_pt;
     }
References Lambda_sq_pt.
Referenced by fill_in_contribution_to_residuals_shell(), and get_energy().
lambda_sq_pt()
double*& oomph::KirchhoffLoveShellEquations::lambda_sq_pt () inline
Return a pointer to timescale ratio (nondim density)
     {
       return Lambda_sq_pt;
     }
References Lambda_sq_pt.
load_rate_of_work()
double oomph::KirchhoffLoveShellEquations::load_rate_of_work ()
Get integral of instantaneous rate of work done on the wall due to the load returned by the virtual function load_vector_for_rate_of_work_computation(...). In the current class the latter function simply de-references the external load but this can be overloaded in derived classes (e.g. in FSI elements) to determine the rate of work done by individual constituents of this load (e.g. the fluid load in an FSI problem).
   {
     // Initialise
     double rate_of_work_integral = 0.0;
     // The number of dimensions
     const unsigned n_dim = 3;
     // The number of lagrangian coordinates
     const unsigned n_lagrangian = 2;
     // The number of nodes
     const unsigned n_node = nnode();
     // Number of integration points
     unsigned n_intpt = integral_pt()->nweight();
     // Find out how many positional dofs there are
     unsigned n_position_type = nnodal_position_type();
     // Vector to hold local coordinate in element
     Vector<double> s(n_lagrangian);
     // Set up storage for shape functions and derivatives of shape functions
     Shape psi(n_node, n_position_type);
     DShape dpsidxi(n_node, n_position_type, n_lagrangian);
     // Storage for jacobian of mapping from local to Lagrangian coords
     DenseMatrix<double> jacobian(n_lagrangian);
     // Storage for velocity vector
     Vector<double> velocity(n_dim);
     // Storage for load vector
     Vector<double> load(n_dim);
     // Storage for normal vector
     Vector<double> normal(n_dim);
     // Storage for Lagrangian and Eulerian coordinates
     Vector<double> xi(n_lagrangian);
     Vector<double> x(n_dim);
     // Storage for covariant vectors
     DenseMatrix<double> interpolated_A(n_lagrangian, n_dim);
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Get local coords at knot
       for (unsigned i = 0; i < n_lagrangian; i++)
       {
         s[i] = integral_pt()->knot(ipt, i);
       }
       // Get shape functions, derivatives, determinant of Jacobian of mapping
       double J = dshape_lagrangian(s, psi, dpsidxi);
       // Premultiply the weights and the Jacobian
       double W = w * J;
       // Initialise velocity, x and interpolated_A to zero
       for (unsigned i = 0; i < n_dim; i++)
       {
         velocity[i] = 0.0;
         x[i] = 0.0;
         for (unsigned j = 0; j < n_lagrangian; j++)
         {
           interpolated_A(j, i) = 0.0;
         }
       }
       // Initialise xi to zero
       for (unsigned i = 0; i < n_lagrangian; i++)
       {
         xi[i] = 0.0;
       }
       // Calculate velocity, coordinates and derivatives
       for (unsigned l = 0; l < n_node; l++)
       {
         // Loop over positional dofs
         for (unsigned k = 0; k < n_position_type; k++)
         {
           // Loop over lagrangian coordinate directions
           for (unsigned i = 0; i < n_lagrangian; i++)
           {
             xi[i] += lagrangian_position_gen(l, k, i) * psi(l, k);
           }
           // Loop over displacement components
           for (unsigned i = 0; i < n_dim; i++)
           {
             velocity[i] += dnodal_position_gen_dt(1, l, k, i) * psi(l, k);
             double x_value = nodal_position_gen(l, k, i);
             x[i] += x_value * psi(l, k);
             // Loop over derivative directions
             for (unsigned j = 0; j < n_lagrangian; j++)
             {
               interpolated_A(j, i) += x_value * dpsidxi(l, k, j);
             }
           }
         }
       }
       // Get deformed metric tensor
       double A[2][2];
       for (unsigned al = 0; al < 2; al++)
       {
         for (unsigned be = 0; be < 2; be++)
         {
           // Initialise A(al,be) to zero
           A[al][be] = 0.0;
           // Calculate the dot product
           for (unsigned k = 0; k < n_dim; k++)
           {
             A[al][be] += interpolated_A(al, k) * interpolated_A(be, k);
           }
         }
       }
       // Get determinant of metric tensor
       double A_det = A[0][0] * A[1][1] - A[0][1] * A[1][0];
       // Get outer unit normal
       get_normal(s, normal);
       // Get load vector
       load_vector_for_rate_of_work_computation(ipt, xi, x, normal, load);
       // Local rate of work:
       double rate_of_work = 0.0;
       for (unsigned i = 0; i < n_dim; i++)
       {
         rate_of_work += load[i] * velocity[i];
       }
       // Add rate of work
       rate_of_work_integral += rate_of_work / h() * W * A_det;
     }
     return rate_of_work_integral;
   }
References oomph::FiniteElement::dnodal_position_gen_dt(), oomph::SolidFiniteElement::dshape_lagrangian(), get_normal(), h(), i, oomph::FiniteElement::integral_pt(), J, j, k, oomph::Integral::knot(), oomph::SolidFiniteElement::lagrangian_position_gen(), load(), load_vector_for_rate_of_work_computation(), oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_position_gen(), WallFunction::normal(), oomph::Integral::nweight(), s, Jeffery_Solution::velocity(), w, oomph::QuadTreeNames::W, oomph::Integral::weight(), and plotDoE::x.
Referenced by oomph::FSIDiagHermiteShellElement::fluid_load_rate_of_work().
load_vector()
virtual void oomph::KirchhoffLoveShellEquations::load_vector (const unsigned & intpt, const Vector< double > & xi, const Vector< double > & x, const Vector< double > & N, Vector< double > & load) inline virtual
Get the load vector: Pass number of integration point (dummy), Lagr. coordinate and normal vector and return the load vector (not all of the input arguments will be required for all specific load functions but the list should cover all cases). This function is virtual so it can be overloaded for FSI.
Reimplemented in oomph::FSIDiagHermiteShellElement.
     {
       Load_vector_fct_pt(xi, x, N, load);
     }
References load(), Load_vector_fct_pt, N, and plotDoE::x.
Referenced by fill_in_contribution_to_residuals_shell(), and load_vector_for_rate_of_work_computation().
load_vector_for_rate_of_work_computation()
virtual void oomph::KirchhoffLoveShellEquations::load_vector_for_rate_of_work_computation (const unsigned & intpt, const Vector< double > & xi, const Vector< double > & x, const Vector< double > & N, Vector< double > & load) inline protected virtual
Get the load vector for the computation of the rate of work done by the load. Here we simply forward this to load_vector(...) but allow it to be overloaded in derived classes to allow the computation of the rate of work due to constituent parts of the load vector (e.g. the fluid traction in an FSI problem). Pass number of integration point (dummy), Lagr. coordinate and normal vector and return the load vector (not all of the input arguments will be required for all specific load functions but the list should cover all cases).
Reimplemented in oomph::FSIDiagHermiteShellElement.
     {
       load_vector(intpt, xi, x, N, load);
     }
References load(), load_vector(), N, and plotDoE::x.
Referenced by load_rate_of_work().
nu()
const double& oomph::KirchhoffLoveShellEquations::nu () const inline
Return the Poisson's ratio.
     {
       return *Nu_pt;
     }
References Nu_pt.
Referenced by fill_in_contribution_to_residuals_shell(), and get_energy().
nu_pt()
double*& oomph::KirchhoffLoveShellEquations::nu_pt () inline
Return a pointer to the Poisson ratio.
     {
       return Nu_pt;
     }
References Nu_pt.
output() [1/4]
void oomph::KirchhoffLoveShellEquations::output (FILE * file_pt) inline virtual
Generic FiniteElement output function.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::HermiteShellElement.
     {
       FiniteElement::output(file_pt);
     }
References oomph::FiniteElement::output().
output() [2/4]
void oomph::KirchhoffLoveShellEquations::output (FILE * file_pt, const unsigned & n_plot) inline virtual
Generic FiniteElement output function.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::HermiteShellElement.
     {
       FiniteElement::output(file_pt, n_plot);
     }
References oomph::FiniteElement::output().
output() [3/4]
void oomph::KirchhoffLoveShellEquations::output (std::ostream & outfile) inline virtual
Generic FiniteElement output function.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::HermiteShellElement.
     {
       FiniteElement::output(outfile);
     }
References oomph::FiniteElement::output().
output() [4/4]
void oomph::KirchhoffLoveShellEquations::output (std::ostream & outfile, const unsigned & n_plot) inline virtual
Generic FiniteElement output function.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::HermiteShellElement.
     {
       FiniteElement::output(outfile, n_plot);
     }
References oomph::FiniteElement::output().
prestress()
double oomph::KirchhoffLoveShellEquations::prestress (const unsigned & i, const unsigned & j) inline
Return (i,j)-th component of second Piola Kirchhoff membrane prestress
     {
       return *Prestress_pt(i, j);
     }
References i, j, and Prestress_pt.
Referenced by get_energy().
set_prestress_pt()
void oomph::KirchhoffLoveShellEquations::set_prestress_pt (const unsigned & i, const unsigned & j, double * value_pt) inline
Set pointer to (i,j)-th component of second Piola Kirchhoff membrane prestress to specified value (automatically imposes symmetry for off-diagonal entries)
     {
       Prestress_pt(i, j) = value_pt;
       Prestress_pt(j, i) = value_pt;
     }
References i, j, and Prestress_pt.
undeformed_midplane_pt()
GeomObject*& oomph::KirchhoffLoveShellEquations::undeformed_midplane_pt () inline
Return a reference to geometric object that specifies the shell's undeformed geometry
     {
       return Undeformed_midplane_pt;
     }
References Undeformed_midplane_pt.
Zero_traction_fct()
void oomph::KirchhoffLoveShellEquations::Zero_traction_fct (const Vector< double > & xi, const Vector< double > & x, const Vector< double > & N, Vector< double > & load) static protected
Default load function (zero traction)
   {
     unsigned n_dim = load.size();
     for (unsigned i = 0; i < n_dim; i++)
     {
       load[i] = 0.0;
     }
   }
References i, and load().
Referenced by KirchhoffLoveShellEquations().
Member Data Documentation
Default_h_value
double oomph::KirchhoffLoveShellEquations::Default_h_value = 0.05 static private
Static default value for the thickness ratio.
Static default value for non-dim wall thickness (1/20)
Referenced by KirchhoffLoveShellEquations().
Default_lambda_sq_value
double oomph::KirchhoffLoveShellEquations::Default_lambda_sq_value = 1.0 static private
Static default value for the timescale ratio (1.0 for natural scaling)
Static default value for timescale ratio (1.0 for natural scaling)
Referenced by KirchhoffLoveShellEquations().
Default_nu_value
double oomph::KirchhoffLoveShellEquations::Default_nu_value = 0.49 static private
Static default value for the Poisson's ratio.
Default value for the Poisson ratio: 0.49 for no particular reason.
Referenced by KirchhoffLoveShellEquations().
H_pt
double* oomph::KirchhoffLoveShellEquations::H_pt private
Pointer to dimensionless wall thickness.
Referenced by h(), h_pt(), and KirchhoffLoveShellEquations().
Ignore_membrane_terms
bool oomph::KirchhoffLoveShellEquations::Ignore_membrane_terms private
Boolean flag to ignore membrane terms.
Referenced by disable_membrane_terms(), enable_membrane_terms(), fill_in_contribution_to_residuals_shell(), and KirchhoffLoveShellEquations().
Lambda_sq_pt
double* oomph::KirchhoffLoveShellEquations::Lambda_sq_pt private
Pointer to timescale ratio (non-dimensional density)
Referenced by KirchhoffLoveShellEquations(), lambda_sq(), and lambda_sq_pt().
load_vector_fct_pt
void(*&)(const Vector<double>& xi, const Vector<double>& x, const Vector<double>& N, Vector<double>& load) oomph::KirchhoffLoveShellEquations::load_vector_fct_pt() inline
Access to the load vector function pointer.
     {
       return Load_vector_fct_pt;
     }
Load_vector_fct_pt
void(* oomph::KirchhoffLoveShellEquations::Load_vector_fct_pt) (const Vector< double > &xi, const Vector< double > &x, const Vector< double > &N, Vector< double > &load) protected
Pointer to load vector function: Its arguments are: Lagrangian coordinate, Eulerian coordinate, normal vector and load vector itself (not all of the input arguments will be required for all specific load functions but the list should cover all cases)
Referenced by KirchhoffLoveShellEquations(), load_vector(), and oomph::FSIDiagHermiteShellElement::load_vector().
Nu_pt
double* oomph::KirchhoffLoveShellEquations::Nu_pt private
Pointer to Poisson's ratio.
Referenced by KirchhoffLoveShellEquations(), nu(), and nu_pt().
Prestress_pt
DenseMatrix<double*> oomph::KirchhoffLoveShellEquations::Prestress_pt private
Pointer to membrane pre-stress terms – should probably generalise this to function pointers at some point
Referenced by fill_in_contribution_to_residuals_shell(), KirchhoffLoveShellEquations(), prestress(), and set_prestress_pt().
Undeformed_midplane_pt
GeomObject* oomph::KirchhoffLoveShellEquations::Undeformed_midplane_pt protected
Pointer to the GeomObject that specifies the undeformed midplane of the shell
Referenced by oomph::FSIDiagHermiteShellElement::dposition_dlagrangian_at_local_coordinate(), fill_in_contribution_to_residuals_shell(), get_energy(), get_strain_and_bend(), and undeformed_midplane_pt().
Zero_prestress
double oomph::KirchhoffLoveShellEquations::Zero_prestress = 0.0 static private
Static default for prestress (set to zero)
Referenced by KirchhoffLoveShellEquations().
The documentation for this class was generated from the following files:
shell_elements.h
shell_elements.cc