MercuryDPM: Eigen::internal::scalar_bitwise_not_op< Scalar > Struct Template Reference
Eigen::internal::scalar_bitwise_not_op< Scalar > Struct Template Reference
Template functor to compute the bitwise not of a scalar.
#include <UnaryFunctors.h>
Public Member Functions
EIGEN_STATIC_ASSERT (!NumTraits< Scalar >::RequireInitialization, BITWISE OPERATIONS MAY ONLY BE PERFORMED ON PLAIN DATA TYPES) using result_type
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar operator() (const Scalar &a) const
template<typename Packet >
EIGEN_STRONG_INLINE Packet packetOp (const Packet &a) const
Detailed Description
template<typename Scalar>
struct Eigen::internal::scalar_bitwise_not_op< Scalar >
Template functor to compute the bitwise not of a scalar.
See also
class CwiseUnaryOp, ArrayBase::operator~
Member Function Documentation
EIGEN_STATIC_ASSERT()
template<typename Scalar > Eigen::internal::scalar_bitwise_not_op< Scalar >::EIGEN_STATIC_ASSERT (!NumTraits< Scalar >::RequireInitialization , BITWISE OPERATIONS MAY ONLY BE PERFORMED ON PLAIN DATA TYPES)
operator()()
template<typename Scalar > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar Eigen::internal::scalar_bitwise_not_op< Scalar >::operator() (const Scalar & a) const inline
{
     return bitwise_unary_impl<Scalar>::run_not(a);
   }
References a, and Eigen::internal::bitwise_unary_impl< Scalar, IsComplex >::run_not().
packetOp()
template<typename Scalar > template<typename Packet > EIGEN_STRONG_INLINE Packet Eigen::internal::scalar_bitwise_not_op< Scalar >::packetOp (const Packet & a) const inline
{
     return pandnot(ptrue(a), a);
   }
References a, Eigen::internal::pandnot(), and Eigen::internal::ptrue().
The documentation for this struct was generated from the following file:
functors/UnaryFunctors.h