MercuryDPM: Eigen::internal::evaluator< PlainObjectBase< Derived > > Struct Template Reference
Eigen::internal::evaluator< PlainObjectBase< Derived > > Struct Template Reference
#include <CoreEvaluators.h>
Public Types
enum {
IsRowMajor = PlainObjectType::IsRowMajor , IsVectorAtCompileTime = PlainObjectType::IsVectorAtCompileTime , RowsAtCompileTime = PlainObjectType::RowsAtCompileTime , ColsAtCompileTime = PlainObjectType::ColsAtCompileTime ,
CoeffReadCost = NumTraits<Scalar>::ReadCost , Flags = traits<Derived>::EvaluatorFlags , Alignment = traits<Derived>::Alignment
}
enum { OuterStrideAtCompileTime }
typedef PlainObjectBase< Derived > PlainObjectType
typedef PlainObjectType::Scalar Scalar
typedef PlainObjectType::CoeffReturnType CoeffReturnType
Public Types inherited from Eigen::internal::evaluator_base< Derived >
enum
typedef traits< Derived > ExpressionTraits
Public Member Functions
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE evaluator ()
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE evaluator (const PlainObjectType &m)
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE CoeffReturnType coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE Scalar & coeffRef (Index row, Index col)
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE Scalar & coeffRef (Index index)
template<int LoadMode, typename PacketType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType packet (Index row, Index col) const
template<int LoadMode, typename PacketType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType packet (Index index) const
template<int StoreMode, typename PacketType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void writePacket (Index row, Index col, const PacketType &x)
template<int StoreMode, typename PacketType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void writePacket (Index index, const PacketType &x)
Public Member Functions inherited from Eigen::internal::evaluator_base< Derived >
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE evaluator_base ()=default
Protected Attributes
plainobjectbase_evaluator_data< Scalar, OuterStrideAtCompileTime > m_d
Member Typedef Documentation
CoeffReturnType
template<typename Derived > typedef PlainObjectType::CoeffReturnType Eigen::internal::evaluator< PlainObjectBase< Derived > >::CoeffReturnType
PlainObjectType
template<typename Derived > typedef PlainObjectBase<Derived> Eigen::internal::evaluator< PlainObjectBase< Derived > >::PlainObjectType
Scalar
template<typename Derived > typedef PlainObjectType::Scalar Eigen::internal::evaluator< PlainObjectBase< Derived > >::Scalar
Member Enumeration Documentation
anonymous enum
template<typename Derived > anonymous enum
Enumerator
IsRowMajor
IsVectorAtCompileTime
RowsAtCompileTime
ColsAtCompileTime
CoeffReadCost
Flags
Alignment
        {
     IsRowMajor = PlainObjectType::IsRowMajor,
     IsVectorAtCompileTime = PlainObjectType::IsVectorAtCompileTime,
     RowsAtCompileTime = PlainObjectType::RowsAtCompileTime,
     ColsAtCompileTime = PlainObjectType::ColsAtCompileTime,
     CoeffReadCost = NumTraits<Scalar>::ReadCost,
     Flags = traits<Derived>::EvaluatorFlags,
     Alignment = traits<Derived>::Alignment
   };
anonymous enum
template<typename Derived > anonymous enum
Enumerator
OuterStrideAtCompileTime
        {
     // We do not need to know the outer stride for vectors
     OuterStrideAtCompileTime = IsVectorAtCompileTime ? 0
                                : int(IsRowMajor)     ? ColsAtCompileTime
                                                      : RowsAtCompileTime
   };
Constructor & Destructor Documentation
evaluator() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE Eigen::internal::evaluator< PlainObjectBase< Derived > >::evaluator () inline constexpr
                                                               : m_d(0, OuterStrideAtCompileTime) {
     EIGEN_INTERNAL_CHECK_COST_VALUE(CoeffReadCost);
   }
References EIGEN_INTERNAL_CHECK_COST_VALUE.
evaluator() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE Eigen::internal::evaluator< PlainObjectBase< Derived > >::evaluator (const PlainObjectType & m) inline explicit constexpr
       : m_d(m.data(), IsVectorAtCompileTime ? 0 : m.outerStride()) {
     EIGEN_INTERNAL_CHECK_COST_VALUE(CoeffReadCost);
   }
References EIGEN_INTERNAL_CHECK_COST_VALUE.
Member Function Documentation
coeff() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::evaluator< PlainObjectBase< Derived > >::coeff (Index index) const inline constexpr
 { return m_d.data[index]; }
coeff() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::evaluator< PlainObjectBase< Derived > >::coeff (Index row, Index col) const inline constexpr
{
     if (IsRowMajor)
       return m_d.data[row * m_d.outerStride() + col];
     else
       return m_d.data[row + col * m_d.outerStride()];
   }
References col(), and row().
coeffRef() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE Scalar& Eigen::internal::evaluator< PlainObjectBase< Derived > >::coeffRef (Index index) inline constexpr
{
     return const_cast<Scalar*>(m_d.data)[index];
   }
coeffRef() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE Scalar& Eigen::internal::evaluator< PlainObjectBase< Derived > >::coeffRef (Index row, Index col) inline constexpr
{
     if (IsRowMajor)
       return const_cast<Scalar*>(m_d.data)[row * m_d.outerStride() + col];
     else
       return const_cast<Scalar*>(m_d.data)[row + col * m_d.outerStride()];
   }
References col(), and row().
packet() [1/2]
template<typename Derived > template<int LoadMode, typename PacketType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType Eigen::internal::evaluator< PlainObjectBase< Derived > >::packet (Index index) const inline
{
     return ploadt<PacketType, LoadMode>(m_d.data + index);
   }
packet() [2/2]
template<typename Derived > template<int LoadMode, typename PacketType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType Eigen::internal::evaluator< PlainObjectBase< Derived > >::packet (Index row, Index col) const inline
{
     if (IsRowMajor)
       return ploadt<PacketType, LoadMode>(m_d.data + row * m_d.outerStride() + col);
     else
       return ploadt<PacketType, LoadMode>(m_d.data + row + col * m_d.outerStride());
   }
References col(), and row().
writePacket() [1/2]
template<typename Derived > template<int StoreMode, typename PacketType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::evaluator< PlainObjectBase< Derived > >::writePacket (Index index, const PacketType & x) inline
{
     return pstoret<Scalar, PacketType, StoreMode>(const_cast<Scalar*>(m_d.data) + index, x);
   }
References plotDoE::x.
writePacket() [2/2]
template<typename Derived > template<int StoreMode, typename PacketType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::evaluator< PlainObjectBase< Derived > >::writePacket (Index row, Index col, const PacketType & x) inline
{
     if (IsRowMajor)
       return pstoret<Scalar, PacketType, StoreMode>(const_cast<Scalar*>(m_d.data) + row * m_d.outerStride() + col, x);
     else
       return pstoret<Scalar, PacketType, StoreMode>(const_cast<Scalar*>(m_d.data) + row + col * m_d.outerStride(), x);
   }
References col(), row(), and plotDoE::x.
Member Data Documentation
m_d
template<typename Derived > plainobjectbase_evaluator_data<Scalar, OuterStrideAtCompileTime> Eigen::internal::evaluator< PlainObjectBase< Derived > >::m_d protected
The documentation for this struct was generated from the following file:
CoreEvaluators.h