MercuryDPM: TestFunc1< Scalar_, NX, NY > Struct Template Reference
TestFunc1< Scalar_, NX, NY > Struct Template Reference
Public Types
enum { InputsAtCompileTime = NX , ValuesAtCompileTime = NY }
enum { InputsAtCompileTime = NX , ValuesAtCompileTime = NY }
typedef Scalar_ Scalar
typedef Matrix< Scalar, InputsAtCompileTime, 1 > InputType
typedef Matrix< Scalar, ValuesAtCompileTime, 1 > ValueType
typedef Matrix< Scalar, ValuesAtCompileTime, InputsAtCompileTime > JacobianType
typedef Scalar_ Scalar
typedef Matrix< Scalar, InputsAtCompileTime, 1 > InputType
typedef Matrix< Scalar, ValuesAtCompileTime, 1 > ValueType
typedef Matrix< Scalar, ValuesAtCompileTime, InputsAtCompileTime > JacobianType
Public Member Functions
TestFunc1 ()
TestFunc1 (int inputs_, int values_)
int inputs () const
int values () const
template<typename T >
void operator() (const Matrix< T, InputsAtCompileTime, 1 > &x, Matrix< T, ValuesAtCompileTime, 1 > *_v) const
void operator() (const InputType &x, ValueType *v, JacobianType *_j) const
TestFunc1 ()
TestFunc1 (int inputs_, int values_)
int inputs () const
int values () const
template<typename T >
void operator() (const Matrix< T, InputsAtCompileTime, 1 > &x, Matrix< T, ValuesAtCompileTime, 1 > *_v) const
void operator() (const InputType &x, ValueType *v, JacobianType *_j) const
Public Attributes
int m_inputs
int m_values
Member Typedef Documentation
InputType [1/2]
template<typename Scalar_ , int NX = Dynamic, int NY = Dynamic> typedef Matrix<Scalar, InputsAtCompileTime, 1> TestFunc1< Scalar_, NX, NY >::InputType
InputType [2/2]
template<typename Scalar_ , int NX = Dynamic, int NY = Dynamic> typedef Matrix<Scalar, InputsAtCompileTime, 1> TestFunc1< Scalar_, NX, NY >::InputType
JacobianType [1/2]
template<typename Scalar_ , int NX = Dynamic, int NY = Dynamic> typedef Matrix<Scalar, ValuesAtCompileTime, InputsAtCompileTime> TestFunc1< Scalar_, NX, NY >::JacobianType
JacobianType [2/2]
template<typename Scalar_ , int NX = Dynamic, int NY = Dynamic> typedef Matrix<Scalar, ValuesAtCompileTime, InputsAtCompileTime> TestFunc1< Scalar_, NX, NY >::JacobianType
Scalar [1/2]
template<typename Scalar_ , int NX = Dynamic, int NY = Dynamic> typedef Scalar_ TestFunc1< Scalar_, NX, NY >::Scalar
Scalar [2/2]
template<typename Scalar_ , int NX = Dynamic, int NY = Dynamic> typedef Scalar_ TestFunc1< Scalar_, NX, NY >::Scalar
ValueType [1/2]
template<typename Scalar_ , int NX = Dynamic, int NY = Dynamic> typedef Matrix<Scalar, ValuesAtCompileTime, 1> TestFunc1< Scalar_, NX, NY >::ValueType
ValueType [2/2]
template<typename Scalar_ , int NX = Dynamic, int NY = Dynamic> typedef Matrix<Scalar, ValuesAtCompileTime, 1> TestFunc1< Scalar_, NX, NY >::ValueType
Member Enumeration Documentation
anonymous enum
template<typename Scalar_ , int NX = Dynamic, int NY = Dynamic> anonymous enum
Enumerator
InputsAtCompileTime
ValuesAtCompileTime
 { InputsAtCompileTime = NX, ValuesAtCompileTime = NY };
anonymous enum
template<typename Scalar_ , int NX = Dynamic, int NY = Dynamic> anonymous enum
Enumerator
InputsAtCompileTime
ValuesAtCompileTime
 { InputsAtCompileTime = NX, ValuesAtCompileTime = NY };
Constructor & Destructor Documentation
TestFunc1() [1/4]
template<typename Scalar_ , int NX = Dynamic, int NY = Dynamic> TestFunc1< Scalar_, NX, NY >::TestFunc1 () inline
 : m_inputs(InputsAtCompileTime), m_values(ValuesAtCompileTime) {}
TestFunc1() [2/4]
template<typename Scalar_ , int NX = Dynamic, int NY = Dynamic> TestFunc1< Scalar_, NX, NY >::TestFunc1 (int inputs_, int values_) inline
 : m_inputs(inputs_), m_values(values_) {}
TestFunc1() [3/4]
template<typename Scalar_ , int NX = Dynamic, int NY = Dynamic> TestFunc1< Scalar_, NX, NY >::TestFunc1 () inline
 : m_inputs(InputsAtCompileTime), m_values(ValuesAtCompileTime) {}
TestFunc1() [4/4]
template<typename Scalar_ , int NX = Dynamic, int NY = Dynamic> TestFunc1< Scalar_, NX, NY >::TestFunc1 (int inputs_, int values_) inline
 : m_inputs(inputs_), m_values(values_) {}
Member Function Documentation
inputs() [1/2]
template<typename Scalar_ , int NX = Dynamic, int NY = Dynamic> int TestFunc1< Scalar_, NX, NY >::inputs () const inline
 { return m_inputs; }
References TestFunc1< Scalar_, NX, NY >::m_inputs.
Referenced by TestFunc1< Scalar_, NX, NY >::operator()().
inputs() [2/2]
template<typename Scalar_ , int NX = Dynamic, int NY = Dynamic> int TestFunc1< Scalar_, NX, NY >::inputs () const inline
 { return m_inputs; }
References TestFunc1< Scalar_, NX, NY >::m_inputs.
operator()() [1/4]
template<typename Scalar_ , int NX = Dynamic, int NY = Dynamic> void TestFunc1< Scalar_, NX, NY >::operator() (const InputType & x, ValueType * v, JacobianType * _j) const inline
{
     (*this)(x, v);
     if (_j) {
       JacobianType& j = *_j;
       j(0, 0) = 4 * x[0] + x[1];
       j(1, 0) = 3 * x[1];
       j(0, 1) = x[0];
       j(1, 1) = 3 * x[0] + 2 * 0.5 * x[1];
       if (inputs() > 2) {
         j(0, 2) = 0.5;
         j(1, 2) = 1;
       }
       if (values() > 2) {
         j(2, 0) = 3 * x[1] * 2 * x[0];
         j(2, 1) = 3 * x[0] * x[0];
       }
       if (inputs() > 2 && values() > 2) {
         j(2, 0) *= x[2];
         j(2, 1) *= x[2];
         j(2, 2) = 3 * x[1] * x[0] * x[0];
         j(2, 2) = 3 * x[1] * x[0] * x[0];
       }
     }
   }
References TestFunc1< Scalar_, NX, NY >::inputs(), j, v, TestFunc1< Scalar_, NX, NY >::values(), and plotDoE::x.
operator()() [2/4]
template<typename Scalar_ , int NX = Dynamic, int NY = Dynamic> void TestFunc1< Scalar_, NX, NY >::operator() (const InputType & x, ValueType * v, JacobianType * _j) const inline
{
     (*this)(x, v);
     if (_j) {
       JacobianType& j = *_j;
       j(0, 0) = 4 * x[0] + x[1];
       j(1, 0) = 3 * x[1];
       j(0, 1) = x[0];
       j(1, 1) = 3 * x[0] + 2 * 0.5 * x[1];
       if (inputs() > 2) {
         j(0, 2) = 0.5;
         j(1, 2) = 1;
       }
       if (values() > 2) {
         j(2, 0) = 3 * x[1] * 2 * x[0];
         j(2, 1) = 3 * x[0] * x[0];
       }
       if (inputs() > 2 && values() > 2) {
         j(2, 0) *= x[2];
         j(2, 1) *= x[2];
         j(2, 2) = 3 * x[1] * x[0] * x[0];
         j(2, 2) = 3 * x[1] * x[0] * x[0];
       }
     }
   }
References TestFunc1< Scalar_, NX, NY >::inputs(), j, v, TestFunc1< Scalar_, NX, NY >::values(), and plotDoE::x.
operator()() [3/4]
template<typename Scalar_ , int NX = Dynamic, int NY = Dynamic> template<typename T > void TestFunc1< Scalar_, NX, NY >::operator() (const Matrix< T, InputsAtCompileTime, 1 > & x, Matrix< T, ValuesAtCompileTime, 1 > * _v) const inline
{
     Matrix<T, ValuesAtCompileTime, 1>& v = *_v;
     v[0] = 2 * x[0] * x[0] + x[0] * x[1];
     v[1] = 3 * x[1] * x[0] + 0.5 * x[1] * x[1];
     if (inputs() > 2) {
       v[0] += 0.5 * x[2];
       v[1] += x[2];
     }
     if (values() > 2) {
       v[2] = 3 * x[1] * x[0] * x[0];
     }
     if (inputs() > 2 && values() > 2) v[2] *= x[2];
   }
References TestFunc1< Scalar_, NX, NY >::inputs(), v, TestFunc1< Scalar_, NX, NY >::values(), and plotDoE::x.
operator()() [4/4]
template<typename Scalar_ , int NX = Dynamic, int NY = Dynamic> template<typename T > void TestFunc1< Scalar_, NX, NY >::operator() (const Matrix< T, InputsAtCompileTime, 1 > & x, Matrix< T, ValuesAtCompileTime, 1 > * _v) const inline
{
     Matrix<T, ValuesAtCompileTime, 1>& v = *_v;
     v[0] = 2 * x[0] * x[0] + x[0] * x[1];
     v[1] = 3 * x[1] * x[0] + 0.5 * x[1] * x[1];
     if (inputs() > 2) {
       v[0] += 0.5 * x[2];
       v[1] += x[2];
     }
     if (values() > 2) {
       v[2] = 3 * x[1] * x[0] * x[0];
     }
     if (inputs() > 2 && values() > 2) v[2] *= x[2];
   }
References TestFunc1< Scalar_, NX, NY >::inputs(), v, TestFunc1< Scalar_, NX, NY >::values(), and plotDoE::x.
values() [1/2]
template<typename Scalar_ , int NX = Dynamic, int NY = Dynamic> int TestFunc1< Scalar_, NX, NY >::values () const inline
 { return m_values; }
References TestFunc1< Scalar_, NX, NY >::m_values.
Referenced by TestFunc1< Scalar_, NX, NY >::operator()().
values() [2/2]
template<typename Scalar_ , int NX = Dynamic, int NY = Dynamic> int TestFunc1< Scalar_, NX, NY >::values () const inline
 { return m_values; }
References TestFunc1< Scalar_, NX, NY >::m_values.
Member Data Documentation
m_inputs
template<typename Scalar_ , int NX = Dynamic, int NY = Dynamic> int TestFunc1< Scalar_, NX, NY >::m_inputs
Referenced by TestFunc1< Scalar_, NX, NY >::inputs().
m_values
template<typename Scalar_ , int NX = Dynamic, int NY = Dynamic> int TestFunc1< Scalar_, NX, NY >::m_values
Referenced by TestFunc1< Scalar_, NX, NY >::values().
The documentation for this struct was generated from the following files:
autodiff.cpp
forward_adolc.cpp