MercuryDPM: Eigen::TensorEvaluator< const Derived, Device > Struct Template Reference
Eigen::TensorEvaluator< const Derived, Device > Struct Template Reference
#include <TensorEvaluator.h>
Public Types
enum { IsAligned = Derived::IsAligned , PacketAccess = (PacketType<CoeffReturnType, Device>::size > 1) , BlockAccess = internal::is_arithmetic<ScalarNoConst>::value , PreferBlockAccess = false }
typedef Derived::Index Index
typedef Derived::Scalar Scalar
typedef Derived::Scalar CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef Derived::Dimensions Dimensions
typedef const Derived XprType
typedef internal::traits< Derived >::template MakePointer< const Scalar >::Type TensorPointerType
typedef StorageMemory< const Scalar, Device > Storage
typedef Storage::Type EvaluatorPointerType
typedef std::remove_const_t< Scalar > ScalarNoConst
typedef internal::TensorBlockDescriptor< NumCoords, Index > TensorBlockDesc
typedef internal::TensorBlockScratchAllocator< Device > TensorBlockScratch
typedef internal::TensorMaterializedBlock< ScalarNoConst, NumCoords, Layout, Index > TensorBlock
Public Member Functions
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC TensorEvaluator (const Derived &m, const Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions & dimensions () const
EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (EvaluatorPointerType data)
EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType packet (Index index) const
template<typename PacketReturnTypeT >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE std::enable_if_t< internal::unpacket_traits< PacketReturnTypeT >::masked_load_available, PacketReturnTypeT > partialPacket (Index index, typename internal::unpacket_traits< PacketReturnTypeT >::mask_t umask) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (const array< DenseIndex, NumCoords > &coords) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::TensorBlockResourceRequirements getResourceRequirements () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorBlock block (TensorBlockDesc &desc, TensorBlockScratch &scratch, bool=false) const
EIGEN_DEVICE_FUNC EvaluatorPointerType data () const
Static Public Attributes
static constexpr int NumCoords
static constexpr int PacketSize = PacketType<CoeffReturnType, Device>::size
static constexpr int Layout = Derived::Layout
Protected Attributes
EvaluatorPointerType m_data
Dimensions m_dims
const Device EIGEN_DEVICE_REF m_device
Member Typedef Documentation
CoeffReturnType
template<typename Derived , typename Device > typedef Derived::Scalar Eigen::TensorEvaluator< const Derived, Device >::CoeffReturnType
Dimensions
template<typename Derived , typename Device > typedef Derived::Dimensions Eigen::TensorEvaluator< const Derived, Device >::Dimensions
EvaluatorPointerType
template<typename Derived , typename Device > typedef Storage::Type Eigen::TensorEvaluator< const Derived, Device >::EvaluatorPointerType
Index
template<typename Derived , typename Device > typedef Derived::Index Eigen::TensorEvaluator< const Derived, Device >::Index
PacketReturnType
template<typename Derived , typename Device > typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorEvaluator< const Derived, Device >::PacketReturnType
Scalar
template<typename Derived , typename Device > typedef Derived::Scalar Eigen::TensorEvaluator< const Derived, Device >::Scalar
ScalarNoConst
template<typename Derived , typename Device > typedef std::remove_const_t<Scalar> Eigen::TensorEvaluator< const Derived, Device >::ScalarNoConst
Storage
template<typename Derived , typename Device > typedef StorageMemory<const Scalar, Device> Eigen::TensorEvaluator< const Derived, Device >::Storage
TensorBlock
template<typename Derived , typename Device > typedef internal::TensorMaterializedBlock<ScalarNoConst, NumCoords, Layout, Index> Eigen::TensorEvaluator< const Derived, Device >::TensorBlock
TensorBlockDesc
template<typename Derived , typename Device > typedef internal::TensorBlockDescriptor<NumCoords, Index> Eigen::TensorEvaluator< const Derived, Device >::TensorBlockDesc
TensorBlockScratch
template<typename Derived , typename Device > typedef internal::TensorBlockScratchAllocator<Device> Eigen::TensorEvaluator< const Derived, Device >::TensorBlockScratch
TensorPointerType
template<typename Derived , typename Device > typedef internal::traits<Derived>::template MakePointer<const Scalar>::Type Eigen::TensorEvaluator< const Derived, Device >::TensorPointerType
XprType
template<typename Derived , typename Device > typedef const Derived Eigen::TensorEvaluator< const Derived, Device >::XprType
Member Enumeration Documentation
anonymous enum
template<typename Derived , typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
BlockAccess
PreferBlockAccess
        {
     IsAligned = Derived::IsAligned,
     PacketAccess = (PacketType<CoeffReturnType, Device>::size > 1),
     BlockAccess = internal::is_arithmetic<ScalarNoConst>::value,
     PreferBlockAccess = false,
     CoordAccess = NumCoords > 0,
     RawAccess = true
   };
Constructor & Destructor Documentation
TensorEvaluator()
template<typename Derived , typename Device > EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC Eigen::TensorEvaluator< const Derived, Device >::TensorEvaluator (const Derived & m, const Device & device) inline
       : m_data(device.get(m.data())), m_dims(m.dimensions()), m_device(device) {}
Member Function Documentation
block()
template<typename Derived , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorBlock Eigen::TensorEvaluator< const Derived, Device >::block (TensorBlockDesc & desc, TensorBlockScratch & scratch, bool = false) const inline
{
     eigen_assert(m_data != NULL);
     return TensorBlock::materialize(m_data, m_dims, desc, scratch);
   }
References eigen_assert, Eigen::TensorEvaluator< Derived, Device >::m_data, Eigen::TensorEvaluator< Derived, Device >::m_dims, and Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::materialize().
cleanup()
template<typename Derived , typename Device > EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const Derived, Device >::cleanup () inline
 {}
Referenced by framework.Frame::__init__().
coeff() [1/2]
template<typename Derived , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::TensorEvaluator< const Derived, Device >::coeff (const array< DenseIndex, NumCoords > & coords) const inline
{
     eigen_assert(m_data != NULL);
     const Index index = (static_cast<int>(Layout) == static_cast<int>(ColMajor)) ? m_dims.IndexOfColMajor(coords)
                                                                                  : m_dims.IndexOfRowMajor(coords);
     return internal::loadConstant(m_data + index);
   }
References Eigen::ColMajor, eigen_assert, Eigen::TensorEvaluator< Derived, Device >::Layout, Eigen::internal::loadConstant(), Eigen::TensorEvaluator< Derived, Device >::m_data, and Eigen::TensorEvaluator< Derived, Device >::m_dims.
coeff() [2/2]
template<typename Derived , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::TensorEvaluator< const Derived, Device >::coeff (Index index) const inline
{
     eigen_assert(m_data != NULL);
     return internal::loadConstant(m_data + index);
   }
References eigen_assert, Eigen::internal::loadConstant(), and Eigen::TensorEvaluator< Derived, Device >::m_data.
costPerCoeff()
template<typename Derived , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorEvaluator< const Derived, Device >::costPerCoeff (bool vectorized) const inline
{
     return TensorOpCost(sizeof(CoeffReturnType), 0, 0, vectorized, PacketType<CoeffReturnType, Device>::size);
   }
data()
template<typename Derived , typename Device > EIGEN_DEVICE_FUNC EvaluatorPointerType Eigen::TensorEvaluator< const Derived, Device >::data () const inline
 { return m_data; }
References Eigen::TensorEvaluator< Derived, Device >::m_data.
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
dimensions()
template<typename Derived , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions& Eigen::TensorEvaluator< const Derived, Device >::dimensions () const inline
 { return m_dims; }
References Eigen::TensorEvaluator< Derived, Device >::m_dims.
evalSubExprsIfNeeded()
template<typename Derived , typename Device > EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const Derived, Device >::evalSubExprsIfNeeded (EvaluatorPointerType data) inline
{
     if (!NumTraits<std::remove_const_t<Scalar>>::RequireInitialization && data) {
       m_device.memcpy((void*)(m_device.get(data)), m_device.get(m_data), m_dims.TotalSize() * sizeof(Scalar));
       return false;
     }
     return true;
   }
References Eigen::TensorEvaluator< Derived, Device >::data(), Eigen::TensorEvaluator< Derived, Device >::m_data, Eigen::TensorEvaluator< Derived, Device >::m_device, and Eigen::TensorEvaluator< Derived, Device >::m_dims.
getResourceRequirements()
template<typename Derived , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::TensorBlockResourceRequirements Eigen::TensorEvaluator< const Derived, Device >::getResourceRequirements () const inline
{
     return internal::TensorBlockResourceRequirements::any();
   }
References Eigen::internal::TensorBlockResourceRequirements::any().
packet()
template<typename Derived , typename Device > template<int LoadMode> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType Eigen::TensorEvaluator< const Derived, Device >::packet (Index index) const inline
{
     return internal::ploadt_ro<PacketReturnType, LoadMode>(m_data + index);
   }
References Eigen::TensorEvaluator< Derived, Device >::m_data.
partialPacket()
template<typename Derived , typename Device > template<typename PacketReturnTypeT > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE std::enable_if_t<internal::unpacket_traits<PacketReturnTypeT>::masked_load_available, PacketReturnTypeT> Eigen::TensorEvaluator< const Derived, Device >::partialPacket (Index index, typename internal::unpacket_traits< PacketReturnTypeT >::mask_t umask) const inline
{
     return internal::ploadu<PacketReturnTypeT>(m_data + index, umask);
   }
References Eigen::TensorEvaluator< Derived, Device >::m_data.
Member Data Documentation
Layout
template<typename Derived , typename Device > constexpr int Eigen::TensorEvaluator< const Derived, Device >::Layout = Derived::Layout static constexpr
m_data
template<typename Derived , typename Device > EvaluatorPointerType Eigen::TensorEvaluator< const Derived, Device >::m_data protected
m_device
template<typename Derived , typename Device > const Device EIGEN_DEVICE_REF Eigen::TensorEvaluator< const Derived, Device >::m_device protected
m_dims
template<typename Derived , typename Device > Dimensions Eigen::TensorEvaluator< const Derived, Device >::m_dims protected
NumCoords
template<typename Derived , typename Device > constexpr int Eigen::TensorEvaluator< const Derived, Device >::NumCoords static constexpr
Initial value:
=
      internal::traits<Derived>::NumDimensions > 0 ? internal::traits<Derived>::NumDimensions : 0
PacketSize
template<typename Derived , typename Device > constexpr int Eigen::TensorEvaluator< const Derived, Device >::PacketSize = PacketType<CoeffReturnType, Device>::size static constexpr
The documentation for this struct was generated from the following file:
TensorEvaluator.h