MercuryDPM: NurbsWallSelfTest.cpp File Reference
NurbsWallSelfTest.cpp File Reference
#include "Nurbs/NurbsSurface.h"
#include "Walls/NurbsWall.h"
#include "Walls/InfiniteWall.h"
#include "Math/Helpers.h"
#include <sstream>
#include <DPMBase.h>
#include <Interactions/NormalForceInteractions/LinearViscoelasticInteraction.h>
#include <Species/LinearViscoelasticSpecies.h>
Functions
int main ()
Function Documentation
main()
int main ()
Tests if contact with nurbs surface is correctly implemented. The setup consists of five particles and two walls, on of which is a NurbsWall. The particles fall downwards by gravity, filling the space between the two walls.
 {
     //define quarter circle as nurbs surface
     std::vector<double> knotsU = {0,0,0,1,1,1};
     std::vector<double> knotsV = {0,0,1,1};
     std::vector<std::vector<Vec3D>> controlPoints = {{{1,0,0},{1,0,2}},{{1,1,0},{1,1,2}},{{0,1,0},{0,1,2}}};
     std::vector<std::vector<Mdouble>> weights = {{1,1},{1,1},{2,2}};
     NurbsSurface nurbsSurface(knotsU,knotsV,controlPoints,weights);
     //nurbsSurface.flipOrientation();
     //create a basic dpm class
     DPMBase dpm;
     dpm.setName("NurbsWallSelfTest");
     dpm.setGravity({0,0,-1});
     auto s = dpm.speciesHandler.copyAndAddObject(LinearViscoelasticSpecies());
     s->setCollisionTimeAndRestitutionCoefficient(.05,.1,s->getMassFromRadius(0.1));
     //define nurbs wall and add to dpm class
     NurbsWall nurbsWall;
     nurbsWall.setSpecies(s);
     nurbsWall.set(nurbsSurface);
     nurbsWall.setOrientationViaNormal({0,0,1});
     nurbsWall.setPosition({1,0,0});
     dpm.wallHandler.copyAndAddObject(nurbsWall);
     InfiniteWall infiniteWall;
     infiniteWall.setSpecies(s);
     infiniteWall.set({0,1,0},{1,1,1});
     dpm.wallHandler.copyAndAddObject(infiniteWall);
     SphericalParticle particle;
     particle.setSpecies(s);
     particle.setRadius(.1);
     for (double x=0; x<=0; x+=.2) {
         for (double y = .1; y <= .9; y += .2) {
             for (double z = 1.1; z <= 1.1; z += .2) {
                 particle.setPosition({x, y, z});
                 dpm.particleHandler.copyAndAddObject(particle);
             }
         }
     }
     dpm.wallHandler.setWriteVTK(FileType::ONE_FILE);
     dpm.setParticlesWriteVTK(true);
     dpm.setTimeStep(0.001);
     dpm.setTimeMax(2.0);
     dpm.setSaveCount(100);
     dpm.setDomain({-1,0,0},{1,1,1});
     dpm.solve();
     return 0;
 }
References BaseHandler< T >::copyAndAddObject(), ONE_FILE, DPMBase::particleHandler, s, NurbsWall::set(), InfiniteWall::set(), DPMBase::setDomain(), DPMBase::setGravity(), DPMBase::setName(), BaseInteractable::setOrientationViaNormal(), DPMBase::setParticlesWriteVTK(), BaseInteractable::setPosition(), BaseParticle::setRadius(), DPMBase::setSaveCount(), BaseParticle::setSpecies(), BaseWall::setSpecies(), DPMBase::setTimeMax(), DPMBase::setTimeStep(), WallHandler::setWriteVTK(), DPMBase::solve(), DPMBase::speciesHandler, DPMBase::wallHandler, calibrate::weights, plotDoE::x, and y.