MercuryDPM: AxisymmetricHopperSelfTest.cpp File Reference
AxisymmetricHopperSelfTest.cpp File Reference
#include "AxisymmetricHopper.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
A three-dimensional, axisymmetric hopper.
 {
     //Print description
     logger(INFO, "\nDescription: A quasi-2D inclined plane with inflow "
                  "conditions on the left boundary, and deletion of particles when "
                  "they exit the domain.");
     // Problem parameters
     AxisymmetricHopper axisymmetricHopper;
     axisymmetricHopper.setName("AxisymmetricHopperSelfTest");
     axisymmetricHopper.setTimeMax(
             std::sqrt(6.0 * axisymmetricHopper.getZMax())); //let the particles fall to at most 16 times the domain size
     // Particle properties
     axisymmetricHopper.setFixedParticleRadius(0);
     axisymmetricHopper.setInflowParticleRadius(0.5);
     // Chute properties
     axisymmetricHopper.setChuteAngleAndMagnitudeOfGravity(0.0,1.0);
     //Output parameters
     axisymmetricHopper.setLastSavedTimeStep(1);
     axisymmetricHopper.fStatFile.setFileType(FileType::NO_FILE);
     axisymmetricHopper.setXBallsAdditionalArguments("-sort -v0 -solidf");
     //solve
     axisymmetricHopper.solve(argc,argv);
 }
References DPMBase::fStatFile, DPMBase::getZMax(), INFO, logger, NO_FILE, Chute::setChuteAngleAndMagnitudeOfGravity(), File::setFileType(), Chute::setFixedParticleRadius(), Chute::setInflowParticleRadius(), DPMBase::setLastSavedTimeStep(), DPMBase::setName(), DPMBase::setTimeMax(), DPMBase::setXBallsAdditionalArguments(), DPMBase::solve(), and sqrt().