MercuryDPM: BaseNormalForce Class Reference
BaseNormalForce Class Reference
#include <BaseNormalForce.h>
Public Member Functions
BaseNormalForce ()
BaseNormalForce (const BaseNormalForce &p)
bool getConstantRestitution () const
void setConstantRestitution (bool constantRestitution)
virtual void actionsAfterTimeStep (BaseParticle *particle) const
Public Member Functions inherited from BaseForce
BaseSpecies * getBaseSpecies () const
void setBaseSpecies (BaseSpecies *baseSpecies)
Private Attributes
bool constantRestitution_
Constructor & Destructor Documentation
BaseNormalForce() [1/2]
BaseNormalForce::BaseNormalForce () inline
                       {
         constantRestitution_ = false;
     }
References constantRestitution_.
BaseNormalForce() [2/2]
BaseNormalForce::BaseNormalForce (const BaseNormalForce & p) inline
{
         constantRestitution_ = p.constantRestitution_;
     }
References constantRestitution_, and p.
Member Function Documentation
actionsAfterTimeStep()
virtual void BaseNormalForce::actionsAfterTimeStep (BaseParticle * particle) const inline virtual
Reimplemented in Species< LinearViscoelasticNormalSpecies >, Species< LinearViscoelasticNormalSpecies, FrictionSpecies >, Species< LinearPlasticViscoelasticNormalSpecies, SlidingFrictionSpecies, IrreversibleAdhesiveSpecies >, and Species< LinearViscoelasticNormalSpecies, SlidingFrictionSpecies, IrreversibleAdhesiveSpecies >.
 {};
getConstantRestitution()
bool BaseNormalForce::getConstantRestitution () const inline
Accesses constantRestitution_.
{
         return constantRestitution_;
     }
References constantRestitution_.
Referenced by LinearPlasticViscoelasticNormalSpecies::computeBondNumberMax(), LinearPlasticViscoelasticInteraction::computeNormalForce(), LinearViscoelasticInteraction::computeNormalForce(), LinearPlasticViscoelasticNormalSpecies::computeTimeStep(), SinterLinNormalSpecies::computeTimeStep(), LinearPlasticViscoelasticNormalSpecies::getCollisionTime(), LinearViscoelasticNormalSpecies::getCollisionTime(), LinearPlasticViscoelasticInteraction::getElasticEnergy(), LinearViscoelasticInteraction::getElasticEnergy(), SinterLinInteraction::getElasticEnergy(), LinearPlasticViscoelasticNormalSpecies::getRestitutionCoefficient(), LinearViscoelasticNormalSpecies::getRestitutionCoefficient(), SinterLinNormalSpecies::getRestitutionCoefficient(), LinearPlasticViscoelasticNormalSpecies::setCollisionTimeAndRestitutionCoefficient(), LinearViscoelasticNormalSpecies::setCollisionTimeAndRestitutionCoefficient(), LinearPlasticViscoelasticNormalSpecies::setRestitutionCoefficient(), LinearViscoelasticNormalSpecies::setRestitutionCoefficient(), SinterLinNormalSpecies::setRestitutionCoefficient(), LinearPlasticViscoelasticNormalSpecies::setStiffnessAndRestitutionCoefficient(), LinearViscoelasticNormalSpecies::setStiffnessAndRestitutionCoefficient(), and BaseSpecies::write().
setConstantRestitution()
void BaseNormalForce::setConstantRestitution (bool constantRestitution)
Sets constantRestitution_.
{
         constantRestitution_ = constantRestitution;
         if (constantRestitution) {
             logger(INFO,"You are using a constant restitution contact model; make sure you understand the implications this has on the stiffness and dissipation used by the contact model!");
         }
         //if use setCollisionTime or setRestitutionCoefficient to set the parameters of your contact model, then these functions should be called AFTER calling setConstantRestitution.
         //For more info, see http://docs.mercurydpm.org/Trunk/d0/db6/ConstantRestitution.html
 }
References constantRestitution_, INFO, and logger.
Referenced by BaseSpecies::read().
Member Data Documentation
constantRestitution_
bool BaseNormalForce::constantRestitution_ private
If constantRestitution_ is true, the elastic and dissipative force is multiplied by the harmonic mean mass, making restitution and collision time independent of the particle mass. This is set to false by default.
Referenced by BaseNormalForce(), getConstantRestitution(), and setConstantRestitution().
The documentation for this class was generated from the following files:
BaseNormalForce.h
BaseNormalForce.cc