MercuryDPM: PSDConversionUnitTest.cpp File Reference
PSDConversionUnitTest.cpp File Reference
#include "Math/PSD.h"
Functions
std::string getPSDTypeName (PSD::TYPE psdType)
bool isEqual (const std::vector< DistributionElements > &l, const std::vector< DistributionElements > &r)
void testPSD (PSD::TYPE psdType)
Sets a PSD by vector with a given type and gets the PSD vector back by the same type to confirm it's the same.
void runTest ()
int main ()
Function Documentation
getPSDTypeName()
std::string getPSDTypeName (PSD::TYPE psdType)
 {
     if (psdType == PSD::TYPE::CUMULATIVE_NUMBER_DISTRIBUTION)
         return "CUMULATIVE_NUMBER_DISTRIBUTION";
     else if (psdType == PSD::TYPE::CUMULATIVE_LENGTH_DISTRIBUTION)
         return "CUMULATIVE_LENGTH_DISTRIBUTION";
     else if (psdType == PSD::TYPE::CUMULATIVE_AREA_DISTRIBUTION)
         return "CUMULATIVE_AREA_DISTRIBUTION";
     else if (psdType == PSD::TYPE::CUMULATIVE_VOLUME_DISTRIBUTION)
         return "CUMULATIVE_VOLUME_DISTRIBUTION";
     else if (psdType == PSD::TYPE::PROBABILITYDENSITY_NUMBER_DISTRIBUTION)
         return "PROBABILITYDENSITY_NUMBER_DISTRIBUTION";
     else if (psdType == PSD::TYPE::PROBABILITYDENSITY_LENGTH_DISTRIBUTION)
         return "PROBABILITYDENSITY_LENGTH_DISTRIBUTION";
     else if (psdType == PSD::TYPE::PROBABILITYDENSITY_AREA_DISTRIBUTION)
         return "PROBABILITYDENSITY_AREA_DISTRIBUTION";
     else if (psdType == PSD::TYPE::PROBABILITYDENSITY_VOLUME_DISTRIBUTION)
         return "PROBABILITYDENSITY_VOLUME_DISTRIBUTION";
     else
         logger(ERROR, "Unknown PSD type");
     return "";
 }
References PSD::CUMULATIVE_AREA_DISTRIBUTION, PSD::CUMULATIVE_LENGTH_DISTRIBUTION, PSD::CUMULATIVE_NUMBER_DISTRIBUTION, PSD::CUMULATIVE_VOLUME_DISTRIBUTION, ERROR, logger, PSD::PROBABILITYDENSITY_AREA_DISTRIBUTION, PSD::PROBABILITYDENSITY_LENGTH_DISTRIBUTION, PSD::PROBABILITYDENSITY_NUMBER_DISTRIBUTION, and PSD::PROBABILITYDENSITY_VOLUME_DISTRIBUTION.
Referenced by testPSD().
isEqual()
bool isEqual (const std::vector< DistributionElements > & l, const std::vector< DistributionElements > & r)
 {
     if (l.size() != r.size())
         return false;
     Mdouble tol = 1.0e-15;
     for (int i = 0; i < l.size(); i++)
         if (std::fabs(l[i].internalVariable - r[i].internalVariable) > tol || std::fabs(l[i].probability - r[i].probability) > tol)
             return false;
     return true;
 }
References boost::multiprecision::fabs(), i, and UniformPSDSelfTest::r.
Referenced by mathsFunc::isEqual(), main(), and testPSD().
main()
int main ()
 {
     runTest();
 }
References runTest().
runTest()
void runTest ()
 {
     testPSD(PSD::TYPE::CUMULATIVE_NUMBER_DISTRIBUTION);
     testPSD(PSD::TYPE::CUMULATIVE_LENGTH_DISTRIBUTION);
     testPSD(PSD::TYPE::CUMULATIVE_AREA_DISTRIBUTION);
     testPSD(PSD::TYPE::CUMULATIVE_VOLUME_DISTRIBUTION);
     testPSD(PSD::TYPE::PROBABILITYDENSITY_NUMBER_DISTRIBUTION);
     testPSD(PSD::TYPE::PROBABILITYDENSITY_LENGTH_DISTRIBUTION);
     testPSD(PSD::TYPE::PROBABILITYDENSITY_AREA_DISTRIBUTION);
     testPSD(PSD::TYPE::PROBABILITYDENSITY_VOLUME_DISTRIBUTION);
 }
References PSD::CUMULATIVE_AREA_DISTRIBUTION, PSD::CUMULATIVE_LENGTH_DISTRIBUTION, PSD::CUMULATIVE_NUMBER_DISTRIBUTION, PSD::CUMULATIVE_VOLUME_DISTRIBUTION, PSD::PROBABILITYDENSITY_AREA_DISTRIBUTION, PSD::PROBABILITYDENSITY_LENGTH_DISTRIBUTION, PSD::PROBABILITYDENSITY_NUMBER_DISTRIBUTION, PSD::PROBABILITYDENSITY_VOLUME_DISTRIBUTION, and testPSD().
Referenced by main().
testPSD()
void testPSD (PSD::TYPE psdType)
Sets a PSD by vector with a given type and gets the PSD vector back by the same type to confirm it's the same.
The PSD class internally converts any PSD type to CUMULATIVE_NUMBER_DISTRIBUTION. It is also possible to get the PSD vector by any type, where internally it is converted back from CUMULATIVE_NUMBER_DISTRIBUTION. Doing this for the same type should of course give the same PSD vector back, provided the PSD vector was perfect to start with, so that internal validation didn't alter it in any way.
Note
This merely checks if converting to and converting back from CUMULATIVE_NUMBER_DISTRIBUTION will yield the same PSD vector. It does not check for the correctness of the conversions itself. It is therefore possible that forwards and backwards conversion both contain the same but opposite mistake. This test would then still pass.
Parameters
psdType The PSD type the test.
 {
     // Set a default PSD vector, differentiating between cumulative and probability density.
     // Note: it is important that this is a proper normalised PSD vector, so that the PSD class does not alter it in any
     // way when validating it. Because then converting back would result in a different PSD vector.
     std::vector<DistributionElements> psdVector;
     switch (psdType)
     {
         case PSD::TYPE::CUMULATIVE_NUMBER_DISTRIBUTION:
         case PSD::TYPE::CUMULATIVE_LENGTH_DISTRIBUTION:
         case PSD::TYPE::CUMULATIVE_AREA_DISTRIBUTION:
         case PSD::TYPE::CUMULATIVE_VOLUME_DISTRIBUTION:
             psdVector = { {1.0, 0.0}, {2.0, 0.5}, {3.0, 0.6}, {4.0, 1.0} };
             break;
         case PSD::TYPE::PROBABILITYDENSITY_NUMBER_DISTRIBUTION:
         case PSD::TYPE::PROBABILITYDENSITY_LENGTH_DISTRIBUTION:
         case PSD::TYPE::PROBABILITYDENSITY_AREA_DISTRIBUTION:
         case PSD::TYPE::PROBABILITYDENSITY_VOLUME_DISTRIBUTION:
             psdVector = { {1.0, 0.0}, {2.0, 0.5}, {3.0, 0.1}, {4.0, 0.4} };
             break;
         default:
             logger(ERROR, "Unknown PSD type");
     }
     PSD psd;
     // Set the PSD by the correct type (internally converted to CUMULATIVE_NUMBER_DISTRIBUTION).
     psd.setPSDFromVector(psdVector, psdType);
     // Get the PSD vector by the same type (internally converted from CUMULATIVE_NUMBER_DISTRIBUTION).
     std::vector<DistributionElements> psdVectorBack = psd.getParticleSizeDistributionByType(psdType);
     // The original and converted back PSD vectors should be equal.
     logger.assert_always(isEqual(psdVector, psdVectorBack), "Original and converted back PSD vectors of PSD type % are not equal!", getPSDTypeName(psdType));
 }
References PSD::CUMULATIVE_AREA_DISTRIBUTION, PSD::CUMULATIVE_LENGTH_DISTRIBUTION, PSD::CUMULATIVE_NUMBER_DISTRIBUTION, PSD::CUMULATIVE_VOLUME_DISTRIBUTION, ERROR, PSD::getParticleSizeDistributionByType(), getPSDTypeName(), isEqual(), logger, PSD::PROBABILITYDENSITY_AREA_DISTRIBUTION, PSD::PROBABILITYDENSITY_LENGTH_DISTRIBUTION, PSD::PROBABILITYDENSITY_NUMBER_DISTRIBUTION, PSD::PROBABILITYDENSITY_VOLUME_DISTRIBUTION, and PSD::setPSDFromVector().
Referenced by runTest().