MercuryDPM: oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement Class Reference
oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement Class Reference
#include <axisym_buoyant_navier_stokes.h>
Public Member Functions
RefineableBuoyantQAxisymCrouzeixRaviartElement ()
unsigned required_nvalue (const unsigned &n) const
const double & ra () const
Access function for the Rayleigh number (const version)
double *& ra_pt ()
Access function for the pointer to the Rayleigh number.
void disable_ALE ()
Final override for disable ALE.
void enable_ALE ()
Final override for enable ALE.
unsigned nscalar_paraview () const
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
std::string scalar_name_paraview (const unsigned &i) const
void output (std::ostream &outfile)
Overload the standard output function with the broken default.
void output (std::ostream &outfile, const unsigned &nplot)
void output (FILE *file_pt)
C-style output function: Broken default.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: Broken default.
void output_fct (std::ostream &outfile, const unsigned &Nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for an exact solution: Broken default.
void output_fct (std::ostream &outfile, const unsigned &Nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
unsigned u_index_axi_adv_diff () const
unsigned nvertex_node () const
Node * vertex_node_pt (const unsigned &j) const
unsigned ncont_interpolated_values () const
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
void further_setup_hanging_nodes ()
void rebuild_from_sons (Mesh *&mesh_pt)
double geometric_jacobian (const Vector< double > &x)
Fill in the geometric Jacobian, which in this case is r.
void further_build ()
unsigned nrecovery_order ()
The recovery order is that of the NavierStokes elements.
unsigned num_Z2_flux_terms ()
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
unsigned ncompound_fluxes ()
void get_Z2_compound_flux_indices (Vector< unsigned > &flux_index)
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
void get_wind_axi_adv_diff (const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &wind) const
void get_body_force_axi_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &result)
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Fill in the constituent elements' contribution to the residual vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
void fill_in_off_diagonal_jacobian_blocks_analytic (Vector< double > &residuals, DenseMatrix< double > &jacobian)
RefineableBuoyantQAxisymCrouzeixRaviartElement ()
unsigned required_nvalue (const unsigned &n) const
const double & ra () const
Access function for the Rayleigh number (const version)
double *& ra_pt ()
Access function for the pointer to the Rayleigh number.
void disable_ALE ()
Final override for disable ALE.
void enable_ALE ()
Final override for enable ALE.
unsigned nscalar_paraview () const
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
std::string scalar_name_paraview (const unsigned &i) const
void output (std::ostream &outfile)
Overload the standard output function with the broken default.
void output (std::ostream &outfile, const unsigned &nplot)
void output (FILE *file_pt)
C-style output function: Broken default.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: Broken default.
void output_fct (std::ostream &outfile, const unsigned &Nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for an exact solution: Broken default.
void output_fct (std::ostream &outfile, const unsigned &Nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
unsigned u_index_axi_adv_diff () const
unsigned nvertex_node () const
Node * vertex_node_pt (const unsigned &j) const
unsigned ncont_interpolated_values () const
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
void further_setup_hanging_nodes ()
void rebuild_from_sons (Mesh *&mesh_pt)
double geometric_jacobian (const Vector< double > &x)
Fill in the geometric Jacobian, which in this case is r.
void further_build ()
unsigned nrecovery_order ()
The recovery order is that of the NavierStokes elements.
unsigned num_Z2_flux_terms ()
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
unsigned ncompound_fluxes ()
void get_Z2_compound_flux_indices (Vector< unsigned > &flux_index)
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
void get_wind_axi_adv_diff (const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &wind) const
void get_body_force_axi_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &result)
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Fill in the constituent elements' contribution to the residual vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
void fill_in_off_diagonal_jacobian_blocks_analytic (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Public Member Functions inherited from oomph::RefineableQAxisymAdvectionDiffusionElement< 3 >
RefineableQAxisymAdvectionDiffusionElement ()
Empty Constructor:
RefineableQAxisymAdvectionDiffusionElement (const RefineableQAxisymAdvectionDiffusionElement< NNODE_1D > &dummy)=delete
Broken copy constructor.
unsigned ncont_interpolated_values () const
Broken assignment operator.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
void rebuild_from_sons (Mesh *&mesh_pt)
Rebuild from sons: empty.
unsigned nrecovery_order ()
void further_setup_hanging_nodes ()
Public Member Functions inherited from oomph::QAxisymAdvectionDiffusionElement< NNODE_1D >
QAxisymAdvectionDiffusionElement ()
QAxisymAdvectionDiffusionElement (const QAxisymAdvectionDiffusionElement< NNODE_1D > &dummy)=delete
Broken copy constructor.
unsigned required_nvalue (const unsigned &n) const
Broken assignment operator.
void output (std::ostream &outfile)
void output (std::ostream &outfile, const unsigned &n_plot)
void output (FILE *file_pt)
void output (FILE *file_pt, const unsigned &n_plot)
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Public Member Functions inherited from oomph::QElement< 2, NNODE_1D >
QElement ()
Constructor.
QElement (const QElement &)=delete
Broken copy constructor.
void shape (const Vector< double > &s, Shape &psi) const
Broken assignment operator.
void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
Derivatives of shape functions for specific QElement<2,..>
void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double s_min () const
Min. value of local coordinate.
double s_max () const
Max. value of local coordinate.
void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
Get local coordinates of node j in the element; vector sets its own size.
void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
Get the local fraction of node j in the element.
double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
Node * get_node_at_local_coordinate (const Vector< double > &s) const
Get the node at the specified local coordinate.
unsigned nnode_1d () const
Number of nodes along each element edge.
unsigned nplot_points_paraview (const unsigned &nplot) const
unsigned nsub_elements_paraview (const unsigned &nplot) const
void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
void output (std::ostream &outfile)
Output.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at n_plot points.
void output (FILE *file_pt)
C-style output.
void output (FILE *file_pt, const unsigned &n_plot)
C_style output at n_plot points.
void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &use_equally_spaced_interior_sample_points=false) const
std::string tecplot_zone_string (const unsigned &nplot) const
unsigned nplot_points (const unsigned &nplot) const
unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::QuadElementBase
QuadElementBase ()
Constructor. Empty.
Public Member Functions inherited from oomph::QElementBase
QElementBase ()
Constructor: Initialise pointers to macro element reference coords.
QElementBase (const QElementBase &)=delete
Broken copy constructor.
virtual ~QElementBase ()
Broken assignment operator.
bool local_coord_is_valid (const Vector< double > &s)
Check whether the local coordinate are valid or not.
void move_local_coord_back_into_element (Vector< double > &s) const
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
double & s_macro_ll (const unsigned &i)
double & s_macro_ur (const unsigned &i)
double s_macro_ll (const unsigned &i) const
double s_macro_ur (const unsigned &i) const
void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
unsigned nnode_on_face () const
ElementGeometry::ElementGeometry element_geometry () const
It's a Q element!
Public Member Functions inherited from oomph::QElementGeometricBase
QElementGeometricBase ()
Empty default constructor.
QElementGeometricBase (const QElementGeometricBase &)=delete
Broken copy constructor.
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
double size () const
void point_output (std::ostream &outfile, const Vector< double > &s)
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::AxisymAdvectionDiffusionEquations
AxisymAdvectionDiffusionEquations ()
AxisymAdvectionDiffusionEquations (const AxisymAdvectionDiffusionEquations &dummy)=delete
Broken copy constructor.
double du_dt_axi_adv_diff (const unsigned &n) const
void disable_ALE ()
void enable_ALE ()
unsigned nscalar_paraview () const
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
std::string scalar_name_paraview (const unsigned &i) const
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Get error against and norm of exact solution.
AxisymAdvectionDiffusionSourceFctPt & source_fct_pt ()
Access function: Pointer to source function.
AxisymAdvectionDiffusionSourceFctPt source_fct_pt () const
Access function: Pointer to source function. Const version.
AxisymAdvectionDiffusionWindFctPt & wind_fct_pt ()
Access function: Pointer to wind function.
AxisymAdvectionDiffusionWindFctPt wind_fct_pt () const
Access function: Pointer to wind function. Const version.
const double & pe () const
Peclet number.
double *& pe_pt ()
Pointer to Peclet number.
const double & pe_st () const
Peclet number multiplied by Strouhal number.
double *& pe_st_pt ()
Pointer to Peclet number multipled by Strouha number.
const double & d () const
Peclet number multiplied by Strouhal number.
double *& d_pt ()
Pointer to Peclet number multipled by Strouha number.
virtual void get_source_axi_adv_diff (const unsigned &ipt, const Vector< double > &x, double &source) const
void get_flux (const Vector< double > &s, Vector< double > &flux) const
Get flux: [du/dr,du/dz].
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector (wrapper)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
double interpolated_u_axi_adv_diff (const Vector< double > &s) const
Return FE representation of function value u(s) at local coordinate s.
virtual void dinterpolated_u_axi_adv_diff_ddata (const Vector< double > &s, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
unsigned self_test ()
Self-test: Return 0 for OK.
Public Member Functions inherited from oomph::RefineableAxisymAdvectionDiffusionEquations
RefineableAxisymAdvectionDiffusionEquations ()
Empty Constructor.
RefineableAxisymAdvectionDiffusionEquations (const RefineableAxisymAdvectionDiffusionEquations &dummy)=delete
Broken copy constructor.
unsigned num_Z2_flux_terms ()
Broken assignment operator.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
double geometric_jacobian (const Vector< double > &x)
Fill in the geometric Jacobian, which in this case is r.
void further_build ()
Further build: Copy source function pointer from father element.
void dinterpolated_u_adv_diff_ddata (const Vector< double > &s, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
Public Member Functions inherited from oomph::RefineableElement
RefineableElement ()
virtual ~RefineableElement ()
Destructor, delete the allocated storage for the hanging equations.
RefineableElement (const RefineableElement &)=delete
Broken copy constructor.
void operator= (const RefineableElement &)=delete
Broken assignment operator.
Tree * tree_pt ()
Access function: Pointer to quadtree representation of this element.
void set_tree_pt (Tree *my_tree_pt)
Set pointer to quadtree representation of this element.
bool refinement_is_enabled ()
Flag to indicate suppression of any refinement.
void disable_refinement ()
Suppress of any refinement for this element.
void enable_refinement ()
Emnable refinement for this element.
template<class ELEMENT >
void split (Vector< ELEMENT * > &son_pt) const
int local_hang_eqn (Node *const &node_pt, const unsigned &i)
void set_refinement_level (const int &refine_level)
Set the refinement level.
unsigned refinement_level () const
Return the Refinement level.
void select_for_refinement ()
Select the element for refinement.
void deselect_for_refinement ()
Deselect the element for refinement.
void select_sons_for_unrefinement ()
Unrefinement will be performed by merging the four sons of this element.
void deselect_sons_for_unrefinement ()
bool to_be_refined ()
Has the element been selected for refinement?
bool sons_to_be_unrefined ()
Has the element been selected for unrefinement?
virtual void unbuild ()
virtual void deactivate_element ()
virtual bool nodes_built ()
Return true if all the nodes have been built, false if not.
long number () const
Element number (for debugging/plotting)
void set_number (const long &mynumber)
Set element number (for debugging/plotting)
virtual Node * interpolating_node_pt (const unsigned &n, const int &value_id)
virtual double local_one_d_fraction_of_interpolating_node (const unsigned &n1d, const unsigned &i, const int &value_id)
virtual Node * get_interpolating_node_at_local_coordinate (const Vector< double > &s, const int &value_id)
virtual unsigned ninterpolating_node (const int &value_id)
virtual unsigned ninterpolating_node_1d (const int &value_id)
virtual void interpolating_basis (const Vector< double > &s, Shape &psi, const int &value_id) const
void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual RefineableElement * root_element_pt ()
virtual RefineableElement * father_element_pt () const
Return a pointer to the father element.
void get_father_at_refinement_level (unsigned &refinement_level, RefineableElement *&father_at_reflevel_pt)
virtual void initial_setup (Tree *const &adopted_father_pt=0, const unsigned &initial_p_order=0)
virtual void pre_build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt)
Pre-build the element.
void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
unsigned nshape_controlling_nodes ()
std::map< Node *, unsigned > shape_controlling_node_lookup ()
Public Member Functions inherited from oomph::ElementWithZ2ErrorEstimator
ElementWithZ2ErrorEstimator ()
Default empty constructor.
ElementWithZ2ErrorEstimator (const ElementWithZ2ErrorEstimator &)=delete
Broken copy constructor.
void operator= (const ElementWithZ2ErrorEstimator &)=delete
Broken assignment operator.
virtual void compute_exact_Z2_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_flux_pt, double &error, double &norm)
Public Member Functions inherited from oomph::RefineableQElement< 2 >
RefineableQElement ()
Constructor: Pass refinement level (default 0 = root)
RefineableQElement (const RefineableQElement< 2 > &dummy)=delete
Broken copy constructor.
virtual ~RefineableQElement ()
Broken assignment operator.
unsigned required_nsons () const
A refineable quad element has four sons.
virtual Node * node_created_by_neighbour (const Vector< double > &s_fraction, bool &is_periodic)
virtual Node * node_created_by_son_of_neighbour (const Vector< double > &s_fraction, bool &is_periodic)
virtual void build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt, bool &was_already_built, std::ofstream &new_nodes_file)
void check_integrity (double &max_error)
void output_corners (std::ostream &outfile, const std::string &colour) const
Print corner nodes, use colour.
QuadTree * quadtree_pt ()
Pointer to quadtree representation of this element.
QuadTree * quadtree_pt () const
Pointer to quadtree representation of this element.
void setup_hanging_nodes (Vector< std::ofstream * > &output_stream)
void get_boundaries (const int &edge, std::set< unsigned > &boundaries) const
void get_bcs (int bound, Vector< int > &bound_cons) const
void interpolated_zeta_on_edge (const unsigned &boundary, const int &edge, const Vector< double > &s, Vector< double > &zeta)
Public Member Functions inherited from oomph::RefineableAxisymmetricQCrouzeixRaviartElement
RefineableAxisymmetricQCrouzeixRaviartElement ()
Constructor:
unsigned ncont_interpolated_values () const
Number of continuously interpolated values: 3 (velocities)
void rebuild_from_sons (Mesh *&mesh_pt)
Rebuild from sons: Reconstruct pressure from the (merged) sons.
unsigned nrecovery_order ()
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
void further_setup_hanging_nodes ()
void further_build ()
Public Member Functions inherited from oomph::AxisymmetricQCrouzeixRaviartElement
AxisymmetricQCrouzeixRaviartElement ()
Constructor, there are three internal values (for the pressure)
double p_axi_nst (const unsigned &i) const
unsigned npres_axi_nst () const
Return number of pressure values.
void fix_pressure (const unsigned &p_dof, const double &pvalue)
Function to fix the internal pressure dof idof_internal.
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction) const
Compute traction at local coordinate s for outer unit normal N.
int p_local_eqn (const unsigned &n) const
void output (std::ostream &outfile)
Redirect output to NavierStokesEquations output.
void output (std::ostream &outfile, const unsigned &n_plot)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt, const unsigned &n_plot)
Redirect output to NavierStokesEquations output.
unsigned ndof_types () const
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::AxisymmetricNavierStokesEquations
AxisymmetricNavierStokesEquations ()
Constructor: NULL the body force and source function.
const double & re () const
Reynolds number.
const double & re_st () const
Product of Reynolds and Strouhal number (=Womersley number)
double *& re_pt ()
Pointer to Reynolds number.
double *& re_st_pt ()
Pointer to product of Reynolds and Strouhal number (=Womersley number)
const double & re_invfr () const
Global inverse Froude number.
double *& re_invfr_pt ()
Pointer to global inverse Froude number.
const double & re_invro () const
Global Reynolds number multiplied by inverse Rossby number.
double *& re_invro_pt ()
Pointer to global inverse Froude number.
const Vector< double > & g () const
Vector of gravitational components.
Vector< double > *& g_pt ()
Pointer to Vector of gravitational components.
const double & density_ratio () const
double *& density_ratio_pt ()
Pointer to Density ratio.
const double & viscosity_ratio () const
double *& viscosity_ratio_pt ()
Pointer to Viscosity Ratio.
virtual unsigned u_index_axi_nst (const unsigned &i) const
unsigned u_index_nst (const unsigned &i) const
unsigned n_u_nst () const
double du_dt_axi_nst (const unsigned &n, const unsigned &i) const
void disable_ALE ()
void enable_ALE ()
virtual int p_nodal_index_axi_nst () const
Which nodal value represents the pressure?
double pressure_integral () const
Integral of pressure over element.
double dissipation () const
Return integral of dissipation over element.
double dissipation (const Vector< double > &s) const
Return dissipation at local coordinate s.
double kin_energy () const
Get integral of kinetic energy over element.
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
Strain-rate tensor: \(e_{ij} \) where \(i,j = r,z,\theta \) (in that order)
void traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction) const
void get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > &press_mass_diag, Vector< double > &veloc_mass_diag, const unsigned &which_one=0)
unsigned nscalar_paraview () const
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
std::string scalar_name_paraview (const unsigned &i) const
void point_output_data (const Vector< double > &s, Vector< double > &data)
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element's residual Vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
Compute the element's residual Vector.
void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
void interpolated_u_axi_nst (const Vector< double > &s, Vector< double > &veloc) const
Compute vector of FE interpolated velocity u at local coordinate s.
double interpolated_u_axi_nst (const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s.
double interpolated_u_axi_nst (const unsigned &t, const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s.
double interpolated_p_axi_nst (const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s.
double interpolated_duds_axi_nst (const Vector< double > &s, const unsigned &i, const unsigned &j) const
double interpolated_dudx_axi_nst (const Vector< double > &s, const unsigned &i, const unsigned &j) const
double interpolated_dudt_axi_nst (const Vector< double > &s, const unsigned &i) const
double interpolated_d_dudx_dX_axi_nst (const Vector< double > &s, const unsigned &p, const unsigned &q, const unsigned &i, const unsigned &k) const
double compute_physical_size () const
Compute the volume of the element.
Public Member Functions inherited from oomph::NavierStokesElementWithDiagonalMassMatrices
NavierStokesElementWithDiagonalMassMatrices ()
Empty constructor.
virtual ~NavierStokesElementWithDiagonalMassMatrices ()
Virtual destructor.
NavierStokesElementWithDiagonalMassMatrices (const NavierStokesElementWithDiagonalMassMatrices &)=delete
Broken copy constructor.
void operator= (const NavierStokesElementWithDiagonalMassMatrices &)=delete
Broken assignment operator.
Public Member Functions inherited from oomph::RefineableAxisymmetricNavierStokesEquations
RefineableAxisymmetricNavierStokesEquations ()
Empty Constructor.
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
double geometric_jacobian (const Vector< double > &x)
Fill in the geometric Jacobian, which in this case is r.
void dinterpolated_u_axi_nst_ddata (const Vector< double > &s, const unsigned &i, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
Private Attributes
double * Ra_pt
Pointer to a new physical variable, the Rayleigh number.
Static Private Attributes
static double Default_Physical_Constant_Value =0.0
The static default value of the Rayleigh number.
Additional Inherited Members
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Public Types inherited from oomph::AxisymAdvectionDiffusionEquations
typedef void(* AxisymAdvectionDiffusionSourceFctPt) (const Vector< double > &x, double &f)
typedef void(* AxisymAdvectionDiffusionWindFctPt) (const Vector< double > &x, Vector< double > &wind)
Public Types inherited from oomph::RefineableQElement< 2 >
typedef void(RefineableQElement< 2 >::* VoidMemberFctPt) ()
Static Public Member Functions inherited from oomph::RefineableElement
static double & max_integrity_tolerance ()
Max. allowed discrepancy in element integrity check.
Static Public Member Functions inherited from oomph::RefineableAxisymmetricNavierStokesEquations
static void pin_redundant_nodal_pressures (const Vector< GeneralisedElement * > &element_pt)
static void unpin_all_pressure_dofs (const Vector< GeneralisedElement * > &element_pt)
Unpin all pressure dofs in elements listed in vector.
Public Attributes inherited from oomph::AxisymmetricNavierStokesEquations
void(*&)(const double &time, const Vector< double > &x, Vector< double > &f) axi_nst_body_force_fct_pt ()
Access function for the body-force pointer.
double(*&)(const double &time, const Vector< double > &x) source_fct_pt ()
Access function for the source-function pointer.
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Static Public Attributes inherited from oomph::AxisymmetricNavierStokesEquations
static Vector< double > Gamma
Vector to decide whether the stress-divergence form is used or not.
Protected Member Functions inherited from oomph::QAxisymAdvectionDiffusionElement< NNODE_1D >
double dshape_and_dtest_eulerian_axi_adv_diff (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_axi_adv_diff (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Protected Member Functions inherited from oomph::FiniteElement
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Member Functions inherited from oomph::RefineableAxisymAdvectionDiffusionEquations
void fill_in_generic_residual_contribution_axi_adv_diff (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
Protected Member Functions inherited from oomph::RefineableElement
void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
void assign_hanging_local_eqn_numbers (const bool &store_local_dof_pt)
Assign the local equation numbers for hanging node variables.
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Protected Member Functions inherited from oomph::RefineableQElement< 2 >
void setup_father_bounds ()
void get_edge_bcs (const int &edge, Vector< int > &bound_cons) const
Determine Vector of boundary conditions along edge (N/S/W/E)
void setup_hang_for_value (const int &value_id)
virtual void quad_hang_helper (const int &value_id, const int &my_edge, std::ofstream &output_hangfile)
Protected Member Functions inherited from oomph::AxisymmetricQCrouzeixRaviartElement
double dshape_and_dtest_eulerian_axi_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
void pshape_axi_nst (const Vector< double > &s, Shape &psi) const
Pressure shape functions at local coordinate s.
void pshape_axi_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Pressure shape and test functions at local coordinte s.
Protected Member Functions inherited from oomph::AxisymmetricNavierStokesEquations
virtual void get_body_force_gradient_axi_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, DenseMatrix< double > &d_body_force_dx)
double get_source_fct (const double &time, const unsigned &ipt, const Vector< double > &x)
Calculate the source fct at given time and Eulerian position.
virtual void get_source_fct_gradient (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &gradient)
virtual void get_viscosity_ratio_axisym_nst (const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, double &visc_ratio)
Protected Member Functions inherited from oomph::RefineableAxisymmetricNavierStokesEquations
virtual Node * pressure_node_pt (const unsigned &n_p)
virtual void pin_elemental_redundant_nodal_pressure_dofs ()
Static Protected Member Functions inherited from oomph::RefineableElement
static void check_value_id (const int &n_continuously_interpolated_values, const int &value_id)
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Protected Attributes inherited from oomph::AxisymAdvectionDiffusionEquations
double * Pe_pt
Pointer to global Peclet number.
double * PeSt_pt
Pointer to global Peclet number multiplied by Strouhal number.
double * D_pt
Pointer to global Diffusion parameter.
AxisymAdvectionDiffusionSourceFctPt Source_fct_pt
Pointer to source function:
AxisymAdvectionDiffusionWindFctPt Wind_fct_pt
Pointer to wind function:
bool ALE_is_disabled
Boolean flag to indicate whether AlE formulation is disable.
Protected Attributes inherited from oomph::RefineableElement
Tree * Tree_pt
A pointer to a general tree object.
unsigned Refine_level
Refinement level.
bool To_be_refined
Flag for refinement.
bool Refinement_is_enabled
Flag to indicate suppression of any refinement.
bool Sons_to_be_unrefined
Flag for unrefinement.
long Number
Global element number – for plotting/validation purposes.
Protected Attributes inherited from oomph::AxisymmetricQCrouzeixRaviartElement
unsigned P_axi_nst_internal_index
Protected Attributes inherited from oomph::AxisymmetricNavierStokesEquations
double * Viscosity_Ratio_pt
double * Density_Ratio_pt
double * Re_pt
Pointer to global Reynolds number.
double * ReSt_pt
Pointer to global Reynolds number x Strouhal number (=Womersley)
double * ReInvFr_pt
double * ReInvRo_pt
Vector< double > * G_pt
Pointer to global gravity Vector.
void(* Body_force_fct_pt)(const double &time, const Vector< double > &x, Vector< double > &result)
Pointer to body force function.
double(* Source_fct_pt)(const double &time, const Vector< double > &x)
Pointer to volumetric source function.
bool ALE_is_disabled
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Static Protected Attributes inherited from oomph::RefineableElement
static double Max_integrity_tolerance = 1.0e-8
Max. allowed discrepancy in element integrity check.
Static Protected Attributes inherited from oomph::RefineableQElement< 2 >
static std::map< unsigned, DenseMatrix< int > > Father_bound
Detailed Description
A RefineableElement class that solves the Boussinesq approximation of the Navier–Stokes and energy equations by coupling two pre-existing classes. The RefineableQAdvectionDiffusionElement with bi-quadratic interpolation for the scalar variable (temperature) and RefineableQCrouzeixRaviartElement which solves the Navier–Stokes equations using bi-quadratic interpolation for the velocities and a discontinuous bi-linear interpolation for the pressure. Note that we are free to choose the order in which we store the variables at the nodes. In this case we choose to store the variables in the order fluid velocities followed by temperature. We must, therefore, overload the function AdvectionDiffusionEquations<DIM>::u_index_adv_diff() to indicate that the temperature is stored at the DIM-th position not the 0-th. We do not need to overload the corresponding function in the NavierStokesEquations<DIM> class because the velocities are stored first. Finally, we choose to use the flux-recovery calculation from the fluid velocities to provide the error used in the mesh adaptation.
Constructor & Destructor Documentation
RefineableBuoyantQAxisymCrouzeixRaviartElement() [1/2]
oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::RefineableBuoyantQAxisymCrouzeixRaviartElement () inline
Constructor: call the underlying constructors and initialise the pointer to the Rayleigh number to address the default value of 0.0
                                                   :
   RefineableQAxisymAdvectionDiffusionElement<3>(),
   RefineableAxisymmetricQCrouzeixRaviartElement()
   {
    Ra_pt = &Default_Physical_Constant_Value;
   }
References Default_Physical_Constant_Value, and Ra_pt.
RefineableBuoyantQAxisymCrouzeixRaviartElement() [2/2]
oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::RefineableBuoyantQAxisymCrouzeixRaviartElement () inline
Constructor: call the underlying constructors and initialise the pointer to the Rayleigh number to address the default value of 0.0
                                                   :
   RefineableQAxisymAdvectionDiffusionElement<3>(),
   RefineableAxisymmetricQCrouzeixRaviartElement()
   {
    Ra_pt = &Default_Physical_Constant_Value;
   }
References Default_Physical_Constant_Value, and Ra_pt.
Member Function Documentation
compute_error() [1/4]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) inline virtual
Validate against exact solution. Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element Overload to broken default.
Reimplemented from oomph::FiniteElement.
   {FiniteElement::
    compute_error(outfile,exact_soln_pt,error,norm);}
References oomph::FiniteElement::compute_error(), and calibrate::error.
compute_error() [2/4]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) inline virtual
Validate against exact solution. Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element Overload to broken default.
Reimplemented from oomph::FiniteElement.
   {FiniteElement::
    compute_error(outfile,exact_soln_pt,error,norm);}
References oomph::FiniteElement::compute_error(), and calibrate::error.
compute_error() [3/4]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) inline virtual
Validate against exact solution at given time Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element Overload to broken default
Reimplemented from oomph::FiniteElement.
   {FiniteElement::compute_error(outfile,exact_soln_pt,
                                 time,error,norm);}
References oomph::FiniteElement::compute_error(), and calibrate::error.
compute_error() [4/4]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) inline virtual
Validate against exact solution at given time Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element Overload to broken default
Reimplemented from oomph::FiniteElement.
   {FiniteElement::compute_error(outfile,exact_soln_pt,
                                 time,error,norm);}
References oomph::FiniteElement::compute_error(), and calibrate::error.
disable_ALE() [1/2]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::disable_ALE () inline virtual
Final override for disable ALE.
Reimplemented from oomph::FiniteElement.
   {
    //Disable ALE in both sets of equations
    RefineableAxisymmetricNavierStokesEquations::disable_ALE();
    RefineableAxisymAdvectionDiffusionEquations::disable_ALE();
   }
References oomph::AxisymAdvectionDiffusionEquations::disable_ALE(), and oomph::AxisymmetricNavierStokesEquations::disable_ALE().
disable_ALE() [2/2]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::disable_ALE () inline virtual
Final override for disable ALE.
Reimplemented from oomph::FiniteElement.
   {
    //Disable ALE in both sets of equations
    RefineableAxisymmetricNavierStokesEquations::disable_ALE();
    RefineableAxisymAdvectionDiffusionEquations::disable_ALE();
   }
References oomph::AxisymAdvectionDiffusionEquations::disable_ALE(), and oomph::AxisymmetricNavierStokesEquations::disable_ALE().
enable_ALE() [1/2]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::enable_ALE () inline virtual
Final override for enable ALE.
Reimplemented from oomph::FiniteElement.
   {
    //Enable ALE in both sets of equations
    RefineableAxisymmetricNavierStokesEquations::enable_ALE();
    RefineableAxisymAdvectionDiffusionEquations::enable_ALE();
   }
References oomph::AxisymAdvectionDiffusionEquations::enable_ALE(), and oomph::AxisymmetricNavierStokesEquations::enable_ALE().
enable_ALE() [2/2]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::enable_ALE () inline virtual
Final override for enable ALE.
Reimplemented from oomph::FiniteElement.
   {
    //Enable ALE in both sets of equations
    RefineableAxisymmetricNavierStokesEquations::enable_ALE();
    RefineableAxisymAdvectionDiffusionEquations::enable_ALE();
   }
References oomph::AxisymAdvectionDiffusionEquations::enable_ALE(), and oomph::AxisymmetricNavierStokesEquations::enable_ALE().
fill_in_contribution_to_jacobian() [1/2]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline virtual
Compute the element's residual Vector and the jacobian matrix using full finite differences, the default implementation
Reimplemented from oomph::GeneralisedElement.
   {
 #ifdef USE_FD_JACOBIAN_FOR_REFINEABLE_BUOYANT_Q_ELEMENT
    FiniteElement::fill_in_contribution_to_jacobian(residuals,jacobian);
 #else
    //Calculate the Navier-Stokes contributions (diagonal block and residuals)
    RefineableAxisymmetricNavierStokesEquations::
     fill_in_contribution_to_jacobian(residuals,jacobian);
    //Calculate the advection-diffusion contributions
    //(diagonal block and residuals)
    RefineableAxisymAdvectionDiffusionEquations::
     fill_in_contribution_to_jacobian(residuals,jacobian);
    //We now fill in the off-diagonal (interaction) blocks analytically
    this->fill_in_off_diagonal_jacobian_blocks_analytic(residuals,jacobian);
 #endif
   } //End of jacobian calculation
References oomph::AxisymAdvectionDiffusionEquations::fill_in_contribution_to_jacobian(), oomph::AxisymmetricNavierStokesEquations::fill_in_contribution_to_jacobian(), oomph::FiniteElement::fill_in_contribution_to_jacobian(), and fill_in_off_diagonal_jacobian_blocks_analytic().
fill_in_contribution_to_jacobian() [2/2]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline virtual
Compute the element's residual Vector and the jacobian matrix using full finite differences, the default implementation
Reimplemented from oomph::GeneralisedElement.
   {
 #ifdef USE_FD_JACOBIAN_FOR_REFINEABLE_BUOYANT_Q_ELEMENT
    FiniteElement::fill_in_contribution_to_jacobian(residuals,jacobian);
 #else
    //Calculate the Navier-Stokes contributions (diagonal block and residuals)
    RefineableAxisymmetricNavierStokesEquations::
     fill_in_contribution_to_jacobian(residuals,jacobian);
    //Calculate the advection-diffusion contributions
    //(diagonal block and residuals)
    RefineableAxisymAdvectionDiffusionEquations::
     fill_in_contribution_to_jacobian(residuals,jacobian);
    //We now fill in the off-diagonal (interaction) blocks analytically
    this->fill_in_off_diagonal_jacobian_blocks_analytic(residuals,jacobian);
 #endif
   } //End of jacobian calculation
References oomph::AxisymAdvectionDiffusionEquations::fill_in_contribution_to_jacobian(), oomph::AxisymmetricNavierStokesEquations::fill_in_contribution_to_jacobian(), oomph::FiniteElement::fill_in_contribution_to_jacobian(), and fill_in_off_diagonal_jacobian_blocks_analytic().
fill_in_contribution_to_jacobian_and_mass_matrix() [1/2]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) inline virtual
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix
Reimplemented from oomph::GeneralisedElement.
   {
    //Call the (broken) version in the base class
    FiniteElement::fill_in_contribution_to_jacobian_and_mass_matrix(
      residuals,jacobian,mass_matrix);
   }
References oomph::GeneralisedElement::fill_in_contribution_to_jacobian_and_mass_matrix().
fill_in_contribution_to_jacobian_and_mass_matrix() [2/2]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) inline virtual
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix
Reimplemented from oomph::GeneralisedElement.
   {
    //Call the (broken) version in the base class
    FiniteElement::fill_in_contribution_to_jacobian_and_mass_matrix(
      residuals,jacobian,mass_matrix);
   }
References oomph::GeneralisedElement::fill_in_contribution_to_jacobian_and_mass_matrix().
fill_in_contribution_to_residuals() [1/2]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::fill_in_contribution_to_residuals (Vector< double > & residuals) inline virtual
Fill in the constituent elements' contribution to the residual vector.
Reimplemented from oomph::GeneralisedElement.
   {
    //Call the residuals of the Navier-Stokes equations
    RefineableAxisymmetricNavierStokesEquations::
     fill_in_contribution_to_residuals(residuals);
    //Call the residuals of the advection-diffusion equations
    RefineableAxisymAdvectionDiffusionEquations::
     fill_in_contribution_to_residuals(residuals);
   }
References oomph::AxisymAdvectionDiffusionEquations::fill_in_contribution_to_residuals(), and oomph::AxisymmetricNavierStokesEquations::fill_in_contribution_to_residuals().
fill_in_contribution_to_residuals() [2/2]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::fill_in_contribution_to_residuals (Vector< double > & residuals) inline virtual
Fill in the constituent elements' contribution to the residual vector.
Reimplemented from oomph::GeneralisedElement.
   {
    //Call the residuals of the Navier-Stokes equations
    RefineableAxisymmetricNavierStokesEquations::
     fill_in_contribution_to_residuals(residuals);
    //Call the residuals of the advection-diffusion equations
    RefineableAxisymAdvectionDiffusionEquations::
     fill_in_contribution_to_residuals(residuals);
   }
References oomph::AxisymAdvectionDiffusionEquations::fill_in_contribution_to_residuals(), and oomph::AxisymmetricNavierStokesEquations::fill_in_contribution_to_residuals().
fill_in_off_diagonal_jacobian_blocks_analytic() [1/2]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::fill_in_off_diagonal_jacobian_blocks_analytic (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline
Compute the contribution of the off-diagonal blocks analytically.
   {
    //Perform another loop over the integration loops using the information
    //from the original elements' residual assembly loops to determine
    //the conributions to the jacobian
    // Local storage for pointers to hang_info objects
    HangInfo *hang_info_pt=0, *hang_info2_pt=0;
    //Local storage for the index in the nodes at which the
    //Navier-Stokes velocities are stored (we know that this should be 0,1,2)
    unsigned u_nodal_axi_nst[3];
    for(unsigned i=0;i<3;i++) {u_nodal_axi_nst[i] = this->u_index_axi_nst(i);}
    //Local storage for the  index at which the temperature is stored
    const unsigned u_nodal_axi_adv_diff = this->u_index_axi_adv_diff();
    //Find out how many nodes there are
    const unsigned n_node = this->nnode();
    //Set up memory for the shape and test functions and their derivatives
    Shape psif(n_node), testf(n_node);
    DShape dpsifdx(n_node,2), dtestfdx(n_node,2);
    //Number of integration points
    const unsigned n_intpt = this->integral_pt()->nweight();
    //Get Physical Variables from Element
    double Ra = this->ra();
    double Pe = this->pe();
    Vector<double> gravity = this->g();
    //Integers to store the local equations and unknowns
    int local_eqn=0, local_unknown=0;
    //Loop over the integration points
    for(unsigned ipt=0;ipt<n_intpt;ipt++)
     {
      //Get the integral weight
      double w = this->integral_pt()->weight(ipt);
      //Call the derivatives of the shape and test functions
      double J =
       this->dshape_and_dtest_eulerian_at_knot_axi_nst(ipt,psif,dpsifdx,
                                                       testf,dtestfdx);
      //Premultiply the weights and the Jacobian
      double W = w*J;
      //Work out the radius
      double r = 0.0;
      //Calculate local values of temperature derivatives
      //Allocate
      Vector<double> interpolated_du_axi_adv_diff_dx(2,0.0);
      // Loop over nodes
      for(unsigned l=0;l<n_node;l++)
       {
        //Get the nodal value
        double u_value = this->nodal_value(l,u_nodal_axi_adv_diff);
        //Loop over the derivative directions
        for(unsigned j=0;j<2;j++)
         {
          interpolated_du_axi_adv_diff_dx[j] += u_value*dpsifdx(l,j);
         }
        //Calculate the position
        r += this->nodal_position(l,0)*psif(l);
       }
      //Assemble the Jacobian terms
      //---------------------------
      //Loop over the test functions/eqns
      for(unsigned l=0;l<n_node;l++)
       {
        //Local variables to store the number of master nodes and
        //the weight associated with the shape function if the node is hanging
        unsigned n_master=1;
        double hang_weight=1.0;
        //Local bool (is the node hanging)
        bool is_node_hanging = this->node_pt(l)->is_hanging();
        //If the node is hanging, get the number of master nodes
        if(is_node_hanging)
         {
          hang_info_pt = this->node_pt(l)->hanging_pt();
          n_master = hang_info_pt->nmaster();
         }
        //Otherwise there is just one master node, the node itself
        else
         {
          n_master = 1;
         }
        //Loop over the master nodes
        for(unsigned m=0;m<n_master;m++)
         {
          //If the node is hanging get weight from master node
          if(is_node_hanging)
           {
            //Get the hang weight from the master node
            hang_weight = hang_info_pt->master_weight(m);
           }
          else
           {
            // Node contributes with full weight
            hang_weight = 1.0;
           }
          //Assemble derivatives of Navier Stokes momentum w.r.t. temperature
          //-----------------------------------------------------------------
          // Loop over velocity components for equations
          for(unsigned i=0;i<3;i++)
           {
            //Get the equation number
            if(is_node_hanging)
             {
              //Get the equation number from the master node
              local_eqn = this->local_hang_eqn(hang_info_pt->master_node_pt(m),
                                               u_nodal_axi_nst[i]);
             }
            else
             {
              // Local equation number
              local_eqn = this->nodal_local_eqn(l,u_nodal_axi_nst[i]);
             }
            if(local_eqn >= 0)
             {
              //Local variables to store the number of master nodes
              //and the weights associated with each hanging node
              unsigned n_master2=1;
              double hang_weight2=1.0;
              //Loop over the nodes for the unknowns
              for(unsigned l2=0;l2<n_node;l2++)
               {
                //Local bool (is the node hanging)
                bool is_node2_hanging = this->node_pt(l2)->is_hanging();
                //If the node is hanging, get the number of master nodes
                if(is_node2_hanging)
                 {
                  hang_info2_pt = this->node_pt(l2)->hanging_pt();
                  n_master2 = hang_info2_pt->nmaster();
                 }
                //Otherwise there is one master node, the node itself
                else
                 {
                  n_master2 = 1;
                 }
                //Loop over the master nodes
                for(unsigned m2=0;m2<n_master2;m2++)
                 {
                  if(is_node2_hanging)
                   {
                    //Read out the local unknown from the master node
                    local_unknown =
                     this->local_hang_eqn(hang_info2_pt->master_node_pt(m2),
                                          u_nodal_axi_adv_diff);
                    //Read out the hanging weight from the master node
                    hang_weight2 = hang_info2_pt->master_weight(m2);
                   }
                  else
                   {
                    //The local unknown number comes from the node
                    local_unknown = this->nodal_local_eqn(l2,
                                                          u_nodal_axi_adv_diff);
                    //The hang weight is one
                    hang_weight2 = 1.0;
                   }
                  if(local_unknown >= 0)
                   {
                    //Add contribution to jacobian matrix
                    jacobian(local_eqn,local_unknown)
                     += -gravity[i]*psif(l2)*Ra*testf(l)*
                     r*W*hang_weight*hang_weight2;
                   }
                 }
               }
             }
           }
          //Assemble derivative of adv diff eqn w.r.t. fluid veloc
          //------------------------------------------------------
          {
           //Get the equation number
           if(is_node_hanging)
            {
             //Get the equation number from the master node
             local_eqn = this->local_hang_eqn(hang_info_pt->master_node_pt(m),
                                              u_nodal_axi_adv_diff);
            }
           else
            {
             // Local equation number
             local_eqn = this->nodal_local_eqn(l,u_nodal_axi_adv_diff);
            }
           //If it's not pinned
           if(local_eqn >= 0)
            {
             //Local variables to store the number of master nodes
             //and the weights associated with each hanging node
             unsigned n_master2=1;
             double hang_weight2=1.0;
             //Loop over the nodes for the unknowns
             for(unsigned l2=0;l2<n_node;l2++)
              {
               //Local bool (is the node hanging)
               bool is_node2_hanging = this->node_pt(l2)->is_hanging();
               //If the node is hanging, get the number of master nodes
               if(is_node2_hanging)
                {
                 hang_info2_pt = this->node_pt(l2)->hanging_pt();
                 n_master2 = hang_info2_pt->nmaster();
                }
               //Otherwise there is one master node, the node itself
               else
                {
                 n_master2 = 1;
                }
               //Loop over the master nodes
               for(unsigned m2=0;m2<n_master2;m2++)
                {
                 //If the node is hanging
                 if(is_node2_hanging)
                  {
                   //Read out the hanging weight from the master node
                   hang_weight2 = hang_info2_pt->master_weight(m2);
                  }
                 //If the node is not hanging
                 else
                  {
                   //The hang weight is one
                   hang_weight2 = 1.0;
                  }
                 //Loop over the velocity degrees of freedom
                 for(unsigned i2=0;i2<2;i2++)
                  {
                   //If the node is hanging
                   if(is_node2_hanging)
                    {
                     //Read out the local unknown from the master node
                     local_unknown =
                      this->local_hang_eqn(hang_info2_pt->master_node_pt(m2),
                                           u_nodal_axi_nst[i2]);
                    }
                   else
                    {
                     //The local unknown number comes from the node
                     local_unknown=this->nodal_local_eqn(l2,
                                                         u_nodal_axi_nst[i2]);
                    }
                   //If it's not pinned
                   if(local_unknown >= 0)
                    {
                     //Add the contribution to the jacobian matrix
                     jacobian(local_eqn,local_unknown)
                      -= Pe*psif(l2)*interpolated_du_axi_adv_diff_dx[i2]*testf(l)
                      *r*W*hang_weight*hang_weight2;
                    }
                  }
                }
              }
            }
          }
         }
       }
     }
   } //End of function
References oomph::AxisymmetricQCrouzeixRaviartElement::dshape_and_dtest_eulerian_at_knot_axi_nst(), oomph::AxisymmetricNavierStokesEquations::g(), oomph::Node::hanging_pt(), i, oomph::FiniteElement::integral_pt(), oomph::Node::is_hanging(), J, j, oomph::RefineableElement::local_hang_eqn(), m, m2(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::Integral::nweight(), Global_Parameters::Pe, oomph::AxisymAdvectionDiffusionEquations::pe(), UniformPSDSelfTest::r, ra(), Global_Parameters::Ra, u_index_axi_adv_diff(), oomph::AxisymmetricNavierStokesEquations::u_index_axi_nst(), w, oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by fill_in_contribution_to_jacobian().
fill_in_off_diagonal_jacobian_blocks_analytic() [2/2]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::fill_in_off_diagonal_jacobian_blocks_analytic (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline
Compute the contribution of the off-diagonal blocks analytically.
   {
    //Perform another loop over the integration loops using the information
    //from the original elements' residual assembly loops to determine
    //the conributions to the jacobian
    // Local storage for pointers to hang_info objects
    HangInfo *hang_info_pt=0, *hang_info2_pt=0;
    //Local storage for the index in the nodes at which the
    //Navier-Stokes velocities are stored (we know that this should be 0,1,2)
    unsigned u_nodal_axi_nst[3];
    for(unsigned i=0;i<3;i++) {u_nodal_axi_nst[i] = this->u_index_axi_nst(i);}
    //Local storage for the  index at which the temperature is stored
    const unsigned u_nodal_axi_adv_diff = this->u_index_axi_adv_diff();
    //Find out how many nodes there are
    const unsigned n_node = this->nnode();
    //Set up memory for the shape and test functions and their derivatives
    Shape psif(n_node), testf(n_node);
    DShape dpsifdx(n_node,2), dtestfdx(n_node,2);
    //Number of integration points
    const unsigned n_intpt = this->integral_pt()->nweight();
    //Get Physical Variables from Element
    double Ra = this->ra();
    double Pe = this->pe();
    Vector<double> gravity = this->g();
    //Integers to store the local equations and unknowns
    int local_eqn=0, local_unknown=0;
    //Loop over the integration points
    for(unsigned ipt=0;ipt<n_intpt;ipt++)
     {
      //Get the integral weight
      double w = this->integral_pt()->weight(ipt);
      //Call the derivatives of the shape and test functions
      double J =
       this->dshape_and_dtest_eulerian_at_knot_axi_nst(ipt,psif,dpsifdx,
                                                       testf,dtestfdx);
      //Premultiply the weights and the Jacobian
      double W = w*J;
      //Work out the radius
      double r = 0.0;
      //Calculate local values of temperature derivatives
      //Allocate
      Vector<double> interpolated_du_axi_adv_diff_dx(2,0.0);
      // Loop over nodes
      for(unsigned l=0;l<n_node;l++)
       {
        //Get the nodal value
        double u_value = this->nodal_value(l,u_nodal_axi_adv_diff);
        //Loop over the derivative directions
        for(unsigned j=0;j<2;j++)
         {
          interpolated_du_axi_adv_diff_dx[j] += u_value*dpsifdx(l,j);
         }
        //Calculate the position
        r += this->nodal_position(l,0)*psif(l);
       }
      //Assemble the Jacobian terms
      //---------------------------
      //Loop over the test functions/eqns
      for(unsigned l=0;l<n_node;l++)
       {
        //Local variables to store the number of master nodes and
        //the weight associated with the shape function if the node is hanging
        unsigned n_master=1;
        double hang_weight=1.0;
        //Local bool (is the node hanging)
        bool is_node_hanging = this->node_pt(l)->is_hanging();
        //If the node is hanging, get the number of master nodes
        if(is_node_hanging)
         {
          hang_info_pt = this->node_pt(l)->hanging_pt();
          n_master = hang_info_pt->nmaster();
         }
        //Otherwise there is just one master node, the node itself
        else
         {
          n_master = 1;
         }
        //Loop over the master nodes
        for(unsigned m=0;m<n_master;m++)
         {
          //If the node is hanging get weight from master node
          if(is_node_hanging)
           {
            //Get the hang weight from the master node
            hang_weight = hang_info_pt->master_weight(m);
           }
          else
           {
            // Node contributes with full weight
            hang_weight = 1.0;
           }
          //Assemble derivatives of Navier Stokes momentum w.r.t. temperature
          //-----------------------------------------------------------------
          // Loop over velocity components for equations
          for(unsigned i=0;i<3;i++)
           {
            //Get the equation number
            if(is_node_hanging)
             {
              //Get the equation number from the master node
              local_eqn = this->local_hang_eqn(hang_info_pt->master_node_pt(m),
                                               u_nodal_axi_nst[i]);
             }
            else
             {
              // Local equation number
              local_eqn = this->nodal_local_eqn(l,u_nodal_axi_nst[i]);
             }
            if(local_eqn >= 0)
             {
              //Local variables to store the number of master nodes
              //and the weights associated with each hanging node
              unsigned n_master2=1;
              double hang_weight2=1.0;
              //Loop over the nodes for the unknowns
              for(unsigned l2=0;l2<n_node;l2++)
               {
                //Local bool (is the node hanging)
                bool is_node2_hanging = this->node_pt(l2)->is_hanging();
                //If the node is hanging, get the number of master nodes
                if(is_node2_hanging)
                 {
                  hang_info2_pt = this->node_pt(l2)->hanging_pt();
                  n_master2 = hang_info2_pt->nmaster();
                 }
                //Otherwise there is one master node, the node itself
                else
                 {
                  n_master2 = 1;
                 }
                //Loop over the master nodes
                for(unsigned m2=0;m2<n_master2;m2++)
                 {
                  if(is_node2_hanging)
                   {
                    //Read out the local unknown from the master node
                    local_unknown =
                     this->local_hang_eqn(hang_info2_pt->master_node_pt(m2),
                                          u_nodal_axi_adv_diff);
                    //Read out the hanging weight from the master node
                    hang_weight2 = hang_info2_pt->master_weight(m2);
                   }
                  else
                   {
                    //The local unknown number comes from the node
                    local_unknown = this->nodal_local_eqn(l2,
                                                          u_nodal_axi_adv_diff);
                    //The hang weight is one
                    hang_weight2 = 1.0;
                   }
                  if(local_unknown >= 0)
                   {
                    //Add contribution to jacobian matrix
                    jacobian(local_eqn,local_unknown)
                     += -gravity[i]*psif(l2)*Ra*testf(l)*
                     r*W*hang_weight*hang_weight2;
                   }
                 }
               }
             }
           }
          //Assemble derivative of adv diff eqn w.r.t. fluid veloc
          //------------------------------------------------------
          {
           //Get the equation number
           if(is_node_hanging)
            {
             //Get the equation number from the master node
             local_eqn = this->local_hang_eqn(hang_info_pt->master_node_pt(m),
                                              u_nodal_axi_adv_diff);
            }
           else
            {
             // Local equation number
             local_eqn = this->nodal_local_eqn(l,u_nodal_axi_adv_diff);
            }
           //If it's not pinned
           if(local_eqn >= 0)
            {
             //Local variables to store the number of master nodes
             //and the weights associated with each hanging node
             unsigned n_master2=1;
             double hang_weight2=1.0;
             //Loop over the nodes for the unknowns
             for(unsigned l2=0;l2<n_node;l2++)
              {
               //Local bool (is the node hanging)
               bool is_node2_hanging = this->node_pt(l2)->is_hanging();
               //If the node is hanging, get the number of master nodes
               if(is_node2_hanging)
                {
                 hang_info2_pt = this->node_pt(l2)->hanging_pt();
                 n_master2 = hang_info2_pt->nmaster();
                }
               //Otherwise there is one master node, the node itself
               else
                {
                 n_master2 = 1;
                }
               //Loop over the master nodes
               for(unsigned m2=0;m2<n_master2;m2++)
                {
                 //If the node is hanging
                 if(is_node2_hanging)
                  {
                   //Read out the hanging weight from the master node
                   hang_weight2 = hang_info2_pt->master_weight(m2);
                  }
                 //If the node is not hanging
                 else
                  {
                   //The hang weight is one
                   hang_weight2 = 1.0;
                  }
                 //Loop over the velocity degrees of freedom
                 for(unsigned i2=0;i2<2;i2++)
                  {
                   //If the node is hanging
                   if(is_node2_hanging)
                    {
                     //Read out the local unknown from the master node
                     local_unknown =
                      this->local_hang_eqn(hang_info2_pt->master_node_pt(m2),
                                           u_nodal_axi_nst[i2]);
                    }
                   else
                    {
                     //The local unknown number comes from the node
                     local_unknown=this->nodal_local_eqn(l2,
                                                         u_nodal_axi_nst[i2]);
                    }
                   //If it's not pinned
                   if(local_unknown >= 0)
                    {
                     //Add the contribution to the jacobian matrix
                     jacobian(local_eqn,local_unknown)
                      -= Pe*psif(l2)*interpolated_du_axi_adv_diff_dx[i2]*testf(l)
                      *r*W*hang_weight*hang_weight2;
                    }
                  }
                }
              }
            }
          }
         }
       }
     }
   } //End of function
References oomph::AxisymmetricQCrouzeixRaviartElement::dshape_and_dtest_eulerian_at_knot_axi_nst(), oomph::AxisymmetricNavierStokesEquations::g(), oomph::Node::hanging_pt(), i, oomph::FiniteElement::integral_pt(), oomph::Node::is_hanging(), J, j, oomph::RefineableElement::local_hang_eqn(), m, m2(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::Integral::nweight(), Global_Parameters::Pe, oomph::AxisymAdvectionDiffusionEquations::pe(), UniformPSDSelfTest::r, ra(), Global_Parameters::Ra, u_index_axi_adv_diff(), oomph::AxisymmetricNavierStokesEquations::u_index_axi_nst(), w, oomph::QuadTreeNames::W, and oomph::Integral::weight().
further_build() [1/2]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::further_build () inline virtual
Call the underlying single-physics element's further_build() functions and make sure that the pointer to the Rayleigh number is passed to the sons
Reimplemented from oomph::RefineableElement.
   {
    RefineableAxisymmetricQCrouzeixRaviartElement::further_build();
    RefineableQAxisymAdvectionDiffusionElement<3>::further_build();
    //Cast the pointer to the father element to the specific
    //element type
    RefineableBuoyantQAxisymCrouzeixRaviartElement* cast_father_element_pt
     = dynamic_cast<RefineableBuoyantQAxisymCrouzeixRaviartElement*>(
      this->father_element_pt());
    //Set the pointer to the Rayleigh number to be the same as that in
    //the father
    this->Ra_pt = cast_father_element_pt->ra_pt();
   } //end of further build
References oomph::RefineableElement::father_element_pt(), oomph::RefineableAxisymAdvectionDiffusionEquations::further_build(), oomph::RefineableAxisymmetricQCrouzeixRaviartElement::further_build(), and ra_pt().
further_build() [2/2]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::further_build () inline virtual
Call the underlying single-physics element's further_build() functions and make sure that the pointer to the Rayleigh number is passed to the sons
Reimplemented from oomph::RefineableElement.
   {
    RefineableAxisymmetricQCrouzeixRaviartElement::further_build();
    RefineableQAxisymAdvectionDiffusionElement<3>::further_build();
    //Cast the pointer to the father element to the specific
    //element type
    RefineableBuoyantQAxisymCrouzeixRaviartElement* cast_father_element_pt
     = dynamic_cast<RefineableBuoyantQAxisymCrouzeixRaviartElement*>(
      this->father_element_pt());
    //Set the pointer to the Rayleigh number to be the same as that in
    //the father
    this->Ra_pt = cast_father_element_pt->ra_pt();
   } //end of further build
References oomph::RefineableElement::father_element_pt(), oomph::RefineableAxisymAdvectionDiffusionEquations::further_build(), and oomph::RefineableAxisymmetricQCrouzeixRaviartElement::further_build().
further_setup_hanging_nodes() [1/2]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::further_setup_hanging_nodes () inline virtual
The additional hanging node information must be set up for both single-physics elements.
Implements oomph::RefineableQElement< 2 >.
   {
    RefineableAxisymmetricQCrouzeixRaviartElement::further_setup_hanging_nodes();
    RefineableQAxisymAdvectionDiffusionElement<3>::further_setup_hanging_nodes();
   }
References oomph::RefineableQAxisymAdvectionDiffusionElement< NNODE_1D >::further_setup_hanging_nodes(), and oomph::RefineableAxisymmetricQCrouzeixRaviartElement::further_setup_hanging_nodes().
further_setup_hanging_nodes() [2/2]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::further_setup_hanging_nodes () inline virtual
The additional hanging node information must be set up for both single-physics elements.
Implements oomph::RefineableQElement< 2 >.
   {
    RefineableAxisymmetricQCrouzeixRaviartElement::further_setup_hanging_nodes();
    RefineableQAxisymAdvectionDiffusionElement<3>::further_setup_hanging_nodes();
   }
References oomph::RefineableQAxisymAdvectionDiffusionElement< NNODE_1D >::further_setup_hanging_nodes(), and oomph::RefineableAxisymmetricQCrouzeixRaviartElement::further_setup_hanging_nodes().
geometric_jacobian() [1/2]
double oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::geometric_jacobian (const Vector< double > & x) inline virtual
Fill in the geometric Jacobian, which in this case is r.
Reimplemented from oomph::ElementWithZ2ErrorEstimator.
   {return x[0];}
References plotDoE::x.
geometric_jacobian() [2/2]
double oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::geometric_jacobian (const Vector< double > & x) inline virtual
Fill in the geometric Jacobian, which in this case is r.
Reimplemented from oomph::ElementWithZ2ErrorEstimator.
   {return x[0];}
References plotDoE::x.
get_body_force_axi_nst() [1/2]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::get_body_force_axi_nst (const double & time, const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, Vector< double > & result) inline virtual
Overload the body force in the navier-stokes equations This provides the coupling from the advection-diffusion equations to the Navier–Stokes equations, the body force is the temperature multiplied by the Rayleigh number acting in the direction opposite to gravity.
Reimplemented from oomph::AxisymmetricNavierStokesEquations.
   {
    // Get the temperature
    const double interpolated_t = this->interpolated_u_axi_adv_diff(s);
    // Get vector that indicates the direction of gravity from
    // the Navier-Stokes equations
    Vector<double> gravity(AxisymmetricNavierStokesEquations::g());
    // Temperature-dependent body force:
    for (unsigned i=0;i<3;i++)
     {
      result[i] = -gravity[i]*interpolated_t*ra();
     }
   }
References oomph::AxisymmetricNavierStokesEquations::g(), Gravity::gravity(), i, oomph::AxisymAdvectionDiffusionEquations::interpolated_u_axi_adv_diff(), and ra().
get_body_force_axi_nst() [2/2]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::get_body_force_axi_nst (const double & time, const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, Vector< double > & result) inline virtual
Overload the body force in the navier-stokes equations This provides the coupling from the advection-diffusion equations to the Navier–Stokes equations, the body force is the temperature multiplied by the Rayleigh number acting in the direction opposite to gravity.
Reimplemented from oomph::AxisymmetricNavierStokesEquations.
   {
    // Get the temperature
    const double interpolated_t = this->interpolated_u_axi_adv_diff(s);
    // Get vector that indicates the direction of gravity from
    // the Navier-Stokes equations
    Vector<double> gravity(AxisymmetricNavierStokesEquations::g());
    // Temperature-dependent body force:
    for (unsigned i=0;i<3;i++)
     {
      result[i] = -gravity[i]*interpolated_t*ra();
     }
   }
References oomph::AxisymmetricNavierStokesEquations::g(), Gravity::gravity(), i, oomph::AxisymAdvectionDiffusionEquations::interpolated_u_axi_adv_diff(), and ra().
get_interpolated_values() [1/4]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::get_interpolated_values (const unsigned & t, const Vector< double > & s, Vector< double > & values) inline virtual
Get all continuously interpolated values at the local coordinate s at time level t (t=0: present; t>0: previous). We choose to put the fluid velocities first, followed by the temperature
Implements oomph::RefineableElement.
   {
    //Storage for the fluid velocities
    Vector<double> nst_values;
    //Get the fluid velocities from the fluid element
    RefineableAxisymmetricQCrouzeixRaviartElement::
     get_interpolated_values(t,s,nst_values);
    //Storage for the temperature
    Vector<double> advection_values;
    //Get the temperature from the advection-diffusion element
    RefineableQAxisymAdvectionDiffusionElement<3>::
     get_interpolated_values(s,advection_values);
    //Add the fluid velocities to the values vector
    for(unsigned i=0;i<3;i++) {values.push_back(nst_values[i]);}
    //Add the concentration to the end
    values.push_back(advection_values[0]);
   } // end of get_interpolated_values
References oomph::RefineableAxisymAdvectionDiffusionEquations::get_interpolated_values(), oomph::RefineableAxisymmetricQCrouzeixRaviartElement::get_interpolated_values(), i, s, and plotPSD::t.
get_interpolated_values() [2/4]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::get_interpolated_values (const unsigned & t, const Vector< double > & s, Vector< double > & values) inline virtual
Get all continuously interpolated values at the local coordinate s at time level t (t=0: present; t>0: previous). We choose to put the fluid velocities first, followed by the temperature
Implements oomph::RefineableElement.
   {
    //Storage for the fluid velocities
    Vector<double> nst_values;
    //Get the fluid velocities from the fluid element
    RefineableAxisymmetricQCrouzeixRaviartElement::
     get_interpolated_values(t,s,nst_values);
    //Storage for the temperature
    Vector<double> advection_values;
    //Get the temperature from the advection-diffusion element
    RefineableQAxisymAdvectionDiffusionElement<3>::
     get_interpolated_values(s,advection_values);
    //Add the fluid velocities to the values vector
    for(unsigned i=0;i<3;i++) {values.push_back(nst_values[i]);}
    //Add the concentration to the end
    values.push_back(advection_values[0]);
   } // end of get_interpolated_values
References oomph::RefineableAxisymAdvectionDiffusionEquations::get_interpolated_values(), oomph::RefineableAxisymmetricQCrouzeixRaviartElement::get_interpolated_values(), i, s, and plotPSD::t.
get_interpolated_values() [3/4]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::get_interpolated_values (const Vector< double > & s, Vector< double > & values) inline virtual
Get the continuously interpolated values at the local coordinate s. We choose to put the fluid velocities first, followed by the temperature.
Reimplemented from oomph::RefineableElement.
   {
    //Storage for the fluid velocities
    Vector<double> nst_values;
    //Get the fluid velocities from the fluid element
    RefineableAxisymmetricQCrouzeixRaviartElement::
     get_interpolated_values(s,nst_values);
    //Storage for the temperature
    Vector<double> advection_values;
    //Get the temperature from the advection-diffusion element
    RefineableQAxisymAdvectionDiffusionElement<3>::
     get_interpolated_values(s,advection_values);
    //Add the fluid velocities to the values vector
    for(unsigned i=0;i<3;i++) {values.push_back(nst_values[i]);}
    //Add the concentration to the end
    values.push_back(advection_values[0]);
   }
References oomph::RefineableAxisymAdvectionDiffusionEquations::get_interpolated_values(), oomph::RefineableAxisymmetricQCrouzeixRaviartElement::get_interpolated_values(), i, and s.
get_interpolated_values() [4/4]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::get_interpolated_values (const Vector< double > & s, Vector< double > & values) inline virtual
Get the continuously interpolated values at the local coordinate s. We choose to put the fluid velocities first, followed by the temperature.
Reimplemented from oomph::RefineableElement.
   {
    //Storage for the fluid velocities
    Vector<double> nst_values;
    //Get the fluid velocities from the fluid element
    RefineableAxisymmetricQCrouzeixRaviartElement::
     get_interpolated_values(s,nst_values);
    //Storage for the temperature
    Vector<double> advection_values;
    //Get the temperature from the advection-diffusion element
    RefineableQAxisymAdvectionDiffusionElement<3>::
     get_interpolated_values(s,advection_values);
    //Add the fluid velocities to the values vector
    for(unsigned i=0;i<3;i++) {values.push_back(nst_values[i]);}
    //Add the concentration to the end
    values.push_back(advection_values[0]);
   }
References oomph::RefineableAxisymAdvectionDiffusionEquations::get_interpolated_values(), oomph::RefineableAxisymmetricQCrouzeixRaviartElement::get_interpolated_values(), i, and s.
get_wind_axi_adv_diff() [1/2]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::get_wind_axi_adv_diff (const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, Vector< double > & wind) const inline virtual
Overload the wind function in the advection-diffusion equations. This provides the coupling from the Navier–Stokes equations to the advection-diffusion equations because the wind is the fluid velocity.
Reimplemented from oomph::AxisymAdvectionDiffusionEquations.
   {
    //The wind function is simply the velocity at the points
    this->interpolated_u_axi_nst(s,wind);
   }
References oomph::AxisymmetricNavierStokesEquations::interpolated_u_axi_nst().
get_wind_axi_adv_diff() [2/2]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::get_wind_axi_adv_diff (const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, Vector< double > & wind) const inline virtual
Overload the wind function in the advection-diffusion equations. This provides the coupling from the Navier–Stokes equations to the advection-diffusion equations because the wind is the fluid velocity.
Reimplemented from oomph::AxisymAdvectionDiffusionEquations.
   {
    //The wind function is simply the velocity at the points
    this->interpolated_u_axi_nst(s,wind);
   }
References oomph::AxisymmetricNavierStokesEquations::interpolated_u_axi_nst().
get_Z2_compound_flux_indices() [1/2]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::get_Z2_compound_flux_indices (Vector< unsigned > & flux_index) inline virtual
Fill in which flux components are associated with the fluid measure and which are associated with the temperature measure
Reimplemented from oomph::ElementWithZ2ErrorEstimator.
   {
    //Find the number of fluid fluxes
    unsigned n_fluid_flux =
     RefineableAxisymmetricQCrouzeixRaviartElement::num_Z2_flux_terms();
    //Find the number of temperature fluxes
    unsigned n_temp_flux =
     RefineableQAxisymAdvectionDiffusionElement<3>::num_Z2_flux_terms();
    //The fluid fluxes are first
    //The values of the flux_index vector are zero on entry, so we
    //could omit this line
    for(unsigned i=0;i<n_fluid_flux;i++) {flux_index[i] = 0;}
    //Set the temperature fluxes (the last set of fluxes
    for(unsigned i=0;i<n_temp_flux;i++) {flux_index[n_fluid_flux + i] = 1;}
   } //end of get_Z2_compound_flux_indices
References i, oomph::RefineableAxisymAdvectionDiffusionEquations::num_Z2_flux_terms(), and oomph::RefineableAxisymmetricNavierStokesEquations::num_Z2_flux_terms().
get_Z2_compound_flux_indices() [2/2]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::get_Z2_compound_flux_indices (Vector< unsigned > & flux_index) inline virtual
Fill in which flux components are associated with the fluid measure and which are associated with the temperature measure
Reimplemented from oomph::ElementWithZ2ErrorEstimator.
   {
    //Find the number of fluid fluxes
    unsigned n_fluid_flux =
     RefineableAxisymmetricQCrouzeixRaviartElement::num_Z2_flux_terms();
    //Find the number of temperature fluxes
    unsigned n_temp_flux =
     RefineableQAxisymAdvectionDiffusionElement<3>::num_Z2_flux_terms();
    //The fluid fluxes are first
    //The values of the flux_index vector are zero on entry, so we
    //could omit this line
    for(unsigned i=0;i<n_fluid_flux;i++) {flux_index[i] = 0;}
    //Set the temperature fluxes (the last set of fluxes
    for(unsigned i=0;i<n_temp_flux;i++) {flux_index[n_fluid_flux + i] = 1;}
   } //end of get_Z2_compound_flux_indices
References i, oomph::RefineableAxisymAdvectionDiffusionEquations::num_Z2_flux_terms(), and oomph::RefineableAxisymmetricNavierStokesEquations::num_Z2_flux_terms().
get_Z2_flux() [1/2]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) inline virtual
Get the Z2 flux by concatenating the fluxes from the fluid and the advection diffusion elements.
Implements oomph::ElementWithZ2ErrorEstimator.
   {
    //Find the number of fluid fluxes
    unsigned n_fluid_flux =
     RefineableAxisymmetricQCrouzeixRaviartElement::num_Z2_flux_terms();
    //Fill in the first flux entries as the velocity entries
    RefineableAxisymmetricQCrouzeixRaviartElement::get_Z2_flux(s,flux);
    //Find the number of temperature fluxes
    unsigned n_temp_flux =
     RefineableQAxisymAdvectionDiffusionElement<3>::num_Z2_flux_terms();
    Vector<double> temp_flux(n_temp_flux);
    //Get the temperature flux
    RefineableQAxisymAdvectionDiffusionElement<3>::get_Z2_flux(s,temp_flux);
    //Add the temperature flux to the end of the flux vector
    for(unsigned i=0;i<n_temp_flux;i++)
     {
      flux[n_fluid_flux+i] = temp_flux[i];
     }
   } //end of get_Z2_flux
References ProblemParameters::flux(), oomph::RefineableAxisymAdvectionDiffusionEquations::get_Z2_flux(), oomph::RefineableAxisymmetricNavierStokesEquations::get_Z2_flux(), i, oomph::RefineableAxisymAdvectionDiffusionEquations::num_Z2_flux_terms(), oomph::RefineableAxisymmetricNavierStokesEquations::num_Z2_flux_terms(), and s.
get_Z2_flux() [2/2]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) inline virtual
Get the Z2 flux by concatenating the fluxes from the fluid and the advection diffusion elements.
Implements oomph::ElementWithZ2ErrorEstimator.
   {
    //Find the number of fluid fluxes
    unsigned n_fluid_flux =
     RefineableAxisymmetricQCrouzeixRaviartElement::num_Z2_flux_terms();
    //Fill in the first flux entries as the velocity entries
    RefineableAxisymmetricQCrouzeixRaviartElement::get_Z2_flux(s,flux);
    //Find the number of temperature fluxes
    unsigned n_temp_flux =
     RefineableQAxisymAdvectionDiffusionElement<3>::num_Z2_flux_terms();
    Vector<double> temp_flux(n_temp_flux);
    //Get the temperature flux
    RefineableQAxisymAdvectionDiffusionElement<3>::get_Z2_flux(s,temp_flux);
    //Add the temperature flux to the end of the flux vector
    for(unsigned i=0;i<n_temp_flux;i++)
     {
      flux[n_fluid_flux+i] = temp_flux[i];
     }
   } //end of get_Z2_flux
References ProblemParameters::flux(), oomph::RefineableAxisymAdvectionDiffusionEquations::get_Z2_flux(), oomph::RefineableAxisymmetricNavierStokesEquations::get_Z2_flux(), i, oomph::RefineableAxisymAdvectionDiffusionEquations::num_Z2_flux_terms(), oomph::RefineableAxisymmetricNavierStokesEquations::num_Z2_flux_terms(), and s.
ncompound_fluxes() [1/2]
unsigned oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::ncompound_fluxes () inline virtual
The number of compound fluxes is two (one for the fluid and one for the temperature)
Reimplemented from oomph::ElementWithZ2ErrorEstimator.
 {return 2;}
ncompound_fluxes() [2/2]
unsigned oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::ncompound_fluxes () inline virtual
The number of compound fluxes is two (one for the fluid and one for the temperature)
Reimplemented from oomph::ElementWithZ2ErrorEstimator.
 {return 2;}
ncont_interpolated_values() [1/2]
unsigned oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::ncont_interpolated_values () const inline virtual
The total number of continously interpolated values is 4 (3 fluid velocities and one temperature).
Implements oomph::RefineableElement.
   {return 4;}
ncont_interpolated_values() [2/2]
unsigned oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::ncont_interpolated_values () const inline virtual
The total number of continously interpolated values is 4 (3 fluid velocities and one temperature).
Implements oomph::RefineableElement.
   {return 4;}
nrecovery_order() [1/2]
unsigned oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::nrecovery_order () inline virtual
The recovery order is that of the NavierStokes elements.
Implements oomph::ElementWithZ2ErrorEstimator.
   {return RefineableAxisymmetricQCrouzeixRaviartElement::nrecovery_order();}
References oomph::RefineableAxisymmetricQCrouzeixRaviartElement::nrecovery_order().
nrecovery_order() [2/2]
unsigned oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::nrecovery_order () inline virtual
The recovery order is that of the NavierStokes elements.
Implements oomph::ElementWithZ2ErrorEstimator.
   {return RefineableAxisymmetricQCrouzeixRaviartElement::nrecovery_order();}
References oomph::RefineableAxisymmetricQCrouzeixRaviartElement::nrecovery_order().
nscalar_paraview() [1/2]
unsigned oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::nscalar_paraview () const inline virtual
Number of scalars/fields output by this element. Broken virtual. Needs to be implemented for each new specific element type. Temporary dummy
Reimplemented from oomph::FiniteElement.
  {
   throw OomphLibError(
    "This function hasn't been implemented for this element",
    OOMPH_CURRENT_FUNCTION,
    OOMPH_EXCEPTION_LOCATION);
   // Dummy unsigned
   return 0;
  }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
nscalar_paraview() [2/2]
unsigned oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::nscalar_paraview () const inline virtual
Number of scalars/fields output by this element. Broken virtual. Needs to be implemented for each new specific element type. Temporary dummy
Reimplemented from oomph::FiniteElement.
  {
   throw OomphLibError(
    "This function hasn't been implemented for this element",
    OOMPH_CURRENT_FUNCTION,
    OOMPH_EXCEPTION_LOCATION);
   // Dummy unsigned
   return 0;
  }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
num_Z2_flux_terms() [1/2]
unsigned oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::num_Z2_flux_terms () inline virtual
The number of Z2 flux terms is the same as that in the fluid element plus that in the advection-diffusion element
Implements oomph::ElementWithZ2ErrorEstimator.
   {
    return (RefineableAxisymmetricQCrouzeixRaviartElement::num_Z2_flux_terms() +
            RefineableQAxisymAdvectionDiffusionElement<3>::num_Z2_flux_terms());
   }
References oomph::RefineableAxisymmetricNavierStokesEquations::num_Z2_flux_terms().
num_Z2_flux_terms() [2/2]
unsigned oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::num_Z2_flux_terms () inline virtual
The number of Z2 flux terms is the same as that in the fluid element plus that in the advection-diffusion element
Implements oomph::ElementWithZ2ErrorEstimator.
   {
    return (RefineableAxisymmetricQCrouzeixRaviartElement::num_Z2_flux_terms() +
            RefineableQAxisymAdvectionDiffusionElement<3>::num_Z2_flux_terms());
   }
References oomph::RefineableAxisymmetricNavierStokesEquations::num_Z2_flux_terms().
nvertex_node() [1/2]
unsigned oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::nvertex_node () const inline virtual
Number of vertex nodes in the element is obtained from the geometric element.
Implements oomph::ElementWithZ2ErrorEstimator.
   {return QElement<2,3>::nvertex_node();}
nvertex_node() [2/2]
unsigned oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::nvertex_node () const inline virtual
Number of vertex nodes in the element is obtained from the geometric element.
Implements oomph::ElementWithZ2ErrorEstimator.
   {return QElement<2,3>::nvertex_node();}
output() [1/8]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::output (FILE * file_pt) inline virtual
C-style output function: Broken default.
Reimplemented from oomph::FiniteElement.
   {FiniteElement::output(file_pt);}
References oomph::FiniteElement::output().
output() [2/8]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::output (FILE * file_pt) inline virtual
C-style output function: Broken default.
Reimplemented from oomph::FiniteElement.
   {FiniteElement::output(file_pt);}
References oomph::FiniteElement::output().
output() [3/8]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::output (FILE * file_pt, const unsigned & n_plot) inline virtual
C-style output function: Broken default.
Reimplemented from oomph::FiniteElement.
   {FiniteElement::output(file_pt,n_plot);}
References oomph::FiniteElement::output().
output() [4/8]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::output (FILE * file_pt, const unsigned & n_plot) inline virtual
C-style output function: Broken default.
Reimplemented from oomph::FiniteElement.
   {FiniteElement::output(file_pt,n_plot);}
References oomph::FiniteElement::output().
output() [5/8]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::output (std::ostream & outfile) inline virtual
Overload the standard output function with the broken default.
Reimplemented from oomph::FiniteElement.
   {FiniteElement::output(outfile);}
References oomph::FiniteElement::output().
output() [6/8]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::output (std::ostream & outfile) inline virtual
Overload the standard output function with the broken default.
Reimplemented from oomph::FiniteElement.
   {FiniteElement::output(outfile);}
References oomph::FiniteElement::output().
output() [7/8]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::output (std::ostream & outfile, const unsigned & nplot) inline virtual
Output function:
x,y,u or x,y,z,u at Nplot^DIM plot points
Reimplemented from oomph::FiniteElement.
   {
    //vector of local coordinates
    Vector<double> s(2);
    // Tecplot header info
    outfile << this->tecplot_zone_string(nplot);
    // Loop over plot points
    unsigned num_plot_points=this->nplot_points(nplot);
    for (unsigned iplot=0;iplot<num_plot_points;iplot++)
     {
      // Get local coordinates of plot point
      this->get_s_plot(iplot,nplot,s);
      // Output the position of the plot point
      for(unsigned i=0;i<2;i++)
       {outfile << this->interpolated_x(s,i) << " ";}
      // Output the fluid velocities at the plot point
      for(unsigned i=0;i<3;i++)
       {outfile << this->interpolated_u_axi_nst(s,i) << " ";}
      // Output the fluid pressure at the plot point
      outfile << this->interpolated_p_axi_nst(s)  << " ";
      // Output the temperature at the plot point
      outfile << this->interpolated_u_axi_adv_diff(s) << " " << std::endl;
     }
    outfile << std::endl;
    // Write tecplot footer (e.g. FE connectivity lists)
    this->write_tecplot_zone_footer(outfile,nplot);
   }
References oomph::QElement< 2, NNODE_1D >::get_s_plot(), i, oomph::AxisymmetricNavierStokesEquations::interpolated_p_axi_nst(), oomph::AxisymAdvectionDiffusionEquations::interpolated_u_axi_adv_diff(), oomph::AxisymmetricNavierStokesEquations::interpolated_u_axi_nst(), oomph::FiniteElement::interpolated_x(), oomph::QElement< 2, NNODE_1D >::nplot_points(), s, oomph::QElement< 2, NNODE_1D >::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output() [8/8]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::output (std::ostream & outfile, const unsigned & nplot) inline virtual
Output function:
x,y,u or x,y,z,u at Nplot^DIM plot points
Reimplemented from oomph::FiniteElement.
   {
    //vector of local coordinates
    Vector<double> s(2);
    // Tecplot header info
    outfile << this->tecplot_zone_string(nplot);
    // Loop over plot points
    unsigned num_plot_points=this->nplot_points(nplot);
    for (unsigned iplot=0;iplot<num_plot_points;iplot++)
     {
      // Get local coordinates of plot point
      this->get_s_plot(iplot,nplot,s);
      // Output the position of the plot point
      for(unsigned i=0;i<2;i++)
       {outfile << this->interpolated_x(s,i) << " ";}
      // Output the fluid velocities at the plot point
      for(unsigned i=0;i<3;i++)
       {outfile << this->interpolated_u_axi_nst(s,i) << " ";}
      // Output the fluid pressure at the plot point
      outfile << this->interpolated_p_axi_nst(s)  << " ";
      // Output the temperature at the plot point
      outfile << this->interpolated_u_axi_adv_diff(s) << " " << std::endl;
     }
    outfile << std::endl;
    // Write tecplot footer (e.g. FE connectivity lists)
    this->write_tecplot_zone_footer(outfile,nplot);
   }
References oomph::QElement< 2, NNODE_1D >::get_s_plot(), i, oomph::AxisymmetricNavierStokesEquations::interpolated_p_axi_nst(), oomph::AxisymAdvectionDiffusionEquations::interpolated_u_axi_adv_diff(), oomph::AxisymmetricNavierStokesEquations::interpolated_u_axi_nst(), oomph::FiniteElement::interpolated_x(), oomph::QElement< 2, NNODE_1D >::nplot_points(), s, oomph::QElement< 2, NNODE_1D >::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output_fct() [1/4]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::output_fct (std::ostream & outfile, const unsigned & Nplot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) inline virtual
Output function for a time-dependent exact solution. Broken default
Reimplemented from oomph::FiniteElement.
   {
    FiniteElement::
     output_fct(outfile,Nplot,time,exact_soln_pt);
   }
References oomph::FiniteElement::output_fct().
output_fct() [2/4]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::output_fct (std::ostream & outfile, const unsigned & Nplot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) inline virtual
Output function for a time-dependent exact solution. Broken default
Reimplemented from oomph::FiniteElement.
   {
    FiniteElement::
     output_fct(outfile,Nplot,time,exact_soln_pt);
   }
References oomph::FiniteElement::output_fct().
output_fct() [3/4]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::output_fct (std::ostream & outfile, const unsigned & Nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) inline virtual
Output function for an exact solution: Broken default.
Reimplemented from oomph::FiniteElement.
   {FiniteElement::output_fct(outfile,Nplot,exact_soln_pt);}
References oomph::FiniteElement::output_fct().
output_fct() [4/4]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::output_fct (std::ostream & outfile, const unsigned & Nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) inline virtual
Output function for an exact solution: Broken default.
Reimplemented from oomph::FiniteElement.
   {FiniteElement::output_fct(outfile,Nplot,exact_soln_pt);}
References oomph::FiniteElement::output_fct().
ra() [1/2]
const double& oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::ra () const inline
Access function for the Rayleigh number (const version)
 {return *Ra_pt;}
References Ra_pt.
Referenced by fill_in_off_diagonal_jacobian_blocks_analytic(), and get_body_force_axi_nst().
ra() [2/2]
const double& oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::ra () const inline
Access function for the Rayleigh number (const version)
 {return *Ra_pt;}
References Ra_pt.
ra_pt() [1/2]
double* & oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::ra_pt () inline
Access function for the pointer to the Rayleigh number.
 {return Ra_pt;}
References Ra_pt.
Referenced by further_build().
ra_pt() [2/2]
double* & oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::ra_pt () inline
Access function for the pointer to the Rayleigh number.
 {return Ra_pt;}
References Ra_pt.
rebuild_from_sons() [1/2]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::rebuild_from_sons (Mesh *& mesh_pt) inline virtual
Call the rebuild_from_sons functions for each of the constituent multi-physics elements.
Implements oomph::RefineableElement.
   {
    RefineableQAxisymAdvectionDiffusionElement<3>::rebuild_from_sons(mesh_pt);
    RefineableAxisymmetricQCrouzeixRaviartElement::rebuild_from_sons(mesh_pt);
   }
References oomph::RefineableQAxisymAdvectionDiffusionElement< NNODE_1D >::rebuild_from_sons(), and oomph::RefineableAxisymmetricQCrouzeixRaviartElement::rebuild_from_sons().
rebuild_from_sons() [2/2]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::rebuild_from_sons (Mesh *& mesh_pt) inline virtual
Call the rebuild_from_sons functions for each of the constituent multi-physics elements.
Implements oomph::RefineableElement.
   {
    RefineableQAxisymAdvectionDiffusionElement<3>::rebuild_from_sons(mesh_pt);
    RefineableAxisymmetricQCrouzeixRaviartElement::rebuild_from_sons(mesh_pt);
   }
References oomph::RefineableQAxisymAdvectionDiffusionElement< NNODE_1D >::rebuild_from_sons(), and oomph::RefineableAxisymmetricQCrouzeixRaviartElement::rebuild_from_sons().
required_nvalue() [1/2]
unsigned oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::required_nvalue (const unsigned & n) const inline virtual
The required number of values stored at the nodes is the sum of the required values of the two single-physics elements. This step is generic for any composed element of this type.
Reimplemented from oomph::AxisymmetricQCrouzeixRaviartElement.
   {return (RefineableQAxisymAdvectionDiffusionElement<3>::required_nvalue(n) +
            RefineableAxisymmetricQCrouzeixRaviartElement::required_nvalue(n));}
References n, and oomph::AxisymmetricQCrouzeixRaviartElement::required_nvalue().
required_nvalue() [2/2]
unsigned oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::required_nvalue (const unsigned & n) const inline virtual
The required number of values stored at the nodes is the sum of the required values of the two single-physics elements. This step is generic for any composed element of this type.
Reimplemented from oomph::AxisymmetricQCrouzeixRaviartElement.
   {return (RefineableQAxisymAdvectionDiffusionElement<3>::required_nvalue(n) +
            RefineableAxisymmetricQCrouzeixRaviartElement::required_nvalue(n));}
References n, and oomph::AxisymmetricQCrouzeixRaviartElement::required_nvalue().
scalar_name_paraview() [1/2]
std::string oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::scalar_name_paraview (const unsigned & i) const inline virtual
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc. Can (should!) be overloaded with more meaningful names.
Reimplemented from oomph::FiniteElement.
   {
    return "V"+StringConversion::to_string(i);
   }
References i, and oomph::StringConversion::to_string().
scalar_name_paraview() [2/2]
std::string oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::scalar_name_paraview (const unsigned & i) const inline virtual
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc. Can (should!) be overloaded with more meaningful names.
Reimplemented from oomph::FiniteElement.
   {
    return "V"+StringConversion::to_string(i);
   }
References i, and oomph::StringConversion::to_string().
scalar_value_paraview() [1/2]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::scalar_value_paraview (std::ofstream & file_out, const unsigned & i, const unsigned & nplot) const inline virtual
Write values of the i-th scalar field at the plot points. Broken virtual. Needs to be implemented for each new specific element type. Temporary dummy
Reimplemented from oomph::FiniteElement.
  {
   throw OomphLibError(
    "This function hasn't been implemented for this element",
    OOMPH_CURRENT_FUNCTION,
    OOMPH_EXCEPTION_LOCATION);
  }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
scalar_value_paraview() [2/2]
void oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::scalar_value_paraview (std::ofstream & file_out, const unsigned & i, const unsigned & nplot) const inline virtual
Write values of the i-th scalar field at the plot points. Broken virtual. Needs to be implemented for each new specific element type. Temporary dummy
Reimplemented from oomph::FiniteElement.
  {
   throw OomphLibError(
    "This function hasn't been implemented for this element",
    OOMPH_CURRENT_FUNCTION,
    OOMPH_EXCEPTION_LOCATION);
  }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
u_index_axi_adv_diff() [1/2]
unsigned oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::u_index_axi_adv_diff () const inline virtual
Overload the index at which the temperature variable is stored. We choose to store is after the fluid velocities.
Reimplemented from oomph::AxisymAdvectionDiffusionEquations.
 {return 3;}
Referenced by fill_in_off_diagonal_jacobian_blocks_analytic().
u_index_axi_adv_diff() [2/2]
unsigned oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::u_index_axi_adv_diff () const inline virtual
Overload the index at which the temperature variable is stored. We choose to store is after the fluid velocities.
Reimplemented from oomph::AxisymAdvectionDiffusionEquations.
 {return 3;}
vertex_node_pt() [1/2]
Node* oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::vertex_node_pt (const unsigned & j) const inline virtual
Pointer to the j-th vertex node in the element, Call the geometric element's function.
Implements oomph::ElementWithZ2ErrorEstimator.
  {return QElement<2,3>::vertex_node_pt(j);}
References j.
vertex_node_pt() [2/2]
Node* oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::vertex_node_pt (const unsigned & j) const inline virtual
Pointer to the j-th vertex node in the element, Call the geometric element's function.
Implements oomph::ElementWithZ2ErrorEstimator.
  {return QElement<2,3>::vertex_node_pt(j);}
References j.
Member Data Documentation
Default_Physical_Constant_Value
double oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::Default_Physical_Constant_Value =0.0 static private
The static default value of the Rayleigh number.
Set the default value of the Rayleigh number to be zero.
Referenced by RefineableBuoyantQAxisymCrouzeixRaviartElement().
Ra_pt
double * oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement::Ra_pt private
Pointer to a new physical variable, the Rayleigh number.
Referenced by ra(), ra_pt(), and RefineableBuoyantQAxisymCrouzeixRaviartElement().
The documentation for this class was generated from the following file:
axisym_heat_sphere/axisym_buoyant_navier_stokes.h