MercuryDPM: Eigen::internal::Assignment< DstXprType, Inverse< XprType >, internal::assign_op< typename DstXprType::Scalar, typename XprType::Scalar >, Dense2Dense > Struct Template Reference
Eigen::internal::Assignment< DstXprType, Inverse< XprType >, internal::assign_op< typename DstXprType::Scalar, typename XprType::Scalar >, Dense2Dense > Struct Template Reference
#include <InverseImpl.h>
Public Types
typedef Inverse< XprType > SrcXprType
Static Public Member Functions
static EIGEN_DEVICE_FUNC void run (DstXprType &dst, const SrcXprType &src, const internal::assign_op< typename DstXprType::Scalar, typename XprType::Scalar > &)
Member Typedef Documentation
SrcXprType
template<typename DstXprType , typename XprType > typedef Inverse<XprType> Eigen::internal::Assignment< DstXprType, Inverse< XprType >, internal::assign_op< typename DstXprType::Scalar, typename XprType::Scalar >, Dense2Dense >::SrcXprType
Member Function Documentation
run()
template<typename DstXprType , typename XprType > static EIGEN_DEVICE_FUNC void Eigen::internal::Assignment< DstXprType, Inverse< XprType >, internal::assign_op< typename DstXprType::Scalar, typename XprType::Scalar >, Dense2Dense >::run (DstXprType & dst, const SrcXprType & src, const internal::assign_op< typename DstXprType::Scalar, typename XprType::Scalar > &) inline static
{
     Index dstRows = src.rows();
     Index dstCols = src.cols();
     if ((dst.rows() != dstRows) || (dst.cols() != dstCols)) dst.resize(dstRows, dstCols);
     const int Size = plain_enum_min(XprType::ColsAtCompileTime, DstXprType::ColsAtCompileTime);
     EIGEN_ONLY_USED_FOR_DEBUG(Size);
     eigen_assert(((Size <= 1) || (Size > 4) || (extract_data(src.nestedExpression()) != extract_data(dst))) &&
                  "Aliasing problem detected in inverse(), you need to do inverse().eval() here.");
     typedef typename internal::nested_eval<XprType, XprType::ColsAtCompileTime>::type ActualXprType;
     typedef internal::remove_all_t<ActualXprType> ActualXprTypeCleanded;
     ActualXprType actual_xpr(src.nestedExpression());
     compute_inverse<ActualXprTypeCleanded, DstXprType>::run(actual_xpr, dst);
   }
References Eigen::Inverse< XprType >::cols(), eigen_assert, EIGEN_ONLY_USED_FOR_DEBUG, Eigen::internal::extract_data(), Eigen::Inverse< XprType >::nestedExpression(), Eigen::internal::plain_enum_min(), Eigen::Inverse< XprType >::rows(), and Eigen::internal::compute_inverse< MatrixType, ResultType, Size >::run().
The documentation for this struct was generated from the following file:
InverseImpl.h