MercuryDPM: oomph::FluidInterfaceAdditionalValues< SurfactantTransportInterfaceElement > Class Reference
oomph::FluidInterfaceAdditionalValues< SurfactantTransportInterfaceElement > Class Reference
#include <surfactant_transport_elements.h>
Public Member Functions
FluidInterfaceAdditionalValues ()
unsigned nadditional_values (const unsigned &n)
void setup_equation_indices (SurfactantTransportInterfaceElement *const &element_pt, const unsigned &id)
Detailed Description
============================================================================= This is the policy class for the surfactanttransport equations which require one additional value for the surface concentration
Constructor & Destructor Documentation
FluidInterfaceAdditionalValues()
oomph::FluidInterfaceAdditionalValues< SurfactantTransportInterfaceElement >::FluidInterfaceAdditionalValues () inline
 {}
Member Function Documentation
nadditional_values()
unsigned oomph::FluidInterfaceAdditionalValues< SurfactantTransportInterfaceElement >::nadditional_values (const unsigned & n) inline
     {
       return 1;
     }
setup_equation_indices()
void oomph::FluidInterfaceAdditionalValues< SurfactantTransportInterfaceElement >::setup_equation_indices (SurfactantTransportInterfaceElement *const & element_pt, const unsigned & id) inline
     {
       const unsigned n_node = element_pt->nnode();
       Vector<unsigned> c_index(n_node);
       for (unsigned n = 0; n < n_node; n++)
       {
         c_index[n] = dynamic_cast<BoundaryNodeBase*>(element_pt->node_pt(n))
                        ->index_of_first_value_assigned_by_face_element(id);
       }
       element_pt->set_c_index(c_index);
     }
References n, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), and oomph::SurfactantTransportInterfaceElement::set_c_index().
The documentation for this class was generated from the following file:
surfactant_transport_elements.h