MercuryDPM: VTKData Class Reference
VTKData Class Reference
#include <VTKData.h>
Public Member Functions
VTKData ()=default
~VTKData ()=default
void addToPoints (Vec3D point)
Adds a point to the points vector.
void addToPointData (const std::string &key, Mdouble value)
Adds a value to the pointData values vector corresponding to the given key.
void addToConnectivity (const std::vector< size_t > &indices)
Adds a vector of indices to the connectivity vector.
void addToTypes (int type)
Adds a type to the types vector.
std::vector< Vec3D > getPoints () const
std::unordered_map< std::string, std::vector< Mdouble > > getPointData () const
std::vector< std::vector< size_t > > getConnectivity () const
std::vector< int > getTypes () const
void reservePoints (unsigned int n, const std::vector< std::string > &keys={})
Reserves additional memory for the points vector and optionally for the values vectors of the pointData.
void reserveCells (unsigned int n)
Reserves additional memory for connectivity and types vectors.
void writeVTKData (std::string fileName) const
Writes the data to a file with the given file name.
void writeVTKDataFromVtkContainer (std::string fileName, const std::vector< Vec3D > &points, const std::vector< std::vector< double >> &triangleStrips)
Private Member Functions
std::fstream makeVTKFileWithHeader (std::string &fileName) const
void writePoints (std::fstream &file) const
void writePointData (std::fstream &file) const
void writeConnectivity (std::fstream &file) const
void writeOffsets (std::fstream &file) const
void writeTypes (std::fstream &file) const
Private Attributes
std::vector< Vec3D > points_
std::unordered_map< std::string, std::vector< Mdouble > > pointData_
std::vector< std::vector< size_t > > connectivity_
std::vector< int > types_
Constructor & Destructor Documentation
VTKData()
VTKData::VTKData () default
~VTKData()
VTKData::~VTKData () default
Member Function Documentation
addToConnectivity()
void VTKData::addToConnectivity (const std::vector< size_t > & indices)
Adds a vector of indices to the connectivity vector.
Parameters
indices Vector of indices to be added
 {
     connectivity_.push_back(indices);
 }
References connectivity_.
Referenced by writeVTKDataFromVtkContainer().
addToPointData()
void VTKData::addToPointData (const std::string & key, Mdouble value)
Adds a value to the pointData values vector corresponding to the given key.
Parameters
key To which pointData values vector to add
value Value to be added
 {
     pointData_[key].push_back(value);
 }
References pointData_, and Eigen::value.
addToPoints()
void VTKData::addToPoints (Vec3D point)
Adds a point to the points vector.
Parameters
point Point to be added
 {
     points_.push_back(point);
 }
References points_.
Referenced by writeVTKDataFromVtkContainer().
addToTypes()
void VTKData::addToTypes (int type)
Adds a type to the types vector.
Parameters
type Type to be added
 {
     types_.push_back(type);
 }
References compute_granudrum_aor::type, and types_.
Referenced by writeVTKDataFromVtkContainer().
getConnectivity()
std::vector< std::vector< size_t > > VTKData::getConnectivity () const
Returns
Vector of vectors with indices
 {
     return connectivity_;
 }
References connectivity_.
getPointData()
std::unordered_map< std::string, std::vector< Mdouble > > VTKData::getPointData () const
Returns
Map of pointData, each having a key and a vector of values
 {
     return pointData_;
 }
References pointData_.
getPoints()
std::vector< Vec3D > VTKData::getPoints () const
Returns
Vector of points
 {
     return points_;
 }
References points_.
getTypes()
std::vector< int > VTKData::getTypes () const
Returns
Vector of types
 {
     return types_;
 }
References types_.
makeVTKFileWithHeader()
std::fstream VTKData::makeVTKFileWithHeader (std::string & fileName) const private
 {
     // Open output file
     std::fstream file;
     file.open(fileName.c_str(), std::ios_base::out);
     if (file.fail())
     {
         logger(WARN, "File % could not be opened", fileName);
     }
     // Write output file header
     file << "<?xml version=\"1.0\"?>\n";
     //file << "<!-- time " << handler_.getDPMBase()->getTime() << "-->\n"; //\todo JWB do we care about time?
     file << "<VTKFile type=\"UnstructuredGrid\" version=\"0.1\" byte_order=\"LittleEndian\">\n";
     file << "<UnstructuredGrid>\n";
     return file;
 }
References UniformPSDSelfTest::fileName, logger, out(), and WARN.
Referenced by writeVTKData().
reserveCells()
void VTKData::reserveCells (unsigned int n)
Reserves additional memory for connectivity and types vectors.
Parameters
n Number of new cells to reserve memory for
 {
     unsigned int nt = connectivity_.size() + n;
     connectivity_.reserve(nt);
     types_.reserve(nt);
 }
References connectivity_, n, and types_.
reservePoints()
void VTKData::reservePoints (unsigned int n, const std::vector< std::string > & keys = {})
Reserves additional memory for the points vector and optionally for the values vectors of the pointData.
Parameters
n Number of new points to reserve memory for
keys Keys for pointData values vectors to reserve memory for
 {
     unsigned int nt = points_.size() + n;
     points_.reserve(nt);
     for (const std::string& key : keys)
         pointData_[key].reserve(nt);
 }
References n, pointData_, points_, and oomph::Global_string_for_annotation::string().
writeConnectivity()
void VTKData::writeConnectivity (std::fstream & file) const private
 {
     file << "  <DataArray type=\"Int32\" Name=\"connectivity\" format=\"ascii\">\n";
     for (const std::vector<size_t>& vec : connectivity_)
     {
         file << "\t";
         for (const int i : vec)
         {
             file << i << " ";
         }
         file << "\n";
     }
     file << "  </DataArray>\n";
 }
References connectivity_, and i.
Referenced by writeVTKData().
writeOffsets()
void VTKData::writeOffsets (std::fstream & file) const private
 {
     file << "  <DataArray type=\"Int32\" Name=\"offsets\" format=\"ascii\">\n";
     unsigned int offset = 0;
     for (const std::vector<size_t>& vec : connectivity_)
     {
         offset += vec.size();
         file << "\t" << offset << "\n";
     }
     file << "  </DataArray>\n";
 }
References connectivity_.
Referenced by writeVTKData().
writePointData()
void VTKData::writePointData (std::fstream & file) const private
 {
     file << "<PointData Vectors=\"vector\">\n";
     for (const auto& da : pointData_)
     {
         const std::string& name = da.first;
         const std::vector<Mdouble>& values = da.second;
         unsigned int numberOfComponents = points_.size() / values.size();
         file << "  <DataArray type=\"Float32\" Name=\"" << name << "\" NumberOfComponents=\"" << numberOfComponents << "\" format=\"ascii\">\n";
         int i = 0;
         while (i < values.size())
         {
             file << "\t";
             for (int j = 0; j < numberOfComponents; j++)
             {
                 file << values[i++] << " ";
             }
             file << "\n";
         }
         file << "  </DataArray>\n";
     }
     file << "</PointData>\n";
 }
References i, j, plotDoE::name, pointData_, points_, and oomph::Global_string_for_annotation::string().
Referenced by writeVTKData().
writePoints()
void VTKData::writePoints (std::fstream & file) const private
 {
     file << "<Points>\n";
     file << "  <DataArray type=\"Float32\" Name=\"Position\" NumberOfComponents=\"3\" format=\"ascii\">\n";
     for (const Vec3D p : points_)
     {
         file << "\t" << p << "\n";
     }
     file << "  </DataArray>\n";
     file << "</Points>\n";
 }
References p, and points_.
Referenced by writeVTKData().
writeTypes()
void VTKData::writeTypes (std::fstream & file) const private
 {
     file << "  <DataArray type=\"UInt8\"  Name=\"types\" format=\"ascii\">\n";
     for (const int i : types_)
     {
         file << "\t" << i << "\n";
     }
     file << "  </DataArray>\n";
 }
References i, and types_.
Referenced by writeVTKData().
writeVTKData()
void VTKData::writeVTKData (std::string fileName) const
Writes the data to a file with the given file name.
Parameters
fileName Full filename, e.g. Example.vtu
 {
     std::fstream file = makeVTKFileWithHeader(fileName);
     file << "<Piece NumberOfPoints=\"" + std::to_string(points_.size()) + "\" NumberOfCells=\"" + std::to_string(connectivity_.size()) + "\">\n";
     writePoints(file);
     writePointData(file);
     file << "<Cells>\n";
     writeConnectivity(file);
     writeOffsets(file);
     writeTypes(file);
     file << "</Cells>\n";
     file << "</Piece>\n";
     file << "</UnstructuredGrid>\n";
     file << "</VTKFile>\n";
     // Close output file
     file.close();
 }
References connectivity_, UniformPSDSelfTest::fileName, makeVTKFileWithHeader(), points_, oomph::StringConversion::to_string(), writeConnectivity(), writeOffsets(), writePointData(), writePoints(), and writeTypes().
Referenced by WallDetailsVTKWriter::writeVTK(), and writeVTKDataFromVtkContainer().
writeVTKDataFromVtkContainer()
void VTKData::writeVTKDataFromVtkContainer (std::string fileName, const std::vector< Vec3D > & points, const std::vector< std::vector< double >> & triangleStrips)
 {
     for (auto& p : points)
         addToPoints(p);
     for (auto& c : triangleStrips)
     {
         std::vector<size_t> cell;
         for (auto& cc : c)
             cell.push_back(static_cast<size_t>(cc));
         addToConnectivity(cell);
         addToTypes(6);
     }
     writeVTKData(fileName);
 }
References addToConnectivity(), addToPoints(), addToTypes(), calibrate::c, UniformPSDSelfTest::fileName, p, and writeVTKData().
Member Data Documentation
connectivity_
std::vector<std::vector<size_t> > VTKData::connectivity_ private
The connectivity 2D vector, connecting points
Referenced by addToConnectivity(), getConnectivity(), reserveCells(), writeConnectivity(), writeOffsets(), and writeVTKData().
pointData_
std::unordered_map<std::string, std::vector<Mdouble> > VTKData::pointData_ private
The point data, corresponding to each point
Referenced by addToPointData(), getPointData(), reservePoints(), and writePointData().
points_
std::vector<Vec3D> VTKData::points_ private
The 3D positions
Referenced by addToPoints(), getPoints(), reservePoints(), writePointData(), writePoints(), and writeVTKData().
types_
std::vector<int> VTKData::types_ private
The types, corresponding to each row of the connectivity 2D vector
Referenced by addToTypes(), getTypes(), reserveCells(), and writeTypes().
The documentation for this class was generated from the following files:
Kernel/VTKWriter/VTKData.h
VTKData.cc