MercuryDPM: Eigen::internal::TensorExecutor< Expression, Device, Vectorizable, Tiling > Class Template Reference
Eigen::internal::TensorExecutor< Expression, Device, Vectorizable, Tiling > Class Template Reference
#include <TensorExecutor.h>
Public Types
typedef Expression::Index StorageIndex
Static Public Member Functions
static EIGEN_STRONG_INLINE void run (const Expression &expr, const Device &device=DefaultDevice())
Detailed Description
template<typename Expression, typename Device, bool Vectorizable, TiledEvaluation Tiling>
class Eigen::internal::TensorExecutor< Expression, Device, Vectorizable, Tiling >
Default strategy: the expression is evaluated sequentially with a single cpu thread, without vectorization and block evaluation.
Member Typedef Documentation
StorageIndex
template<typename Expression , typename Device , bool Vectorizable, TiledEvaluation Tiling> typedef Expression::Index Eigen::internal::TensorExecutor< Expression, Device, Vectorizable, Tiling >::StorageIndex
Member Function Documentation
run()
template<typename Expression , typename Device , bool Vectorizable, TiledEvaluation Tiling> static EIGEN_STRONG_INLINE void Eigen::internal::TensorExecutor< Expression, Device, Vectorizable, Tiling >::run (const Expression & expr, const Device & device = DefaultDevice()) inline static
{
     TensorEvaluator<Expression, Device> evaluator(expr, device);
     const bool needs_assign = evaluator.evalSubExprsIfNeeded(NULL);
     if (needs_assign) {
       const StorageIndex size = array_prod(evaluator.dimensions());
       for (StorageIndex i = 0; i < size; ++i) {
         evaluator.evalScalar(i);
       }
     }
     evaluator.cleanup();
   }
References Eigen::internal::array_prod(), i, and size.
Referenced by Eigen::TensorDevice< ExpressionType, DeviceType >::operator+=(), Eigen::TensorDevice< ExpressionType, DeviceType >::operator-=(), Eigen::TensorBase< Derived, AccessLevel >::operator=(), Eigen::TensorDevice< ExpressionType, DeviceType >::operator=(), Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::operator=(), Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Device >::preloadKernel(), Eigen::TensorEvaluator< const TensorConvolutionOp< Indices, InputArgType, KernelArgType >, Eigen::SyclDevice >::preloadKernel(), Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::Tensor(), and Eigen::TensorFixedSize< Scalar_, Dimensions_, Options_, IndexType >::TensorFixedSize().
The documentation for this class was generated from the following file:
TensorExecutor.h