MercuryDPM: Eigen::TensorStorage< T, DSizes< IndexType, NumIndices_ >, Options_ > Class Template Reference
Eigen::TensorStorage< T, DSizes< IndexType, NumIndices_ >, Options_ > Class Template Reference
#include <TensorStorage.h>
Public Types
typedef IndexType Index
typedef DSizes< IndexType, NumIndices_ > Dimensions
typedef TensorStorage< T, DSizes< IndexType, NumIndices_ >, Options_ > Self
Public Member Functions
EIGEN_DEVICE_FUNC TensorStorage ()
EIGEN_DEVICE_FUNC TensorStorage (Index size, const array< Index, NumIndices_ > &dimensions)
template<typename... DenseIndex>
EIGEN_DEVICE_FUNC TensorStorage (DenseIndex... indices)
EIGEN_DEVICE_FUNC TensorStorage (const Self &other)
EIGEN_DEVICE_FUNC Self & operator= (const Self &other)
EIGEN_DEVICE_FUNC TensorStorage (Self &&other)
EIGEN_DEVICE_FUNC Self & operator= (Self &&other)
EIGEN_DEVICE_FUNC ~TensorStorage ()
EIGEN_DEVICE_FUNC void swap (Self &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions & dimensions () const
EIGEN_DEVICE_FUNC void resize (Index size, const array< Index, NumIndices_ > &nbDimensions)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T * data ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const T * data () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index size () const
Private Attributes
T * m_data
Dimensions m_dimensions
Member Typedef Documentation
Dimensions
template<typename T , typename IndexType , int NumIndices_, int Options_> typedef DSizes<IndexType, NumIndices_> Eigen::TensorStorage< T, DSizes< IndexType, NumIndices_ >, Options_ >::Dimensions
Index
template<typename T , typename IndexType , int NumIndices_, int Options_> typedef IndexType Eigen::TensorStorage< T, DSizes< IndexType, NumIndices_ >, Options_ >::Index
Self
template<typename T , typename IndexType , int NumIndices_, int Options_> typedef TensorStorage<T, DSizes<IndexType, NumIndices_>, Options_> Eigen::TensorStorage< T, DSizes< IndexType, NumIndices_ >, Options_ >::Self
Constructor & Destructor Documentation
TensorStorage() [1/5]
template<typename T , typename IndexType , int NumIndices_, int Options_> EIGEN_DEVICE_FUNC Eigen::TensorStorage< T, DSizes< IndexType, NumIndices_ >, Options_ >::TensorStorage () inline
                                     : m_data(0), m_dimensions() {
     if (NumIndices_ == 0) {
       m_data = internal::conditional_aligned_new_auto<T, (Options_ & DontAlign) == 0>(1);
     }
   }
References Eigen::TensorStorage< T, FixedDimensions, Options_ >::m_data.
TensorStorage() [2/5]
template<typename T , typename IndexType , int NumIndices_, int Options_> EIGEN_DEVICE_FUNC Eigen::TensorStorage< T, DSizes< IndexType, NumIndices_ >, Options_ >::TensorStorage (Index size, const array< Index, NumIndices_ > & dimensions) inline
       : m_data(internal::conditional_aligned_new_auto<T, (Options_ & DontAlign) == 0>(size)), m_dimensions(dimensions) {
     EIGEN_INTERNAL_TENSOR_STORAGE_CTOR_PLUGIN
   }
References EIGEN_INTERNAL_TENSOR_STORAGE_CTOR_PLUGIN.
TensorStorage() [3/5]
template<typename T , typename IndexType , int NumIndices_, int Options_> template<typename... DenseIndex> EIGEN_DEVICE_FUNC Eigen::TensorStorage< T, DSizes< IndexType, NumIndices_ >, Options_ >::TensorStorage (DenseIndex... indices) inline
                                                          : m_dimensions(indices...) {
     m_data = internal::conditional_aligned_new_auto<T, (Options_ & DontAlign) == 0>(internal::array_prod(m_dimensions));
   }
References Eigen::internal::array_prod(), and Eigen::TensorStorage< T, FixedDimensions, Options_ >::m_data.
TensorStorage() [4/5]
template<typename T , typename IndexType , int NumIndices_, int Options_> EIGEN_DEVICE_FUNC Eigen::TensorStorage< T, DSizes< IndexType, NumIndices_ >, Options_ >::TensorStorage (const Self & other) inline
       : m_data(internal::conditional_aligned_new_auto<T, (Options_ & DontAlign) == 0>(
             internal::array_prod(other.m_dimensions))),
         m_dimensions(other.m_dimensions) {
     internal::smart_copy(other.m_data, other.m_data + internal::array_prod(other.m_dimensions), m_data);
   }
References Eigen::internal::array_prod(), Eigen::TensorStorage< T, FixedDimensions, Options_ >::m_data, m_data, m_dimensions, and Eigen::internal::smart_copy().
TensorStorage() [5/5]
template<typename T , typename IndexType , int NumIndices_, int Options_> EIGEN_DEVICE_FUNC Eigen::TensorStorage< T, DSizes< IndexType, NumIndices_ >, Options_ >::TensorStorage (Self && other) inline
 : TensorStorage() { *this = std::move(other); }
~TensorStorage()
template<typename T , typename IndexType , int NumIndices_, int Options_> EIGEN_DEVICE_FUNC Eigen::TensorStorage< T, DSizes< IndexType, NumIndices_ >, Options_ >::~TensorStorage () inline
{
     internal::conditional_aligned_delete_auto<T, (Options_ & DontAlign) == 0>(m_data,
                                                                               internal::array_prod(m_dimensions));
   }
References Eigen::internal::array_prod(), and Eigen::TensorStorage< T, FixedDimensions, Options_ >::m_data.
Member Function Documentation
data() [1/2]
template<typename T , typename IndexType , int NumIndices_, int Options_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T* Eigen::TensorStorage< T, DSizes< IndexType, NumIndices_ >, Options_ >::data () inline
 { return m_data; }
References Eigen::TensorStorage< T, FixedDimensions, Options_ >::m_data.
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
data() [2/2]
template<typename T , typename IndexType , int NumIndices_, int Options_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const T* Eigen::TensorStorage< T, DSizes< IndexType, NumIndices_ >, Options_ >::data () const inline
 { return m_data; }
References Eigen::TensorStorage< T, FixedDimensions, Options_ >::m_data.
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
dimensions()
template<typename T , typename IndexType , int NumIndices_, int Options_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions& Eigen::TensorStorage< T, DSizes< IndexType, NumIndices_ >, Options_ >::dimensions () const inline
 { return m_dimensions; }
operator=() [1/2]
template<typename T , typename IndexType , int NumIndices_, int Options_> EIGEN_DEVICE_FUNC Self& Eigen::TensorStorage< T, DSizes< IndexType, NumIndices_ >, Options_ >::operator= (const Self & other) inline
{
     if (this != &other) {
       Self tmp(other);
       this->swap(tmp);
     }
     return *this;
   }
References Eigen::swap(), and tmp.
operator=() [2/2]
template<typename T , typename IndexType , int NumIndices_, int Options_> EIGEN_DEVICE_FUNC Self& Eigen::TensorStorage< T, DSizes< IndexType, NumIndices_ >, Options_ >::operator= (Self && other) inline
{
     numext::swap(m_data, other.m_data);
     numext::swap(m_dimensions, other.m_dimensions);
     return *this;
   }
References Eigen::TensorStorage< T, FixedDimensions, Options_ >::m_data, and Eigen::numext::swap().
resize()
template<typename T , typename IndexType , int NumIndices_, int Options_> EIGEN_DEVICE_FUNC void Eigen::TensorStorage< T, DSizes< IndexType, NumIndices_ >, Options_ >::resize (Index size, const array< Index, NumIndices_ > & nbDimensions) inline
{
     const Index currentSz = internal::array_prod(m_dimensions);
     if (size != currentSz) {
       internal::conditional_aligned_delete_auto<T, (Options_ & DontAlign) == 0>(m_data, currentSz);
       if (size)
         m_data = internal::conditional_aligned_new_auto<T, (Options_ & DontAlign) == 0>(size);
       else if (NumIndices_ == 0) {
         m_data = internal::conditional_aligned_new_auto<T, (Options_ & DontAlign) == 0>(1);
       } else
         m_data = 0;
       EIGEN_INTERNAL_DENSE_STORAGE_CTOR_PLUGIN({})
     }
     m_dimensions = nbDimensions;
   }
References Eigen::internal::array_prod(), EIGEN_INTERNAL_DENSE_STORAGE_CTOR_PLUGIN, Eigen::TensorStorage< T, FixedDimensions, Options_ >::m_data, and Eigen::TensorStorage< T, FixedDimensions, Options_ >::size().
size()
template<typename T , typename IndexType , int NumIndices_, int Options_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorStorage< T, DSizes< IndexType, NumIndices_ >, Options_ >::size () const inline
 { return m_dimensions.TotalSize(); }
swap()
template<typename T , typename IndexType , int NumIndices_, int Options_> EIGEN_DEVICE_FUNC void Eigen::TensorStorage< T, DSizes< IndexType, NumIndices_ >, Options_ >::swap (Self & other) inline
{
     numext::swap(m_data, other.m_data);
     numext::swap(m_dimensions, other.m_dimensions);
   }
References Eigen::TensorStorage< T, FixedDimensions, Options_ >::m_data, m_data, m_dimensions, and Eigen::numext::swap().
Member Data Documentation
m_data
template<typename T , typename IndexType , int NumIndices_, int Options_> T* Eigen::TensorStorage< T, DSizes< IndexType, NumIndices_ >, Options_ >::m_data private
Referenced by swap(), and TensorStorage().
m_dimensions
template<typename T , typename IndexType , int NumIndices_, int Options_> Dimensions Eigen::TensorStorage< T, DSizes< IndexType, NumIndices_ >, Options_ >::m_dimensions private
Referenced by swap(), and TensorStorage().
The documentation for this class was generated from the following file:
TensorStorage.h