MercuryDPM: Eigen::internal::image_retval< FullPivLU< MatrixType_, PermutationIndex_ > > Struct Template Reference
Eigen::internal::image_retval< FullPivLU< MatrixType_, PermutationIndex_ > > Struct Template Reference
#include <FullPivLU.h>
Public Types
enum { MaxSmallDimAtCompileTime = min_size_prefer_fixed(MatrixType::MaxColsAtCompileTime, MatrixType::MaxRowsAtCompileTime) }
using DecompositionType = FullPivLU< MatrixType_, PermutationIndex_ >
Public Types inherited from Eigen::internal::image_retval_base< FullPivLU< MatrixType_, PermutationIndex_ > >
typedef FullPivLU< MatrixType_, PermutationIndex_ > DecompositionType
typedef DecompositionType::MatrixType MatrixType
typedef ReturnByValue< image_retval_base > Base
Public Types inherited from Eigen::ReturnByValue< Derived >
typedef internal::traits< Derived >::ReturnType ReturnType
typedef internal::dense_xpr_base< ReturnByValue >::type Base
Public Member Functions
template<typename Dest >
void evalTo (Dest &dst) const
Public Member Functions inherited from Eigen::internal::image_retval_base< FullPivLU< MatrixType_, PermutationIndex_ > >
image_retval_base (const DecompositionType &dec, const MatrixType &originalMatrix)
Index rows () const
Index cols () const
Index rank () const
const DecompositionType & dec () const
const MatrixType & originalMatrix () const
void evalTo (Dest &dst) const
Public Member Functions inherited from Eigen::ReturnByValue< Derived >
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
const Unusable & coeff (Index) const
const Unusable & coeff (Index, Index) const
Unusable & coeffRef (Index)
Unusable & coeffRef (Index, Index)
Additional Inherited Members
Protected Attributes inherited from Eigen::internal::image_retval_base< FullPivLU< MatrixType_, PermutationIndex_ > >
const DecompositionType & m_dec
Index m_rank
Index m_cols
const MatrixType & m_originalMatrix
Member Typedef Documentation
DecompositionType
template<typename MatrixType_ , typename PermutationIndex_ > using Eigen::internal::image_retval< FullPivLU< MatrixType_, PermutationIndex_ > >::DecompositionType = FullPivLU<MatrixType_, PermutationIndex_>
Member Enumeration Documentation
anonymous enum
template<typename MatrixType_ , typename PermutationIndex_ > anonymous enum
Enumerator
MaxSmallDimAtCompileTime
        {
     MaxSmallDimAtCompileTime = min_size_prefer_fixed(MatrixType::MaxColsAtCompileTime, MatrixType::MaxRowsAtCompileTime)
   };
Member Function Documentation
evalTo()
template<typename MatrixType_ , typename PermutationIndex_ > template<typename Dest > void Eigen::internal::image_retval< FullPivLU< MatrixType_, PermutationIndex_ > >::evalTo (Dest & dst) const inline
{
     using std::abs;
     if (rank() == 0) {
       // The Image is just {0}, so it doesn't have a basis properly speaking, but let's
       // avoid crashing/asserting as that depends on floating point calculations. Let's
       // just return a single column vector filled with zeros.
       dst.setZero();
       return;
     }
     Matrix<Index, Dynamic, 1, 0, MaxSmallDimAtCompileTime, 1> pivots(rank());
     RealScalar premultiplied_threshold = dec().maxPivot() * dec().threshold();
     Index p = 0;
     for (Index i = 0; i < dec().nonzeroPivots(); ++i)
       if (abs(dec().matrixLU().coeff(i, i)) > premultiplied_threshold) pivots.coeffRef(p++) = i;
     eigen_internal_assert(p == rank());
     for (Index i = 0; i < rank(); ++i)
       dst.col(i) = originalMatrix().col(dec().permutationQ().indices().coeff(pivots.coeff(i)));
   }
References abs(), Eigen::PlainObjectBase< Derived >::coeff(), Eigen::Matrix< Scalar_, Rows_, Cols_, Options_, MaxRows_, MaxCols_ >::coeffRef(), eigen_internal_assert, i, and p.
The documentation for this struct was generated from the following file:
FullPivLU.h