MercuryDPM: oomph::QSpectralElement< 1, NNODE_1D > Class Template Reference
oomph::QSpectralElement< 1, NNODE_1D > Class Template Reference
General QSpectralElement class specialised to one spatial dimension.
#include <Qspectral_elements.h>
Public Member Functions
QSpectralElement ()
Constructor.
double s_min () const
Min. value of local coordinate.
double s_max () const
Max. value of local coordinate.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
void local_coordinate_of_node (const unsigned &n, Vector< double > &s) const
Get local coordinates of node j in the element; vector sets its own size.
void local_fraction_of_node (const unsigned &n, Vector< double > &s_fraction)
Get the local fractino of node j in the element.
double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
The local one-d fraction is the same.
void shape (const Vector< double > &s, Shape &psi) const
Calculate the geometric shape functions at local coordinate s.
void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
Derivatives of shape functions for specific QSpectralElement<1,..>
void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
unsigned nnode_1d () const
Number of nodes along each element edge.
void output (FILE *file_pt)
C-style output.
void output (FILE *file_pt, const unsigned &n_plot)
C_style output at n_plot points.
void output (std::ostream &outfile)
Output.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at n_plot points.
void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &use_equally_spaced_interior_sample_points=false) const
std::string tecplot_zone_string (const unsigned &nplot) const
unsigned nplot_points (const unsigned &nplot) const
void build_face_element (const int &face_index, FaceElement *face_element_pt)
Public Member Functions inherited from oomph::SpectralElement
SpectralElement ()
virtual ~SpectralElement ()
Data * spectral_data_pt (const unsigned &i) const
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
unsigned nspectral () const
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
virtual void disable_ALE ()
virtual void enable_ALE ()
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output an exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output a time-dependent exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::LineElementBase
LineElementBase ()
Constructor. Empty.
Public Member Functions inherited from oomph::QElementBase
QElementBase ()
Constructor: Initialise pointers to macro element reference coords.
QElementBase (const QElementBase &)=delete
Broken copy constructor.
virtual ~QElementBase ()
Broken assignment operator.
bool local_coord_is_valid (const Vector< double > &s)
Check whether the local coordinate are valid or not.
void move_local_coord_back_into_element (Vector< double > &s) const
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
double & s_macro_ll (const unsigned &i)
double & s_macro_ur (const unsigned &i)
double s_macro_ll (const unsigned &i) const
double s_macro_ur (const unsigned &i) const
void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
unsigned nnode_on_face () const
ElementGeometry::ElementGeometry element_geometry () const
It's a Q element!
Public Member Functions inherited from oomph::QElementGeometricBase
QElementGeometricBase ()
Empty default constructor.
QElementGeometricBase (const QElementGeometricBase &)=delete
Broken copy constructor.
Static Private Attributes
static GaussLobattoLegendre< 1, NNODE_1D > integral
Assign the static integral.
Additional Inherited Members
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
virtual void fill_in_contribution_to_residuals (Vector< double > &residuals)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Attributes inherited from oomph::SpectralElement
Vector< Data * > * Spectral_data_pt
Additional Storage for shared spectral data.
Vector< unsigned > Spectral_order
Vector that represents the spectral order in each dimension.
Vector< unsigned > Nodal_spectral_order
Vector that represents the nodal spectral order.
DenseMatrix< int > Spectral_local_eqn
Local equation numbers for the spectral degrees of freedom.
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
template<unsigned NNODE_1D>
class oomph::QSpectralElement< 1, NNODE_1D >
General QSpectralElement class specialised to one spatial dimension.
Constructor & Destructor Documentation
QSpectralElement()
template<unsigned NNODE_1D> oomph::QSpectralElement< 1, NNODE_1D >::QSpectralElement () inline
Constructor.
     {
       // There are NNODE_1D nodes in this element
       this->set_n_node(NNODE_1D);
       Spectral_order.resize(1, NNODE_1D);
       Nodal_spectral_order.resize(1, NNODE_1D);
       // Set the elemental and nodal dimensions
       this->set_dimension(1);
       // Assign integral point
       this->set_integration_scheme(&integral);
       // Calculate the nodal positions for the shape functions
       OneDimensionalLegendreShape<NNODE_1D>::calculate_nodal_positions();
       // OneDLegendreShapeParam::calculate_nodal_positions(NNODE_1D);
     }
References oomph::OneDimensionalLegendreShape< NNODE_1D >::calculate_nodal_positions().
Member Function Documentation
build_face_element()
template<unsigned NNODE_1D> void oomph::QSpectralElement< 1, NNODE_1D >::build_face_element (const int & face_index, FaceElement * face_element_pt) virtual
Build the lower-dimensional FaceElement (an element of type QSpectralElement<0,NNODE_1D>). The face index takes two values corresponding to the two possible faces: -1 (Left) s[0] = -1.0 +1 (Right) s[0] = 1.0
Function to setup geometrical information for lower-dimensional FaceElements (which are of type QSpectralElement<0,1>).
Reimplemented from oomph::FiniteElement.
   {
     /*throw OomphLibError("Untested",
       OOMPH_CURRENT_FUNCTION,
                         OOMPH_EXCEPTION_LOCATION);*/
     // Overload the nodal dimension by reading out the value from the node
     face_element_pt->set_nodal_dimension(this->node_pt(0)->ndim());
     // Set the pointer to the "bulk" element
     face_element_pt->bulk_element_pt() = this;
 #ifdef OOMPH_HAS_MPI
     // If the bulk element is halo then the face element must be too
     // if (this->is_halo())
     {
       face_element_pt->set_halo(Non_halo_proc_ID);
     }
 #endif
     // Resize the storage for the original number of values at the (one and
     // only) node of the face element.
     face_element_pt->nbulk_value_resize(1);
     // Resize the storage for the bulk node number corresponding to the (one
     // and only) node of the face element
     face_element_pt->bulk_node_number_resize(1);
     // Set the face index in the face element
     face_element_pt->face_index() = face_index;
     // Now set up the node pointer
     // The convention is that the "normal", should always point
     // out of the element
     switch (face_index)
     {
         // Bottom, normal sign is negative (coordinate points into element)
       case (-1):
         face_element_pt->node_pt(0) = this->node_pt(0);
         face_element_pt->bulk_node_number(0) = 0;
         face_element_pt->normal_sign() = -1;
         // Set the pointer to the function that determines the bulk coordinates
         // in the face element
         face_element_pt->face_to_bulk_coordinate_fct_pt() =
           &QElement1FaceToBulkCoordinates::face0;
         // Set the pointer to the function that determines the mapping of
         // derivatives
         face_element_pt->bulk_coordinate_derivatives_fct_pt() =
           &QElement1BulkCoordinateDerivatives::faces0;
         // Set the number of values stored when the node is part of the "bulk"
         // element. The required_nvalue() must be used, rather than nvalue(),
         // because otherwise nodes on boundaries will be resized multiple
         // times. If you want any other behaviour, you MUST set nbulk_value()
         // manually after construction of your specific face element.
         face_element_pt->nbulk_value(0) = this->required_nvalue(0);
         break;
         // Top, normal sign is positive (coordinate points out of element)
       case (1):
         face_element_pt->node_pt(0) = this->node_pt(NNODE_1D - 1);
         face_element_pt->bulk_node_number(0) = NNODE_1D - 1;
         face_element_pt->normal_sign() = +1;
         // Set the pointer to the function that determines the bulk coordinates
         // in the face element
         face_element_pt->face_to_bulk_coordinate_fct_pt() =
           &QElement1FaceToBulkCoordinates::face1;
         // Set the pointer to the function that determines the mapping of
         // derivatives
         face_element_pt->bulk_coordinate_derivatives_fct_pt() =
           &QElement1BulkCoordinateDerivatives::faces0;
         // Set the number of values stored when the node is part of the "bulk"
         // element.
         face_element_pt->nbulk_value(0) = this->required_nvalue(NNODE_1D - 1);
         break;
         // Other cases
       default:
         std::ostringstream error_message;
         error_message << "Face_index should only take "
                       << "the values +/-1, not " << face_index << std::endl;
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
     }
   }
References oomph::FaceElement::bulk_coordinate_derivatives_fct_pt(), oomph::FaceElement::bulk_element_pt(), oomph::FaceElement::bulk_node_number(), oomph::FaceElement::bulk_node_number_resize(), oomph::QElement1FaceToBulkCoordinates::face0(), oomph::QElement1FaceToBulkCoordinates::face1(), oomph::FaceElement::face_index(), oomph::FaceElement::face_to_bulk_coordinate_fct_pt(), oomph::QElement1BulkCoordinateDerivatives::faces0(), oomph::FaceElement::nbulk_value(), oomph::FaceElement::nbulk_value_resize(), oomph::FiniteElement::node_pt(), oomph::FaceElement::normal_sign(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::FiniteElement::set_nodal_dimension().
d2shape_local()
template<unsigned NNODE_1D> void oomph::QSpectralElement< 1, NNODE_1D >::d2shape_local (const Vector< double > & s, Shape & psi, DShape & dpsids, DShape & d2psids) const inline virtual
Compute the geometric shape functions, derivatives and second derivatives w.r.t. local coordinates at local coordinate s d2psids(i,0) = \(d^2 \psi_j / d s^2 \)
Second derivatives of shape functions for specific QSpectralElement<1,..> d2psids(i,0) = \(d^2 \psi_j / d s^2 \)
Reimplemented from oomph::FiniteElement.
   {
     std::ostringstream error_message;
     error_message
       << "\nd2shpe_local currently not implemented for this element\n";
     throw OomphLibError(
       error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     /*  //Call the shape functions and derivatives */
     /*  OneDimensionalShape<NNODE_1D> psi1(s[0]); */
     /*  OneDimensionalDShape<NNODE_1D> dpsi1ds(s[0]); */
     /*  OneDimensionalD2Shape<NNODE_1D> d2psi1ds(s[0]); */
     /*  //Loop over shape functions in element and assign to psi */
     /*  for(unsigned l=0;l<NNODE_1D;l++)  */
     /*   { */
     /*    psi[l] = psi1[l]; */
     /*    dpsids[l][0] = dpsi1ds[l]; */
     /*    d2psids[l][0] = d2psi1ds[l]; */
     /*   } */
   }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
dshape_local()
template<unsigned NNODE_1D> void oomph::QSpectralElement< 1, NNODE_1D >::dshape_local (const Vector< double > & s, Shape & psi, DShape & dpsids) const inline virtual
Derivatives of shape functions for specific QSpectralElement<1,..>
Compute the geometric shape functions and derivatives w.r.t. local coordinates at local coordinate s
Reimplemented from oomph::FiniteElement.
   {
     // Call the shape functions and derivatives
     OneDimensionalLegendreShape<NNODE_1D> psi1(s[0]);
     OneDimensionalLegendreDShape<NNODE_1D> dpsi1ds(s[0]);
     // OneDLegendreShapeParam psi1(NNODE_1D,s[0]);
     // OneDLegendreDShapeParam dpsi1ds(NNODE_1D,s[0]);
     // Loop over shape functions in element and assign to psi
     for (unsigned l = 0; l < NNODE_1D; l++)
     {
       psi(l) = psi1[l];
       dpsids(l, 0) = dpsi1ds[l];
     }
   }
References s.
get_s_plot()
template<unsigned NNODE_1D> void oomph::QSpectralElement< 1, NNODE_1D >::get_s_plot (const unsigned & i, const unsigned & nplot, Vector< double > & s, const bool & use_equally_spaced_interior_sample_points = false) const inline virtual
Get cector of local coordinates of plot point i (when plotting nplot points in each "coordinate direction).
Reimplemented from oomph::FiniteElement.
     {
       if (nplot > 1)
       {
         s[0] = -1.0 + 2.0 * double(i) / double(nplot - 1);
         if (use_equally_spaced_interior_sample_points)
         {
           double range = 2.0;
           double dx_new = range / double(nplot);
           double range_new = double(nplot - 1) * dx_new;
           s[0] = -1.0 + 0.5 * dx_new + range_new * (1.0 + s[0]) / range;
         }
       }
       else
       {
         s[0] = 0.0;
       }
     }
References i, and s.
invert_jacobian_mapping()
template<unsigned NNODE_1D> double oomph::QSpectralElement< 1, NNODE_1D >::invert_jacobian_mapping (const DenseMatrix< double > & jacobian, DenseMatrix< double > & inverse_jacobian) const inline virtual
Overload the template-free interface for the calculation of inverse jacobian matrix. This is a one-dimensional element, so use the 1D version.
Reimplemented from oomph::FiniteElement.
     {
       return FiniteElement::invert_jacobian<1>(jacobian, inverse_jacobian);
     }
local_coordinate_of_node()
template<unsigned NNODE_1D> void oomph::QSpectralElement< 1, NNODE_1D >::local_coordinate_of_node (const unsigned & n, Vector< double > & s) const inline virtual
Get local coordinates of node j in the element; vector sets its own size.
Reimplemented from oomph::FiniteElement.
     {
       s.resize(1);
       s[0] = OneDimensionalLegendreShape<NNODE_1D>::nodal_position(n);
     }
References n, oomph::OneDimensionalLegendreShape< NNODE_1D >::nodal_position(), and s.
local_fraction_of_node()
template<unsigned NNODE_1D> void oomph::QSpectralElement< 1, NNODE_1D >::local_fraction_of_node (const unsigned & n, Vector< double > & s_fraction) inline virtual
Get the local fractino of node j in the element.
Reimplemented from oomph::FiniteElement.
     {
       this->local_coordinate_of_node(n, s_fraction);
       // Resize
       s_fraction[0] = 0.5 * (s_fraction[0] + 1.0);
     }
References n.
local_one_d_fraction_of_node()
template<unsigned NNODE_1D> double oomph::QSpectralElement< 1, NNODE_1D >::local_one_d_fraction_of_node (const unsigned & n1d, const unsigned & i) inline virtual
The local one-d fraction is the same.
Reimplemented from oomph::FiniteElement.
     {
       return 0.5 *
              (OneDimensionalLegendreShape<NNODE_1D>::nodal_position(n1d) + 1.0);
     }
References oomph::OneDimensionalLegendreShape< NNODE_1D >::nodal_position().
nnode_1d()
template<unsigned NNODE_1D> unsigned oomph::QSpectralElement< 1, NNODE_1D >::nnode_1d () const inline virtual
Number of nodes along each element edge.
Reimplemented from oomph::FiniteElement.
     {
       return NNODE_1D;
     }
nplot_points()
template<unsigned NNODE_1D> unsigned oomph::QSpectralElement< 1, NNODE_1D >::nplot_points (const unsigned & nplot) const inline virtual
Return total number of plot points (when plotting nplot points in each "coordinate direction)
Reimplemented from oomph::FiniteElement.
     {
       unsigned DIM = 1;
       unsigned np = 1;
       for (unsigned i = 0; i < DIM; i++)
       {
         np *= nplot;
       }
       return np;
     }
References DIM, and i.
nvertex_node()
template<unsigned NNODE_1D> unsigned oomph::QSpectralElement< 1, NNODE_1D >::nvertex_node () const inline virtual
Number of vertex nodes in the element.
Implements oomph::LineElementBase.
     {
       return 2;
     }
output() [1/4]
template<unsigned NNODE_1D> void oomph::QSpectralElement< 1, NNODE_1D >::output (FILE * file_pt) inline virtual
C-style output.
Reimplemented from oomph::FiniteElement.
     {
       FiniteElement::output(file_pt);
     }
References oomph::FiniteElement::output().
output() [2/4]
template<unsigned NNODE_1D> void oomph::QSpectralElement< 1, NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) inline virtual
C_style output at n_plot points.
Reimplemented from oomph::FiniteElement.
     {
       FiniteElement::output(file_pt, n_plot);
     }
References oomph::FiniteElement::output().
output() [3/4]
template<unsigned NNODE_1D> void oomph::QSpectralElement< 1, NNODE_1D >::output (std::ostream & outfile) virtual
Output.
The output function for general 1D QSpectralElements.
Reimplemented from oomph::FiniteElement.
   {
     // Tecplot header info
     outfile << "ZONE I=" << NNODE_1D << std::endl;
     // Find the dimension of the nodes
     unsigned n_dim = this->nodal_dimension();
     // Loop over element nodes
     for (unsigned l = 0; l < NNODE_1D; l++)
     {
       // Loop over the dimensions and output the position
       for (unsigned i = 0; i < n_dim; i++)
       {
         outfile << this->node_pt(l)->x(i) << " ";
       }
       // Find out how many data values at the node
       unsigned initial_nvalue = this->node_pt(l)->nvalue();
       // Lopp over the data and output whether pinned or not
       for (unsigned i = 0; i < initial_nvalue; i++)
       {
         outfile << this->node_pt(l)->is_pinned(i) << " ";
       }
       outfile << std::endl;
     }
     outfile << std::endl;
   }
References i.
output() [4/4]
template<unsigned NNODE_1D> void oomph::QSpectralElement< 1, NNODE_1D >::output (std::ostream & outfile, const unsigned & n_plot) virtual
Output at n_plot points.
The output function for nplot points in each coordinate direction.
Reimplemented from oomph::FiniteElement.
   {
     // Local variables
     Vector<double> s(1);
     // Shape functions
     Shape psi(NNODE_1D);
     // Find the dimension of the nodes
     unsigned n_dim = this->nodal_dimension();
     // Tecplot header info
     outfile << "ZONE I=" << nplot << std::endl;
     // Loop over element nodes
     for (unsigned l = 0; l < nplot; l++)
     {
       s[0] = -1.0 + l * 2.0 / (nplot - 1);
       shape(s, psi);
       for (unsigned i = 0; i < n_dim; i++)
       {
         // Output the x and y positions
         outfile << this->interpolated_x(s, i) << " ";
       }
       for (unsigned i = 0; i < NNODE_1D; i++)
       {
         outfile << psi(i) << " ";
       }
       outfile << std::endl;
     }
     outfile << std::endl;
   }
References i, s, and oomph::OneDimLagrange::shape().
s_max()
template<unsigned NNODE_1D> double oomph::QSpectralElement< 1, NNODE_1D >::s_max () const inline virtual
Max. value of local coordinate.
Reimplemented from oomph::FiniteElement.
     {
       return 1.0;
     }
s_min()
template<unsigned NNODE_1D> double oomph::QSpectralElement< 1, NNODE_1D >::s_min () const inline virtual
Min. value of local coordinate.
Reimplemented from oomph::FiniteElement.
     {
       return -1.0;
     }
shape()
template<unsigned NNODE_1D> void oomph::QSpectralElement< 1, NNODE_1D >::shape (const Vector< double > & s, Shape & psi) const inline virtual
Calculate the geometric shape functions at local coordinate s.
Shape function for specific QSpectralElement<1,..>
Implements oomph::FiniteElement.
   {
     // Call the OneDimensional Shape functions
     OneDimensionalLegendreShape<NNODE_1D> psi1(s[0]);
     // OneDLegendreShapeParam psi1(NNODE_1D,s[0]);
     // Now let's loop over the nodal points in the element
     // and copy the values back in
     for (unsigned i = 0; i < NNODE_1D; i++)
     {
       psi(i) = psi1[i];
     }
   }
References i, and s.
Referenced by oomph::SpectralPeriodicOrbitElement< NNODE_1D >::get_interpolated_values().
tecplot_zone_string()
template<unsigned NNODE_1D> std::string oomph::QSpectralElement< 1, NNODE_1D >::tecplot_zone_string (const unsigned & nplot) const inline virtual
Return string for tecplot zone header (when plotting nplot points in each "coordinate direction)
Reimplemented from oomph::FiniteElement.
     {
       std::ostringstream header;
       header << "ZONE I=" << nplot << "\n";
       return header.str();
     }
vertex_node_pt()
template<unsigned NNODE_1D> Node* oomph::QSpectralElement< 1, NNODE_1D >::vertex_node_pt (const unsigned & j) const inline virtual
Pointer to the j-th vertex node in the element.
Implements oomph::LineElementBase.
     {
       unsigned n_node_1d = nnode_1d();
       Node* nod_pt;
       switch (j)
       {
         case 0:
           nod_pt = this->node_pt(0);
           break;
         case 1:
           nod_pt = this->node_pt(n_node_1d - 1);
           break;
         default:
           std::ostringstream error_message;
           error_message << "Vertex node number is " << j
                         << " but must be from 0 to 1\n";
           throw OomphLibError(error_message.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
       }
       return nod_pt;
     }
References j, OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Member Data Documentation
integral
template<unsigned NNODE_1D> GaussLobattoLegendre< 1, NNODE_1D > oomph::QSpectralElement< 1, NNODE_1D >::integral static private
Assign the static integral.
Default integration rule: Gaussian integration of same 'order' as the element
/////////////////////////////////////////////////////////////////////// 1D QLegendreElements ///////////////////////////////////////////////////////////////////////
The documentation for this class was generated from the following files:
Qspectral_elements.h
Qspectral_elements.cc