MercuryDPM: Global Namespace Reference
Global Namespace Reference
Functions
void constant_wind (const oomph::Vector< double > &x, oomph::Vector< double > &wind)
void initial_condition (const double &time, const Vector< double > &x, Vector< double > &u)
Function that determines the initial conditions.
void two_d_wind (const oomph::Vector< double > &x, oomph::Vector< double > &wind)
void exact_solution (const double &t, const Vector< double > &x, Vector< double > &u)
Function that determines the initial conditions.
void initial_left (Vector< double > &u, const bool &sod)
void initial_right (Vector< double > &u, const bool &sod)
Variables
const double pi = MathematicalConstants::Pi
double Gamma = 1.4
Vector< double > x0 (2, 0.0)
double Beta = 5.0
Function Documentation
constant_wind()
void Global::constant_wind (const oomph::Vector< double > & x, oomph::Vector< double > & wind)
  {
   wind.resize(1);
   wind[0] = 1.0;
  }
Referenced by ContProblem< ELEMENT >::ContProblem(), DGProblem< ELEMENT >::DGProblem(), and AdvectionProblem::set_initial_conditions().
exact_solution()
void Global::exact_solution (const double & t, const Vector< double > & x, Vector< double > & u)
Function that determines the initial conditions.
  {
   double r = sqrt(x[0]*x[0] + x[1]*x[1]);
   double theta = atan2(x[1],x[0]);
   double u_theta = (1.0/75.0)*(-r + 16.0/r);
   //Set the density
   u[0] = 1.0;
   //Set the momenta
   u[2] = -sin(theta)*u_theta;
   u[3] = cos(theta)*u_theta;
   double p = 1.0 + (1.0/(75.0*75.0))*(0.5*r*r - 32*log(r) - 128/(r*r));
   u[1] = p/(Gamma-1.0) + 0.5*u[0]*u_theta*u_theta;
  }
References atan2(), cos(), Gamma, Eigen::bfloat16_impl::log(), p, UniformPSDSelfTest::r, sin(), sqrt(), BiharmonicTestFunctions2::theta, Global_Parameters::u_theta(), and plotDoE::x.
Referenced by TwoDDGProblem< ELEMENT >::apply_boundary_conditions(), TwoDDGProblem< ELEMENT >::apply_initial_conditions(), TwoDDGProblem< ELEMENT >::compute_error(), and TwoDDGProblem< ELEMENT >::TwoDDGProblem().
initial_condition()
void Global::initial_condition (const double & time, const Vector< double > & x, Vector< double > & u)
Function that determines the initial conditions.
  {
   u[0] = sin(8.0*atan(1.0)*x[0]);
  }
References Eigen::bfloat16_impl::atan(), sin(), and plotDoE::x.
Referenced by TwoDDGProblem< ELEMENT >::apply_initial_conditions(), AdvectionProblem::compute_error(), TwoDDGProblem< ELEMENT >::compute_error(), and AdvectionProblem::set_initial_conditions().
initial_left()
void Global::initial_left (Vector< double > & u, const bool & sod)
  {
   //Sod
   double ro, vel, pres;
   if(sod)
    {
     ro = 1.0;
     vel = 0.0;
     pres = 1.0;
    }
   else
    {
     //Lax
     ro = 0.445;
     vel = 0.698;
     pres = 3.528;
    }
   double m = vel*ro;
   double E = pres/(Gamma-1.0) + 0.5*ro*vel*vel;
   u[0] = ro;
   u[1] = E;
   u[2] = m;
  }
References Global_Physical_Variables::E, GlobalPhysicalVariables::Gamma, and m.
Referenced by EulerProblem::set_initial_conditions().
initial_right()
void Global::initial_right (Vector< double > & u, const bool & sod)
  {
   double ro, vel, pres;
   //Sod
   if(sod)
    {
     ro = 0.125;
     vel = 0.0;
     pres = 0.1;
    }
   else
    {
     //Lax
     ro = 0.5;
     vel = 0.0;
     pres = 0.571;
    }
   double m = vel*ro;
   double E = pres/(Gamma-1.0) + 0.5*ro*vel*vel;
   u[0] = ro;
   u[1] = E;
   u[2] = m;
  }
References Global_Physical_Variables::E, GlobalPhysicalVariables::Gamma, and m.
Referenced by EulerProblem::set_initial_conditions().
two_d_wind()
void Global::two_d_wind (const oomph::Vector< double > & x, oomph::Vector< double > & wind)
  {
   wind.resize(2);
   wind[0] = 1.0; wind[1] = 1.0;
  }
Referenced by TwoDDGProblem< ELEMENT >::TwoDDGProblem().
Variable Documentation
Beta
double Global::Beta = 5.0
Referenced by oomph::deriv_functions::DampedOscillation::DampedOscillation(), oomph::deriv_functions::DampedOscillation::derivative(), oomph::SolubleSurfactantTransportInterfaceElement::dsigma_dC(), oomph::deriv_functions::DampedOscillation::operator()(), oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::sigma(), oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >::sigma(), oomph::SolubleSurfactantTransportInterfaceElement::sigma(), and oomph::SurfactantTransportInterfaceElement::sigma().
Gamma
double Global::Gamma = 1.4
Referenced by TwoDDGProblem< ELEMENT >::apply_initial_conditions(), exact_solution(), and TwoDDGProblem< ELEMENT >::TwoDDGProblem().
pi
const double Global::pi = MathematicalConstants::Pi
x0
Vector< double > Global::x0 (2 , 0. 0)
Referenced by TiltedCavityProblem< ELEMENT >::actions_before_newton_solve(), DPM::actionsBeforeTimeStep(), Eigen::internal::bicgstabl(), bug_1281(), oomph::ElementElementMortaringElement::evaluate_constraint_functions(), Eigen::internal::generic_ndtri_lt_exp_neg_two(), SineWall::getDistanceAndNormal(), VChute::getDistanceAndNormal(), Eigen::internal::idrstabl(), oomph::MinModLimiter::limit(), main(), oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::node_update_I(), oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::node_update_II(), oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::node_update_III(), oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::node_update_IV(), oomph::UnsteadyHeatFluxPseudoMeltElement< ELEMENT >::plot_residual_landscape(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::scale_basis(), oomph::TRaviartThomasDarcyElement< ORDER >::scale_basis(), oomph::TPoroelasticityElement< ORDER >::scale_basis(), Eigen::IterativeSolverBase< Derived >::solveWithGuess(), UndeformedLeaflet::UndeformedLeaflet(), and UndeformedWall::UndeformedWall().