MercuryDPM: RefineableModalPoissonEquations< DIM > Class Template Reference
RefineableModalPoissonEquations< DIM > Class Template Reference
Refineable version of Poisson equations.
Public Member Functions
RefineableModalPoissonEquations ()
Constructor, simply call other constructors.
RefineableModalPoissonEquations (const RefineableModalPoissonEquations< DIM > &dummy)
Broken copy constructor.
virtual unsigned u_index_poisson () const
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Get 'flux' for Z2 error recovery: Standard flux.from Poisson equations.
void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
Get error against and norm of exact flux.
void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)
void further_build ()
Further build: Copy source function pointer from father element.
Public Member Functions inherited from ModalPoissonEquations< DIM >
ModalPoissonEquations ()
Constructor (must initialise the Source_fct_pt to null)
virtual double u (const unsigned &n) const =0
virtual unsigned nbasis () const =0
Number of basis functions.
virtual void basis (const Vector< double > &s, Shape &basis) const =0
void output (ostream &outfile)
Output with default number of plot points.
void output (ostream &outfile, const unsigned &nplot)
void output_fct (ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: x,y,u_exact or x,y,z,u_exact at nplot^DIM plot points.
virtual void output_fct (ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
void compute_error (ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Get error against and norm of exact solution.
void compute_error (ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Dummy, time dependent error checker.
PoissonSourceFctPt & source_fct_pt ()
Access function: Pointer to source function.
PoissonSourceFctPt source_fct_pt () const
Access function: Pointer to source function. Const version.
virtual void get_source_poisson (const Vector< double > &x, double &source) const
PoissonDiffFctPt & diff_fct_pt ()
Access function: Pointer to diffusivity function.
PoissonDiffFctPt diff_fct_pt () const
Access function: Pointer to source function. Const version.
virtual void get_diff (const Vector< double > &x, double &diff) const
void get_flux (const Vector< double > &s, Vector< double > &flux, unsigned p_order) const
Get flux: flux[i] = du/dx_i.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector (wrapper)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
double interpolated_u (const Vector< double > &s) const
Return FE representation of function value u(s) at local coordinate s.
unsigned self_test ()
Self-test: Return 0 for OK.
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void disable_ALE ()
virtual void enable_ALE ()
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output (FILE *file_pt)
virtual void output (FILE *file_pt, const unsigned &n_plot)
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output an exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output a time-dependent exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::RefineableElement
RefineableElement ()
virtual ~RefineableElement ()
Destructor, delete the allocated storage for the hanging equations.
RefineableElement (const RefineableElement &)=delete
Broken copy constructor.
void operator= (const RefineableElement &)=delete
Broken assignment operator.
Tree * tree_pt ()
Access function: Pointer to quadtree representation of this element.
void set_tree_pt (Tree *my_tree_pt)
Set pointer to quadtree representation of this element.
virtual unsigned required_nsons () const
bool refinement_is_enabled ()
Flag to indicate suppression of any refinement.
void disable_refinement ()
Suppress of any refinement for this element.
void enable_refinement ()
Emnable refinement for this element.
template<class ELEMENT >
void split (Vector< ELEMENT * > &son_pt) const
int local_hang_eqn (Node *const &node_pt, const unsigned &i)
virtual void build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt, bool &was_already_built, std::ofstream &new_nodes_file)=0
void set_refinement_level (const int &refine_level)
Set the refinement level.
unsigned refinement_level () const
Return the Refinement level.
void select_for_refinement ()
Select the element for refinement.
void deselect_for_refinement ()
Deselect the element for refinement.
void select_sons_for_unrefinement ()
Unrefinement will be performed by merging the four sons of this element.
void deselect_sons_for_unrefinement ()
bool to_be_refined ()
Has the element been selected for refinement?
bool sons_to_be_unrefined ()
Has the element been selected for unrefinement?
virtual void rebuild_from_sons (Mesh *&mesh_pt)=0
virtual void unbuild ()
virtual void deactivate_element ()
virtual bool nodes_built ()
Return true if all the nodes have been built, false if not.
long number () const
Element number (for debugging/plotting)
void set_number (const long &mynumber)
Set element number (for debugging/plotting)
virtual unsigned ncont_interpolated_values () const =0
virtual Node * interpolating_node_pt (const unsigned &n, const int &value_id)
virtual double local_one_d_fraction_of_interpolating_node (const unsigned &n1d, const unsigned &i, const int &value_id)
virtual Node * get_interpolating_node_at_local_coordinate (const Vector< double > &s, const int &value_id)
virtual unsigned ninterpolating_node (const int &value_id)
virtual unsigned ninterpolating_node_1d (const int &value_id)
virtual void interpolating_basis (const Vector< double > &s, Shape &psi, const int &value_id) const
virtual void check_integrity (double &max_error)=0
void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual RefineableElement * root_element_pt ()
virtual RefineableElement * father_element_pt () const
Return a pointer to the father element.
void get_father_at_refinement_level (unsigned &refinement_level, RefineableElement *&father_at_reflevel_pt)
virtual void initial_setup (Tree *const &adopted_father_pt=0, const unsigned &initial_p_order=0)
virtual void pre_build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt)
Pre-build the element.
virtual void setup_hanging_nodes (Vector< std::ofstream * > &output_stream)
virtual void further_setup_hanging_nodes ()
void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
unsigned nshape_controlling_nodes ()
std::map< Node *, unsigned > shape_controlling_node_lookup ()
Public Member Functions inherited from oomph::ElementWithZ2ErrorEstimator
ElementWithZ2ErrorEstimator ()
Default empty constructor.
ElementWithZ2ErrorEstimator (const ElementWithZ2ErrorEstimator &)=delete
Broken copy constructor.
void operator= (const ElementWithZ2ErrorEstimator &)=delete
Broken assignment operator.
virtual unsigned ncompound_fluxes ()
virtual void compute_exact_Z2_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_flux_pt, double &error, double &norm)
virtual void get_Z2_compound_flux_indices (Vector< unsigned > &flux_index)
virtual unsigned nvertex_node () const =0
Number of vertex nodes in the element.
virtual Node * vertex_node_pt (const unsigned &j) const =0
virtual unsigned nrecovery_order ()=0
Order of recovery shape functions.
virtual double geometric_jacobian (const Vector< double > &x)
Private Member Functions
void fill_in_generic_residual_contribution (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
void get_source_gradient (unsigned int &, oomph::Vector< double > &, oomph::Vector< double > &)
Additional Inherited Members
Public Types inherited from ModalPoissonEquations< DIM >
typedef void(* PoissonSourceFctPt) (const Vector< double > &x, double &f)
typedef void(* PoissonDiffFctPt) (const Vector< double > &x, double &f)
Function pointer to a diffusion function fxt(x,f(x))
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Static Public Member Functions inherited from oomph::RefineableElement
static double & max_integrity_tolerance ()
Max. allowed discrepancy in element integrity check.
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Protected Member Functions inherited from ModalPoissonEquations< DIM >
virtual double dshape_dbasis_and_dtest_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &basis, DShape &dbasisdx, Shape &test, DShape &dtestdx) const =0
virtual double dshape_dbasis_and_dtest_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &basis, DShape &dbasisdx, Shape &test, DShape &dtestdx) const =0
virtual void add_generic_residual_contribution (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
Protected Member Functions inherited from oomph::FiniteElement
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Member Functions inherited from oomph::RefineableElement
void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
void assign_hanging_local_eqn_numbers (const bool &store_local_dof_pt)
Assign the local equation numbers for hanging node variables.
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Static Protected Member Functions inherited from oomph::RefineableElement
static void check_value_id (const int &n_continuously_interpolated_values, const int &value_id)
Protected Attributes inherited from ModalPoissonEquations< DIM >
PoissonSourceFctPt Source_fct_pt
Pointer to source function:
PoissonDiffFctPt Diff_fct_pt
Pointer to the diffusivity function.
Vector< int > Local_eqn
Array to hold local eqn numbers: Local_eqn[n] (=-1 for BC)
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Protected Attributes inherited from oomph::RefineableElement
Tree * Tree_pt
A pointer to a general tree object.
unsigned Refine_level
Refinement level.
bool To_be_refined
Flag for refinement.
bool Refinement_is_enabled
Flag to indicate suppression of any refinement.
bool Sons_to_be_unrefined
Flag for unrefinement.
long Number
Global element number – for plotting/validation purposes.
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Static Protected Attributes inherited from oomph::RefineableElement
static double Max_integrity_tolerance = 1.0e-8
Max. allowed discrepancy in element integrity check.
Detailed Description
template<unsigned DIM>
class RefineableModalPoissonEquations< DIM >
Refineable version of Poisson equations.
Constructor & Destructor Documentation
RefineableModalPoissonEquations() [1/2]
template<unsigned DIM> RefineableModalPoissonEquations< DIM >::RefineableModalPoissonEquations () inline
Constructor, simply call other constructors.
                                    : ModalPoissonEquations<DIM>(),
   RefineableElement(), ElementWithZ2ErrorEstimator()
   { }
RefineableModalPoissonEquations() [2/2]
template<unsigned DIM> RefineableModalPoissonEquations< DIM >::RefineableModalPoissonEquations (const RefineableModalPoissonEquations< DIM > & dummy) inline
Broken copy constructor.
   {
    BrokenCopy::broken_copy("RefineableModalPoissonEquations");
   }
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
fill_in_generic_residual_contribution()
template<unsigned DIM> void RefineableModalPoissonEquations< DIM >::fill_in_generic_residual_contribution (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) private
Add element's contribution to elemental residual vector and/or Jacobian matrix flag=1: compute both flag=0: compute only residual vector
Referenced by ModalPRefineableQPoissonElement< DIM >::fill_in_generic_residual_contribution().
further_build()
template<unsigned DIM> void RefineableModalPoissonEquations< DIM >::further_build () inline virtual
Further build: Copy source function pointer from father element.
Reimplemented from oomph::RefineableElement.
Reimplemented in ModalPRefineableQPoissonElement< DIM >.
   {
    this->Source_fct_pt=dynamic_cast<RefineableModalPoissonEquations<DIM>*>
                                 (this->father_element_pt())->source_fct_pt();
   }
References oomph::source_fct_pt(), and oomph::Source_fct_pt.
Referenced by ModalPRefineableQPoissonElement< DIM >::further_build().
get_dresidual_dnodal_coordinates()
template<unsigned DIM> void RefineableModalPoissonEquations< DIM >::get_dresidual_dnodal_coordinates (RankThreeTensor< double > & dresidual_dnodal_coordinates) private virtual
Compute derivatives of elemental residual vector with respect to nodal coordinates. Overwrites default implementation in FiniteElement base class. dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij}
Compute derivatives of elemental residual vector with respect to nodal coordinates. dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij} Overloads the FD-based version in the FE base class.
Reimplemented from oomph::FiniteElement.
Reimplemented in ModalPRefineableQPoissonElement< DIM >.
 {
  //Find out how many nodes there are
  unsigned n_node = nnode();
  //Find out the total number of basis and test functions there are
  unsigned n_basis = this->nbasis();
  //Set up memory for the shape and test functions
  Shape psi(n_node), basis(n_basis), test(n_basis);
  DShape dpsidx(n_node,DIM), dbasisdx(n_basis,DIM), dtestdx(n_basis,DIM);
  DShape dpsidx_pls(n_node,DIM), dbasisdx_pls(n_basis,DIM), dtestdx_pls(n_basis,DIM);
  // Get number of shape controlling nodes
  unsigned n_shape_controlling_node=nshape_controlling_nodes();
  // Deriatives of shape fct derivatives w.r.t. nodal coords
  RankFourTensor<double> d_dpsidx_dX(DIM,n_shape_controlling_node,n_node,DIM);
  RankFourTensor<double> d_dtestdx_dX(DIM,n_shape_controlling_node,n_node,DIM);
  // Derivative of Jacobian of mapping w.r.t. to nodal coords
  DenseMatrix<double> dJ_dX(DIM,n_shape_controlling_node);
  // Derivatives of derivative of u w.r.t. nodal coords
  RankThreeTensor<double> d_dudx_dX(DIM,n_shape_controlling_node,DIM);
  // Gradient of source fct
  Vector<double> d_source_dx(DIM);
  //Index at which the poisson unknown is stored
  const unsigned u_nodal_index = this->u_index_poisson();
  //Set the value of n_intpt
  const unsigned n_intpt = integral_pt()->nweight();
  //Integers to store the local equation number
  int local_eqn=0;
  // Local storage for pointers to hang_info object
  HangInfo *hang_info_pt=0;
  //Loop over the integration points
  for(unsigned ipt=0;ipt<n_intpt;ipt++)
   {
    //Get the integral weight
    double w = integral_pt()->weight(ipt);
    //Call the derivatives of the shape and test functions
    double J = this->dshape_dbasis_and_dtest_eulerian_at_knot(ipt,
                                                              psi,
                                                              dpsidx,
                                                              basis,
                                                              dbasisdx,
                                                              test,
                                                              dtestdx);
    //Calculate local values
    //Allocate and initialise to zero
    Vector<double> interpolated_x(DIM,0.0);
    Vector<double> interpolated_dudx(DIM,0.0);
    //Calculate function value and derivatives:
    //-----------------------------------------
    // Loop over nodes
    for(unsigned l=0;l<n_node;l++)
     {
      //Get the nodal value of the Poisson unknown
      double u_value = nodal_value(l,u_nodal_index);
      // Loop over directions
      for(unsigned j=0;j<DIM;j++)
       {
        interpolated_x[j] += nodal_position(l,j)*psi(l);
        interpolated_dudx[j] += u_value*dpsidx(l,j);
       }
     }
    //Get source function
    //-------------------
    double source;
    //this->get_source(ipt,interpolated_x,source);
    this->get_source_poisson(interpolated_x,source);
    // FD step
    double eps_fd=GeneralisedElement::Default_fd_jacobian_step;
    std::map<Node*,unsigned> local_shape_controlling_node_lookup=
     shape_controlling_node_lookup();
    // FD loop over shape-controlling nodes
    for (std::map<Node*,unsigned>::iterator it=
         local_shape_controlling_node_lookup.begin();
         it!=local_shape_controlling_node_lookup.end();
         it++)
     {
      // Get node
      Node* nod_pt=it->first;
      // Get its number
      unsigned jj=it->second;
      // Loop over coordinate directions
      for (unsigned ii=0;ii<DIM;ii++)
       {
        // Make backup
        double backup=nod_pt->x(ii);
        // Do FD step. No node update required as we're
        // attacking the coordinate directly...
        nod_pt->x(ii)+=eps_fd;
        //Call the derivatives of the shape and test functions
        //at advanced level
        double J_pls =
         this->dshape_dbasis_and_dtest_eulerian_at_knot(ipt,
                                                        psi,
                                                        dpsidx_pls,
                                                        basis,
                                                        dbasisdx_pls,
                                                        test,
                                                        dtestdx_pls);
        // Assign
        dJ_dX(ii,jj)=(J_pls-J)/eps_fd;
        for (unsigned i=0;i<DIM;i++)
         {
          for (unsigned j=0;j<n_node;j++)
           {
            d_dpsidx_dX(ii,jj,j,i)=(dpsidx_pls(j,i)-dpsidx(j,i))/eps_fd;
            d_dtestdx_dX(ii,jj,j,i)=(dtestdx_pls(j,i)-dtestdx(j,i))/eps_fd;
           }
         }
        // Shape deriv of du/dx_i
        for (unsigned i=0;i<DIM;i++)
         {
          double aux=0.0;
          for (unsigned j_nod=0;j_nod<n_node;j_nod++)
           {
            aux+=nodal_value(j_nod,u_nodal_index)*
             d_dpsidx_dX(ii,jj,j_nod,i);
           }
          d_dudx_dX(ii,jj,i)=aux;
         }
        // Reset coordinate. No node update required as we're
        // attacking the coordinate directly...
        nod_pt->x(ii)=backup;
       }
     }
    // Get gradient of source function
    this->get_source_gradient(ipt, interpolated_x, d_source_dx);
    // Assemble shape derivatives
    //---------------------------
    // Loop over the nodes for the test functions
    for(unsigned l=0;l<n_node;l++)
     {
      //Local variables used to store the number of master nodes and the
      //weight associated with the shape function if the node is hanging
      unsigned n_master=1;
      double hang_weight=1.0;
      //Local bool (is the node hanging)
      bool is_node_hanging = this->node_pt(l)->is_hanging();
      //If the node is hanging, get the number of master nodes
      if(is_node_hanging)
       {
        hang_info_pt = this->node_pt(l)->hanging_pt();
        n_master = hang_info_pt->nmaster();
       }
      //Otherwise there is just one master node, the node itself
      else
       {
        n_master = 1;
       }
      //Loop over the master nodes
      for(unsigned m=0;m<n_master;m++)
       {
        //Get the local equation number and hang_weight
        //If the node is hanging
        if(is_node_hanging)
         {
          //Read out the local equation number from the m-th master node
          local_eqn =  this->local_hang_eqn(hang_info_pt->master_node_pt(m),
                                            u_nodal_index);
          //Read out the weight from the master node
          hang_weight = hang_info_pt->master_weight(m);
         }
        //If the node is not hanging
        else
         {
          //The local equation number comes from the node itself
          local_eqn = this->nodal_local_eqn(l,u_nodal_index);
          //The hang weight is one
          hang_weight = 1.0;
         }
        //If the nodal equation is not a boundary condition
        if(local_eqn >= 0)
         {
          // Loop over coordinate directions
          for (unsigned ii=0;ii<DIM;ii++)
           {
            // Loop over shape controlling nodes
            for (unsigned jj=0;jj<n_shape_controlling_node;jj++)
             {
              double sum=source*psi(l)*dJ_dX(ii,jj)+
               d_source_dx[ii]*psi(l)*psi(jj)*J;
              for (unsigned k=0;k<DIM;k++)
               {
                sum+=interpolated_dudx[k]*(dtestdx(l,k)*dJ_dX(ii,jj)+
                                           d_dtestdx_dX(ii,jj,l,k)*J)
                 + d_dudx_dX(ii,jj,k)*dtestdx(l,k)*J;
               }
              // Multiply through by integration weight
              dresidual_dnodal_coordinates(local_eqn,ii,jj)+=sum*w*hang_weight;
             }
           }
         }
       }
     }
   } // End of loop over integration points
 }
References DIM, i, J, j, k, m, oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), TestProblem::source(), Eigen::test, w, and oomph::Node::x().
get_interpolated_values() [1/2]
template<unsigned DIM> void RefineableModalPoissonEquations< DIM >::get_interpolated_values (const unsigned & t, const Vector< double > & s, Vector< double > & values) inline virtual
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Implements oomph::RefineableElement.
   {
    if (t!=0)
     {
      std::string error_message =
       "Time-dependent version of get_interpolated_values() ";
      error_message += "not implemented for this element \n";
      throw
       OomphLibError(error_message,
                     "RefineablePoissonEquations::get_interpolated_values()",
                     OOMPH_EXCEPTION_LOCATION);
     }
    else
     {
      //Make sure that we call this particular object's steady
      //get_interpolated_values (it could get overloaded lower down)
      this->get_interpolated_values(s,values);
     }
   }
References OOMPH_EXCEPTION_LOCATION, s, oomph::Global_string_for_annotation::string(), and plotPSD::t.
get_interpolated_values() [2/2]
template<unsigned DIM> void RefineableModalPoissonEquations< DIM >::get_interpolated_values (const Vector< double > & s, Vector< double > & values) inline virtual
Get error against and norm of exact flux.
Get the function value u in Vector. Note: Given the generality of the interface (this function is usually called from black-box documentation or interpolation routines), the values Vector sets its own size in here.
Reimplemented from oomph::RefineableElement.
  {
   // Set size of Vector: u
   values.resize(1);
   //Find number of nodes
   unsigned n_node = nnode();
   //Local shape function
   Shape psi(n_node);
   //Find values of shape function
   shape(s,psi);
   //Initialise value of u
   values[0] = 0.0;
   //Find the index at which the poisson unknown is stored
   unsigned u_nodal_index = this->u_index_poisson();
   //Loop over the local nodes and sum up the values
   for(unsigned l=0;l<n_node;l++)
    {
     values[0] += this->nodal_value(l,u_nodal_index)*psi[l];
    }
  }
References s, and oomph::OneDimLagrange::shape().
get_source_gradient()
template<unsigned DIM> void RefineableModalPoissonEquations< DIM >::get_source_gradient (unsigned int & , oomph::Vector< double > & , oomph::Vector< double > &) inline private
   {
    std::string error_message = "get_source_gradient() is ";
    error_message += "not implemented for this element \n";
    throw
     OomphLibError(error_message,
                   "RefineablePoissonEquations::get_source_gradient()",
                   OOMPH_EXCEPTION_LOCATION);
   }
References OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
get_Z2_flux()
template<unsigned DIM> void RefineableModalPoissonEquations< DIM >::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) inline virtual
Get 'flux' for Z2 error recovery: Standard flux.from Poisson equations.
Implements oomph::ElementWithZ2ErrorEstimator.
   {this->get_flux(s,flux,2);}
References ProblemParameters::flux(), and oomph::get_flux().
num_Z2_flux_terms()
template<unsigned DIM> unsigned RefineableModalPoissonEquations< DIM >::num_Z2_flux_terms () inline virtual
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
 {return DIM;}
References DIM.
u_index_poisson()
template<unsigned DIM> virtual unsigned RefineableModalPoissonEquations< DIM >::u_index_poisson () const inline virtual
 {return 0;}
The documentation for this class was generated from the following file:
one_d_poisson_hp_adapt.cc