MercuryDPM: Eigen::TensorEvaluator< const TensorForcedEvalOp< ArgType_ >, Device > Struct Template Reference
Eigen::TensorEvaluator< const TensorForcedEvalOp< ArgType_ >, Device > Struct Template Reference
#include <TensorForcedEval.h>
Public Types
enum {
IsAligned = true , PacketAccess = (PacketType<CoeffReturnType, Device>::size > 1) , BlockAccess = internal::is_arithmetic<CoeffReturnType>::value , PreferBlockAccess = false ,
RawAccess = true
}
typedef const internal::remove_all_t< ArgType_ > ArgType
typedef TensorForcedEvalOp< ArgType > XprType
typedef ArgType::Scalar Scalar
typedef TensorEvaluator< ArgType, Device >::Dimensions Dimensions
typedef XprType::Index Index
typedef XprType::CoeffReturnType CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef Eigen::internal::traits< XprType >::PointerType TensorPointerType
typedef StorageMemory< CoeffReturnType, Device > Storage
typedef Storage::Type EvaluatorPointerType
typedef internal::TensorBlockDescriptor< NumDims, Index > TensorBlockDesc
typedef internal::TensorBlockScratchAllocator< Device > TensorBlockScratch
typedef internal::TensorMaterializedBlock< CoeffReturnType, NumDims, Layout, Index > TensorBlock
Public Member Functions
TensorEvaluator (const XprType &op, const Device &device)
~TensorEvaluator ()
EIGEN_DEVICE_FUNC const Dimensions & dimensions () const
EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (EvaluatorPointerType)
EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType packet (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::TensorBlockResourceRequirements getResourceRequirements () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorBlock block (TensorBlockDesc &desc, TensorBlockScratch &scratch, bool=false) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE EvaluatorPointerType data () const
Static Public Attributes
static constexpr int PacketSize = PacketType<CoeffReturnType, Device>::size
static constexpr int Layout = TensorEvaluator<ArgType, Device>::Layout
static constexpr int NumDims = internal::traits<ArgType>::NumDimensions
Private Attributes
TensorEvaluator< ArgType, Device > m_impl
const ArgType m_op
const Device EIGEN_DEVICE_REF m_device
std::shared_ptr< DeviceTempPointerHolder< Device > > m_buffer_holder
EvaluatorPointerType m_buffer
Member Typedef Documentation
ArgType
template<typename ArgType_ , typename Device > typedef const internal::remove_all_t<ArgType_> Eigen::TensorEvaluator< const TensorForcedEvalOp< ArgType_ >, Device >::ArgType
CoeffReturnType
template<typename ArgType_ , typename Device > typedef XprType::CoeffReturnType Eigen::TensorEvaluator< const TensorForcedEvalOp< ArgType_ >, Device >::CoeffReturnType
Dimensions
template<typename ArgType_ , typename Device > typedef TensorEvaluator<ArgType, Device>::Dimensions Eigen::TensorEvaluator< const TensorForcedEvalOp< ArgType_ >, Device >::Dimensions
EvaluatorPointerType
template<typename ArgType_ , typename Device > typedef Storage::Type Eigen::TensorEvaluator< const TensorForcedEvalOp< ArgType_ >, Device >::EvaluatorPointerType
Index
template<typename ArgType_ , typename Device > typedef XprType::Index Eigen::TensorEvaluator< const TensorForcedEvalOp< ArgType_ >, Device >::Index
PacketReturnType
template<typename ArgType_ , typename Device > typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorEvaluator< const TensorForcedEvalOp< ArgType_ >, Device >::PacketReturnType
Scalar
template<typename ArgType_ , typename Device > typedef ArgType::Scalar Eigen::TensorEvaluator< const TensorForcedEvalOp< ArgType_ >, Device >::Scalar
Storage
template<typename ArgType_ , typename Device > typedef StorageMemory<CoeffReturnType, Device> Eigen::TensorEvaluator< const TensorForcedEvalOp< ArgType_ >, Device >::Storage
TensorBlock
template<typename ArgType_ , typename Device > typedef internal::TensorMaterializedBlock<CoeffReturnType, NumDims, Layout, Index> Eigen::TensorEvaluator< const TensorForcedEvalOp< ArgType_ >, Device >::TensorBlock
TensorBlockDesc
template<typename ArgType_ , typename Device > typedef internal::TensorBlockDescriptor<NumDims, Index> Eigen::TensorEvaluator< const TensorForcedEvalOp< ArgType_ >, Device >::TensorBlockDesc
TensorBlockScratch
template<typename ArgType_ , typename Device > typedef internal::TensorBlockScratchAllocator<Device> Eigen::TensorEvaluator< const TensorForcedEvalOp< ArgType_ >, Device >::TensorBlockScratch
TensorPointerType
template<typename ArgType_ , typename Device > typedef Eigen::internal::traits<XprType>::PointerType Eigen::TensorEvaluator< const TensorForcedEvalOp< ArgType_ >, Device >::TensorPointerType
XprType
template<typename ArgType_ , typename Device > typedef TensorForcedEvalOp<ArgType> Eigen::TensorEvaluator< const TensorForcedEvalOp< ArgType_ >, Device >::XprType
Member Enumeration Documentation
anonymous enum
template<typename ArgType_ , typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
BlockAccess
PreferBlockAccess
RawAccess
        {
     IsAligned = true,
     PacketAccess = (PacketType<CoeffReturnType, Device>::size > 1),
     BlockAccess = internal::is_arithmetic<CoeffReturnType>::value,
     PreferBlockAccess = false,
     RawAccess = true
   };
Constructor & Destructor Documentation
TensorEvaluator()
template<typename ArgType_ , typename Device > Eigen::TensorEvaluator< const TensorForcedEvalOp< ArgType_ >, Device >::TensorEvaluator (const XprType & op, const Device & device) inline
       : m_impl(op.expression(), device),
         m_op(op.expression()),
         m_device(device),
         m_buffer_holder(nullptr),
         m_buffer(nullptr) {}
~TensorEvaluator()
template<typename ArgType_ , typename Device > Eigen::TensorEvaluator< const TensorForcedEvalOp< ArgType_ >, Device >::~TensorEvaluator () inline
 { cleanup(); }
References Eigen::TensorEvaluator< Derived, Device >::cleanup().
Member Function Documentation
block()
template<typename ArgType_ , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorBlock Eigen::TensorEvaluator< const TensorForcedEvalOp< ArgType_ >, Device >::block (TensorBlockDesc & desc, TensorBlockScratch & scratch, bool = false) const inline
{
     eigen_assert(m_buffer != nullptr);
     return TensorBlock::materialize(m_buffer, m_impl.dimensions(), desc, scratch);
   }
References eigen_assert, and Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::materialize().
cleanup()
template<typename ArgType_ , typename Device > EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorForcedEvalOp< ArgType_ >, Device >::cleanup () inline
{
     m_buffer_holder = nullptr;
     m_buffer = nullptr;
   }
Referenced by framework.Frame::__init__().
coeff()
template<typename ArgType_ , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::TensorEvaluator< const TensorForcedEvalOp< ArgType_ >, Device >::coeff (Index index) const inline
 { return m_buffer[index]; }
costPerCoeff()
template<typename ArgType_ , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorEvaluator< const TensorForcedEvalOp< ArgType_ >, Device >::costPerCoeff (bool vectorized) const inline
{
     return TensorOpCost(sizeof(CoeffReturnType), 0, 0, vectorized, PacketSize);
   }
References Eigen::TensorEvaluator< Derived, Device >::PacketSize.
data()
template<typename ArgType_ , typename Device > EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE EvaluatorPointerType Eigen::TensorEvaluator< const TensorForcedEvalOp< ArgType_ >, Device >::data () const inline
 { return m_buffer; }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
dimensions()
template<typename ArgType_ , typename Device > EIGEN_DEVICE_FUNC const Dimensions& Eigen::TensorEvaluator< const TensorForcedEvalOp< ArgType_ >, Device >::dimensions () const inline
 { return m_impl.dimensions(); }
evalSubExprsIfNeeded()
template<typename ArgType_ , typename Device > EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorForcedEvalOp< ArgType_ >, Device >::evalSubExprsIfNeeded (EvaluatorPointerType) inline
{
     const Index numValues = internal::array_prod(m_impl.dimensions());
     m_buffer_holder = std::make_shared<DeviceTempPointerHolder<Device>>(m_device, numValues * sizeof(CoeffReturnType));
     m_buffer = static_cast<EvaluatorPointerType>(m_buffer_holder->ptr());
     internal::non_integral_type_placement_new<Device, CoeffReturnType>()(numValues, m_buffer);
     typedef TensorEvalToOp<const std::remove_const_t<ArgType>> EvalTo;
     EvalTo evalToTmp(m_device.get(m_buffer), m_op);
     internal::TensorExecutor<const EvalTo, std::remove_const_t<Device>,
                              /*Vectorizable=*/internal::IsVectorizable<Device, const ArgType>::value,
                              /*Tiling=*/internal::IsTileable<Device, const ArgType>::value>::run(evalToTmp, m_device);
     return true;
   }
References Eigen::internal::array_prod(), Eigen::TensorEvaluator< Derived, Device >::m_device, and Eigen::run().
getResourceRequirements()
template<typename ArgType_ , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::TensorBlockResourceRequirements Eigen::TensorEvaluator< const TensorForcedEvalOp< ArgType_ >, Device >::getResourceRequirements () const inline
{
     return internal::TensorBlockResourceRequirements::any();
   }
References Eigen::internal::TensorBlockResourceRequirements::any().
packet()
template<typename ArgType_ , typename Device > template<int LoadMode> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType Eigen::TensorEvaluator< const TensorForcedEvalOp< ArgType_ >, Device >::packet (Index index) const inline
{
     return internal::ploadt<PacketReturnType, LoadMode>(m_buffer + index);
   }
Member Data Documentation
Layout
template<typename ArgType_ , typename Device > constexpr int Eigen::TensorEvaluator< const TensorForcedEvalOp< ArgType_ >, Device >::Layout = TensorEvaluator<ArgType, Device>::Layout static constexpr
m_buffer
template<typename ArgType_ , typename Device > EvaluatorPointerType Eigen::TensorEvaluator< const TensorForcedEvalOp< ArgType_ >, Device >::m_buffer private
m_buffer_holder
template<typename ArgType_ , typename Device > std::shared_ptr<DeviceTempPointerHolder<Device> > Eigen::TensorEvaluator< const TensorForcedEvalOp< ArgType_ >, Device >::m_buffer_holder private
m_device
template<typename ArgType_ , typename Device > const Device EIGEN_DEVICE_REF Eigen::TensorEvaluator< const TensorForcedEvalOp< ArgType_ >, Device >::m_device private
m_impl
template<typename ArgType_ , typename Device > TensorEvaluator<ArgType, Device> Eigen::TensorEvaluator< const TensorForcedEvalOp< ArgType_ >, Device >::m_impl private
m_op
template<typename ArgType_ , typename Device > const ArgType Eigen::TensorEvaluator< const TensorForcedEvalOp< ArgType_ >, Device >::m_op private
NumDims
template<typename ArgType_ , typename Device > constexpr int Eigen::TensorEvaluator< const TensorForcedEvalOp< ArgType_ >, Device >::NumDims = internal::traits<ArgType>::NumDimensions static constexpr
PacketSize
template<typename ArgType_ , typename Device > constexpr int Eigen::TensorEvaluator< const TensorForcedEvalOp< ArgType_ >, Device >::PacketSize = PacketType<CoeffReturnType, Device>::size static constexpr
The documentation for this struct was generated from the following file:
TensorForcedEval.h