MercuryDPM: Eigen::internal::Assignment< DstXprType, Inverse< FullPivHouseholderQR< MatrixType, PermutationIndex > >, internal::assign_op< typename DstXprType::Scalar, typename FullPivHouseholderQR< MatrixType, PermutationIndex >::Scalar >, Dense2Dense > Struct Template Reference
Eigen::internal::Assignment< DstXprType, Inverse< FullPivHouseholderQR< MatrixType, PermutationIndex > >, internal::assign_op< typename DstXprType::Scalar, typename FullPivHouseholderQR< MatrixType, PermutationIndex >::Scalar >, Dense2Dense > Struct Template Reference
#include <FullPivHouseholderQR.h>
Public Types
typedef FullPivHouseholderQR< MatrixType, PermutationIndex > QrType
typedef Inverse< QrType > SrcXprType
Static Public Member Functions
static void run (DstXprType &dst, const SrcXprType &src, const internal::assign_op< typename DstXprType::Scalar, typename QrType::Scalar > &)
Member Typedef Documentation
QrType
template<typename DstXprType , typename MatrixType , typename PermutationIndex > typedef FullPivHouseholderQR<MatrixType, PermutationIndex> Eigen::internal::Assignment< DstXprType, Inverse< FullPivHouseholderQR< MatrixType, PermutationIndex > >, internal::assign_op< typename DstXprType::Scalar, typename FullPivHouseholderQR< MatrixType, PermutationIndex >::Scalar >, Dense2Dense >::QrType
SrcXprType
template<typename DstXprType , typename MatrixType , typename PermutationIndex > typedef Inverse<QrType> Eigen::internal::Assignment< DstXprType, Inverse< FullPivHouseholderQR< MatrixType, PermutationIndex > >, internal::assign_op< typename DstXprType::Scalar, typename FullPivHouseholderQR< MatrixType, PermutationIndex >::Scalar >, Dense2Dense >::SrcXprType
Member Function Documentation
run()
template<typename DstXprType , typename MatrixType , typename PermutationIndex > static void Eigen::internal::Assignment< DstXprType, Inverse< FullPivHouseholderQR< MatrixType, PermutationIndex > >, internal::assign_op< typename DstXprType::Scalar, typename FullPivHouseholderQR< MatrixType, PermutationIndex >::Scalar >, Dense2Dense >::run (DstXprType & dst, const SrcXprType & src, const internal::assign_op< typename DstXprType::Scalar, typename QrType::Scalar > &) inline static
{
     dst = src.nestedExpression().solve(MatrixType::Identity(src.rows(), src.cols()));
   }
References Eigen::Inverse< XprType >::cols(), Eigen::Inverse< XprType >::nestedExpression(), and Eigen::Inverse< XprType >::rows().
The documentation for this struct was generated from the following file:
FullPivHouseholderQR.h