MercuryDPM: cholmod_support.cpp File Reference
cholmod_support.cpp File Reference
#include "sparse_solver.h"
#include <Eigen/CholmodSupport>
Macros
#define EIGEN_NO_DEBUG_SMALL_PRODUCT_BLOCKS
Functions
template<typename SparseType >
void test_cholmod_ST ()
template<typename T , int flags, typename IdxType >
void test_cholmod_T ()
EIGEN_DECLARE_TEST (cholmod_support)
Macro Definition Documentation
EIGEN_NO_DEBUG_SMALL_PRODUCT_BLOCKS
#define EIGEN_NO_DEBUG_SMALL_PRODUCT_BLOCKS
Function Documentation
EIGEN_DECLARE_TEST()
EIGEN_DECLARE_TEST (cholmod_support)
{
   CALL_SUBTEST_11((test_cholmod_T<double, ColMajor, int>()));
   CALL_SUBTEST_12((test_cholmod_T<double, ColMajor, long>()));
   CALL_SUBTEST_13((test_cholmod_T<double, RowMajor, int>()));
   CALL_SUBTEST_14((test_cholmod_T<double, RowMajor, long>()));
   CALL_SUBTEST_21((test_cholmod_T<std::complex<double>, ColMajor, int>()));
   CALL_SUBTEST_22((test_cholmod_T<std::complex<double>, ColMajor, long>()));
   // TODO complex row-major matrices do not work at the moment:
   // CALL_SUBTEST_23( (test_cholmod_T<std::complex<double>, RowMajor, int >()) );
   // CALL_SUBTEST_24( (test_cholmod_T<std::complex<double>, RowMajor, long>()) );
 }
References CALL_SUBTEST_11, CALL_SUBTEST_12, CALL_SUBTEST_13, CALL_SUBTEST_14, CALL_SUBTEST_21, CALL_SUBTEST_22, Eigen::ColMajor, and test_cholmod_T().
test_cholmod_ST()
template<typename SparseType > void test_cholmod_ST ()
{
   CholmodDecomposition<SparseType, Lower> g_chol_colmajor_lower;
   g_chol_colmajor_lower.setMode(CholmodSupernodalLLt);
   CholmodDecomposition<SparseType, Upper> g_chol_colmajor_upper;
   g_chol_colmajor_upper.setMode(CholmodSupernodalLLt);
   CholmodDecomposition<SparseType, Lower> g_llt_colmajor_lower;
   g_llt_colmajor_lower.setMode(CholmodSimplicialLLt);
   CholmodDecomposition<SparseType, Upper> g_llt_colmajor_upper;
   g_llt_colmajor_upper.setMode(CholmodSimplicialLLt);
   CholmodDecomposition<SparseType, Lower> g_ldlt_colmajor_lower;
   g_ldlt_colmajor_lower.setMode(CholmodLDLt);
   CholmodDecomposition<SparseType, Upper> g_ldlt_colmajor_upper;
   g_ldlt_colmajor_upper.setMode(CholmodLDLt);
   CholmodSupernodalLLT<SparseType, Lower> chol_colmajor_lower;
   CholmodSupernodalLLT<SparseType, Upper> chol_colmajor_upper;
   CholmodSimplicialLLT<SparseType, Lower> llt_colmajor_lower;
   CholmodSimplicialLLT<SparseType, Upper> llt_colmajor_upper;
   CholmodSimplicialLDLT<SparseType, Lower> ldlt_colmajor_lower;
   CholmodSimplicialLDLT<SparseType, Upper> ldlt_colmajor_upper;
   check_sparse_spd_solving(g_chol_colmajor_lower);
   check_sparse_spd_solving(g_chol_colmajor_upper);
   check_sparse_spd_solving(g_llt_colmajor_lower);
   check_sparse_spd_solving(g_llt_colmajor_upper);
   check_sparse_spd_solving(g_ldlt_colmajor_lower);
   check_sparse_spd_solving(g_ldlt_colmajor_upper);
   check_sparse_spd_solving(chol_colmajor_lower);
   check_sparse_spd_solving(chol_colmajor_upper);
   check_sparse_spd_solving(llt_colmajor_lower);
   check_sparse_spd_solving(llt_colmajor_upper);
   check_sparse_spd_solving(ldlt_colmajor_lower);
   check_sparse_spd_solving(ldlt_colmajor_upper);
   check_sparse_spd_determinant(chol_colmajor_lower);
   check_sparse_spd_determinant(chol_colmajor_upper);
   check_sparse_spd_determinant(llt_colmajor_lower);
   check_sparse_spd_determinant(llt_colmajor_upper);
   check_sparse_spd_determinant(ldlt_colmajor_lower);
   check_sparse_spd_determinant(ldlt_colmajor_upper);
   check_sparse_zero_matrix(chol_colmajor_lower);
   check_sparse_zero_matrix(chol_colmajor_upper);
   check_sparse_zero_matrix(llt_colmajor_lower);
   check_sparse_zero_matrix(llt_colmajor_upper);
   check_sparse_zero_matrix(ldlt_colmajor_lower);
   check_sparse_zero_matrix(ldlt_colmajor_upper);
 }
References check_sparse_spd_determinant(), check_sparse_spd_solving(), check_sparse_zero_matrix(), Eigen::CholmodLDLt, Eigen::CholmodSimplicialLLt, Eigen::CholmodSupernodalLLt, and Eigen::CholmodDecomposition< MatrixType_, UpLo_ >::setMode().
test_cholmod_T()
template<typename T , int flags, typename IdxType > void test_cholmod_T ()
                       {
   test_cholmod_ST<SparseMatrix<T, flags, IdxType> >();
 }
Referenced by EIGEN_DECLARE_TEST().