MercuryDPM: Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape > Struct Template Reference
Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape > Struct Template Reference
#include <SparsePermutation.h>
Public Types
using MatrixType = typename nested_eval< ExpressionType, 1 >::type
using MatrixTypeCleaned = remove_all_t< MatrixType >
using Scalar = typename MatrixTypeCleaned::Scalar
using StorageIndex = typename MatrixTypeCleaned::StorageIndex
using ReturnType = SparseMatrix< Scalar, MatrixTypeCleaned::IsRowMajor ? RowMajor :ColMajor, StorageIndex >
using TmpHelper = XprHelper< ExpressionType, ReturnType >
Static Public Member Functions
template<typename Dest , typename PermutationType >
static void permute_outer (Dest &dst, const PermutationType &perm, const ExpressionType &xpr)
template<typename Dest , typename PermutationType >
static void permute_inner (Dest &dst, const PermutationType &perm, const ExpressionType &xpr)
template<typename Dest , typename PermutationType , bool DoOuter = NeedOuterPermutation, std::enable_if_t< DoOuter, int > = 0>
static void run (Dest &dst, const PermutationType &perm, const ExpressionType &xpr)
template<typename Dest , typename PermutationType , bool DoOuter = NeedOuterPermutation, std::enable_if_t<!DoOuter, int > = 0>
static void run (Dest &dst, const PermutationType &perm, const ExpressionType &xpr)
Static Public Attributes
static constexpr bool NeedOuterPermutation = ExpressionType::IsRowMajor ? Side == OnTheLeft : Side == OnTheRight
static constexpr bool NeedInversePermutation = Transposed ? Side == OnTheLeft : Side == OnTheRight
Member Typedef Documentation
MatrixType
template<typename ExpressionType , int Side, bool Transposed> using Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape >::MatrixType = typename nested_eval<ExpressionType, 1>::type
MatrixTypeCleaned
template<typename ExpressionType , int Side, bool Transposed> using Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape >::MatrixTypeCleaned = remove_all_t<MatrixType>
ReturnType
template<typename ExpressionType , int Side, bool Transposed> using Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape >::ReturnType = SparseMatrix<Scalar, MatrixTypeCleaned::IsRowMajor ? RowMajor : ColMajor, StorageIndex>
Scalar
template<typename ExpressionType , int Side, bool Transposed> using Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape >::Scalar = typename MatrixTypeCleaned::Scalar
StorageIndex
template<typename ExpressionType , int Side, bool Transposed> using Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape >::StorageIndex = typename MatrixTypeCleaned::StorageIndex
TmpHelper
template<typename ExpressionType , int Side, bool Transposed> using Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape >::TmpHelper = XprHelper<ExpressionType, ReturnType>
Member Function Documentation
permute_inner()
template<typename ExpressionType , int Side, bool Transposed> template<typename Dest , typename PermutationType > static void Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape >::permute_inner (Dest & dst, const PermutationType & perm, const ExpressionType & xpr) inline static
{
     using InnerPermHelper = PermHelper<PermutationType, NeedInversePermutation>;
     using InnerPermType = typename InnerPermHelper::type;
     // if ExpressionType is not ReturnType, evaluate `xpr` (allocation)
     // otherwise, just reference `xpr`
     // TODO: handle trivial expressions such as CwiseBinaryOp without temporary
     const TmpHelper tmpHelper(xpr);
     const ReturnType& tmp = tmpHelper.xpr();
     // if inverse permutation of inner indices is requested, calculate perm.inverse() (allocation)
     // otherwise, just reference `perm`
     const InnerPermHelper permHelper(perm);
     const InnerPermType& innerPerm = permHelper.perm();
     ReturnType result(tmp.rows(), tmp.cols());
     for (Index j = 0; j < tmp.outerSize(); j++) {
       Index begin = tmp.outerIndexPtr()[j];
       Index end = tmp.isCompressed() ? tmp.outerIndexPtr()[j + 1] : begin + tmp.innerNonZeroPtr()[j];
       result.outerIndexPtr()[j + 1] += end - begin;
     }
     std::partial_sum(result.outerIndexPtr(), result.outerIndexPtr() + result.outerSize() + 1, result.outerIndexPtr());
     result.resizeNonZeros(result.nonZeros());
     for (Index j = 0; j < tmp.outerSize(); j++) {
       Index begin = tmp.outerIndexPtr()[j];
       Index end = tmp.isCompressed() ? tmp.outerIndexPtr()[j + 1] : begin + tmp.innerNonZeroPtr()[j];
       Index target = result.outerIndexPtr()[j];
       std::transform(tmp.innerIndexPtr() + begin, tmp.innerIndexPtr() + end, result.innerIndexPtr() + target,
                      [&innerPerm](StorageIndex i) { return innerPerm.indices().coeff(i); });
       smart_copy(tmp.valuePtr() + begin, tmp.valuePtr() + end, result.valuePtr() + target);
     }
     // the inner indices were permuted, and must be sorted
     result.sortInnerIndices();
     dst = std::move(result);
   }
References Eigen::PlainObjectBase< Derived >::cols(), Eigen::placeholders::end, i, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::innerIndexPtr(), j, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::nonZeros(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::outerIndexPtr(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::outerSize(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::resizeNonZeros(), Eigen::PlainObjectBase< Derived >::rows(), Eigen::internal::smart_copy(), Eigen::SparseCompressedBase< Derived >::sortInnerIndices(), tmp, transform(), compute_granudrum_aor::type, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::valuePtr(), and Eigen::internal::XprHelper< ExpressionType, PlainObjectType, NeedEval >::xpr().
permute_outer()
template<typename ExpressionType , int Side, bool Transposed> template<typename Dest , typename PermutationType > static void Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape >::permute_outer (Dest & dst, const PermutationType & perm, const ExpressionType & xpr) inline static
{
     // if ExpressionType is not ReturnType, evaluate `xpr` (allocation)
     // otherwise, just reference `xpr`
     // TODO: handle trivial expressions such as CwiseBinaryOp without temporary
     const TmpHelper tmpHelper(xpr);
     const ReturnType& tmp = tmpHelper.xpr();
     ReturnType result(tmp.rows(), tmp.cols());
     for (Index j = 0; j < tmp.outerSize(); j++) {
       Index jp = perm.indices().coeff(j);
       Index jsrc = NeedInversePermutation ? jp : j;
       Index jdst = NeedInversePermutation ? j : jp;
       Index begin = tmp.outerIndexPtr()[jsrc];
       Index end = tmp.isCompressed() ? tmp.outerIndexPtr()[jsrc + 1] : begin + tmp.innerNonZeroPtr()[jsrc];
       result.outerIndexPtr()[jdst + 1] += end - begin;
     }
     std::partial_sum(result.outerIndexPtr(), result.outerIndexPtr() + result.outerSize() + 1, result.outerIndexPtr());
     result.resizeNonZeros(result.nonZeros());
     for (Index j = 0; j < tmp.outerSize(); j++) {
       Index jp = perm.indices().coeff(j);
       Index jsrc = NeedInversePermutation ? jp : j;
       Index jdst = NeedInversePermutation ? j : jp;
       Index begin = tmp.outerIndexPtr()[jsrc];
       Index end = tmp.isCompressed() ? tmp.outerIndexPtr()[jsrc + 1] : begin + tmp.innerNonZeroPtr()[jsrc];
       Index target = result.outerIndexPtr()[jdst];
       smart_copy(tmp.innerIndexPtr() + begin, tmp.innerIndexPtr() + end, result.innerIndexPtr() + target);
       smart_copy(tmp.valuePtr() + begin, tmp.valuePtr() + end, result.valuePtr() + target);
     }
     dst = std::move(result);
   }
References Eigen::PlainObjectBase< Derived >::cols(), Eigen::placeholders::end, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::innerIndexPtr(), j, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::nonZeros(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::outerIndexPtr(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::outerSize(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::resizeNonZeros(), Eigen::PlainObjectBase< Derived >::rows(), Eigen::internal::smart_copy(), tmp, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::valuePtr(), and Eigen::internal::XprHelper< ExpressionType, PlainObjectType, NeedEval >::xpr().
run() [1/2]
template<typename ExpressionType , int Side, bool Transposed> template<typename Dest , typename PermutationType , bool DoOuter = NeedOuterPermutation, std::enable_if_t< DoOuter, int > = 0> static void Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape >::run (Dest & dst, const PermutationType & perm, const ExpressionType & xpr) inline static
{
     permute_outer(dst, perm, xpr);
   }
run() [2/2]
template<typename ExpressionType , int Side, bool Transposed> template<typename Dest , typename PermutationType , bool DoOuter = NeedOuterPermutation, std::enable_if_t<!DoOuter, int > = 0> static void Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape >::run (Dest & dst, const PermutationType & perm, const ExpressionType & xpr) inline static
{
     permute_inner(dst, perm, xpr);
   }
Member Data Documentation
NeedInversePermutation
template<typename ExpressionType , int Side, bool Transposed> constexpr bool Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape >::NeedInversePermutation = Transposed ? Side == OnTheLeft : Side == OnTheRight static constexpr
NeedOuterPermutation
template<typename ExpressionType , int Side, bool Transposed> constexpr bool Eigen::internal::permutation_matrix_product< ExpressionType, Side, Transposed, SparseShape >::NeedOuterPermutation = ExpressionType::IsRowMajor ? Side == OnTheLeft : Side == OnTheRight static constexpr
The documentation for this struct was generated from the following file:
SparsePermutation.h