MercuryDPM: oomph::CollapsibleChannelMesh< ELEMENT > Class Template Reference
oomph::CollapsibleChannelMesh< ELEMENT > Class Template Reference
#include <collapsible_channel_mesh.template.h>
Public Member Functions
CollapsibleChannelMesh (const unsigned &nup, const unsigned &ncollapsible, const unsigned &ndown, const unsigned &ny, const double &lup, const double &lcollapsible, const double &ldown, const double &ly, GeomObject *wall_pt, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
~CollapsibleChannelMesh ()
destructor
GeomObject *& wall_pt ()
Access function to GeomObject representing wall.
CollapsibleChannelDomain * domain_pt ()
Access function to domain.
virtual CollapsibleChannelDomain::BLSquashFctPt & bl_squash_fct_pt ()
CollapsibleChannelDomain::BLSquashFctPt bl_squash_fct_pt () const
virtual CollapsibleChannelDomain::AxialSpacingFctPt & axial_spacing_fct_pt ()
virtual CollapsibleChannelDomain::AxialSpacingFctPt & axial_spacing_fct_pt () const
Public Member Functions inherited from oomph::SimpleRectangularQuadMesh< ELEMENT >
SimpleRectangularQuadMesh (const unsigned &Nx, const unsigned &Ny, const double &Lx, const double &Ly, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
const unsigned & nx () const
Access function for number of elements in x directions.
const unsigned & ny () const
Access function for number of elements in y directions.
Public Member Functions inherited from oomph::QuadMeshBase
QuadMeshBase ()
Constructor (empty)
QuadMeshBase (const QuadMeshBase &node)=delete
Broken copy constructor.
void operator= (const QuadMeshBase &)=delete
Broken assignment operator.
virtual ~QuadMeshBase ()
Destructor (empty)
void setup_boundary_element_info ()
void setup_boundary_element_info (std::ostream &outfile)
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void node_update (const bool &update_all_solid_nodes=false)
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Protected Attributes
CollapsibleChannelDomain * Domain_pt
Pointer to domain.
unsigned Nup
Number of element columns in upstream part.
unsigned Ncollapsible
Number of element columns in collapsible part.
unsigned Ndown
Number of element columns in downstream part.
unsigned Ny
Number of element rows across channel.
GeomObject * Wall_pt
Pointer to geometric object that represents the moving wall.
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Detailed Description
template<class ELEMENT>
class oomph::CollapsibleChannelMesh< ELEMENT >
Basic collapsible channel mesh. The mesh is derived from the SimpleRectangularQuadMesh so it's node and element numbering scheme is the same as in that mesh. Only the boundaries are numbered differently to allow the easy identification of the "collapsible" segment. Boundary coordinates are set up for all nodes located on boundary 3 (the collapsible segment). The curvilinear ("collapsible") segment is defined by a GeomObject.
Constructor & Destructor Documentation
CollapsibleChannelMesh()
template<class ELEMENT > oomph::CollapsibleChannelMesh< ELEMENT >::CollapsibleChannelMesh (const unsigned & nup, const unsigned & ncollapsible, const unsigned & ndown, const unsigned & ny, const double & lup, const double & lcollapsible, const double & ldown, const double & ly, GeomObject * wall_pt, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
Constructor: Pass number of elements in upstream/collapsible/ downstream segment and across the channel; lengths of upstream/ collapsible/downstream segments and width of channel, pointer to GeomObject that defines the collapsible segment and pointer to TimeStepper (defaults to the default timestepper, Steady).
Constructor: Pass number of elements in upstream/collapsible/downstream segment and across the channel; lengths of upstream/collapsible/downstream segments and width of channel, pointer to GeomObject that defines the collapsible segment and pointer to TimeStepper (defaults to the default timestepper, Steady).
     : SimpleRectangularQuadMesh<ELEMENT>(nup + ncollapsible + ndown,
                                          ny,
                                          lup + lcollapsible + ldown,
                                          ly,
                                          time_stepper_pt),
       Nup(nup),
       Ncollapsible(ncollapsible),
       Ndown(ndown),
       Ny(ny),
       Wall_pt(wall_pt)
   {
     // Mesh can only be built with 2D Qelements.
     MeshChecker::assert_geometric_element<QElementGeometricBase, ELEMENT>(2);
     // Create the CollapsibleChannelDomain with the wall represented
     // by the geometric object
     Domain_pt = new CollapsibleChannelDomain(
       nup, ncollapsible, ndown, ny, lup, lcollapsible, ldown, ly, wall_pt);
     // Total number of (macro/finite)elements
     unsigned nmacro = (nup + ncollapsible + ndown) * ny;
     // Loop over all elements and set macro element pointer
     for (unsigned e = 0; e < nmacro; e++)
     {
       // Get pointer to finite element
       FiniteElement* el_pt = this->finite_element_pt(e);
       // Set pointer to macro element so the curvlinear boundaries
       // of the mesh/domain can get picked up during adaptive
       // mesh refinement
       el_pt->set_macro_elem_pt(this->Domain_pt->macro_element_pt(e));
     }
     // Update the nodal positions corresponding to their
     // macro element representations.
     this->node_update();
     // Update the boundary numbering scheme and set boundary coordinate
     //-----------------------------------------------------------------
     // (Note: The original SimpleRectangularQuadMesh had four boundaries.
     // We need to overwrite the boundary lookup scheme for the current
     // mesh so that the collapsible segment becomes identifiable).
     // While we're doing this, we're also setting up a boundary
     // coordinate for the nodes located on the collapsible segment.
     // The boundary coordinate can be used to setup FSI.
     // How many boundaries does the mesh have now?
     unsigned nbound = this->nboundary();
     for (unsigned b = 0; b < nbound; b++)
     {
       // Remove all nodes on this boundary from the mesh's lookup scheme
       // and also delete the reverse lookup scheme held by the nodes
       this->remove_boundary_nodes(b);
     }
 #ifdef PARANOID
     // Sanity check
     unsigned nnod = this->nnode();
     for (unsigned j = 0; j < nnod; j++)
     {
       if (this->node_pt(j)->is_on_boundary())
       {
         std::ostringstream error_message;
         error_message << "Node " << j << "is still on boundary " << std::endl;
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
     }
 #endif
     // Change the numbers of boundaries
     this->set_nboundary(6);
     // Get the number of nodes along the element edge from first element
     unsigned nnode_1d = this->finite_element_pt(0)->nnode_1d();
     // Vector of Lagrangian coordinates used as boundary coordinate
     Vector<double> zeta(1);
     // Index of first element underneath the collapsible bit
     unsigned first_collapsible = (ny - 1) * (nup + ncollapsible + ndown) + nup;
     // Zeta increment over elements (used for assignment of
     // boundary coordinate)
     double dzeta = lcollapsible / double(ncollapsible);
     // Manually loop over the elements near the boundaries and
     // assign nodes to boundaries. Also set up boundary coordinate
     unsigned nelem = this->nelement();
     for (unsigned e = 0; e < nelem; e++)
     {
       // Bottom row of elements
       if (e < nup + ncollapsible + ndown)
       {
         for (unsigned i = 0; i < nnode_1d; i++)
         {
           this->add_boundary_node(0, this->finite_element_pt(e)->node_pt(i));
         }
       }
       // Upstream upper rigid bit
       if ((e > (ny - 1) * (nup + ncollapsible + ndown) - 1) &&
           (e < (ny - 1) * (nup + ncollapsible + ndown) + nup))
       {
         for (unsigned i = 0; i < nnode_1d; i++)
         {
           this->add_boundary_node(
             4,
             this->finite_element_pt(e)->node_pt((nnode_1d - 1) * nnode_1d + i));
         }
       }
       // Collapsible bit
       if ((e > (ny - 1) * (nup + ncollapsible + ndown) + nup - 1) &&
           (e < (ny - 1) * (nup + ncollapsible + ndown) + nup + ncollapsible))
       {
         for (unsigned i = 0; i < nnode_1d; i++)
         {
           this->add_boundary_node(
             3,
             this->finite_element_pt(e)->node_pt((nnode_1d - 1) * nnode_1d + i));
           // What column of elements are we in?
           unsigned ix = e - first_collapsible;
           // Zeta coordinate
           zeta[0] =
             double(ix) * dzeta + double(i) * dzeta / double(nnode_1d - 1);
           // Set boundary coordinate
           this->finite_element_pt(e)
             ->node_pt((nnode_1d - 1) * nnode_1d + i)
             ->set_coordinates_on_boundary(3, zeta);
         }
       }
       // Downstream upper rigid bit
       if ((e >
            (ny - 1) * (nup + ncollapsible + ndown) + nup + ncollapsible - 1) &&
           (e < ny * (nup + ncollapsible + ndown)))
       {
         for (unsigned i = 0; i < nnode_1d; i++)
         {
           this->add_boundary_node(
             2,
             this->finite_element_pt(e)->node_pt((nnode_1d - 1) * nnode_1d + i));
         }
       }
       // Left end
       if (e % (nup + ncollapsible + ndown) == 0)
       {
         for (unsigned i = 0; i < nnode_1d; i++)
         {
           this->add_boundary_node(
             5, this->finite_element_pt(e)->node_pt(i * nnode_1d));
         }
       }
       // Right end
       if (e % (nup + ncollapsible + ndown) == (nup + ncollapsible + ndown) - 1)
       {
         for (unsigned i = 0; i < nnode_1d; i++)
         {
           this->add_boundary_node(
             1, this->finite_element_pt(e)->node_pt((i + 1) * nnode_1d - 1));
         }
       }
     }
     // Re-setup lookup scheme that establishes which elements are located
     // on the mesh boundaries (doesn't need to be wiped)
     this->setup_boundary_element_info();
     // We have only bothered to parametrise boundary 3
     this->Boundary_coordinate_exists[3] = true;
   }
References oomph::Mesh::add_boundary_node(), b, oomph::Mesh::Boundary_coordinate_exists, oomph::CollapsibleChannelMesh< ELEMENT >::Domain_pt, e(), oomph::Mesh::finite_element_pt(), i, j, Mesh_Parameters::ly, oomph::Domain::macro_element_pt(), oomph::Mesh::nboundary(), oomph::Mesh::nelement(), oomph::Mesh::nnode(), oomph::FiniteElement::nnode_1d(), oomph::FiniteElement::node_pt(), oomph::Mesh::node_pt(), oomph::Mesh::node_update(), oomph::SimpleRectangularQuadMesh< ELEMENT >::ny(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::Mesh::remove_boundary_nodes(), oomph::Node::set_coordinates_on_boundary(), oomph::FiniteElement::set_macro_elem_pt(), oomph::Mesh::set_nboundary(), oomph::QuadMeshBase::setup_boundary_element_info(), oomph::CollapsibleChannelMesh< ELEMENT >::wall_pt(), and Eigen::zeta().
~CollapsibleChannelMesh()
template<class ELEMENT > oomph::CollapsibleChannelMesh< ELEMENT >::~CollapsibleChannelMesh () inline
destructor
     {
       delete Domain_pt;
     }
References oomph::CollapsibleChannelMesh< ELEMENT >::Domain_pt.
Member Function Documentation
axial_spacing_fct_pt() [1/2]
template<class ELEMENT > virtual CollapsibleChannelDomain::AxialSpacingFctPt& oomph::CollapsibleChannelMesh< ELEMENT >::axial_spacing_fct_pt () inline virtual
Function pointer for function that redistributes the elements in the axial direction. Virtual so we can break it in derived classes (e.g. the Algebraic versions of this mesh where it doesn't make any sense to provide the bl_squash_fct after the mesh has been built).
Reimplemented in oomph::AlgebraicCollapsibleChannelMesh< ELEMENT >.
     {
       return Domain_pt->axial_spacing_fct_pt();
     }
References oomph::CollapsibleChannelDomain::axial_spacing_fct_pt(), and oomph::CollapsibleChannelMesh< ELEMENT >::Domain_pt.
axial_spacing_fct_pt() [2/2]
template<class ELEMENT > virtual CollapsibleChannelDomain::AxialSpacingFctPt& oomph::CollapsibleChannelMesh< ELEMENT >::axial_spacing_fct_pt () const inline virtual
Function pointer for function that redistributes the elements in the axial direction. Const version
     {
       return Domain_pt->axial_spacing_fct_pt();
     }
References oomph::CollapsibleChannelDomain::axial_spacing_fct_pt(), and oomph::CollapsibleChannelMesh< ELEMENT >::Domain_pt.
bl_squash_fct_pt() [1/2]
template<class ELEMENT > virtual CollapsibleChannelDomain::BLSquashFctPt& oomph::CollapsibleChannelMesh< ELEMENT >::bl_squash_fct_pt () inline virtual
Function pointer for function that squashes the mesh near the walls. Default trivial mapping (the identity) leaves vertical nodal positions unchanged. Mapping is used in underlying CollapsibleChannelDomain. Virtual so we can break it in derived classes (e.g. the Algebraic versions of this mesh where it doesn't make any sense to provide the bl_squash_fct after the mesh has been built).
Reimplemented in oomph::AlgebraicCollapsibleChannelMesh< ELEMENT >, and oomph::MyAlgebraicCollapsibleChannelMesh< ELEMENT >.
     {
       return Domain_pt->bl_squash_fct_pt();
     }
References oomph::CollapsibleChannelDomain::bl_squash_fct_pt(), and oomph::CollapsibleChannelMesh< ELEMENT >::Domain_pt.
bl_squash_fct_pt() [2/2]
template<class ELEMENT > CollapsibleChannelDomain::BLSquashFctPt oomph::CollapsibleChannelMesh< ELEMENT >::bl_squash_fct_pt () const inline
Function pointer for function that squashes the mesh near the walls. Default trivial mapping (the identity) leaves vertical nodal positions unchanged. Mapping is used in underlying CollapsibleChannelDomain. Const version.
     {
       return Domain_pt->bl_squash_fct_pt();
     }
References oomph::CollapsibleChannelDomain::bl_squash_fct_pt(), and oomph::CollapsibleChannelMesh< ELEMENT >::Domain_pt.
domain_pt()
template<class ELEMENT > CollapsibleChannelDomain* oomph::CollapsibleChannelMesh< ELEMENT >::domain_pt () inline
Access function to domain.
     {
       return Domain_pt;
     }
References oomph::CollapsibleChannelMesh< ELEMENT >::Domain_pt.
Referenced by oomph::MacroElementNodeUpdateCollapsibleChannelMesh< ELEMENT >::MacroElementNodeUpdateCollapsibleChannelMesh().
wall_pt()
template<class ELEMENT > GeomObject*& oomph::CollapsibleChannelMesh< ELEMENT >::wall_pt () inline
Access function to GeomObject representing wall.
     {
       return Wall_pt;
     }
References oomph::CollapsibleChannelMesh< ELEMENT >::Wall_pt.
Referenced by oomph::AlgebraicCollapsibleChannelMesh< ELEMENT >::AlgebraicCollapsibleChannelMesh(), and oomph::CollapsibleChannelMesh< ELEMENT >::CollapsibleChannelMesh().
Member Data Documentation
Domain_pt
template<class ELEMENT > CollapsibleChannelDomain* oomph::CollapsibleChannelMesh< ELEMENT >::Domain_pt protected
Pointer to domain.
Referenced by oomph::AlgebraicCollapsibleChannelMesh< ELEMENT >::AlgebraicCollapsibleChannelMesh(), oomph::CollapsibleChannelMesh< ELEMENT >::axial_spacing_fct_pt(), oomph::CollapsibleChannelMesh< ELEMENT >::bl_squash_fct_pt(), oomph::CollapsibleChannelMesh< ELEMENT >::CollapsibleChannelMesh(), oomph::CollapsibleChannelMesh< ELEMENT >::domain_pt(), oomph::MyAlgebraicCollapsibleChannelMesh< ELEMENT >::MyAlgebraicCollapsibleChannelMesh(), and oomph::CollapsibleChannelMesh< ELEMENT >::~CollapsibleChannelMesh().
Ncollapsible
template<class ELEMENT > unsigned oomph::CollapsibleChannelMesh< ELEMENT >::Ncollapsible protected
Number of element columns in collapsible part.
Ndown
template<class ELEMENT > unsigned oomph::CollapsibleChannelMesh< ELEMENT >::Ndown protected
Number of element columns in downstream part.
Nup
template<class ELEMENT > unsigned oomph::CollapsibleChannelMesh< ELEMENT >::Nup protected
Number of element columns in upstream part.
Ny
template<class ELEMENT > unsigned oomph::CollapsibleChannelMesh< ELEMENT >::Ny protected
Number of element rows across channel.
Wall_pt
template<class ELEMENT > GeomObject* oomph::CollapsibleChannelMesh< ELEMENT >::Wall_pt protected
Pointer to geometric object that represents the moving wall.
Referenced by oomph::MacroElementNodeUpdateCollapsibleChannelMesh< ELEMENT >::MacroElementNodeUpdateCollapsibleChannelMesh(), and oomph::CollapsibleChannelMesh< ELEMENT >::wall_pt().
The documentation for this class was generated from the following files:
collapsible_channel_mesh.template.h
collapsible_channel_mesh.template.cc