MercuryDPM: benchVecAdd.cpp File Reference
benchVecAdd.cpp File Reference
#include <iostream>
#include <Eigen/Core>
#include <bench/BenchTimer.h>
Macros
#define SIZE 50
#define REPEAT 10000
Typedefs
typedef float Scalar
Functions
__attribute__ ((noinline)) void benchVec(Scalar *a
__attribute__ ((noinline)) void benchVec(MatrixXf &a
int main (int argc, char *argv[])
void benchVec (MatrixXf &a, MatrixXf &b, MatrixXf &c)
void benchVec (VectorXf &a, VectorXf &b, VectorXf &c)
void benchVec (Scalar *a, Scalar *b, Scalar *c, int size)
Variables
Scalar * b = reinterpret_cast<Scalar *>(pb)
Scalar Scalar * c = reinterpret_cast<Scalar *>(pc)
Scalar Scalar int size = (SIDE(*side) == LEFT) ? (*m) : (*n)
Macro Definition Documentation
REPEAT
#define REPEAT 10000
SIZE
#define SIZE 50
Typedef Documentation
Scalar
typedef float Scalar
Function Documentation
__attribute__() [1/2]
__attribute__ ((noinline)) &
__attribute__() [2/2]
__attribute__ ((noinline))
benchVec() [1/3]
void benchVec (MatrixXf & a, MatrixXf & b, MatrixXf & c)
{
   for (int k = 0; k < REPEAT; ++k) a = a + b;
 }
References a, b, k, and REPEAT.
Referenced by main().
benchVec() [2/3]
void benchVec (Scalar * a, Scalar * b, Scalar * c, int size)
{
   typedef internal::packet_traits<Scalar>::type PacketScalar;
   const int PacketSize = internal::packet_traits<Scalar>::size;
   PacketScalar a0, a1, a2, a3, b0, b1, b2, b3;
   for (int k = 0; k < REPEAT; ++k)
     for (int i = 0; i < size; i += PacketSize * 8) {
       //             a0 = internal::pload(&a[i]);
       //             b0 = internal::pload(&b[i]);
       //             a1 = internal::pload(&a[i+1*PacketSize]);
       //             b1 = internal::pload(&b[i+1*PacketSize]);
       //             a2 = internal::pload(&a[i+2*PacketSize]);
       //             b2 = internal::pload(&b[i+2*PacketSize]);
       //             a3 = internal::pload(&a[i+3*PacketSize]);
       //             b3 = internal::pload(&b[i+3*PacketSize]);
       //             internal::pstore(&a[i], internal::padd(a0, b0));
       //             a0 = internal::pload(&a[i+4*PacketSize]);
       //             b0 = internal::pload(&b[i+4*PacketSize]);
       //
       //             internal::pstore(&a[i+1*PacketSize], internal::padd(a1, b1));
       //             a1 = internal::pload(&a[i+5*PacketSize]);
       //             b1 = internal::pload(&b[i+5*PacketSize]);
       //
       //             internal::pstore(&a[i+2*PacketSize], internal::padd(a2, b2));
       //             a2 = internal::pload(&a[i+6*PacketSize]);
       //             b2 = internal::pload(&b[i+6*PacketSize]);
       //
       //             internal::pstore(&a[i+3*PacketSize], internal::padd(a3, b3));
       //             a3 = internal::pload(&a[i+7*PacketSize]);
       //             b3 = internal::pload(&b[i+7*PacketSize]);
       //
       //             internal::pstore(&a[i+4*PacketSize], internal::padd(a0, b0));
       //             internal::pstore(&a[i+5*PacketSize], internal::padd(a1, b1));
       //             internal::pstore(&a[i+6*PacketSize], internal::padd(a2, b2));
       //             internal::pstore(&a[i+7*PacketSize], internal::padd(a3, b3));
       internal::pstore(&a[i + 2 * PacketSize], internal::padd(internal::ploadu(&a[i + 2 * PacketSize]),
                                                               internal::ploadu(&b[i + 2 * PacketSize])));
       internal::pstore(&a[i + 3 * PacketSize], internal::padd(internal::ploadu(&a[i + 3 * PacketSize]),
                                                               internal::ploadu(&b[i + 3 * PacketSize])));
       internal::pstore(&a[i + 4 * PacketSize], internal::padd(internal::ploadu(&a[i + 4 * PacketSize]),
                                                               internal::ploadu(&b[i + 4 * PacketSize])));
       internal::pstore(&a[i + 5 * PacketSize], internal::padd(internal::ploadu(&a[i + 5 * PacketSize]),
                                                               internal::ploadu(&b[i + 5 * PacketSize])));
       internal::pstore(&a[i + 6 * PacketSize], internal::padd(internal::ploadu(&a[i + 6 * PacketSize]),
                                                               internal::ploadu(&b[i + 6 * PacketSize])));
       internal::pstore(&a[i + 7 * PacketSize], internal::padd(internal::ploadu(&a[i + 7 * PacketSize]),
                                                               internal::ploadu(&b[i + 7 * PacketSize])));
     }
 }
References a, b, i, k, Eigen::internal::padd(), Eigen::internal::ploadu(), Eigen::internal::pstore(), REPEAT, size, and Eigen::internal::packet_traits< Scalar >::size.
benchVec() [3/3]
void benchVec (VectorXf & a, VectorXf & b, VectorXf & c)
{
   for (int k = 0; k < REPEAT; ++k) a = a + b;
 }
References a, b, k, and REPEAT.
main()
int main (int argc , char * argv[])
{
   int size = SIZE * 8;
   int size2 = size * size;
   Scalar* a = internal::aligned_new<Scalar>(size2);
   Scalar* b = internal::aligned_new<Scalar>(size2 + 4) + 1;
   Scalar* c = internal::aligned_new<Scalar>(size2);
   for (int i = 0; i < size; ++i) {
     a[i] = b[i] = c[i] = 0;
   }
   BenchTimer timer;
   timer.reset();
   for (int k = 0; k < 10; ++k) {
     timer.start();
     benchVec(a, b, c, size2);
     timer.stop();
   }
   std::cout << timer.value() << "s  " << (double(size2 * REPEAT) / timer.value()) / (1024. * 1024. * 1024.)
             << " GFlops\n";
   return 0;
   for (int innersize = size; innersize > 2; --innersize) {
     if (size2 % innersize == 0) {
       int outersize = size2 / innersize;
       MatrixXf ma = Map<MatrixXf>(a, innersize, outersize);
       MatrixXf mb = Map<MatrixXf>(b, innersize, outersize);
       MatrixXf mc = Map<MatrixXf>(c, innersize, outersize);
       timer.reset();
       for (int k = 0; k < 3; ++k) {
         timer.start();
         benchVec(ma, mb, mc);
         timer.stop();
       }
       std::cout << innersize << " x " << outersize << "  " << timer.value() << "s   "
                 << (double(size2 * REPEAT) / timer.value()) / (1024. * 1024. * 1024.) << " GFlops\n";
     }
   }
   VectorXf va = Map<VectorXf>(a, size2);
   VectorXf vb = Map<VectorXf>(b, size2);
   VectorXf vc = Map<VectorXf>(c, size2);
   timer.reset();
   for (int k = 0; k < 3; ++k) {
     timer.start();
     benchVec(va, vb, vc);
     timer.stop();
   }
   std::cout << timer.value() << "s   " << (double(size2 * REPEAT) / timer.value()) / (1024. * 1024. * 1024.)
             << " GFlops\n";
   return 0;
 }
References a, b, benchVec(), c, i, k, REPEAT, SIZE, and size.
Variable Documentation
b
const Scalar * b = reinterpret_cast<Scalar *>(pb)
Referenced by __attribute__(), Eigen::SolverBase< Derived >::_check_solve_assertion(), Eigen::CompleteOrthogonalDecomposition< MatrixType_, PermutationIndex_ >::_check_solve_assertion(), Eigen::SVDBase< Derived >::_check_solve_assertion(), Eigen::KLU< MatrixType_ >::_solve_impl(), Eigen::PardisoImpl< Derived >::_solve_impl(), Eigen::UmfPackLU< MatrixType_ >::_solve_impl(), Eigen::AccelerateImpl< MatrixType_, UpLo_, Solver_, EnforceSquare_ >::_solve_impl(), Eigen::CholmodBase< MatrixType_, UpLo_, Derived >::_solve_impl(), Eigen::SimplicialCholeskyBase< Derived >::_solve_impl(), Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::_solve_impl(), Eigen::SparseQR< MatrixType_, OrderingType_ >::_solve_impl(), Eigen::SPQR< MatrixType_ >::_solve_impl(), Eigen::SuperLU< MatrixType_ >::_solve_impl(), Eigen::PastixBase< Derived >::_solve_impl(), Eigen::DiagonalPreconditioner< Scalar_ >::_solve_impl(), Eigen::IncompleteCholesky< Scalar, UpLo_, OrderingType_ >::_solve_impl(), Eigen::IncompleteLUT< Scalar_, StorageIndex_ >::_solve_impl(), Eigen::IterativeSolverBase< Derived >::_solve_impl(), Eigen::IncompleteLU< Scalar_ >::_solve_impl(), Eigen::SparseSolverBase< Derived >::_solve_impl(), Eigen::BiCGSTAB< MatrixType_, Preconditioner_ >::_solve_vector_with_guess_impl(), Eigen::ConjugateGradient< MatrixType_, UpLo_, Preconditioner_ >::_solve_vector_with_guess_impl(), Eigen::LeastSquaresConjugateGradient< MatrixType_, Preconditioner_ >::_solve_vector_with_guess_impl(), Eigen::BiCGSTABL< MatrixType_, Preconditioner_ >::_solve_vector_with_guess_impl(), Eigen::DGMRES< MatrixType_, Preconditioner_ >::_solve_vector_with_guess_impl(), Eigen::GMRES< MatrixType_, Preconditioner_ >::_solve_vector_with_guess_impl(), Eigen::IDRS< MatrixType_, Preconditioner_ >::_solve_vector_with_guess_impl(), Eigen::IDRSTABL< MatrixType_, Preconditioner_ >::_solve_vector_with_guess_impl(), Eigen::MINRES< MatrixType_, UpLo_, Preconditioner_ >::_solve_vector_with_guess_impl(), Eigen::IterativeSolverBase< Derived >::_solve_with_guess_impl(), Jeffery_Solution::acceleration(), UnstructuredTorusProblem< ELEMENT >::actions_after_adapt(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::actions_after_adapt(), UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::actions_after_adapt(), UnstructuredSolidProblem< ELEMENT, MESH >::actions_after_adapt(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::actions_after_distribute(), UnstructuredTorusProblem< ELEMENT >::actions_before_adapt(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::actions_before_distribute(), ContactProblem< ELEMENT >::actions_before_implicit_timestep(), StefanBoltzmannProblem< ELEMENT >::actions_before_implicit_timestep(), RefineableUnsteadyHeatProblem< ELEMENT >::actions_before_implicit_timestep(), FlowAroundCylinderProblem< ELEMENT >::actions_before_implicit_timestep(), UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::actions_before_newton_convergence_check(), RefineableOneDPoissonProblem< ELEMENT >::actions_before_newton_solve(), PRefineableOneDPoissonProblem< ELEMENT >::actions_before_newton_solve(), PrescribedBoundaryDisplacementProblem< ELEMENT >::actions_before_newton_solve(), oomph::RefineableTetgenMesh< ELEMENT >::adapt(), oomph::RefineableGmshTetMesh< ELEMENT >::adapt(), oomph::TreeBasedRefineableMeshBase::adapt_mesh(), oomph::Mesh::add_boundary_node(), FlowAroundCylinderProblem< ELEMENT >::add_eigenproblem(), oomph::Node::add_to_boundary(), oomph::BoundaryNodeBase::add_to_boundary(), oomph::BoundaryNode< NODE_TYPE >::add_to_boundary(), adjoint_extra(), AirwayReopeningProblem< ELEMENT >::AirwayReopeningProblem(), aliasing_with_resize(), alignedboxTranslatable(), Jeffery_Solution::angle(), oomph::VectorHelpers::angle(), AngledPeriodicBoundarySecondUnitTest::AngledPeriodicBoundarySecondUnitTest(), AngledPeriodicBoundaryUnitTest::AngledPeriodicBoundaryUnitTest(), Quaternion< float >::angularVelocityBodyFixedFrameToAngularDisplacement(), MovingBlockProblem< ELEMENT >::apply_boundary_conditions(), ExtrudedMovingCylinderProblem< TWO_D_ELEMENT, THREE_D_ELEMENT >::apply_boundary_conditions(), PMLStructuredCubicHelmholtz< ELEMENT >::apply_boundary_conditions(), PMLHelmholtzMGProblem< ELEMENT >::apply_boundary_conditions(), FlowAroundCylinderProblem< ELEMENT >::apply_boundary_conditions(), NavierStokesProblem< ELEMENT >::apply_boundary_conditions(), PMLProblem< ELEMENT >::apply_boundary_conditions(), UnsteadyHeatProblem< ELEMENT >::apply_boundary_conditions(), TwoDDGProblem< ELEMENT >::apply_boundary_conditions(), PMLFourierDecomposedHelmholtzProblem< ELEMENT >::apply_zero_dirichlet_boundary_conditions(), Eigen::test::areApprox(), Eigen::test::areApproxAbs(), Eigen::test::areEqual(), array_special_functions(), Eigen::internal::array_zip(), Eigen::internal::array_zip_and_reduce(), Eigen::internal::assign_op< DstScalar, SrcScalar >::assignCoeff(), Eigen::internal::add_assign_op< DstScalar, SrcScalar >::assignCoeff(), Eigen::internal::sub_assign_op< DstScalar, SrcScalar >::assignCoeff(), Eigen::internal::mul_assign_op< DstScalar, SrcScalar >::assignCoeff(), Eigen::internal::div_assign_op< DstScalar, SrcScalar >::assignCoeff(), Eigen::internal::swap_assign_op< Scalar >::assignCoeff(), Eigen::internal::assign_op< DstScalar, SrcScalar >::assignPacket(), Eigen::internal::add_assign_op< DstScalar, SrcScalar >::assignPacket(), Eigen::internal::sub_assign_op< DstScalar, SrcScalar >::assignPacket(), Eigen::internal::mul_assign_op< DstScalar, SrcScalar >::assignPacket(), Eigen::internal::div_assign_op< DstScalar, SrcScalar >::assignPacket(), Eigen::atan2(), Eigen::bfloat16_impl::atan2(), Eigen::half_impl::atan2(), BaseSpecies::average(), BaseSpecies::averageInf(), AxialSolidQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::AxialSolidQuarterTubeMesh(), bandmatrix(), BaseBoundary::BaseBoundary(), BasePeriodicBoundary::BasePeriodicBoundary(), BaseStateProblem< BASE_ELEMENT >::BaseStateProblem(), BasicIntersectionOfWalls::BasicIntersectionOfWalls(), basicStuff(), BasicUnionOfWalls::BasicUnionOfWalls(), bench(), bench_prod(), benchVec(), CRBond_Bessel::bessik01a(), CRBond_Bessel::bessjy01a(), CRBond_Bessel::bessjynb(), CRBond_Bessel::bessjyv(), Eigen::betainc(), oomph::BiharmonicFluxElement< DIM >::BiharmonicFluxElement(), Eigen::internal::bytewise_bitwise_helper< T >::binary(), Eigen::test::biteq(), Eigen::internal::operator_bitwise_helper< T >::bitwise_and(), Eigen::internal::bytewise_bitwise_helper< T >::bitwise_and(), Eigen::internal::operator_bitwise_helper< T >::bitwise_or(), Eigen::internal::bytewise_bitwise_helper< T >::bitwise_or(), Eigen::internal::operator_bitwise_helper< T >::bitwise_xor(), Eigen::internal::bytewise_bitwise_helper< T >::bitwise_xor(), Global_Parameters::blended_grad_velocity_pseudo_singularity_for_couette(), Global_Parameters::blended_pressure_pseudo_singularity_for_couette(), Global_Parameters::blended_velocity_pseudo_singularity_for_couette(), block(), oomph::BlockPreconditioner< MATRIX >::block_distribution_pt(), oomph::BlockPreconditioner< MATRIX >::block_setup(), BlockCompressionProblem< ELEMENT >::BlockCompressionProblem(), oomph::AxisymmetricLinearElasticityEquationsBase::body_force(), oomph::LinearElasticityEquationsBase< DIM >::body_force(), Global_Parameters::body_force(), oomph::PMLTimeHarmonicLinearElasticityEquationsBase< DIM >::body_force(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquationsBase::body_force(), oomph::TimeHarmonicLinearElasticityEquationsBase< DIM >::body_force(), Global_Physical_Variables::body_force(), oomph::PVDEquationsBase< DIM >::body_force(), rapidjson::GenericDocument< Encoding, Allocator >::Bool_(), rapidjson::PrettyWriter< Stream, Encoding, Allocator >::Bool_(), rapidjson::Writer< Stream, Encoding, Allocator >::Bool_(), oomph::RefineableTriangleMesh< ELEMENT >::boundary_connections(), oomph::UnstructuredTwoDMeshGeometryBase::boundary_coordinate_limits(), oomph::TetMeshBase::boundary_element_in_region_pt(), oomph::UnstructuredTwoDMeshGeometryBase::boundary_element_in_region_pt(), oomph::Mesh::boundary_element_pt(), oomph::UnstructuredTwoDMeshGeometryBase::boundary_geom_object_pt(), oomph::Mesh::boundary_node_pt(), oomph::SolidMesh::boundary_node_pt(), oomph::DiskLikeGeomObjectWithBoundaries::boundary_parametrising_geom_object_pt(), oomph::UnstructuredTwoDMeshGeometryBase::boundary_polyline_pt(), oomph::DiskTetMeshFacetedSurface::boundary_zeta01(), BoundaryHandler::boundaryActionsBeforeTimeLoop(), bounding_box(), Eigen::internal::bruteforce_det3_helper(), bug1150(), bug_127(), bug_1311(), oomph::Mesh::build_face_mesh(), oomph::GmshTetMesh< ELEMENT >::build_it(), PrescribedBoundaryDisplacementProblem< ELEMENT >::build_mesh(), RefineableUnsteadyHeatProblem< ELEMENT >::build_mesh(), oomph::BackwardStepQuadMesh< ELEMENT >::build_mesh(), oomph::ExtrudedCubeMeshFromQuadMesh< ELEMENT >::build_mesh(), oomph::BrickFromTetMesh< ELEMENT >::build_mesh(), RectangularWomersleyImpedanceTube< ELEMENT >::build_mesh_and_apply_boundary_conditions(), CombCanSpineMesh< ELEMENT, INTERFACE_ELEMENT >::build_single_layer_mesh(), CombTipSpineMesh< ELEMENT, INTERFACE_ELEMENT >::build_single_layer_mesh(), STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::build_single_layer_mesh(), buildProblem(), Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::calc_hadj_inner(), oomph::RefineableSolidCubicMesh< ELEMENT >::calculate_boundary_coordinate_of_node(), oomph::HomogenisedLinearElasticityEquations< DIM >::calculate_effective_modulus(), oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_fitting_parameters_of_cubic(), oomph::CassonTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_fitting_parameters_of_cubic(), GlobalParameters::calculate_strouhal_number(), call_directsolver(), call_itersolver(), call_ref(), call_ref_1(), call_ref_2(), call_ref_3(), call_ref_4(), call_ref_5(), call_ref_6(), call_ref_7(), call_solver(), CapProblem< ELEMENT >::CapProblem(), pcast_array< SrcPacket, TgtPacket, 2, 1 >::cast(), pcast_array< SrcPacket, TgtPacket, 4, 1 >::cast(), pcast_array< SrcPacket, TgtPacket, 8, 1 >::cast(), Eigen::internal::cat256(), Eigen::internal::cat256i(), CRBond_Bessel::cbessik01(), CRBond_Bessel::cbessjy01(), CRBond_Bessel::cbessjynb(), check(), Eigen::internal::check_implication(), check_indexed_view(), oomph::VectorHelpers::check_lengths_match(), check_sparse_leastsquare_solving(), check_sparse_nonhermitian_solving(), check_sparse_solving(), check_sparse_solving_real_cases(), check_sparse_spd_solving(), check_sparse_square_solving(), DropletBoundary::checkBoundaryAfterParticlesMove(), Mercury3Dclump::checkClumpForInteractionPeriodic(), DPMBase::checkInteractionWithBoundaries(), DPMBase::checkParticleForInteractionLocalPeriodic(), StressStrainControlBoundary::checkPeriodicLeesEdwardsBoundariesAfterParticlesMove(), Eigen::AlignedBox< Scalar_, AmbientDim_ >::clamp(), oomph::BlockPreconditioner< MATRIX >::clear_block_preconditioner_base(), NurbsUtils::close(), ClosedCSCWalls::ClosedCSCWalls(), CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::CoatedSphereProblem(), Eigen::internal::scalar_inner_product_op< LhsScalar, RhsScalar, Conj >::coeff(), Eigen::internal::scalar_inner_product_op< Scalar, Scalar, Conj >::coeff(), oomph::CollapsibleChannelMesh< ELEMENT >::CollapsibleChannelMesh(), Eigen::internal::combine2Packet16h(), compare(), Eigen::internal::minmax_compare< Scalar, NaNPropagation, is_min >::compare(), Eigen::internal::minmax_compare< Scalar, NaNPropagation, false >::compare(), CompareFunction(), MeltContactProblem< ELEMENT >::complete_problem_setup(), SolarRadiationProblem< ELEMENT >::complete_problem_setup(), ContactProblem< ELEMENT >::complete_problem_setup(), UnsteadyHeatMeltProblem< ELEMENT >::complete_problem_setup(), HomogenisationProblem< ELEMENT >::complete_problem_setup(), ElasticAnnulusProblem< ELASTICITY_ELEMENT >::complete_problem_setup(), Eigen::internal::complex_log(), CompressedSquareProblem< ELEMENT >::CompressedSquareProblem(), Eigen::GeneralizedEigenSolver< MatrixType_ >::compute(), oomph::InexactSubBiharmonicPreconditioner::compute_inexact_schur_complement(), LiquidBridgeBagheriInteraction::computeAdhesionForce(), Mercury3Dclump::computeAllForces(), Eigen::ThreadPoolTempl< Environment >::ComputeCoprimes(), DPMBase::computeOneTimeStep(), Eigen::ComplexSchur< MatrixType_ >::computeShift(), Eigen::BDCSVD< MatrixType_, Options_ >::computeSingVals(), AirwayReopeningProblem< ELEMENT >::construct_poisson_outlet_elements(), AirwayReopeningProblem< ELEMENT >::construct_pressure_gradient_outlet_elements(), oomph::OcTree::construct_rotation_matrix(), Eigen::AlignedBox< Scalar_, AmbientDim_ >::contains(), oomph::FaceElement::continuous_tangent_and_outer_unit_normal(), SCoupling< M, O >::coupleBoundaries(), SCoupling< M, O >::coupleBoundary(), ShellProblem< ELEMENT >::create_bc_elements(), oomph::TwoDimensionalPMLHelper::create_bottom_left_pml_mesh(), oomph::TwoDimensionalPMLHelper::create_bottom_pml_mesh(), oomph::TwoDimensionalPMLHelper::create_bottom_right_pml_mesh(), RefineableYoungLaplaceProblem< ELEMENT >::create_contact_angle_elements(), YoungLaplaceProblem< ELEMENT >::create_contact_angle_elements(), MeltContactProblem< ELEMENT >::create_contact_elements(), SolarRadiationProblem< ELEMENT >::create_contact_elements(), ContactProblem< ELEMENT >::create_contact_elements(), ContactProblem< ELEMENT >::create_contact_heat_elements_on_boulder(), ContactProblem< ELEMENT >::create_displ_imposition_elements(), UnstructuredImmersedEllipseProblem< ELEMENT >::create_drag_elements(), UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_fluid_traction_elements(), UnstructuredFluidProblem< ELEMENT >::create_fluid_traction_elements(), MeltContactProblem< ELEMENT >::create_flux_elements(), SolarRadiationProblem< ELEMENT >::create_flux_elements(), UnsteadyHeatMeltProblem< ELEMENT >::create_flux_elements(), UnsteadyHeatProblem< ELEMENT >::create_flux_elements(), FluxPoissonMGProblem< ELEMENT, MESH >::create_flux_elements(), FluxPoissonProblem< ELEMENT >::create_flux_elements(), ScatteringProblem< ELEMENT >::create_flux_elements(), PMLProblem< ELEMENT >::create_flux_elements(), TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::create_flux_elements(), LinearWaveProblem< ELEMENT, TIMESTEPPER >::create_flux_elements(), RefineableUnsteadyHeatProblem< ELEMENT >::create_flux_elements(), RefineableTwoMeshFluxPoissonProblem< ELEMENT >::create_flux_elements(), AxisymFreeSurfaceNozzleAdvDiffRobinProblem< ELEMENT >::create_flux_elements(), TwoMeshFluxPoissonProblem< ELEMENT >::create_flux_elements(), TwoMeshFluxSteadyAxisymAdvectionDiffusionProblem< ELEMENT >::create_flux_elements(), FourierDecomposedHelmholtzProblem< ELEMENT >::create_flux_elements_on_inner_boundary(), PMLFourierDecomposedHelmholtzProblem< ELEMENT >::create_flux_elements_on_inner_boundary(), PseudoSolidCapProblem< ELEMENT >::create_free_surface_elements(), TwoLayerInterfaceProblem< ELEMENT >::create_free_surface_elements(), RisingBubbleProblem< ELEMENT >::create_free_surface_elements(), BubbleInChannelProblem< ELEMENT >::create_free_surface_elements(), DropInChannelProblem< ELEMENT >::create_free_surface_elements(), CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_fsi_traction_elements(), CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_fsi_traction_elements(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_fsi_traction_elements(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_fsi_traction_elements(), UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_fsi_traction_elements(), CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_helmholtz_ABC_elements(), CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_helmholtz_DtN_elements(), CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_helmholtz_DtN_elements(), CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_helmholtz_fsi_flux_elements(), CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_helmholtz_fsi_flux_elements(), ContactProblem< ELEMENT >::create_imposed_heat_flux_elements_on_boulder(), UnstructuredTorusProblem< ELEMENT >::create_lagrange_multiplier_elements(), FSICollapsibleChannelProblem< ELEMENT >::create_lagrange_multiplier_elements(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_lagrange_multiplier_elements(), FSIChannelWithLeafletProblem< ELEMENT >::create_lagrange_multiplier_elements(), UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_lagrange_multiplier_elements(), PrescribedBoundaryDisplacementProblem< ELEMENT >::create_lagrange_multiplier_elements(), UnstructuredImmersedEllipseProblem< ELEMENT >::create_lagrange_multiplier_elements(), UnstructuredFluidProblem< ELEMENT >::create_lagrange_multiplier_elements(), CollapsibleChannelProblem< ELEMENT >::create_lagrange_multiplier_elements(), oomph::TwoDimensionalPMLHelper::create_left_pml_mesh(), MeltContactProblem< ELEMENT >::create_melt_elements(), StefanBoltzmannProblem< ELEMENT >::create_melt_elements(), FourierDecomposedHelmholtzProblem< ELEMENT >::create_outer_bc_elements(), HelmholtzPointSourceProblem< ELEMENT >::create_outer_bc_elements(), ScatteringProblem< ELEMENT >::create_outer_bc_elements(), TiltedCavityProblem< ELEMENT >::create_parall_outflow_lagrange_elements(), UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_parallel_flow_lagrange_elements(), UnstructuredFluidProblem< ELEMENT >::create_parallel_outflow_lagrange_elements(), PMLProblem< ELEMENT >::create_power_elements(), PMLFourierDecomposedHelmholtzProblem< ELEMENT >::create_power_monitor_mesh(), FpTestProblem::create_refineable_traction_elements(), oomph::TwoDimensionalPMLHelper::create_right_pml_mesh(), StefanBoltzmannProblem< ELEMENT >::create_sb_elements(), CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_solid_traction_elements(), CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_solid_traction_elements(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_solid_traction_elements(), oomph::TwoDimensionalPMLHelper::create_top_left_pml_mesh(), oomph::TwoDimensionalPMLHelper::create_top_pml_mesh(), oomph::TwoDimensionalPMLHelper::create_top_right_pml_mesh(), CantileverProblem< ELEMENT >::create_traction_elements(), FpTestProblem::create_traction_elements(), BlockCompressionProblem< ELEMENT >::create_traction_elements(), UnstructuredSolidProblem< ELEMENT, MESH >::create_traction_elements(), AnnularDiskProblem< ELASTICITY_ELEMENT >::create_traction_elements(), RingWithTRibProblem< ELASTICITY_ELEMENT >::create_traction_elements(), CollapsibleChannelProblem< ELEMENT >::create_traction_elements(), RayleighTractionProblem< ELEMENT, TIMESTEPPER >::create_traction_elements(), FSICollapsibleChannelProblem< ELEMENT >::create_traction_elements(), SheetGlueProblem< ELEMENT >::create_traction_elements(), CapProblem< ELEMENT >::create_volume_constraint_elements(), PseudoSolidCapProblem< ELEMENT >::create_volume_constraint_elements(), RefineableRotatingCylinderProblem< ELEMENT >::create_volume_constraint_elements(), FreeSurfaceRotationProblem< ELEMENT >::create_volume_constraint_elements(), SolidFreeSurfaceRotationProblem< ELEMENT >::create_volume_constraint_elements(), RisingBubbleProblem< ELEMENT >::create_volume_constraint_elements(), BubbleInChannelProblem< ELEMENT >::create_volume_constraint_elements(), DropInChannelProblem< ELEMENT >::create_volume_constraint_elements(), StressStrainControlBoundary::createPeriodicParticles(), Eigen::createRandomPIMatrixOfRank(), Vec3D::cross(), CSCWalls::CSCWalls(), ctms_decompositions(), oomph::Ellipse::d2position(), UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::delete_fsi_traction_elements(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::delete_fsi_traction_elements(), UnstructuredTorusProblem< ELEMENT >::delete_lagrange_multiplier_elements(), UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::delete_lagrange_multiplier_elements(), demo_smoothing_with_linear_elasticity(), demo_smoothing_with_poisson(), dense_storage_swap(), chwirut2_functor::df(), misra1a_functor::df(), hahn1_functor::df(), misra1d_functor::df(), lanczos1_functor::df(), rat42_functor::df(), MGH10_functor::df(), BoxBOD_functor::df(), MGH17_functor::df(), MGH09_functor::df(), Bennett5_functor::df(), thurber_functor::df(), rat43_functor::df(), eckerle4_functor::df(), HGridOptimiser::diffEndExpectedCellsIntegral(), HGridOptimiser::diffHExpectedCellsIntegralCellNumerator(), HGridOptimiser::diffPdfInt(), HGridOptimiser::diffStartExpectedCellsIntegral(), oomph::DiskTetMeshFacetedSurface::DiskTetMeshFacetedSurface(), oomph::DiskWithTorusAroundEdgeTetMeshFacetedSurface::DiskWithTorusAroundEdgeTetMeshFacetedSurface(), oomph::MyProblem::doc_boundaries(), UnstructuredFluidProblem< ELEMENT >::doc_boundary_coordinates(), oomph::Mesh::doc_boundary_coordinates(), UnstructuredFvKProblem< ELEMENT >::doc_solution(), TetmeshPoissonProblem< ELEMENT >::doc_solution(), CantileverProblem< ELEMENT >::doc_solution(), oomph::BlockPreconditioner< MATRIX >::document(), doEigen(), oomph::BlockPreconditioner< MATRIX >::dof_block_distribution_pt(), Domain::Domain(), Vec3D::dot(), oomph::VectorHelpers::dot(), oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::dviscosity_dinvariant(), oomph::CassonTanMilRegWithBlendingConstitutiveEquation< DIM >::dviscosity_dinvariant(), Matrix3D::dyadic(), EIGEN_DECLARE_TEST(), ElasticBeamProblem::ElasticBeamProblem(), ElasticInterfaceProblem< ELEMENT, TIMESTEPPER >::ElasticInterfaceProblem(), ElasticQuarterTubeMesh< ELEMENT >::ElasticQuarterTubeMesh(), oomph::ElasticRefineableRectangularQuadMesh< ELEMENT >::ElasticRefineableRectangularQuadMesh(), Eigen::internal::enum_eq_not_dynamic(), Eigen::internal::enum_ge_not_dynamic(), Eigen::internal::enum_gt_not_dynamic(), Eigen::internal::enum_le_not_dynamic(), Eigen::internal::enum_lt_not_dynamic(), Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::evalToBuf(), HGridOptimiser::expectedCellsIntegralCellDenominator(), HGridOptimiser::expectedCellsIntegralCellNumerator(), Eigen::AlignedBox< Scalar_, AmbientDim_ >::extend(), Eigen::AlignedBox< Scalar_, AmbientDim_ >::exteriorDistance(), Eigen::internal::extract2Packet16h(), oomph::Mesh::face_index_at_boundary(), oomph::TetMeshBase::face_index_at_boundary_in_region(), oomph::UnstructuredTwoDMeshGeometryBase::face_index_at_boundary_in_region(), oomph::KirchhoffLoveBeamEquations::fill_in_contribution_to_residuals_beam(), oomph::KirchhoffLoveShellEquations::fill_in_contribution_to_residuals_shell(), oomph::AxisymmetricLinearElasticityEquations::fill_in_generic_contribution_to_residuals_axisymmetric_linear_elasticity(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::fill_in_generic_contribution_to_residuals_fourier_decomp_time_harmonic_linear_elasticity(), oomph::HomogenisedLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_linear_elasticity(), oomph::LinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_linear_elasticity(), oomph::RefineableLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_linear_elasticity(), oomph::RefineableQDPVDElement< DIM, NNODE_1D >::fill_in_generic_contribution_to_residuals_pvd(), oomph::RefineablePVDEquations< DIM >::fill_in_generic_contribution_to_residuals_pvd(), oomph::PVDEquations< DIM >::fill_in_generic_contribution_to_residuals_pvd(), oomph::ScaleCoupledElement< ELEMENT >::fill_in_generic_contribution_to_residuals_pvd(), oomph::VolumeCoupledElement< ELEMENT >::fill_in_generic_contribution_to_residuals_pvd(), oomph::PMLTimeHarmonicLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity(), oomph::RefineableTimeHarmonicLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity(), oomph::TimeHarmonicLinearElasticityEquations< DIM >::fill_in_generic_contribution_to_residuals_time_harmonic_linear_elasticity(), oomph::RefineablePVDEquationsWithPressure< DIM >::fill_in_generic_residual_contribution_pvd_with_pressure(), oomph::PVDEquationsWithPressure< DIM >::fill_in_generic_residual_contribution_pvd_with_pressure(), DPMBase::fillDomainWithParticles(), PeriodicBoundaryHandler::findNewParticle(), oomph::AxisymmetricPoroelasticityEquations::fluid_body_force(), FluidTetMesh< ELEMENT >::FluidTetMesh(), FluxPoissonMGProblem< ELEMENT, MESH >::FluxPoissonMGProblem(), FluxPoissonProblem< ELEMENT >::FluxPoissonProblem(), Eigen::bfloat16_impl::fmax(), boost::multiprecision::fmax(), Eigen::bfloat16_impl::fmin(), Eigen::bfloat16_impl::fmod(), Eigen::half_impl::fmod(), Eigen::numext::fmod(), foo(), oomph::PoroelasticityEquations< DIM >::force_fluid(), oomph::PoroelasticityEquations< DIM >::force_solid(), FreeSurfaceRotationProblem< ELEMENT >::FreeSurfaceRotationProblem(), Eigen::Quaternion< Scalar_, Options_ >::FromTwoVectors(), FSIChannelWithLeafletProblem< ELEMENT >::FSIChannelWithLeafletProblem(), FSICollapsibleChannelProblem< ELEMENT >::FSICollapsibleChannelProblem(), oomph::FSIDrivenCavityMesh< ELEMENT >::FSIDrivenCavityMesh(), FSIDrivenCavityProblem< ELEMENT >::FSIDrivenCavityProblem(), gemm(), Eigen::internal::gemm_kern_avx512(), gemv_mult_complex_complex(), gemv_mult_complex_real(), gemv_mult_generic(), gemv_mult_real_complex(), GeneralEllipse::GeneralEllipse(), generalized_eigensolver_real(), oomph::GeompackQuadScaffoldMesh::GeompackQuadScaffoldMesh(), oomph::BlockPreconditioner< MATRIX >::get_block_ordered_preconditioner_vector(), oomph::BlockPreconditioner< MATRIX >::get_block_vector(), oomph::BlockPreconditioner< MATRIX >::get_block_vectors(), oomph::RefineableQElement< 3 >::get_boundaries(), oomph::BoundaryNodeBase::get_coordinates_on_boundary(), oomph::Node::get_coordinates_on_boundary(), oomph::BoundaryNode< NODE_TYPE >::get_coordinates_on_boundary(), oomph::ExtrudedCubeMeshFromQuadMesh< ELEMENT >::get_element_boundary_information(), oomph::KirchhoffLoveShellEquations::get_energy(), oomph::KirchhoffLoveBeamEquations::get_energy(), RachelsAdvectionDiffusion::get_exact_u(), oomph::CRDoubleMatrix::get_matrix_transpose(), oomph::NavierStokesSchurComplementPreconditioner::get_pressure_advection_diffusion_matrix(), oomph::KirchhoffLoveShellEquations::get_strain_and_bend(), PolarNSProblem< ELEMENT >::get_symmetry(), SheetGlueProblem< ELEMENT >::get_unique_nodes_that_meet_sidewalls(), oomph::StreamfunctionProblem::get_vels(), Vec3D::getDistance(), NurbsSurface::getDistance(), HorizontalScrew::getDistanceAndNormal(), Vec3D::getDistanceSquared(), CGCoordinates::Base_X_Y_Z::getGaussIntegralPrefactor(), CGCoordinates::Base_XY_XZ_YZ::getGaussIntegralPrefactor(), CGCoordinates::XYZ::getGaussIntegralPrefactor(), Quaternion< float >::getLength(), ParticleHandler::getPSD(), SCoupling< M, O >::getSCoupledElements(), TriangleMeshWall::getVolumeTetrahedron(), GluedSolidMesh::glue(), Gravity::gravity(), gravity::gravity(), Global_Parameters::gravity(), Global_Physical_Variables::gravity(), Eigen::internal::h_array_zip(), Eigen::internal::h_array_zip_and_reduce(), Eigen::internal::idrs(), oomph::BiharmonicFluidProblem< DIM >::impose_fluid_flow_on_edge(), oomph::BiharmonicFluidProblem< DIM >::impose_solid_boundary_on_edge(), oomph::BiharmonicFluidProblem< DIM >::impose_traction_free_edge(), InitialConditions< SpeciesType >::InitialConditions(), inplace(), insertCoefficient(), InterfaceProblem< ELEMENT, TIMESTEPPER >::InterfaceProblem(), oomph::BlockPreconditioner< MATRIX >::internal_block_dimension(), oomph::BlockPreconditioner< MATRIX >::internal_block_distribution_pt(), oomph::BlockPreconditioner< MATRIX >::internal_get_block_ordered_preconditioner_vector(), oomph::BlockPreconditioner< MATRIX >::internal_get_block_vector(), oomph::BlockPreconditioner< MATRIX >::internal_get_block_vectors(), oomph::BlockPreconditioner< MATRIX >::internal_master_dof_number(), oomph::BlockPreconditioner< MATRIX >::internal_return_block_ordered_preconditioner_vector(), oomph::BlockPreconditioner< MATRIX >::internal_return_block_vector(), oomph::BlockPreconditioner< MATRIX >::internal_return_block_vectors(), Eigen::SplineFitting< SplineType >::InterpolateWithDerivatives(), Eigen::AlignedBox< Scalar_, AmbientDim_ >::intersection(), BallPointStuff< Dim >::intersectObject(), BallPointStuff< Dim >::intersectObjectObject(), BallPointStuff< Dim >::intersectObjectVolume(), Eigen::AlignedBox< Scalar_, AmbientDim_ >::intersects(), BallPointStuff< Dim >::intersectVolumeObject(), inverse_zerosized(), exp_complex_test_impl< Scalar, Packet, HasExp >::is_exactly_equal(), oomph::BoundaryNodeBase::is_on_boundary(), oomph::BoundaryNode< NODE_TYPE >::is_on_boundary(), is_same_block(), is_same_eq(), is_same_seq(), is_same_seq_type(), is_same_symb(), Eigen::test::isApproxAbs(), jacobi(), Eigen::internal::trsmKernelL< Scalar, Index, Mode, Conjugate, TriStorageOrder, OtherInnerStride, Specialized >::kernel(), Eigen::internal::trsmKernelR< Scalar, Index, Mode, Conjugate, TriStorageOrder, OtherInnerStride, Specialized >::kernel(), Eigen::kroneckerProduct(), Matrix3D::ldivide(), lerp(), lerpFrame(), oomph::Refineable_r_mesh< ELEMENT >::linear_spacing(), load(), Eigen::internal::loadQuadToDoublePacket(), Eigen::internal::gebp_traits< LhsScalar_, RhsScalar_, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::loadRhs(), Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::loadRhs(), Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, ConjRhs_, Arch, PacketSize_ >::loadRhs(), Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::loadRhs(), Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::loadRhsQuad(), Eigen::internal::gebp_traits< LhsScalar_, RhsScalar_, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::loadRhsQuad(), Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::loadRhsQuad(), Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, ConjRhs_, Arch, PacketSize_ >::loadRhsQuad(), Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::loadRhsQuad_impl(), oomph::Refineable_r_mesh< ELEMENT >::log_spacing(), Eigen::internal::logical_xor(), oomph::CRComplexMatrix::lubksub(), oomph::CCComplexMatrix::lubksub(), Eigen::internal::LUnumTempV(), Eigen::internal::gebp_traits< LhsScalar_, RhsScalar_, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::madd(), Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::madd(), Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, ConjRhs_, Arch, PacketSize_ >::madd(), Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::madd(), Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::madd_impl(), Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, ConjRhs_, Arch, PacketSize_ >::madd_impl(), main(), InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::make_free_surface_elements(), Eigen::internal::make_packet2d(), Eigen::internal::make_packet2f(), Eigen::internal::make_packet4f(), ElasticRefineableQuarterCircleSectorMesh< ELEMENT >::make_traction_element_mesh(), InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::make_traction_elements(), Eigen::internal::manage_caching_sizes_helper(), oomph::AxisymmetricPoroelasticityEquations::mass_source(), oomph::PoroelasticityEquations< DIM >::mass_source(), oomph::DarcyEquations< DIM >::mass_source(), matlab_cplx_real(), Eigen::internal::matrix_exp_pade13(), Eigen::internal::matrix_exp_pade3(), Eigen::internal::matrix_exp_pade5(), Eigen::internal::matrix_exp_pade7(), Eigen::internal::matrix_exp_pade9(), Eigen::bfloat16_impl::max(), Eigen::half_impl::max(), Vec3D::max(), Eigen::internal::max_size_prefer_dynamic(), measure_clock_speed(), Eigen::AlignedBox< Scalar_, AmbientDim_ >::merged(), MortaringHelpers::MergedSolidMesh::MergedSolidMesh(), Eigen::bfloat16_impl::min(), Eigen::half_impl::min(), Vec3D::min(), Eigen::internal::min_size_prefer_dynamic(), Eigen::internal::min_size_prefer_fixed(), BallPointStuff< Dim >::minimumOnObject(), BallPointStuff< Dim >::minimumOnObjectObject(), BallPointStuff< Dim >::minimumOnObjectVolume(), BallPointStuff< Dim >::minimumOnVolumeObject(), msvc_workaround(), Eigen::internal::muluh(), Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::MvDot(), Anasazi::MultiVecTraits< double, oomph::DoubleMultiVector >::MvTransMv(), MyFluidTetMesh< ELEMENT >::MyFluidTetMesh(), MySolidTetgenMesh< ELEMENT >::MySolidTetgenMesh(), oomph::Mesh::nboundary_element(), oomph::TetMeshBase::nboundary_element_in_region(), oomph::UnstructuredTwoDMeshGeometryBase::nboundary_element_in_region(), oomph::BoundaryNodeBase::ncoordinates_on_boundary(), oomph::BoundaryNode< NODE_TYPE >::ncoordinates_on_boundary(), nlerp(), Eigen::AutoDiffScalar< DerivativeType >::operator!=(), Eigen::bfloat16_impl::operator!=(), Eigen::half_impl::operator!=(), Eigen::internal::bit_and< bool >::operator()(), Eigen::internal::bit_or< bool >::operator()(), Eigen::internal::bit_xor< bool >::operator()(), Eigen::internal::scalar_sum_op< LhsScalar, RhsScalar >::operator()(), Eigen::internal::scalar_product_op< LhsScalar, RhsScalar >::operator()(), Eigen::internal::scalar_conj_product_op< LhsScalar, RhsScalar >::operator()(), Eigen::internal::scalar_min_op< LhsScalar, RhsScalar, NaNPropagation >::operator()(), Eigen::internal::scalar_max_op< LhsScalar, RhsScalar, NaNPropagation >::operator()(), Eigen::internal::scalar_cmp_op< LhsScalar, RhsScalar, cmp_EQ, UseTypedComparators >::operator()(), Eigen::internal::scalar_cmp_op< LhsScalar, RhsScalar, cmp_LT, UseTypedComparators >::operator()(), Eigen::internal::scalar_cmp_op< LhsScalar, RhsScalar, cmp_LE, UseTypedComparators >::operator()(), Eigen::internal::scalar_cmp_op< LhsScalar, RhsScalar, cmp_GT, UseTypedComparators >::operator()(), Eigen::internal::scalar_cmp_op< LhsScalar, RhsScalar, cmp_GE, UseTypedComparators >::operator()(), Eigen::internal::scalar_cmp_op< LhsScalar, RhsScalar, cmp_UNORD, UseTypedComparators >::operator()(), Eigen::internal::scalar_cmp_op< LhsScalar, RhsScalar, cmp_NEQ, UseTypedComparators >::operator()(), Eigen::internal::scalar_difference_op< LhsScalar, RhsScalar >::operator()(), Eigen::internal::scalar_quotient_op< LhsScalar, RhsScalar >::operator()(), Eigen::internal::scalar_absolute_difference_op< LhsScalar, RhsScalar >::operator()(), Eigen::internal::scalar_disjunction_op< DupFunctor, LhsScalar, RhsScalar >::operator()(), Eigen::internal::scalar_pow_op< Scalar, Exponent >::operator()(), MakeComplexOp< Scalar >::operator()(), Eigen::internal::scalar_boolean_and_op< Scalar >::operator()(), Eigen::internal::scalar_boolean_or_op< Scalar >::operator()(), Eigen::internal::scalar_boolean_xor_op< Scalar >::operator()(), Eigen::internal::scalar_bitwise_and_op< Scalar >::operator()(), Eigen::internal::scalar_bitwise_or_op< Scalar >::operator()(), Eigen::internal::scalar_bitwise_xor_op< Scalar >::operator()(), Eigen::internal::scalar_mod2_op< Scalar >::operator()(), Eigen::internal::scalar_fmod_op< Scalar >::operator()(), Eigen::internal::scalar_betainc_op< Scalar >::operator()(), Eigen::internal::bind1st_op< BinaryOp >::operator()(), Eigen::internal::bit_and< T >::operator()(), Eigen::internal::bit_or< T >::operator()(), Eigen::internal::bit_xor< T >::operator()(), Eigen::internal::scalar_boolean_select_op< ThenScalar, ElseScalar, ConditionScalar >::operator()(), Eigen::internal::TripletComp< Iterator, IsColMajor >::operator()(), chwirut2_functor::operator()(), misra1a_functor::operator()(), hahn1_functor::operator()(), misra1d_functor::operator()(), lanczos1_functor::operator()(), rat42_functor::operator()(), MGH10_functor::operator()(), BoxBOD_functor::operator()(), MGH17_functor::operator()(), MGH09_functor::operator()(), Bennett5_functor::operator()(), thurber_functor::operator()(), rat43_functor::operator()(), eckerle4_functor::operator()(), Eigen::internal::gemm_pack_lhs< Scalar, Index, DataMapper, Pack1, Pack2, Packet, RowMajor, Conjugate, PanelMode >::operator()(), oomph::NonLinearElasticitySmoothMesh< ELEMENT >::operator()(), Eigen::symbolic::BaseExpr< Derived_ >::operator*(), Eigen::bfloat16_impl::operator*(), Eigen::Transform< Scalar_, Dim_, Mode_, Options_ >::operator*(), Eigen::half_impl::operator*(), Eigen::internal::Packet1cd::operator*(), Eigen::internal::Packet2cf::operator*(), Eigen::internal::operator*(), Eigen::bfloat16_impl::operator*=(), Eigen::internal::Packet1cd::operator*=(), Eigen::internal::Packet2cf::operator*=(), Eigen::half_impl::operator*=(), Eigen::bfloat16_impl::operator+(), Eigen::half_impl::operator+(), Eigen::operator+(), Eigen::internal::Packet1cd::operator+(), Eigen::internal::Packet2cf::operator+(), Eigen::symbolic::BaseExpr< Derived_ >::operator+(), Eigen::bfloat16_impl::operator+=(), Eigen::internal::Packet1cd::operator+=(), Eigen::internal::Packet2cf::operator+=(), Eigen::half_impl::operator+=(), Eigen::internal::indexed_based_stl_iterator_base< Derived >::operator+=(), Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator+=(), Eigen::internal::pointer_based_stl_iterator< XprType >::operator+=(), Eigen::symbolic::BaseExpr< Derived_ >::operator-(), Eigen::bfloat16_impl::operator-(), Eigen::half_impl::operator-(), Eigen::operator-(), Eigen::internal::Packet1cd::operator-(), Eigen::internal::Packet2cf::operator-(), Eigen::AutoDiffScalar< DerivativeType >::operator-(), operator-(), Eigen::bfloat16_impl::operator-=(), Eigen::internal::Packet1cd::operator-=(), Eigen::internal::Packet2cf::operator-=(), Eigen::half_impl::operator-=(), Eigen::internal::indexed_based_stl_iterator_base< Derived >::operator-=(), Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator-=(), Eigen::internal::pointer_based_stl_iterator< XprType >::operator-=(), Eigen::symbolic::BaseExpr< Derived_ >::operator/(), Eigen::bfloat16_impl::operator/(), Eigen::half_impl::operator/(), Eigen::internal::Packet1cd::operator/(), Eigen::internal::Packet2cf::operator/(), Eigen::bfloat16_impl::operator/=(), Eigen::internal::Packet1cd::operator/=(), Eigen::internal::Packet2cf::operator/=(), Eigen::half_impl::operator/=(), Eigen::AutoDiffScalar< DerivativeType >::operator<(), Eigen::bfloat16_impl::operator<(), Eigen::half_impl::operator<(), operator<<(), Eigen::AutoDiffScalar< DerivativeType >::operator<=(), Eigen::bfloat16_impl::operator<=(), Eigen::half_impl::operator<=(), Eigen::internal::Packet1cd::operator=(), Eigen::internal::Packet2cf::operator=(), Eigen::AutoDiffScalar< DerivativeType >::operator==(), Eigen::bfloat16_impl::operator==(), Eigen::half_impl::operator==(), Eigen::AutoDiffScalar< DerivativeType >::operator>(), Eigen::bfloat16_impl::operator>(), Eigen::half_impl::operator>(), Eigen::AutoDiffScalar< DerivativeType >::operator>=(), Eigen::bfloat16_impl::operator>=(), Eigen::half_impl::operator>=(), NonRefineableBinArray::output_bins(), oomph::DiskLikeGeomObjectWithBoundaries::output_boundaries_and_triads(), oomph::TriangleMesh< ELEMENT >::output_boundary_coordinates(), oomph::TreeBasedRefineableMeshBase::p_adapt_mesh(), Eigen::internal::pabsdiff(), Eigen::internal::pabsdiff< Packet16c >(), Eigen::internal::pabsdiff< Packet16uc >(), Eigen::internal::pabsdiff< Packet2f >(), Eigen::internal::pabsdiff< Packet2i >(), Eigen::internal::pabsdiff< Packet2ui >(), Eigen::internal::pabsdiff< Packet4bf >(), Eigen::internal::pabsdiff< Packet4c >(), Eigen::internal::pabsdiff< Packet4f >(), Eigen::internal::pabsdiff< Packet4i >(), Eigen::internal::pabsdiff< Packet4s >(), Eigen::internal::pabsdiff< Packet4uc >(), Eigen::internal::pabsdiff< Packet4ui >(), Eigen::internal::pabsdiff< Packet4us >(), Eigen::internal::pabsdiff< Packet8c >(), Eigen::internal::pabsdiff< Packet8s >(), Eigen::internal::pabsdiff< Packet8uc >(), Eigen::internal::pabsdiff< Packet8us >(), Eigen::internal::scalar_inner_product_op< Scalar, Scalar, Conj >::packet(), Eigen::internal::Packet2cf::Packet2cf(), Eigen::internal::scalar_sum_op< LhsScalar, RhsScalar >::packetOp(), Eigen::internal::scalar_product_op< LhsScalar, RhsScalar >::packetOp(), Eigen::internal::scalar_conj_product_op< LhsScalar, RhsScalar >::packetOp(), Eigen::internal::scalar_min_op< LhsScalar, RhsScalar, NaNPropagation >::packetOp(), Eigen::internal::scalar_max_op< LhsScalar, RhsScalar, NaNPropagation >::packetOp(), Eigen::internal::scalar_cmp_op< LhsScalar, RhsScalar, cmp_EQ, UseTypedComparators >::packetOp(), Eigen::internal::scalar_cmp_op< LhsScalar, RhsScalar, cmp_LT, UseTypedComparators >::packetOp(), Eigen::internal::scalar_cmp_op< LhsScalar, RhsScalar, cmp_LE, UseTypedComparators >::packetOp(), Eigen::internal::scalar_cmp_op< LhsScalar, RhsScalar, cmp_GT, UseTypedComparators >::packetOp(), Eigen::internal::scalar_cmp_op< LhsScalar, RhsScalar, cmp_GE, UseTypedComparators >::packetOp(), Eigen::internal::scalar_cmp_op< LhsScalar, RhsScalar, cmp_UNORD, UseTypedComparators >::packetOp(), Eigen::internal::scalar_cmp_op< LhsScalar, RhsScalar, cmp_NEQ, UseTypedComparators >::packetOp(), Eigen::internal::scalar_pow_op< Scalar, Exponent >::packetOp(), Eigen::internal::scalar_difference_op< LhsScalar, RhsScalar >::packetOp(), Eigen::internal::scalar_quotient_op< LhsScalar, RhsScalar >::packetOp(), Eigen::internal::scalar_boolean_and_op< Scalar >::packetOp(), Eigen::internal::scalar_boolean_or_op< Scalar >::packetOp(), Eigen::internal::scalar_boolean_xor_op< Scalar >::packetOp(), Eigen::internal::scalar_bitwise_and_op< Scalar >::packetOp(), Eigen::internal::scalar_bitwise_or_op< Scalar >::packetOp(), Eigen::internal::scalar_bitwise_xor_op< Scalar >::packetOp(), Eigen::internal::scalar_absolute_difference_op< LhsScalar, RhsScalar >::packetOp(), Eigen::internal::scalar_boolean_select_op< ThenScalar, ElseScalar, ConditionScalar >::packetOp(), Eigen::internal::bind1st_op< BinaryOp >::packetOp(), Eigen::internal::scalar_betainc_op< Scalar >::packetOp(), Eigen::internal::padd(), padd(), Eigen::internal::padd< Packet16b >(), Eigen::internal::padd< Packet16bf >(), Eigen::internal::padd< Packet16c >(), Eigen::internal::padd< Packet16f >(), Eigen::internal::padd< Packet16h >(), Eigen::internal::padd< Packet16i >(), Eigen::internal::padd< Packet16uc >(), Eigen::internal::padd< Packet1cd >(), Eigen::internal::padd< Packet1cf >(), Eigen::internal::padd< Packet2cd >(), Eigen::internal::padd< Packet2cf >(), Eigen::internal::padd< Packet2d >(), Eigen::internal::padd< Packet2f >(), Eigen::internal::padd< Packet2i >(), Eigen::internal::padd< Packet2l >(), Eigen::internal::padd< Packet2ui >(), Eigen::internal::padd< Packet2ul >(), Eigen::internal::padd< Packet32h >(), Eigen::internal::padd< Packet4bf >(), Eigen::internal::padd< Packet4c >(), Eigen::internal::padd< Packet4cd >(), Eigen::internal::padd< Packet4cf >(), Eigen::internal::padd< Packet4d >(), Eigen::internal::padd< Packet4f >(), Eigen::internal::padd< Packet4i >(), Eigen::internal::padd< Packet4s >(), Eigen::internal::padd< Packet4uc >(), Eigen::internal::padd< Packet4ui >(), Eigen::internal::padd< Packet4us >(), Eigen::internal::padd< Packet8bf >(), Eigen::internal::padd< Packet8c >(), Eigen::internal::padd< Packet8cf >(), Eigen::internal::padd< Packet8d >(), Eigen::internal::padd< Packet8f >(), Eigen::internal::padd< Packet8h >(), Eigen::internal::padd< Packet8i >(), Eigen::internal::padd< Packet8l >(), Eigen::internal::padd< Packet8s >(), Eigen::internal::padd< Packet8uc >(), Eigen::internal::padd< Packet8ui >(), Eigen::internal::padd< Packet8us >(), Eigen::internal::padd< PacketXf >(), Eigen::internal::padd< PacketXi >(), Eigen::internal::padds< Packet2d >(), Eigen::internal::padds< Packet4f >(), Eigen::internal::paddsub(), Eigen::internal::paddsub< Packet2d >(), Eigen::internal::paddsub< Packet2f >(), Eigen::internal::paddsub< Packet4f >(), Eigen::internal::pand(), Eigen::internal::pand< Packet16b >(), Eigen::internal::pand< Packet16c >(), Eigen::internal::pand< Packet16f >(), Eigen::internal::pand< Packet16i >(), Eigen::internal::pand< Packet16uc >(), Eigen::internal::pand< Packet1cd >(), Eigen::internal::pand< Packet1cf >(), Eigen::internal::pand< Packet2cd >(), Eigen::internal::pand< Packet2cf >(), Eigen::internal::pand< Packet2d >(), Eigen::internal::pand< Packet2f >(), Eigen::internal::pand< Packet2i >(), Eigen::internal::pand< Packet2l >(), Eigen::internal::pand< Packet2ui >(), Eigen::internal::pand< Packet2ul >(), Eigen::internal::pand< Packet4c >(), Eigen::internal::pand< Packet4cd >(), Eigen::internal::pand< Packet4cf >(), Eigen::internal::pand< Packet4d >(), Eigen::internal::pand< Packet4f >(), Eigen::internal::pand< Packet4i >(), Eigen::internal::pand< Packet4s >(), Eigen::internal::pand< Packet4uc >(), Eigen::internal::pand< Packet4ui >(), Eigen::internal::pand< Packet4us >(), Eigen::internal::pand< Packet8bf >(), Eigen::internal::pand< Packet8c >(), Eigen::internal::pand< Packet8cf >(), Eigen::internal::pand< Packet8d >(), Eigen::internal::pand< Packet8f >(), Eigen::internal::pand< Packet8i >(), Eigen::internal::pand< Packet8l >(), Eigen::internal::pand< Packet8s >(), Eigen::internal::pand< Packet8uc >(), Eigen::internal::pand< Packet8ui >(), Eigen::internal::pand< Packet8us >(), Eigen::internal::pand< PacketXf >(), Eigen::internal::pand< PacketXi >(), Eigen::internal::pandnot(), Eigen::internal::pandnot< Packet16c >(), Eigen::internal::pandnot< Packet16f >(), Eigen::internal::pandnot< Packet16i >(), Eigen::internal::pandnot< Packet16uc >(), Eigen::internal::pandnot< Packet1cd >(), Eigen::internal::pandnot< Packet1cf >(), Eigen::internal::pandnot< Packet2cd >(), Eigen::internal::pandnot< Packet2cf >(), Eigen::internal::pandnot< Packet2d >(), Eigen::internal::pandnot< Packet2f >(), Eigen::internal::pandnot< Packet2i >(), Eigen::internal::pandnot< Packet2l >(), Eigen::internal::pandnot< Packet2ui >(), Eigen::internal::pandnot< Packet2ul >(), Eigen::internal::pandnot< Packet4c >(), Eigen::internal::pandnot< Packet4cd >(), Eigen::internal::pandnot< Packet4cf >(), Eigen::internal::pandnot< Packet4d >(), Eigen::internal::pandnot< Packet4f >(), Eigen::internal::pandnot< Packet4i >(), Eigen::internal::pandnot< Packet4s >(), Eigen::internal::pandnot< Packet4uc >(), Eigen::internal::pandnot< Packet4ui >(), Eigen::internal::pandnot< Packet4us >(), Eigen::internal::pandnot< Packet8c >(), Eigen::internal::pandnot< Packet8cf >(), Eigen::internal::pandnot< Packet8d >(), Eigen::internal::pandnot< Packet8f >(), Eigen::internal::pandnot< Packet8i >(), Eigen::internal::pandnot< Packet8l >(), Eigen::internal::pandnot< Packet8s >(), Eigen::internal::pandnot< Packet8uc >(), Eigen::internal::pandnot< Packet8ui >(), Eigen::internal::pandnot< Packet8us >(), Eigen::internal::pandnot< PacketXf >(), Eigen::internal::pandnot< PacketXi >(), Eigen::internal::pbetainc(), Eigen::internal::pcast(), Eigen::internal::pcast< Packet2d, Packet16c >(), Eigen::internal::pcast< Packet2d, Packet16uc >(), Eigen::internal::pcast< Packet2d, Packet4f >(), Eigen::internal::pcast< Packet2d, Packet4i >(), Eigen::internal::pcast< Packet2d, Packet4ui >(), Eigen::internal::pcast< Packet2d, Packet8s >(), Eigen::internal::pcast< Packet2d, Packet8us >(), Eigen::internal::pcast< Packet2f, Packet4s >(), Eigen::internal::pcast< Packet2f, Packet4us >(), Eigen::internal::pcast< Packet2f, Packet8c >(), Eigen::internal::pcast< Packet2f, Packet8uc >(), Eigen::internal::pcast< Packet2i, Packet4s >(), Eigen::internal::pcast< Packet2i, Packet4us >(), Eigen::internal::pcast< Packet2i, Packet8c >(), Eigen::internal::pcast< Packet2i, Packet8uc >(), Eigen::internal::pcast< Packet2l, Packet16c >(), Eigen::internal::pcast< Packet2l, Packet16uc >(), Eigen::internal::pcast< Packet2l, Packet4c >(), Eigen::internal::pcast< Packet2l, Packet4f >(), Eigen::internal::pcast< Packet2l, Packet4i >(), Eigen::internal::pcast< Packet2l, Packet4s >(), Eigen::internal::pcast< Packet2l, Packet4uc >(), Eigen::internal::pcast< Packet2l, Packet4ui >(), Eigen::internal::pcast< Packet2l, Packet4us >(), Eigen::internal::pcast< Packet2l, Packet8c >(), Eigen::internal::pcast< Packet2l, Packet8s >(), Eigen::internal::pcast< Packet2l, Packet8uc >(), Eigen::internal::pcast< Packet2l, Packet8us >(), Eigen::internal::pcast< Packet2ui, Packet4s >(), Eigen::internal::pcast< Packet2ui, Packet4us >(), Eigen::internal::pcast< Packet2ui, Packet8c >(), Eigen::internal::pcast< Packet2ui, Packet8uc >(), Eigen::internal::pcast< Packet2ul, Packet16c >(), Eigen::internal::pcast< Packet2ul, Packet16uc >(), Eigen::internal::pcast< Packet2ul, Packet4c >(), Eigen::internal::pcast< Packet2ul, Packet4f >(), Eigen::internal::pcast< Packet2ul, Packet4i >(), Eigen::internal::pcast< Packet2ul, Packet4s >(), Eigen::internal::pcast< Packet2ul, Packet4uc >(), Eigen::internal::pcast< Packet2ul, Packet4ui >(), Eigen::internal::pcast< Packet2ul, Packet4us >(), Eigen::internal::pcast< Packet2ul, Packet8c >(), Eigen::internal::pcast< Packet2ul, Packet8s >(), Eigen::internal::pcast< Packet2ul, Packet8uc >(), Eigen::internal::pcast< Packet2ul, Packet8us >(), Eigen::internal::pcast< Packet4d, Packet8f >(), Eigen::internal::pcast< Packet4d, Packet8i >(), Eigen::internal::pcast< Packet4f, Packet16b >(), Eigen::internal::pcast< Packet4f, Packet16c >(), Eigen::internal::pcast< Packet4f, Packet16uc >(), Eigen::internal::pcast< Packet4f, Packet8bf >(), Eigen::internal::pcast< Packet4f, Packet8c >(), Eigen::internal::pcast< Packet4f, Packet8s >(), Eigen::internal::pcast< Packet4f, Packet8uc >(), Eigen::internal::pcast< Packet4f, Packet8us >(), Eigen::internal::pcast< Packet4i, Packet16c >(), Eigen::internal::pcast< Packet4i, Packet16uc >(), Eigen::internal::pcast< Packet4i, Packet8c >(), Eigen::internal::pcast< Packet4i, Packet8s >(), Eigen::internal::pcast< Packet4i, Packet8uc >(), Eigen::internal::pcast< Packet4i, Packet8us >(), Eigen::internal::pcast< Packet4s, Packet8c >(), Eigen::internal::pcast< Packet4s, Packet8uc >(), Eigen::internal::pcast< Packet4ui, Packet16c >(), Eigen::internal::pcast< Packet4ui, Packet16uc >(), Eigen::internal::pcast< Packet4ui, Packet8c >(), Eigen::internal::pcast< Packet4ui, Packet8s >(), Eigen::internal::pcast< Packet4ui, Packet8uc >(), Eigen::internal::pcast< Packet4ui, Packet8us >(), Eigen::internal::pcast< Packet4us, Packet8c >(), Eigen::internal::pcast< Packet4us, Packet8uc >(), Eigen::internal::pcast< Packet8d, Packet16f >(), Eigen::internal::pcast< Packet8d, Packet16i >(), Eigen::internal::pcast< Packet8f, Packet16b >(), Eigen::internal::pcast< Packet8s, Packet16c >(), Eigen::internal::pcast< Packet8s, Packet16uc >(), Eigen::internal::pcast< Packet8us, Packet16c >(), Eigen::internal::pcast< Packet8us, Packet16uc >(), Eigen::internal::pcmp_eq(), Eigen::internal::pcmp_eq< Packet16c >(), Eigen::internal::pcmp_eq< Packet16uc >(), Eigen::internal::pcmp_eq< Packet2d >(), Eigen::internal::pcmp_eq< Packet2f >(), Eigen::internal::pcmp_eq< Packet2i >(), Eigen::internal::pcmp_eq< Packet2l >(), Eigen::internal::pcmp_eq< Packet2ui >(), Eigen::internal::pcmp_eq< Packet2ul >(), Eigen::internal::pcmp_eq< Packet4bf >(), Eigen::internal::pcmp_eq< Packet4c >(), Eigen::internal::pcmp_eq< Packet4f >(), Eigen::internal::pcmp_eq< Packet4i >(), Eigen::internal::pcmp_eq< Packet4s >(), Eigen::internal::pcmp_eq< Packet4uc >(), Eigen::internal::pcmp_eq< Packet4ui >(), Eigen::internal::pcmp_eq< Packet4us >(), Eigen::internal::pcmp_eq< Packet8c >(), Eigen::internal::pcmp_eq< Packet8s >(), Eigen::internal::pcmp_eq< Packet8uc >(), Eigen::internal::pcmp_eq< Packet8us >(), Eigen::internal::pcmp_eq< PacketXf >(), Eigen::internal::pcmp_eq< PacketXi >(), Eigen::internal::pcmp_le(), Eigen::internal::pcmp_le< Packet16c >(), Eigen::internal::pcmp_le< Packet16uc >(), Eigen::internal::pcmp_le< Packet2d >(), Eigen::internal::pcmp_le< Packet2f >(), Eigen::internal::pcmp_le< Packet2i >(), Eigen::internal::pcmp_le< Packet2l >(), Eigen::internal::pcmp_le< Packet2ui >(), Eigen::internal::pcmp_le< Packet2ul >(), Eigen::internal::pcmp_le< Packet4bf >(), Eigen::internal::pcmp_le< Packet4c >(), Eigen::internal::pcmp_le< Packet4f >(), Eigen::internal::pcmp_le< Packet4i >(), Eigen::internal::pcmp_le< Packet4s >(), Eigen::internal::pcmp_le< Packet4uc >(), Eigen::internal::pcmp_le< Packet4ui >(), Eigen::internal::pcmp_le< Packet4us >(), Eigen::internal::pcmp_le< Packet8c >(), Eigen::internal::pcmp_le< Packet8s >(), Eigen::internal::pcmp_le< Packet8uc >(), Eigen::internal::pcmp_le< Packet8us >(), Eigen::internal::pcmp_le< PacketXf >(), Eigen::internal::pcmp_le< PacketXi >(), Eigen::internal::pcmp_lt(), Eigen::internal::pcmp_lt< Packet16c >(), Eigen::internal::pcmp_lt< Packet16uc >(), Eigen::internal::pcmp_lt< Packet2d >(), Eigen::internal::pcmp_lt< Packet2f >(), Eigen::internal::pcmp_lt< Packet2i >(), Eigen::internal::pcmp_lt< Packet2l >(), Eigen::internal::pcmp_lt< Packet2ui >(), Eigen::internal::pcmp_lt< Packet2ul >(), Eigen::internal::pcmp_lt< Packet4bf >(), Eigen::internal::pcmp_lt< Packet4c >(), Eigen::internal::pcmp_lt< Packet4f >(), Eigen::internal::pcmp_lt< Packet4i >(), Eigen::internal::pcmp_lt< Packet4s >(), Eigen::internal::pcmp_lt< Packet4uc >(), Eigen::internal::pcmp_lt< Packet4ui >(), Eigen::internal::pcmp_lt< Packet4us >(), Eigen::internal::pcmp_lt< Packet8c >(), Eigen::internal::pcmp_lt< Packet8s >(), Eigen::internal::pcmp_lt< Packet8uc >(), Eigen::internal::pcmp_lt< Packet8us >(), Eigen::internal::pcmp_lt< PacketXf >(), Eigen::internal::pcmp_lt< PacketXi >(), Eigen::internal::pcmp_lt_or_nan(), Eigen::internal::pcmp_lt_or_nan< Packet2d >(), Eigen::internal::pcmp_lt_or_nan< Packet2f >(), Eigen::internal::pcmp_lt_or_nan< Packet4bf >(), Eigen::internal::pcmp_lt_or_nan< Packet4f >(), Eigen::internal::pcmp_lt_or_nan< PacketXf >(), Eigen::internal::pconj(), HGridOptimiser::pdfIntCell(), Eigen::internal::pdiv(), Eigen::internal::pdiv< Packet16bf >(), Eigen::internal::pdiv< Packet16f >(), Eigen::internal::pdiv< Packet16h >(), Eigen::internal::pdiv< Packet16i >(), Eigen::internal::pdiv< Packet16uc >(), Eigen::internal::pdiv< Packet1cd >(), Eigen::internal::pdiv< Packet1cf >(), Eigen::internal::pdiv< Packet2cd >(), Eigen::internal::pdiv< Packet2cf >(), Eigen::internal::pdiv< Packet2d >(), Eigen::internal::pdiv< Packet2f >(), Eigen::internal::pdiv< Packet2l >(), Eigen::internal::pdiv< Packet2ul >(), Eigen::internal::pdiv< Packet32h >(), Eigen::internal::pdiv< Packet4bf >(), Eigen::internal::pdiv< Packet4cd >(), Eigen::internal::pdiv< Packet4cf >(), Eigen::internal::pdiv< Packet4d >(), Eigen::internal::pdiv< Packet4f >(), Eigen::internal::pdiv< Packet4i >(), Eigen::internal::pdiv< Packet4ui >(), Eigen::internal::pdiv< Packet8bf >(), Eigen::internal::pdiv< Packet8cf >(), Eigen::internal::pdiv< Packet8d >(), Eigen::internal::pdiv< Packet8f >(), Eigen::internal::pdiv< Packet8h >(), Eigen::internal::pdiv< Packet8i >(), Eigen::internal::pdiv< Packet8s >(), Eigen::internal::pdiv< Packet8us >(), Eigen::internal::pdiv< PacketXf >(), Eigen::internal::pdiv< PacketXi >(), Eigen::internal::pdiv_float_common(), PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::PerturbedStateProblem(), Eigen::internal::pexp< Packet2cf >(), Eigen::internal::pgerMMA(), SolidProblem< ELEMENT_TYPE >::pinBoundaries(), SolidProblem< ELEMENT_TYPE >::pinBoundary(), Eigen::internal::plain_enum_max(), Eigen::internal::plain_enum_min(), Eigen::internal::pldexp< Packet4d >(), Eigen::internal::pldexp< Packet8d >(), Eigen::internal::pldexp_generic(), Eigen::internal::ploaddup< Packet16bf >(), Eigen::internal::ploaddup< Packet16h >(), Eigen::internal::ploaddup< Packet4cf >(), Eigen::internal::ploaddup< Packet8h >(), Eigen::internal::ploadquad(), Eigen::internal::ploadquad< Packet8h >(), Eigen::internal::plog< Packet1cd >(), Eigen::internal::plog< Packet2cf >(), Eigen::internal::pmadd(), Eigen::internal::pmadd< Packet1cd >(), Eigen::internal::pmadd< Packet2cf >(), pmadd_complex_complex(), pmadd_complex_real(), Eigen::internal::pmax(), Eigen::internal::pmax< Packet16bf >(), Eigen::internal::pmax< Packet16c >(), Eigen::internal::pmax< Packet16f >(), Eigen::internal::pmax< Packet16h >(), Eigen::internal::pmax< Packet16i >(), Eigen::internal::pmax< Packet16uc >(), Eigen::internal::pmax< Packet2d >(), Eigen::internal::pmax< Packet2f >(), Eigen::internal::pmax< Packet2i >(), Eigen::internal::pmax< Packet2l >(), Eigen::internal::pmax< Packet2ui >(), Eigen::internal::pmax< Packet2ul >(), Eigen::internal::pmax< Packet32h >(), Eigen::internal::pmax< Packet4bf >(), Eigen::internal::pmax< Packet4c >(), Eigen::internal::pmax< Packet4d >(), Eigen::internal::pmax< Packet4f >(), Eigen::internal::pmax< Packet4i >(), Eigen::internal::pmax< Packet4s >(), Eigen::internal::pmax< Packet4uc >(), Eigen::internal::pmax< Packet4ui >(), Eigen::internal::pmax< Packet4us >(), Eigen::internal::pmax< Packet8bf >(), Eigen::internal::pmax< Packet8c >(), Eigen::internal::pmax< Packet8d >(), Eigen::internal::pmax< Packet8f >(), Eigen::internal::pmax< Packet8h >(), Eigen::internal::pmax< Packet8i >(), Eigen::internal::pmax< Packet8l >(), Eigen::internal::pmax< Packet8s >(), Eigen::internal::pmax< Packet8uc >(), Eigen::internal::pmax< Packet8ui >(), Eigen::internal::pmax< Packet8us >(), Eigen::internal::pmax< PacketXf >(), Eigen::internal::pmax< PacketXi >(), Eigen::internal::pmax< PropagateNaN, Packet16f >(), Eigen::internal::pmax< PropagateNaN, Packet2d >(), Eigen::internal::pmax< PropagateNaN, Packet2f >(), Eigen::internal::pmax< PropagateNaN, Packet4bf >(), Eigen::internal::pmax< PropagateNaN, Packet4d >(), Eigen::internal::pmax< PropagateNaN, Packet4f >(), Eigen::internal::pmax< PropagateNaN, Packet8d >(), Eigen::internal::pmax< PropagateNaN, Packet8f >(), Eigen::internal::pmax< PropagateNaN, PacketXf >(), Eigen::internal::pmax< PropagateNumbers, Packet16f >(), Eigen::internal::pmax< PropagateNumbers, Packet2d >(), Eigen::internal::pmax< PropagateNumbers, Packet4bf >(), Eigen::internal::pmax< PropagateNumbers, Packet4d >(), Eigen::internal::pmax< PropagateNumbers, Packet4f >(), Eigen::internal::pmax< PropagateNumbers, Packet8d >(), Eigen::internal::pmax< PropagateNumbers, Packet8f >(), Eigen::internal::pmax< PropagateNumbers, PacketXf >(), Eigen::internal::pmin(), Eigen::internal::pmin< Packet16bf >(), Eigen::internal::pmin< Packet16c >(), Eigen::internal::pmin< Packet16f >(), Eigen::internal::pmin< Packet16h >(), Eigen::internal::pmin< Packet16i >(), Eigen::internal::pmin< Packet16uc >(), Eigen::internal::pmin< Packet2d >(), Eigen::internal::pmin< Packet2f >(), Eigen::internal::pmin< Packet2i >(), Eigen::internal::pmin< Packet2l >(), Eigen::internal::pmin< Packet2ui >(), Eigen::internal::pmin< Packet2ul >(), Eigen::internal::pmin< Packet32h >(), Eigen::internal::pmin< Packet4bf >(), Eigen::internal::pmin< Packet4c >(), Eigen::internal::pmin< Packet4d >(), Eigen::internal::pmin< Packet4f >(), Eigen::internal::pmin< Packet4i >(), Eigen::internal::pmin< Packet4s >(), Eigen::internal::pmin< Packet4uc >(), Eigen::internal::pmin< Packet4ui >(), Eigen::internal::pmin< Packet4us >(), Eigen::internal::pmin< Packet8bf >(), Eigen::internal::pmin< Packet8c >(), Eigen::internal::pmin< Packet8d >(), Eigen::internal::pmin< Packet8f >(), Eigen::internal::pmin< Packet8h >(), Eigen::internal::pmin< Packet8i >(), Eigen::internal::pmin< Packet8l >(), Eigen::internal::pmin< Packet8s >(), Eigen::internal::pmin< Packet8uc >(), Eigen::internal::pmin< Packet8ui >(), Eigen::internal::pmin< Packet8us >(), Eigen::internal::pmin< PacketXf >(), Eigen::internal::pmin< PacketXi >(), Eigen::internal::pmin< PropagateNaN, Packet16f >(), Eigen::internal::pmin< PropagateNaN, Packet2d >(), Eigen::internal::pmin< PropagateNaN, Packet2f >(), Eigen::internal::pmin< PropagateNaN, Packet4bf >(), Eigen::internal::pmin< PropagateNaN, Packet4d >(), Eigen::internal::pmin< PropagateNaN, Packet4f >(), Eigen::internal::pmin< PropagateNaN, Packet8d >(), Eigen::internal::pmin< PropagateNaN, Packet8f >(), Eigen::internal::pmin< PropagateNaN, PacketXf >(), Eigen::internal::pmin< PropagateNumbers, Packet16f >(), Eigen::internal::pmin< PropagateNumbers, Packet2d >(), Eigen::internal::pmin< PropagateNumbers, Packet4bf >(), Eigen::internal::pmin< PropagateNumbers, Packet4d >(), Eigen::internal::pmin< PropagateNumbers, Packet4f >(), Eigen::internal::pmin< PropagateNumbers, Packet8d >(), Eigen::internal::pmin< PropagateNumbers, Packet8f >(), Eigen::internal::pmin< PropagateNumbers, PacketXf >(), Eigen::internal::pminmax_propagate_nan(), Eigen::internal::pminmax_propagate_numbers(), Eigen::internal::pmsub(), Eigen::internal::Packet2cf::pmul(), Eigen::internal::pmul(), Eigen::internal::pmul< Packet16b >(), Eigen::internal::pmul< Packet16bf >(), Eigen::internal::pmul< Packet16c >(), Eigen::internal::pmul< Packet16f >(), Eigen::internal::pmul< Packet16h >(), Eigen::internal::pmul< Packet16i >(), Eigen::internal::pmul< Packet16uc >(), Eigen::internal::pmul< Packet1cd >(), Eigen::internal::pmul< Packet1cf >(), Eigen::internal::pmul< Packet2cf >(), Eigen::internal::pmul< Packet2d >(), Eigen::internal::pmul< Packet2f >(), Eigen::internal::pmul< Packet2i >(), Eigen::internal::pmul< Packet2l >(), Eigen::internal::pmul< Packet2ui >(), Eigen::internal::pmul< Packet2ul >(), Eigen::internal::pmul< Packet32h >(), Eigen::internal::pmul< Packet4bf >(), Eigen::internal::pmul< Packet4c >(), Eigen::internal::pmul< Packet4cd >(), Eigen::internal::pmul< Packet4d >(), Eigen::internal::pmul< Packet4f >(), Eigen::internal::pmul< Packet4i >(), Eigen::internal::pmul< Packet4s >(), Eigen::internal::pmul< Packet4uc >(), Eigen::internal::pmul< Packet4ui >(), Eigen::internal::pmul< Packet4us >(), Eigen::internal::pmul< Packet8bf >(), Eigen::internal::pmul< Packet8c >(), Eigen::internal::pmul< Packet8cf >(), Eigen::internal::pmul< Packet8d >(), Eigen::internal::pmul< Packet8f >(), Eigen::internal::pmul< Packet8h >(), Eigen::internal::pmul< Packet8i >(), Eigen::internal::pmul< Packet8l >(), Eigen::internal::pmul< Packet8s >(), Eigen::internal::pmul< Packet8uc >(), Eigen::internal::pmul< Packet8ui >(), Eigen::internal::pmul< Packet8us >(), Eigen::internal::pmul< PacketXf >(), Eigen::internal::pmul< PacketXi >(), Eigen::internal::pnmadd(), Eigen::internal::pnmsub(), Eigen::internal::por(), Eigen::internal::por< Packet16b >(), Eigen::internal::por< Packet16c >(), Eigen::internal::por< Packet16f >(), Eigen::internal::por< Packet16i >(), Eigen::internal::por< Packet16uc >(), Eigen::internal::por< Packet1cd >(), Eigen::internal::por< Packet1cf >(), Eigen::internal::por< Packet2cd >(), Eigen::internal::por< Packet2cf >(), Eigen::internal::por< Packet2d >(), Eigen::internal::por< Packet2f >(), Eigen::internal::por< Packet2i >(), Eigen::internal::por< Packet2l >(), Eigen::internal::por< Packet2ui >(), Eigen::internal::por< Packet2ul >(), Eigen::internal::por< Packet4c >(), Eigen::internal::por< Packet4cd >(), Eigen::internal::por< Packet4cf >(), Eigen::internal::por< Packet4d >(), Eigen::internal::por< Packet4f >(), Eigen::internal::por< Packet4i >(), Eigen::internal::por< Packet4s >(), Eigen::internal::por< Packet4uc >(), Eigen::internal::por< Packet4ui >(), Eigen::internal::por< Packet4us >(), Eigen::internal::por< Packet8bf >(), Eigen::internal::por< Packet8c >(), Eigen::internal::por< Packet8cf >(), Eigen::internal::por< Packet8d >(), Eigen::internal::por< Packet8f >(), Eigen::internal::por< Packet8i >(), Eigen::internal::por< Packet8l >(), Eigen::internal::por< Packet8s >(), Eigen::internal::por< Packet8uc >(), Eigen::internal::por< Packet8ui >(), Eigen::internal::por< Packet8us >(), Eigen::internal::por< PacketXf >(), Eigen::internal::por< PacketXi >(), oomph::DiskLikeGeomObjectWithBoundaries::position_on_boundary(), Eigen::bfloat16_impl::pow(), Eigen::half_impl::pow(), oomph::LagrangeEnforcedFlowPreconditioner::preconditioner_solve(), Eigen::internal::predux< Packet2cf >(), Eigen::internal::predux< Packet4f >(), Eigen::internal::predux< Packet4i >(), predux_complex(), Eigen::internal::predux_mul< Packet2cf >(), predux_real(), PrescribedBoundaryDisplacementProblem< ELEMENT >::PrescribedBoundaryDisplacementProblem(), PressureWaveFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::PressureWaveFSIProblem(), print_size(), LiquidMigrationMPI2Test::printTime(), Eigen::TensorEvaluator< const TensorFFTOp< FFT, ArgType, FFTResultType, FFTDir >, Device >::processDataLineBluestein(), prod(), product_large_regressions(), propagate_nan_max(), propagate_nan_min(), propagate_number_max(), propagate_number_min(), Eigen::internal::pselect(), Eigen::internal::pselect< bool >(), Eigen::internal::pselect< Packet4d >(), Eigen::internal::pselect< Packet8f >(), Eigen::internal::pselect< Packet8i >(), Eigen::internal::pselect< Packet8ui >(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::PseudoElasticCollapsibleChannelProblem(), PseudoSolidCapProblem< ELEMENT >::PseudoSolidCapProblem(), Eigen::internal::psub(), Eigen::internal::psub< Packet16b >(), Eigen::internal::psub< Packet16bf >(), Eigen::internal::psub< Packet16c >(), Eigen::internal::psub< Packet16f >(), Eigen::internal::psub< Packet16h >(), Eigen::internal::psub< Packet16i >(), Eigen::internal::psub< Packet16uc >(), Eigen::internal::psub< Packet1cd >(), Eigen::internal::psub< Packet1cf >(), Eigen::internal::psub< Packet2cd >(), Eigen::internal::psub< Packet2cf >(), Eigen::internal::psub< Packet2d >(), Eigen::internal::psub< Packet2f >(), Eigen::internal::psub< Packet2i >(), Eigen::internal::psub< Packet2l >(), Eigen::internal::psub< Packet2ui >(), Eigen::internal::psub< Packet2ul >(), Eigen::internal::psub< Packet32h >(), Eigen::internal::psub< Packet4bf >(), Eigen::internal::psub< Packet4c >(), Eigen::internal::psub< Packet4cd >(), Eigen::internal::psub< Packet4cf >(), Eigen::internal::psub< Packet4d >(), Eigen::internal::psub< Packet4f >(), Eigen::internal::psub< Packet4i >(), Eigen::internal::psub< Packet4s >(), Eigen::internal::psub< Packet4uc >(), Eigen::internal::psub< Packet4ui >(), Eigen::internal::psub< Packet4us >(), Eigen::internal::psub< Packet8bf >(), Eigen::internal::psub< Packet8c >(), Eigen::internal::psub< Packet8cf >(), Eigen::internal::psub< Packet8d >(), Eigen::internal::psub< Packet8f >(), Eigen::internal::psub< Packet8h >(), Eigen::internal::psub< Packet8i >(), Eigen::internal::psub< Packet8l >(), Eigen::internal::psub< Packet8s >(), Eigen::internal::psub< Packet8uc >(), Eigen::internal::psub< Packet8ui >(), Eigen::internal::psub< Packet8us >(), Eigen::internal::psub< PacketXf >(), Eigen::internal::psub< PacketXi >(), Eigen::internal::ptranspose(), Eigen::internal::ptrue< Packet2d >(), Eigen::internal::ptrue< Packet4d >(), Eigen::internal::ptrue< Packet4f >(), Eigen::internal::ptrue< Packet8f >(), Eigen::internal::ptrue< Packet8i >(), Eigen::internal::pxor(), Eigen::internal::pxor< Packet16b >(), Eigen::internal::pxor< Packet16c >(), Eigen::internal::pxor< Packet16f >(), Eigen::internal::pxor< Packet16i >(), Eigen::internal::pxor< Packet16uc >(), Eigen::internal::pxor< Packet1cd >(), Eigen::internal::pxor< Packet1cf >(), Eigen::internal::pxor< Packet2cd >(), Eigen::internal::pxor< Packet2cf >(), Eigen::internal::pxor< Packet2d >(), Eigen::internal::pxor< Packet2f >(), Eigen::internal::pxor< Packet2i >(), Eigen::internal::pxor< Packet2l >(), Eigen::internal::pxor< Packet2ui >(), Eigen::internal::pxor< Packet2ul >(), Eigen::internal::pxor< Packet4c >(), Eigen::internal::pxor< Packet4cd >(), Eigen::internal::pxor< Packet4cf >(), Eigen::internal::pxor< Packet4d >(), Eigen::internal::pxor< Packet4f >(), Eigen::internal::pxor< Packet4i >(), Eigen::internal::pxor< Packet4s >(), Eigen::internal::pxor< Packet4uc >(), Eigen::internal::pxor< Packet4ui >(), Eigen::internal::pxor< Packet4us >(), Eigen::internal::pxor< Packet8bf >(), Eigen::internal::pxor< Packet8c >(), Eigen::internal::pxor< Packet8cf >(), Eigen::internal::pxor< Packet8d >(), Eigen::internal::pxor< Packet8f >(), Eigen::internal::pxor< Packet8i >(), Eigen::internal::pxor< Packet8l >(), Eigen::internal::pxor< Packet8s >(), Eigen::internal::pxor< Packet8uc >(), Eigen::internal::pxor< Packet8ui >(), Eigen::internal::pxor< Packet8us >(), Eigen::internal::pxor< PacketXf >(), Eigen::internal::pxor< PacketXi >(), QFaceTestProblem< ELEMENT >::QFaceTestProblem(), oomph::QuarterPipeMesh< ELEMENT >::QuarterPipeMesh(), quaternion(), quatmul_default(), quatmul_novec(), REF_ABS_DIFF(), REF_ADD(), REF_DIV(), REF_MADD(), REF_MSUB(), REF_MUL(), REF_NMADD(), REF_NMSUB(), REF_SUB(), RefineableAdvectionDiffusionPipeProblem< ELEMENT >::RefineableAdvectionDiffusionPipeProblem(), RefineableElasticCubicMesh< ELEMENT >::RefineableElasticCubicMesh(), oomph::RefineableQuadMeshWithMovingCylinder< ELEMENT >::RefineableQuadMeshWithMovingCylinder(), oomph::RefineableSolidCubicMesh< ELEMENT >::RefineableSolidCubicMesh(), oomph::RefineableTetgenMesh< ELEMENT >::RefineableTetgenMesh(), RefineableTwoMeshFluxPoissonProblem< ELEMENT >::RefineableTwoMeshFluxPoissonProblem(), RefineableUnsteadyHeatProblem< ELEMENT >::RefineableUnsteadyHeatProblem(), RefineableYoungLaplaceProblem< ELEMENT >::RefineableYoungLaplaceProblem(), ElasticRefineableQuarterCircleSectorMesh< ELEMENT >::remake_traction_element_mesh(), oomph::Mesh::remove_boundary_node(), oomph::Mesh::remove_boundary_nodes(), oomph::BoundaryNodeBase::remove_from_boundary(), oomph::BoundaryNode< NODE_TYPE >::remove_from_boundary(), oomph::DoubleMatrixBase::residual(), oomph::AugmentedBlockFoldLinearSolver::resolve(), oomph::AugmentedBlockPitchForkLinearSolver::resolve(), oomph::HSL_MA42::resolve(), oomph::BlockPreconditioner< MATRIX >::return_block_ordered_preconditioner_vector(), oomph::BlockPreconditioner< MATRIX >::return_block_vector(), oomph::BlockPreconditioner< MATRIX >::return_block_vectors(), Quaternion::rotateInverseInertiaTensor(), RotatingCylinderProblem< ELEMENT, TIMESTEPPER >::RotatingCylinderProblem(), rotg(), Eigen::internal::pardiso_run_selector< IndexType >::run(), Eigen::internal::pardiso_run_selector< long long int >::run(), Eigen::internal::not_equal_op::run(), Eigen::internal::logical_and_op::run(), Eigen::internal::product_op::run(), Eigen::internal::greater_op::run(), Eigen::internal::greater_equal_op::run(), Eigen::internal::sum_op::run(), Eigen::internal::lesser_op::run(), Eigen::internal::lesser_equal_op::run(), Eigen::internal::equal_op::run(), Eigen::internal::logical_or_op::run(), Eigen::internal::solve_assertion< Derived >::run(), Eigen::internal::default_inner_product_impl< Lhs, Rhs, Conj >::run(), Eigen::internal::ptrue_impl< Packet, EnableIf >::run(), Eigen::internal::pzero_impl< Packet, EnableIf >::run(), Eigen::internal::pminmax_impl< NaNPropagation >::run(), Eigen::internal::pminmax_impl< PropagateNaN >::run(), Eigen::internal::pminmax_impl< PropagateNumbers >::run(), Eigen::internal::pselect_impl< Packet, EnableIf >::run(), Eigen::internal::pselect_impl< Packet, std::enable_if_t< is_scalar< Packet >::value > >::run(), Eigen::internal::quat_product< Architecture::Target, Derived, OtherDerived, float >::run(), Eigen::internal::quat_product< Arch, Derived1, Derived2, Scalar >::run(), Eigen::internal::solve_assertion< CwiseUnaryOp< Eigen::internal::scalar_conjugate_op< Scalar >, const Transpose< Derived > > >::run(), Eigen::internal::solve_assertion< Transpose< Derived > >::run(), Eigen::internal::cross3_impl< Architecture::Target, VectorLhs, VectorRhs, float, true >::run(), Eigen::internal::matrix_swap_impl< MatrixTypeA, MatrixTypeB, SwapPointers >::run(), Eigen::internal::matrix_swap_impl< MatrixTypeA, MatrixTypeB, true >::run(), Eigen::internal::bitwise_binary_impl< Scalar, IsComplex >::run_and(), Eigen::internal::bitwise_binary_impl< Scalar, true >::run_and(), run_navier_stokes_outflow(), Eigen::internal::bitwise_binary_impl< Scalar, IsComplex >::run_or(), Eigen::internal::bitwise_binary_impl< Scalar, true >::run_or(), run_prescribed_flux(), run_prescribed_pressure_gradient(), Eigen::internal::bitwise_binary_impl< Scalar, IsComplex >::run_xor(), Eigen::internal::bitwise_binary_impl< Scalar, true >::run_xor(), rvalue_move(), Eigen::internal::rwupdt(), SelectSolvers(), selfadjointeigensolver(), oomph::Ellipse::set_B_ellips(), BaseStateProblem< BASE_ELEMENT >::set_boundary_conditions(), PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::set_boundary_conditions(), RotatingCylinderProblem< ELEMENT, TIMESTEPPER >::set_boundary_conditions(), InterfaceProblem< ELEMENT, TIMESTEPPER >::set_boundary_conditions(), FlowAroundCylinderProblem< ELEMENT >::set_boundary_conditions(), UnstructuredTorusProblem< ELEMENT >::set_boundary_conditions(), oomph::FaceElement::set_boundary_number_in_bulk_mesh(), oomph::FreeStandingFaceElement< ELEMENT >::set_boundary_number_in_bulk_mesh(), oomph::BoundaryNodeBase::set_coordinates_on_boundary(), oomph::Node::set_coordinates_on_boundary(), oomph::BoundaryNode< NODE_TYPE >::set_coordinates_on_boundary(), oomph::BiharmonicProblem< DIM >::set_dirichlet_boundary_condition(), RefineableAdvectionDiffusionPipeProblem< ELEMENT >::set_inlet_concentration(), oomph::BiharmonicProblem< DIM >::set_neumann_boundary_condition(), CollapsibleChannelProblem< ELEMENT >::set_parallel_outflow(), CollapsibleChannelProblem< ELEMENT >::set_poiseuille_outflow(), oomph::HermiteQuadMesh< ELEMENT >::set_position_of_boundary_node(), SolidProblem< ELEMENT_TYPE >::setBodyForceAsGravity(), Eigen::QuaternionBase< Derived >::setFromTwoVectors(), SolidBag::setSuctionAsBodyForce(), SimpleShearProblem< ELEMENT >::setup_boundary_conditions(), oomph::TetMeshBase::setup_boundary_coordinates(), oomph::UnstructuredTwoDMeshGeometryBase::setup_boundary_coordinates(), oomph::XdaTetMesh< ELEMENT >::setup_boundary_coordinates(), oomph::LineMeshBase::setup_boundary_element_info(), CollapsibleChannelProblem< ELEMENT >::setup_inflow_traction_elements(), oomph::BlockPreconditioner< MATRIX >::setup_matrix_vector_product(), CollapsibleChannelProblem< ELEMENT >::setup_outflow_flux_control_elements(), CollapsibleChannelProblem< ELEMENT >::setup_outflow_impedance_elements(), oomph::TetgenMesh< ELEMENT >::setup_reverse_lookup_schemes_for_faceted_surface(), oomph::StefanBoltzmannHelper::setup_stefan_boltzmann_visibility(), ChutePeriodic::setupInitialConditions(), InsertionBoundaryMPI2Test::setupInitialConditions(), MaserRepeatedOutInMPI2Test::setupInitialConditions(), CubicCell::setupInitialConditions(), MinimalExampleDrum::setupInitialConditions(), Drum::setupInitialConditions(), Penetration::setupInitialConditions(), Silo::setupInitialConditions(), CubeDeletionBoundarySelfTest::setupInitialConditions(), DeletionBoundarySelfTest::setupInitialConditions(), TriangulatedScrewSelfTest::setupInitialConditions(), Packing::setupInitialConditions(), CoupledBeam::setupOomph(), SheetGlueProblem< ELEMENT >::SheetGlueProblem(), Eigen::internal::shuffle(), Eigen::internal::shuffle2(), Eigen::internal::shuffle2< true >(), SimpleShearProblem< ELEMENT >::SimpleShearProblem(), slerp_eigen(), slerp_gael(), slerp_legacy(), slerp_legacy_nlerp(), slerp_rw(), oomph::RefineableTetgenMesh< ELEMENT >::snap_nodes_onto_boundary(), oomph::TetMeshBase::snap_nodes_onto_geometric_objects(), oomph::UnstructuredTwoDMeshGeometryBase::snap_nodes_onto_geometric_objects(), RisingBubbleProblem< ELEMENT >::snap_onto_sphere(), oomph::TetMeshBase::snap_to_quadratic_surface(), ProblemParameters::Solid_body_force(), oomph::AxisymmetricPoroelasticityEquations::solid_body_force(), SolidFreeSurfaceRotationProblem< ELEMENT >::SolidFreeSurfaceRotationProblem(), oomph::SolidTetgenMesh< ELEMENT >::SolidTetgenMesh(), Eigen::SolverBase< Derived >::solve(), Eigen::DiagonalPreconditioner< Scalar_ >::solve(), Eigen::SparseSolverBase< Derived >::solve(), Eigen::IdentityPreconditioner::solve(), oomph::AugmentedBlockFoldLinearSolver::solve(), oomph::AugmentedBlockPitchForkLinearSolver::solve(), SmallMatrix< numberOfRows, numberOfColumns >::solve(), oomph::ANASAZI::solve_eigenproblem(), solve_with_guess(), VolumeCoupling::solveFirstHalfTimeStep(), solveQuad(), Eigen::IterativeSolverBase< Derived >::solveWithGuess(), oomph::DarcyEquations< DIM >::source(), sparse_basic(), sparse_product(), oomph::TetMeshBase::split_elements_in_corners(), DPMBase::splitDomain(), Eigen::AlignedBox< Scalar_, AmbientDim_ >::squaredExteriorDistance(), StefanBoltzmannProblem< ELEMENT >::StefanBoltzmannProblem(), WearableTriangulatedWall::storeDebris(), oomph::Refineable_r_mesh< ELEMENT >::stretch_mesh(), sub(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::SurfactantProblem(), Eigen::swap(), Eigen::internal::swap(), Eigen::numext::swap(), Eigen::internal::swap_plain_array(), MatrixSymmetric3D::symmetrisedDyadic(), test_accelerate_ldlt(), test_accelerate_llt(), test_accelerate_qr(), test_array_reverse_and_reduce(), test_array_zip_and_apply(), test_async_multithread_chip(), test_async_multithread_elementwise(), test_async_multithread_volume_patch(), test_comparison_sugar(), test_complex_operators(), test_const_slice(), test_conversion(), test_entire_volume_patch(), test_entire_volume_patch_sycl(), test_hypot(), test_id_helper(), test_imagenet_patches(), test_imagenet_patches_sycl(), test_isApprox(), boost::multiprecision::test_isApprox(), Eigen::test_isApprox(), test_isApprox_abs(), Eigen::test_isApproxOrLessThan(), boost::multiprecision::test_isApproxOrLessThan(), Eigen::test_isApproxWithRef(), test_isMuchSmallerThan(), boost::multiprecision::test_isMuchSmallerThan(), Eigen::test_isMuchSmallerThan(), test_nnls_does_not_allocate_during_solve(), test_nnls_handles_0x0_matrix(), test_nnls_handles_dependent_columns(), test_nnls_handles_Mx0_matrix(), test_nnls_handles_wide_matrix(), test_nnls_handles_zero_rhs(), test_nnls_known_1(), test_nnls_known_2(), test_nnls_known_3(), test_nnls_known_4(), test_nnls_known_5(), test_nnls_known_solution(), test_nnls_random_problem(), test_nnls_repeated_calls_to_compute_and_solve(), test_nnls_returns_NoConvergence_when_maxIterations_is_too_low(), test_nnls_special_case_solves_in_n_iterations(), test_nnls_special_case_solves_in_zero_iterations(), test_nnls_with_half_precision(), test_parallelize_gemm(), test_patch_padding_same(), test_patch_padding_same_sycl(), test_patch_padding_valid(), test_patch_padding_valid_same_value(), test_patch_padding_valid_same_value_sycl(), test_patch_padding_valid_sycl(), Eigen::test_relative_error(), test_relative_error(), boost::multiprecision::test_relative_error(), test_simple_image_patch_sycl(), test_simple_patch(), test_sparseqr_scalar(), test_spqr_scalar(), test_std_initializers_tensor(), test_stl_iterators(), test_unaryview_solve(), TreeTest< Dim >::testIntersect1(), TreeTest< Dim >::testIntersect2(), TreeTest< Dim >::testMinimize1(), TreeTest< Dim >::testMinimize2(), oomph::TetgenMesh< ELEMENT >::TetgenMesh(), TFaceTestProblem< ELEMENT >::TFaceTestProblem(), oomph::ThinLayerBrickOnTetMesh< ELEMENT >::ThinLayerBrickOnTetMesh(), Multipole::TranslateMultipoleExpansionTo(), TriangleFaceTestProblem< ELEMENT >::TriangleFaceTestProblem(), oomph::TriangleMesh< ELEMENT >::TriangleMesh(), TwoDDGProblem< ELEMENT >::TwoDDGProblem(), TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::TwoMeshFluxAdvectionDiffusionProblem(), TwoMeshFluxPoissonProblem< ELEMENT >::TwoMeshFluxPoissonProblem(), UnitCubePoissonMGProblem< ELEMENT, MESH >::UnitCubePoissonMGProblem(), Eigen::Quaternion< Scalar_, Options_ >::UnitRandom(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::unpin_surface(), UnsteadyHeatProblem< ELEMENT >::UnsteadyHeatProblem(), UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::UnstructuredFSIProblem(), UnstructuredTorusProblem< ELEMENT >::UnstructuredTorusProblem(), PeriodicBoundaryHandler::updateMaserParticle(), PeriodicBoundaryHandler::updateParticles(), PeriodicBoundaryHandler::updateParticleStatus(), Eigen::internal::gebp_traits< LhsScalar_, RhsScalar_, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::updateRhs(), Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::updateRhs(), Eigen::internal::gebp_traits< RealScalar, std::complex< RealScalar >, false, ConjRhs_, Arch, PacketSize_ >::updateRhs(), Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::updateRhs(), upperbidiag(), oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::validate(), Eigen::internal::random_without_cast_overflow< SrcScalar, TgtScalar, std::enable_if_t< NumTraits< SrcScalar >::IsInteger &&NumTraits< TgtScalar >::IsInteger &&NumTraits< TgtScalar >::IsSigned &&!NumTraits< SrcScalar >::IsSigned &&(std::numeric_limits< SrcScalar >::digits > std::numeric_limits< TgtScalar >::digits)> >::value(), Eigen::internal::random_without_cast_overflow< SrcScalar, TgtScalar, std::enable_if_t< NumTraits< SrcScalar >::IsInteger &&NumTraits< TgtScalar >::IsInteger &&!NumTraits< TgtScalar >::IsSigned &&!NumTraits< SrcScalar >::IsSigned &&(std::numeric_limits< SrcScalar >::digits > std::numeric_limits< TgtScalar >::digits)> >::value(), Eigen::internal::vec2d_swizzle2(), Eigen::internal::vec2d_unpackhi(), Eigen::internal::vec2d_unpacklo(), Eigen::internal::vec4f_movehl(), Eigen::internal::vec4f_movelh(), Eigen::internal::vec4f_swizzle2(), Eigen::internal::vec4f_unpackhi(), Eigen::internal::vec4f_unpacklo(), oomph::VectorHelpers::vector_diff(), Jeffery_Solution::velocity(), verify_nnls_optimality(), verifyIsApprox(), Eigen::verifyIsApprox(), Eigen::verifyIsCwiseApprox(), oomph::OcTree::vertex_node_to_vector(), oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::viscosity(), oomph::CassonTanMilRegWithBlendingConstitutiveEquation< DIM >::viscosity(), DPMBase::write(), rapidjson::Writer< Stream, Encoding, Allocator >::WriteBool_(), SolidProblem< ELEMENT_TYPE >::writeToVTK(), HorizontalScrew::writeVTK(), oomph::XdaTetMesh< ELEMENT >::XdaTetMesh(), YoungLaplaceProblem< ELEMENT >::YoungLaplaceProblem(), zero_sized_objects(), oomph::DiskLikeGeomObjectWithBoundaries::zeta_boundary_end(), oomph::DiskLikeGeomObjectWithBoundaries::zeta_boundary_start(), oomph::DiskLikeGeomObjectWithBoundaries::zeta_on_boundary(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::~TurekProblem(), and oomph::WarpedCircularDisk::~WarpedCircularDisk().
c
Scalar * c = reinterpret_cast<Scalar *>(pc)
Referenced by main().
size
int size = (SIDE(*side) == LEFT) ? (*m) : (*n)
Referenced by __attribute__(), Eigen::PlainObjectBase< Derived >::_init1(), Eigen::PlainObjectBase< Derived >::_resize_to_match(), Eigen::CholmodBase< MatrixType_, UpLo_, Derived >::_solve_impl(), Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::_solve_impl(), Eigen::IterativeSolverBase< Derived >::_solve_with_guess_impl(), oomph::TreeBasedRefineableMeshBase::adapt_mesh(), adjoint(), Eigen::internal::aligned_delete(), Eigen::internal::aligned_malloc(), Eigen::internal::aligned_new(), Eigen::internal::aligned_stack_memory_handler< T >::aligned_stack_memory_handler(), Eigen::internal::TensorBlockScratchAllocator< Device >::allocate(), Eigen::SimplicialCholeskyBase< Derived >::analyzePattern(), Eigen::SimplicialCholeskyBase< Derived >::analyzePattern_preordered(), Eigen::internal::apply_rotation_in_the_plane(), Eigen::test::areApprox(), Eigen::test::areApproxAbs(), Eigen::test::areEqual(), bench(), benchVec(), oomph::Problem::bifurcation_adapt_helper(), Eigen::TensorEvaluator< const TensorBroadcastingOp< Broadcast, ArgType >, Device >::block(), Eigen::TensorEvaluator< const TensorGeneratorOp< Generator, ArgType >, Device >::block(), Eigen::TensorEvaluator< const TensorPaddingOp< PaddingDimensions, ArgType >, Device >::block(), Eigen::TensorEvaluator< const TensorReverseOp< ReverseDimensions, ArgType >, Device >::block(), Eigen::TensorEvaluator< const TensorRollOp< RollDimensions, ArgType >, Device >::block(), oomph::BlockPreconditioner< MATRIX >::block_setup(), Eigen::internal::partial_lu_impl< Scalar, StorageOrder, PivIndex, SizeAtCompileTime >::blocked_lu(), MPIContainer::broadcast(), oomph::TetgenMesh< ELEMENT >::build_from_scaffold(), oomph::TriangleMesh< ELEMENT >::build_from_scaffold(), Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::calc_colcount(), Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::calc_etree(), Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::calc_hadj_inner(), Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::calc_hadj_outer(), Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::calc_lineage(), Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::calc_post(), Eigen::internal::calcColLoops(), Eigen::CoreThreadPoolDevice::calculateLevels(), Eigen::RunQueue< Work, kSize >::CalculateSize(), Eigen::internal::calcVSXColLoops(), pcast_array< SrcPacket, TgtPacket, 1, TgtCoeffRatio >::cast(), pcast_array< SrcPacket, TgtPacket, 2, 1 >::cast(), pcast_array< SrcPacket, TgtPacket, 4, 1 >::cast(), pcast_array< SrcPacket, TgtPacket, 8, 1 >::cast(), Eigen::DenseBase< Derived >::cend(), Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::check_array_bounds(), check_extremity_accuracy(), check_indexed_view(), check_marketio_vector(), check_negate(), Eigen::internal::check_size_for_overflow(), VorticityRecoveryProblem< ELEMENT >::check_smoothed_vorticity(), check_sparse_nonhermitian_solving(), check_sparse_spd_solving(), check_sparse_square_determinant(), check_sparse_square_solving(), check_symbolic_index(), cod(), Eigen::DenseCoeffsBase< Derived, ReadOnlyAccessors >::coeff(), Eigen::DenseCoeffsBase< Derived, WriteAccessors >::coeffRef(), Eigen::internal::colVSXLoops(), PeriodicBoundaryHandler::communicateTargetDomains(), compare(), compare_using_data_and_stride(), Eigen::PartialPivLU< MatrixType_, PermutationIndex_ >::compute(), Eigen::GeneralizedEigenSolver< MatrixType_ >::compute(), Eigen::IncompleteLU< Scalar_ >::compute(), Eigen::SimplicialCholeskyBase< Derived >::compute(), Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::computeInPlace(), Eigen::RealSchur< MatrixType_ >::computeNormOfT(), Eigen::RealQZ< MatrixType_ >::computeNorms(), Eigen::internal::conditional_aligned_delete(), Eigen::internal::conditional_aligned_delete_auto(), Eigen::internal::conditional_aligned_malloc(), Eigen::internal::conditional_aligned_malloc< false >(), Eigen::internal::conditional_aligned_new(), Eigen::internal::conditional_aligned_new_auto(), Eigen::PlainObjectBase< Derived >::conservativeResize(), Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Dynamic, Options >::conservativeResize(), Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Cols, Options >::conservativeResize(), Eigen::internal::DenseStorage_impl< T, Dynamic, Rows, Dynamic, Options >::conservativeResize(), Eigen::DenseBase< Derived >::Constant(), Eigen::internal::convertArrayF32toBF16Col(), Eigen::internal::convertArrayF32toBF16ColVSX(), Eigen::internal::convertArrayPointerBF16toF32DupOne(), Eigen::internal::convertBF16toF32(), Eigen::internal::convertPointerBF16toF32(), Eigen::internal::convertPointerF32toBF16(), convertPointerF32toBF16VSX(), Eigen::internal::copy_construct_elements_of_array(), oomph::GmshTetScaffoldMesh::create_mesh_from_msh_file(), Eigen::internal::IndexedViewHelperIndicesWrapper< ArithmeticSequence< FirstType, SizeType, IncrType >, NestedSizeAtCompileTime, void >::CreateIndexSequence(), Eigen::internal::CreateIndexSequence(), ctms_decompositions(), Eigen::internal::default_construct_elements_of_array(), Eigen::BDCSVD< MatrixType_, Options_ >::deflation43(), Eigen::BDCSVD< MatrixType_, Options_ >::deflation44(), dense_storage_assignment(), dense_storage_copy(), Eigen::internal::DenseStorage_impl< T, Size, Rows, Cols, Options >::DenseStorage_impl(), Eigen::internal::DenseStorage_impl< T, Size, Dynamic, Cols, Options >::DenseStorage_impl(), Eigen::internal::DenseStorage_impl< T, Size, Rows, Dynamic, Options >::DenseStorage_impl(), Eigen::internal::DenseStorage_impl< T, Size, Dynamic, Dynamic, Options >::DenseStorage_impl(), Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Cols, Options >::DenseStorage_impl(), Eigen::internal::DenseStorage_impl< T, Dynamic, Rows, Dynamic, Options >::DenseStorage_impl(), Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Dynamic, Options >::DenseStorage_impl(), Eigen::internal::destruct_elements_of_array(), determinant(), Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::DisjointSet::DisjointSet(), oomph::StefanBoltzmannHelper::doc_bins(), AxisymmetricVibratingShellProblem< ELEMENT >::doc_solution(), VibratingShellProblem< ELEMENT >::doc_solution(), Eigen::EigenSolver< MatrixType_ >::doComputeEigenvectors(), Eigen::SparseMatrixBase< Derived >::dot(), IcoSphere::draw(), dynamicVectorConstruction(), Eigen::internal::lapacke_helpers::lapacke_llt< Scalar, Mode >::EIGEN_STATIC_ASSERT(), Eigen::internal::SymbolicExpressionEvaluator< Expr, Dynamic, std::enable_if_t< symbolic::is_symbolic< Expr >::value > >::eval(), exp_complex_test(), Eigen::SuperLUBase< MatrixType_, Derived >::extractData(), Eigen::SimplicialCholeskyBase< Derived >::factorize(), Eigen::SimplicialCholeskyBase< Derived >::factorize_preordered(), NonRefineableBinArray::fill_bin_by_diffusion(), PeriodicBoundaryHandler::findNewInteractions(), Eigen::internal::first_aligned(), Eigen::internal::first_default_aligned(), Eigen::internal::first_multiple(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, 1 >::firstAligned(), Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::firstAligned(), float_pow_test_impl(), foo(), Eigen::internal::imklfft::imklfft_impl< Scalar_ >::fwd(), generate_sparse_nonhermitian_problem(), generate_sparse_spd_problem(), generate_sparse_square_problem(), GenerateRandomData(), Eigen::internal::get_runtime_reshape_size(), Eigen::internal::handmade_aligned_malloc(), hessenberg(), Eigen::HessenbergDecomposition< MatrixType_ >::HessenbergDecomposition(), Eigen::MatrixBase< Derived >::hnormalized(), householder_update(), Eigen::MatrixBase< Derived >::hypotNorm(), BinaryReader::ignoreChar(), Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::init_matrix(), Eigen::SuperLUBase< MatrixType_, Derived >::initFactorization(), Eigen::DenseBase< Derived >::innerSize(), Eigen::internal::imklfft::imklfft_impl< Scalar_ >::inv(), is_same_symb(), Eigen::internal::trsmKernelR< double, Index, Mode, false, TriStorageOrder, 1, true >::kernel(), Eigen::internal::trsmKernelL< double, Index, Mode, false, TriStorageOrder, 1, true >::kernel(), Eigen::internal::trsmKernelR< float, Index, Mode, false, TriStorageOrder, 1, true >::kernel(), Eigen::internal::trsmKernelL< float, Index, Mode, false, TriStorageOrder, 1, true >::kernel(), Eigen::internal::trsmKernelL< Scalar, Index, Mode, Conjugate, TriStorageOrder, OtherInnerStride, Specialized >::kernel(), Eigen::internal::trsmKernelR< Scalar, Index, Mode, Conjugate, TriStorageOrder, OtherInnerStride, Specialized >::kernel(), Eigen::placeholders::lastN(), TwoDDGProblem< ELEMENT >::limit(), Eigen::DenseBase< Derived >::LinSpaced(), load(), Eigen::CholmodBase< MatrixType_, UpLo_, Derived >::logDeterminant(), lu_invertible(), lu_partial_piv(), main(), make_vector(), BaseCluster::makeDataAnalysis(), Eigen::MatrixBase< Derived >::makeHouseholder(), Eigen::MatrixBase< Derived >::makeHouseholderInPlace(), rapidjson::CrtAllocator::Malloc(), rapidjson::MemoryPoolAllocator< BaseAllocator >::Malloc(), Eigen::PlainObjectBase< Derived >::Map(), map_class_matrix(), map_class_vector(), map_static_methods(), Eigen::PlainObjectBase< Derived >::MapAligned(), Eigen::internal::matrix_sqrt_quasi_triangular_diagonal(), Eigen::internal::matrix_sqrt_quasi_triangular_off_diagonal(), oomph::Mesh::max_and_min_element_size(), Eigen::DenseBase< Derived >::mean(), rapidjson::MemoryPoolAllocator< BaseAllocator >::MemoryPoolAllocator(), mixingtypes(), mmtr(), Eigen::internal::move_construct_elements_of_array(), oomph::CCDoubleMatrix::multiply(), oomph::CRDoubleMatrix::multiply(), negate_test(), nmsub_test(), Eigen::ThreadPoolTempl< Environment >::NonEmptyQueueIndex(), Eigen::RandomSetter< SparseMatrixType, MapTraits, OuterPacketBits >::nonZeros(), Eigen::DenseBase< Derived >::NullaryExpr(), NurbsSurface::NurbsSurface(), Eigen::internal::dhs_pack< bfloat16, DataMapper, Packet8bf, StorageOrder, PanelMode, false >::operator()(), Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::operator()(), Eigen::DenseCoeffsBase< Derived, WriteAccessors >::operator()(), Eigen::DenseCoeffsBase< Derived, ReadOnlyAccessors >::operator()(), Eigen::internal::tribb_kernel< LhsScalar, RhsScalar, Index, mr, nr, ConjLhs, ConjRhs, ResInnerStride, UpLo >::operator()(), Eigen::internal::ScanLauncher< Self, Reducer, Device, Vectorize >::operator()(), operator<<(), Eigen::DenseCoeffsBase< Derived, WriteAccessors >::operator[](), Eigen::DenseCoeffsBase< Derived, ReadOnlyAccessors >::operator[](), Eigen::SimplicialCholeskyBase< Derived >::ordering(), orthomethods(), Eigen::Map< PlainObjectType, MapOptions, StrideType >::outerStride(), Eigen::RefBase< Derived >::outerStride(), output(), oomph::MyTaylorHoodElement< DIM >::output(), oomph::MyCrouzeixRaviartElement::output(), oomph::TreeBasedRefineableMeshBase::p_adapt_mesh(), Eigen::DenseCoeffsBase< Derived, ReadOnlyAccessors >::packet(), packetmath(), packetmath_boolean_mask_ops(), packetmath_boolean_mask_ops_real(), packetmath_complex(), packetmath_notcomplex(), packetmath_real(), packetmath_scatter_gather(), packetmath_test_IEEE_corner_cases(), MyGenerator::packetOp(), Eigen::CoreThreadPoolDevice::parallelFor(), Eigen::CoreThreadPoolDevice::parallelForImpl(), Eigen::RealSchur< MatrixType_ >::performFrancisQRStep(), Eigen::internal::permute_symm_to_fullsymm(), Eigen::internal::permute_symm_to_symm(), oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::pin_all_non_pressure_dofs(), Eigen::internal::pload_partial_common(), Eigen::internal::ploadu_partial_common(), Eigen::internal::plset< PacketXf >(), Eigen::internal::plset< PacketXi >(), Eigen::RunQueue< Work, kSize >::PopBackHalf(), Eigen::test::print_mismatch(), Eigen::DenseBase< Derived >::prod(), Eigen::internal::psqrt< Packet4f >(), Eigen::internal::pstore_partial_common(), Eigen::internal::pstoreu_partial_common(), rapidjson::internal::Stack< Allocator >::Push(), qr(), qr_invertible(), randMatrixSpecialUnitary(), randMatrixUnitary(), Eigen::DenseBase< Derived >::Random(), randomMatrixWithRealEivals(), Eigen::randomPermutationVector(), BaseWall::read(), BasicIntersectionOfWalls::read(), BasicUnionOfWalls::read(), BinaryReader::readDouble(), BinaryReader::readFloat(), BinaryReader::readUnsignedInt(), Eigen::internal::InnerMostDimPreserver< 0, Self, Op, true >::reduce(), ref_vector(), Eigen::DenseBase< Derived >::resize(), Eigen::PlainObjectBase< Derived >::resize(), Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Dynamic, Options >::resize(), Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Cols, Options >::resize(), Eigen::internal::DenseStorage_impl< T, Dynamic, Rows, Dynamic, Options >::resize(), test_cast_helper< SrcPacket, TgtPacket, SrcCoeffRatio, TgtCoeffRatio, true >::run(), test_cast< SrcPacket, TgtPacket >::run(), packetmath_boolean_mask_ops_notcomplex_test< Scalar, Packet, std::enable_if_t< internal::packet_traits< Scalar >::HasCmp &&!internal::is_same< Scalar, bool >::value > >::run(), packetmath_minus_zero_add_test< Scalar, Packet, std::enable_if_t<!NumTraits< Scalar >::IsInteger > >::run(), Eigen::internal::visitor_impl< Visitor, Derived, Dynamic, false, true, ShortCircuitEvaluation >::run(), Eigen::internal::visitor_impl< Visitor, Derived, Dynamic, true, true, ShortCircuitEvaluation >::run(), Eigen::internal::inner_product_impl< Evaluator, false >::run(), Eigen::internal::inner_product_impl< Evaluator, true >::run(), Eigen::internal::redux_impl< Func, Evaluator, LinearVectorizedTraversal, NoUnrolling >::run(), Eigen::internal::packetwise_redux_impl< Func, Evaluator, NoUnrolling >::run(), Eigen::internal::TensorExecutor< Expression, DefaultDevice, true, TiledEvaluation::Off >::run(), Eigen::internal::TensorExecutor< Expression, Device, Vectorizable, Tiling >::run(), randomMatrixWithImagEivals< MatrixType, 0 >::run(), randomMatrixWithImagEivals< MatrixType, 1 >::run(), Eigen::internal::gemv_dense_selector< OnTheRight, ColMajor, true >::run(), Eigen::internal::gemv_dense_selector< OnTheRight, RowMajor, true >::run(), Eigen::internal::gemv_dense_selector< OnTheRight, ColMajor, false >::run(), Eigen::internal::trmv_selector< Mode, ColMajor >::run(), Eigen::internal::trmv_selector< Mode, RowMajor >::run(), Eigen::internal::triangular_solver_selector< Lhs, Rhs, Side, Mode, NoUnrolling, Dynamic >::run(), mapstaticmethods_impl< PlainObjectType, true, true >::run(), Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::run(), Eigen::internal::smart_copy_helper< T, true >::run(), Eigen::internal::smart_memmove_helper< T, true >::run(), Eigen::internal::TensorBlockAssignment< Scalar, NumDims, TensorBlockExpr, IndexType >::Run(), partition_action_t::run(), Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, true >::run(), Eigen::internal::VectorIndexedViewSelector< Derived, Indices, std::enable_if_t<!internal::is_single_range< IvcType< Indices, Derived::SizeAtCompileTime > >::value &&internal::IndexedViewHelper< IvcType< Indices, Derived::SizeAtCompileTime > >::IncrAtCompileTime==1 > >::run(), Eigen::internal::IndexedViewSelector< Derived, RowIndices, ColIndices, std::enable_if_t< internal::traits< IndexedView< Derived, IvcType< RowIndices, Derived::RowsAtCompileTime >, IvcType< ColIndices, Derived::ColsAtCompileTime > > >::ReturnAsBlock > >::run(), Eigen::internal::setIdentity_impl< Derived, true >::run(), Eigen::internal::selfadjoint_product_impl< Lhs, LhsMode, false, Rhs, 0, true >::run(), Eigen::internal::transposition_matrix_product< ExpressionType, Side, Transposed, ExpressionShape >::run(), Eigen::internal::triangular_matrix_vector_product< Index, Mode, LhsScalar, ConjLhs, RhsScalar, ConjRhs, ColMajor, Version >::run(), Eigen::internal::product_selfadjoint_matrix< Scalar, Index, LhsStorageOrder, true, ConjugateLhs, RhsStorageOrder, false, ConjugateRhs, ColMajor, ResInnerStride >::run(), Eigen::internal::product_selfadjoint_matrix< Scalar, Index, LhsStorageOrder, false, ConjugateLhs, RhsStorageOrder, true, ConjugateRhs, ColMajor, ResInnerStride >::run(), Eigen::internal::triangular_solve_vector< LhsScalar, RhsScalar, Index, OnTheRight, Mode, Conjugate, StorageOrder >::run(), Eigen::internal::triangular_solve_vector< LhsScalar, RhsScalar, Index, OnTheLeft, Mode, Conjugate, RowMajor >::run(), Eigen::internal::triangular_solve_vector< LhsScalar, RhsScalar, Index, OnTheLeft, Mode, Conjugate, ColMajor >::run(), Eigen::internal::packed_triangular_matrix_vector_product< Index, Mode, LhsScalar, ConjLhs, RhsScalar, ConjRhs, ColMajor >::run(), Eigen::internal::packed_triangular_matrix_vector_product< Index, Mode, LhsScalar, ConjLhs, RhsScalar, ConjRhs, RowMajor >::run(), Eigen::internal::packed_triangular_solve_vector< LhsScalar, RhsScalar, Index, OnTheLeft, Mode, Conjugate, RowMajor >::run(), Eigen::internal::packed_triangular_solve_vector< LhsScalar, RhsScalar, Index, OnTheLeft, Mode, Conjugate, ColMajor >::run(), Eigen::internal::packed_triangular_solve_vector< LhsScalar, RhsScalar, Index, OnTheRight, Mode, Conjugate, StorageOrder >::run(), Eigen::internal::selfadjoint_matrix_vector_product< Scalar, Index, StorageOrder, UpLo, ConjugateLhs, ConjugateRhs, Version >::run(), Eigen::internal::triangular_solve_matrix< Scalar, Index, Side, Mode, Conjugate, TriStorageOrder, RowMajor, OtherInnerStride >::run(), Eigen::internal::general_matrix_matrix_triangular_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, RowMajor, ResInnerStride, UpLo, Version >::run(), Eigen::internal::general_matrix_matrix_triangular_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor, ResInnerStride, UpLo, Version >::run(), Eigen::internal::band_solve_triangular_selector< Index, Mode, LhsScalar, ConjLhs, RhsScalar, RowMajor >::run(), Eigen::internal::band_solve_triangular_selector< Index, Mode, LhsScalar, ConjLhs, RhsScalar, ColMajor >::run(), Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheLeft, Mode, Conjugate, TriStorageOrder, ColMajor, OtherInnerStride >::run(), Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheRight, Mode, Conjugate, TriStorageOrder, ColMajor, OtherInnerStride >::run(), Eigen::internal::packed_rank2_update_selector< Scalar, Index, UpLo >::run(), Eigen::internal::selfadjoint_packed_rank1_update< Scalar, Index, ColMajor, UpLo, ConjLhs, ConjRhs >::run(), Eigen::internal::selfadjoint_packed_rank1_update< Scalar, Index, RowMajor, UpLo, ConjLhs, ConjRhs >::run(), Eigen::internal::rank2_update_selector< Scalar, Index, UpLo >::run(), Eigen::selfadjoint_rank1_update< Scalar, Index, ColMajor, UpLo, ConjLhs, ConjRhs >::run(), Eigen::selfadjoint_rank1_update< Scalar, Index, RowMajor, UpLo, ConjLhs, ConjRhs >::run(), Eigen::internal::dense_assignment_loop< Kernel, LinearVectorizedTraversal, NoUnrolling >::run(), Eigen::internal::dense_assignment_loop< Kernel, LinearVectorizedTraversal, CompleteUnrolling >::run(), Eigen::internal::dense_assignment_loop< Kernel, LinearTraversal, NoUnrolling >::run(), Eigen::internal::dense_assignment_loop_with_device< Kernel, CoreThreadPoolDevice, LinearTraversal, NoUnrolling >::run(), Eigen::internal::dense_assignment_loop_with_device< Kernel, CoreThreadPoolDevice, LinearVectorizedTraversal, NoUnrolling >::run(), processTriangularMatrix< MatrixType, 0 >::run(), Eigen::selfadjoint_product_selector< MatrixType, OtherType, UpLo, false >::run(), Eigen::general_product_to_triangular_selector< MatrixType, ProductType, UpLo, false >::run(), generateTestMatrix< MatrixType, 0 >::run(), generateTestMatrix< MatrixType, 1 >::run(), loadColData_impl< RhsMapper, linear >::run(), exp_complex_test_impl< Scalar, Packet, HasExp >::run(), Eigen::internal::selfadjoint_rank2_update_selector< Scalar, Index, UType, VType, Lower >::run(), Eigen::internal::selfadjoint_rank2_update_selector< Scalar, Index, UType, VType, Upper >::run(), Eigen::internal::apply_rotation_in_the_plane_selector< Scalar, OtherScalar, SizeAtCompileTime, MinAlignment, Vectorizable >::run(), Eigen::internal::apply_rotation_in_the_plane_selector< Scalar, OtherScalar, SizeAtCompileTime, MinAlignment, true >::run(), run_bdmp_spec_1(), run_vector_tests(), Eigen::ForkJoinScheduler::RunParallelForAsync(), schur(), Eigen::internal::scoped_array< T >::scoped_array(), oomph::AlgebraicNode::self_test(), Eigen::seqN(), Eigen::Serializer< DenseBase< Derived >, void >::serialize(), Eigen::Serializer< SparseMatrix< Scalar, Options, StorageIndex >, void >::serialize(), Eigen::internal::serialize_impl< N, T1, Ts... >::serialize_size(), Eigen::PlainObjectBase< Derived >::setConstant(), Eigen::DenseBase< Derived >::setEqualSpaced(), Eigen::DenseBase< Derived >::setLinSpaced(), Penetration::setSize(), Eigen::MatrixBase< Derived >::setUnit(), oomph::UnstructuredTwoDMeshGeometryBase::setup_boundary_coordinates(), oomph::BrickMeshBase::setup_boundary_element_info(), oomph::QuadMeshBase::setup_boundary_element_info(), oomph::TriangleMeshBase::setup_boundary_element_info(), oomph::HermiteQuadMesh< ELEMENT >::setup_boundary_element_info(), oomph::VorticitySmoother< ELEMENT >::setup_patches(), oomph::Z2ErrorEstimator::setup_patches(), Silo::setupInitialConditions(), signbit_test(), rapidjson::MemoryPoolAllocator< BaseAllocator >::Size(), oomph::TetMeshBase::snap_nodes_onto_geometric_objects(), Eigen::internal::solve_sparse_through_dense_panels(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_two_arrays(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_two_vectors(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_vectors_of_pairs(), sparse_permutations_all(), Eigen::internal::sparse_reserve_op< StorageIndex >::sparse_reserve_op(), special_value_pairs(), Eigen::RealSchur< MatrixType_ >::splitOffTwoRows(), stable_norm(), Eigen::ThreadPoolTempl< Environment >::Steal(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::storePacketBlock_helper< SubPacket, std::complex< double >, n, idx >::store(), storeBF16fromResult(), Eigen::internal::storeBlock(), helpers::stringFormat(), Eigen::DenseBase< Derived >::sum(), Eigen::internal::DenseStorage_impl< T, Size, Dynamic, Cols, Options >::swap(), Eigen::internal::DenseStorage_impl< T, Size, Rows, Dynamic, Options >::swap(), Eigen::internal::DenseStorage_impl< T, Size, Dynamic, Dynamic, Options >::swap(), swapBytes(), symm(), Eigen::TensorContractionEvaluatorBase< Derived >::TensorContractionEvaluatorBase(), test_1d_scan(), test_4d_scan(), test_array(), test_complex_operators(), test_conj_helper(), test_conversion(), test_exponent(), test_first_aligned_helper(), test_gpu_full_reductions(), test_memcpy(), test_minmax_nan_propagation_templ(), test_none_aligned_helper(), test_sycl_cast(), test_sycl_mem_sync(), testMapRef(), testMatrixType(), testPascal(), testVectorType(), oomph::ThinLayerBrickOnTetMesh< ELEMENT >::ThinLayerBrickOnTetMesh(), oomph::Mesh::total_size(), oomph::TriangleMeshPolyLine::TriangleMeshPolyLine(), triggerVectorBadAlloc(), trsolve(), Eigen::internal::partial_lu_impl< Scalar, StorageOrder, PivIndex, SizeAtCompileTime >::unblocked_lu(), Eigen::internal::upperbidiagonalization_inplace_blocked(), vectorRedux(), vectorVisitor(), verifyIsQuasiTriangular(), NurbsSurface::wrapAroundInU(), NurbsSurface::wrapAroundInV(), NurbsWall::writeWallDetailsVTK(), WearableNurbsWall::writeWallDetailsVTK(), oomph::XdaTetMesh< ELEMENT >::XdaTetMesh(), Eigen::DenseBase< Derived >::Zero(), zero_sized_objects(), Eigen::internal::zeroAccumulators(), Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Cols, Options >::~DenseStorage_impl(), Eigen::internal::DenseStorage_impl< T, Dynamic, Rows, Dynamic, Options >::~DenseStorage_impl(), and Eigen::internal::DenseStorage_impl< T, Dynamic, Dynamic, Dynamic, Options >::~DenseStorage_impl().