MercuryDPM: Eigen::TensorIOFormat Struct Reference
Eigen::TensorIOFormat Struct Reference
#include <TensorIO.h>
Public Types
using Base = TensorIOFormatBase< TensorIOFormat >
Public Types inherited from Eigen::TensorIOFormatBase< TensorIOFormat >
using Derived = TensorIOFormat
Public Member Functions
TensorIOFormat (const std::vector< std::string > &separator, const std::vector< std::string > &prefix, const std::vector< std::string > &suffix, int precision=StreamPrecision, int flags=0, const std::string &tenPrefix="", const std::string &tenSuffix="", const char fill=' ')
Public Member Functions inherited from Eigen::TensorIOFormatBase< TensorIOFormat >
TensorIOFormatBase (const std::vector< std::string > &separator, const std::vector< std::string > &prefix, const std::vector< std::string > &suffix, int precision=StreamPrecision, int flags=0, const std::string &tenPrefix="", const std::string &tenSuffix="", const char fill=' ')
void init_spacer ()
Static Public Member Functions
static const TensorIOFormatNumpy Numpy ()
static const TensorIOFormatPlain Plain ()
static const TensorIOFormatNative Native ()
static const TensorIOFormatLegacy Legacy ()
Additional Inherited Members
Public Attributes inherited from Eigen::TensorIOFormatBase< TensorIOFormat >
std::string tenPrefix
std::string tenSuffix
std::vector< std::string > prefix
std::vector< std::string > suffix
std::vector< std::string > separator
char fill
int precision
int flags
std::vector< std::string > spacer
Member Typedef Documentation
Base
using Eigen::TensorIOFormat::Base = TensorIOFormatBase<TensorIOFormat>
Constructor & Destructor Documentation
TensorIOFormat()
Eigen::TensorIOFormat::TensorIOFormat (const std::vector< std::string > & separator, const std::vector< std::string > & prefix, const std::vector< std::string > & suffix, int precision = StreamPrecision, int flags = 0, const std::string & tenPrefix = "", const std::string & tenSuffix = "", const char fill = ' ') inline
       : Base(separator, prefix, suffix, precision, flags, tenPrefix, tenSuffix, fill) {}
Member Function Documentation
Legacy()
static const TensorIOFormatLegacy Eigen::TensorIOFormat::Legacy () inline static
 { return TensorIOFormatLegacy{}; }
Native()
static const TensorIOFormatNative Eigen::TensorIOFormat::Native () inline static
 { return TensorIOFormatNative{}; }
Referenced by test_tensor_ostream_impl< std::complex< Scalar >, 2, Layout >::run().
Numpy()
static const TensorIOFormatNumpy Eigen::TensorIOFormat::Numpy () inline static
 { return TensorIOFormatNumpy{}; }
Referenced by test_tensor_ostream_impl< std::complex< Scalar >, 2, Layout >::run().
Plain()
static const TensorIOFormatPlain Eigen::TensorIOFormat::Plain () inline static
 { return TensorIOFormatPlain{}; }
Referenced by Eigen::operator<<(), test_tensor_ostream_impl< Scalar, 0, Layout >::run(), test_tensor_ostream_impl< Scalar, 1, Layout >::run(), test_tensor_ostream_impl< Scalar, 2, Layout >::run(), test_tensor_ostream_impl< Scalar, 3, Layout >::run(), test_tensor_ostream_impl< bool, 2, Layout >::run(), test_tensor_ostream_impl< std::complex< Scalar >, 2, Layout >::run(), and test_const_tensor_ostream().
The documentation for this struct was generated from the following file:
TensorIO.h