MercuryDPM: benchmark_main.cc File Reference
benchmark_main.cc File Reference
#include "benchmark.h"
#include <regex.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <string>
#include <inttypes.h>
#include <time.h>
#include <map>
Namespaces
testing
Typedefs
typedef std::map< std::string, ::testing::Benchmark * > BenchmarkMap
typedef BenchmarkMap::iterator BenchmarkMapIt
Functions
BenchmarkMap & gBenchmarks ()
static int Round (int n)
static int64_t NanoTime ()
void SetBenchmarkFlopsProcessed (int64_t x)
void StopBenchmarkTiming ()
void StartBenchmarkTiming ()
int main (int argc, char *argv[])
Variables
static int64_t g_flops_processed
static int64_t g_benchmark_total_time_ns
static int64_t g_benchmark_start_time_ns
static int g_name_column_width = 20
Typedef Documentation
BenchmarkMap
typedef std::map<std::string, ::testing::Benchmark*> BenchmarkMap
BenchmarkMapIt
typedef BenchmarkMap::iterator BenchmarkMapIt
Function Documentation
gBenchmarks()
BenchmarkMap& gBenchmarks ()
{
   static BenchmarkMap g_benchmarks;
   return g_benchmarks;
 }
Referenced by main(), and testing::Benchmark::Register().
main()
int main (int argc , char * argv[])
{
   if (gBenchmarks().empty()) {
     fprintf(stderr, "No benchmarks registered!\n");
     exit(EXIT_FAILURE);
   }
   for (BenchmarkMapIt it = gBenchmarks().begin(); it != gBenchmarks().end(); ++it) {
     int name_width = static_cast<int>(strlen(it->second->Name()));
     g_name_column_width = std::max(g_name_column_width, name_width);
   }
   bool need_header = true;
   for (BenchmarkMapIt it = gBenchmarks().begin(); it != gBenchmarks().end(); ++it) {
     ::testing::Benchmark* b = it->second;
     if (b->ShouldRun(argc, argv)) {
       if (need_header) {
         printf("%-*s %10s %10s\n", g_name_column_width, "", "iterations", "ns/op");
         fflush(stdout);
         need_header = false;
       }
       b->Run();
     }
   }
   if (need_header) {
     fprintf(stderr, "No matching benchmarks!\n");
     fprintf(stderr, "Available benchmarks:\n");
     for (BenchmarkMapIt it = gBenchmarks().begin(); it != gBenchmarks().end(); ++it) {
       fprintf(stderr, "  %s\n", it->second->Name());
     }
     exit(EXIT_FAILURE);
   }
   return 0;
 }
References b, g_name_column_width, gBenchmarks(), max, and fix_broken_doxygen_formulae::stdout.
NanoTime()
static int64_t NanoTime () static
{
 #if defined(__APPLE__)
   uint64_t t = mach_absolute_time();
   return t * g_time_info.numer / g_time_info.denom;
 #else
   struct timespec t;
   t.tv_sec = t.tv_nsec = 0;
   clock_gettime(CLOCK_MONOTONIC, &t);
   return static_cast<int64_t>(t.tv_sec) * 1000000000LL + t.tv_nsec;
 #endif
 }
References plotPSD::t.
Referenced by testing::Benchmark::RunRepeatedlyWithArg(), StartBenchmarkTiming(), and StopBenchmarkTiming().
Round()
static int Round (int n) static
{
   int base = 1;
   while (base * 10 < n) {
     base *= 10;
   }
   if (n < 2 * base) {
     return 2 * base;
   }
   if (n < 5 * base) {
     return 5 * base;
   }
   return 10 * base;
 }
References n.
Referenced by testing::Benchmark::RunWithArg().
SetBenchmarkFlopsProcessed()
void SetBenchmarkFlopsProcessed (int64_t x)
 { g_flops_processed = x; }
References g_flops_processed, and plotDoE::x.
Referenced by BenchmarkSuite< Device, T >::finalizeBenchmark().
StartBenchmarkTiming()
void StartBenchmarkTiming ()
{
   if (g_benchmark_start_time_ns == 0) {
     g_benchmark_start_time_ns = NanoTime();
   }
 }
References g_benchmark_start_time_ns, and NanoTime().
Referenced by BenchmarkSuite< Device, T >::algebraicFunc(), BenchmarkSuite< Device, T >::broadcasting(), BenchmarkSuite< Device, T >::coeffWiseOp(), BenchmarkSuite< Device, T >::colChip(), BenchmarkSuite< Device, T >::colReduction(), BenchmarkSuite< Device, T >::contraction(), BenchmarkSuite< Device, T >::convolution(), BenchmarkSuite< Device, T >::fullReduction(), BenchmarkSuite< Device, T >::memcpy(), BenchmarkSuite< Device, T >::padding(), BenchmarkSuite< Device, T >::random(), BenchmarkSuite< Device, T >::rowChip(), BenchmarkSuite< Device, T >::rowReduction(), BenchmarkSuite< Device, T >::shuffling(), BenchmarkSuite< Device, T >::slicing(), BenchmarkSuite< Device, T >::striding(), BenchmarkSuite< Device, T >::transcendentalFunc(), and BenchmarkSuite< Device, T >::typeCasting().
StopBenchmarkTiming()
void StopBenchmarkTiming ()
{
   if (g_benchmark_start_time_ns != 0) {
     g_benchmark_total_time_ns += NanoTime() - g_benchmark_start_time_ns;
   }
   g_benchmark_start_time_ns = 0;
 }
References g_benchmark_start_time_ns, g_benchmark_total_time_ns, and NanoTime().
Referenced by BenchmarkSuite< Device, T >::finalizeBenchmark().
Variable Documentation
g_benchmark_start_time_ns
int64_t g_benchmark_start_time_ns static
Referenced by testing::Benchmark::RunRepeatedlyWithArg(), StartBenchmarkTiming(), and StopBenchmarkTiming().
g_benchmark_total_time_ns
int64_t g_benchmark_total_time_ns static
Referenced by testing::Benchmark::RunRepeatedlyWithArg(), testing::Benchmark::RunWithArg(), and StopBenchmarkTiming().
g_flops_processed
int64_t g_flops_processed static
Referenced by testing::Benchmark::RunRepeatedlyWithArg(), testing::Benchmark::RunWithArg(), and SetBenchmarkFlopsProcessed().
g_name_column_width
int g_name_column_width = 20 static
Referenced by main(), and testing::Benchmark::RunWithArg().