MercuryDPM: LiquidFilm< Particle > Class Template Reference
LiquidFilm< Particle > Class Template Reference
#include <LiquidFilmParticle.h>
Public Member Functions
LiquidFilm ()
Basic Particle constructor, creates an Particle at (0,0,0) with radius, mass and inertia equal to 1.
LiquidFilm (const LiquidFilm &p)
Particle copy constructor, which accepts as input a reference to a Particle. It creates a copy of this Particle and all it's information. Usually it is better to use the copy() function for polymorfism.
~LiquidFilm () override=default
Particle destructor, needs to be implemented and checked if it removes tangential spring information.
LiquidFilm * copy () const override
Particle copy method. It calls to copy constructor of this Particle, useful for polymorfism.
void write (std::ostream &os) const override
std::string getName () const override
void read (std::istream &is) override
Mdouble getLiquidVolume () const
void setLiquidVolume (Mdouble liquidVolume)
void addLiquidVolume (Mdouble liquidVolume)
Mdouble getFullLiquidVolume () const
Mdouble getLiquidBridgeVolume () const
Mdouble getTotalEvaporatedLiquidVolume () const
void setTotalEvaporatedLiquidVolume (Mdouble liquidVolume)
void addTotalEvaporatedLiquidVolume (Mdouble liquidVolume)
Mdouble getMeanLiquidFilmThickness () const
Mdouble getRelativeLiquidVolume () const
unsigned getNumberOfFieldsVTK () const override
std::string getTypeVTK (unsigned i) const override
std::string getNameVTK (unsigned i) const override
std::vector< Mdouble > getFieldVTK (unsigned i) const override
bool isSphericalParticle () const override
Protected Attributes
Mdouble liquidVolume_
Mdouble totalEvaporatedLiquidVolume_
Constructor & Destructor Documentation
LiquidFilm() [1/2]
template<class Particle > LiquidFilm< Particle >::LiquidFilm () inline
Basic Particle constructor, creates an Particle at (0,0,0) with radius, mass and inertia equal to 1.
default constructor
     {
         liquidVolume_ = 0;
         totalEvaporatedLiquidVolume_ = 0;
     }
References LiquidFilm< Particle >::liquidVolume_, and LiquidFilm< Particle >::totalEvaporatedLiquidVolume_.
Referenced by LiquidFilm< Particle >::copy().
LiquidFilm() [2/2]
template<class Particle > LiquidFilm< Particle >::LiquidFilm (const LiquidFilm< Particle > & p) inline
Particle copy constructor, which accepts as input a reference to a Particle. It creates a copy of this Particle and all it's information. Usually it is better to use the copy() function for polymorfism.
Constructor that copies most of the properties of the given particle. Please note that not everything is copied, for example the position in the HGrid is not determined yet by the end of this constructor. It also does not copy the interactions and the pointer to the handler that handles this particle. Use with care.
Parameters
[in,out] p Reference to the LiquidFilm this one should become a copy of.
                                     : Particle(p)
     {
         liquidVolume_ = p.liquidVolume_;
         totalEvaporatedLiquidVolume_ = p.totalEvaporatedLiquidVolume_;
     }
References LiquidFilm< Particle >::liquidVolume_, p, and LiquidFilm< Particle >::totalEvaporatedLiquidVolume_.
~LiquidFilm()
template<class Particle > LiquidFilm< Particle >::~LiquidFilm () override default
Particle destructor, needs to be implemented and checked if it removes tangential spring information.
Destructor. It asks the ParticleHandler to check if this was the smallest or largest particle and adjust itself accordingly.
Member Function Documentation
addLiquidVolume()
template<class Particle > void LiquidFilm< Particle >::addLiquidVolume (Mdouble liquidVolume) inline
     {
         liquidVolume_ += liquidVolume;
     }
References LiquidFilm< Particle >::liquidVolume_.
Referenced by DropletBoundary::checkBoundaryAfterParticlesMove(), LiquidMigrationLSInteraction::distributeToOtherBridges(), and LiquidMigrationWilletInteraction::distributeToOtherBridges().
addTotalEvaporatedLiquidVolume()
template<class Particle > void LiquidFilm< Particle >::addTotalEvaporatedLiquidVolume (Mdouble liquidVolume) inline
     {
         totalEvaporatedLiquidVolume_ += liquidVolume;
     }
References LiquidFilm< Particle >::totalEvaporatedLiquidVolume_.
copy()
template<class Particle > LiquidFilm* LiquidFilm< Particle >::copy () const inline override
Particle copy method. It calls to copy constructor of this Particle, useful for polymorfism.
Copy method. Uses copy constructor to create a copy on the heap. Useful for polymorphism.
Returns
pointer to the particle's copy
     {
         return new LiquidFilm(*this);
     }
References LiquidFilm< Particle >::LiquidFilm().
getFieldVTK()
template<class Particle > std::vector< Mdouble > LiquidFilm< Particle >::getFieldVTK (unsigned i) const override
 {
     if (i==1)
         return { liquidVolume_ };
     else if (i==2)
         return { getLiquidBridgeVolume() };
     else if (i==3)
         return { totalEvaporatedLiquidVolume_ };
     else if (i==4)
         return { getMeanLiquidFilmThickness() };
     else if (i==5)
         return { getRelativeLiquidVolume() };
     else /*i=0*/
         return { getFullLiquidVolume() };
 }
References i.
getFullLiquidVolume()
template<class Particle > Mdouble LiquidFilm< Particle >::getFullLiquidVolume () const inline
     {
         return liquidVolume_ + getLiquidBridgeVolume();
     }
References LiquidFilm< Particle >::getLiquidBridgeVolume(), and LiquidFilm< Particle >::liquidVolume_.
Referenced by HeatFluidCoupled< Particle >::getFieldVTK().
getLiquidBridgeVolume()
template<class Particle > Mdouble LiquidFilm< Particle >::getLiquidBridgeVolume
 {
     // Sums the volume of all liquid bridges. Half when interacting with a particle, full when interacting with a wall.
     Mdouble volume = 0.0;
     for (auto i : this->getInteractions())
     {
         auto j = dynamic_cast<LiquidMigrationWilletInteraction*>(i);
         if (j)
         {
             if (dynamic_cast<BaseParticle*>(j->getI()))
                 volume += 0.5 * j->getLiquidBridgeVolume();
             else
                 volume += j->getLiquidBridgeVolume();
         }
         else
         {
             auto k = dynamic_cast<LiquidMigrationLSInteraction*>(i);
             if (k)
             {
                 if (dynamic_cast<BaseParticle*>(k->getI()))
                     volume += 0.5 * k->getLiquidBridgeVolume();
                 else
                     volume += k->getLiquidBridgeVolume();
             }
         }
     }
     return volume;
 }
References i, j, and k.
Referenced by HeatFluidCoupled< Particle >::getFieldVTK(), and LiquidFilm< Particle >::getFullLiquidVolume().
getLiquidVolume()
template<class Particle > Mdouble LiquidFilm< Particle >::getLiquidVolume () const inline
     {
         return liquidVolume_;
     }
References LiquidFilm< Particle >::liquidVolume_.
Referenced by LiquidMigrationSelfTest::printTime().
getMeanLiquidFilmThickness()
template<class Particle > Mdouble LiquidFilm< Particle >::getMeanLiquidFilmThickness () const inline
This is an approximated value of the thickness, used to be compatible with all particle types. Note that some particles might not have a getSurfaceArea() function implemented!
     {
         return liquidVolume_ / Particle::getSurfaceArea();
     }
References LiquidFilm< Particle >::liquidVolume_.
getName()
template<class Particle > std::string LiquidFilm< Particle >::getName () const inline override
Returns the name of the object; in this case 'LiquidFilm'.
Returns
The object name.
     {
         return "LiquidFilm" + Particle::getName();
     }
References getName().
getNameVTK()
template<class Particle > std::string LiquidFilm< Particle >::getNameVTK (unsigned i) const override
 {
     if (i==1)
         return "liquidFilmVolume";
     else if (i==2)
         return "liquidBridgeVolume";
     else if (i==3)
         return "totalEvaporatedLiquidVolume";
     else if (i==4)
         return "meanLiquidFilmThickness";
     else if (i==5)
         return "relativeLiquidVolume";
     else /*i=0*/
         return "fullLiquidVolume";
 }
References i.
getNumberOfFieldsVTK()
template<class Particle > unsigned LiquidFilm< Particle >::getNumberOfFieldsVTK () const inline override
     {
         return 6;
     }
getRelativeLiquidVolume()
template<class Particle > Mdouble LiquidFilm< Particle >::getRelativeLiquidVolume () const inline
     {
         return liquidVolume_ / Particle::getVolume();
     }
References LiquidFilm< Particle >::liquidVolume_.
getTotalEvaporatedLiquidVolume()
template<class Particle > Mdouble LiquidFilm< Particle >::getTotalEvaporatedLiquidVolume () const inline
     {
         return totalEvaporatedLiquidVolume_;
     }
References LiquidFilm< Particle >::totalEvaporatedLiquidVolume_.
getTypeVTK()
template<class Particle > std::string LiquidFilm< Particle >::getTypeVTK (unsigned i) const inline override
     {
         return "Float32";
     }
isSphericalParticle()
template<class Particle > bool LiquidFilm< Particle >::isSphericalParticle () const inline override
 {return true;}
read()
template<class Particle > void LiquidFilm< Particle >::read (std::istream & is) override
Particle read function. Has an std::istream as argument, from which it extracts the radius_, invMass_ and invInertia_, respectively. From these the mass_ and inertia_ are deduced. An additional set of properties is read through the call to the parent's method BaseParticle::read().
Parameters
[in,out] is input stream with particle properties.
 {
     Particle::read(is);
     std::string dummy;
     is >> dummy >> liquidVolume_;
     // a fix to allow reading of restart files pre-nonspherical
     if (dummy == "invInertia")
     {
         is >> dummy >> liquidVolume_;
     }
     is >> dummy >> totalEvaporatedLiquidVolume_;
 }
References Eigen::TensorSycl::internal::read(), and oomph::Global_string_for_annotation::string().
setLiquidVolume()
template<class Particle > void LiquidFilm< Particle >::setLiquidVolume (Mdouble liquidVolume) inline
     {
         liquidVolume_ = liquidVolume;
     }
References LiquidFilm< Particle >::liquidVolume_.
Referenced by LiquidMigrationMPI2Test::setupInitialConditions(), LiquidMigrationSelfTest::setupInitialConditions(), TwoParticleElasticCollisionInteraction::setupInitialConditions(), and EvaporationAndHeatTest::setupInitialConditions().
setTotalEvaporatedLiquidVolume()
template<class Particle > void LiquidFilm< Particle >::setTotalEvaporatedLiquidVolume (Mdouble liquidVolume) inline
     {
         totalEvaporatedLiquidVolume_ = liquidVolume;
     }
References LiquidFilm< Particle >::totalEvaporatedLiquidVolume_.
write()
template<class Particle > void LiquidFilm< Particle >::write (std::ostream & os) const inline override
LiquidFilm print method, which accepts an os std::ostream as input. It prints human readable LiquidFilm information to the std::ostream.
Parameters
[in,out] os stream to which the info is written
     {
         Particle::write(os);
         os << " liquidVolume " << liquidVolume_ << " totalEvaporatedLiquidVolume " << totalEvaporatedLiquidVolume_;
     }
References LiquidFilm< Particle >::liquidVolume_, LiquidFilm< Particle >::totalEvaporatedLiquidVolume_, and Eigen::TensorSycl::internal::write().
Member Data Documentation
liquidVolume_
template<class Particle > Mdouble LiquidFilm< Particle >::liquidVolume_ protected
Referenced by LiquidFilm< Particle >::addLiquidVolume(), HeatFluidCoupled< Particle >::getFieldVTK(), LiquidFilm< Particle >::getFullLiquidVolume(), LiquidFilm< Particle >::getLiquidVolume(), LiquidFilm< Particle >::getMeanLiquidFilmThickness(), LiquidFilm< Particle >::getRelativeLiquidVolume(), LiquidFilm< Particle >::LiquidFilm(), LiquidFilm< Particle >::setLiquidVolume(), and LiquidFilm< Particle >::write().
totalEvaporatedLiquidVolume_
template<class Particle > Mdouble LiquidFilm< Particle >::totalEvaporatedLiquidVolume_ protected
Referenced by LiquidFilm< Particle >::addTotalEvaporatedLiquidVolume(), HeatFluidCoupled< Particle >::getFieldVTK(), LiquidFilm< Particle >::getTotalEvaporatedLiquidVolume(), LiquidFilm< Particle >::LiquidFilm(), LiquidFilm< Particle >::setTotalEvaporatedLiquidVolume(), and LiquidFilm< Particle >::write().
The documentation for this class was generated from the following files:
LiquidMigrationLSInteraction.h
LiquidFilmParticle.h