MercuryDPM: JacobiSVD_basic.cpp File Reference
JacobiSVD_basic.cpp File Reference
Functions
cout<< "Here is the matrix m:"<< endl<< m<< endl;JacobiSVD< MatrixXf, ComputeThinU|ComputeThinV > svd (m)
Variables
MatrixXf m = MatrixXf::Random(3, 2)
Function Documentation
svd()
cout<< "Here is the matrix m:" << endl << m << endl;JacobiSVD<MatrixXf, ComputeThinU | ComputeThinV> svd (m)
Referenced by Eigen::internal::qr_preconditioner_impl< MatrixType, Options, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::allocate(), Eigen::internal::qr_preconditioner_impl< MatrixType, Options, FullPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::allocate(), Eigen::internal::qr_preconditioner_impl< MatrixType, Options, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::allocate(), Eigen::internal::qr_preconditioner_impl< MatrixType, Options, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::allocate(), Eigen::internal::qr_preconditioner_impl< MatrixType, Options, HouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::allocate(), Eigen::internal::qr_preconditioner_impl< MatrixType, Options, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::allocate(), bdcsvd_check_convergence(), Eigen::internal::lapacke_helpers::BDCSVD_wrapper(), cod(), cod_fixedsize(), Eigen::BDCSVD< MatrixType_, Options_ >::computeBaseCase(), Eigen::Transform< Scalar_, Dim_, Mode_, Options_ >::computeRotationScaling(), Eigen::Transform< Scalar_, Dim_, Mode_, Options_ >::computeScalingRotation(), randomRotationMatrix(), Eigen::internal::qr_preconditioner_impl< MatrixType, Options, FullPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, Options, FullPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, Options, ColPivHouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, Options, ColPivHouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, Options, HouseholderQRPreconditioner, PreconditionIfMoreRowsThanCols, true >::run(), Eigen::internal::qr_preconditioner_impl< MatrixType, Options, HouseholderQRPreconditioner, PreconditionIfMoreColsThanRows, true >::run(), Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, Options, true >::run(), Eigen::QuaternionBase< Derived >::setFromTwoVectors(), svd_check_full(), svd_compare_to_full(), svd_inf_nan(), svd_least_square(), svd_preallocate(), svd_underoverflow(), svd_verify_constructor_options_assert(), Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::Through(), and Eigen::umeyama().
Variable Documentation
m
MatrixXf m = MatrixXf::Random(3, 2)