MercuryDPM: Eigen::internal::scalar_logistic_op_impl< T, std::enable_if_t< NumTraits< T >::IsComplex > > Struct Template Reference
Eigen::internal::scalar_logistic_op_impl< T, std::enable_if_t< NumTraits< T >::IsComplex > > Struct Template Reference
#include <UnaryFunctors.h>
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T operator() (const T &x) const
Member Function Documentation
operator()()
template<typename T > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T Eigen::internal::scalar_logistic_op_impl< T, std::enable_if_t< NumTraits< T >::IsComplex > >::operator() (const T & x) const inline
{
     const T e = numext::exp(x);
     return (numext::isinf)(numext::real(e)) ? T(1) : e / (e + T(1));
   }
References e(), Eigen::numext::exp(), Eigen::numext::isinf(), and plotDoE::x.
The documentation for this struct was generated from the following file:
functors/UnaryFunctors.h