MercuryDPM: Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ > Class Template Reference
Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ > Class Template Reference
#include <GeneralBlockPanelKernel.h>
Public Types
enum {
ConjLhs = ConjLhs_ , ConjRhs = false , Vectorizable = unpacket_traits<LhsPacket_>::vectorizable && unpacket_traits<RhsPacket_>::vectorizable , LhsPacketSize = Vectorizable ? unpacket_traits<LhsPacket_>::size : 1 ,
RhsPacketSize = Vectorizable ? unpacket_traits<RhsPacket_>::size : 1 , ResPacketSize = Vectorizable ? unpacket_traits<ResPacket_>::size : 1 , NumberOfRegisters = EIGEN_ARCH_DEFAULT_NUMBER_OF_REGISTERS , nr = 4 ,
mr = (plain_enum_min(16, NumberOfRegisters) / 2 / nr) * LhsPacketSize , LhsProgress = LhsPacketSize , RhsProgress = 1
}
typedef std::complex< RealScalar > LhsScalar
typedef RealScalar RhsScalar
typedef ScalarBinaryOpTraits< LhsScalar, RhsScalar >::ReturnType ResScalar
typedef std::conditional_t< Vectorizable, LhsPacket_, LhsScalar > LhsPacket
typedef std::conditional_t< Vectorizable, RhsPacket_, RhsScalar > RhsPacket
typedef std::conditional_t< Vectorizable, ResPacket_, ResScalar > ResPacket
typedef LhsPacket LhsPacket4Packing
typedef QuadPacket< RhsPacket > RhsPacketx4
typedef ResPacket AccPacket
Public Member Functions
PACKET_DECL_COND_POSTFIX (_, Lhs, PacketSize_)
PACKET_DECL_COND_POSTFIX (_, Rhs, PacketSize_)
PACKET_DECL_COND_POSTFIX (_, Res, PacketSize_)
EIGEN_STRONG_INLINE void initAcc (AccPacket &p)
template<typename RhsPacketType >
EIGEN_STRONG_INLINE void loadRhs (const RhsScalar *b, RhsPacketType &dest) const
EIGEN_STRONG_INLINE void loadRhs (const RhsScalar *b, RhsPacketx4 &dest) const
template<typename RhsPacketType >
EIGEN_STRONG_INLINE void updateRhs (const RhsScalar *b, RhsPacketType &dest) const
EIGEN_STRONG_INLINE void updateRhs (const RhsScalar *, RhsPacketx4 &) const
EIGEN_STRONG_INLINE void loadRhsQuad (const RhsScalar *b, RhsPacket &dest) const
EIGEN_STRONG_INLINE void loadRhsQuad_impl (const RhsScalar *b, RhsPacket &dest, const true_type &) const
EIGEN_STRONG_INLINE void loadRhsQuad_impl (const RhsScalar *b, RhsPacket &dest, const false_type &) const
EIGEN_STRONG_INLINE void loadLhs (const LhsScalar *a, LhsPacket &dest) const
template<typename LhsPacketType >
EIGEN_STRONG_INLINE void loadLhsUnaligned (const LhsScalar *a, LhsPacketType &dest) const
template<typename LhsPacketType , typename RhsPacketType , typename AccPacketType , typename LaneIdType >
EIGEN_STRONG_INLINE void madd (const LhsPacketType &a, const RhsPacketType &b, AccPacketType &c, RhsPacketType &tmp, const LaneIdType &) const
template<typename LhsPacketType , typename RhsPacketType , typename AccPacketType >
EIGEN_STRONG_INLINE void madd_impl (const LhsPacketType &a, const RhsPacketType &b, AccPacketType &c, RhsPacketType &tmp, const true_type &) const
EIGEN_STRONG_INLINE void madd_impl (const LhsScalar &a, const RhsScalar &b, ResScalar &c, RhsScalar &, const false_type &) const
template<typename LhsPacketType , typename AccPacketType , typename LaneIdType >
EIGEN_STRONG_INLINE void madd (const LhsPacketType &a, const RhsPacketx4 &b, AccPacketType &c, RhsPacket &tmp, const LaneIdType &lane) const
template<typename ResPacketType , typename AccPacketType >
EIGEN_STRONG_INLINE void acc (const AccPacketType &c, const ResPacketType &alpha, ResPacketType &r) const
Member Typedef Documentation
AccPacket
template<typename RealScalar , bool ConjLhs_, int Arch, int PacketSize_> typedef ResPacket Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::AccPacket
LhsPacket
template<typename RealScalar , bool ConjLhs_, int Arch, int PacketSize_> typedef std::conditional_t<Vectorizable, LhsPacket_, LhsScalar> Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::LhsPacket
LhsPacket4Packing
template<typename RealScalar , bool ConjLhs_, int Arch, int PacketSize_> typedef LhsPacket Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::LhsPacket4Packing
LhsScalar
template<typename RealScalar , bool ConjLhs_, int Arch, int PacketSize_> typedef std::complex<RealScalar> Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::LhsScalar
ResPacket
template<typename RealScalar , bool ConjLhs_, int Arch, int PacketSize_> typedef std::conditional_t<Vectorizable, ResPacket_, ResScalar> Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::ResPacket
ResScalar
template<typename RealScalar , bool ConjLhs_, int Arch, int PacketSize_> typedef ScalarBinaryOpTraits<LhsScalar, RhsScalar>::ReturnType Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::ResScalar
RhsPacket
template<typename RealScalar , bool ConjLhs_, int Arch, int PacketSize_> typedef std::conditional_t<Vectorizable, RhsPacket_, RhsScalar> Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::RhsPacket
RhsPacketx4
template<typename RealScalar , bool ConjLhs_, int Arch, int PacketSize_> typedef QuadPacket<RhsPacket> Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::RhsPacketx4
RhsScalar
template<typename RealScalar , bool ConjLhs_, int Arch, int PacketSize_> typedef RealScalar Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::RhsScalar
Member Enumeration Documentation
anonymous enum
template<typename RealScalar , bool ConjLhs_, int Arch, int PacketSize_> anonymous enum
Enumerator
ConjLhs
ConjRhs
Vectorizable
LhsPacketSize
RhsPacketSize
ResPacketSize
NumberOfRegisters
nr
mr
LhsProgress
RhsProgress
        {
     ConjLhs = ConjLhs_,
     ConjRhs = false,
     Vectorizable = unpacket_traits<LhsPacket_>::vectorizable && unpacket_traits<RhsPacket_>::vectorizable,
     LhsPacketSize = Vectorizable ? unpacket_traits<LhsPacket_>::size : 1,
     RhsPacketSize = Vectorizable ? unpacket_traits<RhsPacket_>::size : 1,
     ResPacketSize = Vectorizable ? unpacket_traits<ResPacket_>::size : 1,
     NumberOfRegisters = EIGEN_ARCH_DEFAULT_NUMBER_OF_REGISTERS,
     nr = 4,
 #if defined(EIGEN_HAS_SINGLE_INSTRUCTION_MADD) && !defined(EIGEN_VECTORIZE_ALTIVEC) && !defined(EIGEN_VECTORIZE_VSX)
     // we assume 16 registers
     mr = 3 * LhsPacketSize,
 #else
     mr = (plain_enum_min(16, NumberOfRegisters) / 2 / nr) * LhsPacketSize,
 #endif
     LhsProgress = LhsPacketSize,
     RhsProgress = 1
   };
Member Function Documentation
acc()
template<typename RealScalar , bool ConjLhs_, int Arch, int PacketSize_> template<typename ResPacketType , typename AccPacketType > EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::acc (const AccPacketType & c, const ResPacketType & alpha, ResPacketType & r) const inline
{
     conj_helper<ResPacketType, ResPacketType, ConjLhs, false> cj;
     r = cj.pmadd(c, alpha, r);
   }
References alpha, calibrate::c, Eigen::internal::conj_helper< LhsType, RhsType, ConjLhs, ConjRhs >::pmadd(), and UniformPSDSelfTest::r.
initAcc()
template<typename RealScalar , bool ConjLhs_, int Arch, int PacketSize_> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::initAcc (AccPacket & p) inline
 { p = pset1<ResPacket>(ResScalar(0)); }
References p.
loadLhs()
template<typename RealScalar , bool ConjLhs_, int Arch, int PacketSize_> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::loadLhs (const LhsScalar * a, LhsPacket & dest) const inline
 { dest = pload<LhsPacket>(a); }
References a.
loadLhsUnaligned()
template<typename RealScalar , bool ConjLhs_, int Arch, int PacketSize_> template<typename LhsPacketType > EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::loadLhsUnaligned (const LhsScalar * a, LhsPacketType & dest) const inline
{
     dest = ploadu<LhsPacketType>(a);
   }
References a.
loadRhs() [1/2]
template<typename RealScalar , bool ConjLhs_, int Arch, int PacketSize_> template<typename RhsPacketType > EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::loadRhs (const RhsScalar * b, RhsPacketType & dest) const inline
{
     dest = pset1<RhsPacketType>(*b);
   }
References b.
loadRhs() [2/2]
template<typename RealScalar , bool ConjLhs_, int Arch, int PacketSize_> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::loadRhs (const RhsScalar * b, RhsPacketx4 & dest) const inline
{
     pbroadcast4(b, dest.B_0, dest.B1, dest.B2, dest.B3);
   }
References b, Eigen::internal::QuadPacket< Packet >::B1, Eigen::internal::QuadPacket< Packet >::B2, Eigen::internal::QuadPacket< Packet >::B3, Eigen::internal::QuadPacket< Packet >::B_0, and Eigen::internal::pbroadcast4().
loadRhsQuad()
template<typename RealScalar , bool ConjLhs_, int Arch, int PacketSize_> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::loadRhsQuad (const RhsScalar * b, RhsPacket & dest) const inline
{
     loadRhsQuad_impl(b, dest, std::conditional_t<RhsPacketSize == 16, true_type, false_type>());
   }
References b.
loadRhsQuad_impl() [1/2]
template<typename RealScalar , bool ConjLhs_, int Arch, int PacketSize_> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::loadRhsQuad_impl (const RhsScalar * b, RhsPacket & dest, const false_type &) const inline
{
     eigen_internal_assert(RhsPacketSize <= 8);
     dest = pset1<RhsPacket>(*b);
   }
References b, eigen_internal_assert, and Eigen::internal::gebp_traits< LhsScalar_, RhsScalar_, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::RhsPacketSize.
loadRhsQuad_impl() [2/2]
template<typename RealScalar , bool ConjLhs_, int Arch, int PacketSize_> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::loadRhsQuad_impl (const RhsScalar * b, RhsPacket & dest, const true_type &) const inline
{
     // FIXME we can do better!
     // what we want here is a ploadheight
     RhsScalar tmp[4] = {b[0], b[0], b[1], b[1]};
     dest = ploadquad<RhsPacket>(tmp);
   }
References b, and tmp.
madd() [1/2]
template<typename RealScalar , bool ConjLhs_, int Arch, int PacketSize_> template<typename LhsPacketType , typename RhsPacketType , typename AccPacketType , typename LaneIdType > EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::madd (const LhsPacketType & a, const RhsPacketType & b, AccPacketType & c, RhsPacketType & tmp, const LaneIdType &) const inline
{
     madd_impl(a, b, c, tmp, std::conditional_t<Vectorizable, true_type, false_type>());
   }
References a, b, calibrate::c, and tmp.
madd() [2/2]
template<typename RealScalar , bool ConjLhs_, int Arch, int PacketSize_> template<typename LhsPacketType , typename AccPacketType , typename LaneIdType > EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::madd (const LhsPacketType & a, const RhsPacketx4 & b, AccPacketType & c, RhsPacket & tmp, const LaneIdType & lane) const inline
{
     madd(a, b.get(lane), c, tmp, lane);
   }
References a, b, calibrate::c, Eigen::internal::gebp_traits< LhsScalar_, RhsScalar_, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::madd(), and tmp.
madd_impl() [1/2]
template<typename RealScalar , bool ConjLhs_, int Arch, int PacketSize_> template<typename LhsPacketType , typename RhsPacketType , typename AccPacketType > EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::madd_impl (const LhsPacketType & a, const RhsPacketType & b, AccPacketType & c, RhsPacketType & tmp, const true_type &) const inline
{
 #ifdef EIGEN_HAS_SINGLE_INSTRUCTION_MADD
     EIGEN_UNUSED_VARIABLE(tmp);
     c.v = pmadd(a.v, b, c.v);
 #else
     tmp = b;
     tmp = pmul(a.v, tmp);
     c.v = padd(c.v, tmp);
 #endif
   }
References a, b, calibrate::c, EIGEN_UNUSED_VARIABLE, Eigen::internal::padd(), Eigen::internal::pmadd(), Eigen::internal::pmul(), and tmp.
madd_impl() [2/2]
template<typename RealScalar , bool ConjLhs_, int Arch, int PacketSize_> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::madd_impl (const LhsScalar & a, const RhsScalar & b, ResScalar & c, RhsScalar & , const false_type &) const inline
{
     c += a * b;
   }
References a, b, and calibrate::c.
PACKET_DECL_COND_POSTFIX() [1/3]
template<typename RealScalar , bool ConjLhs_, int Arch, int PacketSize_> Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::PACKET_DECL_COND_POSTFIX (_ , Lhs , PacketSize_)
PACKET_DECL_COND_POSTFIX() [2/3]
template<typename RealScalar , bool ConjLhs_, int Arch, int PacketSize_> Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::PACKET_DECL_COND_POSTFIX (_ , Res , PacketSize_)
PACKET_DECL_COND_POSTFIX() [3/3]
template<typename RealScalar , bool ConjLhs_, int Arch, int PacketSize_> Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::PACKET_DECL_COND_POSTFIX (_ , Rhs , PacketSize_)
updateRhs() [1/2]
template<typename RealScalar , bool ConjLhs_, int Arch, int PacketSize_> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::updateRhs (const RhsScalar * , RhsPacketx4 &) const inline
 {}
updateRhs() [2/2]
template<typename RealScalar , bool ConjLhs_, int Arch, int PacketSize_> template<typename RhsPacketType > EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, RealScalar, ConjLhs_, false, Arch, PacketSize_ >::updateRhs (const RhsScalar * b, RhsPacketType & dest) const inline
{
     loadRhs(b, dest);
   }
References b, and Eigen::internal::gebp_traits< LhsScalar_, RhsScalar_, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::loadRhs().
The documentation for this class was generated from the following file:
products/GeneralBlockPanelKernel.h