MercuryDPM: Eigen::internal::unary_pow::exponent_helper< ScalarExponent, true > Struct Template Reference
Eigen::internal::unary_pow::exponent_helper< ScalarExponent, true > Struct Template Reference
#include <GenericPacketMathFunctions.h>
Public Types
using safe_abs_type = typename numext::get_integer_by_size< sizeof(ScalarExponent)>::unsigned_type
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE safe_abs_type safe_abs (const ScalarExponent &exp)
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool is_odd (const safe_abs_type &exp)
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE safe_abs_type floor_div_two (const safe_abs_type &exp)
Member Typedef Documentation
safe_abs_type
template<typename ScalarExponent > using Eigen::internal::unary_pow::exponent_helper< ScalarExponent, true >::safe_abs_type = typename numext::get_integer_by_size<sizeof(ScalarExponent)>::unsigned_type
Member Function Documentation
floor_div_two()
template<typename ScalarExponent > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE safe_abs_type Eigen::internal::unary_pow::exponent_helper< ScalarExponent, true >::floor_div_two (const safe_abs_type & exp) inline static
{
     return exp >> safe_abs_type(1);
   }
References Eigen::bfloat16_impl::exp().
is_odd()
template<typename ScalarExponent > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool Eigen::internal::unary_pow::exponent_helper< ScalarExponent, true >::is_odd (const safe_abs_type & exp) inline static
{
     return exp % safe_abs_type(2) != safe_abs_type(0);
   }
References Eigen::bfloat16_impl::exp().
safe_abs()
template<typename ScalarExponent > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE safe_abs_type Eigen::internal::unary_pow::exponent_helper< ScalarExponent, true >::safe_abs (const ScalarExponent & exp) inline static
{
     ScalarExponent mask = numext::signbit(exp);
     safe_abs_type result = safe_abs_type(exp ^ mask);
     return result + safe_abs_type(ScalarExponent(1) & mask);
   }
References Eigen::bfloat16_impl::exp(), and Eigen::numext::signbit().
The documentation for this struct was generated from the following file:
GenericPacketMathFunctions.h