MercuryDPM: Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, RowMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version > Struct Template Reference
Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, RowMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version > Struct Template Reference
#include <GeneralMatrixVector.h>
Public Types
typedef gemv_traits< LhsScalar, RhsScalar > Traits
typedef gemv_traits< LhsScalar, RhsScalar, GEMVPacketHalf > HalfTraits
typedef gemv_traits< LhsScalar, RhsScalar, GEMVPacketQuarter > QuarterTraits
typedef ScalarBinaryOpTraits< LhsScalar, RhsScalar >::ReturnType ResScalar
typedef Traits::LhsPacket LhsPacket
typedef Traits::RhsPacket RhsPacket
typedef Traits::ResPacket ResPacket
typedef HalfTraits::LhsPacket LhsPacketHalf
typedef HalfTraits::RhsPacket RhsPacketHalf
typedef HalfTraits::ResPacket ResPacketHalf
typedef QuarterTraits::LhsPacket LhsPacketQuarter
typedef QuarterTraits::RhsPacket RhsPacketQuarter
typedef QuarterTraits::ResPacket ResPacketQuarter
Static Public Member Functions
EIGEN_DEVICE_FUNC static EIGEN_DONT_INLINE void run (Index rows, Index cols, const LhsMapper &lhs, const RhsMapper &rhs, ResScalar *res, Index resIncr, ResScalar alpha)
Member Typedef Documentation
HalfTraits
template<typename Index , typename LhsScalar , typename LhsMapper , bool ConjugateLhs, typename RhsScalar , typename RhsMapper , bool ConjugateRhs, int Version> typedef gemv_traits<LhsScalar, RhsScalar, GEMVPacketHalf> Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, RowMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::HalfTraits
LhsPacket
template<typename Index , typename LhsScalar , typename LhsMapper , bool ConjugateLhs, typename RhsScalar , typename RhsMapper , bool ConjugateRhs, int Version> typedef Traits::LhsPacket Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, RowMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::LhsPacket
LhsPacketHalf
template<typename Index , typename LhsScalar , typename LhsMapper , bool ConjugateLhs, typename RhsScalar , typename RhsMapper , bool ConjugateRhs, int Version> typedef HalfTraits::LhsPacket Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, RowMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::LhsPacketHalf
LhsPacketQuarter
template<typename Index , typename LhsScalar , typename LhsMapper , bool ConjugateLhs, typename RhsScalar , typename RhsMapper , bool ConjugateRhs, int Version> typedef QuarterTraits::LhsPacket Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, RowMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::LhsPacketQuarter
QuarterTraits
template<typename Index , typename LhsScalar , typename LhsMapper , bool ConjugateLhs, typename RhsScalar , typename RhsMapper , bool ConjugateRhs, int Version> typedef gemv_traits<LhsScalar, RhsScalar, GEMVPacketQuarter> Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, RowMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::QuarterTraits
ResPacket
template<typename Index , typename LhsScalar , typename LhsMapper , bool ConjugateLhs, typename RhsScalar , typename RhsMapper , bool ConjugateRhs, int Version> typedef Traits::ResPacket Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, RowMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::ResPacket
ResPacketHalf
template<typename Index , typename LhsScalar , typename LhsMapper , bool ConjugateLhs, typename RhsScalar , typename RhsMapper , bool ConjugateRhs, int Version> typedef HalfTraits::ResPacket Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, RowMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::ResPacketHalf
ResPacketQuarter
template<typename Index , typename LhsScalar , typename LhsMapper , bool ConjugateLhs, typename RhsScalar , typename RhsMapper , bool ConjugateRhs, int Version> typedef QuarterTraits::ResPacket Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, RowMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::ResPacketQuarter
ResScalar
template<typename Index , typename LhsScalar , typename LhsMapper , bool ConjugateLhs, typename RhsScalar , typename RhsMapper , bool ConjugateRhs, int Version> typedef ScalarBinaryOpTraits<LhsScalar, RhsScalar>::ReturnType Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, RowMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::ResScalar
RhsPacket
template<typename Index , typename LhsScalar , typename LhsMapper , bool ConjugateLhs, typename RhsScalar , typename RhsMapper , bool ConjugateRhs, int Version> typedef Traits::RhsPacket Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, RowMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::RhsPacket
RhsPacketHalf
template<typename Index , typename LhsScalar , typename LhsMapper , bool ConjugateLhs, typename RhsScalar , typename RhsMapper , bool ConjugateRhs, int Version> typedef HalfTraits::RhsPacket Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, RowMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::RhsPacketHalf
RhsPacketQuarter
template<typename Index , typename LhsScalar , typename LhsMapper , bool ConjugateLhs, typename RhsScalar , typename RhsMapper , bool ConjugateRhs, int Version> typedef QuarterTraits::RhsPacket Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, RowMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::RhsPacketQuarter
Traits
template<typename Index , typename LhsScalar , typename LhsMapper , bool ConjugateLhs, typename RhsScalar , typename RhsMapper , bool ConjugateRhs, int Version> typedef gemv_traits<LhsScalar, RhsScalar> Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, RowMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::Traits
Member Function Documentation
run()
template<typename Index , typename LhsScalar , typename LhsMapper , bool ConjugateLhs, typename RhsScalar , typename RhsMapper , bool ConjugateRhs, int Version> EIGEN_DEVICE_FUNC EIGEN_DONT_INLINE void Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, RowMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >::run (Index rows, Index cols, const LhsMapper & lhs, const RhsMapper & rhs, ResScalar * res, Index resIncr, ResScalar alpha) static
{
   // The following copy tells the compiler that lhs's attributes are not modified outside this function
   // This helps GCC to generate proper code.
   LhsMapper lhs(alhs);
   eigen_internal_assert(rhs.stride() == 1);
   conj_helper<LhsScalar, RhsScalar, ConjugateLhs, ConjugateRhs> cj;
   conj_helper<LhsPacket, RhsPacket, ConjugateLhs, ConjugateRhs> pcj;
   conj_helper<LhsPacketHalf, RhsPacketHalf, ConjugateLhs, ConjugateRhs> pcj_half;
   conj_helper<LhsPacketQuarter, RhsPacketQuarter, ConjugateLhs, ConjugateRhs> pcj_quarter;
   // TODO: fine tune the following heuristic. The rationale is that if the matrix is very large,
   //       processing 8 rows at once might be counter productive wrt cache.
   const Index n8 = lhs.stride() * sizeof(LhsScalar) > 32000 ? 0 : rows - 7;
   const Index n4 = rows - 3;
   const Index n2 = rows - 1;
   // TODO: for padded aligned inputs, we could enable aligned reads
   enum {
     LhsAlignment = Unaligned,
     ResPacketSize = Traits::ResPacketSize,
     ResPacketSizeHalf = HalfTraits::ResPacketSize,
     ResPacketSizeQuarter = QuarterTraits::ResPacketSize,
     LhsPacketSize = Traits::LhsPacketSize,
     LhsPacketSizeHalf = HalfTraits::LhsPacketSize,
     LhsPacketSizeQuarter = QuarterTraits::LhsPacketSize,
     HasHalf = (int)ResPacketSizeHalf < (int)ResPacketSize,
     HasQuarter = (int)ResPacketSizeQuarter < (int)ResPacketSizeHalf
   };
   using UnsignedIndex = typename make_unsigned<Index>::type;
   const Index fullColBlockEnd = LhsPacketSize * (UnsignedIndex(cols) / LhsPacketSize);
   const Index halfColBlockEnd = LhsPacketSizeHalf * (UnsignedIndex(cols) / LhsPacketSizeHalf);
   const Index quarterColBlockEnd = LhsPacketSizeQuarter * (UnsignedIndex(cols) / LhsPacketSizeQuarter);
   Index i = 0;
   for (; i < n8; i += 8) {
     ResPacket c0 = pset1<ResPacket>(ResScalar(0)), c1 = pset1<ResPacket>(ResScalar(0)),
               c2 = pset1<ResPacket>(ResScalar(0)), c3 = pset1<ResPacket>(ResScalar(0)),
               c4 = pset1<ResPacket>(ResScalar(0)), c5 = pset1<ResPacket>(ResScalar(0)),
               c6 = pset1<ResPacket>(ResScalar(0)), c7 = pset1<ResPacket>(ResScalar(0));
     for (Index j = 0; j < fullColBlockEnd; j += LhsPacketSize) {
       RhsPacket b0 = rhs.template load<RhsPacket, Unaligned>(j, 0);
       c0 = pcj.pmadd(lhs.template load<LhsPacket, LhsAlignment>(i + 0, j), b0, c0);
       c1 = pcj.pmadd(lhs.template load<LhsPacket, LhsAlignment>(i + 1, j), b0, c1);
       c2 = pcj.pmadd(lhs.template load<LhsPacket, LhsAlignment>(i + 2, j), b0, c2);
       c3 = pcj.pmadd(lhs.template load<LhsPacket, LhsAlignment>(i + 3, j), b0, c3);
       c4 = pcj.pmadd(lhs.template load<LhsPacket, LhsAlignment>(i + 4, j), b0, c4);
       c5 = pcj.pmadd(lhs.template load<LhsPacket, LhsAlignment>(i + 5, j), b0, c5);
       c6 = pcj.pmadd(lhs.template load<LhsPacket, LhsAlignment>(i + 6, j), b0, c6);
       c7 = pcj.pmadd(lhs.template load<LhsPacket, LhsAlignment>(i + 7, j), b0, c7);
     }
     ResScalar cc0 = predux(c0);
     ResScalar cc1 = predux(c1);
     ResScalar cc2 = predux(c2);
     ResScalar cc3 = predux(c3);
     ResScalar cc4 = predux(c4);
     ResScalar cc5 = predux(c5);
     ResScalar cc6 = predux(c6);
     ResScalar cc7 = predux(c7);
     for (Index j = fullColBlockEnd; j < cols; ++j) {
       RhsScalar b0 = rhs(j, 0);
       cc0 += cj.pmul(lhs(i + 0, j), b0);
       cc1 += cj.pmul(lhs(i + 1, j), b0);
       cc2 += cj.pmul(lhs(i + 2, j), b0);
       cc3 += cj.pmul(lhs(i + 3, j), b0);
       cc4 += cj.pmul(lhs(i + 4, j), b0);
       cc5 += cj.pmul(lhs(i + 5, j), b0);
       cc6 += cj.pmul(lhs(i + 6, j), b0);
       cc7 += cj.pmul(lhs(i + 7, j), b0);
     }
     res[(i + 0) * resIncr] += alpha * cc0;
     res[(i + 1) * resIncr] += alpha * cc1;
     res[(i + 2) * resIncr] += alpha * cc2;
     res[(i + 3) * resIncr] += alpha * cc3;
     res[(i + 4) * resIncr] += alpha * cc4;
     res[(i + 5) * resIncr] += alpha * cc5;
     res[(i + 6) * resIncr] += alpha * cc6;
     res[(i + 7) * resIncr] += alpha * cc7;
   }
   for (; i < n4; i += 4) {
     ResPacket c0 = pset1<ResPacket>(ResScalar(0)), c1 = pset1<ResPacket>(ResScalar(0)),
               c2 = pset1<ResPacket>(ResScalar(0)), c3 = pset1<ResPacket>(ResScalar(0));
     for (Index j = 0; j < fullColBlockEnd; j += LhsPacketSize) {
       RhsPacket b0 = rhs.template load<RhsPacket, Unaligned>(j, 0);
       c0 = pcj.pmadd(lhs.template load<LhsPacket, LhsAlignment>(i + 0, j), b0, c0);
       c1 = pcj.pmadd(lhs.template load<LhsPacket, LhsAlignment>(i + 1, j), b0, c1);
       c2 = pcj.pmadd(lhs.template load<LhsPacket, LhsAlignment>(i + 2, j), b0, c2);
       c3 = pcj.pmadd(lhs.template load<LhsPacket, LhsAlignment>(i + 3, j), b0, c3);
     }
     ResScalar cc0 = predux(c0);
     ResScalar cc1 = predux(c1);
     ResScalar cc2 = predux(c2);
     ResScalar cc3 = predux(c3);
     for (Index j = fullColBlockEnd; j < cols; ++j) {
       RhsScalar b0 = rhs(j, 0);
       cc0 += cj.pmul(lhs(i + 0, j), b0);
       cc1 += cj.pmul(lhs(i + 1, j), b0);
       cc2 += cj.pmul(lhs(i + 2, j), b0);
       cc3 += cj.pmul(lhs(i + 3, j), b0);
     }
     res[(i + 0) * resIncr] += alpha * cc0;
     res[(i + 1) * resIncr] += alpha * cc1;
     res[(i + 2) * resIncr] += alpha * cc2;
     res[(i + 3) * resIncr] += alpha * cc3;
   }
   for (; i < n2; i += 2) {
     ResPacket c0 = pset1<ResPacket>(ResScalar(0)), c1 = pset1<ResPacket>(ResScalar(0));
     for (Index j = 0; j < fullColBlockEnd; j += LhsPacketSize) {
       RhsPacket b0 = rhs.template load<RhsPacket, Unaligned>(j, 0);
       c0 = pcj.pmadd(lhs.template load<LhsPacket, LhsAlignment>(i + 0, j), b0, c0);
       c1 = pcj.pmadd(lhs.template load<LhsPacket, LhsAlignment>(i + 1, j), b0, c1);
     }
     ResScalar cc0 = predux(c0);
     ResScalar cc1 = predux(c1);
     for (Index j = fullColBlockEnd; j < cols; ++j) {
       RhsScalar b0 = rhs(j, 0);
       cc0 += cj.pmul(lhs(i + 0, j), b0);
       cc1 += cj.pmul(lhs(i + 1, j), b0);
     }
     res[(i + 0) * resIncr] += alpha * cc0;
     res[(i + 1) * resIncr] += alpha * cc1;
   }
   for (; i < rows; ++i) {
     ResPacket c0 = pset1<ResPacket>(ResScalar(0));
     ResPacketHalf c0_h = pset1<ResPacketHalf>(ResScalar(0));
     ResPacketQuarter c0_q = pset1<ResPacketQuarter>(ResScalar(0));
     for (Index j = 0; j < fullColBlockEnd; j += LhsPacketSize) {
       RhsPacket b0 = rhs.template load<RhsPacket, Unaligned>(j, 0);
       c0 = pcj.pmadd(lhs.template load<LhsPacket, LhsAlignment>(i, j), b0, c0);
     }
     ResScalar cc0 = predux(c0);
     if (HasHalf) {
       for (Index j = fullColBlockEnd; j < halfColBlockEnd; j += LhsPacketSizeHalf) {
         RhsPacketHalf b0 = rhs.template load<RhsPacketHalf, Unaligned>(j, 0);
         c0_h = pcj_half.pmadd(lhs.template load<LhsPacketHalf, LhsAlignment>(i, j), b0, c0_h);
       }
       cc0 += predux(c0_h);
     }
     if (HasQuarter) {
       for (Index j = halfColBlockEnd; j < quarterColBlockEnd; j += LhsPacketSizeQuarter) {
         RhsPacketQuarter b0 = rhs.template load<RhsPacketQuarter, Unaligned>(j, 0);
         c0_q = pcj_quarter.pmadd(lhs.template load<LhsPacketQuarter, LhsAlignment>(i, j), b0, c0_q);
       }
       cc0 += predux(c0_q);
     }
     for (Index j = quarterColBlockEnd; j < cols; ++j) {
       cc0 += cj.pmul(lhs(i, j), rhs(j, 0));
     }
     res[i * resIncr] += alpha * cc0;
   }
 }
References alpha, cols, eigen_internal_assert, i, int(), j, Eigen::internal::conj_helper< LhsType, RhsType, ConjLhs, ConjRhs >::pmadd(), Eigen::internal::conj_helper< LhsType, RhsType, ConjLhs, ConjRhs >::pmul(), Eigen::internal::predux(), res, rows, compute_granudrum_aor::type, and Eigen::Unaligned.
The documentation for this struct was generated from the following file:
GeneralMatrixVector.h