MercuryDPM: Eigen::DeviceWrapper< Derived, Device > Struct Template Reference
Eigen::DeviceWrapper< Derived, Device > Struct Template Reference
#include <DeviceWrapper.h>
Public Types
using Base = EigenBase< internal::remove_all_t< Derived > >
using Scalar = typename Derived::Scalar
Public Member Functions
EIGEN_DEVICE_FUNC DeviceWrapper (Base &xpr, Device &device)
EIGEN_DEVICE_FUNC DeviceWrapper (const Base &xpr, Device &device)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator+= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator-= (const EigenBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & derived ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Device & device ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE NoAlias< DeviceWrapper, EigenBase > noalias ()
Public Attributes
Derived & m_xpr
Device & m_device
Member Typedef Documentation
Base
template<typename Derived , typename Device > using Eigen::DeviceWrapper< Derived, Device >::Base = EigenBase<internal::remove_all_t<Derived> >
Scalar
template<typename Derived , typename Device > using Eigen::DeviceWrapper< Derived, Device >::Scalar = typename Derived::Scalar
Constructor & Destructor Documentation
DeviceWrapper() [1/2]
template<typename Derived , typename Device > EIGEN_DEVICE_FUNC Eigen::DeviceWrapper< Derived, Device >::DeviceWrapper (Base & xpr, Device & device) inline
 : m_xpr(xpr.derived()), m_device(device) {}
DeviceWrapper() [2/2]
template<typename Derived , typename Device > EIGEN_DEVICE_FUNC Eigen::DeviceWrapper< Derived, Device >::DeviceWrapper (const Base & xpr, Device & device) inline
 : m_xpr(xpr.derived()), m_device(device) {}
Member Function Documentation
derived()
template<typename Derived , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived& Eigen::DeviceWrapper< Derived, Device >::derived () inline
 { return m_xpr; }
References Eigen::DeviceWrapper< Derived, Device >::m_xpr.
Referenced by Eigen::internal::call_assignment_no_alias().
device()
template<typename Derived , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Device& Eigen::DeviceWrapper< Derived, Device >::device () inline
 { return m_device; }
References Eigen::DeviceWrapper< Derived, Device >::m_device.
noalias()
template<typename Derived , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE NoAlias<DeviceWrapper, EigenBase> Eigen::DeviceWrapper< Derived, Device >::noalias () inline
{
     return NoAlias<DeviceWrapper, EigenBase>(*this);
   }
operator+=()
template<typename Derived , typename Device > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived& Eigen::DeviceWrapper< Derived, Device >::operator+= (const EigenBase< OtherDerived > & other) inline
{
     using AddAssignOp = internal::add_assign_op<Scalar, typename OtherDerived::Scalar>;
     internal::call_assignment(*this, other.derived(), AddAssignOp());
     return m_xpr;
   }
References Eigen::internal::call_assignment(), Eigen::EigenBase< Derived >::derived(), and Eigen::DeviceWrapper< Derived, Device >::m_xpr.
operator-=()
template<typename Derived , typename Device > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived& Eigen::DeviceWrapper< Derived, Device >::operator-= (const EigenBase< OtherDerived > & other) inline
{
     using SubAssignOp = internal::sub_assign_op<Scalar, typename OtherDerived::Scalar>;
     internal::call_assignment(*this, other.derived(), SubAssignOp());
     return m_xpr;
   }
References Eigen::internal::call_assignment(), Eigen::EigenBase< Derived >::derived(), and Eigen::DeviceWrapper< Derived, Device >::m_xpr.
operator=()
template<typename Derived , typename Device > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived& Eigen::DeviceWrapper< Derived, Device >::operator= (const EigenBase< OtherDerived > & other) inline
{
     using AssignOp = internal::assign_op<Scalar, typename OtherDerived::Scalar>;
     internal::call_assignment(*this, other.derived(), AssignOp());
     return m_xpr;
   }
References Eigen::internal::call_assignment(), Eigen::EigenBase< Derived >::derived(), and Eigen::DeviceWrapper< Derived, Device >::m_xpr.
Member Data Documentation
m_device
template<typename Derived , typename Device > Device& Eigen::DeviceWrapper< Derived, Device >::m_device
Referenced by Eigen::DeviceWrapper< Derived, Device >::device().
m_xpr
template<typename Derived , typename Device > Derived& Eigen::DeviceWrapper< Derived, Device >::m_xpr
Referenced by Eigen::DeviceWrapper< Derived, Device >::derived(), Eigen::DeviceWrapper< Derived, Device >::operator+=(), Eigen::DeviceWrapper< Derived, Device >::operator-=(), and Eigen::DeviceWrapper< Derived, Device >::operator=().
The documentation for this struct was generated from the following file:
DeviceWrapper.h