MercuryDPM: Thermal< Particle > Class Template Reference
Thermal< Particle > Class Template Reference
#include <ThermalParticle.h>
Public Member Functions
Thermal ()
Basic Particle constructor, creates a particle at (0,0,0) with radius, mass and inertia equal to 1.
Thermal (const Thermal &p)
Particle copy constructor, which accepts as input a reference to a Particle. It creates a copy of this Particle and all it's information. Usually it is better to use the copy() function for polymorphism.
~Thermal () override=default
Particle destructor, needs to be implemented and checked if it removes tangential spring information.
Thermal * copy () const override
Particle copy method. It calls to copy constructor of this Particle, useful for polymorfism.
void write (std::ostream &os) const override
std::string getName () const override
void read (std::istream &is) override
Mdouble getTemperature () const
void setTemperature (Mdouble temperature)
void addTemperature (Mdouble temperature)
void setTemperatureDependentDensity (const std::function< double(double)> &temperatureDependentDensity)
const std::function< double(double)> & getTemperatureDependentDensity () const
const std::function< double(double)> & getTimeDependentTemperature () const
void setTimeDependentTemperature (const std::function< double(double)> &timeDependentTemperature)
void actionsAfterTimeStep () override
bool isSphericalParticle () const override
Protected Attributes
Mdouble temperature_
Private Attributes
std::function< double(double temperature)> timeDependentTemperature_
Constructor & Destructor Documentation
Thermal() [1/2]
template<class Particle > Thermal< Particle >::Thermal () inline
Basic Particle constructor, creates a particle at (0,0,0) with radius, mass and inertia equal to 1.
default constructor
     {
         temperature_ = 0;
         //temperatureDependentDensity_
     }
References Thermal< Particle >::temperature_.
Referenced by Thermal< Particle >::copy().
Thermal() [2/2]
template<class Particle > Thermal< Particle >::Thermal (const Thermal< Particle > & p) inline
Particle copy constructor, which accepts as input a reference to a Particle. It creates a copy of this Particle and all it's information. Usually it is better to use the copy() function for polymorphism.
Constructor that copies most of the properties of the given particle. Please note that not everything is copied, for example the position in the HGrid is not determined yet by the end of this constructor. It also does not copy the interactions and the pointer to the handler that handles this particle. Use with care.
Parameters
[in,out] p Reference to the Thermal this one should become a copy of.
                               : Particle(p)
     {
         temperature_ = p.temperature_;
         timeDependentTemperature_ = p.timeDependentTemperature_;
     }
References p, Thermal< Particle >::temperature_, and Thermal< Particle >::timeDependentTemperature_.
~Thermal()
template<class Particle > Thermal< Particle >::~Thermal () override default
Particle destructor, needs to be implemented and checked if it removes tangential spring information.
Destructor. It asks the ParticleHandler to check if this was the smallest or largest particle and adjust itself accordingly.
Member Function Documentation
actionsAfterTimeStep()
template<class Particle > void Thermal< Particle >::actionsAfterTimeStep override
 {
     // reset temperature_ if timeDependentTemperature_ function is provided
     if (timeDependentTemperature_)
     {
         temperature_ = timeDependentTemperature_(this->getHandler()->getDPMBase()->getTime());
     }
     // reset density and radius if getTemperatureDependentDensity function is provided
     if (this->getSpecies()->getTemperatureDependentDensity())
     {
         const Mdouble density = this->getSpecies()->getTemperatureDependentDensity()(temperature_);
         this->radius_ = this->getRadius() * cbrt(this->getMass() / (this->getVolume() * density));
     }
     /* Compute temperature change due to heat convection with the ambient fluid */
     this->getSpecies()->actionsAfterTimeStep(this);
 }
References Eigen::numext::cbrt(), and UniformPSDSelfTest::density.
addTemperature()
template<class Particle > void Thermal< Particle >::addTemperature (Mdouble temperature) inline
     {
         temperature_ += temperature;
         logger.assert_debug(temperature_>0, "Temperature has to be positive");
     }
References logger, and Thermal< Particle >::temperature_.
Referenced by MeltableParticle::actionsAfterTimeStep(), and ThermalInteraction< NormalForceInteraction >::computeNormalForce().
copy()
template<class Particle > Thermal* Thermal< Particle >::copy () const inline override
Particle copy method. It calls to copy constructor of this Particle, useful for polymorfism.
Copy method. Uses copy constructor to create a copy on the heap. Useful for polymorphism.
Returns
pointer to the particle's copy
     {
         return new Thermal(*this);
     }
References Thermal< Particle >::Thermal().
getName()
template<class Particle > std::string Thermal< Particle >::getName () const inline override
     {
         return "Thermal" + Particle::getName();
     }
References getName().
getTemperature()
template<class Particle > Mdouble Thermal< Particle >::getTemperature () const inline
     {
         return temperature_;
     }
References Thermal< Particle >::temperature_.
Referenced by MeltableParticle::actionsAfterTimeStep(), MeltableParticle::actionsBeforeTimeStep(), SinterInteraction::computeNormalForce(), and ThermalInteraction< NormalForceInteraction >::computeNormalForce().
getTemperatureDependentDensity()
template<class Particle > const std::function<double(double)>& Thermal< Particle >::getTemperatureDependentDensity () const
getTimeDependentTemperature()
template<class Particle > const std::function<double(double)>& Thermal< Particle >::getTimeDependentTemperature () const inline
     {
         return timeDependentTemperature_;
     }
References Thermal< Particle >::timeDependentTemperature_.
isSphericalParticle()
template<class Particle > bool Thermal< Particle >::isSphericalParticle () const inline override
 {return true;}
read()
template<class Particle > void Thermal< Particle >::read (std::istream & is) override
Particle read function. Has an std::istream as argument, from which it extracts the radius_, invMass_ and invInertia_, respectively. From these the mass_ and inertia_ are deduced. An additional set of properties is read through the call to the parent's method BaseParticle::read().
Parameters
[in,out] is input stream with particle properties.
 {
     Particle::read(is);
     std::string dummy;
     is >> dummy >> temperature_;
 }
References Eigen::TensorSycl::internal::read(), and oomph::Global_string_for_annotation::string().
setTemperature()
template<class Particle > void Thermal< Particle >::setTemperature (Mdouble temperature) inline
     {
         logger.assert_debug(temperature>0, "Temperature has to be positive");
         temperature_ = temperature;
     }
References logger, and Thermal< Particle >::temperature_.
Referenced by HeatTransferUnitTest::setupInitialConditions().
setTemperatureDependentDensity()
template<class Particle > void Thermal< Particle >::setTemperatureDependentDensity (const std::function< double(double)> & temperatureDependentDensity)
setTimeDependentTemperature()
template<class Particle > void Thermal< Particle >::setTimeDependentTemperature (const std::function< double(double)> & timeDependentTemperature)
 {
     timeDependentTemperature_ = timeDependentTemperature;
     temperature_ = timeDependentTemperature(0);
     logger(INFO, "Setting initial temperature to %", temperature_);
 }
References INFO, and logger.
write()
template<class Particle > void Thermal< Particle >::write (std::ostream & os) const inline override
Thermal print method, which accepts an os std::ostream as input. It prints human readable Thermal information to the std::ostream.
Parameters
[in,out] os stream to which the info is written
     {
         Particle::write(os);
         os << " temperature " << temperature_;
     }
References Thermal< Particle >::temperature_, and Eigen::TensorSycl::internal::write().
Member Data Documentation
temperature_
template<class Particle > Mdouble Thermal< Particle >::temperature_ protected
Referenced by Thermal< Particle >::addTemperature(), MeltableParticle::getFieldVTK(), MeltableParticle::getSolidRadius(), Thermal< Particle >::getTemperature(), Thermal< Particle >::setTemperature(), Thermal< Particle >::Thermal(), and Thermal< Particle >::write().
timeDependentTemperature_
template<class Particle > std::function<double(double temperature)> Thermal< Particle >::timeDependentTemperature_ private
Change this function to let the temperature be time-dependent.
Referenced by Thermal< Particle >::getTimeDependentTemperature(), and Thermal< Particle >::Thermal().
The documentation for this class was generated from the following file:
ThermalParticle.h