MercuryDPM: pseudo_solid_collapsible_tube.cc File Reference
mpi/multi_domain/pseudo_solid_collapsible_tube/pseudo_solid_collapsible_tube.cc File Reference
#include "generic.h"
#include "solid.h"
#include "constitutive.h"
#include "navier_stokes.h"
#include "multi_physics.h"
#include "meshes/simple_cubic_mesh.h"
#include "meshes/quarter_tube_mesh.h"
Classes
class oomph::PseudoElasticBulkElement< ELEMENT >
class oomph::FaceGeometry< PseudoElasticBulkElement< ELEMENT > >
FaceGeometry of wrapped element is the same as the underlying element.
class WallMesh< ELEMENT >
class FluidMesh< ELEMENT >
class PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >
Namespaces
oomph
DRAIG: Change all instances of (SPATIAL_DIM) to (DIM-1).
Global_Parameters
Namespace for global parameters.
Functions
void Global_Parameters::press_load (const Vector< double > &xi, const Vector< double > &x, const Vector< double > &N, Vector< double > &load)
Load function for wall.
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
///////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////// Demonstrate how to solve a 3D FSI problem with pseudo-solid node update for the fluid mesh.
 {
 #ifdef OOMPH_HAS_MPI
    MPI_Helpers::init(argc,argv);
 #endif
  // Switch off output modifier
  oomph_info.output_modifier_pt() = &default_output_modifier;
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Doc info
  DocInfo doc_info;
  // Use separate directory for output from each processor
  std::ostringstream dir_name;
  dir_name << "RESLT_proc" << MPI_Helpers::communicator_pt()->my_rank();
  doc_info.set_directory(dir_name.str());
  // Define processor-labeled output file for all on-screen stuff
  std::ofstream output_stream;
  char filename[1000];
 #ifdef OOMPH_HAS_MPI
  sprintf(filename,"%s/OUTPUT.%i",doc_info.directory().c_str(),
          MPI_Helpers::communicator_pt()->my_rank());
 #else
  sprintf(filename,"%s/OUTPUT.%i",doc_info.directory().c_str(),0);
 #endif
  output_stream.open(filename);
  oomph_info.stream_pt() = &output_stream;
  OomphLibWarning::set_stream_pt(&output_stream);
  OomphLibError::set_stream_pt(&output_stream);
  // Define possible command line arguments and parse the ones that
  // were actually specified
  // Validation run?
  CommandLineArgs::specify_command_line_flag("--validate");
  // Use iterative solver?
  CommandLineArgs::specify_command_line_flag("--use_iterative_solver");
  // Doc available command line flags
  CommandLineArgs::doc_available_flags();
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  // Create generalised Hookean constitutive equations
  Global_Parameters::Constitutive_law_wall_pt =
   new GeneralisedHookean(&Global_Parameters::Nu_wall);
 Global_Parameters::Constitutive_law_pseudo_elastic_pt =
   new GeneralisedHookean(&Global_Parameters::Nu_pseudo_elastic);
 //Set up the problem
 PseudoElasticCollapsibleChannelProblem
  <RefineablePseudoSolidNodeUpdateElement
   <RefineableQTaylorHoodElement<3>,
    PseudoElasticBulkElement<RefineableQPVDElement<3,3> > >,
   RefineableQPVDElement<3,3> >  problem;
 #ifdef OOMPH_HAS_MPI
  // Distribute the problem
  oomph_info << "Problem is being distributed." << std::endl;
  // Validation: manufacture distribution so that domain is split in two in a
  // controllable way
  if (CommandLineArgs::command_line_flag_has_been_set("--validate"))
   {
    unsigned nel=problem.mesh_pt()->nelement();
    Vector<unsigned> element_partition(nel);
    for (unsigned e=0;e<nel;e++)
     {
      if (problem.mesh_pt()->finite_element_pt(e)->node_pt(0)->x(2)<
          0.5*Global_Parameters::L)
       {
        element_partition[e]=0;
       }
      else
       {
        element_partition[e]=1;
       }
     }
    problem.distribute(element_partition);
   }
  // Use METIS to determine the partitioning
  else
   {
    problem.distribute();
   }
  oomph_info << "Problem has been distributed." << std::endl;
 #endif
  // Doc initial configuration
  problem.doc_solution(doc_info);
  oomph_info << "Before manual refine: doc_info.number()="
             << doc_info.number() << std::endl;
  doc_info.number()++;
  // Do manual non-uniform refinement
  if (CommandLineArgs::command_line_flag_has_been_set("--validate"))
   {
    problem.adapt();
   }
  // Doc afterwards
  problem.doc_solution(doc_info);
  oomph_info << "After manual refine: doc_info.number()="
             << doc_info.number() << std::endl;
  doc_info.number()++;
  // Setup timestepping
  double dt = Global_Parameters::T/double(Global_Parameters::Nstep_per_period);
  Global_Parameters::Dt=dt;
  problem.initialise_dt(dt);
  problem.set_initial_condition();
  // Switch solver if required
  if (CommandLineArgs::command_line_flag_has_been_set("--use_iterative_solver"))
   {
    oomph_info << "switching to iterative solver\n";
    problem.set_pseudo_elastic_fsi_solver();
   }
  else
   {
    oomph_info << "Using direct solver\n";
   }
  // Steady run
  problem.steady_run(doc_info);
  // Unteady run
  problem.unsteady_run(doc_info);
 #ifdef OOMPH_HAS_MPI
  MPI_Helpers::finalize();
 #endif
 } // end_of_main
References oomph::CommandLineArgs::command_line_flag_has_been_set(), Global_Parameters::Constitutive_law_pseudo_elastic_pt, Global_Parameters::Constitutive_law_wall_pt, oomph::default_output_modifier, oomph::DocInfo::directory(), oomph::CommandLineArgs::doc_available_flags(), oomph::CommandLineArgs::doc_specified_flags(), Global_Parameters::Dt, e(), MergeRestartFiles::filename, Global_Parameters::L, Global_Parameters::Nstep_per_period, Global_Parameters::Nu_pseudo_elastic, Global_Parameters::Nu_wall, oomph::DocInfo::number(), oomph::oomph_info, oomph::OomphInfo::output_modifier_pt(), oomph::CommandLineArgs::parse_and_assign(), problem, oomph::DocInfo::set_directory(), Flag_definition::setup(), oomph::CommandLineArgs::specify_command_line_flag(), oomph::OomphInfo::stream_pt(), and Global_Parameters::T.