MercuryDPM: oomph::NavierStokesSurfacePowerElement< ELEMENT > Class Template Reference
oomph::NavierStokesSurfacePowerElement< ELEMENT > Class Template Reference
#include <navier_stokes_surface_power_elements.h>
Public Member Functions
NavierStokesSurfacePowerElement (FiniteElement *const &element_pt, const int &face_index)
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
Vector< double > drag_force ()
Get drag force (traction acting on fluid)
Vector< double > drag_force (std::ofstream &outfile)
double get_rate_of_traction_work ()
double get_rate_of_traction_work (std::ofstream &outfile)
void get_rate_of_traction_work_components (double &rate_of_work_integral_p, double &rate_of_work_integral_n, double &rate_of_work_integral_t)
void get_rate_of_traction_work_components (std::ofstream &outfile, double &rate_of_work_integral_p, double &rate_of_work_integral_n, double &rate_of_work_integral_t)
double get_kinetic_energy_flux ()
Get integral of kinetic energy flux.
double get_kinetic_energy_flux (std::ofstream &outfile)
Get integral of kinetic energy flux and doc.
double get_volume_flux ()
Get integral of volume flux.
double get_volume_flux (std::ofstream &outfile)
Get integral of volume flux and doc.
Public Member Functions inherited from oomph::FaceElement
FaceElement ()
Constructor: Initialise all appropriate member data.
virtual ~FaceElement ()
Empty virtual destructor.
FaceElement (const FaceElement &)=delete
Broken copy constructor.
const unsigned & boundary_number_in_bulk_mesh () const
Broken assignment operator.
void set_boundary_number_in_bulk_mesh (const unsigned &b)
Set function for the boundary number in bulk mesh.
double J_eulerian (const Vector< double > &s) const
double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
double interpolated_x (const Vector< double > &s, const unsigned &i) const
double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
void interpolated_x (const Vector< double > &s, Vector< double > &x) const
void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
int & normal_sign ()
int normal_sign () const
int & face_index ()
int face_index () const
const Vector< double > * tangent_direction_pt () const
Public access function for the tangent direction pointer.
void set_tangent_direction (Vector< double > *tangent_direction_pt)
Set the tangent direction vector.
void turn_on_warning_for_discontinuous_tangent ()
void turn_off_warning_for_discontinuous_tangent ()
void continuous_tangent_and_outer_unit_normal (const Vector< double > &s, Vector< Vector< double >> &tang_vec, Vector< double > &unit_normal) const
void continuous_tangent_and_outer_unit_normal (const unsigned &ipt, Vector< Vector< double >> &tang_vec, Vector< double > &unit_normal) const
void outer_unit_normal (const Vector< double > &s, Vector< double > &unit_normal) const
Compute outer unit normal at the specified local coordinate.
void outer_unit_normal (const unsigned &ipt, Vector< double > &unit_normal) const
Compute outer unit normal at ipt-th integration point.
FiniteElement *& bulk_element_pt ()
Pointer to higher-dimensional "bulk" element.
FiniteElement * bulk_element_pt () const
Pointer to higher-dimensional "bulk" element (const version)
CoordinateMappingFctPt & face_to_bulk_coordinate_fct_pt ()
CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt () const
BulkCoordinateDerivativesFctPt & bulk_coordinate_derivatives_fct_pt ()
BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt () const
Vector< double > local_coordinate_in_bulk (const Vector< double > &s) const
void get_local_coordinate_in_bulk (const Vector< double > &s, Vector< double > &s_bulk) const
void get_ds_bulk_ds_face (const Vector< double > &s, DenseMatrix< double > &dsbulk_dsface, unsigned &interior_direction) const
unsigned & bulk_position_type (const unsigned &i)
const unsigned & bulk_position_type (const unsigned &i) const
void bulk_node_number_resize (const unsigned &i)
Resize the storage for the bulk node numbers.
unsigned & bulk_node_number (const unsigned &n)
const unsigned & bulk_node_number (const unsigned &n) const
void bulk_position_type_resize (const unsigned &i)
Resize the storage for bulk_position_type to i entries.
unsigned & nbulk_value (const unsigned &n)
unsigned nbulk_value (const unsigned &n) const
void nbulk_value_resize (const unsigned &i)
void resize_nodes (Vector< unsigned > &nadditional_data_values)
void output_zeta (std::ostream &outfile, const unsigned &nplot)
Output boundary coordinate zeta.
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
virtual void disable_ALE ()
virtual void enable_ALE ()
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual unsigned nvertex_node () const
virtual Node * vertex_node_pt (const unsigned &j) const
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (std::ostream &outfile)
virtual void output (std::ostream &outfile, const unsigned &n_plot)
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output (FILE *file_pt)
virtual void output (FILE *file_pt, const unsigned &n_plot)
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output an exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output a time-dependent exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Private Attributes
unsigned Dim
The highest dimension of the problem.
Additional Inherited Members
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Protected Member Functions inherited from oomph::FaceElement
void add_additional_values (const Vector< unsigned > &nadditional_values, const unsigned &id)
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
virtual void fill_in_contribution_to_residuals (Vector< double > &residuals)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Attributes inherited from oomph::FaceElement
unsigned Boundary_number_in_bulk_mesh
The boundary number in the bulk mesh to which this element is attached.
FiniteElement * Bulk_element_pt
Pointer to the associated higher-dimensional "bulk" element.
Vector< unsigned > Bulk_node_number
Vector< unsigned > Nbulk_value
Vector< double > * Tangent_direction_pt
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
template<class ELEMENT>
class oomph::NavierStokesSurfacePowerElement< ELEMENT >
A class of elements that allow the determination of the power input and various other fluxes over the domain boundaries. The element operates as a FaceElement and attaches itself to a bulk element of the type specified by the template argument.
Constructor & Destructor Documentation
NavierStokesSurfacePowerElement()
template<class ELEMENT > oomph::NavierStokesSurfacePowerElement< ELEMENT >::NavierStokesSurfacePowerElement (FiniteElement *const & element_pt, const int & face_index) inline
Constructor, which takes a "bulk" element and the value of the index and its limit
       : FaceGeometry<ELEMENT>(), FaceElement()
     {
       // Attach the geometrical information to the element. N.B. This function
       // also assigns nbulk_value from the required_nvalue of the bulk element
       element_pt->build_face_element(face_index, this);
       // Set the dimension from the dimension of the first node
       Dim = node_pt(0)->ndim();
     }
References oomph::FiniteElement::build_face_element(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::Dim, oomph::FaceElement::face_index(), oomph::Node::ndim(), and oomph::FiniteElement::node_pt().
Member Function Documentation
drag_force() [1/2]
template<class ELEMENT > Vector<double> oomph::NavierStokesSurfacePowerElement< ELEMENT >::drag_force () inline
Get drag force (traction acting on fluid)
     {
       std::ofstream dummy_file;
       return drag_force(dummy_file);
     }
drag_force() [2/2]
template<class ELEMENT > Vector<double> oomph::NavierStokesSurfacePowerElement< ELEMENT >::drag_force (std::ofstream & outfile) inline
Get drag force (traction acting on fluid) Doc in outfile.
     {
       // Spatial dimension of element
       unsigned ndim = dim();
       // Initialise
       Vector<double> drag(ndim + 1, 0.0);
       // Vector of local coordinates in face element
       Vector<double> s(ndim);
       // Vector for global Eulerian coordinates
       Vector<double> x(ndim + 1);
       // Vector for local coordinates in bulk element
       Vector<double> s_bulk(ndim + 1);
       // Set the value of n_intpt
       unsigned n_intpt = integral_pt()->nweight();
       // Get pointer to assocated bulk element
       ELEMENT* bulk_el_pt = dynamic_cast<ELEMENT*>(bulk_element_pt());
       // Hacky: This is only appropriate for 3 point integration of
       // 1D line elements
       if (outfile.is_open()) outfile << "ZONE I=3" << std::endl;
       // Loop over the integration points
       for (unsigned ipt = 0; ipt < n_intpt; ipt++)
       {
         // Assign values of s in FaceElement and local coordinates in bulk
         // element
         for (unsigned i = 0; i < ndim; i++)
         {
           s[i] = integral_pt()->knot(ipt, i);
         }
         // Get the bulk coordinates
         this->get_local_coordinate_in_bulk(s, s_bulk);
         // Get the integral weight
         double w = integral_pt()->weight(ipt);
         // Get jacobian of mapping
         double J = J_eulerian(s);
         // Premultiply the weights and the Jacobian
         double W = w * J;
         // Get x position as Vector
         interpolated_x(s, x);
 #ifdef PARANOID
         // Get x position as Vector from bulk element
         Vector<double> x_bulk(ndim + 1);
         bulk_el_pt->interpolated_x(s_bulk, x_bulk);
         double max_legal_error = 1.0e-5;
         double error = 0.0;
         for (unsigned i = 0; i < ndim + 1; i++)
         {
           error += fabs(x[i] - x_bulk[i]);
         }
         if (error > max_legal_error)
         {
           std::ostringstream error_stream;
           error_stream << "difference in Eulerian posn from bulk and face: "
                        << error << " exceeds threshold " << max_legal_error
                        << std::endl;
           throw OomphLibError(error_stream.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
 #endif
         // Outer unit normal
         Vector<double> normal(ndim + 1);
         outer_unit_normal(s, normal);
         // Get velocity from bulk element
         Vector<double> veloc(ndim + 1);
         bulk_el_pt->interpolated_u_nst(s_bulk, veloc);
         // Get traction from bulk element
         Vector<double> traction(ndim + 1);
         bulk_el_pt->get_traction(s_bulk, normal, traction);
         // Integrate
         for (unsigned i = 0; i < ndim + 1; i++)
         {
           drag[i] += traction[i] * W;
         }
         if (outfile.is_open())
         {
           // Output x,y,...,
           for (unsigned i = 0; i < ndim + 1; i++)
           {
             outfile << x[i] << " ";
           }
           // Output traction
           for (unsigned i = 0; i < ndim + 1; i++)
           {
             outfile << traction[i] << " ";
           }
           // Output normal
           for (unsigned i = 0; i < ndim + 1; i++)
           {
             outfile << normal[i] << " ";
           }
           outfile << std::endl;
         }
       }
       return drag;
     }
References oomph::FaceElement::bulk_element_pt(), oomph::FiniteElement::dim(), calibrate::error, boost::multiprecision::fabs(), oomph::FaceElement::get_local_coordinate_in_bulk(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), J, oomph::FaceElement::J_eulerian(), oomph::Integral::knot(), oomph::GeomObject::ndim(), WallFunction::normal(), oomph::Integral::nweight(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::FaceElement::outer_unit_normal(), s, w, oomph::QuadTreeNames::W, oomph::Integral::weight(), and plotDoE::x.
get_kinetic_energy_flux() [1/2]
template<class ELEMENT > double oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_kinetic_energy_flux () inline
Get integral of kinetic energy flux.
     {
       std::ofstream dummy_file;
       return get_kinetic_energy_flux(dummy_file);
     }
get_kinetic_energy_flux() [2/2]
template<class ELEMENT > double oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_kinetic_energy_flux (std::ofstream & outfile) inline
Get integral of kinetic energy flux and doc.
     {
       // Initialise
       double kinetic_energy_flux_integral = 0.0;
       // Spatial dimension of element
       unsigned ndim = dim();
       // Vector of local coordinates in face element
       Vector<double> s(ndim);
       // Vector for global Eulerian coordinates
       Vector<double> x(ndim + 1);
       // Vector for local coordinates in bulk element
       Vector<double> s_bulk(ndim + 1);
       // Set the value of n_intpt
       unsigned n_intpt = integral_pt()->nweight();
       // Get pointer to assocated bulk element
       ELEMENT* bulk_el_pt = dynamic_cast<ELEMENT*>(bulk_element_pt());
       // Hacky: This is only appropriate for 3x3 integration of
       // 2D quad elements
       if (outfile.is_open()) outfile << "ZONE I=3, J=3" << std::endl;
       // Loop over the integration points
       for (unsigned ipt = 0; ipt < n_intpt; ipt++)
       {
         // Assign values of s in FaceElement and local coordinates in bulk
         // element
         for (unsigned i = 0; i < ndim; i++)
         {
           s[i] = integral_pt()->knot(ipt, i);
         }
         // Get the bulk coordinates
         this->get_local_coordinate_in_bulk(s, s_bulk);
         // Get the integral weight
         double w = integral_pt()->weight(ipt);
         // Get jacobian of mapping
         double J = J_eulerian(s);
         // Premultiply the weights and the Jacobian
         double W = w * J;
         // Get x position as Vector
         interpolated_x(s, x);
 #ifdef PARANOID
         // Get x position as Vector from bulk element
         Vector<double> x_bulk(ndim + 1);
         bulk_el_pt->interpolated_x(s_bulk, x_bulk);
         double max_legal_error = 1.0e-5;
         double error = 0.0;
         for (unsigned i = 0; i < ndim + 1; i++)
         {
           error += fabs(x[i] - x_bulk[i]);
         }
         if (error > max_legal_error)
         {
           std::ostringstream error_stream;
           error_stream << "difference in Eulerian posn from bulk and face: "
                        << error << " exceeds threshold " << max_legal_error
                        << std::endl;
           throw OomphLibError(error_stream.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
 #endif
         // Outer unit normal
         Vector<double> normal(ndim + 1);
         outer_unit_normal(s, normal);
         // Get velocity from bulk element
         Vector<double> veloc(ndim + 1);
         bulk_el_pt->interpolated_u_nst(s_bulk, veloc);
         double kin_energy = 0.0;
         for (unsigned i = 0; i < ndim + 1; i++)
         {
           kin_energy += veloc[i] * veloc[i];
         }
         kin_energy *= 0.5;
         // Kinetic energy flux
         double kin_energy_flux = 0.0;
         for (unsigned i = 0; i < ndim + 1; i++)
         {
           kin_energy_flux += kin_energy * normal[i] * veloc[i];
         }
         // Add to integral
         kinetic_energy_flux_integral += kin_energy_flux * W;
         if (outfile.is_open())
         {
           // Output x,y,...,
           for (unsigned i = 0; i < ndim + 1; i++)
           {
             outfile << x[i] << " ";
           }
           // Output veloc
           for (unsigned i = 0; i < ndim + 1; i++)
           {
             outfile << veloc[i] << " ";
           }
           // Output normal
           for (unsigned i = 0; i < ndim + 1; i++)
           {
             outfile << normal[i] << " ";
           }
           // Output local kin energy flux
           outfile << kin_energy_flux << " ";
           outfile << std::endl;
         }
       }
       return kinetic_energy_flux_integral;
     }
References oomph::FaceElement::bulk_element_pt(), oomph::FiniteElement::dim(), calibrate::error, boost::multiprecision::fabs(), oomph::FaceElement::get_local_coordinate_in_bulk(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), J, oomph::FaceElement::J_eulerian(), oomph::Integral::knot(), oomph::GeomObject::ndim(), WallFunction::normal(), oomph::Integral::nweight(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::FaceElement::outer_unit_normal(), s, w, oomph::QuadTreeNames::W, oomph::Integral::weight(), and plotDoE::x.
get_rate_of_traction_work() [1/2]
template<class ELEMENT > double oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_rate_of_traction_work () inline
Get integral of instantaneous rate of work done by the traction that's exerted onto the fluid.
     {
       std::ofstream dummy_file;
       return get_rate_of_traction_work(dummy_file);
     }
get_rate_of_traction_work() [2/2]
template<class ELEMENT > double oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_rate_of_traction_work (std::ofstream & outfile) inline
Get integral of instantaneous rate of work done by the traction that's exerted onto the fluid. Doc in outfile.
     {
       // Initialise
       double rate_of_work_integral = 0.0;
       // Spatial dimension of element
       unsigned ndim = dim();
       // Vector of local coordinates in face element
       Vector<double> s(ndim);
       // Vector for global Eulerian coordinates
       Vector<double> x(ndim + 1);
       // Vector for local coordinates in bulk element
       Vector<double> s_bulk(ndim + 1);
       // Set the value of n_intpt
       unsigned n_intpt = integral_pt()->nweight();
       // Get pointer to assocated bulk element
       ELEMENT* bulk_el_pt = dynamic_cast<ELEMENT*>(bulk_element_pt());
       // Hacky: This is only appropriate for 3x3 integration of
       // 2D quad elements
       if (outfile.is_open()) outfile << "ZONE I=3, J=3" << std::endl;
       // Loop over the integration points
       for (unsigned ipt = 0; ipt < n_intpt; ipt++)
       {
         // Assign values of s in FaceElement and local coordinates in bulk
         // element
         for (unsigned i = 0; i < ndim; i++)
         {
           s[i] = integral_pt()->knot(ipt, i);
         }
         // Get the bulk coordinates
         this->get_local_coordinate_in_bulk(s, s_bulk);
         // Get the integral weight
         double w = integral_pt()->weight(ipt);
         // Get jacobian of mapping
         double J = J_eulerian(s);
         // Premultiply the weights and the Jacobian
         double W = w * J;
         // Get x position as Vector
         interpolated_x(s, x);
 #ifdef PARANOID
         // Get x position as Vector from bulk element
         Vector<double> x_bulk(ndim + 1);
         bulk_el_pt->interpolated_x(s_bulk, x_bulk);
         double max_legal_error = 1.0e-5;
         double error = 0.0;
         for (unsigned i = 0; i < ndim + 1; i++)
         {
           error += fabs(x[i] - x_bulk[i]);
         }
         if (error > max_legal_error)
         {
           std::ostringstream error_stream;
           error_stream << "difference in Eulerian posn from bulk and face: "
                        << error << " exceeds threshold " << max_legal_error
                        << std::endl;
           throw OomphLibError(error_stream.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
 #endif
         // Outer unit normal
         Vector<double> normal(ndim + 1);
         outer_unit_normal(s, normal);
         // Get velocity from bulk element
         Vector<double> veloc(ndim + 1);
         bulk_el_pt->interpolated_u_nst(s_bulk, veloc);
         // Get traction from bulk element
         Vector<double> traction(ndim + 1);
         bulk_el_pt->get_traction(s_bulk, normal, traction);
         // Local rate of work:
         double rate_of_work = 0.0;
         for (unsigned i = 0; i < ndim + 1; i++)
         {
           rate_of_work += traction[i] * veloc[i];
         }
         // Add rate of work
         rate_of_work_integral += rate_of_work * W;
         if (outfile.is_open())
         {
           // Output x,y,...,
           for (unsigned i = 0; i < ndim + 1; i++)
           {
             outfile << x[i] << " ";
           }
           // Output traction
           for (unsigned i = 0; i < ndim + 1; i++)
           {
             outfile << traction[i] << " ";
           }
           // Output veloc
           for (unsigned i = 0; i < ndim + 1; i++)
           {
             outfile << veloc[i] << " ";
           }
           // Output normal
           for (unsigned i = 0; i < ndim + 1; i++)
           {
             outfile << normal[i] << " ";
           }
           // Output local rate of work
           for (unsigned i = 0; i < ndim + 1; i++)
           {
             outfile << rate_of_work << " ";
           }
           outfile << std::endl;
         }
       }
       return rate_of_work_integral;
     }
References oomph::FaceElement::bulk_element_pt(), oomph::FiniteElement::dim(), calibrate::error, boost::multiprecision::fabs(), oomph::FaceElement::get_local_coordinate_in_bulk(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), J, oomph::FaceElement::J_eulerian(), oomph::Integral::knot(), oomph::GeomObject::ndim(), WallFunction::normal(), oomph::Integral::nweight(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::FaceElement::outer_unit_normal(), s, w, oomph::QuadTreeNames::W, oomph::Integral::weight(), and plotDoE::x.
get_rate_of_traction_work_components() [1/2]
template<class ELEMENT > void oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_rate_of_traction_work_components (double & rate_of_work_integral_p, double & rate_of_work_integral_n, double & rate_of_work_integral_t) inline
Get integral of instantaneous rate of work done by the traction that's exerted onto the fluid, decomposed into pressure and normal and tangential viscous components.
     {
       std::ofstream dummy_file;
       get_rate_of_traction_work_components(dummy_file,
                                            rate_of_work_integral_p,
                                            rate_of_work_integral_n,
                                            rate_of_work_integral_t);
     }
get_rate_of_traction_work_components() [2/2]
template<class ELEMENT > void oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_rate_of_traction_work_components (std::ofstream & outfile, double & rate_of_work_integral_p, double & rate_of_work_integral_n, double & rate_of_work_integral_t) inline
Get integral of instantaneous rate of work done by the traction that's exerted onto the fluid, decomposed into pressure and normal and tangential viscous components. Doc in outfile.
     {
       // Initialise
       rate_of_work_integral_p = 0;
       rate_of_work_integral_n = 0;
       rate_of_work_integral_t = 0;
       // Spatial dimension of element
       unsigned ndim = dim();
       // Vector of local coordinates in face element
       Vector<double> s(ndim);
       // Vector for global Eulerian coordinates
       Vector<double> x(ndim + 1);
       // Vector for local coordinates in bulk element
       Vector<double> s_bulk(ndim + 1);
       // Set the value of n_intpt
       unsigned n_intpt = integral_pt()->nweight();
       // Get pointer to assocated bulk element
       ELEMENT* bulk_el_pt = dynamic_cast<ELEMENT*>(bulk_element_pt());
       // Hacky: This is only appropriate for 3x3 integration of
       // 2D quad elements
       if (outfile.is_open()) outfile << "ZONE I=3, J=3" << std::endl;
       // Loop over the integration points
       for (unsigned ipt = 0; ipt < n_intpt; ipt++)
       {
         // Assign values of s in FaceElement and local coordinates in bulk
         // element
         for (unsigned i = 0; i < ndim; i++)
         {
           s[i] = integral_pt()->knot(ipt, i);
         }
         // Get the bulk coordinates
         this->get_local_coordinate_in_bulk(s, s_bulk);
         // Get the integral weight
         double w = integral_pt()->weight(ipt);
         // Get jacobian of mapping
         double J = J_eulerian(s);
         // Premultiply the weights and the Jacobian
         double W = w * J;
         // Get x position as Vector
         interpolated_x(s, x);
 #ifdef PARANOID
         // Get x position as Vector from bulk element
         Vector<double> x_bulk(ndim + 1);
         bulk_el_pt->interpolated_x(s_bulk, x_bulk);
         double max_legal_error = 1.0e-5;
         double error = 0.0;
         for (unsigned i = 0; i < ndim + 1; i++)
         {
           error += fabs(x[i] - x_bulk[i]);
         }
         if (error > max_legal_error)
         {
           std::ostringstream error_stream;
           error_stream << "difference in Eulerian posn from bulk and face: "
                        << error << " exceeds threshold " << max_legal_error
                        << std::endl;
           throw OomphLibError(error_stream.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
 #endif
         // Outer unit normal
         Vector<double> normal(ndim + 1);
         outer_unit_normal(s, normal);
         // Get velocity from bulk element
         Vector<double> veloc(ndim + 1);
         bulk_el_pt->interpolated_u_nst(s_bulk, veloc);
         // Get traction from bulk element
         Vector<double> traction_p(ndim + 1);
         Vector<double> traction_n(ndim + 1);
         Vector<double> traction_t(ndim + 1);
         bulk_el_pt->get_traction(
           s_bulk, normal, traction_p, traction_n, traction_t);
         // Local rate of work:
         double rate_of_work_p = 0.0;
         double rate_of_work_n = 0.0;
         double rate_of_work_t = 0.0;
         for (unsigned i = 0; i < ndim + 1; i++)
         {
           rate_of_work_p += traction_p[i] * veloc[i];
           rate_of_work_n += traction_n[i] * veloc[i];
           rate_of_work_t += traction_t[i] * veloc[i];
         }
         // Add rate of work
         rate_of_work_integral_p += rate_of_work_p * W;
         rate_of_work_integral_n += rate_of_work_n * W;
         rate_of_work_integral_t += rate_of_work_t * W;
         if (outfile.is_open())
         {
           // Output x,y,...,
           for (unsigned i = 0; i < ndim + 1; i++)
           {
             outfile << x[i] << " ";
           }
           // Output traction due to pressure
           for (unsigned i = 0; i < ndim + 1; i++)
           {
             outfile << traction_p[i] << " ";
           }
           // Output traction due to viscous normal stress
           for (unsigned i = 0; i < ndim + 1; i++)
           {
             outfile << traction_n[i] << " ";
           }
           // Output traction due to viscous tangential stress
           for (unsigned i = 0; i < ndim + 1; i++)
           {
             outfile << traction_t[i] << " ";
           }
           // Output veloc
           for (unsigned i = 0; i < ndim + 1; i++)
           {
             outfile << veloc[i] << " ";
           }
           // Output normal
           for (unsigned i = 0; i < ndim + 1; i++)
           {
             outfile << normal[i] << " ";
           }
           // Output local rate of work due to pressure
           for (unsigned i = 0; i < ndim + 1; i++)
           {
             outfile << rate_of_work_p << " ";
           }
           // Output local rate of work due to viscous normal stress
           for (unsigned i = 0; i < ndim + 1; i++)
           {
             outfile << rate_of_work_n << " ";
           }
           // Output local rate of work due to viscous tangential stress
           for (unsigned i = 0; i < ndim + 1; i++)
           {
             outfile << rate_of_work_t << " ";
           }
           outfile << std::endl;
         }
       }
     }
References oomph::FaceElement::bulk_element_pt(), oomph::FiniteElement::dim(), calibrate::error, boost::multiprecision::fabs(), oomph::FaceElement::get_local_coordinate_in_bulk(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), J, oomph::FaceElement::J_eulerian(), oomph::Integral::knot(), oomph::GeomObject::ndim(), WallFunction::normal(), oomph::Integral::nweight(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::FaceElement::outer_unit_normal(), s, w, oomph::QuadTreeNames::W, oomph::Integral::weight(), and plotDoE::x.
get_volume_flux() [1/2]
template<class ELEMENT > double oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_volume_flux () inline
Get integral of volume flux.
     {
       std::ofstream dummy_file;
       return get_volume_flux(dummy_file);
     }
Referenced by UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solution(), and oomph::NavierStokesFluxControlElement< ELEMENT >::get_volume_flux().
get_volume_flux() [2/2]
template<class ELEMENT > double oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_volume_flux (std::ofstream & outfile) inline
Get integral of volume flux and doc.
     {
       // Initialise
       double volume_flux_integral = 0.0;
       // Spatial dimension of element
       unsigned ndim = dim();
       // Vector of local coordinates in face element
       Vector<double> s(ndim);
       // Vector for global Eulerian coordinates
       Vector<double> x(ndim + 1);
       // Vector for local coordinates in bulk element
       Vector<double> s_bulk(ndim + 1);
       // Set the value of n_intpt
       unsigned n_intpt = integral_pt()->nweight();
       // Get pointer to assocated bulk element
       ELEMENT* bulk_el_pt = dynamic_cast<ELEMENT*>(bulk_element_pt());
       // Hacky: This is only appropriate for 3x3 integration of
       // 2D quad elements
       if (outfile.is_open()) outfile << "ZONE I=3, J=3" << std::endl;
       // Loop over the integration points
       for (unsigned ipt = 0; ipt < n_intpt; ipt++)
       {
         // Assign values of s in FaceElement and local coordinates in bulk
         // element
         for (unsigned i = 0; i < ndim; i++)
         {
           s[i] = integral_pt()->knot(ipt, i);
         }
         // Get the bulk coordinates
         this->get_local_coordinate_in_bulk(s, s_bulk);
         // Get the integral weight
         double w = integral_pt()->weight(ipt);
         // Get jacobian of mapping
         double J = J_eulerian(s);
         // Premultiply the weights and the Jacobian
         double W = w * J;
         // Get x position as Vector
         interpolated_x(s, x);
 #ifdef PARANOID
         // Get x position as Vector from bulk element
         Vector<double> x_bulk(ndim + 1);
         bulk_el_pt->interpolated_x(s_bulk, x_bulk);
         double max_legal_error = 1.0e-5;
         double error = 0.0;
         for (unsigned i = 0; i < ndim + 1; i++)
         {
           error += fabs(x[i] - x_bulk[i]);
         }
         if (error > max_legal_error)
         {
           std::ostringstream error_stream;
           error_stream << "difference in Eulerian posn from bulk and face: "
                        << error << " exceeds threshold " << max_legal_error
                        << std::endl;
           throw OomphLibError(error_stream.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
 #endif
         // Outer unit normal
         Vector<double> normal(ndim + 1);
         outer_unit_normal(s, normal);
         // Get velocity from bulk element
         Vector<double> veloc(ndim + 1);
         bulk_el_pt->interpolated_u_nst(s_bulk, veloc);
         // Volume flux
         double volume_flux = 0.0;
         for (unsigned i = 0; i < ndim + 1; i++)
         {
           volume_flux += normal[i] * veloc[i];
         }
         // Add to integral
         volume_flux_integral += volume_flux * W;
         if (outfile.is_open())
         {
           // Output x,y,...,
           for (unsigned i = 0; i < ndim + 1; i++)
           {
             outfile << x[i] << " ";
           }
           // Output veloc
           for (unsigned i = 0; i < ndim + 1; i++)
           {
             outfile << veloc[i] << " ";
           }
           // Output normal
           for (unsigned i = 0; i < ndim + 1; i++)
           {
             outfile << normal[i] << " ";
           }
           // Output local volume flux
           outfile << volume_flux << " ";
           outfile << std::endl;
         }
       }
       return volume_flux_integral;
     }
References oomph::FaceElement::bulk_element_pt(), oomph::FiniteElement::dim(), calibrate::error, boost::multiprecision::fabs(), oomph::FaceElement::get_local_coordinate_in_bulk(), i, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), J, oomph::FaceElement::J_eulerian(), oomph::Integral::knot(), oomph::GeomObject::ndim(), WallFunction::normal(), oomph::Integral::nweight(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::FaceElement::outer_unit_normal(), s, w, oomph::QuadTreeNames::W, oomph::Integral::weight(), and plotDoE::x.
zeta_nodal()
template<class ELEMENT > double oomph::NavierStokesSurfacePowerElement< ELEMENT >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const inline virtual
The "global" intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default This final over-ride is required for cases where the FaceElement is a SolidFiniteElement because both SolidFiniteElements and FaceElements overload zeta_nodal.
Reimplemented from oomph::FaceElement.
     {
       return FaceElement::zeta_nodal(n, k, i);
     }
References i, k, n, and oomph::FaceElement::zeta_nodal().
Member Data Documentation
Dim
template<class ELEMENT > unsigned oomph::NavierStokesSurfacePowerElement< ELEMENT >::Dim private
The highest dimension of the problem.
Referenced by oomph::NavierStokesSurfacePowerElement< ELEMENT >::NavierStokesSurfacePowerElement().
The documentation for this class was generated from the following file:
navier_stokes_surface_power_elements.h