MercuryDPM: InteractionHandlerSpeedTest.cpp File Reference
InteractionHandlerSpeedTest.cpp File Reference
#include <Boundaries/CubeInsertionBoundary.h>
#include <Mercury3D.h>
#include <Species/LinearViscoelasticSpecies.h>
#include <MercuryTime.h>
#include <Walls/InfiniteWall.h>
Classes
class DPM
In this file a cubic packing of 5^3 particles in a tri-axial box is created and allowed to settle under small gravity. After that Z statistics are calculated.
Functions
int main ()
Function Documentation
main()
int main ()
 {
     // create a simulation
     DPM dpm;
     // restart from initial condition; create them if they dont exist.
     if (!dpm.readRestartFile("InteractionHandlerSpeedTestInit")) {
         logger(ERROR,"Creating restart file first");
         // create a initial simulation
         unsigned n = 100000;
         DPM dpm0;
         dpm0.setName("InteractionHandlerSpeedTestInit");
         dpm0.setDomain(Vec3D(0, 0, 0), cbrt(n) * 0.95 * Vec3D(1, 1, 1));
         //dpm0.setGravity(Vec3D(0,0,-1));
         dpm0.setTimeStep(1e-4);
         dpm0.setTimeMax(10);
         dpm0.setSaveCount(50);
         // create species
         auto species = dpm0.speciesHandler.copyAndAddObject(LinearViscoelasticSpecies());
         species->setDensity(6.0/constants::pi);
         species->setCollisionTimeAndRestitutionCoefficient(10 * dpm0.getTimeStep(), 0.1, 1.0);
         // create walls
         InfiniteWall wall(species);
         wall.set(Vec3D(0,0,1), dpm0.getMax());
         dpm0.wallHandler.copyAndAddObject(wall);
         wall.set(Vec3D(0,0,-1), dpm0.getMin());
         dpm0.wallHandler.copyAndAddObject(wall);
         wall.set(Vec3D(0,1,0), dpm0.getMax());
         dpm0.wallHandler.copyAndAddObject(wall);
         wall.set(Vec3D(0, -1, 0), dpm0.getMin());
         dpm0.wallHandler.copyAndAddObject(wall);
         wall.set(Vec3D(1, 0, 0), dpm0.getMax());
         dpm0.wallHandler.copyAndAddObject(wall);
         wall.set(Vec3D(-1, 0, 0), dpm0.getMin());
         dpm0.wallHandler.copyAndAddObject(wall);
         // create particles
         SphericalParticle particle(species);
         CubeInsertionBoundary insertionBoundary;
         insertionBoundary.set(particle, 1e6, dpm0.getMin(), dpm0.getMax(), {0, 0, 0}, {0, 0, 0});
         insertionBoundary.setInitialVolume((n - 0.5) * constants::pi / 6.);
         insertionBoundary.checkBoundaryBeforeTimeStep(&dpm0);
         logger(INFO, "Number of particles: %", dpm0.particleHandler.getSize());
         //solve
         dpm0.solve();
         if (!dpm.readRestartFile("InteractionHandlerSpeedTestInit"))
         {
             logger(ERROR, "Restart file could not be created");
         }
     }
     //rename simulation
     dpm.setName("InteractionHandlerSpeedTest");
     dpm.setTime(0);
     //simulate 0 time steps
     dpm.setTimeMax(0);
     dpm.setHGridMaxLevels(1);
     dpm.setFileType(FileType::NO_FILE);
     dpm.solve();
     dpm.interactionHandler.clear();
     dpm.computeAllForces();
     Time timer;
     int repetitions = 10;
     logger(INFO,"% interactions",dpm.interactionHandler.getNumberOfObjects());
     dpm.hGridInfo(std::cout);
     //timings
     timer.tic();
     for (int i = 0; i < repetitions; ++i) {
         dpm.interactionHandler.clear();
         dpm.computeAllForces();
     }
     logger(INFO, "Time to simulate contact detection and force computation for % non-existing contacts: % s",dpm.interactionHandler.getNumberOfObjects(), timer.toctic());
     for (int i = 0; i < repetitions; ++i) {
         dpm.computeAllForces();
     }
     logger(INFO, "Time to simulate contact detection and force computation for % existing contacts: % s",dpm.interactionHandler.getNumberOfObjects(), timer.toctic());
     for (int i = 0; i < repetitions; ++i) {
         dpm.computeAllForcesNoHGrid();
     }
     logger(INFO, "Time to simulate force computation for % existing contacts: % s",dpm.interactionHandler.getNumberOfObjects(), timer.toctic());
     return 0;
 }
References Eigen::numext::cbrt(), InsertionBoundary::checkBoundaryBeforeTimeStep(), BaseHandler< T >::clear(), DPM::computeAllForces(), DPM::computeAllForcesNoHGrid(), BaseHandler< T >::copyAndAddObject(), e(), ERROR, DPMBase::getMax(), DPMBase::getMin(), BaseHandler< T >::getNumberOfObjects(), BaseHandler< T >::getSize(), DPMBase::getTimeStep(), MercuryBase::hGridInfo(), i, INFO, DPMBase::interactionHandler, logger, n, NO_FILE, DPMBase::particleHandler, constants::pi, DPMBase::readRestartFile(), CubeInsertionBoundary::set(), InfiniteWall::set(), DPMBase::setDomain(), DPMBase::setFileType(), MercuryBase::setHGridMaxLevels(), InsertionBoundary::setInitialVolume(), DPMBase::setName(), DPMBase::setSaveCount(), DPMBase::setTime(), DPMBase::setTimeMax(), DPMBase::setTimeStep(), DPMBase::solve(), DPMBase::speciesHandler, and DPMBase::wallHandler.