MercuryDPM: Eigen::internal::FullReducer< Self, Op, Device, Vectorizable > Struct Template Reference
Eigen::internal::FullReducer< Self, Op, Device, Vectorizable > Struct Template Reference
#include <TensorReduction.h>
Static Public Member Functions
static EIGEN_DEVICE_FUNC void run (const Self &self, Op &reducer, const Device &, typename Self::EvaluatorPointerType output)
Static Public Attributes
static constexpr bool HasOptimizedImplementation = false
Member Function Documentation
run()
template<typename Self , typename Op , typename Device , bool Vectorizable = (Self::InputPacketAccess && Self::ReducerTraits::PacketAccess)> static EIGEN_DEVICE_FUNC void Eigen::internal::FullReducer< Self, Op, Device, Vectorizable >::run (const Self & self, Op & reducer, const Device & , typename Self::EvaluatorPointerType output) inline static
{
     const typename Self::Index num_coeffs = array_prod(self.m_impl.dimensions());
     *output = InnerMostDimReducer<Self, Op, Vectorizable>::reduce(self, 0, num_coeffs, reducer);
   }
References Eigen::internal::array_prod(), output(), and Eigen::internal::InnerMostDimReducer< Self, Op, Vectorizable, UseTreeReduction >::reduce().
Referenced by Eigen::TensorReductionEvaluatorBase< const TensorReductionOp< Op, Dims, ArgType, MakePointer_ >, Device >::evalSubExprsIfNeededCommon().
Member Data Documentation
HasOptimizedImplementation
template<typename Self , typename Op , typename Device , bool Vectorizable = (Self::InputPacketAccess && Self::ReducerTraits::PacketAccess)> constexpr bool Eigen::internal::FullReducer< Self, Op, Device, Vectorizable >::HasOptimizedImplementation = false static constexpr
The documentation for this struct was generated from the following file:
TensorReduction.h