MercuryDPM: Eigen::Translation< Scalar_, Dim_ > Class Template Reference
Eigen::Translation< Scalar_, Dim_ > Class Template Reference
Geometry » Reference » Geometry_Module
Represents a translation transformation.
#include <Translation.h>
Public Types
enum { Dim = Dim_ }
typedef Scalar_ Scalar
typedef Matrix< Scalar, Dim, 1 > VectorType
typedef Matrix< Scalar, Dim, Dim > LinearMatrixType
typedef Transform< Scalar, Dim, Affine > AffineTransformType
typedef Transform< Scalar, Dim, Isometry > IsometryTransformType
Public Member Functions
EIGEN_DEVICE_FUNC Translation ()
EIGEN_DEVICE_FUNC Translation (const Scalar &sx, const Scalar &sy)
EIGEN_DEVICE_FUNC Translation (const Scalar &sx, const Scalar &sy, const Scalar &sz)
EIGEN_DEVICE_FUNC Translation (const VectorType &vector)
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Scalar x () const
Returns the x-translation by value.
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Scalar y () const
Returns the y-translation by value.
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Scalar z () const
Returns the z-translation by value.
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Scalar & x ()
Returns the x-translation as a reference.
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Scalar & y ()
Returns the y-translation as a reference.
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Scalar & z ()
Returns the z-translation as a reference.
EIGEN_DEVICE_FUNC const VectorType & vector () const
EIGEN_DEVICE_FUNC VectorType & vector ()
EIGEN_DEVICE_FUNC const VectorType & translation () const
EIGEN_DEVICE_FUNC VectorType & translation ()
EIGEN_DEVICE_FUNC Translation operator* (const Translation &other) const
EIGEN_DEVICE_FUNC AffineTransformType operator* (const UniformScaling< Scalar > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC AffineTransformType operator* (const EigenBase< OtherDerived > &linear) const
template<typename Derived >
EIGEN_DEVICE_FUNC IsometryTransformType operator* (const RotationBase< Derived, Dim > &r) const
template<int Mode, int Options>
EIGEN_DEVICE_FUNC Transform< Scalar, Dim, Mode > operator* (const Transform< Scalar, Dim, Mode, Options > &t) const
template<typename Derived >
std::enable_if_t< Derived::IsVectorAtCompileTime, VectorType > operator* (const MatrixBase< Derived > &vec) const
Translation inverse () const
template<typename NewScalarType >
EIGEN_DEVICE_FUNC internal::cast_return_type< Translation, Translation< NewScalarType, Dim > >::type cast () const
template<typename OtherScalarType >
EIGEN_DEVICE_FUNC Translation (const Translation< OtherScalarType, Dim > &other)
EIGEN_DEVICE_FUNC bool isApprox (const Translation &other, const typename NumTraits< Scalar >::Real &prec=NumTraits< Scalar >::dummy_precision()) const
Static Public Member Functions
static const Translation Identity ()
Protected Attributes
VectorType m_coeffs
Friends
template<typename OtherDerived >
EIGEN_DEVICE_FUNC AffineTransformType operator* (const EigenBase< OtherDerived > &linear, const Translation &t)
Detailed Description
template<typename Scalar_, int Dim_>
class Eigen::Translation< Scalar_, Dim_ >
Represents a translation transformation.
\geometry_module
Template Parameters
Scalar_ the scalar type, i.e., the type of the coefficients.
Dim_ the dimension of the space, can be a compile time value or Dynamic
Note
This class is not aimed to be used to store a translation transformation, but rather to make easier the constructions and updates of Transform objects.
See also
class Scaling, class Transform
Member Typedef Documentation
AffineTransformType
template<typename Scalar_ , int Dim_> typedef Transform<Scalar, Dim, Affine> Eigen::Translation< Scalar_, Dim_ >::AffineTransformType
corresponding affine transformation type
IsometryTransformType
template<typename Scalar_ , int Dim_> typedef Transform<Scalar, Dim, Isometry> Eigen::Translation< Scalar_, Dim_ >::IsometryTransformType
corresponding isometric transformation type
LinearMatrixType
template<typename Scalar_ , int Dim_> typedef Matrix<Scalar, Dim, Dim> Eigen::Translation< Scalar_, Dim_ >::LinearMatrixType
corresponding linear transformation matrix type
Scalar
template<typename Scalar_ , int Dim_> typedef Scalar_ Eigen::Translation< Scalar_, Dim_ >::Scalar
the scalar type of the coefficients
VectorType
template<typename Scalar_ , int Dim_> typedef Matrix<Scalar, Dim, 1> Eigen::Translation< Scalar_, Dim_ >::VectorType
corresponding vector type
Member Enumeration Documentation
anonymous enum
template<typename Scalar_ , int Dim_> anonymous enum
dimension of the space
Enumerator
Dim
 { Dim = Dim_ };
Constructor & Destructor Documentation
Translation() [1/5]
template<typename Scalar_ , int Dim_> EIGEN_DEVICE_FUNC Eigen::Translation< Scalar_, Dim_ >::Translation () inline
Default constructor without initialization.
 {}
Referenced by Eigen::Translation< Scalar_, Dim_ >::Identity(), Eigen::Translation< Scalar_, Dim_ >::inverse(), and Eigen::Translation< Scalar_, Dim_ >::operator*().
Translation() [2/5]
template<typename Scalar_ , int Dim_> EIGEN_DEVICE_FUNC Eigen::Translation< Scalar_, Dim_ >::Translation (const Scalar & sx, const Scalar & sy) inline
{
     eigen_assert(Dim == 2);
     m_coeffs.x() = sx;
     m_coeffs.y() = sy;
   }
References Eigen::Translation< Scalar_, Dim_ >::Dim, eigen_assert, and Eigen::Translation< Scalar_, Dim_ >::m_coeffs.
Translation() [3/5]
template<typename Scalar_ , int Dim_> EIGEN_DEVICE_FUNC Eigen::Translation< Scalar_, Dim_ >::Translation (const Scalar & sx, const Scalar & sy, const Scalar & sz) inline
{
     eigen_assert(Dim == 3);
     m_coeffs.x() = sx;
     m_coeffs.y() = sy;
     m_coeffs.z() = sz;
   }
References Eigen::Translation< Scalar_, Dim_ >::Dim, eigen_assert, and Eigen::Translation< Scalar_, Dim_ >::m_coeffs.
Translation() [4/5]
template<typename Scalar_ , int Dim_> EIGEN_DEVICE_FUNC Eigen::Translation< Scalar_, Dim_ >::Translation (const VectorType & vector) inline explicit
Constructs and initialize the translation transformation from a vector of translation coefficients
 : m_coeffs(vector) {}
Translation() [5/5]
template<typename Scalar_ , int Dim_> template<typename OtherScalarType > EIGEN_DEVICE_FUNC Eigen::Translation< Scalar_, Dim_ >::Translation (const Translation< OtherScalarType, Dim > & other) inline explicit
Copy constructor with scalar type conversion
{
     m_coeffs = other.vector().template cast<Scalar>();
   }
References Eigen::Translation< Scalar_, Dim_ >::m_coeffs, and Eigen::Translation< Scalar_, Dim_ >::vector().
Member Function Documentation
cast()
template<typename Scalar_ , int Dim_> template<typename NewScalarType > EIGEN_DEVICE_FUNC internal::cast_return_type<Translation, Translation<NewScalarType, Dim> >::type Eigen::Translation< Scalar_, Dim_ >::cast () const inline
Returns
*this with scalar type casted to NewScalarType
Note that if NewScalarType is equal to the current scalar type of *this then this function smartly returns a const reference to *this.
                {
     return typename internal::cast_return_type<Translation, Translation<NewScalarType, Dim> >::type(*this);
   }
References compute_granudrum_aor::type.
Identity()
template<typename Scalar_ , int Dim_> static const Translation Eigen::Translation< Scalar_, Dim_ >::Identity () inline static
 { return Translation(VectorType::Zero()); }
References Eigen::Translation< Scalar_, Dim_ >::Translation(), and oomph::PseudoSolidHelper::Zero.
inverse()
template<typename Scalar_ , int Dim_> Translation Eigen::Translation< Scalar_, Dim_ >::inverse () const inline
Returns
the inverse translation (opposite)
 { return Translation(-m_coeffs); }
References Eigen::Translation< Scalar_, Dim_ >::m_coeffs, and Eigen::Translation< Scalar_, Dim_ >::Translation().
isApprox()
template<typename Scalar_ , int Dim_> EIGEN_DEVICE_FUNC bool Eigen::Translation< Scalar_, Dim_ >::isApprox (const Translation< Scalar_, Dim_ > & other, const typename NumTraits< Scalar >::Real & prec = NumTraits<Scalar>::dummy_precision()) const inline
Returns
true if *this is approximately equal to other, within the precision determined by prec.
See also
MatrixBase::isApprox()
{
     return m_coeffs.isApprox(other.m_coeffs, prec);
   }
References Eigen::Translation< Scalar_, Dim_ >::m_coeffs.
operator*() [1/6]
template<typename Scalar , int Dim> template<typename OtherDerived > EIGEN_DEVICE_FUNC Translation< Scalar, Dim >::AffineTransformType Eigen::Translation< Scalar, Dim >::operator* (const EigenBase< OtherDerived > & linear) const inline
Concatenates a translation and a linear transformation
{
   AffineTransformType res;
   res.matrix().setZero();
   res.linear() = linear.derived();
   res.translation() = m_coeffs;
   res.matrix().row(Dim).setZero();
   res(Dim, Dim) = Scalar(1);
   return res;
 }
References Eigen::EigenBase< Derived >::derived(), Global_Variables::Dim, and res.
operator*() [2/6]
template<typename Scalar_ , int Dim_> template<typename Derived > std::enable_if_t<Derived::IsVectorAtCompileTime, VectorType> Eigen::Translation< Scalar_, Dim_ >::operator* (const MatrixBase< Derived > & vec) const inline
Applies translation to vector
{
     return m_coeffs + vec.derived();
   }
References Eigen::Translation< Scalar_, Dim_ >::m_coeffs.
operator*() [3/6]
template<typename Scalar_ , int Dim_> template<typename Derived > EIGEN_DEVICE_FUNC IsometryTransformType Eigen::Translation< Scalar_, Dim_ >::operator* (const RotationBase< Derived, Dim > & r) const inline
Concatenates a translation and a rotation
{
     return *this * IsometryTransformType(r);
   }
References UniformPSDSelfTest::r.
operator*() [4/6]
template<typename Scalar_ , int Dim_> template<int Mode, int Options> EIGEN_DEVICE_FUNC Transform<Scalar, Dim, Mode> Eigen::Translation< Scalar_, Dim_ >::operator* (const Transform< Scalar, Dim, Mode, Options > & t) const inline
Concatenates a translation and a transformation
{
     Transform<Scalar, Dim, Mode> res = t;
     res.pretranslate(m_coeffs);
     return res;
   }
References Eigen::Translation< Scalar_, Dim_ >::m_coeffs, res, and plotPSD::t.
operator*() [5/6]
template<typename Scalar_ , int Dim_> EIGEN_DEVICE_FUNC Translation Eigen::Translation< Scalar_, Dim_ >::operator* (const Translation< Scalar_, Dim_ > & other) const inline
Concatenates two translation
{
     return Translation(m_coeffs + other.m_coeffs);
   }
References Eigen::Translation< Scalar_, Dim_ >::m_coeffs, and Eigen::Translation< Scalar_, Dim_ >::Translation().
operator*() [6/6]
template<typename Scalar , int Dim> EIGEN_DEVICE_FUNC Translation< Scalar, Dim >::AffineTransformType Eigen::Translation< Scalar, Dim >::operator* (const UniformScaling< Scalar > & other) const inline
Concatenates a translation and a uniform scaling
{
   AffineTransformType res;
   res.matrix().setZero();
   res.linear().diagonal().fill(other.factor());
   res.translation() = m_coeffs;
   res(Dim, Dim) = Scalar(1);
   return res;
 }
References Global_Variables::Dim, Eigen::UniformScaling< Scalar_ >::factor(), and res.
translation() [1/2]
template<typename Scalar_ , int Dim_> EIGEN_DEVICE_FUNC VectorType& Eigen::Translation< Scalar_, Dim_ >::translation () inline
 { return m_coeffs; }
References Eigen::Translation< Scalar_, Dim_ >::m_coeffs.
translation() [2/2]
template<typename Scalar_ , int Dim_> EIGEN_DEVICE_FUNC const VectorType& Eigen::Translation< Scalar_, Dim_ >::translation () const inline
 { return m_coeffs; }
References Eigen::Translation< Scalar_, Dim_ >::m_coeffs.
vector() [1/2]
template<typename Scalar_ , int Dim_> EIGEN_DEVICE_FUNC VectorType& Eigen::Translation< Scalar_, Dim_ >::vector () inline
 { return m_coeffs; }
References Eigen::Translation< Scalar_, Dim_ >::m_coeffs.
vector() [2/2]
template<typename Scalar_ , int Dim_> EIGEN_DEVICE_FUNC const VectorType& Eigen::Translation< Scalar_, Dim_ >::vector () const inline
 { return m_coeffs; }
References Eigen::Translation< Scalar_, Dim_ >::m_coeffs.
Referenced by openglsupport_test_loop(), and Eigen::Translation< Scalar_, Dim_ >::Translation().
x() [1/2]
template<typename Scalar_ , int Dim_> EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Scalar& Eigen::Translation< Scalar_, Dim_ >::x () inline
Returns the x-translation as a reference.
 { return m_coeffs.x(); }
References Eigen::Translation< Scalar_, Dim_ >::m_coeffs.
x() [2/2]
template<typename Scalar_ , int Dim_> EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Scalar Eigen::Translation< Scalar_, Dim_ >::x () const inline
Returns the x-translation by value.
 { return m_coeffs.x(); }
References Eigen::Translation< Scalar_, Dim_ >::m_coeffs.
y() [1/2]
template<typename Scalar_ , int Dim_> EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Scalar& Eigen::Translation< Scalar_, Dim_ >::y () inline
Returns the y-translation as a reference.
 { return m_coeffs.y(); }
References Eigen::Translation< Scalar_, Dim_ >::m_coeffs.
y() [2/2]
template<typename Scalar_ , int Dim_> EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Scalar Eigen::Translation< Scalar_, Dim_ >::y () const inline
Returns the y-translation by value.
 { return m_coeffs.y(); }
References Eigen::Translation< Scalar_, Dim_ >::m_coeffs.
z() [1/2]
template<typename Scalar_ , int Dim_> EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Scalar& Eigen::Translation< Scalar_, Dim_ >::z () inline
Returns the z-translation as a reference.
 { return m_coeffs.z(); }
References Eigen::Translation< Scalar_, Dim_ >::m_coeffs.
z() [2/2]
template<typename Scalar_ , int Dim_> EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Scalar Eigen::Translation< Scalar_, Dim_ >::z () const inline
Returns the z-translation by value.
 { return m_coeffs.z(); }
References Eigen::Translation< Scalar_, Dim_ >::m_coeffs.
Friends And Related Function Documentation
operator*
template<typename Scalar_ , int Dim_> template<typename OtherDerived > EIGEN_DEVICE_FUNC AffineTransformType operator* (const EigenBase< OtherDerived > & linear, const Translation< Scalar_, Dim_ > & t) friend
Returns
the concatenation of a linear transformation l with the translation t
{
     AffineTransformType res;
     res.matrix().setZero();
     res.linear() = linear.derived();
     res.translation() = linear.derived() * t.m_coeffs;
     res.matrix().row(Dim).setZero();
     res(Dim, Dim) = Scalar(1);
     return res;
   }
Member Data Documentation
m_coeffs
template<typename Scalar_ , int Dim_> VectorType Eigen::Translation< Scalar_, Dim_ >::m_coeffs protected
Referenced by Eigen::Translation< Scalar_, Dim_ >::inverse(), Eigen::Translation< Scalar_, Dim_ >::isApprox(), Eigen::Translation< Scalar_, Dim_ >::operator*(), Eigen::Translation< Scalar_, Dim_ >::translation(), Eigen::Translation< Scalar_, Dim_ >::Translation(), Eigen::Translation< Scalar_, Dim_ >::vector(), Eigen::Translation< Scalar_, Dim_ >::x(), Eigen::Translation< Scalar_, Dim_ >::y(), and Eigen::Translation< Scalar_, Dim_ >::z().
The documentation for this class was generated from the following files:
ForwardDeclarations.h
Translation.h