MercuryDPM: BasicIntersectionOfWalls Class Reference
BasicIntersectionOfWalls Class Reference
Restriction of a wall to the intersection with another wall.
#include <BasicIntersectionOfWalls.h>
Public Member Functions
BasicIntersectionOfWalls ()
Default constructor, the normal is infinitely long.
BasicIntersectionOfWalls (const BasicIntersectionOfWalls &w)
Copy constructor, copy the given wall.
~BasicIntersectionOfWalls () override
Default destructor.
BasicIntersectionOfWalls * copy () const override
Wall copy method. It calls the copy constructor of this Wall, useful for polymorphism.
unsigned long getNumberOfObjects ()
Returns the number of objects.
void add (BaseWall &wall)
Defines a standard wall, given an outward normal vector s.t. normal*x=normal*point for all x of the wall.
bool getDistanceAndNormal (const BaseParticle &p, Mdouble &distance, Vec3D &normal_return) const override
Compute the distance from the wall for a given BaseParticle and return if there is a collision. If there is a collision, also return the normal vector.
void read (std::istream &is) override
Reads BasicIntersectionOfWalls from a restart file.
void oldRead (std::istream &is)
Reads BasicIntersectionOfWalls from an old-style restart file.
void write (std::ostream &os) const override
Writes the BasicIntersectionOfWalls to an output stream, usually a restart file.
std::string getName () const override
Returns the name of the object, in this case the string "BasicIntersectionOfWalls".
void getVTK (std::vector< Vec3D > &points, std::vector< std::vector< double >> &triangleStrips)
BaseWall * getObject (unsigned i)
Public Member Functions inherited from BaseWall
BaseWall ()
Default constructor.
BaseWall (const BaseWall &w)
Copy constructor.
~BaseWall () override
Default destructor.
virtual bool getDistanceNormalOverlap (const BaseParticle &P, Mdouble &distance, Vec3D &normal_return, Mdouble &overlap) const
virtual bool getDistanceNormalOverlapSuperquadric (const SuperQuadricParticle &p, Mdouble &distance, Vec3D &normal_return, Mdouble &overlap) const
virtual Vec3D getFurthestPointSuperQuadric (const Vec3D &normalBodyFixed, const Vec3D &axes, Mdouble eps1, Mdouble eps2) const
virtual void setHandler (WallHandler *handler)
A function which sets the WallHandler for this BaseWall.
WallHandler * getHandler () const
A function which returns the WallHandler that handles this BaseWall.
void setIndSpecies (unsigned int indSpecies) override
Define the species of this wall using the index of the species in the SpeciesHandler in this DPMBase.
void setSpecies (const ParticleSpecies *species)
Defines the species of the current wall.
bool isFixed () const override
void setForceControl (Vec3D forceGoal, Vec3D gainFactor, Vec3D baseVelocity={0, 0, 0})
Slowly adjusts the force on a wall towards a specified goal, by adjusting (prescribing) the velocity of the wall.
virtual bool isLocal (Vec3D &min, Vec3D &max) const
bool getLinePlaneIntersect (Vec3D &intersect, const Vec3D &p0, const Vec3D &p1, const Vec3D &n, const Vec3D &p)
bool isInsideWallVTK (const Vec3D &point, const Vec3D &normal, const Vec3D &position) const
void projectOntoWallVTK (Vec3D &point0, const Vec3D &point1, const Vec3D &normal, const Vec3D &position) const
void intersectVTK (std::vector< Vec3D > &points, Vec3D normal, Vec3D position) const
virtual BaseInteraction * getInteractionWithSuperQuad (SuperQuadricParticle *p, unsigned timeStamp, InteractionHandler *interactionHandler)
virtual void writeVTK (VTKContainer &vtk) const
void getVTK (std::vector< Vec3D > &points, std::vector< std::vector< double >> &triangleStrips)
const Vec3D getAxis () const
BaseInteraction * getInteractionWith (BaseParticle *p, unsigned timeStamp, InteractionHandler *interactionHandler) override
Returns the interaction between this wall and a given particle, nullptr if there is no interaction.
virtual void actionsOnRestart ()
No implementation but can be overidden in its derived classes.
virtual void actionsAfterParticleGhostUpdate ()
No implementation but can be overidden in its derived classes.
virtual void handleParticleAddition (unsigned int id, BaseParticle *p)
Handles the addition of particles to the particleHandler.
virtual void handleParticleRemoval (unsigned int id)
Handles the addition of particles to the particleHandler.
virtual void checkInteractions (InteractionHandler *interactionHandler, unsigned int timeStamp)
Check if all interactions are valid.
bool getVTKVisibility () const
void setVTKVisibility (bool vtkVisibility)
void addRenderedWall (BaseWall *w)
BaseWall * getRenderedWall (size_t i) const
std::vector< BaseWall * > getRenderedWalls () const
void removeRenderedWalls ()
void renderWall (VTKContainer &vtk)
void addParticlesAtWall (unsigned numElements=50)
void setVelocityControl (Vec3D forceGoal, Vec3D gainFactor, Vec3D baseVelocity)
virtual void writeWallDetailsVTK (VTKData &data) const
virtual void computeWear ()
Public Member Functions inherited from BaseInteractable
BaseInteractable ()
Default BaseInteractable constructor.
BaseInteractable (const BaseInteractable &p)
Copy constructor.
~BaseInteractable () override
Destructor, it simply destructs the BaseInteractable and all the objects it contains.
unsigned int getIndSpecies () const
Returns the index of the species associated with the interactable object.
const ParticleSpecies * getSpecies () const
Returns a pointer to the species of this BaseInteractable.
void setSpecies (const ParticleSpecies *species)
Sets the species of this BaseInteractable.
const Vec3D & getForce () const
Returns the force on this BaseInteractable.
const Vec3D & getTorque () const
Returns the torque on this BaseInteractable.
void setForce (const Vec3D &force)
Sets the force on this BaseInteractable.
void setTorque (const Vec3D &torque)
Sets the torque on this BaseInteractable.
void addForce (const Vec3D &addForce)
Adds an amount to the force on this BaseInteractable.
void addTorque (const Vec3D &addTorque)
Adds an amount to the torque on this BaseInteractable.
virtual void resetForceTorque (int numberOfOMPthreads)
void sumForceTorqueOMP ()
const Vec3D & getPosition () const
Returns the position of this BaseInteractable.
const Quaternion & getOrientation () const
Returns the orientation of this BaseInteractable.
virtual void setPosition (const Vec3D &position)
Sets the position of this BaseInteractable.
void setOrientationViaNormal (Vec3D normal)
Sets the orientation of this BaseInteractable by defining the vector that results from the rotation of the (1,0,0) vector.
void setOrientationViaEuler (Vec3D eulerAngle)
Sets the orientation of this BaseInteractable by defining the euler angles.
virtual void setOrientation (const Quaternion &orientation)
Sets the orientation of this BaseInteractable.
virtual void move (const Vec3D &move)
Moves this BaseInteractable by adding an amount to the position.
virtual void rotate (const Vec3D &angularVelocityDt)
Rotates this BaseInteractable.
const std::vector< BaseInteraction * > & getInteractions () const
Returns a list of interactions which belong to this interactable.
void addInteraction (BaseInteraction *I)
Adds an interaction to this BaseInteractable.
bool removeInteraction (BaseInteraction *I)
Removes an interaction from this BaseInteractable.
void copyInteractionsForPeriodicParticles (const BaseInteractable &p)
Copies interactions to this BaseInteractable whenever a periodic copy made.
void setVelocity (const Vec3D &velocity)
set the velocity of the BaseInteractable.
void setAngularVelocity (const Vec3D &angularVelocity)
set the angular velocity of the BaseInteractble.
void addVelocity (const Vec3D &velocity)
adds an increment to the velocity.
void addAngularVelocity (const Vec3D &angularVelocity)
add an increment to the angular velocity.
virtual const Vec3D & getVelocity () const
Returns the velocity of this interactable.
virtual const Vec3D & getAngularVelocity () const
Returns the angular velocity of this interactable.
void setPrescribedPosition (const std::function< Vec3D(double)> &prescribedPosition)
Allows the position of an infinite mass interactable to be prescribed.
void applyPrescribedPosition (double time)
Computes the position from the user defined prescribed position function.
void setPrescribedVelocity (const std::function< Vec3D(double)> &prescribedVelocity)
Allows the velocity of an infinite mass interactable to be prescribed.
void applyPrescribedVelocity (double time)
Computes the velocity from the user defined prescribed velocity function.
void setPrescribedOrientation (const std::function< Quaternion(double)> &prescribedOrientation)
Allows the orientation of the infinite mass interactbale to be prescribed.
void applyPrescribedOrientation (double time)
Computes the orientation from the user defined prescribed orientation function.
void setPrescribedAngularVelocity (const std::function< Vec3D(double)> &prescribedAngularVelocity)
Allows the angular velocity of the infinite mass interactable to be prescribed.
void applyPrescribedAngularVelocity (double time)
Computes the angular velocity from the user defined prescribed angular velocity.
virtual const Vec3D getVelocityAtContact (const Vec3D &contact) const
Returns the velocity at the contact point, use by many force laws.
void integrateBeforeForceComputation (double time, double timeStep)
This is part of integrate routine for objects with infinite mass.
void integrateAfterForceComputation (double time, double timeStep)
This is part of the integration routine for objects with infinite mass.
virtual Mdouble getInvMass () const
virtual Mdouble getCurvature (const Vec3D &labFixedCoordinates) const
virtual bool isFaceContact (const Vec3D &normal) const
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Private Attributes
std::vector< BaseWall * > walls_
Additional Inherited Members
Static Public Member Functions inherited from BaseWall
static void addToVTK (const std::vector< Vec3D > &points, VTKContainer &vtk)
Takes the points provided and adds a triangle strip connecting these points to the vtk container.
Detailed Description
Restriction of a wall to the intersection with another wall.
This is a class defining walls. It defines the interaction of regular walls and periodic walls with particles as defined in Particle Modifications:
Constructor & Destructor Documentation
BasicIntersectionOfWalls() [1/2]
BasicIntersectionOfWalls::BasicIntersectionOfWalls ()
Default constructor, the normal is infinitely long.
 {
     logger(DEBUG, "BasicIntersectionOfWalls::BasicIntersectionOfWalls ) finished");
 }
References DEBUG, and logger.
Referenced by copy().
BasicIntersectionOfWalls() [2/2]
BasicIntersectionOfWalls::BasicIntersectionOfWalls (const BasicIntersectionOfWalls & b)
Copy constructor, copy the given wall.
Parameters
[in] w BasicIntersectionOfWalls that has to be copied.
First copy the attributes of the BaseWall, then copy the ones that are specific for the BasicIntersectionOfWalls.
         : BaseWall(b)
 {
     for (auto& w : b.walls_)
     {
         walls_.push_back(w->copy());
     }
     logger(DEBUG, "BasicIntersectionOfWalls::BasicIntersectionOfWalls(const BasicIntersectionOfWalls &p) finished");
 }
References b, DEBUG, logger, w, and walls_.
~BasicIntersectionOfWalls()
BasicIntersectionOfWalls::~BasicIntersectionOfWalls () override
Default destructor.
 {
     for (auto& w : walls_)
     {
         delete w;
     }
     logger(DEBUG, "BasicIntersectionOfWalls::~BasicIntersectionOfWalls finished");
 }
References DEBUG, logger, w, and walls_.
Member Function Documentation
add()
void BasicIntersectionOfWalls::add (BaseWall & wall)
Defines a standard wall, given an outward normal vector s.t. normal*x=normal*point for all x of the wall.
Todo:
TW maybe the Restricted wall should be templated with the wall type such that we don't need to use new and delete.
 {
     walls_.push_back(wall.copy());
     walls_.back()->setId(walls_.size());
 }
References BaseWall::copy(), and walls_.
Referenced by UnionOfWalls::setupInitialConditions().
copy()
BasicIntersectionOfWalls * BasicIntersectionOfWalls::copy () const override virtual
Wall copy method. It calls the copy constructor of this Wall, useful for polymorphism.
Wall copy method. It calls the copy constructor of this Wall, useful for polymorphism
Implements BaseWall.
 {
     return new BasicIntersectionOfWalls(*this);
 }
References BasicIntersectionOfWalls().
getDistanceAndNormal()
bool BasicIntersectionOfWalls::getDistanceAndNormal (const BaseParticle & p, Mdouble & distance, Vec3D & normal) const override virtual
Compute the distance from the wall for a given BaseParticle and return if there is a collision. If there is a collision, also return the normal vector.
Parameters
[in] p BaseParticle for which the distance to the wall must be computed.
[out] distance Distance between the particle and the wall.
[out] normal The normal of this wall, will only be set if there is a collision.
Returns
A boolean value for whether or not there is a collision.
Return the smallest distance and normal
Implements BaseWall.
 {
     if (walls_.empty())
     {
         logger(DEBUG, "Empty BasicIntersectionOfWalls");
         return false;
     }
     distance = -constants::inf; //distance of the closest wall
     Mdouble distance2 = -constants::inf; //distance of the second-closest wall
     Mdouble distance3 = -constants::inf; //distance of the third-closest wall
     Mdouble distanceCurrent; //distance of teh current wall
     Vec3D normal2; //normal of the second-closest wall
     Vec3D normal3; //normal of the third-closest wall
     Vec3D normalCurrent; //normal of the current wall
     unsigned int id = static_cast<unsigned int>(-1); //id of the closest wall
     unsigned int id2 = static_cast<unsigned int>(-1); //id of the second-closest wall
     unsigned int id3 = static_cast<unsigned int>(-1); //id of the third-closest wall
     Mdouble wallInteractionRadius = p.getWallInteractionRadius(this);
     Vec3D position = p.getPosition() - getPosition();
     getOrientation().rotateBack(position);
     SphericalParticle shifted;
     shifted.setSpecies(p.getSpecies());
     shifted.setPosition(position);
     shifted.setRadius(p.getRadius());
     //The object has to touch each wall each wall (distanceCurrent) and keep the minimum distance (distance) and wall index (id)
     for (unsigned int i = 0; i < walls_.size(); i++)
     {
         //immediately stop if one of teh walls is not in interaction distance
         if (!walls_[i]->getDistanceAndNormal(shifted, distanceCurrent, normalCurrent))
             return false;
         // Find out which of the walls is interacting with the particle.
         // Keep the minimum distance (distance) and wall index (id)
         // and store up to two walls (id2, id3) and their distances (distance2, distance3),
         // if the possible contact point is near the intersection between id and id2 (and id3)
         if (distanceCurrent > distance)
         {
             if (distance > -wallInteractionRadius)
             {
                 if (distance2 > -wallInteractionRadius)
                 {
                     distance3 = distance;
                     normal3 = normal;
                     id3 = id;
                 }
                 else
                 {
                     distance2 = distance;
                     normal2 = normal;
                     id2 = id;
                 }
             }
             distance = distanceCurrent;
             normal = normalCurrent;
             id = i;
         }
         else if (distanceCurrent > -wallInteractionRadius)
         {
             if (distance2 > -wallInteractionRadius)
             {
                 distance3 = distanceCurrent;
                 normal3 = normalCurrent;
                 id3 = i;
             }
             else
             {
                 distance2 = distanceCurrent;
                 normal2 = normalCurrent;
                 id2 = i;
             }
         }
     }
     //logger(INFO, "particle %: contact with % % %, n % % %", p.getId(), distance, distance2, distance3, normal, normal2, normal3);
     //If we are here, the closest wall is id;
     //if distance2>-P.Radius, it's a possible face or vertex contact
     //if distance3>-P.Radius, it's a possible vertex contact
     if (distance2 > -wallInteractionRadius)
     {
         //contact point on wall id
         SphericalParticle contact;
         contact.setSpecies(p.getSpecies());
         contact.setPosition(position + distance * normal);
         contact.setRadius(0);
         //If the distance of D to id2 is positive, the contact is with the intersection
         bool contactPointOutsideID2 = !walls_[id2]->getDistanceAndNormal(contact, distanceCurrent, normalCurrent);
         if (distance3 > -wallInteractionRadius &&
             !walls_[id3]->getDistanceAndNormal(contact, distanceCurrent, normalCurrent))
         {
             if (contactPointOutsideID2)
             {
                 //find vertex C
                 Matrix3D N(normal.X, normal.Y, normal.Z, normal2.X, normal2.Y, normal2.Z, normal3.X, normal3.Y,
                            normal3.Z);
                 Vec3D P(Vec3D::dot(position, normal) + distance, Vec3D::dot(position, normal2) + distance2,
                         Vec3D::dot(position, normal3) + distance3);
                 Vec3D vertex = N.ldivide(P);
                 normal = position - vertex;
                 distance = sqrt(normal.getLengthSquared());
                 if (distance >= wallInteractionRadius)
                     return false; //no contact
                 normal /= -distance;
                 //logger(INFO, "vertex contact with % % %: pos %, n %, d %", id, id2, id3, p.getPosition(), normal, distance);
                 getOrientation().rotate(normal);
                 return true;
             }
             else
             {
                 contactPointOutsideID2 = true;
                 distance2 = distance3;
                 id2 = id3;
             }
         }
         if (contactPointOutsideID2)
         {
             //find contact point C
             normal3 = Vec3D::cross(normal, normal2);
             Matrix3D N(normal.X, normal.Y, normal.Z, normal2.X, normal2.Y, normal2.Z, normal3.X, normal3.Y,
                        normal3.Z);
             Vec3D P(Vec3D::dot(position, normal) + distance, Vec3D::dot(position, normal2) + distance2,
                     Vec3D::dot(position, normal3));
             Vec3D C = N.ldivide(P);
             normal = position - C;
             distance = sqrt(normal.getLengthSquared());
             if (distance >= wallInteractionRadius)
                 return false; //no contact
             normal /= -distance;
             //logger(INFO, "edge contact with % %: normal %", id, id2, normal);
             getOrientation().rotate(normal);
             return true;
         }
     }
     //logger(INFO, "face contact with %", id);
     getOrientation().rotate(normal);
     return true;
 }
References Vec3D::cross(), DEBUG, Vec3D::dot(), BaseInteractable::getOrientation(), BaseInteractable::getPosition(), i, constants::inf, logger, N, WallFunction::normal(), Global_Physical_Variables::P, p, Quaternion::rotate(), Quaternion::rotateBack(), BaseInteractable::setPosition(), BaseParticle::setRadius(), BaseParticle::setSpecies(), sqrt(), walls_, Vec3D::X, Vec3D::Y, and Vec3D::Z.
Referenced by getVTK().
getName()
std::string BasicIntersectionOfWalls::getName () const override virtual
Returns the name of the object, in this case the string "BasicIntersectionOfWalls".
Returns
The string "BasicIntersectionOfWalls", which is the name of this class.
Implements BaseObject.
 {
     return "BasicIntersectionOfWalls";
 }
getNumberOfObjects()
unsigned long BasicIntersectionOfWalls::getNumberOfObjects ()
Returns the number of objects.
Suppose your simulation adds to an BasicIntersectionOfWalls after a certain time or condition is met. Checking the number of objects is useful for checking if this has happened yet, when restarting.
 {
     return walls_.size();
 }
References walls_.
getObject()
BaseWall * BasicIntersectionOfWalls::getObject (unsigned i)
 {
     logger.assert_always(walls_.size() > i, "Index % exceeds number of walls %", i, walls_.size());
     return walls_[i];
 }
References i, logger, and walls_.
getVTK()
void BasicIntersectionOfWalls::getVTK (std::vector< Vec3D > & points, std::vector< std::vector< double >> & triangleStrips)
Todo:
change getVTK to writeVTK
Parameters
points
triangleStrips
Todo:
this function could be improved; might not plot full wall
 {
 //    for (auto w : walls_) {
 //        w->writeVTK (points, triangleStrips);
 //    }
     //writes points and strips for all walls; points are added to the global point vector, but the strips are held back
     std::vector<std::vector<double>> myTriangleStrips;
     unsigned long n = points.size();
     for (auto w : walls_)
     {
         w->getVTK(points, myTriangleStrips);
     }
     //add position of the BasicIntersectionOfWalls to the point
     for (std::vector<Vec3D>::iterator p = points.begin() + n; p != points.end(); p++)
     {
         getOrientation().rotate(*p);
     }
     //create a vector which points are in the wall (actually, only the new points are necessary)
     std::vector<bool> pointInWall;
     pointInWall.reserve(points.size());
     SphericalParticle particle;
     particle.setSpecies(getSpecies());
     particle.setRadius(1e-10); //points within that distance are declared part of the wall
     Mdouble distance;
     Vec3D normal;
     for (auto p : points)
     {
         particle.setPosition(p);
         pointInWall.push_back(getDistanceAndNormal(particle, distance, normal));
     }
     //now loop through myTriangleStrips to find the strip parts that are fully inside the wall
     std::vector<double> strip;
     for (auto t : myTriangleStrips)
     {
         for (unsigned i : t)
         {
             if (pointInWall[i] == true)
             {
                 strip.push_back(i);
             }
             else
             {
                 if (strip.size() > 2)
                     triangleStrips.push_back(strip);
                 strip.clear();
             }
         }
         if (strip.size() > 2)
             triangleStrips.push_back(strip);
         strip.clear();
     }
 }
References e(), getDistanceAndNormal(), BaseInteractable::getOrientation(), BaseInteractable::getSpecies(), i, n, WallFunction::normal(), p, Quaternion::rotate(), BaseInteractable::setPosition(), BaseParticle::setRadius(), BaseParticle::setSpecies(), plotPSD::t, w, and walls_.
oldRead()
void BasicIntersectionOfWalls::oldRead (std::istream & is)
Reads BasicIntersectionOfWalls from an old-style restart file.
read()
void BasicIntersectionOfWalls::read (std::istream & is) override virtual
Reads BasicIntersectionOfWalls from a restart file.
Parameters
[in] is The input stream from which the BasicIntersectionOfWalls is read.
Reimplemented from BaseWall.
 {
     BaseWall::read(is);
     std::string dummy;
     unsigned size;
     // read e.g. "numIntersectionOfWalls 2"
     is >> dummy >> size;
     for (unsigned i = 0; i < size; i++)
     {
         std::string type;
         // read e.g. "IntersectionOfWalls"
         is >> type;
         BaseWall* wall = getHandler()->createObject(type);
         wall->setHandler(getHandler());
         wall->read(is);
         walls_.push_back(wall);
         walls_.back()->setId(walls_.size());
     }
 }
References WallHandler::createObject(), BaseWall::getHandler(), i, BaseWall::read(), BaseWall::setHandler(), size, oomph::Global_string_for_annotation::string(), compute_granudrum_aor::type, and walls_.
write()
void BasicIntersectionOfWalls::write (std::ostream & os) const override virtual
Writes the BasicIntersectionOfWalls to an output stream, usually a restart file.
Parameters
[in] os The output stream the BasicIntersectionOfWalls is written to.
Reimplemented from BaseWall.
 {
     BaseWall::write(os);
     os << " numIntersectionOfWalls " << walls_.size();
     for (auto w : walls_)
     {
         os << " ";
         w->write(os);
     }
 }
References w, walls_, and BaseWall::write().
Member Data Documentation
walls_
std::vector<BaseWall*> BasicIntersectionOfWalls::walls_ private
Outward normal vector. This does not have to be a unit vector.
Referenced by add(), BasicIntersectionOfWalls(), getDistanceAndNormal(), getNumberOfObjects(), getObject(), getVTK(), read(), write(), and ~BasicIntersectionOfWalls().
The documentation for this class was generated from the following files:
BasicIntersectionOfWalls.h
BasicIntersectionOfWalls.cc