MercuryDPM: CylindricalWall Class Reference
CylindricalWall Class Reference
#include <CylindricalWall.h>
Public Member Functions
CylindricalWall ()
CylindricalWall (const CylindricalWall &p)
CylindricalWall (double radius)
CylindricalWall * copy () const override
Wall copy method. It calls the copy contrustor of this Wall, usefull for polymorfism.
void set (Mdouble radius)
Defines a standard wall, given an outward normal vector s. t. normal*x=position.
bool getDistanceAndNormal (const BaseParticle &P, Mdouble &distance, Vec3D &normal_return) const override
Since this function should be called before calculating any Particle-Wall interactions, it can also be used to set the normal vector in case of curved walls.
void read (std::istream &is) override
reads wall
void oldRead (std::istream &is)
void write (std::ostream &os) const override
outputs wall
std::string getName () const override
Returns the name of the object.
double getRadius () const
access function for radius
Public Member Functions inherited from BaseWall
BaseWall ()
Default constructor.
BaseWall (const BaseWall &w)
Copy constructor.
~BaseWall () override
Default destructor.
virtual bool getDistanceNormalOverlap (const BaseParticle &P, Mdouble &distance, Vec3D &normal_return, Mdouble &overlap) const
virtual bool getDistanceNormalOverlapSuperquadric (const SuperQuadricParticle &p, Mdouble &distance, Vec3D &normal_return, Mdouble &overlap) const
virtual Vec3D getFurthestPointSuperQuadric (const Vec3D &normalBodyFixed, const Vec3D &axes, Mdouble eps1, Mdouble eps2) const
virtual void setHandler (WallHandler *handler)
A function which sets the WallHandler for this BaseWall.
WallHandler * getHandler () const
A function which returns the WallHandler that handles this BaseWall.
void setIndSpecies (unsigned int indSpecies) override
Define the species of this wall using the index of the species in the SpeciesHandler in this DPMBase.
void setSpecies (const ParticleSpecies *species)
Defines the species of the current wall.
bool isFixed () const override
void setForceControl (Vec3D forceGoal, Vec3D gainFactor, Vec3D baseVelocity={0, 0, 0})
Slowly adjusts the force on a wall towards a specified goal, by adjusting (prescribing) the velocity of the wall.
virtual bool isLocal (Vec3D &min, Vec3D &max) const
bool getLinePlaneIntersect (Vec3D &intersect, const Vec3D &p0, const Vec3D &p1, const Vec3D &n, const Vec3D &p)
bool isInsideWallVTK (const Vec3D &point, const Vec3D &normal, const Vec3D &position) const
void projectOntoWallVTK (Vec3D &point0, const Vec3D &point1, const Vec3D &normal, const Vec3D &position) const
void intersectVTK (std::vector< Vec3D > &points, Vec3D normal, Vec3D position) const
virtual BaseInteraction * getInteractionWithSuperQuad (SuperQuadricParticle *p, unsigned timeStamp, InteractionHandler *interactionHandler)
virtual void writeVTK (VTKContainer &vtk) const
void getVTK (std::vector< Vec3D > &points, std::vector< std::vector< double >> &triangleStrips)
const Vec3D getAxis () const
BaseInteraction * getInteractionWith (BaseParticle *p, unsigned timeStamp, InteractionHandler *interactionHandler) override
Returns the interaction between this wall and a given particle, nullptr if there is no interaction.
virtual void actionsOnRestart ()
No implementation but can be overidden in its derived classes.
virtual void actionsAfterParticleGhostUpdate ()
No implementation but can be overidden in its derived classes.
virtual void handleParticleAddition (unsigned int id, BaseParticle *p)
Handles the addition of particles to the particleHandler.
virtual void handleParticleRemoval (unsigned int id)
Handles the addition of particles to the particleHandler.
virtual void checkInteractions (InteractionHandler *interactionHandler, unsigned int timeStamp)
Check if all interactions are valid.
bool getVTKVisibility () const
void setVTKVisibility (bool vtkVisibility)
void addRenderedWall (BaseWall *w)
BaseWall * getRenderedWall (size_t i) const
std::vector< BaseWall * > getRenderedWalls () const
void removeRenderedWalls ()
void renderWall (VTKContainer &vtk)
void addParticlesAtWall (unsigned numElements=50)
void setVelocityControl (Vec3D forceGoal, Vec3D gainFactor, Vec3D baseVelocity)
virtual void writeWallDetailsVTK (VTKData &data) const
virtual void computeWear ()
Public Member Functions inherited from BaseInteractable
BaseInteractable ()
Default BaseInteractable constructor.
BaseInteractable (const BaseInteractable &p)
Copy constructor.
~BaseInteractable () override
Destructor, it simply destructs the BaseInteractable and all the objects it contains.
unsigned int getIndSpecies () const
Returns the index of the species associated with the interactable object.
const ParticleSpecies * getSpecies () const
Returns a pointer to the species of this BaseInteractable.
void setSpecies (const ParticleSpecies *species)
Sets the species of this BaseInteractable.
const Vec3D & getForce () const
Returns the force on this BaseInteractable.
const Vec3D & getTorque () const
Returns the torque on this BaseInteractable.
void setForce (const Vec3D &force)
Sets the force on this BaseInteractable.
void setTorque (const Vec3D &torque)
Sets the torque on this BaseInteractable.
void addForce (const Vec3D &addForce)
Adds an amount to the force on this BaseInteractable.
void addTorque (const Vec3D &addTorque)
Adds an amount to the torque on this BaseInteractable.
virtual void resetForceTorque (int numberOfOMPthreads)
void sumForceTorqueOMP ()
const Vec3D & getPosition () const
Returns the position of this BaseInteractable.
const Quaternion & getOrientation () const
Returns the orientation of this BaseInteractable.
virtual void setPosition (const Vec3D &position)
Sets the position of this BaseInteractable.
void setOrientationViaNormal (Vec3D normal)
Sets the orientation of this BaseInteractable by defining the vector that results from the rotation of the (1,0,0) vector.
void setOrientationViaEuler (Vec3D eulerAngle)
Sets the orientation of this BaseInteractable by defining the euler angles.
virtual void setOrientation (const Quaternion &orientation)
Sets the orientation of this BaseInteractable.
virtual void move (const Vec3D &move)
Moves this BaseInteractable by adding an amount to the position.
virtual void rotate (const Vec3D &angularVelocityDt)
Rotates this BaseInteractable.
const std::vector< BaseInteraction * > & getInteractions () const
Returns a list of interactions which belong to this interactable.
void addInteraction (BaseInteraction *I)
Adds an interaction to this BaseInteractable.
bool removeInteraction (BaseInteraction *I)
Removes an interaction from this BaseInteractable.
void copyInteractionsForPeriodicParticles (const BaseInteractable &p)
Copies interactions to this BaseInteractable whenever a periodic copy made.
void setVelocity (const Vec3D &velocity)
set the velocity of the BaseInteractable.
void setAngularVelocity (const Vec3D &angularVelocity)
set the angular velocity of the BaseInteractble.
void addVelocity (const Vec3D &velocity)
adds an increment to the velocity.
void addAngularVelocity (const Vec3D &angularVelocity)
add an increment to the angular velocity.
virtual const Vec3D & getVelocity () const
Returns the velocity of this interactable.
virtual const Vec3D & getAngularVelocity () const
Returns the angular velocity of this interactable.
void setPrescribedPosition (const std::function< Vec3D(double)> &prescribedPosition)
Allows the position of an infinite mass interactable to be prescribed.
void applyPrescribedPosition (double time)
Computes the position from the user defined prescribed position function.
void setPrescribedVelocity (const std::function< Vec3D(double)> &prescribedVelocity)
Allows the velocity of an infinite mass interactable to be prescribed.
void applyPrescribedVelocity (double time)
Computes the velocity from the user defined prescribed velocity function.
void setPrescribedOrientation (const std::function< Quaternion(double)> &prescribedOrientation)
Allows the orientation of the infinite mass interactbale to be prescribed.
void applyPrescribedOrientation (double time)
Computes the orientation from the user defined prescribed orientation function.
void setPrescribedAngularVelocity (const std::function< Vec3D(double)> &prescribedAngularVelocity)
Allows the angular velocity of the infinite mass interactable to be prescribed.
void applyPrescribedAngularVelocity (double time)
Computes the angular velocity from the user defined prescribed angular velocity.
virtual const Vec3D getVelocityAtContact (const Vec3D &contact) const
Returns the velocity at the contact point, use by many force laws.
void integrateBeforeForceComputation (double time, double timeStep)
This is part of integrate routine for objects with infinite mass.
void integrateAfterForceComputation (double time, double timeStep)
This is part of the integration routine for objects with infinite mass.
virtual Mdouble getInvMass () const
virtual Mdouble getCurvature (const Vec3D &labFixedCoordinates) const
virtual bool isFaceContact (const Vec3D &normal) const
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Private Attributes
Mdouble radius_
Additional Inherited Members
Static Public Member Functions inherited from BaseWall
static void addToVTK (const std::vector< Vec3D > &points, VTKContainer &vtk)
Takes the points provided and adds a triangle strip connecting these points to the vtk container.
Detailed Description
Deprecated:
This class will be gone in Mercury 2.0, use AxisymmetricIntersectionOfWalls instead.
Constructor & Destructor Documentation
CylindricalWall() [1/3]
CylindricalWall::CylindricalWall ()
         : BaseWall()
 {
     radius_ = std::numeric_limits<double>::quiet_NaN();
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"CylindricalWall () finished"<<std::endl;
 #endif
 }
References radius_.
Referenced by copy().
CylindricalWall() [2/3]
CylindricalWall::CylindricalWall (const CylindricalWall & p)
         : BaseWall(p)
 {
     radius_ = p.radius_;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"CylindricalWall (const CylindricalWall &p) finished"<<std::endl;
 #endif
 }
References p, and radius_.
CylindricalWall() [3/3]
CylindricalWall::CylindricalWall (double radius) explicit
         : BaseWall()
 {
     this->radius_ = radius;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"CylindricalWall (double radius) finished"<<std::endl;
 #endif
 }
References UniformPSDSelfTest::radius, and radius_.
Member Function Documentation
copy()
CylindricalWall * CylindricalWall::copy () const override virtual
Wall copy method. It calls the copy contrustor of this Wall, usefull for polymorfism.
Implements BaseWall.
 {
     return new CylindricalWall(*this);
 }
References CylindricalWall().
getDistanceAndNormal()
bool CylindricalWall::getDistanceAndNormal (const BaseParticle & P, Mdouble & distance, Vec3D & normal_return) const override virtual
Since this function should be called before calculating any Particle-Wall interactions, it can also be used to set the normal vector in case of curved walls.
Implements BaseWall.
 {
     double R = sqrt(pow(P.getPosition().X, 2) + pow(P.getPosition().Y, 2));
     distance = radius_ - R;
     if (distance >= P.getRadius())
         return false;
     normal_return.X = P.getPosition().X;
     normal_return.Y = P.getPosition().Y;
     normal_return.Z = 0.0;
     normal_return /= normal_return.getLength();
     return true;
 }
References Vec3D::getLength(), Global_Physical_Variables::P, Eigen::bfloat16_impl::pow(), R, radius_, sqrt(), Vec3D::X, Vec3D::Y, and Vec3D::Z.
getName()
std::string CylindricalWall::getName () const override virtual
Returns the name of the object.
Implements BaseObject.
 {
     return "CylindricalWall";
 }
getRadius()
double CylindricalWall::getRadius () const
access function for radius
 {
     return radius_;
 }
References radius_.
oldRead()
void CylindricalWall::oldRead (std::istream & is)
 {
     std::string dummy;
     is >> dummy >> radius_;
 }
References radius_, and oomph::Global_string_for_annotation::string().
read()
void CylindricalWall::read (std::istream & is) override virtual
reads wall
Reimplemented from BaseWall.
 {
     BaseWall::read(is);
     std::string dummy;
     is >> dummy >> radius_;
 }
References radius_, BaseWall::read(), and oomph::Global_string_for_annotation::string().
set()
void CylindricalWall::set (Mdouble radius)
Defines a standard wall, given an outward normal vector s. t. normal*x=position.
 {
     this->radius_ = radius;
 }
References UniformPSDSelfTest::radius, and radius_.
Referenced by FullRestartTest::setupInitialConditions().
write()
void CylindricalWall::write (std::ostream & os) const override virtual
outputs wall
Reimplemented from BaseWall.
 {
     BaseWall::write(os);
     os << "  radius " << radius_;
 }
References radius_, and BaseWall::write().
Member Data Documentation
radius_
Mdouble CylindricalWall::radius_ private
Referenced by CylindricalWall(), getDistanceAndNormal(), getRadius(), oldRead(), read(), set(), and write().
The documentation for this class was generated from the following files:
CylindricalWall.h
CylindricalWall.cc