MercuryDPM: basicbenchmark.h File Reference
basicbenchmark.h File Reference
Enumerations
enum { LazyEval , EarlyEval , OmpEval }
Functions
template<int Mode, typename MatrixType >
void benchBasic_loop (const MatrixType &I, MatrixType &m, int iterations) __attribute__((noinline))
template<int Mode, typename MatrixType >
double benchBasic (const MatrixType &mat, int size, int tries) __attribute__((noinline))
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
LazyEval
EarlyEval
OmpEval
 { LazyEval, EarlyEval, OmpEval };
Function Documentation
benchBasic()
template<int Mode, typename MatrixType > double benchBasic (const MatrixType & mat, int size, int tries)
{
   const int rows = mat.rows();
   const int cols = mat.cols();
   MatrixType I(rows, cols);
   MatrixType m(rows, cols);
   initMatrix_identity(I);
   Eigen::BenchTimer timer;
   for (uint t = 0; t < tries; ++t) {
     initMatrix_random(m);
     timer.start();
     benchBasic_loop<Mode>(I, m, iterations);
     timer.stop();
     cerr << m;
   }
   return timer.value();
 };
References cols, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::cols(), I, initMatrix_identity(), initMatrix_random(), m, rows, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::rows(), and plotPSD::t.
benchBasic_loop()
template<int Mode, typename MatrixType > void benchBasic_loop (const MatrixType & I, MatrixType & m, int iterations)
{
   for (int a = 0; a < iterations; a++) {
     if (Mode == LazyEval) {
       asm("#begin_bench_loop LazyEval");
       if (MatrixType::SizeAtCompileTime != Eigen::Dynamic) asm("#fixedsize");
       m = (I + 0.00005 * (m + m.lazyProduct(m))).eval();
     } else if (Mode == OmpEval) {
       asm("#begin_bench_loop OmpEval");
       if (MatrixType::SizeAtCompileTime != Eigen::Dynamic) asm("#fixedsize");
       m = (I + 0.00005 * (m + m.lazyProduct(m))).eval();
     } else {
       asm("#begin_bench_loop EarlyEval");
       if (MatrixType::SizeAtCompileTime != Eigen::Dynamic) asm("#fixedsize");
       m = I + 0.00005 * (m + m * m);
     }
     asm("#end_bench_loop");
   }
 }
References a, Eigen::Dynamic, I, LazyEval, m, and OmpEval.