MercuryDPM: Eigen::internal::HessenbergDecompositionMatrixHReturnType< MatrixType > Struct Template Reference
Eigen::internal::HessenbergDecompositionMatrixHReturnType< MatrixType > Struct Template Reference
Dense linear problems and decompositions » Reference » Eigenvalues_Module
Expression type for return value of HessenbergDecomposition::matrixH()
#include <HessenbergDecomposition.h>
Public Member Functions
HessenbergDecompositionMatrixHReturnType (const HessenbergDecomposition< MatrixType > &hess)
Constructor.
template<typename ResultType >
void evalTo (ResultType &result) const
Hessenberg matrix in decomposition.
Index rows () const
Index cols () const
Public Member Functions inherited from Eigen::ReturnByValue< HessenbergDecompositionMatrixHReturnType< MatrixType > >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
const Unusable & coeff (Index) const
const Unusable & coeff (Index, Index) const
Unusable & coeffRef (Index)
Unusable & coeffRef (Index, Index)
Protected Attributes
const HessenbergDecomposition< MatrixType > & m_hess
Additional Inherited Members
Public Types inherited from Eigen::ReturnByValue< HessenbergDecompositionMatrixHReturnType< MatrixType > >
typedef internal::traits< HessenbergDecompositionMatrixHReturnType< MatrixType > >::ReturnType ReturnType
typedef internal::dense_xpr_base< ReturnByValue >::type Base
Detailed Description
template<typename MatrixType>
struct Eigen::internal::HessenbergDecompositionMatrixHReturnType< MatrixType >
Expression type for return value of HessenbergDecomposition::matrixH()
\eigenvalues_module
Template Parameters
MatrixType type of matrix in the Hessenberg decomposition
Objects of this type represent the Hessenberg matrix in the Hessenberg decomposition of some matrix. The object holds a reference to the HessenbergDecomposition class until the it is assigned or evaluated for some other reason (the reference should remain valid during the life time of this object). This class is the return type of HessenbergDecomposition::matrixH(); there is probably no other use for this class.
Constructor & Destructor Documentation
HessenbergDecompositionMatrixHReturnType()
template<typename MatrixType > Eigen::internal::HessenbergDecompositionMatrixHReturnType< MatrixType >::HessenbergDecompositionMatrixHReturnType (const HessenbergDecomposition< MatrixType > & hess) inline
Constructor.
Parameters
[in] hess Hessenberg decomposition
 : m_hess(hess) {}
Member Function Documentation
cols()
template<typename MatrixType > Index Eigen::internal::HessenbergDecompositionMatrixHReturnType< MatrixType >::cols () const inline
 { return m_hess.packedMatrix().cols(); }
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
evalTo()
template<typename MatrixType > template<typename ResultType > void Eigen::internal::HessenbergDecompositionMatrixHReturnType< MatrixType >::evalTo (ResultType & result) const inline
Hessenberg matrix in decomposition.
Parameters
[out] result Hessenberg matrix in decomposition hess which was passed to the constructor
{
     result = m_hess.packedMatrix();
     Index n = result.rows();
     if (n > 2) result.bottomLeftCorner(n - 2, n - 2).template triangularView<Lower>().setZero();
   }
References n.
rows()
template<typename MatrixType > Index Eigen::internal::HessenbergDecompositionMatrixHReturnType< MatrixType >::rows () const inline
 { return m_hess.packedMatrix().rows(); }
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
Member Data Documentation
m_hess
template<typename MatrixType > const HessenbergDecomposition<MatrixType>& Eigen::internal::HessenbergDecompositionMatrixHReturnType< MatrixType >::m_hess protected
The documentation for this struct was generated from the following file:
HessenbergDecomposition.h