MercuryDPM: oomph::LinearisedAxisymmetricNavierStokesEquations Class Reference
oomph::LinearisedAxisymmetricNavierStokesEquations Class Reference abstract
#include <linearised_axisym_navier_stokes_elements.h>
Public Member Functions
LinearisedAxisymmetricNavierStokesEquations ()
const double & re () const
Reynolds number.
const double & re_st () const
Product of Reynolds and Strouhal number (=Womersley number)
const int & azimuthal_mode_number () const
Azimuthal mode number k in e^ik(theta) decomposition.
double *& re_pt ()
Pointer to Reynolds number.
double *& re_st_pt ()
Pointer to product of Reynolds and Strouhal number (=Womersley number)
int *& azimuthal_mode_number_pt ()
Pointer to azimuthal mode number k in e^ik(theta) decomposition.
const double & viscosity_ratio () const
double *& viscosity_ratio_pt ()
Pointer to the viscosity ratio.
const double & density_ratio () const
double *& density_ratio_pt ()
Pointer to the density ratio.
virtual unsigned npres_linearised_axi_nst () const =0
virtual unsigned u_index_linearised_axi_nst (const unsigned &i) const
double du_dt_linearised_axi_nst (const unsigned &n, const unsigned &i) const
void disable_ALE ()
void enable_ALE ()
virtual double p_linearised_axi_nst (const unsigned &n_p, const unsigned &i) const =0
virtual int p_index_linearised_axi_nst (const unsigned &i) const
Which nodal value represents the pressure?
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
void output (std::ostream &outfile)
void output (std::ostream &outfile, const unsigned &nplot)
void output (FILE *file_pt)
void output (FILE *file_pt, const unsigned &nplot)
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element's residual Vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
double interpolated_u_linearised_axi_nst (const Vector< double > &s, const unsigned &i) const
double interpolated_p_linearised_axi_nst (const Vector< double > &s, const unsigned &i) const
virtual void get_base_flow_u (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &result) const
LinearisedAxisymmetricNavierStokesEquations ()
const double & re () const
Reynolds number.
double *& re_pt ()
Pointer to Reynolds number.
const double & re_st () const
Product of Reynolds and Strouhal number (=Womersley number)
double *& re_st_pt ()
Pointer to product of Reynolds and Strouhal number (=Womersley number)
const double & re_invfr () const
Global inverse Froude number.
double *& re_invfr_pt ()
Pointer to global inverse Froude number.
const double & re_invro () const
Global Reynolds number multiplied by inverse Rossby number.
double *& re_invro_pt ()
Pointer to global Reynolds number multiplied by inverse Rossby number.
const Vector< double > & g () const
Vector of gravitational components.
Vector< double > *& g_pt ()
Pointer to Vector of gravitational components.
const int & azimuthal_mode_number () const
Azimuthal mode number k in e^ik(theta) decomposition.
int *& azimuthal_mode_number_pt ()
Pointer to azimuthal mode number k in e^ik(theta) decomposition.
const double & viscosity_ratio () const
double *& viscosity_ratio_pt ()
Pointer to the viscosity ratio.
const double & density_ratio () const
double *& density_ratio_pt ()
Pointer to the density ratio.
virtual int get_local_eqn_number_corresponding_to_geometric_dofs (const unsigned &n, const unsigned &i)=0
virtual unsigned npres_lin_axi_nst () const =0
virtual unsigned xhat_index_lin_axi_nst (const unsigned &i) const
virtual unsigned u_index_lin_axi_nst (const unsigned &i) const
double du_dt_lin_axi_nst (const unsigned &n, const unsigned &i) const
double dnodal_position_perturbation_dt_lin_axi_nst (const unsigned &n, const unsigned &i) const
unsigned nexternal_H_data ()
Return the number of external perturbed spine "heights" data.
void disable_ALE ()
void enable_ALE ()
virtual double p_lin_axi_nst (const unsigned &n_p, const unsigned &i) const =0
virtual int p_index_lin_axi_nst (const unsigned &i) const
Which nodal value represents the pressure?
void dkin_energy_dt (double &dkin_en_dt, double &kin_en) const
Get integral of kinetic energy over element plus deriv w.r.t. time.
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
void output (std::ostream &outfile)
void output (std::ostream &outfile, const unsigned &nplot)
void output (FILE *file_pt)
void output (FILE *file_pt, const unsigned &nplot)
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element's residual Vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
double interpolated_u_lin_axi_nst (const Vector< double > &s, const unsigned &i) const
double interpolated_p_lin_axi_nst (const Vector< double > &s, const unsigned &i) const
double interpolated_nodal_position_perturbation_lin_axi_nst (const Vector< double > &s, const unsigned &i) const
void assign_additional_local_eqn_numbers ()
Define the local equation numbering schemes.
LinearisedAxisymmetricNavierStokesEquations ()
const double & re () const
Reynolds number.
const double & re_st () const
Product of Reynolds and Strouhal number (=Womersley number)
const int & azimuthal_mode_number () const
Azimuthal mode number k in e^ik(theta) decomposition.
double *& re_pt ()
Pointer to Reynolds number.
double *& re_st_pt ()
Pointer to product of Reynolds and Strouhal number (=Womersley number)
int *& azimuthal_mode_number_pt ()
Pointer to azimuthal mode number k in e^ik(theta) decomposition.
const double & viscosity_ratio () const
double *& viscosity_ratio_pt ()
Pointer to the viscosity ratio.
const double & density_ratio () const
double *& density_ratio_pt ()
Pointer to the density ratio.
virtual unsigned npres_linearised_axi_nst () const =0
virtual unsigned u_index_linearised_axi_nst (const unsigned &i) const
double du_dt_linearised_axi_nst (const unsigned &n, const unsigned &i) const
void disable_ALE ()
void enable_ALE ()
virtual double p_linearised_axi_nst (const unsigned &n_p, const unsigned &i) const =0
virtual int p_index_linearised_axi_nst (const unsigned &i) const
Which nodal value represents the pressure?
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
void output (std::ostream &outfile)
void output (std::ostream &outfile, const unsigned &nplot)
void output (FILE *file_pt)
void output (FILE *file_pt, const unsigned &nplot)
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element's residual Vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
double interpolated_u_linearised_axi_nst (const Vector< double > &s, const unsigned &i) const
double interpolated_p_linearised_axi_nst (const Vector< double > &s, const unsigned &i) const
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual unsigned nvertex_node () const
virtual Node * vertex_node_pt (const unsigned &j) const
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output an exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output a time-dependent exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Attributes
void(*&)(const double &time, const Vector< double > &x, Vector< double > &f) base_flow_u_fct_pt ()
Access function for the base flow solution pointer.
void(*&)(const double &time, const Vector< double > &x, DenseMatrix< double > &f) base_flow_dudx_fct_pt ()
void(*&)(const double &time, const Vector< double > &x, Vector< double > &f) base_flow_dudt_fct_pt ()
void(*&)(const double &time, const Vector< double > &x, double &f) base_flow_p_fct_pt ()
Access function for the base flow pressure pointer.
void(*&)(const double &time, const Vector< double > &x, RankFourTensor< double > &f) base_flow_d_dudx_dX_fct_pt ()
void(*&)(const double &time, const Vector< double > &x, Vector< double > &f) body_force_fct_pt ()
Access function for the body-force pointer.
double(*&)(const double &time, const Vector< double > &x) source_fct_pt ()
Access function for the source-function pointer.
void(*&)(const double &time, const Vector< double > &x, DenseMatrix< double > &f) base_flow_duds_fct_pt ()
Static Public Attributes
static Vector< double > Gamma
Vector to decide whether the stress-divergence form is used or not.
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Protected Member Functions
virtual int p_local_eqn (const unsigned &n, const unsigned &i)=0
virtual double dshape_and_dtest_eulerian_linearised_axi_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
virtual double dshape_and_dtest_eulerian_at_knot_linearised_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
virtual void pshape_linearised_axi_nst (const Vector< double > &s, Shape &psi) const =0
Compute the pressure shape functions at local coordinate s.
virtual void pshape_linearised_axi_nst (const Vector< double > &s, Shape &psi, Shape &test) const =0
Compute the pressure shape and test functions at local coordinate s.
virtual void get_base_flow_u (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &result) const
virtual void get_base_flow_dudx (const double &time, const unsigned &ipt, const Vector< double > &x, DenseMatrix< double > &result) const
virtual void fill_in_generic_residual_contribution_linearised_axi_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
virtual int p_local_eqn (const unsigned &n, const unsigned &i)=0
virtual double dshape_and_dtest_eulerian_lin_axi_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
virtual double dshape_and_dtest_eulerian_at_knot_lin_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
virtual double dshape_and_dtest_eulerian_and_dnodal_coordinates_at_knot_lin_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const =0
virtual void pshape_lin_axi_nst (const Vector< double > &s, Shape &psi) const =0
Compute the pressure shape functions at local coordinate s.
virtual void pshape_lin_axi_nst (const Vector< double > &s, Shape &psi, Shape &test) const =0
Compute the pressure shape and test functions at local coordinate s.
virtual void get_base_flow_dudx (const double &time, const unsigned &ipt, const Vector< double > &x, DenseMatrix< double > &result) const
virtual void get_base_flow_dudt (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &result) const
virtual void get_base_flow_p (const double &time, const unsigned &ipt, const Vector< double > &x, double &result) const
virtual void get_base_flow_d_dudx_dX (const double &time, const unsigned &ipt, const Vector< double > &x, RankFourTensor< double > &result) const
void get_body_force_base_flow (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &result)
double get_source_base_flow (const double &time, const unsigned &ipt, const Vector< double > &x)
void get_body_force_gradient_base_flow (const double &time, const unsigned &ipt, const Vector< double > &x, DenseMatrix< double > &result)
void get_source_gradient_base_flow (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &result)
virtual void get_base_flow_duds (const double &time, const unsigned &ipt, const Vector< double > &x, DenseMatrix< double > &result) const
virtual void fill_in_generic_residual_contribution_lin_axi_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
virtual int p_local_eqn (const unsigned &n, const unsigned &i)=0
virtual double dshape_and_dtest_eulerian_linearised_axi_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
virtual double dshape_and_dtest_eulerian_at_knot_linearised_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
virtual void pshape_linearised_axi_nst (const Vector< double > &s, Shape &psi) const =0
Compute the pressure shape functions at local coordinate s.
virtual void pshape_linearised_axi_nst (const Vector< double > &s, Shape &psi, Shape &test) const =0
Compute the pressure shape and test functions at local coordinate s.
virtual void get_base_flow_u (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &result) const
virtual void get_base_flow_dudx (const double &time, const unsigned &ipt, const Vector< double > &x, DenseMatrix< double > &result) const
virtual void fill_in_generic_residual_contribution_linearised_axi_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Attributes
double * Viscosity_Ratio_pt
double * Density_Ratio_pt
double * Re_pt
Pointer to global Reynolds number.
double * ReSt_pt
Pointer to global Reynolds number x Strouhal number (=Womersley)
int * Azimuthal_Mode_Number_pt
Pointer to azimuthal mode number k in e^ik(theta) decomposition.
void(* Base_flow_u_fct_pt)(const double &time, const Vector< double > &x, Vector< double > &result)
Pointer to base flow solution (velocity components) function.
void(* Base_flow_dudx_fct_pt)(const double &time, const Vector< double > &x, DenseMatrix< double > &result)
bool ALE_is_disabled
double * ReInvFr_pt
double * ReInvRo_pt
Vector< double > * G_pt
Pointer to global gravity Vector.
void(* Base_flow_dudt_fct_pt)(const double &time, const Vector< double > &x, Vector< double > &result)
void(* Base_flow_p_fct_pt)(const double &time, const Vector< double > &x, double &result)
Pointer to base flow solution (pressure) function.
void(* Base_flow_d_dudx_dX_fct_pt)(const double &time, const Vector< double > &x, RankFourTensor< double > &result)
void(* Body_force_fct_pt)(const double &time, const Vector< double > &x, Vector< double > &result)
Pointer to (base flow) body force function.
double(* Source_fct_pt)(const double &time, const Vector< double > &x)
Pointer to (base flow) volumetric source function.
void(* Base_flow_duds_fct_pt)(const double &time, const Vector< double > &x, DenseMatrix< double > &result)
Vector< int > External_H_local_eqn
Vector< unsigned > External_node
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Static Private Attributes
static int Pressure_not_stored_at_node
static double Default_Physical_Constant_Value
static int Default_Azimuthal_Mode_Number_Value
Static default value for the azimuthal mode number (zero)
static double Default_Physical_Ratio_Value
Static default value for the physical ratios (all initialised to one)
static Vector< double > Default_Gravity_Vector
Static default value for the gravity vector (zero)
Additional Inherited Members
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
A class for elements that solve the linearised unsteady axisymmetric Navier–Stokes equations in cylindrical polar coordinates, \(x_0^* = r^*\) and \(x_1^* = z^* \) with \(\partial / \partial \theta = 0 \). We're solving for the radial, axial and azimuthal (swirl) velocities, \(u_0^* = u_r^*(r^*,z^*,t^*) = u^*(r^*,z^*,t^*), \ u_1^* = u_z^*(r^*,z^*,t^*) = w^*(r^*,z^*,t^*)\) and \(u_2^* = u_\theta^*(r^*,z^*,t^*) = v^*(r^*,z^*,t^*) \), respectively, and the pressure \(p(r^*,z^*,t^*) \).
A class for elements that solve the linearised version of the unsteady Navier–Stokes equations in cylindrical polar coordinates, where we have Fourier-decomposed in the azimuthal direction so that the theta-dependance is replaced by an azimuthal mode number.
Constructor & Destructor Documentation
LinearisedAxisymmetricNavierStokesEquations() [1/3]
oomph::LinearisedAxisymmetricNavierStokesEquations::LinearisedAxisymmetricNavierStokesEquations () inline
Constructor: NULL the base flow solution and the derivatives of the base flow function
    : Base_flow_u_fct_pt(0), Base_flow_dudx_fct_pt(0), ALE_is_disabled(false)
    {
     // Set all the physical parameter pointers to the default value of zero
     Re_pt = &Default_Physical_Constant_Value;
     ReSt_pt = &Default_Physical_Constant_Value;
     // Set the azimuthal mode number to default (zero)
     Azimuthal_Mode_Number_pt = &Default_Azimuthal_Mode_Number_Value;
     // Set the physical ratios to the default value of one
     Viscosity_Ratio_pt = &Default_Physical_Ratio_Value;
     Density_Ratio_pt = &Default_Physical_Ratio_Value;
    }
References Azimuthal_Mode_Number_pt, Default_Azimuthal_Mode_Number_Value, Default_Physical_Constant_Value, Default_Physical_Ratio_Value, Density_Ratio_pt, Re_pt, ReSt_pt, and Viscosity_Ratio_pt.
LinearisedAxisymmetricNavierStokesEquations() [2/3]
oomph::LinearisedAxisymmetricNavierStokesEquations::LinearisedAxisymmetricNavierStokesEquations () inline
Constructor: NULL the base flow solution and the derivatives of the base flow function, as well as the base flow body force and volumetric source function pointers
    : Base_flow_u_fct_pt(0), Base_flow_dudx_fct_pt(0), Base_flow_dudt_fct_pt(0),
    Base_flow_p_fct_pt(0), Base_flow_d_dudx_dX_fct_pt(0),
    Body_force_fct_pt(0), Source_fct_pt(0), Base_flow_duds_fct_pt(0),
    ALE_is_disabled(false)
    {
     // Set all the physical parameter pointers to the default value of zero
     Re_pt = &Default_Physical_Constant_Value;
     ReSt_pt = &Default_Physical_Constant_Value;
     ReInvFr_pt = &Default_Physical_Constant_Value;
     ReInvRo_pt = &Default_Physical_Constant_Value;
     G_pt = &Default_Gravity_Vector;
     // Set the azimuthal mode number to default (zero)
     Azimuthal_Mode_Number_pt = &Default_Azimuthal_Mode_Number_Value;
     // Set the physical ratios to the default value of one
     Viscosity_Ratio_pt = &Default_Physical_Ratio_Value;
     Density_Ratio_pt = &Default_Physical_Ratio_Value;
    }
References Azimuthal_Mode_Number_pt, Default_Azimuthal_Mode_Number_Value, Default_Gravity_Vector, Default_Physical_Constant_Value, Default_Physical_Ratio_Value, Density_Ratio_pt, G_pt, Re_pt, ReInvFr_pt, ReInvRo_pt, ReSt_pt, and Viscosity_Ratio_pt.
LinearisedAxisymmetricNavierStokesEquations() [3/3]
oomph::LinearisedAxisymmetricNavierStokesEquations::LinearisedAxisymmetricNavierStokesEquations () inline
Constructor: NULL the base flow solution and the derivatives of the base flow function
       : Base_flow_u_fct_pt(0), Base_flow_dudx_fct_pt(0), ALE_is_disabled(false)
     {
       // Set all the physical parameter pointers to the default value of zero
       Re_pt = &Default_Physical_Constant_Value;
       ReSt_pt = &Default_Physical_Constant_Value;
       // Set the azimuthal mode number to default (zero)
       Azimuthal_Mode_Number_pt = &Default_Azimuthal_Mode_Number_Value;
       // Set the physical ratios to the default value of one
       Viscosity_Ratio_pt = &Default_Physical_Ratio_Value;
       Density_Ratio_pt = &Default_Physical_Ratio_Value;
     }
References Azimuthal_Mode_Number_pt, Default_Azimuthal_Mode_Number_Value, Default_Physical_Constant_Value, Default_Physical_Ratio_Value, Density_Ratio_pt, Re_pt, ReSt_pt, and Viscosity_Ratio_pt.
Member Function Documentation
assign_additional_local_eqn_numbers()
void oomph::LinearisedAxisymmetricNavierStokesEquations::assign_additional_local_eqn_numbers () inline virtual
Define the local equation numbering schemes.
Reimplemented from oomph::GeneralisedElement.
   {
    // Determine the number of external degrees of freedom
    const unsigned n_external_H = nexternal_H_data();
    // Resize the external degree of freedom counter
    External_H_local_eqn.resize(n_external_H);
    // Loop over the external degrees of freedom
    for(unsigned e=0;e<n_external_H;e++)
     {
      External_H_local_eqn[e] = external_local_eqn(e,0);
     }
   }
References e(), External_H_local_eqn, oomph::GeneralisedElement::external_local_eqn(), and nexternal_H_data().
azimuthal_mode_number() [1/3]
const int& oomph::LinearisedAxisymmetricNavierStokesEquations::azimuthal_mode_number () const inline
Azimuthal mode number k in e^ik(theta) decomposition.
     {
      return *Azimuthal_Mode_Number_pt;
     }
References Azimuthal_Mode_Number_pt.
Referenced by fill_in_generic_residual_contribution_lin_axi_nst(), fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), and strain_rate().
azimuthal_mode_number() [2/3]
const int& oomph::LinearisedAxisymmetricNavierStokesEquations::azimuthal_mode_number () const inline
Azimuthal mode number k in e^ik(theta) decomposition.
     {
      return *Azimuthal_Mode_Number_pt;
     }
References Azimuthal_Mode_Number_pt.
azimuthal_mode_number() [3/3]
const int& oomph::LinearisedAxisymmetricNavierStokesEquations::azimuthal_mode_number () const inline
Azimuthal mode number k in e^ik(theta) decomposition.
     {
       return *Azimuthal_Mode_Number_pt;
     }
References Azimuthal_Mode_Number_pt.
azimuthal_mode_number_pt() [1/3]
int* & oomph::LinearisedAxisymmetricNavierStokesEquations::azimuthal_mode_number_pt () inline
Pointer to azimuthal mode number k in e^ik(theta) decomposition.
 { return Azimuthal_Mode_Number_pt; }
References Azimuthal_Mode_Number_pt.
Referenced by oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::further_build().
azimuthal_mode_number_pt() [2/3]
int* & oomph::LinearisedAxisymmetricNavierStokesEquations::azimuthal_mode_number_pt () inline
Pointer to azimuthal mode number k in e^ik(theta) decomposition.
 { return Azimuthal_Mode_Number_pt; }
References Azimuthal_Mode_Number_pt.
azimuthal_mode_number_pt() [3/3]
int*& oomph::LinearisedAxisymmetricNavierStokesEquations::azimuthal_mode_number_pt () inline
Pointer to azimuthal mode number k in e^ik(theta) decomposition.
     {
       return Azimuthal_Mode_Number_pt;
     }
References Azimuthal_Mode_Number_pt.
density_ratio() [1/3]
const double& oomph::LinearisedAxisymmetricNavierStokesEquations::density_ratio () const inline
Density ratio for element: element's density relative to the viscosity used in the definition of the Reynolds number
 { return *Density_Ratio_pt; }
References Density_Ratio_pt.
Referenced by fill_in_generic_residual_contribution_lin_axi_nst(), fill_in_generic_residual_contribution_linearised_axi_nst(), and oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst().
density_ratio() [2/3]
const double& oomph::LinearisedAxisymmetricNavierStokesEquations::density_ratio () const inline
Density ratio for element: element's density relative to the viscosity used in the definition of the Reynolds number
 { return *Density_Ratio_pt; }
References Density_Ratio_pt.
density_ratio() [3/3]
const double& oomph::LinearisedAxisymmetricNavierStokesEquations::density_ratio () const inline
Density ratio for element: element's density relative to the viscosity used in the definition of the Reynolds number
     {
       return *Density_Ratio_pt;
     }
References Density_Ratio_pt.
density_ratio_pt() [1/3]
double* & oomph::LinearisedAxisymmetricNavierStokesEquations::density_ratio_pt () inline
Pointer to the density ratio.
 { return Density_Ratio_pt; }
References Density_Ratio_pt.
Referenced by oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::further_build().
density_ratio_pt() [2/3]
double* & oomph::LinearisedAxisymmetricNavierStokesEquations::density_ratio_pt () inline
Pointer to the density ratio.
 { return Density_Ratio_pt; }
References Density_Ratio_pt.
density_ratio_pt() [3/3]
double*& oomph::LinearisedAxisymmetricNavierStokesEquations::density_ratio_pt () inline
Pointer to the density ratio.
     {
       return Density_Ratio_pt;
     }
References Density_Ratio_pt.
disable_ALE() [1/3]
void oomph::LinearisedAxisymmetricNavierStokesEquations::disable_ALE () inline virtual
Disable ALE, i.e. assert the mesh is not moving – you do this at your own risk!
Reimplemented from oomph::FiniteElement.
 { ALE_is_disabled = true; }
References ALE_is_disabled.
disable_ALE() [2/3]
void oomph::LinearisedAxisymmetricNavierStokesEquations::disable_ALE () inline virtual
Disable ALE, i.e. assert the mesh is not moving – you do this at your own risk!
Reimplemented from oomph::FiniteElement.
 { ALE_is_disabled = true; }
References ALE_is_disabled.
disable_ALE() [3/3]
void oomph::LinearisedAxisymmetricNavierStokesEquations::disable_ALE () inline virtual
Disable ALE, i.e. assert the mesh is not moving – you do this at your own risk!
Reimplemented from oomph::FiniteElement.
     {
       ALE_is_disabled = true;
     }
References ALE_is_disabled.
dkin_energy_dt()
void oomph::LinearisedAxisymmetricNavierStokesEquations::dkin_energy_dt (double & dkin_en_dt, double & kin_en) const
Get integral of kinetic energy over element plus deriv w.r.t. time.
Get integral of kinetic energy over element. Also return the derivative of the integral of the kinetic energy w.r.t. time. Note that this is the "raw" kinetic energy in the sense that the density ratio has not been included. In problems with two or more fluids the user will have to remember to premultiply certain elements by the appropriate density ratio. ratio.
  {
   // Initialise kinetic energy and its deriv w.r.t. time
   kin_en = 0.0; dkin_en_dt = 0.0;
   // Determine number of nodes in the element
   const unsigned n_node = nnode();
   // Set up memory for the fluid (f) shape functions and their derivatives
   // w.r.t. local coordinates (s).
   Shape psif(n_node);
   DShape dpsifds(n_node,2);
   // Set the Vector to hold local coordinates
   Vector<double> s(2);
   // Get the nodal indices at which the velocity is stored
   unsigned u_nodal_index[6];
   for(unsigned i=0;i<6;++i) { u_nodal_index[i] = u_index_lin_axi_nst(i); }
   // Determine number of integration points
   const unsigned n_intpt = integral_pt()->nweight();
   // Loop over the integration points
   for(unsigned ipt=0;ipt<n_intpt;ipt++)
    {
     // Compute the local coordinates s of the integration point
     for(unsigned i=0;i<2;i++) { s[i] = integral_pt()->knot(ipt,i); }
     // Get the integral weight
     const double w = integral_pt()->weight(ipt);
     // Calculate the derivatives of the fluid shape functions w.r.t. the
     // local coordinates
     this->dshape_local_at_knot(ipt,psif,dpsifds);
     // Get Jacobian of mapping
     const double J = J_eulerian(s);
     // Allocate storage for the r-position and its deriv w.r.t. time
     double interpolated_r = 0.0;
     double interpolated_drdt = 0.0;
     // Allocate storage for the derivatives of the positions
     // w.r.t. local coordinates (s_1 and s_2)
     DenseMatrix<double> interpolated_dxds(2,2,0.0);
     // Allocate storage for the derivative w.r.t. time of the spatial
     // derivatives of the positions
     DenseMatrix<double> interpolated_d_dxds_dt(2,2,0.0);
     // Allocate storage for the velocity components (six of these)
     // and their derivatives w.r.t. time
     Vector<double> interpolated_u(6,0.0);
     Vector<double> dudt(6,0.0);
     // Loop over the element's nodes
     for(unsigned l=0;l<n_node;l++)
      {
       // Cache the shape function
       const double psif_ = psif(l);
       // Loop over the two coordinate directions
       for(unsigned i=0;i<2;i++)
        {
         // Loop over the two coordinate directions (for derivatives)
         for(unsigned j=0;j<2;j++)
          {
           interpolated_dxds(i,j) += this->nodal_position(l,i)*dpsifds(l,j);
           interpolated_d_dxds_dt(i,j) +=
            this->dnodal_position_dt(l,i)*dpsifds(l,j);
          }
        }
       // Calculate the r-position
       interpolated_r += this->nodal_position(l,0)*psif_;
       // Calculate the derivative of the r-position w.r.t. time
       interpolated_drdt += this->dnodal_position_dt(l,0)*psif_;
       // Loop over the six velocity components
       for(unsigned i=0;i<6;i++)
        {
         // Get the value
         const double u_value = this->nodal_value(l,u_nodal_index[i]);
         // Add contribution
         interpolated_u[i] += u_value*psif_;
         // Add contribution to dudt
         dudt[i] += du_dt_lin_axi_nst(l,i)*psif_;
        }
      } // End of loop over the element's nodes
     // Compute sum of square of velocity components and sum of product of
     // velocity components and their time derivatives
     double veloc_squared = 0.0;
     double veloc_multiplied_by_time_deriv = 0.0;
     for(unsigned i=0;i<6;i++)
      {
       veloc_squared += interpolated_u[i]*interpolated_u[i];
       veloc_multiplied_by_time_deriv += interpolated_u[i]*dudt[i];
      }
     // Compute the derivative of the Jacobian of the mapping w.r.t. time
     const double dJdt = interpolated_d_dxds_dt(0,0)*interpolated_dxds(1,1)
      + interpolated_d_dxds_dt(1,1)*interpolated_dxds(0,0)
      + interpolated_d_dxds_dt(1,0)*interpolated_dxds(0,1)
      + interpolated_d_dxds_dt(0,1)*interpolated_dxds(1,0);
     // Add contribution to kinetic energy (no density ratio)
     kin_en += veloc_squared*interpolated_r*J*w;
     // Add contributions to deriv of kinetic energy w.r.t. time
     dkin_en_dt += 2.0*veloc_multiplied_by_time_deriv*interpolated_r*J*w;
     dkin_en_dt += veloc_squared*interpolated_drdt*J*w;
     dkin_en_dt += veloc_squared*interpolated_r*dJdt*w;
    }
  } // End of dkin_energy_dt
References oomph::FiniteElement::dnodal_position_dt(), oomph::FiniteElement::dshape_local_at_knot(), du_dt_lin_axi_nst(), i, oomph::FiniteElement::integral_pt(), J, j, oomph::FiniteElement::J_eulerian(), oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_value(), oomph::Integral::nweight(), s, u_index_lin_axi_nst(), w, and oomph::Integral::weight().
dnodal_position_perturbation_dt_lin_axi_nst()
double oomph::LinearisedAxisymmetricNavierStokesEquations::dnodal_position_perturbation_dt_lin_axi_nst (const unsigned & n, const unsigned & i) const inline
Return the i-th component of dnodal_xhat/dt at local node n. Uses suitably interpolated value for hanging nodes.
    {
     // Get the node's positional timestepper
     TimeStepper* time_stepper_pt =
      this->node_pt(n)->position_time_stepper_pt();
     // Initialise dxhat/dt
     double dnodal_xhat_dt = 0.0;
     // Loop over the timesteps, if there is a non-steady timestepper
     if (!time_stepper_pt->is_steady())
      {
       // Get the index at which the perturbation to the nodal position
       // is stored
       const unsigned xhat_nodal_index = xhat_index_lin_axi_nst(i);
       // Determine number of timsteps (past & present)
       const unsigned n_time = time_stepper_pt->ntstorage();
       // Add the contributions to the time derivative
       for(unsigned t=0;t<n_time;t++)
        {
         dnodal_xhat_dt +=
          time_stepper_pt->weight(1,t)*nodal_value(t,n,xhat_nodal_index);
        }
      }
     return dnodal_xhat_dt;
    }
References i, oomph::TimeStepper::is_steady(), n, oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), oomph::Node::position_time_stepper_pt(), plotPSD::t, oomph::GeomObject::time_stepper_pt(), oomph::TimeStepper::weight(), and xhat_index_lin_axi_nst().
Referenced by fill_in_generic_residual_contribution_lin_axi_nst().
dshape_and_dtest_eulerian_and_dnodal_coordinates_at_knot_lin_axi_nst()
virtual double oomph::LinearisedAxisymmetricNavierStokesEquations::dshape_and_dtest_eulerian_and_dnodal_coordinates_at_knot_lin_axi_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const protected pure virtual
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Implemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
dshape_and_dtest_eulerian_at_knot_lin_axi_nst()
virtual double oomph::LinearisedAxisymmetricNavierStokesEquations::dshape_and_dtest_eulerian_at_knot_lin_axi_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const protected pure virtual
Compute the shape functions and their derivatives w.r.t. global coordinates at the ipt-th integration point. Return Jacobian of mapping between local and global coordinates.
Implemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
Referenced by fill_in_generic_residual_contribution_lin_axi_nst().
dshape_and_dtest_eulerian_at_knot_linearised_axi_nst() [1/2]
virtual double oomph::LinearisedAxisymmetricNavierStokesEquations::dshape_and_dtest_eulerian_at_knot_linearised_axi_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const protected pure virtual
Compute the shape functions and their derivatives w.r.t. global coordinates at the ipt-th integration point. Return Jacobian of mapping between local and global coordinates.
Implemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
Referenced by fill_in_generic_residual_contribution_linearised_axi_nst(), and oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst().
dshape_and_dtest_eulerian_at_knot_linearised_axi_nst() [2/2]
virtual double oomph::LinearisedAxisymmetricNavierStokesEquations::dshape_and_dtest_eulerian_at_knot_linearised_axi_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const protected pure virtual
Compute the shape functions and their derivatives w.r.t. global coordinates at the ipt-th integration point. Return Jacobian of mapping between local and global coordinates.
Implemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
dshape_and_dtest_eulerian_lin_axi_nst()
virtual double oomph::LinearisedAxisymmetricNavierStokesEquations::dshape_and_dtest_eulerian_lin_axi_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const protected pure virtual
Compute the shape functions and their derivatives w.r.t. global coordinates at local coordinate s. Return Jacobian of mapping between local and global coordinates.
Implemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
dshape_and_dtest_eulerian_linearised_axi_nst() [1/2]
virtual double oomph::LinearisedAxisymmetricNavierStokesEquations::dshape_and_dtest_eulerian_linearised_axi_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const protected pure virtual
Compute the shape functions and their derivatives w.r.t. global coordinates at local coordinate s. Return Jacobian of mapping between local and global coordinates.
Implemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
dshape_and_dtest_eulerian_linearised_axi_nst() [2/2]
virtual double oomph::LinearisedAxisymmetricNavierStokesEquations::dshape_and_dtest_eulerian_linearised_axi_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const protected pure virtual
Compute the shape functions and their derivatives w.r.t. global coordinates at local coordinate s. Return Jacobian of mapping between local and global coordinates.
Implemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
du_dt_lin_axi_nst()
double oomph::LinearisedAxisymmetricNavierStokesEquations::du_dt_lin_axi_nst (const unsigned & n, const unsigned & i) const inline
Return the i-th component of du/dt at local node n. Uses suitably interpolated value for hanging nodes.
    {
     // Get the data's timestepper
     TimeStepper* time_stepper_pt = this->node_pt(n)->time_stepper_pt();
     // Initialise dudt
     double dudt = 0.0;
     // Loop over the timesteps, if there is a non-steady timestepper
     if (!time_stepper_pt->is_steady())
      {
       // Get the index at which the velocity is stored
       const unsigned u_nodal_index = u_index_lin_axi_nst(i);
       // Determine number of timsteps (past & present)
       const unsigned n_time = time_stepper_pt->ntstorage();
       // Add the contributions to the time derivative
       for(unsigned t=0;t<n_time;t++)
        {
         dudt += time_stepper_pt->weight(1,t)*nodal_value(t,n,u_nodal_index);
        }
      }
     return dudt;
    }
References i, oomph::TimeStepper::is_steady(), n, oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), plotPSD::t, oomph::GeomObject::time_stepper_pt(), oomph::Data::time_stepper_pt(), u_index_lin_axi_nst(), and oomph::TimeStepper::weight().
Referenced by dkin_energy_dt(), and fill_in_generic_residual_contribution_lin_axi_nst().
du_dt_linearised_axi_nst() [1/2]
double oomph::LinearisedAxisymmetricNavierStokesEquations::du_dt_linearised_axi_nst (const unsigned & n, const unsigned & i) const inline
Return the i-th component of du/dt at local node n. Uses suitably interpolated value for hanging nodes.
    {
     // Get the data's timestepper
     TimeStepper* time_stepper_pt = this->node_pt(n)->time_stepper_pt();
     // Initialise dudt
     double dudt = 0.0;
     // Loop over the timesteps, if there is a non-steady timestepper
     if (!time_stepper_pt->is_steady())
      {
       // Get the index at which the velocity is stored
       const unsigned u_nodal_index = u_index_linearised_axi_nst(i);
       // Determine number of timsteps (past & present)
       const unsigned n_time = time_stepper_pt->ntstorage();
       // Add the contributions to the time derivative
       for(unsigned t=0;t<n_time;t++)
        {
         dudt += time_stepper_pt->weight(1,t)*nodal_value(t,n,u_nodal_index);
        }
      }
     return dudt;
    }
References i, oomph::TimeStepper::is_steady(), n, oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), plotPSD::t, oomph::GeomObject::time_stepper_pt(), oomph::Data::time_stepper_pt(), u_index_linearised_axi_nst(), and oomph::TimeStepper::weight().
Referenced by fill_in_generic_residual_contribution_linearised_axi_nst(), and oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst().
du_dt_linearised_axi_nst() [2/2]
double oomph::LinearisedAxisymmetricNavierStokesEquations::du_dt_linearised_axi_nst (const unsigned & n, const unsigned & i) const inline
Return the i-th component of du/dt at local node n. Uses suitably interpolated value for hanging nodes.
     {
       // Get the data's timestepper
       TimeStepper* time_stepper_pt = this->node_pt(n)->time_stepper_pt();
       // Initialise dudt
       double dudt = 0.0;
       // Loop over the timesteps, if there is a non-steady timestepper
       if (!time_stepper_pt->is_steady())
       {
         // Get the index at which the velocity is stored
         const unsigned u_nodal_index = u_index_linearised_axi_nst(i);
         // Determine number of timsteps (past & present)
         const unsigned n_time = time_stepper_pt->ntstorage();
         // Add the contributions to the time derivative
         for (unsigned t = 0; t < n_time; t++)
         {
           dudt +=
             time_stepper_pt->weight(1, t) * nodal_value(t, n, u_nodal_index);
         }
       }
       return dudt;
     }
References i, oomph::TimeStepper::is_steady(), n, oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), plotPSD::t, oomph::GeomObject::time_stepper_pt(), oomph::Data::time_stepper_pt(), u_index_linearised_axi_nst(), and oomph::TimeStepper::weight().
enable_ALE() [1/3]
void oomph::LinearisedAxisymmetricNavierStokesEquations::enable_ALE () inline virtual
(Re-)enable ALE, i.e. take possible mesh motion into account when evaluating the time-derivative. Note: By default, ALE is enabled, at the expense of possibly creating unnecessary work in problems where the mesh is, in fact, stationary.
Reimplemented from oomph::FiniteElement.
 { ALE_is_disabled = false; }
References ALE_is_disabled.
enable_ALE() [2/3]
void oomph::LinearisedAxisymmetricNavierStokesEquations::enable_ALE () inline virtual
(Re-)enable ALE, i.e. take possible mesh motion into account when evaluating the time-derivative. Note: By default, ALE is enabled, at the expense of possibly creating unnecessary work in problems where the mesh is, in fact, stationary.
Reimplemented from oomph::FiniteElement.
 { ALE_is_disabled = false; }
References ALE_is_disabled.
enable_ALE() [3/3]
void oomph::LinearisedAxisymmetricNavierStokesEquations::enable_ALE () inline virtual
(Re-)enable ALE, i.e. take possible mesh motion into account when evaluating the time-derivative. Note: By default, ALE is enabled, at the expense of possibly creating unnecessary work in problems where the mesh is, in fact, stationary.
Reimplemented from oomph::FiniteElement.
     {
       ALE_is_disabled = false;
     }
References ALE_is_disabled.
fill_in_contribution_to_jacobian() [1/3]
void oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline virtual
Compute the element's residual Vector and the jacobian matrix. Virtual function can be overloaded by hanging-node version.
Reimplemented from oomph::GeneralisedElement.
Reimplemented in RefineableLinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, RefineableLinearisedAxisymmetricQTaylorHoodMultiDomainElement, LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, LinearisedAxisymmetricQTaylorHoodMultiDomainElement, LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, RefineableLinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, RefineableLinearisedAxisymmetricQTaylorHoodMultiDomainElement, LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, and LinearisedAxisymmetricQTaylorHoodMultiDomainElement.
    {
     // Call the generic routine with the flag set to 1
     fill_in_generic_residual_contribution_linearised_axi_nst(
      residuals,jacobian,GeneralisedElement::Dummy_matrix,1);
    }
References oomph::GeneralisedElement::Dummy_matrix, and fill_in_generic_residual_contribution_linearised_axi_nst().
Referenced by LinearisedAxisymmetricQTaylorHoodMultiDomainElement::fill_in_contribution_to_jacobian(), LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement::fill_in_contribution_to_jacobian(), RefineableLinearisedAxisymmetricQTaylorHoodMultiDomainElement::fill_in_contribution_to_jacobian(), and RefineableLinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement::fill_in_contribution_to_jacobian().
fill_in_contribution_to_jacobian() [2/3]
void oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline virtual
Compute the element's residual Vector and the jacobian matrix. Virtual function can be overloaded by hanging-node version.
Reimplemented from oomph::GeneralisedElement.
Reimplemented in RefineableLinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, RefineableLinearisedAxisymmetricQTaylorHoodMultiDomainElement, LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, LinearisedAxisymmetricQTaylorHoodMultiDomainElement, and LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement.
    {
     // Call the generic routine with the flag set to 1
     fill_in_generic_residual_contribution_lin_axi_nst(
      residuals,jacobian,GeneralisedElement::Dummy_matrix,1);
    }
References oomph::GeneralisedElement::Dummy_matrix, and fill_in_generic_residual_contribution_lin_axi_nst().
fill_in_contribution_to_jacobian() [3/3]
void oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline virtual
Compute the element's residual Vector and the jacobian matrix. Virtual function can be overloaded by hanging-node version.
Reimplemented from oomph::FiniteElement.
Reimplemented in RefineableLinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, RefineableLinearisedAxisymmetricQTaylorHoodMultiDomainElement, LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, and LinearisedAxisymmetricQTaylorHoodMultiDomainElement.
     {
       // Call the generic routine with the flag set to 1
       fill_in_generic_residual_contribution_linearised_axi_nst(
         residuals, jacobian, GeneralisedElement::Dummy_matrix, 1);
     }
References oomph::GeneralisedElement::Dummy_matrix, and fill_in_generic_residual_contribution_linearised_axi_nst().
fill_in_contribution_to_jacobian_and_mass_matrix() [1/3]
void oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) inline virtual
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix
Reimplemented from oomph::GeneralisedElement.
    {
     // Call the generic routine with the flag set to 2
     fill_in_generic_residual_contribution_linearised_axi_nst(
      residuals,jacobian,mass_matrix,2);
    }
References fill_in_generic_residual_contribution_linearised_axi_nst().
fill_in_contribution_to_jacobian_and_mass_matrix() [2/3]
void oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) inline virtual
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix
Reimplemented from oomph::GeneralisedElement.
    {
     // Call the generic routine with the flag set to 2
     fill_in_generic_residual_contribution_lin_axi_nst(
      residuals,jacobian,mass_matrix,2);
    }
References fill_in_generic_residual_contribution_lin_axi_nst().
fill_in_contribution_to_jacobian_and_mass_matrix() [3/3]
void oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) inline virtual
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix
Reimplemented from oomph::GeneralisedElement.
     {
       // Call the generic routine with the flag set to 2
       fill_in_generic_residual_contribution_linearised_axi_nst(
         residuals, jacobian, mass_matrix, 2);
     }
References fill_in_generic_residual_contribution_linearised_axi_nst().
fill_in_contribution_to_residuals() [1/3]
void oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_contribution_to_residuals (Vector< double > & residuals) inline virtual
Compute the element's residual Vector.
Reimplemented from oomph::GeneralisedElement.
    {
     // Call the generic residuals function with flag set to 0
     // and using a dummy matrix argument
     fill_in_generic_residual_contribution_linearised_axi_nst(
      residuals,
      GeneralisedElement::Dummy_matrix,
      GeneralisedElement::Dummy_matrix,0);
    }
References oomph::GeneralisedElement::Dummy_matrix, and fill_in_generic_residual_contribution_linearised_axi_nst().
fill_in_contribution_to_residuals() [2/3]
void oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_contribution_to_residuals (Vector< double > & residuals) inline virtual
Compute the element's residual Vector.
Reimplemented from oomph::GeneralisedElement.
    {
     // Call the generic residuals function with flag set to 0
     // and using a dummy matrix argument
     fill_in_generic_residual_contribution_lin_axi_nst(
      residuals,
      GeneralisedElement::Dummy_matrix,
      GeneralisedElement::Dummy_matrix,0);
    }
References oomph::GeneralisedElement::Dummy_matrix, and fill_in_generic_residual_contribution_lin_axi_nst().
fill_in_contribution_to_residuals() [3/3]
void oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_contribution_to_residuals (Vector< double > & residuals) inline virtual
Compute the element's residual Vector.
Reimplemented from oomph::GeneralisedElement.
     {
       // Call the generic residuals function with flag set to 0
       // and using a dummy matrix argument
       fill_in_generic_residual_contribution_linearised_axi_nst(
         residuals,
         GeneralisedElement::Dummy_matrix,
         GeneralisedElement::Dummy_matrix,
         0);
     }
References oomph::GeneralisedElement::Dummy_matrix, and fill_in_generic_residual_contribution_linearised_axi_nst().
fill_in_generic_residual_contribution_lin_axi_nst()
void oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_lin_axi_nst (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, unsigned flag) protected virtual
Compute the residuals for the Navier-Stokes equations; flag=1(or 0): do (or don't) compute the Jacobian as well.
Compute the residuals for the linearised axisymmetric Navier–Stokes equations; flag=1(or 0): do (or don't) compute the Jacobian as well.
  {
   // Get the time from the first node in the element
   const double time = this->node_pt(0)->time_stepper_pt()->time();
   // Determine number of nodes in the element
   const unsigned n_node = nnode();
   // Determine number of nodes along one edge
   const unsigned n_p = nnode_1d();
   // Determine how many pressure values there are associated with
   // a single pressure component
   const unsigned n_pres = npres_lin_axi_nst();
   // Get the nodal indices at which the velocity is stored
   unsigned u_nodal_index[6];
   for(unsigned i=0;i<6;++i)
    {
     u_nodal_index[i] = u_index_lin_axi_nst(i);
    }
   // Get the nodal indices at which the perturbations to the nodal
   // positions are stored
   unsigned xhat_nodal_index[4];
   for(unsigned i=0;i<4;++i)
    {
     xhat_nodal_index[i] = xhat_index_lin_axi_nst(i);
    }
   // Set up memory for the fluid shape and test functions
   // Note that there are two spatial dimensions, r and z, in this problem
   Shape psif(n_node), testf(n_node);
   DShape dpsifds(n_node,2), dpsifdx(n_node,2);
   DShape dtestfds(n_node,2), dtestfdx(n_node,2);
   // Set up memory for the pressure (p) shape and test functions
   Shape psip(n_pres), testp(n_pres);
   // Determine number of integration points
   const unsigned n_intpt = integral_pt()->nweight();
   // Set up memory for the vector to hold local coordinates (two dimensions)
   Vector<double> s(2);
   // Get physical variables from the element
   // (Reynolds number must be multiplied by the density ratio)
   const double scaled_re = re()*density_ratio();
   const double scaled_re_st = re_st()*density_ratio();
   const double scaled_re_inv_fr = re_invfr()*density_ratio();
   const double visc_ratio = viscosity_ratio();
   const Vector<double> G = g();
   const int k = azimuthal_mode_number();
   // Integers used to store the local equation and unknown numbers
   int local_eqn = 0, local_unknown = 0;
   // Loop over the integration points
   for(unsigned ipt=0;ipt<n_intpt;ipt++)
    {
     // Assign values of the local coordinates s
     for(unsigned i=0;i<2;i++) { s[i] = integral_pt()->knot(ipt,i); }
     // Get the integral weight
     const double w = integral_pt()->weight(ipt);
     // Calculate the derivatives of the fluid shape functions w.r.t. the
     // local coordinates
     this->dshape_local_at_knot(ipt,psif,dpsifds);
     // Set the derivatives of the test functions w.r.t. local coords
     // equal to that of the shape functions
     dtestfds = dpsifds;
     // Calculate the fluid shape and test functions, and their derivatives
     // w.r.t. the global coordinates
     const double Jbar =
      dshape_and_dtest_eulerian_at_knot_lin_axi_nst(ipt,psif,dpsifdx,
                                                           testf,dtestfdx);
     // Calculate the pressure shape and test functions
     pshape_lin_axi_nst(s,psip,testp);
     // Allocate storage for the position and the derivative of the
     // mesh positions w.r.t. time
     Vector<double> interpolated_x(2,0.0);
     Vector<double> mesh_velocity(2,0.0);
     // Allocate storage for the derivatives of the unperturbed positions
     // w.r.t. local coordinates (s_1 and s_2)
     DenseMatrix<double> interpolated_dxbar_ds(2,2,0.0);
     // Allocate storage for the perturbed position xhat
     Vector<double> interpolated_xhat(4,0.0);
     // Allocate storage for the derivative of the perturbed position
     // w.r.t. time
     Vector<double> dxhat_dt(4,0.0);
     // Allocate storage for the derivatives of the perturbed positions
     // w.r.t. local coordinates (s_1 and s_2)
     DenseMatrix<double> interpolated_dxhat_ds(4,2,0.0);
     // Allocate storage for the velocity components (six of these)
     // and their derivatives w.r.t. time
     Vector<double> interpolated_u(6,0.0);
     Vector<double> dudt(6,0.0);
     // Allocate storage for the pressure components (two of these)
     Vector<double> interpolated_p(2,0.0);
     // Allocate storage for the derivatives of the velocity components
     // w.r.t. local coordinates (s_1 and s_2)
     DenseMatrix<double> interpolated_duds(6,2,0.0);
     // Calculate pressure at the integration point
     // -------------------------------------------
     // Loop over pressure degrees of freedom (associated with a single
     // pressure component) in the element
     for(unsigned l=0;l<n_pres;l++)
      {
       // Cache the shape function
       const double psip_ = psip(l);
       // Loop over the two pressure components
       for(unsigned i=0;i<2;i++)
        {
         // Get the value
         const double p_value = this->p_lin_axi_nst(l,i);
         // Add contribution
         interpolated_p[i] += p_value*psip_;
        }
      } // End of loop over the pressure degrees of freedom in the element
     // Calculate eulerian positions, perturbations to these positions,
     // ---------------------------------------------------------------
     // velocities and their derivatives at the integration point
     // ---------------------------------------------------------
     // Loop over the element's nodes
     for(unsigned l=0;l<n_node;l++)
      {
       // Cache the shape function
       const double psif_ = psif(l);
       // Loop over the two coordinate directions
       for(unsigned i=0;i<2;i++)
        {
         // Calculate the unperturbed position xbar
         interpolated_x[i] += this->raw_nodal_position(l,i)*psif_;
         // Loop over the two coordinate directions (for derivatives)
         for(unsigned j=0;j<2;j++)
          {
           interpolated_dxbar_ds(i,j) +=
            this->raw_nodal_position(l,i)*dpsifds(l,j);
          }
        }
       // Loop over the four position perturbations R_k^C, R_k^S, Z_k^C, Z_k^S
       for(unsigned i=0;i<4;i++)
        {
         // Get the value
         const double xhat_value = this->raw_nodal_value(l,xhat_nodal_index[i]);
         // Add contribution
         interpolated_xhat[i] += xhat_value*psif_;
         // Loop over the two coordinate directions (for derivatives)
         for(unsigned j=0;j<2;j++)
          {
           interpolated_dxhat_ds(i,j) += xhat_value*dpsifds(l,j);
          }
        }
       // Loop over the six velocity components
       for(unsigned i=0;i<6;i++)
        {
         // Get the value
         const double u_value = this->raw_nodal_value(l,u_nodal_index[i]);
         // Add contribution
         interpolated_u[i] += u_value*psif_;
         // Add contribution to dudt
         dudt[i] += du_dt_lin_axi_nst(l,i)*psif_;
         // Loop over the two coordinate directions (for derivatives)
         for(unsigned j=0;j<2;j++)
          {
           interpolated_duds(i,j) += u_value*dpsifds(l,j);
          }
        }
      } // End of loop over the element's nodes
     // Get the mesh velocity if ALE is enabled
     if(!ALE_is_disabled)
      {
       // Loop over the element's nodes
       for(unsigned l=0;l<n_node;l++)
        {
         // Loop over the two coordinate directions
         for(unsigned i=0;i<2;i++)
          {
           // Calculate the derivative of the unperturbed position xbar
           // w.r.t. time
           mesh_velocity[i] += this->raw_dnodal_position_dt(l,i)*psif(l);
          }
         // Loop over the four perturbed positions R_k^C, R_k^S, Z_k^C, Z_k^S
         for(unsigned i=0;i<4;i++)
          {
           // Calculate the derivative of the perturbed position xhat
           // w.r.t. time
           dxhat_dt[i] +=
            this->dnodal_position_perturbation_dt_lin_axi_nst(l,i)
            *psif(l);
          }
        }
      }
     // Compute the cosine part of the perturbed jacobian at this ipt
     const double JhatC =
      interpolated_dxbar_ds(0,0)*interpolated_dxhat_ds(2,1)
      + interpolated_dxbar_ds(1,1)*interpolated_dxhat_ds(0,0)
      - interpolated_dxbar_ds(0,1)*interpolated_dxhat_ds(2,0)
      - interpolated_dxbar_ds(1,0)*interpolated_dxhat_ds(0,1);
     // Compute the sine part of the perturbed jacobian at this ipt
     const double JhatS =
      interpolated_dxbar_ds(0,0)*interpolated_dxhat_ds(3,1)
      + interpolated_dxbar_ds(1,1)*interpolated_dxhat_ds(1,0)
      - interpolated_dxbar_ds(0,1)*interpolated_dxhat_ds(3,0)
      - interpolated_dxbar_ds(1,0)*interpolated_dxhat_ds(1,1);
     // Determine the inverse of the unperturbed jacobian
     const double invJbar = 1.0/Jbar;
     // Get the user-defined (base flow) body force terms
     Vector<double> body_force(3);
     get_body_force_base_flow(time,ipt,interpolated_x,body_force);
     // Get the user-defined (base flow) source function
     const double source = get_source_base_flow(time,ipt,interpolated_x);
     // Get velocities and their derivatives from base flow problem
     // -----------------------------------------------------------
     // Allocate storage for the velocity components of the base state
     // solution (initialise to zero)
     Vector<double> base_flow_u(3,0.0);
     // Get the base state solution velocity components
     get_base_flow_u(time,ipt,interpolated_x,base_flow_u);
     // Allocate storage for the derivatives of the base state solution's
     // velocity components w.r.t. local coordinates (s_1 and s_2) and
     // global coordinates (r and z)
     // N.B. the derivatives of the base flow components w.r.t. the
     // azimuthal coordinate direction (theta) are always zero since the
     // base flow is axisymmetric
     DenseMatrix<double> base_flow_duds(3,2,0.0);
     DenseMatrix<double> base_flow_dudx(3,2,0.0);
     // Get the derivatives of the base state solution
     // velocity components w.r.t. local and global coordinates
     get_base_flow_duds(time,ipt,interpolated_x,base_flow_duds);
     get_base_flow_dudx(time,ipt,interpolated_x,base_flow_dudx);
     // Allocate storage for the base state pressure at the current
     // integration point
     double base_flow_p = 0.0;
     // Allocate storage for the derivatives of the base state solution
     // velocity components w.r.t. time
     Vector<double> base_flow_dudt(3,0.0);
     // If ALE is enabled, get the base state pressure and the derivatives
     // of the base state velocity w.r.t. time (only needed in this case)
     if(!ALE_is_disabled)
      {
       get_base_flow_p(time,ipt,interpolated_x,base_flow_p);
       get_base_flow_dudt(time,ipt,interpolated_x,base_flow_dudt);
      }
     // Compute the following quantities
     const double interpolated_dUdRC =
      invJbar*(interpolated_dxbar_ds(1,1)*interpolated_duds(0,0)
               + base_flow_duds(0,0)*interpolated_dxhat_ds(2,1)
               - interpolated_dxbar_ds(1,0)*interpolated_duds(0,1)
               - base_flow_duds(0,1)*interpolated_dxhat_ds(2,0));
     const double interpolated_dUdRS =
      invJbar*(interpolated_dxbar_ds(1,1)*interpolated_duds(1,0)
               + base_flow_duds(0,0)*interpolated_dxhat_ds(3,1)
               - interpolated_dxbar_ds(1,0)*interpolated_duds(1,1)
               - base_flow_duds(0,1)*interpolated_dxhat_ds(3,0));
     const double interpolated_dWdRC =
      invJbar*(interpolated_dxbar_ds(1,1)*interpolated_duds(2,0)
               + base_flow_duds(1,0)*interpolated_dxhat_ds(2,1)
               - interpolated_dxbar_ds(1,0)*interpolated_duds(2,1)
               - base_flow_duds(1,1)*interpolated_dxhat_ds(2,0));
     const double interpolated_dWdRS =
      invJbar*(interpolated_dxbar_ds(1,1)*interpolated_duds(3,0)
               + base_flow_duds(1,0)*interpolated_dxhat_ds(3,1)
               - interpolated_dxbar_ds(1,0)*interpolated_duds(3,1)
               - base_flow_duds(1,1)*interpolated_dxhat_ds(3,0));
     const double interpolated_dVdRC =
      invJbar*(interpolated_dxbar_ds(1,1)*interpolated_duds(4,0)
               + base_flow_duds(2,0)*interpolated_dxhat_ds(2,1)
               - interpolated_dxbar_ds(1,0)*interpolated_duds(4,1)
               - base_flow_duds(2,1)*interpolated_dxhat_ds(2,0));
     const double interpolated_dVdRS =
      invJbar*(interpolated_dxbar_ds(1,1)*interpolated_duds(5,0)
               + base_flow_duds(2,0)*interpolated_dxhat_ds(3,1)
               - interpolated_dxbar_ds(1,0)*interpolated_duds(5,1)
               - base_flow_duds(2,1)*interpolated_dxhat_ds(3,0));
     const double interpolated_dUdZC =
      invJbar*(interpolated_dxbar_ds(0,0)*interpolated_duds(0,1)
               + base_flow_duds(0,1)*interpolated_dxhat_ds(0,0)
               - interpolated_dxbar_ds(0,1)*interpolated_duds(0,0)
               - base_flow_duds(0,0)*interpolated_dxhat_ds(0,1));
     const double interpolated_dUdZS =
      invJbar*(interpolated_dxbar_ds(0,0)*interpolated_duds(1,1)
               + base_flow_duds(0,1)*interpolated_dxhat_ds(1,0)
               - interpolated_dxbar_ds(0,1)*interpolated_duds(1,0)
               - base_flow_duds(0,0)*interpolated_dxhat_ds(1,1));
     const double interpolated_dWdZC =
      invJbar*(interpolated_dxbar_ds(0,0)*interpolated_duds(2,1)
               + base_flow_duds(1,1)*interpolated_dxhat_ds(0,0)
               - interpolated_dxbar_ds(0,1)*interpolated_duds(2,0)
               - base_flow_duds(1,0)*interpolated_dxhat_ds(0,1));
     const double interpolated_dWdZS =
      invJbar*(interpolated_dxbar_ds(0,0)*interpolated_duds(3,1)
               + base_flow_duds(1,1)*interpolated_dxhat_ds(1,0)
               - interpolated_dxbar_ds(0,1)*interpolated_duds(3,0)
               - base_flow_duds(1,0)*interpolated_dxhat_ds(1,1));
     const double interpolated_dVdZC =
      invJbar*(interpolated_dxbar_ds(0,0)*interpolated_duds(4,1)
               + base_flow_duds(2,1)*interpolated_dxhat_ds(0,0)
               - interpolated_dxbar_ds(0,1)*interpolated_duds(4,0)
               - base_flow_duds(2,0)*interpolated_dxhat_ds(0,1));
     const double interpolated_dVdZS =
      invJbar*(interpolated_dxbar_ds(0,0)*interpolated_duds(5,1)
               + base_flow_duds(2,1)*interpolated_dxhat_ds(1,0)
               - interpolated_dxbar_ds(0,1)*interpolated_duds(5,0)
               - base_flow_duds(2,0)*interpolated_dxhat_ds(1,1));
     // Define the following useful quantities...
     Vector<double> group_A(n_node,0.0);
     Vector<double> group_B(n_node,0.0);
     Vector<double> group_C(n_node,0.0);
     Vector<double> group_D(n_node,0.0);
     Vector<double> group_E(n_node,0.0);
     DenseMatrix<double> group_F(n_node,n_node,0.0);
     // Loop over the element's nodes
     for(unsigned l=0;l<n_node;l++)
      {
       group_A[l] = interpolated_dxbar_ds(0,0)*dpsifds(l,1)
        - interpolated_dxbar_ds(0,1)*dpsifds(l,0);
       group_B[l] = interpolated_dxbar_ds(1,1)*dpsifds(l,0)
        - interpolated_dxbar_ds(1,0)*dpsifds(l,1);
       group_C[l] = base_flow_duds(0,0)*dpsifds(l,1)
        - base_flow_duds(0,1)*dpsifds(l,0);
       group_D[l] = base_flow_duds(1,0)*dpsifds(l,1)
        - base_flow_duds(1,1)*dpsifds(l,0);
       group_E[l] = base_flow_duds(2,0)*dpsifds(l,1)
        - base_flow_duds(2,1)*dpsifds(l,0);
       // Loop over the element's nodes again
       for(unsigned l2=0;l2<n_node;l2++)
        {
         group_F(l,l2) = dtestfds(l,0)*dpsifds(l2,1)
          - dtestfds(l,1)*dpsifds(l2,0);
        }
      }
     // Allocate storage for the "effective" perturbed spine node fraction
     Vector<double> effective_perturbed_spine_node_fraction(n_node,0.0);
     // Loop over the element's nodes
     for(unsigned l=0;l<n_node;l++)
      {
       // Upcast to a PerturbedSpineNode
       PerturbedSpineNode* nod_pt =
        dynamic_cast<PerturbedSpineNode*>(this->node_pt(l));
       // Cache node update fct id
       const unsigned cached_node_update_fct_id = nod_pt->node_update_fct_id();
       // Set effective perturbed spine node fraction -- this is different
       // depending on whether node l uses the lower (0) or upper (1) node
       // update function
       if(cached_node_update_fct_id==0)
        {
         effective_perturbed_spine_node_fraction[l] = nod_pt->fraction();
        }
       else if(cached_node_update_fct_id==1)
        {
         effective_perturbed_spine_node_fraction[l] = 1.0 - nod_pt->fraction();
        }
       else
        {
         throw OomphLibError("Incorrect node_update_fct_id",
                             "LinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_lin_axi_nst()",
                             OOMPH_EXCEPTION_LOCATION);
        }
      }
     // Cache base flow velocities and their derivatives
     const double base_flow_ur = base_flow_u[0];
     const double base_flow_uz = base_flow_u[1];
     const double base_flow_utheta = base_flow_u[2];
     const double base_flow_durdr = base_flow_dudx(0,0);
     const double base_flow_durdz = base_flow_dudx(0,1);
     const double base_flow_duzdr = base_flow_dudx(1,0);
     const double base_flow_duzdz = base_flow_dudx(1,1);
     const double base_flow_duthetadr = base_flow_dudx(2,0);
     const double base_flow_duthetadz = base_flow_dudx(2,1);
     const double base_flow_durdt = base_flow_dudt[0];
     const double base_flow_duzdt = base_flow_dudt[1];
     const double base_flow_duthetadt = base_flow_dudt[2];
     // Cache r-component of position
     const double r = interpolated_x[0];
     // Cache perturbations to nodal positions
     const double interpolated_RC = interpolated_xhat[0];
     const double interpolated_RS = interpolated_xhat[1];
     const double interpolated_ZC = interpolated_xhat[2];
     const double interpolated_ZS = interpolated_xhat[3];
     // Cache temporal derivatives of the perturbations to nodal positions
     const double dRCdt = dxhat_dt[0];
     const double dRSdt = dxhat_dt[1];
     const double dZCdt = dxhat_dt[2];
     const double dZSdt = dxhat_dt[3];
     // Cache unknowns
     const double interpolated_UC = interpolated_u[0];
     const double interpolated_US = interpolated_u[1];
     const double interpolated_WC = interpolated_u[2];
     const double interpolated_WS = interpolated_u[3];
     const double interpolated_VC = interpolated_u[4];
     const double interpolated_VS = interpolated_u[5];
     const double interpolated_PC = interpolated_p[0];
     const double interpolated_PS = interpolated_p[1];
     // Cache temporal derivatives of the unknowns
     const double dUCdt = dudt[0];
     const double dUSdt = dudt[1];
     const double dWCdt = dudt[2];
     const double dWSdt = dudt[3];
     const double dVCdt = dudt[4];
     const double dVSdt = dudt[5];
     // ==================
     // MOMENTUM EQUATIONS
     // ==================
     // Loop over the fluid test functions
     for(unsigned l=0;l<n_node;l++)
      {
       // Cache test functions and their derivatives
       const double testf_ = testf(l);
       const double dtestfdr = dtestfdx(l,0);
       const double dtestfdz = dtestfdx(l,1);
       // Compute the following useful quantities...
       const double dtestfdRC = invJbar*
        (dtestfds(l,0)*interpolated_dxhat_ds(2,1)
         - dtestfds(l,1)*interpolated_dxhat_ds(2,0));
       const double dtestfdRS = invJbar*
        (dtestfds(l,0)*interpolated_dxhat_ds(3,1)
         - dtestfds(l,1)*interpolated_dxhat_ds(3,0));
       const double dtestfdZC = invJbar*
        (dtestfds(l,1)*interpolated_dxhat_ds(0,0)
         - dtestfds(l,0)*interpolated_dxhat_ds(0,1));
       const double dtestfdZS = invJbar*
        (dtestfds(l,1)*interpolated_dxhat_ds(1,0)
         - dtestfds(l,0)*interpolated_dxhat_ds(1,1));
       // ---------------------------------------------
       // FIRST (RADIAL) MOMENTUM EQUATION: COSINE PART
       // ---------------------------------------------
       // Get local equation number of first velocity value at this node
       local_eqn = nodal_local_eqn(l,u_nodal_index[0]);
       // If it's not a boundary condition
       if(local_eqn >= 0)
        {
         residuals[local_eqn] -= scaled_re_st*r*dUCdt*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re_st*interpolated_RC*base_flow_durdt*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*r*base_flow_ur*interpolated_dUdRC*testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_st*r*mesh_velocity[0]*interpolated_dUdRC*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*r*interpolated_UC*base_flow_durdr*testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_st*r*dRCdt*base_flow_durdr*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*interpolated_RC*base_flow_ur*base_flow_durdr*testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_st*interpolated_RC*mesh_velocity[0]*base_flow_durdr
          *testf_*Jbar*w;
         residuals[local_eqn] -=
          k*scaled_re*base_flow_utheta*interpolated_US*testf_*Jbar*w;
         residuals[local_eqn] +=
          k*scaled_re*base_flow_utheta*base_flow_durdr*interpolated_RS
          *testf_*Jbar*w;
         residuals[local_eqn] +=
          k*scaled_re*base_flow_utheta*base_flow_durdz*interpolated_ZS
          *testf_*Jbar*w;
         residuals[local_eqn] +=
          2*scaled_re*base_flow_utheta*interpolated_VC*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*r*base_flow_uz*interpolated_dUdZC*testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_st*r*mesh_velocity[1]*interpolated_dUdZC*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*r*interpolated_WC*base_flow_durdz*testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_st*r*dZCdt*base_flow_durdz*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*interpolated_RC*base_flow_uz*base_flow_durdz*testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_st*interpolated_RC*mesh_velocity[1]*base_flow_durdz*testf_
          *Jbar*w;
         residuals[local_eqn] += interpolated_RC*body_force[0]*testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_inv_fr*interpolated_RC*G[0]*testf_*Jbar*w;
         residuals[local_eqn] += r*base_flow_p*dtestfdRC*Jbar*w;
         residuals[local_eqn] += r*interpolated_PC*dtestfdr*Jbar*w;
         residuals[local_eqn] += interpolated_RC*base_flow_p*dtestfdr*Jbar*w;
         residuals[local_eqn] -=
          visc_ratio*(1.0+Gamma[0])*r*base_flow_durdr*dtestfdRC*Jbar*w;
         residuals[local_eqn] -=
          visc_ratio*(1.0+Gamma[0])*r*interpolated_dUdRC*dtestfdr*Jbar*w;
         residuals[local_eqn] +=
          visc_ratio*(1.0+Gamma[0])*r*base_flow_durdr*JhatC*dtestfdr*w;
         residuals[local_eqn] -=
          visc_ratio*(1.0+Gamma[0])*interpolated_RC*base_flow_durdr*dtestfdr
          *Jbar*w;
         residuals[local_eqn] +=
          k*visc_ratio*Gamma[0]*base_flow_duthetadr*dtestfdr*interpolated_RS
          *Jbar*w;
         residuals[local_eqn] +=
          k*visc_ratio*Gamma[0]*base_flow_duthetadr*dtestfdz*interpolated_ZS
          *Jbar*w;
         residuals[local_eqn] +=
          k*visc_ratio*Gamma[0]*interpolated_dVdRS*testf_*Jbar*w;
         residuals[local_eqn] -=
          visc_ratio*k*k*interpolated_UC*testf_*Jbar*w/r;
         residuals[local_eqn] +=
          visc_ratio*k*k*base_flow_durdr*interpolated_RC*testf_*Jbar*w/r;
         residuals[local_eqn] +=
          visc_ratio*k*k*base_flow_durdz*interpolated_ZC*testf_*Jbar*w/r;
         residuals[local_eqn] -=
          visc_ratio*k*base_flow_utheta*dtestfdr*interpolated_RS*Jbar*w/r;
         residuals[local_eqn] -=
          visc_ratio*k*base_flow_utheta*dtestfdz*interpolated_ZS*Jbar*w/r;
         residuals[local_eqn] -= visc_ratio*k*interpolated_VS*testf_*Jbar*w/r;
         residuals[local_eqn] +=
          visc_ratio*k*interpolated_RS*base_flow_utheta*testf_*Jbar*w/(r*r);
         residuals[local_eqn] -=
          visc_ratio*Gamma[0]*r*base_flow_duzdr*dtestfdZC*Jbar*w;
         residuals[local_eqn] -=
          visc_ratio*Gamma[0]*r*interpolated_dWdRC*dtestfdz*Jbar*w;
         residuals[local_eqn] +=
          visc_ratio*Gamma[0]*r*base_flow_duzdr*JhatC*dtestfdz*w;
         residuals[local_eqn] -=
          visc_ratio*Gamma[0]*interpolated_RC*base_flow_duzdr*dtestfdz*Jbar*w;
         residuals[local_eqn] -= visc_ratio*r*base_flow_durdz*dtestfdZC*Jbar*w;
         residuals[local_eqn] -=
          visc_ratio*r*interpolated_dUdZC*dtestfdz*Jbar*w;
         residuals[local_eqn] += visc_ratio*r*base_flow_durdz*JhatC*dtestfdz*w;
         residuals[local_eqn] -=
          visc_ratio*interpolated_RC*base_flow_durdz*dtestfdz*Jbar*w;
         residuals[local_eqn] += interpolated_PC*testf_*Jbar*w;
         residuals[local_eqn] -=
          visc_ratio*(1.0+Gamma[0])*k*interpolated_VS*testf_*Jbar*w/r;
         residuals[local_eqn] +=
          visc_ratio*(1.0+Gamma[0])*k*base_flow_duthetadr*interpolated_RS
          *testf_*Jbar*w/r;
         residuals[local_eqn] +=
          visc_ratio*(1.0+Gamma[0])*k*base_flow_duthetadz*interpolated_ZS
          *testf_*Jbar*w/r;
         residuals[local_eqn] -=
          visc_ratio*(1.0+Gamma[0])*interpolated_UC*testf_*Jbar*w/r;
         residuals[local_eqn] +=
          visc_ratio*(1.0+Gamma[0])*base_flow_ur*interpolated_RC
          *testf_*Jbar*w/(r*r);
         residuals[local_eqn] -= scaled_re_st*r*base_flow_durdt*testf_*JhatC*w;
         residuals[local_eqn] +=
          scaled_re*base_flow_utheta*base_flow_utheta*testf_*JhatC*w;
         residuals[local_eqn] += r*body_force[0]*testf_*JhatC*w;
         residuals[local_eqn] += scaled_re_inv_fr*r*G[0]*testf_*JhatC*w;
         residuals[local_eqn] -= k*visc_ratio*base_flow_utheta*testf_*JhatS*w/r;
         residuals[local_eqn] += base_flow_p*testf_*JhatC*w;
         residuals[local_eqn] -=
          visc_ratio*(1.0+Gamma[0])*base_flow_ur*testf_*JhatC*w/r;
         // Calculate the Jacobian
         // ----------------------
         if(flag)
          {
           // Loop over the velocity shape functions again
           for(unsigned l2=0;l2<n_node;l2++)
            {
             // Radial velocity component (cosine part) U_k^C
             local_unknown = nodal_local_eqn(l2,u_nodal_index[0]);
             if(local_unknown >= 0)
              {
               if(flag==2)
                {
                 // Add the mass matrix
                 mass_matrix(local_eqn,local_unknown) +=
                  scaled_re_st*r*psif[l2]*testf_*Jbar*w;
                }
               // Add contributions to the Jacobian matrix
               jacobian(local_eqn,local_unknown) -=
                scaled_re_st*r*psif[l2]
                *node_pt(l2)->time_stepper_pt()->weight(1,0)*testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) -=
                scaled_re*r*base_flow_ur*group_B[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re_st*r*mesh_velocity[0]*group_B[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) -=
                scaled_re*r*psif[l2]*base_flow_durdr*testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) -=
                scaled_re*r*base_flow_uz*group_A[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re_st*r*mesh_velocity[1]*group_A[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*(1.0+Gamma[0])*r*group_B[l2]*dtestfdr*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*k*k*psif[l2]*testf_*Jbar*w/r;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*r*group_A[l2]*dtestfdz*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*(1.0+Gamma[0])*psif[l2]*testf_*Jbar*w/r;
              }
             // Radial velocity component (sine part) U_k^S
             local_unknown = nodal_local_eqn(l2,u_nodal_index[1]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) -=
                k*scaled_re*base_flow_utheta*psif[l2]*testf_*Jbar*w;
              }
             // Axial velocity component (cosine part) W_k^C
             local_unknown = nodal_local_eqn(l2,u_nodal_index[2]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) -=
                scaled_re*r*psif[l2]*base_flow_durdz*testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*Gamma[0]*r*group_B[l2]*dtestfdz*w;
              }
             // Axial velocity component (sine part) W_k^S
             // has no contribution
             // Azimuthal velocity component (cosine part) V_k^C
             local_unknown = nodal_local_eqn(l2,u_nodal_index[4]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) +=
                2.0*scaled_re*base_flow_utheta*psif[l2]*testf_*Jbar*w;
              }
             // Azimuthal velocity component (sine part) V_k^S
             local_unknown = nodal_local_eqn(l2,u_nodal_index[5]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) +=
                k*visc_ratio*Gamma[0]*group_B[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*k*psif[l2]*testf_*Jbar*w/r;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*(1.0+Gamma[0])*k*psif[l2]*testf_*Jbar*w/r;
              }
             // Perturbation to radial nodal coord (cosine part) R_k^C
             local_unknown = nodal_local_eqn(l2,xhat_nodal_index[0]);
             if(local_unknown >= 0)
             {
              jacobian(local_eqn,local_unknown) -=
               scaled_re_st*psif[l2]*base_flow_durdt*testf_*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               scaled_re_st*r*psif[l2]
               *node_pt(l2)->position_time_stepper_pt()->weight(1,0)
               *base_flow_durdr*testf_*Jbar*w;
              jacobian(local_eqn,local_unknown) -=
               scaled_re*psif[l2]*base_flow_ur*base_flow_durdr*testf_*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               scaled_re_st*psif[l2]*mesh_velocity[0]*base_flow_durdr
               *testf_*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               scaled_re*r*base_flow_uz*group_C[l2]*testf_*w;
              jacobian(local_eqn,local_unknown) -=
               scaled_re_st*r*mesh_velocity[1]*group_C[l2]*testf_*w;
              jacobian(local_eqn,local_unknown) -=
               scaled_re*psif[l2]*base_flow_uz*base_flow_durdz*testf_*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               scaled_re_st*psif[l2]*mesh_velocity[1]*base_flow_durdz
               *testf_*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               psif[l2]*body_force[0]*testf_*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               scaled_re_inv_fr*psif[l2]*G[0]*testf_*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               psif[l2]*base_flow_p*dtestfdr*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*(1.0+Gamma[0])*r*base_flow_durdr*group_B[l2]
               *dtestfdr*w;
              jacobian(local_eqn,local_unknown) -=
               visc_ratio*(1.0+Gamma[0])*psif[l2]*base_flow_durdr
               *dtestfdr*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*k*k*base_flow_durdr*psif[l2]*testf_*Jbar*w/r;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*Gamma[0]*r*base_flow_duzdr*group_F(l,l2)*w;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*Gamma[0]*r*base_flow_duzdr*group_B[l2]*dtestfdz*w;
              jacobian(local_eqn,local_unknown) -=
               visc_ratio*Gamma[0]*psif[l2]*base_flow_duzdr*dtestfdz*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*r*base_flow_durdz*group_F(l,l2)*w;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*r*group_C[l2]*dtestfdz*w;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*r*base_flow_durdz*group_B[l2]*dtestfdz*w;
              jacobian(local_eqn,local_unknown) -=
               visc_ratio*psif[l2]*base_flow_durdz*dtestfdz*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*(1.0+Gamma[0])*base_flow_ur*psif[l2]*testf_
               *Jbar*w/(r*r);
              jacobian(local_eqn,local_unknown) -=
               scaled_re_st*r*base_flow_durdt*testf_*group_B[l2]*w;
              jacobian(local_eqn,local_unknown) +=
               scaled_re*base_flow_utheta*base_flow_utheta*testf_*group_B[l2]*w;
              jacobian(local_eqn,local_unknown) +=
               r*body_force[0]*testf_*group_B[l2]*w;
              jacobian(local_eqn,local_unknown) +=
               scaled_re_inv_fr*r*G[0]*testf_*group_B[l2]*w;
              jacobian(local_eqn,local_unknown) +=
               base_flow_p*testf_*group_B[l2]*w;
              jacobian(local_eqn,local_unknown) -=
               visc_ratio*(1.0+Gamma[0])*base_flow_ur*testf_*group_B[l2]*w/r;
             }
             // Perturbation to radial nodal coord (sine part) R_k^S
             local_unknown = nodal_local_eqn(l2,xhat_nodal_index[1]);
             if(local_unknown >= 0)
             {
              jacobian(local_eqn,local_unknown) +=
               k*scaled_re*base_flow_utheta*base_flow_durdr*psif[l2]
               *testf_*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               k*visc_ratio*Gamma[0]*base_flow_duthetadr*dtestfdr*psif[l2]
               *Jbar*w;
              jacobian(local_eqn,local_unknown) -=
               visc_ratio*k*base_flow_utheta*dtestfdr*psif[l2]*Jbar*w/r;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*k*psif[l2]*base_flow_utheta*testf_*Jbar*w/(r*r);
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*(1.0+Gamma[0])*k*base_flow_duthetadr*psif[l2]
               *testf_*Jbar*w/r;
              jacobian(local_eqn,local_unknown) -=
               k*visc_ratio*base_flow_utheta*testf_*group_B[l2]*w/r;
             }
             // Perturbation to axial nodal coord (cosine part) Z_k^C
             local_unknown = nodal_local_eqn(l2,xhat_nodal_index[2]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) -=
                scaled_re*r*base_flow_ur*group_C[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re_st*r*mesh_velocity[0]*group_C[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re_st*r*psif[l2]
                *node_pt(l2)->position_time_stepper_pt()->weight(1,0)
                *base_flow_durdz*testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) +=
                r*base_flow_p*group_F(l,l2)*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*(1.0+Gamma[0])*r*base_flow_durdr*group_F(l,l2)*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*(1.0+Gamma[0])*r*group_C[l2]*dtestfdr*w;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*(1.0+Gamma[0])*r*base_flow_durdr*group_A[l2]
                *dtestfdr*w;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*k*k*base_flow_durdz*psif[l2]*testf_*Jbar*w/r;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*Gamma[0]*r*group_D[l2]*dtestfdz*w;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*Gamma[0]*r*base_flow_duzdr*group_A[l2]*dtestfdz*w;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*r*base_flow_durdz*group_A[l2]*dtestfdz*w;
               jacobian(local_eqn,local_unknown) -=
                scaled_re_st*r*base_flow_durdt*testf_*group_A[l2]*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re*base_flow_utheta*base_flow_utheta*testf_
                *group_A[l2]*w;
               jacobian(local_eqn,local_unknown) +=
                r*body_force[0]*testf_*group_A[l2]*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re_inv_fr*r*G[0]*testf_*group_A[l2]*w;
               jacobian(local_eqn,local_unknown) +=
                base_flow_p*testf_*group_A[l2]*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*(1.0+Gamma[0])*base_flow_ur*testf_*group_A[l2]*w/r;
              }
             // Perturbation to axial nodal coord (sine part) Z_k^S
             local_unknown = nodal_local_eqn(l2,xhat_nodal_index[3]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) +=
                k*scaled_re*base_flow_utheta*base_flow_durdz*psif[l2]
                *testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) +=
                k*visc_ratio*Gamma[0]*base_flow_duthetadr*dtestfdz*psif[l2]
                *Jbar*w;
               jacobian(local_eqn,local_unknown) +=
                k*visc_ratio*Gamma[0]*group_E[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*k*base_flow_utheta*dtestfdz*psif[l2]*Jbar*w/r;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*(1.0+Gamma[0])*k*base_flow_duthetadz*psif[l2]
                *testf_*Jbar*w/r;
               jacobian(local_eqn,local_unknown) -=
                k*visc_ratio*base_flow_utheta*testf_*group_A[l2]*w/r;
              }
            } // End of loop over velocity shape functions
           // Now loop over pressure shape functions
           // (This is the contribution from pressure gradient)
           for(unsigned l2=0;l2<n_pres;l2++)
            {
             // Cosine part P_k^C
             local_unknown = p_local_eqn(l2,0);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) += r*psip[l2]*dtestfdr*Jbar*w;
               jacobian(local_eqn,local_unknown) += psip[l2]*testf_*Jbar*w;
              }
             // Sine part P_k^S has no contribution
            } // End of loop over pressure shape functions
           // Now loop over the spines in the element
           for(unsigned l2=0;l2<n_p;l2++)
            {
             // Perturbed spine "height" (cosine part) H_k^C
             local_unknown =
              get_local_eqn_number_corresponding_to_geometric_dofs(l2,0);
             if(local_unknown >= 0)
              {
               for(unsigned a=0;a<3;a++)
                {
                 double sum = 0.0;
                 sum -= scaled_re*r*base_flow_ur*group_C[l2+(3*a)]*testf_*w;
                 sum += scaled_re_st*r*mesh_velocity[0]*group_C[l2+(3*a)]
                  *testf_*w;
                 sum += scaled_re_st*r*psif[l2+(3*a)]
                  *node_pt(l2+(3*a))->position_time_stepper_pt()->weight(1,0)
                  *base_flow_durdz*testf_*Jbar*w;
                 sum += r*base_flow_p*group_F(l,(l2+(3*a)))*w;
                 sum -= visc_ratio*(1.0+Gamma[0])*r*base_flow_durdr
                  *group_F(l,(l2+(3*a)))*w;
                 sum -= visc_ratio*(1.0+Gamma[0])*r*group_C[l2+(3*a)]
                  *dtestfdr*w;
                 sum += visc_ratio*(1.0+Gamma[0])*r*base_flow_durdr
                  *group_A[l2+(3*a)]*dtestfdr*w;
                 sum += visc_ratio*k*k*base_flow_durdz*psif[l2+(3*a)]
                  *testf_*Jbar*w/r;
                 sum -= visc_ratio*Gamma[0]*r*group_D[l2+(3*a)]*dtestfdz*w;
                 sum += visc_ratio*Gamma[0]*r*base_flow_duzdr
                  *group_A[l2+(3*a)]*dtestfdz*w;
                 sum += visc_ratio*r*base_flow_durdz*group_A[l2+(3*a)]
                  *dtestfdz*w;
                 sum -= scaled_re_st*r*base_flow_durdt*testf_
                  *group_A[l2+(3*a)]*w;
                 sum += scaled_re*base_flow_utheta*base_flow_utheta
                  *testf_*group_A[l2+(3*a)]*w;
                 sum += r*body_force[0]*testf_*group_A[l2+(3*a)]*w;
                 sum += scaled_re_inv_fr*r*G[0]*testf_*group_A[l2+(3*a)]*w;
                 sum += base_flow_p*testf_*group_A[l2+(3*a)]*w;
                 sum -= visc_ratio*(1.0+Gamma[0])*base_flow_ur*testf_
                  *group_A[l2+(3*a)]*w/r;
                 jacobian(local_eqn,local_unknown) +=
                  sum*effective_perturbed_spine_node_fraction[l2+(3*a)];
                }
              }
             // Perturbed spine "height" (sine part) H_k^S
             local_unknown =
              get_local_eqn_number_corresponding_to_geometric_dofs(l2,1);
             if(local_unknown >= 0)
              {
               for(unsigned a=0;a<3;a++)
                {
                 double sum = 0.0;
                 sum += k*scaled_re*base_flow_utheta*base_flow_durdz
                  *psif[l2+(3*a)]*testf_*Jbar*w;
                 sum += k*visc_ratio*Gamma[0]*base_flow_duthetadr*dtestfdz
                  *psif[l2+(3*a)]*Jbar*w;
                 sum += k*visc_ratio*Gamma[0]*group_E[l2+(3*a)]*testf_*w;
                 sum -= visc_ratio*k*base_flow_utheta*dtestfdz
                  *psif[l2+(3*a)]*Jbar*w/r;
                 sum += visc_ratio*(1.0+Gamma[0])*k*base_flow_duthetadz
                  *psif[l2+(3*a)]*testf_*Jbar*w/r;
                 sum -= k*visc_ratio*base_flow_utheta*testf_
                  *group_A[l2+(3*a)]*w/r;
                 jacobian(local_eqn,local_unknown) +=
                  sum*effective_perturbed_spine_node_fraction[l2+(3*a)];
                }
              }
            } // End of loop over spines in the element
          } // End of Jacobian calculation
        } // End of if not boundary condition statement
       // --------------------------------------------
       // SECOND (RADIAL) MOMENTUM EQUATION: SINE PART
       // --------------------------------------------
       // Get local equation number of second velocity value at this node
       local_eqn = nodal_local_eqn(l,u_nodal_index[1]);
       // If it's not a boundary condition
       if(local_eqn >= 0)
        {
         residuals[local_eqn] -= scaled_re_st*r*dUSdt*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re_st*interpolated_RS*base_flow_durdt*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*r*base_flow_ur*interpolated_dUdRS*testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_st*r*mesh_velocity[0]*interpolated_dUdRS*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*r*interpolated_US*base_flow_durdr*testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_st*r*dRSdt*base_flow_durdr*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*interpolated_RS*base_flow_ur*base_flow_durdr
          *testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_st*interpolated_RS*mesh_velocity[0]*base_flow_durdr
          *testf_*Jbar*w;
         residuals[local_eqn] +=
          k*scaled_re*base_flow_utheta*interpolated_UC*testf_*Jbar*w;
         residuals[local_eqn] -=
          k*scaled_re*base_flow_utheta*base_flow_durdr*interpolated_RC
          *testf_*Jbar*w;
         residuals[local_eqn] -=
          k*scaled_re*base_flow_utheta*base_flow_durdz*interpolated_ZC
          *testf_*Jbar*w;
         residuals[local_eqn] +=
          2*scaled_re*base_flow_utheta*interpolated_VS*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*r*base_flow_uz*interpolated_dUdZS*testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_st*r*mesh_velocity[1]*interpolated_dUdZS*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*r*interpolated_WS*base_flow_durdz*testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_st*r*dZSdt*base_flow_durdz*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*interpolated_RS*base_flow_uz*base_flow_durdz*testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_st*interpolated_RS*mesh_velocity[1]*base_flow_durdz
          *testf_*Jbar*w;
         residuals[local_eqn] += interpolated_RS*body_force[0]*testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_inv_fr*interpolated_RS*G[0]*testf_*Jbar*w;
         residuals[local_eqn] += r*base_flow_p*dtestfdRS*Jbar*w;
         residuals[local_eqn] += r*interpolated_PS*dtestfdr*Jbar*w;
         residuals[local_eqn] += interpolated_RS*base_flow_p*dtestfdr*Jbar*w;
         residuals[local_eqn] -=
          visc_ratio*(1.0+Gamma[0])*r*base_flow_durdr*dtestfdRS*Jbar*w;
         residuals[local_eqn] -=
          visc_ratio*(1.0+Gamma[0])*r*interpolated_dUdRS*dtestfdr*Jbar*w;
         residuals[local_eqn] +=
          visc_ratio*(1.0+Gamma[0])*r*base_flow_durdr*JhatS*dtestfdr*w;
         residuals[local_eqn] -=
          visc_ratio*(1.0+Gamma[0])*interpolated_RS*base_flow_durdr*dtestfdr
          *Jbar*w;
         residuals[local_eqn] -=
          k*visc_ratio*Gamma[0]*base_flow_duthetadr*dtestfdr*interpolated_RC
          *Jbar*w;
         residuals[local_eqn] -=
          k*visc_ratio*Gamma[0]*base_flow_duthetadr*dtestfdz*interpolated_ZC
          *Jbar*w;
         residuals[local_eqn] -=
          k*visc_ratio*Gamma[0]*interpolated_dVdRC*testf_*Jbar*w;
         residuals[local_eqn] -= visc_ratio*k*k*interpolated_US*testf_*Jbar*w/r;
         residuals[local_eqn] +=
          visc_ratio*k*k*base_flow_durdr*interpolated_RS*testf_*Jbar*w/r;
         residuals[local_eqn] +=
          visc_ratio*k*k*base_flow_durdz*interpolated_ZS*testf_*Jbar*w/r;
         residuals[local_eqn] +=
          visc_ratio*k*base_flow_utheta*dtestfdr*interpolated_RC*Jbar*w/r;
         residuals[local_eqn] +=
          visc_ratio*k*base_flow_utheta*dtestfdz*interpolated_ZC*Jbar*w/r;
         residuals[local_eqn] += visc_ratio*k*interpolated_VC*testf_*Jbar*w/r;
         residuals[local_eqn] -=
          visc_ratio*k*interpolated_RC*base_flow_utheta*testf_*Jbar*w/(r*r);
         residuals[local_eqn] -=
          visc_ratio*Gamma[0]*r*base_flow_duzdr*dtestfdZS*Jbar*w;
         residuals[local_eqn] -=
          visc_ratio*Gamma[0]*r*interpolated_dWdRS*dtestfdz*Jbar*w;
         residuals[local_eqn] +=
          visc_ratio*Gamma[0]*r*base_flow_duzdr*JhatS*dtestfdz*w;
         residuals[local_eqn] -=
          visc_ratio*Gamma[0]*interpolated_RS*base_flow_duzdr*dtestfdz*Jbar*w;
         residuals[local_eqn] -= visc_ratio*r*base_flow_durdz*dtestfdZS*Jbar*w;
         residuals[local_eqn] -=
          visc_ratio*r*interpolated_dUdZS*dtestfdz*Jbar*w;
         residuals[local_eqn] += visc_ratio*r*base_flow_durdz*JhatS*dtestfdz*w;
         residuals[local_eqn] -=
          visc_ratio*interpolated_RS*base_flow_durdz*dtestfdz*Jbar*w;
         residuals[local_eqn] += interpolated_PS*testf_*Jbar*w;
         residuals[local_eqn] +=
          visc_ratio*(1.0+Gamma[0])*k*interpolated_VC*testf_*Jbar*w/r;
         residuals[local_eqn] -=
          visc_ratio*(1.0+Gamma[0])*k*base_flow_duthetadr*interpolated_RC
          *testf_*Jbar*w/r;
         residuals[local_eqn] -=
          visc_ratio*(1.0+Gamma[0])*k*base_flow_duthetadz*interpolated_ZC
          *testf_*Jbar*w/r;
         residuals[local_eqn] -=
          visc_ratio*(1.0+Gamma[0])*interpolated_US*testf_*Jbar*w/r;
         residuals[local_eqn] +=
          visc_ratio*(1.0+Gamma[0])*base_flow_ur*interpolated_RS*testf_
          *Jbar*w/(r*r);
         residuals[local_eqn] -= scaled_re_st*r*base_flow_durdt*testf_*JhatS*w;
         residuals[local_eqn] +=
          scaled_re*base_flow_utheta*base_flow_utheta*testf_*JhatS*w;
         residuals[local_eqn] += r*body_force[0]*testf_*JhatS*w;
         residuals[local_eqn] += scaled_re_inv_fr*r*G[0]*testf_*JhatS*w;
         residuals[local_eqn] += k*visc_ratio*base_flow_utheta*testf_*JhatC*w/r;
         residuals[local_eqn] += base_flow_p*testf_*JhatS*w;
         residuals[local_eqn] -=
          visc_ratio*(1.0+Gamma[0])*base_flow_ur*testf_*JhatS*w/r;
         // Calculate the Jacobian
         // ----------------------
         if(flag)
          {
           // Loop over the velocity shape functions again
           for(unsigned l2=0;l2<n_node;l2++)
            {
             // Radial velocity component (cosine part) U_k^C
             local_unknown = nodal_local_eqn(l2,u_nodal_index[0]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) +=
                k*scaled_re*base_flow_utheta*psif[l2]*testf_*Jbar*w;
              }
             // Radial velocity component (sine part) U_k^S
             local_unknown = nodal_local_eqn(l2,u_nodal_index[1]);
             if(local_unknown >= 0)
              {
               if(flag==2)
                {
                 // Add the mass matrix
                 mass_matrix(local_eqn,local_unknown) +=
                  scaled_re_st*r*psif[l2]*testf_*Jbar*w;
                }
               // Add contributions to the Jacobian matrix
               jacobian(local_eqn,local_unknown) -=
                scaled_re_st*r*psif[l2]
                *node_pt(l2)->time_stepper_pt()->weight(1,0)*testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) -=
                scaled_re*r*base_flow_ur*group_B[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re_st*r*mesh_velocity[0]*group_B[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) -=
                scaled_re*r*psif[l2]*base_flow_durdr*testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) -=
                scaled_re*r*base_flow_uz*group_A[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re_st*r*mesh_velocity[1]*group_A[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*(1.0+Gamma[0])*r*group_B[l2]*dtestfdr*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*k*k*psif[l2]*testf_*Jbar*w/r;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*r*group_A[l2]*dtestfdz*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*(1.0+Gamma[0])*psif[l2]*testf_*Jbar*w/r;
              }
             // Axial velocity component (cosine part) W_k^C
             // has no contribution
             // Axial velocity component (sine part) W_k^S
             local_unknown = nodal_local_eqn(l2,u_nodal_index[3]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) -=
                scaled_re*r*psif[l2]*base_flow_durdz*testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*Gamma[0]*r*group_B[l2]*dtestfdz*w;
              }
             // Azimuthal velocity component (cosine part) V_k^C
             local_unknown = nodal_local_eqn(l2,u_nodal_index[4]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) -=
                k*visc_ratio*Gamma[0]*group_B[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*k*psif[l2]*testf_*Jbar*w/r;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*(1.0+Gamma[0])*k*psif[l2]*testf_*Jbar*w/r;
              }
             // Azimuthal velocity component (sine part) V_k^S
             local_unknown = nodal_local_eqn(l2,u_nodal_index[5]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) +=
                2.0*scaled_re*base_flow_utheta*psif[l2]*testf_*Jbar*w;
              }
             // Perturbation to radial nodal coord (cosine part) R_k^C
             local_unknown = nodal_local_eqn(l2,xhat_nodal_index[0]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) -=
                k*scaled_re*base_flow_utheta*base_flow_durdr*psif[l2]
                *testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) -=
                k*visc_ratio*Gamma[0]*base_flow_duthetadr*dtestfdr
                *psif[l2]*Jbar*w;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*k*base_flow_utheta*dtestfdr*psif[l2]*Jbar*w/r;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*k*psif[l2]*base_flow_utheta*testf_*Jbar*w/(r*r);
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*(1.0+Gamma[0])*k*base_flow_duthetadr*psif[l2]
                *testf_*Jbar*w/r;
               jacobian(local_eqn,local_unknown) +=
                k*visc_ratio*base_flow_utheta*testf_*group_B[l2]*w/r;
              }
             // Perturbation to radial nodal coord (sine part) R_k^S
             local_unknown = nodal_local_eqn(l2,xhat_nodal_index[1]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) -=
                scaled_re_st*psif[l2]*base_flow_durdt*testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re_st*r*psif[l2]
                *node_pt(l2)->position_time_stepper_pt()->weight(1,0)
                *base_flow_durdr*testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) -=
                scaled_re*psif[l2]*base_flow_ur*base_flow_durdr*testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re_st*psif[l2]*mesh_velocity[0]*base_flow_durdr
                *testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re*r*base_flow_uz*group_C[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) -=
                scaled_re_st*r*mesh_velocity[1]*group_C[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) -=
                scaled_re*psif[l2]*base_flow_uz*base_flow_durdz*testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re_st*psif[l2]*mesh_velocity[1]*base_flow_durdz
                *testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) +=
                psif[l2]*body_force[0]*testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re_inv_fr*psif[l2]*G[0]*testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) +=
                psif[l2]*base_flow_p*dtestfdr*Jbar*w;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*(1.0+Gamma[0])*r*base_flow_durdr*group_B[l2]
                *dtestfdr*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*(1.0+Gamma[0])*psif[l2]*base_flow_durdr
                *dtestfdr*Jbar*w;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*k*k*base_flow_durdr*psif[l2]*testf_*Jbar*w/r;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*Gamma[0]*r*base_flow_duzdr*group_F(l,l2)*w;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*Gamma[0]*r*base_flow_duzdr*group_B[l2]*dtestfdz*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*Gamma[0]*psif[l2]*base_flow_duzdr*dtestfdz*Jbar*w;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*r*base_flow_durdz*group_F(l,l2)*w;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*r*group_C[l2]*dtestfdz*w;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*r*base_flow_durdz*group_B[l2]*dtestfdz*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*psif[l2]*base_flow_durdz*dtestfdz*Jbar*w;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*(1.0+Gamma[0])*base_flow_ur*psif[l2]
                *testf_*Jbar*w/(r*r);
               jacobian(local_eqn,local_unknown) -=
                scaled_re_st*r*base_flow_durdt*testf_*group_B[l2]*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re*base_flow_utheta*base_flow_utheta
                *testf_*group_B[l2]*w;
               jacobian(local_eqn,local_unknown) +=
                r*body_force[0]*testf_*group_B[l2]*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re_inv_fr*r*G[0]*testf_*group_B[l2]*w;
               jacobian(local_eqn,local_unknown) +=
                base_flow_p*testf_*group_B[l2]*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*(1.0+Gamma[0])*base_flow_ur*testf_*group_B[l2]*w/r;
              }
             // Perturbation to axial nodal coord (cosine part) Z_k^C
             local_unknown = nodal_local_eqn(l2,xhat_nodal_index[2]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) -=
                k*scaled_re*base_flow_utheta*base_flow_durdz*psif[l2]
                *testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) -=
                k*visc_ratio*Gamma[0]*base_flow_duthetadr*dtestfdz
                *psif[l2]*Jbar*w;
               jacobian(local_eqn,local_unknown) -=
                k*visc_ratio*Gamma[0]*group_E[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*k*base_flow_utheta*dtestfdz*psif[l2]*Jbar*w/r;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*(1.0+Gamma[0])*k*base_flow_duthetadz*psif[l2]
                *testf_*Jbar*w/r;
               jacobian(local_eqn,local_unknown) +=
                k*visc_ratio*base_flow_utheta*testf_*group_A[l2]*w/r;
              }
             // Perturbation to axial nodal coord (sine part) Z_k^S
             local_unknown = nodal_local_eqn(l2,xhat_nodal_index[3]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) -=
                scaled_re*r*base_flow_ur*group_C[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re_st*r*mesh_velocity[0]*group_C[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re_st*r*psif[l2]
                *node_pt(l2)->position_time_stepper_pt()->weight(1,0)
                *base_flow_durdz*testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) +=
                r*base_flow_p*group_F(l,l2)*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*(1.0+Gamma[0])*r*base_flow_durdr*group_F(l,l2)*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*(1.0+Gamma[0])*r*group_C[l2]*dtestfdr*w;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*(1.0+Gamma[0])*r*base_flow_durdr*group_A[l2]
                *dtestfdr*w;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*k*k*base_flow_durdz*psif[l2]*testf_*Jbar*w/r;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*Gamma[0]*r*base_flow_duzdr*dtestfdz*group_A[l2]*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*Gamma[0]*r*group_D[l2]*dtestfdz*w;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*r*base_flow_durdz*group_A[l2]*dtestfdz*w;
               jacobian(local_eqn,local_unknown) -=
                scaled_re_st*r*base_flow_durdt*testf_*group_A[l2]*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re*base_flow_utheta*base_flow_utheta*testf_
                *group_A[l2]*w;
               jacobian(local_eqn,local_unknown) +=
                r*body_force[0]*testf_*group_A[l2]*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re_inv_fr*r*G[0]*testf_*group_A[l2]*w;
               jacobian(local_eqn,local_unknown) +=
                base_flow_p*testf_*group_A[l2]*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*(1.0+Gamma[0])*base_flow_ur*testf_*group_A[l2]*w/r;
              }
            } // End of loop over velocity shape functions
           // Now loop over pressure shape functions
           // (This is the contribution from pressure gradient)
           for(unsigned l2=0;l2<n_pres;l2++)
            {
             // Cosine part P_k^C has no contribution
             // Sine part P_k^S
             local_unknown = p_local_eqn(l2,1);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) += r*psip[l2]*dtestfdr*Jbar*w;
               jacobian(local_eqn,local_unknown) += psip[l2]*testf_*Jbar*w;
              }
            } // End of loop over pressure shape functions
           // Now loop over the spines in the element
           for(unsigned l2=0;l2<n_p;l2++)
            {
             // Perturbed spine "height" (cosine part) H_k^C
             local_unknown =
              get_local_eqn_number_corresponding_to_geometric_dofs(l2,0);
             if(local_unknown >= 0)
              {
               for(unsigned a=0;a<3;a++)
                {
                 double sum = 0.0;
                 sum -=
                  k*scaled_re*base_flow_utheta*base_flow_durdz
                  *psif[l2+(3*a)]*testf_*Jbar*w;
                 sum -=
                  k*visc_ratio*Gamma[0]*base_flow_duthetadr*dtestfdz
                  *psif[l2+(3*a)]*Jbar*w;
                 sum -= k*visc_ratio*Gamma[0]*group_E[l2+(3*a)]*testf_*w;
                 sum +=
                  visc_ratio*k*base_flow_utheta*dtestfdz*psif[l2+(3*a)]
                  *Jbar*w/r;
                 sum -=
                  visc_ratio*(1.0+Gamma[0])*k*base_flow_duthetadz
                  *psif[l2+(3*a)]*testf_*Jbar*w/r;
                 sum +=
                  k*visc_ratio*base_flow_utheta*testf_*group_A[l2+(3*a)]*w/r;
                 jacobian(local_eqn,local_unknown) +=
                  sum*effective_perturbed_spine_node_fraction[l2+(3*a)];
                }
              }
             // Perturbed spine "height" (sine part) H_k^S
             local_unknown =
              get_local_eqn_number_corresponding_to_geometric_dofs(l2,1);
             if(local_unknown >= 0)
              {
               for(unsigned a=0;a<3;a++)
                {
                 double sum = 0.0;
                 sum -= scaled_re*r*base_flow_ur*group_C[l2+(3*a)]*testf_*w;
                 sum +=
                  scaled_re_st*r*mesh_velocity[0]*group_C[l2+(3*a)]*testf_*w;
                 sum +=
                  scaled_re_st*r*psif[l2+(3*a)]
                  *node_pt(l2+(3*a))->position_time_stepper_pt()->weight(1,0)
                  *base_flow_durdz*testf_*Jbar*w;
                 sum += r*base_flow_p*group_F(l,(l2+(3*a)))*w;
                 sum -=
                  visc_ratio*(1.0+Gamma[0])*r*base_flow_durdr
                  *group_F(l,(l2+(3*a)))*w;
                 sum -=
                  visc_ratio*(1.0+Gamma[0])*r*group_C[l2+(3*a)]*dtestfdr*w;
                 sum +=
                  visc_ratio*(1.0+Gamma[0])*r*base_flow_durdr
                  *group_A[l2+(3*a)]*dtestfdr*w;
                 sum +=
                  visc_ratio*k*k*base_flow_durdz*psif[l2+(3*a)]*testf_*Jbar*w/r;
                 sum -= visc_ratio*Gamma[0]*r*group_D[l2+(3*a)]*dtestfdz*w;
                 sum +=
                  visc_ratio*Gamma[0]*r*base_flow_duzdr*group_A[l2+(3*a)]
                  *dtestfdz*w;
                 sum +=
                  visc_ratio*r*base_flow_durdz*group_A[l2+(3*a)]*dtestfdz*w;
                 sum -=
                  scaled_re_st*r*base_flow_durdt*testf_*group_A[l2+(3*a)]*w;
                 sum +=
                  scaled_re*base_flow_utheta*base_flow_utheta*testf_
                  *group_A[l2+(3*a)]*w;
                 sum += r*body_force[0]*testf_*group_A[l2+(3*a)]*w;
                 sum += scaled_re_inv_fr*r*G[0]*testf_*group_A[l2+(3*a)]*w;
                 sum += base_flow_p*testf_*group_A[l2+(3*a)]*w;
                 sum -=
                  visc_ratio*(1.0+Gamma[0])*base_flow_ur*testf_
                  *group_A[l2+(3*a)]*w/r;
                 jacobian(local_eqn,local_unknown) +=
                  sum*effective_perturbed_spine_node_fraction[l2+(3*a)];
                }
              }
            } // End of loop over spines in the element
          } // End of Jacobian calculation
        } // End of if not boundary condition statement
       // --------------------------------------------
       // THIRD (AXIAL) MOMENTUM EQUATION: COSINE PART
       // --------------------------------------------
       // Get local equation number of third velocity value at this node
       local_eqn = nodal_local_eqn(l,u_nodal_index[2]);
       // If it's not a boundary condition
       if(local_eqn >= 0)
        {
         residuals[local_eqn] -= scaled_re_st*r*dWCdt*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re_st*interpolated_RC*base_flow_duzdt*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*r*base_flow_ur*interpolated_dWdRC*testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_st*r*mesh_velocity[0]*interpolated_dWdRC*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*r*interpolated_UC*base_flow_duzdr*testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_st*r*dRCdt*base_flow_duzdr*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*interpolated_RC*base_flow_ur*base_flow_duzdr*testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_st*interpolated_RC*mesh_velocity[0]*base_flow_duzdr
          *testf_*Jbar*w;
         residuals[local_eqn] -=
          k*scaled_re*base_flow_utheta*interpolated_WS*testf_*Jbar*w;
         residuals[local_eqn] +=
          k*scaled_re*base_flow_utheta*base_flow_duzdr*interpolated_RS
          *testf_*Jbar*w;
         residuals[local_eqn] +=
          k*scaled_re*base_flow_utheta*base_flow_duzdz*interpolated_ZS
          *testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*r*base_flow_uz*interpolated_dWdZC*testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_st*r*mesh_velocity[1]*interpolated_dWdZC*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*r*interpolated_WC*base_flow_duzdz*testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_st*r*dZCdt*base_flow_duzdz*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*interpolated_RC*base_flow_uz*base_flow_duzdz*testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_st*interpolated_RC*mesh_velocity[1]*base_flow_duzdz
          *testf_*Jbar*w;
         residuals[local_eqn] += interpolated_RC*body_force[1]*testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_inv_fr*interpolated_RC*G[1]*testf_*Jbar*w;
         residuals[local_eqn] -= visc_ratio*r*base_flow_duzdr*dtestfdRC*Jbar*w;
         residuals[local_eqn] -=
          visc_ratio*r*interpolated_dWdRC*dtestfdr*Jbar*w;
         residuals[local_eqn] += visc_ratio*r*base_flow_duzdr*JhatC*dtestfdr*w;
         residuals[local_eqn] -=
          visc_ratio*interpolated_RC*base_flow_duzdr*dtestfdr*Jbar*w;
         residuals[local_eqn] -=
          visc_ratio*Gamma[1]*r*base_flow_durdz*dtestfdRC*Jbar*w;
         residuals[local_eqn] -=
          visc_ratio*Gamma[1]*r*interpolated_dUdZC*dtestfdr*Jbar*w;
         residuals[local_eqn] +=
          visc_ratio*Gamma[1]*r*base_flow_durdz*JhatC*dtestfdr*w;
         residuals[local_eqn] -=
          visc_ratio*Gamma[1]*interpolated_RC*base_flow_durdz*dtestfdr*Jbar*w;
         residuals[local_eqn] -= visc_ratio*k*k*interpolated_WC*testf_*Jbar*w/r;
         residuals[local_eqn] +=
          visc_ratio*k*k*base_flow_duzdr*interpolated_RC*testf_*Jbar*w/r;
         residuals[local_eqn] +=
          visc_ratio*k*k*base_flow_duzdz*interpolated_ZC*testf_*Jbar*w/r;
         residuals[local_eqn] +=
          k*visc_ratio*Gamma[1]*base_flow_duthetadz*dtestfdr*interpolated_RS
          *Jbar*w;
         residuals[local_eqn] +=
          k*visc_ratio*Gamma[1]*base_flow_duthetadz*dtestfdz*interpolated_ZS
          *Jbar*w;
         residuals[local_eqn] +=
          k*visc_ratio*Gamma[1]*interpolated_dVdZS*testf_*Jbar*w;
         residuals[local_eqn] += r*base_flow_p*dtestfdZC*Jbar*w;
         residuals[local_eqn] += r*interpolated_PC*dtestfdz*Jbar*w;
         residuals[local_eqn] += interpolated_RC*base_flow_p*dtestfdz*Jbar*w;
         residuals[local_eqn] -=
          visc_ratio*(1.0+Gamma[1])*r*base_flow_duzdz*dtestfdZC*Jbar*w;
         residuals[local_eqn] -=
          visc_ratio*(1.0+Gamma[1])*r*interpolated_dWdZC*dtestfdz*Jbar*w;
         residuals[local_eqn] +=
          visc_ratio*(1.0+Gamma[1])*r*base_flow_duzdz*JhatC*dtestfdz*w;
         residuals[local_eqn] -=
          visc_ratio*(1.0+Gamma[1])*interpolated_RC*base_flow_duzdz
          *dtestfdz*Jbar*w;
         residuals[local_eqn] -= scaled_re_st*r*base_flow_duzdt*testf_*JhatC*w;
         residuals[local_eqn] += r*body_force[1]*testf_*JhatC*w;
         residuals[local_eqn] += scaled_re_inv_fr*r*G[1]*testf_*JhatC*w;
         // Calculate the Jacobian
         // ----------------------
         if(flag)
          {
           // Loop over the velocity shape functions again
           for(unsigned l2=0;l2<n_node;l2++)
            {
             // Radial velocity component (cosine part) U_k^C
             local_unknown = nodal_local_eqn(l2,u_nodal_index[0]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) -=
                scaled_re*r*psif[l2]*base_flow_duzdr*testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*Gamma[1]*r*group_A[l2]*dtestfdr*w;
              }
             // Radial velocity component (sine part) U_k^S
             // has no contribution
             // Axial velocity component (cosine part) W_k^C
             local_unknown = nodal_local_eqn(l2,u_nodal_index[2]);
             if(local_unknown >= 0)
              {
               if(flag==2)
                {
                 // Add the mass matrix
                 mass_matrix(local_eqn,local_unknown) +=
                  scaled_re_st*r*psif[l2]*testf_*Jbar*w;
                }
               // Add contributions to the Jacobian matrix
               jacobian(local_eqn,local_unknown) -=
                scaled_re_st*r*psif[l2]
                *node_pt(l2)->time_stepper_pt()->weight(1,0)*testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) -=
                scaled_re*r*base_flow_ur*group_B[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re_st*r*mesh_velocity[0]*group_B[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) -=
                scaled_re*r*base_flow_uz*group_A[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re_st*r*mesh_velocity[1]*group_A[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) -=
                scaled_re*r*psif[l2]*base_flow_duzdz*testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*r*group_B[l2]*dtestfdr*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*k*k*psif[l2]*testf_*Jbar*w/r;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*(1.0+Gamma[1])*r*group_A[l2]*dtestfdz*w;
              }
             // Axial velocity component (sine part) W_k^S
             local_unknown = nodal_local_eqn(l2,u_nodal_index[3]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) -=
                k*scaled_re*base_flow_utheta*psif[l2]*testf_*Jbar*w;
              }
             // Azimuthal velocity component (cosine part) V_k^C
             // has no contribution
             // Azimuthal velocity component (sine part) V_k^S
             local_unknown = nodal_local_eqn(l2,u_nodal_index[5]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) +=
                k*visc_ratio*Gamma[1]*group_A[l2]*testf_*w;
              }
             // Perturbation to radial nodal coord (cosine part) R_k^C
             local_unknown = nodal_local_eqn(l2,xhat_nodal_index[0]);
             if(local_unknown >= 0)
             {
              jacobian(local_eqn,local_unknown) -=
               scaled_re_st*psif[l2]*base_flow_duzdt*testf_*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               scaled_re_st*r*psif[l2]
               *node_pt(l2)->position_time_stepper_pt()->weight(1,0)
               *base_flow_duzdr*testf_*Jbar*w;
              jacobian(local_eqn,local_unknown) -=
               scaled_re*psif[l2]*base_flow_ur*base_flow_duzdr*testf_*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               scaled_re_st*psif[l2]*mesh_velocity[0]*base_flow_duzdr
               *testf_*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               scaled_re*r*base_flow_uz*group_D[l2]*testf_*w;
              jacobian(local_eqn,local_unknown) -=
               scaled_re_st*r*mesh_velocity[1]*group_D[l2]*testf_*w;
              jacobian(local_eqn,local_unknown) -=
               scaled_re*psif[l2]*base_flow_uz*base_flow_duzdz*testf_*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               scaled_re_st*psif[l2]*mesh_velocity[1]*base_flow_duzdz
               *testf_*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               psif[l2]*body_force[1]*testf_*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               scaled_re_inv_fr*psif[l2]*G[1]*testf_*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*r*base_flow_duzdr*group_B[l2]*dtestfdr*w;
              jacobian(local_eqn,local_unknown) -=
               visc_ratio*psif[l2]*base_flow_duzdr*dtestfdr*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*Gamma[1]*r*group_C[l2]*dtestfdr*w;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*Gamma[1]*r*base_flow_durdz*group_B[l2]*dtestfdr*w;
              jacobian(local_eqn,local_unknown) -=
               visc_ratio*Gamma[1]*psif[l2]*base_flow_durdz*dtestfdr*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*k*k*base_flow_duzdr*psif[l2]*testf_*Jbar*w/r;
              jacobian(local_eqn,local_unknown) -=
               r*base_flow_p*group_F(l,l2)*w;
              jacobian(local_eqn,local_unknown) +=
               psif[l2]*base_flow_p*dtestfdz*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*(1.0+Gamma[1])*r*base_flow_duzdz*group_F(l,l2)*w;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*(1.0+Gamma[1])*r*group_D[l2]*dtestfdz*w;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*(1.0+Gamma[1])*r*base_flow_duzdz*group_B[l2]
               *dtestfdz*w;
              jacobian(local_eqn,local_unknown) -=
               visc_ratio*(1.0+Gamma[1])*psif[l2]*base_flow_duzdz*dtestfdz
               *Jbar*w;
              jacobian(local_eqn,local_unknown) -=
               scaled_re_st*r*base_flow_duzdt*testf_*group_B[l2]*w;
              jacobian(local_eqn,local_unknown) +=
               r*body_force[1]*testf_*group_B[l2]*w;
              jacobian(local_eqn,local_unknown) +=
               scaled_re_inv_fr*r*G[1]*testf_*group_B[l2]*w;
             }
             // Perturbation to radial nodal coord (sine part) R_k^S
             local_unknown = nodal_local_eqn(l2,xhat_nodal_index[1]);
             if(local_unknown >= 0)
             {
              jacobian(local_eqn,local_unknown) +=
               k*scaled_re*base_flow_utheta*base_flow_duzdr*psif[l2]*testf_
               *Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               k*visc_ratio*Gamma[1]*base_flow_duthetadz*dtestfdr*psif[l2]
               *Jbar*w;
              jacobian(local_eqn,local_unknown) -=
               k*visc_ratio*Gamma[1]*group_E[l2]*testf_*w;
             }
             // Perturbation to axial nodal coord (cosine part) Z_k^C
             local_unknown = nodal_local_eqn(l2,xhat_nodal_index[2]);
             if(local_unknown >= 0)
             {
              jacobian(local_eqn,local_unknown) -=
               scaled_re*r*base_flow_ur*group_D[l2]*testf_*w;
              jacobian(local_eqn,local_unknown) +=
               scaled_re_st*r*mesh_velocity[0]*group_D[l2]*testf_*w;
              jacobian(local_eqn,local_unknown) +=
               scaled_re_st*r*psif[l2]
               *node_pt(l2)->position_time_stepper_pt()->weight(1,0)
               *base_flow_duzdz*testf_*Jbar*w;
              jacobian(local_eqn,local_unknown) -=
               visc_ratio*r*base_flow_duzdr*group_F(l,l2)*w;
              jacobian(local_eqn,local_unknown) -=
               visc_ratio*r*group_D[l2]*dtestfdr*w;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*r*base_flow_duzdr*group_A[l2]*dtestfdr*w;
              jacobian(local_eqn,local_unknown) -=
               visc_ratio*Gamma[1]*r*base_flow_durdz*group_F(l,l2)*w;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*Gamma[1]*r*base_flow_durdz*group_A[l2]*dtestfdr*w;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*k*k*base_flow_duzdz*psif[l2]*testf_*Jbar*w/r;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*(1.0+Gamma[1])*r*base_flow_duzdz*group_A[l2]
               *dtestfdz*w;
              jacobian(local_eqn,local_unknown) -=
               scaled_re_st*r*base_flow_duzdt*testf_*group_A[l2]*w;
              jacobian(local_eqn,local_unknown) +=
               r*body_force[1]*testf_*group_A[l2]*w;
              jacobian(local_eqn,local_unknown) +=
               scaled_re_inv_fr*r*G[1]*testf_*group_A[l2]*w;
             }
             // Perturbation to axial nodal coord (sine part) Z_k^S
             local_unknown = nodal_local_eqn(l2,xhat_nodal_index[3]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) +=
                k*scaled_re*base_flow_utheta*base_flow_duzdz*psif[l2]
                *testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) +=
                k*visc_ratio*Gamma[1]*base_flow_duthetadz*dtestfdz
                *psif[l2]*Jbar*w;
              }
            } // End of loop over velocity shape functions
           // Now loop over pressure shape functions
           // (This is the contribution from pressure gradient)
           for(unsigned l2=0;l2<n_pres;l2++)
            {
             // Cosine part P_k^C
             local_unknown = p_local_eqn(l2,0);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) += r*psip[l2]*dtestfdz*Jbar*w;
              }
             // Sine part P_k^S has no contribution
            } // End of loop over pressure shape functions
           // Now loop over the spines in the element
           for(unsigned l2=0;l2<n_p;l2++)
            {
             // Perturbed spine "height" (cosine part) H_k^C
             local_unknown =
              get_local_eqn_number_corresponding_to_geometric_dofs(l2,0);
             if(local_unknown >= 0)
              {
               for(unsigned a=0;a<3;a++)
                {
                 double sum = 0.0;
                 sum -= scaled_re*r*base_flow_ur*group_D[l2+(3*a)]*testf_*w;
                 sum +=
                  scaled_re_st*r*mesh_velocity[0]*group_D[l2+(3*a)]*testf_*w;
                 sum +=
                  scaled_re_st*r*psif[l2+(3*a)]
                  *node_pt(l2+(3*a))->position_time_stepper_pt()->weight(1,0)
                  *base_flow_duzdz*testf_*Jbar*w;
                 sum -= visc_ratio*r*base_flow_duzdr*group_F(l,(l2+(3*a)))*w;
                 sum -= visc_ratio*r*group_D[l2+(3*a)]*dtestfdr*w;
                 sum +=
                  visc_ratio*r*base_flow_duzdr*group_A[l2+(3*a)]*dtestfdr*w;
                 sum -=
                  visc_ratio*Gamma[1]*r*base_flow_durdz*group_F(l,(l2+(3*a)))*w;
                 sum +=
                  visc_ratio*Gamma[1]*r*base_flow_durdz*group_A[l2+(3*a)]
                  *dtestfdr*w;
                 sum +=
                  visc_ratio*k*k*base_flow_duzdz*psif[l2+(3*a)]*testf_*Jbar*w/r;
                 sum +=
                  visc_ratio*(1.0+Gamma[1])*r*base_flow_duzdz
                  *group_A[l2+(3*a)]*dtestfdz*w;
                 sum -=
                  scaled_re_st*r*base_flow_duzdt*testf_*group_A[l2+(3*a)]*w;
                 sum += r*body_force[1]*testf_*group_A[l2+(3*a)]*w;
                 sum += scaled_re_inv_fr*r*G[1]*testf_*group_A[l2+(3*a)]*w;
                 jacobian(local_eqn,local_unknown) +=
                  sum*effective_perturbed_spine_node_fraction[l2+(3*a)];
                }
              }
             // Perturbed spine "height" (sine part) H_k^S
             local_unknown =
              get_local_eqn_number_corresponding_to_geometric_dofs(l2,1);
             if(local_unknown >= 0)
              {
               for(unsigned a=0;a<3;a++)
                {
                 double sum = 0.0;
                 sum += k*scaled_re*base_flow_utheta*base_flow_duzdz
                  *psif[l2+(3*a)]*testf_*Jbar*w;
                 sum += k*visc_ratio*Gamma[1]*base_flow_duthetadz*dtestfdz
                  *psif[l2+(3*a)]*Jbar*w;
                 jacobian(local_eqn,local_unknown) +=
                  sum*effective_perturbed_spine_node_fraction[l2+(3*a)];
                }
              }
            } // End of loop over spines in the element
          } // End of Jacobian calculation
        } // End of if not boundary condition statement
       // -------------------------------------------
       // FOURTH (AXIAL) MOMENTUM EQUATION: SINE PART
       // -------------------------------------------
       // Get local equation number of fourth velocity value at this node
       local_eqn = nodal_local_eqn(l,u_nodal_index[3]);
       // If it's not a boundary condition
       if(local_eqn >= 0)
        {
         residuals[local_eqn] -= scaled_re_st*r*dWSdt*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re_st*interpolated_RS*base_flow_duzdt*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*r*base_flow_ur*interpolated_dWdRS*testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_st*r*mesh_velocity[0]*interpolated_dWdRS*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*r*interpolated_US*base_flow_duzdr*testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_st*r*dRSdt*base_flow_duzdr*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*interpolated_RS*base_flow_ur*base_flow_duzdr*testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_st*interpolated_RS*mesh_velocity[0]*base_flow_duzdr
          *testf_*Jbar*w;
         residuals[local_eqn] +=
          k*scaled_re*base_flow_utheta*interpolated_WC*testf_*Jbar*w;
         residuals[local_eqn] -=
          k*scaled_re*base_flow_utheta*base_flow_duzdr*interpolated_RC
          *testf_*Jbar*w;
         residuals[local_eqn] -=
          k*scaled_re*base_flow_utheta*base_flow_duzdz*interpolated_ZC
          *testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*r*base_flow_uz*interpolated_dWdZS*testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_st*r*mesh_velocity[1]*interpolated_dWdZS*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*r*interpolated_WS*base_flow_duzdz*testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_st*r*dZSdt*base_flow_duzdz*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*interpolated_RS*base_flow_uz*base_flow_duzdz*testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_st*interpolated_RS*mesh_velocity[1]*base_flow_duzdz
          *testf_*Jbar*w;
         residuals[local_eqn] += interpolated_RS*body_force[1]*testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_inv_fr*interpolated_RS*G[1]*testf_*Jbar*w;
         residuals[local_eqn] -= visc_ratio*r*base_flow_duzdr*dtestfdRS*Jbar*w;
         residuals[local_eqn] -=
          visc_ratio*r*interpolated_dWdRS*dtestfdr*Jbar*w;
         residuals[local_eqn] += visc_ratio*r*base_flow_duzdr*JhatS*dtestfdr*w;
         residuals[local_eqn] -=
          visc_ratio*interpolated_RS*base_flow_duzdr*dtestfdr*Jbar*w;
         residuals[local_eqn] -=
          visc_ratio*Gamma[1]*r*base_flow_durdz*dtestfdRS*Jbar*w;
         residuals[local_eqn] -=
          visc_ratio*Gamma[1]*r*interpolated_dUdZS*dtestfdr*Jbar*w;
         residuals[local_eqn] +=
          visc_ratio*Gamma[1]*r*base_flow_durdz*JhatS*dtestfdr*w;
         residuals[local_eqn] -=
          visc_ratio*Gamma[1]*interpolated_RS*base_flow_durdz*dtestfdr*Jbar*w;
         residuals[local_eqn] -= visc_ratio*k*k*interpolated_WS*testf_*Jbar*w/r;
         residuals[local_eqn] +=
          visc_ratio*k*k*base_flow_duzdr*interpolated_RS*testf_*Jbar*w/r;
         residuals[local_eqn] +=
          visc_ratio*k*k*base_flow_duzdz*interpolated_ZS*testf_*Jbar*w/r;
         residuals[local_eqn] -=
          k*visc_ratio*Gamma[1]*base_flow_duthetadz*dtestfdr*interpolated_RC
          *Jbar*w;
         residuals[local_eqn] -=
          k*visc_ratio*Gamma[1]*base_flow_duthetadz*dtestfdz*interpolated_ZC
          *Jbar*w;
         residuals[local_eqn] -=
          k*visc_ratio*Gamma[1]*interpolated_dVdZC*testf_*Jbar*w;
         residuals[local_eqn] += r*base_flow_p*dtestfdZS*Jbar*w;
         residuals[local_eqn] += r*interpolated_PS*dtestfdz*Jbar*w;
         residuals[local_eqn] += interpolated_RS*base_flow_p*dtestfdz*Jbar*w;
         residuals[local_eqn] -=
          visc_ratio*(1.0+Gamma[1])*r*base_flow_duzdz*dtestfdZS*Jbar*w;
         residuals[local_eqn] -=
          visc_ratio*(1.0+Gamma[1])*r*interpolated_dWdZS*dtestfdz*Jbar*w;
         residuals[local_eqn] +=
          visc_ratio*(1.0+Gamma[1])*r*base_flow_duzdz*JhatS*dtestfdz*w;
         residuals[local_eqn] -=
          visc_ratio*(1.0+Gamma[1])*interpolated_RS*base_flow_duzdz*dtestfdz
          *Jbar*w;
         residuals[local_eqn] -= scaled_re_st*r*base_flow_duzdt*testf_*JhatS*w;
         residuals[local_eqn] += r*body_force[1]*testf_*JhatS*w;
         residuals[local_eqn] += scaled_re_inv_fr*r*G[1]*testf_*JhatS*w;
         // Calculate the Jacobian
         // ----------------------
         if(flag)
          {
           // Loop over the velocity shape functions again
           for(unsigned l2=0;l2<n_node;l2++)
            {
             // Radial velocity component (cosine part) U_k^C
             // has no contribution
             // Radial velocity component (sine part) U_k^S
             local_unknown = nodal_local_eqn(l2,u_nodal_index[1]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) -=
                scaled_re*r*psif[l2]*base_flow_duzdr*testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*Gamma[1]*r*group_A[l2]*dtestfdr*w;
              }
             // Axial velocity component (cosine part) W_k^S
             local_unknown = nodal_local_eqn(l2,u_nodal_index[2]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) +=
                k*scaled_re*base_flow_utheta*psif[l2]*testf_*Jbar*w;
              }
             // Axial velocity component (sine part) W_k^S
             local_unknown = nodal_local_eqn(l2,u_nodal_index[3]);
             if(local_unknown >= 0)
              {
               if(flag==2)
                {
                 // Add the mass matrix
                 mass_matrix(local_eqn,local_unknown) +=
                  scaled_re_st*r*psif[l2]*testf_*Jbar*w;
                }
               // Add contributions to the Jacobian matrix
               jacobian(local_eqn,local_unknown) -=
                scaled_re_st*r*psif[l2]
                *node_pt(l2)->time_stepper_pt()->weight(1,0)*testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) -=
                scaled_re*r*base_flow_ur*group_B[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re_st*r*mesh_velocity[0]*group_B[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) -=
                scaled_re*r*base_flow_uz*group_A[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re_st*r*mesh_velocity[1]*group_A[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) -=
                scaled_re*r*psif[l2]*base_flow_duzdz*testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*r*group_B[l2]*dtestfdr*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*k*k*psif[l2]*testf_*Jbar*w/r;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*(1.0+Gamma[1])*r*group_A[l2]*dtestfdz*w;
              }
             // Azimuthal velocity component (cosine part) V_k^C
             local_unknown = nodal_local_eqn(l2,u_nodal_index[4]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) -=
                k*visc_ratio*Gamma[1]*group_A[l2]*testf_*w;
              }
             // Azimuthal velocity component (sine part) V_k^S
             // has no contribution
             // Perturbation to radial nodal coord (cosine part) R_k^C
             local_unknown = nodal_local_eqn(l2,xhat_nodal_index[0]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) -=
                k*scaled_re*base_flow_utheta*base_flow_duzdr*psif[l2]
                *testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) -=
                k*visc_ratio*Gamma[1]*base_flow_duthetadz*dtestfdr
                *psif[l2]*Jbar*w;
               jacobian(local_eqn,local_unknown) +=
                k*visc_ratio*Gamma[1]*group_E[l2]*testf_*w;
              }
             // Perturbation to radial nodal coord (sine part) R_k^S
             local_unknown = nodal_local_eqn(l2,xhat_nodal_index[1]);
             if(local_unknown >= 0)
             {
              jacobian(local_eqn,local_unknown) -=
               scaled_re_st*psif[l2]*base_flow_duzdt*testf_*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               scaled_re_st*r*psif[l2]
               *node_pt(l2)->position_time_stepper_pt()->weight(1,0)
               *base_flow_duzdr*testf_*Jbar*w;
              jacobian(local_eqn,local_unknown) -=
               scaled_re*psif[l2]*base_flow_ur*base_flow_duzdr*testf_*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               scaled_re_st*psif[l2]*mesh_velocity[0]*base_flow_duzdr
               *testf_*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               scaled_re*r*base_flow_uz*group_D[l2]*testf_*w;
              jacobian(local_eqn,local_unknown) -=
               scaled_re_st*r*mesh_velocity[1]*group_D[l2]*testf_*w;
              jacobian(local_eqn,local_unknown) -=
               scaled_re*psif[l2]*base_flow_uz*base_flow_duzdz*testf_*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               scaled_re_st*psif[l2]*mesh_velocity[1]*base_flow_duzdz
               *testf_*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               psif[l2]*body_force[1]*testf_*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               scaled_re_inv_fr*psif[l2]*G[1]*testf_*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*r*base_flow_duzdr*group_B[l2]*dtestfdr*w;
              jacobian(local_eqn,local_unknown) -=
               visc_ratio*psif[l2]*base_flow_duzdr*dtestfdr*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*Gamma[1]*r*group_C[l2]*dtestfdr*w;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*Gamma[1]*r*base_flow_durdz*group_B[l2]*dtestfdr*w;
              jacobian(local_eqn,local_unknown) -=
               visc_ratio*Gamma[1]*psif[l2]*base_flow_durdz*dtestfdr*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*k*k*base_flow_duzdr*psif[l2]*testf_*Jbar*w/r;
              jacobian(local_eqn,local_unknown) -=
               r*base_flow_p*group_F(l,l2)*w;
              jacobian(local_eqn,local_unknown) +=
               psif[l2]*base_flow_p*dtestfdz*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*(1.0+Gamma[1])*r*base_flow_duzdz*group_F(l,l2)*w;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*(1.0+Gamma[1])*r*group_D[l2]*dtestfdz*w;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*(1.0+Gamma[1])*r*base_flow_duzdz*group_B[l2]
               *dtestfdz*w;
              jacobian(local_eqn,local_unknown) -=
               visc_ratio*(1.0+Gamma[1])*psif[l2]*base_flow_duzdz
               *dtestfdz*Jbar*w;
              jacobian(local_eqn,local_unknown) -=
               scaled_re_st*r*base_flow_duzdt*testf_*group_B[l2]*w;
              jacobian(local_eqn,local_unknown) +=
               r*body_force[1]*testf_*group_B[l2]*w;
              jacobian(local_eqn,local_unknown) +=
               scaled_re_inv_fr*r*G[1]*testf_*group_B[l2]*w;
             }
             // Perturbation to axial nodal coord (cosine part) Z_k^C
             local_unknown = nodal_local_eqn(l2,xhat_nodal_index[2]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) -=
                k*scaled_re*base_flow_utheta*base_flow_duzdz*psif[l2]
                *testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) -=
                k*visc_ratio*Gamma[1]*base_flow_duthetadz*dtestfdz
                *psif[l2]*Jbar*w;
              }
             // Perturbation to axial nodal coord (sine part) Z_k^S
             local_unknown = nodal_local_eqn(l2,xhat_nodal_index[3]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) -=
                scaled_re*r*base_flow_ur*group_D[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re_st*r*mesh_velocity[0]*group_D[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re_st*r*psif[l2]
                *node_pt(l2)->position_time_stepper_pt()->weight(1,0)
                *base_flow_duzdz*testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*r*base_flow_duzdr*group_F(l,l2)*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*r*group_D[l2]*dtestfdr*w;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*r*base_flow_duzdr*group_A[l2]*dtestfdr*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*Gamma[1]*r*base_flow_durdz*group_F(l,l2)*w;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*Gamma[1]*r*base_flow_durdz*group_A[l2]*dtestfdr*w;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*k*k*base_flow_duzdz*psif[l2]*testf_*Jbar*w/r;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*(1.0+Gamma[1])*r*base_flow_duzdz*group_A[l2]
                *dtestfdz*w;
               jacobian(local_eqn,local_unknown) -=
                scaled_re_st*r*base_flow_duzdt*testf_*group_A[l2]*w;
               jacobian(local_eqn,local_unknown) +=
                r*body_force[1]*testf_*group_A[l2]*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re_inv_fr*r*G[1]*testf_*group_A[l2]*w;
              }
            } // End of loop over velocity shape functions
           // Now loop over pressure shape functions
           // (This is the contribution from pressure gradient)
           for(unsigned l2=0;l2<n_pres;l2++)
            {
             // Cosine part P_k^C has no contribution
             // Sine part P_k^S
             local_unknown = p_local_eqn(l2,1);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) += r*psip[l2]*dtestfdz*Jbar*w;
              }
            } // End of loop over pressure shape functions
           // Now loop over the spines in the element
           for(unsigned l2=0;l2<n_p;l2++)
            {
             // Perturbed spine "height" (cosine part) H_k^C
             local_unknown =
              get_local_eqn_number_corresponding_to_geometric_dofs(l2,0);
            if(local_unknown >= 0)
              {
               for(unsigned a=0;a<3;a++)
                {
                 double sum = 0.0;
                 sum -=
                  k*scaled_re*base_flow_utheta*base_flow_duzdz
                  *psif[l2+(3*a)]*testf_*Jbar*w;
                 sum -=
                  k*visc_ratio*Gamma[1]*base_flow_duthetadz*dtestfdz
                  *psif[l2+(3*a)]*Jbar*w;
                 jacobian(local_eqn,local_unknown) +=
                  sum*effective_perturbed_spine_node_fraction[l2+(3*a)];
                }
              }
             // Perturbed spine "height" (sine part) H_k^S
             local_unknown =
              get_local_eqn_number_corresponding_to_geometric_dofs(l2,1);
             if(local_unknown >= 0)
              {
               for(unsigned a=0;a<3;a++)
                {
                 double sum = 0.0;
                 sum -= scaled_re*r*base_flow_ur*group_D[l2+(3*a)]*testf_*w;
                 sum +=
                  scaled_re_st*r*mesh_velocity[0]*group_D[l2+(3*a)]*testf_*w;
                 sum +=
                  scaled_re_st*r*psif[l2+(3*a)]
                  *node_pt(l2+(3*a))->position_time_stepper_pt()->weight(1,0)
                  *base_flow_duzdz*testf_*Jbar*w;
                 sum -= visc_ratio*r*base_flow_duzdr*group_F(l,(l2+(3*a)))*w;
                 sum -= visc_ratio*r*group_D[l2+(3*a)]*dtestfdr*w;
                 sum +=
                  visc_ratio*r*base_flow_duzdr*group_A[l2+(3*a)]*dtestfdr*w;
                 sum -=
                  visc_ratio*Gamma[1]*r*base_flow_durdz*group_F(l,(l2+(3*a)))*w;
                 sum +=
                  visc_ratio*Gamma[1]*r*base_flow_durdz*group_A[l2+(3*a)]
                  *dtestfdr*w;
                 sum +=
                  visc_ratio*k*k*base_flow_duzdz*psif[l2+(3*a)]*testf_*Jbar*w/r;
                 sum +=
                  visc_ratio*(1.0+Gamma[1])*r*base_flow_duzdz
                  *group_A[l2+(3*a)]*dtestfdz*w;
                 sum -=
                  scaled_re_st*r*base_flow_duzdt*testf_*group_A[l2+(3*a)]*w;
                 sum += r*body_force[1]*testf_*group_A[l2+(3*a)]*w;
                 sum += scaled_re_inv_fr*r*G[1]*testf_*group_A[l2+(3*a)]*w;
                 jacobian(local_eqn,local_unknown) +=
                  sum*effective_perturbed_spine_node_fraction[l2+(3*a)];
                }
              }
            } // End of loop over spines in the element
          } // End of Jacobian calculation
        } // End of if not boundary condition statement
       // ------------------------------------------------
       // FIFTH (AZIMUTHAL) MOMENTUM EQUATION: COSINE PART
       // ------------------------------------------------
       //if(offensive_eqn>=0) cout<<"residuals[offensive_eqn] = "<<residuals[offensive_eqn]<<endl;
       // Get local equation number of fifth velocity value at this node
       local_eqn = nodal_local_eqn(l,u_nodal_index[4]);
       // If it's not a boundary condition
       if(local_eqn >= 0)
        {
         residuals[local_eqn] -= scaled_re_st*r*dVCdt*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re_st*interpolated_RC*base_flow_duthetadt*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*r*base_flow_ur*interpolated_dVdRC*testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_st*r*mesh_velocity[0]*interpolated_dVdRC*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*r*interpolated_UC*base_flow_duthetadr*testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_st*r*dRCdt*base_flow_duthetadr*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*interpolated_RC*base_flow_ur*base_flow_duthetadr
          *testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_st*interpolated_RC*mesh_velocity[0]*base_flow_duthetadr
          *testf_*Jbar*w;
         residuals[local_eqn] -=
          k*scaled_re*base_flow_utheta*interpolated_VS*testf_*Jbar*w;
         residuals[local_eqn] +=
          k*scaled_re*base_flow_utheta*base_flow_duthetadr*interpolated_RS
          *testf_*Jbar*w;
         residuals[local_eqn] +=
          k*scaled_re*base_flow_utheta*base_flow_duthetadz*interpolated_ZS
          *testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*base_flow_utheta*interpolated_UC*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*interpolated_VC*base_flow_ur*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*r*base_flow_uz*interpolated_dVdZC*testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_st*r*mesh_velocity[1]*interpolated_dVdZC*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*r*interpolated_WC*base_flow_duthetadz*testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_st*r*dZCdt*base_flow_duthetadz*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*interpolated_RC*base_flow_uz*base_flow_duthetadz
          *testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_st*interpolated_RC*mesh_velocity[1]*base_flow_duthetadz
          *testf_*Jbar*w;
         residuals[local_eqn] += interpolated_RC*body_force[2]*testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_inv_fr*interpolated_RC*G[2]*testf_*Jbar*w;
         residuals[local_eqn] -=
          visc_ratio*r*base_flow_duthetadr*dtestfdRC*Jbar*w;
         residuals[local_eqn] -=
          visc_ratio*r*interpolated_dVdRC*dtestfdr*Jbar*w;
         residuals[local_eqn] +=
          visc_ratio*r*base_flow_duthetadr*JhatC*dtestfdr*w;
         residuals[local_eqn] -=
          visc_ratio*interpolated_RC*base_flow_duthetadr*dtestfdr*Jbar*w;
         residuals[local_eqn] -=
          k*visc_ratio*Gamma[0]*interpolated_US*dtestfdr*Jbar*w;
         residuals[local_eqn] +=
          k*visc_ratio*Gamma[0]*base_flow_durdr*interpolated_RS*dtestfdr*Jbar*w;
         residuals[local_eqn] +=
          k*visc_ratio*Gamma[0]*base_flow_durdz*interpolated_ZS*dtestfdr*Jbar*w;
         residuals[local_eqn] +=
          visc_ratio*Gamma[0]*base_flow_utheta*dtestfdRC*Jbar*w;
         residuals[local_eqn] +=
          visc_ratio*Gamma[0]*interpolated_VC*dtestfdr*Jbar*w;
         residuals[local_eqn] -= k*base_flow_p*dtestfdr*interpolated_RS*Jbar*w;
         residuals[local_eqn] -= k*base_flow_p*dtestfdz*interpolated_ZS*Jbar*w;
         residuals[local_eqn] -= k*interpolated_PS*testf_*Jbar*w;
         residuals[local_eqn] -=
          visc_ratio*(1.0+Gamma[0])*k*k*interpolated_VC*testf_*Jbar*w/r;
         residuals[local_eqn] +=
          visc_ratio*(1.0+Gamma[0])*k*k*base_flow_duthetadr*interpolated_RC
          *testf_*Jbar*w/r;
         residuals[local_eqn] +=
          visc_ratio*(1.0+Gamma[0])*k*k*base_flow_duthetadz*interpolated_ZC
          *testf_*Jbar*w/r;
         residuals[local_eqn] +=
          visc_ratio*(1.0+Gamma[0])*k*base_flow_ur*dtestfdr*interpolated_RS
          *Jbar*w/r;
         residuals[local_eqn] +=
          visc_ratio*(1.0+Gamma[0])*k*base_flow_ur*dtestfdz*interpolated_ZS
          *Jbar*w/r;
         residuals[local_eqn] +=
          visc_ratio*(1.0+Gamma[0])*k*interpolated_US*testf_*Jbar*w/r;
         residuals[local_eqn] -=
          visc_ratio*(1.0+Gamma[0])*k*interpolated_RS*base_flow_ur*testf_
          *Jbar*w/(r*r);
         residuals[local_eqn] -=
          k*visc_ratio*Gamma[0]*interpolated_WS*dtestfdz*Jbar*w;
         residuals[local_eqn] +=
          k*visc_ratio*Gamma[0]*base_flow_duzdr*interpolated_RS*dtestfdz*Jbar*w;
         residuals[local_eqn] +=
          k*visc_ratio*Gamma[0]*base_flow_duzdz*interpolated_ZS*dtestfdz*Jbar*w;
         residuals[local_eqn] -=
          visc_ratio*r*base_flow_duthetadz*dtestfdZC*Jbar*w;
         residuals[local_eqn] -=
          visc_ratio*r*interpolated_dVdZC*dtestfdz*Jbar*w;
         residuals[local_eqn] +=
          visc_ratio*r*base_flow_duthetadz*JhatC*dtestfdz*w;
         residuals[local_eqn] -=
          visc_ratio*interpolated_RC*base_flow_duthetadz*dtestfdz*Jbar*w;
         residuals[local_eqn] +=
          visc_ratio*Gamma[0]*interpolated_dVdRC*testf_*Jbar*w;
         residuals[local_eqn] += visc_ratio*k*interpolated_US*testf_*Jbar*w/r;
         residuals[local_eqn] -=
          visc_ratio*k*base_flow_durdr*interpolated_RS*testf_*Jbar*w/r;
         residuals[local_eqn] -=
          visc_ratio*k*base_flow_durdz*interpolated_ZS*testf_*Jbar*w/r;
         residuals[local_eqn] -= visc_ratio*interpolated_VC*testf_*Jbar*w/r;
         residuals[local_eqn] +=
          visc_ratio*base_flow_utheta*interpolated_RC*testf_*Jbar*w/(r*r);
         residuals[local_eqn] -=
          scaled_re_st*r*base_flow_duthetadt*testf_*JhatC*w;
         residuals[local_eqn] -=
          scaled_re*base_flow_utheta*base_flow_ur*testf_*JhatC*w;
         residuals[local_eqn] += r*body_force[2]*testf_*JhatC*w;
         residuals[local_eqn] += scaled_re_inv_fr*r*G[2]*testf_*JhatC*w;
         residuals[local_eqn] -= k*base_flow_p*testf_*JhatS*w;
         residuals[local_eqn] +=
          k*visc_ratio*(1.0+Gamma[0])*base_flow_ur*testf_*JhatS*w/r;
         residuals[local_eqn] -= visc_ratio*base_flow_utheta*testf_*JhatC*w/r;
         // Calculate the Jacobian
         // ----------------------
         if(flag)
          {
           // Loop over the velocity shape functions again
           for(unsigned l2=0;l2<n_node;l2++)
            {
             // Radial velocity component (cosine part) U_k^C
             local_unknown = nodal_local_eqn(l2,u_nodal_index[0]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) -=
                scaled_re*r*psif[l2]*base_flow_duthetadr*testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) -=
                scaled_re*base_flow_utheta*psif[l2]*testf_*Jbar*w;
              }
             // Radial velocity component (sine part) U_k^S
             local_unknown = nodal_local_eqn(l2,u_nodal_index[1]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) -=
                k*visc_ratio*Gamma[0]*psif[l2]*dtestfdr*Jbar*w;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*(1.0+Gamma[0])*k*psif[l2]*testf_*Jbar*w/r;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*k*psif[l2]*testf_*Jbar*w/r;
              }
             // Axial velocity component (cosine part) W_k^C
             local_unknown = nodal_local_eqn(l2,u_nodal_index[2]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) -=
                scaled_re*r*psif[l2]*base_flow_duthetadz*testf_*Jbar*w;
              }
             // Axial velocity component (sine part) W_k^S
             local_unknown = nodal_local_eqn(l2,u_nodal_index[3]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) -=
                k*visc_ratio*Gamma[0]*psif[l2]*dtestfdz*Jbar*w;
              }
             // Azimuthal velocity component (cosine part) V_k^C
             local_unknown = nodal_local_eqn(l2,u_nodal_index[4]);
             if(local_unknown >= 0)
              {
               if(flag==2)
                {
                 // Add the mass matrix
                 mass_matrix(local_eqn,local_unknown) +=
                  scaled_re_st*r*psif[l2]*testf_*Jbar*w;
                }
               // Add contributions to the Jacobian matrix
               jacobian(local_eqn,local_unknown) -=
                scaled_re_st*r*psif[l2]
                *node_pt(l2)->time_stepper_pt()->weight(1,0)*testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) -=
                scaled_re*r*base_flow_ur*group_B[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re_st*r*mesh_velocity[0]*group_B[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) -=
                scaled_re*psif[l2]*base_flow_ur*testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) -=
                scaled_re*r*base_flow_uz*group_A[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re_st*r*mesh_velocity[1]*group_A[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*r*group_B[l2]*dtestfdr*w;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*Gamma[0]*psif[l2]*dtestfdr*Jbar*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*(1.0+Gamma[0])*k*k*psif[l2]*testf_*Jbar*w/r;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*r*group_A[l2]*dtestfdz*w;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*Gamma[0]*group_B[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*psif[l2]*testf_*Jbar*w/r;
              }
             // Azimuthal velocity component (sine part) V_k^S
             local_unknown = nodal_local_eqn(l2,u_nodal_index[5]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) -=
                k*scaled_re*base_flow_utheta*psif[l2]*testf_*Jbar*w;
              }
             // Perturbation to radial nodal coord (cosine part) R_k^C
             local_unknown = nodal_local_eqn(l2,xhat_nodal_index[0]);
             if(local_unknown >= 0)
             {
              jacobian(local_eqn,local_unknown) -=
               scaled_re_st*psif[l2]*base_flow_duthetadt*testf_*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               scaled_re_st*r*psif[l2]
               *node_pt(l2)->position_time_stepper_pt()->weight(1,0)
               *base_flow_duthetadr*testf_*Jbar*w;
              jacobian(local_eqn,local_unknown) -=
               scaled_re*psif[l2]*base_flow_ur*base_flow_duthetadr*testf_
               *Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               scaled_re_st*psif[l2]*mesh_velocity[0]*base_flow_duthetadr
               *testf_*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               scaled_re*r*base_flow_uz*group_E[l2]*testf_*w;
              jacobian(local_eqn,local_unknown) -=
               scaled_re_st*r*mesh_velocity[1]*group_E[l2]*testf_*w;
              jacobian(local_eqn,local_unknown) -=
               scaled_re*psif[l2]*base_flow_uz*base_flow_duthetadz
               *testf_*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               scaled_re_st*psif[l2]*mesh_velocity[1]*base_flow_duthetadz
               *testf_*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               psif[l2]*body_force[2]*testf_*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               scaled_re_inv_fr*psif[l2]*G[2]*testf_*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*r*base_flow_duthetadr*group_B[l2]*dtestfdr*w;
              jacobian(local_eqn,local_unknown) -=
               visc_ratio*psif[l2]*base_flow_duthetadr*dtestfdr*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*(1.0+Gamma[0])*k*k*base_flow_duthetadr
               *psif[l2]*testf_*Jbar*w/r;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*r*base_flow_duthetadz*group_F(l,l2)*w;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*r*group_E[l2]*dtestfdz*w;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*r*base_flow_duthetadz*group_B[l2]*dtestfdz*w;
              jacobian(local_eqn,local_unknown) -=
               visc_ratio*psif[l2]*base_flow_duthetadz*dtestfdz*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*base_flow_utheta*psif[l2]*testf_*Jbar*w/(r*r);
              jacobian(local_eqn,local_unknown) -=
               scaled_re_st*r*base_flow_duthetadt*testf_*group_B[l2]*w;
              jacobian(local_eqn,local_unknown) -=
               scaled_re*base_flow_utheta*base_flow_ur*testf_*group_B[l2]*w;
              jacobian(local_eqn,local_unknown) +=
               r*body_force[2]*testf_*group_B[l2]*w;
              jacobian(local_eqn,local_unknown) +=
               scaled_re_inv_fr*r*G[2]*testf_*group_B[l2]*w;
              jacobian(local_eqn,local_unknown) -=
               visc_ratio*base_flow_utheta*testf_*group_B[l2]*w/r;
             }
             // Perturbation to radial nodal coord (sine part) R_k^S
             local_unknown = nodal_local_eqn(l2,xhat_nodal_index[1]);
             if(local_unknown >= 0)
             {
              jacobian(local_eqn,local_unknown) +=
               k*scaled_re*base_flow_utheta*base_flow_duthetadr*psif[l2]
               *testf_*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               k*visc_ratio*Gamma[0]*base_flow_durdr*psif[l2]*dtestfdr*Jbar*w;
              jacobian(local_eqn,local_unknown) -=
               k*base_flow_p*dtestfdr*psif[l2]*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*(1.0+Gamma[0])*k*base_flow_ur*dtestfdr*psif[l2]
               *Jbar*w/r;
              jacobian(local_eqn,local_unknown) -=
               visc_ratio*(1.0+Gamma[0])*k*psif[l2]*base_flow_ur*testf_
               *Jbar*w/(r*r);
              jacobian(local_eqn,local_unknown) +=
               k*visc_ratio*Gamma[0]*base_flow_duzdr*psif[l2]*dtestfdz*Jbar*w;
              jacobian(local_eqn,local_unknown) -=
               visc_ratio*k*base_flow_durdr*psif[l2]*testf_*Jbar*w/r;
              jacobian(local_eqn,local_unknown) -=
               k*base_flow_p*testf_*group_B[l2]*w;
              jacobian(local_eqn,local_unknown) +=
               k*visc_ratio*(1.0+Gamma[0])*base_flow_ur*testf_*group_B[l2]*w/r;
             }
             // Perturbation to axial nodal coord (cosine part) Z_k^C
             local_unknown = nodal_local_eqn(l2,xhat_nodal_index[2]);
             if(local_unknown >= 0)
             {
              jacobian(local_eqn,local_unknown) -=
               scaled_re*r*base_flow_ur*group_E[l2]*testf_*w;
              jacobian(local_eqn,local_unknown) +=
               scaled_re_st*r*mesh_velocity[0]*group_E[l2]*testf_*w;
              jacobian(local_eqn,local_unknown) +=
               scaled_re_st*r*psif[l2]
               *node_pt(l2)->position_time_stepper_pt()->weight(1,0)
               *base_flow_duthetadz*testf_*Jbar*w;
              jacobian(local_eqn,local_unknown) -=
               visc_ratio*r*base_flow_duthetadr*group_F(l,l2)*w;
              jacobian(local_eqn,local_unknown) -=
               visc_ratio*r*group_E[l2]*dtestfdr*w;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*r*base_flow_duthetadr*group_A[l2]*dtestfdr*w;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*Gamma[0]*base_flow_utheta*group_F(l,l2)*w;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*(1.0+Gamma[0])*k*k*base_flow_duthetadz*psif[l2]
               *testf_*Jbar*w/r;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*r*base_flow_duthetadz*group_A[l2]*dtestfdz*w;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*Gamma[0]*group_E[l2]*testf_*w;
              jacobian(local_eqn,local_unknown) -=
               scaled_re_st*r*base_flow_duthetadt*testf_*group_A[l2]*w;
              jacobian(local_eqn,local_unknown) -=
               scaled_re*base_flow_utheta*base_flow_ur*testf_*group_A[l2]*w;
              jacobian(local_eqn,local_unknown) +=
               r*body_force[2]*testf_*group_A[l2]*w;
              jacobian(local_eqn,local_unknown) +=
               scaled_re_inv_fr*r*G[2]*testf_*group_A[l2]*w;
              jacobian(local_eqn,local_unknown) -=
               visc_ratio*base_flow_utheta*testf_*group_A[l2]*w/r;
             }
             // Perturbation to axial nodal coord (sine part) Z_k^S
             local_unknown = nodal_local_eqn(l2,xhat_nodal_index[3]);
             if(local_unknown >= 0)
             {
              jacobian(local_eqn,local_unknown) +=
               k*scaled_re*base_flow_utheta*base_flow_duthetadz*psif[l2]
               *testf_*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               k*visc_ratio*Gamma[0]*base_flow_durdz*psif[l2]*dtestfdr*Jbar*w;
              jacobian(local_eqn,local_unknown) -=
               k*base_flow_p*dtestfdz*psif[l2]*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               visc_ratio*(1.0+Gamma[0])*k*base_flow_ur*dtestfdz*psif[l2]
               *Jbar*w/r;
              jacobian(local_eqn,local_unknown) +=
               k*visc_ratio*Gamma[0]*base_flow_duzdz*psif[l2]*dtestfdz*Jbar*w;
              jacobian(local_eqn,local_unknown) -=
               visc_ratio*k*base_flow_durdz*psif[l2]*testf_*Jbar*w/r;
              jacobian(local_eqn,local_unknown) -=
               k*base_flow_p*testf_*group_A[l2]*w;
              jacobian(local_eqn,local_unknown) +=
               k*visc_ratio*(1.0+Gamma[0])*base_flow_ur*testf_*group_A[l2]*w/r;
             }
            } // End of loop over velocity shape functions
           // Now loop over pressure shape functions
           // (This is the contribution from pressure gradient)
           for(unsigned l2=0;l2<n_pres;l2++)
            {
             // Cosine part P_k^C has no contribution
             // Sine part P_k^S
             local_unknown = p_local_eqn(l2,1);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) -= k*psip[l2]*testf_*Jbar*w;
              }
            } // End of loop over pressure shape functions
           // Now loop over the spines in the element
           for(unsigned l2=0;l2<n_p;l2++)
            {
             // Perturbed spine "height" (cosine part) H_k^C
             local_unknown =
              get_local_eqn_number_corresponding_to_geometric_dofs(l2,0);
             if(local_unknown >= 0)
              {
               for(unsigned a=0;a<3;a++)
                {
                 double sum = 0.0;
                 sum -= scaled_re*r*base_flow_ur*group_E[l2+(3*a)]*testf_*w;
                 sum +=
                  scaled_re_st*r*mesh_velocity[0]*group_E[l2+(3*a)]*testf_*w;
                 sum +=
                  scaled_re_st*r*psif[l2+(3*a)]
                  *node_pt(l2+(3*a))->position_time_stepper_pt()->weight(1,0)
                  *base_flow_duthetadz*testf_*Jbar*w;
                 sum -=
                  visc_ratio*r*base_flow_duthetadr*group_F(l,(l2+(3*a)))*w;
                 sum -= visc_ratio*r*group_E[l2+(3*a)]*dtestfdr*w;
                 sum +=
                  visc_ratio*r*base_flow_duthetadr*group_A[l2+(3*a)]*dtestfdr*w;
                 sum +=
                  visc_ratio*Gamma[0]*base_flow_utheta*group_F(l,(l2+(3*a)))*w;
                 sum +=
                  visc_ratio*(1.0+Gamma[0])*k*k*base_flow_duthetadz
                  *psif[l2+(3*a)]*testf_*Jbar*w/r;
                 sum +=
                  visc_ratio*r*base_flow_duthetadz*group_A[l2+(3*a)]*dtestfdz*w;
                 sum += visc_ratio*Gamma[0]*group_E[l2+(3*a)]*testf_*w;
                 sum -=
                  scaled_re_st*r*base_flow_duthetadt*testf_*group_A[l2+(3*a)]*w;
                 sum -=
                  scaled_re*base_flow_utheta*base_flow_ur*testf_
                  *group_A[l2+(3*a)]*w;
                 sum += r*body_force[2]*testf_*group_A[l2+(3*a)]*w;
                 sum += scaled_re_inv_fr*r*G[2]*testf_*group_A[l2+(3*a)]*w;
                 sum -=
                  visc_ratio*base_flow_utheta*testf_*group_A[l2+(3*a)]*w/r;
                 jacobian(local_eqn,local_unknown) +=
                  sum*effective_perturbed_spine_node_fraction[l2+(3*a)];
                }
              }
             // Perturbed spine "height" (sine part) H_k^S
             local_unknown =
              get_local_eqn_number_corresponding_to_geometric_dofs(l2,1);
             if(local_unknown >= 0)
              {
               for(unsigned a=0;a<3;a++)
                {
                 double sum = 0.0;
                 sum +=
                  k*scaled_re*base_flow_utheta*base_flow_duthetadz
                  *psif[l2+(3*a)]*testf_*Jbar*w;
                 sum +=
                  k*visc_ratio*Gamma[0]*base_flow_durdz*psif[l2+(3*a)]
                  *dtestfdr*Jbar*w;
                 sum -= k*base_flow_p*dtestfdz*psif[l2+(3*a)]*Jbar*w;
                 sum +=
                  visc_ratio*(1.0+Gamma[0])*k*base_flow_ur*dtestfdz
                  *psif[l2+(3*a)]*Jbar*w/r;
                 sum +=
                  k*visc_ratio*Gamma[0]*base_flow_duzdz*psif[l2+(3*a)]
                  *dtestfdz*Jbar*w;
                 sum -=
                  visc_ratio*k*base_flow_durdz*psif[l2+(3*a)]*testf_*Jbar*w/r;
                 sum -= k*base_flow_p*testf_*group_A[l2+(3*a)]*w;
                 sum +=
                  k*visc_ratio*(1.0+Gamma[0])*base_flow_ur*testf_
                  *group_A[l2+(3*a)]*w/r;
                 jacobian(local_eqn,local_unknown) +=
                  sum*effective_perturbed_spine_node_fraction[l2+(3*a)];
                }
              }
            } // End of loop over spines in the element
          } // End of Jacobian calculation
        } // End of if not boundary condition statement
       // ----------------------------------------------
       // SIXTH (AZIMUTHAL) MOMENTUM EQUATION: SINE PART
       // ----------------------------------------------
       //if(offensive_eqn>=0) cout<<"residuals[offensive_eqn] = "<<residuals[offensive_eqn]<<endl;
       // Get local equation number of sixth velocity value at this node
       local_eqn = nodal_local_eqn(l,u_nodal_index[5]);
       // If it's not a boundary condition
       if(local_eqn >= 0)
        {
         residuals[local_eqn] -= scaled_re_st*r*dVSdt*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re_st*interpolated_RS*base_flow_duthetadt*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*r*base_flow_ur*interpolated_dVdRS*testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_st*r*mesh_velocity[0]*interpolated_dVdRS*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*r*interpolated_US*base_flow_duthetadr*testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_st*r*dRSdt*base_flow_duthetadr*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*interpolated_RS*base_flow_ur*base_flow_duthetadr
          *testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_st*interpolated_RS*mesh_velocity[0]*base_flow_duthetadr
          *testf_*Jbar*w;
         residuals[local_eqn] +=
          k*scaled_re*base_flow_utheta*interpolated_VC*testf_*Jbar*w;
         residuals[local_eqn] -=
          k*scaled_re*base_flow_utheta*base_flow_duthetadr*interpolated_RC
          *testf_*Jbar*w;
         residuals[local_eqn] -=
          k*scaled_re*base_flow_utheta*base_flow_duthetadz*interpolated_ZC
          *testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*base_flow_utheta*interpolated_US*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*interpolated_VS*base_flow_ur*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*r*base_flow_uz*interpolated_dVdZS*testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_st*r*mesh_velocity[1]*interpolated_dVdZS*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*r*interpolated_WS*base_flow_duthetadz*testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_st*r*dZSdt*base_flow_duthetadz*testf_*Jbar*w;
         residuals[local_eqn] -=
          scaled_re*interpolated_RS*base_flow_uz*base_flow_duthetadz
          *testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_st*interpolated_RS*mesh_velocity[1]*base_flow_duthetadz
          *testf_*Jbar*w;
         residuals[local_eqn] += interpolated_RS*body_force[2]*testf_*Jbar*w;
         residuals[local_eqn] +=
          scaled_re_inv_fr*interpolated_RS*G[2]*testf_*Jbar*w;
         residuals[local_eqn] -=
          visc_ratio*r*base_flow_duthetadr*dtestfdRS*Jbar*w;
         residuals[local_eqn] -=
          visc_ratio*r*interpolated_dVdRS*dtestfdr*Jbar*w;
         residuals[local_eqn] +=
          visc_ratio*r*base_flow_duthetadr*JhatS*dtestfdr*w;
         residuals[local_eqn] -=
          visc_ratio*interpolated_RS*base_flow_duthetadr*dtestfdr*Jbar*w;
         residuals[local_eqn] +=
          k*visc_ratio*Gamma[0]*interpolated_UC*dtestfdr*Jbar*w;
         residuals[local_eqn] -=
          k*visc_ratio*Gamma[0]*base_flow_durdr*interpolated_RC*dtestfdr*Jbar*w;
         residuals[local_eqn] -=
          k*visc_ratio*Gamma[0]*base_flow_durdz*interpolated_ZC*dtestfdr*Jbar*w;
         residuals[local_eqn] +=
          visc_ratio*Gamma[0]*base_flow_utheta*dtestfdRS*Jbar*w;
         residuals[local_eqn] +=
          visc_ratio*Gamma[0]*interpolated_VS*dtestfdr*Jbar*w;
         residuals[local_eqn] += k*base_flow_p*dtestfdr*interpolated_RC*Jbar*w;
         residuals[local_eqn] += k*base_flow_p*dtestfdz*interpolated_ZC*Jbar*w;
         residuals[local_eqn] += k*interpolated_PC*testf_*Jbar*w;
         residuals[local_eqn] -=
          visc_ratio*(1.0+Gamma[0])*k*k*interpolated_VS*testf_*Jbar*w/r;
         residuals[local_eqn] +=
          visc_ratio*(1.0+Gamma[0])*k*k*base_flow_duthetadr*interpolated_RS
          *testf_*Jbar*w/r;
         residuals[local_eqn] +=
          visc_ratio*(1.0+Gamma[0])*k*k*base_flow_duthetadz*interpolated_ZS
          *testf_*Jbar*w/r;
         residuals[local_eqn] -=
          visc_ratio*(1.0+Gamma[0])*k*base_flow_ur*dtestfdr*interpolated_RC
          *Jbar*w/r;
         residuals[local_eqn] -=
          visc_ratio*(1.0+Gamma[0])*k*base_flow_ur*dtestfdz*interpolated_ZC
          *Jbar*w/r;
         residuals[local_eqn] -=
          visc_ratio*(1.0+Gamma[0])*k*interpolated_UC*testf_*Jbar*w/r;
         residuals[local_eqn] +=
          visc_ratio*(1.0+Gamma[0])*k*interpolated_RC*base_flow_ur
          *testf_*Jbar*w/(r*r);
         residuals[local_eqn] +=
          k*visc_ratio*Gamma[0]*interpolated_WC*dtestfdz*Jbar*w;
         residuals[local_eqn] -=
          k*visc_ratio*Gamma[0]*base_flow_duzdr*interpolated_RC*dtestfdz
          *Jbar*w;
         residuals[local_eqn] -=
          k*visc_ratio*Gamma[0]*base_flow_duzdz*interpolated_ZC*dtestfdz
          *Jbar*w;
         residuals[local_eqn] -=
          visc_ratio*r*base_flow_duthetadz*dtestfdZS*Jbar*w;
         residuals[local_eqn] -=
          visc_ratio*r*interpolated_dVdZS*dtestfdz*Jbar*w;
         residuals[local_eqn] +=
          visc_ratio*r*base_flow_duthetadz*JhatS*dtestfdz*w;
         residuals[local_eqn] -=
          visc_ratio*interpolated_RS*base_flow_duthetadz*dtestfdz*Jbar*w;
         residuals[local_eqn] +=
          visc_ratio*Gamma[0]*interpolated_dVdRS*testf_*Jbar*w;
         residuals[local_eqn] -= visc_ratio*k*interpolated_UC*testf_*Jbar*w/r;
         residuals[local_eqn] +=
          visc_ratio*k*base_flow_durdr*interpolated_RC*testf_*Jbar*w/r;
         residuals[local_eqn] +=
          visc_ratio*k*base_flow_durdz*interpolated_ZC*testf_*Jbar*w/r;
         residuals[local_eqn] -= visc_ratio*interpolated_VS*testf_*Jbar*w/r;
         residuals[local_eqn] +=
          visc_ratio*base_flow_utheta*interpolated_RS*testf_*Jbar*w/(r*r);
         residuals[local_eqn] -=
          scaled_re_st*r*base_flow_duthetadt*testf_*JhatS*w;
         residuals[local_eqn] -=
          scaled_re*base_flow_utheta*base_flow_ur*testf_*JhatS*w;
         residuals[local_eqn] += r*body_force[2]*testf_*JhatS*w;
         residuals[local_eqn] += scaled_re_inv_fr*r*G[2]*testf_*JhatS*w;
         residuals[local_eqn] += k*base_flow_p*testf_*JhatC*w;
         residuals[local_eqn] -=
          k*visc_ratio*(1.0+Gamma[0])*base_flow_ur*testf_*JhatC*w/r;
         residuals[local_eqn] -= visc_ratio*base_flow_utheta*testf_*JhatS*w/r;
         // Calculate the Jacobian
         // ----------------------
         if(flag)
          {
           // Loop over the velocity shape functions again
           for(unsigned l2=0;l2<n_node;l2++)
            {
             // Radial velocity component (cosine part) U_k^C
             local_unknown = nodal_local_eqn(l2,u_nodal_index[0]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) +=
                k*visc_ratio*Gamma[0]*psif[l2]*dtestfdr*Jbar*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*(1.0+Gamma[0])*k*psif[l2]*testf_*Jbar*w/r;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*k*psif[l2]*testf_*Jbar*w/r;
              }
             // Radial velocity component (sine part) U_k^S
             local_unknown = nodal_local_eqn(l2,u_nodal_index[1]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) -=
                scaled_re*r*psif[l2]*base_flow_duthetadr*testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) -=
                scaled_re*base_flow_utheta*psif[l2]*testf_*Jbar*w;
              }
             // Axial velocity component (cosine part) W_k^C
             local_unknown = nodal_local_eqn(l2,u_nodal_index[2]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) +=
                k*visc_ratio*Gamma[0]*psif[l2]*dtestfdz*Jbar*w;
              }
             // Axial velocity component (sine part) W_k^S
             local_unknown = nodal_local_eqn(l2,u_nodal_index[3]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) -=
                scaled_re*r*psif[l2]*base_flow_duthetadz*testf_*Jbar*w;
              }
             // Azimuthal velocity component (cosine part) V_k^C
             local_unknown = nodal_local_eqn(l2,u_nodal_index[4]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) +=
                k*scaled_re*base_flow_utheta*psif[l2]*testf_*Jbar*w;
              }
             // Azimuthal velocity component (sine part) V_k^S
             local_unknown = nodal_local_eqn(l2,u_nodal_index[5]);
             if(local_unknown >= 0)
              {
               if(flag==2)
                {
                 // Add the mass matrix
                 mass_matrix(local_eqn,local_unknown) +=
                  scaled_re_st*r*psif[l2]*testf_*Jbar*w;
                }
               // Add contributions to the Jacobian matrix
               jacobian(local_eqn,local_unknown) -=
                scaled_re_st*r*psif[l2]
                *node_pt(l2)->time_stepper_pt()->weight(1,0)*testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) -=
                scaled_re*r*base_flow_ur*group_B[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re_st*r*mesh_velocity[0]*group_B[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) -=
                scaled_re*psif[l2]*base_flow_ur*testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) -=
                scaled_re*r*base_flow_uz*group_A[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re_st*r*mesh_velocity[1]*group_A[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*r*group_B[l2]*dtestfdr*w;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*Gamma[0]*psif[l2]*dtestfdr*Jbar*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*(1.0+Gamma[0])*k*k*psif[l2]*testf_*Jbar*w/r;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*r*group_A[l2]*dtestfdz*w;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*Gamma[0]*group_B[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*psif[l2]*testf_*Jbar*w/r;
              }
             // Perturbation to radial nodal coord (cosine part) R_k^C
             local_unknown = nodal_local_eqn(l2,xhat_nodal_index[0]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) -=
                k*scaled_re*base_flow_utheta*base_flow_duthetadr
                *psif[l2]*testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) -=
                k*visc_ratio*Gamma[0]*base_flow_durdr*psif[l2]*dtestfdr*Jbar*w;
               jacobian(local_eqn,local_unknown) +=
                k*base_flow_p*dtestfdr*psif[l2]*Jbar*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*(1.0+Gamma[0])*k*base_flow_ur*dtestfdr
                *psif[l2]*Jbar*w/r;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*(1.0+Gamma[0])*k*psif[l2]*base_flow_ur
                *testf_*Jbar*w/(r*r);
               jacobian(local_eqn,local_unknown) -=
                k*visc_ratio*Gamma[0]*base_flow_duzdr*psif[l2]*dtestfdz*Jbar*w;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*k*base_flow_durdr*psif[l2]*testf_*Jbar*w/r;
               jacobian(local_eqn,local_unknown) +=
                k*base_flow_p*testf_*group_B[l2]*w;
               jacobian(local_eqn,local_unknown) -=
                k*visc_ratio*(1.0+Gamma[0])*base_flow_ur*testf_
                *group_B[l2]*w/r;
              }
             // Perturbation to radial nodal coord (sine part) R_k^S
             local_unknown = nodal_local_eqn(l2,xhat_nodal_index[1]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) -=
                scaled_re_st*psif[l2]*base_flow_duthetadt*testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re_st*r*psif[l2]
                *node_pt(l2)->position_time_stepper_pt()->weight(1,0)
                *base_flow_duthetadr*testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) -=
                scaled_re*psif[l2]*base_flow_ur*base_flow_duthetadr
                *testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re_st*psif[l2]*mesh_velocity[0]*base_flow_duthetadr
                *testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re*r*base_flow_uz*group_E[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) -=
                scaled_re_st*r*mesh_velocity[1]*group_E[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) -=
                scaled_re*psif[l2]*base_flow_uz*base_flow_duthetadz
                *testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re_st*psif[l2]*mesh_velocity[1]*base_flow_duthetadz
                *testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) +=
                psif[l2]*body_force[2]*testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re_inv_fr*psif[l2]*G[2]*testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*r*base_flow_duthetadr*group_B[l2]*dtestfdr*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*psif[l2]*base_flow_duthetadr*dtestfdr*Jbar*w;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*(1.0+Gamma[0])*k*k*base_flow_duthetadr*psif[l2]
                *testf_*Jbar*w/r;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*r*base_flow_duthetadz*group_F(l,l2)*w;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*r*group_E[l2]*dtestfdz*w;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*r*base_flow_duthetadz*group_B[l2]*dtestfdz*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*psif[l2]*base_flow_duthetadz*dtestfdz*Jbar*w;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*base_flow_utheta*psif[l2]*testf_*Jbar*w/(r*r);
               jacobian(local_eqn,local_unknown) -=
                scaled_re_st*r*base_flow_duthetadt*testf_*group_B[l2]*w;
               jacobian(local_eqn,local_unknown) -=
                scaled_re*base_flow_utheta*base_flow_ur*testf_*group_B[l2]*w;
               jacobian(local_eqn,local_unknown) +=
                r*body_force[2]*testf_*group_B[l2]*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re_inv_fr*r*G[2]*testf_*group_B[l2]*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*base_flow_utheta*testf_*group_B[l2]*w/r;
              }
             // Perturbation to axial nodal coord (cosine part) Z_k^C
             local_unknown = nodal_local_eqn(l2,xhat_nodal_index[2]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) -=
                k*scaled_re*base_flow_utheta*base_flow_duthetadz*psif[l2]
                *testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) -=
                k*visc_ratio*Gamma[0]*base_flow_durdz*psif[l2]*dtestfdr*Jbar*w;
               jacobian(local_eqn,local_unknown) +=
                k*base_flow_p*dtestfdz*psif[l2]*Jbar*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*(1.0+Gamma[0])*k*base_flow_ur*dtestfdz*psif[l2]
                *Jbar*w/r;
               jacobian(local_eqn,local_unknown) -=
                k*visc_ratio*Gamma[0]*base_flow_duzdz*psif[l2]*dtestfdz*Jbar*w;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*k*base_flow_durdz*psif[l2]*testf_*Jbar*w/r;
               jacobian(local_eqn,local_unknown) +=
                k*base_flow_p*testf_*group_A[l2]*w;
               jacobian(local_eqn,local_unknown) -=
                k*visc_ratio*(1.0+Gamma[0])*base_flow_ur*testf_*group_A[l2]*w/r;
              }
             // Perturbation to axial nodal coord (sine part) Z_k^S
             local_unknown = nodal_local_eqn(l2,xhat_nodal_index[3]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) -=
                scaled_re*r*base_flow_ur*group_E[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re_st*r*mesh_velocity[0]*group_E[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re_st*r*psif[l2]
                *node_pt(l2)->position_time_stepper_pt()->weight(1,0)
                *base_flow_duthetadz*testf_*Jbar*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*r*base_flow_duthetadr*group_F(l,l2)*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*r*group_E[l2]*dtestfdr*w;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*r*base_flow_duthetadr*group_A[l2]*dtestfdr*w;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*Gamma[0]*base_flow_utheta*group_F(l,l2)*w;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*(1.0+Gamma[0])*k*k*base_flow_duthetadz*psif[l2]
                *testf_*Jbar*w/r;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*r*base_flow_duthetadz*group_A[l2]*dtestfdz*w;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*Gamma[0]*group_E[l2]*testf_*w;
               jacobian(local_eqn,local_unknown) -=
                scaled_re_st*r*base_flow_duthetadt*testf_*group_A[l2]*w;
               jacobian(local_eqn,local_unknown) -=
                scaled_re*base_flow_utheta*base_flow_ur*testf_*group_A[l2]*w;
               jacobian(local_eqn,local_unknown) +=
                r*body_force[2]*testf_*group_A[l2]*w;
               jacobian(local_eqn,local_unknown) +=
                scaled_re_inv_fr*r*G[2]*testf_*group_A[l2]*w;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*base_flow_utheta*testf_*group_A[l2]*w/r;
              }
            } // End of loop over velocity shape functions
           // Now loop over pressure shape functions
           // (This is the contribution from pressure gradient)
           for(unsigned l2=0;l2<n_pres;l2++)
            {
             // Cosine part P_k^C
             local_unknown = p_local_eqn(l2,0);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) += k*psip[l2]*testf_*Jbar*w;
              }
             // Sine part P_k^S has no contribution
            } // End of loop over pressure shape functions
           // Now loop over the spines in the element
           for(unsigned l2=0;l2<n_p;l2++)
            {
             // Perturbed spine "height" (cosine part) H_k^C
             local_unknown =
              get_local_eqn_number_corresponding_to_geometric_dofs(l2,0);
             if(local_unknown >= 0)
              {
               for(unsigned a=0;a<3;a++)
                {
                 double sum = 0.0;
                 sum -=
                  k*scaled_re*base_flow_utheta*base_flow_duthetadz
                  *psif[l2+(3*a)]*testf_*Jbar*w;
                 sum -=
                  k*visc_ratio*Gamma[0]*base_flow_durdz*psif[l2+(3*a)]
                  *dtestfdr*Jbar*w;
                 sum += k*base_flow_p*dtestfdz*psif[l2+(3*a)]*Jbar*w;
                 sum -=
                  visc_ratio*(1.0+Gamma[0])*k*base_flow_ur*dtestfdz
                  *psif[l2+(3*a)]*Jbar*w/r;
                 sum -=
                  k*visc_ratio*Gamma[0]*base_flow_duzdz*psif[l2+(3*a)]
                  *dtestfdz*Jbar*w;
                 sum +=
                  visc_ratio*k*base_flow_durdz*psif[l2+(3*a)]*testf_*Jbar*w/r;
                 sum += k*base_flow_p*testf_*group_A[l2+(3*a)]*w;
                 sum -=
                  k*visc_ratio*(1.0+Gamma[0])*base_flow_ur*testf_
                  *group_A[l2+(3*a)]*w/r;
                 jacobian(local_eqn,local_unknown) +=
                  sum*effective_perturbed_spine_node_fraction[l2+(3*a)];
                }
              }
             // Perturbed spine "height" (sine part) H_k^S
             local_unknown =
              get_local_eqn_number_corresponding_to_geometric_dofs(l2,1);
             if(local_unknown >= 0)
              {
               for(unsigned a=0;a<3;a++)
                {
                 double sum = 0.0;
                 sum -= scaled_re*r*base_flow_ur*group_E[l2+(3*a)]*testf_*w;
                 sum +=
                  scaled_re_st*r*mesh_velocity[0]*group_E[l2+(3*a)]*testf_*w;
                 sum +=
                  scaled_re_st*r*psif[l2+(3*a)]
                  *node_pt(l2+(3*a))->position_time_stepper_pt()->weight(1,0)
                  *base_flow_duthetadz*testf_*Jbar*w;
                 sum -=
                  visc_ratio*r*base_flow_duthetadr*group_F(l,(l2+(3*a)))*w;
                 sum -= visc_ratio*r*group_E[l2+(3*a)]*dtestfdr*w;
                 sum +=
                  visc_ratio*r*base_flow_duthetadr*group_A[l2+(3*a)]
                  *dtestfdr*w;
                 sum +=
                  visc_ratio*Gamma[0]*base_flow_utheta*group_F(l,(l2+(3*a)))*w;
                 sum +=
                  visc_ratio*(1.0+Gamma[0])*k*k*base_flow_duthetadz
                  *psif[l2+(3*a)]*testf_*Jbar*w/r;
                 sum +=
                  visc_ratio*r*base_flow_duthetadz*group_A[l2+(3*a)]*dtestfdz*w;
                 sum += visc_ratio*Gamma[0]*group_E[l2+(3*a)]*testf_*w;
                 sum -=
                  scaled_re_st*r*base_flow_duthetadt*testf_*group_A[l2+(3*a)]*w;
                 sum -=
                  scaled_re*base_flow_utheta*base_flow_ur*testf_
                  *group_A[l2+(3*a)]*w;
                 sum += r*body_force[2]*testf_*group_A[l2+(3*a)]*w;
                 sum += scaled_re_inv_fr*r*G[2]*testf_*group_A[l2+(3*a)]*w;
                 sum -=
                  visc_ratio*base_flow_utheta*testf_*group_A[l2+(3*a)]*w/r;
                 jacobian(local_eqn,local_unknown) +=
                  sum*effective_perturbed_spine_node_fraction[l2+(3*a)];
                }
              }
            } // End of loop over spines in the element
          } // End of Jacobian calculation
        } // End of if not boundary condition statement
      } // End of loop over fluid test functions
     // ====================
     // CONTINUITY EQUATIONS
     // ====================
     // Loop over the pressure test functions
     for(unsigned l=0;l<n_pres;l++)
      {
       // Cache the test function
       const double testp_ = testp[l];
       // --------------------------------------
       // FIRST CONTINUITY EQUATION: COSINE PART
       // --------------------------------------
       // Get local equation number of first pressure value at this node
       local_eqn = p_local_eqn(l,0);
       // If it's not a boundary condition
       if(local_eqn >= 0)
        {
         residuals[local_eqn] += r*interpolated_dUdRC*testp_*Jbar*w;
         residuals[local_eqn] += interpolated_RC*base_flow_durdr*testp_*Jbar*w;
         residuals[local_eqn] += interpolated_UC*testp_*Jbar*w;
         residuals[local_eqn] += k*interpolated_VS*testp_*Jbar*w;
         residuals[local_eqn] -=
          k*base_flow_duthetadr*interpolated_RS*testp_*Jbar*w;
         residuals[local_eqn] -=
          k*base_flow_duthetadz*interpolated_ZS*testp_*Jbar*w;
         residuals[local_eqn] += r*interpolated_dWdZC*testp_*Jbar*w;
         residuals[local_eqn] += interpolated_RC*base_flow_duzdz*testp_*Jbar*w;
         residuals[local_eqn] -= interpolated_RC*source*testp_*Jbar*w;
         residuals[local_eqn] += base_flow_ur*testp_*JhatC*w;
         residuals[local_eqn] -= source*r*testp_*JhatC*w;
         // Calculate the Jacobian
         // ----------------------
         if(flag)
          {
           // Loop over the velocity shape functions
           for(unsigned l2=0;l2<n_node;l2++)
            {
             // Radial velocity component (cosine part) U_k^C
             local_unknown = nodal_local_eqn(l2,u_nodal_index[0]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) += r*group_B[l2]*testp_*w;
               jacobian(local_eqn,local_unknown) += psif[l2]*testp_*Jbar*w;
              }
             // Radial velocity component (sine part) U_k^S
             // has no contribution
             // Axial velocity component (cosine part) W_k^C
             local_unknown = nodal_local_eqn(l2,u_nodal_index[2]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) += r*group_A[l2]*testp_*w;
              }
             // Axial velocity component (sine part) W_k^S
             // has no contribution
             // Azimuthal velocity component (cosine part) V_k^C
             // has no contribution
             // Azimuthal velocity component (sine part) V_k^S
             local_unknown = nodal_local_eqn(l2,u_nodal_index[5]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) += k*psif[l2]*testp_*Jbar*w;
              }
             // Perturbation to radial nodal coord (cosine part) R_k^C
             local_unknown = nodal_local_eqn(l2,xhat_nodal_index[0]);
             if(local_unknown >= 0)
             {
              jacobian(local_eqn,local_unknown) +=
               psif[l2]*base_flow_durdr*testp_*Jbar*w;
              jacobian(local_eqn,local_unknown) -= r*group_D[l2]*testp_*w;
              jacobian(local_eqn,local_unknown) +=
               psif[l2]*base_flow_duzdz*testp_*Jbar*w;
              jacobian(local_eqn,local_unknown) -=
               psif[l2]*source*testp_*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               base_flow_ur*testp_*group_B[l2]*w;
              jacobian(local_eqn,local_unknown) -=
               source*r*testp_*group_B[l2]*w;
             }
             // Perturbation to radial nodal coord (sine part) R_k^S
             local_unknown = nodal_local_eqn(l2,xhat_nodal_index[1]);
             if(local_unknown >= 0)
             {
              jacobian(local_eqn,local_unknown) -=
               k*base_flow_duthetadr*psif[l2]*testp_*Jbar*w;
             }
             // Perturbation to axial nodal coord (cosine part) Z_k^C
             local_unknown = nodal_local_eqn(l2,xhat_nodal_index[2]);
             if(local_unknown >= 0)
             {
              jacobian(local_eqn,local_unknown) += r*group_C[l2]*testp_*w;
              jacobian(local_eqn,local_unknown) +=
               base_flow_ur*testp_*group_A[l2]*w;
              jacobian(local_eqn,local_unknown) -=
               source*r*testp_*group_A[l2]*w;
             }
             // Perturbation to axial nodal coord (sine part) Z_k^S
             local_unknown = nodal_local_eqn(l2,xhat_nodal_index[3]);
             if(local_unknown >= 0)
             {
              jacobian(local_eqn,local_unknown) -=
               k*base_flow_duthetadz*psif[l2]*testp_*Jbar*w;
             }
            } // End of loop over velocity shape functions
           // Real and imaginary pressure components, P_k^C and P_k^S,
           // have no contribution
           // Now loop over the spines in the element
           for(unsigned l2=0;l2<n_p;l2++)
            {
             // Perturbed spine "height" (cosine part) H_k^C
             local_unknown =
              get_local_eqn_number_corresponding_to_geometric_dofs(l2,0);
             if(local_unknown >= 0)
              {
               for(unsigned a=0;a<3;a++)
                {
                 double sum = 0.0;
                 sum += r*group_C[l2+(3*a)]*testp_*w;
                 sum += base_flow_ur*testp_*group_A[l2+(3*a)]*w;
                 sum -= source*r*testp_*group_A[l2+(3*a)]*w;
                 jacobian(local_eqn,local_unknown) +=
                  sum*effective_perturbed_spine_node_fraction[l2+(3*a)];
                }
              }
             // Perturbed spine "height" (sine part) H_k^S
             local_unknown =
              get_local_eqn_number_corresponding_to_geometric_dofs(l2,1);
             if(local_unknown >= 0)
              {
               for(unsigned a=0;a<3;a++)
                {
                 double sum = 0.0;
                 sum -= k*base_flow_duthetadz*psif[l2+(3*a)]*testp_*Jbar*w;
                 jacobian(local_eqn,local_unknown) +=
                  sum*effective_perturbed_spine_node_fraction[l2+(3*a)];
                }
              }
            } // End of loop over spines in the element
          } // End of Jacobian calculation
        } // End of if not boundary condition statement
       // -------------------------------------
       // SECOND CONTINUITY EQUATION: SINE PART
       // -------------------------------------
       // Get local equation number of second pressure value at this node
       local_eqn = p_local_eqn(l,1);
       // If it's not a boundary condition
       if(local_eqn >= 0)
        {
         residuals[local_eqn] += r*interpolated_dUdRS*testp_*Jbar*w;
         residuals[local_eqn] += interpolated_RS*base_flow_durdr*testp_*Jbar*w;
         residuals[local_eqn] += interpolated_US*testp_*Jbar*w;
         residuals[local_eqn] -= k*interpolated_VC*testp_*Jbar*w;
         residuals[local_eqn] +=
          k*base_flow_duthetadr*interpolated_RC*testp_*Jbar*w;
         residuals[local_eqn] +=
          k*base_flow_duthetadz*interpolated_ZC*testp_*Jbar*w;
         residuals[local_eqn] += r*interpolated_dWdZS*testp_*Jbar*w;
         residuals[local_eqn] += interpolated_RS*base_flow_duzdz*testp_*Jbar*w;
         residuals[local_eqn] -= interpolated_RS*source*testp_*Jbar*w;
         residuals[local_eqn] += base_flow_ur*testp_*JhatS*w;
         residuals[local_eqn] -= source*r*testp_*JhatS*w;
         // Calculate the Jacobian
         // ----------------------
         if(flag)
          {
           // Loop over the velocity shape functions
           for(unsigned l2=0;l2<n_node;l2++)
            {
             // Radial velocity component (cosine part) U_k^C
             // has no contribution
             // Radial velocity component (sine part) U_k^S
             local_unknown = nodal_local_eqn(l2,u_nodal_index[1]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) += r*group_B[l2]*testp_*w;
               jacobian(local_eqn,local_unknown) += psif[l2]*testp_*Jbar*w;
              }
             // Axial velocity component (cosine part) W_k^C
             // has no contribution
             // Axial velocity component (sine part) W_k^S
             local_unknown = nodal_local_eqn(l2,u_nodal_index[3]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) += r*group_A[l2]*testp_*w;
              }
             // Azimuthal velocity component (cosine part) V_k^C
             local_unknown = nodal_local_eqn(l2,u_nodal_index[4]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) -= k*psif[l2]*testp_*Jbar*w;
              }
             // Azimuthal velocity component (sine part) V_k^S
             // has no contribution
             // Perturbation to radial nodal coord (cosine part) R_k^C
             local_unknown = nodal_local_eqn(l2,xhat_nodal_index[0]);
             if(local_unknown >= 0)
             {
              jacobian(local_eqn,local_unknown) +=
               k*base_flow_duthetadr*psif[l2]*testp_*Jbar*w;
             }
             // Perturbation to radial nodal coord (sine part) R_k^S
             local_unknown = nodal_local_eqn(l2,xhat_nodal_index[1]);
             if(local_unknown >= 0)
             {
              jacobian(local_eqn,local_unknown) +=
               psif[l2]*base_flow_durdr*testp_*Jbar*w;
              jacobian(local_eqn,local_unknown) -=
               r*group_D[l2]*testp_*w;
              jacobian(local_eqn,local_unknown) +=
               psif[l2]*base_flow_duzdz*testp_*Jbar*w;
              jacobian(local_eqn,local_unknown) -=
               psif[l2]*source*testp_*Jbar*w;
              jacobian(local_eqn,local_unknown) +=
               base_flow_ur*testp_*group_B[l2]*w;
              jacobian(local_eqn,local_unknown) -=
               source*r*testp_*group_B[l2]*w;
             }
             // Perturbation to axial nodal coord (cosine part) Z_k^C
             local_unknown = nodal_local_eqn(l2,xhat_nodal_index[2]);
             if(local_unknown >= 0)
             {
              jacobian(local_eqn,local_unknown) +=
               k*base_flow_duthetadz*psif[l2]*testp_*Jbar*w;
             }
             // Perturbation to axial nodal coord (sine part) Z_k^S
             local_unknown = nodal_local_eqn(l2,xhat_nodal_index[3]);
             if(local_unknown >= 0)
             {
              jacobian(local_eqn,local_unknown) += r*group_C[l2]*testp_*w;
              jacobian(local_eqn,local_unknown) +=
               base_flow_ur*testp_*group_A[l2]*w;
              jacobian(local_eqn,local_unknown) -=
               source*r*testp_*group_A[l2]*w;
             }
            } // End of loop over velocity shape functions
           // Real and imaginary pressure components, P_k^C and P_k^S,
           // have no contribution
           // Now loop over the spines in the element
           for(unsigned l2=0;l2<n_p;l2++)
            {
             // Perturbed spine "height" (cosine part) H_k^C
             local_unknown =
              get_local_eqn_number_corresponding_to_geometric_dofs(l2,0);
             if(local_unknown >= 0)
              {
               for(unsigned a=0;a<3;a++)
                {
                 double sum = 0.0;
                 sum += k*base_flow_duthetadz*psif[l2+(3*a)]*testp_*Jbar*w;
                 jacobian(local_eqn,local_unknown) +=
                  sum*effective_perturbed_spine_node_fraction[l2+(3*a)];
                }
              }
             // Perturbed spine "height" (sine part) H_k^S
             local_unknown =
              get_local_eqn_number_corresponding_to_geometric_dofs(l2,1);
             if(local_unknown >= 0)
              {
               for(unsigned a=0;a<3;a++)
                {
                 double sum = 0.0;
                 sum += r*group_C[l2+(3*a)]*testp_*w;
                 sum += base_flow_ur*testp_*group_A[l2+(3*a)]*w;
                 sum -= source*r*testp_*group_A[l2+(3*a)]*w;
                 jacobian(local_eqn,local_unknown) +=
                  sum*effective_perturbed_spine_node_fraction[l2+(3*a)];
                }
              }
            } // End of loop over spines in the element
          } // End of Jacobian calculation
        } // End of if not boundary condition statement
      } // End of loop over pressure test functions
    } // End of loop over the integration points
  } // End of fill_in_generic_residual_contribution_lin_axi_nst
References a, ALE_is_disabled, azimuthal_mode_number(), Global_Parameters::body_force(), density_ratio(), dnodal_position_perturbation_dt_lin_axi_nst(), dshape_and_dtest_eulerian_at_knot_lin_axi_nst(), oomph::FiniteElement::dshape_local_at_knot(), du_dt_lin_axi_nst(), oomph::PerturbedSpineNode::fraction(), G, g(), Gamma, get_base_flow_duds(), get_base_flow_dudt(), get_base_flow_dudx(), get_base_flow_p(), get_base_flow_u(), get_body_force_base_flow(), get_local_eqn_number_corresponding_to_geometric_dofs(), get_source_base_flow(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), j, k, oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nnode_1d(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), oomph::PerturbedSpineNode::node_update_fct_id(), npres_lin_axi_nst(), oomph::Integral::nweight(), OOMPH_EXCEPTION_LOCATION, p_lin_axi_nst(), p_local_eqn(), oomph::Node::position_time_stepper_pt(), pshape_lin_axi_nst(), UniformPSDSelfTest::r, oomph::FiniteElement::raw_dnodal_position_dt(), oomph::FiniteElement::raw_nodal_position(), oomph::FiniteElement::raw_nodal_value(), re(), re_invfr(), re_st(), s, TestProblem::source(), oomph::TimeStepper::time(), oomph::Data::time_stepper_pt(), u_index_lin_axi_nst(), viscosity_ratio(), w, oomph::Integral::weight(), oomph::TimeStepper::weight(), and xhat_index_lin_axi_nst().
Referenced by fill_in_contribution_to_jacobian(), fill_in_contribution_to_jacobian_and_mass_matrix(), and fill_in_contribution_to_residuals().
fill_in_generic_residual_contribution_linearised_axi_nst() [1/2]
void oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, unsigned flag) protected virtual
Compute the residuals for the Navier-Stokes equations; flag=1(or 0): do (or don't) compute the Jacobian as well.
Compute the residuals for the Navier–Stokes equations; flag=1(or 0): do (or don't) compute the Jacobian as well.
Compute the residuals for the linearised axisymmetric Navier–Stokes equations; flag=1(or 0): do (or don't) compute the Jacobian as well.
Reimplemented in oomph::RefineableLinearisedAxisymmetricNavierStokesEquations, and oomph::RefineableLinearisedAxisymmetricNavierStokesEquations.
  {
   // Determine number of nodes in the element
   const unsigned n_node = nnode();
   // Get continuous time from timestepper of first node
   double time=node_pt(0)->time_stepper_pt()->time_pt()->time();
   // Determine how many pressure values there are associated with
   // a single pressure component
   const unsigned n_pres = npres_linearised_axi_nst();
   // Get the nodal indices at which the velocity is stored
   unsigned u_nodal_index[6];
   for(unsigned i=0;i<6;++i)
    {
     u_nodal_index[i] = u_index_linearised_axi_nst(i);
    }
   // Set up memory for the fluid shape and test functions
   // Note that there are two dimensions, r and z, in this problem
   Shape psif(n_node), testf(n_node);
   DShape dpsifdx(n_node,2), dtestfdx(n_node,2);
   // Set up memory for the pressure shape and test functions
   Shape psip(n_pres), testp(n_pres);
   // Determine number of integration points
   const unsigned n_intpt = integral_pt()->nweight();
   // Set up memory for the vector to hold local coordinates (two dimensions)
   Vector<double> s(2);
   // Get physical variables from the element
   // (Reynolds number must be multiplied by the density ratio)
   const double scaled_re = re()*density_ratio();
   const double scaled_re_st = re_st()*density_ratio();
   const double visc_ratio = viscosity_ratio();
   const int k = azimuthal_mode_number();
   // Integers used to store the local equation and unknown numbers
   int local_eqn = 0, local_unknown = 0;
   // Loop over the integration points
   for(unsigned ipt=0;ipt<n_intpt;ipt++)
    {
     // Assign values of the local coordinates s
     for(unsigned i=0;i<2;i++) { s[i] = integral_pt()->knot(ipt,i); }
     // Get the integral weight
     const double w = integral_pt()->weight(ipt);
     // Calculate the fluid shape and test functions, and their derivatives
     // w.r.t. the global coordinates
     const double J =
      dshape_and_dtest_eulerian_at_knot_linearised_axi_nst(ipt,psif,dpsifdx,
                                                           testf,dtestfdx);
     // Calculate the pressure shape and test functions
     pshape_linearised_axi_nst(s,psip,testp);
     // Premultiply the weights and the Jacobian of the mapping between
     // local and global coordinates
     const double W = w*J;
     // Allocate storage for the position and the derivative of the
     // mesh positions w.r.t. time
     Vector<double> interpolated_x(2,0.0);
     Vector<double> mesh_velocity(2,0.0);
     // Allocate storage for the velocity components (six of these)
     // and their derivatives w.r.t. time
     Vector<double> interpolated_u(6,0.0);
     Vector<double> dudt(6,0.0);
     // Allocate storage for the pressure components (two of these)
     Vector<double> interpolated_p(2,0.0);
     // Allocate storage for the derivatives of the velocity components
     // w.r.t. global coordinates (r and z)
     DenseMatrix<double> interpolated_dudx(6,2,0.0);
     // Calculate pressure at the integration point
     // -------------------------------------------
     // Loop over pressure degrees of freedom (associated with a single
     // pressure component) in the element
     for(unsigned l=0;l<n_pres;l++)
      {
       // Cache the shape function
       const double psip_ = psip(l);
       // Loop over the two pressure components
       for(unsigned i=0;i<2;i++)
        {
         // Get the value
         const double p_value = this->p_linearised_axi_nst(l,i);
         // Add contribution
         interpolated_p[i] += p_value*psip_;
        }
      } // End of loop over the pressure degrees of freedom in the element
     // Calculate velocities and their derivatives at the integration point
     // -------------------------------------------------------------------
     // Loop over the element's nodes
     for(unsigned l=0;l<n_node;l++)
      {
       // Cache the shape function
       const double psif_ = psif(l);
       // Loop over the two coordinate directions
       for(unsigned i=0;i<2;i++)
        {
         interpolated_x[i] += this->raw_nodal_position(l,i)*psif_;
        }
      // Loop over the six velocity components
      for(unsigned i=0;i<6;i++)
       {
        // Get the value
        const double u_value = this->raw_nodal_value(l,u_nodal_index[i]);
        // Add contribution
        interpolated_u[i] += u_value*psif_;
        // Add contribution to dudt
        dudt[i] += du_dt_linearised_axi_nst(l,i)*psif_;
        // Loop over two coordinate directions (for derivatives)
        for(unsigned j=0;j<2;j++)
         {
          interpolated_dudx(i,j) += u_value*dpsifdx(l,j);
         }
       }
      } // End of loop over the element's nodes
     // Get the mesh velocity if ALE is enabled
     if(!ALE_is_disabled)
      {
       // Loop over the element's nodes
       for(unsigned l=0;l<n_node;l++)
        {
         // Loop over the two coordinate directions
         for(unsigned i=0;i<2;i++)
          {
           mesh_velocity[i] += this->raw_dnodal_position_dt(l,i)*psif(l);
          }
        }
      }
     // Get velocities and their derivatives from base flow problem
     // -----------------------------------------------------------
     // Allocate storage for the velocity components of the base state
     // solution (initialise to zero)
     Vector<double> base_flow_u(3,0.0);
     // Get the user-defined base state solution velocity components
     get_base_flow_u(time,ipt,interpolated_x,base_flow_u);
     // Allocate storage for the derivatives of the base state solution's
     // velocity components w.r.t. global coordinate (r and z)
     // N.B. the derivatives of the base flow components w.r.t. the
     // azimuthal coordinate direction (theta) are always zero since the
     // base flow is axisymmetric
     DenseMatrix<double> base_flow_dudx(3,2,0.0);
     // Get the derivatives of the user-defined base state solution
     // velocity components w.r.t. global coordinates
     get_base_flow_dudx(time,ipt,interpolated_x,base_flow_dudx);
     // Cache base flow velocities and their derivatives
     const double interpolated_ur = base_flow_u[0];
     const double interpolated_uz = base_flow_u[1];
     const double interpolated_utheta = base_flow_u[2];
     const double interpolated_durdr = base_flow_dudx(0,0);
     const double interpolated_durdz = base_flow_dudx(0,1);
     const double interpolated_duzdr = base_flow_dudx(1,0);
     const double interpolated_duzdz = base_flow_dudx(1,1);
     const double interpolated_duthetadr = base_flow_dudx(2,0);
     const double interpolated_duthetadz = base_flow_dudx(2,1);
     // Cache r-component of position
     const double r = interpolated_x[0];
     // Cache unknowns
     const double interpolated_UC = interpolated_u[0];
     const double interpolated_US = interpolated_u[1];
     const double interpolated_WC = interpolated_u[2];
     const double interpolated_WS = interpolated_u[3];
     const double interpolated_VC = interpolated_u[4];
     const double interpolated_VS = interpolated_u[5];
     const double interpolated_PC = interpolated_p[0];
     const double interpolated_PS = interpolated_p[1];
     // Cache derivatives of the unknowns
     const double interpolated_dUCdr = interpolated_dudx(0,0);
     const double interpolated_dUCdz = interpolated_dudx(0,1);
     const double interpolated_dUSdr = interpolated_dudx(1,0);
     const double interpolated_dUSdz = interpolated_dudx(1,1);
     const double interpolated_dWCdr = interpolated_dudx(2,0);
     const double interpolated_dWCdz = interpolated_dudx(2,1);
     const double interpolated_dWSdr = interpolated_dudx(3,0);
     const double interpolated_dWSdz = interpolated_dudx(3,1);
     const double interpolated_dVCdr = interpolated_dudx(4,0);
     const double interpolated_dVCdz = interpolated_dudx(4,1);
     const double interpolated_dVSdr = interpolated_dudx(5,0);
     const double interpolated_dVSdz = interpolated_dudx(5,1);
     // ==================
     // MOMENTUM EQUATIONS
     // ==================
     // Loop over the test functions
     for(unsigned l=0;l<n_node;l++)
      {
       // Cache test functions and their derivatives
       const double testf_ = testf(l);
       const double dtestfdr = dtestfdx(l,0);
       const double dtestfdz = dtestfdx(l,1);
       // ---------------------------------------------
       // FIRST (RADIAL) MOMENTUM EQUATION: COSINE PART
       // ---------------------------------------------
       // Get local equation number of first velocity value at this node
       local_eqn = nodal_local_eqn(l,u_nodal_index[0]);
       // If it's not a boundary condition
       if(local_eqn >= 0)
        {
         // Pressure gradient term
         residuals[local_eqn] += interpolated_PC*(testf_ + r*dtestfdr)*W;
         // Stress tensor terms
         residuals[local_eqn] -= visc_ratio*
          r*(1.0+Gamma[0])*interpolated_dUCdr*dtestfdr*W;
         residuals[local_eqn] -= visc_ratio*r*
          (interpolated_dUCdz + Gamma[0]*interpolated_dWCdr)*
          dtestfdz*W;
         residuals[local_eqn] += visc_ratio*(
      (k*Gamma[0]*interpolated_dVSdr)
          - (k*(2.0+Gamma[0])*interpolated_VS/r)
          - ((1.0+Gamma[0]+(k*k))*interpolated_UC/r))*testf_*W;
         // Inertial terms (du/dt)
         residuals[local_eqn] -= scaled_re_st*r*dudt[0]*testf_*W;
         // Inertial terms (convective)
         residuals[local_eqn] -=
          scaled_re*(r*interpolated_ur*interpolated_dUCdr
                     + r*interpolated_durdr*interpolated_UC
                     + k*interpolated_utheta*interpolated_US
                     - 2*interpolated_utheta*interpolated_VC
                     + r*interpolated_uz*interpolated_dUCdz
                     + r*interpolated_durdz*interpolated_WC)*testf_*W;
         // Mesh velocity terms
         if(!ALE_is_disabled)
          {
           for(unsigned j=0;j<2;j++)
            {
             residuals[local_eqn] +=
              scaled_re_st*r*mesh_velocity[j]
              *interpolated_dudx(0,j)*testf_*W;
            }
          }
         // Calculate the Jacobian
         // ----------------------
         if(flag)
          {
           // Loop over the velocity shape functions again
           for(unsigned l2=0;l2<n_node;l2++)
            {
             // Cache velocity shape functions and their derivatives
             const double psif_ = psif[l2];
             const double dpsifdr = dpsifdx(l2,0);
             const double dpsifdz = dpsifdx(l2,1);
             // Radial velocity component (cosine part) U_k^C
             local_unknown = nodal_local_eqn(l2,u_nodal_index[0]);
             if(local_unknown >= 0)
              {
               if(flag==2)
                {
                 // Add the mass matrix
                 mass_matrix(local_eqn,local_unknown) +=
                  scaled_re_st*r*psif_*testf_*W;
                }
               // Add contributions to the Jacobian matrix
               // Stress tensor terms
               jacobian(local_eqn,local_unknown)
                -= visc_ratio*r*(1.0+Gamma[0])*dpsifdr*dtestfdr*W;
               jacobian(local_eqn,local_unknown)
                -= visc_ratio*r*dpsifdz*dtestfdz*W;
               jacobian(local_eqn,local_unknown)
         -= visc_ratio*(1.0+Gamma[0]+(k*k))*psif_*testf_*W/r;
               // Inertial terms (du/dt)
               jacobian(local_eqn,local_unknown) -=
                scaled_re_st*r*node_pt(l2)->time_stepper_pt()->weight(1,0)*
                psif_*testf_*W;
               // Inertial terms (convective)
               jacobian(local_eqn,local_unknown) -=
                scaled_re*r*(psif_*interpolated_durdr
                             + interpolated_ur*dpsifdr
                             + interpolated_uz*dpsifdz)*testf_*W;
               // Mesh velocity terms
               if(!ALE_is_disabled)
                {
                 for(unsigned j=0;j<2;j++)
                  {
                   jacobian(local_eqn,local_unknown) +=
                    scaled_re_st*r*mesh_velocity[j]
                    *dpsifdx(l2,j)*testf_*W;
                  }
                }
              }
             // Radial velocity component (sine part) U_k^S
             local_unknown = nodal_local_eqn(l2,u_nodal_index[1]);
             if(local_unknown >= 0)
              {
               // Convective term
               jacobian(local_eqn,local_unknown) -=
                scaled_re*k*interpolated_utheta*psif_*testf_*W;
              }
             // Axial velocity component (cosine part) W_k^C
             local_unknown = nodal_local_eqn(l2,u_nodal_index[2]);
             if(local_unknown >= 0)
              {
               // Stress tensor term
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*Gamma[0]*r*dpsifdr*dtestfdz*W;
               // Convective term
               jacobian(local_eqn,local_unknown) -=
                scaled_re*r*interpolated_durdz*psif_*testf_*W;
              }
             // Axial velocity component (sine part) W_k^S
             // has no contribution
             // Azimuthal velocity component (cosine part) V_k^C
             local_unknown = nodal_local_eqn(l2,u_nodal_index[4]);
             if(local_unknown >= 0)
              {
               // Convective term
               jacobian(local_eqn,local_unknown) +=
                scaled_re*2*interpolated_utheta*psif_*testf_*W;
              }
             // Azimuthal velocity component (sine part) V_k^S
             local_unknown = nodal_local_eqn(l2,u_nodal_index[5]);
             if(local_unknown >= 0)
              {
               // Stress tensor term
               jacobian(local_eqn,local_unknown) += visc_ratio*(
            (Gamma[0]*k*dpsifdr) - (k*(2.0+Gamma[0])*psif_/r))*testf_*W;
              }
            } // End of loop over velocity shape functions
           // Now loop over pressure shape functions
           // (This is the contribution from pressure gradient)
           for(unsigned l2=0;l2<n_pres;l2++)
            {
             // Cosine part P_k^C
             local_unknown = p_local_eqn(l2,0);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) +=
                psip[l2]*(testf_ + r*dtestfdr)*W;
              }
             // Sine part P_k^S has no contribution
            } // End of loop over pressure shape functions
          } // End of Jacobian calculation
        } // End of if not boundary condition statement
       // --------------------------------------------
       // SECOND (RADIAL) MOMENTUM EQUATION: SINE PART
       // --------------------------------------------
       // Get local equation number of second velocity value at this node
       local_eqn = nodal_local_eqn(l,u_nodal_index[1]);
       // If it's not a boundary condition
       if(local_eqn >= 0)
        {
         // Pressure gradient term
         residuals[local_eqn] += interpolated_PS*(testf_ + r*dtestfdr)*W;
         // Stress tensor terms
         residuals[local_eqn] -= visc_ratio*
          r*(1.0+Gamma[0])*interpolated_dUSdr*dtestfdr*W;
         residuals[local_eqn] -= visc_ratio*r*
          (interpolated_dUSdz + Gamma[0]*interpolated_dWSdr)*
          dtestfdz*W;
         residuals[local_eqn] -= visc_ratio*(
      (k*Gamma[0]*interpolated_dVCdr)
          - (k*(2.0+Gamma[0])*interpolated_VC/r)
          + ((1.0+Gamma[0]+(k*k))*interpolated_US/r))*testf_*W;
         // Inertial terms (du/dt)
         residuals[local_eqn] -= scaled_re_st*r*dudt[1]*testf_*W;
         // Inertial terms (convective)
         residuals[local_eqn] -=
          scaled_re*(r*interpolated_ur*interpolated_dUSdr
                     + r*interpolated_durdr*interpolated_US
                     - k*interpolated_utheta*interpolated_UC
                     - 2*interpolated_utheta*interpolated_VS
                     + r*interpolated_uz*interpolated_dUSdz
                     + r*interpolated_durdz*interpolated_WS)*testf_*W;
         // Mesh velocity terms
         if(!ALE_is_disabled)
          {
           for(unsigned j=0;j<2;j++)
            {
             residuals[local_eqn] +=
              scaled_re_st*r*mesh_velocity[j]
              *interpolated_dudx(1,j)*testf_*W;
            }
          }
         // Calculate the Jacobian
         // ----------------------
         if(flag)
          {
           // Loop over the velocity shape functions again
           for(unsigned l2=0;l2<n_node;l2++)
            {
             // Cache velocity shape functions and their derivatives
             const double psif_ = psif[l2];
             const double dpsifdr = dpsifdx(l2,0);
             const double dpsifdz = dpsifdx(l2,1);
             // Radial velocity component (cosine part) U_k^C
             local_unknown = nodal_local_eqn(l2,u_nodal_index[0]);
             if(local_unknown >= 0)
              {
               // Convective term
               jacobian(local_eqn,local_unknown) +=
                scaled_re*k*interpolated_utheta*psif_*testf_*W;
              }
             // Radial velocity component (sine part) U_k^S
             local_unknown = nodal_local_eqn(l2,u_nodal_index[1]);
             if(local_unknown >= 0)
              {
               if(flag==2)
                {
                 // Add the mass matrix
                 mass_matrix(local_eqn,local_unknown) +=
                  scaled_re_st*r*psif_*testf_*W;
                }
               // Add contributions to the Jacobian matrix
               // Stress tensor terms
               jacobian(local_eqn,local_unknown)
                -= visc_ratio*r*(1.0+Gamma[0])*dpsifdr*dtestfdr*W;
               jacobian(local_eqn,local_unknown)
                -= visc_ratio*r*dpsifdz*dtestfdz*W;
               jacobian(local_eqn,local_unknown)
         -= visc_ratio*(1.0+Gamma[0]+(k*k))*psif_*testf_*W/r;
               // Inertial terms (du/dt)
               jacobian(local_eqn,local_unknown)
                -= scaled_re_st*r*node_pt(l2)->time_stepper_pt()->weight(1,0)*
                psif_*testf_*W;
               // Inertial terms (convective)
               jacobian(local_eqn,local_unknown) -=
                scaled_re*r*(psif_*interpolated_durdr
                             + interpolated_ur*dpsifdr
                             + interpolated_uz*dpsifdz)*testf_*W;
               // Mesh velocity terms
               if(!ALE_is_disabled)
                {
                 for(unsigned j=0;j<2;j++)
                  {
                   jacobian(local_eqn,local_unknown) +=
                    scaled_re_st*r*mesh_velocity[j]
                    *dpsifdx(l2,j)*testf_*W;
                  }
                }
              }
             // Axial velocity component (cosine part) W_k^C
             // has no contribution
             // Axial velocity component (sine part) W_k^S
             local_unknown = nodal_local_eqn(l2,u_nodal_index[3]);
             if(local_unknown >= 0)
              {
               // Stress tensor term
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*Gamma[0]*r*dpsifdr*dtestfdz*W;
               // Convective term
               jacobian(local_eqn,local_unknown) -=
                scaled_re*r*interpolated_durdz*psif_*testf_*W;
              }
             // Azimuthal velocity component (cosine part) V_k^C
             local_unknown = nodal_local_eqn(l2,u_nodal_index[4]);
             if(local_unknown >= 0)
              {
               // Stress tensor terms
           jacobian(local_eqn,local_unknown) -= visc_ratio*(
            (Gamma[0]*k*dpsifdr)
                - (k*(2.0+Gamma[0])*psif_/r))*testf_*W;
              }
             // Azimuthal velocity component (sine part) V_k^S
             local_unknown = nodal_local_eqn(l2,u_nodal_index[5]);
             if(local_unknown >= 0)
              {
               // Convective term
               jacobian(local_eqn,local_unknown) +=
                scaled_re*2*interpolated_utheta*psif_*testf_*W;
              }
            } // End of loop over velocity shape functions
           // Now loop over pressure shape functions
           // (This is the contribution from pressure gradient)
           for(unsigned l2=0;l2<n_pres;l2++)
            {
             // Cosine part P_k^C has no contribution
             // Sine part P_k^S
             local_unknown = p_local_eqn(l2,1);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown)
                += psip[l2]*(testf_ + r*dtestfdr)*W;
              }
            } // End of loop over pressure shape functions
          } // End of Jacobian calculation
        } // End of if not boundary condition statement
       // --------------------------------------------
       // THIRD (AXIAL) MOMENTUM EQUATION: COSINE PART
       // --------------------------------------------
       // Get local equation number of third velocity value at this node
       local_eqn = nodal_local_eqn(l,u_nodal_index[2]);
       // If it's not a boundary condition
       if(local_eqn >= 0)
        {
         // Pressure gradient term
         residuals[local_eqn]  += r*interpolated_PC*dtestfdz*W;
         // Stress tensor terms
         residuals[local_eqn] -= visc_ratio*r*
          (interpolated_dWCdr + Gamma[1]*interpolated_dUCdz)
          *dtestfdr*W;
         residuals[local_eqn] -= visc_ratio*r*
          (1.0 + Gamma[1])*interpolated_dWCdz*dtestfdz*W;
         residuals[local_eqn] += visc_ratio*k*
          (Gamma[1]*interpolated_dVSdz - k*interpolated_WC/r)*testf_*W;
         // Inertial terms (du/dt)
         residuals[local_eqn] -= scaled_re_st*r*dudt[2]*testf_*W;
         // Inertial terms (convective)
         residuals[local_eqn] -=
          scaled_re*(r*interpolated_ur*interpolated_dWCdr
                     + r*interpolated_duzdr*interpolated_UC
                     + k*interpolated_utheta*interpolated_WS
                     + r*interpolated_uz*interpolated_dWCdz
                     + r*interpolated_duzdz*interpolated_WC)*testf_*W;
         // Mesh velocity terms
         if(!ALE_is_disabled)
          {
           for(unsigned j=0;j<2;j++)
            {
             residuals[local_eqn] +=
              scaled_re_st*r*mesh_velocity[j]
              *interpolated_dudx(2,j)*testf_*W;
            }
          }
         // Calculate the Jacobian
         // ----------------------
         if(flag)
          {
           // Loop over the velocity shape functions again
           for(unsigned l2=0;l2<n_node;l2++)
            {
             // Cache velocity shape functions and their derivatives
             const double psif_ = psif[l2];
             const double dpsifdr = dpsifdx(l2,0);
             const double dpsifdz = dpsifdx(l2,1);
             // Radial velocity component (cosine part) U_k^C
             local_unknown = nodal_local_eqn(l2,u_nodal_index[0]);
             if(local_unknown >= 0)
              {
               // Stress tensor term
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*r*Gamma[1]*dpsifdz*dtestfdr*W;
               // Convective term
               jacobian(local_eqn,local_unknown) -=
                scaled_re*r*psif_*interpolated_duzdr*testf_*W;
              }
             // Radial velocity component (sine part) U_k^S
             // has no contribution
             // Axial velocity component (cosine part) W_k^C
             local_unknown = nodal_local_eqn(l2,u_nodal_index[2]);
             if(local_unknown >= 0)
              {
               if(flag==2)
                {
                 // Add the mass matrix
                 mass_matrix(local_eqn,local_unknown) +=
                  scaled_re_st*r*psif_*testf_*W;
                }
               // Add contributions to the Jacobian matrix
               // Stress tensor terms
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*r*dpsifdr*dtestfdr*W;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*r*(1.0+Gamma[1])*dpsifdz*dtestfdz*W;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*k*k*psif_*testf_*W/r;
               // Inertial terms (du/dt)
               jacobian(local_eqn,local_unknown) -=
                scaled_re_st*r*node_pt(l2)->time_stepper_pt()->weight(1,0)*
                psif_*testf_*W;
               // Inertial terms (convective)
               jacobian(local_eqn,local_unknown) -=
                scaled_re*r*(interpolated_ur*dpsifdr
                             + psif_*interpolated_duzdz
                             + interpolated_uz*dpsifdz)*testf_*W;
               // Mesh velocity terms
               if(!ALE_is_disabled)
                {
                 for(unsigned j=0;j<2;j++)
                  {
                   jacobian(local_eqn,local_unknown) +=
                    scaled_re_st*r*mesh_velocity[j]
                    *dpsifdx(l2,j)*testf_*W;
                  }
                }
              }
             // Axial velocity component (sine part) W_k^S
             local_unknown = nodal_local_eqn(l2,u_nodal_index[3]);
             if(local_unknown >= 0)
              {
               // Convective term
               jacobian(local_eqn,local_unknown) -=
                scaled_re*k*interpolated_utheta*psif_*testf_*W;
              }
             // Azimuthal velocity component (cosine part) V_k^C
             // has no contribution
             // Azimuthal velocity component (sine part) V_k^S
             local_unknown = nodal_local_eqn(l2,u_nodal_index[5]);
             if(local_unknown >= 0)
              {
               // Stress tensor term
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*Gamma[1]*k*dpsifdz*testf_*W;
              }
            } // End of loop over velocity shape functions
           // Now loop over pressure shape functions
           // (This is the contribution from pressure gradient)
           for(unsigned l2=0;l2<n_pres;l2++)
            {
             // Cosine part P_k^C
             local_unknown = p_local_eqn(l2,0);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) +=
                r*psip[l2]*dtestfdz*W;
              }
             // Sine part P_k^S has no contribution
            } // End of loop over pressure shape functions
          } // End of Jacobian calculation
        } // End of if not boundary condition statement
       // -------------------------------------------
       // FOURTH (AXIAL) MOMENTUM EQUATION: SINE PART
       // -------------------------------------------
       // Get local equation number of fourth velocity value at this node
       local_eqn = nodal_local_eqn(l,u_nodal_index[3]);
       // If it's not a boundary condition
       if(local_eqn >= 0)
        {
         // Pressure gradient term
         residuals[local_eqn]  += r*interpolated_PS*dtestfdz*W;
         // Stress tensor terms
         residuals[local_eqn] -= visc_ratio*r*
          (interpolated_dWSdr + Gamma[1]*interpolated_dUSdz)
          *dtestfdr*W;
         residuals[local_eqn] -= visc_ratio*r*
          (1.0+Gamma[1])*interpolated_dWSdz*dtestfdz*W;
         residuals[local_eqn] -= visc_ratio*k*
          (Gamma[1]*interpolated_dVCdz + k*interpolated_WS/r)*testf_*W;
         // Inertial terms (du/dt)
         residuals[local_eqn] -= scaled_re_st*r*dudt[3]*testf_*W;
         // Inertial terms (convective)
         residuals[local_eqn] -=
          scaled_re*(r*interpolated_ur*interpolated_dWSdr
                     + r*interpolated_duzdr*interpolated_US
                     - k*interpolated_utheta*interpolated_WC
                     + r*interpolated_uz*interpolated_dWSdz
                     + r*interpolated_duzdz*interpolated_WS)*testf_*W;
         // Mesh velocity terms
         if(!ALE_is_disabled)
          {
           for(unsigned j=0;j<2;j++)
            {
             residuals[local_eqn] +=
              scaled_re_st*r*mesh_velocity[j]
              *interpolated_dudx(3,j)*testf_*W;
            }
          }
         // Calculate the Jacobian
         // ----------------------
         if(flag)
          {
           // Loop over the velocity shape functions again
           for(unsigned l2=0;l2<n_node;l2++)
            {
             // Cache velocity shape functions and their derivatives
             const double psif_ = psif[l2];
             const double dpsifdr = dpsifdx(l2,0);
             const double dpsifdz = dpsifdx(l2,1);
             // Radial velocity component (cosine part) U_k^C
             // has no contribution
             // Radial velocity component (sine part) U_k^S
             local_unknown = nodal_local_eqn(l2,u_nodal_index[1]);
             if(local_unknown >= 0)
              {
               // Stress tensor term
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*r*Gamma[1]*dpsifdz*dtestfdr*W;
               // Convective term
               jacobian(local_eqn,local_unknown) -=
                scaled_re*r*psif_*interpolated_duzdr*testf_*W;
              }
             // Axial velocity component (cosine part) W_k^S
             local_unknown = nodal_local_eqn(l2,u_nodal_index[2]);
             if(local_unknown >= 0)
              {
               // Convective term
               jacobian(local_eqn,local_unknown) +=
                scaled_re*k*interpolated_utheta*psif_*testf_*W;
              }
             // Axial velocity component (sine part) W_k^S
             local_unknown = nodal_local_eqn(l2,u_nodal_index[3]);
             if(local_unknown >= 0)
              {
               if(flag==2)
                {
                 // Add the mass matrix
                 mass_matrix(local_eqn,local_unknown) +=
                  scaled_re_st*r*psif_*testf_*W;
                }
               // Add contributions to the Jacobian matrix
               // Stress tensor terms
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*r*dpsifdr*dtestfdr*W;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*r*(1.0+Gamma[1])*dpsifdz*dtestfdz*W;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*k*k*psif_*testf_*W/r;
               // Inertial terms (du/dt)
               jacobian(local_eqn,local_unknown) -=
                scaled_re_st*r*node_pt(l2)->time_stepper_pt()->weight(1,0)*
                psif_*testf_*W;
               // Inertial terms (convective)
               jacobian(local_eqn,local_unknown) -=
                scaled_re*r*(interpolated_ur*dpsifdr
                             + psif_*interpolated_duzdz
                             + interpolated_uz*dpsifdz)*testf_*W;
               // Mesh velocity terms
               if(!ALE_is_disabled)
                {
                 for(unsigned j=0;j<2;j++)
                  {
                   jacobian(local_eqn,local_unknown) +=
                    scaled_re_st*r*mesh_velocity[j]
                    *dpsifdx(l2,j)*testf_*W;
                  }
                }
              }
             // Azimuthal velocity component (cosine part) V_k^C
             local_unknown = nodal_local_eqn(l2,u_nodal_index[4]);
             if(local_unknown >= 0)
              {
               // Stress tensor term
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*Gamma[1]*k*dpsifdz*testf_*W;
              }
             // Azimuthal velocity component (sine part) V_k^S
             // has no contribution
            } // End of loop over velocity shape functions
           // Now loop over pressure shape functions
           // (This is the contribution from pressure gradient)
           for(unsigned l2=0;l2<n_pres;l2++)
            {
             // Cosine part P_k^C has no contribution
             // Sine part P_k^S
             local_unknown = p_local_eqn(l2,1);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) +=
                r*psip[l2]*dtestfdz*W;
              }
            } // End of loop over pressure shape functions
          } // End of Jacobian calculation
        } // End of if not boundary condition statement
       // ------------------------------------------------
       // FIFTH (AZIMUTHAL) MOMENTUM EQUATION: COSINE PART
       // ------------------------------------------------
       // Get local equation number of fifth velocity value at this node
       local_eqn = nodal_local_eqn(l,u_nodal_index[4]);
       // If it's not a boundary condition
       if(local_eqn >= 0)
        {
         // Pressure gradient term
         residuals[local_eqn] -= k*interpolated_PS*testf_*W;
         // Stress tensor terms
         residuals[local_eqn] += visc_ratio*
          (-r*interpolated_dVCdr
           - k*Gamma[0]*interpolated_US
           + Gamma[0]*interpolated_VC)*dtestfdr*W;
         residuals[local_eqn] -= visc_ratio*
          (k*Gamma[0]*interpolated_WS + r*interpolated_dVCdz)*dtestfdz*W;
         residuals[local_eqn] += visc_ratio*
          (Gamma[0]*interpolated_dVCdr
           + k*(2.0+Gamma[0])*interpolated_US/r
           - (1.0+(k*k)+(k*k*Gamma[0]))*interpolated_VC/r)*testf_*W;
         // Inertial terms (du/dt)
         residuals[local_eqn] -= scaled_re_st*r*dudt[4]*testf_*W;
         // Inertial terms (convective)
         residuals[local_eqn] -=
          scaled_re*(r*interpolated_ur*interpolated_dVCdr
                     + r*interpolated_duthetadr*interpolated_UC
                     + k*interpolated_utheta*interpolated_VS
                     + interpolated_utheta*interpolated_UC
                     + interpolated_ur*interpolated_VC
                     + r*interpolated_uz*interpolated_dVCdz
                     + r*interpolated_duthetadz*interpolated_WC)*testf_*W;
         // Mesh velocity terms
         if(!ALE_is_disabled)
          {
           for(unsigned j=0;j<2;j++)
            {
             residuals[local_eqn] +=
              scaled_re_st*r*mesh_velocity[j]
              *interpolated_dudx(4,j)*testf_*W;
            }
          }
         // Calculate the Jacobian
         // ----------------------
         if(flag)
          {
           // Loop over the velocity shape functions again
           for(unsigned l2=0;l2<n_node;l2++)
            {
             // Cache velocity shape functions and their derivatives
             const double psif_ = psif[l2];
             const double dpsifdr = dpsifdx(l2,0);
             const double dpsifdz = dpsifdx(l2,1);
             // Radial velocity component (cosine part) U_k^C
             local_unknown = nodal_local_eqn(l2,u_nodal_index[0]);
             if(local_unknown >= 0)
              {
               // Convective terms
               jacobian(local_eqn,local_unknown) -=
                scaled_re*(r*interpolated_duthetadr
                           + interpolated_utheta)*psif_*testf_*W;
              }
             // Radial velocity component (sine part) U_k^S
             local_unknown = nodal_local_eqn(l2,u_nodal_index[1]);
             if(local_unknown >= 0)
              {
               // Stress tensor terms
               jacobian(local_eqn,local_unknown) += visc_ratio*k*psif_*(
            ((2.0+Gamma[0])*testf_/r) - (Gamma[0]*dtestfdr))*W;
              }
             // Axial velocity component (cosine part) W_k^C
             local_unknown = nodal_local_eqn(l2,u_nodal_index[2]);
             if(local_unknown >= 0)
              {
               // Convective term
               jacobian(local_eqn,local_unknown) -=
                scaled_re*r*psif_*interpolated_duthetadz*testf_*W;
              }
             // Axial velocity component (sine part) W_k^S
             local_unknown = nodal_local_eqn(l2,u_nodal_index[3]);
             if(local_unknown >= 0)
              {
               // Stress tensor term
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*k*Gamma[0]*psif_*dtestfdz*W;
              }
             // Azimuthal velocity component (cosine part) V_k^C
             local_unknown = nodal_local_eqn(l2,u_nodal_index[4]);
             if(local_unknown >= 0)
              {
               if(flag==2)
                {
                 // Add the mass matrix
                 mass_matrix(local_eqn,local_unknown) +=
                  scaled_re_st*r*psif_*testf_*W;
                }
               // Add contributions to the Jacobian matrix
               // Stress tensor terms
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*(Gamma[0]*psif_ - r*dpsifdr)*dtestfdr*W;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*r*dpsifdz*dtestfdz*W;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*(Gamma[0]*dpsifdr
                            - (1.0+(k*k)+(k*k*Gamma[0]))*psif_/r)*testf_*W;
               // Inertial terms (du/dt)
               jacobian(local_eqn,local_unknown) -=
                scaled_re_st*r*node_pt(l2)->time_stepper_pt()->weight(1,0)*
                psif_*testf_*W;
               // Inertial terms (convective)
               jacobian(local_eqn,local_unknown) -=
                scaled_re*(r*interpolated_ur*dpsifdr
                           + interpolated_ur*psif_
                           + r*interpolated_uz*dpsifdz)*testf_*W;
               // Mesh velocity terms
               if(!ALE_is_disabled)
                {
                 for(unsigned j=0;j<2;j++)
                  {
                   jacobian(local_eqn,local_unknown) +=
                    scaled_re_st*r*mesh_velocity[j]
                    *dpsifdx(l2,j)*testf_*W;
                  }
                }
              }
             // Azimuthal velocity component (sine part) V_k^S
             local_unknown = nodal_local_eqn(l2,u_nodal_index[5]);
             if(local_unknown >= 0)
              {
               // Convective term
               jacobian(local_eqn,local_unknown) -=
                scaled_re*k*interpolated_utheta*psif_*testf_*W;
              }
            } // End of loop over velocity shape functions
           // Now loop over pressure shape functions
           // (This is the contribution from pressure gradient)
           for(unsigned l2=0;l2<n_pres;l2++)
            {
             // Cosine part P_k^C has no contribution
             // Sine part P_k^S
             local_unknown = p_local_eqn(l2,1);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) -=
                k*psip[l2]*testf_*W;
              }
            } // End of loop over pressure shape functions
          } // End of Jacobian calculation
        } // End of if not boundary condition statement
       // ----------------------------------------------
       // SIXTH (AZIMUTHAL) MOMENTUM EQUATION: SINE PART
       // ----------------------------------------------
       // Get local equation number of sixth velocity value at this node
       local_eqn = nodal_local_eqn(l,u_nodal_index[5]);
       // If it's not a boundary condition
       if(local_eqn >= 0)
        {
         // Pressure gradient term
         residuals[local_eqn] += k*interpolated_PC*testf_*W;
         // Stress tensor terms
         residuals[local_eqn] += visc_ratio*
          (-r*interpolated_dVSdr
           + k*Gamma[0]*interpolated_UC
           + Gamma[0]*interpolated_VS)*dtestfdr*W;
         residuals[local_eqn] += visc_ratio*
          (k*Gamma[0]*interpolated_WC - r*interpolated_dVSdz)*dtestfdz*W;
         residuals[local_eqn] += visc_ratio*
          (Gamma[0]*interpolated_dVSdr
           - k*(2.0+Gamma[0])*interpolated_UC/r
           - (1.0+(k*k)+(k*k*Gamma[0]))*interpolated_VS/r)*testf_*W;
         // Inertial terms (du/dt)
         residuals[local_eqn] -= scaled_re_st*r*dudt[5]*testf_*W;
         // Inertial terms (convective)
         residuals[local_eqn] -=
          scaled_re*(r*interpolated_ur*interpolated_dVSdr
                     + r*interpolated_duthetadr*interpolated_US
                     - k*interpolated_utheta*interpolated_VC
                     + interpolated_utheta*interpolated_US
                     + interpolated_ur*interpolated_VS
                     + r*interpolated_uz*interpolated_dVSdz
                     + r*interpolated_duthetadz*interpolated_WS)*testf_*W;
         // Mesh velocity terms
         if(!ALE_is_disabled)
          {
           for(unsigned j=0;j<2;j++)
            {
             residuals[local_eqn] +=
              scaled_re_st*r*mesh_velocity[j]
              *interpolated_dudx(5,j)*testf_*W;
            }
          }
         // Calculate the Jacobian
         // ----------------------
         if(flag)
          {
           // Loop over the velocity shape functions again
           for(unsigned l2=0;l2<n_node;l2++)
            {
             // Cache velocity shape functions and their derivatives
             const double psif_ = psif[l2];
             const double dpsifdr = dpsifdx(l2,0);
             const double dpsifdz = dpsifdx(l2,1);
             // Radial velocity component (cosine part) U_k^C
             local_unknown = nodal_local_eqn(l2,u_nodal_index[0]);
             if(local_unknown >= 0)
              {
               // Stress tensor terms
               jacobian(local_eqn,local_unknown) += visc_ratio*k*psif_*(
            (Gamma[0]*dtestfdr) - ((2.0+Gamma[0])*testf_/r))*W;
              }
             // Radial velocity component (sine part) U_k^S
             local_unknown = nodal_local_eqn(l2,u_nodal_index[1]);
             if(local_unknown >= 0)
              {
               // Convective terms
               jacobian(local_eqn,local_unknown) -=
                scaled_re*(r*interpolated_duthetadr
                           + interpolated_utheta)*psif_*testf_*W;
              }
             // Axial velocity component (cosine part) W_k^C
             local_unknown = nodal_local_eqn(l2,u_nodal_index[2]);
             if(local_unknown >= 0)
              {
               // Stress tensor term
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*k*Gamma[0]*psif_*dtestfdz*W;
              }
             // Axial velocity component (sine part) W_k^S
             local_unknown = nodal_local_eqn(l2,u_nodal_index[3]);
             if(local_unknown >= 0)
              {
               // Convective term
               jacobian(local_eqn,local_unknown) -=
                scaled_re*r*psif_*interpolated_duthetadz*testf_*W;
              }
             // Azimuthal velocity component (cosine part) V_k^C
             local_unknown = nodal_local_eqn(l2,u_nodal_index[4]);
             if(local_unknown >= 0)
              {
               // Convective term
               jacobian(local_eqn,local_unknown) +=
                scaled_re*k*interpolated_utheta*psif_*testf_*W;
              }
             // Azimuthal velocity component (sine part) V_k^S
             local_unknown = nodal_local_eqn(l2,u_nodal_index[5]);
             if(local_unknown >= 0)
              {
               if(flag==2)
                {
                 // Add the mass matrix
                 mass_matrix(local_eqn,local_unknown) +=
                  scaled_re_st*r*psif_*testf_*W;
                }
               // Add contributions to the Jacobian matrix
               // Stress tensor terms
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*(Gamma[0]*psif_ - r*dpsifdr)*dtestfdr*W;
               jacobian(local_eqn,local_unknown) -=
                visc_ratio*r*dpsifdz*dtestfdz*W;
               jacobian(local_eqn,local_unknown) +=
                visc_ratio*(Gamma[0]*dpsifdr
                            - (1.0+(k*k)+(k*k*Gamma[0]))*psif_/r)*testf_*W;
               // Inertial terms (du/dt)
               jacobian(local_eqn,local_unknown) -=
                scaled_re_st*r*node_pt(l2)->time_stepper_pt()->weight(1,0)*
                psif_*testf_*W;
               // Convective terms
               jacobian(local_eqn,local_unknown) -=
                scaled_re*(r*interpolated_ur*dpsifdr
                           + interpolated_ur*psif_
                           + r*interpolated_uz*dpsifdz)*testf_*W;
               // Mesh velocity terms
               if(!ALE_is_disabled)
                {
                 for(unsigned j=0;j<2;j++)
                  {
                   jacobian(local_eqn,local_unknown) +=
                    scaled_re_st*r*mesh_velocity[j]
                    *dpsifdx(l2,j)*testf_*W;
                  }
                }
              }
            } // End of loop over velocity shape functions
           // Now loop over pressure shape functions
           // (This is the contribution from pressure gradient)
           for(unsigned l2=0;l2<n_pres;l2++)
            {
             // Cosine part P_k^C
             local_unknown = p_local_eqn(l2,0);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) +=
                k*psip[l2]*testf_*W;
              }
             // Sine part P_k^S has no contribution
            } // End of loop over pressure shape functions
          } // End of Jacobian calculation
        } // End of if not boundary condition statement
      } // End of loop over shape functions
     // ====================
     // CONTINUITY EQUATIONS
     // ====================
     // Loop over the pressure shape functions
     for(unsigned l=0;l<n_pres;l++)
      {
       // Cache test function
       const double testp_ = testp[l];
       // --------------------------------------
       // FIRST CONTINUITY EQUATION: COSINE PART
       // --------------------------------------
       // Get local equation number of first pressure value at this node
       local_eqn = p_local_eqn(l,0);
       // If it's not a boundary condition
       if(local_eqn >= 0)
        {
         // Gradient terms
         residuals[local_eqn] +=
          (interpolated_UC + r*interpolated_dUCdr
           + k*interpolated_VS + r*interpolated_dWCdz)*testp_*W;
         // Calculate the Jacobian
         // ----------------------
         if(flag)
          {
           // Loop over the velocity shape functions
           for(unsigned l2=0;l2<n_node;l2++)
            {
             // Cache velocity shape functions and their derivatives
             const double psif_ = psif[l2];
             const double dpsifdr = dpsifdx(l2,0);
             const double dpsifdz = dpsifdx(l2,1);
             // Radial velocity component (cosine part) U_k^C
             local_unknown = nodal_local_eqn(l2,u_nodal_index[0]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) +=
                (psif_ + r*dpsifdr)*testp_*W;
              }
             // Radial velocity component (sine part) U_k^S
             // has no contribution
             // Axial velocity component (cosine part) W_k^C
             local_unknown = nodal_local_eqn(l2,u_nodal_index[2]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) +=
                r*dpsifdz*testp_*W;
              }
             // Axial velocity component (sine part) W_k^S
             // has no contribution
             // Azimuthal velocity component (cosine part) V_k^C
             // has no contribution
             // Azimuthal velocity component (sine part) V_k^S
             local_unknown = nodal_local_eqn(l2,u_nodal_index[5]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) +=
                k*psif_*testp_*W;
              }
            } // End of loop over velocity shape functions
           // Real and imaginary pressure components, P_k^C and P_k^S,
           // have no contribution
          } // End of Jacobian calculation
        } // End of if not boundary condition statement
       // -------------------------------------
       // SECOND CONTINUITY EQUATION: SINE PART
       // -------------------------------------
       // Get local equation number of second pressure value at this node
       local_eqn = p_local_eqn(l,1);
       // If it's not a boundary condition
       if(local_eqn >= 0)
        {
         // Gradient terms
         residuals[local_eqn] +=
          (interpolated_US + r*interpolated_dUSdr
           - k*interpolated_VC + r*interpolated_dWSdz)*testp_*W;
         // Calculate the Jacobian
         // ----------------------
         if(flag)
          {
           // Loop over the velocity shape functions
           for(unsigned l2=0;l2<n_node;l2++)
            {
             // Cache velocity shape functions and their derivatives
             const double psif_ = psif[l2];
             const double dpsifdr = dpsifdx(l2,0);
             const double dpsifdz = dpsifdx(l2,1);
             // Radial velocity component (cosine part) U_k^C
             // has no contribution
             // Radial velocity component (sine part) U_k^S
             local_unknown = nodal_local_eqn(l2,u_nodal_index[1]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) +=
                (psif_ + r*dpsifdr)*testp_*W;
              }
             // Axial velocity component (cosine part) W_k^C
             // has no contribution
             // Axial velocity component (sine part) W_k^S
             local_unknown = nodal_local_eqn(l2,u_nodal_index[3]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) +=
                r*dpsifdz*testp_*W;
              }
             // Azimuthal velocity component (cosine part) V_k^C
             local_unknown = nodal_local_eqn(l2,u_nodal_index[4]);
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) -=
                k*psif_*testp_*W;
              }
             // Azimuthal velocity component (sine part) V_k^S
             // has no contribution
            } // End of loop over velocity shape functions
           // Real and imaginary pressure components, P_k^C and P_k^S,
           // have no contribution
          } // End of Jacobian calculation
        } // End of if not boundary condition statement
      } // End of loop over pressure shape functions
    } // End of loop over the integration points
  } // End of fill_in_generic_residual_contribution_linearised_axi_nst
References ALE_is_disabled, azimuthal_mode_number(), density_ratio(), dshape_and_dtest_eulerian_at_knot_linearised_axi_nst(), du_dt_linearised_axi_nst(), Gamma, get_base_flow_dudx(), get_base_flow_u(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), J, j, k, oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), npres_linearised_axi_nst(), oomph::Integral::nweight(), p_linearised_axi_nst(), p_local_eqn(), pshape_linearised_axi_nst(), UniformPSDSelfTest::r, oomph::FiniteElement::raw_dnodal_position_dt(), oomph::FiniteElement::raw_nodal_position(), oomph::FiniteElement::raw_nodal_value(), re(), re_st(), s, oomph::Time::time(), oomph::TimeStepper::time_pt(), oomph::Data::time_stepper_pt(), u_index_linearised_axi_nst(), viscosity_ratio(), w, oomph::QuadTreeNames::W, oomph::Integral::weight(), and oomph::TimeStepper::weight().
Referenced by fill_in_contribution_to_jacobian(), fill_in_contribution_to_jacobian_and_mass_matrix(), and fill_in_contribution_to_residuals().
fill_in_generic_residual_contribution_linearised_axi_nst() [2/2]
virtual void oomph::LinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, unsigned flag) protected virtual
Compute the residuals for the Navier-Stokes equations; flag=1(or 0): do (or don't) compute the Jacobian as well.
Reimplemented in oomph::RefineableLinearisedAxisymmetricNavierStokesEquations, and oomph::RefineableLinearisedAxisymmetricNavierStokesEquations.
g()
const Vector<double>& oomph::LinearisedAxisymmetricNavierStokesEquations::g () const inline
Vector of gravitational components.
 {return *G_pt;}
References G_pt.
Referenced by fill_in_generic_residual_contribution_lin_axi_nst().
g_pt()
Vector<double>* & oomph::LinearisedAxisymmetricNavierStokesEquations::g_pt () inline
Pointer to Vector of gravitational components.
 {return G_pt;}
References G_pt.
get_base_flow_d_dudx_dX()
virtual void oomph::LinearisedAxisymmetricNavierStokesEquations::get_base_flow_d_dudx_dX (const double & time, const unsigned & ipt, const Vector< double > & x, RankFourTensor< double > & result) const inline protected virtual
Calculate the derivatives w.r.t. nodal coordinates X_{pq} of the spatial derivatives of the velocity components of the base flow solution at a given time and Eulerian position
   {
    // If the function pointer is zero return zero
    if(Base_flow_d_dudx_dX_fct_pt==0)
     {
      // Determine number of nodes in this element
      const unsigned n_node = nnode();
      // Loop over the element's nodes
      for(unsigned q=0;q<n_node;q++)
       {
        // Loop over the two coordinate directions
        for(unsigned p=0;p<2;p++)
         {
          // Loop over velocity components
          for(unsigned i=0;i<3;i++)
           {
            // Loop over coordinate directions and set to zero
            for(unsigned k=0;k<2;k++) { result(p,q,i,k) = 0.0; }
           }
         }
       }
     }
    // Otherwise call the function
    else
     {
      (*Base_flow_d_dudx_dX_fct_pt)(time,x,result);
     }
   }
References Base_flow_d_dudx_dX_fct_pt, i, k, oomph::FiniteElement::nnode(), p, Eigen::numext::q, and plotDoE::x.
get_base_flow_duds()
virtual void oomph::LinearisedAxisymmetricNavierStokesEquations::get_base_flow_duds (const double & time, const unsigned & ipt, const Vector< double > & x, DenseMatrix< double > & result) const inline protected virtual
Calculate the derivatives of the velocity components of the base flow solution w.r.t. local coordinates (s_1 and s_2) at a given time and Eulerian position
Reimplemented in LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement.
   {
    // If the function pointer is zero return zero
    if(Base_flow_duds_fct_pt==0)
     {
      // Loop over velocity components
      for(unsigned i=0;i<3;i++)
       {
        // Loop over coordinate directions and set to zero
        for(unsigned j=0;j<2;j++) { result(i,j) = 0.0; }
       }
     }
    // Otherwise call the function
    else
     {
      (*Base_flow_duds_fct_pt)(time,x,result);
     }
   }
References Base_flow_duds_fct_pt, i, j, and plotDoE::x.
Referenced by fill_in_generic_residual_contribution_lin_axi_nst().
get_base_flow_dudt()
virtual void oomph::LinearisedAxisymmetricNavierStokesEquations::get_base_flow_dudt (const double & time, const unsigned & ipt, const Vector< double > & x, Vector< double > & result) const inline protected virtual
Calculate the derivative of the velocity components of the base flow solution w.r.t. time at a given time and Eulerian position
Reimplemented in LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement.
   {
    // If the function pointer is zero return zero
    if(Base_flow_dudt_fct_pt==0)
     {
      // Loop over velocity components and set to zero
      for(unsigned i=0;i<3;i++) { result[i] = 0.0; }
     }
    // Otherwise call the function
    else
     {
      (*Base_flow_dudt_fct_pt)(time,x,result);
     }
   }
References Base_flow_dudt_fct_pt, i, and plotDoE::x.
Referenced by fill_in_generic_residual_contribution_lin_axi_nst().
get_base_flow_dudx() [1/3]
virtual void oomph::LinearisedAxisymmetricNavierStokesEquations::get_base_flow_dudx (const double & time, const unsigned & ipt, const Vector< double > & x, DenseMatrix< double > & result) const inline protected virtual
Calculate the derivatives of the velocity components of the base flow solution w.r.t. global coordinates (r and z) at a given time and Eulerian position
Reimplemented in RefineableLinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, RefineableLinearisedAxisymmetricQTaylorHoodMultiDomainElement, LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, LinearisedAxisymmetricQTaylorHoodMultiDomainElement, LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, RefineableLinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, RefineableLinearisedAxisymmetricQTaylorHoodMultiDomainElement, LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, and LinearisedAxisymmetricQTaylorHoodMultiDomainElement.
   {
    // If the function pointer is zero return zero
    if(Base_flow_dudx_fct_pt==0)
     {
      // Loop over velocity components
      for(unsigned i=0;i<3;i++)
       {
        // Loop over coordinate directions and set to zero
        for(unsigned j=0;j<2;j++) { result(i,j) = 0.0; }
       }
     }
    // Otherwise call the function
    else
     {
      (*Base_flow_dudx_fct_pt)(time,x,result);
     }
   }
References Base_flow_dudx_fct_pt, i, j, and plotDoE::x.
Referenced by fill_in_generic_residual_contribution_lin_axi_nst(), fill_in_generic_residual_contribution_linearised_axi_nst(), and oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst().
get_base_flow_dudx() [2/3]
virtual void oomph::LinearisedAxisymmetricNavierStokesEquations::get_base_flow_dudx (const double & time, const unsigned & ipt, const Vector< double > & x, DenseMatrix< double > & result) const inline protected virtual
Calculate the derivatives of the velocity components of the base flow solution w.r.t. global coordinates (r and z) at a given time and Eulerian position
Reimplemented in RefineableLinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, RefineableLinearisedAxisymmetricQTaylorHoodMultiDomainElement, LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, LinearisedAxisymmetricQTaylorHoodMultiDomainElement, LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, RefineableLinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, RefineableLinearisedAxisymmetricQTaylorHoodMultiDomainElement, LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, and LinearisedAxisymmetricQTaylorHoodMultiDomainElement.
   {
    // If the function pointer is zero return zero
    if(Base_flow_dudx_fct_pt==0)
     {
      // Loop over velocity components
      for(unsigned i=0;i<3;i++)
       {
        // Loop over coordinate directions and set to zero
        for(unsigned j=0;j<2;j++) { result(i,j) = 0.0; }
       }
     }
    // Otherwise call the function
    else
     {
      (*Base_flow_dudx_fct_pt)(time,x,result);
     }
   }
References Base_flow_dudx_fct_pt, i, j, and plotDoE::x.
get_base_flow_dudx() [3/3]
virtual void oomph::LinearisedAxisymmetricNavierStokesEquations::get_base_flow_dudx (const double & time, const unsigned & ipt, const Vector< double > & x, DenseMatrix< double > & result) const inline protected virtual
Calculate the derivatives of the velocity components of the base flow solution w.r.t. global coordinates (r and z) at a given time and Eulerian position
Reimplemented in RefineableLinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, RefineableLinearisedAxisymmetricQTaylorHoodMultiDomainElement, LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, LinearisedAxisymmetricQTaylorHoodMultiDomainElement, LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, RefineableLinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, RefineableLinearisedAxisymmetricQTaylorHoodMultiDomainElement, LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, and LinearisedAxisymmetricQTaylorHoodMultiDomainElement.
     {
       // If the function pointer is zero return zero
       if (Base_flow_dudx_fct_pt == 0)
       {
         // Loop over velocity components
         for (unsigned i = 0; i < 3; i++)
         {
           // Loop over coordinate directions and set to zero
           for (unsigned j = 0; j < 2; j++)
           {
             result(i, j) = 0.0;
           }
         }
       }
       // Otherwise call the function
       else
       {
         (*Base_flow_dudx_fct_pt)(time, x, result);
       }
     }
References Base_flow_dudx_fct_pt, i, j, and plotDoE::x.
get_base_flow_p()
virtual void oomph::LinearisedAxisymmetricNavierStokesEquations::get_base_flow_p (const double & time, const unsigned & ipt, const Vector< double > & x, double & result) const inline protected virtual
Calculate the pressure in the base flow solution at a given time and Eulerian position
Reimplemented in LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement.
   {
    // If the function pointer is zero return zero
    if(Base_flow_p_fct_pt==0) { result = 0.0; }
    // Otherwise call the function
    else { (*Base_flow_p_fct_pt)(time,x,result); }
   }
References Base_flow_p_fct_pt, and plotDoE::x.
Referenced by fill_in_generic_residual_contribution_lin_axi_nst().
get_base_flow_u() [1/3]
virtual void oomph::LinearisedAxisymmetricNavierStokesEquations::get_base_flow_u (const double & time, const unsigned & ipt, const Vector< double > & x, Vector< double > & result) const inline protected virtual
Calculate the velocity components of the base flow solution at a given time and Eulerian position
Reimplemented in RefineableLinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, RefineableLinearisedAxisymmetricQTaylorHoodMultiDomainElement, LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, LinearisedAxisymmetricQTaylorHoodMultiDomainElement, LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, RefineableLinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, RefineableLinearisedAxisymmetricQTaylorHoodMultiDomainElement, LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, and LinearisedAxisymmetricQTaylorHoodMultiDomainElement.
   {
    // If the function pointer is zero return zero
    if(Base_flow_u_fct_pt==0)
     {
      // Loop over velocity components and set base flow solution to zero
      for(unsigned i=0;i<3;i++) { result[i] = 0.0; }
     }
    // Otherwise call the function
    else
     {
      (*Base_flow_u_fct_pt)(time,x,result);
     }
   }
References Base_flow_u_fct_pt, i, and plotDoE::x.
Referenced by oomph::PerturbedSpineLinearisedAxisymmetricFluidInterfaceElement< ELEMENT >::fill_in_generic_residual_contribution_interface(), fill_in_generic_residual_contribution_lin_axi_nst(), fill_in_generic_residual_contribution_linearised_axi_nst(), and oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst().
get_base_flow_u() [2/3]
virtual void oomph::LinearisedAxisymmetricNavierStokesEquations::get_base_flow_u (const double & time, const unsigned & ipt, const Vector< double > & x, Vector< double > & result) const inline virtual
Calculate the velocity components of the base flow solution at a given time and Eulerian position
Reimplemented in RefineableLinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, RefineableLinearisedAxisymmetricQTaylorHoodMultiDomainElement, LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, LinearisedAxisymmetricQTaylorHoodMultiDomainElement, LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, RefineableLinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, RefineableLinearisedAxisymmetricQTaylorHoodMultiDomainElement, LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, and LinearisedAxisymmetricQTaylorHoodMultiDomainElement.
   {
    // If the function pointer is zero return zero
    if(Base_flow_u_fct_pt==0)
     {
      // Loop over velocity components and set base flow solution to zero
      for(unsigned i=0;i<3;i++) { result[i] = 0.0; }
     }
    // Otherwise call the function
    else
     {
      (*Base_flow_u_fct_pt)(time,x,result);
     }
   }
References Base_flow_u_fct_pt, i, and plotDoE::x.
get_base_flow_u() [3/3]
virtual void oomph::LinearisedAxisymmetricNavierStokesEquations::get_base_flow_u (const double & time, const unsigned & ipt, const Vector< double > & x, Vector< double > & result) const inline protected virtual
Calculate the velocity components of the base flow solution at a given time and Eulerian position
Reimplemented in RefineableLinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, RefineableLinearisedAxisymmetricQTaylorHoodMultiDomainElement, LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, LinearisedAxisymmetricQTaylorHoodMultiDomainElement, LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, RefineableLinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, RefineableLinearisedAxisymmetricQTaylorHoodMultiDomainElement, LinearisedAxisymmetricQCrouzeixRaviartMultiDomainElement, and LinearisedAxisymmetricQTaylorHoodMultiDomainElement.
     {
       // If the function pointer is zero return zero
       if (Base_flow_u_fct_pt == 0)
       {
         // Loop over velocity components and set base flow solution to zero
         for (unsigned i = 0; i < 3; i++)
         {
           result[i] = 0.0;
         }
       }
       // Otherwise call the function
       else
       {
         (*Base_flow_u_fct_pt)(time, x, result);
       }
     }
References Base_flow_u_fct_pt, i, and plotDoE::x.
get_body_force_base_flow()
void oomph::LinearisedAxisymmetricNavierStokesEquations::get_body_force_base_flow (const double & time, const unsigned & ipt, const Vector< double > & x, Vector< double > & result) inline protected
Calculate the body force fct of the base flow at a given time and Eulerian position
   {
    // If the function pointer is zero return zero
    if(Body_force_fct_pt==0)
     {
      // Loop over dimensions and set body forces to zero
      for(unsigned i=0;i<3;i++) { result[i] = 0.0; }
     }
    // Otherwise call the function
    else
     {
      (*Body_force_fct_pt)(time,x,result);
     }
   }
References Body_force_fct_pt, i, and plotDoE::x.
Referenced by fill_in_generic_residual_contribution_lin_axi_nst(), and get_body_force_gradient_base_flow().
get_body_force_gradient_base_flow()
void oomph::LinearisedAxisymmetricNavierStokesEquations::get_body_force_gradient_base_flow (const double & time, const unsigned & ipt, const Vector< double > & x, DenseMatrix< double > & result) inline protected
Calculate the gradient of the body force of the base flow at a given time and Eulerian position
   {
    // Reference value
    Vector<double> body_force(3,0.0);
    get_body_force_base_flow(time,ipt,x,body_force);
    // FD it
    const double eps_fd=GeneralisedElement::Default_fd_jacobian_step;
    Vector<double> body_force_pls(3,0.0);
    Vector<double> x_pls(x);
    for(unsigned i=0;i<2;i++)
     {
      x_pls[i] += eps_fd;
      get_body_force_base_flow(time,ipt,x_pls,body_force_pls);
      for(unsigned j=0;j<3;j++)
       {
        result(j,i)=(body_force_pls[j]-body_force[j])/eps_fd;
       }
      x_pls[i]=x[i];
     }
   }
References Global_Parameters::body_force(), oomph::GeneralisedElement::Default_fd_jacobian_step, get_body_force_base_flow(), i, j, and plotDoE::x.
get_local_eqn_number_corresponding_to_geometric_dofs()
virtual int oomph::LinearisedAxisymmetricNavierStokesEquations::get_local_eqn_number_corresponding_to_geometric_dofs (const unsigned & n, const unsigned & i) pure virtual
Return the local equation number corresponding to a particular geometric degree of freedom. This function is pure virtual because this information MUST be provided in any concrete derived classes. Note: n ranges from 0->number of PAIRS (cosine and sine) of geom dofs i ranges from 0->1 (0==cosine part, 1==sine part)
Referenced by fill_in_generic_residual_contribution_lin_axi_nst().
get_source_base_flow()
double oomph::LinearisedAxisymmetricNavierStokesEquations::get_source_base_flow (const double & time, const unsigned & ipt, const Vector< double > & x) inline protected
Calculate the source fct of the base flow at given time and Eulerian position
   {
    // If the function pointer is zero return zero
    if(Source_fct_pt==0) { return 0; }
    // Otherwise call the function
    else { return (*Source_fct_pt)(time,x); }
   }
References Source_fct_pt, and plotDoE::x.
Referenced by fill_in_generic_residual_contribution_lin_axi_nst(), and get_source_gradient_base_flow().
get_source_gradient_base_flow()
void oomph::LinearisedAxisymmetricNavierStokesEquations::get_source_gradient_base_flow (const double & time, const unsigned & ipt, const Vector< double > & x, Vector< double > & result) inline protected
Calculate the gradient of the source function of the base flow at a given time and Eulerian position
   {
    // Reference value
    const double source = get_source_base_flow(time,ipt,x);
    // FD it
    const double eps_fd = GeneralisedElement::Default_fd_jacobian_step;
    double source_pls = 0.0;
    Vector<double> x_pls(x);
    for(unsigned i=0;i<2;i++)
     {
      x_pls[i] += eps_fd;
      source_pls = get_source_base_flow(time,ipt,x_pls);
      result[i] = (source_pls-source)/eps_fd;
      x_pls[i] = x[i];
     }
   }
References oomph::GeneralisedElement::Default_fd_jacobian_step, get_source_base_flow(), i, TestProblem::source(), and plotDoE::x.
interpolated_nodal_position_perturbation_lin_axi_nst()
double oomph::LinearisedAxisymmetricNavierStokesEquations::interpolated_nodal_position_perturbation_lin_axi_nst (const Vector< double > & s, const unsigned & i) const inline
Return the i-th component of the FE interpolated perturbation to the nodal position xhat[i] at local coordinate s
    {
     // Determine number of nodes in the element
     const unsigned n_node = nnode();
     // Provide storage for local shape functions
     Shape psi(n_node);
     // Find values of shape functions
     shape(s,psi);
     // Get the index at which the perturbation to the nodal position
     // is stored
     const unsigned xhat_nodal_index = xhat_index_lin_axi_nst(i);
     // Initialise value of xhat
     double interpolated_xhat = 0.0;
     // Loop over the local nodes and sum
     for(unsigned l=0;l<n_node;l++)
      {
       interpolated_xhat += nodal_value(l,xhat_nodal_index)*psi[l];
      }
     return(interpolated_xhat);
    }
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), and xhat_index_lin_axi_nst().
interpolated_p_lin_axi_nst()
double oomph::LinearisedAxisymmetricNavierStokesEquations::interpolated_p_lin_axi_nst (const Vector< double > & s, const unsigned & i) const inline
Return the i-th component of the FE interpolated pressure p[i] at local coordinate s
    {
     // Determine number of pressure nodes in the element
     const unsigned n_pressure_nodes = npres_lin_axi_nst();
     // Provide storage for local shape functions
     Shape psi(n_pressure_nodes);
     // Find values of shape functions
     pshape_lin_axi_nst(s,psi);
     // Initialise value of p
     double interpolated_p = 0.0;
     // Loop over the local nodes and sum
     for(unsigned l=0;l<n_pressure_nodes;l++)
      {
       // N.B. The pure virtual function p_lin_axi_nst(...)
       // automatically calculates the index at which the pressure value
       // is stored, so we don't need to worry about this here
       interpolated_p += p_lin_axi_nst(l,i)*psi[l];
      }
     return(interpolated_p);
    }
References i, npres_lin_axi_nst(), p_lin_axi_nst(), pshape_lin_axi_nst(), and s.
interpolated_p_linearised_axi_nst() [1/2]
double oomph::LinearisedAxisymmetricNavierStokesEquations::interpolated_p_linearised_axi_nst (const Vector< double > & s, const unsigned & i) const inline
Return the i-th component of the FE interpolated pressure p[i] at local coordinate s
    {
     // Determine number of pressure nodes in the element
     const unsigned n_pressure_nodes = npres_linearised_axi_nst();
     // Provide storage for local shape functions
     Shape psi(n_pressure_nodes);
     // Find values of shape functions
     pshape_linearised_axi_nst(s,psi);
     // Initialise value of p
     double interpolated_p = 0.0;
     // Loop over the local nodes and sum
     for(unsigned l=0;l<n_pressure_nodes;l++)
      {
       // N.B. The pure virtual function p_linearised_axi_nst(...)
       // automatically calculates the index at which the pressure value
       // is stored, so we don't need to worry about this here
       interpolated_p += p_linearised_axi_nst(l,i)*psi[l];
      }
     return(interpolated_p);
    }
References i, npres_linearised_axi_nst(), p_linearised_axi_nst(), pshape_linearised_axi_nst(), and s.
Referenced by oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::further_build(), oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::get_interpolated_values(), and output().
interpolated_p_linearised_axi_nst() [2/2]
double oomph::LinearisedAxisymmetricNavierStokesEquations::interpolated_p_linearised_axi_nst (const Vector< double > & s, const unsigned & i) const inline
Return the i-th component of the FE interpolated pressure p[i] at local coordinate s
     {
       // Determine number of pressure nodes in the element
       const unsigned n_pressure_nodes = npres_linearised_axi_nst();
       // Provide storage for local shape functions
       Shape psi(n_pressure_nodes);
       // Find values of shape functions
       pshape_linearised_axi_nst(s, psi);
       // Initialise value of p
       double interpolated_p = 0.0;
       // Loop over the local nodes and sum
       for (unsigned l = 0; l < n_pressure_nodes; l++)
       {
         // N.B. The pure virtual function p_linearised_axi_nst(...)
         // automatically calculates the index at which the pressure value
         // is stored, so we don't need to worry about this here
         interpolated_p += p_linearised_axi_nst(l, i) * psi[l];
       }
       return (interpolated_p);
     }
References i, npres_linearised_axi_nst(), p_linearised_axi_nst(), pshape_linearised_axi_nst(), and s.
interpolated_u_lin_axi_nst()
double oomph::LinearisedAxisymmetricNavierStokesEquations::interpolated_u_lin_axi_nst (const Vector< double > & s, const unsigned & i) const inline
Return the i-th component of the FE interpolated velocity u[i] at local coordinate s
    {
     // Determine number of nodes in the element
     const unsigned n_node = nnode();
     // Provide storage for local shape functions
     Shape psi(n_node);
     // Find values of shape functions
     shape(s,psi);
     // Get the index at which the velocity is stored
     const unsigned u_nodal_index = u_index_lin_axi_nst(i);
     // Initialise value of u
     double interpolated_u = 0.0;
     // Loop over the local nodes and sum
     for(unsigned l=0;l<n_node;l++)
      {
       interpolated_u += nodal_value(l,u_nodal_index)*psi[l];
      }
     return(interpolated_u);
    }
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), and u_index_lin_axi_nst().
interpolated_u_linearised_axi_nst() [1/2]
double oomph::LinearisedAxisymmetricNavierStokesEquations::interpolated_u_linearised_axi_nst (const Vector< double > & s, const unsigned & i) const inline
Return the i-th component of the FE interpolated velocity u[i] at local coordinate s
    {
     // Determine number of nodes in the element
     const unsigned n_node = nnode();
     // Provide storage for local shape functions
     Shape psi(n_node);
     // Find values of shape functions
     shape(s,psi);
     // Get the index at which the velocity is stored
     const unsigned u_nodal_index = u_index_linearised_axi_nst(i);
     // Initialise value of u
     double interpolated_u = 0.0;
     // Loop over the local nodes and sum
     for(unsigned l=0;l<n_node;l++)
      {
       interpolated_u += nodal_value(l,u_nodal_index)*psi[l];
      }
     return(interpolated_u);
    }
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), and u_index_linearised_axi_nst().
Referenced by oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::get_interpolated_values(), oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::get_interpolated_values(), and output().
interpolated_u_linearised_axi_nst() [2/2]
double oomph::LinearisedAxisymmetricNavierStokesEquations::interpolated_u_linearised_axi_nst (const Vector< double > & s, const unsigned & i) const inline
Return the i-th component of the FE interpolated velocity u[i] at local coordinate s
     {
       // Determine number of nodes in the element
       const unsigned n_node = nnode();
       // Provide storage for local shape functions
       Shape psi(n_node);
       // Find values of shape functions
       shape(s, psi);
       // Get the index at which the velocity is stored
       const unsigned u_nodal_index = u_index_linearised_axi_nst(i);
       // Initialise value of u
       double interpolated_u = 0.0;
       // Loop over the local nodes and sum
       for (unsigned l = 0; l < n_node; l++)
       {
         interpolated_u += nodal_value(l, u_nodal_index) * psi[l];
       }
       return (interpolated_u);
     }
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), and u_index_linearised_axi_nst().
nexternal_H_data()
unsigned oomph::LinearisedAxisymmetricNavierStokesEquations::nexternal_H_data () inline
Return the number of external perturbed spine "heights" data.
 { return External_node.size(); }
References External_node.
Referenced by assign_additional_local_eqn_numbers().
npres_lin_axi_nst()
virtual unsigned oomph::LinearisedAxisymmetricNavierStokesEquations::npres_lin_axi_nst () const pure virtual
Return the number of pressure degrees of freedom associated with a single pressure component in the element
Implemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
Referenced by fill_in_generic_residual_contribution_lin_axi_nst(), and interpolated_p_lin_axi_nst().
npres_linearised_axi_nst() [1/2]
virtual unsigned oomph::LinearisedAxisymmetricNavierStokesEquations::npres_linearised_axi_nst () const pure virtual
Return the number of pressure degrees of freedom associated with a single pressure component in the element
Implemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
Referenced by fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), and interpolated_p_linearised_axi_nst().
npres_linearised_axi_nst() [2/2]
virtual unsigned oomph::LinearisedAxisymmetricNavierStokesEquations::npres_linearised_axi_nst () const pure virtual
Return the number of pressure degrees of freedom associated with a single pressure component in the element
Implemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
output() [1/12]
void oomph::LinearisedAxisymmetricNavierStokesEquations::output (FILE * file_pt) inline virtual
Output function: r, z, U^C, U^S, V^C, V^S, W^C, W^S, P^C, P^S in tecplot format. Default number of plot points
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
    {
     const unsigned nplot = 5;
     output(file_pt,nplot);
    }
References output().
output() [2/12]
void oomph::LinearisedAxisymmetricNavierStokesEquations::output (FILE * file_pt) inline virtual
Output function in tecplot format: r, z, U^C, U^S, V^C, V^S, W^C, W^S, P^C, P^S, R^C, R^S, Z^C, Z^S. Default number of plot points
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
    {
     const unsigned nplot = 5;
     output(file_pt,nplot);
    }
References output().
output() [3/12]
void oomph::LinearisedAxisymmetricNavierStokesEquations::output (FILE * file_pt) inline virtual
Output function: r, z, U^C, U^S, V^C, V^S, W^C, W^S, P^C, P^S in tecplot format. Default number of plot points
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
     {
       const unsigned nplot = 5;
       output(file_pt, nplot);
     }
References output().
output() [4/12]
void oomph::LinearisedAxisymmetricNavierStokesEquations::output (FILE * file_pt, const unsigned & nplot) virtual
Output function: r, z, U^C, U^S, V^C, V^S, W^C, W^S, P^C, P^S in tecplot format. nplot points in each coordinate direction
Output function: r, z, U^C, U^S, V^C, V^S, W^C, W^S, P^C, P^S in tecplot format. Specified number of plot points in each coordinate direction.
Output function in tecplot format: r, z, R^C, R^S, Z^C, Z^S, U^C, U^S, V^C, V^S, W^C, W^S, P^C, P^S Specified number of plot points in each coordinate direction.
Output function in tecplot format: r, z, U^C, U^S, V^C, V^S, W^C, W^S, P^C, P^S Specified number of plot points in each coordinate direction.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
  {
   // Provide storage for vector of local coordinates
   Vector<double> s(2);
   // Tecplot header info
   fprintf(file_pt,"%s ",tecplot_zone_string(nplot).c_str());
   // Determine number of plot points
   const unsigned n_plot_points = nplot_points(nplot);
   // Loop over plot points
   for(unsigned iplot=0;iplot<n_plot_points;iplot++)
    {
     // Get local coordinates of plot point
     get_s_plot(iplot,nplot,s);
     // Output global coordinates to file
     for(unsigned i=0;i<2;i++) { fprintf(file_pt,"%g ",interpolated_x(s,i)); }
     //  Output velocities to file
     for(unsigned i=0;i<6;i++)
      {
       fprintf(file_pt,"%g ",interpolated_u_linearised_axi_nst(s,i));
      }
     // Output pressure to file
     for(unsigned i=0;i<2;i++)
      {
       fprintf(file_pt,"%g ",interpolated_p_linearised_axi_nst(s,i));
      }
     fprintf(file_pt,"\n");
    }
   fprintf(file_pt,"\n");
   // Write tecplot footer (e.g. FE connectivity lists)
   write_tecplot_zone_footer(file_pt,nplot);
  } // End of output(...)
References oomph::FiniteElement::get_s_plot(), i, interpolated_p_linearised_axi_nst(), interpolated_u_linearised_axi_nst(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output() [5/12]
void oomph::LinearisedAxisymmetricNavierStokesEquations::output (FILE * file_pt, const unsigned & nplot) virtual
Output function in tecplot format: r, z, U^C, U^S, V^C, V^S, W^C, W^S, P^C, P^S, R^C, R^S, Z^C, Z^S. Use nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
output() [6/12]
void oomph::LinearisedAxisymmetricNavierStokesEquations::output (FILE * file_pt, const unsigned & nplot) virtual
Output function: r, z, U^C, U^S, V^C, V^S, W^C, W^S, P^C, P^S in tecplot format. nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
output() [7/12]
void oomph::LinearisedAxisymmetricNavierStokesEquations::output (std::ostream & outfile) inline virtual
Output function: r, z, U^C, U^S, V^C, V^S, W^C, W^S, P^C, P^S in tecplot format. Default number of plot points
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
    {
     const unsigned nplot = 5;
     output(outfile,nplot);
    }
Referenced by output(), oomph::LinearisedAxisymmetricQCrouzeixRaviartElement::output(), and oomph::LinearisedAxisymmetricQTaylorHoodElement::output().
output() [8/12]
void oomph::LinearisedAxisymmetricNavierStokesEquations::output (std::ostream & outfile) inline virtual
Output function in tecplot format: r, z, U^C, U^S, V^C, V^S, W^C, W^S, P^C, P^S, R^C, R^S, Z^C, Z^S. Default number of plot points
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
    {
     const unsigned nplot = 5;
     output(outfile,nplot);
    }
References output().
output() [9/12]
void oomph::LinearisedAxisymmetricNavierStokesEquations::output (std::ostream & outfile) inline virtual
Output function: r, z, U^C, U^S, V^C, V^S, W^C, W^S, P^C, P^S in tecplot format. Default number of plot points
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
     {
       const unsigned nplot = 5;
       output(outfile, nplot);
     }
References output().
output() [10/12]
void oomph::LinearisedAxisymmetricNavierStokesEquations::output (std::ostream & outfile, const unsigned & nplot) virtual
Output function: r, z, U^C, U^S, V^C, V^S, W^C, W^S, P^C, P^S in tecplot format. nplot points in each coordinate direction
Output function: r, z, U^C, U^S, V^C, V^S, W^C, W^S, P^C, P^S in tecplot format. Specified number of plot points in each coordinate direction.
Output function in tecplot format: r, z, R^C, R^S, Z^C, Z^S, U^C, U^S, V^C, V^S, W^C, W^S, P^C, P^S Specified number of plot points in each coordinate direction.
Output function in tecplot format: r, z, U^C, U^S, V^C, V^S, W^C, W^S, P^C, P^S in tecplot format. Specified number of plot points in each coordinate direction.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
  {
   // Provide storage for vector of local coordinates
   Vector<double> s(2);
   // Tecplot header info
   outfile << tecplot_zone_string(nplot);
   // Determine number of plot points
   const unsigned n_plot_points = nplot_points(nplot);
   // Loop over plot points
   for(unsigned iplot=0;iplot<n_plot_points;iplot++)
    {
     // Get local coordinates of plot point
     get_s_plot(iplot,nplot,s);
     // Output global coordinates to file
     for(unsigned i=0;i<2;i++) { outfile << interpolated_x(s,i) << " "; }
     //  Output velocities to file
     for(unsigned i=0;i<6;i++)
      {
       outfile << interpolated_u_linearised_axi_nst(s,i) << " ";
      }
     // Output pressure to file
     for(unsigned i=0;i<2;i++)
      {
       outfile << interpolated_p_linearised_axi_nst(s,i)  << " ";
      }
     outfile << std::endl;
    }
   outfile << std::endl;
   // Write tecplot footer (e.g. FE connectivity lists)
   write_tecplot_zone_footer(outfile,nplot);
  } // End of output(...)
References oomph::FiniteElement::get_s_plot(), i, interpolated_p_linearised_axi_nst(), interpolated_u_linearised_axi_nst(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output() [11/12]
void oomph::LinearisedAxisymmetricNavierStokesEquations::output (std::ostream & outfile, const unsigned & nplot) virtual
Output function in tecplot format: r, z, U^C, U^S, V^C, V^S, W^C, W^S, P^C, P^S, R^C, R^S, Z^C, Z^S. Use nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
output() [12/12]
void oomph::LinearisedAxisymmetricNavierStokesEquations::output (std::ostream & outfile, const unsigned & nplot) virtual
Output function: r, z, U^C, U^S, V^C, V^S, W^C, W^S, P^C, P^S in tecplot format. nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
output_veloc() [1/3]
void oomph::LinearisedAxisymmetricNavierStokesEquations::output_veloc (std::ostream & outfile, const unsigned & nplot, const unsigned & t)
Output function: r, z, U^C, U^S, V^C, V^S, W^C, W^S, in tecplot format. nplot points in each coordinate direction at timestep t (t=0: present; t>0: previous timestep)
Output function: Velocities only
r, z, U^C, U^S, V^C, V^S, W^C, W^S in tecplot format at specified previous timestep (t=0: present; t>0: previous timestep). Specified number of plot points in each coordinate direction.
Output function in tecplot format: Velocities only
r, z, U^C, U^S, V^C, V^S, W^C, W^S at specified previous timestep (t=0 present; t>0 previous timestep). Specified number of plot points in each coordinate direction.
Output function in tecplot format: Velocities only r, z, U^C, U^S, V^C, V^S, W^C, W^S at specified previous timestep (t=0 present; t>0 previous timestep). Specified number of plot points in each coordinate direction.
  {
   // Determine number of nodes in element
   const unsigned n_node = nnode();
   // Provide storage for local shape functions
   Shape psi(n_node);
   // Provide storage for vectors of local coordinates and
   // global coordinates and velocities
   Vector<double> s(2);
   Vector<double> interpolated_x(2);
   Vector<double> interpolated_u(6);
   // Tecplot header info
   outfile << tecplot_zone_string(nplot);
   // Determine number of plot points
   const unsigned n_plot_points = nplot_points(nplot);
   // Loop over plot points
   for(unsigned iplot=0;iplot<n_plot_points;iplot++)
    {
     // Get local coordinates of plot point
     get_s_plot(iplot,nplot,s);
     // Get shape functions
     shape(s,psi);
     // Loop over coordinate directions
     for(unsigned i=0;i<2;i++)
      {
       // Initialise global coordinate
       interpolated_x[i]=0.0;
       // Loop over the local nodes and sum
       for(unsigned l=0;l<n_node;l++)
        {
         interpolated_x[i] += nodal_position(t,l,i)*psi[l];
        }
      }
     // Loop over the velocity components
     for(unsigned i=0;i<6;i++)
      {
       // Get the index at which the velocity is stored
       const unsigned u_nodal_index = u_index_linearised_axi_nst(i);
       // Initialise velocity
       interpolated_u[i]=0.0;
       // Loop over the local nodes and sum
       for(unsigned l=0;l<n_node;l++)
        {
         interpolated_u[i] += nodal_value(t,l,u_nodal_index)*psi[l];
        }
      }
     // Output global coordinates to file
     for(unsigned i=0;i<2;i++) { outfile << interpolated_x[i] << " "; }
     // Output velocities to file
     for(unsigned i=0;i<6;i++) { outfile << interpolated_u[i] << " "; }
     outfile << std::endl;
    }
   // Write tecplot footer (e.g. FE connectivity lists)
   write_tecplot_zone_footer(outfile,nplot);
  } // End of output_veloc
References oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::shape(), plotPSD::t, oomph::FiniteElement::tecplot_zone_string(), u_index_linearised_axi_nst(), and oomph::FiniteElement::write_tecplot_zone_footer().
output_veloc() [2/3]
void oomph::LinearisedAxisymmetricNavierStokesEquations::output_veloc (std::ostream & outfile, const unsigned & nplot, const unsigned & t)
Output function: r, z, U^C, U^S, V^C, V^S, W^C, W^S, in tecplot format. nplot points in each coordinate direction at timestep t (t=0: present; t>0: previous timestep)
output_veloc() [3/3]
void oomph::LinearisedAxisymmetricNavierStokesEquations::output_veloc (std::ostream & outfile, const unsigned & nplot, const unsigned & t)
Output function: r, z, U^C, U^S, V^C, V^S, W^C, W^S, in tecplot format. nplot points in each coordinate direction at timestep t (t=0: present; t>0: previous timestep)
p_index_lin_axi_nst()
virtual int oomph::LinearisedAxisymmetricNavierStokesEquations::p_index_lin_axi_nst (const unsigned & i) const inline virtual
Which nodal value represents the pressure?
Reimplemented in oomph::LinearisedAxisymmetricQTaylorHoodElement.
           { return Pressure_not_stored_at_node; }
References Pressure_not_stored_at_node.
p_index_linearised_axi_nst() [1/2]
virtual int oomph::LinearisedAxisymmetricNavierStokesEquations::p_index_linearised_axi_nst (const unsigned & i) const inline virtual
Which nodal value represents the pressure?
Reimplemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQTaylorHoodElement.
           { return Pressure_not_stored_at_node; }
References Pressure_not_stored_at_node.
Referenced by oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::pin_elemental_redundant_nodal_pressure_dofs(), and oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::unpin_elemental_pressure_dofs().
p_index_linearised_axi_nst() [2/2]
virtual int oomph::LinearisedAxisymmetricNavierStokesEquations::p_index_linearised_axi_nst (const unsigned & i) const inline virtual
Which nodal value represents the pressure?
Reimplemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQTaylorHoodElement.
     {
       return Pressure_not_stored_at_node;
     }
References Pressure_not_stored_at_node.
p_lin_axi_nst()
virtual double oomph::LinearisedAxisymmetricNavierStokesEquations::p_lin_axi_nst (const unsigned & n_p, const unsigned & i) const pure virtual
Return the i-th pressure value at local pressure "node" n_p. Uses suitably interpolated value for hanging nodes.
Implemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
Referenced by fill_in_generic_residual_contribution_lin_axi_nst(), and interpolated_p_lin_axi_nst().
p_linearised_axi_nst() [1/2]
virtual double oomph::LinearisedAxisymmetricNavierStokesEquations::p_linearised_axi_nst (const unsigned & n_p, const unsigned & i) const pure virtual
Return the i-th pressure value at local pressure "node" n_p. Uses suitably interpolated value for hanging nodes.
Implemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
Referenced by fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), and interpolated_p_linearised_axi_nst().
p_linearised_axi_nst() [2/2]
virtual double oomph::LinearisedAxisymmetricNavierStokesEquations::p_linearised_axi_nst (const unsigned & n_p, const unsigned & i) const pure virtual
Return the i-th pressure value at local pressure "node" n_p. Uses suitably interpolated value for hanging nodes.
Implemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
p_local_eqn() [1/3]
virtual int oomph::LinearisedAxisymmetricNavierStokesEquations::p_local_eqn (const unsigned & n, const unsigned & i) protected pure virtual
Access function for the local equation number information for the i-th component of the pressure. p_local_eqn[n,i] = local equation number or < 0 if pinned.
Implemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
Referenced by fill_in_generic_residual_contribution_lin_axi_nst(), fill_in_generic_residual_contribution_linearised_axi_nst(), and oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst().
p_local_eqn() [2/3]
virtual int oomph::LinearisedAxisymmetricNavierStokesEquations::p_local_eqn (const unsigned & n, const unsigned & i) protected pure virtual
Access function for the local equation number information for the i-th component of the pressure. p_local_eqn[n,i] = local equation number or < 0 if pinned.
Implemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
p_local_eqn() [3/3]
virtual int oomph::LinearisedAxisymmetricNavierStokesEquations::p_local_eqn (const unsigned & n, const unsigned & i) protected pure virtual
Access function for the local equation number information for the i-th component of the pressure. p_local_eqn[n,i] = local equation number or < 0 if pinned.
Implemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
pshape_lin_axi_nst() [1/2]
virtual void oomph::LinearisedAxisymmetricNavierStokesEquations::pshape_lin_axi_nst (const Vector< double > & s, Shape & psi) const protected pure virtual
Compute the pressure shape functions at local coordinate s.
Implemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
Referenced by fill_in_generic_residual_contribution_lin_axi_nst(), and interpolated_p_lin_axi_nst().
pshape_lin_axi_nst() [2/2]
virtual void oomph::LinearisedAxisymmetricNavierStokesEquations::pshape_lin_axi_nst (const Vector< double > & s, Shape & psi, Shape & test) const protected pure virtual
Compute the pressure shape and test functions at local coordinate s.
Implemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
pshape_linearised_axi_nst() [1/4]
virtual void oomph::LinearisedAxisymmetricNavierStokesEquations::pshape_linearised_axi_nst (const Vector< double > & s, Shape & psi) const protected pure virtual
Compute the pressure shape functions at local coordinate s.
Implemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
Referenced by fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), and interpolated_p_linearised_axi_nst().
pshape_linearised_axi_nst() [2/4]
virtual void oomph::LinearisedAxisymmetricNavierStokesEquations::pshape_linearised_axi_nst (const Vector< double > & s, Shape & psi) const protected pure virtual
Compute the pressure shape functions at local coordinate s.
Implemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
pshape_linearised_axi_nst() [3/4]
virtual void oomph::LinearisedAxisymmetricNavierStokesEquations::pshape_linearised_axi_nst (const Vector< double > & s, Shape & psi, Shape & test) const protected pure virtual
Compute the pressure shape and test functions at local coordinate s.
Implemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
pshape_linearised_axi_nst() [4/4]
virtual void oomph::LinearisedAxisymmetricNavierStokesEquations::pshape_linearised_axi_nst (const Vector< double > & s, Shape & psi, Shape & test) const protected pure virtual
Compute the pressure shape and test functions at local coordinate s.
Implemented in oomph::LinearisedAxisymmetricQTaylorHoodElement, oomph::LinearisedAxisymmetricQCrouzeixRaviartElement, oomph::LinearisedAxisymmetricQTaylorHoodElement, and oomph::LinearisedAxisymmetricQCrouzeixRaviartElement.
re() [1/3]
const double& oomph::LinearisedAxisymmetricNavierStokesEquations::re () const inline
Reynolds number.
 { return *Re_pt; }
References Re_pt.
Referenced by fill_in_generic_residual_contribution_lin_axi_nst(), fill_in_generic_residual_contribution_linearised_axi_nst(), and oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst().
re() [2/3]
const double& oomph::LinearisedAxisymmetricNavierStokesEquations::re () const inline
Reynolds number.
 { return *Re_pt; }
References Re_pt.
re() [3/3]
const double& oomph::LinearisedAxisymmetricNavierStokesEquations::re () const inline
Reynolds number.
     {
       return *Re_pt;
     }
References Re_pt.
re_invfr()
const double& oomph::LinearisedAxisymmetricNavierStokesEquations::re_invfr () const inline
Global inverse Froude number.
 {return *ReInvFr_pt;}
References ReInvFr_pt.
Referenced by fill_in_generic_residual_contribution_lin_axi_nst().
re_invfr_pt()
double* & oomph::LinearisedAxisymmetricNavierStokesEquations::re_invfr_pt () inline
Pointer to global inverse Froude number.
 {return ReInvFr_pt;}
References ReInvFr_pt.
re_invro()
const double& oomph::LinearisedAxisymmetricNavierStokesEquations::re_invro () const inline
Global Reynolds number multiplied by inverse Rossby number.
 {return *ReInvRo_pt;}
References ReInvRo_pt.
re_invro_pt()
double* & oomph::LinearisedAxisymmetricNavierStokesEquations::re_invro_pt () inline
Pointer to global Reynolds number multiplied by inverse Rossby number.
 {return ReInvRo_pt;}
References ReInvRo_pt.
re_pt() [1/3]
double* & oomph::LinearisedAxisymmetricNavierStokesEquations::re_pt () inline
Pointer to Reynolds number.
 { return Re_pt; }
References Re_pt.
Referenced by oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::further_build().
re_pt() [2/3]
double* & oomph::LinearisedAxisymmetricNavierStokesEquations::re_pt () inline
Pointer to Reynolds number.
 { return Re_pt; }
References Re_pt.
re_pt() [3/3]
double*& oomph::LinearisedAxisymmetricNavierStokesEquations::re_pt () inline
Pointer to Reynolds number.
     {
       return Re_pt;
     }
References Re_pt.
re_st() [1/3]
const double& oomph::LinearisedAxisymmetricNavierStokesEquations::re_st () const inline
Product of Reynolds and Strouhal number (=Womersley number)
 { return *ReSt_pt; }
References ReSt_pt.
Referenced by fill_in_generic_residual_contribution_lin_axi_nst(), fill_in_generic_residual_contribution_linearised_axi_nst(), and oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst().
re_st() [2/3]
const double& oomph::LinearisedAxisymmetricNavierStokesEquations::re_st () const inline
Product of Reynolds and Strouhal number (=Womersley number)
 { return *ReSt_pt; }
References ReSt_pt.
re_st() [3/3]
const double& oomph::LinearisedAxisymmetricNavierStokesEquations::re_st () const inline
Product of Reynolds and Strouhal number (=Womersley number)
     {
       return *ReSt_pt;
     }
References ReSt_pt.
re_st_pt() [1/3]
double* & oomph::LinearisedAxisymmetricNavierStokesEquations::re_st_pt () inline
Pointer to product of Reynolds and Strouhal number (=Womersley number)
 { return ReSt_pt; }
References ReSt_pt.
Referenced by oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::further_build().
re_st_pt() [2/3]
double* & oomph::LinearisedAxisymmetricNavierStokesEquations::re_st_pt () inline
Pointer to product of Reynolds and Strouhal number (=Womersley number)
 { return ReSt_pt; }
References ReSt_pt.
re_st_pt() [3/3]
double*& oomph::LinearisedAxisymmetricNavierStokesEquations::re_st_pt () inline
Pointer to product of Reynolds and Strouhal number (=Womersley number)
     {
       return ReSt_pt;
     }
References ReSt_pt.
strain_rate() [1/3]
void oomph::LinearisedAxisymmetricNavierStokesEquations::strain_rate (const Vector< double > & s, DenseMatrix< double > & strainrate) const
Strain-rate tensor: \(e_{ij} \) where \(i,j = r,z,\theta \) (in that order)
Get strain-rate tensor: \(e_{ij} \) where \(i,j = r,z,\theta \) (in that order) We evaluate this tensor at a value of theta such that the product of theta and the azimuthal mode number (k) gives \(\pi/4 \). Therefore \(\cos(k \theta) = \sin(k \theta) = 1/\sqrt{2} \).
Get strain-rate tensor: \(e_{ij} \) where \(i,j = r,z,\theta \) (in that order). We evaluate this tensor at a value of theta such that the product of theta and the azimuthal mode number (k) gives \(\pi/4 \). Therefore \(\cos(k \theta) = \sin(k \theta) = 1/\sqrt{2} \).
  {
 #ifdef PARANOID
   if ((strainrate.ncol()!=3)||(strainrate.nrow()!=3))
    {
     std::ostringstream error_message;
     error_message  << "The strain rate has incorrect dimensions "
                    << strainrate.ncol() << " x "
                    << strainrate.nrow() << " Not 3" << std::endl;
     throw OomphLibError(error_message.str(),
                         OOMPH_CURRENT_FUNCTION,
                         OOMPH_EXCEPTION_LOCATION);
    }
 #endif
   //Find out how many nodes there are in the element
   unsigned n_node = nnode();
   //Set up memory for the shape and test functions
   Shape psi(n_node);
   DShape dpsidx(n_node,2);
   //Call the derivatives of the shape functions
   dshape_eulerian(s,psi,dpsidx);
   // Radius
   double interpolated_r = 0.0;
   // Velocity components and their derivatives
   double UC = 0.0, US = 0.0;
   double dUCdr = 0.0, dUSdr = 0.0;
   double dUCdz = 0.0, dUSdz = 0.0;
   double WC = 0.0, WS = 0.0;
   double dWCdr = 0.0, dWSdr = 0.0;
   double dWCdz = 0.0, dWSdz = 0.0;
   double VC = 0.0, VS = 0.0;
   double dVCdr = 0.0, dVSdr = 0.0;
   double dVCdz = 0.0, dVSdz = 0.0;
   //Get the local storage for the indices
   unsigned u_nodal_index[6];
   for(unsigned i=0;i<6;++i) {u_nodal_index[i] = u_index_linearised_axi_nst(i);}
   // Loop over nodes to assemble velocities and their derivatives
   // w.r.t. r and z (x_0 and x_1)
   for(unsigned l=0;l<n_node;l++)
    {
     interpolated_r += nodal_position(l,0)*psi[l];
     UC += nodal_value(l,u_nodal_index[0])*psi[l];
     US += nodal_value(l,u_nodal_index[1])*psi[l];
     WC += nodal_value(l,u_nodal_index[2])*psi[l];
     WS += nodal_value(l,u_nodal_index[3])*psi[l];
     VC += nodal_value(l,u_nodal_index[4])*psi[l];
     VS += nodal_value(l,u_nodal_index[4])*psi[l];
     dUCdr += nodal_value(l,u_nodal_index[0])*dpsidx(l,0);
     dUSdr += nodal_value(l,u_nodal_index[1])*dpsidx(l,0);
     dWCdr += nodal_value(l,u_nodal_index[2])*dpsidx(l,0);
     dWSdr += nodal_value(l,u_nodal_index[3])*dpsidx(l,0);
     dVCdr += nodal_value(l,u_nodal_index[4])*dpsidx(l,0);
     dVSdr += nodal_value(l,u_nodal_index[5])*dpsidx(l,0);
     dUCdz += nodal_value(l,u_nodal_index[0])*dpsidx(l,1);
     dUSdz += nodal_value(l,u_nodal_index[1])*dpsidx(l,1);
     dWCdz += nodal_value(l,u_nodal_index[2])*dpsidx(l,1);
     dWSdz += nodal_value(l,u_nodal_index[3])*dpsidx(l,1);
     dVCdz += nodal_value(l,u_nodal_index[4])*dpsidx(l,1);
     dVSdz += nodal_value(l,u_nodal_index[5])*dpsidx(l,1);
    }
   // Cache azimuthal mode number
   const int k = this->azimuthal_mode_number();
   // We wish to evaluate the strain-rate tensor at a value of theta
   // such that k*theta = pi/4 radians. That way we pick up equal
   // contributions from the real and imaginary parts of the velocities.
   // sin(pi/4) = cos(pi/4) = 1/sqrt(2)
   const double cosktheta = 1.0/sqrt(2);
   const double sinktheta = cosktheta;
   // Assemble velocities and their derivatives w.r.t. r, z and theta
   // from real and imaginary parts
   const double ur = UC*cosktheta + US*sinktheta;
   const double utheta = VC*cosktheta + VS*sinktheta;
   const double durdr = dUCdr*cosktheta + dUSdr*sinktheta;
   const double durdz = dUCdz*cosktheta + dUSdz*sinktheta;
   const double durdtheta = k*US*cosktheta - k*UC*sinktheta;
   const double duzdr = dWCdr*cosktheta + dWSdr*sinktheta;
   const double duzdz = dWCdz*cosktheta + dWSdz*sinktheta;
   const double duzdtheta = k*WS*cosktheta - k*WC*sinktheta;
   const double duthetadr = dVCdr*cosktheta + dVSdr*sinktheta;
   const double duthetadz = dVCdz*cosktheta + dVSdz*sinktheta;
   const double duthetadtheta = k*VS*cosktheta - k*VC*sinktheta;
   // Assign strain rates without negative powers of the radius
   // and zero those with:
   strainrate(0,0)=durdr;
   strainrate(0,1)=0.5*(durdz+duzdr);
   strainrate(1,0)=strainrate(0,1);
   strainrate(0,2)=0.5*duthetadr;
   strainrate(2,0)=strainrate(0,2);
   strainrate(1,1)=duzdz;
   strainrate(1,2)=0.5*duthetadz;
   strainrate(2,1)=strainrate(1,2);
   strainrate(2,2)=0.0;
   // Overwrite the strain rates with negative powers of the radius
   // unless we're at the origin
   if (std::abs(interpolated_r)>1.0e-16)
    {
     double inverse_radius=1.0/interpolated_r;
     strainrate(0,2)=0.5*(duthetadr + inverse_radius*(durdtheta - utheta));
     strainrate(2,0)=strainrate(0,2);
     strainrate(2,2)=inverse_radius*(ur + duthetadtheta);
     strainrate(1,2)=0.5*(duthetadz + inverse_radius*duzdtheta);
     strainrate(2,1)=strainrate(1,2);
    }
  }
References abs(), azimuthal_mode_number(), oomph::FiniteElement::dshape_eulerian(), i, k, oomph::DenseMatrix< T >::ncol(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_value(), oomph::DenseMatrix< T >::nrow(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, s, sqrt(), and u_index_linearised_axi_nst().
Referenced by oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::get_Z2_flux().
strain_rate() [2/3]
void oomph::LinearisedAxisymmetricNavierStokesEquations::strain_rate (const Vector< double > & s, DenseMatrix< double > & strain_rate) const
Strain-rate tensor: \(e_{ij} \) where \(i,j = r,z,\theta \) (in that order)
strain_rate() [3/3]
void oomph::LinearisedAxisymmetricNavierStokesEquations::strain_rate (const Vector< double > & s, DenseMatrix< double > & strain_rate) const
Strain-rate tensor: \(e_{ij} \) where \(i,j = r,z,\theta \) (in that order)
u_index_lin_axi_nst()
virtual unsigned oomph::LinearisedAxisymmetricNavierStokesEquations::u_index_lin_axi_nst (const unsigned & i) const inline virtual
Return the index at which the i-th unknown velocity component is stored. The default value, i+4, is appropriate for single-physics problems, since it stores the velocity components immediately after the four perturbations to the nodal positions. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknowns are always stored at the same indices at each node.
           { return i+4; }
References i.
Referenced by dkin_energy_dt(), du_dt_lin_axi_nst(), fill_in_generic_residual_contribution_lin_axi_nst(), and interpolated_u_lin_axi_nst().
u_index_linearised_axi_nst() [1/2]
virtual unsigned oomph::LinearisedAxisymmetricNavierStokesEquations::u_index_linearised_axi_nst (const unsigned & i) const inline virtual
Return the index at which the i-th unknown velocity component is stored. The default value, i, is appropriate for single-physics problems. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknowns are always stored at the same indices at each node.
           { return i; }
References i.
Referenced by du_dt_linearised_axi_nst(), fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement::get_interpolated_values(), oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement::get_interpolated_values(), interpolated_u_linearised_axi_nst(), output_veloc(), and strain_rate().
u_index_linearised_axi_nst() [2/2]
virtual unsigned oomph::LinearisedAxisymmetricNavierStokesEquations::u_index_linearised_axi_nst (const unsigned & i) const inline virtual
Return the index at which the i-th unknown velocity component is stored. The default value, i, is appropriate for single-physics problems. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknowns are always stored at the same indices at each node.
     {
       return i;
     }
References i.
viscosity_ratio() [1/3]
const double& oomph::LinearisedAxisymmetricNavierStokesEquations::viscosity_ratio () const inline
Viscosity ratio for element: element's viscosity relative to the viscosity used in the definition of the Reynolds number
 { return *Viscosity_Ratio_pt; }
References Viscosity_Ratio_pt.
Referenced by fill_in_generic_residual_contribution_lin_axi_nst(), fill_in_generic_residual_contribution_linearised_axi_nst(), and oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst().
viscosity_ratio() [2/3]
const double& oomph::LinearisedAxisymmetricNavierStokesEquations::viscosity_ratio () const inline
Viscosity ratio for element: element's viscosity relative to the viscosity used in the definition of the Reynolds number
 { return *Viscosity_Ratio_pt; }
References Viscosity_Ratio_pt.
viscosity_ratio() [3/3]
const double& oomph::LinearisedAxisymmetricNavierStokesEquations::viscosity_ratio () const inline
Viscosity ratio for element: element's viscosity relative to the viscosity used in the definition of the Reynolds number
     {
       return *Viscosity_Ratio_pt;
     }
References Viscosity_Ratio_pt.
viscosity_ratio_pt() [1/3]
double* & oomph::LinearisedAxisymmetricNavierStokesEquations::viscosity_ratio_pt () inline
Pointer to the viscosity ratio.
 { return Viscosity_Ratio_pt; }
References Viscosity_Ratio_pt.
Referenced by oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::further_build().
viscosity_ratio_pt() [2/3]
double* & oomph::LinearisedAxisymmetricNavierStokesEquations::viscosity_ratio_pt () inline
Pointer to the viscosity ratio.
 { return Viscosity_Ratio_pt; }
References Viscosity_Ratio_pt.
viscosity_ratio_pt() [3/3]
double*& oomph::LinearisedAxisymmetricNavierStokesEquations::viscosity_ratio_pt () inline
Pointer to the viscosity ratio.
     {
       return Viscosity_Ratio_pt;
     }
References Viscosity_Ratio_pt.
xhat_index_lin_axi_nst()
virtual unsigned oomph::LinearisedAxisymmetricNavierStokesEquations::xhat_index_lin_axi_nst (const unsigned & i) const inline virtual
Return the index at which the i-th component of the unknown perturbation to the nodal position is stored. The default value, i, is appropriate for single-physics problems. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknowns are always stored at the same indices at each node.
 { return i; }
References i.
Referenced by dnodal_position_perturbation_dt_lin_axi_nst(), fill_in_generic_residual_contribution_lin_axi_nst(), and interpolated_nodal_position_perturbation_lin_axi_nst().
Member Data Documentation
ALE_is_disabled
bool oomph::LinearisedAxisymmetricNavierStokesEquations::ALE_is_disabled protected
Boolean flag to indicate if ALE formulation is disabled when the time-derivatives are computed. Only set to true if you're sure that the mesh is stationary.
Referenced by disable_ALE(), enable_ALE(), fill_in_generic_residual_contribution_lin_axi_nst(), fill_in_generic_residual_contribution_linearised_axi_nst(), oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst(), and oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::further_build().
Azimuthal_Mode_Number_pt
int * oomph::LinearisedAxisymmetricNavierStokesEquations::Azimuthal_Mode_Number_pt protected
Pointer to azimuthal mode number k in e^ik(theta) decomposition.
Referenced by azimuthal_mode_number(), azimuthal_mode_number_pt(), oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::further_build(), and LinearisedAxisymmetricNavierStokesEquations().
base_flow_d_dudx_dX_fct_pt
void(* &)(const double& time, const Vector<double>& x, RankFourTensor<double>& f) oomph::LinearisedAxisymmetricNavierStokesEquations::base_flow_d_dudx_dX_fct_pt() inline
Access function for the derivs w.r.t. nodal coords X_{pq} of the spatial derivatives of base flow velocities pointer
     {
      return Base_flow_d_dudx_dX_fct_pt;
     }
Base_flow_d_dudx_dX_fct_pt
void(* oomph::LinearisedAxisymmetricNavierStokesEquations::Base_flow_d_dudx_dX_fct_pt) (const double &time, const Vector< double > &x, RankFourTensor< double > &result) protected
Pointer to derivs w.r.t. nodal coords X_{pq} of spatial derivatives of base flow solution velocities function
Referenced by get_base_flow_d_dudx_dX().
base_flow_duds_fct_pt
void(* &)(const double& time, const Vector<double>& x, DenseMatrix<double>& f) oomph::LinearisedAxisymmetricNavierStokesEquations::base_flow_duds_fct_pt() inline
Access function for the derivatives of the base flow velocities w.r.t. local coordinates solution pointer
     {
      return Base_flow_duds_fct_pt;
     }
Base_flow_duds_fct_pt
void(* oomph::LinearisedAxisymmetricNavierStokesEquations::Base_flow_duds_fct_pt) (const double &time, const Vector< double > &x, DenseMatrix< double > &result) protected
Pointer to derivatives of base flow solution velocity components w.r.t. local coordinates (s_1 and s_2) function
Referenced by get_base_flow_duds().
base_flow_dudt_fct_pt
void(* &)(const double& time, const Vector<double>& x, Vector<double>& f) oomph::LinearisedAxisymmetricNavierStokesEquations::base_flow_dudt_fct_pt() inline
Access function for the derivatives of the base flow velocities w.r.t. time solution pointer
     {
      return Base_flow_dudt_fct_pt;
     }
Base_flow_dudt_fct_pt
void(* oomph::LinearisedAxisymmetricNavierStokesEquations::Base_flow_dudt_fct_pt) (const double &time, const Vector< double > &x, Vector< double > &result) protected
Pointer to derivatives of base flow solution velocity components w.r.t. time function
Referenced by get_base_flow_dudt().
base_flow_dudx_fct_pt
void(*&)(const double& time, const Vector<double>& x, DenseMatrix<double>& f) oomph::LinearisedAxisymmetricNavierStokesEquations::base_flow_dudx_fct_pt() inline
Access function for the derivatives of the base flow w.r.t. global coordinates solution pointer
     {
      return Base_flow_dudx_fct_pt;
     }
Base_flow_dudx_fct_pt
void(* oomph::LinearisedAxisymmetricNavierStokesEquations::Base_flow_dudx_fct_pt)(const double &time, const Vector< double > &x, DenseMatrix< double > &result) protected
Pointer to derivatives of base flow solution velocity components w.r.t. global coordinates (r and z) function
Referenced by get_base_flow_dudx().
base_flow_p_fct_pt
void(* &)(const double& time, const Vector<double>& x, double& f) oomph::LinearisedAxisymmetricNavierStokesEquations::base_flow_p_fct_pt() inline
Access function for the base flow pressure pointer.
     {
      return Base_flow_p_fct_pt;
     }
Base_flow_p_fct_pt
void(* oomph::LinearisedAxisymmetricNavierStokesEquations::Base_flow_p_fct_pt) (const double &time, const Vector< double > &x, double &result) protected
Pointer to base flow solution (pressure) function.
Referenced by get_base_flow_p().
base_flow_u_fct_pt
void(*&)(const double& time, const Vector<double>& x, Vector<double>& f) oomph::LinearisedAxisymmetricNavierStokesEquations::base_flow_u_fct_pt() inline
Access function for the base flow solution pointer.
Access function for the base flow velocity pointer.
     {
      return Base_flow_u_fct_pt;
     }
Base_flow_u_fct_pt
void(* oomph::LinearisedAxisymmetricNavierStokesEquations::Base_flow_u_fct_pt)(const double &time, const Vector< double > &x, Vector< double > &result) protected
Pointer to base flow solution (velocity components) function.
Referenced by get_base_flow_u().
body_force_fct_pt
void(* &)(const double& time, const Vector<double>& x, Vector<double> & f) oomph::LinearisedAxisymmetricNavierStokesEquations::body_force_fct_pt() inline
Access function for the body-force pointer.
     {
      return Body_force_fct_pt;
     }
Body_force_fct_pt
void(* oomph::LinearisedAxisymmetricNavierStokesEquations::Body_force_fct_pt) (const double &time, const Vector< double > &x, Vector< double > &result) protected
Pointer to (base flow) body force function.
Referenced by get_body_force_base_flow().
Default_Azimuthal_Mode_Number_Value
static int oomph::LinearisedAxisymmetricNavierStokesEquations::Default_Azimuthal_Mode_Number_Value static private
Static default value for the azimuthal mode number (zero)
Referenced by LinearisedAxisymmetricNavierStokesEquations().
Default_Gravity_Vector
Vector< double > oomph::LinearisedAxisymmetricNavierStokesEquations::Default_Gravity_Vector static private
Static default value for the gravity vector (zero)
Referenced by LinearisedAxisymmetricNavierStokesEquations().
Default_Physical_Constant_Value
static double oomph::LinearisedAxisymmetricNavierStokesEquations::Default_Physical_Constant_Value static private
Static default value for the physical constants (all initialised to zero)
Referenced by LinearisedAxisymmetricNavierStokesEquations().
Default_Physical_Ratio_Value
static double oomph::LinearisedAxisymmetricNavierStokesEquations::Default_Physical_Ratio_Value static private
Initial value:
=
      1.0
Static default value for the physical ratios (all initialised to one)
Referenced by LinearisedAxisymmetricNavierStokesEquations().
Density_Ratio_pt
double * oomph::LinearisedAxisymmetricNavierStokesEquations::Density_Ratio_pt protected
Pointer to the density ratio (relative to the density used in the definition of the Reynolds number)
Referenced by density_ratio(), density_ratio_pt(), oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::further_build(), and LinearisedAxisymmetricNavierStokesEquations().
External_H_local_eqn
Vector<int> oomph::LinearisedAxisymmetricNavierStokesEquations::External_H_local_eqn protected
Array to hold the local eqn number information for the external data
Referenced by assign_additional_local_eqn_numbers().
External_node
Vector<unsigned> oomph::LinearisedAxisymmetricNavierStokesEquations::External_node protected
Vector to keep track of the external data associated with each bulk node
Referenced by nexternal_H_data().
G_pt
Vector<double>* oomph::LinearisedAxisymmetricNavierStokesEquations::G_pt protected
Pointer to global gravity Vector.
Referenced by g(), g_pt(), and LinearisedAxisymmetricNavierStokesEquations().
Gamma
static Vector< double > oomph::LinearisedAxisymmetricNavierStokesEquations::Gamma static
Vector to decide whether the stress-divergence form is used or not.
Linearised axisymmetric Navier–Stokes equations static data.
Navier–Stokes equations static data.
Referenced by fill_in_generic_residual_contribution_lin_axi_nst(), fill_in_generic_residual_contribution_linearised_axi_nst(), and oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_linearised_axi_nst().
Pressure_not_stored_at_node
static int oomph::LinearisedAxisymmetricNavierStokesEquations::Pressure_not_stored_at_node static private
Initial value:
=
    -100
Static "magic" number that indicates that the pressure is not stored at a node
Referenced by p_index_lin_axi_nst(), and p_index_linearised_axi_nst().
Re_pt
double * oomph::LinearisedAxisymmetricNavierStokesEquations::Re_pt protected
Pointer to global Reynolds number.
Referenced by oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::further_build(), LinearisedAxisymmetricNavierStokesEquations(), re(), and re_pt().
ReInvFr_pt
double* oomph::LinearisedAxisymmetricNavierStokesEquations::ReInvFr_pt protected
Pointer to global Reynolds number x inverse Froude number (= Bond number / Capillary number)
Referenced by LinearisedAxisymmetricNavierStokesEquations(), re_invfr(), and re_invfr_pt().
ReInvRo_pt
double* oomph::LinearisedAxisymmetricNavierStokesEquations::ReInvRo_pt protected
Pointer to global Reynolds number x inverse Rossby number (used when in a rotating frame)
Referenced by LinearisedAxisymmetricNavierStokesEquations(), re_invro(), and re_invro_pt().
ReSt_pt
double * oomph::LinearisedAxisymmetricNavierStokesEquations::ReSt_pt protected
Pointer to global Reynolds number x Strouhal number (=Womersley)
Referenced by oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::further_build(), LinearisedAxisymmetricNavierStokesEquations(), re_st(), and re_st_pt().
source_fct_pt
double(* &)(const double& time, const Vector<double>& x) oomph::LinearisedAxisymmetricNavierStokesEquations::source_fct_pt() inline
Access function for the source-function pointer.
     {
      return Source_fct_pt;
     }
Source_fct_pt
double(* oomph::LinearisedAxisymmetricNavierStokesEquations::Source_fct_pt) (const double &time, const Vector< double > &x) protected
Pointer to (base flow) volumetric source function.
Referenced by get_source_base_flow().
Viscosity_Ratio_pt
double * oomph::LinearisedAxisymmetricNavierStokesEquations::Viscosity_Ratio_pt protected
Pointer to the viscosity ratio (relative to the viscosity used in the definition of the Reynolds number)
Referenced by oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::further_build(), LinearisedAxisymmetricNavierStokesEquations(), viscosity_ratio(), and viscosity_ratio_pt().
The documentation for this class was generated from the following files:
demo_drivers/axisym_navier_stokes/counter_rotating_disks/linearised_axisym_navier_stokes_elements.h
demo_drivers/axisym_navier_stokes/counter_rotating_disks/linearised_axisym_navier_stokes_elements.cc