MercuryDPM: oomph::PMLQuadMeshBase< ELEMENT > Class Template Reference
oomph::PMLQuadMeshBase< ELEMENT > Class Template Reference
PML mesh class. Policy class for 2D PML meshes.
#include <pml_meshes.h>
Public Member Functions
PMLQuadMeshBase (const unsigned &n_pml_x, const unsigned &n_pml_y, const double &x_pml_start, const double &x_pml_end, const double &y_pml_start, const double &y_pml_end, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Create the underlying rectangular quad mesh.
void pml_locate_zeta (const Vector< double > &x, FiniteElement *&coarse_mesh_el_pt)
Public Member Functions inherited from oomph::RectangularQuadMesh< ELEMENT >
RectangularQuadMesh (const unsigned &nx, const unsigned &ny, const double &lx, const double &ly, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
RectangularQuadMesh (const unsigned &nx, const unsigned &ny, const double &xmin, const double &xmax, const double &ymin, const double &ymax, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
RectangularQuadMesh (const unsigned &nx, const unsigned &ny, const double &lx, const double &ly, const bool &periodic_in_x, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
RectangularQuadMesh (const unsigned &nx, const unsigned &ny, const double &xmin, const double &xmax, const double &ymin, const double &ymax, const bool &periodic_in_x, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
const unsigned & nx () const
Return number of elements in x direction.
const unsigned & ny () const
Return number of elements in y direction.
const double x_min () const
Return the minimum value of x coordinate.
const double x_max () const
Return the maximum value of x coordinate.
const double y_min () const
Return the minimum value of y coordinate.
const double y_max () const
Return the maximum value of y coordinate.
virtual void element_reorder ()
virtual double x_spacing_function (unsigned xelement, unsigned xnode, unsigned yelement, unsigned ynode)
virtual double y_spacing_function (unsigned xelement, unsigned xnode, unsigned yelement, unsigned ynode)
Public Member Functions inherited from oomph::QuadMeshBase
QuadMeshBase ()
Constructor (empty)
QuadMeshBase (const QuadMeshBase &node)=delete
Broken copy constructor.
void operator= (const QuadMeshBase &)=delete
Broken assignment operator.
virtual ~QuadMeshBase ()
Destructor (empty)
void setup_boundary_element_info ()
void setup_boundary_element_info (std::ostream &outfile)
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void node_update (const bool &update_all_solid_nodes=false)
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Protected Member Functions inherited from oomph::RectangularQuadMesh< ELEMENT >
void build_mesh (TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Generic mesh construction function: contains all the hard work.
RectangularQuadMesh (const unsigned &nx, const unsigned &ny, const double &xmin, const double &xmax, const double &ymin, const double &ymax, const bool &periodic_in_x, const bool &build, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Protected Attributes inherited from oomph::RectangularQuadMesh< ELEMENT >
unsigned Nx
Nx: number of elements in x-direction.
unsigned Ny
Ny: number of elements in y-direction.
unsigned Np
Np: number of (linear) points in the element.
double Xmin
Minimum value of x coordinate.
double Xmax
Maximum value of x coordinate.
double Ymin
Minimum value of y coordinate.
double Ymax
Maximum value of y coordinate.
bool Xperiodic
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Detailed Description
template<class ELEMENT>
class oomph::PMLQuadMeshBase< ELEMENT >
PML mesh class. Policy class for 2D PML meshes.
Constructor & Destructor Documentation
PMLQuadMeshBase()
template<class ELEMENT > oomph::PMLQuadMeshBase< ELEMENT >::PMLQuadMeshBase (const unsigned & n_pml_x, const unsigned & n_pml_y, const double & x_pml_start, const double & x_pml_end, const double & y_pml_start, const double & y_pml_end, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) inline
Constructor: Create the underlying rectangular quad mesh.
       : RectangularQuadMesh<ELEMENT>(n_pml_x,
                                      n_pml_y,
                                      x_pml_start,
                                      x_pml_end,
                                      y_pml_start,
                                      y_pml_end,
                                      time_stepper_pt)
     {
     }
Member Function Documentation
pml_locate_zeta()
template<class ELEMENT > void oomph::PMLQuadMeshBase< ELEMENT >::pml_locate_zeta (const Vector< double > & x, FiniteElement *& coarse_mesh_el_pt) inline virtual
Overloaded function to allow the user to locate an element in mesh given the (Eulerian) position of a point. Note, the result may be nonunique if the given point lies on the boundary of two elements in the mesh. Additionally, we assume that the PML mesh is axis aligned when deciding if the given point lies inside the mesh
Implements oomph::PMLMeshBase.
     {
       //------------------------------------------
       // Make sure the point lies inside the mesh:
       //------------------------------------------
       // Get the lower x limit of the mesh
       const double x_min = this->x_min();
       // Get the upper x limit of the mesh
       const double x_max = this->x_max();
       // Get the lower y limit of the mesh
       const double y_min = this->y_min();
       // Get the upper y limit of the mesh
       const double y_max = this->y_max();
       // Due to roundoff error we will choose a small tolerance which will be
       // used to determine whether or not the point lies in the mesh
       double tol = 1.0e-12;
       // Assuming the mesh is axis-aligned we merely need to check if the
       // x-coordinate of the input lies in the range [x_min,x_max] and the
       // y-coordinate of the input lies in the range [y_min,y_max]
       if ((x[0] < x_min - tol) || (x[0] > x_max + tol) ||
           (x[1] < y_min - tol) || (x[1] > y_max + tol))
       {
         // Open an output string stream
         std::ostringstream error_message_stream;
         // Create an error message
         error_message_stream << "Point does not lie in the mesh." << std::endl;
         // Throw the error message
         throw OomphLibError(error_message_stream.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
       //-----------------------------------------
       // Collect some information about the mesh:
       //-----------------------------------------
       // Find out how many elements there are in the x-direction
       const unsigned nx = this->nx();
       // Find out how many elements there are in the y-direction
       const unsigned ny = this->ny();
       // Find out how many nodes there are in one direction in each element
       unsigned nnode_1d = this->finite_element_pt(0)->nnode_1d();
       // Find out how many nodes there are in each element
       unsigned nnode = this->finite_element_pt(0)->nnode();
       // Create a pointer to store the element pointer as a FiniteElement
       FiniteElement* el_pt = 0;
       // Vector to store the coordinate of each element corner node which
       // lies on the bottom boundary of the mesh and varies, i.e. if we're
       // on the bottom boundary of the PML mesh then the y-coordinate will
       // be fixed therefore we need only store the x-coordinates of the
       // corner nodes of each element attached to this boundary
       Vector<double> bottom_boundary_x_coordinates(nx + 1, 0.0);
       // Vector to store the coordinate of each element corner node which lies
       // on the right boundary of the mesh and varies
       Vector<double> right_boundary_y_coordinates(ny + 1, 0.0);
       // Recall, we already know the start and end coordinates of the mesh
       // in the x-direction so we can assign these entries straight away.
       // Note, these values are exactly the same as those had we instead
       // considered the upper boundary so it is only necessary to store
       // the information of the one of these boundaries. A similar argument
       // holds for the left and right boundaries.
       // The first entry of bottom_boundary_x_coordinates is:
       bottom_boundary_x_coordinates[0] = x_min;
       // The last entry is:
       bottom_boundary_x_coordinates[nx] = x_max;
       // The first entry of right_boundary_y_coordinates is:
       right_boundary_y_coordinates[0] = y_min;
       // The last entry is:
       right_boundary_y_coordinates[ny] = y_max;
       // To collect the remaining entries we need to loop over all of the
       // elements on the bottom boundary and collect the x-coordinate of
       // the bottom right node in the element. To avoid assigning the
       // last entry twice we ignore the last element.
       // Store the lower boundary ID
       unsigned lower_boundary_id = 0;
       // Store the right boundary ID
       unsigned right_boundary_id = 1;
       // Loop over the elements on the bottom boundary
       for (unsigned i = 0; i < nx; i++)
       {
         // Assign the element pointer
         el_pt = this->boundary_element_pt(lower_boundary_id, i);
         // Store the x-coordinate of the bottom right node in this element
         bottom_boundary_x_coordinates[i + 1] =
           el_pt->node_pt(nnode_1d - 1)->x(0);
       }
       // To collect the remaining entries we need to loop over all of the
       // elements on the right boundary and collect the y-coordinate of
       // the top right node in the element. To avoid assigning the
       // last entry twice we ignore the last element.
       // Loop over the elements on the bottom boundary
       for (unsigned i = 0; i < ny; i++)
       {
         // Assign the element pointer
         el_pt = this->boundary_element_pt(right_boundary_id, i);
         // Store the y-coordinate of the top right node in this element
         right_boundary_y_coordinates[i + 1] = el_pt->node_pt(nnode - 1)->x(1);
       }
       //---------------------------
       // Find the matching element:
       //---------------------------
       // Boolean variable to indicate that the ID of the element in the
       // x-direction has been found. Note, the value of this ID must lie
       // in the range [0,nx]
       bool element_x_id_has_been_found = false;
       // Boolean variable to indicate that the ID of the element in the
       // y-direction has been found. Note, the value of this ID must lie
       // in the range [0,ny]
       bool element_y_id_has_been_found = false;
       // Initialise the ID of the element in the x-direction
       unsigned element_x_id = 0;
       // Initialise the ID of the element in the y-direction
       unsigned element_y_id = 0;
       // Loop over all of the entries in bottom_boundary_x_coordinates
       for (unsigned i = 0; i < nx; i++)
       {
         // Check if the x-coordinate of the input lies in this interval
         if ((x[0] >= bottom_boundary_x_coordinates[i]) &&
             (x[0] <= bottom_boundary_x_coordinates[i + 1]))
         {
           // The point lies in the i-th interval so the element ID is i
           element_x_id = i;
           // Indicate that the element ID has been found
           element_x_id_has_been_found = true;
         }
       } // for (unsigned i=0;i<nx;i++)
       // If the element ID hasn't been found
       if (!element_x_id_has_been_found)
       {
         // Open an output string stream
         std::ostringstream error_message_stream;
         // Create an error message
         error_message_stream << "The ID of the element in the x-direction "
                              << "has not been found." << std::endl;
         // Throw the error message
         throw OomphLibError(error_message_stream.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
       // Loop over all of the entries in right_boundary_y_coordinates
       for (unsigned i = 0; i < ny; i++)
       {
         // Check if the y-coordinate of the input lies in this interval
         if ((x[1] >= right_boundary_y_coordinates[i]) &&
             (x[1] <= right_boundary_y_coordinates[i + 1]))
         {
           // The point lies in the i-th interval so the element ID is i
           element_y_id = i;
           // Indicate that the element ID has been found
           element_y_id_has_been_found = true;
         }
       } // for (unsigned i=0;i<ny;i++)
       // If the element ID hasn't been found
       if (!element_y_id_has_been_found)
       {
         // Open an output string stream
         std::ostringstream error_message_stream;
         // Create an error message
         error_message_stream << "The ID of the element in the y-direction "
                              << "has not been found." << std::endl;
         // Throw the error message
         throw OomphLibError(error_message_stream.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
       // Calculate the element number in the mesh
       unsigned el_id = element_y_id * nx + element_x_id;
       // Set the pointer to this element
       coarse_mesh_el_pt = dynamic_cast<FiniteElement*>(this->element_pt(el_id));
     } // End of pml_locate_zeta
References oomph::Mesh::boundary_element_pt(), oomph::Mesh::element_pt(), oomph::Mesh::finite_element_pt(), i, oomph::FiniteElement::nnode(), oomph::Mesh::nnode(), oomph::FiniteElement::nnode_1d(), oomph::FiniteElement::node_pt(), oomph::RectangularQuadMesh< ELEMENT >::nx(), oomph::RectangularQuadMesh< ELEMENT >::ny(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, plotDoE::x, oomph::Node::x(), oomph::RectangularQuadMesh< ELEMENT >::x_max(), oomph::RectangularQuadMesh< ELEMENT >::x_min(), oomph::RectangularQuadMesh< ELEMENT >::y_max(), and oomph::RectangularQuadMesh< ELEMENT >::y_min().
The documentation for this class was generated from the following file:
pml_meshes.h