MercuryDPM: PossibleContactList Class Reference
PossibleContactList Class Reference
Manages the linked list of PossibleContact.
#include <PossibleContactList.h>
Public Member Functions
PossibleContactList ()
Constructor, sets the firstPossibleContact_ to a nullptr since there are no possible interactions yet.
void add_PossibleContact (BaseParticle *P1, BaseParticle *P2)
Add the possible contact between two given BaseParticle to the linked list.
void remove_ParticlePosibleContacts (BaseParticle *P)
Remove all PossibleContact with given BaseParticle from the linked list.
void write (std::ostream &os) const
Write all PossibleContact to the given ostream.
PossibleContact * getFirstPossibleContact ()
Get the front of the linked list of PossibleContact.
Private Attributes
PossibleContact * firstPossibleContact_
The pointer to the first PossibleContact on the linked list.
Detailed Description
Manages the linked list of PossibleContact.
Please note that the PossibleContact at the front of the list is the one that is added last, so firstPossibleContact_ is the PossibleContact that has been added last.
Todo:
Look at the memory management of PossibleContactList. Maybe a destructor that takes out all remaining PossibleContact? Or is there a Handler that calls remove_ParticlePosibleContacts for all particles?
Restart-tests are not working with CONTACT_LIST_HGRID turned on, so either finish the ContactList-related code, or get rid of it. If we keep it, clean up the code, in particular the naming-convention.
Constructor & Destructor Documentation
PossibleContactList()
PossibleContactList::PossibleContactList () inline
Constructor, sets the firstPossibleContact_ to a nullptr since there are no possible interactions yet.
     {
         firstPossibleContact_ = nullptr;
         logger(DEBUG, "PossibleContactList() constructor finished.");
     }
References DEBUG, firstPossibleContact_, and logger.
Member Function Documentation
add_PossibleContact()
void PossibleContactList::add_PossibleContact (BaseParticle * P1, BaseParticle * P2) inline
Add the possible contact between two given BaseParticle to the linked list.
Parameters
[in] P1 A pointer to the first BaseParticle we want to make a PossibleContact with.
[in] P2 A pointer to the second BaseParticle we want to make a PossibleContact with.
If there is a PossibleContact between two BaseParticle, make a new PossibleContact and put it in front of the linked list. Then assign the newly made PossibleContact to the former front of the linked list.
     {
         firstPossibleContact_ = new PossibleContact(P1, P2, firstPossibleContact_, P1->getFirstPossibleContact(),
                                                     P2->getFirstPossibleContact());
         P1->setFirstPossibleContact(firstPossibleContact_);
         P2->setFirstPossibleContact(firstPossibleContact_);
         if (firstPossibleContact_->getNext())
             firstPossibleContact_->getNext()->setPreviousPosition(firstPossibleContact_);
         if (firstPossibleContact_->getNext1())
             firstPossibleContact_->getNext1()->setPreviousPosition(P1, firstPossibleContact_);
         if (firstPossibleContact_->getNext2())
             firstPossibleContact_->getNext2()->setPreviousPosition(P2, firstPossibleContact_);
         logger(VERBOSE, "Added new possible contact between particles % and % ", P1->getIndex(), P2->getIndex());
     }
References firstPossibleContact_, BaseObject::getIndex(), PossibleContact::getNext(), PossibleContact::getNext1(), PossibleContact::getNext2(), logger, PossibleContact::setPreviousPosition(), and VERBOSE.
getFirstPossibleContact()
PossibleContact* PossibleContactList::getFirstPossibleContact () inline
Get the front of the linked list of PossibleContact.
Returns
A pointer to the first PossibleContact on the linked list.
     {
         return firstPossibleContact_;
     }
References firstPossibleContact_.
remove_ParticlePosibleContacts()
void PossibleContactList::remove_ParticlePosibleContacts (BaseParticle * P) inline
Remove all PossibleContact with given BaseParticle from the linked list.
Parameters
[in] P A pointer to the BaseParticle we want to remove all PossibleContact for.
To remove all PossibleContact with given BaseParticle from the linked list of all PossibleContact, go through all PossibleContact that are given as a list for the given BaseParticle, and then remove it from the global list by correcting all pointers and then delete the PossibleContact.
     {
         logger(VERBOSE, "Removing all contacts of particle %.", P->getIndex());
         //The BaseParticle that shares a PossibleContact with P.
         BaseParticle* O;
         //The next possible contact for P.
         PossibleContact* Next;
         //The current possible contact for P.
         PossibleContact* Curr = P->getFirstPossibleContact();
         while (Curr != nullptr)
         {
             logger(VERBOSE, "Removing possible contacts index = % between particles % and %.", Curr->getIndex(),
                    Curr->getP1()->getIndex(), Curr->getP2()->getIndex());
             Next = Curr->getNext(P);
             O = Curr->getOtherParticle(P);
             //Set the pointers of the next global possible contact.
             if (Curr->getNext())
                 Curr->getNext()->setPreviousPosition(Curr->getPrevious());
             //Set the pointers of the previous possible contact.
             if (Curr->getPrevious())
                 Curr->getPrevious()->setNextPosition(Curr->getNext());
             else
                 firstPossibleContact_ = Curr->getNext();
             //Set the pointers of the other object of the possible contact.
             if (Curr->getNext(O))
                 Curr->getNext(O)->setPreviousPosition(O, Curr->getPrevious(O));
             if (Curr->getPrevious(O))
                 Curr->getPrevious(O)->setNextPosition(O, Curr->getNext(O));
             else
                 O->setFirstPossibleContact(Curr->getNext(O));
             //Delete the possible contact and update the the pointer Curr to the
             //next possible contact with P.
             delete Curr;
             Curr = Next;
         }
         P->setFirstPossibleContact(nullptr);
     }
References firstPossibleContact_, PossibleContact::getIndex(), BaseObject::getIndex(), PossibleContact::getNext(), PossibleContact::getOtherParticle(), PossibleContact::getP1(), PossibleContact::getP2(), PossibleContact::getPrevious(), logger, O, Global_Physical_Variables::P, PossibleContact::setNextPosition(), PossibleContact::setPreviousPosition(), and VERBOSE.
write()
void PossibleContactList::write (std::ostream & os) const inline
Write all PossibleContact to the given ostream.
Parameters
[in,out] os The output stream the PossibleContactList must be written to.
     {
         os << "Possible contacts are: " << std::endl;
         PossibleContact* it = firstPossibleContact_;
         while (it != nullptr)
         {
             os << *it << std::endl;
             it = it->getNext();
         }
     }
References firstPossibleContact_, and PossibleContact::getNext().
Member Data Documentation
firstPossibleContact_
PossibleContact* PossibleContactList::firstPossibleContact_ private
The pointer to the first PossibleContact on the linked list.
Please note that this is the PossibleContact that has been added last.
Referenced by add_PossibleContact(), getFirstPossibleContact(), PossibleContactList(), remove_ParticlePosibleContacts(), and write().
The documentation for this class was generated from the following file:
PossibleContactList.h