MercuryDPM: MatrixReplacement Class Reference
MatrixReplacement Class Reference
Public Types
enum { ColsAtCompileTime = Eigen::Dynamic , MaxColsAtCompileTime = Eigen::Dynamic , IsRowMajor = false }
typedef double Scalar
typedef double RealScalar
typedef int StorageIndex
Public Types inherited from Eigen::EigenBase< MatrixReplacement >
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< MatrixReplacement >::StorageKind StorageKind
Public Member Functions
Index rows () const
Index cols () const
template<typename Rhs >
Eigen::Product< MatrixReplacement, Rhs, Eigen::AliasFreeProduct > operator* (const Eigen::MatrixBase< Rhs > &x) const
MatrixReplacement ()
void attachMyMatrix (const SparseMatrix< double > &mat)
const SparseMatrix< double > my_matrix () const
Public Member Functions inherited from Eigen::EigenBase< MatrixReplacement >
constexpr EIGEN_DEVICE_FUNC MatrixReplacement & derived ()
constexpr EIGEN_DEVICE_FUNC const MatrixReplacement & derived () const
EIGEN_DEVICE_FUNC MatrixReplacement & const_cast_derived () const
EIGEN_DEVICE_FUNC const MatrixReplacement & const_derived () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index size () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< MatrixReplacement, Device > device (Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< const MatrixReplacement, Device > device (Device &device) const
Private Attributes
const SparseMatrix< double > * mp_mat
Member Typedef Documentation
RealScalar
typedef double MatrixReplacement::RealScalar
Scalar
typedef double MatrixReplacement::Scalar
StorageIndex
typedef int MatrixReplacement::StorageIndex
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
ColsAtCompileTime
MaxColsAtCompileTime
IsRowMajor
 { ColsAtCompileTime = Eigen::Dynamic, MaxColsAtCompileTime = Eigen::Dynamic, IsRowMajor = false };
Constructor & Destructor Documentation
MatrixReplacement()
MatrixReplacement::MatrixReplacement () inline
 : mp_mat(0) {}
Member Function Documentation
attachMyMatrix()
void MatrixReplacement::attachMyMatrix (const SparseMatrix< double > & mat) inline
 { mp_mat = &mat; }
References mp_mat.
cols()
Index MatrixReplacement::cols () const inline
 { return mp_mat->cols(); }
References Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::cols(), and mp_mat.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), Eigen::internal::generic_product_impl< MatrixReplacement, Rhs, SparseShape, DenseShape, GemvProduct >::scaleAndAddTo(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
my_matrix()
const SparseMatrix<double> MatrixReplacement::my_matrix () const inline
 { return *mp_mat; }
References mp_mat.
Referenced by Eigen::internal::generic_product_impl< MatrixReplacement, Rhs, SparseShape, DenseShape, GemvProduct >::scaleAndAddTo().
operator*()
template<typename Rhs > Eigen::Product<MatrixReplacement, Rhs, Eigen::AliasFreeProduct> MatrixReplacement::operator* (const Eigen::MatrixBase< Rhs > & x) const inline
{
     return Eigen::Product<MatrixReplacement, Rhs, Eigen::AliasFreeProduct>(*this, x.derived());
   }
References plotDoE::x.
rows()
Index MatrixReplacement::rows () const inline
 { return mp_mat->rows(); }
References mp_mat, and Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::rows().
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
Member Data Documentation
mp_mat
const SparseMatrix<double>* MatrixReplacement::mp_mat private
Referenced by attachMyMatrix(), cols(), my_matrix(), and rows().
The documentation for this class was generated from the following file:
matrixfree_cg.cpp