MercuryDPM: Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived > Class Template Reference
Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived > Class Template Reference
#include <StlIterators.h>
Public Types
typedef Index difference_type
typedef std::random_access_iterator_tag iterator_category
Public Member Functions
indexed_based_stl_reverse_iterator_base ()
indexed_based_stl_reverse_iterator_base (XprType &xpr, Index index)
indexed_based_stl_reverse_iterator_base (const non_const_iterator &other)
indexed_based_stl_reverse_iterator_base & operator= (const non_const_iterator &other)
Derived & operator++ ()
Derived & operator-- ()
Derived operator++ (int)
Derived operator-- (int)
Derived & operator+= (Index b)
Derived & operator-= (Index b)
difference_type operator- (const indexed_based_stl_reverse_iterator_base &other) const
difference_type operator- (const other_iterator &other) const
bool operator== (const indexed_based_stl_reverse_iterator_base &other) const
bool operator!= (const indexed_based_stl_reverse_iterator_base &other) const
bool operator< (const indexed_based_stl_reverse_iterator_base &other) const
bool operator<= (const indexed_based_stl_reverse_iterator_base &other) const
bool operator> (const indexed_based_stl_reverse_iterator_base &other) const
bool operator>= (const indexed_based_stl_reverse_iterator_base &other) const
bool operator== (const other_iterator &other) const
bool operator!= (const other_iterator &other) const
bool operator< (const other_iterator &other) const
bool operator<= (const other_iterator &other) const
bool operator> (const other_iterator &other) const
bool operator>= (const other_iterator &other) const
Protected Types
typedef indexed_based_stl_iterator_traits< Derived > traits
typedef traits::XprType XprType
typedef indexed_based_stl_reverse_iterator_base< typename traits::non_const_iterator > non_const_iterator
typedef indexed_based_stl_reverse_iterator_base< typename traits::const_iterator > const_iterator
typedef std::conditional_t< internal::is_const< XprType >::value, non_const_iterator, const_iterator > other_iterator
Protected Member Functions
Derived & derived ()
const Derived & derived () const
Protected Attributes
XprType * mp_xpr
Index m_index
Friends
class indexed_based_stl_reverse_iterator_base< typename traits::const_iterator >
class indexed_based_stl_reverse_iterator_base< typename traits::non_const_iterator >
Derived operator+ (const indexed_based_stl_reverse_iterator_base &a, Index b)
Derived operator- (const indexed_based_stl_reverse_iterator_base &a, Index b)
Derived operator+ (Index a, const indexed_based_stl_reverse_iterator_base &b)
Derived operator- (Index a, const indexed_based_stl_reverse_iterator_base &b)
Member Typedef Documentation
const_iterator
template<typename Derived > typedef indexed_based_stl_reverse_iterator_base<typename traits::const_iterator> Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::const_iterator protected
difference_type
template<typename Derived > typedef Index Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::difference_type
iterator_category
template<typename Derived > typedef std::random_access_iterator_tag Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::iterator_category
non_const_iterator
template<typename Derived > typedef indexed_based_stl_reverse_iterator_base<typename traits::non_const_iterator> Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::non_const_iterator protected
other_iterator
template<typename Derived > typedef std::conditional_t<internal::is_const<XprType>::value, non_const_iterator, const_iterator> Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::other_iterator protected
traits
template<typename Derived > typedef indexed_based_stl_iterator_traits<Derived> Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::traits protected
XprType
template<typename Derived > typedef traits::XprType Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::XprType protected
Constructor & Destructor Documentation
indexed_based_stl_reverse_iterator_base() [1/3]
template<typename Derived > Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::indexed_based_stl_reverse_iterator_base () inline
 : mp_xpr(0), m_index(0) {}
indexed_based_stl_reverse_iterator_base() [2/3]
template<typename Derived > Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::indexed_based_stl_reverse_iterator_base (XprType & xpr, Index index) inline
 : mp_xpr(&xpr), m_index(index) {}
indexed_based_stl_reverse_iterator_base() [3/3]
template<typename Derived > Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::indexed_based_stl_reverse_iterator_base (const non_const_iterator & other) inline
       : mp_xpr(other.mp_xpr), m_index(other.m_index) {}
Member Function Documentation
derived() [1/2]
template<typename Derived > Derived& Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::derived () inline protected
 { return static_cast<Derived&>(*this); }
Referenced by Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator++(), Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator+=(), Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator--(), and Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator-=().
derived() [2/2]
template<typename Derived > const Derived& Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::derived () const inline protected
 { return static_cast<const Derived&>(*this); }
operator!=() [1/2]
template<typename Derived > bool Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator!= (const indexed_based_stl_reverse_iterator_base< Derived > & other) const inline
{
     eigen_assert(mp_xpr == other.mp_xpr);
     return m_index != other.m_index;
   }
References eigen_assert, Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::m_index, and Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::mp_xpr.
operator!=() [2/2]
template<typename Derived > bool Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator!= (const other_iterator & other) const inline
{
     eigen_assert(mp_xpr == other.mp_xpr);
     return m_index != other.m_index;
   }
References eigen_assert, Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::m_index, and Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::mp_xpr.
operator++() [1/2]
template<typename Derived > Derived& Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator++ () inline
{
     --m_index;
     return derived();
   }
References Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::derived(), and Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::m_index.
Referenced by Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator++().
operator++() [2/2]
template<typename Derived > Derived Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator++ (int) inline
{
     Derived prev(derived());
     operator++();
     return prev;
   }
References Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::derived(), and Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator++().
operator+=()
template<typename Derived > Derived& Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator+= (Index b) inline
{
     m_index -= b;
     return derived();
   }
References b, Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::derived(), and Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::m_index.
operator-() [1/2]
template<typename Derived > difference_type Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator- (const indexed_based_stl_reverse_iterator_base< Derived > & other) const inline
{
     eigen_assert(mp_xpr == other.mp_xpr);
     return other.m_index - m_index;
   }
References eigen_assert, Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::m_index, and Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::mp_xpr.
operator-() [2/2]
template<typename Derived > difference_type Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator- (const other_iterator & other) const inline
{
     eigen_assert(mp_xpr == other.mp_xpr);
     return other.m_index - m_index;
   }
References eigen_assert, Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::m_index, and Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::mp_xpr.
operator--() [1/2]
template<typename Derived > Derived& Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator-- () inline
{
     ++m_index;
     return derived();
   }
References Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::derived(), and Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::m_index.
Referenced by Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator--().
operator--() [2/2]
template<typename Derived > Derived Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator-- (int) inline
{
     Derived prev(derived());
     operator--();
     return prev;
   }
References Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::derived(), and Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator--().
operator-=()
template<typename Derived > Derived& Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator-= (Index b) inline
{
     m_index += b;
     return derived();
   }
References b, Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::derived(), and Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::m_index.
operator<() [1/2]
template<typename Derived > bool Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator< (const indexed_based_stl_reverse_iterator_base< Derived > & other) const inline
{
     eigen_assert(mp_xpr == other.mp_xpr);
     return m_index > other.m_index;
   }
References eigen_assert, Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::m_index, and Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::mp_xpr.
operator<() [2/2]
template<typename Derived > bool Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator< (const other_iterator & other) const inline
{
     eigen_assert(mp_xpr == other.mp_xpr);
     return m_index > other.m_index;
   }
References eigen_assert, Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::m_index, and Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::mp_xpr.
operator<=() [1/2]
template<typename Derived > bool Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator<= (const indexed_based_stl_reverse_iterator_base< Derived > & other) const inline
{
     eigen_assert(mp_xpr == other.mp_xpr);
     return m_index >= other.m_index;
   }
References eigen_assert, Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::m_index, and Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::mp_xpr.
operator<=() [2/2]
template<typename Derived > bool Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator<= (const other_iterator & other) const inline
{
     eigen_assert(mp_xpr == other.mp_xpr);
     return m_index >= other.m_index;
   }
References eigen_assert, Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::m_index, and Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::mp_xpr.
operator=()
template<typename Derived > indexed_based_stl_reverse_iterator_base& Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator= (const non_const_iterator & other) inline
{
     mp_xpr = other.mp_xpr;
     m_index = other.m_index;
     return *this;
   }
References Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::m_index, and Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::mp_xpr.
operator==() [1/2]
template<typename Derived > bool Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator== (const indexed_based_stl_reverse_iterator_base< Derived > & other) const inline
{
     eigen_assert(mp_xpr == other.mp_xpr);
     return m_index == other.m_index;
   }
References eigen_assert, Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::m_index, and Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::mp_xpr.
operator==() [2/2]
template<typename Derived > bool Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator== (const other_iterator & other) const inline
{
     eigen_assert(mp_xpr == other.mp_xpr);
     return m_index == other.m_index;
   }
References eigen_assert, Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::m_index, and Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::mp_xpr.
operator>() [1/2]
template<typename Derived > bool Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator> (const indexed_based_stl_reverse_iterator_base< Derived > & other) const inline
{
     eigen_assert(mp_xpr == other.mp_xpr);
     return m_index < other.m_index;
   }
References eigen_assert, Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::m_index, and Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::mp_xpr.
operator>() [2/2]
template<typename Derived > bool Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator> (const other_iterator & other) const inline
{
     eigen_assert(mp_xpr == other.mp_xpr);
     return m_index < other.m_index;
   }
References eigen_assert, Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::m_index, and Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::mp_xpr.
operator>=() [1/2]
template<typename Derived > bool Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator>= (const indexed_based_stl_reverse_iterator_base< Derived > & other) const inline
{
     eigen_assert(mp_xpr == other.mp_xpr);
     return m_index <= other.m_index;
   }
References eigen_assert, Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::m_index, and Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::mp_xpr.
operator>=() [2/2]
template<typename Derived > bool Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator>= (const other_iterator & other) const inline
{
     eigen_assert(mp_xpr == other.mp_xpr);
     return m_index <= other.m_index;
   }
References eigen_assert, Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::m_index, and Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::mp_xpr.
Friends And Related Function Documentation
indexed_based_stl_reverse_iterator_base< typename traits::const_iterator >
template<typename Derived > friend class indexed_based_stl_reverse_iterator_base< typename traits::const_iterator > friend
indexed_based_stl_reverse_iterator_base< typename traits::non_const_iterator >
template<typename Derived > friend class indexed_based_stl_reverse_iterator_base< typename traits::non_const_iterator > friend
operator+ [1/2]
template<typename Derived > Derived operator+ (const indexed_based_stl_reverse_iterator_base< Derived > & a, Index b) friend
{
     Derived ret(a.derived());
     ret += b;
     return ret;
   }
operator+ [2/2]
template<typename Derived > Derived operator+ (Index a, const indexed_based_stl_reverse_iterator_base< Derived > & b) friend
{
     Derived ret(b.derived());
     ret += a;
     return ret;
   }
operator- [1/2]
template<typename Derived > Derived operator- (const indexed_based_stl_reverse_iterator_base< Derived > & a, Index b) friend
{
     Derived ret(a.derived());
     ret -= b;
     return ret;
   }
operator- [2/2]
template<typename Derived > Derived operator- (Index a, const indexed_based_stl_reverse_iterator_base< Derived > & b) friend
{
     Derived ret(b.derived());
     ret -= a;
     return ret;
   }
Member Data Documentation
m_index
template<typename Derived > Index Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::m_index protected
Referenced by Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator!=(), Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator++(), Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator+=(), Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator-(), Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator--(), Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator-=(), Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator<(), Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator<=(), Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator=(), Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator==(), Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator>(), and Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator>=().
mp_xpr
template<typename Derived > XprType* Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::mp_xpr protected
Referenced by Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator!=(), Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator-(), Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator<(), Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator<=(), Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator=(), Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator==(), Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator>(), and Eigen::internal::indexed_based_stl_reverse_iterator_base< Derived >::operator>=().
The documentation for this class was generated from the following file:
StlIterators.h