MercuryDPM: Eigen::TriangularBase< Derived > Class Template Reference
Eigen::TriangularBase< Derived > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
Base class for triangular part in a matrix.
#include <TriangularMatrix.h>
Public Types
enum {
Mode = internal::traits<Derived>::Mode , RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime , ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime , MaxRowsAtCompileTime = internal::traits<Derived>::MaxRowsAtCompileTime ,
MaxColsAtCompileTime = internal::traits<Derived>::MaxColsAtCompileTime , SizeAtCompileTime = (internal::size_of_xpr_at_compile_time<Derived>::ret) , MaxSizeAtCompileTime
}
typedef internal::traits< Derived >::Scalar Scalar
typedef internal::traits< Derived >::StorageKind StorageKind
typedef internal::traits< Derived >::StorageIndex StorageIndex
typedef internal::traits< Derived >::FullMatrixType DenseMatrixType
typedef DenseMatrixType DenseType
typedef Derived const & Nested
Public Types inherited from Eigen::EigenBase< Derived >
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< Derived >::StorageKind StorageKind
Public Member Functions
EIGEN_DEVICE_FUNC TriangularBase ()
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index outerStride () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index innerStride () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC void resize (Index rows, Index cols)
EIGEN_DEVICE_FUNC Scalar coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC Scalar & coeffRef (Index row, Index col)
template<typename Other >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void copyCoeff (Index row, Index col, Other &other)
EIGEN_DEVICE_FUNC Scalar operator() (Index row, Index col) const
EIGEN_DEVICE_FUNC Scalar & operator() (Index row, Index col)
EIGEN_DEVICE_FUNC const Derived & derived () const
EIGEN_DEVICE_FUNC Derived & derived ()
template<typename DenseDerived >
EIGEN_DEVICE_FUNC void evalTo (MatrixBase< DenseDerived > &other) const
template<typename DenseDerived >
EIGEN_DEVICE_FUNC void evalToLazy (MatrixBase< DenseDerived > &other) const
EIGEN_DEVICE_FUNC DenseMatrixType toDenseMatrix () const
Public Member Functions inherited from Eigen::EigenBase< Derived >
constexpr EIGEN_DEVICE_FUNC Derived & derived ()
constexpr EIGEN_DEVICE_FUNC const Derived & derived () const
EIGEN_DEVICE_FUNC Derived & const_cast_derived () const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index size () const EIGEN_NOEXCEPT
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
template<typename Device >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< Derived, Device > device (Device &device)
template<typename Device >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< const Derived, Device > device (Device &device) const
Protected Member Functions
void check_coordinates (Index row, Index col) const
void check_coordinates_internal (Index, Index) const
Detailed Description
template<typename Derived>
class Eigen::TriangularBase< Derived >
Base class for triangular part in a matrix.
Member Typedef Documentation
DenseMatrixType
template<typename Derived > typedef internal::traits<Derived>::FullMatrixType Eigen::TriangularBase< Derived >::DenseMatrixType
DenseType
template<typename Derived > typedef DenseMatrixType Eigen::TriangularBase< Derived >::DenseType
Nested
template<typename Derived > typedef Derived const& Eigen::TriangularBase< Derived >::Nested
Scalar
template<typename Derived > typedef internal::traits<Derived>::Scalar Eigen::TriangularBase< Derived >::Scalar
StorageIndex
template<typename Derived > typedef internal::traits<Derived>::StorageIndex Eigen::TriangularBase< Derived >::StorageIndex
StorageKind
template<typename Derived > typedef internal::traits<Derived>::StorageKind Eigen::TriangularBase< Derived >::StorageKind
Member Enumeration Documentation
anonymous enum
template<typename Derived > anonymous enum
Enumerator
Mode
RowsAtCompileTime
ColsAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
SizeAtCompileTime
This is equal to the number of coefficients, i.e. the number of rows times the number of columns, or to Dynamic if this is not known at compile-time.
See also
RowsAtCompileTime, ColsAtCompileTime
MaxSizeAtCompileTime
        {
     Mode = internal::traits<Derived>::Mode,
     RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime,
     ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime,
     MaxRowsAtCompileTime = internal::traits<Derived>::MaxRowsAtCompileTime,
     MaxColsAtCompileTime = internal::traits<Derived>::MaxColsAtCompileTime,
     SizeAtCompileTime = (internal::size_of_xpr_at_compile_time<Derived>::ret),
     MaxSizeAtCompileTime = internal::size_at_compile_time(internal::traits<Derived>::MaxRowsAtCompileTime,
                                                           internal::traits<Derived>::MaxColsAtCompileTime)
   };
Constructor & Destructor Documentation
TriangularBase()
template<typename Derived > EIGEN_DEVICE_FUNC Eigen::TriangularBase< Derived >::TriangularBase () inline
{
     eigen_assert(!((int(Mode) & int(UnitDiag)) && (int(Mode) & int(ZeroDiag))));
   }
References eigen_assert, Eigen::TriangularBase< Derived >::Mode, Eigen::UnitDiag, and Eigen::ZeroDiag.
Member Function Documentation
check_coordinates()
template<typename Derived > void Eigen::TriangularBase< Derived >::check_coordinates (Index row, Index col) const inline protected
{
     EIGEN_ONLY_USED_FOR_DEBUG(row);
     EIGEN_ONLY_USED_FOR_DEBUG(col);
     eigen_assert(col >= 0 && col < cols() && row >= 0 && row < rows());
     const int mode = int(Mode) & ~SelfAdjoint;
     EIGEN_ONLY_USED_FOR_DEBUG(mode);
     eigen_assert((mode == Upper && col >= row) || (mode == Lower && col <= row) ||
                  ((mode == StrictlyUpper || mode == UnitUpper) && col > row) ||
                  ((mode == StrictlyLower || mode == UnitLower) && col < row));
   }
References col(), Eigen::TriangularBase< Derived >::cols(), eigen_assert, EIGEN_ONLY_USED_FOR_DEBUG, int(), Eigen::Lower, Eigen::TriangularBase< Derived >::Mode, row(), Eigen::TriangularBase< Derived >::rows(), Eigen::SelfAdjoint, Eigen::StrictlyLower, Eigen::StrictlyUpper, Eigen::UnitLower, Eigen::UnitUpper, and Eigen::Upper.
Referenced by Eigen::TriangularBase< Derived >::operator()().
check_coordinates_internal()
template<typename Derived > void Eigen::TriangularBase< Derived >::check_coordinates_internal (Index , Index) const inline protected
 {}
Referenced by Eigen::SelfAdjointView< MatrixType_, UpLo >::coeff(), and Eigen::SelfAdjointView< MatrixType_, UpLo >::coeffRef().
coeff()
template<typename Derived > EIGEN_DEVICE_FUNC Scalar Eigen::TriangularBase< Derived >::coeff (Index row, Index col) const inline
 { return derived().coeff(row, col); }
References col(), Eigen::TriangularBase< Derived >::derived(), and row().
Referenced by Eigen::TriangularBase< Derived >::operator()().
coeffRef()
template<typename Derived > EIGEN_DEVICE_FUNC Scalar& Eigen::TriangularBase< Derived >::coeffRef (Index row, Index col) inline
 { return derived().coeffRef(row, col); }
References col(), Eigen::TriangularBase< Derived >::derived(), and row().
Referenced by Eigen::TriangularBase< Derived >::operator()().
cols()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::TriangularBase< Derived >::cols () const inline
 { return derived().cols(); }
References Eigen::TriangularBase< Derived >::derived().
Referenced by gdb.printers._MatrixEntryIterator::__next__(), Eigen::TriangularBase< Derived >::check_coordinates(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), Eigen::TriangularBase< Derived >::resize(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and Eigen::TriangularBase< Derived >::toDenseMatrix().
copyCoeff()
template<typename Derived > template<typename Other > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TriangularBase< Derived >::copyCoeff (Index row, Index col, Other & other) inline
See also
MatrixBase::copyCoeff(row,col)
{
     derived().coeffRef(row, col) = other.coeff(row, col);
   }
References col(), Eigen::TriangularBase< Derived >::derived(), and row().
derived() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC Derived& Eigen::TriangularBase< Derived >::derived () inline
 { return *static_cast<Derived*>(this); }
derived() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC const Derived& Eigen::TriangularBase< Derived >::derived () const inline
 { return *static_cast<const Derived*>(this); }
Referenced by Eigen::TriangularBase< Derived >::coeff(), Eigen::TriangularBase< Derived >::coeffRef(), Eigen::TriangularBase< Derived >::cols(), Eigen::TriangularBase< Derived >::copyCoeff(), Eigen::TriangularBase< Derived >::innerStride(), Eigen::TriangularBase< Derived >::outerStride(), and Eigen::TriangularBase< Derived >::rows().
evalTo()
template<typename Derived > template<typename DenseDerived > EIGEN_DEVICE_FUNC void Eigen::TriangularBase< Derived >::evalTo (MatrixBase< DenseDerived > & other) const
Assigns a triangular or selfadjoint matrix to a dense matrix. If the matrix is triangular, the opposite part is set to zero.
{
   evalToLazy(other.derived());
 }
evalToLazy()
template<typename Derived > template<typename DenseDerived > EIGEN_DEVICE_FUNC void Eigen::TriangularBase< Derived >::evalToLazy (MatrixBase< DenseDerived > & other) const
Assigns a triangular or selfadjoint matrix to a dense matrix. If the matrix is triangular, the opposite part is set to zero.
{
   other.derived().resize(this->rows(), this->cols());
   internal::call_triangular_assignment_loop<Derived::Mode,
                                             (int(Derived::Mode) & int(SelfAdjoint)) == 0 /* SetOpposite */>(
       other.derived(), derived().nestedExpression());
 }
References Eigen::internal::call_triangular_assignment_loop(), cols, int(), Eigen::DenseBase< Derived >::resize(), rows, and Eigen::SelfAdjoint.
Referenced by Eigen::TriangularBase< Derived >::toDenseMatrix().
innerStride()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::TriangularBase< Derived >::innerStride () const inline
 { return derived().innerStride(); }
References Eigen::TriangularBase< Derived >::derived().
operator()() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC Scalar& Eigen::TriangularBase< Derived >::operator() (Index row, Index col) inline
{
     check_coordinates(row, col);
     return coeffRef(row, col);
   }
References Eigen::TriangularBase< Derived >::check_coordinates(), Eigen::TriangularBase< Derived >::coeffRef(), col(), and row().
operator()() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC Scalar Eigen::TriangularBase< Derived >::operator() (Index row, Index col) const inline
{
     check_coordinates(row, col);
     return coeff(row, col);
   }
References Eigen::TriangularBase< Derived >::check_coordinates(), Eigen::TriangularBase< Derived >::coeff(), col(), and row().
outerStride()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::TriangularBase< Derived >::outerStride () const inline
 { return derived().outerStride(); }
References Eigen::TriangularBase< Derived >::derived().
resize()
template<typename Derived > EIGEN_DEVICE_FUNC void Eigen::TriangularBase< Derived >::resize (Index rows, Index cols) inline
{
     EIGEN_UNUSED_VARIABLE(rows);
     EIGEN_UNUSED_VARIABLE(cols);
     eigen_assert(rows == this->rows() && cols == this->cols());
   }
References Eigen::TriangularBase< Derived >::cols(), eigen_assert, EIGEN_UNUSED_VARIABLE, and Eigen::TriangularBase< Derived >::rows().
rows()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::TriangularBase< Derived >::rows () const inline
 { return derived().rows(); }
References Eigen::TriangularBase< Derived >::derived().
Referenced by gdb.printers._MatrixEntryIterator::__next__(), Eigen::TriangularBase< Derived >::check_coordinates(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), Eigen::TriangularBase< Derived >::resize(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and Eigen::TriangularBase< Derived >::toDenseMatrix().
toDenseMatrix()
template<typename Derived > EIGEN_DEVICE_FUNC DenseMatrixType Eigen::TriangularBase< Derived >::toDenseMatrix () const inline
{
     DenseMatrixType res(rows(), cols());
     evalToLazy(res);
     return res;
   }
References Eigen::TriangularBase< Derived >::cols(), Eigen::TriangularBase< Derived >::evalToLazy(), res, and Eigen::TriangularBase< Derived >::rows().
The documentation for this class was generated from the following file:
TriangularMatrix.h