MercuryDPM: TestAllocator Class Reference
TestAllocator Class Reference
Public Member Functions
~TestAllocator () EIGEN_OVERRIDE
EIGEN_DEVICE_FUNC void * allocate (size_t num_bytes) const EIGEN_OVERRIDE
EIGEN_DEVICE_FUNC void deallocate (void *buffer) const EIGEN_OVERRIDE
int alloc_count () const
int dealloc_count () const
Private Attributes
int alloc_count_ = 0
int dealloc_count_ = 0
Constructor & Destructor Documentation
~TestAllocator()
TestAllocator::~TestAllocator () inline
 {}
Member Function Documentation
alloc_count()
int TestAllocator::alloc_count () const inline
 { return alloc_count_; }
References alloc_count_.
Referenced by test_threadpool_allocate().
allocate()
EIGEN_DEVICE_FUNC void* TestAllocator::allocate (size_t num_bytes) const inline
{
     const_cast<TestAllocator*>(this)->alloc_count_++;
     return internal::aligned_malloc(num_bytes);
   }
References Eigen::internal::aligned_malloc(), and alloc_count_.
dealloc_count()
int TestAllocator::dealloc_count () const inline
 { return dealloc_count_; }
References dealloc_count_.
Referenced by test_threadpool_allocate().
deallocate()
EIGEN_DEVICE_FUNC void TestAllocator::deallocate (void * buffer) const inline
{
     const_cast<TestAllocator*>(this)->dealloc_count_++;
     internal::aligned_free(buffer);
   }
References Eigen::internal::aligned_free(), and dealloc_count_.
Member Data Documentation
alloc_count_
int TestAllocator::alloc_count_ = 0 private
Referenced by alloc_count(), and allocate().
dealloc_count_
int TestAllocator::dealloc_count_ = 0 private
Referenced by dealloc_count(), and deallocate().
The documentation for this class was generated from the following file:
cxx11_tensor_thread_pool.cpp