MercuryDPM: Eigen::internal::redux_impl< Func, Evaluator, LinearVectorizedTraversal, CompleteUnrolling > Struct Template Reference
Eigen::internal::redux_impl< Func, Evaluator, LinearVectorizedTraversal, CompleteUnrolling > Struct Template Reference
#include <Redux.h>
Public Types
typedef Evaluator::Scalar Scalar
typedef redux_traits< Func, Evaluator >::PacketType PacketType
Static Public Member Functions
template<typename XprType >
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar run (const Evaluator &eval, const Func &func, const XprType &xpr)
Static Public Attributes
static constexpr Index PacketSize = redux_traits<Func, Evaluator>::PacketSize
static constexpr Index Size = Evaluator::SizeAtCompileTime
static constexpr Index VectorizedSize = (int(Size) / int(PacketSize)) * int(PacketSize)
Member Typedef Documentation
PacketType
template<typename Func , typename Evaluator > typedef redux_traits<Func, Evaluator>::PacketType Eigen::internal::redux_impl< Func, Evaluator, LinearVectorizedTraversal, CompleteUnrolling >::PacketType
Scalar
template<typename Func , typename Evaluator > typedef Evaluator::Scalar Eigen::internal::redux_impl< Func, Evaluator, LinearVectorizedTraversal, CompleteUnrolling >::Scalar
Member Function Documentation
run()
template<typename Func , typename Evaluator > template<typename XprType > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar Eigen::internal::redux_impl< Func, Evaluator, LinearVectorizedTraversal, CompleteUnrolling >::run (const Evaluator & eval, const Func & func, const XprType & xpr) inline static
{
     EIGEN_ONLY_USED_FOR_DEBUG(xpr)
     eigen_assert(xpr.rows() > 0 && xpr.cols() > 0 && "you are using an empty matrix");
     if (VectorizedSize > 0) {
       Scalar res = func.predux(
           redux_vec_linear_unroller<Func, Evaluator, 0, Size / PacketSize>::template run<PacketType>(eval, func));
       if (VectorizedSize != Size)
         res = func(
             res, redux_novec_linear_unroller<Func, Evaluator, VectorizedSize, Size - VectorizedSize>::run(eval, func));
       return res;
     } else {
       return redux_novec_linear_unroller<Func, Evaluator, 0, Size>::run(eval, func);
     }
   }
References Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::cols(), eigen_assert, EIGEN_ONLY_USED_FOR_DEBUG, func(), res, Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::rows(), and Eigen::internal::redux_novec_linear_unroller< Func, Evaluator, Start, Length >::run().
Member Data Documentation
PacketSize
template<typename Func , typename Evaluator > constexpr Index Eigen::internal::redux_impl< Func, Evaluator, LinearVectorizedTraversal, CompleteUnrolling >::PacketSize = redux_traits<Func, Evaluator>::PacketSize static constexpr
Size
template<typename Func , typename Evaluator > constexpr Index Eigen::internal::redux_impl< Func, Evaluator, LinearVectorizedTraversal, CompleteUnrolling >::Size = Evaluator::SizeAtCompileTime static constexpr
VectorizedSize
template<typename Func , typename Evaluator > constexpr Index Eigen::internal::redux_impl< Func, Evaluator, LinearVectorizedTraversal, CompleteUnrolling >::VectorizedSize = (int(Size) / int(PacketSize)) * int(PacketSize) static constexpr
The documentation for this struct was generated from the following file:
Redux.h