MercuryDPM: Eigen::general_product_to_triangular_selector< MatrixType, ProductType, UpLo, false > Struct Template Reference
Eigen::general_product_to_triangular_selector< MatrixType, ProductType, UpLo, false > Struct Template Reference
#include <GeneralMatrixMatrixTriangular.h>
Static Public Member Functions
static void run (MatrixType &mat, const ProductType &prod, const typename MatrixType::Scalar &alpha, bool beta)
Member Function Documentation
run()
template<typename MatrixType , typename ProductType , int UpLo> static void Eigen::general_product_to_triangular_selector< MatrixType, ProductType, UpLo, false >::run (MatrixType & mat, const ProductType & prod, const typename MatrixType::Scalar & alpha, bool beta) inline static
{
     typedef internal::remove_all_t<typename ProductType::LhsNested> Lhs;
     typedef internal::blas_traits<Lhs> LhsBlasTraits;
     typedef typename LhsBlasTraits::DirectLinearAccessType ActualLhs;
     typedef internal::remove_all_t<ActualLhs> ActualLhs_;
     internal::add_const_on_value_type_t<ActualLhs> actualLhs = LhsBlasTraits::extract(prod.lhs());
     typedef internal::remove_all_t<typename ProductType::RhsNested> Rhs;
     typedef internal::blas_traits<Rhs> RhsBlasTraits;
     typedef typename RhsBlasTraits::DirectLinearAccessType ActualRhs;
     typedef internal::remove_all_t<ActualRhs> ActualRhs_;
     internal::add_const_on_value_type_t<ActualRhs> actualRhs = RhsBlasTraits::extract(prod.rhs());
     typename ProductType::Scalar actualAlpha = alpha * LhsBlasTraits::extractScalarFactor(prod.lhs().derived()) *
                                                RhsBlasTraits::extractScalarFactor(prod.rhs().derived());
     if (!beta) mat.template triangularView<UpLo>().setZero();
     enum {
       IsRowMajor = (internal::traits<MatrixType>::Flags & RowMajorBit) ? 1 : 0,
       LhsIsRowMajor = ActualLhs_::Flags & RowMajorBit ? 1 : 0,
       RhsIsRowMajor = ActualRhs_::Flags & RowMajorBit ? 1 : 0,
       SkipDiag = (UpLo & (UnitDiag | ZeroDiag)) != 0
     };
     Index size = mat.cols();
     if (SkipDiag) size--;
     Index depth = actualLhs.cols();
     typedef internal::gemm_blocking_space<IsRowMajor ? RowMajor : ColMajor, typename Lhs::Scalar, typename Rhs::Scalar,
                                           MatrixType::MaxColsAtCompileTime, MatrixType::MaxColsAtCompileTime,
                                           ActualRhs_::MaxColsAtCompileTime>
         BlockingType;
     BlockingType blocking(size, size, depth, 1, false);
     internal::general_matrix_matrix_triangular_product<
         Index, typename Lhs::Scalar, LhsIsRowMajor ? RowMajor : ColMajor, LhsBlasTraits::NeedToConjugate,
         typename Rhs::Scalar, RhsIsRowMajor ? RowMajor : ColMajor, RhsBlasTraits::NeedToConjugate,
         IsRowMajor ? RowMajor : ColMajor, MatrixType::InnerStrideAtCompileTime,
         UpLo&(Lower | Upper)>::run(size, depth, &actualLhs.coeffRef(SkipDiag && (UpLo & Lower) == Lower ? 1 : 0, 0),
                                    actualLhs.outerStride(),
                                    &actualRhs.coeffRef(0, SkipDiag && (UpLo & Upper) == Upper ? 1 : 0),
                                    actualRhs.outerStride(),
                                    mat.data() +
                                        (SkipDiag ? (bool(IsRowMajor) != ((UpLo & Lower) == Lower) ? mat.innerStride()
                                                                                                   : mat.outerStride())
                                                  : 0),
                                    mat.innerStride(), mat.outerStride(), actualAlpha, blocking);
   }
References alpha, beta, Eigen::ColMajor, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::cols(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::data(), Eigen::Product< Lhs_, Rhs_, Option >::lhs(), Eigen::internal::Lhs, Eigen::Lower, Eigen::prod(), Eigen::Product< Lhs_, Rhs_, Option >::rhs(), Eigen::internal::Rhs, Eigen::RowMajor, Eigen::RowMajorBit, Eigen::run(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::setZero(), size, Eigen::UnitDiag, Eigen::Upper, and Eigen::ZeroDiag.
The documentation for this struct was generated from the following file:
GeneralMatrixMatrixTriangular.h