MercuryDPM: one_d_poisson_hp_adapt.cc File Reference
one_d_poisson_hp_adapt.cc File Reference
#include "generic.h"
#include "poisson.h"
#include "meshes/one_d_mesh.h"
Classes
class ModalPoissonEquations< DIM >
class RefineableModalPoissonEquations< DIM >
Refineable version of Poisson equations.
class ModalPRefineableQElement< DIM >
class ModalPRefineableQPoissonElement< DIM >
class PRefineableOneDPoissonProblem< ELEMENT >
Namespaces
ArcTanSolnForPoisson
Namespace for exact solution for Poisson equation with "sharp step".
Functions
void ArcTanSolnForPoisson::get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void ArcTanSolnForPoisson::get_exact_gradient (const Vector< double > &x, Vector< double > &dudx)
Exact gradient as a Vector.
void ArcTanSolnForPoisson::get_source (const Vector< double > &x, double &source)
Source function required to make the solution above an exact solution.
int main ()
Driver code for 1D Poisson problem.
Function Documentation
main()
int main ()
Driver code for 1D Poisson problem.
 {
  // Create label for output
  // -----------------------
  DocInfo doc_info;
  // Set output directory
  doc_info.set_directory("RESLT");
  // Step number
  doc_info.number()=0;
  // Choose a large value for the steepness of the "step"
  ArcTanSolnForPoisson::Alpha=100.0;
  cout << "\n====================================\nNodal elements:\n" << endl;
  //Set up the problem
  //------------------
  // Create the problem with 1D three-node refineable elements from the
  // PRefineableQPoissonElement<1> family. Pass pointer to source function.
  PRefineableOneDPoissonProblem<PRefineableQPoissonElement<1> >
   nodal_problem(&ArcTanSolnForPoisson::get_source);
  // Check if we're ready to go:
  // ---------------------------
  cout << "\n\n\nProblem self-test ";
  if (nodal_problem.self_test()==0)
   {
    cout << "passed: Problem can be solved." << std::endl;
   }
  else
   {
    throw OomphLibError("Self test failed",
                        OOMPH_CURRENT_FUNCTION,
                        OOMPH_EXCEPTION_LOCATION);
   }
  // Refine problem uniformly 2 times
  for(unsigned i=0;i<2;i++)
   {
    cout << "p_refining:" << endl;
    nodal_problem.p_refine_uniformly();
   }
  for(unsigned i=0;i<2;i++)
   {
    cout << "h_refining:" << endl;
    nodal_problem.refine_uniformly();
   }
  doc_info.number()=2;
  nodal_problem.newton_solve();
  nodal_problem.doc_solution(doc_info);
  nodal_problem.adapt();
  doc_info.number()=3;
  nodal_problem.newton_solve();
  nodal_problem.doc_solution(doc_info);
  nodal_problem.p_adapt();
  doc_info.number()=4;
  nodal_problem.newton_solve();
  nodal_problem.doc_solution(doc_info);
  nodal_problem.adapt();
  doc_info.number()=5;
  nodal_problem.newton_solve();
  nodal_problem.doc_solution(doc_info);
  nodal_problem.p_adapt();
  doc_info.number()=6;
  nodal_problem.newton_solve();
  nodal_problem.doc_solution(doc_info);
  nodal_problem.adapt();
  doc_info.number()=7;
  nodal_problem.newton_solve();
  nodal_problem.doc_solution(doc_info);
  nodal_problem.p_adapt();
  doc_info.number()=8;
  nodal_problem.newton_solve();
  nodal_problem.doc_solution(doc_info);
  doc_info.number()=0;
  nodal_problem.doc_solution(doc_info);
  cout << "\n====================================\nModal elements:\n" << endl;
  //Set up the problem
  //------------------
  // Create the problem with 1D three-node refineable elements from the
  // RefineableLinePoissonElement family. Pass pointer to source function.
  PRefineableOneDPoissonProblem<ModalPRefineableQPoissonElement<1> >
   modal_problem(&ArcTanSolnForPoisson::get_source);
  // Check if we're ready to go:
  // ---------------------------
  cout << "\n\n\nProblem self-test ";
  if (modal_problem.self_test()==0)
   {
    cout << "passed: Problem can be solved." << std::endl;
   }
  else
   {
    throw OomphLibError("Self test failed",
                        OOMPH_CURRENT_FUNCTION,
                        OOMPH_EXCEPTION_LOCATION);
   }
  // Refine problem uniformly 2 times
  for(unsigned i=0;i<2;i++)
   {
    cout << "p_refining:" << endl;
    modal_problem.p_refine_uniformly();
   }
  for(unsigned i=0;i<2;i++)
   {
    cout << "h_refining:" << endl;
    modal_problem.refine_uniformly();
   }
  doc_info.number()=2;
  modal_problem.newton_solve();
  modal_problem.doc_solution(doc_info);
  modal_problem.adapt();
  doc_info.number()=3;
  modal_problem.newton_solve();
  modal_problem.doc_solution(doc_info);
  modal_problem.p_adapt();
  doc_info.number()=4;
  modal_problem.newton_solve();
  modal_problem.doc_solution(doc_info);
  modal_problem.adapt();
  doc_info.number()=5;
  modal_problem.newton_solve();
  modal_problem.doc_solution(doc_info);
  modal_problem.p_adapt();
  doc_info.number()=6;
  modal_problem.newton_solve();
  modal_problem.doc_solution(doc_info);
  modal_problem.adapt();
  doc_info.number()=7;
  modal_problem.newton_solve();
  modal_problem.doc_solution(doc_info);
  modal_problem.p_adapt();
  doc_info.number()=8;
  modal_problem.newton_solve();
  modal_problem.doc_solution(doc_info);
  doc_info.number()=1;
  modal_problem.doc_solution(doc_info);
 } // End of main
References oomph::Problem::adapt(), ArcTanSolnForPoisson::Alpha, PRefineableOneDPoissonProblem< ELEMENT >::doc_solution(), ArcTanSolnForPoisson::get_source(), i, oomph::Problem::newton_solve(), oomph::DocInfo::number(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::Problem::p_adapt(), oomph::Problem::p_refine_uniformly(), oomph::Problem::refine_uniformly(), oomph::Problem::self_test(), and oomph::DocInfo::set_directory().