MercuryDPM: Eigen::SVDBase< Derived > Class Template Reference
Eigen::SVDBase< Derived > Class Template Reference
Dense linear problems and decompositions » Reference » SVD_Module
Base class of SVD algorithms.
#include <SVDBase.h>
Public Types
enum {
RowsAtCompileTime = MatrixType::RowsAtCompileTime , ColsAtCompileTime = MatrixType::ColsAtCompileTime , DiagSizeAtCompileTime = internal::min_size_prefer_dynamic(RowsAtCompileTime, ColsAtCompileTime) , MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime ,
MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime , MaxDiagSizeAtCompileTime = internal::min_size_prefer_fixed(MaxRowsAtCompileTime, MaxColsAtCompileTime) , MatrixOptions = internal::traits<MatrixType>::Options , MatrixUColsAtCompileTime = internal::traits<Derived>::MatrixUColsAtCompileTime ,
MatrixVColsAtCompileTime = internal::traits<Derived>::MatrixVColsAtCompileTime , MatrixUMaxColsAtCompileTime = internal::traits<Derived>::MatrixUMaxColsAtCompileTime , MatrixVMaxColsAtCompileTime = internal::traits<Derived>::MatrixVMaxColsAtCompileTime
}
typedef internal::traits< Derived >::MatrixType MatrixType
typedef MatrixType::Scalar Scalar
typedef NumTraits< typename MatrixType::Scalar >::Real RealScalar
typedef Eigen::internal::traits< SVDBase >::StorageIndex StorageIndex
typedef internal::make_proper_matrix_type< Scalar, RowsAtCompileTime, MatrixUColsAtCompileTime, MatrixOptions, MaxRowsAtCompileTime, MatrixUMaxColsAtCompileTime >::type MatrixUType
typedef internal::make_proper_matrix_type< Scalar, ColsAtCompileTime, MatrixVColsAtCompileTime, MatrixOptions, MaxColsAtCompileTime, MatrixVMaxColsAtCompileTime >::type MatrixVType
typedef internal::plain_diag_type< MatrixType, RealScalar >::type SingularValuesType
Public Types inherited from Eigen::SolverBase< SVDBase< Derived > >
enum
typedef EigenBase< SVDBase< Derived > > Base
typedef internal::traits< SVDBase< Derived > >::Scalar Scalar
typedef Scalar CoeffReturnType
typedef Transpose< const SVDBase< Derived > > ConstTransposeReturnType
typedef std::conditional_t< NumTraits< Scalar >::IsComplex, CwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, const ConstTransposeReturnType >, const ConstTransposeReturnType > AdjointReturnType
Public Types inherited from Eigen::EigenBase< Derived >
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< Derived >::StorageKind StorageKind
Public Member Functions
Derived & derived ()
const Derived & derived () const
const MatrixUType & matrixU () const
const MatrixVType & matrixV () const
const SingularValuesType & singularValues () const
Index nonzeroSingularValues () const
Index rank () const
Derived & setThreshold (const RealScalar &threshold)
Derived & setThreshold (Default_t)
RealScalar threshold () const
bool computeU () const
bool computeV () const
Index rows () const
Index cols () const
Index diagSize () const
EIGEN_DEVICE_FUNC ComputationInfo info () const
Reports whether previous computation was successful.
template<typename RhsType , typename DstType >
void _solve_impl (const RhsType &rhs, DstType &dst) const
template<bool Conjugate, typename RhsType , typename DstType >
void _solve_impl_transposed (const RhsType &rhs, DstType &dst) const
Public Member Functions inherited from Eigen::SolverBase< SVDBase< Derived > >
SolverBase ()
~SolverBase ()
const Solve< SVDBase< Derived >, Rhs > solve (const MatrixBase< Rhs > &b) const
const ConstTransposeReturnType transpose () const
const AdjointReturnType adjoint () const
constexpr EIGEN_DEVICE_FUNC SVDBase< Derived > & derived ()
constexpr EIGEN_DEVICE_FUNC const SVDBase< Derived > & derived () const
Public Member Functions inherited from Eigen::EigenBase< Derived >
constexpr EIGEN_DEVICE_FUNC Derived & derived ()
constexpr EIGEN_DEVICE_FUNC const Derived & derived () const
EIGEN_DEVICE_FUNC Derived & const_cast_derived () const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index size () const EIGEN_NOEXCEPT
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
template<typename Device >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< Derived, Device > device (Device &device)
template<typename Device >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< const Derived, Device > device (Device &device) const
Static Public Attributes
static constexpr bool ShouldComputeFullU = internal::traits<Derived>::ShouldComputeFullU
static constexpr bool ShouldComputeThinU = internal::traits<Derived>::ShouldComputeThinU
static constexpr bool ShouldComputeFullV = internal::traits<Derived>::ShouldComputeFullV
static constexpr bool ShouldComputeThinV = internal::traits<Derived>::ShouldComputeThinV
Protected Member Functions
void _check_compute_assertions () const
template<bool Transpose_, typename Rhs >
void _check_solve_assertion (const Rhs &b) const
bool allocate (Index rows, Index cols, unsigned int computationOptions)
SVDBase ()
Default Constructor.
Protected Member Functions inherited from Eigen::SolverBase< SVDBase< Derived > >
void _check_solve_assertion (const Rhs &b) const
Protected Attributes
MatrixUType m_matrixU
MatrixVType m_matrixV
SingularValuesType m_singularValues
ComputationInfo m_info
bool m_isInitialized
bool m_isAllocated
bool m_usePrescribedThreshold
bool m_computeFullU
bool m_computeThinU
bool m_computeFullV
bool m_computeThinV
unsigned int m_computationOptions
Index m_nonzeroSingularValues
internal::variable_if_dynamic< Index, RowsAtCompileTime > m_rows
internal::variable_if_dynamic< Index, ColsAtCompileTime > m_cols
internal::variable_if_dynamic< Index, DiagSizeAtCompileTime > m_diagSize
RealScalar m_prescribedThreshold
Friends
template<typename Derived_ >
struct internal::solve_assertion
Detailed Description
template<typename Derived>
class Eigen::SVDBase< Derived >
Base class of SVD algorithms.
Template Parameters
Derived the type of the actual SVD decomposition
SVD decomposition consists in decomposing any n-by-p matrix A as a product
\[ A = U S V^* \]
where U is a n-by-n unitary, V is a p-by-p unitary, and S is a n-by-p real positive matrix which is zero outside of its main diagonal; the diagonal entries of S are known as the singular values of A and the columns of U and V are known as the left and right singular vectors of A respectively.
Singular values are always sorted in decreasing order.
You can ask for only thin U or V to be computed, meaning the following. In case of a rectangular n-by-p matrix, letting m be the smaller value among n and p, there are only m singular vectors; the remaining columns of U and V do not correspond to actual singular vectors. Asking for thin U or V means asking for only their m first columns to be formed. So U is then a n-by-m matrix, and V is then a p-by-m matrix. Notice that thin U and V are all you need for (least squares) solving.
The status of the computation can be retrieved using the info() method. Unless info() returns Success, the results should be not considered well defined.
If the input matrix has inf or nan coefficients, the result of the computation is undefined, and info() will return InvalidInput, but the computation is guaranteed to terminate in finite (and reasonable) time.
See also
class BDCSVD, class JacobiSVD
Member Typedef Documentation
MatrixType
template<typename Derived > typedef internal::traits<Derived>::MatrixType Eigen::SVDBase< Derived >::MatrixType
MatrixUType
template<typename Derived > typedef internal::make_proper_matrix_type<Scalar, RowsAtCompileTime, MatrixUColsAtCompileTime, MatrixOptions, MaxRowsAtCompileTime, MatrixUMaxColsAtCompileTime>::type Eigen::SVDBase< Derived >::MatrixUType
MatrixVType
template<typename Derived > typedef internal::make_proper_matrix_type<Scalar, ColsAtCompileTime, MatrixVColsAtCompileTime, MatrixOptions, MaxColsAtCompileTime, MatrixVMaxColsAtCompileTime>::type Eigen::SVDBase< Derived >::MatrixVType
RealScalar
template<typename Derived > typedef NumTraits<typename MatrixType::Scalar>::Real Eigen::SVDBase< Derived >::RealScalar
Scalar
template<typename Derived > typedef MatrixType::Scalar Eigen::SVDBase< Derived >::Scalar
SingularValuesType
template<typename Derived > typedef internal::plain_diag_type<MatrixType, RealScalar>::type Eigen::SVDBase< Derived >::SingularValuesType
StorageIndex
template<typename Derived > typedef Eigen::internal::traits<SVDBase>::StorageIndex Eigen::SVDBase< Derived >::StorageIndex
Member Enumeration Documentation
anonymous enum
template<typename Derived > anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
DiagSizeAtCompileTime
MaxRowsAtCompileTime
MaxColsAtCompileTime
MaxDiagSizeAtCompileTime
MatrixOptions
MatrixUColsAtCompileTime
MatrixVColsAtCompileTime
MatrixUMaxColsAtCompileTime
MatrixVMaxColsAtCompileTime
        {
     RowsAtCompileTime = MatrixType::RowsAtCompileTime,
     ColsAtCompileTime = MatrixType::ColsAtCompileTime,
     DiagSizeAtCompileTime = internal::min_size_prefer_dynamic(RowsAtCompileTime, ColsAtCompileTime),
     MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime,
     MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime,
     MaxDiagSizeAtCompileTime = internal::min_size_prefer_fixed(MaxRowsAtCompileTime, MaxColsAtCompileTime),
     MatrixOptions = internal::traits<MatrixType>::Options,
     MatrixUColsAtCompileTime = internal::traits<Derived>::MatrixUColsAtCompileTime,
     MatrixVColsAtCompileTime = internal::traits<Derived>::MatrixVColsAtCompileTime,
     MatrixUMaxColsAtCompileTime = internal::traits<Derived>::MatrixUMaxColsAtCompileTime,
     MatrixVMaxColsAtCompileTime = internal::traits<Derived>::MatrixVMaxColsAtCompileTime
   };
Constructor & Destructor Documentation
SVDBase()
template<typename Derived > Eigen::SVDBase< Derived >::SVDBase () inline protected
Default Constructor.
Default constructor of SVDBase
       : m_matrixU(MatrixUType()),
         m_matrixV(MatrixVType()),
         m_singularValues(SingularValuesType()),
         m_info(Success),
         m_isInitialized(false),
         m_isAllocated(false),
         m_usePrescribedThreshold(false),
         m_computeFullU(ShouldComputeFullU),
         m_computeThinU(ShouldComputeThinU),
         m_computeFullV(ShouldComputeFullV),
         m_computeThinV(ShouldComputeThinV),
         m_computationOptions(internal::traits<Derived>::Options),
         m_nonzeroSingularValues(0),
         m_rows(RowsAtCompileTime),
         m_cols(ColsAtCompileTime),
         m_diagSize(DiagSizeAtCompileTime),
         m_prescribedThreshold(0) {}
Member Function Documentation
_check_compute_assertions()
template<typename Derived > void Eigen::SVDBase< Derived >::_check_compute_assertions () const inline protected
 { eigen_assert(m_isInitialized && "SVD is not initialized."); }
References eigen_assert, and Eigen::SVDBase< Derived >::m_isInitialized.
Referenced by Eigen::SVDBase< Derived >::_check_solve_assertion(), Eigen::SVDBase< Derived >::matrixU(), Eigen::SVDBase< Derived >::matrixV(), Eigen::SVDBase< Derived >::nonzeroSingularValues(), Eigen::SVDBase< Derived >::rank(), and Eigen::SVDBase< Derived >::singularValues().
_check_solve_assertion()
template<typename Derived > template<bool Transpose_, typename Rhs > void Eigen::SVDBase< Derived >::_check_solve_assertion (const Rhs & b) const inline protected
{
     EIGEN_ONLY_USED_FOR_DEBUG(b);
     _check_compute_assertions();
     eigen_assert(computeU() && computeV() &&
                  "SVDBase::solve(): Both unitaries U and V are required to be computed (thin unitaries suffice).");
     eigen_assert((Transpose_ ? cols() : rows()) == b.rows() &&
                  "SVDBase::solve(): invalid number of rows of the right hand side matrix b");
   }
References Eigen::SVDBase< Derived >::_check_compute_assertions(), b, Eigen::SVDBase< Derived >::cols(), Eigen::SVDBase< Derived >::computeU(), Eigen::SVDBase< Derived >::computeV(), eigen_assert, EIGEN_ONLY_USED_FOR_DEBUG, and Eigen::SVDBase< Derived >::rows().
_solve_impl()
template<typename Derived > template<typename RhsType , typename DstType > void Eigen::SVDBase< Derived >::_solve_impl (const RhsType & rhs, DstType & dst) const
{
   // A = U S V^*
   // So A^{-1} = V S^{-1} U^*
   Matrix<typename RhsType::Scalar, Dynamic, RhsType::ColsAtCompileTime, 0, MatrixType::MaxRowsAtCompileTime,
          RhsType::MaxColsAtCompileTime>
       tmp;
   Index l_rank = rank();
   tmp.noalias() = m_matrixU.leftCols(l_rank).adjoint() * rhs;
   tmp = m_singularValues.head(l_rank).asDiagonal().inverse() * tmp;
   dst = m_matrixV.leftCols(l_rank) * tmp;
 }
References Eigen::Dynamic, and tmp.
_solve_impl_transposed()
template<typename Derived > template<bool Conjugate, typename RhsType , typename DstType > void Eigen::SVDBase< Derived >::_solve_impl_transposed (const RhsType & rhs, DstType & dst) const
{
   // A = U S V^*
   // So  A^{-*} = U S^{-1} V^*
   // And A^{-T} = U_conj S^{-1} V^T
   Matrix<typename RhsType::Scalar, Dynamic, RhsType::ColsAtCompileTime, 0, MatrixType::MaxRowsAtCompileTime,
          RhsType::MaxColsAtCompileTime>
       tmp;
   Index l_rank = rank();
   tmp.noalias() = m_matrixV.leftCols(l_rank).transpose().template conjugateIf<Conjugate>() * rhs;
   tmp = m_singularValues.head(l_rank).asDiagonal().inverse() * tmp;
   dst = m_matrixU.template conjugateIf<!Conjugate>().leftCols(l_rank) * tmp;
 }
References Eigen::Dynamic, and tmp.
allocate()
template<typename Derived > bool Eigen::SVDBase< Derived >::allocate (Index rows, Index cols, unsigned int computationOptions) protected
{
   eigen_assert(rows >= 0 && cols >= 0);
   if (m_isAllocated && rows == m_rows.value() && cols == m_cols.value() && computationOptions == m_computationOptions) {
     return true;
   }
   m_rows.setValue(rows);
   m_cols.setValue(cols);
   m_info = Success;
   m_isInitialized = false;
   m_isAllocated = true;
   m_computationOptions = computationOptions;
   m_computeFullU = ShouldComputeFullU || internal::should_svd_compute_full_u(computationOptions);
   m_computeThinU = ShouldComputeThinU || internal::should_svd_compute_thin_u(computationOptions);
   m_computeFullV = ShouldComputeFullV || internal::should_svd_compute_full_v(computationOptions);
   m_computeThinV = ShouldComputeThinV || internal::should_svd_compute_thin_v(computationOptions);
   eigen_assert(!(m_computeFullU && m_computeThinU) && "SVDBase: you can't ask for both full and thin U");
   eigen_assert(!(m_computeFullV && m_computeThinV) && "SVDBase: you can't ask for both full and thin V");
   m_diagSize.setValue(numext::mini(m_rows.value(), m_cols.value()));
   m_singularValues.resize(m_diagSize.value());
   if (RowsAtCompileTime == Dynamic)
     m_matrixU.resize(m_rows.value(), m_computeFullU ? m_rows.value() : m_computeThinU ? m_diagSize.value() : 0);
   if (ColsAtCompileTime == Dynamic)
     m_matrixV.resize(m_cols.value(), m_computeFullV ? m_cols.value() : m_computeThinV ? m_diagSize.value() : 0);
   return false;
 }
References cols, Eigen::Dynamic, eigen_assert, Eigen::numext::mini(), rows, Eigen::internal::should_svd_compute_full_u(), Eigen::internal::should_svd_compute_full_v(), Eigen::internal::should_svd_compute_thin_u(), Eigen::internal::should_svd_compute_thin_v(), and Eigen::Success.
Referenced by Eigen::JacobiSVD< MatrixType_, Options_ >::allocate().
cols()
template<typename Derived > Index Eigen::SVDBase< Derived >::cols () const inline
 { return m_cols.value(); }
References Eigen::SVDBase< Derived >::m_cols, and Eigen::internal::variable_if_dynamic< T, Value >::value().
Referenced by gdb.printers._MatrixEntryIterator::__next__(), Eigen::SVDBase< Derived >::_check_solve_assertion(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
computeU()
template<typename Derived > bool Eigen::SVDBase< Derived >::computeU () const inline
Returns
true if U (full or thin) is asked for in this SVD decomposition
 { return m_computeFullU || m_computeThinU; }
References Eigen::SVDBase< Derived >::m_computeFullU, and Eigen::SVDBase< Derived >::m_computeThinU.
Referenced by Eigen::SVDBase< Derived >::_check_solve_assertion(), and Eigen::SVDBase< Derived >::matrixU().
computeV()
template<typename Derived > bool Eigen::SVDBase< Derived >::computeV () const inline
Returns
true if V (full or thin) is asked for in this SVD decomposition
 { return m_computeFullV || m_computeThinV; }
References Eigen::SVDBase< Derived >::m_computeFullV, and Eigen::SVDBase< Derived >::m_computeThinV.
Referenced by Eigen::SVDBase< Derived >::_check_solve_assertion(), and Eigen::SVDBase< Derived >::matrixV().
derived() [1/2]
template<typename Derived > Derived& Eigen::SVDBase< Derived >::derived () inline
 { return *static_cast<Derived*>(this); }
Referenced by Eigen::SVDBase< Derived >::setThreshold().
derived() [2/2]
template<typename Derived > const Derived& Eigen::SVDBase< Derived >::derived () const inline
 { return *static_cast<const Derived*>(this); }
diagSize()
template<typename Derived > Index Eigen::SVDBase< Derived >::diagSize () const inline
 { return m_diagSize.value(); }
References Eigen::SVDBase< Derived >::m_diagSize, and Eigen::internal::variable_if_dynamic< T, Value >::value().
Referenced by Eigen::SVDBase< Derived >::threshold().
info()
template<typename Derived > EIGEN_DEVICE_FUNC ComputationInfo Eigen::SVDBase< Derived >::info () const inline
Reports whether previous computation was successful.
Returns
Success if computation was successful.
{
     eigen_assert(m_isInitialized && "SVD is not initialized.");
     return m_info;
   }
References eigen_assert, Eigen::SVDBase< Derived >::m_info, and Eigen::SVDBase< Derived >::m_isInitialized.
matrixU()
template<typename Derived > const MatrixUType& Eigen::SVDBase< Derived >::matrixU () const inline
Returns
the U matrix.
For the SVD decomposition of a n-by-p matrix, letting m be the minimum of n and p, the U matrix is n-by-n if you asked for ComputeFullU , and is n-by-m if you asked for ComputeThinU .
The m first columns of U are the left singular vectors of the matrix being decomposed.
This method asserts that you asked for U to be computed.
{
     _check_compute_assertions();
     eigen_assert(computeU() && "This SVD decomposition didn't compute U. Did you ask for it?");
     return m_matrixU;
   }
References Eigen::SVDBase< Derived >::_check_compute_assertions(), Eigen::SVDBase< Derived >::computeU(), eigen_assert, and Eigen::SVDBase< Derived >::m_matrixU.
matrixV()
template<typename Derived > const MatrixVType& Eigen::SVDBase< Derived >::matrixV () const inline
Returns
the V matrix.
For the SVD decomposition of a n-by-p matrix, letting m be the minimum of n and p, the V matrix is p-by-p if you asked for ComputeFullV , and is p-by-m if you asked for ComputeThinV .
The m first columns of V are the right singular vectors of the matrix being decomposed.
This method asserts that you asked for V to be computed.
{
     _check_compute_assertions();
     eigen_assert(computeV() && "This SVD decomposition didn't compute V. Did you ask for it?");
     return m_matrixV;
   }
References Eigen::SVDBase< Derived >::_check_compute_assertions(), Eigen::SVDBase< Derived >::computeV(), eigen_assert, and Eigen::SVDBase< Derived >::m_matrixV.
nonzeroSingularValues()
template<typename Derived > Index Eigen::SVDBase< Derived >::nonzeroSingularValues () const inline
Returns
the number of singular values that are not exactly 0
{
     _check_compute_assertions();
     return m_nonzeroSingularValues;
   }
References Eigen::SVDBase< Derived >::_check_compute_assertions(), and Eigen::SVDBase< Derived >::m_nonzeroSingularValues.
rank()
template<typename Derived > Index Eigen::SVDBase< Derived >::rank () const inline
Returns
the rank of the matrix of which *this is the SVD.
Note
This method has to determine which singular values should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
{
     using std::abs;
     _check_compute_assertions();
     if (m_singularValues.size() == 0) return 0;
     RealScalar premultiplied_threshold =
         numext::maxi<RealScalar>(m_singularValues.coeff(0) * threshold(), (std::numeric_limits<RealScalar>::min)());
     Index i = m_nonzeroSingularValues - 1;
     while (i >= 0 && m_singularValues.coeff(i) < premultiplied_threshold) --i;
     return i + 1;
   }
References Eigen::SVDBase< Derived >::_check_compute_assertions(), abs(), i, Eigen::SVDBase< Derived >::m_nonzeroSingularValues, Eigen::SVDBase< Derived >::m_singularValues, min, and Eigen::SVDBase< Derived >::threshold().
rows()
template<typename Derived > Index Eigen::SVDBase< Derived >::rows () const inline
 { return m_rows.value(); }
References Eigen::SVDBase< Derived >::m_rows, and Eigen::internal::variable_if_dynamic< T, Value >::value().
Referenced by gdb.printers._MatrixEntryIterator::__next__(), Eigen::SVDBase< Derived >::_check_solve_assertion(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
setThreshold() [1/2]
template<typename Derived > Derived& Eigen::SVDBase< Derived >::setThreshold (const RealScalar & threshold) inline
Allows to prescribe a threshold to be used by certain methods, such as rank() and solve(), which need to determine when singular values are to be considered nonzero. This is not used for the SVD decomposition itself.
When it needs to get the threshold value, Eigen calls threshold(). The default is NumTraits<Scalar>::epsilon()
Parameters
threshold The new value to use as the threshold.
A singular value will be considered nonzero if its value is strictly greater than \(\vert singular value \vert \leqslant threshold \times \vert max singular value \vert \).
If you want to come back to the default behavior, call setThreshold(Default_t)
{
     m_usePrescribedThreshold = true;
     m_prescribedThreshold = threshold;
     return derived();
   }
References Eigen::SVDBase< Derived >::derived(), Eigen::SVDBase< Derived >::m_prescribedThreshold, Eigen::SVDBase< Derived >::m_usePrescribedThreshold, and Eigen::SVDBase< Derived >::threshold().
setThreshold() [2/2]
template<typename Derived > Derived& Eigen::SVDBase< Derived >::setThreshold (Default_t) inline
Allows to come back to the default behavior, letting Eigen use its default formula for determining the threshold.
You should pass the special object Eigen::Default as parameter here.
svd.setThreshold(Eigen::Default);
See the documentation of setThreshold(const RealScalar&).
{
     m_usePrescribedThreshold = false;
     return derived();
   }
References Eigen::SVDBase< Derived >::derived(), and Eigen::SVDBase< Derived >::m_usePrescribedThreshold.
singularValues()
template<typename Derived > const SingularValuesType& Eigen::SVDBase< Derived >::singularValues () const inline
Returns
the vector of singular values.
For the SVD decomposition of a n-by-p matrix, letting m be the minimum of n and p, the returned vector has size m. Singular values are always sorted in decreasing order.
{
     _check_compute_assertions();
     return m_singularValues;
   }
References Eigen::SVDBase< Derived >::_check_compute_assertions(), and Eigen::SVDBase< Derived >::m_singularValues.
Referenced by check_generateRandomMatrixSvs(), compare_bdc_jacobi(), and Eigen::BDCSVD< MatrixType_, Options_ >::computeSVDofM().
threshold()
template<typename Derived > RealScalar Eigen::SVDBase< Derived >::threshold () const inline
Returns the threshold that will be used by certain methods such as rank().
See the documentation of setThreshold(const RealScalar&).
{
     eigen_assert(m_isInitialized || m_usePrescribedThreshold);
     // this temporary is needed to workaround a MSVC issue
     Index diagSize = (std::max<Index>)(1, m_diagSize);
     return m_usePrescribedThreshold ? m_prescribedThreshold : RealScalar(diagSize) * NumTraits<Scalar>::epsilon();
   }
References Eigen::SVDBase< Derived >::diagSize(), eigen_assert, oomph::SarahBL::epsilon, Eigen::SVDBase< Derived >::m_diagSize, Eigen::SVDBase< Derived >::m_isInitialized, Eigen::SVDBase< Derived >::m_prescribedThreshold, and Eigen::SVDBase< Derived >::m_usePrescribedThreshold.
Referenced by Eigen::SVDBase< Derived >::rank(), and Eigen::SVDBase< Derived >::setThreshold().
Friends And Related Function Documentation
internal::solve_assertion
template<typename Derived > template<typename Derived_ > friend struct internal::solve_assertion friend
Member Data Documentation
m_cols
template<typename Derived > internal::variable_if_dynamic<Index, ColsAtCompileTime> Eigen::SVDBase< Derived >::m_cols protected
Referenced by Eigen::SVDBase< Derived >::cols().
m_computationOptions
template<typename Derived > unsigned int Eigen::SVDBase< Derived >::m_computationOptions protected
m_computeFullU
template<typename Derived > bool Eigen::SVDBase< Derived >::m_computeFullU protected
Referenced by Eigen::SVDBase< Derived >::computeU().
m_computeFullV
template<typename Derived > bool Eigen::SVDBase< Derived >::m_computeFullV protected
Referenced by Eigen::SVDBase< Derived >::computeV().
m_computeThinU
template<typename Derived > bool Eigen::SVDBase< Derived >::m_computeThinU protected
Referenced by Eigen::SVDBase< Derived >::computeU().
m_computeThinV
template<typename Derived > bool Eigen::SVDBase< Derived >::m_computeThinV protected
Referenced by Eigen::SVDBase< Derived >::computeV().
m_diagSize
template<typename Derived > internal::variable_if_dynamic<Index, DiagSizeAtCompileTime> Eigen::SVDBase< Derived >::m_diagSize protected
Referenced by Eigen::SVDBase< Derived >::diagSize(), and Eigen::SVDBase< Derived >::threshold().
m_info
template<typename Derived > ComputationInfo Eigen::SVDBase< Derived >::m_info protected
Referenced by Eigen::SVDBase< Derived >::info().
m_isAllocated
template<typename Derived > bool Eigen::SVDBase< Derived >::m_isAllocated protected
m_isInitialized
template<typename Derived > bool Eigen::SVDBase< Derived >::m_isInitialized protected
Referenced by Eigen::SVDBase< Derived >::_check_compute_assertions(), Eigen::SVDBase< Derived >::info(), and Eigen::SVDBase< Derived >::threshold().
m_matrixU
template<typename Derived > MatrixUType Eigen::SVDBase< Derived >::m_matrixU protected
Referenced by Eigen::SVDBase< Derived >::matrixU().
m_matrixV
template<typename Derived > MatrixVType Eigen::SVDBase< Derived >::m_matrixV protected
Referenced by Eigen::SVDBase< Derived >::matrixV().
m_nonzeroSingularValues
template<typename Derived > Index Eigen::SVDBase< Derived >::m_nonzeroSingularValues protected
Referenced by Eigen::SVDBase< Derived >::nonzeroSingularValues(), and Eigen::SVDBase< Derived >::rank().
m_prescribedThreshold
template<typename Derived > RealScalar Eigen::SVDBase< Derived >::m_prescribedThreshold protected
Referenced by Eigen::SVDBase< Derived >::setThreshold(), and Eigen::SVDBase< Derived >::threshold().
m_rows
template<typename Derived > internal::variable_if_dynamic<Index, RowsAtCompileTime> Eigen::SVDBase< Derived >::m_rows protected
Referenced by Eigen::SVDBase< Derived >::rows().
m_singularValues
template<typename Derived > SingularValuesType Eigen::SVDBase< Derived >::m_singularValues protected
Referenced by Eigen::SVDBase< Derived >::rank(), and Eigen::SVDBase< Derived >::singularValues().
m_usePrescribedThreshold
template<typename Derived > bool Eigen::SVDBase< Derived >::m_usePrescribedThreshold protected
Referenced by Eigen::SVDBase< Derived >::setThreshold(), and Eigen::SVDBase< Derived >::threshold().
ShouldComputeFullU
template<typename Derived > constexpr bool Eigen::SVDBase< Derived >::ShouldComputeFullU = internal::traits<Derived>::ShouldComputeFullU static constexpr
ShouldComputeFullV
template<typename Derived > constexpr bool Eigen::SVDBase< Derived >::ShouldComputeFullV = internal::traits<Derived>::ShouldComputeFullV static constexpr
ShouldComputeThinU
template<typename Derived > constexpr bool Eigen::SVDBase< Derived >::ShouldComputeThinU = internal::traits<Derived>::ShouldComputeThinU static constexpr
ShouldComputeThinV
template<typename Derived > constexpr bool Eigen::SVDBase< Derived >::ShouldComputeThinV = internal::traits<Derived>::ShouldComputeThinV static constexpr
The documentation for this class was generated from the following files:
ForwardDeclarations.h
SVDBase.h