MercuryDPM: simplicial_cholesky.cpp File Reference
simplicial_cholesky.cpp File Reference
#include "sparse_solver.h"
Functions
template<typename T , typename I_ , int flag>
void test_simplicial_cholesky_T ()
EIGEN_DECLARE_TEST (simplicial_cholesky)
Function Documentation
EIGEN_DECLARE_TEST()
EIGEN_DECLARE_TEST (simplicial_cholesky)
{
   CALL_SUBTEST_11((test_simplicial_cholesky_T<double, int, ColMajor>()));
   CALL_SUBTEST_12((test_simplicial_cholesky_T<std::complex<double>, int, ColMajor>()));
   CALL_SUBTEST_13((test_simplicial_cholesky_T<double, long int, ColMajor>()));
   CALL_SUBTEST_21((test_simplicial_cholesky_T<double, int, RowMajor>()));
   CALL_SUBTEST_22((test_simplicial_cholesky_T<std::complex<double>, int, RowMajor>()));
   CALL_SUBTEST_23((test_simplicial_cholesky_T<double, long int, RowMajor>()));
 }
References CALL_SUBTEST_11, CALL_SUBTEST_12, CALL_SUBTEST_13, CALL_SUBTEST_21, CALL_SUBTEST_22, CALL_SUBTEST_23, Eigen::ColMajor, Eigen::RowMajor, and test_simplicial_cholesky_T().
test_simplicial_cholesky_T()
template<typename T , typename I_ , int flag> void test_simplicial_cholesky_T ()
{
   typedef SparseMatrix<T, flag, I_> SparseMatrixType;
   SimplicialCholesky<SparseMatrixType, Lower> chol_colmajor_lower_amd;
   SimplicialCholesky<SparseMatrixType, Upper> chol_colmajor_upper_amd;
   SimplicialLLT<SparseMatrixType, Lower> llt_colmajor_lower_amd;
   SimplicialLLT<SparseMatrixType, Upper> llt_colmajor_upper_amd;
   SimplicialLDLT<SparseMatrixType, Lower> ldlt_colmajor_lower_amd;
   SimplicialLDLT<SparseMatrixType, Upper> ldlt_colmajor_upper_amd;
   SimplicialLDLT<SparseMatrixType, Lower, NaturalOrdering<I_> > ldlt_colmajor_lower_nat;
   SimplicialLDLT<SparseMatrixType, Upper, NaturalOrdering<I_> > ldlt_colmajor_upper_nat;
   SimplicialNonHermitianLLT<SparseMatrixType, Lower> nhllt_colmajor_lower_amd;
   SimplicialNonHermitianLLT<SparseMatrixType, Upper> nhllt_colmajor_upper_amd;
   SimplicialNonHermitianLDLT<SparseMatrixType, Lower> nhldlt_colmajor_lower_amd;
   SimplicialNonHermitianLDLT<SparseMatrixType, Upper> nhldlt_colmajor_upper_amd;
   SimplicialNonHermitianLDLT<SparseMatrixType, Lower, NaturalOrdering<I_> > nhldlt_colmajor_lower_nat;
   SimplicialNonHermitianLDLT<SparseMatrixType, Upper, NaturalOrdering<I_> > nhldlt_colmajor_upper_nat;
   check_sparse_spd_solving(chol_colmajor_lower_amd);
   check_sparse_spd_solving(chol_colmajor_upper_amd);
   check_sparse_spd_solving(llt_colmajor_lower_amd);
   check_sparse_spd_solving(llt_colmajor_upper_amd);
   check_sparse_spd_solving(ldlt_colmajor_lower_amd);
   check_sparse_spd_solving(ldlt_colmajor_upper_amd);
   check_sparse_nonhermitian_solving(nhllt_colmajor_lower_amd);
   check_sparse_nonhermitian_solving(nhllt_colmajor_upper_amd);
   check_sparse_nonhermitian_solving(nhldlt_colmajor_lower_amd);
   check_sparse_nonhermitian_solving(nhldlt_colmajor_upper_amd);
   check_sparse_spd_determinant(chol_colmajor_lower_amd);
   check_sparse_spd_determinant(chol_colmajor_upper_amd);
   check_sparse_spd_determinant(llt_colmajor_lower_amd);
   check_sparse_spd_determinant(llt_colmajor_upper_amd);
   check_sparse_spd_determinant(ldlt_colmajor_lower_amd);
   check_sparse_spd_determinant(ldlt_colmajor_upper_amd);
   check_sparse_nonhermitian_determinant(nhllt_colmajor_lower_amd);
   check_sparse_nonhermitian_determinant(nhllt_colmajor_upper_amd);
   check_sparse_nonhermitian_determinant(nhldlt_colmajor_lower_amd);
   check_sparse_nonhermitian_determinant(nhldlt_colmajor_upper_amd);
   check_sparse_spd_solving(ldlt_colmajor_lower_nat, (std::min)(300, EIGEN_TEST_MAX_SIZE), 1000);
   check_sparse_spd_solving(ldlt_colmajor_upper_nat, (std::min)(300, EIGEN_TEST_MAX_SIZE), 1000);
   check_sparse_nonhermitian_solving(nhldlt_colmajor_lower_nat, (std::min)(300, EIGEN_TEST_MAX_SIZE), 1000);
   check_sparse_nonhermitian_solving(nhldlt_colmajor_upper_nat, (std::min)(300, EIGEN_TEST_MAX_SIZE), 1000);
 }
References check_sparse_nonhermitian_determinant(), check_sparse_nonhermitian_solving(), check_sparse_spd_determinant(), check_sparse_spd_solving(), EIGEN_TEST_MAX_SIZE, and min.
Referenced by EIGEN_DECLARE_TEST().