MercuryDPM: Eigen::HessenbergDecomposition< MatrixType_ > Class Template Reference
Eigen::HessenbergDecomposition< MatrixType_ > Class Template Reference
Dense linear problems and decompositions » Reference » Eigenvalues_Module
Reduces a square matrix to Hessenberg form by an orthogonal similarity transformation.
#include <HessenbergDecomposition.h>
Public Types
enum {
Size = MatrixType::RowsAtCompileTime , SizeMinusOne = Size == Dynamic ? Dynamic : Size - 1 , Options = internal::traits<MatrixType>::Options , MaxSize = MatrixType::MaxRowsAtCompileTime ,
MaxSizeMinusOne = MaxSize == Dynamic ? Dynamic : MaxSize - 1
}
typedef MatrixType_ MatrixType
Synonym for the template parameter MatrixType_.
typedef MatrixType::Scalar Scalar
Scalar type for matrices of type MatrixType.
typedef Eigen::Index Index
typedef Matrix< Scalar, SizeMinusOne, 1, Options &~RowMajor, MaxSizeMinusOne, 1 > CoeffVectorType
Type for vector of Householder coefficients.
typedef HouseholderSequence< MatrixType, internal::remove_all_t< typename CoeffVectorType::ConjugateReturnType > > HouseholderSequenceType
Return type of matrixQ()
typedef internal::HessenbergDecompositionMatrixHReturnType< MatrixType > MatrixHReturnType
Public Member Functions
HessenbergDecomposition (Index size=Size==Dynamic ? 2 :Size)
Default constructor; the decomposition will be computed later.
template<typename InputType >
HessenbergDecomposition (const EigenBase< InputType > &matrix)
Constructor; computes Hessenberg decomposition of given matrix.
template<typename InputType >
HessenbergDecomposition & compute (const EigenBase< InputType > &matrix)
Computes Hessenberg decomposition of given matrix.
const CoeffVectorType & householderCoefficients () const
Returns the Householder coefficients.
const MatrixType & packedMatrix () const
Returns the internal representation of the decomposition.
HouseholderSequenceType matrixQ () const
Reconstructs the orthogonal matrix Q in the decomposition.
MatrixHReturnType matrixH () const
Constructs the Hessenberg matrix H in the decomposition.
Protected Attributes
MatrixType m_matrix
CoeffVectorType m_hCoeffs
VectorType m_temp
bool m_isInitialized
Private Types
typedef Matrix< Scalar, 1, Size, int(Options)|int(RowMajor), 1, MaxSize > VectorType
typedef NumTraits< Scalar >::Real RealScalar
Static Private Member Functions
static void _compute (MatrixType &matA, CoeffVectorType &hCoeffs, VectorType &temp)
Detailed Description
template<typename MatrixType_>
class Eigen::HessenbergDecomposition< MatrixType_ >
Reduces a square matrix to Hessenberg form by an orthogonal similarity transformation.
\eigenvalues_module
Template Parameters
MatrixType_ the type of the matrix of which we are computing the Hessenberg decomposition
This class performs an Hessenberg decomposition of a matrix \(A \). In the real case, the Hessenberg decomposition consists of an orthogonal matrix \(Q \) and a Hessenberg matrix \(H \) such that \(A = Q H Q^T \). An orthogonal matrix is a matrix whose inverse equals its transpose (\(Q^{-1} = Q^T \)). A Hessenberg matrix has zeros below the subdiagonal, so it is almost upper triangular. The Hessenberg decomposition of a complex matrix is \(A = Q H Q^* \) with \(Q \) unitary (that is, \(Q^{-1} = Q^* \)).
Call the function compute() to compute the Hessenberg decomposition of a given matrix. Alternatively, you can use the HessenbergDecomposition(const MatrixType&) constructor which computes the Hessenberg decomposition at construction time. Once the decomposition is computed, you can use the matrixH() and matrixQ() functions to construct the matrices H and Q in the decomposition.
The documentation for matrixH() contains an example of the typical use of this class.
See also
class ComplexSchur, class Tridiagonalization, QR Module
Member Typedef Documentation
CoeffVectorType
template<typename MatrixType_ > typedef Matrix<Scalar, SizeMinusOne, 1, Options & ~RowMajor, MaxSizeMinusOne, 1> Eigen::HessenbergDecomposition< MatrixType_ >::CoeffVectorType
Type for vector of Householder coefficients.
This is column vector with entries of type Scalar. The length of the vector is one less than the size of MatrixType, if it is a fixed-side type.
HouseholderSequenceType
template<typename MatrixType_ > typedef HouseholderSequence<MatrixType, internal::remove_all_t<typename CoeffVectorType::ConjugateReturnType> > Eigen::HessenbergDecomposition< MatrixType_ >::HouseholderSequenceType
Return type of matrixQ()
Index
template<typename MatrixType_ > typedef Eigen::Index Eigen::HessenbergDecomposition< MatrixType_ >::Index
Deprecated:
since Eigen 3.3
MatrixHReturnType
template<typename MatrixType_ > typedef internal::HessenbergDecompositionMatrixHReturnType<MatrixType> Eigen::HessenbergDecomposition< MatrixType_ >::MatrixHReturnType
MatrixType
template<typename MatrixType_ > typedef MatrixType_ Eigen::HessenbergDecomposition< MatrixType_ >::MatrixType
Synonym for the template parameter MatrixType_.
RealScalar
template<typename MatrixType_ > typedef NumTraits<Scalar>::Real Eigen::HessenbergDecomposition< MatrixType_ >::RealScalar private
Scalar
template<typename MatrixType_ > typedef MatrixType::Scalar Eigen::HessenbergDecomposition< MatrixType_ >::Scalar
Scalar type for matrices of type MatrixType.
VectorType
template<typename MatrixType_ > typedef Matrix<Scalar, 1, Size, int(Options) | int(RowMajor), 1, MaxSize> Eigen::HessenbergDecomposition< MatrixType_ >::VectorType private
Member Enumeration Documentation
anonymous enum
template<typename MatrixType_ > anonymous enum
Enumerator
Size
SizeMinusOne
Options
MaxSize
MaxSizeMinusOne
        {
     Size = MatrixType::RowsAtCompileTime,
     SizeMinusOne = Size == Dynamic ? Dynamic : Size - 1,
     Options = internal::traits<MatrixType>::Options,
     MaxSize = MatrixType::MaxRowsAtCompileTime,
     MaxSizeMinusOne = MaxSize == Dynamic ? Dynamic : MaxSize - 1
   };
Constructor & Destructor Documentation
HessenbergDecomposition() [1/2]
template<typename MatrixType_ > Eigen::HessenbergDecomposition< MatrixType_ >::HessenbergDecomposition (Index size = Size == Dynamic ? 2 : Size) inline explicit
Default constructor; the decomposition will be computed later.
Parameters
[in] size The size of the matrix whose Hessenberg decomposition will be computed.
The default constructor is useful in cases in which the user intends to perform decompositions via compute(). The size parameter is only used as a hint. It is not an error to give a wrong size, but it may impair performance.
See also
compute() for an example.
                                                                     : Size)
       : m_matrix(size, size), m_temp(size), m_isInitialized(false) {
     if (size > 1) m_hCoeffs.resize(size - 1);
   }
References Eigen::HessenbergDecomposition< MatrixType_ >::m_hCoeffs, Eigen::PlainObjectBase< Derived >::resize(), and size.
HessenbergDecomposition() [2/2]
template<typename MatrixType_ > template<typename InputType > Eigen::HessenbergDecomposition< MatrixType_ >::HessenbergDecomposition (const EigenBase< InputType > & matrix) inline explicit
Constructor; computes Hessenberg decomposition of given matrix.
Parameters
[in] matrix Square matrix whose Hessenberg decomposition is to be computed.
This constructor calls compute() to compute the Hessenberg decomposition.
See also
matrixH() for an example.
       : m_matrix(matrix.derived()), m_temp(matrix.rows()), m_isInitialized(false) {
     if (matrix.rows() < 2) {
       m_isInitialized = true;
       return;
     }
     m_hCoeffs.resize(matrix.rows() - 1, 1);
     _compute(m_matrix, m_hCoeffs, m_temp);
     m_isInitialized = true;
   }
References Eigen::HessenbergDecomposition< MatrixType_ >::_compute(), Eigen::HessenbergDecomposition< MatrixType_ >::m_hCoeffs, Eigen::HessenbergDecomposition< MatrixType_ >::m_isInitialized, Eigen::HessenbergDecomposition< MatrixType_ >::m_matrix, Eigen::HessenbergDecomposition< MatrixType_ >::m_temp, matrix(), and Eigen::PlainObjectBase< Derived >::resize().
Member Function Documentation
_compute()
template<typename MatrixType > void Eigen::HessenbergDecomposition< MatrixType >::_compute (MatrixType & matA, CoeffVectorType & hCoeffs, VectorType & temp) static private
Performs a tridiagonal decomposition of matA in place.
Parameters
matA the input selfadjoint matrix
hCoeffs returned Householder coefficients
The result is written in the lower triangular part of matA.
Implemented from Golub's "%Matrix Computations", algorithm 8.3.1.
See also
packedMatrix()
{
   eigen_assert(matA.rows() == matA.cols());
   Index n = matA.rows();
   temp.resize(n);
   for (Index i = 0; i < n - 1; ++i) {
     // let's consider the vector v = i-th column starting at position i+1
     Index remainingSize = n - i - 1;
     RealScalar beta;
     Scalar h;
     matA.col(i).tail(remainingSize).makeHouseholderInPlace(h, beta);
     matA.col(i).coeffRef(i + 1) = beta;
     hCoeffs.coeffRef(i) = h;
     // Apply similarity transformation to remaining columns,
     // i.e., compute A = H A H'
     // A = H A
     matA.bottomRightCorner(remainingSize, remainingSize)
         .applyHouseholderOnTheLeft(matA.col(i).tail(remainingSize - 1), h, &temp.coeffRef(0));
     // A = A H'
     matA.rightCols(remainingSize)
         .applyHouseholderOnTheRight(matA.col(i).tail(remainingSize - 1), numext::conj(h), &temp.coeffRef(0));
   }
 }
References beta, Eigen::Matrix< Scalar_, Rows_, Cols_, Options_, MaxRows_, MaxCols_ >::coeffRef(), Eigen::PlainObjectBase< Derived >::cols(), conj(), eigen_assert, i, matA(), n, Eigen::PlainObjectBase< Derived >::resize(), and Eigen::PlainObjectBase< Derived >::rows().
Referenced by Eigen::HessenbergDecomposition< MatrixType_ >::compute(), and Eigen::HessenbergDecomposition< MatrixType_ >::HessenbergDecomposition().
compute()
template<typename MatrixType_ > template<typename InputType > HessenbergDecomposition& Eigen::HessenbergDecomposition< MatrixType_ >::compute (const EigenBase< InputType > & matrix) inline
Computes Hessenberg decomposition of given matrix.
Parameters
[in] matrix Square matrix whose Hessenberg decomposition is to be computed.
Returns
Reference to *this
The Hessenberg decomposition is computed by bringing the columns of the matrix successively in the required form using Householder reflections (see, e.g., Algorithm 7.4.2 in Golub & Van Loan, Matrix Computations). The cost is \(10n^3/3 \) flops, where \(n \) denotes the size of the given matrix.
This method reuses of the allocated data in the HessenbergDecomposition object.
Example:
MatrixXcf A = MatrixXcf::Random(4, 4);
HessenbergDecomposition<MatrixXcf> hd(4);
hd.compute(A);
cout << "The matrix H in the decomposition of A is:" << endl << hd.matrixH() << endl;
hd.compute(2 * A);  // re-use hd to compute and store decomposition of 2A
cout << "The matrix H in the decomposition of 2A is:" << endl << hd.matrixH() << endl;
Output:
{
     m_matrix = matrix.derived();
     if (matrix.rows() < 2) {
       m_isInitialized = true;
       return *this;
     }
     m_hCoeffs.resize(matrix.rows() - 1, 1);
     _compute(m_matrix, m_hCoeffs, m_temp);
     m_isInitialized = true;
     return *this;
   }
References Eigen::HessenbergDecomposition< MatrixType_ >::_compute(), Eigen::HessenbergDecomposition< MatrixType_ >::m_hCoeffs, Eigen::HessenbergDecomposition< MatrixType_ >::m_isInitialized, Eigen::HessenbergDecomposition< MatrixType_ >::m_matrix, Eigen::HessenbergDecomposition< MatrixType_ >::m_temp, matrix(), and Eigen::PlainObjectBase< Derived >::resize().
Referenced by ctms_decompositions(), hessenberg(), Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, IsComplex >::run(), and Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, false >::run().
householderCoefficients()
template<typename MatrixType_ > const CoeffVectorType& Eigen::HessenbergDecomposition< MatrixType_ >::householderCoefficients () const inline
Returns the Householder coefficients.
Returns
a const reference to the vector of Householder coefficients
Precondition
Either the constructor HessenbergDecomposition(const MatrixType&) or the member function compute(const MatrixType&) has been called before to compute the Hessenberg decomposition of a matrix.
The Householder coefficients allow the reconstruction of the matrix \(Q \) in the Hessenberg decomposition from the packed data.
See also
packedMatrix(), Householder module
{
     eigen_assert(m_isInitialized && "HessenbergDecomposition is not initialized.");
     return m_hCoeffs;
   }
References eigen_assert, Eigen::HessenbergDecomposition< MatrixType_ >::m_hCoeffs, and Eigen::HessenbergDecomposition< MatrixType_ >::m_isInitialized.
Referenced by hessenberg().
matrixH()
template<typename MatrixType_ > MatrixHReturnType Eigen::HessenbergDecomposition< MatrixType_ >::matrixH () const inline
Constructs the Hessenberg matrix H in the decomposition.
Returns
expression object representing the matrix H
Precondition
Either the constructor HessenbergDecomposition(const MatrixType&) or the member function compute(const MatrixType&) has been called before to compute the Hessenberg decomposition of a matrix.
The object returned by this function constructs the Hessenberg matrix H when it is assigned to a matrix or otherwise evaluated. The matrix H is constructed from the packed matrix as returned by packedMatrix(): The upper part (including the subdiagonal) of the packed matrix contains the matrix H. It may sometimes be better to directly use the packed matrix instead of constructing the matrix H.
Example:
Matrix4f A = MatrixXf::Random(4, 4);
cout << "Here is a random 4x4 matrix:" << endl << A << endl;
HessenbergDecomposition<MatrixXf> hessOfA(A);
MatrixXf H = hessOfA.matrixH();
cout << "The Hessenberg matrix H is:" << endl << H << endl;
MatrixXf Q = hessOfA.matrixQ();
cout << "The orthogonal matrix Q is:" << endl << Q << endl;
cout << "Q H Q^T is:" << endl << Q * H * Q.transpose() << endl;
Output:
See also
matrixQ(), packedMatrix()
{
     eigen_assert(m_isInitialized && "HessenbergDecomposition is not initialized.");
     return MatrixHReturnType(*this);
   }
References eigen_assert, and Eigen::HessenbergDecomposition< MatrixType_ >::m_isInitialized.
Referenced by hessenberg(), Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, IsComplex >::run(), and Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, false >::run().
matrixQ()
template<typename MatrixType_ > HouseholderSequenceType Eigen::HessenbergDecomposition< MatrixType_ >::matrixQ () const inline
Reconstructs the orthogonal matrix Q in the decomposition.
Returns
object representing the matrix Q
Precondition
Either the constructor HessenbergDecomposition(const MatrixType&) or the member function compute(const MatrixType&) has been called before to compute the Hessenberg decomposition of a matrix.
This function returns a light-weight object of template class HouseholderSequence. You can either apply it directly to a matrix or you can convert it to a matrix of type MatrixType.
See also
matrixH() for an example, class HouseholderSequence
{
     eigen_assert(m_isInitialized && "HessenbergDecomposition is not initialized.");
     return HouseholderSequenceType(m_matrix, m_hCoeffs.conjugate()).setLength(m_matrix.rows() - 1).setShift(1);
   }
References eigen_assert, Eigen::HessenbergDecomposition< MatrixType_ >::m_hCoeffs, Eigen::HessenbergDecomposition< MatrixType_ >::m_isInitialized, and Eigen::HessenbergDecomposition< MatrixType_ >::m_matrix.
Referenced by hessenberg(), Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, IsComplex >::run(), and Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, false >::run().
packedMatrix()
template<typename MatrixType_ > const MatrixType& Eigen::HessenbergDecomposition< MatrixType_ >::packedMatrix () const inline
Returns the internal representation of the decomposition.
Returns
a const reference to a matrix with the internal representation of the decomposition.
Precondition
Either the constructor HessenbergDecomposition(const MatrixType&) or the member function compute(const MatrixType&) has been called before to compute the Hessenberg decomposition of a matrix.
The returned matrix contains the following information:
the upper part and lower sub-diagonal represent the Hessenberg matrix H
the rest of the lower part contains the Householder vectors that, combined with Householder coefficients returned by householderCoefficients(), allows to reconstruct the matrix Q as \(Q = H_{N-1} \ldots H_1 H_0 \). Here, the matrices \(H_i \) are the Householder transformations \(H_i = (I - h_i v_i v_i^T) \) where \(h_i \) is the \(i \)th Householder coefficient and \(v_i \) is the Householder vector defined by \(v_i = [ 0, \ldots, 0, 1, M(i+2,i), \ldots, M(N-1,i) ]^T \) with M the matrix returned by this function.
See LAPACK for further details on this packed storage.
Example:
Matrix4d A = Matrix4d::Random(4, 4);
cout << "Here is a random 4x4 matrix:" << endl << A << endl;
HessenbergDecomposition<Matrix4d> hessOfA(A);
Matrix4d pm = hessOfA.packedMatrix();
cout << "The packed matrix M is:" << endl << pm << endl;
cout << "The upper Hessenberg part corresponds to the matrix H, which is:" << endl << hessOfA.matrixH() << endl;
Vector3d hc = hessOfA.householderCoefficients();
cout << "The vector of Householder coefficients is:" << endl << hc << endl;
Output:
See also
householderCoefficients()
{
     eigen_assert(m_isInitialized && "HessenbergDecomposition is not initialized.");
     return m_matrix;
   }
References eigen_assert, Eigen::HessenbergDecomposition< MatrixType_ >::m_isInitialized, and Eigen::HessenbergDecomposition< MatrixType_ >::m_matrix.
Referenced by hessenberg().
Member Data Documentation
m_hCoeffs
template<typename MatrixType_ > CoeffVectorType Eigen::HessenbergDecomposition< MatrixType_ >::m_hCoeffs protected
Referenced by Eigen::HessenbergDecomposition< MatrixType_ >::compute(), Eigen::HessenbergDecomposition< MatrixType_ >::HessenbergDecomposition(), Eigen::HessenbergDecomposition< MatrixType_ >::householderCoefficients(), and Eigen::HessenbergDecomposition< MatrixType_ >::matrixQ().
m_isInitialized
template<typename MatrixType_ > bool Eigen::HessenbergDecomposition< MatrixType_ >::m_isInitialized protected
Referenced by Eigen::HessenbergDecomposition< MatrixType_ >::compute(), Eigen::HessenbergDecomposition< MatrixType_ >::HessenbergDecomposition(), Eigen::HessenbergDecomposition< MatrixType_ >::householderCoefficients(), Eigen::HessenbergDecomposition< MatrixType_ >::matrixH(), Eigen::HessenbergDecomposition< MatrixType_ >::matrixQ(), and Eigen::HessenbergDecomposition< MatrixType_ >::packedMatrix().
m_matrix
template<typename MatrixType_ > MatrixType Eigen::HessenbergDecomposition< MatrixType_ >::m_matrix protected
Referenced by Eigen::HessenbergDecomposition< MatrixType_ >::compute(), Eigen::HessenbergDecomposition< MatrixType_ >::HessenbergDecomposition(), Eigen::HessenbergDecomposition< MatrixType_ >::matrixQ(), and Eigen::HessenbergDecomposition< MatrixType_ >::packedMatrix().
m_temp
template<typename MatrixType_ > VectorType Eigen::HessenbergDecomposition< MatrixType_ >::m_temp protected
Referenced by Eigen::HessenbergDecomposition< MatrixType_ >::compute(), and Eigen::HessenbergDecomposition< MatrixType_ >::HessenbergDecomposition().
The documentation for this class was generated from the following file:
HessenbergDecomposition.h