MercuryDPM: Tutorial1_ParticleInOuterSpace.cpp File Reference
Tutorial1_ParticleInOuterSpace.cpp File Reference
#include <Mercury3D.h>
#include <Species/Species.h>
#include <Species/LinearViscoelasticSpecies.h>
Classes
class Tutorial1
[T1:headers]
Functions
int main (int argc, char *argv[])
[T1:class]
Function Documentation
main()
int main (int argc , char * argv[])
[T1:class]
[T1:main]
[T1:problemSetup]
[T1:problemSetup]
[T1:speciesProp]
[T1:speciesProp]
[T1:output]
[T1:output]
[T1:paraviewOutput]
[T1:paraviewOutput]
[T1:solve]
[T1:solve]
 {
     // Instantiate an object of class Tutorial1
     Tutorial1 problem;
     // Problem setup: set file name, gravity, domain size, simulation time
     problem.setName("Tutorial1");
     problem.setGravity(Vec3D(0.0, 0.0, 0.0));
     problem.setXMax(1.0);
     problem.setYMax(1.0);
     problem.setZMax(1.0);
     problem.setTimeMax(1.0);
     // Set the species (material properties such as density and stiffness) of particles and walls
     // (in this case, both are assumed to consist of the same material)
     LinearViscoelasticSpecies species;
     species.setDensity(2500.0); //sets the species type_0 density in kg/m3
     // The normal spring stiffness and normal dissipation is computed such that
     // collision time tc=0.005 and restitution coefficient rc=1.0
     species.setStiffness(258.5);//sets the spring stiffness in kN/m.
     species.setDissipation(0.0); //sets the dissipation.
     problem.speciesHandler.copyAndAddObject(species);
     // Define what output gets written
     // number of time steps skipped between saves (i.e. every 10-th time step is written to file)
     problem.setSaveCount(50);
     // creates file with particle positions, velocities, radii for multiple time steps (for plotting)
     problem.dataFile.setFileType(FileType::ONE_FILE);
     // file with contact forces, overlaps for multiple time steps (for plotting)
     problem.fStatFile.setFileType(FileType::NO_FILE);
     // file with all parameters of the last saved time step (for restarting)
     problem.restartFile.setFileType(FileType::ONE_FILE);
     // writes global properties like kinetic/potential energy and center of mass (for quick analysis)
     problem.eneFile.setFileType(FileType::NO_FILE);
     // whether the wall geometry is written into a vtu file (either once initially or for several time steps)
     problem.wallHandler.setWriteVTK(FileType::ONE_FILE);
     // whether the particle positions are written into a vtu file
     problem.setParticlesWriteVTK(true);
     // set a time step 1/50th of collision time
     problem.setTimeStep(0.005 / 50.0);
     // start the solver (calls setupInitialConditions and initiates time loop)
     problem.solve(argc, argv);
     return 0;
 }
References NO_FILE, ONE_FILE, problem, ParticleSpecies::setDensity(), LinearViscoelasticNormalSpecies::setDissipation(), and LinearViscoelasticNormalSpecies::setStiffness().