MercuryDPM: CubicPackingSelfTest.cpp File Reference
CubicPackingSelfTest.cpp File Reference
#include "Mercury3D.h"
#include "StatisticsVector.h"
#include "Walls/InfiniteWall.h"
#include <cmath>
#include <iostream>
#include <iomanip>
#include <Species/LinearViscoelasticSpecies.h>
Classes
class NewtonsCradleSelftest
In this file a cubic packing of 5^3 particles in a tri-axial box is created and allowed to settle under small gravity. After that Z statistics are calculated.
Functions
int main (int argc UNUSED, char *argv[] UNUSED)
Function Documentation
main()
int main (int argc UNUSED, char *argv[] UNUSED)
should give you Density 1
 {
     NewtonsCradleSelftest problem;
     problem.setName("CubicPackingSelfTest");
     auto species=problem.speciesHandler.copyAndAddObject(LinearViscoelasticSpecies());
     //set the number of particles
     problem.N = 5;
     problem.setSystemDimensions(3);
     problem.speciesHandler.getObject(0)->setDensity(1.9098593);
     problem.setGravity(Vec3D(0., 0., -1.));
     species->setCollisionTimeAndRestitutionCoefficient(.01, .1, 1.);
     problem.setTimeStep(.0002);
     problem.setTimeMax(0.2);
     problem.setSaveCount(1000);
     problem.solve();
     StatisticsVector<Z> stats("CubicPackingSelfTest");
     int n = 500;
     stats.setN(n);
     stats.setCGWidth(.1);
     stats.setSuperExact(false);
     stats.setCGShape("Gaussian");
     stats.setCGTimeMin(problem.getTimeMax() * .999999);
     stats.setTimeMaxStat(1e20);
     stats.setVerbosityLevel(0);
     stats.statistics_from_fstat_and_data();
 }
References n, problem, StatisticsVector< T >::setCGShape(), StatisticsVector< T >::setCGTimeMin(), StatisticsVector< T >::setCGWidth(), StatisticsVector< T >::setN(), StatisticsVector< T >::setSuperExact(), StatisticsVector< T >::setTimeMaxStat(), StatisticsVector< T >::setVerbosityLevel(), and StatisticsVector< T >::statistics_from_fstat_and_data().