MercuryDPM: oomph::TElement< 3, NNODE_1D > Class Template Reference
oomph::TElement< 3, NNODE_1D > Class Template Reference
#include <Telements.h>
Public Member Functions
TElement ()
Constructor.
TElement (const TElement &)=delete
Broken copy constructor.
~TElement ()
Broken assignment operator.
unsigned nnode_1d () const
Number of nodes along each element edge.
unsigned nvertex_node () const
unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
Public access function for Node_on_face.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
void shape (const Vector< double > &s, Shape &psi) const
Calculate the geometric shape functions at local coordinate s.
void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double s_min () const
Min. value of local coordinate.
double s_max () const
Max. value of local coordinate.
void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
Return local coordinates of node j.
unsigned nplot_points_paraview (const unsigned &nplot) const
unsigned nsub_elements_paraview (const unsigned &nplot) const
void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
void output (std::ostream &output)
Output.
void output (std::ostream &outfile, const unsigned &nplot)
Output at specified number of plot points.
void output (FILE *file_pt)
C-style output.
void output (FILE *file_pt, const unsigned &n_plot)
C_style output at n_plot points.
void get_s_plot (const unsigned &iplot, const unsigned &nplot, Vector< double > &s, const bool &use_equally_spaced_interior_sample_points=false) const
std::string tecplot_zone_string (const unsigned &nplot) const
void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
unsigned nplot_points (const unsigned &nplot) const
void build_face_element (const int &face_index, FaceElement *face_element_pt)
Public Member Functions inherited from oomph::TElementBase
TElementBase ()
Empty default constructor.
TElementBase (const TElementBase &)=delete
Broken copy constructor.
ElementGeometry::ElementGeometry element_geometry () const
Broken assignment operator.
bool local_coord_is_valid (const Vector< double > &s)
Check whether the local coordinates are valid or not.
void move_local_coord_back_into_element (Vector< double > &s) const
Public Member Functions inherited from oomph::TElementGeometricBase
TElementGeometricBase ()
Empty default constructor.
TElementGeometricBase (const TElementGeometricBase &)=delete
Broken copy constructor.
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
virtual void disable_ALE ()
virtual void enable_ALE ()
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output an exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output a time-dependent exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual unsigned self_test ()
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Static Private Attributes
static const unsigned Node_on_face [4][(NNODE_1D *(NNODE_1D+1))/2]
Nodal translation scheme for use when generating face elements.
static TGauss< 3, NNODE_1D > Default_integration_scheme
Additional Inherited Members
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
virtual void fill_in_contribution_to_residuals (Vector< double > &residuals)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
template<unsigned NNODE_1D>
class oomph::TElement< 3, NNODE_1D >
General TElement class specialised to three spatial dimensions (tet) Ordering of nodes inverted from Zienkiewizc sketches: When looking into the tet from vertex node 0. The vertex nodes on the opposite face are 1 - 2 - 3 in anticlockwise direction. Other nodes filled in edge by edge, then the face ones, then the internal ones.
Constructor & Destructor Documentation
TElement() [1/2]
template<unsigned NNODE_1D> oomph::TElement< 3, NNODE_1D >::TElement () inline
Constructor.
     {
       switch (NNODE_1D)
       {
         case 2:
         case 3:
           break;
           /*     case 4: */
           /*      n_node = 20; */
           /*      break; */
         default:
           std::string error_message =
             "Tets are currently only implemented for\n";
           error_message += "four and ten nodes, i.e. NNODE_1D=2 , 3 \n";
           throw OomphLibError(
             error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
       // Set the number of nodes
       unsigned n_node =
         (NNODE_1D * (NNODE_1D + 1)) / 2 + 1 + 3 * (NNODE_1D - 2);
       this->set_n_node(n_node);
       // Set the elemental and nodal dimensions
       set_dimension(3);
       // Assign default (full) spatial integration scheme
       set_integration_scheme(&Default_integration_scheme);
     }
References OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Global_string_for_annotation::string().
TElement() [2/2]
template<unsigned NNODE_1D> oomph::TElement< 3, NNODE_1D >::TElement (const TElement< 3, NNODE_1D > &) delete
Broken copy constructor.
~TElement()
template<unsigned NNODE_1D> oomph::TElement< 3, NNODE_1D >::~TElement () inline
Broken assignment operator.
Destructor
 {}
Member Function Documentation
build_face_element()
template<unsigned NNODE_1D> void oomph::TElement< 3, NNODE_1D >::build_face_element (const int & face_index, FaceElement * face_element_pt) virtual
Build the lower-dimensional FaceElement (an element of type TElement<2,NNODE_1D>). The face index can take one of four values corresponding to the four possible faces: 0: (left) s[0] = 0.0 1: (bottom) s[1] = 0.0 2: (back) s[2] = 0.0 3: (sloping face) s[0] + s[1] + s[2] = 1
Function to setup geometrical information for lower-dimensional FaceElements (which are of type TElement<2,NNODE_1D>).
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::SolidTElement< 3, NNODE_1D >.
   {
     // Set the nodal dimension
     face_element_pt->set_nodal_dimension(nodal_dimension());
     // Set the pointer to the orginal "bulk" element
     face_element_pt->bulk_element_pt() = this;
 #ifdef OOMPH_HAS_MPI
     // Pass on non-halo proc ID
     face_element_pt->set_halo(Non_halo_proc_ID);
 #endif
     // Calculate the number of nodes in the face element
     const unsigned n_face_nodes = (NNODE_1D * (NNODE_1D + 1)) / 2;
     // Resize storage for the number of values originally stored
     // at the face element's nodes.
     face_element_pt->nbulk_value_resize(n_face_nodes);
     // Resize storage for the bulk node numbers corresponding to
     // the nodes of the face
     face_element_pt->bulk_node_number_resize(n_face_nodes);
     // Set the face index in the face element
     face_element_pt->face_index() = face_index;
     // So the faces are
     // 0 : s_0 fixed
     // 1 : s_1 fixed
     // 2 : s_2 fixed
     // 3 : sloping face
     // Copy nodes across to the face
     for (unsigned i = 0; i < n_face_nodes; i++)
     {
       // The number is just offset by one
       unsigned bulk_number = Node_on_face[face_index][i];
       face_element_pt->node_pt(i) = node_pt(bulk_number);
       face_element_pt->bulk_node_number(i) = bulk_number;
       // set the number of values originally stored at this node
       face_element_pt->nbulk_value(i) = required_nvalue(bulk_number);
     }
     // Now set up the node pointers and the normal vectors
     switch (face_index)
     {
         //
         //-----The face s0 is constant
       case 0:
         // Set the pointer to the function that determines the bulk
         // coordinates in the face element
         face_element_pt->face_to_bulk_coordinate_fct_pt() =
           &TElement3FaceToBulkCoordinates::face0;
         // Outer unit normal is the negative cross product of two in plane
         // tangent vectors
         face_element_pt->normal_sign() = -1;
         break;
         //-----The face s1 is constant
       case 1:
         // Set the pointer to the function that determines the bulk
         // coordinates in the face element
         face_element_pt->face_to_bulk_coordinate_fct_pt() =
           &TElement3FaceToBulkCoordinates::face1;
         // Outer unit normal is the positive cross product of two in plane
         // tangent vectors
         face_element_pt->normal_sign() = +1;
         break;
         //
         //-----The face s2 is constant
       case 2:
         // Set the pointer to the function that determines the bulk
         // coordinates in the face element
         face_element_pt->face_to_bulk_coordinate_fct_pt() =
           &TElement3FaceToBulkCoordinates::face2;
         // Outer unit normal is the negative cross product of two in plane
         // tangent vectors
         face_element_pt->normal_sign() = -1;
         break;
         //-----The sloping face of the tetrahedron
       case 3:
         // Set the pointer to the function that determines the bulk
         // coordinates in the face element
         face_element_pt->face_to_bulk_coordinate_fct_pt() =
           &TElement3FaceToBulkCoordinates::face3;
         // Outer unit normal is the positive cross product of two in plane
         // tangent vectors
         face_element_pt->normal_sign() = +1;
         break;
       default:
         std::ostringstream error_message;
         error_message << "Face_index should only take "
                       << "the values 0, 1, 2 or 3, not " << face_index
                       << std::endl;
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
     } // end switch
   }
References oomph::FaceElement::bulk_element_pt(), oomph::FaceElement::bulk_node_number(), oomph::FaceElement::bulk_node_number_resize(), oomph::TElement3FaceToBulkCoordinates::face0(), oomph::TElement3FaceToBulkCoordinates::face1(), oomph::TElement3FaceToBulkCoordinates::face2(), oomph::TElement3FaceToBulkCoordinates::face3(), oomph::FaceElement::face_index(), oomph::FaceElement::face_to_bulk_coordinate_fct_pt(), i, oomph::FaceElement::nbulk_value(), oomph::FaceElement::nbulk_value_resize(), oomph::TElement< DIM, NNODE_1D >::Node_on_face(), oomph::FiniteElement::node_pt(), oomph::FaceElement::normal_sign(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::FiniteElement::set_nodal_dimension().
d2shape_local()
template<unsigned NNODE_1D> void oomph::TElement< 3, NNODE_1D >::d2shape_local (const Vector< double > & s, Shape & psi, DShape & dpsids, DShape & d2psids) const inline virtual
Compute the geometric shape functions, derivatives and second derivatives w.r.t local coordinates at local coordinate s. d2psids(i,0) = \(\partial^2 \psi_j / \partial s_0^2 \) d2psids(i,1) = \(\partial^2 \psi_j / \partial s_1^2 \) d2psids(i,2) = \(\partial^2 \psi_j / \partial s_2^2 \) d2psids(i,3) = \(\partial^2 \psi_j / \partial s_0 \partial s_1 \) d2psids(i,4) = \(\partial^2 \psi_j / \partial s_0 \partial s_2 \) d2psids(i,5) = \(\partial^2 \psi_j / \partial s_1 \partial s_2 \)
Reimplemented from oomph::FiniteElement.
     {
       TElementShape<3, NNODE_1D>::d2shape_local(s, psi, dpsids, d2psids);
     }
References s.
dshape_local()
template<unsigned NNODE_1D> void oomph::TElement< 3, NNODE_1D >::dshape_local (const Vector< double > & s, Shape & psi, DShape & dpsids) const inline virtual
Compute the geometric shape functions and derivatives w.r.t. local coordinates at local coordinate s
Reimplemented from oomph::FiniteElement.
     {
       TElementShape<3, NNODE_1D>::dshape_local(s, psi, dpsids);
     }
References s.
get_bulk_node_number()
template<unsigned NNODE_1D> unsigned oomph::TElement< 3, NNODE_1D >::get_bulk_node_number (const int & face_index, const unsigned & i) const inline virtual
Public access function for Node_on_face.
Reimplemented from oomph::FiniteElement.
     {
       return Node_on_face[face_index][i];
     }
References i, and oomph::TElement< DIM, NNODE_1D >::Node_on_face().
get_s_plot()
template<unsigned NNODE_1D> void oomph::TElement< 3, NNODE_1D >::get_s_plot (const unsigned & iplot, const unsigned & nplot, Vector< double > & s, const bool & use_equally_spaced_interior_sample_points = false) const inline virtual
Get vector of local coordinates of plot point i (when plotting nplot points in each "coordinate direction).
Reimplemented from oomph::FiniteElement.
     {
       if (nplot > 1)
       {
         unsigned np = 0;
         for (unsigned i = 0; i < nplot; ++i)
         {
           for (unsigned j = 0; j < nplot - i; ++j)
           {
             for (unsigned k = 0; k < nplot - i - j; ++k)
             {
               if (np == iplot)
               {
                 {
                   s[0] = double(j) / double(nplot - 1);
                   s[1] = double(i) / double(nplot - 1);
                   s[2] = double(k) / double(nplot - 1);
                   if (use_equally_spaced_interior_sample_points)
                   {
                     double range = 1.0;
                     double dx_new = range / double(nplot + 1);
                     double range_new = double(nplot - 1) * dx_new;
                     s[0] = 0.5 * dx_new + range_new * s[0] / range;
                     s[1] = 0.5 * dx_new + range_new * s[1] / range;
                     s[2] = 0.5 * dx_new + range_new * s[2] / range;
                   }
                   return;
                 }
               }
               np++;
             }
           }
         }
       }
       else
       {
         s[0] = 1.0 / 4.0;
         s[1] = 1.0 / 4.0;
         s[2] = 1.0 / 4.0;
       }
     }
References i, j, k, and s.
invert_jacobian_mapping()
template<unsigned NNODE_1D> double oomph::TElement< 3, NNODE_1D >::invert_jacobian_mapping (const DenseMatrix< double > & jacobian, DenseMatrix< double > & inverse_jacobian) const inline virtual
Overload the template-free interface for the calculation of inverse jacobian matrix. This is a three dimensional element, so use the 3D version.
Reimplemented from oomph::FiniteElement.
     {
       return FiniteElement::invert_jacobian<3>(jacobian, inverse_jacobian);
     }
local_coordinate_of_node()
template<unsigned NNODE_1D> void oomph::TElement< 3, NNODE_1D >::local_coordinate_of_node (const unsigned & j, Vector< double > & s) const inline virtual
Return local coordinates of node j.
Reimplemented from oomph::FiniteElement.
     {
       TElementShape<3, NNODE_1D>::local_coordinate_of_node(j, s);
     }
References j, and s.
nnode_1d()
template<unsigned NNODE_1D> unsigned oomph::TElement< 3, NNODE_1D >::nnode_1d () const inline virtual
Number of nodes along each element edge.
Reimplemented from oomph::FiniteElement.
     {
       return NNODE_1D;
     }
nplot_points()
template<unsigned NNODE_1D> unsigned oomph::TElement< 3, NNODE_1D >::nplot_points (const unsigned & nplot) const inline virtual
Return total number of plot points (when plotting nplot points in each "coordinate direction)
Reimplemented from oomph::FiniteElement.
     {
       unsigned res = 0;
       if (nplot > 1)
       {
         res = 4;
         for (unsigned i = 3; i <= nplot; i++)
         {
           res += (i * (i + 1) / 2);
         }
         return res;
       }
       // Otherwise we return 1(?)
       return 1;
     }
References i, and res.
nplot_points_paraview()
template<unsigned NNODE_1D> unsigned oomph::TElement< 3, NNODE_1D >::nplot_points_paraview (const unsigned & nplot) const inline virtual
Return the number of actual plot points for paraview plot with parameter nplot.
Reimplemented from oomph::FiniteElement.
     {
       unsigned node_sum = 0;
       for (unsigned j = 1; j <= nplot; j++)
       {
         for (unsigned i = 1; i <= j; i++)
         {
           node_sum += i;
         }
       }
       return node_sum;
     }
References i, and j.
nsub_elements_paraview()
template<unsigned NNODE_1D> unsigned oomph::TElement< 3, NNODE_1D >::nsub_elements_paraview (const unsigned & nplot) const inline virtual
Return the number of local sub-elements for paraview plot with parameter nplot.
Reimplemented from oomph::FiniteElement.
     {
       return (nplot - 1) * (nplot - 1) * (nplot - 1);
     }
nvertex_node()
template<unsigned NNODE_1D> unsigned oomph::TElement< 3, NNODE_1D >::nvertex_node () const inline virtual
Number of vertex nodes in the element: One more than spatial dimension
Reimplemented from oomph::FiniteElement.
     {
       return 4;
     }
output() [1/4]
template<unsigned NNODE_1D> void oomph::TElement< 3, NNODE_1D >::output (FILE * file_pt) virtual
C-style output.
The C-style output function for TElement<3,NNODE_1D>
Reimplemented from oomph::FiniteElement.
   {
     output(file_pt, NNODE_1D);
   }
References oomph::output().
output() [2/4]
template<unsigned NNODE_1D> void oomph::TElement< 3, NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) virtual
C_style output at n_plot points.
The C-style output function for TElement<3,NNODE_1D>
Reimplemented from oomph::FiniteElement.
   {
     // Vector of local coordinates
     Vector<double> s(3);
     // Find the dimension of the nodes
     unsigned n_dim = this->nodal_dimension();
     // Tecplot header info
     fprintf(file_pt, "%s \n", tecplot_zone_string(nplot).c_str());
     // Loop over plot points
     unsigned num_plot_points = nplot_points(nplot);
     for (unsigned iplot = 0; iplot < num_plot_points; iplot++)
     {
       // Get local coordinates of plot point
       get_s_plot(iplot, nplot, s);
       for (unsigned i = 0; i < n_dim; i++)
       {
         fprintf(file_pt, "%g ", interpolated_x(s, i));
         // outfile << interpolated_x(s,i) << " ";
       }
       fprintf(file_pt, "\n");
       // outfile << std::endl;
     }
     // Write tecplot footer (e.g. FE connectivity lists)
     write_tecplot_zone_footer(file_pt, nplot);
   }
References i, and s.
output() [3/4]
template<unsigned NNODE_1D> void oomph::TElement< 3, NNODE_1D >::output (std::ostream & outfile, const unsigned & nplot) virtual
Output at specified number of plot points.
The output function for TElement<3,NNODE_1D>
Reimplemented from oomph::FiniteElement.
   {
     // Vector of local coordinates
     Vector<double> s(3);
     // Find the dimension of the nodes
     unsigned n_dim = this->nodal_dimension();
     // Tecplot header info
     outfile << tecplot_zone_string(nplot);
     // Loop over plot points
     unsigned num_plot_points = nplot_points(nplot);
     for (unsigned iplot = 0; iplot < num_plot_points; iplot++)
     {
       // Get local coordinates of plot point
       get_s_plot(iplot, nplot, s);
       for (unsigned i = 0; i < n_dim; i++)
       {
         outfile << interpolated_x(s, i) << " ";
       }
       outfile << "\n";
     }
     // Write tecplot footer (e.g. FE connectivity lists)
     write_tecplot_zone_footer(outfile, nplot);
   }
References i, and s.
output() [4/4]
template<unsigned NNODE_1D> void oomph::TElement< 3, NNODE_1D >::output (std::ostream & outfile) virtual
Output.
The output function for TElement<3,NNODE_1D>
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Reimplemented from oomph::FiniteElement.
   {
     output(outfile, NNODE_1D);
   }
References oomph::output().
s_max()
template<unsigned NNODE_1D> double oomph::TElement< 3, NNODE_1D >::s_max () const inline virtual
Max. value of local coordinate.
Reimplemented from oomph::FiniteElement.
     {
       return 1.0;
     }
s_min()
template<unsigned NNODE_1D> double oomph::TElement< 3, NNODE_1D >::s_min () const inline virtual
Min. value of local coordinate.
Reimplemented from oomph::FiniteElement.
     {
       return 0.0;
     }
shape()
template<unsigned NNODE_1D> void oomph::TElement< 3, NNODE_1D >::shape (const Vector< double > & s, Shape & psi) const inline virtual
Calculate the geometric shape functions at local coordinate s.
Implements oomph::FiniteElement.
     {
       TElementShape<3, NNODE_1D>::shape(s, psi);
     }
References s, and oomph::OneDimLagrange::shape().
tecplot_zone_string()
template<unsigned NNODE_1D> std::string oomph::TElement< 3, NNODE_1D >::tecplot_zone_string (const unsigned & nplot) const inline virtual
Return string for tecplot zone header (when plotting nplot points in each "coordinate direction)
Reimplemented from oomph::FiniteElement.
     {
       std::ostringstream header;
       unsigned nel = 0;
       nel = (nplot - 1) * (nplot - 1) * (nplot - 1);
       header << "ZONE N=" << nplot_points(nplot) << ", E=" << nel
              << ", F=FEPOINT, ET=TETRAHEDRON\n";
       return header.str();
     }
vertex_node_pt()
template<unsigned NNODE_1D> Node* oomph::TElement< 3, NNODE_1D >::vertex_node_pt (const unsigned & j) const inline virtual
Pointer to the j-th vertex node in the element.
Reimplemented from oomph::FiniteElement.
     {
       // Vertex nodes come first:
 #ifdef PARANOID
       if (j > 3)
       {
         std::ostringstream error_message;
         error_message
           << "Element only has four vertex nodes; called with node number " << j
           << std::endl;
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       return node_pt(j);
     }
References j, OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
write_paraview_offsets()
template<unsigned NNODE_1D> void oomph::TElement< 3, NNODE_1D >::write_paraview_offsets (std::ofstream & file_out, const unsigned & nplot, unsigned & offset_sum) const inline virtual
Return the offsets for the paraview sub-elements. Needs to be implemented for each new geometric element type; see http://www.vtk.org/VTK/img/file-formats.pdf
Reimplemented from oomph::FiniteElement.
     {
       unsigned local_loop = nsub_elements_paraview(nplot);
       for (unsigned i = 0; i < local_loop; i++)
       {
         offset_sum += 4;
         file_out << offset_sum << std::endl;
       }
     }
References i.
write_paraview_output_offset_information()
template<unsigned NNODE_1D> void oomph::TElement< 3, NNODE_1D >::write_paraview_output_offset_information (std::ofstream & file_out, const unsigned & nplot, unsigned & counter) const inline virtual
Fill in the offset information for paraview plot. Needs to be implemented for each new geometric element type; see http://www.vtk.org/VTK/img/file-formats.pdf
Reimplemented from oomph::FiniteElement.
     {
       // Output node lists for sub elements for Paraview (node index
       // must start at 0, fixed with magical counter-1)
       unsigned paraview_fix = counter - 1;
       unsigned nod_count = 1;
       for (unsigned i = 0; i < nplot; i++)
       {
         for (unsigned j = 0; j < nplot - i; j++)
         {
           for (unsigned k = 0; k < nplot - i - j; k++)
           {
             if (k < nplot - i - j - 1)
             {
               file_out << nod_count + paraview_fix << " "
                        << nod_count + 1 + paraview_fix << " "
                        << nod_count + nplot - i - j + paraview_fix << " "
                        << nod_count + nplot - i - j +
                             ((nplot - 1 - i) * (nplot - i) / 2) + paraview_fix
                        << std::endl;
               if (k < nplot - i - j - 2)
               {
                 file_out << nod_count + 1 + paraview_fix << " "
                          << nod_count + nplot - i - j + paraview_fix << " "
                          << nod_count + nplot - i - j +
                               ((nplot - 1 - i) * (nplot - i) / 2) + paraview_fix
                          << " "
                          << nod_count + 2 * (nplot - i - j) - 1 +
                               ((nplot - 1 - i) * (nplot - i) / 2) + paraview_fix
                          << std::endl;
                 file_out << nod_count + 1 + paraview_fix << " "
                          << nod_count + nplot - i - j + paraview_fix << " "
                          << nod_count + nplot - i - j + 1 + paraview_fix << " "
                          << nod_count + 2 * (nplot - i - j) - 1 +
                               ((nplot - 1 - i) * (nplot - i) / 2) + paraview_fix
                          << std::endl;
                 file_out << nod_count + 1 + paraview_fix << " "
                          << nod_count + nplot - i - j +
                               ((nplot - 1 - i) * (nplot - i) / 2) + paraview_fix
                          << " "
                          << nod_count + nplot - i - j +
                               ((nplot - 1 - i) * (nplot - i) / 2) + 1 +
                               paraview_fix
                          << " "
                          << nod_count + 2 * (nplot - i - j) - 1 +
                               ((nplot - 1 - i) * (nplot - i) / 2) + paraview_fix
                          << std::endl;
                 file_out << nod_count + 1 + paraview_fix << " "
                          << nod_count + nplot - i - j + 1 + paraview_fix << " "
                          << nod_count + nplot - i - j +
                               ((nplot - 1 - i) * (nplot - i) / 2) + 1 +
                               paraview_fix
                          << " "
                          << nod_count + 2 * (nplot - i - j) - 1 +
                               ((nplot - 1 - i) * (nplot - i) / 2) + paraview_fix
                          << std::endl;
               }
               if (k > 1)
               {
                 file_out << nod_count + nplot - i - j - 1 + paraview_fix << " "
                          << nod_count + nplot - i - j +
                               ((nplot - 1 - i) * (nplot - i) / 2) - 1 +
                               paraview_fix
                          << " "
                          << nod_count + 2 * (nplot - i - j - 1) +
                               ((nplot - 1 - i) * (nplot - i) / 2) - 1 +
                               paraview_fix
                          << " "
                          << nod_count + 2 * (nplot - i - j - 1) +
                               ((nplot - 1 - i) * (nplot - i) / 2) + paraview_fix
                          << std::endl;
               }
             } // end if(k<nplot-i-j-1)
             ++nod_count;
           }
         }
       }
       // increment the counter to keep track of global connectivity
       counter += nplot_points_paraview(nplot);
     } // end of write Paraview_element...
References i, j, and k.
write_paraview_type()
template<unsigned NNODE_1D> void oomph::TElement< 3, NNODE_1D >::write_paraview_type (std::ofstream & file_out, const unsigned & nplot) const inline virtual
Return the paraview element type. Needs to be implemented for each new geometric element type; see http://www.vtk.org/VTK/img/file-formats.pdf
Reimplemented from oomph::FiniteElement.
     {
       unsigned local_loop = nsub_elements_paraview(nplot);
       for (unsigned i = 0; i < local_loop; i++)
       {
         file_out << "10" << std::endl;
       }
     }
References i.
write_tecplot_zone_footer() [1/2]
template<unsigned NNODE_1D> void oomph::TElement< 3, NNODE_1D >::write_tecplot_zone_footer (FILE * file_pt, const unsigned & nplot) const inline virtual
Add tecplot zone "footer" to C-style output. (when plotting nplot points in each "coordinate direction). Empty by default – can be used, e.g., to add FE connectivity lists to elements that need it.
Reimplemented from oomph::FiniteElement.
     {
       // Output node lists for sub elements for Tecplot (node index
       // must start at 1)
       unsigned nod_count = 1;
       for (unsigned i = 0; i < nplot; i++)
       {
         for (unsigned j = 0; j < nplot - i; j++)
         {
           for (unsigned k = 0; k < nplot - i - j; k++)
           {
             if (j < nplot - i - 1)
             {
               fprintf(file_pt,
                       "%i %i %i \n",
                       nod_count,
                       nod_count + 1,
                       nod_count + nplot - i);
               if (j < nplot - i - 2)
               {
                 fprintf(file_pt,
                         "%i %i %i \n",
                         nod_count + 1,
                         nod_count + nplot - i + 1,
                         nod_count + nplot - i);
               }
             }
             ++nod_count;
           }
         }
       }
     }
References i, j, and k.
write_tecplot_zone_footer() [2/2]
template<unsigned NNODE_1D> void oomph::TElement< 3, NNODE_1D >::write_tecplot_zone_footer (std::ostream & outfile, const unsigned & nplot) const inline virtual
Add tecplot zone "footer" to output stream (when plotting nplot points in each "coordinate direction). Empty by default – can be used, e.g., to add FE connectivity lists to elements that need it.
Reimplemented from oomph::FiniteElement.
     {
       // Output node lists for sub elements for Tecplot (node index
       // must start at 1)
       unsigned nod_count = 1;
       for (unsigned i = 0; i < nplot; i++)
       {
         for (unsigned j = 0; j < nplot - i; j++)
         {
           for (unsigned k = 0; k < nplot - i - j; k++)
           {
             if (k < nplot - i - j - 1)
             {
               outfile << nod_count << " " << nod_count + 1 << " "
                       << nod_count + nplot - i - j << " "
                       << nod_count + nplot - i - j +
                            ((nplot - 1 - i) * (nplot - i) / 2)
                       << std::endl;
               if (k < nplot - i - j - 2)
               {
                 outfile << nod_count + 1 << " " << nod_count + nplot - i - j
                         << " "
                         << nod_count + nplot - i - j +
                              ((nplot - 1 - i) * (nplot - i) / 2)
                         << " "
                         << nod_count + 2 * (nplot - i - j) - 1 +
                              ((nplot - 1 - i) * (nplot - i) / 2)
                         << std::endl;
                 outfile << nod_count + 1 << " " << nod_count + nplot - i - j
                         << " " << nod_count + nplot - i - j + 1 << " "
                         << nod_count + 2 * (nplot - i - j) - 1 +
                              ((nplot - 1 - i) * (nplot - i) / 2)
                         << std::endl;
                 outfile << nod_count + 1 << " "
                         << nod_count + nplot - i - j +
                              ((nplot - 1 - i) * (nplot - i) / 2)
                         << " "
                         << nod_count + nplot - i - j +
                              ((nplot - 1 - i) * (nplot - i) / 2) + 1
                         << " "
                         << nod_count + 2 * (nplot - i - j) - 1 +
                              ((nplot - 1 - i) * (nplot - i) / 2)
                         << std::endl;
                 outfile << nod_count + 1 << " " << nod_count + nplot - i - j + 1
                         << " "
                         << nod_count + nplot - i - j +
                              ((nplot - 1 - i) * (nplot - i) / 2) + 1
                         << " "
                         << nod_count + 2 * (nplot - i - j) - 1 +
                              ((nplot - 1 - i) * (nplot - i) / 2)
                         << std::endl;
               }
               if (k > 1)
               {
                 outfile << nod_count + nplot - i - j - 1 << " "
                         << nod_count + nplot - i - j +
                              ((nplot - 1 - i) * (nplot - i) / 2) - 1
                         << " "
                         << nod_count + 2 * (nplot - i - j - 1) +
                              ((nplot - 1 - i) * (nplot - i) / 2) - 1
                         << " "
                         << nod_count + 2 * (nplot - i - j - 1) +
                              ((nplot - 1 - i) * (nplot - i) / 2)
                         << std::endl;
               }
             } // end if(k<nplot-i-j-1)
             ++nod_count;
           }
         }
       }
     } // end of write tecplot...
References i, j, and k.
Member Data Documentation
Default_integration_scheme
template<unsigned NNODE_1D> TGauss< 3, NNODE_1D > oomph::TElement< 3, NNODE_1D >::Default_integration_scheme static private
Default integration rule: Gaussian integration of same 'order' as the element
Node_on_face
template<unsigned NNODE_1D> const unsigned oomph::TElement< 3, NNODE_1D >::Node_on_face[4][(NNODE_1D *(NNODE_1D+1))/2] static private
Nodal translation scheme for use when generating face elements.
The documentation for this class was generated from the following files:
Telements.h
Telements.cc