MercuryDPM: ElasticInclinedPlaneProblem< ELEMENT, TIMESTEPPER > Class Template Reference
ElasticInclinedPlaneProblem< ELEMENT, TIMESTEPPER > Class Template Reference
Public Member Functions
ElasticInclinedPlaneProblem (const unsigned &nx, const unsigned &ny, const double &length)
void actions_after_implicit_timestep ()
Public Member Functions inherited from InclinedPlaneProblem< ELEMENT, ElasticLineFluidInterfaceElement< ELEMENT > >
InclinedPlaneProblem (const unsigned &nx, const unsigned &ny, const double &length)
Generic Constructor (empty)
void solve_steady ()
Solve the steady problem.
void timestep (const double &dt, const unsigned &n_tsteps)
Take n_tsteps timesteps of size dt.
void actions_before_implicit_timestep ()
void make_traction_elements ()
void make_free_surface_elements ()
void complete_build ()
~InclinedPlaneProblem ()
Generic desructor to clean up the memory allocated in the problem.
Additional Inherited Members
Protected Attributes inherited from InclinedPlaneProblem< ELEMENT, ElasticLineFluidInterfaceElement< ELEMENT > >
Mesh * Bulk_mesh_pt
Bulk fluid mesh.
Mesh * Traction_mesh_pt
Mesh for the traction elements that are added at inlet and outlet.
Mesh * Surface_mesh_pt
Mesh for the free surface elements.
Mesh * Point_mesh_pt
Mesh for the point elements at each end of the free surface.
std::string Output_prefix
Prefix for output files.
Constructor & Destructor Documentation
ElasticInclinedPlaneProblem()
template<class ELEMENT , class TIMESTEPPER > ElasticInclinedPlaneProblem< ELEMENT, TIMESTEPPER >::ElasticInclinedPlaneProblem (const unsigned & nx, const unsigned & ny, const double & length) inline
                                             :
   InclinedPlaneProblem<ELEMENT,ElasticLineFluidInterfaceElement<ELEMENT> >
   (nx,ny,length)
   {
    //Set the name
    this->Output_prefix = "elastic";
    //Create our one and only timestepper, with adaptive timestepping
    this->add_time_stepper_pt(new TIMESTEPPER);
    //Create the bulk mesh
    this->Bulk_mesh_pt = new  ElasticInclinedPlaneMesh<ELEMENT>(
     nx,ny,length,1.0,this->time_stepper_pt());
    //Set the consititutive law for the elements
    unsigned n_element = this->Bulk_mesh_pt->nelement();
    //Loop over all the fluid elements
    for(unsigned e=0;e<n_element;e++)
     {
      //Cast to a fluid element
      ELEMENT *temp_pt = dynamic_cast<ELEMENT*>(
       this->Bulk_mesh_pt->element_pt(e));
      //Set the constitutive law
      temp_pt->constitutive_law_pt() =
       Global_Physical_Variables::Constitutive_law_pt;
     }
    //Create the traction elements
    this->make_traction_elements();
    //Create the free surface element
    this->make_free_surface_elements();
    //Add all sub meshes to the problem
    this->add_sub_mesh(this->Bulk_mesh_pt);
    this->add_sub_mesh(this->Traction_mesh_pt);
    this->add_sub_mesh(this->Surface_mesh_pt);
    this->add_sub_mesh(this->Point_mesh_pt);
    //Create the global mesh
    this->build_global_mesh();
    //Complete the rest of the build
    this->complete_build();
   } //end of constructor
References Global_Physical_Variables::Constitutive_law_pt, e(), Mesh_Parameters::nx, and Mesh_Parameters::ny.
Member Function Documentation
actions_after_implicit_timestep()
template<class ELEMENT , class TIMESTEPPER > void ElasticInclinedPlaneProblem< ELEMENT, TIMESTEPPER >::actions_after_implicit_timestep () inline
Update Lagrangian positions after each timestep (updated-lagrangian approach)
   {
    //Now loop over all the nodes and reset their Lagrangian coordinates
    unsigned n_node = this->Bulk_mesh_pt->nnode();
    for(unsigned n=0;n<n_node;n++)
     {
      //Cast node to an elastic node
      SolidNode* temp_pt =
       static_cast<SolidNode*>(this->Bulk_mesh_pt->node_pt(n));
      for(unsigned j=0;j<2;j++) {temp_pt->xi(j) = temp_pt->x(j);}
     }
   } //end of actions_after_implicit_timestep
References j, n, oomph::Node::x(), and oomph::SolidNode::xi().
The documentation for this class was generated from the following file:
inclined_plane.cc