MercuryDPM: Eigen::SolveWithGuess< Decomposition, RhsType, GuessType > Class Template Reference
Eigen::SolveWithGuess< Decomposition, RhsType, GuessType > Class Template Reference
Sparse linear algebra » Reference » IterativeLinearSolvers_Module
Pseudo expression representing a solving operation.
#include <SolveWithGuess.h>
Public Types
typedef internal::traits< SolveWithGuess >::Scalar Scalar
typedef internal::traits< SolveWithGuess >::PlainObject PlainObject
typedef internal::generic_xpr_base< SolveWithGuess< Decomposition, RhsType, GuessType >, MatrixXpr, typename internal::traits< RhsType >::StorageKind >::type Base
typedef internal::ref_selector< SolveWithGuess >::type Nested
Public Member Functions
SolveWithGuess (const Decomposition &dec, const RhsType &rhs, const GuessType &guess)
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC const Decomposition & dec () const
EIGEN_DEVICE_FUNC const RhsType & rhs () const
EIGEN_DEVICE_FUNC const GuessType & guess () const
Protected Attributes
const Decomposition & m_dec
const RhsType & m_rhs
const GuessType & m_guess
Private Member Functions
Scalar coeff (Index row, Index col) const
Scalar coeff (Index i) const
Detailed Description
template<typename Decomposition, typename RhsType, typename GuessType>
class Eigen::SolveWithGuess< Decomposition, RhsType, GuessType >
Pseudo expression representing a solving operation.
Template Parameters
Decomposition the type of the matrix or decomposition object
Rhstype the type of the right-hand side
This class represents an expression of A.solve(B) and most of the time this is the only way it is used.
Member Typedef Documentation
Base
template<typename Decomposition , typename RhsType , typename GuessType > typedef internal::generic_xpr_base<SolveWithGuess<Decomposition, RhsType, GuessType>, MatrixXpr, typename internal::traits<RhsType>::StorageKind>::type Eigen::SolveWithGuess< Decomposition, RhsType, GuessType >::Base
Nested
template<typename Decomposition , typename RhsType , typename GuessType > typedef internal::ref_selector<SolveWithGuess>::type Eigen::SolveWithGuess< Decomposition, RhsType, GuessType >::Nested
PlainObject
template<typename Decomposition , typename RhsType , typename GuessType > typedef internal::traits<SolveWithGuess>::PlainObject Eigen::SolveWithGuess< Decomposition, RhsType, GuessType >::PlainObject
Scalar
template<typename Decomposition , typename RhsType , typename GuessType > typedef internal::traits<SolveWithGuess>::Scalar Eigen::SolveWithGuess< Decomposition, RhsType, GuessType >::Scalar
Constructor & Destructor Documentation
SolveWithGuess()
template<typename Decomposition , typename RhsType , typename GuessType > Eigen::SolveWithGuess< Decomposition, RhsType, GuessType >::SolveWithGuess (const Decomposition & dec, const RhsType & rhs, const GuessType & guess) inline
       : m_dec(dec), m_rhs(rhs), m_guess(guess) {}
Member Function Documentation
coeff() [1/2]
template<typename Decomposition , typename RhsType , typename GuessType > Scalar Eigen::SolveWithGuess< Decomposition, RhsType, GuessType >::coeff (Index i) const private
coeff() [2/2]
template<typename Decomposition , typename RhsType , typename GuessType > Scalar Eigen::SolveWithGuess< Decomposition, RhsType, GuessType >::coeff (Index row, Index col) const private
cols()
template<typename Decomposition , typename RhsType , typename GuessType > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::SolveWithGuess< Decomposition, RhsType, GuessType >::cols () const inline
 { return m_rhs.cols(); }
References Eigen::SolveWithGuess< Decomposition, RhsType, GuessType >::m_rhs.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), Eigen::internal::Assignment< DstXprType, SolveWithGuess< DecType, RhsType, GuessType >, internal::assign_op< Scalar, Scalar >, Dense2Dense >::run(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
dec()
template<typename Decomposition , typename RhsType , typename GuessType > EIGEN_DEVICE_FUNC const Decomposition& Eigen::SolveWithGuess< Decomposition, RhsType, GuessType >::dec () const inline
 { return m_dec; }
References Eigen::SolveWithGuess< Decomposition, RhsType, GuessType >::m_dec.
Referenced by Eigen::internal::Assignment< DstXprType, SolveWithGuess< DecType, RhsType, GuessType >, internal::assign_op< Scalar, Scalar >, Dense2Dense >::run().
guess()
template<typename Decomposition , typename RhsType , typename GuessType > EIGEN_DEVICE_FUNC const GuessType& Eigen::SolveWithGuess< Decomposition, RhsType, GuessType >::guess () const inline
 { return m_guess; }
References Eigen::SolveWithGuess< Decomposition, RhsType, GuessType >::m_guess.
Referenced by Eigen::internal::Assignment< DstXprType, SolveWithGuess< DecType, RhsType, GuessType >, internal::assign_op< Scalar, Scalar >, Dense2Dense >::run().
rhs()
template<typename Decomposition , typename RhsType , typename GuessType > EIGEN_DEVICE_FUNC const RhsType& Eigen::SolveWithGuess< Decomposition, RhsType, GuessType >::rhs () const inline
 { return m_rhs; }
References Eigen::SolveWithGuess< Decomposition, RhsType, GuessType >::m_rhs.
Referenced by Eigen::internal::Assignment< DstXprType, SolveWithGuess< DecType, RhsType, GuessType >, internal::assign_op< Scalar, Scalar >, Dense2Dense >::run().
rows()
template<typename Decomposition , typename RhsType , typename GuessType > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::SolveWithGuess< Decomposition, RhsType, GuessType >::rows () const inline
 { return m_dec.cols(); }
References Eigen::SolveWithGuess< Decomposition, RhsType, GuessType >::m_dec.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), Eigen::internal::Assignment< DstXprType, SolveWithGuess< DecType, RhsType, GuessType >, internal::assign_op< Scalar, Scalar >, Dense2Dense >::run(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
Member Data Documentation
m_dec
template<typename Decomposition , typename RhsType , typename GuessType > const Decomposition& Eigen::SolveWithGuess< Decomposition, RhsType, GuessType >::m_dec protected
Referenced by Eigen::SolveWithGuess< Decomposition, RhsType, GuessType >::dec(), and Eigen::SolveWithGuess< Decomposition, RhsType, GuessType >::rows().
m_guess
template<typename Decomposition , typename RhsType , typename GuessType > const GuessType& Eigen::SolveWithGuess< Decomposition, RhsType, GuessType >::m_guess protected
Referenced by Eigen::SolveWithGuess< Decomposition, RhsType, GuessType >::guess().
m_rhs
template<typename Decomposition , typename RhsType , typename GuessType > const RhsType& Eigen::SolveWithGuess< Decomposition, RhsType, GuessType >::m_rhs protected
Referenced by Eigen::SolveWithGuess< Decomposition, RhsType, GuessType >::cols(), and Eigen::SolveWithGuess< Decomposition, RhsType, GuessType >::rhs().
The documentation for this class was generated from the following file:
SolveWithGuess.h