MercuryDPM: SinusoidalWall Class Reference
SinusoidalWall Class Reference
Public Member Functions
SinusoidalWall (const double &height, const double &amplitude, const double &zeta_min, const double &zeta_max)
SinusoidalWall (const Vector< Data * > &geom_data_pt)
~SinusoidalWall ()
Destructor: Clean up if necessary.
double & height ()
Access function for horizontal half axis.
double & amplitude ()
Access function for vertical half axis.
void position (const Vector< double > &zeta, Vector< double > &r) const
Position vector at Lagrangian coordinate zeta.
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
unsigned ngeom_data () const
How many items of Data does the shape of the object depend on?
Data * geom_data_pt (const unsigned &j)
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition_dt (const Vector< double > &zeta, const unsigned &j, Vector< double > &drdt)
virtual void locate_zeta (const Vector< double > &zeta, GeomObject *&sub_geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
Private Attributes
Vector< Data * > Geom_data_pt
Vector of pointers to Data items that affects the object's shape.
bool Must_clean_up
Do I need to clean up?
Additional Inherited Members
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Detailed Description
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// Geometric object representing a sinusoidal wall, parametrised by
\[ x = \zeta \]
\[ y = H + A \sin\left(\frac{2\pi \left(\zeta-\zeta_{\mbox{min}}\right)} {\zeta_{\mbox{max}}-\zeta_{\mbox{min}}} \right)\]
Constructor & Destructor Documentation
SinusoidalWall() [1/2]
SinusoidalWall::SinusoidalWall (const double & height, const double & amplitude, const double & zeta_min, const double & zeta_max) inline
Constructor: Pass height, amplitude, zeta min and zeta max (all are pinned by default)
   : GeomObject(1,2)
   {
    // Make space for the geometric data
    Geom_data_pt.resize(1);
    // Create data: Four value, no time dependence, free by default
    Geom_data_pt[0] = new Data(4);
    // I've created the data, I have to clean up
    Must_clean_up=true;
    // Pin the data
    for (unsigned i=0;i<4;i++) {Geom_data_pt[0]->pin(i);}
    // Give it a value: Initial height
    Geom_data_pt[0]->set_value(0,height);
    Geom_data_pt[0]->set_value(1,amplitude);
    Geom_data_pt[0]->set_value(2,zeta_min);
    Geom_data_pt[0]->set_value(3,zeta_max);
   }
References Global_Physical_Variables::height(), and i.
SinusoidalWall() [2/2]
SinusoidalWall::SinusoidalWall (const Vector< Data * > & geom_data_pt) inline
Constructor: One item of geometric data, containing four values:
Geom_data_pt[0]->value(0) = height
Geom_data_pt[0]->value(1) = amplitude
Geom_data_pt[0]->value(2) = zeta_min
Geom_data_pt[0]->value(3) = zeta_max
                                                    : GeomObject(1,2)
   {
 #ifdef PARANOID
    if(geom_data_pt.size()!=1)
     {
      std::ostringstream error_stream;
      error_stream
       << "Wrong size for geom_data_pt " << geom_data_pt.size() << std::endl;
      if (geom_data_pt[0]->nvalue()!=1)
       {
        error_stream << "Wrong geom_data_pt[0]->nvalue() "
                     << geom_data_pt[0]->nvalue() << std::endl;
       }
      throw OomphLibError(error_stream.str(),
                          OOMPH_CURRENT_FUNCTION,
                          OOMPH_EXCEPTION_LOCATION);
     }
 #endif
    Geom_data_pt.resize(1);
    Geom_data_pt[0]=geom_data_pt[0];
    // Data has been created externally: Must not clean up
    Must_clean_up=false;
   }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
~SinusoidalWall()
SinusoidalWall::~SinusoidalWall () inline
Destructor: Clean up if necessary.
   {
    // Do I need to clean up?
    if (Must_clean_up)
     {
      delete Geom_data_pt[0];
      Geom_data_pt[0]=0;
     }
   }
Member Function Documentation
amplitude()
double& SinusoidalWall::amplitude () inline
Access function for vertical half axis.
 {return *Geom_data_pt[0]->value_pt(1);}
d2position() [1/2]
virtual void SinusoidalWall::d2position (const Vector< double > & zeta, RankThreeTensor< double > & ddrdzeta) const inline virtual
2nd derivative of position Vector w.r.t. to coordinates: \(\frac{d^2R_i}{d \zeta_\alpha d \zeta_\beta}\) = ddrdzeta(alpha,beta,i). Evaluated at current time.
Reimplemented from oomph::GeomObject.
   {
    // Get parametres
    double A = Geom_data_pt[0]->value(1);
    double zeta_min = Geom_data_pt[0]->value(2);
    double zeta_max = Geom_data_pt[0]->value(3);
    double Lz = zeta_max-zeta_min;
    // Derivative of tangent vector
    ddrdzeta(0,0,0)=0.0;
    ddrdzeta(0,0,1)=-MathematicalConstants::Pi*MathematicalConstants::Pi*
     A*sin(MathematicalConstants::Pi*(zeta[0]-zeta_min)/Lz)/(Lz*Lz);
   }
References Global_Parameters::Lz, BiharmonicTestFunctions2::Pi, sin(), and Eigen::zeta().
d2position() [2/2]
virtual void SinusoidalWall::d2position (const Vector< double > & zeta, Vector< double > & r, DenseMatrix< double > & drdzeta, RankThreeTensor< double > & ddrdzeta) const inline virtual
Posn Vector and its 1st & 2nd derivatives w.r.t. to coordinates: \(\frac{dR_i}{d \zeta_\alpha}\) = drdzeta(alpha,i). \(\frac{d^2R_i}{d \zeta_\alpha d \zeta_\beta}\) = ddrdzeta(alpha,beta,i). Evaluated at current time.
Reimplemented from oomph::GeomObject.
   {
    // Get parametres
    double H = Geom_data_pt[0]->value(0);
    double A = Geom_data_pt[0]->value(1);
    double zeta_min = Geom_data_pt[0]->value(2);
    double zeta_max = Geom_data_pt[0]->value(3);
    double Lz = zeta_max-zeta_min;
    // Position Vector
    r[0] = zeta[0];
    r[1] = H + A*sin(MathematicalConstants::Pi*(zeta[0]-zeta_min)/Lz);
    // Tangent vector
    drdzeta(0,0)=1.0;
    drdzeta(0,1)=MathematicalConstants::Pi*A*
     cos(MathematicalConstants::Pi*(zeta[0]-zeta_min)/Lz)/Lz;
    // Derivative of tangent vector
    ddrdzeta(0,0,0)=0.0;
    ddrdzeta(0,0,1)=-MathematicalConstants::Pi*MathematicalConstants::Pi*
     A*sin(MathematicalConstants::Pi*(zeta[0]-zeta_min)/Lz)/(Lz*Lz);
   }
References cos(), H, Global_Parameters::Lz, BiharmonicTestFunctions2::Pi, UniformPSDSelfTest::r, sin(), and Eigen::zeta().
dposition()
virtual void SinusoidalWall::dposition (const Vector< double > & zeta, DenseMatrix< double > & drdzeta) const inline virtual
Derivative of position Vector w.r.t. to coordinates: \(\frac{dR_i}{d \zeta_\alpha}\) = drdzeta(alpha,i). Evaluated at current time.
Reimplemented from oomph::GeomObject.
   {
    // Get parametres
    double A = Geom_data_pt[0]->value(1);
    double zeta_min = Geom_data_pt[0]->value(2);
    double zeta_max = Geom_data_pt[0]->value(3);
    double Lz = zeta_max-zeta_min;
    // Tangent vector
    drdzeta(0,0)=1.0;
    drdzeta(0,1)=MathematicalConstants::Pi*A*
     cos(MathematicalConstants::Pi*(zeta[0]-zeta_min)/Lz)/Lz;
   }
References cos(), Global_Parameters::Lz, BiharmonicTestFunctions2::Pi, and Eigen::zeta().
geom_data_pt()
Data* SinusoidalWall::geom_data_pt (const unsigned & j) inline virtual
Return pointer to the j-th Data item that the object's shape depends on
Reimplemented from oomph::GeomObject.
 {return Geom_data_pt[j];}
References j.
height()
double& SinusoidalWall::height () inline
Access function for horizontal half axis.
 {return *Geom_data_pt[0]->value_pt(0);}
ngeom_data()
unsigned SinusoidalWall::ngeom_data () const inline virtual
How many items of Data does the shape of the object depend on?
Reimplemented from oomph::GeomObject.
 {return Geom_data_pt.size();}
position() [1/2]
void SinusoidalWall::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const inline virtual
Parametrised position on object: r(zeta). Evaluated at previous timestep. t=0: current time; t>0: previous timestep.
Reimplemented from oomph::GeomObject.
   {
 #ifdef PARANOID
    if (t>Geom_data_pt[0]->time_stepper_pt()->nprev_values())
     {
      std::ostringstream error_stream;
      error_stream
       << "t > nprev_values() in SpikedLine:  " << t << " "
       << Geom_data_pt[0]->time_stepper_pt()->nprev_values() << std::endl;
      throw OomphLibError(error_stream.str(),
                          OOMPH_CURRENT_FUNCTION,
                          OOMPH_EXCEPTION_LOCATION);
     }
 #endif
    // Get parameters
    double H = Geom_data_pt[0]->value(t,0);
    double A = Geom_data_pt[0]->value(t,1);
    double zeta_min = Geom_data_pt[0]->value(t,2);
    double zeta_max = Geom_data_pt[0]->value(t,3);
    double Lz = zeta_max-zeta_min;
    // Position Vector at time level t
    r[0] = zeta[0];
    r[1] = H + A*sin(MathematicalConstants::Pi*(zeta[0]-zeta_min)/Lz);
   }
References H, Global_Parameters::Lz, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, BiharmonicTestFunctions2::Pi, UniformPSDSelfTest::r, sin(), plotPSD::t, and Eigen::zeta().
position() [2/2]
void SinusoidalWall::position (const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position vector at Lagrangian coordinate zeta.
Implements oomph::GeomObject.
   {
 #ifdef PARANOID
    if (r.size()!=Ndim)
     {
      throw OomphLibError("The vector r has the wrong dimension\n",
                          OOMPH_CURRENT_FUNCTION,
                          OOMPH_EXCEPTION_LOCATION);
     }
 #endif
    // Get parameters
    double H = Geom_data_pt[0]->value(0);
    double A = Geom_data_pt[0]->value(1);
    double zeta_min = Geom_data_pt[0]->value(2);
    double zeta_max = Geom_data_pt[0]->value(3);
    double Lz = zeta_max-zeta_min;
    // Position Vector
    r[0] = zeta[0];
    r[1] = H + A*sin(MathematicalConstants::Pi*(zeta[0]-zeta_min)/Lz);
   }
References H, Global_Parameters::Lz, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, BiharmonicTestFunctions2::Pi, UniformPSDSelfTest::r, sin(), and Eigen::zeta().
Member Data Documentation
Geom_data_pt
Vector<Data*> SinusoidalWall::Geom_data_pt private
Vector of pointers to Data items that affects the object's shape.
Must_clean_up
bool SinusoidalWall::Must_clean_up private
Do I need to clean up?
The documentation for this class was generated from the following file:
spine_channel.cc