MercuryDPM: Eigen::DenseBase< Derived > Class Template Reference
Eigen::DenseBase< Derived > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
Base class for all dense matrices, vectors, and arrays.
#include <DenseBase.h>
Public Types
enum {
RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime , ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime , SizeAtCompileTime = (internal::size_of_xpr_at_compile_time<Derived>::ret) , MaxRowsAtCompileTime = internal::traits<Derived>::MaxRowsAtCompileTime ,
MaxColsAtCompileTime = internal::traits<Derived>::MaxColsAtCompileTime , MaxSizeAtCompileTime , IsVectorAtCompileTime , NumDimensions ,
Flags = internal::traits<Derived>::Flags , IsRowMajor = int(Flags) & RowMajorBit , InnerSizeAtCompileTime , InnerStrideAtCompileTime = internal::inner_stride_at_compile_time<Derived>::ret ,
OuterStrideAtCompileTime = internal::outer_stride_at_compile_time<Derived>::ret
}
enum { IsPlainObjectBase = 0 }
typedef Eigen::InnerIterator< Derived > InnerIterator
typedef internal::traits< Derived >::StorageKind StorageKind
typedef internal::traits< Derived >::StorageIndex StorageIndex
The type used to store indices.
typedef internal::traits< Derived >::Scalar Scalar
typedef Scalar value_type
typedef NumTraits< Scalar >::Real RealScalar
typedef DenseCoeffsBase< Derived, internal::accessors_level< Derived >::value > Base
typedef Base::CoeffReturnType CoeffReturnType
typedef internal::find_best_packet< Scalar, SizeAtCompileTime >::type PacketScalar
typedef Matrix< typename internal::traits< Derived >::Scalar, internal::traits< Derived >::RowsAtCompileTime, internal::traits< Derived >::ColsAtCompileTime, AutoAlign|(internal::traits< Derived >::Flags &RowMajorBit ? RowMajor :ColMajor), internal::traits< Derived >::MaxRowsAtCompileTime, internal::traits< Derived >::MaxColsAtCompileTime > PlainMatrix
typedef Array< typename internal::traits< Derived >::Scalar, internal::traits< Derived >::RowsAtCompileTime, internal::traits< Derived >::ColsAtCompileTime, AutoAlign|(internal::traits< Derived >::Flags &RowMajorBit ? RowMajor :ColMajor), internal::traits< Derived >::MaxRowsAtCompileTime, internal::traits< Derived >::MaxColsAtCompileTime > PlainArray
typedef std::conditional_t< internal::is_same< typename internal::traits< Derived >::XprKind, MatrixXpr >::value, PlainMatrix, PlainArray > PlainObject
The plain matrix or array type corresponding to this expression.
typedef CwiseNullaryOp< internal::scalar_constant_op< Scalar >, PlainObject > ConstantReturnType
typedef CwiseNullaryOp< internal::scalar_zero_op< Scalar >, PlainObject > ZeroReturnType
typedef CwiseNullaryOp< internal::linspaced_op< Scalar >, PlainObject > RandomAccessLinSpacedReturnType
typedef CwiseNullaryOp< internal::equalspaced_op< Scalar >, PlainObject > RandomAccessEqualSpacedReturnType
typedef Matrix< typename NumTraits< typename internal::traits< Derived >::Scalar >::Real, internal::traits< Derived >::ColsAtCompileTime, 1 > EigenvaluesReturnType
typedef Transpose< Derived > TransposeReturnType
typedef Transpose< const Derived > ConstTransposeReturnType
typedef internal::add_const_on_value_type_t< typename internal::eval< Derived >::type > EvalReturnType
typedef VectorwiseOp< Derived, Horizontal > RowwiseReturnType
typedef const VectorwiseOp< const Derived, Horizontal > ConstRowwiseReturnType
typedef VectorwiseOp< Derived, Vertical > ColwiseReturnType
typedef const VectorwiseOp< const Derived, Vertical > ConstColwiseReturnType
typedef CwiseNullaryOp< internal::scalar_random_op< Scalar >, PlainObject > RandomReturnType
typedef Reverse< Derived, BothDirections > ReverseReturnType
typedef const Reverse< const Derived, BothDirections > ConstReverseReturnType
typedef std::conditional_t<(Flags &DirectAccessBit)==DirectAccessBit, internal::pointer_based_stl_iterator< Derived >, internal::generic_randaccess_stl_iterator< Derived > > iterator_type
typedef std::conditional_t<(Flags &DirectAccessBit)==DirectAccessBit, internal::pointer_based_stl_iterator< const Derived >, internal::generic_randaccess_stl_iterator< const Derived > > const_iterator_type
typedef std::conditional_t< IsVectorAtCompileTime, iterator_type, void > iterator
typedef std::conditional_t< IsVectorAtCompileTime, const_iterator_type, void > const_iterator
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index outerSize () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index innerSize () const
EIGEN_DEVICE_FUNC void resize (Index newSize)
EIGEN_DEVICE_FUNC void resize (Index rows, Index cols)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator= (const DenseBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator= (const DenseBase &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator= (const EigenBase< OtherDerived > &other)
Copies the generic expression other into *this.
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator+= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator-= (const EigenBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC Derived & operator= (const ReturnByValue< OtherDerived > &func)
template<typename OtherDerived >
EIGEN_DEPRECATED EIGEN_DEVICE_FUNC Derived & lazyAssign (const DenseBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC CommaInitializer< Derived > operator<< (const Scalar &s)
template<unsigned int Added, unsigned int Removed>
EIGEN_DEPRECATED const Derived & flagged () const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC CommaInitializer< Derived > operator<< (const DenseBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC TransposeReturnType transpose ()
EIGEN_DEVICE_FUNC const ConstTransposeReturnType transpose () const
EIGEN_DEVICE_FUNC void transposeInPlace ()
EIGEN_DEVICE_FUNC void fill (const Scalar &value)
EIGEN_DEVICE_FUNC Derived & setConstant (const Scalar &value)
EIGEN_DEVICE_FUNC Derived & setLinSpaced (Index size, const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
EIGEN_DEVICE_FUNC Derived & setLinSpaced (const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
EIGEN_DEVICE_FUNC Derived & setEqualSpaced (Index size, const Scalar &low, const Scalar &step)
EIGEN_DEVICE_FUNC Derived & setEqualSpaced (const Scalar &low, const Scalar &step)
EIGEN_DEVICE_FUNC Derived & setZero ()
EIGEN_DEVICE_FUNC Derived & setOnes ()
EIGEN_DEVICE_FUNC Derived & setRandom ()
template<typename OtherDerived >
EIGEN_DEVICE_FUNC bool isApprox (const DenseBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isMuchSmallerThan (const RealScalar &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC bool isMuchSmallerThan (const DenseBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isApproxToConstant (const Scalar &value, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isConstant (const Scalar &value, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isZero (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool isOnes (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
EIGEN_DEVICE_FUNC bool hasNaN () const
EIGEN_DEVICE_FUNC bool allFinite () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator*= (const Scalar &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & operator/= (const Scalar &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EvalReturnType eval () const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void swap (const DenseBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void swap (PlainObjectBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC const NestByValue< Derived > nestByValue () const
EIGEN_DEVICE_FUNC const ForceAlignedAccess< Derived > forceAlignedAccess () const
EIGEN_DEVICE_FUNC ForceAlignedAccess< Derived > forceAlignedAccess ()
template<bool Enable>
EIGEN_DEVICE_FUNC const std::conditional_t< Enable, ForceAlignedAccess< Derived >, Derived & > forceAlignedAccessIf () const
template<bool Enable>
EIGEN_DEVICE_FUNC std::conditional_t< Enable, ForceAlignedAccess< Derived >, Derived & > forceAlignedAccessIf ()
EIGEN_DEVICE_FUNC Scalar sum () const
EIGEN_DEVICE_FUNC Scalar mean () const
EIGEN_DEVICE_FUNC Scalar trace () const
EIGEN_DEVICE_FUNC Scalar prod () const
template<int NaNPropagation>
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff () const
template<int NaNPropagation>
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff () const
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff () const
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff () const
template<int NaNPropagation, typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff (IndexType *row, IndexType *col) const
template<int NaNPropagation, typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff (IndexType *row, IndexType *col) const
template<int NaNPropagation, typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff (IndexType *index) const
template<int NaNPropagation, typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff (IndexType *index) const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff (IndexType *row, IndexType *col) const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff (IndexType *row, IndexType *col) const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar minCoeff (IndexType *index) const
template<typename IndexType >
EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar maxCoeff (IndexType *index) const
template<typename BinaryOp >
EIGEN_DEVICE_FUNC Scalar redux (const BinaryOp &func) const
template<typename Visitor >
EIGEN_DEVICE_FUNC void visit (Visitor &func) const
const WithFormat< Derived > format (const IOFormat &fmt) const
EIGEN_DEVICE_FUNC CoeffReturnType value () const
EIGEN_DEVICE_FUNC bool all () const
EIGEN_DEVICE_FUNC bool any () const
EIGEN_DEVICE_FUNC Index count () const
EIGEN_DEVICE_FUNC ConstRowwiseReturnType rowwise () const
EIGEN_DEVICE_FUNC RowwiseReturnType rowwise ()
EIGEN_DEVICE_FUNC ConstColwiseReturnType colwise () const
EIGEN_DEVICE_FUNC ColwiseReturnType colwise ()
template<typename ThenDerived , typename ElseDerived >
EIGEN_DEVICE_FUNC CwiseTernaryOp< internal::scalar_boolean_select_op< typename DenseBase< ThenDerived >::Scalar, typename DenseBase< ElseDerived >::Scalar, Scalar >, ThenDerived, ElseDerived, Derived > select (const DenseBase< ThenDerived > &thenMatrix, const DenseBase< ElseDerived > &elseMatrix) const
template<typename ThenDerived >
EIGEN_DEVICE_FUNC CwiseTernaryOp< internal::scalar_boolean_select_op< typename DenseBase< ThenDerived >::Scalar, typename DenseBase< ThenDerived >::Scalar, Scalar >, ThenDerived, typename DenseBase< ThenDerived >::ConstantReturnType, Derived > select (const DenseBase< ThenDerived > &thenMatrix, const typename DenseBase< ThenDerived >::Scalar &elseScalar) const
template<typename ElseDerived >
EIGEN_DEVICE_FUNC CwiseTernaryOp< internal::scalar_boolean_select_op< typename DenseBase< ElseDerived >::Scalar, typename DenseBase< ElseDerived >::Scalar, Scalar >, typename DenseBase< ElseDerived >::ConstantReturnType, ElseDerived, Derived > select (const typename DenseBase< ElseDerived >::Scalar &thenScalar, const DenseBase< ElseDerived > &elseMatrix) const
template<int p>
RealScalar lpNorm () const
template<int RowFactor, int ColFactor>
EIGEN_DEVICE_FUNC const Replicate< Derived, RowFactor, ColFactor > replicate () const
EIGEN_DEVICE_FUNC const Replicate< Derived, Dynamic, Dynamic > replicate (Index rowFactor, Index colFactor) const
EIGEN_DEVICE_FUNC ReverseReturnType reverse ()
EIGEN_DEVICE_FUNC ConstReverseReturnType reverse () const
EIGEN_DEVICE_FUNC void reverseInPlace ()
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
iterator end ()
const_iterator end () const
const_iterator cend () const
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & lazyAssign (const DenseBase< OtherDerived > &other)
template<typename CustomNullaryOp >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseNullaryOp< CustomNullaryOp, typename DenseBase< Derived >::PlainObject > NullaryExpr (Index rows, Index cols, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseNullaryOp< CustomNullaryOp, typename DenseBase< Derived >::PlainObject > NullaryExpr (Index size, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseNullaryOp< CustomNullaryOp, typename DenseBase< Derived >::PlainObject > NullaryExpr (const CustomNullaryOp &func)
template<typename Derived >
EIGEN_DEVICE_FUNC bool isMuchSmallerThan (const typename NumTraits< Scalar >::Real &other, const RealScalar &prec) const
template<typename Func >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar redux (const Func &func) const
template<typename ThenDerived , typename ElseDerived >
EIGEN_DEVICE_FUNC CwiseTernaryOp< internal::scalar_boolean_select_op< typename DenseBase< ThenDerived >::Scalar, typename DenseBase< ElseDerived >::Scalar, typename DenseBase< Derived >::Scalar >, ThenDerived, ElseDerived, Derived > select (const DenseBase< ThenDerived > &thenMatrix, const DenseBase< ElseDerived > &elseMatrix) const
template<typename ThenDerived >
EIGEN_DEVICE_FUNC CwiseTernaryOp< internal::scalar_boolean_select_op< typename DenseBase< ThenDerived >::Scalar, typename DenseBase< ThenDerived >::Scalar, typename DenseBase< Derived >::Scalar >, ThenDerived, typename DenseBase< ThenDerived >::ConstantReturnType, Derived > select (const DenseBase< ThenDerived > &thenMatrix, const typename DenseBase< ThenDerived >::Scalar &elseScalar) const
template<typename ElseDerived >
EIGEN_DEVICE_FUNC CwiseTernaryOp< internal::scalar_boolean_select_op< typename DenseBase< ElseDerived >::Scalar, typename DenseBase< ElseDerived >::Scalar, typename DenseBase< Derived >::Scalar >, typename DenseBase< ElseDerived >::ConstantReturnType, ElseDerived, Derived > select (const typename DenseBase< ElseDerived >::Scalar &thenScalar, const DenseBase< ElseDerived > &elseMatrix) const
Static Public Member Functions
static EIGEN_DEVICE_FUNC const ConstantReturnType Constant (Index rows, Index cols, const Scalar &value)
static EIGEN_DEVICE_FUNC const ConstantReturnType Constant (Index size, const Scalar &value)
static EIGEN_DEVICE_FUNC const ConstantReturnType Constant (const Scalar &value)
EIGEN_DEPRECATED static EIGEN_DEVICE_FUNC const RandomAccessLinSpacedReturnType LinSpaced (Sequential_t, Index size, const Scalar &low, const Scalar &high)
EIGEN_DEPRECATED static EIGEN_DEVICE_FUNC const RandomAccessLinSpacedReturnType LinSpaced (Sequential_t, const Scalar &low, const Scalar &high)
static EIGEN_DEVICE_FUNC const RandomAccessLinSpacedReturnType LinSpaced (Index size, const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
static EIGEN_DEVICE_FUNC const RandomAccessLinSpacedReturnType LinSpaced (const Scalar &low, const Scalar &high)
Sets a linearly spaced vector.
static EIGEN_DEVICE_FUNC const RandomAccessEqualSpacedReturnType EqualSpaced (Index size, const Scalar &low, const Scalar &step)
static EIGEN_DEVICE_FUNC const RandomAccessEqualSpacedReturnType EqualSpaced (const Scalar &low, const Scalar &step)
template<typename CustomNullaryOp >
static EIGEN_DEVICE_FUNC const CwiseNullaryOp< CustomNullaryOp, PlainObject > NullaryExpr (Index rows, Index cols, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
static EIGEN_DEVICE_FUNC const CwiseNullaryOp< CustomNullaryOp, PlainObject > NullaryExpr (Index size, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
static EIGEN_DEVICE_FUNC const CwiseNullaryOp< CustomNullaryOp, PlainObject > NullaryExpr (const CustomNullaryOp &func)
static EIGEN_DEVICE_FUNC const ZeroReturnType Zero (Index rows, Index cols)
static EIGEN_DEVICE_FUNC const ZeroReturnType Zero (Index size)
static EIGEN_DEVICE_FUNC const ZeroReturnType Zero ()
static EIGEN_DEVICE_FUNC const ConstantReturnType Ones (Index rows, Index cols)
static EIGEN_DEVICE_FUNC const ConstantReturnType Ones (Index size)
static EIGEN_DEVICE_FUNC const ConstantReturnType Ones ()
static const RandomReturnType Random (Index rows, Index cols)
static const RandomReturnType Random (Index size)
static const RandomReturnType Random ()
Public Attributes
EIGEN_DEPRECATED typedef CwiseNullaryOp< internal::linspaced_op< Scalar >, PlainObject > SequentialLinSpacedReturnType
Protected Member Functions
constexpr EIGEN_DEVICE_FUNC DenseBase ()=default
Private Member Functions
EIGEN_DEVICE_FUNC DenseBase (int)
EIGEN_DEVICE_FUNC DenseBase (int, int)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC DenseBase (const DenseBase< OtherDerived > &)
Related Functions
(Note that these are not member functions.)
template<typename Derived >
std::ostream & operator<< (std::ostream &s, const DenseBase< Derived > &m)
Detailed Description
template<typename Derived>
class Eigen::DenseBase< Derived >
Base class for all dense matrices, vectors, and arrays.
This class is the base that is inherited by all dense objects (matrix, vector, arrays, and related expression types). The common Eigen API for dense objects is contained in this class.
Template Parameters
Derived is the derived type, e.g., a matrix type or an expression.
This class can be extended with the help of the plugin mechanism described on the page Extending MatrixBase (and other classes) by defining the preprocessor symbol EIGEN_DENSEBASE_PLUGIN.
See also
\blank The class hierarchy
Member Typedef Documentation
Base
template<typename Derived > typedef DenseCoeffsBase<Derived, internal::accessors_level<Derived>::value> Eigen::DenseBase< Derived >::Base
CoeffReturnType
template<typename Derived > typedef Base::CoeffReturnType Eigen::DenseBase< Derived >::CoeffReturnType
ColwiseReturnType
template<typename Derived > typedef VectorwiseOp<Derived, Vertical> Eigen::DenseBase< Derived >::ColwiseReturnType
const_iterator
template<typename Derived > typedef std::conditional_t<IsVectorAtCompileTime, const_iterator_type, void> Eigen::DenseBase< Derived >::const_iterator
const_iterator_type
template<typename Derived > typedef std::conditional_t<(Flags & DirectAccessBit) == DirectAccessBit, internal::pointer_based_stl_iterator<const Derived>, internal::generic_randaccess_stl_iterator<const Derived> > Eigen::DenseBase< Derived >::const_iterator_type
ConstantReturnType
template<typename Derived > typedef CwiseNullaryOp<internal::scalar_constant_op<Scalar>, PlainObject> Eigen::DenseBase< Derived >::ConstantReturnType
Represents a matrix with all coefficients equal to one another
ConstColwiseReturnType
template<typename Derived > typedef const VectorwiseOp<const Derived, Vertical> Eigen::DenseBase< Derived >::ConstColwiseReturnType
ConstReverseReturnType
template<typename Derived > typedef const Reverse<const Derived, BothDirections> Eigen::DenseBase< Derived >::ConstReverseReturnType
ConstRowwiseReturnType
template<typename Derived > typedef const VectorwiseOp<const Derived, Horizontal> Eigen::DenseBase< Derived >::ConstRowwiseReturnType
ConstTransposeReturnType
template<typename Derived > typedef Transpose<const Derived> Eigen::DenseBase< Derived >::ConstTransposeReturnType
EigenvaluesReturnType
template<typename Derived > typedef Matrix<typename NumTraits<typename internal::traits<Derived>::Scalar>::Real, internal::traits<Derived>::ColsAtCompileTime, 1> Eigen::DenseBase< Derived >::EigenvaluesReturnType
the return type of MatrixBase::eigenvalues()
EvalReturnType
template<typename Derived > typedef internal::add_const_on_value_type_t<typename internal::eval<Derived>::type> Eigen::DenseBase< Derived >::EvalReturnType
InnerIterator
template<typename Derived > typedef Eigen::InnerIterator<Derived> Eigen::DenseBase< Derived >::InnerIterator
Inner iterator type to iterate over the coefficients of a row or column.
See also
class InnerIterator
iterator
template<typename Derived > typedef std::conditional_t<IsVectorAtCompileTime, iterator_type, void> Eigen::DenseBase< Derived >::iterator
iterator_type
template<typename Derived > typedef std::conditional_t<(Flags & DirectAccessBit) == DirectAccessBit, internal::pointer_based_stl_iterator<Derived>, internal::generic_randaccess_stl_iterator<Derived> > Eigen::DenseBase< Derived >::iterator_type
PacketScalar
template<typename Derived > typedef internal::find_best_packet<Scalar, SizeAtCompileTime>::type Eigen::DenseBase< Derived >::PacketScalar
PlainArray
template<typename Derived > typedef Array<typename internal::traits<Derived>::Scalar, internal::traits<Derived>::RowsAtCompileTime, internal::traits<Derived>::ColsAtCompileTime, AutoAlign | (internal::traits<Derived>::Flags & RowMajorBit ? RowMajor : ColMajor), internal::traits<Derived>::MaxRowsAtCompileTime, internal::traits<Derived>::MaxColsAtCompileTime> Eigen::DenseBase< Derived >::PlainArray
The plain array type corresponding to this expression.
See also
PlainObject
PlainMatrix
template<typename Derived > typedef Matrix<typename internal::traits<Derived>::Scalar, internal::traits<Derived>::RowsAtCompileTime, internal::traits<Derived>::ColsAtCompileTime, AutoAlign | (internal::traits<Derived>::Flags & RowMajorBit ? RowMajor : ColMajor), internal::traits<Derived>::MaxRowsAtCompileTime, internal::traits<Derived>::MaxColsAtCompileTime> Eigen::DenseBase< Derived >::PlainMatrix
The plain matrix type corresponding to this expression.
See also
PlainObject
PlainObject
template<typename Derived > typedef std::conditional_t<internal::is_same<typename internal::traits<Derived>::XprKind, MatrixXpr>::value, PlainMatrix, PlainArray> Eigen::DenseBase< Derived >::PlainObject
The plain matrix or array type corresponding to this expression.
This is not necessarily exactly the return type of eval(). In the case of plain matrices, the return type of eval() is a const reference to a matrix, not a matrix! It is however guaranteed that the return type of eval() is either PlainObject or const PlainObject&.
RandomAccessEqualSpacedReturnType
template<typename Derived > typedef CwiseNullaryOp<internal::equalspaced_op<Scalar>, PlainObject> Eigen::DenseBase< Derived >::RandomAccessEqualSpacedReturnType
Represents a vector with equally spaced coefficients that allows random access.
RandomAccessLinSpacedReturnType
template<typename Derived > typedef CwiseNullaryOp<internal::linspaced_op<Scalar>, PlainObject> Eigen::DenseBase< Derived >::RandomAccessLinSpacedReturnType
Represents a vector with linearly spaced coefficients that allows random access.
RandomReturnType
template<typename Derived > typedef CwiseNullaryOp<internal::scalar_random_op<Scalar>, PlainObject> Eigen::DenseBase< Derived >::RandomReturnType
RealScalar
template<typename Derived > typedef NumTraits<Scalar>::Real Eigen::DenseBase< Derived >::RealScalar
ReverseReturnType
template<typename Derived > typedef Reverse<Derived, BothDirections> Eigen::DenseBase< Derived >::ReverseReturnType
RowwiseReturnType
template<typename Derived > typedef VectorwiseOp<Derived, Horizontal> Eigen::DenseBase< Derived >::RowwiseReturnType
Scalar
template<typename Derived > typedef internal::traits<Derived>::Scalar Eigen::DenseBase< Derived >::Scalar
The numeric type of the expression' coefficients, e.g. float, double, int or std::complex<float>, etc.
StorageIndex
template<typename Derived > typedef internal::traits<Derived>::StorageIndex Eigen::DenseBase< Derived >::StorageIndex
The type used to store indices.
This typedef is relevant for types that store multiple indices such as PermutationMatrix or Transpositions, otherwise it defaults to Eigen::Index
See also
\blank Preprocessor directives, Eigen::Index, SparseMatrixBase.
StorageKind
template<typename Derived > typedef internal::traits<Derived>::StorageKind Eigen::DenseBase< Derived >::StorageKind
TransposeReturnType
template<typename Derived > typedef Transpose<Derived> Eigen::DenseBase< Derived >::TransposeReturnType
value_type
template<typename Derived > typedef Scalar Eigen::DenseBase< Derived >::value_type
The numeric type of the expression' coefficients, e.g. float, double, int or std::complex<float>, etc.
It is an alias for the Scalar type
ZeroReturnType
template<typename Derived > typedef CwiseNullaryOp<internal::scalar_zero_op<Scalar>, PlainObject> Eigen::DenseBase< Derived >::ZeroReturnType
Represents a matrix with all coefficients equal to zero
Member Enumeration Documentation
anonymous enum
template<typename Derived > anonymous enum
Enumerator
RowsAtCompileTime
The number of rows at compile-time. This is just a copy of the value provided by the Derived type. If a value is not known at compile-time, it is set to the Dynamic constant.
See also
MatrixBase::rows(), MatrixBase::cols(), ColsAtCompileTime, SizeAtCompileTime
ColsAtCompileTime
The number of columns at compile-time. This is just a copy of the value provided by the Derived type. If a value is not known at compile-time, it is set to the Dynamic constant.
See also
MatrixBase::rows(), MatrixBase::cols(), RowsAtCompileTime, SizeAtCompileTime
SizeAtCompileTime
This is equal to the number of coefficients, i.e. the number of rows times the number of columns, or to Dynamic if this is not known at compile-time.
See also
RowsAtCompileTime, ColsAtCompileTime
MaxRowsAtCompileTime
This value is equal to the maximum possible number of rows that this expression might have. If this expression might have an arbitrarily high number of rows, this value is set to Dynamic.
This value is useful to know when evaluating an expression, in order to determine whether it is possible to avoid doing a dynamic memory allocation.
See also
RowsAtCompileTime, MaxColsAtCompileTime, MaxSizeAtCompileTime
MaxColsAtCompileTime
This value is equal to the maximum possible number of columns that this expression might have. If this expression might have an arbitrarily high number of columns, this value is set to Dynamic.
This value is useful to know when evaluating an expression, in order to determine whether it is possible to avoid doing a dynamic memory allocation.
See also
ColsAtCompileTime, MaxRowsAtCompileTime, MaxSizeAtCompileTime
MaxSizeAtCompileTime
This value is equal to the maximum possible number of coefficients that this expression might have. If this expression might have an arbitrarily high number of coefficients, this value is set to Dynamic.
This value is useful to know when evaluating an expression, in order to determine whether it is possible to avoid doing a dynamic memory allocation.
See also
SizeAtCompileTime, MaxRowsAtCompileTime, MaxColsAtCompileTime
IsVectorAtCompileTime
This is set to true if either the number of rows or the number of columns is known at compile-time to be equal to 1. Indeed, in that case, we are dealing with a column-vector (if there is only one column) or with a row-vector (if there is only one row).
NumDimensions
This value is equal to Tensor::NumDimensions, i.e. 0 for scalars, 1 for vectors, and 2 for matrices.
Flags
This stores expression Flags flags which may or may not be inherited by new expressions constructed from this one. See the list of flags.
IsRowMajor
True if this expression has row-major storage order.
InnerSizeAtCompileTime
InnerStrideAtCompileTime
OuterStrideAtCompileTime
        {
     RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime,
     ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime,
     SizeAtCompileTime = (internal::size_of_xpr_at_compile_time<Derived>::ret),
     MaxRowsAtCompileTime = internal::traits<Derived>::MaxRowsAtCompileTime,
     MaxColsAtCompileTime = internal::traits<Derived>::MaxColsAtCompileTime,
     MaxSizeAtCompileTime = internal::size_at_compile_time(internal::traits<Derived>::MaxRowsAtCompileTime,
                                                           internal::traits<Derived>::MaxColsAtCompileTime),
     IsVectorAtCompileTime =
         internal::traits<Derived>::RowsAtCompileTime == 1 || internal::traits<Derived>::ColsAtCompileTime == 1,
     NumDimensions = int(MaxSizeAtCompileTime) == 1 ? 0
                     : bool(IsVectorAtCompileTime)  ? 1
                                                    : 2,
     Flags = internal::traits<Derived>::Flags,
     IsRowMajor = int(Flags) & RowMajorBit,
     InnerSizeAtCompileTime = int(IsVectorAtCompileTime) ? int(SizeAtCompileTime)
                              : int(IsRowMajor)          ? int(ColsAtCompileTime)
                                                         : int(RowsAtCompileTime),
     InnerStrideAtCompileTime = internal::inner_stride_at_compile_time<Derived>::ret,
     OuterStrideAtCompileTime = internal::outer_stride_at_compile_time<Derived>::ret
   };
anonymous enum
template<typename Derived > anonymous enum
Enumerator
IsPlainObjectBase
 { IsPlainObjectBase = 0 };
Constructor & Destructor Documentation
DenseBase() [1/4]
template<typename Derived > constexpr EIGEN_DEVICE_FUNC Eigen::DenseBase< Derived >::DenseBase () constexpr protected default
Default constructor. Do nothing.
DenseBase() [2/4]
template<typename Derived > EIGEN_DEVICE_FUNC Eigen::DenseBase< Derived >::DenseBase (int) explicit private
DenseBase() [3/4]
template<typename Derived > EIGEN_DEVICE_FUNC Eigen::DenseBase< Derived >::DenseBase (int , int) private
DenseBase() [4/4]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC Eigen::DenseBase< Derived >::DenseBase (const DenseBase< OtherDerived > &) explicit private
Member Function Documentation
all()
template<typename Derived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::all inline
Returns
true if all coefficients are true
Example:
Vector3f boxMin(Vector3f::Zero()), boxMax(Vector3f::Ones());
Vector3f p0 = Vector3f::Random(), p1 = Vector3f::Random().cwiseAbs();
// let's check if p0 and p1 are inside the axis aligned box defined by the corners boxMin,boxMax:
cout << "Is (" << p0.transpose()
     << ") inside the box: " << ((boxMin.array() < p0.array()).all() && (boxMax.array() > p0.array()).all()) << endl;
cout << "Is (" << p1.transpose()
     << ") inside the box: " << ((boxMin.array() < p1.array()).all() && (boxMax.array() > p1.array()).all()) << endl;
Output:
See also
any(), Cwise::operator<()
{
   using Visitor = internal::all_visitor<Scalar>;
   using impl = internal::visit_impl<Derived, Visitor, /*ShortCircuitEvaulation*/ true>;
   Visitor visitor;
   impl::run(derived(), visitor);
   return visitor.res;
 }
References run().
allFinite()
template<typename Derived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::allFinite inline
Returns
true if *this contains only finite numbers, i.e., no NaN and no +/-INF values.
See also
hasNaN()
{
   return derived().array().isFiniteTyped().all();
 }
any()
template<typename Derived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::any inline
Returns
true if at least one coefficient is true
See also
all()
{
   using Visitor = internal::any_visitor<Scalar>;
   using impl = internal::visit_impl<Derived, Visitor, /*ShortCircuitEvaulation*/ true>;
   Visitor visitor;
   impl::run(derived(), visitor);
   return visitor.res;
 }
References run().
begin() [1/2]
template<typename Derived > DenseBase< Derived >::iterator Eigen::DenseBase< Derived >::begin inline
returns an iterator to the first element of the 1D vector or array \only_for_vectors
See also
end(), cbegin()
{
   EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived);
   return iterator(derived(), 0);
 }
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
begin() [2/2]
template<typename Derived > DenseBase< Derived >::const_iterator Eigen::DenseBase< Derived >::begin inline
const version of begin()
{
   return cbegin();
 }
cbegin()
template<typename Derived > DenseBase< Derived >::const_iterator Eigen::DenseBase< Derived >::cbegin inline
returns a read-only const_iterator to the first element of the 1D vector or array \only_for_vectors
See also
cend(), begin()
{
   EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived);
   return const_iterator(derived(), 0);
 }
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
cend()
template<typename Derived > DenseBase< Derived >::const_iterator Eigen::DenseBase< Derived >::cend inline
returns a read-only const_iterator to the element following the last element of the 1D vector or array \only_for_vectors
See also
begin(), cend()
{
   EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived);
   return const_iterator(derived(), size());
 }
References EIGEN_STATIC_ASSERT_VECTOR_ONLY, and size.
colwise() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC DenseBase< Derived >::ColwiseReturnType Eigen::DenseBase< Derived >::colwise inline
Returns
a writable VectorwiseOp wrapper of *this providing additional partial reduction operations
See also
rowwise(), class VectorwiseOp, TutorialReductionsVisitorsBroadcasting
{
   return ColwiseReturnType(derived());
 }
colwise() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC ConstColwiseReturnType Eigen::DenseBase< Derived >::colwise () const inline
Returns
a VectorwiseOp wrapper of *this broadcasting and partial reductions
Example:
Matrix3d m = Matrix3d::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is the sum of each column:" << endl << m.colwise().sum() << endl;
cout << "Here is the maximum absolute value of each column:" << endl << m.cwiseAbs().colwise().maxCoeff() << endl;
Output:
See also
rowwise(), class VectorwiseOp, TutorialReductionsVisitorsBroadcasting
 { return ConstColwiseReturnType(derived()); }
Referenced by Eigen::umeyama().
Constant() [1/3]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Constant (const Scalar & value) static
Returns
an expression of a constant matrix of value value
This variant is only for fixed-size DenseBase types. For dynamic-size types, you need to use the variants taking size arguments.
The template parameter CustomNullaryOp is the type of the functor.
See also
class CwiseNullaryOp
{
   EIGEN_STATIC_ASSERT_FIXED_SIZE(Derived)
   return DenseBase<Derived>::NullaryExpr(RowsAtCompileTime, ColsAtCompileTime,
                                          internal::scalar_constant_op<Scalar>(value));
 }
References EIGEN_STATIC_ASSERT_FIXED_SIZE, Eigen::DenseBase< Derived >::NullaryExpr(), and Eigen::value.
Constant() [2/3]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Constant (Index rows, Index cols, const Scalar & value) static
Returns
an expression of a constant matrix of value value
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this DenseBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Zero() should be used instead.
The template parameter CustomNullaryOp is the type of the functor.
See also
class CwiseNullaryOp
{
   return DenseBase<Derived>::NullaryExpr(rows, cols, internal::scalar_constant_op<Scalar>(value));
 }
References cols, Eigen::DenseBase< Derived >::NullaryExpr(), rows, and Eigen::value.
Constant() [3/3]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Constant (Index size, const Scalar & value) static
Returns
an expression of a constant matrix of value value
The parameter size is the size of the returned vector. Must be compatible with this DenseBase type.
\only_for_vectors
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Zero() should be used instead.
The template parameter CustomNullaryOp is the type of the functor.
See also
class CwiseNullaryOp
{
   return DenseBase<Derived>::NullaryExpr(size, internal::scalar_constant_op<Scalar>(value));
 }
References Eigen::DenseBase< Derived >::NullaryExpr(), size, and Eigen::value.
count()
template<typename Derived > EIGEN_DEVICE_FUNC Index Eigen::DenseBase< Derived >::count
Returns
the number of coefficients which evaluate to true
See also
all(), any()
{
   using Visitor = internal::count_visitor<Scalar>;
   using impl = internal::visit_impl<Derived, Visitor, /*ShortCircuitEvaulation*/ false>;
   Visitor visitor;
   impl::run(derived(), visitor);
   return visitor.res;
 }
References run().
end() [1/2]
template<typename Derived > DenseBase< Derived >::iterator Eigen::DenseBase< Derived >::end inline
returns an iterator to the element following the last element of the 1D vector or array \only_for_vectors
See also
begin(), cend()
{
   EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived);
   return iterator(derived(), size());
 }
end() [2/2]
template<typename Derived > DenseBase< Derived >::const_iterator Eigen::DenseBase< Derived >::end inline
const version of end()
{
   return cend();
 }
EqualSpaced() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::RandomAccessEqualSpacedReturnType Eigen::DenseBase< Derived >::EqualSpaced (const Scalar & low, const Scalar & step) static
{
   EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
   return DenseBase<Derived>::NullaryExpr(Derived::SizeAtCompileTime, internal::equalspaced_op<Scalar>(low, step));
 }
EqualSpaced() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::RandomAccessEqualSpacedReturnType Eigen::DenseBase< Derived >::EqualSpaced (Index size, const Scalar & low, const Scalar & step) static
{
   EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
   return DenseBase<Derived>::NullaryExpr(size, internal::equalspaced_op<Scalar>(low, step));
 }
eval()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EvalReturnType Eigen::DenseBase< Derived >::eval () const inline
Returns
the matrix or vector obtained by evaluating this expression.
Notice that in the case of a plain matrix or vector (not an expression) this function just returns a const reference, in order to avoid a useless copy.
Warning
Be careful with eval() and the auto C++ keyword, as detailed in this page .
{
     // Even though MSVC does not honor strong inlining when the return type
     // is a dynamic matrix, we desperately need strong inlining for fixed
     // size types on MSVC.
     return typename internal::eval<Derived>::type(derived());
   }
References compute_granudrum_aor::type.
Referenced by Eigen::internal::generic_product_impl< Lhs, Homogeneous< RhsArg, Vertical >, TriangularShape, HomogeneousShape, ProductTag >::evalTo().
evalTo()
template<typename Derived > template<typename Dest > EIGEN_DEVICE_FUNC void Eigen::DenseBase< Derived >::evalTo (Dest &) const inline
{
     EIGEN_STATIC_ASSERT((internal::is_same<Dest, void>::value),
                         THE_EVAL_EVALTO_FUNCTION_SHOULD_NEVER_BE_CALLED_FOR_DENSE_OBJECTS);
   }
References EIGEN_STATIC_ASSERT.
fill()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::DenseBase< Derived >::fill (const Scalar & val)
Alias for setConstant(): sets all coefficients in this expression to val.
See also
setConstant(), Constant(), class CwiseNullaryOp
{
   setConstant(val);
 }
flagged()
template<typename Derived > template<unsigned int Added, unsigned int Removed> EIGEN_DEPRECATED const Derived& Eigen::DenseBase< Derived >::flagged () const inline
Deprecated:
it now returns *this
{
     return derived();
   }
forceAlignedAccess() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC ForceAlignedAccess<Derived> Eigen::DenseBase< Derived >::forceAlignedAccess () inline
forceAlignedAccess() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC const ForceAlignedAccess<Derived> Eigen::DenseBase< Derived >::forceAlignedAccess () const inline
forceAlignedAccessIf() [1/2]
template<typename Derived > template<bool Enable> EIGEN_DEVICE_FUNC std::conditional_t<Enable, ForceAlignedAccess<Derived>, Derived&> Eigen::DenseBase< Derived >::forceAlignedAccessIf () inline
forceAlignedAccessIf() [2/2]
template<typename Derived > template<bool Enable> EIGEN_DEVICE_FUNC const std::conditional_t<Enable, ForceAlignedAccess<Derived>, Derived&> Eigen::DenseBase< Derived >::forceAlignedAccessIf () const inline
format()
template<typename Derived > const WithFormat<Derived> Eigen::DenseBase< Derived >::format (const IOFormat & fmt) const inline
Returns
a WithFormat proxy object allowing to print a matrix the with given format fmt.
See class IOFormat for some examples.
See also
class IOFormat, class WithFormat
 { return WithFormat<Derived>(derived(), fmt); }
hasNaN()
template<typename Derived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::hasNaN inline
{
   return derived().cwiseTypedNotEqual(derived()).any();
 }
innerSize()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::DenseBase< Derived >::innerSize () const inline
Returns
the inner size.
Note
For a vector, this is just the size. For a matrix (non-vector), this is the minor dimension with respect to the storage order, i.e., the number of rows for a column-major matrix, and the number of columns for a row-major matrix.
{
     return IsVectorAtCompileTime ? this->size() : int(IsRowMajor) ? this->cols() : this->rows();
   }
References cols, int(), Eigen::DenseBase< Derived >::IsRowMajor, Eigen::DenseBase< Derived >::IsVectorAtCompileTime, rows, and size.
isApprox()
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::isApprox (const DenseBase< OtherDerived > & other, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if *this is approximately equal to other, within the precision determined by prec.
Note
The fuzzy compares are done multiplicatively. Two vectors \(v \) and \(w \) are considered to be approximately equal within precision \(p \) if
\[ \Vert v - w \Vert \leqslant p\,\min(\Vert v\Vert, \Vert w\Vert). \]
For matrices, the comparison is done using the Hilbert-Schmidt norm (aka Frobenius norm L2 norm).
Because of the multiplicativeness of this comparison, one can't use this function to check whether *this is approximately equal to the zero matrix or vector. Indeed, isApprox(zero) returns false unless *this itself is exactly the zero matrix or vector. If you want to test whether *this is zero, use internal::isMuchSmallerThan(const RealScalar&, RealScalar) instead.
See also
internal::isMuchSmallerThan(const RealScalar&, RealScalar) const
{
   return internal::isApprox_selector<Derived, OtherDerived>::run(derived(), other.derived(), prec);
 }
References Eigen::internal::isApprox_selector< Derived, OtherDerived, is_integer >::run().
isApproxToConstant()
template<typename Derived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::isApproxToConstant (const Scalar & val, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if all coefficients in this matrix are approximately equal to val, to within precision prec
{
   typename internal::nested_eval<Derived, 1>::type self(derived());
   for (Index j = 0; j < cols(); ++j)
     for (Index i = 0; i < rows(); ++i)
       if (!internal::isApprox(self.coeff(i, j), val, prec)) return false;
   return true;
 }
isConstant()
template<typename Derived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::isConstant (const Scalar & val, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
This is just an alias for isApproxToConstant().
Returns
true if all coefficients in this matrix are approximately equal to value, to within precision prec
{
   return isApproxToConstant(val, prec);
 }
References calibrate::val.
isMuchSmallerThan() [1/3]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::isMuchSmallerThan (const DenseBase< OtherDerived > & other, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if the norm of *this is much smaller than the norm of other, within the precision determined by prec.
Note
The fuzzy compares are done multiplicatively. A vector \(v \) is considered to be much smaller than a vector \(w \) within precision \(p \) if
\[ \Vert v \Vert \leqslant p\,\Vert w\Vert. \]
For matrices, the comparison is done using the Hilbert-Schmidt norm.
See also
isApprox(), isMuchSmallerThan(const RealScalar&, RealScalar) const
{
   return internal::isMuchSmallerThan_object_selector<Derived, OtherDerived>::run(derived(), other.derived(), prec);
 }
References Eigen::internal::isMuchSmallerThan_object_selector< Derived, OtherDerived, is_integer >::run().
isMuchSmallerThan() [2/3]
template<typename Derived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::isMuchSmallerThan (const RealScalar & other, const RealScalar & prec = NumTraits< Scalar >::dummy_precision()) const
isMuchSmallerThan() [3/3]
template<typename Derived > template<typename Derived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::isMuchSmallerThan (const typename NumTraits< Scalar >::Real & other, const RealScalar & prec) const
Returns
true if the norm of *this is much smaller than other, within the precision determined by prec.
Note
The fuzzy compares are done multiplicatively. A vector \(v \) is considered to be much smaller than \(x \) within precision \(p \) if
\[ \Vert v \Vert \leqslant p\,\vert x\vert. \]
For matrices, the comparison is done using the Hilbert-Schmidt norm. For this reason, the value of the reference scalar other should come from the Hilbert-Schmidt norm of a reference matrix of same dimensions.
See also
isApprox(), isMuchSmallerThan(const DenseBase<OtherDerived>&, RealScalar) const
{
   return internal::isMuchSmallerThan_scalar_selector<Derived>::run(derived(), other, prec);
 }
References Eigen::internal::isMuchSmallerThan_scalar_selector< Derived, is_integer >::run().
isOnes()
template<typename Derived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::isOnes (const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if *this is approximately equal to the matrix where all coefficients are equal to 1, within the precision given by prec.
Example:
Matrix3d m = Matrix3d::Ones();
m(0, 2) += 1e-4;
cout << "Here's the matrix m:" << endl << m << endl;
cout << "m.isOnes() returns: " << m.isOnes() << endl;
cout << "m.isOnes(1e-3) returns: " << m.isOnes(1e-3) << endl;
Output:
See also
class CwiseNullaryOp, Ones()
{
   return isApproxToConstant(Scalar(1), prec);
 }
isZero()
template<typename Derived > EIGEN_DEVICE_FUNC bool Eigen::DenseBase< Derived >::isZero (const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if *this is approximately equal to the zero matrix, within the precision given by prec.
Example:
Matrix3d m = Matrix3d::Zero();
m(0, 2) = 1e-4;
cout << "Here's the matrix m:" << endl << m << endl;
cout << "m.isZero() returns: " << m.isZero() << endl;
cout << "m.isZero(1e-3) returns: " << m.isZero(1e-3) << endl;
Output:
See also
class CwiseNullaryOp, Zero()
{
   typename internal::nested_eval<Derived, 1>::type self(derived());
   for (Index j = 0; j < cols(); ++j)
     for (Index i = 0; i < rows(); ++i)
       if (!internal::isMuchSmallerThan(self.coeff(i, j), static_cast<Scalar>(1), prec)) return false;
   return true;
 }
References cols, i, Eigen::internal::isMuchSmallerThan(), j, and rows.
lazyAssign() [1/2]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived& Eigen::DenseBase< Derived >::lazyAssign (const DenseBase< OtherDerived > & other)
{
   enum { SameType = internal::is_same<typename Derived::Scalar, typename OtherDerived::Scalar>::value };
   EIGEN_STATIC_ASSERT_LVALUE(Derived)
   EIGEN_STATIC_ASSERT_SAME_MATRIX_SIZE(Derived, OtherDerived)
   EIGEN_STATIC_ASSERT(
       SameType,
       YOU_MIXED_DIFFERENT_NUMERIC_TYPES__YOU_NEED_TO_USE_THE_CAST_METHOD_OF_MATRIXBASE_TO_CAST_NUMERIC_TYPES_EXPLICITLY)
   eigen_assert(rows() == other.rows() && cols() == other.cols());
   internal::call_assignment_no_alias(derived(), other.derived());
   return derived();
 }
References Eigen::internal::call_assignment_no_alias(), cols, eigen_assert, EIGEN_STATIC_ASSERT, EIGEN_STATIC_ASSERT_LVALUE, EIGEN_STATIC_ASSERT_SAME_MATRIX_SIZE, and rows.
lazyAssign() [2/2]
template<typename Derived > template<typename OtherDerived > EIGEN_DEPRECATED EIGEN_DEVICE_FUNC Derived& Eigen::DenseBase< Derived >::lazyAssign (const DenseBase< OtherDerived > & other)
Copies other into *this without evaluating other.
Returns
a reference to *this.
Deprecated:
LinSpaced() [1/4]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::RandomAccessLinSpacedReturnType Eigen::DenseBase< Derived >::LinSpaced (const Scalar & low, const Scalar & high) static
Sets a linearly spaced vector.
The function generates 'size' equally spaced values in the closed interval [low,high]. When size is set to 1, a vector of length 1 containing 'high' is returned.
\only_for_vectors
Example:
cout << VectorXi::LinSpaced(4, 7, 10).transpose() << endl;
cout << VectorXd::LinSpaced(5, 0.0, 1.0).transpose() << endl;
Output:
For integer scalar types, an even spacing is possible if and only if the length of the range, i.e., high-low is a scalar multiple of size-1, or if size is a scalar multiple of the number of values high-low+1 (meaning each value can be repeated the same number of time). If one of these two considions is not satisfied, then high is lowered to the largest value satisfying one of this constraint. Here are some examples:
Example:
cout << "Even spacing inputs:" << endl;
cout << VectorXi::LinSpaced(8, 1, 4).transpose() << endl;
cout << VectorXi::LinSpaced(8, 1, 8).transpose() << endl;
cout << VectorXi::LinSpaced(8, 1, 15).transpose() << endl;
cout << "Uneven spacing inputs:" << endl;
cout << VectorXi::LinSpaced(8, 1, 7).transpose() << endl;
cout << VectorXi::LinSpaced(8, 1, 9).transpose() << endl;
cout << VectorXi::LinSpaced(8, 1, 16).transpose() << endl;
Output:
See also
setLinSpaced(Index,const Scalar&,const Scalar&), CwiseNullaryOp Special version for fixed size types which does not require the size parameter.
{
   EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
   EIGEN_STATIC_ASSERT_FIXED_SIZE(Derived)
   return DenseBase<Derived>::NullaryExpr(Derived::SizeAtCompileTime,
                                          internal::linspaced_op<Scalar>(low, high, Derived::SizeAtCompileTime));
 }
References EIGEN_STATIC_ASSERT_FIXED_SIZE, EIGEN_STATIC_ASSERT_VECTOR_ONLY, and Eigen::DenseBase< Derived >::NullaryExpr().
LinSpaced() [2/4]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::RandomAccessLinSpacedReturnType Eigen::DenseBase< Derived >::LinSpaced (Index size, const Scalar & low, const Scalar & high) static
Sets a linearly spaced vector.
The function generates 'size' equally spaced values in the closed interval [low,high]. When size is set to 1, a vector of length 1 containing 'high' is returned.
\only_for_vectors
Example:
cout << VectorXi::LinSpaced(4, 7, 10).transpose() << endl;
cout << VectorXd::LinSpaced(5, 0.0, 1.0).transpose() << endl;
Output:
For integer scalar types, an even spacing is possible if and only if the length of the range, i.e., high-low is a scalar multiple of size-1, or if size is a scalar multiple of the number of values high-low+1 (meaning each value can be repeated the same number of time). If one of these two considions is not satisfied, then high is lowered to the largest value satisfying one of this constraint. Here are some examples:
Example:
cout << "Even spacing inputs:" << endl;
cout << VectorXi::LinSpaced(8, 1, 4).transpose() << endl;
cout << VectorXi::LinSpaced(8, 1, 8).transpose() << endl;
cout << VectorXi::LinSpaced(8, 1, 15).transpose() << endl;
cout << "Uneven spacing inputs:" << endl;
cout << VectorXi::LinSpaced(8, 1, 7).transpose() << endl;
cout << VectorXi::LinSpaced(8, 1, 9).transpose() << endl;
cout << VectorXi::LinSpaced(8, 1, 16).transpose() << endl;
Output:
See also
setLinSpaced(Index,const Scalar&,const Scalar&), CwiseNullaryOp
{
   EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
   return DenseBase<Derived>::NullaryExpr(size, internal::linspaced_op<Scalar>(low, high, size));
 }
References EIGEN_STATIC_ASSERT_VECTOR_ONLY, Eigen::DenseBase< Derived >::NullaryExpr(), and size.
LinSpaced() [3/4]
template<typename Derived > EIGEN_DEPRECATED EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::RandomAccessLinSpacedReturnType Eigen::DenseBase< Derived >::LinSpaced (Sequential_t , const Scalar & low, const Scalar & high) static
Deprecated:
because of accuracy loss. In Eigen 3.3, it is an alias for LinSpaced(const Scalar&,const Scalar&)
See also
LinSpaced(const Scalar&, const Scalar&)
{
   EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
   EIGEN_STATIC_ASSERT_FIXED_SIZE(Derived)
   return DenseBase<Derived>::NullaryExpr(Derived::SizeAtCompileTime,
                                          internal::linspaced_op<Scalar>(low, high, Derived::SizeAtCompileTime));
 }
LinSpaced() [4/4]
template<typename Derived > EIGEN_DEPRECATED EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::RandomAccessLinSpacedReturnType Eigen::DenseBase< Derived >::LinSpaced (Sequential_t , Index size, const Scalar & low, const Scalar & high) static
Deprecated:
because of accuracy loss. In Eigen 3.3, it is an alias for LinSpaced(Index,const Scalar&,const Scalar&)
\only_for_vectors
Example:
cout << VectorXi::LinSpaced(Sequential, 4, 7, 10).transpose() << endl;
cout << VectorXd::LinSpaced(Sequential, 5, 0.0, 1.0).transpose() << endl;
Output:
See also
LinSpaced(Index,const Scalar&, const Scalar&), setLinSpaced(Index,const Scalar&,const Scalar&)
{
   EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
   return DenseBase<Derived>::NullaryExpr(size, internal::linspaced_op<Scalar>(low, high, size));
 }
References EIGEN_STATIC_ASSERT_VECTOR_ONLY, Eigen::DenseBase< Derived >::NullaryExpr(), and size.
lpNorm()
template<typename Derived > template<int p> RealScalar Eigen::DenseBase< Derived >::lpNorm () const
maxCoeff() [1/6]
template<typename Derived > template<int NaNPropagation> EIGEN_DEVICE_FUNC internal::traits<Derived>::Scalar Eigen::DenseBase< Derived >::maxCoeff () const
maxCoeff() [2/6]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::maxCoeff () const inline
Returns
the maximum of all coefficients of *this. In case *this contains NaN, NaNPropagation determines the behavior: NaNPropagation == PropagateFast : undefined NaNPropagation == PropagateNaN : result is NaN NaNPropagation == PropagateNumbers : result is maximum of elements that are not NaN
Warning
the matrix must be not empty, otherwise an assertion is triggered.
{
     return maxCoeff<PropagateFast>();
   }
maxCoeff() [3/6]
template<typename Derived > template<int NaNPropagation, typename IndexType > EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::maxCoeff (IndexType * index) const
Returns
the maximum of all coefficients of *this and puts in *index its location.
In case *this contains NaN, NaNPropagation determines the behavior: NaNPropagation == PropagateFast : undefined NaNPropagation == PropagateNaN : result is NaN NaNPropagation == PropagateNumbers : result is maximum of elements that are not NaN
Warning
the matrix must be not empty, otherwise an assertion is triggered.
See also
DenseBase::maxCoeff(IndexType*,IndexType*), DenseBase::minCoeff(IndexType*,IndexType*), DenseBase::visitor(), DenseBase::maxCoeff()
{
   eigen_assert(this->rows() > 0 && this->cols() > 0 && "you are using an empty matrix");
   EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
   internal::minmax_coeff_visitor<Derived, false, NaNPropagation> maxVisitor;
   this->visit(maxVisitor);
   *index = (RowsAtCompileTime == 1) ? maxVisitor.col : maxVisitor.row;
   return maxVisitor.res;
 }
References Eigen::internal::coeff_visitor< Derived >::col, cols, eigen_assert, EIGEN_STATIC_ASSERT_VECTOR_ONLY, Eigen::internal::coeff_visitor< Derived >::res, Eigen::internal::coeff_visitor< Derived >::row, and rows.
maxCoeff() [4/6]
template<typename Derived > template<typename IndexType > EIGEN_DEVICE_FUNC internal::traits<Derived>::Scalar Eigen::DenseBase< Derived >::maxCoeff (IndexType * index) const inline
{
     return maxCoeff<PropagateFast>(index);
   }
maxCoeff() [5/6]
template<typename Derived > template<int NaNPropagation, typename IndexType > EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::maxCoeff (IndexType * rowId, IndexType * colId) const
Returns
the maximum of all coefficients of *this and puts in *row and *col its location.
In case *this contains NaN, NaNPropagation determines the behavior: NaNPropagation == PropagateFast : undefined NaNPropagation == PropagateNaN : result is NaN NaNPropagation == PropagateNumbers : result is maximum of elements that are not NaN
Warning
the matrix must be not empty, otherwise an assertion is triggered.
See also
DenseBase::minCoeff(IndexType*,IndexType*), DenseBase::visit(), DenseBase::maxCoeff()
{
   eigen_assert(this->rows() > 0 && this->cols() > 0 && "you are using an empty matrix");
   internal::minmax_coeff_visitor<Derived, false, NaNPropagation> maxVisitor;
   this->visit(maxVisitor);
   *rowPtr = maxVisitor.row;
   if (colPtr) *colPtr = maxVisitor.col;
   return maxVisitor.res;
 }
References Eigen::internal::coeff_visitor< Derived >::col, cols, eigen_assert, Eigen::internal::coeff_visitor< Derived >::res, Eigen::internal::coeff_visitor< Derived >::row, and rows.
maxCoeff() [6/6]
template<typename Derived > template<typename IndexType > EIGEN_DEVICE_FUNC internal::traits<Derived>::Scalar Eigen::DenseBase< Derived >::maxCoeff (IndexType * row, IndexType * col) const inline
{
     return maxCoeff<PropagateFast>(row, col);
   }
References col(), and row().
mean()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::mean
Returns
the mean of all coefficients of *this
See also
trace(), prod(), sum()
{
 #ifdef __INTEL_COMPILER
 #pragma warning push
 #pragma warning(disable : 2259)
 #endif
   return Scalar(derived().redux(Eigen::internal::scalar_sum_op<Scalar, Scalar>())) / Scalar(this->size());
 #ifdef __INTEL_COMPILER
 #pragma warning pop
 #endif
 }
References size.
minCoeff() [1/6]
template<typename Derived > template<int NaNPropagation> EIGEN_DEVICE_FUNC internal::traits<Derived>::Scalar Eigen::DenseBase< Derived >::minCoeff () const
minCoeff() [2/6]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::minCoeff () const inline
Returns
the minimum of all coefficients of *this. In case *this contains NaN, NaNPropagation determines the behavior: NaNPropagation == PropagateFast : undefined NaNPropagation == PropagateNaN : result is NaN NaNPropagation == PropagateNumbers : result is minimum of elements that are not NaN
Warning
the matrix must be not empty, otherwise an assertion is triggered.
{
     return minCoeff<PropagateFast>();
   }
minCoeff() [3/6]
template<typename Derived > template<int NaNPropagation, typename IndexType > EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::minCoeff (IndexType * index) const
Returns
the minimum of all coefficients of *this and puts in *index its location.
In case *this contains NaN, NaNPropagation determines the behavior: NaNPropagation == PropagateFast : undefined NaNPropagation == PropagateNaN : result is NaN NaNPropagation == PropagateNumbers : result is maximum of elements that are not NaN
Warning
the matrix must be not empty, otherwise an assertion is triggered.
See also
DenseBase::minCoeff(IndexType*,IndexType*), DenseBase::maxCoeff(IndexType*,IndexType*), DenseBase::visit(), DenseBase::minCoeff()
{
   eigen_assert(this->rows() > 0 && this->cols() > 0 && "you are using an empty matrix");
   EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
   internal::minmax_coeff_visitor<Derived, true, NaNPropagation> minVisitor;
   this->visit(minVisitor);
   *index = IndexType((RowsAtCompileTime == 1) ? minVisitor.col : minVisitor.row);
   return minVisitor.res;
 }
References Eigen::internal::coeff_visitor< Derived >::col, cols, eigen_assert, EIGEN_STATIC_ASSERT_VECTOR_ONLY, Eigen::internal::coeff_visitor< Derived >::res, Eigen::internal::coeff_visitor< Derived >::row, and rows.
minCoeff() [4/6]
template<typename Derived > template<typename IndexType > EIGEN_DEVICE_FUNC internal::traits<Derived>::Scalar Eigen::DenseBase< Derived >::minCoeff (IndexType * index) const inline
{
     return minCoeff<PropagateFast>(index);
   }
minCoeff() [5/6]
template<typename Derived > template<int NaNPropagation, typename IndexType > EIGEN_DEVICE_FUNC internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::minCoeff (IndexType * rowId, IndexType * colId) const
Returns
the minimum of all coefficients of *this and puts in *row and *col its location.
In case *this contains NaN, NaNPropagation determines the behavior: NaNPropagation == PropagateFast : undefined NaNPropagation == PropagateNaN : result is NaN NaNPropagation == PropagateNumbers : result is maximum of elements that are not NaN
Warning
the matrix must be not empty, otherwise an assertion is triggered.
See also
DenseBase::minCoeff(Index*), DenseBase::maxCoeff(Index*,Index*), DenseBase::visit(), DenseBase::minCoeff()
{
   eigen_assert(this->rows() > 0 && this->cols() > 0 && "you are using an empty matrix");
   internal::minmax_coeff_visitor<Derived, true, NaNPropagation> minVisitor;
   this->visit(minVisitor);
   *rowId = minVisitor.row;
   if (colId) *colId = minVisitor.col;
   return minVisitor.res;
 }
References Eigen::internal::coeff_visitor< Derived >::col, cols, eigen_assert, Eigen::internal::coeff_visitor< Derived >::res, Eigen::internal::coeff_visitor< Derived >::row, and rows.
minCoeff() [6/6]
template<typename Derived > template<typename IndexType > EIGEN_DEVICE_FUNC internal::traits<Derived>::Scalar Eigen::DenseBase< Derived >::minCoeff (IndexType * row, IndexType * col) const inline
{
     return minCoeff<PropagateFast>(row, col);
   }
References col(), and row().
nestByValue()
template<typename Derived > EIGEN_DEVICE_FUNC const NestByValue< Derived > Eigen::DenseBase< Derived >::nestByValue inline
Returns
an expression of the temporary version of *this.
{
   return NestByValue<Derived>(derived());
 }
NullaryExpr() [1/6]
template<typename Derived > template<typename CustomNullaryOp > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseNullaryOp<CustomNullaryOp, typename DenseBase<Derived>::PlainObject> Eigen::DenseBase< Derived >::NullaryExpr (const CustomNullaryOp & func)
Returns
an expression of a matrix defined by a custom functor func
This variant is only for fixed-size DenseBase types. For dynamic-size types, you need to use the variants taking size arguments.
The template parameter CustomNullaryOp is the type of the functor.
See also
class CwiseNullaryOp
{
   return CwiseNullaryOp<CustomNullaryOp, PlainObject>(RowsAtCompileTime, ColsAtCompileTime, func);
 }
NullaryExpr() [2/6]
template<typename Derived > template<typename CustomNullaryOp > static EIGEN_DEVICE_FUNC const CwiseNullaryOp<CustomNullaryOp, PlainObject> Eigen::DenseBase< Derived >::NullaryExpr (const CustomNullaryOp & func) static
NullaryExpr() [3/6]
template<typename Derived > template<typename CustomNullaryOp > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseNullaryOp<CustomNullaryOp, typename DenseBase<Derived>::PlainObject> Eigen::DenseBase< Derived >::NullaryExpr (Index rows, Index cols, const CustomNullaryOp & func)
Returns
an expression of a matrix defined by a custom functor func
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Zero() should be used instead.
The template parameter CustomNullaryOp is the type of the functor.
See also
class CwiseNullaryOp
{
   return CwiseNullaryOp<CustomNullaryOp, PlainObject>(rows, cols, func);
 }
References cols, and rows.
NullaryExpr() [4/6]
template<typename Derived > template<typename CustomNullaryOp > static EIGEN_DEVICE_FUNC const CwiseNullaryOp<CustomNullaryOp, PlainObject> Eigen::DenseBase< Derived >::NullaryExpr (Index rows, Index cols, const CustomNullaryOp & func) static
Referenced by Eigen::DenseBase< Derived >::Constant(), Eigen::MatrixBase< Derived >::Identity(), and Eigen::DenseBase< Derived >::LinSpaced().
NullaryExpr() [5/6]
template<typename Derived > template<typename CustomNullaryOp > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const CwiseNullaryOp<CustomNullaryOp, typename DenseBase<Derived>::PlainObject> Eigen::DenseBase< Derived >::NullaryExpr (Index size, const CustomNullaryOp & func)
Returns
an expression of a matrix defined by a custom functor func
The parameter size is the size of the returned vector. Must be compatible with this MatrixBase type.
\only_for_vectors
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Zero() should be used instead.
The template parameter CustomNullaryOp is the type of the functor.
Here is an example with C++11 random generators:
#include <Eigen/Core>
#include <iostream>
#include <random>
int main() {
  std::default_random_engine generator;
  std::poisson_distribution<int> distribution(4.1);
  auto poisson = [&]() { return distribution(generator); };
  Eigen::RowVectorXi v = Eigen::RowVectorXi::NullaryExpr(10, poisson);
  std::cout << v << "\n";
}
Output:
See also
class CwiseNullaryOp
{
   EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
   if (RowsAtCompileTime == 1)
     return CwiseNullaryOp<CustomNullaryOp, PlainObject>(1, size, func);
   else
     return CwiseNullaryOp<CustomNullaryOp, PlainObject>(size, 1, func);
 }
References EIGEN_STATIC_ASSERT_VECTOR_ONLY, and size.
NullaryExpr() [6/6]
template<typename Derived > template<typename CustomNullaryOp > static EIGEN_DEVICE_FUNC const CwiseNullaryOp<CustomNullaryOp, PlainObject> Eigen::DenseBase< Derived >::NullaryExpr (Index size, const CustomNullaryOp & func) static
Ones() [1/3]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Ones static
Returns
an expression of a fixed-size matrix or vector where all coefficients equal one.
This variant is only for fixed-size MatrixBase types. For dynamic-size types, you need to use the variants taking size arguments.
Example:
cout << Matrix2d::Ones() << endl;
cout << 6 * RowVector4i::Ones() << endl;
Output:
See also
Ones(Index), Ones(Index,Index), isOnes(), class Ones
{
   return Constant(Scalar(1));
 }
Ones() [2/3]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Ones (Index rows, Index cols) static
Returns
an expression of a matrix where all coefficients equal one.
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Ones() should be used instead.
Example:
cout << MatrixXi::Ones(2, 3) << endl;
Output:
See also
Ones(), Ones(Index), isOnes(), class Ones
{
   return Constant(rows, cols, Scalar(1));
 }
References cols, and rows.
Ones() [3/3]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstantReturnType Eigen::DenseBase< Derived >::Ones (Index newSize) static
Returns
an expression of a vector where all coefficients equal one.
The parameter newSize is the size of the returned vector. Must be compatible with this MatrixBase type.
\only_for_vectors
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Ones() should be used instead.
Example:
cout << 6 * RowVectorXi::Ones(4) << endl;
cout << VectorXf::Ones(2) << endl;
Output:
See also
Ones(), Ones(Index,Index), isOnes(), class Ones
                    {
   return Constant(newSize, Scalar(1));
 }
operator*=()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::operator*= (const Scalar & other)
{
   internal::call_assignment(this->derived(), PlainObject::Constant(rows(), cols(), other),
                             internal::mul_assign_op<Scalar, Scalar>());
   return derived();
 }
References Eigen::internal::call_assignment(), cols, and rows.
operator+=()
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC Derived & Eigen::DenseBase< Derived >::operator+= (const EigenBase< OtherDerived > & other)
{
   call_assignment(derived(), other.derived(), internal::add_assign_op<Scalar, typename OtherDerived::Scalar>());
   return derived();
 }
References Eigen::internal::call_assignment(), and Eigen::EigenBase< Derived >::derived().
operator-=()
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC Derived & Eigen::DenseBase< Derived >::operator-= (const EigenBase< OtherDerived > & other)
{
   call_assignment(derived(), other.derived(), internal::sub_assign_op<Scalar, typename OtherDerived::Scalar>());
   return derived();
 }
References Eigen::internal::call_assignment(), and Eigen::EigenBase< Derived >::derived().
operator/=()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::operator/= (const Scalar & other)
{
   internal::call_assignment(this->derived(), PlainObject::Constant(rows(), cols(), other),
                             internal::div_assign_op<Scalar, Scalar>());
   return derived();
 }
References Eigen::internal::call_assignment(), cols, and rows.
operator<<() [1/2]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC CommaInitializer< Derived > Eigen::DenseBase< Derived >::operator<< (const DenseBase< OtherDerived > & other) inline
See also
operator<<(const Scalar&)
{
   return CommaInitializer<Derived>(*static_cast<Derived*>(this), other);
 }
operator<<() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC CommaInitializer< Derived > Eigen::DenseBase< Derived >::operator<< (const Scalar & s) inline
Convenient operator to set the coefficients of a matrix.
The coefficients must be provided in a row major order and exactly match the size of the matrix. Otherwise an assertion is raised.
Example:
Matrix3i m1;
m1 << 1, 2, 3, 4, 5, 6, 7, 8, 9;
cout << m1 << endl << endl;
Matrix3i m2 = Matrix3i::Identity();
m2.block(0, 0, 2, 2) << 10, 11, 12, 13;
cout << m2 << endl << endl;
Vector2i v1;
v1 << 14, 15;
m2 << v1.transpose(), 16, v1, m1.block(1, 1, 2, 2);
cout << m2 << endl;
Output:
Note
According the c++ standard, the argument expressions of this comma initializer are evaluated in arbitrary order.
See also
CommaInitializer::finished(), class CommaInitializer
{
   return CommaInitializer<Derived>(*static_cast<Derived*>(this), s);
 }
References s.
operator=() [1/4]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::operator= (const DenseBase< Derived > & other)
Special case of the template operator=, in order to prevent the compiler from generating a default operator= (issue hit with g++ 4.1)
{
   internal::call_assignment(derived(), other.derived());
   return derived();
 }
References Eigen::internal::call_assignment().
operator=() [2/4]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::operator= (const DenseBase< OtherDerived > & other)
Copies other into *this.
Returns
a reference to *this.
{
   internal::call_assignment(derived(), other.derived());
   return derived();
 }
References Eigen::internal::call_assignment().
operator=() [3/4]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC Derived & Eigen::DenseBase< Derived >::operator= (const EigenBase< OtherDerived > & other)
Copies the generic expression other into *this.
The expression must provide a (templated) evalTo(Derived& dst) const function which does the actual job. In practice, this allows any user to write its own special matrix without having to modify MatrixBase
Returns
a reference to *this.
{
   call_assignment(derived(), other.derived());
   return derived();
 }
References Eigen::internal::call_assignment(), and Eigen::EigenBase< Derived >::derived().
operator=() [4/4]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC Derived & Eigen::DenseBase< Derived >::operator= (const ReturnByValue< OtherDerived > & func)
{
   other.evalTo(derived());
   return derived();
 }
References Eigen::ReturnByValue< Derived >::evalTo().
outerSize()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::DenseBase< Derived >::outerSize () const inline
Returns
the outer size.
Note
For a vector, this returns just 1. For a matrix (non-vector), this is the major dimension with respect to the storage order, i.e., the number of columns for a column-major matrix, and the number of rows for a row-major matrix.
{
     return IsVectorAtCompileTime ? 1 : int(IsRowMajor) ? this->rows() : this->cols();
   }
References cols, int(), Eigen::DenseBase< Derived >::IsRowMajor, Eigen::DenseBase< Derived >::IsVectorAtCompileTime, and rows.
prod()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::prod
Returns
the product of all coefficients of *this
Example:
Matrix3d m = Matrix3d::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is the product of all the coefficients:" << endl << m.prod() << endl;
Output:
See also
sum(), mean(), trace()
{
   if (SizeAtCompileTime == 0 || (SizeAtCompileTime == Dynamic && size() == 0)) return Scalar(1);
   return derived().redux(Eigen::internal::scalar_product_op<Scalar>());
 }
References Eigen::Dynamic, and size.
Random() [1/3]
template<typename Derived > const DenseBase< Derived >::RandomReturnType Eigen::DenseBase< Derived >::Random inline static
Returns
a fixed-size random matrix or vector expression
Numbers are uniformly spread through their whole definition range for integer types, and in the [-1:1] range for floating point scalar types.
This variant is only for fixed-size MatrixBase types. For dynamic-size types, you need to use the variants taking size arguments.
Example:
cout << 100 * Matrix2i::Random() << endl;
Output:
This expression has the "evaluate before nesting" flag so that it will be evaluated into a temporary matrix whenever it is nested in a larger expression. This prevents unexpected behavior with expressions involving random matrices.
\not_reentrant
See also
DenseBase::setRandom(), DenseBase::Random(Index,Index), DenseBase::Random(Index)
{
   return NullaryExpr(RowsAtCompileTime, ColsAtCompileTime, internal::scalar_random_op<Scalar>());
 }
Random() [2/3]
template<typename Derived > const DenseBase< Derived >::RandomReturnType Eigen::DenseBase< Derived >::Random (Index rows, Index cols) inline static
Returns
a random matrix expression
Numbers are uniformly spread through their whole definition range for integer types, and in the [-1:1] range for floating point scalar types.
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
\not_reentrant
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Random() should be used instead.
Example:
cout << MatrixXi::Random(2, 3) << endl;
Output:
This expression has the "evaluate before nesting" flag so that it will be evaluated into a temporary matrix whenever it is nested in a larger expression. This prevents unexpected behavior with expressions involving random matrices.
See DenseBase::NullaryExpr(Index, const CustomNullaryOp&) for an example using C++11 random generators.
See also
DenseBase::setRandom(), DenseBase::Random(Index), DenseBase::Random()
{
   return NullaryExpr(rows, cols, internal::scalar_random_op<Scalar>());
 }
References cols, and rows.
Random() [3/3]
template<typename Derived > const DenseBase< Derived >::RandomReturnType Eigen::DenseBase< Derived >::Random (Index size) inline static
Returns
a random vector expression
Numbers are uniformly spread through their whole definition range for integer types, and in the [-1:1] range for floating point scalar types.
The parameter size is the size of the returned vector. Must be compatible with this MatrixBase type.
\only_for_vectors \not_reentrant
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Random() should be used instead.
Example:
cout << VectorXi::Random(2) << endl;
Output:
This expression has the "evaluate before nesting" flag so that it will be evaluated into a temporary vector whenever it is nested in a larger expression. This prevents unexpected behavior with expressions involving random matrices.
See also
DenseBase::setRandom(), DenseBase::Random(Index,Index), DenseBase::Random()
{
   return NullaryExpr(size, internal::scalar_random_op<Scalar>());
 }
References size.
redux() [1/2]
template<typename Derived > template<typename BinaryOp > EIGEN_DEVICE_FUNC Scalar Eigen::DenseBase< Derived >::redux (const BinaryOp & func) const
redux() [2/2]
template<typename Derived > template<typename Func > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::traits<Derived>::Scalar Eigen::DenseBase< Derived >::redux (const Func & func) const
Returns
the result of a full redux operation on the whole matrix or vector using func
The template parameter BinaryOp is the type of the functor func which must be an associative operator. Both current C++98 and C++11 functor styles are handled.
Warning
the matrix must be not empty, otherwise an assertion is triggered.
See also
DenseBase::sum(), DenseBase::minCoeff(), DenseBase::maxCoeff(), MatrixBase::colwise(), MatrixBase::rowwise()
{
   eigen_assert(this->rows() > 0 && this->cols() > 0 && "you are using an empty matrix");
   typedef typename internal::redux_evaluator<Derived> ThisEvaluator;
   ThisEvaluator thisEval(derived());
   // The initial expression is passed to the reducer as an additional argument instead of
   // passing it as a member of redux_evaluator to help
   return internal::redux_impl<Func, ThisEvaluator>::run(thisEval, func, derived());
 }
References cols, eigen_assert, rows, and run().
replicate() [1/2]
template<typename Derived > template<int RowFactor, int ColFactor> EIGEN_DEVICE_FUNC const Replicate< Derived, RowFactor, ColFactor > Eigen::DenseBase< Derived >::replicate
Returns
an expression of the replication of *this
Example:
MatrixXi m = MatrixXi::Random(2, 3);
cout << "Here is the matrix m:" << endl << m << endl;
cout << "m.replicate<3,2>() = ..." << endl;
cout << m.replicate<3, 2>() << endl;
Output:
See also
VectorwiseOp::replicate(), DenseBase::replicate(Index,Index), class Replicate
{
   return Replicate<Derived, RowFactor, ColFactor>(derived());
 }
replicate() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC const Replicate<Derived, Dynamic, Dynamic> Eigen::DenseBase< Derived >::replicate (Index rowFactor, Index colFactor) const inline
Returns
an expression of the replication of *this
Example:
Vector3i v = Vector3i::Random();
cout << "Here is the vector v:" << endl << v << endl;
cout << "v.replicate(2,5) = ..." << endl;
cout << v.replicate(2, 5) << endl;
Output:
See also
VectorwiseOp::replicate(), DenseBase::replicate<int,int>(), class Replicate
{
     return Replicate<Derived, Dynamic, Dynamic>(derived(), rowFactor, colFactor);
   }
resize() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC void Eigen::DenseBase< Derived >::resize (Index newSize) inline
Only plain matrices/arrays, not expressions, may be resized; therefore the only useful resize methods are Matrix::resize() and Array::resize(). The present method only asserts that the new size equals the old size, and does nothing else.
{
     EIGEN_ONLY_USED_FOR_DEBUG(newSize);
     eigen_assert(newSize == this->size() && "DenseBase::resize() does not actually allow to resize.");
   }
References eigen_assert, EIGEN_ONLY_USED_FOR_DEBUG, and size.
Referenced by Eigen::TriangularBase< Derived >::evalToLazy().
resize() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC void Eigen::DenseBase< Derived >::resize (Index rows, Index cols) inline
Only plain matrices/arrays, not expressions, may be resized; therefore the only useful resize methods are Matrix::resize() and Array::resize(). The present method only asserts that the new size equals the old size, and does nothing else.
{
     EIGEN_ONLY_USED_FOR_DEBUG(rows);
     EIGEN_ONLY_USED_FOR_DEBUG(cols);
     eigen_assert(rows == this->rows() && cols == this->cols() &&
                  "DenseBase::resize() does not actually allow to resize.");
   }
References cols, eigen_assert, EIGEN_ONLY_USED_FOR_DEBUG, and rows.
reverse() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC DenseBase< Derived >::ReverseReturnType Eigen::DenseBase< Derived >::reverse inline
Returns
an expression of the reverse of *this.
Example:
MatrixXi m = MatrixXi::Random(3, 4);
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is the reverse of m:" << endl << m.reverse() << endl;
cout << "Here is the coefficient (1,0) in the reverse of m:" << endl << m.reverse()(1, 0) << endl;
cout << "Let us overwrite this coefficient with the value 4." << endl;
m.reverse()(1, 0) = 4;
cout << "Now the matrix m is:" << endl << m << endl;
Output:
{
   return ReverseReturnType(derived());
 }
reverse() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC ConstReverseReturnType Eigen::DenseBase< Derived >::reverse () const inline
This is the const version of reverse().
 { return ConstReverseReturnType(derived()); }
reverseInPlace()
template<typename Derived > EIGEN_DEVICE_FUNC void Eigen::DenseBase< Derived >::reverseInPlace inline
This is the "in place" version of reverse: it reverses *this.
In most cases it is probably better to simply use the reversed expression of a matrix. However, when reversing the matrix data itself is really needed, then this "in-place" version is probably the right choice because it provides the following additional benefits:
less error prone: doing the same operation with .reverse() requires special care:
m = m.reverse().eval();
this API enables reverse operations without the need for a temporary
it allows future optimizations (cache friendliness, etc.)
See also
VectorwiseOp::reverseInPlace(), reverse()
{
   constexpr int HalfRowsAtCompileTime = RowsAtCompileTime == Dynamic ? Dynamic : RowsAtCompileTime / 2;
   constexpr int HalfColsAtCompileTime = ColsAtCompileTime == Dynamic ? Dynamic : ColsAtCompileTime / 2;
   if (cols() > rows()) {
     Index half = cols() / 2;
     this->template leftCols<HalfColsAtCompileTime>(half).swap(
         this->template rightCols<HalfColsAtCompileTime>(half).reverse());
     if ((cols() % 2) == 1) {
       Index half2 = rows() / 2;
       col(half).template head<HalfRowsAtCompileTime>(half2).swap(
           col(half).template tail<HalfRowsAtCompileTime>(half2).reverse());
     }
   } else {
     Index half = rows() / 2;
     this->template topRows<HalfRowsAtCompileTime>(half).swap(
         this->template bottomRows<HalfRowsAtCompileTime>(half).reverse());
     if ((rows() % 2) == 1) {
       Index half2 = cols() / 2;
       row(half).template head<HalfColsAtCompileTime>(half2).swap(
           row(half).template tail<HalfColsAtCompileTime>(half2).reverse());
     }
   }
 }
References col(), cols, Eigen::Dynamic, reverse(), row(), and rows.
rowwise() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC DenseBase< Derived >::RowwiseReturnType Eigen::DenseBase< Derived >::rowwise inline
Returns
a writable VectorwiseOp wrapper of *this providing additional partial reduction operations
See also
colwise(), class VectorwiseOp, TutorialReductionsVisitorsBroadcasting
{
   return RowwiseReturnType(derived());
 }
rowwise() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC ConstRowwiseReturnType Eigen::DenseBase< Derived >::rowwise () const inline
Returns
a VectorwiseOp wrapper of *this for broadcasting and partial reductions
Example:
Matrix3d m = Matrix3d::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is the sum of each row:" << endl << m.rowwise().sum() << endl;
cout << "Here is the maximum absolute value of each row:" << endl << m.cwiseAbs().rowwise().maxCoeff() << endl;
Output:
See also
colwise(), class VectorwiseOp, TutorialReductionsVisitorsBroadcasting
 { return ConstRowwiseReturnType(derived()); }
Referenced by Eigen::umeyama().
select() [1/6]
template<typename Derived > template<typename ThenDerived , typename ElseDerived > EIGEN_DEVICE_FUNC CwiseTernaryOp<internal::scalar_boolean_select_op<typename DenseBase<ThenDerived>::Scalar, typename DenseBase<ElseDerived>::Scalar, Scalar>, ThenDerived, ElseDerived, Derived> Eigen::DenseBase< Derived >::select (const DenseBase< ThenDerived > & thenMatrix, const DenseBase< ElseDerived > & elseMatrix) const inline
select() [2/6]
template<typename Derived > template<typename ThenDerived , typename ElseDerived > EIGEN_DEVICE_FUNC CwiseTernaryOp< internal::scalar_boolean_select_op<typename DenseBase<ThenDerived>::Scalar, typename DenseBase<ElseDerived>::Scalar, typename DenseBase<Derived>::Scalar>, ThenDerived, ElseDerived, Derived> Eigen::DenseBase< Derived >::select (const DenseBase< ThenDerived > & thenMatrix, const DenseBase< ElseDerived > & elseMatrix) const inline
Returns
a matrix where each coefficient (i,j) is equal to thenMatrix(i,j) if *this(i,j) != Scalar(0), and elseMatrix(i,j) otherwise.
Example:
MatrixXi m(3, 3);
m << 1, 2, 3, 4, 5, 6, 7, 8, 9;
m = (m.array() >= 5).select(-m, m);
cout << m << endl;
Output:
See also
DenseBase::bitwiseSelect(const DenseBase<ThenDerived>&, const DenseBase<ElseDerived>&)
{
   using Op = internal::scalar_boolean_select_op<typename DenseBase<ThenDerived>::Scalar,
                                                 typename DenseBase<ElseDerived>::Scalar, Scalar>;
   return CwiseTernaryOp<Op, ThenDerived, ElseDerived, Derived>(thenMatrix.derived(), elseMatrix.derived(), derived(),
                                                                Op());
 }
select() [3/6]
template<typename Derived > template<typename ThenDerived > EIGEN_DEVICE_FUNC CwiseTernaryOp<internal::scalar_boolean_select_op<typename DenseBase<ThenDerived>::Scalar, typename DenseBase<ThenDerived>::Scalar, Scalar>, ThenDerived, typename DenseBase<ThenDerived>::ConstantReturnType, Derived> Eigen::DenseBase< Derived >::select (const DenseBase< ThenDerived > & thenMatrix, const typename DenseBase< ThenDerived >::Scalar & elseScalar) const inline
select() [4/6]
template<typename Derived > template<typename ThenDerived > EIGEN_DEVICE_FUNC CwiseTernaryOp< internal::scalar_boolean_select_op<typename DenseBase<ThenDerived>::Scalar, typename DenseBase<ThenDerived>::Scalar, typename DenseBase<Derived>::Scalar>, ThenDerived, typename DenseBase<ThenDerived>::ConstantReturnType, Derived> Eigen::DenseBase< Derived >::select (const DenseBase< ThenDerived > & thenMatrix, const typename DenseBase< ThenDerived >::Scalar & elseScalar) const inline
Version of DenseBase::select(const DenseBase&, const DenseBase&) with the else expression being a scalar value.
See also
DenseBase::booleanSelect(const DenseBase<ThenDerived>&, const DenseBase<ElseDerived>&) const, class Select
{
   using ElseConstantType = typename DenseBase<ThenDerived>::ConstantReturnType;
   using Op = internal::scalar_boolean_select_op<typename DenseBase<ThenDerived>::Scalar,
                                                 typename DenseBase<ThenDerived>::Scalar, Scalar>;
   return CwiseTernaryOp<Op, ThenDerived, ElseConstantType, Derived>(
       thenMatrix.derived(), ElseConstantType(rows(), cols(), elseScalar), derived(), Op());
 }
References cols, and rows.
select() [5/6]
template<typename Derived > template<typename ElseDerived > EIGEN_DEVICE_FUNC CwiseTernaryOp<internal::scalar_boolean_select_op<typename DenseBase<ElseDerived>::Scalar, typename DenseBase<ElseDerived>::Scalar, Scalar>, typename DenseBase<ElseDerived>::ConstantReturnType, ElseDerived, Derived> Eigen::DenseBase< Derived >::select (const typename DenseBase< ElseDerived >::Scalar & thenScalar, const DenseBase< ElseDerived > & elseMatrix) const inline
select() [6/6]
template<typename Derived > template<typename ElseDerived > EIGEN_DEVICE_FUNC CwiseTernaryOp< internal::scalar_boolean_select_op<typename DenseBase<ElseDerived>::Scalar, typename DenseBase<ElseDerived>::Scalar, typename DenseBase<Derived>::Scalar>, typename DenseBase<ElseDerived>::ConstantReturnType, ElseDerived, Derived> Eigen::DenseBase< Derived >::select (const typename DenseBase< ElseDerived >::Scalar & thenScalar, const DenseBase< ElseDerived > & elseMatrix) const inline
Version of DenseBase::select(const DenseBase&, const DenseBase&) with the then expression being a scalar value.
See also
DenseBase::booleanSelect(const DenseBase<ThenDerived>&, const DenseBase<ElseDerived>&) const, class Select
{
   using ThenConstantType = typename DenseBase<ElseDerived>::ConstantReturnType;
   using Op = internal::scalar_boolean_select_op<typename DenseBase<ElseDerived>::Scalar,
                                                 typename DenseBase<ElseDerived>::Scalar, Scalar>;
   return CwiseTernaryOp<Op, ThenConstantType, ElseDerived, Derived>(ThenConstantType(rows(), cols(), thenScalar),
                                                                     elseMatrix.derived(), derived(), Op());
 }
References cols, and rows.
setConstant()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::setConstant (const Scalar & val)
Sets all coefficients in this expression to value val.
See also
fill(), setConstant(Index,const Scalar&), setConstant(Index,Index,const Scalar&), setZero(), setOnes(), Constant(), class CwiseNullaryOp, setZero(), setOnes()
{
   internal::eigen_fill_impl<Derived>::run(derived(), val);
   return derived();
 }
References run(), and calibrate::val.
Referenced by Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::collapseDuplicates(), and Eigen::ArrayBase< Derived >::operator=().
setEqualSpaced() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::setEqualSpaced (const Scalar & low, const Scalar & step)
{
   EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
   return setEqualSpaced(size(), low, step);
 }
References EIGEN_STATIC_ASSERT_VECTOR_ONLY, and size.
setEqualSpaced() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::setEqualSpaced (Index size, const Scalar & low, const Scalar & step)
{
   EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
   return derived() = Derived::NullaryExpr(newSize, internal::equalspaced_op<Scalar>(low, step));
 }
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
setLinSpaced() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::setLinSpaced (const Scalar & low, const Scalar & high)
Sets a linearly spaced vector.
The function fills *this with equally spaced values in the closed interval [low,high]. When size is set to 1, a vector of length 1 containing 'high' is returned.
\only_for_vectors
For integer scalar types, do not miss the explanations on the definition of even spacing .
See also
LinSpaced(Index,const Scalar&,const Scalar&), setLinSpaced(Index, const Scalar&, const Scalar&), CwiseNullaryOp
{
   EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
   return setLinSpaced(size(), low, high);
 }
References EIGEN_STATIC_ASSERT_VECTOR_ONLY, setLinSpaced(), and size.
setLinSpaced() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::setLinSpaced (Index newSize, const Scalar & low, const Scalar & high)
Sets a linearly spaced vector.
The function generates 'size' equally spaced values in the closed interval [low,high]. When size is set to 1, a vector of length 1 containing 'high' is returned.
\only_for_vectors
Example:
VectorXf v;
v.setLinSpaced(5, 0.5f, 1.5f);
cout << v << endl;
Output:
For integer scalar types, do not miss the explanations on the definition of even spacing .
See also
LinSpaced(Index,const Scalar&,const Scalar&), CwiseNullaryOp
{
   EIGEN_STATIC_ASSERT_VECTOR_ONLY(Derived)
   return derived() = Derived::NullaryExpr(newSize, internal::linspaced_op<Scalar>(low, high, newSize));
 }
References EIGEN_STATIC_ASSERT_VECTOR_ONLY.
setOnes()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::setOnes
Sets all coefficients in this expression to one.
Example:
Matrix4i m = Matrix4i::Random();
m.row(1).setOnes();
cout << m << endl;
Output:
See also
class CwiseNullaryOp, Ones()
{
   return setConstant(Scalar(1));
 }
References setConstant().
setRandom()
template<typename Derived > EIGEN_DEVICE_FUNC Derived & Eigen::DenseBase< Derived >::setRandom inline
Sets all coefficients in this expression to random values.
Numbers are uniformly spread through their whole definition range for integer types, and in the [-1:1] range for floating point scalar types.
\not_reentrant
Example:
Matrix4i m = Matrix4i::Zero();
m.col(1).setRandom();
cout << m << endl;
Output:
See also
class CwiseNullaryOp, setRandom(Index), setRandom(Index,Index)
{
   return *this = Random(rows(), cols());
 }
References cols, and rows.
setZero()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Derived & Eigen::DenseBase< Derived >::setZero
Sets all coefficients in this expression to zero.
Example:
Matrix4i m = Matrix4i::Random();
m.row(1).setZero();
cout << m << endl;
Output:
See also
class CwiseNullaryOp, Zero()
{
   internal::eigen_zero_impl<Derived>::run(derived());
   return derived();
 }
References run().
Referenced by Eigen::SPQR< MatrixType_ >::_solve_impl(), Eigen::PermutationBase< Derived >::evalTo(), and Eigen::InverseImpl< PermutationType, PermutationStorage >::evalTo().
sum()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::traits< Derived >::Scalar Eigen::DenseBase< Derived >::sum
Returns
the sum of all coefficients of *this
If *this is empty, then the value 0 is returned.
See also
trace(), prod(), mean()
{
   if (SizeAtCompileTime == 0 || (SizeAtCompileTime == Dynamic && size() == 0)) return Scalar(0);
   return derived().redux(Eigen::internal::scalar_sum_op<Scalar, Scalar>());
 }
References Eigen::Dynamic, and size.
swap() [1/2]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::DenseBase< Derived >::swap (const DenseBase< OtherDerived > & other) inline
swaps *this with the expression other.
{
     EIGEN_STATIC_ASSERT(!OtherDerived::IsPlainObjectBase, THIS_EXPRESSION_IS_NOT_A_LVALUE__IT_IS_READ_ONLY);
     eigen_assert(rows() == other.rows() && cols() == other.cols());
     call_assignment(derived(), other.const_cast_derived(), internal::swap_assign_op<Scalar>());
   }
References Eigen::internal::call_assignment(), cols, eigen_assert, EIGEN_STATIC_ASSERT, and rows.
Referenced by Eigen::internal::conservative_resize_like_impl< Derived, OtherDerived, IsVector >::run().
swap() [2/2]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::DenseBase< Derived >::swap (PlainObjectBase< OtherDerived > & other) inline
swaps *this with the matrix or array other.
{
     eigen_assert(rows() == other.rows() && cols() == other.cols());
     call_assignment(derived(), other.derived(), internal::swap_assign_op<Scalar>());
   }
References Eigen::internal::call_assignment(), cols, Eigen::PlainObjectBase< Derived >::cols(), eigen_assert, rows, and Eigen::PlainObjectBase< Derived >::rows().
trace()
template<typename Derived > EIGEN_DEVICE_FUNC Scalar Eigen::DenseBase< Derived >::trace () const
transpose() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DenseBase< Derived >::TransposeReturnType Eigen::DenseBase< Derived >::transpose
Returns
an expression of the transpose of *this.
Example:
Matrix2i m = Matrix2i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is the transpose of m:" << endl << m.transpose() << endl;
cout << "Here is the coefficient (1,0) in the transpose of m:" << endl << m.transpose()(1, 0) << endl;
cout << "Let us overwrite this coefficient with the value 0." << endl;
m.transpose()(1, 0) = 0;
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Warning
If you want to replace a matrix by its own transpose, do NOT do this:
m = m.transpose(); // bug!!! caused by aliasing effect
Instead, use the transposeInPlace() method:
m.transposeInPlace();
which gives Eigen good opportunities for optimization, or alternatively you can also do:
m = m.transpose().eval();
See also
transposeInPlace(), adjoint()
{
   return TransposeReturnType(derived());
 }
transpose() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ConstTransposeReturnType Eigen::DenseBase< Derived >::transpose
This is the const version of transpose().
Make sure you read the warning for transpose() !
See also
transposeInPlace(), adjoint()
{
   return ConstTransposeReturnType(derived());
 }
transposeInPlace()
template<typename Derived > EIGEN_DEVICE_FUNC void Eigen::DenseBase< Derived >::transposeInPlace inline
This is the "in place" version of transpose(): it replaces *this by its own transpose. Thus, doing
m.transposeInPlace();
has the same effect on m as doing
m = m.transpose().eval();
and is faster and also safer because in the latter line of code, forgetting the eval() results in a bug caused by aliasing.
Notice however that this method is only useful if you want to replace a matrix by its own transpose. If you just need the transpose of a matrix, use transpose().
Note
if the matrix is not square, then *this must be a resizable matrix. This excludes (non-square) fixed-size matrices, block-expressions and maps.
See also
transpose(), adjoint(), adjointInPlace()
{
   eigen_assert((rows() == cols() || (RowsAtCompileTime == Dynamic && ColsAtCompileTime == Dynamic)) &&
                "transposeInPlace() called on a non-square non-resizable matrix");
   internal::inplace_transpose_selector<Derived>::run(derived());
 }
References cols, Eigen::Dynamic, eigen_assert, rows, and run().
value()
template<typename Derived > EIGEN_DEVICE_FUNC CoeffReturnType Eigen::DenseBase< Derived >::value () const inline
Returns
the unique coefficient of a 1x1 expression
{
     EIGEN_STATIC_ASSERT_SIZE_1x1(Derived) eigen_assert(this->rows() == 1 && this->cols() == 1);
     return derived().coeff(0, 0);
   }
References cols, eigen_assert, EIGEN_STATIC_ASSERT_SIZE_1x1, and rows.
Referenced by Eigen::ArrayBase< Derived >::operator=().
visit()
template<typename Derived > template<typename Visitor > EIGEN_DEVICE_FUNC void Eigen::DenseBase< Derived >::visit (Visitor & visitor) const
Applies the visitor visitor to the whole coefficients of the matrix or vector.
The template parameter Visitor is the type of the visitor and provides the following interface:
struct MyVisitor {
  // called for the first coefficient
  void init(const Scalar& value, Index i, Index j);
  // called for all other coefficients
  void operator() (const Scalar& value, Index i, Index j);
};
Note
compared to one or two for loops, visitors offer automatic unrolling for small fixed size matrix.
if the matrix is empty, then the visitor is left unchanged.
See also
minCoeff(Index*,Index*), maxCoeff(Index*,Index*), DenseBase::redux()
{
   using impl = internal::visit_impl<Derived, Visitor, /*ShortCircuitEvaulation*/ false>;
   impl::run(derived(), visitor);
 }
References run().
Zero() [1/3]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ZeroReturnType Eigen::DenseBase< Derived >::Zero static
Returns
an expression of a fixed-size zero matrix or vector.
This variant is only for fixed-size MatrixBase types. For dynamic-size types, you need to use the variants taking size arguments.
Example:
cout << Matrix2d::Zero() << endl;
cout << RowVector4i::Zero() << endl;
Output:
See also
Zero(Index), Zero(Index,Index)
{
   return ZeroReturnType(RowsAtCompileTime, ColsAtCompileTime);
 }
Zero() [2/3]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ZeroReturnType Eigen::DenseBase< Derived >::Zero (Index rows, Index cols) static
Returns
an expression of a zero matrix.
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Zero() should be used instead.
Example:
cout << MatrixXi::Zero(2, 3) << endl;
Output:
See also
Zero(), Zero(Index)
{
   return ZeroReturnType(rows, cols);
 }
References cols, and rows.
Zero() [3/3]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const DenseBase< Derived >::ZeroReturnType Eigen::DenseBase< Derived >::Zero (Index size) static
Returns
an expression of a zero vector.
The parameter size is the size of the returned vector. Must be compatible with this MatrixBase type.
\only_for_vectors
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Zero() should be used instead.
Example:
cout << RowVectorXi::Zero(4) << endl;
cout << VectorXf::Zero(2) << endl;
Output:
See also
Zero(), Zero(Index,Index)
                 {
   return ZeroReturnType(size);
 }
References size.
Friends And Related Function Documentation
operator<<()
template<typename Derived > std::ostream & operator<< (std::ostream & s, const DenseBase< Derived > & m) related
Outputs the matrix, to the given stream.
If you wish to print the matrix with a format different than the default, use DenseBase::format().
It is also possible to change the default format by defining EIGEN_DEFAULT_IO_FORMAT before including Eigen headers. If not defined, this will automatically be defined to Eigen::IOFormat(), that is the Eigen::IOFormat with default parameters.
See also
DenseBase::format()
{
   return internal::print_matrix(s, m.eval(), EIGEN_DEFAULT_IO_FORMAT);
 }
References EIGEN_DEFAULT_IO_FORMAT, m, Eigen::internal::print_matrix(), and s.
Member Data Documentation
SequentialLinSpacedReturnType
template<typename Derived > EIGEN_DEPRECATED typedef CwiseNullaryOp<internal::linspaced_op<Scalar>, PlainObject> Eigen::DenseBase< Derived >::SequentialLinSpacedReturnType
Deprecated:
Represents a vector with linearly spaced coefficients that allows sequential access only.
The documentation for this class was generated from the following files:
DenseBase.h
Assign.h
CommaInitializer.h
CwiseNullaryOp.h
EigenBase.h
Fuzzy.h
IO.h
NestByValue.h
Random.h
Redux.h
Replicate.h
ReturnByValue.h
Reverse.h
Select.h
SelfCwiseBinaryOp.h
StlIterators.h
Transpose.h
VectorwiseOp.h
Visitor.h