MercuryDPM: UndeformedWall Class Reference
UndeformedWall Class Reference
#include <fsi_chan_problem.h>
Public Member Functions
UndeformedWall (const double &x0, const double &h)
void position (const Vector< double > &zeta, Vector< double > &r) const
Position vector at Lagrangian coordinate zeta.
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
UndeformedWall (const double &x0, const double &h)
void position (const Vector< double > &zeta, Vector< double > &r) const
Position vector at Lagrangian coordinate zeta.
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
UndeformedWall (const double &x0, const double &h)
void position (const Vector< double > &zeta, Vector< double > &r) const
Position vector at Lagrangian coordinate zeta.
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
UndeformedWall (const double &x0, const double &h)
void position (const Vector< double > &zeta, Vector< double > &r) const
Position vector at Lagrangian coordinate zeta.
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
UndeformedWall (const double &x0, const double &h)
void position (const Vector< double > &zeta, Vector< double > &r) const
Position vector at Lagrangian coordinate zeta.
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
UndeformedWall (const double &x0, const double &h)
void position (const Vector< double > &zeta, Vector< double > &r) const
Position vector at Lagrangian coordinate zeta.
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
UndeformedWall (const double &x0, const double &h)
void position (const Vector< double > &zeta, Vector< double > &r) const
Position vector at Lagrangian coordinate zeta.
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
UndeformedWall (const double &x0, const double &h)
void position (const Vector< double > &zeta, Vector< double > &r) const
Position vector at Lagrangian coordinate zeta.
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual unsigned ngeom_data () const
virtual Data * geom_data_pt (const unsigned &j)
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition_dt (const Vector< double > &zeta, const unsigned &j, Vector< double > &drdt)
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void locate_zeta (const Vector< double > &zeta, GeomObject *&sub_geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
Private Attributes
double X0
x position of the undeformed beam's left end.
double H
Height of the undeformed wall above y=0.
Additional Inherited Members
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Detailed Description
/////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////// Undeformed wall is a steady, straight 1D line in 2D space
\[ x = X_0 + \zeta \]
\[ y = H \]
Constructor & Destructor Documentation
UndeformedWall() [1/8]
UndeformedWall::UndeformedWall (const double & x0, const double & h) inline
Constructor: arguments are the starting point and the height above y=0.
                                                   : GeomObject(1,2)
   {
    X0=x0;
    H=h;
   }
References H, Global::x0, and X0.
UndeformedWall() [2/8]
UndeformedWall::UndeformedWall (const double & x0, const double & h) inline
Constructor: arguments are the starting point and the height above y=0.
                                                   : GeomObject(1,2)
   {
    X0=x0;
    H=h;
   }
References H, and Global::x0.
UndeformedWall() [3/8]
UndeformedWall::UndeformedWall (const double & x0, const double & h) inline
Constructor: arguments are the starting point and the height above y=0.
                                                   : GeomObject(1,2)
   {
    X0=x0;
    H=h;
   }
References H, and Global::x0.
UndeformedWall() [4/8]
UndeformedWall::UndeformedWall (const double & x0, const double & h) inline
Constructor: arguments are the starting point and the height above y=0.
                                                   : GeomObject(1,2)
   {
    X0=x0;
    H=h;
   }
References H, and Global::x0.
UndeformedWall() [5/8]
UndeformedWall::UndeformedWall (const double & x0, const double & h) inline
Constructor: arguments are the starting point and the height above y=0.
                                                   : GeomObject(1,2)
   {
    X0=x0;
    H=h;
   }
References H, and Global::x0.
UndeformedWall() [6/8]
UndeformedWall::UndeformedWall (const double & x0, const double & h) inline
Constructor: arguments are the starting point and the height above y=0.
                                                   : GeomObject(1,2)
   {
    X0=x0;
    H=h;
   }
References H, and Global::x0.
UndeformedWall() [7/8]
UndeformedWall::UndeformedWall (const double & x0, const double & h) inline
Constructor: arguments are the starting point and the height above y=0.
                                                   : GeomObject(1,2)
   {
    X0=x0;
    H=h;
   }
References H, and Global::x0.
UndeformedWall() [8/8]
UndeformedWall::UndeformedWall (const double & x0, const double & h) inline
Constructor: arguments are the starting point and the height above y=0.
                                                   : GeomObject(1,2)
   {
    X0=x0;
    H=h;
   }
References H, and Global::x0.
Member Function Documentation
d2position() [1/8]
virtual void UndeformedWall::d2position (const Vector< double > & zeta, Vector< double > & r, DenseMatrix< double > & drdzeta, RankThreeTensor< double > & ddrdzeta) const inline virtual
Posn vector and its 1st & 2nd derivatives w.r.t. to coordinates: \(\frac{dR_i}{d \zeta_\alpha}\) = drdzeta(alpha,i). \(\frac{d^2R_i}{d \zeta_\alpha d \zeta_\beta}\) = ddrdzeta(alpha,beta,i). Evaluated at current time.
   {
    // Position vector
    r[0] = zeta[0]+X0;
    r[1] = H;
    // Tangent vector
    drdzeta(0,0)=1.0;
    drdzeta(0,1)=0.0;
    // Derivative of tangent vector
    ddrdzeta(0,0,0)=0.0;
    ddrdzeta(0,0,1)=0.0;
   } // end of d2position
References H, UniformPSDSelfTest::r, X0, and Eigen::zeta().
d2position() [2/8]
void UndeformedWall::d2position (const Vector< double > & zeta, Vector< double > & r, DenseMatrix< double > & drdzeta, RankThreeTensor< double > & ddrdzeta) const inline virtual
Posn vector and its 1st & 2nd derivatives w.r.t. to coordinates: \(\frac{dR_i}{d \zeta_\alpha}\) = drdzeta(alpha,i). \(\frac{d^2R_i}{d \zeta_\alpha d \zeta_\beta}\) = ddrdzeta(alpha,beta,i). Evaluated at current time.
Reimplemented from oomph::GeomObject.
   {
    // Position vector
    r[0] = zeta[0]+X0;
    r[1] = H;
    // Tangent vector
    drdzeta(0,0)=1.0;
    drdzeta(0,1)=0.0;
    // Derivative of tangent vector
    ddrdzeta(0,0,0)=0.0;
    ddrdzeta(0,0,1)=0.0;
   } // end of d2position
References H, UniformPSDSelfTest::r, and Eigen::zeta().
d2position() [3/8]
virtual void UndeformedWall::d2position (const Vector< double > & zeta, Vector< double > & r, DenseMatrix< double > & drdzeta, RankThreeTensor< double > & ddrdzeta) const inline virtual
Posn vector and its 1st & 2nd derivatives w.r.t. to coordinates: \(\frac{dR_i}{d \zeta_\alpha}\) = drdzeta(alpha,i). \(\frac{d^2R_i}{d \zeta_\alpha d \zeta_\beta}\) = ddrdzeta(alpha,beta,i). Evaluated at current time.
Reimplemented from oomph::GeomObject.
   {
    // Position vector
    r[0] = zeta[0]+X0;
    r[1] = H;
    // Tangent vector
    drdzeta(0,0)=1.0;
    drdzeta(0,1)=0.0;
    // Derivative of tangent vector
    ddrdzeta(0,0,0)=0.0;
    ddrdzeta(0,0,1)=0.0;
   } // end of d2position
References H, UniformPSDSelfTest::r, and Eigen::zeta().
d2position() [4/8]
virtual void UndeformedWall::d2position (const Vector< double > & zeta, Vector< double > & r, DenseMatrix< double > & drdzeta, RankThreeTensor< double > & ddrdzeta) const inline virtual
Posn vector and its 1st & 2nd derivatives w.r.t. to coordinates: \(\frac{dR_i}{d \zeta_\alpha}\) = drdzeta(alpha,i). \(\frac{d^2R_i}{d \zeta_\alpha d \zeta_\beta}\) = ddrdzeta(alpha,beta,i). Evaluated at current time.
Reimplemented from oomph::GeomObject.
   {
    // Position vector
    r[0] = zeta[0]+X0;
    r[1] = H;
    // Tangent vector
    drdzeta(0,0)=1.0;
    drdzeta(0,1)=0.0;
    // Derivative of tangent vector
    ddrdzeta(0,0,0)=0.0;
    ddrdzeta(0,0,1)=0.0;
   } // end of d2position
References H, UniformPSDSelfTest::r, and Eigen::zeta().
d2position() [5/8]
virtual void UndeformedWall::d2position (const Vector< double > & zeta, Vector< double > & r, DenseMatrix< double > & drdzeta, RankThreeTensor< double > & ddrdzeta) const inline virtual
Posn vector and its 1st & 2nd derivatives w.r.t. to coordinates: \(\frac{dR_i}{d \zeta_\alpha}\) = drdzeta(alpha,i). \(\frac{d^2R_i}{d \zeta_\alpha d \zeta_\beta}\) = ddrdzeta(alpha,beta,i). Evaluated at current time.
Reimplemented from oomph::GeomObject.
   {
    // Position vector
    r[0] = zeta[0]+X0;
    r[1] = H;
    // Tangent vector
    drdzeta(0,0)=1.0;
    drdzeta(0,1)=0.0;
    // Derivative of tangent vector
    ddrdzeta(0,0,0)=0.0;
    ddrdzeta(0,0,1)=0.0;
   } // end of d2position
References H, UniformPSDSelfTest::r, and Eigen::zeta().
d2position() [6/8]
void UndeformedWall::d2position (const Vector< double > & zeta, Vector< double > & r, DenseMatrix< double > & drdzeta, RankThreeTensor< double > & ddrdzeta) const inline virtual
Posn vector and its 1st & 2nd derivatives w.r.t. to coordinates: \(\frac{dR_i}{d \zeta_\alpha}\) = drdzeta(alpha,i). \(\frac{d^2R_i}{d \zeta_\alpha d \zeta_\beta}\) = ddrdzeta(alpha,beta,i). Evaluated at current time.
Reimplemented from oomph::GeomObject.
   {
    // Position vector
    r[0] = zeta[0]+X0;
    r[1] = H;
    // Tangent vector
    drdzeta(0,0)=1.0;
    drdzeta(0,1)=0.0;
    // Derivative of tangent vector
    ddrdzeta(0,0,0)=0.0;
    ddrdzeta(0,0,1)=0.0;
   } // end of d2position
References H, UniformPSDSelfTest::r, and Eigen::zeta().
d2position() [7/8]
virtual void UndeformedWall::d2position (const Vector< double > & zeta, Vector< double > & r, DenseMatrix< double > & drdzeta, RankThreeTensor< double > & ddrdzeta) const inline virtual
Posn vector and its 1st & 2nd derivatives w.r.t. to coordinates: \(\frac{dR_i}{d \zeta_\alpha}\) = drdzeta(alpha,i). \(\frac{d^2R_i}{d \zeta_\alpha d \zeta_\beta}\) = ddrdzeta(alpha,beta,i). Evaluated at current time.
Reimplemented from oomph::GeomObject.
   {
    // Position vector
    r[0] = zeta[0]+X0;
    r[1] = H;
    // Tangent vector
    drdzeta(0,0)=1.0;
    drdzeta(0,1)=0.0;
    // Derivative of tangent vector
    ddrdzeta(0,0,0)=0.0;
    ddrdzeta(0,0,1)=0.0;
   } // end of d2position
References H, UniformPSDSelfTest::r, and Eigen::zeta().
d2position() [8/8]
void UndeformedWall::d2position (const Vector< double > & zeta, Vector< double > & r, DenseMatrix< double > & drdzeta, RankThreeTensor< double > & ddrdzeta) const inline virtual
Posn vector and its 1st & 2nd derivatives w.r.t. to coordinates: \(\frac{dR_i}{d \zeta_\alpha}\) = drdzeta(alpha,i). \(\frac{d^2R_i}{d \zeta_\alpha d \zeta_\beta}\) = ddrdzeta(alpha,beta,i). Evaluated at current time.
Reimplemented from oomph::GeomObject.
   {
    // Position vector
    r[0] = zeta[0]+X0;
    r[1] = H;
    // Tangent vector
    drdzeta(0,0)=1.0;
    drdzeta(0,1)=0.0;
    // Derivative of tangent vector
    ddrdzeta(0,0,0)=0.0;
    ddrdzeta(0,0,1)=0.0;
   } // end of d2position
References H, UniformPSDSelfTest::r, and Eigen::zeta().
position() [1/16]
void UndeformedWall::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const inline virtual
Parametrised position on object: r(zeta). Evaluated at previous timestep. t=0: current time; t>0: previous timestep. Calls steady version.
Reimplemented from oomph::GeomObject.
   {
    // Use the steady version
    position(zeta,r);
   } // end of position
References position(), UniformPSDSelfTest::r, and Eigen::zeta().
position() [2/16]
void UndeformedWall::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const inline virtual
Parametrised position on object: r(zeta). Evaluated at previous timestep. t=0: current time; t>0: previous timestep. Calls steady version.
Reimplemented from oomph::GeomObject.
   {
    // Use the steady version
    position(zeta,r);
   } // end of position
References UniformPSDSelfTest::r, and Eigen::zeta().
position() [3/16]
void UndeformedWall::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const inline virtual
Parametrised position on object: r(zeta). Evaluated at previous timestep. t=0: current time; t>0: previous timestep. Calls steady version.
Reimplemented from oomph::GeomObject.
   {
    // Use the steady version
    position(zeta,r);
   } // end of position
References UniformPSDSelfTest::r, and Eigen::zeta().
position() [4/16]
void UndeformedWall::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const inline virtual
Parametrised position on object: r(zeta). Evaluated at previous timestep. t=0: current time; t>0: previous timestep. Calls steady version.
Reimplemented from oomph::GeomObject.
   {
    // Use the steady version
    position(zeta,r);
   } // end of position
References UniformPSDSelfTest::r, and Eigen::zeta().
position() [5/16]
void UndeformedWall::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const inline virtual
Parametrised position on object: r(zeta). Evaluated at previous timestep. t=0: current time; t>0: previous timestep. Calls steady version.
Reimplemented from oomph::GeomObject.
   {
    // Use the steady version
    position(zeta,r);
   } // end of position
References UniformPSDSelfTest::r, and Eigen::zeta().
position() [6/16]
void UndeformedWall::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const inline virtual
Parametrised position on object: r(zeta). Evaluated at previous timestep. t=0: current time; t>0: previous timestep. Calls steady version.
Reimplemented from oomph::GeomObject.
   {
    // Use the steady version
    position(zeta,r);
   } // end of position
References UniformPSDSelfTest::r, and Eigen::zeta().
position() [7/16]
void UndeformedWall::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const inline virtual
Parametrised position on object: r(zeta). Evaluated at previous timestep. t=0: current time; t>0: previous timestep. Calls steady version.
Reimplemented from oomph::GeomObject.
   {
    // Use the steady version
    position(zeta,r);
   } // end of position
References UniformPSDSelfTest::r, and Eigen::zeta().
position() [8/16]
void UndeformedWall::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const inline virtual
Parametrised position on object: r(zeta). Evaluated at previous timestep. t=0: current time; t>0: previous timestep. Calls steady version.
Reimplemented from oomph::GeomObject.
   {
    // Use the steady version
    position(zeta,r);
   } // end of position
References UniformPSDSelfTest::r, and Eigen::zeta().
position() [9/16]
void UndeformedWall::position (const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position vector at Lagrangian coordinate zeta.
Implements oomph::GeomObject.
   {
    // Position Vector
    r[0] = zeta[0]+X0;
    r[1] = H;
   }
References H, UniformPSDSelfTest::r, X0, and Eigen::zeta().
Referenced by position().
position() [10/16]
void UndeformedWall::position (const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position vector at Lagrangian coordinate zeta.
Implements oomph::GeomObject.
   {
    // Position Vector
    r[0] = zeta[0]+X0;
    r[1] = H;
   }
References H, UniformPSDSelfTest::r, and Eigen::zeta().
position() [11/16]
void UndeformedWall::position (const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position vector at Lagrangian coordinate zeta.
Implements oomph::GeomObject.
   {
    // Position Vector
    r[0] = zeta[0]+X0;
    r[1] = H;
   }
References H, UniformPSDSelfTest::r, and Eigen::zeta().
position() [12/16]
void UndeformedWall::position (const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position vector at Lagrangian coordinate zeta.
Implements oomph::GeomObject.
   {
    // Position Vector
    r[0] = zeta[0]+X0;
    r[1] = H;
   }
References H, UniformPSDSelfTest::r, and Eigen::zeta().
position() [13/16]
void UndeformedWall::position (const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position vector at Lagrangian coordinate zeta.
Implements oomph::GeomObject.
   {
    // Position Vector
    r[0] = zeta[0]+X0;
    r[1] = H;
   }
References H, UniformPSDSelfTest::r, and Eigen::zeta().
position() [14/16]
void UndeformedWall::position (const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position vector at Lagrangian coordinate zeta.
Implements oomph::GeomObject.
   {
    // Position Vector
    r[0] = zeta[0]+X0;
    r[1] = H;
   }
References H, UniformPSDSelfTest::r, and Eigen::zeta().
position() [15/16]
void UndeformedWall::position (const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position vector at Lagrangian coordinate zeta.
Implements oomph::GeomObject.
   {
    // Position Vector
    r[0] = zeta[0]+X0;
    r[1] = H;
   }
References H, UniformPSDSelfTest::r, and Eigen::zeta().
position() [16/16]
void UndeformedWall::position (const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position vector at Lagrangian coordinate zeta.
Implements oomph::GeomObject.
   {
    // Position Vector
    r[0] = zeta[0]+X0;
    r[1] = H;
   }
References H, UniformPSDSelfTest::r, and Eigen::zeta().
Member Data Documentation
H
double UndeformedWall::H private
Height of the undeformed wall above y=0.
Referenced by d2position(), position(), and UndeformedWall().
X0
double UndeformedWall::X0 private
x position of the undeformed beam's left end.
Referenced by d2position(), position(), and UndeformedWall().
The documentation for this class was generated from the following files:
fsi_chan_problem.h
fsi_collapsible_channel.cc
interaction/fsi_collapsible_channel/fsi_collapsible_channel_adapt.cc
fsi_pseudo_solid_collapsible_channel.cc
fsi_pseudo_solid_collapsible_channel_adapt.cc
fsi_driven_cavity_problem.h
fsi_jacobian_approximation.cc