MercuryDPM: oomph::QElement1FaceToBulkCoordinates Namespace Reference
oomph::QElement1FaceToBulkCoordinates Namespace Reference
Functions
void face0 (const Vector< double > &s, Vector< double > &s_bulk)
The translation scheme for the face s0 = -1.0.
void face1 (const Vector< double > &s, Vector< double > &s_bulk)
The translation scheme for the face s0 = 1.0.
Detailed Description
Namespace for helper functions that return the local coordinates in the bulk elements
Function Documentation
face0()
void oomph::QElement1FaceToBulkCoordinates::face0 (const Vector< double > & s, Vector< double > & s_bulk)
The translation scheme for the face s0 = -1.0.
     {
       s_bulk[0] = -1.0;
     }
Referenced by oomph::QHermiteElement< DIM >::build_face_element(), oomph::QSpectralElement< 1, NNODE_1D >::build_face_element(), oomph::BrickFromTetMesh< ELEMENT >::build_mesh(), oomph::QElement< 1, NNODE_1D >::face_to_bulk_coordinate_fct_pt(), Membrane::initializeEdgeBendingQuantities(), TriangulatedWall::setNormalsAndNeighbours(), and Membrane::updateFaceNeighbors().
face1()
void oomph::QElement1FaceToBulkCoordinates::face1 (const Vector< double > & s, Vector< double > & s_bulk)
The translation scheme for the face s0 = 1.0.
     {
       s_bulk[0] = 1.0;
     }
Referenced by oomph::QHermiteElement< DIM >::build_face_element(), oomph::QSpectralElement< 1, NNODE_1D >::build_face_element(), oomph::BrickFromTetMesh< ELEMENT >::build_mesh(), oomph::QElement< 1, NNODE_1D >::face_to_bulk_coordinate_fct_pt(), TriangulatedWall::setNormalsAndNeighbours(), and Membrane::updateFaceNeighbors().