MercuryDPM: Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ > Class Template Reference
Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ > Class Template Reference
#include <GeneralBlockPanelKernel.h>
Public Types
enum {
ConjLhs = ConjLhs_ , ConjRhs = ConjRhs_ , Vectorizable = unpacket_traits<RealPacket>::vectorizable && unpacket_traits<ScalarPacket>::vectorizable , ResPacketSize = Vectorizable ? unpacket_traits<ResPacket_>::size : 1 ,
LhsPacketSize = Vectorizable ? unpacket_traits<LhsPacket_>::size : 1 , RhsPacketSize = Vectorizable ? unpacket_traits<RhsScalar>::size : 1 , RealPacketSize = Vectorizable ? unpacket_traits<RealPacket>::size : 1 , NumberOfRegisters = EIGEN_ARCH_DEFAULT_NUMBER_OF_REGISTERS ,
nr = 4 , mr = (plain_enum_min(16, NumberOfRegisters) / 2 / nr) * ResPacketSize , LhsProgress = ResPacketSize , RhsProgress = 1
}
typedef std::complex< RealScalar > Scalar
typedef std::complex< RealScalar > LhsScalar
typedef std::complex< RealScalar > RhsScalar
typedef std::complex< RealScalar > ResScalar
typedef DoublePacket< RealPacket > DoublePacketType
typedef std::conditional_t< Vectorizable, ScalarPacket, Scalar > LhsPacket4Packing
typedef std::conditional_t< Vectorizable, RealPacket, Scalar > LhsPacket
typedef std::conditional_t< Vectorizable, DoublePacketType, Scalar > RhsPacket
typedef std::conditional_t< Vectorizable, ScalarPacket, Scalar > ResPacket
typedef std::conditional_t< Vectorizable, DoublePacketType, Scalar > AccPacket
typedef QuadPacket< RhsPacket > RhsPacketx4
Public Member Functions
PACKET_DECL_COND_POSTFIX (_, Lhs, PacketSize_)
PACKET_DECL_COND_POSTFIX (_, Rhs, PacketSize_)
PACKET_DECL_COND_POSTFIX (_, Res, PacketSize_)
PACKET_DECL_COND (Real, PacketSize_)
PACKET_DECL_COND_SCALAR (PacketSize_)
EIGEN_STRONG_INLINE void initAcc (Scalar &p)
EIGEN_STRONG_INLINE void initAcc (DoublePacketType &p)
EIGEN_STRONG_INLINE void loadRhs (const RhsScalar *b, ScalarPacket &dest) const
template<typename RealPacketType >
EIGEN_STRONG_INLINE void loadRhs (const RhsScalar *b, DoublePacket< RealPacketType > &dest) const
EIGEN_STRONG_INLINE void loadRhs (const RhsScalar *b, RhsPacketx4 &dest) const
EIGEN_STRONG_INLINE void updateRhs (const RhsScalar *b, ScalarPacket &dest) const
template<typename RealPacketType >
EIGEN_STRONG_INLINE void updateRhs (const RhsScalar *b, DoublePacket< RealPacketType > &dest) const
EIGEN_STRONG_INLINE void updateRhs (const RhsScalar *, RhsPacketx4 &) const
EIGEN_STRONG_INLINE void loadRhsQuad (const RhsScalar *b, ResPacket &dest) const
EIGEN_STRONG_INLINE void loadRhsQuad (const RhsScalar *b, DoublePacketType &dest) const
EIGEN_STRONG_INLINE void loadLhs (const LhsScalar *a, LhsPacket &dest) const
template<typename LhsPacketType >
EIGEN_STRONG_INLINE void loadLhsUnaligned (const LhsScalar *a, LhsPacketType &dest) const
template<typename LhsPacketType , typename RhsPacketType , typename ResPacketType , typename TmpType , typename LaneIdType >
EIGEN_STRONG_INLINE std::enable_if_t<!is_same< RhsPacketType, RhsPacketx4 >::value > madd (const LhsPacketType &a, const RhsPacketType &b, DoublePacket< ResPacketType > &c, TmpType &, const LaneIdType &) const
template<typename LaneIdType >
EIGEN_STRONG_INLINE void madd (const LhsPacket &a, const RhsPacket &b, ResPacket &c, RhsPacket &, const LaneIdType &) const
template<typename LhsPacketType , typename AccPacketType , typename LaneIdType >
EIGEN_STRONG_INLINE void madd (const LhsPacketType &a, const RhsPacketx4 &b, AccPacketType &c, RhsPacket &tmp, const LaneIdType &lane) const
EIGEN_STRONG_INLINE void acc (const Scalar &c, const Scalar &alpha, Scalar &r) const
template<typename RealPacketType , typename ResPacketType >
EIGEN_STRONG_INLINE void acc (const DoublePacket< RealPacketType > &c, const ResPacketType &alpha, ResPacketType &r) const
Protected Attributes
conj_helper< LhsScalar, RhsScalar, ConjLhs, ConjRhs > cj
Member Typedef Documentation
AccPacket
template<typename RealScalar , bool ConjLhs_, bool ConjRhs_, int Arch, int PacketSize_> typedef std::conditional_t<Vectorizable, DoublePacketType, Scalar> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::AccPacket
DoublePacketType
template<typename RealScalar , bool ConjLhs_, bool ConjRhs_, int Arch, int PacketSize_> typedef DoublePacket<RealPacket> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::DoublePacketType
LhsPacket
template<typename RealScalar , bool ConjLhs_, bool ConjRhs_, int Arch, int PacketSize_> typedef std::conditional_t<Vectorizable, RealPacket, Scalar> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::LhsPacket
LhsPacket4Packing
template<typename RealScalar , bool ConjLhs_, bool ConjRhs_, int Arch, int PacketSize_> typedef std::conditional_t<Vectorizable, ScalarPacket, Scalar> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::LhsPacket4Packing
LhsScalar
template<typename RealScalar , bool ConjLhs_, bool ConjRhs_, int Arch, int PacketSize_> typedef std::complex<RealScalar> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::LhsScalar
ResPacket
template<typename RealScalar , bool ConjLhs_, bool ConjRhs_, int Arch, int PacketSize_> typedef std::conditional_t<Vectorizable, ScalarPacket, Scalar> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::ResPacket
ResScalar
template<typename RealScalar , bool ConjLhs_, bool ConjRhs_, int Arch, int PacketSize_> typedef std::complex<RealScalar> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::ResScalar
RhsPacket
template<typename RealScalar , bool ConjLhs_, bool ConjRhs_, int Arch, int PacketSize_> typedef std::conditional_t<Vectorizable, DoublePacketType, Scalar> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::RhsPacket
RhsPacketx4
template<typename RealScalar , bool ConjLhs_, bool ConjRhs_, int Arch, int PacketSize_> typedef QuadPacket<RhsPacket> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::RhsPacketx4
RhsScalar
template<typename RealScalar , bool ConjLhs_, bool ConjRhs_, int Arch, int PacketSize_> typedef std::complex<RealScalar> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::RhsScalar
Scalar
template<typename RealScalar , bool ConjLhs_, bool ConjRhs_, int Arch, int PacketSize_> typedef std::complex<RealScalar> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::Scalar
Member Enumeration Documentation
anonymous enum
template<typename RealScalar , bool ConjLhs_, bool ConjRhs_, int Arch, int PacketSize_> anonymous enum
Enumerator
ConjLhs
ConjRhs
Vectorizable
ResPacketSize
LhsPacketSize
RhsPacketSize
RealPacketSize
NumberOfRegisters
nr
mr
LhsProgress
RhsProgress
        {
     ConjLhs = ConjLhs_,
     ConjRhs = ConjRhs_,
     Vectorizable = unpacket_traits<RealPacket>::vectorizable && unpacket_traits<ScalarPacket>::vectorizable,
     ResPacketSize = Vectorizable ? unpacket_traits<ResPacket_>::size : 1,
     LhsPacketSize = Vectorizable ? unpacket_traits<LhsPacket_>::size : 1,
     RhsPacketSize = Vectorizable ? unpacket_traits<RhsScalar>::size : 1,
     RealPacketSize = Vectorizable ? unpacket_traits<RealPacket>::size : 1,
     NumberOfRegisters = EIGEN_ARCH_DEFAULT_NUMBER_OF_REGISTERS,
     nr = 4,
     mr = (plain_enum_min(16, NumberOfRegisters) / 2 / nr) * ResPacketSize,
     LhsProgress = ResPacketSize,
     RhsProgress = 1
   };
Member Function Documentation
acc() [1/2]
template<typename RealScalar , bool ConjLhs_, bool ConjRhs_, int Arch, int PacketSize_> template<typename RealPacketType , typename ResPacketType > EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::acc (const DoublePacket< RealPacketType > & c, const ResPacketType & alpha, ResPacketType & r) const inline
{
     // assemble c
     ResPacketType tmp;
     if ((!ConjLhs) && (!ConjRhs)) {
       tmp = pcplxflip(pconj(ResPacketType(c.second)));
       tmp = padd(ResPacketType(c.first), tmp);
     } else if ((!ConjLhs) && (ConjRhs)) {
       tmp = pconj(pcplxflip(ResPacketType(c.second)));
       tmp = padd(ResPacketType(c.first), tmp);
     } else if ((ConjLhs) && (!ConjRhs)) {
       tmp = pcplxflip(ResPacketType(c.second));
       tmp = padd(pconj(ResPacketType(c.first)), tmp);
     } else if ((ConjLhs) && (ConjRhs)) {
       tmp = pcplxflip(ResPacketType(c.second));
       tmp = psub(pconj(ResPacketType(c.first)), tmp);
     }
     r = pmadd(tmp, alpha, r);
   }
References alpha, calibrate::c, Eigen::internal::gebp_traits< LhsScalar_, RhsScalar_, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::ConjLhs, Eigen::internal::gebp_traits< LhsScalar_, RhsScalar_, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::ConjRhs, Eigen::internal::padd(), Eigen::internal::pconj(), Eigen::internal::pcplxflip(), Eigen::internal::pmadd(), Eigen::internal::psub(), UniformPSDSelfTest::r, and tmp.
acc() [2/2]
template<typename RealScalar , bool ConjLhs_, bool ConjRhs_, int Arch, int PacketSize_> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::acc (const Scalar & c, const Scalar & alpha, Scalar & r) const inline
 { r += alpha * c; }
References alpha, calibrate::c, and UniformPSDSelfTest::r.
initAcc() [1/2]
template<typename RealScalar , bool ConjLhs_, bool ConjRhs_, int Arch, int PacketSize_> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::initAcc (DoublePacketType & p) inline
{
     p.first = pset1<RealPacket>(RealScalar(0));
     p.second = pset1<RealPacket>(RealScalar(0));
   }
References p.
initAcc() [2/2]
template<typename RealScalar , bool ConjLhs_, bool ConjRhs_, int Arch, int PacketSize_> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::initAcc (Scalar & p) inline
 { p = Scalar(0); }
References p.
loadLhs()
template<typename RealScalar , bool ConjLhs_, bool ConjRhs_, int Arch, int PacketSize_> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::loadLhs (const LhsScalar * a, LhsPacket & dest) const inline
{
     dest = pload<LhsPacket>((const typename unpacket_traits<LhsPacket>::type*)(a));
   }
References a.
loadLhsUnaligned()
template<typename RealScalar , bool ConjLhs_, bool ConjRhs_, int Arch, int PacketSize_> template<typename LhsPacketType > EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::loadLhsUnaligned (const LhsScalar * a, LhsPacketType & dest) const inline
{
     dest = ploadu<LhsPacketType>((const typename unpacket_traits<LhsPacketType>::type*)(a));
   }
References a.
loadRhs() [1/3]
template<typename RealScalar , bool ConjLhs_, bool ConjRhs_, int Arch, int PacketSize_> template<typename RealPacketType > EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::loadRhs (const RhsScalar * b, DoublePacket< RealPacketType > & dest) const inline
{
     dest.first = pset1<RealPacketType>(numext::real(*b));
     dest.second = pset1<RealPacketType>(numext::imag(*b));
   }
References b, Eigen::internal::DoublePacket< Packet >::first, imag(), and Eigen::internal::DoublePacket< Packet >::second.
loadRhs() [2/3]
template<typename RealScalar , bool ConjLhs_, bool ConjRhs_, int Arch, int PacketSize_> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::loadRhs (const RhsScalar * b, RhsPacketx4 & dest) const inline
{
     loadRhs(b, dest.B_0);
     loadRhs(b + 1, dest.B1);
     loadRhs(b + 2, dest.B2);
     loadRhs(b + 3, dest.B3);
   }
References b, Eigen::internal::QuadPacket< Packet >::B1, Eigen::internal::QuadPacket< Packet >::B2, Eigen::internal::QuadPacket< Packet >::B3, Eigen::internal::QuadPacket< Packet >::B_0, and Eigen::internal::gebp_traits< LhsScalar_, RhsScalar_, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::loadRhs().
loadRhs() [3/3]
template<typename RealScalar , bool ConjLhs_, bool ConjRhs_, int Arch, int PacketSize_> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::loadRhs (const RhsScalar * b, ScalarPacket & dest) const inline
 { dest = pset1<ScalarPacket>(*b); }
References b.
loadRhsQuad() [1/2]
template<typename RealScalar , bool ConjLhs_, bool ConjRhs_, int Arch, int PacketSize_> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::loadRhsQuad (const RhsScalar * b, DoublePacketType & dest) const inline
{
     loadQuadToDoublePacket(b, dest);
   }
References b, and Eigen::internal::loadQuadToDoublePacket().
loadRhsQuad() [2/2]
template<typename RealScalar , bool ConjLhs_, bool ConjRhs_, int Arch, int PacketSize_> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::loadRhsQuad (const RhsScalar * b, ResPacket & dest) const inline
 { loadRhs(b, dest); }
References b, and Eigen::internal::gebp_traits< LhsScalar_, RhsScalar_, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::loadRhs().
madd() [1/3]
template<typename RealScalar , bool ConjLhs_, bool ConjRhs_, int Arch, int PacketSize_> template<typename LaneIdType > EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::madd (const LhsPacket & a, const RhsPacket & b, ResPacket & c, RhsPacket & , const LaneIdType &) const inline
{
     c = cj.pmadd(a, b, c);
   }
References a, b, and calibrate::c.
madd() [2/3]
template<typename RealScalar , bool ConjLhs_, bool ConjRhs_, int Arch, int PacketSize_> template<typename LhsPacketType , typename RhsPacketType , typename ResPacketType , typename TmpType , typename LaneIdType > EIGEN_STRONG_INLINE std::enable_if_t<!is_same<RhsPacketType, RhsPacketx4>::value> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::madd (const LhsPacketType & a, const RhsPacketType & b, DoublePacket< ResPacketType > & c, TmpType & , const LaneIdType &) const inline
{
     c.first = pmadd(a, b.first, c.first);
     c.second = pmadd(a, b.second, c.second);
   }
References a, b, calibrate::c, and Eigen::internal::pmadd().
madd() [3/3]
template<typename RealScalar , bool ConjLhs_, bool ConjRhs_, int Arch, int PacketSize_> template<typename LhsPacketType , typename AccPacketType , typename LaneIdType > EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::madd (const LhsPacketType & a, const RhsPacketx4 & b, AccPacketType & c, RhsPacket & tmp, const LaneIdType & lane) const inline
{
     madd(a, b.get(lane), c, tmp, lane);
   }
References a, b, calibrate::c, Eigen::internal::gebp_traits< LhsScalar_, RhsScalar_, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::madd(), and tmp.
PACKET_DECL_COND()
template<typename RealScalar , bool ConjLhs_, bool ConjRhs_, int Arch, int PacketSize_> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::PACKET_DECL_COND (Real , PacketSize_)
PACKET_DECL_COND_POSTFIX() [1/3]
template<typename RealScalar , bool ConjLhs_, bool ConjRhs_, int Arch, int PacketSize_> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::PACKET_DECL_COND_POSTFIX (_ , Lhs , PacketSize_)
PACKET_DECL_COND_POSTFIX() [2/3]
template<typename RealScalar , bool ConjLhs_, bool ConjRhs_, int Arch, int PacketSize_> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::PACKET_DECL_COND_POSTFIX (_ , Res , PacketSize_)
PACKET_DECL_COND_POSTFIX() [3/3]
template<typename RealScalar , bool ConjLhs_, bool ConjRhs_, int Arch, int PacketSize_> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::PACKET_DECL_COND_POSTFIX (_ , Rhs , PacketSize_)
PACKET_DECL_COND_SCALAR()
template<typename RealScalar , bool ConjLhs_, bool ConjRhs_, int Arch, int PacketSize_> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::PACKET_DECL_COND_SCALAR (PacketSize_)
updateRhs() [1/3]
template<typename RealScalar , bool ConjLhs_, bool ConjRhs_, int Arch, int PacketSize_> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::updateRhs (const RhsScalar * , RhsPacketx4 &) const inline
 {}
updateRhs() [2/3]
template<typename RealScalar , bool ConjLhs_, bool ConjRhs_, int Arch, int PacketSize_> template<typename RealPacketType > EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::updateRhs (const RhsScalar * b, DoublePacket< RealPacketType > & dest) const inline
{
     loadRhs(b, dest);
   }
References b, and Eigen::internal::gebp_traits< LhsScalar_, RhsScalar_, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::loadRhs().
updateRhs() [3/3]
template<typename RealScalar , bool ConjLhs_, bool ConjRhs_, int Arch, int PacketSize_> EIGEN_STRONG_INLINE void Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::updateRhs (const RhsScalar * b, ScalarPacket & dest) const inline
 { loadRhs(b, dest); }
References b, and Eigen::internal::gebp_traits< LhsScalar_, RhsScalar_, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::loadRhs().
Member Data Documentation
cj
template<typename RealScalar , bool ConjLhs_, bool ConjRhs_, int Arch, int PacketSize_> conj_helper<LhsScalar, RhsScalar, ConjLhs, ConjRhs> Eigen::internal::gebp_traits< std::complex< RealScalar >, std::complex< RealScalar >, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::cj protected
The documentation for this class was generated from the following file:
products/GeneralBlockPanelKernel.h