MercuryDPM: oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT > Class Template Reference
oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT > Class Template Reference
#include <solid_traction_elements.h>
Public Member Functions
ImposeDisplacementByLagrangeMultiplierElement (FiniteElement *const &element_pt, const int &face_index, const unsigned &id=0, const bool &called_from_refineable_constructor=false)
GeomObject * boundary_shape_geom_object_pt () const
void set_boundary_shape_geom_object_pt (GeomObject *boundary_shape_geom_object_pt, const unsigned &boundary_number_in_bulk_mesh)
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Fill in the residuals.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Fill in contribution from Jacobian.
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
void output (std::ostream &outfile, const unsigned &n_plot)
Output function.
void output (std::ostream &outfile)
Output function.
double square_of_l2_norm_of_error ()
Public Member Functions inherited from oomph::SolidFaceElement
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
double interpolated_xi (const Vector< double > &s, const unsigned &i) const
void interpolated_xi (const Vector< double > &s, Vector< double > &xi) const
Public Member Functions inherited from oomph::FaceElement
FaceElement ()
Constructor: Initialise all appropriate member data.
virtual ~FaceElement ()
Empty virtual destructor.
FaceElement (const FaceElement &)=delete
Broken copy constructor.
const unsigned & boundary_number_in_bulk_mesh () const
Broken assignment operator.
void set_boundary_number_in_bulk_mesh (const unsigned &b)
Set function for the boundary number in bulk mesh.
double J_eulerian (const Vector< double > &s) const
double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
double interpolated_x (const Vector< double > &s, const unsigned &i) const
double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
void interpolated_x (const Vector< double > &s, Vector< double > &x) const
void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
int & normal_sign ()
int normal_sign () const
int & face_index ()
int face_index () const
const Vector< double > * tangent_direction_pt () const
Public access function for the tangent direction pointer.
void set_tangent_direction (Vector< double > *tangent_direction_pt)
Set the tangent direction vector.
void turn_on_warning_for_discontinuous_tangent ()
void turn_off_warning_for_discontinuous_tangent ()
void continuous_tangent_and_outer_unit_normal (const Vector< double > &s, Vector< Vector< double >> &tang_vec, Vector< double > &unit_normal) const
void continuous_tangent_and_outer_unit_normal (const unsigned &ipt, Vector< Vector< double >> &tang_vec, Vector< double > &unit_normal) const
void outer_unit_normal (const Vector< double > &s, Vector< double > &unit_normal) const
Compute outer unit normal at the specified local coordinate.
void outer_unit_normal (const unsigned &ipt, Vector< double > &unit_normal) const
Compute outer unit normal at ipt-th integration point.
FiniteElement *& bulk_element_pt ()
Pointer to higher-dimensional "bulk" element.
FiniteElement * bulk_element_pt () const
Pointer to higher-dimensional "bulk" element (const version)
CoordinateMappingFctPt & face_to_bulk_coordinate_fct_pt ()
CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt () const
BulkCoordinateDerivativesFctPt & bulk_coordinate_derivatives_fct_pt ()
BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt () const
Vector< double > local_coordinate_in_bulk (const Vector< double > &s) const
void get_local_coordinate_in_bulk (const Vector< double > &s, Vector< double > &s_bulk) const
void get_ds_bulk_ds_face (const Vector< double > &s, DenseMatrix< double > &dsbulk_dsface, unsigned &interior_direction) const
unsigned & bulk_position_type (const unsigned &i)
const unsigned & bulk_position_type (const unsigned &i) const
void bulk_node_number_resize (const unsigned &i)
Resize the storage for the bulk node numbers.
unsigned & bulk_node_number (const unsigned &n)
const unsigned & bulk_node_number (const unsigned &n) const
void bulk_position_type_resize (const unsigned &i)
Resize the storage for bulk_position_type to i entries.
unsigned & nbulk_value (const unsigned &n)
unsigned nbulk_value (const unsigned &n) const
void nbulk_value_resize (const unsigned &i)
void resize_nodes (Vector< unsigned > &nadditional_data_values)
void output_zeta (std::ostream &outfile, const unsigned &nplot)
Output boundary coordinate zeta.
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
virtual void disable_ALE ()
virtual void enable_ALE ()
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual unsigned nvertex_node () const
virtual Node * vertex_node_pt (const unsigned &j) const
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output (FILE *file_pt)
virtual void output (FILE *file_pt, const unsigned &n_plot)
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output an exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output a time-dependent exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::SolidFiniteElement
void set_lagrangian_dimension (const unsigned &lagrangian_dimension)
virtual bool has_internal_solid_data ()
SolidFiniteElement ()
Constructor: Set defaults.
virtual ~SolidFiniteElement ()
Destructor to clean up any allocated memory.
SolidFiniteElement (const SolidFiniteElement &)=delete
Broken copy constructor.
unsigned ngeom_data () const
Broken assignment operator.
Data * geom_data_pt (const unsigned &j)
void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual void get_x_and_xi (const Vector< double > &s, Vector< double > &x_fe, Vector< double > &x, Vector< double > &xi_fe, Vector< double > &xi) const
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt, MacroElement *undeformed_macro_elem_pt)
void set_undeformed_macro_elem_pt (MacroElement *undeformed_macro_elem_pt)
MacroElement * undeformed_macro_elem_pt ()
Access function to pointer to "undeformed" macro element.
double dshape_lagrangian (const Vector< double > &s, Shape &psi, DShape &dpsidxi) const
virtual double dshape_lagrangian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidxi) const
double d2shape_lagrangian (const Vector< double > &s, Shape &psi, DShape &dpsidxi, DShape &d2psidxi) const
virtual double d2shape_lagrangian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidxi, DShape &d2psidxi) const
unsigned lagrangian_dimension () const
unsigned nnodal_lagrangian_type () const
Node * construct_node (const unsigned &n)
Construct the local node n and return a pointer to it.
Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
Node * construct_boundary_node (const unsigned &n)
Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
double raw_lagrangian_position (const unsigned &n, const unsigned &i) const
double raw_lagrangian_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double lagrangian_position (const unsigned &n, const unsigned &i) const
Return i-th Lagrangian coordinate at local node n.
double lagrangian_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void interpolated_dxids (const Vector< double > &s, DenseMatrix< double > &dxids) const
virtual void J_lagrangian (const Vector< double > &s) const
virtual double J_lagrangian_at_knot (const unsigned &ipt) const
SolidInitialCondition *& solid_ic_pt ()
Pointer to object that describes the initial condition.
void enable_solve_for_consistent_newmark_accel ()
void disable_solve_for_consistent_newmark_accel ()
Set to reset the problem being solved to be the standard problem.
MultiplierFctPt & multiplier_fct_pt ()
MultiplierFctPt multiplier_fct_pt () const
virtual void get_residuals_for_solid_ic (Vector< double > &residuals)
void fill_in_residuals_for_solid_ic (Vector< double > &residuals)
void fill_in_jacobian_for_solid_ic (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_for_newmark_accel (DenseMatrix< double > &jacobian)
void compute_norm (double &el_norm)
int position_local_eqn (const unsigned &n, const unsigned &k, const unsigned &j) const
Protected Member Functions
void fill_in_generic_contribution_to_residuals_displ_lagr_multiplier (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
unsigned ndof_types () const
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Protected Member Functions inherited from oomph::FaceElement
void add_additional_values (const Vector< unsigned > &nadditional_values, const unsigned &id)
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Member Functions inherited from oomph::SolidFiniteElement
void fill_in_generic_jacobian_for_solid_ic (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
void set_nnodal_lagrangian_type (const unsigned &nlagrangian_type)
virtual double local_to_lagrangian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_lagrangian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_lagrangian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void assign_solid_local_eqn_numbers (const bool &store_local_dof)
Assign local equation numbers for the solid equations in the element.
void describe_solid_local_dofs (std::ostream &out, const std::string &current_string) const
Classifies dofs locally for solid specific aspects.
virtual void fill_in_jacobian_from_solid_position_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_solid_position_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_solid_position_fd ()
virtual void reset_after_solid_position_fd ()
virtual void update_in_solid_position_fd (const unsigned &i)
virtual void reset_in_solid_position_fd (const unsigned &i)
Protected Attributes
unsigned Id
Lagrange Id.
GeomObject * Boundary_shape_geom_object_pt
Vector< GeomObject * > Sub_geom_object_pt
Storage for sub-GeomObject at the integration points.
Vector< Vector< double > > Zeta_sub_geom_object
bool Sparsify
Protected Attributes inherited from oomph::FaceElement
unsigned Boundary_number_in_bulk_mesh
The boundary number in the bulk mesh to which this element is attached.
FiniteElement * Bulk_element_pt
Pointer to the associated higher-dimensional "bulk" element.
Vector< unsigned > Bulk_node_number
Vector< unsigned > Nbulk_value
Vector< double > * Tangent_direction_pt
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Protected Attributes inherited from oomph::SolidFiniteElement
MacroElement * Undeformed_macro_elem_pt
Pointer to the element's "undeformed" macro element (NULL by default)
SolidInitialCondition * Solid_ic_pt
Pointer to object that specifies the initial condition.
bool Solve_for_consistent_newmark_accel_flag
Additional Inherited Members
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Public Types inherited from oomph::SolidFiniteElement
typedef double(* MultiplierFctPt) (const Vector< double > &xi)
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
template<class ELEMENT>
class oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >
///////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////// A class for elements that allow the imposition of a displacement constraint for "bulk" solid elements via a Lagrange multiplier. The geometrical information can be read from the FaceGeometry<ELEMENT> class and and thus, we can be generic enough without the need to have a separate equations class. NOTE: Currently (and for the foreseeable future) this element only works with bulk elements that do not have generalised degrees of freedom (so it won't work with Hermite-type elements, say). The additional functionality to deal with such elements could easily be added (once a a suitable test case is written). For now we simply throw errors if an attempt is made to use the element with an unsuitable bulk element.
Constructor & Destructor Documentation
ImposeDisplacementByLagrangeMultiplierElement()
template<class ELEMENT > oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::ImposeDisplacementByLagrangeMultiplierElement (FiniteElement *const & element_pt, const int & face_index, const unsigned & id = 0, const bool & called_from_refineable_constructor = false) inline
Constructor takes a "bulk" element and the index that identifies which face the FaceElement is supposed to be attached to. The optional identifier can be used to distinguish the additional nodal values created by this element from thos created by other FaceElements.
       : FaceGeometry<ELEMENT>(), FaceElement(), Boundary_shape_geom_object_pt(0)
     {
       //  Store the ID of the FaceElement -- this is used to distinguish
       // it from any others
       Id = id;
       // By default sparsify, i.e. check if the GeomObject that
       // defines the boundary contains sub-GeomObjects. If so,
       // only use their GeomData as the external Data that affects
       // this element's residuals.
       Sparsify = true;
       // Build the face element
       element_pt->build_face_element(face_index, this);
 #ifdef PARANOID
       {
         // Initialise number of assigned geom Data.
         N_assigned_geom_data = 0;
         // Check that the bulk element is not a refineable 3d element
         if (!called_from_refineable_constructor)
         {
           if (element_pt->dim() == 3)
           {
             // Is it refineable
             RefineableElement* ref_el_pt =
               dynamic_cast<RefineableElement*>(element_pt);
             if (ref_el_pt != 0)
             {
               if (this->has_hanging_nodes())
               {
                 throw OomphLibError(
                   "This face element will not work correctly if nodes are "
                   "hanging\nUse the refineable version instead. ",
                   OOMPH_CURRENT_FUNCTION,
                   OOMPH_EXCEPTION_LOCATION);
               }
             }
           }
         }
       }
       {
         // Check that the bulk element does not require generalised positional
         // degrees of freedom
         if (element_pt->nnodal_position_type() != 1)
         {
           throw OomphLibError(
             "ImposeDisplacementByLagrangeMultiplierElement cannot (currently) "
             "be used with elements that have generalised positional dofs",
             OOMPH_CURRENT_FUNCTION,
             OOMPH_EXCEPTION_LOCATION);
         }
       }
 #endif
       // Dimension of the bulk element
       unsigned dim = element_pt->dim();
       // We need dim additional values for each FaceElement node
       // to store the dim Lagrange multipliers.
       Vector<unsigned> n_additional_values(nnode(), dim);
       // Now add storage for Lagrange multipliers and set the map containing
       // the position of the first entry of this face element's
       // additional values.
       add_additional_values(n_additional_values, id);
     }
References oomph::FaceElement::add_additional_values(), oomph::FiniteElement::build_face_element(), oomph::FiniteElement::dim(), oomph::FaceElement::face_index(), oomph::FiniteElement::has_hanging_nodes(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::Id, oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::Sparsify.
Member Function Documentation
boundary_shape_geom_object_pt()
template<class ELEMENT > GeomObject* oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::boundary_shape_geom_object_pt () const inline
Access to GeomObject that specifies the prescribed boundary displacement; GeomObject is assumed to be parametrised by the same coordinate that is used as the boundary coordinate in the bulk solid mesh to which this element is attached.
     {
       return Boundary_shape_geom_object_pt;
     }
References oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::Boundary_shape_geom_object_pt.
Referenced by oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::set_boundary_shape_geom_object_pt().
fill_in_contribution_to_jacobian()
template<class ELEMENT > void oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline virtual
Fill in contribution from Jacobian.
Reimplemented from oomph::SolidFiniteElement.
Reimplemented in oomph::RefineableImposeDisplacementByLagrangeMultiplierElement< ELEMENT >.
     {
       // Call the generic routine with the flag set to 1
       fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(
         residuals, jacobian, 1);
       // Fill in the derivatives w.r.t. external data by FD, re-using
       // the pre-computed residual vector
       fill_in_jacobian_from_external_by_fd(residuals, jacobian);
     }
References oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), and oomph::GeneralisedElement::fill_in_jacobian_from_external_by_fd().
Referenced by oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_contribution_to_jacobian_and_mass_matrix().
fill_in_contribution_to_jacobian_and_mass_matrix()
template<class ELEMENT > void oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) inline virtual
Fill in contribution to Mass matrix and Jacobian. There is no contributiont to mass matrix so simply call the fill_in_contribution_to_jacobian term Note that the Jacobian is multiplied by minus one to ensure that the mass matrix is positive semi-definite.
Reimplemented from oomph::GeneralisedElement.
     {
       // Just call the jacobian calculation
       fill_in_contribution_to_jacobian(residuals, jacobian);
       // Multiply the residuals and jacobian by minus one
       const unsigned n_dof = this->ndof();
       for (unsigned i = 0; i < n_dof; i++)
       {
         residuals[i] *= -1.0;
         for (unsigned j = 0; j < n_dof; j++)
         {
           jacobian(i, j) *= -1.0;
         }
       }
     }
References oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_contribution_to_jacobian(), i, j, and oomph::GeneralisedElement::ndof().
fill_in_contribution_to_residuals()
template<class ELEMENT > void oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) inline virtual
Fill in the residuals.
Reimplemented from oomph::GeneralisedElement.
Reimplemented in oomph::RefineableImposeDisplacementByLagrangeMultiplierElement< ELEMENT >.
     {
       // Call the generic routine with the flag set to 0
       fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(
         residuals, GeneralisedElement::Dummy_matrix, 0);
     }
References oomph::GeneralisedElement::Dummy_matrix, and oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_displ_lagr_multiplier().
fill_in_generic_contribution_to_residuals_displ_lagr_multiplier()
template<class ELEMENT > void oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_displ_lagr_multiplier (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) inline protected
Helper function to compute the residuals and, if flag==1, the Jacobian
     {
       // Find out how many positional dofs there are
       unsigned n_position_type = this->nnodal_position_type();
 #ifdef PARANOID
       if (n_position_type != 1)
       {
         throw OomphLibError(
           "ImposeDisplacementByLagrangeMultiplierElement cannot (currently) be "
           "used with elements that have generalised positional dofs",
           OOMPH_CURRENT_FUNCTION,
           OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // Find out how many nodes there are
       unsigned n_node = nnode();
       // Dimension of element
       unsigned dim_el = dim();
       // Set up memory for the shape functions
       Shape psi(n_node);
       DShape dpsids(n_node, dim_el);
       // Set the value of n_intpt
       unsigned n_intpt = integral_pt()->nweight();
       // Loop over the integration points
       for (unsigned ipt = 0; ipt < n_intpt; ipt++)
       {
         // Get the integral weight
         double w = integral_pt()->weight(ipt);
         // Only need to call the local derivatives
         dshape_local_at_knot(ipt, psi, dpsids);
         // Calculate the Eulerian coordinates and Lagrange multiplier
         Vector<double> x(dim_el + 1, 0.0);
         Vector<double> lambda(dim_el + 1, 0.0);
         Vector<double> zeta(dim_el, 0.0);
         DenseMatrix<double> interpolated_a(dim_el, dim_el + 1, 0.0);
         // Loop over nodes
         for (unsigned j = 0; j < n_node; j++)
         {
           Node* nod_pt = node_pt(j);
           // Cast to a boundary node
           BoundaryNodeBase* bnod_pt =
             dynamic_cast<BoundaryNodeBase*>(node_pt(j));
           // Get the index of the first nodal value associated with
           // this FaceElement
           unsigned first_index =
             bnod_pt->index_of_first_value_assigned_by_face_element(Id);
           // Assemble higher-dimensional quantities
           for (unsigned i = 0; i < dim_el + 1; i++)
           {
             x[i] += nodal_position(j, i) * psi(j);
             lambda[i] += nod_pt->value(first_index + i) * psi(j);
             for (unsigned ii = 0; ii < dim_el; ii++)
             {
               interpolated_a(ii, i) +=
                 lagrangian_position(j, i) * dpsids(j, ii);
             }
           }
           if (!Sparsify)
           {
             for (unsigned k = 0; k < n_position_type; k++)
             {
               // Assemble in-element quantities: boundary coordinate
               for (unsigned i = 0; i < dim_el; i++)
               {
                 zeta[i] += zeta_nodal(j, k, i) * psi(j, k);
               }
             }
           }
         }
         if (Sparsify) zeta = Zeta_sub_geom_object[ipt];
         // Now find the local undeformed metric tensor from the tangent Vectors
         DenseMatrix<double> a(dim_el);
         for (unsigned i = 0; i < dim_el; i++)
         {
           for (unsigned j = 0; j < dim_el; j++)
           {
             // Initialise surface metric tensor to zero
             a(i, j) = 0.0;
             // Take the dot product
             for (unsigned k = 0; k < dim_el + 1; k++)
             {
               a(i, j) += interpolated_a(i, k) * interpolated_a(j, k);
             }
           }
         }
         // Find the determinant of the metric tensor
         double adet = 0.0;
         switch (dim_el + 1)
         {
           case 2:
             adet = a(0, 0);
             break;
           case 3:
             adet = a(0, 0) * a(1, 1) - a(0, 1) * a(1, 0);
             break;
           default:
             throw OomphLibError(
               "Wrong dimension "
               "fill_in_generic_contribution_to_residuals_displ_lagr_multiplier",
               "ImposeDisplacementByLagrangeMultiplierElement::fill_in_generic_"
               "contribution_to_residuals_displ_lagr_multiplier()",
               OOMPH_EXCEPTION_LOCATION);
         }
         // Get prescribed wall shape
         Vector<double> r_prescribed(dim_el + 1);
         if (!Sparsify)
         {
           Boundary_shape_geom_object_pt->position(zeta, r_prescribed);
         }
         else
         {
           Sub_geom_object_pt[ipt]->position(zeta, r_prescribed);
         }
         // Premultiply the weights and the square-root of the determinant of
         // the metric tensor
         double W = w * sqrt(adet);
         // Assemble residuals and jacobian
         // Loop over directions
         for (unsigned i = 0; i < dim_el + 1; i++)
         {
           // Loop over the nodes
           for (unsigned j = 0; j < n_node; j++)
           {
             // Assemble residual for Lagrange multiplier:
             // Cast to a boundary node
             BoundaryNodeBase* bnod_pt =
               dynamic_cast<BoundaryNodeBase*>(node_pt(j));
             // Local eqn number:
             int local_eqn = nodal_local_eqn(
               j,
               bnod_pt->index_of_first_value_assigned_by_face_element(Id) + i);
             if (local_eqn >= 0)
             {
               residuals[local_eqn] += (x[i] - r_prescribed[i]) * psi(j) * W;
               // Do Jacobian too?
               if (flag == 1)
               {
                 // Loop over the nodes again for unknowns (only diagonal
                 // contribution to direction!).
                 for (unsigned jj = 0; jj < n_node; jj++)
                 {
                   int local_unknown = position_local_eqn(jj, 0, i);
                   if (local_unknown >= 0)
                   {
                     jacobian(local_eqn, local_unknown) += psi(jj) * psi(j) * W;
                   }
                 }
               }
             }
             // Add Lagrange multiplier contribution to bulk equations
             // Local eqn number: Node, type, direction
             local_eqn = position_local_eqn(j, 0, i);
             if (local_eqn >= 0)
             {
               // Add to residual
               residuals[local_eqn] += lambda[i] * psi(j) * W;
               // Do Jacobian too?
               if (flag == 1)
               {
                 // Loop over the nodes again for unknowns (only diagonal
                 // contribution to direction!).
                 for (unsigned jj = 0; jj < n_node; jj++)
                 {
                   // Cast to a boundary node
                   BoundaryNodeBase* bnode_pt =
                     dynamic_cast<BoundaryNodeBase*>(node_pt(jj));
                   int local_unknown = nodal_local_eqn(
                     jj,
                     bnode_pt->index_of_first_value_assigned_by_face_element(
                       Id) +
                       i);
                   if (local_unknown >= 0)
                   {
                     jacobian(local_eqn, local_unknown) += psi(jj) * psi(j) * W;
                   }
                 }
               }
             }
           }
         }
       } // End of loop over the integration points
     }
References a, oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::Boundary_shape_geom_object_pt, oomph::FiniteElement::dim(), oomph::FiniteElement::dshape_local_at_knot(), i, oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::Id, oomph::BoundaryNodeBase::index_of_first_value_assigned_by_face_element(), oomph::FiniteElement::integral_pt(), j, k, oomph::SolidFiniteElement::lagrangian_position(), lambda, oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::node_pt(), oomph::Integral::nweight(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::GeomObject::position(), oomph::SolidFiniteElement::position_local_eqn(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::Sparsify, sqrt(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::Sub_geom_object_pt, oomph::Node::value(), w, oomph::QuadTreeNames::W, oomph::Integral::weight(), plotDoE::x, Eigen::zeta(), oomph::SolidFaceElement::zeta_nodal(), and oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::Zeta_sub_geom_object.
Referenced by oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_contribution_to_jacobian(), and oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_contribution_to_residuals().
get_dof_numbers_for_unknowns()
template<class ELEMENT > void oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> & dof_lookup_list) const inline protected virtual
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the dof that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
Reimplemented from oomph::GeneralisedElement.
     {
       // temporary pair (used to store dof lookup prior to being added to list)
       std::pair<unsigned, unsigned> dof_lookup;
       // number of nodes
       const unsigned n_node = this->nnode();
       // Loop over directions
       unsigned dim_el = this->dim();
       for (unsigned i = 0; i < dim_el + 1; i++)
       {
         // Loop over the nodes
         for (unsigned j = 0; j < n_node; j++)
         {
           // Cast to a boundary node
           BoundaryNodeBase* bnod_pt =
             dynamic_cast<BoundaryNodeBase*>(node_pt(j));
           // Local eqn number:
           int local_eqn = nodal_local_eqn(
             j, bnod_pt->index_of_first_value_assigned_by_face_element(Id) + i);
           if (local_eqn >= 0)
           {
             // store dof lookup in temporary pair: First entry in pair
             // is global equation number; second entry is dof type
             dof_lookup.first = this->eqn_number(local_eqn);
             dof_lookup.second = i;
             // add to list
             dof_lookup_list.push_front(dof_lookup);
           }
         }
       }
     }
References oomph::FiniteElement::dim(), oomph::GeneralisedElement::eqn_number(), i, oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::Id, oomph::BoundaryNodeBase::index_of_first_value_assigned_by_face_element(), j, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), and oomph::FiniteElement::node_pt().
ndof_types()
template<class ELEMENT > unsigned oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::ndof_types () const inline protected virtual
The number of "DOF types" that degrees of freedom in this element are sub-divided into: We only label the Lagrange multiplier degrees of freedom (one for each spatial dimension)
Reimplemented from oomph::GeneralisedElement.
     {
       return this->dim() + 1;
     }
References oomph::FiniteElement::dim().
output() [1/2]
template<class ELEMENT > void oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::output (std::ostream & outfile) inline virtual
Output function.
Reimplemented from oomph::FiniteElement.
     {
       unsigned n_plot = 5;
       output(outfile, n_plot);
     }
References oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::output().
output() [2/2]
template<class ELEMENT > void oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::output (std::ostream & outfile, const unsigned & n_plot) inline virtual
Output function.
Reimplemented from oomph::FiniteElement.
     {
       // Elemental dimension
       unsigned dim_el = dim();
       // Find the number of positional types
       unsigned n_position_type = this->nnodal_position_type();
 #ifdef PARANOID
       if (n_position_type != 1)
       {
         throw OomphLibError(
           "ImposeDisplacementByLagrangeMultiplierElement cannot (currently) be "
           "used with elements that have generalised positional dofs",
           OOMPH_CURRENT_FUNCTION,
           OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // Local coord
       Vector<double> s(dim_el);
       // # of nodes,
       unsigned n_node = nnode();
       Shape psi(n_node, n_position_type);
       // Tecplot header info
       outfile << this->tecplot_zone_string(n_plot);
       // Loop over plot points
       unsigned num_plot_points = this->nplot_points(n_plot);
       for (unsigned iplot = 0; iplot < num_plot_points; iplot++)
       {
         // Get local coordinates of plot point
         this->get_s_plot(iplot, n_plot, s);
         // Get shape function
         shape(s, psi);
         // Calculate the Eulerian coordinates and Lagrange multiplier
         Vector<double> x(dim_el + 1, 0.0);
         Vector<double> lambda(dim_el + 1, 0.0);
         Vector<double> zeta(dim_el, 0.0);
         for (unsigned j = 0; j < n_node; j++)
         {
           // Cast to a boundary node
           BoundaryNodeBase* bnod_pt =
             dynamic_cast<BoundaryNodeBase*>(node_pt(j));
           // get the node pt
           Node* nod_pt = node_pt(j);
           // Get the index of the first nodal value associated with
           // this FaceElement
           unsigned first_index =
             bnod_pt->index_of_first_value_assigned_by_face_element(Id);
           // higher dimensional quantities
           for (unsigned i = 0; i < dim_el + 1; i++)
           {
             x[i] += nodal_position(j, i) * psi(j, 0); // need to sort
                                                       // this out properly
                                                       // for generalised dofs
             lambda[i] += nod_pt->value(first_index + i) * psi(j, 0);
           }
           // In-element quantities
           for (unsigned i = 0; i < dim_el; i++)
           {
             // Loop over positional types
             for (unsigned k = 0; k < n_position_type; k++)
             {
               zeta[i] += zeta_nodal(j, k, i) * psi(j, k);
             }
           }
         }
         // Get prescribed wall shape
         Vector<double> r_prescribed(dim_el + 1);
         Boundary_shape_geom_object_pt->position(zeta, r_prescribed);
         // Output stuff
         for (unsigned i = 0; i < dim_el + 1; i++)
         {
           outfile << x[i] << " ";
         }
         for (unsigned i = 0; i < dim_el + 1; i++)
         {
           outfile << -lambda[i] << " ";
         }
         for (unsigned i = 0; i < dim_el + 1; i++)
         {
           outfile << r_prescribed[i] << " ";
         }
         /*     for(unsigned i=0;i<dim_el;i++) */
         /*       { */
         /*        outfile << zeta[i] << " "; */
         /*       } */
         outfile << std::endl;
       }
     }
References oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::Boundary_shape_geom_object_pt, oomph::FiniteElement::dim(), oomph::FiniteElement::get_s_plot(), i, oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::Id, oomph::BoundaryNodeBase::index_of_first_value_assigned_by_face_element(), j, k, lambda, oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::nplot_points(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::GeomObject::position(), s, oomph::FiniteElement::shape(), oomph::FiniteElement::tecplot_zone_string(), oomph::Node::value(), plotDoE::x, Eigen::zeta(), and oomph::SolidFaceElement::zeta_nodal().
Referenced by oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::output().
set_boundary_shape_geom_object_pt()
template<class ELEMENT > void oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::set_boundary_shape_geom_object_pt (GeomObject * boundary_shape_geom_object_pt, const unsigned & boundary_number_in_bulk_mesh) inline
Set GeomObject that specifies the prescribed boundary displacement; GeomObject is assumed to be parametrised by the same coordinate that is used as the boundary coordinate in the bulk solid mesh to which this element is attached. GeomData of GeomObject is added to this element's external Data. Also specify the boundary number in the bulk mesh to which this element is attached.
     {
       // Record boundary number
 #ifdef PARANOID
       Boundary_number_in_bulk_mesh_has_been_set = true;
 #endif
       Boundary_number_in_bulk_mesh = boundary_number_in_bulk_mesh;
       // Store (possibly compound) GeomObject that specifies the
       // the desired  boundary shape.
       Boundary_shape_geom_object_pt = boundary_shape_geom_object_pt;
       // Don't sparsify: Use all the geometric Data associated with
       // the (possibly compound) GeomObject that specifies the
       // boundary shape as external data for this element.
       if (!Sparsify)
       {
         unsigned n_geom_data = boundary_shape_geom_object_pt->ngeom_data();
 #ifdef PARANOID
         if ((this->nexternal_data() > 0) &&
             (N_assigned_geom_data != this->nexternal_data()))
         {
           std::ostringstream error_message;
           error_message << "About to wipe external data for "
                         << "ImposeDisplacementByLagrangeMultiplierElement.\n"
                         << "I noted that N_assigned_geom_data = "
                         << N_assigned_geom_data
                         << " != nexternal_data() = " << this->nexternal_data()
                         << " \n"
                         << "so we're going to wipe some external data that\n"
                         << "is not geometric Data of the GeomObject that\n"
                         << "specifies the desired boundary shape.\n"
                         << std::endl;
           throw OomphLibError(error_message.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
 #endif
         this->flush_external_data();
         for (unsigned i = 0; i < n_geom_data; i++)
         {
           add_external_data(boundary_shape_geom_object_pt->geom_data_pt(i));
         }
 #ifdef PARANOID
         N_assigned_geom_data = n_geom_data;
 #endif
       }
       // Sparsify: Use locate_zeta to determine the sub-GeomObjects that
       // make up  the (possibly compound) GeomObject that specifies the
       // boundary shape. Use their geometric Data as external data for
       // this element.
       else
       {
         // Find out how many nodes there are
         unsigned n_node = nnode();
         // Get the number of position dofs and dimensions at the node
         const unsigned n_position_type = nnodal_position_type();
         // Dimension of element
         unsigned dim_el = dim();
         // Set up memory for the shape functions
         Shape psi(n_node);
 #ifdef PARANOID
         if ((this->nexternal_data() > 0) &&
             (N_assigned_geom_data != this->nexternal_data()))
         {
           std::ostringstream error_message;
           error_message << "About to wipe external data for "
                         << "ImposeDisplacementByLagrangeMultiplierElement.\n"
                         << "I noted that N_assigned_geom_data = "
                         << N_assigned_geom_data
                         << " != nexternal_data() = " << this->nexternal_data()
                         << " \n"
                         << "so we're going to wipe some external data that\n"
                         << "is not geometric Data of the GeomObject that\n"
                         << "specifies the desired boundary shape.\n"
                         << std::endl;
           throw OomphLibError(error_message.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
 #endif
         // Flush the data
         this->flush_external_data();
 #ifdef PARANOID
         N_assigned_geom_data = 0;
 #endif
         // Prepare local storage
         unsigned n_intpt = integral_pt()->nweight();
         Sub_geom_object_pt.resize(n_intpt);
         Zeta_sub_geom_object.resize(n_intpt);
         // Loop over the integration points
         for (unsigned ipt = 0; ipt < n_intpt; ipt++)
         {
           // Get shape function
           shape_at_knot(ipt, psi);
           // Calculate the intrinsic coordinates
           Vector<double> zeta(dim_el, 0.0);
           Vector<double> s(dim_el);
           // Loop over nodes
           for (unsigned j = 0; j < n_node; j++)
           {
             for (unsigned k = 0; k < n_position_type; k++)
             {
               // Assemble the intrinsic coordinate
               for (unsigned i = 0; i < dim_el; i++)
               {
                 zeta[i] += zeta_nodal(j, k, i) * psi(j, k);
               }
             }
           }
           // Find sub-GeomObject and local coordinate within it
           // at integration point
           Zeta_sub_geom_object[ipt].resize(dim_el);
           Boundary_shape_geom_object_pt->locate_zeta(
             zeta, Sub_geom_object_pt[ipt], Zeta_sub_geom_object[ipt]);
           unsigned n_geom_data = Sub_geom_object_pt[ipt]->ngeom_data();
           for (unsigned i = 0; i < n_geom_data; i++)
           {
             add_external_data(Sub_geom_object_pt[ipt]->geom_data_pt(i));
           }
 #ifdef PARANOID
           N_assigned_geom_data += n_geom_data;
 #endif
         }
       }
     }
References oomph::GeneralisedElement::add_external_data(), oomph::FaceElement::Boundary_number_in_bulk_mesh, oomph::FaceElement::boundary_number_in_bulk_mesh(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::boundary_shape_geom_object_pt(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::Boundary_shape_geom_object_pt, oomph::FiniteElement::dim(), oomph::GeneralisedElement::flush_external_data(), oomph::SolidFiniteElement::geom_data_pt(), oomph::GeomObject::geom_data_pt(), i, oomph::FiniteElement::integral_pt(), j, k, oomph::GeomObject::locate_zeta(), oomph::GeneralisedElement::nexternal_data(), oomph::GeomObject::ngeom_data(), oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), oomph::Integral::nweight(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, s, oomph::FiniteElement::shape_at_knot(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::Sparsify, oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::Sub_geom_object_pt, Eigen::zeta(), oomph::SolidFaceElement::zeta_nodal(), and oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::Zeta_sub_geom_object.
Referenced by ContactProblem< ELEMENT >::create_displ_imposition_elements(), UnstructuredTorusProblem< ELEMENT >::create_lagrange_multiplier_elements(), FSICollapsibleChannelProblem< ELEMENT >::create_lagrange_multiplier_elements(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_lagrange_multiplier_elements(), FSIChannelWithLeafletProblem< ELEMENT >::create_lagrange_multiplier_elements(), UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_lagrange_multiplier_elements(), PrescribedBoundaryDisplacementProblem< ELEMENT >::create_lagrange_multiplier_elements(), UnstructuredImmersedEllipseProblem< ELEMENT >::create_lagrange_multiplier_elements(), UnstructuredFluidProblem< ELEMENT >::create_lagrange_multiplier_elements(), CollapsibleChannelProblem< ELEMENT >::create_lagrange_multiplier_elements(), and oomph::NonLinearElasticitySmoothMesh< ELEMENT >::operator()().
square_of_l2_norm_of_error()
template<class ELEMENT > double oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::square_of_l2_norm_of_error () inline
Compute square of L2 norm of error between prescribed and actual displacement
     {
       // Find out how many positional dofs there are
       unsigned n_position_type = this->nnodal_position_type();
 #ifdef PARANOID
       if (n_position_type != 1)
       {
         throw OomphLibError(
           "ImposeDisplacementByLagrangeMultiplierElement cannot (currently) be "
           "used with elements that have generalised positional dofs",
           OOMPH_CURRENT_FUNCTION,
           OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // Find out how many nodes there are
       unsigned n_node = nnode();
       // Dimension of element
       unsigned dim_el = dim();
       // Set up memory for the shape functions
       Shape psi(n_node);
       DShape dpsids(n_node, dim_el);
       // Set the value of n_intpt
       unsigned n_intpt = integral_pt()->nweight();
       // Initialise error
       double squared_error = 0.0;
       // Loop over the integration points
       for (unsigned ipt = 0; ipt < n_intpt; ipt++)
       {
         // Get the integral weight
         double w = integral_pt()->weight(ipt);
         // Only need to call the local derivatives
         dshape_local_at_knot(ipt, psi, dpsids);
         // Calculate the Eulerian coordinates and Lagrange multiplier
         Vector<double> x(dim_el + 1, 0.0);
         Vector<double> lambda(dim_el + 1, 0.0);
         Vector<double> zeta(dim_el, 0.0);
         DenseMatrix<double> interpolated_a(dim_el, dim_el + 1, 0.0);
         // Loop over nodes
         for (unsigned j = 0; j < n_node; j++)
         {
           Node* nod_pt = node_pt(j);
           // Cast to a boundary node
           BoundaryNodeBase* bnod_pt =
             dynamic_cast<BoundaryNodeBase*>(node_pt(j));
           // Get the index of the first nodal value associated with
           // this FaceElement
           unsigned first_index =
             bnod_pt->index_of_first_value_assigned_by_face_element(Id);
           // Assemble higher-dimensional quantities
           for (unsigned i = 0; i < dim_el + 1; i++)
           {
             x[i] += nodal_position(j, i) * psi(j);
             lambda[i] += nod_pt->value(first_index + i) * psi(j);
             for (unsigned ii = 0; ii < dim_el; ii++)
             {
               interpolated_a(ii, i) +=
                 lagrangian_position(j, i) * dpsids(j, ii);
             }
           }
           if (!Sparsify)
           {
             for (unsigned k = 0; k < n_position_type; k++)
             {
               // Assemble in-element quantities: boundary coordinate
               for (unsigned i = 0; i < dim_el; i++)
               {
                 zeta[i] += zeta_nodal(j, k, i) * psi(j, k);
               }
             }
           }
         }
         if (Sparsify) zeta = Zeta_sub_geom_object[ipt];
         // Now find the local undeformed metric tensor from the tangent Vectors
         DenseMatrix<double> a(dim_el);
         for (unsigned i = 0; i < dim_el; i++)
         {
           for (unsigned j = 0; j < dim_el; j++)
           {
             // Initialise surface metric tensor to zero
             a(i, j) = 0.0;
             // Take the dot product
             for (unsigned k = 0; k < dim_el + 1; k++)
             {
               a(i, j) += interpolated_a(i, k) * interpolated_a(j, k);
             }
           }
         }
         // Find the determinant of the metric tensor
         double adet = 0.0;
         switch (dim_el + 1)
         {
           case 2:
             adet = a(0, 0);
             break;
           case 3:
             adet = a(0, 0) * a(1, 1) - a(0, 1) * a(1, 0);
             break;
           default:
             throw OomphLibError(
               "Wrong dimension "
               "fill_in_generic_contribution_to_residuals_displ_lagr_multiplier",
               "ImposeDisplacementByLagrangeMultiplierElement::fill_in_generic_"
               "contribution_to_residuals_displ_lagr_multiplier()",
               OOMPH_EXCEPTION_LOCATION);
         }
         // Get prescribed wall shape
         Vector<double> r_prescribed(dim_el + 1);
         if (!Sparsify)
         {
           Boundary_shape_geom_object_pt->position(zeta, r_prescribed);
         }
         else
         {
           Sub_geom_object_pt[ipt]->position(zeta, r_prescribed);
         }
         // Premultiply the weights and the square-root of the determinant of
         // the metric tensor
         double W = w * sqrt(adet);
         // Assemble error
         // Loop over directions
         for (unsigned i = 0; i < dim_el + 1; i++)
         {
           squared_error +=
             (x[i] - r_prescribed[i]) * (x[i] - r_prescribed[i]) * W;
         }
       } // End of loop over the integration points
       return squared_error;
     }
References a, oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::Boundary_shape_geom_object_pt, oomph::FiniteElement::dim(), oomph::FiniteElement::dshape_local_at_knot(), i, oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::Id, oomph::BoundaryNodeBase::index_of_first_value_assigned_by_face_element(), oomph::FiniteElement::integral_pt(), j, k, oomph::SolidFiniteElement::lagrangian_position(), lambda, oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::node_pt(), oomph::Integral::nweight(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::GeomObject::position(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::Sparsify, sqrt(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::Sub_geom_object_pt, oomph::Node::value(), w, oomph::QuadTreeNames::W, oomph::Integral::weight(), plotDoE::x, Eigen::zeta(), oomph::SolidFaceElement::zeta_nodal(), and oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::Zeta_sub_geom_object.
Member Data Documentation
Boundary_shape_geom_object_pt
template<class ELEMENT > GeomObject* oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::Boundary_shape_geom_object_pt protected
GeomObject that specifies the prescribed boundary displacement; GeomObject is assumed to be parametrised by the same coordinate the is used as the boundary coordinate in the bulk solid mesh to which this element is attached.
Referenced by oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::boundary_shape_geom_object_pt(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::output(), oomph::RefineableImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::set_boundary_shape_geom_object_pt(), and oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::square_of_l2_norm_of_error().
Id
template<class ELEMENT > unsigned oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::Id protected
Lagrange Id.
Referenced by oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::get_dof_numbers_for_unknowns(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::ImposeDisplacementByLagrangeMultiplierElement(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::output(), oomph::RefineableImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), and oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::square_of_l2_norm_of_error().
Sparsify
template<class ELEMENT > bool oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::Sparsify protected
Boolean flag to indicate if we're using geometric Data of sub-GeomObjects that make up the (possibly compound) GeomObject that specifies the boundary shape. Defaults to true.
Referenced by oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::ImposeDisplacementByLagrangeMultiplierElement(), oomph::RefineableImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::set_boundary_shape_geom_object_pt(), and oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::square_of_l2_norm_of_error().
Sub_geom_object_pt
template<class ELEMENT > Vector<GeomObject*> oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::Sub_geom_object_pt protected
Storage for sub-GeomObject at the integration points.
Referenced by oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::RefineableImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::set_boundary_shape_geom_object_pt(), and oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::square_of_l2_norm_of_error().
Zeta_sub_geom_object
template<class ELEMENT > Vector<Vector<double> > oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::Zeta_sub_geom_object protected
Storage for local coordinates in sub-GeomObjects at integration points
Referenced by oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::RefineableImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::set_boundary_shape_geom_object_pt(), and oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::square_of_l2_norm_of_error().
The documentation for this class was generated from the following file:
solid_traction_elements.h