MercuryDPM: FrictionSpecies Class Reference
FrictionSpecies Class Reference
FrictionSpecies contains the parameters used to describe sliding, rolling and torsional friction.
#include <FrictionSpecies.h>
Public Types
typedef FrictionInteraction InteractionType
The correct Interaction type for this FrictionForceSpecies.
Public Types inherited from SlidingFrictionSpecies
typedef SlidingFrictionInteraction InteractionType
The correct Interaction type for this FrictionForceSpecies.
Public Member Functions
FrictionSpecies ()
The default constructor.
FrictionSpecies (const FrictionSpecies &s)
The default copy constructor.
~FrictionSpecies ()
The default destructor.
void read (std::istream &is)
Reads the species properties from an input stream.
void write (std::ostream &os) const
Writes the species properties to an output stream.
std::string getBaseName () const override
Used in Species::getName to obtain a unique name for each Species.
bool getUseAngularDOFs () const override
Returns true if torques have to be calculated.
void mix (FrictionSpecies *S, FrictionSpecies *T)
creates default values for mixed species
void setRollingStiffness (Mdouble new_kt)
Allows the spring constant to be changed.
Mdouble getRollingStiffness () const
Allows the spring constant to be accessed.
void setRollingDissipation (Mdouble new_dispt)
Allows the tangential viscosity to be changed.
Mdouble getRollingDissipation () const
Allows the tangential viscosity to be accessed.
void setRollingFrictionCoefficient (Mdouble new_mu)
Allows the (dynamic) Coulomb friction coefficient to be changed; also sets mu_s by default.
Mdouble getRollingFrictionCoefficient () const
Allows the (dynamic) Coulomb friction coefficient to be accessed.
void setRollingFrictionCoefficientStatic (Mdouble new_mu)
Allows the static Coulomb rolling friction coefficient to be changed.
Mdouble getRollingFrictionCoefficientStatic () const
Allows the static Coulomb rolling friction coefficient to be accessed.
void setTorsionStiffness (Mdouble new_kt)
Allows the torsion stiffness to be changed.
Mdouble getTorsionStiffness () const
Allows the torsion stiffness to be accessed.
void setTorsionDissipation (Mdouble new_dispt)
Allows the torsion viscosity to be changed.
Mdouble getTorsionDissipation () const
Allows the torsion viscosity to be accessed.
void setTorsionFrictionCoefficient (Mdouble new_mu)
Allows the (dynamic) Coulomb torsion friction coefficient to be changed; also sets mu_s by default.
Mdouble getTorsionFrictionCoefficient () const
Allows the (dynamic) Coulomb torsion friction coefficient to be accessed.
void setTorsionFrictionCoefficientStatic (Mdouble new_mu)
Allows the static Coulomb torsion friction coefficient to be accessed.
Mdouble getTorsionFrictionCoefficientStatic () const
Allows the static Coulomb torsion friction coefficient to be accessed.
Public Member Functions inherited from SlidingFrictionSpecies
SlidingFrictionSpecies ()
The default constructor.
SlidingFrictionSpecies (const SlidingFrictionSpecies &s)
The default copy constructor.
~SlidingFrictionSpecies ()
The default destructor.
void read (std::istream &is)
Reads the species properties from an input stream.
void write (std::ostream &os) const
Writes the species properties to an output stream.
void setSlidingStiffness (Mdouble new_kt)
Allows the spring constant to be changed.
Mdouble getSlidingStiffness () const
Allows the spring constant to be accessed.
void setSlidingDissipation (Mdouble new_dispt)
Allows the tangential viscosity to be changed.
Mdouble getSlidingDissipation () const
Allows the tangential viscosity to be accessed.
void setSlidingFrictionCoefficient (Mdouble new_mu)
Allows the (dynamic) Coulomb friction coefficient to be changed; also sets mu_s by default.
Mdouble getSlidingFrictionCoefficient () const
Allows the (dynamic) Coulomb friction coefficient to be accessed.
void setSlidingFrictionCoefficientStatic (Mdouble new_mu)
Allows the static Coulomb friction coefficient to be changed.
Mdouble getSlidingFrictionCoefficientStatic () const
Allows the static Coulomb friction coefficient to be accessed.
bool getUseAngularDOFs () const override
Returns true if torques have to be calculated.
void mix (SlidingFrictionSpecies *S, SlidingFrictionSpecies *T)
creates default values for mixed species
void setCollisionTimeAndNormalAndTangentialRestitutionCoefficient (Mdouble tc, Mdouble eps, Mdouble beta, Mdouble mass)
Sets k, disp, kt, dispt such that it matches a given tc and eps for a collision of two particles of masses m0,m1.
void setCollisionTimeAndNormalAndTangentialRestitutionCoefficientNoDispt (Mdouble tc, Mdouble eps, Mdouble beta, Mdouble mass)
Sets k, disp, kt (with dispt=0) such that it matches a given tc and eps for a collision of two particles of mass m.
void setIsSuperquadricSpecies (bool isSuperquadricSpecies)
bool getIsSuperquadricSpecies () const
Public Member Functions inherited from BaseForce
BaseSpecies * getBaseSpecies () const
void setBaseSpecies (BaseSpecies *baseSpecies)
Private Attributes
Mdouble rollingStiffness_
rolling stiffness.
Mdouble rollingDissipation_
rolling dissipation coefficient.
Mdouble rollingFrictionCoefficient_
(dynamic) Coulomb rolling friction coefficient.
Mdouble rollingFrictionCoefficientStatic_
static Coulomb rolling friction coefficient
(by default set equal to the dynamic one).
Mdouble torsionStiffness_
rolling stiffness.
Mdouble torsionDissipation_
rolling dissipation coefficient.
Mdouble torsionFrictionCoefficient_
(dynamic) Coulomb torsion friction coefficient.
Mdouble torsionFrictionCoefficientStatic_
static Coulomb torsion friction coefficient
(by default set equal to the dynamic one).
Detailed Description
FrictionSpecies contains the parameters used to describe sliding, rolling and torsional friction.
See FrictionInteraction::computeForce for a description of the force law.
Todo:
TW: should this class be renamed SlidingRollingTorsionFrictionSpecies?
Member Typedef Documentation
InteractionType
typedef FrictionInteraction FrictionSpecies::InteractionType
The correct Interaction type for this FrictionForceSpecies.
Constructor & Destructor Documentation
FrictionSpecies() [1/2]
FrictionSpecies::FrictionSpecies ()
The default constructor.
         : SlidingFrictionSpecies()
 {
     rollingStiffness_ = 0.0;
     rollingDissipation_ = 0.0;
     rollingFrictionCoefficient_ = 0.0;
     rollingFrictionCoefficientStatic_ = 0.0;
     torsionStiffness_ = 0.0;
     torsionDissipation_ = 0.0;
     torsionFrictionCoefficient_ = 0.0;
     torsionFrictionCoefficientStatic_ = 0.0;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"FrictionSpecies::FrictionSpecies() finished"<<std::endl;
 #endif
 }
References rollingDissipation_, rollingFrictionCoefficient_, rollingFrictionCoefficientStatic_, rollingStiffness_, torsionDissipation_, torsionFrictionCoefficient_, torsionFrictionCoefficientStatic_, and torsionStiffness_.
FrictionSpecies() [2/2]
FrictionSpecies::FrictionSpecies (const FrictionSpecies & s)
The default copy constructor.
Parameters
[in] s the species that is copied
         : SlidingFrictionSpecies(s)
 {
     rollingStiffness_ = s.rollingStiffness_;
     rollingDissipation_ = s.rollingDissipation_;
     rollingFrictionCoefficient_ = s.rollingFrictionCoefficient_;
     rollingFrictionCoefficientStatic_ = s.rollingFrictionCoefficientStatic_;
     torsionStiffness_ = s.torsionStiffness_;
     torsionDissipation_ = s.torsionDissipation_;
     torsionFrictionCoefficient_ = s.torsionFrictionCoefficient_;
     torsionFrictionCoefficientStatic_ = s.torsionFrictionCoefficientStatic_;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"FrictionSpecies::FrictionSpecies(const FrictionSpecies &p) finished"<<std::endl;
 #endif
 }
References rollingDissipation_, rollingFrictionCoefficient_, rollingFrictionCoefficientStatic_, rollingStiffness_, s, torsionDissipation_, torsionFrictionCoefficient_, torsionFrictionCoefficientStatic_, and torsionStiffness_.
~FrictionSpecies()
FrictionSpecies::~FrictionSpecies ()
The default destructor.
 {
 #ifdef DEBUG_DESTRUCTOR
     std::cout<<"FrictionSpecies::~FrictionSpecies() finished"<<std::endl;
 #endif
 }
Member Function Documentation
getBaseName()
std::string FrictionSpecies::getBaseName () const override virtual
Used in Species::getName to obtain a unique name for each Species.
Returns
a string containing the name of the species (minus the word "Species")
Reimplemented from SlidingFrictionSpecies.
 {
     return "Friction";
 }
getRollingDissipation()
Mdouble FrictionSpecies::getRollingDissipation () const
Allows the tangential viscosity to be accessed.
 {
     return rollingDissipation_;
 }
References rollingDissipation_.
Referenced by FrictionInteraction::computeFrictionForce().
getRollingFrictionCoefficient()
Mdouble FrictionSpecies::getRollingFrictionCoefficient () const
Allows the (dynamic) Coulomb friction coefficient to be accessed.
 {
     return rollingFrictionCoefficient_;
 }
References rollingFrictionCoefficient_.
Referenced by Slide::actionsBeforeTimeStep(), FrictionInteraction::computeFrictionForce(), and RotatingDrumBidisperseInitialise::RotatingDrumBidisperseInitialise().
getRollingFrictionCoefficientStatic()
Mdouble FrictionSpecies::getRollingFrictionCoefficientStatic () const
Allows the static Coulomb rolling friction coefficient to be accessed.
Allows the static Coulomb friction coefficient to be accessed.
 {
     return rollingFrictionCoefficientStatic_;
 }
References rollingFrictionCoefficientStatic_.
Referenced by FrictionInteraction::computeFrictionForce().
getRollingStiffness()
Mdouble FrictionSpecies::getRollingStiffness () const
Allows the spring constant to be accessed.
 {
     return rollingStiffness_;
 }
References rollingStiffness_.
Referenced by FrictionInteraction::computeFrictionForce(), and FrictionInteraction::getElasticEnergy().
getTorsionDissipation()
Mdouble FrictionSpecies::getTorsionDissipation () const
Allows the torsion viscosity to be accessed.
Allows the tangential viscosity to be accessed.
 {
     return torsionDissipation_;
 }
References torsionDissipation_.
Referenced by FrictionInteraction::computeFrictionForce().
getTorsionFrictionCoefficient()
Mdouble FrictionSpecies::getTorsionFrictionCoefficient () const
Allows the (dynamic) Coulomb torsion friction coefficient to be accessed.
Allows the (dynamic) Coulomb friction coefficient to be accessed.
 {
     return torsionFrictionCoefficient_;
 }
References torsionFrictionCoefficient_.
Referenced by Slide::actionsBeforeTimeStep(), and FrictionInteraction::computeFrictionForce().
getTorsionFrictionCoefficientStatic()
Mdouble FrictionSpecies::getTorsionFrictionCoefficientStatic () const
Allows the static Coulomb torsion friction coefficient to be accessed.
Allows the static Coulomb friction coefficient to be accessed.
 {
     return torsionFrictionCoefficientStatic_;
 }
References torsionFrictionCoefficientStatic_.
Referenced by FrictionInteraction::computeFrictionForce().
getTorsionStiffness()
Mdouble FrictionSpecies::getTorsionStiffness () const
Allows the torsion stiffness to be accessed.
Allows the spring constant to be accessed.
 {
     return torsionStiffness_;
 }
References torsionStiffness_.
Referenced by FrictionInteraction::computeFrictionForce(), and FrictionInteraction::getElasticEnergy().
getUseAngularDOFs()
bool FrictionSpecies::getUseAngularDOFs () const override virtual
Returns true if torques have to be calculated.
Returns true for any FrictionForceSpecies except EmptyFrictionSpecies, because for spherical particles, torques are only caused by tangential forces. See SpeciesHandler::useAngularDOFs for more details
Returns
true
Implements BaseFrictionForce.
Reimplemented in Species< LinearViscoelasticNormalSpecies, FrictionSpecies >.
 {
     return true;
 }
mix()
void FrictionSpecies::mix (FrictionSpecies * S, FrictionSpecies * T)
creates default values for mixed species
For all parameters we assume that the harmonic mean of the parameters of the original two species is a sensible default.
Parameters
[in] S,T the two species whose properties are mixed to create the new species
 {
     SlidingFrictionSpecies::mix(S,T);
     rollingStiffness_ = BaseSpecies::average(S->getRollingStiffness(), T->getRollingStiffness());
     rollingDissipation_ = BaseSpecies::average(S->getRollingDissipation(), T->getRollingDissipation());
     rollingFrictionCoefficient_ = BaseSpecies::averageInf(S->getRollingFrictionCoefficient(), T->getRollingFrictionCoefficient());
     rollingFrictionCoefficientStatic_ = BaseSpecies::averageInf(S->getRollingFrictionCoefficientStatic(),
                                                 T->getRollingFrictionCoefficientStatic());
     torsionStiffness_ = BaseSpecies::average(S->getTorsionStiffness(), T->getTorsionStiffness());
     torsionDissipation_ = BaseSpecies::average(S->getTorsionDissipation(), T->getTorsionDissipation());
     torsionFrictionCoefficient_ = BaseSpecies::averageInf(S->getTorsionFrictionCoefficient(), T->getTorsionFrictionCoefficient());
     torsionFrictionCoefficientStatic_ = BaseSpecies::averageInf(S->getTorsionFrictionCoefficientStatic(),
                                                 T->getTorsionFrictionCoefficientStatic());
 }
References BaseSpecies::average(), BaseSpecies::averageInf(), SlidingFrictionSpecies::mix(), rollingDissipation_, rollingFrictionCoefficient_, rollingFrictionCoefficientStatic_, rollingStiffness_, oomph::QuadTreeNames::S, torsionDissipation_, torsionFrictionCoefficient_, torsionFrictionCoefficientStatic_, and torsionStiffness_.
read()
void FrictionSpecies::read (std::istream & is)
Reads the species properties from an input stream.
Parameters
[in] is input stream (typically the restart file)
 {
     SlidingFrictionSpecies::read(is);
     std::string dummy;
     is >> dummy >> rollingStiffness_;
     is >> dummy >> rollingDissipation_;
     is >> dummy >> rollingFrictionCoefficient_;
     is >> dummy >> rollingFrictionCoefficientStatic_;
     is >> dummy >> torsionStiffness_;
     is >> dummy >> torsionDissipation_;
     is >> dummy >> torsionFrictionCoefficient_;
     is >> dummy >> torsionFrictionCoefficientStatic_;
 }
References SlidingFrictionSpecies::read(), rollingDissipation_, rollingFrictionCoefficient_, rollingFrictionCoefficientStatic_, rollingStiffness_, oomph::Global_string_for_annotation::string(), torsionDissipation_, torsionFrictionCoefficient_, torsionFrictionCoefficientStatic_, and torsionStiffness_.
setRollingDissipation()
void FrictionSpecies::setRollingDissipation (Mdouble new_dispt)
Allows the tangential viscosity to be changed.
 {
     if (new_dispt >= 0)
         rollingDissipation_ = new_dispt;
     else
     {
         logger(ERROR, "Error in setRollingDissipation");
     }
 }
References ERROR, logger, and rollingDissipation_.
Referenced by BoundariesSelfTest::BoundariesSelfTest(), ParameterStudy1DDemo::createSpecies(), ParameterStudy2DDemo::createSpecies(), FluxAndPeriodicBoundarySelfTest::FluxAndPeriodicBoundarySelfTest(), FluxBoundarySelfTest::FluxBoundarySelfTest(), main(), MinimalExampleDrum::MinimalExampleDrum(), RotatingDrumBidisperseInitialise::RotatingDrumBidisperseInitialise(), Drum::setupInitialConditions(), MarbleRun::setupInitialConditions(), and Siegen::Siegen().
setRollingFrictionCoefficient()
void FrictionSpecies::setRollingFrictionCoefficient (Mdouble new_mu)
Allows the (dynamic) Coulomb friction coefficient to be changed; also sets mu_s by default.
 {
     if (new_mu >= 0)
     {
         rollingFrictionCoefficient_ = new_mu;
         rollingFrictionCoefficientStatic_ = rollingFrictionCoefficient_;
     }
     else
         logger(ERROR, "[FrictionSpecies::setRollingFrictionCoefficient(Mdouble)] The coefficient of friction must be nonnegative.");
 }
References ERROR, logger, rollingFrictionCoefficient_, and rollingFrictionCoefficientStatic_.
Referenced by Slide::actionsBeforeTimeStep(), BoundariesSelfTest::BoundariesSelfTest(), ParameterStudy1DDemo::createSpecies(), ParameterStudy2DDemo::createSpecies(), FluxAndPeriodicBoundarySelfTest::FluxAndPeriodicBoundarySelfTest(), FluxBoundarySelfTest::FluxBoundarySelfTest(), main(), MinimalExampleDrum::MinimalExampleDrum(), RotatingDrumBidisperseInitialise::RotatingDrumBidisperseInitialise(), MarbleRun::setRollingFrictionCoefficient(), Drum::setupInitialConditions(), PeriodicWallsWithSlidingFrictionUnitTest::setupInitialConditions(), and Siegen::Siegen().
setRollingFrictionCoefficientStatic()
void FrictionSpecies::setRollingFrictionCoefficientStatic (Mdouble new_mu)
Allows the static Coulomb rolling friction coefficient to be changed.
Allows the static Coulomb friction coefficient to be changed; also sets mu_s by default.
 {
     if (new_mu >= 0)
     {
         rollingFrictionCoefficientStatic_ = new_mu;
     }
     else
         logger(ERROR, "[FrictionSpecies::setRollingFrictionCoefficientStatic(Mdouble)] The coefficient of friction must be nonnegative.");
 }
References ERROR, logger, and rollingFrictionCoefficientStatic_.
setRollingStiffness()
void FrictionSpecies::setRollingStiffness (Mdouble new_kt)
Allows the spring constant to be changed.
 {
     if (new_kt >= 0)
     {
         rollingStiffness_ = new_kt;
     }
     else
     {
         logger(ERROR, "Error in setRollingStiffness");
     }
 }
References ERROR, logger, and rollingStiffness_.
Referenced by BoundariesSelfTest::BoundariesSelfTest(), ParameterStudy1DDemo::createSpecies(), ParameterStudy2DDemo::createSpecies(), FluxAndPeriodicBoundarySelfTest::FluxAndPeriodicBoundarySelfTest(), FluxBoundarySelfTest::FluxBoundarySelfTest(), main(), MinimalExampleDrum::MinimalExampleDrum(), RotatingDrumBidisperseInitialise::RotatingDrumBidisperseInitialise(), Drum::setupInitialConditions(), MarbleRun::setupInitialConditions(), PeriodicWallsWithSlidingFrictionUnitTest::setupInitialConditions(), and Siegen::Siegen().
setTorsionDissipation()
void FrictionSpecies::setTorsionDissipation (Mdouble new_dispt)
Allows the torsion viscosity to be changed.
Allows the tangential viscosity to be changed.
 {
     if (new_dispt >= 0)
         torsionDissipation_ = new_dispt;
     else
     {
         logger(ERROR, "Error in setTorsionDissipation");
     }
 }
References ERROR, logger, and torsionDissipation_.
Referenced by BoundariesSelfTest::BoundariesSelfTest(), FluxAndPeriodicBoundarySelfTest::FluxAndPeriodicBoundarySelfTest(), FluxBoundarySelfTest::FluxBoundarySelfTest(), MarbleRun::setupInitialConditions(), and Siegen::Siegen().
setTorsionFrictionCoefficient()
void FrictionSpecies::setTorsionFrictionCoefficient (Mdouble new_mu)
Allows the (dynamic) Coulomb torsion friction coefficient to be changed; also sets mu_s by default.
Allows the (dynamic) Coulomb friction coefficient to be changed; also sets mu_s by default.
 {
     if (new_mu >= 0)
     {
         torsionFrictionCoefficient_ = new_mu;
         torsionFrictionCoefficientStatic_ = torsionFrictionCoefficient_;
     }
     else
     {
         logger(ERROR, "Error in setSlidingFrictionCoefficient");
     }
 }
References ERROR, logger, torsionFrictionCoefficient_, and torsionFrictionCoefficientStatic_.
Referenced by Slide::actionsBeforeTimeStep(), BoundariesSelfTest::BoundariesSelfTest(), ParameterStudy1DDemo::createSpecies(), ParameterStudy2DDemo::createSpecies(), FluxAndPeriodicBoundarySelfTest::FluxAndPeriodicBoundarySelfTest(), FluxBoundarySelfTest::FluxBoundarySelfTest(), main(), MarbleRun::setTorsionFrictionCoefficient(), PeriodicWallsWithSlidingFrictionUnitTest::setupInitialConditions(), and Siegen::Siegen().
setTorsionFrictionCoefficientStatic()
void FrictionSpecies::setTorsionFrictionCoefficientStatic (Mdouble new_mu)
Allows the static Coulomb torsion friction coefficient to be accessed.
Allows the static Coulomb friction coefficient to be changed; also sets mu_s by default.
 {
     if (new_mu >= 0)
     {
         torsionFrictionCoefficientStatic_ = new_mu;
     }
     else
     {
         logger(ERROR, "Error in setSlidingFrictionCoefficientStatic");
     }
 }
References ERROR, logger, and torsionFrictionCoefficientStatic_.
setTorsionStiffness()
void FrictionSpecies::setTorsionStiffness (Mdouble new_kt)
Allows the torsion stiffness to be changed.
Allows the spring constant to be changed.
 {
     if (new_kt >= 0)
     {
         torsionStiffness_ = new_kt;
     }
     else
     {
         logger(ERROR, "Error in setTorsionStiffness");
     }
 }
References ERROR, logger, and torsionStiffness_.
Referenced by BoundariesSelfTest::BoundariesSelfTest(), ParameterStudy1DDemo::createSpecies(), ParameterStudy2DDemo::createSpecies(), FluxAndPeriodicBoundarySelfTest::FluxAndPeriodicBoundarySelfTest(), FluxBoundarySelfTest::FluxBoundarySelfTest(), main(), MarbleRun::setupInitialConditions(), PeriodicWallsWithSlidingFrictionUnitTest::setupInitialConditions(), and Siegen::Siegen().
write()
void FrictionSpecies::write (std::ostream & os) const
Writes the species properties to an output stream.
Parameters
[out] os output stream (typically the restart file)
 {
     SlidingFrictionSpecies::write(os);
     os << " rollingStiffness " << rollingStiffness_;
     os << " rollingDissipation " << rollingDissipation_;
     os << " rollingFrictionCoefficient " << rollingFrictionCoefficient_;
     os << " rollingFrictionCoefficientStatic " << rollingFrictionCoefficientStatic_;
     os << " torsionStiffness " << torsionStiffness_;
     os << " torsionDissipation " << torsionDissipation_;
     os << " torsionFrictionCoefficient " << torsionFrictionCoefficient_;
     os << " torsionFrictionCoefficientStatic " << torsionFrictionCoefficientStatic_;
 }
References rollingDissipation_, rollingFrictionCoefficient_, rollingFrictionCoefficientStatic_, rollingStiffness_, torsionDissipation_, torsionFrictionCoefficient_, torsionFrictionCoefficientStatic_, torsionStiffness_, and SlidingFrictionSpecies::write().
Member Data Documentation
rollingDissipation_
Mdouble FrictionSpecies::rollingDissipation_ private
rolling dissipation coefficient.
Typically set to 2/5 of the normal force dissipation, as both the tangential and the normal spring have the same restitution coefficients (if the rolling and normal stiffnesses also have a ratio of 2/5).
Referenced by FrictionSpecies(), getRollingDissipation(), mix(), read(), setRollingDissipation(), and write().
rollingFrictionCoefficient_
Mdouble FrictionSpecies::rollingFrictionCoefficient_ private
(dynamic) Coulomb rolling friction coefficient.
Referenced by FrictionSpecies(), getRollingFrictionCoefficient(), mix(), read(), setRollingFrictionCoefficient(), and write().
rollingFrictionCoefficientStatic_
Mdouble FrictionSpecies::rollingFrictionCoefficientStatic_ private
static Coulomb rolling friction coefficient
(by default set equal to the dynamic one).
Referenced by FrictionSpecies(), getRollingFrictionCoefficientStatic(), mix(), read(), setRollingFrictionCoefficient(), setRollingFrictionCoefficientStatic(), and write().
rollingStiffness_
Mdouble FrictionSpecies::rollingStiffness_ private
rolling stiffness.
Typically set to 2/5 of the stiffness of the normal force, as
both the rolling and the normal spring have the same oscillation
frequency (and thus require the same timeStep)in this case.
Referenced by FrictionSpecies(), getRollingStiffness(), mix(), read(), setRollingStiffness(), and write().
torsionDissipation_
Mdouble FrictionSpecies::torsionDissipation_ private
rolling dissipation coefficient.
Typically set to 2/5 of the normal force dissipation, as both the tangential and the normal spring have the same restitution coefficients (if the rolling and normal stiffnesses also have a ratio of 2/5).
Referenced by FrictionSpecies(), getTorsionDissipation(), mix(), read(), setTorsionDissipation(), and write().
torsionFrictionCoefficient_
Mdouble FrictionSpecies::torsionFrictionCoefficient_ private
(dynamic) Coulomb torsion friction coefficient.
Referenced by FrictionSpecies(), getTorsionFrictionCoefficient(), mix(), read(), setTorsionFrictionCoefficient(), and write().
torsionFrictionCoefficientStatic_
Mdouble FrictionSpecies::torsionFrictionCoefficientStatic_ private
static Coulomb torsion friction coefficient
(by default set equal to the dynamic one).
Referenced by FrictionSpecies(), getTorsionFrictionCoefficientStatic(), mix(), read(), setTorsionFrictionCoefficient(), setTorsionFrictionCoefficientStatic(), and write().
torsionStiffness_
Mdouble FrictionSpecies::torsionStiffness_ private
rolling stiffness.
Typically set to 2/5 of the stiffness of the normal force, as
both the rolling and the normal spring have the same oscillation
frequency (and thus require the same timeStep)in this case.
Referenced by FrictionSpecies(), getTorsionStiffness(), mix(), read(), setTorsionStiffness(), and write().
The documentation for this class was generated from the following files:
FrictionSpecies.h
FrictionSpecies.cc