MercuryDPM: Eigen::internal::generic_reciprocal_newton_step< Packet, Steps > Struct Template Reference
Eigen::internal::generic_reciprocal_newton_step< Packet, Steps > Struct Template Reference
#include <MathFunctionsImpl.h>
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet run (const Packet &a, const Packet &approx_a_recip)
Detailed Description
template<typename Packet, int Steps>
struct Eigen::internal::generic_reciprocal_newton_step< Packet, Steps >
Fast reciprocal using Newton-Raphson's method.
Preconditions:
The starting guess provided in approx_a_recip must have at least half the leading mantissa bits in the correct result, such that a single Newton-Raphson step is sufficient to get within 1-2 ulps of the correct result.
If a is zero, approx_a_recip must be infinite with the same sign as a.
If a is infinite, approx_a_recip must be zero with the same sign as a.
If the preconditions are satisfied, which they are for for the _*_rcp_ps instructions on x86, the result has a maximum relative error of 2 ulps, and correctly handles reciprocals of zero, infinity, and NaN.
Member Function Documentation
run()
template<typename Packet , int Steps> static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet Eigen::internal::generic_reciprocal_newton_step< Packet, Steps >::run (const Packet & a, const Packet & approx_a_recip) inline static
{
     using Scalar = typename unpacket_traits<Packet>::type;
     const Packet two = pset1<Packet>(Scalar(2));
     // Refine the approximation using one Newton-Raphson step:
     //   x_{i} = x_{i-1} * (2 - a * x_{i-1})
     const Packet x = generic_reciprocal_newton_step<Packet, Steps - 1>::run(a, approx_a_recip);
     const Packet tmp = pnmadd(a, x, two);
     // If tmp is NaN, it means that a is either +/-0 or +/-Inf.
     // In this case return the approximation directly.
     const Packet is_not_nan = pcmp_eq(tmp, tmp);
     return pselect(is_not_nan, pmul(x, tmp), x);
   }
References a, Eigen::internal::pcmp_eq(), Eigen::internal::pmul(), Eigen::internal::pnmadd(), Eigen::internal::pselect(), tmp, and plotDoE::x.
The documentation for this struct was generated from the following file:
MathFunctionsImpl.h