MercuryDPM: Eigen::internal::ppolevl< Packet, N > Struct Template Reference
Eigen::internal::ppolevl< Packet, N > Struct Template Reference
#include <GenericPacketMathFunctions.h>
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet run (const Packet &x, const typename unpacket_traits< Packet >::type coeff[])
Member Function Documentation
run()
template<typename Packet , int N> static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet Eigen::internal::ppolevl< Packet, N >::run (const Packet & x, const typename unpacket_traits< Packet >::type coeff[]) inline static
{
     EIGEN_STATIC_ASSERT((N > 0), YOU_MADE_A_PROGRAMMING_MISTAKE);
     return pmadd(ppolevl<Packet, N - 1>::run(x, coeff), x, pset1<Packet>(coeff[N]));
   }
References EIGEN_STATIC_ASSERT, N, Eigen::internal::pmadd(), and plotDoE::x.
Referenced by Eigen::internal::erf_over_x_double_small(), Eigen::internal::erfc_double_large(), Eigen::internal::accurate_log2< float >::operator()(), Eigen::internal::pasin_float(), Eigen::internal::patanh_double(), Eigen::internal::patanh_float(), Eigen::internal::plog_impl_float(), Eigen::internal::ptanh_double(), Eigen::internal::ptanh_float(), Eigen::internal::digamma_impl_maybe_poly< double >::run(), Eigen::internal::digamma_impl_maybe_poly< float >::run(), Eigen::internal::patan_reduced< Scalar >::run(), Eigen::internal::generic_fast_erf< Scalar >::run(), and Eigen::internal::generic_fast_erfc< Scalar >::run().
The documentation for this struct was generated from the following file:
GenericPacketMathFunctions.h