MercuryDPM: unstructured_three_d_fluid.cc File Reference
unstructured_three_d_fluid.cc File Reference
#include "generic.h"
#include "constitutive.h"
#include "navier_stokes.h"
#include "meshes/tetgen_mesh.h"
Classes
class UnstructuredFluidProblem< ELEMENT >
Unstructured Navier-Stokes ALE Problem.
Namespaces
Global_Parameters
Namespace for global parameters.
Functions
void Global_Parameters::prescribed_inflow_traction (const double &t, const Vector< double > &x, const Vector< double > &n, Vector< double > &traction)
Applied traction on fluid at the inflow boundary.
void Global_Parameters::prescribed_outflow_traction (const double &t, const Vector< double > &x, const Vector< double > &n, Vector< double > &traction)
Applied traction on fluid at the inflow boundary.
int main (int argc, char **argv)
Demonstrate how to solve an unstructured 3D fluids problem.
Function Documentation
main()
int main (int argc , char ** argv)
Demonstrate how to solve an unstructured 3D fluids problem.
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Label for output
  DocInfo doc_info;
  // Parameter study
  double Re_increment=100.0;
  unsigned nstep=4;
  if (CommandLineArgs::Argc==2)
   {
    std::cout << "Validation -- only doing two steps" << std::endl;
    nstep=2;
   }
  //Taylor--Hood
  {
   // Output directory
   doc_info.set_directory("RESLT_TH");
   //Set up the problem
   UnstructuredFluidProblem<TTaylorHoodElement<3> > problem;
   //Output initial guess
   problem.doc_solution(doc_info);
   doc_info.number()++;
   // Parameter study: Crank up the pressure drop along the vessel
   for (unsigned istep=0;istep<nstep;istep++)
    {
     // Solve the problem
     problem.newton_solve();
     //Output solution
     problem.doc_solution(doc_info);
     doc_info.number()++;
     // Bump up Reynolds number (equivalent to increasing the imposed pressure
     // drop)
     Global_Parameters::Re+=Re_increment;
    }
  }
  //Crouzeix Raviart
  {
   //Reset to default Reynolds number
   Global_Parameters::Re = 100.0;
   //Reset doc info number
   doc_info.number()=0;
   // Output directory
   doc_info.set_directory("RESLT_CR");
   //Set up the problem
   UnstructuredFluidProblem<TCrouzeixRaviartElement<3> > problem;
   //Output initial guess
   problem.doc_solution(doc_info);
   doc_info.number()++;
   // Parameter study: Crank up the pressure drop along the vessel
   for (unsigned istep=0;istep<nstep;istep++)
    {
     // Solve the problem
     problem.newton_solve();
     //Output solution
     problem.doc_solution(doc_info);
     doc_info.number()++;
     // Bump up Reynolds number (equivalent to increasing the imposed pressure
     // drop)
     Global_Parameters::Re+=Re_increment;
    }
  }
 } // end_of_main
References oomph::CommandLineArgs::Argc, oomph::DocInfo::number(), problem, Global_Parameters::Re, oomph::DocInfo::set_directory(), and Flag_definition::setup().