MercuryDPM: ParabolaChute Class Reference
ParabolaChute Class Reference
#include <ParabolaChute.h>
Public Member Functions
ParabolaChute ()
Default constructor, sets a chute with default parameters.
ParabolaChute (const ParabolaChute &other)
Copy constructor.
ParabolaChute (Mdouble length, Mdouble widthscale)
Constructor in which all parameters are set.
~ParabolaChute () override
void set (Mdouble length, Mdouble widthscale)
ParabolaChute * copy () const override
Pure virtual function that can be overwritten in inherited classes in order to copy a BaseWall.
bool getDistanceAndNormal (const BaseParticle &P, Mdouble &distance, Vec3D &normal_return) const override
Pure virtual function that computes the distance of a BaseParticle to this wall and returns the normal of this wall if there is a collision.
BaseInteraction * getInteractionWith (BaseParticle *p, unsigned timeStamp, InteractionHandler *interactionHandler) override
Returns the interaction between this wall and a given particle, nullptr if there is no interaction.
void read (std::istream &is) override
Function that reads a BaseWall from an input stream, usually a restart file.
void write (std::ostream &os) const override
Function that writes a BaseWall to an output stream, usually a restart file.
std::string getName () const override
A purely virtual function.
Public Member Functions inherited from BaseWall
BaseWall ()
Default constructor.
BaseWall (const BaseWall &w)
Copy constructor.
~BaseWall () override
Default destructor.
virtual bool getDistanceNormalOverlap (const BaseParticle &P, Mdouble &distance, Vec3D &normal_return, Mdouble &overlap) const
virtual bool getDistanceNormalOverlapSuperquadric (const SuperQuadricParticle &p, Mdouble &distance, Vec3D &normal_return, Mdouble &overlap) const
virtual Vec3D getFurthestPointSuperQuadric (const Vec3D &normalBodyFixed, const Vec3D &axes, Mdouble eps1, Mdouble eps2) const
virtual void setHandler (WallHandler *handler)
A function which sets the WallHandler for this BaseWall.
WallHandler * getHandler () const
A function which returns the WallHandler that handles this BaseWall.
void setIndSpecies (unsigned int indSpecies) override
Define the species of this wall using the index of the species in the SpeciesHandler in this DPMBase.
void setSpecies (const ParticleSpecies *species)
Defines the species of the current wall.
bool isFixed () const override
void setForceControl (Vec3D forceGoal, Vec3D gainFactor, Vec3D baseVelocity={0, 0, 0})
Slowly adjusts the force on a wall towards a specified goal, by adjusting (prescribing) the velocity of the wall.
virtual bool isLocal (Vec3D &min, Vec3D &max) const
bool getLinePlaneIntersect (Vec3D &intersect, const Vec3D &p0, const Vec3D &p1, const Vec3D &n, const Vec3D &p)
bool isInsideWallVTK (const Vec3D &point, const Vec3D &normal, const Vec3D &position) const
void projectOntoWallVTK (Vec3D &point0, const Vec3D &point1, const Vec3D &normal, const Vec3D &position) const
void intersectVTK (std::vector< Vec3D > &points, Vec3D normal, Vec3D position) const
virtual BaseInteraction * getInteractionWithSuperQuad (SuperQuadricParticle *p, unsigned timeStamp, InteractionHandler *interactionHandler)
virtual void writeVTK (VTKContainer &vtk) const
void getVTK (std::vector< Vec3D > &points, std::vector< std::vector< double >> &triangleStrips)
const Vec3D getAxis () const
virtual void actionsOnRestart ()
No implementation but can be overidden in its derived classes.
virtual void actionsAfterParticleGhostUpdate ()
No implementation but can be overidden in its derived classes.
virtual void handleParticleAddition (unsigned int id, BaseParticle *p)
Handles the addition of particles to the particleHandler.
virtual void handleParticleRemoval (unsigned int id)
Handles the addition of particles to the particleHandler.
virtual void checkInteractions (InteractionHandler *interactionHandler, unsigned int timeStamp)
Check if all interactions are valid.
bool getVTKVisibility () const
void setVTKVisibility (bool vtkVisibility)
void addRenderedWall (BaseWall *w)
BaseWall * getRenderedWall (size_t i) const
std::vector< BaseWall * > getRenderedWalls () const
void removeRenderedWalls ()
void renderWall (VTKContainer &vtk)
void addParticlesAtWall (unsigned numElements=50)
void setVelocityControl (Vec3D forceGoal, Vec3D gainFactor, Vec3D baseVelocity)
virtual void writeWallDetailsVTK (VTKData &data) const
virtual void computeWear ()
Public Member Functions inherited from BaseInteractable
BaseInteractable ()
Default BaseInteractable constructor.
BaseInteractable (const BaseInteractable &p)
Copy constructor.
~BaseInteractable () override
Destructor, it simply destructs the BaseInteractable and all the objects it contains.
unsigned int getIndSpecies () const
Returns the index of the species associated with the interactable object.
const ParticleSpecies * getSpecies () const
Returns a pointer to the species of this BaseInteractable.
void setSpecies (const ParticleSpecies *species)
Sets the species of this BaseInteractable.
const Vec3D & getForce () const
Returns the force on this BaseInteractable.
const Vec3D & getTorque () const
Returns the torque on this BaseInteractable.
void setForce (const Vec3D &force)
Sets the force on this BaseInteractable.
void setTorque (const Vec3D &torque)
Sets the torque on this BaseInteractable.
void addForce (const Vec3D &addForce)
Adds an amount to the force on this BaseInteractable.
void addTorque (const Vec3D &addTorque)
Adds an amount to the torque on this BaseInteractable.
virtual void resetForceTorque (int numberOfOMPthreads)
void sumForceTorqueOMP ()
const Vec3D & getPosition () const
Returns the position of this BaseInteractable.
const Quaternion & getOrientation () const
Returns the orientation of this BaseInteractable.
virtual void setPosition (const Vec3D &position)
Sets the position of this BaseInteractable.
void setOrientationViaNormal (Vec3D normal)
Sets the orientation of this BaseInteractable by defining the vector that results from the rotation of the (1,0,0) vector.
void setOrientationViaEuler (Vec3D eulerAngle)
Sets the orientation of this BaseInteractable by defining the euler angles.
virtual void setOrientation (const Quaternion &orientation)
Sets the orientation of this BaseInteractable.
virtual void move (const Vec3D &move)
Moves this BaseInteractable by adding an amount to the position.
virtual void rotate (const Vec3D &angularVelocityDt)
Rotates this BaseInteractable.
const std::vector< BaseInteraction * > & getInteractions () const
Returns a list of interactions which belong to this interactable.
void addInteraction (BaseInteraction *I)
Adds an interaction to this BaseInteractable.
bool removeInteraction (BaseInteraction *I)
Removes an interaction from this BaseInteractable.
void copyInteractionsForPeriodicParticles (const BaseInteractable &p)
Copies interactions to this BaseInteractable whenever a periodic copy made.
void setVelocity (const Vec3D &velocity)
set the velocity of the BaseInteractable.
void setAngularVelocity (const Vec3D &angularVelocity)
set the angular velocity of the BaseInteractble.
void addVelocity (const Vec3D &velocity)
adds an increment to the velocity.
void addAngularVelocity (const Vec3D &angularVelocity)
add an increment to the angular velocity.
virtual const Vec3D & getVelocity () const
Returns the velocity of this interactable.
virtual const Vec3D & getAngularVelocity () const
Returns the angular velocity of this interactable.
void setPrescribedPosition (const std::function< Vec3D(double)> &prescribedPosition)
Allows the position of an infinite mass interactable to be prescribed.
void applyPrescribedPosition (double time)
Computes the position from the user defined prescribed position function.
void setPrescribedVelocity (const std::function< Vec3D(double)> &prescribedVelocity)
Allows the velocity of an infinite mass interactable to be prescribed.
void applyPrescribedVelocity (double time)
Computes the velocity from the user defined prescribed velocity function.
void setPrescribedOrientation (const std::function< Quaternion(double)> &prescribedOrientation)
Allows the orientation of the infinite mass interactbale to be prescribed.
void applyPrescribedOrientation (double time)
Computes the orientation from the user defined prescribed orientation function.
void setPrescribedAngularVelocity (const std::function< Vec3D(double)> &prescribedAngularVelocity)
Allows the angular velocity of the infinite mass interactable to be prescribed.
void applyPrescribedAngularVelocity (double time)
Computes the angular velocity from the user defined prescribed angular velocity.
virtual const Vec3D getVelocityAtContact (const Vec3D &contact) const
Returns the velocity at the contact point, use by many force laws.
void integrateBeforeForceComputation (double time, double timeStep)
This is part of integrate routine for objects with infinite mass.
void integrateAfterForceComputation (double time, double timeStep)
This is part of the integration routine for objects with infinite mass.
virtual Mdouble getInvMass () const
virtual Mdouble getCurvature (const Vec3D &labFixedCoordinates) const
virtual bool isFaceContact (const Vec3D &normal) const
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Private Attributes
Mdouble l_
Mdouble ws_
Additional Inherited Members
Static Public Member Functions inherited from BaseWall
static void addToVTK (const std::vector< Vec3D > &points, VTKContainer &vtk)
Takes the points provided and adds a triangle strip connecting these points to the vtk container.
Detailed Description
Parabolic chute Based on the Coil class
Constructor & Destructor Documentation
ParabolaChute() [1/3]
ParabolaChute::ParabolaChute ()
Default constructor, sets a chute with default parameters.
 {
     l_ = 1.0;
     ws_ = 1.0;
     logger(DEBUG, "ParabolaChute() constructor finished");
 }
References DEBUG, l_, logger, and ws_.
ParabolaChute() [2/3]
ParabolaChute::ParabolaChute (const ParabolaChute & other)
Copy constructor.
                                                        : BaseWall(other)
 {
     l_ = other.l_;
     ws_ = other.ws_;
     logger(DEBUG, "ParabolaChute copy constructor finished");
 }
References DEBUG, l_, logger, and ws_.
ParabolaChute() [3/3]
ParabolaChute::ParabolaChute (Mdouble length, Mdouble widthscale)
Constructor in which all parameters are set.
 {
     l_ = length;
     ws_ = widthscale;
     logger(DEBUG, "ParabolaChute(params) constructor finished");
 }
References DEBUG, l_, logger, and ws_.
~ParabolaChute()
ParabolaChute::~ParabolaChute () override
 {
     logger(DEBUG, "ParabolaChute destructor finished");
 }
References DEBUG, and logger.
Member Function Documentation
copy()
ParabolaChute* ParabolaChute::copy () const override virtual
Pure virtual function that can be overwritten in inherited classes in order to copy a BaseWall.
Returns
A pointer to the new BaseWall.
Implements BaseWall.
getDistanceAndNormal()
bool ParabolaChute::getDistanceAndNormal (const BaseParticle & P, Mdouble & distance, Vec3D & normal_return) const override virtual
Pure virtual function that computes the distance of a BaseParticle to this wall and returns the normal of this wall if there is a collision.
Beware, the distance and normal are output parameters, not return values!
Parameters
[in] P Reference to the BaseParticle we want to compute the distance to the BaseWall of.
[out] distance Distance of the BaseParticle to the BaseWall.
[out] normal_return The normal of the wall. Is only given if there is a collision.
Returns
A boolean which indicates if there is a collision between the BaseParticle and the wall.
Implements BaseWall.
 {
     /* Define some shortcuts */
     Mdouble y0 = p.getPosition().Y;
     Mdouble z0 = p.getPosition().Z;
     /* First, check whether the particle is definitely out of contact with the
      * chute. This will be so if the particle's interaction radius is small and
      * the particle's z-position is high. */
     // TODO do this properly
     if (false)
     {
         return false;
     }
     /* If not, then use Newton's method to minimise (half of the squared) distance */
     //Mdouble R; //TODO
     //Mdouble alpha; //TODO
     //Mdouble dz = p.getPosition().Z; //TODO
     Mdouble q = 0; // current guess
     Mdouble dd = 0; // derivative of half of the squared distance at current guess
     Mdouble ddd = 0; // second derivative at current guess
     //Mdouble q0 = dz / l_; // minimum of the parabolic part
     // Iterate according to Newton
     do
     {
         dd = -2 * pow(q, 3) / pow(ws_, 2) + (1 - 2 * z0 / ws_) * q - y0;
         ddd = 6 * pow(q / ws_, 2) + (1 - 2 * z0 / ws_);
         q -= dd / ddd;
     } while (fabs(dd / ddd) > 1e-14);
     // Check whether this location is actually on the parabolic chute, otherwise
     // a point collision with the end of the chute calculated
     Mdouble distanceSquared = pow(q - y0, 2) + pow(pow(q, 2) / ws_ - z0, 2);
     // TODO
     if (distanceSquared >= mathsFunc::square(p.getWallInteractionRadius(this)))
     {
         return false;
     }
     else
     {
         Vec3D ContactPoint;
         distance = sqrt(distanceSquared);
         // ContactPoint.X = // TODO
         normal_return = ContactPoint - p.getPosition();
         normal_return /= normal_return.getLength();
         return true;
     }
 }
References e(), boost::multiprecision::fabs(), Vec3D::getLength(), p, Eigen::bfloat16_impl::pow(), Eigen::numext::q, sqrt(), mathsFunc::square(), and ws_.
getInteractionWith()
BaseInteraction* ParabolaChute::getInteractionWith (BaseParticle * p, unsigned timeStamp, InteractionHandler * interactionHandler) override virtual
Returns the interaction between this wall and a given particle, nullptr if there is no interaction.
Parameters
[in] p Pointer to the BaseParticle which we want to check the interaction for.
[in] timeStamp The time at which we want to look at the interaction.
[in] interactionHandler A pointer to the InteractionHandler in which the interaction can be found.
Returns
A pointer to the BaseInteraction that happened between this BaseWall and the BaseParticle at the timeStamp.
Reimplemented from BaseWall.
getName()
std::string ParabolaChute::getName () const override virtual
A purely virtual function.
Implements BaseObject.
read()
void ParabolaChute::read (std::istream & is) override virtual
Function that reads a BaseWall from an input stream, usually a restart file.
The BaseWall takes no more information than for a BaseInteractable. (A derived class' read method does most of the work.)
Parameters
[in] is - The input stream from which the BaseWall is read.
Reimplemented from BaseWall.
set()
void ParabolaChute::set (Mdouble length, Mdouble widthscale)
 {
     l_ = length;
     ws_ = widthscale;
 }
References l_, and ws_.
write()
void ParabolaChute::write (std::ostream & os) const override virtual
Function that writes a BaseWall to an output stream, usually a restart file.
Reimplemented from BaseWall.
Member Data Documentation
l_
Mdouble ParabolaChute::l_ private
Referenced by ParabolaChute(), and set().
ws_
Mdouble ParabolaChute::ws_ private
Referenced by getDistanceAndNormal(), ParabolaChute(), and set().
The documentation for this class was generated from the following files:
ParabolaChute.h
ParabolaChute.cc