MercuryDPM: oomph::PMLCornerQuadMesh< ELEMENT > Class Template Reference
oomph::PMLCornerQuadMesh< ELEMENT > Class Template Reference
PML mesh, derived from RectangularQuadMesh.
#include <pml_meshes.h>
Public Member Functions
PMLCornerQuadMesh (Mesh *PMLQuad_mesh_x_pt, Mesh *PMLQuad_mesh_y_pt, Mesh *bulk_mesh_pt, Node *special_corner_node_pt, const unsigned &parent_boundary_x_id, const unsigned &parent_boundary_y_id, const unsigned &current_boundary_x_id, const unsigned &current_boundary_y_id, const unsigned &n_pml_x, const unsigned &n_pml_y, const double &x_pml_start, const double &x_pml_end, const double &y_pml_start, const double &y_pml_end, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Public Member Functions inherited from oomph::PMLQuadMeshBase< ELEMENT >
PMLQuadMeshBase (const unsigned &n_pml_x, const unsigned &n_pml_y, const double &x_pml_start, const double &x_pml_end, const double &y_pml_start, const double &y_pml_end, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor: Create the underlying rectangular quad mesh.
void pml_locate_zeta (const Vector< double > &x, FiniteElement *&coarse_mesh_el_pt)
Public Member Functions inherited from oomph::RectangularQuadMesh< ELEMENT >
RectangularQuadMesh (const unsigned &nx, const unsigned &ny, const double &lx, const double &ly, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
RectangularQuadMesh (const unsigned &nx, const unsigned &ny, const double &xmin, const double &xmax, const double &ymin, const double &ymax, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
RectangularQuadMesh (const unsigned &nx, const unsigned &ny, const double &lx, const double &ly, const bool &periodic_in_x, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
RectangularQuadMesh (const unsigned &nx, const unsigned &ny, const double &xmin, const double &xmax, const double &ymin, const double &ymax, const bool &periodic_in_x, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
const unsigned & nx () const
Return number of elements in x direction.
const unsigned & ny () const
Return number of elements in y direction.
const double x_min () const
Return the minimum value of x coordinate.
const double x_max () const
Return the maximum value of x coordinate.
const double y_min () const
Return the minimum value of y coordinate.
const double y_max () const
Return the maximum value of y coordinate.
virtual void element_reorder ()
virtual double x_spacing_function (unsigned xelement, unsigned xnode, unsigned yelement, unsigned ynode)
virtual double y_spacing_function (unsigned xelement, unsigned xnode, unsigned yelement, unsigned ynode)
Public Member Functions inherited from oomph::QuadMeshBase
QuadMeshBase ()
Constructor (empty)
QuadMeshBase (const QuadMeshBase &node)=delete
Broken copy constructor.
void operator= (const QuadMeshBase &)=delete
Broken assignment operator.
virtual ~QuadMeshBase ()
Destructor (empty)
void setup_boundary_element_info ()
void setup_boundary_element_info (std::ostream &outfile)
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void node_update (const bool &update_all_solid_nodes=false)
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Protected Member Functions inherited from oomph::RectangularQuadMesh< ELEMENT >
void build_mesh (TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Generic mesh construction function: contains all the hard work.
RectangularQuadMesh (const unsigned &nx, const unsigned &ny, const double &xmin, const double &xmax, const double &ymin, const double &ymax, const bool &periodic_in_x, const bool &build, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Protected Attributes inherited from oomph::RectangularQuadMesh< ELEMENT >
unsigned Nx
Nx: number of elements in x-direction.
unsigned Ny
Ny: number of elements in y-direction.
unsigned Np
Np: number of (linear) points in the element.
double Xmin
Minimum value of x coordinate.
double Xmax
Maximum value of x coordinate.
double Ymin
Minimum value of y coordinate.
double Ymax
Maximum value of y coordinate.
bool Xperiodic
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Detailed Description
template<class ELEMENT>
class oomph::PMLCornerQuadMesh< ELEMENT >
PML mesh, derived from RectangularQuadMesh.
/////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
Constructor & Destructor Documentation
PMLCornerQuadMesh()
template<class ELEMENT > oomph::PMLCornerQuadMesh< ELEMENT >::PMLCornerQuadMesh (Mesh * PMLQuad_mesh_x_pt, Mesh * PMLQuad_mesh_y_pt, Mesh * bulk_mesh_pt, Node * special_corner_node_pt, const unsigned & parent_boundary_x_id, const unsigned & parent_boundary_y_id, const unsigned & current_boundary_x_id, const unsigned & current_boundary_y_id, const unsigned & n_pml_x, const unsigned & n_pml_y, const double & x_pml_start, const double & x_pml_end, const double & y_pml_start, const double & y_pml_end, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) inline
Constructor: Pass pointer to "bulk" mesh and the two existing PML meshes in order to construct the corner PML mesh in between them based on their element number and coordinates.
Simple interior node numbering helpers to be precomputed before the main loop
Top left node in element
Lower right node in element
Top right node in element
       : PMLQuadMeshBase<ELEMENT>(n_pml_x,
                                  n_pml_y,
                                  x_pml_start,
                                  x_pml_end,
                                  y_pml_start,
                                  y_pml_end,
                                  time_stepper_pt)
     {
       unsigned nnode_1d = this->finite_element_pt(0)->nnode_1d();
       unsigned interior_node_nr_helper_1 = nnode_1d * (nnode_1d - 1);
       unsigned interior_node_nr_helper_2 = nnode_1d - 1;
       unsigned interior_node_nr_helper_3 = nnode_1d * nnode_1d - 1;
       // Set up top right corner element
       //--------------------------------
       if ((parent_boundary_x_id == 2) && (parent_boundary_y_id == 1))
       {
         // Get the number of nodes to be connected on the horizontal boundary
         unsigned n_boundary_x_node =
           PMLQuad_mesh_x_pt->nboundary_node(parent_boundary_x_id);
         // Create a vector of ordered boundary nodes
         Vector<Node*> ordered_boundary_x_node_pt(n_boundary_x_node);
         // Fill the vector with the nodes on the respective boundary
         for (unsigned n = 0; n < n_boundary_x_node; n++)
         {
           ordered_boundary_x_node_pt[n] =
             PMLQuad_mesh_x_pt->boundary_node_pt(parent_boundary_x_id, n);
         }
         // Sort them from lowest to highest (in x coordinate)
         if (parent_boundary_x_id == 2)
         {
           std::sort(ordered_boundary_x_node_pt.begin(),
                     ordered_boundary_x_node_pt.end(),
                     TwoDimensionalPMLHelper::sorter_top_boundary);
         }
         // Get the number of nodes to be connected on the vertical boundary
         unsigned n_boundary_y_node =
           PMLQuad_mesh_y_pt->nboundary_node(parent_boundary_y_id);
         // Create a vector of ordered boundary nodes
         Vector<Node*> ordered_boundary_y_node_pt(n_boundary_y_node);
         // Fill the vector with the nodes on the respective boundary
         for (unsigned n = 0; n < n_boundary_y_node; n++)
         {
           ordered_boundary_y_node_pt[n] =
             PMLQuad_mesh_y_pt->boundary_node_pt(parent_boundary_y_id, n);
         }
         // Sort them
         if (parent_boundary_y_id == 1)
         {
           std::sort(ordered_boundary_y_node_pt.begin(),
                     ordered_boundary_y_node_pt.end(),
                     TwoDimensionalPMLHelper::sorter_right_boundary);
         }
         unsigned x_nnod = this->nboundary_node(current_boundary_x_id);
         for (unsigned j = 0; j < x_nnod; j++)
         {
           this->boundary_node_pt(current_boundary_x_id, j)->set_obsolete();
         }
         unsigned y_nnod = this->nboundary_node(current_boundary_y_id);
         for (unsigned j = 0; j < y_nnod; j++)
         {
           this->boundary_node_pt(current_boundary_y_id, j)->set_obsolete();
         }
         // Kill the obsolete nodes
         this->prune_dead_nodes();
         unsigned n_pml_element = this->nelement();
         // Connect the elements in the pml mesh to the ones
         // in the triangular mesh at element level
         unsigned count = 0;
         if (parent_boundary_y_id == 1)
         {
           for (unsigned e = 0; e < n_pml_element; e++)
           {
             // If element is on the right boundary
             if ((e % n_pml_x) == 0)
             {
               // Upcast from GeneralisedElement to bulk element
               ELEMENT* el_pt = dynamic_cast<ELEMENT*>(this->element_pt(e));
               // Loop over all nodes in element
               unsigned n_node = el_pt->nnode();
               for (unsigned inod = 0; inod < n_node; inod++)
               {
                 // If it is one of the ones on the left boundary
                 if (e == 0)
                 {
                   if (inod == 0) el_pt->node_pt(inod) = special_corner_node_pt;
                   if ((inod % nnode_1d == 0) && (inod > 0))
                   {
                     // Get the pointer from the triangular mesh
                     el_pt->node_pt(inod) = ordered_boundary_y_node_pt[count];
                     count++;
                     // Node between two elements
                     if (inod == interior_node_nr_helper_1)
                     {
                       count--;
                     }
                   }
                 }
                 else
                 {
                   if ((inod % nnode_1d) == 0)
                   {
                     // Get the pointer from the triangular mesh
                     el_pt->node_pt(inod) = ordered_boundary_y_node_pt[count];
                     count++;
                     // Node between two elements
                     if (inod == interior_node_nr_helper_1)
                     {
                       count--;
                     }
                   }
                 }
               }
             }
           }
         }
         count = 0;
         if (parent_boundary_x_id == 2)
         {
           for (unsigned e = 0; e < n_pml_element; e++)
           {
             // If element is on the right boundary
             if ((int)(e / n_pml_x) == 0)
             {
               // Upcast from GeneralisedElement to bulk element
               ELEMENT* el_pt = dynamic_cast<ELEMENT*>(this->element_pt(e));
               // Loop over all nodes in element
               unsigned n_node = el_pt->nnode();
               for (unsigned inod = 0; inod < n_node; inod++)
               {
                 if (e == 0)
                 {
                   if (((int)(inod / nnode_1d) == 0) && (inod > 0))
                   {
                     // Get the pointer from the triangular mesh
                     el_pt->node_pt(inod) = ordered_boundary_x_node_pt[count];
                     count++;
                     // Node between two elements
                     if (inod == interior_node_nr_helper_2)
                     {
                       count--;
                     }
                   }
                 }
                 else
                 {
                   if ((int)(inod / nnode_1d) == 0)
                   {
                     // Get the pointer from the triangular mesh
                     el_pt->node_pt(inod) = ordered_boundary_x_node_pt[count];
                     count++;
                     // Node between two elements
                     if (inod == interior_node_nr_helper_2)
                     {
                       count--;
                     }
                   }
                 }
               }
             }
           }
         }
       }
       // Set up bottom right corner element
       //--------------------------------
       if ((parent_boundary_x_id == 0) && (parent_boundary_y_id == 1))
       {
         // Get the number of nodes to be connected on the horizontal boundary
         unsigned n_boundary_x_node =
           PMLQuad_mesh_x_pt->nboundary_node(parent_boundary_x_id);
         // Create a vector of ordered boundary nodes
         Vector<Node*> ordered_boundary_x_node_pt(n_boundary_x_node);
         // Fill the vector with the nodes on the respective boundary
         for (unsigned n = 0; n < n_boundary_x_node; n++)
         {
           ordered_boundary_x_node_pt[n] =
             PMLQuad_mesh_x_pt->boundary_node_pt(parent_boundary_x_id, n);
         }
         // Sort them from lowest to highest (in x coordinate)
         if (parent_boundary_x_id == 0)
         {
           std::sort(ordered_boundary_x_node_pt.begin(),
                     ordered_boundary_x_node_pt.end(),
                     TwoDimensionalPMLHelper::sorter_top_boundary);
         }
         // Get the number of nodes to be connected on the vertical boundary
         unsigned n_boundary_y_node =
           PMLQuad_mesh_y_pt->nboundary_node(parent_boundary_y_id);
         // Create a vector of ordered boundary nodes
         Vector<Node*> ordered_boundary_y_node_pt(n_boundary_y_node);
         // Fill the vector with the nodes on the respective boundary
         for (unsigned n = 0; n < n_boundary_y_node; n++)
         {
           ordered_boundary_y_node_pt[n] =
             PMLQuad_mesh_y_pt->boundary_node_pt(parent_boundary_y_id, n);
         }
         // Sort them
         if (parent_boundary_y_id == 1)
         {
           std::sort(ordered_boundary_y_node_pt.begin(),
                     ordered_boundary_y_node_pt.end(),
                     TwoDimensionalPMLHelper::sorter_right_boundary);
         }
         unsigned x_nnod = this->nboundary_node(current_boundary_x_id);
         for (unsigned j = 0; j < x_nnod; j++)
         {
           this->boundary_node_pt(current_boundary_x_id, j)->set_obsolete();
         }
         unsigned y_nnod = this->nboundary_node(current_boundary_y_id);
         for (unsigned j = 0; j < y_nnod; j++)
         {
           this->boundary_node_pt(current_boundary_y_id, j)->set_obsolete();
         }
         // Kill the obsolete nodes
         this->prune_dead_nodes();
         // Get the number of elements in the PML mesh
         unsigned n_pml_element = this->nelement();
         // Connect the elements in the pml mesh to the ones
         // in the triangular mesh at element level
         unsigned count = 0;
         if (parent_boundary_y_id == 1)
         {
           for (unsigned e = 0; e < n_pml_element; e++)
           {
             // If element is on the right boundary
             if ((e % n_pml_x) == 0)
             {
               // Upcast from GeneralisedElement to bulk element
               ELEMENT* el_pt = dynamic_cast<ELEMENT*>(this->element_pt(e));
               // Loop over all nodes in element
               unsigned n_node = el_pt->nnode();
               for (unsigned inod = 0; inod < n_node; inod++)
               {
                 if (e == ((n_pml_x) * (n_pml_y - 1)))
                 {
                   if (inod == interior_node_nr_helper_1)
                   {
                     el_pt->node_pt(inod) = special_corner_node_pt;
                   }
                   if ((inod % nnode_1d == 0) &&
                       (inod < interior_node_nr_helper_1))
                   {
                     // Get the pointer from the triangular mesh
                     el_pt->node_pt(inod) = ordered_boundary_y_node_pt[count];
                     count++;
                     // Node between two elements
                     if (inod == interior_node_nr_helper_1)
                     {
                       count--;
                     }
                   }
                 }
                 else
                 {
                   if ((inod % nnode_1d) == 0)
                   {
                     // Get the pointer from the triangular mesh
                     el_pt->node_pt(inod) = ordered_boundary_y_node_pt[count];
                     count++;
                     // Node between two elements
                     if (inod == interior_node_nr_helper_1)
                     {
                       count--;
                     }
                   }
                 }
               }
             }
           }
         }
         count = 0;
         if (parent_boundary_x_id == 0)
         {
           for (unsigned e = 0; e < n_pml_element; e++)
           {
             // If element is on the right boundary
             if (e >= ((n_pml_x - 0) * (n_pml_y - 1)))
             {
               // Upcast from GeneralisedElement to bulk element
               ELEMENT* el_pt = dynamic_cast<ELEMENT*>(this->element_pt(e));
               // Loop over all nodes in element
               unsigned n_node = el_pt->nnode();
               for (unsigned inod = 0; inod < n_node; inod++)
               {
                 if (e == ((n_pml_x) * (n_pml_y - 1)))
                 {
                   if (((unsigned)(inod / nnode_1d) ==
                        interior_node_nr_helper_2) &&
                       (inod > interior_node_nr_helper_1))
                   {
                     // Get the pointer from the triangular mesh
                     el_pt->node_pt(inod) = ordered_boundary_x_node_pt[count];
                     count++;
                     // Node between two elements
                     if (inod == interior_node_nr_helper_3)
                     {
                       count--;
                     }
                   }
                 }
                 else
                 {
                   if ((unsigned)(inod / nnode_1d) == interior_node_nr_helper_2)
                   {
                     // Get the pointer from the triangular mesh
                     el_pt->node_pt(inod) = ordered_boundary_x_node_pt[count];
                     count++;
                     // Node between two elements
                     if (inod == interior_node_nr_helper_3)
                     {
                       count--;
                     }
                   }
                 }
               }
             }
           }
         }
       }
       // Set up top left corner element
       //--------------------------------
       if ((parent_boundary_x_id == 2) && (parent_boundary_y_id == 3))
       {
         // Get the number of nodes to be connected on the horizontal boundary
         unsigned n_boundary_x_node =
           PMLQuad_mesh_x_pt->nboundary_node(parent_boundary_x_id);
         // Create a vector of ordered boundary nodes
         Vector<Node*> ordered_boundary_x_node_pt(n_boundary_x_node);
         // Fill the vector with the nodes on the respective boundary
         for (unsigned n = 0; n < n_boundary_x_node; n++)
         {
           ordered_boundary_x_node_pt[n] =
             PMLQuad_mesh_x_pt->boundary_node_pt(parent_boundary_x_id, n);
         }
         // Sort them from lowest to highest (in x coordinate)
         if (parent_boundary_x_id == 2)
         {
           std::sort(ordered_boundary_x_node_pt.begin(),
                     ordered_boundary_x_node_pt.end(),
                     TwoDimensionalPMLHelper::sorter_top_boundary);
         }
         // Get the number of nodes to be connected on the vertical boundary
         unsigned n_boundary_y_node =
           PMLQuad_mesh_y_pt->nboundary_node(parent_boundary_y_id);
         // Create a vector of ordered boundary nodes
         Vector<Node*> ordered_boundary_y_node_pt(n_boundary_y_node);
         // Fill the vector with the nodes on the respective boundary
         for (unsigned n = 0; n < n_boundary_y_node; n++)
         {
           ordered_boundary_y_node_pt[n] =
             PMLQuad_mesh_y_pt->boundary_node_pt(parent_boundary_y_id, n);
         }
         // Sort them from lowest to highest (in x coordinate)
         if (parent_boundary_y_id == 1)
         {
           std::sort(ordered_boundary_y_node_pt.begin(),
                     ordered_boundary_y_node_pt.end(),
                     TwoDimensionalPMLHelper::sorter_right_boundary);
         }
         unsigned x_nnod = this->nboundary_node(current_boundary_x_id);
         for (unsigned j = 0; j < x_nnod; j++)
         {
           this->boundary_node_pt(current_boundary_x_id, j)->set_obsolete();
         }
         unsigned y_nnod = this->nboundary_node(current_boundary_y_id);
         for (unsigned j = 0; j < y_nnod; j++)
         {
           this->boundary_node_pt(current_boundary_y_id, j)->set_obsolete();
         }
         // Kill the obsolete nodes
         this->prune_dead_nodes();
         // Get the number of elements in the PML mesh
         unsigned n_pml_element = this->nelement();
         // Connect the elements in the pml mesh to the ones
         // in the triangular mesh at element level
         unsigned count = 0;
         if (parent_boundary_y_id == 3)
         {
           for (unsigned e = 0; e < n_pml_element; e++)
           {
             // If element is on the right boundary
             if ((e % n_pml_x) == (n_pml_x - 1))
             {
               // Upcast from GeneralisedElement to bulk element
               ELEMENT* el_pt = dynamic_cast<ELEMENT*>(this->element_pt(e));
               // Loop over all nodes in element
               unsigned n_node = el_pt->nnode();
               for (unsigned inod = 0; inod < n_node; inod++)
               {
                 if (e == (n_pml_x - 1))
                 {
                   if (inod == interior_node_nr_helper_2)
                     el_pt->node_pt(inod) = special_corner_node_pt;
                   if ((inod % nnode_1d == interior_node_nr_helper_2) &&
                       (inod > (nnode_1d - 1)))
                   {
                     // Get the pointer from the triangular mesh
                     el_pt->node_pt(inod) = ordered_boundary_y_node_pt[count];
                     count++;
                     // Node between two elements
                     if (inod == interior_node_nr_helper_3)
                     {
                       count--;
                     }
                   }
                 }
                 else
                 {
                   if ((inod % nnode_1d) == interior_node_nr_helper_2)
                   {
                     // Get the pointer from the triangular mesh
                     el_pt->node_pt(inod) = ordered_boundary_y_node_pt[count];
                     count++;
                     // Node between two elements
                     if (inod == interior_node_nr_helper_3)
                     {
                       count--;
                     }
                   }
                 }
               }
             }
           }
         }
         count = 0;
         if (parent_boundary_x_id == 2)
         {
           for (unsigned e = 0; e < n_pml_element; e++)
           {
             // If element is on the right boundary
             if ((int)(e / n_pml_x) == 0)
             {
               // Upcast from GeneralisedElement to bulk element
               ELEMENT* el_pt = dynamic_cast<ELEMENT*>(this->element_pt(e));
               // Loop over all nodes in element
               unsigned n_node = el_pt->nnode();
               for (unsigned inod = 0; inod < n_node; inod++)
               {
                 // If it is one of the ones on the left boundary
                 if (e == (n_pml_x - 1))
                 {
                   if (((int)(inod / nnode_1d) == 0) &&
                       (inod < interior_node_nr_helper_2))
                   {
                     // Get the pointer from the triangular mesh
                     el_pt->node_pt(inod) = ordered_boundary_x_node_pt[count];
                     count++;
                     // Node between two elements
                     if (inod == (nnode_1d - 1))
                     {
                       count--;
                     }
                   }
                 }
                 else
                 {
                   if ((int)(inod / nnode_1d) == 0)
                   {
                     // Get the pointer from the triangular mesh
                     el_pt->node_pt(inod) = ordered_boundary_x_node_pt[count];
                     count++;
                     // Node between two elements
                     if (inod == interior_node_nr_helper_2)
                     {
                       count--;
                     }
                   }
                 }
               }
             }
           }
         }
       }
       // Set up bottom left corner element
       //--------------------------------
       if ((parent_boundary_x_id == 0) && (parent_boundary_y_id == 3))
       {
         // Get the number of nodes to be connected on the horizontal boundary
         unsigned n_boundary_x_node =
           PMLQuad_mesh_x_pt->nboundary_node(parent_boundary_x_id);
         // Create a vector of ordered boundary nodes
         Vector<Node*> ordered_boundary_x_node_pt(n_boundary_x_node);
         // Fill the vector with the nodes on the respective boundary
         for (unsigned n = 0; n < n_boundary_x_node; n++)
         {
           ordered_boundary_x_node_pt[n] =
             PMLQuad_mesh_x_pt->boundary_node_pt(parent_boundary_x_id, n);
         }
         // Sort them
         if (parent_boundary_x_id == 0)
         {
           std::sort(ordered_boundary_x_node_pt.begin(),
                     ordered_boundary_x_node_pt.end(),
                     TwoDimensionalPMLHelper::sorter_top_boundary);
         }
         // Get the number of nodes to be connected on the vertical boundary
         unsigned n_boundary_y_node =
           PMLQuad_mesh_y_pt->nboundary_node(parent_boundary_y_id);
         // Create a vector of ordered boundary nodes
         Vector<Node*> ordered_boundary_y_node_pt(n_boundary_y_node);
         // Fill the vector with the nodes on the respective boundary
         for (unsigned n = 0; n < n_boundary_y_node; n++)
         {
           ordered_boundary_y_node_pt[n] =
             PMLQuad_mesh_y_pt->boundary_node_pt(parent_boundary_y_id, n);
         }
         // Sort them
         if (parent_boundary_y_id == 3)
         {
           std::sort(ordered_boundary_y_node_pt.begin(),
                     ordered_boundary_y_node_pt.end(),
                     TwoDimensionalPMLHelper::sorter_right_boundary);
         }
         unsigned x_nnod = this->nboundary_node(current_boundary_x_id);
         for (unsigned j = 0; j < x_nnod; j++)
         {
           this->boundary_node_pt(current_boundary_x_id, j)->set_obsolete();
         }
         unsigned y_nnod = this->nboundary_node(current_boundary_y_id);
         for (unsigned j = 0; j < y_nnod; j++)
         {
           this->boundary_node_pt(current_boundary_y_id, j)->set_obsolete();
         }
         // Kill the obsolete nodes
         this->prune_dead_nodes();
         unsigned n_pml_element = this->nelement();
         // Connect the elements in the pml mesh to the ones
         // in the triangular mesh at element level
         unsigned count = 0;
         if (parent_boundary_y_id == 3)
         {
           for (unsigned e = 0; e < n_pml_element; e++)
           {
             // If element is on the right boundary
             if ((e % n_pml_x) == (n_pml_x - 1))
             {
               // Upcast from GeneralisedElement to bulk element
               ELEMENT* el_pt = dynamic_cast<ELEMENT*>(this->element_pt(e));
               // Loop over all nodes in element
               unsigned n_node = el_pt->nnode();
               for (unsigned inod = 0; inod < n_node; inod++)
               {
                 if (e == (n_pml_element - 1))
                 {
                   if (inod == interior_node_nr_helper_3)
                   {
                     el_pt->node_pt(inod) = special_corner_node_pt;
                   }
                   if ((inod % nnode_1d == interior_node_nr_helper_2) &&
                       (inod < interior_node_nr_helper_3))
                   {
                     // Get the pointer from the triangular mesh
                     el_pt->node_pt(inod) = ordered_boundary_y_node_pt[count];
                     count++;
                     // Node between two elements
                     if (inod == interior_node_nr_helper_3)
                     {
                       count--;
                     }
                   }
                 }
                 else
                 {
                   if ((inod % nnode_1d) == interior_node_nr_helper_2)
                   {
                     // Get the pointer from the triangular mesh
                     el_pt->node_pt(inod) = ordered_boundary_y_node_pt[count];
                     count++;
                     // Node between two elements
                     if (inod == interior_node_nr_helper_3)
                     {
                       count--;
                     }
                   }
                 }
               }
             }
           }
         }
         count = 0;
         if (parent_boundary_x_id == 0)
         {
           for (unsigned e = 0; e < n_pml_element; e++)
           {
             // If element is on the right boundary
             if (e >= ((n_pml_x) * (n_pml_y - 1)))
             {
               // Upcast from GeneralisedElement to bulk element
               ELEMENT* el_pt = dynamic_cast<ELEMENT*>(this->element_pt(e));
               // Loop over all nodes in element
               unsigned n_node = el_pt->nnode();
               for (unsigned inod = 0; inod < n_node; inod++)
               {
                 if (e == (n_pml_element - 1))
                 {
                   if (((unsigned)(inod / nnode_1d) ==
                        interior_node_nr_helper_2) &&
                       (inod < interior_node_nr_helper_3))
                   {
                     // Get the pointer from the triangular mesh
                     el_pt->node_pt(inod) = ordered_boundary_x_node_pt[count];
                     count++;
                     // Node between two elements
                     if (inod == interior_node_nr_helper_3)
                     {
                       count--;
                     }
                   }
                 }
                 else
                 {
                   if ((unsigned)(inod / nnode_1d) == interior_node_nr_helper_2)
                   {
                     // Get the pointer from the triangular mesh
                     el_pt->node_pt(inod) = ordered_boundary_x_node_pt[count];
                     count++;
                     // Node between two elements
                     if (inod == interior_node_nr_helper_3)
                     {
                       count--;
                     }
                   }
                 }
               }
             }
           }
         }
       }
     }
References oomph::Mesh::boundary_node_pt(), e(), oomph::Mesh::element_pt(), oomph::Mesh::finite_element_pt(), j, n, oomph::Mesh::nboundary_node(), oomph::Mesh::nelement(), oomph::FiniteElement::nnode_1d(), oomph::Mesh::prune_dead_nodes(), oomph::Node::set_obsolete(), oomph::TwoDimensionalPMLHelper::sorter_right_boundary(), and oomph::TwoDimensionalPMLHelper::sorter_top_boundary().
The documentation for this class was generated from the following file:
pml_meshes.h