MercuryDPM: Eigen::DSizes< DenseIndex, NumDims > Struct Template Reference
Eigen::DSizes< DenseIndex, NumDims > Struct Template Reference
#include <TensorDimensions.h>
Public Types
typedef array< DenseIndex, NumDims > Base
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index rank () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DenseIndex TotalSize () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DSizes ()
EIGEN_DEVICE_FUNC DSizes (const array< DenseIndex, NumDims > &a)
EIGEN_DEVICE_FUNC DSizes (const DenseIndex i0)
EIGEN_DEVICE_FUNC DSizes (const DimensionList< DenseIndex, NumDims > &a)
template<typename OtherIndex >
EIGEN_DEVICE_FUNC DSizes (const array< OtherIndex, NumDims > &other, std::enable_if_t< internal::is_same< DenseIndex, typename internal::promote_index_type< DenseIndex, OtherIndex >::type >::value, void * >=0)
template<typename FirstType , typename... OtherTypes>
EIGEN_DEVICE_FUNC DSizes (const Eigen::IndexList< FirstType, OtherTypes... > &dimensions)
template<typename std::ptrdiff_t... Indices>
EIGEN_DEVICE_FUNC DSizes (const Sizes< Indices... > &a)
template<typename... IndexTypes>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DSizes (DenseIndex firstDimension, DenseIndex secondDimension, IndexTypes... otherDimensions)
EIGEN_DEVICE_FUNC DSizes & operator= (const array< DenseIndex, NumDims > &other)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DenseIndex IndexOfColMajor (const array< DenseIndex, NumDims > &indices) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DenseIndex IndexOfRowMajor (const array< DenseIndex, NumDims > &indices) const
Static Public Attributes
static const int count = NumDims
Member Typedef Documentation
Base
template<typename DenseIndex , int NumDims> typedef array<DenseIndex, NumDims> Eigen::DSizes< DenseIndex, NumDims >::Base
Constructor & Destructor Documentation
DSizes() [1/8]
template<typename DenseIndex , int NumDims> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::DSizes< DenseIndex, NumDims >::DSizes () inline
{
     for (int i = 0; i < NumDims; ++i) {
       (*this)[i] = 0;
     }
   }
References i.
DSizes() [2/8]
template<typename DenseIndex , int NumDims> EIGEN_DEVICE_FUNC Eigen::DSizes< DenseIndex, NumDims >::DSizes (const array< DenseIndex, NumDims > & a) inline explicit
 : Base(a) {}
DSizes() [3/8]
template<typename DenseIndex , int NumDims> EIGEN_DEVICE_FUNC Eigen::DSizes< DenseIndex, NumDims >::DSizes (const DenseIndex i0) inline explicit
{
     eigen_assert(NumDims == 1);
     (*this)[0] = i0;
   }
References eigen_assert.
DSizes() [4/8]
template<typename DenseIndex , int NumDims> EIGEN_DEVICE_FUNC Eigen::DSizes< DenseIndex, NumDims >::DSizes (const DimensionList< DenseIndex, NumDims > & a) inline
{
     for (int i = 0; i < NumDims; ++i) {
       (*this)[i] = a[i];
     }
   }
References a, and i.
DSizes() [5/8]
template<typename DenseIndex , int NumDims> template<typename OtherIndex > EIGEN_DEVICE_FUNC Eigen::DSizes< DenseIndex, NumDims >::DSizes (const array< OtherIndex, NumDims > & other, std::enable_if_t< internal::is_same< DenseIndex, typename internal::promote_index_type< DenseIndex, OtherIndex >::type >::value, void * > = 0) inline explicit
                       {
     for (int i = 0; i < NumDims; ++i) {
       (*this)[i] = static_cast<DenseIndex>(other[i]);
     }
   }
References i.
DSizes() [6/8]
template<typename DenseIndex , int NumDims> template<typename FirstType , typename... OtherTypes> EIGEN_DEVICE_FUNC Eigen::DSizes< DenseIndex, NumDims >::DSizes (const Eigen::IndexList< FirstType, OtherTypes... > & dimensions) inline explicit
{
     for (int i = 0; i < dimensions.count; ++i) {
       (*this)[i] = dimensions[i];
     }
   }
References i.
DSizes() [7/8]
template<typename DenseIndex , int NumDims> template<typename std::ptrdiff_t... Indices> EIGEN_DEVICE_FUNC Eigen::DSizes< DenseIndex, NumDims >::DSizes (const Sizes< Indices... > & a) inline
{
     for (int i = 0; i < NumDims; ++i) {
       (*this)[i] = a[i];
     }
   }
References a, and i.
DSizes() [8/8]
template<typename DenseIndex , int NumDims> template<typename... IndexTypes> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::DSizes< DenseIndex, NumDims >::DSizes (DenseIndex firstDimension, DenseIndex secondDimension, IndexTypes... otherDimensions) inline explicit
       : Base({{firstDimension, secondDimension, otherDimensions...}}) {
     EIGEN_STATIC_ASSERT(sizeof...(otherDimensions) + 2 == NumDims, YOU_MADE_A_PROGRAMMING_MISTAKE)
   }
Member Function Documentation
IndexOfColMajor()
template<typename DenseIndex , int NumDims> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DenseIndex Eigen::DSizes< DenseIndex, NumDims >::IndexOfColMajor (const array< DenseIndex, NumDims > & indices) const inline
{
     return internal::tensor_index_linearization_helper<DenseIndex, NumDims, NumDims - 1, false>::run(
         indices, *static_cast<const Base*>(this));
   }
References Eigen::internal::tensor_index_linearization_helper< Index, NumIndices, n, RowMajor >::run().
Referenced by Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::linearizedIndex().
IndexOfRowMajor()
template<typename DenseIndex , int NumDims> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DenseIndex Eigen::DSizes< DenseIndex, NumDims >::IndexOfRowMajor (const array< DenseIndex, NumDims > & indices) const inline
{
     return internal::tensor_index_linearization_helper<DenseIndex, NumDims, NumDims - 1, true>::run(
         indices, *static_cast<const Base*>(this));
   }
References Eigen::internal::tensor_index_linearization_helper< Index, NumIndices, n, RowMajor >::run().
Referenced by Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::linearizedIndex().
operator=()
template<typename DenseIndex , int NumDims> EIGEN_DEVICE_FUNC DSizes& Eigen::DSizes< DenseIndex, NumDims >::operator= (const array< DenseIndex, NumDims > & other) inline
{
     *static_cast<Base*>(this) = other;
     return *this;
   }
rank()
template<typename DenseIndex , int NumDims> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::DSizes< DenseIndex, NumDims >::rank () const inline
 { return NumDims; }
Referenced by Eigen::internal::TensorBlockMapper< NumDims, Layout, IndexType >::InitializeBlockDimensions(), and test_rank_zero().
TotalSize()
template<typename DenseIndex , int NumDims> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DenseIndex Eigen::DSizes< DenseIndex, NumDims >::TotalSize () const inline
{
     return (NumDims == 0) ? 1 : internal::array_prod(*static_cast<const Base*>(this));
   }
References Eigen::internal::array_prod().
Referenced by Eigen::internal::TensorBlockMapper< NumDims, Layout, IndexType >::blockTotalSize(), Eigen::TensorEvaluator< const TensorBroadcastingOp< Broadcast, ArgType >, Device >::BroadcastBlock(), Eigen::internal::TensorBlockIO< Scalar, IndexType, NumDims, Layout >::Copy(), Eigen::internal::TensorBlockMapper< NumDims, Layout, IndexType >::InitializeBlockDimensions(), RandomTargetBlockSize(), RandomTargetSize(), Eigen::internal::TensorBlockAssignment< Scalar, NumDims, TensorBlockExpr, IndexType >::Run(), SkewedInnerBlock(), test_block_io_copy_data_from_source_to_target(), test_block_io_copy_using_reordered_dimensions(), test_block_io_squeeze_ones(), test_block_mapper_maps_every_element(), test_broadcast_sycl(), test_broadcast_sycl_fixed(), test_composition(), test_concatenation_as_lvalue(), test_custom_binary_op_sycl(), test_custom_unary_op_sycl(), test_dynamic_size(), test_expr_reverse(), test_first_dim_reductions_max_sycl(), test_first_dim_reductions_mean_sycl(), test_first_dim_reductions_sum_sycl(), test_forced_eval_sycl(), test_full_reductions_max_sycl(), test_full_reductions_mean_sycl(), test_full_reductions_min_sycl(), test_full_reductions_sum_sycl(), test_large_contraction_with_output_kernel(), test_last_dim_reductions_mean_sycl(), test_last_dim_reductions_sum_sycl(), test_multithread_contraction_with_output_kernel(), test_rank_zero(), test_sharded_by_inner_dim_contraction(), test_sharded_by_inner_dim_contraction_with_output_kernel(), test_simple_concatenation(), and test_simple_reverse().
Member Data Documentation
count
template<typename DenseIndex , int NumDims> const int Eigen::DSizes< DenseIndex, NumDims >::count = NumDims static
The documentation for this struct was generated from the following file:
TensorDimensions.h