MercuryDPM: Eigen::CwiseUnaryOp< UnaryOp, XprType > Class Template Reference
Eigen::CwiseUnaryOp< UnaryOp, XprType > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
Generic expression where a coefficient-wise unary operator is applied to an expression.
#include <CwiseUnaryOp.h>
Public Types
typedef CwiseUnaryOpImpl< UnaryOp, XprType, typename internal::traits< XprType >::StorageKind >::Base Base
typedef internal::ref_selector< XprType >::type XprTypeNested
typedef internal::remove_all_t< XprType > NestedExpression
Public Types inherited from Eigen::CwiseUnaryOpImpl< UnaryOp, XprType, internal::traits< XprType >::StorageKind >
typedef internal::generic_xpr_base< CwiseUnaryOp< UnaryOp, XprType > >::type Base
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CwiseUnaryOp (const XprType &xpr, const UnaryOp &func=UnaryOp())
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const UnaryOp & functor () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const internal::remove_all_t< XprTypeNested > & nestedExpression () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::remove_all_t< XprTypeNested > & nestedExpression ()
Protected Attributes
XprTypeNested m_xpr
const UnaryOp m_functor
Detailed Description
template<typename UnaryOp, typename XprType>
class Eigen::CwiseUnaryOp< UnaryOp, XprType >
Generic expression where a coefficient-wise unary operator is applied to an expression.
Template Parameters
UnaryOp template functor implementing the operator
XprType the type of the expression to which we are applying the unary operator
This class represents an expression where a unary operator is applied to an expression. It is the return type of all operations taking exactly 1 input expression, regardless of the presence of other inputs such as scalars. For example, the operator* in the expression 3*matrix is considered unary, because only the right-hand side is an expression, and its return type is a specialization of CwiseUnaryOp.
Most of the time, this is the only way that it is used, so you typically don't have to name CwiseUnaryOp types explicitly.
See also
MatrixBase::unaryExpr(const CustomUnaryOp &) const, class CwiseBinaryOp, class CwiseNullaryOp
Member Typedef Documentation
Base
template<typename UnaryOp , typename XprType > typedef CwiseUnaryOpImpl<UnaryOp, XprType, typename internal::traits<XprType>::StorageKind>::Base Eigen::CwiseUnaryOp< UnaryOp, XprType >::Base
NestedExpression
template<typename UnaryOp , typename XprType > typedef internal::remove_all_t<XprType> Eigen::CwiseUnaryOp< UnaryOp, XprType >::NestedExpression
XprTypeNested
template<typename UnaryOp , typename XprType > typedef internal::ref_selector<XprType>::type Eigen::CwiseUnaryOp< UnaryOp, XprType >::XprTypeNested
Constructor & Destructor Documentation
CwiseUnaryOp()
template<typename UnaryOp , typename XprType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::CwiseUnaryOp< UnaryOp, XprType >::CwiseUnaryOp (const XprType & xpr, const UnaryOp & func = UnaryOp()) inline explicit
       : m_xpr(xpr), m_functor(func) {}
Member Function Documentation
cols()
template<typename UnaryOp , typename XprType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EIGEN_CONSTEXPR Index Eigen::CwiseUnaryOp< UnaryOp, XprType >::cols () const inline
 { return m_xpr.cols(); }
References Eigen::CwiseUnaryOp< UnaryOp, XprType >::m_xpr.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
functor()
template<typename UnaryOp , typename XprType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const UnaryOp& Eigen::CwiseUnaryOp< UnaryOp, XprType >::functor () const inline
Returns
the functor representing the unary operation
 { return m_functor; }
References Eigen::CwiseUnaryOp< UnaryOp, XprType >::m_functor.
nestedExpression() [1/2]
template<typename UnaryOp , typename XprType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::remove_all_t<XprTypeNested>& Eigen::CwiseUnaryOp< UnaryOp, XprType >::nestedExpression () inline
Returns
the nested expression
 { return m_xpr; }
References Eigen::CwiseUnaryOp< UnaryOp, XprType >::m_xpr.
nestedExpression() [2/2]
template<typename UnaryOp , typename XprType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const internal::remove_all_t<XprTypeNested>& Eigen::CwiseUnaryOp< UnaryOp, XprType >::nestedExpression () const inline
Returns
the nested expression
{
     return m_xpr;
   }
References Eigen::CwiseUnaryOp< UnaryOp, XprType >::m_xpr.
rows()
template<typename UnaryOp , typename XprType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EIGEN_CONSTEXPR Index Eigen::CwiseUnaryOp< UnaryOp, XprType >::rows () const inline
 { return m_xpr.rows(); }
References Eigen::CwiseUnaryOp< UnaryOp, XprType >::m_xpr.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
Member Data Documentation
m_functor
template<typename UnaryOp , typename XprType > const UnaryOp Eigen::CwiseUnaryOp< UnaryOp, XprType >::m_functor protected
Referenced by Eigen::CwiseUnaryOp< UnaryOp, XprType >::functor().
m_xpr
template<typename UnaryOp , typename XprType > XprTypeNested Eigen::CwiseUnaryOp< UnaryOp, XprType >::m_xpr protected
Referenced by Eigen::CwiseUnaryOp< UnaryOp, XprType >::cols(), Eigen::CwiseUnaryOp< UnaryOp, XprType >::nestedExpression(), and Eigen::CwiseUnaryOp< UnaryOp, XprType >::rows().
The documentation for this class was generated from the following file:
CwiseUnaryOp.h