MercuryDPM: plotPSD Namespace Reference
plotPSD Namespace Reference
Variables
fileName = sys.argv[1]
read in the data file name
lines = open(fileName).readlines()
open the data file read all lines
int no = 0
t = float(lines[no].split()[1])
n = int(lines[no].split()[0])
list data = [[float(d) for d in line.split()] for line in lines[no + 1:]]
radius = np.array([dat[6] for dat in data])
figsize
plot psd of data file define figure size in inch
dpi
probN = np.append(probCN[0], np.diff(probCN))
bins
density
True
r = bins[:-1]
R = bins[1:]
probV = probN * (R**2+r**2) * (R+r)
probCV = np.cumsum(probV)
probCN = np.cumsum(probN)
label
csvName = sys.argv[2]
read in cumulative number psd from csv
Variable Documentation
bins
plotPSD.bins
csvName
plotPSD.csvName = sys.argv[2]
read in cumulative number psd from csv
read in second cumulative number psd from csv
data
list plotPSD.data = [[float(d) for d in line.split()] for line in lines[no + 1:]]
density
plotPSD.density
dpi
plotPSD.dpi
figsize
plotPSD.figsize
plot psd of data file define figure size in inch
fileName
plotPSD.fileName = sys.argv[1]
read in the data file name
label
plotPSD.label
lines
plotPSD.lines = open(fileName).readlines()
open the data file read all lines
n
plotPSD.n = int(lines[no].split()[0])
no
int plotPSD.no = 0
probCN
plotPSD.probCN = np.cumsum(probN)
probCV
plotPSD.probCV = np.cumsum(probV)
probN
plotPSD.probN = np.append(probCN[0], np.diff(probCN))
probV
plotPSD.probV = probN * (R**2+r**2) * (R+r)
r
plotPSD.r = bins[:-1]
R
plotPSD.R = bins[1:]
radius
plotPSD.radius = np.array([dat[6] for dat in data])
t
plotPSD.t = float(lines[no].split()[1])
Referenced by __attribute__(), Jeffery_Solution.acceleration(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >.actions_after_adapt(), FSIChannelWithLeafletProblem< ELEMENT >.actions_before_implicit_timestep(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >.actions_before_implicit_timestep(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >.actions_before_implicit_timestep(), oomph::TreeBasedRefineableMeshBase.adapt_mesh(), oomph::PeriodicOrbitAssemblyHandler< NNODE_1D >.adapt_temporal_mesh(), TriangleMeshWall.addToMesh(), tetgenmesh.adjustedgering(), oomph::MyAlgebraicCollapsibleChannelMesh< ELEMENT >.algebraic_node_update(), oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >.algebraic_node_update(), oomph::AlgebraicCollapsibleChannelMesh< ELEMENT >.algebraic_node_update(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >.algebraic_node_update(), oomph::AlgebraicFSIDrivenCavityMesh< ELEMENT >.algebraic_node_update(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >.algebraic_node_update(), oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >.algebraic_node_update(), ExactSolution.analytical_outer_unit_normal(), Jeffery_Solution.angle(), tetgenmesh.apex(), TwoDDGProblem< ELEMENT >.apply_boundary_conditions(), Eigen::internal.array_prod(), oomph::QMacroElement< 2 >.assemble_macro_to_eulerian_jacobian(), oomph::MacroElement.assemble_macro_to_eulerian_jacobian(), oomph::QMacroElement< 2 >.assemble_macro_to_eulerian_jacobian2(), oomph::MacroElement.assemble_macro_to_eulerian_jacobian2(), oomph::SelfStartingBDF2.assign_initial_data_values(), oomph::PeriodicOrbitTimeDiscretisation.assign_initial_data_values(), oomph::Steady< NSTEPS >.assign_initial_data_values(), oomph::BDF< NSTEPS >.assign_initial_data_values(), oomph::Newmark< NSTEPS >.assign_initial_data_values(), oomph::Newmark< 2 >.assign_initial_data_values(), oomph::Newmark< 2 >.assign_initial_data_values_stage1(), oomph::SelfStartingBDF2.assign_initial_positions_impulsive(), oomph::Steady< NSTEPS >.assign_initial_positions_impulsive(), oomph::Newmark< NSTEPS >.assign_initial_positions_impulsive(), oomph::BDF< NSTEPS >.assign_initial_positions_impulsive(), oomph::SelfStartingBDF2.assign_initial_values_impulsive(), oomph::Steady< NSTEPS >.assign_initial_values_impulsive(), oomph::Newmark< NSTEPS >.assign_initial_values_impulsive(), oomph::BDF< NSTEPS >.assign_initial_values_impulsive(), UnsteadyHeatProblem< ELEMENT >.assign_time_slab_id(), NavierStokesProblem< ELEMENT >.assign_time_slice_id(), Eigen::internal::swap_assign_op< Scalar >.assignCoeff(), oomph::Multi_domain_functions.aux_setup_multi_domain_interaction(), oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT >.BackupMeshForProjection(), bench(), bench_mnk(), bench_prod(), bench_t(), benchBasic(), CRBond_Bessel.bessik01b(), CRBond_Bessel.bessjy01b(), Eigen::internal::kiss_cpx_fft< Scalar_ >.bfly2(), Eigen::internal::kiss_cpx_fft< Scalar_ >.bfly_generic(), Eigen::internal.bicgstab(), binary_ops_test(), MPIContainer.broadcast(), oomph::SarahBL.buckled_ring_residual(), SarahBL.buckled_ring_residual(), bug_1223(), oomph::RefineableQElement< 3 >.build(), oomph::RefineableSolidQElement< 3 >.build(), oomph::RefineableQElement< 1 >.build(), oomph::RefineableQElement< 2 >.build(), oomph::RefineableSolidQElement< 2 >.build(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >.build_mesh(), Eigen::internal::TensorIntDivisor< int32_t, true >.calcMagic(), check_custom_new_delete(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >.check_integrity(), oomph::RefineableQElement< 3 >.check_integrity(), oomph::RefineableQElement< 1 >.check_integrity(), oomph::RefineableQElement< 2 >.check_integrity(), check_slerp(), oomph::BoundaryNode< NODE_TYPE >.clear_copied_pointers(), cod(), compact_size_triple(), AxisymmetricVibratingShellProblem< ELEMENT >.complete_problem_setup(), VibratingShellProblem< ELEMENT >.complete_problem_setup(), TwoLayerInterfaceProblem< ELEMENT >.complete_problem_setup(), UnstructuredFluidProblem< ELEMENT >.complete_problem_setup(), BubbleInChannelProblem< ELEMENT >.complete_problem_setup(), DropInChannelProblem< ELEMENT >.complete_problem_setup(), AdvectionProblem.compute_error(), TwoDDGProblem< ELEMENT >.compute_error(), oomph::EulerEquations< DIM >.compute_error(), oomph::ScalarAdvectionEquations< DIM >.compute_error(), SinterLinInteraction.computeNormalForce(), Eigen::ComplexSchur< MatrixType_ >.computeShift(), WearableTriangleMeshWall.computeWear(), Eigen::internal.conservative_sparse_sparse_product_impl(), oomph::TriangleMesh< ELEMENT >.convex_hull(), oomph::Data.copy(), oomph::Node.copy(), oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT >.copy_onto_original_mesh(), oomph::Domain.d2macro_element_boundary(), oomph::AxisymmetricPoroelasticityEquations.d2u_dt2(), oomph::PoroelasticityEquations< DIM >.d2u_dt2(), oomph::AxisymmetricLinearElasticityEquationsBase.d2u_dt2_axisymmetric_linear_elasticity(), oomph::LinearWaveEquations< DIM >.d2u_dt2_lin_wave(), oomph::LinearElasticityEquationsBase< DIM >.d2u_dt2_linear_elasticity(), oomph::Data.Data(), ElasticAxisymmetricSolubleSurfactantTransportInterfaceElement< ELEMENT >.dc_bulk_dt_surface(), oomph::AdvectionDiffusionReactionEquations< NREAGENT, DIM >.dc_dt_adv_diff_react(), oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >.dcdt_surface(), oomph::SpineLineMarangoniSurfactantFluidInterfaceElement< ELEMENT >.dcdt_surface(), oomph::SurfactantTransportInterfaceElement.dcdt_surface(), oomph::deriv_functions.dcos(), tetgenmesh.decode(), oomph::Mesh.delete_all_external_storage(), oomph::deriv_functions::DampedOscillation.derivative(), oomph::deriv_functions::OrderReductionTest.derivative(), oomph::SolutionFunctor.derivative(), oomph::ODEElement.derivative_function(), oomph::TR.derivative_index(), tetgenmesh.dest(), SSPorousChannelEquations.df_dt(), oomph::PerturbedSpineLinearisedAxisymmetricFluidInterfaceElement< ELEMENT >.dH_dt(), MPIContainer.directReceive(), MPIContainer.directSend(), oomph::PeriodicOrbitAssemblyHandler< NNODE_1D >.discrete_times(), oomph::SarahBL.Diss_sarah(), SarahBL.Diss_sarah(), tetgenmesh.dissolve(), Eigen::internal::TensorIntDivisor< T, div_gt_one >.divide(), oomph::Domain.dmacro_element_boundary(), oomph::LinearisedAxisymmetricNavierStokesEquations.dnodal_position_perturbation_dt_lin_axi_nst(), InterfaceProblem< ELEMENT, TIMESTEPPER >.doc_solution(), ElasticRingProblem< ELEMENT >.doc_solution(), Eigen::EigenSolver< MatrixType_ >.doComputeEigenvectors(), oomph::GeneralisedElement.dof_vector(), oomph::AssemblyHandler.dof_vector(), dostuff(), oomph::deriv_functions.dpoly2(), oomph::deriv_functions.dpoly3(), oomph::Node.dposition_dt(), oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >.dposition_dt(), oomph::FiniteElement.dposition_dt(), oomph::Node.dposition_gen_dt(), oomph::AxisymmetricPoroelasticityEquations.dq_edge_dt(), oomph::PoroelasticityEquations< DIM >.dq_edge_dt(), oomph::AxisymmetricPoroelasticityEquations.dq_internal_dt(), oomph::PoroelasticityEquations< DIM >.dq_internal_dt(), FancySpheres.draw(), oomph::deriv_functions.dsin(), oomph::Time.dt(), SpineGravityTractionElement< ELEMENT >.du_dt(), oomph::AxisymmetricPoroelasticityEquations.du_dt(), oomph::PoroelasticityEquations< DIM >.du_dt(), oomph::AdvectionDiffusionEquations< DIM >.du_dt_adv_diff(), oomph::AxisymAdvectionDiffusionEquations.du_dt_axi_adv_diff(), oomph::AxisymmetricNavierStokesEquations.du_dt_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.du_dt_axi_nst(), oomph::AxisymmetricLinearElasticityEquationsBase.du_dt_axisymmetric_linear_elasticity(), oomph::GeneralisedAdvectionDiffusionEquations< DIM >.du_dt_cons_adv_diff(), oomph.du_dt_cons_axisym_adv_diff(), oomph::FluxTransportEquations< DIM >.du_dt_flux_transport(), oomph::LinearisedAxisymmetricNavierStokesEquations.du_dt_lin_axi_nst(), oomph::LinearWaveEquations< DIM >.du_dt_lin_wave(), oomph::LinearisedAxisymmetricNavierStokesEquations.du_dt_linearised_axi_nst(), oomph::LinearisedNavierStokesEquations.du_dt_linearised_nst(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.du_dt_nst(), oomph::NavierStokesEquations< DIM >.du_dt_nst(), oomph::PolarNavierStokesEquations.du_dt_pnst(), oomph::SphericalAdvectionDiffusionEquations.du_dt_spherical_adv_diff(), oomph::SphericalNavierStokesEquations.du_dt_spherical_nst(), oomph::UnsteadyHeatEquations< DIM >.du_dt_ust_heat(), oomph::WomersleyEquations< DIM >.du_dt_womersley(), oomph::Data.dump(), oomph::Node.dump(), oomph::Node.dx_dt(), oomph::Node.dx_gen_dt(), oomph::LinearisedAxisymmetricFluidInterfaceElement.dXhat_dt(), tetgenmesh.edgemarked(), Detail::VTKPointDescriptorEntryImpl< T, V >.emit(), Detail.emitProxy(), tetgenmesh.encode(), tetgenmesh.enext2fnextself(), tetgenmesh.enext2self(), tetgenmesh.enextfnextself(), tetgenmesh.enextself(), oomph::PeriodicOrbitAssemblyHandler< NNODE_1D >.eqn_number(), tetgenmesh.esymself(), StatisticsPoint< T >.evaluateIntegral(), StatisticsVector< T >.evaluateIntegral(), oomph::ODEElement.exact_solution(), oomph::MyProblem.exact_solution(), Eigen::StlThreadEnvironment.ExecuteTask(), SSPorousChannelElement.f(), Eigen::internal.F32ToBf16(), tetgenmesh.facemarked(), mathsFunc.factorial(), FancySpheres.FancySpheres(), Eigen::internal.fast_twosum(), oomph::IMRODEElement.fill_in_contribution_to_jacobian(), oomph::ODEElement.fill_in_contribution_to_jacobian(), oomph::IMRODEElement.fill_in_contribution_to_residuals(), oomph::ODEElement.fill_in_contribution_to_residuals(), DPMBase.findNextExistingDataFile(), Global_Physical_Variables.flux(), Global_Parameters.flux(), ExactSolution.flux_into_bulk(), foo(), PrintWallTimeMixin.formatTime(), Eigen::internal::tuple_coeff< Idx, ValueT >.get(), Eigen::internal::tuple_coeff< 0, ValueT >.get(), oomph::Problem.get_dofs(), oomph::MyProblem.get_error_norm(), Global_Physical_Variables.get_exact_u(), ExactSoln.get_exact_u(), SinSolution.get_exact_u(), ExactSolution.get_exact_u_for_unsteady_heat_validation(), oomph::ProjectableLinearHeatAndElasticityElement< LINEAR_HEAT_AND_ELAST_ELEMENT >.get_field(), oomph::ProjectableAxisymmetricCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >.get_field(), oomph::ProjectableAxisymmetricPoroelasticityElement< AXISYMMETRIC_POROELASTICITY_ELEMENT >.get_field(), oomph::GeneralisedNewtonianProjectableAxisymmetricCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >.get_field(), oomph::ProjectableGeneralisedNewtonianTaylorHoodElement< TAYLOR_HOOD_ELEMENT >.get_field(), oomph::ProjectableGeneralisedNewtonianCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >.get_field(), oomph::ProjectableTaylorHoodElement< TAYLOR_HOOD_ELEMENT >.get_field(), oomph::ProjectableCrouzeixRaviartElement< CROUZEIX_RAVIART_ELEMENT >.get_field(), oomph::ProjectableTaylorHoodSpaceTimeElement< TAYLOR_HOOD_ELEMENT >.get_field(), oomph::ProjectableTaylorHoodMixedOrderSpaceTimeElement< TAYLOR_HOOD_ELEMENT >.get_field(), oomph::ElementWithMortaringStatusAtNodes< ELEMENT >.get_interpolated_values(), oomph::RefineableLinearisedAxisymmetricQTaylorHoodElement.get_interpolated_values(), oomph::RefineableLinearisedAxisymmetricQCrouzeixRaviartElement.get_interpolated_values(), RefineableBuoyantQCrouzeixRaviartElement< DIM >.get_interpolated_values(), oomph::RefineableBuoyantQAxisymCrouzeixRaviartElement.get_interpolated_values(), oomph::RefineableBuoyantQSphericalCrouzeixRaviartElement.get_interpolated_values(), oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >.get_interpolated_values(), RefineableModalPoissonEquations< DIM >.get_interpolated_values(), oomph::RefineablePolarStreamfunctionEquations.get_interpolated_values(), oomph::RefineableAxisymAdvectionDiffusionEquations.get_interpolated_values(), oomph::RefineableAxisymmetricQTaylorHoodElement.get_interpolated_values(), oomph::RefineableAxisymmetricQCrouzeixRaviartElement.get_interpolated_values(), oomph::RefineableGeneralisedNewtonianAxisymmetricQTaylorHoodElement.get_interpolated_values(), oomph::RefineableGeneralisedNewtonianAxisymmetricQCrouzeixRaviartElement.get_interpolated_values(), oomph::RefineablePseudoSolidNodeUpdateElement< BASIC, SOLID >.get_interpolated_values(), oomph::RefineableHelmholtzEquations< DIM >.get_interpolated_values(), oomph::RefineableLinearisedQCrouzeixRaviartElement.get_interpolated_values(), oomph::RefineableLinearisedQTaylorHoodElement.get_interpolated_values(), oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >.get_interpolated_values(), oomph::RefineablePMLHelmholtzEquations< DIM >.get_interpolated_values(), oomph::RefineablePoissonEquations< DIM >.get_interpolated_values(), oomph::RefineablePolarTaylorHoodElement.get_interpolated_values(), oomph::RefineablePolarCrouzeixRaviartElement.get_interpolated_values(), oomph::RefineableQTaylorHoodSpaceTimeElement< DIM >.get_interpolated_values(), oomph::RefineableQTaylorHoodMixedOrderSpaceTimeElement< DIM >.get_interpolated_values(), oomph::RefineableSphericalAdvectionDiffusionEquations.get_interpolated_values(), oomph::RefineableQSphericalTaylorHoodElement.get_interpolated_values(), oomph::RefineableQSphericalCrouzeixRaviartElement.get_interpolated_values(), oomph::RefineableYoungLaplaceEquations.get_interpolated_values(), oomph::VorticitySmootherElement< ELEMENT >.get_interpolated_values(), SinSolution.get_source(), ExactSolution.get_source_for_unsteady_heat_validation(), oomph::LinearWaveEquations< DIM >.get_source_lin_wave(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >.get_source_ust_heat(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >.get_source_ust_heat(), oomph::UnsteadyHeatEquations< DIM >.get_source_ust_heat(), oomph::FiniteElement.get_x(), oomph::QElementBase.get_x_from_macro_element(), oomph::SpectralPeriodicOrbitElement< NNODE_1D >.get_Z2_flux(), BaseParticle.getDisplacement2(), TriangleMeshWall.getDistanceAndNormal(), Time2Finish.getFinishTime(), TriangleMeshWall.getInteractionWith(), BaseWall.getLinePlaneIntersect(), Time2Finish.getTime2Finish(), BasicIntersectionOfWalls.getVTK(), BasicUnionOfWalls.getVTK(), Eigen::internal.gmres(), RenderingWidget.grabFrame(), oomph::PerturbedSpine.height(), Eigen::internal.idrs(), GlobalParameters.incoming_sb_inside(), GlobalParameters.incoming_sb_outside(), tetgenmesh.infect(), tetgenmesh.infected(), oomph::FaceElement.interpolated_dxdt(), GeneralCircle.interpolated_history(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.interpolated_p_nst(), oomph::NavierStokesEquations< DIM >.interpolated_p_nst(), oomph::SpaceTimeNavierStokesEquations< DIM >.interpolated_p_nst(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >.interpolated_p_nst(), oomph::AxisymmetricPoroelasticityEquations.interpolated_q(), oomph::AxisymmetricPoroelasticityEquations.interpolated_u(), oomph::AxisymmetricNavierStokesEquations.interpolated_u_axi_nst(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.interpolated_u_axi_nst(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.interpolated_u_nst(), oomph::NavierStokesEquations< DIM >.interpolated_u_nst(), oomph::SpaceTimeUnsteadyHeatEquations< SPATIAL_DIM >.interpolated_u_ust_heat(), oomph::SpaceTimeUnsteadyHeatMixedOrderEquations< SPATIAL_DIM >.interpolated_u_ust_heat(), oomph::UnsteadyHeatEquations< DIM >.interpolated_u_ust_heat(), oomph::FiniteElement.interpolated_x(), oomph::FaceElement.interpolated_x(), tetgenmesh.isdead(), tetgenmesh.isfacehaspoint(), tetgenmesh.issymexist(), kill_trailing(), kill_trailingn(), oomph::SarahBL.Kin_energy_sarah(), SarahBL.Kin_energy_sarah(), lerp(), oomph::AssemblyHandler.local_problem_dof(), Camera.localTranslate(), Flag_definition.lower_tip(), Eigen::internal.LUnumTempV(), oomph::ChannelWithLeafletDomain.macro_bound_I_E(), oomph::ChannelWithLeafletDomain.macro_bound_I_N(), oomph::ChannelWithLeafletDomain.macro_bound_I_S(), oomph::ChannelWithLeafletDomain.macro_bound_I_W(), oomph::ChannelWithLeafletDomain.macro_bound_II_E(), oomph::ChannelWithLeafletDomain.macro_bound_II_N(), oomph::ChannelWithLeafletDomain.macro_bound_II_S(), oomph::ChannelWithLeafletDomain.macro_bound_II_W(), oomph::ChannelWithLeafletDomain.macro_bound_III_E(), oomph::ChannelWithLeafletDomain.macro_bound_III_N(), oomph::ChannelWithLeafletDomain.macro_bound_III_S(), oomph::ChannelWithLeafletDomain.macro_bound_III_W(), oomph::ChannelWithLeafletDomain.macro_bound_IV_E(), oomph::ChannelWithLeafletDomain.macro_bound_IV_N(), oomph::ChannelWithLeafletDomain.macro_bound_IV_S(), oomph::ChannelWithLeafletDomain.macro_bound_IV_W(), oomph::Domain.macro_element_boundary(), oomph::WarpedCubeDomain.macro_element_boundary(), oomph::FullCircleDomain.macro_element_boundary(), oomph::QuarterCircleSectorDomain.macro_element_boundary(), oomph::QuarterPipeDomain.macro_element_boundary(), oomph::QuarterTubeDomain.macro_element_boundary(), oomph::TubeDomain.macro_element_boundary(), oomph::FishDomain.macro_element_boundary(), oomph::EighthSphereDomain.macro_element_boundary(), oomph::ChannelWithLeafletDomain.macro_element_boundary(), oomph::CollapsibleChannelDomain.macro_element_boundary(), oomph::ExtrudedDomain.macro_element_boundary(), oomph::QMacroElement< 2 >.macro_map(), oomph::QExtrudedMacroElement< 3 >.macro_map(), oomph::QMacroElement< 3 >.macro_map(), oomph::MacroElement.macro_map(), main(), Eigen::JacobiRotation< Scalar >.makeGivens(), Eigen::JacobiRotation< Scalar >.makeJacobi(), tetgenmesh.markedge(), tetgenmesh.markface(), tetgenmesh.marktest(), tetgenmesh.marktested(), Eigen::ThreadPoolTempl< Environment >.MaybeGetTask(), GlobalParameters.melt_flux(), ExactSolution.melting_surface_height(), Eigen::internal.minimum_degree_ordering(), MandelbrotWidget.mouseMoveEvent(), TriangleMeshWall.moveVerticesToMatchVolume(), oomph::ODEProblem.my_set_initial_condition(), NanoTime(), nlerp(), oomph::FiniteElement.nodal_position(), oomph::FiniteElement.nodal_position_gen(), oomph::FiniteElement.nodal_value(), oomph::Node.Node(), oomph::AlgebraicNode.node_update(), oomph::MacroElementNodeUpdateNode.node_update(), oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >.node_update_central_region(), oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >.node_update_I(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >.node_update_I(), oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >.node_update_II(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >.node_update_II(), oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >.node_update_III(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >.node_update_III(), oomph::AlgebraicFishMesh< ELEMENT >.node_update_in_body(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >.node_update_in_central_box(), oomph::AlgebraicFishMesh< ELEMENT >.node_update_in_fin(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >.node_update_in_lower_right_box(), oomph::AlgebraicRefineableQuarterCircleSectorMesh< ELEMENT >.node_update_in_upper_left_box(), oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >.node_update_IV(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >.node_update_IV(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >.node_update_IX(), oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >.node_update_lower_right_region(), oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >.node_update_upper_left_region(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >.node_update_V(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >.node_update_VI(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >.node_update_VII(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >.node_update_VIII(), BiharmonicTestFunctions2.normal_E(), BiharmonicTestFunctions2.normal_W(), Eigen::internal.omega(), tetgenmesh::triface.operator!=(), oomph::deriv_functions::DampedOscillation.operator()(), oomph::deriv_functions::SimpleStiffTest.operator()(), oomph::deriv_functions::OrderReductionTest.operator()(), oomph::SolutionFunctor.operator()(), Eigen::UniformScaling< Scalar_ >.operator*(), Eigen::Translation< Scalar_, Dim_ >.operator*(), Eigen::RotationBase< Derived, Dim_ >.operator*(), Eigen::Transform< Scalar_, Dim_, Mode_, Options_ >.operator*(), Eigen::Transform< Scalar_, Dim_, Mode_, Options_ >.operator*=(), operator<<(), Eigen.operator<<(), Eigen::Transform< Scalar_, Dim_, Mode_, Options_ >.operator=(), tetgenmesh::triface.operator=(), tetgenmesh::triface.operator==(), tetgenmesh.oppo(), tetgenmesh.org(), oomph::HermiteBeamElement.output(), oomph::QExtrudedMacroElement< 3 >.output(), oomph::QMacroElement< 2 >.output(), oomph::QMacroElement< 3 >.output(), oomph::MacroElement.output(), oomph::MyTaylorHoodElement< DIM >.output(), oomph::MyCrouzeixRaviartElement.output(), oomph::ProjectableUnsteadyHeatSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >.output(), oomph::ProjectableUnsteadyHeatMixedOrderSpaceTimeElement< UNSTEADY_HEAT_ELEMENT >.output(), oomph::ProjectableUnsteadyHeatElement< UNSTEADY_HEAT_ELEMENT >.output(), oomph::QExtrudedMacroElement< 3 >.output_macro_element_boundaries(), oomph::QMacroElement< 2 >.output_macro_element_boundaries(), oomph::QMacroElement< 3 >.output_macro_element_boundaries(), oomph::MyProblem.output_solution(), oomph::ODEProblem.output_solution(), oomph::LinearisedAxisymmetricNavierStokesEquations.output_veloc(), oomph::AxisymmetricNavierStokesEquations.output_veloc(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.output_veloc(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.output_veloc(), oomph::LinearisedNavierStokesEquations.output_veloc(), oomph::NavierStokesEquations< DIM >.output_veloc(), oomph::PolarNavierStokesEquations.output_veloc(), oomph::SphericalNavierStokesEquations.output_veloc(), oomph::TreeBasedRefineableMeshBase.p_adapt_mesh(), oomph::GeneralisedNewtonianQCrouzeixRaviartElement< DIM >.p_nst(), oomph::GeneralisedNewtonianTCrouzeixRaviartElement< DIM >.p_nst(), oomph::QCrouzeixRaviartElement< DIM >.p_nst(), oomph::TCrouzeixRaviartElement< DIM >.p_nst(), oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >.p_refine(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >.p_refine(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >.p_refine(), oomph::SarahBL.P_sarah(), SarahBL.P_sarah(), Eigen::internal::Packet2cf.Packet2cf(), TwoDDGProblem< ELEMENT >.parameter_study(), parametrizedline(), Eigen::internal.pdiv< Packet4f >(), Eigen::internal.pfirst< Packet16bf >(), pload_complex_half(), pload_realimag(), pload_realimag_row(), PlanarWave.plot(), Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >.pointAt(), OscillatingCylinder.position(), Leaflet.position(), MyEllipse.position(), Flag_definition::TopOfFlag.position(), Flag_definition::BottomOfFlag.position(), Flag_definition::TipOfFlag.position(), OscillatingWall.position(), SinusoidalWall.position(), SpikedLine.position(), oomph::GeomObject.position(), oomph::StraightLine.position(), oomph::Ellipse.position(), oomph::Circle.position(), oomph::PseudoBucklingRing.position(), oomph::Node.position(), oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >.position(), oomph::MeshAsGeomObject.position(), oomph::Node.position_gen(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >.pre_build(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >.pre_build(), oomph::ILUZeroPreconditioner< CRDoubleMatrix >.preconditioner_solve(), ExactSolution.prescribed_flux_for_unsteady_heat_validation(), ExactSoln.prescribed_traction(), Eigen::internal.pround< Packet4f >(), Eigen::internal.ptranspose(), Eigen::MaxSizeVector< T >.push_back(), oomph::TAxisymmetricPoroelasticityElement< ORDER >.q_edge(), oomph::TPoroelasticityElement< ORDER >.q_edge(), oomph::QuarterPipeDomain.r_B(), oomph::QuarterTubeDomain.r_bot_right_B(), oomph::QuarterTubeDomain.r_bot_right_D(), oomph::QuarterCircleSectorDomain.r_bot_right_E(), oomph::QuarterTubeDomain.r_bot_right_F(), oomph::QuarterTubeDomain.r_bot_right_L(), oomph::QuarterCircleSectorDomain.r_bot_right_N(), oomph::QuarterTubeDomain.r_bot_right_R(), oomph::QuarterCircleSectorDomain.r_bot_right_S(), oomph::QuarterTubeDomain.r_bot_right_U(), oomph::QuarterCircleSectorDomain.r_bot_right_W(), oomph::QuarterTubeDomain.r_centr_B(), oomph::QuarterTubeDomain.r_centr_D(), oomph::QuarterCircleSectorDomain.r_centr_E(), oomph::QuarterTubeDomain.r_centr_F(), oomph::QuarterTubeDomain.r_centr_L(), oomph::QuarterCircleSectorDomain.r_centr_N(), oomph::QuarterTubeDomain.r_centr_R(), oomph::QuarterCircleSectorDomain.r_centr_S(), oomph::QuarterTubeDomain.r_centr_U(), oomph::QuarterCircleSectorDomain.r_centr_W(), oomph::QuarterPipeDomain.r_D(), oomph::CollapsibleChannelDomain.r_E_collapsible(), oomph::QuarterPipeDomain.r_F(), oomph::EighthSphereDomain.r_front_B(), oomph::EighthSphereDomain.r_front_D(), oomph::EighthSphereDomain.r_front_L(), oomph::EighthSphereDomain.r_front_R(), oomph::EighthSphereDomain.r_front_U(), oomph::QuarterPipeDomain.r_L(), oomph::FishDomain.r_lower_body_E(), oomph::FishDomain.r_lower_body_N(), oomph::FishDomain.r_lower_body_S(), oomph::FishDomain.r_lower_body_W(), oomph::FishDomain.r_lower_fin_E(), oomph::FishDomain.r_lower_fin_N(), oomph::FishDomain.r_lower_fin_S(), oomph::FishDomain.r_lower_fin_W(), oomph::CollapsibleChannelDomain.r_N_collapsible(), oomph::QuarterPipeDomain.r_R(), oomph::EighthSphereDomain.r_right_B(), oomph::EighthSphereDomain.r_right_D(), oomph::EighthSphereDomain.r_right_F(), oomph::EighthSphereDomain.r_right_L(), oomph::EighthSphereDomain.r_right_U(), oomph::CollapsibleChannelDomain.r_S_collapsible(), oomph::QuarterTubeDomain.r_top_left_B(), oomph::QuarterTubeDomain.r_top_left_D(), oomph::QuarterCircleSectorDomain.r_top_left_E(), oomph::QuarterTubeDomain.r_top_left_F(), oomph::QuarterTubeDomain.r_top_left_L(), oomph::QuarterCircleSectorDomain.r_top_left_N(), oomph::QuarterTubeDomain.r_top_left_R(), oomph::QuarterCircleSectorDomain.r_top_left_S(), oomph::QuarterTubeDomain.r_top_left_U(), oomph::QuarterCircleSectorDomain.r_top_left_W(), oomph::QuarterPipeDomain.r_U(), oomph::EighthSphereDomain.r_up_B(), oomph::EighthSphereDomain.r_up_D(), oomph::EighthSphereDomain.r_up_F(), oomph::EighthSphereDomain.r_up_L(), oomph::EighthSphereDomain.r_up_R(), oomph::FishDomain.r_upper_body_E(), oomph::FishDomain.r_upper_body_N(), oomph::FishDomain.r_upper_body_S(), oomph::FishDomain.r_upper_body_W(), oomph::FishDomain.r_upper_fin_N(), oomph::FishDomain.r_upper_fin_S(), oomph::FishDomain.r_upper_fin_W(), oomph::CollapsibleChannelDomain.r_W_collapsible(), GlobalParameters.radius(), oomph::Data.range_check(), oomph::FiniteElement.raw_nodal_position(), oomph::FiniteElement.raw_nodal_position_gen(), oomph::FiniteElement.raw_nodal_value(), oomph::Node.raw_value(), oomph::Data.read(), oomph::Node.read(), Eigen::internal.real_2x2_jacobi_svd(), oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >.rebuild_from_sons(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >.rebuild_from_sons(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >.rebuild_from_sons(), oomph::RefineableQSpectralElement< 3 >.rebuild_from_sons(), oomph::RefineableQSpectralElement< 1 >.rebuild_from_sons(), oomph::RefineableQSpectralElement< 2 >.rebuild_from_sons(), MPIContainer.receive(), Eigen::internal::AndReducer.reduce(), Eigen::internal::OrReducer.reduce(), Eigen::internal::ArgMinPairReducer< T >.reduce(), Eigen::internal::MeanReducer< T >.reduce(), Eigen::internal::SumReducer< T >.reduce(), Eigen::internal::MaxReducer< T, NaNPropagation >.reduce(), Eigen::internal::MinReducer< T, NaNPropagation >.reduce(), Eigen::internal::ProdReducer< T >.reduce(), Eigen::internal::ArgMaxPairReducer< T >.reduce(), TriangleMeshWall.refineTriangle(), oomph::ImmersedRigidBodyTriangleMeshPolygon.reset_reference_configuration(), TriangleMeshWall.resetForceTorque(), resize(), oomph::Data.resize(), CGHandler.restart(), Camera.rotateAroundTarget(), test_tensor_ostream_impl< Scalar, 0, Layout >.run(), test_tensor_ostream_impl< Scalar, 1, Layout >.run(), test_tensor_ostream_impl< Scalar, 2, Layout >.run(), test_tensor_ostream_impl< Scalar, 3, Layout >.run(), test_tensor_ostream_impl< bool, 2, Layout >.run(), test_tensor_ostream_impl< std::complex< Scalar >, 2, Layout >.run(), bench_impl< Transformation, N >.run(), Eigen::internal::transform_rotation_impl< Mode >.run(), Eigen::internal::transform_rotation_impl< Isometry >.run(), evaluate_defaults_action_t.run(), Eigen::internal::quaternionbase_assign_impl< Other, 3, 3 >.run(), Eigen::internal::zeta_impl< Scalar >.run(), run_fixed_size_test(), run_test(), Eigen::ThreadPoolTempl< Environment >.ScheduleWithHint(), MPIContainer.send(), Eigen::internal::tuple_coeff< Idx, ValueT >.set(), Eigen::internal::tuple_coeff< 0, ValueT >.set(), UnstructuredImmersedEllipseProblem< ELEMENT >.set_boundary_velocity(), oomph::ContinuationStorageScheme.set_consistent_pinned_positions(), oomph::ContinuationStorageScheme.set_consistent_pinned_values(), oomph::Problem.set_dofs(), UnsteadyHeatProblem< ELEMENT >.set_initial_condition(), RayleighProblem< ELEMENT, TIMESTEPPER >.set_initial_condition(), RayleighTractionProblem< ELEMENT, TIMESTEPPER >.set_initial_condition(), EulerProblem.set_initial_conditions(), oomph::NewmarkBDF< NSTEPS >.set_newmark_veloc_weights(), oomph::Node.set_position_time_stepper(), oomph::TAxisymmetricPoroelasticityElement< ORDER >.set_q_edge(), oomph::SuperLUSolver.set_solver_type(), oomph::Data.set_time_stepper(), oomph::MyProblem.set_up_impulsive_initial_condition(), oomph::Data.set_value(), oomph::Newmark< NSTEPS >.set_weights(), tetgenmesh.setapex(), StatisticsVector< T >.setCGTimeAveragingInterval(), StatisticsVector< T >.setCGTimeMin(), tetgenmesh.setdest(), tetgenmesh.setoppo(), tetgenmesh.setorg(), TriangleMeshWall.setSpecies(), Eigen::SluMatrix.setStorageType(), StatisticsVector< T >.setTimeMaxStat(), my_problem.setupInitialConditions(), LeesEdwardsDemo.setupInitialConditions(), TimeDependentPeriodicBoundary3DSelfTest.setupInitialConditions(), TimeDependentPeriodicBoundaryTest.setupInitialConditions(), RotatingDrum.setupInitialConditions(), GetDistanceAndNormalForTriangleWalls.setupInitialConditions(), oomph::SelfStartingBDF2.shift_time_positions(), oomph::IMRBase.shift_time_positions(), oomph::Steady< NSTEPS >.shift_time_positions(), oomph::Newmark< NSTEPS >.shift_time_positions(), oomph::NewmarkBDF< NSTEPS >.shift_time_positions(), oomph::BDF< NSTEPS >.shift_time_positions(), oomph::SelfStartingBDF2.shift_time_values(), oomph::IMRBase.shift_time_values(), oomph::Steady< NSTEPS >.shift_time_values(), oomph::Newmark< 2 >.shift_time_values(), oomph::NewmarkBDF< NSTEPS >.shift_time_values(), oomph::BDF< NSTEPS >.shift_time_values(), GlobalParameters.sin_cos_velocity_field(), GlobalParameters.sin_cos_vorticity(), oomph::ChannelWithLeafletDomain.slanted_bound_up(), oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >.slanted_bound_up(), Eigen::QuaternionBase< Derived >.slerp(), Eigen::Rotation2D< Scalar_ >.slerp(), slerp_eigen(), slerp_gael(), slerp_legacy(), slerp_legacy_nlerp(), slerp_rw(), oomph::TetMeshBase.snap_nodes_onto_geometric_objects(), oomph::UnstructuredTwoDMeshGeometryBase.snap_nodes_onto_geometric_objects(), ABCProblem< ELEMENT, TIMESTEPPERT >.solve(), oomph::BiCGStab< MATRIX >.solve_helper(), sparse_block(), Eigen::ThreadPoolTempl< Environment >.Steal(), tetgenmesh.stpivot(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations.strain_rate(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.strain_rate(), tetgenmesh.symedgeself(), tetgenmesh.symself(), test_comparison_sugar(), test_const_tensor_ostream(), test_multithread_random(), test_nested_ops_with_ref(), test_tensor_asym(), test_tensor_dynsym(), test_tensor_randacc(), test_tensor_sym(), tetgenmesh.tfnextself(), oomph::Time.time(), Time2Finish.Time2Finish(), oomph::TimeStepper.time_derivative(), oomph::IMRODEElement.time_interpolate_time(), oomph::TimingHelpers.timer(), InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >.timestep(), rapidjson::GenericReader< Encoding, Allocator >.to_int(), rapidjson::Writer< Stream, Encoding, Allocator >.to_int(), oomph::SarahBL.Total_Diss_lead_sarah(), SarahBL.Total_Diss_lead_sarah(), oomph::SarahBL.Total_Diss_sarah(), SarahBL.Total_Diss_sarah(), Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >.transform(), Eigen::ParametrizedLine< Scalar_, AmbientDim_, Options_ >.transform(), transform(), Eigen::Transform< Scalar_, Dim_, Mode_, Options_ >.Transform(), Eigen::AlignedBox< Scalar_, AmbientDim_ >.translate(), Eigen::internal.trig_reduce_medium_double(), Eigen::internal.trig_reduce_small_double(), tetgenmesh.tsbond(), tetgenmesh.tsdissolve(), tetgenmesh.tspivot(), tetgenmesh.tssbond1(), tetgenmesh.tssdissolve1(), tetgenmesh.tsspivot1(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >.TurekProblem(), SpineGravityTractionElement< ELEMENT >.u(), BiharmonicTestFunctions2.u_E(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >.u_nst(), oomph::NavierStokesEquations< DIM >.u_nst(), oomph::SpaceTimeNavierStokesEquations< DIM >.u_nst(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >.u_nst(), oomph::SarahBL.U_sarah(), SarahBL.U_sarah(), oomph::SphericalNavierStokesEquations.u_spherical_nst(), BiharmonicTestFunctions2.u_W(), tetgenmesh.uninfect(), tetgenmesh.unmarkedge(), tetgenmesh.unmarkface(), tetgenmesh.unmarktest(), RotatingCylinderProblem< ELEMENT, TIMESTEPPER >.unsteady_run(), InterfaceProblem< ELEMENT, TIMESTEPPER >.unsteady_run(), ElasticInterfaceProblem< ELEMENT, TIMESTEPPER >.unsteady_run(), OscRingNStProblem< ELEMENT >.unsteady_run(), RayleighProblem< ELEMENT, TIMESTEPPER >.unsteady_run(), RayleighTractionProblem< ELEMENT, TIMESTEPPER >.unsteady_run(), FlowAroundCylinderProblem< ELEMENT >.unsteady_simulation(), Flag_definition.upper_tip(), oomph::SarahBL.V_sarah(), SarahBL.V_sarah(), oomph::Node.value(), oomph::Data.value(), Eigen::internal::tuple_coeff< Idx, ValueT >.value_known_statically(), oomph::Data.value_pt(), Eigen::internal::tuple_coeff< Idx, ValueT >.values_up_to_known_statically(), Eigen::internal::tuple_coeff< Idx, ValueT >.values_up_to_statically_known_to_increase(), Jeffery_Solution.velocity(), OscillatingCylinder.velocity(), vkill_trailing(), Eigen::ThreadPoolTempl< Environment >.WaitForWork(), Eigen::ThreadPoolTempl< Environment >.WorkerLoop(), TriangleMeshWall.write(), CFile.writeP4C(), CFile.writeP4W(), TriangleMeshWall.writeVTK(), oomph::Node.x(), oomph::Node.x_gen(), oomph::Node.x_gen_range_check(), oomph::Node.x_pt(), oomph::SarahBL.X_sarah(), SarahBL.X_sarah(), oomph::SarahBL.Y_sarah(), and SarahBL.Y_sarah().
True
plotPSD.True