MercuryDPM: StressStrainControlBoundarySelfTest.cpp File Reference
StressStrainControlBoundarySelfTest.cpp File Reference
#include <Species/LinearPlasticViscoelasticFrictionSpecies.h>
#include <Mercury3D.h>
#include <Boundaries/PeriodicBoundary.h>
#include <Boundaries/StressStrainControlBoundary.h>
#include "Boundaries/LeesEdwardsBoundary.h"
#include <CMakeDefinitions.h>
Classes
class StressStrainControl
[REV_ISO:headers]
Functions
int main (int argc UNUSED, char *argv[] UNUSED)
Function Documentation
main()
int main (int argc UNUSED, char *argv[] UNUSED)
 {
     //helpers::writeToFile("xyz.restart","abc");
     Matrix3D stressGoal;
     stressGoal.XX = 0.0;
     stressGoal.YY = 0.0;
     stressGoal.ZZ = 0.0;
     stressGoal.XY = -2.0;
     Matrix3D strainRate;
     strainRate.XY = 0.0;
     Matrix3D gainFactor;
     gainFactor.XY = 0.0001;
     gainFactor.XX = 0.0001;
     gainFactor.YY = 0.0001;
     gainFactor.ZZ = 0.0001;
     bool isStrainRateControlled = true;
     //instantiate the class
     StressStrainControl dpm(stressGoal, strainRate, gainFactor, isStrainRateControlled);
     //set name
     dpm.setName("StressStrainControlBoundarySelfTest");
     //set output and time stepping properties
     dpm.setTimeMax(0.1);
     dpm.eneFile.setSaveCount(1000);
     //dpm.dataFile.setFileType(FileType::NO_FILE);
     //dpm.restartFile.setFileType(FileType::ONE_FILE);
     //dpm.fStatFile.setFileType(FileType::NO_FILE);
     dpm.eneFile.setFileType(FileType::ONE_FILE);
     //solve
     dpm.solve();
     //dpm.writeRestartFile();
 }
References DPMBase::eneFile, ONE_FILE, File::setFileType(), DPMBase::setName(), File::setSaveCount(), DPMBase::setTimeMax(), DPMBase::solve(), Matrix3D::XX, Matrix3D::XY, Matrix3D::YY, and Matrix3D::ZZ.