MercuryDPM: HeatFluidCoupled< Particle > Class Template Reference
HeatFluidCoupled< Particle > Class Template Reference
Class of particles that store both temperature and liquid volume, which is adapted for the CFD-DEM studies.
#include <HeatFluidCoupledParticle.h>
Public Member Functions
HeatFluidCoupled ()=default
HeatFluidCoupled constructor creates a HeatFluidCoupled at (0,0,0) with radius, mass and inertia equal to 1.
HeatFluidCoupled (const HeatFluidCoupled &p)=default
HeatFluidCoupled copy constructor, which accepts as input a reference to a HeatFluidCoupled. It creates a copy of this HeatFluidCoupled and all it's information. Usually it is better to use the copy() function for polymorphism.
~HeatFluidCoupled () override=default
HeatFluidCoupled destructor, needs to be implemented and checked if it removes tangential spring information.
HeatFluidCoupled * copy () const override
HeatFluidCoupled copy method. Use copy constructor of this HeatFluidCoupled to create a copy on the heap, useful for polymorphism.
std::string getName () const override
Returns the name of the object; in this case "HeatFluidCoupledParticle".
unsigned getNumberOfFieldsVTK () const override
Tells the vtkWriter how many fields should be written for this particle type.
std::string getTypeVTK (unsigned) const override
Tells the vtkWriter the type of each field written for this particle type.
std::string getNameVTK (unsigned i) const override
Tells the vtkWriter the name of each field written for this particle type.
std::vector< Mdouble > getFieldVTK (unsigned i) const override
Tells the vtkWriter the value of each field written for this particle type.
void actionsAfterTimeStep () override
The actionAfterTimeStep is defined in the species, as we cannot extract the species properties of a HeatFluidCoupled*Species.
Public Member Functions inherited from Thermal< LiquidFilm< Particle > >
Thermal ()
Basic Particle constructor, creates a particle at (0,0,0) with radius, mass and inertia equal to 1.
Thermal (const Thermal &p)
Particle copy constructor, which accepts as input a reference to a Particle. It creates a copy of this Particle and all it's information. Usually it is better to use the copy() function for polymorphism.
~Thermal () override=default
Particle destructor, needs to be implemented and checked if it removes tangential spring information.
Thermal * copy () const override
Particle copy method. It calls to copy constructor of this Particle, useful for polymorfism.
void write (std::ostream &os) const override
std::string getName () const override
void read (std::istream &is) override
Mdouble getTemperature () const
void setTemperature (Mdouble temperature)
void addTemperature (Mdouble temperature)
void setTemperatureDependentDensity (const std::function< double(double)> &temperatureDependentDensity)
const std::function< double(double)> & getTemperatureDependentDensity () const
const std::function< double(double)> & getTimeDependentTemperature () const
void setTimeDependentTemperature (const std::function< double(double)> &timeDependentTemperature)
void actionsAfterTimeStep () override
bool isSphericalParticle () const override
Public Member Functions inherited from LiquidFilm< Particle >
LiquidFilm ()
Basic Particle constructor, creates an Particle at (0,0,0) with radius, mass and inertia equal to 1.
LiquidFilm (const LiquidFilm &p)
Particle copy constructor, which accepts as input a reference to a Particle. It creates a copy of this Particle and all it's information. Usually it is better to use the copy() function for polymorfism.
~LiquidFilm () override=default
Particle destructor, needs to be implemented and checked if it removes tangential spring information.
LiquidFilm * copy () const override
Particle copy method. It calls to copy constructor of this Particle, useful for polymorfism.
void write (std::ostream &os) const override
std::string getName () const override
void read (std::istream &is) override
Mdouble getLiquidVolume () const
void setLiquidVolume (Mdouble liquidVolume)
void addLiquidVolume (Mdouble liquidVolume)
Mdouble getFullLiquidVolume () const
Mdouble getLiquidBridgeVolume () const
Mdouble getTotalEvaporatedLiquidVolume () const
void setTotalEvaporatedLiquidVolume (Mdouble liquidVolume)
void addTotalEvaporatedLiquidVolume (Mdouble liquidVolume)
Mdouble getMeanLiquidFilmThickness () const
Mdouble getRelativeLiquidVolume () const
unsigned getNumberOfFieldsVTK () const override
std::string getTypeVTK (unsigned i) const override
std::string getNameVTK (unsigned i) const override
std::vector< Mdouble > getFieldVTK (unsigned i) const override
bool isSphericalParticle () const override
Additional Inherited Members
Protected Attributes inherited from Thermal< LiquidFilm< Particle > >
Mdouble temperature_
Protected Attributes inherited from LiquidFilm< Particle >
Mdouble liquidVolume_
Mdouble totalEvaporatedLiquidVolume_
Detailed Description
template<class Particle>
class HeatFluidCoupled< Particle >
Class of particles that store both temperature and liquid volume, which is adapted for the CFD-DEM studies.
In some CFD-DEM studies, a drying process needs to be simulated. Therefore, we selected the drying/liquid evaporation model of Azmir et al. (2018), which considers heat and mass transfer between the liquid film on the particles and the surrounding air. Their model considers convection, conduction, radiation of heat, and evaporation of liquid. Conduction is already implemented in ThermalParticles, from which this class derives; convection and radiation is still missing. This class implements evaporation model.
Constructor & Destructor Documentation
HeatFluidCoupled() [1/2]
template<class Particle > HeatFluidCoupled< Particle >::HeatFluidCoupled () default
HeatFluidCoupled constructor creates a HeatFluidCoupled at (0,0,0) with radius, mass and inertia equal to 1.
HeatFluidCoupled() [2/2]
template<class Particle > HeatFluidCoupled< Particle >::HeatFluidCoupled (const HeatFluidCoupled< Particle > & p) default
HeatFluidCoupled copy constructor, which accepts as input a reference to a HeatFluidCoupled. It creates a copy of this HeatFluidCoupled and all it's information. Usually it is better to use the copy() function for polymorphism.
Constructor that copies most of the properties of the given particle. Please note that not everything is copied, for example the position in the HGrid is not determined yet by the end of this constructor. It also does not copy the interactions and the pointer to the handler that handles this particle. Use with care.
Parameters
[in,out] p Reference to the HeatFluidCoupled this one should become a copy of.
~HeatFluidCoupled()
template<class Particle > HeatFluidCoupled< Particle >::~HeatFluidCoupled () override default
HeatFluidCoupled destructor, needs to be implemented and checked if it removes tangential spring information.
Destructor that asks the ParticleHandler to check if this was the smallest or largest particle and adjust itself accordingly.
Member Function Documentation
actionsAfterTimeStep()
template<class Particle > void HeatFluidCoupled< Particle >::actionsAfterTimeStep () inline override
The actionAfterTimeStep is defined in the species, as we cannot extract the species properties of a HeatFluidCoupled*Species.
{
         this->getSpecies()->actionsAfterTimeStep(this);
     }
copy()
template<class Particle > HeatFluidCoupled* HeatFluidCoupled< Particle >::copy () const inline override
HeatFluidCoupled copy method. Use copy constructor of this HeatFluidCoupled to create a copy on the heap, useful for polymorphism.
Returns
pointer to the particle's copy.
     {
         return new HeatFluidCoupled<Particle>(*this);
     }
getFieldVTK()
template<class Particle > std::vector<Mdouble> HeatFluidCoupled< Particle >::getFieldVTK (unsigned i) const inline override
Tells the vtkWriter the value of each field written for this particle type.
{
         if (i==0)
             return { this->getFullLiquidVolume() };
         else if (i==1)
             return { this->liquidVolume_ };
         else if (i==2)
             return { this->getLiquidBridgeVolume() };
         else if (i==3)
             return { this->totalEvaporatedLiquidVolume_ };
         else /* i=4 */
             return { this->temperature_ };
     }
References LiquidFilm< Particle >::getFullLiquidVolume(), LiquidFilm< Particle >::getLiquidBridgeVolume(), i, LiquidFilm< Particle >::liquidVolume_, Thermal< LiquidFilm< Particle > >::temperature_, and LiquidFilm< Particle >::totalEvaporatedLiquidVolume_.
getName()
template<class Particle > std::string HeatFluidCoupled< Particle >::getName () const inline override
Returns the name of the object; in this case "HeatFluidCoupledParticle".
Returns
The object name.
     {
         return "HeatFluidCoupled" + Particle::getName();
     }
References getName().
getNameVTK()
template<class Particle > std::string HeatFluidCoupled< Particle >::getNameVTK (unsigned i) const inline override
Tells the vtkWriter the name of each field written for this particle type.
{
         if (i==0)
             return "fullLiquidVolume";
         else if (i==1)
             return "liquidFilmVolume";
         else if (i==2)
             return "liquidBridgeVolume";
         else if (i==3)
             return "totalEvaporatedLiquidVolume";
         else /* i=4 */
             return "temperature";
     }
References i.
getNumberOfFieldsVTK()
template<class Particle > unsigned HeatFluidCoupled< Particle >::getNumberOfFieldsVTK () const inline override
Tells the vtkWriter how many fields should be written for this particle type.
 { return 5; }
getTypeVTK()
template<class Particle > std::string HeatFluidCoupled< Particle >::getTypeVTK (unsigned) const inline override
Tells the vtkWriter the type of each field written for this particle type.
 { return "Float32"; }
The documentation for this class was generated from the following file:
HeatFluidCoupledParticle.h