MercuryDPM: Eigen::ComplexSchur< MatrixType_ > Class Template Reference
Eigen::ComplexSchur< MatrixType_ > Class Template Reference
Dense linear problems and decompositions » Reference » Eigenvalues_Module
Performs a complex Schur decomposition of a real or complex square matrix.
#include <ComplexSchur.h>
Public Types
enum {
RowsAtCompileTime = MatrixType::RowsAtCompileTime , ColsAtCompileTime = MatrixType::ColsAtCompileTime , Options = internal::traits<MatrixType>::Options , MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime ,
MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime
}
typedef MatrixType_ MatrixType
typedef MatrixType::Scalar Scalar
Scalar type for matrices of type MatrixType_.
typedef NumTraits< Scalar >::Real RealScalar
typedef Eigen::Index Index
typedef std::complex< RealScalar > ComplexScalar
Complex scalar type for MatrixType_.
typedef Matrix< ComplexScalar, RowsAtCompileTime, ColsAtCompileTime, Options, MaxRowsAtCompileTime, MaxColsAtCompileTime > ComplexMatrixType
Type for the matrices in the Schur decomposition.
Public Member Functions
ComplexSchur (Index size=RowsAtCompileTime==Dynamic ? 1 :RowsAtCompileTime)
Default constructor.
template<typename InputType >
ComplexSchur (const EigenBase< InputType > &matrix, bool computeU=true)
Constructor; computes Schur decomposition of given matrix.
const ComplexMatrixType & matrixU () const
Returns the unitary matrix in the Schur decomposition.
const ComplexMatrixType & matrixT () const
Returns the triangular matrix in the Schur decomposition.
template<typename InputType >
ComplexSchur & compute (const EigenBase< InputType > &matrix, bool computeU=true)
Computes Schur decomposition of given matrix.
template<typename HessMatrixType , typename OrthMatrixType >
ComplexSchur & computeFromHessenberg (const HessMatrixType &matrixH, const OrthMatrixType &matrixQ, bool computeU=true)
Compute Schur decomposition from a given Hessenberg matrix.
ComputationInfo info () const
Reports whether previous computation was successful.
ComplexSchur & setMaxIterations (Index maxIters)
Sets the maximum number of iterations allowed.
Index getMaxIterations ()
Returns the maximum number of iterations.
template<typename InputType >
ComplexSchur< MatrixType > & compute (const EigenBase< InputType > &matrix, bool computeU)
template<typename HessMatrixType , typename OrthMatrixType >
ComplexSchur< MatrixType > & computeFromHessenberg (const HessMatrixType &matrixH, const OrthMatrixType &matrixQ, bool computeU)
Static Public Attributes
static const int m_maxIterationsPerRow = 30
Maximum number of iterations per row.
Protected Attributes
ComplexMatrixType m_matT
ComplexMatrixType m_matU
HessenbergDecomposition< MatrixType > m_hess
ComputationInfo m_info
bool m_isInitialized
bool m_matUisUptodate
Index m_maxIters
Private Member Functions
bool subdiagonalEntryIsNeglegible (Index i)
ComplexScalar computeShift (Index iu, Index iter)
void reduceToTriangularForm (bool computeU)
Friends
struct internal::complex_schur_reduce_to_hessenberg< MatrixType, NumTraits< Scalar >::IsComplex >
Detailed Description
template<typename MatrixType_>
class Eigen::ComplexSchur< MatrixType_ >
Performs a complex Schur decomposition of a real or complex square matrix.
\eigenvalues_module
Template Parameters
MatrixType_ the type of the matrix of which we are computing the Schur decomposition; this is expected to be an instantiation of the Matrix class template.
Given a real or complex square matrix A, this class computes the Schur decomposition: \(A = U T U^*\) where U is a unitary complex matrix, and T is a complex upper triangular matrix. The diagonal of the matrix T corresponds to the eigenvalues of the matrix A.
Call the function compute() to compute the Schur decomposition of a given matrix. Alternatively, you can use the ComplexSchur(const MatrixType&, bool) constructor which computes the Schur decomposition at construction time. Once the decomposition is computed, you can use the matrixU() and matrixT() functions to retrieve the matrices U and V in the decomposition.
Note
This code is inspired from Jampack
See also
class RealSchur, class EigenSolver, class ComplexEigenSolver
Member Typedef Documentation
ComplexMatrixType
template<typename MatrixType_ > typedef Matrix<ComplexScalar, RowsAtCompileTime, ColsAtCompileTime, Options, MaxRowsAtCompileTime, MaxColsAtCompileTime> Eigen::ComplexSchur< MatrixType_ >::ComplexMatrixType
Type for the matrices in the Schur decomposition.
This is a square matrix with entries of type ComplexScalar. The size is the same as the size of MatrixType_.
ComplexScalar
template<typename MatrixType_ > typedef std::complex<RealScalar> Eigen::ComplexSchur< MatrixType_ >::ComplexScalar
Complex scalar type for MatrixType_.
This is std::complex<Scalar> if Scalar is real (e.g., float or double) and just Scalar if Scalar is complex.
Index
template<typename MatrixType_ > typedef Eigen::Index Eigen::ComplexSchur< MatrixType_ >::Index
Deprecated:
since Eigen 3.3
MatrixType
template<typename MatrixType_ > typedef MatrixType_ Eigen::ComplexSchur< MatrixType_ >::MatrixType
RealScalar
template<typename MatrixType_ > typedef NumTraits<Scalar>::Real Eigen::ComplexSchur< MatrixType_ >::RealScalar
Scalar
template<typename MatrixType_ > typedef MatrixType::Scalar Eigen::ComplexSchur< MatrixType_ >::Scalar
Scalar type for matrices of type MatrixType_.
Member Enumeration Documentation
anonymous enum
template<typename MatrixType_ > anonymous enum
Enumerator
RowsAtCompileTime
ColsAtCompileTime
Options
MaxRowsAtCompileTime
MaxColsAtCompileTime
        {
     RowsAtCompileTime = MatrixType::RowsAtCompileTime,
     ColsAtCompileTime = MatrixType::ColsAtCompileTime,
     Options = internal::traits<MatrixType>::Options,
     MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime,
     MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime
   };
Constructor & Destructor Documentation
ComplexSchur() [1/2]
template<typename MatrixType_ > Eigen::ComplexSchur< MatrixType_ >::ComplexSchur (Index size = RowsAtCompileTime == Dynamic ? 1 : RowsAtCompileTime) inline explicit
Default constructor.
Parameters
[in] size Positive integer, size of the matrix whose Schur decomposition will be computed.
The default constructor is useful in cases in which the user intends to perform decompositions via compute(). The size parameter is only used as a hint. It is not an error to give a wrong size, but it may impair performance.
See also
compute() for an example.
                                                                       : RowsAtCompileTime)
       : m_matT(size, size),
         m_matU(size, size),
         m_hess(size),
         m_isInitialized(false),
         m_matUisUptodate(false),
         m_maxIters(-1) {}
ComplexSchur() [2/2]
template<typename MatrixType_ > template<typename InputType > Eigen::ComplexSchur< MatrixType_ >::ComplexSchur (const EigenBase< InputType > & matrix, bool computeU = true) inline explicit
Constructor; computes Schur decomposition of given matrix.
Parameters
[in] matrix Square matrix whose Schur decomposition is to be computed.
[in] computeU If true, both T and U are computed; if false, only T is computed.
This constructor calls compute() to compute the Schur decomposition.
See also
matrixT() and matrixU() for examples.
       : m_matT(matrix.rows(), matrix.cols()),
         m_matU(matrix.rows(), matrix.cols()),
         m_hess(matrix.rows()),
         m_isInitialized(false),
         m_matUisUptodate(false),
         m_maxIters(-1) {
     compute(matrix.derived(), computeU);
   }
References Eigen::ComplexSchur< MatrixType_ >::compute(), and matrix().
Member Function Documentation
compute() [1/2]
template<typename MatrixType_ > template<typename InputType > ComplexSchur<MatrixType>& Eigen::ComplexSchur< MatrixType_ >::compute (const EigenBase< InputType > & matrix, bool computeU)
{
   m_matUisUptodate = false;
   eigen_assert(matrix.cols() == matrix.rows());
   if (matrix.cols() == 1) {
     m_matT = matrix.derived().template cast<ComplexScalar>();
     if (computeU) m_matU = ComplexMatrixType::Identity(1, 1);
     m_info = Success;
     m_isInitialized = true;
     m_matUisUptodate = computeU;
     return *this;
   }
   internal::complex_schur_reduce_to_hessenberg<MatrixType, NumTraits<Scalar>::IsComplex>::run(*this, matrix.derived(),
                                                                                               computeU);
   computeFromHessenberg(m_matT, m_matU, computeU);
   return *this;
 }
References Eigen::ComplexSchur< MatrixType_ >::computeFromHessenberg(), eigen_assert, Eigen::ComplexSchur< MatrixType_ >::m_info, Eigen::ComplexSchur< MatrixType_ >::m_isInitialized, Eigen::ComplexSchur< MatrixType_ >::m_matT, Eigen::ComplexSchur< MatrixType_ >::m_matU, Eigen::ComplexSchur< MatrixType_ >::m_matUisUptodate, matrix(), Eigen::run(), and Eigen::Success.
compute() [2/2]
template<typename MatrixType_ > template<typename InputType > ComplexSchur& Eigen::ComplexSchur< MatrixType_ >::compute (const EigenBase< InputType > & matrix, bool computeU = true)
Computes Schur decomposition of given matrix.
Parameters
[in] matrix Square matrix whose Schur decomposition is to be computed.
[in] computeU If true, both T and U are computed; if false, only T is computed.
Returns
Reference to *this
The Schur decomposition is computed by first reducing the matrix to Hessenberg form using the class HessenbergDecomposition. The Hessenberg matrix is then reduced to triangular form by performing QR iterations with a single shift. The cost of computing the Schur decomposition depends on the number of iterations; as a rough guide, it may be taken on the number of iterations; as a rough guide, it may be taken to be \(25n^3\) complex flops, or \(10n^3\) complex flops if computeU is false.
Example:
MatrixXcf A = MatrixXcf::Random(4, 4);
ComplexSchur<MatrixXcf> schur(4);
schur.compute(A);
cout << "The matrix T in the decomposition of A is:" << endl << schur.matrixT() << endl;
schur.compute(A.inverse());
cout << "The matrix T in the decomposition of A^(-1) is:" << endl << schur.matrixT() << endl;
Output:
See also
compute(const MatrixType&, bool, Index)
Referenced by Eigen::ComplexSchur< MatrixType_ >::ComplexSchur(), Eigen::ComplexEigenSolver< MatrixType_ >::compute(), ctms_decompositions(), and schur().
computeFromHessenberg() [1/2]
template<typename MatrixType_ > template<typename HessMatrixType , typename OrthMatrixType > ComplexSchur<MatrixType>& Eigen::ComplexSchur< MatrixType_ >::computeFromHessenberg (const HessMatrixType & matrixH, const OrthMatrixType & matrixQ, bool computeU)
{
   m_matT = matrixH;
   if (computeU) m_matU = matrixQ;
   reduceToTriangularForm(computeU);
   return *this;
 }
References Eigen::ComplexSchur< MatrixType_ >::m_matT, Eigen::ComplexSchur< MatrixType_ >::m_matU, and Eigen::ComplexSchur< MatrixType_ >::reduceToTriangularForm().
computeFromHessenberg() [2/2]
template<typename MatrixType_ > template<typename HessMatrixType , typename OrthMatrixType > ComplexSchur& Eigen::ComplexSchur< MatrixType_ >::computeFromHessenberg (const HessMatrixType & matrixH, const OrthMatrixType & matrixQ, bool computeU = true)
Compute Schur decomposition from a given Hessenberg matrix.
Parameters
[in] matrixH Matrix in Hessenberg form H
[in] matrixQ orthogonal matrix Q that transform a matrix A to H : A = Q H Q^T
computeU Computes the matriX U of the Schur vectors
Returns
Reference to *this
This routine assumes that the matrix is already reduced in Hessenberg form matrixH using either the class HessenbergDecomposition or another mean. It computes the upper quasi-triangular matrix T of the Schur decomposition of H When computeU is true, this routine computes the matrix U such that A = U T U^T = (QZ) T (QZ)^T = Q H Q^T where A is the initial matrix
NOTE Q is referenced if computeU is true; so, if the initial orthogonal matrix is not available, the user should give an identity matrix (Q.setIdentity())
See also
compute(const MatrixType&, bool)
Referenced by Eigen::ComplexSchur< MatrixType_ >::compute().
computeShift()
template<typename MatrixType > ComplexSchur< MatrixType >::ComplexScalar Eigen::ComplexSchur< MatrixType >::computeShift (Index iu, Index iter) private
Compute the shift in the current QR iteration.
{
   using std::abs;
   if ((iter == 10 || iter == 20) && iu > 1) {
     // exceptional shift, taken from http://www.netlib.org/eispack/comqr.f
     return abs(numext::real(m_matT.coeff(iu, iu - 1))) + abs(numext::real(m_matT.coeff(iu - 1, iu - 2)));
   }
   // compute the shift as one of the eigenvalues of t, the 2x2
   // diagonal block on the bottom of the active submatrix
   Matrix<ComplexScalar, 2, 2> t = m_matT.template block<2, 2>(iu - 1, iu - 1);
   RealScalar normt = t.cwiseAbs().sum();
   t /= normt;  // the normalization by sf is to avoid under/overflow
   ComplexScalar b = t.coeff(0, 1) * t.coeff(1, 0);
   ComplexScalar c = t.coeff(0, 0) - t.coeff(1, 1);
   ComplexScalar disc = sqrt(c * c + RealScalar(4) * b);
   ComplexScalar det = t.coeff(0, 0) * t.coeff(1, 1) - b;
   ComplexScalar trace = t.coeff(0, 0) + t.coeff(1, 1);
   ComplexScalar eival1 = (trace + disc) / RealScalar(2);
   ComplexScalar eival2 = (trace - disc) / RealScalar(2);
   RealScalar eival1_norm = numext::norm1(eival1);
   RealScalar eival2_norm = numext::norm1(eival2);
   // A division by zero can only occur if eival1==eival2==0.
   // In this case, det==0, and all we have to do is checking that eival2_norm!=0
   if (eival1_norm > eival2_norm)
     eival2 = det / eival1;
   else if (!numext::is_exactly_zero(eival2_norm))
     eival1 = det / eival2;
   // choose the eigenvalue closest to the bottom entry of the diagonal
   if (numext::norm1(eival1 - t.coeff(1, 1)) < numext::norm1(eival2 - t.coeff(1, 1)))
     return normt * eival1;
   else
     return normt * eival2;
 }
References abs(), b, calibrate::c, Eigen::PlainObjectBase< Derived >::coeff(), Eigen::numext::is_exactly_zero(), Eigen::ComplexSchur< MatrixType_ >::m_matT, sqrt(), and plotPSD::t.
Referenced by Eigen::ComplexSchur< MatrixType_ >::reduceToTriangularForm().
getMaxIterations()
template<typename MatrixType_ > Index Eigen::ComplexSchur< MatrixType_ >::getMaxIterations () inline
Returns the maximum number of iterations.
 { return m_maxIters; }
References Eigen::ComplexSchur< MatrixType_ >::m_maxIters.
Referenced by Eigen::ComplexEigenSolver< MatrixType_ >::getMaxIterations(), and schur().
info()
template<typename MatrixType_ > ComputationInfo Eigen::ComplexSchur< MatrixType_ >::info () const inline
Reports whether previous computation was successful.
Returns
Success if computation was successful, NoConvergence otherwise.
{
     eigen_assert(m_isInitialized && "ComplexSchur is not initialized.");
     return m_info;
   }
References eigen_assert, Eigen::ComplexSchur< MatrixType_ >::m_info, and Eigen::ComplexSchur< MatrixType_ >::m_isInitialized.
Referenced by Eigen::ComplexEigenSolver< MatrixType_ >::compute(), Eigen::ComplexEigenSolver< MatrixType_ >::info(), and schur().
matrixT()
template<typename MatrixType_ > const ComplexMatrixType& Eigen::ComplexSchur< MatrixType_ >::matrixT () const inline
Returns the triangular matrix in the Schur decomposition.
Returns
A const reference to the matrix T.
It is assumed that either the constructor ComplexSchur(const MatrixType& matrix, bool computeU) or the member function compute(const MatrixType& matrix, bool computeU) has been called before to compute the Schur decomposition of a matrix.
Note that this function returns a plain square matrix. If you want to reference only the upper triangular part, use:
schur.matrixT().triangularView<Upper>()
Example:
MatrixXcf A = MatrixXcf::Random(4, 4);
cout << "Here is a random 4x4 matrix, A:" << endl << A << endl << endl;
ComplexSchur<MatrixXcf> schurOfA(A, false);  // false means do not compute U
cout << "The triangular matrix T is:" << endl << schurOfA.matrixT() << endl;
Output:
{
     eigen_assert(m_isInitialized && "ComplexSchur is not initialized.");
     return m_matT;
   }
References eigen_assert, Eigen::ComplexSchur< MatrixType_ >::m_isInitialized, and Eigen::ComplexSchur< MatrixType_ >::m_matT.
Referenced by Eigen::ComplexEigenSolver< MatrixType_ >::compute(), Eigen::ComplexEigenSolver< MatrixType_ >::doComputeEigenvectors(), schur(), and Eigen::DGMRES< MatrixType_, Preconditioner_ >::schurValues().
matrixU()
template<typename MatrixType_ > const ComplexMatrixType& Eigen::ComplexSchur< MatrixType_ >::matrixU () const inline
Returns the unitary matrix in the Schur decomposition.
Returns
A const reference to the matrix U.
It is assumed that either the constructor ComplexSchur(const MatrixType& matrix, bool computeU) or the member function compute(const MatrixType& matrix, bool computeU) has been called before to compute the Schur decomposition of a matrix, and that computeU was set to true (the default value).
Example:
MatrixXcf A = MatrixXcf::Random(4, 4);
cout << "Here is a random 4x4 matrix, A:" << endl << A << endl << endl;
ComplexSchur<MatrixXcf> schurOfA(A);
cout << "The unitary matrix U is:" << endl << schurOfA.matrixU() << endl;
Output:
{
     eigen_assert(m_isInitialized && "ComplexSchur is not initialized.");
     eigen_assert(m_matUisUptodate && "The matrix U has not been computed during the ComplexSchur decomposition.");
     return m_matU;
   }
References eigen_assert, Eigen::ComplexSchur< MatrixType_ >::m_isInitialized, Eigen::ComplexSchur< MatrixType_ >::m_matU, and Eigen::ComplexSchur< MatrixType_ >::m_matUisUptodate.
Referenced by Eigen::ComplexEigenSolver< MatrixType_ >::doComputeEigenvectors(), and schur().
reduceToTriangularForm()
template<typename MatrixType > void Eigen::ComplexSchur< MatrixType >::reduceToTriangularForm (bool computeU) private
{
   Index maxIters = m_maxIters;
   if (maxIters == -1) maxIters = m_maxIterationsPerRow * m_matT.rows();
   // The matrix m_matT is divided in three parts.
   // Rows 0,...,il-1 are decoupled from the rest because m_matT(il,il-1) is zero.
   // Rows il,...,iu is the part we are working on (the active submatrix).
   // Rows iu+1,...,end are already brought in triangular form.
   Index iu = m_matT.cols() - 1;
   Index il;
   Index iter = 0;       // number of iterations we are working on the (iu,iu) element
   Index totalIter = 0;  // number of iterations for whole matrix
   while (true) {
     // find iu, the bottom row of the active submatrix
     while (iu > 0) {
       if (!subdiagonalEntryIsNeglegible(iu - 1)) break;
       iter = 0;
       --iu;
     }
     // if iu is zero then we are done; the whole matrix is triangularized
     if (iu == 0) break;
     // if we spent too many iterations, we give up
     iter++;
     totalIter++;
     if (totalIter > maxIters) break;
     // find il, the top row of the active submatrix
     il = iu - 1;
     while (il > 0 && !subdiagonalEntryIsNeglegible(il - 1)) {
       --il;
     }
     /* perform the QR step using Givens rotations. The first rotation
        creates a bulge; the (il+2,il) element becomes nonzero. This
        bulge is chased down to the bottom of the active submatrix. */
     ComplexScalar shift = computeShift(iu, iter);
     JacobiRotation<ComplexScalar> rot;
     rot.makeGivens(m_matT.coeff(il, il) - shift, m_matT.coeff(il + 1, il));
     m_matT.rightCols(m_matT.cols() - il).applyOnTheLeft(il, il + 1, rot.adjoint());
     m_matT.topRows((std::min)(il + 2, iu) + 1).applyOnTheRight(il, il + 1, rot);
     if (computeU) m_matU.applyOnTheRight(il, il + 1, rot);
     for (Index i = il + 1; i < iu; i++) {
       rot.makeGivens(m_matT.coeffRef(i, i - 1), m_matT.coeffRef(i + 1, i - 1), &m_matT.coeffRef(i, i - 1));
       m_matT.coeffRef(i + 1, i - 1) = ComplexScalar(0);
       m_matT.rightCols(m_matT.cols() - i).applyOnTheLeft(i, i + 1, rot.adjoint());
       m_matT.topRows((std::min)(i + 2, iu) + 1).applyOnTheRight(i, i + 1, rot);
       if (computeU) m_matU.applyOnTheRight(i, i + 1, rot);
     }
   }
   if (totalIter <= maxIters)
     m_info = Success;
   else
     m_info = NoConvergence;
   m_isInitialized = true;
   m_matUisUptodate = computeU;
 }
References Eigen::PlainObjectBase< Derived >::coeff(), Eigen::Matrix< Scalar_, Rows_, Cols_, Options_, MaxRows_, MaxCols_ >::coeffRef(), Eigen::PlainObjectBase< Derived >::cols(), Eigen::ComplexSchur< MatrixType_ >::computeShift(), i, Eigen::ComplexSchur< MatrixType_ >::m_info, Eigen::ComplexSchur< MatrixType_ >::m_isInitialized, Eigen::ComplexSchur< MatrixType_ >::m_matT, Eigen::ComplexSchur< MatrixType_ >::m_matU, Eigen::ComplexSchur< MatrixType_ >::m_matUisUptodate, Eigen::ComplexSchur< MatrixType_ >::m_maxIterationsPerRow, Eigen::ComplexSchur< MatrixType_ >::m_maxIters, min, Eigen::NoConvergence, rot(), Eigen::PlainObjectBase< Derived >::rows(), Eigen::ComplexSchur< MatrixType_ >::subdiagonalEntryIsNeglegible(), and Eigen::Success.
Referenced by Eigen::ComplexSchur< MatrixType_ >::computeFromHessenberg().
setMaxIterations()
template<typename MatrixType_ > ComplexSchur& Eigen::ComplexSchur< MatrixType_ >::setMaxIterations (Index maxIters) inline
Sets the maximum number of iterations allowed.
If not specified by the user, the maximum number of iterations is m_maxIterationsPerRow times the size of the matrix.
{
     m_maxIters = maxIters;
     return *this;
   }
References Eigen::ComplexSchur< MatrixType_ >::m_maxIters.
Referenced by schur(), and Eigen::ComplexEigenSolver< MatrixType_ >::setMaxIterations().
subdiagonalEntryIsNeglegible()
template<typename MatrixType > bool Eigen::ComplexSchur< MatrixType >::subdiagonalEntryIsNeglegible (Index i) inline private
If m_matT(i+1,i) is negligible in floating point arithmetic compared to m_matT(i,i) and m_matT(j,j), then set it to zero and return true, else return false.
{
   RealScalar d = numext::norm1(m_matT.coeff(i, i)) + numext::norm1(m_matT.coeff(i + 1, i + 1));
   RealScalar sd = numext::norm1(m_matT.coeff(i + 1, i));
   if (internal::isMuchSmallerThan(sd, d, NumTraits<RealScalar>::epsilon())) {
     m_matT.coeffRef(i + 1, i) = ComplexScalar(0);
     return true;
   }
   return false;
 }
References Eigen::PlainObjectBase< Derived >::coeff(), Eigen::Matrix< Scalar_, Rows_, Cols_, Options_, MaxRows_, MaxCols_ >::coeffRef(), i, Eigen::internal::isMuchSmallerThan(), and Eigen::ComplexSchur< MatrixType_ >::m_matT.
Referenced by Eigen::ComplexSchur< MatrixType_ >::reduceToTriangularForm().
Friends And Related Function Documentation
internal::complex_schur_reduce_to_hessenberg< MatrixType, NumTraits< Scalar >::IsComplex >
template<typename MatrixType_ > friend struct internal::complex_schur_reduce_to_hessenberg< MatrixType, NumTraits< Scalar >::IsComplex > friend
Member Data Documentation
m_hess
template<typename MatrixType_ > HessenbergDecomposition<MatrixType> Eigen::ComplexSchur< MatrixType_ >::m_hess protected
Referenced by Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, IsComplex >::run(), and Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, false >::run().
m_info
template<typename MatrixType_ > ComputationInfo Eigen::ComplexSchur< MatrixType_ >::m_info protected
Referenced by Eigen::ComplexSchur< MatrixType_ >::compute(), Eigen::ComplexSchur< MatrixType_ >::info(), and Eigen::ComplexSchur< MatrixType_ >::reduceToTriangularForm().
m_isInitialized
template<typename MatrixType_ > bool Eigen::ComplexSchur< MatrixType_ >::m_isInitialized protected
Referenced by Eigen::ComplexSchur< MatrixType_ >::compute(), Eigen::ComplexSchur< MatrixType_ >::info(), Eigen::ComplexSchur< MatrixType_ >::matrixT(), Eigen::ComplexSchur< MatrixType_ >::matrixU(), and Eigen::ComplexSchur< MatrixType_ >::reduceToTriangularForm().
m_matT
template<typename MatrixType_ > ComplexMatrixType Eigen::ComplexSchur< MatrixType_ >::m_matT protected
Referenced by Eigen::ComplexSchur< MatrixType_ >::compute(), Eigen::ComplexSchur< MatrixType_ >::computeFromHessenberg(), Eigen::ComplexSchur< MatrixType_ >::computeShift(), Eigen::ComplexSchur< MatrixType_ >::matrixT(), Eigen::ComplexSchur< MatrixType_ >::reduceToTriangularForm(), Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, IsComplex >::run(), Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, false >::run(), and Eigen::ComplexSchur< MatrixType_ >::subdiagonalEntryIsNeglegible().
m_matU
template<typename MatrixType_ > ComplexMatrixType Eigen::ComplexSchur< MatrixType_ >::m_matU protected
Referenced by Eigen::ComplexSchur< MatrixType_ >::compute(), Eigen::ComplexSchur< MatrixType_ >::computeFromHessenberg(), Eigen::ComplexSchur< MatrixType_ >::matrixU(), Eigen::ComplexSchur< MatrixType_ >::reduceToTriangularForm(), Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, IsComplex >::run(), and Eigen::internal::complex_schur_reduce_to_hessenberg< MatrixType, false >::run().
m_matUisUptodate
template<typename MatrixType_ > bool Eigen::ComplexSchur< MatrixType_ >::m_matUisUptodate protected
Referenced by Eigen::ComplexSchur< MatrixType_ >::compute(), Eigen::ComplexSchur< MatrixType_ >::matrixU(), and Eigen::ComplexSchur< MatrixType_ >::reduceToTriangularForm().
m_maxIterationsPerRow
template<typename MatrixType_ > const int Eigen::ComplexSchur< MatrixType_ >::m_maxIterationsPerRow = 30 static
Maximum number of iterations per row.
If not otherwise specified, the maximum number of iterations is this number times the size of the matrix. It is currently set to 30.
Referenced by Eigen::ComplexSchur< MatrixType_ >::reduceToTriangularForm().
m_maxIters
template<typename MatrixType_ > Index Eigen::ComplexSchur< MatrixType_ >::m_maxIters protected
Referenced by Eigen::ComplexSchur< MatrixType_ >::getMaxIterations(), Eigen::ComplexSchur< MatrixType_ >::reduceToTriangularForm(), and Eigen::ComplexSchur< MatrixType_ >::setMaxIterations().
The documentation for this class was generated from the following file:
ComplexSchur.h