MercuryDPM: Eigen::MapBase< Derived, WriteAccessors > Class Template Reference
Eigen::MapBase< Derived, WriteAccessors > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
Base class for non-const dense Map and Block expression with direct access.
#include <MapBase.h>
Public Types
typedef MapBase< Derived, ReadOnlyAccessors > Base
typedef Base::Scalar Scalar
typedef Base::PacketScalar PacketScalar
typedef Base::StorageIndex StorageIndex
typedef Base::PointerType PointerType
typedef std::conditional_t< internal::is_lvalue< Derived >::value, Scalar, const Scalar > ScalarWithConstIfNotLvalue
Public Types inherited from Eigen::MapBase< Derived, ReadOnlyAccessors >
enum { RowsAtCompileTime = internal::traits<Derived>::RowsAtCompileTime , ColsAtCompileTime = internal::traits<Derived>::ColsAtCompileTime , InnerStrideAtCompileTime = internal::traits<Derived>::InnerStrideAtCompileTime , SizeAtCompileTime = Base::SizeAtCompileTime }
typedef internal::dense_xpr_base< Derived >::type Base
typedef internal::traits< Derived >::StorageKind StorageKind
typedef internal::traits< Derived >::Scalar Scalar
typedef internal::packet_traits< Scalar >::type PacketScalar
typedef NumTraits< Scalar >::Real RealScalar
typedef std::conditional_t< bool(internal::is_lvalue< Derived >::value), Scalar *, const Scalar * > PointerType
typedef Base::CoeffReturnType CoeffReturnType
Public Member Functions
constexpr EIGEN_DEVICE_FUNC const Scalar * data () const
constexpr EIGEN_DEVICE_FUNC ScalarWithConstIfNotLvalue * data ()
EIGEN_DEVICE_FUNC ScalarWithConstIfNotLvalue & coeffRef (Index row, Index col)
EIGEN_DEVICE_FUNC ScalarWithConstIfNotLvalue & coeffRef (Index index)
template<int StoreMode>
void writePacket (Index row, Index col, const PacketScalar &val)
template<int StoreMode>
void writePacket (Index index, const PacketScalar &val)
EIGEN_DEVICE_FUNC MapBase (PointerType dataPtr)
EIGEN_DEVICE_FUNC MapBase (PointerType dataPtr, Index vecSize)
EIGEN_DEVICE_FUNC MapBase (PointerType dataPtr, Index rows, Index cols)
EIGEN_DEVICE_FUNC Derived & operator= (const MapBase &other)
Public Member Functions inherited from Eigen::MapBase< Derived, ReadOnlyAccessors >
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
constexpr EIGEN_DEVICE_FUNC const Scalar * data () const
EIGEN_DEVICE_FUNC const Scalar & coeff (Index rowId, Index colId) const
EIGEN_DEVICE_FUNC const Scalar & coeff (Index index) const
EIGEN_DEVICE_FUNC const Scalar & coeffRef (Index rowId, Index colId) const
EIGEN_DEVICE_FUNC const Scalar & coeffRef (Index index) const
template<int LoadMode>
PacketScalar packet (Index rowId, Index colId) const
template<int LoadMode>
PacketScalar packet (Index index) const
EIGEN_DEVICE_FUNC MapBase (PointerType dataPtr)
EIGEN_DEVICE_FUNC MapBase (PointerType dataPtr, Index vecSize)
EIGEN_DEVICE_FUNC MapBase (PointerType dataPtr, Index rows, Index cols)
Private Types
typedef MapBase< Derived, ReadOnlyAccessors > ReadOnlyMapBase
Additional Inherited Members
Protected Member Functions inherited from Eigen::MapBase< Derived, ReadOnlyAccessors >
template<typename T >
EIGEN_DEVICE_FUNC void checkSanity (std::enable_if_t<(internal::traits< T >::Alignment > 0), void * >=0) const
template<typename T >
EIGEN_DEVICE_FUNC void checkSanity (std::enable_if_t< internal::traits< T >::Alignment==0, void * >=0) const
Protected Attributes inherited from Eigen::MapBase< Derived, ReadOnlyAccessors >
PointerType m_data
const internal::variable_if_dynamic< Index, RowsAtCompileTime > m_rows
const internal::variable_if_dynamic< Index, ColsAtCompileTime > m_cols
Detailed Description
template<typename Derived>
class Eigen::MapBase< Derived, WriteAccessors >
Base class for non-const dense Map and Block expression with direct access.
This base class provides the non-const low-level accessors (e.g. coeff and coeffRef) of dense Map and Block objects with direct access. It inherits MapBase<Derived, ReadOnlyAccessors> which defines the const variant for reading specific entries.
See also
class Map, class Block
Member Typedef Documentation
Base
template<typename Derived > typedef MapBase<Derived, ReadOnlyAccessors> Eigen::MapBase< Derived, WriteAccessors >::Base
PacketScalar
template<typename Derived > typedef Base::PacketScalar Eigen::MapBase< Derived, WriteAccessors >::PacketScalar
PointerType
template<typename Derived > typedef Base::PointerType Eigen::MapBase< Derived, WriteAccessors >::PointerType
ReadOnlyMapBase
template<typename Derived > typedef MapBase<Derived, ReadOnlyAccessors> Eigen::MapBase< Derived, WriteAccessors >::ReadOnlyMapBase private
Scalar
template<typename Derived > typedef Base::Scalar Eigen::MapBase< Derived, WriteAccessors >::Scalar
ScalarWithConstIfNotLvalue
template<typename Derived > typedef std::conditional_t<internal::is_lvalue<Derived>::value, Scalar, const Scalar> Eigen::MapBase< Derived, WriteAccessors >::ScalarWithConstIfNotLvalue
StorageIndex
template<typename Derived > typedef Base::StorageIndex Eigen::MapBase< Derived, WriteAccessors >::StorageIndex
Constructor & Destructor Documentation
MapBase() [1/3]
template<typename Derived > EIGEN_DEVICE_FUNC Eigen::MapBase< Derived, WriteAccessors >::MapBase (PointerType dataPtr) inline explicit
 : Base(dataPtr) {}
MapBase() [2/3]
template<typename Derived > EIGEN_DEVICE_FUNC Eigen::MapBase< Derived, WriteAccessors >::MapBase (PointerType dataPtr, Index vecSize) inline
 : Base(dataPtr, vecSize) {}
MapBase() [3/3]
template<typename Derived > EIGEN_DEVICE_FUNC Eigen::MapBase< Derived, WriteAccessors >::MapBase (PointerType dataPtr, Index rows, Index cols) inline
 : Base(dataPtr, rows, cols) {}
Member Function Documentation
coeffRef() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC ScalarWithConstIfNotLvalue& Eigen::MapBase< Derived, WriteAccessors >::coeffRef (Index index) inline
{
     EIGEN_STATIC_ASSERT_INDEX_BASED_ACCESS(Derived)
     return this->m_data[index * innerStride()];
   }
References EIGEN_STATIC_ASSERT_INDEX_BASED_ACCESS.
coeffRef() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC ScalarWithConstIfNotLvalue& Eigen::MapBase< Derived, WriteAccessors >::coeffRef (Index row, Index col) inline
{
     return this->m_data[col * colStride() + row * rowStride()];
   }
References col(), and row().
data() [1/2]
template<typename Derived > constexpr EIGEN_DEVICE_FUNC ScalarWithConstIfNotLvalue* Eigen::MapBase< Derived, WriteAccessors >::data () inline constexpr
{
     return this->m_data;
   }  // no const-cast here so non-const-correct code will give a compile error
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
data() [2/2]
template<typename Derived > constexpr EIGEN_DEVICE_FUNC const Scalar* Eigen::MapBase< Derived, WriteAccessors >::data () const inline constexpr
 { return this->m_data; }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
operator=()
template<typename Derived > EIGEN_DEVICE_FUNC Derived& Eigen::MapBase< Derived, WriteAccessors >::operator= (const MapBase< Derived, WriteAccessors > & other) inline
{
     ReadOnlyMapBase::Base::operator=(other);
     return derived();
   }
writePacket() [1/2]
template<typename Derived > template<int StoreMode> void Eigen::MapBase< Derived, WriteAccessors >::writePacket (Index index, const PacketScalar & val) inline
{
     EIGEN_STATIC_ASSERT_INDEX_BASED_ACCESS(Derived)
     internal::pstoret<Scalar, PacketScalar, StoreMode>(this->m_data + index * innerStride(), val);
   }
References EIGEN_STATIC_ASSERT_INDEX_BASED_ACCESS, and calibrate::val.
writePacket() [2/2]
template<typename Derived > template<int StoreMode> void Eigen::MapBase< Derived, WriteAccessors >::writePacket (Index row, Index col, const PacketScalar & val) inline
{
     internal::pstoret<Scalar, PacketScalar, StoreMode>(this->m_data + (col * colStride() + row * rowStride()), val);
   }
References col(), row(), and calibrate::val.
The documentation for this class was generated from the following file:
MapBase.h