MercuryDPM: T_protectiveWall.cpp File Reference
T_protectiveWall.cpp File Reference
#include <Mercury3D.h>
#include <Species/LinearViscoelasticSpecies.h>
#include "Walls/InfiniteWall.h"
#include "Walls/IntersectionOfWalls.h"
#include "Boundaries/CubeInsertionBoundary.h"
#include "Boundaries/CubeDeletionBoundary.h"
Classes
class T_protectiveWall
[AT_PW:headers]
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
[AT_PW:setUp]
[AT_PW:setUp]
 {
     std::cout << "Write './T_protectiveWall -Np 100 -r 0.05 -h 0.5 -w 1.0 -l 5.0 -s 20.0 -t 2.0' to run the program" << std::endl;
     int Nump = helpers::readFromCommandLine(argc,argv,"-Np",500); //100 partilces inserted by default
     Mdouble pRadius = helpers::readFromCommandLine(argc,argv,"-r",0.01); //by default is 2.0
     Mdouble height = helpers::readFromCommandLine(argc,argv,"-h",0.1); //by default is 2.0
     Mdouble width = helpers::readFromCommandLine(argc,argv,"-w",0.25);  //by default is 1.0
     Mdouble length = helpers::readFromCommandLine(argc,argv,"-l",1.0); //by default is 4.0
     Mdouble slopeAngle = helpers::readFromCommandLine(argc,argv,"-s",15.0); //by default is 20 degrees
     T_protectiveWall problem(Nump,pRadius,height,width,length,slopeAngle);
     Mdouble simTime = helpers::readFromCommandLine(argc,argv,"-t",20.0); //by default is 5.0
     problem.setTimeMax(simTime);
     problem.removeOldFiles();
     problem.solve();
     return 0;
 }
References Global_Physical_Variables::height(), problem, and helpers::readFromCommandLine().
Referenced by oomph::AddedMainNumberingLookup::main_to_added(), and oomph::AddedMainNumberingLookup::unsafe_main_to_added().