MercuryDPM: oomph::PRefineableQElement< 3, INITIAL_NNODE_1D > Class Template Reference
oomph::PRefineableQElement< 3, INITIAL_NNODE_1D > Class Template Reference
p-refineable version of RefineableQElement<3,INITIAL_NNODE_1D>.
#include <hp_refineable_elements.h>
Public Member Functions
PRefineableQElement ()
Constructor.
virtual ~PRefineableQElement ()
Destructor.
void initial_setup (Tree *const &adopted_father_pt=0, const unsigned &initial_p_order=0)
void pre_build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt)
void p_refine (const int &inc, Mesh *const &mesh_pt, GeneralisedElement *const &clone_pt)
p-refine the element (refine if inc>0, unrefine if inc<0).
void shape (const Vector< double > &s, Shape &psi) const
Overload the shape functions.
void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsi) const
Derivatives of shape functions for PRefineableQElement<DIM>
void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
void further_setup_hanging_nodes ()
unsigned nnode_1d () const
unsigned initial_p_order () const
Get the initial P_order.
Node * get_node_at_local_coordinate (const Vector< double > &s) const
Return the node at the specified local coordinate.
Node * node_created_by_neighbour (const Vector< double > &s_fraction, bool &is_periodic)
Node * node_created_by_son_of_neighbour (const Vector< double > &s_fraction, bool &is_periodic)
void local_coordinate_of_node (const unsigned &n, Vector< double > &s) const
Get local coordinates of node j in the element; vector sets its own size.
void local_fraction_of_node (const unsigned &n, Vector< double > &s_fraction)
Get the local fractino of node j in the element.
double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
The local one-d fraction is the same.
void rebuild_from_sons (Mesh *&mesh_pt)
void check_integrity (double &max_error)
Public Member Functions inherited from oomph::RefineableQElement< 3 >
RefineableQElement ()
Constructor: Pass refinement level (default 0 = root)
RefineableQElement (const RefineableQElement< 3 > &dummy)=delete
Broken copy constructor.
virtual ~RefineableQElement ()
Broken assignment operator.
unsigned required_nsons () const
A refineable brick element has eight sons.
virtual void build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt, bool &was_already_built, std::ofstream &new_nodes_file)
void check_integrity (double &max_error)
void output_corners (std::ostream &outfile, const std::string &colour) const
Print corner nodes, use colour.
OcTree * octree_pt ()
Pointer to octree representation of this element.
OcTree * octree_pt () const
Pointer to octree representation of this element.
void setup_hanging_nodes (Vector< std::ofstream * > &output_stream)
Public Member Functions inherited from oomph::RefineableElement
RefineableElement ()
virtual ~RefineableElement ()
Destructor, delete the allocated storage for the hanging equations.
RefineableElement (const RefineableElement &)=delete
Broken copy constructor.
void operator= (const RefineableElement &)=delete
Broken assignment operator.
Tree * tree_pt ()
Access function: Pointer to quadtree representation of this element.
void set_tree_pt (Tree *my_tree_pt)
Set pointer to quadtree representation of this element.
bool refinement_is_enabled ()
Flag to indicate suppression of any refinement.
void disable_refinement ()
Suppress of any refinement for this element.
void enable_refinement ()
Emnable refinement for this element.
template<class ELEMENT >
void split (Vector< ELEMENT * > &son_pt) const
int local_hang_eqn (Node *const &node_pt, const unsigned &i)
void set_refinement_level (const int &refine_level)
Set the refinement level.
unsigned refinement_level () const
Return the Refinement level.
void select_for_refinement ()
Select the element for refinement.
void deselect_for_refinement ()
Deselect the element for refinement.
void select_sons_for_unrefinement ()
Unrefinement will be performed by merging the four sons of this element.
void deselect_sons_for_unrefinement ()
bool to_be_refined ()
Has the element been selected for refinement?
bool sons_to_be_unrefined ()
Has the element been selected for unrefinement?
virtual void unbuild ()
virtual void deactivate_element ()
long number () const
Element number (for debugging/plotting)
void set_number (const long &mynumber)
Set element number (for debugging/plotting)
virtual unsigned ncont_interpolated_values () const =0
virtual void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
virtual void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)=0
virtual Node * interpolating_node_pt (const unsigned &n, const int &value_id)
virtual double local_one_d_fraction_of_interpolating_node (const unsigned &n1d, const unsigned &i, const int &value_id)
virtual Node * get_interpolating_node_at_local_coordinate (const Vector< double > &s, const int &value_id)
virtual unsigned ninterpolating_node (const int &value_id)
virtual unsigned ninterpolating_node_1d (const int &value_id)
virtual void interpolating_basis (const Vector< double > &s, Shape &psi, const int &value_id) const
void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual RefineableElement * root_element_pt ()
virtual RefineableElement * father_element_pt () const
Return a pointer to the father element.
void get_father_at_refinement_level (unsigned &refinement_level, RefineableElement *&father_at_reflevel_pt)
virtual void further_build ()
Further build: e.g. deal with interpolation of internal values.
void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
unsigned nshape_controlling_nodes ()
std::map< Node *, unsigned > shape_controlling_node_lookup ()
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void disable_ALE ()
virtual void enable_ALE ()
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (std::ostream &outfile)
virtual void output (std::ostream &outfile, const unsigned &n_plot)
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output (FILE *file_pt)
virtual void output (FILE *file_pt, const unsigned &n_plot)
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output an exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output a time-dependent exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::BrickElementBase
BrickElementBase ()
Constructor. Empty.
virtual unsigned nvertex_node () const =0
Number of vertex nodes in the element.
virtual Node * vertex_node_pt (const unsigned &j) const =0
Pointer to the j-th vertex node in the element.
Public Member Functions inherited from oomph::QElementBase
QElementBase ()
Constructor: Initialise pointers to macro element reference coords.
QElementBase (const QElementBase &)=delete
Broken copy constructor.
virtual ~QElementBase ()
Broken assignment operator.
bool local_coord_is_valid (const Vector< double > &s)
Check whether the local coordinate are valid or not.
void move_local_coord_back_into_element (Vector< double > &s) const
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
double & s_macro_ll (const unsigned &i)
double & s_macro_ur (const unsigned &i)
double s_macro_ll (const unsigned &i) const
double s_macro_ur (const unsigned &i) const
void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
unsigned nnode_on_face () const
ElementGeometry::ElementGeometry element_geometry () const
It's a Q element!
Public Member Functions inherited from oomph::QElementGeometricBase
QElementGeometricBase ()
Empty default constructor.
QElementGeometricBase (const QElementGeometricBase &)=delete
Broken copy constructor.
Public Member Functions inherited from oomph::PRefineableElement
PRefineableElement ()
Constructor, calls the RefineableElement constructor.
virtual ~PRefineableElement ()
Destructor, empty.
PRefineableElement (const PRefineableElement &)=delete
Broken copy constructor.
void operator= (const PRefineableElement &)=delete
Broken assignment operator.
bool p_refinement_is_enabled ()
Flag to indicate suppression of any refinement.
void disable_p_refinement ()
Suppress of any refinement for this element.
void enable_p_refinement ()
Emnable refinement for this element.
unsigned & p_order ()
Access function to P_order.
unsigned p_order () const
Access function to P_order (const version)
void select_for_p_refinement ()
Select the element for p-refinement.
void deselect_for_p_refinement ()
Deselect the element for p-refinement.
void select_for_p_unrefinement ()
Select the element for p-unrefinement.
void deselect_for_p_unrefinement ()
Deselect the element for p-unrefinement.
bool to_be_p_refined ()
Has the element been selected for refinement?
bool to_be_p_unrefined ()
Has the element been selected for p-unrefinement?
bool nodes_built ()
Return true if all the nodes have been built, false if not.
Protected Member Functions
void oc_hang_helper (const int &value_id, const int &my_face, std::ofstream &output_hangfile)
Protected Member Functions inherited from oomph::RefineableQElement< 3 >
void setup_father_bounds ()
void get_face_bcs (const int &edge, Vector< int > &bound_cons) const
void get_boundaries (const int &edge, std::set< unsigned > &boundaries) const
void get_bcs (int bound, Vector< int > &bound_cons) const
void interpolated_zeta_on_face (const unsigned &boundary, const int &face, const Vector< double > &s, Vector< double > &zeta)
void setup_hang_for_value (const int &value_id)
Protected Member Functions inherited from oomph::RefineableElement
void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
void assign_hanging_local_eqn_numbers (const bool &store_local_dof_pt)
Assign the local equation numbers for hanging node variables.
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Protected Member Functions inherited from oomph::FiniteElement
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
virtual void fill_in_contribution_to_residuals (Vector< double > &residuals)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Additional Inherited Members
Public Types inherited from oomph::RefineableQElement< 3 >
typedef void(RefineableQElement< 3 >::* VoidMemFctPt) ()
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Static Public Member Functions inherited from oomph::RefineableElement
static double & max_integrity_tolerance ()
Max. allowed discrepancy in element integrity check.
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Static Protected Member Functions inherited from oomph::RefineableElement
static void check_value_id (const int &n_continuously_interpolated_values, const int &value_id)
Protected Attributes inherited from oomph::RefineableElement
Tree * Tree_pt
A pointer to a general tree object.
unsigned Refine_level
Refinement level.
bool To_be_refined
Flag for refinement.
bool Refinement_is_enabled
Flag to indicate suppression of any refinement.
bool Sons_to_be_unrefined
Flag for unrefinement.
long Number
Global element number – for plotting/validation purposes.
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Protected Attributes inherited from oomph::PRefineableElement
unsigned P_order
The polynomial expansion order of the elemental basis functions.
bool To_be_p_refined
Flag for p-refinement.
bool P_refinement_is_enabled
Flag to indicate suppression of any refinement.
bool To_be_p_unrefined
Flag for unrefinement.
Static Protected Attributes inherited from oomph::RefineableQElement< 3 >
static std::map< unsigned, DenseMatrix< int > > Father_bound
Static Protected Attributes inherited from oomph::RefineableElement
static double Max_integrity_tolerance = 1.0e-8
Max. allowed discrepancy in element integrity check.
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
template<unsigned INITIAL_NNODE_1D>
class oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >
p-refineable version of RefineableQElement<3,INITIAL_NNODE_1D>.
Constructor & Destructor Documentation
PRefineableQElement()
template<unsigned INITIAL_NNODE_1D> oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::PRefineableQElement () inline
Constructor.
 : PRefineableElement(), RefineableQElement<3>() {}
~PRefineableQElement()
template<unsigned INITIAL_NNODE_1D> virtual oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::~PRefineableQElement () inline virtual
Destructor.
 {}
Member Function Documentation
check_integrity()
template<unsigned INITIAL_NNODE_1D> void oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::check_integrity (double & max_error) virtual
Check the integrity of interpolated values across element boundaries. Note: with the mortar method, continuity is enforced weakly across non- conforming element boundaries, so it makes no sense to check the continuity of interpolated values across these boundaries.
Check inter-element continuity of
nodal positions
(nodally) interpolated function values Overloaded to not check differences in the value. Mortaring doesn't enforce strong continuity between elements.
Implements oomph::RefineableElement.
   {
     // Not yet implemented -- doing nothing for now.
     // Dummy set max_error to 0
     max_error = 0.0;
     return;
   }
References MeshRefinement::max_error.
d2shape_local()
template<unsigned INITIAL_NNODE_1D> void oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::d2shape_local (const Vector< double > & s, Shape & psi, DShape & dpsids, DShape & d2psids) const virtual
Second derivatives of shape functions for PRefineableQElement<DIM> d2psids(i,0) = \(d^2 \psi_j / d s^2 \)
Reimplemented from oomph::FiniteElement.
   {
     std::ostringstream error_message;
     error_message
       << "\nd2shape_local currently not implemented for this element\n";
     throw OomphLibError(
       error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
   }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
dshape_local()
template<unsigned INITIAL_NNODE_1D> void oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::dshape_local (const Vector< double > & s, Shape & psi, DShape & dpsi) const virtual
Derivatives of shape functions for PRefineableQElement<DIM>
Reimplemented from oomph::FiniteElement.
   {
     switch (P_order)
     {
       case 2:
       {
         // Call the shape functions and derivatives
         OneDimensionalLegendreShape<2>::calculate_nodal_positions();
         OneDimensionalLegendreShape<2> psi1(s[0]), psi2(s[1]), psi3(s[2]);
         OneDimensionalLegendreDShape<2> dpsi1ds(s[0]), dpsi2ds(s[1]),
           dpsi3ds(s[2]);
         // Index for the shape functions
         unsigned index = 0;
         // Loop over shape functions in element
         for (unsigned i = 0; i < P_order; i++)
         {
           for (unsigned j = 0; j < P_order; j++)
           {
             for (unsigned k = 0; k < P_order; k++)
             {
               // Assign the values
               dpsids(index, 0) = psi3[i] * psi2[j] * dpsi1ds[k];
               dpsids(index, 1) = psi3[i] * dpsi2ds[j] * psi1[k];
               dpsids(index, 2) = dpsi3ds[i] * psi2[j] * psi1[k];
               psi[index] = psi3[i] * psi2[j] * psi1[k];
               // Increment the index
               ++index;
             }
           }
         }
         break;
       }
       case 3:
       {
         // Call the shape functions and derivatives
         OneDimensionalLegendreShape<3>::calculate_nodal_positions();
         OneDimensionalLegendreShape<3> psi1(s[0]), psi2(s[1]), psi3(s[2]);
         OneDimensionalLegendreDShape<3> dpsi1ds(s[0]), dpsi2ds(s[1]),
           dpsi3ds(s[2]);
         // Index for the shape functions
         unsigned index = 0;
         // Loop over shape functions in element
         for (unsigned i = 0; i < P_order; i++)
         {
           for (unsigned j = 0; j < P_order; j++)
           {
             for (unsigned k = 0; k < P_order; k++)
             {
               // Assign the values
               dpsids(index, 0) = psi3[i] * psi2[j] * dpsi1ds[k];
               dpsids(index, 1) = psi3[i] * dpsi2ds[j] * psi1[k];
               dpsids(index, 2) = dpsi3ds[i] * psi2[j] * psi1[k];
               psi[index] = psi3[i] * psi2[j] * psi1[k];
               // Increment the index
               ++index;
             }
           }
         }
         break;
       }
       case 4:
       {
         // Call the shape functions and derivatives
         OneDimensionalLegendreShape<4>::calculate_nodal_positions();
         OneDimensionalLegendreShape<4> psi1(s[0]), psi2(s[1]), psi3(s[2]);
         OneDimensionalLegendreDShape<4> dpsi1ds(s[0]), dpsi2ds(s[1]),
           dpsi3ds(s[2]);
         // Index for the shape functions
         unsigned index = 0;
         // Loop over shape functions in element
         for (unsigned i = 0; i < P_order; i++)
         {
           for (unsigned j = 0; j < P_order; j++)
           {
             for (unsigned k = 0; k < P_order; k++)
             {
               // Assign the values
               dpsids(index, 0) = psi3[i] * psi2[j] * dpsi1ds[k];
               dpsids(index, 1) = psi3[i] * dpsi2ds[j] * psi1[k];
               dpsids(index, 2) = dpsi3ds[i] * psi2[j] * psi1[k];
               psi[index] = psi3[i] * psi2[j] * psi1[k];
               // Increment the index
               ++index;
             }
           }
         }
         break;
       }
       case 5:
       {
         // Call the shape functions and derivatives
         OneDimensionalLegendreShape<5>::calculate_nodal_positions();
         OneDimensionalLegendreShape<5> psi1(s[0]), psi2(s[1]), psi3(s[2]);
         OneDimensionalLegendreDShape<5> dpsi1ds(s[0]), dpsi2ds(s[1]),
           dpsi3ds(s[2]);
         // Index for the shape functions
         unsigned index = 0;
         // Loop over shape functions in element
         for (unsigned i = 0; i < P_order; i++)
         {
           for (unsigned j = 0; j < P_order; j++)
           {
             for (unsigned k = 0; k < P_order; k++)
             {
               // Assign the values
               dpsids(index, 0) = psi3[i] * psi2[j] * dpsi1ds[k];
               dpsids(index, 1) = psi3[i] * dpsi2ds[j] * psi1[k];
               dpsids(index, 2) = dpsi3ds[i] * psi2[j] * psi1[k];
               psi[index] = psi3[i] * psi2[j] * psi1[k];
               // Increment the index
               ++index;
             }
           }
         }
         break;
       }
       case 6:
       {
         // Call the shape functions and derivatives
         OneDimensionalLegendreShape<6>::calculate_nodal_positions();
         OneDimensionalLegendreShape<6> psi1(s[0]), psi2(s[1]), psi3(s[2]);
         OneDimensionalLegendreDShape<6> dpsi1ds(s[0]), dpsi2ds(s[1]),
           dpsi3ds(s[2]);
         // Index for the shape functions
         unsigned index = 0;
         // Loop over shape functions in element
         for (unsigned i = 0; i < P_order; i++)
         {
           for (unsigned j = 0; j < P_order; j++)
           {
             for (unsigned k = 0; k < P_order; k++)
             {
               // Assign the values
               dpsids(index, 0) = psi3[i] * psi2[j] * dpsi1ds[k];
               dpsids(index, 1) = psi3[i] * dpsi2ds[j] * psi1[k];
               dpsids(index, 2) = dpsi3ds[i] * psi2[j] * psi1[k];
               psi[index] = psi3[i] * psi2[j] * psi1[k];
               // Increment the index
               ++index;
             }
           }
         }
         break;
       }
       case 7:
       {
         // Call the shape functions and derivatives
         OneDimensionalLegendreShape<7>::calculate_nodal_positions();
         OneDimensionalLegendreShape<7> psi1(s[0]), psi2(s[1]), psi3(s[2]);
         OneDimensionalLegendreDShape<7> dpsi1ds(s[0]), dpsi2ds(s[1]),
           dpsi3ds(s[2]);
         // Index for the shape functions
         unsigned index = 0;
         // Loop over shape functions in element
         for (unsigned i = 0; i < P_order; i++)
         {
           for (unsigned j = 0; j < P_order; j++)
           {
             for (unsigned k = 0; k < P_order; k++)
             {
               // Assign the values
               dpsids(index, 0) = psi3[i] * psi2[j] * dpsi1ds[k];
               dpsids(index, 1) = psi3[i] * dpsi2ds[j] * psi1[k];
               dpsids(index, 2) = dpsi3ds[i] * psi2[j] * psi1[k];
               psi[index] = psi3[i] * psi2[j] * psi1[k];
               // Increment the index
               ++index;
             }
           }
         }
         break;
       }
       default:
         std::ostringstream error_message;
         error_message << "\nERROR: Exceeded maximum polynomial order for";
         error_message << "\n       polynomial order for shape functions.\n";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
     }
   }
References oomph::OneDimensionalLegendreShape< NNODE_1D >::calculate_nodal_positions(), i, j, k, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and s.
further_setup_hanging_nodes()
template<unsigned INITIAL_NNODE_1D> void oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::further_setup_hanging_nodes () inline virtual
Perform additional hanging node procedures for variables that are not interpolated by all nodes (e.g. lower order interpolations for the pressure in Taylor Hood).
Implements oomph::RefineableQElement< 3 >.
 {}
get_node_at_local_coordinate()
template<unsigned INITIAL_NNODE_1D> Node * oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::get_node_at_local_coordinate (const Vector< double > & s) const virtual
Return the node at the specified local coordinate.
Reimplemented from oomph::FiniteElement.
   {
     unsigned Nnode_1d = this->nnode_1d();
     // Load the tolerance into a local variable
     double tol = FiniteElement::Node_location_tolerance;
     // There are two possible indices.
     Vector<int> index(3);
     // Loop over indices
     for (unsigned i = 0; i < 3; i++)
     {
       // Determine the index
       // -------------------
       bool is_found = false;
       // If we are at the lower limit, the index is zero
       if (std::fabs(s[i] + 1.0) < tol)
       {
         index[i] = 0;
         is_found = true;
       }
       // If we are at the upper limit, the index is the number of nodes minus 1
       else if (std::fabs(s[i] - 1.0) < tol)
       {
         index[i] = Nnode_1d - 1;
         is_found = true;
       }
       // Otherwise, we have to calculate the index in general
       else
       {
         // Compute Gauss-Lobatto-Legendre node positions
         Vector<double> z;
         Orthpoly::gll_nodes(Nnode_1d, z);
         // Loop over possible internal nodal positions
         for (unsigned n = 1; n < Nnode_1d - 1; n++)
         {
           if (std::fabs(z[n] - s[i]) < tol)
           {
             index[i] = n;
             is_found = true;
             break;
           }
         }
       }
       if (!is_found)
       {
         // No matching nodes
         return 0;
       }
     }
     // If we've got here we have a node, so let's return a pointer to it
     return this->node_pt(index[0] + Nnode_1d * index[1] +
                          Nnode_1d * Nnode_1d * index[2]);
   }
References boost::multiprecision::fabs(), oomph::Orthpoly::gll_nodes(), i, n, GlobalParameters::Nnode_1d, oomph::FiniteElement::Node_location_tolerance, and s.
Referenced by p_refine().
initial_p_order()
template<unsigned INITIAL_NNODE_1D> unsigned oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::initial_p_order () const inline virtual
Get the initial P_order.
Implements oomph::PRefineableElement.
     {
       return INITIAL_NNODE_1D;
     }
initial_setup()
template<unsigned INITIAL_NNODE_1D> void oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::initial_setup (Tree *const & adopted_father_pt = 0, const unsigned & initial_p_order = 0) virtual
Initial setup of element (set the correct p-order and integration scheme) If an adopted father is specified, information from this is used instead of using the father found from the tree.
Set the correct p-order of the element based on that of its father. Then construct an integration scheme of the correct order. If an adopted father is specified, information from this is used instead of using the father found from the tree.
Reimplemented from oomph::RefineableElement.
   {
     // Storage for pointer to my father (in octree impersonation)
     OcTree* father_pt = 0;
     // Check if an adopted father has been specified
     if (adopted_father_pt != 0)
     {
       // Get pointer to my father (in octree impersonation)
       father_pt = dynamic_cast<OcTree*>(adopted_father_pt);
     }
     // Check if element is in a tree
     else if (Tree_pt != 0)
     {
       // Get pointer to my father (in octree impersonation)
       father_pt = dynamic_cast<OcTree*>(octree_pt()->father_pt());
     }
     else
     {
       // throw OomphLibError(
       //       "Element not in a tree, and no adopted father has been
       //       specified!",
       //       "PRefineableQElement<2,INITIAL_NNODE_1D>::initial_setup()",
       //       OOMPH_EXCEPTION_LOCATION);
     }
     // Check if element has father
     if (father_pt != 0 || initial_p_order != 0)
     {
       if (father_pt != 0)
       {
         PRefineableQElement<3, INITIAL_NNODE_1D>* father_el_pt =
           dynamic_cast<PRefineableQElement<3, INITIAL_NNODE_1D>*>(
             father_pt->object_pt());
         if (father_el_pt != 0)
         {
           unsigned father_p_order = father_el_pt->p_order();
           // Set p-order to that of father
           P_order = father_p_order;
         }
       }
       else
       {
         P_order = initial_p_order;
       }
       // Now sort out the element...
       // (has p^3 nodes)
       unsigned new_n_node = P_order * P_order * P_order;
       // Allocate new space for Nodes (at the element level)
       this->set_n_node(new_n_node);
       // Set integration scheme
       delete this->integral_pt();
       switch (P_order)
       {
         case 2:
           this->set_integration_scheme(new GaussLobattoLegendre<3, 2>);
           break;
         case 3:
           this->set_integration_scheme(new GaussLobattoLegendre<3, 3>);
           break;
         case 4:
           this->set_integration_scheme(new GaussLobattoLegendre<3, 4>);
           break;
         case 5:
           this->set_integration_scheme(new GaussLobattoLegendre<3, 5>);
           break;
         case 6:
           this->set_integration_scheme(new GaussLobattoLegendre<3, 6>);
           break;
         case 7:
           this->set_integration_scheme(new GaussLobattoLegendre<3, 7>);
           break;
         default:
           std::ostringstream error_message;
           error_message << "\nERROR: Exceeded maximum polynomial order for";
           error_message << "\n       integration scheme.\n";
           throw OomphLibError(error_message.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
       }
     }
   }
References oomph::Tree::object_pt(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::PRefineableElement::p_order().
local_coordinate_of_node()
template<unsigned INITIAL_NNODE_1D> void oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::local_coordinate_of_node (const unsigned & n, Vector< double > & s) const virtual
Get local coordinates of node j in the element; vector sets its own size.
Reimplemented from oomph::FiniteElement.
   {
     s.resize(3);
     unsigned Nnode_1d = this->nnode_1d();
     unsigned n0 = n % Nnode_1d;
     unsigned n1 = unsigned(double(n) / double(Nnode_1d)) % Nnode_1d;
     unsigned n2 = unsigned(double(n) / double(Nnode_1d * Nnode_1d));
     switch (Nnode_1d)
     {
       case 2:
         OneDimensionalLegendreShape<2>::calculate_nodal_positions();
         s[0] = OneDimensionalLegendreShape<2>::nodal_position(n0);
         s[1] = OneDimensionalLegendreShape<2>::nodal_position(n1);
         s[2] = OneDimensionalLegendreShape<2>::nodal_position(n2);
         break;
       case 3:
         OneDimensionalLegendreShape<3>::calculate_nodal_positions();
         s[0] = OneDimensionalLegendreShape<3>::nodal_position(n0);
         s[1] = OneDimensionalLegendreShape<3>::nodal_position(n1);
         s[2] = OneDimensionalLegendreShape<3>::nodal_position(n2);
         break;
       case 4:
         OneDimensionalLegendreShape<4>::calculate_nodal_positions();
         s[0] = OneDimensionalLegendreShape<4>::nodal_position(n0);
         s[1] = OneDimensionalLegendreShape<4>::nodal_position(n1);
         s[2] = OneDimensionalLegendreShape<4>::nodal_position(n2);
         break;
       case 5:
         OneDimensionalLegendreShape<5>::calculate_nodal_positions();
         s[0] = OneDimensionalLegendreShape<5>::nodal_position(n0);
         s[1] = OneDimensionalLegendreShape<5>::nodal_position(n1);
         s[2] = OneDimensionalLegendreShape<5>::nodal_position(n2);
         break;
       case 6:
         OneDimensionalLegendreShape<6>::calculate_nodal_positions();
         s[0] = OneDimensionalLegendreShape<6>::nodal_position(n0);
         s[1] = OneDimensionalLegendreShape<6>::nodal_position(n1);
         s[2] = OneDimensionalLegendreShape<6>::nodal_position(n2);
         break;
       case 7:
         OneDimensionalLegendreShape<7>::calculate_nodal_positions();
         s[0] = OneDimensionalLegendreShape<7>::nodal_position(n0);
         s[1] = OneDimensionalLegendreShape<7>::nodal_position(n1);
         s[2] = OneDimensionalLegendreShape<7>::nodal_position(n2);
         break;
       default:
         std::ostringstream error_message;
         error_message << "\nERROR: Exceeded maximum polynomial order for";
         error_message << "\n       shape functions.\n";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
         break;
     }
   }
References oomph::OneDimensionalLegendreShape< NNODE_1D >::calculate_nodal_positions(), n, GlobalParameters::Nnode_1d, oomph::OneDimensionalLegendreShape< NNODE_1D >::nodal_position(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and s.
local_fraction_of_node()
template<unsigned INITIAL_NNODE_1D> void oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::local_fraction_of_node (const unsigned & n, Vector< double > & s_fraction) virtual
Get the local fractino of node j in the element.
Reimplemented from oomph::FiniteElement.
   {
     this->local_coordinate_of_node(n, s_fraction);
     s_fraction[0] = 0.5 * (s_fraction[0] + 1.0);
     s_fraction[1] = 0.5 * (s_fraction[1] + 1.0);
     s_fraction[2] = 0.5 * (s_fraction[2] + 1.0);
   }
References n.
local_one_d_fraction_of_node()
template<unsigned INITIAL_NNODE_1D> double oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::local_one_d_fraction_of_node (const unsigned & n1d, const unsigned & i) virtual
The local one-d fraction is the same.
Reimplemented from oomph::FiniteElement.
   {
     switch (this->nnode_1d())
     {
       case 2:
         OneDimensionalLegendreShape<2>::calculate_nodal_positions();
         return 0.5 *
                (OneDimensionalLegendreShape<2>::nodal_position(n1d) + 1.0);
       case 3:
         OneDimensionalLegendreShape<3>::calculate_nodal_positions();
         return 0.5 *
                (OneDimensionalLegendreShape<3>::nodal_position(n1d) + 1.0);
       case 4:
         OneDimensionalLegendreShape<4>::calculate_nodal_positions();
         return 0.5 *
                (OneDimensionalLegendreShape<4>::nodal_position(n1d) + 1.0);
       case 5:
         OneDimensionalLegendreShape<5>::calculate_nodal_positions();
         return 0.5 *
                (OneDimensionalLegendreShape<5>::nodal_position(n1d) + 1.0);
       case 6:
         OneDimensionalLegendreShape<6>::calculate_nodal_positions();
         return 0.5 *
                (OneDimensionalLegendreShape<6>::nodal_position(n1d) + 1.0);
       case 7:
         OneDimensionalLegendreShape<7>::calculate_nodal_positions();
         return 0.5 *
                (OneDimensionalLegendreShape<7>::nodal_position(n1d) + 1.0);
       default:
         std::ostringstream error_message;
         error_message << "\nERROR: Exceeded maximum polynomial order for";
         error_message << "\n       shape functions.\n";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
         return 0.0;
     }
   }
References oomph::OneDimensionalLegendreShape< NNODE_1D >::calculate_nodal_positions(), oomph::OneDimensionalLegendreShape< NNODE_1D >::nodal_position(), OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
nnode_1d()
template<unsigned INITIAL_NNODE_1D> unsigned oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::nnode_1d () const inline virtual
Returns the number of nodes along each edge of the element. Overloaded to return the (variable) p-order rather than the template argument.
Reimplemented from oomph::FiniteElement.
     {
       return this->p_order();
     }
node_created_by_neighbour()
template<unsigned INITIAL_NNODE_1D> Node * oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::node_created_by_neighbour (const Vector< double > & s_fraction, bool & is_periodic) virtual
If a neighbouring element has already created a node at a position corresponding to the local fractional position within the present element, s_fraction, return a pointer to that node. If not, return NULL (0).
Reimplemented from oomph::RefineableQElement< 3 >.
   {
     using namespace OcTreeNames;
     // Calculate the faces/edges on which the node lies
     Vector<int> faces;
     Vector<int> edges;
     if (s_fraction[0] == 0.0)
     {
       faces.push_back(L);
       if (s_fraction[1] == 0.0)
       {
         edges.push_back(LD);
       }
       if (s_fraction[2] == 0.0)
       {
         edges.push_back(LB);
       }
       if (s_fraction[1] == 1.0)
       {
         edges.push_back(LU);
       }
       if (s_fraction[2] == 1.0)
       {
         edges.push_back(LF);
       }
     }
     if (s_fraction[0] == 1.0)
     {
       faces.push_back(R);
       if (s_fraction[1] == 0.0)
       {
         edges.push_back(RD);
       }
       if (s_fraction[2] == 0.0)
       {
         edges.push_back(RB);
       }
       if (s_fraction[1] == 1.0)
       {
         edges.push_back(RU);
       }
       if (s_fraction[2] == 1.0)
       {
         edges.push_back(RF);
       }
     }
     if (s_fraction[1] == 0.0)
     {
       faces.push_back(D);
       if (s_fraction[2] == 0.0)
       {
         edges.push_back(DB);
       }
       if (s_fraction[2] == 1.0)
       {
         edges.push_back(DF);
       }
     }
     if (s_fraction[1] == 1.0)
     {
       faces.push_back(U);
       if (s_fraction[2] == 0.0)
       {
         edges.push_back(UB);
       }
       if (s_fraction[2] == 1.0)
       {
         edges.push_back(UF);
       }
     }
     if (s_fraction[2] == 0.0)
     {
       faces.push_back(B);
     }
     if (s_fraction[2] == 1.0)
     {
       faces.push_back(F);
     }
     // Find the number of faces
     unsigned n_face = faces.size();
     // Find the number of edges
     unsigned n_edge = edges.size();
     Vector<unsigned> translate_s(3);
     Vector<double> s_lo_neigh(3);
     Vector<double> s_hi_neigh(3);
     Vector<double> s(3);
     int neigh_face, diff_level;
     bool in_neighbouring_tree;
     // Loop over the faces on which the node lies
     //------------------------------------------
     for (unsigned j = 0; j < n_face; j++)
     {
       // Find pointer to neighbouring element along face
       OcTree* neigh_pt;
       neigh_pt = octree_pt()->gteq_face_neighbour(faces[j],
                                                   translate_s,
                                                   s_lo_neigh,
                                                   s_hi_neigh,
                                                   neigh_face,
                                                   diff_level,
                                                   in_neighbouring_tree);
       // Neighbour exists
       if (neigh_pt != 0)
       {
         // Have any of its vertex nodes been created yet?
         // (Must look in incomplete neighbours because after the
         // pre-build they may contain pointers to the required nodes. e.g.
         // h-refinement of neighbouring linear and quadratic elements)
         bool a_vertex_node_is_built = false;
         QElement<3, INITIAL_NNODE_1D>* neigh_obj_pt =
           dynamic_cast<QElement<3, INITIAL_NNODE_1D>*>(neigh_pt->object_pt());
         if (neigh_obj_pt == 0)
         {
           throw OomphLibError("Not a quad element!",
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
         for (unsigned vnode = 0; vnode < neigh_obj_pt->nvertex_node(); vnode++)
         {
           if (neigh_obj_pt->vertex_node_pt(vnode) != 0)
             a_vertex_node_is_built = true;
           break;
         }
         if (a_vertex_node_is_built)
         {
           // We now need to translate the nodal location, defined in terms
           // of the fractional coordinates of the present element into
           // those of its neighbour. For this we use the information returned
           // to use from the octree function.
           // Calculate the local coordinate in the neighbour
           // Note that we need to use the translation scheme in case
           // the local coordinates are swapped in the neighbour.
           for (unsigned i = 0; i < 3; i++)
           {
             s[i] = s_lo_neigh[i] +
                    s_fraction[translate_s[i]] * (s_hi_neigh[i] - s_lo_neigh[i]);
           }
           // Find the node in the neighbour
           Node* neighbour_node_pt =
             neigh_pt->object_pt()->get_node_at_local_coordinate(s);
           // If there is a node, return it
           if (neighbour_node_pt != 0)
           {
             // Now work out whether it's a periodic boundary
             // only possible if we have moved into a neighbouring tree
             if (in_neighbouring_tree)
             {
               // Return whether the neighbour is periodic
               is_periodic =
                 octree_pt()->root_pt()->is_neighbour_periodic(faces[j]);
             }
             return neighbour_node_pt;
           }
         }
       }
     } // End of loop over faces
     // Loop over the edges on which the node lies
     //------------------------------------------
     for (unsigned j = 0; j < n_edge; j++)
     {
       // Even if we restrict ourselves to true edge neighbours (i.e.
       // elements that are not also face neighbours) there may be multiple
       // edge neighbours across the edges between multiple root octrees.
       // When making the first call to OcTree::gteq_true_edge_neighbour(...)
       // we simply return the first one of these multiple edge neighbours
       // (if there are any at all, of course) and also return the total number
       // of true edge neighbours. If the node in question already exists
       // on the first edge neighbour we're done. If it doesn't it may exist
       // on other edge neighbours so we repeat the process over all
       // other edge neighbours (bailing out if a node is found, of course).
       // Initially return the zero-th true edge neighbour
       unsigned i_root_edge_neighbour = 0;
       // Initialise the total number of true edge neighbours
       unsigned nroot_edge_neighbour = 0;
       // Keep searching until we've found the node or until we've checked
       // all available edge neighbours
       bool keep_searching = true;
       while (keep_searching)
       {
         // Find pointer to neighbouring element along edge
         OcTree* neigh_pt;
         neigh_pt = octree_pt()->gteq_true_edge_neighbour(edges[j],
                                                          i_root_edge_neighbour,
                                                          nroot_edge_neighbour,
                                                          translate_s,
                                                          s_lo_neigh,
                                                          s_hi_neigh,
                                                          neigh_face,
                                                          diff_level);
         // Neighbour exists
         if (neigh_pt != 0)
         {
           // Have any of its vertex nodes been created yet?
           // (Must look in incomplete neighbours because after the
           // pre-build they may contain pointers to the required nodes. e.g.
           // h-refinement of neighbouring linear and quadratic elements)
           bool a_vertex_node_is_built = false;
           QElement<3, INITIAL_NNODE_1D>* neigh_obj_pt =
             dynamic_cast<QElement<3, INITIAL_NNODE_1D>*>(neigh_pt->object_pt());
           if (neigh_obj_pt == 0)
           {
             throw OomphLibError("Not a quad element!",
                                 OOMPH_CURRENT_FUNCTION,
                                 OOMPH_EXCEPTION_LOCATION);
           }
           for (unsigned vnode = 0; vnode < neigh_obj_pt->nvertex_node();
                vnode++)
           {
             if (neigh_obj_pt->vertex_node_pt(vnode) != 0)
               a_vertex_node_is_built = true;
             break;
           }
           if (a_vertex_node_is_built)
           {
             // We now need to translate the nodal location, defined in terms
             // of the fractional coordinates of the present element into
             // those of its neighbour. For this we use the information returned
             // to use from the octree function.
             // Calculate the local coordinate in the neighbour
             // Note that we need to use the translation scheme in case
             // the local coordinates are swapped in the neighbour.
             for (unsigned i = 0; i < 3; i++)
             {
               s[i] = s_lo_neigh[i] + s_fraction[translate_s[i]] *
                                        (s_hi_neigh[i] - s_lo_neigh[i]);
             }
             // Find the node in the neighbour
             Node* neighbour_node_pt =
               neigh_pt->object_pt()->get_node_at_local_coordinate(s);
             // If there is a node, return it
             if (neighbour_node_pt != 0)
             {
               // Get the faces on which the edge lies
               Vector<int> faces_attached_to_edge =
                 OcTree::faces_of_common_edge(edges[j]);
               // Get the number of entries in the vector
               unsigned n_faces_attached_to_edge = faces_attached_to_edge.size();
               // Loop over the faces
               for (unsigned i_face = 0; i_face < n_faces_attached_to_edge;
                    i_face++)
               {
                 // Is the node periodic in the face direction?
                 is_periodic = octree_pt()->root_pt()->is_neighbour_periodic(
                   faces_attached_to_edge[i_face]);
                 // Check if the edge is periodic in the i_face-th face direction
                 if (is_periodic)
                 {
                   // We're done!
                   break;
                 }
               } // for (unsigned
                 // i_face=0;i_face<n_faces_attached_to_edge;i_face++)
               return neighbour_node_pt;
             }
           }
         }
         // Keep searching, but only if there are further edge neighbours
         // Try next root edge neighbour
         i_root_edge_neighbour++;
         // Have we exhausted the search
         if (i_root_edge_neighbour >= nroot_edge_neighbour)
         {
           keep_searching = false;
         }
       } // End of while keep searching over all true edge neighbours
     } // End of loop over edges
     // Node not found, return null
     return 0;
   }
References D, oomph::OcTreeNames::DB, oomph::OcTreeNames::DF, oomph::OcTreeNames::F, oomph::OcTree::faces_of_common_edge(), oomph::FiniteElement::get_node_at_local_coordinate(), oomph::OcTree::gteq_face_neighbour(), oomph::OcTree::gteq_true_edge_neighbour(), i, j, L, oomph::OcTreeNames::LB, oomph::OcTreeNames::LD, oomph::OcTreeNames::LF, oomph::OcTreeNames::LU, oomph::Tree::object_pt(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, R, oomph::OcTreeNames::RB, oomph::OcTreeNames::RD, oomph::OcTreeNames::RF, oomph::OcTreeNames::RU, s, RachelsAdvectionDiffusion::U, oomph::OcTreeNames::UB, and oomph::OcTreeNames::UF.
node_created_by_son_of_neighbour()
template<unsigned INITIAL_NNODE_1D> Node * oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::node_created_by_son_of_neighbour (const Vector< double > & s_fraction, bool & is_periodic) virtual
If a neighbouring element's son has already created a node at a position corresponding to the local fractional position within the present element, s_fraction, return a pointer to that node. If not, return NULL (0). If the node is periodic the flag is_periodic will be true
Reimplemented from oomph::RefineableQElement< 3 >.
   {
     using namespace OcTreeNames;
     // Calculate the faces/edges on which the node lies
     Vector<int> faces;
     Vector<int> edges;
     if (s_fraction[0] == 0.0)
     {
       faces.push_back(L);
       if (s_fraction[1] == 0.0)
       {
         edges.push_back(LD);
       }
       if (s_fraction[2] == 0.0)
       {
         edges.push_back(LB);
       }
       if (s_fraction[1] == 1.0)
       {
         edges.push_back(LU);
       }
       if (s_fraction[2] == 1.0)
       {
         edges.push_back(LF);
       }
     }
     if (s_fraction[0] == 1.0)
     {
       faces.push_back(R);
       if (s_fraction[1] == 0.0)
       {
         edges.push_back(RD);
       }
       if (s_fraction[2] == 0.0)
       {
         edges.push_back(RB);
       }
       if (s_fraction[1] == 1.0)
       {
         edges.push_back(RU);
       }
       if (s_fraction[2] == 1.0)
       {
         edges.push_back(RF);
       }
     }
     if (s_fraction[1] == 0.0)
     {
       faces.push_back(D);
       if (s_fraction[2] == 0.0)
       {
         edges.push_back(DB);
       }
       if (s_fraction[2] == 1.0)
       {
         edges.push_back(DF);
       }
     }
     if (s_fraction[1] == 1.0)
     {
       faces.push_back(U);
       if (s_fraction[2] == 0.0)
       {
         edges.push_back(UB);
       }
       if (s_fraction[2] == 1.0)
       {
         edges.push_back(UF);
       }
     }
     if (s_fraction[2] == 0.0)
     {
       faces.push_back(B);
     }
     if (s_fraction[2] == 1.0)
     {
       faces.push_back(F);
     }
     // Find the number of faces
     unsigned n_face = faces.size();
     // Find the number of edges
     unsigned n_edge = edges.size();
     Vector<unsigned> translate_s(3);
     Vector<double> s_lo_neigh(3);
     Vector<double> s_hi_neigh(3);
     Vector<double> s(3);
     int neigh_face, diff_level;
     bool in_neighbouring_tree;
     // Loop over the faces on which the node lies
     //------------------------------------------
     for (unsigned j = 0; j < n_face; j++)
     {
       // Find pointer to neighbouring element along face
       OcTree* neigh_pt;
       neigh_pt = octree_pt()->gteq_face_neighbour(faces[j],
                                                   translate_s,
                                                   s_lo_neigh,
                                                   s_hi_neigh,
                                                   neigh_face,
                                                   diff_level,
                                                   in_neighbouring_tree);
       // Neighbour exists
       if (neigh_pt != 0)
       {
         // Have its nodes been created yet?
         // (Must look in sons of unfinished neighbours too!!!)
         if (true)
         {
           // We now need to translate the nodal location, defined in terms
           // of the fractional coordinates of the present element into
           // those of its neighbour. For this we use the information returned
           // to use from the octree function.
           // Calculate the local coordinate in the neighbour
           // Note that we need to use the translation scheme in case
           // the local coordinates are swapped in the neighbour.
           for (unsigned i = 0; i < 3; i++)
           {
             s[i] = s_lo_neigh[i] +
                    s_fraction[translate_s[i]] * (s_hi_neigh[i] - s_lo_neigh[i]);
           }
           // Check if the element has sons
           if (neigh_pt->nsons() != 0)
           {
             // First, find the son element in which the node should live
             // Find coordinates in the sons
             Vector<double> s_in_son(3);
             int son = -10;
             // On the left
             if (s[0] < 0.0)
             {
               // On the bottom
               if (s[1] < 0.0)
               {
                 // On the back
                 if (s[2] < 0.0)
                 {
                   // It's the LDB son
                   son = OcTreeNames::LDB;
                   s_in_son[0] = 1.0 + 2.0 * s[0];
                   s_in_son[1] = 1.0 + 2.0 * s[1];
                   s_in_son[2] = 1.0 + 2.0 * s[2];
                 }
                 // On the front
                 else
                 {
                   // It's the LDF son
                   son = OcTreeNames::LDF;
                   s_in_son[0] = 1.0 + 2.0 * s[0];
                   s_in_son[1] = 1.0 + 2.0 * s[1];
                   s_in_son[2] = -1.0 + 2.0 * s[2];
                 }
               }
               // On the top
               else
               {
                 // On the back
                 if (s[2] < 0.0)
                 {
                   // It's the LUB son
                   son = OcTreeNames::LUB;
                   s_in_son[0] = 1.0 + 2.0 * s[0];
                   s_in_son[1] = -1.0 + 2.0 * s[1];
                   s_in_son[2] = 1.0 + 2.0 * s[2];
                 }
                 // On the front
                 else
                 {
                   // It's the LUF son
                   son = OcTreeNames::LUF;
                   s_in_son[0] = 1.0 + 2.0 * s[0];
                   s_in_son[1] = -1.0 + 2.0 * s[1];
                   s_in_son[2] = -1.0 + 2.0 * s[2];
                 }
               }
             }
             // On the right
             else
             {
               // On the bottom
               if (s[1] < 0.0)
               {
                 // On the back
                 if (s[2] < 0.0)
                 {
                   // It's the RDB son
                   son = OcTreeNames::RDB;
                   s_in_son[0] = -1.0 + 2.0 * s[0];
                   s_in_son[1] = 1.0 + 2.0 * s[1];
                   s_in_son[2] = 1.0 + 2.0 * s[2];
                 }
                 // On the front
                 else
                 {
                   // It's the RDF son
                   son = OcTreeNames::RDF;
                   s_in_son[0] = -1.0 + 2.0 * s[0];
                   s_in_son[1] = 1.0 + 2.0 * s[1];
                   s_in_son[2] = -1.0 + 2.0 * s[2];
                 }
               }
               // On the top
               else
               {
                 // On the back
                 if (s[2] < 0.0)
                 {
                   // It's the RUB son
                   son = OcTreeNames::RUB;
                   s_in_son[0] = -1.0 + 2.0 * s[0];
                   s_in_son[1] = -1.0 + 2.0 * s[1];
                   s_in_son[2] = 1.0 + 2.0 * s[2];
                 }
                 // On the front
                 else
                 {
                   // It's the RUF son
                   son = OcTreeNames::RUF;
                   s_in_son[0] = -1.0 + 2.0 * s[0];
                   s_in_son[1] = -1.0 + 2.0 * s[1];
                   s_in_son[2] = -1.0 + 2.0 * s[2];
                 }
               }
             }
             // Find the node in the neighbour's son
             Node* neighbour_son_node_pt =
               neigh_pt->son_pt(son)->object_pt()->get_node_at_local_coordinate(
                 s_in_son);
             // If there is a node, return it
             if (neighbour_son_node_pt != 0)
             {
               // Now work out whether it's a periodic boundary
               // only possible if we have moved into a neighbouring tree
               if (in_neighbouring_tree)
               {
                 // Return whether the neighbour is periodic
                 is_periodic =
                   octree_pt()->root_pt()->is_neighbour_periodic(faces[j]);
               }
               // Return the pointer to the neighbouring node
               return neighbour_son_node_pt;
             }
           }
         }
       }
     } // End of loop over faces
     // Loop over the edges on which the node lies
     //------------------------------------------
     for (unsigned j = 0; j < n_edge; j++)
     {
       // Even if we restrict ourselves to true edge neighbours (i.e.
       // elements that are not also face neighbours) there may be multiple
       // edge neighbours across the edges between multiple root octrees.
       // When making the first call to OcTree::gteq_true_edge_neighbour(...)
       // we simply return the first one of these multiple edge neighbours
       // (if there are any at all, of course) and also return the total number
       // of true edge neighbours. If the node in question already exists
       // on the first edge neighbour we're done. If it doesn't it may exist
       // on other edge neighbours so we repeat the process over all
       // other edge neighbours (bailing out if a node is found, of course).
       // Initially return the zero-th true edge neighbour
       unsigned i_root_edge_neighbour = 0;
       // Initialise the total number of true edge neighbours
       unsigned nroot_edge_neighbour = 0;
       // Keep searching until we've found the node or until we've checked
       // all available edge neighbours
       bool keep_searching = true;
       while (keep_searching)
       {
         // Find pointer to neighbouring element along edge
         OcTree* neigh_pt;
         neigh_pt = octree_pt()->gteq_true_edge_neighbour(edges[j],
                                                          i_root_edge_neighbour,
                                                          nroot_edge_neighbour,
                                                          translate_s,
                                                          s_lo_neigh,
                                                          s_hi_neigh,
                                                          neigh_face,
                                                          diff_level);
         // Neighbour exists
         if (neigh_pt != 0)
         {
           // Have its nodes been created yet?
           // (Must look in sons of unfinished neighbours too!!!)
           if (true)
           {
             // We now need to translate the nodal location, defined in terms
             // of the fractional coordinates of the present element into
             // those of its neighbour. For this we use the information returned
             // to use from the octree function.
             // Calculate the local coordinate in the neighbour
             // Note that we need to use the translation scheme in case
             // the local coordinates are swapped in the neighbour.
             for (unsigned i = 0; i < 3; i++)
             {
               s[i] = s_lo_neigh[i] + s_fraction[translate_s[i]] *
                                        (s_hi_neigh[i] - s_lo_neigh[i]);
             }
             // Check if the element has sons
             if (neigh_pt->nsons() != 0)
             {
               // First, find the son element in which the node should live
               // Find coordinates in the sons
               Vector<double> s_in_son(3);
               int son = -10;
               // On the left
               if (s[0] < 0.0)
               {
                 // On the bottom
                 if (s[1] < 0.0)
                 {
                   // On the back
                   if (s[2] < 0.0)
                   {
                     // It's the LDB son
                     son = OcTreeNames::LDB;
                     s_in_son[0] = 1.0 + 2.0 * s[0];
                     s_in_son[1] = 1.0 + 2.0 * s[1];
                     s_in_son[2] = 1.0 + 2.0 * s[2];
                   }
                   // On the front
                   else
                   {
                     // It's the LDF son
                     son = OcTreeNames::LDF;
                     s_in_son[0] = 1.0 + 2.0 * s[0];
                     s_in_son[1] = 1.0 + 2.0 * s[1];
                     s_in_son[2] = -1.0 + 2.0 * s[2];
                   }
                 }
                 // On the top
                 else
                 {
                   // On the back
                   if (s[2] < 0.0)
                   {
                     // It's the LUB son
                     son = OcTreeNames::LUB;
                     s_in_son[0] = 1.0 + 2.0 * s[0];
                     s_in_son[1] = -1.0 + 2.0 * s[1];
                     s_in_son[2] = 1.0 + 2.0 * s[2];
                   }
                   // On the front
                   else
                   {
                     // It's the LUF son
                     son = OcTreeNames::LUF;
                     s_in_son[0] = 1.0 + 2.0 * s[0];
                     s_in_son[1] = -1.0 + 2.0 * s[1];
                     s_in_son[2] = -1.0 + 2.0 * s[2];
                   }
                 }
               }
               // On the right
               else
               {
                 // On the bottom
                 if (s[1] < 0.0)
                 {
                   // On the back
                   if (s[2] < 0.0)
                   {
                     // It's the RDB son
                     son = OcTreeNames::RDB;
                     s_in_son[0] = -1.0 + 2.0 * s[0];
                     s_in_son[1] = 1.0 + 2.0 * s[1];
                     s_in_son[2] = 1.0 + 2.0 * s[2];
                   }
                   // On the front
                   else
                   {
                     // It's the RDF son
                     son = OcTreeNames::RDF;
                     s_in_son[0] = -1.0 + 2.0 * s[0];
                     s_in_son[1] = 1.0 + 2.0 * s[1];
                     s_in_son[2] = -1.0 + 2.0 * s[2];
                   }
                 }
                 // On the top
                 else
                 {
                   // On the back
                   if (s[2] < 0.0)
                   {
                     // It's the RUB son
                     son = OcTreeNames::RUB;
                     s_in_son[0] = -1.0 + 2.0 * s[0];
                     s_in_son[1] = -1.0 + 2.0 * s[1];
                     s_in_son[2] = 1.0 + 2.0 * s[2];
                   }
                   // On the front
                   else
                   {
                     // It's the RUF son
                     son = OcTreeNames::RUF;
                     s_in_son[0] = -1.0 + 2.0 * s[0];
                     s_in_son[1] = -1.0 + 2.0 * s[1];
                     s_in_son[2] = -1.0 + 2.0 * s[2];
                   }
                 }
               }
               // Find the node in the neighbour's son
               Node* neighbour_son_node_pt =
                 neigh_pt->son_pt(son)
                   ->object_pt()
                   ->get_node_at_local_coordinate(s_in_son);
               // If there is a node, return it
               if (neighbour_son_node_pt != 0)
               {
                 // Get the faces on which the edge lies
                 Vector<int> faces_attached_to_edge =
                   OcTree::faces_of_common_edge(edges[j]);
                 // Get the number of entries in the vector
                 unsigned n_faces_attached_to_edge =
                   faces_attached_to_edge.size();
                 // Loop over the faces
                 for (unsigned i_face = 0; i_face < n_faces_attached_to_edge;
                      i_face++)
                 {
                   // Is the node periodic in the face direction?
                   is_periodic = octree_pt()->root_pt()->is_neighbour_periodic(
                     faces_attached_to_edge[i_face]);
                   // Check if the edge is periodic in the i_face-th face
                   // direction
                   if (is_periodic)
                   {
                     // We're done!
                     break;
                   }
                 } // for (unsigned
                   // i_face=0;i_face<n_faces_attached_to_edge;i_face++)
                 // Return the pointer to the neighbouring node
                 return neighbour_son_node_pt;
               }
             }
           }
         }
         // Keep searching, but only if there are further edge neighbours
         // Try next root edge neighbour
         i_root_edge_neighbour++;
         // Have we exhausted the search
         if (i_root_edge_neighbour >= nroot_edge_neighbour)
         {
           keep_searching = false;
         }
       } // End of while keep searching over all true edge neighbours
     } // End of loop over edges
     // Node not found, return null
     return 0;
   }
References D, oomph::OcTreeNames::DB, oomph::OcTreeNames::DF, oomph::OcTreeNames::F, oomph::OcTree::faces_of_common_edge(), oomph::FiniteElement::get_node_at_local_coordinate(), oomph::OcTree::gteq_face_neighbour(), oomph::OcTree::gteq_true_edge_neighbour(), i, j, L, oomph::OcTreeNames::LB, oomph::OcTreeNames::LD, oomph::OcTreeNames::LDB, oomph::OcTreeNames::LDF, oomph::OcTreeNames::LF, oomph::OcTreeNames::LU, oomph::OcTreeNames::LUB, oomph::OcTreeNames::LUF, oomph::Tree::nsons(), oomph::Tree::object_pt(), R, oomph::OcTreeNames::RB, oomph::OcTreeNames::RD, oomph::OcTreeNames::RDB, oomph::OcTreeNames::RDF, oomph::OcTreeNames::RF, oomph::OcTreeNames::RU, oomph::OcTreeNames::RUB, oomph::OcTreeNames::RUF, s, oomph::Tree::son_pt(), RachelsAdvectionDiffusion::U, oomph::OcTreeNames::UB, and oomph::OcTreeNames::UF.
oc_hang_helper()
template<unsigned INITIAL_NNODE_1D> void oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::oc_hang_helper (const int & value_id, const int & my_face, std::ofstream & output_hangfile) protected virtual
Set up hanging node information. Overloaded to implement the mortar method rather than constrained approximation. This enforces continuity weakly via an integral matching condition at non-conforming element boundaries.
Internal function to set up the hanging nodes on a particular edge of the element. Implements the mortar method.
/ Set up hanging scheme for this node
/ Print out hanging scheme
/ Print out local projection matrix
/ Print out global projection matrix
/ Print out solved global projection matrix
/ Create structures to hold the hanging info /----------------------------------------—
/ Copy information to hanging nodes /-------------------------------—
/ Print out hanging scheme
/ Print out dependent and master node coords
/ Print out diag(M)
/ Print out diag(M)
/ Print out local projection matrix
/ Print out global projection matrix
/ Print out solved matrix
Reimplemented from oomph::RefineableQElement< 3 >.
   {
     using namespace OcTreeNames;
     Vector<unsigned> translate_s(3);
     Vector<double> s_lo_neigh(3);
     Vector<double> s_hi_neigh(3);
     int neigh_face, diff_level;
     bool in_neighbouring_tree;
     // Find pointer to neighbour in this direction
     OcTree* neigh_pt;
     neigh_pt = this->octree_pt()->gteq_face_neighbour(my_face,
                                                       translate_s,
                                                       s_lo_neigh,
                                                       s_hi_neigh,
                                                       neigh_face,
                                                       diff_level,
                                                       in_neighbouring_tree);
     // Work out master/dependent faces
     //----------------------------
     // Set up booleans
     // bool h_type_master = false;
     bool h_type_dependent = false;
     // bool p_type_master = false;
     bool p_type_dependent = false;
     // Neighbour exists
     if (neigh_pt != 0)
     {
       // Check if neighbour is bigger than me
       if (diff_level != 0)
       {
         // Dependent at h-type non-conformity
         h_type_dependent = true;
       }
       // Check if neighbour is the same size as me
       else if (neigh_pt->nsons() == 0)
       {
         // Neighbour is same size as me
         // Find p-orders of each element
         unsigned my_p_order =
           dynamic_cast<PRefineableQElement<3, INITIAL_NNODE_1D>*>(this)
             ->p_order();
         unsigned neigh_p_order =
           dynamic_cast<PRefineableQElement<3, INITIAL_NNODE_1D>*>(
             neigh_pt->object_pt())
             ->p_order();
         // Check for p-type non-conformity
         if (neigh_p_order == my_p_order)
         {
           // At a conforming interface
         }
         else if (neigh_p_order < my_p_order)
         {
           // Dependent at p-type non-conformity
           p_type_dependent = true;
         }
         else
         {
           // Master at p-type non-conformity
           // p_type_master = true;
         }
       }
       // Neighbour must be smaller than me
       else
       {
         // Master at h-type non-conformity
         // h_type_master = true;
       }
     }
     else
     {
       // Face is on a boundary
     }
     // Work out master/dependent edges
     //----------------------------
     if (h_type_dependent || p_type_dependent || true)
     {
       // Get edges of face and the face that shares that edge
       Vector<unsigned> face_edge(4), face_edge_other_face(4);
       switch (my_face)
       {
         case L:
           face_edge[0] = LB;
           face_edge_other_face[0] = B;
           face_edge[1] = LF;
           face_edge_other_face[1] = F;
           face_edge[2] = LD;
           face_edge_other_face[2] = D;
           face_edge[3] = LU;
           face_edge_other_face[3] = U;
           break;
         case R:
           face_edge[0] = RB;
           face_edge_other_face[0] = B;
           face_edge[1] = RF;
           face_edge_other_face[1] = F;
           face_edge[2] = RD;
           face_edge_other_face[2] = D;
           face_edge[3] = RU;
           face_edge_other_face[3] = U;
           break;
         case U:
           face_edge[0] = UB;
           face_edge_other_face[0] = B;
           face_edge[1] = UF;
           face_edge_other_face[1] = F;
           face_edge[2] = LU;
           face_edge_other_face[2] = L;
           face_edge[3] = RU;
           face_edge_other_face[3] = R;
           break;
         case D:
           face_edge[0] = DB;
           face_edge_other_face[0] = B;
           face_edge[1] = DF;
           face_edge_other_face[1] = F;
           face_edge[2] = LD;
           face_edge_other_face[2] = L;
           face_edge[3] = RD;
           face_edge_other_face[3] = R;
           break;
         case B:
           face_edge[0] = DB;
           face_edge_other_face[0] = D;
           face_edge[1] = UB;
           face_edge_other_face[1] = U;
           face_edge[2] = LB;
           face_edge_other_face[2] = L;
           face_edge[3] = RB;
           face_edge_other_face[3] = R;
           break;
         case F:
           face_edge[0] = DF;
           face_edge_other_face[0] = D;
           face_edge[1] = UF;
           face_edge_other_face[1] = U;
           face_edge[2] = LF;
           face_edge_other_face[2] = L;
           face_edge[3] = RF;
           face_edge_other_face[3] = R;
           break;
         default:
           throw OomphLibError(
             "my_face not L, R, D, U, B, F\n",
             "PRefineableQElement<3,INITIAL_NNODE_1D>::oc_hang_helper()",
             OOMPH_EXCEPTION_LOCATION);
       }
       // Loop over edges of face
       for (unsigned i = 0; i < 4; i++)
       {
         // Get edge
         unsigned my_edge = face_edge[i];
         // Separate storage for edge mortaring
         OcTree* edge_neigh_pt = 0;
         Vector<unsigned> edge_translate_s(3);
         Vector<double> edge_s_lo_neigh(3);
         Vector<double> edge_s_hi_neigh(3);
         int neigh_edge = 0, edge_diff_level = 0;
         unsigned edge_p_order =
           dynamic_cast<PRefineableQElement<3, INITIAL_NNODE_1D>*>(this)
             ->p_order();
         // Temporary storage to keep track of master edge
         Vector<unsigned> tmp_edge_translate_s(3);
         Vector<double> tmp_edge_s_lo_neigh(3);
         Vector<double> tmp_edge_s_hi_neigh(3);
         int tmp_neigh_edge, tmp_edge_diff_level;
         // Initially return the zero-th true edge neighbour
         unsigned i_root_edge_neighbour = 0;
         // Initialise the total number of true edge neighbours
         unsigned nroot_edge_neighbour = 0;
         // Flag to keep track of master status of my_edge
         bool my_edge_is_master = true;
         // unsigned master_edge_index=0;
         // Keep searching until we've found the node or until we've checked
         // all available edge neighbours
         bool keep_searching = true;
         bool search_faces = false;
         bool first_face_searched = false;
         // unsigned index=0;
         while (keep_searching)
         {
           // Pointer to edge neighbouring OcTree
           OcTree* tmp_edge_neigh_pt;
           // Looking in edge neighbours that are also face neighbours
           // if(index==0 || index==1)
           if (search_faces)
           {
             if (!first_face_searched)
             {
               // Find pointer to neighbour in this direction
               tmp_edge_neigh_pt =
                 this->octree_pt()->gteq_face_neighbour(my_face,
                                                        tmp_edge_translate_s,
                                                        tmp_edge_s_lo_neigh,
                                                        tmp_edge_s_hi_neigh,
                                                        tmp_neigh_edge,
                                                        tmp_edge_diff_level,
                                                        in_neighbouring_tree);
               // Mark first face as searched
               first_face_searched = true;
             }
             else
             {
               // Find pointer to neighbour in this direction
               tmp_edge_neigh_pt =
                 this->octree_pt()->gteq_face_neighbour(face_edge_other_face[i],
                                                        tmp_edge_translate_s,
                                                        tmp_edge_s_lo_neigh,
                                                        tmp_edge_s_hi_neigh,
                                                        tmp_neigh_edge,
                                                        tmp_edge_diff_level,
                                                        in_neighbouring_tree);
               // Search is finally exhausted
               keep_searching = false;
             }
           }
           // Looking in a true edge neighbour
           else
           {
             // Find pointer to neighbour in this direction
             tmp_edge_neigh_pt =
               this->octree_pt()->gteq_true_edge_neighbour(my_edge,
                                                           i_root_edge_neighbour,
                                                           nroot_edge_neighbour,
                                                           tmp_edge_translate_s,
                                                           tmp_edge_s_lo_neigh,
                                                           tmp_edge_s_hi_neigh,
                                                           tmp_neigh_edge,
                                                           tmp_edge_diff_level);
           }
           // Set up booleans
           // bool h_type_edge_master = false;
           // bool h_type_edge_dependent  = false;
           // bool p_type_edge_master = false;
           // bool p_type_edge_dependent  = false;
           // Flag to check if we have a new edge master
           bool new_edge_master = false;
           // Edge neighbour exists
           if (tmp_edge_neigh_pt != 0)
           {
             // Check if neighbour is bigger than my biggest neighbour
             if (tmp_edge_diff_level < edge_diff_level)
             {
               // Dependent at h-type non-conformity
               // h_type_edge_dependent = true;
               new_edge_master = true;
               // Update edge_diff_level and p-order
               edge_diff_level = tmp_edge_diff_level;
               edge_p_order =
                 dynamic_cast<PRefineableQElement<3, INITIAL_NNODE_1D>*>(
                   tmp_edge_neigh_pt->object_pt())
                   ->p_order();
             }
             // Check if neighbour is the same size as my biggest neighbour
             else if (tmp_edge_diff_level == edge_diff_level &&
                      tmp_edge_neigh_pt->nsons() == 0)
             {
               // Neighbour is same size as me
               // Find p-orders of each element
               // unsigned my_p_order =
               // dynamic_cast<PRefineableQElement<3,INITIAL_NNODE_1D>*>
               //  (this)->p_order();
               unsigned tmp_edge_neigh_p_order =
                 dynamic_cast<PRefineableQElement<3, INITIAL_NNODE_1D>*>(
                   tmp_edge_neigh_pt->object_pt())
                   ->p_order();
               // Check for p-type non-conformity
               if (tmp_edge_neigh_p_order == edge_p_order)
               {
                 // At a conforming interface
               }
               else if (tmp_edge_neigh_p_order < edge_p_order)
               {
                 // Dependent at p-type non-conformity
                 // p_type_edge_dependent = true;
                 new_edge_master = true;
                 // Update edge_diff_level and p-order
                 edge_diff_level = tmp_edge_diff_level;
                 edge_p_order =
                   dynamic_cast<PRefineableQElement<3, INITIAL_NNODE_1D>*>(
                     tmp_edge_neigh_pt->object_pt())
                     ->p_order();
               }
               else
               {
                 // Master at p-type non-conformity
                 // p_type_edge_master = true;
               }
             }
             // Neighbour must be smaller than me
             else
             {
               // Master at h-type non-conformity
               // h_type_edge_master = true;
             }
           }
           else
           {
             // Edge is on a boundary
           }
           // Update master neighbour information
           if (new_edge_master)
           {
             // Store new master edge information
             edge_neigh_pt = tmp_edge_neigh_pt;
             edge_translate_s = tmp_edge_translate_s;
             edge_s_lo_neigh = tmp_edge_s_lo_neigh;
             edge_s_hi_neigh = tmp_edge_s_hi_neigh;
             neigh_edge = tmp_neigh_edge;
             edge_diff_level = tmp_edge_diff_level;
             // Set this edge as dependent
             my_edge_is_master = false;
           }
           // Keep searching, but only if there are further edge neighbours
           // Try next root edge neighbour
           i_root_edge_neighbour++;
           // Increment counter
           // index++;
           // Have we exhausted the search over true edge neighbours
           // if (index>2 && i_root_edge_neighbour>=nroot_edge_neighbour)
           if (i_root_edge_neighbour >= nroot_edge_neighbour)
           {
             // keep_searching = false;
             // Extend search to face neighours (these are edge neighbours too)
             search_faces = true;
           }
         } // End of while keep searching over all face and true edge neighbours
         // Now do edge mortaring to enforce the mortar vertex matching condition
         if (!my_edge_is_master)
         {
           // Compute the active coordinate index along the this side of mortar
           unsigned active_coord_index;
           switch (my_edge)
           {
             case DB:
             case DF:
             case UB:
             case UF:
               active_coord_index = 0;
               break;
             case LB:
             case RB:
             case LF:
             case RF:
               active_coord_index = 1;
               break;
             case LD:
             case RD:
             case LU:
             case RU:
               active_coord_index = 2;
               break;
             default:
               throw OomphLibError(
                 "Cannot transform coordinates",
                 "PRefineableQElement<3,INITIAL_NNODE_1D>::oc_hang_helper()",
                 OOMPH_EXCEPTION_LOCATION);
           }
           // Get pointer to neighbouring master element (in p-refineable form)
           PRefineableQElement<3, INITIAL_NNODE_1D>* edge_neigh_obj_pt;
           edge_neigh_obj_pt =
             dynamic_cast<PRefineableQElement<3, INITIAL_NNODE_1D>*>(
               edge_neigh_pt->object_pt());
           // Create vector of master and dependent nodes
           //----------------------------------------
           Vector<Node*> master_node_pt, dependent_node_pt;
           Vector<unsigned> master_node_number, dependent_node_number;
           Vector<Vector<double>> dependent_node_s_fraction;
           // Number of nodes in one dimension
           const unsigned my_n_p = this->ninterpolating_node_1d(value_id);
           const unsigned neigh_n_p =
             edge_neigh_obj_pt->ninterpolating_node_1d(value_id);
           // Storage for pointers to the nodes and their numbers along the
           // master edge
           unsigned neighbour_node_number = 0;
           Node* neighbour_node_pt = 0;
           // Loop over nodes along the edge
           bool master_is_not_edge = false;
           for (unsigned i0 = 0; i0 < neigh_n_p; i0++)
           {
             const unsigned s0space = 1;
             const unsigned s1space = neigh_n_p;
             const unsigned s2space = neigh_n_p * neigh_n_p;
             // Find the neighbour's node
             switch (neigh_edge)
             {
               case DB:
                 neighbour_node_number = i0 * s0space;
                 neighbour_node_pt = edge_neigh_obj_pt->interpolating_node_pt(
                   neighbour_node_number, value_id);
                 break;
               case UB:
                 neighbour_node_number =
                   (neigh_n_p - 1) * s1space + i0 * s0space;
                 neighbour_node_pt = edge_neigh_obj_pt->interpolating_node_pt(
                   neighbour_node_number, value_id);
                 break;
               case DF:
                 neighbour_node_number =
                   (neigh_n_p - 1) * s2space + i0 * s0space;
                 neighbour_node_pt = edge_neigh_obj_pt->interpolating_node_pt(
                   neighbour_node_number, value_id);
                 break;
               case UF:
                 neighbour_node_number = (neigh_n_p - 1) * s1space +
                                         (neigh_n_p - 1) * s2space +
                                         i0 * s0space;
                 neighbour_node_pt = edge_neigh_obj_pt->interpolating_node_pt(
                   neighbour_node_number, value_id);
                 break;
               case LB:
                 neighbour_node_number = i0 * s1space;
                 neighbour_node_pt = edge_neigh_obj_pt->interpolating_node_pt(
                   neighbour_node_number, value_id);
                 break;
               case RB:
                 neighbour_node_number =
                   (neigh_n_p - 1) * s0space + i0 * s1space;
                 neighbour_node_pt = edge_neigh_obj_pt->interpolating_node_pt(
                   neighbour_node_number, value_id);
                 break;
               case LF:
                 neighbour_node_number =
                   (neigh_n_p - 1) * s2space + i0 * s1space;
                 neighbour_node_pt = edge_neigh_obj_pt->interpolating_node_pt(
                   neighbour_node_number, value_id);
                 break;
               case RF:
                 neighbour_node_number = (neigh_n_p - 1) * s0space +
                                         (neigh_n_p - 1) * s2space +
                                         i0 * s1space;
                 neighbour_node_pt = edge_neigh_obj_pt->interpolating_node_pt(
                   neighbour_node_number, value_id);
                 break;
               case LD:
                 neighbour_node_number = i0 * s2space;
                 neighbour_node_pt = edge_neigh_obj_pt->interpolating_node_pt(
                   neighbour_node_number, value_id);
                 break;
               case RD:
                 neighbour_node_number =
                   (neigh_n_p - 1) * s0space + i0 * s2space;
                 neighbour_node_pt = edge_neigh_obj_pt->interpolating_node_pt(
                   neighbour_node_number, value_id);
                 break;
               case LU:
                 neighbour_node_number =
                   (neigh_n_p - 1) * s1space + i0 * s2space;
                 neighbour_node_pt = edge_neigh_obj_pt->interpolating_node_pt(
                   neighbour_node_number, value_id);
                 break;
               case RU:
                 neighbour_node_number = (neigh_n_p - 1) * s0space +
                                         (neigh_n_p - 1) * s1space +
                                         i0 * s2space;
                 neighbour_node_pt = edge_neigh_obj_pt->interpolating_node_pt(
                   neighbour_node_number, value_id);
                 break;
               default:
                 // Master 'edge' may be a face instead, so no need to throw an
                 // error
                 master_is_not_edge = true;
             }
             if (master_is_not_edge) break;
             // Set node as master node
             master_node_number.push_back(neighbour_node_number);
             master_node_pt.push_back(neighbour_node_pt);
           }
           // Now if edge is really a face (from an edge neighbour that isn't
           // a true edge neighbour) each node on the face is (potentially) a
           // master
           if (master_is_not_edge)
           {
             // Loop over nodes along the face
             for (unsigned i0 = 0; i0 < neigh_n_p; i0++)
             {
               // Loop over nodes along the face
               for (unsigned i1 = 0; i1 < neigh_n_p; i1++)
               {
                 const unsigned s0space = 1;
                 const unsigned s1space = neigh_n_p;
                 const unsigned s2space = neigh_n_p * neigh_n_p;
                 // Find the neighbour's node
                 switch (neigh_edge)
                 {
                   case B:
                     neighbour_node_number = i0 * s0space + i1 * s1space;
                     neighbour_node_pt =
                       edge_neigh_obj_pt->interpolating_node_pt(
                         neighbour_node_number, value_id);
                     break;
                   case F:
                     neighbour_node_number =
                       (neigh_n_p - 1) * s2space + i0 * s0space + i1 * s1space;
                     neighbour_node_pt =
                       edge_neigh_obj_pt->interpolating_node_pt(
                         neighbour_node_number, value_id);
                     break;
                   case D:
                     neighbour_node_number = i0 * s0space + i1 * s2space;
                     neighbour_node_pt =
                       edge_neigh_obj_pt->interpolating_node_pt(
                         neighbour_node_number, value_id);
                     break;
                   case U:
                     neighbour_node_number =
                       (neigh_n_p - 1) * s1space + i0 * s0space + i1 * s2space;
                     neighbour_node_pt =
                       edge_neigh_obj_pt->interpolating_node_pt(
                         neighbour_node_number, value_id);
                     break;
                   case L:
                     neighbour_node_number = i0 * s1space + i1 * s2space;
                     neighbour_node_pt =
                       edge_neigh_obj_pt->interpolating_node_pt(
                         neighbour_node_number, value_id);
                     break;
                   case R:
                     neighbour_node_number =
                       (neigh_n_p - 1) * s0space + i0 * s1space + i1 * s2space;
                     neighbour_node_pt =
                       edge_neigh_obj_pt->interpolating_node_pt(
                         neighbour_node_number, value_id);
                     break;
                   default:
                     throw OomphLibError("neigh_edge not recognised\n",
                                         "PRefineableQElement<3,INITIAL_NNODE_"
                                         "1D>::oc_hang_helper()",
                                         OOMPH_EXCEPTION_LOCATION);
                 }
                 // Set node as master node
                 master_node_number.push_back(neighbour_node_number);
                 master_node_pt.push_back(neighbour_node_pt);
               }
             }
           }
           // Storage for pointers to the local nodes and their numbers along my
           // edge
           unsigned local_node_number = 0;
           Node* local_node_pt = 0;
           // Loop over the nodes along my edge
           for (unsigned i0 = 0; i0 < my_n_p; i0++)
           {
             // Storage for the fractional position of the node in the element
             Vector<double> s_fraction(3);
             const unsigned s0space = 1;
             const unsigned s1space = my_n_p;
             const unsigned s2space = my_n_p * my_n_p;
             // Find the local node and the fractional position of the node
             // which depends on the edge, of course
             switch (my_edge)
             {
               case DB:
                 s_fraction[0] =
                   local_one_d_fraction_of_interpolating_node(i0, 0, value_id);
                 s_fraction[1] = 0.0;
                 s_fraction[2] = 0.0;
                 local_node_number = i0 * s0space;
                 local_node_pt =
                   this->interpolating_node_pt(local_node_number, value_id);
                 break;
               case UB:
                 s_fraction[0] =
                   local_one_d_fraction_of_interpolating_node(i0, 0, value_id);
                 s_fraction[1] = 1.0;
                 s_fraction[2] = 0.0;
                 local_node_number = (my_n_p - 1) * s1space + i0 * s0space;
                 local_node_pt =
                   this->interpolating_node_pt(local_node_number, value_id);
                 break;
               case DF:
                 s_fraction[0] =
                   local_one_d_fraction_of_interpolating_node(i0, 0, value_id);
                 s_fraction[1] = 0.0;
                 s_fraction[2] = 1.0;
                 local_node_number = (my_n_p - 1) * s2space + i0 * s0space;
                 local_node_pt =
                   this->interpolating_node_pt(local_node_number, value_id);
                 break;
               case UF:
                 s_fraction[0] =
                   local_one_d_fraction_of_interpolating_node(i0, 0, value_id);
                 s_fraction[1] = 1.0;
                 s_fraction[2] = 1.0;
                 local_node_number = (my_n_p - 1) * s1space +
                                     (my_n_p - 1) * s2space + i0 * s0space;
                 local_node_pt =
                   this->interpolating_node_pt(local_node_number, value_id);
                 break;
               case LB:
                 s_fraction[0] = 0.0;
                 s_fraction[1] =
                   local_one_d_fraction_of_interpolating_node(i0, 1, value_id);
                 s_fraction[2] = 0.0;
                 local_node_number = i0 * s1space;
                 local_node_pt =
                   this->interpolating_node_pt(local_node_number, value_id);
                 break;
               case RB:
                 s_fraction[0] = 1.0;
                 s_fraction[1] =
                   local_one_d_fraction_of_interpolating_node(i0, 1, value_id);
                 s_fraction[2] = 0.0;
                 local_node_number = (my_n_p - 1) * s0space + i0 * s1space;
                 local_node_pt =
                   this->interpolating_node_pt(local_node_number, value_id);
                 break;
               case LF:
                 s_fraction[0] = 0.0;
                 s_fraction[1] =
                   local_one_d_fraction_of_interpolating_node(i0, 1, value_id);
                 s_fraction[2] = 1.0;
                 local_node_number = (my_n_p - 1) * s2space + i0 * s1space;
                 local_node_pt =
                   this->interpolating_node_pt(local_node_number, value_id);
                 break;
               case RF:
                 s_fraction[0] = 1.0;
                 s_fraction[1] =
                   local_one_d_fraction_of_interpolating_node(i0, 1, value_id);
                 s_fraction[2] = 1.0;
                 local_node_number = (my_n_p - 1) * s0space +
                                     (my_n_p - 1) * s2space + i0 * s1space;
                 local_node_pt =
                   this->interpolating_node_pt(local_node_number, value_id);
                 break;
               case LD:
                 s_fraction[0] = 0.0;
                 s_fraction[1] = 0.0;
                 s_fraction[2] =
                   local_one_d_fraction_of_interpolating_node(i0, 2, value_id);
                 local_node_number = i0 * s2space;
                 local_node_pt =
                   this->interpolating_node_pt(local_node_number, value_id);
                 break;
               case RD:
                 s_fraction[0] = 1.0;
                 s_fraction[1] = 0.0;
                 s_fraction[2] =
                   local_one_d_fraction_of_interpolating_node(i0, 2, value_id);
                 local_node_number = (my_n_p - 1) * s0space + i0 * s2space;
                 local_node_pt =
                   this->interpolating_node_pt(local_node_number, value_id);
                 break;
               case LU:
                 s_fraction[0] = 0.0;
                 s_fraction[1] = 1.0;
                 s_fraction[2] =
                   local_one_d_fraction_of_interpolating_node(i0, 2, value_id);
                 local_node_number = (my_n_p - 1) * s1space + i0 * s2space;
                 local_node_pt =
                   this->interpolating_node_pt(local_node_number, value_id);
                 break;
               case RU:
                 s_fraction[0] = 1.0;
                 s_fraction[1] = 1.0;
                 s_fraction[2] =
                   local_one_d_fraction_of_interpolating_node(i0, 2, value_id);
                 local_node_number = (my_n_p - 1) * s0space +
                                     (my_n_p - 1) * s1space + i0 * s2space;
                 local_node_pt =
                   this->interpolating_node_pt(local_node_number, value_id);
                 break;
               default:
                 throw OomphLibError(
                   "my_edge not recognised\n",
                   "PRefineableQElement<3,INITIAL_NNODE_1D>::oc_hang_helper()",
                   OOMPH_EXCEPTION_LOCATION);
             }
             // Add node to vector of dependent element nodes
             dependent_node_number.push_back(local_node_number);
             dependent_node_pt.push_back(local_node_pt);
             // Store node's local fraction
             dependent_node_s_fraction.push_back(s_fraction);
           }
           // Store the number of dependent and master nodes for use later
           const unsigned n_dependent_nodes = dependent_node_pt.size();
           const unsigned n_master_nodes = master_node_pt.size();
           const unsigned dependent_element_nnode_1d = my_n_p;
           const unsigned master_element_nnode_1d = neigh_n_p;
           // Storage for master shapes
           Shape master_shapes(edge_neigh_obj_pt->ninterpolating_node(value_id));
           // Get master and dependent nodal positions
           //-------------------------------------
           Vector<double> dependent_nodal_position;
           Vector<double> dependent_weight(dependent_element_nnode_1d);
           Orthpoly::gll_nodes(dependent_element_nnode_1d,
                               dependent_nodal_position,
                               dependent_weight);
           Vector<double> master_nodal_position;
           Vector<double> master_weight(master_element_nnode_1d);
           Orthpoly::gll_nodes(
             master_element_nnode_1d, master_nodal_position, master_weight);
           // Apply the (1D) vertex matching condition
           //-----------------------------------------
           // Vertiex matching is ensured automatically in cases where there is a
           // node at each end of the mortar that is shared between the master
           // and dependent elements. Where this is not the case, the vertex
           // matching condition must be enforced by constraining the value of
           // the unknown at the node on the dependent side to be the same as the
           // value at that location in the master.
           // Store positions of the mortar vertex/non-vertex nodes in the
           // dependent element
           const unsigned n_mortar_vertices = 2;
           Vector<unsigned> vertex_pos(n_mortar_vertices);
           vertex_pos[0] = 0;
           vertex_pos[1] = this->ninterpolating_node_1d(value_id) - 1;
           Vector<unsigned> non_vertex_pos(my_n_p - n_mortar_vertices);
           for (unsigned i = 0; i < my_n_p - n_mortar_vertices; i++)
           {
             non_vertex_pos[i] = i + 1;
           }
           // If the node is on a master edge, we may be setting the
           // hanging info incorrectly. Hanging schemes (if they are
           // required) for such nodes are instead computed by the
           // dependent edge. We dont't want to overwrite them here!
           std::vector<bool> mortar_vertex_on_master_edge(n_mortar_vertices);
           for (unsigned v = 0; v < n_mortar_vertices; v++)
           {
             // Check if each node is on the master edge
             mortar_vertex_on_master_edge[v] = true;
             unsigned non_extreme_coordinate = 0;
             Vector<double> s_in_neigh(3);
             for (unsigned i = 0; i < 3; i++)
             {
               // Work out this node's location in the master
               s_in_neigh[i] =
                 edge_s_lo_neigh[i] +
                 dependent_node_s_fraction[vertex_pos[v]][edge_translate_s[i]] *
                   (edge_s_hi_neigh[i] - edge_s_lo_neigh[i]);
               // Check if local coordinate in master element takes non-extreme
               // value
               if (std::fabs(std::fabs(s_in_neigh[i]) - 1.0) > 1.0e-14)
               {
                 non_extreme_coordinate++;
                 if (non_extreme_coordinate > 1)
                 {
                   mortar_vertex_on_master_edge[v] = false;
                   break;
                 }
               }
             }
           }
           // Now work out if my edge coincides with the master edge
           bool my_edge_coincides_with_master = true;
           for (unsigned v = 0; v < n_mortar_vertices; v++)
           {
             my_edge_coincides_with_master =
               my_edge_coincides_with_master && mortar_vertex_on_master_edge[v];
           }
           // Check if we need to apply the (1D) vertex matching condition at the
           // mortar vertices. This is trivially satisfied if the node is shared
           // with the master, but if not then we need to constrain it.
           for (unsigned v = 0; v < n_mortar_vertices; v++)
           {
             // Don't make hanging node if my edge doesn't coincide with
             // the master edge *and* this node is on the master edge!
             // (We are not in a position to determine its hanging status.)
             if ((!my_edge_coincides_with_master) &&
                 mortar_vertex_on_master_edge[v])
               continue;
             // Search master node storage for the node
             bool node_is_shared = false;
             for (unsigned i = 0; i < master_node_pt.size(); i++)
             {
               if (dependent_node_pt[vertex_pos[v]] == master_node_pt[i])
               {
                 node_is_shared = true;
                 break;
               }
             }
             // If the node is not shared then we must constrain its value by
             // setting up a hanging scheme
             if (!node_is_shared)
             {
               // Calculate weights. These are just the master shapes evaluated
               // at this dependent node's position
               // Work out this node's location in the master
               Vector<double> s_in_neigh(3);
               for (unsigned i = 0; i < 3; i++)
               {
                 s_in_neigh[i] = edge_s_lo_neigh[i] +
                                 dependent_node_s_fraction[vertex_pos[v]]
                                                          [edge_translate_s[i]] *
                                   (edge_s_hi_neigh[i] - edge_s_lo_neigh[i]);
               }
               // Get master shapes at dependent nodal positions
               edge_neigh_obj_pt->interpolating_basis(
                 s_in_neigh, master_shapes, value_id);
               // Remove any existing hanging node info
               // (This may be a bit wasteful, but guarantees correctness)
               dependent_node_pt[vertex_pos[v]]->set_nonhanging();
               // Don't include master nodes with zero weights
               Vector<unsigned> master_node_zero_weight;
               for (unsigned m = 0; m < n_master_nodes; m++)
               {
                 // Compare weights to some (small) tolerance
                 if (std::fabs(master_shapes[master_node_number[m]]) < 1.0e-14)
                 {
                   // Store
                   master_node_zero_weight.push_back(m);
                 }
               }
               // Set up hanging scheme for this node
               HangInfo* explicit_hang_pt =
                 new HangInfo(n_master_nodes - master_node_zero_weight.size());
               unsigned mindex = 0;
               for (unsigned m = 0; m < n_master_nodes; m++)
               {
                 // Check that master doesn't have zero weight
                 bool skip = false;
                 for (unsigned i = 0; i < master_node_zero_weight.size(); i++)
                 {
                   if (m == master_node_zero_weight[i]) skip = true;
                 }
                 // Add pointer and weight to hang info
                 if (!skip)
                   explicit_hang_pt->set_master_node_pt(
                     mindex++,
                     master_node_pt[m],
                     master_shapes[master_node_number[m]]);
               }
               // HangInfo* explicit_hang_pt = new HangInfo(n_master_nodes);
               // for(unsigned m=0; m<n_master_nodes; m++)
               // {
               //  explicit_hang_pt->set_master_node_pt(m,master_node_pt[m],master_shapes[master_node_number[m]]);
               // }
               // Make node hang
               dependent_node_pt[vertex_pos[v]]->set_hanging_pt(explicit_hang_pt,
                                                                -1);
               // std::cout << "Hanging node: "
               //          << dependent_node_pt[vertex_pos[v]]->x(0) << "  "
               //          << dependent_node_pt[vertex_pos[v]]->x(1) << "  "
               //          << dependent_node_pt[vertex_pos[v]]->x(2) << "  "
               //          << std::endl;
               // for(unsigned m=0; m<explicit_hang_pt->nmaster(); m++)
               // {
               //  std::cout << "   m = " << m << ": "
               //            << explicit_hang_pt->master_node_pt(m)->x(0) << "  "
               //            << explicit_hang_pt->master_node_pt(m)->x(1) << "  "
               //            << explicit_hang_pt->master_node_pt(m)->x(2) << "  "
               //            << "w = " << explicit_hang_pt->master_weight(m) << "
               //            "
               //            << std::endl;
               // }
               // Check there are no zero weights at this stage
               for (unsigned m = 0; m < explicit_hang_pt->nmaster(); m++)
               {
                 if (std::fabs(explicit_hang_pt->master_weight(m)) < 1.0e-14)
                 {
                   throw OomphLibError(
                     "Master has zero weight!",
                     "PRefineableQElement<3,INITIAL_NNODE_1D>::oc_hang_helper()",
                     OOMPH_EXCEPTION_LOCATION);
                 }
               }
             }
           }
           // Check that there are actually dependent nodes for which we still
           // need to construct a hanging scheme. If not then there is nothing
           // more to do.
           if (n_dependent_nodes - n_mortar_vertices > 0)
           {
             // Assemble mass matrix for mortar
             //--------------------------------
             Vector<double> psi(n_dependent_nodes - n_mortar_vertices);
             Vector<double> diag_M(n_dependent_nodes - n_mortar_vertices);
             Vector<Vector<double>> shared_node_M(n_mortar_vertices);
             for (unsigned i = 0; i < shared_node_M.size(); i++)
             {
               shared_node_M[i].resize(n_dependent_nodes - n_mortar_vertices);
             }
             // Fill in part corresponding to dependent nodal positions (unknown)
             for (unsigned i = 0; i < n_dependent_nodes - n_mortar_vertices; i++)
             {
               // Use L'Hosptal's rule:
               psi[i] =
                 pow(-1.0, int((dependent_element_nnode_1d - 1) - i - 1)) *
                 -Orthpoly::ddlegendre(
                   dependent_element_nnode_1d - 1,
                   dependent_nodal_position[non_vertex_pos[i]]);
               // Put in contribution
               diag_M[i] = psi[i] * dependent_weight[non_vertex_pos[i]];
             }
             // Fill in part corresponding to dependent element vertices (known)
             for (unsigned v = 0; v < shared_node_M.size(); v++)
             {
               for (unsigned i = 0; i < n_dependent_nodes - n_mortar_vertices;
                    i++)
               {
                 // Check if denominator is zero
                 if (std::fabs(dependent_nodal_position[non_vertex_pos[i]] -
                               dependent_nodal_position[vertex_pos[v]]) >=
                     1.0e-8)
                 {
                   // We're ok
                   psi[i] =
                     pow(-1.0, int((dependent_element_nnode_1d - 1) - i - 1)) *
                     Orthpoly::dlegendre(
                       dependent_element_nnode_1d - 1,
                       dependent_nodal_position[vertex_pos[v]]) /
                     (dependent_nodal_position[non_vertex_pos[i]] -
                      dependent_nodal_position[vertex_pos[v]]);
                 }
                 // Check if numerator is zero
                 else if (std::fabs(Orthpoly::dlegendre(
                            dependent_element_nnode_1d - 1,
                            dependent_nodal_position[vertex_pos[v]])) < 1.0e-8)
                 {
                   // We can use l'hopital's rule
                   psi[i] =
                     pow(-1.0, int((dependent_element_nnode_1d - 1) - i - 1)) *
                     -Orthpoly::ddlegendre(
                       dependent_element_nnode_1d - 1,
                       dependent_nodal_position[non_vertex_pos[i]]);
                 }
                 else
                 {
                   // We can't use l'hopital's rule
                   throw OomphLibError(
                     "Cannot use l'Hopital's rule. Dividing by zero is not "
                     "allowed!",
                     "PRefineableQElement<3,INITIAL_NNODE_1D>::oc_hang_helper()",
                     OOMPH_EXCEPTION_LOCATION);
                 }
                 // Put in contribution
                 shared_node_M[v][i] = psi[i] * dependent_weight[vertex_pos[v]];
               }
             }
             // Assemble local projection matrix for mortar
             //--------------------------------------------
             // Have only one local projection matrix because there is just one
             // master
             Vector<Vector<double>> P(n_dependent_nodes - n_mortar_vertices);
             for (unsigned i = 0; i < P.size(); i++)
             {
               P[i].resize(n_master_nodes, 0.0);
             }
             // Storage for local coordinate
             Vector<double> s(3);
             // Sum contributions from master element shapes (quadrature).
             // The order of quadrature must be high enough to evaluate a
             // polynomial of order N_s + N_m - 3 exactly, where N_s =
             // n_dependent_nodes, N_m = n_master_nodes. (Use pointers for the
             // quadrature knots and weights so that data is not unnecessarily
             // copied)
             // unsigned quadrature_order =
             // std::max(dependent_element_nnode_1d,master_element_nnode_1d);
             Vector<double>*quadrature_knot, *quadrature_weight;
             if (dependent_element_nnode_1d >= master_element_nnode_1d)
             {
               // Use the same quadrature order as the dependent element (me)
               quadrature_knot = &dependent_nodal_position;
               quadrature_weight = &dependent_weight;
             }
             else
             {
               // Use the same quadrature order as the master element (neighbour)
               quadrature_knot = &master_nodal_position;
               quadrature_weight = &master_weight;
             }
             // Quadrature loop
             for (unsigned q = 0; q < (*quadrature_weight).size(); q++)
             {
               // Evaluate mortar test functions at the quadrature knots in the
               // dependent
               // s[active_coord_index] = (*quadrature_knot)[q];
               Vector<double> s_on_mortar(1);
               s_on_mortar[0] = (*quadrature_knot)[q];
               // Get psi
               for (unsigned k = 0; k < n_dependent_nodes - n_mortar_vertices;
                    k++)
               {
                 // Check if denominator is zero
                 if (std::fabs(dependent_nodal_position[non_vertex_pos[k]] -
                               s_on_mortar[0]) >= 1.0e-08)
                 {
                   // We're ok
                   psi[k] =
                     pow(-1.0, int((dependent_element_nnode_1d - 1) - k - 1)) *
                     Orthpoly::dlegendre(dependent_element_nnode_1d - 1,
                                         s_on_mortar[0]) /
                     (dependent_nodal_position[non_vertex_pos[k]] -
                      s_on_mortar[0]);
                 }
                 // Check if numerator is zero
                 else if (std::fabs(Orthpoly::dlegendre(
                            dependent_element_nnode_1d - 1, s_on_mortar[0])) <
                          1.0e-8)
                 {
                   // We can use l'Hopital's rule
                   psi[k] =
                     pow(-1.0, int((dependent_element_nnode_1d - 1) - k - 1)) *
                     -Orthpoly::ddlegendre(dependent_element_nnode_1d - 1,
                                           s_on_mortar[0]);
                 }
                 else
                 {
                   // We can't use l'hopital's rule
                   throw OomphLibError(
                     "Cannot use l'Hopital's rule. Dividing by zero is not "
                     "allowed!",
                     "PRefineableQElement<3,INITIAL_NNODE_1D>::oc_hang_helper()",
                     OOMPH_EXCEPTION_LOCATION);
                 }
               }
               // Convert coordinate on mortar to local fraction in dependent
               // element
               Vector<double> s_fraction(3);
               for (unsigned i = 0; i < 3; i++)
               {
                 s_fraction[i] = (i == active_coord_index) ?
                                   0.5 * (s_on_mortar[0] + 1.0) :
                                   dependent_node_s_fraction[vertex_pos[0]][i];
               }
               // Project active coordinate into master element
               Vector<double> s_in_neigh(3);
               for (unsigned i = 0; i < 3; i++)
               {
                 s_in_neigh[i] = edge_s_lo_neigh[i] +
                                 s_fraction[edge_translate_s[i]] *
                                   (edge_s_hi_neigh[i] - edge_s_lo_neigh[i]);
               }
               // Evaluate master shapes at projections of local quadrature knots
               edge_neigh_obj_pt->interpolating_basis(
                 s_in_neigh, master_shapes, value_id);
               // Populate local projection matrix
               for (unsigned i = 0; i < n_dependent_nodes - n_mortar_vertices;
                    i++)
               {
                 for (unsigned j = 0; j < n_master_nodes; j++)
                 {
                   P[i][j] += master_shapes[master_node_number[j]] * psi[i] *
                              (*quadrature_weight)[q];
                 }
               }
             }
             // std::cout << "P_e:" << std::endl;
             // for(unsigned i=0; i<P.size(); i++)
             // {
             //  for(unsigned j=0; j<P[i].size(); j++)
             //   {
             //    std::cout << "  " << P[i][j];
             //   }
             // }
             // std::cout << std::endl;
             // Assemble global projection matrices for mortar
             //-----------------------------------------------
             // Need to subtract contributions from the "known unknowns"
             // corresponding to the nodes at the vertices of the mortar
             // Assemble contributions from mortar vertex nodes
             for (unsigned v = 0; v < n_mortar_vertices; v++)
             {
               // Convert coordinate on mortar to local fraction in dependent
               // element
               Vector<double> s_fraction(3);
               for (unsigned i = 0; i < 3; i++)
               {
                 s_fraction[i] =
                   (i == active_coord_index) ?
                     0.5 * (dependent_nodal_position[vertex_pos[v]] + 1.0) :
                     dependent_node_s_fraction[vertex_pos[0]][i];
               }
               // Project active coordinate into master element
               Vector<double> s_in_neigh(3);
               for (unsigned i = 0; i < 3; i++)
               {
                 s_in_neigh[i] = edge_s_lo_neigh[i] +
                                 s_fraction[edge_translate_s[i]] *
                                   (edge_s_hi_neigh[i] - edge_s_lo_neigh[i]);
               }
               // Get master shapes at dependent nodal positions
               edge_neigh_obj_pt->interpolating_basis(
                 s_in_neigh, master_shapes, value_id);
               for (unsigned i = 0; i < n_dependent_nodes - n_mortar_vertices;
                    i++)
               {
                 for (unsigned k = 0; k < n_master_nodes; k++)
                 {
                   P[i][k] -=
                     master_shapes[master_node_number[k]] * shared_node_M[v][i];
                 }
               }
             }
             // std::cout << "P:" << std::endl;
             // for(unsigned i=0; i<P.size(); i++)
             // {
             //  for(unsigned j=0; j<P[i].size(); j++)
             //   {
             //    std::cout << "  " << P[i][j];
             //   }
             //  std::cout << std::endl;
             // }
             // std::cout << std::endl;
             // Solve mortar system
             //--------------------
             for (unsigned i = 0; i < n_dependent_nodes - n_mortar_vertices; i++)
             {
               for (unsigned j = 0; j < n_master_nodes; j++)
               {
                 P[i][j] /= diag_M[i];
               }
             }
             // std::cout << "solved P:" << std::endl;
             // for(unsigned i=0; i<P.size(); i++)
             // {
             //  for(unsigned j=0; j<P[i].size(); j++)
             //   {
             //    std::cout << "  " << P[i][j];
             //   }
             //  std::cout << std::endl;
             // }
             // std::cout << std::endl;
             // Create and populate structures to hold the hanging info
             //--------------------------------------------------------
             Vector<HangInfo*> hang_info_pt(n_dependent_nodes);
             for (unsigned i = 0; i < n_dependent_nodes - n_mortar_vertices; i++)
             {
               // Don't include master nodes with zero weights
               Vector<unsigned> master_node_zero_weight;
               for (unsigned m = 0; m < n_master_nodes; m++)
               {
                 // Compare weights to some (small) tolerance
                 if (std::fabs(P[i][m]) < 1.0e-14)
                 {
                   // Store
                   master_node_zero_weight.push_back(m);
                 }
               }
               // Set up hanging scheme for this node
               hang_info_pt[i] =
                 new HangInfo(n_master_nodes - master_node_zero_weight.size());
               unsigned mindex = 0;
               for (unsigned m = 0; m < n_master_nodes; m++)
               {
                 // Check that master doesn't have zero weight
                 bool skip = false;
                 for (unsigned k = 0; k < master_node_zero_weight.size(); k++)
                 {
                   if (m == master_node_zero_weight[k]) skip = true;
                 }
                 // Add pointer and weight to hang info
                 if (!skip)
                   hang_info_pt[i]->set_master_node_pt(
                     mindex++, master_node_pt[m], P[i][m]);
               }
             }
             // Vector<HangInfo*> hang_info_pt(n_dependent_nodes);
             // for (unsigned i=0; i<n_dependent_nodes-n_mortar_vertices; i++)
             // {
             //  hang_info_pt[i] = new HangInfo(n_master_nodes);
             // }
             //
             // for(unsigned i=0; i<n_dependent_nodes-n_mortar_vertices; i++)
             // {
             //  for(unsigned j=0; j<n_master_nodes; j++)
             //   {
             //    hang_info_pt[i]->set_master_node_pt(j,master_node_pt[j],P[i][j]);
             //   }
             // }
             // Set pointers to hanging info
             //-----------------------------
             for (unsigned i = 0; i < n_dependent_nodes - n_mortar_vertices; i++)
             {
               // Check that the node shoule actually hang.
               // That is, if the polynomial orders of the elements at a p-type
               // non-conormity are both odd then the middle node on the edge is
               // shared but a hanging scheme has been constructed for it.
               bool node_is_really_shared = false;
               for (unsigned m = 0; m < hang_info_pt[i]->nmaster(); m++)
               {
                 // We can simply check if the hanging scheme lists itself as a
                 // master
                 if (hang_info_pt[i]->master_node_pt(m) ==
                     dependent_node_pt[non_vertex_pos[i]])
                 {
                   node_is_really_shared = true;
 #ifdef PARANOID
                   // Also check the corresponding weight: it should be 1
                   if (std::fabs(hang_info_pt[i]->master_weight(m) - 1.0) >
                       1.0e-06)
                   {
                     throw OomphLibError("Something fishy here -- with shared "
                                         "node at a mortar vertex",
                                         "PRefineableQElemen<2,INITIAL_NNODE_1D>"
                                         "t::quad_hang_helper()",
                                         OOMPH_EXCEPTION_LOCATION);
                   }
 #endif
                 }
               }
               // Now we can make the node hang, if it isn't a shared node
               if (!node_is_really_shared)
               {
                 dependent_node_pt[non_vertex_pos[i]]->set_hanging_pt(
                   hang_info_pt[i], -1);
                 // std::cout << "Hanging node: "
                 //          << dependent_node_pt[non_vertex_pos[i]]->x(0) << " "
                 //          << dependent_node_pt[non_vertex_pos[i]]->x(1) << " "
                 //          << dependent_node_pt[non_vertex_pos[i]]->x(2) << " "
                 //          << std::endl;
                 // for(unsigned m=0; m<hang_info_pt[i]->nmaster(); m++)
                 // {
                 //  std::cout << "   m = " << m << ": "
                 //            << hang_info_pt[i]->master_node_pt(m)->x(0) << " "
                 //            << hang_info_pt[i]->master_node_pt(m)->x(1) << " "
                 //            << hang_info_pt[i]->master_node_pt(m)->x(2) << " "
                 //            << "w = " << hang_info_pt[i]->master_weight(m) <<
                 //            "  "
                 //            << std::endl;
                 // }
               }
             }
           } // End of case where there are still dependent nodes
         } // End of edge is dependent
       } // End of loop over face edges
     } // End of if face is dependent
     // Now do the mortaring
     //---------------------
     if (h_type_dependent || p_type_dependent)
     {
       // Compute the active coordinate indices along the this side of mortar
       Vector<unsigned> active_coord_index(2);
       if (my_face == B || my_face == F)
       {
         active_coord_index[0] = 0;
         active_coord_index[1] = 1;
       }
       else if (my_face == D || my_face == U)
       {
         active_coord_index[0] = 0;
         active_coord_index[1] = 2;
       }
       else if (my_face == L || my_face == R)
       {
         active_coord_index[0] = 1;
         active_coord_index[1] = 2;
       }
       else
       {
         throw OomphLibError(
           "Cannot transform coordinates",
           "PRefineableQElement<3,INITIAL_NNODE_1D>::oc_hang_helper()",
           OOMPH_EXCEPTION_LOCATION);
       }
       // Get pointer to neighbouring master element (in p-refineable form)
       PRefineableQElement<3, INITIAL_NNODE_1D>* neigh_obj_pt;
       neigh_obj_pt = dynamic_cast<PRefineableQElement<3, INITIAL_NNODE_1D>*>(
         neigh_pt->object_pt());
       // Create vector of master and dependent nodes
       //----------------------------------------
       Vector<Node*> master_node_pt, dependent_node_pt;
       Vector<unsigned> master_node_number, dependent_node_number;
       Vector<Vector<double>> dependent_node_s_fraction;
       // Number of nodes in one dimension
       const unsigned my_n_p = this->ninterpolating_node_1d(value_id);
       const unsigned neigh_n_p = neigh_obj_pt->ninterpolating_node_1d(value_id);
       // Storage for pointers to the nodes and their numbers along the master
       // edge
       unsigned neighbour_node_number = 0;
       Node* neighbour_node_pt = 0;
       // Loop over nodes on the face
       for (unsigned i0 = 0; i0 < neigh_n_p; i0++)
       {
         for (unsigned i1 = 0; i1 < neigh_n_p; i1++)
         {
           const unsigned s0space = 1;
           const unsigned s1space = neigh_n_p;
           const unsigned s2space = neigh_n_p * neigh_n_p;
           // Find the neighbour's node
           switch (neigh_face)
           {
             case B:
               neighbour_node_number = i0 * s0space + i1 * s1space;
               neighbour_node_pt = neigh_obj_pt->interpolating_node_pt(
                 neighbour_node_number, value_id);
               break;
             case F:
               neighbour_node_number =
                 (neigh_n_p - 1) * s2space + i0 * s0space + i1 * s1space;
               neighbour_node_pt = neigh_obj_pt->interpolating_node_pt(
                 neighbour_node_number, value_id);
               break;
             case D:
               neighbour_node_number = i0 * s0space + i1 * s2space;
               neighbour_node_pt = neigh_obj_pt->interpolating_node_pt(
                 neighbour_node_number, value_id);
               break;
             case U:
               neighbour_node_number =
                 (neigh_n_p - 1) * s1space + i0 * s0space + i1 * s2space;
               neighbour_node_pt = neigh_obj_pt->interpolating_node_pt(
                 neighbour_node_number, value_id);
               break;
             case L:
               neighbour_node_number = i0 * s1space + i1 * s2space;
               neighbour_node_pt = neigh_obj_pt->interpolating_node_pt(
                 neighbour_node_number, value_id);
               break;
             case R:
               neighbour_node_number =
                 (neigh_n_p - 1) * s0space + i0 * s1space + i1 * s2space;
               neighbour_node_pt = neigh_obj_pt->interpolating_node_pt(
                 neighbour_node_number, value_id);
               break;
             default:
               throw OomphLibError(
                 "my_face not L, R, D, U, B, F\n",
                 "PRefineableQElement<3,INITIAL_NNODE_1D>::oc_hang_helper()",
                 OOMPH_EXCEPTION_LOCATION);
           }
           // Set node as master node
           master_node_number.push_back(neighbour_node_number);
           master_node_pt.push_back(neighbour_node_pt);
         }
       }
       // Storage for pointers to the local nodes and their numbers along my edge
       unsigned local_node_number = 0;
       Node* local_node_pt = 0;
       // Loop over the nodes along my edge
       for (unsigned i0 = 0; i0 < my_n_p; i0++)
       {
         for (unsigned i1 = 0; i1 < my_n_p; i1++)
         {
           // Storage for the fractional position of the node in the element
           Vector<double> s_fraction(3);
           const unsigned s0space = 1;
           const unsigned s1space = my_n_p;
           const unsigned s2space = my_n_p * my_n_p;
           // Find the local node and the fractional position of the node
           // which depends on the edge, of course
           switch (my_face)
           {
             case B:
               s_fraction[0] =
                 local_one_d_fraction_of_interpolating_node(i0, 0, value_id);
               s_fraction[1] =
                 local_one_d_fraction_of_interpolating_node(i1, 1, value_id);
               s_fraction[2] = 0.0;
               local_node_number = i0 * s0space + i1 * s1space;
               local_node_pt =
                 this->interpolating_node_pt(local_node_number, value_id);
               break;
             case F:
               s_fraction[0] =
                 local_one_d_fraction_of_interpolating_node(i0, 0, value_id);
               s_fraction[1] =
                 local_one_d_fraction_of_interpolating_node(i1, 1, value_id);
               s_fraction[2] = 1.0;
               local_node_number =
                 (my_n_p - 1) * s2space + i0 * s0space + i1 * s1space;
               local_node_pt =
                 this->interpolating_node_pt(local_node_number, value_id);
               break;
             case D:
               s_fraction[0] =
                 local_one_d_fraction_of_interpolating_node(i0, 0, value_id);
               s_fraction[1] = 0.0;
               s_fraction[2] =
                 local_one_d_fraction_of_interpolating_node(i1, 2, value_id);
               local_node_number = i0 * s0space + i1 * s2space;
               local_node_pt =
                 this->interpolating_node_pt(local_node_number, value_id);
               break;
             case U:
               s_fraction[0] =
                 local_one_d_fraction_of_interpolating_node(i0, 0, value_id);
               s_fraction[1] = 1.0;
               s_fraction[2] =
                 local_one_d_fraction_of_interpolating_node(i1, 2, value_id);
               local_node_number =
                 (my_n_p - 1) * s1space + i0 * s0space + i1 * s2space;
               local_node_pt =
                 this->interpolating_node_pt(local_node_number, value_id);
               break;
             case L:
               s_fraction[0] = 0.0;
               s_fraction[1] =
                 local_one_d_fraction_of_interpolating_node(i0, 1, value_id);
               s_fraction[2] =
                 local_one_d_fraction_of_interpolating_node(i1, 2, value_id);
               local_node_number = i0 * s1space + i1 * s2space;
               local_node_pt =
                 this->interpolating_node_pt(local_node_number, value_id);
               break;
             case R:
               s_fraction[0] = 1.0;
               s_fraction[1] =
                 local_one_d_fraction_of_interpolating_node(i0, 1, value_id);
               s_fraction[2] =
                 local_one_d_fraction_of_interpolating_node(i1, 2, value_id);
               local_node_number =
                 (my_n_p - 1) * s0space + i0 * s1space + i1 * s2space;
               local_node_pt =
                 this->interpolating_node_pt(local_node_number, value_id);
               break;
             default:
               throw OomphLibError(
                 "my_face not L, R, D, U, B, F\n",
                 "PRefineableQElement<3,INITIAL_NNODE_1D>::oc_hang_helper()",
                 OOMPH_EXCEPTION_LOCATION);
           }
           // Add node to vector of dependent element nodes
           dependent_node_number.push_back(local_node_number);
           dependent_node_pt.push_back(local_node_pt);
           // Store node's local fraction
           dependent_node_s_fraction.push_back(s_fraction);
         }
       }
       // Store the number of dependent and master nodes for use later
       const unsigned n_dependent_nodes = dependent_node_pt.size();
       const unsigned n_master_nodes = master_node_pt.size();
       const unsigned dependent_element_nnode_1d = my_n_p;
       const unsigned master_element_nnode_1d = neigh_n_p;
       // std::cout << "Dependent nodes on face: " <<
       // OcTree::Direct_string[my_face] << std::endl; for(unsigned i=0;
       // i<dependent_node_pt.size(); i++)
       // {
       //  std::cout << i << ": "
       //            << dependent_node_pt[i]->x(0) << "  "
       //            << dependent_node_pt[i]->x(1) << "  "
       //            << dependent_node_pt[i]->x(2) << "  "
       //            << std::endl;
       // }
       // std::cout << "Master nodes on face: " << OcTree::Direct_string[my_face]
       // << std::endl; for(unsigned i=0; i<master_node_pt.size(); i++)
       // {
       //  std::cout << i << ": "
       //            << master_node_pt[i]->x(0) << "  "
       //            << master_node_pt[i]->x(1) << "  "
       //            << master_node_pt[i]->x(2) << "  "
       //            << std::endl;
       // }
       // Storage for master shapes
       Shape master_shapes(neigh_obj_pt->ninterpolating_node(value_id));
       // Get master and dependent nodal positions
       //-------------------------------------
       // Get in 1D
       Vector<double> dependent_nodal_position_1d;
       Vector<double> dependent_weight_1d(dependent_element_nnode_1d);
       Orthpoly::gll_nodes(dependent_element_nnode_1d,
                           dependent_nodal_position_1d,
                           dependent_weight_1d);
       Vector<double> master_nodal_position_1d;
       Vector<double> master_weight_1d(master_element_nnode_1d);
       Orthpoly::gll_nodes(
         master_element_nnode_1d, master_nodal_position_1d, master_weight_1d);
       // Storage for 2D
       Vector<Vector<double>> dependent_nodal_position(
         dependent_element_nnode_1d * dependent_element_nnode_1d);
       for (unsigned i = 0; i < dependent_nodal_position.size(); i++)
       {
         dependent_nodal_position[i].resize(2);
       }
       Vector<double> dependent_weight(dependent_element_nnode_1d *
                                       dependent_element_nnode_1d);
       Vector<Vector<double>> master_nodal_position(master_element_nnode_1d *
                                                    master_element_nnode_1d);
       for (unsigned i = 0; i < master_nodal_position.size(); i++)
       {
         master_nodal_position[i].resize(2);
       }
       Vector<double> master_weight(master_element_nnode_1d *
                                    master_element_nnode_1d);
       // Fill in coordinates and weights in 2D
       unsigned dependent_index = 0;
       for (unsigned i = 0; i < dependent_element_nnode_1d; i++)
       {
         for (unsigned j = 0; j < dependent_element_nnode_1d; j++)
         {
           dependent_nodal_position[dependent_index][0] =
             dependent_nodal_position_1d[i];
           dependent_nodal_position[dependent_index][1] =
             dependent_nodal_position_1d[j];
           dependent_weight[dependent_index] =
             dependent_weight_1d[i] * dependent_weight_1d[j];
           dependent_index++;
         }
       }
       unsigned master_index = 0;
       for (unsigned i = 0; i < master_element_nnode_1d; i++)
       {
         for (unsigned j = 0; j < master_element_nnode_1d; j++)
         {
           master_nodal_position[master_index][0] = master_nodal_position_1d[i];
           master_nodal_position[master_index][1] = master_nodal_position_1d[j];
           master_weight[master_index] =
             master_weight_1d[i] * master_weight_1d[j];
           master_index++;
         }
       }
       // Apply the vertex matching condition
       //------------------------------------
       // Vertiex matching is ensured automatically in cases where there is a
       // node at each end of the mortar that is shared between the master and
       // dependent elements. Where this is not the case, the vertex matching
       // condition must be enforced by constraining the value of the unknown at
       // the node on the dependent side to be the same as the value at that
       // location in the master.
       // Store positions of the mortar vertex/non-vertex nodes in the dependent
       // element
       // const unsigned n_mortar_vertices = 4;
       // Vector<unsigned> vertex_pos(n_mortar_vertices);
       // vertex_pos[0] = 0;
       // vertex_pos[1] = my_n_p-1;
       // vertex_pos[2] = my_n_p*(my_n_p-1);
       // vertex_pos[3] = my_n_p*my_n_p-1;
       Vector<unsigned> non_vertex_pos((dependent_element_nnode_1d - 2) *
                                       (dependent_element_nnode_1d - 2));
       unsigned nvindex = 0;
       for (unsigned i = 1; i < dependent_element_nnode_1d - 1; i++)
       {
         for (unsigned j = 1; j < dependent_element_nnode_1d - 1; j++)
         {
           non_vertex_pos[nvindex++] = i * dependent_element_nnode_1d + j;
         }
       }
       Vector<unsigned> vertex_pos;
       for (unsigned i = 0; i < n_dependent_nodes; i++)
       {
         // Check if node number is in the non-vertex storage
         bool node_is_vertex = true;
         for (unsigned j = 0; j < non_vertex_pos.size(); j++)
         {
           if (i == non_vertex_pos[j])
           {
             // Node is not a vertex
             node_is_vertex = false;
             break;
           }
         }
         // If we get here and the node is a vertex then add it's index
         if (node_is_vertex)
         {
           vertex_pos.push_back(i);
         }
       }
       // Store number of mortar vertices
       const unsigned n_mortar_vertices = vertex_pos.size();
       // Check that there are actually dependent nodes for which we still need
       // to construct a hanging scheme. If not then there is nothing more to do.
       if (n_dependent_nodes - n_mortar_vertices > 0)
       {
         // Assemble mass matrix for mortar
         //--------------------------------
         Vector<double> psi(n_dependent_nodes - n_mortar_vertices);
         Vector<double> diag_M(n_dependent_nodes - n_mortar_vertices);
         Vector<Vector<double>> shared_node_M(n_mortar_vertices);
         for (unsigned i = 0; i < shared_node_M.size(); i++)
         {
           shared_node_M[i].resize(n_dependent_nodes - n_mortar_vertices);
         }
         // Fill in part corresponding to dependent nodal positions (unknown)
         for (unsigned i = 0; i < n_dependent_nodes - n_mortar_vertices; i++)
         {
           // Mortar test functions in 2D are just the cross product of the 1D
           // test functions Initialise to 1
           psi[i] = 1.0;
           // Take product in each direction
           for (unsigned dir = 0; dir < 2; dir++)
           {
             unsigned index1d =
               (dir == 0) ? i : i % (dependent_element_nnode_1d - 2);
             // Use L'Hosptal's rule:
             psi[i] *=
               pow(-1.0, int((dependent_element_nnode_1d - 1) - index1d - 1)) *
               -Orthpoly::ddlegendre(
                 dependent_element_nnode_1d - 1,
                 dependent_nodal_position[non_vertex_pos[i]][dir]);
           }
           // Put in contribution
           diag_M[i] = psi[i] * dependent_weight[non_vertex_pos[i]];
         }
         // std::cout << "diag(M):" << std::endl;
         // for(unsigned i=0; i<diag_M.size(); i++)
         // {
         //  std::cout << "  " << diag_M[i];
         // }
         // std::cout << std::endl;
         // Fill in part corresponding to dependent element vertices (known)
         for (unsigned v = 0; v < shared_node_M.size(); v++)
         {
           for (unsigned i = 0; i < n_dependent_nodes - n_mortar_vertices; i++)
           {
             // Mortar test functions in 2D are just the cross product of the 1D
             // test functions Initialise to 1
             psi[i] = 1.0;
             // Take product in each direction
             for (unsigned dir = 0; dir < 2; dir++)
             {
               unsigned index1d =
                 (dir == 0) ? i : i % (dependent_element_nnode_1d - 2);
               // Check if denominator is zero
               if (std::fabs(dependent_nodal_position[non_vertex_pos[i]][dir] -
                             dependent_nodal_position[vertex_pos[v]][dir]) >=
                   1.0e-8)
               {
                 // We're ok
                 psi[i] *=
                   pow(-1.0,
                       int((dependent_element_nnode_1d - 1) - index1d - 1)) *
                   Orthpoly::dlegendre(
                     dependent_element_nnode_1d - 1,
                     dependent_nodal_position[vertex_pos[v]][dir]) /
                   (dependent_nodal_position[non_vertex_pos[i]][dir] -
                    dependent_nodal_position[vertex_pos[v]][dir]);
               }
               // Check if numerator is zero
               else if (std::fabs(Orthpoly::dlegendre(
                          dependent_element_nnode_1d - 1,
                          dependent_nodal_position[vertex_pos[v]][dir])) <
                        1.0e-8)
               {
                 // We can use l'hopital's rule
                 psi[i] *=
                   pow(-1.0,
                       int((dependent_element_nnode_1d - 1) - index1d - 1)) *
                   -Orthpoly::ddlegendre(
                     dependent_element_nnode_1d - 1,
                     dependent_nodal_position[non_vertex_pos[i]][dir]);
               }
               else
               {
                 // We can't use l'hopital's rule
                 throw OomphLibError(
                   "Cannot use l'Hopital's rule. Dividing by zero is not "
                   "allowed!",
                   "PRefineableQElement<3,INITIAL_NNODE_1D>::quad_hang_helper()",
                   OOMPH_EXCEPTION_LOCATION);
               }
             }
             // Put in contribution
             shared_node_M[v][i] = psi[i] * dependent_weight[vertex_pos[v]];
           }
         }
         // std::cout << "shared node M:" << std::endl;
         // for(unsigned i=0; i<shared_node_M.size(); i++)
         // {
         //  for(unsigned j=0; j<shared_node_M[i].size(); j++)
         //   {
         //    std::cout << "  " << shared_node_M[i][j];
         //   }
         // }
         // std::cout << std::endl;
         // Assemble local projection matrix for mortar
         //--------------------------------------------
         // Have only one local projection matrix because there is just one
         // master
         Vector<Vector<double>> P(n_dependent_nodes - n_mortar_vertices);
         for (unsigned i = 0; i < P.size(); i++)
         {
           P[i].resize(n_master_nodes, 0.0);
         }
         // Storage for local coordinate
         Vector<double> s(3);
         // Sum contributions from master element shapes (quadrature).
         // The order of quadrature must be high enough to evaluate a polynomial
         // of order N_s + N_m - 3 exactly, where N_s = n_dependent_nodes, N_m =
         // n_master_nodes.
         // (Use pointers for the quadrature knots and weights so that
         // data is not unnecessarily copied)
         // unsigned quadrature_order =
         // std::max(dependent_element_nnode_1d,master_element_nnode_1d);
         Vector<Vector<double>>* quadrature_knot;
         Vector<double>* quadrature_weight;
         if (dependent_element_nnode_1d >= master_element_nnode_1d)
         {
           // Use the same quadrature order as the dependent element (me)
           quadrature_knot = &dependent_nodal_position;
           quadrature_weight = &dependent_weight;
         }
         else
         {
           // Use the same quadrature order as the master element (neighbour)
           quadrature_knot = &master_nodal_position;
           quadrature_weight = &master_weight;
         }
         // Quadrature loop
         for (unsigned q = 0; q < (*quadrature_weight).size(); q++)
         {
           // Evaluate mortar test functions at the quadrature knots in the
           // dependent
           Vector<double> s_on_mortar(2);
           for (unsigned i = 0; i < 2; i++)
           {
             s_on_mortar[i] = (*quadrature_knot)[q][i];
           }
           // Get psi
           for (unsigned k = 0; k < n_dependent_nodes - n_mortar_vertices; k++)
           {
             // Mortar test functions in 2D are just the cross product of the 1D
             // test functions Initialise to 1
             psi[k] = 1.0;
             // Take product in each direction
             for (unsigned dir = 0; dir < 2; dir++)
             {
               unsigned index1d =
                 (dir == 0) ? k : k % (dependent_element_nnode_1d - 2);
               // Check if denominator is zero
               if (std::fabs(dependent_nodal_position[non_vertex_pos[k]][dir] -
                             s_on_mortar[dir]) >= 1.0e-08)
               {
                 // We're ok
                 psi[k] *=
                   pow(-1.0,
                       int((dependent_element_nnode_1d - 1) - index1d - 1)) *
                   Orthpoly::dlegendre(dependent_element_nnode_1d - 1,
                                       s_on_mortar[dir]) /
                   (dependent_nodal_position[non_vertex_pos[k]][dir] -
                    s_on_mortar[dir]);
               }
               // Check if numerator is zero
               else if (std::fabs(Orthpoly::dlegendre(
                          dependent_element_nnode_1d - 1, s_on_mortar[dir])) <
                        1.0e-8)
               {
                 // We can use l'Hopital's rule
                 psi[k] *=
                   pow(-1.0,
                       int((dependent_element_nnode_1d - 1) - index1d - 1)) *
                   -Orthpoly::ddlegendre(dependent_element_nnode_1d - 1,
                                         s_on_mortar[dir]);
               }
               else
               {
                 // We can't use l'hopital's rule
                 throw OomphLibError(
                   "Cannot use l'Hopital's rule. Dividing by zero is not "
                   "allowed!",
                   "PRefineableQElement<3,INITIAL_NNODE_1D>::quad_hang_helper()",
                   OOMPH_EXCEPTION_LOCATION);
               }
             }
           }
           // Convert coordinate on mortar to local fraction in dependent element
           Vector<double> s_fraction(3);
           for (unsigned i = 0; i < 3; i++)
           {
             if (i == active_coord_index[0])
             {
               s_fraction[i] = 0.5 * (s_on_mortar[0] + 1.0);
             }
             else if (i == active_coord_index[1])
             {
               s_fraction[i] = 0.5 * (s_on_mortar[1] + 1.0);
             }
             else
             {
               s_fraction[i] = dependent_node_s_fraction[vertex_pos[0]][i];
             }
           }
           // Project active coordinate into master element
           Vector<double> s_in_neigh(3);
           for (unsigned i = 0; i < 3; i++)
           {
             s_in_neigh[i] = s_lo_neigh[i] + s_fraction[translate_s[i]] *
                                               (s_hi_neigh[i] - s_lo_neigh[i]);
           }
           // Evaluate master shapes at projections of local quadrature knots
           neigh_obj_pt->interpolating_basis(
             s_in_neigh, master_shapes, value_id);
           // Populate local projection matrix
           for (unsigned i = 0; i < n_dependent_nodes - n_mortar_vertices; i++)
           {
             for (unsigned j = 0; j < n_master_nodes; j++)
             {
               P[i][j] += master_shapes[master_node_number[j]] * psi[i] *
                          (*quadrature_weight)[q];
             }
           }
         }
         // std::cout << "P_e:" << std::endl;
         // for(unsigned i=0; i<P.size(); i++)
         // {
         //  for(unsigned j=0; j<P[i].size(); j++)
         //   {
         //    std::cout << "  " << P[i][j];
         //   }
         // }
         // std::cout << std::endl;
         // Assemble global projection matrices for mortar
         //-----------------------------------------------
         // Need to subtract contributions from the "known unknowns"
         // corresponding to the nodes at the vertices of the mortar
         // Assemble contributions from mortar vertex nodes
         for (unsigned v = 0; v < n_mortar_vertices; v++)
         {
           // Convert coordinate on mortar to local fraction in dependent element
           Vector<double> s_fraction(3);
           for (unsigned i = 0; i < 3; i++)
           {
             if (i == active_coord_index[0])
             {
               s_fraction[i] =
                 0.5 * (dependent_nodal_position[vertex_pos[v]][0] + 1.0);
             }
             else if (i == active_coord_index[1])
             {
               s_fraction[i] =
                 0.5 * (dependent_nodal_position[vertex_pos[v]][1] + 1.0);
             }
             else
             {
               s_fraction[i] = dependent_node_s_fraction[vertex_pos[0]][i];
             }
           }
           // Project active coordinate into master element
           Vector<double> s_in_neigh(3);
           for (unsigned i = 0; i < 3; i++)
           {
             s_in_neigh[i] = s_lo_neigh[i] + s_fraction[translate_s[i]] *
                                               (s_hi_neigh[i] - s_lo_neigh[i]);
           }
           // Get master shapes at dependent nodal positions
           neigh_obj_pt->interpolating_basis(
             s_in_neigh, master_shapes, value_id);
           for (unsigned i = 0; i < n_dependent_nodes - n_mortar_vertices; i++)
           {
             for (unsigned k = 0; k < n_master_nodes; k++)
             {
               P[i][k] -=
                 master_shapes[master_node_number[k]] * shared_node_M[v][i];
             }
           }
         }
         // std::cout << "P:" << std::endl;
         // for(unsigned i=0; i<P.size(); i++)
         // {
         //  for(unsigned j=0; j<P[i].size(); j++)
         //   {
         //    std::cout << "  " << P[i][j];
         //   }
         // }
         // std::cout << std::endl;
         // Solve mortar system
         //--------------------
         for (unsigned i = 0; i < n_dependent_nodes - n_mortar_vertices; i++)
         {
           for (unsigned j = 0; j < n_master_nodes; j++)
           {
             P[i][j] /= diag_M[i];
           }
         }
         // std::cout << "solved P:" << std::endl;
         // for(unsigned i=0; i<P.size(); i++)
         // {
         //  for(unsigned j=0; j<P[i].size(); j++)
         //   {
         //    std::cout << "  " << P[i][j];
         //   }
         // }
         // std::cout << std::endl;
         // Create structures to hold the hanging info
         //-------------------------------------------
         Vector<HangInfo*> hang_info_pt(n_dependent_nodes);
         for (unsigned i = 0; i < n_dependent_nodes - n_mortar_vertices; i++)
         {
           hang_info_pt[i] = new HangInfo(n_master_nodes);
         }
         // Copy information to hanging nodes
         //----------------------------------
         for (unsigned i = 0; i < n_dependent_nodes - n_mortar_vertices; i++)
         {
           for (unsigned j = 0; j < n_master_nodes; j++)
           {
             hang_info_pt[i]->set_master_node_pt(j, master_node_pt[j], P[i][j]);
           }
         }
         // Set pointers to hanging info
         //-----------------------------
         for (unsigned i = 0; i < n_dependent_nodes - n_mortar_vertices; i++)
         {
           // Check that the node shoule actually hang.
           // That is, if the polynomial orders of the elements at a p-type
           // non-conormity are both odd then the middle node on the edge is
           // shared but a hanging scheme has been constructed for it.
           bool node_is_really_shared = false;
           for (unsigned m = 0; m < hang_info_pt[i]->nmaster(); m++)
           {
             // We can simply check if the hanging scheme lists itself as a
             // master
             if (hang_info_pt[i]->master_node_pt(m) ==
                 dependent_node_pt[non_vertex_pos[i]])
             {
               node_is_really_shared = true;
 #ifdef PARANOID
               // Also check the corresponding weight: it should be 1
               if (std::fabs(hang_info_pt[i]->master_weight(m) - 1.0) > 1.0e-06)
               {
                 throw OomphLibError(
                   "Something fishy here -- with shared node at a mortar vertex",
                   "PRefineableQElement<3,INITIAL_NNODE_1D>::quad_hang_helper()",
                   OOMPH_EXCEPTION_LOCATION);
               }
 #endif
             }
           }
           // Now we can make the node hang, if it isn't a shared node
           if (!node_is_really_shared)
           {
             dependent_node_pt[non_vertex_pos[i]]->set_hanging_pt(
               hang_info_pt[i], -1);
           }
         }
       } // End of case where there are still dependent nodes
 #ifdef PARANOID
       // Check all dependent nodes, hanging or otherwise
       for (unsigned i = 0; i < n_dependent_nodes; i++)
       {
         // Check that weights sum to 1 for those that hang
         if (dependent_node_pt[i]->is_hanging())
         {
           // Check that weights sum to 1 and no zero weights
           double weight_sum = 0.0;
           bool zero_weight = false;
           for (unsigned m = 0;
                m < dependent_node_pt[i]->hanging_pt()->nmaster();
                m++)
           {
             weight_sum += dependent_node_pt[i]->hanging_pt()->master_weight(m);
             if (std::fabs(dependent_node_pt[i]->hanging_pt()->master_weight(
                   m)) < 1.0e-14)
             {
               zero_weight = true;
               oomph_info << "In the hanging scheme for dependent node " << i
                          << ", master node " << m << " has weight "
                          << dependent_node_pt[i]->hanging_pt()->master_weight(m)
                          << " < 1.0e-14" << std::endl;
             }
           }
           // Warn if not
           if (std::fabs(weight_sum - 1.0) > 1.0e-08)
           {
             oomph_info << "Sum of master weights: " << weight_sum << std::endl;
             OomphLibWarning(
               "Weights in hanging scheme do not sum to 1",
               "PRefineableQElement<3,INITIAL_NNODE_1D>::oc_hang_helper()",
               OOMPH_EXCEPTION_LOCATION);
           }
           if (zero_weight)
           {
             OomphLibWarning(
               "Zero weights present in hanging schemes",
               "PRefineableQElement<3,INITIAL_NNODE_1D>::oc_hang_helper()",
               OOMPH_EXCEPTION_LOCATION);
           }
           // Also check that dependent nodes do not have themselves as masters
           // bool dependent_should_not_be_hanging = false;
           for (unsigned m = 0;
                m < dependent_node_pt[i]->hanging_pt()->nmaster();
                m++)
           {
             if (dependent_node_pt[i] ==
                 dependent_node_pt[i]->hanging_pt()->master_node_pt(m))
             {
               // This shouldn't happen!
               throw OomphLibError(
                 "Dependent node has itself as a master!",
                 "PRefineableQElement<3,INITIAL_NNODE_1D>::oc_hang_helper()",
                 OOMPH_EXCEPTION_LOCATION);
             }
             if (dependent_node_pt[i]
                   ->hanging_pt()
                   ->master_node_pt(m)
                   ->is_hanging())
             {
               // Check if node is master of master
               Node* new_nod_pt =
                 dependent_node_pt[i]->hanging_pt()->master_node_pt(m);
               for (unsigned mm = 0; mm < new_nod_pt->hanging_pt()->nmaster();
                    mm++)
               {
                 if (dependent_node_pt[i] ==
                     new_nod_pt->hanging_pt()->master_node_pt(mm))
                 {
                   std::cout << "++++++++++++++++++++++++++++++++++++++++"
                             << std::endl;
                   std::cout
                     << "          Dependent node: " << dependent_node_pt[i]
                     << " = " << dependent_node_pt[i]->x(0) << " "
                     << dependent_node_pt[i]->x(1) << " "
                     << dependent_node_pt[i]->x(2) << " " << std::endl;
                   std::cout
                     << "         Master node: "
                     << dependent_node_pt[i]->hanging_pt()->master_node_pt(m)
                     << " = "
                     << dependent_node_pt[i]->hanging_pt()->master_node_pt(m)->x(
                          0)
                     << " "
                     << dependent_node_pt[i]->hanging_pt()->master_node_pt(m)->x(
                          1)
                     << " "
                     << dependent_node_pt[i]->hanging_pt()->master_node_pt(m)->x(
                          2)
                     << " " << std::endl;
                   std::cout << "Master's master node: "
                             << dependent_node_pt[i]
                                  ->hanging_pt()
                                  ->master_node_pt(m)
                                  ->hanging_pt()
                                  ->master_node_pt(mm)
                             << " = "
                             << dependent_node_pt[i]
                                  ->hanging_pt()
                                  ->master_node_pt(m)
                                  ->hanging_pt()
                                  ->master_node_pt(mm)
                                  ->x(0)
                             << " "
                             << dependent_node_pt[i]
                                  ->hanging_pt()
                                  ->master_node_pt(m)
                                  ->hanging_pt()
                                  ->master_node_pt(mm)
                                  ->x(1)
                             << " "
                             << dependent_node_pt[i]
                                  ->hanging_pt()
                                  ->master_node_pt(m)
                                  ->hanging_pt()
                                  ->master_node_pt(mm)
                                  ->x(2)
                             << " " << std::endl;
                   // Print out hanging scheme
                   std::cout << "Hanging node: " << dependent_node_pt[i]->x(0)
                             << "  " << dependent_node_pt[i]->x(1) << "  "
                             << dependent_node_pt[i]->x(2) << "  " << std::endl;
                   for (unsigned m_tmp = 0;
                        m_tmp < dependent_node_pt[i]->hanging_pt()->nmaster();
                        m_tmp++)
                   {
                     std::cout
                       << "   m = " << m_tmp << ": "
                       << dependent_node_pt[i]
                            ->hanging_pt()
                            ->master_node_pt(m_tmp)
                            ->x(0)
                       << "  "
                       << dependent_node_pt[i]
                            ->hanging_pt()
                            ->master_node_pt(m_tmp)
                            ->x(1)
                       << "  "
                       << dependent_node_pt[i]
                            ->hanging_pt()
                            ->master_node_pt(m_tmp)
                            ->x(2)
                       << "  "
                       << "w = "
                       << dependent_node_pt[i]->hanging_pt()->master_weight(
                            m_tmp)
                       << "  " << std::endl;
                   }
                   // Print out hanging scheme
                   std::cout << "Master node " << m
                             << " of Hanging node: " << new_nod_pt->x(0) << "  "
                             << new_nod_pt->x(1) << "  " << new_nod_pt->x(2)
                             << "  " << std::endl;
                   for (unsigned mm_tmp = 0;
                        mm_tmp < new_nod_pt->hanging_pt()->nmaster();
                        mm_tmp++)
                   {
                     std::cout
                       << "   mm = " << mm_tmp << ": "
                       << new_nod_pt->hanging_pt()->master_node_pt(mm_tmp)->x(0)
                       << "  "
                       << new_nod_pt->hanging_pt()->master_node_pt(mm_tmp)->x(1)
                       << "  "
                       << new_nod_pt->hanging_pt()->master_node_pt(mm_tmp)->x(2)
                       << "  "
                       << "w = "
                       << new_nod_pt->hanging_pt()->master_weight(mm_tmp) << "  "
                       << std::endl;
                   }
                   // This shouldn't happen!
                   throw OomphLibError(
                     "Dependent node has itself as a master of a master!",
                     "PRefineableQElement<3,INITIAL_NNODE_1D>::oc_hang_helper()",
                     OOMPH_EXCEPTION_LOCATION);
                 }
               }
             }
           }
         }
         else
         {
           // Check that this node is shared with the master element if it
           // isn't hanging
           bool is_master = false;
           for (unsigned n = 0; n < n_master_nodes; n++)
           {
             if (dependent_node_pt[i] == master_node_pt[n])
             {
               // Node is a master
               is_master = true;
               break;
             }
           }
           if (!is_master)
           {
             // std::ostringstream error_string;
             // error_string
             // << "This node in the dependent element is neither" << std::endl
             // << "hanging or shared with a master element." << std::endl;
             //
             // throw OomphLibError(
             //       error_string.str(),
             //       "PRefineableQElement<3,INITIAL_NNODE_1D>::quad_hang_helper()",
             //       OOMPH_EXCEPTION_LOCATION);
           }
         }
       }
 #endif
       // Finally, Loop over all dependent nodes and fine-tune their positions
       //-----------------------------------------------------------------
       // Here we simply set the node's positions to be consistent
       // with the hanging scheme. This is not strictly necessary
       // because it is done in the mesh adaptation before the node
       // becomes non-hanging later on. We make no attempt to ensure
       // (strong) continuity in the position across the mortar.
       for (unsigned i = 0; i < n_dependent_nodes; i++)
       {
         // Only fine-tune hanging nodes
         if (dependent_node_pt[i]->is_hanging())
         {
           // If we are doing the position, then
           if (value_id == -1)
           {
             // Get the local coordinate of this dependent node
             Vector<double> s_local(3);
             this->local_coordinate_of_node(dependent_node_number[i], s_local);
             // Get the position from interpolation in this element via
             // the hanging scheme
             Vector<double> x_in_neighb(3);
             this->interpolated_x(s_local, x_in_neighb);
             // Fine adjust the coordinates (macro map will pick up boundary
             // accurately but will lead to different element edges)
             dependent_node_pt[i]->x(0) = x_in_neighb[0];
             dependent_node_pt[i]->x(1) = x_in_neighb[1];
             dependent_node_pt[i]->x(2) = x_in_neighb[2];
           }
         }
       }
     } // End of case where this interface is to be mortared
   }
References D, oomph::OcTreeNames::DB, oomph::Orthpoly::ddlegendre(), oomph::OcTreeNames::DF, oomph::Orthpoly::dlegendre(), oomph::OcTreeNames::F, boost::multiprecision::fabs(), oomph::Orthpoly::gll_nodes(), oomph::OcTree::gteq_face_neighbour(), oomph::OcTree::gteq_true_edge_neighbour(), oomph::Node::hanging_pt(), i, oomph::RefineableElement::interpolating_basis(), oomph::RefineableElement::interpolating_node_pt(), j, k, L, oomph::OcTreeNames::LB, oomph::OcTreeNames::LD, oomph::OcTreeNames::LF, oomph::OcTreeNames::LU, m, oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), n, oomph::RefineableElement::ninterpolating_node(), oomph::RefineableElement::ninterpolating_node_1d(), oomph::HangInfo::nmaster(), oomph::Tree::nsons(), oomph::Tree::object_pt(), OOMPH_EXCEPTION_LOCATION, oomph::oomph_info, Global_Physical_Variables::P, Eigen::bfloat16_impl::pow(), Eigen::numext::q, R, oomph::OcTreeNames::RB, oomph::OcTreeNames::RD, oomph::OcTreeNames::RF, oomph::OcTreeNames::RU, s, oomph::HangInfo::set_master_node_pt(), RachelsAdvectionDiffusion::U, oomph::OcTreeNames::UB, oomph::OcTreeNames::UF, v, and oomph::Node::x().
p_refine()
template<unsigned INITIAL_NNODE_1D> void oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::p_refine (const int & inc, Mesh *const & mesh_pt, GeneralisedElement *const & clone_pt) virtual
p-refine the element (refine if inc>0, unrefine if inc<0).
p-refine the element inc times. (If inc<0 then p-unrefinement is performed.)
Implements oomph::PRefineableElement.
   {
     // Number of dimensions
     unsigned n_dim = 3;
     // Cast clone to correct type
     PRefineableQElement<3, INITIAL_NNODE_1D>* clone_el_pt =
       dynamic_cast<PRefineableQElement<3, INITIAL_NNODE_1D>*>(clone_pt);
     // Check if we can use it
     if (clone_el_pt == 0)
     {
       throw OomphLibError(
         "Cloned copy must be a PRefineableQElement<3,INITIAL_NNODE_1D>!",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
 #ifdef PARANOID
     // Clone exists, so check that it is infact a copy of me
     else
     {
       // Flag to keep track of check
       bool clone_is_ok = true;
       // Does the clone have the correct p-order?
       clone_is_ok = clone_is_ok && (clone_el_pt->p_order() == this->p_order());
       if (!clone_is_ok)
       {
         std::ostringstream err_stream;
         err_stream << "Clone element has a different p-order from me,"
                    << std::endl
                    << "but it is supposed to be a copy!" << std::endl;
         throw OomphLibError(
           err_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
       // Does the clone have the same number of nodes as me?
       clone_is_ok = clone_is_ok && (clone_el_pt->nnode() == this->nnode());
       if (!clone_is_ok)
       {
         std::ostringstream err_stream;
         err_stream << "Clone element has a different number of nodes from me,"
                    << std::endl
                    << "but it is supposed to be a copy!" << std::endl;
         throw OomphLibError(
           err_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
       // Does the clone have the same nodes as me?
       for (unsigned n = 0; n < this->nnode(); n++)
       {
         clone_is_ok =
           clone_is_ok && (clone_el_pt->node_pt(n) == this->node_pt(n));
       }
       if (!clone_is_ok)
       {
         std::ostringstream err_stream;
         err_stream << "The nodes belonging to the clone element are different"
                    << std::endl
                    << "from mine, but it is supposed to be a copy!"
                    << std::endl;
         throw OomphLibError(
           err_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
       // If we get to here then the clone has all the information we require
     }
 #endif
     // Currently we can't handle the case of generalised coordinates
     // since we haven't established how they should be interpolated.
     // Buffer this case:
     if (clone_el_pt->node_pt(0)->nposition_type() != 1)
     {
       throw OomphLibError("Can't handle generalised nodal positions (yet).",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
     // Timestepper should be the same for all nodes -- use it
     // to create timesteppers for new nodes
     TimeStepper* time_stepper_pt = this->node_pt(0)->time_stepper_pt();
     // Get number of history values (incl. present)
     unsigned ntstorage = time_stepper_pt->ntstorage();
     // Increment p-order of the element
     this->P_order += inc;
     // Change integration scheme
     delete this->integral_pt();
     switch (this->P_order)
     {
       case 2:
         this->set_integration_scheme(new GaussLobattoLegendre<3, 2>);
         break;
       case 3:
         this->set_integration_scheme(new GaussLobattoLegendre<3, 3>);
         break;
       case 4:
         this->set_integration_scheme(new GaussLobattoLegendre<3, 4>);
         break;
       case 5:
         this->set_integration_scheme(new GaussLobattoLegendre<3, 5>);
         break;
       case 6:
         this->set_integration_scheme(new GaussLobattoLegendre<3, 6>);
         break;
       case 7:
         this->set_integration_scheme(new GaussLobattoLegendre<3, 7>);
         break;
       default:
         std::ostringstream error_message;
         error_message << "\nERROR: Exceeded maximum polynomial order for";
         error_message << "\n       integration scheme.\n";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
     }
     // Allocate new space for Nodes (at the element level)
     this->set_n_node(this->P_order * this->P_order * this->P_order);
     // Copy vertex nodes and create new edge and internal nodes
     //---------------------------------------------------------
     // Setup vertex coordinates in element:
     //-------------------------------------
     Vector<double> s_lo(n_dim, 0.0);
     Vector<double> s_hi(n_dim, 0.0);
     s_lo[0] = -1.0;
     s_hi[0] = 1.0;
     s_lo[1] = -1.0;
     s_hi[1] = 1.0;
     s_lo[2] = -1.0;
     s_hi[2] = 1.0;
     // Local coordinate in element
     Vector<double> s(n_dim, 0.0);
     unsigned jnod = 0;
     Vector<double> s_fraction(n_dim, 0.0);
     // Loop over nodes in element
     for (unsigned i0 = 0; i0 < this->P_order; i0++)
     {
       // Get the fractional position of the node in the direction of s[0]
       s_fraction[0] = this->local_one_d_fraction_of_node(i0, 0);
       // Local coordinate
       s[0] = s_lo[0] + (s_hi[0] - s_lo[0]) * s_fraction[0];
       for (unsigned i1 = 0; i1 < this->P_order; i1++)
       {
         // Get the fractional position of the node in the direction of s[1]
         s_fraction[1] = this->local_one_d_fraction_of_node(i1, 1);
         // Local coordinate
         s[1] = s_lo[1] + (s_hi[1] - s_lo[1]) * s_fraction[1];
         for (unsigned i2 = 0; i2 < this->P_order; i2++)
         {
           // Get the fractional position of the node in the direction of s[2]
           s_fraction[2] = this->local_one_d_fraction_of_node(i2, 2);
           // Local coordinate
           s[2] = s_lo[2] + (s_hi[2] - s_lo[2]) * s_fraction[2];
           // Local node number
           jnod = i0 + this->P_order * i1 + this->P_order * this->P_order * i2;
           // Initialise flag: So far, this node hasn't been built
           // or copied yet
           bool node_done = false;
           // Get the pointer to the node in this element (or rather, its clone),
           // returns NULL if there is not node
           Node* created_node_pt = clone_el_pt->get_node_at_local_coordinate(s);
           // created_node_pt = 0;
           // Does this node already exist in this element?
           //----------------------------------------------
           if (created_node_pt != 0)
           {
             // Copy node across
             this->node_pt(jnod) = created_node_pt;
             // Make sure that we update the values at the node so that
             // they are consistent with the present representation.
             // This is only need for mixed interpolation where the value
             // at the father could now become active.
             // Loop over all history values
             for (unsigned t = 0; t < ntstorage; t++)
             {
               // Get values from father element
               // Note: get_interpolated_values() sets Vector size itself.
               Vector<double> prev_values;
               clone_el_pt->get_interpolated_values(t, s, prev_values);
               // Find the minimum number of values
               //(either those stored at the node, or those returned by
               // the function)
               unsigned n_val_at_node = created_node_pt->nvalue();
               unsigned n_val_from_function = prev_values.size();
               // Use the ternary conditional operator here
               unsigned n_var = n_val_at_node < n_val_from_function ?
                                  n_val_at_node :
                                  n_val_from_function;
               // Assign the values that we can
               for (unsigned k = 0; k < n_var; k++)
               {
                 created_node_pt->set_value(t, k, prev_values[k]);
               }
             }
             // Node has been created by copy
             node_done = true;
           }
           // Node does not exist in this element but might already
           //------------------------------------------------------
           // have been created by neighbouring elements
           //-------------------------------------------
           else
           {
             // Was the node created by one of its neighbours
             // Whether or not the node lies on an edge can be calculated
             // by from the fractional position
             bool is_periodic = false;
             created_node_pt =
               this->node_created_by_neighbour(s_fraction, is_periodic);
             // If the node was so created, assign the pointers
             if (created_node_pt != 0)
             {
               // If the node is periodic
               if (is_periodic)
               {
                 // Now the node must be on a boundary, but we don't know which
                 // one
                 // The returned created_node_pt is actually the neighbouring
                 // periodic node
                 Node* neighbour_node_pt = created_node_pt;
                 // Determine the edge on which the new node will live
                 //(cannot be a vertex node)
                 int my_bound = Tree::OMEGA;
                 // If we are on the left face
                 if (i0 == 0)
                 {
                   my_bound = OcTreeNames::L;
                 }
                 // If we are on the right face
                 else if (i0 == this->P_order - 1)
                 {
                   my_bound = OcTreeNames::R;
                 }
                 // If we are on the bottom face
                 if (i1 == 0)
                 {
                   // If we already have already set the boundary, we're on an
                   // edge
                   switch (my_bound)
                   {
                     case OcTreeNames::L:
                       my_bound = OcTreeNames::LD;
                       break;
                     case OcTreeNames::R:
                       my_bound = OcTreeNames::RD;
                       break;
                     // Boundary not set
                     default:
                       my_bound = OcTreeNames::D;
                       break;
                   }
                 }
                 // If we are the top face
                 else if (i1 == this->P_order - 1)
                 {
                   // If we already have a boundary
                   switch (my_bound)
                   {
                     case OcTreeNames::L:
                       my_bound = OcTreeNames::LU;
                       break;
                     case OcTreeNames::R:
                       my_bound = OcTreeNames::RU;
                       break;
                     default:
                       my_bound = OcTreeNames::U;
                       break;
                   }
                 }
                 // If we are on the back face
                 if (i2 == 0)
                 {
                   // If we already have already set the boundary, we're on an
                   // edge
                   switch (my_bound)
                   {
                     case OcTreeNames::L:
                       my_bound = OcTreeNames::LB;
                       break;
                     case OcTreeNames::LD:
                       my_bound = OcTreeNames::LDB;
                       break;
                     case OcTreeNames::LU:
                       my_bound = OcTreeNames::LUB;
                       break;
                     case OcTreeNames::R:
                       my_bound = OcTreeNames::RB;
                       break;
                     case OcTreeNames::RD:
                       my_bound = OcTreeNames::RDB;
                       break;
                     case OcTreeNames::RU:
                       my_bound = OcTreeNames::RUB;
                       break;
                     case OcTreeNames::D:
                       my_bound = OcTreeNames::DB;
                       break;
                     case OcTreeNames::U:
                       my_bound = OcTreeNames::UB;
                       break;
                     // Boundary not set
                     default:
                       my_bound = OcTreeNames::B;
                       break;
                   }
                 }
                 // If we are the front face
                 else if (i2 == this->P_order - 1)
                 {
                   // If we already have a boundary
                   switch (my_bound)
                   {
                     case OcTreeNames::L:
                       my_bound = OcTreeNames::LF;
                       break;
                     case OcTreeNames::LD:
                       my_bound = OcTreeNames::LDF;
                       break;
                     case OcTreeNames::LU:
                       my_bound = OcTreeNames::LUF;
                       break;
                     case OcTreeNames::R:
                       my_bound = OcTreeNames::RF;
                       break;
                     case OcTreeNames::RD:
                       my_bound = OcTreeNames::RDF;
                       break;
                     case OcTreeNames::RU:
                       my_bound = OcTreeNames::RUF;
                       break;
                     case OcTreeNames::D:
                       my_bound = OcTreeNames::DF;
                       break;
                     case OcTreeNames::U:
                       my_bound = OcTreeNames::UF;
                       break;
                     default:
                       my_bound = OcTreeNames::F;
                       break;
                   }
                 }
                 // Storage for the set of Mesh boundaries on which the
                 // appropriate edge lives.
                 // [New nodes should always be mid-edge nodes and therefore
                 // only live on one boundary but just to play it safe...]
                 std::set<unsigned> boundaries;
                 // Only get the boundaries if we are at the edge of
                 // an element. Nodes in the centre of an element cannot be
                 // on Mesh boundaries
                 if (my_bound != Tree::OMEGA)
                 {
                   clone_el_pt->get_boundaries(my_bound, boundaries);
                 }
 #ifdef PARANOID
                 // Case where a new node lives on more than one boundary
                 // seems fishy enough to flag
                 if (boundaries.size() > 2)
                 {
                   throw OomphLibError(
                     "boundaries.size()>2 seems a bit strange..\n",
                     OOMPH_CURRENT_FUNCTION,
                     OOMPH_EXCEPTION_LOCATION);
                 }
                 // Case when there are no boundaries, we are in big trouble
                 if (boundaries.size() == 0)
                 {
                   std::ostringstream error_stream;
                   error_stream << "Periodic node is not on a boundary...\n"
                                << "Coordinates: " << created_node_pt->x(0)
                                << " " << created_node_pt->x(1) << "\n";
                   throw OomphLibError(error_stream.str(),
                                       OOMPH_CURRENT_FUNCTION,
                                       OOMPH_EXCEPTION_LOCATION);
                 }
 #endif
                 // Create node and set the pointer to it from the element
                 created_node_pt =
                   this->construct_boundary_node(jnod, time_stepper_pt);
                 // Make the node periodic from the neighbour
                 created_node_pt->make_periodic(neighbour_node_pt);
                 // Loop over # of history values
                 for (unsigned t = 0; t < ntstorage; t++)
                 {
                   // Get position from father element -- this uses the macro
                   // element representation if appropriate. If the node
                   // turns out to be a hanging node later on, then
                   // its position gets adjusted in line with its
                   // hanging node interpolation.
                   Vector<double> x_prev(n_dim, 0.0);
                   clone_el_pt->get_x(t, s, x_prev);
                   // Set previous positions of the new node
                   for (unsigned i = 0; i < n_dim; i++)
                   {
                     created_node_pt->x(t, i) = x_prev[i];
                   }
                 }
                 // Check if we need to add nodes to the mesh
                 if (mesh_pt != 0)
                 {
                   // Next, we Update the boundary lookup schemes
                   // Loop over the boundaries stored in the set
                   for (std::set<unsigned>::iterator it = boundaries.begin();
                        it != boundaries.end();
                        ++it)
                   {
                     // Add the node to the boundary
                     mesh_pt->add_boundary_node(*it, created_node_pt);
                     // If we have set an intrinsic coordinate on this
                     // mesh boundary then it must also be interpolated on
                     // the new node
                     // Now interpolate the intrinsic boundary coordinate
                     if (mesh_pt->boundary_coordinate_exists(*it) == true)
                     {
                       Vector<double> zeta(2, 0.0);
                       clone_el_pt->interpolated_zeta_on_face(
                         *it, my_bound, s, zeta);
                       created_node_pt->set_coordinates_on_boundary(*it, zeta);
                     }
                   }
                   // Make sure that we add the node to the mesh
                   mesh_pt->add_node_pt(created_node_pt);
                 }
               } // End of periodic case
               // Otherwise the node is not periodic, so just set the
               // pointer to the neighbours node
               else
               {
                 this->node_pt(jnod) = created_node_pt;
               }
               // Node has been created
               node_done = true;
             }
             // Node does not exist in neighbour element but might already
             //-----------------------------------------------------------
             // have been created by a son of a neighbouring element
             //-----------------------------------------------------
             else
             {
               // Was the node created by one of its neighbours' sons
               // Whether or not the node lies on an edge can be calculated
               // by from the fractional position
               bool is_periodic = false;
               created_node_pt =
                 this->node_created_by_son_of_neighbour(s_fraction, is_periodic);
               // If the node was so created, assign the pointers
               if (created_node_pt != 0)
               {
                 // If the node is periodic
                 if (is_periodic)
                 {
                   // Now the node must be on a boundary, but we don't know which
                   // one
                   // The returned created_node_pt is actually the neighbouring
                   // periodic node
                   Node* neighbour_node_pt = created_node_pt;
                   // Determine the edge on which the new node will live
                   //(cannot be a vertex node)
                   int my_bound = Tree::OMEGA;
                   // If we are on the left face
                   if (i0 == 0)
                   {
                     my_bound = OcTreeNames::L;
                   }
                   // If we are on the right face
                   else if (i0 == this->P_order - 1)
                   {
                     my_bound = OcTreeNames::R;
                   }
                   // If we are on the bottom face
                   if (i1 == 0)
                   {
                     // If we already have already set the boundary, we're on an
                     // edge
                     switch (my_bound)
                     {
                       case OcTreeNames::L:
                         my_bound = OcTreeNames::LD;
                         break;
                       case OcTreeNames::R:
                         my_bound = OcTreeNames::RD;
                         break;
                       // Boundary not set
                       default:
                         my_bound = OcTreeNames::D;
                         break;
                     }
                   }
                   // If we are the top face
                   else if (i1 == this->P_order - 1)
                   {
                     // If we already have a boundary
                     switch (my_bound)
                     {
                       case OcTreeNames::L:
                         my_bound = OcTreeNames::LU;
                         break;
                       case OcTreeNames::R:
                         my_bound = OcTreeNames::RU;
                         break;
                       default:
                         my_bound = OcTreeNames::U;
                         break;
                     }
                   }
                   // If we are on the back face
                   if (i2 == 0)
                   {
                     // If we already have already set the boundary, we're on an
                     // edge
                     switch (my_bound)
                     {
                       case OcTreeNames::L:
                         my_bound = OcTreeNames::LB;
                         break;
                       case OcTreeNames::LD:
                         my_bound = OcTreeNames::LDB;
                         break;
                       case OcTreeNames::LU:
                         my_bound = OcTreeNames::LUB;
                         break;
                       case OcTreeNames::R:
                         my_bound = OcTreeNames::RB;
                         break;
                       case OcTreeNames::RD:
                         my_bound = OcTreeNames::RDB;
                         break;
                       case OcTreeNames::RU:
                         my_bound = OcTreeNames::RUB;
                         break;
                       case OcTreeNames::D:
                         my_bound = OcTreeNames::DB;
                         break;
                       case OcTreeNames::U:
                         my_bound = OcTreeNames::UB;
                         break;
                       // Boundary not set
                       default:
                         my_bound = OcTreeNames::B;
                         break;
                     }
                   }
                   // If we are the front face
                   else if (i2 == this->P_order - 1)
                   {
                     // If we already have a boundary
                     switch (my_bound)
                     {
                       case OcTreeNames::L:
                         my_bound = OcTreeNames::LF;
                         break;
                       case OcTreeNames::LD:
                         my_bound = OcTreeNames::LDF;
                         break;
                       case OcTreeNames::LU:
                         my_bound = OcTreeNames::LUF;
                         break;
                       case OcTreeNames::R:
                         my_bound = OcTreeNames::RF;
                         break;
                       case OcTreeNames::RD:
                         my_bound = OcTreeNames::RDF;
                         break;
                       case OcTreeNames::RU:
                         my_bound = OcTreeNames::RUF;
                         break;
                       case OcTreeNames::D:
                         my_bound = OcTreeNames::DF;
                         break;
                       case OcTreeNames::U:
                         my_bound = OcTreeNames::UF;
                         break;
                       default:
                         my_bound = OcTreeNames::F;
                         break;
                     }
                   }
                   // Storage for the set of Mesh boundaries on which the
                   // appropriate edge lives.
                   // [New nodes should always be mid-edge nodes and therefore
                   // only live on one boundary but just to play it safe...]
                   std::set<unsigned> boundaries;
                   // Only get the boundaries if we are at the edge of
                   // an element. Nodes in the centre of an element cannot be
                   // on Mesh boundaries
                   if (my_bound != Tree::OMEGA)
                   {
                     clone_el_pt->get_boundaries(my_bound, boundaries);
                   }
 #ifdef PARANOID
                   // Case where a new node lives on more than one boundary
                   // seems fishy enough to flag
                   if (boundaries.size() > 2)
                   {
                     throw OomphLibError(
                       "boundaries.size()>2 seems a bit strange..\n",
                       OOMPH_CURRENT_FUNCTION,
                       OOMPH_EXCEPTION_LOCATION);
                   }
                   // Case when there are no boundaries, we are in big trouble
                   if (boundaries.size() == 0)
                   {
                     std::ostringstream error_stream;
                     error_stream << "Periodic node is not on a boundary...\n"
                                  << "Coordinates: " << created_node_pt->x(0)
                                  << " " << created_node_pt->x(1) << "\n";
                     throw OomphLibError(error_stream.str(),
                                         OOMPH_CURRENT_FUNCTION,
                                         OOMPH_EXCEPTION_LOCATION);
                   }
 #endif
                   // Create node and set the pointer to it from the element
                   created_node_pt =
                     this->construct_boundary_node(jnod, time_stepper_pt);
                   // Make the node periodic from the neighbour
                   created_node_pt->make_periodic(neighbour_node_pt);
                   // Loop over # of history values
                   for (unsigned t = 0; t < ntstorage; t++)
                   {
                     // Get position from father element -- this uses the macro
                     // element representation if appropriate. If the node
                     // turns out to be a hanging node later on, then
                     // its position gets adjusted in line with its
                     // hanging node interpolation.
                     Vector<double> x_prev(n_dim);
                     clone_el_pt->get_x(t, s, x_prev);
                     // Set previous positions of the new node
                     for (unsigned i = 0; i < n_dim; i++)
                     {
                       created_node_pt->x(t, i) = x_prev[i];
                     }
                   }
                   // Check if we need to add nodes to the mesh
                   if (mesh_pt != 0)
                   {
                     // Next, we Update the boundary lookup schemes
                     // Loop over the boundaries stored in the set
                     for (std::set<unsigned>::iterator it = boundaries.begin();
                          it != boundaries.end();
                          ++it)
                     {
                       // Add the node to the boundary
                       mesh_pt->add_boundary_node(*it, created_node_pt);
                       // If we have set an intrinsic coordinate on this
                       // mesh boundary then it must also be interpolated on
                       // the new node
                       // Now interpolate the intrinsic boundary coordinate
                       if (mesh_pt->boundary_coordinate_exists(*it) == true)
                       {
                         Vector<double> zeta(2, 0.0);
                         clone_el_pt->interpolated_zeta_on_face(
                           *it, my_bound, s, zeta);
                         created_node_pt->set_coordinates_on_boundary(*it, zeta);
                       }
                     }
                     // Make sure that we add the node to the mesh
                     mesh_pt->add_node_pt(created_node_pt);
                   }
                 } // End of periodic case
                 // Otherwise the node is not periodic, so just set the
                 // pointer to the neighbours node
                 else
                 {
                   this->node_pt(jnod) = created_node_pt;
                 }
                 // Node has been created
                 node_done = true;
               } // Node does not exist in son of neighbouring element
             } // Node does not exist in neighbouring element
           } // Node does not exist in this element
           // Node has not been built anywhere ---> build it here
           if (!node_done)
           {
             // Firstly, we need to determine whether or not a node lies
             // on the boundary before building it, because
             // we actually assign a different type of node on boundaries.
             // Initially none
             int my_bound = Tree::OMEGA;
             // If we are on the left face
             if (i0 == 0)
             {
               my_bound = OcTreeNames::L;
             }
             // If we are on the right face
             else if (i0 == this->P_order - 1)
             {
               my_bound = OcTreeNames::R;
             }
             // If we are on the bottom face
             if (i1 == 0)
             {
               // If we already have already set the boundary, we're on an edge
               switch (my_bound)
               {
                 case OcTreeNames::L:
                   my_bound = OcTreeNames::LD;
                   break;
                 case OcTreeNames::R:
                   my_bound = OcTreeNames::RD;
                   break;
                 // Boundary not set
                 default:
                   my_bound = OcTreeNames::D;
                   break;
               }
             }
             // If we are the top face
             else if (i1 == this->P_order - 1)
             {
               // If we already have a boundary
               switch (my_bound)
               {
                 case OcTreeNames::L:
                   my_bound = OcTreeNames::LU;
                   break;
                 case OcTreeNames::R:
                   my_bound = OcTreeNames::RU;
                   break;
                 default:
                   my_bound = OcTreeNames::U;
                   break;
               }
             }
             // If we are on the back face
             if (i2 == 0)
             {
               // If we already have already set the boundary, we're on an edge
               switch (my_bound)
               {
                 case OcTreeNames::L:
                   my_bound = OcTreeNames::LB;
                   break;
                 case OcTreeNames::LD:
                   my_bound = OcTreeNames::LDB;
                   break;
                 case OcTreeNames::LU:
                   my_bound = OcTreeNames::LUB;
                   break;
                 case OcTreeNames::R:
                   my_bound = OcTreeNames::RB;
                   break;
                 case OcTreeNames::RD:
                   my_bound = OcTreeNames::RDB;
                   break;
                 case OcTreeNames::RU:
                   my_bound = OcTreeNames::RUB;
                   break;
                 case OcTreeNames::D:
                   my_bound = OcTreeNames::DB;
                   break;
                 case OcTreeNames::U:
                   my_bound = OcTreeNames::UB;
                   break;
                 // Boundary not set
                 default:
                   my_bound = OcTreeNames::B;
                   break;
               }
             }
             // If we are the front face
             else if (i2 == this->P_order - 1)
             {
               // If we already have a boundary
               switch (my_bound)
               {
                 case OcTreeNames::L:
                   my_bound = OcTreeNames::LF;
                   break;
                 case OcTreeNames::LD:
                   my_bound = OcTreeNames::LDF;
                   break;
                 case OcTreeNames::LU:
                   my_bound = OcTreeNames::LUF;
                   break;
                 case OcTreeNames::R:
                   my_bound = OcTreeNames::RF;
                   break;
                 case OcTreeNames::RD:
                   my_bound = OcTreeNames::RDF;
                   break;
                 case OcTreeNames::RU:
                   my_bound = OcTreeNames::RUF;
                   break;
                 case OcTreeNames::D:
                   my_bound = OcTreeNames::DF;
                   break;
                 case OcTreeNames::U:
                   my_bound = OcTreeNames::UF;
                   break;
                 default:
                   my_bound = OcTreeNames::F;
                   break;
               }
             }
             // Storage for the set of Mesh boundaries on which the
             // appropriate edge lives.
             // [New nodes should always be mid-edge nodes and therefore
             // only live on one boundary but just to play it safe...]
             std::set<unsigned> boundaries;
             // Only get the boundaries if we are at the edge of
             // an element. Nodes in the centre of an element cannot be
             // on Mesh boundaries
             if (my_bound != Tree::OMEGA)
               clone_el_pt->get_boundaries(my_bound, boundaries);
 #ifdef PARANOID
             // Case where a new node lives on more than two boundaries
             // seems fishy enough to flag
             if (boundaries.size() > 2)
             {
               throw OomphLibError(
                 "boundaries.size()>2 seems a bit strange..\n",
                 "PRefineableQElement<3,INITIAL_NNODE_1D>::p_refine()",
                 OOMPH_EXCEPTION_LOCATION);
             }
 #endif
             // If the node lives on a mesh boundary,
             // then we need to create a boundary node
             if (boundaries.size() > 0)
             {
               // Create node and set the pointer to it from the element
               created_node_pt =
                 this->construct_boundary_node(jnod, time_stepper_pt);
               // Now we need to work out whether to pin the values at
               // the new node based on the boundary conditions applied at
               // its Mesh boundary
               // Get the boundary conditions from the father
               Vector<int> bound_cons(this->ncont_interpolated_values());
               clone_el_pt->get_bcs(my_bound, bound_cons);
               // Loop over the values and pin, if necessary
               unsigned n_value = created_node_pt->nvalue();
               for (unsigned k = 0; k < n_value; k++)
               {
                 if (bound_cons[k])
                 {
                   created_node_pt->pin(k);
                 }
               }
               // Solid node? If so, deal with the positional boundary
               // conditions:
               SolidNode* solid_node_pt =
                 dynamic_cast<SolidNode*>(created_node_pt);
               if (solid_node_pt != 0)
               {
                 // Get the positional boundary conditions from the father:
                 unsigned n_dim = created_node_pt->ndim();
                 Vector<int> solid_bound_cons(n_dim);
                 RefineableSolidQElement<3>* clone_solid_el_pt =
                   dynamic_cast<RefineableSolidQElement<3>*>(clone_el_pt);
 #ifdef PARANOID
                 if (clone_solid_el_pt == 0)
                 {
                   std::string error_message =
                     "We have a SolidNode outside a refineable SolidElement\n";
                   error_message +=
                     "during mesh refinement -- this doesn't make sense";
                   throw OomphLibError(
                     error_message,
                     "PRefineableQElement<3,INITIAL_NNODE_1D>::p_refine()",
                     OOMPH_EXCEPTION_LOCATION);
                 }
 #endif
                 clone_solid_el_pt->get_solid_bcs(my_bound, solid_bound_cons);
                 // Loop over the positions and pin, if necessary
                 for (unsigned k = 0; k < n_dim; k++)
                 {
                   if (solid_bound_cons[k])
                   {
                     solid_node_pt->pin_position(k);
                   }
                 }
               } // End of if solid_node_pt
               // Next, we Update the boundary lookup schemes
               // Check if we need to add nodes to the mesh
               if (mesh_pt != 0)
               {
                 // Loop over the boundaries stored in the set
                 for (std::set<unsigned>::iterator it = boundaries.begin();
                      it != boundaries.end();
                      ++it)
                 {
                   // Add the node to the boundary
                   mesh_pt->add_boundary_node(*it, created_node_pt);
                   // If we have set an intrinsic coordinate on this
                   // mesh boundary then it must also be interpolated on
                   // the new node
                   // Now interpolate the intrinsic boundary coordinate
                   if (mesh_pt->boundary_coordinate_exists(*it) == true)
                   {
                     Vector<double> zeta(2);
                     clone_el_pt->interpolated_zeta_on_face(
                       *it, my_bound, s, zeta);
                     created_node_pt->set_coordinates_on_boundary(*it, zeta);
                   }
                 }
               }
             }
             // Otherwise the node is not on a Mesh boundary and
             // we create a normal "bulk" node
             else
             {
               // Create node and set the pointer to it from the element
               created_node_pt = this->construct_node(jnod, time_stepper_pt);
             }
             // Now we set the position and values at the newly created node
             // In the first instance use macro element or FE representation
             // to create past and present nodal positions.
             // (THIS STEP SHOULD NOT BE SKIPPED FOR ALGEBRAIC
             // ELEMENTS AS NOT ALL OF THEM NECESSARILY IMPLEMENT
             // NONTRIVIAL NODE UPDATE FUNCTIONS. CALLING
             // THE NODE UPDATE FOR SUCH ELEMENTS/NODES WILL LEAVE
             // THEIR NODAL POSITIONS WHERE THEY WERE (THIS IS APPROPRIATE
             // ONCE THEY HAVE BEEN GIVEN POSITIONS) BUT WILL
             // NOT ASSIGN SENSIBLE INITIAL POSITONS!
             // Loop over # of history values
             for (unsigned t = 0; t < ntstorage; t++)
             {
               // Get position from father element -- this uses the macro
               // element representation if appropriate. If the node
               // turns out to be a hanging node later on, then
               // its position gets adjusted in line with its
               // hanging node interpolation.
               Vector<double> x_prev(3);
               clone_el_pt->get_x(t, s, x_prev);
               // Set previous positions of the new node
               for (unsigned i = 0; i < 3; i++)
               {
                 created_node_pt->x(t, i) = x_prev[i];
               }
             }
             // Loop over all history values
             for (unsigned t = 0; t < ntstorage; t++)
             {
               // Get values from father element
               // Note: get_interpolated_values() sets Vector size itself.
               Vector<double> prev_values;
               clone_el_pt->get_interpolated_values(t, s, prev_values);
               // Initialise the values at the new node
               unsigned n_value = created_node_pt->nvalue();
               for (unsigned k = 0; k < n_value; k++)
               {
                 created_node_pt->set_value(t, k, prev_values[k]);
               }
             }
             // Add new node to mesh (if requested)
             if (mesh_pt != 0)
             {
               mesh_pt->add_node_pt(created_node_pt);
             }
             AlgebraicElementBase* alg_el_pt =
               dynamic_cast<AlgebraicElementBase*>(this);
             // If we do have an algebraic element
             if (alg_el_pt != 0)
             {
               std::string error_message =
                 "Have not implemented p-refinement for";
               error_message += "Algebraic p-refineable elements yet\n";
               throw OomphLibError(
                 error_message,
                 "PRefineableQElement<3,INITIAL_NNODE_1D>::p_refine()",
                 OOMPH_EXCEPTION_LOCATION);
             }
           } // End of case when we build the node ourselves
           // Check if the element is an algebraic element
           AlgebraicElementBase* alg_el_pt =
             dynamic_cast<AlgebraicElementBase*>(this);
           // If the element is an algebraic element, setup
           // node position (past and present) from algebraic node update
           // function. This over-writes previous assingments that
           // were made based on the macro-element/FE representation.
           // NOTE: YES, THIS NEEDS TO BE CALLED REPEATEDLY IF THE
           // NODE IS MEMBER OF MULTIPLE ELEMENTS: THEY ALL ASSIGN
           // THE SAME NODAL POSITIONS BUT WE NEED TO ADD THE REMESH
           // INFO FOR *ALL* ROOT ELEMENTS!
           if (alg_el_pt != 0)
           {
             // Build algebraic node update info for new node
             // This sets up the node update data for all node update
             // functions that are shared by all nodes in the father
             // element
             alg_el_pt->setup_algebraic_node_update(
               this->node_pt(jnod), s, clone_el_pt);
           }
         } // End of vertical loop over nodes in element (i2)
       } // End of horizontal loop over nodes in element (i1)
     } // End of horizontal loop over nodes in element (i0)
     // Loop over all nodes in element again, to re-set the positions
     // This must be done using the new element's macro-element
     // representation, rather than the old version which may be
     // of a different p-order!
     for (unsigned i0 = 0; i0 < this->P_order; i0++)
     {
       // Get the fractional position of the node in the direction of s[0]
       s_fraction[0] = this->local_one_d_fraction_of_node(i0, 0);
       // Local coordinate
       s[0] = s_lo[0] + (s_hi[0] - s_lo[0]) * s_fraction[0];
       for (unsigned i1 = 0; i1 < this->P_order; i1++)
       {
         // Get the fractional position of the node in the direction of s[1]
         s_fraction[1] = this->local_one_d_fraction_of_node(i1, 1);
         // Local coordinate
         s[1] = s_lo[1] + (s_hi[1] - s_lo[1]) * s_fraction[1];
         for (unsigned i2 = 0; i2 < this->P_order; i2++)
         {
           // Get the fractional position of the node in the direction of s[2]
           s_fraction[2] = this->local_one_d_fraction_of_node(i2, 2);
           // Local coordinate
           s[2] = s_lo[2] + (s_hi[2] - s_lo[2]) * s_fraction[2];
           // Local node number
           jnod = i0 + this->P_order * i1 + this->P_order * this->P_order * i2;
           // Loop over # of history values
           for (unsigned t = 0; t < ntstorage; t++)
           {
             // Get position from father element -- this uses the macro
             // element representation if appropriate. If the node
             // turns out to be a hanging node later on, then
             // its position gets adjusted in line with its
             // hanging node interpolation.
             Vector<double> x_prev(3);
             this->get_x(t, s, x_prev);
             // Set previous positions of the new node
             for (unsigned i = 0; i < 3; i++)
             {
               this->node_pt(jnod)->x(t, i) = x_prev[i];
             }
           }
         }
       }
     }
     // If the element is a MacroElementNodeUpdateElement, set
     // the update parameters for the current element's nodes --
     // all this needs is the vector of (pointers to the)
     // geometric objects that affect the MacroElement-based
     // node update -- this needs to be done to set the node
     // update info for newly created nodes
     MacroElementNodeUpdateElementBase* clone_m_el_pt =
       dynamic_cast<MacroElementNodeUpdateElementBase*>(clone_el_pt);
     if (clone_m_el_pt != 0)
     {
       // Get vector of geometric objects from father (construct vector
       // via copy operation)
       Vector<GeomObject*> geom_object_pt(clone_m_el_pt->geom_object_pt());
       // Cast current element to MacroElementNodeUpdateElement:
       MacroElementNodeUpdateElementBase* m_el_pt =
         dynamic_cast<MacroElementNodeUpdateElementBase*>(this);
 #ifdef PARANOID
       if (m_el_pt == 0)
       {
         std::string error_message =
           "Failed to cast to MacroElementNodeUpdateElementBase*\n";
         error_message +=
           "Strange -- if my clone is a MacroElementNodeUpdateElement\n";
         error_message += "then I should be too....\n";
         throw OomphLibError(
           error_message,
           "PRefineableQElement<3,INITIAL_NNODE_1D>::p_refine()",
           OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // Build update info by passing vector of geometric objects:
       // This sets the current element to be the update element
       // for all of the element's nodes -- this is reversed
       // if the element is ever un-refined in the father element's
       // rebuild_from_sons() function which overwrites this
       // assignment to avoid nasty segmentation faults that occur
       // when a node tries to update itself via an element that no
       // longer exists...
       m_el_pt->set_node_update_info(geom_object_pt);
     }
     // Not necessary to delete the old nodes since all original nodes are in the
     // current mesh and so will be pruned as part of the mesh adaption process.
     // Do any further-build required
     this->further_build();
   }
References oomph::Mesh::add_boundary_node(), oomph::Mesh::add_node_pt(), oomph::OcTreeNames::B, oomph::Mesh::boundary_coordinate_exists(), oomph::OcTreeNames::D, oomph::OcTreeNames::DB, oomph::OcTreeNames::DF, oomph::OcTreeNames::F, oomph::MacroElementNodeUpdateElementBase::geom_object_pt(), oomph::RefineableQElement< 3 >::get_bcs(), oomph::RefineableQElement< 3 >::get_boundaries(), oomph::RefineableElement::get_interpolated_values(), get_node_at_local_coordinate(), oomph::RefineableSolidQElement< 3 >::get_solid_bcs(), oomph::FiniteElement::get_x(), i, oomph::RefineableQElement< 3 >::interpolated_zeta_on_face(), k, oomph::OcTreeNames::L, oomph::OcTreeNames::LB, oomph::OcTreeNames::LD, oomph::OcTreeNames::LDB, oomph::OcTreeNames::LDF, oomph::OcTreeNames::LF, oomph::OcTreeNames::LU, oomph::OcTreeNames::LUB, oomph::OcTreeNames::LUF, oomph::Node::make_periodic(), n, oomph::Node::ndim(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::Node::nposition_type(), oomph::TimeStepper::ntstorage(), oomph::Data::nvalue(), oomph::Tree::OMEGA, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::PRefineableElement::p_order(), oomph::Data::pin(), oomph::SolidNode::pin_position(), oomph::OcTreeNames::R, oomph::OcTreeNames::RB, oomph::OcTreeNames::RD, oomph::OcTreeNames::RDB, oomph::OcTreeNames::RDF, oomph::OcTreeNames::RF, oomph::OcTreeNames::RU, oomph::OcTreeNames::RUB, oomph::OcTreeNames::RUF, s, oomph::Node::set_coordinates_on_boundary(), oomph::MacroElementNodeUpdateElementBase::set_node_update_info(), oomph::Data::set_value(), oomph::AlgebraicElementBase::setup_algebraic_node_update(), oomph::Global_string_for_annotation::string(), plotPSD::t, oomph::OcTreeNames::U, oomph::OcTreeNames::UB, oomph::OcTreeNames::UF, oomph::Node::x(), and Eigen::zeta().
pre_build()
template<unsigned INITIAL_NNODE_1D> void oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::pre_build (Mesh *& mesh_pt, Vector< Node * > & new_node_pt) virtual
Pre-build (search father for required nodes which may already exist)
Check the father element for any required nodes which already exist
/ Pass pointer to time object:
/ Pass macro element pointer on to sons and / set coordinates in macro element / hierher why can I see this?
Reimplemented from oomph::RefineableElement.
   {
     using namespace OcTreeNames;
     // Get the number of 1d nodes
     unsigned n_p = nnode_1d();
     // Check whether static father_bound needs to be created
     if (Father_bound[n_p].nrow() == 0)
     {
       setup_father_bounds();
     }
     // Pointer to my father (in quadtree impersonation)
     OcTree* father_pt = dynamic_cast<OcTree*>(octree_pt()->father_pt());
     // What type of son am I? Ask my quadtree representation...
     int son_type = Tree_pt->son_type();
     // Has somebody build me already? (If any nodes have not been built)
     if (!nodes_built())
     {
 #ifdef PARANOID
       if (father_pt == 0)
       {
         std::string error_message =
           "Something fishy here: I have no father and yet \n";
         error_message += "I have no nodes. Who has created me then?!\n";
         throw OomphLibError(
           error_message,
           "PRefineableQElement<3,INITIAL_NNODE_1D>::pre_build()",
           OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // Return pointer to father element
       RefineableQElement<3>* father_el_pt =
         dynamic_cast<RefineableQElement<3>*>(father_pt->object_pt());
       // Timestepper should be the same for all nodes in father
       // element -- use it create timesteppers for new nodes
       TimeStepper* time_stepper_pt =
         father_el_pt->node_pt(0)->time_stepper_pt();
       // Number of history values (incl. present)
       unsigned ntstorage = time_stepper_pt->ntstorage();
       // this->time_pt()=father_el_pt->time_pt();
       Vector<double> s_lo(3);
       Vector<double> s_hi(3);
       Vector<double> s(3);
       Vector<double> x(3);
       // Setup vertex coordinates in father element:
       //--------------------------------------------
       switch (son_type)
       {
         case LDB:
           s_lo[0] = -1.0;
           s_hi[0] = 0.0;
           s_lo[1] = -1.0;
           s_hi[1] = 0.0;
           s_lo[2] = -1.0;
           s_hi[2] = 0.0;
           break;
         case LDF:
           s_lo[0] = -1.0;
           s_hi[0] = 0.0;
           s_lo[1] = -1.0;
           s_hi[1] = 0.0;
           s_lo[2] = 0.0;
           s_hi[2] = 1.0;
           break;
         case LUB:
           s_lo[0] = -1.0;
           s_hi[0] = 0.0;
           s_lo[1] = 0.0;
           s_hi[1] = 1.0;
           s_lo[2] = -1.0;
           s_hi[2] = 0.0;
           break;
         case LUF:
           s_lo[0] = -1.0;
           s_hi[0] = 0.0;
           s_lo[1] = 0.0;
           s_hi[1] = 1.0;
           s_lo[2] = 0.0;
           s_hi[2] = 1.0;
           break;
         case RDB:
           s_lo[0] = 0.0;
           s_hi[0] = 1.0;
           s_lo[1] = -1.0;
           s_hi[1] = 0.0;
           s_lo[2] = -1.0;
           s_hi[2] = 0.0;
           break;
         case RDF:
           s_lo[0] = 0.0;
           s_hi[0] = 1.0;
           s_lo[1] = -1.0;
           s_hi[1] = 0.0;
           s_lo[2] = 0.0;
           s_hi[2] = 1.0;
           break;
         case RUB:
           s_lo[0] = 0.0;
           s_hi[0] = 1.0;
           s_lo[1] = 0.0;
           s_hi[1] = 1.0;
           s_lo[2] = -1.0;
           s_hi[2] = 0.0;
           break;
         case RUF:
           s_lo[0] = 0.0;
           s_hi[0] = 1.0;
           s_lo[1] = 0.0;
           s_hi[1] = 1.0;
           s_lo[2] = 0.0;
           s_hi[2] = 1.0;
           break;
       }
       // if(father_el_pt->macro_elem_pt()!=0)
       // {
       //  set_macro_elem_pt(father_el_pt->macro_elem_pt());
       //  for(unsigned i=0;i<2;i++)
       //   {
       //    s_macro_ll(i)=      father_el_pt->s_macro_ll(i)+
       //     0.5*(s_lo[i]+1.0)*(father_el_pt->s_macro_ur(i)-
       //                        father_el_pt->s_macro_ll(i));
       //    s_macro_ur(i)=      father_el_pt->s_macro_ll(i)+
       //     0.5*(s_hi[i]+1.0)*(father_el_pt->s_macro_ur(i)-
       //                        father_el_pt->s_macro_ll(i));
       //   }
       // }
       // If the father element hasn't been generated yet, we're stuck...
       if (father_el_pt->node_pt(0) == 0)
       {
         throw OomphLibError(
           "Trouble: father_el_pt->node_pt(0)==0\n Can't build son element!\n",
           "PRefineableQElement<3,INITIAL_NNODE_1D>::pre_build()",
           OOMPH_EXCEPTION_LOCATION);
       }
       else
       {
         unsigned jnod = 0;
         Vector<double> s_fraction(3);
         // Loop over nodes in element
         for (unsigned i0 = 0; i0 < n_p; i0++)
         {
           // Get the fractional position of the node in the direction of s[0]
           s_fraction[0] = this->local_one_d_fraction_of_node(i0, 0);
           // Local coordinate in father element
           s[0] = s_lo[0] + (s_hi[0] - s_lo[0]) * s_fraction[0];
           for (unsigned i1 = 0; i1 < n_p; i1++)
           {
             // Get the fractional position of the node in the direction of s[1]
             s_fraction[1] = this->local_one_d_fraction_of_node(i1, 1);
             // Local coordinate in father element
             s[1] = s_lo[1] + (s_hi[1] - s_lo[1]) * s_fraction[1];
             for (unsigned i2 = 0; i2 < n_p; i2++)
             {
               // Get the fractional position of the node in the direction of
               // s[2]
               s_fraction[2] = this->local_one_d_fraction_of_node(i2, 2);
               // Local coordinate in father element
               s[2] = s_lo[2] + (s_hi[2] - s_lo[2]) * s_fraction[2];
               // Local node number
               jnod = i0 + n_p * i1 + n_p * n_p * i2;
               // Get the pointer to the node in the father, returns NULL
               // if there is not node
               Node* created_node_pt =
                 father_el_pt->get_node_at_local_coordinate(s);
               // Does this node already exist in father element?
               //------------------------------------------------
               if (created_node_pt != 0)
               {
                 // Copy node across
                 this->node_pt(jnod) = created_node_pt;
                 // Make sure that we update the values at the node so that
                 // they are consistent with the present representation.
                 // This is only need for mixed interpolation where the value
                 // at the father could now become active.
                 // Loop over all history values
                 for (unsigned t = 0; t < ntstorage; t++)
                 {
                   // Get values from father element
                   // Note: get_interpolated_values() sets Vector size itself.
                   Vector<double> prev_values;
                   father_el_pt->get_interpolated_values(t, s, prev_values);
                   // Find the minimum number of values
                   //(either those stored at the node, or those returned by
                   // the function)
                   unsigned n_val_at_node = created_node_pt->nvalue();
                   unsigned n_val_from_function = prev_values.size();
                   // Use the ternary conditional operator here
                   unsigned n_var = n_val_at_node < n_val_from_function ?
                                      n_val_at_node :
                                      n_val_from_function;
                   // Assign the values that we can
                   for (unsigned k = 0; k < n_var; k++)
                   {
                     created_node_pt->set_value(t, k, prev_values[k]);
                   }
                 }
               }
             } // End of loop i2
           } // End of loop i1
         } // End of loop i0
       } // Sanity check: Father element has been generated
     } // End of nodes not built
   }
References oomph::RefineableElement::get_interpolated_values(), oomph::FiniteElement::get_node_at_local_coordinate(), k, oomph::OcTreeNames::LDB, oomph::OcTreeNames::LDF, oomph::OcTreeNames::LUB, oomph::OcTreeNames::LUF, oomph::FiniteElement::node_pt(), oomph::Data::nvalue(), oomph::Tree::object_pt(), OOMPH_EXCEPTION_LOCATION, oomph::OcTreeNames::RDB, oomph::OcTreeNames::RDF, oomph::OcTreeNames::RUB, oomph::OcTreeNames::RUF, s, oomph::Data::set_value(), oomph::Tree::son_type(), oomph::Global_string_for_annotation::string(), plotPSD::t, oomph::Data::time_stepper_pt(), and plotDoE::x.
rebuild_from_sons()
template<unsigned INITIAL_NNODE_1D> void oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::rebuild_from_sons (Mesh *& mesh_pt) virtual
Rebuild the element. This needs to find any nodes in the sons which are still required.
Rebuild the element from nodes found in its sons Adjusts its p-order to be the maximum of its sons' p-orders
Implements oomph::RefineableElement.
   {
     // Get p-orders of sons
     unsigned n_sons = this->tree_pt()->nsons();
     Vector<unsigned> son_p_order(n_sons);
     unsigned max_son_p_order = 0;
     for (unsigned ison = 0; ison < n_sons; ison++)
     {
       PRefineableElement* el_pt = dynamic_cast<PRefineableElement*>(
         this->tree_pt()->son_pt(ison)->object_pt());
       son_p_order[ison] = el_pt->p_order();
       if (son_p_order[ison] > max_son_p_order)
         max_son_p_order = son_p_order[ison];
     }
     unsigned old_Nnode = this->nnode();
     unsigned old_P_order = this->p_order();
     // Set p-order of the element
     this->p_order() = max_son_p_order;
     // Change integration scheme
     delete this->integral_pt();
     switch (this->p_order())
     {
       case 2:
         this->set_integration_scheme(new GaussLobattoLegendre<3, 2>);
         break;
       case 3:
         this->set_integration_scheme(new GaussLobattoLegendre<3, 3>);
         break;
       case 4:
         this->set_integration_scheme(new GaussLobattoLegendre<3, 4>);
         break;
       case 5:
         this->set_integration_scheme(new GaussLobattoLegendre<3, 5>);
         break;
       case 6:
         this->set_integration_scheme(new GaussLobattoLegendre<3, 6>);
         break;
       case 7:
         this->set_integration_scheme(new GaussLobattoLegendre<3, 7>);
         break;
       default:
         std::ostringstream error_message;
         error_message << "\nERROR: Exceeded maximum polynomial order for";
         error_message << "\n       integration scheme.\n";
         throw OomphLibError(
           error_message.str(),
           "PRefineableQElement<3,INITIAL_NNODE_1D>::rebuild_from_sons()",
           OOMPH_EXCEPTION_LOCATION);
     }
     // Back up pointers to old nodes before they are lost
     Vector<Node*> old_node_pt(old_Nnode);
     for (unsigned n = 0; n < old_Nnode; n++)
     {
       old_node_pt[n] = this->node_pt(n);
     }
     // Allocate new space for Nodes (at the element level)
     this->set_n_node(this->p_order() * this->p_order() * this->p_order());
     // Copy vertex nodes which were populated in the pre-build
     this->node_pt(0) = old_node_pt[0];
     this->node_pt(this->p_order() - 1) = old_node_pt[old_P_order - 1];
     this->node_pt(this->p_order() * (this->p_order() - 1)) =
       old_node_pt[(old_P_order) * (old_P_order - 1)];
     this->node_pt(this->p_order() * this->p_order() - 1) =
       old_node_pt[(old_P_order) * (old_P_order)-1];
     this->node_pt(this->p_order() * this->p_order() * (this->p_order() - 1)) =
       old_node_pt[old_P_order * old_P_order * (old_P_order - 1)];
     this->node_pt((this->p_order() * this->p_order() + 1) *
                   (this->p_order() - 1)) =
       old_node_pt[(old_P_order * old_P_order + 1) * (old_P_order - 1)];
     this->node_pt(this->p_order() * (this->p_order() + 1) *
                   (this->p_order() - 1)) =
       old_node_pt[old_P_order * (old_P_order + 1) * (old_P_order - 1)];
     this->node_pt(this->p_order() * this->p_order() * this->p_order() - 1) =
       old_node_pt[old_P_order * old_P_order * old_P_order - 1];
     // Copy midpoint nodes from sons if new p-order is odd
     if (this->p_order() % 2 == 1)
     {
       // Work out which is midpoint node
       unsigned n_p = this->p_order();
       unsigned m = (n_p - 1) / 2;
       unsigned s0space = m;
       unsigned s1space = m * n_p;
       unsigned s2space = m * n_p * n_p;
       // Back face
       // DB edge
       this->node_pt(1 * s0space + 0 * s1space + 0 * s2space) =
         dynamic_cast<RefineableQElement<3>*>(
           octree_pt()->son_pt(OcTreeNames::RDB)->object_pt())
           ->vertex_node_pt(0);
       // LB edge
       this->node_pt(0 * s0space + 1 * s1space + 0 * s2space) =
         dynamic_cast<RefineableQElement<3>*>(
           octree_pt()->son_pt(OcTreeNames::LUB)->object_pt())
           ->vertex_node_pt(0);
       // B centre
       this->node_pt(1 * s0space + 1 * s1space + 0 * s2space) =
         dynamic_cast<RefineableQElement<3>*>(
           octree_pt()->son_pt(OcTreeNames::RUB)->object_pt())
           ->vertex_node_pt(0);
       // RB edge
       this->node_pt(2 * s0space + 1 * s1space + 0 * s2space) =
         dynamic_cast<RefineableQElement<3>*>(
           octree_pt()->son_pt(OcTreeNames::RUB)->object_pt())
           ->vertex_node_pt(1);
       // UB edge
       this->node_pt(1 * s0space + 2 * s1space + 0 * s2space) =
         dynamic_cast<RefineableQElement<3>*>(
           octree_pt()->son_pt(OcTreeNames::RUB)->object_pt())
           ->vertex_node_pt(2);
       // Mid-way between between back and front faces
       // LD edge
       this->node_pt(0 * s0space + 0 * s1space + 1 * s2space) =
         dynamic_cast<RefineableQElement<3>*>(
           octree_pt()->son_pt(OcTreeNames::LDF)->object_pt())
           ->vertex_node_pt(0);
       // D centre
       this->node_pt(1 * s0space + 0 * s1space + 1 * s2space) =
         dynamic_cast<RefineableQElement<3>*>(
           octree_pt()->son_pt(OcTreeNames::LDF)->object_pt())
           ->vertex_node_pt(1);
       // RD edge
       this->node_pt(2 * s0space + 0 * s1space + 1 * s2space) =
         dynamic_cast<RefineableQElement<3>*>(
           octree_pt()->son_pt(OcTreeNames::RDF)->object_pt())
           ->vertex_node_pt(1);
       // L centre
       this->node_pt(0 * s0space + 1 * s1space + 1 * s2space) =
         dynamic_cast<RefineableQElement<3>*>(
           octree_pt()->son_pt(OcTreeNames::LUF)->object_pt())
           ->vertex_node_pt(0);
       // Centre
       this->node_pt(1 * s0space + 1 * s1space + 1 * s2space) =
         dynamic_cast<RefineableQElement<3>*>(
           octree_pt()->son_pt(OcTreeNames::RUF)->object_pt())
           ->vertex_node_pt(0);
       // R centre
       this->node_pt(2 * s0space + 1 * s1space + 1 * s2space) =
         dynamic_cast<RefineableQElement<3>*>(
           octree_pt()->son_pt(OcTreeNames::RUF)->object_pt())
           ->vertex_node_pt(1);
       // LU edge
       this->node_pt(0 * s0space + 2 * s1space + 1 * s2space) =
         dynamic_cast<RefineableQElement<3>*>(
           octree_pt()->son_pt(OcTreeNames::LUF)->object_pt())
           ->vertex_node_pt(2);
       // U center
       this->node_pt(1 * s0space + 2 * s1space + 1 * s2space) =
         dynamic_cast<RefineableQElement<3>*>(
           octree_pt()->son_pt(OcTreeNames::RUF)->object_pt())
           ->vertex_node_pt(2);
       // RU edge
       this->node_pt(2 * s0space + 2 * s1space + 1 * s2space) =
         dynamic_cast<RefineableQElement<3>*>(
           octree_pt()->son_pt(OcTreeNames::RUF)->object_pt())
           ->vertex_node_pt(3);
       // Front face
       // DF edge
       this->node_pt(1 * s0space + 0 * s1space + 2 * s2space) =
         dynamic_cast<RefineableQElement<3>*>(
           octree_pt()->son_pt(OcTreeNames::LDF)->object_pt())
           ->vertex_node_pt(5);
       // LF edge
       this->node_pt(0 * s0space + 1 * s1space + 2 * s2space) =
         dynamic_cast<RefineableQElement<3>*>(
           octree_pt()->son_pt(OcTreeNames::LUF)->object_pt())
           ->vertex_node_pt(4);
       // F centre
       this->node_pt(1 * s0space + 1 * s1space + 2 * s2space) =
         dynamic_cast<RefineableQElement<3>*>(
           octree_pt()->son_pt(OcTreeNames::RUF)->object_pt())
           ->vertex_node_pt(4);
       // RF edge
       this->node_pt(2 * s0space + 1 * s1space + 2 * s2space) =
         dynamic_cast<RefineableQElement<3>*>(
           octree_pt()->son_pt(OcTreeNames::RUF)->object_pt())
           ->vertex_node_pt(5);
       // UF edge
       this->node_pt(1 * s0space + 2 * s1space + 2 * s2space) =
         dynamic_cast<RefineableQElement<3>*>(
           octree_pt()->son_pt(OcTreeNames::RUF)->object_pt())
           ->vertex_node_pt(6);
     }
     // The timestepper should be the same for all nodes and node 0 should
     // never be deleted.
     if (this->node_pt(0) == 0)
     {
       throw OomphLibError(
         "The Corner node (0) does not exist",
         "PRefineableQElement<3,INITIAL_NNODE_1D>::rebuild_from_sons()",
         OOMPH_EXCEPTION_LOCATION);
     }
     TimeStepper* time_stepper_pt = this->node_pt(0)->time_stepper_pt();
     unsigned ntstorage = time_stepper_pt->ntstorage();
     unsigned jnod = 0;
     Vector<double> s_fraction(3), s(3);
     // Loop over the nodes in the element
     unsigned n_p = this->nnode_1d();
     for (unsigned i0 = 0; i0 < n_p; i0++)
     {
       // Get the fractional position of the node
       s_fraction[0] = this->local_one_d_fraction_of_node(i0, 0);
       // Local coordinate
       s[0] = -1.0 + 2.0 * s_fraction[0];
       for (unsigned i1 = 0; i1 < n_p; i1++)
       {
         // Get the fractional position of the node in the direction of s[1]
         s_fraction[1] = this->local_one_d_fraction_of_node(i1, 1);
         // Local coordinate in father element
         s[1] = -1.0 + 2.0 * s_fraction[1];
         for (unsigned i2 = 0; i2 < n_p; i2++)
         {
           // Get the fractional position of the node in the direction of s[2]
           s_fraction[2] = this->local_one_d_fraction_of_node(i2, 2);
           // Local coordinate in father element
           s[2] = -1.0 + 2.0 * s_fraction[2];
           // Set the local node number
           jnod = i0 + n_p * i1 + n_p * n_p * i2;
           // Initialise flag: So far, this node hasn't been built
           // or copied yet
           bool node_done = false;
           // Get the pointer to the node in this element, returns NULL
           // if there is not node
           Node* created_node_pt = this->get_node_at_local_coordinate(s);
           // Does this node already exist in this element?
           //----------------------------------------------
           if (created_node_pt != 0)
           {
             // Copy node across
             this->node_pt(jnod) = created_node_pt;
             // Node has been created by copy
             node_done = true;
           }
           // Node does not exist in this element but might already
           //------------------------------------------------------
           // have been created by neighbouring elements
           //-------------------------------------------
           else
           {
             // Was the node created by one of its neighbours
             // Whether or not the node lies on an edge can be calculated
             // by from the fractional position
             bool is_periodic = false;
             created_node_pt =
               node_created_by_neighbour(s_fraction, is_periodic);
             // If the node was so created, assign the pointers
             if (created_node_pt != 0)
             {
               // If the node is periodic
               if (is_periodic)
               {
                 throw OomphLibError("Cannot handle periodic nodes yet",
                                     OOMPH_CURRENT_FUNCTION,
                                     OOMPH_EXCEPTION_LOCATION);
               }
               // Non-periodic case, just set the pointer
               else
               {
                 this->node_pt(jnod) = created_node_pt;
               }
               // Node has been created
               node_done = true;
             }
           } // Node does not exist in this element
           // Node has not been built anywhere ---> build it here
           if (!node_done)
           {
             // First, find the son element in which the node should live
             // Find coordinates in the sons
             Vector<double> s_in_son(3);
             // using namespace OcTreeNames;
             int son = -10;
             // On the left
             if (s_fraction[0] < 0.5)
             {
               // On the bottom
               if (s_fraction[1] < 0.5)
               {
                 // On the back
                 if (s_fraction[2] < 0.5)
                 {
                   // It's the LDB son
                   son = OcTreeNames::LDB;
                   s_in_son[0] = -1.0 + 4.0 * s_fraction[0];
                   s_in_son[1] = -1.0 + 4.0 * s_fraction[1];
                   s_in_son[2] = -1.0 + 4.0 * s_fraction[2];
                 }
                 // On the front
                 else
                 {
                   // It's the LDF son
                   son = OcTreeNames::LDF;
                   s_in_son[0] = -1.0 + 4.0 * s_fraction[0];
                   s_in_son[1] = -1.0 + 4.0 * s_fraction[1];
                   s_in_son[2] = -1.0 + 4.0 * (s_fraction[2] - 0.5);
                 }
               }
               // On the top
               else
               {
                 // On the back
                 if (s[2] < 0.0)
                 {
                   // It's the LUB son
                   son = OcTreeNames::LUB;
                   s_in_son[0] = -1.0 + 4.0 * s_fraction[0];
                   s_in_son[1] = -1.0 + 4.0 * (s_fraction[1] - 0.5);
                   s_in_son[2] = -1.0 + 4.0 * s_fraction[2];
                 }
                 // On the front
                 else
                 {
                   // It's the LUF son
                   son = OcTreeNames::LUF;
                   s_in_son[0] = -1.0 + 4.0 * s_fraction[0];
                   s_in_son[1] = -1.0 + 4.0 * (s_fraction[1] - 0.5);
                   s_in_son[2] = -1.0 + 4.0 * (s_fraction[2] - 0.5);
                 }
               }
             }
             // On the right
             else
             {
               // On the bottom
               if (s[1] < 0.0)
               {
                 // On the back
                 if (s[2] < 0.0)
                 {
                   // It's the RDB son
                   son = OcTreeNames::RDB;
                   s_in_son[0] = -1.0 + 4.0 * (s_fraction[0] - 0.5);
                   s_in_son[1] = -1.0 + 4.0 * s_fraction[1];
                   s_in_son[2] = -1.0 + 4.0 * s_fraction[2];
                 }
                 // On the front
                 else
                 {
                   // It's the RDF son
                   son = OcTreeNames::RDF;
                   s_in_son[0] = -1.0 + 4.0 * (s_fraction[0] - 0.5);
                   s_in_son[1] = -1.0 + 4.0 * s_fraction[1];
                   s_in_son[2] = -1.0 + 4.0 * (s_fraction[2] - 0.5);
                 }
               }
               // On the top
               else
               {
                 // On the back
                 if (s[2] < 0.0)
                 {
                   // It's the RUB son
                   son = OcTreeNames::RUB;
                   s_in_son[0] = -1.0 + 4.0 * (s_fraction[0] - 0.5);
                   s_in_son[1] = -1.0 + 4.0 * (s_fraction[1] - 0.5);
                   s_in_son[2] = -1.0 + 4.0 * s_fraction[2];
                 }
                 // On the front
                 else
                 {
                   // It's the RUF son
                   son = OcTreeNames::RUF;
                   s_in_son[0] = -1.0 + 4.0 * (s_fraction[0] - 0.5);
                   s_in_son[1] = -1.0 + 4.0 * (s_fraction[1] - 0.5);
                   s_in_son[2] = -1.0 + 4.0 * (s_fraction[2] - 0.5);
                 }
               }
             }
             // Get the pointer to the son element in which the new node
             // would live
             PRefineableQElement<3, INITIAL_NNODE_1D>* son_el_pt =
               dynamic_cast<PRefineableQElement<3, INITIAL_NNODE_1D>*>(
                 this->tree_pt()->son_pt(son)->object_pt());
             // If we are rebuilding, then worry about the boundary conditions
             // Find the boundary of the node
             // Initially none
             int boundary = Tree::OMEGA;
             // If we are on the left face
             if (i0 == 0)
             {
               boundary = OcTreeNames::L;
             }
             // If we are on the right face
             else if (i0 == n_p - 1)
             {
               boundary = OcTreeNames::R;
             }
             // If we are on the bottom face
             if (i1 == 0)
             {
               // If we already have already set the boundary, we're on an edge
               switch (boundary)
               {
                 case OcTreeNames::L:
                   boundary = OcTreeNames::LD;
                   break;
                 case OcTreeNames::R:
                   boundary = OcTreeNames::RD;
                   break;
                 // Boundary not set
                 default:
                   boundary = OcTreeNames::D;
                   break;
               }
             }
             // If we are the top face
             else if (i1 == n_p - 1)
             {
               // If we already have a boundary
               switch (boundary)
               {
                 case OcTreeNames::L:
                   boundary = OcTreeNames::LU;
                   break;
                 case OcTreeNames::R:
                   boundary = OcTreeNames::RU;
                   break;
                 default:
                   boundary = OcTreeNames::U;
                   break;
               }
             }
             // If we are on the back face
             if (i2 == 0)
             {
               // If we already have already set the boundary, we're on an edge
               switch (boundary)
               {
                 case OcTreeNames::L:
                   boundary = OcTreeNames::LB;
                   break;
                 case OcTreeNames::LD:
                   boundary = OcTreeNames::LDB;
                   break;
                 case OcTreeNames::LU:
                   boundary = OcTreeNames::LUB;
                   break;
                 case OcTreeNames::R:
                   boundary = OcTreeNames::RB;
                   break;
                 case OcTreeNames::RD:
                   boundary = OcTreeNames::RDB;
                   break;
                 case OcTreeNames::RU:
                   boundary = OcTreeNames::RUB;
                   break;
                 case OcTreeNames::D:
                   boundary = OcTreeNames::DB;
                   break;
                 case OcTreeNames::U:
                   boundary = OcTreeNames::UB;
                   break;
                 // Boundary not set
                 default:
                   boundary = OcTreeNames::B;
                   break;
               }
             }
             // If we are the front face
             else if (i2 == n_p - 1)
             {
               // If we already have a boundary
               switch (boundary)
               {
                 case OcTreeNames::L:
                   boundary = OcTreeNames::LF;
                   break;
                 case OcTreeNames::LD:
                   boundary = OcTreeNames::LDF;
                   break;
                 case OcTreeNames::LU:
                   boundary = OcTreeNames::LUF;
                   break;
                 case OcTreeNames::R:
                   boundary = OcTreeNames::RF;
                   break;
                 case OcTreeNames::RD:
                   boundary = OcTreeNames::RDF;
                   break;
                 case OcTreeNames::RU:
                   boundary = OcTreeNames::RUF;
                   break;
                 case OcTreeNames::D:
                   boundary = OcTreeNames::DF;
                   break;
                 case OcTreeNames::U:
                   boundary = OcTreeNames::UF;
                   break;
                 default:
                   boundary = OcTreeNames::F;
                   break;
               }
             }
             // set of boundaries that this edge in the son lives on
             std::set<unsigned> boundaries;
             // Now get the boundary conditions from the son
             // The boundaries will be common to the son because there can be
             // no rotations here
             if (boundary != Tree::OMEGA)
             {
               son_el_pt->get_boundaries(boundary, boundaries);
             }
             // If the node lives on a boundary:
             // Construct a boundary node,
             // Get boundary conditions and
             // update all lookup schemes
             if (boundaries.size() > 0)
             {
               // Construct the new node
               created_node_pt =
                 this->construct_boundary_node(jnod, time_stepper_pt);
               // Get the boundary conditions from the son
               Vector<int> bound_cons(this->ncont_interpolated_values());
               son_el_pt->get_bcs(boundary, bound_cons);
               // Loop over the values and pin if necessary
               unsigned nval = created_node_pt->nvalue();
               for (unsigned k = 0; k < nval; k++)
               {
                 if (bound_cons[k])
                 {
                   created_node_pt->pin(k);
                 }
               }
               // Solid node? If so, deal with the positional boundary
               // conditions:
               SolidNode* solid_node_pt =
                 dynamic_cast<SolidNode*>(created_node_pt);
               if (solid_node_pt != 0)
               {
                 // Get the positional boundary conditions from the father:
                 unsigned n_dim = created_node_pt->ndim();
                 Vector<int> solid_bound_cons(n_dim);
                 RefineableSolidQElement<3>* son_solid_el_pt =
                   dynamic_cast<RefineableSolidQElement<3>*>(son_el_pt);
 #ifdef PARANOID
                 if (son_solid_el_pt == 0)
                 {
                   std::string error_message =
                     "We have a SolidNode outside a refineable SolidElement\n";
                   error_message +=
                     "during mesh refinement -- this doesn't make sense\n";
                   throw OomphLibError(error_message,
                                       "PRefineableQElement<3,INITIAL_NNODE_1D>:"
                                       ":rebuild_from_sons()",
                                       OOMPH_EXCEPTION_LOCATION);
                 }
 #endif
                 son_solid_el_pt->get_solid_bcs(boundary, solid_bound_cons);
                 // Loop over the positions and pin, if necessary
                 for (unsigned k = 0; k < n_dim; k++)
                 {
                   if (solid_bound_cons[k])
                   {
                     solid_node_pt->pin_position(k);
                   }
                 }
               } // End of if solid_node_pt
               // Next we update the boundary look-up schemes
               // Loop over the boundaries stored in the set
               for (std::set<unsigned>::iterator it = boundaries.begin();
                    it != boundaries.end();
                    ++it)
               {
                 // Add the node to the boundary
                 mesh_pt->add_boundary_node(*it, created_node_pt);
                 // If we have set an intrinsic coordinate on this
                 // mesh boundary then it must also be interpolated on
                 // the new node
                 // Now interpolate the intrinsic boundary coordinate
                 if (mesh_pt->boundary_coordinate_exists(*it) == true)
                 {
                   Vector<double> zeta(2);
                   son_el_pt->interpolated_zeta_on_face(
                     *it, boundary, s_in_son, zeta);
                   created_node_pt->set_coordinates_on_boundary(*it, zeta);
                 }
               }
             }
             // Otherwise the node is not on a Mesh boundary
             // and we create a normal "bulk" node
             else
             {
               // Construct the new node
               created_node_pt = this->construct_node(jnod, time_stepper_pt);
             }
             // Now we set the position and values at the newly created node
             // In the first instance use macro element or FE representation
             // to create past and present nodal positions.
             // (THIS STEP SHOULD NOT BE SKIPPED FOR ALGEBRAIC
             // ELEMENTS AS NOT ALL OF THEM NECESSARILY IMPLEMENT
             // NONTRIVIAL NODE UPDATE FUNCTIONS. CALLING
             // THE NODE UPDATE FOR SUCH ELEMENTS/NODES WILL LEAVE
             // THEIR NODAL POSITIONS WHERE THEY WERE (THIS IS APPROPRIATE
             // ONCE THEY HAVE BEEN GIVEN POSITIONS) BUT WILL
             // NOT ASSIGN SENSIBLE INITIAL POSITONS!
             // Loop over # of history values
             // Loop over # of history values
             for (unsigned t = 0; t < ntstorage; t++)
             {
               using namespace QuadTreeNames;
               // Get the position from the son
               Vector<double> x_prev(3);
               // Now let's fill in the value
               son_el_pt->get_x(t, s_in_son, x_prev);
               for (unsigned i = 0; i < 3; i++)
               {
                 created_node_pt->x(t, i) = x_prev[i];
               }
             }
             // Now set up the values
             // Loop over all history values
             for (unsigned t = 0; t < ntstorage; t++)
             {
               // Get values from father element
               // Note: get_interpolated_values() sets Vector size itself.
               Vector<double> prev_values;
               son_el_pt->get_interpolated_values(t, s_in_son, prev_values);
               // Initialise the values at the new node
               for (unsigned k = 0; k < created_node_pt->nvalue(); k++)
               {
                 created_node_pt->set_value(t, k, prev_values[k]);
               }
             }
             // Add the node to the mesh
             mesh_pt->add_node_pt(created_node_pt);
             // Check if the element is an algebraic element
             AlgebraicElementBase* alg_el_pt =
               dynamic_cast<AlgebraicElementBase*>(this);
             // If we do have an algebraic element
             if (alg_el_pt != 0)
             {
               std::string error_message =
                 "Have not implemented rebuilding from sons for";
               error_message += "Algebraic p-refineable elements yet\n";
               throw OomphLibError(
                 error_message,
                 "PRefineableQElement<3,INITIAL_NNODE_1D>::rebuild_from_sons()",
                 OOMPH_EXCEPTION_LOCATION);
             }
           } // End of the case when we build the node ourselves
         }
       }
     }
   }
References oomph::Mesh::add_boundary_node(), oomph::Mesh::add_node_pt(), oomph::OcTreeNames::B, oomph::Mesh::boundary_coordinate_exists(), oomph::OcTreeNames::D, oomph::OcTreeNames::DB, oomph::OcTreeNames::DF, oomph::OcTreeNames::F, oomph::RefineableQElement< 3 >::get_bcs(), oomph::RefineableQElement< 3 >::get_boundaries(), oomph::RefineableElement::get_interpolated_values(), oomph::RefineableSolidQElement< 3 >::get_solid_bcs(), oomph::FiniteElement::get_x(), i, oomph::RefineableQElement< 3 >::interpolated_zeta_on_face(), k, oomph::OcTreeNames::L, oomph::OcTreeNames::LB, oomph::OcTreeNames::LD, oomph::OcTreeNames::LDB, oomph::OcTreeNames::LDF, oomph::OcTreeNames::LF, oomph::OcTreeNames::LU, oomph::OcTreeNames::LUB, oomph::OcTreeNames::LUF, m, n, oomph::Node::ndim(), oomph::TimeStepper::ntstorage(), oomph::Data::nvalue(), oomph::Tree::OMEGA, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::PRefineableElement::p_order(), oomph::Data::pin(), oomph::SolidNode::pin_position(), oomph::OcTreeNames::R, oomph::OcTreeNames::RB, oomph::OcTreeNames::RD, oomph::OcTreeNames::RDB, oomph::OcTreeNames::RDF, oomph::OcTreeNames::RF, oomph::OcTreeNames::RU, oomph::OcTreeNames::RUB, oomph::OcTreeNames::RUF, s, oomph::Node::set_coordinates_on_boundary(), oomph::Data::set_value(), oomph::Global_string_for_annotation::string(), plotPSD::t, oomph::OcTreeNames::U, oomph::OcTreeNames::UB, oomph::OcTreeNames::UF, oomph::Node::x(), and Eigen::zeta().
shape()
template<unsigned INITIAL_NNODE_1D> void oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::shape (const Vector< double > & s, Shape & psi) const virtual
Overload the shape functions.
Shape functions for PRefineableQElement<DIM>
Implements oomph::FiniteElement.
   {
     switch (P_order)
     {
       case 2:
       {
         // Call the OneDimensional Shape functions
         OneDimensionalLegendreShape<2>::calculate_nodal_positions();
         OneDimensionalLegendreShape<2> psi1(s[0]), psi2(s[1]), psi3(s[2]);
         // Now let's loop over the nodal points in the element
         // and copy the values back in
         for (unsigned i = 0; i < P_order; i++)
         {
           for (unsigned j = 0; j < P_order; j++)
           {
             for (unsigned k = 0; k < P_order; k++)
             {
               psi(P_order * P_order * i + P_order * j + k) =
                 psi3[i] * psi2[j] * psi1[k];
             }
           }
         }
         break;
       }
       case 3:
       {
         // Call the OneDimensional Shape functions
         OneDimensionalLegendreShape<3>::calculate_nodal_positions();
         OneDimensionalLegendreShape<3> psi1(s[0]), psi2(s[1]), psi3(s[2]);
         // Now let's loop over the nodal points in the element
         // and copy the values back in
         for (unsigned i = 0; i < P_order; i++)
         {
           for (unsigned j = 0; j < P_order; j++)
           {
             for (unsigned k = 0; k < P_order; k++)
             {
               psi(P_order * P_order * i + P_order * j + k) =
                 psi3[i] * psi2[j] * psi1[k];
             }
           }
         }
         break;
       }
       case 4:
       {
         // Call the OneDimensional Shape functions
         OneDimensionalLegendreShape<4>::calculate_nodal_positions();
         OneDimensionalLegendreShape<4> psi1(s[0]), psi2(s[1]), psi3(s[2]);
         // Now let's loop over the nodal points in the element
         // and copy the values back in
         for (unsigned i = 0; i < P_order; i++)
         {
           for (unsigned j = 0; j < P_order; j++)
           {
             for (unsigned k = 0; k < P_order; k++)
             {
               psi(P_order * P_order * i + P_order * j + k) =
                 psi3[i] * psi2[j] * psi1[k];
             }
           }
         }
         break;
       }
       case 5:
       {
         // Call the OneDimensional Shape functions
         OneDimensionalLegendreShape<5>::calculate_nodal_positions();
         OneDimensionalLegendreShape<5> psi1(s[0]), psi2(s[1]), psi3(s[2]);
         // Now let's loop over the nodal points in the element
         // and copy the values back in
         for (unsigned i = 0; i < P_order; i++)
         {
           for (unsigned j = 0; j < P_order; j++)
           {
             for (unsigned k = 0; k < P_order; k++)
             {
               psi(P_order * P_order * i + P_order * j + k) =
                 psi3[i] * psi2[j] * psi1[k];
             }
           }
         }
         break;
       }
       case 6:
       {
         // Call the OneDimensional Shape functions
         OneDimensionalLegendreShape<6>::calculate_nodal_positions();
         OneDimensionalLegendreShape<6> psi1(s[0]), psi2(s[1]), psi3(s[2]);
         // Now let's loop over the nodal points in the element
         // and copy the values back in
         for (unsigned i = 0; i < P_order; i++)
         {
           for (unsigned j = 0; j < P_order; j++)
           {
             for (unsigned k = 0; k < P_order; k++)
             {
               psi(P_order * P_order * i + P_order * j + k) =
                 psi3[i] * psi2[j] * psi1[k];
             }
           }
         }
         break;
       }
       case 7:
       {
         // Call the OneDimensional Shape functions
         OneDimensionalLegendreShape<7>::calculate_nodal_positions();
         OneDimensionalLegendreShape<7> psi1(s[0]), psi2(s[1]), psi3(s[2]);
         // Now let's loop over the nodal points in the element
         // and copy the values back in
         for (unsigned i = 0; i < P_order; i++)
         {
           for (unsigned j = 0; j < P_order; j++)
           {
             for (unsigned k = 0; k < P_order; k++)
             {
               psi(P_order * P_order * i + P_order * j + k) =
                 psi3[i] * psi2[j] * psi1[k];
             }
           }
         }
         break;
       }
       default:
         std::ostringstream error_message;
         error_message << "\nERROR: Exceeded maximum polynomial order for";
         error_message << "\n       polynomial order for shape functions.\n";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
     }
   }
References oomph::OneDimensionalLegendreShape< NNODE_1D >::calculate_nodal_positions(), i, j, k, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and s.
The documentation for this class was generated from the following files:
hp_refineable_elements.h
hp_refineable_elements.cc