MercuryDPM: oomph::SimpleCubicTetMesh< ELEMENT > Class Template Reference
oomph::SimpleCubicTetMesh< ELEMENT > Class Template Reference
MySimple 3D tet mesh for TElements.
#include <simple_cubic_tet_mesh.template.h>
Public Member Functions
SimpleCubicTetMesh (const unsigned &n_x, const unsigned &n_y, const unsigned &n_z, const double &l_x, const double &l_y, const double &l_z, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Public Member Functions inherited from oomph::TetMeshBase
TetMeshBase ()
Constructor.
TetMeshBase (const TetMeshBase &node)=delete
Broken copy constructor.
void operator= (const TetMeshBase &)=delete
Broken assignment operator.
virtual ~TetMeshBase ()
Destructor (empty)
void assess_mesh_quality (std::ofstream &some_file)
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b)
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b, const bool &switch_normal)
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b, const bool &switch_normal, std::ofstream &outfile)
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b, std::ofstream &outfile)
unsigned nboundary_element_in_region (const unsigned &b, const unsigned &r) const
Return the number of elements adjacent to boundary b in region r.
FiniteElement * boundary_element_in_region_pt (const unsigned &b, const unsigned &r, const unsigned &e) const
Return pointer to the e-th element adjacent to boundary b in region r.
int face_index_at_boundary_in_region (const unsigned &b, const unsigned &r, const unsigned &e) const
Return face index of the e-th element adjacent to boundary b in region r.
unsigned nregion ()
Return the number of regions specified by attributes.
unsigned nregion_element (const unsigned &r)
Return the number of elements in region r.
double region_attribute (const unsigned &i)
FiniteElement * region_element_pt (const unsigned &r, const unsigned &e)
Return the e-th element in the r-th region.
template<class ELEMENT >
void snap_to_quadratic_surface (const Vector< unsigned > &boundary_id, const std::string &quadratic_surface_file_name, const bool &switch_normal, DocInfo &doc_info)
template<class ELEMENT >
void snap_to_quadratic_surface (const Vector< unsigned > &boundary_id, const std::string &quadratic_surface_file_name, const bool &switch_normal)
void snap_nodes_onto_geometric_objects ()
template<class ELEMENT >
void split_elements_in_corners (TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
void setup_boundary_element_info ()
void setup_boundary_element_info (std::ostream &outfile)
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void node_update (const bool &update_all_solid_nodes=false)
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Private Member Functions
void build_from_scaffold (TimeStepper *time_stepper_pt)
Build mesh from scaffold mesh.
Private Attributes
Mesh * Tmp_mesh_pt
Temporary scaffold mesh.
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::TetMeshBase
static double Tolerance_for_boundary_finding = 1.0e-5
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Protected Attributes inherited from oomph::TetMeshBase
Vector< Vector< FiniteElement * > > Region_element_pt
Vector< double > Region_attribute
Vector< std::map< unsigned, Vector< FiniteElement * > > > Boundary_region_element_pt
Storage for elements adjacent to a boundary in a particular region.
Vector< std::map< unsigned, Vector< int > > > Face_index_region_at_boundary
TetMeshFacetedClosedSurface * Outer_boundary_pt
Faceted surface that defines outer boundaries.
Vector< TetMeshFacetedSurface * > Internal_surface_pt
Vector to faceted surfaces that define internal boundaries.
std::map< unsigned, TetMeshFacetedSurface * > Tet_mesh_faceted_surface_pt
std::map< unsigned, TetMeshFacet * > Tet_mesh_facet_pt
std::map< unsigned, Vector< Vector< double > > > Triangular_facet_vertex_boundary_coordinate
TimeStepper * Time_stepper_pt
Timestepper used to build nodes.
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Detailed Description
template<class ELEMENT>
class oomph::SimpleCubicTetMesh< ELEMENT >
MySimple 3D tet mesh for TElements.
Constructor & Destructor Documentation
SimpleCubicTetMesh()
template<class ELEMENT > oomph::SimpleCubicTetMesh< ELEMENT >::SimpleCubicTetMesh (const unsigned & n_x, const unsigned & n_y, const unsigned & n_z, const double & l_x, const double & l_y, const double & l_z, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) inline
Constructor: Pass number of element blocks in the x, y and z directions and the corresponding dimensions. Timestepper defaults to Steady.
     {
       // Mesh can only be built with 3D Telements.
       MeshChecker::assert_geometric_element<TElementGeometricBase, ELEMENT>(3);
       std::ostringstream warn_message;
       warn_message
         << "Note: The SimpleCubicTetMesh() is quite inefficient.\n"
         << "      If your code takes a long time in the constructor\n"
         << "      consider using another tet mesh\n";
       OomphLibWarning(warn_message.str(),
                       "SimpleCubicTetMesh::SimpleCubicTetMesh()",
                       OOMPH_EXCEPTION_LOCATION);
       oomph_info << "Starting mesh construction..." << std::endl;
       double start_t = TimingHelpers::timer();
       // Build scaffold mesh
       Tmp_mesh_pt =
         new SimpleCubicScaffoldTetMesh(n_x, n_y, n_z, l_x, l_y, l_z);
       // Build actual mesh from scaffold mesh
       build_from_scaffold(time_stepper_pt);
       delete Tmp_mesh_pt;
       double end_t = TimingHelpers::timer();
       oomph_info << "...finished mesh construction. Total time [sec] "
                  << end_t - start_t << std::endl;
     }
References oomph::SimpleCubicTetMesh< ELEMENT >::build_from_scaffold(), OOMPH_EXCEPTION_LOCATION, oomph::oomph_info, oomph::TimingHelpers::timer(), and oomph::SimpleCubicTetMesh< ELEMENT >::Tmp_mesh_pt.
Member Function Documentation
build_from_scaffold()
template<class ELEMENT > void oomph::SimpleCubicTetMesh< ELEMENT >::build_from_scaffold (TimeStepper * time_stepper_pt) private
Build mesh from scaffold mesh.
Simple tetrahedral mesh - with 24 tet elements constructed within a "brick" form for each element block.
   {
     // Mesh can only be built with 3D Telements.
     MeshChecker::assert_geometric_element<TElementGeometricBase, ELEMENT>(3);
     // Create space for elements
     unsigned nelem = Tmp_mesh_pt->nelement();
     Element_pt.resize(nelem);
     // Create space for nodes
     unsigned nnode_scaffold = Tmp_mesh_pt->nnode();
     Node_pt.resize(nnode_scaffold);
     // Set number of boundaries
     unsigned nbound = Tmp_mesh_pt->nboundary();
     set_nboundary(nbound);
     // Loop over elements in scaffold mesh, visit their nodes
     for (unsigned e = 0; e < nelem; e++)
     {
       Element_pt[e] = new ELEMENT;
     }
     // In the first instance build all nodes from within all the elements
     unsigned nnod_el = Tmp_mesh_pt->finite_element_pt(0)->nnode();
     // Loop over elements in scaffold mesh, visit their nodes
     for (unsigned e = 0; e < nelem; e++)
     {
       // Loop over all nodes in element
       for (unsigned j = 0; j < nnod_el; j++)
       {
         // Create new node, using the NEW element's construct_node
         // member function
         finite_element_pt(e)->construct_node(j, time_stepper_pt);
       }
     }
     // Setup map to check the (pseudo-)global node number
     // Nodes whose number is zero haven't been copied across
     // into the mesh yet.
     std::map<Node*, unsigned> global_number;
     unsigned global_count = 0;
     // Loop over elements in scaffold mesh, visit their nodes
     for (unsigned e = 0; e < nelem; e++)
     {
       // Loop over all nodes in element
       for (unsigned j = 0; j < nnod_el; j++)
       {
         // Pointer to node in the scaffold mesh
         Node* scaffold_node_pt = Tmp_mesh_pt->finite_element_pt(e)->node_pt(j);
         // Get the (pseudo-)global node number in scaffold mesh
         // (It's zero [=default] if not visited this one yet)
         unsigned j_global = global_number[scaffold_node_pt];
         // Haven't done this one yet
         if (j_global == 0)
         {
           // Give it a number (not necessarily the global node
           // number in the scaffold mesh -- we just need something
           // to keep track...)
           global_count++;
           global_number[scaffold_node_pt] = global_count;
           // Copy new node, created using the NEW element's construct_node
           // function into global storage, using the same global
           // node number that we've just associated with the
           // corresponding node in the scaffold mesh
           Node_pt[global_count - 1] = finite_element_pt(e)->node_pt(j);
           // Assign coordinates
           Node_pt[global_count - 1]->x(0) = scaffold_node_pt->x(0);
           Node_pt[global_count - 1]->x(1) = scaffold_node_pt->x(1);
           Node_pt[global_count - 1]->x(2) = scaffold_node_pt->x(2);
           // Get pointer to set of mesh boundaries that this
           // scaffold node occupies; NULL if the node is not on any boundary
           std::set<unsigned>* boundaries_pt;
           scaffold_node_pt->get_boundaries_pt(boundaries_pt);
           // Loop over the mesh boundaries that the node in the scaffold mesh
           // occupies and assign new node to the same ones.
           if (boundaries_pt != 0)
           {
             this->convert_to_boundary_node(Node_pt[global_count - 1]);
             for (std::set<unsigned>::iterator it = boundaries_pt->begin();
                  it != boundaries_pt->end();
                  ++it)
             {
               add_boundary_node(*it, Node_pt[global_count - 1]);
             }
           }
         }
         // This one has already been done: Kill it
         else
         {
           // Kill it
           delete finite_element_pt(e)->node_pt(j);
           // Overwrite the element's pointer to local node by
           // pointer to the already existing node -- identified by
           // the number kept in the map
           finite_element_pt(e)->node_pt(j) = Node_pt[j_global - 1];
         }
       }
     }
     // At this point we've created all the elements and
     // created their vertex nodes. Now we need to create
     // the additional (midside and internal) nodes!
     // We'll first create all local nodes for all elements
     // and then delete the superfluous ones that have
     // a matching node in an adjacent element.
     // Get number of nodes along element edge and dimension of element (3)
     // from first element
     unsigned nnode_1d = finite_element_pt(0)->nnode_1d();
     // At the moment we're only able to deal with nnode_1d=2 or 3.
     if ((nnode_1d != 2) && (nnode_1d != 3))
     {
       std::ostringstream error_message;
       error_message << "Mesh generation currently only works\n";
       error_message << "for nnode_1d = 2 or 3. You're trying to use it\n";
       error_message << "for nnode_1d=" << nnode_1d << std::endl;
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
     // Spatial dimension of element = number of local coordinates
     unsigned dim = finite_element_pt(0)->dim();
     // Storage for the local coordinate of the new node
     Vector<double> s(dim);
     // Get number of nodes in the element from first element
     unsigned nnode = finite_element_pt(0)->nnode();
     // Loop over all elements
     for (unsigned e = 0; e < nelem; e++)
     {
       // Loop over the new nodes in the element and create them.
       for (unsigned j = 4; j < nnode; j++)
       {
         // Create new node
         Node* new_node_pt =
           finite_element_pt(e)->construct_node(j, time_stepper_pt);
         // What are the node's local coordinates?
         finite_element_pt(e)->local_coordinate_of_node(j, s);
         // Find the coordinates of the new node from the existing
         // and fully-functional element in the scaffold mesh
         for (unsigned i = 0; i < dim; i++)
         {
           new_node_pt->x(i) =
             Tmp_mesh_pt->finite_element_pt(e)->interpolated_x(s, i);
         }
       } // end of loop over new nodes
     } // end of loop over elements
     // Bracket this away so the edge map goes out of scope
     // when we're done
     {
       // Storage for pointer to mid-edge node
       MapMatrix<Node*, Node*> central_edge_node_pt;
       Node* edge_node1_pt = 0;
       Node* edge_node2_pt = 0;
       // Loop over elements
       for (unsigned e = 0; e < nelem; e++)
       {
         // Loop over new local nodes
         for (unsigned j = 4; j < nnode; j++)
         {
           // Pointer to the element's local node
           Node* node_pt = finite_element_pt(e)->node_pt(j);
           // By default, we assume the node is not new
           bool is_new = false;
           // This will have to be changed for higher-order elements
           //=======================================================
           // Switch on local node number (all located on edges)
           switch (j)
           {
               // Node 4 is located between nodes 0 and 1
             case 4:
               edge_node1_pt = finite_element_pt(e)->node_pt(0);
               edge_node2_pt = finite_element_pt(e)->node_pt(1);
               if (central_edge_node_pt(edge_node1_pt, edge_node2_pt) == 0)
               {
                 is_new = true;
                 central_edge_node_pt(edge_node1_pt, edge_node2_pt) = node_pt;
                 central_edge_node_pt(edge_node2_pt, edge_node1_pt) = node_pt;
               }
               break;
               // Node 5 is located between nodes 0 and 2
             case 5:
               edge_node1_pt = finite_element_pt(e)->node_pt(0);
               edge_node2_pt = finite_element_pt(e)->node_pt(2);
               if (central_edge_node_pt(edge_node1_pt, edge_node2_pt) == 0)
               {
                 is_new = true;
                 central_edge_node_pt(edge_node1_pt, edge_node2_pt) = node_pt;
                 central_edge_node_pt(edge_node2_pt, edge_node1_pt) = node_pt;
               }
               break;
               // Node 6 is located between nodes 0 and 3
             case 6:
               edge_node1_pt = finite_element_pt(e)->node_pt(0);
               edge_node2_pt = finite_element_pt(e)->node_pt(3);
               if (central_edge_node_pt(edge_node1_pt, edge_node2_pt) == 0)
               {
                 is_new = true;
                 central_edge_node_pt(edge_node1_pt, edge_node2_pt) = node_pt;
                 central_edge_node_pt(edge_node2_pt, edge_node1_pt) = node_pt;
               }
               break;
               // Node 7 is located between nodes 1 and 2
             case 7:
               edge_node1_pt = finite_element_pt(e)->node_pt(1);
               edge_node2_pt = finite_element_pt(e)->node_pt(2);
               if (central_edge_node_pt(edge_node1_pt, edge_node2_pt) == 0)
               {
                 is_new = true;
                 central_edge_node_pt(edge_node1_pt, edge_node2_pt) = node_pt;
                 central_edge_node_pt(edge_node2_pt, edge_node1_pt) = node_pt;
               }
               break;
               // Node 8 is located between nodes 2 and 3
             case 8:
               edge_node1_pt = finite_element_pt(e)->node_pt(2);
               edge_node2_pt = finite_element_pt(e)->node_pt(3);
               if (central_edge_node_pt(edge_node1_pt, edge_node2_pt) == 0)
               {
                 is_new = true;
                 central_edge_node_pt(edge_node1_pt, edge_node2_pt) = node_pt;
                 central_edge_node_pt(edge_node2_pt, edge_node1_pt) = node_pt;
               }
               break;
               // Node 9 is located between nodes 1 and 3
             case 9:
               edge_node1_pt = finite_element_pt(e)->node_pt(1);
               edge_node2_pt = finite_element_pt(e)->node_pt(3);
               if (central_edge_node_pt(edge_node1_pt, edge_node2_pt) == 0)
               {
                 is_new = true;
                 central_edge_node_pt(edge_node1_pt, edge_node2_pt) = node_pt;
                 central_edge_node_pt(edge_node2_pt, edge_node1_pt) = node_pt;
               }
               break;
             default:
               throw OomphLibError("More than ten nodes in Tet Element",
                                   OOMPH_CURRENT_FUNCTION,
                                   OOMPH_EXCEPTION_LOCATION);
           }
           if (is_new)
           {
             // New node: Add it to mesh
             Node_pt.push_back(node_pt);
           }
           else
           {
             // Delete local node in element...
             delete finite_element_pt(e)->node_pt(j);
             // ... and reset pointer to the existing node
             finite_element_pt(e)->node_pt(j) =
               central_edge_node_pt(edge_node1_pt, edge_node2_pt);
           }
         }
       }
     }
     // Boundary conditions
     // Matrix map to check if a node has already been added to
     // the boundary number b (NOTE: Enumerated by pointer to ORIGINAL
     // node before transfer to boundary node)
     MapMatrixMixed<Node*, unsigned, bool> bound_node_done;
     // Create lookup scheme for pointers to original local nodes
     // in elements
     Vector<Vector<Node*>> orig_node_pt(nelem);
     // Loop over elements
     for (unsigned e = 0; e < nelem; e++)
     {
       orig_node_pt[e].resize(nnode, 0);
       // Loop over new local nodes
       for (unsigned j = 4; j < nnode; j++)
       {
         // Pointer to the element's local node
         orig_node_pt[e][j] = finite_element_pt(e)->node_pt(j);
       }
     }
     // Loop over elements
     for (unsigned e = 0; e < nelem; e++)
     {
       // Loop over new local nodes
       for (unsigned j = 4; j < nnode; j++)
       {
         // Loop over the boundaries
         for (unsigned bo = 0; bo < nbound; bo++)
         {
           // Pointer to the element's local node
           Node* loc_node_pt = finite_element_pt(e)->node_pt(j);
           // Pointer to original node
           Node* orig_loc_node_pt = orig_node_pt[e][j];
           // value of the map for the node and boundary specified
           bool bound_test = bound_node_done(orig_loc_node_pt, bo);
           if (bound_test == false)
           {
             bound_node_done(orig_loc_node_pt, bo) = true;
             // This will have to be changed for higher-order elements
             //=======================================================
             // Switch on local node number (all located on edges)
             switch (j)
             {
                 // Node 4 is located between nodes 0 and 1
               case 4:
                 if (finite_element_pt(e)->node_pt(0)->is_on_boundary(bo) &&
                     finite_element_pt(e)->node_pt(1)->is_on_boundary(bo))
                 {
                   this->convert_to_boundary_node(loc_node_pt);
                   add_boundary_node(bo, loc_node_pt);
                 }
                 break;
                 // Node 5 is located between nodes 0 and 2
               case 5:
                 if (finite_element_pt(e)->node_pt(0)->is_on_boundary(bo) &&
                     finite_element_pt(e)->node_pt(2)->is_on_boundary(bo))
                 {
                   this->convert_to_boundary_node(loc_node_pt);
                   add_boundary_node(bo, loc_node_pt);
                 }
                 break;
                 // Node 6 is located between nodes 0 and 3
               case 6:
                 if (finite_element_pt(e)->node_pt(0)->is_on_boundary(bo) &&
                     finite_element_pt(e)->node_pt(3)->is_on_boundary(bo))
                 {
                   this->convert_to_boundary_node(loc_node_pt);
                   add_boundary_node(bo, loc_node_pt);
                 }
                 break;
                 // Node 7 is located between nodes 1 and 2
               case 7:
                 if (finite_element_pt(e)->node_pt(1)->is_on_boundary(bo) &&
                     finite_element_pt(e)->node_pt(2)->is_on_boundary(bo))
                 {
                   this->convert_to_boundary_node(loc_node_pt);
                   add_boundary_node(bo, loc_node_pt);
                 }
                 break;
                 // Node 8 is located between nodes 2 and 3
               case 8:
                 if (finite_element_pt(e)->node_pt(2)->is_on_boundary(bo) &&
                     finite_element_pt(e)->node_pt(3)->is_on_boundary(bo))
                 {
                   this->convert_to_boundary_node(loc_node_pt);
                   add_boundary_node(bo, loc_node_pt);
                 }
                 break;
                 // Node 9 is located between nodes 1 and 3
               case 9:
                 if (finite_element_pt(e)->node_pt(1)->is_on_boundary(bo) &&
                     finite_element_pt(e)->node_pt(3)->is_on_boundary(bo))
                 {
                   this->convert_to_boundary_node(loc_node_pt);
                   add_boundary_node(bo, loc_node_pt);
                 }
                 break;
               default:
                 throw OomphLibError("More than ten nodes in Tet Element",
                                     OOMPH_CURRENT_FUNCTION,
                                     OOMPH_EXCEPTION_LOCATION);
             }
           }
         } // end for bo
       } // end for j
     } // end for e
   }
References plotDoE::bo, e(), oomph::Node::get_boundaries_pt(), i, j, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, s, and oomph::Node::x().
Referenced by oomph::SimpleCubicTetMesh< ELEMENT >::SimpleCubicTetMesh().
Member Data Documentation
Tmp_mesh_pt
template<class ELEMENT > Mesh* oomph::SimpleCubicTetMesh< ELEMENT >::Tmp_mesh_pt private
Temporary scaffold mesh.
Referenced by oomph::SimpleCubicTetMesh< ELEMENT >::SimpleCubicTetMesh().
The documentation for this class was generated from the following files:
simple_cubic_tet_mesh.template.h
simple_cubic_tet_mesh.template.cc