MercuryDPM: ShearBoxBoundary Class Reference
ShearBoxBoundary Class Reference
Class which creates a boundary with Lees-Edwards type periodic boundary conditions.
#include <ShearBoxBoundary.h>
Public Member Functions
void set (std::function< double(double, double)> velocity, Mdouble left, Mdouble right, Mdouble down, Mdouble up)
Sets all boundary properties.
void read (std::istream &is) override
Reads all boundary properties from a stream.
void write (std::ostream &os) const override
Writes all boundary properties to a stream.
std::string getName () const override
Returns the name of the object.
ShearBoxBoundary * copy () const override
Creates a copy of the object.
Mdouble getHorizontalDistance (BaseParticle &p, bool &positive)
Returns distance from given particle to the closest horizontal wall.
Mdouble getVerticalDistance (BaseParticle &p, bool &positive)
Returns distance from given particle to the closest vertical wall.
void shiftHorizontalPosition (BaseParticle *p, bool positive)
Applies a horizontal shift to the given particle.
void shiftVerticalPosition (BaseParticle *p, bool positive)
Applies a vertical shift to the given particle.
bool checkBoundaryAfterParticleMoved (BaseParticle *p, ParticleHandler &pH UNUSED)
Checks if particle crossed a boundary wall and if so, applies periodic shift.
void createPeriodicParticle (BaseParticle *p, ParticleHandler &pH) override
Creates horizontal and vertical periodic copies of given particle, if needed.
void createHorizontalPeriodicParticle (BaseParticle *p, ParticleHandler &pH)
Creates horizontal periodic copies of given particle, if needed.
void createVerticalPeriodicParticle (BaseParticle *p, ParticleHandler &pH)
Creates vertical periodic copies of given particle, if needed.
void setVelocity (std::function< double(double, double)>)
Public Member Functions inherited from BaseBoundary
BaseBoundary ()
default constructor.
BaseBoundary (const BaseBoundary &b)
copy constructor
~BaseBoundary () override
destructor
virtual void createPeriodicParticle (BaseParticle *p UNUSED, ParticleHandler &pH UNUSED)
Creates a periodic particle in case of periodic boundaries in serial build.
virtual void createPeriodicParticles (ParticleHandler &pH UNUSED)
Creates periodic copies of given particle in case of periodic boundaries.
virtual void checkBoundaryAfterParticlesMove (ParticleHandler &pH)
Virtual function that does things to particles, each time step after particles have moved.
virtual void checkBoundaryBeforeTimeStep (DPMBase *md)
Virtual function that does things before each time step.
virtual void actionsBeforeTimeLoop ()
Virtual function that does something after DPMBase::setupInitialConditions but before the first time step.
virtual void modifyGhostAfterCreation (BaseParticle *particle, int i)
virtual void writeVTK (std::fstream &file)
void setHandler (BoundaryHandler *handler)
Sets the boundary's BoundaryHandler.
BoundaryHandler * getHandler () const
Returns the boundary's BoundaryHandler.
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Private Attributes
Mdouble left_
Mdouble right_
(signed) Horizontal distance between the left wall and the origin
Mdouble down_
(signed) Horizontal distance between the right wall and the origin
Mdouble up_
(signed) Vertical distance between the bottom wall and the origin
std::function< double(double, double)> velocity_
(signed) Vertical distance between the top wall and the origin
Detailed Description
Class which creates a boundary with Lees-Edwards type periodic boundary conditions.
See also [insert link to the original paper by LE]. Inherits from BaseBoundary.
Todo:
Add link to paper by Lees-Edwards in the documentation of this class.
Is implemented for 2D only now. Needs extension to 3D.
Member Function Documentation
checkBoundaryAfterParticleMoved()
bool ShearBoxBoundary::checkBoundaryAfterParticleMoved (BaseParticle * p, ParticleHandler &pH UNUSED)
Checks if particle crossed a boundary wall and if so, applies periodic shift.
Checks if the particle has to be shifted into the main domain (i.e., if the particle has crossed any of the boundary walls) and if so performs the shift
Parameters
[in] p A pointer to the BaseParticle that is checked
 {
     bool positive;
     while (getVerticalDistance(*p, positive) < 0)
     {
         shiftVerticalPosition(p, positive);
     }
     while (getHorizontalDistance(*p, positive) < 0)
     {
         shiftHorizontalPosition(p, positive);
     }
     return false;
 }
References getHorizontalDistance(), getVerticalDistance(), p, shiftHorizontalPosition(), and shiftVerticalPosition().
copy()
ShearBoxBoundary * ShearBoxBoundary::copy () const override virtual
Creates a copy of the object.
Copy method; creates a copy on the heap and returns its pointer.
Returns
pointer to the copy on the heap
Implements BaseBoundary.
 {
     return new ShearBoxBoundary(*this);
 }
createHorizontalPeriodicParticle()
void ShearBoxBoundary::createHorizontalPeriodicParticle (BaseParticle * p, ParticleHandler & pH)
Creates horizontal periodic copies of given particle, if needed.
Check if periodic copies of the particle in horizontal direction have to be made (i.e., if the distance of the particle to either of the horizontal boundary walls is smaller than its radius plus the radius of the largest particle in the system), and if so makes them
Parameters
[in] p A pointer to the BaseParticle that is checked
[out] pH A reference to the ParticleHandler where periodic copies will be added
 {
     bool positive;      // TRUE if the particle is closest to the left boundary
     // wall (set by getVerticalDistance in the following if-statement)
     // check if particle is close enough to either of the walls
     const Mdouble maxDistance = p->getMaxInteractionRadius() + pH.getLargestParticle()->getMaxInteractionRadius();
     if (getHorizontalDistance(*p, positive) < maxDistance)
     {
         // create a periodic copy of the particle
         BaseParticle* F0 = p->copy();
         pH.addObject(F0);
         F0->copyInteractionsForPeriodicParticles(*p);
         // If Particle is doubly shifted, get correct original particle
         BaseParticle* From = p;
         while (From->getPeriodicFromParticle() != nullptr)
             From = From->getPeriodicFromParticle();
         F0->setPeriodicFromParticle(From);
         // shift the copy to the 'periodic' position
         shiftHorizontalPosition(F0, positive);
         // NB: No extra creation of possible vertical copies of the horizontal copy
         // here (as compared to createVerticalPeriodicParticle), because these would
         // overlap with the extra creation of horizontal copies in createVerticalPeriodicParticle.
     }
 }
References ParticleHandler::addObject(), BaseInteractable::copyInteractionsForPeriodicParticles(), getHorizontalDistance(), ParticleHandler::getLargestParticle(), BaseParticle::getMaxInteractionRadius(), BaseParticle::getPeriodicFromParticle(), p, BaseParticle::setPeriodicFromParticle(), and shiftHorizontalPosition().
Referenced by createPeriodicParticle(), and createVerticalPeriodicParticle().
createPeriodicParticle()
void ShearBoxBoundary::createPeriodicParticle (BaseParticle * p, ParticleHandler & pH) override
Creates horizontal and vertical periodic copies of given particle, if needed.
Check if periodic copies of the particle have to be made for the contact detection and if so makes them
Parameters
[in] p A pointer to the BaseParticle that is checked
[out] pH A reference to the ParticleHandler where periodic copies will be added
 {
     createVerticalPeriodicParticle(p, pH);
     createHorizontalPeriodicParticle(p, pH);
 }
References createHorizontalPeriodicParticle(), createVerticalPeriodicParticle(), and p.
createVerticalPeriodicParticle()
void ShearBoxBoundary::createVerticalPeriodicParticle (BaseParticle * p, ParticleHandler & pH)
Creates vertical periodic copies of given particle, if needed.
Check if periodic copies of the particle in vertical direction have to be made (i.e., if the distance of the particle to either of the vertical boundary walls is smaller than its radius plus the radius of the largest particle in the system), and if so makes them
Parameters
[in] p A pointer to the BaseParticle that is checked
[out] pH A reference to the ParticleHandler where periodic copies will be added
 {
     bool positive;      // TRUE if the particle is closest to the bottom boundary
     // wall (set by getVerticalDistance in the following if-statement)
     // check if particle is close enough to either of the walls
     const Mdouble maxDistance = p->getMaxInteractionRadius() + pH.getLargestParticle()->getMaxInteractionRadius();
     if (getVerticalDistance(*p, positive) < maxDistance)
     {
         // create a periodic copy of the particle
         BaseParticle* F0 = p->copy();
         pH.addObject(F0);
         F0->copyInteractionsForPeriodicParticles(*p);
         // If Particle is doubly shifted, get correct original particle
         BaseParticle* From = p;
         while (From->getPeriodicFromParticle() != nullptr)
             From = From->getPeriodicFromParticle();
         F0->setPeriodicFromParticle(From);
         // shift the copy to the 'periodic' position
         shiftVerticalPosition(F0, positive);
         while (getHorizontalDistance(*F0, positive) < 0)
         {
             shiftHorizontalPosition(F0, positive);
         }
         // Create horizontal periodic copies of the copy particle, if needed (i.e.,
         // if the original particle is in one of the boundary corners).
         createHorizontalPeriodicParticle(pH.getLastObject(), pH);
     }
 }
References ParticleHandler::addObject(), BaseInteractable::copyInteractionsForPeriodicParticles(), createHorizontalPeriodicParticle(), getHorizontalDistance(), ParticleHandler::getLargestParticle(), BaseHandler< T >::getLastObject(), BaseParticle::getMaxInteractionRadius(), BaseParticle::getPeriodicFromParticle(), getVerticalDistance(), p, BaseParticle::setPeriodicFromParticle(), shiftHorizontalPosition(), and shiftVerticalPosition().
Referenced by createPeriodicParticle().
getHorizontalDistance()
Mdouble ShearBoxBoundary::getHorizontalDistance (BaseParticle & p, bool & positive)
Returns distance from given particle to the closest horizontal wall.
Returns the distance between BaseParticle p and the closest boundary wall in horizontal direction
Parameters
[in] p A reference to the BaseParticle
[out] positive A boolean which is true when the left wall is closest
Returns
The distance to the closes wall in horizontal direction
 {
     Mdouble left = p.getPosition().X - left_;
     Mdouble right = right_ - p.getPosition().X;
     if (left < right)
     {
         positive = true;
         return left;
     }
     else
     {
         positive = false;
         return right;
     }
 }
References left_, p, and right_.
Referenced by checkBoundaryAfterParticleMoved(), createHorizontalPeriodicParticle(), and createVerticalPeriodicParticle().
getName()
std::string ShearBoxBoundary::getName () const override virtual
Returns the name of the object.
Returns
The name of this object (i.e. "ShearBoxBoundary")
Implements BaseObject.
 {
     return "ShearBoxBoundary";
 }
getVerticalDistance()
Mdouble ShearBoxBoundary::getVerticalDistance (BaseParticle & p, bool & positive)
Returns distance from given particle to the closest vertical wall.
Returns the distance between BaseParticle p and the closest wall in vertical direction
Parameters
[in] p A reference to the BaseParticle
[out] positive A boolean which is true when the bottom wall is closest
Returns
The distance to the closes wall in vertical direction
 {
     Mdouble down = p.getPosition().Y - down_;
     Mdouble up = up_ - p.getPosition().Y;
     if (down < up)
     {
         positive = true;
         return down;
     }
     else
     {
         positive = false;
         return up;
     }
 }
References down_, p, and up_.
Referenced by checkBoundaryAfterParticleMoved(), and createVerticalPeriodicParticle().
read()
void ShearBoxBoundary::read (std::istream & is) override virtual
Reads all boundary properties from a stream.
Reads all the properties of the ShearBoxBoundary from an std::istream
Parameters
[in,out] is The stream from which the parameters are read
Implements BaseBoundary.
 {
     std::string dummy;
     BaseBoundary::read(is);
     is >> dummy >> left_ >> dummy >> right_ >> dummy >> down_ >> dummy >> up_;
     velocity_ = [](double time UNUSED, double velocity UNUSED) { return 0.0; };
 }
References down_, left_, BaseBoundary::read(), right_, oomph::Global_string_for_annotation::string(), UNUSED, up_, Jeffery_Solution::velocity(), and velocity_.
set()
void ShearBoxBoundary::set (std::function< double(double, double)> velocity, Mdouble left, Mdouble right, Mdouble down, Mdouble up)
Sets all boundary properties.
Allows the user to set all the properties of the ShearBoxBoundary at once.
Parameters
[in] velocity The difference in velocities at which the bottom and to wall move
[in] left The (signed) distance between the origin and the left wall
[in] right The (signed) distance between the origin and the right wall
[in] down The (signed) distance between the origin and the top wall
[in] up The (signed) distance between the origin and the bottom wall
 {
     velocity_ = velocity;
     left_ = left;
     right_ = right;
     down_ = down;
     up_ = up;
 }
References down_, left_, right_, up_, Jeffery_Solution::velocity(), and velocity_.
setVelocity()
void ShearBoxBoundary::setVelocity (std::function< double(double, double)> velocity)
 {
     velocity_ = velocity;
 }
References Jeffery_Solution::velocity(), and velocity_.
shiftHorizontalPosition()
void ShearBoxBoundary::shiftHorizontalPosition (BaseParticle * p, bool positive)
Applies a horizontal shift to the given particle.
Shifts the BaseParticle p in horizontal direction to its 'periodic' position, i.e. over the horizontal length of the boundary.
Parameters
[in] p A reference to the BaseParticle that has to be shifted
[in] positive A boolean which determines the direction of the shift NB: TRUE if particle is closest to the left boundary wall
 {
     Mdouble time = getHandler()->getDPMBase()->getTime();
     Mdouble z = p->getPosition().Z;
     if (positive)
     {
         p->move(Vec3D(right_ - left_, 0.0, 0.0));
         p->addVelocity(Vec3D(velocity_(time, z), 0.0, 0.0));
     }
     else
     {
         p->move(Vec3D(left_ - right_, 0.0, 0.0));
         p->addVelocity(Vec3D(velocity_(time, z), 0.0, 0.0));
     }
 }
References BaseHandler< T >::getDPMBase(), BaseBoundary::getHandler(), DPMBase::getTime(), left_, p, right_, and velocity_.
Referenced by checkBoundaryAfterParticleMoved(), createHorizontalPeriodicParticle(), and createVerticalPeriodicParticle().
shiftVerticalPosition()
void ShearBoxBoundary::shiftVerticalPosition (BaseParticle * p, bool positive)
Applies a vertical shift to the given particle.
Shifts the BaseParticle p in vertical direction to its 'periodic' position, i.e. over the vertical length of the boundary.
Parameters
[in] p A reference to the BaseParticle that has to be shifted
[in] positive A boolean which determines the direction of the shift NB: TRUE if particle is closest to the bottom boundary wall
 {
     if (positive)
     {
         p->move(Vec3D(0.0, up_ - down_, 0.0));
     }
     else
     {
         p->move(Vec3D(0.0, down_ - up_, 0.0));
     }
 }
References down_, p, and up_.
Referenced by checkBoundaryAfterParticleMoved(), and createVerticalPeriodicParticle().
write()
void ShearBoxBoundary::write (std::ostream & os) const override virtual
Writes all boundary properties to a stream.
Writes all the properties of the ShearBoxBoundary to an std::ostream
Parameters
[out] os The stream to which the parameters are written
Implements BaseBoundary.
 {
     BaseBoundary::write(os);
     os << " left " << left_ << " right " << right_ << " down " << down_ << " up " << up_;
 }
References down_, left_, right_, up_, and BaseBoundary::write().
Member Data Documentation
down_
Mdouble ShearBoxBoundary::down_ private
(signed) Horizontal distance between the right wall and the origin
Referenced by getVerticalDistance(), read(), set(), shiftVerticalPosition(), and write().
left_
Mdouble ShearBoxBoundary::left_ private
Referenced by getHorizontalDistance(), read(), set(), shiftHorizontalPosition(), and write().
right_
Mdouble ShearBoxBoundary::right_ private
(signed) Horizontal distance between the left wall and the origin
Referenced by getHorizontalDistance(), read(), set(), shiftHorizontalPosition(), and write().
up_
Mdouble ShearBoxBoundary::up_ private
(signed) Vertical distance between the bottom wall and the origin
Referenced by getVerticalDistance(), read(), set(), shiftVerticalPosition(), and write().
velocity_
std::function<double(double, double)> ShearBoxBoundary::velocity_ private
(signed) Vertical distance between the top wall and the origin
Referenced by read(), set(), setVelocity(), and shiftHorizontalPosition().
The documentation for this class was generated from the following files:
ShearBoxBoundary.h
ShearBoxBoundary.cc