MercuryDPM: Eigen::internal::variable_if_dynamic< T, Value > Class Template Reference
Eigen::internal::variable_if_dynamic< T, Value > Class Template Reference
#include <XprHelper.h>
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE variable_if_dynamic (T v)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EIGEN_CONSTEXPR operator T () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void setValue (T v) const
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EIGEN_CONSTEXPR T value ()
Detailed Description
template<typename T, int Value>
class Eigen::internal::variable_if_dynamic< T, Value >
If the template parameter Value is Dynamic, this class is just a wrapper around a T variable that can be accessed using value() and setValue(). Otherwise, this class is an empty structure and value() just returns the template parameter Value.
Constructor & Destructor Documentation
variable_if_dynamic()
template<typename T , int Value> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::internal::variable_if_dynamic< T, Value >::variable_if_dynamic (T v) inline explicit
{
     EIGEN_ONLY_USED_FOR_DEBUG(v);
     eigen_assert(v == T(Value));
   }
References eigen_assert, EIGEN_ONLY_USED_FOR_DEBUG, and v.
Member Function Documentation
operator T()
template<typename T , int Value> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EIGEN_CONSTEXPR Eigen::internal::variable_if_dynamic< T, Value >::operator T () const inline
 { return T(Value); }
setValue()
template<typename T , int Value> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::variable_if_dynamic< T, Value >::setValue (T v) const inline
{
     EIGEN_ONLY_USED_FOR_DEBUG(v);
     eigen_assert(v == T(Value));
   }
References eigen_assert, EIGEN_ONLY_USED_FOR_DEBUG, and v.
Referenced by Eigen::internal::pointer_based_stl_iterator< XprType >::operator=(), and Eigen::Stride< OuterStrideAtCompileTime_, InnerStrideAtCompileTime_ >::operator=().
value()
template<typename T , int Value> static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EIGEN_CONSTEXPR T Eigen::internal::variable_if_dynamic< T, Value >::value () inline static
 { return T(Value); }
Referenced by Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::blockCols(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::blockRows(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::coeff(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::coeffRef(), Eigen::CwiseNullaryOp< NullaryOp, PlainObjectType >::cols(), Eigen::Replicate< MatrixType, RowFactor, ColFactor >::cols(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::cols(), Eigen::SVDBase< Derived >::cols(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::colStride(), Eigen::SVDBase< Derived >::diagSize(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::getLinearMapper(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::getSubMapper(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::incr(), Eigen::Stride< OuterStrideAtCompileTime_, InnerStrideAtCompileTime_ >::inner(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::load(), Eigen::internal::BlasLinearMapper< Scalar, Index, AlignmentType, Incr >::loadPacket(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::loadPacket(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::loadPacketPartial(), Eigen::internal::BlasLinearMapper< Scalar, Index, AlignmentType, Incr >::loadPacketPartial(), Eigen::internal::BlasLinearMapper< Scalar, Index, AlignmentType, Incr >::operator()(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::operator()(), Eigen::internal::pointer_based_stl_iterator< XprType >::operator++(), Eigen::internal::pointer_based_stl_iterator< XprType >::operator+=(), Eigen::internal::pointer_based_stl_iterator< XprType >::operator-(), Eigen::internal::pointer_based_stl_iterator< XprType >::operator--(), Eigen::internal::pointer_based_stl_iterator< XprType >::operator-=(), Eigen::SparseCompressedBase< Derived >::InnerIterator::operator=(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::operator=(), Eigen::internal::pointer_based_stl_iterator< XprType >::operator[](), Eigen::Stride< OuterStrideAtCompileTime_, InnerStrideAtCompileTime_ >::outer(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::packet(), Eigen::internal::pointer_based_stl_iterator< XprType >::pointer_based_stl_iterator(), Eigen::CwiseNullaryOp< NullaryOp, PlainObjectType >::rows(), Eigen::Replicate< MatrixType, RowFactor, ColFactor >::rows(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::rows(), Eigen::SVDBase< Derived >::rows(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::rowStride(), Eigen::internal::variable_if_dynamic< T, Dynamic >::setValue(), Eigen::internal::inner_product_evaluator< Func, Lhs, Rhs >::size(), Eigen::internal::CoherentPadOp< XprType, SizeAtCompileTime_ >::size(), Eigen::internal::ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >::size(), Eigen::internal::AllRange< SizeAtCompileTime_ >::size(), Eigen::internal::BlasLinearMapper< Scalar, Index, AlignmentType, Incr >::storePacket(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::storePacket(), Eigen::internal::BlasLinearMapper< Scalar, Index, AlignmentType, Incr >::storePacketPartial(), Eigen::internal::blas_data_mapper< Scalar, Index, StorageOrder, AlignmentType, Incr >::storePacketPartial(), and Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::writePacket().
The documentation for this class was generated from the following file:
XprHelper.h