MercuryDPM: oomph::PseudoBucklingRingElement Class Reference
oomph::PseudoBucklingRingElement Class Reference
#include <pseudo_buckling_ring.h>
Public Member Functions
PseudoBucklingRingElement (const double &eps_buckl, const double &ampl_ratio, const unsigned n_buckl, const double &r_0, const double &T, TimeStepper *time_stepper_pt)
PseudoBucklingRingElement (const double &eps_buckl, const double &HoR, const unsigned &n_buckl, const unsigned &imode, TimeStepper *time_stepper_pt)
PseudoBucklingRingElement (const PseudoBucklingRingElement &dummy)=delete
Broken copy constructor.
void operator= (const PseudoBucklingRingElement &)=delete
Broken assignment operator.
virtual ~PseudoBucklingRingElement ()
Destructor: Kill internal data and set to NULL.
virtual void get_residuals (Vector< double > &residuals)
Compute element residual Vector (wrapper)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute element residual Vector and element Jacobian matrix (wrapper)
Data *const & reference_pressure_pt () const
Pointer to pressure data that is used as reference pressure.
double reference_pressure () const
Return the reference pressure.
void set_reference_pressure_pt (Data *const &data_pt)
Set the pressure data that is used as reference pressure.
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual unsigned self_test ()
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::PseudoBucklingRing
PseudoBucklingRing ()
Default constructor (empty and broken)
PseudoBucklingRing (const Vector< Data * > &geom_data_pt, TimeStepper *time_stepper_pt)
PseudoBucklingRing (const double &eps_buckl, const double &ampl_ratio, const unsigned n_buckl, const double &r_0, const double &T, TimeStepper *time_stepper_pt)
PseudoBucklingRing (const double &eps_buckl, const double &HoR, const unsigned &n_buckl, const unsigned &imode, TimeStepper *time_stepper_pt)
PseudoBucklingRing (const PseudoBucklingRing &node)=delete
Broken copy constructor.
void operator= (const PseudoBucklingRing &)=delete
Broken assignment operator.
~PseudoBucklingRing ()
Destructor: Clean up if necessary.
double eps_buckl ()
Access function for buckling amplitude.
double ampl_ratio ()
Access function for amplitude ratio.
double r_0 ()
Access function for undeformed radius.
double T ()
Access function for period of oscillation.
double n_buckl_float ()
Access function for buckling wavenumber (as float)
void set_eps_buckl (const double &eps_buckl)
Set buckling amplitude.
void set_ampl_ratio (const double &ampl_ratio)
void set_n_buckl (const unsigned &n_buckl)
Set buckling wavenumber.
void set_R_0 (const double &r_0)
Set undeformed radius of ring.
void set_T (const double &T)
Set period of oscillation.
void position (const Vector< double > &zeta, Vector< double > &r) const
void veloc (const Vector< double > &zeta, Vector< double > &veloc)
void accel (const Vector< double > &zeta, Vector< double > &accel)
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &j, Vector< double > &drdt)
unsigned ngeom_data () const
How many items of Data does the shape of the object depend on?
Data * geom_data_pt (const unsigned &j)
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
virtual void locate_zeta (const Vector< double > &zeta, GeomObject *&sub_geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
Protected Member Functions
virtual void get_residuals_generic (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
virtual void fill_in_contribution_to_residuals (Vector< double > &residuals)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Private Member Functions
int geometric_local_eqn ()
Return the local equation number of the internal geometric variable.
int reference_pressure_local_eqn ()
Return the local equation number of the reference pressure variable.
Private Attributes
unsigned Internal_geometric_variable_index
unsigned External_reference_pressure_index
Data * External_reference_pressure_pt
Additional Inherited Members
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Protected Attributes inherited from oomph::PseudoBucklingRing
Vector< Data * > Geom_data_pt
Vector of pointers to Data items that affects the object's shape.
bool Must_clean_up
Do I need to clean up?
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// Pseudo buckling ring: Circular ring deformed by the N-th buckling mode of a thin-wall elastic ring.
\[ x = R_0 \cos(\zeta) + \epsilon \left(\cos(N \zeta) \cos(\zeta) - A \sin(N \zeta) \sin(\zeta) \right) sin(2 \pi t/T) \]
\[ y = R_0 \sin(\zeta) + \epsilon \left(\cos(N \zeta) \sin(\zeta) + A \sin(N \zeta) \cos(\zeta) \right) sin(2 \pi t/T) \]
where A is the ratio of the aziumuthal to the radial buckling amplitude (A=-1/N for statically buckling rings) and epsilon is the buckling amplitude. Scale R_0 is adjusted to ensure conservation of (computational) volume/area. This is implemented by a pseudo-elasticity approach: The governing equation for \(R_0 \) is:
\[ p_{ref} = R_0 - 1.0 \]
The pointer to the reference pressure needs to be set with reference_pressure_pt().
Constructor & Destructor Documentation
PseudoBucklingRingElement() [1/3]
oomph::PseudoBucklingRingElement::PseudoBucklingRingElement (const double & eps_buckl, const double & ampl_ratio, const unsigned n_buckl, const double & r_0, const double & T, TimeStepper * time_stepper_pt) inline
Constructor: Build pseudo buckling ring from doubles that describe the geometry.
       : PseudoBucklingRing(
           eps_buckl, ampl_ratio, n_buckl, r_0, T, time_stepper_pt),
         External_reference_pressure_pt(0)
     {
       // Geom data for geom object has been setup (and pinned) in
       // constructor for geometric object. Now free the scale for the half axes
       // because we want to determine it as an unknown
       Geom_data_pt[0]->unpin(3);
       // Record that the geometric variable is value 3 in the geometric data
       Internal_geometric_variable_index = 3;
       // The geometric data is internal to the element -- this
       // ensures that any unknown pieces of geom_data get global equation
       // numbers. There should only be one piece of internal data
       unsigned n_geom_data = Geom_data_pt.size();
       for (unsigned i = 0; i < n_geom_data; i++)
       {
         add_internal_data(Geom_data_pt[i]);
       }
     }
References oomph::GeneralisedElement::add_internal_data(), oomph::PseudoBucklingRing::Geom_data_pt, i, and Internal_geometric_variable_index.
PseudoBucklingRingElement() [2/3]
oomph::PseudoBucklingRingElement::PseudoBucklingRingElement (const double & eps_buckl, const double & HoR, const unsigned & n_buckl, const unsigned & imode, TimeStepper * time_stepper_pt) inline
Constructor: Pass buckling amplitude, h/R, buckling wavenumbe and pointer to global timestepper. Other parameters get set up to represent oscillating ring with mode imode (1 or 2). All geometric data is pinned by default.
       : PseudoBucklingRing(eps_buckl, HoR, n_buckl, imode, time_stepper_pt),
         External_reference_pressure_pt(0)
     {
       // Geom data for geom object has been setup (and pinned) in
       // constructor for geometric object. Now free the scale for the half axes
       // because we want to determine it as an unknown
       Geom_data_pt[0]->unpin(3);
       // Record that the geometric variable is value 3 in the geometric data
       Internal_geometric_variable_index = 3;
       // The geometric data is internal to the element -- this
       // ensures that any unknown pieces of geom_data get global equation
       // numbers. There should only be one piece of internal data
       unsigned n_geom_data = Geom_data_pt.size();
       for (unsigned i = 0; i < n_geom_data; i++)
       {
         add_internal_data(Geom_data_pt[i]);
       }
     }
References oomph::GeneralisedElement::add_internal_data(), oomph::PseudoBucklingRing::Geom_data_pt, i, and Internal_geometric_variable_index.
PseudoBucklingRingElement() [3/3]
oomph::PseudoBucklingRingElement::PseudoBucklingRingElement (const PseudoBucklingRingElement & dummy) delete
Broken copy constructor.
~PseudoBucklingRingElement()
virtual oomph::PseudoBucklingRingElement::~PseudoBucklingRingElement () inline virtual
Destructor: Kill internal data and set to NULL.
     {
       // The GeomElement's GeomData is mirrored in the element's
       // Internal Data and therefore gets wiped in the
       // destructor of GeneralisedElement --> No need to
       // kill it in PseudoBucklingRing()
       Must_clean_up = false;
     }
References oomph::PseudoBucklingRing::Must_clean_up.
Member Function Documentation
geometric_local_eqn()
int oomph::PseudoBucklingRingElement::geometric_local_eqn () inline private
Return the local equation number of the internal geometric variable.
     {
       return internal_local_eqn(0, Internal_geometric_variable_index);
     }
References Internal_geometric_variable_index, and oomph::GeneralisedElement::internal_local_eqn().
Referenced by get_residuals_generic().
get_jacobian()
virtual void oomph::PseudoBucklingRingElement::get_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline virtual
Compute element residual Vector and element Jacobian matrix (wrapper)
Reimplemented from oomph::GeneralisedElement.
     {
       // Call the generic routine with the flag set to 1
       get_residuals_generic(residuals, jacobian, 1);
     }
References get_residuals_generic().
get_residuals()
virtual void oomph::PseudoBucklingRingElement::get_residuals (Vector< double > & residuals) inline virtual
Compute element residual Vector (wrapper)
Reimplemented from oomph::GeneralisedElement.
     {
       // Create a dummy matrix
       DenseMatrix<double> dummy(1);
       // Call the generic residuals function with flag set to 0
       get_residuals_generic(residuals, dummy, 0);
     }
References get_residuals_generic().
get_residuals_generic()
virtual void oomph::PseudoBucklingRingElement::get_residuals_generic (Vector< double > & residuals, DenseMatrix< double > & jacobian, unsigned flag) inline protected virtual
Compute element residual Vector (only if flag=0) and also element Jacobian matrix (if flag=1)
     {
       // Initialise the residuals to zero
       residuals.initialise(0.0);
       // If computing the Jacobian initialise to zero
       if (flag)
       {
         jacobian.initialise(0.0);
       }
       // There is only one equation, which is due to the internal degree
       // of freedom
       int local_eqn = geometric_local_eqn();
       // If it's not a boundary condition
       if (local_eqn >= 0)
       {
         // Pseudo force balance
         residuals[local_eqn] = reference_pressure() - (r_0() - 1.0);
         // Work out jacobian: d residual[0]/d r_0
         if (flag)
         {
           // The derivative wrt the internal unknown is
           // Derivative residual w.r.t. scale
           jacobian(local_eqn, local_eqn) = -1.0;
           int local_unknown = reference_pressure_local_eqn();
           if (local_unknown >= 0)
           {
             jacobian(local_eqn, local_unknown) = 1.0;
           }
         }
       }
     }
References geometric_local_eqn(), oomph::Vector< _Tp >::initialise(), oomph::DenseMatrix< T >::initialise(), oomph::PseudoBucklingRing::r_0(), reference_pressure(), and reference_pressure_local_eqn().
Referenced by get_jacobian(), and get_residuals().
operator=()
void oomph::PseudoBucklingRingElement::operator= (const PseudoBucklingRingElement &) delete
Broken assignment operator.
reference_pressure()
double oomph::PseudoBucklingRingElement::reference_pressure () const inline
Return the reference pressure.
     {
       // If there is no external pressure, return 0.0
       if (External_reference_pressure_pt == 0)
       {
         return 0.0;
       }
       else
       {
         return External_reference_pressure_pt->value(0);
       }
     }
References External_reference_pressure_pt, and oomph::Data::value().
Referenced by get_residuals_generic().
reference_pressure_local_eqn()
int oomph::PseudoBucklingRingElement::reference_pressure_local_eqn () inline private
Return the local equation number of the reference pressure variable.
     {
       return external_local_eqn(External_reference_pressure_index, 0);
     }
References oomph::GeneralisedElement::external_local_eqn(), and External_reference_pressure_index.
Referenced by get_residuals_generic().
reference_pressure_pt()
Data* const& oomph::PseudoBucklingRingElement::reference_pressure_pt () const inline
Pointer to pressure data that is used as reference pressure.
     {
       return external_data_pt(0);
     }
References oomph::GeneralisedElement::external_data_pt().
set_reference_pressure_pt()
void oomph::PseudoBucklingRingElement::set_reference_pressure_pt (Data *const & data_pt) inline
Set the pressure data that is used as reference pressure.
     {
       // Clear the existing external data, if there is any
       flush_external_data(External_reference_pressure_pt);
       // Set the new External reference pointer
       External_reference_pressure_pt = data_pt;
       // Add it to the external data
       External_reference_pressure_index = add_external_data(data_pt);
     }
References oomph::GeneralisedElement::add_external_data(), External_reference_pressure_index, External_reference_pressure_pt, and oomph::GeneralisedElement::flush_external_data().
Member Data Documentation
External_reference_pressure_index
unsigned oomph::PseudoBucklingRingElement::External_reference_pressure_index private
The Data object that represents the reference pressure is stored at the location indexed by this integer in the external data storage.
Referenced by reference_pressure_local_eqn(), and set_reference_pressure_pt().
External_reference_pressure_pt
Data* oomph::PseudoBucklingRingElement::External_reference_pressure_pt private
Pointer to the data object that represents the external reference pressure
Referenced by reference_pressure(), and set_reference_pressure_pt().
Internal_geometric_variable_index
unsigned oomph::PseudoBucklingRingElement::Internal_geometric_variable_index private
Index of the value stored in the single geometric object that has become an unknown
Referenced by geometric_local_eqn(), and PseudoBucklingRingElement().
The documentation for this class was generated from the following file:
pseudo_buckling_ring.h