MercuryDPM: FiveParticles.cpp File Reference
FiveParticles.cpp File Reference
#include <Mercury3D.h>
#include <Species/LinearViscoelasticSlidingFrictionSpecies.h>
Classes
class FiveParticles
[FP:headers]
Functions
int main (int argc, char *argv[])
[FP:class]
Function Documentation
main()
int main (int argc , char * argv[])
[FP:class]
[FP:main]
 {
     //instantiate the class
     FiveParticles fiveParticles;
     //set name
     fiveParticles.setName("FiveParticles");
     //set output and time stepping properties
     fiveParticles.setTimeMax(20); //run until the situation is static
     fiveParticles.setSaveCount(std::numeric_limits<unsigned >::max()); //save only the first and last time step
     //solve
     fiveParticles.solve(argc,argv);
     logger(INFO,"Execute 'source FiveParticles.sh' to get coarse-grained statistics of the last time step");
     helpers::writeToFile("FiveParticles.sh","../MercuryCG/fstatistics FiveParticles -stattype XZ -w 0.1 -h 0.05 -tmin 1 -tmax 30");
     logger(INFO,"Run 'FiveParticles.m' in MATLAB/octave to visualise the statistical output");
     helpers::writeToFile("FiveParticles.m","addpath('../../MercuryCG/')\n"
      "data = loadstatistics('FiveParticles.stat');\n"
      "colormap(1-gray)\n"
      "contourf(data.x,data.z,data.Density,20,'EdgeColor','none')\n"
      "c = colorbar\n"
      "c.Label.String = '\\rho';\n"
      "title('Density')\n"
      "xlabel('x')\n"
      "ylabel('z');\n"
      "axis equal\n"
      "%%\n"
      "particles=importdata('FiveParticles.data',' ',12);\n"
      "x=particles.data(:,1);\n"
      "z=particles.data(:,3);\n"
      "r=particles.data(:,7);\n"
      "a=linspace(0,2*pi,40);\n"
      "xCircle = sin(a);\n"
      "zCircle = cos(a);\n"
      "hold on;\n"
      "for i=1:length(x)\n"
      "  plot(x(i)+r(i)*xCircle,z(i)+r(i)*zCircle,'Color',.8*[1 1 1])\n"
      "end\n"
      "hold off");
 }
References INFO, logger, max, DPMBase::setName(), DPMBase::setSaveCount(), DPMBase::setTimeMax(), DPMBase::solve(), and helpers::writeToFile().