MercuryDPM: acoustic_fsi.cc File Reference
acoustic_fsi.cc File Reference
#include "generic.h"
#include "helmholtz.h"
#include "time_harmonic_linear_elasticity.h"
#include "multi_physics.h"
#include "meshes/annular_mesh.h"
Classes
class CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >
Coated disk FSI.
Namespaces
Global_Parameters
Namespace for global parameters.
Functions
TimeHarmonicIsotropicElasticityTensor Global_Parameters::E (Nu)
The elasticity tensor for the solid.
void Global_Parameters::update_parameter_values ()
Function to update dependent parameter values.
void Global_Parameters::solid_boundary_displacement (const Vector< double > &x, Vector< std::complex< double > > &u)
Displacement field on inner boundary of solid.
std::complex< double > Global_Parameters::HankelH1 (const double &k, const double &x)
Interface to Hankel function in maple style.
std::complex< double > Global_Parameters::axisym_coefficient ()
void Global_Parameters::exact_axisym_potential (const Vector< double > &x, Vector< double > &soln)
Exact solution for Helmholtz potential for axisymmetric solution.
double Global_Parameters::exact_axisym_radiated_power ()
Exact radiated power for axisymmetric solution.
int main (int argc, char **argv)
Driver for acoustic fsi problem.
Variables
double Global_Parameters::K_squared =10.0
Square of wavenumber for the Helmholtz equation.
double Global_Parameters::Outer_radius =4.0
Radius of outer boundary of Helmholtz domain.
double Global_Parameters::Q =0.0
FSI parameter.
double Global_Parameters::H_coating =0.3
Non-dim thickness of elastic coating.
double Global_Parameters::Density_ratio =0.0
Density ratio: solid to fluid.
unsigned Global_Parameters::N =0
string Global_Parameters::Directory ="RESLT"
Output directory.
unsigned Global_Parameters::El_multiplier =1
Multiplier for number of elements.
Function Documentation
main()
int main (int argc , char ** argv)
Driver for acoustic fsi problem.
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Define possible command line arguments and parse the ones that
  // were actually specified
  // Output directory
  CommandLineArgs::specify_command_line_flag("--dir",
                                             &Global_Parameters::Directory);
  // Azimuthal wavenumber of forcing
  CommandLineArgs::specify_command_line_flag("--n",&Global_Parameters::N);
  // Minimum refinement level
  CommandLineArgs::specify_command_line_flag("--el_multiplier",
                             &Global_Parameters::El_multiplier);
  // Outer radius of Helmholtz domain
  CommandLineArgs::specify_command_line_flag("--outer_radius",
                             &Global_Parameters::Outer_radius);
  // Number of steps in parameter study
  unsigned nstep=2;
  CommandLineArgs::specify_command_line_flag("--nstep",&nstep);
  // Increment in FSI parameter in parameter study
  double q_increment=5.0;
  CommandLineArgs::specify_command_line_flag("--q_increment",&q_increment);
  // Max. number of adaptations
  unsigned max_adapt=3;
  CommandLineArgs::specify_command_line_flag("--max_adapt",&max_adapt);
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  //Set up the problem
  CoatedDiskProblem<RefineableQTimeHarmonicLinearElasticityElement<2,3>,
                    RefineableQHelmholtzElement<2,3> > problem;
  // Initial values for parameter values
  Global_Parameters::Q=0.0;
  Global_Parameters::update_parameter_values();
  //Parameter incrementation
  for(unsigned i=0;i<nstep;i++)
   {
    // Solve the problem with Newton's method, allowing
    // up to max_adapt mesh adaptations after every solve.
    problem.newton_solve(max_adapt);
    // Doc solution
    problem.doc_solution();
    // Increment FSI parameter
    Global_Parameters::Q+=q_increment;
    Global_Parameters::update_parameter_values();
   }
 } //end of main
References Global_Parameters::Directory, oomph::CommandLineArgs::doc_specified_flags(), Global_Parameters::El_multiplier, i, Global_Parameters::N, Global_Parameters::Outer_radius, oomph::CommandLineArgs::parse_and_assign(), problem, Global_Parameters::Q, Flag_definition::setup(), oomph::CommandLineArgs::specify_command_line_flag(), and Global_Parameters::update_parameter_values().