MercuryDPM: Detail::VTKPointDescriptorEntry< T > Class Template Reference
Detail::VTKPointDescriptorEntry< T > Class Template Reference abstract
#include <VTKData.h>
Public Member Functions
VTKPointDescriptorEntry (std::string fieldName)
initialises this data member with given name.
virtual ~VTKPointDescriptorEntry ()
virtual void emit (std::ostream &out, const T &t) const =0
writes this VTKData to the given output stream for a single T
virtual std::string getTypeName () const =0
Gives the VTKDataType for VTK.
std::string getName () const
Returns the name associated with this field.
virtual std::size_t getNumberOfComponents () const =0
Returns the number of components in this type.
Private Attributes
std::string name_
Detailed Description
template<typename T>
class Detail::VTKPointDescriptorEntry< T >
Type-erased Internal storage class for a single datamember.
Constructor & Destructor Documentation
VTKPointDescriptorEntry()
template<typename T > Detail::VTKPointDescriptorEntry< T >::VTKPointDescriptorEntry (std::string fieldName) inline
initialises this data member with given name.
Parameters
fieldName Name of the VTK output field
         : name_(fieldName)
       {
       }
~VTKPointDescriptorEntry()
template<typename T > virtual Detail::VTKPointDescriptorEntry< T >::~VTKPointDescriptorEntry () inline virtual
       {
       }
Member Function Documentation
emit()
template<typename T > virtual void Detail::VTKPointDescriptorEntry< T >::emit (std::ostream & out, const T & t) const pure virtual
writes this VTKData to the given output stream for a single T
Parameters
out the output stream
t the backing dataobject
Implemented in Detail::VTKPointDescriptorEntryImpl< T, V >.
Referenced by VTKUnstructuredGrid< T >::write().
getName()
template<typename T > std::string Detail::VTKPointDescriptorEntry< T >::getName () const inline
Returns the name associated with this field.
       {
         return name_;
       }
References Detail::VTKPointDescriptorEntry< T >::name_.
Referenced by VTKUnstructuredGrid< T >::write().
getNumberOfComponents()
template<typename T > virtual std::size_t Detail::VTKPointDescriptorEntry< T >::getNumberOfComponents () const pure virtual
Returns the number of components in this type.
Implemented in Detail::VTKPointDescriptorEntryImpl< T, V >.
Referenced by VTKUnstructuredGrid< T >::write().
getTypeName()
template<typename T > virtual std::string Detail::VTKPointDescriptorEntry< T >::getTypeName () const pure virtual
Gives the VTKDataType for VTK.
Returns
the VTK datatype in string format.
Implemented in Detail::VTKPointDescriptorEntryImpl< T, V >.
Referenced by VTKUnstructuredGrid< T >::write().
Member Data Documentation
name_
template<typename T > std::string Detail::VTKPointDescriptorEntry< T >::name_ private
Referenced by Detail::VTKPointDescriptorEntry< T >::getName().
The documentation for this class was generated from the following file:
Tools/VTKData.h