MercuryDPM: vmtk_fluid.cc File Reference
vmtk_fluid.cc File Reference
#include "generic.h"
#include "constitutive.h"
#include "navier_stokes.h"
#include "meshes/tetgen_mesh.h"
Classes
class UnstructuredFluidProblem< ELEMENT >
Unstructured Navier-Stokes ALE Problem.
Namespaces
Global_Parameters
Namespace for global parameters.
Functions
int main (int argc, char **argv)
Demonstrate how to solve an unstructured 3D fluids problem.
Function Documentation
main()
int main (int argc , char ** argv)
Demonstrate how to solve an unstructured 3D fluids problem.
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Label for output
  DocInfo doc_info;
  // Output directory
  doc_info.set_directory("RESLT");
  //Set up the problem
  UnstructuredFluidProblem<TTaylorHoodElement<3> > problem;
  //Output initial guess
  problem.doc_solution(doc_info);
  doc_info.number()++;
  // Parameter study
  double Re_increment=100.0;
  unsigned nstep=2;
  // Parameter study: Crank up the pressure drop along the vessel
  for (unsigned istep=0;istep<nstep;istep++)
   {
    // Solve the problem
    problem.newton_solve();
    //Output solution
    problem.doc_solution(doc_info);
    doc_info.number()++;
    // Bump up Reynolds number (equivalent to increasing the imposed pressure
    // drop)
    Global_Parameters::Re+=Re_increment;
   }
 } // end_of_main
References oomph::DocInfo::number(), problem, Global_Parameters::Re, oomph::DocInfo::set_directory(), and Flag_definition::setup().