MercuryDPM: hstop_restart.cpp File Reference
hstop_restart.cpp File Reference
#include "SilbertPeriodic.h"
Classes
class SilbertHstop
Functions
bool PointIsAboveCurve (Mdouble h, Mdouble a, int study_num)
void HstopCurve (int study_num, Mdouble h, Mdouble a)
int main (int argc, char *argv[])
Variables
fstream ReportFile
Function Documentation
HstopCurve()
void HstopCurve (int study_num, Mdouble h, Mdouble a)
 {
     cout << "restart at study_num=" << study_num << ", h=" << h << ", a=" << a << endl;
     Mdouble hMax = 60; //height at which bisection algorithm stops
     Mdouble dh = 2; //how much I decrease the height after a point is found
     Mdouble da = .5; // how exact I want the angle to be determined
     stringstream name;
     name << "Report" << study_num;
     ReportFile.open(name.str().c_str(),fstream::out);
     ReportFile << "height\tangle\tlambda\tmu\tabovemuBottom\tabove\n";
     //now increase height gradually; decrease angle if flow starts
     for (; h<hMax; h+=dh) while (PointIsAboveCurve(h,a,study_num)) a-=da;
     ReportFile.close();
     return;
 }
References a, plotDoE::name, out(), PointIsAboveCurve(), and ReportFile.
Referenced by main().
main()
int main (int argc , char * argv[])
 {
     if (argc>3)
         HstopCurve(atoi(argv[1]),atof(argv[2]),atof(argv[3]));
     else exit(-1);
 }
References HstopCurve().
PointIsAboveCurve()
bool PointIsAboveCurve (Mdouble h, Mdouble a, int study_num)
{
     SilbertHstop problem;
     problem.setInflowHeight(h) ;
     problem.setChuteAngle(a);
     problem.set_study(study_num);
     stringstream name;
     name << "H" << problem.getInflowHeight()
          << "A" << problem.getChuteAngleDegrees()
          << "L" << round(100.*problem.getFixedParticleRadius()*2.)/100.
          << "M" << problem.getSlidingFrictionCoefficient()
          << "B" << problem.getSlidingFrictionCoefficientBottom();
     problem.setName(name.str().c_str());
     cout << "starting " << name.str().c_str() << endl;
     problem.solve();
     stringstream com;
     ReportFile   << problem.getInflowHeight()
          << "\t" << problem.getChuteAngleDegrees()
          << "\t" << round(100.*problem.getFixedParticleRadius()*2.)/100.
          << "\t" << problem.getSlidingFrictionCoefficient()
          << "\t" << problem.getSlidingFrictionCoefficientBottom()
          << "\t" << problem.pointIsAboveCurve
          << endl;
     return problem.pointIsAboveCurve;
 }
References a, plotDoE::name, problem, ReportFile, and Eigen::bfloat16_impl::round().
Referenced by HstopCurve().
Variable Documentation
ReportFile
fstream ReportFile
Referenced by HstopCurve(), and PointIsAboveCurve().