MercuryDPM: fish_domain.cc File Reference
fish_domain.cc File Reference
#include "generic.h"
#include "meshes/fish_domain.h"
Classes
class UnitCircle
Functions
int main ()
Function Documentation
main()
int main ()
Driver code for mucking around with GeomObjects, MacroElements and domains
 {
  // Play around with a GeomObject
  //------------------------------
  // Create a unit circle
  UnitCircle unit_circle;
  // Plot:
  ofstream circle_file("unit_circle.dat");
  // Number of plot points
  unsigned nplot=50;
  // 1D vector for the Lagrangian coordinate
  Vector<double> s(1);
  // 2D vector for the Eulerian position
  Vector<double> r(2);
  for (unsigned i=0;i<nplot;i++)
   {
    // Lagrangian coordinate at plot point
    s[0]=2.0*MathematicalConstants::Pi*double(i)/double(nplot-1);
    // Get Eulerian position vector from GeomObject:
    unit_circle.position(s,r);
    // Plot
    circle_file << r[0] << " " << r[1] << std::endl;
   }
  // Close output file
  circle_file.close();
  // Build a FishDomain and plot it
  //-------------------------------
  // Create the fish's back as a circle of radius 1, centred at (0.5,0.0)
  double x_c=0.5;
  double y_c=0.0;
  double r_back=1.0;
  GeomObject* back_pt=new Circle(x_c,y_c,r_back);
  // Start and end coordinates of the fish back
  double s_nose=2.6;
  double s_tail=0.4;
  // Create the domain
  Domain* domain_pt=new FishDomain(back_pt,s_nose,s_tail);
  // Plot the domain
  // Number of plot points in each coordinate direction.
  unsigned npts=10;
  // Output domain (= plot its macro elements) and the macro element boundaries
  ofstream domain_file("fish_domain.dat");
  domain_pt->output(domain_file,npts);
  domain_pt->output_macro_element_boundaries(domain_file,npts);
  domain_file.close();
 }
References i, oomph::Domain::output(), oomph::Domain::output_macro_element_boundaries(), BiharmonicTestFunctions2::Pi, UnitCircle::position(), UniformPSDSelfTest::r, and s.