MercuryDPM: BaseCG Class Reference
BaseCG Class Reference abstract
Base class of all CG objects, needed to store the various CG objects in the CGHandler.
#include <BaseCG.h>
Public Member Functions
BaseCG ()
Simple constructor, sets default values.
BaseCG (const BaseCG &p)=default
Default copy constructor, copies all values.
~BaseCG () override=default
Default destructor, does nothing.
void read (std::istream &is) override
Currently, no read functions are implemented for the CGHandler, but the function is required for any derivative of BaseObject.
void write (std::ostream &os) const override
Writes class content into an output stream, usually a stat file.
void clear ()
This class seems to have no use (?), but is required for any derivative of BaseObject.
virtual BaseCG * copy () const =0
Copy operator. Required for BaseHandler::copyAndAddObject.
virtual void initialise ()=0
Called at the beginning of the DPM simulation to initialise the cg evaluation and to open the statFile.
virtual void evaluate ()=0
Called after a given number of time steps (statFile::saveCount_) to evaluate the CG fields.
virtual void finish ()=0
Called at the end of the DPM simulation to finish the cg evaluation and to close the statFile.
void setHandler (CGHandler *handler)
Sets handler_, the pointer to the CGHandler.
CGHandler * getHandler () const
Returns handler_, a pointer to the CGHandler.
virtual void setWidth (Mdouble width)=0
Sets width_, the coarse-graining width.
virtual Mdouble getWidth () const =0
Returns width_, the coarse-graining width.
void setNZ (std::size_t nZ)
Sets nZ_, the number of spatial mesh points in the z-direction.
std::size_t getNZ () const
Returns nZ_, the number of spatial mesh points in the z-direction.
void setNY (std::size_t nY)
Sets nY_, the number of spatial mesh points in the y-direction.
std::size_t getNY () const
Returns nY_, the number of spatial mesh points in the y-direction.
void setNX (std::size_t nX)
Sets nX_, the number of spatial mesh points in the x-direction.
std::size_t getNX () const
Returns nX_, the number of spatial mesh points in the x-direction.
void setN (std::size_t n)
Sets nX_, nY_, nZ_, the number of spatial mesh points in each cartesian direction.
void setN (std::array< std::size_t, 3 > n)
Sets nX_, nY_, nZ_, the number of spatial mesh points in each cartesian direction.
void setH (Mdouble h)
Sets nX_, nY_, nZ_, the number of spatial mesh points in each cartesian direction. However, instead of explicitly defining n, the mesh size h=(max-min)/n is defined.
void setHX (Mdouble h)
Sets nX_ the number of spatial mesh points in the X-direction. Instead of explicitly defining nX, the mesh size hX=(max.X-min.X)/nX is defined.
void setHY (Mdouble h)
Sets nX_ the number of spatial mesh points in the X-direction. Instead of explicitly defining nX, the mesh size hX=(max.X-min.X)/nX is defined.
void setHZ (Mdouble h)
Sets nX_ the number of spatial mesh points in the X-direction. Instead of explicitly defining nX, the mesh size hX=(max.X-min.X)/nX is defined.
void setTimeMin (Mdouble timeMin)
Sets timeMin_, the lower limit of the temporal domain.
void setTimeMax (Mdouble timeMax)
Sets timeMax_, the upper limit of the temporal domain.
Mdouble getTimeMin () const
Returns timeMin_, the lower limit of the temporal domain.
Mdouble getTimeMax () const
Returns timeMax_, the upper limit of the temporal domain.
void setMin (Vec3D min)
Sets max_, the lower limit of the spatial domain.
void setX (Mdouble min, Mdouble max)
Sets min_.X, max_.X, the limits of the spatial domain in X.
void setY (Mdouble min, Mdouble max)
Sets min_.Y, max_.Y, the limits of the spatial domain in Y.
void setZ (Mdouble min, Mdouble max)
Sets min_.Z, max_.Z, the limits of the spatial domain in Z.
void setXGrid (Mdouble min, Mdouble max, Mdouble h)
void setYGrid (Mdouble min, Mdouble max, Mdouble h)
void setZGrid (Mdouble min, Mdouble max, Mdouble h)
void setGrid (Vec3D min, Vec3D max, Mdouble h)
void setMax (Vec3D max)
Sets max_, the upper limit of the spatial domain.
Vec3D getMin () const
Returns min_, the lower limit of the spatial domain.
Vec3D getMax () const
Returns max_, the upper limit of the spatial domain.
void selectSpecies (unsigned speciesIndex)
void setSelectedParticle (const std::function< const bool(const BaseInteractable *)> &selectedParticle)
void setEps (Mdouble eps)
Mdouble getEps () const
void setAverageBeyondDomain (const bool val)
bool getAverageBeyondDomain () const
void setVerbose (const bool verbose)
bool getVerbose () const
virtual void setWidthTime (Mdouble widthTime)
virtual Mdouble getWidthTime () const
virtual void setTimeStep (Mdouble timeStep)
virtual Mdouble getTimeStep () const
virtual void setStandardDeviation (Mdouble std)=0
virtual void setRadius (Mdouble radius)=0
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual std::string getName () const =0
A purely virtual function.
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Public Attributes
File statFile
File class to handle the output into a .stat file.
Protected Attributes
CGHandler * handler_
std::size_t nX_
std::size_t nY_
std::size_t nZ_
Mdouble eps_
Mdouble timeMin_
Mdouble timeMax_
Vec3D min_
Vec3D max_
std::function< bool(const BaseInteractable *)> selectedParticle_
bool averageBeyondDomain_ = true
Determines whether particles outside the domain are considered when computing the averaged fields.
bool verbose_ = false
Detailed Description
Base class of all CG objects, needed to store the various CG objects in the CGHandler.
The CGHandler contains a set of BaseCG* pointers, which can contain different CG objects.
This class contains properties that any CG class needs:
a pointer to a handler_ object with set and get functions
the variables and functionality inherited from BaseObject
initialize, evaluate, and finalize functions called by the CGHandler
parameters that specify the options to initialize the mesh of CGPoints (min_, max_, nX_, nY_, nZ_) and properties of the CGFunction (width_)
parameters that specify when evaluate will be called (timeMin_, timeMax_)
the statFile into which statistical output is written.
Constructor & Destructor Documentation
BaseCG() [1/2]
BaseCG::BaseCG ()
Simple constructor, sets default values.
 {
     handler_ = nullptr;
     statFile.getFstream().precision(8);
     statFile.getFstream().setf(std::ios::left);
     statFile.setLastSavedTimeStep(NEVER);
     nX_ = 1;
     nY_ = 1;
     nZ_ = 1;
     timeMin_ = -constants::inf;
     timeMax_ = constants::inf;
     min_ = Vec3D(-constants::inf, -constants::inf, -constants::inf);
     max_ = Vec3D(constants::inf, constants::inf, constants::inf);
     selectedParticle_ = [](const BaseInteractable* p) { return true; };
     logger(DEBUG, "BaseCG::BaseCG() finished");
 }
References DEBUG, File::getFstream(), handler_, constants::inf, logger, max_, min_, NEVER, nX_, nY_, nZ_, p, selectedParticle_, File::setLastSavedTimeStep(), statFile, timeMax_, and timeMin_.
BaseCG() [2/2]
BaseCG::BaseCG (const BaseCG & p) default
Default copy constructor, copies all values.
~BaseCG()
BaseCG::~BaseCG () override default
Default destructor, does nothing.
Member Function Documentation
clear()
void BaseCG::clear ()
This class seems to have no use (?), but is required for any derivative of BaseObject.
 {
     logger(WARN, "BaseCG::clear(), this function shouldn't be called");
 }
References logger, and WARN.
copy()
virtual BaseCG* BaseCG::copy () const pure virtual
Copy operator. Required for BaseHandler::copyAndAddObject.
Implemented in TimeSmoothedCG< Coordinates, BaseFunction, Fields >, TimeAveragedCGXYZ< BaseFunction, Fields >, TimeAveragedCGXYZ< BaseFunction, CGFields::StandardFields >, TimeAveragedCG< Coordinates, BaseFunction, Fields >, TimeAveragedCG< CGCoordinates::XYZ, BaseFunction, CGFields::StandardFields >, CG< Coordinates, BaseFunction, Fields >, CG< Coordinates, CGFunctions::Lucy, CGFields::StandardFields >, CG< CGCoordinates::O, CGFunctions::Lucy, CGFields::StandardFields >, and TimeAveragedLebedevCG< BaseFunction, Fields >.
evaluate()
virtual void BaseCG::evaluate () pure virtual
Called after a given number of time steps (statFile::saveCount_) to evaluate the CG fields.
Implemented in TimeSmoothedCG< Coordinates, BaseFunction, Fields >, TimeAveragedCG< Coordinates, BaseFunction, Fields >, TimeAveragedCG< CGCoordinates::XYZ, BaseFunction, CGFields::StandardFields >, CG< Coordinates, BaseFunction, Fields >, CG< Coordinates, CGFunctions::Lucy, CGFields::StandardFields >, CG< CGCoordinates::O, CGFunctions::Lucy, CGFields::StandardFields >, and TimeAveragedLebedevCG< BaseFunction, Fields >.
Referenced by CGHandler::evaluate().
finish()
virtual void BaseCG::finish () pure virtual
Called at the end of the DPM simulation to finish the cg evaluation and to close the statFile.
Implemented in TimeSmoothedCG< Coordinates, BaseFunction, Fields >, TimeAveragedCG< Coordinates, BaseFunction, Fields >, TimeAveragedCG< CGCoordinates::XYZ, BaseFunction, CGFields::StandardFields >, CG< Coordinates, BaseFunction, Fields >, CG< Coordinates, CGFunctions::Lucy, CGFields::StandardFields >, and CG< CGCoordinates::O, CGFunctions::Lucy, CGFields::StandardFields >.
Referenced by CGHandler::finish().
getAverageBeyondDomain()
bool BaseCG::getAverageBeyondDomain () const inline
 {return averageBeyondDomain_;}
References averageBeyondDomain_.
getEps()
Mdouble BaseCG::getEps () const
 {
     return eps_;
 }
References eps_.
Referenced by commandLineCG().
getHandler()
CGHandler * BaseCG::getHandler () const
Returns handler_, a pointer to the CGHandler.
Returns
pointer to the CGHandler
 {
 #ifdef DEBUG_OUTPUT
     if (handler_ == nullptr)
     {
         std::cerr << "error: handler_==0 " << std::endl;
     }
 #endif
     return handler_;
 }
References handler_.
Referenced by CGFields::DisplacementField::setFields().
getMax()
Vec3D BaseCG::getMax () const
Returns max_, the upper limit of the spatial domain.
 {
     return max_;
 }
References max_.
getMin()
Vec3D BaseCG::getMin () const
Returns min_, the lower limit of the spatial domain.
 {
     return min_;
 }
References min_.
getNX()
std::size_t BaseCG::getNX () const
Returns nX_, the number of spatial mesh points in the x-direction.
 {
     return nX_;
 }
References nX_.
Referenced by commandLineCG(), and setHX().
getNY()
std::size_t BaseCG::getNY () const
Returns nY_, the number of spatial mesh points in the y-direction.
 {
     return nY_;
 }
References nY_.
Referenced by commandLineCG(), and setHY().
getNZ()
std::size_t BaseCG::getNZ () const
Returns nZ_, the number of spatial mesh points in the z-direction.
 {
     return nZ_;
 }
References nZ_.
Referenced by commandLineCG(), and setHZ().
getTimeMax()
Mdouble BaseCG::getTimeMax () const
Returns timeMax_, the upper limit of the temporal domain.
 {
     return timeMax_;
 }
References timeMax_.
Referenced by CGHandler::evaluate(), and CGHandler::getTimeMax().
getTimeMin()
Mdouble BaseCG::getTimeMin () const
Returns timeMin_, the lower limit of the temporal domain.
 {
     return timeMin_;
 }
References timeMin_.
Referenced by CGHandler::evaluate(), and CGHandler::getTimeMin().
getTimeStep()
Mdouble BaseCG::getTimeStep () const virtual
Reimplemented in TimeSmoothedCG< Coordinates, BaseFunction, Fields >.
 {
     logger(ERROR, "getTimeStep() should not be used, it is a dummy function for templating");
     return 0;
 }
References ERROR, and logger.
Referenced by commandLineCG().
getVerbose()
bool BaseCG::getVerbose () const inline
 {return verbose_;}
References verbose_.
getWidth()
virtual Mdouble BaseCG::getWidth () const pure virtual
Returns width_, the coarse-graining width.
Implemented in CG< Coordinates, BaseFunction, Fields >, CG< Coordinates, CGFunctions::Lucy, CGFields::StandardFields >, and CG< CGCoordinates::O, CGFunctions::Lucy, CGFields::StandardFields >.
Referenced by commandLineCG(), and write().
getWidthTime()
Mdouble BaseCG::getWidthTime () const virtual
Reimplemented in TimeSmoothedCG< Coordinates, BaseFunction, Fields >.
 {
     logger(ERROR, "getWidthTime() should not be used, it is a dummy function for templating");
     return 0;
 }
References ERROR, and logger.
Referenced by commandLineCG().
initialise()
virtual void BaseCG::initialise () pure virtual
Called at the beginning of the DPM simulation to initialise the cg evaluation and to open the statFile.
Implemented in TimeSmoothedCG< Coordinates, BaseFunction, Fields >, TimeAveragedCG< Coordinates, BaseFunction, Fields >, TimeAveragedCG< CGCoordinates::XYZ, BaseFunction, CGFields::StandardFields >, CG< Coordinates, BaseFunction, Fields >, CG< Coordinates, CGFunctions::Lucy, CGFields::StandardFields >, and CG< CGCoordinates::O, CGFunctions::Lucy, CGFields::StandardFields >.
Referenced by CGHandler::initialise().
read()
void BaseCG::read (std::istream & is) override virtual
Currently, no read functions are implemented for the CGHandler, but the function is required for any derivative of BaseObject.
Implements BaseObject.
 {
 }
selectSpecies()
void BaseCG::selectSpecies (unsigned speciesIndex)
sets selectedParticle_ such that only particles of a certain species are selected
Parameters
speciesIndex
 {
     selectedParticle_ = [speciesIndex](const BaseInteractable* p)
     {
         return p->getIndSpecies() == speciesIndex;
     };
 }
References p, and selectedParticle_.
Referenced by commandLineCG().
setAverageBeyondDomain()
void BaseCG::setAverageBeyondDomain (const bool val) inline
 {averageBeyondDomain_=val;}
References averageBeyondDomain_, and calibrate::val.
Referenced by commandLineCG().
setEps()
void BaseCG::setEps (Mdouble eps)
 {
     eps_ = eps;
 }
References CRBond_Bessel::eps, and eps_.
Referenced by commandLineCG().
setGrid()
void BaseCG::setGrid (Vec3D min, Vec3D max, Mdouble h)
 {
     setMin(min);
     setMax(max);
     setH(h);
 }
References max, min, setH(), setMax(), and setMin().
setH()
void BaseCG::setH (Mdouble h)
Sets nX_, nY_, nZ_, the number of spatial mesh points in each cartesian direction. However, instead of explicitly defining n, the mesh size h=(max-min)/n is defined.
 {
     setHX(h);
     setHY(h);
     setHZ(h);
     logger(INFO, "min % max % h % nz %", min_, max_, h, nZ_);
 }
References INFO, logger, max_, min_, nZ_, setHX(), setHY(), and setHZ().
Referenced by commandLineCG(), and setGrid().
setHandler()
void BaseCG::setHandler (CGHandler * handler)
Sets handler_, the pointer to the CGHandler.
 {
     handler_ = handler;
 }
References handler_.
Referenced by CGHandler::addObject().
setHX()
void BaseCG::setHX (Mdouble h)
Sets nX_ the number of spatial mesh points in the X-direction. Instead of explicitly defining nX, the mesh size hX=(max.X-min.X)/nX is defined.
 {
     logger.assert_debug(h > 0, "setHX(%): h has to be positive");
     logger.assert_debug(max_.X!=constants::inf && min_.X!=-constants::inf,
                   "setHX(%) can only be used after setting min and max values", h);
     setNX(static_cast<size_t>(std::ceil((max_.X - min_.X) / h)));
     logger.assert_always(getNX() > 0, "setHX(%) generated nX=% for %<x<%", h, getNX(), min_.X, max_.X);
 }
References Eigen::bfloat16_impl::ceil(), getNX(), constants::inf, logger, max_, min_, setNX(), and Vec3D::X.
Referenced by commandLineCG(), setH(), and setXGrid().
setHY()
void BaseCG::setHY (Mdouble h)
Sets nX_ the number of spatial mesh points in the X-direction. Instead of explicitly defining nX, the mesh size hX=(max.X-min.X)/nX is defined.
 {
     logger.assert_debug(h > 0, "setHY(%): h has to be positive");
     logger.assert_debug(max_.Y!=constants::inf && min_.Y!=-constants::inf,
                   "setHY(%) can only be used after setting min and max values", h);
     setNY(static_cast<size_t>(std::ceil((max_.Y - min_.Y) / h)));
     logger.assert_always(getNY() > 0, "setHY(%) generated nY=% for %<y<%", h, getNY(), min_.Y, max_.Y);
 }
References Eigen::bfloat16_impl::ceil(), getNY(), constants::inf, logger, max_, min_, setNY(), and Vec3D::Y.
Referenced by commandLineCG(), setH(), and setYGrid().
setHZ()
void BaseCG::setHZ (Mdouble h)
Sets nX_ the number of spatial mesh points in the X-direction. Instead of explicitly defining nX, the mesh size hX=(max.X-min.X)/nX is defined.
 {
     logger.assert_debug(h > 0, "setHZ(%): h has to be positive");
     logger.assert_debug(max_.Z!=constants::inf && min_.Z!=-constants::inf,
                   "setHZ(%) can only be used after setting min and max values", h);
     setNZ(static_cast<size_t>(std::ceil((max_.Z - min_.Z) / h)));
     logger.assert_always(getNZ() > 0, "setHZ(%) generated nZ=% for %<z<%", h, getNZ(), min_.Z, max_.Z);
 }
References Eigen::bfloat16_impl::ceil(), getNZ(), constants::inf, logger, max_, min_, setNZ(), and Vec3D::Z.
Referenced by commandLineCG(), setH(), and setZGrid().
setMax()
void BaseCG::setMax (Vec3D max)
Sets max_, the upper limit of the spatial domain.
 {
     max_ = max;
 }
References max, and max_.
Referenced by commandLineCG(), and setGrid().
setMin()
void BaseCG::setMin (Vec3D min)
Sets max_, the lower limit of the spatial domain.
 {
     min_ = min;
 }
References min, and min_.
Referenced by commandLineCG(), and setGrid().
setN() [1/2]
void BaseCG::setN (std::array< std::size_t, 3 > n)
Sets nX_, nY_, nZ_, the number of spatial mesh points in each cartesian direction.
 {
     nX_ = n[0];
     nY_ = n[1];
     nZ_ = n[2];
 }
References n, nX_, nY_, and nZ_.
setN() [2/2]
void BaseCG::setN (std::size_t n)
Sets nX_, nY_, nZ_, the number of spatial mesh points in each cartesian direction.
 {
     nX_ = n;
     nY_ = n;
     nZ_ = n;
 }
References n, nX_, nY_, and nZ_.
Referenced by commandLineCG(), and main().
setNX()
void BaseCG::setNX (std::size_t nX)
Sets nX_, the number of spatial mesh points in the x-direction.
 {
     nX_ = nX;
 }
References nX_.
Referenced by commandLineCG(), main(), and setHX().
setNY()
void BaseCG::setNY (std::size_t nY)
Sets nY_, the number of spatial mesh points in the y-direction.
 {
     nY_ = nY;
 }
References nY_.
Referenced by commandLineCG(), and setHY().
setNZ()
void BaseCG::setNZ (std::size_t nZ)
Sets nZ_, the number of spatial mesh points in the z-direction.
 {
     nZ_ = nZ;
 }
References nZ_.
Referenced by commandLineCG(), main(), setCGHandler(), and setHZ().
setRadius()
virtual void BaseCG::setRadius (Mdouble radius) pure virtual
Implemented in CG< Coordinates, BaseFunction, Fields >, CG< Coordinates, CGFunctions::Lucy, CGFields::StandardFields >, and CG< CGCoordinates::O, CGFunctions::Lucy, CGFields::StandardFields >.
setSelectedParticle()
void BaseCG::setSelectedParticle (const std::function< const bool(const BaseInteractable *)> & selectedParticle)
 {
     selectedParticle_ = selectedParticle;
 }
References selectedParticle_.
setStandardDeviation()
virtual void BaseCG::setStandardDeviation (Mdouble std) pure virtual
Implemented in CG< Coordinates, BaseFunction, Fields >, CG< Coordinates, CGFunctions::Lucy, CGFields::StandardFields >, and CG< CGCoordinates::O, CGFunctions::Lucy, CGFields::StandardFields >.
Referenced by commandLineCG().
setTimeMax()
void BaseCG::setTimeMax (Mdouble timeMax)
Sets timeMax_, the upper limit of the temporal domain.
 {
     timeMax_ = timeMax;
 }
References timeMax_.
Referenced by commandLineCG(), and main().
setTimeMin()
void BaseCG::setTimeMin (Mdouble timeMin)
Sets timeMin_, the lower limit of the temporal domain.
 {
     timeMin_ = timeMin;
 }
References timeMin_.
Referenced by commandLineCG(), and main().
setTimeStep()
void BaseCG::setTimeStep (Mdouble timeStep) virtual
Reimplemented in TimeSmoothedCG< Coordinates, BaseFunction, Fields >.
 {
     logger(ERROR, "setTimeStep() should not be used, it is a dummy function for templating");
 }
References ERROR, and logger.
Referenced by commandLineCG().
setVerbose()
void BaseCG::setVerbose (const bool verbose) inline
 {verbose_=verbose;}
References verbose, and verbose_.
Referenced by commandLineCG().
setWidth()
virtual void BaseCG::setWidth (Mdouble width) pure virtual
Sets width_, the coarse-graining width.
Todo:
should be standard deviation, but is currently cutoff.
Implemented in CG< Coordinates, BaseFunction, Fields >, CG< Coordinates, CGFunctions::Lucy, CGFields::StandardFields >, and CG< CGCoordinates::O, CGFunctions::Lucy, CGFields::StandardFields >.
Referenced by commandLineCG().
setWidthTime()
void BaseCG::setWidthTime (Mdouble widthTime) virtual
Reimplemented in TimeSmoothedCG< Coordinates, BaseFunction, Fields >.
 {
     logger(ERROR, "setWidthTime() should not be used, it is a dummy function for templating");
 }
References ERROR, and logger.
Referenced by commandLineCG().
setX()
void BaseCG::setX (Mdouble min, Mdouble max)
Sets min_.X, max_.X, the limits of the spatial domain in X.
 {
     min_.X = min;
     max_.X = max;
 }
References max, max_, min, min_, and Vec3D::X.
Referenced by commandLineCG(), and setXGrid().
setXGrid()
void BaseCG::setXGrid (Mdouble min, Mdouble max, Mdouble h)
 {
     setX(min,max);
     setHX(h);
 }
References max, min, setHX(), and setX().
setY()
void BaseCG::setY (Mdouble min, Mdouble max)
Sets min_.Y, max_.Y, the limits of the spatial domain in Y.
 {
     min_.Y = min;
     max_.Y = max;
 }
References max, max_, min, min_, and Vec3D::Y.
Referenced by commandLineCG(), and setYGrid().
setYGrid()
void BaseCG::setYGrid (Mdouble min, Mdouble max, Mdouble h)
 {
     setY(min,max);
     setHY(h);
 }
References max, min, setHY(), and setY().
setZ()
void BaseCG::setZ (Mdouble min, Mdouble max)
Sets min_.Z, max_.Z, the limits of the spatial domain in Z.
 {
     min_.Z = min;
     max_.Z = max;
 }
References max, max_, min, min_, and Vec3D::Z.
Referenced by commandLineCG(), and setZGrid().
setZGrid()
void BaseCG::setZGrid (Mdouble min, Mdouble max, Mdouble h)
 {
     setZ(min,max);
     setHZ(h);
 }
References max, min, setHZ(), and setZ().
write()
void BaseCG::write (std::ostream & os) const override virtual
Writes class content into an output stream, usually a stat file.
Parameters
[out] os output stream to which data is written
Implements BaseObject.
Reimplemented in TimeSmoothedCG< Coordinates, BaseFunction, Fields >, TimeAveragedCG< Coordinates, BaseFunction, Fields >, TimeAveragedCG< CGCoordinates::XYZ, BaseFunction, CGFields::StandardFields >, CG< Coordinates, BaseFunction, Fields >, CG< Coordinates, CGFunctions::Lucy, CGFields::StandardFields >, and CG< CGCoordinates::O, CGFunctions::Lucy, CGFields::StandardFields >.
 {
     //BaseObject::write(os);
     os << getName();
     os << " min " << min_;
     os << " max " << max_;
     if (!std::isinf(timeMin_)) os << " timeMin " << timeMin_;
     if (!std::isinf(timeMax_)) os << " timeMax " << timeMax_;
     os << " n " << nX_ << " " << nY_ << " " << nZ_;
     os << " width " << getWidth();
     if (verbose_) os << " verbose 1";
     //statFile
 }
References BaseObject::getName(), getWidth(), isinf, max_, min_, nX_, nY_, nZ_, timeMax_, timeMin_, and verbose_.
Member Data Documentation
averageBeyondDomain_
bool BaseCG::averageBeyondDomain_ = true protected
Determines whether particles outside the domain are considered when computing the averaged fields.
If set to true, then the average of field f over a coordinate direction x is computed as \(\frac{1}{x_{max}-x_{min}}\int_{-\infty}^{\infty} f dx\) If set to false, then the average of field f over a coordinate direction x is computed as \(\frac{1}{x_{max}-x_{min}}\int_{x_{min}}^{x_{max}} f dx\)
Todo:
should the default be false?
currently, the above description is not implemented; it simply ignores particles outside the domain.
Referenced by getAverageBeyondDomain(), and setAverageBeyondDomain().
eps_
Mdouble BaseCG::eps_ protected
Finite difference step size used to computed derivatives of CG functions
Referenced by getEps(), and setEps().
handler_
CGHandler* BaseCG::handler_ protected
the pointer to the CGHandler, used to get data from the CGHandler.
Referenced by BaseCG(), getHandler(), and setHandler().
max_
Vec3D BaseCG::max_ protected
see min_.
Referenced by BaseCG(), getMax(), setH(), setHX(), setHY(), setHZ(), setMax(), setX(), setY(), setZ(), and write().
min_
Vec3D BaseCG::min_ protected
min_ and max_ define the spatial dimensions of the coarse-graining volume; if these parameters are not defined by the user, they are set to the system dimensions (DPMBase::min_ and DPMBase::max_) in CG::initialize.
Referenced by BaseCG(), getMin(), setH(), setHX(), setHY(), setHZ(), setMin(), setX(), setY(), setZ(), and write().
nX_
std::size_t BaseCG::nX_ protected
nX_, nY_, and nZ_ define the size of the mesh of CGPoints, i.e. the spatial positions at which the cg variables are evaluated. nX_, nY_, and nZ_ are the number of points in x-, y-, and z-direction. the is used to set the width of the These values are set to 1 by default, unless modified by the user.
Referenced by BaseCG(), getNX(), setN(), setNX(), and write().
nY_
std::size_t BaseCG::nY_ protected
see nX_
Referenced by BaseCG(), getNY(), setN(), setNY(), and write().
nZ_
std::size_t BaseCG::nZ_ protected
see nZ_
Referenced by BaseCG(), getNZ(), setH(), setN(), setNZ(), and write().
selectedParticle_
std::function<bool(const BaseInteractable*)> BaseCG::selectedParticle_ protected
A function returning true for each particle that should be included in the statistics (all by default).
Referenced by BaseCG(), selectSpecies(), and setSelectedParticle().
statFile
File BaseCG::statFile
File class to handle the output into a .stat file.
Referenced by BaseCG(), commandLineCG(), CGHandler::evaluate(), CGHandler::finish(), main(), and setCGHandler().
timeMax_
Mdouble BaseCG::timeMax_ protected
see timeMin_
Referenced by BaseCG(), getTimeMax(), setTimeMax(), and write().
timeMin_
Mdouble BaseCG::timeMin_ protected
timeMin_ and timeMax_ define the temporal dimensions of the coarse-graining volume; these parameters are set to \(\pm\infty\) by default, unless modified by the user; otherwise, timeMin_ is set to DPMBase::time_ in CG::initialize.
Referenced by BaseCG(), getTimeMin(), setTimeMin(), and write().
verbose_
bool BaseCG::verbose_ = false protected
Referenced by getVerbose(), setVerbose(), and write().
The documentation for this class was generated from the following files:
BaseCG.h
BaseCG.cc