MercuryDPM: oomph::AlgebraicCylinderWithFlagMesh< ELEMENT > Class Template Reference
oomph::AlgebraicCylinderWithFlagMesh< ELEMENT > Class Template Reference
Algebraic version of CylinderWithFlagMesh.
#include <cylinder_with_flag_mesh.template.h>
Public Member Functions
AlgebraicCylinderWithFlagMesh (Circle *cylinder_pt, GeomObject *top_flag_pt, GeomObject *bottom_flag_pt, GeomObject *tip_flag_pt, const double &length, const double &height, const double &flag_length, const double &flag_height, const double &centre_x, const double &centre_y, const double &a, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
virtual ~AlgebraicCylinderWithFlagMesh ()
Destructor: empty.
void set_bottom_flag_pt (GeomObject *bottom_flag_pt)
void set_top_flag_pt (GeomObject *top_flag_pt)
void set_tip_flag_pt (GeomObject *tip_flag_pt)
GeomObject * bottom_flag_pt () const
GeomObject * top_flag_pt () const
GeomObject * tip_flag_pt () const
void update_node_update (AlgebraicNode *&node_pt)
void algebraic_node_update (const unsigned &t, AlgebraicNode *&node_pt)
The algebraic node update function.
Public Member Functions inherited from oomph::AlgebraicMesh
AlgebraicMesh ()
AlgebraicMesh (const AlgebraicMesh &)=delete
Broken copy constructor.
~AlgebraicMesh ()
Broken assignment operator.
AlgebraicNode * node_pt (const unsigned long &n)
Return a pointer to the n-th global AlgebraicNode.
void node_update (const bool &update_all_solid_nodes=false)
unsigned self_test ()
Self test: check consistentency of multiple node updates.
void add_geom_object_list_pt (GeomObject *geom_object_pt)
unsigned ngeom_object_list_pt ()
Return number of geometric objects associated with AlgebraicMesh.
GeomObject * geom_object_list_pt (const unsigned &i)
Access function to the ith GeomObject.
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Public Member Functions inherited from oomph::CylinderWithFlagMesh< ELEMENT >
CylinderWithFlagMesh (Circle *cylinder_pt, GeomObject *top_flag_pt, GeomObject *bottom_flag_pt, GeomObject *tip_flag_pt, const double &length, const double &height, const double &flag_length, const double &flag_height, const double &centre_x, const double &centre_y, const double &a, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
virtual ~CylinderWithFlagMesh ()
Destructor: Kill the domain.
CylinderWithFlagDomain * domain_pt ()
Access function to the domain.
Public Member Functions inherited from oomph::QuadMeshBase
QuadMeshBase ()
Constructor (empty)
QuadMeshBase (const QuadMeshBase &node)=delete
Broken copy constructor.
void operator= (const QuadMeshBase &)=delete
Broken assignment operator.
virtual ~QuadMeshBase ()
Destructor (empty)
void setup_boundary_element_info ()
void setup_boundary_element_info (std::ostream &outfile)
Protected Member Functions
void setup_algebraic_node_update ()
Function to setup the algebraic node update.
void node_update_I (const unsigned &t, AlgebraicNode *&node_pt)
Helper function.
void node_update_II (const unsigned &t, AlgebraicNode *&node_pt)
Helper function.
void node_update_III (const unsigned &t, AlgebraicNode *&node_pt)
Helper function.
void node_update_IV (const unsigned &t, AlgebraicNode *&node_pt)
Helper function.
void node_update_V (const unsigned &t, AlgebraicNode *&node_pt)
Helper function.
void node_update_VI (const unsigned &t, AlgebraicNode *&node_pt)
Helper function.
void node_update_VII (const unsigned &t, AlgebraicNode *&node_pt)
Helper function.
void node_update_VIII (const unsigned &t, AlgebraicNode *&node_pt)
Helper function.
void node_update_IX (const unsigned &t, AlgebraicNode *&node_pt)
Helper function.
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Protected Attributes
GeomObject * Cylinder_pt
Cylinder.
GeomObject * Top_flag_pt
Top flag.
GeomObject * Bottom_flag_pt
Bottom flag.
GeomObject * Tip_flag_pt
Tip flag.
double Length
Length of the domain.
double Height
Height of the domain.
double Flag_length
Flag length.
double Flag_height
Flag thickness.
double Centre_x
x position of the centre of the cylinder
double Centre_y
x position of the centre of the cylinder
double A
radius of the cylinder
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Protected Attributes inherited from oomph::CylinderWithFlagMesh< ELEMENT >
CylinderWithFlagDomain * Domain_pt
Pointer to the domain.
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Detailed Description
template<class ELEMENT>
class oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >
Algebraic version of CylinderWithFlagMesh.
/////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////
Constructor & Destructor Documentation
AlgebraicCylinderWithFlagMesh()
template<class ELEMENT > oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::AlgebraicCylinderWithFlagMesh (Circle * cylinder_pt, GeomObject * top_flag_pt, GeomObject * bottom_flag_pt, GeomObject * tip_flag_pt, const double & length, const double & height, const double & flag_length, const double & flag_height, const double & centre_x, const double & centre_y, const double & a, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) inline
Constructor. Pass the pointers to the GeomObjects that parametrise the cylinder, the three edges of the flag, the length and height of the domain, the length and height of the flag, the coordinates of the centre of the cylinder and its radius. Timestepper defaults to Steady default timestepper.
       : CylinderWithFlagMesh<ELEMENT>(cylinder_pt,
                                       top_flag_pt,
                                       bottom_flag_pt,
                                       tip_flag_pt,
                                       length,
                                       height,
                                       flag_length,
                                       flag_height,
                                       centre_x,
                                       centre_y,
                                       a,
                                       time_stepper_pt),
         Cylinder_pt(cylinder_pt),
         Top_flag_pt(top_flag_pt),
         Bottom_flag_pt(bottom_flag_pt),
         Tip_flag_pt(tip_flag_pt),
         Length(length),
         Height(height),
         Flag_length(flag_length),
         Flag_height(flag_height),
         Centre_x(centre_x),
         Centre_y(centre_y),
         A(a)
     {
       // Add the geometric objects to the list associated with this
       // AlgebraicMesh
       AlgebraicMesh::add_geom_object_list_pt(cylinder_pt);
       AlgebraicMesh::add_geom_object_list_pt(top_flag_pt);
       AlgebraicMesh::add_geom_object_list_pt(bottom_flag_pt);
       AlgebraicMesh::add_geom_object_list_pt(tip_flag_pt);
       // Setup algebraic node update operations
       setup_algebraic_node_update();
     }
References oomph::AlgebraicMesh::add_geom_object_list_pt(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::bottom_flag_pt(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::setup_algebraic_node_update(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::tip_flag_pt(), and oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::top_flag_pt().
~AlgebraicCylinderWithFlagMesh()
template<class ELEMENT > virtual oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::~AlgebraicCylinderWithFlagMesh () inline virtual
Destructor: empty.
 {}
Member Function Documentation
algebraic_node_update()
template<class ELEMENT > void oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::algebraic_node_update (const unsigned & t, AlgebraicNode *& node_pt) virtual
The algebraic node update function.
Update nodal position at time level t (t=0: present; t>0: previous)
Implements oomph::AlgebraicMesh.
   {
     unsigned id = node_pt->node_update_fct_id();
     switch (id)
     {
       case 1:
         node_update_I(t, node_pt);
         break;
       case 2:
         node_update_II(t, node_pt);
         break;
       case 3:
         node_update_III(t, node_pt);
         break;
       case 4:
         node_update_IV(t, node_pt);
         break;
       case 5:
         node_update_V(t, node_pt);
         break;
       case 6:
         node_update_VI(t, node_pt);
         break;
       case 7:
         node_update_VII(t, node_pt);
         break;
       case 8:
         node_update_VIII(t, node_pt);
         break;
       case 9:
         node_update_IX(t, node_pt);
         break;
       default:
         std::ostringstream error_message;
         error_message << "Wrong id " << id << std::endl;
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
     }
   } // end of algebraic_node_update()
References oomph::AlgebraicNode::node_update_fct_id(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and plotPSD::t.
bottom_flag_pt()
template<class ELEMENT > GeomObject* oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::bottom_flag_pt () const inline
Read-only access to geometric object that defines the bottom face of the flag
     {
       return Bottom_flag_pt;
     }
References oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::Bottom_flag_pt.
Referenced by oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::AlgebraicCylinderWithFlagMesh(), and oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::set_bottom_flag_pt().
node_update_I()
template<class ELEMENT > void oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::node_update_I (const unsigned & t, AlgebraicNode *& node_pt) protected
Helper function.
Node update for region I.
   {
     // Extract reference values for update by copy construction
     Vector<double> ref_value(node_pt->vector_ref_value());
     // Extract geometric objects for update by copy construction
     Vector<GeomObject*> geom_object_pt(node_pt->vector_geom_object_pt());
     // Pointer to geom object
     GeomObject* flag_pt = geom_object_pt[0];
     // Point on the line y=p11[1] corresponding to the initial x.
     Vector<double> ref_point(2);
     ref_point[0] = ref_value[4];
     ref_point[1] = 0.778024390 * Height;
     // Point on the flag
     Vector<double> flag_point(2);
     Vector<double> zeta(1);
     zeta[0] = ref_value[3];
     flag_pt->position(t, zeta, flag_point);
     // Third reference value : fraction of the vertical line
     // between the straight line y = p11[1] and the flag
     double r = ref_value[1];
     // Assign new nodal coordinates
     node_pt->x(t, 0) =
       ref_point[0] + (1.0 - r) * (flag_point[0] - ref_point[0]);
     node_pt->x(t, 1) =
       ref_point[1] + (1.0 - r) * (flag_point[1] - ref_point[1]);
   }
References GlobalParameters::Height, oomph::GeomObject::position(), UniformPSDSelfTest::r, plotPSD::t, oomph::AlgebraicNode::vector_geom_object_pt(), oomph::AlgebraicNode::vector_ref_value(), oomph::Node::x(), and Eigen::zeta().
node_update_II()
template<class ELEMENT > void oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::node_update_II (const unsigned & t, AlgebraicNode *& node_pt) protected
Helper function.
Node update for region II.
   {
     // Extract reference values for update by copy construction
     Vector<double> ref_value(node_pt->vector_ref_value());
     // Extract geometric objects for update by copy construction
     Vector<GeomObject*> geom_object_pt(node_pt->vector_geom_object_pt());
     // Pointer to geom object
     GeomObject* flag_pt = geom_object_pt[0];
     // Point on the line y=p37[1] corresponding to the initial x.
     Vector<double> ref_point(2);
     ref_point[0] = ref_value[4];
     ref_point[1] = 0.197585366 * Height;
     // Point on the flag
     Vector<double> flag_point(2);
     Vector<double> zeta(1);
     zeta[0] = ref_value[3];
     flag_pt->position(t, zeta, flag_point);
     // Third reference value : fraction of the vertical line
     // between the straight line y = p11[1] and the flag
     double r = ref_value[1];
     // Assign new nodal coordinates
     node_pt->x(t, 0) = ref_point[0] + r * (flag_point[0] - ref_point[0]);
     node_pt->x(t, 1) = ref_point[1] + r * (flag_point[1] - ref_point[1]);
   }
References GlobalParameters::Height, oomph::GeomObject::position(), UniformPSDSelfTest::r, plotPSD::t, oomph::AlgebraicNode::vector_geom_object_pt(), oomph::AlgebraicNode::vector_ref_value(), oomph::Node::x(), and Eigen::zeta().
node_update_III()
template<class ELEMENT > void oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::node_update_III (const unsigned & t, AlgebraicNode *& node_pt) protected
Helper function.
Node update for region III.
   {
     // useful points
     Vector<double> p15(2);
     Vector<double> p35(2);
     p15[0] = 0.285123967 * Length;
     p15[1] = 0.625 * Height;
     p35[0] = 0.285123967 * Length;
     p35[1] = 0.350609756 * Height;
     // Extract reference values for update by copy construction
     Vector<double> ref_value(node_pt->vector_ref_value());
     // Extract geometric objects for update by copy construction
     Vector<GeomObject*> geom_object_pt(node_pt->vector_geom_object_pt());
     // Pointer to geom object
     GeomObject* flag_pt = geom_object_pt[0];
     // Point on the line x=p15[0]
     Vector<double> ref_point(2);
     ref_point[0] = p15[0];
     ref_point[1] = p35[1] + ref_value[1] * (p15[1] - p35[1]);
     // Point on the flag
     Vector<double> flag_point(2);
     Vector<double> zeta(1);
     zeta[0] = ref_value[3];
     flag_pt->position(t, zeta, flag_point);
     // Third reference value : fraction of the horizontal line
     // between the flag and the horizontal straight line in x=p15[0]
     double r = ref_value[0];
     // Assign new nodal coordinates
     node_pt->x(t, 0) = flag_point[0] + r * (ref_point[0] - flag_point[0]);
     node_pt->x(t, 1) = flag_point[1] + r * (ref_point[1] - flag_point[1]);
   }
References GlobalParameters::Height, Global_Physical_Variables::Length, oomph::GeomObject::position(), UniformPSDSelfTest::r, plotPSD::t, oomph::AlgebraicNode::vector_geom_object_pt(), oomph::AlgebraicNode::vector_ref_value(), oomph::Node::x(), and Eigen::zeta().
node_update_IV()
template<class ELEMENT > void oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::node_update_IV (const unsigned & t, AlgebraicNode *& node_pt) protected
Helper function.
Node update for region IV.
   {
     // Useful points
     Vector<double> p15(2);
     Vector<double> p25(2);
     Vector<double> top_flag(2);
     p15[0] = 0.285123967 * Length;
     p15[1] = 0.625 * Height;
     p25[0] = Centre_x +
              A * sqrt(1.0 - Flag_height * Flag_height / (4.0 * A * A)) +
              Flag_length;
     p25[1] = Centre_y + Flag_height / 2.0;
     // Extract reference values for update by copy construction
     Vector<double> ref_value(node_pt->vector_ref_value());
     // Extract geometric objects for update by copy construction
     Vector<GeomObject*> geom_object_pt(node_pt->vector_geom_object_pt());
     // Pointer to geom object
     GeomObject* flag_pt = geom_object_pt[0];
     Vector<double> zeta(1);
     zeta[0] = ref_value[2];
     flag_pt->position(t, zeta, top_flag);
     // point on the line linking p15 et top_flag
     Vector<double> p1(2);
     p1[0] = top_flag[0] + ref_value[0] * (p15[0] - top_flag[0]);
     p1[1] = top_flag[1] + ref_value[0] * (p15[1] - top_flag[1]);
     // Point on the line y = Height;
     Vector<double> p2(2);
     p2[0] = p25[0] + ref_value[0] * (p15[0] - p25[0]);
     p2[1] = Height;
     // Connect those points with the vertical fraction ref_value[1]
     node_pt->x(t, 0) = p1[0] + ref_value[1] * (p2[0] - p1[0]);
     node_pt->x(t, 1) = p1[1] + ref_value[1] * (p2[1] - p1[1]);
   }
References Global_Parameters::Centre_x, Global_Parameters::Centre_y, GlobalParameters::Height, Global_Physical_Variables::Length, p1, oomph::GeomObject::position(), sqrt(), plotPSD::t, oomph::AlgebraicNode::vector_geom_object_pt(), oomph::AlgebraicNode::vector_ref_value(), oomph::Node::x(), and Eigen::zeta().
node_update_IX()
template<class ELEMENT > void oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::node_update_IX (const unsigned & t, AlgebraicNode *& node_pt) protected
Helper function.
Node update for region IX.
Extreme angles on circle
   {
     // Useful point
     Vector<double> p37(2);
     p37[0] = 0.127596 * Length;
     p37[1] = 0.197585366 * Height;
     double zeta_circle_top = -asin(Flag_height / 2. / A);
     double zeta_circle_bot = -atan(1.0);
     // Extract reference values for update by copy construction
     Vector<double> ref_value(node_pt->vector_ref_value());
     // Extract geometric objects for update by copy construction
     Vector<GeomObject*> geom_object_pt(node_pt->vector_geom_object_pt());
     // Pointer to geom object containing the reference point
     GeomObject* flag_ref_pt = geom_object_pt[0];
     // Pointer to geom object containing the end of macro element
     GeomObject* flag_end_pt = geom_object_pt[1];
     double omega_horizontal = ref_value[0];
     double omega_vertical = ref_value[1];
     // end of the macro element on the flag
     Vector<double> flag_end(2);
     Vector<double> zeta(1);
     zeta[0] = ref_value[5];
     flag_end_pt->position(t, zeta, flag_end);
     Vector<double> outer_point(p37);
     // Get reference point on circle
     Vector<double> ref_point_on_circle(2);
     zeta[0] =
       zeta_circle_bot + (zeta_circle_top - zeta_circle_bot) * omega_vertical;
     Cylinder_pt->position(zeta, ref_point_on_circle);
     // Get reference point on right line
     Vector<double> ref_point_on_right_line(2);
     ref_point_on_right_line[0] = // flag_end[0];
       outer_point[0] + (flag_end[0] - outer_point[0]) * omega_vertical;
     ref_point_on_right_line[1] =
       outer_point[1] + (flag_end[1] - outer_point[1]) * omega_vertical;
     // Get reference point on flag
     Vector<double> ref_point_on_flag(2);
     zeta[0] = ref_value[3];
     flag_ref_pt->position(t, zeta, ref_point_on_flag);
     // Get top-most point on circle
     Vector<double> circle_top(2);
     zeta[0] = zeta_circle_top;
     Cylinder_pt->position(zeta, circle_top);
     // Get reference point on horizontal fraction of straight line
     // connecting the two top most reference points
     Vector<double> r_top(2);
     r_top[0] = circle_top[0] + (flag_end[0] - circle_top[0]) * omega_horizontal;
     r_top[1] = circle_top[1] + (flag_end[1] - circle_top[1]) * omega_horizontal;
     // Place point on horizontal fraction of straight line
     // connecting reference points -- this won't match the
     // curved top boundary adjacent to the flag
     node_pt->x(t, 0) =
       ref_point_on_circle[0] +
       (ref_point_on_right_line[0] - ref_point_on_circle[0]) * omega_horizontal;
     node_pt->x(t, 1) =
       ref_point_on_circle[1] +
       (ref_point_on_right_line[1] - ref_point_on_circle[1]) * omega_horizontal;
     // Correct by scaled difference between top straight line
     // and bent flag
     node_pt->x(t, 0) += (ref_point_on_flag[0] - r_top[0]) * omega_vertical;
     node_pt->x(t, 1) += (ref_point_on_flag[1] - r_top[1]) * omega_vertical;
   }
References Eigen::bfloat16_impl::asin(), Eigen::bfloat16_impl::atan(), GlobalParameters::Cylinder_pt, GlobalParameters::Height, Global_Physical_Variables::Length, OscillatingCylinder::position(), oomph::GeomObject::position(), plotPSD::t, oomph::AlgebraicNode::vector_geom_object_pt(), oomph::AlgebraicNode::vector_ref_value(), oomph::Node::x(), and Eigen::zeta().
node_update_V()
template<class ELEMENT > void oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::node_update_V (const unsigned & t, AlgebraicNode *& node_pt) protected
Helper function.
Node update for region V.
   {
     // Useful points
     Vector<double> p31(2);
     Vector<double> p35(2);
     Vector<double> top_flag(2);
     p31[0] = Centre_x +
              A * sqrt(1.0 - Flag_height * Flag_height / (4.0 * A * A)) +
              Flag_length;
     p31[1] = Centre_y - Flag_height / 2.;
     p35[0] = 0.285123967 * Length;
     p35[1] = 0.350609756 * Height;
     // Extract reference values for update by copy construction
     Vector<double> ref_value(node_pt->vector_ref_value());
     // Extract geometric objects for update by copy construction
     Vector<GeomObject*> geom_object_pt(node_pt->vector_geom_object_pt());
     // Pointer to geom object
     GeomObject* flag_pt = geom_object_pt[0];
     Vector<double> zeta(1);
     zeta[0] = ref_value[2];
     flag_pt->position(t, zeta, top_flag);
     // point on the line linking p35 et top_flag
     Vector<double> p1(2);
     p1[0] = top_flag[0] + ref_value[0] * (p35[0] - top_flag[0]);
     p1[1] = top_flag[1] + ref_value[0] * (p35[1] - top_flag[1]);
     // Point on the line y = 0.0;
     Vector<double> p2(2);
     p2[0] = p31[0] + ref_value[0] * (p35[0] - p31[0]);
     p2[1] = 0.;
     // Connect those points with the vertical fraction ref_value[1]
     node_pt->x(t, 0) = p2[0] + ref_value[1] * (p1[0] - p2[0]);
     node_pt->x(t, 1) = p2[1] + ref_value[1] * (p1[1] - p2[1]);
   }
References Global_Parameters::Centre_x, Global_Parameters::Centre_y, GlobalParameters::Height, Global_Physical_Variables::Length, p1, oomph::GeomObject::position(), sqrt(), plotPSD::t, oomph::AlgebraicNode::vector_geom_object_pt(), oomph::AlgebraicNode::vector_ref_value(), oomph::Node::x(), and Eigen::zeta().
node_update_VI()
template<class ELEMENT > void oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::node_update_VI (const unsigned & t, AlgebraicNode *& node_pt) protected
Helper function.
Node update for region VI.
   {
     // Extract reference values for update by copy construction
     Vector<double> ref_value(node_pt->vector_ref_value());
     // Useful points
     Vector<double> p14(2);
     Vector<double> p5(2);
     Vector<double> point_flag(2);
     p14[0] = 0.211596 * Length;
     p14[1] = 0.778024390 * Height;
     p5[0] = 0.239596 * Length;
     p5[1] = Height;
     // Extract geometric objects for update by copy construction
     Vector<GeomObject*> geom_object_pt(node_pt->vector_geom_object_pt());
     // Pointer to geom object
     GeomObject* flag_pt = geom_object_pt[0];
     Vector<double> zeta(1);
     zeta[0] = ref_value[3];
     flag_pt->position(t, zeta, point_flag);
     // point on the line linking p14 et p5
     Vector<double> p1(2);
     p1[0] = p14[0] + ref_value[0] * (p5[0] - p14[0]);
     p1[1] = p14[1] + ref_value[0] * (p5[1] - p14[1]);
     // Connect those points with the vertical fraction ref_value[1]
     node_pt->x(t, 0) = point_flag[0] + ref_value[1] * (p1[0] - point_flag[0]);
     node_pt->x(t, 1) = point_flag[1] + ref_value[1] * (p1[1] - point_flag[1]);
   }
References GlobalParameters::Height, Global_Physical_Variables::Length, p1, oomph::GeomObject::position(), plotPSD::t, oomph::AlgebraicNode::vector_geom_object_pt(), oomph::AlgebraicNode::vector_ref_value(), oomph::Node::x(), and Eigen::zeta().
node_update_VII()
template<class ELEMENT > void oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::node_update_VII (const unsigned & t, AlgebraicNode *& node_pt) protected
Helper function.
Node update for region VII.
   {
     // Extract reference values for update by copy construction
     Vector<double> ref_value(node_pt->vector_ref_value());
     // Useful points
     Vector<double> p40(2);
     Vector<double> p45(2);
     Vector<double> point_flag(2);
     p40[0] = 0.211596 * Length;
     p40[1] = 0.197585366 * Height;
     p45[0] = 0.239596 * Length;
     p45[1] = 0.0;
     // Extract geometric objects for update by copy construction
     Vector<GeomObject*> geom_object_pt(node_pt->vector_geom_object_pt());
     // Pointer to geom object
     GeomObject* flag_pt = geom_object_pt[0];
     Vector<double> zeta(1);
     zeta[0] = ref_value[3];
     flag_pt->position(t, zeta, point_flag);
     // point on the line linking p40 et p45
     Vector<double> p1(2);
     p1[0] = p40[0] + ref_value[0] * (p45[0] - p40[0]);
     p1[1] = p40[1] + ref_value[0] * (p45[1] - p40[1]);
     // Connect those points with the vertical fraction ref_value[1]
     node_pt->x(t, 0) =
       point_flag[0] + (1 - ref_value[1]) * (p1[0] - point_flag[0]);
     node_pt->x(t, 1) =
       point_flag[1] + (1 - ref_value[1]) * (p1[1] - point_flag[1]);
   }
References GlobalParameters::Height, Global_Physical_Variables::Length, p1, oomph::GeomObject::position(), plotPSD::t, oomph::AlgebraicNode::vector_geom_object_pt(), oomph::AlgebraicNode::vector_ref_value(), oomph::Node::x(), and Eigen::zeta().
node_update_VIII()
template<class ELEMENT > void oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::node_update_VIII (const unsigned & t, AlgebraicNode *& node_pt) protected
Helper function.
Node update for region VIII.
Extreme angles on circle
   {
     // Useful point
     Vector<double> p11(2);
     p11[0] = 0.127596 * Length;
     p11[1] = 0.778024390 * Height;
     double zeta_circle_top = atan(1.0);
     double zeta_circle_bot = asin(Flag_height / 2. / A);
     // Extract reference values for update by copy construction
     Vector<double> ref_value(node_pt->vector_ref_value());
     // Extract geometric objects for update by copy construction
     Vector<GeomObject*> geom_object_pt(node_pt->vector_geom_object_pt());
     // Pointer to geom object containing the reference point
     GeomObject* flag_ref_pt = geom_object_pt[0];
     // Pointer to geom object containing the end of the macro element
     GeomObject* flag_end_pt = geom_object_pt[1];
     double omega_horizontal = ref_value[0];
     double omega_vertical = ref_value[1];
     // end of the macro element on the flag
     Vector<double> flag_end(2);
     Vector<double> zeta(1);
     zeta[0] = ref_value[5];
     flag_end_pt->position(t, zeta, flag_end);
     Vector<double> outer_point(p11);
     // Get reference point on circle
     Vector<double> ref_point_on_circle(2);
     zeta[0] =
       zeta_circle_bot + (zeta_circle_top - zeta_circle_bot) * omega_vertical;
     Cylinder_pt->position(zeta, ref_point_on_circle);
     // Get reference point on right line
     Vector<double> ref_point_on_right_line(2);
     ref_point_on_right_line[0] = // flag_end[0];
       outer_point[0] + (flag_end[0] - outer_point[0]) * (1.0 - omega_vertical);
     ref_point_on_right_line[1] =
       outer_point[1] + (flag_end[1] - outer_point[1]) * (1.0 - omega_vertical);
     // Get reference point on flag
     Vector<double> ref_point_on_flag(2);
     zeta[0] = ref_value[3];
     flag_ref_pt->position(t, zeta, ref_point_on_flag);
     // Get bottom-most point on circle
     Vector<double> circle_bot(2);
     zeta[0] = zeta_circle_bot;
     Cylinder_pt->position(zeta, circle_bot);
     // Get reference point on horizontal fraction of straight line
     // connecting the two bottom most reference points
     Vector<double> r_bot(2);
     r_bot[0] = circle_bot[0] + (flag_end[0] - circle_bot[0]) * omega_horizontal;
     r_bot[1] = circle_bot[1] + (flag_end[1] - circle_bot[1]) * omega_horizontal;
     // Place point on horizontal fraction of straight line
     // connecting reference points -- this won't match the
     // curved top boundary adjacent to the flag
     node_pt->x(t, 0) =
       ref_point_on_circle[0] +
       (ref_point_on_right_line[0] - ref_point_on_circle[0]) * omega_horizontal;
     node_pt->x(t, 1) =
       ref_point_on_circle[1] +
       (ref_point_on_right_line[1] - ref_point_on_circle[1]) * omega_horizontal;
     // Correct by scaled difference between bottom straight line
     // and bent flag
     node_pt->x(t, 0) +=
       (ref_point_on_flag[0] - r_bot[0]) * (1.0 - omega_vertical);
     node_pt->x(t, 1) +=
       (ref_point_on_flag[1] - r_bot[1]) * (1.0 - omega_vertical);
   }
References Eigen::bfloat16_impl::asin(), Eigen::bfloat16_impl::atan(), GlobalParameters::Cylinder_pt, GlobalParameters::Height, Global_Physical_Variables::Length, OscillatingCylinder::position(), oomph::GeomObject::position(), plotPSD::t, oomph::AlgebraicNode::vector_geom_object_pt(), oomph::AlgebraicNode::vector_ref_value(), oomph::Node::x(), and Eigen::zeta().
set_bottom_flag_pt()
template<class ELEMENT > void oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::set_bottom_flag_pt (GeomObject * bottom_flag_pt) inline
Set geometric object that defines the bottom face of the flag
     {
       // Need to alter the domain's bottom_flag_pt too
       this->domain_pt()->bottom_flag_pt() = bottom_flag_pt;
       Bottom_flag_pt = bottom_flag_pt;
     }
References oomph::CylinderWithFlagDomain::bottom_flag_pt(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::bottom_flag_pt(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::Bottom_flag_pt, and oomph::CylinderWithFlagMesh< ELEMENT >::domain_pt().
set_tip_flag_pt()
template<class ELEMENT > void oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::set_tip_flag_pt (GeomObject * tip_flag_pt) inline
Set the geometric object that defines the tip of the flag
     {
       this->domain_pt()->tip_flag_pt() = tip_flag_pt;
       Tip_flag_pt = tip_flag_pt;
     }
References oomph::CylinderWithFlagMesh< ELEMENT >::domain_pt(), oomph::CylinderWithFlagDomain::tip_flag_pt(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::tip_flag_pt(), and oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::Tip_flag_pt.
set_top_flag_pt()
template<class ELEMENT > void oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::set_top_flag_pt (GeomObject * top_flag_pt) inline
Set the geometric object that defines the top face of the flag
     {
       this->domain_pt()->top_flag_pt() = top_flag_pt;
       Top_flag_pt = top_flag_pt;
     }
References oomph::CylinderWithFlagMesh< ELEMENT >::domain_pt(), oomph::CylinderWithFlagDomain::top_flag_pt(), oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::top_flag_pt(), and oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::Top_flag_pt.
setup_algebraic_node_update()
template<class ELEMENT > void oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::setup_algebraic_node_update protected
Function to setup the algebraic node update.
Setup algebraic node update.
/////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////
set the size ??
   {
     // The update function requires six parameters in some cases:
     Vector<double> ref_value(6);
     for (unsigned i = 0; i < 5; i++)
     {
       ref_value[i] = 0.0;
     }
     // Part I : macro elements 8,12,16
     for (unsigned k = 0; k < 3; k++)
     {
       FiniteElement* el_pt = this->finite_element_pt(8 + k * 4);
       unsigned nnode = el_pt->nnode();
       for (unsigned i = 0; i < nnode; i++)
       {
         // Get local coordinates
         Vector<double> coord_loc(2);
         el_pt->local_coordinate_of_node(i, coord_loc);
         // First reference value : horizontal fraction
         ref_value[0] = 0.5 * (coord_loc[0] + 1.0);
         // Second reference value : vertical fraction
         ref_value[1] = 0.5 * (coord_loc[1] + 1.0);
         // Third reference value : zeta coordinate on flag
         ref_value[2] = double(k + 1) / 5. * Flag_length +
                        ref_value[0] * 1. / 5. * Flag_length;
         // Sub-geomobject corresponding to the zeta coordinate on the flag
         GeomObject* geom_obj_pt;
         Vector<double> s(1);
         Vector<double> zeta(1);
         zeta[0] = ref_value[2];
         Top_flag_pt->locate_zeta(zeta, geom_obj_pt, s);
         // Create vector of geomobject for add_node_update_info()
         Vector<GeomObject*> geom_object_pt(1);
         geom_object_pt[0] = geom_obj_pt;
         // Fourth reference value : local coordinate in the sub geomobject
         ref_value[3] = s[0];
         // Fifth reference value : x coordinate
         ref_value[4] = el_pt->node_pt(i)->x(0);
         // Setup algebraic update for node: Pass update information
         // to AlgebraicNode:
         dynamic_cast<AlgebraicNode*>(el_pt->node_pt(i))
           ->add_node_update_info(1, // ID
                                  this, // mesh
                                  geom_object_pt, // vector of geom objects
                                  ref_value); // vector of ref. values
       }
     }
     // Part II : macro elements 9,13,17
     for (unsigned k = 0; k < 3; k++)
     {
       FiniteElement* el_pt = this->finite_element_pt(9 + k * 4);
       unsigned nnode = el_pt->nnode();
       for (unsigned i = 0; i < nnode; i++)
       {
         // Get local coordinates
         Vector<double> coord_loc(2);
         el_pt->local_coordinate_of_node(i, coord_loc);
         // First reference value : horizontal fraction
         ref_value[0] = 0.5 * (coord_loc[0] + 1.0);
         // Second reference value : vertical fraction
         ref_value[1] = 0.5 * (coord_loc[1] + 1.0);
         // Third reference value : zeta coordinate on flag
         ref_value[2] = double(k + 1) / 5. * Flag_length +
                        ref_value[0] * 1. / 5. * Flag_length;
         // Sub-geomobject corresponding to the zeta coordinate on the flag
         GeomObject* geom_obj_pt;
         Vector<double> s(1);
         Vector<double> zeta(1);
         zeta[0] = ref_value[2];
         Bottom_flag_pt->locate_zeta(zeta, geom_obj_pt, s);
         // Create vector of geomobject for add_node_update_info()
         Vector<GeomObject*> geom_object_pt(1);
         geom_object_pt[0] = geom_obj_pt;
         // Fourth reference value : local coordinate in the sub geomobject
         ref_value[3] = s[0];
         // Fifth reference value : x coordinate
         ref_value[4] = el_pt->node_pt(i)->x(0);
         // Setup algebraic update for node: Pass update information
         // to AlgebraicNode:
         dynamic_cast<AlgebraicNode*>(el_pt->node_pt(i))
           ->add_node_update_info(2, // ID
                                  this, // mesh
                                  geom_object_pt, // vector of geom objects
                                  ref_value); // vector of ref. values
       }
     }
     // Part III : macro element 22
     FiniteElement* el_pt = this->finite_element_pt(22);
     unsigned nnode = el_pt->nnode();
     for (unsigned i = 0; i < nnode; i++)
     {
       // Get local coordinates
       Vector<double> coord_loc(2);
       el_pt->local_coordinate_of_node(i, coord_loc);
       // First reference value : horizontal fraction
       ref_value[0] = 0.5 * (coord_loc[0] + 1.0);
       // Second reference value : vertical fraction
       ref_value[1] = 0.5 * (coord_loc[1] + 1.0);
       // Third reference value : zeta coordinate on flag
       ref_value[2] = coord_loc[1] * Flag_height / 2.;
       // Sub-geomobject corresponding to the zeta coordinate on the flag
       GeomObject* geom_obj_pt;
       Vector<double> s(1);
       Vector<double> zeta(1);
       zeta[0] = ref_value[2];
       Tip_flag_pt->locate_zeta(zeta, geom_obj_pt, s);
       // Create vector of geomobject for add_node_update_info()
       Vector<GeomObject*> geom_object_pt(1);
       geom_object_pt[0] = geom_obj_pt;
       // Fourth reference value : local coordinate in the sub geomobject
       ref_value[3] = s[0];
       // Setup algebraic update for node: Pass update information
       // to AlgebraicNode:
       dynamic_cast<AlgebraicNode*>(el_pt->node_pt(i))
         ->add_node_update_info(3, // ID
                                this, // mesh
                                geom_object_pt, // vector of geom objects
                                ref_value); // vector of ref. values
     }
     // Part IV : macro element 21
     el_pt = this->finite_element_pt(21);
     nnode = el_pt->nnode();
     for (unsigned i = 0; i < nnode; i++)
     {
       // Get local coordinates
       Vector<double> coord_loc(2);
       el_pt->local_coordinate_of_node(i, coord_loc);
       // First reference value : horizontal fraction
       ref_value[0] = 0.5 * (coord_loc[0] + 1.0);
       // Second reference value : vertical fraction
       ref_value[1] = 0.5 * (coord_loc[1] + 1.0);
       // Sub-geomobject corresponding to the tip of the Tip_flag
       GeomObject* geom_obj_pt;
       Vector<double> s(1);
       Vector<double> zeta(1);
       zeta[0] = Flag_height / 2.;
       Tip_flag_pt->locate_zeta(zeta, geom_obj_pt, s);
       // Create vector of geomobject for add_node_update_info()
       Vector<GeomObject*> geom_object_pt(1);
       geom_object_pt[0] = geom_obj_pt;
       // Third reference value : local coordinate in the sub geomobject
       ref_value[2] = s[0];
       // Setup algebraic update for node: Pass update information
       // to AlgebraicNode:
       dynamic_cast<AlgebraicNode*>(el_pt->node_pt(i))
         ->add_node_update_info(4, // ID
                                this, // mesh
                                geom_object_pt, // vector of geom objects
                                ref_value); // vector of ref. values
     }
     // Part V : macro element 23
     el_pt = this->finite_element_pt(23);
     nnode = el_pt->nnode();
     for (unsigned i = 0; i < nnode; i++)
     {
       // Get local coordinates
       Vector<double> coord_loc(2);
       el_pt->local_coordinate_of_node(i, coord_loc);
       // First reference value : horizontal fraction
       ref_value[0] = 0.5 * (coord_loc[0] + 1.0);
       // Second reference value : vertical fraction
       ref_value[1] = 0.5 * (coord_loc[1] + 1.0);
       // Sub-geomobject corresponding to the tip of the Tip_flag
       GeomObject* geom_obj_pt;
       Vector<double> s(1);
       Vector<double> zeta(1);
       zeta[0] = -Flag_height / 2.;
       Tip_flag_pt->locate_zeta(zeta, geom_obj_pt, s);
       // Create vector of geomobject for add_node_update_info()
       Vector<GeomObject*> geom_object_pt(1);
       geom_object_pt[0] = geom_obj_pt;
       // Third reference value : local coordinate in the sub geomobject
       ref_value[2] = s[0];
       // Setup algebraic update for node: Pass update information
       // to AlgebraicNode:
       dynamic_cast<AlgebraicNode*>(el_pt->node_pt(i))
         ->add_node_update_info(5, // ID
                                this, // mesh
                                geom_object_pt, // vector of geom objects
                                ref_value); // vector of ref. values
     }
     // Part VI = macro element 19
     el_pt = this->finite_element_pt(19);
     nnode = el_pt->nnode();
     for (unsigned i = 0; i < nnode; i++)
     {
       // Get local coordinates
       Vector<double> coord_loc(2);
       el_pt->local_coordinate_of_node(i, coord_loc);
       // First reference value : horizontal fraction
       ref_value[0] = 0.5 * (coord_loc[0] + 1.0);
       // Second reference value : vertical fraction
       ref_value[1] = 0.5 * (coord_loc[1] + 1.0);
       // Third reference value : zeta coordinate on the flag
       ref_value[2] =
         4. / 5. * Flag_length + ref_value[0] * 1. / 5. * Flag_length;
       // Sub-geomobject
       GeomObject* geom_obj_pt;
       Vector<double> s(1);
       Vector<double> zeta(1);
       zeta[0] = ref_value[2];
       Top_flag_pt->locate_zeta(zeta, geom_obj_pt, s);
       // Create vector of geomobject for add_node_update_info()
       Vector<GeomObject*> geom_object_pt(1);
       geom_object_pt[0] = geom_obj_pt;
       // Third reference value : local coordinate in the sub geomobject
       ref_value[3] = s[0];
       // Setup algebraic update for node: Pass update information
       // to AlgebraicNode:
       dynamic_cast<AlgebraicNode*>(el_pt->node_pt(i))
         ->add_node_update_info(6, // ID
                                this, // mesh
                                geom_object_pt, // vector of geom objects
                                ref_value); // vector of ref. values
     }
     // Part VII = macro element 20
     el_pt = this->finite_element_pt(20);
     nnode = el_pt->nnode();
     for (unsigned i = 0; i < nnode; i++)
     {
       // Get local coordinates
       Vector<double> coord_loc(2);
       el_pt->local_coordinate_of_node(i, coord_loc);
       // First reference value : horizontal fraction
       ref_value[0] = 0.5 * (coord_loc[0] + 1.0);
       // Second reference value : vertical fraction
       ref_value[1] = 0.5 * (coord_loc[1] + 1.0);
       // Third reference value : zeta coordinate on the flag
       ref_value[2] =
         4. / 5. * Flag_length + ref_value[0] * 1. / 5. * Flag_length;
       // Sub-geomobject
       GeomObject* geom_obj_pt;
       Vector<double> s(1);
       Vector<double> zeta(1);
       zeta[0] = ref_value[2];
       Bottom_flag_pt->locate_zeta(zeta, geom_obj_pt, s);
       // Create vector of geomobject for add_node_update_info()
       Vector<GeomObject*> geom_object_pt(1);
       geom_object_pt[0] = geom_obj_pt;
       // Third reference value : local coordinate in the sub geomobject
       ref_value[3] = s[0];
       // Setup algebraic update for node: Pass update information
       // to AlgebraicNode:
       dynamic_cast<AlgebraicNode*>(el_pt->node_pt(i))
         ->add_node_update_info(7, // ID
                                this, // mesh
                                geom_object_pt, // vector of geom objects
                                ref_value); // vector of ref. values
     }
     // Part VIII : macro element 3
     el_pt = this->finite_element_pt(3);
     nnode = el_pt->nnode();
     for (unsigned i = 0; i < nnode; i++)
     {
       // Get local coordinates
       Vector<double> coord_loc(2);
       el_pt->local_coordinate_of_node(i, coord_loc);
       // First reference value : horizontal fraction
       ref_value[0] = 0.5 * (coord_loc[0] + 1.0);
       // Second reference value : vertical fraction
       ref_value[1] = 0.5 * (coord_loc[1] + 1.0);
       // Third reference value : zeta coordinate on flag at reference point
       ref_value[2] = ref_value[0] * 1. / 5. * Flag_length;
       // Sub-geomobject corresponding to the zeta coordinate on the flag
       // at the reference point
       GeomObject* geom_obj_pt;
       Vector<double> s(1);
       Vector<double> zeta(1);
       zeta[0] = ref_value[2];
       Top_flag_pt->locate_zeta(zeta, geom_obj_pt, s);
       // Fourth reference value : local coordinate in the sub geomobject
       ref_value[3] = s[0];
       // Create vector of geomobject for add_node_update_info()
       Vector<GeomObject*> geom_object_pt(2);
       geom_object_pt[0] = geom_obj_pt;
       // Fifth reference value : zeta coordinate on flag at end of macro element
       ref_value[4] = 1. / 5. * Flag_length;
       // Sub-geomobject corresponding to the zeta coordinate on the flag
       // at the end of the macro element
       zeta[0] = ref_value[4];
       Top_flag_pt->locate_zeta(zeta, geom_obj_pt, s);
       // Add geom object
       geom_object_pt[1] = geom_obj_pt;
       // Sixth reference value : local coordinate in the sub geomobject
       ref_value[5] = s[0];
       // Setup algebraic update for node: Pass update information
       // to AlgebraicNode:
       dynamic_cast<AlgebraicNode*>(el_pt->node_pt(i))
         ->add_node_update_info(8, // ID
                                this, // mesh
                                geom_object_pt, // vector of geom objects
                                ref_value); // vector of ref. values
     }
     // Part IX : macro element 4
     el_pt = this->finite_element_pt(4);
     nnode = el_pt->nnode();
     for (unsigned i = 0; i < nnode; i++)
     {
       // Get local coordinates
       Vector<double> coord_loc(2);
       el_pt->local_coordinate_of_node(i, coord_loc);
       // First reference value : horizontal fraction
       ref_value[0] = 0.5 * (coord_loc[0] + 1.0);
       // Second reference value : vertical fraction
       ref_value[1] = 0.5 * (coord_loc[1] + 1.0);
       // Third reference value : zeta coordinate on flag
       ref_value[2] = ref_value[0] * 1. / 5. * Flag_length;
       // Sub-geomobject corresponding to the zeta coordinate on the flag
       // at the reference point
       GeomObject* geom_obj_pt;
       Vector<double> s(1);
       Vector<double> zeta(1);
       zeta[0] = ref_value[2];
       Bottom_flag_pt->locate_zeta(zeta, geom_obj_pt, s);
       // Fourth reference value : local coordinate in the sub geomobject
       ref_value[3] = s[0];
       // Create vector of geomobject for add_node_update_info()
       Vector<GeomObject*> geom_object_pt(2);
       geom_object_pt[0] = geom_obj_pt;
       // Fifth reference value : zeta coordinate on flag at end of macro element
       ref_value[4] = 1. / 5. * Flag_length;
       // Sub-geomobject corresponding to the zeta coordinate on the flag
       // at the end of the macro element
       zeta[0] = ref_value[4];
       Bottom_flag_pt->locate_zeta(zeta, geom_obj_pt, s);
       // Add geom object
       geom_object_pt[1] = geom_obj_pt;
       // Sixth reference value : local coordinate in the sub geomobject
       ref_value[5] = s[0];
       // Setup algebraic update for node: Pass update information
       // to AlgebraicNode:
       dynamic_cast<AlgebraicNode*>(el_pt->node_pt(i))
         ->add_node_update_info(9, // ID
                                this, // mesh
                                geom_object_pt, // vector of geom objects
                                ref_value); // vector of ref. values
     }
   } // end of setup_algebraic_node_update
References Flag_definition::Bottom_flag_pt, i, k, oomph::FiniteElement::local_coordinate_of_node(), oomph::GeomObject::locate_zeta(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), s, Flag_definition::Tip_flag_pt, Flag_definition::Top_flag_pt, oomph::Node::x(), and Eigen::zeta().
Referenced by oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::AlgebraicCylinderWithFlagMesh().
tip_flag_pt()
template<class ELEMENT > GeomObject* oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::tip_flag_pt () const inline
Read-only access to geometric object that defines the tip of the flag
     {
       return Tip_flag_pt;
     }
References oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::Tip_flag_pt.
Referenced by oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::AlgebraicCylinderWithFlagMesh(), and oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::set_tip_flag_pt().
top_flag_pt()
template<class ELEMENT > GeomObject* oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::top_flag_pt () const inline
Read-only access to geometric object that defines the top face of the flag
     {
       return Top_flag_pt;
     }
References oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::Top_flag_pt.
Referenced by oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::AlgebraicCylinderWithFlagMesh(), and oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::set_top_flag_pt().
update_node_update()
template<class ELEMENT > void oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::update_node_update (AlgebraicNode *& node_pt) inline virtual
Update the geometric references that are used to update node after mesh adaptation. Empty – no update of node update required without adaptativity
Implements oomph::AlgebraicMesh.
Reimplemented in oomph::RefineableAlgebraicCylinderWithFlagMesh< ELEMENT >, and oomph::RefineableAlgebraicCylinderWithFlagMesh< FLUID_ELEMENT >.
 {}
Member Data Documentation
A
template<class ELEMENT > double oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::A protected
radius of the cylinder
Bottom_flag_pt
template<class ELEMENT > GeomObject* oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::Bottom_flag_pt protected
Bottom flag.
Referenced by oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::bottom_flag_pt(), and oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::set_bottom_flag_pt().
Centre_x
template<class ELEMENT > double oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::Centre_x protected
x position of the centre of the cylinder
Centre_y
template<class ELEMENT > double oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::Centre_y protected
x position of the centre of the cylinder
Cylinder_pt
template<class ELEMENT > GeomObject* oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::Cylinder_pt protected
Cylinder.
Flag_height
template<class ELEMENT > double oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::Flag_height protected
Flag thickness.
Flag_length
template<class ELEMENT > double oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::Flag_length protected
Flag length.
Height
template<class ELEMENT > double oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::Height protected
Height of the domain.
Length
template<class ELEMENT > double oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::Length protected
Length of the domain.
Tip_flag_pt
template<class ELEMENT > GeomObject* oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::Tip_flag_pt protected
Tip flag.
Referenced by oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::set_tip_flag_pt(), and oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::tip_flag_pt().
Top_flag_pt
template<class ELEMENT > GeomObject* oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::Top_flag_pt protected
Top flag.
Referenced by oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::set_top_flag_pt(), and oomph::AlgebraicCylinderWithFlagMesh< ELEMENT >::top_flag_pt().
The documentation for this class was generated from the following files:
cylinder_with_flag_mesh.template.h
cylinder_with_flag_mesh.template.cc