MercuryDPM: LoggerUnitTest.cpp File Reference
LoggerUnitTest.cpp File Reference
#include <iostream>
#include "Logger.h"
#include <cstdlib>
Macros
#define HG_LOGLEVEL_SELFTEST Log::DEFAULT
Functions
void assertOrDie (bool condition, std::string message)
int main ()
Variables
Logger< HG_LOGLEVEL_SELFTEST > unitLogger ("UnitTester")
Macro Definition Documentation
HG_LOGLEVEL_SELFTEST
#define HG_LOGLEVEL_SELFTEST Log::DEFAULT
Function Documentation
assertOrDie()
void assertOrDie (bool condition, std::string message)
 {
     if (!condition)
     {
         std::cerr << "Assert failed: " << message << std::endl;
         std::exit(1);
     }
 }
Referenced by main().
main()
int main ()
 {
     int x = 3;
     bool hasLogged = false;
     std::string lastMessage;
     std::string lastModule;
     auto tmpLogger = [&](std::string module, std::string msg, Flusher doFlush)
     {
         lastMessage = msg;
         lastModule = module;
         hasLogged = true;
     };
     loggerOutput->onFatal = tmpLogger;
     loggerOutput->onError = tmpLogger;
     loggerOutput->onWarn = tmpLogger;
     loggerOutput->onInfo = tmpLogger;
     loggerOutput->onVerbose = tmpLogger;
     loggerOutput->onDebug = tmpLogger;
     //Basic usage cases:
     unitLogger(ERROR, "Oopsie!"); //An error!
     assertOrDie(hasLogged, "No output detected!");
     hasLogged = false;
     unitLogger(FATAL, "Mweh. x = %", x);
     assertOrDie(hasLogged, "No output detected!");
     assertOrDie(lastMessage == "Mweh. x = 3", "Substitution gone wrong!");
     hasLogged = false;
     unitLogger(DEBUG, "You won't see me!");
     assertOrDie(!hasLogged, "Output detected!");
     unitLogger(WARN, "Escapes are possible! %\% sure!", 100.01f);
     assertOrDie(lastMessage == "Escapes are possible! 100.01% sure!", "Escape gone wrong!");
     //Usage case for redefining with an function
     unitLogger(FATAL, "Test");
     assertOrDie(lastModule == "UnitTester", "Module was incorrect!");
     logger(FATAL, "Test");
     assertOrDie(lastModule != "UnitTester", "Module was incorrect!");
     return 0;
 }
References assertOrDie(), DEBUG, ERROR, FATAL, logger, loggerOutput, LoggerOutput::onDebug, LoggerOutput::onError, LoggerOutput::onFatal, LoggerOutput::onInfo, LoggerOutput::onVerbose, LoggerOutput::onWarn, oomph::Global_string_for_annotation::string(), unitLogger, WARN, and plotDoE::x.
Variable Documentation
unitLogger
Logger<HG_LOGLEVEL_SELFTEST> unitLogger("UnitTester") ("UnitTester")
Referenced by main().