MercuryDPM: ComplexEigenSolver_compute.cpp File Reference
ComplexEigenSolver_compute.cpp File Reference
Functions
ces compute (A)
Variables
MatrixXcf A = MatrixXcf::Random(4, 4)
cout<< "Here is a random 4x4 matrix, A:"<< endl<< A<< endl<< endl;ComplexEigenSolver< MatrixXcf > ces
cout<< "The eigenvalues of A are:"<< endl<< ces.eigenvalues()<< endl;cout<< "The matrix of eigenvectors, V, is:"<< endl<< ces.eigenvectors()<< endl<< endl;complex< float > lambda = ces.eigenvalues()[0]
Function Documentation
compute()
ces compute (A)
Variable Documentation
A
MatrixXcf A = MatrixXcf::Random(4, 4)
ces
cout<< "Here is a random 4x4 matrix, A:" << endl << A << endl << endl;ComplexEigenSolver<MatrixXcf> ces
lambda
cout<< "The eigenvalues of A are:" << endl << ces.eigenvalues() << endl;cout << "The matrix of eigenvectors, V, is:" << endl << ces.eigenvectors() << endl << endl;complex<float> lambda = ces.eigenvalues()[0]
Referenced by oomph::Problem::add_to_dofs(), Eigen::BDCSVD< MatrixType_, Options_ >::divide(), ThreeDimBethertonProblem< ELEMENT >::doc_solution(), Global_Parameters::exact_u(), oomph::NodeElementSolidOnlyMortaringElement::fill_in_contribution_to_jacobian_mortared_nodes(), oomph::NodeNodeMortaringElement::fill_in_contribution_to_jacobian_mortared_nodes(), oomph::ClampedHermiteShellBoundaryConditionElement::fill_in_contribution_to_residuals(), oomph::AxisymmetricLinearElasticityEquations::fill_in_generic_contribution_to_residuals_axisymmetric_linear_elasticity(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::TimeHarmonicFourierDecomposedLinearElasticityEquations::fill_in_generic_contribution_to_residuals_fourier_decomp_time_harmonic_linear_elasticity(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), DependentPositionPointElement::fill_in_generic_contribution_to_residuals_match_position(), SlavePositionPointElement::fill_in_generic_contribution_to_residuals_match_position(), oomph::ImposeImpenetrabilityElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(), oomph::ImposeParallelOutflowElement< ELEMENT >::fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(), GelfandBratuElement< NNODE_1D >::fill_in_generic_dresidual_contribution(), oomph::AxisymmetricPoroelasticityEquations::fill_in_generic_residual_contribution(), PredatorPreyElement::fill_in_generic_residual_contribution(), GelfandBratuElement< NNODE_1D >::fill_in_generic_residual_contribution(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::fill_in_generic_residual_contribution_axisym_poroelastic_fsi(), oomph::LinearisedFSIAxisymmetricNStNoSlipBCElementElement< FLUID_BULK_ELEMENT, SOLID_BULK_ELEMENT >::fill_in_generic_residual_contribution_fsi_no_slip_axisym(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::find_distance_to_free_surface(), ExactSoln::get_exact_u(), helpers::getPercentile(), RNG::getPoissonVariate(), oomph::Problem::globally_convergent_line_search(), oomph::IsotropicElasticityTensor::IsotropicElasticityTensor(), oomph::BlackBoxFDNewtonSolver::line_search(), oomph::DGEulerFaceElement< ELEMENT >::numerical_flux(), oomph::ClampedHermiteShellBoundaryConditionElement::output(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::output(), oomph::FSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::output(), oomph::PMLTimeHarmonicIsotropicElasticityTensor::PMLTimeHarmonicIsotropicElasticityTensor(), ExactSoln::prescribed_traction(), oomph::RefineableImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), oomph::RefineableFSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier(), oomph::YoungLaplaceEquations::scalar_times_vector(), oomph::IsotropicElasticityTensor::set_lame_coefficients(), oomph::PMLTimeHarmonicIsotropicElasticityTensor::set_lame_coefficients(), oomph::TimeHarmonicIsotropicElasticityTensor::set_lame_coefficients(), oomph::ImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::square_of_l2_norm_of_error(), oomph::TimeHarmonicIsotropicElasticityTensor::TimeHarmonicIsotropicElasticityTensor(), oomph::IsotropicElasticityTensor::update_constitutive_parameters(), oomph::PMLTimeHarmonicIsotropicElasticityTensor::update_constitutive_parameters(), oomph::TimeHarmonicIsotropicElasticityTensor::update_constitutive_parameters(), and verify_nnls_optimality().