MercuryDPM: Eigen::TensorEvaluator< const TensorPatchOp< PatchDim, ArgType >, Device > Struct Template Reference
Eigen::TensorEvaluator< const TensorPatchOp< PatchDim, ArgType >, Device > Struct Template Reference
#include <TensorPatch.h>
Public Types
enum {
IsAligned = false , PacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess , BlockAccess = false , PreferBlockAccess = TensorEvaluator<ArgType, Device>::PreferBlockAccess ,
CoordAccess = false , RawAccess = false
}
typedef TensorPatchOp< PatchDim, ArgType > XprType
typedef XprType::Index Index
typedef DSizes< Index, NumDims > Dimensions
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef StorageMemory< CoeffReturnType, Device > Storage
typedef Storage::Type EvaluatorPointerType
typedef internal::TensorBlockNotImplemented TensorBlock
Public Member Functions
EIGEN_STRONG_INLINE TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions & dimensions () const
EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (EvaluatorPointerType)
EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType packet (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
EIGEN_DEVICE_FUNC EvaluatorPointerType data () const
Static Public Attributes
static constexpr int NumDims = internal::array_size<typename TensorEvaluator<ArgType, Device>::Dimensions>::value + 1
static constexpr int PacketSize = PacketType<CoeffReturnType, Device>::size
static constexpr int Layout = TensorEvaluator<ArgType, Device>::Layout
Protected Attributes
Dimensions m_dimensions
array< Index, NumDims > m_outputStrides
array< Index, NumDims - 1 > m_inputStrides
array< Index, NumDims - 1 > m_patchStrides
TensorEvaluator< ArgType, Device > m_impl
Member Typedef Documentation
CoeffReturnType
template<typename PatchDim , typename ArgType , typename Device > typedef XprType::CoeffReturnType Eigen::TensorEvaluator< const TensorPatchOp< PatchDim, ArgType >, Device >::CoeffReturnType
Dimensions
template<typename PatchDim , typename ArgType , typename Device > typedef DSizes<Index, NumDims> Eigen::TensorEvaluator< const TensorPatchOp< PatchDim, ArgType >, Device >::Dimensions
EvaluatorPointerType
template<typename PatchDim , typename ArgType , typename Device > typedef Storage::Type Eigen::TensorEvaluator< const TensorPatchOp< PatchDim, ArgType >, Device >::EvaluatorPointerType
Index
template<typename PatchDim , typename ArgType , typename Device > typedef XprType::Index Eigen::TensorEvaluator< const TensorPatchOp< PatchDim, ArgType >, Device >::Index
PacketReturnType
template<typename PatchDim , typename ArgType , typename Device > typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorEvaluator< const TensorPatchOp< PatchDim, ArgType >, Device >::PacketReturnType
Scalar
template<typename PatchDim , typename ArgType , typename Device > typedef XprType::Scalar Eigen::TensorEvaluator< const TensorPatchOp< PatchDim, ArgType >, Device >::Scalar
Storage
template<typename PatchDim , typename ArgType , typename Device > typedef StorageMemory<CoeffReturnType, Device> Eigen::TensorEvaluator< const TensorPatchOp< PatchDim, ArgType >, Device >::Storage
TensorBlock
template<typename PatchDim , typename ArgType , typename Device > typedef internal::TensorBlockNotImplemented Eigen::TensorEvaluator< const TensorPatchOp< PatchDim, ArgType >, Device >::TensorBlock
XprType
template<typename PatchDim , typename ArgType , typename Device > typedef TensorPatchOp<PatchDim, ArgType> Eigen::TensorEvaluator< const TensorPatchOp< PatchDim, ArgType >, Device >::XprType
Member Enumeration Documentation
anonymous enum
template<typename PatchDim , typename ArgType , typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
BlockAccess
PreferBlockAccess
CoordAccess
RawAccess
        {
     IsAligned = false,
     PacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess,
     BlockAccess = false,
     PreferBlockAccess = TensorEvaluator<ArgType, Device>::PreferBlockAccess,
     CoordAccess = false,
     RawAccess = false
   };
Constructor & Destructor Documentation
TensorEvaluator()
template<typename PatchDim , typename ArgType , typename Device > EIGEN_STRONG_INLINE Eigen::TensorEvaluator< const TensorPatchOp< PatchDim, ArgType >, Device >::TensorEvaluator (const XprType & op, const Device & device) inline
                                                                                : m_impl(op.expression(), device) {
     Index num_patches = 1;
     const typename TensorEvaluator<ArgType, Device>::Dimensions& input_dims = m_impl.dimensions();
     const PatchDim& patch_dims = op.patch_dims();
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       for (int i = 0; i < NumDims - 1; ++i) {
         m_dimensions[i] = patch_dims[i];
         num_patches *= (input_dims[i] - patch_dims[i] + 1);
       }
       m_dimensions[NumDims - 1] = num_patches;
       m_inputStrides[0] = 1;
       m_patchStrides[0] = 1;
       for (int i = 1; i < NumDims - 1; ++i) {
         m_inputStrides[i] = m_inputStrides[i - 1] * input_dims[i - 1];
         m_patchStrides[i] = m_patchStrides[i - 1] * (input_dims[i - 1] - patch_dims[i - 1] + 1);
       }
       m_outputStrides[0] = 1;
       for (int i = 1; i < NumDims; ++i) {
         m_outputStrides[i] = m_outputStrides[i - 1] * m_dimensions[i - 1];
       }
     } else {
       for (int i = 0; i < NumDims - 1; ++i) {
         m_dimensions[i + 1] = patch_dims[i];
         num_patches *= (input_dims[i] - patch_dims[i] + 1);
       }
       m_dimensions[0] = num_patches;
       m_inputStrides[NumDims - 2] = 1;
       m_patchStrides[NumDims - 2] = 1;
       for (int i = NumDims - 3; i >= 0; --i) {
         m_inputStrides[i] = m_inputStrides[i + 1] * input_dims[i + 1];
         m_patchStrides[i] = m_patchStrides[i + 1] * (input_dims[i + 1] - patch_dims[i + 1] + 1);
       }
       m_outputStrides[NumDims - 1] = 1;
       for (int i = NumDims - 2; i >= 0; --i) {
         m_outputStrides[i] = m_outputStrides[i + 1] * m_dimensions[i + 1];
       }
     }
   }
References Eigen::ColMajor, Eigen::TensorEvaluator< Derived, Device >::dimensions(), i, Eigen::TensorEvaluator< Derived, Device >::Layout, and op.
Member Function Documentation
cleanup()
template<typename PatchDim , typename ArgType , typename Device > EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorPatchOp< PatchDim, ArgType >, Device >::cleanup () inline
 { m_impl.cleanup(); }
Referenced by framework.Frame::__init__().
coeff()
template<typename PatchDim , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::TensorEvaluator< const TensorPatchOp< PatchDim, ArgType >, Device >::coeff (Index index) const inline
{
     Index output_stride_index = (static_cast<int>(Layout) == static_cast<int>(ColMajor)) ? NumDims - 1 : 0;
     // Find the location of the first element of the patch.
     Index patchIndex = index / m_outputStrides[output_stride_index];
     // Find the offset of the element wrt the location of the first element.
     Index patchOffset = index - patchIndex * m_outputStrides[output_stride_index];
     Index inputIndex = 0;
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       EIGEN_UNROLL_LOOP
       for (int i = NumDims - 2; i > 0; --i) {
         const Index patchIdx = patchIndex / m_patchStrides[i];
         patchIndex -= patchIdx * m_patchStrides[i];
         const Index offsetIdx = patchOffset / m_outputStrides[i];
         patchOffset -= offsetIdx * m_outputStrides[i];
         inputIndex += (patchIdx + offsetIdx) * m_inputStrides[i];
       }
     } else {
       EIGEN_UNROLL_LOOP
       for (int i = 0; i < NumDims - 2; ++i) {
         const Index patchIdx = patchIndex / m_patchStrides[i];
         patchIndex -= patchIdx * m_patchStrides[i];
         const Index offsetIdx = patchOffset / m_outputStrides[i + 1];
         patchOffset -= offsetIdx * m_outputStrides[i + 1];
         inputIndex += (patchIdx + offsetIdx) * m_inputStrides[i];
       }
     }
     inputIndex += (patchIndex + patchOffset);
     return m_impl.coeff(inputIndex);
   }
References Eigen::ColMajor, EIGEN_UNROLL_LOOP, i, and Eigen::TensorEvaluator< Derived, Device >::Layout.
costPerCoeff()
template<typename PatchDim , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorEvaluator< const TensorPatchOp< PatchDim, ArgType >, Device >::costPerCoeff (bool vectorized) const inline
{
     const double compute_cost = NumDims * (TensorOpCost::DivCost<Index>() + TensorOpCost::MulCost<Index>() +
                                            2 * TensorOpCost::AddCost<Index>());
     return m_impl.costPerCoeff(vectorized) + TensorOpCost(0, 0, compute_cost, vectorized, PacketSize);
   }
References Eigen::TensorEvaluator< Derived, Device >::PacketSize.
data()
template<typename PatchDim , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EvaluatorPointerType Eigen::TensorEvaluator< const TensorPatchOp< PatchDim, ArgType >, Device >::data () const inline
 { return NULL; }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
dimensions()
template<typename PatchDim , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions& Eigen::TensorEvaluator< const TensorPatchOp< PatchDim, ArgType >, Device >::dimensions () const inline
 { return m_dimensions; }
evalSubExprsIfNeeded()
template<typename PatchDim , typename ArgType , typename Device > EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorPatchOp< PatchDim, ArgType >, Device >::evalSubExprsIfNeeded (EvaluatorPointerType) inline
{
     m_impl.evalSubExprsIfNeeded(NULL);
     return true;
   }
packet()
template<typename PatchDim , typename ArgType , typename Device > template<int LoadMode> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType Eigen::TensorEvaluator< const TensorPatchOp< PatchDim, ArgType >, Device >::packet (Index index) const inline
{
     eigen_assert(index + PacketSize - 1 < dimensions().TotalSize());
     Index output_stride_index = (static_cast<int>(Layout) == static_cast<int>(ColMajor)) ? NumDims - 1 : 0;
     Index indices[2] = {index, index + PacketSize - 1};
     Index patchIndices[2] = {indices[0] / m_outputStrides[output_stride_index],
                              indices[1] / m_outputStrides[output_stride_index]};
     Index patchOffsets[2] = {indices[0] - patchIndices[0] * m_outputStrides[output_stride_index],
                              indices[1] - patchIndices[1] * m_outputStrides[output_stride_index]};
     Index inputIndices[2] = {0, 0};
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       EIGEN_UNROLL_LOOP
       for (int i = NumDims - 2; i > 0; --i) {
         const Index patchIdx[2] = {patchIndices[0] / m_patchStrides[i], patchIndices[1] / m_patchStrides[i]};
         patchIndices[0] -= patchIdx[0] * m_patchStrides[i];
         patchIndices[1] -= patchIdx[1] * m_patchStrides[i];
         const Index offsetIdx[2] = {patchOffsets[0] / m_outputStrides[i], patchOffsets[1] / m_outputStrides[i]};
         patchOffsets[0] -= offsetIdx[0] * m_outputStrides[i];
         patchOffsets[1] -= offsetIdx[1] * m_outputStrides[i];
         inputIndices[0] += (patchIdx[0] + offsetIdx[0]) * m_inputStrides[i];
         inputIndices[1] += (patchIdx[1] + offsetIdx[1]) * m_inputStrides[i];
       }
     } else {
       EIGEN_UNROLL_LOOP
       for (int i = 0; i < NumDims - 2; ++i) {
         const Index patchIdx[2] = {patchIndices[0] / m_patchStrides[i], patchIndices[1] / m_patchStrides[i]};
         patchIndices[0] -= patchIdx[0] * m_patchStrides[i];
         patchIndices[1] -= patchIdx[1] * m_patchStrides[i];
         const Index offsetIdx[2] = {patchOffsets[0] / m_outputStrides[i + 1], patchOffsets[1] / m_outputStrides[i + 1]};
         patchOffsets[0] -= offsetIdx[0] * m_outputStrides[i + 1];
         patchOffsets[1] -= offsetIdx[1] * m_outputStrides[i + 1];
         inputIndices[0] += (patchIdx[0] + offsetIdx[0]) * m_inputStrides[i];
         inputIndices[1] += (patchIdx[1] + offsetIdx[1]) * m_inputStrides[i];
       }
     }
     inputIndices[0] += (patchIndices[0] + patchOffsets[0]);
     inputIndices[1] += (patchIndices[1] + patchOffsets[1]);
     if (inputIndices[1] - inputIndices[0] == PacketSize - 1) {
       PacketReturnType rslt = m_impl.template packet<Unaligned>(inputIndices[0]);
       return rslt;
     } else {
       EIGEN_ALIGN_MAX CoeffReturnType values[PacketSize];
       values[0] = m_impl.coeff(inputIndices[0]);
       values[PacketSize - 1] = m_impl.coeff(inputIndices[1]);
       EIGEN_UNROLL_LOOP
       for (int i = 1; i < PacketSize - 1; ++i) {
         values[i] = coeff(index + i);
       }
       PacketReturnType rslt = internal::pload<PacketReturnType>(values);
       return rslt;
     }
   }
References Eigen::TensorEvaluator< Derived, Device >::coeff(), Eigen::ColMajor, Eigen::TensorEvaluator< Derived, Device >::dimensions(), EIGEN_ALIGN_MAX, eigen_assert, EIGEN_UNROLL_LOOP, i, Eigen::TensorEvaluator< Derived, Device >::Layout, and Eigen::TensorEvaluator< Derived, Device >::PacketSize.
Member Data Documentation
Layout
template<typename PatchDim , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorPatchOp< PatchDim, ArgType >, Device >::Layout = TensorEvaluator<ArgType, Device>::Layout static constexpr
m_dimensions
template<typename PatchDim , typename ArgType , typename Device > Dimensions Eigen::TensorEvaluator< const TensorPatchOp< PatchDim, ArgType >, Device >::m_dimensions protected
m_impl
template<typename PatchDim , typename ArgType , typename Device > TensorEvaluator<ArgType, Device> Eigen::TensorEvaluator< const TensorPatchOp< PatchDim, ArgType >, Device >::m_impl protected
m_inputStrides
template<typename PatchDim , typename ArgType , typename Device > array<Index, NumDims - 1> Eigen::TensorEvaluator< const TensorPatchOp< PatchDim, ArgType >, Device >::m_inputStrides protected
m_outputStrides
template<typename PatchDim , typename ArgType , typename Device > array<Index, NumDims> Eigen::TensorEvaluator< const TensorPatchOp< PatchDim, ArgType >, Device >::m_outputStrides protected
m_patchStrides
template<typename PatchDim , typename ArgType , typename Device > array<Index, NumDims - 1> Eigen::TensorEvaluator< const TensorPatchOp< PatchDim, ArgType >, Device >::m_patchStrides protected
NumDims
template<typename PatchDim , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorPatchOp< PatchDim, ArgType >, Device >::NumDims = internal::array_size<typename TensorEvaluator<ArgType, Device>::Dimensions>::value + 1 static constexpr
PacketSize
template<typename PatchDim , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorPatchOp< PatchDim, ArgType >, Device >::PacketSize = PacketType<CoeffReturnType, Device>::size static constexpr
The documentation for this struct was generated from the following file:
TensorPatch.h