MercuryDPM: Eigen::internal::IndexedViewHelper< ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >, void > Struct Template Reference
Eigen::internal::IndexedViewHelper< ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >, void > Struct Template Reference
#include <IndexedViewHelper.h>
Public Types
using Indices = ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >
Static Public Member Functions
static Index first (const Indices &indices)
static Index size (const Indices &indices)
static Index incr (const Indices &indices)
Static Public Attributes
static constexpr Index FirstAtCompileTime = Indices::FirstAtCompileTime
static constexpr Index SizeAtCompileTime = Indices::SizeAtCompileTime
static constexpr Index IncrAtCompileTime = Indices::IncrAtCompileTime
Member Typedef Documentation
Indices
template<Index FirstAtCompileTime_, Index SizeAtCompileTime_, Index IncrAtCompileTime_> using Eigen::internal::IndexedViewHelper< ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >, void >::Indices = ArithmeticSequenceRange<FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_>
Member Function Documentation
first()
template<Index FirstAtCompileTime_, Index SizeAtCompileTime_, Index IncrAtCompileTime_> static Index Eigen::internal::IndexedViewHelper< ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >, void >::first (const Indices & indices) inline static
 { return indices.first(); }
References Eigen::internal::ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >::first().
incr()
template<Index FirstAtCompileTime_, Index SizeAtCompileTime_, Index IncrAtCompileTime_> static Index Eigen::internal::IndexedViewHelper< ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >, void >::incr (const Indices & indices) inline static
 { return indices.incr(); }
References Eigen::internal::ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >::incr().
size()
template<Index FirstAtCompileTime_, Index SizeAtCompileTime_, Index IncrAtCompileTime_> static Index Eigen::internal::IndexedViewHelper< ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >, void >::size (const Indices & indices) inline static
 { return indices.size(); }
References Eigen::internal::ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >::size().
Member Data Documentation
FirstAtCompileTime
template<Index FirstAtCompileTime_, Index SizeAtCompileTime_, Index IncrAtCompileTime_> constexpr Index Eigen::internal::IndexedViewHelper< ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >, void >::FirstAtCompileTime = Indices::FirstAtCompileTime static constexpr
IncrAtCompileTime
template<Index FirstAtCompileTime_, Index SizeAtCompileTime_, Index IncrAtCompileTime_> constexpr Index Eigen::internal::IndexedViewHelper< ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >, void >::IncrAtCompileTime = Indices::IncrAtCompileTime static constexpr
SizeAtCompileTime
template<Index FirstAtCompileTime_, Index SizeAtCompileTime_, Index IncrAtCompileTime_> constexpr Index Eigen::internal::IndexedViewHelper< ArithmeticSequenceRange< FirstAtCompileTime_, SizeAtCompileTime_, IncrAtCompileTime_ >, void >::SizeAtCompileTime = Indices::SizeAtCompileTime static constexpr
The documentation for this struct was generated from the following file:
IndexedViewHelper.h