MercuryDPM: MathCheck.cpp File Reference
MathCheck.cpp File Reference
#include "Math/Helpers.h"
#include "Math/ExtendedMath.h"
#include <sstream>
Functions
int main ()
Function Documentation
main()
int main ()
 {
     std::stringstream ss;
     for (Mdouble x=-6; x<6; x+=0.01)
     {
         Mdouble e = mathsFunc::exp(x);
         Mdouble l = mathsFunc::log(e);
         Mdouble c = mathsFunc::cos(x);
         Mdouble s = mathsFunc::sin(x);
         ss << x << " "
            << e << " "
            << l << " "
            << c << " "
            << s << "\n";
     }
     logger(INFO, "Execute 'gnuplot MathCheck.gnu' to view output");
     helpers::writeToFile("MathCheck.data", ss.str());
     helpers::writeToFile("MathCheck.gnu",
                          "set xlabel 'x'\n"
                          "p 'MathCheck.data' u 1:(log($2)) t 'log(Exp(x))',"
                          "  'MathCheck.data' u 1:3 t 'Log(Exp(x))', x,"
                          "  'MathCheck.data' u 1:5 t 'Sin(x)', sin(x),"
                          "  'MathCheck.data' u 1:4 t 'Cos(x)', cos(x)x"
                          "\n");
     //WARNING: sin and cos are really bad outside (-pi,pi)
     Mdouble d = 1e-15;
     logger(INFO, "Accuracy of sin: %\n"
                  "Accuracy of cos: %",
            mathsFunc::sin(constants::pi - d) - mathsFunc::sin(constants::pi + d), mathsFunc::cos(constants::pi) + 1);
 }
References calibrate::c, mathsFunc::cos(), e(), mathsFunc::exp(), INFO, mathsFunc::log(), logger, constants::pi, s, mathsFunc::sin(), helpers::writeToFile(), and plotDoE::x.