MercuryDPM: PeriodicChuteUnitTestMPI.cpp File Reference
PeriodicChuteUnitTestMPI.cpp File Reference
#include "Mercury3D.h"
#include "Walls/InfiniteWall.h"
#include <iostream>
#include "Species/LinearViscoelasticFrictionSpecies.h"
#include <cstdlib>
#include "Boundaries/PeriodicBoundary.h"
#include <chrono>
Classes
class MpiPeriodicBoundaryUnitTest
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
 {
     // Start measuring elapsed time
     std::chrono::time_point<std::chrono::system_clock> startClock, endClock;
     startClock = std::chrono::system_clock::now();
     //Create the problem
     MpiPeriodicBoundaryUnitTest problem;
     problem.setName("PeriodicChuteUnitTestMPI");
     //Create a species
     LinearViscoelasticFrictionSpecies* species = problem.speciesHandler.copyAndAddObject(LinearViscoelasticFrictionSpecies());
     species->setDensity(1.0);
     //Set domain accordingly (domain boundaries are not walls!)
     problem.setXMin(0.0);
     problem.setXMax(80.0);
     problem.setYMin(0.0);
     problem.setYMax(80.0);
     problem.setZMin(0.0);
     problem.setZMax(40.0);
     //specify particle properties
     species->setDensity(6.0/constants::pi);
     //specify body forces
     double angle = 27.0;
     double g = 1.0;
     double val = g*std::sin(angle/360.0*2.0*constants::pi);
     problem.setGravity(Vec3D(val, -val, -g*std::cos(angle/360.0*2.0*constants::pi)));
     //Set the number of domains for parallel decomposition
     problem.setNumberOfDomains({2,2,1});
     //specify contact properties
     //normal forces
     species->setStiffness(1e5);
     species->setDissipation(0.1);
     //tangential (sliding) forces
     species->setSlidingFrictionCoefficient(0.5);
     species->setSlidingStiffness(1.2e4);
     species->setSlidingDissipation(0.16);
     //tangential (rolling) torques
     species->setRollingFrictionCoefficient(0.2);
     species->setRollingStiffness(1.2e4);
     species->setRollingDissipation(6.3e-2);
     //normal (torsion/spin) torques
     species->setTorsionFrictionCoefficient(0.1);
     species->setTorsionStiffness(1.2e4);
     species->setSlidingDissipation(6.3e-2);
     //set other simulation parameters
     Mdouble MinParticleMass = species->getDensity()*4.0 / 3.0 * constants::pi ;
     Mdouble tc = species->getCollisionTime(MinParticleMass);
     problem.setTimeStep(tc / 50.0);
     //problem.setTimeMax(100.0);//run until 3.0 to see full simulation
     problem.setTimeMax(40.0);//run until 3.0 to see full simulation
     problem.setSaveCount(200); //used to be 500
     //Set output to paraview
     problem.setParticlesWriteVTK(true);
     problem.solve(argc, argv);
     // Measure elapsed time
     endClock = std::chrono::system_clock::now();
     std::chrono::duration<double> elapsed_seconds = endClock - startClock;
     logger(INFO, "Elapsed time for solving the PDE: % s", elapsed_seconds.count());
     return 0;
 }
References Jeffery_Solution::angle(), cos(), LinearViscoelasticNormalSpecies::getCollisionTime(), ParticleSpecies::getDensity(), INFO, logger, constants::pi, problem, ParticleSpecies::setDensity(), LinearViscoelasticNormalSpecies::setDissipation(), FrictionSpecies::setRollingDissipation(), FrictionSpecies::setRollingFrictionCoefficient(), FrictionSpecies::setRollingStiffness(), SlidingFrictionSpecies::setSlidingDissipation(), SlidingFrictionSpecies::setSlidingFrictionCoefficient(), SlidingFrictionSpecies::setSlidingStiffness(), LinearViscoelasticNormalSpecies::setStiffness(), FrictionSpecies::setTorsionFrictionCoefficient(), FrictionSpecies::setTorsionStiffness(), sin(), and calibrate::val.