MercuryDPM: SaveToVtu Namespace Reference
SaveToVtu Namespace Reference
Functions
def SavePebblesToVtu (filename, positions, velocities, rad)
def SavePDToVtu (filename, v1, v2, v3)
Function Documentation
SavePDToVtu()
def SaveToVtu.SavePDToVtu (filename, v1, v2, v3)
 def SavePDToVtu(filename, v1, v2, v3):
     # This function saves clump principal directions in XML/vtu (unstructured grid) format
     num_part = 1
     num_timesteps = len(v1)
     for timestep in range(num_timesteps):
         pos_string = ""
         v1_string = ""
         v2_string = ""
         v3_string = ""
         rad_string = ""
         pos_string = pos_string + "%.4f " % 0
         pos_string = pos_string + "%.4f " % 0
         pos_string = pos_string + "%.4f " % 0
         v1_string = v1_string + "%.4f " % v1[timestep, 0]
         v1_string = v1_string + "%.4f " % v1[timestep, 1]
         v1_string = v1_string + "%.4f " % v1[timestep, 2]
         v2_string = v2_string + "%.4f " % v2[timestep, 0]
         v2_string = v2_string + "%.4f " % v2[timestep, 1]
         v2_string = v2_string + "%.4f " % v2[timestep, 2]
         v3_string = v3_string + "%.4f " % v3[timestep, 0]
         v3_string = v3_string + "%.4f " % v3[timestep, 1]
         v3_string = v3_string + "%.4f " % v3[timestep, 2]
         rad_string = rad_string + "%.4f " % 1.0
         pos_string = pos_string + "\n"
         v1_string = v1_string + "\n"
         v2_string = v2_string + "\n"
         v3_string = v3_string + "\n"
         rad_string = rad_string + "\n"
         textfile = open(filename + '_pd_' + str(timestep) + '.vtu', "w")
         textfile.write('<?xml version="1.0"?>\n')
         textfile.write('<VTKFile type="UnstructuredGrid" version="0.1" byte_order="LittleEndian">\n')
         textfile.write(' <UnstructuredGrid>\n')
         textfile.write('  <Piece NumberOfPoints="' + str(num_part) + '" NumberOfCells="0">\n')
         textfile.write('   <Cells>\n')
         textfile.write('    <DataArray type="Int32" name="connectivity" format="ascii">\n')
         textfile.write('       0\n')
         textfile.write('    </DataArray>\n')
         textfile.write('    <DataArray type="Float32" name="offset" format="ascii">\n')
         textfile.write('       0\n')
         textfile.write('    </DataArray>\n')
         textfile.write('    <DataArray type="UInt8" name="types" format="ascii">\n')
         textfile.write('       1\n')
         textfile.write('    </DataArray>\n')
         textfile.write('   </Cells>\n')
         textfile.write('   <Points>\n')
         textfile.write('<DataArray type="Float32" NumberOfComponents="3" format="ascii">\n')
         textfile.write(pos_string)
         textfile.write('</DataArray>\n')
         textfile.write('    </Points>\n')
         textfile.write('    <PointData>\n')
         textfile.write('<DataArray type="Float32" Name="Position" NumberOfComponents="3" format="ascii">\n')
         textfile.write(pos_string)
         textfile.write('</DataArray>\n')
         textfile.write('<DataArray type="Float32" Name="v1" NumberOfComponents="3" format="ascii">\n')
         textfile.write(v1_string)
         textfile.write('</DataArray>\n')
         textfile.write('<DataArray type="Float32" Name="v2" NumberOfComponents="3" format="ascii">\n')
         textfile.write(v2_string)
         textfile.write('</DataArray>\n')
         textfile.write('<DataArray type="Float32" Name="v3" NumberOfComponents="3" format="ascii">\n')
         textfile.write(v3_string)
         textfile.write('</DataArray>\n')
         textfile.write('<DataArray type="Float32" Name="Radius" NumberOfComponents="1" format="ascii">\n')
         textfile.write(rad_string)
         textfile.write('</DataArray>\n')
         textfile.write('</PointData>\n')
         textfile.write('<CellData/>\n')
         textfile.write('</Piece>\n')
         textfile.write('</UnstructuredGrid>\n')
         textfile.write('</VTKFile>\n')
         textfile.close()
     return
References compute_granudrum_aor.str.
Referenced by OutputData.ParaviewOutputPebblesAnimated().
SavePebblesToVtu()
def SaveToVtu.SavePebblesToVtu (filename, positions, velocities, rad)
 def SavePebblesToVtu(filename, positions, velocities, rad):
     # This function saves pebble information in XML/vtu (unstructured grid) format
     num_part = np.shape(positions)[0]
     num_timesteps = np.shape(positions)[1]
     for timestep in range(num_timesteps):
         pos_string = ""
         vel_string = ""
         rad_string = ""
         for num in range(num_part):
             pos_string = pos_string + "%.4f " % positions[num, timestep, 0]
             pos_string = pos_string + "%.4f " % positions[num, timestep, 1]
             pos_string = pos_string + "%.4f " % positions[num, timestep, 2]
             vel_string = vel_string + "%.4f " % velocities[num, timestep, 0]
             vel_string = vel_string + "%.4f " % velocities[num, timestep, 1]
             vel_string = vel_string + "%.4f " % velocities[num, timestep, 2]
             rad_string = rad_string + "%.4f " % rad[num, timestep]
         pos_string = pos_string + "\n"
         vel_string = vel_string + "\n"
         rad_string = rad_string + "\n"
         textfile = open(filename + '_' + str(timestep) + '.vtu', "w")
         textfile.write('<?xml version="1.0"?>\n')
         textfile.write('<VTKFile type="UnstructuredGrid" version="0.1" byte_order="LittleEndian">\n')
         textfile.write(' <UnstructuredGrid>\n')
         textfile.write('  <Piece NumberOfPoints="' + str(num_part) + '" NumberOfCells="0">\n')
         textfile.write('   <Cells>\n')
         textfile.write('    <DataArray type="Int32" name="connectivity" format="ascii">\n')
         textfile.write('       0\n')
         textfile.write('    </DataArray>\n')
         textfile.write('    <DataArray type="Float32" name="offset" format="ascii">\n')
         textfile.write('       0\n')
         textfile.write('    </DataArray>\n')
         textfile.write('    <DataArray type="UInt8" name="types" format="ascii">\n')
         textfile.write('       1\n')
         textfile.write('    </DataArray>\n')
         textfile.write('   </Cells>\n')
         textfile.write('   <Points>\n')
         textfile.write('<DataArray type="Float32" NumberOfComponents="3" format="ascii">\n')
         textfile.write(pos_string)
         textfile.write('</DataArray>\n')
         textfile.write('    </Points>\n')
         textfile.write('    <PointData>\n')
         textfile.write('<DataArray type="Float32" Name="Position" NumberOfComponents="3" format="ascii">\n')
         textfile.write(pos_string)
         textfile.write('</DataArray>\n')
         textfile.write('<DataArray type="Float32" Name="Velocity" NumberOfComponents="3" format="ascii">\n')
         textfile.write(vel_string)
         textfile.write('</DataArray>\n')
         textfile.write('<DataArray type="Float32" Name="Radius" NumberOfComponents="1" format="ascii">\n')
         textfile.write(rad_string)
         textfile.write('</DataArray>\n')
         textfile.write('</PointData>\n')
         textfile.write('<CellData/>\n')
         textfile.write('</Piece>\n')
         textfile.write('</UnstructuredGrid>\n')
         textfile.write('</VTKFile>\n')
         textfile.close()
     return
References compute_granudrum_aor.str.
Referenced by OutputData.ParaviewOutputPebblesAnimated(), and OutputData.ParaviewOutputPebblesStatic().