MercuryDPM: InsertZeros< TensorType > Struct Template Reference
InsertZeros< TensorType > Struct Template Reference
Public Member Functions
DSizes< DenseIndex, 2 > dimensions (const Tensor< float, 2 > &input) const
template<typename Output , typename Device >
void eval (const Tensor< float, 2 > &input, Output &output, const Device &device) const
DSizes< DenseIndex, 2 > dimensions (const TensorType &input) const
template<typename Output , typename Device >
void eval (const TensorType &input, Output &output, const Device &device) const
Member Function Documentation
dimensions() [1/2]
template<typename TensorType > DSizes<DenseIndex, 2> InsertZeros< TensorType >::dimensions (const Tensor< float, 2 > & input) const inline
{
     DSizes<DenseIndex, 2> result;
     result[0] = input.dimension(0) * 2;
     result[1] = input.dimension(1) * 2;
     return result;
   }
References Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::dimension().
dimensions() [2/2]
template<typename TensorType > DSizes<DenseIndex, 2> InsertZeros< TensorType >::dimensions (const TensorType & input) const inline
{
     DSizes<DenseIndex, 2> result;
     result[0] = input.dimension(0) * 2;
     result[1] = input.dimension(1) * 2;
     return result;
   }
eval() [1/2]
template<typename TensorType > template<typename Output , typename Device > void InsertZeros< TensorType >::eval (const Tensor< float, 2 > & input, Output & output, const Device & device) const inline
{
     array<DenseIndex, 2> strides;
     strides[0] = 2;
     strides[1] = 2;
     output.stride(strides).device(device) = input;
     Eigen::DSizes<DenseIndex, 2> offsets(1, 1);
     Eigen::DSizes<DenseIndex, 2> extents(output.dimension(0) - 1, output.dimension(1) - 1);
     output.slice(offsets, extents).stride(strides).device(device) = input.constant(0.0f);
   }
References output(), and Eigen::internal::strides().
eval() [2/2]
template<typename TensorType > template<typename Output , typename Device > void InsertZeros< TensorType >::eval (const TensorType & input, Output & output, const Device & device) const inline
{
     array<DenseIndex, 2> strides;
     strides[0] = 2;
     strides[1] = 2;
     output.stride(strides).device(device) = input;
     Eigen::DSizes<DenseIndex, 2> offsets(1, 1);
     Eigen::DSizes<DenseIndex, 2> extents(output.dimension(0) - 1, output.dimension(1) - 1);
     output.slice(offsets, extents).stride(strides).device(device) = input.constant(0.0f);
   }
References output(), and Eigen::internal::strides().
The documentation for this struct was generated from the following files:
cxx11_tensor_custom_op.cpp
cxx11_tensor_custom_op_sycl.cpp