MercuryDPM: Eigen::FullPivLU< MatrixType_, PermutationIndex_ > Class Template Reference
Eigen::FullPivLU< MatrixType_, PermutationIndex_ > Class Template Reference
Dense linear problems and decompositions » Reference » LU_Module
LU decomposition of a matrix with complete pivoting, and related features.
#include <FullPivLU.h>
Public Types
enum { MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime , MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime }
typedef MatrixType_ MatrixType
typedef SolverBase< FullPivLU > Base
using PermutationIndex = PermutationIndex_
typedef internal::plain_row_type< MatrixType, PermutationIndex >::type IntRowVectorType
typedef internal::plain_col_type< MatrixType, PermutationIndex >::type IntColVectorType
typedef PermutationMatrix< ColsAtCompileTime, MaxColsAtCompileTime, PermutationIndex > PermutationQType
typedef PermutationMatrix< RowsAtCompileTime, MaxRowsAtCompileTime, PermutationIndex > PermutationPType
typedef MatrixType::PlainObject PlainObject
Public Types inherited from Eigen::SolverBase< FullPivLU< MatrixType_, PermutationIndex_ > >
enum
typedef EigenBase< FullPivLU< MatrixType_, PermutationIndex_ > > Base
typedef internal::traits< FullPivLU< MatrixType_, PermutationIndex_ > >::Scalar Scalar
typedef Scalar CoeffReturnType
typedef Transpose< const FullPivLU< MatrixType_, PermutationIndex_ > > ConstTransposeReturnType
typedef std::conditional_t< NumTraits< Scalar >::IsComplex, CwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, const ConstTransposeReturnType >, const ConstTransposeReturnType > AdjointReturnType
Public Types inherited from Eigen::EigenBase< Derived >
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< Derived >::StorageKind StorageKind
Public Member Functions
FullPivLU ()
Default Constructor.
FullPivLU (Index rows, Index cols)
Default Constructor with memory preallocation.
template<typename InputType >
FullPivLU (const EigenBase< InputType > &matrix)
template<typename InputType >
FullPivLU (EigenBase< InputType > &matrix)
Constructs a LU factorization from a given matrix.
template<typename InputType >
FullPivLU & compute (const EigenBase< InputType > &matrix)
const MatrixType & matrixLU () const
Index nonzeroPivots () const
RealScalar maxPivot () const
EIGEN_DEVICE_FUNC const PermutationPType & permutationP () const
const PermutationQType & permutationQ () const
const internal::kernel_retval< FullPivLU > kernel () const
const internal::image_retval< FullPivLU > image (const MatrixType &originalMatrix) const
RealScalar rcond () const
internal::traits< MatrixType >::Scalar determinant () const
FullPivLU & setThreshold (const RealScalar &threshold)
FullPivLU & setThreshold (Default_t)
RealScalar threshold () const
Index rank () const
Index dimensionOfKernel () const
bool isInjective () const
bool isSurjective () const
bool isInvertible () const
const Inverse< FullPivLU > inverse () const
MatrixType reconstructedMatrix () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
template<typename RhsType , typename DstType >
void _solve_impl (const RhsType &rhs, DstType &dst) const
template<bool Conjugate, typename RhsType , typename DstType >
void _solve_impl_transposed (const RhsType &rhs, DstType &dst) const
Public Member Functions inherited from Eigen::SolverBase< FullPivLU< MatrixType_, PermutationIndex_ > >
SolverBase ()
~SolverBase ()
const Solve< FullPivLU< MatrixType_, PermutationIndex_ >, Rhs > solve (const MatrixBase< Rhs > &b) const
const ConstTransposeReturnType transpose () const
const AdjointReturnType adjoint () const
constexpr EIGEN_DEVICE_FUNC FullPivLU< MatrixType_, PermutationIndex_ > & derived ()
constexpr EIGEN_DEVICE_FUNC const FullPivLU< MatrixType_, PermutationIndex_ > & derived () const
Public Member Functions inherited from Eigen::EigenBase< Derived >
constexpr EIGEN_DEVICE_FUNC Derived & derived ()
constexpr EIGEN_DEVICE_FUNC const Derived & derived () const
EIGEN_DEVICE_FUNC Derived & const_cast_derived () const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index size () const EIGEN_NOEXCEPT
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
template<typename Device >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< Derived, Device > device (Device &device)
template<typename Device >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< const Derived, Device > device (Device &device) const
Protected Member Functions
void computeInPlace ()
Protected Member Functions inherited from Eigen::SolverBase< FullPivLU< MatrixType_, PermutationIndex_ > >
void _check_solve_assertion (const Rhs &b) const
Protected Attributes
MatrixType m_lu
PermutationPType m_p
PermutationQType m_q
IntColVectorType m_rowsTranspositions
IntRowVectorType m_colsTranspositions
Index m_nonzero_pivots
RealScalar m_l1_norm
RealScalar m_maxpivot
RealScalar m_prescribedThreshold
signed char m_det_pq
bool m_isInitialized
bool m_usePrescribedThreshold
Friends
class SolverBase< FullPivLU >
Detailed Description
template<typename MatrixType_, typename PermutationIndex_>
class Eigen::FullPivLU< MatrixType_, PermutationIndex_ >
LU decomposition of a matrix with complete pivoting, and related features.
Template Parameters
MatrixType_ the type of the matrix of which we are computing the LU decomposition
This class represents a LU decomposition of any matrix, with complete pivoting: the matrix A is decomposed as \(A = P^{-1} L U Q^{-1} \) where L is unit-lower-triangular, U is upper-triangular, and P and Q are permutation matrices. This is a rank-revealing LU decomposition. The eigenvalues (diagonal coefficients) of U are sorted in such a way that any zeros are at the end.
This decomposition provides the generic approach to solving systems of linear equations, computing the rank, invertibility, inverse, kernel, and determinant.
This LU decomposition is very stable and well tested with large matrices. However there are use cases where the SVD decomposition is inherently more stable and/or flexible. For example, when computing the kernel of a matrix, working with the SVD allows to select the smallest singular values of the matrix, something that the LU decomposition doesn't see.
The data of the LU decomposition can be directly accessed through the methods matrixLU(), permutationP(), permutationQ().
As an example, here is how the original matrix can be retrieved:
typedef Matrix<double, 5, 3> Matrix5x3;
typedef Matrix<double, 5, 5> Matrix5x5;
Matrix5x3 m = Matrix5x3::Random();
cout << "Here is the matrix m:" << endl << m << endl;
Eigen::FullPivLU<Matrix5x3> lu(m);
cout << "Here is, up to permutations, its LU decomposition matrix:" << endl << lu.matrixLU() << endl;
cout << "Here is the L part:" << endl;
Matrix5x5 l = Matrix5x5::Identity();
l.block<5, 3>(0, 0).triangularView<StrictlyLower>() = lu.matrixLU();
cout << l << endl;
cout << "Here is the U part:" << endl;
Matrix5x3 u = lu.matrixLU().triangularView<Upper>();
cout << u << endl;
cout << "Let us now reconstruct the original matrix m:" << endl;
cout << lu.permutationP().inverse() * l * u * lu.permutationQ().inverse() << endl;
Output:
This class supports the inplace decomposition mechanism.
See also
MatrixBase::fullPivLu(), MatrixBase::determinant(), MatrixBase::inverse()
Member Typedef Documentation
Base
template<typename MatrixType_ , typename PermutationIndex_ > typedef SolverBase<FullPivLU> Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::Base
IntColVectorType
template<typename MatrixType_ , typename PermutationIndex_ > typedef internal::plain_col_type<MatrixType, PermutationIndex>::type Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::IntColVectorType
IntRowVectorType
template<typename MatrixType_ , typename PermutationIndex_ > typedef internal::plain_row_type<MatrixType, PermutationIndex>::type Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::IntRowVectorType
MatrixType
template<typename MatrixType_ , typename PermutationIndex_ > typedef MatrixType_ Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::MatrixType
PermutationIndex
template<typename MatrixType_ , typename PermutationIndex_ > using Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::PermutationIndex = PermutationIndex_
PermutationPType
template<typename MatrixType_ , typename PermutationIndex_ > typedef PermutationMatrix<RowsAtCompileTime, MaxRowsAtCompileTime, PermutationIndex> Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::PermutationPType
PermutationQType
template<typename MatrixType_ , typename PermutationIndex_ > typedef PermutationMatrix<ColsAtCompileTime, MaxColsAtCompileTime, PermutationIndex> Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::PermutationQType
PlainObject
template<typename MatrixType_ , typename PermutationIndex_ > typedef MatrixType::PlainObject Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::PlainObject
Member Enumeration Documentation
anonymous enum
template<typename MatrixType_ , typename PermutationIndex_ > anonymous enum
Enumerator
MaxRowsAtCompileTime
MaxColsAtCompileTime
        {
     MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime,
     MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime
   };
Constructor & Destructor Documentation
FullPivLU() [1/4]
template<typename MatrixType , typename PermutationIndex > Eigen::FullPivLU< MatrixType, PermutationIndex >::FullPivLU
Default Constructor.
The default constructor is useful in cases in which the user intends to perform decompositions via LU::compute(const MatrixType&).
 : m_isInitialized(false), m_usePrescribedThreshold(false) {}
FullPivLU() [2/4]
template<typename MatrixType , typename PermutationIndex > Eigen::FullPivLU< MatrixType, PermutationIndex >::FullPivLU (Index rows, Index cols)
Default Constructor with memory preallocation.
Like the default constructor but with preallocation of the internal data according to the specified problem size.
See also
FullPivLU()
     : m_lu(rows, cols),
       m_p(rows),
       m_q(cols),
       m_rowsTranspositions(rows),
       m_colsTranspositions(cols),
       m_isInitialized(false),
       m_usePrescribedThreshold(false) {}
FullPivLU() [3/4]
template<typename MatrixType , typename PermutationIndex > template<typename InputType > Eigen::FullPivLU< MatrixType, PermutationIndex >::FullPivLU (const EigenBase< InputType > & matrix) explicit
Constructor.
Parameters
matrix the matrix of which to compute the LU decomposition. It is required to be nonzero.
     : m_lu(matrix.rows(), matrix.cols()),
       m_p(matrix.rows()),
       m_q(matrix.cols()),
       m_rowsTranspositions(matrix.rows()),
       m_colsTranspositions(matrix.cols()),
       m_isInitialized(false),
       m_usePrescribedThreshold(false) {
   compute(matrix.derived());
 }
References Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::compute(), and matrix().
FullPivLU() [4/4]
template<typename MatrixType , typename PermutationIndex > template<typename InputType > Eigen::FullPivLU< MatrixType, PermutationIndex >::FullPivLU (EigenBase< InputType > & matrix) explicit
Constructs a LU factorization from a given matrix.
This overloaded constructor is provided for inplace decomposition when MatrixType is a Eigen::Ref.
See also
FullPivLU(const EigenBase&)
     : m_lu(matrix.derived()),
       m_p(matrix.rows()),
       m_q(matrix.cols()),
       m_rowsTranspositions(matrix.rows()),
       m_colsTranspositions(matrix.cols()),
       m_isInitialized(false),
       m_usePrescribedThreshold(false) {
   computeInPlace();
 }
References Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::computeInPlace().
Member Function Documentation
_solve_impl()
template<typename MatrixType_ , typename PermutationIndex_ > template<typename RhsType , typename DstType > void Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::_solve_impl (const RhsType & rhs, DstType & dst) const
{
   /* The decomposition PAQ = LU can be rewritten as A = P^{-1} L U Q^{-1}.
    * So we proceed as follows:
    * Step 1: compute c = P * rhs.
    * Step 2: replace c by the solution x to Lx = c. Exists because L is invertible.
    * Step 3: replace c by the solution x to Ux = c. May or may not exist.
    * Step 4: result = Q * c;
    */
   const Index rows = this->rows(), cols = this->cols(), nonzero_pivots = this->rank();
   const Index smalldim = (std::min)(rows, cols);
   if (nonzero_pivots == 0) {
     dst.setZero();
     return;
   }
   typename RhsType::PlainObject c(rhs.rows(), rhs.cols());
   // Step 1
   c = permutationP() * rhs;
   // Step 2
   m_lu.topLeftCorner(smalldim, smalldim).template triangularView<UnitLower>().solveInPlace(c.topRows(smalldim));
   if (rows > cols) c.bottomRows(rows - cols) -= m_lu.bottomRows(rows - cols) * c.topRows(cols);
   // Step 3
   m_lu.topLeftCorner(nonzero_pivots, nonzero_pivots)
       .template triangularView<Upper>()
       .solveInPlace(c.topRows(nonzero_pivots));
   // Step 4
   for (Index i = 0; i < nonzero_pivots; ++i) dst.row(permutationQ().indices().coeff(i)) = c.row(i);
   for (Index i = nonzero_pivots; i < m_lu.cols(); ++i) dst.row(permutationQ().indices().coeff(i)).setZero();
 }
References calibrate::c, cols, i, min, and rows.
_solve_impl_transposed()
template<typename MatrixType_ , typename PermutationIndex_ > template<bool Conjugate, typename RhsType , typename DstType > void Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::_solve_impl_transposed (const RhsType & rhs, DstType & dst) const
{
   /* The decomposition PAQ = LU can be rewritten as A = P^{-1} L U Q^{-1},
    * and since permutations are real and unitary, we can write this
    * as   A^T = Q U^T L^T P,
    * So we proceed as follows:
    * Step 1: compute c = Q^T rhs.
    * Step 2: replace c by the solution x to U^T x = c. May or may not exist.
    * Step 3: replace c by the solution x to L^T x = c.
    * Step 4: result = P^T c.
    * If Conjugate is true, replace "^T" by "^*" above.
    */
   const Index rows = this->rows(), cols = this->cols(), nonzero_pivots = this->rank();
   const Index smalldim = (std::min)(rows, cols);
   if (nonzero_pivots == 0) {
     dst.setZero();
     return;
   }
   typename RhsType::PlainObject c(rhs.rows(), rhs.cols());
   // Step 1
   c = permutationQ().inverse() * rhs;
   // Step 2
   m_lu.topLeftCorner(nonzero_pivots, nonzero_pivots)
       .template triangularView<Upper>()
       .transpose()
       .template conjugateIf<Conjugate>()
       .solveInPlace(c.topRows(nonzero_pivots));
   // Step 3
   m_lu.topLeftCorner(smalldim, smalldim)
       .template triangularView<UnitLower>()
       .transpose()
       .template conjugateIf<Conjugate>()
       .solveInPlace(c.topRows(smalldim));
   // Step 4
   PermutationPType invp = permutationP().inverse().eval();
   for (Index i = 0; i < smalldim; ++i) dst.row(invp.indices().coeff(i)) = c.row(i);
   for (Index i = smalldim; i < rows; ++i) dst.row(invp.indices().coeff(i)).setZero();
 }
References calibrate::c, cols, i, Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ >::indices(), Eigen::PermutationBase< Derived >::inverse(), min, and rows.
cols()
template<typename MatrixType_ , typename PermutationIndex_ > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::cols () const inline
 { return m_lu.cols(); }
References Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_lu.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::dimensionOfKernel(), Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::isInjective(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
compute()
template<typename MatrixType_ , typename PermutationIndex_ > template<typename InputType > FullPivLU& Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::compute (const EigenBase< InputType > & matrix) inline
Computes the LU decomposition of the given matrix.
Parameters
matrix the matrix of which to compute the LU decomposition. It is required to be nonzero.
Returns
a reference to *this
{
     m_lu = matrix.derived();
     computeInPlace();
     return *this;
   }
References Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::computeInPlace(), Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_lu, and matrix().
Referenced by ctms_decompositions(), Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::FullPivLU(), Eigen::internal::idrs(), and Eigen::internal::idrstabl().
computeInPlace()
template<typename MatrixType , typename PermutationIndex > void Eigen::FullPivLU< MatrixType, PermutationIndex >::computeInPlace protected
{
   eigen_assert(m_lu.rows() <= NumTraits<PermutationIndex>::highest() &&
                m_lu.cols() <= NumTraits<PermutationIndex>::highest());
   m_l1_norm = m_lu.cwiseAbs().colwise().sum().maxCoeff();
   const Index size = m_lu.diagonalSize();
   const Index rows = m_lu.rows();
   const Index cols = m_lu.cols();
   // will store the transpositions, before we accumulate them at the end.
   // can't accumulate on-the-fly because that will be done in reverse order for the rows.
   m_rowsTranspositions.resize(m_lu.rows());
   m_colsTranspositions.resize(m_lu.cols());
   Index number_of_transpositions = 0;  // number of NONTRIVIAL transpositions, i.e. m_rowsTranspositions[i]!=i
   m_nonzero_pivots = size;  // the generic case is that in which all pivots are nonzero (invertible case)
   m_maxpivot = RealScalar(0);
   for (Index k = 0; k < size; ++k) {
     // First, we need to find the pivot.
     // biggest coefficient in the remaining bottom-right corner (starting at row k, col k)
     Index row_of_biggest_in_corner, col_of_biggest_in_corner;
     typedef internal::scalar_score_coeff_op<Scalar> Scoring;
     typedef typename Scoring::result_type Score;
     Score biggest_in_corner;
     biggest_in_corner = m_lu.bottomRightCorner(rows - k, cols - k)
                             .unaryExpr(Scoring())
                             .maxCoeff(&row_of_biggest_in_corner, &col_of_biggest_in_corner);
     row_of_biggest_in_corner += k;  // correct the values! since they were computed in the corner,
     col_of_biggest_in_corner += k;  // need to add k to them.
     if (numext::is_exactly_zero(biggest_in_corner)) {
       // before exiting, make sure to initialize the still uninitialized transpositions
       // in a sane state without destroying what we already have.
       m_nonzero_pivots = k;
       for (Index i = k; i < size; ++i) {
         m_rowsTranspositions.coeffRef(i) = internal::convert_index<StorageIndex>(i);
         m_colsTranspositions.coeffRef(i) = internal::convert_index<StorageIndex>(i);
       }
       break;
     }
     RealScalar abs_pivot = internal::abs_knowing_score<Scalar>()(
         m_lu(row_of_biggest_in_corner, col_of_biggest_in_corner), biggest_in_corner);
     if (abs_pivot > m_maxpivot) m_maxpivot = abs_pivot;
     // Now that we've found the pivot, we need to apply the row/col swaps to
     // bring it to the location (k,k).
     m_rowsTranspositions.coeffRef(k) = internal::convert_index<StorageIndex>(row_of_biggest_in_corner);
     m_colsTranspositions.coeffRef(k) = internal::convert_index<StorageIndex>(col_of_biggest_in_corner);
     if (k != row_of_biggest_in_corner) {
       m_lu.row(k).swap(m_lu.row(row_of_biggest_in_corner));
       ++number_of_transpositions;
     }
     if (k != col_of_biggest_in_corner) {
       m_lu.col(k).swap(m_lu.col(col_of_biggest_in_corner));
       ++number_of_transpositions;
     }
     // Now that the pivot is at the right location, we update the remaining
     // bottom-right corner by Gaussian elimination.
     if (k < rows - 1) m_lu.col(k).tail(rows - k - 1) /= m_lu.coeff(k, k);
     if (k < size - 1)
       m_lu.block(k + 1, k + 1, rows - k - 1, cols - k - 1).noalias() -=
           m_lu.col(k).tail(rows - k - 1) * m_lu.row(k).tail(cols - k - 1);
   }
   // the main loop is over, we still have to accumulate the transpositions to find the
   // permutations P and Q
   m_p.setIdentity(rows);
   for (Index k = size - 1; k >= 0; --k) m_p.applyTranspositionOnTheRight(k, m_rowsTranspositions.coeff(k));
   m_q.setIdentity(cols);
   for (Index k = 0; k < size; ++k) m_q.applyTranspositionOnTheRight(k, m_colsTranspositions.coeff(k));
   m_det_pq = (number_of_transpositions % 2) ? -1 : 1;
   m_isInitialized = true;
 }
References cols, eigen_assert, i, Eigen::numext::is_exactly_zero(), k, rows, and size.
Referenced by Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::compute(), and Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::FullPivLU().
determinant()
template<typename MatrixType , typename PermutationIndex > internal::traits< MatrixType >::Scalar Eigen::FullPivLU< MatrixType, PermutationIndex >::determinant
Returns
the determinant of the matrix of which *this is the LU decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the LU decomposition has already been computed.
Note
This is only for square matrices.
For fixed-size matrices of size up to 4, MatrixBase::determinant() offers optimized paths.
Warning
a determinant can be very big or small, so for matrices of large enough dimension, there is a risk of overflow/underflow.
See also
MatrixBase::determinant()
{
   eigen_assert(m_isInitialized && "LU is not initialized.");
   eigen_assert(m_lu.rows() == m_lu.cols() && "You can't take the determinant of a non-square matrix!");
   return Scalar(m_det_pq) * Scalar(m_lu.diagonal().prod());
 }
References eigen_assert.
dimensionOfKernel()
template<typename MatrixType_ , typename PermutationIndex_ > Index Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::dimensionOfKernel () const inline
Returns
the dimension of the kernel of the matrix of which *this is the LU decomposition.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
{
     eigen_assert(m_isInitialized && "LU is not initialized.");
     return cols() - rank();
   }
References Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::cols(), eigen_assert, Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_isInitialized, and Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::rank().
image()
template<typename MatrixType_ , typename PermutationIndex_ > const internal::image_retval<FullPivLU> Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::image (const MatrixType & originalMatrix) const inline
Returns
the image of the matrix, also called its column-space. The columns of the returned matrix will form a basis of the image (column-space).
Parameters
originalMatrix the original matrix, of which *this is the LU decomposition. The reason why it is needed to pass it here, is that this allows a large optimization, as otherwise this method would need to reconstruct it from the LU decomposition.
Note
If the image has dimension zero, then the returned matrix is a column-vector filled with zeros.
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
Example:
Matrix3d m;
m << 1, 1, 0, 1, 3, 2, 0, 1, 1;
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Notice that the middle column is the sum of the two others, so the "
     << "columns are linearly dependent." << endl;
cout << "Here is a matrix whose columns have the same span but are linearly independent:" << endl
     << m.fullPivLu().image(m) << endl;
Output:
See also
kernel()
{
     eigen_assert(m_isInitialized && "LU is not initialized.");
     return internal::image_retval<FullPivLU>(*this, originalMatrix);
   }
References eigen_assert, and Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_isInitialized.
Referenced by main().
inverse()
template<typename MatrixType_ , typename PermutationIndex_ > const Inverse<FullPivLU> Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::inverse () const inline
Returns
the inverse of the matrix of which *this is the LU decomposition.
Note
If this matrix is not invertible, the returned matrix has undefined coefficients. Use isInvertible() to first determine whether this matrix is invertible.
See also
MatrixBase::inverse()
{
     eigen_assert(m_isInitialized && "LU is not initialized.");
     eigen_assert(m_lu.rows() == m_lu.cols() && "You can't take the inverse of a non-square matrix!");
     return Inverse<FullPivLU>(*this);
   }
References eigen_assert, Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_isInitialized, and Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_lu.
isInjective()
template<typename MatrixType_ , typename PermutationIndex_ > bool Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::isInjective () const inline
Returns
true if the matrix of which *this is the LU decomposition represents an injective linear map, i.e. has trivial kernel; false otherwise.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
{
     eigen_assert(m_isInitialized && "LU is not initialized.");
     return rank() == cols();
   }
References Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::cols(), eigen_assert, Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_isInitialized, and Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::rank().
Referenced by Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::isInvertible().
isInvertible()
template<typename MatrixType_ , typename PermutationIndex_ > bool Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::isInvertible () const inline
Returns
true if the matrix of which *this is the LU decomposition is invertible.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
{
     eigen_assert(m_isInitialized && "LU is not initialized.");
     return isInjective() && (m_lu.rows() == m_lu.cols());
   }
References eigen_assert, Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::isInjective(), Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_isInitialized, and Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_lu.
Referenced by inverse_general_4x4().
isSurjective()
template<typename MatrixType_ , typename PermutationIndex_ > bool Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::isSurjective () const inline
Returns
true if the matrix of which *this is the LU decomposition represents a surjective linear map; false otherwise.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
{
     eigen_assert(m_isInitialized && "LU is not initialized.");
     return rank() == rows();
   }
References eigen_assert, Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_isInitialized, Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::rank(), and Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::rows().
kernel()
template<typename MatrixType_ , typename PermutationIndex_ > const internal::kernel_retval<FullPivLU> Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::kernel () const inline
Returns
the kernel of the matrix, also called its null-space. The columns of the returned matrix will form a basis of the kernel.
Note
If the kernel has dimension zero, then the returned matrix is a column-vector filled with zeros.
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
Example:
MatrixXf m = MatrixXf::Random(3, 5);
cout << "Here is the matrix m:" << endl << m << endl;
MatrixXf ker = m.fullPivLu().kernel();
cout << "Here is a matrix whose columns form a basis of the kernel of m:" << endl << ker << endl;
cout << "By definition of the kernel, m*ker is zero:" << endl << m * ker << endl;
Output:
See also
image()
{
     eigen_assert(m_isInitialized && "LU is not initialized.");
     return internal::kernel_retval<FullPivLU>(*this);
   }
References eigen_assert, and Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_isInitialized.
Referenced by main().
matrixLU()
template<typename MatrixType_ , typename PermutationIndex_ > const MatrixType& Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::matrixLU () const inline
Returns
the LU decomposition matrix: the upper-triangular part is U, the unit-lower-triangular part is L (at least for square matrices; in the non-square case, special care is needed, see the documentation of class FullPivLU).
See also
matrixL(), matrixU()
{
     eigen_assert(m_isInitialized && "LU is not initialized.");
     return m_lu;
   }
References eigen_assert, Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_isInitialized, and Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_lu.
maxPivot()
template<typename MatrixType_ , typename PermutationIndex_ > RealScalar Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::maxPivot () const inline
Returns
the absolute value of the biggest pivot, i.e. the biggest diagonal coefficient of U.
 { return m_maxpivot; }
References Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_maxpivot.
nonzeroPivots()
template<typename MatrixType_ , typename PermutationIndex_ > Index Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::nonzeroPivots () const inline
Returns
the number of nonzero pivots in the LU decomposition. Here nonzero is meant in the exact sense, not in a fuzzy sense. So that notion isn't really intrinsically interesting, but it is still useful when implementing algorithms.
See also
rank()
{
     eigen_assert(m_isInitialized && "LU is not initialized.");
     return m_nonzero_pivots;
   }
References eigen_assert, Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_isInitialized, and Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_nonzero_pivots.
permutationP()
template<typename MatrixType_ , typename PermutationIndex_ > EIGEN_DEVICE_FUNC const PermutationPType& Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::permutationP () const inline
Returns
the permutation matrix P
See also
permutationQ()
{
     eigen_assert(m_isInitialized && "LU is not initialized.");
     return m_p;
   }
References eigen_assert, Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_isInitialized, and Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_p.
permutationQ()
template<typename MatrixType_ , typename PermutationIndex_ > const PermutationQType& Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::permutationQ () const inline
Returns
the permutation matrix Q
See also
permutationP()
{
     eigen_assert(m_isInitialized && "LU is not initialized.");
     return m_q;
   }
References eigen_assert, Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_isInitialized, and Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_q.
rank()
template<typename MatrixType_ , typename PermutationIndex_ > Index Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::rank () const inline
Returns
the rank of the matrix of which *this is the LU decomposition.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
{
     using std::abs;
     eigen_assert(m_isInitialized && "LU is not initialized.");
     RealScalar premultiplied_threshold = abs(m_maxpivot) * threshold();
     Index result = 0;
     for (Index i = 0; i < m_nonzero_pivots; ++i) result += (abs(m_lu.coeff(i, i)) > premultiplied_threshold);
     return result;
   }
References abs(), eigen_assert, i, Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_isInitialized, Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_lu, Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_maxpivot, Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_nonzero_pivots, and Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::threshold().
Referenced by Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::dimensionOfKernel(), Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::isInjective(), Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::isSurjective(), and main().
rcond()
template<typename MatrixType_ , typename PermutationIndex_ > RealScalar Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::rcond () const inline
Returns
an estimate of the reciprocal condition number of the matrix of which *this is the LU decomposition.
{
     eigen_assert(m_isInitialized && "PartialPivLU is not initialized.");
     return internal::rcond_estimate_helper(m_l1_norm, *this);
   }
References eigen_assert, Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_isInitialized, Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_l1_norm, and Eigen::internal::rcond_estimate_helper().
reconstructedMatrix()
template<typename MatrixType , typename PermutationIndex > MatrixType Eigen::FullPivLU< MatrixType, PermutationIndex >::reconstructedMatrix
Returns
the matrix represented by the decomposition, i.e., it returns the product: \(P^{-1} L U Q^{-1} \). This function is provided for debug purposes.
{
   eigen_assert(m_isInitialized && "LU is not initialized.");
   const Index smalldim = (std::min)(m_lu.rows(), m_lu.cols());
   // LU
   MatrixType res(m_lu.rows(), m_lu.cols());
   // FIXME the .toDenseMatrix() should not be needed...
   res = m_lu.leftCols(smalldim).template triangularView<UnitLower>().toDenseMatrix() *
         m_lu.topRows(smalldim).template triangularView<Upper>().toDenseMatrix();
   // P^{-1}(LU)
   res = m_p.inverse() * res;
   // (P^{-1}LU)Q^{-1}
   res = res * m_q.inverse();
   return res;
 }
References eigen_assert, min, and res.
rows()
template<typename MatrixType_ , typename PermutationIndex_ > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::rows () const inline
 { return m_lu.rows(); }
References Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_lu.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::isSurjective(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
setThreshold() [1/2]
template<typename MatrixType_ , typename PermutationIndex_ > FullPivLU& Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::setThreshold (const RealScalar & threshold) inline
Allows to prescribe a threshold to be used by certain methods, such as rank(), who need to determine when pivots are to be considered nonzero. This is not used for the LU decomposition itself.
When it needs to get the threshold value, Eigen calls threshold(). By default, this uses a formula to automatically determine a reasonable threshold. Once you have called the present method setThreshold(const RealScalar&), your value is used instead.
Parameters
threshold The new value to use as the threshold.
A pivot will be considered nonzero if its absolute value is strictly greater than \(\vert pivot \vert \leqslant threshold \times \vert maxpivot \vert \) where maxpivot is the biggest pivot.
If you want to come back to the default behavior, call setThreshold(Default_t)
{
     m_usePrescribedThreshold = true;
     m_prescribedThreshold = threshold;
     return *this;
   }
References Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_prescribedThreshold, Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_usePrescribedThreshold, and Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::threshold().
setThreshold() [2/2]
template<typename MatrixType_ , typename PermutationIndex_ > FullPivLU& Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::setThreshold (Default_t) inline
Allows to come back to the default behavior, letting Eigen use its default formula for determining the threshold.
You should pass the special object Eigen::Default as parameter here.
lu.setThreshold(Eigen::Default);
See the documentation of setThreshold(const RealScalar&).
{
     m_usePrescribedThreshold = false;
     return *this;
   }
References Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_usePrescribedThreshold.
threshold()
template<typename MatrixType_ , typename PermutationIndex_ > RealScalar Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::threshold () const inline
Returns the threshold that will be used by certain methods such as rank().
See the documentation of setThreshold(const RealScalar&).
{
     eigen_assert(m_isInitialized || m_usePrescribedThreshold);
     return m_usePrescribedThreshold ? m_prescribedThreshold
                                     // this formula comes from experimenting (see "LU precision tuning" thread on the
                                     // list) and turns out to be identical to Higham's formula used already in LDLt.
                                     : NumTraits<Scalar>::epsilon() * RealScalar(m_lu.diagonalSize());
   }
References eigen_assert, oomph::SarahBL::epsilon, Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_isInitialized, Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_lu, Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_prescribedThreshold, and Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_usePrescribedThreshold.
Referenced by Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::rank(), and Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::setThreshold().
Friends And Related Function Documentation
SolverBase< FullPivLU >
template<typename MatrixType_ , typename PermutationIndex_ > friend class SolverBase< FullPivLU > friend
Member Data Documentation
m_colsTranspositions
template<typename MatrixType_ , typename PermutationIndex_ > IntRowVectorType Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_colsTranspositions protected
m_det_pq
template<typename MatrixType_ , typename PermutationIndex_ > signed char Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_det_pq protected
m_isInitialized
template<typename MatrixType_ , typename PermutationIndex_ > bool Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_isInitialized protected
Referenced by Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::dimensionOfKernel(), Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::image(), Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::inverse(), Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::isInjective(), Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::isInvertible(), Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::isSurjective(), Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::kernel(), Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::matrixLU(), Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::nonzeroPivots(), Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::permutationP(), Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::permutationQ(), Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::rank(), Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::rcond(), and Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::threshold().
m_l1_norm
template<typename MatrixType_ , typename PermutationIndex_ > RealScalar Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_l1_norm protected
Referenced by Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::rcond().
m_lu
template<typename MatrixType_ , typename PermutationIndex_ > MatrixType Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_lu protected
Referenced by Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::cols(), Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::compute(), Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::inverse(), Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::isInvertible(), Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::matrixLU(), Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::rank(), Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::rows(), and Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::threshold().
m_maxpivot
template<typename MatrixType_ , typename PermutationIndex_ > RealScalar Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_maxpivot protected
Referenced by Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::maxPivot(), and Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::rank().
m_nonzero_pivots
template<typename MatrixType_ , typename PermutationIndex_ > Index Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_nonzero_pivots protected
Referenced by Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::nonzeroPivots(), and Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::rank().
m_p
template<typename MatrixType_ , typename PermutationIndex_ > PermutationPType Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_p protected
Referenced by Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::permutationP().
m_prescribedThreshold
template<typename MatrixType_ , typename PermutationIndex_ > RealScalar Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_prescribedThreshold protected
Referenced by Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::setThreshold(), and Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::threshold().
m_q
template<typename MatrixType_ , typename PermutationIndex_ > PermutationQType Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_q protected
Referenced by Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::permutationQ().
m_rowsTranspositions
template<typename MatrixType_ , typename PermutationIndex_ > IntColVectorType Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_rowsTranspositions protected
m_usePrescribedThreshold
template<typename MatrixType_ , typename PermutationIndex_ > bool Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::m_usePrescribedThreshold protected
Referenced by Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::setThreshold(), and Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::threshold().
The documentation for this class was generated from the following files:
ForwardDeclarations.h
FullPivLU.h