MercuryDPM: Eigen::internal::generic_y0< T, double > Struct Template Reference
Eigen::internal::generic_y0< T, double > Struct Template Reference
#include <BesselFunctionsImpl.h>
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T run (const T &x)
Member Function Documentation
run()
template<typename T > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T Eigen::internal::generic_y0< T, double >::run (const T & x) inline static
{
     /*  j0.c
      *  Bessel function of the second kind, order zero
      *
      *
      *
      * SYNOPSIS:
      *
      * double x, y, y0();
      *
      * y = y0( x );
      *
      *
      *
      * DESCRIPTION:
      *
      * Returns Bessel function of the second kind, of order
      * zero, of the argument.
      *
      * The domain is divided into the intervals [0, 5] and
      * (5, infinity). In the first interval a rational approximation
      * R(x) is employed to compute
      *   y0(x)  = R(x)  +   2 * log(x) * j0(x) / PI.
      * Thus a call to j0() is required.
      *
      * In the second interval, the Hankel asymptotic expansion
      * is employed with two rational functions of degree 6/6
      * and 7/7.
      *
      *
      *
      * ACCURACY:
      *
      *  Absolute error, when y0(x) < 1; else relative error:
      *
      * arithmetic   domain     # trials      peak         rms
      *    DEC       0, 30        9400       7.0e-17     7.9e-18
      *    IEEE      0, 30       30000       1.3e-15     1.6e-16
      *
      */
     const double PP[] = {7.96936729297347051624E-4, 8.28352392107440799803E-2, 1.23953371646414299388E0,
                          5.44725003058768775090E0,  8.74716500199817011941E0,  5.30324038235394892183E0,
                          9.99999999999999997821E-1};
     const double PQ[] = {9.24408810558863637013E-4, 8.56288474354474431428E-2, 1.25352743901058953537E0,
                          5.47097740330417105182E0,  8.76190883237069594232E0,  5.30605288235394617618E0,
                          1.00000000000000000218E0};
     const double QP[] = {-1.13663838898469149931E-2, -1.28252718670509318512E0, -1.95539544257735972385E1,
                          -9.32060152123768231369E1,  -1.77681167980488050595E2, -1.47077505154951170175E2,
                          -5.14105326766599330220E1,  -6.05014350600728481186E0};
     const double QQ[] = {1.00000000000000000000E0, 6.43178256118178023184E1, 8.56430025976980587198E2,
                          3.88240183605401609683E3, 7.24046774195652478189E3, 5.93072701187316984827E3,
                          2.06209331660327847417E3, 2.42005740240291393179E2};
     const double YP[] = {1.55924367855235737965E4,   -1.46639295903971606143E7, 5.43526477051876500413E9,
                          -9.82136065717911466409E11, 8.75906394395366999549E13, -3.46628303384729719441E15,
                          4.42733268572569800351E16,  -1.84950800436986690637E16};
     const double YQ[] = {1.00000000000000000000E0,  1.04128353664259848412E3,  6.26107330137134956842E5,
                          2.68919633393814121987E8,  8.64002487103935000337E10, 2.02979612750105546709E13,
                          3.17157752842975028269E15, 2.50596256172653059228E17};
     const T SQ2OPI = pset1<T>(7.9788456080286535587989E-1); /* sqrt(2 / pi) */
     const T TWOOPI = pset1<T>(0.636619772367581343075535);  /* 2 / pi */
     const T NEG_PIO4 = pset1<T>(-0.7853981633974483096);    /* -pi / 4 */
     const T NEG_MAXNUM = pset1<T>(-NumTraits<double>::infinity());
     T z = pmul(x, x);
     T x_le_five = pdiv(internal::ppolevl<T, 7>::run(z, YP), internal::ppolevl<T, 7>::run(z, YQ));
     x_le_five = pmadd(pmul(TWOOPI, plog(x)), generic_j0<T, double>::run(x), x_le_five);
     x_le_five = pselect(pcmp_le(x, pset1<T>(0.0)), NEG_MAXNUM, x_le_five);
     T s = pdiv(pset1<T>(25.0), z);
     T p = pdiv(internal::ppolevl<T, 6>::run(s, PP), internal::ppolevl<T, 6>::run(s, PQ));
     T q = pdiv(internal::ppolevl<T, 7>::run(s, QP), internal::ppolevl<T, 7>::run(s, QQ));
     T xn = padd(x, NEG_PIO4);
     T w = pdiv(pset1<T>(5.0), x);
     p = pmadd(p, psin(xn), pmul(w, pmul(q, pcos(xn))));
     T x_gt_five = pmul(p, pmul(SQ2OPI, prsqrt(x)));
     return pselect(pcmp_le(x, pset1<T>(5.0)), x_le_five, x_gt_five);
   }
References p, Eigen::internal::padd(), Eigen::internal::pcmp_le(), Eigen::internal::pcos(), Eigen::internal::pdiv(), Eigen::internal::plog(), Eigen::internal::pmadd(), Eigen::internal::pmul(), Eigen::internal::prsqrt(), Eigen::internal::pselect(), Eigen::internal::psin(), Eigen::numext::q, s, w, and plotDoE::x.
The documentation for this struct was generated from the following file:
BesselFunctionsImpl.h