MercuryDPM: PeriodicWallsWithSlidingFrictionUnitTest.cpp File Reference
PeriodicWallsWithSlidingFrictionUnitTest.cpp File Reference
#include "Species/LinearViscoelasticSlidingFrictionSpecies.h"
#include "Species/LinearViscoelasticFrictionSpecies.h"
#include "Mercury2D.h"
#include "Boundaries/PeriodicBoundary.h"
#include <Logger.h>
Classes
class PeriodicWallsWithSlidingFrictionUnitTest
Functions
int main (int argc UNUSED, char *argv[] UNUSED)
Function Documentation
main()
int main (int argc UNUSED, char *argv[] UNUSED)
Start off by solving the default problem
 {
     PeriodicWallsWithSlidingFrictionUnitTest periodicWallsWithSlidingFrictionUnitTest;
     periodicWallsWithSlidingFrictionUnitTest.setName("PeriodicWallsWithSlidingFrictionUnitTest");
     periodicWallsWithSlidingFrictionUnitTest.solve();
     BaseParticle* pNormal = periodicWallsWithSlidingFrictionUnitTest.particleHandler.getObject(4);
     BaseParticle* pCase1 = periodicWallsWithSlidingFrictionUnitTest.particleHandler.getObject(0);
     BaseParticle* pCase2 = periodicWallsWithSlidingFrictionUnitTest.particleHandler.getObject(2);
     Vec3D shift;
     shift = Vec3D(-0.58, -0.4, 0.0);
     if (!pCase1->getPosition().isEqualTo(pNormal->getPosition() + shift, 1e-10))
     {
         logger(FATAL, "E0 The particle is in the wrong position. It is %, however is should be %",
                pCase1->getPosition(), pNormal->getPosition() + shift);
     }
     if (!pCase1->getVelocity().isEqualTo(pNormal->getVelocity(), 1e-10))
     {
         logger(FATAL, "E1 The particle has the wrong velocity. It is %, however is should be %", pCase1->getVelocity(),
                pNormal->getVelocity());
     }
     shift = Vec3D(0.0, -0.779, 0.0);
     if (!pCase2->getPosition().isEqualTo(pNormal->getPosition() + shift, 1e-10))
     {
         logger(FATAL, "E2 The particle is in the wrong position. It is %, however is should be %",
                pCase2->getPosition(), pNormal->getPosition() + shift);
     }
     if (!pCase2->getVelocity().isEqualTo(pNormal->getVelocity(), 1e-10))
     {
         logger(FATAL, "E3 The particle has the wrong velocity. It is %, however is should be %", pCase2->getVelocity(),
                pNormal->getVelocity());
     }
     pNormal = periodicWallsWithSlidingFrictionUnitTest.particleHandler.getObject(5);
     pCase1 = periodicWallsWithSlidingFrictionUnitTest.particleHandler.getObject(1);
     pCase2 = periodicWallsWithSlidingFrictionUnitTest.particleHandler.getObject(3);
     shift = Vec3D(1.0 - 0.58, -0.4, 0.0);
     if (!pCase1->getPosition().isEqualTo(pNormal->getPosition() + shift, 1e-10))
     {
         logger(FATAL, "E4 The particle is in the wrong position. It is %, however is should be %",
                pCase1->getPosition(), pNormal->getPosition() + shift);
     }
     if (!pCase1->getVelocity().isEqualTo(pNormal->getVelocity(), 1e-10))
     {
         logger(FATAL, "E5 The particle has the wrong velocity. It is %, however is should be %", pCase1->getVelocity(),
                pNormal->getVelocity());
     }
     shift = Vec3D(0.0, 1.0 - 0.779, 0.0);
     if (!pCase2->getPosition().isEqualTo(pNormal->getPosition() + shift, 1e-10))
     {
         logger(FATAL, "E6 The particle is in the wrong position. It is %, however is should be %",
                pCase2->getPosition(), pNormal->getPosition() + shift);
     }
     if (!pCase2->getVelocity().isEqualTo(pNormal->getVelocity(), 1e-10))
     {
         logger(FATAL, "E7 The particle has the wrong velocity. It is %, however is should be %", pCase2->getVelocity(),
                pNormal->getVelocity());
     }
 }
References e(), FATAL, BaseHandler< T >::getObject(), BaseInteractable::getPosition(), BaseInteractable::getVelocity(), Vec3D::isEqualTo(), logger, DPMBase::particleHandler, DPMBase::setName(), and DPMBase::solve().