MercuryDPM: c_style_output.cc File Reference
c_style_output.cc File Reference
#include "generic.h"
#include "navier_stokes.h"
#include "poisson.h"
#include "unsteady_heat.h"
#include "solid.h"
#include "beam.h"
#include "meshes/one_d_lagrangian_mesh.h"
#include "meshes/quarter_circle_sector_mesh.h"
#include "meshes/simple_rectangular_quadmesh.h"
#include "meshes/quarter_tube_mesh.h"
Classes
class ElasticRefineableQuarterCircleSectorMesh< ELEMENT >
class SimpleRefineableRectangularQuadMesh< ELEMENT >
Functions
void output_both_versions (const string &file_root, Mesh *mesh_pt, const unsigned &npts)
Global output function to compare C++ and C-style output routines.
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
///////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////// Ugly driver code – brutally loop over lots of mesh/element combinations and produce C/C++-style output.
///////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////
 {
  unsigned nplot=5;
  unsigned nelem=1000;
  {
   // Set the undeformed beam to be a straight line at y=0
   GeomObject* undef_beam_pt=new StraightLine(0.0);
   // Build and assign mesh
   double L=1.0;
   Mesh* mesh_pt =
    new OneDLagrangianMesh<HermiteBeamElement>(nelem,L,undef_beam_pt);
   //Assign undeformed geometry
   for(unsigned i=0;i<nelem;i++)
    {
     //Cast to proper element type
     HermiteBeamElement* elem_pt =
      dynamic_cast<HermiteBeamElement*>(mesh_pt->element_pt(i));
     //Assign the undeformed beam shape
     elem_pt->undeformed_beam_pt() = undef_beam_pt;
    }
   // Filename for output
   string file_root="beam";
   // Compare output
   output_both_versions(file_root,mesh_pt,nplot);
   delete mesh_pt;
  }
  {
   // Build the geometric object that describes the outer wall
   GeomObject* curved_boundary_pt = new Ellipse(1.0,1.0);
   // The curved boundary of the mesh is defined by the geometric object
   // What follows are the start and end coordinates on the geometric object:
   double xi_lo=0.0;
   double xi_hi=2.0*atan(1.0);
   // Fraction along geometric object at which the radial dividing line
   // is placed
   double fract_mid=0.5;
   //--------------------------------------------------
   {
    // Build and assign mesh
    Mesh* mesh_pt =
     new ElasticRefineableQuarterCircleSectorMesh<RefineableQPVDElement<2,2> >
     (curved_boundary_pt,xi_lo,fract_mid,xi_hi);
    // Filename for output
    string file_root="adapt_solid_pvd_2";
    // Compare output
    output_both_versions(file_root,mesh_pt,nplot);
    delete mesh_pt;
   }
   //--------------------------------------------------
   {
    // Build and assign mesh
    Mesh* mesh_pt =
     new ElasticRefineableQuarterCircleSectorMesh<RefineableQPVDElement<2,3> >
     (curved_boundary_pt,xi_lo,fract_mid,xi_hi);
    // Filename for output
    string file_root="adapt_solid_pvd_3";
    // Compare output
    output_both_versions(file_root,mesh_pt,nplot);
    delete mesh_pt;
   }
   //--------------------------------------------------
   {
    // Build and assign mesh
    Mesh* mesh_pt =
     new ElasticRefineableQuarterCircleSectorMesh<RefineableQPVDElement<2,4> >
     (curved_boundary_pt,xi_lo,fract_mid,xi_hi);
    // Filename for output
    string file_root="adapt_solid_pvd_4";
    // Compare output
    output_both_versions(file_root,mesh_pt,nplot);
    delete mesh_pt;
   }
   //--------------------------------------------------
   {
    // Build and assign mesh
    Mesh* mesh_pt =
     new ElasticRefineableQuarterCircleSectorMesh
     <RefineableQPVDElementWithContinuousPressure<2> >(
      curved_boundary_pt,xi_lo,fract_mid,xi_hi);
    // Filename for output
    string file_root="adapt_solid_pvd_cp";
    // Compare output
    output_both_versions(file_root,mesh_pt,nplot);
    delete mesh_pt;
   }
   //--------------------------------------------------
   {
    // Build and assign mesh
    Mesh* mesh_pt =
     new ElasticRefineableQuarterCircleSectorMesh
     <RefineableQPVDElementWithPressure<2> >(
      curved_boundary_pt,xi_lo,fract_mid,xi_hi);
    // Filename for output
    string file_root="adapt_solid_pvd_p";
    // Compare output
    output_both_versions(file_root,mesh_pt,nplot);
    delete mesh_pt;
   }
  }
  // # of elements in x-direction
  unsigned n_x=10;
  // # of elements in y-direction
  unsigned n_y=10;
  // Domain length in x-direction
  double l_x=1.0;
  // Domain length in y-direction
  double l_y=2.0;
  // Create geom object
  double L_up=1.0;
  double L=5.0;
  double L_down=5.0;
  TimeStepper* time_stepper_pt=new Steady<0>;
   GeomObject* Wall_pt=new
    EllipticalTube(1.0,1.0);
  // Boundaries on object: quarter tube
  Vector<double> xi_lo(2);
  xi_lo[0]=0.0;
  xi_lo[1]=0.0;
  Vector<double> xi_hi(2);
  xi_hi[0]=L_up+L+L_down;
  xi_hi[1]=0.5*4.0*atan(1.0);
  double frac_mid=0.5;
  unsigned nlayer=11;
  //-------------------------------------------------------------
  {
   // Build and assign mesh
   Mesh* mesh_pt=new RefineableQuarterTubeMesh<RefineableQTaylorHoodElement<3> >
    (Wall_pt,xi_lo,frac_mid,xi_hi,nlayer,time_stepper_pt);
   // Filename for output
   string file_root="adapt_taylor_hood_3";
   // Compare output
   output_both_versions(file_root,mesh_pt,nplot);
   delete mesh_pt;
  }
  //-------------------------------------------------------------
  {
   // Build and assign mesh
   Mesh* mesh_pt=
    new RefineableQuarterTubeMesh<RefineableQCrouzeixRaviartElement<3> >(
     Wall_pt,xi_lo,frac_mid,xi_hi,nlayer,time_stepper_pt);
   // Filename for output
   string file_root="adapt_crozier_raviart_3";
   // Compare output
   output_both_versions(file_root,mesh_pt,nplot);
   delete mesh_pt;
  }
  //--------------------------------------------------
  {
   // Build and assign mesh
   Mesh* mesh_pt =
    new SimpleRectangularQuadMesh<QTaylorHoodElement<2> >(n_x,n_y,l_x,l_y);
   // Filename for output
   string file_root="taylor_hood_2";
   // Compare output
   output_both_versions(file_root,mesh_pt,nplot);
   delete mesh_pt;
  }
  //--------------------------------------------------
  {
   // Build and assign mesh
   Mesh* mesh_pt =
    new SimpleRectangularQuadMesh<QCrouzeixRaviartElement<2> >(n_x,n_y,l_x,l_y);
   // Filename for output
   string file_root="crozier_raviart_2";
   // Compare output
   output_both_versions(file_root,mesh_pt,nplot);
   delete mesh_pt;
  }
  //--------------------------------------------------
  {
   // Build and assign mesh
   Mesh* mesh_pt =
    new SimpleRefineableRectangularQuadMesh
    <RefineableQCrouzeixRaviartElement<2> >(n_x,n_y,l_x,l_y);
   // Filename for output
   string file_root="adapt_crozier_raviart_2";
   // Compare output
   output_both_versions(file_root,mesh_pt,nplot);
   delete mesh_pt;
  }
  //--------------------------------------------------
  {
   // Build and assign mesh
   Mesh* mesh_pt =
    new SimpleRefineableRectangularQuadMesh
    <RefineableQTaylorHoodElement<2> >(n_x,n_y,l_x,l_y);
   // Filename for output
   string file_root="adapt_taylor_hood_2";
   // Compare output
   output_both_versions(file_root,mesh_pt,nplot);
   delete mesh_pt;
  }
  //-------------------------------------------------------------
  {
   // Build and assign mesh
   Mesh* mesh_pt=new QuarterTubeMesh<QPoissonElement<3,2> >(
    Wall_pt,xi_lo,frac_mid,xi_hi,nlayer,time_stepper_pt);
   // Filename for output
   string file_root="poisson_3_2";
   // Compare output
   output_both_versions(file_root,mesh_pt,nplot);
   delete mesh_pt;
  }
  //-------------------------------------------------------------
  {
   // Build and assign mesh
   Mesh* mesh_pt=new QuarterTubeMesh<QPoissonElement<3,3> >(
    Wall_pt,xi_lo,frac_mid,xi_hi,nlayer,time_stepper_pt);
   // Filename for output
   string file_root="poisson_3_3";
   // Compare output
   output_both_versions(file_root,mesh_pt,nplot);
   delete mesh_pt;
  }
  //-------------------------------------------------------------
  {
   // Build and assign mesh
   Mesh* mesh_pt=new QuarterTubeMesh<QPoissonElement<3,4> >(
    Wall_pt,xi_lo,frac_mid,xi_hi,nlayer,time_stepper_pt);
   // Filename for output
   string file_root="poisson_3_4";
   // Compare output
   output_both_versions(file_root,mesh_pt,nplot);
   delete mesh_pt;
  }
  //-------------------------------------------------------------
  {
   // Build and assign mesh
   Mesh* mesh_pt=new RefineableQuarterTubeMesh<RefineableQPoissonElement<3,2> >(
    Wall_pt,xi_lo,frac_mid,xi_hi,nlayer,time_stepper_pt);
   // Filename for output
   string file_root="adapt_poisson_3_2";
   // Compare output
   output_both_versions(file_root,mesh_pt,nplot);
   delete mesh_pt;
  }
  //-------------------------------------------------------------
  {
   // Build and assign mesh
   Mesh* mesh_pt=new RefineableQuarterTubeMesh<RefineableQPoissonElement<3,3> >(
    Wall_pt,xi_lo,frac_mid,xi_hi,nlayer,time_stepper_pt);
   // Filename for output
   string file_root="adapt_poisson_3_3";
   // Compare output
   output_both_versions(file_root,mesh_pt,nplot);
   delete mesh_pt;
  }
  //-------------------------------------------------------------
  {
   // Build and assign mesh
   Mesh* mesh_pt=new RefineableQuarterTubeMesh<RefineableQPoissonElement<3,4> >(
    Wall_pt,xi_lo,frac_mid,xi_hi,nlayer,time_stepper_pt);
   // Filename for output
   string file_root="adapt_poisson_3_4";
   // Compare output
   output_both_versions(file_root,mesh_pt,nplot);
   delete mesh_pt;
  }
  //--------------------------------------------------
  {
   // Build mesh and store pointer
   Mesh* mesh_pt=new OneDMesh<QPoissonElement<1,2> >(nelem,1.0);
   // Filename for output
   string file_root="poisson_1_2";
   // Compare output
   output_both_versions(file_root,mesh_pt,nplot);
   delete mesh_pt;
  }
  //--------------------------------------------------
  {
   // Build mesh and store pointer
   Mesh* mesh_pt=new OneDMesh<QPoissonElement<1,3> >(nelem,1.0);
   // Filename for output
   string file_root="poisson_1_3";
   // Compare output
   output_both_versions(file_root,mesh_pt,nplot);
   delete mesh_pt;
  }
  //--------------------------------------------------
  {
   // Build mesh and store pointer
   Mesh* mesh_pt=new OneDMesh<QPoissonElement<1,4> >(nelem,1.0);
   // Filename for output
   string file_root="poisson_1_4";
   // Compare output
   output_both_versions(file_root,mesh_pt,nplot);
   delete mesh_pt;
  }
  //--------------------------------------------------
  {
   // Build and assign mesh
   Mesh* mesh_pt =
    new SimpleRectangularQuadMesh<QPoissonElement<2,2> >(n_x,n_y,l_x,l_y);
   // Filename for output
   string file_root="poisson_2_2";
   // Compare output
   output_both_versions(file_root,mesh_pt,nplot);
   delete mesh_pt;
  }
  //--------------------------------------------------
  {
   // Build and assign mesh
   Mesh* mesh_pt =
    new SimpleRectangularQuadMesh<QPoissonElement<2,3> >(n_x,n_y,l_x,l_y);
   // Filename for output
   string file_root="poisson_2_3";
   // Compare output
   output_both_versions(file_root,mesh_pt,nplot);
   delete mesh_pt;
  }
  //--------------------------------------------------
  {
   // Build and assign mesh
   Mesh* mesh_pt =
    new SimpleRectangularQuadMesh<QPoissonElement<2,4> >(n_x,n_y,l_x,l_y);
   // Filename for output
   string file_root="poisson_2_4";
   // Compare output
   output_both_versions(file_root,mesh_pt,nplot);
   delete mesh_pt;
  }
 //--------------------------------------------------
  {
   // Build and assign mesh
   Mesh* mesh_pt =
    new SimpleRefineableRectangularQuadMesh<RefineableQPoissonElement<2,2> >
    (n_x,n_y,l_x,l_y);
   // Filename for output
   string file_root="adapt_poisson_2_2";
   // Compare output
   output_both_versions(file_root,mesh_pt,nplot);
   delete mesh_pt;
  }
  //--------------------------------------------------
  {
   // Build and assign mesh
   Mesh* mesh_pt =
    new SimpleRefineableRectangularQuadMesh<RefineableQPoissonElement<2,3> >
    (n_x,n_y,l_x,l_y);
   // Filename for output
   string file_root="adapt_poisson_2_3";
   // Compare output
   output_both_versions(file_root,mesh_pt,nplot);
   delete mesh_pt;
  }
  //--------------------------------------------------
  {
   // Build and assign mesh
   Mesh* mesh_pt =
    new SimpleRefineableRectangularQuadMesh<RefineableQPoissonElement<2,4> >
    (n_x,n_y,l_x,l_y);
   // Filename for output
   string file_root="adapt_poisson_2_4";
   // Compare output
   output_both_versions(file_root,mesh_pt,nplot);
   delete mesh_pt;
  }
  //-------------------------------------------------------------
  {
   // Build and assign mesh
   Mesh* mesh_pt=new QuarterTubeMesh<QUnsteadyHeatElement<3,2> >(
    Wall_pt,xi_lo,frac_mid,xi_hi,nlayer,time_stepper_pt);
   // Filename for output
   string file_root="unsteady_heat_3_2";
   // Compare output
   output_both_versions(file_root,mesh_pt,nplot);
   delete mesh_pt;
  }
  //-------------------------------------------------------------
  {
   // Build and assign mesh
   Mesh* mesh_pt=new QuarterTubeMesh<QUnsteadyHeatElement<3,3> >(
    Wall_pt,xi_lo,frac_mid,xi_hi,nlayer,time_stepper_pt);
   // Filename for output
   string file_root="unsteady_heat_3_3";
   // Compare output
   output_both_versions(file_root,mesh_pt,nplot);
   delete mesh_pt;
  }
  //-------------------------------------------------------------
  {
   // Build and assign mesh
   Mesh* mesh_pt=new QuarterTubeMesh<QUnsteadyHeatElement<3,4> >(
    Wall_pt,xi_lo,frac_mid,xi_hi,nlayer,time_stepper_pt);
   // Filename for output
   string file_root="unsteady_heat_3_4";
   // Compare output
   output_both_versions(file_root,mesh_pt,nplot);
   delete mesh_pt;
  }
  //--------------------------------------------------
  {
   // Build mesh and store pointer
   Mesh* mesh_pt=new OneDMesh<QUnsteadyHeatElement<1,2> >(nelem,1.0);
   // Filename for output
   string file_root="unsteady_heat_1_2";
   // Compare output
   output_both_versions(file_root,mesh_pt,nplot);
   delete mesh_pt;
  }
  //--------------------------------------------------
  {
   // Build mesh and store pointer
   Mesh* mesh_pt=new OneDMesh<QUnsteadyHeatElement<1,3> >(nelem,1.0);
   // Filename for output
   string file_root="unsteady_heat_1_3";
   // Compare output
   output_both_versions(file_root,mesh_pt,nplot);
   delete mesh_pt;
  }
  //--------------------------------------------------
  {
   // Build mesh and store pointer
   Mesh* mesh_pt=new OneDMesh<QUnsteadyHeatElement<1,4> >(nelem,1.0);
   // Filename for output
   string file_root="unsteady_heat_1_4";
   // Compare output
   output_both_versions(file_root,mesh_pt,nplot);
   delete mesh_pt;
  }
  //--------------------------------------------------
  {
   // Build and assign mesh
   Mesh* mesh_pt =
    new SimpleRectangularQuadMesh<QUnsteadyHeatElement<2,2> >(n_x,n_y,l_x,l_y);
   // Filename for output
   string file_root="unsteady_heat_2_2";
   // Compare output
   output_both_versions(file_root,mesh_pt,nplot);
   delete mesh_pt;
  }
  //--------------------------------------------------
  {
   // Build and assign mesh
   Mesh* mesh_pt =
    new SimpleRectangularQuadMesh<QUnsteadyHeatElement<2,3> >(n_x,n_y,l_x,l_y);
   // Filename for output
   string file_root="unsteady_heat_2_3";
   // Compare output
   output_both_versions(file_root,mesh_pt,nplot);
   delete mesh_pt;
  }
  //--------------------------------------------------
  {
   // Build and assign mesh
   Mesh* mesh_pt =
    new SimpleRectangularQuadMesh<QUnsteadyHeatElement<2,4> >(n_x,n_y,l_x,l_y);
   // Filename for output
   string file_root="unsteady_heat_2_4";
   // Compare output
   output_both_versions(file_root,mesh_pt,nplot);
   delete mesh_pt;
  }
  //--------------------------------------------------
  {
   // Build and assign mesh
   Mesh* mesh_pt =
    new SimpleRefineableRectangularQuadMesh
    <RefineableQUnsteadyHeatElement<2,2> >(n_x,n_y,l_x,l_y);
   // Filename for output
   string file_root="adapt_unsteady_heat_2_2";
   // Compare output
   output_both_versions(file_root,mesh_pt,nplot);
   delete mesh_pt;
  }
  //--------------------------------------------------
  {
   // Build and assign mesh
   Mesh* mesh_pt =
    new SimpleRefineableRectangularQuadMesh
    <RefineableQUnsteadyHeatElement<2,3> >(n_x,n_y,l_x,l_y);
   // Filename for output
   string file_root="adapt_unsteady_heat_2_3";
   // Compare output
   output_both_versions(file_root,mesh_pt,nplot);
   delete mesh_pt;
  }
  //--------------------------------------------------
  {
   // Build and assign mesh
   Mesh* mesh_pt =
    new SimpleRefineableRectangularQuadMesh
    <RefineableQUnsteadyHeatElement<2,4> >(n_x,n_y,l_x,l_y);
   // Filename for output
   string file_root="adapt_unsteady_heat_2_4";
   // Compare output
   output_both_versions(file_root,mesh_pt,nplot);
   delete mesh_pt;
  }
 }
output_both_versions()
void output_both_versions (const string & file_root, Mesh * mesh_pt, const unsigned & npts)
Global output function to compare C++ and C-style output routines.
/////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////
 {
  cout << std::endl << "=============================================="
       << std::endl << std::endl;
  cout << file_root << std::endl << std::endl;
  DocInfo doc_info;
  char filename[100];
  ofstream some_file;
  double total_time_old, total_time_new;
  // C style output
  //-----------------
  {
   cout << "C style" << std::endl;
   doc_info.set_directory("RESLT_C_style");
   // Output solution
   sprintf(filename,"%s/%s.dat",doc_info.directory().c_str(),
           file_root.c_str());
   FILE* file_pt = fopen(filename,"w");
   clock_t t_start = clock();
   mesh_pt->output(file_pt,npts);
   clock_t t_end = clock();
   total_time_new=double(t_end-t_start)/CLOCKS_PER_SEC;
   cout << "CPU time [sec]: "
        << total_time_new << std::endl << std::endl;
   fclose(file_pt);
  }
  // C++ style output
  //-----------------
  {
   cout << "C++ style" << std::endl;
   doc_info.set_directory("RESLT_Cpp_style");
   // Output solution
   sprintf(filename,"%s/%s.dat",doc_info.directory().c_str(),
           file_root.c_str());
   some_file.open(filename);
   clock_t t_start = clock();
   mesh_pt->output(some_file,npts);
   clock_t t_end = clock();
   total_time_old=double(t_end-t_start)/CLOCKS_PER_SEC;
   cout << "CPU time [sec]: "
        << total_time_old << std::endl << std::endl;
   some_file.close();
  }
  cout << "                    RATIO: " << total_time_old/total_time_new
       << std::endl;
 }
References oomph::DocInfo::directory(), MergeRestartFiles::filename, oomph::Mesh::output(), and oomph::DocInfo::set_directory().
Referenced by ElasticRefineableQuarterCircleSectorMesh< ELEMENT >::ElasticRefineableQuarterCircleSectorMesh().