MercuryDPM: Eigen::internal::pchebevl< Packet, N > Struct Template Reference
Eigen::internal::pchebevl< Packet, N > Struct Template Reference
#include <GenericPacketMathFunctions.h>
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet run (Packet x, const typename unpacket_traits< Packet >::type coef[])
Member Function Documentation
run()
template<typename Packet , int N> static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet Eigen::internal::pchebevl< Packet, N >::run (Packet x, const typename unpacket_traits< Packet >::type coef[]) inline static
{
     typedef typename unpacket_traits<Packet>::type Scalar;
     Packet b0 = pset1<Packet>(coef[0]);
     Packet b1 = pset1<Packet>(static_cast<Scalar>(0.f));
     Packet b2;
     for (int i = 1; i < N; i++) {
       b2 = b1;
       b1 = b0;
       b0 = psub(pmadd(x, b1, pset1<Packet>(coef[i])), b2);
     }
     return pmul(pset1<Packet>(static_cast<Scalar>(0.5f)), psub(b0, b2));
   }
References i, N, Eigen::internal::pmadd(), Eigen::internal::pmul(), Eigen::internal::psub(), and plotDoE::x.
Referenced by Eigen::internal::generic_i0e< T, float >::run(), Eigen::internal::generic_i0e< T, double >::run(), Eigen::internal::generic_k0e< T, float >::run(), Eigen::internal::generic_k0e< T, double >::run(), Eigen::internal::generic_k0< T, float >::run(), and Eigen::internal::generic_k0< T, double >::run().
The documentation for this struct was generated from the following file:
GenericPacketMathFunctions.h