MercuryDPM: oomph::Edge Class Reference
oomph::Edge Class Reference
Edge class.
#include <mesh.h>
Public Member Functions
Edge (Node *node1_pt, Node *node2_pt)
Constructor: Pass in the two vertex nodes.
Node * node1_pt () const
Access to the first vertex node.
Node * node2_pt () const
Access to the second vertex node.
bool operator== (const Edge &other) const
Comparison operator.
bool operator< (const Edge &other) const
Less-than operator.
bool is_on_boundary () const
bool is_boundary_edge () const
Private Attributes
Node * Node1_pt
First vertex node.
Node * Node2_pt
Second vertex node.
Detailed Description
Edge class.
//////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////////
Constructor & Destructor Documentation
Edge()
oomph::Edge::Edge (Node * node1_pt, Node * node2_pt) inline
Constructor: Pass in the two vertex nodes.
     {
       if (node1_pt == node2_pt)
       {
 #ifdef PARANOID
         std::ostringstream error_stream;
         error_stream << "Edge cannot have two identical vertex nodes\n";
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
 #endif
       }
       // Sort lexicographically based on pointer address of nodes
       if (node1_pt > node2_pt)
       {
         Node1_pt = node1_pt;
         Node2_pt = node2_pt;
       }
       else
       {
         Node1_pt = node2_pt;
         Node2_pt = node1_pt;
       }
     }
References node1_pt(), Node1_pt, node2_pt(), Node2_pt, OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Member Function Documentation
is_boundary_edge()
bool oomph::Edge::is_boundary_edge () const inline
Test whether the Edge is a boundary edge, i.e. does it connnect two boundary nodes?
     {
       return ((dynamic_cast<BoundaryNodeBase*>(Node1_pt) != 0) &&
               (dynamic_cast<BoundaryNodeBase*>(Node2_pt) != 0));
     }
References Node1_pt, and Node2_pt.
Referenced by oomph::BrickFromTetMesh< ELEMENT >::build_mesh().
is_on_boundary()
bool oomph::Edge::is_on_boundary () const inline
Test whether the Edge lies on a boundary. Relatively simple test, based on both vertices lying on (some) boundary.
     {
       return (Node1_pt->is_on_boundary() && Node2_pt->is_on_boundary());
     }
References oomph::Node::is_on_boundary(), Node1_pt, and Node2_pt.
node1_pt()
Node* oomph::Edge::node1_pt () const inline
Access to the first vertex node.
     {
       return Node1_pt;
     }
References Node1_pt.
Referenced by Edge(), operator<(), operator==(), and oomph::ThinLayerBrickOnTetMesh< ELEMENT >::ThinLayerBrickOnTetMesh().
node2_pt()
Node* oomph::Edge::node2_pt () const inline
Access to the second vertex node.
     {
       return Node2_pt;
     }
References Node2_pt.
Referenced by Edge(), operator<(), operator==(), and oomph::ThinLayerBrickOnTetMesh< ELEMENT >::ThinLayerBrickOnTetMesh().
operator<()
bool oomph::Edge::operator< (const Edge & other) const inline
Less-than operator.
     {
       if (Node1_pt < other.node1_pt())
       {
         return true;
       }
       else if (Node1_pt == other.node1_pt())
       {
         if (Node2_pt < other.node2_pt())
         {
           return true;
         }
         else
         {
           return false;
         }
       }
       else
       {
         return false;
       }
     }
References node1_pt(), Node1_pt, node2_pt(), and Node2_pt.
operator==()
bool oomph::Edge::operator== (const Edge & other) const inline
Comparison operator.
     {
       if ((Node1_pt == other.node1_pt()) && (Node2_pt == other.node2_pt()))
       {
         return true;
       }
       else
       {
         return false;
       }
     }
References node1_pt(), Node1_pt, node2_pt(), and Node2_pt.
Member Data Documentation
Node1_pt
Node* oomph::Edge::Node1_pt private
First vertex node.
Referenced by Edge(), is_boundary_edge(), is_on_boundary(), node1_pt(), operator<(), and operator==().
Node2_pt
Node* oomph::Edge::Node2_pt private
Second vertex node.
Referenced by Edge(), is_boundary_edge(), is_on_boundary(), node2_pt(), operator<(), and operator==().
The documentation for this class was generated from the following file:
mesh.h