MercuryDPM: Eigen::IndexList< FirstType, OtherTypes > Struct Template Reference
Eigen::IndexList< FirstType, OtherTypes > Struct Template Reference
#include <TensorIndexList.h>
Public Member Functions
EIGEN_STRONG_INLINE constexpr EIGEN_DEVICE_FUNC Index operator[] (const Index i) const
EIGEN_STRONG_INLINE constexpr EIGEN_DEVICE_FUNC Index get (const Index i) const
EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC void set (const Index i, const Index value)
EIGEN_STRONG_INLINE constexpr EIGEN_DEVICE_FUNC std::size_t size () const
constexpr EIGEN_DEVICE_FUNC IndexList (const internal::IndexTuple< FirstType, OtherTypes... > &other)
constexpr EIGEN_DEVICE_FUNC IndexList (FirstType &first, OtherTypes... other)
constexpr EIGEN_DEVICE_FUNC IndexList ()
constexpr EIGEN_DEVICE_FUNC bool value_known_statically (const Index i) const
constexpr EIGEN_DEVICE_FUNC bool all_values_known_statically () const
constexpr EIGEN_DEVICE_FUNC bool values_statically_known_to_increase () const
Constructor & Destructor Documentation
IndexList() [1/3]
template<typename FirstType , typename... OtherTypes> constexpr EIGEN_DEVICE_FUNC Eigen::IndexList< FirstType, OtherTypes >::IndexList (const internal::IndexTuple< FirstType, OtherTypes... > & other) inline constexpr
       : internal::IndexTuple<FirstType, OtherTypes...>(other) {}
IndexList() [2/3]
template<typename FirstType , typename... OtherTypes> constexpr EIGEN_DEVICE_FUNC Eigen::IndexList< FirstType, OtherTypes >::IndexList (FirstType & first, OtherTypes... other) inline constexpr
       : internal::IndexTuple<FirstType, OtherTypes...>(first, other...) {}
IndexList() [3/3]
template<typename FirstType , typename... OtherTypes> constexpr EIGEN_DEVICE_FUNC Eigen::IndexList< FirstType, OtherTypes >::IndexList () inline constexpr
 : internal::IndexTuple<FirstType, OtherTypes...>() {}
Member Function Documentation
all_values_known_statically()
template<typename FirstType , typename... OtherTypes> constexpr EIGEN_DEVICE_FUNC bool Eigen::IndexList< FirstType, OtherTypes >::all_values_known_statically () const inline constexpr
{
     return internal::tuple_coeff<internal::array_size<internal::IndexTuple<FirstType, OtherTypes...>>::value - 1,
                                  Index>::values_up_to_known_statically(*this);
   }
References Eigen::value.
get()
template<typename FirstType , typename... OtherTypes> EIGEN_STRONG_INLINE constexpr EIGEN_DEVICE_FUNC Index Eigen::IndexList< FirstType, OtherTypes >::get (const Index i) const inline constexpr
{
     return internal::tuple_coeff<internal::array_size<internal::IndexTuple<FirstType, OtherTypes...>>::value - 1,
                                  Index>::get(i, *this);
   }
References i, and Eigen::value.
Referenced by Eigen::IndexList< FirstType, OtherTypes >::operator[]().
operator[]()
template<typename FirstType , typename... OtherTypes> EIGEN_STRONG_INLINE constexpr EIGEN_DEVICE_FUNC Index Eigen::IndexList< FirstType, OtherTypes >::operator[] (const Index i) const inline constexpr
{
     return internal::tuple_coeff<internal::array_size<internal::IndexTuple<FirstType, OtherTypes...>>::value - 1,
                                  Index>::get(i, *this);
   }
References Eigen::IndexList< FirstType, OtherTypes >::get(), i, and Eigen::value.
set()
template<typename FirstType , typename... OtherTypes> EIGEN_STRONG_INLINE EIGEN_DEVICE_FUNC void Eigen::IndexList< FirstType, OtherTypes >::set (const Index i, const Index value) inline
{
     return internal::tuple_coeff<internal::array_size<internal::IndexTuple<FirstType, OtherTypes...>>::value - 1,
                                  Index>::set(i, *this, value);
   }
References i, and Eigen::value.
Referenced by BenchmarkSuite< Device, T >::broadcasting(), and test_dim_check().
size()
template<typename FirstType , typename... OtherTypes> EIGEN_STRONG_INLINE constexpr EIGEN_DEVICE_FUNC std::size_t Eigen::IndexList< FirstType, OtherTypes >::size () const inline constexpr
 { return 1 + sizeof...(OtherTypes); };
value_known_statically()
template<typename FirstType , typename... OtherTypes> constexpr EIGEN_DEVICE_FUNC bool Eigen::IndexList< FirstType, OtherTypes >::value_known_statically (const Index i) const inline constexpr
{
     return internal::tuple_coeff<internal::array_size<internal::IndexTuple<FirstType, OtherTypes...>>::value - 1,
                                  Index>::value_known_statically(i, *this);
   }
References i, and Eigen::value.
values_statically_known_to_increase()
template<typename FirstType , typename... OtherTypes> constexpr EIGEN_DEVICE_FUNC bool Eigen::IndexList< FirstType, OtherTypes >::values_statically_known_to_increase () const inline constexpr
{
     return internal::tuple_coeff<internal::array_size<internal::IndexTuple<FirstType, OtherTypes...>>::value - 1,
                                  Index>::values_up_to_statically_known_to_increase(*this);
   }
References Eigen::value.
The documentation for this struct was generated from the following file:
TensorIndexList.h