MercuryDPM: oomph::ProblemBasedShiftInvertOperator Class Reference
oomph::ProblemBasedShiftInvertOperator Class Reference
Class for the shift invert operation.
#include <trilinos_eigen_solver.h>
Public Member Functions
ProblemBasedShiftInvertOperator (Problem *const &problem_pt, LinearSolver *const &linear_solver_pt, const double &sigma=0.0)
void apply (const DoubleMultiVector &x, DoubleMultiVector &y) const
The apply interface.
Public Member Functions inherited from oomph::DoubleMultiVectorOperator
DoubleMultiVectorOperator ()
Empty constructor.
virtual ~DoubleMultiVectorOperator ()
virtual destructor
Private Attributes
Problem * Problem_pt
LinearSolver * Linear_solver_pt
double Sigma
CRDoubleMatrix * M_pt
CRDoubleMatrix * AsigmaM_pt
Detailed Description
Class for the shift invert operation.
Constructor & Destructor Documentation
ProblemBasedShiftInvertOperator()
oomph::ProblemBasedShiftInvertOperator::ProblemBasedShiftInvertOperator (Problem *const & problem_pt, LinearSolver *const & linear_solver_pt, const double & sigma = 0.0) inline
       : Problem_pt(problem_pt), Linear_solver_pt(linear_solver_pt), Sigma(sigma)
     {
       // Before we get into the Arnoldi loop solve the shifted matrix problem
       // Allocated Row compressed matrices for the mass matrix and shifted main
       // matrix
       M_pt = new CRDoubleMatrix(problem_pt->dof_distribution_pt());
       AsigmaM_pt = new CRDoubleMatrix(problem_pt->dof_distribution_pt());
       // Assemble the matrices
       problem_pt->get_eigenproblem_matrices(*M_pt, *AsigmaM_pt, Sigma);
       // Do not report the time taken
       Linear_solver_pt->disable_doc_time();
     }
References AsigmaM_pt, oomph::LinearSolver::disable_doc_time(), oomph::Problem::dof_distribution_pt(), oomph::Problem::get_eigenproblem_matrices(), Linear_solver_pt, M_pt, and Sigma.
Member Function Documentation
apply()
void oomph::ProblemBasedShiftInvertOperator::apply (const DoubleMultiVector & x, DoubleMultiVector & y) const inline virtual
The apply interface.
Implements oomph::DoubleMultiVectorOperator.
     {
       const unsigned n_vec = x.nvector();
       const unsigned n_row_local = x.nrow_local();
       if (n_vec > 1)
       {
         Linear_solver_pt->enable_resolve();
       }
       // Solve the first vector
       DoubleVector X(x.distribution_pt());
       // Premultiply by mass matrix
       M_pt->multiply(x.doublevector(0), X);
       // For some reason I need to create a new vector and copy here
       // This is odd and not expected, examine carefully
       DoubleVector Y(x.distribution_pt());
       Linear_solver_pt->solve(AsigmaM_pt, X, Y);
       // Need to synchronise
       //#ifdef OOMPH_HAS_MPI
       //   Problem_pt->synchronise_all_dofs();
       //#endif
       for (unsigned i = 0; i < n_row_local; i++)
       {
         y(0, i) = Y[i];
       }
       // Now loop over the others and resolve
       for (unsigned v = 1; v < n_vec; ++v)
       {
         M_pt->multiply(x.doublevector(v), X);
         Linear_solver_pt->resolve(X, Y);
         //#ifdef OOMPH_HAS_MPI
         //     Problem_pt->synchronise_all_dofs();
         //#endif
         for (unsigned i = 0; i < n_row_local; i++)
         {
           y(v, i) = Y[i];
         }
       }
     }
References AsigmaM_pt, oomph::LinearSolver::enable_resolve(), i, Linear_solver_pt, M_pt, oomph::CRDoubleMatrix::multiply(), oomph::LinearSolver::resolve(), oomph::LinearSolver::solve(), v, plotDoE::x, X, y, and Y.
Member Data Documentation
AsigmaM_pt
CRDoubleMatrix * oomph::ProblemBasedShiftInvertOperator::AsigmaM_pt private
Referenced by apply(), and ProblemBasedShiftInvertOperator().
Linear_solver_pt
LinearSolver* oomph::ProblemBasedShiftInvertOperator::Linear_solver_pt private
Referenced by apply(), and ProblemBasedShiftInvertOperator().
M_pt
CRDoubleMatrix* oomph::ProblemBasedShiftInvertOperator::M_pt private
Referenced by apply(), and ProblemBasedShiftInvertOperator().
Problem_pt
Problem* oomph::ProblemBasedShiftInvertOperator::Problem_pt private
Sigma
double oomph::ProblemBasedShiftInvertOperator::Sigma private
Referenced by ProblemBasedShiftInvertOperator().
The documentation for this class was generated from the following file:
trilinos_eigen_solver.h