MercuryDPM: oomph::GeompackQuadMesh< ELEMENT > Class Template Reference
oomph::GeompackQuadMesh< ELEMENT > Class Template Reference
#include <geompack_mesh.template.h>
Public Member Functions
GeompackQuadMesh (const std::string &mesh_file_name, const std::string &curve_file_name, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor with the input files.
~GeompackQuadMesh ()
Empty destructor.
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void setup_boundary_element_info ()
virtual void setup_boundary_element_info (std::ostream &outfile)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void node_update (const bool &update_all_solid_nodes=false)
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Private Member Functions
void build_from_scaffold (TimeStepper *time_stepper_pt)
Build mesh from scaffold.
Private Attributes
GeompackQuadScaffoldMesh * Tmp_mesh_pt
Temporary scaffold mesh.
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Detailed Description
template<class ELEMENT>
class oomph::GeompackQuadMesh< ELEMENT >
Quadrilateral mesh generator; Uses input from Geompack++. See: http://members.shaw.ca/bjoe/ Currently only for four-noded quads – extension to higher-order quads should be trivial (see the corresponding classes for triangular meshes).
Constructor & Destructor Documentation
GeompackQuadMesh()
template<class ELEMENT > oomph::GeompackQuadMesh< ELEMENT >::GeompackQuadMesh (const std::string & mesh_file_name, const std::string & curve_file_name, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) inline
Constructor with the input files.
     {
       // Mesh can only be built with four-noded 2D Qelements.
       MeshChecker::assert_geometric_element<QElementGeometricBase, ELEMENT>(2,
                                                                             2);
       // Build scaffold
       Tmp_mesh_pt =
         new GeompackQuadScaffoldMesh(mesh_file_name, curve_file_name);
       // Convert mesh from scaffold to actual mesh
       build_from_scaffold(time_stepper_pt);
       // Kill the scaffold
       delete Tmp_mesh_pt;
       Tmp_mesh_pt = 0;
     }
References oomph::GeompackQuadMesh< ELEMENT >::build_from_scaffold(), and oomph::GeompackQuadMesh< ELEMENT >::Tmp_mesh_pt.
~GeompackQuadMesh()
template<class ELEMENT > oomph::GeompackQuadMesh< ELEMENT >::~GeompackQuadMesh () inline
Empty destructor.
 {}
Member Function Documentation
build_from_scaffold()
template<class ELEMENT > void oomph::GeompackQuadMesh< ELEMENT >::build_from_scaffold (TimeStepper * time_stepper_pt) private
Build mesh from scaffold.
Quadrilateral mesh generator; Uses input from Geompack++. See: http://members.shaw.ca/bjoe/ Currently only for four-noded quads – extension to higher-order quads should be trivial (see the corresponding classes for triangular meshes).
   {
     // Mesh can only be built with four-noded 2D Qelements.
     MeshChecker::assert_geometric_element<QElementGeometricBase, ELEMENT>(2, 2);
     // Create space for elements
     unsigned nelem = Tmp_mesh_pt->nelement();
     Element_pt.resize(nelem);
     // Create space for nodes
     unsigned nnod = Tmp_mesh_pt->nnode();
     Node_pt.resize(nnod);
     // Set number of boundaries
     unsigned nbound = Tmp_mesh_pt->nboundary();
     set_nboundary(nbound);
     // Loop over elements in scaffold mesh, visit their nodes
     for (unsigned e = 0; e < nelem; e++)
     {
       Element_pt[e] = new ELEMENT;
     }
     // At the moment we can only do four-noded quads
     if (finite_element_pt(0)->nnode() != 4)
     {
       std::string error_message =
         "GeompackQuadMesh can currently only deal with\n";
       error_message += "four noded quads! \n";
       error_message += "Generalisation to higher-order elements should be \n";
       error_message += "straightforward but hasn't been done yet.\n";
       error_message += "Do you want to volunteer? \n";
       throw OomphLibError(
         error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
     // In the first instance build all nodes from within all the elements
     unsigned nnod_el = Tmp_mesh_pt->finite_element_pt(0)->nnode();
     // Loop over elements in scaffold mesh, visit their nodes
     for (unsigned e = 0; e < nelem; e++)
     {
       // Loop over all nodes in element
       for (unsigned j = 0; j < nnod_el; j++)
       {
         // Create new node, using the NEW element's construct_node
         // member function
         finite_element_pt(e)->construct_node(j, time_stepper_pt);
       }
     }
     std::map<Node*, unsigned> global_number;
     unsigned global_count = 0;
     // Loop over elements in scaffold mesh, visit their nodes
     for (unsigned e = 0; e < nelem; e++)
     {
       // Loop over all nodes in element
       for (unsigned j = 0; j < nnod_el; j++)
       {
         // Pointer to node in the scaffold mesh
         Node* scaffold_node_pt = Tmp_mesh_pt->finite_element_pt(e)->node_pt(j);
         // Get the (pseudo-)global node number in scaffold mesh
         // (It's zero [=default] if not visited this one yet)
         unsigned j_global = global_number[scaffold_node_pt];
         // Haven't done this one yet
         if (j_global == 0)
         {
           // Give it a number (not necessarily the global node
           // number in the scaffold mesh -- we just need something
           // to keep track...)
           global_count++;
           global_number[scaffold_node_pt] = global_count;
           // Copy new node, created using the NEW element's construct_node
           // function into global storage, using the same global
           // node number that we've just associated with the
           // corresponding node in the scaffold mesh
           Node_pt[global_count - 1] = finite_element_pt(e)->node_pt(j);
           // Assign coordinates
           Node_pt[global_count - 1]->x(0) = scaffold_node_pt->x(0);
           Node_pt[global_count - 1]->x(1) = scaffold_node_pt->x(1);
           // Get pointer to set of mesh boundaries that this
           // scaffold node occupies; NULL if the node is not on any boundary
           std::set<unsigned>* boundaries_pt;
           scaffold_node_pt->get_boundaries_pt(boundaries_pt);
           // Loop over the mesh boundaries that the node in the scaffold mesh
           // occupies and assign new node to the same ones.
           if (boundaries_pt != 0)
           {
             // Convert it to a boundary node
             this->convert_to_boundary_node(Node_pt[global_count - 1]);
             // Add the node to the boundaries
             for (std::set<unsigned>::iterator it = boundaries_pt->begin();
                  it != boundaries_pt->end();
                  ++it)
             {
               add_boundary_node(*it, Node_pt[global_count - 1]);
             }
           }
         }
         // This one has already been done: Kill it
         else
         {
           // Kill it
           delete finite_element_pt(e)->node_pt(j);
           // Overwrite the element's pointer to local node by
           // pointer to the already existing node -- identified by
           // the number kept in the map
           finite_element_pt(e)->node_pt(j) = Node_pt[j_global - 1];
         }
       }
     }
   }
References e(), oomph::Node::get_boundaries_pt(), j, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::Global_string_for_annotation::string(), and oomph::Node::x().
Referenced by oomph::GeompackQuadMesh< ELEMENT >::GeompackQuadMesh().
Member Data Documentation
Tmp_mesh_pt
template<class ELEMENT > GeompackQuadScaffoldMesh* oomph::GeompackQuadMesh< ELEMENT >::Tmp_mesh_pt private
Temporary scaffold mesh.
Referenced by oomph::GeompackQuadMesh< ELEMENT >::GeompackQuadMesh().
The documentation for this class was generated from the following files:
geompack_mesh.template.h
geompack_mesh.template.cc