MercuryDPM: umfpack_support.cpp File Reference
umfpack_support.cpp File Reference
#include "sparse_solver.h"
#include <Eigen/UmfPackSupport>
Macros
#define EIGEN_NO_DEBUG_SMALL_PRODUCT_BLOCKS
Functions
template<typename T1 , typename T2 >
void test_umfpack_support_T ()
EIGEN_DECLARE_TEST (umfpack_support)
Macro Definition Documentation
EIGEN_NO_DEBUG_SMALL_PRODUCT_BLOCKS
#define EIGEN_NO_DEBUG_SMALL_PRODUCT_BLOCKS
Function Documentation
EIGEN_DECLARE_TEST()
EIGEN_DECLARE_TEST (umfpack_support)
{
   CALL_SUBTEST_1((test_umfpack_support_T<double, int>()));
   CALL_SUBTEST_2((test_umfpack_support_T<std::complex<double>, int>()));
   CALL_SUBTEST_3((test_umfpack_support_T<double, long>()));
   CALL_SUBTEST_4((test_umfpack_support_T<std::complex<double>, long>()));
 }
References CALL_SUBTEST_1, CALL_SUBTEST_2, CALL_SUBTEST_3, CALL_SUBTEST_4, and test_umfpack_support_T().
test_umfpack_support_T()
template<typename T1 , typename T2 > void test_umfpack_support_T ()
{
   UmfPackLU<SparseMatrix<T1, ColMajor, T2> > umfpack_colmajor;
   UmfPackLU<SparseMatrix<T1, RowMajor, T2> > umfpack_rowmajor;
   check_sparse_square_solving(umfpack_colmajor);
   check_sparse_square_solving(umfpack_rowmajor);
   check_sparse_square_determinant(umfpack_colmajor);
   check_sparse_square_determinant(umfpack_rowmajor);
 }
References check_sparse_square_determinant(), and check_sparse_square_solving().
Referenced by EIGEN_DECLARE_TEST().