MercuryDPM: FrictionInteraction Class Reference
FrictionInteraction Class Reference
This class allows one to take all three types of frictional interactions into account. The sliding, rolling and torsional frictional interaction. See.
#include <FrictionInteraction.h>
Public Types
typedef FrictionSpecies SpeciesType
An alias for FrictionSpecies.
Public Types inherited from SlidingFrictionInteraction
typedef SlidingFrictionSpecies SpeciesType
An alias name for SlidingFrictionSpecies data type.
Public Member Functions
FrictionInteraction (BaseInteractable *P, BaseInteractable *I, unsigned timeStamp)
Constructor.
FrictionInteraction ()
FrictionInteraction (const FrictionInteraction &p)
Copy constructor.
~FrictionInteraction () override
Destructor.
void computeFrictionForce ()
Computes the forces arising due to all three types of friction, i.e., sliding, rolling and torsional.
void read (std::istream &is) override
Interaction read function, which accepts an std::istream as input.
void write (std::ostream &os) const override
Interaction print function, which accepts an std::ostream as input.
void integrate (Mdouble timeStep) override
Computes the amount of compression in all the springs, i.e., increments the rollingSpring_, slidingSpring_ (see SlidingFrictionInteraction.cc) and torsionSpring_.
Mdouble getElasticEnergy () const override
Returns the global amount of energy stored in all the springs (rolling, sliding and torsional).
std::string getBaseName () const
Returns interaction name/type.
const FrictionSpecies * getSpecies () const
Returns a const pointer of type FrictionSpecies*.
void reverseHistory () override
A useful feature if one wants to return to the initial state of the springs. However, reverse history decrements the current state to the state corresponding to previous time step. Decrements the state or value of rollingSpring_, torsionSpring_ and slidingSpring_.
void rotateHistory (Matrix3D &rotationMatrix) override
When periodic particles are used, some interactions need certain history properties rotated (e.g. tangential springs). This is the function for that.
Vec3D getRollingSpring () const
Vec3D getTorsionSpring () const
void setRollingSpring (Vec3D rollingSpring)
void setTorsionSpring (Vec3D torsionSpring)
Public Member Functions inherited from SlidingFrictionInteraction
SlidingFrictionInteraction (BaseInteractable *P, BaseInteractable *I, unsigned timeStamp)
Constructor.
SlidingFrictionInteraction ()
SlidingFrictionInteraction (const SlidingFrictionInteraction &p)
Copy constructor.
~SlidingFrictionInteraction () override
Destructor.
void computeFrictionForce ()
Computes the tangential force generated due to compression in the sliding spring. Does take into account if the interaction is between particle-particle or particle-wall.
void read (std::istream &is) override
Interaction read function, which accepts an std::istream as input.
void write (std::ostream &os) const override
Interaction write function, which accepts an std::ostream as input.
void integrate (Mdouble timeStep) override
Increments the amount of compression in sliding spring.
Mdouble getElasticEnergy () const override
Returns the amount of elastic energy stored in sliding spring.
Mdouble getTangentialOverlap () const override
Returns the amount of tangential overlap which is needed by BaseInteraction::writeToFstat().
std::string getBaseName () const
Returns the type/name of interaction (sliding friction interaction)
void setSlidingSpring (Vec3D slidingSpring)
Vec3D getSlidingSpring () const
const Vec3D getTangentialForce () const override
Returns the sliding friction force vector.
void addTangentialForce (Vec3D force)
adds an extra tangential force, mainly for the tangential lubrication force from LiquidMigrationLS model.
const SlidingFrictionSpecies * getSpecies () const
Returns a const pointer of type SlidingFrictionSpecies*.
void reverseHistory () override
A useful feature if one wants to return to the initial state of the spring. However, reverse history decrements the current state to the state corresponding to previous time step. Decrements the value of slidingSpring_.
void rotateHistory (Matrix3D &rotationMatrix) override
When periodic particles are used, some interactions need certain history properties rotated (e.g. tangential springs). This is the function for that.
void moveSlidingSpring (Vec3D displacement)
void computeSlidingSpring (const Vec3D &tangentialRelativeVelocity)
void setIsSuperQuadricInteraction (bool isSuperQuadricInteraction)
Public Member Functions inherited from BaseInteraction
BaseInteraction (BaseInteractable *P, BaseInteractable *I, unsigned timeStamp)
A constructor takes the BaseInteractable objects which are interacting (come into contact) and time the interaction starts.
BaseInteraction ()
BaseInteraction (const BaseInteraction &p)
Copy constructor.
~BaseInteraction () override
The destructor. It removes this interactions from the objects that were interacting, and writes the time to a file when needed.
virtual void actionsOnErase ()
If an interaction needs to do something before it gets erased, add it here. E.g. Liquid bridges rupture at the end of their lifetime, and the liquid bridge volume has to be redistributed. The reason this action is not done in the destructor is that this action should not be taken when erasing ghost interactions.
virtual void computeForce ()
Virtual function that contains the force law between the two objects interacting.
void writeToFStat (std::ostream &os, Mdouble time) const
Writes forces data to the FStat file.
std::string getName () const override
Virtual function which allows interactions to be named.
void setDistance (Mdouble distance)
Sets the interaction distance between the two interacting objects.
void setNormal (Vec3D normal)
Sets the normal vector between the two interacting objects.
void setOverlap (Mdouble overlap)
Set the overlap between the two interacting object.
void setContactPoint (Vec3D contactPoint)
Set the location of the contact point between the two interacting objects.
void setTimeStamp (unsigned timeStamp)
Updates the time step of the interacting. Note, time steps used to find completed interactions.
void setSpecies (const BaseSpecies *species)
Set the Species of the interaction; note this can either be a Species or MixedSpecies.
void setP (BaseInteractable *P)
Sets the first object involved in the interaction (normally a particle).
void setI (BaseInteractable *I)
Sets the second object involved in the interaction (often particle or wall).
void importP (BaseInteractable *P)
Sets the first object involved in the interaction (normally a particle).
void importI (BaseInteractable *I)
Sets the second object involved in the interaction (often particle or wall).
Vec3D getIP () const
Vec3D getIC () const
Vec3D getCP () const
void setLagrangeMultiplier (Mdouble multiplier)
Mdouble getLagrangeMultiplier ()
void setHandler (InteractionHandler *handler)
Sets the pointer to the interaction hander which is storing this interaction.
InteractionHandler * getHandler () const
Gets a point to the interaction handlers to which this interaction belongs.
const Vec3D & getForce () const
Gets the current force (vector) between the two interacting objects.
const Vec3D & getTorque () const
Gets the current torque (vector) between the two interacting objects.
const Vec3D & getNormal () const
Gets the normal vector between the two interacting objects.
const Vec3D & getContactPoint () const
Gets constant reference to contact point (vector).
Mdouble getOverlap () const
Returns a Mdouble with the current overlap between the two interacting objects.
Mdouble getOverlapVolume () const
Returns the overlap volume between two interacting objects.
Mdouble getContactRadius () const
Returns a Mdouble with the current contact between the two interacting objects.
void removeFromHandler ()
Removes this interaction from its interaction hander.
void copySwitchPointer (const BaseInteractable *original, BaseInteractable *ghost) const
This copies the interactions of the original particle and replaces the original with the ghost copy.
void gatherContactStatistics ()
BaseInteractable * getP ()
Returns a pointer to first object involved in the interaction (normally a particle).
BaseInteractable * getI ()
Returns a pointer to the second object involved in the interaction (often a wall or a particle).
const BaseInteractable * getP () const
Returns a constant pointer to the first object involved in the interaction.
const BaseInteractable * getI () const
Returns a constant pointer to the second object involved in the interaction.
Mdouble getTimeStamp () const
Returns an Mdouble which is the time stamp of the interaction.
Mdouble getDistance () const
Returns an Mdouble which is the norm (length) of distance vector.
const Vec3D & getRelativeVelocity () const
Returns a constant reference to a vector of relative velocity.
Mdouble getNormalRelativeVelocity () const
Returns a double which is the norm (length) of the relative velocity vector.
Mdouble getAbsoluteNormalForce () const
Returns the absolute value of the norm (length) of the Normal force vector.
virtual BaseInteraction * copy () const =0
Makes a copy of the interaction and returns a pointer to the copy.
void setFStatData (std::fstream &fstat, BaseParticle *P, BaseWall *I)
void setFStatData (std::fstream &fstat, BaseParticle *P, BaseParticle *I)
unsigned int getMultiContactIdentifier () const
void setMultiContactIdentifier (unsigned int multiContactIdentifier_)
virtual void actionsAfterTimeStep ()
virtual unsigned getNumberOfFieldsVTK () const
virtual std::string getTypeVTK (unsigned i) const
virtual std::string getNameVTK (unsigned i) const
virtual std::vector< Mdouble > getFieldVTK (unsigned i) const
void addForce (Vec3D force)
add an force increment to the total force.
void addTorque (Vec3D torque)
add a torque increment to the total torque.
void setForce (Vec3D force)
set total force (this is used by the normal force, tangential forces are added use addForce)
void setTorque (Vec3D torque)
set the total force (this is used by the normal force, tangential torques are added use addTorque)
const BaseSpecies * getBaseSpecies () const
Return a constant point to BaseSpecies of the interaction.
virtual void createMPIType ()
virtual void * createMPIInteractionDataArray (unsigned int numberOfInteractions) const
virtual void deleteMPIInteractionDataArray (void *dataArray)
virtual void getMPIInteraction (void *historyDataArray, unsigned int index) const
copies the history interactions into the data array
virtual void getInteractionDetails (void *interactionDataArray, unsigned int index, unsigned int &identificationP, unsigned int &identificationI, bool &isWallInteraction, unsigned &timeStamp)
virtual void setMPIInteraction (void *interactionDataArray, unsigned int index, bool resetPointers)
void setBasicMPIInteractionValues (int P, int I, unsigned timeStamp, Vec3D force, Vec3D torque, bool isWallInteraction, bool resetPointers)
void setIdentificationP (unsigned int identification)
void setIdentificationI (int identification)
void setWallInteraction (bool flag)
unsigned int getIdentificationP ()
int getIdentificationI ()
bool isWallInteraction ()
virtual bool isBonded () const
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Private Attributes
Vec3D rollingSpring_
Stores the amount of rolling spring compression. Set in integrate(), used in computing frictional force due to rolling.
Vec3D rollingSpringVelocity_
Stores the rate at which the rolling spring compresses or relaxes. Set in computeFrictionForce(), used in computing the amount of compression in rolling spring. Used in integrate().
Vec3D torsionSpring_
Stores the amount of torsional spring compression. Set in integrate(), used in computing frictional force due to torsion.
Vec3D torsionSpringVelocity_
Stores the rate at which the torsional spring compresses or relaxes. Set in computeFrictionForce(), used in computing the amount of compression in torsion spring. Used in integrate().
Additional Inherited Members
Protected Member Functions inherited from BaseInteraction
Mdouble getEffectiveRadius () const
Returns a Mdouble to the effective radius of the interaction. (Not corrected for the overlap)
Mdouble getEffectiveMass () const
Returns a Mdouble to the effective radius of the interaction. (Not corrected for the overlap)
void setRelativeVelocity (Vec3D relativeVelocity)
set the relative velocity of the current of the interactions.
void setNormalRelativeVelocity (Mdouble normalRelativeVelocit)
set the normal component of the relative velocity.
void setAbsoluteNormalForce (Mdouble absoluteNormalForce)
the absolute values of the norm (length) of the normal force
virtual Mdouble getElasticEnergyAtEquilibrium (Mdouble adhesiveForce) const
void writeInteraction (std::ostream &os, bool created) const
Writes information about a interaction to the interaction file.
Protected Attributes inherited from SlidingFrictionInteraction
Vec3D slidingSpring_
Stores the amount of sliding spring (\(\delta\)) compression from the expression \(f_t=-k*\delta-\nu*relVel\). Set in the member function integrate(), used in computeFrictionForce().
Vec3D slidingSpringVelocity_
Stores the rate at which the sliding spring compressed or relaxed. Set in the member function computeFrictionForce() and used in integrate().
Vec3D tangentialForce_
Computes the tangential force such that \(|f_t|=\mu*|f_n|\). Set and computed in computeFrictionForce().
bool isSuperQuadricInteraction_
Detailed Description
This class allows one to take all three types of frictional interactions into account. The sliding, rolling and torsional frictional interaction. See.
Member Typedef Documentation
SpeciesType
typedef FrictionSpecies FrictionInteraction::SpeciesType
An alias for FrictionSpecies.
Constructor & Destructor Documentation
FrictionInteraction() [1/3]
FrictionInteraction::FrictionInteraction (BaseInteractable * P, BaseInteractable * I, unsigned timeStamp)
Constructor.
Parameters
[in] P
[in] I
[in] timeStamp
         : BaseInteraction(P, I, timeStamp), SlidingFrictionInteraction(P, I, timeStamp)
 {
     rollingSpring_.setZero();
     torsionSpring_.setZero();
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"FrictionInteraction::FrictionInteraction() finished"<<std::endl;
 #endif
 }
References rollingSpring_, Vec3D::setZero(), and torsionSpring_.
FrictionInteraction() [2/3]
FrictionInteraction::FrictionInteraction ()
         : BaseInteraction(), SlidingFrictionInteraction()
 {
     rollingSpring_.setZero();
     torsionSpring_.setZero();
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"FrictionInteraction::FrictionInteraction() finished"<<std::endl;
 #endif
 }
References rollingSpring_, Vec3D::setZero(), and torsionSpring_.
FrictionInteraction() [3/3]
FrictionInteraction::FrictionInteraction (const FrictionInteraction & p)
Copy constructor.
Parameters
[in] p
         : BaseInteraction(p), SlidingFrictionInteraction(p)
 {
     rollingSpring_ = p.rollingSpring_;
     torsionSpring_ = p.torsionSpring_;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"FrictionInteraction::FrictionInteraction(const FrictionInteraction& p) finished"<<std::endl;
 #endif
 }
References p, rollingSpring_, and torsionSpring_.
~FrictionInteraction()
FrictionInteraction::~FrictionInteraction () override
Destructor.
 {
 #ifdef DEBUG_DESTRUCTOR
     std::cout<<"FrictionInteraction::~FrictionInteraction() finished"<<std::endl;
 #endif
 }
Member Function Documentation
computeFrictionForce()
void FrictionInteraction::computeFrictionForce ()
Computes the forces arising due to all three types of friction, i.e., sliding, rolling and torsional.
Calls the slidingFrictionInteraction::computeFrictionForce() as well, see slidingFrictionInteraction.cc.
Todo:
TW: Why do we not use the corrected diameter here, as in the rolling case? And check if Stefan uses radius or diameter
 {
     SlidingFrictionInteraction::computeFrictionForce();
     const FrictionSpecies* species = getSpecies();
     //If tangential forces are present
     if (getAbsoluteNormalForce() == 0.0) return;
     if (species->getRollingFrictionCoefficient() != 0.0)
     {
         if (species->getRollingStiffness() != 0.0)
         {
             Mdouble effectiveDiameter = 2.0 * getEffectiveRadius();
             //From Luding2008, objective rolling velocity (eq 15) w/o 2.0!
             Vec3D rollingRelativeVelocity = -effectiveDiameter *
                                             Vec3D::cross(getNormal(),
                                                          getP()->getAngularVelocity() - getI()->getAngularVelocity());
             // Rotate the rolling Spring like the tangential spring using Luding, S. (2008) eq. (17)
             const Mdouble springLength = rollingSpring_.getLength();
             if (springLength > 1e-10)
             {
                 rollingSpring_ -= Vec3D::dot(rollingSpring_, getNormal()) * getNormal();
                 rollingSpring_ *= springLength / rollingSpring_.getLength();
                 logger.assert_debug(std::abs(rollingSpring_.getLength() - springLength) < 1e-10, "FrictionInteraction::computeFrictionForce: rolling-spring length not the same after rotation");
             }
             // integrate the spring
             rollingSpringVelocity_ = rollingRelativeVelocity;
             rollingSpring_ += rollingSpringVelocity_ * getHandler()->getDPMBase()->getTimeStep();
             //Calculate test force acting on P including viscous force
             Vec3D rollingForce = -species->getRollingStiffness() * rollingSpring_ -
                                  species->getRollingDissipation() * rollingRelativeVelocity;
             if (getBaseSpecies()->getNormalForce()->getConstantRestitution()) rollingForce *=2.0*getEffectiveMass();
             //tangential forces are modelled by a spring-damper of elasticity kt and viscosity dispt (sticking),
             //but the force is limited by Coulomb friction (rolling):
             Mdouble rollingForceSquared = rollingForce.getLengthSquared();
             if (rollingForceSquared <=
                 mathsFunc::square(species->getRollingFrictionCoefficientStatic() * getAbsoluteNormalForce()))
             {
                 //if sticking (|ft|<=mu*|fn|), apply the force
             }
             else
             {
                 //if rolling, resize the tangential force such that |ft|=mu*|fn|
                 rollingForce *= species->getRollingFrictionCoefficient() * getAbsoluteNormalForce() /
                                 std::sqrt(rollingForceSquared);
                 //resize the tangential spring accordingly such ft=-k*delta-nu*relVel
                 rollingSpring_ = -(rollingForce + species->getRollingDissipation() * rollingRelativeVelocity) /
                                  species->getRollingStiffness();
             }
             //Add (virtual) rolling force to torque
             addTorque(effectiveDiameter * Vec3D::cross(getNormal(), rollingForce));
         }
         else //if no spring stiffness is set
         {
             logger(ERROR, "FrictionInteraction::computeFrictionForce(): Rolling friction is zero");
         }
     } //end if rolling force
     if (species->getTorsionFrictionCoefficient() != 0.0)
     {
         if (species->getTorsionStiffness() != 0.0)
         {
             Mdouble effectiveDiameter = 2.0 * getEffectiveRadius();
             //From Luding2008, spin velocity (eq 16) w/o 2.0!
             Vec3D torsionRelativeVelocity = effectiveDiameter * Vec3D::dot(getNormal(), getP()->getAngularVelocity() -
                                                                                         getI()->getAngularVelocity()) *
                                             getNormal();
             //Integrate the spring
             torsionSpringVelocity_ = torsionRelativeVelocity;
             //integrate(getHandler()->timeStep_);
             torsionSpring_ =
                     Vec3D::dot(torsionSpring_ + torsionSpringVelocity_ * getHandler()->getDPMBase()->getTimeStep(),
                                getNormal()) * getNormal();
             //Calculate test force acting on P including viscous force
             Vec3D torsionForce = -species->getTorsionStiffness() * torsionSpring_ -
                                  species->getTorsionDissipation() * torsionRelativeVelocity;
             if (getBaseSpecies()->getNormalForce()->getConstantRestitution()) torsionForce *=2.0*getEffectiveMass();
             //tangential forces are modelled by a spring-damper of elasticity kt and viscosity dispt (sticking),
             //but the force is limited by Coulomb friction (torsion):
             Mdouble torsionForceSquared = torsionForce.getLengthSquared();
             if (torsionForceSquared <=
                 mathsFunc::square(species->getTorsionFrictionCoefficientStatic() * getAbsoluteNormalForce()))
             {
                 //if sticking (|ft|<=mu*|fn|), apply the force
             }
             else
             {
                 //if torsion, resize the tangential force such that |ft|=mu*|fn|
                 torsionForce *= species->getTorsionFrictionCoefficient() * getAbsoluteNormalForce() /
                                 std::sqrt(torsionForceSquared);
                 //resize the tangential spring accordingly such ft=-k*delta-nu*relVel
                 torsionSpring_ = -(torsionForce + species->getTorsionDissipation() * torsionRelativeVelocity) /
                                  species->getTorsionStiffness();
             }
             //Add (virtual) rolling force to torque
             addTorque(effectiveDiameter * torsionForce);
         }
         else //if no spring stiffness is set
         {
             logger(ERROR, "FrictionInteraction::computeFrictionForce(): Torsion stiffness is zero");
         }
     } //end if torsion force
 }
References abs(), BaseInteraction::addTorque(), SlidingFrictionInteraction::computeFrictionForce(), Vec3D::cross(), Vec3D::dot(), e(), ERROR, BaseInteraction::getAbsoluteNormalForce(), BaseInteraction::getBaseSpecies(), BaseHandler< T >::getDPMBase(), BaseInteraction::getEffectiveMass(), BaseInteraction::getEffectiveRadius(), BaseInteraction::getHandler(), BaseInteraction::getI(), Vec3D::getLength(), Vec3D::getLengthSquared(), BaseInteraction::getNormal(), BaseInteraction::getP(), FrictionSpecies::getRollingDissipation(), FrictionSpecies::getRollingFrictionCoefficient(), FrictionSpecies::getRollingFrictionCoefficientStatic(), FrictionSpecies::getRollingStiffness(), getSpecies(), DPMBase::getTimeStep(), FrictionSpecies::getTorsionDissipation(), FrictionSpecies::getTorsionFrictionCoefficient(), FrictionSpecies::getTorsionFrictionCoefficientStatic(), FrictionSpecies::getTorsionStiffness(), logger, rollingSpring_, rollingSpringVelocity_, sqrt(), mathsFunc::square(), torsionSpring_, and torsionSpringVelocity_.
getBaseName()
std::string FrictionInteraction::getBaseName () const
Returns interaction name/type.
Returns
std::string
 {
     return "Friction";
 }
getElasticEnergy()
Mdouble FrictionInteraction::getElasticEnergy () const override virtual
Returns the global amount of energy stored in all the springs (rolling, sliding and torsional).
Returns
Mdouble the total elastic energy stored in the frictional springs
Reimplemented from BaseInteraction.
 {
     if (getBaseSpecies()->getNormalForce()->getConstantRestitution()) {
         return SlidingFrictionInteraction::getElasticEnergy()
                + getEffectiveMass() * getSpecies()->getRollingStiffness() * rollingSpring_.getLengthSquared()
                + getEffectiveMass() * getSpecies()->getTorsionStiffness() * torsionSpring_.getLengthSquared();
     } else {
         return SlidingFrictionInteraction::getElasticEnergy()
                + 0.5 * getSpecies()->getRollingStiffness() * rollingSpring_.getLengthSquared()
                + 0.5 * getSpecies()->getTorsionStiffness() * torsionSpring_.getLengthSquared();
     }
 }
References BaseInteraction::getBaseSpecies(), BaseInteraction::getEffectiveMass(), SlidingFrictionInteraction::getElasticEnergy(), Vec3D::getLengthSquared(), FrictionSpecies::getRollingStiffness(), getSpecies(), FrictionSpecies::getTorsionStiffness(), rollingSpring_, and torsionSpring_.
getRollingSpring()
Vec3D FrictionInteraction::getRollingSpring () const
 {
     return rollingSpring_;
 }
References rollingSpring_.
getSpecies()
const FrictionSpecies * FrictionInteraction::getSpecies () const
Returns a const pointer of type FrictionSpecies*.
Returns
const FrictionSpecies*
 {
     return static_cast<const FrictionSpecies*>(getBaseSpecies()->getFrictionForce());
 ;
 }
References BaseInteraction::getBaseSpecies(), and BaseSpecies::getFrictionForce().
Referenced by computeFrictionForce(), and getElasticEnergy().
getTorsionSpring()
Vec3D FrictionInteraction::getTorsionSpring () const
 {
     return torsionSpring_;
 }
References torsionSpring_.
integrate()
void FrictionInteraction::integrate (Mdouble timeStep) override virtual
Computes the amount of compression in all the springs, i.e., increments the rollingSpring_, slidingSpring_ (see SlidingFrictionInteraction.cc) and torsionSpring_.
Parameters
[in] timeStep the amount of time by which the solution is evolved
Reimplemented from BaseInteraction.
 {
     SlidingFrictionInteraction::integrate(timeStep);
     rollingSpring_ += rollingSpringVelocity_ * timeStep;
     torsionSpring_ += Vec3D::dot(torsionSpring_ + torsionSpringVelocity_ * timeStep, getNormal()) * getNormal();
 }
References Vec3D::dot(), BaseInteraction::getNormal(), SlidingFrictionInteraction::integrate(), rollingSpring_, rollingSpringVelocity_, torsionSpring_, and torsionSpringVelocity_.
read()
void FrictionInteraction::read (std::istream & is) override virtual
Interaction read function, which accepts an std::istream as input.
Parameters
[in/out] is input file stream
Reimplemented from BaseInteraction.
 {
     SlidingFrictionInteraction::read(is);
     std::string dummy;
     is >> dummy >> rollingSpring_;
     is >> dummy >> torsionSpring_;
 }
References SlidingFrictionInteraction::read(), rollingSpring_, oomph::Global_string_for_annotation::string(), and torsionSpring_.
reverseHistory()
void FrictionInteraction::reverseHistory () override virtual
A useful feature if one wants to return to the initial state of the springs. However, reverse history decrements the current state to the state corresponding to previous time step. Decrements the state or value of rollingSpring_, torsionSpring_ and slidingSpring_.
Reimplemented from BaseInteraction.
 {
     SlidingFrictionInteraction::reverseHistory();
     //rollingSpring_=-rollingSpring_;
     //rollingSpringVelocity_=-rollingSpringVelocity_;
     torsionSpring_ = -torsionSpring_;
     torsionSpringVelocity_ = -torsionSpringVelocity_;
 }
References SlidingFrictionInteraction::reverseHistory(), torsionSpring_, and torsionSpringVelocity_.
rotateHistory()
void FrictionInteraction::rotateHistory (Matrix3D & rotationMatrix) override virtual
When periodic particles are used, some interactions need certain history properties rotated (e.g. tangential springs). This is the function for that.
Todo:
some of these might be unneccesary
Reimplemented from BaseInteraction.
 {
     SlidingFrictionInteraction::rotateHistory(rotationMatrix);
     rollingSpring_ = rotationMatrix * rollingSpring_;
     rollingSpringVelocity_ = rotationMatrix * rollingSpringVelocity_;
     torsionSpring_ = rotationMatrix * torsionSpring_;
     torsionSpringVelocity_ = rotationMatrix * torsionSpringVelocity_;
 }
References rollingSpring_, rollingSpringVelocity_, SlidingFrictionInteraction::rotateHistory(), torsionSpring_, and torsionSpringVelocity_.
setRollingSpring()
void FrictionInteraction::setRollingSpring (Vec3D rollingSpring)
 {
     rollingSpring_ = rollingSpring;
 }
References rollingSpring_.
setTorsionSpring()
void FrictionInteraction::setTorsionSpring (Vec3D torsionSpring)
 {
     torsionSpring_ = torsionSpring;
 }
References torsionSpring_.
write()
void FrictionInteraction::write (std::ostream & os) const override virtual
Interaction print function, which accepts an std::ostream as input.
Parameters
[in/out] os output file stream
Reimplemented from BaseInteraction.
 {
     SlidingFrictionInteraction::write(os);
     os << " rollingSpring " << rollingSpring_;
     os << " torsionSpring " << torsionSpring_;
 }
References rollingSpring_, torsionSpring_, and SlidingFrictionInteraction::write().
Member Data Documentation
rollingSpring_
Vec3D FrictionInteraction::rollingSpring_ private
Stores the amount of rolling spring compression. Set in integrate(), used in computing frictional force due to rolling.
Referenced by computeFrictionForce(), FrictionInteraction(), getElasticEnergy(), getRollingSpring(), integrate(), read(), rotateHistory(), setRollingSpring(), and write().
rollingSpringVelocity_
Vec3D FrictionInteraction::rollingSpringVelocity_ private
Stores the rate at which the rolling spring compresses or relaxes. Set in computeFrictionForce(), used in computing the amount of compression in rolling spring. Used in integrate().
Referenced by computeFrictionForce(), integrate(), and rotateHistory().
torsionSpring_
Vec3D FrictionInteraction::torsionSpring_ private
Stores the amount of torsional spring compression. Set in integrate(), used in computing frictional force due to torsion.
Referenced by computeFrictionForce(), FrictionInteraction(), getElasticEnergy(), getTorsionSpring(), integrate(), read(), reverseHistory(), rotateHistory(), setTorsionSpring(), and write().
torsionSpringVelocity_
Vec3D FrictionInteraction::torsionSpringVelocity_ private
Stores the rate at which the torsional spring compresses or relaxes. Set in computeFrictionForce(), used in computing the amount of compression in torsion spring. Used in integrate().
Referenced by computeFrictionForce(), integrate(), reverseHistory(), and rotateHistory().
The documentation for this class was generated from the following files:
FrictionInteraction.h
FrictionInteraction.cc