MercuryDPM: SpineGravityTractionElement< ELEMENT > Class Template Reference
SpineGravityTractionElement< ELEMENT > Class Template Reference
#include <extra_elements.h>
Public Member Functions
SpineGravityTractionElement (FiniteElement *const &element_pt, const int &face_index)
void hijack_all_nodes ()
void set_delta_p_pt (Data *const &delta_p_pt)
Access function to the pointer to pressure gradient data.
const double delta_p () const
Return the value of the pressure gradient.
unsigned nexternal_u_data ()
Return the number of external velocity data.
const double & viscosity_ratio () const
double *& viscosity_ratio_pt ()
Pointer to Viscosity Ratio.
const double & density_ratio () const
double *& density_ratio_pt ()
Pointer to Density ratio.
double *& re_invfr_pt ()
Pointer to Reynolds number divided by Froude number.
const double & re_invfr ()
Reynolds number divided by Froude number.
const Vector< double > & g () const
Vector of gravitational components.
Vector< double > *& g_pt ()
Pointer to Vector of gravitational components.
double u (const unsigned &l, const unsigned &i)
Access function for the velocity. N. B. HEAVY ASSUMPTIONS HERE.
double u (const unsigned &t, const unsigned &l, const unsigned &i) const
double du_dt (const unsigned &l, const unsigned &i) const
i-th component of du/dt at local node l.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the contribution to the residuals.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
This function returns the residuals and the jacobian.
void add_generic_residual_contribution (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
double get_flux ()
Calculate the flux.
void assign_additional_local_eqn_numbers ()
Define the local equation numbering schemes.
void output (ostream &outfile)
Overload the output function.
void output (ostream &outfile, const unsigned &Np)
Output function: x,y,[z],u,v,[w],p in tecplot format.
SpineGravityTractionElement (FiniteElement *element_pt, int face_index)
void node_update ()
unsigned nexternal_u_data ()
Return the number of external velocity data.
const double & viscosity_ratio () const
double *& viscosity_ratio_pt ()
Pointer to Viscosity Ratio.
const double & density_ratio () const
double *& density_ratio_pt ()
Pointer to Density ratio.
double *& re_invfr_pt ()
Pointer to Reynolds number divided by Froude number.
const double & re_invfr () const
Return the value of the Re/Fr number.
const Vector< double > & g () const
Vector of gravitational components.
Vector< double > *& g_pt ()
Pointer to Vector of gravitational components.
double flow ()
Calculate the flow across the element.
double u (const unsigned &l, const unsigned &i)
Access function for the velocity. N. B. HEAVY ASSUMPTIONS HERE.
double u (const unsigned &t, const unsigned &l, const unsigned &i) const
double du_dt (const unsigned &l, const unsigned &i) const
i-th component of du/dt at local node l.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the contribution to the residuals.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
This function returns the residuals and the jacobian.
void add_generic_residual_contribution (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
void assign_additional_local_eqn_numbers ()
Define the local equation numbering schemes.
void output (std::ostream &outfile)
Overload the output function.
void output (std::ostream &outfile, const unsigned &Np)
Output function: x,y,[z],u,v,[w],p in tecplot format.
Public Member Functions inherited from oomph::SpineElement< FaceGeometry< ELEMENT > >
SpineElement ()
Constructor, call the constructor of the base element.
SpineElement (FiniteElement *const &element_pt, const int &face_index)
Constructor used for spine face elements.
~SpineElement ()
Destructor, clean up the storage allocated to the local equation numbers.
int spine_local_eqn (const unsigned &n)
Public Member Functions inherited from oomph::ElementWithSpecificMovingNodes< ELEMENT, NODE_TYPE >
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
ElementWithSpecificMovingNodes ()
Constructor, call the constructor of the base element.
ElementWithSpecificMovingNodes (FiniteElement *const &element_pt, const int &face_index)
Constructor used for face elements.
~ElementWithSpecificMovingNodes ()
Empty Destructor,.
void describe_local_dofs (std::ostream &out, std::string &curr_str)
Unique final overrider for describe_dofs.
Node * construct_node (const unsigned &n)
Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
Overloaded node allocation for unsteady problems.
Node * construct_boundary_node (const unsigned &n)
Overload the node assignment routine to assign boundary nodes.
Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
Overloaded boundary node allocation for unsteady problems.
void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Compute the element's residuals vector and jacobian matrix.
void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
Compute the element's residuals vector and jacobian matrix.
Public Member Functions inherited from oomph::ElementWithMovingNodes
ElementWithMovingNodes ()
Constructor.
ElementWithMovingNodes (const ElementWithMovingNodes &)=delete
Broken copy constructor.
void operator= (const ElementWithMovingNodes &)=delete
Broken assignment operator.
virtual ~ElementWithMovingNodes ()
Virtual destructor (clean up and allocated memory)
unsigned ngeom_dof () const
Number of geometric dofs.
int geometric_data_local_eqn (const unsigned &n, const unsigned &i)
void assemble_set_of_all_geometric_data (std::set< Data * > &unique_geom_data_pt)
Return a set of all geometric data associated with the element.
void identify_geometric_data (std::set< Data * > &geometric_data_pt)
bool are_dresidual_dnodal_coordinates_always_evaluated_by_fd () const
Return whether shape derivatives are evaluated by fd.
void enable_always_evaluate_dresidual_dnodal_coordinates_by_fd ()
void disable_always_evaluate_dresidual_dnodal_coordinates_by_fd ()
void evaluate_shape_derivs_by_direct_fd ()
Evaluate shape derivatives by direct finite differencing.
void evaluate_shape_derivs_by_chain_rule (const bool &i_know_what_i_am_doing=false)
void evaluate_shape_derivs_by_fastest_method (const bool &i_know_what_i_am_doing=false)
int & method_for_shape_derivs ()
Access to method (enumerated flag) for determination of shape derivs.
void enable_bypass_fill_in_jacobian_from_geometric_data ()
Bypass the call to fill_in_jacobian_from_geometric_data.
void disable_bypass_fill_in_jacobian_from_geometric_data ()
Do not bypass the call to fill_in_jacobian_from_geometric_data.
bool is_fill_in_jacobian_from_geometric_data_bypassed () const
unsigned ngeom_data () const
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
virtual void disable_ALE ()
virtual void enable_ALE ()
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual unsigned nvertex_node () const
virtual Node * vertex_node_pt (const unsigned &j) const
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output (FILE *file_pt)
virtual void output (FILE *file_pt, const unsigned &n_plot)
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output an exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output a time-dependent exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void get_residuals (Vector< double > &residuals)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::SpineFiniteElement
SpineFiniteElement ()
Empty constructor.
virtual ~SpineFiniteElement ()
Emtpty virtual destructor.
Public Member Functions inherited from oomph::FaceElement
FaceElement ()
Constructor: Initialise all appropriate member data.
virtual ~FaceElement ()
Empty virtual destructor.
FaceElement (const FaceElement &)=delete
Broken copy constructor.
const unsigned & boundary_number_in_bulk_mesh () const
Broken assignment operator.
void set_boundary_number_in_bulk_mesh (const unsigned &b)
Set function for the boundary number in bulk mesh.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
double J_eulerian (const Vector< double > &s) const
double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
double interpolated_x (const Vector< double > &s, const unsigned &i) const
double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
void interpolated_x (const Vector< double > &s, Vector< double > &x) const
void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
int & normal_sign ()
int normal_sign () const
int & face_index ()
int face_index () const
const Vector< double > * tangent_direction_pt () const
Public access function for the tangent direction pointer.
void set_tangent_direction (Vector< double > *tangent_direction_pt)
Set the tangent direction vector.
void turn_on_warning_for_discontinuous_tangent ()
void turn_off_warning_for_discontinuous_tangent ()
void continuous_tangent_and_outer_unit_normal (const Vector< double > &s, Vector< Vector< double >> &tang_vec, Vector< double > &unit_normal) const
void continuous_tangent_and_outer_unit_normal (const unsigned &ipt, Vector< Vector< double >> &tang_vec, Vector< double > &unit_normal) const
void outer_unit_normal (const Vector< double > &s, Vector< double > &unit_normal) const
Compute outer unit normal at the specified local coordinate.
void outer_unit_normal (const unsigned &ipt, Vector< double > &unit_normal) const
Compute outer unit normal at ipt-th integration point.
FiniteElement *& bulk_element_pt ()
Pointer to higher-dimensional "bulk" element.
FiniteElement * bulk_element_pt () const
Pointer to higher-dimensional "bulk" element (const version)
CoordinateMappingFctPt & face_to_bulk_coordinate_fct_pt ()
CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt () const
BulkCoordinateDerivativesFctPt & bulk_coordinate_derivatives_fct_pt ()
BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt () const
Vector< double > local_coordinate_in_bulk (const Vector< double > &s) const
void get_local_coordinate_in_bulk (const Vector< double > &s, Vector< double > &s_bulk) const
void get_ds_bulk_ds_face (const Vector< double > &s, DenseMatrix< double > &dsbulk_dsface, unsigned &interior_direction) const
unsigned & bulk_position_type (const unsigned &i)
const unsigned & bulk_position_type (const unsigned &i) const
void bulk_node_number_resize (const unsigned &i)
Resize the storage for the bulk node numbers.
unsigned & bulk_node_number (const unsigned &n)
const unsigned & bulk_node_number (const unsigned &n) const
void bulk_position_type_resize (const unsigned &i)
Resize the storage for bulk_position_type to i entries.
unsigned & nbulk_value (const unsigned &n)
unsigned nbulk_value (const unsigned &n) const
void nbulk_value_resize (const unsigned &i)
void resize_nodes (Vector< unsigned > &nadditional_data_values)
void output_zeta (std::ostream &outfile, const unsigned &nplot)
Output boundary coordinate zeta.
Protected Member Functions
int invca_local_eqn ()
Protected Member Functions inherited from oomph::ElementWithMovingNodes
virtual void get_dnodal_coordinates_dgeom_dofs (RankThreeTensor< double > &dnodal_coordinates_dgeom_dofs)
void fill_in_jacobian_from_geometric_data (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_geometric_data (DenseMatrix< double > &jacobian)
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Member Functions inherited from oomph::FaceElement
void add_additional_values (const Vector< unsigned > &nadditional_values, const unsigned &id)
Protected Attributes
DenseMatrix< int > U_local_eqn
int Delta_P_local_eqn
unsigned External_Delta_P_index
DenseMatrix< int > External_u_local_eqn
Vector< unsigned > External_node
unsigned External_data_number_of_invca
Data * invca_data_pt
Pointer to the Data item that stores the capillary number.
double * bond_pt
Protected Attributes inherited from oomph::ElementWithMovingNodes
Vector< Data * > Geom_data_pt
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Protected Attributes inherited from oomph::FaceElement
unsigned Boundary_number_in_bulk_mesh
The boundary number in the bulk mesh to which this element is attached.
FiniteElement * Bulk_element_pt
Pointer to the associated higher-dimensional "bulk" element.
Vector< unsigned > Bulk_node_number
Vector< unsigned > Nbulk_value
Vector< double > * Tangent_direction_pt
Private Attributes
unsigned Dim
The highest dimension of the problem.
double * ReInvFr_pt
Pointer to the global Reynold number divided by the Froude number.
Vector< double > * G_pt
Pointer to global gravity Vector.
double * Viscosity_Ratio_pt
double * Density_Ratio_pt
Data * Delta_P_pt
Additional Inherited Members
Public Types inherited from oomph::ElementWithMovingNodes
enum { Shape_derivs_by_chain_rule , Shape_derivs_by_direct_fd , Shape_derivs_by_fastest_method }
Public enumeration to choose method for computing shape derivatives.
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
template<class ELEMENT>
class SpineGravityTractionElement< ELEMENT >
Special Face element used to calculate the additional inlet velocities and tractions when gravity has a component in the axial direction
Constructor & Destructor Documentation
SpineGravityTractionElement() [1/2]
template<class ELEMENT > SpineGravityTractionElement< ELEMENT >::SpineGravityTractionElement (FiniteElement *const & element_pt, const int & face_index) inline
Constructor, which takes a "bulk" element and the value of the index and its limit
                                                     :
   SpineElement<FaceGeometry<ELEMENT> >(), FaceElement()
   {
    //Attach the geometrical information to the element. N.B. This function
    //also assigns nbulk_data from the required_nvalue of the bulk element
    element_pt->build_face_element(face_index,this);
    //Set the dimension from the dimension of the first node
    Dim = node_pt(0)->ndim();
    //Set the Physical values from the bulk elemenet
    ELEMENT* cast_element_pt = dynamic_cast<ELEMENT*>(element_pt);
    this->ReInvFr_pt = cast_element_pt->re_invfr_pt();
    this->G_pt = cast_element_pt->g_pt();
    this->Viscosity_Ratio_pt = cast_element_pt->viscosity_ratio_pt();
    this->Density_Ratio_pt = cast_element_pt->density_ratio_pt();
    //Initialise the external pressure gradient pointer to zero
    Delta_P_pt=0;
    //Hijack the nodes in the bulk element in the axial coordinate
    unsigned n_node = this->nnode();
    for(unsigned m=0;m<n_node;m++)
     {
      delete cast_element_pt->hijack_nodal_value(bulk_node_number(m),0);
     }
    //The other nodes of the bulk element must be external data, because
    //they can affect the derivatives that are used in this element
    //Loop over the nodes of the parent element
    unsigned n_node_parent = cast_element_pt->nnode();
    for(unsigned n=0;n<n_node_parent;n++)
     {
      bool external=true;
      //Loop over the face nodes
      for(unsigned m=0;m<n_node;m++)
       {
        //If the parent's node is  one of the face nodes continue
        if(n == this->bulk_node_number(m)) {external=false;}
       }
      //If it's external data add it, but do not finite difference
      if(external)
       {
        this->add_external_data(cast_element_pt->node_pt(n),false);
        External_node.push_back(n);
       }
     }
    //Now add the spines of the bulk elemnt as external data, which
    //we will finite difference
    //Set of unique geometric data that is used to update the bulk,
    //but is not used to update the face
    std::set<Data*> unique_additional_geom_data;
    //Get all the geometric data for this (bulk) element
    cast_element_pt->assemble_set_of_all_geometric_data(
     unique_additional_geom_data);
    //Now assemble the set of geometric data for the face element
    std::set<Data*> unique_face_geom_data_pt;
    this->assemble_set_of_all_geometric_data(unique_face_geom_data_pt);
    //Erase the face geometric data from the additional data
    for(std::set<Data*>::iterator it=unique_face_geom_data_pt.begin();
        it!=unique_face_geom_data_pt.end();++it)
     {unique_additional_geom_data.erase(*it);}
    //Finally add all unique additional data as external data
    for(std::set<Data*>::iterator it = unique_additional_geom_data.begin();
        it!= unique_additional_geom_data.end();++it)
     {
      this->add_external_data(*it);
     }
   }
References oomph::FiniteElement::build_face_element(), Global_Variables::Dim, m, and n.
SpineGravityTractionElement() [2/2]
template<class ELEMENT > SpineGravityTractionElement< ELEMENT >::SpineGravityTractionElement (FiniteElement * element_pt, int face_index) inline
Constructor, which takes a "bulk" element and the value of the index and its limit
                                              :
   SpineElement<FaceGeometry<ELEMENT> >(), FaceElement()
   {
    //Attach the geometrical information to the element. N.B. This function
    //also assigns nbulk_data from the required_nvalue of the bulk element
    element_pt->build_face_element(face_index,this);
    //Set the dimension from the dimension of the first node
    Dim = node_pt(0)->ndim();
    //Initializa pointer
    invca_data_pt = 0;
    //Set the Physical values from the bulk elemenet
    ELEMENT* cast_element_pt = dynamic_cast<ELEMENT*>(element_pt);
    this->ReInvFr_pt = cast_element_pt->re_invfr_pt();
    this->G_pt = cast_element_pt->g_pt();
    this->Viscosity_Ratio_pt = cast_element_pt->viscosity_ratio_pt();
    this->Density_Ratio_pt = cast_element_pt->density_ratio_pt();
    //Hijack the nodes in the bulk element in the axial coordinate
    unsigned n_node = this->nnode();
    for(unsigned m=0;m<n_node;m++)
     {
      delete cast_element_pt->hijack_nodal_value(bulk_node_number(m),1);
     }
    //The other nodes of the bulk element must be external data, because
    //they can affect the derivatives that are used in this element
    //Loop over the nodes of the parent element
    unsigned n_node_parent = cast_element_pt->nnode();
    for(unsigned n=0;n<n_node_parent;n++)
     {
      bool external=true;
      //Loop over the face nodes
      for(unsigned m=0;m<n_node;m++)
       {
        //If the parent's node is  one of the face nodes continue
        if(n == this->bulk_node_number(m)) {external=false;}
       }
      //If it's external data add it
      if(external)
       {
        this->add_external_data(cast_element_pt->node_pt(n));
        External_node.push_back(n);
       }
     }
    //Now add the spines of the bulk elemnt as external data, which
    //we will finite difference
    //Set of unique geometric data that is used to update the bulk,
    //but is not used to update the face
    std::set<Data*> unique_additional_geom_data;
    //Get all the geometric data for this (bulk) element
    cast_element_pt->assemble_set_of_all_geometric_data(
     unique_additional_geom_data);
    //Now assemble the set of geometric data for the face element
    std::set<Data*> unique_face_geom_data_pt;
    this->assemble_set_of_all_geometric_data(unique_face_geom_data_pt);
    //Erase the face geometric data from the additional data
    for(std::set<Data*>::iterator it=unique_face_geom_data_pt.begin();
        it!=unique_face_geom_data_pt.end();++it)
     {unique_additional_geom_data.erase(*it);}
    //Finally add all unique additional data as geometric data
    /*for(std::set<Data*>::iterator it = unique_additional_geom_data.begin();
        it!= unique_additional_geom_data.end();++it)
     {
      this->add_external_data(*it);
      }*/
    this->identify_geometric_data(unique_additional_geom_data);
   }
References oomph::FiniteElement::build_face_element(), Global_Variables::Dim, m, and n.
Member Function Documentation
add_generic_residual_contribution() [1/2]
template<class ELEMENT > void SpineGravityTractionElement< ELEMENT >::add_generic_residual_contribution (Vector< double > & residuals, DenseMatrix< double > & jacobian, unsigned flag) inline
This function returns the residuals for the Navier–Stokes equations; flag=1(or 0): do (or don't) compute the Jacobian as well.
   {
    //Find out how many nodes there are
    unsigned n_node = nnode();
    //Set the value of n_intpt
    unsigned n_intpt = integral_pt()->nweight();
    //Set the Vector to hold local coordinates
    Vector<double> s(Dim-1);
    //Set the Vector to hold the local coordinates of the parent element
    Vector<double> s_parent(Dim);
    //Get a pointer to the parent element
    ELEMENT* bulk_el_pt = dynamic_cast<ELEMENT*>(bulk_element_pt());
    //Find the number of nodes in the parent element
    unsigned n_node_parent = bulk_el_pt->nnode();
    //Set up memory for shape functions and their derivatives
    Shape psif_parent(n_node_parent), testf_parent(n_node_parent);
    DShape dpsifdx_parent(n_node_parent,Dim),
     dtestfdx_parent(n_node_parent,Dim);
    //Storage for the local equation number
    int local_eqn=0, local_unknown=0;
    //Get the Physical Variable
    double ReInvFr = re_invfr()*density_ratio();
    double Viscosity_Ratio = viscosity_ratio();
    Vector<double> G = g();
    double Delta_p = delta_p();
    unsigned n_external_u = nexternal_u_data();
    //Loop over the integration points
    for(unsigned ipt=0;ipt<n_intpt;ipt++)
     {
      //Assign values of s
      for(unsigned i=0;i<(Dim-1);i++) {s[i] = integral_pt()->knot(ipt,i);}
      //Get the values of s_parent
      this->get_local_coordinate_in_bulk(s,s_parent);
      //Get the integral weight
      double w = integral_pt()->weight(ipt);
      //Find the shape functions and derivatives of the parent
      (void)bulk_el_pt->
       dshape_eulerian(s_parent,psif_parent,dpsifdx_parent);
      //Get the local jacobian for the FaceElement
      double J = J_eulerian(s);
      //Premultiply the weights and the Jacobian
      double W = w*J;
      //Need only to find the velocity derivatives
      DenseMatrix<double> interpolated_dudx(Dim,Dim,0.0);
      Vector<double> interpolated_u(Dim,0.0);
      //Calculate velocities and derivatives
      for(unsigned l=0;l<n_node_parent;l++)
       {
        //Loop over velocity components
        for(unsigned i=0;i<Dim;i++)
         {
          for(unsigned j=0;j<Dim;j++)
           {
            interpolated_dudx(i,j) +=
             bulk_el_pt->u_nst(l,i)*dpsifdx_parent(l,j);
           }
          dtestfdx_parent(l,i) = dpsifdx_parent(l,i);
          interpolated_u[i] += bulk_el_pt->u_nst(l,i)*psif_parent(l);
         }
        //Set the test functions to be the same as the shape functions
        testf_parent[l] = psif_parent[l];
       }
      //Storage for the outer unit normal
      Vector<double> normal(Dim);
      outer_unit_normal(s,normal);
      //Loop over the test functions
      for(unsigned l=0;l<n_node;l++)
       {
        //Do the first (axial) velocity component -- Poisson equation
        {
         unsigned i=0;
         local_eqn = U_local_eqn(l,i);
         /*IF it's not a boundary condition*/
         if(local_eqn >= 0)
          {
           //Add the pressure gradient
           residuals[local_eqn] +=
            Delta_p*testf_parent[bulk_node_number(l)]*W;
           //Add the gravitational body force term
           residuals[local_eqn] +=
            ReInvFr*testf_parent[bulk_node_number(l)]*G[i]*W;
           //Add in the Poisson terms (Only in y(1) direction)
           residuals[local_eqn] -= Viscosity_Ratio*
            (interpolated_dudx(i,1) /*+ interpolated_dudx(1,i)*/)
            *dtestfdx_parent(bulk_node_number(l),1)*W;
           //Now add the jacobian terms
           if(flag)
            {
             //Loop over all nodes again
             for(unsigned l2=0;l2<n_node;l2++)
              {
               {
                unsigned i2=0;
                local_unknown = U_local_eqn(l2,i2);
                if(local_unknown >= 0)
                 {
                  jacobian(local_eqn,local_unknown) -=
                   Viscosity_Ratio*(dpsifdx_parent(bulk_node_number(l2),1)*
                                    dtestfdx_parent(bulk_node_number(l),1))*W;
                 }
               }
               /*{
                unsigned i2=1;
                local_unknown = U_local_eqn(l2,i2);
                if(local_unknown >= 0)
                 {
                  jacobian(local_eqn,local_unknown) -=
                   Viscosity_Ratio*(dpsifdx_parent(bulk_node_number(l2),i)*
                                    dtestfdx_parent(bulk_node_number(l),1))*W;
                 }
                 }*/
              }
             //Loop over external data
             for(unsigned l2=0;l2<n_external_u;l2++)             {
               {
                unsigned i2=0;
                local_unknown = External_u_local_eqn(l2,i2);
                if(local_unknown >= 0)
                 {
                  jacobian(local_eqn,local_unknown) -=
                   Viscosity_Ratio*(dpsifdx_parent(External_node[l2],1)*
                                    dtestfdx_parent(bulk_node_number(l),1))*W;
                 }
               }
               /*{
                unsigned i2=1;
                local_unknown = External_u_local_eqn(l2,i2);
                if(local_unknown >= 0)
                 {
                  jacobian(local_eqn,local_unknown) -=
                   Viscosity_Ratio*(dpsifdx_parent(External_node[l2],i)*
                                    dtestfdx_parent(bulk_node_number(l),1))*W;
                 }
                 }*/
              }
             //Add in the pressure gradient term
             local_unknown = Delta_P_local_eqn;
             if(local_unknown >= 0)
              {
               jacobian(local_eqn,local_unknown) +=
                testf_parent[bulk_node_number(l)]*W;
              }
            } //End of if flag
          }
        }
        //Now do the second (traction) component
        /*     {
         unsigned i=1;
         local_eqn = U_local_eqn(l,i);
         //If it's not a boundary condition
         if(local_eqn >= 0)
          {
           for(unsigned k=0;k<Dim;k++)
            {
             residuals[local_eqn] += Viscosity_Ratio*
              (interpolated_dudx(i,k) + interpolated_dudx(k,i))*normal[k]
              *testf_parent(bulk_node_number(l))*W;
            }
           //Now add the jacobian terms
           if(flag)
            {
             //Loop over all nodes again
             for(unsigned l2=0;l2<n_node;l2++)
              {
               {
                unsigned i2=0;
                local_unknown = U_local_eqn(l2,i2);
                if(local_unknown >= 0)
                 {
                  jacobian(local_eqn,local_unknown) +=
                   Viscosity_Ratio*dpsifdx_parent(bulk_node_number(l2),i)*
                   normal[i2]*testf_parent(bulk_node_number(l))*W;
                 }
               }
               {
                unsigned i2=1;
                local_unknown = U_local_eqn(l2,i2);
                if(local_unknown >= 0)
                 {
                  for(unsigned k=0;k<Dim;k++)
                   {
                    jacobian(local_eqn,local_unknown) +=
                     Viscosity_Ratio*dpsifdx_parent(bulk_node_number(l2),k)*
                     normal[k]*testf_parent(bulk_node_number(l))*W;
                   }
                  jacobian(local_eqn,local_unknown) +=
                   Viscosity_Ratio*dpsifdx_parent(bulk_node_number(l2),i)*
                   normal[i2]*testf_parent(bulk_node_number(l))*W;
                 }
               }
              }
             //Loop over all external data
             for(unsigned l2=0;l2<n_external_u;l2++)
              {
               {
                unsigned i2=0;
                local_unknown = External_u_local_eqn(l2,i2);
                if(local_unknown >= 0)
                 {
                  jacobian(local_eqn,local_unknown) +=
                   Viscosity_Ratio*dpsifdx_parent(External_node[l2],i)*
                   normal[i2]*testf_parent(bulk_node_number(l))*W;
                 }
               }
               {
                unsigned i2=1;
                local_unknown = External_u_local_eqn(l2,i2);
                if(local_unknown >= 0)
                 {
                  for(unsigned k=0;k<Dim;k++)
                   {
                    jacobian(local_eqn,local_unknown) +=
                     Viscosity_Ratio*dpsifdx_parent(External_node[l2],k)*
                     normal[k]*testf_parent(bulk_node_number(l))*W;
                   }
                  jacobian(local_eqn,local_unknown) +=
                   Viscosity_Ratio*dpsifdx_parent(External_node[l2],i)*
                   normal[i2]*testf_parent(bulk_node_number(l))*W;
                 }
               }
              }
            }
          }
          }*/
       }
      //Add the contribution to the pressure gradient constraint,
      //which states that the flux must be 2.0
      local_eqn = Delta_P_local_eqn;
      if(local_eqn >= 0)
       {
        residuals[local_eqn] += interpolated_u[0]*W;
        //Add the jacobian terms
        if(flag)
         {
          //Loop over the nodes again
          for(unsigned l2=0;l2<n_node;l2++)
           {
            //Only the x-velocities at the nodes on the boundary
            //affect the residuals
            local_unknown = U_local_eqn(l2,0);
            if(local_unknown >= 0)
             {
              //Add the appropriate jacobian term
              jacobian(local_eqn,local_unknown) +=
               psif_parent(bulk_node_number(l2))*W;
             }
           }
         }
       }
     }
   }
References Global_Variables::Dim, G, i, J, j, WallFunction::normal(), GlobalPhysicalVariables::ReInvFr, s, Global_Physical_Variables::Viscosity_Ratio, w, and oomph::QuadTreeNames::W.
add_generic_residual_contribution() [2/2]
template<class ELEMENT > void SpineGravityTractionElement< ELEMENT >::add_generic_residual_contribution (Vector< double > & residuals, DenseMatrix< double > & jacobian, unsigned flag) inline
This function returns the residuals for the Navier–Stokes equations; flag=1(or 0): do (or don't) compute the Jacobian as well.
   {
    //Find out how many nodes there are
    unsigned n_node = nnode();
    //Set the value of n_intpt
    unsigned n_intpt = integral_pt()->nweight();
    //Set the Vector to hold local coordinates
    Vector<double> s(Dim-1);
    //Set the Vector to hold the local coordinates of the parent element
    Vector<double> s_parent(Dim);
    //Get a pointer to the parent element
    ELEMENT* bulk_el_pt = dynamic_cast<ELEMENT*>(bulk_element_pt());
    //Find the number of nodes in the parent element
    unsigned n_node_parent = bulk_el_pt->nnode();
    //Set up memory for shape functions and their derivatives
    Shape psif_parent(n_node_parent), testf_parent(n_node_parent);
    DShape dpsifdx_parent(n_node_parent,Dim),
     dtestfdx_parent(n_node_parent,Dim);
    //Storage for the local equation number
    int local_eqn=0, local_unknown=0;
    //Get the Physical Variable
    double ReInvFr = re_invfr()*density_ratio();
    double Viscosity_Ratio = viscosity_ratio();
    Vector<double> G = g();
    unsigned n_external =  this->nexternal_u_data();
    //Loop over the integration points
    for(unsigned ipt=0;ipt<n_intpt;ipt++)
     {
      //Assign values of s and s_parent
      for(unsigned i=0;i<(Dim-1);i++)  {s[i] = integral_pt()->knot(ipt,i);}
      //Get the local coordinate in the bulk
      this->get_local_coordinate_in_bulk(s,s_parent);
      //Get the integral weight
      double w = integral_pt()->weight(ipt);
      //Find the shape functions and derivatives of the parent
      (void)bulk_el_pt->
       dshape_eulerian(s_parent,psif_parent,dpsifdx_parent);
      //Get the local jacobian for the FaceElement
      double J = J_eulerian(s);
      //Premultiply the weights and the Jacobian
      double W = w*J;
      //Need only to find the velocity derivatives
      DenseMatrix<double> interpolated_dudx(Dim,Dim,0.0);
      Vector<double> interpolated_u(Dim,0.0);
      //Calculate velocities and derivatives
      for(unsigned l=0;l<n_node_parent;l++)
       {
        //Loop over velocity components
        for(unsigned i=0;i<Dim;i++)
         {
          for(unsigned j=0;j<Dim;j++)
           {
            interpolated_dudx(i,j) +=
             bulk_el_pt->u_nst(l,i)*dpsifdx_parent(l,j);
           }
          dtestfdx_parent(l,i) = dpsifdx_parent(l,i);
          interpolated_u[i] += bulk_el_pt->u_nst(l,i)*psif_parent(l);
         }
        //Set the test functions to be the same as the shape functions
        testf_parent[l] = psif_parent[l];
       }
      //Storage for the outer unit normal
      Vector<double> normal(Dim);
      outer_unit_normal(s,normal);
      //Loop over the test functions
      for(unsigned l=0;l<n_node;l++)
       {
        //Do the first (axial) velocity component -- Poisson equation
        {
         unsigned i=1;
         local_eqn = U_local_eqn(l,i);
         /*IF it's not a boundary condition*/
         if(local_eqn >= 0)
          {
           //Add the gravitational body force term
           residuals[local_eqn] +=
            ReInvFr*testf_parent[bulk_node_number(l)]*G[i]*W;
           //Add in the equation term (equation constant traction in the axial direction d(Tyy+p)/dy =0)
           residuals[local_eqn] -= Viscosity_Ratio*W* (
            ( interpolated_dudx(i,0) /*+ interpolated_dudx(0,i)*/ )
              *dtestfdx_parent(bulk_node_number(l),0) +
            ( interpolated_dudx(i,2) /*+ interpolated_dudx(2,i) */)
             *dtestfdx_parent(bulk_node_number(l),2) );
           //Now add the jacobian terms
           if(flag)
            {
             //Loop over all nodes again
             for(unsigned l2=0;l2<n_node;l2++)
              {
               /*   {
                unsigned i2=0;
                local_unknown = U_local_eqn(l2,i2);
                if(local_unknown >= 0)
                 {
                  jacobian(local_eqn,local_unknown) -=
                   Viscosity_Ratio*(dpsifdx_parent(bulk_node_number(l2),i)*
                                    dtestfdx_parent(bulk_node_number(l),0))*W;
                 }
                 } */
               //Poisson equation term
               {
                unsigned i2=1;
                local_unknown = U_local_eqn(l2,i2);
                if(local_unknown >= 0)
                 {
                  jacobian(local_eqn,local_unknown) -=
                   Viscosity_Ratio*(dpsifdx_parent(bulk_node_number(l2),0)*
                                    dtestfdx_parent(bulk_node_number(l),0)  +
                                    dpsifdx_parent(bulk_node_number(l2),2)*
                                    dtestfdx_parent(bulk_node_number(l),2) )*W;
                 }
               }
               /* {
                unsigned i2=2;
                local_unknown = U_local_eqn(l2,i2);
                if(local_unknown >= 0)
                 {
                  jacobian(local_eqn,local_unknown) -=
                   Viscosity_Ratio*(dpsifdx_parent(bulk_node_number(l2),i)*
                                    dtestfdx_parent(bulk_node_number(l),2))*W;
                 }
                 }*/
              }
             //Loop over external data
             for(unsigned l2=0;l2<n_external;l2++)
              {
               /* {
                unsigned i2=0;
                local_unknown = External_u_local_eqn(l2,i2);
                if(local_unknown >= 0)
                 {
                  jacobian(local_eqn,local_unknown) -=
                   Viscosity_Ratio*(dpsifdx_parent(External_node[l2],i)*
                                    dtestfdx_parent(bulk_node_number(l),0))*W;
                 }
                 }*/
               //Poisson equation term
               {
                unsigned i2=1;
                local_unknown = External_u_local_eqn(l2,i2);
                if(local_unknown >= 0)
                 {
                  jacobian(local_eqn,local_unknown) -=
                   Viscosity_Ratio*(dpsifdx_parent(External_node[l2],0)*
                                    dtestfdx_parent(bulk_node_number(l),0)  +
                                    dpsifdx_parent(External_node[l2],2)*
                                    dtestfdx_parent(bulk_node_number(l),2)  )*W;
                 }
               }
               /*{
                unsigned i2=2;
                local_unknown = External_u_local_eqn(l2,i2);
                if(local_unknown >= 0)
                 {
                  jacobian(local_eqn,local_unknown) -=
                   Viscosity_Ratio*(dpsifdx_parent(External_node[l2],i)*
                                    dtestfdx_parent(bulk_node_number(l),2))*W;
                 }
                 }*/
              }
            } //End of if flag
          }
        }
        //Now do the other (traction) components
        /* for(unsigned i =0;i<3;i+=2)
        {
         local_eqn = U_local_eqn(l,i);
         //If it's not a boundary condition
         if(local_eqn >= 0)
          {
           for(unsigned k=0;k<Dim;k++)
            {
             residuals[local_eqn] += Viscosity_Ratio*
              (interpolated_dudx(i,k) + interpolated_dudx(k,i))*normal[k]
              *testf_parent(bulk_node_number(l))*W;
            }
           //Now add the jacobian terms
           if(flag)
            {
             //Loop over all nodes again
             for(unsigned l2=0;l2<n_node;l2++)
              {
               for(unsigned i2=0;i2<Dim;i2++)
               {
                if(i2!=i)
                {
                  // unsigned i2=0;
                  local_unknown = U_local_eqn(l2,i2);
                  if(local_unknown >= 0)
                   {
                     jacobian(local_eqn,local_unknown) +=
                     Viscosity_Ratio*dpsifdx_parent(bulk_node_number(l2),i)*
                     normal[i2]*testf_parent(bulk_node_number(l))*W;
                   }
                 }
                  else
                  {
                  // unsigned i2=1;
                   local_unknown = U_local_eqn(l2,i2);
                   if(local_unknown >= 0)
                   {
                      for(unsigned k=0;k<Dim;k++)
                      {
                        jacobian(local_eqn,local_unknown) +=
                        Viscosity_Ratio*dpsifdx_parent(bulk_node_number(l2),k)*
                        normal[k]*testf_parent(bulk_node_number(l))*W;
                      }
                      jacobian(local_eqn,local_unknown) +=
                      Viscosity_Ratio*dpsifdx_parent(bulk_node_number(l2),i)*
                      normal[i2]*testf_parent(bulk_node_number(l))*W;
                   }
                 }
               }
              }
             //Loop over all external data
             for(unsigned l2=0;l2<n_external;l2++)
              {
               for(unsigned i2=0;i2<Dim;i2++)
               {
                if (i2!=i)
                 {
                  //unsigned i2=0;
                  local_unknown = External_u_local_eqn(l2,i2);
                  if(local_unknown >= 0)
                   {
                    jacobian(local_eqn,local_unknown) +=
                     Viscosity_Ratio*dpsifdx_parent(External_node[l2],i)*
                     normal[i2]*testf_parent(bulk_node_number(l))*W;
                   }
                 }
                 else
                 {
                    //unsigned i2=1;
                  local_unknown = External_u_local_eqn(l2,i2);
                  if(local_unknown >= 0)
                   {
                    for(unsigned k=0;k<Dim;k++)
                     {
                      jacobian(local_eqn,local_unknown) +=
                       Viscosity_Ratio*dpsifdx_parent(External_node[l2],k)*
                       normal[k]*testf_parent(bulk_node_number(l))*W;
                     }
                    jacobian(local_eqn,local_unknown) +=
                     Viscosity_Ratio*dpsifdx_parent(External_node[l2],i)*
                     normal[i2]*testf_parent(bulk_node_number(l))*W;
                   }
                 }
                }
                }
            }
          }
          } */
       }
     }
   }
References Global_Variables::Dim, G, i, J, j, WallFunction::normal(), GlobalPhysicalVariables::ReInvFr, s, Global_Physical_Variables::Viscosity_Ratio, w, and oomph::QuadTreeNames::W.
assign_additional_local_eqn_numbers() [1/2]
template<class ELEMENT > void SpineGravityTractionElement< ELEMENT >::assign_additional_local_eqn_numbers () inline virtual
Define the local equation numbering schemes.
Reimplemented from oomph::GeneralisedElement.
   {
    //Get number of nodes
    unsigned n_node = nnode();
    //Resize the equation counters
    U_local_eqn.resize(n_node,Dim);
    //Loop over the nodes
    for(unsigned i=0;i<n_node;i++)
     {
      //Loop over the nodal values
      for(unsigned j=0;j<Dim;j++)
       {
        U_local_eqn(i,j) = this->nodal_local_eqn(i,j);
       }
     }
    //Now sort out the external degrees of freedom
    //Find the number of external degrees of freedom
    unsigned n_external_u = nexternal_u_data();
    //Resize the external degree of freedom counter
    External_u_local_eqn.resize(n_external_u,Dim);
    //Loop over the external degrees of freedom
    for(unsigned e=0;e<n_external_u;e++)
     {
      //Loop over the velocity values
      for(unsigned i=0;i<Dim;i++)
       {
        External_u_local_eqn(e,i) = external_local_eqn(e,i);
       }
     }
    //Add the final additional data object for the external pressure
    //gradient
    if(Delta_P_pt!=0)
     {
      //This is the final external data object
      Delta_P_local_eqn = external_local_eqn(External_Delta_P_index,0);
     }
    else
     {
      Delta_P_local_eqn = -1;
     }
   }
References Global_Variables::Dim, e(), i, j, and oomph::DenseMatrix< T >::resize().
assign_additional_local_eqn_numbers() [2/2]
template<class ELEMENT > void SpineGravityTractionElement< ELEMENT >::assign_additional_local_eqn_numbers () inline virtual
Define the local equation numbering schemes.
Reimplemented from oomph::GeneralisedElement.
   {
    //Get number of nodes
    unsigned n_node = nnode();
    //Resize the equation counters
    U_local_eqn.resize(n_node,Dim);
    //Loop over the nodes
    for(unsigned i=0;i<n_node;i++)
     {
      //Loop over the nodal values
      for(unsigned j=0;j<Dim;j++)
       {
        U_local_eqn(i,j) = this->nodal_local_eqn(i,j);
       }
     }
    //Now sort out the external degrees of freedom
    //Find the number of external degrees of freedom
   //ACHTUNG !!!!!!
 //   unsigned n_external = nexternal_data();
  unsigned n_external =  External_node.size();
    //Resize the external degree of freedom counter
    External_u_local_eqn.resize(n_external,Dim);
    //Loop over the external degrees of freedom
    for(unsigned e=0;e<n_external;e++)
     {
      //Loop over the velocity values
      for(unsigned i=0;i<Dim;i++)
       {
        External_u_local_eqn(e,i) = external_local_eqn(e,i);
       }
     }
   }
References Global_Variables::Dim, e(), i, j, and oomph::DenseMatrix< T >::resize().
delta_p()
template<class ELEMENT > const double SpineGravityTractionElement< ELEMENT >::delta_p () const inline
Return the value of the pressure gradient.
   {
    if(Delta_P_pt==0) {return 0.0;}
    else {return Delta_P_pt->value(0);}
   }
References oomph::Data::value().
density_ratio() [1/2]
template<class ELEMENT > const double& SpineGravityTractionElement< ELEMENT >::density_ratio () const inline
Density ratio for element: Element's density relative to the viscosity used in the definition of the Reynolds number
 {return *Density_Ratio_pt;}
density_ratio() [2/2]
template<class ELEMENT > const double& SpineGravityTractionElement< ELEMENT >::density_ratio () const inline
Density ratio for element: Element's density relative to the viscosity used in the definition of the Reynolds number
 {return *Density_Ratio_pt;}
density_ratio_pt() [1/2]
template<class ELEMENT > double* & SpineGravityTractionElement< ELEMENT >::density_ratio_pt () inline
Pointer to Density ratio.
 {return Density_Ratio_pt;}
density_ratio_pt() [2/2]
template<class ELEMENT > double* & SpineGravityTractionElement< ELEMENT >::density_ratio_pt () inline
Pointer to Density ratio.
 {return Density_Ratio_pt;}
du_dt() [1/2]
template<class ELEMENT > double SpineGravityTractionElement< ELEMENT >::du_dt (const unsigned & l, const unsigned & i) const inline
i-th component of du/dt at local node l.
   {
    // Get the data's timestepper
    TimeStepper* time_stepper_pt=node_pt(l)->time_stepper_pt();
    // Number of timsteps (past & present)
    unsigned n_time = time_stepper_pt->ntstorage();
    double dudt=0.0;
    //Loop over the timesteps
    if (time_stepper_pt->type()!="Steady")
     {
      for(unsigned t=0;t<n_time;t++)
       {
        dudt+=time_stepper_pt->weight(1,t)*u(t,l,i);
       }
     }
    return dudt;
   }
References i, oomph::TimeStepper::ntstorage(), plotPSD::t, oomph::TimeStepper::type(), and oomph::TimeStepper::weight().
du_dt() [2/2]
template<class ELEMENT > double SpineGravityTractionElement< ELEMENT >::du_dt (const unsigned & l, const unsigned & i) const inline
i-th component of du/dt at local node l.
   {
    // Get the data's timestepper
       TimeStepper* time_stepper_pt=node_pt(l)->time_stepper_pt(); // cgj: previously Node_pt[l] -- but (interpreting as FiniteElement::Node_pt as clang does) this is private!
    // Number of timsteps (past & present)
    unsigned n_time = time_stepper_pt->ntstorage();
    double dudt=0.0;
    //Loop over the timesteps
    if (time_stepper_pt->type()!="Steady")
     {
      for(unsigned t=0;t<n_time;t++)
       {
        dudt+=time_stepper_pt->weight(1,t)*u(t,l,i);
       }
     }
    return dudt;
   }
References i, oomph::TimeStepper::ntstorage(), plotPSD::t, oomph::TimeStepper::type(), and oomph::TimeStepper::weight().
fill_in_contribution_to_jacobian() [1/2]
template<class ELEMENT > void SpineGravityTractionElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline virtual
This function returns the residuals and the jacobian.
Reimplemented from oomph::GeneralisedElement.
   {
    //Call the generic routine with the flag set to 1
    add_generic_residual_contribution(residuals,jacobian,1);
    //Add in external data contributions
    this->fill_in_jacobian_from_external_by_fd(jacobian);
    //Add the spine contributions
    this->fill_in_jacobian_from_geometric_data(jacobian);
   }
fill_in_contribution_to_jacobian() [2/2]
template<class ELEMENT > void SpineGravityTractionElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline virtual
This function returns the residuals and the jacobian.
Reimplemented from oomph::GeneralisedElement.
   {
    //Call the generic routine with the flag set to 1
    add_generic_residual_contribution(residuals,jacobian,1);
    //Add the external data
    this->fill_in_jacobian_from_external_by_fd(jacobian);
    //Add the spine contributions
    this->fill_in_jacobian_from_geometric_data(jacobian);
   }
fill_in_contribution_to_residuals() [1/2]
template<class ELEMENT > void SpineGravityTractionElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) inline virtual
Add the contribution to the residuals.
Reimplemented from oomph::GeneralisedElement.
   {
    //Create a dummy matrix
    DenseMatrix<double> dummy(1);
    //Call the generic residuals function with flag set to 0
    add_generic_residual_contribution(residuals,dummy,0);
   }
fill_in_contribution_to_residuals() [2/2]
template<class ELEMENT > void SpineGravityTractionElement< ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residuals) inline virtual
Add the contribution to the residuals.
Reimplemented from oomph::GeneralisedElement.
   {
    //Create a dummy matrix
    DenseMatrix<double> dummy(1);
    //Call the generic residuals function with flag set to 0
    add_generic_residual_contribution(residuals,dummy,0);
   }
flow()
template<class ELEMENT > double SpineGravityTractionElement< ELEMENT >::flow () inline
Calculate the flow across the element.
   {
    //Storage for the normal flux
    double flux = 0.0;
    //Set the value of n_intpt
    const unsigned n_intpt = integral_pt()->nweight();
    //Set the Vector to hold local coordinates
    Vector<double> s(Dim-1);
    //Set the Vector to hold the local coordinates of the parent element
    Vector<double> s_parent(Dim);
    //Get a pointer to the parent element
    ELEMENT* bulk_el_pt = dynamic_cast<ELEMENT*>(bulk_element_pt());
    //Loop over the integration points
    for(unsigned ipt=0;ipt<n_intpt;ipt++)
     {
      //Assign values of s and s_parent
      for(unsigned i=0;i<(Dim-1);i++)  {s[i] = integral_pt()->knot(ipt,i);}
      //Get the local coordinate in the bulk
      this->get_local_coordinate_in_bulk(s,s_parent);
      //Get the integral weight
      double w = integral_pt()->weight(ipt);
      //Get the local jacobian for the FaceElement
      double J = J_eulerian(s);
      //Premultiply the weights and the Jacobian
      double W = w*J;
      //Get the velocity from the parent
      Vector<double> interpolated_u(Dim,0.0);
      bulk_el_pt->interpolated_u_nst(s_parent,interpolated_u);
      //Get the outer unit normal
      Vector<double> normal(Dim,0);
      outer_unit_normal(s,normal);
      //Find the normal flux
      double normal_flux = 0.0;
      for(unsigned i=0;i<Dim;i++) {normal_flux += interpolated_u[i]*normal[i];}
      //Add to the flux
      flux += normal_flux*W;
     } //End of loop over integration points
    //Return the flux
    return flux;
   }
References Global_Variables::Dim, ProblemParameters::flux(), i, J, WallFunction::normal(), s, w, and oomph::QuadTreeNames::W.
g() [1/2]
template<class ELEMENT > const Vector<double>& SpineGravityTractionElement< ELEMENT >::g () const inline
Vector of gravitational components.
 {return *G_pt;}
g() [2/2]
template<class ELEMENT > const Vector<double>& SpineGravityTractionElement< ELEMENT >::g () const inline
Vector of gravitational components.
 {return *G_pt;}
g_pt() [1/2]
template<class ELEMENT > Vector<double>* & SpineGravityTractionElement< ELEMENT >::g_pt () inline
Pointer to Vector of gravitational components.
 {return G_pt;}
Referenced by AirwayReopeningProblem< ELEMENT >::AirwayReopeningProblem(), and ThreeDimBethertonProblem< ELEMENT >::ThreeDimBethertonProblem().
g_pt() [2/2]
template<class ELEMENT > Vector<double>* & SpineGravityTractionElement< ELEMENT >::g_pt () inline
Pointer to Vector of gravitational components.
 {return G_pt;}
get_flux()
template<class ELEMENT > double SpineGravityTractionElement< ELEMENT >::get_flux () inline
Calculate the flux.
   {
    //Initialise flux to zero
    double flux = 0.0;
    //Find out how many nodes there are
    unsigned n_node = nnode();
    //Set the value of n_intpt
    unsigned n_intpt = integral_pt()->nweight();
    //Set the Vector to hold local coordinates
    Vector<double> s(Dim-1);
    //Set up memory for shape functions and their derivatives
    Shape psif(n_node);
    //Loop over the integration points
    for(unsigned ipt=0;ipt<n_intpt;ipt++)
     {
      //Assign values of s and s_parent
      for(unsigned i=0;i<(Dim-1);i++)
       {s[i] = integral_pt()->knot(ipt,i);}
      //Get the integral weight
      double w = integral_pt()->weight(ipt);
      //Find the shape functions and derivatives of the parent
      shape(s,psif);
      //Get the local jacobian for the FaceElement
      double J = J_eulerian(s);
      //Premultiply the weights and the Jacobian
      double W = w*J;
      Vector<double> interpolated_u(Dim,0.0);
      //Calculate velocities and derivatives
      for(unsigned l=0;l<n_node;l++)
       {
        //Loop over velocity components
        for(unsigned i=0;i<Dim;i++)
         {
          interpolated_u[i] += u(l,i)*psif(l);
         }
       }
      flux += interpolated_u[0]*W;
     }
    return flux;
   }
References Global_Variables::Dim, ProblemParameters::flux(), i, J, s, oomph::OneDimLagrange::shape(), w, and oomph::QuadTreeNames::W.
hijack_all_nodes()
template<class ELEMENT > void SpineGravityTractionElement< ELEMENT >::hijack_all_nodes () inline
   {
    ELEMENT* cast_element_pt = dynamic_cast<ELEMENT*>(bulk_element_pt());
    //Hijack the nodes in the bulk element in the axial coordinate
    unsigned n_node = this->nnode();
    for(unsigned m=0;m<n_node;m++)
     {
      delete cast_element_pt->hijack_nodal_value(bulk_node_number(m),0);
     }
   }
References m.
invca_local_eqn()
template<class ELEMENT > int SpineGravityTractionElement< ELEMENT >::invca_local_eqn () inline protected
 {
  return external_local_eqn(External_data_number_of_invca,0);
 }
nexternal_u_data() [1/2]
template<class ELEMENT > unsigned SpineGravityTractionElement< ELEMENT >::nexternal_u_data () inline
Return the number of external velocity data.
 {return External_node.size();}
nexternal_u_data() [2/2]
template<class ELEMENT > unsigned SpineGravityTractionElement< ELEMENT >::nexternal_u_data () inline
Return the number of external velocity data.
 {return External_node.size();}
node_update()
template<class ELEMENT > void SpineGravityTractionElement< ELEMENT >::node_update () inline virtual
Update the positions of all nodes in the element using each node update function. The default implementation may be overloaded so that more efficient versions can be written
Loop over all nodes in the element and update their positions using each node's (algebraic) update function
Reimplemented from oomph::FiniteElement.
   {
    this->bulk_element_pt()->node_update();
   }
output() [1/4]
template<class ELEMENT > void SpineGravityTractionElement< ELEMENT >::output (ostream & outfile) inline virtual
Overload the output function.
Reimplemented from oomph::FiniteElement.
 { }
output() [2/4]
template<class ELEMENT > void SpineGravityTractionElement< ELEMENT >::output (ostream & outfile, const unsigned & Np) inline virtual
Output function: x,y,[z],u,v,[w],p in tecplot format.
Reimplemented from oomph::FiniteElement.
 { }
output() [3/4]
template<class ELEMENT > void SpineGravityTractionElement< ELEMENT >::output (std::ostream & outfile) inline virtual
Overload the output function.
Reimplemented from oomph::FiniteElement.
 { }
output() [4/4]
template<class ELEMENT > void SpineGravityTractionElement< ELEMENT >::output (std::ostream & outfile, const unsigned & Np) inline virtual
Output function: x,y,[z],u,v,[w],p in tecplot format.
Reimplemented from oomph::FiniteElement.
  {
   SpineElement<FaceGeometry<ELEMENT> >::output(outfile,Np);
  }
References oomph::output().
re_invfr() [1/2]
template<class ELEMENT > const double& SpineGravityTractionElement< ELEMENT >::re_invfr () inline
Reynolds number divided by Froude number.
 {return *ReInvFr_pt;}
re_invfr() [2/2]
template<class ELEMENT > const double& SpineGravityTractionElement< ELEMENT >::re_invfr () const inline
Return the value of the Re/Fr number.
 {return *ReInvFr_pt;}
re_invfr_pt() [1/2]
template<class ELEMENT > double* & SpineGravityTractionElement< ELEMENT >::re_invfr_pt () inline
Pointer to Reynolds number divided by Froude number.
 {return ReInvFr_pt;}
Referenced by AirwayReopeningProblem< ELEMENT >::AirwayReopeningProblem(), and ThreeDimBethertonProblem< ELEMENT >::ThreeDimBethertonProblem().
re_invfr_pt() [2/2]
template<class ELEMENT > double* & SpineGravityTractionElement< ELEMENT >::re_invfr_pt () inline
Pointer to Reynolds number divided by Froude number.
 {return ReInvFr_pt;}
set_delta_p_pt()
template<class ELEMENT > void SpineGravityTractionElement< ELEMENT >::set_delta_p_pt (Data *const & delta_p_pt) inline
Access function to the pointer to pressure gradient data.
   {
    Delta_P_pt = delta_p_pt;
    //Add the external data and do not finite difference it!
    External_Delta_P_index = add_external_data(delta_p_pt,false);
   }
Referenced by AirwayReopeningProblem< ELEMENT >::construct_poisson_outlet_elements().
u() [1/4]
template<class ELEMENT > double SpineGravityTractionElement< ELEMENT >::u (const unsigned & l, const unsigned & i) inline
Access function for the velocity. N. B. HEAVY ASSUMPTIONS HERE.
   {return nodal_value(l,i);}
References i.
u() [2/4]
template<class ELEMENT > double SpineGravityTractionElement< ELEMENT >::u (const unsigned & l, const unsigned & i) inline
Access function for the velocity. N. B. HEAVY ASSUMPTIONS HERE.
   {return this->nodal_value(l,i);}
References i.
u() [3/4]
template<class ELEMENT > double SpineGravityTractionElement< ELEMENT >::u (const unsigned & t, const unsigned & l, const unsigned & i) const inline
/// Velocity i at local node l at timestep t (t=0: present; t>0: previous). SIMILAR HEAVY ASSUMPTIONS
   {return nodal_value(t,l,i);}
References i, and plotPSD::t.
u() [4/4]
template<class ELEMENT > double SpineGravityTractionElement< ELEMENT >::u (const unsigned & t, const unsigned & l, const unsigned & i) const inline
/// Velocity i at local node l at timestep t (t=0: present; t>0: previous). SIMILAR HEAVY ASSUMPTIONS
   {return this->nodal_value(t,l,i);}
References i, and plotPSD::t.
viscosity_ratio() [1/2]
template<class ELEMENT > const double& SpineGravityTractionElement< ELEMENT >::viscosity_ratio () const inline
Viscosity ratio for element: Element's viscosity relative to the viscosity used in the definition of the Reynolds number
 {return *Viscosity_Ratio_pt;}
viscosity_ratio() [2/2]
template<class ELEMENT > const double& SpineGravityTractionElement< ELEMENT >::viscosity_ratio () const inline
Viscosity ratio for element: Element's viscosity relative to the viscosity used in the definition of the Reynolds number
 {return *Viscosity_Ratio_pt;}
viscosity_ratio_pt() [1/2]
template<class ELEMENT > double* & SpineGravityTractionElement< ELEMENT >::viscosity_ratio_pt () inline
Pointer to Viscosity Ratio.
 {return Viscosity_Ratio_pt;}
viscosity_ratio_pt() [2/2]
template<class ELEMENT > double* & SpineGravityTractionElement< ELEMENT >::viscosity_ratio_pt () inline
Pointer to Viscosity Ratio.
 {return Viscosity_Ratio_pt;}
Member Data Documentation
bond_pt
template<class ELEMENT > double* SpineGravityTractionElement< ELEMENT >::bond_pt protected
Delta_P_local_eqn
template<class ELEMENT > int SpineGravityTractionElement< ELEMENT >::Delta_P_local_eqn protected
The local equation number for the external data associated with the unknown pressure gradient
Delta_P_pt
template<class ELEMENT > Data* SpineGravityTractionElement< ELEMENT >::Delta_P_pt private
Pointer to an External Data object that represents the an unknown pressure gradient
Density_Ratio_pt
template<class ELEMENT > double * SpineGravityTractionElement< ELEMENT >::Density_Ratio_pt private
Pointer to the density ratio (relative to the density used in the definition of the Reynolds number)
Dim
template<class ELEMENT > unsigned SpineGravityTractionElement< ELEMENT >::Dim private
The highest dimension of the problem.
External_data_number_of_invca
template<class ELEMENT > unsigned SpineGravityTractionElement< ELEMENT >::External_data_number_of_invca protected
The Data that contains the capillary number is stored as external Data for the element. Which external Data item is it?
External_Delta_P_index
template<class ELEMENT > unsigned SpineGravityTractionElement< ELEMENT >::External_Delta_P_index protected
The index in the external data at which the Delta_p data is stored
External_node
template<class ELEMENT > Vector< unsigned > SpineGravityTractionElement< ELEMENT >::External_node protected
Vector to keep track of the external data associated with each bulk node
External_u_local_eqn
template<class ELEMENT > DenseMatrix< int > SpineGravityTractionElement< ELEMENT >::External_u_local_eqn protected
Array to hold the local eqn number information for the external data (other nodes in the bulk element)
G_pt
template<class ELEMENT > Vector< double > * SpineGravityTractionElement< ELEMENT >::G_pt private
Pointer to global gravity Vector.
invca_data_pt
template<class ELEMENT > Data* SpineGravityTractionElement< ELEMENT >::invca_data_pt protected
Pointer to the Data item that stores the capillary number.
ReInvFr_pt
template<class ELEMENT > double * SpineGravityTractionElement< ELEMENT >::ReInvFr_pt private
Pointer to the global Reynold number divided by the Froude number.
U_local_eqn
template<class ELEMENT > DenseMatrix< int > SpineGravityTractionElement< ELEMENT >::U_local_eqn protected
Array to hold local eqn number information for veloc: U_local_eqn(jnod,i) = local equation number or < 0 if pinned
Viscosity_Ratio_pt
template<class ELEMENT > double * SpineGravityTractionElement< ELEMENT >::Viscosity_Ratio_pt private
Pointer to the viscosity ratio (relative to the viscosity used in the definition of the Reynolds number)
The documentation for this class was generated from the following files:
elastic_bretherton.cc
extra_elements.h