MercuryDPM: trmv_upt.cpp File Reference
trmv_upt.cpp File Reference
#include "gemv_common.h"
Functions
EIGEN_DONT_INLINE void trmv (const Mat &A, Vec &B, const Vec &C)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc , char ** argv)
 { return main_gemv(argc, argv, trmv); }
References main_gemv(), and trmv().
trmv()
EIGEN_DONT_INLINE void trmv (const Mat & A, Vec & B, const Vec & C)
{
   B.noalias() += A.transpose().triangularView<Upper>() * C;
 }
References Eigen::Upper.
Referenced by main().