MercuryDPM: adaptive_driven_cavity_load_balance.cc File Reference
adaptive_driven_cavity_load_balance.cc File Reference
#include "generic.h"
#include "navier_stokes.h"
#include "meshes/rectangular_quadmesh.h"
Classes
class RefineableDrivenCavityProblem< ELEMENT >
Namespaces
Global_Physical_Variables
Global variables.
Functions
int main (int argc, char **argv)
Driver for RefineableDrivenCavity test problem.
Function Documentation
main()
int main (int argc , char ** argv)
Driver for RefineableDrivenCavity test problem.
 {
 #ifdef OOMPH_HAS_MPI
  // Initialise MPI
  MPI_Helpers::init(argc,argv);
 #endif
   // Switch off output modifier
  oomph_info.output_modifier_pt() = &default_output_modifier;
  // Define processor-labeled output file for all on-screen stuff
  std::ofstream output_stream;
  char filename[100];
  sprintf(filename,"OUTPUT.%i",MPI_Helpers::communicator_pt()->my_rank());
  output_stream.open(filename);
  oomph_info.stream_pt() = &output_stream;
  OomphLibWarning::set_stream_pt(&output_stream);
  OomphLibError::set_stream_pt(&output_stream);
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Use manual distribution of elements rather than metis
  CommandLineArgs::specify_command_line_flag("--validate");
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  //Build problem
  RefineableDrivenCavityProblem<RefineableQTaylorHoodElement<2> > problem;
  // Tell us what you're doing
  bool report_stats=true;
  // Metis or manual distribution?
  if (!CommandLineArgs::command_line_flag_has_been_set("--validate"))
   {
    // Distribute with metis
    problem.distribute(report_stats);
   }
  else
   {
    // Make up some pre-determined distribution
    unsigned n_element=problem.mesh_pt()->nelement();
    Vector<unsigned> element_partition(n_element);
    std::string input_string;
    for (unsigned e=0;e<n_element;e++)
     {
      unsigned target_part=0;
      if ( (e<unsigned(0.25*double(n_element))) ||
           ( (e>unsigned(0.5*double(n_element))) &&
             (e<unsigned(0.75*double(n_element))) ) )
       {
        target_part=1;
       }
      element_partition[e]=target_part;
     }
    problem.distribute(element_partition,report_stats);
    // This is a validation run: use the default partition when load balancing
    problem.set_default_partition_in_load_balance();
   }
  //Output initial mesh
  problem.doc_solution("Initial mesh");
  // Solve the problem with automatic adaptation
  problem.newton_solve(1);
  //Output solution
  problem.doc_solution("First adapted solution");
  // Prune
  problem.prune_halo_elements_and_nodes(report_stats);
  //Output solution
  problem.doc_solution("After first prune");
  // Solve the problem again with automatic adaptation
  problem.newton_solve(1);
  //Output solution
  problem.doc_solution("Second adapted solution after pruning");
  // Do load balancing
  problem.load_balance(report_stats);
  //Output solution
  problem.doc_solution("After load balancing");
  // Prune
  problem.prune_halo_elements_and_nodes(report_stats);
  //Output solution
  problem.doc_solution("After second pruning");
  // Solve the problem again with automatic adaptation
  problem.newton_solve(1);
  //Output solution
  problem.doc_solution("Third adapted solution after pruning");
  // Do a uniform refinement
  problem.refine_uniformly();
  //Output solution
  problem.doc_solution("After uniform refinement");
  // Prune
  problem.prune_halo_elements_and_nodes(report_stats);
  //Output solution
  problem.doc_solution("After third pruning");
  // Solve the problem again with automatic adaptation
  problem.newton_solve(1);
  //Output solution
  problem.doc_solution("Fourth adapted solution after pruning");
  // Do load balancing
  problem.load_balance(report_stats);
  //Output solution
  problem.doc_solution("After load balancing");
  // Solve the problem again with automatic adaptation
  problem.newton_solve(1);
  //Output solution
  problem.doc_solution("Fifth adapted solution after load balancing");
  oomph_info << "done\n";
  std::cout << "done\n";
   // Finalise MPI
 #ifdef OOMPH_HAS_MPI
   MPI_Helpers::finalize();
 #endif
 } // end_of_main
References oomph::CommandLineArgs::command_line_flag_has_been_set(), oomph::default_output_modifier, oomph::CommandLineArgs::doc_specified_flags(), e(), MergeRestartFiles::filename, oomph::oomph_info, oomph::OomphInfo::output_modifier_pt(), oomph::CommandLineArgs::parse_and_assign(), problem, Flag_definition::setup(), oomph::CommandLineArgs::specify_command_line_flag(), oomph::OomphInfo::stream_pt(), and oomph::Global_string_for_annotation::string().