MercuryDPM: checkIdx Struct Reference
checkIdx Struct Reference
Static Public Member Functions
template<typename ArrType >
static int doCheck_ (ArrType e, int flags, int dummy, std::set< uint64_t > &found, std::map< uint64_t, int > const &expected)
static int run (std::vector< int > e, int flags, int dummy, std::set< uint64_t > &found, std::map< uint64_t, int > const &expected)
template<std::size_t N>
static int run (std::array< int, N > e, int flags, int dummy, std::set< uint64_t > &found, std::map< uint64_t, int > const &expected)
Member Function Documentation
doCheck_()
template<typename ArrType > static int checkIdx::doCheck_ (ArrType e, int flags, int dummy, std::set< uint64_t > & found, std::map< uint64_t, int > const & expected) inline static
{
     // use decimal representation of value
     uint64_t value = e[0];
     for (std::size_t i = 1; i < e.size(); i++) value = value * 10 + e[i];
     // we want to make sure that we find each element
     auto it = expected.find(value);
     VERIFY((it != expected.end()));
     VERIFY_IS_EQUAL(it->second, flags);
     // we want to make sure we only have each element once;
     // set::insert returns true for the second part of the pair
     // if the element was really inserted and not already there
     auto p = found.insert(value);
     VERIFY((p.second));
     return dummy;
   }
References e(), MergeRestartFiles::found, i, p, Eigen::value, VERIFY, and VERIFY_IS_EQUAL.
Referenced by run().
run() [1/2]
template<std::size_t N> static int checkIdx::run (std::array< int, N > e, int flags, int dummy, std::set< uint64_t > & found, std::map< uint64_t, int > const & expected) inline static
{
     return doCheck_(e, flags, dummy, found, expected);
   }
References doCheck_(), e(), and MergeRestartFiles::found.
run() [2/2]
static int checkIdx::run (std::vector< int > e, int flags, int dummy, std::set< uint64_t > & found, std::map< uint64_t, int > const & expected) inline static
{
     return doCheck_(e, flags, dummy, found, expected);
   }
References doCheck_(), e(), and MergeRestartFiles::found.
The documentation for this struct was generated from the following file:
cxx11_tensor_symmetry.cpp