MercuryDPM: Eigen::internal::apply_rotation_in_the_plane_selector< Scalar, OtherScalar, SizeAtCompileTime, MinAlignment, Vectorizable > Struct Template Reference
Eigen::internal::apply_rotation_in_the_plane_selector< Scalar, OtherScalar, SizeAtCompileTime, MinAlignment, Vectorizable > Struct Template Reference
#include <Jacobi.h>
Static Public Member Functions
static EIGEN_DEVICE_FUNC void run (Scalar *x, Index incrx, Scalar *y, Index incry, Index size, OtherScalar c, OtherScalar s)
Member Function Documentation
run()
template<typename Scalar , typename OtherScalar , int SizeAtCompileTime, int MinAlignment, bool Vectorizable> static EIGEN_DEVICE_FUNC void Eigen::internal::apply_rotation_in_the_plane_selector< Scalar, OtherScalar, SizeAtCompileTime, MinAlignment, Vectorizable >::run (Scalar * x, Index incrx, Scalar * y, Index incry, Index size, OtherScalar c, OtherScalar s) inline static
{
     for (Index i = 0; i < size; ++i) {
       Scalar xi = *x;
       Scalar yi = *y;
       *x = c * xi + numext::conj(s) * yi;
       *y = -s * xi + numext::conj(c) * yi;
       x += incrx;
       y += incry;
     }
   }
References calibrate::c, conj(), i, s, size, plotDoE::x, and Eigen::internal::y.
Referenced by Eigen::internal::apply_rotation_in_the_plane(), and Eigen::internal::apply_rotation_in_the_plane_selector< Scalar, OtherScalar, SizeAtCompileTime, MinAlignment, true >::run().
The documentation for this struct was generated from the following file:
Jacobi.h