MercuryDPM: test_cast_runner< Scalar, EnableIf > Struct Template Reference
test_cast_runner< Scalar, EnableIf > Struct Template Reference
Static Public Member Functions
static void run ()
Member Function Documentation
run()
template<typename Scalar , typename EnableIf = void> static void test_cast_runner< Scalar, EnableIf >::run () inline static
                     {
     test_type_cast<Scalar, bool>();
     test_type_cast<Scalar, int8_t>();
     test_type_cast<Scalar, int16_t>();
     test_type_cast<Scalar, int32_t>();
     test_type_cast<Scalar, int64_t>();
     test_type_cast<Scalar, uint8_t>();
     test_type_cast<Scalar, uint16_t>();
     test_type_cast<Scalar, uint32_t>();
     test_type_cast<Scalar, uint64_t>();
     test_type_cast<Scalar, half>();
     test_type_cast<Scalar, bfloat16>();
     test_type_cast<Scalar, float>();
     test_type_cast<Scalar, double>();
     test_type_cast<Scalar, std::complex<float>>();
     test_type_cast<Scalar, std::complex<double>>();
   }
Referenced by test_cast_runner< SrcPacket, TgtScalar, TgtPacket, true, true >::run(), packetmath_pcast_ops_runner< Scalar, Packet, EnableIf >::run(), and packetmath_pcast_ops_runner< Scalar, Packet, std::enable_if_t< NumTraits< Scalar >::IsComplex > >::run().
The documentation for this struct was generated from the following files:
packetmath.cpp
cxx11_tensor_casts.cpp