MercuryDPM: Eigen::internal::householder_qr_inplace_blocked< MatrixQR, HCoeffs, MatrixQRScalar, InnerStrideIsOne > Struct Template Reference
Eigen::internal::householder_qr_inplace_blocked< MatrixQR, HCoeffs, MatrixQRScalar, InnerStrideIsOne > Struct Template Reference
#include <HouseholderQR.h>
Static Public Member Functions
static void run (MatrixQR &mat, HCoeffs &hCoeffs, Index maxBlockSize=32, typename MatrixQR::Scalar *tempData=0)
Detailed Description
template<typename MatrixQR, typename HCoeffs, typename MatrixQRScalar = typename MatrixQR::Scalar, bool InnerStrideIsOne = (MatrixQR::InnerStrideAtCompileTime == 1 && HCoeffs::InnerStrideAtCompileTime == 1)>
struct Eigen::internal::householder_qr_inplace_blocked< MatrixQR, HCoeffs, MatrixQRScalar, InnerStrideIsOne >
Member Function Documentation
run()
template<typename MatrixQR , typename HCoeffs , typename MatrixQRScalar = typename MatrixQR::Scalar, bool InnerStrideIsOne = (MatrixQR::InnerStrideAtCompileTime == 1 && HCoeffs::InnerStrideAtCompileTime == 1)> static void Eigen::internal::householder_qr_inplace_blocked< MatrixQR, HCoeffs, MatrixQRScalar, InnerStrideIsOne >::run (MatrixQR & mat, HCoeffs & hCoeffs, Index maxBlockSize = 32, typename MatrixQR::Scalar * tempData = 0) inline static
{
     typedef typename MatrixQR::Scalar Scalar;
     typedef Block<MatrixQR, Dynamic, Dynamic> BlockType;
     Index rows = mat.rows();
     Index cols = mat.cols();
     Index size = (std::min)(rows, cols);
     typedef Matrix<Scalar, Dynamic, 1, ColMajor, MatrixQR::MaxColsAtCompileTime, 1> TempType;
     TempType tempVector;
     if (tempData == 0) {
       tempVector.resize(cols);
       tempData = tempVector.data();
     }
     Index blockSize = (std::min)(maxBlockSize, size);
     Index k = 0;
     for (k = 0; k < size; k += blockSize) {
       Index bs = (std::min)(size - k, blockSize);  // actual size of the block
       Index tcols = cols - k - bs;                 // trailing columns
       Index brows = rows - k;                      // rows of the block
       // partition the matrix:
       //        A00 | A01 | A02
       // mat  = A10 | A11 | A12
       //        A20 | A21 | A22
       // and performs the qr dec of [A11^T A12^T]^T
       // and update [A21^T A22^T]^T using level 3 operations.
       // Finally, the algorithm continue on A22
       BlockType A11_21 = mat.block(k, k, brows, bs);
       Block<HCoeffs, Dynamic, 1> hCoeffsSegment = hCoeffs.segment(k, bs);
       householder_qr_inplace_unblocked(A11_21, hCoeffsSegment, tempData);
       if (tcols) {
         BlockType A21_22 = mat.block(k, k + bs, brows, tcols);
         apply_block_householder_on_the_left(A21_22, A11_21, hCoeffsSegment, false);  // false == backward
       }
     }
   }
References Eigen::internal::apply_block_householder_on_the_left(), Eigen::HouseholderQR< MatrixType_ >::cols(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::cols(), Eigen::HouseholderQR< MatrixType_ >::hCoeffs(), Eigen::internal::householder_qr_inplace_unblocked(), k, min, Eigen::PlainObjectBase< Derived >::resize(), Eigen::HouseholderQR< MatrixType_ >::rows(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::rows(), and Eigen::EigenBase< Derived >::size().
Referenced by Eigen::HouseholderQR< MatrixType_ >::computeInPlace().
The documentation for this struct was generated from the following file:
HouseholderQR.h