MercuryDPM: Eigen::internal::etor_product_packet_impl< RowMajor, UnrollingIndex, Lhs, Rhs, Packet, LoadMode > Struct Template Reference
Eigen::internal::etor_product_packet_impl< RowMajor, UnrollingIndex, Lhs, Rhs, Packet, LoadMode > Struct Template Reference
#include <ProductEvaluators.h>
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void run (Index row, Index col, const Lhs &lhs, const Rhs &rhs, Index innerDim, Packet &res)
Member Function Documentation
run()
template<int UnrollingIndex, typename Lhs , typename Rhs , typename Packet , int LoadMode> static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::etor_product_packet_impl< RowMajor, UnrollingIndex, Lhs, Rhs, Packet, LoadMode >::run (Index row, Index col, const Lhs & lhs, const Rhs & rhs, Index innerDim, Packet & res) inline static
{
     etor_product_packet_impl<RowMajor, UnrollingIndex - 1, Lhs, Rhs, Packet, LoadMode>::run(row, col, lhs, rhs,
                                                                                             innerDim, res);
     res = pmadd(pset1<Packet>(lhs.coeff(row, Index(UnrollingIndex - 1))),
                 rhs.template packet<LoadMode, Packet>(Index(UnrollingIndex - 1), col), res);
   }
References col(), Eigen::internal::pmadd(), res, row(), and run().
The documentation for this struct was generated from the following file:
ProductEvaluators.h