MercuryDPM: BatchMatMul< TensorType > Struct Template Reference
BatchMatMul< TensorType > Struct Template Reference
Public Member Functions
DSizes< DenseIndex, 3 > dimensions (const Tensor< float, 3 > &input1, const Tensor< float, 3 > &input2) const
template<typename Output , typename Device >
void eval (const Tensor< float, 3 > &input1, const Tensor< float, 3 > &input2, Output &output, const Device &device) const
DSizes< DenseIndex, 3 > dimensions (const TensorType &input1, const TensorType &input2) const
template<typename Output , typename Device >
void eval (const TensorType &input1, const TensorType &input2, Output &output, const Device &device) const
Member Function Documentation
dimensions() [1/2]
template<typename TensorType > DSizes<DenseIndex, 3> BatchMatMul< TensorType >::dimensions (const Tensor< float, 3 > & input1, const Tensor< float, 3 > & input2) const inline
{
     DSizes<DenseIndex, 3> result;
     result[0] = input1.dimension(0);
     result[1] = input2.dimension(1);
     result[2] = input2.dimension(2);
     return result;
   }
References Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::dimension().
dimensions() [2/2]
template<typename TensorType > DSizes<DenseIndex, 3> BatchMatMul< TensorType >::dimensions (const TensorType & input1, const TensorType & input2) const inline
{
     DSizes<DenseIndex, 3> result;
     result[0] = input1.dimension(0);
     result[1] = input2.dimension(1);
     result[2] = input2.dimension(2);
     return result;
   }
eval() [1/2]
template<typename TensorType > template<typename Output , typename Device > void BatchMatMul< TensorType >::eval (const Tensor< float, 3 > & input1, const Tensor< float, 3 > & input2, Output & output, const Device & device) const inline
{
     typedef Tensor<float, 3>::DimensionPair DimPair;
     array<DimPair, 1> dims;
     dims[0] = DimPair(1, 0);
     for (int i = 0; i < output.dimension(2); ++i) {
       output.template chip<2>(i).device(device) = input1.chip<2>(i).contract(input2.chip<2>(i), dims);
     }
   }
References Eigen::TensorBase< Derived, AccessLevel >::chip(), i, and output().
eval() [2/2]
template<typename TensorType > template<typename Output , typename Device > void BatchMatMul< TensorType >::eval (const TensorType & input1, const TensorType & input2, Output & output, const Device & device) const inline
{
     typedef typename TensorType::DimensionPair DimPair;
     array<DimPair, 1> dims;
     dims[0] = DimPair(1, 0);
     for (int64_t i = 0; i < output.dimension(2); ++i) {
       output.template chip<2>(i).device(device) = input1.template chip<2>(i).contract(input2.template chip<2>(i), dims);
     }
   }
References i, and output().
The documentation for this struct was generated from the following files:
cxx11_tensor_custom_op.cpp
cxx11_tensor_custom_op_sycl.cpp