MercuryDPM: Eigen::internal::TensorTernaryExprBlock< BlockFactory, Arg1TensorBlock, Arg2TensorBlock, Arg3TensorBlock > Class Template Reference
Eigen::internal::TensorTernaryExprBlock< BlockFactory, Arg1TensorBlock, Arg2TensorBlock, Arg3TensorBlock > Class Template Reference
#include <TensorBlock.h>
Public Types
typedef std::conditional_t< NoArgBlockAccess, void, typename BlockFactory::template XprType< Arg1XprType, Arg2XprType, Arg3XprType >::type > XprType
typedef XprScalar< XprType >::type Scalar
Public Member Functions
TensorTernaryExprBlock (const Arg1TensorBlock &arg1_block, const Arg2TensorBlock &arg2_block, const Arg3TensorBlock &arg3_block, const BlockFactory &factory)
TensorBlockKind kind () const
XprType expr () const
const Scalar * data () const
void cleanup ()
Private Types
typedef Arg1TensorBlock::XprType Arg1XprType
typedef Arg2TensorBlock::XprType Arg2XprType
typedef Arg3TensorBlock::XprType Arg3XprType
Private Attributes
Arg1TensorBlock m_arg1_block
Arg2TensorBlock m_arg2_block
Arg3TensorBlock m_arg3_block
BlockFactory m_factory
Static Private Attributes
static constexpr bool NoArgBlockAccess
Member Typedef Documentation
Arg1XprType
template<typename BlockFactory , typename Arg1TensorBlock , typename Arg2TensorBlock , typename Arg3TensorBlock > typedef Arg1TensorBlock::XprType Eigen::internal::TensorTernaryExprBlock< BlockFactory, Arg1TensorBlock, Arg2TensorBlock, Arg3TensorBlock >::Arg1XprType private
Arg2XprType
template<typename BlockFactory , typename Arg1TensorBlock , typename Arg2TensorBlock , typename Arg3TensorBlock > typedef Arg2TensorBlock::XprType Eigen::internal::TensorTernaryExprBlock< BlockFactory, Arg1TensorBlock, Arg2TensorBlock, Arg3TensorBlock >::Arg2XprType private
Arg3XprType
template<typename BlockFactory , typename Arg1TensorBlock , typename Arg2TensorBlock , typename Arg3TensorBlock > typedef Arg3TensorBlock::XprType Eigen::internal::TensorTernaryExprBlock< BlockFactory, Arg1TensorBlock, Arg2TensorBlock, Arg3TensorBlock >::Arg3XprType private
Scalar
template<typename BlockFactory , typename Arg1TensorBlock , typename Arg2TensorBlock , typename Arg3TensorBlock > typedef XprScalar<XprType>::type Eigen::internal::TensorTernaryExprBlock< BlockFactory, Arg1TensorBlock, Arg2TensorBlock, Arg3TensorBlock >::Scalar
XprType
template<typename BlockFactory , typename Arg1TensorBlock , typename Arg2TensorBlock , typename Arg3TensorBlock > typedef std::conditional_t<NoArgBlockAccess, void, typename BlockFactory::template XprType<Arg1XprType, Arg2XprType, Arg3XprType>::type> Eigen::internal::TensorTernaryExprBlock< BlockFactory, Arg1TensorBlock, Arg2TensorBlock, Arg3TensorBlock >::XprType
Constructor & Destructor Documentation
TensorTernaryExprBlock()
template<typename BlockFactory , typename Arg1TensorBlock , typename Arg2TensorBlock , typename Arg3TensorBlock > Eigen::internal::TensorTernaryExprBlock< BlockFactory, Arg1TensorBlock, Arg2TensorBlock, Arg3TensorBlock >::TensorTernaryExprBlock (const Arg1TensorBlock & arg1_block, const Arg2TensorBlock & arg2_block, const Arg3TensorBlock & arg3_block, const BlockFactory & factory) inline
       : m_arg1_block(arg1_block), m_arg2_block(arg2_block), m_arg3_block(arg3_block), m_factory(factory) {}
Member Function Documentation
cleanup()
template<typename BlockFactory , typename Arg1TensorBlock , typename Arg2TensorBlock , typename Arg3TensorBlock > void Eigen::internal::TensorTernaryExprBlock< BlockFactory, Arg1TensorBlock, Arg2TensorBlock, Arg3TensorBlock >::cleanup () inline
                  {
     m_arg1_block.cleanup();
     m_arg2_block.cleanup();
     m_arg3_block.cleanup();
   }
References Eigen::internal::TensorTernaryExprBlock< BlockFactory, Arg1TensorBlock, Arg2TensorBlock, Arg3TensorBlock >::m_arg1_block, Eigen::internal::TensorTernaryExprBlock< BlockFactory, Arg1TensorBlock, Arg2TensorBlock, Arg3TensorBlock >::m_arg2_block, and Eigen::internal::TensorTernaryExprBlock< BlockFactory, Arg1TensorBlock, Arg2TensorBlock, Arg3TensorBlock >::m_arg3_block.
Referenced by framework.Frame::__init__().
data()
template<typename BlockFactory , typename Arg1TensorBlock , typename Arg2TensorBlock , typename Arg3TensorBlock > const Scalar* Eigen::internal::TensorTernaryExprBlock< BlockFactory, Arg1TensorBlock, Arg2TensorBlock, Arg3TensorBlock >::data () const inline
 { return NULL; }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
expr()
template<typename BlockFactory , typename Arg1TensorBlock , typename Arg2TensorBlock , typename Arg3TensorBlock > XprType Eigen::internal::TensorTernaryExprBlock< BlockFactory, Arg1TensorBlock, Arg2TensorBlock, Arg3TensorBlock >::expr () const inline
 { return m_factory.expr(m_arg1_block.expr(), m_arg2_block.expr(), m_arg3_block.expr()); }
References Eigen::internal::TensorTernaryExprBlock< BlockFactory, Arg1TensorBlock, Arg2TensorBlock, Arg3TensorBlock >::m_arg1_block, Eigen::internal::TensorTernaryExprBlock< BlockFactory, Arg1TensorBlock, Arg2TensorBlock, Arg3TensorBlock >::m_arg2_block, Eigen::internal::TensorTernaryExprBlock< BlockFactory, Arg1TensorBlock, Arg2TensorBlock, Arg3TensorBlock >::m_arg3_block, and Eigen::internal::TensorTernaryExprBlock< BlockFactory, Arg1TensorBlock, Arg2TensorBlock, Arg3TensorBlock >::m_factory.
kind()
template<typename BlockFactory , typename Arg1TensorBlock , typename Arg2TensorBlock , typename Arg3TensorBlock > TensorBlockKind Eigen::internal::TensorTernaryExprBlock< BlockFactory, Arg1TensorBlock, Arg2TensorBlock, Arg3TensorBlock >::kind () const inline
 { return internal::TensorBlockKind::kExpr; }
References Eigen::internal::kExpr.
Member Data Documentation
m_arg1_block
template<typename BlockFactory , typename Arg1TensorBlock , typename Arg2TensorBlock , typename Arg3TensorBlock > Arg1TensorBlock Eigen::internal::TensorTernaryExprBlock< BlockFactory, Arg1TensorBlock, Arg2TensorBlock, Arg3TensorBlock >::m_arg1_block private
Referenced by Eigen::internal::TensorTernaryExprBlock< BlockFactory, Arg1TensorBlock, Arg2TensorBlock, Arg3TensorBlock >::cleanup(), and Eigen::internal::TensorTernaryExprBlock< BlockFactory, Arg1TensorBlock, Arg2TensorBlock, Arg3TensorBlock >::expr().
m_arg2_block
template<typename BlockFactory , typename Arg1TensorBlock , typename Arg2TensorBlock , typename Arg3TensorBlock > Arg2TensorBlock Eigen::internal::TensorTernaryExprBlock< BlockFactory, Arg1TensorBlock, Arg2TensorBlock, Arg3TensorBlock >::m_arg2_block private
Referenced by Eigen::internal::TensorTernaryExprBlock< BlockFactory, Arg1TensorBlock, Arg2TensorBlock, Arg3TensorBlock >::cleanup(), and Eigen::internal::TensorTernaryExprBlock< BlockFactory, Arg1TensorBlock, Arg2TensorBlock, Arg3TensorBlock >::expr().
m_arg3_block
template<typename BlockFactory , typename Arg1TensorBlock , typename Arg2TensorBlock , typename Arg3TensorBlock > Arg3TensorBlock Eigen::internal::TensorTernaryExprBlock< BlockFactory, Arg1TensorBlock, Arg2TensorBlock, Arg3TensorBlock >::m_arg3_block private
Referenced by Eigen::internal::TensorTernaryExprBlock< BlockFactory, Arg1TensorBlock, Arg2TensorBlock, Arg3TensorBlock >::cleanup(), and Eigen::internal::TensorTernaryExprBlock< BlockFactory, Arg1TensorBlock, Arg2TensorBlock, Arg3TensorBlock >::expr().
m_factory
template<typename BlockFactory , typename Arg1TensorBlock , typename Arg2TensorBlock , typename Arg3TensorBlock > BlockFactory Eigen::internal::TensorTernaryExprBlock< BlockFactory, Arg1TensorBlock, Arg2TensorBlock, Arg3TensorBlock >::m_factory private
Referenced by Eigen::internal::TensorTernaryExprBlock< BlockFactory, Arg1TensorBlock, Arg2TensorBlock, Arg3TensorBlock >::expr().
NoArgBlockAccess
template<typename BlockFactory , typename Arg1TensorBlock , typename Arg2TensorBlock , typename Arg3TensorBlock > constexpr bool Eigen::internal::TensorTernaryExprBlock< BlockFactory, Arg1TensorBlock, Arg2TensorBlock, Arg3TensorBlock >::NoArgBlockAccess static constexpr private
Initial value:
= internal::is_void<Arg1XprType>::value ||
                                           internal::is_void<Arg2XprType>::value ||
                                           internal::is_void<Arg3XprType>::value
The documentation for this class was generated from the following file:
TensorBlock.h