MercuryDPM: oomph::SarahBL Namespace Reference
oomph::SarahBL Namespace Reference
Sarah's boundary layer solution for flow in oscillating ring.
Functions
double Diss_sarah (double rho, double zeta, double t)
double Kin_energy_sarah (double t)
double P_sarah (double rho, double zeta, double t)
double Total_Diss_lead_sarah (double t)
double Total_Diss_sarah (double t)
double U_sarah (double rho, double zeta, double t)
double V_sarah (double rho, double zeta, double t)
double X_sarah (double rho, double zeta, double t)
double Y_sarah (double rho, double zeta, double t)
void buckled_ring_residual (const Vector< double > &params, const Vector< double > &unknowns, Vector< double > &residuals)
Residual function for buckled ring.
void exact_soln (const double &time, const Vector< double > &x, Vector< double > &soln)
Exact solution: x,y,u,v,p.
void full_exact_soln (const double &time, const Vector< double > &x, Vector< double > &soln)
Full exact solution: x,y,u,v,p,du/dt,dv/dt,diss.
Variables
double epsilon
double alpha
double A
double Omega
double N
Detailed Description
Sarah's boundary layer solution for flow in oscillating ring.
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Function Documentation
buckled_ring_residual()
void oomph::SarahBL::buckled_ring_residual (const Vector< double > & params, const Vector< double > & unknowns, Vector< double > & residuals)
Residual function for buckled ring.
 {
   // Parameters
   double t=params[0];
   double xx=params[1];
   double yy=params[2];
   // Unknowns
   double rho=unknowns[0];
   double zeta=unknowns[1];
   // Residuals
   residuals[0]=X_sarah(rho,zeta,t)-xx;
   residuals[1]=Y_sarah(rho,zeta,t)-yy;
  }
References Particles2023AnalysisHung::params, plotPSD::t, X_sarah(), Y_sarah(), and Eigen::zeta().
Referenced by exact_soln(), and full_exact_soln().
Diss_sarah()
double oomph::SarahBL::Diss_sarah (double rho, double zeta, double t)
 {
   double t1;
   double t10;
   double t11;
   double t13;
   double t14;
   double t19;
   double t2;
   double t20;
   double t21;
   double t22;
   double t25;
   double t26;
   double t39;
   double t43;
   double t5;
   double t6;
   double t8;
   {
     t1 = alpha*alpha;
     t2 = epsilon*epsilon;
     t5 = sin(N*zeta);
     t6 = t5*t5;
     t8 = Omega*Omega;
     t10 = 1.0+A;
     t11 = t10*t10;
     t13 = sqrt(2.0);
     t14 = sqrt(Omega);
     t19 = t13*t14*alpha*(1.0-rho)/2.0;
     t20 = exp(-t19);
     t21 = t20*t20;
     t22 = Omega*t;
     t25 = cos(-t19+t22+0.3141592653589793E1/4.0);
     t26 = t25*t25;
     t39 = cos(-t19+t22);
     t43 = cos(t22);
     return(t1*t2*t6*t8*Omega*t11*t21*t26+4.0*alpha*t2*t6*t14*Omega*t10*t20*t25*
 (N-1.0)*(Omega*t10*t20*t39/2.0-Omega*t43));
   }
 }
References A, alpha, cos(), epsilon, Eigen::bfloat16_impl::exp(), N, Omega, sin(), sqrt(), plotPSD::t, and Eigen::zeta().
Referenced by full_exact_soln().
exact_soln()
void oomph::SarahBL::exact_soln (const double & time, const Vector< double > & x, Vector< double > & soln)
Exact solution: x,y,u,v,p.
  {
   // Primary variables only
   soln.resize(3);
   // Get rho and zeta with black-box Newton method:
   // Parameters: time, x, y
   Vector<double> params(3);
   params[0]=time;
   params[1]=x[0];
   params[2]=x[1];
   // Unknowns rho, zeta
   Vector<double> unknowns(2);
   // Initial guess:
   double rho=sqrt(x[0]*x[0]+x[1]*x[1]);
   double zeta=0.5*MathematicalConstants::Pi;
   if (std::abs(x[0])>1e-4) zeta=atan(x[1]/x[0]);
   // Copy across
   unknowns[0]=rho;
   unknowns[1]=zeta;
   // Call Newton solver
   BlackBoxFDNewtonSolver::black_box_fd_newton_solve(
    buckled_ring_residual,params,unknowns);
   // Extract rho, zeta
   // Copy across
   rho=unknowns[0];
   zeta=unknowns[1];
   // Double check the position
   double dx=X_sarah(rho,zeta,time)-x[0];
   double dy=Y_sarah(rho,zeta,time)-x[1];
   double error=sqrt(dx*dx+dy*dy);
   if (error>1.0e-6)
    {
     std::cout << "Trafo error " << error << std::endl;
     //assert(false);
    }
   // Velocities
   soln[0]=U_sarah(rho,zeta,time);
   soln[1]=V_sarah(rho,zeta,time);
   // Pressure on viscous scale
   soln[2]=P_sarah(rho,zeta,time)*(alpha*alpha);
  }
References abs(), alpha, Eigen::bfloat16_impl::atan(), oomph::BlackBoxFDNewtonSolver::black_box_fd_newton_solve(), buckled_ring_residual(), e(), calibrate::error, P_sarah(), Particles2023AnalysisHung::params, oomph::MathematicalConstants::Pi, sqrt(), U_sarah(), V_sarah(), plotDoE::x, X_sarah(), Y_sarah(), and Eigen::zeta().
full_exact_soln()
void oomph::SarahBL::full_exact_soln (const double & time, const Vector< double > & x, Vector< double > & soln)
Full exact solution: x,y,u,v,p,du/dt,dv/dt,diss.
  {
   // Full solution
   soln.resize(6);
   // Get rho and zeta with black-box Newton method:
   // Parameters: time, x, y
   Vector<double> params(3);
   params[0]=time;
   params[1]=x[0];
   params[2]=x[1];
   // Unknowns rho, zeta
   Vector<double> unknowns(2);
   // Initial guess:
   double rho=sqrt(x[0]*x[0]+x[1]*x[1]);
   double zeta=0.5*MathematicalConstants::Pi;
   if (std::abs(x[0])>1e-4) zeta=atan(x[1]/x[0]);
   // Copy across
   unknowns[0]=rho;
   unknowns[1]=zeta;
   // Call Newton solver
   BlackBoxFDNewtonSolver::black_box_fd_newton_solve(
    buckled_ring_residual,params,unknowns);
   // Extract rho, zeta
   // Copy across
   rho=unknowns[0];
   zeta=unknowns[1];
   // Double check the position
   double dx=X_sarah(rho,zeta,time)-x[0];
   double dy=Y_sarah(rho,zeta,time)-x[1];
   double error=sqrt(dx*dx+dy*dy);
   if (error>1.0e-6)
    {
     std::cout << "Trafo error " << error << std::endl;
     //assert(false);
    }
   // Velocities
   soln[0]=U_sarah(rho,zeta,time);
   soln[1]=V_sarah(rho,zeta,time);
   // Pressure on viscous scale
   soln[2]=P_sarah(rho,zeta,time)*(alpha*alpha);
   // du/dt dv/dt not coded up yet...
   soln[3]=0.0; //DUDT(xx,y,time);
   soln[4]=0.0; //DVDT(xx,y,time);
   if (rho<1.0e-6)
    {
     rho=1e-6;
    }
   soln[5]=Diss_sarah(rho,zeta,time);
  }
References abs(), alpha, Eigen::bfloat16_impl::atan(), oomph::BlackBoxFDNewtonSolver::black_box_fd_newton_solve(), buckled_ring_residual(), Diss_sarah(), e(), calibrate::error, P_sarah(), Particles2023AnalysisHung::params, oomph::MathematicalConstants::Pi, sqrt(), U_sarah(), V_sarah(), plotDoE::x, X_sarah(), Y_sarah(), and Eigen::zeta().
Kin_energy_sarah()
double oomph::SarahBL::Kin_energy_sarah (double t)
 {
   double t1;
   double t11;
   double t13;
   double t16;
   double t18;
   double t2;
   double t20;
   double t27;
   double t28;
   double t31;
   double t33;
   double t5;
   double t6;
   double t7;
   {
     t1 = epsilon*epsilon;
     t2 = Omega*Omega;
     t5 = Omega*t;
     t6 = cos(t5);
     t7 = t6*t6;
     t11 = 1/alpha;
     t13 = sqrt(Omega);
     t16 = 1.0+A;
     t18 = 0.3141592653589793E1/4.0;
     t20 = sin(t5+t18);
     t27 = t16*t16;
     t28 = 1/t13;
     t31 = sin(2.0*t5+t18);
     t33 = sqrt(2.0);
     return(t1*(0.3141592653589793E1*t2/N*t7/2.0+t11*0.3141592653589793E1*t13*
 Omega*t16*t6*t20)+0.3141592653589793E1*t1*t2*t11*(t27*(t28*t31/4.0+t33*t28/4.0
 )-2.0*t28*t16*t6*t20)/2.0);
   }
 }
References A, alpha, cos(), epsilon, N, Omega, sin(), sqrt(), and plotPSD::t.
P_sarah()
double oomph::SarahBL::P_sarah (double rho, double zeta, double t)
 {
   double t1;
   double t12;
   double t19;
   double t4;
   double t6;
   double t8;
   double t9;
   {
     t1 = Omega*Omega;
     t4 = pow(rho,1.0*N);
     t6 = cos(N*zeta);
     t8 = Omega*t;
     t9 = sin(t8);
     t12 = sqrt(Omega);
     t19 = cos(t8+0.3141592653589793E1/4.0);
     return(epsilon*(t1/N*t4*t6*t9-t12*Omega*(1.0+A)*t4*t6*t19/alpha));
   }
 }
References alpha, cos(), epsilon, N, Omega, Eigen::bfloat16_impl::pow(), sin(), sqrt(), plotPSD::t, and Eigen::zeta().
Referenced by exact_soln(), and full_exact_soln().
Total_Diss_lead_sarah()
double oomph::SarahBL::Total_Diss_lead_sarah (double t)
 {
   double t1;
   double t10;
   double t11;
   double t12;
   double t13;
   double t16;
   double t4;
   double t5;
   double t6;
   {
     t1 = epsilon*epsilon;
     t4 = sqrt(2.0);
     t5 = Omega*Omega;
     t6 = sqrt(Omega);
     t10 = pow(1.0+A,2.0);
     t11 = Omega*t;
     t12 = sin(t11);
     t13 = cos(t11);
     t16 = t13*t13;
     return(-alpha*t1*0.3141592653589793E1*t4*t6*t5*t10*(-1.0+2.0*t12*t13-2.0*
 t16)/8.0);
   }
 }
References alpha, cos(), epsilon, Omega, Eigen::bfloat16_impl::pow(), sin(), sqrt(), and plotPSD::t.
Total_Diss_sarah()
double oomph::SarahBL::Total_Diss_sarah (double t)
 {
   double t1;
   double t14;
   double t15;
   double t18;
   double t19;
   double t2;
   double t20;
   double t4;
   double t6;
   double t7;
   double t8;
   {
     t1 = Omega*Omega;
     t2 = 0.3141592653589793E1*t1;
     t4 = epsilon*epsilon;
     t6 = Omega*t;
     t7 = cos(t6);
     t8 = t7*t7;
     t14 = sqrt(2.0);
     t15 = sqrt(Omega);
     t18 = 1.0+A;
     t19 = t18*t18;
     t20 = sin(t6);
     return(4.0*t2*(N-1.0)*t4*t8-alpha*t4*0.3141592653589793E1*t14*t15*t1*t19*(
 -1.0+2.0*t20*t7-2.0*t8)/8.0+t4*t18*t2*(-10.0*A*t8-A+8.0*A*N*t8+22.0*t8-1.0-24.0
 *N*t8)/8.0);
   }
 }
References A, alpha, cos(), epsilon, N, Omega, sin(), sqrt(), and plotPSD::t.
U_sarah()
double oomph::SarahBL::U_sarah (double rho, double zeta, double t)
 {
   double t1;
   double t12;
   double t14;
   double t19;
   double t21;
   double t22;
   double t23;
   double t25;
   double t3;
   double t35;
   double t4;
   double t41;
   double t43;
   double t46;
   double t47;
   double t49;
   double t5;
   double t52;
   double t55;
   double t57;
   double t59;
   double t6;
   double t62;
   double t64;
   double t8;
   double t87;
   double t89;
   double t9;
   {
     t1 = cos(zeta);
     t3 = N-1.0;
     t4 = pow(rho,1.0*t3);
     t5 = N*zeta;
     t6 = cos(t5);
     t8 = Omega*t;
     t9 = cos(t8);
     t12 = sin(zeta);
     t14 = sin(t5);
     t19 = sqrt(Omega);
     t21 = 1.0+A;
     t22 = t21*t4;
     t23 = 0.3141592653589793E1/4.0;
     t25 = sin(t8+t23);
     t35 = 1/alpha;
     t41 = sqrt(2.0);
     t43 = 1.0-rho;
     t46 = t41*t19*alpha*t43/2.0;
     t47 = exp(-t46);
     t49 = cos(-t46+t8);
     t52 = Omega*t9;
     t55 = N*t19;
     t57 = sin(-t46+t8+t23);
     t59 = t47*t57-t25;
     t62 = Omega*alpha;
     t64 = -t43*t3;
     t87 = t9*(1.0+t64);
     t89 = N*t35;
     return(epsilon*(t1*Omega*t4*t6*t9+t12*Omega*t4*t14*t9+(t1*N*t19*t22*t6*t25+
 t12*N*t19*t22*t14*t25)*t35)-epsilon*t12*(t14*(Omega*t21*t47*t49-t52)+t14*(t55*
 t21*t59-t62*t64*t9)*t35)+epsilon*t1*(t52*t6+t6*(-t55*t21*t59-t62*t43*t3*t9)*t35
 )-(-t12*(-Omega*t14*t87-t89*t19*t21*t14*t25)+t1*(Omega*t6*t87+t89*t6*t19*t21*
 t25))*epsilon);
   }
 }
References A, alpha, cos(), epsilon, Eigen::bfloat16_impl::exp(), N, Omega, Eigen::bfloat16_impl::pow(), sin(), sqrt(), plotPSD::t, and Eigen::zeta().
Referenced by exact_soln(), and full_exact_soln().
V_sarah()
double oomph::SarahBL::V_sarah (double rho, double zeta, double t)
 {
   double t1;
   double t12;
   double t14;
   double t19;
   double t21;
   double t22;
   double t23;
   double t25;
   double t3;
   double t35;
   double t4;
   double t41;
   double t43;
   double t46;
   double t47;
   double t49;
   double t5;
   double t52;
   double t55;
   double t57;
   double t59;
   double t6;
   double t62;
   double t64;
   double t8;
   double t87;
   double t89;
   double t9;
   {
     t1 = sin(zeta);
     t3 = N-1.0;
     t4 = pow(rho,1.0*t3);
     t5 = N*zeta;
     t6 = cos(t5);
     t8 = Omega*t;
     t9 = cos(t8);
     t12 = cos(zeta);
     t14 = sin(t5);
     t19 = sqrt(Omega);
     t21 = 1.0+A;
     t22 = t21*t4;
     t23 = 0.3141592653589793E1/4.0;
     t25 = sin(t8+t23);
     t35 = 1/alpha;
     t41 = sqrt(2.0);
     t43 = 1.0-rho;
     t46 = t41*t19*alpha*t43/2.0;
     t47 = exp(-t46);
     t49 = cos(-t46+t8);
     t52 = Omega*t9;
     t55 = N*t19;
     t57 = sin(-t46+t8+t23);
     t59 = t47*t57-t25;
     t62 = Omega*alpha;
     t64 = -t43*t3;
     t87 = t9*(1.0+t64);
     t89 = N*t35;
     return(epsilon*(t1*Omega*t4*t6*t9-t12*Omega*t4*t14*t9+(t1*N*t19*t22*t6*t25-
 t12*N*t19*t22*t14*t25)*t35)+epsilon*t12*(t14*(Omega*t21*t47*t49-t52)+t14*(t55*
 t21*t59-t62*t64*t9)*t35)+epsilon*t1*(t52*t6+t6*(-t55*t21*t59-t62*t43*t3*t9)*t35
 )-(t12*(-Omega*t14*t87-t89*t19*t21*t14*t25)+t1*(Omega*t6*t87+t89*t6*t19*t21*t25
 ))*epsilon);
   }
 }
References A, alpha, cos(), epsilon, Eigen::bfloat16_impl::exp(), N, Omega, Eigen::bfloat16_impl::pow(), sin(), sqrt(), plotPSD::t, and Eigen::zeta().
Referenced by exact_soln(), and full_exact_soln().
X_sarah()
double oomph::SarahBL::X_sarah (double rho, double zeta, double t)
 {
   double t1;
   double t10;
   double t3;
   double t5;
   double t6;
   double t8;
   {
     t1 = cos(zeta);
     t3 = sin(Omega*t);
     t5 = N*zeta;
     t6 = cos(t5);
     t8 = sin(t5);
     t10 = sin(zeta);
     return(rho*(t1+epsilon*t3*(t6*t1-A*t8*t10)));
   }
 }
References cos(), epsilon, N, Omega, sin(), plotPSD::t, and Eigen::zeta().
Referenced by buckled_ring_residual(), exact_soln(), and full_exact_soln().
Y_sarah()
double oomph::SarahBL::Y_sarah (double rho, double zeta, double t)
 {
   double t1;
   double t10;
   double t3;
   double t5;
   double t6;
   double t8;
   {
     t1 = sin(zeta);
     t3 = sin(Omega*t);
     t5 = N*zeta;
     t6 = cos(t5);
     t8 = sin(t5);
     t10 = cos(zeta);
     return(rho*(t1+epsilon*t3*(t6*t1+A*t8*t10)));
   }
 }
References cos(), epsilon, N, Omega, sin(), plotPSD::t, and Eigen::zeta().
Referenced by buckled_ring_residual(), exact_soln(), and full_exact_soln().
Variable Documentation
A
double oomph::SarahBL::A
Referenced by Diss_sarah(), Kin_energy_sarah(), Total_Diss_sarah(), U_sarah(), and V_sarah().
alpha
double oomph::SarahBL::alpha
Referenced by Diss_sarah(), exact_soln(), full_exact_soln(), Kin_energy_sarah(), P_sarah(), Total_Diss_lead_sarah(), Total_Diss_sarah(), U_sarah(), and V_sarah().
epsilon
double oomph::SarahBL::epsilon
Referenced by InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::actions_before_implicit_timestep(), oomph::Problem::adaptive_unsteady_newton_solve(), oomph::Problem::add_eigenvector_to_dofs(), TriangleMeshWall::addToMesh(), areNotApprox(), array_complex(), array_real(), array_special_functions(), Eigen::internal::bicgstab(), Eigen::internal::cephes_helper< float >::big(), Eigen::internal::cephes_helper< double >::big(), Eigen::internal::cephes_helper< double >::biginv(), bug79(), oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_fitting_parameters_of_cubic(), oomph::CassonTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_fitting_parameters_of_cubic(), oomph::SiskoTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_zero_shear_viscosity(), oomph::CassonTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_zero_shear_viscosity(), oomph::Mesh::check_for_repeated_nodes(), check_singular_cases(), Eigen::internal::chkder(), Eigen::PolynomialSolver< Scalar_, Deg_ >::compute(), Eigen::JacobiSVD< MatrixType_, Options_ >::compute_impl(), Eigen::internal::computeFromTridiagonal_impl(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::computeInPlace(), Eigen::BDCSVD< MatrixType_, Options_ >::deflation(), InterfaceProblem< ELEMENT, TIMESTEPPER >::deform_free_surface(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::deform_interface(), TwoLayerInterfaceProblem< ELEMENT >::deform_interface(), Diss_sarah(), Eigen::EigenSolver< MatrixType_ >::doComputeEigenvectors(), Eigen::ComplexEigenSolver< MatrixType_ >::doComputeEigenvectors(), Eigen::internal::dogleg(), oomph::Problem::doubly_adaptive_unsteady_newton_solve(), oomph::Problem::doubly_adaptive_unsteady_newton_solve_helper(), EIGEN_DECLARE_TEST(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::EIGEN_STATIC_ASSERT(), Eigen::EigenSolver< MatrixType_ >::eigenvectors(), Eigen::NumTraits< std::complex< Real_ > >::epsilon(), Eigen::NumTraits< Array< Scalar, Rows, Cols, Options, MaxRows, MaxCols > >::epsilon(), Eigen::internal::fdjac1(), NurbsSurface::getDistance(), RNG::getNormalVariate(), Eigen::internal::idrs(), Eigen::IterativeSolverBase< Derived >::init(), Eigen::RealSchur< MatrixType_ >::initFrancisQRStep(), Eigen::internal::AmbiVector< Scalar_, StorageIndex_ >::Iterator::Iterator(), Kin_energy_sarah(), oomph::FSIHermiteBeamElement::locate_zeta(), Eigen::internal::cephes_helper< float >::machep(), Eigen::internal::cephes_helper< double >::machep(), main(), P_sarah(), packetmath_real(), HertzianBSHPInteractionTwoParticleElasticCollision::padeCoefficientOfRestitution(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::prune(), Eigen::SparseVector< Scalar_, Options_, StorageIndex_ >::prune(), Eigen::SparseMatrixBase< Derived >::pruned(), Eigen::EigenSolver< MatrixType_ >::pseudoEigenvalueMatrix(), qr(), qr_kahan_matrix(), Eigen::internal::svd_precondition_2x2_block_to_be_real< MatrixType, Options, true >::run(), run_fixed_size_test(), run_test(), RefineablePorousChannelProblem< ELEMENT >::set_boundary_conditions(), ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::set_boundary_conditions(), DDConvectionProblem< NST_ELEMENT, AD_ELEMENT >::set_boundary_conditions(), RefineableDDConvectionProblem< NST_ELEMENT, AD_ELEMENT >::set_boundary_conditions(), SuperQuadricParticle::setBoundingRadius(), Eigen::QuaternionBase< Derived >::slerp(), Eigen::MatrixBase< Derived >::sparseView(), svd_inf_nan(), svd_least_square(), test_3d(), test_conversion(), test_nextafter(), test_numeric_limits(), test_numtraits(), test_resize(), test_simple_assign(), test_sum_accuracy(), test_tensor_epsilon(), testNistBoxBOD(), testNistChwirut2(), testNistMGH17(), testNistRat43(), testNistThurber(), TetmeshPoissonProblem< ELEMENT >::TetmeshPoissonProblem(), Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::threshold(), Eigen::ColPivHouseholderQR< MatrixType_, PermutationIndex_ >::threshold(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::threshold(), Eigen::SVDBase< Derived >::threshold(), Total_Diss_lead_sarah(), Total_Diss_sarah(), U_sarah(), InterfaceProblem< ELEMENT, TIMESTEPPER >::unsteady_run(), ElasticInterfaceProblem< ELEMENT, TIMESTEPPER >::unsteady_run(), V_sarah(), Wind_fct_pt(), X_sarah(), and Y_sarah().
N
double oomph::SarahBL::N
Referenced by Diss_sarah(), Kin_energy_sarah(), P_sarah(), Total_Diss_sarah(), U_sarah(), V_sarah(), X_sarah(), and Y_sarah().
Omega
double oomph::SarahBL::Omega
Referenced by oomph::ComplexDampedJacobi< MATRIX >::complex_solve_helper(), oomph::deriv_functions::DampedOscillation::DampedOscillation(), oomph::deriv_functions::DampedOscillation::derivative(), Diss_sarah(), FreeSurfaceRotationProblem< ELEMENT >::FreeSurfaceRotationProblem(), Kin_energy_sarah(), oomph::deriv_functions::DampedOscillation::operator()(), P_sarah(), RefineableRotatingCylinderProblem< ELEMENT >::set_boundary_conditions(), oomph::DampedJacobi< MATRIX >::solve_helper(), Total_Diss_lead_sarah(), Total_Diss_sarah(), U_sarah(), V_sarah(), X_sarah(), and Y_sarah().