MercuryDPM: Eigen::internal::inner_product_impl< Evaluator, true > Struct Template Reference
Eigen::internal::inner_product_impl< Evaluator, true > Struct Template Reference
#include <InnerProduct.h>
Public Types
using UnsignedIndex = std::make_unsigned_t< Index >
using Scalar = typename Evaluator::Scalar
using Packet = typename Evaluator::Packet
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar run (const Evaluator &eval)
Static Public Attributes
static constexpr int PacketSize = unpacket_traits<Packet>::size
Member Typedef Documentation
Packet
template<typename Evaluator > using Eigen::internal::inner_product_impl< Evaluator, true >::Packet = typename Evaluator::Packet
Scalar
template<typename Evaluator > using Eigen::internal::inner_product_impl< Evaluator, true >::Scalar = typename Evaluator::Scalar
UnsignedIndex
template<typename Evaluator > using Eigen::internal::inner_product_impl< Evaluator, true >::UnsignedIndex = std::make_unsigned_t<Index>
Member Function Documentation
run()
template<typename Evaluator > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar Eigen::internal::inner_product_impl< Evaluator, true >::run (const Evaluator & eval) inline static
{
     const UnsignedIndex size = static_cast<UnsignedIndex>(eval.size());
     if (size < PacketSize) return inner_product_impl<Evaluator, false>::run(eval);
     const UnsignedIndex packetEnd = numext::round_down(size, PacketSize);
     const UnsignedIndex quadEnd = numext::round_down(size, 4 * PacketSize);
     const UnsignedIndex numPackets = size / PacketSize;
     const UnsignedIndex numRemPackets = (packetEnd - quadEnd) / PacketSize;
     Packet presult0, presult1, presult2, presult3;
     presult0 = eval.template packet<Packet>(0 * PacketSize);
     if (numPackets >= 2) presult1 = eval.template packet<Packet>(1 * PacketSize);
     if (numPackets >= 3) presult2 = eval.template packet<Packet>(2 * PacketSize);
     if (numPackets >= 4) {
       presult3 = eval.template packet<Packet>(3 * PacketSize);
       for (UnsignedIndex k = 4 * PacketSize; k < quadEnd; k += 4 * PacketSize) {
         presult0 = eval.packet(presult0, k + 0 * PacketSize);
         presult1 = eval.packet(presult1, k + 1 * PacketSize);
         presult2 = eval.packet(presult2, k + 2 * PacketSize);
         presult3 = eval.packet(presult3, k + 3 * PacketSize);
       }
       if (numRemPackets >= 1) presult0 = eval.packet(presult0, quadEnd + 0 * PacketSize);
       if (numRemPackets >= 2) presult1 = eval.packet(presult1, quadEnd + 1 * PacketSize);
       if (numRemPackets == 3) presult2 = eval.packet(presult2, quadEnd + 2 * PacketSize);
       presult2 = padd(presult2, presult3);
     }
     if (numPackets >= 3) presult1 = padd(presult1, presult2);
     if (numPackets >= 2) presult0 = padd(presult0, presult1);
     Scalar result = predux(presult0);
     for (UnsignedIndex k = packetEnd; k < size; k++) {
       result = eval.coeff(result, k);
     }
     return result;
   }
References k, Eigen::internal::padd(), Eigen::internal::predux(), Eigen::numext::round_down(), run(), and size.
Member Data Documentation
PacketSize
template<typename Evaluator > constexpr int Eigen::internal::inner_product_impl< Evaluator, true >::PacketSize = unpacket_traits<Packet>::size static constexpr
The documentation for this struct was generated from the following file:
InnerProduct.h