MercuryDPM: Eigen::internal::tridiagonalization_inplace_selector< MatrixType, 3, false > Struct Template Reference
Eigen::internal::tridiagonalization_inplace_selector< MatrixType, 3, false > Struct Template Reference
#include <Tridiagonalization.h>
Public Types
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
Static Public Member Functions
template<typename DiagonalType , typename SubDiagonalType , typename CoeffVectorType , typename WorkSpaceType >
static EIGEN_DEVICE_FUNC void run (MatrixType &mat, DiagonalType &diag, SubDiagonalType &subdiag, CoeffVectorType &, WorkSpaceType &, bool extractQ)
Detailed Description
template<typename MatrixType>
struct Eigen::internal::tridiagonalization_inplace_selector< MatrixType, 3, false >
Specialization for 3x3 real matrices. Especially useful for plane fitting.
Member Typedef Documentation
RealScalar
template<typename MatrixType > typedef MatrixType::RealScalar Eigen::internal::tridiagonalization_inplace_selector< MatrixType, 3, false >::RealScalar
Scalar
template<typename MatrixType > typedef MatrixType::Scalar Eigen::internal::tridiagonalization_inplace_selector< MatrixType, 3, false >::Scalar
Member Function Documentation
run()
template<typename MatrixType > template<typename DiagonalType , typename SubDiagonalType , typename CoeffVectorType , typename WorkSpaceType > static EIGEN_DEVICE_FUNC void Eigen::internal::tridiagonalization_inplace_selector< MatrixType, 3, false >::run (MatrixType & mat, DiagonalType & diag, SubDiagonalType & subdiag, CoeffVectorType & , WorkSpaceType & , bool extractQ) inline static
{
     using std::sqrt;
     const RealScalar tol = (std::numeric_limits<RealScalar>::min)();
     diag[0] = mat(0, 0);
     RealScalar v1norm2 = numext::abs2(mat(2, 0));
     if (v1norm2 <= tol) {
       diag[1] = mat(1, 1);
       diag[2] = mat(2, 2);
       subdiag[0] = mat(1, 0);
       subdiag[1] = mat(2, 1);
       if (extractQ) mat.setIdentity();
     } else {
       RealScalar beta = sqrt(numext::abs2(mat(1, 0)) + v1norm2);
       RealScalar invBeta = RealScalar(1) / beta;
       Scalar m01 = mat(1, 0) * invBeta;
       Scalar m02 = mat(2, 0) * invBeta;
       Scalar q = RealScalar(2) * m01 * mat(2, 1) + m02 * (mat(2, 2) - mat(1, 1));
       diag[1] = mat(1, 1) + m02 * q;
       diag[2] = mat(2, 2) - m02 * q;
       subdiag[0] = beta;
       subdiag[1] = mat(2, 1) - m01 * q;
       if (extractQ) {
         mat << 1, 0, 0, 0, m01, m02, 0, m02, -m01;
       }
     }
   }
References Eigen::numext::abs2(), beta, diag, min, Eigen::numext::q, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::setIdentity(), and sqrt().
The documentation for this struct was generated from the following file:
Tridiagonalization.h