MercuryDPM: SinterInteraction Class Reference
SinterInteraction Class Reference
Computes normal forces in case of a linear plastic visco-elastic interaction.
#include <SinterInteraction.h>
Public Types
typedef SinterNormalSpecies SpeciesType
An alias for the corresponding species.
Public Member Functions
SinterInteraction (BaseInteractable *P, BaseInteractable *I, unsigned timeStamp)
Constructor.
SinterInteraction (const SinterInteraction &p)
Copy constructor.
SinterInteraction ()
~SinterInteraction () override
Destructor.
void computeNormalForce ()
Creates a copy of an object of this class. (Deep copy)
void read (std::istream &is) override
Interaction read function, which accepts an std::istream as input.
void write (std::ostream &os) const override
Interaction write function, which accepts an std::ostream as input.
virtual std::string getBaseName () const
Returns the name of the interaction.
Mdouble getElasticEnergy () const override
Computes and returns the amount of elastic energy stored in the spring.
const SinterNormalSpecies * getSpecies () const
Mdouble getPlasticOverlap () const
void setPlasticOverlap (Mdouble plasticOverlap)
Mdouble getUnloadingStiffness () const
unsigned getNumberOfFieldsVTK () const override
std::string getTypeVTK (unsigned i) const override
std::string getNameVTK (unsigned i) const override
std::vector< Mdouble > getFieldVTK (unsigned i) const override
Public Member Functions inherited from BaseInteraction
BaseInteraction (BaseInteractable *P, BaseInteractable *I, unsigned timeStamp)
A constructor takes the BaseInteractable objects which are interacting (come into contact) and time the interaction starts.
BaseInteraction ()
BaseInteraction (const BaseInteraction &p)
Copy constructor.
~BaseInteraction () override
The destructor. It removes this interactions from the objects that were interacting, and writes the time to a file when needed.
virtual void actionsOnErase ()
If an interaction needs to do something before it gets erased, add it here. E.g. Liquid bridges rupture at the end of their lifetime, and the liquid bridge volume has to be redistributed. The reason this action is not done in the destructor is that this action should not be taken when erasing ghost interactions.
virtual void computeForce ()
Virtual function that contains the force law between the two objects interacting.
void writeToFStat (std::ostream &os, Mdouble time) const
Writes forces data to the FStat file.
std::string getName () const override
Virtual function which allows interactions to be named.
void setDistance (Mdouble distance)
Sets the interaction distance between the two interacting objects.
void setNormal (Vec3D normal)
Sets the normal vector between the two interacting objects.
void setOverlap (Mdouble overlap)
Set the overlap between the two interacting object.
void setContactPoint (Vec3D contactPoint)
Set the location of the contact point between the two interacting objects.
void setTimeStamp (unsigned timeStamp)
Updates the time step of the interacting. Note, time steps used to find completed interactions.
void setSpecies (const BaseSpecies *species)
Set the Species of the interaction; note this can either be a Species or MixedSpecies.
void setP (BaseInteractable *P)
Sets the first object involved in the interaction (normally a particle).
void setI (BaseInteractable *I)
Sets the second object involved in the interaction (often particle or wall).
void importP (BaseInteractable *P)
Sets the first object involved in the interaction (normally a particle).
void importI (BaseInteractable *I)
Sets the second object involved in the interaction (often particle or wall).
Vec3D getIP () const
Vec3D getIC () const
Vec3D getCP () const
void setLagrangeMultiplier (Mdouble multiplier)
Mdouble getLagrangeMultiplier ()
void setHandler (InteractionHandler *handler)
Sets the pointer to the interaction hander which is storing this interaction.
InteractionHandler * getHandler () const
Gets a point to the interaction handlers to which this interaction belongs.
const Vec3D & getForce () const
Gets the current force (vector) between the two interacting objects.
const Vec3D & getTorque () const
Gets the current torque (vector) between the two interacting objects.
const Vec3D & getNormal () const
Gets the normal vector between the two interacting objects.
const Vec3D & getContactPoint () const
Gets constant reference to contact point (vector).
Mdouble getOverlap () const
Returns a Mdouble with the current overlap between the two interacting objects.
Mdouble getOverlapVolume () const
Returns the overlap volume between two interacting objects.
Mdouble getContactRadius () const
Returns a Mdouble with the current contact between the two interacting objects.
void removeFromHandler ()
Removes this interaction from its interaction hander.
void copySwitchPointer (const BaseInteractable *original, BaseInteractable *ghost) const
This copies the interactions of the original particle and replaces the original with the ghost copy.
void gatherContactStatistics ()
BaseInteractable * getP ()
Returns a pointer to first object involved in the interaction (normally a particle).
BaseInteractable * getI ()
Returns a pointer to the second object involved in the interaction (often a wall or a particle).
const BaseInteractable * getP () const
Returns a constant pointer to the first object involved in the interaction.
const BaseInteractable * getI () const
Returns a constant pointer to the second object involved in the interaction.
Mdouble getTimeStamp () const
Returns an Mdouble which is the time stamp of the interaction.
virtual void integrate (Mdouble timeStep)
integrates variables of the interaction which need to be integrate e.g. the tangential overlap.
virtual Mdouble getTangentialOverlap () const
get the length of the current tangential overlap
Mdouble getDistance () const
Returns an Mdouble which is the norm (length) of distance vector.
const Vec3D & getRelativeVelocity () const
Returns a constant reference to a vector of relative velocity.
Mdouble getNormalRelativeVelocity () const
Returns a double which is the norm (length) of the relative velocity vector.
Mdouble getAbsoluteNormalForce () const
Returns the absolute value of the norm (length) of the Normal force vector.
virtual BaseInteraction * copy () const =0
Makes a copy of the interaction and returns a pointer to the copy.
void setFStatData (std::fstream &fstat, BaseParticle *P, BaseWall *I)
void setFStatData (std::fstream &fstat, BaseParticle *P, BaseParticle *I)
unsigned int getMultiContactIdentifier () const
void setMultiContactIdentifier (unsigned int multiContactIdentifier_)
virtual void rotateHistory (Matrix3D &rotationMatrix)
When periodic particles are used, some interactions need certain history properties rotated (e.g. tangential springs). This is the function for that.
virtual void actionsAfterTimeStep ()
void addForce (Vec3D force)
add an force increment to the total force.
void addTorque (Vec3D torque)
add a torque increment to the total torque.
void setForce (Vec3D force)
set total force (this is used by the normal force, tangential forces are added use addForce)
void setTorque (Vec3D torque)
set the total force (this is used by the normal force, tangential torques are added use addTorque)
const BaseSpecies * getBaseSpecies () const
Return a constant point to BaseSpecies of the interaction.
virtual void createMPIType ()
virtual void * createMPIInteractionDataArray (unsigned int numberOfInteractions) const
virtual void deleteMPIInteractionDataArray (void *dataArray)
virtual void getMPIInteraction (void *historyDataArray, unsigned int index) const
copies the history interactions into the data array
virtual void getInteractionDetails (void *interactionDataArray, unsigned int index, unsigned int &identificationP, unsigned int &identificationI, bool &isWallInteraction, unsigned &timeStamp)
virtual void setMPIInteraction (void *interactionDataArray, unsigned int index, bool resetPointers)
void setBasicMPIInteractionValues (int P, int I, unsigned timeStamp, Vec3D force, Vec3D torque, bool isWallInteraction, bool resetPointers)
void setIdentificationP (unsigned int identification)
void setIdentificationI (int identification)
void setWallInteraction (bool flag)
unsigned int getIdentificationP ()
int getIdentificationI ()
bool isWallInteraction ()
virtual bool isBonded () const
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Private Attributes
Mdouble plasticOverlap_
Additional Inherited Members
Protected Member Functions inherited from BaseInteraction
virtual const Vec3D getTangentialForce () const
Mdouble getEffectiveRadius () const
Returns a Mdouble to the effective radius of the interaction. (Not corrected for the overlap)
Mdouble getEffectiveMass () const
Returns a Mdouble to the effective radius of the interaction. (Not corrected for the overlap)
void setRelativeVelocity (Vec3D relativeVelocity)
set the relative velocity of the current of the interactions.
void setNormalRelativeVelocity (Mdouble normalRelativeVelocit)
set the normal component of the relative velocity.
void setAbsoluteNormalForce (Mdouble absoluteNormalForce)
the absolute values of the norm (length) of the normal force
virtual Mdouble getElasticEnergyAtEquilibrium (Mdouble adhesiveForce) const
virtual void reverseHistory ()
When periodic particles some interaction need certain history properties reversing. This is the function for that.
void writeInteraction (std::ostream &os, bool created) const
Writes information about a interaction to the interaction file.
Detailed Description
Computes normal forces in case of a linear plastic visco-elastic interaction.
Ref: Visco-elastic sintering kinetics in virgin and aged polymer powders. Powder Technology, 2020.
Member Typedef Documentation
SpeciesType
typedef SinterNormalSpecies SinterInteraction::SpeciesType
An alias for the corresponding species.
Constructor & Destructor Documentation
SinterInteraction() [1/3]
SinterInteraction::SinterInteraction (BaseInteractable * P, BaseInteractable * I, unsigned timeStamp)
Constructor.
Parameters
[in] P
[in] I
[in] timeStamp
         : BaseInteraction(P, I, timeStamp)
 {
     plasticOverlap_ = 0;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"SinterInteraction::SinterInteraction() finished"<<std::endl;
 #endif
 }
References plasticOverlap_.
SinterInteraction() [2/3]
SinterInteraction::SinterInteraction (const SinterInteraction & p)
Copy constructor.
Parameters
[in] p
         : BaseInteraction(p)
 {
     plasticOverlap_ = p.plasticOverlap_;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"SinterInteraction::SinterInteraction(const SinterInteraction &p finished"<<std::endl;
 #endif
 }
References p, and plasticOverlap_.
SinterInteraction() [3/3]
SinterInteraction::SinterInteraction () default
Todo:
: MX add to MPI
~SinterInteraction()
SinterInteraction::~SinterInteraction () override
Destructor.
 {
 #ifdef DEBUG_DESTRUCTOR
     std::cout<<"SinterInteraction::~SinterInteraction() finished"<<std::endl;
 #endif
 }
Member Function Documentation
computeNormalForce()
void SinterInteraction::computeNormalForce ()
Creates a copy of an object of this class. (Deep copy)
Computes the normal forces due to linear plastic visco elastic interaction.
Todo:
adhesive force only, or add normalForce?
 {
     // Compute the relative velocity vector of particle P w.r.t. I
     setRelativeVelocity(
             getP()->getVelocityAtContact(getContactPoint()) - getI()->getVelocityAtContact(getContactPoint()));
     // Compute the projection of vrel onto the normal (can be negative)
     setNormalRelativeVelocity(Vec3D::dot(getRelativeVelocity(), getNormal()));
     if (getOverlap() > 0) //if contact forces
     {
         const SinterNormalSpecies* species = getSpecies();
         // calculate the effective diameter, equal to the radius for two equal-sized particles
         const Mdouble effectiveDiameter = 2.0 * getEffectiveRadius();
         // [1] Calculate the overlap above which the max. unloading stiffness
         //becomes active (the 'fluid branch'). In this interaction, it is the same than delta*
         const Mdouble d_fluid_0 = (species->getUnloadingStiffnessMax()
                                    / (species->getUnloadingStiffnessMax() - species->getLoadingStiffness()))
                                   * species->getPenetrationDepthMax() * effectiveDiameter;
         //const Mdouble deltaStar = species->getPenetrationDepthMax() * effectiveDiameter;
         //[2] Compute the rate d(k2/k1)/d(delta0). To obtain this parameter, the linear relationship
         //between unloading stiffness and maximum overlap is used.
         const Mdouble dk = (species->getUnloadingStiffnessMax() / species->getLoadingStiffness() - 1.0) / d_fluid_0;
         //increase max overlap if necessary
         //Here, two relationships are used. The linear relationship between unloadingstiffness max and
         //the equilibrium overlap based on the unloading stiffness.
         //k2 = k1*(1+dk*d), k1*d = k2*(d-d0)
         //k1*d = k1*(1 + dk*d)*(d-d0)
         //d = d - d0 +dk*d^2 -dk*d*d0
         //dk*d^2 = dk *d * d0 + d0
         //dk*d^2 = (dk*d + 1)*d0
         //dkd^2/(dk*d + 1) = d0
         //d0 = d/(1 + 1/(dk*d))
         //[3] Compute the equilibirum overlap is:
         const Mdouble d0 = getOverlap()/(1.0 + 1.0/(dk*getOverlap()));
         const Mdouble minPlasticOverlap = std::min(d0,d_fluid_0);
         //[4] Determine the plastic overlap
         plasticOverlap_ = std::max(minPlasticOverlap, plasticOverlap_);
         //[5] Compute the unloading Stiffness \hat{k2}.
         const Mdouble unloadingStiffness = species->getLoadingStiffness() * (1.0 + dk * plasticOverlap_);
         //[6] Compute the elastic force
         Mdouble normalForce = unloadingStiffness * (getOverlap() - plasticOverlap_);
         //[7] Add the adhesive force (distinct from sintering)
         Mdouble nonSinterAdhesiveForce = -species->getCohesionStiffness() * getOverlap();
         if (normalForce < nonSinterAdhesiveForce)
         {
             plasticOverlap_ = (1.0 + species->getCohesionStiffness() / unloadingStiffness) * getOverlap();
             normalForce = nonSinterAdhesiveForce;
         }
         //[[8] Add dissipative force (distinct from sintering)
         normalForce -= species->getDissipation() * getNormalRelativeVelocity();
         //[9] Sintering effect:
         Mdouble adhesiveForce = species->getSinterAdhesion() * effectiveDiameter;
         //[10] Now set the interaction force equal to this normal force (friction and adhesive forces will be added later)
         setForce(getNormal() * ((normalForce - adhesiveForce)));
         setTorque(Vec3D(0.0, 0.0, 0.0));
         //used for tangential force calculations; don't add adhesive force components
         setAbsoluteNormalForce(std::abs(normalForce));
         //[11] Approaches - Increase plastic overlap due to sintering
         const Mdouble baseNum = 9*constants::pi*species->getComplianceZero()*species->getSurfTension()/(effectiveDiameter);
         const Mdouble a0_R = std::pow(baseNum,1.0/3.0);
         const Mdouble realOverlap = std::sqrt(getOverlap()/effectiveDiameter);
         DPMBase* dpmBase = getHandler()->getDPMBase();
         Mdouble rateOverlap;
         // sinter adhesion force fa=sinterAdhesion_*radius in sinter rate:
         if (species->getSinterType() == SINTERTYPE::PARHAMI_MCKEEPING)
         {
             rateOverlap = normalForce * species->getSinterRate() /
                           (0.375 * species->getSinterAdhesion() * mathsFunc::square(
                                   getOverlap() / effectiveDiameter));
             if (species->getSinterRate() == 0) rateOverlap = 0;
         }
         else if (species->getSinterType() == SINTERTYPE::CONSTANT_RATE)
         {
             rateOverlap = 2.0 * normalForce * species->getSinterRate() / species->getSinterAdhesion();
             if (species->getSinterRate() == 0) rateOverlap = 0;
         }
         else if (species->getSinterType() == SINTERTYPE::TEMPERATURE_DEPENDENT_FRENKEL)
         {
             ThermalParticle* tp = dynamic_cast<ThermalParticle*>(getP());
             ThermalParticle* ti = dynamic_cast<ThermalParticle*>(getI());
             logger.assert_debug(tp && ti,
                           "warning contact partners have to be ThermalParticle's if this sinter species is used");
             double temperature =
                     2.0 * tp->getTemperature() * ti->getTemperature() / (tp->getTemperature() + ti->getTemperature());
             rateOverlap = 2.0 * normalForce * species->getTemperatureDependentSinterRate(temperature) /
                           species->getSinterAdhesion();
         }
         else if (species->getSinterType() == SINTERTYPE::REGIME_SINTERING)
         {
             if (realOverlap < a0_R) {
                 //Here, Sintering rate has unit of [1/s]
                 rateOverlap = normalForce / species->getSinterAdhesion();
                 //rateOverlap = effectiveDiameter* species->getSinterRate();
             }else {
                 const Mdouble val0 = std::pow((63 * pow(constants::pi, 3.0) / 16.0), 1.0 / 7.0);
                 const Mdouble val1 = pow((species->getSeparationDis()*10 / effectiveDiameter), 2.0 / 7.0);
                 const Mdouble val2 = (2.0 / 7.0) * (2.0 * species->getConstantC1() * species->getSurfTension() /
                                                     (effectiveDiameter));
                 const Mdouble val3 = 1.0 / (std::pow(getOverlap(), 5.0 / 2.0));
                 const Mdouble val4 = std::pow(effectiveDiameter, 7.0 / 2.0);
                 rateOverlap = (std::pow(val0 * val1, 7.0) * val2 * val3 * val4) * normalForce / species->getSinterAdhesion();
                 const Mdouble aVisc_R = std::pow(63.0 * std::pow(constants::pi, 3.0), 1.0 / 5.0) *
                                         std::pow((1.0 / 8.0) * (species->getSeparationDis()/33.0) / (effectiveDiameter), 2.0 / 5.0);
                 if (realOverlap > aVisc_R) {
                     rateOverlap = 2.0*normalForce * species->getSinterRate() / species->getSinterAdhesion();
 //                    logger(INFO," RealOver % aVisc_R %",realOverlap,aVisc_R);
                 }
             }
         }
         else
         {
             rateOverlap = 0;
             //missing: add the sintering model 'modified Frenkel' of the Pokula paper
         }
         plasticOverlap_ = std::max(0.0, std::min(d_fluid_0, plasticOverlap_ + rateOverlap * dpmBase->getTimeStep()));
         /*//change particle radius by dr
         Mdouble dr;
         BaseParticle* PParticle = dynamic_cast<BaseParticle*>(getP());
         BaseParticle* IParticle = dynamic_cast<BaseParticle*>(getI());
         if (dpmBase->getSystemDimensions()==2) {
             //2D: increase the radius of each particle such that the particle area
             //increases by the same amount that the contact area decreases
             //Particle circumference C = 2 pi r increased by dr => dA = 2 pi r dr
             //Contact line L = 2*sqrt(2*r*o) indented by do/2 => dA = sqrt(2*r*o) do
             //Thus, dr = sqrt(0.5*o/r)/pi do.
             dr = sqrt(0.5*plasticOverlap_/effectiveDiameter)/3.14 *doverlap;
         } else {
             //3D: increase the radius of each sphere such that the particle volume
             //increases by the same amount that the contact volume decreases
             //Particle surface area S = 4 pi r^2 increased by dr => dA = 4 pi r^2 dr
             //Contact area L = pi 2*r*o indented by do/2 => dA = pi r o do
             //Thus, dr = 0.25*o/r do
             dr = 0.25*plasticOverlap_/effectiveDiameter *doverlap;
         }
         if (PParticle==nullptr) { //if P is a wall
             IParticle->setRadius(IParticle->getRadius()+dr);//should be twice that amount
         } else if (IParticle==nullptr) { //if I is a wall
             PParticle->setRadius(PParticle->getRadius()+dr);
         } else { //if both P and I are particles
             PParticle->setRadius(PParticle->getRadius()+dr);
             IParticle->setRadius(IParticle->getRadius()+dr);
         }*/
     }
     else
     {
         setAbsoluteNormalForce(0.0);
         setForce(Vec3D(0.0, 0.0, 0.0));
         setTorque(Vec3D(0.0, 0.0, 0.0));
     }
 }
References abs(), CONSTANT_RATE, Vec3D::dot(), SinterNormalSpecies::getCohesionStiffness(), SinterNormalSpecies::getComplianceZero(), SinterNormalSpecies::getConstantC1(), BaseInteraction::getContactPoint(), SinterNormalSpecies::getDissipation(), BaseHandler< T >::getDPMBase(), BaseInteraction::getEffectiveRadius(), BaseInteraction::getHandler(), BaseInteraction::getI(), SinterNormalSpecies::getLoadingStiffness(), BaseInteraction::getNormal(), BaseInteraction::getNormalRelativeVelocity(), BaseInteraction::getOverlap(), BaseInteraction::getP(), SinterNormalSpecies::getPenetrationDepthMax(), BaseInteraction::getRelativeVelocity(), SinterNormalSpecies::getSeparationDis(), SinterNormalSpecies::getSinterAdhesion(), SinterNormalSpecies::getSinterRate(), SinterNormalSpecies::getSinterType(), getSpecies(), SinterNormalSpecies::getSurfTension(), Thermal< Particle >::getTemperature(), SinterNormalSpecies::getTemperatureDependentSinterRate(), DPMBase::getTimeStep(), SinterNormalSpecies::getUnloadingStiffnessMax(), logger, max, min, PARHAMI_MCKEEPING, constants::pi, plasticOverlap_, Eigen::bfloat16_impl::pow(), REGIME_SINTERING, BaseInteraction::setAbsoluteNormalForce(), BaseInteraction::setForce(), BaseInteraction::setNormalRelativeVelocity(), BaseInteraction::setRelativeVelocity(), BaseInteraction::setTorque(), sqrt(), mathsFunc::square(), and TEMPERATURE_DEPENDENT_FRENKEL.
getBaseName()
std::string SinterInteraction::getBaseName () const virtual
Returns the name of the interaction.
Returns
std::string
 {
     return "Sinter";
 }
getElasticEnergy()
Mdouble SinterInteraction::getElasticEnergy () const override virtual
Computes and returns the amount of elastic energy stored in the spring.
Returns
Mdouble
Todo:
TW this is not correct; we should count the return energy
Reimplemented from BaseInteraction.
 {
     if (getOverlap() > 0)
         return 0.5 * (getSpecies()->getLoadingStiffness() * mathsFunc::square(getOverlap()));
     else
         return 0.0;
 }
References SinterNormalSpecies::getLoadingStiffness(), BaseInteraction::getOverlap(), getSpecies(), and mathsFunc::square().
getFieldVTK()
std::vector< Mdouble > SinterInteraction::getFieldVTK (unsigned i) const override virtual
Reimplemented from BaseInteraction.
 {
     if (i == 0)
         return std::vector<Mdouble>(1, plasticOverlap_);
     else
         return std::vector<Mdouble>(1, sqrt(2.0 * getEffectiveRadius() * plasticOverlap_));
 }
References BaseInteraction::getEffectiveRadius(), i, plasticOverlap_, and sqrt().
getNameVTK()
std::string SinterInteraction::getNameVTK (unsigned i) const override virtual
Reimplemented from BaseInteraction.
 {
     if (i == 0)
         return "plasticOverlap";
     else
         return "neckRadius";
 }
References i.
getNumberOfFieldsVTK()
unsigned SinterInteraction::getNumberOfFieldsVTK () const override virtual
Reimplemented from BaseInteraction.
 {
     return 2;
 }
getPlasticOverlap()
Mdouble SinterInteraction::getPlasticOverlap () const
Returns
Mdouble plasticOverlap_
 {
     return plasticOverlap_;
 }
References plasticOverlap_.
Referenced by getUnloadingStiffness().
getSpecies()
const SinterNormalSpecies * SinterInteraction::getSpecies () const
Returns
const SinterNormalSpecies*
 {
     return static_cast<const SinterNormalSpecies*>(getBaseSpecies()->getNormalForce());
 ;
 }
References BaseInteraction::getBaseSpecies(), and BaseSpecies::getNormalForce().
Referenced by computeNormalForce(), getElasticEnergy(), and getUnloadingStiffness().
getTypeVTK()
std::string SinterInteraction::getTypeVTK (unsigned i) const override virtual
Reimplemented from BaseInteraction.
 {
     return "Float32";
 }
getUnloadingStiffness()
Mdouble SinterInteraction::getUnloadingStiffness () const
Returns
Mdouble
 {
     const SinterNormalSpecies* species = getSpecies();
     Mdouble effectiveDiameter = 2.0 * getEffectiveRadius();
     Mdouble deltaMaxFluid = species->getPenetrationDepthMax() * effectiveDiameter /
                             (1.0 - species->getLoadingStiffness() / species->getUnloadingStiffnessMax());
     if (getOverlap() > deltaMaxFluid)
         return species->getUnloadingStiffnessMax();
     else
         return species->getLoadingStiffness() + (species->getUnloadingStiffnessMax() - species->getLoadingStiffness()) *
                                                 getPlasticOverlap() / deltaMaxFluid;
 }
References BaseInteraction::getEffectiveRadius(), SinterNormalSpecies::getLoadingStiffness(), BaseInteraction::getOverlap(), SinterNormalSpecies::getPenetrationDepthMax(), getPlasticOverlap(), getSpecies(), and SinterNormalSpecies::getUnloadingStiffnessMax().
read()
void SinterInteraction::read (std::istream & is) override virtual
Interaction read function, which accepts an std::istream as input.
Calls the read function of BaseInteraction().
Parameters
[in,out] is
Reimplemented from BaseInteraction.
 {
     BaseInteraction::read(is);
     std::string dummy;
     is >> dummy >> plasticOverlap_;
 }
References plasticOverlap_, BaseInteraction::read(), and oomph::Global_string_for_annotation::string().
setPlasticOverlap()
void SinterInteraction::setPlasticOverlap (Mdouble plasticOverlap)
Parameters
[in] maxOverlap
 {
     plasticOverlap_ = plasticOverlap;
 }
References plasticOverlap_.
write()
void SinterInteraction::write (std::ostream & os) const override virtual
Interaction write function, which accepts an std::ostream as input.
Calls the write function of BaseInteraction().
Parameters
[in,out] os
Reimplemented from BaseInteraction.
 {
     BaseInteraction::write(os);
     os << " plasticOverlap " << plasticOverlap_;
 }
References plasticOverlap_, and BaseInteraction::write().
Member Data Documentation
plasticOverlap_
Mdouble SinterInteraction::plasticOverlap_ private
Referenced by computeNormalForce(), getFieldVTK(), getPlasticOverlap(), read(), setPlasticOverlap(), SinterInteraction(), and write().
The documentation for this class was generated from the following files:
SinterInteraction.h
SinterInteraction.cc