MercuryDPM: AngledPeriodicBoundarySecondUnitTest.cpp File Reference
AngledPeriodicBoundarySecondUnitTest.cpp File Reference
#include "Species/Species.h"
#include "Species/LinearViscoelasticFrictionReversibleAdhesiveSpecies.h"
#include "DPMBase.h"
#include "Boundaries/AngledPeriodicBoundary.h"
Classes
class AngledPeriodicBoundarySecondUnitTest
Functions
int main (int argc UNUSED, char *argv[] UNUSED)
Function Documentation
main()
int main (int argc UNUSED, char *argv[] UNUSED)
 {
     AngledPeriodicBoundarySecondUnitTest dpm;
     dpm.setName("AngledPeriodicBoundarySecondUnitTest");
     dpm.setTimeMax(4.0 * constants::pi);
     dpm.solve(argc, argv);
     AngledPeriodicBoundarySecondUnitTest dpm2;
     dpm2.setName("AngledPeriodicBoundarySecondUnitTest2");
     dpm2.boundaryHandler.clear();
     dpm2.setTimeMax(4.0 * constants::pi);
     dpm2.solve(argc, argv);
     if (!mathsFunc::isEqual(dpm.particleHandler.getObject(0)->getAngularVelocity(),
                             dpm2.particleHandler.getObject(0)->getAngularVelocity(), 1e-10))
     {
         logger(ERROR, "angular velocity of the two simulations doesn't match");
     }
     //Note:: currently the rolling spring is not conserved!!
     return 0;
 }
References DPMBase::boundaryHandler, BaseHandler< T >::clear(), e(), ERROR, BaseInteractable::getAngularVelocity(), BaseHandler< T >::getObject(), mathsFunc::isEqual(), logger, DPMBase::particleHandler, constants::pi, DPMBase::setName(), DPMBase::setTimeMax(), and DPMBase::solve().