MercuryDPM: spring_contact2.cc File Reference
spring_contact2.cc File Reference
#include "generic.h"
#include <fenv.h>
Namespaces
GlobalFct
Functions
void GlobalFct::reset (Vector< double > &unknowns)
Reset unknowns to some nontrivial garbage.
void GlobalFct::get_residuals (const Vector< double > &param, const Vector< double > &unknowns, Vector< double > &residuals)
Global residual fct.
void GlobalFct::plot_it (const std::string filename)
Plot "landscape" of residuals (only for 2D problems!)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc , char ** argv)
/////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////
 {
  //feenableexcept(FE_INVALID | FE_DIVBYZERO | FE_OVERFLOW | FE_UNDERFLOW);
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // CommandLineArgs::specify_command_line_flag("--bilinear");
  // CommandLineArgs::specify_command_line_flag("--completely_smooth");
  // CommandLineArgs::specify_command_line_flag("--single_kink");
  // CommandLineArgs::specify_command_line_flag("--old_version");
  // CommandLineArgs::specify_command_line_flag("--kuhn_tucker");
  // CommandLineArgs::specify_command_line_flag("--n_primary",
  //                                            &GlobalFct::N_primary);
  // Doc available command line flags
  CommandLineArgs::doc_available_flags();
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  // Number of steps for load incrementation
  unsigned nstep=10;
  unsigned nstep_total=2*nstep;
  BlackBoxFDNewtonSolver::Max_iter=30;
  ofstream outfile2;
  outfile2.open("trace.dat");
  BlackBoxFDNewtonSolver::Doc_Progress=true;
  Vector<double> param;
  Vector<double> unknowns;
  GlobalFct::reset(unknowns);
  GlobalFct::Force=0.0;
  for (unsigned j=0;j<nstep_total;j++)
   {
    oomph_info << "\n\nSolving for force: " << GlobalFct::Force
               << std::endl << std::endl;
    char name[100];
    sprintf(name,"landscape%i.dat",j);
    std::string filename(name);
    GlobalFct::plot_it(filename);
    try
     {
      //BlackBoxFDNewtonSolver::Use_step_length_control=true;
      BlackBoxFDNewtonSolver::black_box_fd_newton_solve(
       GlobalFct::get_residuals,param,unknowns);
      oomph_info << "Number of Newton iterations to convergence: "
                 << BlackBoxFDNewtonSolver::N_iter_taken++ << std::endl;
      char name[100];
      sprintf(name,"soln%i.dat",j);
      ofstream outfile;
      outfile.open(name);
      outfile <<  unknowns[0] << " "
              <<  unknowns[1] << "\n";
      outfile.close();
      oomph_info <<  "Displ: " << GlobalFct::U_max-unknowns[0]*unknowns[0]<< " "
                 <<  "Contact force: " << unknowns[1]*unknowns[1]<< " "
                 << std::endl;
      unsigned n=unknowns.size();
      outfile2 << GlobalFct::Force << " ";
      for (unsigned k=0;k<n;k++)
       {
        outfile2 << unknowns[k] << " ";
       }
      outfile2 << std::endl;
     }
    catch(OomphLibError) {}
    // Sweep up and then down
    if (j<nstep)
     {
      GlobalFct::Force+=2.1;
     }
    else
     {
      GlobalFct::Force-=2.1;
     }
   }
  outfile2.close();
  // //----------------------------------------
  // oomph_info << "\n\n\n\nTRY POSSIBLY SPURIOUS SOLUTION\n"
  //            <<         "==============================\n\n";
  // // Try spurious solution
  // GlobalFct::set_spurious_solution(unknowns);
  // BlackBoxFDNewtonSolver::black_box_fd_newton_solve(
  //  GlobalFct::get_residuals,param,unknowns);
  // oomph_info << "Number of Newton iterations to convergence: "
  //            << BlackBoxFDNewtonSolver::N_iter_taken++ << std::endl;
  // oomph_info << "\nPossibly spurious solution: "
  //            << unknowns[0] << " " <<  unknowns[1] << "\n\n";
 } // end_of_main
References oomph::BlackBoxFDNewtonSolver::black_box_fd_newton_solve(), oomph::CommandLineArgs::doc_available_flags(), oomph::BlackBoxFDNewtonSolver::Doc_Progress, oomph::CommandLineArgs::doc_specified_flags(), MergeRestartFiles::filename, GlobalFct::Force, GlobalFct::get_residuals(), j, k, oomph::BlackBoxFDNewtonSolver::Max_iter, n, oomph::BlackBoxFDNewtonSolver::N_iter_taken, plotDoE::name, oomph::oomph_info, oomph::CommandLineArgs::parse_and_assign(), GlobalFct::plot_it(), GlobalFct::reset(), Flag_definition::setup(), oomph::Global_string_for_annotation::string(), and GlobalFct::U_max.