MercuryDPM: adaptive_unstructured_scattering_quad.cc File Reference
adaptive_unstructured_scattering_quad.cc File Reference
#include "math.h"
#include <complex>
#include "generic.h"
#include "helmholtz.h"
#include "meshes/quad_from_triangle_mesh.h"
#include "meshes/rectangular_quadmesh.h"
#include "oomph_crbond_bessel.h"
Classes
class ScatteringProblem< ELEMENT >
Problem class to compute scattering of planar wave from unit disk.
Namespaces
GlobalParameters
Global parameters.
Macros
#define ADAPTIVE
Functions
std::complex< double > GlobalParameters::I (0.0, 1.0)
Imaginary unit.
void GlobalParameters::get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void GlobalParameters::prescribed_incoming_flux (const Vector< double > &x, complex< double > &flux)
int main (int argc, char **argv)
Macro Definition Documentation
ADAPTIVE
#define ADAPTIVE
Function Documentation
main()
int main (int argc , char ** argv)
Solve 2D Helmholtz problem for scattering of a planar wave from a unit disk
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Define case to be run
  unsigned i_case=0;
  CommandLineArgs::specify_command_line_flag("--case",&i_case);
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  // Now set flags accordingly
  switch(i_case)
   {
   case 0:
    GlobalParameters::DtN_BC=true;
    break;
   case 1:
    GlobalParameters::DtN_BC=false;
    GlobalParameters::ABC_order=1;
    break;
   case 2:
    GlobalParameters::DtN_BC=false;
    GlobalParameters::ABC_order=2;
    break;
   case 3:
    GlobalParameters::DtN_BC=false;
    GlobalParameters::ABC_order=3;
    break;
   }
  //Set up the problem
  //------------------
 #ifdef ADAPTIVE
  // Typedef the ELEMENT and MESH type
  typedef RefineableQHelmholtzElement<2,3> ELEMENT;
  typedef RefineableQuadFromTriangleMesh<ELEMENT> MESH;
 #else
  // Typedef the ELEMENT and MESH type
  typedef QHelmholtzElement<2,3> ELEMENT;
  typedef QuadFromTriangleMesh<ELEMENT> MESH;
 #endif
  // Set up the problem with 2D nine-node elements from the
  // QHelmholtzElement family.
  ScatteringProblem<ELEMENT,MESH> problem;
  // Create label for output
  //------------------------
  DocInfo doc_info;
  // Set output directory
  doc_info.set_directory("RESLT");
 #ifdef ADAPTIVE
  // Max. number of adaptations
  unsigned max_adapt=1;
  // Solve the problem with Newton's method, allowing
  // up to max_adapt mesh adaptations after every solve.
  problem.newton_solve(max_adapt);
 #else
  // Solve the problem with Newton's method
  problem.newton_solve();
 #endif
  //Output solution
  problem.doc_solution(doc_info);
 } //end of main
References GlobalParameters::ABC_order, oomph::CommandLineArgs::doc_specified_flags(), GlobalParameters::DtN_BC, oomph::CommandLineArgs::parse_and_assign(), problem, oomph::DocInfo::set_directory(), oomph::CommandLineArgs::setup(), and oomph::CommandLineArgs::specify_command_line_flag().