MercuryDPM: oomph::FluidInterfaceAdditionalValues< SolubleSurfactantTransportInterfaceElement > Class Reference
oomph::FluidInterfaceAdditionalValues< SolubleSurfactantTransportInterfaceElement > Class Reference
#include <soluble_surfactant_transport_equations.h>
Public Member Functions
FluidInterfaceAdditionalValues ()
unsigned nadditional_values (const unsigned &n)
void setup_equation_indices (SolubleSurfactantTransportInterfaceElement *const &element_pt, const unsigned &id)
Detailed Description
============================================================================= This is the policy class for the surfactanttransport equations which require one additional value for the surface concentration
Constructor & Destructor Documentation
FluidInterfaceAdditionalValues()
oomph::FluidInterfaceAdditionalValues< SolubleSurfactantTransportInterfaceElement >::FluidInterfaceAdditionalValues () inline
 {}
References oomph::FiniteElement::output().
Member Function Documentation
nadditional_values()
unsigned oomph::FluidInterfaceAdditionalValues< SolubleSurfactantTransportInterfaceElement >::nadditional_values (const unsigned & n) inline
 {return 1;}
setup_equation_indices()
void oomph::FluidInterfaceAdditionalValues< SolubleSurfactantTransportInterfaceElement >::setup_equation_indices (SolubleSurfactantTransportInterfaceElement *const & element_pt, const unsigned & id) inline
   {
    const unsigned n_node = element_pt->nnode();
    Vector<unsigned> c_index(n_node);
    for(unsigned n=0;n<n_node;n++)
     {
      c_index[n] =
       dynamic_cast<BoundaryNodeBase*>(element_pt->node_pt(n))
       ->index_of_first_value_assigned_by_face_element(id);
     }
    element_pt->set_c_index(c_index);
    //This is a hack
    const unsigned C_bulk_index =
     dynamic_cast<AdvectionDiffusionReactionEquations<2,2>*>(
       element_pt->bulk_element_pt())->c_index_adv_diff_react(0);
     element_pt->set_c_bulk_index(C_bulk_index);
   }
References oomph::FaceElement::bulk_element_pt(), n, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::SolubleSurfactantTransportInterfaceElement::set_c_bulk_index(), and oomph::SurfactantTransportInterfaceElement::set_c_index().
The documentation for this class was generated from the following file:
soluble_surfactant_transport_equations.h