MercuryDPM: GeneralCircle Class Reference
GeneralCircle Class Reference
Public Member Functions
GeneralCircle (const double &centre_y, const double &radius)
virtual ~GeneralCircle ()
Destructor.
void position (const Vector< double > &xi, Vector< double > &r) const
Lagrangian coordinate xi.
bool interpolated_history (const unsigned &t)
void position (const unsigned &t, const Vector< double > &xi, Vector< double > &r) const
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
GeneralCircle (const double &centre_x, const double &centre_y, const double &radius)
virtual ~GeneralCircle ()
Destructor.
void position (const Vector< double > &xi, Vector< double > &r) const
Lagrangian coordinate xi.
void position (const unsigned &t, const Vector< double > &xi, Vector< double > &r) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition_dt (const Vector< double > &zeta, const unsigned &j, Vector< double > &drdt)
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
virtual void locate_zeta (const Vector< double > &zeta, GeomObject *&sub_geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
Private Attributes
double Centre_y
Storage for the y-coordinate of the centre.
double Radius
Storage for the radius of the circle.
double Centre_x
Storage for the x-coordinate of the centre.
Additional Inherited Members
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Constructor & Destructor Documentation
GeneralCircle() [1/2]
GeneralCircle::GeneralCircle (const double & centre_y, const double & radius) inline
Constructor that takes the centre position and radius of the circle as its arguments
                                      :
   GeomObject(1,2), Centre_y(centre_y), Radius(radius) { }
~GeneralCircle() [1/2]
virtual GeneralCircle::~GeneralCircle () inline virtual
Destructor.
 {}
GeneralCircle() [2/2]
GeneralCircle::GeneralCircle (const double & centre_x, const double & centre_y, const double & radius) inline
Constructor that takes the centre position and raidus of the circle as its arguments
                                         :
   GeomObject(1,2), Centre_x(centre_x), Centre_y(centre_y), Radius(radius) { }
~GeneralCircle() [2/2]
virtual GeneralCircle::~GeneralCircle () inline virtual
Destructor.
 {}
Member Function Documentation
geom_data_pt()
Data* GeneralCircle::geom_data_pt (const unsigned & j) inline virtual
Return pointer to the j-th (only) Data item that the object's shape depends on.
Reimplemented from oomph::GeomObject.
   {return 0;}
interpolated_history()
bool GeneralCircle::interpolated_history (const unsigned & t) inline
   {
    if(t==0) {return true;}
    else {return false;}
   }
References plotPSD::t.
ngeom_data()
unsigned GeneralCircle::ngeom_data () const inline virtual
How many items of Data does the shape of the object depend on? This is implemented as a broken virtual function. You must overload this for GeomObjects that contain geometric Data, i.e. GeomObjects whose shape depends on Data that may contain unknowns in the overall Problem.
Reimplemented from oomph::GeomObject.
 {return 0;}
position() [1/4]
void GeneralCircle::position (const unsigned & t, const Vector< double > & xi, Vector< double > & r) const inline virtual
Return the position of the circle as a function of time (doesn't move as a function of time)
Reimplemented from oomph::GeomObject.
   {
    position(xi,r);
   }
References UniformPSDSelfTest::r.
position() [2/4]
void GeneralCircle::position (const unsigned & t, const Vector< double > & xi, Vector< double > & r) const inline virtual
Return the position of the circle as a function of time (doesn't move as a function of time)
Reimplemented from oomph::GeomObject.
   {
    position(xi,r);
   }
References UniformPSDSelfTest::r.
position() [3/4]
void GeneralCircle::position (const Vector< double > & xi, Vector< double > & r) const inline virtual
Lagrangian coordinate xi.
Implements oomph::GeomObject.
 {
  Vector<double> r_circle(2);
  r_circle[0] = 1.0/Global_Physical_Variables::Delta + Radius*cos(xi[0]);
  r_circle[1] = Centre_y + Radius*sin(xi[0]);
  Vector<double> r_square(2);
  const double pi = MathematicalConstants::Pi;
  if(std::fabs(xi[0]) < 0.25*pi)
   {
    r_square[0] = 1.0/Global_Physical_Variables::Delta + Radius;
    r_square[1] = Centre_y + Radius*tan(xi[0]);
   }
  else if((xi[0] >= 0.25*pi) && (xi[0] < 0.75*pi))
   {
    r_square[0] = 1.0/Global_Physical_Variables::Delta
     + Radius*tan(0.5*pi - xi[0]);
    r_square[1] = Centre_y + Radius;
   }
  else if(std::fabs(xi[0]) >= 0.75*pi)
   {
    r_square[0] = 1.0/Global_Physical_Variables::Delta - Radius;
    r_square[1] = Centre_y + Radius*tan(pi - xi[0]);
   }
  else
   {
    r_square[0] = 1.0/Global_Physical_Variables::Delta
     + Radius*tan(0.5*pi + xi[0]);
    r_square[1] = Centre_y - Radius;
   }
  //Now smoothly match between the two
  for(unsigned i=0;i<2;i++)
   {
    r[i] = Global_Physical_Variables::Mu*r_circle[i] +
     (1.0 - Global_Physical_Variables::Mu)*r_square[i];
   }
 }
References Global_Parameters::Centre_y, cos(), Global_Physical_Variables::Delta, boost::multiprecision::fabs(), i, Global_Physical_Variables::Mu, constants::pi, BiharmonicTestFunctions2::Pi, UniformPSDSelfTest::r, Global_Physical_Variables::Radius, sin(), and Eigen::bfloat16_impl::tan().
position() [4/4]
void GeneralCircle::position (const Vector< double > & xi, Vector< double > & r) const inline virtual
Lagrangian coordinate xi.
Implements oomph::GeomObject.
 {
  r[0] = Centre_x + Radius*cos(xi[0]);
  r[1] = Centre_y + Radius*sin(xi[0]);
 }
References Global_Parameters::Centre_x, Global_Parameters::Centre_y, cos(), UniformPSDSelfTest::r, Global_Physical_Variables::Radius, and sin().
Member Data Documentation
Centre_x
double GeneralCircle::Centre_x private
Storage for the x-coordinate of the centre.
Centre_y
double GeneralCircle::Centre_y private
Storage for the y-coordinate of the centre.
Radius
double GeneralCircle::Radius private
Storage for the radius of the circle.
The documentation for this class was generated from the following files:
pressure_driven_torus.cc
unstructured_torus.cc