MercuryDPM: Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense > Class Template Reference
Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
Base class for a triangular part in a dense matrix.
#include <TriangularMatrix.h>
Public Types
enum { Mode = Mode_ , Flags = internal::traits<TriangularViewType>::Flags }
typedef TriangularView< MatrixType_, Mode_ > TriangularViewType
typedef TriangularBase< TriangularViewType > Base
typedef internal::traits< TriangularViewType >::Scalar Scalar
typedef MatrixType_ MatrixType
typedef MatrixType::PlainObject DenseMatrixType
typedef DenseMatrixType PlainObject
typedef internal::traits< TriangularViewType >::StorageKind StorageKind
Public Types inherited from Eigen::TriangularBase< TriangularView< MatrixType_, Mode_ > >
enum
typedef internal::traits< TriangularView< MatrixType_, Mode_ > >::Scalar Scalar
typedef internal::traits< TriangularView< MatrixType_, Mode_ > >::StorageKind StorageKind
typedef internal::traits< TriangularView< MatrixType_, Mode_ > >::StorageIndex StorageIndex
typedef internal::traits< TriangularView< MatrixType_, Mode_ > >::FullMatrixType DenseMatrixType
typedef DenseMatrixType DenseType
typedef TriangularView< MatrixType_, Mode_ > const & Nested
Public Types inherited from Eigen::EigenBase< Derived >
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< Derived >::StorageKind StorageKind
Public Member Functions
EIGEN_DEVICE_FUNC Index outerStride () const
EIGEN_DEVICE_FUNC Index innerStride () const
template<typename Other >
EIGEN_DEVICE_FUNC TriangularViewType & operator+= (const DenseBase< Other > &other)
template<typename Other >
EIGEN_DEVICE_FUNC TriangularViewType & operator-= (const DenseBase< Other > &other)
EIGEN_DEVICE_FUNC TriangularViewType & operator*= (const typename internal::traits< MatrixType >::Scalar &other)
EIGEN_DEVICE_FUNC TriangularViewType & operator/= (const typename internal::traits< MatrixType >::Scalar &other)
EIGEN_DEVICE_FUNC void fill (const Scalar &value)
EIGEN_DEVICE_FUNC TriangularViewType & setConstant (const Scalar &value)
EIGEN_DEVICE_FUNC TriangularViewType & setZero ()
EIGEN_DEVICE_FUNC TriangularViewType & setOnes ()
EIGEN_DEVICE_FUNC Scalar coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC Scalar & coeffRef (Index row, Index col)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC TriangularViewType & operator= (const TriangularBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC TriangularViewType & operator= (const MatrixBase< OtherDerived > &other)
EIGEN_DEVICE_FUNC TriangularViewType & operator= (const TriangularViewImpl &other)
template<typename OtherDerived >
EIGEN_DEPRECATED EIGEN_DEVICE_FUNC void lazyAssign (const TriangularBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEPRECATED EIGEN_DEVICE_FUNC void lazyAssign (const MatrixBase< OtherDerived > &other)
template<typename OtherDerived >
EIGEN_DEVICE_FUNC const Product< TriangularViewType, OtherDerived > operator* (const MatrixBase< OtherDerived > &rhs) const
template<int Side, typename Other >
const internal::triangular_solve_retval< Side, TriangularViewType, Other > solve (const MatrixBase< Other > &other) const
template<int Side, typename OtherDerived >
EIGEN_DEVICE_FUNC void solveInPlace (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC void solveInPlace (const MatrixBase< OtherDerived > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC void swap (TriangularBase< OtherDerived > const &other)
template<typename OtherDerived >
EIGEN_DEPRECATED EIGEN_DEVICE_FUNC void swap (MatrixBase< OtherDerived > const &other)
template<typename RhsType , typename DstType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void _solve_impl (const RhsType &rhs, DstType &dst) const
template<typename ProductType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TriangularViewType & _assignProduct (const ProductType &prod, const Scalar &alpha, bool beta)
EIGEN_DEVICE_FUNC const Derived & derived () const
EIGEN_DEVICE_FUNC Derived & derived ()
template<typename DenseDerived >
EIGEN_DEVICE_FUNC void evalToLazy (MatrixBase< DenseDerived > &other) const
Public Member Functions inherited from Eigen::TriangularBase< TriangularView< MatrixType_, Mode_ > >
EIGEN_DEVICE_FUNC TriangularBase ()
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index outerStride () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index innerStride () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC void resize (Index rows, Index cols)
EIGEN_DEVICE_FUNC Scalar coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC Scalar & coeffRef (Index row, Index col)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void copyCoeff (Index row, Index col, Other &other)
EIGEN_DEVICE_FUNC Scalar operator() (Index row, Index col) const
EIGEN_DEVICE_FUNC Scalar & operator() (Index row, Index col)
EIGEN_DEVICE_FUNC const TriangularView< MatrixType_, Mode_ > & derived () const
EIGEN_DEVICE_FUNC TriangularView< MatrixType_, Mode_ > & derived ()
EIGEN_DEVICE_FUNC void evalTo (MatrixBase< DenseDerived > &other) const
EIGEN_DEVICE_FUNC void evalToLazy (MatrixBase< DenseDerived > &other) const
EIGEN_DEVICE_FUNC DenseMatrixType toDenseMatrix () const
Public Member Functions inherited from Eigen::EigenBase< Derived >
constexpr EIGEN_DEVICE_FUNC Derived & derived ()
constexpr EIGEN_DEVICE_FUNC const Derived & derived () const
EIGEN_DEVICE_FUNC Derived & const_cast_derived () const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index size () const EIGEN_NOEXCEPT
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
template<typename Device >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< Derived, Device > device (Device &device)
template<typename Device >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< const Derived, Device > device (Device &device) const
Friends
template<typename OtherDerived >
EIGEN_DEVICE_FUNC const Product< OtherDerived, TriangularViewType > operator* (const MatrixBase< OtherDerived > &lhs, const TriangularViewImpl &rhs)
Additional Inherited Members
Protected Member Functions inherited from Eigen::TriangularBase< TriangularView< MatrixType_, Mode_ > >
void check_coordinates (Index row, Index col) const
void check_coordinates_internal (Index, Index) const
Detailed Description
template<typename MatrixType_, unsigned int Mode_>
class Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense >
Base class for a triangular part in a dense matrix.
This class is an abstract base class of class TriangularView, and objects of type TriangularViewImpl cannot be instantiated. It extends class TriangularView with additional methods which available for dense expressions only.
See also
class TriangularView, MatrixBase::triangularView()
Member Typedef Documentation
Base
template<typename MatrixType_ , unsigned int Mode_> typedef TriangularBase<TriangularViewType> Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense >::Base
DenseMatrixType
template<typename MatrixType_ , unsigned int Mode_> typedef MatrixType::PlainObject Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense >::DenseMatrixType
MatrixType
template<typename MatrixType_ , unsigned int Mode_> typedef MatrixType_ Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense >::MatrixType
PlainObject
template<typename MatrixType_ , unsigned int Mode_> typedef DenseMatrixType Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense >::PlainObject
Scalar
template<typename MatrixType_ , unsigned int Mode_> typedef internal::traits<TriangularViewType>::Scalar Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense >::Scalar
StorageKind
template<typename MatrixType_ , unsigned int Mode_> typedef internal::traits<TriangularViewType>::StorageKind Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense >::StorageKind
TriangularViewType
template<typename MatrixType_ , unsigned int Mode_> typedef TriangularView<MatrixType_, Mode_> Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense >::TriangularViewType
Member Enumeration Documentation
anonymous enum
template<typename MatrixType_ , unsigned int Mode_> anonymous enum
Enumerator
Mode
Flags
 { Mode = Mode_, Flags = internal::traits<TriangularViewType>::Flags };
Member Function Documentation
_assignProduct()
template<typename MatrixType_ , unsigned int Mode_> template<typename ProductType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TriangularViewType& Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense >::_assignProduct (const ProductType & prod, const Scalar & alpha, bool beta)
_solve_impl()
template<typename MatrixType_ , unsigned int Mode_> template<typename RhsType , typename DstType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense >::_solve_impl (const RhsType & rhs, DstType & dst) const inline
{
     if (!internal::is_same_dense(dst, rhs)) dst = rhs;
     this->solveInPlace(dst);
   }
References Eigen::internal::is_same_dense().
coeff()
template<typename MatrixType_ , unsigned int Mode_> EIGEN_DEVICE_FUNC Scalar Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense >::coeff (Index row, Index col) const inline
See also
MatrixBase::coeff()
Warning
the coordinates must fit into the referenced triangular part
{
     Base::check_coordinates_internal(row, col);
     return derived().nestedExpression().coeff(row, col);
   }
References col(), and row().
coeffRef()
template<typename MatrixType_ , unsigned int Mode_> EIGEN_DEVICE_FUNC Scalar& Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense >::coeffRef (Index row, Index col) inline
See also
MatrixBase::coeffRef()
Warning
the coordinates must fit into the referenced triangular part
{
     EIGEN_STATIC_ASSERT_LVALUE(TriangularViewType);
     Base::check_coordinates_internal(row, col);
     return derived().nestedExpression().coeffRef(row, col);
   }
References col(), EIGEN_STATIC_ASSERT_LVALUE, and row().
derived() [1/2]
template<typename MatrixType_ , unsigned int Mode_> EIGEN_DEVICE_FUNC Derived& Eigen::TriangularBase< Derived >::derived inline
 { return *static_cast<Derived*>(this); }
derived() [2/2]
template<typename MatrixType_ , unsigned int Mode_> EIGEN_DEVICE_FUNC const Derived& Eigen::TriangularBase< Derived >::derived inline
 { return *static_cast<const Derived*>(this); }
evalToLazy()
template<typename MatrixType_ , unsigned int Mode_> template<typename DenseDerived > EIGEN_DEVICE_FUNC void Eigen::TriangularBase< Derived >::evalToLazy (typename DenseDerived)
Assigns a triangular or selfadjoint matrix to a dense matrix. If the matrix is triangular, the opposite part is set to zero.
{
   other.derived().resize(this->rows(), this->cols());
   internal::call_triangular_assignment_loop<Derived::Mode,
                                             (int(Derived::Mode) & int(SelfAdjoint)) == 0 /* SetOpposite */>(
       other.derived(), derived().nestedExpression());
 }
fill()
template<typename MatrixType_ , unsigned int Mode_> EIGEN_DEVICE_FUNC void Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense >::fill (const Scalar & value) inline
See also
MatrixBase::fill()
 { setConstant(value); }
References setConstant(), and Eigen::value.
innerStride()
template<typename MatrixType_ , unsigned int Mode_> EIGEN_DEVICE_FUNC Index Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense >::innerStride () const inline
Returns
the inner-stride of the underlying dense matrix
See also
DenseCoeffsBase::innerStride()
 { return derived().nestedExpression().innerStride(); }
lazyAssign() [1/2]
template<typename MatrixType_ , unsigned int Mode_> template<typename OtherDerived > EIGEN_DEPRECATED EIGEN_DEVICE_FUNC void Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense >::lazyAssign (const MatrixBase< OtherDerived > & other)
Deprecated:
lazyAssign() [2/2]
template<typename MatrixType_ , unsigned int Mode_> template<typename OtherDerived > EIGEN_DEPRECATED EIGEN_DEVICE_FUNC void Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense >::lazyAssign (const TriangularBase< OtherDerived > & other)
Deprecated:
operator*()
template<typename MatrixType_ , unsigned int Mode_> template<typename OtherDerived > EIGEN_DEVICE_FUNC const Product<TriangularViewType, OtherDerived> Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense >::operator* (const MatrixBase< OtherDerived > & rhs) const inline
Efficient triangular matrix times vector/matrix product
{
     return Product<TriangularViewType, OtherDerived>(derived(), rhs.derived());
   }
operator*=()
template<typename MatrixType_ , unsigned int Mode_> EIGEN_DEVICE_FUNC TriangularViewType& Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense >::operator*= (const typename internal::traits< MatrixType >::Scalar & other) inline
See also
MatrixBase::operator*=()
{
     return *this = derived().nestedExpression() * other;
   }
References Eigen::TriangularView< MatrixType_, Mode_ >::nestedExpression().
operator+=()
template<typename MatrixType_ , unsigned int Mode_> template<typename Other > EIGEN_DEVICE_FUNC TriangularViewType& Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense >::operator+= (const DenseBase< Other > & other) inline
See also
MatrixBase::operator+=()
{
     internal::call_assignment_no_alias(derived(), other.derived(),
                                        internal::add_assign_op<Scalar, typename Other::Scalar>());
     return derived();
   }
References Eigen::internal::call_assignment_no_alias().
operator-=()
template<typename MatrixType_ , unsigned int Mode_> template<typename Other > EIGEN_DEVICE_FUNC TriangularViewType& Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense >::operator-= (const DenseBase< Other > & other) inline
See also
MatrixBase::operator-=()
{
     internal::call_assignment_no_alias(derived(), other.derived(),
                                        internal::sub_assign_op<Scalar, typename Other::Scalar>());
     return derived();
   }
References Eigen::internal::call_assignment_no_alias().
operator/=()
template<typename MatrixType_ , unsigned int Mode_> EIGEN_DEVICE_FUNC TriangularViewType& Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense >::operator/= (const typename internal::traits< MatrixType >::Scalar & other) inline
See also
DenseBase::operator/=()
{
     return *this = derived().nestedExpression() / other;
   }
References Eigen::TriangularView< MatrixType_, Mode_ >::nestedExpression().
operator=() [1/3]
template<typename MatrixType_ , unsigned int Mode_> template<typename OtherDerived > EIGEN_DEVICE_FUNC TriangularViewType& Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense >::operator= (const MatrixBase< OtherDerived > & other)
Shortcut for
*this = other.other.triangularView<(*this)::Mode>()
operator=() [2/3]
template<typename MatrixType_ , unsigned int Mode_> template<typename OtherDerived > EIGEN_DEVICE_FUNC TriangularViewType& Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense >::operator= (const TriangularBase< OtherDerived > & other)
Assigns a triangular matrix to a triangular part of a dense matrix
operator=() [3/3]
template<typename MatrixType_ , unsigned int Mode_> EIGEN_DEVICE_FUNC TriangularViewType& Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense >::operator= (const TriangularViewImpl< MatrixType_, Mode_, Dense > & other) inline
{
     return *this = other.derived().nestedExpression();
   }
outerStride()
template<typename MatrixType_ , unsigned int Mode_> EIGEN_DEVICE_FUNC Index Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense >::outerStride () const inline
Returns
the outer-stride of the underlying dense matrix
See also
DenseCoeffsBase::outerStride()
 { return derived().nestedExpression().outerStride(); }
setConstant()
template<typename MatrixType_ , unsigned int Mode_> EIGEN_DEVICE_FUNC TriangularViewType& Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense >::setConstant (const Scalar & value) inline
See also
MatrixBase::setConstant()
{
     return *this = MatrixType::Constant(derived().rows(), derived().cols(), value);
   }
References cols, rows, and Eigen::value.
setOnes()
template<typename MatrixType_ , unsigned int Mode_> EIGEN_DEVICE_FUNC TriangularViewType& Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense >::setOnes () inline
See also
MatrixBase::setOnes()
 { return setConstant(Scalar(1)); }
References setConstant().
setZero()
template<typename MatrixType_ , unsigned int Mode_> EIGEN_DEVICE_FUNC TriangularViewType& Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense >::setZero () inline
See also
MatrixBase::setZero()
 { return setConstant(Scalar(0)); }
References setConstant().
solve()
template<typename MatrixType_ , unsigned int Mode_> template<int Side, typename Other > const internal::triangular_solve_retval<Side, TriangularViewType, Other> Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense >::solve (const MatrixBase< Other > & other) const inline
Returns
the product of the inverse of *this with other, *this being triangular.
This function computes the inverse-matrix matrix product inverse(*this) * other if Side==OnTheLeft (the default), or the right-inverse-multiply other * inverse(*this) if Side==OnTheRight.
Note that the template parameter Side can be omitted, in which case Side==OnTheLeft
The matrix *this must be triangular and invertible (i.e., all the coefficients of the diagonal must be non zero). It works as a forward (resp. backward) substitution if *this is an upper (resp. lower) triangular matrix.
Example:
Matrix3d m = Matrix3d::Zero();
m.triangularView<Eigen::Upper>().setOnes();
cout << "Here is the matrix m:\n" << m << endl;
Matrix3d n = Matrix3d::Ones();
n.triangularView<Eigen::Lower>() *= 2;
cout << "Here is the matrix n:\n" << n << endl;
cout << "And now here is m.inverse()*n, taking advantage of the fact that"
        " m is upper-triangular:\n"
     << m.triangularView<Eigen::Upper>().solve(n) << endl;
cout << "And this is n*m.inverse():\n" << m.triangularView<Eigen::Upper>().solve<Eigen::OnTheRight>(n);
Output:
This function returns an expression of the inverse-multiply and can works in-place if it is assigned to the same matrix or vector other.
For users coming from BLAS, this function (and more specifically solveInPlace()) offer all the operations supported by the *TRSV and *TRSM BLAS routines.
See also
TriangularView::solveInPlace()
solveInPlace() [1/2]
template<typename MatrixType_ , unsigned int Mode_> template<int Side, typename OtherDerived > EIGEN_DEVICE_FUNC void Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense >::solveInPlace (const MatrixBase< OtherDerived > & other) const
"in-place" version of TriangularView::solve() where the result is written in other
Warning
The parameter is only marked 'const' to make the C++ compiler accept a temporary expression here. This function will const_cast it, so constness isn't honored here.
Note that the template parameter Side can be omitted, in which case Side==OnTheLeft
See TriangularView:solve() for the details.
solveInPlace() [2/2]
template<typename MatrixType_ , unsigned int Mode_> template<typename OtherDerived > EIGEN_DEVICE_FUNC void Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense >::solveInPlace (const MatrixBase< OtherDerived > & other) const inline
{
     return solveInPlace<OnTheLeft>(other);
   }
swap() [1/2]
template<typename MatrixType_ , unsigned int Mode_> template<typename OtherDerived > EIGEN_DEPRECATED EIGEN_DEVICE_FUNC void Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense >::swap (MatrixBase< OtherDerived > const & other) inline
Shortcut for
(*this).swap(other.triangularView<(*this)::Mode>())
Deprecated:
{
     EIGEN_STATIC_ASSERT_LVALUE(OtherDerived);
     call_assignment(derived(), other.const_cast_derived(), internal::swap_assign_op<Scalar>());
   }
References Eigen::internal::call_assignment(), and EIGEN_STATIC_ASSERT_LVALUE.
swap() [2/2]
template<typename MatrixType_ , unsigned int Mode_> template<typename OtherDerived > EIGEN_DEVICE_FUNC void Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense >::swap (TriangularBase< OtherDerived > const & other) inline
Swaps the coefficients of the common triangular parts of two matrices
   {
     EIGEN_STATIC_ASSERT_LVALUE(OtherDerived);
     call_assignment(derived(), other.const_cast_derived(), internal::swap_assign_op<Scalar>());
   }
References Eigen::internal::call_assignment(), Eigen::EigenBase< Derived >::const_cast_derived(), and EIGEN_STATIC_ASSERT_LVALUE.
Friends And Related Function Documentation
operator*
template<typename MatrixType_ , unsigned int Mode_> template<typename OtherDerived > EIGEN_DEVICE_FUNC const Product<OtherDerived, TriangularViewType> operator* (const MatrixBase< OtherDerived > & lhs, const TriangularViewImpl< MatrixType_, Mode_, Dense > & rhs) friend
Efficient vector/matrix times triangular matrix product
{
     return Product<OtherDerived, TriangularViewType>(lhs.derived(), rhs.derived());
   }
The documentation for this class was generated from the following file:
TriangularMatrix.h