MercuryDPM: oomph::TwoDimensionalPMLHelper Namespace Reference
oomph::TwoDimensionalPMLHelper Namespace Reference
Functions
bool sorter_right_boundary (Node *nod_i_pt, Node *nod_j_pt)
helper function for sorting the right boundary nodes
bool sorter_top_boundary (Node *nod_i_pt, Node *nod_j_pt)
helper function for sorting the top boundary nodes
bool sorter_left_boundary (Node *nod_i_pt, Node *nod_j_pt)
helper function for sorting the left boundary nodes
bool sorter_bottom_boundary (Node *nod_i_pt, Node *nod_j_pt)
helper function for sorting the bottom boundary nodes
template<class ASSOCIATED_PML_QUAD_ELEMENT >
Mesh * create_right_pml_mesh (Mesh *bulk_mesh_pt, const unsigned &right_boundary_id, const unsigned &n_x_right_pml, const double &width_x_right_pml, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
template<class ASSOCIATED_PML_QUAD_ELEMENT >
Mesh * create_top_pml_mesh (Mesh *bulk_mesh_pt, const unsigned &top_boundary_id, const unsigned &n_y_top_pml, const double &width_y_top_pml, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
template<class ASSOCIATED_PML_QUAD_ELEMENT >
Mesh * create_left_pml_mesh (Mesh *bulk_mesh_pt, const unsigned &left_boundary_id, const unsigned &n_x_left_pml, const double &width_x_left_pml, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
template<class ASSOCIATED_PML_QUAD_ELEMENT >
Mesh * create_bottom_pml_mesh (Mesh *bulk_mesh_pt, const unsigned &bottom_boundary_id, const unsigned &n_y_bottom_pml, const double &width_y_bottom_pml, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
template<class ASSOCIATED_PML_QUAD_ELEMENT >
Mesh * create_top_right_pml_mesh (Mesh *pml_right_mesh_pt, Mesh *pml_top_mesh_pt, Mesh *bulk_mesh_pt, const unsigned &right_boundary_id, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
template<class ASSOCIATED_PML_QUAD_ELEMENT >
Mesh * create_bottom_right_pml_mesh (Mesh *pml_right_mesh_pt, Mesh *pml_bottom_mesh_pt, Mesh *bulk_mesh_pt, const unsigned &right_boundary_id, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
template<class ASSOCIATED_PML_QUAD_ELEMENT >
Mesh * create_top_left_pml_mesh (Mesh *pml_left_mesh_pt, Mesh *pml_top_mesh_pt, Mesh *bulk_mesh_pt, const unsigned &left_boundary_id, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
template<class ASSOCIATED_PML_QUAD_ELEMENT >
Mesh * create_bottom_left_pml_mesh (Mesh *pml_left_mesh_pt, Mesh *pml_bottom_mesh_pt, Mesh *bulk_mesh_pt, const unsigned &left_boundary_id, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Detailed Description
Namespace with functions that allow the construction of PML layers on axis aligned boundaries
/////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////// All helper routines for 2D bulk boundary mesh usage in order to generate PML meshes aligned to the main mesh
///////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////// All helper routines for 2D bulk boundary mesh usage in order to generate PML meshes aligned to the main mesh
Function Documentation
create_bottom_left_pml_mesh()
template<class ASSOCIATED_PML_QUAD_ELEMENT > Mesh* oomph::TwoDimensionalPMLHelper::create_bottom_left_pml_mesh (Mesh * pml_left_mesh_pt, Mesh * pml_bottom_mesh_pt, Mesh * bulk_mesh_pt, const unsigned & left_boundary_id, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
"Constructor" for PML bottom left corner mesh, aligned with the existing PML meshes
Relevant boundary id's to be used in construction Parent id refers to already existing PML meshes
Sort them from lowest to highest (in y coordinate) sorter_right_boundary is still functional, as the sorting is performed by the same criterion
Number of elements and boundary nodes to be acted upon during construction are extracted from the 'parent' PML meshes
Specific PML sizes needed, taken directly from physical domain and existing PML meshes
The enabling must be perfromed in both x- and y-directions as this is a corner PML mesh
Return the finalized mesh, with PML enabled and boundary conditions added
     {
       unsigned parent_boundary_x_id = 0;
       unsigned parent_boundary_y_id = 3;
       // Current id refers to the mesh that is to be constructed
       unsigned current_boundary_x_id = 2;
       unsigned current_boundary_y_id = 1;
       // Look at the left boundary of the triangular mesh
       unsigned n_left_boundary_node =
         bulk_mesh_pt->nboundary_node(left_boundary_id);
       // Create a vector of ordered boundary nodes
       Vector<Node*> ordered_left_boundary_node_pt(n_left_boundary_node);
       // Fill the vector with the nodes on the respective boundary
       for (unsigned n = 0; n < n_left_boundary_node; n++)
       {
         ordered_left_boundary_node_pt[n] =
           bulk_mesh_pt->boundary_node_pt(left_boundary_id, n);
       }
       std::sort(ordered_left_boundary_node_pt.begin(),
                 ordered_left_boundary_node_pt.end(),
                 sorter_right_boundary);
       unsigned n_x_left_pml =
         pml_left_mesh_pt->nboundary_element(parent_boundary_x_id);
       unsigned n_y_bottom_pml =
         pml_bottom_mesh_pt->nboundary_element(parent_boundary_y_id);
       double l_pml_left_x_start =
         pml_left_mesh_pt->boundary_node_pt(parent_boundary_x_id, 0)->x(0);
       double l_pml_left_x_end =
         ordered_left_boundary_node_pt[n_left_boundary_node - 1]->x(0);
       double l_pml_bottom_y_start =
         pml_bottom_mesh_pt->boundary_node_pt(parent_boundary_y_id, 0)->x(1);
       double l_pml_bottom_y_end = ordered_left_boundary_node_pt[0]->x(1);
       // Create the mesh to be designated to the PML
       Mesh* pml_bottom_left_mesh_pt = 0;
       // Build the bottom left corner PML mesh
       pml_bottom_left_mesh_pt =
         new PMLCornerQuadMesh<ASSOCIATED_PML_QUAD_ELEMENT>(
           pml_left_mesh_pt,
           pml_bottom_mesh_pt,
           bulk_mesh_pt,
           ordered_left_boundary_node_pt[0],
           parent_boundary_x_id,
           parent_boundary_y_id,
           current_boundary_x_id,
           current_boundary_y_id,
           n_x_left_pml,
           n_y_bottom_pml,
           l_pml_left_x_start,
           l_pml_left_x_end,
           l_pml_bottom_y_start,
           l_pml_bottom_y_end,
           time_stepper_pt);
       // Enable PML damping on the entire mesh
       unsigned n_element_pml_bottom_left = pml_bottom_left_mesh_pt->nelement();
       for (unsigned e = 0; e < n_element_pml_bottom_left; e++)
       {
         // Upcast
         PMLElementBase<2>* el_pt = dynamic_cast<PMLElementBase<2>*>(
           pml_bottom_left_mesh_pt->element_pt(e));
         el_pt->enable_pml(0, l_pml_left_x_end, l_pml_left_x_start);
         el_pt->enable_pml(1, l_pml_bottom_y_end, l_pml_bottom_y_start);
       }
       // Get the values to be pinned from the first element (which we
       // assume exists!)
       PMLElementBase<2>* el_pt = dynamic_cast<PMLElementBase<2>*>(
         pml_bottom_left_mesh_pt->element_pt(0));
       Vector<unsigned> values_to_pin;
       el_pt->values_to_be_pinned_on_outer_pml_boundary(values_to_pin);
       unsigned npin = values_to_pin.size();
       // Exterior boundary needs to be set to Dirichlet 0
       // for both real and imaginary parts of all fields
       // in the problem
       unsigned n_bound_pml_bottom_left = pml_bottom_left_mesh_pt->nboundary();
       for (unsigned b = 0; b < n_bound_pml_bottom_left; b++)
       {
         unsigned n_node = pml_bottom_left_mesh_pt->nboundary_node(b);
         for (unsigned n = 0; n < n_node; n++)
         {
           Node* nod_pt = pml_bottom_left_mesh_pt->boundary_node_pt(b, n);
           if ((b == 0) || (b == 3))
           {
             for (unsigned j = 0; j < npin; j++)
             {
               unsigned j_val = values_to_pin[j];
               nod_pt->pin(j_val);
               nod_pt->set_value(j_val, 0.0);
             }
           }
         }
       }
       return pml_bottom_left_mesh_pt;
     }
References b, oomph::Mesh::boundary_node_pt(), e(), oomph::Mesh::element_pt(), oomph::PMLElementBase< DIM >::enable_pml(), j, n, oomph::Mesh::nboundary(), oomph::Mesh::nboundary_element(), oomph::Mesh::nboundary_node(), oomph::Mesh::nelement(), oomph::Data::pin(), oomph::Data::set_value(), sorter_right_boundary(), oomph::PMLElementBase< DIM >::values_to_be_pinned_on_outer_pml_boundary(), and oomph::Node::x().
Referenced by PMLHelmholtzMGProblem< ELEMENT >::create_pml_meshes(), PMLProblem< ELEMENT >::create_pml_meshes(), ElasticAnnulusProblem< ELASTICITY_ELEMENT >::create_pml_meshes(), and oomph::RefineableQuadMeshWithMovingCylinder< ELEMENT >::RefineableQuadMeshWithMovingCylinder().
create_bottom_pml_mesh()
template<class ASSOCIATED_PML_QUAD_ELEMENT > Mesh* oomph::TwoDimensionalPMLHelper::create_bottom_pml_mesh (Mesh * bulk_mesh_pt, const unsigned & bottom_boundary_id, const unsigned & n_y_bottom_pml, const double & width_y_bottom_pml, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
"Constructor" for PML mesh,aligned with the bottom physical domain boundary
PML layer width subtracted from the bulk mesh lower boundary coordinate
Return the finalized mesh, with PML enabled and boundary conditions added
     {
       // Look at the bottom boundary of the triangular mesh
       unsigned n_bottom_boundary_node =
         bulk_mesh_pt->nboundary_node(bottom_boundary_id);
       // Create a vector of ordered boundary nodes
       Vector<Node*> ordered_bottom_boundary_node_pt(n_bottom_boundary_node);
       // Fill the vector with the nodes on the respective boundary
       for (unsigned n = 0; n < n_bottom_boundary_node; n++)
       {
         ordered_bottom_boundary_node_pt[n] =
           bulk_mesh_pt->boundary_node_pt(bottom_boundary_id, n);
       }
       // Sort them from highest to lowest (in x coordinate)
       std::sort(ordered_bottom_boundary_node_pt.begin(),
                 ordered_bottom_boundary_node_pt.end(),
                 sorter_bottom_boundary);
       // The number of elements in y is taken from the triangular mesh
       unsigned n_x_bottom_pml =
         bulk_mesh_pt->nboundary_element(bottom_boundary_id);
       // Specific PML sizes needed, taken directly from physical domain
       double l_pml_bottom_x_start =
         ordered_bottom_boundary_node_pt[n_bottom_boundary_node - 1]->x(0);
       double l_pml_bottom_x_end = ordered_bottom_boundary_node_pt[0]->x(0);
       double l_pml_bottom_y_start =
         -width_y_bottom_pml + ordered_bottom_boundary_node_pt[0]->x(1);
       double l_pml_bottom_y_end = ordered_bottom_boundary_node_pt[0]->x(1);
       unsigned bottom_quadPML_boundary_id = 2;
       // Create the mesh to be designated to the PML
       Mesh* pml_bottom_mesh_pt = 0;
       // Build the bottom PML mesh
       pml_bottom_mesh_pt =
         new PMLQuadMesh<ASSOCIATED_PML_QUAD_ELEMENT>(bulk_mesh_pt,
                                                      bottom_boundary_id,
                                                      bottom_quadPML_boundary_id,
                                                      n_x_bottom_pml,
                                                      n_y_bottom_pml,
                                                      l_pml_bottom_x_start,
                                                      l_pml_bottom_x_end,
                                                      l_pml_bottom_y_start,
                                                      l_pml_bottom_y_end,
                                                      time_stepper_pt);
       // Enable PML damping on the entire mesh
       unsigned n_element_pml_bottom = pml_bottom_mesh_pt->nelement();
       for (unsigned e = 0; e < n_element_pml_bottom; e++)
       {
         // Upcast
         PMLElementBase<2>* el_pt =
           dynamic_cast<PMLElementBase<2>*>(pml_bottom_mesh_pt->element_pt(e));
         el_pt->enable_pml(1, l_pml_bottom_y_end, l_pml_bottom_y_start);
       }
       // Get the values to be pinned from the first element (which we
       // assume exists!)
       PMLElementBase<2>* el_pt =
         dynamic_cast<PMLElementBase<2>*>(pml_bottom_mesh_pt->element_pt(0));
       Vector<unsigned> values_to_pin;
       el_pt->values_to_be_pinned_on_outer_pml_boundary(values_to_pin);
       unsigned npin = values_to_pin.size();
       // Exterior boundary needs to be set to Dirichlet 0
       // for both real and imaginary parts of all fields
       // in the problem
       unsigned n_bound_pml_bottom = pml_bottom_mesh_pt->nboundary();
       for (unsigned b = 0; b < n_bound_pml_bottom; b++)
       {
         unsigned n_node = pml_bottom_mesh_pt->nboundary_node(b);
         for (unsigned n = 0; n < n_node; n++)
         {
           Node* nod_pt = pml_bottom_mesh_pt->boundary_node_pt(b, n);
           if (b == 0)
           {
             for (unsigned j = 0; j < npin; j++)
             {
               unsigned j_val = values_to_pin[j];
               nod_pt->pin(j_val);
               nod_pt->set_value(j_val, 0.0);
             }
           }
         }
       }
       return pml_bottom_mesh_pt;
     }
References b, oomph::Mesh::boundary_node_pt(), e(), oomph::Mesh::element_pt(), oomph::PMLElementBase< DIM >::enable_pml(), j, n, oomph::Mesh::nboundary(), oomph::Mesh::nboundary_element(), oomph::Mesh::nboundary_node(), oomph::Mesh::nelement(), oomph::Data::pin(), oomph::Data::set_value(), sorter_bottom_boundary(), and oomph::PMLElementBase< DIM >::values_to_be_pinned_on_outer_pml_boundary().
Referenced by PMLHelmholtzMGProblem< ELEMENT >::create_pml_meshes(), PMLFourierDecomposedHelmholtzProblem< ELEMENT >::create_pml_meshes(), PMLProblem< ELEMENT >::create_pml_meshes(), and ElasticAnnulusProblem< ELASTICITY_ELEMENT >::create_pml_meshes().
create_bottom_right_pml_mesh()
template<class ASSOCIATED_PML_QUAD_ELEMENT > Mesh* oomph::TwoDimensionalPMLHelper::create_bottom_right_pml_mesh (Mesh * pml_right_mesh_pt, Mesh * pml_bottom_mesh_pt, Mesh * bulk_mesh_pt, const unsigned & right_boundary_id, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
"Constructor" for PML bottom right corner mesh, aligned with the existing PML meshes
Relevant boundary id's to be used in construction Parent id refers to already existing PML meshes
Number of elements and boundary nodes to be acted upon during construction are extracted from the 'parent' PML meshes
Specific PML sizes needed, taken directly from physical domain and existing PML meshes
The enabling must be perfromed in both x- and y-directions as this is a corner PML mesh
Return the finalized mesh, with PML enabled and boundary conditions added
     {
       unsigned parent_boundary_x_id = 0;
       unsigned parent_boundary_y_id = 1;
       // Current id refers to the mesh that is to be constructed
       unsigned current_boundary_x_id = 2;
       unsigned current_boundary_y_id = 3;
       // Look at the right boundary of the triangular mesh
       unsigned n_right_boundary_node =
         bulk_mesh_pt->nboundary_node(right_boundary_id);
       // Create a vector of ordered boundary nodes
       Vector<Node*> ordered_right_boundary_node_pt(n_right_boundary_node);
       // Fill the vector with the nodes on the respective boundary
       for (unsigned n = 0; n < n_right_boundary_node; n++)
       {
         ordered_right_boundary_node_pt[n] =
           bulk_mesh_pt->boundary_node_pt(right_boundary_id, n);
       }
       // Sort them from lowest to highest (in y coordinate)
       std::sort(ordered_right_boundary_node_pt.begin(),
                 ordered_right_boundary_node_pt.end(),
                 sorter_right_boundary);
       unsigned n_x_right_pml =
         pml_right_mesh_pt->nboundary_element(parent_boundary_x_id);
       unsigned n_y_bottom_pml =
         pml_bottom_mesh_pt->nboundary_element(parent_boundary_y_id);
       unsigned n_x_boundary_nodes =
         pml_right_mesh_pt->nboundary_node(parent_boundary_x_id);
       double l_pml_right_x_start = ordered_right_boundary_node_pt[0]->x(0);
       double l_pml_right_x_end =
         pml_right_mesh_pt
           ->boundary_node_pt(parent_boundary_x_id, n_x_boundary_nodes - 1)
           ->x(0);
       double l_pml_bottom_y_start =
         pml_bottom_mesh_pt->boundary_node_pt(parent_boundary_y_id, 0)->x(1);
       double l_pml_bottom_y_end = ordered_right_boundary_node_pt[0]->x(1);
       // Create the mesh to be designated to the PML
       Mesh* pml_bottom_right_mesh_pt = 0;
       // Build the bottom right corner PML mesh
       pml_bottom_right_mesh_pt =
         new PMLCornerQuadMesh<ASSOCIATED_PML_QUAD_ELEMENT>(
           pml_right_mesh_pt,
           pml_bottom_mesh_pt,
           bulk_mesh_pt,
           ordered_right_boundary_node_pt[0],
           parent_boundary_x_id,
           parent_boundary_y_id,
           current_boundary_x_id,
           current_boundary_y_id,
           n_x_right_pml,
           n_y_bottom_pml,
           l_pml_right_x_start,
           l_pml_right_x_end,
           l_pml_bottom_y_start,
           l_pml_bottom_y_end,
           time_stepper_pt);
       // Enable PML damping on the entire mesh
       unsigned n_element_pml_bottom_right =
         pml_bottom_right_mesh_pt->nelement();
       for (unsigned e = 0; e < n_element_pml_bottom_right; e++)
       {
         // Upcast
         PMLElementBase<2>* el_pt = dynamic_cast<PMLElementBase<2>*>(
           pml_bottom_right_mesh_pt->element_pt(e));
         el_pt->enable_pml(0, l_pml_right_x_start, l_pml_right_x_end);
         el_pt->enable_pml(1, l_pml_bottom_y_end, l_pml_bottom_y_start);
       }
       // Get the values to be pinned from the first element (which we
       // assume exists!)
       PMLElementBase<2>* el_pt = dynamic_cast<PMLElementBase<2>*>(
         pml_bottom_right_mesh_pt->element_pt(0));
       Vector<unsigned> values_to_pin;
       el_pt->values_to_be_pinned_on_outer_pml_boundary(values_to_pin);
       unsigned npin = values_to_pin.size();
       // Exterior boundary needs to be set to Dirichlet 0
       // for both real and imaginary parts of all fields
       // in the problem
       unsigned n_bound_pml_bottom_right = pml_bottom_right_mesh_pt->nboundary();
       for (unsigned b = 0; b < n_bound_pml_bottom_right; b++)
       {
         unsigned n_node = pml_bottom_right_mesh_pt->nboundary_node(b);
         for (unsigned n = 0; n < n_node; n++)
         {
           Node* nod_pt = pml_bottom_right_mesh_pt->boundary_node_pt(b, n);
           if ((b == 0) || (b == 1))
           {
             for (unsigned j = 0; j < npin; j++)
             {
               unsigned j_val = values_to_pin[j];
               nod_pt->pin(j_val);
               nod_pt->set_value(j_val, 0.0);
             }
           }
         }
       }
       return pml_bottom_right_mesh_pt;
     }
References b, oomph::Mesh::boundary_node_pt(), e(), oomph::Mesh::element_pt(), oomph::PMLElementBase< DIM >::enable_pml(), j, n, oomph::Mesh::nboundary(), oomph::Mesh::nboundary_element(), oomph::Mesh::nboundary_node(), oomph::Mesh::nelement(), oomph::Data::pin(), oomph::Data::set_value(), sorter_right_boundary(), oomph::PMLElementBase< DIM >::values_to_be_pinned_on_outer_pml_boundary(), and oomph::Node::x().
Referenced by PMLHelmholtzMGProblem< ELEMENT >::create_pml_meshes(), PMLFourierDecomposedHelmholtzProblem< ELEMENT >::create_pml_meshes(), PMLProblem< ELEMENT >::create_pml_meshes(), ElasticAnnulusProblem< ELASTICITY_ELEMENT >::create_pml_meshes(), and oomph::RefineableQuadMeshWithMovingCylinder< ELEMENT >::RefineableQuadMeshWithMovingCylinder().
create_left_pml_mesh()
template<class ASSOCIATED_PML_QUAD_ELEMENT > Mesh* oomph::TwoDimensionalPMLHelper::create_left_pml_mesh (Mesh * bulk_mesh_pt, const unsigned & left_boundary_id, const unsigned & n_x_left_pml, const double & width_x_left_pml, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
"Constructor" for PML mesh, aligned with the left physical domain boundary
PML layer width subtracted from left bulk mesh coordinate
Return the finalized mesh, with PML enabled and boundary conditions added
     {
       // Look at the left boundary of the triangular mesh
       unsigned n_left_boundary_node =
         bulk_mesh_pt->nboundary_node(left_boundary_id);
       // Create a vector of ordered boundary nodes
       Vector<Node*> ordered_left_boundary_node_pt(n_left_boundary_node);
       // Fill the vector with the nodes on the respective boundary
       for (unsigned n = 0; n < n_left_boundary_node; n++)
       {
         ordered_left_boundary_node_pt[n] =
           bulk_mesh_pt->boundary_node_pt(left_boundary_id, n);
       }
       // Sort them from lowest to highest (in y coordinate)
       std::sort(ordered_left_boundary_node_pt.begin(),
                 ordered_left_boundary_node_pt.end(),
                 sorter_left_boundary);
       // The number of elements in y is taken from the triangular mesh
       unsigned n_y_left_pml = bulk_mesh_pt->nboundary_element(left_boundary_id);
       // Specific PML sizes needed, taken directly from physical domain
       double l_pml_left_x_start =
         -width_x_left_pml +
         ordered_left_boundary_node_pt[n_left_boundary_node - 1]->x(0);
       double l_pml_left_x_end =
         ordered_left_boundary_node_pt[n_left_boundary_node - 1]->x(0);
       double l_pml_left_y_start =
         ordered_left_boundary_node_pt[n_left_boundary_node - 1]->x(1);
       double l_pml_left_y_end = ordered_left_boundary_node_pt[0]->x(1);
       unsigned left_quadPML_boundary_id = 1;
       // Create the mesh to be designated to the PML
       Mesh* pml_left_mesh_pt = 0;
       // Build the left PML mesh
       pml_left_mesh_pt =
         new PMLQuadMesh<ASSOCIATED_PML_QUAD_ELEMENT>(bulk_mesh_pt,
                                                      left_boundary_id,
                                                      left_quadPML_boundary_id,
                                                      n_x_left_pml,
                                                      n_y_left_pml,
                                                      l_pml_left_x_start,
                                                      l_pml_left_x_end,
                                                      l_pml_left_y_start,
                                                      l_pml_left_y_end,
                                                      time_stepper_pt);
       // Enable PML damping on the entire mesh
       unsigned n_element_pml_left = pml_left_mesh_pt->nelement();
       for (unsigned e = 0; e < n_element_pml_left; e++)
       {
         // Upcast
         PMLElementBase<2>* el_pt =
           dynamic_cast<PMLElementBase<2>*>(pml_left_mesh_pt->element_pt(e));
         el_pt->enable_pml(0, l_pml_left_x_end, l_pml_left_x_start);
       }
       // Get the values to be pinned from the first element (which we
       // assume exists!)
       PMLElementBase<2>* el_pt =
         dynamic_cast<PMLElementBase<2>*>(pml_left_mesh_pt->element_pt(0));
       Vector<unsigned> values_to_pin;
       el_pt->values_to_be_pinned_on_outer_pml_boundary(values_to_pin);
       unsigned npin = values_to_pin.size();
       // Exterior boundary needs to be set to Dirichlet 0
       // for both real and imaginary parts of all fields
       // in the problem
       unsigned n_bound_pml_left = pml_left_mesh_pt->nboundary();
       for (unsigned b = 0; b < n_bound_pml_left; b++)
       {
         unsigned n_node = pml_left_mesh_pt->nboundary_node(b);
         for (unsigned n = 0; n < n_node; n++)
         {
           Node* nod_pt = pml_left_mesh_pt->boundary_node_pt(b, n);
           if (b == 3)
           {
             for (unsigned j = 0; j < npin; j++)
             {
               unsigned j_val = values_to_pin[j];
               nod_pt->pin(j_val);
               nod_pt->set_value(j_val, 0.0);
             }
           }
         }
       }
       return pml_left_mesh_pt;
     }
References b, oomph::Mesh::boundary_node_pt(), e(), oomph::Mesh::element_pt(), oomph::PMLElementBase< DIM >::enable_pml(), j, n, oomph::Mesh::nboundary(), oomph::Mesh::nboundary_element(), oomph::Mesh::nboundary_node(), oomph::Mesh::nelement(), oomph::Data::pin(), oomph::Data::set_value(), sorter_left_boundary(), and oomph::PMLElementBase< DIM >::values_to_be_pinned_on_outer_pml_boundary().
Referenced by PMLHelmholtzMGProblem< ELEMENT >::create_pml_meshes(), PMLProblem< ELEMENT >::create_pml_meshes(), and ElasticAnnulusProblem< ELASTICITY_ELEMENT >::create_pml_meshes().
create_right_pml_mesh()
template<class ASSOCIATED_PML_QUAD_ELEMENT > Mesh* oomph::TwoDimensionalPMLHelper::create_right_pml_mesh (Mesh * bulk_mesh_pt, const unsigned & right_boundary_id, const unsigned & n_x_right_pml, const double & width_x_right_pml, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
"Constructor" for PML mesh,aligned with the right physical domain boundary
PML layer with added to the bulk mesh coordinate
Return the finalized mesh, with PML enabled and boundary conditions added
     {
       // Look at the right boundary of the triangular mesh
       unsigned n_right_boundary_node =
         bulk_mesh_pt->nboundary_node(right_boundary_id);
       // Create a vector of ordered boundary nodes
       Vector<Node*> ordered_right_boundary_node_pt(n_right_boundary_node);
       // Fill the vector with the nodes on the respective boundary
       for (unsigned n = 0; n < n_right_boundary_node; n++)
       {
         ordered_right_boundary_node_pt[n] =
           bulk_mesh_pt->boundary_node_pt(right_boundary_id, n);
       }
       // Sort them from lowest to highest (in y coordinate)
       std::sort(ordered_right_boundary_node_pt.begin(),
                 ordered_right_boundary_node_pt.end(),
                 sorter_right_boundary);
       // The number of elements in y is taken from the triangular mesh
       unsigned n_y_right_pml =
         bulk_mesh_pt->nboundary_element(right_boundary_id);
       // Specific PML sizes needed, taken directly from physical domain
       double l_pml_right_x_start = ordered_right_boundary_node_pt[0]->x(0);
       double l_pml_right_x_end =
         width_x_right_pml + ordered_right_boundary_node_pt[0]->x(0);
       double l_pml_right_y_start = ordered_right_boundary_node_pt[0]->x(1);
       double l_pml_right_y_end =
         ordered_right_boundary_node_pt[n_right_boundary_node - 1]->x(1);
       // Rectangular boundary id to be merged with triangular mesh
       unsigned right_quadPML_boundary_id = 3;
       // Create the mesh to be designated to the PML
       Mesh* pml_right_mesh_pt = 0;
       // Build the right one
       pml_right_mesh_pt =
         new PMLQuadMesh<ASSOCIATED_PML_QUAD_ELEMENT>(bulk_mesh_pt,
                                                      right_boundary_id,
                                                      right_quadPML_boundary_id,
                                                      n_x_right_pml,
                                                      n_y_right_pml,
                                                      l_pml_right_x_start,
                                                      l_pml_right_x_end,
                                                      l_pml_right_y_start,
                                                      l_pml_right_y_end,
                                                      time_stepper_pt);
       // Enable PML damping on the entire mesh
       unsigned n_element_pml_right = pml_right_mesh_pt->nelement();
       for (unsigned e = 0; e < n_element_pml_right; e++)
       {
         // Upcast
         PMLElementBase<2>* el_pt =
           dynamic_cast<PMLElementBase<2>*>(pml_right_mesh_pt->element_pt(e));
         el_pt->enable_pml(0, l_pml_right_x_start, l_pml_right_x_end);
       }
       // Get the values to be pinned from the first element (which we
       // assume exists!)
       PMLElementBase<2>* el_pt =
         dynamic_cast<PMLElementBase<2>*>(pml_right_mesh_pt->element_pt(0));
       Vector<unsigned> values_to_pin;
       el_pt->values_to_be_pinned_on_outer_pml_boundary(values_to_pin);
       unsigned npin = values_to_pin.size();
       // Exterior boundary needs to be set to Dirichlet 0
       // in both real and imaginary parts
       unsigned n_bound_pml_right = pml_right_mesh_pt->nboundary();
       for (unsigned b = 0; b < n_bound_pml_right; b++)
       {
         unsigned n_node = pml_right_mesh_pt->nboundary_node(b);
         for (unsigned n = 0; n < n_node; n++)
         {
           Node* nod_pt = pml_right_mesh_pt->boundary_node_pt(b, n);
           if (b == 1)
           {
             for (unsigned j = 0; j < npin; j++)
             {
               unsigned j_val = values_to_pin[j];
               nod_pt->pin(j_val);
               nod_pt->set_value(j_val, 0.0);
             }
           }
         }
       }
       return pml_right_mesh_pt;
     }
References b, oomph::Mesh::boundary_node_pt(), e(), oomph::Mesh::element_pt(), oomph::PMLElementBase< DIM >::enable_pml(), j, n, oomph::Mesh::nboundary(), oomph::Mesh::nboundary_element(), oomph::Mesh::nboundary_node(), oomph::Mesh::nelement(), oomph::Data::pin(), oomph::Data::set_value(), sorter_right_boundary(), and oomph::PMLElementBase< DIM >::values_to_be_pinned_on_outer_pml_boundary().
Referenced by PMLHelmholtzMGProblem< ELEMENT >::create_pml_meshes(), PMLFourierDecomposedHelmholtzProblem< ELEMENT >::create_pml_meshes(), PMLProblem< ELEMENT >::create_pml_meshes(), and ElasticAnnulusProblem< ELASTICITY_ELEMENT >::create_pml_meshes().
create_top_left_pml_mesh()
template<class ASSOCIATED_PML_QUAD_ELEMENT > Mesh* oomph::TwoDimensionalPMLHelper::create_top_left_pml_mesh (Mesh * pml_left_mesh_pt, Mesh * pml_top_mesh_pt, Mesh * bulk_mesh_pt, const unsigned & left_boundary_id, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
"Constructor" for PML top left corner mesh, aligned with the existing PML meshes
Relevant boundary id's to be used in construction Parent id refers to already existing PML meshes
Sort them from lowest to highest (in y coordinate) sorter_right_boundary is still functional, as the sorting is performed by the same criterion
Number of elements and boundary nodes to be acted upon during construction are extracted from the 'parent' PML meshes
Specific PML sizes needed, taken directly from physical domain and existing PML meshes
The enabling must be perfromed in both x- and y-directions as this is a corner PML mesh
Return the finalized mesh, with PML enabled and boundary conditions added
     {
       unsigned parent_boundary_x_id = 2;
       unsigned parent_boundary_y_id = 3;
       // Current id refers to the mesh that is to be constructed
       unsigned current_boundary_x_id = 0;
       unsigned current_boundary_y_id = 1;
       // Look at the left boundary of the triangular mesh
       unsigned n_left_boundary_node =
         bulk_mesh_pt->nboundary_node(left_boundary_id);
       // Create a vector of ordered boundary nodes
       Vector<Node*> ordered_left_boundary_node_pt(n_left_boundary_node);
       // Fill the vector with the nodes on the respective boundary
       for (unsigned n = 0; n < n_left_boundary_node; n++)
       {
         ordered_left_boundary_node_pt[n] =
           bulk_mesh_pt->boundary_node_pt(left_boundary_id, n);
       }
       std::sort(ordered_left_boundary_node_pt.begin(),
                 ordered_left_boundary_node_pt.end(),
                 sorter_right_boundary);
       unsigned n_x_left_pml =
         pml_left_mesh_pt->nboundary_element(parent_boundary_x_id);
       unsigned n_y_top_pml =
         pml_top_mesh_pt->nboundary_element(parent_boundary_y_id);
       unsigned n_y_boundary_nodes =
         pml_top_mesh_pt->nboundary_node(parent_boundary_y_id);
       double l_pml_left_x_start =
         pml_left_mesh_pt->boundary_node_pt(parent_boundary_x_id, 0)->x(0);
       double l_pml_left_x_end =
         ordered_left_boundary_node_pt[n_left_boundary_node - 1]->x(0);
       double l_pml_top_y_start =
         ordered_left_boundary_node_pt[n_left_boundary_node - 1]->x(1);
       double l_pml_top_y_end =
         pml_top_mesh_pt
           ->boundary_node_pt(parent_boundary_y_id, n_y_boundary_nodes - 1)
           ->x(1);
       // Create the mesh to be designated to the PML
       Mesh* pml_top_left_mesh_pt = 0;
       // Build the top left corner PML mesh
       pml_top_left_mesh_pt = new PMLCornerQuadMesh<ASSOCIATED_PML_QUAD_ELEMENT>(
         pml_left_mesh_pt,
         pml_top_mesh_pt,
         bulk_mesh_pt,
         ordered_left_boundary_node_pt[n_left_boundary_node - 1],
         parent_boundary_x_id,
         parent_boundary_y_id,
         current_boundary_x_id,
         current_boundary_y_id,
         n_x_left_pml,
         n_y_top_pml,
         l_pml_left_x_start,
         l_pml_left_x_end,
         l_pml_top_y_start,
         l_pml_top_y_end,
         time_stepper_pt);
       // Enable PML damping on the entire mesh
       unsigned n_element_pml_top_left = pml_top_left_mesh_pt->nelement();
       for (unsigned e = 0; e < n_element_pml_top_left; e++)
       {
         // Upcast
         PMLElementBase<2>* el_pt =
           dynamic_cast<PMLElementBase<2>*>(pml_top_left_mesh_pt->element_pt(e));
         el_pt->enable_pml(0, l_pml_left_x_end, l_pml_left_x_start);
         el_pt->enable_pml(1, l_pml_top_y_start, l_pml_top_y_end);
       }
       // Get the values to be pinned from the first element (which we
       // assume exists!)
       PMLElementBase<2>* el_pt =
         dynamic_cast<PMLElementBase<2>*>(pml_top_left_mesh_pt->element_pt(0));
       Vector<unsigned> values_to_pin;
       el_pt->values_to_be_pinned_on_outer_pml_boundary(values_to_pin);
       unsigned npin = values_to_pin.size();
       // Exterior boundary needs to be set to Dirichlet 0
       // for both real and imaginary parts of all fields
       // in the problem
       unsigned n_bound_pml_top_left = pml_top_left_mesh_pt->nboundary();
       for (unsigned b = 0; b < n_bound_pml_top_left; b++)
       {
         unsigned n_node = pml_top_left_mesh_pt->nboundary_node(b);
         for (unsigned n = 0; n < n_node; n++)
         {
           Node* nod_pt = pml_top_left_mesh_pt->boundary_node_pt(b, n);
           if ((b == 2) || (b == 3))
           {
             for (unsigned j = 0; j < npin; j++)
             {
               unsigned j_val = values_to_pin[j];
               nod_pt->pin(j_val);
               nod_pt->set_value(j_val, 0.0);
             }
           }
         }
       }
       return pml_top_left_mesh_pt;
     }
References b, oomph::Mesh::boundary_node_pt(), e(), oomph::Mesh::element_pt(), oomph::PMLElementBase< DIM >::enable_pml(), j, n, oomph::Mesh::nboundary(), oomph::Mesh::nboundary_element(), oomph::Mesh::nboundary_node(), oomph::Mesh::nelement(), oomph::Data::pin(), oomph::Data::set_value(), sorter_right_boundary(), oomph::PMLElementBase< DIM >::values_to_be_pinned_on_outer_pml_boundary(), and oomph::Node::x().
Referenced by PMLHelmholtzMGProblem< ELEMENT >::create_pml_meshes(), PMLProblem< ELEMENT >::create_pml_meshes(), ElasticAnnulusProblem< ELASTICITY_ELEMENT >::create_pml_meshes(), and oomph::RefineableQuadMeshWithMovingCylinder< ELEMENT >::RefineableQuadMeshWithMovingCylinder().
create_top_pml_mesh()
template<class ASSOCIATED_PML_QUAD_ELEMENT > Mesh* oomph::TwoDimensionalPMLHelper::create_top_pml_mesh (Mesh * bulk_mesh_pt, const unsigned & top_boundary_id, const unsigned & n_y_top_pml, const double & width_y_top_pml, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
"Constructor" for PML mesh, aligned with the top physical domain boundary
PML layer width added to the bulk mesh coordinate
Return the finalized mesh, with PML enabled and boundary conditions added
     {
       // Look at the top boundary of the triangular mesh
       unsigned n_top_boundary_node =
         bulk_mesh_pt->nboundary_node(top_boundary_id);
       // Create a vector of ordered boundary nodes
       Vector<Node*> ordered_top_boundary_node_pt(n_top_boundary_node);
       // Fill the vector with the nodes on the respective boundary
       for (unsigned n = 0; n < n_top_boundary_node; n++)
       {
         ordered_top_boundary_node_pt[n] =
           bulk_mesh_pt->boundary_node_pt(top_boundary_id, n);
       }
       // Sort them from lowest to highest (in x coordinate)
       std::sort(ordered_top_boundary_node_pt.begin(),
                 ordered_top_boundary_node_pt.end(),
                 sorter_top_boundary);
       // The number of elements in x is taken from the triangular mesh
       unsigned n_x_top_pml = bulk_mesh_pt->nboundary_element(top_boundary_id);
       // Specific PML sizes needed, taken directly from physical domain
       double l_pml_top_x_start = ordered_top_boundary_node_pt[0]->x(0);
       double l_pml_top_x_end =
         ordered_top_boundary_node_pt[n_top_boundary_node - 1]->x(0);
       double l_pml_top_y_start = ordered_top_boundary_node_pt[0]->x(1);
       double l_pml_top_y_end =
         width_y_top_pml + ordered_top_boundary_node_pt[0]->x(1);
       unsigned top_quadPML_boundary_id = 0;
       // Create the mesh to be designated to the PML
       Mesh* pml_top_mesh_pt = 0;
       // Build the top PML mesh
       pml_top_mesh_pt =
         new PMLQuadMesh<ASSOCIATED_PML_QUAD_ELEMENT>(bulk_mesh_pt,
                                                      top_boundary_id,
                                                      top_quadPML_boundary_id,
                                                      n_x_top_pml,
                                                      n_y_top_pml,
                                                      l_pml_top_x_start,
                                                      l_pml_top_x_end,
                                                      l_pml_top_y_start,
                                                      l_pml_top_y_end,
                                                      time_stepper_pt);
       // Enable PML damping on the entire mesh
       unsigned n_element_pml_top = pml_top_mesh_pt->nelement();
       for (unsigned e = 0; e < n_element_pml_top; e++)
       {
         // Upcast
         PMLElementBase<2>* el_pt =
           dynamic_cast<PMLElementBase<2>*>(pml_top_mesh_pt->element_pt(e));
         el_pt->enable_pml(1, l_pml_top_y_start, l_pml_top_y_end);
       }
       // Get the values to be pinned from the first element (which we
       // assume exists!)
       PMLElementBase<2>* el_pt =
         dynamic_cast<PMLElementBase<2>*>(pml_top_mesh_pt->element_pt(0));
       Vector<unsigned> values_to_pin;
       el_pt->values_to_be_pinned_on_outer_pml_boundary(values_to_pin);
       unsigned npin = values_to_pin.size();
       // Exterior boundary needs to be set to Dirichlet 0
       // for both real and imaginary parts of all fields
       // in the problem
       unsigned n_bound_pml_top = pml_top_mesh_pt->nboundary();
       for (unsigned b = 0; b < n_bound_pml_top; b++)
       {
         unsigned n_node = pml_top_mesh_pt->nboundary_node(b);
         for (unsigned n = 0; n < n_node; n++)
         {
           Node* nod_pt = pml_top_mesh_pt->boundary_node_pt(b, n);
           if (b == 2)
           {
             for (unsigned j = 0; j < npin; j++)
             {
               unsigned j_val = values_to_pin[j];
               nod_pt->pin(j_val);
               nod_pt->set_value(j_val, 0.0);
             }
           }
         }
       }
       return pml_top_mesh_pt;
     }
References b, oomph::Mesh::boundary_node_pt(), e(), oomph::Mesh::element_pt(), oomph::PMLElementBase< DIM >::enable_pml(), j, n, oomph::Mesh::nboundary(), oomph::Mesh::nboundary_element(), oomph::Mesh::nboundary_node(), oomph::Mesh::nelement(), oomph::Data::pin(), oomph::Data::set_value(), sorter_top_boundary(), and oomph::PMLElementBase< DIM >::values_to_be_pinned_on_outer_pml_boundary().
Referenced by PMLHelmholtzMGProblem< ELEMENT >::create_pml_meshes(), PMLFourierDecomposedHelmholtzProblem< ELEMENT >::create_pml_meshes(), PMLProblem< ELEMENT >::create_pml_meshes(), and ElasticAnnulusProblem< ELASTICITY_ELEMENT >::create_pml_meshes().
create_top_right_pml_mesh()
template<class ASSOCIATED_PML_QUAD_ELEMENT > Mesh* oomph::TwoDimensionalPMLHelper::create_top_right_pml_mesh (Mesh * pml_right_mesh_pt, Mesh * pml_top_mesh_pt, Mesh * bulk_mesh_pt, const unsigned & right_boundary_id, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
"Constructor" for PML top right corner mesh, aligned with the existing PML meshes
Relevant boundary id's to be used in construction Parent id refers to already existing PML meshes
Number of elements and boundary nodes to be acted upon during construction are extracted from the 'parent' PML meshes
Specific PML sizes needed, taken directly from physical domain and existing PML meshes
The enabling must be perfromed in both x- and y-directions as this is a corner PML mesh
Return the finalized mesh, with PML enabled and boundary conditions added
     {
       unsigned parent_boundary_x_id = 2;
       unsigned parent_boundary_y_id = 1;
       // Current id refers to the mesh that is to be constructed
       unsigned current_boundary_x_id = 0;
       unsigned current_boundary_y_id = 3;
       // Look at the right boundary of the triangular mesh
       unsigned n_right_boundary_node =
         bulk_mesh_pt->nboundary_node(right_boundary_id);
       // Create a vector of ordered boundary nodes
       Vector<Node*> ordered_right_boundary_node_pt(n_right_boundary_node);
       // Fill the vector with the nodes on the respective boundary
       for (unsigned n = 0; n < n_right_boundary_node; n++)
       {
         ordered_right_boundary_node_pt[n] =
           bulk_mesh_pt->boundary_node_pt(right_boundary_id, n);
       }
       // Sort them from lowest to highest (in y coordinate)
       std::sort(ordered_right_boundary_node_pt.begin(),
                 ordered_right_boundary_node_pt.end(),
                 sorter_right_boundary);
       unsigned n_x_right_pml =
         pml_right_mesh_pt->nboundary_element(parent_boundary_x_id);
       unsigned n_y_top_pml =
         pml_top_mesh_pt->nboundary_element(parent_boundary_y_id);
       unsigned n_x_boundary_nodes =
         pml_right_mesh_pt->nboundary_node(parent_boundary_x_id);
       unsigned n_y_boundary_nodes =
         pml_top_mesh_pt->nboundary_node(parent_boundary_y_id);
       double l_pml_right_x_start =
         ordered_right_boundary_node_pt[n_right_boundary_node - 1]->x(0);
       double l_pml_right_x_end =
         pml_right_mesh_pt
           ->boundary_node_pt(parent_boundary_x_id, n_x_boundary_nodes - 1)
           ->x(0);
       double l_pml_top_y_start =
         ordered_right_boundary_node_pt[n_right_boundary_node - 1]->x(1);
       double l_pml_top_y_end =
         pml_top_mesh_pt
           ->boundary_node_pt(parent_boundary_y_id, n_y_boundary_nodes - 1)
           ->x(1);
       // Create the mesh to be designated to the PML
       Mesh* pml_top_right_mesh_pt = 0;
       // Build the top right corner PML mesh
       pml_top_right_mesh_pt =
         new PMLCornerQuadMesh<ASSOCIATED_PML_QUAD_ELEMENT>(
           pml_right_mesh_pt,
           pml_top_mesh_pt,
           bulk_mesh_pt,
           ordered_right_boundary_node_pt[n_right_boundary_node - 1],
           parent_boundary_x_id,
           parent_boundary_y_id,
           current_boundary_x_id,
           current_boundary_y_id,
           n_x_right_pml,
           n_y_top_pml,
           l_pml_right_x_start,
           l_pml_right_x_end,
           l_pml_top_y_start,
           l_pml_top_y_end,
           time_stepper_pt);
       // Enable PML damping on the entire mesh
       unsigned n_element_pml_top_right = pml_top_right_mesh_pt->nelement();
       for (unsigned e = 0; e < n_element_pml_top_right; e++)
       {
         // Upcast
         PMLElementBase<2>* el_pt = dynamic_cast<PMLElementBase<2>*>(
           pml_top_right_mesh_pt->element_pt(e));
         el_pt->enable_pml(0, l_pml_right_x_start, l_pml_right_x_end);
         el_pt->enable_pml(1, l_pml_top_y_start, l_pml_top_y_end);
       }
       // Get the values to be pinned from the first element (which we
       // assume exists!)
       PMLElementBase<2>* el_pt =
         dynamic_cast<PMLElementBase<2>*>(pml_top_right_mesh_pt->element_pt(0));
       Vector<unsigned> values_to_pin;
       el_pt->values_to_be_pinned_on_outer_pml_boundary(values_to_pin);
       unsigned npin = values_to_pin.size();
       // Exterior boundary needs to be set to Dirichlet 0
       // for both real and imaginary parts of all fields
       // in the problem
       unsigned n_bound_pml_top_right = pml_top_right_mesh_pt->nboundary();
       for (unsigned b = 0; b < n_bound_pml_top_right; b++)
       {
         unsigned n_node = pml_top_right_mesh_pt->nboundary_node(b);
         for (unsigned n = 0; n < n_node; n++)
         {
           Node* nod_pt = pml_top_right_mesh_pt->boundary_node_pt(b, n);
           if ((b == 1) || (b == 2))
           {
             for (unsigned j = 0; j < npin; j++)
             {
               unsigned j_val = values_to_pin[j];
               nod_pt->pin(j_val);
               nod_pt->set_value(j_val, 0.0);
             }
           }
         }
       }
       return pml_top_right_mesh_pt;
     }
References b, oomph::Mesh::boundary_node_pt(), e(), oomph::Mesh::element_pt(), oomph::PMLElementBase< DIM >::enable_pml(), j, n, oomph::Mesh::nboundary(), oomph::Mesh::nboundary_element(), oomph::Mesh::nboundary_node(), oomph::Mesh::nelement(), oomph::Data::pin(), oomph::Data::set_value(), sorter_right_boundary(), oomph::PMLElementBase< DIM >::values_to_be_pinned_on_outer_pml_boundary(), and oomph::Node::x().
Referenced by PMLHelmholtzMGProblem< ELEMENT >::create_pml_meshes(), PMLFourierDecomposedHelmholtzProblem< ELEMENT >::create_pml_meshes(), PMLProblem< ELEMENT >::create_pml_meshes(), ElasticAnnulusProblem< ELASTICITY_ELEMENT >::create_pml_meshes(), and oomph::RefineableQuadMeshWithMovingCylinder< ELEMENT >::RefineableQuadMeshWithMovingCylinder().
sorter_bottom_boundary()
bool oomph::TwoDimensionalPMLHelper::sorter_bottom_boundary (Node * nod_i_pt, Node * nod_j_pt)
helper function for sorting the bottom boundary nodes
     {
       return (nod_i_pt->x(0) > nod_j_pt->x(0));
     }
References oomph::Node::x().
Referenced by create_bottom_pml_mesh(), and oomph::PMLQuadMesh< ELEMENT >::PMLQuadMesh().
sorter_left_boundary()
bool oomph::TwoDimensionalPMLHelper::sorter_left_boundary (Node * nod_i_pt, Node * nod_j_pt)
helper function for sorting the left boundary nodes
     {
       return (nod_i_pt->x(1) > nod_j_pt->x(1));
     }
References oomph::Node::x().
Referenced by create_left_pml_mesh(), and oomph::PMLQuadMesh< ELEMENT >::PMLQuadMesh().
sorter_right_boundary()
bool oomph::TwoDimensionalPMLHelper::sorter_right_boundary (Node * nod_i_pt, Node * nod_j_pt)
helper function for sorting the right boundary nodes
     {
       return (nod_i_pt->x(1) < nod_j_pt->x(1));
     }
References oomph::Node::x().
Referenced by create_bottom_left_pml_mesh(), create_bottom_right_pml_mesh(), create_right_pml_mesh(), create_top_left_pml_mesh(), create_top_right_pml_mesh(), oomph::PMLCornerQuadMesh< ELEMENT >::PMLCornerQuadMesh(), and oomph::PMLQuadMesh< ELEMENT >::PMLQuadMesh().
sorter_top_boundary()
bool oomph::TwoDimensionalPMLHelper::sorter_top_boundary (Node * nod_i_pt, Node * nod_j_pt)
helper function for sorting the top boundary nodes
     {
       return (nod_i_pt->x(0) < nod_j_pt->x(0));
     }
References oomph::Node::x().
Referenced by create_top_pml_mesh(), oomph::PMLCornerQuadMesh< ELEMENT >::PMLCornerQuadMesh(), and oomph::PMLQuadMesh< ELEMENT >::PMLQuadMesh().