MercuryDPM: oomph::TriangleMeshCurveSection Class Reference
oomph::TriangleMeshCurveSection Class Reference abstract
#include <unstructured_two_d_mesh_geometry_base.h>
Public Member Functions
TriangleMeshCurveSection ()
Empty constructor. Initialises the curve section as non connected.
virtual ~TriangleMeshCurveSection ()
Empty destructor.
virtual unsigned nsegment () const =0
virtual unsigned boundary_id () const =0
Boundary id.
virtual unsigned boundary_chunk () const =0
virtual unsigned nvertex () const =0
Number of vertices.
virtual void output (std::ostream &outfile, const unsigned &n_sample=50)=0
Output the curve_section.
void enable_refinement_tolerance (const double &tolerance=0.08)
void set_refinement_tolerance (const double &tolerance)
double refinement_tolerance ()
void disable_refinement_tolerance ()
Disable refinement of curve section.
void enable_unrefinement_tolerance (const double &tolerance=0.04)
void set_unrefinement_tolerance (const double &tolerance)
double unrefinement_tolerance ()
void disable_unrefinement_tolerance ()
Disable unrefinement of curve sections.
void set_maximum_length (const double &maximum_length)
void disable_use_maximum_length ()
double maximum_length ()
Gets access to the maximum length variable.
virtual void initial_vertex_coordinate (Vector< double > &vertex)=0
Get first vertex coordinates.
virtual void final_vertex_coordinate (Vector< double > &vertex)=0
Get last vertex coordinates.
void connect_initial_vertex_to_polyline (TriangleMeshPolyLine *polyline_pt, const unsigned &vertex_number, const double &tolerance_for_connection=1.0e-14)
void connect_final_vertex_to_polyline (TriangleMeshPolyLine *polyline_pt, const unsigned &vertex_number, const double &tolerance_for_connection=1.0e-14)
void connect_initial_vertex_to_curviline (TriangleMeshCurviLine *curviline_pt, const double &s_value, const double &tolerance_for_connection=1.0e-14)
void connect_final_vertex_to_curviline (TriangleMeshCurviLine *curviline_pt, const double &s_value, const double &tolerance_for_connection=1.0e-14)
bool is_initial_vertex_connected () const
Test whether initial vertex is connected or not.
void set_initial_vertex_connected ()
Sets the initial vertex as connected.
void unset_initial_vertex_connected ()
Sets the initial vertex as non connected.
void suspend_initial_vertex_connected ()
void resume_initial_vertex_connected ()
bool is_final_vertex_connected () const
Test whether final vertex is connected or not.
void set_final_vertex_connected ()
Sets the final vertex as connected.
void unset_final_vertex_connected ()
Sets the final vertex as non connected.
void suspend_final_vertex_connected ()
void resume_final_vertex_connected ()
unsigned initial_vertex_connected_bnd_id () const
Gets the id to which the initial end is connected.
unsigned & initial_vertex_connected_bnd_id ()
Sets the id to which the initial end is connected.
unsigned initial_vertex_connected_n_vertex () const
Gets the vertex number to which the initial end is connected.
unsigned & initial_vertex_connected_n_vertex ()
Sets the vertex number to which the initial end is connected.
unsigned initial_vertex_connected_n_chunk () const
Gets the boundary chunk to which the initial end is connected.
unsigned & initial_vertex_connected_n_chunk ()
Sets the boundary chunk to which the initial end is connected.
unsigned final_vertex_connected_bnd_id () const
Gets the id to which the final end is connected.
unsigned & final_vertex_connected_bnd_id ()
Sets the id to which the final end is connected.
unsigned final_vertex_connected_n_vertex () const
Sets the vertex number to which the final end is connected.
unsigned & final_vertex_connected_n_vertex ()
Gets the vertex number to which the final end is connected.
unsigned final_vertex_connected_n_chunk () const
Gets the boundary chunk to which the final end is connected.
unsigned & final_vertex_connected_n_chunk ()
Sets the boundary chunk to which the final end is connected.
bool is_initial_vertex_connected_to_curviline () const
Test whether the initial vertex is connected to a curviline.
void set_initial_vertex_connected_to_curviline ()
Sets the initial vertex as connected to a curviline.
void unset_initial_vertex_connected_to_curviline ()
Sets the initial vertex as non connected to a curviline.
bool is_final_vertex_connected_to_curviline () const
Test whether the final vertex is connected to a curviline.
void set_final_vertex_connected_to_curviline ()
Sets the final vertex as connected to a curviline.
void unset_final_vertex_connected_to_curviline ()
Sets the final vertex as non connected to a curviline.
double initial_s_connection_value () const
Gets the s value to which the initial end is connected.
double & initial_s_connection_value ()
Sets the s value to which the initial end is connected.
double final_s_connection_value () const
Gets the s value to which the final end is connected.
double & final_s_connection_value ()
Sets the s value to which the final end is connected.
double tolerance_for_s_connection () const
double & tolerance_for_s_connection ()
Protected Attributes
bool Initial_vertex_connected
bool Final_vertex_connected
bool Initial_vertex_connected_suspended
bool Final_vertex_connected_suspended
unsigned Initial_vertex_connected_bnd_id
Stores the id to which the initial end is connected.
unsigned Initial_vertex_connected_n_vertex
unsigned Initial_vertex_connected_n_chunk
unsigned Final_vertex_connected_bnd_id
Stores the id to which the initial end is connected.
unsigned Final_vertex_connected_n_vertex
unsigned Final_vertex_connected_n_chunk
bool Initial_vertex_connected_to_curviline
States if the initial vertex is connected to a curviline.
bool Final_vertex_connected_to_curviline
States if the final vertex is connected to a curviline.
double Initial_s_connection_value
double Final_s_connection_value
double Tolerance_for_s_connection
Tolerance used for connecting the ends to a curviline.
Private Attributes
double Refinement_tolerance
double Unrefinement_tolerance
double Maximum_length
Detailed Description
Base class for defining a triangle mesh boundary, this class has the methods that allow to connect the initial and final ends to other triangle mesh boundaries
Constructor & Destructor Documentation
TriangleMeshCurveSection()
oomph::TriangleMeshCurveSection::TriangleMeshCurveSection () inline
Empty constructor. Initialises the curve section as non connected.
       : Initial_vertex_connected(false),
         Final_vertex_connected(false),
         Initial_vertex_connected_suspended(false),
         Final_vertex_connected_suspended(false),
         Initial_vertex_connected_to_curviline(false),
         Final_vertex_connected_to_curviline(false),
         Refinement_tolerance(0.08),
         Unrefinement_tolerance(0.04),
         Maximum_length(-1.0)
     {
     }
~TriangleMeshCurveSection()
virtual oomph::TriangleMeshCurveSection::~TriangleMeshCurveSection () inline virtual
Empty destructor.
 {}
Member Function Documentation
boundary_chunk()
virtual unsigned oomph::TriangleMeshCurveSection::boundary_chunk () const pure virtual
Boundary chunk (Used when a boundary is represented by more than one polyline
Implemented in oomph::TriangleMeshPolyLine, and oomph::TriangleMeshCurviLine.
boundary_id()
virtual unsigned oomph::TriangleMeshCurveSection::boundary_id () const pure virtual
Boundary id.
Implemented in oomph::TriangleMeshPolyLine, and oomph::TriangleMeshCurviLine.
Referenced by connect_final_vertex_to_curviline(), connect_final_vertex_to_polyline(), connect_initial_vertex_to_curviline(), and connect_initial_vertex_to_polyline().
connect_final_vertex_to_curviline()
void oomph::TriangleMeshCurveSection::connect_final_vertex_to_curviline (TriangleMeshCurviLine * curviline_pt, const double & s_value, const double & tolerance_for_connection = 1.0e-14)
Connects the final vertex of the curve section to a desired target curviline by specifying the s value (intrinsic value on the geometric object of the curviline) where to connect on the target curviline. There is a checking which verifies that the final vertex and the coordinates on the given s value are close enough by no more than the given tolerance
target curviline by specifying the s value (intrinsic value on the geometric object of the curviline) where to connect on the target curviline. There is a checking which verifies that the final vertex and the coordinates on the given s value are close enough by no more than the given tolerance
   {
 #ifdef PARANOID
     double z_initial = curviline_pt->zeta_start();
     double z_final = curviline_pt->zeta_end();
     double z_max = std::max(z_initial, z_final);
     double z_min = std::min(z_initial, z_final);
     if (s_value < z_min || z_max < s_value)
     {
       std::ostringstream error_stream;
       error_stream << "The s value you provided for connection (" << s_value
                    << ") is out\nof the limits of the specified "
                    << "TriangleMeshCurviLine.\nThe limits are [" << z_initial
                    << ", " << z_final << "]" << std::endl
                    << "Source boundary (" << boundary_id()
                    << ") wants to connect "
                    << "to destination boundary (" << curviline_pt->boundary_id()
                    << ")" << std::endl;
       throw OomphLibError(
         error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
     // Verify if there is really a match point in the specified
     // connection values
     Vector<double> v_src(2);
     Vector<double> v_dst(2);
     Vector<double> z(1);
     this->final_vertex_coordinate(v_src);
     z[0] = s_value;
     curviline_pt->geom_object_pt()->position(z, v_dst);
     double error = sqrt((v_src[0] - v_dst[0]) * (v_src[0] - v_dst[0]) +
                         (v_src[1] - v_dst[1]) * (v_src[1] - v_dst[1]));
     if (error >= tolerance_for_connection)
     {
       std::ostringstream error_stream;
       error_stream
         << "The associated vertex for the provided connection s value\n"
         << "are not close enough. Their respective values are:\n"
         << "Source boundary id:(" << this->boundary_id() << ")\n"
         << "Source vertex x:(" << v_src[0] << ") y:(" << v_src[1] << ")\n"
         << "Destination boundary id:(" << curviline_pt->boundary_id() << ")"
         << "\nDestination s value (" << s_value << ")\n"
         << "Associated vertex x:(" << v_dst[0] << ") y:(" << v_dst[1] << ")"
         << "\nThe corresponding distance is: (" << error << ") but the "
         << "allowed\ntolerance is: (" << tolerance_for_connection << ")"
         << std::endl;
       throw OomphLibError(
         error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     Final_vertex_connected_to_curviline = true;
     Final_vertex_connected = true;
     Final_vertex_connected_bnd_id = curviline_pt->boundary_id();
     Final_vertex_connected_n_chunk = curviline_pt->boundary_chunk();
     // We are still not able to compute the vertex number but we can
     // at least store the corresponding s value.
     // The corresponding vertex will be computed when the curviline be
     // transformed into a polyline
     Final_s_connection_value = s_value;
     Tolerance_for_s_connection = tolerance_for_connection;
     curviline_pt->add_connection_point(s_value, tolerance_for_connection);
   }
References oomph::TriangleMeshCurviLine::add_connection_point(), oomph::TriangleMeshCurviLine::boundary_chunk(), oomph::TriangleMeshCurviLine::boundary_id(), boundary_id(), calibrate::error, Final_s_connection_value, Final_vertex_connected, Final_vertex_connected_bnd_id, Final_vertex_connected_n_chunk, Final_vertex_connected_to_curviline, final_vertex_coordinate(), oomph::TriangleMeshCurviLine::geom_object_pt(), max, min, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::GeomObject::position(), sqrt(), Tolerance_for_s_connection, oomph::TriangleMeshCurviLine::zeta_end(), and oomph::TriangleMeshCurviLine::zeta_start().
Referenced by UnstructuredFvKProblem< ELEMENT >::UnstructuredFvKProblem().
connect_final_vertex_to_polyline()
void oomph::TriangleMeshCurveSection::connect_final_vertex_to_polyline (TriangleMeshPolyLine * polyline_pt, const unsigned & vertex_number, const double & tolerance_for_connection = 1.0e-14)
Connects the final vertex of the curve section to a desired target polyline by specifying the vertex number. There is a checking which verifies that the final vertex is close enough to the destination vertex on the target polyline by no more than the specified tolerance
target polyline by specifying the vertex number. There is a checking which verifies that the final vertex is close enough to the destination vertex on the target polyline by no more than the specified tolerance
   {
 #ifdef PARANOID
     unsigned n_vertices = polyline_pt->nvertex();
     if (n_vertices <= vertex_number)
     {
       std::ostringstream error_stream;
       error_stream << "The vertex number you provided (" << vertex_number
                    << ") is greater\n than the number of vertices ("
                    << n_vertices << "in the specified TriangleMeshPolyLine.\n"
                    << "Remember that the vertex index starts at 0" << std::endl
                    << "Source boundary (" << boundary_id()
                    << ") wants to connect "
                    << "to destination boundary (" << polyline_pt->boundary_id()
                    << ")" << std::endl;
       throw OomphLibError(
         error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
     // Verify if there is really a match point in the specified
     // connection values
     Vector<double> v_src(2);
     Vector<double> v_dst(2);
     this->final_vertex_coordinate(v_src);
     v_dst = polyline_pt->vertex_coordinate(vertex_number);
     double error = sqrt((v_src[0] - v_dst[0]) * (v_src[0] - v_dst[0]) +
                         (v_src[1] - v_dst[1]) * (v_src[1] - v_dst[1]));
     if (error > tolerance_for_connection)
     {
       std::ostringstream error_stream;
       error_stream << "The associated vertices for the connection"
                    << "\nare not close enough. Their respective values are:\n"
                    << "Source boundary id:(" << this->boundary_id() << ")\n"
                    << "Source vertex x:(" << v_src[0] << ") y:(" << v_src[1]
                    << ")\n"
                    << "Destination boundary id:(" << polyline_pt->boundary_id()
                    << ")"
                    << "\nAssociated vertex x:(" << v_dst[0] << ") y:("
                    << v_dst[1] << ")"
                    << "\nThe corresponding distance is: (" << error
                    << ") but the "
                    << "allowed\ntolerance is: (" << tolerance_for_connection
                    << ")" << std::endl;
       throw OomphLibError(
         error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     Final_vertex_connected = true;
     Final_vertex_connected_bnd_id = polyline_pt->boundary_id();
     Final_vertex_connected_n_vertex = vertex_number;
     Final_vertex_connected_n_chunk = polyline_pt->boundary_chunk();
   }
References oomph::TriangleMeshPolyLine::boundary_chunk(), oomph::TriangleMeshPolyLine::boundary_id(), boundary_id(), calibrate::error, Final_vertex_connected, Final_vertex_connected_bnd_id, Final_vertex_connected_n_chunk, Final_vertex_connected_n_vertex, final_vertex_coordinate(), oomph::TriangleMeshPolyLine::nvertex(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, sqrt(), and oomph::TriangleMeshPolyLine::vertex_coordinate().
Referenced by MeltContactProblem< ELEMENT >::MeltContactProblem(), SolarRadiationProblem< ELEMENT >::SolarRadiationProblem(), and TwoLayerInterfaceProblem< ELEMENT >::TwoLayerInterfaceProblem().
connect_initial_vertex_to_curviline()
void oomph::TriangleMeshCurveSection::connect_initial_vertex_to_curviline (TriangleMeshCurviLine * curviline_pt, const double & s_value, const double & tolerance_for_connection = 1.0e-14)
Connects the initial vertex of the curve section to a desired target curviline by specifying the s value (intrinsic value on the geometric object of the curviline) where to connect on the target curviline. There is a checking which verifies that the initial vertex and the coordinates on the given s value are close enough by no more than the given tolerance
target curviline by specifying the s value (intrinsic value on the geometric object of the curviline) where to connect on the target curviline. There is a checking which verifies that the initial vertex and the coordinates on the given s value are close enough by no more than the given tolerance
   {
 #ifdef PARANOID
     double z_initial = curviline_pt->zeta_start();
     double z_final = curviline_pt->zeta_end();
     double z_max = std::max(z_initial, z_final);
     double z_min = std::min(z_initial, z_final);
     if (s_value < z_min || z_max < s_value)
     {
       std::ostringstream error_stream;
       error_stream << "The s value you provided for connection (" << s_value
                    << ") is out\nof the limits of the specified "
                    << "TriangleMeshCurviLine.\nThe limits are [" << z_initial
                    << ", " << z_final << "]" << std::endl
                    << "Source boundary (" << boundary_id()
                    << ") wants to connect "
                    << "to destination boundary (" << curviline_pt->boundary_id()
                    << ")" << std::endl;
       throw OomphLibError(
         error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
     // Verify if there is really a match point in the specified
     // connection values
     Vector<double> v_src(2);
     Vector<double> v_dst(2);
     Vector<double> z(1);
     this->initial_vertex_coordinate(v_src);
     z[0] = s_value;
     curviline_pt->geom_object_pt()->position(z, v_dst);
     double error = sqrt((v_src[0] - v_dst[0]) * (v_src[0] - v_dst[0]) +
                         (v_src[1] - v_dst[1]) * (v_src[1] - v_dst[1]));
     if (error >= tolerance_for_connection)
     {
       std::ostringstream error_stream;
       error_stream
         << "The associated vertex for the provided connection s value\n"
         << "are not close enough. Their respective values are:\n"
         << "Source boundary id:(" << this->boundary_id() << ")\n"
         << "Source vertex x:(" << v_src[0] << ") y:(" << v_src[1] << ")\n"
         << "Destination boundary id:(" << curviline_pt->boundary_id() << ")"
         << "\nDestination s value (" << s_value << ")\n"
         << "Associated vertex x:(" << v_dst[0] << ") y:(" << v_dst[1] << ")"
         << "\nThe corresponding distance is: (" << error << ") but the "
         << "allowed\ntolerance is: (" << tolerance_for_connection << ")"
         << std::endl;
       throw OomphLibError(
         error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     Initial_vertex_connected_to_curviline = true;
     Initial_vertex_connected = true;
     Initial_vertex_connected_bnd_id = curviline_pt->boundary_id();
     Initial_vertex_connected_n_chunk = curviline_pt->boundary_chunk();
     // We are still not able to compute the vertex number but we can
     // at least store the corresponding s value
     // The corresponding vertex will be computed when the curviline be
     // changed into a polyline
     Initial_s_connection_value = s_value;
     Tolerance_for_s_connection = tolerance_for_connection;
     curviline_pt->add_connection_point(s_value, tolerance_for_connection);
   }
References oomph::TriangleMeshCurviLine::add_connection_point(), oomph::TriangleMeshCurviLine::boundary_chunk(), oomph::TriangleMeshCurviLine::boundary_id(), boundary_id(), calibrate::error, oomph::TriangleMeshCurviLine::geom_object_pt(), Initial_s_connection_value, Initial_vertex_connected, Initial_vertex_connected_bnd_id, Initial_vertex_connected_n_chunk, Initial_vertex_connected_to_curviline, initial_vertex_coordinate(), max, min, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::GeomObject::position(), sqrt(), Tolerance_for_s_connection, oomph::TriangleMeshCurviLine::zeta_end(), and oomph::TriangleMeshCurviLine::zeta_start().
Referenced by AxiPoroProblem< ELEMENT, TIMESTEPPER >::AxiPoroProblem(), and UnstructuredFvKProblem< ELEMENT >::UnstructuredFvKProblem().
connect_initial_vertex_to_polyline()
void oomph::TriangleMeshCurveSection::connect_initial_vertex_to_polyline (TriangleMeshPolyLine * polyline_pt, const unsigned & vertex_number, const double & tolerance_for_connection = 1.0e-14)
Connects the initial vertex of the curve section to a desired target polyline by specifying the vertex number. There is a checking which verifies that the initial vertex is close enough to the destination vertex on the target polyline by no more than the specified tolerance
///////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////// target polyline by specifying the vertex number. There is a checking which verifies that the initial vertex is close enough to the destination vertex on the target polyline by no more than the specified tolerance
   {
 #ifdef PARANOID
     unsigned n_vertices = polyline_pt->nvertex();
     if (n_vertices <= vertex_number)
     {
       std::ostringstream error_stream;
       error_stream << "The vertex number you provided (" << vertex_number
                    << ") is greater\n than the number of vertices ("
                    << n_vertices << "in the specified TriangleMeshPolyLine.\n"
                    << "Remember that the vertex index starts at 0" << std::endl
                    << "Source boundary (" << boundary_id()
                    << ") wants to connect "
                    << "to destination boundary (" << polyline_pt->boundary_id()
                    << ")" << std::endl;
       throw OomphLibError(
         error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
     // Verify if there is really a match point in the specified
     // connection values
     Vector<double> v_src(2);
     Vector<double> v_dst(2);
     this->initial_vertex_coordinate(v_src);
     v_dst = polyline_pt->vertex_coordinate(vertex_number);
     double error = sqrt((v_src[0] - v_dst[0]) * (v_src[0] - v_dst[0]) +
                         (v_src[1] - v_dst[1]) * (v_src[1] - v_dst[1]));
     if (error > tolerance_for_connection)
     {
       std::ostringstream error_stream;
       error_stream << "The associated vertices for the connection"
                    << "\nare not close enough. Their respective values are:\n"
                    << "Source boundary id:(" << this->boundary_id() << ")\n"
                    << "Source vertex x:(" << v_src[0] << ") y:(" << v_src[1]
                    << ")\n"
                    << "Destination boundary id:(" << polyline_pt->boundary_id()
                    << ")"
                    << "\nAssociated vertex x:(" << v_dst[0] << ") y:("
                    << v_dst[1] << ")"
                    << "\nThe corresponding distance is: (" << error
                    << ") but the "
                    << "allowed\ntolerance is: (" << tolerance_for_connection
                    << ")" << std::endl;
       throw OomphLibError(
         error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     Initial_vertex_connected = true;
     Initial_vertex_connected_bnd_id = polyline_pt->boundary_id();
     Initial_vertex_connected_n_vertex = vertex_number;
     Initial_vertex_connected_n_chunk = polyline_pt->boundary_chunk();
   }
References oomph::TriangleMeshPolyLine::boundary_chunk(), oomph::TriangleMeshPolyLine::boundary_id(), boundary_id(), calibrate::error, Initial_vertex_connected, Initial_vertex_connected_bnd_id, Initial_vertex_connected_n_chunk, Initial_vertex_connected_n_vertex, initial_vertex_coordinate(), oomph::TriangleMeshPolyLine::nvertex(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, sqrt(), and oomph::TriangleMeshPolyLine::vertex_coordinate().
Referenced by MeltContactProblem< ELEMENT >::MeltContactProblem(), SolarRadiationProblem< ELEMENT >::SolarRadiationProblem(), TwoLayerInterfaceProblem< ELEMENT >::TwoLayerInterfaceProblem(), and UnstructuredFvKProblem< ELEMENT >::UnstructuredFvKProblem().
disable_refinement_tolerance()
void oomph::TriangleMeshCurveSection::disable_refinement_tolerance () inline
Disable refinement of curve section.
     {
       Refinement_tolerance = -1.0;
     }
References Refinement_tolerance.
disable_unrefinement_tolerance()
void oomph::TriangleMeshCurveSection::disable_unrefinement_tolerance () inline
Disable unrefinement of curve sections.
     {
       Unrefinement_tolerance = -1.0;
     }
References Unrefinement_tolerance.
disable_use_maximum_length()
void oomph::TriangleMeshCurveSection::disable_use_maximum_length () inline
Disables the use of the maximum length criteria on the unrefinement or refinement steps
     {
       Maximum_length = -1.0;
     }
References Maximum_length.
enable_refinement_tolerance()
void oomph::TriangleMeshCurveSection::enable_refinement_tolerance (const double & tolerance = 0.08) inline
Enable refinement of curve section to create a better representation of curvilinear boundaries (e.g. in free-surface problems). See tutorial for interpretation of the optional argument which specifies the refinement tolerance. It defaults to 0.08 and the smaller the number the finer the surface representation.
     {
       Refinement_tolerance = tolerance;
     }
References Refinement_tolerance.
enable_unrefinement_tolerance()
void oomph::TriangleMeshCurveSection::enable_unrefinement_tolerance (const double & tolerance = 0.04) inline
Enable unrefinement of curve sections to avoid unnecessarily large numbers of elements on of curvilinear boundaries (e.g. in free-surface problems). See tutorial for interpretation of the optional argument which specifies the unrefinement tolerance. It defaults to 0.04 and the larger the number the more agressive we are when removing unnecessary vertices on gently curved polylines.
     {
       Unrefinement_tolerance = tolerance;
     }
References Unrefinement_tolerance.
final_s_connection_value() [1/2]
double& oomph::TriangleMeshCurveSection::final_s_connection_value () inline
Sets the s value to which the final end is connected.
     {
       return Final_s_connection_value;
     }
References Final_s_connection_value.
final_s_connection_value() [2/2]
double oomph::TriangleMeshCurveSection::final_s_connection_value () const inline
Gets the s value to which the final end is connected.
     {
       return Final_s_connection_value;
     }
References Final_s_connection_value.
Referenced by oomph::TriangleMeshPolyLine::reverse().
final_vertex_connected_bnd_id() [1/2]
unsigned& oomph::TriangleMeshCurveSection::final_vertex_connected_bnd_id () inline
Sets the id to which the final end is connected.
     {
       return Final_vertex_connected_bnd_id;
     }
References Final_vertex_connected_bnd_id.
final_vertex_connected_bnd_id() [2/2]
unsigned oomph::TriangleMeshCurveSection::final_vertex_connected_bnd_id () const inline
Gets the id to which the final end is connected.
     {
       return Final_vertex_connected_bnd_id;
     }
References Final_vertex_connected_bnd_id.
Referenced by oomph::TriangleMeshPolyLine::reverse().
final_vertex_connected_n_chunk() [1/2]
unsigned& oomph::TriangleMeshCurveSection::final_vertex_connected_n_chunk () inline
Sets the boundary chunk to which the final end is connected.
     {
       return Final_vertex_connected_n_chunk;
     }
References Final_vertex_connected_n_chunk.
final_vertex_connected_n_chunk() [2/2]
unsigned oomph::TriangleMeshCurveSection::final_vertex_connected_n_chunk () const inline
Gets the boundary chunk to which the final end is connected.
     {
       return Final_vertex_connected_n_chunk;
     }
References Final_vertex_connected_n_chunk.
Referenced by oomph::TriangleMeshPolyLine::reverse().
final_vertex_connected_n_vertex() [1/2]
unsigned& oomph::TriangleMeshCurveSection::final_vertex_connected_n_vertex () inline
Gets the vertex number to which the final end is connected.
     {
       return Final_vertex_connected_n_vertex;
     }
References Final_vertex_connected_n_vertex.
final_vertex_connected_n_vertex() [2/2]
unsigned oomph::TriangleMeshCurveSection::final_vertex_connected_n_vertex () const inline
Sets the vertex number to which the final end is connected.
     {
       return Final_vertex_connected_n_vertex;
     }
References Final_vertex_connected_n_vertex.
Referenced by oomph::TriangleMeshPolyLine::reverse().
final_vertex_coordinate()
virtual void oomph::TriangleMeshCurveSection::final_vertex_coordinate (Vector< double > & vertex) pure virtual
Get last vertex coordinates.
Implemented in oomph::TriangleMeshPolyLine, and oomph::TriangleMeshCurviLine.
Referenced by connect_final_vertex_to_curviline(), connect_final_vertex_to_polyline(), and oomph::TriangleMeshClosedCurve::TriangleMeshClosedCurve().
initial_s_connection_value() [1/2]
double& oomph::TriangleMeshCurveSection::initial_s_connection_value () inline
Sets the s value to which the initial end is connected.
     {
       return Initial_s_connection_value;
     }
References Initial_s_connection_value.
initial_s_connection_value() [2/2]
double oomph::TriangleMeshCurveSection::initial_s_connection_value () const inline
Gets the s value to which the initial end is connected.
     {
       return Initial_s_connection_value;
     }
References Initial_s_connection_value.
Referenced by oomph::TriangleMeshPolyLine::reverse().
initial_vertex_connected_bnd_id() [1/2]
unsigned& oomph::TriangleMeshCurveSection::initial_vertex_connected_bnd_id () inline
Sets the id to which the initial end is connected.
     {
       return Initial_vertex_connected_bnd_id;
     }
References Initial_vertex_connected_bnd_id.
initial_vertex_connected_bnd_id() [2/2]
unsigned oomph::TriangleMeshCurveSection::initial_vertex_connected_bnd_id () const inline
Gets the id to which the initial end is connected.
     {
       return Initial_vertex_connected_bnd_id;
     }
References Initial_vertex_connected_bnd_id.
Referenced by oomph::TriangleMeshPolyLine::reverse().
initial_vertex_connected_n_chunk() [1/2]
unsigned& oomph::TriangleMeshCurveSection::initial_vertex_connected_n_chunk () inline
Sets the boundary chunk to which the initial end is connected.
     {
       return Initial_vertex_connected_n_chunk;
     }
References Initial_vertex_connected_n_chunk.
initial_vertex_connected_n_chunk() [2/2]
unsigned oomph::TriangleMeshCurveSection::initial_vertex_connected_n_chunk () const inline
Gets the boundary chunk to which the initial end is connected.
     {
       return Initial_vertex_connected_n_chunk;
     }
References Initial_vertex_connected_n_chunk.
Referenced by oomph::TriangleMeshPolyLine::reverse().
initial_vertex_connected_n_vertex() [1/2]
unsigned& oomph::TriangleMeshCurveSection::initial_vertex_connected_n_vertex () inline
Sets the vertex number to which the initial end is connected.
     {
       return Initial_vertex_connected_n_vertex;
     }
References Initial_vertex_connected_n_vertex.
initial_vertex_connected_n_vertex() [2/2]
unsigned oomph::TriangleMeshCurveSection::initial_vertex_connected_n_vertex () const inline
Gets the vertex number to which the initial end is connected.
     {
       return Initial_vertex_connected_n_vertex;
     }
References Initial_vertex_connected_n_vertex.
Referenced by oomph::TriangleMeshPolyLine::reverse().
initial_vertex_coordinate()
virtual void oomph::TriangleMeshCurveSection::initial_vertex_coordinate (Vector< double > & vertex) pure virtual
Get first vertex coordinates.
Implemented in oomph::TriangleMeshPolyLine, and oomph::TriangleMeshCurviLine.
Referenced by connect_initial_vertex_to_curviline(), connect_initial_vertex_to_polyline(), and oomph::TriangleMeshClosedCurve::TriangleMeshClosedCurve().
is_final_vertex_connected()
bool oomph::TriangleMeshCurveSection::is_final_vertex_connected () const inline
Test whether final vertex is connected or not.
     {
       return Final_vertex_connected;
     }
References Final_vertex_connected.
Referenced by oomph::TriangleMeshPolyLine::reverse().
is_final_vertex_connected_to_curviline()
bool oomph::TriangleMeshCurveSection::is_final_vertex_connected_to_curviline () const inline
Test whether the final vertex is connected to a curviline.
     {
       return Final_vertex_connected_to_curviline;
     }
References Final_vertex_connected_to_curviline.
Referenced by oomph::TriangleMeshPolyLine::reverse().
is_initial_vertex_connected()
bool oomph::TriangleMeshCurveSection::is_initial_vertex_connected () const inline
Test whether initial vertex is connected or not.
     {
       return Initial_vertex_connected;
     }
References Initial_vertex_connected.
Referenced by oomph::TriangleMeshPolyLine::reverse().
is_initial_vertex_connected_to_curviline()
bool oomph::TriangleMeshCurveSection::is_initial_vertex_connected_to_curviline () const inline
Test whether the initial vertex is connected to a curviline.
     {
       return Initial_vertex_connected_to_curviline;
     }
References Initial_vertex_connected_to_curviline.
Referenced by oomph::TriangleMeshPolyLine::reverse().
maximum_length()
double oomph::TriangleMeshCurveSection::maximum_length () inline
Gets access to the maximum length variable.
     {
       return Maximum_length;
     }
References Maximum_length.
Referenced by set_maximum_length().
nsegment()
virtual unsigned oomph::TriangleMeshCurveSection::nsegment () const pure virtual
Number of segments that this part of the boundary is to be represented by. This corresponds to the number of straight-line segments in triangle representation.
Implemented in oomph::TriangleMeshPolyLine, and oomph::TriangleMeshCurviLine.
nvertex()
virtual unsigned oomph::TriangleMeshCurveSection::nvertex () const pure virtual
Number of vertices.
Implemented in oomph::TriangleMeshPolyLine, and oomph::TriangleMeshCurviLine.
output()
virtual void oomph::TriangleMeshCurveSection::output (std::ostream & outfile, const unsigned & n_sample = 50) pure virtual
Output the curve_section.
Implemented in oomph::TriangleMeshPolyLine, and oomph::TriangleMeshCurviLine.
refinement_tolerance()
double oomph::TriangleMeshCurveSection::refinement_tolerance () inline
Get tolerance for refinement of curve sections to create a better representation of curvilinear boundaries (e.g. in free-surface problems). See tutorial for interpretation. If it's negative refinement is disabled.
     {
       return Refinement_tolerance;
     }
References Refinement_tolerance.
resume_final_vertex_connected()
void oomph::TriangleMeshCurveSection::resume_final_vertex_connected () inline
Resumes the final vertex connection, it may be that after load balancing the boundary to which the connection was suspended be part of the domain
     {
       if (Final_vertex_connected_suspended)
       {
         Final_vertex_connected = true;
         Final_vertex_connected_suspended = false;
       }
     }
References Final_vertex_connected, and Final_vertex_connected_suspended.
resume_initial_vertex_connected()
void oomph::TriangleMeshCurveSection::resume_initial_vertex_connected () inline
Resumes the initial vertex connection, it may be that after load balancing the boundary to which the connection was suspended be part of the domain
     {
       if (Initial_vertex_connected_suspended)
       {
         Initial_vertex_connected = true;
         Initial_vertex_connected_suspended = false;
       }
     }
References Initial_vertex_connected, and Initial_vertex_connected_suspended.
set_final_vertex_connected()
void oomph::TriangleMeshCurveSection::set_final_vertex_connected () inline
Sets the final vertex as connected.
     {
       Final_vertex_connected = true;
     }
References Final_vertex_connected.
Referenced by oomph::TriangleMeshPolyLine::reverse().
set_final_vertex_connected_to_curviline()
void oomph::TriangleMeshCurveSection::set_final_vertex_connected_to_curviline () inline
Sets the final vertex as connected to a curviline.
     {
       Final_vertex_connected_to_curviline = true;
     }
References Final_vertex_connected_to_curviline.
Referenced by oomph::TriangleMeshPolyLine::reverse().
set_initial_vertex_connected()
void oomph::TriangleMeshCurveSection::set_initial_vertex_connected () inline
Sets the initial vertex as connected.
     {
       Initial_vertex_connected = true;
     }
References Initial_vertex_connected.
Referenced by oomph::TriangleMeshPolyLine::reverse().
set_initial_vertex_connected_to_curviline()
void oomph::TriangleMeshCurveSection::set_initial_vertex_connected_to_curviline () inline
Sets the initial vertex as connected to a curviline.
     {
       Initial_vertex_connected_to_curviline = true;
     }
References Initial_vertex_connected_to_curviline.
Referenced by oomph::TriangleMeshPolyLine::reverse().
set_maximum_length()
void oomph::TriangleMeshCurveSection::set_maximum_length (const double & maximum_length) inline
Allows to specify the maximum distance between two vertices that define the associated polyline of the curve section, it only takes effect on the unrefinement and refinement steps
     {
       Maximum_length = maximum_length;
     }
References maximum_length(), and Maximum_length.
Referenced by ContactProblem< ELEMENT >::actions_before_adapt(), and MeltContactProblem< ELEMENT >::MeltContactProblem().
set_refinement_tolerance()
void oomph::TriangleMeshCurveSection::set_refinement_tolerance (const double & tolerance) inline
Set tolerance for refinement of curve sections to create a better representation of curvilinear boundaries (e.g. in free-surface problems). See tutorial for interpretation of the refinement tolerance. (The smaller the number the finer the surface representation). If set to a negative value, we're switching off refinement – equivalent to calling disable_polyline_refinement()
     {
       Refinement_tolerance = tolerance;
     }
References Refinement_tolerance.
set_unrefinement_tolerance()
void oomph::TriangleMeshCurveSection::set_unrefinement_tolerance (const double & tolerance) inline
Set tolerance for unrefinement of curve sections to avoid unnecessarily large numbers of elements on of curvilinear boundaries (e.g. in free-surface problems). See tutorial for interpretation of the optional argument which specifies the unrefinement tolerance. It defaults to 0.04 and the larger the number the more agressive we are when removing unnecessary vertices on gently curved polylines. If set to a negative value, we're switching off unrefinement – equivalent to calling disable_curve_section_unrefinement()
     {
       Unrefinement_tolerance = tolerance;
     }
References Unrefinement_tolerance.
suspend_final_vertex_connected()
void oomph::TriangleMeshCurveSection::suspend_final_vertex_connected () inline
Set the final vertex connection as suspended, it will be resumed when the method to resume the connections is called This method is only used in a distributed context, when the boundary to connect is no longer part of the domain in the processor
     {
       if (Final_vertex_connected)
       {
         Final_vertex_connected = false;
         Final_vertex_connected_suspended = true;
       }
     }
References Final_vertex_connected, and Final_vertex_connected_suspended.
suspend_initial_vertex_connected()
void oomph::TriangleMeshCurveSection::suspend_initial_vertex_connected () inline
Set the initial vertex connection as suspended, it will be resumed when the method to resume the connections is called This method is only used in a distributed context, when the boundary to connect is no longer part of the domain in the processor
     {
       if (Initial_vertex_connected)
       {
         Initial_vertex_connected = false;
         Initial_vertex_connected_suspended = true;
       }
     }
References Initial_vertex_connected, and Initial_vertex_connected_suspended.
tolerance_for_s_connection() [1/2]
double& oomph::TriangleMeshCurveSection::tolerance_for_s_connection () inline
Sets the tolerance value for connections among curvilines
     {
       return Tolerance_for_s_connection;
     }
References Tolerance_for_s_connection.
tolerance_for_s_connection() [2/2]
double oomph::TriangleMeshCurveSection::tolerance_for_s_connection () const inline
Gets the tolerance value for connections among curvilines
     {
       return Tolerance_for_s_connection;
     }
References Tolerance_for_s_connection.
Referenced by oomph::TriangleMeshPolyLine::reverse().
unrefinement_tolerance()
double oomph::TriangleMeshCurveSection::unrefinement_tolerance () inline
Get tolerance for unrefinement of curve section to create a better representation of curvilinear boundaries (e.g. in free-surface problems). See tutorial for interpretation. If it's negative unrefinement is disabled.
     {
       return Unrefinement_tolerance;
     }
References Unrefinement_tolerance.
unset_final_vertex_connected()
void oomph::TriangleMeshCurveSection::unset_final_vertex_connected () inline
Sets the final vertex as non connected.
     {
       Final_vertex_connected = false;
     }
References Final_vertex_connected.
Referenced by oomph::TriangleMeshPolyLine::reverse().
unset_final_vertex_connected_to_curviline()
void oomph::TriangleMeshCurveSection::unset_final_vertex_connected_to_curviline () inline
Sets the final vertex as non connected to a curviline.
     {
       Final_vertex_connected_to_curviline = false;
     }
References Final_vertex_connected_to_curviline.
Referenced by oomph::TriangleMeshPolyLine::reverse().
unset_initial_vertex_connected()
void oomph::TriangleMeshCurveSection::unset_initial_vertex_connected () inline
Sets the initial vertex as non connected.
     {
       Initial_vertex_connected = false;
     }
References Initial_vertex_connected.
Referenced by oomph::TriangleMeshPolyLine::reverse().
unset_initial_vertex_connected_to_curviline()
void oomph::TriangleMeshCurveSection::unset_initial_vertex_connected_to_curviline () inline
Sets the initial vertex as non connected to a curviline.
     {
       Initial_vertex_connected_to_curviline = false;
     }
References Initial_vertex_connected_to_curviline.
Referenced by oomph::TriangleMeshPolyLine::reverse().
Member Data Documentation
Final_s_connection_value
double oomph::TriangleMeshCurveSection::Final_s_connection_value protected
Stores the s value used for connecting the final end with a curviline
Referenced by connect_final_vertex_to_curviline(), and final_s_connection_value().
Final_vertex_connected
bool oomph::TriangleMeshCurveSection::Final_vertex_connected protected
Used for stating if the final end is connected to another boundary
Referenced by connect_final_vertex_to_curviline(), connect_final_vertex_to_polyline(), is_final_vertex_connected(), resume_final_vertex_connected(), set_final_vertex_connected(), suspend_final_vertex_connected(), and unset_final_vertex_connected().
Final_vertex_connected_bnd_id
unsigned oomph::TriangleMeshCurveSection::Final_vertex_connected_bnd_id protected
Stores the id to which the initial end is connected.
Referenced by connect_final_vertex_to_curviline(), connect_final_vertex_to_polyline(), and final_vertex_connected_bnd_id().
Final_vertex_connected_n_chunk
unsigned oomph::TriangleMeshCurveSection::Final_vertex_connected_n_chunk protected
Stores the chunk number of the boundary to which is connected th initial end
Referenced by connect_final_vertex_to_curviline(), connect_final_vertex_to_polyline(), and final_vertex_connected_n_chunk().
Final_vertex_connected_n_vertex
unsigned oomph::TriangleMeshCurveSection::Final_vertex_connected_n_vertex protected
Stores the vertex number used for connection with the final end
Referenced by connect_final_vertex_to_polyline(), and final_vertex_connected_n_vertex().
Final_vertex_connected_suspended
bool oomph::TriangleMeshCurveSection::Final_vertex_connected_suspended protected
Indicates if the connection is suspended because the boundary to connect is no longer part of the domain (only used in a distributed context)
Referenced by resume_final_vertex_connected(), and suspend_final_vertex_connected().
Final_vertex_connected_to_curviline
bool oomph::TriangleMeshCurveSection::Final_vertex_connected_to_curviline protected
States if the final vertex is connected to a curviline.
Referenced by connect_final_vertex_to_curviline(), is_final_vertex_connected_to_curviline(), set_final_vertex_connected_to_curviline(), and unset_final_vertex_connected_to_curviline().
Initial_s_connection_value
double oomph::TriangleMeshCurveSection::Initial_s_connection_value protected
Stores the s value used for connecting the initial end with a curviline
Referenced by connect_initial_vertex_to_curviline(), and initial_s_connection_value().
Initial_vertex_connected
bool oomph::TriangleMeshCurveSection::Initial_vertex_connected protected
Used for stating if the initial end is connected to another boundary
Referenced by connect_initial_vertex_to_curviline(), connect_initial_vertex_to_polyline(), is_initial_vertex_connected(), resume_initial_vertex_connected(), set_initial_vertex_connected(), suspend_initial_vertex_connected(), and unset_initial_vertex_connected().
Initial_vertex_connected_bnd_id
unsigned oomph::TriangleMeshCurveSection::Initial_vertex_connected_bnd_id protected
Stores the id to which the initial end is connected.
Referenced by connect_initial_vertex_to_curviline(), connect_initial_vertex_to_polyline(), and initial_vertex_connected_bnd_id().
Initial_vertex_connected_n_chunk
unsigned oomph::TriangleMeshCurveSection::Initial_vertex_connected_n_chunk protected
Stores the chunk number of the boundary to which is connected th initial end
Referenced by connect_initial_vertex_to_curviline(), connect_initial_vertex_to_polyline(), and initial_vertex_connected_n_chunk().
Initial_vertex_connected_n_vertex
unsigned oomph::TriangleMeshCurveSection::Initial_vertex_connected_n_vertex protected
Stores the vertex number used for connection with the initial end
Referenced by connect_initial_vertex_to_polyline(), and initial_vertex_connected_n_vertex().
Initial_vertex_connected_suspended
bool oomph::TriangleMeshCurveSection::Initial_vertex_connected_suspended protected
Indicates if the connection is suspended because the boundary to connect is no longer part of the domain (only used in a distributed context)
Referenced by resume_initial_vertex_connected(), and suspend_initial_vertex_connected().
Initial_vertex_connected_to_curviline
bool oomph::TriangleMeshCurveSection::Initial_vertex_connected_to_curviline protected
States if the initial vertex is connected to a curviline.
Referenced by connect_initial_vertex_to_curviline(), is_initial_vertex_connected_to_curviline(), set_initial_vertex_connected_to_curviline(), and unset_initial_vertex_connected_to_curviline().
Maximum_length
double oomph::TriangleMeshCurveSection::Maximum_length private
Maximum allowed distance between two vertices on the polyline representation of the curve section
Referenced by disable_use_maximum_length(), maximum_length(), and set_maximum_length().
Refinement_tolerance
double oomph::TriangleMeshCurveSection::Refinement_tolerance private
Tolerance for refinement of curve sections (neg if refinement is disabled)
Referenced by disable_refinement_tolerance(), enable_refinement_tolerance(), refinement_tolerance(), and set_refinement_tolerance().
Tolerance_for_s_connection
double oomph::TriangleMeshCurveSection::Tolerance_for_s_connection protected
Tolerance used for connecting the ends to a curviline.
Referenced by connect_final_vertex_to_curviline(), connect_initial_vertex_to_curviline(), and tolerance_for_s_connection().
Unrefinement_tolerance
double oomph::TriangleMeshCurveSection::Unrefinement_tolerance private
Tolerance for unrefinement of curve sections (neg if refinement is disabled)
Referenced by disable_unrefinement_tolerance(), enable_unrefinement_tolerance(), set_unrefinement_tolerance(), and unrefinement_tolerance().
The documentation for this class was generated from the following files:
unstructured_two_d_mesh_geometry_base.h
unstructured_two_d_mesh_geometry_base.cc