MercuryDPM: Eigen::internal::CoeffLoader< Tensor, HasRawAccess, MakePointer_ > Struct Template Reference
Eigen::internal::CoeffLoader< Tensor, HasRawAccess, MakePointer_ > Struct Template Reference
#include <TensorContractionMapper.h>
Public Types
enum { DirectOffsets = false }
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE CoeffLoader (const Tensor &tensor)
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE void offsetBuffer (typename Tensor::Index)
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE const MakePointer_< const typename Tensor::Scalar >::Type data () const
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE Tensor::Scalar coeff (typename Tensor::Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Tensor::PacketReturnType packet (typename Tensor::Index index) const
Private Attributes
const Tensor m_tensor
Detailed Description
template<typename Tensor, bool HasRawAccess, template< class > class MakePointer_>
struct Eigen::internal::CoeffLoader< Tensor, HasRawAccess, MakePointer_ >
The make pointer class is used by sycl in order to build the mapper class on the device. For other platform the default make pointer is used which is scalar * for CoeffLoader.
Member Enumeration Documentation
anonymous enum
template<typename Tensor , bool HasRawAccess, template< class > class MakePointer_> anonymous enum
Enumerator
DirectOffsets
 { DirectOffsets = false };
Constructor & Destructor Documentation
CoeffLoader()
template<typename Tensor , bool HasRawAccess, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE Eigen::internal::CoeffLoader< Tensor, HasRawAccess, MakePointer_ >::CoeffLoader (const Tensor & tensor) inline
 : m_tensor(tensor) {}
Member Function Documentation
coeff()
template<typename Tensor , bool HasRawAccess, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE Tensor::Scalar Eigen::internal::CoeffLoader< Tensor, HasRawAccess, MakePointer_ >::coeff (typename Tensor::Index index) const inline
{
     return m_tensor.coeff(index);
   }
References Eigen::Tensor< Scalar_, NumIndices_, Options_, IndexType_ >::coeff(), and Eigen::internal::CoeffLoader< Tensor, HasRawAccess, MakePointer_ >::m_tensor.
data()
template<typename Tensor , bool HasRawAccess, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE const MakePointer_<const typename Tensor::Scalar>::Type Eigen::internal::CoeffLoader< Tensor, HasRawAccess, MakePointer_ >::data () const inline
{
     eigen_assert(false && "unsupported");
     return NULL;
   }
References eigen_assert.
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
offsetBuffer()
template<typename Tensor , bool HasRawAccess, template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE void Eigen::internal::CoeffLoader< Tensor, HasRawAccess, MakePointer_ >::offsetBuffer (typename Tensor::Index) inline
{
     eigen_assert(false && "unsupported");
   }
References eigen_assert.
packet()
template<typename Tensor , bool HasRawAccess, template< class > class MakePointer_> template<int LoadMode> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Tensor::PacketReturnType Eigen::internal::CoeffLoader< Tensor, HasRawAccess, MakePointer_ >::packet (typename Tensor::Index index) const inline
{
     return m_tensor.template packet<LoadMode>(index);
   }
References Eigen::internal::CoeffLoader< Tensor, HasRawAccess, MakePointer_ >::m_tensor.
Member Data Documentation
m_tensor
template<typename Tensor , bool HasRawAccess, template< class > class MakePointer_> const Tensor Eigen::internal::CoeffLoader< Tensor, HasRawAccess, MakePointer_ >::m_tensor private
Referenced by Eigen::internal::CoeffLoader< Tensor, HasRawAccess, MakePointer_ >::coeff(), and Eigen::internal::CoeffLoader< Tensor, HasRawAccess, MakePointer_ >::packet().
The documentation for this struct was generated from the following file:
TensorContractionMapper.h