MercuryDPM: Eigen::internal::dense_assignment_loop< Kernel, SliceVectorizedTraversal, NoUnrolling > Struct Template Reference
Eigen::internal::dense_assignment_loop< Kernel, SliceVectorizedTraversal, NoUnrolling > Struct Template Reference
#include <AssignEvaluator.h>
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EIGEN_CONSTEXPR void run (Kernel &kernel)
Member Function Documentation
run()
template<typename Kernel > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EIGEN_CONSTEXPR void Eigen::internal::dense_assignment_loop< Kernel, SliceVectorizedTraversal, NoUnrolling >::run (Kernel & kernel) inline static
{
     typedef typename Kernel::Scalar Scalar;
     typedef typename Kernel::PacketType PacketType;
     enum {
       packetSize = unpacket_traits<PacketType>::size,
       requestedAlignment = int(Kernel::AssignmentTraits::InnerRequiredAlignment),
       alignable =
           packet_traits<Scalar>::AlignedOnScalar || int(Kernel::AssignmentTraits::DstAlignment) >= sizeof(Scalar),
       dstIsAligned = int(Kernel::AssignmentTraits::DstAlignment) >= int(requestedAlignment),
       dstAlignment = alignable ? int(requestedAlignment) : int(Kernel::AssignmentTraits::DstAlignment)
     };
     const Scalar* dst_ptr = kernel.dstDataPtr();
     if ((!bool(dstIsAligned)) && (std::uintptr_t(dst_ptr) % sizeof(Scalar)) > 0) {
       // the pointer is not aligned-on scalar, so alignment is not possible
       return dense_assignment_loop<Kernel, DefaultTraversal, NoUnrolling>::run(kernel);
     }
     const Index packetAlignedMask = packetSize - 1;
     const Index innerSize = kernel.innerSize();
     const Index outerSize = kernel.outerSize();
     const Index alignedStep = alignable ? (packetSize - kernel.outerStride() % packetSize) & packetAlignedMask : 0;
     Index alignedStart =
         ((!alignable) || bool(dstIsAligned)) ? 0 : internal::first_aligned<requestedAlignment>(dst_ptr, innerSize);
     for (Index outer = 0; outer < outerSize; ++outer) {
       const Index alignedEnd = alignedStart + ((innerSize - alignedStart) & ~packetAlignedMask);
       // do the non-vectorizable part of the assignment
       for (Index inner = 0; inner < alignedStart; ++inner) kernel.assignCoeffByOuterInner(outer, inner);
       // do the vectorizable part of the assignment
       for (Index inner = alignedStart; inner < alignedEnd; inner += packetSize)
         kernel.template assignPacketByOuterInner<dstAlignment, Unaligned, PacketType>(outer, inner);
       // do the non-vectorizable part of the assignment
       for (Index inner = alignedEnd; inner < innerSize; ++inner) kernel.assignCoeffByOuterInner(outer, inner);
       alignedStart = numext::mini((alignedStart + alignedStep) % packetSize, innerSize);
     }
   }
References int(), Eigen::numext::mini(), and run().
The documentation for this struct was generated from the following file:
AssignEvaluator.h