MercuryDPM: Eigen::Ref< const TPlainObjectType, Options, StrideType > Class Template Reference
Eigen::Ref< const TPlainObjectType, Options, StrideType > Class Template Reference
#include <Ref.h>
Public Types
typedef RefBase< Ref > Base
Public Types inherited from Eigen::RefBase< Ref< const TPlainObjectType, Options, StrideType > >
typedef MapBase< Ref< const TPlainObjectType, Options, StrideType > > Base
Public Member Functions
template<typename Derived >
EIGEN_DEVICE_FUNC Ref (const DenseBase< Derived > &expr, std::enable_if_t< bool(Traits::template match< Derived >::ScalarTypeMatch), Derived > *=0)
EIGEN_DEVICE_FUNC Ref (const Ref &other)
EIGEN_DEVICE_FUNC Ref (Ref &&other)
template<typename OtherRef >
EIGEN_DEVICE_FUNC Ref (const RefBase< OtherRef > &other)
Public Member Functions inherited from Eigen::RefBase< Ref< const TPlainObjectType, Options, StrideType > >
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index innerStride () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index outerStride () const
EIGEN_DEVICE_FUNC RefBase ()
Protected Member Functions
template<typename Expression >
EIGEN_DEVICE_FUNC void construct (const Expression &expr, internal::true_type)
template<typename Expression >
EIGEN_DEVICE_FUNC void construct (const Expression &expr, internal::false_type)
Protected Member Functions inherited from Eigen::RefBase< Ref< const TPlainObjectType, Options, StrideType > >
EIGEN_DEVICE_FUNC bool construct (Expression &expr)
Protected Attributes
TPlainObjectType m_object
Protected Attributes inherited from Eigen::RefBase< Ref< const TPlainObjectType, Options, StrideType > >
StrideBase m_stride
Private Types
typedef internal::traits< Ref > Traits
Static Private Attributes
static constexpr bool may_map_m_object_successfully
Additional Inherited Members
Protected Types inherited from Eigen::RefBase< Ref< const TPlainObjectType, Options, StrideType > >
typedef Stride< StrideType::OuterStrideAtCompileTime, StrideType::InnerStrideAtCompileTime > StrideBase
Static Protected Member Functions inherited from Eigen::RefBase< Ref< const TPlainObjectType, Options, StrideType > >
static EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index resolveInnerStride (Index inner)
static EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index resolveOuterStride (Index inner, Index outer, Index rows, Index cols, bool isVectorAtCompileTime, bool isRowMajor)
Member Typedef Documentation
Base
template<typename TPlainObjectType , int Options, typename StrideType > typedef RefBase<Ref> Eigen::Ref< const TPlainObjectType, Options, StrideType >::Base
Traits
template<typename TPlainObjectType , int Options, typename StrideType > typedef internal::traits<Ref> Eigen::Ref< const TPlainObjectType, Options, StrideType >::Traits private
Constructor & Destructor Documentation
Ref() [1/4]
template<typename TPlainObjectType , int Options, typename StrideType > template<typename Derived > EIGEN_DEVICE_FUNC Eigen::Ref< const TPlainObjectType, Options, StrideType >::Ref (const DenseBase< Derived > & expr, std::enable_if_t< bool(Traits::template match< Derived >::ScalarTypeMatch), Derived > * = 0) inline
{
     //      std::cout << match_helper<Derived>::HasDirectAccess << "," << match_helper<Derived>::OuterStrideMatch << ","
     //      << match_helper<Derived>::InnerStrideMatch << "\n"; std::cout << int(StrideType::OuterStrideAtCompileTime)
     //      << " - " << int(Derived::OuterStrideAtCompileTime) << "\n"; std::cout <<
     //      int(StrideType::InnerStrideAtCompileTime) << " - " << int(Derived::InnerStrideAtCompileTime) << "\n";
     EIGEN_STATIC_ASSERT(Traits::template match<Derived>::type::value || may_map_m_object_successfully,
                         STORAGE_LAYOUT_DOES_NOT_MATCH);
     construct(expr.derived(), typename Traits::template match<Derived>::type());
   }
References Eigen::RefBase< Ref< PlainObjectType, Options, StrideType > >::construct(), EIGEN_STATIC_ASSERT, compute_granudrum_aor::type, and Eigen::value.
Ref() [2/4]
template<typename TPlainObjectType , int Options, typename StrideType > EIGEN_DEVICE_FUNC Eigen::Ref< const TPlainObjectType, Options, StrideType >::Ref (const Ref< const TPlainObjectType, Options, StrideType > & other) inline
                                                  : Base(other) {
     // copy constructor shall not copy the m_object, to avoid unnecessary malloc and copy
   }
Ref() [3/4]
template<typename TPlainObjectType , int Options, typename StrideType > EIGEN_DEVICE_FUNC Eigen::Ref< const TPlainObjectType, Options, StrideType >::Ref (Ref< const TPlainObjectType, Options, StrideType > && other) inline
{
     if (other.data() == other.m_object.data()) {
       m_object = std::move(other.m_object);
       Base::construct(m_object);
     } else
       Base::construct(other);
   }
References Eigen::RefBase< Derived >::construct().
Ref() [4/4]
template<typename TPlainObjectType , int Options, typename StrideType > template<typename OtherRef > EIGEN_DEVICE_FUNC Eigen::Ref< const TPlainObjectType, Options, StrideType >::Ref (const RefBase< OtherRef< const TPlainObjectType, Options, StrideType > > & other) inline
{
     EIGEN_STATIC_ASSERT(Traits::template match<OtherRef>::type::value || may_map_m_object_successfully,
                         STORAGE_LAYOUT_DOES_NOT_MATCH);
     construct(other.derived(), typename Traits::template match<OtherRef>::type());
   }
References Eigen::RefBase< Ref< PlainObjectType, Options, StrideType > >::construct(), EIGEN_STATIC_ASSERT, compute_granudrum_aor::type, and Eigen::value.
Member Function Documentation
construct() [1/2]
template<typename TPlainObjectType , int Options, typename StrideType > template<typename Expression > EIGEN_DEVICE_FUNC void Eigen::Ref< const TPlainObjectType, Options, StrideType >::construct (const Expression & expr, internal::false_type) inline protected
{
     internal::call_assignment_no_alias(m_object, expr, internal::assign_op<Scalar, Scalar>());
     const bool success = Base::construct(m_object);
     EIGEN_ONLY_USED_FOR_DEBUG(success)
     eigen_assert(success);
   }
References Eigen::internal::call_assignment_no_alias(), Eigen::RefBase< Derived >::construct(), eigen_assert, and EIGEN_ONLY_USED_FOR_DEBUG.
construct() [2/2]
template<typename TPlainObjectType , int Options, typename StrideType > template<typename Expression > EIGEN_DEVICE_FUNC void Eigen::Ref< const TPlainObjectType, Options, StrideType >::construct (const Expression & expr, internal::true_type) inline protected
{
     // Check if we can use the underlying expr's storage directly, otherwise call the copy version.
     if (!Base::construct(expr)) {
       construct(expr, internal::false_type());
     }
   }
References Eigen::RefBase< Ref< PlainObjectType, Options, StrideType > >::construct(), and Eigen::RefBase< Derived >::construct().
Member Data Documentation
m_object
template<typename TPlainObjectType , int Options, typename StrideType > TPlainObjectType Eigen::Ref< const TPlainObjectType, Options, StrideType >::m_object protected
may_map_m_object_successfully
template<typename TPlainObjectType , int Options, typename StrideType > constexpr bool Eigen::Ref< const TPlainObjectType, Options, StrideType >::may_map_m_object_successfully static constexpr private
Initial value:
=
      (static_cast<int>(StrideType::InnerStrideAtCompileTime) == 0 ||
       static_cast<int>(StrideType::InnerStrideAtCompileTime) == 1 ||
       static_cast<int>(StrideType::InnerStrideAtCompileTime) == Dynamic) &&
      (TPlainObjectType::IsVectorAtCompileTime || static_cast<int>(StrideType::OuterStrideAtCompileTime) == 0 ||
       static_cast<int>(StrideType::OuterStrideAtCompileTime) == Dynamic ||
       static_cast<int>(StrideType::OuterStrideAtCompileTime) ==
           static_cast<int>(TPlainObjectType::InnerSizeAtCompileTime) ||
       static_cast<int>(TPlainObjectType::InnerSizeAtCompileTime) == Dynamic)
The documentation for this class was generated from the following file:
Ref.h