MercuryDPM: ConvertP4Files.cpp File Reference
ConvertP4Files.cpp File Reference
#include <string>
#include <iomanip>
#include <iostream>
#include <fstream>
#include <sstream>
#include <sys/stat.h>
#include <cstdio>
#include <cstdlib>
#include <vector>
#include "Math/ExtendedMath.h"
#include "Math/Helpers.h"
#include "Math/Vector.h"
Classes
class CFile
takes data and fstat files and splits them into *.data.???? and *.fstat.???? files
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
 {
     if (argc<8)
     {
         if (argc < 2)
         {
             logger(INFO, "no arguments given, so a test file is converted; to convert your own p4 files, use:\n"
                          "convertP4Files.cpp name xmin xmax ymin ymax zmin zmax [timeMin [timeMax [periodic]]]");
             helpers::writeToFile("test.p4p",
                                  "TIMESTEP PARTICLES\n"
                                  "0  2\n"
                                  "ID GROUP VOLUME MASS PX PY PZ VX VY VZ Angular_Velocity_X Angular_Velocity_Y Angular_Velocity_Z\n"
                                  "1 1 0.52359877559 1 0.5 0.5 0.5 1 0 0 0 0 1\n"
                                  "3 1 0.52359877559 1 3.5 0.5 0.5 0 0 0 0 0 0\n"
                                  "TIMESTEP PARTICLES\n"
                                  "2  2\n"
                                  "ID GROUP VOLUME MASS PX PY PZ VX VY VZ Angular_Velocity_X Angular_Velocity_Y Angular_Velocity_Z\n"
                                  "1 1 0.52359877559 1 0.5 0.5 0.5 1 0 0 0 0 1\n"
                                  "3 1 0.52359877559 1 3.5 0.5 0.5 0 0 0 0 0 0\n"
             );
             helpers::writeToFile("test.p4c",
                 "TIMESTEP CONTACTS\n"
                     "0  1\n"
                     "P1 P2 CX CY CZ FX FY FZ\n"
                     "1 3 0 0.5 0.5 1 1 0\n"
                     "TIMESTEP CONTACTS\n"
                     "2  1\n"
                     "P1 P2 CX CY CZ FX FY FZ\n"
                     "1 3 4 0.5 0.5 1 1 0\n"
             );
             helpers::writeToFile("test.p4w",
                 "TIMESTEP CONTACTS\n"
                     "0  2\n"
                     "P1 CX CY CZ FX FY FZ\n"
                     "1 0.5 0.5 0 0 0 1\n"
                     "3 3.5 0.5 0 0 0 1\n"
                     "TIMESTEP CONTACTS\n"
                     "2  2\n"
                     "P1 CX CY CZ FX FY FZ\n"
                     "1 0.5 0.5 0 0 0 1\n"
                     "3 3.5 0.5 0 0 0 1\n"
             );
             CFile files("test");
             files.copy(0,4,0,1,0,1,-1,1e20,1);
         }
         else
         {
             logger(ERROR, "convertP4Files.cpp problem_name xmin xmax ymin ymax zmin zmax [timeMin [timeMax "
                           "[periodic]]]");
         }
     }
     else
     {
         std::string name(argv[1]);
         logger(INFO, "converting %", name);
         double timeMin = -1;
         if (argc>8) {
             timeMin = atof(argv[8]);
             logger(INFO, "timeMin %", timeMin);
         }
         double timeMax = 1e20;
         if (argc>9) {
             timeMax = atof(argv[9]);
             logger(INFO, "timeMax %", timeMax);
         }
         unsigned int periodic = 0;
         if (argc > 10)
         {
             periodic = static_cast<unsigned int>(atoi(argv[10]));
             logger(INFO, "periodic %", periodic);
         }
         CFile files(name);
         files.copy(atof(argv[2]), atof(argv[3]), atof(argv[4]), atof(argv[5]), atof(argv[6]), atof(argv[7]), timeMin,
                    timeMax, periodic);
         logger(INFO, "finished converting %", name);
     }
 }
References CFile::copy(), ERROR, INFO, logger, plotDoE::name, oomph::Global_string_for_annotation::string(), and helpers::writeToFile().