MercuryDPM: TanhSolnForLinearWave Namespace Reference
TanhSolnForLinearWave Namespace Reference
Functions
double exact_u (const double &time, const Vector< double > &x)
Exact solution.
double exact_dudt (const double &time, const Vector< double > &x)
1st time-deriv of exact solution
double exact_d2udt2 (const double &time, const Vector< double > &x)
2nd time-deriv of exact solution
void get_exact_u (const double &time, const Vector< double > &x, Vector< double > &u)
Exact solution as a vector.
void get_source (const double &time, const Vector< double > &x, double &source)
Source function to make it an exact solution.
void get_exact_gradient (const double &time, const Vector< double > &x, Vector< double > &dudx)
Gradient of exact solution.
void prescribed_flux_on_fixed_y_boundary (const double &time, const Vector< double > &x, double &flux)
Prescribed flux on a fixed y max boundary.
Variables
double Alpha
Parameter for steepness of step.
double Phi
Orientation of step wave.
Detailed Description
Namespace for exact solution for LinearWave equation with sharp step
Namespace for travelling wave solution for LinearWave equation with sharp step
Function Documentation
exact_d2udt2()
double TanhSolnForLinearWave::exact_d2udt2 (const double & time, const Vector< double > & x)
2nd time-deriv of exact solution
  {
   double zeta=cos(Phi)*x[0]+sin(Phi)*x[1];
   return -2.0*Alpha*Alpha*tanh(1.0-Alpha*(zeta-time))/
    (cosh(1.0-Alpha*(zeta-time))*cosh(1.0-Alpha*(zeta-time)));
  }
References Alpha, cos(), Eigen::bfloat16_impl::cosh(), Phi, sin(), Eigen::bfloat16_impl::tanh(), plotDoE::x, and Eigen::zeta().
Referenced by LinearWaveProblem< ELEMENT, TIMESTEPPER >::actions_before_implicit_timestep(), get_exact_u(), and LinearWaveProblem< ELEMENT, TIMESTEPPER >::set_initial_condition().
exact_dudt()
double TanhSolnForLinearWave::exact_dudt (const double & time, const Vector< double > & x)
1st time-deriv of exact solution
  {
   double zeta=cos(Phi)*x[0]+sin(Phi)*x[1];
   return Alpha/(cosh(1.0-Alpha*(zeta-time))*
               cosh(1.0-Alpha*(zeta-time)));
  }
References Alpha, cos(), Eigen::bfloat16_impl::cosh(), Phi, sin(), plotDoE::x, and Eigen::zeta().
Referenced by LinearWaveProblem< ELEMENT, TIMESTEPPER >::actions_before_implicit_timestep(), get_exact_u(), and LinearWaveProblem< ELEMENT, TIMESTEPPER >::set_initial_condition().
exact_u()
double TanhSolnForLinearWave::exact_u (const double & time, const Vector< double > & x)
Exact solution.
  {
   double zeta=cos(Phi)*x[0]+sin(Phi)*x[1];
   return tanh(1.0-Alpha*(zeta-time));
  }
References Alpha, cos(), Phi, sin(), Eigen::bfloat16_impl::tanh(), plotDoE::x, and Eigen::zeta().
Referenced by LinearWaveProblem< ELEMENT, TIMESTEPPER >::actions_before_implicit_timestep(), PolarNSProblem< ELEMENT >::actions_before_solve(), oomph::EulerEquations< DIM >::compute_error(), oomph::ScalarAdvectionEquations< DIM >::compute_error(), get_exact_u(), and LinearWaveProblem< ELEMENT, TIMESTEPPER >::set_initial_condition().
get_exact_gradient()
void TanhSolnForLinearWave::get_exact_gradient (const double & time, const Vector< double > & x, Vector< double > & dudx)
Gradient of exact solution.
  {
   double zeta=cos(Phi)*x[0]+sin(Phi)*x[1];
   dudx[0] = -Alpha*cos(Phi)/(cosh(1.0-Alpha*(zeta-time))
                              *cosh(1.0-Alpha*(zeta-time)));
   dudx[1] = -Alpha*sin(Phi)/(cosh(1.0-Alpha*(zeta-time))
                              *cosh(1.0-Alpha*(zeta-time)));
  }
References TanhSolnForAdvectionDiffusion::Alpha, cos(), Eigen::bfloat16_impl::cosh(), ExactSolnForUnsteadyHeat::Phi, sin(), plotDoE::x, and Eigen::zeta().
Referenced by prescribed_flux_on_fixed_y_boundary().
get_exact_u()
void TanhSolnForLinearWave::get_exact_u (const double & time, const Vector< double > & x, Vector< double > & u)
Exact solution as a vector.
  {
   u[0]=exact_u(time,x);
   u[1]=exact_dudt(time,x);
   u[2]=exact_d2udt2(time,x);
  }
References exact_d2udt2(), exact_dudt(), exact_u(), and plotDoE::x.
Referenced by LinearWaveProblem< ELEMENT, TIMESTEPPER >::doc_solution().
get_source()
void TanhSolnForLinearWave::get_source (const double & time, const Vector< double > & x, double & source)
Source function to make it an exact solution.
  {
   source=0.0;
  }
References TestProblem::source().
Referenced by main().
prescribed_flux_on_fixed_y_boundary()
void TanhSolnForLinearWave::prescribed_flux_on_fixed_y_boundary (const double & time, const Vector< double > & x, double & flux)
Prescribed flux on a fixed y max boundary.
  {
   // Set up normal
   Vector<double> dudx(2), n(2);
   n[0]=1.0;
   n[1]=0.0;
   // Get gradient
   get_exact_gradient(time,x,dudx);
   // Flux
   flux = dudx[0]*n[0] + dudx[1]*n[1];
  }
References ProblemParameters::flux(), get_exact_gradient(), n, and plotDoE::x.
Referenced by LinearWaveProblem< ELEMENT, TIMESTEPPER >::LinearWaveProblem().
Variable Documentation
Alpha
double TanhSolnForLinearWave::Alpha
Parameter for steepness of step.
Referenced by exact_d2udt2(), exact_dudt(), exact_u(), and LinearWaveProblem< ELEMENT, TIMESTEPPER >::LinearWaveProblem().
Phi
double TanhSolnForLinearWave::Phi
Orientation of step wave.
Referenced by exact_d2udt2(), exact_dudt(), exact_u(), and LinearWaveProblem< ELEMENT, TIMESTEPPER >::LinearWaveProblem().