MercuryDPM: ScrewUnitTest.cpp File Reference
ScrewUnitTest.cpp File Reference
#include <Species/LinearViscoelasticSpecies.h>
#include <Walls/Screw.h>
#include "Mercury3D.h"
Functions
int main ()
Function Documentation
main()
int main ()
Testing if screw geometry is implemented well
 {
     Mercury3D dpm;
     LinearViscoelasticSpecies species;
     species.setDensity(1);
     species.setStiffness(1);
     auto s = dpm.speciesHandler.copyAndAddObject(species);
     Screw screw({0,0,0}, 1, 1, 1, 0, .1, ScrewType::singleHelix);
     screw.setSpecies(s);
     auto w = dpm.wallHandler.copyAndAddObject(screw);
     dpm.setDomain({-0.2,-1,-1},{1.2,1,1});
     dpm.setTimeStep(1e-12);
     dpm.setTimeMax(dpm.getTimeStep());
     dpm.setName("ScrewUnitTest");
     dpm.setParticlesWriteVTK(true);
     dpm.wallHandler.setWriteVTK(true);
     Mdouble h = 0.05;
     Mdouble distance;
     Vec3D normal;
     SphericalParticle particle(s);
     particle.setRadius(0.5*h);
     for (Mdouble x = dpm.getXMin(); x<dpm.getXMax(); x+=h) {
         for (Mdouble y = dpm.getYMin(); y<dpm.getYMax(); y+=h) {
             for (Mdouble z = dpm.getZMin(); z<dpm.getZMax(); z+=h)
             {
                 particle.setPosition({x, y, z});
                 if (w->getDistanceAndNormal(particle,distance,normal))
                 {
                     dpm.particleHandler.copyAndAddObject(particle);
                     //logger(INFO,"p %",particle.getPosition());
                 }
             }
         }
     }
     logger(INFO,"Inserted % particles",dpm.particleHandler.getSize());
     //dpm.solve();
     helpers::check(dpm.particleHandler.getSize(),8213,0,"Screw surface was wrongly detected");
     return 0;
 }
References helpers::check(), BaseHandler< T >::copyAndAddObject(), e(), BaseHandler< T >::getSize(), DPMBase::getTimeStep(), DPMBase::getXMax(), DPMBase::getXMin(), DPMBase::getYMax(), DPMBase::getYMin(), DPMBase::getZMax(), DPMBase::getZMin(), INFO, logger, WallFunction::normal(), DPMBase::particleHandler, s, ParticleSpecies::setDensity(), DPMBase::setDomain(), DPMBase::setName(), DPMBase::setParticlesWriteVTK(), BaseInteractable::setPosition(), BaseParticle::setRadius(), BaseWall::setSpecies(), LinearViscoelasticNormalSpecies::setStiffness(), DPMBase::setTimeMax(), DPMBase::setTimeStep(), WallHandler::setWriteVTK(), singleHelix, DPMBase::speciesHandler, w, DPMBase::wallHandler, plotDoE::x, and y.