MercuryDPM: WallFunction Namespace Reference
WallFunction Namespace Reference
Functions
void normal (const Vector< double > &x, Vector< double > &normal)
Function Documentation
normal()
void WallFunction::normal (const Vector< double > & x, Vector< double > & normal)
  {
   //Calculate theta
   double theta = std::atan2(x[1],x[0]);
   //Return the normal
   normal[0] = cos(theta);
   normal[1] = sin(theta);
   normal[2] = 0.0;
  }
References atan2(), cos(), sin(), BiharmonicTestFunctions2::theta, and plotDoE::x.
Referenced by oomph::YoungLaplaceContactAngleElement< ELEMENT >::actual_cos_contact_angle(), oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::add_element_contribution_to_aux_integral(), SpineGravityTractionElement< ELEMENT >::add_generic_residual_contribution(), NautaMixer::addBaseWall(), NautaMixer::addConeWall(), ChuteWithHopper::addHopper(), IntersectionOfWalls::addObject(), NautaMixer::addParticles(), NautaMixer::addParticlesAtWall(), BaseWall::addParticlesAtWall(), STLReader::addTriangle(), Membrane::Edge::applyStretchForce(), oomph::TetMeshBase::assess_mesh_quality(), AxialSolidQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::AxialSolidQuarterTubeMesh(), AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::AxialSpineQuarterTubeMesh(), oomph::WarpedCircularDisk::boundary_triad(), DPMBase::checkParticleForInteractionLocal(), MercuryBase::checkParticleForInteractionLocal(), ChuteWithContraction::ChuteWithContraction(), ChuteWithPeriodicInflowAndContraction::ChuteWithPeriodicInflowAndContraction(), AngledPeriodicBoundarySecondUnitTest::computeExternalForces(), ChuteWithPeriodicInflow::computeInternalForces(), oomph::YoungLaplaceContactAngleElement< ELEMENT >::contact_line_vectors(), oomph::FaceElement::continuous_tangent_and_outer_unit_normal(), ContractionWithPeriodicInflow::ContractionWithPeriodicInflow(), create_fluid_and_solid_surface_mesh_from_fluid_xda_mesh(), LevelSetWall::createVTK(), oomph::DiskWithTorusAroundEdgeTetMeshFacetedSurface::DiskWithTorusAroundEdgeTetMeshFacetedSurface(), RefineableYoungLaplaceProblem< ELEMENT >::doc_solution(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::drag_force(), oomph::YoungLaplaceContactAngleElement< ELEMENT >::fill_in_contribution_to_residuals(), Domain::findNewMPIInteractions(), SpineGravityTractionElement< ELEMENT >::flow(), oomph::NavierStokesSurfaceDragTorqueElement< ELEMENT >::get_drag_and_torque(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_kinetic_energy_flux(), oomph::FSIAxisymFoepplvonKarmanElement< NNODE_1D, FLUID_ELEMENT >::get_pressure_fvk(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_rate_of_traction_work(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_rate_of_traction_work_components(), oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::get_volume_flux(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_volume_flux(), CGCoordinates::R::getCNormal(), CGCoordinates::RZ::getCNormal(), CGCoordinates::X::getCNormal(), CGCoordinates::XY::getCNormal(), CGCoordinates::XZ::getCNormal(), CGCoordinates::Y::getCNormal(), CGCoordinates::YZ::getCNormal(), CGCoordinates::Z::getCNormal(), NurbsSurface::getDistance(), ArcWall::getDistanceAndNormal(), AxisymmetricIntersectionOfWalls::getDistanceAndNormal(), HorizontalBaseScrew::getDistanceAndNormal(), BasicIntersectionOfWalls::getDistanceAndNormal(), BasicUnionOfWalls::getDistanceAndNormal(), MeshTriangle::getDistanceAndNormal(), TriangleWall::getDistanceAndNormal(), TriangulatedWall::Face::getDistanceAndNormal(), LevelSetWall::getDistanceAndNormalLabCoordinates(), MeshTriangle::getDistanceNormalOverlapType(), SuperQuadricParticle::getInitialGuessForContact(), CGCoordinates::R::getINormal(), CGCoordinates::RZ::getINormal(), CGCoordinates::X::getINormal(), CGCoordinates::XY::getINormal(), CGCoordinates::XZ::getINormal(), CGCoordinates::Y::getINormal(), CGCoordinates::YZ::getINormal(), CGCoordinates::Z::getINormal(), InteractionHandler::getInteraction(), ArcWall::getInteractionWith(), BaseWall::getInteractionWith(), Combtooth::getInteractionWith(), MeshTriangle::getInteractionWith(), SineWall::getInteractionWith(), TriangulatedWall::getInteractionWith(), VChute::getInteractionWith(), SuperQuadricParticle::getInteractionWithSuperQuad(), CGCoordinates::R::getPNormal(), CGCoordinates::RZ::getPNormal(), CGCoordinates::X::getPNormal(), CGCoordinates::XY::getPNormal(), CGCoordinates::XZ::getPNormal(), CGCoordinates::Y::getPNormal(), CGCoordinates::YZ::getPNormal(), CGCoordinates::Z::getPNormal(), BasicIntersectionOfWalls::getVTK(), BasicUnionOfWalls::getVTK(), InfiniteWall::InfiniteWall(), InfiniteWallWithHole::InfiniteWallWithHole(), BaseWall::intersectVTK(), HorizontalMixer::introduceParticlesAtWall(), ContactDetectionIntersectionOfWallsTest::introduceParticlesAtWall(), HorizontalMixer::introduceParticlesInDomain(), TriangleWall::isFaceContact(), BaseWall::isInsideWallVTK(), load(), oomph::KirchhoffLoveShellEquations::load_rate_of_work(), main(), InfiniteWall::oldRead(), oomph::FaceElement::outer_unit_normal(), STLReader::output(), oomph::NavierStokesSurfaceDragTorqueElement< ELEMENT >::output(), oomph::SolarRadiationBase::output_atmospheric_radiation(), oomph::DiskLikeGeomObjectWithBoundaries::output_boundaries_and_triads(), oomph::SolarRadiationBase::output_limiting_angles(), SuperQuadricParticle::overlapFromContactPoint(), BaseWall::projectOntoWallVTK(), Quaternion::Quaternion(), InfiniteWall::read(), IntersectionOfWalls::read(), WallHandler::readAndCreateOldObject(), BoundaryHandler::readOldObject(), DeletionBoundary::set(), FluxBoundary::set(), CylinderInsertionBoundary::set(), PeriodicBoundary::set(), TimeDependentPeriodicBoundary::set(), InfiniteWallWithHole::set(), ConstantMassFlowMaserBoundary::set(), SubcriticalMaserBoundary::set(), InfiniteWall::set(), BaseInteraction::setFStatData(), CylinderInsertionBoundary::setGeometry(), BaseInteraction::setNormal(), InfiniteWall::setNormal(), CylinderInsertionBoundary::setOrientation(), BaseInteractable::setOrientationViaNormal(), Quaternion::setOrientationViaNormal(), HorizontalMixer::setOuterWalls(), HorizontalMixerWalls::setOuterWalls(), oomph::TetMeshBase::setup_boundary_coordinates(), oomph::XdaTetMesh< ELEMENT >::setup_boundary_coordinates(), GetDistanceAndNormalForIntersectionOfWalls::setupInitialConditions(), GetDistanceAndNormalForScrew::setupInitialConditions(), GetDistanceAndNormalForTriangleWall::setupInitialConditions(), InsertionBoundarySelfTest::setupInitialConditions(), CoilSelfTest::setupInitialConditions(), GetDistanceAndNormalForTriangleWalls::setupInitialConditions(), TriangulatedStepWallSelfTest::setupInitialConditions(), oomph::TetMeshBase::snap_to_quadratic_surface(), Global_Parameters::solid_boundary_displacement(), oomph::FluidInterfaceBoundingElement::wall_unit_normal(), Global_Physical_Variables::wall_unit_normal_fct(), oomph::Global_Physical_Variables::wall_unit_normal_inlet_fct(), Global_Physical_Variables::wall_unit_normal_inlet_fct(), Global_Physical_Variables::wall_unit_normal_left_fct(), oomph::Global_Physical_Variables::wall_unit_normal_outlet_fct(), Global_Physical_Variables::wall_unit_normal_outlet_fct(), Global_Physical_Variables::wall_unit_normal_right_fct(), and LevelSetWall::writeToFile().