MercuryDPM: OSPenetration.cpp File Reference
OSPenetration.cpp File Reference
#include "MercuryOS.h"
#include <Walls/TriangleWall.h>
Classes
class Penetration
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc , char ** argv)
 {
     // create an instance of the Penetration class
     Penetration dpm;
     // command line arguments:
     dpm.setNumberOfOMPThreads(helpers::readFromCommandLine(argc, argv, "-omp", 1));
     // turn on additional output files for viewing/analysing the data
     dpm.test(helpers::readFromCommandLine(argc, argv, "-test"));
     // turn on additional output files for viewing/analysing the data
     dpm.writeOutput(helpers::readFromCommandLine(argc, argv, "-writeOutput"));
     // read how many particles should be read (25K, 50K or 100K)
     dpm.setSize(helpers::readFromCommandLine(argc, argv, "-size", std::string("25K")));
     // call the solve routine
     dpm.solve();
     return 0;
 }
References helpers::readFromCommandLine(), DPMBase::setNumberOfOMPThreads(), Penetration::setSize(), DPMBase::solve(), oomph::Global_string_for_annotation::string(), MercuryOS::test(), and MercuryOS::writeOutput().