MercuryDPM: oomph::HeatedLinearSurfaceContactElement< ELEMENT > Class Template Reference
oomph::HeatedLinearSurfaceContactElement< ELEMENT > Class Template Reference
Public Member Functions
HeatedLinearSurfaceContactElement (FiniteElement *const &element_pt, const int &face_index, const unsigned &id=0, const bool &called_from_refineable_constructor=false)
HeatedLinearSurfaceContactElement ()
Default constructor.
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Final over-rider – use version in element with external element.
double heat_flux (const Vector< double > &s) const
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
hierher overload...
void output (std::ostream &outfile, const unsigned &n_plot)
Output function.
bool use_collocated_heat_flux_flag ()
or integrated using the hat function (false)
bool *& use_collocated_heat_flux_flag_pt ()
Access function: Pointer to flag to use collocated heat_flux.
bool * use_collocated_heat_flux_flag_pt () const
Access function: Pointer to flag to use collocated heat_flux (const version)
Public Member Functions inherited from oomph::LinearSurfaceContactElement< ELEMENT >
LinearSurfaceContactElement (FiniteElement *const &element_pt, const int &face_index, const unsigned &id=0, const bool &called_from_refineable_constructor=false)
LinearSurfaceContactElement ()
Default constructor.
void output (std::ostream &outfile)
Output function.
void resulting_contact_force (Vector< double > &contact_force)
Resulting contact force.
Public Member Functions inherited from oomph::SurfaceContactElementBase< ELEMENT >
SurfaceContactElementBase (FiniteElement *const &element_pt, const int &face_index, const unsigned &id=0, const bool &called_from_refineable_constructor=false)
value of the index and its limit
SurfaceContactElementBase ()
Default constructor.
void enable_stick ()
double s_min () const
Min value of local coordinate.
double s_max () const
Max. value of local coordinate.
void disable_stick ()
bool is_stick_enabled ()
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Return the residuals.
Penetrator * penetrator_pt () const
Pointer to penetrator.
void set_penetrator_pt (Penetrator *penetrator_pt)
Set pointer to penetrator.
void output (FILE *file_pt)
C_style output function.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function.
void shape_p (const Vector< double > &s, Shape &psi) const
Shape fct for lagrange multiplier.
void shape_i (const Vector< double > &s, Shape &psi) const
Public Member Functions inherited from oomph::FaceElement
FaceElement ()
Constructor: Initialise all appropriate member data.
virtual ~FaceElement ()
Empty virtual destructor.
FaceElement (const FaceElement &)=delete
Broken copy constructor.
const unsigned & boundary_number_in_bulk_mesh () const
Broken assignment operator.
void set_boundary_number_in_bulk_mesh (const unsigned &b)
Set function for the boundary number in bulk mesh.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
double J_eulerian (const Vector< double > &s) const
double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
double interpolated_x (const Vector< double > &s, const unsigned &i) const
double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
void interpolated_x (const Vector< double > &s, Vector< double > &x) const
void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
int & normal_sign ()
int normal_sign () const
int & face_index ()
int face_index () const
const Vector< double > * tangent_direction_pt () const
Public access function for the tangent direction pointer.
void set_tangent_direction (Vector< double > *tangent_direction_pt)
Set the tangent direction vector.
void turn_on_warning_for_discontinuous_tangent ()
void turn_off_warning_for_discontinuous_tangent ()
void continuous_tangent_and_outer_unit_normal (const Vector< double > &s, Vector< Vector< double >> &tang_vec, Vector< double > &unit_normal) const
void continuous_tangent_and_outer_unit_normal (const unsigned &ipt, Vector< Vector< double >> &tang_vec, Vector< double > &unit_normal) const
void outer_unit_normal (const Vector< double > &s, Vector< double > &unit_normal) const
Compute outer unit normal at the specified local coordinate.
void outer_unit_normal (const unsigned &ipt, Vector< double > &unit_normal) const
Compute outer unit normal at ipt-th integration point.
FiniteElement *& bulk_element_pt ()
Pointer to higher-dimensional "bulk" element.
FiniteElement * bulk_element_pt () const
Pointer to higher-dimensional "bulk" element (const version)
CoordinateMappingFctPt & face_to_bulk_coordinate_fct_pt ()
CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt () const
BulkCoordinateDerivativesFctPt & bulk_coordinate_derivatives_fct_pt ()
BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt () const
Vector< double > local_coordinate_in_bulk (const Vector< double > &s) const
void get_local_coordinate_in_bulk (const Vector< double > &s, Vector< double > &s_bulk) const
void get_ds_bulk_ds_face (const Vector< double > &s, DenseMatrix< double > &dsbulk_dsface, unsigned &interior_direction) const
unsigned & bulk_position_type (const unsigned &i)
const unsigned & bulk_position_type (const unsigned &i) const
void bulk_node_number_resize (const unsigned &i)
Resize the storage for the bulk node numbers.
unsigned & bulk_node_number (const unsigned &n)
const unsigned & bulk_node_number (const unsigned &n) const
void bulk_position_type_resize (const unsigned &i)
Resize the storage for bulk_position_type to i entries.
unsigned & nbulk_value (const unsigned &n)
unsigned nbulk_value (const unsigned &n) const
void nbulk_value_resize (const unsigned &i)
void resize_nodes (Vector< unsigned > &nadditional_data_values)
void output_zeta (std::ostream &outfile, const unsigned &nplot)
Output boundary coordinate zeta.
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
virtual void disable_ALE ()
virtual void enable_ALE ()
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual unsigned nvertex_node () const
virtual Node * vertex_node_pt (const unsigned &j) const
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output an exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output a time-dependent exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::TemplateFreeContactElementBase
TemplateFreeContactElementBase ()
virtual ~TemplateFreeContactElementBase ()
Destructor.
void traction_fct (const Vector< double > &x, Vector< double > &p)
bool use_isoparametric_flag () const
bool use_collocated_penetration_flag ()
bool use_collocated_contact_pressure_flag ()
TractionFctPt & traction_fct_pt ()
Access function: Pointer to body force function.
TractionFctPt traction_fct_pt () const
Access function: Pointer to body force function (const version)
bool *& use_isoparametric_flag_pt ()
Access function: Pointer to flag to use isoparametric.
bool * use_isoparametric_flag_pt () const
bool *& use_collocated_penetration_flag_pt ()
Access function: Pointer to flag to use collocated penetration.
bool * use_collocated_penetration_flag_pt () const
bool *& use_collocated_contact_pressure_flag_pt ()
Access function: Pointer to flag to use collocated contact pressure.
bool * use_collocated_contact_pressure_flag_pt () const
Public Member Functions inherited from oomph::TemplateFreeHeatedLinearSurfaceContactElementBase
virtual ~TemplateFreeHeatedLinearSurfaceContactElementBase ()
Virtual destructor (empty)
Public Member Functions inherited from oomph::ElementWithExternalElement
ElementWithExternalElement ()
virtual ~ElementWithExternalElement ()
The destructor, clean up any allocated memory.
ElementWithExternalElement (const ElementWithExternalElement &)=delete
Broken copy constructor.
void operator= (const ElementWithExternalElement &)=delete
Broken assignment operator.
bool storage_has_been_allocated () const
Helper function to check if storage has actually been allocated.
FiniteElement *& external_element_pt (const unsigned &interaction_index, const unsigned &ipt)
FiniteElement *const & external_element_pt (const unsigned &interaction_index, const unsigned &ipt) const
Access function to source element, const version.
Vector< double > & external_element_local_coord (const unsigned &interaction_index, const unsigned &ipt)
Vector< double > const & external_element_local_coord (const unsigned &interaction_index, const unsigned &ipt) const
Access function to get source element's coords, const version.
void output_external_elements (std::ostream &outfile, const unsigned &interaction_index)
void initialise_external_element_storage ()
void flush_all_external_element_storage ()
Flush the storage for external elements.
void set_ninteraction (const unsigned &n_interaction)
unsigned ninteraction () const
Return the number of interactions in the element.
virtual void identify_all_field_data_for_external_interaction (Vector< std::set< FiniteElement * >> const &external_elements_pt, std::set< std::pair< Data *, unsigned >> &paired_interaction_data)
virtual void identify_all_geometric_data_for_external_interaction (Vector< std::set< FiniteElement * >> const &external_elements_pt, std::set< Data * > &external_geometric_data_pt)
unsigned nexternal_interaction_field_data () const
Vector< Data * > external_interaction_field_data_pt () const
unsigned nexternal_interaction_geometric_data () const
bool add_external_geometric_data ()
Are we including external geometric data in the element's Jacobian.
bool add_external_interaction_data ()
Are we including external data in the element's Jacobian.
Vector< Data * > external_interaction_geometric_data_pt () const
void ignore_external_geometric_data ()
void ignore_external_interaction_data ()
void include_external_geometric_data ()
void include_external_interaction_data ()
bool external_geometric_data_is_included () const
void describe_local_dofs (std::ostream &out, const std::string &curr_string) const
Protected Member Functions
void fill_in_contribution_to_residuals_surface_contact (Vector< double > &residuals)
Return the residuals for the LinearSurfaceContactElement equations.
Protected Member Functions inherited from oomph::LinearSurfaceContactElement< ELEMENT >
void interpolated_u_linear_elasticity (const Vector< double > &s, Vector< double > &disp) const
Compute vector of FE interpolated displacement u at local coordinate s.
Protected Member Functions inherited from oomph::SurfaceContactElementBase< ELEMENT >
double get_interpolated_lagrange_p (const Vector< double > &s)
void penetration (const Vector< double > &x, const Vector< double > &n, double &d, bool &intersection) const
Work out penetration of point.
Protected Member Functions inherited from oomph::FaceElement
void add_additional_values (const Vector< unsigned > &nadditional_values, const unsigned &id)
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Member Functions inherited from oomph::ElementWithExternalElement
void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
void assign_external_interaction_data_local_eqn_numbers (const bool &store_local_dof_pt)
void fill_in_jacobian_from_external_interaction_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_external_interaction_by_fd (DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_external_interaction_field_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_external_interaction_field_by_fd (DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_external_interaction_geometric_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_external_interaction_geometric_by_fd (DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void update_before_external_interaction_field_fd ()
virtual void reset_after_external_interaction_field_fd ()
virtual void update_in_external_interaction_field_fd (const unsigned &i)
virtual void reset_in_external_interaction_field_fd (const unsigned &i)
virtual void update_before_external_interaction_geometric_fd ()
virtual void reset_after_external_interaction_geometric_fd ()
virtual void update_in_external_interaction_geometric_fd (const unsigned &i)
virtual void reset_in_external_interaction_geometric_fd (const unsigned &i)
Protected Attributes
unsigned Heat_flux_lagr_multiplier_id
ID of heat flux Lagrange multiplier (to ensure continuity of temperature)
bool * Use_collocated_heat_flux_flag_pt
Set options for basis/test functions for penetration and pressure.
bool activate_iso_colloc_for_contact
Protected Attributes inherited from oomph::LinearSurfaceContactElement< ELEMENT >
Vector< unsigned > U_index_linear_elasticity_traction
Index at which the i-th displacement component is stored.
Protected Attributes inherited from oomph::SurfaceContactElementBase< ELEMENT >
Penetrator * Penetrator_pt
Pointer to penetrator.
unsigned Contact_id
bool Enable_stick
Vector< int > Penetrator_eq_data_type
Vector< int > Penetrator_eq_data_index
Vector< int > Penetrator_eq_data_data_index
Protected Attributes inherited from oomph::FaceElement
unsigned Boundary_number_in_bulk_mesh
The boundary number in the bulk mesh to which this element is attached.
FiniteElement * Bulk_element_pt
Pointer to the associated higher-dimensional "bulk" element.
Vector< unsigned > Bulk_node_number
Vector< unsigned > Nbulk_value
Vector< double > * Tangent_direction_pt
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Protected Attributes inherited from oomph::TemplateFreeContactElementBase
TractionFctPt Traction_fct_pt
bool * Use_isoparametric_flag_pt
Set whether or not to use isoparametric basis function for pressure.
bool * Use_collocated_penetration_flag_pt
Set options for basis/test functions for penetration and pressure.
bool * Use_collocated_contact_pressure_flag_pt
Set options for basis/test functions for penetration and pressure.
Protected Attributes inherited from oomph::ElementWithExternalElement
bool Add_external_interaction_data
Boolean flag to indicate whether to include the external data.
bool Add_external_geometric_data
Boolean flag to indicate whether to include the external geometric data.
Data ** External_interaction_field_data_pt
Data ** External_interaction_geometric_data_pt
Additional Inherited Members
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Public Types inherited from oomph::TemplateFreeContactElementBase
typedef void(* TractionFctPt) (const double &t, const Vector< double > &x, Vector< double > &p)
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Protected Types inherited from oomph::TemplateFreeContactElementBase
enum { Nodal_data , Nodal_position_data , External_data }
Enumeration for type of penetrator data.
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
template<class ELEMENT>
class oomph::HeatedLinearSurfaceContactElement< ELEMENT >
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// Class for elements that impose contact boundary conditions either enforcing non-penetration (but "without stick"; default) or permament contact (in which case contact force can be positive or negative. Uses Lagrange-multiplier-like pressure to enforce contact/non-penetration. Almost certainly works only with 2D Penetrator at the moment. Specific implementation for linear elasticity. Also applies continuity of temperature constraint at interface
Constructor & Destructor Documentation
HeatedLinearSurfaceContactElement() [1/2]
template<class ELEMENT > oomph::HeatedLinearSurfaceContactElement< ELEMENT >::HeatedLinearSurfaceContactElement (FiniteElement *const & element_pt, const int & face_index, const unsigned & id = 0, const bool & called_from_refineable_constructor = false) inline
Constructor, which takes a "bulk" element and the value of the index and its limit
hierher currently deactivating collocation on contact elements
                                                                              :
   SurfaceContactElementBase<ELEMENT>(element_pt,
                                      face_index,
                                      id,
                                      called_from_refineable_constructor),
   LinearSurfaceContactElement<ELEMENT>(element_pt,
                                        face_index,
                                        id,
                                        called_from_refineable_constructor),
   Use_collocated_heat_flux_flag_pt(0)
   {
    // hierher provide separate id via arg list
    Heat_flux_lagr_multiplier_id=id+1;
    // We need yet another additional value for each FaceElement node:
    // the normal traction (Lagrange multiplier) to be
    // exerted onto the solid
    unsigned n_nod=this->nnode();
    Vector<unsigned> n_additional_values(n_nod,1);
    // Now add storage for Lagrange multipliers and set the map containing
    // the position of the first entry of this face element's
    // additional values.
    this->add_additional_values(n_additional_values,
                                Heat_flux_lagr_multiplier_id);
    // Set source element storage: one interaction with an external
    // element -- the HeatedPenetratorFluxElement whose temperature we're
    //matching
    this->set_ninteraction(1);
    activate_iso_colloc_for_contact = false;
    this->Use_isoparametric_flag_pt = &activate_iso_colloc_for_contact;
    this->Use_collocated_penetration_flag_pt = &activate_iso_colloc_for_contact;
    this->Use_collocated_contact_pressure_flag_pt =&activate_iso_colloc_for_contact;
    //If we are using a top hat function for the heat flux, we need to change
    //the integration scheme
    if(!use_collocated_heat_flux_flag())
     {
      set_integration_scheme(new PiecewiseGauss<1,3>(s_min(),s_max()));
     }
   }
HeatedLinearSurfaceContactElement() [2/2]
template<class ELEMENT > oomph::HeatedLinearSurfaceContactElement< ELEMENT >::HeatedLinearSurfaceContactElement () inline
Default constructor.
 {}
Member Function Documentation
describe_local_dofs()
template<class ELEMENT > void oomph::HeatedLinearSurfaceContactElement< ELEMENT >::describe_local_dofs (std::ostream & out, const std::string & current_string) const inline virtual
Function to describe the local dofs of the element. The ostream specifies the output stream to which the description is written; the string stores the currently assembled output that is ultimately written to the output stream by Data::describe_dofs(...); it is typically built up incrementally as we descend through the call hierarchy of this function when called from Problem::describe_dofs(...)
Reimplemented from oomph::FiniteElement.
   {
    LinearSurfaceContactElement<ELEMENT>::
     describe_local_dofs(out,current_string);
    ElementWithExternalElement::describe_local_dofs(out,current_string);
   }
References out().
fill_in_contribution_to_jacobian()
template<class ELEMENT > void oomph::HeatedLinearSurfaceContactElement< ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline virtual
Final over-rider – use version in element with external element.
Reimplemented from oomph::GeneralisedElement.
   {
    ElementWithExternalElement::fill_in_contribution_to_jacobian(residuals,
                                                                 jacobian);
   }
References oomph::fill_in_contribution_to_jacobian().
fill_in_contribution_to_residuals_surface_contact()
template<class ELEMENT > void oomph::HeatedLinearSurfaceContactElement< ELEMENT >::fill_in_contribution_to_residuals_surface_contact (Vector< double > & residuals) protected virtual
Return the residuals for the LinearSurfaceContactElement equations.
Overloaded fill in contributions function – includes heat flux to ensure continuity of temperature
////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////
Reimplemented from oomph::LinearSurfaceContactElement< ELEMENT >.
 {
  // Get pointer to bulk element
  ELEMENT *bulk_el_pt = dynamic_cast<ELEMENT*>(this->bulk_element_pt());
  // Get index of temperature in bulk element
  unsigned temperature_index=bulk_el_pt->u_index_ust_heat();
  // Spatial dimension of problem
  unsigned n_dim = this->nodal_dimension();
  // Contribution to contact force
  Vector<double> contact_force(n_dim,0.0);
  // Create vector of local residuals (start assembling contributions
  // from zero -- necessary so we can over-write pseudo-hijacked
  // contributions at the end.
  unsigned n_dof=this->ndof();
  Vector<double> local_residuals(n_dof,0.0);
  {
   //Find out how many nodes there are
   unsigned n_node = this->nnode();
   //Integer to hold the local equation number
   int local_eqn=0;
   int local_eqn_p=0;
   int local_eqn_q=0;
   //Set up memory for the shape functions
   Shape psi(n_node);
   DShape dpsids(n_node,n_dim-1);
   // Separate shape functions for Lagrange multiplier
   Shape psi_p(n_node);
   // Separate shape functions for integration (top hat)
   Shape psi_i(n_node);
   Vector<double> s(n_dim-1);
   // Contribution to integrated pressure
   Vector<double> pressure_integral(n_node,0.0);
   // Contribution to weighted penetration integral
   Vector<double> penetration_integral(n_node,0.0);
   // Contribution to heat flux integral
   Vector<double> heat_flux_integral(n_node,0.0);
   // Contribution to temperature deviation integral
   Vector<double> temp_deviation_integral(n_node,0.0);
   // Deformed position
   Vector<double> x_def(n_dim,0.0);
   //Set the value of n_intpt
   unsigned n_intpt = this->integral_pt()->nweight();
   //Loop over the integration points
   for(unsigned ipt=0;ipt<n_intpt;ipt++)
    {
     //Get the integral weight
     double w = this->integral_pt()->weight(ipt);
     //Only need to call the local derivatives
     this->dshape_local_at_knot(ipt,psi,dpsids);
     // Separate shape function for Lagrange multipliers
     for(unsigned i=0;i<n_dim-1;i++)
      {
       s[i] = this->integral_pt()->knot(ipt,i);
      }
     this->shape_p(s,psi_p);
     //set up shape for integration
     this->shape_i(s,psi_i);
     // Interpolated Lagrange multiplier (pressure acting on solid)
     double interpolated_lambda_p=0.0;
     // Interpolated Lagrange multiplier (heat flux)
     double interpolated_lambda_q=0.0;
     // Interpolated temperature
     double interpolated_temp=0.0;
     // Displacement
     Vector<double> disp(n_dim,0.0);
     //Calculate the coordinates
     Vector<double> interpolated_x(n_dim,0.0);
     //Also calculate the surface Vectors (derivatives wrt local coordinates)
     DenseMatrix<double> interpolated_A(n_dim-1,n_dim,0.0);
     //Calculate displacements and derivatives
     for(unsigned l=0;l<n_node;l++)
      {
       // Cast to a boundary node
       BoundaryNodeBase *bnod_pt =
        dynamic_cast<BoundaryNodeBase*>(this->node_pt(l));
       // Get the index of the nodal value associated with
       // this FaceElement
       unsigned first_index=
        bnod_pt->index_of_first_value_assigned_by_face_element(this->Contact_id);
       // Add to Lagrange multiplier (acting as pressure on solid
       // to enforce motion to ensure non-penetration)
       interpolated_lambda_p+=this->node_pt(l)->value(first_index)*psi_p[l];
       // Get the index of the nodal value associated with
       // this FaceElement
       unsigned first_index_q=
        bnod_pt->index_of_first_value_assigned_by_face_element(
         this->Heat_flux_lagr_multiplier_id);
       // Add to Lagrange multiplier (acting as a heat flux to enforce
       // continuity of temperature across boundary)
       interpolated_lambda_q+=this->node_pt(l)->value(first_index_q)*psi_p[l];
       //Get temperature at this integration point
       interpolated_temp+=this->node_pt(l)->value(temperature_index)*psi[l];
       //Loop over directions
       for(unsigned i=0;i<n_dim;i++)
        {
         //Calculate the positions
         interpolated_x[i]+=this->nodal_position(l,i)*psi(l);
         //Index at which the displacement nodal value is stored
         unsigned u_nodal_index=this->U_index_linear_elasticity_traction[i];
         disp[i] += this->nodal_value(l,u_nodal_index)*psi(l);
         // Loop over LOCAL derivative directions, to calculate the
         // tangent(s)
         for(unsigned j=0;j<n_dim-1;j++)
          {
           interpolated_A(j,i)+=this->nodal_position(l,i)*dpsids(l,j);
          }
        }
      }
     // Get the temperature on the penetrator
     double penetrator_temperature=0.0;
     if (external_element_pt(0,ipt)!=0)
      {
       Vector<double> s_ext(external_element_local_coord(0,ipt));
       TemplateFreeHeatedPenetratorFluxElementBase* el_pt=
        dynamic_cast<TemplateFreeHeatedPenetratorFluxElementBase*>(
         external_element_pt(0,ipt));
       // Note: this does NOT take contact or no contact into account
       // it simply returns the local temperature at "that point" in "that
       // element"
       penetrator_temperature=el_pt->penetrator_temperature(s_ext);
       /* oomph_info << "actual penetrator temperature: "
          << penetrator_temperature << std::endl;*/
      }
     else
      {
       // hierher this should never be triggered on contact surface,
       // throw error here? Although it may not always be a problem, depending
       // on penetrator/contact surface geometry
       oomph_info << "using default penetrator temperature: "
                  << penetrator_temperature << std::endl;
      }
     //Now find the local deformed metric tensor from the tangent Vectors
     DenseMatrix<double> A(n_dim-1);
     for(unsigned i=0;i<n_dim-1;i++)
      {
       for(unsigned j=0;j<n_dim-1;j++)
        {
         //Initialise surface metric tensor to zero
         A(i,j) = 0.0;
         //Take the dot product
         for(unsigned k=0;k<n_dim;k++)
          {
           A(i,j) += interpolated_A(i,k)*interpolated_A(j,k);
          }
        }
      }
     //Get the outer unit normal
     Vector<double> interpolated_normal(n_dim);
     this->outer_unit_normal(ipt,interpolated_normal);
     //Find the determinant of the metric tensor
     double Adet =0.0;
     switch(n_dim)
      {
      case 2:
       Adet = A(0,0);
       break;
      case 3:
       Adet = A(0,0)*A(1,1) - A(0,1)*A(1,0);
       break;
      default:
       throw OomphLibError(
        "Wrong dimension in SurfaceContactElement",
        "LinearSurfaceContactElement::fill_in_contribution_to_residuals()",
        OOMPH_EXCEPTION_LOCATION);
      }
     //Premultiply the weights and the square-root of the determinant of
     //the metric tensor
     double W = w*sqrt(Adet);
     // Calculate the "load" -- Lagrange multiplier acts as traction to
     // to enforce required surface displacement and the
     // deformed position
     Vector<double> traction(n_dim);
     for (unsigned i=0;i<n_dim;i++)
      {
       traction[i]=-interpolated_lambda_p*interpolated_normal[i];
       x_def[i]=interpolated_x[i]+disp[i];
      }
     // Accumulate contribution to total contact force
     for(unsigned i=0;i<n_dim;i++)
      {
       contact_force[i]+=traction[i]*W;
      }
     //=====LOAD TERMS  FROM PRINCIPLE OF VIRTUAL DISPLACEMENTS========
     //Loop over the test functions, nodes of the element
     for(unsigned l=0;l<n_node;l++)
      {
       //Loop over the displacement components
       for(unsigned i=0;i<n_dim;i++)
        {
         local_eqn = this->nodal_local_eqn(l,i); // hierher get index
         /*IF it's not a boundary condition*/
         if(local_eqn >= 0)
          {
           //Add the loading terms to the residuals
           local_residuals[local_eqn] -= traction[i]*psi(l)*W;
          } //End of if not boundary condition
        }
       // Contribution to unsteady heat equation on surface
       local_eqn = this->nodal_local_eqn(l,temperature_index);
       /*IF it's not a boundary condition*/
       if(local_eqn >= 0)
        {
         //Add the loading terms to the residuals
         local_residuals[local_eqn] -= interpolated_lambda_q*psi(l)*W;
        } //End of if not boundary condition
      } //End of loop over shape functions
     //=====CONTRIBUTION TO CONTACT PRESSURE/LAGRANGE MULTIPLIER EQNS ========
     //Only calculate the integrals we need to
     if(!this->use_collocated_contact_pressure_flag())
      {
       //Loop over the nodes
       for(unsigned l=0;l<n_node;l++)
        {
         // Contribution to integrated pressure
         pressure_integral[l]+=interpolated_lambda_p*psi_i[l]*W;
        }
      }
     if(!this->use_collocated_penetration_flag())
      {
       // Get local penetration
       double d=0.0;
       bool intersection = false;
       this->penetration(x_def,interpolated_normal,d,intersection);
       //If there is no intersection, d = -max, ie the penetrator
       //is infinitely far away
       if(!intersection)
        {
         d = -DBL_MAX;
        }
       for(unsigned l=0;l<n_node;l++)
        {
         // Contribution to weighted penetration integral
         penetration_integral[l]+=d*psi_i[l]*W;
        }
      }
     if(!this->use_collocated_heat_flux_flag())
      {
       for(unsigned l=0;l<n_node;l++)
        {
         // Contribution to integrated heat flux
         heat_flux_integral[l]+=interpolated_lambda_q*psi_i[l]*W;
        }
      }
     for(unsigned l=0;l<n_node;l++)
      {
       // Contribution to weighted temperature deviation integral
       temp_deviation_integral[l]+=(interpolated_temp-
                                    penetrator_temperature)*psi_i[l]*W;
      }
    } //End of loop over integration points
   // Eqn for contact pressure and heat flux
   //---------------------------------------------
   // Storage for nodal coordinate
   Vector<double> x(n_dim);
   //Loop over the nodes
   for(unsigned l=0;l<n_node;l++)
    {
     // get the node pt
     Node* nod_pt = this->node_pt(l);
     // Cast to a boundary node
     BoundaryNodeBase *bnod_pt =
      dynamic_cast<BoundaryNodeBase*>(nod_pt);
     // Get the index of the first nodal value associated with
     // this FaceElement
     unsigned first_index_p=
      bnod_pt->index_of_first_value_assigned_by_face_element(this->Contact_id);
     // Equation for pressure Lagrange multiplier
     local_eqn_p = this->nodal_local_eqn(l,first_index_p);
     // Get the index of the first nodal value associated with
     // this FaceElement
     unsigned first_index_q=
      bnod_pt->index_of_first_value_assigned_by_face_element(
       this->Heat_flux_lagr_multiplier_id);
     // Equation number for temperature Lagrange multiplier
     local_eqn_q = this->nodal_local_eqn(l,first_index_q);
     //IF it's not a boundary condition for both heat_flux and contact_pressure
     if(local_eqn_p >= 0 || local_eqn_q >= 0)
      {
       // Use weighted/integrated quantities intially (could be 0)
       // then overwrite them if using collocation
       double d=penetration_integral[l];
       double contact_pressure=pressure_integral[l];
       double heat_flux=heat_flux_integral[l];
       double temp_deviation=temp_deviation_integral[l];
       //overwrite appropriate measure if using collocation
       if(this->use_collocated_penetration_flag())
        {
         // Nodal position
         x[0]=nod_pt->x(0);
         x[1]=nod_pt->x(1);
         // Get outer unit normal
         Vector<double> s(1);
         this->local_coordinate_of_node(l,s);
         Vector<double> unit_normal(2);
         this->outer_unit_normal(s,unit_normal);
         // Get penetration
         bool intersection = false;
         this->penetration(x,unit_normal,d,intersection);
         //If there is no intersection, d = -max, ie the penetrator
         //is infinitely far away
         if(!intersection)
          {
           d = -DBL_MAX;
          }
        }
       //If we are using collocated heat flux, overwrite value
       if(this->use_collocated_heat_flux_flag())
        {
         heat_flux = this->node_pt(l)->value(first_index_q);
        }
       //If we are using collocated contact pressure, overwrite value
       if(this->use_collocated_contact_pressure_flag())
        {
         contact_pressure=nod_pt->value(first_index_p);
        }
       // Contact/non-penetration residual
       if (this->Enable_stick)
        {
         // Enforce contact
         if(local_eqn_p >= 0)
          {
           local_residuals[local_eqn_p]-=d;
          }
         // Enforce continuity of temperature
         if(local_eqn_q >= 0)
          {
           local_residuals[local_eqn_q]+=temp_deviation;
          }
        }
       else
        {
         // Piecewise linear variation for non-penetration constraint
         if (-d>contact_pressure)//No penetration
          {
           if(local_eqn_p >= 0)
            {
             //Crush contact pressure
             local_residuals[local_eqn_p]+=contact_pressure;
            }
           if(local_eqn_q >= 0)
            {
             //Crush heat flux as no contact means no heat transfer
             local_residuals[local_eqn_q]+=heat_flux;
            }
          }
         else //Penetration
          {
           if(local_eqn_p >= 0)
            {
             //Increase contact_pressure until d=0
             local_residuals[local_eqn_p]-=d;
            }
           if(local_eqn_q >= 0)
            {
             //Change lagrange mult (heat flux) until we have continuity
             local_residuals[local_eqn_q]+=temp_deviation;
            }
          }
        }
      }
    }
  }
  // Now deal with the penetrator equilibrium equations (if any!)
  unsigned n=this->Penetrator_eq_data_type.size();
  for (unsigned i=0;i<n;i++)
   {
    if (this->Penetrator_eq_data_type[i]>=0)
     {
      switch(unsigned(this->Penetrator_eq_data_type[i]))
       {
       case TemplateFreeContactElementBase::External_data:
       {
        int local_eqn=this->external_local_eqn(
         this->Penetrator_eq_data_data_index[i],
         this->Penetrator_eq_data_index[i]);
        if (local_eqn>=0)
         {
          local_residuals[local_eqn]=contact_force[i];
         }
       }
       break;
       case TemplateFreeContactElementBase::Nodal_position_data:
       {
        // position type (dummy -- hierher paranoid check)
        unsigned k=0;
        int local_eqn=this->position_local_eqn(
         this->Penetrator_eq_data_data_index[i],k,
         this->Penetrator_eq_data_index[i]);
        if (local_eqn>=0)
         {
          local_residuals[local_eqn]=contact_force[i];
         }
       }
       break;
       case TemplateFreeContactElementBase::Nodal_data:
       {
        int local_eqn=this->nodal_local_eqn(
         this->Penetrator_eq_data_data_index[i],
         this->Penetrator_eq_data_index[i]);
        if (local_eqn>=0)
         {
          local_residuals[local_eqn]+=contact_force[i];
         }
       }
       break;
       default:
        std::stringstream junk;
        junk << "Never get here: "
             << "unsigned(Penetrator_eq_data_type[i]) = "
             << unsigned(this->Penetrator_eq_data_type[i]);
        throw OomphLibError(
         junk.str(),
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
       }
     }
   }
  // Now add local contribution to existing entries
  for (unsigned j=0;j<n_dof;j++)
   {
    residuals[j]+=local_residuals[j];
   }
 }
References i, oomph::BoundaryNodeBase::index_of_first_value_assigned_by_face_element(), j, k, n, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::oomph_info, oomph::TemplateFreeHeatedPenetratorFluxElementBase::penetrator_temperature(), s, sqrt(), oomph::Node::value(), w, oomph::QuadTreeNames::W, plotDoE::x, and oomph::Node::x().
heat_flux()
template<class ELEMENT > double oomph::HeatedLinearSurfaceContactElement< ELEMENT >::heat_flux (const Vector< double > & s) const inline virtual
Return heat flux required to maintain continuity of temperature to adjacent penetrator at local coordinate s
Implements oomph::TemplateFreeHeatedLinearSurfaceContactElementBase.
   {
    // Get shape function for Lagrange multiplier
    unsigned n_node = this->nnode();
    Shape psi_p(n_node);
    this->shape_p(s,psi_p);
    // Interpolated Lagrange multiplier (heat flux)
    double interpolated_lambda_q=0.0;
    for(unsigned l=0;l<n_node;l++)
     {
      // Cast to a boundary node
      BoundaryNodeBase *bnod_pt =
       dynamic_cast<BoundaryNodeBase*>(this->node_pt(l));
      // Get the index of the nodal value associated with
      // this FaceElement
      unsigned first_index_q=
       bnod_pt->index_of_first_value_assigned_by_face_element(
        this->Heat_flux_lagr_multiplier_id);
      // Add to Lagrange multiplier (acting as pressure on solid
      // to enforce motion to ensure non-penetration)
      interpolated_lambda_q+=this->node_pt(l)->value(first_index_q)*psi_p[l];
     }
    return interpolated_lambda_q;
   }
References oomph::BoundaryNodeBase::index_of_first_value_assigned_by_face_element(), and s.
output()
template<class ELEMENT > void oomph::HeatedLinearSurfaceContactElement< ELEMENT >::output (std::ostream & outfile, const unsigned & n_plot) inline virtual
Output function.
Reimplemented from oomph::LinearSurfaceContactElement< ELEMENT >.
   {
    unsigned n_dim = this->nodal_dimension();
    Vector<double> x(n_dim);
    Vector<double> disp(n_dim);
    Vector<double> x_def(n_dim);
    Vector<double> s(n_dim-1);
    Vector<double> r_pen(n_dim);
    Vector<double> unit_normal(n_dim);
    Vector<double> interpolated_heat_flux(1);
    // Tecplot header info
    outfile << this->tecplot_zone_string(n_plot);
    // Loop over plot points
    unsigned num_plot_points=this->nplot_points(n_plot);
    for (unsigned iplot=0;iplot<num_plot_points;iplot++)
     {
      // Get local coordinates of plot point
      this->get_s_plot(iplot,n_plot,s);
      // Get coordinates and outer unit normal
      this->interpolated_x(s,x);
      this->outer_unit_normal(s,unit_normal);
      // Displacement
      this->interpolated_u_linear_elasticity(s,disp);
      // Deformed position
      for(unsigned i=0;i<n_dim;i++)
       {
        x_def[i]=x[i]+disp[i];
       }
      // Get penetration based on deformed position
      double d= 0.0;
      bool intersection = false;
      this->penetration(x_def,unit_normal,d,intersection);
      //Get heat flux
      interpolated_heat_flux[0] = heat_flux(s);
      //Output the x,y,..
      for(unsigned i=0;i<n_dim;i++)
       {outfile << x[i] << " ";} // col 1,2
      // Penetration
      outfile << std::max(d,-100.0) << " "; // col 3
      // Lagrange multiplier-like pressure
      double p=this->get_interpolated_lagrange_p(s);
      outfile << p << " "; // col 4
      // Plot Lagrange multiplier like pressure
      outfile << -unit_normal[0]*p << " "; // col 5
      outfile << -unit_normal[1]*p << " "; // col 6
      // Plot vector from current point to boundary of penetrator
      double d_tmp=d;
      if (!intersection) d_tmp=0.0;
      outfile << -d_tmp*unit_normal[0] << " ";  // col 7
      outfile << -d_tmp*unit_normal[1] << " ";  // col 8
      // Output normal
      for(unsigned i=0;i<n_dim;i++)
       {outfile << unit_normal[i] << " ";} // col 9, 10
      //Output the displacements
      for(unsigned i=0;i<n_dim;i++)
       {
        outfile << disp[i] << " "; // col 11, 12
       }
      //Output the deformed position
      for(unsigned i=0;i<n_dim;i++)
       {
       outfile << x_def[i] << " "; // col 13, 14
       }
      //Output the heat_flux
      outfile << interpolated_heat_flux[0] << " "; // col 15
      outfile << std::endl;
     }
   // Write tecplot footer (e.g. FE connectivity lists)
   this->write_tecplot_zone_footer(outfile,n_plot);
  }
References i, max, p, s, and plotDoE::x.
Referenced by ContactProblem< ELEMENT >::doc_solution().
use_collocated_heat_flux_flag()
template<class ELEMENT > bool oomph::HeatedLinearSurfaceContactElement< ELEMENT >::use_collocated_heat_flux_flag () inline
or integrated using the hat function (false)
Determine which method to use to discretise heat_flux, collocation (true)
   {
    if (Use_collocated_heat_flux_flag_pt==0)
     {
      return false;
     }
    else
     {
      return *Use_collocated_heat_flux_flag_pt;
     }
   }
use_collocated_heat_flux_flag_pt() [1/2]
template<class ELEMENT > bool*& oomph::HeatedLinearSurfaceContactElement< ELEMENT >::use_collocated_heat_flux_flag_pt () inline
Access function: Pointer to flag to use collocated heat_flux.
   {return Use_collocated_heat_flux_flag_pt;}
use_collocated_heat_flux_flag_pt() [2/2]
template<class ELEMENT > bool* oomph::HeatedLinearSurfaceContactElement< ELEMENT >::use_collocated_heat_flux_flag_pt () const inline
Access function: Pointer to flag to use collocated heat_flux (const version)
         {return Use_collocated_heat_flux_flag_pt;}
zeta_nodal()
template<class ELEMENT > double oomph::HeatedLinearSurfaceContactElement< ELEMENT >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const inline virtual
hierher overload...
Reimplemented from oomph::SurfaceContactElementBase< ELEMENT >.
   {
    unsigned dim=this->node_pt(n)->ndim();
    Vector<double> x(dim);
    for (unsigned ii=0;ii<dim;ii++)
     {
      x[ii]=this->node_pt(n)->x(ii);
     }
    Vector<double> zeta(dim-1);
    this->penetrator_pt()->surface_coordinate(x,zeta);
    return zeta[i];
   }
References i, n, plotDoE::x, and Eigen::zeta().
Member Data Documentation
activate_iso_colloc_for_contact
template<class ELEMENT > bool oomph::HeatedLinearSurfaceContactElement< ELEMENT >::activate_iso_colloc_for_contact protected
hierher currently we don't want to use isoparametric for the lagrange multipliers and collocation for penetration and contact pressure, use this as a bulk switch
Heat_flux_lagr_multiplier_id
template<class ELEMENT > unsigned oomph::HeatedLinearSurfaceContactElement< ELEMENT >::Heat_flux_lagr_multiplier_id protected
ID of heat flux Lagrange multiplier (to ensure continuity of temperature)
Use_collocated_heat_flux_flag_pt
template<class ELEMENT > bool* oomph::HeatedLinearSurfaceContactElement< ELEMENT >::Use_collocated_heat_flux_flag_pt protected
Set options for basis/test functions for penetration and pressure.
The documentation for this class was generated from the following file:
heated_linear_solid_contact_with_gravity.cc