MercuryDPM: ScalingTestOldCompiler.cpp File Reference
ScalingTestOldCompiler.cpp File Reference
#include <iostream>
#include <iomanip>
#include <ctime>
#include <Species/LinearViscoelasticSpecies.h>
#include "Mercury3D.h"
#include "Boundaries/PeriodicBoundary.h"
#include "Math/ExtendedMath.h"
Classes
class ScalingTestInitialConditionsRelax
class ScalingTestInitialConditionsEquilibrize
class ScalingTestRun
Functions
int main (int argc UNUSED, char *argv[] UNUSED)
Function Documentation
main()
int main (int argc UNUSED, char *argv[] UNUSED)
 {
     ScalingTestInitialConditionsRelax scalingTestInitialConditionsRelax;
     auto species=scalingTestInitialConditionsRelax.speciesHandler.copyAndAddObject(LinearViscoelasticSpecies());
     scalingTestInitialConditionsRelax.N = 100;
     scalingTestInitialConditionsRelax.initialVelocity = 2.0;
     scalingTestInitialConditionsRelax.targetVelocity = 1.0;
     scalingTestInitialConditionsRelax.particleRadius = 0.5;
     scalingTestInitialConditionsRelax.setName("ScalingTestInitialConditionsRelax");
     species->setDensity(constants::pi / 6.0);
     scalingTestInitialConditionsRelax.setSaveCount(100);
     species->setStiffness(2e5);
     species->setDissipation(150);
     scalingTestInitialConditionsRelax.setTimeStep(1e-4);
     scalingTestInitialConditionsRelax.setTimeMax(10);
     scalingTestInitialConditionsRelax.setGravity(Vec3D(0.0, 0.0, 0.0));
     scalingTestInitialConditionsRelax.setHGridMaxLevels(1);
     scalingTestInitialConditionsRelax.solve();
     ScalingTestInitialConditionsEquilibrize scalingTestInitialConditionsEquilibrize(scalingTestInitialConditionsRelax);
     species=scalingTestInitialConditionsRelax.speciesHandler.copyAndAddObject(LinearViscoelasticSpecies());
     scalingTestInitialConditionsEquilibrize.setName("ScalingTestInitialConditionsEquilibrize");
     species->setDissipation(0.0);
     scalingTestInitialConditionsEquilibrize.setSaveCount(100);
     scalingTestInitialConditionsEquilibrize.setTimeMax(1);
     scalingTestInitialConditionsEquilibrize.solve();
     for (unsigned int i = 1; i <= 10; i++)
     {
         ScalingTestRun scalingTestRun(scalingTestInitialConditionsEquilibrize);
         std::string name = "ScalingTestRun";
         name += std::to_string(i);
         scalingTestRun.setName(name);
         scalingTestRun.setMultiplicationFactor(i);
         scalingTestRun.setSaveCount(100);
         clock_t begin = std::clock();
         scalingTestRun.solve();
         clock_t end = std::clock();
         double diff = double(end - begin) / CLOCKS_PER_SEC * 1000;
         logger(INFO, "N=% T=%%5 ms", scalingTestRun.particleHandler.getNumberOfObjects(), std::scientific, diff);
     }
 }
References BaseHandler< T >::copyAndAddObject(), e(), Eigen::placeholders::end, ParticleHandler::getNumberOfObjects(), i, INFO, ScalingTestInitialConditionsRelax::initialVelocity, logger, ScalingTestInitialConditionsRelax::N, plotDoE::name, DPMBase::particleHandler, ScalingTestInitialConditionsRelax::particleRadius, constants::pi, DPMBase::setGravity(), MercuryBase::setHGridMaxLevels(), ScalingTestRun::setMultiplicationFactor(), DPMBase::setName(), DPMBase::setSaveCount(), DPMBase::setTimeMax(), DPMBase::setTimeStep(), DPMBase::solve(), DPMBase::speciesHandler, oomph::Global_string_for_annotation::string(), ScalingTestInitialConditionsRelax::targetVelocity, and oomph::StringConversion::to_string().