MercuryDPM: HertzianSinterNormalSpecies Class Reference
HertzianSinterNormalSpecies Class Reference
HertzianSinterNormalSpecies contains the parameters used to describe a plastic-cohesive normal force (Stefan Ludings plastic-cohesive force model).
#include <HertzianSinterNormalSpecies.h>
Public Types
typedef HertzianSinterInteraction InteractionType
The correct Interaction type for this FrictionForceSpecies.
Public Member Functions
HertzianSinterNormalSpecies ()
The default constructor.
HertzianSinterNormalSpecies (const HertzianSinterNormalSpecies &p)
The default copy constructor.
~HertzianSinterNormalSpecies ()
The default destructor.
void read (std::istream &is)
Reads the species properties from an input stream.
void write (std::ostream &os) const
Writes the species properties to an output stream.
std::string getBaseName () const
Used in Species::getName to obtain a unique name for each Species.
void mix (HertzianSinterNormalSpecies *S, HertzianSinterNormalSpecies *T)
creates default values for mixed species
void setPlasticParameters (Mdouble loadingModulus, Mdouble unloadingModulusMax, Mdouble cohesionModulus, Mdouble penetrationDepthMax)
Sets all parameters of the linear plastic-viscoelastic normal force at once.
Mdouble getLoadingModulus () const
Returns the loading stiffness of the linear plastic-viscoelastic normal force.
Mdouble getUnloadingModulusMax () const
Returns the maximum unloading stiffness of the linear plastic-viscoelastic normal force.
Mdouble getCohesionModulus () const
Returns the cohesive stiffness of the linear plastic-viscoelastic normal force.
Mdouble getPenetrationDepthMax () const
Returns the maximum penetration depth of the linear plastic-viscoelastic normal force.
void setLoadingModulus (Mdouble loadingModulus)
Sets the loading stiffness of the linear plastic-viscoelastic normal force.
void setUnloadingModulusMax (Mdouble unloadingModulusMax)
Sets the maximum unloading stiffness of the linear plastic-viscoelastic normal force.
void setCohesionModulus (Mdouble cohesionModulus)
Sets the cohesive stiffness of the linear plastic-viscoelastic normal force.
void setPenetrationDepthMax (Mdouble penetrationDepthMax)
Sets the maximum penetration depth of the linear plastic-viscoelastic normal force.
void setDissipation (Mdouble dissipation)
Sets the linear dissipation coefficient of the linear plastic-viscoelastic normal force.
Mdouble getDissipation () const
Allows the normal dissipation to be accessed.
void setSinterRate (Mdouble sinterRate)
Sets the linear dissipation coefficient of the linear plastic-viscoelastic normal force.
Mdouble getSinterRate () const
Allows the normal dissipation to be accessed.
Mdouble computeTimeStep (Mdouble mass)
Returns the optimal time step to resolve a collision of two particles of a given mass.
Public Member Functions inherited from BaseNormalForce
BaseNormalForce ()
BaseNormalForce (const BaseNormalForce &p)
bool getConstantRestitution () const
void setConstantRestitution (bool constantRestitution)
virtual void actionsAfterTimeStep (BaseParticle *particle) const
Public Member Functions inherited from BaseForce
BaseSpecies * getBaseSpecies () const
void setBaseSpecies (BaseSpecies *baseSpecies)
Private Attributes
Mdouble loadingModulus_
(normal) spring constant (k_1)
Mdouble unloadingModulusMax_
the maximum elastic constant (k_2^max) for plastic deformations
Mdouble cohesionModulus_
the adhesive spring constant (k^c) for plastic deformations
Mdouble penetrationDepthMax_
the depth (relative to the normalized radius) at which k_2^max is used (phi_f)
Mdouble dissipation_
linear dissipation coefficient
Mdouble sinterRate_
Detailed Description
HertzianSinterNormalSpecies contains the parameters used to describe a plastic-cohesive normal force (Stefan Ludings plastic-cohesive force model).
See SinterNormalInteraction::computeForce for a description of the force law.
Member Typedef Documentation
InteractionType
typedef HertzianSinterInteraction HertzianSinterNormalSpecies::InteractionType
The correct Interaction type for this FrictionForceSpecies.
Constructor & Destructor Documentation
HertzianSinterNormalSpecies() [1/2]
HertzianSinterNormalSpecies::HertzianSinterNormalSpecies ()
The default constructor.
         : BaseNormalForce()
 {
     loadingModulus_ = 0.0;
     unloadingModulusMax_ = 0.0;
     cohesionModulus_ = 0.0;
     penetrationDepthMax_ = 0.0;
     dissipation_ = 0.0;
     sinterRate_ = 0.0;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"HertzianSinterNormalSpecies::HertzianSinterNormalSpecies() finished"<<std::endl;
 #endif
 }
References cohesionModulus_, dissipation_, loadingModulus_, penetrationDepthMax_, sinterRate_, and unloadingModulusMax_.
HertzianSinterNormalSpecies() [2/2]
HertzianSinterNormalSpecies::HertzianSinterNormalSpecies (const HertzianSinterNormalSpecies & p)
The default copy constructor.
Parameters
[in] 'the species that is copied'
         : BaseNormalForce(p)
 {
     loadingModulus_ = p.loadingModulus_;
     unloadingModulusMax_ = p.unloadingModulusMax_;
     cohesionModulus_ = p.cohesionModulus_;
     penetrationDepthMax_ = p.penetrationDepthMax_;
     dissipation_ = p.dissipation_;
     sinterRate_ = p.sinterRate_;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"HertzianSinterNormalSpecies::HertzianSinterNormalSpecies(const HertzianSinterNormalSpecies &p) finished"<<std::endl;
 #endif
 }
References cohesionModulus_, dissipation_, loadingModulus_, p, penetrationDepthMax_, sinterRate_, and unloadingModulusMax_.
~HertzianSinterNormalSpecies()
HertzianSinterNormalSpecies::~HertzianSinterNormalSpecies ()
The default destructor.
 {
 #ifdef DEBUG_DESTRUCTOR
     std::cout<<"HertzianSinterNormalSpecies::~HertzianSinterNormalSpecies() finished"<<std::endl;
 #endif
 }
Member Function Documentation
computeTimeStep()
Mdouble HertzianSinterNormalSpecies::computeTimeStep (Mdouble mass)
Returns the optimal time step to resolve a collision of two particles of a given mass.
Calculates collision time for stiffest spring constant, divides by 50
Parameters
[in] mass the optimal time step is computed to resolve a collision of two particles of this mass.
 {
 //    if (stiffnessMax / (.5 * mass) < mathsFunc::square(dissipation_ /mass)) {
 //        std::cerr << "Dissipation too high; max. allowed " << sqrt(2.0 * stiffnessMax * mass) << std::endl;
 //        return 0.02 * constants::pi / std::sqrt(2.0*stiffnessMax / mass);
 //    } else {
     logger(WARN, "Warning: Dissipation is not taken into account when computing the time step");
     ParticleSpecies* p = dynamic_cast<ParticleSpecies*>(getBaseSpecies());
     logger.assert_debug(p,"Empty particle handler");
     Mdouble radius = cbrt(mass * 3. / (4. * constants::pi * p->getDensity()));
     return 0.02 * constants::pi / std::sqrt(2.0 * getUnloadingModulusMax() * getPenetrationDepthMax() * radius / mass);
 }
References Eigen::numext::cbrt(), BaseForce::getBaseSpecies(), getPenetrationDepthMax(), getUnloadingModulusMax(), logger, p, constants::pi, UniformPSDSelfTest::radius, sqrt(), and WARN.
getBaseName()
std::string HertzianSinterNormalSpecies::getBaseName () const
Used in Species::getName to obtain a unique name for each Species.
Returns
a string containing the name of the species (minus the word "Species")
 {
     return "HertzianSinter";
 }
getCohesionModulus()
Mdouble HertzianSinterNormalSpecies::getCohesionModulus () const
Returns the cohesive stiffness of the linear plastic-viscoelastic normal force.
Returns
the cohesive stiffness of the linear plastic-viscoelastic normal force.
 {
     return cohesionModulus_;
 }
References cohesionModulus_.
Referenced by HertzianSinterInteraction::computeSinterForce().
getDissipation()
Mdouble HertzianSinterNormalSpecies::getDissipation () const
Allows the normal dissipation to be accessed.
Returns
the linear dissipation coefficient
 {
     return dissipation_;
 }
References dissipation_.
Referenced by HertzianSinterInteraction::computeSinterForce().
getLoadingModulus()
Mdouble HertzianSinterNormalSpecies::getLoadingModulus () const
Returns the loading stiffness of the linear plastic-viscoelastic normal force.
Returns
the loading stiffness of the linear plastic-viscoelastic normal force.
 {
     return loadingModulus_;
 }
References loadingModulus_.
Referenced by HertzianSinterInteraction::computeSinterForce(), HertzianSinterInteraction::getElasticEnergy(), and HertzianSinterInteraction::getUnloadingModulus().
getPenetrationDepthMax()
Mdouble HertzianSinterNormalSpecies::getPenetrationDepthMax () const
Returns the maximum penetration depth of the linear plastic-viscoelastic normal force.
Returns
the maximum penetration depth of the linear plastic-viscoelastic normal force.
 {
     return penetrationDepthMax_;
 }
References penetrationDepthMax_.
Referenced by HertzianSinterInteraction::computeSinterForce(), computeTimeStep(), and HertzianSinterInteraction::getUnloadingModulus().
getSinterRate()
Mdouble HertzianSinterNormalSpecies::getSinterRate () const
Allows the normal dissipation to be accessed.
Returns
the linear dissipation coefficient
 {
     return sinterRate_;
 }
References sinterRate_.
Referenced by HertzianSinterInteraction::computeSinterForce().
getUnloadingModulusMax()
Mdouble HertzianSinterNormalSpecies::getUnloadingModulusMax () const
Returns the maximum unloading stiffness of the linear plastic-viscoelastic normal force.
Returns
the maximum unloading stiffness of the linear plastic-viscoelastic normal force.
 {
     return unloadingModulusMax_;
 }
References unloadingModulusMax_.
Referenced by HertzianSinterInteraction::computeSinterForce(), computeTimeStep(), and HertzianSinterInteraction::getUnloadingModulus().
mix()
void HertzianSinterNormalSpecies::mix (HertzianSinterNormalSpecies * S, HertzianSinterNormalSpecies * T)
creates default values for mixed species
For all parameters we assume that the harmonic mean of the parameters of the original two species is a sensible default.
Parameters
[in] S,T the two species whose properties are mixed to create the new species
 {
     loadingModulus_ = BaseSpecies::average(S->getLoadingModulus(), T->getLoadingModulus());
     unloadingModulusMax_ = BaseSpecies::average(S->getUnloadingModulusMax(), T->getUnloadingModulusMax());
     cohesionModulus_ = BaseSpecies::average(S->getCohesionModulus(), T->getCohesionModulus());
     penetrationDepthMax_ = BaseSpecies::average(S->getPenetrationDepthMax(), T->getPenetrationDepthMax());
     dissipation_ = BaseSpecies::average(S->getDissipation(), T->getDissipation());
     sinterRate_ = BaseSpecies::average(S->getSinterRate(), T->getSinterRate());
 }
References BaseSpecies::average(), cohesionModulus_, dissipation_, loadingModulus_, penetrationDepthMax_, oomph::QuadTreeNames::S, sinterRate_, and unloadingModulusMax_.
read()
void HertzianSinterNormalSpecies::read (std::istream & is)
Reads the species properties from an input stream.
Parameters
[in] input stream (typically the restart file)
 {
     std::string dummy;
     is >> dummy >> loadingModulus_;
     is >> dummy >> unloadingModulusMax_;
     is >> dummy >> cohesionModulus_;
     is >> dummy >> penetrationDepthMax_;
     is >> dummy >> dissipation_;
     is >> dummy >> sinterRate_;
 }
References cohesionModulus_, dissipation_, loadingModulus_, penetrationDepthMax_, sinterRate_, oomph::Global_string_for_annotation::string(), and unloadingModulusMax_.
setCohesionModulus()
void HertzianSinterNormalSpecies::setCohesionModulus (Mdouble cohesionModulus)
Sets the cohesive stiffness of the linear plastic-viscoelastic normal force.
Parameters
[in] cohesionModulus the cohesive stiffness of the linear plastic-viscoelastic normal force.
 {
     cohesionModulus_ = cohesionModulus;
 }
References cohesionModulus_.
Referenced by setPlasticParameters().
setDissipation()
void HertzianSinterNormalSpecies::setDissipation (Mdouble dissipation)
Sets the linear dissipation coefficient of the linear plastic-viscoelastic normal force.
should be non-negative
Parameters
[in] dissipation the linear dissipation coefficient of the linear plastic-viscoelastic normal force.
 {
     if (dissipation >= 0)
     {
         dissipation_ = dissipation;
     }
     else
     {
         logger(ERROR, "setDissipation(%) argument has to be non-negative", dissipation);
     }
 }
References dissipation_, ERROR, and logger.
setLoadingModulus()
void HertzianSinterNormalSpecies::setLoadingModulus (Mdouble loadingModulus)
Sets the loading stiffness of the linear plastic-viscoelastic normal force.
Parameters
[in] loadingModulus the loading stiffness of the linear plastic-viscoelastic normal force.
 {
     loadingModulus_ = loadingModulus;
 }
References loadingModulus_.
Referenced by setPlasticParameters().
setPenetrationDepthMax()
void HertzianSinterNormalSpecies::setPenetrationDepthMax (Mdouble penetrationDepthMax)
Sets the maximum penetration depth of the linear plastic-viscoelastic normal force.
Parameters
[in] penetrationDepthMax the maximum penetration depth of the linear plastic-viscoelastic normal force.
 {
     penetrationDepthMax_ = penetrationDepthMax;
 }
References penetrationDepthMax_.
Referenced by setPlasticParameters().
setPlasticParameters()
void HertzianSinterNormalSpecies::setPlasticParameters (Mdouble loadingModulus, Mdouble unloadingModulusMax, Mdouble cohesionModulus, Mdouble penetrationDepthMax)
Sets all parameters of the linear plastic-viscoelastic normal force at once.
Parameters
[in] loadingModulus the loading stiffness of the linear plastic-viscoelastic normal force.
[in] unloadingModulusMax the maximum unloading stiffness of the linear plastic-viscoelastic normal force.
[in] cohesionModulus the cohesive stiffness of the linear plastic-viscoelastic normal force.
[in] penetrationDepthMax the maximum penetration depth of the linear plastic-viscoelastic normal force.
 {
     if (loadingModulus <= 0 || unloadingModulusMax <= 1.000001 * (loadingModulus + cohesionModulus) ||
         cohesionModulus < 0 || penetrationDepthMax < 0)
     {
         logger(ERROR, "Arguments of setPlasticParameters do not make sense");
     }
     setLoadingModulus(loadingModulus);
     setUnloadingModulusMax(unloadingModulusMax);
     setCohesionModulus(cohesionModulus);
     setPenetrationDepthMax(penetrationDepthMax);
 }
References ERROR, logger, setCohesionModulus(), setLoadingModulus(), setPenetrationDepthMax(), and setUnloadingModulusMax().
setSinterRate()
void HertzianSinterNormalSpecies::setSinterRate (Mdouble sinterRate)
Sets the linear dissipation coefficient of the linear plastic-viscoelastic normal force.
should be non-negative
Parameters
[in] the linear dissipation coefficient of the linear plastic-viscoelastic normal force.
 {
     if (sinterRate >= 0)
     {
         sinterRate_ = sinterRate;
     }
     else
     {
         logger(ERROR, "setSinterRate(%) argument has to be non-negative", sinterRate);
     }
 }
References ERROR, logger, and sinterRate_.
setUnloadingModulusMax()
void HertzianSinterNormalSpecies::setUnloadingModulusMax (Mdouble unloadingModulusMax)
Sets the maximum unloading stiffness of the linear plastic-viscoelastic normal force.
Parameters
[in] unloadingModulusMax the maximum unloading stiffness of the linear plastic-viscoelastic normal force.
 {
     unloadingModulusMax_ = unloadingModulusMax;
 }
References unloadingModulusMax_.
Referenced by setPlasticParameters().
write()
void HertzianSinterNormalSpecies::write (std::ostream & os) const
Writes the species properties to an output stream.
Parameters
[out] output stream (typically the restart file)
 {
     os << " loadingModulus " << loadingModulus_;
     os << " maxUnloadingModulus " << unloadingModulusMax_;
     os << " cohesionModulus " << cohesionModulus_;
     os << " maxPenetration " << penetrationDepthMax_;
     os << " dissipation " << dissipation_;
     os << " sinterRate " << sinterRate_;
 }
References cohesionModulus_, dissipation_, loadingModulus_, penetrationDepthMax_, sinterRate_, and unloadingModulusMax_.
Member Data Documentation
cohesionModulus_
Mdouble HertzianSinterNormalSpecies::cohesionModulus_ private
the adhesive spring constant (k^c) for plastic deformations
Referenced by getCohesionModulus(), HertzianSinterNormalSpecies(), mix(), read(), setCohesionModulus(), and write().
dissipation_
Mdouble HertzianSinterNormalSpecies::dissipation_ private
linear dissipation coefficient
Referenced by getDissipation(), HertzianSinterNormalSpecies(), mix(), read(), setDissipation(), and write().
loadingModulus_
Mdouble HertzianSinterNormalSpecies::loadingModulus_ private
(normal) spring constant (k_1)
Referenced by getLoadingModulus(), HertzianSinterNormalSpecies(), mix(), read(), setLoadingModulus(), and write().
penetrationDepthMax_
Mdouble HertzianSinterNormalSpecies::penetrationDepthMax_ private
the depth (relative to the normalized radius) at which k_2^max is used (phi_f)
Referenced by getPenetrationDepthMax(), HertzianSinterNormalSpecies(), mix(), read(), setPenetrationDepthMax(), and write().
sinterRate_
Mdouble HertzianSinterNormalSpecies::sinterRate_ private
Referenced by getSinterRate(), HertzianSinterNormalSpecies(), mix(), read(), setSinterRate(), and write().
unloadingModulusMax_
Mdouble HertzianSinterNormalSpecies::unloadingModulusMax_ private
the maximum elastic constant (k_2^max) for plastic deformations
Referenced by getUnloadingModulusMax(), HertzianSinterNormalSpecies(), mix(), read(), setUnloadingModulusMax(), and write().
The documentation for this class was generated from the following files:
HertzianSinterNormalSpecies.h
HertzianSinterNormalSpecies.cc