MercuryDPM: MyStraightLine Class Reference
MyStraightLine Class Reference
Straight 1D line in 2D space.
Public Member Functions
MyStraightLine (const Vector< double > &r_start, const Vector< double > &r_end)
Constructor: Pass start and end points.
MyStraightLine (const MyStraightLine &dummy)
Broken copy constructor.
void operator= (const MyStraightLine &)
Broken assignment operator.
~MyStraightLine ()
Destructor: Empty.
void position (const Vector< double > &zeta, Vector< double > &r) const
Position Vector at Lagrangian coordinate zeta.
MyStraightLine (const Vector< double > &r_start, const Vector< double > &r_end)
Constructor: Pass start and end points.
MyStraightLine (const MyStraightLine &dummy)
Broken copy constructor.
~MyStraightLine ()
Destructor: Empty.
void position (const Vector< double > &zeta, Vector< double > &r) const
Position Vector at Lagrangian coordinate zeta.
MyStraightLine (const Vector< double > &r_start, const Vector< double > &r_end)
Constructor: Pass start and end points.
MyStraightLine (const MyStraightLine &dummy)
Broken copy constructor.
void operator= (const MyStraightLine &)
Broken assignment operator.
~MyStraightLine ()
Destructor: Empty.
void position (const Vector< double > &zeta, Vector< double > &r) const
Position Vector at Lagrangian coordinate zeta.
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual unsigned ngeom_data () const
virtual Data * geom_data_pt (const unsigned &j)
virtual void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition_dt (const Vector< double > &zeta, const unsigned &j, Vector< double > &drdt)
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
virtual void locate_zeta (const Vector< double > &zeta, GeomObject *&sub_geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
Private Attributes
Vector< double > R_start
Start point of line.
Vector< double > R_end
End point of line.
Additional Inherited Members
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Detailed Description
Straight 1D line in 2D space.
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Constructor & Destructor Documentation
MyStraightLine() [1/6]
MyStraightLine::MyStraightLine (const Vector< double > & r_start, const Vector< double > & r_end) inline
Constructor: Pass start and end points.
   :  GeomObject(1,2), R_start(r_start), R_end(r_end)
   { }
MyStraightLine() [2/6]
MyStraightLine::MyStraightLine (const MyStraightLine & dummy) inline
Broken copy constructor.
   {
    BrokenCopy::broken_copy("MyStraightLine");
   }
References oomph::BrokenCopy::broken_copy().
~MyStraightLine() [1/3]
MyStraightLine::~MyStraightLine () inline
Destructor: Empty.
 {}
MyStraightLine() [3/6]
MyStraightLine::MyStraightLine (const Vector< double > & r_start, const Vector< double > & r_end) inline
Constructor: Pass start and end points.
   :  GeomObject(1,2), R_start(r_start), R_end(r_end)
   { }
MyStraightLine() [4/6]
MyStraightLine::MyStraightLine (const MyStraightLine & dummy) inline
Broken copy constructor.
   {
    BrokenCopy::broken_copy("MyStraightLine");
   }
References oomph::BrokenCopy::broken_copy().
~MyStraightLine() [2/3]
MyStraightLine::~MyStraightLine () inline
Destructor: Empty.
 {}
MyStraightLine() [5/6]
MyStraightLine::MyStraightLine (const Vector< double > & r_start, const Vector< double > & r_end) inline
Constructor: Pass start and end points.
   :  GeomObject(1,2), R_start(r_start), R_end(r_end)
   { }
MyStraightLine() [6/6]
MyStraightLine::MyStraightLine (const MyStraightLine & dummy) inline
Broken copy constructor.
   {
    BrokenCopy::broken_copy("MyStraightLine");
   }
References oomph::BrokenCopy::broken_copy().
~MyStraightLine() [3/3]
MyStraightLine::~MyStraightLine () inline
Destructor: Empty.
 {}
Member Function Documentation
operator=() [1/2]
void MyStraightLine::operator= (const MyStraightLine &) inline
Broken assignment operator.
   {
    BrokenCopy::broken_assign("MyStraightLine");
   }
References oomph::BrokenCopy::broken_assign().
operator=() [2/2]
void MyStraightLine::operator= (const MyStraightLine &) inline
Broken assignment operator.
   {
    BrokenCopy::broken_assign("MyStraightLine");
   }
References oomph::BrokenCopy::broken_assign().
position() [1/3]
void MyStraightLine::position (const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position Vector at Lagrangian coordinate zeta.
Implements oomph::GeomObject.
   {
    // Position Vector
    r[0] = R_start[0]+(R_end[0]-R_start[0])*zeta[0];
    r[1] = R_start[1]+(R_end[1]-R_start[1])*zeta[0];
   }
References UniformPSDSelfTest::r, and Eigen::zeta().
position() [2/3]
void MyStraightLine::position (const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position Vector at Lagrangian coordinate zeta.
Implements oomph::GeomObject.
   {
    // Position Vector
    r[0] = R_start[0]+(R_end[0]-R_start[0])*zeta[0];
    r[1] = R_start[1]+(R_end[1]-R_start[1])*zeta[0];
   }
References UniformPSDSelfTest::r, and Eigen::zeta().
position() [3/3]
void MyStraightLine::position (const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position Vector at Lagrangian coordinate zeta.
Implements oomph::GeomObject.
   {
    // Position Vector
    r[0] = R_start[0]+(R_end[0]-R_start[0])*zeta[0];
    r[1] = R_start[1]+(R_end[1]-R_start[1])*zeta[0];
   }
References UniformPSDSelfTest::r, and Eigen::zeta().
Member Data Documentation
R_end
Vector< double > MyStraightLine::R_end private
End point of line.
R_start
Vector< double > MyStraightLine::R_start private
Start point of line.
The documentation for this class was generated from the following files:
unstructured_acoustic_fsi.cc
unstructured_fourier_decomposed_acoustic_fsi.cc
unstructured_time_harmonic_elastic_annulus.cc