MercuryDPM: oomph::OomphLibException Class Reference
oomph::OomphLibException Class Reference
#include <oomph_definitions.h>
Public Member Functions
void disable_error_message ()
Protected Member Functions
OomphLibException (const std::string &error_description, const std::string &function_name, const char *location, const std::string &exception_type, std::ostream &exception_stream, const unsigned &output_width, bool list_trace_back)
~OomphLibException () throw ()
The destructor cannot throw an exception (C++ STL standard)
Protected Attributes
std::ostream * Exception_stream_pt
Exception stream to which we write message in destructor.
std::stringstream * Exception_stringstream_pt
String stream that records the error message.
bool Suppress_error_message
Detailed Description
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// ===================================================================== A Base class for oomph-lib run-time exception (error and warning) handling.
The class can only be instantiated by the derived classes OomphLibError and OomphLibWarning. The (protected) constructor combines its string arguments into a standard format for uniform exception reports which are written to the specified output stream.
Constructor & Destructor Documentation
OomphLibException()
oomph::OomphLibException::OomphLibException (const std::string & error_description, const std::string & function_name, const char * location, const std::string & exception_type, std::ostream & exception_stream, const unsigned & output_width, bool list_trace_back) protected
Constructor takes the error description, function name and a location string provided by the OOMPH_EXCEPTION_LOCATION macro and combines them into a standard header. The exception type will be the string "WARNING" or "ERROR" and the message is written to the exception_stream, with a specified output_width. Optionally provide a traceback of the function calls.
The OomphLibException constructor takes the error description, function name, a location string provided by the OOMPH_EXCEPTION_LOCATION and an exception type "WARNING" or "ERROR" and combines them into a standard error message that is written to the exception stream. The output_width of the message can also be specified. Optionally provide a traceback of the function calls.
     : std::runtime_error("OomphException")
   {
     // By default we shout
     Suppress_error_message = false;
     // Store exception stream
     Exception_stream_pt = &exception_stream;
     // Create storage for error message
     Exception_stringstream_pt = new std::stringstream;
     // Build an exception header string from the information passed
     // Start with a couple of new lines to space things out
     std::string exception_header = "\n\n";
     // Now add a dividing line
     for (unsigned i = 0; i < output_width; i++)
     {
       exception_header += "=";
     }
     exception_header += "\n";
     // Write the type of exception
     exception_header += "Oomph-lib ";
     exception_header += exception_type;
     // Add the function in which it occurs
     exception_header += "\n\n at ";
     exception_header += location;
     exception_header += "\n\n in ";
     exception_header += function_name;
     // Finish with two new lines
     exception_header += "\n\n";
     // and a closing line
     for (unsigned i = 0; i < (unsigned)(0.8 * output_width); i++)
     {
       exception_header += "-";
     }
     // Output the error header to the stream
     (*Exception_stringstream_pt) << exception_header << std::endl;
     // Report the error
     (*Exception_stringstream_pt) << std::endl << error_description << std::endl;
 #ifdef OOMPH_HAS_STACKTRACE
     // Print the stacktrace
     if (list_trace_back)
     {
       print_stacktrace((*Exception_stringstream_pt));
     }
 #endif
     // Finish off with another set of double lines
     for (unsigned i = 0; i < output_width; i++)
     {
       (*Exception_stringstream_pt) << "=";
     }
     (*Exception_stringstream_pt) << std::endl << std::endl;
     // Copy message to stream in terminate helper in case the message
     // doesn't get caught and/or doesn/t make it to the destructor
     (*TerminateHelper::Exception_stringstream_pt)
       << (*Exception_stringstream_pt).str();
   }
References Exception_stream_pt, Exception_stringstream_pt, i, print_stacktrace(), oomph::Global_string_for_annotation::string(), and Suppress_error_message.
~OomphLibException()
oomph::OomphLibException::~OomphLibException () throw () protected
The destructor cannot throw an exception (C++ STL standard)
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// The OomphLibException destructor actually spawns the error message created in the constructor (unless suppresed)
   {
     if (!Suppress_error_message)
     {
       (*Exception_stream_pt) << (*Exception_stringstream_pt).str();
     }
     delete Exception_stringstream_pt;
     Exception_stringstream_pt = 0;
   }
References Exception_stringstream_pt, and Suppress_error_message.
Member Function Documentation
disable_error_message()
void oomph::OomphLibException::disable_error_message () inline
Suppress issueing of the error message in destructor (useful if error is caught successfully!)
     {
       // Suppress output of message in destructor...
       Suppress_error_message = true;
       // ...and in the big cleanup operation at the end
       TerminateHelper::suppress_exception_error_messages();
     }
References Suppress_error_message, and oomph::TerminateHelper::suppress_exception_error_messages().
Member Data Documentation
Exception_stream_pt
std::ostream* oomph::OomphLibException::Exception_stream_pt protected
Exception stream to which we write message in destructor.
Referenced by OomphLibException().
Exception_stringstream_pt
std::stringstream* oomph::OomphLibException::Exception_stringstream_pt protected
String stream that records the error message.
Referenced by OomphLibException(), and ~OomphLibException().
Suppress_error_message
bool oomph::OomphLibException::Suppress_error_message protected
Boolean to suppress issuing of the error message in destructor (useful if error is caught successfully!)
Referenced by disable_error_message(), OomphLibException(), and ~OomphLibException().
The documentation for this class was generated from the following files:
oomph_definitions.h
oomph_definitions.cc