MercuryDPM: oomph::SecondInvariantHelper Namespace Reference
oomph::SecondInvariantHelper Namespace Reference
Functions
double second_invariant (const DenseMatrix< double > &tensor)
Compute second invariant of tensor.
Detailed Description
Helper namespace containing function that computes second invariant of tensor
Function Documentation
second_invariant()
double oomph::SecondInvariantHelper::second_invariant (const DenseMatrix< double > & tensor)
Compute second invariant of tensor.
     {
       // get size of tensor
       unsigned n = tensor.nrow();
       double trace_of_tensor = 0.0;
       double trace_of_tensor_squared = 0.0;
       for (unsigned i = 0; i < n; i++)
       {
         // Calculate the trace of the tensor: T_ii
         trace_of_tensor += tensor(i, i);
         // Calculate the trace of the tensor squared: T_ij T_ji
         for (unsigned j = 0; j < n; j++)
         {
           trace_of_tensor_squared += tensor(i, j) * tensor(j, i);
         }
       }
       // return the second invariant: 1.0/2.0*[(T_ii)^2 - T_ij T_ji]
       return 0.5 *
              (trace_of_tensor * trace_of_tensor - trace_of_tensor_squared);
     }
References i, j, n, and oomph::DenseMatrix< T >::nrow().
Referenced by oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::fill_in_generic_residual_contribution_axi_nst(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::get_traction(), get_Z2_flux(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::max_and_min_invariant_and_viscosity(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::max_and_min_invariant_and_viscosity(), output(), square_of_norm_of_fixed_point(), square_of_norm_of_strain_invariant(), square_of_norm_of_viscosity(), and oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::traction().