MercuryDPM: ChargedBondedParticleUnitTest.cpp File Reference
ChargedBondedParticleUnitTest.cpp File Reference
#include <iostream>
#include "Species/HertzianViscoelasticFrictionChargedBondedSpecies.h"
#include "DPMBase.h"
Classes
class ChargedBondedParticleUnitTest
In this file, the rolling behaviour of the tangential spring is tested. This is done by placing one normal partilce on top of a fixed partilce and letting graviry roll it over the other particle until it loses contact.
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
 {
     logger(INFO, "Species is neither Sinter nor LinearPlasticViscoelastic");
     //Putting details in more user-friendly terms
     //the maximum force exerted, i.e. when particles are in contact
     double maximumForce = 3;
     //the range of the force.
     //Note that the range is measured from the EDGE of the particle!
     double forceRange = 3;
     //based on user inputs, calculated the necessary adhesion stiffness
     double adStiffness = maximumForce / forceRange;
     //the strength of the force holding particles together
     double bondStrength = 100.0;
     ChargedBondedParticleUnitTest dpm;
     //setting the species of particles
     auto species = dpm.speciesHandler.copyAndAddObject(HertzianViscoelasticFrictionChargedBondedSpecies());
     //setting the material properties of the particles
     species->setDensity(6. / constants::pi);
     species->setEffectiveElasticModulus(1000.0);
     species->setSlidingFrictionCoefficient(0.0);
     species->setAdhesionForceMax(maximumForce);
     species->setAdhesionStiffness(adStiffness);
     species->setBondForceMax(bondStrength);
     species->setBondDissipation(0.2);
     species->setVanDerWaalsForceMax(1);
     species->setVanDerWaalsStiffness(10);
     species->setCharge(-1);
     //setting a second species of particles
     auto species2 = dpm.speciesHandler.copyAndAddObject(species);
     species2->setCharge(1);
     //Giving a name for the output file
     dpm.setName("ChargedBondedParticleUnitTest");
     //setting the time step of the problem
     dpm.setTimeStep(3e-3);
     dpm.setSaveCount(30);
     //setting gravity to zero to ensure only forces acting are inter-particle forces!
     dpm.setGravity(Vec3D(0, 0, 0));
     //setting the duration of the simulation in "simulation seconds" (determined by
     //the dimensions used in setup)
     dpm.setTimeMax(3.);
     //solving the problem!
     dpm.solve(argc, argv);
     helpers::writeToFile("ChargedBondedParticleUnitTest.gnu",
                          "set xlabel 'time [s]'\n"
                          "set ylabel 'total Energy [J]'\n"
                          "p 'ChargedBondedParticleUnitTest.ene' u 1:($2+$3+$4+$5) w l\n"
     );
     Mdouble eneElastic = dpm.getElasticEnergy();
     Mdouble eneKinetic = dpm.getKineticEnergy();
     if (fabs(eneElastic + eneKinetic - (4.03257e-05)) >= 1e-6)
     {
         logger(FATAL, "Particles have the wrong total energy. It is % and should be %", eneElastic+eneKinetic,
                5.33881e-6);
     }
 }
References BaseHandler< T >::copyAndAddObject(), e(), boost::multiprecision::fabs(), FATAL, DPMBase::getElasticEnergy(), DPMBase::getKineticEnergy(), INFO, logger, constants::pi, DPMBase::setGravity(), DPMBase::setName(), DPMBase::setSaveCount(), DPMBase::setTimeMax(), DPMBase::setTimeStep(), DPMBase::solve(), DPMBase::speciesHandler, and helpers::writeToFile().