MercuryDPM: oomph::RankFourTensor< T > Class Template Reference
oomph::RankFourTensor< T > Class Template Reference
A Rank 4 Tensor class.
#include <matrices.h>
Public Member Functions
RankFourTensor ()
Empty constructor.
RankFourTensor (const RankFourTensor &source_tensor)
Copy constructor: Deep copy.
RankFourTensor & operator= (const RankFourTensor &source_tensor)
Copy assignement.
RankFourTensor (const unsigned long &n)
One parameter constructor produces a nxnxnxn tensor.
RankFourTensor (const unsigned long &n_index1, const unsigned long &n_index2, const unsigned long &n_index3, const unsigned long &n_index4)
Four parameter constructor, general non-square tensor.
RankFourTensor (const unsigned long &n_index1, const unsigned long &n_index2, const unsigned long &n_index3, const unsigned long &n_index4, const T &initial_val)
Four parameter constructor, general non-square tensor.
virtual ~RankFourTensor ()
Destructor: delete the pointers.
void resize (const unsigned long &n)
Resize to a square nxnxnxn tensor.
void resize (const unsigned long &n_index1, const unsigned long &n_index2, const unsigned long &n_index3, const unsigned long &n_index4)
Resize to a general tensor.
void resize (const unsigned long &n_index1, const unsigned long &n_index2, const unsigned long &n_index3, const unsigned long &n_index4, const T &initial_value)
Resize to a general tensor.
void initialise (const T &val)
Initialise all values in the tensor to val.
unsigned long nindex1 () const
Return the range of index 1 of the tensor.
unsigned long nindex2 () const
Return the range of index 2 of the tensor.
unsigned long nindex3 () const
Return the range of index 3 of the tensor.
unsigned long nindex4 () const
Return the range of index 4 of the tensor.
T & operator() (const unsigned long &i, const unsigned long &j, const unsigned long &k, const unsigned long &l)
Overload the round brackets to give access as a(i,j,k,l)
T operator() (const unsigned long &i, const unsigned long &j, const unsigned long &k, const unsigned long &l) const
Overload a const version for read-only access as a(i,j,k,l)
T & raw_direct_access (const unsigned long &i)
const T & raw_direct_access (const unsigned long &i) const
unsigned offset (const unsigned long &i, const unsigned long &j) const
Private Member Functions
void range_check (const unsigned long &i, const unsigned long &j, const unsigned long &k, const unsigned long &l) const
Private Attributes
T * Tensordata
Private internal representation as pointer to data.
unsigned N
1st Tensor dimension
unsigned M
2nd Tensor dimension
unsigned P
3rd Tensor dimension
unsigned Q
4th Tensor dimension
Detailed Description
template<class T>
class oomph::RankFourTensor< T >
A Rank 4 Tensor class.
////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////
Constructor & Destructor Documentation
RankFourTensor() [1/5]
template<class T > oomph::RankFourTensor< T >::RankFourTensor () inline
Empty constructor.
 : Tensordata(0), N(0), M(0), P(0), Q(0) {}
RankFourTensor() [2/5]
template<class T > oomph::RankFourTensor< T >::RankFourTensor (const RankFourTensor< T > & source_tensor) inline
Copy constructor: Deep copy.
     {
       // Set row and column lengths
       N = source_tensor.nindex1();
       M = source_tensor.nindex2();
       P = source_tensor.nindex3();
       Q = source_tensor.nindex4();
       // Assign space for the data
       Tensordata = new T[N * M * P * Q];
       // Copy the data across from the other matrix
       for (unsigned i = 0; i < N; i++)
       {
         for (unsigned j = 0; j < M; j++)
         {
           for (unsigned k = 0; k < P; k++)
           {
             for (unsigned l = 0; l < Q; l++)
             {
               Tensordata[Q * (P * (M * i + j) + k) + l] =
                 source_tensor(i, j, k, l);
             }
           }
         }
       }
     }
References i, j, k, oomph::RankFourTensor< T >::M, oomph::RankFourTensor< T >::N, oomph::RankFourTensor< T >::nindex1(), oomph::RankFourTensor< T >::nindex2(), oomph::RankFourTensor< T >::nindex3(), oomph::RankFourTensor< T >::nindex4(), oomph::RankFourTensor< T >::P, oomph::RankFourTensor< T >::Q, and oomph::RankFourTensor< T >::Tensordata.
RankFourTensor() [3/5]
template<class T > oomph::RankFourTensor< T >::RankFourTensor (const unsigned long & n) inline
One parameter constructor produces a nxnxnxn tensor.
     {
       // Set row and column lengths
       N = n;
       M = n;
       P = n;
       Q = n;
       // Assign space for the n rows
       Tensordata = new T[N * M * P * Q];
       // Initialise to zero if required
 #ifdef OOMPH_INITIALISE_DENSE_MATRICES
       initialise(T(0));
 #endif
     }
References oomph::RankFourTensor< T >::initialise(), n, oomph::RankFourTensor< T >::N, oomph::RankFourTensor< T >::P, oomph::RankFourTensor< T >::Q, and oomph::RankFourTensor< T >::Tensordata.
RankFourTensor() [4/5]
template<class T > oomph::RankFourTensor< T >::RankFourTensor (const unsigned long & n_index1, const unsigned long & n_index2, const unsigned long & n_index3, const unsigned long & n_index4) inline
Four parameter constructor, general non-square tensor.
     {
       // Set row and column lengths
       N = n_index1;
       M = n_index2;
       P = n_index3;
       Q = n_index4;
       // Assign space for the n rows
       Tensordata = new T[N * M * P * Q];
       // Initialise to zero if required
 #ifdef OOMPH_INITIALISE_DENSE_MATRICES
       initialise(T(0));
 #endif
     }
References oomph::RankFourTensor< T >::initialise(), oomph::RankFourTensor< T >::N, oomph::RankFourTensor< T >::P, oomph::RankFourTensor< T >::Q, and oomph::RankFourTensor< T >::Tensordata.
RankFourTensor() [5/5]
template<class T > oomph::RankFourTensor< T >::RankFourTensor (const unsigned long & n_index1, const unsigned long & n_index2, const unsigned long & n_index3, const unsigned long & n_index4, const T & initial_val) inline
Four parameter constructor, general non-square tensor.
     {
       // Set row and column lengths
       N = n_index1;
       M = n_index2;
       P = n_index3;
       Q = n_index4;
       // Assign space for the n rows
       Tensordata = new T[N * M * P * Q];
       // Initialise to the initial value
       initialise(initial_val);
     }
References oomph::RankFourTensor< T >::initialise(), oomph::RankFourTensor< T >::N, oomph::RankFourTensor< T >::P, oomph::RankFourTensor< T >::Q, and oomph::RankFourTensor< T >::Tensordata.
~RankFourTensor()
template<class T > virtual oomph::RankFourTensor< T >::~RankFourTensor () inline virtual
Destructor: delete the pointers.
     {
       delete[] Tensordata;
       Tensordata = 0;
     }
References oomph::RankFourTensor< T >::Tensordata.
Member Function Documentation
initialise()
template<class T > void oomph::RankFourTensor< T >::initialise (const T & val) inline
Initialise all values in the tensor to val.
     {
       for (unsigned long i = 0; i < (N * M * P * Q); ++i)
       {
         Tensordata[i] = val;
       }
     }
References i, oomph::RankFourTensor< T >::N, oomph::RankFourTensor< T >::P, oomph::RankFourTensor< T >::Q, oomph::RankFourTensor< T >::Tensordata, and calibrate::val.
Referenced by oomph::RankFourTensor< T >::RankFourTensor(), and oomph::RankFourTensor< T >::resize().
nindex1()
template<class T > unsigned long oomph::RankFourTensor< T >::nindex1 () const inline
Return the range of index 1 of the tensor.
     {
       return N;
     }
References oomph::RankFourTensor< T >::N.
Referenced by oomph::FiniteElement::d_dshape_eulerian_dnodal_coordinates(), oomph::RankFourTensor< T >::operator=(), and oomph::RankFourTensor< T >::RankFourTensor().
nindex2()
template<class T > unsigned long oomph::RankFourTensor< T >::nindex2 () const inline
Return the range of index 2 of the tensor.
     {
       return M;
     }
References oomph::RankFourTensor< T >::M.
Referenced by oomph::FiniteElement::d_dshape_eulerian_dnodal_coordinates(), oomph::RankFourTensor< T >::operator=(), and oomph::RankFourTensor< T >::RankFourTensor().
nindex3()
template<class T > unsigned long oomph::RankFourTensor< T >::nindex3 () const inline
Return the range of index 3 of the tensor.
     {
       return P;
     }
References oomph::RankFourTensor< T >::P.
Referenced by oomph::FiniteElement::d_dshape_eulerian_dnodal_coordinates(), oomph::RankFourTensor< T >::operator=(), and oomph::RankFourTensor< T >::RankFourTensor().
nindex4()
template<class T > unsigned long oomph::RankFourTensor< T >::nindex4 () const inline
Return the range of index 4 of the tensor.
     {
       return Q;
     }
References oomph::RankFourTensor< T >::Q.
Referenced by oomph::FiniteElement::d_dshape_eulerian_dnodal_coordinates(), oomph::RankFourTensor< T >::operator=(), and oomph::RankFourTensor< T >::RankFourTensor().
offset()
template<class T > unsigned oomph::RankFourTensor< T >::offset (const unsigned long & i, const unsigned long & j) const inline
Caculate the offset in flat-packed C-style, column-major format, required for a given i,j. WARNING: Only for experienced users. Only use this if raw speed is of the essence, as in the solid mechanics problems.
     {
       return (Q * (P * (M * i + j) + 0) + 0);
     }
References i, j, oomph::RankFourTensor< T >::P, and oomph::RankFourTensor< T >::Q.
Referenced by oomph::RefineableQDPVDElement< DIM, NNODE_1D >::fill_in_generic_contribution_to_residuals_pvd(), oomph::RefineablePVDEquations< DIM >::fill_in_generic_contribution_to_residuals_pvd(), oomph::PVDEquations< DIM >::fill_in_generic_contribution_to_residuals_pvd(), oomph::ScaleCoupledElement< ELEMENT >::fill_in_generic_contribution_to_residuals_pvd(), oomph::VolumeCoupledElement< ELEMENT >::fill_in_generic_contribution_to_residuals_pvd(), oomph::RefineablePVDEquationsWithPressure< DIM >::fill_in_generic_residual_contribution_pvd_with_pressure(), and oomph::PVDEquationsWithPressure< DIM >::fill_in_generic_residual_contribution_pvd_with_pressure().
operator()() [1/2]
template<class T > T& oomph::RankFourTensor< T >::operator() (const unsigned long & i, const unsigned long & j, const unsigned long & k, const unsigned long & l) inline
Overload the round brackets to give access as a(i,j,k,l)
     {
 #ifdef RANGE_CHECKING
       this->range_check(i, j, k, l);
 #endif
       return Tensordata[Q * (P * (M * i + j) + k) + l];
     }
References i, j, k, oomph::RankFourTensor< T >::P, oomph::RankFourTensor< T >::Q, oomph::RankFourTensor< T >::range_check(), and oomph::RankFourTensor< T >::Tensordata.
operator()() [2/2]
template<class T > T oomph::RankFourTensor< T >::operator() (const unsigned long & i, const unsigned long & j, const unsigned long & k, const unsigned long & l) const inline
Overload a const version for read-only access as a(i,j,k,l)
     {
 #ifdef RANGE_CHECKING
       this->range_check(i, j, k, l);
 #endif
       return Tensordata[Q * (P * (M * i + j) + k) + l];
     }
References i, j, k, oomph::RankFourTensor< T >::P, oomph::RankFourTensor< T >::Q, oomph::RankFourTensor< T >::range_check(), and oomph::RankFourTensor< T >::Tensordata.
operator=()
template<class T > RankFourTensor& oomph::RankFourTensor< T >::operator= (const RankFourTensor< T > & source_tensor) inline
Copy assignement.
     {
       // Don't create a new matrix if the assignement is the identity
       if (this != &source_tensor)
       {
         // Check row and column length
         unsigned long n = source_tensor.nindex1();
         unsigned long m = source_tensor.nindex2();
         unsigned long p = source_tensor.nindex3();
         unsigned long q = source_tensor.nindex4();
         // Resize the tensor to be the same size as the old tensor
         if ((N != n) || (M != m) || (P != p) || (Q != q))
         {
           resize(n, m, p, q);
         }
         // Copy entries across from the other matrix
         for (unsigned long i = 0; i < N; i++)
         {
           for (unsigned long j = 0; j < M; j++)
           {
             for (unsigned long k = 0; k < P; k++)
             {
               for (unsigned long l = 0; l < Q; l++)
               {
                 (*this)(i, j, k, l) = source_tensor(i, j, k, l);
               }
             }
           }
         }
       }
       // Return reference to object itself (i.e. de-reference this pointer)
       return *this;
     }
References i, j, k, m, oomph::RankFourTensor< T >::M, n, oomph::RankFourTensor< T >::N, oomph::RankFourTensor< T >::nindex1(), oomph::RankFourTensor< T >::nindex2(), oomph::RankFourTensor< T >::nindex3(), oomph::RankFourTensor< T >::nindex4(), p, oomph::RankFourTensor< T >::P, Eigen::numext::q, oomph::RankFourTensor< T >::Q, and oomph::RankFourTensor< T >::resize().
range_check()
template<class T > void oomph::RankFourTensor< T >::range_check (const unsigned long & i, const unsigned long & j, const unsigned long & k, const unsigned long & l) const inline private
Range check to catch when an index is out of bounds, if so, it issues a warning message and dies by throwing an OomphLibError
     {
       if (i >= N)
       {
         std::ostringstream error_message;
         error_message << "Range Error: i=" << i << " is not in the range (0,"
                       << N - 1 << ")." << std::endl;
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
       else if (j >= M)
       {
         std::ostringstream error_message;
         error_message << "Range Error: j=" << j << " is not in the range (0,"
                       << M - 1 << ")." << std::endl;
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
       else if (k >= P)
       {
         std::ostringstream error_message;
         error_message << "Range Error: k=" << k << " is not in the range (0,"
                       << P - 1 << ")." << std::endl;
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
       else if (l >= Q)
       {
         std::ostringstream error_message;
         error_message << "Range Error: l=" << l << " is not in the range (0,"
                       << Q - 1 << ")." << std::endl;
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
     }
References i, j, k, oomph::RankFourTensor< T >::N, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::RankFourTensor< T >::P, and oomph::RankFourTensor< T >::Q.
Referenced by oomph::RankFourTensor< T >::operator()().
raw_direct_access() [1/2]
template<class T > T& oomph::RankFourTensor< T >::raw_direct_access (const unsigned long & i) inline
Direct access to internal storage of data in flat-packed C-style column-major format. WARNING: Only for experienced users. Only use this if raw speed is of the essence, as in the solid mechanics problems.
     {
       return Tensordata[i];
     }
References i, and oomph::RankFourTensor< T >::Tensordata.
Referenced by oomph::RefineableQDPVDElement< DIM, NNODE_1D >::fill_in_generic_contribution_to_residuals_pvd(), oomph::RefineablePVDEquations< DIM >::fill_in_generic_contribution_to_residuals_pvd(), oomph::PVDEquations< DIM >::fill_in_generic_contribution_to_residuals_pvd(), oomph::ScaleCoupledElement< ELEMENT >::fill_in_generic_contribution_to_residuals_pvd(), oomph::VolumeCoupledElement< ELEMENT >::fill_in_generic_contribution_to_residuals_pvd(), oomph::RefineablePVDEquationsWithPressure< DIM >::fill_in_generic_residual_contribution_pvd_with_pressure(), and oomph::PVDEquationsWithPressure< DIM >::fill_in_generic_residual_contribution_pvd_with_pressure().
raw_direct_access() [2/2]
template<class T > const T& oomph::RankFourTensor< T >::raw_direct_access (const unsigned long & i) const inline
Direct access to internal storage of data in flat-packed C-style column-major format. WARNING: Only for experienced users. Only use this if raw speed is of the essence, as in the solid mechanics problems.
     {
       return Tensordata[i];
     }
References i, and oomph::RankFourTensor< T >::Tensordata.
resize() [1/3]
template<class T > void oomph::RankFourTensor< T >::resize (const unsigned long & n) inline
Resize to a square nxnxnxn tensor.
     {
       resize(n, n, n, n);
     }
References n.
Referenced by oomph::RankFourTensor< T >::operator=().
resize() [2/3]
template<class T > void oomph::RankFourTensor< T >::resize (const unsigned long & n_index1, const unsigned long & n_index2, const unsigned long & n_index3, const unsigned long & n_index4) inline
Resize to a general tensor.
     {
       // If the sizes have not changed do nothing
       if ((n_index1 == N) && (n_index2 == M) && (n_index3 == P) &&
           (n_index4 == Q))
       {
         return;
       }
       // Store old sizes
       unsigned long n_old = N, m_old = M, p_old = P, q_old = Q;
       // Reassign the sizes
       N = n_index1;
       M = n_index2;
       P = n_index3;
       Q = n_index4;
       // Store pointer to old matrix data
       T* temp_tensor = Tensordata;
       // Re-create Tensordata in new size
       Tensordata = new T[N * M * P * Q];
 #ifdef OOMPH_INITIALISE_DENSE_MATRICES
       initialise(T(0));
 #endif
       // Transfer values
       unsigned long n_copy, m_copy, p_copy, q_copy;
       n_copy = std::min(n_old, n_index1);
       m_copy = std::min(m_old, n_index2);
       p_copy = std::min(p_old, n_index3);
       q_copy = std::min(q_old, n_index4);
       // If matrix has values, transfer them to new matrix
       // Loop over rows
       for (unsigned long i = 0; i < n_copy; i++)
       {
         // Loop over columns
         for (unsigned long j = 0; j < m_copy; j++)
         {
           // Loop over columns
           for (unsigned long k = 0; k < p_copy; k++)
           {
             // Loop over columns
             for (unsigned long l = 0; l < q_copy; l++)
             {
               // Transfer values from temp_tensor
               Tensordata[Q * (M * P * i + P * j + k) + l] =
                 temp_tensor[q_old * (m_old * p_old * i + p_old * j + k) + l];
             }
           }
         }
       }
       // Now kill storage for old tensor
       delete[] temp_tensor;
     }
References i, oomph::RankFourTensor< T >::initialise(), j, k, oomph::RankFourTensor< T >::M, min, oomph::RankFourTensor< T >::N, oomph::RankFourTensor< T >::P, oomph::RankFourTensor< T >::Q, and oomph::RankFourTensor< T >::Tensordata.
resize() [3/3]
template<class T > void oomph::RankFourTensor< T >::resize (const unsigned long & n_index1, const unsigned long & n_index2, const unsigned long & n_index3, const unsigned long & n_index4, const T & initial_value) inline
Resize to a general tensor.
     {
       // If the sizes have not changed do nothing
       if ((n_index1 == N) && (n_index2 == M) && (n_index3 == P) &&
           (n_index4 == Q))
       {
         return;
       }
       // Store old sizes
       unsigned long n_old = N, m_old = M, p_old = P, q_old = Q;
       // Reassign the sizes
       N = n_index1;
       M = n_index2;
       P = n_index3;
       Q = n_index4;
       // Store triple pointer to old matrix data
       T* temp_tensor = Tensordata;
       // Re-create Tensordata in new size
       Tensordata = new T[N * M * P * Q];
       // Initialise the newly allocated storage
       initialise(initial_value);
       // Transfer values
       unsigned long n_copy, m_copy, p_copy, q_copy;
       n_copy = std::min(n_old, n_index1);
       m_copy = std::min(m_old, n_index2);
       p_copy = std::min(p_old, n_index3);
       q_copy = std::min(q_old, n_index4);
       // If matrix has values, transfer them to new matrix
       // Loop over rows
       for (unsigned long i = 0; i < n_copy; i++)
       {
         // Loop over columns
         for (unsigned long j = 0; j < m_copy; j++)
         {
           // Loop over columns
           for (unsigned long k = 0; k < p_copy; k++)
           {
             // Loop over columns
             for (unsigned long l = 0; l < q_copy; l++)
             {
               // Transfer values from temp_tensor
               Tensordata[Q * (M * P * i + P * j + k) + l] =
                 temp_tensor[q_old * (m_old * p_old * i + p_old * j + k) + l];
             }
           }
         }
       }
       // Now kill storage for old tensor
       delete[] temp_tensor;
     }
References i, oomph::RankFourTensor< T >::initialise(), j, k, oomph::RankFourTensor< T >::M, min, oomph::RankFourTensor< T >::N, oomph::RankFourTensor< T >::P, oomph::RankFourTensor< T >::Q, and oomph::RankFourTensor< T >::Tensordata.
Member Data Documentation
M
template<class T > unsigned oomph::RankFourTensor< T >::M private
2nd Tensor dimension
Referenced by oomph::RankFourTensor< T >::nindex2(), oomph::RankFourTensor< T >::operator=(), oomph::RankFourTensor< T >::RankFourTensor(), and oomph::RankFourTensor< T >::resize().
N
template<class T > unsigned oomph::RankFourTensor< T >::N private
1st Tensor dimension
Referenced by oomph::RankFourTensor< T >::initialise(), oomph::RankFourTensor< T >::nindex1(), oomph::RankFourTensor< T >::operator=(), oomph::RankFourTensor< T >::range_check(), oomph::RankFourTensor< T >::RankFourTensor(), and oomph::RankFourTensor< T >::resize().
P
template<class T > unsigned oomph::RankFourTensor< T >::P private
3rd Tensor dimension
Referenced by oomph::RankFourTensor< T >::initialise(), oomph::RankFourTensor< T >::nindex3(), oomph::RankFourTensor< T >::offset(), oomph::RankFourTensor< T >::operator()(), oomph::RankFourTensor< T >::operator=(), oomph::RankFourTensor< T >::range_check(), oomph::RankFourTensor< T >::RankFourTensor(), and oomph::RankFourTensor< T >::resize().
Q
template<class T > unsigned oomph::RankFourTensor< T >::Q private
4th Tensor dimension
Referenced by oomph::RankFourTensor< T >::initialise(), oomph::RankFourTensor< T >::nindex4(), oomph::RankFourTensor< T >::offset(), oomph::RankFourTensor< T >::operator()(), oomph::RankFourTensor< T >::operator=(), oomph::RankFourTensor< T >::range_check(), oomph::RankFourTensor< T >::RankFourTensor(), and oomph::RankFourTensor< T >::resize().
Tensordata
template<class T > T* oomph::RankFourTensor< T >::Tensordata private
Private internal representation as pointer to data.
Referenced by oomph::RankFourTensor< T >::initialise(), oomph::RankFourTensor< T >::operator()(), oomph::RankFourTensor< T >::RankFourTensor(), oomph::RankFourTensor< T >::raw_direct_access(), oomph::RankFourTensor< T >::resize(), and oomph::RankFourTensor< T >::~RankFourTensor().
The documentation for this class was generated from the following file:
matrices.h