MercuryDPM: MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT > Class Template Reference
MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT > Class Template Reference
Public Member Functions
MortaringValidationProblem ()
void setup_multi_domain_interaction ()
void setup_refinement ()
void setup_elements ()
void build_constraint_elements ()
void add_mortaring_elements (Vector< ConstraintElement * > mortaring_elements)
void pin_dofs ()
void actions_before_adapt () override
void actions_after_adapt () override
Actions that are to be performed after a mesh adaptation.
void verify_mortared_nodes_coincide ()
void set_output_distance ()
void set_do_not_output_distance ()
void output ()
void run ()
MortaringValidationProblem ()
void setup_refinement ()
void setup_elements ()
void build_constraint_elements ()
void add_mortaring_elements (Vector< ConstraintElement * > mortaring_elements)
void pin_dofs ()
void actions_before_adapt () override
void actions_after_adapt () override
Actions that are to be performed after a mesh adaptation.
void verify_mortared_nodes_coincide ()
void run ()
MortaringValidationProblem (const unsigned flag)
Vector< ConstraintElement * > build_mortaring_elements ()
void add_mortaring_elements (Vector< ConstraintElement * > mortaring_elements)
void build_and_add_mortaring_elements ()
void actions_before_adapt ()
void actions_after_adapt ()
Actions that are to be performed after a mesh adaptation.
void pin_mortared_status_dofs ()
void verify_mortared_nodes_coincide ()
Public Member Functions inherited from oomph::Problem
virtual void debug_hook_fct (const unsigned &i)
void set_analytic_dparameter (double *const &parameter_pt)
void unset_analytic_dparameter (double *const &parameter_pt)
bool is_dparameter_calculated_analytically (double *const &parameter_pt)
void set_analytic_hessian_products ()
void unset_analytic_hessian_products ()
bool are_hessian_products_calculated_analytically ()
void set_pinned_values_to_zero ()
bool distributed () const
OomphCommunicator * communicator_pt ()
access function to the oomph-lib communicator
const OomphCommunicator * communicator_pt () const
access function to the oomph-lib communicator, const version
Problem ()
Problem (const Problem &dummy)=delete
Broken copy constructor.
void operator= (const Problem &)=delete
Broken assignment operator.
virtual ~Problem ()
Virtual destructor to clean up memory.
Mesh *& mesh_pt ()
Return a pointer to the global mesh.
Mesh *const & mesh_pt () const
Return a pointer to the global mesh (const version)
Mesh *& mesh_pt (const unsigned &imesh)
Mesh *const & mesh_pt (const unsigned &imesh) const
Return a pointer to the i-th submesh (const version)
unsigned nsub_mesh () const
Return number of submeshes.
unsigned add_sub_mesh (Mesh *const &mesh_pt)
void flush_sub_meshes ()
void build_global_mesh ()
void rebuild_global_mesh ()
LinearSolver *& linear_solver_pt ()
Return a pointer to the linear solver object.
LinearSolver *const & linear_solver_pt () const
Return a pointer to the linear solver object (const version)
LinearSolver *& mass_matrix_solver_for_explicit_timestepper_pt ()
LinearSolver * mass_matrix_solver_for_explicit_timestepper_pt () const
EigenSolver *& eigen_solver_pt ()
Return a pointer to the eigen solver object.
EigenSolver *const & eigen_solver_pt () const
Return a pointer to the eigen solver object (const version)
Time *& time_pt ()
Return a pointer to the global time object.
Time * time_pt () const
Return a pointer to the global time object (const version).
double & time ()
Return the current value of continuous time.
double time () const
Return the current value of continuous time (const version)
TimeStepper *& time_stepper_pt ()
const TimeStepper * time_stepper_pt () const
TimeStepper *& time_stepper_pt (const unsigned &i)
Return a pointer to the i-th timestepper.
ExplicitTimeStepper *& explicit_time_stepper_pt ()
Return a pointer to the explicit timestepper.
unsigned long set_timestepper_for_all_data (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data=false)
virtual void shift_time_values ()
Shift all values along to prepare for next timestep.
AssemblyHandler *& assembly_handler_pt ()
Return a pointer to the assembly handler object.
AssemblyHandler *const & assembly_handler_pt () const
Return a pointer to the assembly handler object (const version)
double & minimum_dt ()
Access function to min timestep in adaptive timestepping.
double & maximum_dt ()
Access function to max timestep in adaptive timestepping.
unsigned & max_newton_iterations ()
Access function to max Newton iterations before giving up.
void problem_is_nonlinear (const bool &prob_lin)
Access function to Problem_is_nonlinear.
double & max_residuals ()
bool & time_adaptive_newton_crash_on_solve_fail ()
Access function for Time_adaptive_newton_crash_on_solve_fail.
double & newton_solver_tolerance ()
void add_time_stepper_pt (TimeStepper *const &time_stepper_pt)
void set_explicit_time_stepper_pt (ExplicitTimeStepper *const &explicit_time_stepper_pt)
void initialise_dt (const double &dt)
void initialise_dt (const Vector< double > &dt)
Data *& global_data_pt (const unsigned &i)
Return a pointer to the the i-th global data object.
void add_global_data (Data *const &global_data_pt)
void flush_global_data ()
LinearAlgebraDistribution *const & dof_distribution_pt () const
Return the pointer to the dof distribution (read-only)
unsigned long ndof () const
Return the number of dofs.
unsigned ntime_stepper () const
Return the number of time steppers.
unsigned nglobal_data () const
Return the number of global data values.
unsigned self_test ()
Self-test: Check meshes and global data. Return 0 for OK.
void enable_store_local_dof_pt_in_elements ()
void disable_store_local_dof_pt_in_elements ()
unsigned long assign_eqn_numbers (const bool &assign_local_eqn_numbers=true)
void describe_dofs (std::ostream &out= *(oomph_info.stream_pt())) const
void enable_discontinuous_formulation ()
void disable_discontinuous_formulation ()
void get_dofs (DoubleVector &dofs) const
void get_dofs (const unsigned &t, DoubleVector &dofs) const
Return vector of the t'th history value of all dofs.
void set_dofs (const DoubleVector &dofs)
Set the values of the dofs.
void set_dofs (const unsigned &t, DoubleVector &dofs)
Set the history values of the dofs.
void set_dofs (const unsigned &t, Vector< double * > &dof_pt)
void add_to_dofs (const double &lambda, const DoubleVector &increment_dofs)
Add lambda x incremenet_dofs[l] to the l-th dof.
double * global_dof_pt (const unsigned &i)
double & dof (const unsigned &i)
i-th dof in the problem
double dof (const unsigned &i) const
i-th dof in the problem (const version)
double *& dof_pt (const unsigned &i)
Pointer to i-th dof in the problem.
double * dof_pt (const unsigned &i) const
Pointer to i-th dof in the problem (const version)
virtual void get_inverse_mass_matrix_times_residuals (DoubleVector &Mres)
virtual void get_dvaluesdt (DoubleVector &f)
virtual void get_residuals (DoubleVector &residuals)
Get the total residuals Vector for the problem.
virtual void get_jacobian (DoubleVector &residuals, DenseDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CRDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CCDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, SumOfMatrices &jacobian)
void get_fd_jacobian (DoubleVector &residuals, DenseMatrix< double > &jacobian)
Get the full Jacobian by finite differencing.
void get_derivative_wrt_global_parameter (double *const &parameter_pt, DoubleVector &result)
void get_hessian_vector_products (DoubleVectorWithHaloEntries const &Y, Vector< DoubleVectorWithHaloEntries > const &C, Vector< DoubleVectorWithHaloEntries > &product)
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, Vector< DoubleVector > &eigenvector, const bool &steady=true)
Solve the eigenproblem.
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, const bool &steady=true)
virtual void get_eigenproblem_matrices (CRDoubleMatrix &mass_matrix, CRDoubleMatrix &main_matrix, const double &shift=0.0)
void assign_eigenvector_to_dofs (DoubleVector &eigenvector)
Assign the eigenvector passed to the function to the dofs.
void add_eigenvector_to_dofs (const double &epsilon, const DoubleVector &eigenvector)
void store_current_dof_values ()
Store the current values of the degrees of freedom.
void restore_dof_values ()
Restore the stored values of the degrees of freedom.
void enable_jacobian_reuse ()
void disable_jacobian_reuse ()
Disable recycling of Jacobian in Newton iteration.
bool jacobian_reuse_is_enabled ()
Is recycling of Jacobian in Newton iteration enabled?
bool & use_predictor_values_as_initial_guess ()
void newton_solve ()
Use Newton method to solve the problem.
void enable_globally_convergent_newton_method ()
enable globally convergent Newton method
void disable_globally_convergent_newton_method ()
disable globally convergent Newton method
void newton_solve (unsigned const &max_adapt)
void steady_newton_solve (unsigned const &max_adapt=0)
void copy (Problem *orig_problem_pt)
virtual Problem * make_copy ()
virtual void read (std::ifstream &restart_file, bool &unsteady_restart)
virtual void read (std::ifstream &restart_file)
virtual void dump (std::ofstream &dump_file) const
void dump (const std::string &dump_file_name) const
void delete_all_external_storage ()
virtual void symmetrise_eigenfunction_for_adaptive_pitchfork_tracking ()
double * bifurcation_parameter_pt () const
void get_bifurcation_eigenfunction (Vector< DoubleVector > &eigenfunction)
void activate_fold_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const DoubleVector &normalisation, const bool &block_solve=true)
void activate_pitchfork_tracking (double *const &parameter_pt, const DoubleVector &symmetry_vector, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const double &omega, const DoubleVector &null_real, const DoubleVector &null_imag, const bool &block_solve=true)
void deactivate_bifurcation_tracking ()
void reset_assembly_handler_to_default ()
Reset the system to the standard non-augemented state.
double arc_length_step_solve (double *const &parameter_pt, const double &ds, const unsigned &max_adapt=0)
double arc_length_step_solve (Data *const &data_pt, const unsigned &data_index, const double &ds, const unsigned &max_adapt=0)
void reset_arc_length_parameters ()
int & sign_of_jacobian ()
void explicit_timestep (const double &dt, const bool &shift_values=true)
Take an explicit timestep of size dt.
void unsteady_newton_solve (const double &dt)
void unsteady_newton_solve (const double &dt, const bool &shift_values)
void unsteady_newton_solve (const double &dt, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const unsigned &suppress_resolve_after_spatial_adapt_flag, const bool &first, const bool &shift=true)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon, const bool &shift_values)
void assign_initial_values_impulsive ()
void assign_initial_values_impulsive (const double &dt)
void calculate_predictions ()
Calculate predictions.
void enable_mass_matrix_reuse ()
void disable_mass_matrix_reuse ()
bool mass_matrix_reuse_is_enabled ()
Return whether the mass matrix is being reused.
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly (DocInfo &doc_info)
void refine_uniformly_and_prune (DocInfo &doc_info)
void refine_uniformly ()
void refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform refinement for submesh i_mesh with documentation.
void refine_uniformly (const unsigned &i_mesh)
Do uniform refinement for submesh i_mesh without documentation.
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly (DocInfo &doc_info)
void p_refine_uniformly_and_prune (DocInfo &doc_info)
void p_refine_uniformly ()
void p_refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-refinement for submesh i_mesh with documentation.
void p_refine_uniformly (const unsigned &i_mesh)
Do uniform p-refinement for submesh i_mesh without documentation.
void refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const unsigned &i_mesh, const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void refine_selected_elements (const Vector< Vector< RefineableElement * >> &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void p_refine_selected_elements (const Vector< Vector< PRefineableElement * >> &elements_to_be_refined_pt)
unsigned unrefine_uniformly ()
unsigned unrefine_uniformly (const unsigned &i_mesh)
void p_unrefine_uniformly (DocInfo &doc_info)
void p_unrefine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-unrefinement for submesh i_mesh without documentation.
void adapt (unsigned &n_refined, unsigned &n_unrefined)
void adapt ()
void p_adapt (unsigned &n_refined, unsigned &n_unrefined)
void p_adapt ()
void adapt_based_on_error_estimates (unsigned &n_refined, unsigned &n_unrefined, Vector< Vector< double >> &elemental_error)
void adapt_based_on_error_estimates (Vector< Vector< double >> &elemental_error)
void get_all_error_estimates (Vector< Vector< double >> &elemental_error)
void doc_errors (DocInfo &doc_info)
Get max and min error for all elements in submeshes.
void doc_errors ()
Get max and min error for all elements in submeshes.
void enable_info_in_newton_solve ()
void disable_info_in_newton_solve ()
Disable the output of information when in the newton solver.
Public Member Functions inherited from oomph::ExplicitTimeSteppableObject
ExplicitTimeSteppableObject ()
Empty constructor.
ExplicitTimeSteppableObject (const ExplicitTimeSteppableObject &)=delete
Broken copy constructor.
void operator= (const ExplicitTimeSteppableObject &)=delete
Broken assignment operator.
virtual ~ExplicitTimeSteppableObject ()
Empty destructor.
virtual void actions_before_explicit_stage ()
virtual void actions_after_explicit_stage ()
Public Attributes
Vector< SolidMesh * > Constituent_mesh_pt
SolidMesh * Non_mortared_mesh_pt
Mesh * Mortaring_mesh_pt
ConstitutiveLaw * Constitutive_law_pt
double Nu
double E
DocInfo doc_info
Public Attributes inherited from oomph::Problem
bool Shut_up_in_newton_solve
Additional Inherited Members
Public Types inherited from oomph::Problem
typedef void(* SpatialErrorEstimatorFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error)
Function pointer for spatial error estimator.
typedef void(* SpatialErrorEstimatorWithDocFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error, DocInfo &doc_info)
Function pointer for spatial error estimator with doc.
Static Public Attributes inherited from oomph::Problem
static bool Suppress_warning_about_actions_before_read_unstructured_meshes
Protected Types inherited from oomph::Problem
enum Assembly_method {
Perform_assembly_using_vectors_of_pairs , Perform_assembly_using_two_vectors , Perform_assembly_using_maps , Perform_assembly_using_lists ,
Perform_assembly_using_two_arrays
}
Enumerated flags to determine which sparse assembly method is used.
Protected Member Functions inherited from oomph::Problem
unsigned setup_element_count_per_dof ()
virtual void sparse_assemble_row_or_column_compressed (Vector< int * > &column_or_row_index, Vector< int * > &row_or_column_start, Vector< double * > &value, Vector< unsigned > &nnz, Vector< double * > &residual, bool compressed_row_flag)
virtual void actions_before_newton_solve ()
virtual void actions_after_newton_solve ()
virtual void actions_before_newton_convergence_check ()
virtual void actions_before_newton_step ()
virtual void actions_after_newton_step ()
virtual void actions_before_implicit_timestep ()
virtual void actions_after_implicit_timestep ()
virtual void actions_after_implicit_timestep_and_error_estimation ()
virtual void actions_before_explicit_timestep ()
Actions that should be performed before each explicit time step.
virtual void actions_after_explicit_timestep ()
Actions that should be performed after each explicit time step.
virtual void actions_before_read_unstructured_meshes ()
virtual void actions_after_read_unstructured_meshes ()
virtual void actions_after_change_in_global_parameter (double *const &parameter_pt)
virtual void actions_after_change_in_bifurcation_parameter ()
virtual void actions_after_parameter_increase (double *const &parameter_pt)
double & dof_derivative (const unsigned &i)
double & dof_current (const unsigned &i)
virtual void set_initial_condition ()
virtual double global_temporal_error_norm ()
unsigned newton_solve_continuation (double *const &parameter_pt)
unsigned newton_solve_continuation (double *const &parameter_pt, DoubleVector &z)
void calculate_continuation_derivatives (double *const &parameter_pt)
void calculate_continuation_derivatives (const DoubleVector &z)
void calculate_continuation_derivatives_fd (double *const &parameter_pt)
bool does_pointer_correspond_to_problem_data (double *const &parameter_pt)
void set_consistent_pinned_values_for_continuation ()
Protected Attributes inherited from oomph::Problem
Vector< Problem * > Copy_of_problem_pt
std::map< double *, bool > Calculate_dparameter_analytic
bool Calculate_hessian_products_analytic
LinearAlgebraDistribution * Dof_distribution_pt
Vector< double * > Dof_pt
Vector of pointers to dofs.
DoubleVectorWithHaloEntries Element_count_per_dof
double Relaxation_factor
double Newton_solver_tolerance
unsigned Max_newton_iterations
Maximum number of Newton iterations.
unsigned Nnewton_iter_taken
Vector< double > Max_res
Maximum residuals at start and after each newton iteration.
double Max_residuals
bool Time_adaptive_newton_crash_on_solve_fail
bool Jacobian_reuse_is_enabled
Is re-use of Jacobian in Newton iteration enabled? Default: false.
bool Jacobian_has_been_computed
bool Problem_is_nonlinear
bool Pause_at_end_of_sparse_assembly
bool Doc_time_in_distribute
unsigned Sparse_assembly_method
unsigned Sparse_assemble_with_arrays_initial_allocation
unsigned Sparse_assemble_with_arrays_allocation_increment
Vector< Vector< unsigned > > Sparse_assemble_with_arrays_previous_allocation
double Numerical_zero_for_sparse_assembly
double FD_step_used_in_get_hessian_vector_products
bool Mass_matrix_reuse_is_enabled
bool Mass_matrix_has_been_computed
bool Discontinuous_element_formulation
double Minimum_dt
Minimum desired dt: if dt falls below this value, exit.
double Maximum_dt
Maximum desired dt.
double DTSF_max_increase
double DTSF_min_decrease
double Minimum_dt_but_still_proceed
bool Scale_arc_length
Boolean to control whether arc-length should be scaled.
double Desired_proportion_of_arc_length
Proportion of the arc-length to taken by the parameter.
double Theta_squared
int Sign_of_jacobian
Storage for the sign of the global Jacobian.
double Continuation_direction
double Parameter_derivative
Storage for the derivative of the global parameter wrt arc-length.
double Parameter_current
Storage for the present value of the global parameter.
bool Use_continuation_timestepper
Boolean to control original or new storage of dof stuff.
unsigned Dof_derivative_offset
unsigned Dof_current_offset
Vector< double > Dof_derivative
Storage for the derivative of the problem variables wrt arc-length.
Vector< double > Dof_current
Storage for the present values of the variables.
double Ds_current
Storage for the current step value.
unsigned Desired_newton_iterations_ds
double Minimum_ds
Minimum desired value of arc-length.
bool Bifurcation_detection
Boolean to control bifurcation detection via determinant of Jacobian.
bool Bisect_to_find_bifurcation
Boolean to control wheter bisection is used to located bifurcation.
bool First_jacobian_sign_change
Boolean to indicate whether a sign change has occured in the Jacobian.
bool Arc_length_step_taken
Boolean to indicate whether an arc-length step has been taken.
bool Use_finite_differences_for_continuation_derivatives
OomphCommunicator * Communicator_pt
The communicator for this problem.
bool Always_take_one_newton_step
double Timestep_reduction_factor_after_nonconvergence
bool Keep_temporal_error_below_tolerance
Static Protected Attributes inherited from oomph::Problem
static ContinuationStorageScheme Continuation_time_stepper
Storage for the single static continuation timestorage object.
Constructor & Destructor Documentation
MortaringValidationProblem() [1/3]
template<class ELEMENT , class NON_MORTAR_ELEMENT > MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::MortaringValidationProblem () inline
  {
   //  Create the two meshes - location of second mesh is dependent on the test case flag
   Constituent_mesh_pt.resize(2);
   Constituent_mesh_pt[0] = new RefineableSolidCubicMesh<ELEMENT>(2, 2, 2,
                                                        0.0, MeshSize::x_length/2.0,
                                                        0.0, MeshSize::y_length,
                                                        0.0, MeshSize::z_length);
   double x_offset = 0.0, y_offset = 0.0, z_offset = 0.0;
   x_offset = MeshSize::x_length/2.0;
   Constituent_mesh_pt[1] = new RefineableSolidCubicMesh<ELEMENT>(2, 2, 2,
                                                        x_offset, x_offset+MeshSize::x_length/2.0,
                                                        y_offset, y_offset+MeshSize::y_length,
                                                        z_offset, z_offset+MeshSize::z_length);
   // Create the non-mortared mesh
   Non_mortared_mesh_pt = new RefineableSolidCubicMesh<NON_MORTAR_ELEMENT>(4, 2, 2,
                                                                           0.0, MeshSize::x_length,
                                                                           0.0, MeshSize::y_length,
                                                                           0.0, MeshSize::z_length);
   for(auto m : {0,1})
   {
    // Disable refinemenet for all elements
    for(unsigned e=0; e<Constituent_mesh_pt[m]->nelement(); e++)
    {
     dynamic_cast<ELEMENT*>(Constituent_mesh_pt[m]->finite_element_pt(e))->disable_refinement();
    }
    // Enable refinement for the elements on the mortared boundary
    const Vector<unsigned> mortared_bounds{2,4};
    for(unsigned e=0; e<Constituent_mesh_pt[m]->nboundary_element(mortared_bounds[m]); e++)
    {
     dynamic_cast<ELEMENT*>(Constituent_mesh_pt[m]->boundary_element_pt(mortared_bounds[m], e))->enable_refinement();
    }
   }
   // Set refinement parameters
   MeshRefinement::error_estimator_pt=new Z2ErrorEstimator;
   setup_refinement();
   Max_residuals = 1e200;
   // Constitutve law
   Nu = 0.3;
   E = 1.0;
   Constitutive::Constitutive_law_pt = new GeneralisedHookean(&Nu, &E);
   // Pass to the elements
   setup_elements();
   pin_dofs();
   Mortaring_mesh_pt = new Mesh;
   // Add the mortaring elements to the mortaring mesh
   build_constraint_elements();
   // There are two external meshes so we need to accept failure for each of the times we perform
   //  setup_multi_domain_interaction
   setup_multi_domain_interaction();
   // Add the mesh as a sub mesh
   this->add_sub_mesh(Constituent_mesh_pt[0]);
   this->add_sub_mesh(Constituent_mesh_pt[1]);
   this->add_sub_mesh(Mortaring_mesh_pt);
   this->add_sub_mesh(Non_mortared_mesh_pt);
   this->build_global_mesh();
   this->assign_eqn_numbers();
   doc_info = DocInfo("RESLT_COMPARE_MORTARING_TO_NON_MORTARING");
   doc_info.number() = 0;
   output();
  }
References Constitutive::Constitutive_law_pt, Global_Physical_Variables::E, e(), MeshRefinement::error_estimator_pt, m, Constitutive_Parameters::Nu, oomph::output(), oomph::Multi_domain_functions::setup_multi_domain_interaction(), MeshSize::x_length, MeshSize::y_length, and MeshSize::z_length.
MortaringValidationProblem() [2/3]
template<class ELEMENT , class NON_MORTAR_ELEMENT > MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::MortaringValidationProblem () inline
  {
   //  Create the two meshes - location of second mesh is dependent on the test case flag
   Constituent_mesh_pt.resize(2);
   Constituent_mesh_pt[0] = new RefineableSolidCubicMesh<ELEMENT>(2, 2, 2,
                                                        0.0, 1.0,
                                                        0.0, 1.0,
                                                        0.0, 1.0);
   double x_offset = 0.0, y_offset = 0.0, z_offset = 0.0;
   x_offset = 1.0;
   Constituent_mesh_pt[1] = new RefineableSolidCubicMesh<ELEMENT>(2, 2, 2,
                                                        x_offset, x_offset+1.0,
                                                        y_offset, y_offset+1.0,
                                                        z_offset, z_offset+1.0);
   // Set refinement parameters
   MeshRefinement::error_estimator_pt=new Z2ErrorEstimator;
   setup_refinement();
   Max_residuals = 1e200;
   // Constitutve law
   Nu = 0.3;
   E = 1.0;
   Constitutive::Constitutive_law_pt = new GeneralisedHookean(&Nu, &E);
   // Pass to the elements
   setup_elements();
   pin_dofs();
   Mortaring_mesh_pt = new Mesh;
   // Add the mortaring elements to the mortaring mesh
   build_constraint_elements();
   // Add the mesh as a sub mesh
   this->add_sub_mesh(Constituent_mesh_pt[0]);
   this->add_sub_mesh(Constituent_mesh_pt[1]);
   this->add_sub_mesh(Mortaring_mesh_pt);
   this->build_global_mesh();
   this->assign_eqn_numbers();
   // refine_uniformly();
  }
References Constitutive::Constitutive_law_pt, Global_Physical_Variables::E, MeshRefinement::error_estimator_pt, and Constitutive_Parameters::Nu.
MortaringValidationProblem() [3/3]
template<class ELEMENT , class NON_MORTAR_ELEMENT > MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::MortaringValidationProblem (const unsigned flag) inline
  {
   //  Create the two meshes - location of second mesh is dependent on the test case flag
   Constituent_mesh_pt.resize(2);
   Constituent_mesh_pt[0] = new RefineableSolidCubicMesh<ELEMENT>(2, 2, 2,
                                                                  0.0, 1.0,
                                                                  0.0, 1.0,
                                                                  0.0, 1.0);
   double x_offset = 0.0, y_offset = 0.0, z_offset = 0.0;
   // Determine the offsets of the second mesh from the flag passed
   switch(flag)
   {
    case 0:
     x_offset = 1.0;
     break;
    case 1:
     x_offset = 1.0;
     y_offset = 1.0;
     break;
    case 2:
     x_offset = 1.0;
     y_offset = 1.0;
     z_offset = 1.0;
     break;
    case 3:
     x_offset = 1.0;
     y_offset = 0.5;
     z_offset = 0.5;
     break;
    case 4:
     x_offset = 1.0;
     y_offset = 0.5;
     z_offset = 0.5;
     // Move the top corner node so that it doesn't get mortared
     for(unsigned l=0; l<Constituent_mesh_pt[0]->nnode(); l++)
     {
      Vector<double> x = {Constituent_mesh_pt[0]->node_pt(l)->x(0),Constituent_mesh_pt[0]->node_pt(l)->x(1),Constituent_mesh_pt[0]->node_pt(l)->x(2)};
      if((x[0]-1.0)*(x[0]-1.0) + (x[1]-1.0)*(x[1]-1.0) + (x[2]-1.0)*(x[2]-1.0) < 1e-6)
      {
       Constituent_mesh_pt[0]->node_pt(l)->x(0) -= 1e-2;
       Constituent_mesh_pt[0]->node_pt(l)->x(1) -= 1e-2;
       Constituent_mesh_pt[0]->node_pt(l)->x(2) -= 1e-2;
       break;
      }
     }
     break;
    case 5:
     x_offset = 1.0;
     y_offset = 0.5;
     z_offset = 0.5;
     // Move the top corner node so that it doesn't get mortared
     for(unsigned l=0; l<Constituent_mesh_pt[0]->nnode(); l++)
     {
      Vector<double> x = {Constituent_mesh_pt[0]->node_pt(l)->x(0),Constituent_mesh_pt[0]->node_pt(l)->x(1),Constituent_mesh_pt[0]->node_pt(l)->x(2)};
      if((x[0]-1.0)*(x[0]-1.0) + (x[1]-1.0)*(x[1]-1.0) + (x[2]-0.5)*(x[2]-0.5) < 1e-6)
      {
       Constituent_mesh_pt[0]->node_pt(l)->x(0) -= 1e-2;
       Constituent_mesh_pt[0]->node_pt(l)->x(1) -= 1e-2;
       Constituent_mesh_pt[0]->node_pt(l)->x(2) -= 1e-2;
       break;
      }
     }
     break;
    case 6:
     x_offset = 1.0;
     y_offset = 0.5;
     z_offset = 0.5;
     // Move the top corner node so that it doesn't get mortared
     for(unsigned l=0; l<Constituent_mesh_pt[0]->nnode(); l++)
     {
      Vector<double> x = {Constituent_mesh_pt[0]->node_pt(l)->x(0),Constituent_mesh_pt[0]->node_pt(l)->x(1),Constituent_mesh_pt[0]->node_pt(l)->x(2)};
      if((x[0]-1.0)*(x[0]-1.0) + (x[1]-0.5)*(x[1]-0.5) + (x[2]-0.5)*(x[2]-0.5) < 1e-6)
      {
       Constituent_mesh_pt[0]->node_pt(l)->x(0) -= 1e-2;
       Constituent_mesh_pt[0]->node_pt(l)->x(1) -= 1e-2;
       Constituent_mesh_pt[0]->node_pt(l)->x(2) -= 1e-2;
       break;
      }
     }
     break;
    case 7:
     x_offset = 1.0;
     y_offset = 0.5;
     z_offset = 0.5;
     // Move the top corner node so that it doesn't get mortared
     for(unsigned l=0; l<Constituent_mesh_pt[0]->nnode(); l++)
     {
      Vector<double> x = {Constituent_mesh_pt[0]->node_pt(l)->x(0),Constituent_mesh_pt[0]->node_pt(l)->x(1),Constituent_mesh_pt[0]->node_pt(l)->x(2)};
      if((x[0]-1.0)*(x[0]-1.0) + (x[1]-0.5)*(x[1]-0.5) + (x[2]-1.0)*(x[2]-1.0) < 1e-6)
      {
       Constituent_mesh_pt[0]->node_pt(l)->x(0) -= 1e-2;
       Constituent_mesh_pt[0]->node_pt(l)->x(1) -= 1e-2;
       Constituent_mesh_pt[0]->node_pt(l)->x(2) -= 1e-2;
       break;
      }
     }
     break;
    default:
     throw OomphLibError("Not a valid validation flag",
                         OOMPH_CURRENT_FUNCTION,
                         OOMPH_EXCEPTION_LOCATION);
   }
   // We need to re-assign the lagrangian coordinates because it is these the mortaring procedures use to find where the node is, not the current coordinate
   Constituent_mesh_pt[0]->set_lagrangian_nodal_coordinates();
   Constituent_mesh_pt[1] = new RefineableSolidCubicMesh<ELEMENT>(2, 2, 2,
                                                                  x_offset, x_offset+1.0,
                                                                  y_offset, y_offset+1.0,
                                                                  z_offset, z_offset+1.0);
   Max_residuals = 1e200;
   // Pin the mortared status dofs. These are just to keep track of which nodes should be mortared and which shouldn't
   pin_mortared_status_dofs();
   // Set refinement parameters
   Z2ErrorEstimator* error_estimator_pt=new Z2ErrorEstimator;
   double nu = 1.0;
   ConstitutiveLaw* constitutive_law_pt = new GeneralisedHookean(&nu);
   for(unsigned i=0; i<2; i++)
   {
    dynamic_cast<RefineableBrickMesh<ELEMENT>*>(Constituent_mesh_pt[i])->spatial_error_estimator_pt()=error_estimator_pt;
    // Error targets for adaptive refinement
    dynamic_cast<RefineableBrickMesh<ELEMENT>*>(Constituent_mesh_pt[i])->max_permitted_error()=0.1;
    dynamic_cast<RefineableBrickMesh<ELEMENT>*>(Constituent_mesh_pt[i])->min_permitted_error()=0.01;
    // Tell the elements that they should report their mortared status
    for(unsigned e=0; e<Constituent_mesh_pt[i]->nelement(); e++)
    {
     ELEMENT* el_pt = dynamic_cast<ELEMENT*>(Constituent_mesh_pt[i]->element_pt(e));
     el_pt->constitutive_law_pt() = constitutive_law_pt;
     // Set the mortared status of all nodes to 1 - this means all nodes should be mortared
     for(unsigned l=0; l<Constituent_mesh_pt[i]->finite_element_pt(e)->nnode(); l++)
     {
      el_pt->set_mortared(l);
     }
    }
   }
   // Attempt to refine the mortared mesh - accept failures, we know there are nodes selected which will not have a counterpart node
   Mortaring_mesh_pt = new Mesh;
   // Add the mortaring elements to the mortaring mesh
   build_and_add_mortaring_elements();
   // We have now build the mortaring elements. This first time we should set the mortared status of all nodes to 0
   // and then set the status to 1 for all nodes which were mortared. This lets us see which nodes have been mortared
   for(unsigned i=0; i<2; i++)
   {
    // Tell the elements that they should report their mortared status
    for(unsigned e=0; e<Constituent_mesh_pt[i]->nelement(); e++)
    {
     ELEMENT* el_pt = dynamic_cast<ELEMENT*>(Constituent_mesh_pt[i]->element_pt(e));
     // Set the mortared status of all nodes to 1 - this means all nodes should be mortared
     for(unsigned l=0; l<Constituent_mesh_pt[i]->finite_element_pt(e)->nnode(); l++)
     {
      el_pt->set_not_mortared(l);
     }
    }
   }
   // Now loop over all mortaring elements and set the mortared status of all nodes to 1
   for(unsigned e=0; e<Mortaring_mesh_pt->nelement(); e++)
   {
    // At this point we know that all mortaring elements will be between pairs of nodes
    NodeNodeMortaringElement* m_el_pt = dynamic_cast<NodeNodeMortaringElement*>(Mortaring_mesh_pt->element_pt(e));
    for(unsigned l=0; l<2; l++)
    {
     m_el_pt->solid_node_pt(l)->set_value(m_el_pt->solid_node_pt(l)->nvalue() - 1, 1.0);
    }
   }
   // Add the constituent meshes as sub meshes
   this->add_sub_mesh(Constituent_mesh_pt[0]);
   this->add_sub_mesh(Constituent_mesh_pt[1]);
   this->add_sub_mesh(Mortaring_mesh_pt);
   this->build_global_mesh();
   this->assign_eqn_numbers();
   this->newton_solve();
   verify_mortared_nodes_coincide();
   refine_uniformly();
   verify_mortared_nodes_coincide();
   this->newton_solve();
   verify_mortared_nodes_coincide();
  }
References e(), MeshRefinement::error_estimator_pt, i, oomph::Data::nvalue(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::Data::set_value(), oomph::NodeNodeConstraintElement::solid_node_pt(), and plotDoE::x.
Member Function Documentation
actions_after_adapt() [1/3]
template<class ELEMENT , class NON_MORTAR_ELEMENT > void MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::actions_after_adapt () inline virtual
Actions that are to be performed after a mesh adaptation.
Reimplemented from oomph::Problem.
  {
   // Pin the dof representing if each node is (to be) mortared
   pin_mortared_status_dofs();
   // re-create the mortaring elements
   build_and_add_mortaring_elements();
   // rebuild mesh
   rebuild_global_mesh();
  }
actions_after_adapt() [2/3]
template<class ELEMENT , class NON_MORTAR_ELEMENT > void MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::actions_after_adapt () inline override virtual
Actions that are to be performed after a mesh adaptation.
Reimplemented from oomph::Problem.
  {
   // add the mortaring elements back
   build_constraint_elements();
   // rebuild mesh
   rebuild_global_mesh();
   // To get the elements to re-compute the ipt to node mapping
   setup_elements();
   // Setup multi domain interaction
   setup_multi_domain_interaction();
  }
References oomph::Multi_domain_functions::setup_multi_domain_interaction().
actions_after_adapt() [3/3]
template<class ELEMENT , class NON_MORTAR_ELEMENT > void MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::actions_after_adapt () inline override virtual
Actions that are to be performed after a mesh adaptation.
Reimplemented from oomph::Problem.
  {
   // add the mortaring elements back
   build_constraint_elements();
   // rebuild mesh
   rebuild_global_mesh();
  }
actions_before_adapt() [1/3]
template<class ELEMENT , class NON_MORTAR_ELEMENT > void MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::actions_before_adapt () inline virtual
Actions that are to be performed before a mesh adaptation. These might include removing any additional elements, such as traction boundary elements before the adaptation.
Reimplemented from oomph::Problem.
  {
   // Delete all mortaring elements
   unsigned long Element_pt_range = Mortaring_mesh_pt->nelement();
   for (unsigned long i = Element_pt_range; i > 0; i--)
   {
    delete Mortaring_mesh_pt->element_pt(i - 1);
   }
   // flush the mortaring mesh elements
   Mortaring_mesh_pt->flush_element_storage();
  }
References i.
actions_before_adapt() [2/3]
template<class ELEMENT , class NON_MORTAR_ELEMENT > void MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::actions_before_adapt () inline override virtual
Actions that are to be performed before a mesh adaptation. These might include removing any additional elements, such as traction boundary elements before the adaptation.
Reimplemented from oomph::Problem.
  {
   // Delete all mortaring elements
   unsigned long Element_pt_range = Mortaring_mesh_pt->nelement();
   for (unsigned long i = Element_pt_range; i > 0; i--)
   {
    delete Mortaring_mesh_pt->element_pt(i - 1);
   }
   // flush the mortaring mesh elements
   Mortaring_mesh_pt->flush_element_storage();
  }
References i.
actions_before_adapt() [3/3]
template<class ELEMENT , class NON_MORTAR_ELEMENT > void MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::actions_before_adapt () inline override virtual
Actions that are to be performed before a mesh adaptation. These might include removing any additional elements, such as traction boundary elements before the adaptation.
Reimplemented from oomph::Problem.
  {
   // Delete all mortaring elements
   unsigned long Element_pt_range = Mortaring_mesh_pt->nelement();
   for (unsigned long i = Element_pt_range; i > 0; i--)
   {
    delete Mortaring_mesh_pt->element_pt(i - 1);
   }
   // flush the mortaring mesh elements
   Mortaring_mesh_pt->flush_element_storage();
  }
References i.
add_mortaring_elements() [1/3]
template<class ELEMENT , class NON_MORTAR_ELEMENT > void MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::add_mortaring_elements (Vector< ConstraintElement * > mortaring_elements) inline
  {
   for(unsigned e=0; e<mortaring_elements.size(); e++)
   {
    Mortaring_mesh_pt->add_element_pt(dynamic_cast<GeneralisedElement*>(mortaring_elements[e]));
   }
  }
References e().
add_mortaring_elements() [2/3]
template<class ELEMENT , class NON_MORTAR_ELEMENT > void MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::add_mortaring_elements (Vector< ConstraintElement * > mortaring_elements) inline
  {
   for(unsigned e=0; e<mortaring_elements.size(); e++)
   {
    Mortaring_mesh_pt->add_element_pt(dynamic_cast<GeneralisedElement*>(mortaring_elements[e]));
   }
  }
References e().
add_mortaring_elements() [3/3]
template<class ELEMENT , class NON_MORTAR_ELEMENT > void MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::add_mortaring_elements (Vector< ConstraintElement * > mortaring_elements) inline
  {
   for(unsigned e=0; e<mortaring_elements.size(); e++)
   {
    Mortaring_mesh_pt->add_element_pt(dynamic_cast<GeneralisedElement*>(mortaring_elements[e]));
   }
  }
References e().
build_and_add_mortaring_elements()
template<class ELEMENT , class NON_MORTAR_ELEMENT > void MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::build_and_add_mortaring_elements () inline
  {
   add_mortaring_elements(build_mortaring_elements());
  }
build_constraint_elements() [1/2]
template<class ELEMENT , class NON_MORTAR_ELEMENT > void MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::build_constraint_elements () inline
  {
   // The boundary id on the m-th mesh
   Vector<unsigned> bounds{2,4};
   Vector<Vector<Node*>> nodes_to_be_mortared_pt(2);
   for(unsigned m : {0,1})
   {
    const unsigned n_bound_node = Constituent_mesh_pt[m]->nboundary_node(bounds[m]);
    nodes_to_be_mortared_pt[m].resize(n_bound_node);
    for(unsigned l=0; l<n_bound_node; l++)
    {
     nodes_to_be_mortared_pt[m][l] = Constituent_mesh_pt[m]->boundary_node_pt(bounds[m], l);
    }
   }
   // we mortared boundary 2 of constituent mesh 0 to boundary 4 of constituent mesh 1
   add_mortaring_elements(MortaringHelpers::setup_constraint_elements_at_nodes<NodeNodeMortaringElement,
                                                                               NodeElementSolidOnlyMortaringElement,
                                                                               ELEMENT>
                                                                               (this,
                                                                               nodes_to_be_mortared_pt,
                                                                               Constituent_mesh_pt));
  }
References m, and MortaringHelpers::setup_constraint_elements_at_nodes().
build_constraint_elements() [2/2]
template<class ELEMENT , class NON_MORTAR_ELEMENT > void MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::build_constraint_elements () inline
  {
   // The boundary id on the m-th mesh
   Vector<unsigned> bounds{2,4};
   Vector<Vector<Node*>> nodes_to_be_mortared_pt(2);
   for(unsigned m : {0,1})
   {
    const unsigned n_bound_node = Constituent_mesh_pt[m]->nboundary_node(bounds[m]);
    nodes_to_be_mortared_pt[m].resize(n_bound_node);
    for(unsigned l=0; l<n_bound_node; l++)
    {
     nodes_to_be_mortared_pt[m][l] = Constituent_mesh_pt[m]->boundary_node_pt(bounds[m], l);
    }
   }
   // we mortared bound 2 of constituent mesh 0 to bound 4 of constituent mesh 1
   add_mortaring_elements(MortaringHelpers::setup_constraint_elements_at_nodes<NodeNodeMortaringElement,
                                                                               NodeElementSolidOnlyMortaringElement,
                                                                               ELEMENT>
   (this,
    nodes_to_be_mortared_pt,
    Constituent_mesh_pt));
  }
References m, and MortaringHelpers::setup_constraint_elements_at_nodes().
build_mortaring_elements()
template<class ELEMENT , class NON_MORTAR_ELEMENT > Vector<ConstraintElement*> MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::build_mortaring_elements () inline
  {
   // Get all nodes - we try and mortar them all
   Vector<Vector<Node*>> nodes_to_be_mortared_pt(2);
   for(unsigned m=0;m<2;m++)
   {
    for(unsigned l=0; l<Constituent_mesh_pt[m]->nnode(); l++)
    {
     // if the node is marked for mortaring then add it to the list
     if(Constituent_mesh_pt[m]->node_pt(l)->value(Constituent_mesh_pt[m]->node_pt(l)->nvalue()-1) > 0.5)
     {
      nodes_to_be_mortared_pt[m].push_back(dynamic_cast<Node*>(Constituent_mesh_pt[m]->node_pt(l)));
     }
    }
   }
   // Build and return the mortaring elements - we want to accept failure, hence true
   Vector<ConstraintElement*> mortaring_elements = MortaringHelpers::setup_constraint_elements_at_nodes<NodeNodeMortaringElement,
                                                                                                        NodeElementSolidOnlyMortaringElement,
                                                                                                        ELEMENT>
                                                                                                       (this,
                                                                                                        nodes_to_be_mortared_pt,
                                                                                                        Constituent_mesh_pt,
                                                                                                        true);
   std::cout << "Created " << mortaring_elements.size() << " mortaring elements" << std::endl;
   return mortaring_elements;
  }
References m, MortaringHelpers::setup_constraint_elements_at_nodes(), and Eigen::value.
output()
template<class ELEMENT , class NON_MORTAR_ELEMENT > void MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::output () inline
  {
   Non_mortared_mesh_pt->output(doc_info.directory() + "/non_mortared_" + std::to_string(doc_info.number()++) + ".dat", 2);
   set_output_distance();
   Non_mortared_mesh_pt->output(doc_info.directory() + "/error_" + std::to_string(doc_info.number()++) + ".dat", 2);
   set_do_not_output_distance();
   for(unsigned m : {0,1})
   {
    Constituent_mesh_pt[m]->output(doc_info.directory() + "/mortared_mesh_" + std::to_string(m) + "_" + std::to_string(doc_info.number()++) + ".dat", 2);
   }
  }
References m, and oomph::StringConversion::to_string().
pin_dofs() [1/2]
template<class ELEMENT , class NON_MORTAR_ELEMENT > void MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::pin_dofs () inline
  {
   // Assign the dirichlet boundary conditions...
   // To the mortared mesh which is on the wall
   for(unsigned n=0; n<Constituent_mesh_pt[0]->nboundary_node(4); n++)
   {
    SolidNode* node_pt = dynamic_cast<SolidNode*>(Constituent_mesh_pt[0]->boundary_node_pt(4, n));
    node_pt->pin_position(0);
    node_pt->pin_position(1);
    node_pt->pin_position(2);
   }
   // To the non-mortared mesh
   for(unsigned n=0; n<Non_mortared_mesh_pt->nboundary_node(4); n++)
   {
    SolidNode* node_pt = dynamic_cast<SolidNode*>(Non_mortared_mesh_pt->boundary_node_pt(4, n));
    node_pt->pin_position(0);
    node_pt->pin_position(1);
    node_pt->pin_position(2);
   }
  }
References n, and oomph::SolidNode::pin_position().
pin_dofs() [2/2]
template<class ELEMENT , class NON_MORTAR_ELEMENT > void MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::pin_dofs () inline
  {
   for(unsigned n=0; n<Constituent_mesh_pt[0]->nboundary_node(4); n++)
   {
    SolidNode* node_pt = dynamic_cast<SolidNode*>(Constituent_mesh_pt[0]->boundary_node_pt(4, n));
    node_pt->pin_position(0);
    node_pt->pin_position(1);
    node_pt->pin_position(2);
   }
  }
References n, and oomph::SolidNode::pin_position().
pin_mortared_status_dofs()
template<class ELEMENT , class NON_MORTAR_ELEMENT > void MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::pin_mortared_status_dofs () inline
  {
   for(unsigned i=0; i<2; i++)
   {
    // Pin the mortared status dof of all nodes
    for(unsigned e=0; e<Constituent_mesh_pt[i]->nelement(); e++)
    {
     dynamic_cast<ELEMENT*>(Constituent_mesh_pt[i]->element_pt(e))->pin_mortared_status_of_all_nodes();
    }
   }
  }
References e(), and i.
run() [1/2]
template<class ELEMENT , class NON_MORTAR_ELEMENT > void MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::run () inline
  {
   for(unsigned i=0; i<8; i++)
   {
    std::cout << "Iteration: " << i << std::endl;
    newton_solve(1);
    output();
    // Make spatial error requirements more stringent
    // MeshRefinement::max_error/=2.0;
    // MeshRefinement::min_error/=2.0;
    gravity::gravity_magnitude*=1.2;
    setup_refinement();
    setup_elements();
    // Check if mortared nodes spatially coincide
    verify_mortared_nodes_coincide();
   }
  }
References gravity::gravity_magnitude, i, and oomph::output().
run() [2/2]
template<class ELEMENT , class NON_MORTAR_ELEMENT > void MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::run () inline
  {
   for(unsigned i=0; i<2; i++)
   {
    newton_solve(1);
    // Make spatial error requirements more stringent
    MeshRefinement::max_error/=2.0;
    MeshRefinement::min_error/=2.0;
    gravity::gravity_magnitude*=1.2;
    setup_refinement();
    setup_elements();
    // Check if mortared nodes spatially coincide
    verify_mortared_nodes_coincide();
   }
  }
References gravity::gravity_magnitude, i, MeshRefinement::max_error, and MeshRefinement::min_error.
set_do_not_output_distance()
template<class ELEMENT , class NON_MORTAR_ELEMENT > void MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::set_do_not_output_distance () inline
  {
   for(unsigned e=0; e<Non_mortared_mesh_pt->nelement(); e++)
   {
    dynamic_cast<NON_MORTAR_ELEMENT*>(Non_mortared_mesh_pt->element_pt(e))->set_do_not_output_distance();
   }
  }
References e().
set_output_distance()
template<class ELEMENT , class NON_MORTAR_ELEMENT > void MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::set_output_distance () inline
  {
   for(unsigned e=0; e<Non_mortared_mesh_pt->nelement(); e++)
   {
    dynamic_cast<NON_MORTAR_ELEMENT*>(Non_mortared_mesh_pt->element_pt(e))->set_output_distance();
   }
  }
References e().
setup_elements() [1/2]
template<class ELEMENT , class NON_MORTAR_ELEMENT > void MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::setup_elements () inline
  {
   for(unsigned m=0; m<2; m++)
   {
    for(unsigned e=0; e<Constituent_mesh_pt[m]->nelement(); e++)
    {
     dynamic_cast<ELEMENT*>(Constituent_mesh_pt[m]->element_pt(e))->constitutive_law_pt() = Constitutive::Constitutive_law_pt;
     dynamic_cast<ELEMENT*>(Constituent_mesh_pt[m]->element_pt(e))->body_force_fct_pt() = &gravity::gravity;
    }
   }
   for(unsigned e=0; e<Non_mortared_mesh_pt->nelement(); e++)
   {
    dynamic_cast<NON_MORTAR_ELEMENT*>(Non_mortared_mesh_pt->element_pt(e))->constitutive_law_pt() = Constitutive::Constitutive_law_pt;
    dynamic_cast<NON_MORTAR_ELEMENT*>(Non_mortared_mesh_pt->element_pt(e))->body_force_fct_pt() = &gravity::gravity;
    dynamic_cast<NON_MORTAR_ELEMENT*>(Non_mortared_mesh_pt->element_pt(e))->set_communicator_pt(this->communicator_pt());
    dynamic_cast<NON_MORTAR_ELEMENT*>(Non_mortared_mesh_pt->element_pt(e))->pre_compute_ipt_to_node_mapping();
   }
  }
References Constitutive::Constitutive_law_pt, e(), gravity::gravity(), and m.
setup_elements() [2/2]
template<class ELEMENT , class NON_MORTAR_ELEMENT > void MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::setup_elements () inline
  {
   for(unsigned m=0; m<2; m++)
   {
    for(unsigned e=0; e<Constituent_mesh_pt[m]->nelement(); e++)
    {
     dynamic_cast<ELEMENT*>(Constituent_mesh_pt[m]->element_pt(e))->constitutive_law_pt() = Constitutive::Constitutive_law_pt;
     dynamic_cast<ELEMENT*>(Constituent_mesh_pt[m]->element_pt(e))->body_force_fct_pt() = &gravity::gravity;
    }
   }
  }
References Constitutive::Constitutive_law_pt, e(), gravity::gravity(), and m.
setup_multi_domain_interaction()
template<class ELEMENT , class NON_MORTAR_ELEMENT > void MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::setup_multi_domain_interaction () inline
  {
   // The external element data is wiped before each setup_multi_domain_interaction
   //  We therefore need to store the external data for elements for which it has been set after the first setup_multi_domain_interaction
   //  Then we need to re-assign that data to the elements which have a null external element
   const unsigned n_element = Non_mortared_mesh_pt->nelement();
   Vector<Vector<FiniteElement*>> ext_elem_pt(n_element);
   Vector<Vector<Vector<double>>> ext_elem_local_coord_pt(n_element);
   for(unsigned e=0; e<n_element; e++)
   {
    const unsigned n_ipt = Non_mortared_mesh_pt->finite_element_pt(e)->integral_pt()->nweight();
    ext_elem_pt[e].resize(n_ipt);
    ext_elem_local_coord_pt[e].resize(n_ipt);
   }
   Multi_domain_functions::Accept_failed_locate_zeta_in_setup_multi_domain_interaction = true;
   Multi_domain_functions::setup_multi_domain_interaction<ELEMENT>(this, Non_mortared_mesh_pt, Constituent_mesh_pt[0], 0);
   // Store the external element data which is not null
   for(unsigned e=0; e<n_element; e++)
   {
    const unsigned n_ipt = Non_mortared_mesh_pt->finite_element_pt(e)->integral_pt()->nweight();
    for(unsigned ipt=0; ipt<n_ipt; ipt++)
    {
     if(dynamic_cast<ElementWithExternalElement*>(Non_mortared_mesh_pt->element_pt(e))->external_element_pt(0, ipt) != 0)
     {
      ext_elem_pt[e][ipt] = dynamic_cast<ElementWithExternalElement*>(Non_mortared_mesh_pt->element_pt(e))->external_element_pt(0, ipt);
      ext_elem_local_coord_pt[e][ipt] = dynamic_cast<ElementWithExternalElement*>(Non_mortared_mesh_pt->element_pt(e))->external_element_local_coord(0, ipt);
     }
    }
   }
   Multi_domain_functions::setup_multi_domain_interaction<ELEMENT>(this, Non_mortared_mesh_pt, Constituent_mesh_pt[1], 0);
   // Restore the external element data to external data which is null
   for(unsigned e=0; e<n_element; e++)
   {
    const unsigned n_ipt = Non_mortared_mesh_pt->finite_element_pt(e)->integral_pt()->nweight();
    for(unsigned ipt=0; ipt<n_ipt; ipt++)
    {
     if(dynamic_cast<ElementWithExternalElement*>(Non_mortared_mesh_pt->element_pt(e))->external_element_pt(0, ipt) == 0)
     {
      dynamic_cast<ElementWithExternalElement*>(Non_mortared_mesh_pt->element_pt(e))->external_element_pt(0, ipt) = ext_elem_pt[e][ipt];
      dynamic_cast<ElementWithExternalElement*>(Non_mortared_mesh_pt->element_pt(e))->external_element_local_coord(0, ipt) = ext_elem_local_coord_pt[e][ipt];
     }
    }
   }
  }
References oomph::Multi_domain_functions::Accept_failed_locate_zeta_in_setup_multi_domain_interaction, e(), and oomph::ElementWithExternalElement::external_element_pt().
setup_refinement() [1/2]
template<class ELEMENT , class NON_MORTAR_ELEMENT > void MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::setup_refinement () inline
  {
   for(unsigned m:{0,1})
   {
    dynamic_cast<RefineableSolidCubicMesh<ELEMENT>*>(Constituent_mesh_pt[m])->spatial_error_estimator_pt()=MeshRefinement::error_estimator_pt;
    // Error targets for adaptive refinement
    dynamic_cast<RefineableSolidCubicMesh<ELEMENT>*>(Constituent_mesh_pt[m])->max_permitted_error()=MeshRefinement::max_error;
    dynamic_cast<RefineableSolidCubicMesh<ELEMENT>*>(Constituent_mesh_pt[m])->min_permitted_error()=MeshRefinement::min_error;
   }
   dynamic_cast<RefineableSolidCubicMesh<NON_MORTAR_ELEMENT>*>(Non_mortared_mesh_pt)->spatial_error_estimator_pt()=MeshRefinement::error_estimator_pt;
   // Error targets for adaptive refinement
   dynamic_cast<RefineableSolidCubicMesh<NON_MORTAR_ELEMENT>*>(Non_mortared_mesh_pt)->max_permitted_error()=MeshRefinement::max_error;
   dynamic_cast<RefineableSolidCubicMesh<NON_MORTAR_ELEMENT>*>(Non_mortared_mesh_pt)->min_permitted_error()=MeshRefinement::min_error;
  }
References MeshRefinement::error_estimator_pt, m, MeshRefinement::max_error, and MeshRefinement::min_error.
setup_refinement() [2/2]
template<class ELEMENT , class NON_MORTAR_ELEMENT > void MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::setup_refinement () inline
  {
   for(unsigned m:{0,1})
   {
    dynamic_cast<RefineableSolidCubicMesh<ELEMENT>*>(Constituent_mesh_pt[m])->spatial_error_estimator_pt()=MeshRefinement::error_estimator_pt;
    // Error targets for adaptive refinement
    dynamic_cast<RefineableSolidCubicMesh<ELEMENT>*>(Constituent_mesh_pt[m])->max_permitted_error()=MeshRefinement::max_error;
    dynamic_cast<RefineableSolidCubicMesh<ELEMENT>*>(Constituent_mesh_pt[m])->min_permitted_error()=MeshRefinement::min_error;
   }
  }
References MeshRefinement::error_estimator_pt, m, MeshRefinement::max_error, and MeshRefinement::min_error.
verify_mortared_nodes_coincide() [1/3]
template<class ELEMENT , class NON_MORTAR_ELEMENT > void MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::verify_mortared_nodes_coincide () inline
  {
   for(unsigned e=0; e<Mortaring_mesh_pt->nelement(); e++)
   {
    {
     NodeNodeMortaringElement* el_pt = dynamic_cast<NodeNodeMortaringElement*>(Mortaring_mesh_pt->element_pt(e));
     if(el_pt != 0)
     {
      // Get the nodes and check their distance
      SolidNode* node0_pt = el_pt->solid_node_pt(0);
      SolidNode* node1_pt = el_pt->solid_node_pt(1);
      double distance = 0.0;
      for(unsigned i=0; i<3; i++)
      {
       distance += pow(node0_pt->x(i) - node1_pt->x(i), 2.0);
      }
      distance = sqrt(distance);
      // Assert that the distance is within the expected tolerance
      helpers::check(distance, 0.0, 1e-10, "Distance between mortared nodes");
      // Go to the next mortaring element
      continue;
     }
    }
    // If we did not continue that means we need to try with a node-element mortaring element
    {
     NodeElementSolidOnlyMortaringElement* el_pt = dynamic_cast<NodeElementSolidOnlyMortaringElement*>(Mortaring_mesh_pt->element_pt(e));
     if(el_pt != 0)
     {
      // Get the node and element and check their distance
      SolidNode* node_pt = el_pt->solid_node_pt();
      Vector<double> x_in_elem(3, 0.0);
      el_pt->position_in_element(x_in_elem);
      double distance = 0.0;
      for(unsigned i=0; i<3; i++)
      {
       distance += pow(node_pt->x(i) - x_in_elem[i], 2.0);
      }
      distance = sqrt(distance);
      // Assert that the distance is within the expected tolerance
      helpers::check(distance, 0.0, 1e-10, "Distance between mortared node and element");
      // Go to the next mortaring element
      continue;
     }
     // Should never get here but throw an error if we do
     logger(FATAL, "Mortaring element was not of an expected type.");
    }
   }
  }
References helpers::check(), e(), FATAL, i, logger, oomph::NodeElementSolidOnlyMortaringElement::position_in_element(), Eigen::bfloat16_impl::pow(), oomph::NodeElementSolidOnlyMortaringElement::solid_node_pt(), oomph::NodeNodeConstraintElement::solid_node_pt(), sqrt(), and oomph::Node::x().
verify_mortared_nodes_coincide() [2/3]
template<class ELEMENT , class NON_MORTAR_ELEMENT > void MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::verify_mortared_nodes_coincide () inline
  {
   for(unsigned e=0; e<Mortaring_mesh_pt->nelement(); e++)
   {
    {
     NodeNodeMortaringElement* el_pt = dynamic_cast<NodeNodeMortaringElement*>(Mortaring_mesh_pt->element_pt(e));
     if(el_pt != 0)
     {
      // Get the nodes and check their distance
      SolidNode* node0_pt = el_pt->solid_node_pt(0);
      SolidNode* node1_pt = el_pt->solid_node_pt(1);
      double distance = 0.0;
      for(unsigned i=0; i<3; i++)
      {
       distance += pow(node0_pt->x(i) - node1_pt->x(i), 2.0);
      }
      distance = sqrt(distance);
      // Assert that the distance is within the expected tolerance
      helpers::check(distance, 0.0, 1e-10, "Distance between mortared nodes");
      // Go to the next mortaring element
      continue;
     }
    }
    // If we did not continue that means we need to try with a node-element mortaring element
    {
     NodeElementSolidOnlyMortaringElement* el_pt = dynamic_cast<NodeElementSolidOnlyMortaringElement*>(Mortaring_mesh_pt->element_pt(e));
     if(el_pt != 0)
     {
      // Get the node and element and check their distance
      SolidNode* node_pt = el_pt->solid_node_pt();
      Vector<double> x_in_elem(3, 0.0);
      el_pt->position_in_element(x_in_elem);
      double distance = 0.0;
      for(unsigned i=0; i<3; i++)
      {
       distance += pow(node_pt->x(i) - x_in_elem[i], 2.0);
      }
      distance = sqrt(distance);
      // Assert that the distance is within the expected tolerance
      helpers::check(distance, 0.0, 1e-10, "Distance between mortared node and element");
      // Go to the next mortaring element
      continue;
     }
     // Should never get here but throw an error if we do
     logger(FATAL, "Mortaring element was not of an expected type.");
    }
   }
  }
References helpers::check(), e(), FATAL, i, logger, oomph::NodeElementSolidOnlyMortaringElement::position_in_element(), Eigen::bfloat16_impl::pow(), oomph::NodeElementSolidOnlyMortaringElement::solid_node_pt(), oomph::NodeNodeConstraintElement::solid_node_pt(), sqrt(), and oomph::Node::x().
verify_mortared_nodes_coincide() [3/3]
template<class ELEMENT , class NON_MORTAR_ELEMENT > void MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::verify_mortared_nodes_coincide () inline
  {
   for(unsigned e=0; e<Mortaring_mesh_pt->nelement(); e++)
   {
    {
     NodeNodeMortaringElement* el_pt = dynamic_cast<NodeNodeMortaringElement*>(Mortaring_mesh_pt->element_pt(e));
     if(el_pt != 0)
     {
      // Get the nodes and check their distance
      SolidNode* node0_pt = el_pt->solid_node_pt(0);
      SolidNode* node1_pt = el_pt->solid_node_pt(1);
      double distance = 0.0;
      for(unsigned i=0; i<3; i++)
      {
       distance += pow(node0_pt->x(i) - node1_pt->x(i), 2.0);
      }
      distance = sqrt(distance);
      // Assert that the distance is within the expected tolerance
      helpers::check(distance, 0.0, 1e-10, "Distance between mortared nodes");
      // Go to the next mortaring element
      continue;
     }
    }
    // If we did not continue that means we need to try with a node-element mortaring element
    {
     NodeElementSolidOnlyMortaringElement* el_pt = dynamic_cast<NodeElementSolidOnlyMortaringElement*>(Mortaring_mesh_pt->element_pt(e));
     if(el_pt != 0)
     {
      // Get the node and element and check their distance
      SolidNode* node_pt = el_pt->solid_node_pt();
      Vector<double> x_in_elem(3, 0.0);
      el_pt->position_in_element(x_in_elem);
      double distance = 0.0;
      for(unsigned i=0; i<3; i++)
      {
       distance += pow(node_pt->x(i) - x_in_elem[i], 2.0);
      }
      distance = sqrt(distance);
      // Assert that the distance is within the expected tolerance
      helpers::check(distance, 0.0, 1e-10, "Distance between mortared node and element");
     }
     // Should never get here but throw an error if we do
     logger(FATAL, "Mortaring element was not of an expected type.");
    }
   }
  }
References helpers::check(), e(), FATAL, i, logger, oomph::NodeElementSolidOnlyMortaringElement::position_in_element(), Eigen::bfloat16_impl::pow(), oomph::NodeElementSolidOnlyMortaringElement::solid_node_pt(), oomph::NodeNodeConstraintElement::solid_node_pt(), sqrt(), and oomph::Node::x().
Member Data Documentation
Constituent_mesh_pt
template<class ELEMENT , class NON_MORTAR_ELEMENT > Vector< SolidMesh * > MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::Constituent_mesh_pt
Constitutive_law_pt
template<class ELEMENT , class NON_MORTAR_ELEMENT > ConstitutiveLaw * MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::Constitutive_law_pt
doc_info
template<class ELEMENT , class NON_MORTAR_ELEMENT > DocInfo MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::doc_info
E
template<class ELEMENT , class NON_MORTAR_ELEMENT > double MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::E
Mortaring_mesh_pt
template<class ELEMENT , class NON_MORTAR_ELEMENT > Mesh * MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::Mortaring_mesh_pt
Non_mortared_mesh_pt
template<class ELEMENT , class NON_MORTAR_ELEMENT > SolidMesh* MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::Non_mortared_mesh_pt
Nu
template<class ELEMENT , class NON_MORTAR_ELEMENT > double MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::Nu
The documentation for this class was generated from the following files:
MortaringCantileverCompareToNonMortaring.cpp
MortaringCantileverUnitTest.cpp
MortaringCubesUnitTest.cpp