MercuryDPM: Eigen::internal::llt_inplace< Scalar, Lower > Struct Template Reference
Eigen::internal::llt_inplace< Scalar, Lower > Struct Template Reference
#include <LLT.h>
Public Types
typedef NumTraits< Scalar >::Real RealScalar
Static Public Member Functions
template<typename MatrixType >
static Index unblocked (MatrixType &mat)
template<typename MatrixType >
static Index blocked (MatrixType &m)
template<typename MatrixType , typename VectorType >
static Index rankUpdate (MatrixType &mat, const VectorType &vec, const RealScalar &sigma)
Member Typedef Documentation
RealScalar
template<typename Scalar > typedef NumTraits<Scalar>::Real Eigen::internal::llt_inplace< Scalar, Lower >::RealScalar
Member Function Documentation
blocked()
template<typename Scalar > template<typename MatrixType > static Index Eigen::internal::llt_inplace< Scalar, Lower >::blocked (MatrixType & m) inline static
{
     eigen_assert(m.rows() == m.cols());
     Index size = m.rows();
     if (size < 32) return unblocked(m);
     Index blockSize = size / 8;
     blockSize = (blockSize / 16) * 16;
     blockSize = (std::min)((std::max)(blockSize, Index(8)), Index(128));
     for (Index k = 0; k < size; k += blockSize) {
       // partition the matrix:
       //       A00 |  -  |  -
       // lu  = A10 | A11 |  -
       //       A20 | A21 | A22
       Index bs = (std::min)(blockSize, size - k);
       Index rs = size - k - bs;
       Block<MatrixType, Dynamic, Dynamic> A11(m, k, k, bs, bs);
       Block<MatrixType, Dynamic, Dynamic> A21(m, k + bs, k, rs, bs);
       Block<MatrixType, Dynamic, Dynamic> A22(m, k + bs, k + bs, rs, rs);
       Index ret;
       if ((ret = unblocked(A11)) >= 0) return k + ret;
       if (rs > 0) A11.adjoint().template triangularView<Upper>().template solveInPlace<OnTheRight>(A21);
       if (rs > 0)
         A22.template selfadjointView<Lower>().rankUpdate(A21,
                                                          typename NumTraits<RealScalar>::Literal(-1));  // bottleneck
     }
     return -1;
   }
References eigen_assert, k, m, max, min, ret, and Eigen::EigenBase< Derived >::size().
rankUpdate()
template<typename Scalar > template<typename MatrixType , typename VectorType > static Index Eigen::internal::llt_inplace< Scalar, Lower >::rankUpdate (MatrixType & mat, const VectorType & vec, const RealScalar & sigma) inline static
{
     return Eigen::internal::llt_rank_update_lower(mat, vec, sigma);
   }
References Eigen::internal::llt_rank_update_lower(), and calibrate::sigma.
unblocked()
template<typename Scalar > template<typename MatrixType > static Index Eigen::internal::llt_inplace< Scalar, Lower >::unblocked (MatrixType & mat) inline static
{
     using std::sqrt;
     eigen_assert(mat.rows() == mat.cols());
     const Index size = mat.rows();
     for (Index k = 0; k < size; ++k) {
       Index rs = size - k - 1;  // remaining size
       Block<MatrixType, Dynamic, 1> A21(mat, k + 1, k, rs, 1);
       Block<MatrixType, 1, Dynamic> A10(mat, k, 0, 1, k);
       Block<MatrixType, Dynamic, Dynamic> A20(mat, k + 1, 0, rs, k);
       RealScalar x = numext::real(mat.coeff(k, k));
       if (k > 0) x -= A10.squaredNorm();
       if (x <= RealScalar(0)) return k;
       mat.coeffRef(k, k) = x = sqrt(x);
       if (k > 0 && rs > 0) A21.noalias() -= A20 * A10.adjoint();
       if (rs > 0) A21 /= x;
     }
     return -1;
   }
References Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::coeff(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::coeffRef(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::cols(), eigen_assert, k, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::rows(), Eigen::EigenBase< Derived >::size(), sqrt(), and plotDoE::x.
The documentation for this struct was generated from the following file:
LLT.h