MercuryDPM: Flag_definition::BottomOfFlag Class Reference
Flag_definition::BottomOfFlag Class Reference
GeomObject that defines the lower boundary of the flag.
Public Member Functions
BottomOfFlag ()
Constructor:
~BottomOfFlag ()
Destructor (empty)
void position (const unsigned &t, const Vector< double > &xi, Vector< double > &r) const
void position (const Vector< double > &xi, Vector< double > &r) const
Current position.
unsigned ngeom_data () const
Number of geometric Data in GeomObject: None.
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual Data * geom_data_pt (const unsigned &j)
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition_dt (const Vector< double > &zeta, const unsigned &j, Vector< double > &drdt)
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
virtual void locate_zeta (const Vector< double > &zeta, GeomObject *&sub_geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
Additional Inherited Members
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Detailed Description
GeomObject that defines the lower boundary of the flag.
Constructor & Destructor Documentation
BottomOfFlag()
Flag_definition::BottomOfFlag::BottomOfFlag () inline
Constructor:
 : GeomObject(1,2) {}
~BottomOfFlag()
Flag_definition::BottomOfFlag::~BottomOfFlag () inline
Destructor (empty)
 {}
Member Function Documentation
ngeom_data()
unsigned Flag_definition::BottomOfFlag::ngeom_data () const inline virtual
Number of geometric Data in GeomObject: None.
Reimplemented from oomph::GeomObject.
 {return 0;}
position() [1/2]
void Flag_definition::BottomOfFlag::position (const unsigned & t, const Vector< double > & xi, Vector< double > & r) const inline virtual
Return the position along the bottom of the flag (xi[0] varies between 0 and Lx)
Reimplemented from oomph::GeomObject.
    {
     // Compute position of fixed point on the cylinder
     Vector<double> point_on_circle(2);
     point_on_circle[0]=Centre_x+Radius*sqrt(1.0-H*H/(4.0*Radius*Radius));
     point_on_circle[1]=Centre_y-H/2.0;
     r[0] = point_on_circle[0]+ xi[0]/L*(lower_tip(Time_pt->time(t))[0]-
                                         point_on_circle[0]);
     r[1] = point_on_circle[1]+ xi[0]/L*(lower_tip(Time_pt->time(t))[1]-
                                         point_on_circle[1])+
      1.0/3.0*sin((r[0]-point_on_circle[0])/
                  (lower_tip(Time_pt->time(t))[0]-
                   point_on_circle[0])*MathematicalConstants::Pi)
      *sin(2.0*MathematicalConstants::Pi*Time_pt->time(t)/Period);
    }
References Flag_definition::Centre_x, Flag_definition::Centre_y, H, L, Flag_definition::lower_tip(), Flag_definition::Period, BiharmonicTestFunctions2::Pi, UniformPSDSelfTest::r, Flag_definition::Radius, sin(), sqrt(), plotPSD::t, oomph::Time::time(), and Flag_definition::Time_pt.
position() [2/2]
void Flag_definition::BottomOfFlag::position (const Vector< double > & xi, Vector< double > & r) const inline virtual
Current position.
Implements oomph::GeomObject.
    {
     return position(0,xi,r);
    }
References UniformPSDSelfTest::r.
The documentation for this class was generated from the following file:
turek_flag_non_fsi.cc