MercuryDPM: ClayParticles.cpp File Reference
ClayParticles.cpp File Reference
#include <iostream>
#include "Species/LinearViscoelasticFrictionChargedBondedSpecies.h"
#include "DPMBase.h"
#include "Walls/InfiniteWall.h"
#include "Logger.h"
Classes
class ChargedBondedParticleUnitTest
In this file, the rolling behaviour of the tangential spring is tested. This is done by placing one normal partilce on top of a fixed partilce and letting graviry roll it over the other particle until it loses contact.
Functions
int main (int argc, char *argv[])
Variables
Logger< Log::ERROR > testLogger ("chargedParticleForceUnitTest")
Function Documentation
main()
int main (int argc , char * argv[])
 {
     //********************************************************Setting Interaction Details**********************************************************
     //Putting details in more user-friendly terms
     //the maximum force exerted, i.e. when particles are in contact
     double maximumForce = 3;
     //the range of the force.
     //Note that the range is measured from the EDGE of the particle!
     double forceRange = 3;
     //based on user inputs, calculated the necessary adhesion stiffness
     double adStiffness = maximumForce / forceRange;
     //based on user inputs, calculated the necessary adhesion stiffness
     double stiffness = 1600 * adStiffness;
     //the strength of the force holding particles together
     //(Affects separation of bonded particles)
     double bondStrength = 333.0;
     ChargedBondedParticleUnitTest chargedParticleForceUnitTestProblem;
     //setting the species of particles
     auto species1 = chargedParticleForceUnitTestProblem.speciesHandler.copyAndAddObject(LinearViscoelasticFrictionChargedBondedSpecies());
     //adding second species to allow for attractive interactions
     auto species2 = chargedParticleForceUnitTestProblem.speciesHandler.copyAndAddObject(LinearViscoelasticFrictionChargedBondedSpecies());
     //setting species for system walls
     auto speciesW = chargedParticleForceUnitTestProblem.speciesHandler.copyAndAddObject(LinearViscoelasticFrictionChargedBondedSpecies());
     //*************************************ASSIGNING PROPERTIES TO PARTICLE SPECIES*****************************************
     //SPECIES 1
     //setting the material properties of the particles
     species1->setDensity(6./constants::pi);
     species1->setStiffness(stiffness);
     species1->setSlidingFrictionCoefficient(1);
     species1->setSlidingStiffness(2.0/7.0*stiffness);
     species1->setRollingFrictionCoefficient(1);
     species1->setRollingStiffness(2.0/5.0*stiffness);
     //setting the interaction force properties
     //setting adhesion stiffness and force max as required to give the
     //user-requested force range.
     species1->setAdhesionForceMax(maximumForce);
     species1->setAdhesionStiffness(adStiffness);
     //Setting the charge of a particle:
     //Positive (1) negative (-1) or neutral (0)
     species1->setCharge(1);
     //Assigning bond properties:
     //The maximum force exerted by the 'bond'
     //(determines the size of the overlap)
     species1->setBondForceMax(bondStrength);
     //the dissipation of the interaction -
     //used to damp out any unphysical oscillations in the contacting pair
     species1->setBondDissipation(0.2);
     //SPECIES 2
     //setting the material properties of the particles
     species2->setDensity(6./constants::pi);
     species2->setStiffness(stiffness);
     species2->setSlidingFrictionCoefficient(1);
     species2->setSlidingStiffness(2.0/7.0*stiffness);
     species2->setRollingFrictionCoefficient(1);
     species2->setRollingStiffness(2.0/5.0*stiffness);
     //setting the interaction force properties
     //setting adhesion stiffness and force max as required to give the
     //user-requested force range
     species2->setAdhesionForceMax(maximumForce);
     species2->setAdhesionStiffness(adStiffness);
     //Setting the charge of a particle:
     //Positive (1) negative (-1) or neutral (0)
     species2->setCharge(-1);
     //Assigning bond properties:
     //The maximum force exerted by the 'bond'
     //(determines the size of the overlap)
     species2->setBondForceMax(bondStrength);
     //the dissipation of the interaction -
     //used to damp out any unphysical oscillations in the contacting pair
     species2->setBondDissipation(0.2);
     //FOR MIXED (SPECIES1-SPECIES2) INTERACTIONS
     //adding also the ability to alter the mixed-particle-interaction properties
     auto species1_2 = dynamic_cast<LinearViscoelasticFrictionChargedBondedMixedSpecies*>(chargedParticleForceUnitTestProblem.speciesHandler.getMixedObject(species1->getIndex(),species2->getIndex()));
     //for now, simply setting mixed object parameters equal to those of species 1
     //setting the material properties to the average values of the 2 particle species undergoing interaction
     species1_2->mixAll(species1,species2);
     species1_2->setSlidingFrictionCoefficient(1);
     species1_2->setSlidingStiffness(2.0/7.0*stiffness);
     species1_2->setRollingFrictionCoefficient(1);
     species1_2->setRollingStiffness(2.0/5.0*stiffness);
     //*************************************ASSIGNING PROPERTIES TO WALL SPECIES*********************************************
     //SPECIES W
     //setting the material properties of the particles
     speciesW->setDensity(6./constants::pi);
     speciesW->setStiffness(stiffness);
     speciesW->setSlidingFrictionCoefficient(1);
     speciesW->setSlidingStiffness(2.0/7.0*stiffness);
     speciesW->setRollingFrictionCoefficient(1);
     speciesW->setRollingStiffness(2.0/5.0*stiffness);
     //setting the interaction force properties
     //setting adhesion stiffness and force max as required to give the
     //user-requested force range
     speciesW->setAdhesionForceMax(maximumForce);
     speciesW->setAdhesionStiffness(adStiffness);
     //Setting the charge of a particle:
     //Positive (1) negative (-1) or neutral (0)
     //charge by default set to zero. However, can be changed, e.g. to induce
     //a field throughout the system and encourage alignment
     speciesW->setCharge(0);
     //Assigning bond properties:
     //The maximum force exerted by the 'bond'
     //(determines the size of the overlap)
     //For walls, setting to zero as no need for bonded interactions here.
     speciesW->setBondForceMax(0);
     //the dissipation of the interaction -
     //used to damp out any unphysical oscillations in the contacting pair
     speciesW->setBondDissipation(0.2);
     //FOR MIXED (PARTICLE-WALL) INTERACTIONS
     //walls and species 1 particles
     auto speciesW_1 = dynamic_cast<LinearViscoelasticFrictionChargedBondedMixedSpecies*>(chargedParticleForceUnitTestProblem.speciesHandler.getMixedObject(speciesW->getIndex(),species1->getIndex()));
     //setting the material properties to the average values of the 2 particle species undergoing interaction
     speciesW_1->mixAll(speciesW,species1);
     speciesW_1->setSlidingFrictionCoefficient(1);
     speciesW_1->setSlidingStiffness(2.0/7.0*stiffness);
     speciesW_1->setRollingFrictionCoefficient(1);
     speciesW_1->setRollingStiffness(2.0/5.0*stiffness);
     //walls and species 1 particles
     auto speciesW_2 = dynamic_cast<LinearViscoelasticFrictionChargedBondedMixedSpecies*>(chargedParticleForceUnitTestProblem.speciesHandler.getMixedObject(speciesW->getIndex(),species2->getIndex()));
     //setting the material properties to the average values of the 2 particle species undergoing interaction
     speciesW_2->mixAll(speciesW,species2);
     speciesW_2->setSlidingFrictionCoefficient(1);
     speciesW_2->setSlidingStiffness(2.0/7.0*stiffness);
     speciesW_2->setRollingFrictionCoefficient(1);
     speciesW_2->setRollingStiffness(2.0/5.0*stiffness);
     //*************************************ASSIGNING GENERAL SIMULATION PARAMETERS******************************************
     //Giving a name for the output file
     chargedParticleForceUnitTestProblem.setName("ClayParticles");
     //setting the time step of the problem
     double radius = 0.25;
     double mass = species1->getMassFromRadius(radius);
     double tc = species1->getCollisionTime(mass);
     chargedParticleForceUnitTestProblem.setTimeStep(0.02*tc);
     //setting gravity to zero to ensure only forces acting are inter-particle forces!
     chargedParticleForceUnitTestProblem.setGravity(Vec3D(0,0,-0));
     //setting the duration of the simulation in "simulation seconds" (determined by
     //the dimensions used in setup)
     chargedParticleForceUnitTestProblem.setTimeMax(30.);
     //setting parameters for visualisation using the xballs software package
     chargedParticleForceUnitTestProblem.setXBallsAdditionalArguments("-cmode 8 -solidf -v0");
     //solving the problem!
     chargedParticleForceUnitTestProblem.solve(argc,argv);
     std::vector<BaseParticle*>::iterator pIt = chargedParticleForceUnitTestProblem.particleHandler.begin();
 }
References BaseHandler< T >::begin(), BaseHandler< T >::copyAndAddObject(), SpeciesHandler::getMixedObject(), MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::mixAll(), DPMBase::particleHandler, constants::pi, UniformPSDSelfTest::radius, DPMBase::setGravity(), DPMBase::setName(), DPMBase::setTimeMax(), DPMBase::setTimeStep(), DPMBase::setXBallsAdditionalArguments(), DPMBase::solve(), and DPMBase::speciesHandler.
Variable Documentation
testLogger
Logger<Log::ERROR> testLogger("chargedParticleForceUnitTest") ("chargedParticleForceUnitTest")