MercuryDPM: oomph::HerschelBulkleyMenDutRegConstitutiveEquation< DIM > Class Template Reference
oomph::HerschelBulkleyMenDutRegConstitutiveEquation< DIM > Class Template Reference
#include <generalised_newtonian_constitutive_models.h>
Public Member Functions
HerschelBulkleyMenDutRegConstitutiveEquation (double *yield_stress_pt, double *flow_index_pt, double *zero_shear_viscosity_pt)
"Exponentially regularised" Herschel Bulkley constitutive equation
double viscosity (const double &second_invariant_of_rate_of_strain_tensor)
Viscosity ratio as a fct of strain rate invariant.
double dviscosity_dinvariant (const double &second_invariant_of_rate_of_strain_tensor)
Deriv of viscosity w.r.t. strain rate invariant.
Public Member Functions inherited from oomph::GeneralisedNewtonianConstitutiveEquation< DIM >
GeneralisedNewtonianConstitutiveEquation ()
Empty constructor.
virtual ~GeneralisedNewtonianConstitutiveEquation ()
Empty virtual destructor.
Private Attributes
double * Yield_stress_pt
yield stress tau_y
double * Flow_index_pt
power law index n
double * Zero_shear_viscosity_pt
the viscosity at zero shear rate
Detailed Description
template<unsigned DIM>
class oomph::HerschelBulkleyMenDutRegConstitutiveEquation< DIM >
A GeneralisedNewtonianConstitutiveEquation class defining a Herschel-Bulkley fluid using Mendes and Dutra's (2004) regularisation
Constructor & Destructor Documentation
HerschelBulkleyMenDutRegConstitutiveEquation()
template<unsigned DIM> oomph::HerschelBulkleyMenDutRegConstitutiveEquation< DIM >::HerschelBulkleyMenDutRegConstitutiveEquation (double * yield_stress_pt, double * flow_index_pt, double * zero_shear_viscosity_pt) inline
"Exponentially regularised" Herschel Bulkley constitutive equation
       : GeneralisedNewtonianConstitutiveEquation<DIM>(),
         Yield_stress_pt(yield_stress_pt),
         Flow_index_pt(flow_index_pt),
         Zero_shear_viscosity_pt(zero_shear_viscosity_pt)
     {
     }
Member Function Documentation
dviscosity_dinvariant()
template<unsigned DIM> double oomph::HerschelBulkleyMenDutRegConstitutiveEquation< DIM >::dviscosity_dinvariant (const double & second_invariant_of_rate_of_strain_tensor) inline virtual
Deriv of viscosity w.r.t. strain rate invariant.
Implements oomph::GeneralisedNewtonianConstitutiveEquation< DIM >.
     {
       // Pre-multiply the second invariant with +/-1 depending on whether it's
       // positive or not
       // Also, because the viscosity is exactly zero at zero invariant,
       // we have to add a small value to it
       double sign = -1.0;
       double eps = 0.0;
       if (second_invariant_of_rate_of_strain_tensor == 0.0)
       {
         eps = 1.0e-30;
         sign = 1.0;
       }
       else if (second_invariant_of_rate_of_strain_tensor > 0.0)
       {
         sign = 1.0;
       }
       // Calculate the square root of the absolute value of the
       // second invariant of the rate of strain tensor
       double measure_of_rate_of_strain =
         sqrt(sign * (second_invariant_of_rate_of_strain_tensor + eps));
       return (1.0 - exp(-(*Zero_shear_viscosity_pt) * 2.0 *
                         measure_of_rate_of_strain / (*Yield_stress_pt))) *
                (sign * pow(2.0, (*Flow_index_pt) - 2.0) *
                   ((*Flow_index_pt) - 1.0) *
                   pow(sign * (second_invariant_of_rate_of_strain_tensor + eps),
                       ((*Flow_index_pt) - 1.0) / 2.0 - 1.0) -
                 sign * (*Yield_stress_pt) /
                   (4.0 *
                    pow(sign * (second_invariant_of_rate_of_strain_tensor + eps),
                        3.0 / 2.0))) +
              sign *
                (((*Zero_shear_viscosity_pt) *
                  exp(-(*Zero_shear_viscosity_pt) * 2.0 *
                      measure_of_rate_of_strain / (*Yield_stress_pt))) /
                 ((*Yield_stress_pt) * measure_of_rate_of_strain)) *
                (pow(2.0, (*Flow_index_pt) - 1.0) *
                   pow(sign * (second_invariant_of_rate_of_strain_tensor + eps),
                       ((*Flow_index_pt) - 1.0) / 2.0) +
                 (*Yield_stress_pt) / (2.0 * measure_of_rate_of_strain));
     }
References CRBond_Bessel::eps, Eigen::bfloat16_impl::exp(), oomph::HerschelBulkleyMenDutRegConstitutiveEquation< DIM >::Flow_index_pt, Eigen::bfloat16_impl::pow(), SYCL::sign(), sqrt(), oomph::HerschelBulkleyMenDutRegConstitutiveEquation< DIM >::Yield_stress_pt, and oomph::HerschelBulkleyMenDutRegConstitutiveEquation< DIM >::Zero_shear_viscosity_pt.
viscosity()
template<unsigned DIM> double oomph::HerschelBulkleyMenDutRegConstitutiveEquation< DIM >::viscosity (const double & second_invariant_of_rate_of_strain_tensor) inline virtual
Viscosity ratio as a fct of strain rate invariant.
Implements oomph::GeneralisedNewtonianConstitutiveEquation< DIM >.
     {
       // Pre-multiply the second invariant with +/-1 depending on whether it's
       // positive or not
       // Also, because the viscosity is exactly zero at zero invariant,
       // we have to add a small value to it
       double sign = -1.0;
       double eps = 0.0;
       if (second_invariant_of_rate_of_strain_tensor == 0.0)
       {
         eps = 1.0e-30;
         sign = 1.0;
       }
       else if (second_invariant_of_rate_of_strain_tensor > 0.0)
       {
         sign = 1.0;
       }
       // Calculate the square root of the absolute value of the
       // second invariant of the rate of strain tensor
       double measure_of_rate_of_strain =
         sqrt(sign * (second_invariant_of_rate_of_strain_tensor + eps));
       return (1.0 - exp(-(*Zero_shear_viscosity_pt) * 2.0 *
                         measure_of_rate_of_strain / (*Yield_stress_pt))) *
              ((*Yield_stress_pt) / (2.0 * measure_of_rate_of_strain) +
               pow((2.0 * measure_of_rate_of_strain), *Flow_index_pt - 1.0));
     }
References CRBond_Bessel::eps, Eigen::bfloat16_impl::exp(), oomph::HerschelBulkleyMenDutRegConstitutiveEquation< DIM >::Flow_index_pt, Eigen::bfloat16_impl::pow(), SYCL::sign(), sqrt(), oomph::HerschelBulkleyMenDutRegConstitutiveEquation< DIM >::Yield_stress_pt, and oomph::HerschelBulkleyMenDutRegConstitutiveEquation< DIM >::Zero_shear_viscosity_pt.
Member Data Documentation
Flow_index_pt
template<unsigned DIM> double* oomph::HerschelBulkleyMenDutRegConstitutiveEquation< DIM >::Flow_index_pt private
power law index n
Referenced by oomph::HerschelBulkleyMenDutRegConstitutiveEquation< DIM >::dviscosity_dinvariant(), and oomph::HerschelBulkleyMenDutRegConstitutiveEquation< DIM >::viscosity().
Yield_stress_pt
template<unsigned DIM> double* oomph::HerschelBulkleyMenDutRegConstitutiveEquation< DIM >::Yield_stress_pt private
yield stress tau_y
Referenced by oomph::HerschelBulkleyMenDutRegConstitutiveEquation< DIM >::dviscosity_dinvariant(), and oomph::HerschelBulkleyMenDutRegConstitutiveEquation< DIM >::viscosity().
Zero_shear_viscosity_pt
template<unsigned DIM> double* oomph::HerschelBulkleyMenDutRegConstitutiveEquation< DIM >::Zero_shear_viscosity_pt private
the viscosity at zero shear rate
Referenced by oomph::HerschelBulkleyMenDutRegConstitutiveEquation< DIM >::dviscosity_dinvariant(), and oomph::HerschelBulkleyMenDutRegConstitutiveEquation< DIM >::viscosity().
The documentation for this class was generated from the following file:
generalised_newtonian_constitutive_models.h