MercuryDPM: Eigen::NumTraits< Eigen::bfloat16 > Struct Reference
Eigen::NumTraits< Eigen::bfloat16 > Struct Reference
#include <BFloat16.h>
Public Types
enum { IsSigned = true , IsInteger = false , IsComplex = false , RequireInitialization = false }
Public Types inherited from Eigen::GenericNumTraits< Eigen::bfloat16 >
enum
typedef Eigen::bfloat16 Real
Static Public Member Functions
EIGEN_DEVICE_FUNC static EIGEN_CONSTEXPR EIGEN_STRONG_INLINE Eigen::bfloat16 epsilon ()
EIGEN_DEVICE_FUNC static EIGEN_CONSTEXPR EIGEN_STRONG_INLINE Eigen::bfloat16 dummy_precision ()
EIGEN_DEVICE_FUNC static EIGEN_CONSTEXPR EIGEN_STRONG_INLINE Eigen::bfloat16 highest ()
EIGEN_DEVICE_FUNC static EIGEN_CONSTEXPR EIGEN_STRONG_INLINE Eigen::bfloat16 lowest ()
EIGEN_DEVICE_FUNC static EIGEN_CONSTEXPR EIGEN_STRONG_INLINE Eigen::bfloat16 infinity ()
EIGEN_DEVICE_FUNC static EIGEN_CONSTEXPR EIGEN_STRONG_INLINE Eigen::bfloat16 quiet_NaN ()
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
IsSigned
IsInteger
IsComplex
RequireInitialization
 { IsSigned = true, IsInteger = false, IsComplex = false, RequireInitialization = false };
Member Function Documentation
dummy_precision()
EIGEN_DEVICE_FUNC static EIGEN_CONSTEXPR EIGEN_STRONG_INLINE Eigen::bfloat16 Eigen::NumTraits< Eigen::bfloat16 >::dummy_precision () inline static
{
     return bfloat16_impl::raw_uint16_to_bfloat16(0x3D4D);  // bfloat16(5e-2f);
   }
References Eigen::bfloat16_impl::raw_uint16_to_bfloat16().
epsilon()
EIGEN_DEVICE_FUNC static EIGEN_CONSTEXPR EIGEN_STRONG_INLINE Eigen::bfloat16 Eigen::NumTraits< Eigen::bfloat16 >::epsilon () inline static
{
     return bfloat16_impl::raw_uint16_to_bfloat16(0x3c00);
   }
References Eigen::bfloat16_impl::raw_uint16_to_bfloat16().
highest()
EIGEN_DEVICE_FUNC static EIGEN_CONSTEXPR EIGEN_STRONG_INLINE Eigen::bfloat16 Eigen::NumTraits< Eigen::bfloat16 >::highest () inline static
{
     return bfloat16_impl::raw_uint16_to_bfloat16(0x7F7F);
   }
References Eigen::bfloat16_impl::raw_uint16_to_bfloat16().
infinity()
EIGEN_DEVICE_FUNC static EIGEN_CONSTEXPR EIGEN_STRONG_INLINE Eigen::bfloat16 Eigen::NumTraits< Eigen::bfloat16 >::infinity () inline static
{
     return bfloat16_impl::raw_uint16_to_bfloat16(0x7f80);
   }
References Eigen::bfloat16_impl::raw_uint16_to_bfloat16().
lowest()
EIGEN_DEVICE_FUNC static EIGEN_CONSTEXPR EIGEN_STRONG_INLINE Eigen::bfloat16 Eigen::NumTraits< Eigen::bfloat16 >::lowest () inline static
{
     return bfloat16_impl::raw_uint16_to_bfloat16(0xFF7F);
   }
References Eigen::bfloat16_impl::raw_uint16_to_bfloat16().
quiet_NaN()
EIGEN_DEVICE_FUNC static EIGEN_CONSTEXPR EIGEN_STRONG_INLINE Eigen::bfloat16 Eigen::NumTraits< Eigen::bfloat16 >::quiet_NaN () inline static
{
     return bfloat16_impl::raw_uint16_to_bfloat16(0x7fc0);
   }
References Eigen::bfloat16_impl::raw_uint16_to_bfloat16().
The documentation for this struct was generated from the following file:
BFloat16.h