MercuryDPM: fsi_channel_with_leaflet.cc File Reference
interaction/fsi_channel_with_leaflet/fsi_channel_with_leaflet.cc File Reference
#include "generic.h"
#include "beam.h"
#include "navier_stokes.h"
#include "multi_physics.h"
#include "meshes/channel_with_leaflet_mesh.h"
#include "meshes/one_d_lagrangian_mesh.h"
Classes
class UndeformedLeaflet
GeomObject: Undeformed straight, vertical leaflet.
class FSIChannelWithLeafletProblem< ELEMENT >
FSI leaflet in channel.
Namespaces
Global_Physical_Variables
Global variables.
Functions
double Global_Physical_Variables::flux (const double &t)
int main (int argc, char *argv[])
Variables
double Global_Physical_Variables::Period =2.0
Period for fluctuations in flux.
double Global_Physical_Variables::Min_flux =1.0
Min. flux.
double Global_Physical_Variables::Max_flux =2.0
Max. flux.
Function Documentation
main()
int main (int argc , char * argv[])
Driver code – pass a command line argument if you want to run the code in validation mode where it only performs a few steps
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  //Parameters for the leaflet: x-position of root and height
  double x_0 = 1.0;
  double hleaflet=0.5;
  // Number of elements in various regions of mesh
  unsigned nleft=6;
  unsigned nright=18;
  unsigned ny1=3;
  unsigned ny2=3;
  // Dimensions of fluid mesh: length to the left and right of leaflet
  // and total height
  double lleft =1.0;
  double lright=3.0;
  double htot=1.0;
  //Build the problem
  FSIChannelWithLeafletProblem<
   AlgebraicElement<RefineableQTaylorHoodElement<2> > >
   problem(lleft,lright,hleaflet,
           htot,nleft,nright,ny1,ny2,x_0);
  // Set up doc info
  DocInfo doc_info;
  doc_info.set_directory("RESLT");
  // Trace file
  ofstream trace;
  char filename[100];
  sprintf(filename,"%s/trace.dat",doc_info.directory().c_str());
  trace.open(filename);
  // Number of timesteps (reduced for validation)
  unsigned nstep=200;
  if (CommandLineArgs::Argc>1)
   {
    nstep=2;
   }
  //Timestep:
  double dt=0.05;
  // Initialise timestep
  problem.initialise_dt(dt);
  // Doc initial guess for steady solve
  problem.doc_solution(doc_info,trace);
  doc_info.number()++;
  // Initial loop to increment the Reynolds number in sequence of steady solves
  //---------------------------------------------------------------------------
  unsigned n_increment=4;
  // Just to one step for validation run
  if (CommandLineArgs::Argc>1)
   {
    n_increment=1;
   }
  // Set max. number of adaptations
  unsigned max_adapt=3;
  Global_Physical_Variables::Re=0.0;
  for (unsigned i=0;i<n_increment;i++)
   {
    // Increase Re and ReSt (for St=1)
    Global_Physical_Variables::Re+=50.0;
    Global_Physical_Variables::ReSt=Global_Physical_Variables::Re;
    // Solve the steady problem
    std::cout << "Computing a steady solution for Re="
              <<  Global_Physical_Variables::Re << std::endl;
    problem.steady_newton_solve(max_adapt);
    problem.doc_solution(doc_info,trace);
    doc_info.number()++;
   } // reached final Reynolds number
  // Proper time-dependent run
  //--------------------------
  // Limit the number of adaptations during unsteady run to one per timestep
  max_adapt=1;
  // Don't re-set the initial conditions when adapting the mesh
  bool first = false;
  // Timestepping loop
  for (unsigned istep=0;istep<nstep;istep++)
   {
    // Solve the problem
    problem.unsteady_newton_solve(dt,max_adapt,first);
    // Output the solution
    problem.doc_solution(doc_info,trace);
    // Step number
    doc_info.number()++;
   }
 }//end of main
References oomph::CommandLineArgs::Argc, oomph::DocInfo::directory(), MergeRestartFiles::filename, i, oomph::DocInfo::number(), problem, Global_Physical_Variables::Re, Global_Physical_Variables::ReSt, oomph::DocInfo::set_directory(), and Flag_definition::setup().