MercuryDPM: Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheLeft, Mode, Conjugate, TriStorageOrder, ColMajor, OtherInnerStride > Struct Template Reference
Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheLeft, Mode, Conjugate, TriStorageOrder, ColMajor, OtherInnerStride > Struct Template Reference
#include <TriangularSolverMatrix.h>
Static Public Member Functions
static EIGEN_DONT_INLINE void run (Index size, Index otherSize, const Scalar *_tri, Index triStride, Scalar *_other, Index otherIncr, Index otherStride, level3_blocking< Scalar, Scalar > &blocking)
Member Function Documentation
run()
template<typename Scalar , typename Index , int Mode, bool Conjugate, int TriStorageOrder, int OtherInnerStride> EIGEN_DONT_INLINE void Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheLeft, Mode, Conjugate, TriStorageOrder, ColMajor, OtherInnerStride >::run (Index size, Index otherSize, const Scalar * _tri, Index triStride, Scalar * _other, Index otherIncr, Index otherStride, level3_blocking< Scalar, Scalar > & blocking) static
{
   Index cols = otherSize;
   std::ptrdiff_t l1, l2, l3;
   manage_caching_sizes(GetAction, &l1, &l2, &l3);
 #if defined(EIGEN_VECTORIZE_AVX512) && EIGEN_USE_AVX512_TRSM_L_KERNELS && EIGEN_ENABLE_AVX512_NOCOPY_TRSM_L_CUTOFFS
   EIGEN_IF_CONSTEXPR(
       (OtherInnerStride == 1 && (std::is_same<Scalar, float>::value || std::is_same<Scalar, double>::value))) {
     // Very rough cutoffs to determine when to call trsm w/o packing
     // For small problem sizes trsmKernel compiled with clang is generally faster.
     // TODO: Investigate better heuristics for cutoffs.
     double L2Cap = 0.5;  // 50% of L2 size
     if (size < avx512_trsm_cutoff<Scalar>(l2, cols, L2Cap)) {
       trsmKernelL<Scalar, Index, Mode, Conjugate, TriStorageOrder, 1, /*Specialized=*/true>::kernel(
           size, cols, _tri, triStride, _other, 1, otherStride);
       return;
     }
   }
 #endif
   typedef const_blas_data_mapper<Scalar, Index, TriStorageOrder> TriMapper;
   typedef blas_data_mapper<Scalar, Index, ColMajor, Unaligned, OtherInnerStride> OtherMapper;
   TriMapper tri(_tri, triStride);
   OtherMapper other(_other, otherStride, otherIncr);
   typedef gebp_traits<Scalar, Scalar> Traits;
   enum { SmallPanelWidth = plain_enum_max(Traits::mr, Traits::nr), IsLower = (Mode & Lower) == Lower };
   Index kc = blocking.kc();                    // cache block size along the K direction
   Index mc = (std::min)(size, blocking.mc());  // cache block size along the M direction
   std::size_t sizeA = kc * mc;
   std::size_t sizeB = kc * cols;
   ei_declare_aligned_stack_constructed_variable(Scalar, blockA, sizeA, blocking.blockA());
   ei_declare_aligned_stack_constructed_variable(Scalar, blockB, sizeB, blocking.blockB());
   gebp_kernel<Scalar, Scalar, Index, OtherMapper, Traits::mr, Traits::nr, Conjugate, false> gebp_kernel;
   gemm_pack_lhs<Scalar, Index, TriMapper, Traits::mr, Traits::LhsProgress, typename Traits::LhsPacket4Packing,
                 TriStorageOrder>
       pack_lhs;
   gemm_pack_rhs<Scalar, Index, OtherMapper, Traits::nr, ColMajor, false, true> pack_rhs;
   // the goal here is to subdivise the Rhs panels such that we keep some cache
   // coherence when accessing the rhs elements
   Index subcols = cols > 0 ? l2 / (4 * sizeof(Scalar) * std::max<Index>(otherStride, size)) : 0;
   subcols = std::max<Index>((subcols / Traits::nr) * Traits::nr, Traits::nr);
   for (Index k2 = IsLower ? 0 : size; IsLower ? k2 < size : k2 > 0; IsLower ? k2 += kc : k2 -= kc) {
     const Index actual_kc = (std::min)(IsLower ? size - k2 : k2, kc);
     // We have selected and packed a big horizontal panel R1 of rhs. Let B be the packed copy of this panel,
     // and R2 the remaining part of rhs. The corresponding vertical panel of lhs is split into
     // A11 (the triangular part) and A21 the remaining rectangular part.
     // Then the high level algorithm is:
     //  - B = R1                    => general block copy (done during the next step)
     //  - R1 = A11^-1 B             => tricky part
     //  - update B from the new R1  => actually this has to be performed continuously during the above step
     //  - R2 -= A21 * B             => GEPP
     // The tricky part: compute R1 = A11^-1 B while updating B from R1
     // The idea is to split A11 into multiple small vertical panels.
     // Each panel can be split into a small triangular part T1k which is processed without optimization,
     // and the remaining small part T2k which is processed using gebp with appropriate block strides
     for (Index j2 = 0; j2 < cols; j2 += subcols) {
       Index actual_cols = (std::min)(cols - j2, subcols);
       // for each small vertical panels [T1k^T, T2k^T]^T of lhs
       for (Index k1 = 0; k1 < actual_kc; k1 += SmallPanelWidth) {
         Index actualPanelWidth = std::min<Index>(actual_kc - k1, SmallPanelWidth);
         // tr solve
         {
           Index i = IsLower ? k2 + k1 : k2 - k1;
 #if defined(EIGEN_VECTORIZE_AVX512) && EIGEN_USE_AVX512_TRSM_L_KERNELS
           EIGEN_IF_CONSTEXPR(
               (OtherInnerStride == 1 && (std::is_same<Scalar, float>::value || std::is_same<Scalar, double>::value))) {
             i = IsLower ? k2 + k1 : k2 - k1 - actualPanelWidth;
           }
 #endif
           trsmKernelL<Scalar, Index, Mode, Conjugate, TriStorageOrder, OtherInnerStride, /*Specialized=*/true>::kernel(
               actualPanelWidth, actual_cols, _tri + i + (i)*triStride, triStride,
               _other + i * OtherInnerStride + j2 * otherStride, otherIncr, otherStride);
         }
         Index lengthTarget = actual_kc - k1 - actualPanelWidth;
         Index startBlock = IsLower ? k2 + k1 : k2 - k1 - actualPanelWidth;
         Index blockBOffset = IsLower ? k1 : lengthTarget;
         // update the respective rows of B from other
         pack_rhs(blockB + actual_kc * j2, other.getSubMapper(startBlock, j2), actualPanelWidth, actual_cols, actual_kc,
                  blockBOffset);
         // GEBP
         if (lengthTarget > 0) {
           Index startTarget = IsLower ? k2 + k1 + actualPanelWidth : k2 - actual_kc;
           pack_lhs(blockA, tri.getSubMapper(startTarget, startBlock), actualPanelWidth, lengthTarget);
           gebp_kernel(other.getSubMapper(startTarget, j2), blockA, blockB + actual_kc * j2, lengthTarget,
                       actualPanelWidth, actual_cols, Scalar(-1), actualPanelWidth, actual_kc, 0, blockBOffset);
         }
       }
     }
     // R2 -= A21 * B => GEPP
     {
       Index start = IsLower ? k2 + kc : 0;
       Index end = IsLower ? size : k2 - kc;
       for (Index i2 = start; i2 < end; i2 += mc) {
         const Index actual_mc = (std::min)(mc, end - i2);
         if (actual_mc > 0) {
           pack_lhs(blockA, tri.getSubMapper(i2, IsLower ? k2 : k2 - kc), actual_kc, actual_mc);
           gebp_kernel(other.getSubMapper(i2, 0), blockA, blockB, actual_mc, actual_kc, cols, Scalar(-1), -1, -1, 0, 0);
         }
       }
     }
   }
 }
References Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::blockA(), Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::blockB(), cols, ei_declare_aligned_stack_constructed_variable, EIGEN_IF_CONSTEXPR, Eigen::placeholders::end, Eigen::GetAction, i, Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::kc(), Eigen::Lower, Eigen::internal::manage_caching_sizes(), Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::mc(), min, Eigen::internal::plain_enum_max(), size, oomph::CumulativeTimings::start(), tri, and Eigen::value.
The documentation for this struct was generated from the following file:
TriangularSolverMatrix.h