MercuryDPM: two_d_poisson_flux_bc.cc File Reference
two_d_poisson_flux_bc.cc File Reference
#include "generic.h"
#include "poisson.h"
#include "meshes/simple_rectangular_quadmesh.h"
Classes
class FluxPoissonProblem< ELEMENT >
Namespaces
TanhSolnForPoisson
Namespace for exact solution for Poisson equation with "sharp step".
Functions
void TanhSolnForPoisson::get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void TanhSolnForPoisson::source_function (const Vector< double > &x, double &source)
Source function required to make the solution above an exact solution.
void TanhSolnForPoisson::prescribed_flux_on_fixed_x_boundary (const Vector< double > &x, double &flux)
Flux required by the exact solution on a boundary on which x is fixed.
int main ()
Function Documentation
main()
int main ()
Demonstrate how to solve 2D Poisson problem with flux boundary conditions
 {
  //Set up the problem
  //------------------
  //Set up the problem with 2D nine-node elements from the
  //QPoissonElement family. Pass pointer to source function.
  FluxPoissonProblem<QPoissonElement<2,3> >
   problem(&TanhSolnForPoisson::source_function);
  // Create label for output
  //------------------------
  DocInfo doc_info;
  // Set output directory
  doc_info.set_directory("RESLT");
  // Step number
  doc_info.number()=0;
  // Check that we're ready to go:
  //----------------------------
  cout << "\n\n\nProblem self-test ";
  if (problem.self_test()==0)
   {
    cout << "passed: Problem can be solved." << std::endl;
   }
  else
   {
    throw OomphLibError("Self test failed",
                        OOMPH_CURRENT_FUNCTION,
                        OOMPH_EXCEPTION_LOCATION);
   }
  // Set the orientation of the "step" to 45 degrees
  TanhSolnForPoisson::TanPhi=1.0;
  // Initial value for the steepness of the "step"
  TanhSolnForPoisson::Alpha=1.0;
  // Do a couple of solutions for different forcing functions
  //---------------------------------------------------------
  unsigned nstep=4;
  for (unsigned istep=0;istep<nstep;istep++)
   {
    // Increase the steepness of the step:
    TanhSolnForPoisson::Alpha+=2.0;
    cout << "\n\nSolving for TanhSolnForPoisson::Alpha="
         << TanhSolnForPoisson::Alpha << std::endl << std::endl;
    // Solve the problem
    problem.newton_solve();
    //Output solution
    problem.doc_solution(doc_info);
    //Increment counter for solutions
    doc_info.number()++;
   }
 } //end of main
References TanhSolnForPoisson::Alpha, oomph::DocInfo::number(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, problem, oomph::DocInfo::set_directory(), TanhSolnForPoisson::source_function(), and TanhSolnForPoisson::TanPhi.