MercuryDPM: cxx11_tensor_random.cpp File Reference
cxx11_tensor_random.cpp File Reference
#include "main.h"
#include <Eigen/CXX11/Tensor>
Classes
struct MyGenerator
Functions
template<typename Scalar >
static void test_default ()
template<typename Scalar >
static void test_normal ()
static void test_custom ()
EIGEN_DECLARE_TEST (cxx11_tensor_random)
Function Documentation
EIGEN_DECLARE_TEST()
EIGEN_DECLARE_TEST (cxx11_tensor_random)
{
   CALL_SUBTEST((test_default<float>()));
   CALL_SUBTEST((test_normal<float>()));
   CALL_SUBTEST((test_default<double>()));
   CALL_SUBTEST((test_normal<double>()));
   CALL_SUBTEST((test_default<Eigen::half>()));
   CALL_SUBTEST((test_normal<Eigen::half>()));
   CALL_SUBTEST((test_default<Eigen::bfloat16>()));
   CALL_SUBTEST((test_normal<Eigen::bfloat16>()));
   CALL_SUBTEST(test_custom());
 }
References CALL_SUBTEST, and test_custom().
test_custom()
static void test_custom () static
{
   Tensor<int, 1> vec(6);
   vec.setRandom<MyGenerator>();
   for (int i = 0; i < 6; ++i) {
     VERIFY_IS_EQUAL(vec(i), 3 * i);
   }
 }
References i, Eigen::TensorBase< Derived, AccessLevel >::setRandom(), and VERIFY_IS_EQUAL.
Referenced by EIGEN_DECLARE_TEST().
test_default()
template<typename Scalar > static void test_default () static
{
   Tensor<Scalar, 1> vec(6);
   vec.setRandom();
   // Fixme: we should check that the generated numbers follow a uniform
   // distribution instead.
   for (int i = 1; i < 6; ++i) {
     VERIFY_IS_NOT_EQUAL(vec(i), vec(i - 1));
   }
 }
References i, Eigen::TensorBase< Derived, AccessLevel >::setRandom(), and VERIFY_IS_NOT_EQUAL.
test_normal()
template<typename Scalar > static void test_normal () static
{
   Tensor<Scalar, 1> vec(6);
   vec.template setRandom<Eigen::internal::NormalRandomGenerator<Scalar>>();
   // Fixme: we should check that the generated numbers follow a gaussian
   // distribution instead.
   for (int i = 1; i < 6; ++i) {
     VERIFY_IS_NOT_EQUAL(vec(i), vec(i - 1));
   }
 }
References i, and VERIFY_IS_NOT_EQUAL.