MercuryDPM: extrude_with_macro_element_representation.cc File Reference
extrude_with_macro_element_representation.cc File Reference
#include "generic.h"
#include "poisson.h"
#include "meshes/rectangle_with_moving_cylinder_mesh.h"
#include "meshes/extruded_cube_mesh_from_quad_mesh_with_macro_elements.h"
Classes
class OscillatingCylinder
Oscillating cylinder class.
class ExtrudedMovingCylinderProblem< TWO_D_ELEMENT, THREE_D_ELEMENT >
Namespaces
TanhSolnForPoisson
Namespace for exact solution for Poisson equation with "sharp step".
GlobalParameters
Global parameters.
Functions
void TanhSolnForPoisson::get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void TanhSolnForPoisson::get_exact_u (const Vector< double > &x, double &u)
Exact solution as a scalar.
void TanhSolnForPoisson::get_source (const Vector< double > &x, double &source)
Source function to make it an exact solution.
void GlobalParameters::update_parameters ()
Update parameters.
int main (int argc, char **argv)
Constructor.
Variables
double TanhSolnForPoisson::Alpha =1.0
Parameter for steepness of step.
double TanhSolnForPoisson::N_x =-1.0
Orientation of non-normalised x-component of vector in plane direction.
double TanhSolnForPoisson::N_y =-1.0
Orientation of non-normalised y-component of vector in plane direction.
double TanhSolnForPoisson::N_z =1.0
Orientation of non-normalised z-component of vector in plane direction.
double TanhSolnForPoisson::X_0 =0.0
Orientation (x-coordinate of step plane)
double TanhSolnForPoisson::Y_0 =0.0
Orientation (y-coordinate of step plane)
double TanhSolnForPoisson::Z_0 =0.0
Orientation (z-coordinate of step plane)
OscillatingCylinder * GlobalParameters::Cylinder_pt =0
---------------------------------—TIME-INTEGRATION PARAMETERS---—
double GlobalParameters::Radius =0.5
Radius of the cylinder.
double GlobalParameters::Amplitude =0.50
Amplitude of the cylinder motion.
double GlobalParameters::Length_of_box =10.0
----------------------—Cylinder Properties----------------------—
double GlobalParameters::Length_z =1.0
The length of the extruded mesh in the z-direction.
unsigned GlobalParameters::N_element_z =10
Number of elements in the z-direction (in the extruded mesh)
unsigned GlobalParameters::N_uniform_refinement_before_solve =2
Number of uniform refinements before any solve.
double GlobalParameters::Annular_region_radius =1.0
The radius of the annular region surrounding the cylinder.
Function Documentation
main()
int main (int argc , char ** argv)
Constructor.
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Number of uniform refinements before any solve
 {
 #ifdef OOMPH_HAS_MPI
   // Initialise MPI
   MPI_Helpers::init(argc,argv);
   // Switch off output modifier
   oomph_info.output_modifier_pt()=&default_output_modifier;
   // Switch off oomph_info output for all processors but rank 0
   if (MPI_Helpers::communicator_pt()->my_rank()!=0)
   {
     oomph_info.stream_pt()=&oomph_nullstream;
     OomphLibWarning::set_stream_pt(&oomph_nullstream);
     OomphLibError::set_stream_pt(&oomph_nullstream);
   }
   else
   {
     oomph_info << "\n=====================================================\n"
                << "Number of processors: "
                << MPI_Helpers::communicator_pt()->nproc()
                << "\n=====================================================\n"
                << std::endl;
   }
 #endif
   // Start the clock
   double timer_s=TimingHelpers::timer();
   // Set the documentation directory
   GlobalParameters::Doc_info.set_directory("RESLT");
   // Typedef the element type
   typedef RefineableQPoissonElement<2,2> ELEMENT;
   // Typedef the extruded element type
   typedef RefineableQPoissonElement<3,2> EXTRUDED_ELEMENT;
   // Create Problem
   ExtrudedMovingCylinderProblem<ELEMENT,EXTRUDED_ELEMENT> problem(
     TanhSolnForPoisson::get_source);
   // Document the mesh
   problem.newton_solve();
   // Document the mesh
   problem.doc_solution();
   // Maximum number of adaptations
   unsigned max_adapt=2;
   for (unsigned i=0; i<max_adapt; i++)
   {
     // Document the mesh
     problem.adapt();
     // Document the mesh
     problem.newton_solve();
     // Document the mesh
     problem.doc_solution();
   }
   // Tell the user we're done
   oomph_info << "\nSimulation complete!\nTotal time for simulation [sec]: "
              << TimingHelpers::timer()-timer_s << "\n" << std::endl;
 }
References oomph::default_output_modifier, GlobalParameters::Doc_info, TanhSolnForPoisson::get_source(), i, oomph::oomph_info, oomph::oomph_nullstream, oomph::OomphInfo::output_modifier_pt(), problem, oomph::DocInfo::set_directory(), and oomph::OomphInfo::stream_pt().