MercuryDPM: oomph::ElementElementMortaringElement Class Reference
oomph::ElementElementMortaringElement Class Reference
#include <element_element_constraint_elements.h>
Public Member Functions
ElementElementMortaringElement (FiniteElement *elem0_pt, FiniteElement *elem1_pt, Vector< double > &s0, Vector< double > &s1, const Vector< unsigned > &mortared_dimensions={0, 1, 2})
Public Member Functions inherited from oomph::ElementElementConstraintElement
ElementElementConstraintElement (Vector< FiniteElement * > elem_pt)
Public Member Functions inherited from oomph::ConstraintElement
ConstraintElement (Vector< Data * > &data_pt)
ConstraintElement (Vector< Data * > data_pt)
virtual void fill_in_contribution_to_residuals (Vector< double > &residuals)
virtual void construct_lagrange_multipliers ()
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual unsigned self_test ()
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Protected Member Functions
void evaluate_constraint_functions (Vector< double > &error)
Protected Member Functions inherited from oomph::ElementElementConstraintElement
FiniteElement * elem_pt (const unsigned &i)
Data * node_pt (const unsigned &e, const unsigned &i)
Data * extern_data_pt (const unsigned &e, const unsigned &i)
Data * intern_data_pt (const unsigned &e, const unsigned &i)
const int node_eqn (const unsigned &e, const unsigned &i, const unsigned &j)
const int extern_data_eqn (const unsigned &e, const unsigned &i, const unsigned &j)
const int intern_data_eqn (const unsigned &e, const unsigned &i, const unsigned &j)
Protected Member Functions inherited from oomph::ConstraintElement
Vector< unsigned > get_constrained_data_local_index ()
unsigned get_lagrange_multiplier_index ()
Data * lagrange_multiplier ()
const int lagrange_eqn (const unsigned &i)
Data * ext_data_pt (const unsigned &i)
const int ext_eqn (const unsigned &i, const unsigned &j)
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Private Attributes
Vector< Vector< double > > Local_Coord
Vector< unsigned > Mortared_Dimensions
Additional Inherited Members
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Protected Attributes inherited from oomph::ConstraintElement
Vector< unsigned > Constrained_Data_Local_Index
unsigned Num_Constrained_Data
unsigned Lagrange_Multiplier_Index
unsigned Num_Constraints
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Constructor & Destructor Documentation
ElementElementMortaringElement()
oomph::ElementElementMortaringElement::ElementElementMortaringElement (FiniteElement * elem0_pt, FiniteElement * elem1_pt, Vector< double > & s0, Vector< double > & s1, const Vector< unsigned > & mortared_dimensions = {0,1,2}) inline
                                                                                {0,1,2}) :
          ConstraintElement(ElementElementConstraintElementHelper::element_pt_to_data_pt({elem0_pt, elem1_pt})),
          ElementElementConstraintElement({elem0_pt, elem1_pt}),
          Local_Coord({s0, s1}),
          Mortared_Dimensions(mortared_dimensions)
   {
    if(elem0_pt->dim() != elem1_pt->dim())
    {
     // Throw an error
     throw OomphLibError("The elements do not have the same dimension",
                         OOMPH_CURRENT_FUNCTION,
                         OOMPH_EXCEPTION_LOCATION);
    }
    // There are never more than 3 dimensions
    if(mortared_dimensions.size()>elem0_pt->dim())
    {
     // Throw an error
     throw OomphLibError("Specified more than " + std::to_string(elem0_pt->dim()) + " dimensions to pin",
                         OOMPH_CURRENT_FUNCTION,
                         OOMPH_EXCEPTION_LOCATION);
    }
    construct_lagrange_multipliers();
   }
Member Function Documentation
evaluate_constraint_functions()
void oomph::ElementElementMortaringElement::evaluate_constraint_functions (Vector< double > & error) protected virtual
Reimplemented from oomph::ConstraintElement.
  {
   error.resize(Mortared_Dimensions.size());
   const unsigned dim = elem_pt(0)->dim();
   Vector<double> x0(dim);
   elem_pt(0)->interpolated_x(Local_Coord[0], x0);
   Vector<double> x1(dim);
   elem_pt(1)->interpolated_x(Local_Coord[1], x1);
   for(unsigned e : Mortared_Dimensions)
   {
    error[e] = x0[e] - x1[e];
   }
  }
References oomph::FiniteElement::dim(), e(), oomph::ElementElementConstraintElement::elem_pt(), calibrate::error, oomph::FiniteElement::interpolated_x(), Local_Coord, Mortared_Dimensions, Global::x0, and Global_parameters::x1().
Member Data Documentation
Local_Coord
Vector<Vector<double> > oomph::ElementElementMortaringElement::Local_Coord private
Referenced by evaluate_constraint_functions().
Mortared_Dimensions
Vector<unsigned> oomph::ElementElementMortaringElement::Mortared_Dimensions private
Referenced by evaluate_constraint_functions().
The documentation for this class was generated from the following files:
element_element_constraint_elements.h
element_element_constraint_elements.cc