MercuryDPM: oomph::HijackedData Class Reference
oomph::HijackedData Class Reference
#include <nodes.h>
Public Member Functions
void clear_copied_pointers ()
Clear the pointers to the copied data.
HijackedData (const unsigned &copied_value, Data *const &data_pt)
Constructor.
HijackedData (const Data &data)=delete
(Shallow) copy constructor
void operator= (const HijackedData &)=delete
Broken assignment operator.
~HijackedData ()
bool is_a_copy () const
bool is_a_copy (const unsigned &i) const
void assign_eqn_numbers (unsigned long &global_ndof, Vector< double * > &dof_pt)
void resize (const unsigned &n_value)
We do not allow Hijacked Data to be resized.
Public Member Functions inherited from oomph::Data
Data ()
Default constructor.
Data (const unsigned &initial_n_value)
Data (TimeStepper *const &time_stepper_pt, const unsigned &initial_n_value, const bool &allocate_storage=true)
Data (const Data &data)=delete
Broken copy constructor.
void operator= (const Data &)=delete
Broken assignment operator.
virtual ~Data ()
Destructor, deallocates memory assigned for data.
void set_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
TimeStepper *& time_stepper_pt ()
Return the pointer to the timestepper.
TimeStepper *const & time_stepper_pt () const
Return the pointer to the timestepper (const version).
void set_value (const unsigned &i, const double &value_)
void set_value (const unsigned &t, const unsigned &i, const double &value_)
double value (const unsigned &i) const
double value (const unsigned &t, const unsigned &i) const
void value (Vector< double > &values) const
Compute Vector of values for the Data value.
void value (const unsigned &t, Vector< double > &values) const
double * value_pt (const unsigned &i) const
double * value_pt (const unsigned &t, const unsigned &i) const
bool does_pointer_correspond_to_value (double *const &parameter_pt)
Check whether the pointer parameter_pt addresses internal data values.
void copy (Data *orig_data_pt)
Copy Data values from specified Data object.
void dump (std::ostream &dump_file) const
Dump the data object to a file.
void read (std::ifstream &restart_file)
Read data object from a file.
long * eqn_number_pt (const unsigned &i)
Return the pointer to the equation number of the i-th stored variable.
long & eqn_number (const unsigned &i)
Return the equation number of the i-th stored variable.
long eqn_number (const unsigned &i) const
Return the equation number of the i-th stored variable.
void pin (const unsigned &i)
Pin the i-th stored variable.
void unpin (const unsigned &i)
Unpin the i-th stored variable.
void pin_all ()
Pin all the stored variables.
void unpin_all ()
Unpin all the stored variables.
bool is_pinned (const unsigned &i) const
Test whether the i-th variable is pinned (1: true; 0: false).
bool is_segregated_solve_pinned (const unsigned &i)
void constrain (const unsigned &i)
void unconstrain (const unsigned &i)
void constrain_all ()
Constrain all the stored variables when the data is made hanging.
void unconstrain_all ()
Unconstrain all the stored variables when the data is made nonhanging.
bool is_constrained (const unsigned &i)
unsigned self_test ()
unsigned nvalue () const
Return number of values stored in data object (incl pinned ones).
unsigned ntstorage () const
virtual void describe_dofs (std::ostream &out, const std::string &current_string) const
virtual void add_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
Private Member Functions
void reset_copied_pointers ()
Reset the pointers to the copied data.
Private Attributes
Data * Copied_data_pt
Pointer to the Data object from which the value is copied.
unsigned Copied_index
Index of the value that is copied from within the Data object.
Additional Inherited Members
Static Public Attributes inherited from oomph::Data
static long Is_pinned = -1
Static "Magic number" to indicate pinned values.
static long Is_segregated_solve_pinned = -3
static long Is_unclassified = -10
static long Is_constrained = -2
Protected Attributes inherited from oomph::Data
Data ** Copy_of_data_pt
unsigned Ncopies
Static Protected Attributes inherited from oomph::Data
static TimeStepper * Default_static_time_stepper_pt = new Steady<0>()
Default (static) timestepper used in steady problems.
Detailed Description
Custom Data class that is used when HijackingData. The class always contains a single value that is copied from another Data object.
Constructor & Destructor Documentation
HijackedData() [1/2]
oomph::HijackedData::HijackedData (const unsigned & copied_index, Data *const & data_pt)
Constructor.
Constructor, creates a HijackedData object with a single value that is copied from another Data object. The ordering of the aguments is used to distinguish this case from that of copying all data values, except one independent value.
     : Data(data_pt->time_stepper_pt(), 1, false),
       Copied_data_pt(data_pt),
       Copied_index(copied_index)
   {
     // Don't allow copying of a copy
     if (data_pt->is_a_copy(copied_index))
     {
       std::ostringstream error_stream;
       error_stream << "The data you are trying to hijack is already a copy"
                    << std::endl;
       error_stream << "Please copy the original data" << std::endl;
       error_stream << "In a later version, I might do this for you,"
                    << " but not today" << std::endl;
       throw OomphLibError(
         error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
     // Copy the pointer to the value. This will give the appropriate
     //"slice" of the array
     Value = &data_pt->Value[copied_index];
     // Copy the pointer to the equation number
     Eqn_number = &data_pt->Eqn_number[copied_index];
     // Inform the original data that it has been copied
     data_pt->add_copy(this);
   }
References oomph::Data::add_copy(), oomph::Data::Eqn_number, oomph::Data::is_a_copy(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Data::Value.
HijackedData() [2/2]
oomph::HijackedData::HijackedData (const Data & data) delete
(Shallow) copy constructor
~HijackedData()
oomph::HijackedData::~HijackedData () inline
Destructor informs original object that the copy is being deleted and clears its pointers to the stored values.
     {
       // Inform the Copied data that this copy is being deleted
       // If the original has already been deleted
       // Copied_data_pt will be set to NULL and this will not be
       // necessary
       if (Copied_data_pt)
       {
         Copied_data_pt->remove_copy(this);
       }
       // Now null out the storage
       Copied_data_pt = 0;
       Value = 0;
       Eqn_number = 0;
     }
References Copied_data_pt, oomph::Data::Eqn_number, oomph::Data::remove_copy(), and oomph::Data::Value.
Member Function Documentation
assign_eqn_numbers()
void oomph::HijackedData::assign_eqn_numbers (unsigned long & global_ndof, Vector< double * > & dof_pt) inline virtual
HijackedData is always a copy, so no equation numbers should be allocated. This function just returns.
Reimplemented from oomph::Data.
     {
       return;
     }
clear_copied_pointers()
void oomph::HijackedData::clear_copied_pointers () virtual
Clear the pointers to the copied data.
Reimplemented from oomph::Data.
   {
     Copied_data_pt = 0;
     Value = 0;
     Eqn_number = 0;
   }
References Copied_data_pt, oomph::Data::Eqn_number, and oomph::Data::Value.
is_a_copy() [1/2]
bool oomph::HijackedData::is_a_copy () const inline virtual
Return a boolean to indicate whether the data contains any copied values. Hijacked data is always a copy
Reimplemented from oomph::Data.
     {
       return true;
     }
is_a_copy() [2/2]
bool oomph::HijackedData::is_a_copy (const unsigned & i) const inline virtual
Return a boolean to indicate whether the i-th value is a copied value. Hijacked data is always a copy
Reimplemented from oomph::Data.
     {
       return true;
     }
operator=()
void oomph::HijackedData::operator= (const HijackedData &) delete
Broken assignment operator.
reset_copied_pointers()
void oomph::HijackedData::reset_copied_pointers () private virtual
Reset the pointers to the copied data.
Reimplemented from oomph::Data.
   {
     // Copy the pointer to the value. This will give the appropriate
     //"slice" of the array
     Value = &Copied_data_pt->Value[Copied_index];
     // Copy the pointer to the equation number
     Eqn_number = &Copied_data_pt->Eqn_number[Copied_index];
   }
References Copied_data_pt, Copied_index, oomph::Data::Eqn_number, and oomph::Data::Value.
resize()
void oomph::HijackedData::resize (const unsigned & n_value) virtual
We do not allow Hijacked Data to be resized.
We cannot resize HijackedData, so the resize function throws a warning.
Reimplemented from oomph::Data.
   {
     throw OomphLibError("HijackedData cannot be resized",
                         OOMPH_CURRENT_FUNCTION,
                         OOMPH_EXCEPTION_LOCATION);
   }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Member Data Documentation
Copied_data_pt
Data* oomph::HijackedData::Copied_data_pt private
Pointer to the Data object from which the value is copied.
Referenced by clear_copied_pointers(), reset_copied_pointers(), and ~HijackedData().
Copied_index
unsigned oomph::HijackedData::Copied_index private
Index of the value that is copied from within the Data object.
Referenced by reset_copied_pointers().
The documentation for this class was generated from the following files:
nodes.h
nodes.cc