MercuryDPM: Eigen::internal::unitOrthogonal_selector< Derived, Size > Struct Template Reference
Eigen::internal::unitOrthogonal_selector< Derived, Size > Struct Template Reference
#include <OrthoMethods.h>
Public Types
typedef plain_matrix_type< Derived >::type VectorType
typedef traits< Derived >::Scalar Scalar
typedef NumTraits< Scalar >::Real RealScalar
typedef Matrix< Scalar, 2, 1 > Vector2
Static Public Member Functions
static EIGEN_DEVICE_FUNC VectorType run (const Derived &src)
Member Typedef Documentation
RealScalar
template<typename Derived , int Size = Derived::SizeAtCompileTime> typedef NumTraits<Scalar>::Real Eigen::internal::unitOrthogonal_selector< Derived, Size >::RealScalar
Scalar
template<typename Derived , int Size = Derived::SizeAtCompileTime> typedef traits<Derived>::Scalar Eigen::internal::unitOrthogonal_selector< Derived, Size >::Scalar
Vector2
template<typename Derived , int Size = Derived::SizeAtCompileTime> typedef Matrix<Scalar, 2, 1> Eigen::internal::unitOrthogonal_selector< Derived, Size >::Vector2
VectorType
template<typename Derived , int Size = Derived::SizeAtCompileTime> typedef plain_matrix_type<Derived>::type Eigen::internal::unitOrthogonal_selector< Derived, Size >::VectorType
Member Function Documentation
run()
template<typename Derived , int Size = Derived::SizeAtCompileTime> static EIGEN_DEVICE_FUNC VectorType Eigen::internal::unitOrthogonal_selector< Derived, Size >::run (const Derived & src) inline static
{
     VectorType perp = VectorType::Zero(src.size());
     Index maxi = 0;
     Index sndi = 0;
     src.cwiseAbs().maxCoeff(&maxi);
     if (maxi == 0) sndi = 1;
     RealScalar invnm = RealScalar(1) / (Vector2() << src.coeff(sndi), src.coeff(maxi)).finished().norm();
     perp.coeffRef(maxi) = -numext::conj(src.coeff(sndi)) * invnm;
     perp.coeffRef(sndi) = numext::conj(src.coeff(maxi)) * invnm;
     return perp;
   }
References conj(), MergeRestartFiles::finished, Eigen::numext::maxi(), and oomph::PseudoSolidHelper::Zero.
Referenced by Eigen::MatrixBase< Derived >::unitOrthogonal().
The documentation for this struct was generated from the following file:
OrthoMethods.h