MercuryDPM: oomph::deriv_functions::DampedOscillation Class Reference
oomph::deriv_functions::DampedOscillation Class Reference
A damped oscillation solution.
#include <ode_example_functions.h>
Public Member Functions
DampedOscillation ()
Constructor.
virtual ~DampedOscillation ()
Virtual destructor.
Vector< double > operator() (const double &t, const Vector< double > &x) const
Function call.
Vector< double > derivative (const double &t, const Vector< double > &x, const Vector< double > &u) const
Derivative call.
Public Member Functions inherited from oomph::SolutionFunctorBase
virtual ~SolutionFunctorBase ()
Virtual destructor.
virtual void jacobian (const double &t, const Vector< double > &x, const Vector< double > &u, DenseMatrix< double > &jacobian) const
virtual bool have_jacobian () const
Is a jacobian function implemented?
virtual void initialise_from_problem (const Problem *problem_pt)
Overload to grab data from the problem.
Public Attributes
double Beta
double Omega
Additional Inherited Members
Public Types inherited from oomph::SolutionFunctorBase
typedef double(* TimeSpaceToDoubleFctPt) (const double &t, const Vector< double > &x)
General function of space and time which returns a double.
typedef Vector< double >(* TimeSpaceToDoubleVectFctPt) (const double &t, const Vector< double > &x)
General function of space and time which returns a vector of doubles.
typedef Vector< double >(* TimeSpaceValueToDoubleVectFctPt) (const double &t, const Vector< double > &x, const Vector< double > &u)
Detailed Description
A damped oscillation solution.
Constructor & Destructor Documentation
DampedOscillation()
oomph::deriv_functions::DampedOscillation::DampedOscillation () inline
Constructor.
    {
     Beta = 0.5;
     Omega = 2;
    }
References Global::Beta, and oomph::SarahBL::Omega.
~DampedOscillation()
virtual oomph::deriv_functions::DampedOscillation::~DampedOscillation () inline virtual
Virtual destructor.
 {}
Member Function Documentation
derivative()
Vector<double> oomph::deriv_functions::DampedOscillation::derivative (const double & t, const Vector< double > & x, const Vector< double > & u) const inline virtual
Derivative call.
Implements oomph::SolutionFunctorBase.
    {
     Vector<double> deriv(1, 0.0);
     deriv[0] = -Beta * std::exp(-Beta*t) * std::sin(Omega*t)
      + Omega * std::exp(-Beta*t) * std::cos(Omega*t);
     return deriv;
    }
References Global::Beta, cos(), oomph::deriv_functions::exp(), oomph::SarahBL::Omega, sin(), and plotPSD::t.
operator()()
Vector<double> oomph::deriv_functions::DampedOscillation::operator() (const double & t, const Vector< double > & x) const inline virtual
Function call.
Implements oomph::SolutionFunctorBase.
    {
     Vector<double> values(1);
     values[0] = std::exp(-Beta*t) * std::sin(Omega*t);
     return values;
    }
References Global::Beta, oomph::deriv_functions::exp(), oomph::SarahBL::Omega, sin(), and plotPSD::t.
Member Data Documentation
Beta
double oomph::deriv_functions::DampedOscillation::Beta
Omega
double oomph::deriv_functions::DampedOscillation::Omega
The documentation for this class was generated from the following file:
ode_example_functions.h