MercuryDPM: oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT > Class Template Reference
oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT > Class Template Reference
#include <bretherton_spine_mesh.template.h>
Public Member Functions
BrethertonSpineMesh (const unsigned &nx1, const unsigned &nx2, const unsigned &nx3, const unsigned &nh, const unsigned &nhalf, const double &h, GeomObject *lower_wall_pt, GeomObject *upper_wall_pt, const double &zeta_start, const double &zeta_transition_start, const double &zeta_transition_end, const double &zeta_end, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
FiniteElement *& interface_element_pt (const unsigned long &i)
Access functions for pointers to interface elements.
unsigned long ninterface_element () const
Number of elements on interface.
FiniteElement *& bulk_element_pt (const unsigned long &i)
Access functions for pointers to elements in bulk.
unsigned long nbulk () const
Number of elements in bulk.
unsigned nfree_surface_spines ()
double find_distance_to_free_surface (GeomObject *const &fs_geom_object_pt, Vector< double > &initial_zeta, const Vector< double > &spine_base, const Vector< double > &spine_end)
Recalculate the spine lengths after repositioning.
void reposition_spines (const double &zeta_lo_transition_start, const double &zeta_lo_transition_end, const double &zeta_up_transition_start, const double &zeta_up_transition_end)
Reposition the spines in response to changes in geometry.
void pin_all_spines ()
void spine_node_update (SpineNode *spine_node_pt)
ELEMENT * control_element_pt ()
double spine_centre_fraction () const
Read the value of the spine centre's vertical fraction.
void set_spine_centre_fraction_pt (double *const &fraction_pt)
Set the pointer to the spine centre's vertial fraction.
Public Member Functions inherited from oomph::SingleLayerSpineMesh< ELEMENT >
SingleLayerSpineMesh (const unsigned &nx, const unsigned &ny, const double &lx, const double &h, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
SingleLayerSpineMesh (const unsigned &nx, const unsigned &ny, const double &lx, const double &h, const bool &periodic_in_x, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Public Member Functions inherited from oomph::RectangularQuadMesh< ELEMENT >
RectangularQuadMesh (const unsigned &nx, const unsigned &ny, const double &lx, const double &ly, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
RectangularQuadMesh (const unsigned &nx, const unsigned &ny, const double &xmin, const double &xmax, const double &ymin, const double &ymax, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
RectangularQuadMesh (const unsigned &nx, const unsigned &ny, const double &lx, const double &ly, const bool &periodic_in_x, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
RectangularQuadMesh (const unsigned &nx, const unsigned &ny, const double &xmin, const double &xmax, const double &ymin, const double &ymax, const bool &periodic_in_x, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
const unsigned & nx () const
Return number of elements in x direction.
const unsigned & ny () const
Return number of elements in y direction.
const double x_min () const
Return the minimum value of x coordinate.
const double x_max () const
Return the maximum value of x coordinate.
const double y_min () const
Return the minimum value of y coordinate.
const double y_max () const
Return the maximum value of y coordinate.
virtual void element_reorder ()
virtual double x_spacing_function (unsigned xelement, unsigned xnode, unsigned yelement, unsigned ynode)
virtual double y_spacing_function (unsigned xelement, unsigned xnode, unsigned yelement, unsigned ynode)
Public Member Functions inherited from oomph::QuadMeshBase
QuadMeshBase ()
Constructor (empty)
QuadMeshBase (const QuadMeshBase &node)=delete
Broken copy constructor.
void operator= (const QuadMeshBase &)=delete
Broken assignment operator.
virtual ~QuadMeshBase ()
Destructor (empty)
void setup_boundary_element_info ()
void setup_boundary_element_info (std::ostream &outfile)
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Public Member Functions inherited from oomph::SpineMesh
virtual ~SpineMesh ()
Destructor to clean up the memory allocated to the spines.
Spine *& spine_pt (const unsigned long &i)
Return the i-th spine in the mesh.
const Spine * spine_pt (const unsigned long &i) const
Return the i-th spine in the mesh (const version)
unsigned long nspine () const
Return the number of spines in the mesh.
void add_spine_pt (Spine *const &spine_pt)
Add a spine to the mesh.
SpineNode * node_pt (const unsigned long &n)
Return a pointer to the n-th global SpineNode.
SpineNode * element_node_pt (const unsigned long &e, const unsigned &n)
unsigned long assign_global_spine_eqn_numbers (Vector< double * > &Dof_pt)
Assign spines to Spine_pt vector of element.
void describe_spine_dofs (std::ostream &out, const std::string &current_string) const
void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_spine_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Assign time stepper to spines data.
void set_consistent_pinned_spine_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
bool does_pointer_correspond_to_spine_data (double *const &parameter_pt)
void node_update (const bool &update_all_solid_nodes=false)
void dump (std::ofstream &dump_file) const
Overload the dump function so that the spine data is dumped.
void read (std::ifstream &restart_file)
Overload the read function so that the spine data is also read.
Protected Member Functions
void spine_node_update_film_lower (SpineNode *spine_node_pt)
void spine_node_update_horizontal_transition_lower (SpineNode *spine_node_pt)
void spine_node_update_vertical_transition_lower (SpineNode *spine_node_pt)
void spine_node_update_vertical_transition_upper (SpineNode *spine_node_pt)
void spine_node_update_horizontal_transition_upper (SpineNode *spine_node_pt)
void spine_node_update_film_upper (SpineNode *spine_node_pt)
void spine_node_update_channel (SpineNode *spine_node_pt)
void initial_element_reorder ()
Protected Member Functions inherited from oomph::SingleLayerSpineMesh< ELEMENT >
virtual void build_single_layer_mesh (TimeStepper *time_stepper_pt)
Protected Member Functions inherited from oomph::RectangularQuadMesh< ELEMENT >
void build_mesh (TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Generic mesh construction function: contains all the hard work.
RectangularQuadMesh (const unsigned &nx, const unsigned &ny, const double &xmin, const double &xmax, const double &ymin, const double &ymax, const bool &periodic_in_x, const bool &build, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Protected Attributes
unsigned Nx1
Number of elements along wall in deposited film region.
unsigned Nx2
Number of elements along wall in horizontal transition region.
unsigned Nx3
Number of elements along wall in channel region.
unsigned Nhalf
unsigned Nh
Number of elements across the deposited film.
double H
Thickness of deposited film.
GeomObject * Upper_wall_pt
Pointer to geometric object that represents the upper wall.
GeomObject * Lower_wall_pt
Pointer to geometric object that represents the lower wall.
double Zeta_start
Start coordinate on wall.
double Zeta_end
Wall coordinate of end of liquid filled region (inflow)
double Zeta_transition_start
Wall coordinate of start of the transition region.
double Zeta_transition_end
Wall coordinate of end of transition region.
double * Spine_centre_fraction_pt
Pointer to vertical fraction of the spine centre.
double Default_spine_centre_fraction
Default spine fraction.
ELEMENT * Control_element_pt
Vector< FiniteElement * > Bulk_element_pt
Vector of pointers to element in the fluid layer.
Vector< FiniteElement * > Interface_element_pt
Vector of pointers to interface elements.
Protected Attributes inherited from oomph::RectangularQuadMesh< ELEMENT >
unsigned Nx
Nx: number of elements in x-direction.
unsigned Ny
Ny: number of elements in y-direction.
unsigned Np
Np: number of (linear) points in the element.
double Xmin
Minimum value of x coordinate.
double Xmax
Maximum value of x coordinate.
double Ymin
Minimum value of y coordinate.
double Ymax
Maximum value of y coordinate.
bool Xperiodic
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Protected Attributes inherited from oomph::SpineMesh
Vector< Spine * > Spine_pt
A Spine mesh contains a Vector of pointers to spines.
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Detailed Description
template<class ELEMENT, class INTERFACE_ELEMENT>
class oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >
Mesh for 2D Bretherton problem – based on single layer mesh. Templated by spine-ified Navier-Stokes element type (e.g. SpineElement<QCrouzeixRaviartElement<2> > and the corresponding interface element (e.g. SpineLineFluidInterfaceElement<SpineElement<QCrouzeixRaviartElement<2> > >
Constructor & Destructor Documentation
BrethertonSpineMesh()
template<class ELEMENT , class INTERFACE_ELEMENT > oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::BrethertonSpineMesh (const unsigned & nx1, const unsigned & nx2, const unsigned & nx3, const unsigned & nh, const unsigned & nhalf, const double & h, GeomObject * lower_wall_pt, GeomObject * upper_wall_pt, const double & zeta_start, const double & zeta_transition_start, const double & zeta_transition_end, const double & zeta_end, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
Constructor. Arguments:
nx1: Number of elements along wall in deposited film region
nx2: Number of elements along wall in horizontal transition region
nx3: Number of elements along wall in channel region
nhalf: Number of elements in vertical transition region (there are twice as many elements across the channel)
nh: Number of elements across the deposited film
h: Thickness of deposited film
zeta0: Start coordinate on wall
zeta1: Wall coordinate of start of transition region
zeta2: Wall coordinate of end of liquid filled region (inflow)
lower_wall_pt: Pointer to geometric object that represents the lower wall
upper_wall_pt: Pointer to geometric object that represents the upper wall
time_stepper_pt: Pointer to timestepper; defaults to Steady
Constructor. Arguments:
nx1: Number of elements along wall in deposited film region
nx2: Number of elements along wall in horizontal transition region
nx3: Number of elements along wall in channel region
nhalf: Number of elements in vertical transition region (there are twice as many elements across the channel)
nh: Number of elements across the deposited film
h: Thickness of deposited film
zeta0: Start coordinate on wall
zeta1: Wall coordinate of start of transition region
zeta2: Wall coordinate of end of liquid filled region (inflow)
lower_wall_pt: Pointer to geometric object that represents the lower wall
upper_wall_pt: Pointer to geometric object that represents the upper wall
time_stepper_pt: Pointer to timestepper; defaults to Static
     : SingleLayerSpineMesh<ELEMENT>(
         2 * (nx1 + nx2 + nhalf), nh, 1.0, h, time_stepper_pt),
       Nx1(nx1),
       Nx2(nx2),
       Nx3(nx3),
       Nhalf(nhalf),
       Nh(nh),
       H(h),
       Upper_wall_pt(upper_wall_pt),
       Lower_wall_pt(lower_wall_pt),
       Zeta_start(zeta_start),
       Zeta_end(zeta_end),
       Zeta_transition_start(zeta_transition_start),
       Zeta_transition_end(zeta_transition_end),
       Spine_centre_fraction_pt(&Default_spine_centre_fraction),
       Default_spine_centre_fraction(0.5)
   {
     // Add the created elements to the bulk domain
     unsigned n_bulk = this->nelement();
     Bulk_element_pt.resize(n_bulk);
     for (unsigned e = 0; e < n_bulk; e++)
     {
       Bulk_element_pt[e] = this->finite_element_pt(e);
     }
     // Mesh can only be built with 2D Qelements.
     MeshChecker::assert_geometric_element<QElementGeometricBase, ELEMENT>(2);
     // Mesh can only be built with spine elements
     MeshChecker::assert_geometric_element<SpineFiniteElement, ELEMENT>(2);
     // Initialise start of transition region to zero
     // Zeta_transition_start = 0.0;
     // Length of deposited film region
     double llayer = Zeta_transition_start - Zeta_start;
     // Length of transition region
     double d = Zeta_transition_end - Zeta_transition_start;
     // Work out radius of circular cap from lower and upper wall
     Vector<double> r_wall_lo(2), r_wall_up(2);
     Vector<double> zeta(1), s_lo(1), s_up(1);
     GeomObject *lower_sub_geom_object_pt = 0, *upper_sub_geom_object_pt = 0;
     GeomObject* lower_transition_geom_object_pt = 0;
     GeomObject* upper_transition_geom_object_pt = 0;
     Vector<double> s_transition_lo(1), s_transition_up(1);
     Vector<double> spine_centre(2);
     // Find position of lower and upper walls at start of transition region
     zeta[0] = Zeta_transition_start;
     Lower_wall_pt->position(zeta, r_wall_lo);
     Upper_wall_pt->position(zeta, r_wall_up);
     // Radius is the difference between the film thickness and the distance
     // to the lower wall
     double radius = -r_wall_lo[1] - H;
     // Check to non-symmetric mesh
     if (std::fabs(r_wall_lo[1] + r_wall_up[1]) > 1.0e-4)
     {
       oomph_info << "\n\n=================================================== "
                  << std::endl;
       oomph_info << "Warning: " << std::endl;
       oomph_info << "-------- " << std::endl;
       oomph_info << " " << std::endl;
       oomph_info << "Upper and lower walls are not symmetric at zeta=0"
                  << std::endl;
       oomph_info << "Your initial mesh will look very odd." << std::endl;
       oomph_info << "y-coordinates of walls at zeta=0 are: " << r_wall_lo[1]
                  << " and " << r_wall_up[1] << std::endl
                  << std::endl;
       oomph_info << "===================================================\n\n "
                  << std::endl;
     }
     // Add the interface elements
     // Loop over the horizontal elements
     {
       unsigned n_x = 2 * (nx1 + nx2 + nhalf);
       unsigned n_y = nh;
       for (unsigned i = 0; i < n_x; i++)
       {
         // Construct a new 1D line element on the face on which the local
         // coordinate 1 is fixed at its max. value (1) --- This is face 2
         FiniteElement* interface_element_element_pt = new INTERFACE_ELEMENT(
           this->finite_element_pt(n_x * (n_y - 1) + i), 2);
         // Push it back onto the stack
         this->Element_pt.push_back(interface_element_element_pt);
         // Push it back onto the stack of interface elements
         this->Interface_element_pt.push_back(interface_element_element_pt);
       }
     }
     // Reorder elements: Vertical stacks of elements, each topped by
     // their interface element -- this is (currently) identical to the
     // version in the SingleLayerSpineMesh but it's important
     // that element reordering is maintained in exactly this form
     // so to be on the safe side, we move the function in here.
     initial_element_reorder();
     // Store pointer to control element
     Control_element_pt = dynamic_cast<ELEMENT*>(
       this->element_pt((nx1 + nx2 + nhalf) * (nh + 1) - 2));
     // Temporary storage for boundary lookup scheme
     Vector<std::set<Node*>> set_boundary_node_pt(6);
     // Boundary 1 -> 3; 2 -> 4; 3 -> 5
     for (unsigned ibound = 1; ibound <= 3; ibound++)
     {
       unsigned numnod = this->nboundary_node(ibound);
       for (unsigned j = 0; j < numnod; j++)
       {
         set_boundary_node_pt[ibound + 2].insert(
           this->boundary_node_pt(ibound, j));
       }
     }
     // Get number of nodes per element
     unsigned nnod = this->finite_element_pt(0)->nnode();
     // Get number of nodes along element edge
     unsigned np = this->finite_element_pt(0)->nnode_1d();
     // Initialise number of elements in previous regions:
     unsigned n_prev_elements = 0;
     // We've now built the straight single-layer mesh and need to change the
     // the update functions for all nodes so that the domain
     // deforms into the Bretherton shape
     // Loop over elements in lower deposited film region
     // -------------------------------------------------
     {
       // Increments in wall coordinate
       double dzeta_el = llayer / double(nx1);
       double dzeta_node = llayer / double(nx1 * (np - 1));
       // Loop over elements horizontally
       for (unsigned i = 0; i < nx1; i++)
       {
         // Start of wall coordinate
         double zeta_lo = Zeta_start + double(i) * dzeta_el;
         // Loop over elements vertically
         for (unsigned j = 0; j < nh; j++)
         {
           // Work out element number in overall mesh
           unsigned e = n_prev_elements + i * (nh + 1) + j;
           // Get pointer to element
           FiniteElement* el_pt = this->finite_element_pt(e);
           // Loop over its nodes
           for (unsigned i0 = 0; i0 < np; i0++)
           {
             for (unsigned i1 = 0; i1 < np; i1++)
             {
               // Node number:
               unsigned n = i0 * np + i1;
               // Get spine node
               SpineNode* nod_pt = dynamic_cast<SpineNode*>(el_pt->node_pt(n));
               // Set update fct id
               nod_pt->node_update_fct_id() = 0;
               // Provide spine with additional storage for wall coordinate
               // and wall geom object:
               if (i0 == 0)
               {
                 // Get the Lagrangian coordinate in the Lower Wall
                 zeta[0] = zeta_lo + double(i1) * dzeta_node;
                 // Get the geometric object and local coordinate
                 Lower_wall_pt->locate_zeta(
                   zeta, lower_sub_geom_object_pt, s_lo);
                 // The local coordinate is a geometric parameter
                 // This needs to be set (rather than added) because the
                 // same spine may be visited more than once
                 Vector<double> parameters(1, s_lo[0]);
                 nod_pt->spine_pt()->set_geom_parameter(parameters);
                 // Adjust spine height
                 nod_pt->spine_pt()->height() = H;
                 // The sub geom object is one (and only) geom object
                 // for spine:
                 Vector<GeomObject*> geom_object_pt(1);
                 geom_object_pt[0] = lower_sub_geom_object_pt;
                 // Pass geom object(s) to spine
                 nod_pt->spine_pt()->set_geom_object_pt(geom_object_pt);
                 // Push the node back onto boundaries
                 if (j == 0) set_boundary_node_pt[0].insert(nod_pt);
               }
             }
           }
         }
       }
       // Increment number of previous elements
       n_prev_elements += nx1 * (nh + 1);
     }
     {
       // Calculate the centre for the spine nodes in the transition region
       zeta[0] = Zeta_transition_start;
       // Get the geometric objects on the walls at the start of the transition
       // region
       Lower_wall_pt->locate_zeta(
         zeta, lower_transition_geom_object_pt, s_transition_lo);
       Upper_wall_pt->locate_zeta(
         zeta, upper_transition_geom_object_pt, s_transition_up);
       // Find the Eulerian coordinates of the walls at the transition region
       lower_transition_geom_object_pt->position(s_transition_lo, r_wall_lo);
       upper_transition_geom_object_pt->position(s_transition_up, r_wall_up);
       // Take the average of these positions to define the origin of the spines
       // in the transition region Horizontal position is always halfway
       spine_centre[0] = 0.5 * (r_wall_lo[0] + r_wall_up[0]);
       // Vertical Position is given by a specified fraction
       // between the upper and lower walls
       spine_centre[1] =
         r_wall_lo[1] + spine_centre_fraction() * (r_wall_up[1] - r_wall_lo[1]);
     }
     // Loop over elements in lower horizontal transition region
     // --------------------------------------------------------
     {
       // Increments in wall coordinate
       double dzeta_el = d / double(nx2);
       double dzeta_node = d / double(nx2 * (np - 1));
       // Loop over elements horizontally
       for (unsigned i = 0; i < nx2; i++)
       {
         // Start of wall coordinate
         double zeta_lo = Zeta_transition_start + double(i) * dzeta_el;
         // Loop over elements vertically
         for (unsigned j = 0; j < nh; j++)
         {
           // Work out element number in overall mesh
           unsigned e = n_prev_elements + i * (nh + 1) + j;
           // Get pointer to element
           FiniteElement* el_pt = this->finite_element_pt(e);
           // Loop over its nodes
           for (unsigned i0 = 0; i0 < np; i0++)
           {
             for (unsigned i1 = 0; i1 < np; i1++)
             {
               // Node number:
               unsigned n = i0 * np + i1;
               // Get spine node
               SpineNode* nod_pt = dynamic_cast<SpineNode*>(el_pt->node_pt(n));
               // Set update id
               nod_pt->node_update_fct_id() = 1;
               // Provide spine with additional storage for wall coordinate
               if (i0 == 0)
               {
                 // Get the Lagrangian coordinate in the Lower Wall
                 zeta[0] = zeta_lo + double(i1) * dzeta_node;
                 // Get the sub geometric object and local coordinate
                 Lower_wall_pt->locate_zeta(
                   zeta, lower_sub_geom_object_pt, s_lo);
                 // Pass geometric parameter to the spine
                 Vector<double> parameters(3);
                 parameters[0] = s_lo[0];
                 parameters[1] = s_transition_lo[0];
                 parameters[2] = s_transition_up[0];
                 nod_pt->spine_pt()->set_geom_parameter(parameters);
                 // Get position vector to wall
                 lower_sub_geom_object_pt->position(s_lo, r_wall_lo);
                 // Get normal vector towards origin
                 Vector<double> N(2);
                 N[0] = spine_centre[0] - r_wall_lo[0];
                 N[1] = spine_centre[1] - r_wall_lo[1];
                 double length = sqrt(N[0] * N[0] + N[1] * N[1]);
                 nod_pt->spine_pt()->height() = length - radius;
                 // Lower sub geom object is one (and only) geom object
                 // for spine:
                 Vector<GeomObject*> geom_object_pt(3);
                 geom_object_pt[0] = lower_sub_geom_object_pt;
                 geom_object_pt[1] = lower_transition_geom_object_pt;
                 geom_object_pt[2] = upper_transition_geom_object_pt;
                 // Pass geom object(s) to spine
                 nod_pt->spine_pt()->set_geom_object_pt(geom_object_pt);
                 // Push the node back onto boundaries
                 if (j == 0) set_boundary_node_pt[0].insert(nod_pt);
               }
             }
           }
         }
       }
       // Increment number of previous elements
       n_prev_elements += nx2 * (nh + 1);
     }
     // Loop over elements in lower vertical transition region
     // --------------------------------------------------------
     {
       for (unsigned i = 0; i < nhalf; i++)
       {
         // Loop over elements vertically
         for (unsigned j = 0; j < nh; j++)
         {
           // Work out element number in overall mesh
           unsigned e = n_prev_elements + i * (nh + 1) + j;
           // Get pointer to element
           FiniteElement* el_pt = this->finite_element_pt(e);
           // Loop over its nodes
           for (unsigned i0 = 0; i0 < np; i0++)
           {
             for (unsigned i1 = 0; i1 < np; i1++)
             {
               // Node number:
               unsigned n = i0 * np + i1;
               // Get spine node
               SpineNode* nod_pt = dynamic_cast<SpineNode*>(el_pt->node_pt(n));
               // Set update id
               nod_pt->node_update_fct_id() = 2;
               // Provide spine with additional storage for fraction along
               // vertical line
               if (i0 == 0)
               {
                 // Get position vectors to wall
                 zeta[0] = Zeta_transition_end;
                 // Get the sub geometric objects
                 Lower_wall_pt->locate_zeta(
                   zeta, lower_sub_geom_object_pt, s_lo);
                 Upper_wall_pt->locate_zeta(
                   zeta, upper_sub_geom_object_pt, s_up);
                 lower_sub_geom_object_pt->position(s_lo, r_wall_lo);
                 upper_sub_geom_object_pt->position(s_up, r_wall_up);
                 // Set vertical fraction
                 double vertical_fraction =
                   (double(i) + double(i1) / double(np - 1)) /
                   double(2.0 * nhalf);
                 // Add the geometric parameters in order
                 Vector<double> parameters(5);
                 parameters[0] = s_lo[0];
                 parameters[1] = s_up[0];
                 parameters[2] = vertical_fraction;
                 parameters[3] = s_transition_lo[0];
                 parameters[4] = s_transition_up[0];
                 nod_pt->spine_pt()->set_geom_parameter(parameters);
                 // Origin of spine
                 Vector<double> S0(2);
                 S0[0] = r_wall_lo[0] +
                         vertical_fraction * (r_wall_up[0] - r_wall_lo[0]);
                 S0[1] = r_wall_lo[1] +
                         vertical_fraction * (r_wall_up[1] - r_wall_lo[1]);
                 // Get normal vector towards origin
                 Vector<double> N(2);
                 N[0] = spine_centre[0] - S0[0];
                 N[1] = spine_centre[1] - S0[1];
                 double length = sqrt(N[0] * N[0] + N[1] * N[1]);
                 nod_pt->spine_pt()->height() = length - radius;
                 // Lower and Upper wall sub geom objects affect  spine:
                 Vector<GeomObject*> geom_object_pt(4);
                 geom_object_pt[0] = lower_sub_geom_object_pt;
                 geom_object_pt[1] = upper_sub_geom_object_pt;
                 geom_object_pt[2] = lower_transition_geom_object_pt;
                 geom_object_pt[3] = upper_transition_geom_object_pt;
                 // Pass geom object(s) to spine
                 nod_pt->spine_pt()->set_geom_object_pt(geom_object_pt);
                 // Push the node back onto boundaries
                 if (j == 0) set_boundary_node_pt[1].insert(nod_pt);
               }
             }
           }
         }
       }
       // Increment number of previous elements
       n_prev_elements += nhalf * (nh + 1);
     }
     // Loop over elements in upper vertical transition region
     // ------------------------------------------------------
     {
       for (unsigned i = 0; i < nhalf; i++)
       {
         // Loop over elements vertically
         for (unsigned j = 0; j < nh; j++)
         {
           // Work out element number in overall mesh
           unsigned e = n_prev_elements + i * (nh + 1) + j;
           // Get pointer to element
           FiniteElement* el_pt = this->finite_element_pt(e);
           // Loop over its nodes
           for (unsigned i0 = 0; i0 < np; i0++)
           {
             for (unsigned i1 = 0; i1 < np; i1++)
             {
               // Node number:
               unsigned n = i0 * np + i1;
               // Get spine node
               SpineNode* nod_pt = dynamic_cast<SpineNode*>(el_pt->node_pt(n));
               // Set update id
               nod_pt->node_update_fct_id() = 3;
               // Provide spine with additional storage for fraction along
               // vertical line
               if (i0 == 0)
               {
                 // Get position vectors to wall
                 zeta[0] = Zeta_transition_end;
                 // Get the sub geometric objects
                 Lower_wall_pt->locate_zeta(
                   zeta, lower_sub_geom_object_pt, s_lo);
                 Upper_wall_pt->locate_zeta(
                   zeta, upper_sub_geom_object_pt, s_up);
                 lower_sub_geom_object_pt->position(s_lo, r_wall_lo);
                 upper_sub_geom_object_pt->position(s_up, r_wall_up);
                 // Set vertical fraction
                 double vertical_fraction =
                   0.5 + (double(i) + double(i1) / double(np - 1)) /
                           double(2.0 * nhalf);
                 // Add the geometric parameters in order
                 Vector<double> parameters(5);
                 parameters[0] = s_lo[0];
                 parameters[1] = s_up[0];
                 parameters[2] = vertical_fraction;
                 parameters[3] = s_transition_lo[0];
                 parameters[4] = s_transition_up[0];
                 nod_pt->spine_pt()->set_geom_parameter(parameters);
                 // Origin of spine
                 Vector<double> S0(2);
                 S0[0] = r_wall_lo[0] +
                         vertical_fraction * (r_wall_up[0] - r_wall_lo[0]);
                 S0[1] = r_wall_lo[1] +
                         vertical_fraction * (r_wall_up[1] - r_wall_lo[1]);
                 // Get normal vector towards origin
                 Vector<double> N(2);
                 N[0] = spine_centre[0] - S0[0];
                 N[1] = spine_centre[1] - S0[1];
                 double length = sqrt(N[0] * N[0] + N[1] * N[1]);
                 nod_pt->spine_pt()->height() = length - radius;
                 // Upper and Lower wall geom objects affect spine
                 Vector<GeomObject*> geom_object_pt(4);
                 geom_object_pt[0] = lower_sub_geom_object_pt;
                 geom_object_pt[1] = upper_sub_geom_object_pt;
                 geom_object_pt[2] = lower_transition_geom_object_pt;
                 geom_object_pt[3] = upper_transition_geom_object_pt;
                 // Pass geom object(s) to spine
                 nod_pt->spine_pt()->set_geom_object_pt(geom_object_pt);
                 // Push the node back onto boundaries
                 if (j == 0) set_boundary_node_pt[1].insert(nod_pt);
               }
             }
           }
         }
       }
       // Increment number of previous elements
       n_prev_elements += nhalf * (nh + 1);
     }
     // Loop over elements in upper horizontal transition region
     // --------------------------------------------------------
     {
       // Increments in wall coordinate
       double dzeta_el = d / double(nx2);
       double dzeta_node = d / double(nx2 * (np - 1));
       // Loop over elements horizontally
       for (unsigned i = 0; i < nx2; i++)
       {
         // Start of wall coordinate
         double zeta_lo = Zeta_transition_end - double(i) * dzeta_el;
         // Loop over elements vertically
         for (unsigned j = 0; j < nh; j++)
         {
           // Work out element number in overall mesh
           unsigned e = n_prev_elements + i * (nh + 1) + j;
           // Get pointer to element
           FiniteElement* el_pt = this->finite_element_pt(e);
           // Loop over its nodes
           for (unsigned i0 = 0; i0 < np; i0++)
           {
             for (unsigned i1 = 0; i1 < np; i1++)
             {
               // Node number:
               unsigned n = i0 * np + i1;
               // Get spine node
               SpineNode* nod_pt = dynamic_cast<SpineNode*>(el_pt->node_pt(n));
               // Set update id
               nod_pt->node_update_fct_id() = 4;
               // Provide spine with additional storage for wall coordinate
               if (i0 == 0)
               {
                 // Get the Lagrangian coordinate in the Upper wall
                 zeta[0] = zeta_lo - double(i1) * dzeta_node;
                 // Get the sub geometric object and local coordinate
                 Upper_wall_pt->locate_zeta(
                   zeta, upper_sub_geom_object_pt, s_up);
                 // Pass geometric parameter to spine
                 Vector<double> parameters(3);
                 parameters[0] = s_up[0];
                 parameters[1] = s_transition_lo[0];
                 parameters[2] = s_transition_up[0];
                 nod_pt->spine_pt()->set_geom_parameter(parameters);
                 // Get position vector to wall
                 upper_sub_geom_object_pt->position(s_up, r_wall_up);
                 // Get normal vector towards origin
                 Vector<double> N(2);
                 N[0] = spine_centre[0] - r_wall_up[0];
                 N[1] = spine_centre[1] - r_wall_up[1];
                 double length = sqrt(N[0] * N[0] + N[1] * N[1]);
                 nod_pt->spine_pt()->height() = length - radius;
                 // upper wall sub geom object is one (and only) geom object
                 // for spine:
                 Vector<GeomObject*> geom_object_pt(3);
                 geom_object_pt[0] = upper_sub_geom_object_pt;
                 geom_object_pt[1] = lower_transition_geom_object_pt;
                 geom_object_pt[2] = upper_transition_geom_object_pt;
                 // Pass geom object(s) to spine
                 nod_pt->spine_pt()->set_geom_object_pt(geom_object_pt);
                 // Push the node back onto boundaries
                 if (j == 0) set_boundary_node_pt[2].insert(nod_pt);
               }
             }
           }
         }
       }
       // Increment number of previous elements
       n_prev_elements += nx2 * (nh + 1);
     }
     // Loop over elements in upper deposited film region
     // -------------------------------------------------
     {
       // Increments in wall coordinate
       double dzeta_el = llayer / double(nx1);
       double dzeta_node = llayer / double(nx1 * (np - 1));
       // Loop over elements horizontally
       for (unsigned i = 0; i < nx1; i++)
       {
         // Start of wall coordinate
         double zeta_lo = Zeta_transition_start - double(i) * dzeta_el;
         // Loop over elements vertically
         for (unsigned j = 0; j < nh; j++)
         {
           // Work out element number in overall mesh
           unsigned e = n_prev_elements + i * (nh + 1) + j;
           // Get pointer to element
           FiniteElement* el_pt = this->finite_element_pt(e);
           // Loop over its nodes
           for (unsigned i0 = 0; i0 < np; i0++)
           {
             for (unsigned i1 = 0; i1 < np; i1++)
             {
               // Node number:
               unsigned n = i0 * np + i1;
               // Get spine node
               SpineNode* nod_pt = dynamic_cast<SpineNode*>(el_pt->node_pt(n));
               // Set update id
               nod_pt->node_update_fct_id() = 5;
               // Provide spine with additional storage for wall coordinate
               if (i0 == 0)
               {
                 // Get the Lagrangian coordinate in the Upper wall
                 zeta[0] = zeta_lo - double(i1) * dzeta_node;
                 // Get the geometric object and local coordinate
                 Upper_wall_pt->locate_zeta(
                   zeta, upper_sub_geom_object_pt, s_up);
                 // The local coordinate is a geometric parameter
                 Vector<double> parameters(1, s_up[0]);
                 nod_pt->spine_pt()->set_geom_parameter(parameters);
                 // Adjust spine height
                 nod_pt->spine_pt()->height() = H;
                 // upper sub geom object is one (and only) geom object
                 // for spine:
                 Vector<GeomObject*> geom_object_pt(1);
                 geom_object_pt[0] = upper_sub_geom_object_pt;
                 // Pass geom object(s) to spine
                 nod_pt->spine_pt()->set_geom_object_pt(geom_object_pt);
                 // Push the node back onto boundaries
                 if (j == 0) set_boundary_node_pt[2].insert(nod_pt);
               }
             }
           }
         }
       }
     }
     // Wipe the boundary lookup schemes
     this->remove_boundary_nodes();
     this->set_nboundary(6);
     // Copy from sets to vectors
     for (unsigned ibound = 0; ibound < 6; ibound++)
     {
       typedef std::set<Node*>::iterator IT;
       for (IT it = set_boundary_node_pt[ibound].begin();
            it != set_boundary_node_pt[ibound].end();
            it++)
       {
         this->add_boundary_node(ibound, *it);
       }
     }
     // Loop over the free surface boundary (4) and set a boundary coordinate
     {
       // Boundary coordinate
       Vector<double> zeta(1);
       unsigned n_boundary_node = this->nboundary_node(4);
       for (unsigned n = 0; n < n_boundary_node; ++n)
       {
         zeta[0] = this->boundary_node_pt(4, n)->x(0);
         this->boundary_node_pt(4, n)->set_coordinates_on_boundary(4, zeta);
       }
     }
     // Now add the rectangular mesh in the channel ahead of the finger tip
     //--------------------------------------------------------------------
     // Build a temporary version of a SimpleRectangularQuadMesh as
     // a unit square
     SimpleRectangularQuadMesh<ELEMENT>* aux_mesh_pt =
       new SimpleRectangularQuadMesh<ELEMENT>(
         Nx3, 2 * nhalf, 1.0, 1.0, time_stepper_pt);
     // Wipe the boundary information in the auxilliary mesh
     aux_mesh_pt->remove_boundary_nodes();
     // Copy all nodes in the auxiliary mesh into a set (from where they
     // can easily be removed)
     nnod = aux_mesh_pt->nnode();
     std::set<Node*> aux_node_pt;
     for (unsigned i = 0; i < nnod; i++)
     {
       aux_node_pt.insert(aux_mesh_pt->node_pt(i));
     }
     // Loop over elements in first column and set pointers
     // to the nodes in their first column to the ones that already exist
     // Boundary node number for first node in element
     unsigned first_bound_node = 0;
     // Loop over elements
     for (unsigned e = 0; e < 2 * nhalf; e++)
     {
       FiniteElement* el_pt = aux_mesh_pt->finite_element_pt(e * Nx3);
       // Loop over first column of nodes
       for (unsigned i = 0; i < np; i++)
       {
         // Node number in element
         unsigned n = i * np;
         // Remove node from set and kill it
         if ((e < 1) || (i > 0))
         {
           aux_node_pt.erase(el_pt->node_pt(n));
           delete el_pt->node_pt(n);
         }
         // Set pointer to existing node
         el_pt->node_pt(n) = this->boundary_node_pt(1, first_bound_node + i);
       }
       // Increment first node number
       first_bound_node += np - 1;
     }
     // Now add all the remaining nodes in the auxiliary mesh
     // to the actual one
     typedef std::set<Node*>::iterator IT;
     for (IT it = aux_node_pt.begin(); it != aux_node_pt.end(); it++)
     {
       this->Node_pt.push_back(*it);
     }
     // Store number of elements before the new bit gets added:
     unsigned nelement_orig = this->Element_pt.size();
     // Add the elements to the actual mesh
     unsigned nelem = aux_mesh_pt->nelement();
     for (unsigned e = 0; e < nelem; e++)
     {
       this->Element_pt.push_back(aux_mesh_pt->element_pt(e));
       // Don't forget to add them to the bulk
       this->Bulk_element_pt.push_back(aux_mesh_pt->finite_element_pt(e));
     }
     // Now wipe the boundary node storage scheme for the
     // nodes that used to be at the end of the domain:
     this->remove_boundary_nodes(1);
     // FIRST SPINE
     //-----------
     // Element 0
     // Node 0
     // Assign the new spine with unit height (pinned dummy -- never used)
     Spine* new_spine_pt = new Spine(1.0);
     this->Spine_pt.push_back(new_spine_pt);
     new_spine_pt->spine_height_pt()->pin(0);
     // Get pointer to node
     SpineNode* nod_pt = this->element_node_pt(nelement_orig + 0, 0);
     // Set the pointer to node
     nod_pt->spine_pt() = new_spine_pt;
     // Set the fraction
     nod_pt->fraction() = 0.0;
     // Pointer to the mesh that implements the update fct
     nod_pt->spine_mesh_pt() = this;
     // ID for the update function
     nod_pt->node_update_fct_id() = 6;
     // Need to get the local coordinates for the upper and lower wall
     zeta[0] = Zeta_transition_end;
     // Get the sub geometric objects
     Lower_wall_pt->locate_zeta(zeta, lower_sub_geom_object_pt, s_lo);
     Upper_wall_pt->locate_zeta(zeta, upper_sub_geom_object_pt, s_up);
     lower_sub_geom_object_pt->position(s_lo, r_wall_lo);
     upper_sub_geom_object_pt->position(s_up, r_wall_up);
     // Pass additional data to spine
     Vector<double> parameters(2);
     parameters[0] = s_lo[0];
     parameters[1] = s_up[0];
     new_spine_pt->set_geom_parameter(parameters);
     // Lower and upper wall sub geom objects affect update
     // for spine:
     Vector<GeomObject*> geom_object_pt(2);
     geom_object_pt[0] = lower_sub_geom_object_pt;
     geom_object_pt[1] = upper_sub_geom_object_pt;
     // Pass geom object(s) to spine
     new_spine_pt->set_geom_object_pt(geom_object_pt);
     // Loop vertically along the spine
     // Loop over the elements
     for (unsigned long i = 0; i < 2 * nhalf; i++)
     {
       // Loop over the vertical nodes, apart from the first
       for (unsigned l1 = 1; l1 < np; l1++)
       {
         // Get pointer to node
         SpineNode* nod_pt =
           this->element_node_pt(nelement_orig + i * Nx3, l1 * np);
         // Set the pointer to the spine
         nod_pt->spine_pt() = new_spine_pt;
         // Set the fraction
         nod_pt->fraction() =
           (double(i) + double(l1) / double(np - 1)) / double(2 * nhalf);
         // Pointer to the mesh that implements the update fct
         nod_pt->spine_mesh_pt() = this;
         // ID for the update function
         nod_pt->node_update_fct_id() = 6;
       }
     }
     // LOOP OVER OTHER SPINES
     //----------------------
     // Now loop over the elements horizontally
     for (unsigned long j = 0; j < Nx3; j++)
     {
       // Loop over the nodes in the elements horizontally, ignoring
       // the first column
       for (unsigned l2 = 1; l2 < np; l2++)
       {
         // Assign the new spine with unit height (pinned dummy; never used)
         new_spine_pt = new Spine(1.0);
         this->Spine_pt.push_back(new_spine_pt);
         new_spine_pt->spine_height_pt()->pin(0);
         // Get the node
         SpineNode* nod_pt = this->element_node_pt(nelement_orig + j, l2);
         // Set the pointer to the spine
         nod_pt->spine_pt() = new_spine_pt;
         // Set the fraction
         nod_pt->fraction() = 0.0;
         // Pointer to the mesh that implements the update fct
         nod_pt->spine_mesh_pt() = this;
         // ID for the update function
         nod_pt->node_update_fct_id() = 6;
         // Add to boundary lookup scheme
         this->add_boundary_node(0, nod_pt);
         if ((j == Nx3 - 1) && (l2 == np - 1))
         {
           this->add_boundary_node(1, nod_pt);
         }
         // Increment in wall coordinate
         double dzeta_el = (Zeta_end - Zeta_transition_end) / double(Nx3);
         double dzeta_nod = dzeta_el / double(np - 1);
         // Get wall coordinate
         zeta[0] = Zeta_transition_end + j * dzeta_el + l2 * dzeta_nod;
         // Get the sub geometric objects
         Lower_wall_pt->locate_zeta(zeta, lower_sub_geom_object_pt, s_lo);
         Upper_wall_pt->locate_zeta(zeta, upper_sub_geom_object_pt, s_up);
         lower_sub_geom_object_pt->position(s_lo, r_wall_lo);
         upper_sub_geom_object_pt->position(s_up, r_wall_up);
         // Add geometric parameters to spine
         Vector<double> parameters(2);
         parameters[0] = s_lo[0];
         parameters[1] = s_up[0];
         new_spine_pt->set_geom_parameter(parameters);
         // Lower and upper sub geom objects affect update
         // for spine:
         Vector<GeomObject*> geom_object_pt(2);
         geom_object_pt[0] = lower_sub_geom_object_pt;
         geom_object_pt[1] = upper_sub_geom_object_pt;
         // Pass geom object(s) to spine
         new_spine_pt->set_geom_object_pt(geom_object_pt);
         // Loop vertically along the spine
         // Loop over the elements
         for (unsigned long i = 0; i < 2 * nhalf; i++)
         {
           // Loop over the vertical nodes, apart from the first
           for (unsigned l1 = 1; l1 < np; l1++)
           {
             // Get node
             SpineNode* nod_pt =
               this->element_node_pt(nelement_orig + i * Nx3 + j, l1 * np + l2);
             // Set the pointer to the spine
             nod_pt->spine_pt() = new_spine_pt;
             // Set the fraction
             nod_pt->fraction() =
               (double(i) + double(l1) / double(np - 1)) / double(2 * nhalf);
             // Pointer to the mesh that implements the update fct
             nod_pt->spine_mesh_pt() = this;
             // ID for the update function
             nod_pt->node_update_fct_id() = 6;
             // Add to boundary lookup scheme
             if ((j == Nx3 - 1) && (l2 == np - 1))
             {
               this->add_boundary_node(1, nod_pt);
             }
             // Add to boundary lookup scheme
             if ((i == 2 * nhalf - 1) && (l1 == np - 1))
             {
               this->add_boundary_node(2, nod_pt);
             }
           }
         }
       }
     }
     // (Re-)setup lookup scheme that establishes which elements are located
     // on the mesh boundaries
     this->setup_boundary_element_info();
     // Flush the storage for elements and nodes in the auxiliary mesh
     // so it can be safely deleted
     aux_mesh_pt->flush_element_and_node_storage();
     // Kill the auxiliary mesh
     delete aux_mesh_pt;
   }
Member Function Documentation
bulk_element_pt()
template<class ELEMENT , class INTERFACE_ELEMENT > FiniteElement*& oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::bulk_element_pt (const unsigned long & i) inline
Access functions for pointers to elements in bulk.
     {
       return Bulk_element_pt[i];
     }
References oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Bulk_element_pt, and i.
control_element_pt()
template<class ELEMENT , class INTERFACE_ELEMENT > ELEMENT* oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::control_element_pt () inline
Pointer to control element (just under the symmetry line near the bubble tip, so the bubble tip is located at s=[1.0,1.0] in this element.
     {
       return Control_element_pt;
     }
References oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Control_element_pt.
find_distance_to_free_surface()
template<class ELEMENT , class INTERFACE_ELEMENT > double oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::find_distance_to_free_surface (GeomObject *const & fs_geom_object_pt, Vector< double > & initial_zeta, const Vector< double > & spine_base, const Vector< double > & spine_end)
Recalculate the spine lengths after repositioning.
Calculate the distance from the spine base to the free surface, i.e. the spine height.
   {
     // Now we need to find the intersection points
     double lambda = 0.5;
     Vector<double> dx(2);
     Vector<double> new_free_x(2);
     DenseDoubleMatrix jacobian(2, 2, 0.0);
     Vector<double> spine_x(2);
     Vector<double> free_x(2);
     double maxres = 100.0;
     unsigned count = 0;
     // Let's Newton method it
     do
     {
       count++;
       // Find the spine's location
       for (unsigned i = 0; i < 2; ++i)
       {
         spine_x[i] = spine_base[i] + lambda * (spine_end[i] - spine_base[i]);
       }
       // Find the free_surface location
       fs_geom_object_pt->position(initial_zeta, free_x);
       for (unsigned i = 0; i < 2; ++i)
       {
         dx[i] = spine_x[i] - free_x[i];
       }
       // Calculate the entries of the jacobian matrix
       jacobian(0, 0) = (spine_end[0] - spine_base[0]);
       jacobian(1, 0) = (spine_end[1] - spine_base[1]);
       // Calculate the others by finite differences
       double FD_Jstep = 1.0e-6;
       double old_zeta = initial_zeta[0];
       initial_zeta[0] += FD_Jstep;
       fs_geom_object_pt->position(initial_zeta, new_free_x);
       for (unsigned i = 0; i < 2; ++i)
       {
         jacobian(i, 1) = (free_x[i] - new_free_x[i]) / FD_Jstep;
       }
       // Now let's solve the damn thing
       jacobian.solve(dx);
       lambda -= dx[0];
       initial_zeta[0] = old_zeta - dx[1];
       // How are we doing
       for (unsigned i = 0; i < 2; ++i)
       {
         spine_x[i] = spine_base[i] + lambda * (spine_end[i] - spine_base[i]);
       }
       fs_geom_object_pt->position(initial_zeta, free_x);
       for (unsigned i = 0; i < 2; ++i)
       {
         dx[i] = spine_x[i] - free_x[i];
       }
       maxres = std::fabs(dx[0]) > std::fabs(dx[1]) ? std::fabs(dx[0]) :
                                                      std::fabs(dx[1]);
       if (count > 100)
       {
         throw OomphLibError("Failed to converge after 100 steps",
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
     } while (maxres > 1.0e-8);
     oomph_info << "DONE " << initial_zeta[0] << std::endl;
     double spine_length = sqrt(pow((spine_base[0] - spine_end[0]), 2.0) +
                                pow((spine_base[1] - spine_end[1]), 2.0));
     return (lambda * spine_length); // Divided by spine length
   }
References boost::multiprecision::fabs(), i, lambda, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::oomph_info, oomph::GeomObject::position(), Eigen::ArrayBase< Derived >::pow(), oomph::DoubleMatrixBase::solve(), and sqrt().
initial_element_reorder()
template<class ELEMENT , class INTERFACE_ELEMENT > void oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::initial_element_reorder protected
Initial reordering elements of the elements – before the channel mesh is added. Vertical stacks of elements, each topped by their interface element – this is (currently) identical to the version in the SingleLayerSpineMesh but it's important that the element reordering is maintained in exactly this form for the rest of the mesh generation process to work properly. Therefore we keep a copy of the function in here.
Reorder elements: Vertical stacks of elements, each topped by their interface element – this is (currently) identical to the version in the SingleLayerSpineMesh but it's important that element reordering is maintained in exactly this form so to be on the safe side, we move the function in here.
   {
     unsigned Nx = this->Nx;
     unsigned Ny = this->Ny;
     // Find out how many elements there are
     unsigned long Nelement = this->nelement();
     // Find out how many fluid elements there are
     unsigned long Nfluid = Nx * Ny;
     // Create a dummy array of elements
     Vector<FiniteElement*> dummy;
     // Loop over the elements in horizontal order
     for (unsigned long j = 0; j < Nx; j++)
     {
       // Loop over the elements in lower layer vertically
       for (unsigned long i = 0; i < Ny; i++)
       {
         // Push back onto the new stack
         dummy.push_back(this->finite_element_pt(Nx * i + j));
       }
       // Push back the line element onto the stack
       dummy.push_back(this->finite_element_pt(Nfluid + j));
     }
     // Now copy the reordered elements into the element_pt
     for (unsigned long e = 0; e < Nelement; e++)
     {
       this->Element_pt[e] = dummy[e];
     }
   }
References e(), i, j, GlobalParameters::Nx, and GlobalParameters::Ny.
interface_element_pt()
template<class ELEMENT , class INTERFACE_ELEMENT > FiniteElement*& oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::interface_element_pt (const unsigned long & i) inline
Access functions for pointers to interface elements.
     {
       return Interface_element_pt[i];
     }
References i, and oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Interface_element_pt.
nbulk()
template<class ELEMENT , class INTERFACE_ELEMENT > unsigned long oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::nbulk () const inline
Number of elements in bulk.
     {
       return Bulk_element_pt.size();
     }
References oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Bulk_element_pt.
nfree_surface_spines()
template<class ELEMENT , class INTERFACE_ELEMENT > unsigned oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::nfree_surface_spines () inline
Number of free-surface spines (i.e. excluding the dummy spines in the channel region)
     {
       unsigned np = this->finite_element_pt(0)->nnode_1d();
       return 2 * (Nx1 + Nx2 + Nhalf) * (np - 1);
     }
References oomph::Mesh::finite_element_pt(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Nhalf, oomph::FiniteElement::nnode_1d(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Nx1, and oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Nx2.
ninterface_element()
template<class ELEMENT , class INTERFACE_ELEMENT > unsigned long oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::ninterface_element () const inline
Number of elements on interface.
     {
       return Interface_element_pt.size();
     }
References oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Interface_element_pt.
pin_all_spines()
template<class ELEMENT , class INTERFACE_ELEMENT > void oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::pin_all_spines () inline
Pin all spines so the mesh can be used for computation without free surfaces
     {
       unsigned n_spine = this->nspine();
       for (unsigned i = 0; i < n_spine; i++)
       {
         this->spine_pt(i)->spine_height_pt()->pin(0);
       }
     }
References i, oomph::SpineMesh::nspine(), oomph::Data::pin(), oomph::Spine::spine_height_pt(), and oomph::SpineMesh::spine_pt().
reposition_spines()
template<class ELEMENT , class INTERFACE_ELEMENT > void oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::reposition_spines (const double & zeta_lo_transition_start, const double & zeta_lo_transition_end, const double & zeta_up_transition_start, const double & zeta_up_transition_end)
Reposition the spines in response to changes in geometry.
Reposition the spines that emenate from the lower wall.
   {
     // Firstly create a geometric object of the free surface
     Mesh* fs_mesh_pt = new Mesh;
     this->template build_face_mesh<ELEMENT, FaceElementAsGeomObject>(
       4, fs_mesh_pt);
     // Loop over these new face elements and set the boundary number
     // of the bulk mesh
     unsigned n_face_element = fs_mesh_pt->nelement();
     // Loop over the elements
     for (unsigned e = 0; e < n_face_element; e++)
     {
       // Cast the element pointer to the correct thing!
       dynamic_cast<FaceElementAsGeomObject<ELEMENT>*>(fs_mesh_pt->element_pt(e))
         ->set_boundary_number_in_bulk_mesh(4);
     }
     // Now make a single geometric object that represents the collection of
     // geometric objects that form the boundary of the bulk mesh. Two
     // Eulerian coordinates, one intrinsic coordinate.
     MeshAsGeomObject* fs_geom_object_pt = new MeshAsGeomObject(fs_mesh_pt);
     // Length of deposited film region
     double llayer_lower = zeta_lo_transition_start - Zeta_start;
     double llayer_upper = zeta_up_transition_start - Zeta_start;
     // Length of transition region
     double d_lower = zeta_lo_transition_end - zeta_lo_transition_start;
     double d_upper = zeta_up_transition_end - zeta_up_transition_start;
     // Work out radius of circular cap from lower and upper wall
     Vector<double> r_wall_lo(2), r_wall_up(2);
     Vector<double> zeta(1), s_lo(1), s_up(1);
     GeomObject *lower_sub_geom_object_pt = 0, *upper_sub_geom_object_pt = 0;
     GeomObject* lower_transition_geom_object_pt = 0;
     GeomObject* upper_transition_geom_object_pt = 0;
     Vector<double> s_transition_lo(1), s_transition_up(1);
     Vector<double> spine_centre(2);
     // Get number of nodes along element edge
     unsigned np = this->finite_element_pt(0)->nnode_1d();
     // Calculate the centre for the spine nodes in the transition region
     {
       // Get the geometric objects on the walls at the start of the transition
       // region
       // Lower wall
       zeta[0] = zeta_lo_transition_start;
       Lower_wall_pt->locate_zeta(
         zeta, lower_transition_geom_object_pt, s_transition_lo);
       // Upper wall
       zeta[0] = zeta_up_transition_start;
       Upper_wall_pt->locate_zeta(
         zeta, upper_transition_geom_object_pt, s_transition_up);
       // Find the Eulerian coordinates of the walls at the transition region
       lower_transition_geom_object_pt->position(s_transition_lo, r_wall_lo);
       upper_transition_geom_object_pt->position(s_transition_up, r_wall_up);
       // Take the average of these positions to define the origin of the spines
       // in the transition region Horizontal position is always halfway
       spine_centre[0] = 0.5 * (r_wall_lo[0] + r_wall_up[0]);
       // Vertical Position is given by a specified fraction
       // between the upper and lower walls
       spine_centre[1] =
         r_wall_lo[1] + spine_centre_fraction() * (r_wall_up[1] - r_wall_lo[1]);
     }
     // Initialise number of elements in previous regions:
     unsigned n_prev_elements = 0;
     // Storage for the end of the spines
     Vector<double> spine_end(2);
     Vector<double> fs_zeta(1, 0.0);
     // Loop over elements in lower deposited film region
     // -------------------------------------------------
     {
       oomph_info << "LOWER FILM " << std::endl;
       // Increments in wall coordinate
       double dzeta_el = llayer_lower / double(Nx1);
       double dzeta_node = llayer_lower / double(Nx1 * (np - 1));
       // Loop over elements horizontally
       for (unsigned i = 0; i < Nx1; i++)
       {
         // Start of wall coordinate
         double zeta_lo = Zeta_start + double(i) * dzeta_el;
         // Work out element number in overall mesh
         unsigned e = n_prev_elements + i * (Nh + 1);
         // Get pointer to lower element
         FiniteElement* el_pt = this->finite_element_pt(e);
         // Loop over its nodes "horizontally"
         for (unsigned i1 = 0; i1 < (np - 1); i1++)
         {
           // Get spine node
           SpineNode* nod_pt = dynamic_cast<SpineNode*>(el_pt->node_pt(i1));
           // Get the Lagrangian coordinate in the Lower Wall
           zeta[0] = zeta_lo + double(i1) * dzeta_node;
           // Reset the boundary coordinate
           nod_pt->set_coordinates_on_boundary(0, zeta);
           // Get the geometric object and local coordinate
           Lower_wall_pt->locate_zeta(zeta, lower_sub_geom_object_pt, s_lo);
           // The local coordinate is a geometric parameter
           // This needs to be set (rather than added) because the
           // same spine may be visited more than once
           Vector<double> parameters(1, s_lo[0]);
           nod_pt->spine_pt()->set_geom_parameter(parameters);
           // The sub geom object is one (and only) geom object
           // for spine:
           Vector<GeomObject*> geom_object_pt(1);
           geom_object_pt[0] = lower_sub_geom_object_pt;
           // Pass geom object(s) to spine
           nod_pt->spine_pt()->set_geom_object_pt(geom_object_pt);
           // Get the wall position at the bottom of the spine
           lower_sub_geom_object_pt->position(s_lo, r_wall_lo);
           // The end of the spine is vertically above the base
           spine_end[0] = r_wall_lo[0];
           spine_end[1] = spine_centre[1];
           nod_pt->spine_pt()->height() = find_distance_to_free_surface(
             fs_geom_object_pt, fs_zeta, r_wall_lo, spine_end);
         }
       }
       // Increment number of previous elements
       n_prev_elements += Nx1 * (Nh + 1);
     }
     // Loop over elements in lower horizontal transition region
     // --------------------------------------------------------
     {
       oomph_info << "LOWER HORIZONTAL TRANSITION " << std::endl;
       // Increments in wall coordinate
       double dzeta_el = d_lower / double(Nx2);
       double dzeta_node = d_lower / double(Nx2 * (np - 1));
       // Loop over elements horizontally
       for (unsigned i = 0; i < Nx2; i++)
       {
         // Start of wall coordinate
         double zeta_lo = zeta_lo_transition_start + double(i) * dzeta_el;
         // Work out element number in overall mesh
         unsigned e = n_prev_elements + i * (Nh + 1);
         // Get pointer to element
         FiniteElement* el_pt = this->finite_element_pt(e);
         // Loop over its nodes
         for (unsigned i1 = 0; i1 < (np - 1); i1++)
         {
           // Get spine node
           SpineNode* nod_pt = dynamic_cast<SpineNode*>(el_pt->node_pt(i1));
           // Get the Lagrangian coordinate in the Lower Wall
           zeta[0] = zeta_lo + double(i1) * dzeta_node;
           // Reset the boundary coordinate
           nod_pt->set_coordinates_on_boundary(0, zeta);
           // Get the sub geometric object and local coordinate
           Lower_wall_pt->locate_zeta(zeta, lower_sub_geom_object_pt, s_lo);
           // Pass geometric parameter to the spine
           Vector<double> parameters(3);
           parameters[0] = s_lo[0];
           parameters[1] = s_transition_lo[0];
           parameters[2] = s_transition_up[0];
           nod_pt->spine_pt()->set_geom_parameter(parameters);
           // Lower sub geom object is one (and only) geom object
           // for spine:
           Vector<GeomObject*> geom_object_pt(3);
           geom_object_pt[0] = lower_sub_geom_object_pt;
           geom_object_pt[1] = lower_transition_geom_object_pt;
           geom_object_pt[2] = upper_transition_geom_object_pt;
           // Pass geom object(s) to spine
           nod_pt->spine_pt()->set_geom_object_pt(geom_object_pt);
           // Get position vector to wall
           lower_sub_geom_object_pt->position(s_lo, r_wall_lo);
           // The end of the spine is the spine centre,so the height is easy(ish)
           nod_pt->spine_pt()->height() = find_distance_to_free_surface(
             fs_geom_object_pt, fs_zeta, r_wall_lo, spine_centre);
         }
       }
       // Increment number of previous elements
       n_prev_elements += Nx2 * (Nh + 1);
     }
     // Loop over elements in lower vertical transition region
     // --------------------------------------------------------
     {
       oomph_info << "LOWER VERTICAL TRANSITION " << std::endl;
       for (unsigned i = 0; i < Nhalf; i++)
       {
         // Work out element number in overall mesh
         unsigned e = n_prev_elements + i * (Nh + 1);
         // Get pointer to element
         FiniteElement* el_pt = this->finite_element_pt(e);
         // Loop over its nodes
         for (unsigned i1 = 0; i1 < (np - 1); i1++)
         {
           // Get spine node
           // Note that I have to loop over the second row of nodes
           // because the first row are updated in region 6 and so
           // you get the wrong spines from them (doh!)
           SpineNode* nod_pt = dynamic_cast<SpineNode*>(el_pt->node_pt(np + i1));
           // Get position vectors to wall
           zeta[0] = zeta_lo_transition_end;
           // Get the sub geometric objects
           Lower_wall_pt->locate_zeta(zeta, lower_sub_geom_object_pt, s_lo);
           zeta[0] = zeta_up_transition_end;
           Upper_wall_pt->locate_zeta(zeta, upper_sub_geom_object_pt, s_up);
           lower_sub_geom_object_pt->position(s_lo, r_wall_lo);
           upper_sub_geom_object_pt->position(s_up, r_wall_up);
           // Set vertical fraction
           double vertical_fraction =
             (double(i) + double(i1) / double(np - 1)) / double(2.0 * Nhalf);
           // Add the geometric parameters in order
           Vector<double> parameters(5);
           parameters[0] = s_lo[0];
           parameters[1] = s_up[0];
           parameters[2] = vertical_fraction;
           parameters[3] = s_transition_lo[0];
           parameters[4] = s_transition_up[0];
           nod_pt->spine_pt()->set_geom_parameter(parameters);
           // Origin of spine
           Vector<double> S0(2);
           S0[0] =
             r_wall_lo[0] + vertical_fraction * (r_wall_up[0] - r_wall_lo[0]);
           S0[1] =
             r_wall_lo[1] + vertical_fraction * (r_wall_up[1] - r_wall_lo[1]);
           // Lower and Upper wall sub geom objects affect  spine:
           Vector<GeomObject*> geom_object_pt(4);
           geom_object_pt[0] = lower_sub_geom_object_pt;
           geom_object_pt[1] = upper_sub_geom_object_pt;
           geom_object_pt[2] = lower_transition_geom_object_pt;
           geom_object_pt[3] = upper_transition_geom_object_pt;
           // Pass geom object(s) to spine
           nod_pt->spine_pt()->set_geom_object_pt(geom_object_pt);
           // Calculate the spine height
           nod_pt->spine_pt()->height() = find_distance_to_free_surface(
             fs_geom_object_pt, fs_zeta, S0, spine_centre);
         }
       }
       // Increment number of previous elements
       n_prev_elements += Nhalf * (Nh + 1);
     }
     // Loop over elements in upper vertical transition region
     // --------------------------------------------------------
     {
       oomph_info << "UPPER VERTICAL TRANSITION" << std::endl;
       for (unsigned i = 0; i < Nhalf; i++)
       {
         // Work out element number in overall mesh
         unsigned e = n_prev_elements + i * (Nh + 1);
         // Get pointer to element
         FiniteElement* el_pt = this->finite_element_pt(e);
         // Loop over its nodes
         for (unsigned i1 = 0; i1 < (np - 1); i1++)
         {
           // Get spine node
           // Note that I have to loop over the second row of nodes
           // because the first row are updated in region 6 and so
           // you get the wrong spines from them (doh!)
           SpineNode* nod_pt = dynamic_cast<SpineNode*>(el_pt->node_pt(np + i1));
           // Get position vectors to wall
           zeta[0] = zeta_lo_transition_end;
           // Get the sub geometric objects
           Lower_wall_pt->locate_zeta(zeta, lower_sub_geom_object_pt, s_lo);
           zeta[0] = zeta_up_transition_end;
           Upper_wall_pt->locate_zeta(zeta, upper_sub_geom_object_pt, s_up);
           lower_sub_geom_object_pt->position(s_lo, r_wall_lo);
           upper_sub_geom_object_pt->position(s_up, r_wall_up);
           // Set vertical fraction
           double vertical_fraction =
             0.5 +
             (double(i) + double(i1) / double(np - 1)) / double(2.0 * Nhalf);
           // Add the geometric parameters in order
           Vector<double> parameters(5);
           parameters[0] = s_lo[0];
           parameters[1] = s_up[0];
           parameters[2] = vertical_fraction;
           parameters[3] = s_transition_lo[0];
           parameters[4] = s_transition_up[0];
           nod_pt->spine_pt()->set_geom_parameter(parameters);
           // Origin of spine
           Vector<double> S0(2);
           S0[0] =
             r_wall_lo[0] + vertical_fraction * (r_wall_up[0] - r_wall_lo[0]);
           S0[1] =
             r_wall_lo[1] + vertical_fraction * (r_wall_up[1] - r_wall_lo[1]);
           // Lower and Upper wall sub geom objects affect  spine:
           Vector<GeomObject*> geom_object_pt(4);
           geom_object_pt[0] = lower_sub_geom_object_pt;
           geom_object_pt[1] = upper_sub_geom_object_pt;
           geom_object_pt[2] = lower_transition_geom_object_pt;
           geom_object_pt[3] = upper_transition_geom_object_pt;
           // Pass geom object(s) to spine
           nod_pt->spine_pt()->set_geom_object_pt(geom_object_pt);
           // Calculate the spine height
           nod_pt->spine_pt()->height() = find_distance_to_free_surface(
             fs_geom_object_pt, fs_zeta, S0, spine_centre);
         }
       }
       // Increment number of previous elements
       n_prev_elements += Nhalf * (Nh + 1);
     }
     // Loop over elements in upper horizontal transition region
     // --------------------------------------------------------
     {
       oomph_info << "UPPER HORIZONTAL TRANSITION " << std::endl;
       // Increments in wall coordinate
       double dzeta_el = d_upper / double(Nx2);
       double dzeta_node = d_upper / double(Nx2 * (np - 1));
       // Loop over elements horizontally
       for (unsigned i = 0; i < Nx2; i++)
       {
         // Start of wall coordinate
         double zeta_lo = zeta_up_transition_end - double(i) * dzeta_el;
         // Work out element number in overall mesh
         unsigned e = n_prev_elements + i * (Nh + 1);
         // Get pointer to element
         FiniteElement* el_pt = this->finite_element_pt(e);
         // Loop over its nodes
         for (unsigned i1 = 0; i1 < (np - 1); i1++)
         {
           // Get spine node (same comment)
           SpineNode* nod_pt = dynamic_cast<SpineNode*>(el_pt->node_pt(np + i1));
           // Get the Lagrangian coordinate in the Lower Wall
           zeta[0] = zeta_lo - double(i1) * dzeta_node;
           // Reset the boundary coordinate
           el_pt->node_pt(i1)->set_coordinates_on_boundary(2, zeta);
           // Get the sub geometric object and local coordinate
           Upper_wall_pt->locate_zeta(zeta, upper_sub_geom_object_pt, s_up);
           // Pass geometric parameter to the spine
           Vector<double> parameters(3);
           parameters[0] = s_up[0];
           parameters[1] = s_transition_lo[0];
           parameters[2] = s_transition_up[0];
           nod_pt->spine_pt()->set_geom_parameter(parameters);
           // Lower sub geom object is one (and only) geom object
           // for spine:
           Vector<GeomObject*> geom_object_pt(3);
           geom_object_pt[0] = upper_sub_geom_object_pt;
           geom_object_pt[1] = lower_transition_geom_object_pt;
           geom_object_pt[2] = upper_transition_geom_object_pt;
           // Pass geom object(s) to spine
           nod_pt->spine_pt()->set_geom_object_pt(geom_object_pt);
           // Get position vector to wall
           upper_sub_geom_object_pt->position(s_up, r_wall_up);
           // Find spine height
           nod_pt->spine_pt()->height() = find_distance_to_free_surface(
             fs_geom_object_pt, fs_zeta, r_wall_up, spine_centre);
         }
       }
       // Increment number of previous elements
       n_prev_elements += Nx2 * (Nh + 1);
     }
     // Loop over elements in upper deposited film region
     // -------------------------------------------------
     {
       oomph_info << "UPPER THIN FILM" << std::endl;
       // Increments in wall coordinate
       double dzeta_el = llayer_upper / double(Nx1);
       double dzeta_node = llayer_upper / double(Nx1 * (np - 1));
       // Loop over elements horizontally
       for (unsigned i = 0; i < Nx1; i++)
       {
         // Start of wall coordinate
         double zeta_lo = zeta_up_transition_start - double(i) * dzeta_el;
         // Work out element number in overall mesh
         unsigned e = n_prev_elements + i * (Nh + 1);
         // Get pointer to element
         FiniteElement* el_pt = this->finite_element_pt(e);
         // Loop over its nodes "horizontally"
         for (unsigned i1 = 0; i1 < (np - 1); i1++)
         {
           // Get spine node
           SpineNode* nod_pt = dynamic_cast<SpineNode*>(el_pt->node_pt(i1));
           // Get the Lagrangian coordinate in the Upper wall
           zeta[0] = zeta_lo - double(i1) * dzeta_node;
           // Reset coordinate on boundary
           nod_pt->set_coordinates_on_boundary(2, zeta);
           // Get the geometric object and local coordinate
           Upper_wall_pt->locate_zeta(zeta, upper_sub_geom_object_pt, s_up);
           // The local coordinate is a geometric parameter
           Vector<double> parameters(1, s_up[0]);
           nod_pt->spine_pt()->set_geom_parameter(parameters);
           // upper sub geom object is one (and only) geom object
           // for spine:
           Vector<GeomObject*> geom_object_pt(1);
           geom_object_pt[0] = upper_sub_geom_object_pt;
           // Pass geom object(s) to spine
           nod_pt->spine_pt()->set_geom_object_pt(geom_object_pt);
           // Get the wall position at the bottom of the spine
           upper_sub_geom_object_pt->position(s_up, r_wall_up);
           spine_end[0] = r_wall_up[0];
           spine_end[1] = spine_centre[1];
           // Find the new spine height
           nod_pt->spine_pt()->height() = find_distance_to_free_surface(
             fs_geom_object_pt, fs_zeta, r_wall_up, spine_end);
         }
       }
       // Increment number of previous elements
       n_prev_elements += Nx1 * (Nh + 1);
     }
     // Additional mesh
     {
       unsigned e = n_prev_elements;
       // Get pointer to node
       SpineNode* nod_pt = this->element_node_pt(e, 0);
       // Need to get the local coordinates for the upper and lower wall
       zeta[0] = zeta_lo_transition_end;
       // Get the sub geometric objects
       Lower_wall_pt->locate_zeta(zeta, lower_sub_geom_object_pt, s_lo);
       zeta[0] = zeta_up_transition_end;
       Upper_wall_pt->locate_zeta(zeta, upper_sub_geom_object_pt, s_up);
       lower_sub_geom_object_pt->position(s_lo, r_wall_lo);
       upper_sub_geom_object_pt->position(s_up, r_wall_up);
       // Pass additional data to spine
       Vector<double> parameters(2);
       parameters[0] = s_lo[0];
       parameters[1] = s_up[0];
       nod_pt->spine_pt()->set_geom_parameter(parameters);
       // Lower and upper wall sub geom objects affect update
       // for spine:
       Vector<GeomObject*> geom_object_pt(2);
       geom_object_pt[0] = lower_sub_geom_object_pt;
       geom_object_pt[1] = upper_sub_geom_object_pt;
       // Pass geom object(s) to spine
       nod_pt->spine_pt()->set_geom_object_pt(geom_object_pt);
       // LOOP OVER OTHER SPINES
       //----------------------
       // Now loop over the elements horizontally
       for (unsigned long j = 0; j < Nx3; j++)
       {
         unsigned e = n_prev_elements + j;
         // Loop over the nodes in the elements horizontally, ignoring
         // the first column
         for (unsigned l2 = 0; l2 < np; l2++)
         {
           // Get pointer to node at the base of the spine
           SpineNode* nod_pt = this->element_node_pt(e, l2);
           // Increment in wall coordinate
           double dzeta_el_lower =
             (Zeta_end - zeta_lo_transition_end) / double(Nx3);
           double dzeta_nod_lower = dzeta_el_lower / double(np - 1);
           double dzeta_el_upper =
             (Zeta_end - zeta_up_transition_end) / double(Nx3);
           double dzeta_nod_upper = dzeta_el_upper / double(np - 1);
           // Get wall coordinate
           zeta[0] =
             zeta_lo_transition_end + j * dzeta_el_lower + l2 * dzeta_nod_lower;
           // Reset the boundary coordinate
           nod_pt->set_coordinates_on_boundary(0, zeta);
           // Get the sub geometric objects
           Lower_wall_pt->locate_zeta(zeta, lower_sub_geom_object_pt, s_lo);
           zeta[0] =
             zeta_up_transition_end + j * dzeta_el_upper + l2 * dzeta_nod_upper;
           // Reset the upper boundary coordinate
           this->element_node_pt(e + Nx3 * (2 * Nhalf - 1), np * (np - 1) + l2)
             ->set_coordinates_on_boundary(2, zeta);
           Upper_wall_pt->locate_zeta(zeta, upper_sub_geom_object_pt, s_up);
           lower_sub_geom_object_pt->position(s_lo, r_wall_lo);
           upper_sub_geom_object_pt->position(s_up, r_wall_up);
           // Add geometric parameters to spine
           Vector<double> parameters(2);
           parameters[0] = s_lo[0];
           parameters[1] = s_up[0];
           nod_pt->spine_pt()->set_geom_parameter(parameters);
           // Lower and upper sub geom objects affect update
           // for spine:
           Vector<GeomObject*> geom_object_pt(2);
           geom_object_pt[0] = lower_sub_geom_object_pt;
           geom_object_pt[1] = upper_sub_geom_object_pt;
           // Pass geom object(s) to spine
           nod_pt->spine_pt()->set_geom_object_pt(geom_object_pt);
         }
       }
     }
     // Clean up all the memory
     // Can delete the Geometric object
     delete fs_geom_object_pt;
     // Need to be careful with the FaceMesh, because we can't delete the nodes
     // Loop
     for (unsigned e = n_face_element; e > 0; e--)
     {
       delete fs_mesh_pt->element_pt(e - 1);
       fs_mesh_pt->element_pt(e - 1) = 0;
     }
     // Now clear all element and node storage (should maybe fine-grain this)
     fs_mesh_pt->flush_element_and_node_storage();
     // Finally delete the mesh
     delete fs_mesh_pt;
   }
References e(), oomph::Mesh::element_pt(), oomph::Mesh::flush_element_and_node_storage(), oomph::Spine::height(), i, j, Global_Physical_Variables::Lower_wall_pt, oomph::Mesh::nelement(), oomph::oomph_info, oomph::GeomObject::position(), GlobalParameters::S0, oomph::Node::set_coordinates_on_boundary(), oomph::Spine::set_geom_object_pt(), oomph::Spine::set_geom_parameter(), oomph::SpineNode::spine_pt(), Global_Physical_Variables::Upper_wall_pt, and Eigen::zeta().
set_spine_centre_fraction_pt()
template<class ELEMENT , class INTERFACE_ELEMENT > void oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::set_spine_centre_fraction_pt (double *const & fraction_pt) inline
Set the pointer to the spine centre's vertial fraction.
     {
       Spine_centre_fraction_pt = fraction_pt;
     }
References oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Spine_centre_fraction_pt.
spine_centre_fraction()
template<class ELEMENT , class INTERFACE_ELEMENT > double oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_centre_fraction () const inline
Read the value of the spine centre's vertical fraction.
     {
       return *Spine_centre_fraction_pt;
     }
References oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Spine_centre_fraction_pt.
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_horizontal_transition_lower(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_horizontal_transition_upper(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_vertical_transition_lower(), and oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_vertical_transition_upper().
spine_node_update()
template<class ELEMENT , class INTERFACE_ELEMENT > void oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update (SpineNode * spine_node_pt) inline virtual
General node update function implements pure virtual function defined in SpineMesh base class and performs specific update actions, depending on the node update fct id stored for each node.
Reimplemented from oomph::SingleLayerSpineMesh< ELEMENT >.
     {
       unsigned id = spine_node_pt->node_update_fct_id();
       switch (id)
       {
         case 0:
           spine_node_update_film_lower(spine_node_pt);
           break;
         case 1:
           spine_node_update_horizontal_transition_lower(spine_node_pt);
           break;
         case 2:
           spine_node_update_vertical_transition_lower(spine_node_pt);
           break;
         case 3:
           spine_node_update_vertical_transition_upper(spine_node_pt);
           break;
         case 4:
           spine_node_update_horizontal_transition_upper(spine_node_pt);
           break;
         case 5:
           spine_node_update_film_upper(spine_node_pt);
           break;
         case 6:
           spine_node_update_channel(spine_node_pt);
           break;
         default:
           std::ostringstream error_message;
           error_message << "Incorrect spine update id " << id << std::endl;
           throw OomphLibError(error_message.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
       }
     }
References oomph::SpineNode::node_update_fct_id(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_channel(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_film_lower(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_film_upper(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_horizontal_transition_lower(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_horizontal_transition_upper(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_vertical_transition_lower(), and oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_vertical_transition_upper().
spine_node_update_channel()
template<class ELEMENT , class INTERFACE_ELEMENT > void oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_channel (SpineNode * spine_node_pt) inline protected
Update function for the nodes in the channel region ahead of the finger tip: Nodes are evenly distributed along vertical lines between the top and bottom walls
     {
       // Get fraction along the spine
       double w = spine_node_pt->fraction();
       // Get upper and lower local coordinates
       Vector<double> s_lo(1), s_up(1);
       s_lo[0] = spine_node_pt->spine_pt()->geom_parameter(0);
       s_up[0] = spine_node_pt->spine_pt()->geom_parameter(1);
       // Get position vector to lower wall
       Vector<double> r_lo(2), r_up(2);
       spine_node_pt->spine_pt()->geom_object_pt(0)->position(s_lo, r_lo);
       spine_node_pt->spine_pt()->geom_object_pt(1)->position(s_up, r_up);
       // Update the nodal position
       spine_node_pt->x(0) = r_lo[0] + w * (r_up[0] - r_lo[0]);
       spine_node_pt->x(1) = r_lo[1] + w * (r_up[1] - r_lo[1]);
     }
References oomph::SpineNode::fraction(), oomph::Spine::geom_object_pt(), oomph::Spine::geom_parameter(), oomph::GeomObject::position(), oomph::SpineNode::spine_pt(), w, and oomph::Node::x().
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update().
spine_node_update_film_lower()
template<class ELEMENT , class INTERFACE_ELEMENT > void oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_film_lower (SpineNode * spine_node_pt) inline protected
Update function for the deposited film region in the lower part of the domain: Vertical spines
     {
       // Get fraction along the spine
       double w = spine_node_pt->fraction();
       // Get spine height
       double h = spine_node_pt->h();
       // Get wall coordinate
       Vector<double> s_lo(1);
       s_lo[0] = spine_node_pt->spine_pt()->geom_parameter(0);
       // Get position vector to wall
       Vector<double> r_wall_lo(2);
       spine_node_pt->spine_pt()->geom_object_pt(0)->position(s_lo, r_wall_lo);
       // Update the nodal position
       spine_node_pt->x(0) = r_wall_lo[0];
       spine_node_pt->x(1) = r_wall_lo[1] + w * h;
     }
References oomph::SpineNode::fraction(), oomph::Spine::geom_object_pt(), oomph::Spine::geom_parameter(), oomph::SpineNode::h(), oomph::GeomObject::position(), oomph::SpineNode::spine_pt(), w, and oomph::Node::x().
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update().
spine_node_update_film_upper()
template<class ELEMENT , class INTERFACE_ELEMENT > void oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_film_upper (SpineNode * spine_node_pt) inline protected
Update function for the deposited film region in the upper part of the domain: Vertical spines
     {
       // Get fraction along the spine
       double w = spine_node_pt->fraction();
       // Get spine height
       double h = spine_node_pt->h();
       // Get wall coordinate
       Vector<double> s_up(1);
       s_up[0] = spine_node_pt->spine_pt()->geom_parameter(0);
       // Get position vector to wall
       Vector<double> r_wall_up(2);
       spine_node_pt->spine_pt()->geom_object_pt(0)->position(s_up, r_wall_up);
       // Update the nodal position
       spine_node_pt->x(0) = r_wall_up[0];
       spine_node_pt->x(1) = r_wall_up[1] - w * h;
     }
References oomph::SpineNode::fraction(), oomph::Spine::geom_object_pt(), oomph::Spine::geom_parameter(), oomph::SpineNode::h(), oomph::GeomObject::position(), oomph::SpineNode::spine_pt(), w, and oomph::Node::x().
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update().
spine_node_update_horizontal_transition_lower()
template<class ELEMENT , class INTERFACE_ELEMENT > void oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_horizontal_transition_lower (SpineNode * spine_node_pt) inline protected
Update function for the horizontal transitition region in the lower part of the domain: Spine points from wall to origin
     {
       // Get fraction along the spine
       double w = spine_node_pt->fraction();
       // Get spine height
       double h = spine_node_pt->h();
       // Get wall coordinate
       Vector<double> s_lo(1);
       s_lo[0] = spine_node_pt->spine_pt()->geom_parameter(0);
       // Get position vector to wall
       Vector<double> r_wall_lo(2);
       spine_node_pt->spine_pt()->geom_object_pt(0)->position(s_lo, r_wall_lo);
       // Get the spine centre
       Vector<double> s_transition_lo(1), s_transition_up(1);
       s_transition_lo[0] = spine_node_pt->spine_pt()->geom_parameter(1);
       s_transition_up[0] = spine_node_pt->spine_pt()->geom_parameter(2);
       Vector<double> r_transition_lo(2), r_transition_up(2);
       spine_node_pt->spine_pt()->geom_object_pt(1)->position(s_transition_lo,
                                                              r_transition_lo);
       spine_node_pt->spine_pt()->geom_object_pt(2)->position(s_transition_up,
                                                              r_transition_up);
       Vector<double> spine_centre(2);
       // Horizontal position is always halfway between the walls
       spine_centre[0] = 0.5 * (r_transition_lo[0] + r_transition_up[0]);
       // Vertical spine centre is given by fraction between the walls
       spine_centre[1] =
         r_transition_lo[1] +
         spine_centre_fraction() * (r_transition_up[1] - r_transition_lo[1]);
       // Get vector twoards spine origin
       Vector<double> N(2);
       N[0] = spine_centre[0] - r_wall_lo[0];
       N[1] = spine_centre[1] - r_wall_lo[1];
       double inv_length = 1.0 / sqrt(N[0] * N[0] + N[1] * N[1]);
       // Update the nodal position
       spine_node_pt->x(0) = r_wall_lo[0] + w * h * N[0] * inv_length;
       spine_node_pt->x(1) = r_wall_lo[1] + w * h * N[1] * inv_length;
     }
References oomph::SpineNode::fraction(), oomph::Spine::geom_object_pt(), oomph::Spine::geom_parameter(), oomph::SpineNode::h(), N, oomph::GeomObject::position(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_centre_fraction(), oomph::SpineNode::spine_pt(), sqrt(), w, and oomph::Node::x().
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update().
spine_node_update_horizontal_transition_upper()
template<class ELEMENT , class INTERFACE_ELEMENT > void oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_horizontal_transition_upper (SpineNode * spine_node_pt) inline protected
Update function for the horizontal transitition region in the upper part of the domain: Spine points towards origin
     {
       // Get fraction along the spine
       double w = spine_node_pt->fraction();
       // Get spine height
       double h = spine_node_pt->h();
       // Get wall coordinate
       Vector<double> s_up(1);
       s_up[0] = spine_node_pt->spine_pt()->geom_parameter(0);
       // Get position vector to wall
       Vector<double> r_wall_up(2);
       spine_node_pt->spine_pt()->geom_object_pt(0)->position(s_up, r_wall_up);
       // Get the spine centre
       Vector<double> s_transition_lo(1), s_transition_up(1);
       s_transition_lo[0] = spine_node_pt->spine_pt()->geom_parameter(1);
       s_transition_up[0] = spine_node_pt->spine_pt()->geom_parameter(2);
       Vector<double> r_transition_lo(2), r_transition_up(2);
       spine_node_pt->spine_pt()->geom_object_pt(1)->position(s_transition_lo,
                                                              r_transition_lo);
       spine_node_pt->spine_pt()->geom_object_pt(2)->position(s_transition_up,
                                                              r_transition_up);
       Vector<double> spine_centre(2);
       // Horizontal position is always halfway between the walls
       spine_centre[0] = 0.5 * (r_transition_lo[0] + r_transition_up[0]);
       // Vertical spine centre is given by fraction between the walls
       spine_centre[1] =
         r_transition_lo[1] +
         spine_centre_fraction() * (r_transition_up[1] - r_transition_lo[1]);
       // Get vector towards origin
       Vector<double> N(2);
       N[0] = spine_centre[0] - r_wall_up[0];
       N[1] = spine_centre[1] - r_wall_up[1];
       double inv_length = 1.0 / sqrt(N[0] * N[0] + N[1] * N[1]);
       // Update the nodal position
       spine_node_pt->x(0) = r_wall_up[0] + w * h * N[0] * inv_length;
       spine_node_pt->x(1) = r_wall_up[1] + w * h * N[1] * inv_length;
     }
References oomph::SpineNode::fraction(), oomph::Spine::geom_object_pt(), oomph::Spine::geom_parameter(), oomph::SpineNode::h(), N, oomph::GeomObject::position(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_centre_fraction(), oomph::SpineNode::spine_pt(), sqrt(), w, and oomph::Node::x().
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update().
spine_node_update_vertical_transition_lower()
template<class ELEMENT , class INTERFACE_ELEMENT > void oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_vertical_transition_lower (SpineNode * spine_node_pt) inline protected
Update function for the vertical transitition region in the lower part of the domain: Spine points to origin
     {
       // Get fraction along the spine
       double w = spine_node_pt->fraction();
       // Get spine height
       double h = spine_node_pt->h();
       // Get local coordinates
       Vector<double> s_lo(1), s_up(1);
       s_lo[0] = spine_node_pt->spine_pt()->geom_parameter(0);
       s_up[0] = spine_node_pt->spine_pt()->geom_parameter(1);
       // Get position vector to wall
       Vector<double> r_lo(2), r_up(2);
       spine_node_pt->spine_pt()->geom_object_pt(0)->position(s_lo, r_lo);
       spine_node_pt->spine_pt()->geom_object_pt(1)->position(s_up, r_up);
       // Get fraction along vertical line across
       double vertical_fraction = spine_node_pt->spine_pt()->geom_parameter(2);
       // Origin of spine
       Vector<double> S0(2);
       S0[0] = r_lo[0] + vertical_fraction * (r_up[0] - r_lo[0]);
       S0[1] = r_lo[1] + vertical_fraction * (r_up[1] - r_lo[1]);
       // Get the spine centre
       Vector<double> s_transition_lo(1), s_transition_up(1);
       s_transition_lo[0] = spine_node_pt->spine_pt()->geom_parameter(3);
       s_transition_up[0] = spine_node_pt->spine_pt()->geom_parameter(4);
       Vector<double> r_transition_lo(2), r_transition_up(2);
       spine_node_pt->spine_pt()->geom_object_pt(2)->position(s_transition_lo,
                                                              r_transition_lo);
       spine_node_pt->spine_pt()->geom_object_pt(3)->position(s_transition_up,
                                                              r_transition_up);
       Vector<double> spine_centre(2);
       // Horizontal position is always halfway between the walls
       spine_centre[0] = 0.5 * (r_transition_lo[0] + r_transition_up[0]);
       // Vertical spine centre is given by fraction between the walls
       spine_centre[1] =
         r_transition_lo[1] +
         spine_centre_fraction() * (r_transition_up[1] - r_transition_lo[1]);
       // Get vector towards origin
       Vector<double> N(2);
       N[0] = spine_centre[0] - S0[0];
       N[1] = spine_centre[1] - S0[1];
       double inv_length = 1.0 / sqrt(N[0] * N[0] + N[1] * N[1]);
       // Update the nodal position
       spine_node_pt->x(0) = S0[0] + w * h * N[0] * inv_length;
       spine_node_pt->x(1) = S0[1] + w * h * N[1] * inv_length;
     }
References oomph::SpineNode::fraction(), oomph::Spine::geom_object_pt(), oomph::Spine::geom_parameter(), oomph::SpineNode::h(), N, oomph::GeomObject::position(), GlobalParameters::S0, oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_centre_fraction(), oomph::SpineNode::spine_pt(), sqrt(), w, and oomph::Node::x().
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update().
spine_node_update_vertical_transition_upper()
template<class ELEMENT , class INTERFACE_ELEMENT > void oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update_vertical_transition_upper (SpineNode * spine_node_pt) inline protected
Update function for the vertical transitition region in the upper part of the domain: Spine points to origin
     {
       // Get fraction along the spine
       double w = spine_node_pt->fraction();
       // Get spine height
       double h = spine_node_pt->h();
       // Get local coordinates
       Vector<double> s_lo(1), s_up(1);
       s_lo[0] = spine_node_pt->spine_pt()->geom_parameter(0);
       s_up[0] = spine_node_pt->spine_pt()->geom_parameter(1);
       // Get position vector to wall
       Vector<double> r_lo(2), r_up(2);
       spine_node_pt->spine_pt()->geom_object_pt(0)->position(s_lo, r_lo);
       spine_node_pt->spine_pt()->geom_object_pt(1)->position(s_up, r_up);
       // Get fraction along vertical line across
       double vertical_fraction = spine_node_pt->spine_pt()->geom_parameter(2);
       // Origin of spine
       Vector<double> S0(2);
       S0[0] = r_lo[0] + vertical_fraction * (r_up[0] - r_lo[0]);
       S0[1] = r_lo[1] + vertical_fraction * (r_up[1] - r_lo[1]);
       // Get the spine centre
       Vector<double> s_transition_lo(1), s_transition_up(1);
       s_transition_lo[0] = spine_node_pt->spine_pt()->geom_parameter(3);
       s_transition_up[0] = spine_node_pt->spine_pt()->geom_parameter(4);
       Vector<double> r_transition_lo(2), r_transition_up(2);
       spine_node_pt->spine_pt()->geom_object_pt(2)->position(s_transition_lo,
                                                              r_transition_lo);
       spine_node_pt->spine_pt()->geom_object_pt(3)->position(s_transition_up,
                                                              r_transition_up);
       Vector<double> spine_centre(2);
       // Horizontal position is always halfway between the walls
       spine_centre[0] = 0.5 * (r_transition_lo[0] + r_transition_up[0]);
       // Vertical spine centre is given by fraction between the walls
       spine_centre[1] =
         r_transition_lo[1] +
         spine_centre_fraction() * (r_transition_up[1] - r_transition_lo[1]);
       // Get vector towards origin
       Vector<double> N(2);
       N[0] = spine_centre[0] - S0[0];
       N[1] = spine_centre[1] - S0[1];
       double inv_length = 1.0 / sqrt(N[0] * N[0] + N[1] * N[1]);
       // Update the nodal position
       spine_node_pt->x(0) = S0[0] + w * h * N[0] * inv_length;
       spine_node_pt->x(1) = S0[1] + w * h * N[1] * inv_length;
     }
References oomph::SpineNode::fraction(), oomph::Spine::geom_object_pt(), oomph::Spine::geom_parameter(), oomph::SpineNode::h(), N, oomph::GeomObject::position(), GlobalParameters::S0, oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_centre_fraction(), oomph::SpineNode::spine_pt(), sqrt(), w, and oomph::Node::x().
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update().
Member Data Documentation
Bulk_element_pt
template<class ELEMENT , class INTERFACE_ELEMENT > Vector<FiniteElement*> oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Bulk_element_pt protected
Vector of pointers to element in the fluid layer.
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::bulk_element_pt(), and oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::nbulk().
Control_element_pt
template<class ELEMENT , class INTERFACE_ELEMENT > ELEMENT* oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Control_element_pt protected
Pointer to control element (just under the symmetry line near the bubble tip; the bubble tip is located at s=[1.0,1.0] in this element
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::control_element_pt().
Default_spine_centre_fraction
template<class ELEMENT , class INTERFACE_ELEMENT > double oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Default_spine_centre_fraction protected
Default spine fraction.
H
template<class ELEMENT , class INTERFACE_ELEMENT > double oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::H protected
Thickness of deposited film.
Interface_element_pt
template<class ELEMENT , class INTERFACE_ELEMENT > Vector<FiniteElement*> oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Interface_element_pt protected
Vector of pointers to interface elements.
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::interface_element_pt(), and oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::ninterface_element().
Lower_wall_pt
template<class ELEMENT , class INTERFACE_ELEMENT > GeomObject* oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Lower_wall_pt protected
Pointer to geometric object that represents the lower wall.
Nh
template<class ELEMENT , class INTERFACE_ELEMENT > unsigned oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Nh protected
Number of elements across the deposited film.
Nhalf
template<class ELEMENT , class INTERFACE_ELEMENT > unsigned oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Nhalf protected
Number of elements in vertical transition region (there are twice as many elements across the channel)
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::nfree_surface_spines().
Nx1
template<class ELEMENT , class INTERFACE_ELEMENT > unsigned oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Nx1 protected
Number of elements along wall in deposited film region.
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::nfree_surface_spines().
Nx2
template<class ELEMENT , class INTERFACE_ELEMENT > unsigned oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Nx2 protected
Number of elements along wall in horizontal transition region.
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::nfree_surface_spines().
Nx3
template<class ELEMENT , class INTERFACE_ELEMENT > unsigned oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Nx3 protected
Number of elements along wall in channel region.
Spine_centre_fraction_pt
template<class ELEMENT , class INTERFACE_ELEMENT > double* oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Spine_centre_fraction_pt protected
Pointer to vertical fraction of the spine centre.
Referenced by oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::set_spine_centre_fraction_pt(), and oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::spine_centre_fraction().
Upper_wall_pt
template<class ELEMENT , class INTERFACE_ELEMENT > GeomObject* oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Upper_wall_pt protected
Pointer to geometric object that represents the upper wall.
Zeta_end
template<class ELEMENT , class INTERFACE_ELEMENT > double oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Zeta_end protected
Wall coordinate of end of liquid filled region (inflow)
Zeta_start
template<class ELEMENT , class INTERFACE_ELEMENT > double oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Zeta_start protected
Start coordinate on wall.
Zeta_transition_end
template<class ELEMENT , class INTERFACE_ELEMENT > double oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Zeta_transition_end protected
Wall coordinate of end of transition region.
Zeta_transition_start
template<class ELEMENT , class INTERFACE_ELEMENT > double oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::Zeta_transition_start protected
Wall coordinate of start of the transition region.
The documentation for this class was generated from the following files:
bretherton_spine_mesh.template.h
bretherton_spine_mesh.template.cc