MercuryDPM: Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ > Class Template Reference
Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ > Class Template Reference
Sparse linear algebra » Reference » SparseCholesky_Module
#include <SimplicialCholesky.h>
Public Types
enum { UpLo = UpLo_ }
typedef MatrixType_ MatrixType
typedef SimplicialCholeskyBase< SimplicialCholesky > Base
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
typedef MatrixType::StorageIndex StorageIndex
typedef SparseMatrix< Scalar, ColMajor, StorageIndex > CholMatrixType
typedef Matrix< Scalar, Dynamic, 1 > VectorType
typedef internal::traits< SimplicialLDLT< MatrixType, UpLo > > LDLTTraits
typedef internal::traits< SimplicialLLT< MatrixType, UpLo > > LLTTraits
Public Types inherited from Eigen::SimplicialCholeskyBase< SimplicialCholesky< MatrixType_, UpLo_, Ordering_ > >
enum
enum
typedef internal::traits< SimplicialCholesky< MatrixType_, UpLo_, Ordering_ > >::MatrixType MatrixType
typedef internal::traits< SimplicialCholesky< MatrixType_, UpLo_, Ordering_ > >::OrderingType OrderingType
typedef MatrixType::Scalar Scalar
typedef MatrixType::RealScalar RealScalar
typedef internal::traits< SimplicialCholesky< MatrixType_, UpLo_, Ordering_ > >::DiagonalScalar DiagonalScalar
typedef MatrixType::StorageIndex StorageIndex
typedef SparseMatrix< Scalar, ColMajor, StorageIndex > CholMatrixType
typedef CholMatrixType const * ConstCholMatrixPtr
typedef Matrix< Scalar, Dynamic, 1 > VectorType
typedef Matrix< StorageIndex, Dynamic, 1 > VectorI
Public Member Functions
SimplicialCholesky ()
SimplicialCholesky (const MatrixType &matrix)
SimplicialCholesky & setMode (SimplicialCholeskyMode mode)
const VectorType vectorD () const
const CholMatrixType rawMatrix () const
SimplicialCholesky & compute (const MatrixType &matrix)
void analyzePattern (const MatrixType &a)
void factorize (const MatrixType &a)
template<typename Rhs , typename Dest >
void _solve_impl (const MatrixBase< Rhs > &b, MatrixBase< Dest > &dest) const
template<typename Rhs , typename Dest >
void _solve_impl (const SparseMatrixBase< Rhs > &b, SparseMatrixBase< Dest > &dest) const
Scalar determinant () const
Public Member Functions inherited from Eigen::SimplicialCholeskyBase< SimplicialCholesky< MatrixType_, UpLo_, Ordering_ > >
SimplicialCholeskyBase ()
SimplicialCholeskyBase (const MatrixType &matrix)
~SimplicialCholeskyBase ()
SimplicialCholesky< MatrixType_, UpLo_, Ordering_ > & derived ()
const SimplicialCholesky< MatrixType_, UpLo_, Ordering_ > & derived () const
SimplicialCholesky< MatrixType_, UpLo_, Ordering_ > & derived ()
const SimplicialCholesky< MatrixType_, UpLo_, Ordering_ > & derived () const
Index cols () const
Index rows () const
ComputationInfo info () const
Reports whether previous computation was successful.
const PermutationMatrix< Dynamic, Dynamic, StorageIndex > & permutationP () const
const PermutationMatrix< Dynamic, Dynamic, StorageIndex > & permutationPinv () const
SimplicialCholesky< MatrixType_, UpLo_, Ordering_ > & setShift (const DiagonalScalar &offset, const DiagonalScalar &scale=1)
void dumpMemory (Stream &s)
void _solve_impl (const MatrixBase< Rhs > &b, MatrixBase< Dest > &dest) const
void _solve_impl (const SparseMatrixBase< Rhs > &b, SparseMatrixBase< Dest > &dest) const
Public Member Functions inherited from Eigen::SparseSolverBase< SimplicialCholesky< MatrixType_, UpLo_, Ordering_ > >
SparseSolverBase ()
SparseSolverBase (SparseSolverBase &&other)
~SparseSolverBase ()
SimplicialCholesky< MatrixType_, UpLo_, Ordering_ > & derived ()
const SimplicialCholesky< MatrixType_, UpLo_, Ordering_ > & derived () const
const Solve< SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >, Rhs > solve (const MatrixBase< Rhs > &b) const
const Solve< SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >, Rhs > solve (const SparseMatrixBase< Rhs > &b) const
void _solve_impl (const SparseMatrixBase< Rhs > &b, SparseMatrixBase< Dest > &dest) const
Protected Attributes
bool m_LDLT
Protected Attributes inherited from Eigen::SimplicialCholeskyBase< SimplicialCholesky< MatrixType_, UpLo_, Ordering_ > >
ComputationInfo m_info
bool m_factorizationIsOk
bool m_analysisIsOk
CholMatrixType m_matrix
VectorType m_diag
VectorI m_parent
VectorI m_workSpace
PermutationMatrix< Dynamic, Dynamic, StorageIndex > m_P
PermutationMatrix< Dynamic, Dynamic, StorageIndex > m_Pinv
DiagonalScalar m_shiftOffset
DiagonalScalar m_shiftScale
Protected Attributes inherited from Eigen::SparseSolverBase< SimplicialCholesky< MatrixType_, UpLo_, Ordering_ > >
bool m_isInitialized
Additional Inherited Members
Protected Member Functions inherited from Eigen::SimplicialCholeskyBase< SimplicialCholesky< MatrixType_, UpLo_, Ordering_ > >
void compute (const MatrixType &matrix)
void factorize (const MatrixType &a)
void factorize_preordered (const CholMatrixType &a)
void analyzePattern (const MatrixType &a)
void analyzePattern_preordered (const CholMatrixType &a, bool doLDLT)
void ordering (const MatrixType &a, ConstCholMatrixPtr &pmat, CholMatrixType &ap)
DiagonalScalar getDiag (Scalar x)
Scalar getSymm (Scalar x)
Detailed Description
template<typename MatrixType_, int UpLo_, typename Ordering_>
class Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >
Deprecated:
use SimplicialLDLT or class SimplicialLLT
See also
class SimplicialLDLT, class SimplicialLLT
Member Typedef Documentation
Base
template<typename MatrixType_ , int UpLo_, typename Ordering_ > typedef SimplicialCholeskyBase<SimplicialCholesky> Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::Base
CholMatrixType
template<typename MatrixType_ , int UpLo_, typename Ordering_ > typedef SparseMatrix<Scalar, ColMajor, StorageIndex> Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::CholMatrixType
LDLTTraits
template<typename MatrixType_ , int UpLo_, typename Ordering_ > typedef internal::traits<SimplicialLDLT<MatrixType, UpLo> > Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::LDLTTraits
LLTTraits
template<typename MatrixType_ , int UpLo_, typename Ordering_ > typedef internal::traits<SimplicialLLT<MatrixType, UpLo> > Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::LLTTraits
MatrixType
template<typename MatrixType_ , int UpLo_, typename Ordering_ > typedef MatrixType_ Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::MatrixType
RealScalar
template<typename MatrixType_ , int UpLo_, typename Ordering_ > typedef MatrixType::RealScalar Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::RealScalar
Scalar
template<typename MatrixType_ , int UpLo_, typename Ordering_ > typedef MatrixType::Scalar Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::Scalar
StorageIndex
template<typename MatrixType_ , int UpLo_, typename Ordering_ > typedef MatrixType::StorageIndex Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::StorageIndex
VectorType
template<typename MatrixType_ , int UpLo_, typename Ordering_ > typedef Matrix<Scalar, Dynamic, 1> Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::VectorType
Member Enumeration Documentation
anonymous enum
template<typename MatrixType_ , int UpLo_, typename Ordering_ > anonymous enum
Enumerator
UpLo
 { UpLo = UpLo_ };
Constructor & Destructor Documentation
SimplicialCholesky() [1/2]
template<typename MatrixType_ , int UpLo_, typename Ordering_ > Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::SimplicialCholesky () inline
 : Base(), m_LDLT(true) {}
SimplicialCholesky() [2/2]
template<typename MatrixType_ , int UpLo_, typename Ordering_ > Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::SimplicialCholesky (const MatrixType & matrix) inline explicit
 : Base(), m_LDLT(true) { compute(matrix); }
References Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::compute(), and matrix().
Member Function Documentation
_solve_impl() [1/2]
template<typename MatrixType_ , int UpLo_, typename Ordering_ > template<typename Rhs , typename Dest > void Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::_solve_impl (const MatrixBase< Rhs > & b, MatrixBase< Dest > & dest) const inline
{
     eigen_assert(Base::m_factorizationIsOk &&
                  "The decomposition is not in a valid state for solving, you must first call either compute() or "
                  "symbolic()/numeric()");
     eigen_assert(Base::m_matrix.rows() == b.rows());
     if (Base::m_info != Success) return;
     if (Base::m_P.size() > 0)
       dest = Base::m_P * b;
     else
       dest = b;
     if (Base::m_matrix.nonZeros() > 0)  // otherwise L==I
     {
       if (m_LDLT)
         LDLTTraits::getL(Base::m_matrix).solveInPlace(dest);
       else
         LLTTraits::getL(Base::m_matrix).solveInPlace(dest);
     }
     if (Base::m_diag.size() > 0) dest = Base::m_diag.real().asDiagonal().inverse() * dest;
     if (Base::m_matrix.nonZeros() > 0)  // otherwise I==I
     {
       if (m_LDLT)
         LDLTTraits::getU(Base::m_matrix).solveInPlace(dest);
       else
         LLTTraits::getU(Base::m_matrix).solveInPlace(dest);
     }
     if (Base::m_P.size() > 0) dest = Base::m_Pinv * dest;
   }
References b, eigen_assert, Eigen::SimplicialCholeskyBase< Derived >::m_diag, Eigen::SimplicialCholeskyBase< Derived >::m_factorizationIsOk, Eigen::SimplicialCholeskyBase< Derived >::m_info, Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::m_LDLT, Eigen::SimplicialCholeskyBase< Derived >::m_matrix, Eigen::SimplicialCholeskyBase< Derived >::m_P, Eigen::SimplicialCholeskyBase< Derived >::m_Pinv, Eigen::SimplicialCholeskyBase< SimplicialCholesky< MatrixType_, UpLo_, Ordering_ > >::rows(), size, and Eigen::Success.
_solve_impl() [2/2]
template<typename MatrixType_ , int UpLo_, typename Ordering_ > template<typename Rhs , typename Dest > void Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::_solve_impl (const SparseMatrixBase< Rhs > & b, SparseMatrixBase< Dest > & dest) const inline
{
     internal::solve_sparse_through_dense_panels(*this, b, dest);
   }
References b, and Eigen::internal::solve_sparse_through_dense_panels().
analyzePattern()
template<typename MatrixType_ , int UpLo_, typename Ordering_ > void Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::analyzePattern (const MatrixType & a) inline
Performs a symbolic decomposition on the sparcity of matrix.
This function is particularly useful when solving for several problems having the same structure.
See also
factorize()
{
     if (m_LDLT)
       Base::template analyzePattern<true, false>(a);
     else
       Base::template analyzePattern<false, false>(a);
   }
References a, and Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::m_LDLT.
compute()
template<typename MatrixType_ , int UpLo_, typename Ordering_ > SimplicialCholesky& Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::compute (const MatrixType & matrix) inline
Computes the sparse Cholesky decomposition of matrix
{
     if (m_LDLT)
       Base::template compute<true, false>(matrix);
     else
       Base::template compute<false, false>(matrix);
     return *this;
   }
References Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::m_LDLT, and matrix().
Referenced by Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::SimplicialCholesky().
determinant()
template<typename MatrixType_ , int UpLo_, typename Ordering_ > Scalar Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::determinant () const inline
{
     if (m_LDLT) {
       return Base::m_diag.prod();
     } else {
       Scalar detL = Diagonal<const CholMatrixType>(Base::m_matrix).prod();
       return numext::abs2(detL);
     }
   }
References Eigen::numext::abs2(), Eigen::SimplicialCholeskyBase< Derived >::m_diag, Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::m_LDLT, and Eigen::SimplicialCholeskyBase< Derived >::m_matrix.
factorize()
template<typename MatrixType_ , int UpLo_, typename Ordering_ > void Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::factorize (const MatrixType & a) inline
Performs a numeric decomposition of matrix
The given matrix must has the same sparcity than the matrix on which the symbolic decomposition has been performed.
See also
analyzePattern()
{
     if (m_LDLT)
       Base::template factorize<true, false>(a);
     else
       Base::template factorize<false, false>(a);
   }
References a, and Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::m_LDLT.
rawMatrix()
template<typename MatrixType_ , int UpLo_, typename Ordering_ > const CholMatrixType Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::rawMatrix () const inline
{
     eigen_assert(Base::m_factorizationIsOk && "Simplicial Cholesky not factorized");
     return Base::m_matrix;
   }
References eigen_assert, Eigen::SimplicialCholeskyBase< Derived >::m_factorizationIsOk, and Eigen::SimplicialCholeskyBase< Derived >::m_matrix.
setMode()
template<typename MatrixType_ , int UpLo_, typename Ordering_ > SimplicialCholesky& Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::setMode (SimplicialCholeskyMode mode) inline
{
     switch (mode) {
       case SimplicialCholeskyLLT:
         m_LDLT = false;
         break;
       case SimplicialCholeskyLDLT:
         m_LDLT = true;
         break;
       default:
         break;
     }
     return *this;
   }
References Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::m_LDLT, Eigen::SimplicialCholeskyLDLT, and Eigen::SimplicialCholeskyLLT.
vectorD()
template<typename MatrixType_ , int UpLo_, typename Ordering_ > const VectorType Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::vectorD () const inline
{
     eigen_assert(Base::m_factorizationIsOk && "Simplicial Cholesky not factorized");
     return Base::m_diag;
   }
References eigen_assert, Eigen::SimplicialCholeskyBase< Derived >::m_diag, and Eigen::SimplicialCholeskyBase< Derived >::m_factorizationIsOk.
Member Data Documentation
m_LDLT
template<typename MatrixType_ , int UpLo_, typename Ordering_ > bool Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::m_LDLT protected
Referenced by Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::_solve_impl(), Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::analyzePattern(), Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::compute(), Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::determinant(), Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::factorize(), and Eigen::SimplicialCholesky< MatrixType_, UpLo_, Ordering_ >::setMode().
The documentation for this class was generated from the following file:
SimplicialCholesky.h