MercuryDPM: boost::multiprecision Namespace Reference
boost::multiprecision Namespace Reference
Functions
Real fabs (const Real &a)
Real fmax (const Real &a, const Real &b)
bool test_isMuchSmallerThan (const Real &a, const Real &b)
bool test_isApprox (const Real &a, const Real &b)
bool test_isApproxOrLessThan (const Real &a, const Real &b)
Real get_test_precision (const Real &)
Real test_relative_error (const Real &a, const Real &b)
Function Documentation
fabs()
Real boost::multiprecision::fabs (const Real & a)
 { return abs EIGEN_NOT_A_MACRO(a); }
References a, abs(), and EIGEN_NOT_A_MACRO.
Referenced by SYCL::abs(), HertzianBSHPInteractionTwoParticleElasticCollision::actionsAfterSolve(), T_protectiveWall::actionsAfterTimeStep(), ShearStage::actionsAfterTimeStep(), CFDDEMCoupleTest::actionsAfterTimeStep(), protectiveWall::actionsAfterTimeStep(), oomph::Problem::adapt(), oomph::TriangleMeshCurviLine::add_connection_point(), BendingCantileverProblem< ELEMENT >::apply_boundary_conditions(), NavierStokesProblem< ELEMENT >::apply_boundary_conditions(), oomph::Problem::arc_length_step_solve_helper(), oomph::TetMeshBase::assess_mesh_quality(), CRBond_Bessel::bessik01a(), CRBond_Bessel::bessikv(), CRBond_Bessel::bessjy01a(), CRBond_Bessel::bessjyna(), CRBond_Bessel::bessjyv(), oomph::BlackBoxFDNewtonSolver::black_box_fd_newton_solve(), oomph::HelmholtzMGPreconditioner< DIM >::block_preconditioner_self_test(), oomph::CircularCylindricalShellMesh< ELEMENT >::build_mesh(), oomph::FishMesh< ELEMENT >::build_mesh(), CFDDEMCoupleTest::CalcPhiPAndFz(), oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_cutoff_viscosity(), oomph::IsotropicStrainEnergyFunctionConstitutiveLaw::calculate_second_piola_kirchhoff_stress(), oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_zero_shear_viscosity(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::check_integrity(), oomph::RefineableQElement< 3 >::check_integrity(), oomph::RefineableQElement< 1 >::check_integrity(), oomph::RefineableQElement< 2 >::check_integrity(), oomph::FiniteElement::check_jacobian(), check_locate_zeta(), oomph::TreeBasedRefineableMeshBase::complete_hanging_nodes(), ContactProblem< ELEMENT >::complete_problem_setup(), oomph::HelmholtzBCElementBase< ELEMENT >::compute_contribution_to_fourier_components(), oomph::BiharmonicEquations< DIM >::compute_error(), oomph::HelmholtzDtNBoundaryElement< ELEMENT >::compute_gamma_contribution(), oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::compute_gamma_contribution(), oomph::QSUPGAdvectionDiffusionElement< DIM, NNODE_1D >::compute_stabilisation_parameter(), PSD::computeD50(), CFDDEMCoupleTest::computeExternalForces(), ChuteWithPeriodicInflow::computeInternalForces(), BaseCluster::computeInternalStructure(), ScrewsymmetricIntersectionOfWalls::computeNormalRadialDeltaN(), ClosedCSCWalls::continueSolve(), contraction_batch(), contraction_both_transposed(), contraction_lhs_transposed(), contraction_rhs_transposed(), oomph::StefanBoltzmannRadiationBase::contribution_to_stefan_boltzmann_radiation(), oomph::LinearisedAxisymPoroelasticBJS_FSIElement< FLUID_BULK_ELEMENT, POROELASTICITY_BULK_ELEMENT >::contribution_to_total_porous_flux(), PSD::convertPdfPhiToPdfMeter(), PSDContinuous::convertSubtractiveToCumulative(), BendingCantileverProblem< ELEMENT >::create_constraint_elements(), Chute::createBottom(), InfiniteWall::createVTK(), InterfaceProblem< ELEMENT, TIMESTEPPER >::deform_free_surface(), TwoLayerInterfaceProblem< ELEMENT >::deform_interface(), oomph::TPVDElement< DIM, NNODE_1D >::describe_local_dofs(), oomph::SolidHelpers::doc_2D_principal_stress(), oomph::Problem::doc_errors(), oomph::OcTree::doc_face_neighbours(), oomph::BinaryTree::doc_neighbours(), oomph::QuadTree::doc_neighbours(), ContactProblem< ELEMENT >::doc_solution(), StefanBoltzmannProblem< ELEMENT >::doc_solution(), AxisymmetricVibratingShellProblem< ELEMENT >::doc_solution(), VibratingShellProblem< ELEMENT >::doc_solution(), oomph::OcTree::doc_true_edge_neighbours(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::drag_force(), oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::dviscosity_dinvariant(), UnsteadyHeatProblem< ELEMENT >::enforce_time_periodic_boundary_conditions(), oomph::DenseLU::factorise(), oomph::NavierStokesSpaceTimeTractionElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction(), oomph::NavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::fill_in_generic_residual_contribution_fluid_traction(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::find_distance_to_free_surface(), MembraneDemo::fixMembraneEdges(), MembraneSelfTest::fixMembraneEdges(), oomph::FullCircleMesh< ELEMENT >::FullCircleMesh(), oomph::BermudezPMLMappingAndTransformedCoordinate::gamma(), GlobalParameters::TestPMLMapping::gamma(), oomph::BermudezPMLMapping::gamma(), oomph::ContinuousBermudezPMLMapping::gamma(), CRBond_Bessel::gamma(), oomph::GMRES< MATRIX >::generate_plane_rotation(), oomph::AugmentedProblemGMRES::generate_plane_rotation(), oomph::GMRESBlockPreconditioner::generate_plane_rotation(), oomph::ComplexGMRES< MATRIX >::generate_plane_rotation(), oomph::HelmholtzGMRESMG< MATRIX >::generate_plane_rotation(), oomph::CRDoubleMatrixHelpers::gershgorin_eigenvalue_estimate(), oomph::Problem::get_all_error_estimates(), oomph::NavierStokesSurfaceDragTorqueElement< ELEMENT >::get_drag_and_torque(), oomph::Problem::get_hessian_vector_products(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_kinetic_energy_flux(), oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::get_node_at_local_coordinate(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::get_node_at_local_coordinate(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::get_node_at_local_coordinate(), oomph::QElement< 1, NNODE_1D >::get_node_at_local_coordinate(), oomph::QElement< 2, NNODE_1D >::get_node_at_local_coordinate(), oomph::QElement< 3, NNODE_1D >::get_node_at_local_coordinate(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_rate_of_traction_work(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_rate_of_traction_work_components(), oomph::SegregatableFSIProblem::get_solid_change(), oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::get_volume_flux(), oomph::NavierStokesSurfacePowerElement< ELEMENT >::get_volume_flux(), get_Z2_flux(), BaseParticle::getDisplacement2(), NurbsSurface::getDistance(), HorizontalScrew::getDistanceAndNormal(), Coil::getDistanceAndNormal(), ParabolaChute::getDistanceAndNormal(), SineWall::getDistanceAndNormal(), TriangleWall::getDistanceAndNormal(), VChute::getDistanceAndNormal(), TriangulatedWall::Face::getDistanceAndNormal(), Screw::getDistanceAndNormalLabCoordinates(), CGCoordinates::X::getLength(), CGCoordinates::Y::getLength(), CGCoordinates::Z::getLength(), BaseWall::getLinePlaneIntersect(), Time2Finish::getTime2Finish(), TriangleMeshWall::getVolumeTetrahedron(), oomph::Orthpoly::gl_nodes(), oomph::Orthpoly::gll_nodes(), oomph::Problem::globally_convergent_line_search(), oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation(), oomph::CRDoubleMatrix::inf_norm(), oomph::CRDoubleMatrixHelpers::inf_norm(), oomph::IntersectionChecker::intersects(), isEqual(), CFDDEMCoupleTest::itterateL(), oomph::MinModLimiter::limit(), oomph::BlackBoxFDNewtonSolver::line_search(), oomph::FSIHermiteBeamElement::locate_zeta(), oomph::FiniteElement::locate_zeta(), main(), oomph::CCDoubleMatrix::matrix_reduction(), oomph::CRDoubleMatrix::matrix_reduction(), oomph::DenseDoubleMatrix::matrix_reduction(), oomph::DoubleVector::max(), oomph::MinModLimiter::minmod(), oomph::MinModLimiter::minmodB(), CRBond_Bessel::msta1(), CRBond_Bessel::msta2(), oomph::Problem::newton_solve_continuation(), oomph::TetMeshBase::nregion_element(), oomph::DGEulerFaceElement< ELEMENT >::numerical_flux(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::oc_hang_helper(), oomph::OneDimensionalLegendreDShape< NNODE_1D >::OneDimensionalLegendreDShape(), oomph::OneDimensionalLegendreShape< NNODE_1D >::OneDimensionalLegendreShape(), oomph::OneDLegendreDShapeParam::OneDLegendreDShapeParam(), oomph::OneDLegendreShapeParam::OneDLegendreShapeParam(), oomph::ClampedHermiteShellBoundaryConditionElement::output(), output(), oomph::StefanBoltzmannUnsteadyHeatFluxElement< ELEMENT >::output_stefan_boltzmann_radiation(), oomph::Problem::p_adapt(), oomph::Legendre_functions_helper::plgndr1(), oomph::Legendre_functions_helper::plgndr2(), oomph::SegregatableFSIProblem::pointwise_aitken_extrapolate(), GeneralCircle::position(), oomph::GMRESBlockPreconditioner::preconditioner_solve(), ClosedCSCWalls::printTime(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::quad_hang_helper(), oomph::QuarterTubeMesh< ELEMENT >::QuarterTubeMesh(), FileReader::read(), DPMBase::readParAndIniFiles(), oomph::RefineableNavierStokesSpaceTimeTractionElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction(), oomph::RefineableNavierStokesMixedOrderSpaceTimeTractionElement< ELEMENT >::refineable_fill_in_generic_residual_contribution_fluid_traction(), oomph::TetMeshBase::region_element_pt(), oomph::AugmentedBlockFoldLinearSolver::resolve(), oomph::AugmentedBlockPitchForkLinearSolver::resolve(), Detail::round(), NavierStokesProblem< ELEMENT >::run_natural_continuation(), oomph::SegregatableFSIProblem::segregated_solve(), oomph::FiniteElement::self_test(), InsertionBoundary::setPSD(), LevelSetWall::setShapeCylinder(), oomph::AlgebraicCollapsibleChannelMesh< ELEMENT >::setup_algebraic_node_update(), oomph::AlgebraicFSIDrivenCavityMesh< ELEMENT >::setup_algebraic_node_update(), oomph::UnstructuredTwoDMeshGeometryBase::setup_boundary_coordinates(), oomph::FourierDecomposedHelmholtzDtNMesh< ELEMENT >::setup_gamma(), oomph::HelmholtzDtNMesh< ELEMENT >::setup_gamma(), TwoParticleCollisionInteraction::setupInitialConditions(), ArcWallUnitTest::setupInitialConditions(), Vec3D::signedSquare(), SolidBag::SolidBag(), oomph::AugmentedBlockFoldLinearSolver::solve(), oomph::BlockPitchForkLinearSolver::solve(), oomph::AugmentedBlockPitchForkLinearSolver::solve(), oomph::BlockHopfLinearSolver::solve(), oomph::HSL_MA42::solve_for_one_dof(), oomph::BlockHopfLinearSolver::solve_for_two_rhs(), oomph::GMRES< MATRIX >::solve_helper(), oomph::AugmentedProblemGMRES::solve_helper(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_lists(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_maps(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_two_arrays(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_two_vectors(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_vectors_of_pairs(), oomph::AxisymmetricNavierStokesEquations::strain_rate(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::strain_rate(), oomph::SphericalNavierStokesEquations::strain_rate(), test_no_out_of_bounds(), test_scalar(), test_sycl_contraction(), test_sycl_cumsum(), oomph::BermudezPMLMappingAndTransformedCoordinate::transformed_coordinate(), oomph::TubeMesh< ELEMENT >::TubeMesh(), oomph::SegregatableFSIProblem::under_relax_solid(), update_latest_fixed_point_iteration_guess_for_strain_rate(), oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::viscosity(), oomph::HerschelBulkleyPapRegConstitutiveEquation< DIM >::viscosity(), SolidProblem< ELEMENT_TYPE >::writeToVTK(), and Screw::writeVTK().
fmax()
Real boost::multiprecision::fmax (const Real & a, const Real & b)
{
   using std::max;
   return max(a, b);
 }
References a, b, and max.
get_test_precision()
Real boost::multiprecision::get_test_precision (const Real &)
 { return test_precision<Real>(); }
References Eigen::test_precision< Real >().
test_isApprox()
bool boost::multiprecision::test_isApprox (const Real & a, const Real & b) inline
 { return internal::isApprox(a, b, test_precision<Real>()); }
References a, b, Eigen::internal::isApprox(), and Eigen::test_precision< Real >().
test_isApproxOrLessThan()
bool boost::multiprecision::test_isApproxOrLessThan (const Real & a, const Real & b) inline
{
   return internal::isApproxOrLessThan(a, b, test_precision<Real>());
 }
References a, b, Eigen::internal::isApproxOrLessThan(), and Eigen::test_precision< Real >().
Referenced by qr(), qr_fixedsize(), and qr_kahan_matrix().
test_isMuchSmallerThan()
bool boost::multiprecision::test_isMuchSmallerThan (const Real & a, const Real & b) inline
{
   return internal::isMuchSmallerThan(a, b, test_precision<Real>());
 }
References a, b, Eigen::internal::isMuchSmallerThan(), and Eigen::test_precision< Real >().
test_relative_error()
Real boost::multiprecision::test_relative_error (const Real & a, const Real & b)
{
   using Eigen::numext::abs2;
   return sqrt(abs2<Real>(a - b) / Eigen::numext::mini<Real>(abs2(a), abs2(b)));
 }
References a, Eigen::numext::abs2(), b, and sqrt().