MercuryDPM: Eigen::DynamicSGroupFromTemplateArgs< Gen > Class Template Reference
Eigen::DynamicSGroupFromTemplateArgs< Gen > Class Template Reference
Dynamic symmetry group, initialized from template arguments.
#include <DynamicSymmetry.h>
Public Member Functions
DynamicSGroupFromTemplateArgs ()
DynamicSGroupFromTemplateArgs (DynamicSGroupFromTemplateArgs const &other)
DynamicSGroupFromTemplateArgs (DynamicSGroupFromTemplateArgs &&other)
DynamicSGroupFromTemplateArgs< Gen... > & operator= (const DynamicSGroupFromTemplateArgs< Gen... > &o)
DynamicSGroupFromTemplateArgs< Gen... > & operator= (DynamicSGroupFromTemplateArgs< Gen... > &&o)
Public Member Functions inherited from Eigen::DynamicSGroup
DynamicSGroup ()
DynamicSGroup (const DynamicSGroup &o)
DynamicSGroup (DynamicSGroup &&o)
DynamicSGroup & operator= (const DynamicSGroup &o)
DynamicSGroup & operator= (DynamicSGroup &&o)
void add (int one, int two, int flags=0)
template<typename Gen_ >
void add (Gen_)
void addSymmetry (int one, int two)
void addAntiSymmetry (int one, int two)
void addHermiticity (int one, int two)
void addAntiHermiticity (int one, int two)
template<typename Op , typename RV , typename Index , std::size_t N, typename... Args>
RV apply (const std::array< Index, N > &idx, RV initial, Args &&... args) const
template<typename Op , typename RV , typename Index , typename... Args>
RV apply (const std::vector< Index > &idx, RV initial, Args &&... args) const
int globalFlags () const
std::size_t size () const
template<typename Tensor_ , typename... IndexTypes>
internal::tensor_symmetry_value_setter< Tensor_, DynamicSGroup > operator() (Tensor_ &tensor, typename Tensor_::Index firstIndex, IndexTypes... otherIndices) const
template<typename Tensor_ >
internal::tensor_symmetry_value_setter< Tensor_, DynamicSGroup > operator() (Tensor_ &tensor, std::array< typename Tensor_::Index, Tensor_::NumIndices > const &indices) const
Private Member Functions
template<typename Gen1 , typename... GenNext>
void add_all (internal::type_list< Gen1, GenNext... >)
void add_all (internal::type_list<>)
Detailed Description
template<typename... Gen>
class Eigen::DynamicSGroupFromTemplateArgs< Gen >
Dynamic symmetry group, initialized from template arguments.
This class is a child class of DynamicSGroup. It uses the template arguments specified to initialize itself.
Constructor & Destructor Documentation
DynamicSGroupFromTemplateArgs() [1/3]
template<typename... Gen> Eigen::DynamicSGroupFromTemplateArgs< Gen >::DynamicSGroupFromTemplateArgs () inline
 : DynamicSGroup() { add_all(internal::type_list<Gen...>()); }
References Eigen::DynamicSGroupFromTemplateArgs< Gen >::add_all().
DynamicSGroupFromTemplateArgs() [2/3]
template<typename... Gen> Eigen::DynamicSGroupFromTemplateArgs< Gen >::DynamicSGroupFromTemplateArgs (DynamicSGroupFromTemplateArgs< Gen > const & other) inline
 : DynamicSGroup(other) {}
DynamicSGroupFromTemplateArgs() [3/3]
template<typename... Gen> Eigen::DynamicSGroupFromTemplateArgs< Gen >::DynamicSGroupFromTemplateArgs (DynamicSGroupFromTemplateArgs< Gen > && other) inline
 : DynamicSGroup(other) {}
Member Function Documentation
add_all() [1/2]
template<typename... Gen> template<typename Gen1 , typename... GenNext> void Eigen::DynamicSGroupFromTemplateArgs< Gen >::add_all (internal::type_list< Gen1, GenNext... >) inline private
{
     add(Gen1());
     add_all(internal::type_list<GenNext...>());
   }
References Eigen::DynamicSGroup::add().
Referenced by Eigen::DynamicSGroupFromTemplateArgs< Gen >::DynamicSGroupFromTemplateArgs().
add_all() [2/2]
template<typename... Gen> void Eigen::DynamicSGroupFromTemplateArgs< Gen >::add_all (internal::type_list<>) inline private
 {}
operator=() [1/2]
template<typename... Gen> DynamicSGroupFromTemplateArgs<Gen...>& Eigen::DynamicSGroupFromTemplateArgs< Gen >::operator= (const DynamicSGroupFromTemplateArgs< Gen... > & o) inline
{
     DynamicSGroup::operator=(o);
     return *this;
   }
References Eigen::DynamicSGroup::operator=().
operator=() [2/2]
template<typename... Gen> DynamicSGroupFromTemplateArgs<Gen...>& Eigen::DynamicSGroupFromTemplateArgs< Gen >::operator= (DynamicSGroupFromTemplateArgs< Gen... > && o) inline
{
     DynamicSGroup::operator=(o);
     return *this;
   }
References Eigen::DynamicSGroup::operator=().
The documentation for this class was generated from the following file:
DynamicSymmetry.h