MercuryDPM: Eigen::internal::imklfft::plan< double > Struct Reference
Eigen::internal::imklfft::plan< double > Struct Reference
#include <ei_imklfft_impl.h>
Public Types
typedef double scalar_type
typedef MKL_Complex16 complex_type
Public Member Functions
plan ()=default
void forward (complex_type *dst, complex_type *src, MKL_LONG nfft)
void inverse (complex_type *dst, complex_type *src, MKL_LONG nfft)
void forward (complex_type *dst, scalar_type *src, MKL_LONG nfft)
void inverse (scalar_type *dst, complex_type *src, MKL_LONG nfft)
void forward2 (complex_type *dst, complex_type *src, int n0, int n1)
void inverse2 (complex_type *dst, complex_type *src, int n0, int n1)
Public Attributes
std::shared_ptr< DFTI_DESCRIPTOR > m_plan
enum DFTI_CONFIG_VALUE precision = DFTI_DOUBLE
Member Typedef Documentation
complex_type
typedef MKL_Complex16 Eigen::internal::imklfft::plan< double >::complex_type
scalar_type
typedef double Eigen::internal::imklfft::plan< double >::scalar_type
Constructor & Destructor Documentation
plan()
Eigen::internal::imklfft::plan< double >::plan () default
Member Function Documentation
forward() [1/2]
void Eigen::internal::imklfft::plan< double >::forward (complex_type * dst, complex_type * src, MKL_LONG nfft) inline
{
     if (m_plan == 0) {
       configure_descriptor(m_plan, precision, DFTI_COMPLEX, 1, &nfft);
     }
     RUN_OR_ASSERT(DftiComputeForward(m_plan.get(), src, dst), "DftiComputeForward failed.")
   }
References Eigen::internal::imklfft::configure_descriptor(), and RUN_OR_ASSERT.
forward() [2/2]
void Eigen::internal::imklfft::plan< double >::forward (complex_type * dst, scalar_type * src, MKL_LONG nfft) inline
{
     if (m_plan == 0) {
       configure_descriptor(m_plan, precision, DFTI_REAL, 1, &nfft);
     }
     RUN_OR_ASSERT(DftiComputeForward(m_plan.get(), src, dst), "DftiComputeForward failed.")
   }
References Eigen::internal::imklfft::configure_descriptor(), and RUN_OR_ASSERT.
forward2()
void Eigen::internal::imklfft::plan< double >::forward2 (complex_type * dst, complex_type * src, int n0, int n1) inline
{
     if (m_plan == 0) {
       MKL_LONG sizes[2] = {n0, n1};
       configure_descriptor(m_plan, precision, DFTI_COMPLEX, 2, sizes);
     }
     RUN_OR_ASSERT(DftiComputeForward(m_plan.get(), src, dst), "DftiComputeForward failed.")
   }
References Eigen::internal::imklfft::configure_descriptor(), RUN_OR_ASSERT, and sizes.
inverse() [1/2]
void Eigen::internal::imklfft::plan< double >::inverse (complex_type * dst, complex_type * src, MKL_LONG nfft) inline
{
     if (m_plan == 0) {
       configure_descriptor(m_plan, precision, DFTI_COMPLEX, 1, &nfft);
     }
     RUN_OR_ASSERT(DftiComputeBackward(m_plan.get(), src, dst), "DftiComputeBackward failed.")
   }
References Eigen::internal::imklfft::configure_descriptor(), and RUN_OR_ASSERT.
inverse() [2/2]
void Eigen::internal::imklfft::plan< double >::inverse (scalar_type * dst, complex_type * src, MKL_LONG nfft) inline
{
     if (m_plan == 0) {
       configure_descriptor(m_plan, precision, DFTI_REAL, 1, &nfft);
     }
     RUN_OR_ASSERT(DftiComputeBackward(m_plan.get(), src, dst), "DftiComputeBackward failed.")
   }
References Eigen::internal::imklfft::configure_descriptor(), and RUN_OR_ASSERT.
inverse2()
void Eigen::internal::imklfft::plan< double >::inverse2 (complex_type * dst, complex_type * src, int n0, int n1) inline
{
     if (m_plan == 0) {
       MKL_LONG sizes[2] = {n0, n1};
       configure_descriptor(m_plan, precision, DFTI_COMPLEX, 2, sizes);
     }
     RUN_OR_ASSERT(DftiComputeBackward(m_plan.get(), src, dst), "DftiComputeBackward failed.")
   }
References Eigen::internal::imklfft::configure_descriptor(), RUN_OR_ASSERT, and sizes.
Member Data Documentation
m_plan
std::shared_ptr<DFTI_DESCRIPTOR> Eigen::internal::imklfft::plan< double >::m_plan
precision
enum DFTI_CONFIG_VALUE Eigen::internal::imklfft::plan< double >::precision = DFTI_DOUBLE
The documentation for this struct was generated from the following file:
ei_imklfft_impl.h