MercuryDPM: UndeformedLeaflet Class Reference
UndeformedLeaflet Class Reference
GeomObject: Undeformed straight, vertical leaflet.
Public Member Functions
UndeformedLeaflet (const double &x0)
Constructor: argument is the x-coordinate of the leaflet.
void position (const Vector< double > &zeta, Vector< double > &r) const
Position vector at Lagrangian coordinate zeta.
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
unsigned ngeom_data () const
Number of geometric Data in GeomObject: None.
UndeformedLeaflet (const double &x0)
Constructor: argument is the x-coordinate of the leaflet.
void position (const Vector< double > &zeta, Vector< double > &r) const
Position vector at Lagrangian coordinate zeta.
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
unsigned ngeom_data () const
Number of geometric Data in GeomObject: None.
UndeformedLeaflet (const double &x0)
Constructor: argument is the x-coordinate of the leaflet.
void position (const Vector< double > &zeta, Vector< double > &r) const
Position vector at Lagrangian coordinate zeta.
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
unsigned ngeom_data () const
Number of geometric Data in GeomObject: None.
UndeformedLeaflet (const double &x0)
Constructor: argument is the x-coordinate of the leaflet.
void position (const Vector< double > &zeta, Vector< double > &r) const
Position vector at Lagrangian coordinate zeta.
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
unsigned ngeom_data () const
Number of geometric Data in GeomObject: None.
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual Data * geom_data_pt (const unsigned &j)
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition_dt (const Vector< double > &zeta, const unsigned &j, Vector< double > &drdt)
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void locate_zeta (const Vector< double > &zeta, GeomObject *&sub_geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
Private Attributes
double X0
x position of the undeformed leaflet's origin.
Additional Inherited Members
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Detailed Description
GeomObject: Undeformed straight, vertical leaflet.
//////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////////
Constructor & Destructor Documentation
UndeformedLeaflet() [1/4]
UndeformedLeaflet::UndeformedLeaflet (const double & x0) inline
Constructor: argument is the x-coordinate of the leaflet.
                                     : GeomObject(1,2)
   {
    X0=x0;
   }
References Global::x0.
UndeformedLeaflet() [2/4]
UndeformedLeaflet::UndeformedLeaflet (const double & x0) inline
Constructor: argument is the x-coordinate of the leaflet.
                                     : GeomObject(1,2)
   {
    X0=x0;
   }
References Global::x0.
UndeformedLeaflet() [3/4]
UndeformedLeaflet::UndeformedLeaflet (const double & x0) inline
Constructor: argument is the x-coordinate of the leaflet.
                                     : GeomObject(1,2)
   {
    X0=x0;
   }
References Global::x0.
UndeformedLeaflet() [4/4]
UndeformedLeaflet::UndeformedLeaflet (const double & x0) inline
Constructor: argument is the x-coordinate of the leaflet.
                                     : GeomObject(1,2)
   {
    X0=x0;
   }
References Global::x0.
Member Function Documentation
d2position() [1/4]
void UndeformedLeaflet::d2position (const Vector< double > & zeta, Vector< double > & r, DenseMatrix< double > & drdzeta, RankThreeTensor< double > & ddrdzeta) const inline virtual
Posn vector and its 1st & 2nd derivatives w.r.t. to coordinates: \(\frac{dR_i}{d \zeta_\alpha}\) = drdzeta(alpha,i). \(\frac{d^2R_i}{d \zeta_\alpha d \zeta_\beta}\) = ddrdzeta(alpha,beta,i). Evaluated at current time.
Reimplemented from oomph::GeomObject.
   {
    // Position vector
    r[0] = X0;
    r[1] = zeta[0];
    // Tangent vector
    drdzeta(0,0)=0.0;
    drdzeta(0,1)=1.0;
    // Derivative of tangent vector
    ddrdzeta(0,0,0)=0.0;
    ddrdzeta(0,0,1)=0.0;
   } // end of d2position
References UniformPSDSelfTest::r, and Eigen::zeta().
d2position() [2/4]
void UndeformedLeaflet::d2position (const Vector< double > & zeta, Vector< double > & r, DenseMatrix< double > & drdzeta, RankThreeTensor< double > & ddrdzeta) const inline virtual
Posn vector and its 1st & 2nd derivatives w.r.t. to coordinates: \(\frac{dR_i}{d \zeta_\alpha}\) = drdzeta(alpha,i). \(\frac{d^2R_i}{d \zeta_\alpha d \zeta_\beta}\) = ddrdzeta(alpha,beta,i). Evaluated at current time.
Reimplemented from oomph::GeomObject.
   {
    // Position vector
    r[0] = X0;
    r[1] = zeta[0];
    // Tangent vector
    drdzeta(0,0)=0.0;
    drdzeta(0,1)=1.0;
    // Derivative of tangent vector
    ddrdzeta(0,0,0)=0.0;
    ddrdzeta(0,0,1)=0.0;
   } // end of d2position
References UniformPSDSelfTest::r, and Eigen::zeta().
d2position() [3/4]
void UndeformedLeaflet::d2position (const Vector< double > & zeta, Vector< double > & r, DenseMatrix< double > & drdzeta, RankThreeTensor< double > & ddrdzeta) const inline virtual
Posn vector and its 1st & 2nd derivatives w.r.t. to coordinates: \(\frac{dR_i}{d \zeta_\alpha}\) = drdzeta(alpha,i). \(\frac{d^2R_i}{d \zeta_\alpha d \zeta_\beta}\) = ddrdzeta(alpha,beta,i). Evaluated at current time.
Reimplemented from oomph::GeomObject.
   {
    // Position vector
    r[0] = X0;
    r[1] = zeta[0];
    // Tangent vector
    drdzeta(0,0)=0.0;
    drdzeta(0,1)=1.0;
    // Derivative of tangent vector
    ddrdzeta(0,0,0)=0.0;
    ddrdzeta(0,0,1)=0.0;
   } // end of d2position
References UniformPSDSelfTest::r, and Eigen::zeta().
d2position() [4/4]
void UndeformedLeaflet::d2position (const Vector< double > & zeta, Vector< double > & r, DenseMatrix< double > & drdzeta, RankThreeTensor< double > & ddrdzeta) const inline virtual
Posn vector and its 1st & 2nd derivatives w.r.t. to coordinates: \(\frac{dR_i}{d \zeta_\alpha}\) = drdzeta(alpha,i). \(\frac{d^2R_i}{d \zeta_\alpha d \zeta_\beta}\) = ddrdzeta(alpha,beta,i). Evaluated at current time.
Reimplemented from oomph::GeomObject.
   {
    // Position vector
    r[0] = X0;
    r[1] = zeta[0];
    // Tangent vector
    drdzeta(0,0)=0.0;
    drdzeta(0,1)=1.0;
    // Derivative of tangent vector
    ddrdzeta(0,0,0)=0.0;
    ddrdzeta(0,0,1)=0.0;
   } // end of d2position
References UniformPSDSelfTest::r, and Eigen::zeta().
ngeom_data() [1/4]
unsigned UndeformedLeaflet::ngeom_data () const inline virtual
Number of geometric Data in GeomObject: None.
Reimplemented from oomph::GeomObject.
 {return 0;}
ngeom_data() [2/4]
unsigned UndeformedLeaflet::ngeom_data () const inline virtual
Number of geometric Data in GeomObject: None.
Reimplemented from oomph::GeomObject.
 {return 0;}
ngeom_data() [3/4]
unsigned UndeformedLeaflet::ngeom_data () const inline virtual
Number of geometric Data in GeomObject: None.
Reimplemented from oomph::GeomObject.
 {return 0;}
ngeom_data() [4/4]
unsigned UndeformedLeaflet::ngeom_data () const inline virtual
Number of geometric Data in GeomObject: None.
Reimplemented from oomph::GeomObject.
 {return 0;}
position() [1/8]
void UndeformedLeaflet::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const inline virtual
Parametrised position on object: r(zeta). Evaluated at previous timestep. t=0: current time; t>0: previous timestep. Calls steady version.
Reimplemented from oomph::GeomObject.
   {
    // Use the steady version
    position(zeta,r);
   } // end of position
References UniformPSDSelfTest::r, and Eigen::zeta().
position() [2/8]
void UndeformedLeaflet::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const inline virtual
Parametrised position on object: r(zeta). Evaluated at previous timestep. t=0: current time; t>0: previous timestep. Calls steady version.
Reimplemented from oomph::GeomObject.
   {
    // Use the steady version
    position(zeta,r);
   } // end of position
References UniformPSDSelfTest::r, and Eigen::zeta().
position() [3/8]
void UndeformedLeaflet::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const inline virtual
Parametrised position on object: r(zeta). Evaluated at previous timestep. t=0: current time; t>0: previous timestep. Calls steady version.
Reimplemented from oomph::GeomObject.
   {
    // Use the steady version
    position(zeta,r);
   } // end of position
References UniformPSDSelfTest::r, and Eigen::zeta().
position() [4/8]
void UndeformedLeaflet::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const inline virtual
Parametrised position on object: r(zeta). Evaluated at previous timestep. t=0: current time; t>0: previous timestep. Calls steady version.
Reimplemented from oomph::GeomObject.
   {
    // Use the steady version
    position(zeta,r);
   } // end of position
References UniformPSDSelfTest::r, and Eigen::zeta().
position() [5/8]
void UndeformedLeaflet::position (const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position vector at Lagrangian coordinate zeta.
Implements oomph::GeomObject.
   {
    // Position Vector
    r[0] = X0;
    r[1] = zeta[0];
   }
References UniformPSDSelfTest::r, and Eigen::zeta().
position() [6/8]
void UndeformedLeaflet::position (const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position vector at Lagrangian coordinate zeta.
Implements oomph::GeomObject.
   {
    // Position Vector
    r[0] = X0;
    r[1] = zeta[0];
   }
References UniformPSDSelfTest::r, and Eigen::zeta().
position() [7/8]
void UndeformedLeaflet::position (const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position vector at Lagrangian coordinate zeta.
Implements oomph::GeomObject.
   {
    // Position Vector
    r[0] = X0;
    r[1] = zeta[0];
   }
References UniformPSDSelfTest::r, and Eigen::zeta().
position() [8/8]
void UndeformedLeaflet::position (const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position vector at Lagrangian coordinate zeta.
Implements oomph::GeomObject.
   {
    // Position Vector
    r[0] = X0;
    r[1] = zeta[0];
   }
References UniformPSDSelfTest::r, and Eigen::zeta().
Member Data Documentation
X0
double UndeformedLeaflet::X0 private
x position of the undeformed leaflet's origin.
The documentation for this class was generated from the following files:
interaction/fsi_channel_with_leaflet/fsi_channel_with_leaflet.cc
fsi_channel_with_leaflet_precond.cc