MercuryDPM: NumericalDiff.cpp File Reference
NumericalDiff.cpp File Reference
#include <stdio.h>
#include "main.h"
#include <unsupported/Eigen/NumericalDiff>
Classes
struct Functor< Scalar_, NX, NY >
struct my_functor
Functions
void test_forward ()
void test_central ()
EIGEN_DECLARE_TEST (NumericalDiff)
Function Documentation
EIGEN_DECLARE_TEST()
EIGEN_DECLARE_TEST (NumericalDiff)
{
   CALL_SUBTEST(test_forward());
   CALL_SUBTEST(test_central());
 }
References CALL_SUBTEST, test_central(), and test_forward().
test_central()
void test_central ()
                     {
   VectorXd x(3);
   MatrixXd jac(15, 3);
   MatrixXd actual_jac(15, 3);
   my_functor functor;
   x << 0.082, 1.13, 2.35;
   // real one
   functor.actual_df(x, actual_jac);
   // using NumericalDiff
   NumericalDiff<my_functor, Central> numDiff(functor);
   numDiff.df(x, jac);
   VERIFY_IS_APPROX(jac, actual_jac);
 }
References my_functor::actual_df(), Eigen::NumericalDiff< Functor_, mode >::df(), VERIFY_IS_APPROX, and plotDoE::x.
Referenced by EIGEN_DECLARE_TEST().
test_forward()
void test_forward ()
                     {
   VectorXd x(3);
   MatrixXd jac(15, 3);
   MatrixXd actual_jac(15, 3);
   my_functor functor;
   x << 0.082, 1.13, 2.35;
   // real one
   functor.actual_df(x, actual_jac);
   //    std::cout << actual_jac << std::endl << std::endl;
   // using NumericalDiff
   NumericalDiff<my_functor> numDiff(functor);
   numDiff.df(x, jac);
   //    std::cout << jac << std::endl;
   VERIFY_IS_APPROX(jac, actual_jac);
 }
References my_functor::actual_df(), Eigen::NumericalDiff< Functor_, mode >::df(), VERIFY_IS_APPROX, and plotDoE::x.
Referenced by EIGEN_DECLARE_TEST().