MercuryDPM: oomph::DoubleMatrixBase Class Reference
oomph::DoubleMatrixBase Class Reference abstract
#include <matrices.h>
Public Member Functions
DoubleMatrixBase ()
(Empty) constructor.
DoubleMatrixBase (const DoubleMatrixBase &matrix)=delete
Broken copy constructor.
void operator= (const DoubleMatrixBase &)=delete
Broken assignment operator.
virtual unsigned long nrow () const =0
Return the number of rows of the matrix.
virtual unsigned long ncol () const =0
Return the number of columns of the matrix.
virtual ~DoubleMatrixBase ()
virtual (empty) destructor
virtual double operator() (const unsigned long &i, const unsigned long &j) const =0
LinearSolver *& linear_solver_pt ()
Return a pointer to the linear solver object.
LinearSolver *const & linear_solver_pt () const
Return a pointer to the linear solver object (const version)
void solve (DoubleVector &rhs)
void solve (const DoubleVector &rhs, DoubleVector &soln)
void solve (Vector< double > &rhs)
void solve (const Vector< double > &rhs, Vector< double > &soln)
virtual void residual (const DoubleVector &x, const DoubleVector &b, DoubleVector &residual_)
Find the residual, i.e. r=b-Ax the residual.
virtual double max_residual (const DoubleVector &x, const DoubleVector &rhs)
virtual void multiply (const DoubleVector &x, DoubleVector &soln) const =0
Multiply the matrix by the vector x: soln=Ax.
virtual void multiply_transpose (const DoubleVector &x, DoubleVector &soln) const =0
Multiply the transposed matrix by the vector x: soln=A^T x.
Protected Attributes
LinearSolver * Linear_solver_pt
LinearSolver * Default_linear_solver_pt
Detailed Description
Abstract base class for matrices of doubles – adds abstract interfaces for solving, LU decomposition and multiplication by vectors.
Constructor & Destructor Documentation
DoubleMatrixBase() [1/2]
oomph::DoubleMatrixBase::DoubleMatrixBase () inline
(Empty) constructor.
 : Linear_solver_pt(0), Default_linear_solver_pt(0) {}
DoubleMatrixBase() [2/2]
oomph::DoubleMatrixBase::DoubleMatrixBase (const DoubleMatrixBase & matrix) delete
Broken copy constructor.
~DoubleMatrixBase()
virtual oomph::DoubleMatrixBase::~DoubleMatrixBase () inline virtual
virtual (empty) destructor
 {}
Member Function Documentation
linear_solver_pt() [1/2]
LinearSolver*& oomph::DoubleMatrixBase::linear_solver_pt () inline
Return a pointer to the linear solver object.
     {
       return Linear_solver_pt;
     }
References Linear_solver_pt.
Referenced by oomph::HelmholtzMGPreconditioner< DIM >::disable_smoother_and_superlu_doc_time(), and oomph::InterpolateFromIntegralPointsBase::pre_compute_ipt_to_node_mapping().
linear_solver_pt() [2/2]
LinearSolver* const& oomph::DoubleMatrixBase::linear_solver_pt () const inline
Return a pointer to the linear solver object (const version)
     {
       return Linear_solver_pt;
     }
References Linear_solver_pt.
max_residual()
virtual double oomph::DoubleMatrixBase::max_residual (const DoubleVector & x, const DoubleVector & rhs) inline virtual
Find the maximum residual r=b-Ax – generic version, can be overloaded for specific derived classes where the max. can be determined "on the fly"
     {
       DoubleVector res;
       residual(x, rhs, res);
       return res.max();
     }
References res, residual(), and plotDoE::x.
multiply()
virtual void oomph::DoubleMatrixBase::multiply (const DoubleVector & x, DoubleVector & soln) const pure virtual
Multiply the matrix by the vector x: soln=Ax.
Implemented in oomph::SumOfMatrices, oomph::CCDoubleMatrix, oomph::DenseDoubleMatrix, and oomph::CRDoubleMatrix.
Referenced by oomph::SumOfMatrices::multiply(), residual(), oomph::CG< MATRIX >::solve_helper(), oomph::BiCGStab< MATRIX >::solve_helper(), oomph::DampedJacobi< MATRIX >::solve_helper(), and oomph::GMRES< MATRIX >::solve_helper().
multiply_transpose()
virtual void oomph::DoubleMatrixBase::multiply_transpose (const DoubleVector & x, DoubleVector & soln) const pure virtual
Multiply the transposed matrix by the vector x: soln=A^T x.
Implemented in oomph::SumOfMatrices, oomph::CCDoubleMatrix, oomph::DenseDoubleMatrix, and oomph::CRDoubleMatrix.
ncol()
virtual unsigned long oomph::DoubleMatrixBase::ncol () const pure virtual
Return the number of columns of the matrix.
Implemented in oomph::SumOfMatrices, oomph::CCDoubleMatrix, oomph::DenseDoubleMatrix, and oomph::CRDoubleMatrix.
Referenced by oomph::SumOfMatrices::add_matrix(), oomph::MumpsSolver::factorise(), oomph::SuperLUSolver::factorise_serial(), oomph::SumOfMatrices::ncol(), oomph::HyprePreconditioner::setup(), oomph::TrilinosPreconditionerBase::setup(), oomph::DenseLU::solve(), oomph::SuperLUSolver::solve(), oomph::MumpsSolver::solve(), oomph::HypreSolver::solve(), oomph::TrilinosAztecOOSolver::solve(), oomph::CG< MATRIX >::solve_helper(), oomph::BiCGStab< MATRIX >::solve_helper(), and oomph::SuperLUSolver::solve_transpose().
nrow()
virtual unsigned long oomph::DoubleMatrixBase::nrow () const pure virtual
Return the number of rows of the matrix.
Implemented in oomph::SumOfMatrices, oomph::CCDoubleMatrix, oomph::DenseDoubleMatrix, and oomph::CRDoubleMatrix.
Referenced by oomph::SumOfMatrices::add_matrix(), oomph::DenseLU::factorise(), oomph::MumpsSolver::factorise(), oomph::SuperLUSolver::factorise_serial(), oomph::SumOfMatrices::nrow(), oomph::MatrixBasedDiagPreconditioner::setup(), oomph::HyprePreconditioner::setup(), oomph::IdentityPreconditioner::setup(), oomph::TrilinosPreconditionerBase::setup(), oomph::DenseLU::solve(), oomph::SuperLUSolver::solve(), oomph::MumpsSolver::solve(), oomph::HypreSolver::solve(), oomph::TrilinosAztecOOSolver::solve(), oomph::CG< MATRIX >::solve_helper(), oomph::BiCGStab< MATRIX >::solve_helper(), oomph::AugmentedProblemGMRES::solve_helper(), and oomph::SuperLUSolver::solve_transpose().
operator()()
virtual double oomph::DoubleMatrixBase::operator() (const unsigned long & i, const unsigned long & j) const pure virtual
Round brackets to give access as a(i,j) for read only (we're not providing a general interface for component-wise write access since not all matrix formats allow efficient direct access!)
Implemented in oomph::SumOfMatrices, oomph::CCDoubleMatrix, oomph::DenseDoubleMatrix, and oomph::CRDoubleMatrix.
operator=()
void oomph::DoubleMatrixBase::operator= (const DoubleMatrixBase &) delete
Broken assignment operator.
residual()
virtual void oomph::DoubleMatrixBase::residual (const DoubleVector & x, const DoubleVector & b, DoubleVector & residual_) inline virtual
Find the residual, i.e. r=b-Ax the residual.
     {
       // compute residual = Ax
       this->multiply(x, residual_);
       // set residual to -residual (-Ax)
       unsigned nrow_local = residual_.nrow_local();
       double* residual_pt = residual_.values_pt();
       for (unsigned i = 0; i < nrow_local; i++)
       {
         residual_pt[i] = -residual_pt[i];
       }
       // set residual = b + residuals
       residual_ += b;
     }
References b, i, multiply(), oomph::DistributableLinearAlgebraObject::nrow_local(), and oomph::DoubleVector::values_pt().
Referenced by max_residual(), oomph::GMRESBlockPreconditioner::preconditioner_solve(), oomph::GS< MATRIX >::solve_helper(), oomph::GS< CRDoubleMatrix >::solve_helper(), and oomph::DampedJacobi< MATRIX >::solve_helper().
solve() [1/4]
void oomph::DoubleMatrixBase::solve (const DoubleVector & rhs, DoubleVector & soln)
Complete LU solve (Nothing gets overwritten!). The default should not need to be overwritten
Complete LU solve (Nothing gets overwritten!). This generic version should never need to be overwritten
   {
 #ifdef PARANOID
     if (Linear_solver_pt == 0)
     {
       throw OomphLibError("Linear_solver_pt not set in matrix",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Use the linear algebra interface to the linear solver
     Linear_solver_pt->solve(this, rhs, soln);
   }
References Linear_solver_pt, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::LinearSolver::solve().
solve() [2/4]
void oomph::DoubleMatrixBase::solve (const Vector< double > & rhs, Vector< double > & soln)
Complete LU solve (Nothing gets overwritten!). The default should not need to be overwritten
Complete LU solve (Nothing gets overwritten!). This generic version should never need to be overwritten
   {
 #ifdef PARANOID
     if (Linear_solver_pt == 0)
     {
       throw OomphLibError("Linear_solver_pt not set in matrix",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Use the linear algebra interface to the linear solver
     Linear_solver_pt->solve(this, rhs, soln);
   }
References Linear_solver_pt, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::LinearSolver::solve().
solve() [3/4]
void oomph::DoubleMatrixBase::solve (DoubleVector & rhs)
Complete LU solve (replaces matrix by its LU decomposition and overwrites RHS with solution). The default should not need to be over-written
Complete LU solve (overwrites RHS with solution). This is the generic version which should not need to be over-written.
   {
 #ifdef PARANOID
     if (Linear_solver_pt == 0)
     {
       throw OomphLibError("Linear_solver_pt not set in matrix",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Copy rhs vector into local storage so it doesn't get overwritten
     // if the linear solver decides to initialise the solution vector, say,
     // which it's quite entitled to do!
     DoubleVector actual_rhs(rhs);
     // Use the linear algebra interface to the linear solver
     Linear_solver_pt->solve(this, actual_rhs, rhs);
   }
References Linear_solver_pt, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::LinearSolver::solve().
Referenced by oomph::BlackBoxFDNewtonSolver::black_box_fd_newton_solve(), oomph::HelmholtzMGPreconditioner< DIM >::direct_solve(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::find_distance_to_free_surface(), oomph::PVDEquationsBase< DIM >::get_principal_stress(), oomph::FiniteElement::locate_zeta(), and oomph::InterpolateFromIntegralPointsBase::pre_compute_ipt_to_node_mapping().
solve() [4/4]
void oomph::DoubleMatrixBase::solve (Vector< double > & rhs)
Complete LU solve (replaces matrix by its LU decomposition and overwrites RHS with solution). The default should not need to be over-written
Complete LU solve (overwrites RHS with solution). This is the generic version which should not need to be over-written.
   {
 #ifdef PARANOID
     if (Linear_solver_pt == 0)
     {
       throw OomphLibError("Linear_solver_pt not set in matrix",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Copy rhs vector into local storage so it doesn't get overwritten
     // if the linear solver decides to initialise the solution vector, say,
     // which it's quite entitled to do!
     Vector<double> actual_rhs(rhs);
     // Use the linear algebra interface to the linear solver
     Linear_solver_pt->solve(this, actual_rhs, rhs);
   }
References Linear_solver_pt, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::LinearSolver::solve().
Member Data Documentation
Default_linear_solver_pt
LinearSolver* oomph::DoubleMatrixBase::Default_linear_solver_pt protected
Referenced by oomph::CRDoubleMatrix::build(), oomph::CCDoubleMatrix::CCDoubleMatrix(), oomph::CRDoubleMatrix::CRDoubleMatrix(), oomph::DenseDoubleMatrix::DenseDoubleMatrix(), oomph::CRDoubleMatrix::lubksub(), oomph::DenseDoubleMatrix::lubksub(), oomph::CCDoubleMatrix::lubksub(), oomph::CRDoubleMatrix::ludecompose(), oomph::DenseDoubleMatrix::ludecompose(), oomph::CCDoubleMatrix::ludecompose(), oomph::CCDoubleMatrix::~CCDoubleMatrix(), oomph::CRDoubleMatrix::~CRDoubleMatrix(), and oomph::DenseDoubleMatrix::~DenseDoubleMatrix().
Linear_solver_pt
LinearSolver* oomph::DoubleMatrixBase::Linear_solver_pt protected
Referenced by oomph::CCDoubleMatrix::CCDoubleMatrix(), oomph::CRDoubleMatrix::clear(), oomph::CRDoubleMatrix::CRDoubleMatrix(), oomph::DenseDoubleMatrix::DenseDoubleMatrix(), linear_solver_pt(), and solve().
The documentation for this class was generated from the following files:
matrices.h
matrices.cc