MercuryDPM: cxx11_tensor_notification.cpp File Reference
cxx11_tensor_notification.cpp File Reference
#include <atomic>
#include <stdlib.h>
#include "main.h"
#include <Eigen/CXX11/Tensor>
Macros
#define EIGEN_USE_THREADS
Functions
static void test_notification_single ()
static void test_notification_multiple ()
EIGEN_DECLARE_TEST (cxx11_tensor_notification)
Macro Definition Documentation
EIGEN_USE_THREADS
#define EIGEN_USE_THREADS
Function Documentation
EIGEN_DECLARE_TEST()
EIGEN_DECLARE_TEST (cxx11_tensor_notification)
{
   CALL_SUBTEST(test_notification_single());
   CALL_SUBTEST(test_notification_multiple());
 }
References CALL_SUBTEST, test_notification_multiple(), and test_notification_single().
test_notification_multiple()
static void test_notification_multiple () static
{
   ThreadPool thread_pool(1);
   std::atomic<int> counter(0);
   Eigen::Notification n;
   auto func = [&n, &counter]() {
     n.Wait();
     ++counter;
   };
   thread_pool.Schedule(func);
   thread_pool.Schedule(func);
   thread_pool.Schedule(func);
   thread_pool.Schedule(func);
   std::this_thread::sleep_for(std::chrono::milliseconds(1000));
   VERIFY_IS_EQUAL(counter, 0);
   n.Notify();
   std::this_thread::sleep_for(std::chrono::milliseconds(1000));
   VERIFY_IS_EQUAL(counter, 4);
 }
References n, Eigen::ThreadPoolTempl< Environment >::Schedule(), and VERIFY_IS_EQUAL.
Referenced by EIGEN_DECLARE_TEST().
test_notification_single()
static void test_notification_single () static
{
   ThreadPool thread_pool(1);
   std::atomic<int> counter(0);
   Eigen::Notification n;
   auto func = [&n, &counter]() {
     n.Wait();
     ++counter;
   };
   thread_pool.Schedule(func);
   std::this_thread::sleep_for(std::chrono::milliseconds(1000));
   // The thread should be waiting for the notification.
   VERIFY_IS_EQUAL(counter, 0);
   // Unblock the thread
   n.Notify();
   std::this_thread::sleep_for(std::chrono::milliseconds(1000));
   // Verify the counter has been incremented
   VERIFY_IS_EQUAL(counter, 1);
 }
References n, Eigen::ThreadPoolTempl< Environment >::Schedule(), and VERIFY_IS_EQUAL.
Referenced by EIGEN_DECLARE_TEST().