MercuryDPM: oomph::DenseMatrix< T > Class Template Reference
oomph::DenseMatrix< T > Class Template Reference
#include <matrices.h>
Public Member Functions
DenseMatrix ()
Empty constructor, simply assign the lengths N and M to 0.
DenseMatrix (const DenseMatrix &source_matrix)
Copy constructor: Deep copy!
DenseMatrix & operator= (const DenseMatrix &source_matrix)
Copy assignment.
T & entry (const unsigned long &i, const unsigned long &j)
T get_entry (const unsigned long &i, const unsigned long &j) const
DenseMatrix (const unsigned long &n)
Constructor to build a square n by n matrix.
DenseMatrix (const unsigned long &n, const unsigned long &m)
Constructor to build a matrix with n rows and m columns.
DenseMatrix (const unsigned long &n, const unsigned long &m, const T &initial_val)
virtual ~DenseMatrix ()
Destructor, clean up the matrix data.
unsigned long nrow () const
Return the number of rows of the matrix.
unsigned long ncol () const
Return the number of columns of the matrix.
void resize (const unsigned long &n)
void resize (const unsigned long &n, const unsigned long &m)
void resize (const unsigned long &n, const unsigned long &m, const T &initial_value)
void initialise (const T &val)
Initialize all values in the matrix to val.
void output (std::ostream &outfile) const
Output function to print a matrix row-by-row to the stream outfile.
void output (std::string filename) const
Output function to print a matrix row-by-row to a file. Specify filename.
void indexed_output (std::ostream &outfile) const
Indexed output as i,j,a(i,j)
void indexed_output (std::string filename) const
void output_bottom_right_zero_helper (std::ostream &outfile) const
void sparse_indexed_output_helper (std::ostream &outfile) const
Sparse indexed output as i,j,a(i,j) for a(i,j)!=0 only.
Public Member Functions inherited from oomph::Matrix< T, DenseMatrix< T > >
Matrix ()
(Empty) constructor
Matrix (const Matrix &matrix)=delete
Broken copy constructor.
void operator= (const Matrix &)=delete
Broken assignment operator.
virtual ~Matrix ()
Virtual (empty) destructor.
T operator() (const unsigned long &i, const unsigned long &j) const
T & operator() (const unsigned long &i, const unsigned long &j)
void sparse_indexed_output (std::ostream &outfile, const unsigned &precision=0, const bool &output_bottom_right_zero=false) const
void sparse_indexed_output (std::string filename, const unsigned &precision=0, const bool &output_bottom_right_zero=false) const
Protected Attributes
T * Matrixdata
Internal representation of matrix as a pointer to data.
unsigned long N
Number of rows.
unsigned long M
Number of columns.
Additional Inherited Members
Protected Member Functions inherited from oomph::Matrix< T, DenseMatrix< T > >
void range_check (const unsigned long &i, const unsigned long &j) const
Detailed Description
template<class T>
class oomph::DenseMatrix< T >
//////////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////////// Class for dense matrices, storing all the values of the matrix as a pointer to a pointer with assorted output functions inherited from Matrix<T>. The curious recursive template pattern is used here to pass the specific class to the base class so that round bracket access can be inlined.
Constructor & Destructor Documentation
DenseMatrix() [1/5]
template<class T > oomph::DenseMatrix< T >::DenseMatrix () inline
Empty constructor, simply assign the lengths N and M to 0.
 : Matrixdata(0), N(0), M(0) {}
DenseMatrix() [2/5]
template<class T > oomph::DenseMatrix< T >::DenseMatrix (const DenseMatrix< T > & source_matrix) inline
Copy constructor: Deep copy!
     {
       // Set row and column lengths
       N = source_matrix.nrow();
       M = source_matrix.ncol();
       // Assign space for the data
       Matrixdata = new T[N * M];
       // Copy the data across from the other matrix
       for (unsigned long i = 0; i < N; i++)
       {
         for (unsigned long j = 0; j < M; j++)
         {
           Matrixdata[M * i + j] = source_matrix(i, j);
         }
       }
     }
References i, j, oomph::DenseMatrix< T >::M, oomph::DenseMatrix< T >::Matrixdata, oomph::DenseMatrix< T >::N, oomph::DenseMatrix< T >::ncol(), and oomph::DenseMatrix< T >::nrow().
DenseMatrix() [3/5]
template<class T > oomph::DenseMatrix< T >::DenseMatrix (const unsigned long & n)
Constructor to build a square n by n matrix.
////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////
   {
     // Set row and column lengths
     N = n;
     M = n;
     // Assign space for the n rows
     Matrixdata = new T[n * n];
     // Initialise to zero if required
 #ifdef OOMPH_INITIALISE_DENSE_MATRICES
     initialise(T(0));
 #endif
   }
References n, and N.
DenseMatrix() [4/5]
template<class T > oomph::DenseMatrix< T >::DenseMatrix (const unsigned long & n, const unsigned long & m)
Constructor to build a matrix with n rows and m columns.
   {
     // Set row and column lengths
     N = n;
     M = m;
     // Assign space for the n rows
     Matrixdata = new T[n * m];
 #ifdef OOMPH_INITIALISE_DENSE_MATRICES
     initialise(T(0));
 #endif
   }
References m, n, and N.
DenseMatrix() [5/5]
template<class T > oomph::DenseMatrix< T >::DenseMatrix (const unsigned long & n, const unsigned long & m, const T & initial_val)
Constructor to build a matrix with n rows and m columns, with initial value initial_val
   {
     // Set row and column lengths
     N = n;
     M = m;
     // Assign space for the n rows
     Matrixdata = new T[n * m];
     initialise(initial_val);
   }
References m, n, and N.
~DenseMatrix()
template<class T > virtual oomph::DenseMatrix< T >::~DenseMatrix () inline virtual
Destructor, clean up the matrix data.
     {
       delete[] Matrixdata;
       Matrixdata = 0;
     }
References oomph::DenseMatrix< T >::Matrixdata.
Member Function Documentation
entry()
template<class T > T& oomph::DenseMatrix< T >::entry (const unsigned long & i, const unsigned long & j) inline
The access function that will be called by the read-write round-bracket operator.
     {
 #ifdef RANGE_CHECKING
       this->range_check(i, j);
 #endif
       return Matrixdata[M * i + j];
     }
References i, j, oomph::DenseMatrix< T >::Matrixdata, and oomph::Matrix< T, DenseMatrix< T > >::range_check().
Referenced by oomph::DenseDoubleMatrix::operator()().
get_entry()
template<class T > T oomph::DenseMatrix< T >::get_entry (const unsigned long & i, const unsigned long & j) const inline
The access function the will be called by the read-only (const version) round-bracket operator.
     {
 #ifdef RANGE_CHECKING
       this->range_check(i, j);
 #endif
       return Matrixdata[M * i + j];
     }
References i, j, oomph::DenseMatrix< T >::Matrixdata, and oomph::Matrix< T, DenseMatrix< T > >::range_check().
Referenced by oomph::DenseDoubleMatrix::operator()().
indexed_output() [1/2]
template<class T > void oomph::DenseMatrix< T >::indexed_output (std::ostream & outfile) const
Indexed output as i,j,a(i,j)
Indexed output function to print a matrix to the stream outfile as i,j,a(i,j)
   {
     // Loop over the rows
     for (unsigned i = 0; i < N; i++)
     {
       // Loop over the columns
       for (unsigned j = 0; j < M; j++)
       {
         outfile << i << " " << j << " " << (*this)(i, j) << std::endl;
       }
     }
   }
References i, j, and N.
indexed_output() [2/2]
template<class T > void oomph::DenseMatrix< T >::indexed_output (std::string filename) const
Indexed output function to print a matrix to a file as i,j,a(i,j). Specify filename.
   {
     // Open file
     std::ofstream some_file;
     some_file.open(filename.c_str());
     indexed_output(some_file);
     some_file.close();
   }
References MergeRestartFiles::filename.
initialise()
template<class T > void oomph::DenseMatrix< T >::initialise (const T & val) inline
Initialize all values in the matrix to val.
     {
       for (unsigned long i = 0; i < (N * M); ++i)
       {
         Matrixdata[i] = val;
       }
     }
References i, oomph::DenseMatrix< T >::M, oomph::DenseMatrix< T >::Matrixdata, oomph::DenseMatrix< T >::N, and calibrate::val.
Referenced by oomph::PeriodicOrbitTemporalMesh< ELEMENT >::assemble_residuals_and_jacobian(), oomph::FSIHermiteBeamElement::dposition_dlagrangian_at_local_coordinate(), oomph::FSIDiagHermiteShellElement::dposition_dlagrangian_at_local_coordinate(), oomph::GeneralisedElement::get_djacobian_and_dmass_matrix_dparameter(), oomph::GeneralisedElement::get_djacobian_dparameter(), ABCElement::get_inner_product_matrix(), oomph::PeriodicOrbitBaseElement::get_inner_product_matrix(), oomph::DGElement::get_inverse_mass_matrix_times_residuals(), oomph::Problem::get_jacobian(), oomph::ElasticallySupportedRingElement::get_jacobian(), ElasticFishBackElement::get_jacobian(), oomph::GeneralisedElement::get_jacobian(), oomph::GeneralisedElement::get_jacobian_and_mass_matrix(), oomph::GeneralisedElement::get_mass_matrix(), oomph::PseudoBucklingRingElement::get_residuals_generic(), oomph::SpaceTimeNavierStokesEquations< DIM >::get_vorticity(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::get_vorticity(), oomph::DGElement::pre_compute_mass_matrix(), oomph::SpaceTimeNavierStokesEquations< DIM >::strain_rate(), and oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::strain_rate().
ncol()
template<class T > unsigned long oomph::DenseMatrix< T >::ncol () const inline virtual
Return the number of columns of the matrix.
Implements oomph::Matrix< T, DenseMatrix< T > >.
     {
       return M;
     }
References oomph::DenseMatrix< T >::M.
Referenced by oomph::ConstitutiveLaw::calculate_contravariant(), oomph::ConstitutiveLaw::calculate_d_contravariant_dG(), oomph::CRDoubleMatrixHelpers::concatenate(), oomph::CRDoubleMatrixHelpers::concatenate_without_communication(), create_matrices_to_cat(), oomph::DenseMatrix< T >::DenseMatrix(), oomph::FiniteElement::dJ_eulerian_dnodal_coordinates(), oomph::DenseDoubleMatrix::eigenvalues_by_jacobi(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::extrapolated_strain_rate(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::extrapolated_strain_rate(), fill_in_sub_matrices(), oomph::NavierStokesEquations< 2 >::full_output(), oomph::CRDoubleMatrixHelpers::gershgorin_eigenvalue_estimate(), oomph::BlockPreconditioner< MATRIX >::get_blocks(), oomph::LinearElasticityEquationsBase< DIM >::get_strain(), oomph::PoroelasticityEquations< DIM >::get_strain(), oomph::PVDEquationsBase< DIM >::get_strain(), oomph::LinearElasticityEquations< DIM >::get_stress(), oomph::PoroelasticityEquations< DIM >::get_stress(), oomph::CRDoubleMatrixHelpers::inf_norm(), main(), oomph::DenseDoubleMatrix::ncol(), oomph::DenseMatrix< T >::operator=(), oomph::LagrangeEnforcedFlowPreconditioner::setup(), oomph::LinearisedAxisymmetricNavierStokesEquations::strain_rate(), oomph::AxisymmetricNavierStokesEquations::strain_rate(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::strain_rate(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::strain_rate(), oomph::PolarNavierStokesEquations::strain_rate(), oomph::SpaceTimeNavierStokesEquations< DIM >::strain_rate(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::strain_rate(), oomph::LinearisedNavierStokesEquations::strain_rate(), and oomph::PolarNavierStokesEquations::strain_rate_by_r().
nrow()
template<class T > unsigned long oomph::DenseMatrix< T >::nrow () const inline virtual
Return the number of rows of the matrix.
Implements oomph::Matrix< T, DenseMatrix< T > >.
     {
       return N;
     }
References oomph::DenseMatrix< T >::N.
Referenced by oomph::HelmholtzMGPreconditioner< DIM >::block_preconditioner_self_test(), oomph::IsotropicStrainEnergyFunctionConstitutiveLaw::calculate_second_piola_kirchhoff_stress(), oomph::CRDoubleMatrixHelpers::concatenate(), oomph::CRDoubleMatrixHelpers::concatenate_without_communication(), create_matrices_to_cat(), oomph::DenseMatrix< T >::DenseMatrix(), oomph::FiniteElement::dJ_eulerian_dnodal_coordinates(), oomph::DenseDoubleMatrix::eigenvalues_by_jacobi(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::extrapolated_strain_rate(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::extrapolated_strain_rate(), oomph::DisplacementBasedFoepplvonKarmanEquations::fill_in_contribution_to_jacobian_and_mass_matrix(), fill_in_sub_matrices(), oomph::NavierStokesEquations< 2 >::full_output(), oomph::CRDoubleMatrixHelpers::gershgorin_eigenvalue_estimate(), oomph::BlockPreconditioner< MATRIX >::get_blocks(), oomph::LinearElasticityEquationsBase< DIM >::get_strain(), oomph::PoroelasticityEquations< DIM >::get_strain(), oomph::PVDEquationsBase< DIM >::get_strain(), oomph::LinearElasticityEquations< DIM >::get_stress(), oomph::PoroelasticityEquations< DIM >::get_stress(), oomph::CRDoubleMatrixHelpers::inf_norm(), main(), oomph::DenseDoubleMatrix::nrow(), oomph::DenseMatrix< T >::operator=(), oomph::JacksHelloWorld::say_it_external(), oomph::JacksHelloWorld::say_it_inline(), oomph::SecondInvariantHelper::second_invariant(), oomph::LagrangeEnforcedFlowPreconditioner::setup(), oomph::LinearisedAxisymmetricNavierStokesEquations::strain_rate(), oomph::AxisymmetricNavierStokesEquations::strain_rate(), oomph::GeneralisedNewtonianAxisymmetricNavierStokesEquations::strain_rate(), oomph::GeneralisedNewtonianNavierStokesEquations< DIM >::strain_rate(), oomph::PolarNavierStokesEquations::strain_rate(), oomph::SpaceTimeNavierStokesEquations< DIM >::strain_rate(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::strain_rate(), oomph::LinearisedNavierStokesEquations::strain_rate(), and oomph::PolarNavierStokesEquations::strain_rate_by_r().
operator=()
template<class T > DenseMatrix& oomph::DenseMatrix< T >::operator= (const DenseMatrix< T > & source_matrix) inline
Copy assignment.
     {
       // Don't create a new matrix if the assignment is the identity
       if (this != &source_matrix)
       {
         // Check row and column length
         unsigned long n = source_matrix.nrow();
         unsigned long m = source_matrix.ncol();
         if ((N != n) || (M != m))
         {
           resize(n, m);
         }
         // Copy entries across from the other matrix
         for (unsigned long i = 0; i < N; i++)
         {
           for (unsigned long j = 0; j < M; j++)
           {
             (*this)(i, j) = source_matrix(i, j);
           }
         }
       }
       // Return reference to object itself (i.e. de-reference this pointer)
       return *this;
     }
References i, j, m, oomph::DenseMatrix< T >::M, n, oomph::DenseMatrix< T >::N, oomph::DenseMatrix< T >::ncol(), oomph::DenseMatrix< T >::nrow(), and oomph::DenseMatrix< T >::resize().
output() [1/2]
template<class T > void oomph::DenseMatrix< T >::output (std::ostream & outfile) const virtual
Output function to print a matrix row-by-row to the stream outfile.
Reimplemented from oomph::Matrix< T, DenseMatrix< T > >.
   {
     // Loop over the rows
     for (unsigned i = 0; i < N; i++)
     {
       // Loop over the columne
       for (unsigned j = 0; j < M; j++)
       {
         outfile << (*this)(i, j) << " ";
       }
       // Put in a newline
       outfile << std::endl;
     }
   }
References i, j, and N.
output() [2/2]
template<class T > void oomph::DenseMatrix< T >::output (std::string filename) const
Output function to print a matrix row-by-row to a file. Specify filename.
Output function to print a matrix row-by-row to a file. Specify filename.
   {
     // Open file
     std::ofstream some_file;
     some_file.open(filename.c_str());
     output(some_file);
     some_file.close();
   }
References MergeRestartFiles::filename, and oomph::output().
output_bottom_right_zero_helper()
template<class T > void oomph::DenseMatrix< T >::output_bottom_right_zero_helper (std::ostream & outfile) const virtual
Output the "bottom right" entry regardless of it being zero or not (this allows automatic detection of matrix size in e.g. matlab, python).
Implements oomph::Matrix< T, DenseMatrix< T > >.
   {
     int last_row = this->N - 1;
     int last_col = this->M - 1;
     // Use this strange thingy because of the CRTP discussed above.
     T last_value = this->operator()(last_row, last_col);
     if (last_value == T(0))
     {
       outfile << last_row << " " << last_col << " " << T(0) << std::endl;
     }
   }
References N.
resize() [1/3]
template<class T > void oomph::DenseMatrix< T >::resize (const unsigned long & n) inline
Resize to a square nxn matrix; any values already present will be transfered
     {
       resize(n, n);
     }
References n.
Referenced by SpineGravityTractionElement< ELEMENT >::assign_additional_local_eqn_numbers(), oomph::SpectralElement::assign_all_generic_local_eqn_numbers(), oomph::DenseDoubleMatrix::eigenvalues_by_jacobi(), oomph::PeriodicOrbitEquations::fill_in_generic_residual_contribution_orbit(), RefineableQAxisymCrouzeixRaviartBoussinesqElement::get_dbody_force_axi_nst_dexternal_element_data(), QAxisymCrouzeixRaviartElementWithExternalElement::get_dbody_force_axi_nst_dexternal_element_data(), RefineableQCrouzeixRaviartElementWithExternalElement< DIM >::get_dbody_force_nst_dexternal_element_data(), RefineableQCrouzeixRaviartElementWithTwoExternalElement< DIM >::get_dbody_force_nst_dexternal_element_data(), QCrouzeixRaviartElementWithTwoExternalElement< DIM >::get_dbody_force_nst_dexternal_element_data(), oomph::RefineableNavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::get_dbody_force_nst_dexternal_element_data(), oomph::NavierStokesBoussinesqElement< NST_ELEMENT, AD_ELEMENT >::get_dbody_force_nst_dexternal_element_data(), oomph::Problem::get_fd_jacobian(), oomph::DGElement::get_inverse_mass_matrix_times_residuals(), oomph::Problem::get_jacobian(), oomph::IMRBase::IMRBase(), oomph::JacksHelloWorld::JacksHelloWorld(), oomph::KirchhoffLoveShellEquations::KirchhoffLoveShellEquations(), oomph::DenseDoubleMatrix::matrix_reduction(), oomph::ContinuationStorageScheme::modify_storage(), oomph::DenseDoubleMatrix::multiply(), oomph::DenseMatrix< T >::operator=(), oomph::DGElement::pre_compute_mass_matrix(), oomph::SelfStartingBDF2::SelfStartingBDF2(), oomph::BinaryTree::setup_static_data(), oomph::OcTree::setup_static_data(), oomph::QuadTree::setup_static_data(), and oomph::HSL_MA42::solve().
resize() [2/3]
template<class T > void oomph::DenseMatrix< T >::resize (const unsigned long & n, const unsigned long & m)
Resize to a non-square n x m matrix; any values already present will be transfered
Resize to a non-square n_row x m_col matrix, where any values already present will be transfered.
   {
     // If the sizes are the same, do nothing
     if ((n == N) && (m == M))
     {
       return;
     }
     // Store old sizes
     unsigned long n_old = N, m_old = M;
     // Reassign the sizes
     N = n;
     M = m;
     // Store double pointer to old matrix data
     T* temp_matrix = Matrixdata;
     // Re-create Matrixdata in new size
     Matrixdata = new T[n * m];
     // Initialise to zero
 #ifdef OOMPH_INITIALISE_DENSE_MATRICES
     initialise(T(0));
 #endif
     // Transfer previously existing values
     unsigned long n_copy, m_copy;
     n_copy = std::min(n_old, n);
     m_copy = std::min(m_old, m);
     // If matrix has values, transfer them to new matrix
     // Loop over rows
     for (unsigned long i = 0; i < n_copy; i++)
     {
       // Loop over columns
       for (unsigned long j = 0; j < m_copy; j++)
       {
         // Transfer values from temp_matrix
         Matrixdata[m * i + j] = temp_matrix[m_old * i + j];
       }
     }
     // Now kill storage for old matrix
     delete[] temp_matrix;
   }
References i, j, m, min, n, and N.
resize() [3/3]
template<class T > void oomph::DenseMatrix< T >::resize (const unsigned long & n, const unsigned long & m, const T & initial_value)
Resize to a non-square n x m matrix and initialize the new values to initial_value.
Resize to a non-square n_row x m_col matrix and initialize the new entries to specified value.
   {
     // If the size is not changed, just return
     if ((n == N) && (m == M))
     {
       return;
     }
     // Store old sizes
     unsigned long n_old = N, m_old = M;
     // Reassign the sizes
     N = n;
     M = m;
     // Store double pointer to old matrix data
     T* temp_matrix = Matrixdata;
     // Re-create Matrixdata in new size
     Matrixdata = new T[n * m];
     // Assign initial value (will use the newly allocated data)
     initialise(initial_value);
     // Transfering values
     unsigned long n_copy, m_copy;
     n_copy = std::min(n_old, n);
     m_copy = std::min(m_old, m);
     // If matrix has values, transfer them to temp_matrix
     // Loop over rows
     for (unsigned long i = 0; i < n_copy; i++)
     {
       // Loop over columns
       for (unsigned long j = 0; j < m_copy; j++)
       {
         // Transfer values to temp_matrix
         Matrixdata[m * i + j] = temp_matrix[m_old * i + j];
       }
     }
     // Now kill storage for old matrix
     delete[] temp_matrix;
   }
References i, j, m, min, n, and N.
sparse_indexed_output_helper()
template<class T > void oomph::DenseMatrix< T >::sparse_indexed_output_helper (std::ostream & outfile) const virtual
Sparse indexed output as i,j,a(i,j) for a(i,j)!=0 only.
Indexed output function to print a matrix to the stream outfile as i,j,a(i,j) for a(i,j)!=0 only.
Implements oomph::Matrix< T, DenseMatrix< T > >.
   {
     // Loop over the rows
     for (unsigned i = 0; i < N; i++)
     {
       // Loop over the column
       for (unsigned j = 0; j < M; j++)
       {
         if ((*this)(i, j) != T(0))
         {
           outfile << i << " " << j << " " << (*this)(i, j) << std::endl;
         }
       }
     }
   }
References i, j, and N.
Member Data Documentation
M
template<class T > unsigned long oomph::DenseMatrix< T >::M protected
Number of columns.
Referenced by oomph::DenseMatrix< T >::DenseMatrix(), oomph::DenseMatrix< T >::initialise(), oomph::DenseMatrix< T >::ncol(), and oomph::DenseMatrix< T >::operator=().
Matrixdata
template<class T > T* oomph::DenseMatrix< T >::Matrixdata protected
Internal representation of matrix as a pointer to data.
Referenced by oomph::DenseMatrix< T >::DenseMatrix(), oomph::DenseMatrix< T >::entry(), oomph::DenseMatrix< T >::get_entry(), oomph::DenseMatrix< T >::initialise(), and oomph::DenseMatrix< T >::~DenseMatrix().
N
template<class T > unsigned long oomph::DenseMatrix< T >::N protected
Number of rows.
Referenced by oomph::DenseMatrix< T >::DenseMatrix(), oomph::DenseMatrix< T >::initialise(), oomph::DenseMatrix< T >::nrow(), and oomph::DenseMatrix< T >::operator=().
The documentation for this class was generated from the following files:
communicator.h
matrices.h