MercuryDPM: SingleSphere.cpp File Reference
SingleSphere.cpp File Reference
#include "MercuryProb.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
RVE size
Setup the coupled problem
{
     double RVESize = 0.4 / units::lUnit;
     MercuryProblem TriangleWallsTest;
     TriangleWallsTest.setupMercuryProblem("SingleSphere", 3, RVESize, 1, -9.81*100 / units::accUnit(), 20 / units::tUnit, 1000);
     TriangleWallsTest.solve();
 } //end of main
References units::accUnit(), units::lUnit, MercuryProblem::setupMercuryProblem(), DPMBase::solve(), and units::tUnit.