MercuryDPM: Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheRight, Mode, Conjugate, TriStorageOrder, ColMajor, OtherInnerStride > Struct Template Reference
Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheRight, Mode, Conjugate, TriStorageOrder, ColMajor, OtherInnerStride > Struct Template Reference
#include <TriangularSolverMatrix.h>
Static Public Member Functions
static EIGEN_DONT_INLINE void run (Index size, Index otherSize, const Scalar *_tri, Index triStride, Scalar *_other, Index otherIncr, Index otherStride, level3_blocking< Scalar, Scalar > &blocking)
Member Function Documentation
run()
template<typename Scalar , typename Index , int Mode, bool Conjugate, int TriStorageOrder, int OtherInnerStride> EIGEN_DONT_INLINE void Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheRight, Mode, Conjugate, TriStorageOrder, ColMajor, OtherInnerStride >::run (Index size, Index otherSize, const Scalar * _tri, Index triStride, Scalar * _other, Index otherIncr, Index otherStride, level3_blocking< Scalar, Scalar > & blocking) static
{
   Index rows = otherSize;
 #if defined(EIGEN_VECTORIZE_AVX512) && EIGEN_USE_AVX512_TRSM_R_KERNELS && EIGEN_ENABLE_AVX512_NOCOPY_TRSM_R_CUTOFFS
   EIGEN_IF_CONSTEXPR(
       (OtherInnerStride == 1 && (std::is_same<Scalar, float>::value || std::is_same<Scalar, double>::value))) {
     // TODO: Investigate better heuristics for cutoffs.
     std::ptrdiff_t l1, l2, l3;
     manage_caching_sizes(GetAction, &l1, &l2, &l3);
     double L2Cap = 0.5;  // 50% of L2 size
     if (size < avx512_trsm_cutoff<Scalar>(l2, rows, L2Cap)) {
       trsmKernelR<Scalar, Index, Mode, Conjugate, TriStorageOrder, OtherInnerStride, /*Specialized=*/true>::kernel(
           size, rows, _tri, triStride, _other, 1, otherStride);
       return;
     }
   }
 #endif
   typedef blas_data_mapper<Scalar, Index, ColMajor, Unaligned, OtherInnerStride> LhsMapper;
   typedef const_blas_data_mapper<Scalar, Index, TriStorageOrder> RhsMapper;
   LhsMapper lhs(_other, otherStride, otherIncr);
   RhsMapper rhs(_tri, triStride);
   typedef gebp_traits<Scalar, Scalar> Traits;
   enum {
     RhsStorageOrder = TriStorageOrder,
     SmallPanelWidth = plain_enum_max(Traits::mr, Traits::nr),
     IsLower = (Mode & Lower) == Lower
   };
   Index kc = blocking.kc();                    // cache block size along the K direction
   Index mc = (std::min)(rows, blocking.mc());  // cache block size along the M direction
   std::size_t sizeA = kc * mc;
   std::size_t sizeB = kc * size;
   ei_declare_aligned_stack_constructed_variable(Scalar, blockA, sizeA, blocking.blockA());
   ei_declare_aligned_stack_constructed_variable(Scalar, blockB, sizeB, blocking.blockB());
   gebp_kernel<Scalar, Scalar, Index, LhsMapper, Traits::mr, Traits::nr, false, Conjugate> gebp_kernel;
   gemm_pack_rhs<Scalar, Index, RhsMapper, Traits::nr, RhsStorageOrder> pack_rhs;
   gemm_pack_rhs<Scalar, Index, RhsMapper, Traits::nr, RhsStorageOrder, false, true> pack_rhs_panel;
   gemm_pack_lhs<Scalar, Index, LhsMapper, Traits::mr, Traits::LhsProgress, typename Traits::LhsPacket4Packing, ColMajor,
                 false, true>
       pack_lhs_panel;
   for (Index k2 = IsLower ? size : 0; IsLower ? k2 > 0 : k2 < size; IsLower ? k2 -= kc : k2 += kc) {
     const Index actual_kc = (std::min)(IsLower ? k2 : size - k2, kc);
     Index actual_k2 = IsLower ? k2 - actual_kc : k2;
     Index startPanel = IsLower ? 0 : k2 + actual_kc;
     Index rs = IsLower ? actual_k2 : size - actual_k2 - actual_kc;
     Scalar* geb = blockB + actual_kc * actual_kc;
     if (rs > 0) pack_rhs(geb, rhs.getSubMapper(actual_k2, startPanel), actual_kc, rs);
     // triangular packing (we only pack the panels off the diagonal,
     // neglecting the blocks overlapping the diagonal
     {
       for (Index j2 = 0; j2 < actual_kc; j2 += SmallPanelWidth) {
         Index actualPanelWidth = std::min<Index>(actual_kc - j2, SmallPanelWidth);
         Index actual_j2 = actual_k2 + j2;
         Index panelOffset = IsLower ? j2 + actualPanelWidth : 0;
         Index panelLength = IsLower ? actual_kc - j2 - actualPanelWidth : j2;
         if (panelLength > 0)
           pack_rhs_panel(blockB + j2 * actual_kc, rhs.getSubMapper(actual_k2 + panelOffset, actual_j2), panelLength,
                          actualPanelWidth, actual_kc, panelOffset);
       }
     }
     for (Index i2 = 0; i2 < rows; i2 += mc) {
       const Index actual_mc = (std::min)(mc, rows - i2);
       // triangular solver kernel
       {
         // for each small block of the diagonal (=> vertical panels of rhs)
         for (Index j2 = IsLower ? (actual_kc - ((actual_kc % SmallPanelWidth) ? Index(actual_kc % SmallPanelWidth)
                                                                               : Index(SmallPanelWidth)))
                                 : 0;
              IsLower ? j2 >= 0 : j2 < actual_kc; IsLower ? j2 -= SmallPanelWidth : j2 += SmallPanelWidth) {
           Index actualPanelWidth = std::min<Index>(actual_kc - j2, SmallPanelWidth);
           Index absolute_j2 = actual_k2 + j2;
           Index panelOffset = IsLower ? j2 + actualPanelWidth : 0;
           Index panelLength = IsLower ? actual_kc - j2 - actualPanelWidth : j2;
           // GEBP
           if (panelLength > 0) {
             gebp_kernel(lhs.getSubMapper(i2, absolute_j2), blockA, blockB + j2 * actual_kc, actual_mc, panelLength,
                         actualPanelWidth, Scalar(-1), actual_kc, actual_kc,  // strides
                         panelOffset, panelOffset);                           // offsets
           }
           {
             // unblocked triangular solve
             trsmKernelR<Scalar, Index, Mode, Conjugate, TriStorageOrder, OtherInnerStride,
                         /*Specialized=*/true>::kernel(actualPanelWidth, actual_mc,
                                                       _tri + absolute_j2 + absolute_j2 * triStride, triStride,
                                                       _other + i2 * OtherInnerStride + absolute_j2 * otherStride,
                                                       otherIncr, otherStride);
           }
           // pack the just computed part of lhs to A
           pack_lhs_panel(blockA, lhs.getSubMapper(i2, absolute_j2), actualPanelWidth, actual_mc, actual_kc, j2);
         }
       }
       if (rs > 0)
         gebp_kernel(lhs.getSubMapper(i2, startPanel), blockA, geb, actual_mc, actual_kc, rs, Scalar(-1), -1, -1, 0, 0);
     }
   }
 }
References Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::blockA(), Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::blockB(), Eigen::ColMajor, ei_declare_aligned_stack_constructed_variable, EIGEN_IF_CONSTEXPR, Eigen::GetAction, Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::kc(), Eigen::Lower, Eigen::internal::manage_caching_sizes(), Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::mc(), min, Eigen::internal::plain_enum_max(), rows, size, and Eigen::value.
The documentation for this struct was generated from the following file:
TriangularSolverMatrix.h