MercuryDPM: Coil Class Reference
Coil Class Reference
This class defines a coil in the z-direction from a (constant) starting point, a (constant) length L, a (constant) radius r, a (constant) number or revelations N and a (constant) rotation speed (rev/s)
#include <Coil.h>
Public Member Functions
Coil ()
Default constructor, sets a coil with default parameters.
Coil (const Coil &other)
Copy constructor, makes a coil with the same properties as the input Coil.
Coil (Vec3D Start, Mdouble L, Mdouble r, Mdouble N, Mdouble omega, Mdouble thickness)
Constructor in which all parameters are set.
~Coil () override
Default destructor.
void set (Vec3D Start, Mdouble length, Mdouble radius, Mdouble numberOfRevelations, Mdouble omega, Mdouble thickness)
Set all parameters of this Coil.
Coil * copy () const override
Copy this Coil and return a pointer to the copy, useful for polymorphism.
bool getDistanceAndNormal (const BaseParticle &P, Mdouble &distance, Vec3D &normal_return) const override
Compute the distance from the Coil for a given BaseParticle and return if there is a collision. If there is a collision, also return the normal vector of the interaction point.
void move_time (Mdouble dt)
Rotate the Coil for a period dt, so that the offset_ changes with omega_*dt.
void read (std::istream &is) override
Reads a Coil from an input stream, for example a restart file.
MERCURYDPM_DEPRECATED void oldRead (std::istream &is)
Reads an old-style Coil from an input stream, for example an old restart file.
void write (std::ostream &os) const override
Writes a Coil to an output stream, for example a restart file.
std::string getName () const override
Returns the name of the object, in this case the string "Coil".
Public Member Functions inherited from BaseWall
BaseWall ()
Default constructor.
BaseWall (const BaseWall &w)
Copy constructor.
~BaseWall () override
Default destructor.
virtual bool getDistanceNormalOverlap (const BaseParticle &P, Mdouble &distance, Vec3D &normal_return, Mdouble &overlap) const
virtual bool getDistanceNormalOverlapSuperquadric (const SuperQuadricParticle &p, Mdouble &distance, Vec3D &normal_return, Mdouble &overlap) const
virtual Vec3D getFurthestPointSuperQuadric (const Vec3D &normalBodyFixed, const Vec3D &axes, Mdouble eps1, Mdouble eps2) const
virtual void setHandler (WallHandler *handler)
A function which sets the WallHandler for this BaseWall.
WallHandler * getHandler () const
A function which returns the WallHandler that handles this BaseWall.
void setIndSpecies (unsigned int indSpecies) override
Define the species of this wall using the index of the species in the SpeciesHandler in this DPMBase.
void setSpecies (const ParticleSpecies *species)
Defines the species of the current wall.
bool isFixed () const override
void setForceControl (Vec3D forceGoal, Vec3D gainFactor, Vec3D baseVelocity={0, 0, 0})
Slowly adjusts the force on a wall towards a specified goal, by adjusting (prescribing) the velocity of the wall.
virtual bool isLocal (Vec3D &min, Vec3D &max) const
bool getLinePlaneIntersect (Vec3D &intersect, const Vec3D &p0, const Vec3D &p1, const Vec3D &n, const Vec3D &p)
bool isInsideWallVTK (const Vec3D &point, const Vec3D &normal, const Vec3D &position) const
void projectOntoWallVTK (Vec3D &point0, const Vec3D &point1, const Vec3D &normal, const Vec3D &position) const
void intersectVTK (std::vector< Vec3D > &points, Vec3D normal, Vec3D position) const
virtual BaseInteraction * getInteractionWithSuperQuad (SuperQuadricParticle *p, unsigned timeStamp, InteractionHandler *interactionHandler)
virtual void writeVTK (VTKContainer &vtk) const
void getVTK (std::vector< Vec3D > &points, std::vector< std::vector< double >> &triangleStrips)
const Vec3D getAxis () const
BaseInteraction * getInteractionWith (BaseParticle *p, unsigned timeStamp, InteractionHandler *interactionHandler) override
Returns the interaction between this wall and a given particle, nullptr if there is no interaction.
virtual void actionsOnRestart ()
No implementation but can be overidden in its derived classes.
virtual void actionsAfterParticleGhostUpdate ()
No implementation but can be overidden in its derived classes.
virtual void handleParticleAddition (unsigned int id, BaseParticle *p)
Handles the addition of particles to the particleHandler.
virtual void handleParticleRemoval (unsigned int id)
Handles the addition of particles to the particleHandler.
virtual void checkInteractions (InteractionHandler *interactionHandler, unsigned int timeStamp)
Check if all interactions are valid.
bool getVTKVisibility () const
void setVTKVisibility (bool vtkVisibility)
void addRenderedWall (BaseWall *w)
BaseWall * getRenderedWall (size_t i) const
std::vector< BaseWall * > getRenderedWalls () const
void removeRenderedWalls ()
void renderWall (VTKContainer &vtk)
void addParticlesAtWall (unsigned numElements=50)
void setVelocityControl (Vec3D forceGoal, Vec3D gainFactor, Vec3D baseVelocity)
virtual void writeWallDetailsVTK (VTKData &data) const
virtual void computeWear ()
Public Member Functions inherited from BaseInteractable
BaseInteractable ()
Default BaseInteractable constructor.
BaseInteractable (const BaseInteractable &p)
Copy constructor.
~BaseInteractable () override
Destructor, it simply destructs the BaseInteractable and all the objects it contains.
unsigned int getIndSpecies () const
Returns the index of the species associated with the interactable object.
const ParticleSpecies * getSpecies () const
Returns a pointer to the species of this BaseInteractable.
void setSpecies (const ParticleSpecies *species)
Sets the species of this BaseInteractable.
const Vec3D & getForce () const
Returns the force on this BaseInteractable.
const Vec3D & getTorque () const
Returns the torque on this BaseInteractable.
void setForce (const Vec3D &force)
Sets the force on this BaseInteractable.
void setTorque (const Vec3D &torque)
Sets the torque on this BaseInteractable.
void addForce (const Vec3D &addForce)
Adds an amount to the force on this BaseInteractable.
void addTorque (const Vec3D &addTorque)
Adds an amount to the torque on this BaseInteractable.
virtual void resetForceTorque (int numberOfOMPthreads)
void sumForceTorqueOMP ()
const Vec3D & getPosition () const
Returns the position of this BaseInteractable.
const Quaternion & getOrientation () const
Returns the orientation of this BaseInteractable.
virtual void setPosition (const Vec3D &position)
Sets the position of this BaseInteractable.
void setOrientationViaNormal (Vec3D normal)
Sets the orientation of this BaseInteractable by defining the vector that results from the rotation of the (1,0,0) vector.
void setOrientationViaEuler (Vec3D eulerAngle)
Sets the orientation of this BaseInteractable by defining the euler angles.
virtual void setOrientation (const Quaternion &orientation)
Sets the orientation of this BaseInteractable.
virtual void move (const Vec3D &move)
Moves this BaseInteractable by adding an amount to the position.
virtual void rotate (const Vec3D &angularVelocityDt)
Rotates this BaseInteractable.
const std::vector< BaseInteraction * > & getInteractions () const
Returns a list of interactions which belong to this interactable.
void addInteraction (BaseInteraction *I)
Adds an interaction to this BaseInteractable.
bool removeInteraction (BaseInteraction *I)
Removes an interaction from this BaseInteractable.
void copyInteractionsForPeriodicParticles (const BaseInteractable &p)
Copies interactions to this BaseInteractable whenever a periodic copy made.
void setVelocity (const Vec3D &velocity)
set the velocity of the BaseInteractable.
void setAngularVelocity (const Vec3D &angularVelocity)
set the angular velocity of the BaseInteractble.
void addVelocity (const Vec3D &velocity)
adds an increment to the velocity.
void addAngularVelocity (const Vec3D &angularVelocity)
add an increment to the angular velocity.
virtual const Vec3D & getVelocity () const
Returns the velocity of this interactable.
virtual const Vec3D & getAngularVelocity () const
Returns the angular velocity of this interactable.
void setPrescribedPosition (const std::function< Vec3D(double)> &prescribedPosition)
Allows the position of an infinite mass interactable to be prescribed.
void applyPrescribedPosition (double time)
Computes the position from the user defined prescribed position function.
void setPrescribedVelocity (const std::function< Vec3D(double)> &prescribedVelocity)
Allows the velocity of an infinite mass interactable to be prescribed.
void applyPrescribedVelocity (double time)
Computes the velocity from the user defined prescribed velocity function.
void setPrescribedOrientation (const std::function< Quaternion(double)> &prescribedOrientation)
Allows the orientation of the infinite mass interactbale to be prescribed.
void applyPrescribedOrientation (double time)
Computes the orientation from the user defined prescribed orientation function.
void setPrescribedAngularVelocity (const std::function< Vec3D(double)> &prescribedAngularVelocity)
Allows the angular velocity of the infinite mass interactable to be prescribed.
void applyPrescribedAngularVelocity (double time)
Computes the angular velocity from the user defined prescribed angular velocity.
virtual const Vec3D getVelocityAtContact (const Vec3D &contact) const
Returns the velocity at the contact point, use by many force laws.
void integrateBeforeForceComputation (double time, double timeStep)
This is part of integrate routine for objects with infinite mass.
void integrateAfterForceComputation (double time, double timeStep)
This is part of the integration routine for objects with infinite mass.
virtual Mdouble getInvMass () const
virtual Mdouble getCurvature (const Vec3D &labFixedCoordinates) const
virtual bool isFaceContact (const Vec3D &normal) const
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Private Attributes
Vec3D start_
The centre of the lower end of the Coil.
Mdouble l_
The length of the Coil.
Mdouble r_
Mdouble n_
Mdouble omega_
Mdouble offset_
Mdouble thickness_
Additional Inherited Members
Static Public Member Functions inherited from BaseWall
static void addToVTK (const std::vector< Vec3D > &points, VTKContainer &vtk)
Takes the points provided and adds a triangle strip connecting these points to the vtk container.
Detailed Description
This class defines a coil in the z-direction from a (constant) starting point, a (constant) length L, a (constant) radius r, a (constant) number or revelations N and a (constant) rotation speed (rev/s)
q is a new coordinate going from 0 to 1 and t is the time, x=xs+r*cos(2*pi(offset+N*q)), y=ys+r*sin(2*pi*(offset+N*q)) and z=zs+q*L
Todo:
IFCD: Can someone look at the details of the documentation of class Coil? I can't make sense of them.
Coil is now fixed in Z-direction, centered around the Z-axis. Consider converting to more general parameters, with direction of choise and central axis of choice.
Constructor & Destructor Documentation
Coil() [1/3]
Coil::Coil ()
Default constructor, sets a coil with default parameters.
Default constructor, make a Coil which is centered in the origin, has length 1, radius 1, 1 revelation, rotates with 1 rev/s, has thickness 0 and has not rotated.
 {
     start_.setZero();
     l_ = 1.0;
     r_ = 1.0;
     n_ = 1.0;
     omega_ = 1.0;
     offset_ = 0.0;
     thickness_ = 0.0;
     logger(DEBUG, "Coil() constructor finished");
 }
References DEBUG, l_, logger, n_, offset_, omega_, r_, Vec3D::setZero(), start_, and thickness_.
Referenced by copy().
Coil() [2/3]
Coil::Coil (const Coil & other)
Copy constructor, makes a coil with the same properties as the input Coil.
Parameters
[in] other Coil to be copied into this coil
                             : BaseWall(other)
 {
     start_ = other.start_;
     l_ = other.l_;
     r_ = other.r_;
     n_ = other.n_;
     omega_ = other.omega_;
     offset_ = other.offset_;
     thickness_ = other.thickness_;
     logger(DEBUG, "Coil(const Coil&) copy constructor finished");
 }
References DEBUG, l_, logger, n_, offset_, omega_, r_, start_, and thickness_.
Coil() [3/3]
Coil::Coil (Vec3D start, Mdouble l, Mdouble r, Mdouble n, Mdouble omega, Mdouble thickness)
Constructor in which all parameters are set.
Parameters
[in] start A Vec3D which denotes the centre of the lower end of the Coil.
[in] l The length of the Coil, must be positive.
[in] r The radius of the Coil, must be positive.
[in] n The number of revelations of the Coil, must be positive.
[in] omega The rotation speed of the Coil in rev/s.
[in] thickness The thickness of the "spiral" of the Coil, must be non-negative.
Make a Coil by assigning all input parameters to the data-members of this class, and setting the offset_ to 0.
 {
     start_ = start;
     l_ = l;
     r_ = r;
     n_ = n;
     omega_ = omega;
     thickness_ = thickness;
     offset_ = 0.0;
     logger(DEBUG, "Coil(params) constructor with parameters finished.");
 }
References DEBUG, l_, logger, n, n_, offset_, Eigen::internal::omega(), omega_, UniformPSDSelfTest::r, r_, oomph::CumulativeTimings::start(), start_, and thickness_.
~Coil()
Coil::~Coil () override
Default destructor.
 {
     logger(DEBUG, "~Coil() destructor finished.");
 }
References DEBUG, and logger.
Member Function Documentation
copy()
Coil * Coil::copy () const override virtual
Copy this Coil and return a pointer to the copy, useful for polymorphism.
Returns
A pointer to a copy of this Coil.
Implements BaseWall.
 {
     return new Coil(*this);
 }
References Coil().
getDistanceAndNormal()
bool Coil::getDistanceAndNormal (const BaseParticle & p, Mdouble & distance, Vec3D & normal_return) const override virtual
Compute the distance from the Coil for a given BaseParticle and return if there is a collision. If there is a collision, also return the normal vector of the interaction point.
Parameters
[in] p BaseParticle we want to calculate the distance and whether it collided of.
[out] distance The distance of the BaseParticle to this Coil.
[out] normal_return If there was a collision, the normal vector to this Coil will be placed here.
Returns
A boolean which says whether or not there was a collision.
This function computes whether or not there is a collision between a given BaseParticle and this Coil. If there is a collision, this function also computes the distance between the BaseParticle and Coil and the normal of the IntersectionOfWalls at the intersection point.
Todo:
Make this function readable and explain the steps in the details.
Implements BaseWall.
 {
     const Mdouble interactionRadius = p.getWallInteractionRadius(this) + thickness_;
     Mdouble Rsqr = pow(p.getPosition().X - start_.X, 2) + pow(p.getPosition().Y - start_.Y, 2);
     if (Rsqr > pow(r_ + interactionRadius, 2) ||
         Rsqr < pow(r_ - interactionRadius, 2) ||
         p.getPosition().Z > l_ + start_.Z + interactionRadius ||
         p.getPosition().Z < start_.Z - interactionRadius)
     {
         //std::cout<<"Particle is out of first bound checking"<<std::endl;
         //std::cout<<"Rule 1: "<<pow(r-P.getRadius()-thickness_,2)<<"<"<<Rsqr<<"<"<<pow(r+P.getRadius()+thickness_,2)<<std::endl;
         //std::cout<<"Rule 2: "<<Start.Z-P.getRadius()-thickness_<<"<"<<P.getPosition().Z<<"<"<<L+Start.Z+P.getRadius()+thickness_<<std::endl;
         return false;
     }
     Mdouble R = sqrt(Rsqr);
     Mdouble alpha = atan2(p.getPosition().Y - start_.Y, p.getPosition().X - start_.X);
     Mdouble dz = p.getPosition().Z - start_.Z;
     //To find the contact point we have to minimize (with respect to q)
     //Distance^2=(x-x0-r*cos(2*Pi*(offset+N*q)))^2+(y-y0-r*sin(2*Pi*(offset+N*q)))^2+(z-z0-q*L)^2
     //Using polar coordinated (i.e. x-x0=R*cos(alpha), y-y0=R*sin(alpha) and dz=z-z0)
     //Distance^2=R^2+r^2-2*R*r*cos(alpha-2*Pi*(offset+N*q))+(dz-q*L)^2
     //So we have to minimize:
     //Distance^2=R^2+r^2-2*R*r*cos(alpha-2*Pi*(offset+N*q))+(dz-q*L)^2
     //For this we use the Euler algoritm
     Mdouble q; //Current guess
     Mdouble dd; //Derivative at current guess
     Mdouble ddd; //Second derivative at current guess
     Mdouble q0 = dz / l_; //Minimum of the parabolic part
     //The initial guess will be in the maximum of the cos closest to the minimum of the parabolic part
     //Minima of the cos are at
     //alpha-2*Pi*(offset+N*q)=2*k*Pi (k=integer)
     //q=alpha/(2*Pi*N)-k/N-offset/N (k=integer)
     Mdouble k = round(alpha / 2.0 / constants::pi - (offset_ + n_ * q0));
     q = alpha / (2 * constants::pi * n_) - k / n_ - offset_ / n_;
     //Now apply Newton's method
     do
     {
         dd = -4.0 * R * r_ * constants::pi * n_ * sin(alpha - 2.0 * constants::pi * (n_ * q + offset_)) -
              2.0 * l_ * (dz - q * l_);
         ddd = 8.0 * R * r_ * constants::sqr_pi * n_ * n_ * cos(alpha - 2.0 * constants::pi * (n_ * q + offset_)) +
               2.0 * l_ * l_;
         q -= dd / ddd;
     } while (fabs(dd / ddd) > 1e-14);
     //Check if the location is actually on the coil, otherwise a point collision with the end of the coil calculated
     if (q < 0) //Left boundary of the coil
     {
         q = 0;
     }
     else if (q > 1) //right boundary of the coil
     {
         q = 1;
     }
     Mdouble distanceSquared =
             R * R + r_ * r_ - 2 * R * r_ * cos(alpha - 2 * constants::pi * (offset_ + n_ * q)) + pow(dz - q * l_, 2);
     //If distance is too large there is no contact
     if (distanceSquared >= mathsFunc::square(p.getWallInteractionRadius(this) + thickness_))
     {
         //std::cout<<"Particle is out of second bound checking, distance^2="<<distance<<" max="<<(P.getRadius()+thickness_)*(P.getRadius()+thickness_)<<std::endl;
         return false;
     }
     Vec3D ContactPoint;
     distance = sqrt(distanceSquared) - thickness_;
     ContactPoint.X = start_.X + r_ * cos(2.0 * constants::pi * (offset_ + n_ * q));
     ContactPoint.Y = start_.Y + r_ * sin(2.0 * constants::pi * (offset_ + n_ * q));
     ContactPoint.Z = start_.Z + q * l_;
     normal_return = ContactPoint - p.getPosition();
     normal_return /= normal_return.getLength();
     return true;
 }
References alpha, atan2(), cos(), e(), boost::multiprecision::fabs(), Vec3D::getLength(), k, l_, n_, offset_, p, constants::pi, Eigen::bfloat16_impl::pow(), Eigen::numext::q, R, r_, Eigen::bfloat16_impl::round(), sin(), constants::sqr_pi, sqrt(), mathsFunc::square(), start_, thickness_, Vec3D::X, Vec3D::Y, and Vec3D::Z.
getName()
std::string Coil::getName () const override virtual
Returns the name of the object, in this case the string "Coil".
Returns
The string "Coil".
Implements BaseObject.
 {
     return "Coil";
 }
move_time()
void Coil::move_time (Mdouble dt)
Rotate the Coil for a period dt, so that the offset_ changes with omega_*dt.
Parameters
[in] dt The time for which the Screw has to be turned.
 {
     offset_ += omega_ * dt;
 }
References offset_, and omega_.
Referenced by CoilSelfTest::actionsBeforeTimeStep().
oldRead()
void Coil::oldRead (std::istream & is)
Reads an old-style Coil from an input stream, for example an old restart file.
Deprecated:
If you have old restart files, please convert them to the current version of the restart files and use read(std::istream&) instead of oldRead(std::istream&).
Parameters
[in,out] is The input stream from which the Coil is read.
 {
     std::string dummy;
     is >> dummy >> start_
        >> dummy >> l_
        >> dummy >> r_ >> dummy >> n_
        >> dummy >> omega_
        >> dummy >> offset_;
 }
References l_, n_, offset_, omega_, r_, start_, and oomph::Global_string_for_annotation::string().
read()
void Coil::read (std::istream & is) override virtual
Reads a Coil from an input stream, for example a restart file.
Parameters
[in,out] is The input stream from which the Coil is read.
Reimplemented from BaseWall.
 {
     BaseWall::read(is);
     std::string dummy;
     is >> dummy >> start_
        >> dummy >> l_
        >> dummy >> r_
        >> dummy >> n_
        >> dummy >> omega_
        >> dummy >> thickness_
        >> dummy >> offset_;
 }
References l_, n_, offset_, omega_, r_, BaseWall::read(), start_, oomph::Global_string_for_annotation::string(), and thickness_.
set()
void Coil::set (Vec3D start, Mdouble length, Mdouble radius, Mdouble numberOfRevelations, Mdouble omega, Mdouble thickness)
Set all parameters of this Coil.
Set the parameters of this Coil by assigning all input parameters to the data-members of this class, and setting the offset_ to 0.
Parameters
[in] start A Vec3D which denotes the centre of the lower end of the Coil.
[in] length The length of the Coil, must be positive.
[in] radius The radius of the Coil, must be positive.
[in] numberOfRevelations The number of revelations of the Coil, must be positive.
[in] omega The rotation speed of the Coil in rev/s.
[in] thickness The thickness of the "spiral" of the Coil, must be non-negative.
 {
     start_ = start;
     l_ = length;
     r_ = radius;
     n_ = numberOfRevelations;
     omega_ = omega;
     thickness_ = thickness;
     offset_ = 0.0;
 }
References l_, n_, offset_, Eigen::internal::omega(), omega_, r_, UniformPSDSelfTest::radius, oomph::CumulativeTimings::start(), start_, and thickness_.
Referenced by CoilSelfTest::setupInitialConditions().
write()
void Coil::write (std::ostream & os) const override virtual
Writes a Coil to an output stream, for example a restart file.
Parameters
[in,out] os The outpus stream to which the Coil is written.
Reimplemented from BaseWall.
 {
     BaseWall::write(os);
     os << " Start " << start_
        << " Length " << l_
        << " Radius " << r_
        << " Revolutions " << n_
        << " Omega " << omega_
        << " Thickness " << thickness_
        << " Offset " << offset_;
 }
References l_, n_, offset_, omega_, r_, start_, thickness_, and BaseWall::write().
Member Data Documentation
l_
Mdouble Coil::l_ private
The length of the Coil.
Referenced by Coil(), getDistanceAndNormal(), oldRead(), read(), set(), and write().
n_
Mdouble Coil::n_ private
The number of revelations of the Coil.
Referenced by Coil(), getDistanceAndNormal(), oldRead(), read(), set(), and write().
offset_
Mdouble Coil::offset_ private
The amount the Coil has rotated, this is a number between 0 and 1.
Referenced by Coil(), getDistanceAndNormal(), move_time(), oldRead(), read(), set(), and write().
omega_
Mdouble Coil::omega_ private
The rotation speed of the Coil, in rev/s.
Referenced by Coil(), move_time(), oldRead(), read(), set(), and write().
r_
Mdouble Coil::r_ private
The radius of the Coil.
Referenced by Coil(), getDistanceAndNormal(), oldRead(), read(), set(), and write().
start_
Vec3D Coil::start_ private
The centre of the lower end of the Coil.
Referenced by Coil(), getDistanceAndNormal(), oldRead(), read(), set(), and write().
thickness_
Mdouble Coil::thickness_ private
The thickness of the "spiral" of the Coil.
Referenced by Coil(), getDistanceAndNormal(), read(), set(), and write().
The documentation for this class was generated from the following files:
Coil.h
Coil.cc