MercuryDPM: Eigen::internal::scalar_logistic_op_impl< T, EnableIf > Struct Template Reference
Eigen::internal::scalar_logistic_op_impl< T, EnableIf > Struct Template Reference
#include <UnaryFunctors.h>
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T operator() (const T &x) const
template<typename Packet >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet packetOp (const Packet &x) const
Member Function Documentation
operator()()
template<typename T , typename EnableIf = void> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T Eigen::internal::scalar_logistic_op_impl< T, EnableIf >::operator() (const T & x) const inline
 { return packetOp(x); }
References Eigen::internal::scalar_logistic_op_impl< T, EnableIf >::packetOp(), and plotDoE::x.
packetOp()
template<typename T , typename EnableIf = void> template<typename Packet > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet Eigen::internal::scalar_logistic_op_impl< T, EnableIf >::packetOp (const Packet & x) const inline
{
     const Packet one = pset1<Packet>(T(1));
     const Packet inf = pset1<Packet>(NumTraits<T>::infinity());
     const Packet e = pexp(x);
     const Packet inf_mask = pcmp_eq(e, inf);
     return pselect(inf_mask, one, pdiv(e, padd(one, e)));
   }
References e(), constants::inf, Eigen::internal::padd(), Eigen::internal::pcmp_eq(), Eigen::internal::pdiv(), Eigen::internal::pexp(), Eigen::internal::pselect(), and plotDoE::x.
Referenced by Eigen::internal::scalar_logistic_op_impl< T, EnableIf >::operator()().
The documentation for this struct was generated from the following file:
functors/UnaryFunctors.h