MercuryDPM: oomph::TAxisymmetricPoroelasticityElement< ORDER > Class Template Reference
oomph::TAxisymmetricPoroelasticityElement< ORDER > Class Template Reference
#include <Taxisym_poroelasticity_elements.h>
Public Member Functions
TAxisymmetricPoroelasticityElement ()
Constructor.
~TAxisymmetricPoroelasticityElement ()
Destructor.
unsigned required_nvalue (const unsigned &n) const
Number of values required at node n.
unsigned face_index_of_edge (const unsigned &j) const
Return the face index associated with specified edge.
void face_local_coordinate_of_flux_interpolation_point (const unsigned &edge, const unsigned &n, Vector< double > &s) const
unsigned face_index_of_q_edge_basis_fct (const unsigned &j) const
Return the face index associated with j-th edge flux degree of freedom.
unsigned u_index_axisym_poroelasticity (const unsigned &j) const
int q_edge_local_eqn (const unsigned &j) const
Return the equation number of the j-th edge (flux) degree of freedom.
int q_internal_local_eqn (const unsigned &j) const
Return the equation number of the j-th internal degree of freedom.
Vector< Data * > q_edge_data_pt () const
Data * q_internal_data_pt () const
Return pointer to the Data object that stores the internal flux values.
unsigned q_internal_index () const
unsigned q_edge_index (const unsigned &j) const
Return the nodal index at which the jth edge unknown is stored.
unsigned q_edge_node_number (const unsigned &j) const
Return the number of the node where the jth edge unknown is stored.
Node * edge_flux_node_pt (const unsigned &edge)
Get pointer to node that stores the edge flux dofs for specified edge.
double q_edge (const unsigned &j) const
Return the values of the j-th edge (flux) degree of freedom.
double q_edge (const unsigned &t, const unsigned &j) const
double q_internal (const unsigned &j) const
Return the values of the internal degree of freedom.
double q_internal (const unsigned &t, const unsigned &j) const
void pin_q_edge_value (const unsigned &j, const double &value)
Pin the j-th edge (flux) degree of freedom and set it to specified value.
void set_q_edge (const unsigned &j, const double &value)
Set the values of the j-th edge (flux) degree of freedom.
void set_q_edge (const unsigned &t, const unsigned &j, const double &value)
void set_q_internal (const unsigned &j, const double &value)
Set the values of the j-th internal degree of freedom.
void set_q_internal (const unsigned &t, const unsigned &j, const double &value)
unsigned nq_basis_edge () const
Return the number of edge basis functions for flux q.
unsigned nq_basis_internal () const
Return the number of internal basis functions for flux q.
void get_q_basis_local (const Vector< double > &s, Shape &q_basis) const
Returns the local form of the q basis at local coordinate s.
void get_div_q_basis_local (const Vector< double > &s, Shape &div_q_basis_ds) const
unsigned nedge_flux_interpolation_point () const
Vector< double > edge_flux_interpolation_point (const unsigned &edge, const unsigned &j) const
void edge_flux_interpolation_point_global (const unsigned &edge, const unsigned &j, Vector< double > &x) const
void pin_q_internal_value (const unsigned &j, const double &q)
Pin the jth internal q value and set it to specified value.
int p_local_eqn (const unsigned &j) const
Return the equation number of the j-th pressure degree of freedom.
double p_value (const unsigned &j) const
Return the jth pressure value.
unsigned np_basis () const
Return the total number of pressure basis functions.
void get_p_basis (const Vector< double > &s, Shape &p_basis) const
Return the pressure basis.
void pin_p_value (const unsigned &j, const double &p)
Pin the jth pressure value and set to specified value.
Data * p_data_pt () const
Return pointer to the Data object that stores the pressure values.
void set_p_value (const unsigned &j, const double &value)
Set the jth pressure value.
void scale_basis (Shape &basis) const
Scale the edge basis to allow arbitrary edge mappings.
const short & sign_edge (const unsigned &n) const
Accessor for the unit normal sign of edge n (const version)
short & sign_edge (const unsigned &n)
Accessor for the unit normal sign of edge n.
void output (std::ostream &outfile)
Output with default number of plot points.
void output (std::ostream &outfile, const unsigned &Nplot)
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
unsigned nrecovery_order ()
Recovery order for Z2 error estimator.
TAxisymmetricPoroelasticityElement ()
~TAxisymmetricPoroelasticityElement ()
Destructor.
unsigned nq_basis_edge () const
Return the number of edge basis functions for flux q.
unsigned nq_basis_internal () const
Return the number of internal basis functions for flux q.
void get_q_basis_local (const Vector< double > &s, Shape &q_basis) const
Compute the local form of the q basis at local coordinate s.
void get_div_q_basis_local (const Vector< double > &s, Shape &div_q_basis_ds) const
Compute the local form of the q basis and dbasis/ds at local coordinate s.
unsigned nedge_flux_interpolation_point () const
unsigned np_basis () const
Return the total number of pressure basis functions.
void get_p_basis (const Vector< double > &s, Shape &p_basis) const
Return the pressure basis.
TAxisymmetricPoroelasticityElement ()
~TAxisymmetricPoroelasticityElement ()
Destructor.
unsigned nq_basis_edge () const
Return the number of edge basis functions for flux q.
unsigned nq_basis_internal () const
Return the number of internal basis functions for flux q.
void get_q_basis_local (const Vector< double > &s, Shape &q_basis) const
Returns the local form of the q basis at local coordinate s.
void get_div_q_basis_local (const Vector< double > &s, Shape &div_q_basis_ds) const
Returns the local form of the q basis and dbasis/ds at local coordinate s.
unsigned nedge_flux_interpolation_point () const
unsigned np_basis () const
Return the total number of pressure basis functions.
void get_p_basis (const Vector< double > &s, Shape &p_basis) const
Return the pressure basis.
Public Member Functions inherited from oomph::TElement< 2, 3 >
const unsigned Node_on_face [3][2]
Assign the nodal translation schemes.
const unsigned Node_on_face [3][3]
const unsigned Node_on_face [3][4]
const unsigned Node_on_face [4][3]
Assign the nodal translation scheme for linear elements.
const unsigned Node_on_face [4][6]
Assign the nodal translation scheme for quadratic elements.
Public Member Functions inherited from oomph::AxisymmetricPoroelasticityEquations
AxisymmetricPoroelasticityEquations ()
Constructor.
const double & youngs_modulus () const
double *& youngs_modulus_pt ()
const double & nu () const
Access function for Poisson's ratio.
double *& nu_pt ()
Access function for pointer to Poisson's ratio.
const double & lambda_sq () const
Access function for timescale ratio (nondim density)
double *& lambda_sq_pt ()
Access function for pointer to timescale ratio (nondim density)
const double & density_ratio () const
Access function for the density ratio (fluid to solid)
double *& density_ratio_pt ()
Access function for pointer to the density ratio (fluid to solid)
const double & permeability () const
Access function for the nondim permeability.
double *& permeability_pt ()
Access function for pointer to the nondim permeability.
const double & permeability_ratio () const
double *& permeability_ratio_pt ()
const double & alpha () const
Access function for alpha, the Biot parameter.
double *& alpha_pt ()
Access function for pointer to alpha, the Biot parameter.
const double & porosity () const
Access function for the porosity.
double *& porosity_pt ()
Access function for pointer to the porosity.
SourceFctPt & solid_body_force_fct_pt ()
Access function: Pointer to solid body force function.
SourceFctPt solid_body_force_fct_pt () const
Access function: Pointer to solid body force function (const version)
SourceFctPt & fluid_body_force_fct_pt ()
Access function: Pointer to fluid force function.
SourceFctPt fluid_body_force_fct_pt () const
Access function: Pointer to fluid force function (const version)
MassSourceFctPt & mass_source_fct_pt ()
Access function: Pointer to mass source function.
MassSourceFctPt mass_source_fct_pt () const
Access function: Pointer to mass source function (const version)
void solid_body_force (const double &time, const Vector< double > &x, Vector< double > &b) const
void fluid_body_force (const double &time, const Vector< double > &x, Vector< double > &b) const
void mass_source (const double &time, const Vector< double > &x, double &b) const
virtual unsigned nq_basis () const
Return the total number of computational basis functions for q.
void get_q_basis (const Vector< double > &s, Shape &q_basis) const
Compute the transformed basis at local coordinate s.
double transform_basis (const Vector< double > &s, const Shape &q_basis_local, Shape &psi, DShape &dpsi, Shape &q_basis) const
double transform_basis (const Vector< double > &s, const Shape &q_basis_local, Shape &psi, Shape &q_basis) const
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Fill in contribution to residuals for the Darcy equations.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Fill in the Jacobian matrix for the Newton method.
double interpolated_div_du_dt (const Vector< double > &s, Vector< double > &div_dudt_components) const
double interpolated_div_u (const Vector< double > &s, Vector< double > &div_u_components) const
void interpolated_u (const Vector< double > &s, Vector< double > &disp) const
Calculate the FE representation of u.
double interpolated_u (const Vector< double > &s, const unsigned &i) const
Calculate the FE representation of the i-th component of u.
double interpolated_u (const unsigned &t, const Vector< double > &s, const unsigned &i) const
void interpolated_du_dt (const Vector< double > &s, Vector< double > &du_dt) const
Calculate the FE representation of du_dt.
void interpolated_q (const Vector< double > &s, Vector< double > &q) const
Calculate the FE representation of q.
void interpolated_q (const unsigned &t, const Vector< double > &s, Vector< double > &q) const
double interpolated_q (const Vector< double > &s, const unsigned i) const
Calculate the FE representation of the i-th component of q.
double interpolated_q (const unsigned &t, const Vector< double > &s, const unsigned i) const
void interpolated_div_q (const Vector< double > &s, double &div_q) const
Calculate the FE representation of div u.
double interpolated_div_q (const Vector< double > &s) const
Calculate the FE representation of div q and return it.
void interpolated_p (const Vector< double > &s, double &p) const
Calculate the FE representation of p.
double interpolated_p (const Vector< double > &s) const
Calculate the FE representation of p and return it.
double du_dt (const unsigned &n, const unsigned &i) const
du/dt at local node n
double d2u_dt2 (const unsigned &n, const unsigned &i) const
d^2u/dt^2 at local node n
double dq_edge_dt (const unsigned &n) const
dq_edge/dt for the n-th edge degree of freedom
double dq_internal_dt (const unsigned &n) const
dq_internal/dt for the n-th internal degree of freedom
void set_q_internal_timestepper (TimeStepper *const time_stepper_pt)
Set the timestepper of the q internal data object.
bool darcy_is_switched_off ()
Is Darcy flow switched off?
void switch_off_darcy ()
Switch off Darcy flow.
unsigned self_test ()
Self test.
unsigned nscalar_paraview () const
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
std::string scalar_name_paraview (const unsigned &i) const
void point_output_data (const Vector< double > &s, Vector< double > &data)
void output_with_projected_flux (std::ostream &outfile, const unsigned &nplot, const Vector< double > unit_normal)
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
unsigned num_Z2_flux_terms ()
Number off flux terms for Z2 error estimator (use Darcy flux)
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
Z2 flux (use Darcy flux)
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
virtual void disable_ALE ()
virtual void enable_ALE ()
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output (FILE *file_pt)
virtual void output (FILE *file_pt, const unsigned &n_plot)
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::ElementWithZ2ErrorEstimator
ElementWithZ2ErrorEstimator ()
Default empty constructor.
ElementWithZ2ErrorEstimator (const ElementWithZ2ErrorEstimator &)=delete
Broken copy constructor.
void operator= (const ElementWithZ2ErrorEstimator &)=delete
Broken assignment operator.
virtual unsigned ncompound_fluxes ()
virtual void compute_exact_Z2_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_flux_pt, double &error, double &norm)
virtual void get_Z2_compound_flux_indices (Vector< unsigned > &flux_index)
virtual double geometric_jacobian (const Vector< double > &x)
Protected Member Functions
double shape_basis_test_local (const Vector< double > &s, Shape &psi, DShape &dpsi, Shape &u_basis, Shape &u_test, DShape &du_basis_dx, DShape &du_test_dx, Shape &q_basis, Shape &q_test, Shape &p_basis, Shape &p_test, Shape &div_q_basis_ds, Shape &div_q_test_ds) const
double shape_basis_test_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, Shape &u_basis, Shape &u_test, DShape &du_basis_dx, DShape &du_test_dx, Shape &q_basis, Shape &q_test, Shape &p_basis, Shape &p_test, Shape &div_q_basis_ds, Shape &div_q_test_ds) const
Protected Member Functions inherited from oomph::AxisymmetricPoroelasticityEquations
virtual void fill_in_generic_residual_contribution (Vector< double > &residuals, DenseMatrix< double > &jacobian, bool flag)
Fill in residuals and, if flag==true, jacobian.
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Private Member Functions
const unsigned Initial_Nvalue [6]
The number of values stored at each node.
const unsigned Face_index_of_edge_flux [3]
Face index associated with edge flux degree of freedom.
const unsigned Q_edge_conv [3]
const double Flux_interpolation_point [1]
The points along each edge where the fluxes are taken to be.
const unsigned Initial_Nvalue [6]
The number of values stored at each node.
const unsigned Face_index_of_edge_flux [3]
Face index associated with edge flux degree of freedom.
const unsigned Q_edge_conv [3]
const double Flux_interpolation_point [2]
The points along each edge where the fluxes are taken to be.
Private Attributes
unsigned Q_internal_data_index
unsigned P_internal_data_index
The internal data index where the p degrees of freedom are stored.
std::vector< short > Sign_edge
Static Private Attributes
static const unsigned Initial_Nvalue []
The number of values stored at each node.
static const unsigned Face_index_of_edge_flux []
Face index associated with edge flux degree of freedom.
static const unsigned Q_edge_conv []
static const double Flux_interpolation_point []
The points along each edge where the fluxes are taken to be.
Additional Inherited Members
Public Types inherited from oomph::AxisymmetricPoroelasticityEquations
typedef void(* SourceFctPt) (const double &time, const Vector< double > &x, Vector< double > &f)
Source function pointer typedef.
typedef void(* MassSourceFctPt) (const double &time, const Vector< double > &x, double &f)
Mass source function pointer typedef.
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
template<unsigned ORDER>
class oomph::TAxisymmetricPoroelasticityElement< ORDER >
================================================================= Element which solves the Darcy/linear elasticity equations using TElements Geometrically the element is always a six noded triangle. We use the mid-side nodes to store edge-based flux degrees of freedom and internal data for the discontinuous pressure
and internal flux dofs.
Constructor & Destructor Documentation
TAxisymmetricPoroelasticityElement() [1/3]
template<unsigned ORDER> oomph::TAxisymmetricPoroelasticityElement< ORDER >::TAxisymmetricPoroelasticityElement ()
Constructor.
~TAxisymmetricPoroelasticityElement() [1/3]
template<unsigned ORDER> oomph::TAxisymmetricPoroelasticityElement< ORDER >::~TAxisymmetricPoroelasticityElement ()
Destructor.
TAxisymmetricPoroelasticityElement() [2/3]
oomph::TAxisymmetricPoroelasticityElement< 0 >::TAxisymmetricPoroelasticityElement ()
/////////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////////// Lowest-order Raviart-Thomas based Darcy/axisym lin elast equation element /////////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////////// Constructor. Order 0 elements have 1 pressure dof and no internal flux dofs
     : TElement<2, 3>(), AxisymmetricPoroelasticityEquations(), Sign_edge(3, 1)
   {
     P_internal_data_index = this->add_internal_data(new Data(1));
   }
References oomph::GeneralisedElement::add_internal_data(), and oomph::TAxisymmetricPoroelasticityElement< ORDER >::P_internal_data_index.
~TAxisymmetricPoroelasticityElement() [2/3]
oomph::TAxisymmetricPoroelasticityElement< 0 >::~TAxisymmetricPoroelasticityElement ()
Destructor.
   {
   }
TAxisymmetricPoroelasticityElement() [3/3]
oomph::TAxisymmetricPoroelasticityElement< 1 >::TAxisymmetricPoroelasticityElement ()
//////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////// Second-orderRaviart-Thomas based Darcy/axisym lin elast equation element //////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////// Constructor. Order 1 elements have 3 pressure dofs and 2 internal velocity dofs
     : TElement<2, 3>(), AxisymmetricPoroelasticityEquations(), Sign_edge(3, 1)
   {
     // RT_1 elements have 2 internal degrees of freedom for u, and 3 for p
     Q_internal_data_index = this->add_internal_data(new Data(2));
     P_internal_data_index = this->add_internal_data(new Data(3));
   }
References oomph::GeneralisedElement::add_internal_data(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::P_internal_data_index, and oomph::TAxisymmetricPoroelasticityElement< ORDER >::Q_internal_data_index.
~TAxisymmetricPoroelasticityElement() [3/3]
oomph::TAxisymmetricPoroelasticityElement< 1 >::~TAxisymmetricPoroelasticityElement ()
Destructor.
   {
   }
Member Function Documentation
edge_flux_interpolation_point()
template<unsigned ORDER> Vector<double> oomph::TAxisymmetricPoroelasticityElement< ORDER >::edge_flux_interpolation_point (const unsigned & edge, const unsigned & j) const inline virtual
Returns the local coordinate of the jth flux_interpolation point along specified edge
Implements oomph::AxisymmetricPoroelasticityEquations.
     {
 #ifdef RANGE_CHECKING
       if (edge >= 3)
       {
         std::ostringstream error_message;
         error_message << "Range Error: edge " << edge
                       << " is not in the range (0,2)";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
       if (j >= nedge_flux_interpolation_point())
       {
         std::ostringstream error_message;
         error_message << "Range Error: j " << j << " is not in the range (0,"
                       << nedge_flux_interpolation_point() - 1 << ")";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       Vector<double> coord(1);
       coord[0] = (1.0 - sign_edge(edge)) / 2.0 +
                  sign_edge(edge) * Flux_interpolation_point[j];
       return coord;
     }
References oomph::TAxisymmetricPoroelasticityElement< ORDER >::Flux_interpolation_point, j, oomph::TAxisymmetricPoroelasticityElement< ORDER >::nedge_flux_interpolation_point(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::TAxisymmetricPoroelasticityElement< ORDER >::sign_edge().
Referenced by oomph::TAxisymmetricPoroelasticityElement< ORDER >::edge_flux_interpolation_point_global(), and oomph::TAxisymmetricPoroelasticityElement< ORDER >::face_local_coordinate_of_flux_interpolation_point().
edge_flux_interpolation_point_global()
template<unsigned ORDER> void oomph::TAxisymmetricPoroelasticityElement< ORDER >::edge_flux_interpolation_point_global (const unsigned & edge, const unsigned & j, Vector< double > & x) const inline virtual
Compute the global coordinates of the jth flux_interpolation point along specified edge
Implements oomph::AxisymmetricPoroelasticityEquations.
     {
 #ifdef RANGE_CHECKING
       if (edge >= 3)
       {
         std::ostringstream error_message;
         error_message << "Range Error: edge " << edge
                       << " is not in the range (0,2)";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
       if (j >= nedge_flux_interpolation_point())
       {
         std::ostringstream error_message;
         error_message << "Range Error: j " << j << " is not in the range (0,"
                       << nedge_flux_interpolation_point() - 1 << ")";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // Get the location of the n-th flux_interpolation point along the
       // edge in terms of the distance along the edge itself
       Vector<double> flux_interpolation_point =
         edge_flux_interpolation_point(edge, j);
       // Convert the edge number to the number of the mid-edge node along that
       // edge
       unsigned node_number = Q_edge_conv[edge];
       // Storage for the local coords of the flux_interpolation point
       Vector<double> s_flux_interpolation(2, 0);
       // The edge basis functions are defined in a clockwise manner, so we have
       // to effectively "flip" the coordinates along edges 0 and 1 to match this
       switch (node_number)
       {
         case 3:
           s_flux_interpolation[0] = 1.0 - flux_interpolation_point[0];
           s_flux_interpolation[1] = flux_interpolation_point[0];
           break;
         case 4:
           s_flux_interpolation[0] = 0.0;
           s_flux_interpolation[1] = 1.0 - flux_interpolation_point[0];
           break;
         case 5:
           s_flux_interpolation[0] = flux_interpolation_point[0];
           s_flux_interpolation[1] = 0.0;
           break;
       }
       // Calculate the global coordinates from the local ones
       interpolated_x(s_flux_interpolation, x);
     }
References oomph::TAxisymmetricPoroelasticityElement< ORDER >::edge_flux_interpolation_point(), oomph::FiniteElement::interpolated_x(), j, oomph::TAxisymmetricPoroelasticityElement< ORDER >::nedge_flux_interpolation_point(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::TAxisymmetricPoroelasticityElement< ORDER >::Q_edge_conv, and plotDoE::x.
edge_flux_node_pt()
template<unsigned ORDER> Node* oomph::TAxisymmetricPoroelasticityElement< ORDER >::edge_flux_node_pt (const unsigned & edge) inline
Get pointer to node that stores the edge flux dofs for specified edge.
     {
       return node_pt(Q_edge_conv[edge]);
     }
References oomph::FiniteElement::node_pt(), and oomph::TAxisymmetricPoroelasticityElement< ORDER >::Q_edge_conv.
face_index_of_edge()
template<unsigned ORDER> unsigned oomph::TAxisymmetricPoroelasticityElement< ORDER >::face_index_of_edge (const unsigned & j) const inline virtual
Return the face index associated with specified edge.
Implements oomph::AxisymmetricPoroelasticityEquations.
     {
       return (j + 2) % 3;
     }
References j.
Face_index_of_edge_flux() [1/2]
const unsigned oomph::TAxisymmetricPoroelasticityElement< 0 >::Face_index_of_edge_flux private
Face index associated with edge flux degree of freedom.
Face_index_of_edge_flux() [2/2]
const unsigned oomph::TAxisymmetricPoroelasticityElement< 1 >::Face_index_of_edge_flux private
Face index associated with edge flux degree of freedom.
face_index_of_q_edge_basis_fct()
template<unsigned ORDER> unsigned oomph::TAxisymmetricPoroelasticityElement< ORDER >::face_index_of_q_edge_basis_fct (const unsigned & j) const inline virtual
Return the face index associated with j-th edge flux degree of freedom.
Implements oomph::AxisymmetricPoroelasticityEquations.
     {
       return Face_index_of_edge_flux[j];
     }
References oomph::TAxisymmetricPoroelasticityElement< ORDER >::Face_index_of_edge_flux, and j.
face_local_coordinate_of_flux_interpolation_point()
template<unsigned ORDER> void oomph::TAxisymmetricPoroelasticityElement< ORDER >::face_local_coordinate_of_flux_interpolation_point (const unsigned & edge, const unsigned & n, Vector< double > & s) const inline virtual
Compute the face element coordinates of the nth flux interpolation point along specified edge
Implements oomph::AxisymmetricPoroelasticityEquations.
     {
       // Get the location of the n-th flux interpolation point along
       // the edge in terms of the distance along the edge itself
       Vector<double> flux_interpolation_point =
         edge_flux_interpolation_point(edge, n);
       // Convert the edge number to the number of the mid-edge node along that
       // edge
       unsigned node_number = Q_edge_conv[edge];
       // The edge basis functions are defined in a clockwise manner, so we have
       // to effectively "flip" some coordinates
       switch (node_number)
       {
         case 3:
           s[0] = flux_interpolation_point[0];
           break;
         case 4:
           s[0] = 1.0 - flux_interpolation_point[0];
           break;
         case 5:
           s[0] = flux_interpolation_point[0];
           break;
       }
     }
References oomph::TAxisymmetricPoroelasticityElement< ORDER >::edge_flux_interpolation_point(), n, oomph::TAxisymmetricPoroelasticityElement< ORDER >::Q_edge_conv, and s.
Flux_interpolation_point() [1/2]
const double oomph::TAxisymmetricPoroelasticityElement< 0 >::Flux_interpolation_point private
The points along each edge where the fluxes are taken to be.
Flux_interpolation_point() [2/2]
const double oomph::TAxisymmetricPoroelasticityElement< 1 >::Flux_interpolation_point private
The points along each edge where the fluxes are taken to be.
References sqrt().
get_div_q_basis_local() [1/3]
void oomph::TAxisymmetricPoroelasticityElement< 0 >::get_div_q_basis_local (const Vector< double > & s, Shape & div_q_basis_ds) const virtual
Compute the local form of the q basis and dbasis/ds at local coordinate s.
Implements oomph::AxisymmetricPoroelasticityEquations.
   {
     div_q_basis_ds(0) = Sign_edge[0] * 2 * std::sqrt(2);
     div_q_basis_ds(1) = Sign_edge[1] * 2;
     div_q_basis_ds(2) = Sign_edge[2] * 2;
     // Scale the basis by the ratio of the length of the edge to the length of
     // the corresponding edge on the reference element
     scale_basis(div_q_basis_ds);
   }
References sqrt().
get_div_q_basis_local() [2/3]
void oomph::TAxisymmetricPoroelasticityElement< 1 >::get_div_q_basis_local (const Vector< double > & s, Shape & div_q_basis_ds) const virtual
Returns the local form of the q basis and dbasis/ds at local coordinate s.
Implements oomph::AxisymmetricPoroelasticityEquations.
   {
     Vector<double> g1_vect, g2_vect;
     g1_vect = edge_flux_interpolation_point(0, 0);
     g2_vect = edge_flux_interpolation_point(0, 1);
     double g1 = g1_vect[0];
     double g2 = g2_vect[0];
     div_q_basis_ds(0) =
       Sign_edge[0] * std::sqrt(2.0) * (3.0 * s[1] - 2.0 * g2) / (g1 - g2);
     div_q_basis_ds(1) =
       Sign_edge[0] * std::sqrt(2.0) * (2.0 * g1 - 3.0 * s[1]) / (g1 - g2);
     g1_vect = edge_flux_interpolation_point(1, 0);
     g2_vect = edge_flux_interpolation_point(1, 1);
     g1 = g1_vect[0];
     g2 = g2_vect[0];
     div_q_basis_ds(2) = Sign_edge[1] * (2.0 * g1 - 3.0 * s[1]) / (g1 - g2);
     div_q_basis_ds(3) = Sign_edge[1] * (3.0 * s[1] - 2.0 * g2) / (g1 - g2);
     g1_vect = edge_flux_interpolation_point(2, 0);
     g2_vect = edge_flux_interpolation_point(2, 1);
     g1 = g1_vect[0];
     g2 = g2_vect[0];
     div_q_basis_ds(4) = Sign_edge[2] * (3.0 * s[0] - 2.0 * g2) / (g1 - g2);
     div_q_basis_ds(5) = Sign_edge[2] * (2.0 * g1 - 3.0 * s[0]) / (g1 - g2);
     div_q_basis_ds(6) = 3.0 * s[1] - 1.0;
     div_q_basis_ds(7) = 3.0 * s[0] - 1.0;
     // Scale the basis by the ratio of the length of the edge to the length of
     // the corresponding edge on the reference element
     scale_basis(div_q_basis_ds);
   }
References s, and sqrt().
get_div_q_basis_local() [3/3]
template<unsigned ORDER> void oomph::TAxisymmetricPoroelasticityElement< ORDER >::get_div_q_basis_local (const Vector< double > & s, Shape & div_q_basis_ds) const virtual
Returns the local form of the q basis and dbasis/ds at local coordinate s
Implements oomph::AxisymmetricPoroelasticityEquations.
Referenced by oomph::TAxisymmetricPoroelasticityElement< ORDER >::shape_basis_test_local().
get_p_basis() [1/3]
void oomph::TAxisymmetricPoroelasticityElement< 0 >::get_p_basis (const Vector< double > & s, Shape & p_basis) const virtual
Return the pressure basis.
Implements oomph::AxisymmetricPoroelasticityEquations.
   {
     p_basis(0) = 1.0;
   }
get_p_basis() [2/3]
void oomph::TAxisymmetricPoroelasticityElement< 1 >::get_p_basis (const Vector< double > & s, Shape & p_basis) const virtual
Return the pressure basis.
Implements oomph::AxisymmetricPoroelasticityEquations.
   {
     p_basis(0) = 1.0;
     p_basis(1) = s[0];
     p_basis(2) = s[1];
   }
References s.
get_p_basis() [3/3]
template<unsigned ORDER> void oomph::TAxisymmetricPoroelasticityElement< ORDER >::get_p_basis (const Vector< double > & s, Shape & p_basis) const virtual
Return the pressure basis.
Implements oomph::AxisymmetricPoroelasticityEquations.
Referenced by oomph::TAxisymmetricPoroelasticityElement< ORDER >::shape_basis_test_local().
get_q_basis_local() [1/3]
void oomph::TAxisymmetricPoroelasticityElement< 0 >::get_q_basis_local (const Vector< double > & s, Shape & q_basis) const virtual
Compute the local form of the q basis at local coordinate s.
Implements oomph::AxisymmetricPoroelasticityEquations.
   {
     // RT_0 basis functions
     q_basis(0, 0) = Sign_edge[0] * std::sqrt(2) * s[0];
     q_basis(0, 1) = Sign_edge[0] * std::sqrt(2) * s[1];
     q_basis(1, 0) = Sign_edge[1] * (s[0] - 1);
     q_basis(1, 1) = Sign_edge[1] * s[1];
     q_basis(2, 0) = Sign_edge[2] * s[0];
     q_basis(2, 1) = Sign_edge[2] * (s[1] - 1);
   }
References s, and sqrt().
get_q_basis_local() [2/3]
void oomph::TAxisymmetricPoroelasticityElement< 1 >::get_q_basis_local (const Vector< double > & s, Shape & q_basis) const virtual
Returns the local form of the q basis at local coordinate s.
Implements oomph::AxisymmetricPoroelasticityEquations.
   {
     // RT_1 basis functions
     Vector<double> g1_vect, g2_vect;
     g1_vect = edge_flux_interpolation_point(0, 0);
     g2_vect = edge_flux_interpolation_point(0, 1);
     double g1 = g1_vect[0];
     double g2 = g2_vect[0];
     q_basis(0, 0) =
       Sign_edge[0] * std::sqrt(2.0) * s[0] * (s[1] - g2) / (g1 - g2);
     q_basis(0, 1) =
       Sign_edge[0] * std::sqrt(2.0) * s[1] * (s[1] - g2) / (g1 - g2);
     q_basis(1, 0) =
       Sign_edge[0] * std::sqrt(2.0) * s[0] * (s[1] - g1) / (g2 - g1);
     q_basis(1, 1) =
       Sign_edge[0] * std::sqrt(2.0) * s[1] * (s[1] - g1) / (g2 - g1);
     g1_vect = edge_flux_interpolation_point(1, 0);
     g2_vect = edge_flux_interpolation_point(1, 1);
     g1 = g1_vect[0];
     g2 = g2_vect[0];
     q_basis(2, 0) = Sign_edge[1] * (s[0] - 1.0) * (s[1] - g1) / (g2 - g1);
     q_basis(2, 1) = Sign_edge[1] * s[1] * (s[1] - g1) / (g2 - g1);
     q_basis(3, 0) = Sign_edge[1] * (s[0] - 1.0) * (s[1] - g2) / (g1 - g2);
     q_basis(3, 1) = Sign_edge[1] * s[1] * (s[1] - g2) / (g1 - g2);
     g1_vect = edge_flux_interpolation_point(2, 0);
     g2_vect = edge_flux_interpolation_point(2, 1);
     g1 = g1_vect[0];
     g2 = g2_vect[0];
     q_basis(4, 0) = Sign_edge[2] * s[0] * (s[0] - g2) / (g1 - g2);
     q_basis(4, 1) = Sign_edge[2] * (s[1] - 1.0) * (s[0] - g2) / (g1 - g2);
     q_basis(5, 0) = Sign_edge[2] * s[0] * (s[0] - g1) / (g2 - g1);
     q_basis(5, 1) = Sign_edge[2] * (s[1] - 1.0) * (s[0] - g1) / (g2 - g1);
     q_basis(6, 0) = s[1] * s[0];
     q_basis(6, 1) = s[1] * (s[1] - 1.0);
     q_basis(7, 0) = s[0] * (s[0] - 1.0);
     q_basis(7, 1) = s[0] * s[1];
   }
References s, and sqrt().
get_q_basis_local() [3/3]
template<unsigned ORDER> void oomph::TAxisymmetricPoroelasticityElement< ORDER >::get_q_basis_local (const Vector< double > & s, Shape & q_basis) const virtual
Returns the local form of the q basis at local coordinate s.
Implements oomph::AxisymmetricPoroelasticityEquations.
Referenced by oomph::TAxisymmetricPoroelasticityElement< ORDER >::shape_basis_test_local().
Initial_Nvalue() [1/2]
const unsigned oomph::TAxisymmetricPoroelasticityElement< 0 >::Initial_Nvalue private
The number of values stored at each node.
Initial_Nvalue() [2/2]
const unsigned oomph::TAxisymmetricPoroelasticityElement< 1 >::Initial_Nvalue private
The number of values stored at each node.
nedge_flux_interpolation_point() [1/3]
unsigned oomph::TAxisymmetricPoroelasticityElement< 0 >::nedge_flux_interpolation_point () const virtual
Return the number of flux_interpolation points along each edge of the element
Implements oomph::AxisymmetricPoroelasticityEquations.
   {
     return 1;
   }
nedge_flux_interpolation_point() [2/3]
unsigned oomph::TAxisymmetricPoroelasticityElement< 1 >::nedge_flux_interpolation_point () const virtual
Returns the number of flux_interpolation points along each edge of the element
Implements oomph::AxisymmetricPoroelasticityEquations.
   {
     return 2;
   }
nedge_flux_interpolation_point() [3/3]
template<unsigned ORDER> unsigned oomph::TAxisymmetricPoroelasticityElement< ORDER >::nedge_flux_interpolation_point () const virtual
Returns the number of flux_interpolation points along each edge of the element
Implements oomph::AxisymmetricPoroelasticityEquations.
Referenced by oomph::TAxisymmetricPoroelasticityElement< ORDER >::edge_flux_interpolation_point(), and oomph::TAxisymmetricPoroelasticityElement< ORDER >::edge_flux_interpolation_point_global().
np_basis() [1/3]
unsigned oomph::TAxisymmetricPoroelasticityElement< 0 >::np_basis () const virtual
Return the total number of pressure basis functions.
Implements oomph::AxisymmetricPoroelasticityEquations.
   {
     return 1;
   }
np_basis() [2/3]
unsigned oomph::TAxisymmetricPoroelasticityElement< 1 >::np_basis () const virtual
Return the total number of pressure basis functions.
Implements oomph::AxisymmetricPoroelasticityEquations.
   {
     return 3;
   }
np_basis() [3/3]
template<unsigned ORDER> unsigned oomph::TAxisymmetricPoroelasticityElement< ORDER >::np_basis () const virtual
Return the total number of pressure basis functions.
Implements oomph::AxisymmetricPoroelasticityEquations.
Referenced by oomph::TAxisymmetricPoroelasticityElement< ORDER >::p_local_eqn(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::p_value(), and oomph::TAxisymmetricPoroelasticityElement< ORDER >::pin_p_value().
nq_basis_edge() [1/3]
unsigned oomph::TAxisymmetricPoroelasticityElement< 0 >::nq_basis_edge () const virtual
Return the number of edge basis functions for flux q.
Implements oomph::AxisymmetricPoroelasticityEquations.
   {
     return 3;
   }
nq_basis_edge() [2/3]
unsigned oomph::TAxisymmetricPoroelasticityElement< 1 >::nq_basis_edge () const virtual
Return the number of edge basis functions for flux q.
Implements oomph::AxisymmetricPoroelasticityEquations.
   {
     return 6;
   }
nq_basis_edge() [3/3]
template<unsigned ORDER> unsigned oomph::TAxisymmetricPoroelasticityElement< ORDER >::nq_basis_edge () const virtual
Return the number of edge basis functions for flux q.
Implements oomph::AxisymmetricPoroelasticityEquations.
Referenced by oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_edge(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_edge_index(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_edge_local_eqn(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_edge_node_number(), and oomph::TAxisymmetricPoroelasticityElement< ORDER >::scale_basis().
nq_basis_internal() [1/3]
unsigned oomph::TAxisymmetricPoroelasticityElement< 0 >::nq_basis_internal () const virtual
Return the number of internal basis functions for flux q.
Implements oomph::AxisymmetricPoroelasticityEquations.
   {
     return 0;
   }
nq_basis_internal() [2/3]
unsigned oomph::TAxisymmetricPoroelasticityElement< 1 >::nq_basis_internal () const virtual
Return the number of internal basis functions for flux q.
Implements oomph::AxisymmetricPoroelasticityEquations.
   {
     return 2;
   }
nq_basis_internal() [3/3]
template<unsigned ORDER> unsigned oomph::TAxisymmetricPoroelasticityElement< ORDER >::nq_basis_internal () const virtual
Return the number of internal basis functions for flux q.
Implements oomph::AxisymmetricPoroelasticityEquations.
Referenced by oomph::TAxisymmetricPoroelasticityElement< ORDER >::pin_q_internal_value(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_internal(), and oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_internal_local_eqn().
nrecovery_order()
template<unsigned ORDER> unsigned oomph::TAxisymmetricPoroelasticityElement< ORDER >::nrecovery_order () inline virtual
Recovery order for Z2 error estimator.
Implements oomph::ElementWithZ2ErrorEstimator.
     {
       return 2; // need to experiment with this...
     }
nvertex_node()
template<unsigned ORDER> unsigned oomph::TAxisymmetricPoroelasticityElement< ORDER >::nvertex_node () const inline virtual
Number of vertex nodes in the element.
Reimplemented from oomph::FiniteElement.
     {
       return TElement<2, 3>::nvertex_node();
     }
output() [1/2]
template<unsigned ORDER> void oomph::TAxisymmetricPoroelasticityElement< ORDER >::output (std::ostream & outfile) inline virtual
Output with default number of plot points.
Reimplemented from oomph::AxisymmetricPoroelasticityEquations.
     {
       AxisymmetricPoroelasticityEquations::output(outfile);
     }
References oomph::AxisymmetricPoroelasticityEquations::output().
output() [2/2]
template<unsigned ORDER> void oomph::TAxisymmetricPoroelasticityElement< ORDER >::output (std::ostream & outfile, const unsigned & Nplot) inline virtual
Output FE representation of soln: x,y,u1,u2,div_q,p at Nplot^DIM plot points
Reimplemented from oomph::AxisymmetricPoroelasticityEquations.
     {
       AxisymmetricPoroelasticityEquations::output(outfile, Nplot);
     }
References oomph::AxisymmetricPoroelasticityEquations::output().
p_data_pt()
template<unsigned ORDER> Data* oomph::TAxisymmetricPoroelasticityElement< ORDER >::p_data_pt () const inline virtual
Return pointer to the Data object that stores the pressure values.
Implements oomph::AxisymmetricPoroelasticityEquations.
     {
       return this->internal_data_pt(P_internal_data_index);
     }
References oomph::GeneralisedElement::internal_data_pt().
p_local_eqn()
template<unsigned ORDER> int oomph::TAxisymmetricPoroelasticityElement< ORDER >::p_local_eqn (const unsigned & j) const inline virtual
Return the equation number of the j-th pressure degree of freedom.
Implements oomph::AxisymmetricPoroelasticityEquations.
     {
 #ifdef RANGE_CHECKING
       if (j >= np_basis())
       {
         std::ostringstream error_message;
         error_message << "Range Error: j " << j << " is not in the range (0,"
                       << np_basis() - 1 << ")";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       return this->internal_local_eqn(P_internal_data_index, j);
     }
References oomph::GeneralisedElement::internal_local_eqn(), j, oomph::TAxisymmetricPoroelasticityElement< ORDER >::np_basis(), OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
p_value()
template<unsigned ORDER> double oomph::TAxisymmetricPoroelasticityElement< ORDER >::p_value (const unsigned & j) const inline virtual
Return the jth pressure value.
Implements oomph::AxisymmetricPoroelasticityEquations.
     {
 #ifdef RANGE_CHECKING
       if (j >= np_basis())
       {
         std::ostringstream error_message;
         error_message << "Range Error: j " << j << " is not in the range (0,"
                       << np_basis() - 1 << ")";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       return this->internal_data_pt(P_internal_data_index)->value(j);
     }
References oomph::GeneralisedElement::internal_data_pt(), j, oomph::TAxisymmetricPoroelasticityElement< ORDER >::np_basis(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::Data::value().
pin_p_value()
template<unsigned ORDER> void oomph::TAxisymmetricPoroelasticityElement< ORDER >::pin_p_value (const unsigned & j, const double & p) inline virtual
Pin the jth pressure value and set to specified value.
Implements oomph::AxisymmetricPoroelasticityEquations.
     {
 #ifdef RANGE_CHECKING
       if (j >= np_basis())
       {
         std::ostringstream error_message;
         error_message << "Range Error: j " << j << " is not in the range (0,"
                       << np_basis() - 1 << ")";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       this->internal_data_pt(P_internal_data_index)->pin(j);
       this->internal_data_pt(P_internal_data_index)->set_value(j, p);
     }
References oomph::GeneralisedElement::internal_data_pt(), j, oomph::TAxisymmetricPoroelasticityElement< ORDER >::np_basis(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, p, oomph::Data::pin(), and oomph::Data::set_value().
pin_q_edge_value()
template<unsigned ORDER> void oomph::TAxisymmetricPoroelasticityElement< ORDER >::pin_q_edge_value (const unsigned & j, const double & value) inline virtual
Pin the j-th edge (flux) degree of freedom and set it to specified value.
Implements oomph::AxisymmetricPoroelasticityEquations.
     {
       node_pt(q_edge_node_number(j))->pin(q_edge_index(j));
       node_pt(q_edge_node_number(j))->set_value(q_edge_index(j), value);
     }
References j, oomph::FiniteElement::node_pt(), oomph::Data::pin(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_edge_index(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_edge_node_number(), oomph::Data::set_value(), and Eigen::value.
pin_q_internal_value()
template<unsigned ORDER> void oomph::TAxisymmetricPoroelasticityElement< ORDER >::pin_q_internal_value (const unsigned & j, const double & q) inline virtual
Pin the jth internal q value and set it to specified value.
Implements oomph::AxisymmetricPoroelasticityEquations.
     {
 #ifdef RANGE_CHECKING
       if (j >= nq_basis_internal())
       {
         std::ostringstream error_message;
         error_message << "Range Error: j " << j << " is not in the range (0,"
                       << nq_basis_internal() - 1 << ")";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       this->internal_data_pt(q_internal_index())->pin(j);
       this->internal_data_pt(q_internal_index())->set_value(j, q);
     }
References oomph::GeneralisedElement::internal_data_pt(), j, oomph::TAxisymmetricPoroelasticityElement< ORDER >::nq_basis_internal(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::Data::pin(), Eigen::numext::q, oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_internal_index(), and oomph::Data::set_value().
q_edge() [1/2]
template<unsigned ORDER> double oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_edge (const unsigned & j) const inline virtual
Return the values of the j-th edge (flux) degree of freedom.
Implements oomph::AxisymmetricPoroelasticityEquations.
     {
 #ifdef RANGE_CHECKING
       if (j >= (nq_basis_edge()))
       {
         std::ostringstream error_message;
         error_message << "Range Error: j " << j << " is not in the range (0,"
                       << nq_basis_edge() - 1 << ")";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       return nodal_value(q_edge_node_number(j), q_edge_index(j));
     }
References j, oomph::FiniteElement::nodal_value(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::nq_basis_edge(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_edge_index(), and oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_edge_node_number().
q_edge() [2/2]
template<unsigned ORDER> double oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_edge (const unsigned & t, const unsigned & j) const inline virtual
Return the values of the j-th edge (flux) degree of freedom at time history level t
Implements oomph::AxisymmetricPoroelasticityEquations.
     {
 #ifdef RANGE_CHECKING
       if (j >= (nq_basis_edge()))
       {
         std::ostringstream error_message;
         error_message << "Range Error: j " << j << " is not in the range (0,"
                       << nq_basis_edge() - 1 << ")";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       return nodal_value(t, q_edge_node_number(j), q_edge_index(j));
     }
References j, oomph::FiniteElement::nodal_value(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::nq_basis_edge(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_edge_index(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_edge_node_number(), and plotPSD::t.
Q_edge_conv() [1/2]
const unsigned oomph::TAxisymmetricPoroelasticityElement< 0 >::Q_edge_conv private
Conversion scheme from an edge degree of freedom to the node it's stored at
Q_edge_conv() [2/2]
const unsigned oomph::TAxisymmetricPoroelasticityElement< 1 >::Q_edge_conv private
Conversion scheme from an edge degree of freedom to the node it's stored at
q_edge_data_pt()
template<unsigned ORDER> Vector<Data*> oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_edge_data_pt () const inline virtual
Return vector of pointers to the Data objects that store the edge flux values
Implements oomph::AxisymmetricPoroelasticityEquations.
     {
       // It's the mid-side nodes:
       Vector<Data*> data_pt(3);
       data_pt[0] = node_pt(3);
       data_pt[1] = node_pt(4);
       data_pt[2] = node_pt(5);
       return data_pt;
     }
References oomph::FiniteElement::node_pt().
q_edge_index()
template<unsigned ORDER> unsigned oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_edge_index (const unsigned & j) const inline virtual
Return the nodal index at which the jth edge unknown is stored.
Implements oomph::AxisymmetricPoroelasticityEquations.
     {
 #ifdef RANGE_CHECKING
       if (j >= (nq_basis_edge()))
       {
         std::ostringstream error_message;
         error_message << "Range Error: j " << j << " is not in the range (0,"
                       << nq_basis_edge() - 1 << ")";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       return j % (ORDER + 1) + 2;
     }
References j, oomph::TAxisymmetricPoroelasticityElement< ORDER >::nq_basis_edge(), OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::TAxisymmetricPoroelasticityElement< ORDER >::pin_q_edge_value(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_edge(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_edge_local_eqn(), and oomph::TAxisymmetricPoroelasticityElement< ORDER >::set_q_edge().
q_edge_local_eqn()
template<unsigned ORDER> int oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_edge_local_eqn (const unsigned & j) const inline virtual
Return the equation number of the j-th edge (flux) degree of freedom.
Implements oomph::AxisymmetricPoroelasticityEquations.
     {
 #ifdef RANGE_CHECKING
       if (j >= nq_basis_edge())
       {
         std::ostringstream error_message;
         error_message << "Range Error: j " << j << " is not in the range (0,"
                       << nq_basis_edge() - 1 << ")";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       return this->nodal_local_eqn(q_edge_node_number(j), q_edge_index(j));
     }
References j, oomph::FiniteElement::nodal_local_eqn(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::nq_basis_edge(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_edge_index(), and oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_edge_node_number().
q_edge_node_number()
template<unsigned ORDER> unsigned oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_edge_node_number (const unsigned & j) const inline virtual
Return the number of the node where the jth edge unknown is stored.
Implements oomph::AxisymmetricPoroelasticityEquations.
     {
 #ifdef RANGE_CHECKING
       if (j >= (nq_basis_edge()))
       {
         std::ostringstream error_message;
         error_message << "Range Error: j " << j << " is not in the range (0,"
                       << nq_basis_edge() - 1 << ")";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       return Q_edge_conv[j / (ORDER + 1)];
     }
References j, oomph::TAxisymmetricPoroelasticityElement< ORDER >::nq_basis_edge(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::TAxisymmetricPoroelasticityElement< ORDER >::Q_edge_conv.
Referenced by oomph::TAxisymmetricPoroelasticityElement< ORDER >::pin_q_edge_value(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_edge(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_edge_local_eqn(), and oomph::TAxisymmetricPoroelasticityElement< ORDER >::set_q_edge().
q_internal() [1/2]
template<unsigned ORDER> double oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_internal (const unsigned & j) const inline virtual
Return the values of the internal degree of freedom.
Implements oomph::AxisymmetricPoroelasticityEquations.
     {
 #ifdef RANGE_CHECKING
       if (j >= nq_basis_internal())
       {
         std::ostringstream error_message;
         error_message << "Range Error: j " << j << " is not in the range (0,"
                       << nq_basis_internal() - 1 << ")";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       return this->internal_data_pt(q_internal_index())->value(j);
     }
References oomph::GeneralisedElement::internal_data_pt(), j, oomph::TAxisymmetricPoroelasticityElement< ORDER >::nq_basis_internal(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_internal_index(), and oomph::Data::value().
q_internal() [2/2]
template<unsigned ORDER> double oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_internal (const unsigned & t, const unsigned & j) const inline virtual
Return the value of the j-th internal degree of freedom at time history level t
Implements oomph::AxisymmetricPoroelasticityEquations.
     {
 #ifdef RANGE_CHECKING
       if (j >= nq_basis_internal())
       {
         std::ostringstream error_message;
         error_message << "Range Error: j " << j << " is not in the range (0,"
                       << nq_basis_internal() - 1 << ")";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       return this->internal_data_pt(q_internal_index())->value(t, j);
     }
References oomph::GeneralisedElement::internal_data_pt(), j, oomph::TAxisymmetricPoroelasticityElement< ORDER >::nq_basis_internal(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_internal_index(), and oomph::Data::value().
q_internal_data_pt()
template<unsigned ORDER> Data* oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_internal_data_pt () const inline virtual
Return pointer to the Data object that stores the internal flux values.
Implements oomph::AxisymmetricPoroelasticityEquations.
     {
       return this->internal_data_pt(Q_internal_data_index);
     }
References oomph::GeneralisedElement::internal_data_pt().
q_internal_index()
template<unsigned ORDER> unsigned oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_internal_index () const inline virtual
Return the index of the internal data where the q_internal degrees of freedom are stored
Implements oomph::AxisymmetricPoroelasticityEquations.
     {
       return Q_internal_data_index;
     }
References oomph::TAxisymmetricPoroelasticityElement< ORDER >::Q_internal_data_index.
Referenced by oomph::TAxisymmetricPoroelasticityElement< ORDER >::pin_q_internal_value(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_internal(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_internal_local_eqn(), and oomph::TAxisymmetricPoroelasticityElement< ORDER >::set_q_internal().
q_internal_local_eqn()
template<unsigned ORDER> int oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_internal_local_eqn (const unsigned & j) const inline virtual
Return the equation number of the j-th internal degree of freedom.
Implements oomph::AxisymmetricPoroelasticityEquations.
     {
 #ifdef RANGE_CHECKING
       if (j >= nq_basis_internal())
       {
         std::ostringstream error_message;
         error_message << "Range Error: j " << j << " is not in the range (0,"
                       << nq_basis_internal() - 1 << ")";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       return internal_local_eqn(q_internal_index(), j);
     }
References oomph::GeneralisedElement::internal_local_eqn(), j, oomph::TAxisymmetricPoroelasticityElement< ORDER >::nq_basis_internal(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_internal_index().
required_nvalue()
template<unsigned ORDER> unsigned oomph::TAxisymmetricPoroelasticityElement< ORDER >::required_nvalue (const unsigned & n) const inline virtual
Number of values required at node n.
Implements oomph::AxisymmetricPoroelasticityEquations.
     {
       return Initial_Nvalue[n];
     }
References oomph::TAxisymmetricPoroelasticityElement< ORDER >::Initial_Nvalue, and n.
scale_basis()
template<unsigned ORDER> void oomph::TAxisymmetricPoroelasticityElement< ORDER >::scale_basis (Shape & basis) const inline virtual
Scale the edge basis to allow arbitrary edge mappings.
Implements oomph::AxisymmetricPoroelasticityEquations.
     {
       // Storage for the lengths of the edges of the element
       Vector<double> length(3, 0.0);
       // Temporary storage for the vertex positions
       double x0, y0, x1, y1;
       // loop over the edges of the element and calculate their lengths (in x-y
       // space)
       for (unsigned i = 0; i < 3; i++)
       {
         x0 = this->node_pt(i)->x(0);
         y0 = this->node_pt(i)->x(1);
         x1 = this->node_pt((i + 1) % 3)->x(0);
         y1 = this->node_pt((i + 1) % 3)->x(1);
         length[i] = std::sqrt(std::pow(y1 - y0, 2) + std::pow(x1 - x0, 2));
       }
       // lengths of the sides of the reference element (in the same order as the
       // basis functions)
       const double ref_length[3] = {std::sqrt(2.0), 1, 1};
       // get the number of basis functions associated with the edges
       unsigned n_q_basis_edge = nq_basis_edge();
       // rescale the edge basis functions to allow arbitrary edge mappings from
       // element to ref. element
       const unsigned n_index2 = basis.nindex2();
       for (unsigned i = 0; i < n_index2; i++)
       {
         for (unsigned l = 0; l < n_q_basis_edge; l++)
         {
           basis(l, i) *=
             (length[l / (ORDER + 1)] / ref_length[l / (ORDER + 1)]);
         }
       }
     }
References i, oomph::Shape::nindex2(), oomph::FiniteElement::node_pt(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::nq_basis_edge(), Eigen::bfloat16_impl::pow(), sqrt(), oomph::Node::x(), Global::x0, and Global_parameters::x1().
set_p_value()
template<unsigned ORDER> void oomph::TAxisymmetricPoroelasticityElement< ORDER >::set_p_value (const unsigned & j, const double & value) inline virtual
Set the jth pressure value.
Implements oomph::AxisymmetricPoroelasticityEquations.
     {
       this->internal_data_pt(P_internal_data_index)->set_value(j, value);
     }
References oomph::GeneralisedElement::internal_data_pt(), j, oomph::Data::set_value(), and Eigen::value.
set_q_edge() [1/2]
template<unsigned ORDER> void oomph::TAxisymmetricPoroelasticityElement< ORDER >::set_q_edge (const unsigned & j, const double & value) inline virtual
Set the values of the j-th edge (flux) degree of freedom.
Implements oomph::AxisymmetricPoroelasticityEquations.
     {
       node_pt(q_edge_node_number(j))->set_value(q_edge_index(j), value);
     }
References j, oomph::FiniteElement::node_pt(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_edge_index(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_edge_node_number(), oomph::Data::set_value(), and Eigen::value.
set_q_edge() [2/2]
template<unsigned ORDER> void oomph::TAxisymmetricPoroelasticityElement< ORDER >::set_q_edge (const unsigned & t, const unsigned & j, const double & value) inline virtual
Set the values of the j-th edge (flux) degree of freedom at time history level t
Implements oomph::AxisymmetricPoroelasticityEquations.
     {
       node_pt(q_edge_node_number(j))->set_value(t, q_edge_index(j), value);
     }
References j, oomph::FiniteElement::node_pt(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_edge_index(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_edge_node_number(), oomph::Data::set_value(), plotPSD::t, and Eigen::value.
set_q_internal() [1/2]
template<unsigned ORDER> void oomph::TAxisymmetricPoroelasticityElement< ORDER >::set_q_internal (const unsigned & j, const double & value) inline virtual
Set the values of the j-th internal degree of freedom.
Implements oomph::AxisymmetricPoroelasticityEquations.
     {
       this->internal_data_pt(q_internal_index())->set_value(j, value);
     }
References oomph::GeneralisedElement::internal_data_pt(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_internal_index(), oomph::Data::set_value(), and Eigen::value.
set_q_internal() [2/2]
template<unsigned ORDER> void oomph::TAxisymmetricPoroelasticityElement< ORDER >::set_q_internal (const unsigned & t, const unsigned & j, const double & value) inline virtual
Set the values of the j-th internal degree of freedom at time history level t
Implements oomph::AxisymmetricPoroelasticityEquations.
     {
       this->internal_data_pt(q_internal_index())->set_value(t, j, value);
     }
References oomph::GeneralisedElement::internal_data_pt(), j, oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_internal_index(), oomph::Data::set_value(), and Eigen::value.
shape_basis_test_local()
template<unsigned ORDER> double oomph::TAxisymmetricPoroelasticityElement< ORDER >::shape_basis_test_local (const Vector< double > & s, Shape & psi, DShape & dpsi, Shape & u_basis, Shape & u_test, DShape & du_basis_dx, DShape & du_test_dx, Shape & q_basis, Shape & q_test, Shape & p_basis, Shape & p_test, Shape & div_q_basis_ds, Shape & div_q_test_ds) const inline protected virtual
Returns the geometric basis, and the u, p and divergence basis functions and test functions at local coordinate s
Implements oomph::AxisymmetricPoroelasticityEquations.
     {
       const unsigned n_q_basis = this->nq_basis();
       Shape q_basis_local(n_q_basis, 2);
       this->get_q_basis_local(s, q_basis_local);
       this->get_p_basis(s, p_basis);
       this->get_div_q_basis_local(s, div_q_basis_ds);
       double J = this->transform_basis(s, q_basis_local, psi, dpsi, q_basis);
       // u_basis consists of the normal Lagrangian shape functions
       u_basis = psi;
       du_basis_dx = dpsi;
       u_test = psi;
       du_test_dx = dpsi;
       q_test = q_basis;
       p_test = p_basis;
       div_q_test_ds = div_q_basis_ds;
       return J;
     }
References oomph::TAxisymmetricPoroelasticityElement< ORDER >::get_div_q_basis_local(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::get_p_basis(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::get_q_basis_local(), J, oomph::AxisymmetricPoroelasticityEquations::nq_basis(), and oomph::AxisymmetricPoroelasticityEquations::transform_basis().
Referenced by oomph::TAxisymmetricPoroelasticityElement< ORDER >::shape_basis_test_local_at_knot().
shape_basis_test_local_at_knot()
template<unsigned ORDER> double oomph::TAxisymmetricPoroelasticityElement< ORDER >::shape_basis_test_local_at_knot (const unsigned & ipt, Shape & psi, DShape & dpsi, Shape & u_basis, Shape & u_test, DShape & du_basis_dx, DShape & du_test_dx, Shape & q_basis, Shape & q_test, Shape & p_basis, Shape & p_test, Shape & div_q_basis_ds, Shape & div_q_test_ds) const inline protected virtual
Returns the geometric basis, and the u, p and divergence basis functions and test functions at integration point ipt
Implements oomph::AxisymmetricPoroelasticityEquations.
     {
       Vector<double> s(2);
       for (unsigned i = 0; i < 2; i++)
       {
         s[i] = this->integral_pt()->knot(ipt, i);
       }
       return shape_basis_test_local(s,
                                     psi,
                                     dpsi,
                                     u_basis,
                                     u_test,
                                     du_basis_dx,
                                     du_test_dx,
                                     q_basis,
                                     q_test,
                                     p_basis,
                                     p_test,
                                     div_q_basis_ds,
                                     div_q_test_ds);
     }
References i, oomph::FiniteElement::integral_pt(), oomph::Integral::knot(), s, and oomph::TAxisymmetricPoroelasticityElement< ORDER >::shape_basis_test_local().
sign_edge() [1/2]
template<unsigned ORDER> short& oomph::TAxisymmetricPoroelasticityElement< ORDER >::sign_edge (const unsigned & n) inline
Accessor for the unit normal sign of edge n.
     {
       return Sign_edge[n];
     }
References n, and oomph::TAxisymmetricPoroelasticityElement< ORDER >::Sign_edge.
sign_edge() [2/2]
template<unsigned ORDER> const short& oomph::TAxisymmetricPoroelasticityElement< ORDER >::sign_edge (const unsigned & n) const inline
Accessor for the unit normal sign of edge n (const version)
     {
       return Sign_edge[n];
     }
References n, and oomph::TAxisymmetricPoroelasticityElement< ORDER >::Sign_edge.
Referenced by oomph::TAxisymmetricPoroelasticityElement< ORDER >::edge_flux_interpolation_point().
u_index_axisym_poroelasticity()
template<unsigned ORDER> unsigned oomph::TAxisymmetricPoroelasticityElement< ORDER >::u_index_axisym_poroelasticity (const unsigned & j) const inline virtual
Return the nodal index of the j-th solid displacement unknown [0: r; 1: z]
Implements oomph::AxisymmetricPoroelasticityEquations.
     {
 #ifdef RANGE_CHECKING
       if (j >= 2)
       {
         std::ostringstream error_message;
         error_message << "Range Error: j " << j << " is not in the range (0,1)";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       return j;
     }
References j, OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
vertex_node_pt()
template<unsigned ORDER> Node* oomph::TAxisymmetricPoroelasticityElement< ORDER >::vertex_node_pt (const unsigned & j) const inline virtual
Pointer to the j-th vertex node in the element.
Reimplemented from oomph::FiniteElement.
     {
       return TElement<2, 3>::vertex_node_pt(j);
     }
References j.
Member Data Documentation
Face_index_of_edge_flux
template<unsigned ORDER> const unsigned oomph::TAxisymmetricPoroelasticityElement< ORDER >::Face_index_of_edge_flux[] static private
Face index associated with edge flux degree of freedom.
Referenced by oomph::TAxisymmetricPoroelasticityElement< ORDER >::face_index_of_q_edge_basis_fct().
Flux_interpolation_point
template<unsigned ORDER> const double oomph::TAxisymmetricPoroelasticityElement< ORDER >::Flux_interpolation_point[] static private
The points along each edge where the fluxes are taken to be.
Referenced by oomph::TAxisymmetricPoroelasticityElement< ORDER >::edge_flux_interpolation_point().
Initial_Nvalue
template<unsigned ORDER> const unsigned oomph::TAxisymmetricPoroelasticityElement< ORDER >::Initial_Nvalue[] static private
The number of values stored at each node.
Referenced by oomph::TAxisymmetricPoroelasticityElement< ORDER >::required_nvalue().
P_internal_data_index
template<unsigned ORDER> unsigned oomph::TAxisymmetricPoroelasticityElement< ORDER >::P_internal_data_index private
The internal data index where the p degrees of freedom are stored.
Referenced by oomph::TAxisymmetricPoroelasticityElement< ORDER >::TAxisymmetricPoroelasticityElement().
Q_edge_conv
template<unsigned ORDER> const unsigned oomph::TAxisymmetricPoroelasticityElement< ORDER >::Q_edge_conv[] static private
Conversion scheme from an edge degree of freedom to the node it's stored at
Referenced by oomph::TAxisymmetricPoroelasticityElement< ORDER >::edge_flux_interpolation_point_global(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::edge_flux_node_pt(), oomph::TAxisymmetricPoroelasticityElement< ORDER >::face_local_coordinate_of_flux_interpolation_point(), and oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_edge_node_number().
Q_internal_data_index
template<unsigned ORDER> unsigned oomph::TAxisymmetricPoroelasticityElement< ORDER >::Q_internal_data_index private
The internal data index where the internal q degrees of freedom are stored
Referenced by oomph::TAxisymmetricPoroelasticityElement< ORDER >::q_internal_index(), and oomph::TAxisymmetricPoroelasticityElement< ORDER >::TAxisymmetricPoroelasticityElement().
Sign_edge
template<unsigned ORDER> std::vector<short> oomph::TAxisymmetricPoroelasticityElement< ORDER >::Sign_edge private
Unit normal signs associated with each edge to ensure inter-element continuity of the flux
Referenced by oomph::TAxisymmetricPoroelasticityElement< ORDER >::sign_edge().
The documentation for this class was generated from the following file:
Taxisym_poroelasticity_elements.h