MercuryDPM: BaseVTKWriter< H > Class Template Reference
BaseVTKWriter< H > Class Template Reference abstract
#include <BaseVTKWriter.h>
Public Member Functions
BaseVTKWriter (H &handler)
BaseVTKWriter (const BaseVTKWriter &other)
virtual void writeVTK () const =0
unsigned getFileCounter () const
void setFileCounter (unsigned fileCounter)
void setOutputDirectory (const std::string &dir)
const std::string & getOutputDirectory () const
std::string getFileName () const
Protected Member Functions
std::fstream makeVTKFileWithHeader () const
void writeVTKFooterAndClose (std::fstream &file) const
Protected Attributes
H & handler_
particle handler from which the particles should be written
unsigned int fileCounter
std::string outputDirectory_
Detailed Description
template<typename H>
class BaseVTKWriter< H >
Template Parameters
H some handler, e.g. particleHandler
Constructor & Destructor Documentation
BaseVTKWriter() [1/2]
template<typename H > BaseVTKWriter< H >::BaseVTKWriter (H & handler) inline
                               : handler_(handler)
     {
         fileCounter = 0;
         outputDirectory_ = ".";
     }
References BaseVTKWriter< H >::fileCounter, and BaseVTKWriter< H >::outputDirectory_.
BaseVTKWriter() [2/2]
template<typename H > BaseVTKWriter< H >::BaseVTKWriter (const BaseVTKWriter< H > & other) inline
                                               : handler_(other.handler_)
     {
         fileCounter = other.fileCounter;
         outputDirectory_ = other.outputDirectory_;
     }
References BaseVTKWriter< H >::fileCounter, and BaseVTKWriter< H >::outputDirectory_.
Member Function Documentation
getFileCounter()
template<typename H > unsigned BaseVTKWriter< H >::getFileCounter () const inline
     {
         return fileCounter;
     }
References BaseVTKWriter< H >::fileCounter.
Referenced by DPMBase::write(), and DPMBase::writeVTKFiles().
getFileName()
template<typename T > std::string BaseVTKWriter< T >::getFileName
Todo:
vtw wall files only need to be written by one processor
 {
     //extract the word "Wall" or "Particle" from the VTK writer name
     std::string name = handler_.getName();
     name = name.substr(0, name.length() - 7);
     //determine name of output file
     std::string fileName;
 #ifdef MERCURYDPM_USE_MPI
     if (NUMBER_OF_PROCESSORS > 1 && name != "Wall")
     {
         fileName = handler_.getDPMBase()->getName() + "Processor_" + std::to_string(PROCESSOR_ID) +
         '_' + name + '_' + std::to_string(fileCounter)  + ".vtu";
     }
     else
     {
         fileName = handler_.getDPMBase()->getName() +
                                  name + '_' +
                                  std::to_string(fileCounter) + ".vtu";
     }
 #else
     fileName = handler_.getDPMBase()->getName() +
                name + '_' +
                std::to_string(fileCounter) + ".vtu";
 #endif
     return fileName;
 };
References UniformPSDSelfTest::fileName, plotDoE::name, NUMBER_OF_PROCESSORS, PROCESSOR_ID, oomph::Global_string_for_annotation::string(), and oomph::StringConversion::to_string().
getOutputDirectory()
template<typename H > const std::string& BaseVTKWriter< H >::getOutputDirectory () const inline
     {
         return outputDirectory_;
     }
References BaseVTKWriter< H >::outputDirectory_.
Referenced by DPMBase::initialiseVTK(), DPMBase::removeOldFiles(), DPMBase::write(), and DPMBase::writePythonFileForVTKVisualisation().
makeVTKFileWithHeader()
template<typename T > std::fstream BaseVTKWriter< T >::makeVTKFileWithHeader protected
Todo:
vtw wall files only need to be written by one processor
 {
     std::string fileName = getFileName();
     fileCounter++;
     // open output file
     char filePath[2048];
     const int n = snprintf(filePath, sizeof(filePath), "%s/%s", outputDirectory_.c_str(), fileName.c_str());
     if (n <= 0) {
         logger(ERROR, "unable to create file path");
     }
     std::fstream file;
     file.open(filePath, std::ios_base::out);
     if (file.fail())
     {
         logger(WARN, "File % could not be opened", filePath);
     }
     // write output file header
     file << "<?xml version=\"1.0\"?>\n";
     file << "<!-- time " << handler_.getDPMBase()->getTime() << "-->\n";
     file << "<VTKFile type=\"UnstructuredGrid\" version=\"0.1\" byte_order=\"LittleEndian\">\n";
     file << "<UnstructuredGrid>\n";
     return file;
 }
References ERROR, UniformPSDSelfTest::fileName, logger, n, out(), oomph::Global_string_for_annotation::string(), and WARN.
setFileCounter()
template<typename H > void BaseVTKWriter< H >::setFileCounter (unsigned fileCounter) inline
     {
         this->fileCounter = fileCounter;
     }
References BaseVTKWriter< H >::fileCounter.
Referenced by DPMBase::read(), and DPMBase::resetFileCounter().
setOutputDirectory()
template<typename H > void BaseVTKWriter< H >::setOutputDirectory (const std::string & dir) inline
     {
         logger.assert_always(!dir.empty(), "Invalid VTK directory");
         if (dir.at(dir.size() - 1) == '/'){
             outputDirectory_ = dir.substr(0, dir.size() - 1);
         } else {
             outputDirectory_ = dir;
         }
     }
References logger, and BaseVTKWriter< H >::outputDirectory_.
Referenced by DPMBase::read(), and DPMBase::setVTKOutputDirectory().
writeVTK()
template<typename H > virtual void BaseVTKWriter< H >::writeVTK () const pure virtual
Implemented in WallVTKWriter, WallDetailsVTKWriter, SuperQuadricParticleVtkWriter, SphericalParticleVtkWriter, InteractionVTKWriter, and BoundaryVTKWriter.
Referenced by DPMBase::writeVTKFiles().
writeVTKFooterAndClose()
template<typename T > void BaseVTKWriter< T >::writeVTKFooterAndClose (std::fstream & file) const protected
 {
     // write output file footer
     file << "<Cells>\n";
     file << "  <DataArray type=\"Int32\" Name=\"connectivity\" format=\"ascii\">\n";
     file << "  </DataArray>\n";
     file << "  <DataArray type=\"Int32\" Name=\"offsets\" format=\"ascii\">\n";
     file << "  </DataArray>\n";
     file << "  <DataArray type=\"UInt8\"  Name=\"types\" format=\"ascii\">\n";
     file << "  </DataArray>\n";
     file << "</Cells>\n";
     file << "</Piece>\n";
     file << "</UnstructuredGrid>\n";
     file << "</VTKFile>\n";
     // close output file
     file.close();
 }
Member Data Documentation
fileCounter
template<typename H > unsigned int BaseVTKWriter< H >::fileCounter mutable protected
Referenced by BaseVTKWriter< H >::BaseVTKWriter(), BaseVTKWriter< H >::getFileCounter(), and BaseVTKWriter< H >::setFileCounter().
handler_
template<typename H > H& BaseVTKWriter< H >::handler_ protected
particle handler from which the particles should be written
outputDirectory_
template<typename H > std::string BaseVTKWriter< H >::outputDirectory_ protected
Referenced by BaseVTKWriter< H >::BaseVTKWriter(), BaseVTKWriter< H >::getOutputDirectory(), and BaseVTKWriter< H >::setOutputDirectory().
The documentation for this class was generated from the following file:
BaseVTKWriter.h