MercuryDPM: LiquidMigrationWilletSpecies Class Reference
LiquidMigrationWilletSpecies Class Reference
LiquidMigrationWilletSpecies contains the parameters used to describe a short-range force caused by liquid bridges.
#include <LiquidMigrationWilletSpecies.h>
Public Types
typedef LiquidMigrationWilletInteraction InteractionType
The correct Interaction type for this AdhesiveForceSpecies.
Public Member Functions
LiquidMigrationWilletSpecies ()
The default constructor.
LiquidMigrationWilletSpecies (const LiquidMigrationWilletSpecies &s)
The default copy constructor.
~LiquidMigrationWilletSpecies ()
The default destructor.
void read (std::istream &is)
Reads the species properties from an input stream.
void write (std::ostream &os) const
Writes the species properties to an output stream.
std::string getBaseName () const
Used in Species::getName to obtain a unique name for each Species.
void mix (LiquidMigrationWilletSpecies *S, LiquidMigrationWilletSpecies *T)
creates default values for mixed species
void setInteractionDistance ()
returns the largest separation distance at which adhesive short-range forces can occur.
void setLiquidBridgeVolumeMax (Mdouble liquidBridgeVolume)
used to set the Volume of the liquid bridge.
Mdouble getLiquidBridgeVolumeMax () const
used to access the Volume of the liquid bridge.
void setLiquidBridgeVolumeMin (Mdouble)
used to set the Volume of the liquid bridge.
Mdouble getLiquidBridgeVolumeMin () const
used to access the Volume of the liquid bridge.
void setDistributionCoefficient (Mdouble distributionCoefficient)
used to set the distribution coefficient of the liquid.
Mdouble getDistributionCoefficient () const
used to access the surface tension of the liquid.
void setSurfaceTension (Mdouble surfaceTension)
used to set the surface tension of the liquid.
Mdouble getSurfaceTension () const
used to access the surface tension of the liquid.
void setContactAngle (Mdouble contactAngle)
used to set the contact angle between particle and liquid bridge surface (in radians)
Mdouble getContactAngle () const
used to access the contact angle between particle and liquid bridge surface.
Public Member Functions inherited from BaseForce
BaseSpecies * getBaseSpecies () const
void setBaseSpecies (BaseSpecies *baseSpecies)
Private Attributes
Mdouble liquidBridgeVolumeMax_
Max volume a liquid bridge gets during formation; any excess remains in the liquid film of the particle.
Mdouble liquidBridgeVolumeMin_
Minimum volume needed to form a liquid bridge.
Mdouble distributionCoefficient_
distribution coefficient of the liquid
Mdouble contactAngle_
contact angle between particle and liquid bridge surface
Mdouble surfaceTension_
surface tension of the liquid
Detailed Description
LiquidMigrationWilletSpecies contains the parameters used to describe a short-range force caused by liquid bridges.
See LiquidMigrationWilletInteraction::computeForce for a description of the force law.
Member Typedef Documentation
InteractionType
typedef LiquidMigrationWilletInteraction LiquidMigrationWilletSpecies::InteractionType
The correct Interaction type for this AdhesiveForceSpecies.
Constructor & Destructor Documentation
LiquidMigrationWilletSpecies() [1/2]
LiquidMigrationWilletSpecies::LiquidMigrationWilletSpecies ()
The default constructor.
 {
     liquidBridgeVolumeMax_ = 0.0; //std::numeric_limits<double>::infinity();
     liquidBridgeVolumeMin_ = 0.0;
     distributionCoefficient_ = 1.0;
     surfaceTension_ = 0.0;
     contactAngle_ = 0.0;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"LiquidMigrationWilletSpecies::LiquidMigrationWilletSpecies() finished"<<std::endl;
 #endif
 }
References contactAngle_, distributionCoefficient_, liquidBridgeVolumeMax_, liquidBridgeVolumeMin_, and surfaceTension_.
LiquidMigrationWilletSpecies() [2/2]
LiquidMigrationWilletSpecies::LiquidMigrationWilletSpecies (const LiquidMigrationWilletSpecies & s)
The default copy constructor.
Parameters
[in] the species that is copied
 {
     liquidBridgeVolumeMax_ = s.liquidBridgeVolumeMax_;
     liquidBridgeVolumeMin_ = s.liquidBridgeVolumeMin_;
     distributionCoefficient_ = s.distributionCoefficient_;
     surfaceTension_ = s.surfaceTension_;
     contactAngle_ = s.contactAngle_;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"LiquidMigrationWilletSpecies::LiquidMigrationWilletSpecies(const LiquidMigrationWilletSpecies &p) finished"<<std::endl;
 #endif
 }
References contactAngle_, distributionCoefficient_, liquidBridgeVolumeMax_, liquidBridgeVolumeMin_, s, and surfaceTension_.
~LiquidMigrationWilletSpecies()
LiquidMigrationWilletSpecies::~LiquidMigrationWilletSpecies ()
The default destructor.
 {
 #ifdef DEBUG_DESTRUCTOR
     std::cout<<"LiquidMigrationWilletSpecies::~LiquidMigrationWilletSpecies() finished"<<std::endl;
 #endif
 }
Member Function Documentation
getBaseName()
std::string LiquidMigrationWilletSpecies::getBaseName () const
Used in Species::getName to obtain a unique name for each Species.
Returns
a string containing the name of the species (minus the word "Species")
 {
     return "LiquidMigrationWillet";
 }
Referenced by SolidifyingLiquidMigrationWilletSpecies::getBaseName().
getContactAngle()
Mdouble LiquidMigrationWilletSpecies::getContactAngle () const
used to access the contact angle between particle and liquid bridge surface.
Returns
the contact angle between particle and liquid bridge surface.
 {
     return contactAngle_;
 }
References contactAngle_.
Referenced by LiquidMigrationWilletInteraction::computeAdhesionForce(), and LiquidMigrationWilletInteraction::getRuptureDistance().
getDistributionCoefficient()
Mdouble LiquidMigrationWilletSpecies::getDistributionCoefficient () const
used to access the surface tension of the liquid.
Returns
the distribution coefficient of the liquid.
 {
     return distributionCoefficient_;
 }
References distributionCoefficient_.
Referenced by LiquidMigrationWilletInteraction::distributeToOtherBridges().
getLiquidBridgeVolumeMax()
Mdouble LiquidMigrationWilletSpecies::getLiquidBridgeVolumeMax () const
used to access the Volume of the liquid bridge.
Returns
the volume of the liquid bridge.
 {
     return liquidBridgeVolumeMax_;
 }
References liquidBridgeVolumeMax_.
getLiquidBridgeVolumeMin()
Mdouble LiquidMigrationWilletSpecies::getLiquidBridgeVolumeMin () const
used to access the Volume of the liquid bridge.
 {
     return liquidBridgeVolumeMin_;
 }
References liquidBridgeVolumeMin_.
getSurfaceTension()
Mdouble LiquidMigrationWilletSpecies::getSurfaceTension () const
used to access the surface tension of the liquid.
Returns
the surface tension of the liquid.
 {
     return surfaceTension_;
 }
References surfaceTension_.
Referenced by LiquidMigrationWilletInteraction::computeAdhesionForce().
mix()
void LiquidMigrationWilletSpecies::mix (LiquidMigrationWilletSpecies * S, LiquidMigrationWilletSpecies * T)
creates default values for mixed species
For all parameters we assume that the harmonic mean of the parameters of the original two species is a sensible default.
Parameters
[in] S,T the two species whose properties are mixed to create the new species
 {
     liquidBridgeVolumeMax_ = BaseSpecies::average(S->getLiquidBridgeVolumeMax(), T->getLiquidBridgeVolumeMax());
     liquidBridgeVolumeMin_ = BaseSpecies::average(S->getLiquidBridgeVolumeMin(), T->getLiquidBridgeVolumeMin());
     distributionCoefficient_ = BaseSpecies::average(S->getDistributionCoefficient(), T->getDistributionCoefficient());
     surfaceTension_ = BaseSpecies::average(S->getSurfaceTension(), T->getSurfaceTension());
     contactAngle_ = BaseSpecies::average(S->getContactAngle(), T->getContactAngle());
     setInteractionDistance();
 }
References BaseSpecies::average(), contactAngle_, distributionCoefficient_, liquidBridgeVolumeMax_, liquidBridgeVolumeMin_, oomph::QuadTreeNames::S, setInteractionDistance(), and surfaceTension_.
Referenced by LiquidMigrationWilletViscousSpecies::mix(), and SolidifyingLiquidMigrationWilletSpecies::mix().
read()
void LiquidMigrationWilletSpecies::read (std::istream & is)
Reads the species properties from an input stream.
Parameters
[in] input stream (typically the restart file)
 {
     std::string dummy;
     is >> dummy >> liquidBridgeVolumeMax_;
     helpers::readOptionalVariable(is,"liquidBridgeVolumeMin",liquidBridgeVolumeMin_);
     is >> dummy >> distributionCoefficient_;
     is >> dummy >> surfaceTension_;
     is >> dummy >> contactAngle_;
     setInteractionDistance();
 }
References contactAngle_, distributionCoefficient_, liquidBridgeVolumeMax_, liquidBridgeVolumeMin_, helpers::readOptionalVariable(), setInteractionDistance(), oomph::Global_string_for_annotation::string(), and surfaceTension_.
Referenced by LiquidMigrationWilletViscousSpecies::read(), and SolidifyingLiquidMigrationWilletSpecies::read().
setContactAngle()
void LiquidMigrationWilletSpecies::setContactAngle (Mdouble contactAngle)
used to set the contact angle between particle and liquid bridge surface (in radians)
Parameters
[in] contactAngle the contact angle between particle and liquid bridge surface.
 {
     logger.assert_always(contactAngle >= 0, "Error in setContactAngle(%), contactAngle should be >= 0", contactAngle);
     contactAngle_ = contactAngle;
     setInteractionDistance();
 }
References contactAngle_, logger, and setInteractionDistance().
setDistributionCoefficient()
void LiquidMigrationWilletSpecies::setDistributionCoefficient (Mdouble distributionCoefficient)
used to set the distribution coefficient of the liquid.
Parameters
[in] distributionCoefficient the distribution coefficient of the liquid.
 {
     logger.assert_always(distributionCoefficient >= 0 && distributionCoefficient <= 1.0,
                          "Error in setDistributionCoefficient(%), distributionCoefficient should be between 0 and 1",
                          distributionCoefficient);
     distributionCoefficient_ = distributionCoefficient;
 }
References distributionCoefficient_, and logger.
setInteractionDistance()
void LiquidMigrationWilletSpecies::setInteractionDistance () virtual
returns the largest separation distance at which adhesive short-range forces can occur.
Returns
the maximum separation distance below which adhesive forces can occur (needed for contact detection)
Reimplemented from BaseAdhesiveForce.
 {
     getBaseSpecies()->setInteractionDistance((1.0 + 0.5 * contactAngle_) * cbrt(liquidBridgeVolumeMax_));
 }
References Eigen::numext::cbrt(), contactAngle_, BaseForce::getBaseSpecies(), liquidBridgeVolumeMax_, and BaseSpecies::setInteractionDistance().
Referenced by mix(), read(), setContactAngle(), and setLiquidBridgeVolumeMax().
setLiquidBridgeVolumeMax()
void LiquidMigrationWilletSpecies::setLiquidBridgeVolumeMax (Mdouble liquidBridgeVolumeMax)
used to set the Volume of the liquid bridge.
Parameters
[in] liquidBridgeVolume the volume of the liquid bridge.
 {
     logger.assert_always(liquidBridgeVolumeMax >= 0,
                          "Error in setLiquidBridgeVolumeMax(%), liquidBridgeVolumeMax should be >= 0", liquidBridgeVolumeMax);
     liquidBridgeVolumeMax_ = liquidBridgeVolumeMax;
     setInteractionDistance();
 }
References liquidBridgeVolumeMax_, logger, and setInteractionDistance().
setLiquidBridgeVolumeMin()
void LiquidMigrationWilletSpecies::setLiquidBridgeVolumeMin (Mdouble liquidBridgeVolumeMin)
used to set the Volume of the liquid bridge.
 {
     logger.assert_always(liquidBridgeVolumeMin >= 0,
             "Error in setLiquidBridgeVolumeMin (%), liquidBridgeVolumeMin should be >= 0", liquidBridgeVolumeMin);
     liquidBridgeVolumeMin_ = liquidBridgeVolumeMin;
 }
References liquidBridgeVolumeMin_, and logger.
setSurfaceTension()
void LiquidMigrationWilletSpecies::setSurfaceTension (Mdouble surfaceTension)
used to set the surface tension of the liquid.
Parameters
[in] surfaceTension the surface tension of the liquid.
 {
     logger.assert_always(surfaceTension >= 0, "Error in setSurfaceTension(%), surfaceTension should be >= 0", surfaceTension);
     surfaceTension_ = surfaceTension;
 }
References logger, and surfaceTension_.
write()
void LiquidMigrationWilletSpecies::write (std::ostream & os) const
Writes the species properties to an output stream.
Parameters
[out] output stream (typically the restart file)
 {
     os << " liquidBridgeVolumeMax " << liquidBridgeVolumeMax_;
     if (liquidBridgeVolumeMin_) os << " liquidBridgeVolumeMin " << liquidBridgeVolumeMin_;
     os << " distributionCoefficient " << distributionCoefficient_;
     os << " surfaceTension " << surfaceTension_;
     os << " contactAngle " << contactAngle_;
 }
References contactAngle_, distributionCoefficient_, liquidBridgeVolumeMax_, liquidBridgeVolumeMin_, and surfaceTension_.
Referenced by LiquidMigrationWilletViscousSpecies::write(), and SolidifyingLiquidMigrationWilletSpecies::write().
Member Data Documentation
contactAngle_
Mdouble LiquidMigrationWilletSpecies::contactAngle_ private
contact angle between particle and liquid bridge surface
Referenced by getContactAngle(), LiquidMigrationWilletSpecies(), mix(), read(), setContactAngle(), setInteractionDistance(), and write().
distributionCoefficient_
Mdouble LiquidMigrationWilletSpecies::distributionCoefficient_ private
distribution coefficient of the liquid
This is a variable that determines the fraction of the liquid that is to be distributed to the neighboring contacts of the particles after a liquid bridge rupture.
Referenced by getDistributionCoefficient(), LiquidMigrationWilletSpecies(), mix(), read(), setDistributionCoefficient(), and write().
liquidBridgeVolumeMax_
Mdouble LiquidMigrationWilletSpecies::liquidBridgeVolumeMax_ private
Max volume a liquid bridge gets during formation; any excess remains in the liquid film of the particle.
Referenced by getLiquidBridgeVolumeMax(), LiquidMigrationWilletSpecies(), mix(), read(), setInteractionDistance(), setLiquidBridgeVolumeMax(), and write().
liquidBridgeVolumeMin_
Mdouble LiquidMigrationWilletSpecies::liquidBridgeVolumeMin_ private
Minimum volume needed to form a liquid bridge.
Referenced by getLiquidBridgeVolumeMin(), LiquidMigrationWilletSpecies(), mix(), read(), setLiquidBridgeVolumeMin(), and write().
surfaceTension_
Mdouble LiquidMigrationWilletSpecies::surfaceTension_ private
surface tension of the liquid
Referenced by getSurfaceTension(), LiquidMigrationWilletSpecies(), mix(), read(), setSurfaceTension(), and write().
The documentation for this class was generated from the following files:
LiquidMigrationWilletSpecies.h
LiquidMigrationWilletSpecies.cc