MercuryDPM: FindParticlesSelfTest.cpp File Reference
FindParticlesSelfTest.cpp File Reference
#include "Mercury2D.h"
#include "Walls/IntersectionOfWalls.h"
#include "Species/LinearViscoelasticSpecies.h"
#include "Boundaries/CubeInsertionBoundary.h"
Functions
int main ()
This tests the hGridFindParticleContacts routine.
Function Documentation
main()
int main ()
This tests the hGridFindParticleContacts routine.
Particle are inserted into a square domain using an insertion boundary. Then we find all particles close to the center and give them a velocity.
            {
     // create dpm setup, set necessary variables (time step, domain, name, species)
     Mercury2D dpm;
     dpm.setTimeStep(1e-4);
     dpm.setDomain({0,0,0},{10,10,0});
     dpm.setName("FindParticles");
     // define and add species to dpm
     LinearViscoelasticSpecies species;
     species.setDensity(6.0 / pi);
     species.setCollisionTimeAndRestitutionCoefficient(1.0, 1.0, 1.0);
     dpm.speciesHandler.copyAndAddObject(species);
     // define an insertion boundary and use it to insert particles;
     // note, the boundary is not added to the dpm, it is only used to insert particles initially
     SphericalParticle particle;
     particle.setSpecies(dpm.speciesHandler.getLastObject());
     particle.setRadius(0.1);
     int maxFailed = 100;
     Vec3D posMin = dpm.getMin();
     Vec3D posMax = dpm.getMax();
     Vec3D velMin = {0, 0, 0};
     Vec3D velMax = {0, 0, 0};
     CubeInsertionBoundary insertionBoundary;
     insertionBoundary.set(&particle, maxFailed, posMin, posMax, velMin, velMax);
     //insertionBoundary.setVolumeFlowRate(10);
     insertionBoundary.checkBoundaryBeforeTimeStep(&dpm);
     logger(INFO,"number of particles % ",dpm.particleHandler.getNumberOfObjects());
     // use a search particle to find all particles close to the center of the domain, and give those particles a velocity
     SphericalParticle searchParticle;
     searchParticle.setSpecies(dpm.speciesHandler.getLastObject());
     searchParticle.setRadius(3);
     searchParticle.setPosition({5,5,0});
     auto particlesInContact = dpm.hGridFindParticleContacts(&searchParticle);
     for (auto p : particlesInContact) {
         p->setVelocity({1,0,0});
     }
     logger(INFO,"number of particles in contact with the search particle %",particlesInContact.size());
     //run the dpm to create the output files; it can be seen in the output that the particles in the center have velocity
     dpm.solve();
     logger(INFO,"All particles in contact to the search particle have a different velocity, see findCloseParticles.xballs");
     return 0;
 }
References InsertionBoundary::checkBoundaryBeforeTimeStep(), BaseHandler< T >::copyAndAddObject(), e(), BaseHandler< T >::getLastObject(), DPMBase::getMax(), DPMBase::getMin(), ParticleHandler::getNumberOfObjects(), Mercury2D::hGridFindParticleContacts(), INFO, logger, p, DPMBase::particleHandler, constants::pi, CubeInsertionBoundary::set(), LinearViscoelasticNormalSpecies::setCollisionTimeAndRestitutionCoefficient(), ParticleSpecies::setDensity(), DPMBase::setDomain(), DPMBase::setName(), BaseInteractable::setPosition(), BaseParticle::setRadius(), BaseParticle::setSpecies(), DPMBase::setTimeStep(), DPMBase::solve(), and DPMBase::speciesHandler.