MercuryDPM: oomph::MultiPoissonEquations< DIM, NFIELDS > Class Template Reference
oomph::MultiPoissonEquations< DIM, NFIELDS > Class Template Reference abstract
#include <multi_poisson_elements.h>
Public Types
typedef void(* MultiPoissonSourceFctPt) (const Vector< double > &x, Vector< double > &f)
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Public Member Functions
MultiPoissonEquations ()
Constructor (must initialise the Source_fct_pt to null)
MultiPoissonEquations (const MultiPoissonEquations &dummy)
Broken copy constructor.
virtual unsigned u_index_multi_poisson (const unsigned &i) const
unsigned ndof_types () const
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > &block_lookup_list) const
unsigned nscalar_paraview () const
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
std::string scalar_name_paraview (const unsigned &i) const
void output (std::ostream &outfile)
Output with default number of plot points.
void output (std::ostream &outfile, const unsigned &n_plot)
void output (FILE *file_pt)
C_style output with default number of plot points.
void output (FILE *file_pt, const unsigned &n_plot)
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Get error against and norm of exact solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Dummy, time dependent error checker.
double *& beta_pt ()
Access function: Pointer to interaction parameter beta.
MultiPoissonSourceFctPt & source_fct_pt ()
Access function: Pointer to source function.
MultiPoissonSourceFctPt source_fct_pt () const
Access function: Pointer to source function. Const version.
virtual void get_source_multi_poisson (const unsigned &ipt, const Vector< double > &x, Vector< double > &source) const
void get_flux (const Vector< double > &s, Vector< double > &flux) const
Get flux: flux[i] = du/dx_i.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector (wrapper)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
double interpolated_u_multi_poisson (const unsigned &i, const Vector< double > &s) const
unsigned self_test ()
Self-test: Return 0 for OK.
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
virtual void disable_ALE ()
virtual void enable_ALE ()
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual unsigned nvertex_node () const
virtual Node * vertex_node_pt (const unsigned &j) const
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Protected Member Functions
virtual double dshape_and_dtest_eulerian_multi_poisson (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
virtual double dshape_and_dtest_eulerian_at_knot_multi_poisson (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
virtual double dshape_and_dtest_eulerian_at_knot_multi_poisson (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const =0
virtual void fill_in_generic_residual_contribution_multi_poisson (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Attributes
MultiPoissonSourceFctPt Source_fct_pt
Pointer to source function:
double * Beta_pt
Pointer to interaction parameter Beta.
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Additional Inherited Members
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
template<unsigned DIM, unsigned NFIELDS>
class oomph::MultiPoissonEquations< DIM, NFIELDS >
A class for all isoparametric elements that solve the MultiPoisson equations
\[ (i+1) (\frac{\partial^2 u_i}{\partial x_j^2} + \beta \sum_{k=0}^{k<N} u_k) = f_i(x_j) \ \ \ \ i=0,...,N-1 \]
This contains the generic maths. Shape functions, geometric mapping etc. must get implemented in derived class. [Mathematical disclaimer: These are totally and utterly invented equations; merely for the purpose of testing out the block preconditioning framework. "multi helmholtz" would probably be a better name...]
Member Typedef Documentation
MultiPoissonSourceFctPt
template<unsigned DIM, unsigned NFIELDS> typedef void(* oomph::MultiPoissonEquations< DIM, NFIELDS >::MultiPoissonSourceFctPt) (const Vector< double > &x, Vector< double > &f)
Function pointer to source function fct(x,f(x)) – x is a Vector!
Constructor & Destructor Documentation
MultiPoissonEquations() [1/2]
template<unsigned DIM, unsigned NFIELDS> oomph::MultiPoissonEquations< DIM, NFIELDS >::MultiPoissonEquations () inline
Constructor (must initialise the Source_fct_pt to null)
                           : Source_fct_pt(0), Beta_pt(0)
   {}
MultiPoissonEquations() [2/2]
template<unsigned DIM, unsigned NFIELDS> oomph::MultiPoissonEquations< DIM, NFIELDS >::MultiPoissonEquations (const MultiPoissonEquations< DIM, NFIELDS > & dummy) inline
Broken copy constructor.
   {
    BrokenCopy::broken_copy("MultiPoissonEquations");
   }
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
beta_pt()
template<unsigned DIM, unsigned NFIELDS> double*& oomph::MultiPoissonEquations< DIM, NFIELDS >::beta_pt () inline
Access function: Pointer to interaction parameter beta.
 {return Beta_pt;}
References oomph::MultiPoissonEquations< DIM, NFIELDS >::Beta_pt.
compute_error() [1/2]
template<unsigned DIM, unsigned NFIELDS> void oomph::MultiPoissonEquations< DIM, NFIELDS >::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) virtual
Get error against and norm of exact solution.
Validate against exact solution
Solution is provided via function pointer. Plot error at a given number of plot points.
Reimplemented from oomph::FiniteElement.
   {
    // Initialise
    error=0.0;
    norm=0.0;
    //Vector of local coordinates
    Vector<double> s(DIM);
    // Vector for coordintes
    Vector<double> x(DIM);
    //Find out how many nodes there are in the element
    unsigned n_node = nnode();
    Shape psi(n_node);
    //Set the value of n_intpt
    unsigned n_intpt = integral_pt()->nweight();
    // Tecplot
    outfile << "ZONE" << std::endl;
    // Exact solution Vector (here a scalar)
    Vector<double> exact_soln(NFIELDS);
    //Loop over the integration points
    for(unsigned ipt=0;ipt<n_intpt;ipt++)
     {
      //Assign values of s
      for(unsigned i=0;i<DIM;i++)
       {
        s[i] = integral_pt()->knot(ipt,i);
       }
      //Get the integral weight
      double w = integral_pt()->weight(ipt);
      // Get jacobian of mapping
      double J=J_eulerian(s);
      //Premultiply the weights and the Jacobian
      double W = w*J;
      // Get x position as Vector
      interpolated_x(s,x);
      //Output x,y,...
      for(unsigned i=0;i<DIM;i++)
       {
        outfile << x[i] << " ";
       }
      // Get exact solution at this point
      (*exact_soln_pt)(x,exact_soln);
      for(unsigned i=0;i<NFIELDS;i++)
       {
        // Get FE function value
        double u_fe=interpolated_u_multi_poisson(i,s);
        outfile << exact_soln[i] << " " << exact_soln[i]-u_fe << " ";
        // Add to error and norm
        norm+=exact_soln[i]*exact_soln[i]*W;
        error+=(exact_soln[i]-u_fe)*(exact_soln[i]-u_fe)*W;
       }
      outfile << std::endl;
     }
   }
References DIM, calibrate::error, ProblemParameters::exact_soln(), i, J, s, w, oomph::QuadTreeNames::W, and plotDoE::x.
compute_error() [2/2]
template<unsigned DIM, unsigned NFIELDS> void oomph::MultiPoissonEquations< DIM, NFIELDS >::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) inline virtual
Dummy, time dependent error checker.
Reimplemented from oomph::FiniteElement.
   {
    throw OomphLibError(
     "There is no time-dependent compute_error() for MultiPoisson elements",
     OOMPH_CURRENT_FUNCTION,
     OOMPH_EXCEPTION_LOCATION);
   }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
dshape_and_dtest_eulerian_at_knot_multi_poisson() [1/2]
template<unsigned DIM, unsigned NFIELDS> virtual double oomph::MultiPoissonEquations< DIM, NFIELDS >::dshape_and_dtest_eulerian_at_knot_multi_poisson (const unsigned & ipt, Shape & psi, DShape & dpsidx, RankFourTensor< double > & d_dpsidx_dX, Shape & test, DShape & dtestdx, RankFourTensor< double > & d_dtestdx_dX, DenseMatrix< double > & djacobian_dX) const protected pure virtual
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping (J). Also compute derivatives of dpsidx, dtestdx and J w.r.t. nodal coordinates.
Implemented in oomph::QMultiPoissonElement< DIM, NNODE_1D, NFIELDS >.
dshape_and_dtest_eulerian_at_knot_multi_poisson() [2/2]
template<unsigned DIM, unsigned NFIELDS> virtual double oomph::MultiPoissonEquations< DIM, NFIELDS >::dshape_and_dtest_eulerian_at_knot_multi_poisson (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const protected pure virtual
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping
Implemented in oomph::QMultiPoissonElement< DIM, NNODE_1D, NFIELDS >.
dshape_and_dtest_eulerian_multi_poisson()
template<unsigned DIM, unsigned NFIELDS> virtual double oomph::MultiPoissonEquations< DIM, NFIELDS >::dshape_and_dtest_eulerian_multi_poisson (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const protected pure virtual
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping
Implemented in oomph::QMultiPoissonElement< DIM, NNODE_1D, NFIELDS >.
fill_in_contribution_to_jacobian()
template<unsigned DIM, unsigned NFIELDS> void oomph::MultiPoissonEquations< DIM, NFIELDS >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline virtual
Add the element's contribution to its residual vector and element Jacobian matrix (wrapper)
Reimplemented from oomph::GeneralisedElement.
   {
    //Call the generic routine with the flag set to 1
    fill_in_generic_residual_contribution_multi_poisson(residuals,jacobian,1);
   }
References oomph::MultiPoissonEquations< DIM, NFIELDS >::fill_in_generic_residual_contribution_multi_poisson().
fill_in_contribution_to_residuals()
template<unsigned DIM, unsigned NFIELDS> void oomph::MultiPoissonEquations< DIM, NFIELDS >::fill_in_contribution_to_residuals (Vector< double > & residuals) inline virtual
Add the element's contribution to its residual vector (wrapper)
Reimplemented from oomph::GeneralisedElement.
   {
    //Call the generic residuals function with flag set to 0
    //using a dummy matrix argument
    fill_in_generic_residual_contribution_multi_poisson(
     residuals,GeneralisedElement::Dummy_matrix,0);
   }
References oomph::GeneralisedElement::Dummy_matrix, and oomph::MultiPoissonEquations< DIM, NFIELDS >::fill_in_generic_residual_contribution_multi_poisson().
fill_in_generic_residual_contribution_multi_poisson()
template<unsigned DIM, unsigned NFIELDS> void oomph::MultiPoissonEquations< DIM, NFIELDS >::fill_in_generic_residual_contribution_multi_poisson (Vector< double > & residuals, DenseMatrix< double > & jacobian, const unsigned & flag) protected virtual
Compute element residual Vector only (if flag=and/or element Jacobian matrix
Compute element residual Vector and/or element Jacobian matrix
flag=1: compute both flag=0: compute only residual Vector
Pure version without hanging nodes
 {
  //Find out how many nodes there are
  const unsigned n_node = nnode();
  //Set up memory for the shape and test functions
  Shape psi(n_node), test(n_node);
  DShape dpsidx(n_node,DIM), dtestdx(n_node,DIM);
  //Set the value of n_intpt
  const unsigned n_intpt = integral_pt()->nweight();
  //Integers to store the local equation and unknown numbers
  int local_eqn=0, local_unknown=0;
  //Loop over the integration points
  for(unsigned ipt=0;ipt<n_intpt;ipt++)
   {
    //Get the integral weight
    double w = integral_pt()->weight(ipt);
    //Call the derivatives of the shape and test functions
    double J = dshape_and_dtest_eulerian_at_knot_multi_poisson(ipt,psi,dpsidx,
                                                         test,dtestdx);
    //Premultiply the weights and the Jacobian
    double W = w*J;
    //Calculate local values of unknown
    //Allocate and initialise to zero
    Vector<double> interpolated_u(NFIELDS,0.0);
    Vector<double> interpolated_x(DIM,0.0);
    Vector<Vector<double> > interpolated_dudx(NFIELDS);
    //Calculate function value and derivatives:
    //-----------------------------------------
    for (unsigned i=0;i<NFIELDS;i++)
     {
      interpolated_dudx[i].resize(DIM);
      for (unsigned ii=0;ii<DIM;ii++)
       {
        interpolated_dudx[i][ii]=0.0;
       }
     }
    // Loop over nodes
    for(unsigned l=0;l<n_node;l++)
     {
      // Loop over directions for coordinates
      for(unsigned j=0;j<DIM;j++)
       {
        interpolated_x[j] += raw_nodal_position(l,j)*psi(l);
       }
      // Loop over fields
      for (unsigned i=0;i<NFIELDS;i++)
       {
        //Index at which the multi_poisson unknown is stored
        unsigned u_nodal_index = u_index_multi_poisson(i);
        //Get the nodal value of the multi_poisson unknown
        double u_value = raw_nodal_value(l,u_nodal_index);
        interpolated_u[i] += u_value*psi(l);
        // Loop over directions for derivs
        for(unsigned j=0;j<DIM;j++)
         {
          interpolated_dudx[i][j] += u_value*dpsidx(l,j);
         }
       }
     }
    //Get source function
    //-------------------
    Vector<double> source(NFIELDS);
    get_source_multi_poisson(ipt,interpolated_x,source);
    // Get interaction parameter
 #ifdef PARANOID
    if (Beta_pt==0)
     {
      throw OomphLibError(
       "Beta_pt hasn't been set!",
       OOMPH_CURRENT_FUNCTION,
       OOMPH_EXCEPTION_LOCATION);
     }
 #endif
    const double beta_local=*Beta_pt;
    // Assemble residuals and Jacobian
    //--------------------------------
    // Loop over the test functions
    for(unsigned l=0;l<n_node;l++)
     {
      for (unsigned i=0;i<NFIELDS;i++)
       {
        //Index at which the multi_poisson unknown is stored
        unsigned u_nodal_index = u_index_multi_poisson(i);
        //Get the local equation
        local_eqn = nodal_local_eqn(l,u_nodal_index);
        // IF it's not a boundary condition
        if(local_eqn >= 0)
         {
          // Add body force/source term here
          residuals[local_eqn] += source[i]*test(l)*W;
          // The Poisson bit itself
          for(unsigned k=0;k<DIM;k++)
           {
            residuals[local_eqn] +=
             double(i+1)*interpolated_dudx[i][k]*dtestdx(l,k)*W;
           }
          // The interaction bit:
          for(unsigned k=0;k<NFIELDS;k++)
           {
            residuals[local_eqn] -=
             double(i+1)*beta_local*interpolated_u[k]*test(l)*W;
           }
          // Calculate the jacobian
          //-----------------------
          if(flag)
           {
            //Loop over the velocity shape functions again
            for(unsigned l2=0;l2<n_node;l2++)
             {
              for (unsigned i2=0;i2<NFIELDS;i2++)
               {
                //Index at which the multi_poisson unknown is stored
                unsigned u_nodal_index2 = u_index_multi_poisson(i2);
                local_unknown = nodal_local_eqn(l2,u_nodal_index2);
                //If at a non-zero degree of freedom add in the entry
                if(local_unknown >= 0)
                 {
                  // The Poisson bit
                  if(i==i2)
                   {
                    for(unsigned ii=0;ii<DIM;ii++)
                     {
                      jacobian(local_eqn,local_unknown)
                       += double(i+1)*dpsidx(l2,ii)*dtestdx(l,ii)*W;
                     }
                   }
                  jacobian(local_eqn,local_unknown) -=
                   double(i+1)*beta_local*psi(l2)*test(l)*W;
                 }
               }
             }
           }
         }
       }
     }
   } // End of loop over integration points
 }
References DIM, i, J, j, k, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, TestProblem::source(), Eigen::test, w, and oomph::QuadTreeNames::W.
Referenced by oomph::MultiPoissonEquations< DIM, NFIELDS >::fill_in_contribution_to_jacobian(), and oomph::MultiPoissonEquations< DIM, NFIELDS >::fill_in_contribution_to_residuals().
get_dof_numbers_for_unknowns()
template<unsigned DIM, unsigned NFIELDS> void oomph::MultiPoissonEquations< DIM, NFIELDS >::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned > > & block_lookup_list) const inline
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the "DOF" that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.)
  {
   // temporary pair (used to store block lookup prior to being added to list
   std::pair<unsigned,unsigned> block_lookup;
   // number of nodes
   const unsigned n_node = this->nnode();
   //Integer storage for local unknown
   int local_unknown=0;
   //Loop over the nodes
   for(unsigned n=0;n<n_node;n++)
    {
     //Loop over fields
     for(unsigned i=0;i<NFIELDS;i++)
      {
       //Index at which the multi_poisson unknown is stored
       unsigned u_nodal_index = u_index_multi_poisson(i);
       //Get the local equation
       local_unknown = nodal_local_eqn(n,u_nodal_index);
       // ignore pinned values
       if (local_unknown >= 0)
        {
         // store block lookup in temporary pair: First entry in pair
         // is global equation number; second entry is block type
         block_lookup.first = this->eqn_number(local_unknown);
         block_lookup.second = i;
         // add to list
         block_lookup_list.push_front(block_lookup);
        }
      }
    }
  }
References oomph::GeneralisedElement::eqn_number(), i, n, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), and oomph::MultiPoissonEquations< DIM, NFIELDS >::u_index_multi_poisson().
get_flux()
template<unsigned DIM, unsigned NFIELDS> void oomph::MultiPoissonEquations< DIM, NFIELDS >::get_flux (const Vector< double > & s, Vector< double > & flux) const inline
Get flux: flux[i] = du/dx_i.
   {
    abort();
    /* //Find out how many nodes there are in the element */
    /* const unsigned n_node = nnode(); */
    /* //Get the index at which the unknown is stored */
    /* const unsigned u_nodal_index = u_index_multi_poisson(); */
    /* //Set up memory for the shape and test functions */
    /* Shape psi(n_node); */
    /* DShape dpsidx(n_node,DIM); */
    /* //Call the derivatives of the shape and test functions */
    /* dshape_eulerian(s,psi,dpsidx); */
    /* //Initialise to zero */
    /* for(unsigned j=0;j<DIM;j++) */
    /*  { */
    /*   flux[j] = 0.0; */
    /*  } */
    /* // Loop over nodes */
    /* for(unsigned l=0;l<n_node;l++)  */
    /*  { */
    /*   //Loop over derivative directions */
    /*   for(unsigned j=0;j<DIM;j++) */
    /*    {                                */
    /*     flux[j] += this->nodal_value(l,u_nodal_index)*dpsidx(l,j); */
    /*    } */
    /*  } */
   }
get_source_multi_poisson()
template<unsigned DIM, unsigned NFIELDS> virtual void oomph::MultiPoissonEquations< DIM, NFIELDS >::get_source_multi_poisson (const unsigned & ipt, const Vector< double > & x, Vector< double > & source) const inline virtual
Get source term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the source function might be determined by another system of equations.
  {
   //If no source function has been set, return zero
   if(Source_fct_pt==0)
    {
     for (unsigned i=0;i<NFIELDS;i++)
      {
       source[i] = 0.0;
      }
    }
   else
    {
     // Get source strength
     (*Source_fct_pt)(x,source);
    }
  }
References i, TestProblem::source(), oomph::MultiPoissonEquations< DIM, NFIELDS >::Source_fct_pt, and plotDoE::x.
interpolated_u_multi_poisson()
template<unsigned DIM, unsigned NFIELDS> double oomph::MultiPoissonEquations< DIM, NFIELDS >::interpolated_u_multi_poisson (const unsigned & i, const Vector< double > & s) const inline
Return FE representation of i-th function value u_multi_poisson(s) at local coordinate s
   {
    //Find number of nodes
    const unsigned n_node = nnode();
    //Get the index at which the multi_poisson unknown is stored
    const unsigned u_nodal_index = u_index_multi_poisson(i);
    //Local shape function
    Shape psi(n_node);
    //Find values of shape function
    shape(s,psi);
    //Initialise value of u
    double interpolated_u = 0.0;
    //Loop over the local nodes and sum
    for(unsigned l=0;l<n_node;l++)
     {
      interpolated_u += this->nodal_value(l,u_nodal_index)*psi[l];
     }
    return(interpolated_u);
   }
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), and oomph::MultiPoissonEquations< DIM, NFIELDS >::u_index_multi_poisson().
Referenced by oomph::MultiPoissonEquations< DIM, NFIELDS >::scalar_value_paraview().
ndof_types()
template<unsigned DIM, unsigned NFIELDS> unsigned oomph::MultiPoissonEquations< DIM, NFIELDS >::ndof_types () const inline virtual
returns the number of DOF types associated with this element: The number of fields
Reimplemented from oomph::GeneralisedElement.
  {
   return NFIELDS;
  }
nscalar_paraview()
template<unsigned DIM, unsigned NFIELDS> unsigned oomph::MultiPoissonEquations< DIM, NFIELDS >::nscalar_paraview () const inline virtual
Number of scalars/fields output by this element. Reimplements broken virtual function in base class.
Reimplemented from oomph::FiniteElement.
   {
    return NFIELDS;
   }
output() [1/4]
template<unsigned DIM, unsigned NFIELDS> void oomph::MultiPoissonEquations< DIM, NFIELDS >::output (FILE * file_pt) inline virtual
C_style output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QMultiPoissonElement< DIM, NNODE_1D, NFIELDS >.
   {
    const unsigned n_plot=5;
    output(file_pt,n_plot);
   }
References oomph::MultiPoissonEquations< DIM, NFIELDS >::output().
output() [2/4]
template<unsigned DIM, unsigned NFIELDS> void oomph::MultiPoissonEquations< DIM, NFIELDS >::output (FILE * file_pt, const unsigned & nplot) virtual
C-style output FE representation of soln: x,y,u or x,y,z,u at n_plot^DIM plot points
C-style output function:
x,y,u or x,y,z,u
nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QMultiPoissonElement< DIM, NNODE_1D, NFIELDS >.
 {
  //Vector of local coordinates
  Vector<double> s(DIM);
  // Tecplot header info
  fprintf(file_pt,"%s",tecplot_zone_string(nplot).c_str());
  // Loop over plot points
  unsigned num_plot_points=nplot_points(nplot);
  for (unsigned iplot=0;iplot<num_plot_points;iplot++)
   {
    // Get local coordinates of plot point
    get_s_plot(iplot,nplot,s);
    for(unsigned i=0;i<DIM;i++)
     {
      fprintf(file_pt,"%g ",interpolated_x(s,i));
     }
    for(unsigned i=0;i<NFIELDS;i++)
     {
      fprintf(file_pt,"%g ",interpolated_u_multi_poisson(i,s));
     }
    fprintf(file_pt,"\n");
   }
  // Write tecplot footer (e.g. FE connectivity lists)
  write_tecplot_zone_footer(file_pt,nplot);
 }
References DIM, i, and s.
output() [3/4]
template<unsigned DIM, unsigned NFIELDS> void oomph::MultiPoissonEquations< DIM, NFIELDS >::output (std::ostream & outfile) inline virtual
Output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QMultiPoissonElement< DIM, NNODE_1D, NFIELDS >.
   {
    const unsigned n_plot=5;
    output(outfile,n_plot);
   }
Referenced by oomph::MultiPoissonEquations< DIM, NFIELDS >::output(), and oomph::QMultiPoissonElement< DIM, NNODE_1D, NFIELDS >::output().
output() [4/4]
template<unsigned DIM, unsigned NFIELDS> void oomph::MultiPoissonEquations< DIM, NFIELDS >::output (std::ostream & outfile, const unsigned & nplot) virtual
Output FE representation of soln: x,y,u or x,y,z,u at n_plot^DIM plot points
Output function:
x,y,u or x,y,z,u
nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QMultiPoissonElement< DIM, NNODE_1D, NFIELDS >.
 {
  //Vector of local coordinates
  Vector<double> s(DIM);
  // Tecplot header info
  outfile << tecplot_zone_string(nplot);
  // Loop over plot points
  unsigned num_plot_points=nplot_points(nplot);
  for (unsigned iplot=0;iplot<num_plot_points;iplot++)
   {
    // Get local coordinates of plot point
    get_s_plot(iplot,nplot,s);
    for(unsigned i=0;i<DIM;i++)
     {
      outfile << interpolated_x(s,i) << " ";
     }
    for(unsigned i=0;i<NFIELDS;i++)
     {
      outfile << interpolated_u_multi_poisson(i,s) << " ";
     }
    outfile << std::endl;
   }
  // Write tecplot footer (e.g. FE connectivity lists)
  write_tecplot_zone_footer(outfile,nplot);
 }
References DIM, i, and s.
output_fct() [1/2]
template<unsigned DIM, unsigned NFIELDS> virtual void oomph::MultiPoissonEquations< DIM, NFIELDS >::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) inline virtual
Output exact soln: x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points (dummy time-dependent version to keep intel compiler happy)
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QMultiPoissonElement< DIM, NNODE_1D, NFIELDS >.
   {
    throw OomphLibError(
     "There is no time-dependent output_fct() for MultiPoisson elements ",
     OOMPH_CURRENT_FUNCTION,
     OOMPH_EXCEPTION_LOCATION);
   }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
output_fct() [2/2]
template<unsigned DIM, unsigned NFIELDS> void oomph::MultiPoissonEquations< DIM, NFIELDS >::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) virtual
Output exact soln: x,y,u_exact or x,y,z,u_exact at n_plot^DIM plot points.
Output exact solution
Solution is provided via function pointer. Plot at a given number of plot points.
x,y,u_exact or x,y,z,u_exact
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::QMultiPoissonElement< DIM, NNODE_1D, NFIELDS >.
 {
  //Vector of local coordinates
  Vector<double> s(DIM);
   // Vector for coordintes
   Vector<double> x(DIM);
  // Tecplot header info
  outfile << tecplot_zone_string(nplot);
  // Exact solution Vector
  Vector<double> exact_soln(NFIELDS);
  // Loop over plot points
  unsigned num_plot_points=nplot_points(nplot);
  for (unsigned iplot=0;iplot<num_plot_points;iplot++)
   {
    // Get local coordinates of plot point
    get_s_plot(iplot,nplot,s);
    // Get x position as Vector
    interpolated_x(s,x);
    // Get exact solution at this point
    (*exact_soln_pt)(x,exact_soln);
    //Output x,y,...,u_exact
    for(unsigned i=0;i<DIM;i++)
     {
      outfile << x[i] << " ";
     }
    for(unsigned i=0;i<NFIELDS;i++)
     {
      outfile << exact_soln[i] << " ";
     }
    outfile << std::endl;
   }
  // Write tecplot footer (e.g. FE connectivity lists)
  write_tecplot_zone_footer(outfile,nplot);
 }
References DIM, ProblemParameters::exact_soln(), i, s, and plotDoE::x.
Referenced by oomph::QMultiPoissonElement< DIM, NNODE_1D, NFIELDS >::output_fct().
scalar_name_paraview()
template<unsigned DIM, unsigned NFIELDS> std::string oomph::MultiPoissonEquations< DIM, NFIELDS >::scalar_name_paraview (const unsigned & i) const inline virtual
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc. Can (should!) be overloaded with more meaningful names in specific elements.
Reimplemented from oomph::FiniteElement.
   {
 #ifdef PARANOID
    if (i>=NFIELDS)
     {
      std::stringstream error_stream;
      error_stream
       << "MultiPoisson elements only stores "
       << NFIELDS << " fields so i "
       << i << " is illegal." << std::endl;
      throw OomphLibError(
       error_stream.str(),
       OOMPH_CURRENT_FUNCTION,
       OOMPH_EXCEPTION_LOCATION);
     }
 #endif
    return "MultiPoisson solution"+StringConversion::to_string(i);
   }
References i, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::StringConversion::to_string().
scalar_value_paraview()
template<unsigned DIM, unsigned NFIELDS> void oomph::MultiPoissonEquations< DIM, NFIELDS >::scalar_value_paraview (std::ofstream & file_out, const unsigned & i, const unsigned & nplot) const inline virtual
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
Reimplemented from oomph::FiniteElement.
   {
 #ifdef PARANOID
    if (i>=NFIELDS)
     {
      std::stringstream error_stream;
      error_stream
       << "MultiPoisson elements only stores "
       << NFIELDS << " fields so i "
       << i << " is illegal." << std::endl;
      throw OomphLibError(
       error_stream.str(),
       OOMPH_CURRENT_FUNCTION,
       OOMPH_EXCEPTION_LOCATION);
     }
 #endif
    unsigned local_loop=this->nplot_points_paraview(nplot);
    for(unsigned j=0;j<local_loop;j++)
     {
      // Get the local coordinate of the required plot point
      Vector<double> s(DIM);
      this->get_s_plot(j,nplot,s);
      file_out << this->interpolated_u_multi_poisson(i,s)
               << std::endl;
     }
   }
References DIM, oomph::FiniteElement::get_s_plot(), i, oomph::MultiPoissonEquations< DIM, NFIELDS >::interpolated_u_multi_poisson(), j, oomph::FiniteElement::nplot_points_paraview(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and s.
self_test()
template<unsigned DIM, unsigned NFIELDS> unsigned oomph::MultiPoissonEquations< DIM, NFIELDS >::self_test virtual
Self-test: Return 0 for OK.
Reimplemented from oomph::FiniteElement.
 {
  bool passed=true;
  // Check lower-level stuff
  if (FiniteElement::self_test()!=0)
   {
    passed=false;
   }
  // Return verdict
  if (passed)
   {
    return 0;
   }
  else
   {
    return 1;
   }
 }
References oomph::FiniteElement::self_test().
source_fct_pt() [1/2]
template<unsigned DIM, unsigned NFIELDS> MultiPoissonSourceFctPt& oomph::MultiPoissonEquations< DIM, NFIELDS >::source_fct_pt () inline
Access function: Pointer to source function.
 {return Source_fct_pt;}
References oomph::MultiPoissonEquations< DIM, NFIELDS >::Source_fct_pt.
source_fct_pt() [2/2]
template<unsigned DIM, unsigned NFIELDS> MultiPoissonSourceFctPt oomph::MultiPoissonEquations< DIM, NFIELDS >::source_fct_pt () const inline
Access function: Pointer to source function. Const version.
 {return Source_fct_pt;}
References oomph::MultiPoissonEquations< DIM, NFIELDS >::Source_fct_pt.
u_index_multi_poisson()
template<unsigned DIM, unsigned NFIELDS> virtual unsigned oomph::MultiPoissonEquations< DIM, NFIELDS >::u_index_multi_poisson (const unsigned & i) const inline virtual
Return the index at which the unknown value is stored. The default value, i, is appropriate for single-physics problems, when there is only one variable, the value that satisfies the multi_poisson equation. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknown is always stored at the same index at each node.
  {return i;}
References i.
Referenced by oomph::MultiPoissonEquations< DIM, NFIELDS >::get_dof_numbers_for_unknowns(), and oomph::MultiPoissonEquations< DIM, NFIELDS >::interpolated_u_multi_poisson().
Member Data Documentation
Beta_pt
template<unsigned DIM, unsigned NFIELDS> double* oomph::MultiPoissonEquations< DIM, NFIELDS >::Beta_pt protected
Pointer to interaction parameter Beta.
Referenced by oomph::MultiPoissonEquations< DIM, NFIELDS >::beta_pt().
Source_fct_pt
template<unsigned DIM, unsigned NFIELDS> MultiPoissonSourceFctPt oomph::MultiPoissonEquations< DIM, NFIELDS >::Source_fct_pt protected
Pointer to source function:
Referenced by oomph::MultiPoissonEquations< DIM, NFIELDS >::get_source_multi_poisson(), and oomph::MultiPoissonEquations< DIM, NFIELDS >::source_fct_pt().
The documentation for this class was generated from the following file:
multi_poisson_elements.h