MercuryDPM: oomph::OneDLegendreShapeParam Class Reference
oomph::OneDLegendreShapeParam Class Reference
Class that returns the shape functions associated with legendre.
#include <Qspectral_elements.h>
Public Member Functions
OneDLegendreShapeParam (const unsigned &order, const double &s)
Constructor.
Public Member Functions inherited from oomph::Shape
Shape (const unsigned &N)
Constructor for a single-index set of shape functions.
Shape (const unsigned &N, const unsigned &M)
Constructor for a two-index set of shape functions.
Shape (const Shape &shape)=delete
Broken copy constructor.
Shape ()
void operator= (const Shape &shape)
void operator= (Shape *const &shape_pt)
~Shape ()
Destructor, clear up the memory allocated by the object.
void resize (const unsigned &N, const unsigned &M=1)
Change the size of the storage.
double & operator[] (const unsigned &i)
Overload the bracket operator to provide access to values.
const double & operator[] (const unsigned &i) const
Overload the bracket operator (const version)
double & operator() (const unsigned &i)
Overload the round bracket operator to provide access to values.
const double & operator() (const unsigned &i) const
Overload the round bracket operator (const version)
double & operator() (const unsigned &i, const unsigned &j)
Overload the round bracket operator, allowing for two indices.
const double & operator() (const unsigned &i, const unsigned &j) const
unsigned nindex1 () const
Return the range of index 1 of the shape function object.
unsigned nindex2 () const
Return the range of index 2 of the shape function object.
Static Public Member Functions
static void calculate_nodal_positions (const unsigned &order)
Static function used to populate the stored positions.
static double nodal_position (const unsigned &order, const unsigned &n)
Static Public Attributes
static std::map< unsigned, Vector< double > > z
Additional Inherited Members
Protected Member Functions inherited from oomph::Shape
void range_check (const unsigned &i, const unsigned &j) const
Private function that checks whether the index is in range.
Protected Attributes inherited from oomph::Shape
double * Psi
double * Allocated_storage
unsigned Index1
Size of the first index of the shape function.
unsigned Index2
Size of the second index of the shape function.
Detailed Description
Class that returns the shape functions associated with legendre.
Constructor & Destructor Documentation
OneDLegendreShapeParam()
oomph::OneDLegendreShapeParam::OneDLegendreShapeParam (const unsigned & order, const double & s) inline
Constructor.
       : Shape(order)
     {
       using namespace Orthpoly;
       unsigned p = order - 1;
       // Now populate the shape function
       for (unsigned i = 0; i < order; i++)
       {
         // If we're at one of the nodes, the value must be 1.0
         if (std::fabs(s - z[order][i]) < Orthpoly::eps)
         {
           (*this)[i] = 1.0;
         }
         // Otherwise use the lagrangian interpolant
         else
         {
           (*this)[i] =
             (1.0 - s * s) * dlegendre(p, s) /
             (p * (p + 1) * legendre(p, z[order][i]) * (z[order][i] - s));
         }
       }
     }
References oomph::Orthpoly::dlegendre(), oomph::Orthpoly::eps, boost::multiprecision::fabs(), i, oomph::Orthpoly::legendre(), p, s, and z.
Member Function Documentation
calculate_nodal_positions()
static void oomph::OneDLegendreShapeParam::calculate_nodal_positions (const unsigned & order) inline static
Static function used to populate the stored positions.
     {
       // If we haven't already calculated these
       if (z.find(order) == z.end())
       {
         Orthpoly::gll_nodes(order, z[order]);
       }
     }
References oomph::Orthpoly::gll_nodes(), and z.
nodal_position()
static double oomph::OneDLegendreShapeParam::nodal_position (const unsigned & order, const unsigned & n) inline static
     {
       return z[order][n];
     }
References n, and z.
Member Data Documentation
z
std::map< unsigned, Vector< double > > oomph::OneDLegendreShapeParam::z static
Referenced by calculate_nodal_positions(), nodal_position(), oomph::OneDLegendreDShapeParam::OneDLegendreDShapeParam(), and OneDLegendreShapeParam().
The documentation for this class was generated from the following files:
Qspectral_elements.h
Qspectral_elements.cc