MercuryDPM: AngledPeriodicBoundaryUnitTest.cpp File Reference
AngledPeriodicBoundaryUnitTest.cpp File Reference
#include "Species/Species.h"
#include "Species/LinearViscoelasticFrictionReversibleAdhesiveSpecies.h"
#include "DPMBase.h"
#include "Boundaries/PeriodicBoundary.h"
#include "Boundaries/AngledPeriodicBoundary.h"
Classes
class AngledPeriodicBoundaryUnitTest
Functions
int main (int argc UNUSED, char *argv[] UNUSED)
Function Documentation
main()
int main (int argc UNUSED, char *argv[] UNUSED)
 {
     AngledPeriodicBoundaryUnitTest dpm;
     dpm.setName("AngledPeriodicBoundaryUnitTest");
     dpm.setTimeMax(4.0*constants::pi);
     dpm.setTimeMax(9.5*dpm.getTimeStep());
     dpm.setXMin(0);
     dpm.setXMax( 5);
     dpm.setYMin(0);
     dpm.setYMax( 5);
     dpm.setZMin(0);
     dpm.setZMax( 5);
     dpm.setGravity({0,0,0});
     dpm.solve(argc, argv);
     //Note:: currently the rolling spring is not conserved!!
     return 0;
 }
References DPMBase::getTimeStep(), constants::pi, DPMBase::setGravity(), DPMBase::setName(), DPMBase::setTimeMax(), DPMBase::setXMax(), DPMBase::setXMin(), DPMBase::setYMax(), DPMBase::setYMin(), DPMBase::setZMax(), DPMBase::setZMin(), and DPMBase::solve().