MercuryDPM: Eigen::internal::unary_evaluator< CwiseUnaryView< UnaryOp, ArgType, StrideType >, IndexBased > Struct Template Reference
Eigen::internal::unary_evaluator< CwiseUnaryView< UnaryOp, ArgType, StrideType >, IndexBased > Struct Template Reference
#include <CoreEvaluators.h>
Classes
struct Data
Public Types
enum { CoeffReadCost = int(evaluator<ArgType>::CoeffReadCost) + int(functor_traits<UnaryOp>::Cost) , Flags = (evaluator<ArgType>::Flags & (HereditaryBits | LinearAccessBit | DirectAccessBit)) , Alignment = 0 }
typedef CwiseUnaryView< UnaryOp, ArgType, StrideType > XprType
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
Public Types inherited from Eigen::internal::evaluator_base< CwiseUnaryView< UnaryOp, ArgType, StrideType > >
enum
typedef traits< CwiseUnaryView< UnaryOp, ArgType, StrideType > > ExpressionTraits
Public Member Functions
EIGEN_DEVICE_FUNC unary_evaluator (const XprType &op)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index row, Index col)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index index)
Public Member Functions inherited from Eigen::internal::evaluator_base< CwiseUnaryView< UnaryOp, ArgType, StrideType > >
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE evaluator_base ()=default
Protected Attributes
Data m_d
Member Typedef Documentation
CoeffReturnType
template<typename UnaryOp , typename ArgType , typename StrideType > typedef XprType::CoeffReturnType Eigen::internal::unary_evaluator< CwiseUnaryView< UnaryOp, ArgType, StrideType >, IndexBased >::CoeffReturnType
Scalar
template<typename UnaryOp , typename ArgType , typename StrideType > typedef XprType::Scalar Eigen::internal::unary_evaluator< CwiseUnaryView< UnaryOp, ArgType, StrideType >, IndexBased >::Scalar
XprType
template<typename UnaryOp , typename ArgType , typename StrideType > typedef CwiseUnaryView<UnaryOp, ArgType, StrideType> Eigen::internal::unary_evaluator< CwiseUnaryView< UnaryOp, ArgType, StrideType >, IndexBased >::XprType
Member Enumeration Documentation
anonymous enum
template<typename UnaryOp , typename ArgType , typename StrideType > anonymous enum
Enumerator
CoeffReadCost
Flags
Alignment
        {
     CoeffReadCost = int(evaluator<ArgType>::CoeffReadCost) + int(functor_traits<UnaryOp>::Cost),
     Flags = (evaluator<ArgType>::Flags & (HereditaryBits | LinearAccessBit | DirectAccessBit)),
     Alignment = 0  // FIXME it is not very clear why alignment is necessarily lost...
   };
Constructor & Destructor Documentation
unary_evaluator()
template<typename UnaryOp , typename ArgType , typename StrideType > EIGEN_DEVICE_FUNC Eigen::internal::unary_evaluator< CwiseUnaryView< UnaryOp, ArgType, StrideType >, IndexBased >::unary_evaluator (const XprType & op) inline explicit
                                                                 : m_d(op) {
     EIGEN_INTERNAL_CHECK_COST_VALUE(functor_traits<UnaryOp>::Cost);
     EIGEN_INTERNAL_CHECK_COST_VALUE(CoeffReadCost);
   }
References EIGEN_INTERNAL_CHECK_COST_VALUE.
Member Function Documentation
coeff() [1/2]
template<typename UnaryOp , typename ArgType , typename StrideType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::unary_evaluator< CwiseUnaryView< UnaryOp, ArgType, StrideType >, IndexBased >::coeff (Index index) const inline
{
     return m_d.func()(m_d.argImpl.coeff(index));
   }
coeff() [2/2]
template<typename UnaryOp , typename ArgType , typename StrideType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::unary_evaluator< CwiseUnaryView< UnaryOp, ArgType, StrideType >, IndexBased >::coeff (Index row, Index col) const inline
{
     return m_d.func()(m_d.argImpl.coeff(row, col));
   }
References col(), and row().
coeffRef() [1/2]
template<typename UnaryOp , typename ArgType , typename StrideType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::internal::unary_evaluator< CwiseUnaryView< UnaryOp, ArgType, StrideType >, IndexBased >::coeffRef (Index index) inline
{
     return m_d.func()(m_d.argImpl.coeffRef(index));
   }
coeffRef() [2/2]
template<typename UnaryOp , typename ArgType , typename StrideType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::internal::unary_evaluator< CwiseUnaryView< UnaryOp, ArgType, StrideType >, IndexBased >::coeffRef (Index row, Index col) inline
{
     return m_d.func()(m_d.argImpl.coeffRef(row, col));
   }
References col(), and row().
Member Data Documentation
m_d
template<typename UnaryOp , typename ArgType , typename StrideType > Data Eigen::internal::unary_evaluator< CwiseUnaryView< UnaryOp, ArgType, StrideType >, IndexBased >::m_d protected
The documentation for this struct was generated from the following file:
CoreEvaluators.h