MercuryDPM: oomph::Orthpoly Namespace Reference
oomph::Orthpoly Namespace Reference
Functions
void gll_nodes (const unsigned &Nnode, Vector< double > &x)
Calculates the Gauss Lobatto Legendre abscissas for degree p = NNode-1.
void gll_nodes (const unsigned &Nnode, Vector< double > &x, Vector< double > &w)
void gl_nodes (const unsigned &Nnode, Vector< double > &x)
void gl_nodes (const unsigned &Nnode, Vector< double > &x, Vector< double > &w)
double legendre (const unsigned &p, const double &x)
void legendre_vector (const unsigned &p, const double &x, Vector< double > &polys)
double dlegendre (const unsigned &p, const double &x)
double ddlegendre (const unsigned &p, const double &x)
double jacobi (const int &alpha, const int &beta, const unsigned &p, const double &x)
Calculate the Jacobi polnomials.
void jacobi (const int &alpha, const int &beta, const unsigned &p, const double &x, Vector< double > &polys)
Calculate the Jacobi polnomials all in one goe.
Variables
const double eps = 1.0e-15
Function Documentation
ddlegendre()
double oomph::Orthpoly::ddlegendre (const unsigned & p, const double & x) inline
Calculates second derivative of Legendre polynomial of degree p at x using three term recursive formula.
     {
       double ddL2 = 3.0, ddL3 = 15 * x, ddL4 = 0.0;
       if (p == 0) return 0.0;
       else if (p == 1)
         return 0.0;
       else if (p == 2)
         return ddL2;
       else if (p == 3)
         return ddL3;
       else
       {
         for (unsigned i = 3; i < p; i++)
         {
           ddL4 =
             1.0 / (i - 1.0) * ((2.0 * i + 1.0) * x * ddL3 - (i + 2.0) * ddL2);
           ddL2 = ddL3;
           ddL3 = ddL4;
         }
         return ddL4;
       }
     }
References i, p, and plotDoE::x.
Referenced by gll_nodes(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::oc_hang_helper(), oomph::OneDimensionalLegendreDShape< NNODE_1D >::OneDimensionalLegendreDShape(), oomph::OneDLegendreDShapeParam::OneDLegendreDShapeParam(), and oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::quad_hang_helper().
dlegendre()
double oomph::Orthpoly::dlegendre (const unsigned & p, const double & x) inline
Calculates first derivative of Legendre polynomial of degree p at x using three term recursive formula. \(nP_{n+1}^{'} = (2n+1)xP_{n}^{'} - (n+1)P_{n-1}^{'} \)
     {
       double dL1 = 1.0, dL2 = 3 * x, dL3 = 0.0;
       if (p == 0) return 0.0;
       else if (p == 1)
         return dL1;
       else if (p == 2)
         return dL2;
       else
       {
         for (unsigned n = 2; n < p; n++)
         {
           dL3 = 1.0 / n * ((2.0 * n + 1.0) * x * dL2 - (n + 1.0) * dL1);
           dL1 = dL2;
           dL2 = dL3;
         }
         return dL3;
       }
     }
References n, p, and plotDoE::x.
Referenced by gl_nodes(), gll_nodes(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::oc_hang_helper(), oomph::OneDimensionalLegendreDShape< NNODE_1D >::OneDimensionalLegendreDShape(), oomph::OneDimensionalLegendreShape< NNODE_1D >::OneDimensionalLegendreShape(), oomph::OneDimensionalModalDShape::OneDimensionalModalDShape(), oomph::OneDLegendreDShapeParam::OneDLegendreDShapeParam(), oomph::OneDLegendreShapeParam::OneDLegendreShapeParam(), and oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::quad_hang_helper().
gl_nodes() [1/2]
void oomph::Orthpoly::gl_nodes (const unsigned & Nnode, Vector< double > & x)
     {
       double z, zold, del;
       unsigned p = Nnode - 1;
       x.resize(Nnode);
       if (Nnode < 2)
       {
         throw OomphLibError("Invalid number of nodes",
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
       else if (Nnode == 2)
       {
         x[0] = -1.0 / 3.0 * std::sqrt(3.0);
         x[1] = -x[0];
       }
       else
       {
         unsigned mid;
         if (p % 2 == 0)
         {
           mid = p / 2;
           x[mid] = 0.0;
         }
         else
           mid = p / 2 + 1;
         for (unsigned j = 0; j < mid; j++)
         {
           z = -std::cos((2.0 * j + 1.0) * MathematicalConstants::Pi /
                         (2 * double(p) + 2.0));
           do
           {
             del = legendre(p + 1, z) / dlegendre(p + 1, z);
             zold = z;
             z = zold - del;
           } while (std::fabs(z - zold) > eps);
           x[j] = z;
           x[p - j] = -z;
         }
       }
     }
References cos(), dlegendre(), eps, boost::multiprecision::fabs(), j, legendre(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, p, oomph::MathematicalConstants::Pi, sqrt(), and plotDoE::x.
Referenced by oomph::GaussLegendre< 1, NPTS_1D >::GaussLegendre(), oomph::GaussLegendre< 2, NPTS_1D >::GaussLegendre(), oomph::GaussLegendre< 3, NPTS_1D >::GaussLegendre(), and gl_nodes().
gl_nodes() [2/2]
void oomph::Orthpoly::gl_nodes (const unsigned & Nnode, Vector< double > & x, Vector< double > & w)
     {
       gl_nodes(Nnode, x);
       // Now calculate the corresponding weights
       double dl_z;
       unsigned p = Nnode - 1;
       for (unsigned i = 0; i < p + 1; i++)
       {
         dl_z = dlegendre(p + 1, x[i]);
         w[i] = 2.0 / (1 - x[i] * x[i]) / (dl_z * dl_z);
       }
     }
References dlegendre(), gl_nodes(), i, p, w, and plotDoE::x.
gll_nodes() [1/2]
void oomph::Orthpoly::gll_nodes (const unsigned & Nnode, Vector< double > & x)
Calculates the Gauss Lobatto Legendre abscissas for degree p = NNode-1.
     {
       double z, zold, del;
       unsigned p = Nnode - 1;
       x.resize(Nnode);
       if (Nnode < 2)
       {
         throw OomphLibError("Invalid number of nodes",
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
       else if (Nnode == 2)
       {
         x[0] = -1.0;
         x[1] = 1.0;
       }
       else if (Nnode == 3)
       {
         x[0] = -1;
         x[1] = 0.0;
         x[2] = 1.0;
       }
       else if (Nnode == 4)
       {
         x[0] = -1.0;
         x[1] = -std::sqrt(5.0) / 5.0;
         x[2] = -x[1];
         x[3] = 1.0;
       }
       else
       {
         unsigned mid;
         if (p % 2 == 0)
         {
           mid = p / 2;
           x[mid] = 0.0;
         }
         else
           mid = p / 2 + 1;
         for (unsigned j = 1; j < mid; j++)
         {
           z = -std::cos(j * MathematicalConstants::Pi / double(p));
           do
           {
             del = dlegendre(p, z) / ddlegendre(p, z);
             zold = z;
             z = zold - del;
           } while (std::fabs(z - zold) > eps);
           x[j] = z;
           x[p - j] = -z;
         }
         x[0] = -1.0;
         x[p] = 1.0;
       }
     }
References cos(), ddlegendre(), dlegendre(), eps, boost::multiprecision::fabs(), j, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, p, oomph::MathematicalConstants::Pi, sqrt(), and plotDoE::x.
Referenced by oomph::OneDimensionalLegendreShape< NNODE_1D >::calculate_nodal_positions(), oomph::OneDLegendreShapeParam::calculate_nodal_positions(), oomph::GaussLobattoLegendre< 1, NPTS_1D >::GaussLobattoLegendre(), oomph::GaussLobattoLegendre< 2, NPTS_1D >::GaussLobattoLegendre(), oomph::GaussLobattoLegendre< 3, NPTS_1D >::GaussLobattoLegendre(), oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::get_node_at_local_coordinate(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::get_node_at_local_coordinate(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::get_node_at_local_coordinate(), gll_nodes(), oomph::PRefineableQElement< 3, INITIAL_NNODE_1D >::oc_hang_helper(), and oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::quad_hang_helper().
gll_nodes() [2/2]
void oomph::Orthpoly::gll_nodes (const unsigned & Nnode, Vector< double > & x, Vector< double > & w)
     {
       gll_nodes(Nnode, x);
       // Now calculate the corresponding weights
       double l_z;
       unsigned p = Nnode - 1;
       for (unsigned i = 0; i < p + 1; i++)
       {
         l_z = legendre(p, x[i]);
         w[i] = 2.0 / (p * (p + 1) * l_z * l_z);
       }
     }
References gll_nodes(), i, legendre(), p, w, and plotDoE::x.
jacobi() [1/2]
double oomph::Orthpoly::jacobi (const int & alpha, const int & beta, const unsigned & p, const double & x) inline
Calculate the Jacobi polnomials.
     {
       double P0 = 1.0;
       double P1 = 0.5 * (alpha - beta + (alpha + beta + 2.0) * x);
       double P2;
       if (p == 0) return P0;
       else if (p == 1)
         return P1;
       else
       {
         for (unsigned n = 1; n < p; n++)
         {
           double a1n =
             2 * (n + 1) * (n + alpha + beta + 1) * (2 * n + alpha + beta);
           double a2n =
             (2 * n + alpha + beta + 1) * (alpha * alpha - beta * beta);
           double a3n = (2 * n + alpha + beta) * (2 * n + alpha + beta + 1) *
                        (2 * n + alpha + beta + 2);
           double a4n =
             2 * (n + alpha) * (n + beta) * (2 * n + alpha + beta + 2);
           P2 = ((a2n + a3n * x) * P1 - a4n * P0) / a1n;
           P0 = P1;
           P1 = P2;
         }
         return P2;
       }
     }
References alpha, beta, n, p, Problem_Parameter::P0, and plotDoE::x.
jacobi() [2/2]
void oomph::Orthpoly::jacobi (const int & alpha, const int & beta, const unsigned & p, const double & x, Vector< double > & polys) inline
Calculate the Jacobi polnomials all in one goe.
     {
       // Set the constant term
       polys[0] = 1.0;
       // If we've only been asked for the constant term, bin out
       if (p == 0)
       {
         return;
       }
       // Set the linear polynomial
       polys[1] = 0.5 * (alpha - beta + (alpha + beta + 2.0) * x);
       // Initialise the terms for the recurrence relation
       double P0 = 1.0;
       double P1 = 1.0;
       double P2 = 0.5 * (alpha - beta + (alpha + beta + 2.0) * x);
       // Loop over the remaining terms
       for (unsigned n = 1; n < p; n++)
       {
         // Shift down the terms
         P0 = P1;
         P1 = P2;
         // Set the constants
         double a1n =
           2 * (n + 1) * (n + alpha + beta + 1) * (2 * n + alpha + beta);
         double a2n = (2 * n + alpha + beta + 1) * (alpha * alpha - beta * beta);
         double a3n = (2 * n + alpha + beta) * (2 * n + alpha + beta + 1) *
                      (2 * n + alpha + beta + 2);
         double a4n = 2 * (n + alpha) * (n + beta) * (2 * n + alpha + beta + 2);
         // Set the latest term
         P2 = ((a2n + a3n * x) * P1 - a4n * P0) / a1n;
         // Set the newly calculate polynomial
         polys[n + 1] = P2;
       }
     }
References alpha, beta, n, p, Problem_Parameter::P0, and plotDoE::x.
legendre()
double oomph::Orthpoly::legendre (const unsigned & p, const double & x) inline
Calculates Legendre polynomial of degree p at x using the three term recurrence relation \((n+1) P_{n+1} = (2n+1)xP_{n} - nP_{n-1} \)
     {
       // Return the constant value
       if (p == 0) return 1.0;
       // Return the linear polynomial
       else if (p == 1)
         return x;
       // Otherwise use the recurrence relation
       else
       {
         // Initialise the terms in the recurrence relation, we're going
         // to shift down before using the relation.
         double L0 = 1.0, L1 = 1.0, L2 = x;
         // Loop over the remaining polynomials
         for (unsigned n = 1; n < p; n++)
         {
           // Shift down the values
           L0 = L1;
           L1 = L2;
           // Use the three term recurrence
           L2 = ((2 * n + 1) * x * L1 - n * L0) / (n + 1);
         }
         // Once we've finished return the final value
         return L2;
       }
     }
References n, p, and plotDoE::x.
Referenced by gl_nodes(), gll_nodes(), oomph::OneDimensionalLegendreDShape< NNODE_1D >::OneDimensionalLegendreDShape(), oomph::OneDimensionalLegendreShape< NNODE_1D >::OneDimensionalLegendreShape(), oomph::OneDimensionalModalDShape::OneDimensionalModalDShape(), oomph::OneDimensionalModalShape::OneDimensionalModalShape(), oomph::OneDLegendreDShapeParam::OneDLegendreDShapeParam(), and oomph::OneDLegendreShapeParam::OneDLegendreShapeParam().
legendre_vector()
void oomph::Orthpoly::legendre_vector (const unsigned & p, const double & x, Vector< double > & polys) inline
Calculates Legendre polynomial of degree p at x using three term recursive formula. Returns all polynomials up to order p in the vector
     {
       // Set the constant term
       polys[0] = 1.0;
       // If we're only asked for the constant term return
       if (p == 0)
       {
         return;
       }
       // Set the linear polynomial
       polys[1] = x;
       // Initialise terms for the recurrence relation
       double L0 = 1.0, L1 = 1.0, L2 = x;
       // Loop over the remaining terms
       for (unsigned n = 1; n < p; n++)
       {
         // Shift down the values
         L0 = L1;
         L1 = L2;
         // Use the recurrence relation
         L2 = ((2 * n + 1) * x * L1 - n * L0) / (n + 1);
         // Set the newly calculated polynomial
         polys[n + 1] = L2;
       }
     }
References n, p, and plotDoE::x.
Variable Documentation
eps
const double oomph::Orthpoly::eps = 1.0e-15
Referenced by gl_nodes(), gll_nodes(), oomph::OneDimensionalLegendreDShape< NNODE_1D >::OneDimensionalLegendreDShape(), oomph::OneDimensionalLegendreShape< NNODE_1D >::OneDimensionalLegendreShape(), oomph::OneDLegendreDShapeParam::OneDLegendreDShapeParam(), and oomph::OneDLegendreShapeParam::OneDLegendreShapeParam().