MercuryDPM: oomph::CircularPenetrator Class Reference
oomph::CircularPenetrator Class Reference
Penetrator – here implemented as a circle.
#include <contact_elements.h>
Public Member Functions
CircularPenetrator (Vector< double > *r_c_pt, const double &r)
Constructor: Pass pointer to centre and radius.
virtual ~CircularPenetrator ()
Destructor.
void penetration (const Vector< double > &x, const Vector< double > &n, double &d, bool &intersection) const
Get penetration for given point x.
void output (std::ostream &outfile, const unsigned &nplot) const
Output coordinates of penetrator at nplot plot points.
void position_from_zeta (const Vector< double > &zeta, Vector< double > &r) const
Get position to surface, r, in terms of surface coordinate zeta.
void surface_coordinate (const Vector< double > &x, Vector< double > &zeta) const
Vector< double > rigid_body_displacement () const
Get rigid body displacement of reference point in penetrator.
void set_original_centre (const Vector< double > &orig_centre)
Public Member Functions inherited from oomph::Penetrator
Penetrator ()
Constructor.
virtual ~Penetrator ()
Destructor.
virtual Vector< std::pair< Data *, unsigned > > equilibrium_data ()
Protected Attributes
Vector< double > * Centre_pt
Vector< double > Orig_centre
double Radius
Radius of penetrator.
Detailed Description
Penetrator – here implemented as a circle.
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
Constructor & Destructor Documentation
CircularPenetrator()
oomph::CircularPenetrator::CircularPenetrator (Vector< double > * r_c_pt, const double & r) inline
Constructor: Pass pointer to centre and radius.
    {
     Centre_pt=r_c_pt;
     Radius=r;
     // Back up original centre
     unsigned n=r_c_pt->size();
     Orig_centre.resize(n);
     for (unsigned i=0;i<n;i++)
      {
       Orig_centre[i]=(*r_c_pt)[i];
      }
    }
References Centre_pt, i, n, Orig_centre, UniformPSDSelfTest::r, and Radius.
~CircularPenetrator()
virtual oomph::CircularPenetrator::~CircularPenetrator () inline virtual
Destructor.
 {}
Member Function Documentation
output()
void oomph::CircularPenetrator::output (std::ostream & outfile, const unsigned & nplot) const inline virtual
Output coordinates of penetrator at nplot plot points.
Implements oomph::Penetrator.
    {
     for (unsigned j=0;j<nplot;j++)
      {
       double phi=2.0*MathematicalConstants::Pi*double(j)/double(nplot-1);
       outfile << (*Centre_pt)[0]+Radius*cos(phi) << " "
               << (*Centre_pt)[1]+Radius*sin(phi)
               << std::endl;
      }
    }
References cos(), j, oomph::MathematicalConstants::Pi, Radius, and sin().
penetration()
void oomph::CircularPenetrator::penetration (const Vector< double > & x, const Vector< double > & n, double & d, bool & intersection) const inline virtual
Get penetration for given point x.
Implements oomph::Penetrator.
   {
    // Vector from potential contact point to centre of penetrator
    Vector<double> l(2);
    l[0]=(*Centre_pt)[0]-x[0];
    l[1]=(*Centre_pt)[1]-x[1];
    // Distance from potential contact point to centre of penetrator
    double ll=sqrt(l[0]*l[0]+l[1]*l[1]);
    // Projection of vector from potential contact point to centre of penetrator
    // onto outer unit normal on potential contact point
    double project=n[0]*l[0]+n[1]*l[1];
    double project_squared=project*project;
    // Final term in square root
    double b_squared=ll*ll-Radius*Radius;
    // Is square root negative? In this case we have no intersection
    if (project_squared<b_squared)
     {
      d = 0.0;
      intersection = false;
      //return -10*std::numeric_limits<double>::min();
     }
    else
     {
      double sqr=sqrt(project_squared-b_squared);
      d = -std::min(project-sqr,project+sqr);
      intersection = true;
     }
   }
References min, n, Radius, sqrt(), and plotDoE::x.
position_from_zeta()
void oomph::CircularPenetrator::position_from_zeta (const Vector< double > & zeta, Vector< double > & r) const inline
Get position to surface, r, in terms of surface coordinate zeta.
   {
    double phi=zeta[0];
    r[0]=(*Centre_pt)[0]+Radius*cos(phi);
    r[1]=(*Centre_pt)[1]+Radius*sin(phi);
   }
References cos(), UniformPSDSelfTest::r, Radius, sin(), and Eigen::zeta().
rigid_body_displacement()
Vector<double> oomph::CircularPenetrator::rigid_body_displacement () const inline virtual
Get rigid body displacement of reference point in penetrator.
Reimplemented from oomph::Penetrator.
    {
     unsigned n=Orig_centre.size();
     Vector<double> displ(n);
     for (unsigned i=0;i<n;i++)
      {
       displ[i]=(*Centre_pt)[i]-Orig_centre[i];
      }
     return displ;
    }
References i, n, and Orig_centre.
set_original_centre()
void oomph::CircularPenetrator::set_original_centre (const Vector< double > & orig_centre) inline
Set original centre of penetrator (for computation of rigid body displacement
   {
    Orig_centre=orig_centre;
   }
References Orig_centre.
surface_coordinate()
void oomph::CircularPenetrator::surface_coordinate (const Vector< double > & x, Vector< double > & zeta) const inline virtual
Get surface coordinate along penetrator for given point x. We assume that point on the surface and given point share the same polar angle and return that polar angle
Reimplemented from oomph::Penetrator.
   {
    zeta[0]=atan2(x[1]-(*Centre_pt)[1],x[0]-(*Centre_pt)[0]);
   }
References atan2(), Centre_pt, plotDoE::x, and Eigen::zeta().
Member Data Documentation
Centre_pt
Vector<double>* oomph::CircularPenetrator::Centre_pt protected
Pointer to centre of penetrator (origin for cylindrical polar coordinate system)
Referenced by CircularPenetrator(), surface_coordinate(), and oomph::HeatedCircularPenetrator::temperature().
Orig_centre
Vector<double> oomph::CircularPenetrator::Orig_centre protected
Original centre of penetrator (origin for cylindrical polar coordinate system)
Referenced by CircularPenetrator(), rigid_body_displacement(), and set_original_centre().
Radius
double oomph::CircularPenetrator::Radius protected
Radius of penetrator.
Referenced by CircularPenetrator(), output(), penetration(), and position_from_zeta().
The documentation for this class was generated from the following file:
contact_elements.h