MercuryDPM: BaseCoupling< M, O > Class Template Reference
BaseCoupling< M, O > Class Template Reference
#include <BaseCoupling.h>
Public Member Functions
BaseCoupling ()=default
void setName (std::string name)
std::string getName () const
void removeOldFiles () const
void writeEneTimeStep (std::ostream &os) const override
void writeEneHeader (std::ostream &os) const override
void solveOomph (int max_adapt=0)
void checkResidual ()
void solveMercury (unsigned long nt)
void setCGWidth (const double &width)
double getCGWidth ()
bool useCGMapping ()
CGFunctions::LucyXYZ getCGFunction ()
Private Attributes
bool CGMapping_ = false
CGFunctions::LucyXYZ cgFunction_
Detailed Description
template<class M, class O>
class BaseCoupling< M, O >
Common functionality for both surface- and volume-coupled problems:
defines a cg function
getParticlesInCell to find particles in a particular region
modifies the ene files to add coupled mass and energy
solveOomph and solveMercury functions to advance the two solutions in time
Author
Hongyang Cheng chyal.nosp@m.exch.nosp@m.eng@g.nosp@m.mail.nosp@m..com
Constructor & Destructor Documentation
BaseCoupling()
template<class M , class O > BaseCoupling< M, O >::BaseCoupling () default
Member Function Documentation
checkResidual()
template<class M , class O > void BaseCoupling< M, O >::checkResidual () inline
{
         oomph::DoubleVector residual;
         O::get_residuals(residual);
         double residualNorm = residual.max();
         if (residualNorm == 0) {
             logger(ERROR, "Maximum residuals %; the computation has failed and the code will exit", residualNorm);
         }
     }
References ERROR, GlobalFct::get_residuals(), logger, and oomph::DoubleVector::max().
Referenced by BaseCoupling< M, O >::solveOomph().
getCGFunction()
template<class M , class O > CGFunctions::LucyXYZ BaseCoupling< M, O >::getCGFunction () inline
     { return cgFunction_; }
References BaseCoupling< M, O >::cgFunction_.
Referenced by VolumeCoupling::getProjectionMatrix().
getCGWidth()
template<class M , class O > double BaseCoupling< M, O >::getCGWidth () inline
get the dimensionalized CG width to be used in MercuryProblem
     {
         return cgFunction_.getWidth();
     }
References BaseCoupling< M, O >::cgFunction_, and CGFunctions::Polynomial< Coordinates >::getWidth().
Referenced by VolumeCoupling::checkParticlesInFiniteElems(), and SCoupling< M, O >::getElementBoundingBox().
getName()
template<class M , class O > std::string BaseCoupling< M, O >::getName () const inline
{
         return M::getName();
     }
References getName().
Referenced by ScaleCoupledBeam::actionsBeforeSolve(), CoupledBeam::actionsBeforeSolve(), CoupledProblem::CoupledProblem(), and CoupledProblem::getSolidDeflection().
removeOldFiles()
template<class M , class O > void BaseCoupling< M, O >::removeOldFiles () const inline
{
         M::removeOldFiles();
         O::removeOldFiles();
     }
Referenced by CoupledBeam::CoupledBeam(), CoupledProblem::CoupledProblem(), ElementAnalysis::ElementAnalysis(), and ScaleCoupledBeam::ScaleCoupledBeam().
setCGWidth()
template<class M , class O > void BaseCoupling< M, O >::setCGWidth (const double & width) inline
     {
         if (width == 0)
         {
             CGMapping_ = false;
         }
         else
         {
             CGMapping_ = true;
             // note CG function needs to be nondimensionalized
             // fixme CG width is not set with respect to particle radius. Should we do that?
             cgFunction_.setWidth(width);
         }
     }
References BaseCoupling< M, O >::cgFunction_, BaseCoupling< M, O >::CGMapping_, and CGFunctions::Polynomial< Coordinates >::setWidth().
Referenced by VolumeCoupling::solveVolumeCoupling().
setName()
template<class M , class O > void BaseCoupling< M, O >::setName (std::string name) inline
{
         M::setName(name);
         O::setName(name);
     }
References plotDoE::name.
Referenced by CoupledBeam::CoupledBeam(), CoupledProblem::CoupledProblem(), ElementAnalysis::ElementAnalysis(), and ScaleCoupledBeam::ScaleCoupledBeam().
solveMercury()
template<class M , class O > void BaseCoupling< M, O >::solveMercury (unsigned long nt) inline
solve a given number of time steps nt in Mercury
     {
         for (int n = 0; n < nt; ++n)
         {
             M::computeOneTimeStep();
         }
     }
References n.
Referenced by SCoupling< M, O >::computeOneTimeStepForSCoupling(), and VolumeCoupling::computeOneTimeStepForVCoupling().
solveOomph()
template<class M , class O > void BaseCoupling< M, O >::solveOomph (int max_adapt = 0) inline
used in OomphMercuryCoupling::computeOneTimeStepForV/SCoupling to do a oomph timestep (V/SCoupling)
     {
         O::actionsBeforeOomphTimeStep();
         // the coupled codes seem to not work if newton_solve is used
         //this->newton_solve(this->time_pt()->dt());
         if(max_adapt <= 0)
         {
             this->unsteady_newton_solve(this->time_pt()->dt());
         }
         else
         {
             this->unsteady_newton_solve(this->time_pt()->dt(), max_adapt, false);
         }
         checkResidual();
     }
References BaseCoupling< M, O >::checkResidual().
Referenced by SCoupling< M, O >::computeOneTimeStepForSCoupling(), and VolumeCoupling::computeOneTimeStepForVCoupling().
useCGMapping()
template<class M , class O > bool BaseCoupling< M, O >::useCGMapping () inline
     { return CGMapping_; }
References BaseCoupling< M, O >::CGMapping_.
Referenced by VolumeCoupling::checkParticlesInFiniteElems(), VolumeCoupling::computeCouplingForce(), VolumeCoupling::computeCouplingOnDPM(), VolumeCoupling::computeCouplingOnFEM(), VolumeCoupling::getInvCoupledMassPerTime(), VolumeCoupling::getProjectionAndProjected(), and VolumeCoupling::getProjectionMatrix().
writeEneHeader()
template<class M , class O > void BaseCoupling< M, O >::writeEneHeader (std::ostream & os) const inline override
override writeEneHeader in DPMBase class for the coupling
     {
         //only write if we don't restart
         if (M::getAppend()) {
             return;
         }
         long width = os.precision() + 6;
         os << std::setw(width)
            << "time " << std::setw(width)
            << "mass " << std::setw(width)
            << "momentum_X " << std::setw(width)
            << "momentum_Y " << std::setw(width)
            << "momentum_Z " << std::setw(width)
            << "angMomentum_X " << std::setw(width)
            << "angMomentum_Y " << std::setw(width)
            << "angMomentum_Z " << std::setw(width)
            << "gravitEnergy " << std::setw(width) //gravitational potential energy
            << "traKineticEnergy " << std::setw(width) //translational kinetic energy
            << "rotKineticEnergy " << std::setw(width) //rotational kE
            << "elasticEnergy " << std::setw(width)
            << "centerOfMassX " << std::setw(width)
            << "centerOfMassY " << std::setw(width)
            << "centerOfMassZ\n";
     }
Referenced by BaseCoupling< M, O >::writeEneTimeStep().
writeEneTimeStep()
template<class M , class O > void BaseCoupling< M, O >::writeEneTimeStep (std::ostream & os) const inline override
override writeEneTimeStep because mass and elastic energy are computed different for the coupling; also adds momentum and angular momentum
     {
         if (M::eneFile.getCounter() == 1 || M::eneFile.getFileType() == FileType::MULTIPLE_FILES ||
                 M::eneFile.getFileType() == FileType::MULTIPLE_FILES_PADDED)
         {
             writeEneHeader(os);
         }
         const Mdouble m = M::particleHandler.getMass();
         const Vec3D com = M::particleHandler.getMassTimesPosition();
         //Ensure the numbers fit into a constant width column: for this we need the precision given by the operating system,
         //plus a few extra characters for characters like a minus and scientific notation.
         const static long int width = os.precision() + 6;
         os << std::setw(width) << M::getTime()
 //           << " " << std::setw(width) << getCoupledMass()
            << " " << std::setw(width) << M::particleHandler.getMomentum().getX()
            << " " << std::setw(width) << M::particleHandler.getMomentum().getY()
            << " " << std::setw(width) << M::particleHandler.getMomentum().getZ()
            << " " << std::setw(width) << M::particleHandler.getAngularMomentum().getX()
            << " " << std::setw(width) << M::particleHandler.getAngularMomentum().getY()
            << " " << std::setw(width) << M::particleHandler.getAngularMomentum().getZ()
            << " " << std::setw(width) << -Vec3D::dot(M::getGravity(), com)
            << " " << std::setw(width) << M::particleHandler.getKineticEnergy()
            << " " << std::setw(width) << M::particleHandler.getRotationalEnergy()
            //<< " " << std::setw(width) << M::getElasticEnergyCoupled()
            // we need to write x, y and z coordinates separately, otherwise the width of the columns is incorrect
            << " " << std::setw(width)
            << ( m == 0 ? constants::NaN : com.X / m ) //set to nan because 0/0 implementation in gcc and clang differs
            << " " << std::setw(width) << ( m == 0 ? constants::NaN : com.Y / m )
            << " " << std::setw(width) << ( m == 0 ? constants::NaN : com.Z / m )
            << std::endl;
     }
References Vec3D::dot(), Vec3D::getX(), m, MULTIPLE_FILES, MULTIPLE_FILES_PADDED, constants::NaN, BaseCoupling< M, O >::writeEneHeader(), Vec3D::X, Vec3D::Y, and Vec3D::Z.
Member Data Documentation
cgFunction_
template<class M , class O > CGFunctions::LucyXYZ BaseCoupling< M, O >::cgFunction_ private
Referenced by BaseCoupling< M, O >::getCGFunction(), BaseCoupling< M, O >::getCGWidth(), and BaseCoupling< M, O >::setCGWidth().
CGMapping_
template<class M , class O > bool BaseCoupling< M, O >::CGMapping_ = false private
Referenced by BaseCoupling< M, O >::setCGWidth(), and BaseCoupling< M, O >::useCGMapping().
The documentation for this class was generated from the following file:
BaseCoupling.h