MercuryDPM: oomph::LinearisedNavierStokesEquations Class Reference
oomph::LinearisedNavierStokesEquations Class Reference abstract
#include <linearised_navier_stokes_elements.h>
Public Member Functions
LinearisedNavierStokesEquations ()
const double & re () const
Reynolds number.
const double & re_st () const
Product of Reynolds and Strouhal number (=Womersley number)
const double & lambda () const
const double & omega () const
double *& re_pt ()
Pointer to Reynolds number.
double *& re_st_pt ()
Pointer to product of Reynolds and Strouhal number (=Womersley number)
double *& lambda_pt ()
Pointer to lambda.
double *& omega_pt ()
Pointer to frequency.
LinearisedNavierStokesEigenfunctionNormalisationElement * normalisation_element_pt ()
Pointer to normalisation element.
void set_eigenfunction_normalisation_element (LinearisedNavierStokesEigenfunctionNormalisationElement *const &normalisation_el_pt)
the boolean flag check_nodal_data is set to false.
const double & viscosity_ratio () const
double *& viscosity_ratio_pt ()
Pointer to the viscosity ratio.
const double & density_ratio () const
double *& density_ratio_pt ()
Pointer to the density ratio.
virtual unsigned npres_linearised_nst () const =0
virtual unsigned u_index_linearised_nst (const unsigned &i) const
double du_dt_linearised_nst (const unsigned &n, const unsigned &i) const
void disable_ALE ()
void enable_ALE ()
virtual double p_linearised_nst (const unsigned &n_p, const unsigned &i) const =0
virtual void pin_real_or_imag (const unsigned &real)=0
virtual void unpin_real_or_imag (const unsigned &real)=0
virtual void pin_pressure_normalisation_dofs ()=0
Pin the normalisation dofs.
virtual int p_index_linearised_nst (const unsigned &i) const
Which nodal value represents the pressure?
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate, const unsigned &real) const
void output (std::ostream &outfile)
void output (std::ostream &outfile, const unsigned &nplot)
void output (FILE *file_pt)
void output (FILE *file_pt, const unsigned &nplot)
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element's residual Vector.
double interpolated_u_linearised_nst (const Vector< double > &s, const unsigned &i) const
double interpolated_p_linearised_nst (const Vector< double > &s, const unsigned &i) const
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual unsigned nvertex_node () const
virtual Node * vertex_node_pt (const unsigned &j) const
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output an exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output a time-dependent exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Attributes
void(*&)(const double &time, const Vector< double > &x, Vector< double > &f) base_flow_u_fct_pt ()
Access function for the base flow solution pointer.
void(*&)(const double &time, const Vector< double > &x, DenseMatrix< double > &f) base_flow_dudx_fct_pt ()
Static Public Attributes
static Vector< double > Gamma
Vector to decide whether the stress-divergence form is used or not.
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Protected Member Functions
virtual int p_local_eqn (const unsigned &n, const unsigned &i)=0
virtual double dshape_and_dtest_eulerian_linearised_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
virtual double dshape_and_dtest_eulerian_at_knot_linearised_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
virtual void pshape_linearised_nst (const Vector< double > &s, Shape &psi) const =0
Compute the pressure shape functions at local coordinate s.
virtual void pshape_linearised_nst (const Vector< double > &s, Shape &psi, Shape &test) const =0
Compute the pressure shape and test functions at local coordinate s.
virtual void get_base_flow_u (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &result) const
virtual void get_base_flow_dudx (const double &time, const unsigned &ipt, const Vector< double > &x, DenseMatrix< double > &result) const
int eigenvalue_local_eqn (const unsigned &i)
virtual void fill_in_generic_residual_contribution_linearised_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Attributes
double * Viscosity_Ratio_pt
double * Density_Ratio_pt
double * Re_pt
Pointer to global Reynolds number.
double * ReSt_pt
Pointer to global Reynolds number x Strouhal number (=Womersley)
double * Lambda_pt
Pointer to eigenvalue.
double * Omega_pt
Pointer to frequency.
LinearisedNavierStokesEigenfunctionNormalisationElement * Normalisation_element_pt
Pointer to the normalisation element.
unsigned Data_number_of_eigenvalue
Index of datum where eigenvalue is stored.
unsigned Index_of_eigenvalue
void(* Base_flow_u_fct_pt)(const double &time, const Vector< double > &x, Vector< double > &result)
Pointer to base flow solution (velocity components) function.
void(* Base_flow_dudx_fct_pt)(const double &time, const Vector< double > &x, DenseMatrix< double > &result)
bool ALE_is_disabled
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Static Private Attributes
static int Pressure_not_stored_at_node = -100
static double Default_Physical_Constant_Value = 0.0
static double Default_Physical_Ratio_Value = 1.0
Static default value for the physical ratios (all initialised to one)
Additional Inherited Members
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
A class for elements that solve the linearised version of the unsteady Navier–Stokes equations in cylindrical polar coordinates, where we have Fourier-decomposed in the azimuthal direction so that the theta-dependance is replaced by an azimuthal mode number.
Constructor & Destructor Documentation
LinearisedNavierStokesEquations()
oomph::LinearisedNavierStokesEquations::LinearisedNavierStokesEquations () inline
Constructor: NULL the base flow solution and the derivatives of the base flow function
       : Base_flow_u_fct_pt(0), Base_flow_dudx_fct_pt(0), ALE_is_disabled(false)
     {
       // Set all the physical parameter pointers to the default value of zero
       Re_pt = &Default_Physical_Constant_Value;
       ReSt_pt = &Default_Physical_Constant_Value;
       Lambda_pt = &Default_Physical_Constant_Value;
       Omega_pt = &Default_Physical_Constant_Value;
       // Set to sensible defaults
       Data_number_of_eigenvalue = 0;
       Index_of_eigenvalue = 0;
       // Set the physical ratios to the default value of one
       Viscosity_Ratio_pt = &Default_Physical_Ratio_Value;
       Density_Ratio_pt = &Default_Physical_Ratio_Value;
       // Null out normalisation
       Normalisation_element_pt = 0;
     }
References Data_number_of_eigenvalue, Default_Physical_Constant_Value, Default_Physical_Ratio_Value, Density_Ratio_pt, Index_of_eigenvalue, Lambda_pt, Normalisation_element_pt, Omega_pt, Re_pt, ReSt_pt, and Viscosity_Ratio_pt.
Member Function Documentation
density_ratio()
const double& oomph::LinearisedNavierStokesEquations::density_ratio () const inline
Density ratio for element: element's density relative to the viscosity used in the definition of the Reynolds number
     {
       return *Density_Ratio_pt;
     }
References Density_Ratio_pt.
Referenced by fill_in_generic_residual_contribution_linearised_nst(), and oomph::RefineableLinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst().
density_ratio_pt()
double*& oomph::LinearisedNavierStokesEquations::density_ratio_pt () inline
Pointer to the density ratio.
     {
       return Density_Ratio_pt;
     }
References Density_Ratio_pt.
Referenced by oomph::RefineableLinearisedNavierStokesEquations::further_build().
disable_ALE()
void oomph::LinearisedNavierStokesEquations::disable_ALE () inline virtual
Disable ALE, i.e. assert the mesh is not moving – you do this at your own risk!
Reimplemented from oomph::FiniteElement.
     {
       ALE_is_disabled = true;
     }
References ALE_is_disabled.
dshape_and_dtest_eulerian_at_knot_linearised_nst()
virtual double oomph::LinearisedNavierStokesEquations::dshape_and_dtest_eulerian_at_knot_linearised_nst (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const protected pure virtual
Compute the shape functions and their derivatives w.r.t. global coordinates at the ipt-th integration point. Return Jacobian of mapping between local and global coordinates.
Implemented in oomph::LinearisedQTaylorHoodElement, and oomph::LinearisedQCrouzeixRaviartElement.
Referenced by fill_in_generic_residual_contribution_linearised_nst(), and oomph::RefineableLinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst().
dshape_and_dtest_eulerian_linearised_nst()
virtual double oomph::LinearisedNavierStokesEquations::dshape_and_dtest_eulerian_linearised_nst (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const protected pure virtual
Compute the shape functions and their derivatives w.r.t. global coordinates at local coordinate s. Return Jacobian of mapping between local and global coordinates.
Implemented in oomph::LinearisedQTaylorHoodElement, and oomph::LinearisedQCrouzeixRaviartElement.
du_dt_linearised_nst()
double oomph::LinearisedNavierStokesEquations::du_dt_linearised_nst (const unsigned & n, const unsigned & i) const inline
Return the i-th component of du/dt at local node n. Uses suitably interpolated value for hanging nodes.
     {
       // Get the data's timestepper
       TimeStepper* time_stepper_pt = this->node_pt(n)->time_stepper_pt();
       // Initialise dudt
       double dudt = 0.0;
       // Loop over the timesteps, if there is a non-steady timestepper
       if (!time_stepper_pt->is_steady())
       {
         // Get the index at which the velocity is stored
         const unsigned u_nodal_index = u_index_linearised_nst(i);
         // Determine number of timsteps (past & present)
         const unsigned n_time = time_stepper_pt->ntstorage();
         // Add the contributions to the time derivative
         for (unsigned t = 0; t < n_time; t++)
         {
           dudt +=
             time_stepper_pt->weight(1, t) * nodal_value(t, n, u_nodal_index);
         }
       }
       return dudt;
     }
References i, oomph::TimeStepper::is_steady(), n, oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), plotPSD::t, oomph::GeomObject::time_stepper_pt(), oomph::Data::time_stepper_pt(), u_index_linearised_nst(), and oomph::TimeStepper::weight().
eigenvalue_local_eqn()
int oomph::LinearisedNavierStokesEquations::eigenvalue_local_eqn (const unsigned & i) inline protected
     {
       return this->external_local_eqn(this->Data_number_of_eigenvalue,
                                       this->Index_of_eigenvalue + i);
     }
References oomph::GeneralisedElement::external_local_eqn(), and i.
Referenced by fill_in_generic_residual_contribution_linearised_nst(), and oomph::RefineableLinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst().
enable_ALE()
void oomph::LinearisedNavierStokesEquations::enable_ALE () inline virtual
(Re-)enable ALE, i.e. take possible mesh motion into account when evaluating the time-derivative. Note: By default, ALE is enabled, at the expense of possibly creating unnecessary work in problems where the mesh is, in fact, stationary.
Reimplemented from oomph::FiniteElement.
     {
       ALE_is_disabled = false;
     }
References ALE_is_disabled.
fill_in_contribution_to_residuals()
void oomph::LinearisedNavierStokesEquations::fill_in_contribution_to_residuals (Vector< double > & residuals) inline virtual
Compute the element's residual Vector.
Reimplemented from oomph::GeneralisedElement.
     {
       // Call the generic residuals function with flag set to 0
       // and using a dummy matrix argument
       fill_in_generic_residual_contribution_linearised_nst(
         residuals,
         GeneralisedElement::Dummy_matrix,
         GeneralisedElement::Dummy_matrix,
         0);
     }
References oomph::GeneralisedElement::Dummy_matrix, and fill_in_generic_residual_contribution_linearised_nst().
fill_in_generic_residual_contribution_linearised_nst()
void oomph::LinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, unsigned flag) protected virtual
Compute the residuals for the Navier-Stokes equations; flag=1(or 0): do (or don't) compute the Jacobian as well.
Compute the residuals for the linearised axisymmetric Navier–Stokes equations; flag=1(or 0): do (or don't) compute the Jacobian as well.
Reimplemented in oomph::RefineableLinearisedNavierStokesEquations.
   {
     // Get the time from the first node in the element
     const double time = this->node_pt(0)->time_stepper_pt()->time();
     // Determine number of nodes in the element
     const unsigned n_node = nnode();
     // Determine how many pressure values there are associated with
     // a single pressure component
     const unsigned n_pres = npres_linearised_nst();
     const unsigned n_veloc = 4 * DIM;
     // Get the nodal indices at which the velocity is stored
     unsigned u_nodal_index[n_veloc];
     for (unsigned i = 0; i < n_veloc; ++i)
     {
       u_nodal_index[i] = u_index_linearised_nst(i);
     }
     // Set up memory for the fluid shape and test functions
     Shape psif(n_node), testf(n_node);
     DShape dpsifdx(n_node, DIM), dtestfdx(n_node, DIM);
     // Set up memory for the pressure shape and test functions
     Shape psip(n_pres), testp(n_pres);
     // Determine number of integration points
     const unsigned n_intpt = integral_pt()->nweight();
     // Set up memory for the vector to hold local coordinates (two dimensions)
     Vector<double> s(DIM);
     // Get physical variables from the element
     // (Reynolds number must be multiplied by the density ratio)
     const double scaled_re = re() * density_ratio();
     const double scaled_re_st = re_st() * density_ratio();
     const double visc_ratio = viscosity_ratio();
     const double eval_real = lambda();
     const double eval_imag = omega();
     const std::complex<double> eigenvalue(eval_real, eval_imag);
     // Integers used to store the local equation and unknown numbers
     int local_eqn = 0;
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Assign values of the local coordinates s
       for (unsigned i = 0; i < DIM; i++)
       {
         s[i] = integral_pt()->knot(ipt, i);
       }
       // Get the integral weight
       const double w = integral_pt()->weight(ipt);
       // Calculate the fluid shape and test functions, and their derivatives
       // w.r.t. the global coordinates
       const double J = dshape_and_dtest_eulerian_at_knot_linearised_nst(
         ipt, psif, dpsifdx, testf, dtestfdx);
       // Calculate the pressure shape and test functions
       pshape_linearised_nst(s, psip, testp);
       // Premultiply the weights and the Jacobian of the mapping between
       // local and global coordinates
       const double W = w * J;
       // Allocate storage for the position and the derivative of the
       // mesh positions w.r.t. time
       Vector<double> interpolated_x(DIM, 0.0);
       // Vector<double> mesh_velocity(2,0.0);
       // Allocate storage for the velocity components (six of these)
       // and their derivatives w.r.t. time
       Vector<std::complex<double>> interpolated_u(DIM);
       // Vector<double> dudt(6,0.0);
       // Allocate storage for the eigen function normalisation
       Vector<std::complex<double>> interpolated_u_normalisation(DIM);
       for (unsigned i = 0; i < DIM; ++i)
       {
         interpolated_u[i].real(0.0);
         interpolated_u[i].imag(0.0);
         interpolated_u_normalisation[i].real(0.0);
         interpolated_u_normalisation[i].imag(0.0);
       }
       // Allocate storage for the pressure components (two of these
       std::complex<double> interpolated_p(0.0, 0.0);
       std::complex<double> interpolated_p_normalisation(0.0, 0.0);
       // Allocate storage for the derivatives of the velocity components
       // w.r.t. global coordinates (r and z)
       Vector<Vector<std::complex<double>>> interpolated_dudx(DIM);
       for (unsigned i = 0; i < DIM; ++i)
       {
         interpolated_dudx[i].resize(DIM);
         for (unsigned j = 0; j < DIM; ++j)
         {
           interpolated_dudx[i][j].real(0.0);
           interpolated_dudx[i][j].imag(0.0);
         }
       }
       // Calculate pressure at the integration point
       // -------------------------------------------
       // Loop over pressure degrees of freedom (associated with a single
       // pressure component) in the element
       for (unsigned l = 0; l < n_pres; l++)
       {
         // Cache the shape function
         const double psip_ = psip(l);
         // Get the complex nodal pressure values
         const std::complex<double> p_value(this->p_linearised_nst(l, 0),
                                            this->p_linearised_nst(l, 1));
         // Add contribution
         interpolated_p += p_value * psip_;
         // Repeat for normalisation
         const std::complex<double> p_norm_value(this->p_linearised_nst(l, 2),
                                                 this->p_linearised_nst(l, 3));
         interpolated_p_normalisation += p_norm_value * psip_;
       }
       // End of loop over the pressure degrees of freedom in the element
       // Calculate velocities and their derivatives at the integration point
       // -------------------------------------------------------------------
       // Loop over the element's nodes
       for (unsigned l = 0; l < n_node; l++)
       {
         // Cache the shape function
         const double psif_ = psif(l);
         // Loop over the DIM coordinate directions
         for (unsigned i = 0; i < DIM; i++)
         {
           interpolated_x[i] += this->raw_nodal_position(l, i) * psif_;
         }
         // Loop over the DIM complex velocity components
         for (unsigned i = 0; i < DIM; i++)
         {
           // Get the value
           const std::complex<double> u_value(
             this->raw_nodal_value(l, u_nodal_index[2 * i + 0]),
             this->raw_nodal_value(l, u_nodal_index[2 * i + 1]));
           // Add contribution
           interpolated_u[i] += u_value * psif_;
           // Add contribution to dudt
           // dudt[i] += du_dt_linearised_nst(l,i)*psif_;
           // Loop over two coordinate directions (for derivatives)
           for (unsigned j = 0; j < DIM; j++)
           {
             interpolated_dudx[i][j] += u_value * dpsifdx(l, j);
           }
           // Interpolate the normalisation function
           const std::complex<double> normalisation_value(
             this->raw_nodal_value(l, u_nodal_index[2 * (DIM + i)]),
             this->raw_nodal_value(l, u_nodal_index[2 * (DIM + i) + 1]));
           interpolated_u_normalisation[i] += normalisation_value * psif_;
         }
       } // End of loop over the element's nodes
       // Get the mesh velocity if ALE is enabled
       /*if(!ALE_is_disabled)
        {
         // Loop over the element's nodes
         for(unsigned l=0;l<n_node;l++)
          {
           // Loop over the two coordinate directions
           for(unsigned i=0;i<2;i++)
            {
             mesh_velocity[i] += this->raw_dnodal_position_dt(l,i)*psif(l);
            }
          }
          }*/
       // Get velocities and their derivatives from base flow problem
       // -----------------------------------------------------------
       // Allocate storage for the velocity components of the base state
       // solution (initialise to zero)
       Vector<double> base_flow_u(DIM, 0.0);
       // Get the user-defined base state solution velocity components
       get_base_flow_u(time, ipt, interpolated_x, base_flow_u);
       // Allocate storage for the derivatives of the base state solution's
       // velocity components w.r.t. global coordinate (r and z)
       // N.B. the derivatives of the base flow components w.r.t. the
       // azimuthal coordinate direction (theta) are always zero since the
       // base flow is axisymmetric
       DenseMatrix<double> base_flow_dudx(DIM, DIM, 0.0);
       // Get the derivatives of the user-defined base state solution
       // velocity components w.r.t. global coordinates
       get_base_flow_dudx(time, ipt, interpolated_x, base_flow_dudx);
       // MOMENTUM EQUATIONS
       //------------------
       // Loop over the test functions
       for (unsigned l = 0; l < n_node; l++)
       {
         // Loop over the velocity components
         for (unsigned i = 0; i < DIM; i++)
         {
           // Assemble the residuals
           // Time dependent term
           std::complex<double> residual_contribution =
             -scaled_re_st * eigenvalue * interpolated_u[i] * testf[l] * W;
           // Pressure term
           residual_contribution += interpolated_p * dtestfdx(l, i) * W;
           // Viscous terms
           for (unsigned k = 0; k < DIM; ++k)
           {
             residual_contribution -=
               visc_ratio *
               (interpolated_dudx[i][k] + Gamma[i] * interpolated_dudx[k][i]) *
               dtestfdx(l, k) * W;
           }
           // Advective terms
           for (unsigned k = 0; k < DIM; ++k)
           {
             residual_contribution -=
               scaled_re *
               (base_flow_u[k] * interpolated_dudx[i][k] +
                interpolated_u[k] * base_flow_dudx(i, k)) *
               testf[l] * W;
           }
           // Now separate real and imaginary parts
           /*IF it's not a boundary condition*/
           // Here assume that we're only going to pin entire complex
           // number or not
           local_eqn = nodal_local_eqn(l, u_nodal_index[2 * i]);
           if (local_eqn >= 0)
           {
             residuals[local_eqn] += residual_contribution.real();
           }
           local_eqn = nodal_local_eqn(l, u_nodal_index[2 * i + 1]);
           if (local_eqn >= 0)
           {
             residuals[local_eqn] += residual_contribution.imag();
           }
           // CALCULATE THE JACOBIAN
           /*if(flag)
             {
             //Loop over the velocity shape functions again
             for(unsigned l2=0;l2<n_node;l2++)
             {
             //Loop over the velocity components again
             for(unsigned i2=0;i2<DIM;i2++)
             {
             //If at a non-zero degree of freedom add in the entry
             local_unknown = nodal_local_eqn(l2,u_nodal_index[i2]);
             if(local_unknown >= 0)
             {
             //Add contribution to Elemental Matrix
             jacobian(local_eqn,local_unknown)
             -= visc_ratio*Gamma[i]*dpsifdx(l2,i)*dtestfdx(l,i2)*W;
             //Extra component if i2 = i
             if(i2 == i)
             {
             //Loop over velocity components
             for(unsigned k=0;k<DIM;k++)
             {
             jacobian(local_eqn,local_unknown)
             -= visc_ratio*dpsifdx(l2,k)*dtestfdx(l,k)*W;
             }
             }
             //Now add in the inertial terms
             jacobian(local_eqn,local_unknown)
             -= scaled_re*psif[l2]*interpolated_dudx(i,i2)*testf[l]*W;
             //Extra component if i2=i
             if(i2 == i)
             {
             //Add the mass matrix term (only diagonal entries)
             //Note that this is positive because the mass matrix
             //is taken to the other side of the equation when
             //formulating the generalised eigenproblem.
             if(flag==2)
             {
             mass_matrix(local_eqn,local_unknown) +=
             scaled_re_st*psif[l2]*testf[l]*W;
             }
             //du/dt term
             jacobian(local_eqn,local_unknown)
             -= scaled_re_st*
             node_pt(l2)->time_stepper_pt()->weight(1,0)*
             psif[l2]*testf[l]*W;
             //Loop over the velocity components
             for(unsigned k=0;k<DIM;k++)
             {
             double tmp=scaled_re*interpolated_u[k];
             if (!ALE_is_disabled) tmp-=scaled_re_st*mesh_velocity[k];
             jacobian(local_eqn,local_unknown) -=
             tmp*dpsifdx(l2,k)*testf[l]*W;
             }
             }
             }
             }
             }
             //Now loop over pressure shape functions
             //This is the contribution from pressure gradient
             for(unsigned l2=0;l2<n_pres;l2++)
             {
             //If we are at a non-zero degree of freedom in the entry
             local_unknown = p_local_eqn(l2);
             if(local_unknown >= 0)
             {
             jacobian(local_eqn,local_unknown)
             += psip[l2]*dtestfdx(l,i)*W;
             }
             }
             } //End of Jacobian calculation
             }*/ //End of if not boundary condition statement
         } // End of loop over dimension
       } // End of loop over shape functions
       // CONTINUITY EQUATION
       //-------------------
       // Loop over the shape functions
       for (unsigned l = 0; l < n_pres; l++)
       {
         // Assemble the residuals
         std::complex<double> residual_contribution = interpolated_dudx[0][0];
         for (unsigned k = 1; k < DIM; ++k)
         {
           residual_contribution += interpolated_dudx[k][k];
         }
         local_eqn = p_local_eqn(l, 0);
         // If not a boundary conditions
         if (local_eqn >= 0)
         {
           residuals[local_eqn] += residual_contribution.real() * testp[l] * W;
         }
         local_eqn = p_local_eqn(l, 1);
         // If not a boundary conditions
         if (local_eqn >= 0)
         {
           residuals[local_eqn] += residual_contribution.imag() * testp[l] * W;
         }
       } // End of loop over l
       // Normalisation condition
       std::complex<double> residual_contribution =
         interpolated_p_normalisation * interpolated_p;
       for (unsigned k = 0; k < DIM; ++k)
       {
         residual_contribution +=
           interpolated_u_normalisation[k] * interpolated_u[k];
       }
       local_eqn = this->eigenvalue_local_eqn(0);
       if (local_eqn >= 0)
       {
         residuals[local_eqn] += residual_contribution.real() * W;
       }
       local_eqn = this->eigenvalue_local_eqn(1);
       if (local_eqn >= 0)
       {
         residuals[local_eqn] += residual_contribution.imag() * W;
       }
     } // End of loop over the integration points
   } // End of fill_in_generic_residual_contribution_linearised_nst
References density_ratio(), DIM, dshape_and_dtest_eulerian_at_knot_linearised_nst(), eigenvalue_local_eqn(), Gamma, get_base_flow_dudx(), get_base_flow_u(), i, oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), J, j, k, oomph::Integral::knot(), lambda(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), npres_linearised_nst(), oomph::Integral::nweight(), omega(), p_linearised_nst(), p_local_eqn(), pshape_linearised_nst(), oomph::FiniteElement::raw_nodal_position(), oomph::FiniteElement::raw_nodal_value(), re(), re_st(), s, oomph::TimeStepper::time(), oomph::Data::time_stepper_pt(), u_index_linearised_nst(), viscosity_ratio(), w, oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by fill_in_contribution_to_residuals().
get_base_flow_dudx()
virtual void oomph::LinearisedNavierStokesEquations::get_base_flow_dudx (const double & time, const unsigned & ipt, const Vector< double > & x, DenseMatrix< double > & result) const inline protected virtual
Calculate the derivatives of the velocity components of the base flow solution w.r.t. global coordinates (r and z) at a given time and Eulerian position
Reimplemented in RefineableLinearisedQCrouzeixRaviartMultiDomainElement, RefineableLinearisedQTaylorHoodMultiDomainElement, LinearisedQCrouzeixRaviartMultiDomainElement, and LinearisedQTaylorHoodMultiDomainElement.
     {
       // If the function pointer is zero return zero
       if (Base_flow_dudx_fct_pt == 0)
       {
         // Loop over velocity components
         for (unsigned i = 0; i < DIM; i++)
         {
           // Loop over coordinate directions and set to zero
           for (unsigned j = 0; j < DIM; j++)
           {
             result(i, j) = 0.0;
           }
         }
       }
       // Otherwise call the function
       else
       {
         (*Base_flow_dudx_fct_pt)(time, x, result);
       }
     }
References Base_flow_dudx_fct_pt, DIM, i, j, and plotDoE::x.
Referenced by fill_in_generic_residual_contribution_linearised_nst(), and oomph::RefineableLinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst().
get_base_flow_u()
virtual void oomph::LinearisedNavierStokesEquations::get_base_flow_u (const double & time, const unsigned & ipt, const Vector< double > & x, Vector< double > & result) const inline protected virtual
Calculate the velocity components of the base flow solution at a given time and Eulerian position
Reimplemented in RefineableLinearisedQCrouzeixRaviartMultiDomainElement, RefineableLinearisedQTaylorHoodMultiDomainElement, LinearisedQCrouzeixRaviartMultiDomainElement, and LinearisedQTaylorHoodMultiDomainElement.
     {
       // If the function pointer is zero return zero
       if (Base_flow_u_fct_pt == 0)
       {
         // Loop over velocity components and set base flow solution to zero
         for (unsigned i = 0; i < DIM; i++)
         {
           result[i] = 0.0;
         }
       }
       // Otherwise call the function
       else
       {
         (*Base_flow_u_fct_pt)(time, x, result);
       }
     }
References Base_flow_u_fct_pt, DIM, i, and plotDoE::x.
Referenced by fill_in_generic_residual_contribution_linearised_nst(), and oomph::RefineableLinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst().
interpolated_p_linearised_nst()
double oomph::LinearisedNavierStokesEquations::interpolated_p_linearised_nst (const Vector< double > & s, const unsigned & i) const inline
Return the i-th component of the FE interpolated pressure p[i] at local coordinate s
     {
       // Determine number of pressure nodes in the element
       const unsigned n_pressure_nodes = npres_linearised_nst();
       // Provide storage for local shape functions
       Shape psi(n_pressure_nodes);
       // Find values of shape functions
       pshape_linearised_nst(s, psi);
       // Initialise value of p
       double interpolated_p = 0.0;
       // Loop over the local nodes and sum
       for (unsigned l = 0; l < n_pressure_nodes; l++)
       {
         // N.B. The pure virtual function p_linearised_nst(...)
         // automatically calculates the index at which the pressure value
         // is stored, so we don't need to worry about this here
         interpolated_p += p_linearised_nst(l, i) * psi[l];
       }
       return (interpolated_p);
     }
References i, npres_linearised_nst(), p_linearised_nst(), pshape_linearised_nst(), and s.
Referenced by oomph::RefineableLinearisedQCrouzeixRaviartElement::further_build(), oomph::RefineableLinearisedQTaylorHoodElement::get_interpolated_values(), and output().
interpolated_u_linearised_nst()
double oomph::LinearisedNavierStokesEquations::interpolated_u_linearised_nst (const Vector< double > & s, const unsigned & i) const inline
Compute the element's residual Vector and the jacobian matrix. Virtual function can be overloaded by hanging-node version. Add the element's contribution to its residuals vector, jacobian matrix and mass matrix Return the i-th component of the FE interpolated velocity u[i] at local coordinate s
     {
       // Determine number of nodes in the element
       const unsigned n_node = nnode();
       // Provide storage for local shape functions
       Shape psi(n_node);
       // Find values of shape functions
       shape(s, psi);
       // Get the index at which the velocity is stored
       const unsigned u_nodal_index = u_index_linearised_nst(i);
       // Initialise value of u
       double interpolated_u = 0.0;
       // Loop over the local nodes and sum
       for (unsigned l = 0; l < n_node; l++)
       {
         interpolated_u += nodal_value(l, u_nodal_index) * psi[l];
       }
       return (interpolated_u);
     }
References i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), and u_index_linearised_nst().
Referenced by oomph::RefineableLinearisedQCrouzeixRaviartElement::get_interpolated_values(), oomph::RefineableLinearisedQTaylorHoodElement::get_interpolated_values(), and output().
lambda()
const double& oomph::LinearisedNavierStokesEquations::lambda () const inline
     {
       return *Lambda_pt;
     }
References Lambda_pt.
Referenced by fill_in_generic_residual_contribution_linearised_nst(), and oomph::RefineableLinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst().
lambda_pt()
double*& oomph::LinearisedNavierStokesEquations::lambda_pt () inline
Pointer to lambda.
     {
       return Lambda_pt;
     }
References Lambda_pt.
normalisation_element_pt()
LinearisedNavierStokesEigenfunctionNormalisationElement* oomph::LinearisedNavierStokesEquations::normalisation_element_pt () inline
Pointer to normalisation element.
     {
       return Normalisation_element_pt;
     }
References Normalisation_element_pt.
Referenced by oomph::RefineableLinearisedNavierStokesEquations::further_build().
npres_linearised_nst()
virtual unsigned oomph::LinearisedNavierStokesEquations::npres_linearised_nst () const pure virtual
Return the number of pressure degrees of freedom associated with a single pressure component in the element
Implemented in oomph::LinearisedQTaylorHoodElement, and oomph::LinearisedQCrouzeixRaviartElement.
Referenced by fill_in_generic_residual_contribution_linearised_nst(), oomph::RefineableLinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst(), and interpolated_p_linearised_nst().
omega()
const double& oomph::LinearisedNavierStokesEquations::omega () const inline
     {
       return *Omega_pt;
     }
References Omega_pt.
Referenced by fill_in_generic_residual_contribution_linearised_nst(), and oomph::RefineableLinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst().
omega_pt()
double*& oomph::LinearisedNavierStokesEquations::omega_pt () inline
Pointer to frequency.
     {
       return Omega_pt;
     }
References Omega_pt.
output() [1/4]
void oomph::LinearisedNavierStokesEquations::output (FILE * file_pt) inline virtual
Output function: r, z, U^C, U^S, V^C, V^S, W^C, W^S, P^C, P^S in tecplot format. Default number of plot points
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::LinearisedQTaylorHoodElement, and oomph::LinearisedQCrouzeixRaviartElement.
     {
       const unsigned nplot = 5;
       output(file_pt, nplot);
     }
References output().
output() [2/4]
void oomph::LinearisedNavierStokesEquations::output (FILE * file_pt, const unsigned & nplot) virtual
Output function: r, z, U^C, U^S, V^C, V^S, W^C, W^S, P^C, P^S in tecplot format. nplot points in each coordinate direction
Output function in tecplot format: r, z, U^C, U^S, V^C, V^S, W^C, W^S, P^C, P^S Specified number of plot points in each coordinate direction.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::LinearisedQTaylorHoodElement, and oomph::LinearisedQCrouzeixRaviartElement.
   {
     // Provide storage for vector of local coordinates
     Vector<double> s(2);
     // Tecplot header info
     fprintf(file_pt, "%s ", tecplot_zone_string(nplot).c_str());
     // Determine number of plot points
     const unsigned n_plot_points = nplot_points(nplot);
     // Loop over plot points
     for (unsigned iplot = 0; iplot < n_plot_points; iplot++)
     {
       // Get local coordinates of plot point
       get_s_plot(iplot, nplot, s);
       // Output global coordinates to file
       for (unsigned i = 0; i < 2; i++)
       {
         fprintf(file_pt, "%g ", interpolated_x(s, i));
       }
       //  Output velocities to file
       for (unsigned i = 0; i < (2 * DIM); i++)
       {
         fprintf(file_pt, "%g ", interpolated_u_linearised_nst(s, i));
       }
       // Output pressure to file
       for (unsigned i = 0; i < 2; i++)
       {
         fprintf(file_pt, "%g ", interpolated_p_linearised_nst(s, i));
       }
       fprintf(file_pt, "\n");
     }
     fprintf(file_pt, "\n");
     // Write tecplot footer (e.g. FE connectivity lists)
     write_tecplot_zone_footer(file_pt, nplot);
   } // End of output
References DIM, oomph::FiniteElement::get_s_plot(), i, interpolated_p_linearised_nst(), interpolated_u_linearised_nst(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output() [3/4]
void oomph::LinearisedNavierStokesEquations::output (std::ostream & outfile) inline virtual
Output function: r, z, U^C, U^S, V^C, V^S, W^C, W^S, P^C, P^S in tecplot format. Default number of plot points
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::LinearisedQTaylorHoodElement, and oomph::LinearisedQCrouzeixRaviartElement.
     {
       const unsigned nplot = 5;
       output(outfile, nplot);
     }
Referenced by output(), oomph::LinearisedQCrouzeixRaviartElement::output(), and oomph::LinearisedQTaylorHoodElement::output().
output() [4/4]
void oomph::LinearisedNavierStokesEquations::output (std::ostream & outfile, const unsigned & nplot) virtual
Output function: r, z, U^C, U^S, V^C, V^S, W^C, W^S, P^C, P^S in tecplot format. nplot points in each coordinate direction
Output function in tecplot format: r, z, U^C, U^S, V^C, V^S, W^C, W^S, P^C, P^S in tecplot format. Specified number of plot points in each coordinate direction.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::LinearisedQTaylorHoodElement, and oomph::LinearisedQCrouzeixRaviartElement.
   {
     // Provide storage for vector of local coordinates
     Vector<double> s(DIM);
     // Tecplot header info
     outfile << tecplot_zone_string(nplot);
     // Determine number of plot points
     const unsigned n_plot_points = nplot_points(nplot);
     // Loop over plot points
     for (unsigned iplot = 0; iplot < n_plot_points; iplot++)
     {
       // Get local coordinates of plot point
       get_s_plot(iplot, nplot, s);
       // Output global coordinates to file
       for (unsigned i = 0; i < DIM; i++)
       {
         outfile << interpolated_x(s, i) << " ";
       }
       //  Output velocities (and normalisation) to file
       for (unsigned i = 0; i < (4 * DIM); i++)
       {
         outfile << interpolated_u_linearised_nst(s, i) << " ";
       }
       // Output pressure to file
       for (unsigned i = 0; i < 2; i++)
       {
         outfile << interpolated_p_linearised_nst(s, i) << " ";
       }
       outfile << std::endl;
     }
     outfile << std::endl;
     // Write tecplot footer (e.g. FE connectivity lists)
     write_tecplot_zone_footer(outfile, nplot);
   } // End of output
References DIM, oomph::FiniteElement::get_s_plot(), i, interpolated_p_linearised_nst(), interpolated_u_linearised_nst(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output_veloc()
void oomph::LinearisedNavierStokesEquations::output_veloc (std::ostream & outfile, const unsigned & nplot, const unsigned & t)
Output function: r, z, U^C, U^S, V^C, V^S, W^C, W^S, in tecplot format. nplot points in each coordinate direction at timestep t (t=0: present; t>0: previous timestep)
Output function in tecplot format: Velocities only r, z, U^C, U^S, V^C, V^S, W^C, W^S at specified previous timestep (t=0 present; t>0 previous timestep). Specified number of plot points in each coordinate direction.
   {
     // Determine number of nodes in element
     const unsigned n_node = nnode();
     // Provide storage for local shape functions
     Shape psi(n_node);
     // Provide storage for vectors of local coordinates and
     // global coordinates and velocities
     Vector<double> s(DIM);
     Vector<double> interpolated_x(DIM);
     Vector<double> interpolated_u(2 * DIM);
     // Tecplot header info
     outfile << tecplot_zone_string(nplot);
     // Determine number of plot points
     const unsigned n_plot_points = nplot_points(nplot);
     // Loop over plot points
     for (unsigned iplot = 0; iplot < n_plot_points; iplot++)
     {
       // Get local coordinates of plot point
       get_s_plot(iplot, nplot, s);
       // Get shape functions
       shape(s, psi);
       // Loop over coordinate directions
       for (unsigned i = 0; i < DIM; i++)
       {
         // Initialise global coordinate
         interpolated_x[i] = 0.0;
         // Loop over the local nodes and sum
         for (unsigned l = 0; l < n_node; l++)
         {
           interpolated_x[i] += nodal_position(t, l, i) * psi[l];
         }
       }
       // Loop over the velocity components
       for (unsigned i = 0; i < (2 * DIM); i++)
       {
         // Get the index at which the velocity is stored
         const unsigned u_nodal_index = u_index_linearised_nst(i);
         // Initialise velocity
         interpolated_u[i] = 0.0;
         // Loop over the local nodes and sum
         for (unsigned l = 0; l < n_node; l++)
         {
           interpolated_u[i] += nodal_value(t, l, u_nodal_index) * psi[l];
         }
       }
       // Output global coordinates to file
       for (unsigned i = 0; i < DIM; i++)
       {
         outfile << interpolated_x[i] << " ";
       }
       // Output velocities to file
       for (unsigned i = 0; i < (2 * DIM); i++)
       {
         outfile << interpolated_u[i] << " ";
       }
       outfile << std::endl;
     }
     // Write tecplot footer (e.g. FE connectivity lists)
     write_tecplot_zone_footer(outfile, nplot);
   } // End of output_veloc
References DIM, oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_value(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::shape(), plotPSD::t, oomph::FiniteElement::tecplot_zone_string(), u_index_linearised_nst(), and oomph::FiniteElement::write_tecplot_zone_footer().
p_index_linearised_nst()
virtual int oomph::LinearisedNavierStokesEquations::p_index_linearised_nst (const unsigned & i) const inline virtual
Which nodal value represents the pressure?
Reimplemented in oomph::LinearisedQTaylorHoodElement.
     {
       return Pressure_not_stored_at_node;
     }
References Pressure_not_stored_at_node.
Referenced by oomph::RefineableLinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst(), oomph::RefineableLinearisedQTaylorHoodElement::pin_elemental_redundant_nodal_pressure_dofs(), and oomph::RefineableLinearisedQTaylorHoodElement::unpin_elemental_pressure_dofs().
p_linearised_nst()
virtual double oomph::LinearisedNavierStokesEquations::p_linearised_nst (const unsigned & n_p, const unsigned & i) const pure virtual
Return the i-th pressure value at local pressure "node" n_p. Uses suitably interpolated value for hanging nodes.
Implemented in oomph::LinearisedQTaylorHoodElement, and oomph::LinearisedQCrouzeixRaviartElement.
Referenced by fill_in_generic_residual_contribution_linearised_nst(), oomph::RefineableLinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst(), and interpolated_p_linearised_nst().
p_local_eqn()
virtual int oomph::LinearisedNavierStokesEquations::p_local_eqn (const unsigned & n, const unsigned & i) protected pure virtual
Access function for the local equation number information for the i-th component of the pressure. p_local_eqn[n,i] = local equation number or < 0 if pinned.
Implemented in oomph::LinearisedQTaylorHoodElement, and oomph::LinearisedQCrouzeixRaviartElement.
Referenced by fill_in_generic_residual_contribution_linearised_nst(), and oomph::RefineableLinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst().
pin_pressure_normalisation_dofs()
virtual void oomph::LinearisedNavierStokesEquations::pin_pressure_normalisation_dofs () pure virtual
Pin the normalisation dofs.
Implemented in oomph::LinearisedQTaylorHoodElement, and oomph::LinearisedQCrouzeixRaviartElement.
pin_real_or_imag()
virtual void oomph::LinearisedNavierStokesEquations::pin_real_or_imag (const unsigned & real) pure virtual
Pin the real or imaginary part of the problem Input integer 0 for real 1 for imaginary
Implemented in oomph::LinearisedQCrouzeixRaviartElement, and oomph::LinearisedQTaylorHoodElement.
pshape_linearised_nst() [1/2]
virtual void oomph::LinearisedNavierStokesEquations::pshape_linearised_nst (const Vector< double > & s, Shape & psi) const protected pure virtual
Compute the pressure shape functions at local coordinate s.
Implemented in oomph::LinearisedQTaylorHoodElement, and oomph::LinearisedQCrouzeixRaviartElement.
Referenced by fill_in_generic_residual_contribution_linearised_nst(), oomph::RefineableLinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst(), and interpolated_p_linearised_nst().
pshape_linearised_nst() [2/2]
virtual void oomph::LinearisedNavierStokesEquations::pshape_linearised_nst (const Vector< double > & s, Shape & psi, Shape & test) const protected pure virtual
Compute the pressure shape and test functions at local coordinate s.
Implemented in oomph::LinearisedQTaylorHoodElement, and oomph::LinearisedQCrouzeixRaviartElement.
re()
const double& oomph::LinearisedNavierStokesEquations::re () const inline
Reynolds number.
     {
       return *Re_pt;
     }
References Re_pt.
Referenced by fill_in_generic_residual_contribution_linearised_nst(), and oomph::RefineableLinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst().
re_pt()
double*& oomph::LinearisedNavierStokesEquations::re_pt () inline
Pointer to Reynolds number.
     {
       return Re_pt;
     }
References Re_pt.
Referenced by oomph::RefineableLinearisedNavierStokesEquations::further_build().
re_st()
const double& oomph::LinearisedNavierStokesEquations::re_st () const inline
Product of Reynolds and Strouhal number (=Womersley number)
     {
       return *ReSt_pt;
     }
References ReSt_pt.
Referenced by fill_in_generic_residual_contribution_linearised_nst(), and oomph::RefineableLinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst().
re_st_pt()
double*& oomph::LinearisedNavierStokesEquations::re_st_pt () inline
Pointer to product of Reynolds and Strouhal number (=Womersley number)
     {
       return ReSt_pt;
     }
References ReSt_pt.
Referenced by oomph::RefineableLinearisedNavierStokesEquations::further_build().
set_eigenfunction_normalisation_element()
void oomph::LinearisedNavierStokesEquations::set_eigenfunction_normalisation_element (LinearisedNavierStokesEigenfunctionNormalisationElement *const & normalisation_el_pt) inline
the boolean flag check_nodal_data is set to false.
     {
       // Set the normalisation element
       Normalisation_element_pt = normalisation_el_pt;
       // Add eigenvalue unknown as external data to this element
       Data_number_of_eigenvalue =
         this->add_external_data(normalisation_el_pt->eigenvalue_data_pt());
       // Which value corresponds to the eigenvalue
       Index_of_eigenvalue = normalisation_el_pt->index_of_eigenvalue();
       // Now set the pointers to the eigenvalues
       Lambda_pt = normalisation_el_pt->eigenvalue_data_pt()->value_pt(
         Index_of_eigenvalue);
       Omega_pt = normalisation_el_pt->eigenvalue_data_pt()->value_pt(
         Index_of_eigenvalue + 1);
     }
References oomph::GeneralisedElement::add_external_data(), Data_number_of_eigenvalue, oomph::LinearisedNavierStokesEigenfunctionNormalisationElement::eigenvalue_data_pt(), oomph::LinearisedNavierStokesEigenfunctionNormalisationElement::index_of_eigenvalue(), Index_of_eigenvalue, Lambda_pt, Normalisation_element_pt, Omega_pt, and oomph::Data::value_pt().
Referenced by oomph::RefineableLinearisedNavierStokesEquations::further_build().
strain_rate()
void oomph::LinearisedNavierStokesEquations::strain_rate (const Vector< double > & s, DenseMatrix< double > & strainrate, const unsigned & real) const
Strain-rate tensor: \(e_{ij} \) where \(i,j = r,z,\theta \) (in that order)
Get strain-rate tensor: \(e_{ij} \) where \(i,j = r,z,\theta \) (in that order). We evaluate this tensor at a value of theta such that the product of theta and the azimuthal mode number (k) gives \(\pi/4 \). Therefore \(\cos(k \theta) = \sin(k \theta) = 1/\sqrt{2} \).
   {
 #ifdef PARANOID
     if ((strainrate.ncol() != DIM) || (strainrate.nrow() != DIM))
     {
       std::ostringstream error_message;
       error_message << "The strain rate has incorrect dimensions "
                     << strainrate.ncol() << " x " << strainrate.nrow()
                     << " Not " << DIM << std::endl;
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // The question is what to do about the real and imaginary parts
     // The answer is that we know that the "real" velocity is
     // U_r cos(omega t) - U_i sin(omega t) and we can choose omega t
     // to be 7pi/4 so that cos = 1/sqrt(2) and sin = -1/sqrt(2)
     // to get equal contributions
     double cosomegat = 1.0 / sqrt(2.0);
     double sinomegat = cosomegat;
     // Find out how many nodes there are in the element
     unsigned n_node = nnode();
     // Set up memory for the shape and test functions
     Shape psif(n_node);
     DShape dpsifdx(n_node, DIM);
     // Call the derivatives of the shape functions
     dshape_eulerian(s, psif, dpsifdx);
     // Velocity gradient matrix
     Vector<Vector<std::complex<double>>> dudx(DIM);
     // Initialise to zero
     for (unsigned i = 0; i < DIM; ++i)
     {
       dudx[i].resize(DIM);
       for (unsigned j = 0; j < DIM; ++j)
       {
         dudx[i][j].real(0.0);
         dudx[i][j].imag(0.0);
       }
     }
     // Get the nodal indices at which the velocity is stored
     unsigned n_veloc = 2 * DIM;
     unsigned u_nodal_index[n_veloc];
     for (unsigned i = 0; i < n_veloc; ++i)
     {
       u_nodal_index[i] = u_index_linearised_nst(i);
     }
     // Loop over the element's nodes
     for (unsigned l = 0; l < n_node; l++)
     {
       // Loop over the DIM complex velocity components
       for (unsigned i = 0; i < DIM; i++)
       {
         // Get the value
         const std::complex<double> u_value(
           this->raw_nodal_value(l, u_nodal_index[2 * i + 0]),
           this->raw_nodal_value(l, u_nodal_index[2 * i + 1]));
         // Loop over two coordinate directions (for derivatives)
         for (unsigned j = 0; j < DIM; j++)
         {
           dudx[i][j] += u_value * dpsifdx(l, j);
         }
       }
     }
     // Take the real part of the velocity gradient matrix
     DenseMatrix<double> real_dudx(DIM);
     if (real == 0)
     {
       cosomegat = 1.0;
       sinomegat = 0.0;
     }
     else
     {
       cosomegat = 0.0;
       sinomegat = 1.0;
     }
     for (unsigned i = 0; i < DIM; ++i)
     {
       for (unsigned j = 0; j < DIM; ++j)
       {
         real_dudx(i, j) =
           dudx[i][j].real() * cosomegat + dudx[i][j].imag() * sinomegat;
       }
     }
     // Now set the strain rate
     // Loop over veclocity components
     for (unsigned i = 0; i < DIM; i++)
     {
       // Loop over derivative directions
       for (unsigned j = 0; j < DIM; j++)
       {
         strainrate(i, j) = 0.5 * (real_dudx(i, j) + real_dudx(j, i));
       }
     }
   } // End of strain_rate
References DIM, oomph::FiniteElement::dshape_eulerian(), i, j, oomph::DenseMatrix< T >::ncol(), oomph::FiniteElement::nnode(), oomph::DenseMatrix< T >::nrow(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::FiniteElement::raw_nodal_value(), s, sqrt(), and u_index_linearised_nst().
Referenced by oomph::RefineableLinearisedNavierStokesEquations::get_Z2_flux().
u_index_linearised_nst()
virtual unsigned oomph::LinearisedNavierStokesEquations::u_index_linearised_nst (const unsigned & i) const inline virtual
Return the index at which the i-th unknown velocity component is stored. The default value, i, is appropriate for single-physics problems. In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknowns are always stored at the same indices at each node.
     {
       return i;
     }
References i.
Referenced by du_dt_linearised_nst(), fill_in_generic_residual_contribution_linearised_nst(), oomph::RefineableLinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst(), oomph::RefineableLinearisedQCrouzeixRaviartElement::get_interpolated_values(), oomph::RefineableLinearisedQTaylorHoodElement::get_interpolated_values(), interpolated_u_linearised_nst(), output_veloc(), and strain_rate().
unpin_real_or_imag()
virtual void oomph::LinearisedNavierStokesEquations::unpin_real_or_imag (const unsigned & real) pure virtual
Implemented in oomph::LinearisedQCrouzeixRaviartElement, and oomph::LinearisedQTaylorHoodElement.
viscosity_ratio()
const double& oomph::LinearisedNavierStokesEquations::viscosity_ratio () const inline
Viscosity ratio for element: element's viscosity relative to the viscosity used in the definition of the Reynolds number
     {
       return *Viscosity_Ratio_pt;
     }
References Viscosity_Ratio_pt.
Referenced by fill_in_generic_residual_contribution_linearised_nst(), and oomph::RefineableLinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst().
viscosity_ratio_pt()
double*& oomph::LinearisedNavierStokesEquations::viscosity_ratio_pt () inline
Pointer to the viscosity ratio.
     {
       return Viscosity_Ratio_pt;
     }
References Viscosity_Ratio_pt.
Referenced by oomph::RefineableLinearisedNavierStokesEquations::further_build().
Member Data Documentation
ALE_is_disabled
bool oomph::LinearisedNavierStokesEquations::ALE_is_disabled protected
Boolean flag to indicate if ALE formulation is disabled when the time-derivatives are computed. Only set to true if you're sure that the mesh is stationary.
Referenced by disable_ALE(), enable_ALE(), and oomph::RefineableLinearisedNavierStokesEquations::further_build().
base_flow_dudx_fct_pt
void(*&)(const double& time, const Vector<double>& x, DenseMatrix<double>& f) oomph::LinearisedNavierStokesEquations::base_flow_dudx_fct_pt() inline
Access function for the derivatives of the base flow w.r.t. global coordinates solution pointer
     {
       return Base_flow_dudx_fct_pt;
     }
Base_flow_dudx_fct_pt
void(* oomph::LinearisedNavierStokesEquations::Base_flow_dudx_fct_pt) (const double &time, const Vector< double > &x, DenseMatrix< double > &result) protected
Pointer to derivatives of base flow solution velocity components w.r.t. global coordinates (r and z) function
Referenced by get_base_flow_dudx().
base_flow_u_fct_pt
void(*&)(const double& time, const Vector<double>& x, Vector<double>& f) oomph::LinearisedNavierStokesEquations::base_flow_u_fct_pt() inline
Access function for the base flow solution pointer.
     {
       return Base_flow_u_fct_pt;
     }
Base_flow_u_fct_pt
void(* oomph::LinearisedNavierStokesEquations::Base_flow_u_fct_pt) (const double &time, const Vector< double > &x, Vector< double > &result) protected
Pointer to base flow solution (velocity components) function.
Referenced by get_base_flow_u().
Data_number_of_eigenvalue
unsigned oomph::LinearisedNavierStokesEquations::Data_number_of_eigenvalue protected
Index of datum where eigenvalue is stored.
Referenced by LinearisedNavierStokesEquations(), and set_eigenfunction_normalisation_element().
Default_Physical_Constant_Value
double oomph::LinearisedNavierStokesEquations::Default_Physical_Constant_Value = 0.0 static private
Static default value for the physical constants (all initialised to zero)
Referenced by LinearisedNavierStokesEquations().
Default_Physical_Ratio_Value
double oomph::LinearisedNavierStokesEquations::Default_Physical_Ratio_Value = 1.0 static private
Static default value for the physical ratios (all initialised to one)
Referenced by LinearisedNavierStokesEquations().
Density_Ratio_pt
double* oomph::LinearisedNavierStokesEquations::Density_Ratio_pt protected
Pointer to the density ratio (relative to the density used in the definition of the Reynolds number)
Referenced by density_ratio(), density_ratio_pt(), oomph::RefineableLinearisedNavierStokesEquations::further_build(), and LinearisedNavierStokesEquations().
Gamma
Vector< double > oomph::LinearisedNavierStokesEquations::Gamma static
Vector to decide whether the stress-divergence form is used or not.
Linearised axisymmetric Navier–Stokes equations static data.
Referenced by FlowAroundCylinderProblem< ELEMENT >::add_eigenproblem(), fill_in_generic_residual_contribution_linearised_nst(), and oomph::RefineableLinearisedNavierStokesEquations::fill_in_generic_residual_contribution_linearised_nst().
Index_of_eigenvalue
unsigned oomph::LinearisedNavierStokesEquations::Index_of_eigenvalue protected
Referenced by LinearisedNavierStokesEquations(), and set_eigenfunction_normalisation_element().
Lambda_pt
double* oomph::LinearisedNavierStokesEquations::Lambda_pt protected
Pointer to eigenvalue.
Referenced by lambda(), lambda_pt(), LinearisedNavierStokesEquations(), and set_eigenfunction_normalisation_element().
Normalisation_element_pt
LinearisedNavierStokesEigenfunctionNormalisationElement* oomph::LinearisedNavierStokesEquations::Normalisation_element_pt protected
Pointer to the normalisation element.
Referenced by LinearisedNavierStokesEquations(), normalisation_element_pt(), and set_eigenfunction_normalisation_element().
Omega_pt
double* oomph::LinearisedNavierStokesEquations::Omega_pt protected
Pointer to frequency.
Referenced by LinearisedNavierStokesEquations(), omega(), omega_pt(), and set_eigenfunction_normalisation_element().
Pressure_not_stored_at_node
int oomph::LinearisedNavierStokesEquations::Pressure_not_stored_at_node = -100 static private
Static "magic" number that indicates that the pressure is not stored at a node
Referenced by p_index_linearised_nst().
Re_pt
double* oomph::LinearisedNavierStokesEquations::Re_pt protected
Pointer to global Reynolds number.
Referenced by oomph::RefineableLinearisedNavierStokesEquations::further_build(), LinearisedNavierStokesEquations(), re(), and re_pt().
ReSt_pt
double* oomph::LinearisedNavierStokesEquations::ReSt_pt protected
Pointer to global Reynolds number x Strouhal number (=Womersley)
Referenced by oomph::RefineableLinearisedNavierStokesEquations::further_build(), LinearisedNavierStokesEquations(), re_st(), and re_st_pt().
Viscosity_Ratio_pt
double* oomph::LinearisedNavierStokesEquations::Viscosity_Ratio_pt protected
Pointer to the viscosity ratio (relative to the viscosity used in the definition of the Reynolds number)
Referenced by oomph::RefineableLinearisedNavierStokesEquations::further_build(), LinearisedNavierStokesEquations(), viscosity_ratio(), and viscosity_ratio_pt().
The documentation for this class was generated from the following files:
linearised_navier_stokes_elements.h
linearised_navier_stokes_elements.cc