MercuryDPM: cxx11_tensor_math.cpp File Reference
cxx11_tensor_math.cpp File Reference
#include "main.h"
#include <Eigen/CXX11/Tensor>
Functions
static void test_tanh ()
static void test_sigmoid ()
EIGEN_DECLARE_TEST (cxx11_tensor_math)
Function Documentation
EIGEN_DECLARE_TEST()
EIGEN_DECLARE_TEST (cxx11_tensor_math)
{
   CALL_SUBTEST(test_tanh());
   CALL_SUBTEST(test_sigmoid());
 }
References CALL_SUBTEST, test_sigmoid(), and test_tanh().
test_sigmoid()
static void test_sigmoid () static
{
   Tensor<float, 1> vec1(6);
   vec1.setRandom();
   Tensor<float, 1> vec2 = vec1.sigmoid();
   for (int i = 0; i < 6; ++i) {
     VERIFY_IS_APPROX(vec2(i), 1.0f / (1.0f + std::exp(-vec1(i))));
   }
 }
References Eigen::bfloat16_impl::exp(), i, vec1(), and VERIFY_IS_APPROX.
Referenced by EIGEN_DECLARE_TEST().
test_tanh()
static void test_tanh () static
{
   Tensor<float, 1> vec1(6);
   vec1.setRandom();
   Tensor<float, 1> vec2 = vec1.tanh();
   for (int i = 0; i < 6; ++i) {
     VERIFY_IS_APPROX(vec2(i), tanhf(vec1(i)));
   }
 }
References i, vec1(), and VERIFY_IS_APPROX.
Referenced by EIGEN_DECLARE_TEST().