MercuryDPM: Eigen::SparseQR_QProduct< SparseQRType, Derived > Struct Template Reference
Eigen::SparseQR_QProduct< SparseQRType, Derived > Struct Template Reference
#include <SparseQR.h>
Public Types
typedef SparseQRType::QRMatrixType MatrixType
typedef SparseQRType::Scalar Scalar
Public Types inherited from Eigen::ReturnByValue< SparseQR_QProduct< SparseQRType, Derived > >
typedef internal::traits< SparseQR_QProduct< SparseQRType, Derived > >::ReturnType ReturnType
typedef internal::dense_xpr_base< ReturnByValue >::type Base
Public Member Functions
SparseQR_QProduct (const SparseQRType &qr, const Derived &other, bool transpose)
Index rows () const
Index cols () const
template<typename DesType >
void evalTo (DesType &res) const
Public Member Functions inherited from Eigen::ReturnByValue< SparseQR_QProduct< SparseQRType, Derived > >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
const Unusable & coeff (Index) const
const Unusable & coeff (Index, Index) const
Unusable & coeffRef (Index)
Unusable & coeffRef (Index, Index)
Public Attributes
const SparseQRType & m_qr
const Derived & m_other
bool m_transpose
Member Typedef Documentation
MatrixType
template<typename SparseQRType , typename Derived > typedef SparseQRType::QRMatrixType Eigen::SparseQR_QProduct< SparseQRType, Derived >::MatrixType
Scalar
template<typename SparseQRType , typename Derived > typedef SparseQRType::Scalar Eigen::SparseQR_QProduct< SparseQRType, Derived >::Scalar
Constructor & Destructor Documentation
SparseQR_QProduct()
template<typename SparseQRType , typename Derived > Eigen::SparseQR_QProduct< SparseQRType, Derived >::SparseQR_QProduct (const SparseQRType & qr, const Derived & other, bool transpose) inline
       : m_qr(qr), m_other(other), m_transpose(transpose) {}
Member Function Documentation
cols()
template<typename SparseQRType , typename Derived > Index Eigen::SparseQR_QProduct< SparseQRType, Derived >::cols () const inline
 { return m_other.cols(); }
References Eigen::SparseQR_QProduct< SparseQRType, Derived >::m_other.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), Eigen::SparseQR_QProduct< SparseQRType, Derived >::evalTo(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
evalTo()
template<typename SparseQRType , typename Derived > template<typename DesType > void Eigen::SparseQR_QProduct< SparseQRType, Derived >::evalTo (DesType & res) const inline
{
     Index m = m_qr.rows();
     Index n = m_qr.cols();
     Index diagSize = (std::min)(m, n);
     res = m_other;
     if (m_transpose) {
       eigen_assert(m_qr.m_Q.rows() == m_other.rows() && "Non conforming object sizes");
       // Compute res = Q' * other column by column
       for (Index j = 0; j < res.cols(); j++) {
         for (Index k = 0; k < diagSize; k++) {
           Scalar tau = Scalar(0);
           tau = m_qr.m_Q.col(k).dot(res.col(j));
           if (tau == Scalar(0)) continue;
           tau = tau * m_qr.m_hcoeffs(k);
           res.col(j) -= tau * m_qr.m_Q.col(k);
         }
       }
     } else {
       eigen_assert(m_qr.matrixQ().cols() == m_other.rows() && "Non conforming object sizes");
       res.conservativeResize(rows(), cols());
       // Compute res = Q * other column by column
       for (Index j = 0; j < res.cols(); j++) {
         Index start_k = internal::is_identity<Derived>::value ? numext::mini(j, diagSize - 1) : diagSize - 1;
         for (Index k = start_k; k >= 0; k--) {
           Scalar tau = Scalar(0);
           tau = m_qr.m_Q.col(k).dot(res.col(j));
           if (tau == Scalar(0)) continue;
           tau = tau * numext::conj(m_qr.m_hcoeffs(k));
           res.col(j) -= tau * m_qr.m_Q.col(k);
         }
       }
     }
   }
References Eigen::SparseQR_QProduct< SparseQRType, Derived >::cols(), conj(), eigen_assert, j, k, m, Eigen::SparseQR_QProduct< SparseQRType, Derived >::m_other, Eigen::SparseQR_QProduct< SparseQRType, Derived >::m_qr, Eigen::SparseQR_QProduct< SparseQRType, Derived >::m_transpose, min, Eigen::numext::mini(), n, res, and Eigen::SparseQR_QProduct< SparseQRType, Derived >::rows().
rows()
template<typename SparseQRType , typename Derived > Index Eigen::SparseQR_QProduct< SparseQRType, Derived >::rows () const inline
 { return m_qr.matrixQ().rows(); }
References Eigen::SparseQR_QProduct< SparseQRType, Derived >::m_qr.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), Eigen::SparseQR_QProduct< SparseQRType, Derived >::evalTo(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
Member Data Documentation
m_other
template<typename SparseQRType , typename Derived > const Derived& Eigen::SparseQR_QProduct< SparseQRType, Derived >::m_other
Referenced by Eigen::SparseQR_QProduct< SparseQRType, Derived >::cols(), and Eigen::SparseQR_QProduct< SparseQRType, Derived >::evalTo().
m_qr
template<typename SparseQRType , typename Derived > const SparseQRType& Eigen::SparseQR_QProduct< SparseQRType, Derived >::m_qr
Referenced by Eigen::SparseQR_QProduct< SparseQRType, Derived >::evalTo(), and Eigen::SparseQR_QProduct< SparseQRType, Derived >::rows().
m_transpose
template<typename SparseQRType , typename Derived > bool Eigen::SparseQR_QProduct< SparseQRType, Derived >::m_transpose
Referenced by Eigen::SparseQR_QProduct< SparseQRType, Derived >::evalTo().
The documentation for this struct was generated from the following file:
SparseQR.h