MercuryDPM: MercuryDataFile Class Reference
MercuryDataFile Class Reference
#include <MercuryData.h>
Classes
class IteratorProxy
Public Member Functions
MercuryDataFile (std::string name)
operator bool () const
Gives the status of the backing std::ifstream Returns true is no error has occurred. In any other case (EOF, FailBit, ErrorBit), it returns false. For more information, see std::ifstream::operator bool().
template<std::size_t NDIMS>
bool isMercuryDataFile ()
Checks if this file is a valid Mercury 3D data file. This function jumps to the start of the file, reads the first line and restores the readpointer. It then checks if that line can be succesfully parsed as a time step header. This does however not check if the file is consistent or the particle entries are valid. It can however serve as a first sanity check.
template<std::size_t NDIMS>
IteratorProxy< NDIMS > as ()
template<std::size_t NDIMS>
MercuryTimeStepIterator< NDIMS > begin ()
Returns a forwarditerator to the time steps Returns a forwarditerator to the time steps, invalidating any other valid iterators in the process (since this is a lazy loader and does not actually load the entire file in memory). End iterators do not get invalidated. This function makes no guarantee for the validity of the file-state.
template<std::size_t NDIMS>
MercuryTimeStepIterator< NDIMS > end () const
Returns a forwarditerator one past the last time step.
Private Attributes
std::ifstream file_
Friends
template<std::size_t NDIMS>
class MercuryTimeStep
template<std::size_t NDIMS>
class MercuryTimeStepIterator
Detailed Description
Lazy loader for .data files. This class allows you to iterate over all the particles in it.
Author
dducks
Constructor & Destructor Documentation
MercuryDataFile()
MercuryDataFile::MercuryDataFile (std::string name) inline
Opens the Mercury 3D .data file with filename file.
Parameters
[in] name The filename
       : file_(name)
     { }
Member Function Documentation
as()
template<std::size_t NDIMS> IteratorProxy<NDIMS> MercuryDataFile::as () inline
     {
       return {this};
     };
Referenced by transformMercuryToVTK().
begin()
template<std::size_t NDIMS> MercuryTimeStepIterator<NDIMS> MercuryDataFile::begin () inline
Returns a forwarditerator to the time steps Returns a forwarditerator to the time steps, invalidating any other valid iterators in the process (since this is a lazy loader and does not actually load the entire file in memory). End iterators do not get invalidated. This function makes no guarantee for the validity of the file-state.
     {
       file_.seekg(0);
       return {this};
     }
References file_.
Referenced by MercuryDataFile::IteratorProxy< NDIMS >::begin().
end()
template<std::size_t NDIMS> MercuryTimeStepIterator<NDIMS> MercuryDataFile::end () const inline
Returns a forwarditerator one past the last time step.
     {
         return {};
     }
Referenced by MercuryDataFile::IteratorProxy< NDIMS >::end().
isMercuryDataFile()
template<std::size_t NDIMS> bool MercuryDataFile::isMercuryDataFile () inline
Checks if this file is a valid Mercury 3D data file. This function jumps to the start of the file, reads the first line and restores the readpointer. It then checks if that line can be succesfully parsed as a time step header. This does however not check if the file is consistent or the particle entries are valid. It can however serve as a first sanity check.
Returns
true if the file appears to be a valid Mercury 3D .data file.
See also
MercuryDataFile::isMercury2DDataFile()
     {
       //Store the position, so we can jump back at the end of the function..
       std::ios::pos_type currentPosition = file_.tellg();
       //and jump to the start
       file_.seekg(0);
       //get the first line
       std::string line;
       std::getline(file_, line);
       file_.seekg(currentPosition); //and pretend nothing has happened
       std::istringstream lineStream(line);
       //We'll try to find out if there were exactly enough arguments.
       MercuryTimeStep<NDIMS> step;
       lineStream >> step;
       //Did we reach the end yet?
       bool isValid = lineStream.good() || (lineStream.eof() && !lineStream.fail());
       double dummy;
       lineStream >> dummy;
       //now we should have reached it.
       isValid = isValid && !lineStream.good();
       return isValid;
     }
References file_, calibrate::line, and oomph::Global_string_for_annotation::string().
Referenced by main().
operator bool()
MercuryDataFile::operator bool () const inline
Gives the status of the backing std::ifstream Returns true is no error has occurred. In any other case (EOF, FailBit, ErrorBit), it returns false. For more information, see std::ifstream::operator bool().
Returns
true if the underlying file is readable, false otherwise.
     {
       return file_.good();
     }
References file_.
Friends And Related Function Documentation
MercuryTimeStep
template<std::size_t NDIMS> friend class MercuryTimeStep friend
MercuryTimeStepIterator
template<std::size_t NDIMS> friend class MercuryTimeStepIterator friend
Member Data Documentation
file_
std::ifstream MercuryDataFile::file_ private
The backing file stream used to represent the data file.
Referenced by begin(), isMercuryDataFile(), operator bool(), and MercuryTimeStepIterator< NDIMS >::operator++().
The documentation for this class was generated from the following file:
MercuryData.h