MercuryDPM: hessenberg.cpp File Reference
hessenberg.cpp File Reference
#include "main.h"
#include <Eigen/Eigenvalues>
Functions
template<typename Scalar , int Size>
void hessenberg (int size=Size)
EIGEN_DECLARE_TEST (hessenberg)
Function Documentation
EIGEN_DECLARE_TEST()
EIGEN_DECLARE_TEST (hessenberg)
{
   CALL_SUBTEST_1((hessenberg<std::complex<double>, 1>()));
   CALL_SUBTEST_2((hessenberg<std::complex<double>, 2>()));
   CALL_SUBTEST_3((hessenberg<std::complex<float>, 4>()));
   CALL_SUBTEST_4((hessenberg<float, Dynamic>(internal::random<int>(1, EIGEN_TEST_MAX_SIZE))));
   CALL_SUBTEST_5((hessenberg<std::complex<double>, Dynamic>(internal::random<int>(1, EIGEN_TEST_MAX_SIZE))));
   // Test problem size constructors
   CALL_SUBTEST_6(HessenbergDecomposition<MatrixXf>(10));
 }
References CALL_SUBTEST_1, CALL_SUBTEST_2, CALL_SUBTEST_3, CALL_SUBTEST_4, CALL_SUBTEST_5, CALL_SUBTEST_6, Eigen::Dynamic, EIGEN_TEST_MAX_SIZE, and hessenberg().
hessenberg()
template<typename Scalar , int Size> void hessenberg (int size = Size)
{
   typedef Matrix<Scalar, Size, Size> MatrixType;
   // Test basic functionality: A = U H U* and H is Hessenberg
   for (int counter = 0; counter < g_repeat; ++counter) {
     MatrixType m = MatrixType::Random(size, size);
     HessenbergDecomposition<MatrixType> hess(m);
     MatrixType Q = hess.matrixQ();
     MatrixType H = hess.matrixH();
     VERIFY_IS_APPROX(m, Q * H * Q.adjoint());
     for (int row = 2; row < size; ++row) {
       for (int col = 0; col < row - 1; ++col) {
         VERIFY(H(row, col) == (typename MatrixType::Scalar)0);
       }
     }
   }
   // Test whether compute() and constructor returns same result
   MatrixType A = MatrixType::Random(size, size);
   HessenbergDecomposition<MatrixType> cs1;
   cs1.compute(A);
   HessenbergDecomposition<MatrixType> cs2(A);
   VERIFY_IS_EQUAL(cs1.matrixH().eval(), cs2.matrixH().eval());
   MatrixType cs1Q = cs1.matrixQ();
   MatrixType cs2Q = cs2.matrixQ();
   VERIFY_IS_EQUAL(cs1Q, cs2Q);
   // Test assertions for when used uninitialized
   HessenbergDecomposition<MatrixType> hessUninitialized;
   VERIFY_RAISES_ASSERT(hessUninitialized.matrixH());
   VERIFY_RAISES_ASSERT(hessUninitialized.matrixQ());
   VERIFY_RAISES_ASSERT(hessUninitialized.householderCoefficients());
   VERIFY_RAISES_ASSERT(hessUninitialized.packedMatrix());
   // TODO: Add tests for packedMatrix() and householderCoefficients()
 }
References col(), Eigen::HessenbergDecomposition< MatrixType_ >::compute(), Eigen::g_repeat, H, Eigen::HessenbergDecomposition< MatrixType_ >::householderCoefficients(), m, Eigen::HessenbergDecomposition< MatrixType_ >::matrixH(), Eigen::HessenbergDecomposition< MatrixType_ >::matrixQ(), Eigen::HessenbergDecomposition< MatrixType_ >::packedMatrix(), Q, row(), size, VERIFY, VERIFY_IS_APPROX, VERIFY_IS_EQUAL, and VERIFY_RAISES_ASSERT.
Referenced by oomph::ComplexGMRES< MATRIX >::complex_solve_helper(), EIGEN_DECLARE_TEST(), oomph::HelmholtzGMRESMG< MATRIX >::solve_helper(), oomph::HelmholtzFGMRESMG< MATRIX >::solve_helper(), oomph::ComplexGMRES< MATRIX >::update(), oomph::HelmholtzGMRESMG< MATRIX >::update(), and oomph::HelmholtzFGMRESMG< MATRIX >::update().