MercuryDPM: two_d_tilted_square.cc File Reference
two_d_tilted_square.cc File Reference
#include <fenv.h>
#include <sstream>
#include <iomanip>
#include <ios>
#include "generic.h"
#include "navier_stokes.h"
#include "meshes/simple_rectangular_quadmesh.h"
#include "meshes/rectangular_quadmesh.h"
#include "meshes/simple_cubic_mesh.h"
#include "meshes/simple_cubic_tet_mesh.h"
Classes
class oomph::SlopingQuadMesh< ELEMENT >
class TiltedCavityProblem< ELEMENT >
Namespaces
Global_Variables
Namespace for physical parameters.
oomph
DRAIG: Change all instances of (SPATIAL_DIM) to (DIM-1).
Functions
double Global_Variables::degtorad (const double &ang_deg)
Convert degrees to radians.
int main (int argc, char **argv)
Driver for Lagrange enforced flow preconditioner.
Variables
static const unsigned Global_Variables::Dim = 2
Problem dimension.
static const double Global_Variables::X_min = 0.0
Min and max x value respectively.
static const double Global_Variables::X_max = 1.0
static const double Global_Variables::Y_min = 0.0
Min and max y value respectively.
static const double Global_Variables::Y_max = 1.0
static const double Global_Variables::Lx = X_max - X_min
The domain length in the x and y direction respectively.
static const double Global_Variables::Ly = Y_max - Y_min
unsigned Global_Variables::Visc = 0
The viscous term.
double Global_Variables::Re = 100.0
Reynolds number.
double Global_Variables::Ang_deg = 30.0
Tilting angle of the domain with the x-axis.
double Global_Variables::Ang_rad = -1.0
unsigned Global_Variables::Noel = 4
Number of elements in 1D.
bool Global_Variables::Use_trilinos = false
Use trilinos?
bool Global_Variables::Use_lsc = false
Use LSC preconditioner for the Navier-Stokes block?
bool Global_Variables::Use_amg_for_f = false
Use Boomer AMG for the momentum block?
bool Global_Variables::Use_amg_for_p = false
Use Boomer AMG for the pressure block?
unsigned Global_Variables::Soln_num = 0
Soln number (for doc_solution)
Vector< unsigned > Global_Variables::Iterations
Storage for number of iterations during Newton steps.
Function Documentation
main()
int main (int argc , char ** argv)
Driver for Lagrange enforced flow preconditioner.
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
 {
 #ifdef OOMPH_HAS_MPI
   MPI_Helpers::init(argc,argv);
 #endif
   // Alias the namespace for convenience.
   namespace GV = Global_Variables;
   // Store command line arguments
   CommandLineArgs::setup(argc,argv);
   // Store the viscous term, default is simple form.
   CommandLineArgs::specify_command_line_flag("--visc", &GV::Visc);
   // Default is 100.0
   CommandLineArgs::specify_command_line_flag("--re", &GV::Re);
   // Defaults to 30 degrees
   CommandLineArgs::specify_command_line_flag("--ang", &GV::Ang_deg);
   // Defaults to 4
   CommandLineArgs::specify_command_line_flag("--noel", &GV::Noel);
   // Use trilinos solver?
   CommandLineArgs::specify_command_line_flag("--use_trilinos");
   // Use the LSC preconditioner for the Navier-Stokes block?
   CommandLineArgs::specify_command_line_flag("--use_lsc");
   // Use the amg for the momentum block?
   CommandLineArgs::specify_command_line_flag("--use_amg_for_f");
   // Use the amg for the pressure block?
   CommandLineArgs::specify_command_line_flag("--use_amg_for_p");
   CommandLineArgs::specify_command_line_flag("--soln_num", &GV::Soln_num);
   // Parse the above flags.
   CommandLineArgs::parse_and_assign();
   CommandLineArgs::doc_specified_flags();
   GV::Ang_rad = GV::degtorad(GV::Ang_deg);
   if(GV::Visc == 0)
   {
     oomph_info << "Doing simple form" << std::endl;
     for (unsigned d = 0; d < GV::Dim; d++)
     {
       NavierStokesEquations<GV::Dim>::Gamma[d] = 0.0;
     }
   }
   else
   {
     oomph_info << "Doing stress divergence form" << std::endl;
     for (unsigned d = 0; d < GV::Dim; d++)
     {
       NavierStokesEquations<GV::Dim>::Gamma[d] = 1.0;
     }
   }
   // Set the flag for trilinos solver
   if(CommandLineArgs::command_line_flag_has_been_set("--use_trilinos"))
   {
 #ifdef OOMPH_HAS_TRILINOS
     GV::Use_trilinos = true;
 #else
     std::ostringstream warning_stream;
     warning_stream << "WARNING: \n"
       << "No trilinos installed, using oomphlib's GMRES solver.\n";
     OomphLibWarning(warning_stream.str(),
       OOMPH_CURRENT_FUNCTION,
       OOMPH_EXCEPTION_LOCATION);
     GV::Use_trilinos = false;
 #endif
   }
   else
   {
     GV::Use_trilinos = false;
   }
   // Set the flag for lsc
   if(CommandLineArgs::command_line_flag_has_been_set("--use_lsc"))
   {
     GV::Use_lsc = true;
   }
   else
   {
     GV::Use_lsc = false;
   }
   // Set the flag for amg for the momentum block
   if(CommandLineArgs::command_line_flag_has_been_set("--use_amg_for_f"))
   {
     GV::Use_amg_for_f = true;
   }
   else
   {
     GV::Use_amg_for_f = false;
   }
   // Set the flag for amg for the pressure block
   if(CommandLineArgs::command_line_flag_has_been_set("--use_amg_for_p"))
   {
     GV::Use_amg_for_p = true;
   }
   else
   {
     GV::Use_amg_for_f = false;
   }
   TiltedCavityProblem< QTaylorHoodElement<GV::Dim> > problem;
   // Solve the problem
   problem.newton_solve();
   if(CommandLineArgs::command_line_flag_has_been_set("--soln_num"))
   {
     problem.doc_solution();
     // Create the soln file name string.
     std::stringstream filename;
     filename <<"RESLT/iter"<<GV::Soln_num<<".dat";
     std::ofstream some_file;
     some_file.open(filename.str().c_str());
     // Print out the iteration counts
     const unsigned num_newton_steps = GV::Iterations.size();
     some_file << num_newton_steps << "\n";
     for (unsigned stepi = 0; stepi < num_newton_steps; stepi++)
     {
       some_file << GV::Iterations[stepi] << "\n";
     }
     some_file << "\n";
     some_file.close();
   }
 #ifdef OOMPH_HAS_MPI
   MPI_Helpers::finalize();
 #endif
 } // end_of_main
References Global_Variables::Ang_deg, Global_Variables::Ang_rad, oomph::CommandLineArgs::command_line_flag_has_been_set(), Global_Variables::degtorad(), Global_Variables::Dim, oomph::CommandLineArgs::doc_specified_flags(), MergeRestartFiles::filename, Global_Variables::Iterations, Global_Variables::Noel, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::oomph_info, oomph::CommandLineArgs::parse_and_assign(), problem, Global_Variables::Re, Flag_definition::setup(), Global_Variables::Soln_num, oomph::CommandLineArgs::specify_command_line_flag(), Global_Variables::Use_amg_for_f, Global_Variables::Use_amg_for_p, Global_Variables::Use_lsc, Global_Variables::Use_trilinos, and Global_Variables::Visc.