MercuryDPM: Eigen::TensorEvaluator< const TensorLayoutSwapOp< ArgType >, Device > Struct Template Reference
Eigen::TensorEvaluator< const TensorLayoutSwapOp< ArgType >, Device > Struct Template Reference
#include <TensorLayoutSwap.h>
Public Types
enum {
IsAligned = TensorEvaluator<ArgType, Device>::IsAligned , PacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess , BlockAccess = false , PreferBlockAccess = TensorEvaluator<ArgType, Device>::PreferBlockAccess ,
CoordAccess = false , RawAccess = TensorEvaluator<ArgType, Device>::RawAccess
}
typedef TensorLayoutSwapOp< ArgType > XprType
typedef XprType::Index Index
typedef DSizes< Index, NumDims > Dimensions
typedef internal::TensorBlockNotImplemented TensorBlock
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef StorageMemory< CoeffReturnType, Device > Storage
typedef Storage::Type EvaluatorPointerType
Public Member Functions
EIGEN_STRONG_INLINE TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions & dimensions () const
EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (EvaluatorPointerType data)
EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType packet (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
EIGEN_DEVICE_FUNC Storage::Type data () const
const TensorEvaluator< ArgType, Device > & impl () const
Static Public Attributes
static constexpr int NumDims = internal::array_size<typename TensorEvaluator<ArgType, Device>::Dimensions>::value
static constexpr int Layout
Protected Attributes
TensorEvaluator< ArgType, Device > m_impl
Dimensions m_dimensions
Member Typedef Documentation
CoeffReturnType
template<typename ArgType , typename Device > typedef XprType::CoeffReturnType Eigen::TensorEvaluator< const TensorLayoutSwapOp< ArgType >, Device >::CoeffReturnType
Dimensions
template<typename ArgType , typename Device > typedef DSizes<Index, NumDims> Eigen::TensorEvaluator< const TensorLayoutSwapOp< ArgType >, Device >::Dimensions
EvaluatorPointerType
template<typename ArgType , typename Device > typedef Storage::Type Eigen::TensorEvaluator< const TensorLayoutSwapOp< ArgType >, Device >::EvaluatorPointerType
Index
template<typename ArgType , typename Device > typedef XprType::Index Eigen::TensorEvaluator< const TensorLayoutSwapOp< ArgType >, Device >::Index
PacketReturnType
template<typename ArgType , typename Device > typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorEvaluator< const TensorLayoutSwapOp< ArgType >, Device >::PacketReturnType
Scalar
template<typename ArgType , typename Device > typedef XprType::Scalar Eigen::TensorEvaluator< const TensorLayoutSwapOp< ArgType >, Device >::Scalar
Storage
template<typename ArgType , typename Device > typedef StorageMemory<CoeffReturnType, Device> Eigen::TensorEvaluator< const TensorLayoutSwapOp< ArgType >, Device >::Storage
TensorBlock
template<typename ArgType , typename Device > typedef internal::TensorBlockNotImplemented Eigen::TensorEvaluator< const TensorLayoutSwapOp< ArgType >, Device >::TensorBlock
XprType
template<typename ArgType , typename Device > typedef TensorLayoutSwapOp<ArgType> Eigen::TensorEvaluator< const TensorLayoutSwapOp< ArgType >, Device >::XprType
Member Enumeration Documentation
anonymous enum
template<typename ArgType , typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
BlockAccess
PreferBlockAccess
CoordAccess
RawAccess
        {
     IsAligned = TensorEvaluator<ArgType, Device>::IsAligned,
     PacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess,
     BlockAccess = false,
     PreferBlockAccess = TensorEvaluator<ArgType, Device>::PreferBlockAccess,
     CoordAccess = false,  // to be implemented
     RawAccess = TensorEvaluator<ArgType, Device>::RawAccess
   };
Constructor & Destructor Documentation
TensorEvaluator()
template<typename ArgType , typename Device > EIGEN_STRONG_INLINE Eigen::TensorEvaluator< const TensorLayoutSwapOp< ArgType >, Device >::TensorEvaluator (const XprType & op, const Device & device) inline
                                                                                : m_impl(op.expression(), device) {
     for (int i = 0; i < NumDims; ++i) {
       m_dimensions[i] = m_impl.dimensions()[NumDims - 1 - i];
     }
   }
References i.
Member Function Documentation
cleanup()
template<typename ArgType , typename Device > EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorLayoutSwapOp< ArgType >, Device >::cleanup () inline
 { m_impl.cleanup(); }
Referenced by framework.Frame::__init__().
coeff()
template<typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::TensorEvaluator< const TensorLayoutSwapOp< ArgType >, Device >::coeff (Index index) const inline
 { return m_impl.coeff(index); }
costPerCoeff()
template<typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorEvaluator< const TensorLayoutSwapOp< ArgType >, Device >::costPerCoeff (bool vectorized) const inline
{
     return m_impl.costPerCoeff(vectorized);
   }
data()
template<typename ArgType , typename Device > EIGEN_DEVICE_FUNC Storage::Type Eigen::TensorEvaluator< const TensorLayoutSwapOp< ArgType >, Device >::data () const inline
 { return constCast(m_impl.data()); }
References Eigen::constCast().
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
dimensions()
template<typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions& Eigen::TensorEvaluator< const TensorLayoutSwapOp< ArgType >, Device >::dimensions () const inline
 { return m_dimensions; }
evalSubExprsIfNeeded()
template<typename ArgType , typename Device > EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorLayoutSwapOp< ArgType >, Device >::evalSubExprsIfNeeded (EvaluatorPointerType data) inline
 { return m_impl.evalSubExprsIfNeeded(data); }
References Eigen::TensorEvaluator< Derived, Device >::data().
impl()
template<typename ArgType , typename Device > const TensorEvaluator<ArgType, Device>& Eigen::TensorEvaluator< const TensorLayoutSwapOp< ArgType >, Device >::impl () const inline
 { return m_impl; }
packet()
template<typename ArgType , typename Device > template<int LoadMode> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType Eigen::TensorEvaluator< const TensorLayoutSwapOp< ArgType >, Device >::packet (Index index) const inline
{
     return m_impl.template packet<LoadMode>(index);
   }
Member Data Documentation
Layout
template<typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorLayoutSwapOp< ArgType >, Device >::Layout static constexpr
Initial value:
=
      (TensorEvaluator<ArgType, Device>::Layout == static_cast<int>(ColMajor)) ? RowMajor : ColMajor
m_dimensions
template<typename ArgType , typename Device > Dimensions Eigen::TensorEvaluator< const TensorLayoutSwapOp< ArgType >, Device >::m_dimensions protected
m_impl
template<typename ArgType , typename Device > TensorEvaluator<ArgType, Device> Eigen::TensorEvaluator< const TensorLayoutSwapOp< ArgType >, Device >::m_impl protected
NumDims
template<typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorLayoutSwapOp< ArgType >, Device >::NumDims = internal::array_size<typename TensorEvaluator<ArgType, Device>::Dimensions>::value static constexpr
The documentation for this struct was generated from the following file:
TensorLayoutSwap.h