MercuryDPM: Eigen::internal::StorageRef< Scalar, StorageIndex > Class Template Reference
Eigen::internal::StorageRef< Scalar, StorageIndex > Class Template Reference
#include <SparseCompressedBase.h>
Public Types
using value_type = StorageVal< Scalar, StorageIndex >
Public Member Functions
StorageRef (StorageRef &&other)=default
StorageRef & operator= (const StorageRef &other)
StorageRef & operator= (const value_type &other)
operator value_type () const
const StorageIndex & key () const
StorageIndex & key ()
const Scalar & value () const
Scalar & value ()
StorageIndex * keyPtr () const
Scalar * valuePtr () const
operator StorageIndex () const
Protected Attributes
StorageIndex * m_innerIndexIterator
Scalar * m_valueIterator
Private Member Functions
StorageRef ()=delete
StorageRef (StorageIndex *innerIndexIterator, Scalar *valueIterator)
StorageRef (const StorageRef &other)
Friends
class CompressedStorageIterator< Scalar, StorageIndex >
void swap (const StorageRef &a, const StorageRef &b)
Member Typedef Documentation
value_type
template<typename Scalar , typename StorageIndex > using Eigen::internal::StorageRef< Scalar, StorageIndex >::value_type = StorageVal<Scalar, StorageIndex>
Constructor & Destructor Documentation
StorageRef() [1/4]
template<typename Scalar , typename StorageIndex > Eigen::internal::StorageRef< Scalar, StorageIndex >::StorageRef (StorageRef< Scalar, StorageIndex > && other) default
StorageRef() [2/4]
template<typename Scalar , typename StorageIndex > Eigen::internal::StorageRef< Scalar, StorageIndex >::StorageRef () private delete
StorageRef() [3/4]
template<typename Scalar , typename StorageIndex > Eigen::internal::StorageRef< Scalar, StorageIndex >::StorageRef (StorageIndex * innerIndexIterator, Scalar * valueIterator) inline private
       : m_innerIndexIterator(innerIndexIterator), m_valueIterator(valueIterator) {}
StorageRef() [4/4]
template<typename Scalar , typename StorageIndex > Eigen::internal::StorageRef< Scalar, StorageIndex >::StorageRef (const StorageRef< Scalar, StorageIndex > & other) inline private
       : m_innerIndexIterator(other.m_innerIndexIterator), m_valueIterator(other.m_valueIterator) {}
Member Function Documentation
key() [1/2]
template<typename Scalar , typename StorageIndex > StorageIndex& Eigen::internal::StorageRef< Scalar, StorageIndex >::key () inline
 { return *m_innerIndexIterator; }
References Eigen::internal::StorageRef< Scalar, StorageIndex >::m_innerIndexIterator.
key() [2/2]
template<typename Scalar , typename StorageIndex > const StorageIndex& Eigen::internal::StorageRef< Scalar, StorageIndex >::key () const inline
 { return *m_innerIndexIterator; }
References Eigen::internal::StorageRef< Scalar, StorageIndex >::m_innerIndexIterator.
Referenced by Eigen::internal::StorageRef< Scalar, StorageIndex >::operator value_type(), and Eigen::internal::StorageRef< Scalar, StorageIndex >::operator=().
keyPtr()
template<typename Scalar , typename StorageIndex > StorageIndex* Eigen::internal::StorageRef< Scalar, StorageIndex >::keyPtr () const inline
 { return m_innerIndexIterator; }
References Eigen::internal::StorageRef< Scalar, StorageIndex >::m_innerIndexIterator.
operator StorageIndex()
template<typename Scalar , typename StorageIndex > Eigen::internal::StorageRef< Scalar, StorageIndex >::operator StorageIndex () const inline
 { return *m_innerIndexIterator; }
References Eigen::internal::StorageRef< Scalar, StorageIndex >::m_innerIndexIterator.
operator value_type()
template<typename Scalar , typename StorageIndex > Eigen::internal::StorageRef< Scalar, StorageIndex >::operator value_type () const inline
 { return value_type(key(), value()); }
References Eigen::internal::StorageRef< Scalar, StorageIndex >::key(), and Eigen::internal::StorageRef< Scalar, StorageIndex >::value().
operator=() [1/2]
template<typename Scalar , typename StorageIndex > StorageRef& Eigen::internal::StorageRef< Scalar, StorageIndex >::operator= (const StorageRef< Scalar, StorageIndex > & other) inline
{
     key() = other.key();
     value() = other.value();
     return *this;
   }
References Eigen::internal::StorageRef< Scalar, StorageIndex >::key(), and Eigen::internal::StorageRef< Scalar, StorageIndex >::value().
operator=() [2/2]
template<typename Scalar , typename StorageIndex > StorageRef& Eigen::internal::StorageRef< Scalar, StorageIndex >::operator= (const value_type & other) inline
{
     key() = other.key();
     value() = other.value();
     return *this;
   }
References Eigen::internal::StorageVal< Scalar, StorageIndex >::key(), Eigen::internal::StorageRef< Scalar, StorageIndex >::key(), Eigen::internal::StorageVal< Scalar, StorageIndex >::value(), and Eigen::internal::StorageRef< Scalar, StorageIndex >::value().
value() [1/2]
template<typename Scalar , typename StorageIndex > Scalar& Eigen::internal::StorageRef< Scalar, StorageIndex >::value () inline
 { return *m_valueIterator; }
References Eigen::internal::StorageRef< Scalar, StorageIndex >::m_valueIterator.
value() [2/2]
template<typename Scalar , typename StorageIndex > const Scalar& Eigen::internal::StorageRef< Scalar, StorageIndex >::value () const inline
 { return *m_valueIterator; }
References Eigen::internal::StorageRef< Scalar, StorageIndex >::m_valueIterator.
Referenced by Eigen::internal::StorageRef< Scalar, StorageIndex >::operator value_type(), and Eigen::internal::StorageRef< Scalar, StorageIndex >::operator=().
valuePtr()
template<typename Scalar , typename StorageIndex > Scalar* Eigen::internal::StorageRef< Scalar, StorageIndex >::valuePtr () const inline
 { return m_valueIterator; }
References Eigen::internal::StorageRef< Scalar, StorageIndex >::m_valueIterator.
Friends And Related Function Documentation
CompressedStorageIterator< Scalar, StorageIndex >
template<typename Scalar , typename StorageIndex > friend class CompressedStorageIterator< Scalar, StorageIndex > friend
swap
template<typename Scalar , typename StorageIndex > void swap (const StorageRef< Scalar, StorageIndex > & a, const StorageRef< Scalar, StorageIndex > & b) friend
{
     std::iter_swap(a.keyPtr(), b.keyPtr());
     std::iter_swap(a.valuePtr(), b.valuePtr());
   }
Member Data Documentation
m_innerIndexIterator
template<typename Scalar , typename StorageIndex > StorageIndex* Eigen::internal::StorageRef< Scalar, StorageIndex >::m_innerIndexIterator protected
Referenced by Eigen::internal::StorageRef< Scalar, StorageIndex >::key(), Eigen::internal::StorageRef< Scalar, StorageIndex >::keyPtr(), and Eigen::internal::StorageRef< Scalar, StorageIndex >::operator StorageIndex().
m_valueIterator
template<typename Scalar , typename StorageIndex > Scalar* Eigen::internal::StorageRef< Scalar, StorageIndex >::m_valueIterator protected
Referenced by Eigen::internal::StorageRef< Scalar, StorageIndex >::value(), and Eigen::internal::StorageRef< Scalar, StorageIndex >::valuePtr().
The documentation for this class was generated from the following file:
SparseCompressedBase.h