MercuryDPM: BaseBoundary Class Reference
BaseBoundary Class Reference abstract
#include <BaseBoundary.h>
Public Member Functions
BaseBoundary ()
default constructor.
BaseBoundary (const BaseBoundary &b)
copy constructor
~BaseBoundary () override
destructor
virtual BaseBoundary * copy () const =0
Used to create a copy of the object NB: purely virtual function.
void read (std::istream &is) override=0
Reads the object's id_ from given istream NB: purely virtual function, overriding the version of BaseObject.
void write (std::ostream &os) const override=0
Adds object's id_ to given ostream NB: purely virtual function, overriding the version of BaseObject.
virtual void createPeriodicParticle (BaseParticle *p UNUSED, ParticleHandler &pH UNUSED)
Creates a periodic particle in case of periodic boundaries in serial build.
virtual void createPeriodicParticles (ParticleHandler &pH UNUSED)
Creates periodic copies of given particle in case of periodic boundaries.
virtual void checkBoundaryAfterParticlesMove (ParticleHandler &pH)
Virtual function that does things to particles, each time step after particles have moved.
virtual void checkBoundaryBeforeTimeStep (DPMBase *md)
Virtual function that does things before each time step.
virtual void actionsBeforeTimeLoop ()
Virtual function that does something after DPMBase::setupInitialConditions but before the first time step.
virtual void modifyGhostAfterCreation (BaseParticle *particle, int i)
virtual void writeVTK (std::fstream &file)
void setHandler (BoundaryHandler *handler)
Sets the boundary's BoundaryHandler.
BoundaryHandler * getHandler () const
Returns the boundary's BoundaryHandler.
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual std::string getName () const =0
A purely virtual function.
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Private Attributes
BoundaryHandler * handler_
pointer to the boundary's BoundaryHandler
Detailed Description
Inherits from BaseObject
Constructor & Destructor Documentation
BaseBoundary() [1/2]
BaseBoundary::BaseBoundary ()
default constructor.
Default constructor
 {
     handler_ = nullptr;
     logger(DEBUG, "BaseBoundary::BaseBoundary() finished");
 }
References DEBUG, handler_, and logger.
BaseBoundary() [2/2]
BaseBoundary::BaseBoundary (const BaseBoundary & b)
copy constructor
Note: shallow copy! Otherwise the HGrid causes a stack overflow.
Copy constructor
         : BaseObject(b)
 {
     handler_ = b.handler_;
     logger(DEBUG, "BaseBoundary::BaseBoundary(const BaseBoundary &b) finished");
 }
References b, DEBUG, handler_, and logger.
~BaseBoundary()
BaseBoundary::~BaseBoundary () override
destructor
Destructor
 {
     logger(DEBUG, "BaseBoundary::~BaseBoundary() finished");
 }
References DEBUG, and logger.
Member Function Documentation
actionsBeforeTimeLoop()
void BaseBoundary::actionsBeforeTimeLoop () virtual
Virtual function that does something after DPMBase::setupInitialConditions but before the first time step.
Can be used to perform actions before the time loop, but after setupInitialConditions.
Reimplemented in SubcriticalMaserBoundaryTEST, SubcriticalMaserBoundary, DropletBoundary, and ConstantMassFlowMaserBoundary.
 {
     logger(VERBOSE, "In BaseBoundary::checkBoundaryBeforeTimeLoop\n");
 }
References logger, and VERBOSE.
checkBoundaryAfterParticlesMove()
void BaseBoundary::checkBoundaryAfterParticlesMove (ParticleHandler & pH) virtual
Virtual function that does things to particles, each time step after particles have moved.
checks whether given particle passed the boundary, and if so, does something special with it. This is called after the particles moved, but before the force-computation. NB: virtual function
Parameters
[in] P Particle checked
[out] pH the particle handler.
Returns
returns TRUE if given particle actually did pass the boundary
Reimplemented in TimeDependentPeriodicBoundary, SubcriticalMaserBoundaryTEST, SubcriticalMaserBoundary, PeriodicBoundary, LeesEdwardsBoundary, HeaterBoundary, FluxBoundary, DropletBoundary, DeletionBoundary, ConstantMassFlowMaserBoundary, CircularPeriodicBoundary, BasePeriodicBoundary, AngledPeriodicBoundary, and StressStrainControlBoundary.
 {
 }
checkBoundaryBeforeTimeStep()
void BaseBoundary::checkBoundaryBeforeTimeStep (DPMBase * md) virtual
Virtual function that does things before each time step.
What this does depends on the type of boundary. For example, an InsertionBoundary introduces new particles (and how it does that in turn depends on the type of InsertionBoundary).
Parameters
[in] md the problem's DPMBase object
Reimplemented in RandomClusterInsertionBoundary, InsertionBoundary, BaseClusterInsertionBoundary, and FixedClusterInsertionBoundary.
 {
 }
copy()
virtual BaseBoundary* BaseBoundary::copy () const pure virtual
Used to create a copy of the object NB: purely virtual function.
Implemented in BasePeriodicBoundary, TimeDependentPeriodicBoundary, SubcriticalMaserBoundaryTEST, SubcriticalMaserBoundary, StressStrainControlBoundary, SphereInsertionBoundary, ShearBoxBoundary, RandomClusterInsertionBoundary, PolydisperseInsertionBoundary, PeriodicBoundary, LeesEdwardsBoundary, HopperInsertionBoundary, HeaterBoundary, FluxBoundary, FixedClusterInsertionBoundary, DropletBoundary, DeletionBoundary, CylinderInsertionBoundary, CubeInsertionBoundary, CubeDeletionBoundary, ConstantMassFlowMaserBoundary, CircularPeriodicBoundary, ChuteInsertionBoundary, BidisperseCubeInsertionBoundary, BaseClusterInsertionBoundary, and AngledPeriodicBoundary.
createPeriodicParticle()
void BaseBoundary::createPeriodicParticle (BaseParticle *p UNUSED, ParticleHandler &pH UNUSED) virtual
Creates a periodic particle in case of periodic boundaries in serial build.
Used to create a single periodic copy of a particle in classes which implement periodic boundary conditions
Parameters
[in] p particle of which periodic copies are to be created
[in] pH the particle handler
 {
 }
createPeriodicParticles()
void BaseBoundary::createPeriodicParticles (ParticleHandler &pH UNUSED) virtual
Creates periodic copies of given particle in case of periodic boundaries.
Used to create periodic copies of particles in classes which implement periodic boundary conditions NB: virtual function
Parameters
[in] pH the particle handler
 {
 }
getHandler()
BoundaryHandler * BaseBoundary::getHandler () const
Returns the boundary's BoundaryHandler.
Returns the pointer to the BoundaryHandler the boundary belongs to
Returns
pointer to the handler
 {
     return handler_;
 }
References handler_.
Referenced by DropletBoundary::actionsBeforeTimeLoop(), SubcriticalMaserBoundaryTEST::actionsBeforeTimeLoop(), ConstantMassFlowMaserBoundary::activateMaser(), SubcriticalMaserBoundary::activateMaser(), SubcriticalMaserBoundaryTEST::activateMaser(), StressStrainControlBoundary::activateStrainRateControl(), ConstantMassFlowMaserBoundary::addParticleToMaser(), SubcriticalMaserBoundary::addParticleToMaser(), DeletionBoundary::checkBoundaryAfterParticleMoved(), StressStrainControlBoundary::checkBoundaryAfterParticlesMove(), DropletBoundary::checkBoundaryAfterParticlesMove(), FluxBoundary::checkBoundaryAfterParticlesMove(), PeriodicBoundary::checkBoundaryAfterParticlesMove(), SubcriticalMaserBoundaryTEST::checkBoundaryAfterParticlesMove(), ConstantMassFlowMaserBoundary::closeMaser(), StressStrainControlBoundary::computeStrainRate(), StressStrainControlBoundary::computeStressError(), SubcriticalMaserBoundaryTEST::copyExtraParticles(), PeriodicBoundary::createGhostParticle(), TimeDependentPeriodicBoundary::createGhostParticle(), SubcriticalMaserBoundary::deactivateMaser(), SubcriticalMaserBoundaryTEST::deactivateMaser(), StressStrainControlBoundary::determineStressControlledShearBoundaries(), SubcriticalMaserBoundaryTEST::extendBottom(), InsertionBoundary::generateParticle(), LeesEdwardsBoundary::getCurrentShift(), LeesEdwardsBoundary::getCurrentVelocity(), SubcriticalMaserBoundaryTEST::performActionsBeforeAddingParticles(), ConstantMassFlowMaserBoundary::read(), InsertionBoundary::read(), SubcriticalMaserBoundary::read(), StressStrainControlBoundary::set(), InsertionBoundary::setVariableVolumeFlowRate(), ShearBoxBoundary::shiftHorizontalPosition(), LeesEdwardsBoundary::shiftVerticalPosition(), StressStrainControlBoundary::updateDomainSize(), and LeesEdwardsBoundary::write().
modifyGhostAfterCreation()
void BaseBoundary::modifyGhostAfterCreation (BaseParticle * particle, int i) virtual
Reimplemented in SubcriticalMaserBoundaryTEST.
 {
 }
read()
void BaseBoundary::read (std::istream & is) override pure virtual
Reads the object's id_ from given istream NB: purely virtual function, overriding the version of BaseObject.
Reads the object's id_ from the given istream
Parameters
[in,out] is istream the id_ is read from
Implements BaseObject.
Implemented in TimeDependentPeriodicBoundary, SubcriticalMaserBoundaryTEST, SubcriticalMaserBoundary, StressStrainControlBoundary, SphereInsertionBoundary, ShearBoxBoundary, PolydisperseInsertionBoundary, PeriodicBoundary, LeesEdwardsBoundary, InsertionBoundary, HopperInsertionBoundary, HeaterBoundary, FluxBoundary, DropletBoundary, DeletionBoundary, CylinderInsertionBoundary, CubeInsertionBoundary, CubeDeletionBoundary, ConstantMassFlowMaserBoundary, CircularPeriodicBoundary, ChuteInsertionBoundary, BidisperseCubeInsertionBoundary, BasePeriodicBoundary, BaseClusterInsertionBoundary, and AngledPeriodicBoundary.
 {
     BaseObject::read(is);
 }
References BaseObject::read().
Referenced by AngledPeriodicBoundary::read(), BasePeriodicBoundary::read(), CircularPeriodicBoundary::read(), ConstantMassFlowMaserBoundary::read(), DeletionBoundary::read(), DropletBoundary::read(), FluxBoundary::read(), HeaterBoundary::read(), InsertionBoundary::read(), LeesEdwardsBoundary::read(), ShearBoxBoundary::read(), StressStrainControlBoundary::read(), and SubcriticalMaserBoundary::read().
setHandler()
void BaseBoundary::setHandler (BoundaryHandler * handler)
Sets the boundary's BoundaryHandler.
Sets the pointer to the BounadaryHandler the boundary belongs to
Parameters
[in] handler pointer to the boundary handler
 {
     handler_ = handler;
 }
References handler_.
Referenced by GranuDrum::GranuDrum(), BoundaryHandler::readAndAddObject(), StressStrainControlBoundary::set(), and StressStrainControl::setupInitialConditions().
write()
void BaseBoundary::write (std::ostream & os) const override pure virtual
Adds object's id_ to given ostream NB: purely virtual function, overriding the version of BaseObject.
Adds the object's id_ to the given ostream
Parameters
[in] os ostream the id_ is added to
Implements BaseObject.
Implemented in TimeDependentPeriodicBoundary, SubcriticalMaserBoundaryTEST, SubcriticalMaserBoundary, StressStrainControlBoundary, SphereInsertionBoundary, ShearBoxBoundary, PolydisperseInsertionBoundary, PeriodicBoundary, LeesEdwardsBoundary, InsertionBoundary, HopperInsertionBoundary, HeaterBoundary, FluxBoundary, DropletBoundary, DeletionBoundary, CylinderInsertionBoundary, CubeInsertionBoundary, CubeDeletionBoundary, ConstantMassFlowMaserBoundary, CircularPeriodicBoundary, ChuteInsertionBoundary, BidisperseCubeInsertionBoundary, BasePeriodicBoundary, BaseClusterInsertionBoundary, and AngledPeriodicBoundary.
 {
     BaseObject::write(os);
 }
References BaseObject::write().
Referenced by AngledPeriodicBoundary::write(), BasePeriodicBoundary::write(), CircularPeriodicBoundary::write(), ConstantMassFlowMaserBoundary::write(), DeletionBoundary::write(), DropletBoundary::write(), FluxBoundary::write(), HeaterBoundary::write(), InsertionBoundary::write(), LeesEdwardsBoundary::write(), ShearBoxBoundary::write(), StressStrainControlBoundary::write(), and SubcriticalMaserBoundary::write().
writeVTK()
virtual void BaseBoundary::writeVTK (std::fstream & file) inline virtual
Reimplemented in DropletBoundary.
 {}
Member Data Documentation
handler_
BoundaryHandler* BaseBoundary::handler_ private
pointer to the boundary's BoundaryHandler
Referenced by BaseBoundary(), getHandler(), and setHandler().
The documentation for this class was generated from the following files:
BaseBoundary.h
BaseBoundary.cc