MercuryDPM: Eigen::IterativeSolverBase< Derived > Class Template Reference
Eigen::IterativeSolverBase< Derived > Class Template Reference
Sparse linear algebra » Reference » IterativeLinearSolvers_Module
Base class for linear iterative solvers.
#include <IterativeSolverBase.h>
Public Types
enum { ColsAtCompileTime = MatrixType::ColsAtCompileTime , MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime }
typedef internal::traits< Derived >::MatrixType MatrixType
typedef internal::traits< Derived >::Preconditioner Preconditioner
typedef MatrixType::Scalar Scalar
typedef MatrixType::StorageIndex StorageIndex
typedef MatrixType::RealScalar RealScalar
Public Member Functions
IterativeSolverBase ()
template<typename MatrixDerived >
IterativeSolverBase (const EigenBase< MatrixDerived > &A)
IterativeSolverBase (IterativeSolverBase &&)=default
~IterativeSolverBase ()
template<typename MatrixDerived >
Derived & analyzePattern (const EigenBase< MatrixDerived > &A)
template<typename MatrixDerived >
Derived & factorize (const EigenBase< MatrixDerived > &A)
template<typename MatrixDerived >
Derived & compute (const EigenBase< MatrixDerived > &A)
EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
RealScalar tolerance () const
Derived & setTolerance (const RealScalar &tolerance)
Preconditioner & preconditioner ()
const Preconditioner & preconditioner () const
Index maxIterations () const
Derived & setMaxIterations (Index maxIters)
Index iterations () const
RealScalar error () const
template<typename Rhs , typename Guess >
const SolveWithGuess< Derived, Rhs, Guess > solveWithGuess (const MatrixBase< Rhs > &b, const Guess &x0) const
ComputationInfo info () const
template<typename Rhs , typename DestDerived >
void _solve_with_guess_impl (const Rhs &b, SparseMatrixBase< DestDerived > &aDest) const
template<typename Rhs , typename DestDerived >
std::enable_if_t< Rhs::ColsAtCompileTime !=1 &&DestDerived::ColsAtCompileTime !=1 > _solve_with_guess_impl (const Rhs &b, MatrixBase< DestDerived > &aDest) const
template<typename Rhs , typename DestDerived >
std::enable_if_t< Rhs::ColsAtCompileTime==1||DestDerived::ColsAtCompileTime==1 > _solve_with_guess_impl (const Rhs &b, MatrixBase< DestDerived > &dest) const
template<typename Rhs , typename Dest >
void _solve_impl (const Rhs &b, Dest &x) const
Derived & derived ()
const Derived & derived () const
Public Member Functions inherited from Eigen::SparseSolverBase< Derived >
SparseSolverBase ()
SparseSolverBase (SparseSolverBase &&other)
~SparseSolverBase ()
Derived & derived ()
const Derived & derived () const
template<typename Rhs >
const Solve< Derived, Rhs > solve (const MatrixBase< Rhs > &b) const
template<typename Rhs >
const Solve< Derived, Rhs > solve (const SparseMatrixBase< Rhs > &b) const
template<typename Rhs , typename Dest >
void _solve_impl (const SparseMatrixBase< Rhs > &b, SparseMatrixBase< Dest > &dest) const
Protected Types
typedef SparseSolverBase< Derived > Base
typedef internal::generic_matrix_wrapper< MatrixType > MatrixWrapper
typedef MatrixWrapper::ActualMatrixType ActualMatrixType
Protected Member Functions
void init ()
const ActualMatrixType & matrix () const
template<typename InputType >
void grab (const InputType &A)
Protected Attributes
MatrixWrapper m_matrixWrapper
Preconditioner m_preconditioner
Index m_maxIterations
RealScalar m_tolerance
RealScalar m_error
Index m_iterations
ComputationInfo m_info
bool m_analysisIsOk
bool m_factorizationIsOk
bool m_isInitialized
Protected Attributes inherited from Eigen::SparseSolverBase< Derived >
bool m_isInitialized
Detailed Description
template<typename Derived>
class Eigen::IterativeSolverBase< Derived >
Base class for linear iterative solvers.
See also
class SimplicialCholesky, DiagonalPreconditioner, IdentityPreconditioner
Member Typedef Documentation
ActualMatrixType
template<typename Derived > typedef MatrixWrapper::ActualMatrixType Eigen::IterativeSolverBase< Derived >::ActualMatrixType protected
Base
template<typename Derived > typedef SparseSolverBase<Derived> Eigen::IterativeSolverBase< Derived >::Base protected
MatrixType
template<typename Derived > typedef internal::traits<Derived>::MatrixType Eigen::IterativeSolverBase< Derived >::MatrixType
MatrixWrapper
template<typename Derived > typedef internal::generic_matrix_wrapper<MatrixType> Eigen::IterativeSolverBase< Derived >::MatrixWrapper protected
Preconditioner
template<typename Derived > typedef internal::traits<Derived>::Preconditioner Eigen::IterativeSolverBase< Derived >::Preconditioner
RealScalar
template<typename Derived > typedef MatrixType::RealScalar Eigen::IterativeSolverBase< Derived >::RealScalar
Scalar
template<typename Derived > typedef MatrixType::Scalar Eigen::IterativeSolverBase< Derived >::Scalar
StorageIndex
template<typename Derived > typedef MatrixType::StorageIndex Eigen::IterativeSolverBase< Derived >::StorageIndex
Member Enumeration Documentation
anonymous enum
template<typename Derived > anonymous enum
Enumerator
ColsAtCompileTime
MaxColsAtCompileTime
 { ColsAtCompileTime = MatrixType::ColsAtCompileTime, MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime };
Constructor & Destructor Documentation
IterativeSolverBase() [1/3]
template<typename Derived > Eigen::IterativeSolverBase< Derived >::IterativeSolverBase () inline
Default constructor.
 { init(); }
References Eigen::IterativeSolverBase< Derived >::init().
IterativeSolverBase() [2/3]
template<typename Derived > template<typename MatrixDerived > Eigen::IterativeSolverBase< Derived >::IterativeSolverBase (const EigenBase< MatrixDerived > & A) inline explicit
Initialize the solver with matrix A for further Ax=b solving.
This constructor is a shortcut for the default constructor followed by a call to compute().
Warning
this class stores a reference to the matrix A as well as some precomputed values that depend on it. Therefore, if A is changed this class becomes invalid. Call compute() to update it with the new matrix A, or modify a copy of A.
                                                                   : m_matrixWrapper(A.derived()) {
     init();
     compute(matrix());
   }
References Eigen::IterativeSolverBase< Derived >::compute(), Eigen::IterativeSolverBase< Derived >::init(), and Eigen::IterativeSolverBase< Derived >::matrix().
IterativeSolverBase() [3/3]
template<typename Derived > Eigen::IterativeSolverBase< Derived >::IterativeSolverBase (IterativeSolverBase< Derived > &&) default
~IterativeSolverBase()
template<typename Derived > Eigen::IterativeSolverBase< Derived >::~IterativeSolverBase () inline
 {}
Member Function Documentation
_solve_impl()
template<typename Derived > template<typename Rhs , typename Dest > void Eigen::IterativeSolverBase< Derived >::_solve_impl (const Rhs & b, Dest & x) const inline
default initial guess = 0
{
     x.setZero();
     derived()._solve_with_guess_impl(b, x);
   }
References b, Eigen::IterativeSolverBase< Derived >::derived(), and plotDoE::x.
_solve_with_guess_impl() [1/3]
template<typename Derived > template<typename Rhs , typename DestDerived > std::enable_if_t<Rhs::ColsAtCompileTime != 1 && DestDerived::ColsAtCompileTime != 1> Eigen::IterativeSolverBase< Derived >::_solve_with_guess_impl (const Rhs & b, MatrixBase< DestDerived > & aDest) const inline
{
     eigen_assert(rows() == b.rows());
     Index rhsCols = b.cols();
     DestDerived& dest(aDest.derived());
     ComputationInfo global_info = Success;
     for (Index k = 0; k < rhsCols; ++k) {
       typename DestDerived::ColXpr xk(dest, k);
       typename Rhs::ConstColXpr bk(b, k);
       derived()._solve_vector_with_guess_impl(bk, xk);
       // The call to _solve_vector_with_guess updates m_info, so if it failed for a previous column
       // we need to restore it to the worst value.
       if (m_info == NumericalIssue)
         global_info = NumericalIssue;
       else if (m_info == NoConvergence)
         global_info = NoConvergence;
     }
     m_info = global_info;
   }
References b, Eigen::IterativeSolverBase< Derived >::derived(), eigen_assert, k, Eigen::IterativeSolverBase< Derived >::m_info, Eigen::NoConvergence, Eigen::NumericalIssue, Eigen::IterativeSolverBase< Derived >::rows(), and Eigen::Success.
_solve_with_guess_impl() [2/3]
template<typename Derived > template<typename Rhs , typename DestDerived > std::enable_if_t<Rhs::ColsAtCompileTime == 1 || DestDerived::ColsAtCompileTime == 1> Eigen::IterativeSolverBase< Derived >::_solve_with_guess_impl (const Rhs & b, MatrixBase< DestDerived > & dest) const inline
{
     derived()._solve_vector_with_guess_impl(b, dest.derived());
   }
References b, and Eigen::IterativeSolverBase< Derived >::derived().
_solve_with_guess_impl() [3/3]
template<typename Derived > template<typename Rhs , typename DestDerived > void Eigen::IterativeSolverBase< Derived >::_solve_with_guess_impl (const Rhs & b, SparseMatrixBase< DestDerived > & aDest) const inline
{
     eigen_assert(rows() == b.rows());
     Index rhsCols = b.cols();
     Index size = b.rows();
     DestDerived& dest(aDest.derived());
     typedef typename DestDerived::Scalar DestScalar;
     Eigen::Matrix<DestScalar, Dynamic, 1> tb(size);
     Eigen::Matrix<DestScalar, Dynamic, 1> tx(cols());
     // We do not directly fill dest because sparse expressions have to be free of aliasing issue.
     // For non square least-square problems, b and dest might not have the same size whereas they might alias
     // each-other.
     typename DestDerived::PlainObject tmp(cols(), rhsCols);
     ComputationInfo global_info = Success;
     for (Index k = 0; k < rhsCols; ++k) {
       tb = b.col(k);
       tx = dest.col(k);
       derived()._solve_vector_with_guess_impl(tb, tx);
       tmp.col(k) = tx.sparseView(0);
       // The call to _solve_vector_with_guess_impl updates m_info, so if it failed for a previous column
       // we need to restore it to the worst value.
       if (m_info == NumericalIssue)
         global_info = NumericalIssue;
       else if (m_info == NoConvergence)
         global_info = NoConvergence;
     }
     m_info = global_info;
     dest.swap(tmp);
   }
References b, Eigen::IterativeSolverBase< Derived >::cols(), Eigen::IterativeSolverBase< Derived >::derived(), Eigen::SparseMatrixBase< Derived >::derived(), eigen_assert, k, Eigen::IterativeSolverBase< Derived >::m_info, Eigen::NoConvergence, Eigen::NumericalIssue, Eigen::IterativeSolverBase< Derived >::rows(), size, Eigen::Success, and tmp.
analyzePattern()
template<typename Derived > template<typename MatrixDerived > Derived& Eigen::IterativeSolverBase< Derived >::analyzePattern (const EigenBase< MatrixDerived > & A) inline
Initializes the iterative solver for the sparsity pattern of the matrix A for further solving Ax=b problems.
Currently, this function mostly calls analyzePattern on the preconditioner. In the future we might, for instance, implement column reordering for faster matrix vector products.
{
     grab(A.derived());
     m_preconditioner.analyzePattern(matrix());
     m_isInitialized = true;
     m_analysisIsOk = true;
     m_info = m_preconditioner.info();
     return derived();
   }
References Eigen::IterativeSolverBase< Derived >::derived(), Eigen::IterativeSolverBase< Derived >::grab(), Eigen::IterativeSolverBase< Derived >::m_analysisIsOk, Eigen::IterativeSolverBase< Derived >::m_info, Eigen::IterativeSolverBase< Derived >::m_isInitialized, Eigen::IterativeSolverBase< Derived >::m_preconditioner, and Eigen::IterativeSolverBase< Derived >::matrix().
cols()
template<typename Derived > EIGEN_CONSTEXPR Index Eigen::IterativeSolverBase< Derived >::cols () const inline
 { return matrix().cols(); }
References Eigen::IterativeSolverBase< Derived >::matrix().
Referenced by gdb.printers._MatrixEntryIterator::__next__(), Eigen::IterativeSolverBase< Derived >::_solve_with_guess_impl(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
compute()
template<typename Derived > template<typename MatrixDerived > Derived& Eigen::IterativeSolverBase< Derived >::compute (const EigenBase< MatrixDerived > & A) inline
Initializes the iterative solver with the matrix A for further solving Ax=b problems.
Currently, this function mostly initializes/computes the preconditioner. In the future we might, for instance, implement column reordering for faster matrix vector products.
Warning
this class stores a reference to the matrix A as well as some precomputed values that depend on it. Therefore, if A is changed this class becomes invalid. Call compute() to update it with the new matrix A, or modify a copy of A.
{
     grab(A.derived());
     m_preconditioner.compute(matrix());
     m_isInitialized = true;
     m_analysisIsOk = true;
     m_factorizationIsOk = true;
     m_info = m_preconditioner.info();
     return derived();
   }
References Eigen::IterativeSolverBase< Derived >::derived(), Eigen::IterativeSolverBase< Derived >::grab(), Eigen::IterativeSolverBase< Derived >::m_analysisIsOk, Eigen::IterativeSolverBase< Derived >::m_factorizationIsOk, Eigen::IterativeSolverBase< Derived >::m_info, Eigen::IterativeSolverBase< Derived >::m_isInitialized, Eigen::IterativeSolverBase< Derived >::m_preconditioner, and Eigen::IterativeSolverBase< Derived >::matrix().
Referenced by Eigen::IterativeSolverBase< Derived >::IterativeSolverBase(), and main().
derived() [1/2]
template<typename Derived > Derived& Eigen::SparseSolverBase< Derived >::derived inline
 { return *static_cast<Derived*>(this); }
Referenced by Eigen::IterativeSolverBase< Derived >::_solve_impl(), Eigen::IterativeSolverBase< Derived >::_solve_with_guess_impl(), Eigen::IterativeSolverBase< Derived >::analyzePattern(), Eigen::IterativeSolverBase< Derived >::compute(), Eigen::IterativeSolverBase< Derived >::factorize(), Eigen::IterativeSolverBase< Derived >::setMaxIterations(), Eigen::IterativeSolverBase< Derived >::setTolerance(), and Eigen::IterativeSolverBase< Derived >::solveWithGuess().
derived() [2/2]
template<typename Derived > const Derived& Eigen::SparseSolverBase< Derived >::derived inline
 { return *static_cast<const Derived*>(this); }
error()
template<typename Derived > RealScalar Eigen::IterativeSolverBase< Derived >::error () const inline
Returns
the tolerance error reached during the last solve. It is a close approximation of the true relative residual error |Ax-b|/|b|.
{
     eigen_assert(m_isInitialized && "IterativeSolverBase is not initialized.");
     return m_error;
   }
References eigen_assert, Eigen::IterativeSolverBase< Derived >::m_error, and Eigen::IterativeSolverBase< Derived >::m_isInitialized.
Referenced by main().
factorize()
template<typename Derived > template<typename MatrixDerived > Derived& Eigen::IterativeSolverBase< Derived >::factorize (const EigenBase< MatrixDerived > & A) inline
Initializes the iterative solver with the numerical values of the matrix A for further solving Ax=b problems.
Currently, this function mostly calls factorize on the preconditioner.
Warning
this class stores a reference to the matrix A as well as some precomputed values that depend on it. Therefore, if A is changed this class becomes invalid. Call compute() to update it with the new matrix A, or modify a copy of A.
{
     eigen_assert(m_analysisIsOk && "You must first call analyzePattern()");
     grab(A.derived());
     m_preconditioner.factorize(matrix());
     m_factorizationIsOk = true;
     m_info = m_preconditioner.info();
     return derived();
   }
References Eigen::IterativeSolverBase< Derived >::derived(), eigen_assert, Eigen::IterativeSolverBase< Derived >::grab(), Eigen::IterativeSolverBase< Derived >::m_analysisIsOk, Eigen::IterativeSolverBase< Derived >::m_factorizationIsOk, Eigen::IterativeSolverBase< Derived >::m_info, Eigen::IterativeSolverBase< Derived >::m_preconditioner, and Eigen::IterativeSolverBase< Derived >::matrix().
grab()
template<typename Derived > template<typename InputType > void Eigen::IterativeSolverBase< Derived >::grab (const InputType & A) inline protected
{
     m_matrixWrapper.grab(A);
   }
References Eigen::IterativeSolverBase< Derived >::m_matrixWrapper.
Referenced by Eigen::IterativeSolverBase< Derived >::analyzePattern(), Eigen::IterativeSolverBase< Derived >::compute(), and Eigen::IterativeSolverBase< Derived >::factorize().
info()
template<typename Derived > ComputationInfo Eigen::IterativeSolverBase< Derived >::info () const inline
Returns
Success if the iterations converged, and NoConvergence otherwise.
{
     eigen_assert(m_isInitialized && "IterativeSolverBase is not initialized.");
     return m_info;
   }
References eigen_assert, Eigen::IterativeSolverBase< Derived >::m_info, and Eigen::IterativeSolverBase< Derived >::m_isInitialized.
init()
template<typename Derived > void Eigen::IterativeSolverBase< Derived >::init () inline protected
               {
     m_isInitialized = false;
     m_analysisIsOk = false;
     m_factorizationIsOk = false;
     m_maxIterations = -1;
     m_tolerance = NumTraits<Scalar>::epsilon();
   }
References oomph::SarahBL::epsilon, Eigen::IterativeSolverBase< Derived >::m_analysisIsOk, Eigen::IterativeSolverBase< Derived >::m_factorizationIsOk, Eigen::IterativeSolverBase< Derived >::m_isInitialized, Eigen::IterativeSolverBase< Derived >::m_maxIterations, and Eigen::IterativeSolverBase< Derived >::m_tolerance.
Referenced by Eigen::IterativeSolverBase< Derived >::IterativeSolverBase().
iterations()
template<typename Derived > Index Eigen::IterativeSolverBase< Derived >::iterations () const inline
Returns
the number of iterations performed during the last solve
{
     eigen_assert(m_isInitialized && "IterativeSolverBase is not initialized.");
     return m_iterations;
   }
References eigen_assert, Eigen::IterativeSolverBase< Derived >::m_isInitialized, and Eigen::IterativeSolverBase< Derived >::m_iterations.
Referenced by main().
matrix()
template<typename Derived > const ActualMatrixType& Eigen::IterativeSolverBase< Derived >::matrix () const inline protected
 { return m_matrixWrapper.matrix(); }
References Eigen::IterativeSolverBase< Derived >::m_matrixWrapper.
Referenced by Eigen::IterativeSolverBase< Derived >::analyzePattern(), Eigen::IterativeSolverBase< Derived >::cols(), Eigen::IterativeSolverBase< Derived >::compute(), Eigen::IterativeSolverBase< Derived >::factorize(), Eigen::IterativeSolverBase< Derived >::IterativeSolverBase(), Eigen::IterativeSolverBase< Derived >::maxIterations(), and Eigen::IterativeSolverBase< Derived >::rows().
maxIterations()
template<typename Derived > Index Eigen::IterativeSolverBase< Derived >::maxIterations () const inline
Returns
the max number of iterations. It is either the value set by setMaxIterations or, by default, twice the number of columns of the matrix.
 { return (m_maxIterations < 0) ? 2 * matrix().cols() : m_maxIterations; }
References Eigen::IterativeSolverBase< Derived >::m_maxIterations, and Eigen::IterativeSolverBase< Derived >::matrix().
Referenced by Eigen::BiCGSTAB< MatrixType_, Preconditioner_ >::_solve_vector_with_guess_impl(), Eigen::ConjugateGradient< MatrixType_, UpLo_, Preconditioner_ >::_solve_vector_with_guess_impl(), Eigen::LeastSquaresConjugateGradient< MatrixType_, Preconditioner_ >::_solve_vector_with_guess_impl(), Eigen::BiCGSTABL< MatrixType_, Preconditioner_ >::_solve_vector_with_guess_impl(), Eigen::DGMRES< MatrixType_, Preconditioner_ >::_solve_vector_with_guess_impl(), Eigen::GMRES< MatrixType_, Preconditioner_ >::_solve_vector_with_guess_impl(), Eigen::IDRS< MatrixType_, Preconditioner_ >::_solve_vector_with_guess_impl(), Eigen::IDRSTABL< MatrixType_, Preconditioner_ >::_solve_vector_with_guess_impl(), and Eigen::MINRES< MatrixType_, UpLo_, Preconditioner_ >::_solve_vector_with_guess_impl().
preconditioner() [1/2]
template<typename Derived > Preconditioner& Eigen::IterativeSolverBase< Derived >::preconditioner () inline
Returns
a read-write reference to the preconditioner for custom configuration.
 { return m_preconditioner; }
References Eigen::IterativeSolverBase< Derived >::m_preconditioner.
preconditioner() [2/2]
template<typename Derived > const Preconditioner& Eigen::IterativeSolverBase< Derived >::preconditioner () const inline
Returns
a read-only reference to the preconditioner.
 { return m_preconditioner; }
References Eigen::IterativeSolverBase< Derived >::m_preconditioner.
rows()
template<typename Derived > EIGEN_CONSTEXPR Index Eigen::IterativeSolverBase< Derived >::rows () const inline
 { return matrix().rows(); }
References Eigen::IterativeSolverBase< Derived >::matrix().
Referenced by gdb.printers._MatrixEntryIterator::__next__(), Eigen::IterativeSolverBase< Derived >::_solve_with_guess_impl(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), Eigen::IterativeSolverBase< Derived >::solveWithGuess(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
setMaxIterations()
template<typename Derived > Derived& Eigen::IterativeSolverBase< Derived >::setMaxIterations (Index maxIters) inline
Sets the max number of iterations. Default is twice the number of columns of the matrix.
{
     m_maxIterations = maxIters;
     return derived();
   }
References Eigen::IterativeSolverBase< Derived >::derived(), and Eigen::IterativeSolverBase< Derived >::m_maxIterations.
setTolerance()
template<typename Derived > Derived& Eigen::IterativeSolverBase< Derived >::setTolerance (const RealScalar & tolerance) inline
Sets the tolerance threshold used by the stopping criteria.
This value is used as an upper bound to the relative residual error: |Ax-b|/|b|. The default value is the machine precision given by NumTraits<Scalar>::epsilon()
{
     m_tolerance = tolerance;
     return derived();
   }
References Eigen::IterativeSolverBase< Derived >::derived(), Eigen::IterativeSolverBase< Derived >::m_tolerance, and Eigen::IterativeSolverBase< Derived >::tolerance().
Referenced by test_bicgstab_T(), test_bicgstabl_T(), and test_idrstabl_T().
solveWithGuess()
template<typename Derived > template<typename Rhs , typename Guess > const SolveWithGuess<Derived, Rhs, Guess> Eigen::IterativeSolverBase< Derived >::solveWithGuess (const MatrixBase< Rhs > & b, const Guess & x0) const inline
Returns
the solution x of \(A x = b \) using the current decomposition of A and x0 as an initial solution.
See also
solve(), compute()
{
     eigen_assert(m_isInitialized && "Solver is not initialized.");
     eigen_assert(derived().rows() == b.rows() && "solve(): invalid number of rows of the right hand side matrix b");
     return SolveWithGuess<Derived, Rhs, Guess>(derived(), b.derived(), x0);
   }
References b, Eigen::IterativeSolverBase< Derived >::derived(), eigen_assert, Eigen::IterativeSolverBase< Derived >::m_isInitialized, Eigen::IterativeSolverBase< Derived >::rows(), and Global::x0.
tolerance()
template<typename Derived > RealScalar Eigen::IterativeSolverBase< Derived >::tolerance () const inline
Returns
the tolerance threshold used by the stopping criteria.
See also
setTolerance()
 { return m_tolerance; }
References Eigen::IterativeSolverBase< Derived >::m_tolerance.
Referenced by Eigen::IterativeSolverBase< Derived >::setTolerance().
Member Data Documentation
m_analysisIsOk
template<typename Derived > bool Eigen::IterativeSolverBase< Derived >::m_analysisIsOk mutable protected
Referenced by Eigen::IterativeSolverBase< Derived >::analyzePattern(), Eigen::IterativeSolverBase< Derived >::compute(), Eigen::IterativeSolverBase< Derived >::factorize(), and Eigen::IterativeSolverBase< Derived >::init().
m_error
template<typename Derived > RealScalar Eigen::IterativeSolverBase< Derived >::m_error mutable protected
Referenced by Eigen::IterativeSolverBase< Derived >::error().
m_factorizationIsOk
template<typename Derived > bool Eigen::IterativeSolverBase< Derived >::m_factorizationIsOk protected
Referenced by Eigen::IterativeSolverBase< Derived >::compute(), Eigen::IterativeSolverBase< Derived >::factorize(), and Eigen::IterativeSolverBase< Derived >::init().
m_info
template<typename Derived > ComputationInfo Eigen::IterativeSolverBase< Derived >::m_info mutable protected
Referenced by Eigen::IterativeSolverBase< Derived >::_solve_with_guess_impl(), Eigen::IterativeSolverBase< Derived >::analyzePattern(), Eigen::IterativeSolverBase< Derived >::compute(), Eigen::IterativeSolverBase< Derived >::factorize(), and Eigen::IterativeSolverBase< Derived >::info().
m_isInitialized
template<typename Derived > bool Eigen::SparseSolverBase< Derived >::m_isInitialized mutable protected
Referenced by Eigen::IterativeSolverBase< Derived >::analyzePattern(), Eigen::IterativeSolverBase< Derived >::compute(), Eigen::IterativeSolverBase< Derived >::error(), Eigen::IterativeSolverBase< Derived >::info(), Eigen::IterativeSolverBase< Derived >::init(), Eigen::IterativeSolverBase< Derived >::iterations(), and Eigen::IterativeSolverBase< Derived >::solveWithGuess().
m_iterations
template<typename Derived > Index Eigen::IterativeSolverBase< Derived >::m_iterations mutable protected
Referenced by Eigen::IterativeSolverBase< Derived >::iterations().
m_matrixWrapper
template<typename Derived > MatrixWrapper Eigen::IterativeSolverBase< Derived >::m_matrixWrapper protected
Referenced by Eigen::IterativeSolverBase< Derived >::grab(), and Eigen::IterativeSolverBase< Derived >::matrix().
m_maxIterations
template<typename Derived > Index Eigen::IterativeSolverBase< Derived >::m_maxIterations protected
Referenced by Eigen::IterativeSolverBase< Derived >::init(), Eigen::IterativeSolverBase< Derived >::maxIterations(), and Eigen::IterativeSolverBase< Derived >::setMaxIterations().
m_preconditioner
template<typename Derived > Preconditioner Eigen::IterativeSolverBase< Derived >::m_preconditioner protected
Referenced by Eigen::BiCGSTAB< MatrixType_, Preconditioner_ >::_solve_vector_with_guess_impl(), Eigen::ConjugateGradient< MatrixType_, UpLo_, Preconditioner_ >::_solve_vector_with_guess_impl(), Eigen::LeastSquaresConjugateGradient< MatrixType_, Preconditioner_ >::_solve_vector_with_guess_impl(), Eigen::BiCGSTABL< MatrixType_, Preconditioner_ >::_solve_vector_with_guess_impl(), Eigen::DGMRES< MatrixType_, Preconditioner_ >::_solve_vector_with_guess_impl(), Eigen::GMRES< MatrixType_, Preconditioner_ >::_solve_vector_with_guess_impl(), Eigen::IDRS< MatrixType_, Preconditioner_ >::_solve_vector_with_guess_impl(), Eigen::IDRSTABL< MatrixType_, Preconditioner_ >::_solve_vector_with_guess_impl(), Eigen::MINRES< MatrixType_, UpLo_, Preconditioner_ >::_solve_vector_with_guess_impl(), Eigen::IterativeSolverBase< Derived >::analyzePattern(), Eigen::IterativeSolverBase< Derived >::compute(), Eigen::IterativeSolverBase< Derived >::factorize(), and Eigen::IterativeSolverBase< Derived >::preconditioner().
m_tolerance
template<typename Derived > RealScalar Eigen::IterativeSolverBase< Derived >::m_tolerance protected
Referenced by Eigen::BiCGSTAB< MatrixType_, Preconditioner_ >::_solve_vector_with_guess_impl(), Eigen::ConjugateGradient< MatrixType_, UpLo_, Preconditioner_ >::_solve_vector_with_guess_impl(), Eigen::LeastSquaresConjugateGradient< MatrixType_, Preconditioner_ >::_solve_vector_with_guess_impl(), Eigen::BiCGSTABL< MatrixType_, Preconditioner_ >::_solve_vector_with_guess_impl(), Eigen::DGMRES< MatrixType_, Preconditioner_ >::_solve_vector_with_guess_impl(), Eigen::GMRES< MatrixType_, Preconditioner_ >::_solve_vector_with_guess_impl(), Eigen::IDRS< MatrixType_, Preconditioner_ >::_solve_vector_with_guess_impl(), Eigen::IDRSTABL< MatrixType_, Preconditioner_ >::_solve_vector_with_guess_impl(), Eigen::MINRES< MatrixType_, UpLo_, Preconditioner_ >::_solve_vector_with_guess_impl(), Eigen::IterativeSolverBase< Derived >::init(), Eigen::IterativeSolverBase< Derived >::setTolerance(), and Eigen::IterativeSolverBase< Derived >::tolerance().
The documentation for this class was generated from the following file:
IterativeSolverBase.h