MercuryDPM: InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT > Class Template Reference
InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT > Class Template Reference
Public Member Functions
InclinedPlaneProblem (const unsigned &nx, const unsigned &ny, const double &length)
Generic Constructor (empty)
void solve_steady ()
Solve the steady problem.
void timestep (const double &dt, const unsigned &n_tsteps)
Take n_tsteps timesteps of size dt.
void actions_before_implicit_timestep ()
void make_traction_elements ()
void make_free_surface_elements ()
void complete_build ()
~InclinedPlaneProblem ()
Generic desructor to clean up the memory allocated in the problem.
Public Member Functions inherited from oomph::Problem
virtual void debug_hook_fct (const unsigned &i)
void set_analytic_dparameter (double *const &parameter_pt)
void unset_analytic_dparameter (double *const &parameter_pt)
bool is_dparameter_calculated_analytically (double *const &parameter_pt)
void set_analytic_hessian_products ()
void unset_analytic_hessian_products ()
bool are_hessian_products_calculated_analytically ()
void set_pinned_values_to_zero ()
bool distributed () const
virtual void actions_before_adapt ()
virtual void actions_after_adapt ()
Actions that are to be performed after a mesh adaptation.
OomphCommunicator * communicator_pt ()
access function to the oomph-lib communicator
const OomphCommunicator * communicator_pt () const
access function to the oomph-lib communicator, const version
Problem ()
Problem (const Problem &dummy)=delete
Broken copy constructor.
void operator= (const Problem &)=delete
Broken assignment operator.
virtual ~Problem ()
Virtual destructor to clean up memory.
Mesh *& mesh_pt ()
Return a pointer to the global mesh.
Mesh *const & mesh_pt () const
Return a pointer to the global mesh (const version)
Mesh *& mesh_pt (const unsigned &imesh)
Mesh *const & mesh_pt (const unsigned &imesh) const
Return a pointer to the i-th submesh (const version)
unsigned nsub_mesh () const
Return number of submeshes.
unsigned add_sub_mesh (Mesh *const &mesh_pt)
void flush_sub_meshes ()
void build_global_mesh ()
void rebuild_global_mesh ()
LinearSolver *& linear_solver_pt ()
Return a pointer to the linear solver object.
LinearSolver *const & linear_solver_pt () const
Return a pointer to the linear solver object (const version)
LinearSolver *& mass_matrix_solver_for_explicit_timestepper_pt ()
LinearSolver * mass_matrix_solver_for_explicit_timestepper_pt () const
EigenSolver *& eigen_solver_pt ()
Return a pointer to the eigen solver object.
EigenSolver *const & eigen_solver_pt () const
Return a pointer to the eigen solver object (const version)
Time *& time_pt ()
Return a pointer to the global time object.
Time * time_pt () const
Return a pointer to the global time object (const version).
double & time ()
Return the current value of continuous time.
double time () const
Return the current value of continuous time (const version)
TimeStepper *& time_stepper_pt ()
const TimeStepper * time_stepper_pt () const
TimeStepper *& time_stepper_pt (const unsigned &i)
Return a pointer to the i-th timestepper.
ExplicitTimeStepper *& explicit_time_stepper_pt ()
Return a pointer to the explicit timestepper.
unsigned long set_timestepper_for_all_data (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data=false)
virtual void shift_time_values ()
Shift all values along to prepare for next timestep.
AssemblyHandler *& assembly_handler_pt ()
Return a pointer to the assembly handler object.
AssemblyHandler *const & assembly_handler_pt () const
Return a pointer to the assembly handler object (const version)
double & minimum_dt ()
Access function to min timestep in adaptive timestepping.
double & maximum_dt ()
Access function to max timestep in adaptive timestepping.
unsigned & max_newton_iterations ()
Access function to max Newton iterations before giving up.
void problem_is_nonlinear (const bool &prob_lin)
Access function to Problem_is_nonlinear.
double & max_residuals ()
bool & time_adaptive_newton_crash_on_solve_fail ()
Access function for Time_adaptive_newton_crash_on_solve_fail.
double & newton_solver_tolerance ()
void add_time_stepper_pt (TimeStepper *const &time_stepper_pt)
void set_explicit_time_stepper_pt (ExplicitTimeStepper *const &explicit_time_stepper_pt)
void initialise_dt (const double &dt)
void initialise_dt (const Vector< double > &dt)
Data *& global_data_pt (const unsigned &i)
Return a pointer to the the i-th global data object.
void add_global_data (Data *const &global_data_pt)
void flush_global_data ()
LinearAlgebraDistribution *const & dof_distribution_pt () const
Return the pointer to the dof distribution (read-only)
unsigned long ndof () const
Return the number of dofs.
unsigned ntime_stepper () const
Return the number of time steppers.
unsigned nglobal_data () const
Return the number of global data values.
unsigned self_test ()
Self-test: Check meshes and global data. Return 0 for OK.
void enable_store_local_dof_pt_in_elements ()
void disable_store_local_dof_pt_in_elements ()
unsigned long assign_eqn_numbers (const bool &assign_local_eqn_numbers=true)
void describe_dofs (std::ostream &out= *(oomph_info.stream_pt())) const
void enable_discontinuous_formulation ()
void disable_discontinuous_formulation ()
void get_dofs (DoubleVector &dofs) const
void get_dofs (const unsigned &t, DoubleVector &dofs) const
Return vector of the t'th history value of all dofs.
void set_dofs (const DoubleVector &dofs)
Set the values of the dofs.
void set_dofs (const unsigned &t, DoubleVector &dofs)
Set the history values of the dofs.
void set_dofs (const unsigned &t, Vector< double * > &dof_pt)
void add_to_dofs (const double &lambda, const DoubleVector &increment_dofs)
Add lambda x incremenet_dofs[l] to the l-th dof.
double * global_dof_pt (const unsigned &i)
double & dof (const unsigned &i)
i-th dof in the problem
double dof (const unsigned &i) const
i-th dof in the problem (const version)
double *& dof_pt (const unsigned &i)
Pointer to i-th dof in the problem.
double * dof_pt (const unsigned &i) const
Pointer to i-th dof in the problem (const version)
virtual void get_inverse_mass_matrix_times_residuals (DoubleVector &Mres)
virtual void get_dvaluesdt (DoubleVector &f)
virtual void get_residuals (DoubleVector &residuals)
Get the total residuals Vector for the problem.
virtual void get_jacobian (DoubleVector &residuals, DenseDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CRDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CCDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, SumOfMatrices &jacobian)
void get_fd_jacobian (DoubleVector &residuals, DenseMatrix< double > &jacobian)
Get the full Jacobian by finite differencing.
void get_derivative_wrt_global_parameter (double *const &parameter_pt, DoubleVector &result)
void get_hessian_vector_products (DoubleVectorWithHaloEntries const &Y, Vector< DoubleVectorWithHaloEntries > const &C, Vector< DoubleVectorWithHaloEntries > &product)
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, Vector< DoubleVector > &eigenvector, const bool &steady=true)
Solve the eigenproblem.
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, const bool &steady=true)
virtual void get_eigenproblem_matrices (CRDoubleMatrix &mass_matrix, CRDoubleMatrix &main_matrix, const double &shift=0.0)
void assign_eigenvector_to_dofs (DoubleVector &eigenvector)
Assign the eigenvector passed to the function to the dofs.
void add_eigenvector_to_dofs (const double &epsilon, const DoubleVector &eigenvector)
void store_current_dof_values ()
Store the current values of the degrees of freedom.
void restore_dof_values ()
Restore the stored values of the degrees of freedom.
void enable_jacobian_reuse ()
void disable_jacobian_reuse ()
Disable recycling of Jacobian in Newton iteration.
bool jacobian_reuse_is_enabled ()
Is recycling of Jacobian in Newton iteration enabled?
bool & use_predictor_values_as_initial_guess ()
void newton_solve ()
Use Newton method to solve the problem.
void enable_globally_convergent_newton_method ()
enable globally convergent Newton method
void disable_globally_convergent_newton_method ()
disable globally convergent Newton method
void newton_solve (unsigned const &max_adapt)
void steady_newton_solve (unsigned const &max_adapt=0)
void copy (Problem *orig_problem_pt)
virtual Problem * make_copy ()
virtual void read (std::ifstream &restart_file, bool &unsteady_restart)
virtual void read (std::ifstream &restart_file)
virtual void dump (std::ofstream &dump_file) const
void dump (const std::string &dump_file_name) const
void delete_all_external_storage ()
virtual void symmetrise_eigenfunction_for_adaptive_pitchfork_tracking ()
double * bifurcation_parameter_pt () const
void get_bifurcation_eigenfunction (Vector< DoubleVector > &eigenfunction)
void activate_fold_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const DoubleVector &normalisation, const bool &block_solve=true)
void activate_pitchfork_tracking (double *const &parameter_pt, const DoubleVector &symmetry_vector, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const double &omega, const DoubleVector &null_real, const DoubleVector &null_imag, const bool &block_solve=true)
void deactivate_bifurcation_tracking ()
void reset_assembly_handler_to_default ()
Reset the system to the standard non-augemented state.
double arc_length_step_solve (double *const &parameter_pt, const double &ds, const unsigned &max_adapt=0)
double arc_length_step_solve (Data *const &data_pt, const unsigned &data_index, const double &ds, const unsigned &max_adapt=0)
void reset_arc_length_parameters ()
int & sign_of_jacobian ()
void explicit_timestep (const double &dt, const bool &shift_values=true)
Take an explicit timestep of size dt.
void unsteady_newton_solve (const double &dt)
void unsteady_newton_solve (const double &dt, const bool &shift_values)
void unsteady_newton_solve (const double &dt, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const unsigned &suppress_resolve_after_spatial_adapt_flag, const bool &first, const bool &shift=true)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon, const bool &shift_values)
void assign_initial_values_impulsive ()
void assign_initial_values_impulsive (const double &dt)
void calculate_predictions ()
Calculate predictions.
void enable_mass_matrix_reuse ()
void disable_mass_matrix_reuse ()
bool mass_matrix_reuse_is_enabled ()
Return whether the mass matrix is being reused.
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly (DocInfo &doc_info)
void refine_uniformly_and_prune (DocInfo &doc_info)
void refine_uniformly ()
void refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform refinement for submesh i_mesh with documentation.
void refine_uniformly (const unsigned &i_mesh)
Do uniform refinement for submesh i_mesh without documentation.
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly (DocInfo &doc_info)
void p_refine_uniformly_and_prune (DocInfo &doc_info)
void p_refine_uniformly ()
void p_refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-refinement for submesh i_mesh with documentation.
void p_refine_uniformly (const unsigned &i_mesh)
Do uniform p-refinement for submesh i_mesh without documentation.
void refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const unsigned &i_mesh, const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void refine_selected_elements (const Vector< Vector< RefineableElement * >> &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void p_refine_selected_elements (const Vector< Vector< PRefineableElement * >> &elements_to_be_refined_pt)
unsigned unrefine_uniformly ()
unsigned unrefine_uniformly (const unsigned &i_mesh)
void p_unrefine_uniformly (DocInfo &doc_info)
void p_unrefine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-unrefinement for submesh i_mesh without documentation.
void adapt (unsigned &n_refined, unsigned &n_unrefined)
void adapt ()
void p_adapt (unsigned &n_refined, unsigned &n_unrefined)
void p_adapt ()
void adapt_based_on_error_estimates (unsigned &n_refined, unsigned &n_unrefined, Vector< Vector< double >> &elemental_error)
void adapt_based_on_error_estimates (Vector< Vector< double >> &elemental_error)
void get_all_error_estimates (Vector< Vector< double >> &elemental_error)
void doc_errors (DocInfo &doc_info)
Get max and min error for all elements in submeshes.
void doc_errors ()
Get max and min error for all elements in submeshes.
void enable_info_in_newton_solve ()
void disable_info_in_newton_solve ()
Disable the output of information when in the newton solver.
Public Member Functions inherited from oomph::ExplicitTimeSteppableObject
ExplicitTimeSteppableObject ()
Empty constructor.
ExplicitTimeSteppableObject (const ExplicitTimeSteppableObject &)=delete
Broken copy constructor.
void operator= (const ExplicitTimeSteppableObject &)=delete
Broken assignment operator.
virtual ~ExplicitTimeSteppableObject ()
Empty destructor.
virtual void actions_before_explicit_stage ()
virtual void actions_after_explicit_stage ()
Protected Attributes
Mesh * Bulk_mesh_pt
Bulk fluid mesh.
Mesh * Traction_mesh_pt
Mesh for the traction elements that are added at inlet and outlet.
Mesh * Surface_mesh_pt
Mesh for the free surface elements.
Mesh * Point_mesh_pt
Mesh for the point elements at each end of the free surface.
std::string Output_prefix
Prefix for output files.
Protected Attributes inherited from oomph::Problem
Vector< Problem * > Copy_of_problem_pt
std::map< double *, bool > Calculate_dparameter_analytic
bool Calculate_hessian_products_analytic
LinearAlgebraDistribution * Dof_distribution_pt
Vector< double * > Dof_pt
Vector of pointers to dofs.
DoubleVectorWithHaloEntries Element_count_per_dof
double Relaxation_factor
double Newton_solver_tolerance
unsigned Max_newton_iterations
Maximum number of Newton iterations.
unsigned Nnewton_iter_taken
Vector< double > Max_res
Maximum residuals at start and after each newton iteration.
double Max_residuals
bool Time_adaptive_newton_crash_on_solve_fail
bool Jacobian_reuse_is_enabled
Is re-use of Jacobian in Newton iteration enabled? Default: false.
bool Jacobian_has_been_computed
bool Problem_is_nonlinear
bool Pause_at_end_of_sparse_assembly
bool Doc_time_in_distribute
unsigned Sparse_assembly_method
unsigned Sparse_assemble_with_arrays_initial_allocation
unsigned Sparse_assemble_with_arrays_allocation_increment
Vector< Vector< unsigned > > Sparse_assemble_with_arrays_previous_allocation
double Numerical_zero_for_sparse_assembly
double FD_step_used_in_get_hessian_vector_products
bool Mass_matrix_reuse_is_enabled
bool Mass_matrix_has_been_computed
bool Discontinuous_element_formulation
double Minimum_dt
Minimum desired dt: if dt falls below this value, exit.
double Maximum_dt
Maximum desired dt.
double DTSF_max_increase
double DTSF_min_decrease
double Minimum_dt_but_still_proceed
bool Scale_arc_length
Boolean to control whether arc-length should be scaled.
double Desired_proportion_of_arc_length
Proportion of the arc-length to taken by the parameter.
double Theta_squared
int Sign_of_jacobian
Storage for the sign of the global Jacobian.
double Continuation_direction
double Parameter_derivative
Storage for the derivative of the global parameter wrt arc-length.
double Parameter_current
Storage for the present value of the global parameter.
bool Use_continuation_timestepper
Boolean to control original or new storage of dof stuff.
unsigned Dof_derivative_offset
unsigned Dof_current_offset
Vector< double > Dof_derivative
Storage for the derivative of the problem variables wrt arc-length.
Vector< double > Dof_current
Storage for the present values of the variables.
double Ds_current
Storage for the current step value.
unsigned Desired_newton_iterations_ds
double Minimum_ds
Minimum desired value of arc-length.
bool Bifurcation_detection
Boolean to control bifurcation detection via determinant of Jacobian.
bool Bisect_to_find_bifurcation
Boolean to control wheter bisection is used to located bifurcation.
bool First_jacobian_sign_change
Boolean to indicate whether a sign change has occured in the Jacobian.
bool Arc_length_step_taken
Boolean to indicate whether an arc-length step has been taken.
bool Use_finite_differences_for_continuation_derivatives
OomphCommunicator * Communicator_pt
The communicator for this problem.
bool Always_take_one_newton_step
double Timestep_reduction_factor_after_nonconvergence
bool Keep_temporal_error_below_tolerance
Additional Inherited Members
Public Types inherited from oomph::Problem
typedef void(* SpatialErrorEstimatorFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error)
Function pointer for spatial error estimator.
typedef void(* SpatialErrorEstimatorWithDocFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error, DocInfo &doc_info)
Function pointer for spatial error estimator with doc.
Public Attributes inherited from oomph::Problem
bool Shut_up_in_newton_solve
Static Public Attributes inherited from oomph::Problem
static bool Suppress_warning_about_actions_before_read_unstructured_meshes
Protected Types inherited from oomph::Problem
enum Assembly_method {
Perform_assembly_using_vectors_of_pairs , Perform_assembly_using_two_vectors , Perform_assembly_using_maps , Perform_assembly_using_lists ,
Perform_assembly_using_two_arrays
}
Enumerated flags to determine which sparse assembly method is used.
Protected Member Functions inherited from oomph::Problem
unsigned setup_element_count_per_dof ()
virtual void sparse_assemble_row_or_column_compressed (Vector< int * > &column_or_row_index, Vector< int * > &row_or_column_start, Vector< double * > &value, Vector< unsigned > &nnz, Vector< double * > &residual, bool compressed_row_flag)
virtual void actions_before_newton_solve ()
virtual void actions_after_newton_solve ()
virtual void actions_before_newton_convergence_check ()
virtual void actions_before_newton_step ()
virtual void actions_after_newton_step ()
virtual void actions_after_implicit_timestep ()
virtual void actions_after_implicit_timestep_and_error_estimation ()
virtual void actions_before_explicit_timestep ()
Actions that should be performed before each explicit time step.
virtual void actions_after_explicit_timestep ()
Actions that should be performed after each explicit time step.
virtual void actions_before_read_unstructured_meshes ()
virtual void actions_after_read_unstructured_meshes ()
virtual void actions_after_change_in_global_parameter (double *const &parameter_pt)
virtual void actions_after_change_in_bifurcation_parameter ()
virtual void actions_after_parameter_increase (double *const &parameter_pt)
double & dof_derivative (const unsigned &i)
double & dof_current (const unsigned &i)
virtual void set_initial_condition ()
virtual double global_temporal_error_norm ()
unsigned newton_solve_continuation (double *const &parameter_pt)
unsigned newton_solve_continuation (double *const &parameter_pt, DoubleVector &z)
void calculate_continuation_derivatives (double *const &parameter_pt)
void calculate_continuation_derivatives (const DoubleVector &z)
void calculate_continuation_derivatives_fd (double *const &parameter_pt)
bool does_pointer_correspond_to_problem_data (double *const &parameter_pt)
void set_consistent_pinned_values_for_continuation ()
Static Protected Attributes inherited from oomph::Problem
static ContinuationStorageScheme Continuation_time_stepper
Storage for the single static continuation timestorage object.
Detailed Description
template<class ELEMENT, class INTERFACE_ELEMENT>
class InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >
Generic problem class that will form the base class for both spine and elastic mesh-updates of the problem. Templated by the bulk element and interface element types
Constructor & Destructor Documentation
InclinedPlaneProblem()
template<class ELEMENT , class INTERFACE_ELEMENT > InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::InclinedPlaneProblem (const unsigned & nx, const unsigned & ny, const double & length) inline
Generic Constructor (empty)
                                             :
   Output_prefix("Unset") { }
~InclinedPlaneProblem()
template<class ELEMENT , class INTERFACE_ELEMENT > InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::~InclinedPlaneProblem () inline
Generic desructor to clean up the memory allocated in the problem.
   {
    //Clear node storage before the mesh can be deleted,
    //to avoid double deletion
    this->Point_mesh_pt->flush_node_storage();
    //Then delete the mesh
    delete this->Point_mesh_pt;
    //Clear node storage and then delete mesh
    this->Surface_mesh_pt->flush_node_storage();
    delete this->Surface_mesh_pt;
    //Clear node storage and then delete mesh
    this->Traction_mesh_pt->flush_node_storage();
    delete this->Traction_mesh_pt;
    //Delete the bulk mesh (no need to clear node storage)
    delete this->Bulk_mesh_pt;
    //Delete the time stepper
    delete this->time_stepper_pt();
   }
References oomph::Mesh::flush_node_storage().
Member Function Documentation
actions_before_implicit_timestep()
template<class ELEMENT , class INTERFACE_ELEMENT > void InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::actions_before_implicit_timestep () inline virtual
Actions before the timestep (update the time-dependent boundary conditions)
Reimplemented from oomph::Problem.
   {
    //Read out the current time
    double time = this->time_pt()->time();
    //Now add a temporary sinusoidal suction and blowing to the base
    //Amplitude of the perturbation
    double epsilon = 0.01;
    //Loop over the nodes on the base
    unsigned n_node = this->Bulk_mesh_pt->nboundary_node(0);
    for(unsigned n=0;n<n_node;n++)
     {
      Node* nod_pt = this->Bulk_mesh_pt->boundary_node_pt(0,n);
      double arg = Global_Physical_Variables::K*nod_pt->x(0);
      double value = sin(arg)*epsilon*time*exp(-time);
      nod_pt->set_value(1,value);
     }
   } //end_of_actions_before_implicit_timestep
References oomph::Mesh::boundary_node_pt(), oomph::SarahBL::epsilon, Eigen::bfloat16_impl::exp(), Global_Physical_Variables::K, n, oomph::Mesh::nboundary_node(), oomph::Data::set_value(), sin(), Eigen::value, and oomph::Node::x().
complete_build()
template<class ELEMENT , class INTERFACE_ELEMENT > void InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::complete_build () inline
Complete the build of the problem setting all standard parameters and boundary conditions
   {
    using namespace Global_Physical_Variables;
    //Complete the build of the fluid elements by passing physical parameters
    //Find the number of bulk elements
    unsigned n_element = Bulk_mesh_pt->nelement();
    //Loop over all the fluid elements
    for(unsigned e=0;e<n_element;e++)
     {
      //Cast to a fluid element
      ELEMENT *temp_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(e));
      //Set the Reynolds number
      temp_pt->re_pt() = &Re;
      //The Strouhal number is 1, so ReSt = Re
      temp_pt->re_st_pt() = &Re;
      //Set the Reynolds number / Froude number
      temp_pt->re_invfr_pt() = &ReInvFr;
      //Set the direction of gravity
      temp_pt->g_pt() = &G;
     }
    //------------Set the boundary conditions for this problem----------
    {
     //Determine whether we are solving an elastic problem or not
     bool elastic = false;
     if(dynamic_cast<SolidNode*>(Bulk_mesh_pt->node_pt(0))) {elastic=true;}
     //Loop over the bottom of the mesh (the wall of the channel)
     unsigned n_node = Bulk_mesh_pt->nboundary_node(0);
     for(unsigned j=0;j<n_node;j++)
      {
       //Pin the u- and v- velocities
       Bulk_mesh_pt->boundary_node_pt(0,j)->pin(0);
       Bulk_mesh_pt->boundary_node_pt(0,j)->pin(1);
       //If we are formulating the elastic problem pin both positions
       //of nodes
       if(elastic)
        {
         static_cast<SolidNode*>(Bulk_mesh_pt->boundary_node_pt(0,j))
          ->pin_position(0);
         static_cast<SolidNode*>(Bulk_mesh_pt->boundary_node_pt(0,j))
          ->pin_position(1);
        }
      }
     //Loop over the inlet and set the Dirichlet condition
     //of no vertical velocity
     n_node = Bulk_mesh_pt->nboundary_node(3);
     for(unsigned j=0;j<n_node;j++)
      {
       Bulk_mesh_pt->boundary_node_pt(3,j)->pin(1);
       //If elastic pin horizontal position of nodes
       if(elastic)
        {
         static_cast<SolidNode*>(Bulk_mesh_pt->boundary_node_pt(3,j))
          ->pin_position(0);
        }
      }
     //Loop over the outlet and set the Dirichlet condition
     //of no vertical velocity
     n_node = Bulk_mesh_pt->nboundary_node(1);
     for(unsigned j=0;j<n_node;j++)
      {
       Bulk_mesh_pt->boundary_node_pt(1,j)->pin(1);
       //If elastic pin horizontal position
       if(elastic)
        {
         static_cast<SolidNode*>(Bulk_mesh_pt->boundary_node_pt(1,j))
          ->pin_position(0);
        }
      }
    }
    //Attach the boundary conditions to the mesh
    std::cout << assign_eqn_numbers() << " in the main problem" << std::endl;
   } //end of complete_build
References oomph::Mesh::boundary_node_pt(), e(), oomph::Mesh::element_pt(), G, j, oomph::Mesh::nboundary_node(), oomph::Mesh::nelement(), oomph::Mesh::node_pt(), oomph::Data::pin(), GlobalPhysicalVariables::Re, and GlobalPhysicalVariables::ReInvFr.
make_free_surface_elements()
template<class ELEMENT , class INTERFACE_ELEMENT > void InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::make_free_surface_elements () inline
   {
    //Create the (empty) meshes
    Surface_mesh_pt = new Mesh;
    Point_mesh_pt = new Mesh;
    //The free surface is on the boundary 2
    unsigned b = 2;
    unsigned n_boundary_element = Bulk_mesh_pt->nboundary_element(b);
    //Loop over the elements and create the appropriate interface elements
    for(unsigned e=0;e<n_boundary_element;e++)
     {
      INTERFACE_ELEMENT *surface_element_pt =
       new INTERFACE_ELEMENT
       (Bulk_mesh_pt->boundary_element_pt(b,e),
        Bulk_mesh_pt->face_index_at_boundary(b,e));
      //Add elements to the mesh
      Surface_mesh_pt->add_element_pt(surface_element_pt);
      //Assign the capillary number to the free surface
      surface_element_pt->ca_pt() =
       &Global_Physical_Variables::Ca;
      //Make a point element from left-hand side of the
      //first surface element (note that this relies on knowledge of
      //the element order within the mesh)
      if(e==0)
       {
        FluidInterfaceBoundingElement* point_element_pt =
         surface_element_pt->make_bounding_element(-1);
        //Add element to the point mesh
        Point_mesh_pt->add_element_pt(point_element_pt);
        //Set the capillary number
        point_element_pt->ca_pt() = &Global_Physical_Variables::Ca;
        //Set the wall normal
        point_element_pt->wall_unit_normal_fct_pt() =
         &Global_Physical_Variables::wall_unit_normal_inlet_fct;
        //Set the contact angle (using the strong version of the constraint)
        point_element_pt->set_contact_angle(
         &Global_Physical_Variables::Inlet_Angle);
       }
      //Make another point element from the right-hand side of the
      //last surface element (note that this relies on knowledge of
      //the element order within the mesh)
      if(e==n_boundary_element-1)
       {
        FluidInterfaceBoundingElement* point_element_pt =
         surface_element_pt->make_bounding_element(1);
        //Add element to the mesh
        Point_mesh_pt->add_element_pt(point_element_pt);
        //Set the capillary number
        point_element_pt->ca_pt() = &Global_Physical_Variables::Ca;
        // Set the function that specifies the wall normal
        point_element_pt->wall_unit_normal_fct_pt() =
         &Global_Physical_Variables::wall_unit_normal_outlet_fct;
       }
     }
   } //end of make_free_surface_elements
References oomph::Mesh::add_element_pt(), b, oomph::Mesh::boundary_element_pt(), Global_Physical_Variables::Ca, oomph::FluidInterfaceBoundingElement::ca_pt(), e(), oomph::Mesh::face_index_at_boundary(), Global_Physical_Variables::Inlet_Angle, oomph::Mesh::nboundary_element(), oomph::FluidInterfaceBoundingElement::set_contact_angle(), oomph::FluidInterfaceBoundingElement::wall_unit_normal_fct_pt(), Global_Physical_Variables::wall_unit_normal_inlet_fct(), and Global_Physical_Variables::wall_unit_normal_outlet_fct().
make_traction_elements()
template<class ELEMENT , class INTERFACE_ELEMENT > void InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::make_traction_elements () inline
Function to add the traction boundary elements to boundaries 3(inlet) and 1(outlet) of the mesh
   {
    //Create a new (empty mesh)
    Traction_mesh_pt = new Mesh;
    //Inlet boundary conditions (boundary 3)
    {
     unsigned b = 3;
     //Find the number of elements adjacent to mesh boundary
     unsigned n_boundary_element = Bulk_mesh_pt->nboundary_element(b);
     //Loop over these elements and create the traction elements
     for(unsigned e=0;e<n_boundary_element;e++)
      {
       NavierStokesTractionElement<ELEMENT> *surface_element_pt =
        new NavierStokesTractionElement<ELEMENT>
        (Bulk_mesh_pt->boundary_element_pt(b,e),
         Bulk_mesh_pt->face_index_at_boundary(b,e));
       //Add the elements to the mesh
       Traction_mesh_pt->add_element_pt(surface_element_pt);
       //Set the traction function
       surface_element_pt->traction_fct_pt() =
        &Global_Physical_Variables::hydrostatic_pressure_inlet;
      }
    }
    //Outlet boundary conditions (boundary 1)
    {
     unsigned b=1;
     //Find the number of elements adjacent to mesh boundary
     unsigned n_boundary_element = Bulk_mesh_pt->nboundary_element(b);
     //Loop over these elements and create the traction elements
     for(unsigned e=0;e<n_boundary_element;e++)
      {
       NavierStokesTractionElement<ELEMENT> *surface_element_pt =
        new NavierStokesTractionElement<ELEMENT>
        (Bulk_mesh_pt->boundary_element_pt(b,e),
         Bulk_mesh_pt->face_index_at_boundary(b,e));
       //Add the elements to the mesh
       Traction_mesh_pt->add_element_pt(surface_element_pt);
       //Set the traction function
       surface_element_pt->traction_fct_pt() =
        &Global_Physical_Variables::hydrostatic_pressure_outlet;
      }
    }
   } //end of make_traction_elements
References oomph::Mesh::add_element_pt(), b, oomph::Mesh::boundary_element_pt(), e(), oomph::Mesh::face_index_at_boundary(), Global_Physical_Variables::hydrostatic_pressure_inlet(), Global_Physical_Variables::hydrostatic_pressure_outlet(), oomph::Mesh::nboundary_element(), and oomph::NavierStokesTractionElement< ELEMENT >::traction_fct_pt.
solve_steady()
template<class ELEMENT , class INTERFACE_ELEMENT > void InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::solve_steady
Solve the steady problem.
 {
  //Load the namespace
  using namespace Global_Physical_Variables;
  //Initially set all nodes to the Nusselt flat-film solution
  {
   unsigned n_node = Bulk_mesh_pt->nnode();
   for(unsigned  n=0;n<n_node;n++)
    {
     double y = Bulk_mesh_pt->node_pt(n)->x(1);
     //Top row
     Bulk_mesh_pt->node_pt(n)->set_value(0,0.5*ReInvFr*sin(Alpha)*(2.0*y - y*y));
    }
  }
  //Do one steady solve
  steady_newton_solve();
  //Output the full flow field
  std::string filename = Output_prefix;;
  filename.append("_output.dat");
  ofstream file(filename.c_str());
  Bulk_mesh_pt->output(file,5);
  file.close();
 } //end of solve_steady
References TanhSolnForAdvectionDiffusion::Alpha, MergeRestartFiles::filename, n, GlobalPhysicalVariables::ReInvFr, sin(), oomph::Global_string_for_annotation::string(), and y.
timestep()
template<class ELEMENT , class INTERFACE_ELEMENT > void InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::timestep (const double & dt, const unsigned & n_tsteps)
Take n_tsteps timesteps of size dt.
Perform n_tsteps timesteps of size dt.
 {
  //Need to use the Global variables here
  using namespace Global_Physical_Variables;
  //Open an output file
  std::string filename = Output_prefix;
  filename.append("_time_trace.dat");
  ofstream trace(filename.c_str());
  //Counter that will be used to output the full flowfield
  //at certain timesteps
  int counter=0;
  //Initial output of the time and the value of the vertical position at the
  //left and right-hand end of the free surface
  trace << time_pt()->time() << " "
        << Bulk_mesh_pt->boundary_node_pt(2,0)->value(1)
        << " "
        <<  Bulk_mesh_pt->
   boundary_node_pt(2, Bulk_mesh_pt->nboundary_node(2)-1)->x(1)
        << " "
        << std::endl;
  //Loop over the desired number of timesteps
  for(unsigned t=1;t<=n_tsteps;t++)
   {
    //Increase the counter
    counter++;
    cout << std::endl;
    cout << "--------------TIMESTEP " << t<< " ------------------" << std::endl;
    //Take a timestep of size dt
    unsteady_newton_solve(dt);
    //Uncomment to get full solution output
    if(counter==2) //Change this number to get output every n steps
     {
      std::ofstream file;
      std::ostringstream filename;
      filename << Output_prefix << "_step" << Re << "_" << t << ".dat";
      file.open(filename.str().c_str());
      Bulk_mesh_pt->output(file,5);
      file.close();
      counter=0;
     }
    //Always output the interface
    {
     std::ofstream file;
      std::ostringstream filename;
      filename << Output_prefix << "_interface_" << Re << "_" << t << ".dat";
      file.open(filename.str().c_str());
      Surface_mesh_pt->output(file,5);
      file.close();
    }
    //Output the time and value of the vertical position of the free surface
    //at the left- and right-hand ends
    trace << time_pt()->time() << " "
          << Bulk_mesh_pt->boundary_node_pt(2,0)->x(1) << " "
          <<
     Bulk_mesh_pt->
     boundary_node_pt(2,Bulk_mesh_pt->nboundary_node(2)-1)->x(1) << " "
          << std::endl;
   }
 } //end of timestep
References MergeRestartFiles::filename, GlobalPhysicalVariables::Re, oomph::Global_string_for_annotation::string(), and plotPSD::t.
Member Data Documentation
Bulk_mesh_pt
template<class ELEMENT , class INTERFACE_ELEMENT > Mesh* InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::Bulk_mesh_pt protected
Bulk fluid mesh.
Output_prefix
template<class ELEMENT , class INTERFACE_ELEMENT > std::string InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::Output_prefix protected
Prefix for output files.
Point_mesh_pt
template<class ELEMENT , class INTERFACE_ELEMENT > Mesh* InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::Point_mesh_pt protected
Mesh for the point elements at each end of the free surface.
Surface_mesh_pt
template<class ELEMENT , class INTERFACE_ELEMENT > Mesh* InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::Surface_mesh_pt protected
Mesh for the free surface elements.
Traction_mesh_pt
template<class ELEMENT , class INTERFACE_ELEMENT > Mesh* InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::Traction_mesh_pt protected
Mesh for the traction elements that are added at inlet and outlet.
The documentation for this class was generated from the following file:
inclined_plane.cc