MercuryDPM: oomph::TwoPlusThreeUpperTriangularWithOneLevelSubsidiary< MATRIX > Class Template Reference
oomph::TwoPlusThreeUpperTriangularWithOneLevelSubsidiary< MATRIX > Class Template Reference
#include <multi_poisson_block_preconditioners.h>
Public Member Functions
TwoPlusThreeUpperTriangularWithOneLevelSubsidiary ()
Constructor.
virtual ~TwoPlusThreeUpperTriangularWithOneLevelSubsidiary ()
Destructor - delete the preconditioner matrices.
void clean_up_my_memory ()
Clean up the memory.
TwoPlusThreeUpperTriangularWithOneLevelSubsidiary (const TwoPlusThreeUpperTriangularWithOneLevelSubsidiary &)
Broken copy constructor.
void operator= (const TwoPlusThreeUpperTriangularWithOneLevelSubsidiary &)
Broken assignment operator.
void preconditioner_solve (const DoubleVector &r, DoubleVector &z)
Apply preconditioner to r.
void setup ()
Setup the preconditioner.
void set_multi_poisson_mesh (Mesh *multi_poisson_mesh_pt)
Specify the mesh that contains multi-poisson elements.
void setup (DoubleMatrixBase *matrix_pt)
void setup (const Problem *problem_pt, DoubleMatrixBase *matrix_pt)
virtual void setup ()=0
Public Member Functions inherited from oomph::BlockPreconditioner< MATRIX >
BlockPreconditioner ()
Constructor.
virtual ~BlockPreconditioner ()
Destructor.
BlockPreconditioner (const BlockPreconditioner &)=delete
Broken copy constructor.
void operator= (const BlockPreconditioner &)=delete
Broken assignment operator.
MATRIX * matrix_pt () const
void turn_on_recursive_debug_flag ()
void turn_off_recursive_debug_flag ()
void turn_on_debug_flag ()
Toggles on the debug flag.
void turn_off_debug_flag ()
Toggles off the debug flag.
void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< MATRIX > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse)
void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< MATRIX > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse, const Vector< Vector< unsigned >> &doftype_coarsen_map_coarse)
virtual void block_setup ()
void block_setup (const Vector< unsigned > &dof_to_block_map)
void get_block (const unsigned &i, const unsigned &j, MATRIX &output_matrix, const bool &ignore_replacement_block=false) const
MATRIX get_block (const unsigned &i, const unsigned &j, const bool &ignore_replacement_block=false) const
void set_master_matrix_pt (MATRIX *in_matrix_pt)
Set the matrix_pt in the upper-most master preconditioner.
void get_block_other_matrix (const unsigned &i, const unsigned &j, MATRIX *in_matrix_pt, MATRIX &output_matrix)
void get_blocks (DenseMatrix< bool > &required_blocks, DenseMatrix< MATRIX * > &block_matrix_pt) const
void get_dof_level_block (const unsigned &i, const unsigned &j, MATRIX &output_block, const bool &ignore_replacement_block=false) const
MATRIX get_concatenated_block (const VectorMatrix< BlockSelector > &selected_block)
void get_concatenated_block_vector (const Vector< unsigned > &block_vec_number, const DoubleVector &v, DoubleVector &b)
void return_concatenated_block_vector (const Vector< unsigned > &block_vec_number, const DoubleVector &b, DoubleVector &v) const
Takes concatenated block ordered vector, b, and copies its.
void get_block_vectors (const Vector< unsigned > &block_vec_number, const DoubleVector &v, Vector< DoubleVector > &s) const
void get_block_vectors (const DoubleVector &v, Vector< DoubleVector > &s) const
void return_block_vectors (const Vector< unsigned > &block_vec_number, const Vector< DoubleVector > &s, DoubleVector &v) const
void return_block_vectors (const Vector< DoubleVector > &s, DoubleVector &v) const
void get_block_vector (const unsigned &n, const DoubleVector &v, DoubleVector &b) const
void return_block_vector (const unsigned &n, const DoubleVector &b, DoubleVector &v) const
void get_block_ordered_preconditioner_vector (const DoubleVector &v, DoubleVector &w)
void return_block_ordered_preconditioner_vector (const DoubleVector &w, DoubleVector &v) const
unsigned nblock_types () const
Return the number of block types.
unsigned ndof_types () const
Return the total number of DOF types.
const Mesh * mesh_pt (const unsigned &i) const
unsigned nmesh () const
int block_number (const unsigned &i_dof) const
Return the block number corresponding to a global index i_dof.
int index_in_block (const unsigned &i_dof) const
const LinearAlgebraDistribution * block_distribution_pt (const unsigned &b) const
Access function to the block distributions (const version).
LinearAlgebraDistribution * block_distribution_pt (const unsigned b)
Access function to the block distributions (non-const version).
LinearAlgebraDistribution * dof_block_distribution_pt (const unsigned &b)
Access function to the dof-level block distributions.
const LinearAlgebraDistribution * master_distribution_pt () const
unsigned ndof_types_in_mesh (const unsigned &i) const
bool is_subsidiary_block_preconditioner () const
bool is_master_block_preconditioner () const
void set_block_output_to_files (const std::string &basefilename)
void disable_block_output_to_files ()
Turn off output of blocks (by clearing the basefilename string).
bool block_output_on () const
Test if output of blocks is on or not.
void output_blocks_to_files (const std::string &basefilename, const unsigned &precision=8) const
void post_block_matrix_assembly_partial_clear ()
BlockPreconditioner< MATRIX > * master_block_preconditioner_pt () const
Access function to the master block preconditioner pt.
void clear_block_preconditioner_base ()
void document ()
Vector< Vector< unsigned > > doftype_coarsen_map_fine () const
Vector< unsigned > get_fine_grain_dof_types_in (const unsigned &i) const
unsigned nfine_grain_dof_types_in (const unsigned &i) const
MapMatrix< unsigned, CRDoubleMatrix * > replacement_dof_block_pt () const
Access function to the replaced dof-level blocks.
void setup_matrix_vector_product (MatrixVectorProduct *matvec_prod_pt, CRDoubleMatrix *block_pt, const Vector< unsigned > &block_col_indices)
void setup_matrix_vector_product (MatrixVectorProduct *matvec_prod_pt, CRDoubleMatrix *block_pt, const unsigned &block_col_index)
void internal_get_block_ordered_preconditioner_vector (const DoubleVector &v, DoubleVector &w) const
void internal_return_block_ordered_preconditioner_vector (const DoubleVector &w, DoubleVector &v) const
unsigned internal_nblock_types () const
unsigned internal_ndof_types () const
void internal_return_block_vector (const unsigned &n, const DoubleVector &b, DoubleVector &v) const
void internal_get_block_vector (const unsigned &n, const DoubleVector &v, DoubleVector &b) const
void internal_get_block_vectors (const Vector< unsigned > &block_vec_number, const DoubleVector &v, Vector< DoubleVector > &s) const
void internal_get_block_vectors (const DoubleVector &v, Vector< DoubleVector > &s) const
void internal_return_block_vectors (const Vector< unsigned > &block_vec_number, const Vector< DoubleVector > &s, DoubleVector &v) const
void internal_return_block_vectors (const Vector< DoubleVector > &s, DoubleVector &v) const
void internal_get_block (const unsigned &i, const unsigned &j, MATRIX &output_block) const
int internal_block_number (const unsigned &i_dof) const
int internal_index_in_block (const unsigned &i_dof) const
const LinearAlgebraDistribution * internal_block_distribution_pt (const unsigned &b) const
Access function to the internal block distributions.
void insert_auxiliary_block_distribution (const Vector< unsigned > &block_vec_number, LinearAlgebraDistribution *dist_pt)
void block_matrix_test (const unsigned &i, const unsigned &j, const MATRIX *block_matrix_pt) const
template<typename myType >
int get_index_of_value (const Vector< myType > &vec, const myType val, const bool sorted=false) const
void internal_get_block (const unsigned &block_i, const unsigned &block_j, CRDoubleMatrix &output_block) const
void get_dof_level_block (const unsigned &block_i, const unsigned &block_j, CRDoubleMatrix &output_block, const bool &ignore_replacement_block) const
Public Member Functions inherited from oomph::Preconditioner
Preconditioner ()
Constructor.
Preconditioner (const Preconditioner &)=delete
Broken copy constructor.
void operator= (const Preconditioner &)=delete
Broken assignment operator.
virtual ~Preconditioner ()
Destructor (empty)
virtual void preconditioner_solve_transpose (const DoubleVector &r, DoubleVector &z)
void setup (DoubleMatrixBase *matrix_pt)
void setup (const Problem *problem_pt, DoubleMatrixBase *matrix_pt)
void enable_silent_preconditioner_setup ()
Set up the block preconditioner quietly!
void disable_silent_preconditioner_setup ()
Be verbose in the block preconditioner setup.
virtual void clean_up_memory ()
Clean up memory (empty). Generic interface function.
virtual void set_matrix_pt (DoubleMatrixBase *matrix_pt)
Set the matrix pointer.
virtual const OomphCommunicator * comm_pt () const
Get function for comm pointer.
virtual void set_comm_pt (const OomphCommunicator *const comm_pt)
Set the communicator pointer.
double setup_time () const
Returns the time to setup the preconditioner.
virtual void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse)
virtual void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse, const Vector< Vector< unsigned >> &doftype_coarsen_map_coarse)
Public Member Functions inherited from oomph::DistributableLinearAlgebraObject
DistributableLinearAlgebraObject ()
Default constructor - create a distribution.
DistributableLinearAlgebraObject (const DistributableLinearAlgebraObject &matrix)=delete
Broken copy constructor.
void operator= (const DistributableLinearAlgebraObject &)=delete
Broken assignment operator.
virtual ~DistributableLinearAlgebraObject ()
Destructor.
LinearAlgebraDistribution * distribution_pt () const
access to the LinearAlgebraDistribution
unsigned nrow () const
access function to the number of global rows.
unsigned nrow_local () const
access function for the num of local rows on this processor.
unsigned nrow_local (const unsigned &p) const
access function for the num of local rows on this processor.
unsigned first_row () const
access function for the first row on this processor
unsigned first_row (const unsigned &p) const
access function for the first row on this processor
bool distributed () const
distribution is serial or distributed
bool distribution_built () const
void build_distribution (const LinearAlgebraDistribution *const dist_pt)
void build_distribution (const LinearAlgebraDistribution &dist)
Private Attributes
MatrixVectorProduct * Off_diagonal_matrix_vector_product_pt
Pointer to matrix vector product operators for the off diagonal block.
Preconditioner * First_subsidiary_preconditioner_pt
Preconditioner * Second_subsidiary_preconditioner_pt
Mesh * Multi_poisson_mesh_pt
Additional Inherited Members
Protected Member Functions inherited from oomph::BlockPreconditioner< MATRIX >
void set_nmesh (const unsigned &n)
void set_mesh (const unsigned &i, const Mesh *const mesh_pt, const bool &allow_multiple_element_type_in_mesh=false)
void set_replacement_dof_block (const unsigned &block_i, const unsigned &block_j, CRDoubleMatrix *replacement_dof_block_pt)
bool any_mesh_distributed () const
int internal_dof_number (const unsigned &i_dof) const
unsigned internal_index_in_dof (const unsigned &i_dof) const
unsigned internal_block_dimension (const unsigned &b) const
unsigned internal_dof_block_dimension (const unsigned &i) const
unsigned master_nrow () const
unsigned internal_master_dof_number (const unsigned &b) const
const LinearAlgebraDistribution * internal_preconditioner_matrix_distribution_pt () const
const LinearAlgebraDistribution * preconditioner_matrix_distribution_pt () const
Protected Member Functions inherited from oomph::DistributableLinearAlgebraObject
void clear_distribution ()
Protected Attributes inherited from oomph::BlockPreconditioner< MATRIX >
MapMatrix< unsigned, CRDoubleMatrix * > Replacement_dof_block_pt
The replacement dof-level blocks.
Vector< LinearAlgebraDistribution * > Block_distribution_pt
The distribution for the blocks.
Vector< Vector< unsigned > > Block_to_dof_map_coarse
Vector< Vector< unsigned > > Block_to_dof_map_fine
Mapping for the block types to the most fine grain dof types.
Vector< Vector< unsigned > > Doftype_coarsen_map_coarse
Vector< Vector< unsigned > > Doftype_coarsen_map_fine
Vector< LinearAlgebraDistribution * > Internal_block_distribution_pt
Storage for the default distribution for each internal block.
Vector< LinearAlgebraDistribution * > Dof_block_distribution_pt
Vector< unsigned > Allow_multiple_element_type_in_mesh
Vector< const Mesh * > Mesh_pt
Vector< unsigned > Ndof_types_in_mesh
unsigned Internal_nblock_types
unsigned Internal_ndof_types
Protected Attributes inherited from oomph::Preconditioner
bool Silent_preconditioner_setup
Boolean to indicate whether or not the build should be done silently.
std::ostream * Stream_pt
Pointer to the output stream – defaults to std::cout.
Detailed Description
template<typename MATRIX>
class oomph::TwoPlusThreeUpperTriangularWithOneLevelSubsidiary< MATRIX >
///////////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////////// Upper block triangular with subsidiary block preconditioners for a system with 5 dof types.
Constructor & Destructor Documentation
TwoPlusThreeUpperTriangularWithOneLevelSubsidiary() [1/2]
template<typename MATRIX > oomph::TwoPlusThreeUpperTriangularWithOneLevelSubsidiary< MATRIX >::TwoPlusThreeUpperTriangularWithOneLevelSubsidiary () inline
Constructor.
                                                       :
    BlockPreconditioner<MATRIX>(),
     Off_diagonal_matrix_vector_product_pt(0),
     First_subsidiary_preconditioner_pt(0),
     Second_subsidiary_preconditioner_pt(0)
    {
     Multi_poisson_mesh_pt=0;
    }
References oomph::TwoPlusThreeUpperTriangularWithOneLevelSubsidiary< MATRIX >::Multi_poisson_mesh_pt.
~TwoPlusThreeUpperTriangularWithOneLevelSubsidiary()
template<typename MATRIX > virtual oomph::TwoPlusThreeUpperTriangularWithOneLevelSubsidiary< MATRIX >::~TwoPlusThreeUpperTriangularWithOneLevelSubsidiary () inline virtual
Destructor - delete the preconditioner matrices.
    {
     this->clean_up_my_memory();
    }
References oomph::TwoPlusThreeUpperTriangularWithOneLevelSubsidiary< MATRIX >::clean_up_my_memory().
TwoPlusThreeUpperTriangularWithOneLevelSubsidiary() [2/2]
template<typename MATRIX > oomph::TwoPlusThreeUpperTriangularWithOneLevelSubsidiary< MATRIX >::TwoPlusThreeUpperTriangularWithOneLevelSubsidiary (const TwoPlusThreeUpperTriangularWithOneLevelSubsidiary< MATRIX > &) inline
Broken copy constructor.
    {
     BrokenCopy::broken_copy
      ("TwoPlusThreeUpperTriangularWithOneLevelSubsidiary");
    }
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
clean_up_my_memory()
template<typename MATRIX > void oomph::TwoPlusThreeUpperTriangularWithOneLevelSubsidiary< MATRIX >::clean_up_my_memory
Clean up the memory.
The clean up function.
  {
   // Delete off-diagonal matrix vector product
   if(Off_diagonal_matrix_vector_product_pt!= 0)
    {
     delete Off_diagonal_matrix_vector_product_pt;
     Off_diagonal_matrix_vector_product_pt = 0;
    }
   //Clean up subsidiary preconditioners.
   if(First_subsidiary_preconditioner_pt!=0)
    {
     delete First_subsidiary_preconditioner_pt;
     First_subsidiary_preconditioner_pt = 0;
    }
   if(Second_subsidiary_preconditioner_pt!=0)
    {
     delete Second_subsidiary_preconditioner_pt;
     Second_subsidiary_preconditioner_pt = 0;
    }
  } // End of clean_up_my_memory function.
Referenced by oomph::TwoPlusThreeUpperTriangularWithOneLevelSubsidiary< MATRIX >::~TwoPlusThreeUpperTriangularWithOneLevelSubsidiary().
operator=()
template<typename MATRIX > void oomph::TwoPlusThreeUpperTriangularWithOneLevelSubsidiary< MATRIX >::operator= (const TwoPlusThreeUpperTriangularWithOneLevelSubsidiary< MATRIX > &) inline
Broken assignment operator.
    {
     BrokenCopy::broken_assign(
      "TwoPlusThreeUpperTriangularWithOneLevelSubsidiary");
    }
References oomph::BrokenCopy::broken_assign().
preconditioner_solve()
template<typename MATRIX > void oomph::TwoPlusThreeUpperTriangularWithOneLevelSubsidiary< MATRIX >::preconditioner_solve (const DoubleVector & r, DoubleVector & z) virtual
Apply preconditioner to r.
Preconditioner solve.
Implements oomph::Preconditioner.
  {
   // Solve "bottom right" (1,1) diagonal block system, using the
   // subsidiary block preconditioner that acts on the
   // "bottom right" 3x3 sub-system (only!). The subsidiary preconditioner
   // will extract the relevant (3x1) "sub-vectors" from the "big" (5x1)
   // vector z and treat it as the rhs, r, of P y = z
   // where P is 3x3 a block matrix. Once the system is solved,
   // the result is automatically put back into the appropriate places
   // of the "big" (5x1) vector y:
   Second_subsidiary_preconditioner_pt->preconditioner_solve(z,y);
   // Now extract the "bottom" (3x1) block vector from the full-size (5x1)
   // solution vector that we've just computed -- note that index 1
   // refers to the block enumeration in the current preconditioner
   // (which has two blocks!)
   DoubleVector block_y;
   this->get_block_vector(1,y,block_y);
   // Evaluate matrix vector product of just-extracted (3x1) solution
   // vector with off-diagonal block and store in temporary vector
   DoubleVector temp;
   Off_diagonal_matrix_vector_product_pt->multiply(block_y,temp);
   // Extract "upper" (2x1) block vector from full-size (5x1) rhs
   // vector (as passed into this function)...
   DoubleVector block_z;
   this->get_block_vector(0,z,block_z);
   // ...and subtract matrix vector product computed above
   block_z -= temp;
   // Block solve for first diagonal block. Since the associated subsidiary
   // preconditioner is a block preconditioner itself, it will extract
   // the required (2x1) block from a "big" (5x1) rhs vector.
   // Therefore we first put the actual (2x1) rhs vector block_z into a
   // "big" (5x1) vector big_z whose row distribution matches that of the
   // "big" right hand side vector, z, that was passed into this function.
   DoubleVector big_z(z.distribution_pt());
   this->return_block_vector(0,block_z,big_z);
   // Now apply the subsidiary block preconditioner that acts on the
   // "upper left" (2x2) sub-system (only!). The subsidiary preconditioner
   // will extract the relevant (2x1) block vector from the "big" (5x1)
   // vector big_r and treat it as the rhs, z, of its P y = z
   // where P is upper left 2x2 block diagonal of the big system.
   // Once the system is solved, the result is automatically put back
   // into the appropriate places of the "big" (5x1) vector y which is
   // returned by the current function, so no further action is required.
   First_subsidiary_preconditioner_pt->preconditioner_solve(big_z,y);
  }
References oomph::DistributableLinearAlgebraObject::distribution_pt(), and y.
set_multi_poisson_mesh()
template<typename MATRIX > void oomph::TwoPlusThreeUpperTriangularWithOneLevelSubsidiary< MATRIX >::set_multi_poisson_mesh (Mesh * multi_poisson_mesh_pt) inline
Specify the mesh that contains multi-poisson elements.
   {
    Multi_poisson_mesh_pt=multi_poisson_mesh_pt;
   }
References oomph::TwoPlusThreeUpperTriangularWithOneLevelSubsidiary< MATRIX >::Multi_poisson_mesh_pt.
Referenced by MultiPoissonProblem< ELEMENT >::MultiPoissonProblem().
setup() [1/4]
template<typename MATRIX > void oomph::TwoPlusThreeUpperTriangularWithOneLevelSubsidiary< MATRIX >::setup virtual
Setup the preconditioner.
The setup function.
Implements oomph::Preconditioner.
  {
   // clean the memory
   this->clean_up_my_memory();
 #ifdef PARANOID
   if (Multi_poisson_mesh_pt == 0)
    {
     std::stringstream err;
     err << "Please set pointer to mesh using set_multi_poisson_mesh(...).\n";
     throw OomphLibError(err.str(),
                         OOMPH_CURRENT_FUNCTION,
                         OOMPH_EXCEPTION_LOCATION);
    }
 #endif
   // The preconditioner works with one mesh; set it!
   this->set_nmesh(1);
   this->set_mesh(0,Multi_poisson_mesh_pt);
   // number of dof types
   unsigned n_dof_types = this->ndof_types();
 #ifdef PARANOID
   // This preconditioner only works for 5 dof types
   if (n_dof_types!=5)
    {
     std::stringstream tmp;
     tmp << "This preconditioner only works for problems with 5 dof types\n"
         << "Yours has " << n_dof_types;
     throw OomphLibError(tmp.str(),
                         OOMPH_CURRENT_FUNCTION,
                         OOMPH_EXCEPTION_LOCATION);
    }
 #endif
   // Combine "dof blocks" into two compound blocks, one containing dof
   // types 0 and 1, the final one dof types 2-4. In general we want:
   // dof_to_block_map[dof_type] = block type
   Vector<unsigned> dof_to_block_map(n_dof_types);
   dof_to_block_map[0]=0;
   dof_to_block_map[1]=0;
   dof_to_block_map[2]=1;
   dof_to_block_map[3]=1;
   dof_to_block_map[4]=1;
   this->block_setup(dof_to_block_map);
   // Create the subsidiary block preconditioners.
   {
    // Block upper triangular block preconditioner for compound
    // 2x2 top left block in "big" 5x5 matrix
    UpperTriangular<CRDoubleMatrix>* block_prec_pt=
     new UpperTriangular<CRDoubleMatrix>;
    First_subsidiary_preconditioner_pt=block_prec_pt;
    // Set mesh
    block_prec_pt->set_multi_poisson_mesh(Multi_poisson_mesh_pt);
    // Turn into a subsidiary preconditioner, declaring which
    // of the five dof types in the present (master) preconditioner
    // correspond to the dof types in the subsidiary block preconditioner:
    // dof_map[dof_block_ID_in_subsdiary] = dof_block_ID_in_master. Also
    // pass pointer to present (master) preconditioner.
    unsigned n_sub_dof_types=2;
    Vector<unsigned> dof_map(n_sub_dof_types);
    dof_map[0]=0;
    dof_map[1]=1;
    block_prec_pt->turn_into_subsidiary_block_preconditioner(this,dof_map);
    // Setup: Pass pointer to full-size matrix!
    block_prec_pt->setup(this->matrix_pt());
   }
   {
    // Block upper triangular for 3x3 bottom right block in "big" 5x5 matrix
    UpperTriangular<CRDoubleMatrix>* block_prec_pt=
     new UpperTriangular<CRDoubleMatrix>;
    Second_subsidiary_preconditioner_pt=block_prec_pt;
    // Set mesh
    block_prec_pt->set_multi_poisson_mesh(Multi_poisson_mesh_pt);
    // Turn second_sub into a subsidiary preconditioner, declaring which
    // of the five dof types in the present (master) preconditioner
    // correspond to the dof types in the subsidiary block preconditioner:
    // dof_map[dof_block_ID_in_subsdiary] = dof_block_ID_in_master. Also
    // pass pointer to present (master) preconditioner.
    unsigned n_sub_dof_types=3;
    Vector<unsigned> dof_map(n_sub_dof_types);
    dof_map[0]=2;
    dof_map[1]=3;
    dof_map[2]=4;
    block_prec_pt->turn_into_subsidiary_block_preconditioner(this,dof_map);
    // Setup: Pass pointer to full-size matrix!
    block_prec_pt->setup(this->matrix_pt());
   }
   // Setup the off-diagonal mat vec operator
   {
    // Get the off-diagonal block: the top-right block in the present
    // block preconditioner (which views the system matrix as comprising
    // 2x2 blocks).
    CRDoubleMatrix block_matrix = this->get_block(0,1);
    // Create matrix vector product
    Off_diagonal_matrix_vector_product_pt = new MatrixVectorProduct;
    // Setup: Final argument indicates block column in the present
    // block preconditioner (which views the system matrix as comprising
    // 2x2 blocks).
    unsigned block_column_index=1;
    this->setup_matrix_vector_product(
     Off_diagonal_matrix_vector_product_pt,&block_matrix,block_column_index);
   }
  }
References OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::UpperTriangular< MATRIX >::set_multi_poisson_mesh(), oomph::UpperTriangular< MATRIX >::setup(), tmp, and oomph::BlockPreconditioner< MATRIX >::turn_into_subsidiary_block_preconditioner().
setup() [2/4]
template<typename MATRIX > virtual void oomph::Preconditioner::setup virtual
Setup the preconditioner. Pure virtual generic interface function.
Implements oomph::Preconditioner.
setup() [3/4]
template<typename MATRIX > void oomph::Preconditioner::setup inline virtual
Compatability layer for old preconditioners where problem pointers were needed. The problem pointer is only used to get a communicator pointer.
Implements oomph::Preconditioner.
     {
       ObsoleteCode::obsolete();
       setup(matrix_pt);
     }
setup() [4/4]
template<typename MATRIX > void oomph::Preconditioner::setup inline virtual
Setup the preconditioner: store the matrix pointer and the communicator pointer then call preconditioner specific setup() function.
Implements oomph::Preconditioner.
     {
       // Store matrix pointer
       set_matrix_pt(matrix_pt);
       // Extract and store communicator pointer
       DistributableLinearAlgebraObject* dist_obj_pt =
         dynamic_cast<DistributableLinearAlgebraObject*>(matrix_pt);
       if (dist_obj_pt != 0)
       {
         set_comm_pt(dist_obj_pt->distribution_pt()->communicator_pt());
       }
       else
       {
         set_comm_pt(0);
       }
       double setup_time_start = TimingHelpers::timer();
       setup();
       double setup_time_finish = TimingHelpers::timer();
       Setup_time = setup_time_finish - setup_time_start;
     }
Member Data Documentation
First_subsidiary_preconditioner_pt
template<typename MATRIX > Preconditioner* oomph::TwoPlusThreeUpperTriangularWithOneLevelSubsidiary< MATRIX >::First_subsidiary_preconditioner_pt private
Pointer to preconditioners/inexact solver for (0,0) block
Multi_poisson_mesh_pt
template<typename MATRIX > Mesh* oomph::TwoPlusThreeUpperTriangularWithOneLevelSubsidiary< MATRIX >::Multi_poisson_mesh_pt private
Pointer to mesh with preconditionable elements used for classification of dof types.
Referenced by oomph::TwoPlusThreeUpperTriangularWithOneLevelSubsidiary< MATRIX >::set_multi_poisson_mesh(), and oomph::TwoPlusThreeUpperTriangularWithOneLevelSubsidiary< MATRIX >::TwoPlusThreeUpperTriangularWithOneLevelSubsidiary().
Off_diagonal_matrix_vector_product_pt
template<typename MATRIX > MatrixVectorProduct* oomph::TwoPlusThreeUpperTriangularWithOneLevelSubsidiary< MATRIX >::Off_diagonal_matrix_vector_product_pt private
Pointer to matrix vector product operators for the off diagonal block.
Second_subsidiary_preconditioner_pt
template<typename MATRIX > Preconditioner* oomph::TwoPlusThreeUpperTriangularWithOneLevelSubsidiary< MATRIX >::Second_subsidiary_preconditioner_pt private
Pointer to preconditioners/inexact solver for (1,1) block
The documentation for this class was generated from the following file:
multi_poisson_block_preconditioners.h