MercuryDPM: oomph::EBDF3 Class Reference
oomph::EBDF3 Class Reference
#include <explicit_timesteppers.h>
Public Member Functions
EBDF3 ()
Constructor, set the type.
EBDF3 (const EBDF3 &)=delete
Broken copy constructor.
void operator= (const EBDF3 &)=delete
Broken assignment operator.
void set_weights (const double &dtn, const double &dtnm1, const double &dtnm2)
Calculate the weights for this set of step sizes.
void timestep (ExplicitTimeSteppableObject *const &object_pt, const double &dt)
Function that is used to advance the solution by time dt.
Public Member Functions inherited from oomph::ExplicitTimeStepper
ExplicitTimeStepper ()
Empty Constructor.
ExplicitTimeStepper (const ExplicitTimeStepper &)=delete
Broken copy constructor.
void operator= (const ExplicitTimeStepper &)=delete
Broken assignment operator.
virtual ~ExplicitTimeStepper ()
Empty virtual destructor — no memory is allocated in this class.
Private Attributes
double Yn_weight
double Ynm1_weight
double Ynm2_weight
double Fn_weight
Additional Inherited Members
Protected Attributes inherited from oomph::ExplicitTimeStepper
std::string Type
Detailed Description
=========================================================== An explicit version of BDF3 (i.e. uses derivative evaluation at y_n instead of y_{n+1}). Useful as a predictor because it is third order accurate but requires only one function evaluation (i.e. only one mass matrix inversion + residual calculation).
Constructor & Destructor Documentation
EBDF3() [1/2]
oomph::EBDF3::EBDF3 () inline
Constructor, set the type.
 {}
EBDF3() [2/2]
oomph::EBDF3::EBDF3 (const EBDF3 &) delete
Broken copy constructor.
Member Function Documentation
operator=()
void oomph::EBDF3::operator= (const EBDF3 &) delete
Broken assignment operator.
set_weights()
void oomph::EBDF3::set_weights (const double & dtn, const double & dtnm1, const double & dtnm2)
Calculate the weights for this set of step sizes.
   {
     using namespace std;
     // If this is slow we can probably optimise by doing direct
     // multiplication instead of using pow.
     // Generated using sympy from my python ode code.
     double denom = pow(dtnm1, 4) * dtnm2 + 2 * pow(dtnm1, 3) * pow(dtnm2, 2) +
                    pow(dtnm1, 2) * pow(dtnm2, 3);
     Yn_weight =
       -(2 * pow(dtn, 3) * dtnm1 * dtnm2 + pow(dtn, 3) * pow(dtnm2, 2) +
         3 * pow(dtn, 2) * pow(dtnm1, 2) * dtnm2 +
         3 * pow(dtn, 2) * dtnm1 * pow(dtnm2, 2) + pow(dtn, 2) * pow(dtnm2, 3) -
         pow(dtnm1, 4) * dtnm2 - 2 * pow(dtnm1, 3) * pow(dtnm2, 2) -
         pow(dtnm1, 2) * pow(dtnm2, 3)) /
       denom;
     Ynm1_weight =
       -(-pow(dtn, 3) * pow(dtnm1, 2) - 2 * pow(dtn, 3) * dtnm1 * dtnm2 -
         pow(dtn, 3) * pow(dtnm2, 2) - pow(dtn, 2) * pow(dtnm1, 3) -
         3 * pow(dtn, 2) * pow(dtnm1, 2) * dtnm2 -
         3 * pow(dtn, 2) * dtnm1 * pow(dtnm2, 2) - pow(dtn, 2) * pow(dtnm2, 3)) /
       denom;
     Ynm2_weight =
       -(pow(dtn, 3) * pow(dtnm1, 2) + pow(dtn, 2) * pow(dtnm1, 3)) / denom;
     Fn_weight =
       -(-pow(dtn, 3) * pow(dtnm1, 2) * dtnm2 -
         pow(dtn, 3) * dtnm1 * pow(dtnm2, 2) -
         2 * pow(dtn, 2) * pow(dtnm1, 3) * dtnm2 -
         3 * pow(dtn, 2) * pow(dtnm1, 2) * pow(dtnm2, 2) -
         pow(dtn, 2) * dtnm1 * pow(dtnm2, 3) - dtn * pow(dtnm1, 4) * dtnm2 -
         2 * dtn * pow(dtnm1, 3) * pow(dtnm2, 2) -
         dtn * pow(dtnm1, 2) * pow(dtnm2, 3)) /
       denom;
   }
References Fn_weight, Eigen::bfloat16_impl::pow(), Yn_weight, Ynm1_weight, and Ynm2_weight.
Referenced by timestep().
timestep()
void oomph::EBDF3::timestep (ExplicitTimeSteppableObject *const & object_pt, const double & dt) virtual
Function that is used to advance the solution by time dt.
Implements oomph::ExplicitTimeStepper.
   {
     using namespace StringConversion;
     object_pt->actions_before_explicit_timestep();
     object_pt->actions_before_explicit_stage();
     // Storage indicies for the history values that we need
     unsigned tn = 1;
     unsigned tnm1 = tn + 1;
     unsigned tnm2 = tnm1 + 1;
     // Check dts are the same, this will need to be removed if ebdf3 is being
     // used as something other than a predictor... But seeing as it isn't
     // stable that isn't likely.
 #ifdef PARANOID
     if (std::abs(dt - object_pt->time_pt()->dt(0)) > 1e-15)
     {
       std::string err =
         "Inconsistent dts! Predictor is stepping by " + to_string(dt);
       err += " but dt(0) = " + to_string(object_pt->time_pt()->dt(0));
       throw OomphLibError(
         err, OOMPH_EXCEPTION_LOCATION, OOMPH_CURRENT_FUNCTION);
     }
 #endif
     // Get older dt values
     double dtnm1 = object_pt->time_pt()->dt(1);
     double dtnm2 = object_pt->time_pt()->dt(2);
     // Calculate weights for these dts
     set_weights(dt, dtnm1, dtnm2);
     // Get derivative value at step n (even though this uses values from t=0 =
     // step n+1, it's ok because we haven't changed the values in that slot
     // yet).
     DoubleVector fn;
     object_pt->get_dvaluesdt(fn);
     fn *= Fn_weight;
     // Extract history values and multiply by their weights
     DoubleVector ynp1, yn, ynm1, ynm2;
     object_pt->get_dofs(tn, yn);
     yn *= Yn_weight;
     object_pt->get_dofs(tnm1, ynm1);
     ynm1 *= Ynm1_weight;
     object_pt->get_dofs(tnm2, ynm2);
     ynm2 *= Ynm2_weight;
     // Add everything together
     ynp1 = yn;
     ynp1 += ynm1;
     ynp1 += ynm2;
     ynp1 += fn;
     // Done, update things in the object
     object_pt->set_dofs(ynp1);
     object_pt->time() += dt;
     // Actions functions
     object_pt->actions_after_explicit_stage();
     object_pt->actions_after_explicit_timestep();
   }
References abs(), oomph::ExplicitTimeSteppableObject::actions_after_explicit_stage(), oomph::ExplicitTimeSteppableObject::actions_after_explicit_timestep(), oomph::ExplicitTimeSteppableObject::actions_before_explicit_stage(), oomph::ExplicitTimeSteppableObject::actions_before_explicit_timestep(), oomph::Time::dt(), e(), Fn_weight, oomph::ExplicitTimeSteppableObject::get_dofs(), oomph::ExplicitTimeSteppableObject::get_dvaluesdt(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::ExplicitTimeSteppableObject::set_dofs(), set_weights(), oomph::Global_string_for_annotation::string(), oomph::ExplicitTimeSteppableObject::time(), oomph::ExplicitTimeSteppableObject::time_pt(), oomph::StringConversion::to_string(), Yn_weight, Ynm1_weight, and Ynm2_weight.
Member Data Documentation
Fn_weight
double oomph::EBDF3::Fn_weight private
Referenced by set_weights(), and timestep().
Yn_weight
double oomph::EBDF3::Yn_weight private
Referenced by set_weights(), and timestep().
Ynm1_weight
double oomph::EBDF3::Ynm1_weight private
Referenced by set_weights(), and timestep().
Ynm2_weight
double oomph::EBDF3::Ynm2_weight private
Referenced by set_weights(), and timestep().
The documentation for this class was generated from the following files:
explicit_timesteppers.h
explicit_timesteppers.cc