MercuryDPM: oomph::ChannelWithLeafletMesh< ELEMENT > Class Template Reference
oomph::ChannelWithLeafletMesh< ELEMENT > Class Template Reference
Channel with leaflet mesh.
#include <channel_with_leaflet_mesh.template.h>
Public Member Functions
ChannelWithLeafletMesh (GeomObject *leaflet_pt, const double &lleft, const double &lright, const double &hleaflet, const double &htot, const unsigned &nleft, const unsigned &nright, const unsigned &ny1, const unsigned &ny2, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
virtual ~ChannelWithLeafletMesh ()
Destructor : empty.
ChannelWithLeafletDomain * domain_pt ()
Access function to domain.
Public Member Functions inherited from oomph::SimpleRectangularQuadMesh< ELEMENT >
SimpleRectangularQuadMesh (const unsigned &Nx, const unsigned &Ny, const double &Lx, const double &Ly, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
const unsigned & nx () const
Access function for number of elements in x directions.
const unsigned & ny () const
Access function for number of elements in y directions.
Public Member Functions inherited from oomph::QuadMeshBase
QuadMeshBase ()
Constructor (empty)
QuadMeshBase (const QuadMeshBase &node)=delete
Broken copy constructor.
void operator= (const QuadMeshBase &)=delete
Broken assignment operator.
virtual ~QuadMeshBase ()
Destructor (empty)
void setup_boundary_element_info ()
void setup_boundary_element_info (std::ostream &outfile)
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void node_update (const bool &update_all_solid_nodes=false)
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Protected Attributes
ChannelWithLeafletDomain * Domain_pt
Pointer to domain.
GeomObject * Leaflet_pt
Pointer to GeomObject that represents the leaflet.
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Detailed Description
template<class ELEMENT>
class oomph::ChannelWithLeafletMesh< ELEMENT >
Channel with leaflet mesh.
Constructor & Destructor Documentation
ChannelWithLeafletMesh()
template<class ELEMENT > oomph::ChannelWithLeafletMesh< ELEMENT >::ChannelWithLeafletMesh (GeomObject * leaflet_pt, const double & lleft, const double & lright, const double & hleaflet, const double & htot, const unsigned & nleft, const unsigned & nright, const unsigned & ny1, const unsigned & ny2, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
Constructor: Pass pointer to GeomObject that represents the leaflet, the length of the domain to left and right of the leaflet, the height of the leaflet and the overall height of the channel, the number of element columns to the left and right of the leaflet, the number of rows of elements from the bottom of the channel to the end of the leaflet, the number of rows of elements above the end of the leaflet. Timestepper defaults to Steady default Timestepper defined in the Mesh base class
     : SimpleRectangularQuadMesh<ELEMENT>(
         nright + nleft, ny1 + ny2, lright + lleft, htot, time_stepper_pt)
   {
     // Mesh can only be built with 2D Qelements.
     MeshChecker::assert_geometric_element<QElementGeometricBase, ELEMENT>(2);
     // Copy pointer to leaflet into private storage
     Leaflet_pt = leaflet_pt;
     // Create the ChannelWithLeafletDomain with the wall
     // represented by the geometric object
     Domain_pt = new ChannelWithLeafletDomain(
       leaflet_pt, lleft, lright, hleaflet, htot, nleft, nright, ny1, ny2);
     // Total number of (macro/finite)elements
     unsigned nmacro = (ny1 + ny2) * (nleft + nright);
     // Loop over all elements and set macro element pointer
     for (unsigned e = 0; e < nmacro; e++)
     {
       // Get pointer to finite element
       FiniteElement* el_pt = this->finite_element_pt(e);
       // Set pointer to macro element
       el_pt->set_macro_elem_pt(this->Domain_pt->macro_element_pt(e));
     }
     // Update the nodal positions corresponding to their
     // macro element representations.
     this->node_update();
     // Change the numbers of boundaries
     this->set_nboundary(7);
     // Remove the nodes of boundary 0
     this->remove_boundary_nodes(0);
     // Get the number of nodes along the element edge from first element
     unsigned nnode_1d = this->finite_element_pt(0)->nnode_1d();
     // Boundary 0 will be before the wall, boundary 6 after it
     for (unsigned e = 0; e < nleft; e++)
     {
       for (unsigned i = 0; i < nnode_1d; i++)
       {
         Node* nod_pt = this->finite_element_pt(e)->node_pt(i);
         // do not add the last node : it will go to boundary 6
         if (e != nleft - 1 || i != 2)
         {
           this->add_boundary_node(0, nod_pt);
         }
       }
     }
     for (unsigned e = nleft; e < nleft + nright; e++)
     {
       for (unsigned i = 0; i < nnode_1d; i++)
       {
         Node* nod_pt = this->finite_element_pt(e)->node_pt(i);
         this->add_boundary_node(6, nod_pt);
       }
     }
     // Vector of Lagrangian coordinates used as boundary coordinate
     Vector<double> zeta(1);
     // Set the wall as a boundary
     for (unsigned k = 0; k < ny1; k++)
     {
       unsigned e = (nleft + nright) * k + nleft - 1;
       for (unsigned i = 0; i < nnode_1d; i++)
       {
         Node* nod_pt =
           this->finite_element_pt(e)->node_pt((i + 1) * nnode_1d - 1);
         this->convert_to_boundary_node(nod_pt);
         this->add_boundary_node(4, nod_pt);
         // Set coordinates
         zeta[0] = double(k) * hleaflet / double(ny1) +
                   double(i) * hleaflet / double(ny1) / double(nnode_1d - 1);
         nod_pt->set_coordinates_on_boundary(4, zeta);
       }
     }
     // Duplicate the nodes of the wall and assign then as a boundary.
     // This will make one boundary for the east of the elements at the
     // left of the wall, and one for the west of the elements at the right
     // of the wall.
     // This is necessary to use TaylorHoodElements, because it will allow
     // a discontinuity of the pressure accross the wall.
     // We separate the lower element from the rest as we do not want to
     // add the same node twice to the boundary, and the upper element as its
     // upper node must be the same one than the node of the upper element
     // at the right of the wall
     // Lower element
     unsigned e = nleft - 1;
     // Allocate storage for newly created node outside
     // so we can refer to the most recently created one below.
     Node* nod_pt = 0;
     // duplicate the east nodes and add them to the 6th boundary
     // Add the first node to the 0th boundary (horizontal)
     for (unsigned i = 0; i < nnode_1d; i++)
     {
       nod_pt = this->finite_element_pt(e)->construct_boundary_node(
         (i + 1) * nnode_1d - 1, time_stepper_pt);
       this->add_boundary_node(5, nod_pt);
       if (i == 0)
       {
         this->add_boundary_node(0, nod_pt);
       }
       this->add_node_pt(nod_pt);
       // Set coordinates
       zeta[0] = i * hleaflet / double(ny1) / double(nnode_1d - 1);
       nod_pt->set_coordinates_on_boundary(5, zeta);
     }
     // Other elements just at the left of the wall
     for (unsigned k = 1; k < ny1; k++)
     {
       e = (nleft + nright) * k + nleft - 1;
       // add the upper node of the previous element
       this->finite_element_pt(e)->node_pt(nnode_1d - 1) = nod_pt;
       this->add_boundary_node(5, nod_pt);
       // Set coordinates
       zeta[0] = k * hleaflet / double(ny1);
       nod_pt->set_coordinates_on_boundary(5, zeta);
       // Loop over other nodes on element's eastern edge
       for (unsigned i = 1; i < nnode_1d; i++)
       {
         // Don't duplicate the node at the very top of the "obstacle"
         if ((k == ny1 - 1) && (i == nnode_1d - 1))
         {
           // Get the node but don't do anything else
           nod_pt = this->finite_element_pt(e)->node_pt(nnode_1d * nnode_1d - 1);
         }
         else
         {
           // Overwrite the node with a boundary node
           nod_pt = this->finite_element_pt(e)->construct_boundary_node(
             (i + 1) * nnode_1d - 1, time_stepper_pt);
           this->add_node_pt(nod_pt);
         }
         // Add node to boundary
         this->add_boundary_node(5, nod_pt);
         // Set coordinates
         zeta[0] = double(k) * hleaflet / double(ny1) +
                   double(i) * hleaflet / double(ny1) / double(nnode_1d - 1);
         nod_pt->set_coordinates_on_boundary(5, zeta);
       }
     }
     this->node_update();
     // Re-setup lookup scheme that establishes which elements are located
     // on the mesh boundaries (doesn't need to be wiped)
     this->setup_boundary_element_info();
     // We have parametrised boundary 4 and 5
     this->Boundary_coordinate_exists[4] = true;
     this->Boundary_coordinate_exists[5] = true;
   } // end of constructor
References oomph::Mesh::add_boundary_node(), oomph::Mesh::add_node_pt(), oomph::Mesh::Boundary_coordinate_exists, oomph::FiniteElement::construct_boundary_node(), oomph::Mesh::convert_to_boundary_node(), oomph::ChannelWithLeafletMesh< ELEMENT >::Domain_pt, e(), oomph::Mesh::finite_element_pt(), i, k, oomph::ChannelWithLeafletMesh< ELEMENT >::Leaflet_pt, oomph::Domain::macro_element_pt(), oomph::FiniteElement::nnode_1d(), oomph::FiniteElement::node_pt(), oomph::Mesh::node_update(), oomph::Mesh::remove_boundary_nodes(), oomph::Node::set_coordinates_on_boundary(), oomph::FiniteElement::set_macro_elem_pt(), oomph::Mesh::set_nboundary(), oomph::QuadMeshBase::setup_boundary_element_info(), and Eigen::zeta().
~ChannelWithLeafletMesh()
template<class ELEMENT > virtual oomph::ChannelWithLeafletMesh< ELEMENT >::~ChannelWithLeafletMesh () inline virtual
Destructor : empty.
 {}
Member Function Documentation
domain_pt()
template<class ELEMENT > ChannelWithLeafletDomain* oomph::ChannelWithLeafletMesh< ELEMENT >::domain_pt () inline
Access function to domain.
     {
       return Domain_pt;
     }
References oomph::ChannelWithLeafletMesh< ELEMENT >::Domain_pt.
Referenced by oomph::MacroElementNodeUpdateChannelWithLeafletMesh< ELEMENT >::MacroElementNodeUpdateChannelWithLeafletMesh().
Member Data Documentation
Domain_pt
template<class ELEMENT > ChannelWithLeafletDomain* oomph::ChannelWithLeafletMesh< ELEMENT >::Domain_pt protected
Pointer to domain.
Referenced by oomph::ChannelWithLeafletMesh< ELEMENT >::ChannelWithLeafletMesh(), and oomph::ChannelWithLeafletMesh< ELEMENT >::domain_pt().
Leaflet_pt
template<class ELEMENT > GeomObject* oomph::ChannelWithLeafletMesh< ELEMENT >::Leaflet_pt protected
Pointer to GeomObject that represents the leaflet.
Referenced by oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::AlgebraicChannelWithLeafletMesh(), oomph::ChannelWithLeafletMesh< ELEMENT >::ChannelWithLeafletMesh(), and oomph::MacroElementNodeUpdateChannelWithLeafletMesh< ELEMENT >::MacroElementNodeUpdateChannelWithLeafletMesh().
The documentation for this class was generated from the following files:
channel_with_leaflet_mesh.template.h
channel_with_leaflet_mesh.template.cc