MercuryDPM: RefineableDrivenCavityProblem< ELEMENT > Class Template Reference
RefineableDrivenCavityProblem< ELEMENT > Class Template Reference
Public Member Functions
RefineableDrivenCavityProblem ()
Constructor.
~RefineableDrivenCavityProblem ()
Destructor: Empty.
void actions_after_newton_solve ()
Update the after solve (empty)
void actions_before_newton_solve ()
void actions_after_adapt ()
After adaptation: Unpin pressure and pin redundant pressure dofs.
void doc_solution (DocInfo &doc_info)
Doc the solution.
RefineableDrivenCavityProblem ()
Constructor.
~RefineableDrivenCavityProblem ()
Destructor: Empty.
void actions_after_newton_solve ()
Update the after solve (empty)
void actions_before_newton_solve ()
void actions_after_adapt ()
void build_mesh ()
Build the mesh.
void doc_solution (const std::string &header)
Doc the solution.
RefineableDrivenCavityProblem ()
Constructor.
~RefineableDrivenCavityProblem ()
Destructor: Empty.
void actions_after_newton_solve ()
Update the after solve (empty)
void actions_before_newton_solve ()
void actions_after_adapt ()
After adaptation: Unpin pressure and pin redundant pressure dofs.
void doc_solution (DocInfo &doc_info)
Doc the solution.
RefineableDrivenCavityProblem ()
Constructor.
~RefineableDrivenCavityProblem ()
Destructor: Empty.
void actions_after_newton_solve ()
Update the after solve (empty)
void actions_before_newton_solve ()
void actions_after_adapt ()
After adaptation: Unpin pressure and pin redudant pressure dofs.
void doc_solution (DocInfo &doc_info)
Doc the solution.
RefineableDrivenCavityProblem ()
Constructor.
~RefineableDrivenCavityProblem ()
Destructor: Empty.
void actions_after_newton_solve ()
Update the after solve (empty)
void actions_before_newton_solve ()
void actions_after_adapt ()
After adaptation: Unpin pressure and pin redudant pressure dofs.
void doc_solution (DocInfo &doc_info)
Doc the solution.
void setup_line_plot_points ()
Build line plot points.
RefineableDrivenCavityProblem ()
Constructor.
~RefineableDrivenCavityProblem ()
Destructor: Empty.
void actions_after_newton_solve ()
Update the after solve (empty)
void actions_before_newton_solve ()
void actions_before_adapt ()
Before adaptation.
void actions_after_adapt ()
After adaptation: Unpin pressure and pin redudant pressure dofs.
void doc_solution (DocInfo &doc_info)
Doc the solution.
RefineableDrivenCavityProblem ()
Constructor.
~RefineableDrivenCavityProblem ()
Destructor: Empty.
void actions_after_newton_solve ()
Update the after solve (empty)
void actions_before_newton_solve ()
void actions_before_adapt ()
Before adaptation.
void actions_after_adapt ()
After adaptation: Unpin pressure and pin redundant pressure dofs.
void doc_solution (DocInfo &doc_info)
Doc the solution.
Public Member Functions inherited from oomph::Problem
virtual void debug_hook_fct (const unsigned &i)
void set_analytic_dparameter (double *const &parameter_pt)
void unset_analytic_dparameter (double *const &parameter_pt)
bool is_dparameter_calculated_analytically (double *const &parameter_pt)
void set_analytic_hessian_products ()
void unset_analytic_hessian_products ()
bool are_hessian_products_calculated_analytically ()
void set_pinned_values_to_zero ()
bool distributed () const
OomphCommunicator * communicator_pt ()
access function to the oomph-lib communicator
const OomphCommunicator * communicator_pt () const
access function to the oomph-lib communicator, const version
Problem ()
Problem (const Problem &dummy)=delete
Broken copy constructor.
void operator= (const Problem &)=delete
Broken assignment operator.
virtual ~Problem ()
Virtual destructor to clean up memory.
Mesh *& mesh_pt ()
Return a pointer to the global mesh.
Mesh *const & mesh_pt () const
Return a pointer to the global mesh (const version)
Mesh *& mesh_pt (const unsigned &imesh)
Mesh *const & mesh_pt (const unsigned &imesh) const
Return a pointer to the i-th submesh (const version)
unsigned nsub_mesh () const
Return number of submeshes.
unsigned add_sub_mesh (Mesh *const &mesh_pt)
void flush_sub_meshes ()
void build_global_mesh ()
void rebuild_global_mesh ()
LinearSolver *& linear_solver_pt ()
Return a pointer to the linear solver object.
LinearSolver *const & linear_solver_pt () const
Return a pointer to the linear solver object (const version)
LinearSolver *& mass_matrix_solver_for_explicit_timestepper_pt ()
LinearSolver * mass_matrix_solver_for_explicit_timestepper_pt () const
EigenSolver *& eigen_solver_pt ()
Return a pointer to the eigen solver object.
EigenSolver *const & eigen_solver_pt () const
Return a pointer to the eigen solver object (const version)
Time *& time_pt ()
Return a pointer to the global time object.
Time * time_pt () const
Return a pointer to the global time object (const version).
double & time ()
Return the current value of continuous time.
double time () const
Return the current value of continuous time (const version)
TimeStepper *& time_stepper_pt ()
const TimeStepper * time_stepper_pt () const
TimeStepper *& time_stepper_pt (const unsigned &i)
Return a pointer to the i-th timestepper.
ExplicitTimeStepper *& explicit_time_stepper_pt ()
Return a pointer to the explicit timestepper.
unsigned long set_timestepper_for_all_data (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data=false)
virtual void shift_time_values ()
Shift all values along to prepare for next timestep.
AssemblyHandler *& assembly_handler_pt ()
Return a pointer to the assembly handler object.
AssemblyHandler *const & assembly_handler_pt () const
Return a pointer to the assembly handler object (const version)
double & minimum_dt ()
Access function to min timestep in adaptive timestepping.
double & maximum_dt ()
Access function to max timestep in adaptive timestepping.
unsigned & max_newton_iterations ()
Access function to max Newton iterations before giving up.
void problem_is_nonlinear (const bool &prob_lin)
Access function to Problem_is_nonlinear.
double & max_residuals ()
bool & time_adaptive_newton_crash_on_solve_fail ()
Access function for Time_adaptive_newton_crash_on_solve_fail.
double & newton_solver_tolerance ()
void add_time_stepper_pt (TimeStepper *const &time_stepper_pt)
void set_explicit_time_stepper_pt (ExplicitTimeStepper *const &explicit_time_stepper_pt)
void initialise_dt (const double &dt)
void initialise_dt (const Vector< double > &dt)
Data *& global_data_pt (const unsigned &i)
Return a pointer to the the i-th global data object.
void add_global_data (Data *const &global_data_pt)
void flush_global_data ()
LinearAlgebraDistribution *const & dof_distribution_pt () const
Return the pointer to the dof distribution (read-only)
unsigned long ndof () const
Return the number of dofs.
unsigned ntime_stepper () const
Return the number of time steppers.
unsigned nglobal_data () const
Return the number of global data values.
unsigned self_test ()
Self-test: Check meshes and global data. Return 0 for OK.
void enable_store_local_dof_pt_in_elements ()
void disable_store_local_dof_pt_in_elements ()
unsigned long assign_eqn_numbers (const bool &assign_local_eqn_numbers=true)
void describe_dofs (std::ostream &out= *(oomph_info.stream_pt())) const
void enable_discontinuous_formulation ()
void disable_discontinuous_formulation ()
void get_dofs (DoubleVector &dofs) const
void get_dofs (const unsigned &t, DoubleVector &dofs) const
Return vector of the t'th history value of all dofs.
void set_dofs (const DoubleVector &dofs)
Set the values of the dofs.
void set_dofs (const unsigned &t, DoubleVector &dofs)
Set the history values of the dofs.
void set_dofs (const unsigned &t, Vector< double * > &dof_pt)
void add_to_dofs (const double &lambda, const DoubleVector &increment_dofs)
Add lambda x incremenet_dofs[l] to the l-th dof.
double * global_dof_pt (const unsigned &i)
double & dof (const unsigned &i)
i-th dof in the problem
double dof (const unsigned &i) const
i-th dof in the problem (const version)
double *& dof_pt (const unsigned &i)
Pointer to i-th dof in the problem.
double * dof_pt (const unsigned &i) const
Pointer to i-th dof in the problem (const version)
virtual void get_inverse_mass_matrix_times_residuals (DoubleVector &Mres)
virtual void get_dvaluesdt (DoubleVector &f)
virtual void get_residuals (DoubleVector &residuals)
Get the total residuals Vector for the problem.
virtual void get_jacobian (DoubleVector &residuals, DenseDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CRDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CCDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, SumOfMatrices &jacobian)
void get_fd_jacobian (DoubleVector &residuals, DenseMatrix< double > &jacobian)
Get the full Jacobian by finite differencing.
void get_derivative_wrt_global_parameter (double *const &parameter_pt, DoubleVector &result)
void get_hessian_vector_products (DoubleVectorWithHaloEntries const &Y, Vector< DoubleVectorWithHaloEntries > const &C, Vector< DoubleVectorWithHaloEntries > &product)
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, Vector< DoubleVector > &eigenvector, const bool &steady=true)
Solve the eigenproblem.
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, const bool &steady=true)
virtual void get_eigenproblem_matrices (CRDoubleMatrix &mass_matrix, CRDoubleMatrix &main_matrix, const double &shift=0.0)
void assign_eigenvector_to_dofs (DoubleVector &eigenvector)
Assign the eigenvector passed to the function to the dofs.
void add_eigenvector_to_dofs (const double &epsilon, const DoubleVector &eigenvector)
void store_current_dof_values ()
Store the current values of the degrees of freedom.
void restore_dof_values ()
Restore the stored values of the degrees of freedom.
void enable_jacobian_reuse ()
void disable_jacobian_reuse ()
Disable recycling of Jacobian in Newton iteration.
bool jacobian_reuse_is_enabled ()
Is recycling of Jacobian in Newton iteration enabled?
bool & use_predictor_values_as_initial_guess ()
void newton_solve ()
Use Newton method to solve the problem.
void enable_globally_convergent_newton_method ()
enable globally convergent Newton method
void disable_globally_convergent_newton_method ()
disable globally convergent Newton method
void newton_solve (unsigned const &max_adapt)
void steady_newton_solve (unsigned const &max_adapt=0)
void copy (Problem *orig_problem_pt)
virtual Problem * make_copy ()
virtual void read (std::ifstream &restart_file, bool &unsteady_restart)
virtual void read (std::ifstream &restart_file)
virtual void dump (std::ofstream &dump_file) const
void dump (const std::string &dump_file_name) const
void delete_all_external_storage ()
virtual void symmetrise_eigenfunction_for_adaptive_pitchfork_tracking ()
double * bifurcation_parameter_pt () const
void get_bifurcation_eigenfunction (Vector< DoubleVector > &eigenfunction)
void activate_fold_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const DoubleVector &normalisation, const bool &block_solve=true)
void activate_pitchfork_tracking (double *const &parameter_pt, const DoubleVector &symmetry_vector, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const double &omega, const DoubleVector &null_real, const DoubleVector &null_imag, const bool &block_solve=true)
void deactivate_bifurcation_tracking ()
void reset_assembly_handler_to_default ()
Reset the system to the standard non-augemented state.
double arc_length_step_solve (double *const &parameter_pt, const double &ds, const unsigned &max_adapt=0)
double arc_length_step_solve (Data *const &data_pt, const unsigned &data_index, const double &ds, const unsigned &max_adapt=0)
void reset_arc_length_parameters ()
int & sign_of_jacobian ()
void explicit_timestep (const double &dt, const bool &shift_values=true)
Take an explicit timestep of size dt.
void unsteady_newton_solve (const double &dt)
void unsteady_newton_solve (const double &dt, const bool &shift_values)
void unsteady_newton_solve (const double &dt, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const unsigned &suppress_resolve_after_spatial_adapt_flag, const bool &first, const bool &shift=true)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon, const bool &shift_values)
void assign_initial_values_impulsive ()
void assign_initial_values_impulsive (const double &dt)
void calculate_predictions ()
Calculate predictions.
void enable_mass_matrix_reuse ()
void disable_mass_matrix_reuse ()
bool mass_matrix_reuse_is_enabled ()
Return whether the mass matrix is being reused.
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly (DocInfo &doc_info)
void refine_uniformly_and_prune (DocInfo &doc_info)
void refine_uniformly ()
void refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform refinement for submesh i_mesh with documentation.
void refine_uniformly (const unsigned &i_mesh)
Do uniform refinement for submesh i_mesh without documentation.
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly (DocInfo &doc_info)
void p_refine_uniformly_and_prune (DocInfo &doc_info)
void p_refine_uniformly ()
void p_refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-refinement for submesh i_mesh with documentation.
void p_refine_uniformly (const unsigned &i_mesh)
Do uniform p-refinement for submesh i_mesh without documentation.
void refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const unsigned &i_mesh, const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void refine_selected_elements (const Vector< Vector< RefineableElement * >> &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void p_refine_selected_elements (const Vector< Vector< PRefineableElement * >> &elements_to_be_refined_pt)
unsigned unrefine_uniformly ()
unsigned unrefine_uniformly (const unsigned &i_mesh)
void p_unrefine_uniformly (DocInfo &doc_info)
void p_unrefine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-unrefinement for submesh i_mesh without documentation.
void adapt (unsigned &n_refined, unsigned &n_unrefined)
void adapt ()
void p_adapt (unsigned &n_refined, unsigned &n_unrefined)
void p_adapt ()
void adapt_based_on_error_estimates (unsigned &n_refined, unsigned &n_unrefined, Vector< Vector< double >> &elemental_error)
void adapt_based_on_error_estimates (Vector< Vector< double >> &elemental_error)
void get_all_error_estimates (Vector< Vector< double >> &elemental_error)
void doc_errors (DocInfo &doc_info)
Get max and min error for all elements in submeshes.
void doc_errors ()
Get max and min error for all elements in submeshes.
void enable_info_in_newton_solve ()
void disable_info_in_newton_solve ()
Disable the output of information when in the newton solver.
Public Member Functions inherited from oomph::ExplicitTimeSteppableObject
ExplicitTimeSteppableObject ()
Empty constructor.
ExplicitTimeSteppableObject (const ExplicitTimeSteppableObject &)=delete
Broken copy constructor.
void operator= (const ExplicitTimeSteppableObject &)=delete
Broken assignment operator.
virtual ~ExplicitTimeSteppableObject ()
Empty destructor.
virtual void actions_before_explicit_stage ()
virtual void actions_after_explicit_stage ()
Private Member Functions
void fix_pressure (const unsigned &e, const unsigned &pdof, const double &pvalue)
Fix pressure in element e at pressure dof pdof and set to pvalue.
void pin_only_pressure_at_origin ()
Pin redundant pressures and pressure at origin.
void fix_pressure (const unsigned &e, const unsigned &pdof, const double &pvalue)
Fix pressure in element e at pressure dof pdof and set to pvalue.
void fix_pressure (const unsigned &e, const unsigned &pdof, const double &pvalue)
Fix pressure in element e at pressure dof pdof and set to pvalue.
void fix_pressure (const unsigned &e, const unsigned &pdof, const double &pvalue)
Fix pressure in element e at pressure dof pdof and set to pvalue.
void fix_pressure (const unsigned &e, const unsigned &pdof, const double &pvalue)
Fix pressure in element e at pressure dof pdof and set to pvalue.
void fix_pressure (const unsigned &e, const unsigned &pdof, const double &pvalue)
Fix pressure in element e at pressure dof pdof and set to pvalue.
Private Attributes
DocInfo Doc_info
Doc info object.
MeshAsGeomObject * Mesh_as_geom_object_pt
Mesh as geom object representation of mesh.
Vector< Vector< std::pair< GeomObject *, Vector< double > > > > Line_plot_point
Line_plot_point[i_phi][i_rho].
LineVisualiser * LV_pt
Line visualiser pointer.
Additional Inherited Members
Public Types inherited from oomph::Problem
typedef void(* SpatialErrorEstimatorFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error)
Function pointer for spatial error estimator.
typedef void(* SpatialErrorEstimatorWithDocFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error, DocInfo &doc_info)
Function pointer for spatial error estimator with doc.
Public Attributes inherited from oomph::Problem
bool Shut_up_in_newton_solve
Static Public Attributes inherited from oomph::Problem
static bool Suppress_warning_about_actions_before_read_unstructured_meshes
Protected Types inherited from oomph::Problem
enum Assembly_method {
Perform_assembly_using_vectors_of_pairs , Perform_assembly_using_two_vectors , Perform_assembly_using_maps , Perform_assembly_using_lists ,
Perform_assembly_using_two_arrays
}
Enumerated flags to determine which sparse assembly method is used.
Protected Member Functions inherited from oomph::Problem
unsigned setup_element_count_per_dof ()
virtual void sparse_assemble_row_or_column_compressed (Vector< int * > &column_or_row_index, Vector< int * > &row_or_column_start, Vector< double * > &value, Vector< unsigned > &nnz, Vector< double * > &residual, bool compressed_row_flag)
virtual void actions_before_newton_convergence_check ()
virtual void actions_before_newton_step ()
virtual void actions_after_newton_step ()
virtual void actions_before_implicit_timestep ()
virtual void actions_after_implicit_timestep ()
virtual void actions_after_implicit_timestep_and_error_estimation ()
virtual void actions_before_explicit_timestep ()
Actions that should be performed before each explicit time step.
virtual void actions_after_explicit_timestep ()
Actions that should be performed after each explicit time step.
virtual void actions_before_read_unstructured_meshes ()
virtual void actions_after_read_unstructured_meshes ()
virtual void actions_after_change_in_global_parameter (double *const &parameter_pt)
virtual void actions_after_change_in_bifurcation_parameter ()
virtual void actions_after_parameter_increase (double *const &parameter_pt)
double & dof_derivative (const unsigned &i)
double & dof_current (const unsigned &i)
virtual void set_initial_condition ()
virtual double global_temporal_error_norm ()
unsigned newton_solve_continuation (double *const &parameter_pt)
unsigned newton_solve_continuation (double *const &parameter_pt, DoubleVector &z)
void calculate_continuation_derivatives (double *const &parameter_pt)
void calculate_continuation_derivatives (const DoubleVector &z)
void calculate_continuation_derivatives_fd (double *const &parameter_pt)
bool does_pointer_correspond_to_problem_data (double *const &parameter_pt)
void set_consistent_pinned_values_for_continuation ()
Protected Attributes inherited from oomph::Problem
Vector< Problem * > Copy_of_problem_pt
std::map< double *, bool > Calculate_dparameter_analytic
bool Calculate_hessian_products_analytic
LinearAlgebraDistribution * Dof_distribution_pt
Vector< double * > Dof_pt
Vector of pointers to dofs.
DoubleVectorWithHaloEntries Element_count_per_dof
double Relaxation_factor
double Newton_solver_tolerance
unsigned Max_newton_iterations
Maximum number of Newton iterations.
unsigned Nnewton_iter_taken
Vector< double > Max_res
Maximum residuals at start and after each newton iteration.
double Max_residuals
bool Time_adaptive_newton_crash_on_solve_fail
bool Jacobian_reuse_is_enabled
Is re-use of Jacobian in Newton iteration enabled? Default: false.
bool Jacobian_has_been_computed
bool Problem_is_nonlinear
bool Pause_at_end_of_sparse_assembly
bool Doc_time_in_distribute
unsigned Sparse_assembly_method
unsigned Sparse_assemble_with_arrays_initial_allocation
unsigned Sparse_assemble_with_arrays_allocation_increment
Vector< Vector< unsigned > > Sparse_assemble_with_arrays_previous_allocation
double Numerical_zero_for_sparse_assembly
double FD_step_used_in_get_hessian_vector_products
bool Mass_matrix_reuse_is_enabled
bool Mass_matrix_has_been_computed
bool Discontinuous_element_formulation
double Minimum_dt
Minimum desired dt: if dt falls below this value, exit.
double Maximum_dt
Maximum desired dt.
double DTSF_max_increase
double DTSF_min_decrease
double Minimum_dt_but_still_proceed
bool Scale_arc_length
Boolean to control whether arc-length should be scaled.
double Desired_proportion_of_arc_length
Proportion of the arc-length to taken by the parameter.
double Theta_squared
int Sign_of_jacobian
Storage for the sign of the global Jacobian.
double Continuation_direction
double Parameter_derivative
Storage for the derivative of the global parameter wrt arc-length.
double Parameter_current
Storage for the present value of the global parameter.
bool Use_continuation_timestepper
Boolean to control original or new storage of dof stuff.
unsigned Dof_derivative_offset
unsigned Dof_current_offset
Vector< double > Dof_derivative
Storage for the derivative of the problem variables wrt arc-length.
Vector< double > Dof_current
Storage for the present values of the variables.
double Ds_current
Storage for the current step value.
unsigned Desired_newton_iterations_ds
double Minimum_ds
Minimum desired value of arc-length.
bool Bifurcation_detection
Boolean to control bifurcation detection via determinant of Jacobian.
bool Bisect_to_find_bifurcation
Boolean to control wheter bisection is used to located bifurcation.
bool First_jacobian_sign_change
Boolean to indicate whether a sign change has occured in the Jacobian.
bool Arc_length_step_taken
Boolean to indicate whether an arc-length step has been taken.
bool Use_finite_differences_for_continuation_derivatives
OomphCommunicator * Communicator_pt
The communicator for this problem.
bool Always_take_one_newton_step
double Timestep_reduction_factor_after_nonconvergence
bool Keep_temporal_error_below_tolerance
Static Protected Attributes inherited from oomph::Problem
static ContinuationStorageScheme Continuation_time_stepper
Storage for the single static continuation timestorage object.
Detailed Description
template<class ELEMENT>
class RefineableDrivenCavityProblem< ELEMENT >
Driven cavity problem in rectangular domain, templated by element type.
Constructor & Destructor Documentation
RefineableDrivenCavityProblem() [1/7]
template<class ELEMENT > RefineableDrivenCavityProblem< ELEMENT >::RefineableDrivenCavityProblem
Constructor.
Constructor for RefineableDrivenCavity problem
 {
  // Setup mesh
  // # of elements in x-direction
  unsigned n_x=10;
  // # of elements in y-direction
  unsigned n_y=10;
  // Domain length in x-direction
  double l_x=1.0;
  // Domain length in y-direction
  double l_y=1.0;
  // Build and assign mesh
  Problem::mesh_pt() =
   new RefineableRectangularQuadMesh<ELEMENT>(n_x,n_y,l_x,l_y);
  // Set error estimator
  Z2ErrorEstimator* error_estimator_pt=new Z2ErrorEstimator;
  dynamic_cast<RefineableRectangularQuadMesh<ELEMENT>*>(mesh_pt())->
   spatial_error_estimator_pt()=error_estimator_pt;
  // Set the boundary conditions for this problem: All nodes are
  // free by default -- just pin the ones that have Dirichlet conditions
  // here: All boundaries are Dirichlet boundaries.
  unsigned num_bound = mesh_pt()->nboundary();
  for(unsigned ibound=0;ibound<num_bound;ibound++)
   {
    unsigned num_nod= mesh_pt()->nboundary_node(ibound);
    for (unsigned inod=0;inod<num_nod;inod++)
     {
      // Loop over values (u and v velocities)
      for (unsigned i=0;i<2;i++)
       {
        mesh_pt()->boundary_node_pt(ibound,inod)->pin(i);
       }
     }
   } // end loop over boundaries
  //Find number of elements in mesh
  const unsigned n_element = mesh_pt()->nelement();
  // Loop over the elements to set up element-specific
  // things that cannot be handled by constructor: Pass pointer to Reynolds
  // number
  for(unsigned e=0;e<n_element;e++)
   {
    // Upcast from GeneralisedElement to the present element
    ELEMENT* el_pt = dynamic_cast<ELEMENT*>(mesh_pt()->element_pt(e));
    //Set the Reynolds number, etc
    el_pt->re_pt() = &Global_Physical_Variables::Re;
   } // end loop over elements
  // Pin redudant pressure dofs
  RefineableNavierStokesEquations<2>::
   pin_redundant_nodal_pressures(mesh_pt()->element_pt());
  // Now set the first pressure dof in the first element to 0.0
  fix_pressure(0,0,0.0);
  // Setup equation numbering scheme
  cout <<"Number of equations: " << assign_eqn_numbers() << std::endl;
 } // end_of_constructor
References e(), MeshRefinement::error_estimator_pt, i, and Global_Physical_Variables::Re.
~RefineableDrivenCavityProblem() [1/7]
template<class ELEMENT > RefineableDrivenCavityProblem< ELEMENT >::~RefineableDrivenCavityProblem () inline
Destructor: Empty.
 {}
RefineableDrivenCavityProblem() [2/7]
template<class ELEMENT > RefineableDrivenCavityProblem< ELEMENT >::RefineableDrivenCavityProblem ()
Constructor.
~RefineableDrivenCavityProblem() [2/7]
template<class ELEMENT > RefineableDrivenCavityProblem< ELEMENT >::~RefineableDrivenCavityProblem () inline
Destructor: Empty.
 {}
RefineableDrivenCavityProblem() [3/7]
template<class ELEMENT > RefineableDrivenCavityProblem< ELEMENT >::RefineableDrivenCavityProblem ()
Constructor.
~RefineableDrivenCavityProblem() [3/7]
template<class ELEMENT > RefineableDrivenCavityProblem< ELEMENT >::~RefineableDrivenCavityProblem () inline
Destructor: Empty.
 {}
RefineableDrivenCavityProblem() [4/7]
template<class ELEMENT > RefineableDrivenCavityProblem< ELEMENT >::RefineableDrivenCavityProblem ()
Constructor.
~RefineableDrivenCavityProblem() [4/7]
template<class ELEMENT > RefineableDrivenCavityProblem< ELEMENT >::~RefineableDrivenCavityProblem () inline
Destructor: Empty.
 {}
RefineableDrivenCavityProblem() [5/7]
template<class ELEMENT > RefineableDrivenCavityProblem< ELEMENT >::RefineableDrivenCavityProblem ()
Constructor.
~RefineableDrivenCavityProblem() [5/7]
template<class ELEMENT > RefineableDrivenCavityProblem< ELEMENT >::~RefineableDrivenCavityProblem () inline
Destructor: Empty.
 {}
RefineableDrivenCavityProblem() [6/7]
template<class ELEMENT > RefineableDrivenCavityProblem< ELEMENT >::RefineableDrivenCavityProblem ()
Constructor.
~RefineableDrivenCavityProblem() [6/7]
template<class ELEMENT > RefineableDrivenCavityProblem< ELEMENT >::~RefineableDrivenCavityProblem () inline
Destructor: Empty.
 {}
RefineableDrivenCavityProblem() [7/7]
template<class ELEMENT > RefineableDrivenCavityProblem< ELEMENT >::RefineableDrivenCavityProblem ()
Constructor.
~RefineableDrivenCavityProblem() [7/7]
template<class ELEMENT > RefineableDrivenCavityProblem< ELEMENT >::~RefineableDrivenCavityProblem () inline
Destructor: Empty.
 {}
Member Function Documentation
actions_after_adapt() [1/7]
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::actions_after_adapt () inline virtual
After adaptation: Unpin pressure and pin redundant pressure dofs.
Reimplemented from oomph::Problem.
   {
    // Unpin all pressure dofs
    RefineableNavierStokesEquations<2>::
     unpin_all_pressure_dofs(mesh_pt()->element_pt());
     // Pin redundant pressure dofs
    RefineableNavierStokesEquations<2>::
     pin_redundant_nodal_pressures(mesh_pt()->element_pt());
    // Now set the first pressure dof in the first element to 0.0
    // Loop over all elements
    const unsigned n_element=mesh_pt()->nelement();
    for (unsigned e=0;e<n_element;e++)
     {
      // If the lower left node of this element is (0,0), then fix the
      // pressure dof in this element to zero
      if (mesh_pt()->finite_element_pt(e)->node_pt(0)->x(0)==0.0 &&
          mesh_pt()->finite_element_pt(e)->node_pt(0)->x(1)==0.0) // 2d problem
       {
        oomph_info << "I'm fixing the pressure " << std::endl;
        // Fix the pressure in element e at pdof=0 to 0.0
        unsigned pdof=0;
        fix_pressure(e,pdof,0.0);
       }
     }
   } // end_of_actions_after_adapt
References e(), oomph::oomph_info, and plotDoE::x.
actions_after_adapt() [2/7]
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::actions_after_adapt () inline virtual
After adaptation: Unpin pressures and pin redundant pressure dofs and pressure at origin
Reimplemented from oomph::Problem.
   {
    pin_only_pressure_at_origin();
   }
actions_after_adapt() [3/7]
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::actions_after_adapt () inline virtual
After adaptation: Unpin pressure and pin redundant pressure dofs.
Reimplemented from oomph::Problem.
   {
    // Unpin all pressure dofs
    RefineableNavierStokesEquations<2>::
     unpin_all_pressure_dofs(mesh_pt()->element_pt());
     // Pin redundant pressure dofs
    RefineableNavierStokesEquations<2>::
     pin_redundant_nodal_pressures(mesh_pt()->element_pt());
    // Now set the first pressure dof in the first element to 0.0
    // Loop over all elements
    const unsigned n_element=mesh_pt()->nelement();
    for (unsigned e=0;e<n_element;e++)
     {
      // If the lower left node of this element is (0,0), then fix the
      // pressure dof in this element to zero
      if (mesh_pt()->finite_element_pt(e)->node_pt(0)->x(0)==0.0 &&
          mesh_pt()->finite_element_pt(e)->node_pt(0)->x(1)==0.0) // 2d problem
       {
        oomph_info << "I'm fixing the pressure " << std::endl;
        // Fix the pressure in element e at pdof=0 to 0.0
        unsigned pdof=0;
        fix_pressure(e,pdof,0.0);
       }
     }
   } // end_of_actions_after_adapt
References e(), oomph::oomph_info, and plotDoE::x.
actions_after_adapt() [4/7]
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::actions_after_adapt () inline virtual
After adaptation: Unpin pressure and pin redudant pressure dofs.
Reimplemented from oomph::Problem.
   {
    // Unpin all pressure dofs
    RefineableNavierStokesEquations<2>::
     unpin_all_pressure_dofs(mesh_pt()->element_pt());
     // Pin redundant pressure dofs
    RefineableNavierStokesEquations<2>::
     pin_redundant_nodal_pressures(mesh_pt()->element_pt());
    // Now set the first pressure dof in the first element to 0.0
    fix_pressure(0,0,0.0);
   } // end_of_actions_after_adapt
actions_after_adapt() [5/7]
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::actions_after_adapt () inline virtual
After adaptation: Unpin pressure and pin redudant pressure dofs.
Reimplemented from oomph::Problem.
   {
    // Unpin all pressure dofs
    RefineableNavierStokesEquations<2>::
     unpin_all_pressure_dofs(mesh_pt()->element_pt());
     // Pin redundant pressure dofs
    RefineableNavierStokesEquations<2>::
     pin_redundant_nodal_pressures(mesh_pt()->element_pt());
    // Now set the first pressure dof in the last element to 0.0
    unsigned nel=mesh_pt()->nelement();
    fix_pressure(nel-1,0,0.0);
    // Now we have the mesh, let's set up the plot points
    setup_line_plot_points();
   } // end_of_actions_after_adapt
actions_after_adapt() [6/7]
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::actions_after_adapt () inline virtual
After adaptation: Unpin pressure and pin redudant pressure dofs.
Reimplemented from oomph::Problem.
   {
    // Reincarnate line visualiser
    // How many points to you want?
    unsigned int  npt=100;
    Vector<Vector<double> > coord_vec(npt);
    coord_vec[0].resize(2);
    coord_vec[0][0]=0.1;
    coord_vec[0][1]=0.9;
    for (unsigned j=1;j<npt;j++)
     {
      coord_vec[j].resize(2);
      coord_vec[j][0]=double(j)/100.0;
      coord_vec[j][1]=0.9/double(j);
     }
    // Setup line visualiser
    LV_pt=new LineVisualiser(Problem::mesh_pt(),
                             coord_vec);
    // Unpin all pressure dofs
    RefineableNavierStokesEquations<2>::
     unpin_all_pressure_dofs(mesh_pt()->element_pt());
     // Pin redundant pressure dofs
    RefineableNavierStokesEquations<2>::
     pin_redundant_nodal_pressures(mesh_pt()->element_pt());
    // Now set the first pressure dof in the first element to 0.0
    fix_pressure(0,0,0.0);
   } // end_of_actions_after_adapt
References j.
actions_after_adapt() [7/7]
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::actions_after_adapt () inline virtual
After adaptation: Unpin pressure and pin redundant pressure dofs.
Reimplemented from oomph::Problem.
   {
    // Reincarnate line visualiser.
    // How many points to you want?
    unsigned int  npt=100;
    Vector<Vector<double> > coord_vec(npt);
    coord_vec[0].resize(2);
    coord_vec[0][0]=0.1;
    coord_vec[0][1]=0.9;
    for (unsigned j=1;j<npt;j++)
     {
      coord_vec[j].resize(2);
      coord_vec[j][0]=double(j)/100.0;
      coord_vec[j][1]=0.9/double(j);
     }
    // Setup line visualiser
    LV_pt=new LineVisualiser(Problem::mesh_pt(),
                             coord_vec);
    // Unpin all pressure dofs
    RefineableNavierStokesEquations<2>::
     unpin_all_pressure_dofs(mesh_pt()->element_pt());
     // Pin redundant pressure dofs
    RefineableNavierStokesEquations<2>::
     pin_redundant_nodal_pressures(mesh_pt()->element_pt());
    // Now set the first pressure dof in the first element to 0.0
    // Loop over all elements
    const unsigned n_element=mesh_pt()->nelement();
    for (unsigned e=0;e<n_element;e++)
     {
      // If the lower left node of this element is (0,0), then fix the
      // pressure dof in this element to zero
      if (mesh_pt()->finite_element_pt(e)->node_pt(0)->x(0)==0.0 &&
          mesh_pt()->finite_element_pt(e)->node_pt(0)->x(1)==0.0) // 2d problem
       {
        // Fixing the pressure.
        // Fix the pressure in element e at pdof=0 to 0.0
        unsigned pdof=0;
        fix_pressure(e,pdof,0.0);
       }
     }
   } // end_of_actions_after_adapt
References e(), j, and plotDoE::x.
actions_after_newton_solve() [1/7]
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update the after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [2/7]
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update the after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [3/7]
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update the after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [4/7]
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update the after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [5/7]
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update the after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [6/7]
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update the after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [7/7]
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update the after solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_adapt() [1/2]
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::actions_before_adapt () inline virtual
Before adaptation.
Reimplemented from oomph::Problem.
   {
    // Kill line visualiser.
    delete LV_pt;
    LV_pt=0;
   }
actions_before_adapt() [2/2]
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::actions_before_adapt () inline virtual
Before adaptation.
Reimplemented from oomph::Problem.
   {
    // Kill line visualiser.
    delete LV_pt;
    LV_pt=0;
   }
actions_before_newton_solve() [1/7]
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve. (Re-)set velocity boundary conditions just to be on the safe side...
Reimplemented from oomph::Problem.
   {
   // Setup tangential flow along boundary 0:
   unsigned ibound=0;
   unsigned num_nod= mesh_pt()->nboundary_node(ibound);
   for (unsigned inod=0;inod<num_nod;inod++)
    {
     // Tangential flow
     unsigned i=0;
     mesh_pt()->boundary_node_pt(ibound,inod)->set_value(i,1.0);
     // No penetration
     i=1;
     mesh_pt()->boundary_node_pt(ibound,inod)->set_value(i,0.0);
    }
   // Overwrite with no flow along all other boundaries
   unsigned num_bound = mesh_pt()->nboundary();
   for(unsigned ibound=1;ibound<num_bound;ibound++)
    {
     unsigned num_nod= mesh_pt()->nboundary_node(ibound);
     for (unsigned inod=0;inod<num_nod;inod++)
      {
       for (unsigned i=0;i<2;i++)
        {
         mesh_pt()->boundary_node_pt(ibound,inod)->set_value(i,0.0);
        }
      }
    }
   } // end_of_actions_before_newton_solve
References i.
actions_before_newton_solve() [2/7]
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve. (Re-)set velocity boundary conditions just to be on the safe side...
Reimplemented from oomph::Problem.
   {
   // Setup tangential flow along boundary 0:
   unsigned ibound=0;
   unsigned num_nod= mesh_pt()->nboundary_node(ibound);
   for (unsigned inod=0;inod<num_nod;inod++)
    {
     // Tangential flow
     unsigned i=0;
     mesh_pt()->boundary_node_pt(ibound,inod)->set_value(i,1.0);
     // No penetration
     i=1;
     mesh_pt()->boundary_node_pt(ibound,inod)->set_value(i,0.0);
    }
   // Overwrite with no flow along all other boundaries
   unsigned num_bound = mesh_pt()->nboundary();
   for(unsigned ibound=1;ibound<num_bound;ibound++)
    {
     unsigned num_nod= mesh_pt()->nboundary_node(ibound);
     for (unsigned inod=0;inod<num_nod;inod++)
      {
       for (unsigned i=0;i<2;i++)
        {
         mesh_pt()->boundary_node_pt(ibound,inod)->set_value(i,0.0);
        }
      }
    }
   } // end_of_actions_before_newton_solve
References i.
actions_before_newton_solve() [3/7]
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve. (Re-)set velocity boundary conditions just to be on the safe side...
Reimplemented from oomph::Problem.
   {
   // Setup tangential flow along boundary 0:
   unsigned ibound=0;
   unsigned num_nod= mesh_pt()->nboundary_node(ibound);
   for (unsigned inod=0;inod<num_nod;inod++)
    {
     // Tangential flow
     unsigned i=0;
     mesh_pt()->boundary_node_pt(ibound,inod)->set_value(i,1.0);
     // No penetration
     i=1;
     mesh_pt()->boundary_node_pt(ibound,inod)->set_value(i,0.0);
    }
   // Overwrite with no flow along all other boundaries
   unsigned num_bound = mesh_pt()->nboundary();
   for(unsigned ibound=1;ibound<num_bound;ibound++)
    {
     unsigned num_nod= mesh_pt()->nboundary_node(ibound);
     for (unsigned inod=0;inod<num_nod;inod++)
      {
       for (unsigned i=0;i<2;i++)
        {
         mesh_pt()->boundary_node_pt(ibound,inod)->set_value(i,0.0);
        }
      }
    }
   } // end_of_actions_before_newton_solve
References i.
actions_before_newton_solve() [4/7]
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve. (Re-)set velocity boundary conditions just to be on the safe side...
Reimplemented from oomph::Problem.
   {
   // Setup tangential flow along boundary 0:
   unsigned ibound=0;
   unsigned num_nod= mesh_pt()->nboundary_node(ibound);
   for (unsigned inod=0;inod<num_nod;inod++)
    {
     // Tangential flow
     unsigned i=0;
     mesh_pt()->boundary_node_pt(ibound,inod)->set_value(i,1.0);
     // No penetration
     i=1;
     mesh_pt()->boundary_node_pt(ibound,inod)->set_value(i,0.0);
    }
   // Overwrite with no flow along all other boundaries
   unsigned num_bound = mesh_pt()->nboundary();
   for(unsigned ibound=1;ibound<num_bound;ibound++)
    {
     unsigned num_nod= mesh_pt()->nboundary_node(ibound);
     for (unsigned inod=0;inod<num_nod;inod++)
      {
       for (unsigned i=0;i<2;i++)
        {
         mesh_pt()->boundary_node_pt(ibound,inod)->set_value(i,0.0);
        }
      }
    }
   } // end_of_actions_before_newton_solve
References i.
actions_before_newton_solve() [5/7]
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve. (Re-)set velocity boundary conditions just to be on the safe side...
Reimplemented from oomph::Problem.
   {
   // Setup tangential flow along boundary 0:
   unsigned ibound=0;
   unsigned num_nod= mesh_pt()->nboundary_node(ibound);
   for (unsigned inod=0;inod<num_nod;inod++)
    {
     // Tangential flow
     unsigned i=0;
     mesh_pt()->boundary_node_pt(ibound,inod)->set_value(i,1.0);
     // No penetration
     i=1;
     mesh_pt()->boundary_node_pt(ibound,inod)->set_value(i,0.0);
    }
   // Overwrite with no flow along all other boundaries
   unsigned num_bound = mesh_pt()->nboundary();
   for(unsigned ibound=1;ibound<num_bound;ibound++)
    {
     unsigned num_nod= mesh_pt()->nboundary_node(ibound);
     for (unsigned inod=0;inod<num_nod;inod++)
      {
       for (unsigned i=0;i<2;i++)
        {
         mesh_pt()->boundary_node_pt(ibound,inod)->set_value(i,0.0);
        }
      }
    }
   } // end_of_actions_before_newton_solve
References i.
actions_before_newton_solve() [6/7]
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve. (Re-)set velocity boundary conditions just to be on the safe side...
Reimplemented from oomph::Problem.
   {
   // Setup tangential flow along boundary 0:
   unsigned ibound=0;
   unsigned num_nod= mesh_pt()->nboundary_node(ibound);
   for (unsigned inod=0;inod<num_nod;inod++)
    {
     // Tangential flow
     unsigned i=0;
     mesh_pt()->boundary_node_pt(ibound,inod)->set_value(i,1.0);
     // No penetration
     i=1;
     mesh_pt()->boundary_node_pt(ibound,inod)->set_value(i,0.0);
    }
   // Overwrite with no flow along all other boundaries
   unsigned num_bound = mesh_pt()->nboundary();
   for(unsigned ibound=1;ibound<num_bound;ibound++)
    {
     unsigned num_nod= mesh_pt()->nboundary_node(ibound);
     for (unsigned inod=0;inod<num_nod;inod++)
      {
       for (unsigned i=0;i<2;i++)
        {
         mesh_pt()->boundary_node_pt(ibound,inod)->set_value(i,0.0);
        }
      }
    }
   } // end_of_actions_before_newton_solve
References i.
actions_before_newton_solve() [7/7]
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve. (Re-)set velocity boundary conditions just to be on the safe side...
Reimplemented from oomph::Problem.
   {
   // Setup tangential flow along boundary 0:
   unsigned ibound=0;
   unsigned num_nod= mesh_pt()->nboundary_node(ibound);
   for (unsigned inod=0;inod<num_nod;inod++)
    {
     // Tangential flow
     unsigned i=0;
     mesh_pt()->boundary_node_pt(ibound,inod)->set_value(i,1.0);
     // No penetration
     i=1;
     mesh_pt()->boundary_node_pt(ibound,inod)->set_value(i,0.0);
    }
   // Overwrite with no flow along all other boundaries
   unsigned num_bound = mesh_pt()->nboundary();
   for(unsigned ibound=1;ibound<num_bound;ibound++)
    {
     unsigned num_nod= mesh_pt()->nboundary_node(ibound);
     for (unsigned inod=0;inod<num_nod;inod++)
      {
       for (unsigned i=0;i<2;i++)
        {
         mesh_pt()->boundary_node_pt(ibound,inod)->set_value(i,0.0);
        }
      }
    }
   } // end_of_actions_before_newton_solve
References i.
build_mesh()
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::build_mesh
Build the mesh.
Build the mesh for RefineableDrivenCavity problem
 {
  // Setup mesh
  // # of elements in x-direction
  unsigned n_x=10;
  // # of elements in y-direction
  unsigned n_y=10;
  // Domain length in x-direction
  double l_x=1.0;
  // Domain length in y-direction
  double l_y=1.0;
  // Build and assign mesh
  Problem::mesh_pt() =
   new RefineableRectangularQuadMesh<ELEMENT>(n_x,n_y,l_x,l_y);
  // Set error estimator
  Z2ErrorEstimator* error_estimator_pt=new Z2ErrorEstimator;
  dynamic_cast<RefineableRectangularQuadMesh<ELEMENT>*>(mesh_pt())->
   spatial_error_estimator_pt()=error_estimator_pt;
  // Fine tune error targets to get "interesting" refinement pattern
  dynamic_cast<RefineableRectangularQuadMesh<ELEMENT>*>(mesh_pt())->
   max_permitted_error()=1.0e-5;
  dynamic_cast<RefineableRectangularQuadMesh<ELEMENT>*>(mesh_pt())->
   min_permitted_error()=1.0e-6;
  // Set the boundary conditions for this problem: All nodes are
  // free by default -- just pin the ones that have Dirichlet conditions
  // here: All boundaries are Dirichlet boundaries.
  unsigned num_bound = mesh_pt()->nboundary();
  for(unsigned ibound=0;ibound<num_bound;ibound++)
   {
    unsigned num_nod= mesh_pt()->nboundary_node(ibound);
    for (unsigned inod=0;inod<num_nod;inod++)
     {
      // Loop over values (u and v velocities)
      for (unsigned i=0;i<2;i++)
       {
        mesh_pt()->boundary_node_pt(ibound,inod)->pin(i);
       }
     }
   } // end loop over boundaries
  //Find number of elements in mesh
  const unsigned n_element = mesh_pt()->nelement();
  // Loop over the elements to set up element-specific
  // things that cannot be handled by constructor: Pass pointer to Reynolds
  // number
  for(unsigned e=0;e<n_element;e++)
   {
    // Upcast from GeneralisedElement to the present element
    ELEMENT* el_pt = dynamic_cast<ELEMENT*>(mesh_pt()->element_pt(e));
    //Set the Reynolds number
    el_pt->re_pt() = &Global_Physical_Variables::Re;
   } // end loop over elements
  // Pin pressure at origin no matter which processor contains that node
  pin_only_pressure_at_origin();
 }// end_of_build_mesh
References e(), MeshRefinement::error_estimator_pt, i, oomph::Mesh::nboundary(), and Global_Physical_Variables::Re.
doc_solution() [1/7]
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::doc_solution (const std::string & header)
Doc the solution.
 {
  ofstream some_file;
  ofstream some_file2;
  char filename[100];
  // Number of plot points
  unsigned npts=5;
  // Get current process rank
  int my_rank=this->communicator_pt()->my_rank();
  // Output solution
  sprintf(filename,"%s/soln%i_on_proc%i.dat",Doc_info.directory().c_str(),
          Doc_info.number(),my_rank);
  some_file.open(filename);
  mesh_pt()->output(some_file,npts);
  some_file << "TEXT X=25,Y=93,F=HELV,HU=POINT,C=BLUE,H=26,T=\""
            << header << "\"" << std::endl;
  some_file.close();
  // Output solution
  sprintf(filename,"%s/soln_with_haloes%i_on_proc%i.dat",
          Doc_info.directory().c_str(),
          Doc_info.number(),my_rank);
  some_file.open(filename);
  mesh_pt()->enable_output_of_halo_elements();
  mesh_pt()->output(some_file,npts);
  some_file << "TEXT X=25,Y=93,F=HELV,HU=POINT,C=BLUE,H=26,T=\""
            << header << "\"" << std::endl;
  mesh_pt()->disable_output_of_halo_elements();
  some_file.close();
 // Output mesh distribution
  mesh_pt()->doc_mesh_distribution(Doc_info);
  // Output boundaries
  sprintf(filename,"%s/boundaries%i_on_proc%i.dat",
          Doc_info.directory().c_str(),
          Doc_info.number(),my_rank);
  some_file.open(filename);
  mesh_pt()->output_boundaries(some_file);
  some_file << "TEXT X=25,Y=93,F=HELV,HU=POINT,C=BLUE,H=26,T=\""
            << header << "\"" << std::endl;
  some_file.close();
  {
   unsigned count_non_halo=0;
   unsigned nel=mesh_pt()->nelement();
   for (unsigned e=0;e<nel;e++)
    {
     if (!(mesh_pt()->element_pt(e)->is_halo())) count_non_halo++;
    }
   unsigned total_count_non_halo=0;
   MPI_Allreduce(&count_non_halo,&total_count_non_halo,1,MPI_UNSIGNED,MPI_SUM,
                 communicator_pt()->mpi_comm());
   oomph_info << "Number of non halo elements: "
              << total_count_non_halo << " "
              << count_non_halo << "\n";
  }
  {
   sprintf(filename,"%s/soln_non_halo_nodes%i_on_proc%i.dat",
           Doc_info.directory().c_str(),
           Doc_info.number(),my_rank);
   some_file.open(filename);
   sprintf(filename,"%s/ndof%i_on_proc%i.dat",
           Doc_info.directory().c_str(),
           Doc_info.number(),my_rank);
   some_file2.open(filename);
   unsigned count_non_halo=0;
   unsigned nnod=mesh_pt()->nnode();
   for (unsigned j=0;j<nnod;j++)
    {
     Node* nod_pt=mesh_pt()->node_pt(j);
     if (!(nod_pt->is_halo()))
      {
       count_non_halo++;
       some_file << nod_pt->x(0) << " "
                 << nod_pt->x(1) << "\n";
       unsigned nval=nod_pt->nvalue();
       unsigned cnt=0;
       for (unsigned i=0;i<nval;i++)
        {
         if (!(nod_pt->is_pinned(i))) cnt++;
        }
       some_file2 << nod_pt->x(0) << " "
                  << nod_pt->x(1) << " "
                  << cnt << "\n";
      }
    }
   some_file2.close();
   some_file.close();
   unsigned total_count_non_halo=0;
   MPI_Allreduce(&count_non_halo,&total_count_non_halo,1,MPI_UNSIGNED,MPI_SUM,
                 communicator_pt()->mpi_comm());
   oomph_info << "Number of non halo nodes: "
              << total_count_non_halo << " "
              << count_non_halo << "\n";
  }
  Doc_info.number()++;
 } // end_of_doc_solution
References oomph::DocInfo::directory(), GlobalParameters::Doc_info, e(), MergeRestartFiles::filename, i, oomph::Data::is_pinned(), j, oomph::DocInfo::number(), oomph::Data::nvalue(), oomph::oomph_info, and oomph::Node::x().
doc_solution() [2/7]
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
 {
  ofstream some_file;
  char filename[100];
  // Number of plot points
  unsigned npts=5;
  // Get current process rank
  int my_rank=this->communicator_pt()->my_rank();
  // Output solution
  sprintf(filename,"%s/soln%i_on_proc%i.dat",doc_info.directory().c_str(),
          doc_info.number(),my_rank);
  some_file.open(filename);
  mesh_pt()->output(some_file,npts);
  some_file.close();
 } // end_of_doc_solution
References oomph::DocInfo::directory(), MergeRestartFiles::filename, and oomph::DocInfo::number().
doc_solution() [3/7]
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
doc_solution() [4/7]
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
doc_solution() [5/7]
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
doc_solution() [6/7]
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
doc_solution() [7/7]
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
fix_pressure() [1/6]
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::fix_pressure (const unsigned & e, const unsigned & pdof, const double & pvalue) inline private
Fix pressure in element e at pressure dof pdof and set to pvalue.
   {
    //Cast to proper element and fix pressure
    dynamic_cast<ELEMENT*>(mesh_pt()->element_pt(e))->
                           fix_pressure(pdof,pvalue);
   } // end_of_fix_pressure
References e().
fix_pressure() [2/6]
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::fix_pressure (const unsigned & e, const unsigned & pdof, const double & pvalue) inline private
Fix pressure in element e at pressure dof pdof and set to pvalue.
   {
    //Cast to proper element and fix pressure
    dynamic_cast<ELEMENT*>(mesh_pt()->element_pt(e))->
                           fix_pressure(pdof,pvalue);
   } // end_of_fix_pressure
References e().
fix_pressure() [3/6]
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::fix_pressure (const unsigned & e, const unsigned & pdof, const double & pvalue) inline private
Fix pressure in element e at pressure dof pdof and set to pvalue.
   {
    //Cast to proper element and fix pressure
    dynamic_cast<ELEMENT*>(mesh_pt()->element_pt(e))->
                           fix_pressure(pdof,pvalue);
   } // end_of_fix_pressure
References e().
fix_pressure() [4/6]
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::fix_pressure (const unsigned & e, const unsigned & pdof, const double & pvalue) inline private
Fix pressure in element e at pressure dof pdof and set to pvalue.
   {
    //Cast to proper element and fix pressure
    dynamic_cast<ELEMENT*>(mesh_pt()->element_pt(e))->
                           fix_pressure(pdof,pvalue);
   } // end_of_fix_pressure
References e().
fix_pressure() [5/6]
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::fix_pressure (const unsigned & e, const unsigned & pdof, const double & pvalue) inline private
Fix pressure in element e at pressure dof pdof and set to pvalue.
   {
    //Cast to proper element and fix pressure
    dynamic_cast<ELEMENT*>(mesh_pt()->element_pt(e))->
                           fix_pressure(pdof,pvalue);
   } // end_of_fix_pressure
References e().
fix_pressure() [6/6]
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::fix_pressure (const unsigned & e, const unsigned & pdof, const double & pvalue) inline private
Fix pressure in element e at pressure dof pdof and set to pvalue.
   {
    //Cast to proper element and fix pressure
    dynamic_cast<ELEMENT*>(mesh_pt()->element_pt(e))->
                           fix_pressure(pdof,pvalue);
   } // end_of_fix_pressure
References e().
pin_only_pressure_at_origin()
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::pin_only_pressure_at_origin () inline private
Pin redundant pressures and pressure at origin.
   {
    // Unpin all pressure dofs
    RefineableNavierStokesEquations<2>::
     unpin_all_pressure_dofs(mesh_pt()->element_pt());
    // Pin redundant pressure dofs
    RefineableNavierStokesEquations<2>::
     pin_redundant_nodal_pressures(mesh_pt()->element_pt());
    // Now set the first pressure dof in the first element to 0.0
    // Loop over all elements
    const unsigned n_element=mesh_pt()->nelement();
    for (unsigned e=0;e<n_element;e++)
     {
      // If the lower left node of this element is (0,0), then fix the
      // pressure dof in this element to zero
      if (mesh_pt()->finite_element_pt(e)->node_pt(0)->x(0)==0.0 &&
          mesh_pt()->finite_element_pt(e)->node_pt(0)->x(1)==0.0) // 2d problem
       {
        // Fix the pressure in element e at pdof=0 to 0.0
        unsigned pdof=0;
        double pvalue=0.0;
        //Cast to proper element and fix pressure
        dynamic_cast<ELEMENT*>(mesh_pt()->element_pt(e))->
         fix_pressure(pdof,pvalue);
       }
     }
   }
References e(), and plotDoE::x.
setup_line_plot_points()
template<class ELEMENT > void RefineableDrivenCavityProblem< ELEMENT >::setup_line_plot_points () inline
Build line plot points.
   {
    // Get geom object
    delete Mesh_as_geom_object_pt;
    Mesh_as_geom_object_pt=new MeshAsGeomObject(mesh_pt());
    // Number of radial lines
    unsigned n_phi=5;
    Line_plot_point.resize(n_phi);
    // How many points to you want?
    unsigned npt=100;
    double r_max=0.1;
    Vector<double> zeta(2);
    Vector<double> s(2);
    GeomObject* geom_object_pt=0;
    for (unsigned i=0;i<n_phi;i++)
     {
      Line_plot_point[i].resize(npt);
      double phi=0.5*MathematicalConstants::Pi*double(i)/double(n_phi-1);
      oomph_info << "setup at phi : " << phi/(0.5*MathematicalConstants::Pi)
                 << " pi/2" << std::endl;
      for (unsigned j=0;j<npt;j++)
       {
        double r=r_max*double(j+1)/double(npt);
        zeta[0]=r*cos(phi);
        zeta[1]=r*sin(phi);
        Mesh_as_geom_object_pt->locate_zeta(zeta,geom_object_pt,s);
         if (geom_object_pt==0)
          {
           oomph_info << "Point : "
                      << zeta[0] << " "
                      << zeta[1] << " "
                      << " not found in setup of line plots"
                      << std::endl;
          }
         Line_plot_point[i][j]=std::make_pair(geom_object_pt,s);
       }
     }
   }
References cos(), i, j, oomph::oomph_info, BiharmonicTestFunctions2::Pi, UniformPSDSelfTest::r, BiharmonicTestFunctions2::r_max, s, sin(), and Eigen::zeta().
Member Data Documentation
Doc_info
template<class ELEMENT > DocInfo RefineableDrivenCavityProblem< ELEMENT >::Doc_info private
Doc info object.
Line_plot_point
template<class ELEMENT > Vector<Vector<std::pair<GeomObject*,Vector<double> > > > RefineableDrivenCavityProblem< ELEMENT >::Line_plot_point private
Line_plot_point[i_phi][i_rho].
LV_pt
template<class ELEMENT > LineVisualiser * RefineableDrivenCavityProblem< ELEMENT >::LV_pt private
Line visualiser pointer.
Mesh_as_geom_object_pt
template<class ELEMENT > MeshAsGeomObject* RefineableDrivenCavityProblem< ELEMENT >::Mesh_as_geom_object_pt private
Mesh as geom object representation of mesh.
The documentation for this class was generated from the following files:
demo_drivers/mpi/distribution/adaptive_driven_cavity/adaptive_driven_cavity.cc
adaptive_driven_cavity_load_balance.cc