MercuryDPM: Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ > Class Template Reference
Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ > Class Template Reference
#include <GeneralMatrixMatrix.h>
Public Member Functions
level3_blocking ()
Index mc () const
Index nc () const
Index kc () const
LhsScalar * blockA ()
RhsScalar * blockB ()
Protected Attributes
LhsScalar * m_blockA
RhsScalar * m_blockB
Index m_mc
Index m_nc
Index m_kc
Private Types
typedef LhsScalar_ LhsScalar
typedef RhsScalar_ RhsScalar
Member Typedef Documentation
LhsScalar
template<typename LhsScalar_ , typename RhsScalar_ > typedef LhsScalar_ Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::LhsScalar private
RhsScalar
template<typename LhsScalar_ , typename RhsScalar_ > typedef RhsScalar_ Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::RhsScalar private
Constructor & Destructor Documentation
level3_blocking()
template<typename LhsScalar_ , typename RhsScalar_ > Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::level3_blocking () inline
 : m_blockA(0), m_blockB(0), m_mc(0), m_nc(0), m_kc(0) {}
Member Function Documentation
blockA()
template<typename LhsScalar_ , typename RhsScalar_ > LhsScalar* Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::blockA () inline
 { return m_blockA; }
References Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::m_blockA.
Referenced by Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, true, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, ResInnerStride, Version >::run(), Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, ResInnerStride, Version >::run(), Eigen::internal::product_selfadjoint_matrix< Scalar, Index, LhsStorageOrder, true, ConjugateLhs, RhsStorageOrder, false, ConjugateRhs, ColMajor, ResInnerStride >::run(), Eigen::internal::product_selfadjoint_matrix< Scalar, Index, LhsStorageOrder, false, ConjugateLhs, RhsStorageOrder, true, ConjugateRhs, ColMajor, ResInnerStride >::run(), Eigen::internal::general_matrix_matrix_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor, ResInnerStride >::run(), Eigen::internal::general_matrix_matrix_triangular_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor, ResInnerStride, UpLo, Version >::run(), Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheLeft, Mode, Conjugate, TriStorageOrder, ColMajor, OtherInnerStride >::run(), and Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheRight, Mode, Conjugate, TriStorageOrder, ColMajor, OtherInnerStride >::run().
blockB()
template<typename LhsScalar_ , typename RhsScalar_ > RhsScalar* Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::blockB () inline
 { return m_blockB; }
References Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::m_blockB.
Referenced by Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, true, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, ResInnerStride, Version >::run(), Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, ResInnerStride, Version >::run(), Eigen::internal::product_selfadjoint_matrix< Scalar, Index, LhsStorageOrder, true, ConjugateLhs, RhsStorageOrder, false, ConjugateRhs, ColMajor, ResInnerStride >::run(), Eigen::internal::product_selfadjoint_matrix< Scalar, Index, LhsStorageOrder, false, ConjugateLhs, RhsStorageOrder, true, ConjugateRhs, ColMajor, ResInnerStride >::run(), Eigen::internal::general_matrix_matrix_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor, ResInnerStride >::run(), Eigen::internal::general_matrix_matrix_triangular_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor, ResInnerStride, UpLo, Version >::run(), Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheLeft, Mode, Conjugate, TriStorageOrder, ColMajor, OtherInnerStride >::run(), and Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheRight, Mode, Conjugate, TriStorageOrder, ColMajor, OtherInnerStride >::run().
kc()
template<typename LhsScalar_ , typename RhsScalar_ > Index Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::kc () const inline
 { return m_kc; }
References Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::m_kc.
Referenced by Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, true, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, ResInnerStride, Version >::run(), Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, ResInnerStride, Version >::run(), Eigen::internal::product_selfadjoint_matrix< Scalar, Index, LhsStorageOrder, true, ConjugateLhs, RhsStorageOrder, false, ConjugateRhs, ColMajor, ResInnerStride >::run(), Eigen::internal::product_selfadjoint_matrix< Scalar, Index, LhsStorageOrder, false, ConjugateLhs, RhsStorageOrder, true, ConjugateRhs, ColMajor, ResInnerStride >::run(), Eigen::internal::general_matrix_matrix_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor, ResInnerStride >::run(), Eigen::internal::general_matrix_matrix_triangular_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor, ResInnerStride, UpLo, Version >::run(), Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheLeft, Mode, Conjugate, TriStorageOrder, ColMajor, OtherInnerStride >::run(), and Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheRight, Mode, Conjugate, TriStorageOrder, ColMajor, OtherInnerStride >::run().
mc()
template<typename LhsScalar_ , typename RhsScalar_ > Index Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::mc () const inline
 { return m_mc; }
References Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::m_mc.
Referenced by Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, true, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, ResInnerStride, Version >::run(), Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, false, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, ResInnerStride, Version >::run(), Eigen::internal::product_selfadjoint_matrix< Scalar, Index, LhsStorageOrder, true, ConjugateLhs, RhsStorageOrder, false, ConjugateRhs, ColMajor, ResInnerStride >::run(), Eigen::internal::product_selfadjoint_matrix< Scalar, Index, LhsStorageOrder, false, ConjugateLhs, RhsStorageOrder, true, ConjugateRhs, ColMajor, ResInnerStride >::run(), Eigen::internal::general_matrix_matrix_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor, ResInnerStride >::run(), Eigen::internal::general_matrix_matrix_triangular_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor, ResInnerStride, UpLo, Version >::run(), Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheLeft, Mode, Conjugate, TriStorageOrder, ColMajor, OtherInnerStride >::run(), and Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheRight, Mode, Conjugate, TriStorageOrder, ColMajor, OtherInnerStride >::run().
nc()
template<typename LhsScalar_ , typename RhsScalar_ > Index Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::nc () const inline
 { return m_nc; }
References Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::m_nc.
Referenced by Eigen::internal::general_matrix_matrix_product< Index, LhsScalar, LhsStorageOrder, ConjugateLhs, RhsScalar, RhsStorageOrder, ConjugateRhs, ColMajor, ResInnerStride >::run().
Member Data Documentation
m_blockA
template<typename LhsScalar_ , typename RhsScalar_ > LhsScalar* Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::m_blockA protected
Referenced by Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::blockA().
m_blockB
template<typename LhsScalar_ , typename RhsScalar_ > RhsScalar* Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::m_blockB protected
Referenced by Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::blockB().
m_kc
template<typename LhsScalar_ , typename RhsScalar_ > Index Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::m_kc protected
Referenced by Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::kc().
m_mc
template<typename LhsScalar_ , typename RhsScalar_ > Index Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::m_mc protected
Referenced by Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::mc().
m_nc
template<typename LhsScalar_ , typename RhsScalar_ > Index Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::m_nc protected
Referenced by Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::nc().
The documentation for this class was generated from the following file:
GeneralMatrixMatrix.h