MercuryDPM: BenchUtil.h File Reference
BenchUtil.h File Reference
#include <Eigen/Core>
#include "BenchTimer.h"
#include <boost/preprocessor/repetition/enum_params.hpp>
#include <boost/preprocessor/repetition.hpp>
#include <boost/preprocessor/seq.hpp>
#include <boost/preprocessor/array.hpp>
#include <boost/preprocessor/arithmetic.hpp>
#include <boost/preprocessor/comparison.hpp>
#include <boost/preprocessor/punctuation.hpp>
#include <boost/preprocessor/punctuation/comma.hpp>
#include <boost/preprocessor/stringize.hpp>
Macros
#define DISABLE_SSE_EXCEPTIONS()
Functions
template<typename MatrixType >
void initMatrix_random (MatrixType &mat) __attribute__((noinline))
template<typename MatrixType >
void initMatrix_identity (MatrixType &mat) __attribute__((noinline))
Macro Definition Documentation
DISABLE_SSE_EXCEPTIONS
#define DISABLE_SSE_EXCEPTIONS ()
Value:
  {                                       \
    int aux;                              \
    asm("stmxcsr   %[aux]           \n\t" \
        "orl       $32832, %[aux]   \n\t" \
        "ldmxcsr   %[aux]           \n\t" \
        :                                 \
        : [aux] "m"(aux));                \
  }
Function Documentation
initMatrix_identity()
template<typename MatrixType > void initMatrix_identity (MatrixType & mat)
{
   mat.setIdentity();
 }
References Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::setIdentity().
Referenced by benchBasic().
initMatrix_random()
template<typename MatrixType > void initMatrix_random (MatrixType & mat)
{
   mat.setRandom();  // = MatrixType::random(mat.rows(), mat.cols());
 }
Referenced by benchBasic().