MercuryDPM: oomph::PseudoBucklingRing Class Reference
oomph::PseudoBucklingRing Class Reference
#include <pseudo_buckling_ring.h>
Public Member Functions
PseudoBucklingRing ()
Default constructor (empty and broken)
PseudoBucklingRing (const Vector< Data * > &geom_data_pt, TimeStepper *time_stepper_pt)
PseudoBucklingRing (const double &eps_buckl, const double &ampl_ratio, const unsigned n_buckl, const double &r_0, const double &T, TimeStepper *time_stepper_pt)
PseudoBucklingRing (const double &eps_buckl, const double &HoR, const unsigned &n_buckl, const unsigned &imode, TimeStepper *time_stepper_pt)
PseudoBucklingRing (const PseudoBucklingRing &node)=delete
Broken copy constructor.
void operator= (const PseudoBucklingRing &)=delete
Broken assignment operator.
~PseudoBucklingRing ()
Destructor: Clean up if necessary.
double eps_buckl ()
Access function for buckling amplitude.
double ampl_ratio ()
Access function for amplitude ratio.
double r_0 ()
Access function for undeformed radius.
double T ()
Access function for period of oscillation.
double n_buckl_float ()
Access function for buckling wavenumber (as float)
void set_eps_buckl (const double &eps_buckl)
Set buckling amplitude.
void set_ampl_ratio (const double &ampl_ratio)
void set_n_buckl (const unsigned &n_buckl)
Set buckling wavenumber.
void set_R_0 (const double &r_0)
Set undeformed radius of ring.
void set_T (const double &T)
Set period of oscillation.
void position (const Vector< double > &zeta, Vector< double > &r) const
void veloc (const Vector< double > &zeta, Vector< double > &veloc)
void accel (const Vector< double > &zeta, Vector< double > &accel)
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &j, Vector< double > &drdt)
unsigned ngeom_data () const
How many items of Data does the shape of the object depend on?
Data * geom_data_pt (const unsigned &j)
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
virtual void locate_zeta (const Vector< double > &zeta, GeomObject *&sub_geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
Protected Attributes
Vector< Data * > Geom_data_pt
Vector of pointers to Data items that affects the object's shape.
bool Must_clean_up
Do I need to clean up?
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Detailed Description
Pseudo buckling ring: Circular ring deformed by the N-th buckling mode of a thin-wall elastic ring.
\[ x = R_0 \cos(\zeta) + \epsilon \left(\cos(N \zeta) \cos(\zeta) - A \sin(N \zeta) \sin(\zeta) \right) sin(2 \pi t/T) \]
\[ y = R_0 \sin(\zeta) + \epsilon \left(\cos(N \zeta) \sin(\zeta) + A \sin(N \zeta) \cos(\zeta) \right) sin(2 \pi t/T) \]
where A is the ratio of the aziumuthal to the radial buckling amplitude (A=-1/N for statically buckling rings) and epsilon is the buckling amplitude.
Constructor & Destructor Documentation
PseudoBucklingRing() [1/5]
oomph::PseudoBucklingRing::PseudoBucklingRing () inline
Default constructor (empty and broken)
     {
       throw OomphLibError(
         "Don't call empty constructor for PseudoBucklingRing!",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
PseudoBucklingRing() [2/5]
oomph::PseudoBucklingRing::PseudoBucklingRing (const Vector< Data * > & geom_data_pt, TimeStepper * time_stepper_pt) inline
Constructor: 1 Lagrangian coordinate, 2 Eulerian coords. Pass buckling amplitude, ratio of of buckling amplitudes, buckling wavenumber (as a double), undeformed ring radius (all as Data) and pointer to global timestepper.
Geom_data_pt[0]->value(0) = Eps_buckl;
Geom_data_pt[0]->value(1) = Ampl_ratio;
Geom_data_pt[0]->value(2) = Double_N_buckl;
Geom_data_pt[0]->value(3) = R_0;
Geom_data_pt[0]->value(4) = T;
       : GeomObject(1, 2, time_stepper_pt)
     {
 #ifdef PARANOID
       if (geom_data_pt.size() != 1)
       {
         std::ostringstream error_message;
         error_message << "geom_data_pt should be of size 1, but is of size"
                       << geom_data_pt.size() << std::endl;
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
       if (geom_data_pt[0]->nvalue() != 5)
       {
         std::ostringstream error_message;
         error_message << "geom_data_pt[0] should have 5 values, but has"
                       << geom_data_pt[0]->nvalue() << std::endl;
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       Geom_data_pt.resize(1);
       Geom_data_pt[0] = geom_data_pt[0];
       // Data has been created externally: Must not clean up
       Must_clean_up = false;
     }
References geom_data_pt(), Geom_data_pt, Must_clean_up, oomph::Data::nvalue(), OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
PseudoBucklingRing() [3/5]
oomph::PseudoBucklingRing::PseudoBucklingRing (const double & eps_buckl, const double & ampl_ratio, const unsigned n_buckl, const double & r_0, const double & T, TimeStepper * time_stepper_pt) inline
Constructor: 1 Lagrangian coordinate, 2 Eulerian coords. Pass buckling amplitude, ratio of of buckling amplitudes, buckling wavenumber, undeformed ring radius, period of osc and pointer to global timestepper. All geometric data is pinned by default.
       : GeomObject(1, 2, time_stepper_pt)
     {
       // Number of previous timesteps that need to be stored
       unsigned n_time = time_stepper_pt->nprev_values();
       // Setup geometric data for element: Five items of data live in
       // in the one and only geometric data. Also store time history
       Geom_data_pt.resize(1);
       Geom_data_pt[0] = new Data(time_stepper_pt, 5);
       // I've created the data, I need to clean up
       Must_clean_up = true;
       for (unsigned itime = 0; itime <= n_time; itime++)
       {
         // Buckling amplitude
         Geom_data_pt[0]->set_value(itime, 0, eps_buckl);
         Geom_data_pt[0]->pin(0);
         // Ratio of buckling amplitudes
         Geom_data_pt[0]->set_value(itime, 1, ampl_ratio);
         Geom_data_pt[0]->pin(1);
         // Buckling wavenumber (as double)
         Geom_data_pt[0]->set_value(itime, 2, double(n_buckl));
         Geom_data_pt[0]->pin(2);
         // Radius of undeformed ring
         Geom_data_pt[0]->set_value(itime, 3, r_0);
         Geom_data_pt[0]->pin(3);
         // Period of oscillation
         Geom_data_pt[0]->set_value(itime, 4, T);
         Geom_data_pt[0]->pin(4);
       }
     }
References ampl_ratio(), eps_buckl(), Geom_data_pt, Must_clean_up, oomph::TimeStepper::nprev_values(), r_0(), and oomph::GeomObject::time_stepper_pt().
PseudoBucklingRing() [4/5]
oomph::PseudoBucklingRing::PseudoBucklingRing (const double & eps_buckl, const double & HoR, const unsigned & n_buckl, const unsigned & imode, TimeStepper * time_stepper_pt) inline
Constructor: 1 Lagrangian coordinate, 2 Eulerian coords. Pass buckling amplitude, h/R, buckling wavenumbe and pointer to global timestepper. Other parameters get set up to represent oscillating ring with mode imode (1 or 2). All geometric data is pinned by default.
       : GeomObject(1, 2, time_stepper_pt)
     {
       // Constants in Soedel solution:
       double K1 = (pow(double(n_buckl), 2) + 1.0) *
                   (1.0 / 12.0 * pow(double(n_buckl), 2) * pow(HoR, 2) + 1.0);
       double K2oK1sq =
         1.0 / 12.0 * pow(HoR, 2) * pow(double(n_buckl), 2) *
         pow((pow(double(n_buckl), 2) - 1.0), 2) /
         (pow((pow(double(n_buckl), 2) + 1.0), 2) *
          pow((1.0 / 12.0 * pow(double(n_buckl), 2) * pow(HoR, 2) + 1.0), 2));
       // The two fundamental frequencies:
       double omega1 = sqrt(0.5 * K1 * (1.0 + sqrt(1.0 - 4 * K2oK1sq)));
       double omega2 = sqrt(0.5 * K1 * (1.0 - sqrt(1.0 - 4 * K2oK1sq)));
       // The two amplitude ratios:
       double ampl_ratio1 =
         (double(n_buckl) *
          (1.0 / 12.0 * pow(double(n_buckl), 2) * pow(HoR, 2) + 1.0)) /
         (pow(omega1, 2) -
          pow(double(n_buckl), 2) * (1.0 / 12.0 * pow(HoR, 2) + 1.0));
       double ampl_ratio2 =
         double(n_buckl) *
         (1.0 / 12.0 * pow(double(n_buckl), 2) * pow(HoR, 2) + 1.0) /
         (pow(omega2, 2) -
          pow(double(n_buckl), 2) * (1.0 / 12.0 * pow(HoR, 2) + 1.0));
       double T;
       double ampl_ratio;
       if (n_buckl > 1)
       {
         T = 2.0 * MathematicalConstants::Pi / omega2;
         ampl_ratio = ampl_ratio2;
         if (imode == 1)
         {
           T = 2.0 * MathematicalConstants::Pi / omega1;
           ampl_ratio = ampl_ratio1;
         }
         else if (imode == 2)
         {
           T = 2.0 * MathematicalConstants::Pi / omega2;
           ampl_ratio = ampl_ratio2;
         }
         else
         {
           oomph_info << "wrong imode " << imode << std::endl;
         }
       }
       else
       {
         T = 2.0 * MathematicalConstants::Pi / omega1;
         ampl_ratio = ampl_ratio1;
       }
       // Number of previous timesteps that need to be stored
       unsigned n_time = time_stepper_pt->nprev_values();
       // Setup geometric data for element: Five items of data live in
       // in the one and only geometric data. Also store time history
       Geom_data_pt.resize(1);
       Geom_data_pt[0] = new Data(time_stepper_pt, 5);
       // I've created the data, I need to clean up
       Must_clean_up = true;
       for (unsigned itime = 0; itime <= n_time; itime++)
       {
         // Buckling amplitude
         Geom_data_pt[0]->set_value(itime, 0, eps_buckl);
         Geom_data_pt[0]->pin(0);
         // Ratio of buckling amplitudes
         Geom_data_pt[0]->set_value(itime, 1, ampl_ratio);
         Geom_data_pt[0]->pin(1);
         // Buckling wavenumber (as double)
         Geom_data_pt[0]->set_value(itime, 2, double(n_buckl));
         Geom_data_pt[0]->pin(2);
         // Radius of undeformed ring
         Geom_data_pt[0]->set_value(itime, 3, 1.0);
         Geom_data_pt[0]->pin(3);
         // Period of oscillation
         Geom_data_pt[0]->set_value(itime, 4, T);
         Geom_data_pt[0]->pin(4);
       }
     }
References ampl_ratio(), eps_buckl(), Geom_data_pt, Must_clean_up, oomph::TimeStepper::nprev_values(), oomph::oomph_info, oomph::MathematicalConstants::Pi, Eigen::bfloat16_impl::pow(), sqrt(), T(), and oomph::GeomObject::time_stepper_pt().
PseudoBucklingRing() [5/5]
oomph::PseudoBucklingRing::PseudoBucklingRing (const PseudoBucklingRing & node) delete
Broken copy constructor.
~PseudoBucklingRing()
oomph::PseudoBucklingRing::~PseudoBucklingRing () inline
Destructor: Clean up if necessary.
     {
       // Do I need to clean up?
       if (Must_clean_up)
       {
         delete Geom_data_pt[0];
         Geom_data_pt[0] = 0;
       }
     }
References Geom_data_pt, and Must_clean_up.
Member Function Documentation
accel()
void oomph::PseudoBucklingRing::accel (const Vector< double > & zeta, Vector< double > & accel) inline
Parametrised acceleration on object at current time: accel = d^2 r(zeta)/dt^2.
     {
 #ifdef PARANOID
       if (accel.size() != Ndim)
       {
         throw OomphLibError("The vector accel has the wrong dimension",
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // Parameter values at present time
       double time = Geom_object_time_stepper_pt->time_pt()->time();
       double Eps_buckl = Geom_data_pt[0]->value(0);
       double Ampl_ratio = Geom_data_pt[0]->value(1);
       double double_N_buckl = Geom_data_pt[0]->value(2);
       // Unused double R_0 = Geom_data_pt[0]->value(3);
       double T = Geom_data_pt[0]->value(4);
       // Accel
       accel[0] = -Eps_buckl *
                  (cos(double_N_buckl * zeta[0]) * cos(zeta[0]) -
                   Ampl_ratio * sin(double_N_buckl * zeta[0]) * sin(zeta[0])) *
                  sin(2.0 * MathematicalConstants::Pi * time / T) * 4.0 *
                  MathematicalConstants::Pi * MathematicalConstants::Pi / T / T;
       accel[1] = -Eps_buckl *
                  (cos(double_N_buckl * zeta[0]) * sin(zeta[0]) +
                   Ampl_ratio * sin(double_N_buckl * zeta[0]) * cos(zeta[0])) *
                  sin(2.0 * MathematicalConstants::Pi * time / T) * 4.0 *
                  MathematicalConstants::Pi * MathematicalConstants::Pi / T / T;
     }
References cos(), Geom_data_pt, oomph::GeomObject::Geom_object_time_stepper_pt, oomph::GeomObject::Ndim, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::MathematicalConstants::Pi, sin(), T(), oomph::Time::time(), oomph::TimeStepper::time_pt(), and Eigen::zeta().
Referenced by dposition_dt().
ampl_ratio()
double oomph::PseudoBucklingRing::ampl_ratio () inline
Access function for amplitude ratio.
     {
       return Geom_data_pt[0]->value(1);
     }
References Geom_data_pt.
Referenced by PseudoBucklingRing(), and set_ampl_ratio().
dposition_dt()
void oomph::PseudoBucklingRing::dposition_dt (const Vector< double > & zeta, const unsigned & j, Vector< double > & drdt) inline virtual
j-th time-derivative on object at current time: \(\frac{d^{j} r(\zeta)}{dt^j} \).
Reimplemented from oomph::GeomObject.
     {
       switch (j)
       {
           // Current position
         case 0:
           position(zeta, drdt);
           break;
           // Velocity:
         case 1:
           veloc(zeta, drdt);
           break;
           // Acceleration:
         case 2:
           accel(zeta, drdt);
           break;
         default:
           std::ostringstream error_message;
           error_message << j << "th derivative not implemented\n";
           throw OomphLibError(error_message.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
       }
     }
References accel(), j, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, position(), veloc(), and Eigen::zeta().
eps_buckl()
double oomph::PseudoBucklingRing::eps_buckl () inline
Access function for buckling amplitude.
     {
       return Geom_data_pt[0]->value(0);
     }
References Geom_data_pt.
Referenced by PseudoBucklingRing(), and set_eps_buckl().
geom_data_pt()
Data* oomph::PseudoBucklingRing::geom_data_pt (const unsigned & j) inline virtual
Return pointer to the j-th Data item that the object's shape depends on
Reimplemented from oomph::GeomObject.
     {
       return Geom_data_pt[j];
     }
References Geom_data_pt, and j.
Referenced by PseudoBucklingRing().
n_buckl_float()
double oomph::PseudoBucklingRing::n_buckl_float () inline
Access function for buckling wavenumber (as float)
     {
       return Geom_data_pt[0]->value(2);
     }
References Geom_data_pt.
ngeom_data()
unsigned oomph::PseudoBucklingRing::ngeom_data () const inline virtual
How many items of Data does the shape of the object depend on?
Reimplemented from oomph::GeomObject.
     {
       return Geom_data_pt.size();
     }
References Geom_data_pt.
operator=()
void oomph::PseudoBucklingRing::operator= (const PseudoBucklingRing &) delete
Broken assignment operator.
position() [1/2]
void oomph::PseudoBucklingRing::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position Vector at Lagrangian coordinate zeta at discrete previous time (t=0: present time; t>0: previous time)
Reimplemented from oomph::GeomObject.
     {
 #ifdef PARANOID
       if (r.size() != Ndim)
       {
         throw OomphLibError("The position vector r has the wrong dimension",
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
       if (t > Geom_object_time_stepper_pt->nprev_values())
       {
         throw OomphLibError(
           "The time value t is greater than the number of previous steps",
           OOMPH_CURRENT_FUNCTION,
           OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // Parameter values at previous time
       double Eps_buckl = Geom_data_pt[0]->value(t, 0);
       double Ampl_ratio = Geom_data_pt[0]->value(t, 1);
       double double_N_buckl = Geom_data_pt[0]->value(t, 2);
       double R_0 = Geom_data_pt[0]->value(t, 3);
       double T = Geom_data_pt[0]->value(4);
       // Present time
       double time = Geom_object_time_stepper_pt->time_pt()->time();
       // Recover time at previous timestep
       for (unsigned i = 0; i < t; i++)
       {
         time -= Geom_object_time_stepper_pt->time_pt()->dt(i);
       }
       // Position Vector
       r[0] = R_0 * cos(zeta[0]) +
              Eps_buckl *
                (cos(double_N_buckl * zeta[0]) * cos(zeta[0]) -
                 Ampl_ratio * sin(double_N_buckl * zeta[0]) * sin(zeta[0])) *
                sin(2.0 * MathematicalConstants::Pi * time / T);
       r[1] = R_0 * sin(zeta[0]) +
              Eps_buckl *
                (cos(double_N_buckl * zeta[0]) * sin(zeta[0]) +
                 Ampl_ratio * sin(double_N_buckl * zeta[0]) * cos(zeta[0])) *
                sin(2.0 * MathematicalConstants::Pi * time / T);
     }
References cos(), oomph::Time::dt(), Geom_data_pt, oomph::GeomObject::Geom_object_time_stepper_pt, i, oomph::GeomObject::Ndim, oomph::TimeStepper::nprev_values(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::MathematicalConstants::Pi, UniformPSDSelfTest::r, sin(), plotPSD::t, oomph::Time::time(), oomph::TimeStepper::time_pt(), and Eigen::zeta().
position() [2/2]
void oomph::PseudoBucklingRing::position (const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position Vector at Lagrangian coordinate zeta at present time
Implements oomph::GeomObject.
     {
 #ifdef PARANOID
       if (r.size() != Ndim)
       {
         throw OomphLibError("The position vector r has the wrong dimension",
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // Parameter values at present time
       double time = Geom_object_time_stepper_pt->time_pt()->time();
       double Eps_buckl = Geom_data_pt[0]->value(0);
       double Ampl_ratio = Geom_data_pt[0]->value(1);
       double double_N_buckl = Geom_data_pt[0]->value(2);
       double R_0 = Geom_data_pt[0]->value(3);
       double T = Geom_data_pt[0]->value(4);
       // Position Vector
       r[0] = R_0 * cos(zeta[0]) +
              Eps_buckl *
                (cos(double_N_buckl * zeta[0]) * cos(zeta[0]) -
                 Ampl_ratio * sin(double_N_buckl * zeta[0]) * sin(zeta[0])) *
                sin(2.0 * MathematicalConstants::Pi * time / T);
       r[1] = R_0 * sin(zeta[0]) +
              Eps_buckl *
                (cos(double_N_buckl * zeta[0]) * sin(zeta[0]) +
                 Ampl_ratio * sin(double_N_buckl * zeta[0]) * cos(zeta[0])) *
                sin(2.0 * MathematicalConstants::Pi * time / T);
     }
References cos(), Geom_data_pt, oomph::GeomObject::Geom_object_time_stepper_pt, oomph::GeomObject::Ndim, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::MathematicalConstants::Pi, UniformPSDSelfTest::r, sin(), oomph::Time::time(), oomph::TimeStepper::time_pt(), and Eigen::zeta().
Referenced by dposition_dt().
r_0()
double oomph::PseudoBucklingRing::r_0 () inline
Access function for undeformed radius.
     {
       return Geom_data_pt[0]->value(3);
     }
References Geom_data_pt.
Referenced by oomph::PseudoBucklingRingElement::get_residuals_generic(), PseudoBucklingRing(), and set_R_0().
set_ampl_ratio()
void oomph::PseudoBucklingRing::set_ampl_ratio (const double & ampl_ratio) inline
Set amplitude ratio between radial and azimuthal buckling displacements
     {
       Geom_data_pt[0]->set_value(1, ampl_ratio);
     }
References ampl_ratio(), and Geom_data_pt.
set_eps_buckl()
void oomph::PseudoBucklingRing::set_eps_buckl (const double & eps_buckl) inline
Set buckling amplitude.
     {
       Geom_data_pt[0]->set_value(0, eps_buckl);
     }
References eps_buckl(), and Geom_data_pt.
set_n_buckl()
void oomph::PseudoBucklingRing::set_n_buckl (const unsigned & n_buckl) inline
Set buckling wavenumber.
     {
       Geom_data_pt[0]->set_value(2, double(n_buckl));
     }
References Geom_data_pt.
set_R_0()
void oomph::PseudoBucklingRing::set_R_0 (const double & r_0) inline
Set undeformed radius of ring.
     {
       Geom_data_pt[0]->set_value(3, r_0);
     }
References Geom_data_pt, and r_0().
set_T()
void oomph::PseudoBucklingRing::set_T (const double & T) inline
Set period of oscillation.
     {
       Geom_data_pt[0]->set_value(4, T);
     }
References Geom_data_pt.
T()
double oomph::PseudoBucklingRing::T () inline
Access function for period of oscillation.
     {
       return Geom_data_pt[0]->value(4);
     }
References Geom_data_pt.
Referenced by accel(), PseudoBucklingRing(), and veloc().
veloc()
void oomph::PseudoBucklingRing::veloc (const Vector< double > & zeta, Vector< double > & veloc) inline
Parametrised velocity on object at current time: veloc = d r(zeta)/dt.
     {
 #ifdef PARANOID
       if (veloc.size() != Ndim)
       {
         throw OomphLibError("The vector veloc has the wrong size",
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // Parameter values at present time
       double time = Geom_object_time_stepper_pt->time_pt()->time();
       double Eps_buckl = Geom_data_pt[0]->value(0);
       double Ampl_ratio = Geom_data_pt[0]->value(1);
       double double_N_buckl = Geom_data_pt[0]->value(2);
       // Unused double R_0 = Geom_data_pt[0]->value(3);
       double T = Geom_data_pt[0]->value(4);
       // Veloc
       veloc[0] = Eps_buckl *
                  (cos(double_N_buckl * zeta[0]) * cos(zeta[0]) -
                   Ampl_ratio * sin(double_N_buckl * zeta[0]) * sin(zeta[0])) *
                  cos(2.0 * MathematicalConstants::Pi * time / T) * 2.0 *
                  MathematicalConstants::Pi / T;
       veloc[1] = Eps_buckl *
                  (cos(double_N_buckl * zeta[0]) * sin(zeta[0]) +
                   Ampl_ratio * sin(double_N_buckl * zeta[0]) * cos(zeta[0])) *
                  cos(2.0 * MathematicalConstants::Pi * time / T) * 2.0 *
                  MathematicalConstants::Pi / T;
     }
References cos(), Geom_data_pt, oomph::GeomObject::Geom_object_time_stepper_pt, oomph::GeomObject::Ndim, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::MathematicalConstants::Pi, sin(), T(), oomph::Time::time(), oomph::TimeStepper::time_pt(), and Eigen::zeta().
Referenced by dposition_dt().
Member Data Documentation
Geom_data_pt
Vector<Data*> oomph::PseudoBucklingRing::Geom_data_pt protected
Vector of pointers to Data items that affects the object's shape.
Referenced by accel(), ampl_ratio(), eps_buckl(), geom_data_pt(), n_buckl_float(), ngeom_data(), position(), PseudoBucklingRing(), oomph::PseudoBucklingRingElement::PseudoBucklingRingElement(), r_0(), set_ampl_ratio(), set_eps_buckl(), set_n_buckl(), set_R_0(), set_T(), T(), veloc(), and ~PseudoBucklingRing().
Must_clean_up
bool oomph::PseudoBucklingRing::Must_clean_up protected
Do I need to clean up?
Referenced by PseudoBucklingRing(), ~PseudoBucklingRing(), and oomph::PseudoBucklingRingElement::~PseudoBucklingRingElement().
The documentation for this class was generated from the following file:
pseudo_buckling_ring.h