MercuryDPM: ExtremeOverlapUnitTest.cpp File Reference
ExtremeOverlapUnitTest.cpp File Reference
#include "DPMBase.h"
#include "Walls/InfiniteWall.h"
#include <iostream>
#include <Species/LinearViscoelasticSlidingFrictionSpecies.h>
#include <Logger.h>
Classes
class ExtremeOverlapUnitTest
Makes sure that the behavior is still sensible if the overlap of two particles grows extremely large.
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
 {
     ExtremeOverlapUnitTest OverlapProblem;
     //set some contact parameters; the contact is elastic (so we can check
     //energy conservation), and very soft (so the particles repel each other slowly))
     //To check Energy conservation, use gnuplot:
     //  p 'ExtremeOverlapUnitTest.ene' u 1:($2+$3+$4+$5)
     auto species = OverlapProblem.speciesHandler.copyAndAddObject(LinearViscoelasticSlidingFrictionSpecies());
     species->setDensity(2000);
     species->setStiffness(1e1);
     species->setDissipation(0.0);
     species->setSlidingFrictionCoefficient(1.0);
     species->setSlidingStiffness(2.0/7.0*species->getStiffness());
     species->setSlidingDissipation(2.0/7.0*species->getDissipation());
     OverlapProblem.setName("ExtremeOverlapUnitTest");
     OverlapProblem.setFileType(FileType::NO_FILE);
     OverlapProblem.dataFile.setFileType(FileType::ONE_FILE);
     OverlapProblem.setSaveCount(1e3);
     OverlapProblem.setDimension(2);
     OverlapProblem.setTimeStep(1e-7);
     OverlapProblem.setTimeMax(1e-2);
     OverlapProblem.solve(argc,argv);
     /* JMFT: We don't need this any more, we have the self test system.
      * ART Not true it is a unit test it is below that level, so I added it back in
      * Note I had to change the tollenace to get this to work now from 1e-7 1-e10
      * \todo Thomas could you have a look why I have to change the tollence on this code and if it is a sign of a major problem*/
     Vec3D position = OverlapProblem.particleHandler.getObject(0)->getPosition();
     Vec3D positionToCompare = Vec3D(-1.031389999146e-06, 0.009506389407855, 0);
     if (!position.isEqualTo(positionToCompare, 1e-7))
         logger(FATAL,"Large particle is in the wrong position. It is at % and should be %",position,positionToCompare);
     else
         std::cout << "Test passed" << std::endl;
     position = OverlapProblem.particleHandler.getObject(1)->getPosition();
     positionToCompare = Vec3D(0.01010314899993, 0.01487096023445, 0);
     if (!position.isEqualTo(positionToCompare, 1e-7))
         logger(FATAL,"Small particle is in the wrong position. It is at % and should be %",position,positionToCompare);
     else
         std::cout << "Test passed" << std::endl;
     //std::cout.precision(13); std::cout << position << std::endl;
     return 0;
 }
References BaseHandler< T >::copyAndAddObject(), DPMBase::dataFile, e(), FATAL, BaseHandler< T >::getObject(), BaseInteractable::getPosition(), Vec3D::isEqualTo(), logger, NO_FILE, ONE_FILE, DPMBase::particleHandler, DPMBase::setDimension(), DPMBase::setFileType(), File::setFileType(), DPMBase::setName(), DPMBase::setSaveCount(), DPMBase::setTimeMax(), DPMBase::setTimeStep(), DPMBase::solve(), and DPMBase::speciesHandler.