MercuryDPM: unstructured_adaptive_2d_fsi.cc File Reference
unstructured_adaptive_2d_fsi.cc File Reference
#include "generic.h"
#include "navier_stokes.h"
#include "solid.h"
#include "constitutive.h"
#include "meshes/triangle_mesh.h"
Classes
class UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >
Unstructured 3D FSI problem.
Namespaces
Global_Physical_Variables
Global variables.
Functions
int main (int argc, char **argv)
Demonstrate how to solve an unstructured solid problem.
Variables
double Global_Physical_Variables::Mesh_Nu = 0.1
Mesh poisson ratio.
ConstitutiveLaw * Global_Physical_Variables::Mesh_constitutive_law_pt =0
Pointer to constitutive law for the mesh.
Function Documentation
main()
int main (int argc , char ** argv)
Demonstrate how to solve an unstructured solid problem.
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Define possible command line arguments and parse the ones that
  // were actually specified
  // Validation?
  CommandLineArgs::specify_command_line_flag("--validation");
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  DocInfo doc_info;
  // Output directory
  doc_info.set_directory("RESLT");
  //Create a trace file
  std::ofstream trace("RESLT/trace.dat");
  // Create generalised Hookean constitutive equations
  Global_Physical_Variables::Constitutive_law_pt =
   new GeneralisedHookean(&Global_Physical_Variables::Nu);
  // Create generalised Hookean constitutive equations for the mesh as well
  Global_Physical_Variables::Mesh_constitutive_law_pt =
   new GeneralisedHookean(&Global_Physical_Variables::Mesh_Nu);
  //Set up the problem
  UnstructuredFSIProblem<
  ProjectableTaylorHoodElement<
  PseudoSolidNodeUpdateElement<TTaylorHoodElement<2>, TPVDElement<2,3> > >,
   ProjectablePVDElement<TPVDElement<2,3> > > problem;
 //Output initial configuration
 problem.doc_solution(doc_info);
 doc_info.number()++;
 // Solve the problem
 problem.newton_solve();
 //Output solution
 problem.doc_solution(doc_info);
 doc_info.number()++;
 //Calculate the strain energy of the solid and dissipation in the
 //fluid as global output measures of the solution for validation purposes
 problem.output_strain_and_dissipation(trace);
 //Number of steps to be taken
 unsigned n_step = 10;
 //Reduce the number of steps if validating
 if (CommandLineArgs::command_line_flag_has_been_set("--validation"))
  {
   n_step=3;
  }
 //Now Crank up interaction
 for(unsigned i=0;i<n_step;i++)
  {
   Global_Physical_Variables::Q += 1.0e-4;
   problem.newton_solve(1);
   //Reset the lagrangian nodal coordinates in the fluid mesh
   //(Obviously we shouldn't do this in the solid mesh)
   problem.Fluid_mesh_pt->set_lagrangian_nodal_coordinates();
   //Output solution
   problem.doc_solution(doc_info);
   doc_info.number()++;
   //Calculate the strain energy of the solid and dissipation in the
   //fluid as global output measures of the solution for validation purposes
   problem.output_strain_and_dissipation(trace);
  }
 trace.close();
 } // end main
References oomph::CommandLineArgs::command_line_flag_has_been_set(), Global_Physical_Variables::Constitutive_law_pt, oomph::CommandLineArgs::doc_specified_flags(), i, Global_Physical_Variables::Mesh_constitutive_law_pt, Global_Physical_Variables::Mesh_Nu, Global_Physical_Variables::Nu, oomph::DocInfo::number(), oomph::CommandLineArgs::parse_and_assign(), problem, Global_Physical_Variables::Q, oomph::DocInfo::set_directory(), Flag_definition::setup(), and oomph::CommandLineArgs::specify_command_line_flag().