MercuryDPM: Eigen::internal::unitOrthogonal_selector< Derived, 3 > Struct Template Reference
Eigen::internal::unitOrthogonal_selector< Derived, 3 > Struct Template Reference
#include <OrthoMethods.h>
Public Types
typedef plain_matrix_type< Derived >::type VectorType
typedef traits< Derived >::Scalar Scalar
typedef NumTraits< Scalar >::Real RealScalar
Static Public Member Functions
static EIGEN_DEVICE_FUNC VectorType run (const Derived &src)
Member Typedef Documentation
RealScalar
template<typename Derived > typedef NumTraits<Scalar>::Real Eigen::internal::unitOrthogonal_selector< Derived, 3 >::RealScalar
Scalar
template<typename Derived > typedef traits<Derived>::Scalar Eigen::internal::unitOrthogonal_selector< Derived, 3 >::Scalar
VectorType
template<typename Derived > typedef plain_matrix_type<Derived>::type Eigen::internal::unitOrthogonal_selector< Derived, 3 >::VectorType
Member Function Documentation
run()
template<typename Derived > static EIGEN_DEVICE_FUNC VectorType Eigen::internal::unitOrthogonal_selector< Derived, 3 >::run (const Derived & src) inline static
{
     VectorType perp;
     /* Let us compute the crossed product of *this with a vector
      * that is not too close to being colinear to *this.
      */
     /* unless the x and y coords are both close to zero, we can
      * simply take ( -y, x, 0 ) and normalize it.
      */
     if ((!isMuchSmallerThan(src.x(), src.z())) || (!isMuchSmallerThan(src.y(), src.z()))) {
       RealScalar invnm = RealScalar(1) / src.template head<2>().norm();
       perp.coeffRef(0) = -numext::conj(src.y()) * invnm;
       perp.coeffRef(1) = numext::conj(src.x()) * invnm;
       perp.coeffRef(2) = 0;
     }
     /* if both x and y are close to zero, then the vector is close
      * to the z-axis, so it's far from colinear to the x-axis for instance.
      * So we take the crossed product with (1,0,0) and normalize it.
      */
     else {
       RealScalar invnm = RealScalar(1) / src.template tail<2>().norm();
       perp.coeffRef(0) = 0;
       perp.coeffRef(1) = -numext::conj(src.z()) * invnm;
       perp.coeffRef(2) = numext::conj(src.y()) * invnm;
     }
     return perp;
   }
References conj(), head< 2 >(), Eigen::internal::isMuchSmallerThan(), and tail< 2 >().
The documentation for this struct was generated from the following file:
OrthoMethods.h