MercuryDPM: HGridUnitTest.cpp File Reference
HGridUnitTest.cpp File Reference
#include <Species/LinearViscoelasticSpecies.h>
#include "Mercury3D.h"
#include "DPMBase.h"
#include "Boundaries/PeriodicBoundary.h"
Classes
class MD_demo
class HGrid_demo
Functions
int main (int argc UNUSED, char *argv[] UNUSED)
Function Documentation
main()
int main (int argc UNUSED, char *argv[] UNUSED)
 {
     MD_demo MD_problem;
     MD_problem.species->setDensity(2000);
     MD_problem.omega = 40;
     MD_problem.alpha = -2;
     MD_problem.nu = 0.7;
     MD_problem.N = 1000;
     MD_problem.setSystemDimensions(3);
     MD_problem.setParticleDimensions(3);
     MD_problem.setName("HGridUnitTest_MD");
     MD_problem.setTimeStep(0.1);
     MD_problem.setTimeMax(0.09);
     MD_problem.setSaveCount(1);
     MD_problem.setupInitialConditions();
     HGrid_demo HGrid_problem1(MD_problem);
     HGrid_problem1.setHGridMethod(TOPDOWN);
     HGrid_problem1.setHGridMaxLevels(3);
     HGrid_problem1.setHGridDistribution(EXPONENTIAL);
     HGrid_problem1.setName("HGridUnitTest_HGrid1");
     HGrid_demo HGrid_problem2(MD_problem);
     HGrid_problem2.setHGridMethod(BOTTOMUP);
     HGrid_problem2.setHGridMaxLevels(8);
     HGrid_problem2.setHGridDistribution(LINEAR);
     HGrid_problem2.setName("HGridUnitTest_HGrid2");
     logger(INFO, "Solving the MD problem");
     MD_problem.solve();
     logger(INFO, "Solving the first HGrid problem");
     HGrid_problem1.solve();
     logger(INFO, "Solving the second HGrid problem");
     HGrid_problem2.solve();
     // Check the particles are in the same place for all three problem i.e. no HGrid and two different HGrid settings
     const double tolerance = 1e-10;
     std::vector<BaseParticle*>::iterator hGrid1It = HGrid_problem1.particleHandler.begin();
     std::vector<BaseParticle*>::iterator hGrid2It = HGrid_problem2.particleHandler.begin();
     for(BaseParticle* particle : MD_problem.particleHandler)
     {
         if (!(particle->getPosition().isEqualTo((*hGrid1It)->getPosition(), tolerance)))
         {
             logger(ERROR, "position of particle in hGrid 1 is not equal to the position without hGrid");
         }
         if (!(particle->getPosition().isEqualTo((*hGrid2It)->getPosition(), tolerance)))
         {
             logger(ERROR, "position of particle in hGrid 2 is not equal to the position without hGrid");
         }
         ++hGrid1It;
         ++hGrid2It;
     }
 }
References MD_demo::alpha, BaseHandler< T >::begin(), BOTTOMUP, e(), ERROR, EXPONENTIAL, BaseInteractable::getPosition(), INFO, Vec3D::isEqualTo(), LINEAR, logger, MD_demo::N, MD_demo::nu, MD_demo::omega, DPMBase::particleHandler, ParticleSpecies::setDensity(), MercuryBase::setHGridDistribution(), MercuryBase::setHGridMaxLevels(), MercuryBase::setHGridMethod(), DPMBase::setName(), DPMBase::setParticleDimensions(), DPMBase::setSaveCount(), DPMBase::setSystemDimensions(), DPMBase::setTimeMax(), DPMBase::setTimeStep(), MD_demo::setupInitialConditions(), DPMBase::solve(), MD_demo::species, and TOPDOWN.