MercuryDPM: Eigen::internal::unary_pow_impl< Packet, ScalarExponent, false, false, ExponentIsSigned > Struct Template Reference
Eigen::internal::unary_pow_impl< Packet, ScalarExponent, false, false, ExponentIsSigned > Struct Template Reference
#include <GenericPacketMathFunctions.h>
Public Types
typedef unpacket_traits< Packet >::type Scalar
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet run (const Packet &x, const ScalarExponent &exponent)
Member Typedef Documentation
Scalar
template<typename Packet , typename ScalarExponent , bool ExponentIsSigned> typedef unpacket_traits<Packet>::type Eigen::internal::unary_pow_impl< Packet, ScalarExponent, false, false, ExponentIsSigned >::Scalar
Member Function Documentation
run()
template<typename Packet , typename ScalarExponent , bool ExponentIsSigned> static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet Eigen::internal::unary_pow_impl< Packet, ScalarExponent, false, false, ExponentIsSigned >::run (const Packet & x, const ScalarExponent & exponent) inline static
{
     const bool exponent_is_integer = (numext::isfinite)(exponent) && numext::round(exponent) == exponent;
     if (exponent_is_integer) {
       // The simple recursive doubling implementation is only accurate to 3 ulps
       // for integer exponents in [-3:7]. Since this is a common case, we
       // specialize it here.
       bool use_repeated_squaring =
           (exponent <= ScalarExponent(7) && (!ExponentIsSigned || exponent >= ScalarExponent(-3)));
       return use_repeated_squaring ? unary_pow::int_pow(x, exponent) : generic_pow(x, pset1<Packet>(exponent));
     } else {
       Packet result = unary_pow::gen_pow(x, exponent);
       result = unary_pow::handle_nonint_nonint_errors(x, result, exponent);
       return result;
     }
   }
References Eigen::internal::unary_pow::gen_pow(), Eigen::internal::generic_pow(), Eigen::internal::unary_pow::handle_nonint_nonint_errors(), Eigen::internal::unary_pow::int_pow(), Eigen::numext::isfinite(), Eigen::numext::round(), and plotDoE::x.
The documentation for this struct was generated from the following file:
GenericPacketMathFunctions.h