MercuryDPM: prec_inverse_4x4.cpp File Reference
prec_inverse_4x4.cpp File Reference
#include "main.h"
#include <Eigen/LU>
#include <algorithm>
Functions
template<typename MatrixType >
void inverse_permutation_4x4 ()
template<typename MatrixType >
void inverse_general_4x4 (int repeat)
EIGEN_DECLARE_TEST (prec_inverse_4x4)
Function Documentation
EIGEN_DECLARE_TEST()
EIGEN_DECLARE_TEST (prec_inverse_4x4)
{
   CALL_SUBTEST_1((inverse_permutation_4x4<Matrix4f>()));
   CALL_SUBTEST_1((inverse_general_4x4<Matrix4f>(200000 * g_repeat)));
   CALL_SUBTEST_1((inverse_general_4x4<Matrix<float, 4, 4, RowMajor> >(200000 * g_repeat)));
   CALL_SUBTEST_2((inverse_permutation_4x4<Matrix<double, 4, 4, RowMajor> >()));
   CALL_SUBTEST_2((inverse_general_4x4<Matrix<double, 4, 4, ColMajor> >(200000 * g_repeat)));
   CALL_SUBTEST_2((inverse_general_4x4<Matrix<double, 4, 4, RowMajor> >(200000 * g_repeat)));
   CALL_SUBTEST_3((inverse_permutation_4x4<Matrix4cf>()));
   CALL_SUBTEST_3((inverse_general_4x4<Matrix4cf>(50000 * g_repeat)));
 }
References CALL_SUBTEST_1, CALL_SUBTEST_2, CALL_SUBTEST_3, Eigen::g_repeat, inverse_general_4x4(), and inverse_permutation_4x4().
inverse_general_4x4()
template<typename MatrixType > void inverse_general_4x4 (int repeat)
{
   using std::abs;
   typedef typename MatrixType::Scalar Scalar;
   double error_sum = 0., error_max = 0.;
   for (int i = 0; i < repeat; ++i) {
     MatrixType m;
     bool is_invertible;
     do {
       m = MatrixType::Random();
       is_invertible = Eigen::FullPivLU<MatrixType>(m).isInvertible();
     } while (!is_invertible);
     MatrixType inv = m.inverse();
     double error = double((m * inv - MatrixType::Identity()).norm());
     error_sum += error;
     error_max = (std::max)(error_max, error);
   }
   std::cerr << "inverse_general_4x4, Scalar = " << type_name<Scalar>() << std::endl;
   double error_avg = error_sum / repeat;
   EIGEN_DEBUG_VAR(error_avg);
   EIGEN_DEBUG_VAR(error_max);
   // FIXME that 1.25 used to be a 1.0 until the NumTraits changes on 28 April 2010, what's going wrong??
   // FIXME that 1.25 used to be 1.2 until we tested gcc 4.1 on 30 June 2010 and got 1.21.
   VERIFY(error_avg < (NumTraits<Scalar>::IsComplex ? 8.0 : 1.25));
   VERIFY(error_max < (NumTraits<Scalar>::IsComplex ? 64.0 : 20.0));
   {
     int s = 5;  // internal::random<int>(4,10);
     int i = 0;  // internal::random<int>(0,s-4);
     int j = 0;  // internal::random<int>(0,s-4);
     Matrix<Scalar, 5, 5> mat(s, s);
     mat.setRandom();
     MatrixType submat = mat.template block<4, 4>(i, j);
     MatrixType mat_inv = mat.template block<4, 4>(i, j).inverse();
     VERIFY_IS_APPROX(mat_inv, submat.inverse());
     mat.template block<4, 4>(i, j) = submat.inverse();
     VERIFY_IS_APPROX(mat_inv, (mat.template block<4, 4>(i, j)));
   }
 }
References abs(), EIGEN_DEBUG_VAR, calibrate::error, i, Eigen::FullPivLU< MatrixType_, PermutationIndex_ >::isInvertible(), j, m, max, Eigen::internal::repeat(), s, VERIFY, and VERIFY_IS_APPROX.
Referenced by EIGEN_DECLARE_TEST().
inverse_permutation_4x4()
template<typename MatrixType > void inverse_permutation_4x4 ()
{
   Vector4i indices(0, 1, 2, 3);
   for (int i = 0; i < 24; ++i) {
     MatrixType m = PermutationMatrix<4>(indices);
     MatrixType inv = m.inverse();
     VERIFY_IS_APPROX(m * inv, MatrixType::Identity());
     std::next_permutation(indices.data(), indices.data() + 4);
   }
 }
References i, m, and VERIFY_IS_APPROX.
Referenced by EIGEN_DECLARE_TEST().