MercuryDPM: oomph::EighthSphereDomain Class Reference
oomph::EighthSphereDomain Class Reference
#include <eighth_sphere_domain.h>
Public Member Functions
EighthSphereDomain (const double &radius)
Constructor: Pass the radius of the sphere.
EighthSphereDomain (const EighthSphereDomain &)=delete
Broken copy constructor.
void operator= (const EighthSphereDomain &)=delete
Broken assignment operator.
~EighthSphereDomain ()
Destructor: Empty; cleanup done in base class.
void macro_element_boundary (const unsigned &t, const unsigned &imacro, const unsigned &idirect, const Vector< double > &s, Vector< double > &f)
Public Member Functions inherited from oomph::Domain
Domain ()
Constructor.
Domain (const Domain &)=delete
Broken copy constructor.
void operator= (const Domain &)=delete
Broken assignment operator.
virtual ~Domain ()
MacroElement * macro_element_pt (const unsigned &i)
Access to i-th macro element.
unsigned nmacro_element ()
Number of macro elements in domain.
void output (const std::string &filename, const unsigned &nplot)
Output macro elements.
void output (std::ostream &outfile, const unsigned &nplot)
Output macro elements.
virtual void macro_element_boundary (const double &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void macro_element_boundary (const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void output_macro_element_boundaries (const std::string &filename, const unsigned &nplot)
Output all macro element boundaries as tecplot zones.
void output_macro_element_boundaries (std::ostream &outfile, const unsigned &nplot)
Output all macro element boundaries as tecplot zones.
virtual void dmacro_element_boundary (const unsigned &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
virtual void dmacro_element_boundary (const double &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void dmacro_element_boundary (const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
virtual void d2macro_element_boundary (const unsigned &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
virtual void d2macro_element_boundary (const double &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void d2macro_element_boundary (const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
Private Member Functions
void r_centr_L (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
void r_centr_R (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
void r_centr_D (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
void r_centr_U (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
void r_centr_B (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
void r_centr_F (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
void r_right_L (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
void r_right_R (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
void r_right_D (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
void r_right_U (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
void r_right_B (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
void r_right_F (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
void r_up_L (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
void r_up_R (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
void r_up_D (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
void r_up_U (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
void r_up_B (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
void r_up_F (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
void r_front_L (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
void r_front_R (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
void r_front_D (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
void r_front_U (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
void r_front_B (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
void r_front_F (const unsigned &t, const Vector< double > &zeta, Vector< double > &f)
Private Attributes
double Radius
Additional Inherited Members
Protected Attributes inherited from oomph::Domain
Vector< MacroElement * > Macro_element_pt
Vector of pointers to macro elements.
Detailed Description
Eighth sphere as domain. Domain is parametrised by four macro elements
Constructor & Destructor Documentation
EighthSphereDomain() [1/2]
oomph::EighthSphereDomain::EighthSphereDomain (const double & radius) inline
Constructor: Pass the radius of the sphere.
                                              : Radius(radius)
     {
       // There are four macro elements
       unsigned nmacro = 4;
       // Resize
       Macro_element_pt.resize(nmacro);
       // Create the 3D Q macro elements
       for (unsigned i = 0; i < nmacro; i++)
       {
         Macro_element_pt[i] = new QMacroElement<3>(this, i);
       }
     }
References i, and oomph::Domain::Macro_element_pt.
EighthSphereDomain() [2/2]
oomph::EighthSphereDomain::EighthSphereDomain (const EighthSphereDomain &) delete
Broken copy constructor.
~EighthSphereDomain()
oomph::EighthSphereDomain::~EighthSphereDomain () inline
Destructor: Empty; cleanup done in base class.
 {}
Member Function Documentation
macro_element_boundary()
void oomph::EighthSphereDomain::macro_element_boundary (const unsigned & t, const unsigned & imacro, const unsigned & idirect, const Vector< double > & s, Vector< double > & f) inline virtual
Vector representation of the imacro-th macro element boundary idirect (L/R/D/U/B/F) at time level t (t=0: present; t>0: previous): f(s).
Implements oomph::Domain.
     {
       using namespace OcTreeNames;
 #ifdef WARN_ABOUT_SUBTLY_CHANGED_OOMPH_INTERFACES
       // Warn about time argument being moved to the front
       OomphLibWarning(
         "Order of function arguments has changed between versions 0.8 and 0.85",
         "EighthSphereDomain::macro_element_boundary(...)",
         OOMPH_EXCEPTION_LOCATION);
 #endif
       // Which macro element?
       // --------------------
       switch (imacro)
       {
           // Macro element 0: Central box
         case 0:
           if (idirect == L)
           {
             r_centr_L(t, s, f);
           }
           else if (idirect == R)
           {
             r_centr_R(t, s, f);
           }
           else if (idirect == D)
           {
             r_centr_D(t, s, f);
           }
           else if (idirect == U)
           {
             r_centr_U(t, s, f);
           }
           else if (idirect == B)
           {
             r_centr_B(t, s, f);
           }
           else if (idirect == F)
           {
             r_centr_F(t, s, f);
           }
           else
           {
             std::ostringstream error_message;
             error_message << "idirect is " << OcTree::Direct_string[idirect]
                           << "not one of L, R, U, D, B, F" << std::endl;
             throw OomphLibError(error_message.str(),
                                 OOMPH_CURRENT_FUNCTION,
                                 OOMPH_EXCEPTION_LOCATION);
           }
           break;
           // Macro element 1:right
         case 1:
           // Which direction?
           if (idirect == L)
           {
             r_right_L(t, s, f);
           }
           else if (idirect == R)
           {
             r_right_R(t, s, f);
           }
           else if (idirect == D)
           {
             r_right_D(t, s, f);
           }
           else if (idirect == U)
           {
             r_right_U(t, s, f);
           }
           else if (idirect == B)
           {
             r_right_B(t, s, f);
           }
           else if (idirect == F)
           {
             r_right_F(t, s, f);
           }
           else
           {
             std::ostringstream error_message;
             error_message << "idirect is " << OcTree::Direct_string[idirect]
                           << "not one of L, R, U, D, B, F" << std::endl;
             throw OomphLibError(error_message.str(),
                                 OOMPH_CURRENT_FUNCTION,
                                 OOMPH_EXCEPTION_LOCATION);
           }
           break;
           // Macro element 2: Up
         case 2:
           // Which direction?
           if (idirect == L)
           {
             r_up_L(t, s, f);
           }
           else if (idirect == R)
           {
             r_up_R(t, s, f);
           }
           else if (idirect == D)
           {
             r_up_D(t, s, f);
           }
           else if (idirect == U)
           {
             r_up_U(t, s, f);
           }
           else if (idirect == B)
           {
             r_up_B(t, s, f);
           }
           else if (idirect == F)
           {
             r_up_F(t, s, f);
           }
           else
           {
             std::ostringstream error_message;
             error_message << "idirect is " << OcTree::Direct_string[idirect]
                           << "not one of L, R, U, D, B, F" << std::endl;
             throw OomphLibError(error_message.str(),
                                 OOMPH_CURRENT_FUNCTION,
                                 OOMPH_EXCEPTION_LOCATION);
           }
           break;
           // Macro element 3: Front
         case 3:
           // Which direction?
           if (idirect == L)
           {
             r_front_L(t, s, f);
           }
           else if (idirect == R)
           {
             r_front_R(t, s, f);
           }
           else if (idirect == D)
           {
             r_front_D(t, s, f);
           }
           else if (idirect == U)
           {
             r_front_U(t, s, f);
           }
           else if (idirect == B)
           {
             r_front_B(t, s, f);
           }
           else if (idirect == F)
           {
             r_front_F(t, s, f);
           }
           else
           {
             std::ostringstream error_message;
             error_message << "idirect is " << OcTree::Direct_string[idirect]
                           << "not one of L, R, U, D, B, F" << std::endl;
             throw OomphLibError(error_message.str(),
                                 OOMPH_CURRENT_FUNCTION,
                                 OOMPH_EXCEPTION_LOCATION);
           }
           break;
         default:
           std::ostringstream error_message;
           error_message << "imacro is " << OcTree::Direct_string[idirect]
                         << ", but should be in the range 0-3" << std::endl;
           throw OomphLibError(error_message.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
       }
     }
References D, oomph::OcTree::Direct_string, f(), oomph::OcTreeNames::F, L, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, R, r_centr_B(), r_centr_D(), r_centr_F(), r_centr_L(), r_centr_R(), r_centr_U(), r_front_B(), r_front_D(), r_front_F(), r_front_L(), r_front_R(), r_front_U(), r_right_B(), r_right_D(), r_right_F(), r_right_L(), r_right_R(), r_right_U(), r_up_B(), r_up_D(), r_up_F(), r_up_L(), r_up_R(), r_up_U(), s, plotPSD::t, and RachelsAdvectionDiffusion::U.
operator=()
void oomph::EighthSphereDomain::operator= (const EighthSphereDomain &) delete
Broken assignment operator.
r_centr_B()
void oomph::EighthSphereDomain::r_centr_B (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of central box macro element zeta \(\in [-1,1]^2 \)
   {
     f[0] = Radius * 0.25 * (1.0 + zeta[0]);
     f[1] = Radius * 0.25 * (1.0 + zeta[1]);
     f[2] = 0.0;
   }
References f(), Radius, and Eigen::zeta().
Referenced by macro_element_boundary().
r_centr_D()
void oomph::EighthSphereDomain::r_centr_D (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of central box macro element zeta \(\in [-1,1]^2 \)
   {
     f[0] = Radius * 0.25 * (1.0 + zeta[0]);
     f[1] = 0;
     f[2] = Radius * 0.25 * (1.0 + zeta[1]);
   }
References f(), Radius, and Eigen::zeta().
Referenced by macro_element_boundary().
r_centr_F()
void oomph::EighthSphereDomain::r_centr_F (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of central box macro element zeta \(\in [-1,1]^2 \)
   {
     f[0] = Radius * 0.25 * (1.0 + zeta[0]);
     f[1] = Radius * 0.25 * (1.0 + zeta[1]);
     f[2] = Radius * 0.5;
   }
References f(), Radius, and Eigen::zeta().
Referenced by macro_element_boundary(), and r_front_B().
r_centr_L()
void oomph::EighthSphereDomain::r_centr_L (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of central box macro element zeta \(\in [-1,1]^2 \)
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// Boundary of central box macro element zeta \(\in [-1,1]^2 \)
   {
     f[0] = 0;
     f[1] = Radius * 0.25 * (1.0 + zeta[0]);
     f[2] = Radius * 0.25 * (1.0 + zeta[1]);
   }
References f(), Radius, and Eigen::zeta().
Referenced by macro_element_boundary().
r_centr_R()
void oomph::EighthSphereDomain::r_centr_R (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of central box macro element zeta \(\in [-1,1]^2 \)
   {
     f[0] = Radius * 0.5;
     f[1] = Radius * 0.25 * (1.0 + zeta[0]);
     f[2] = Radius * 0.25 * (1.0 + zeta[1]);
   }
References f(), Radius, and Eigen::zeta().
Referenced by macro_element_boundary(), and r_right_L().
r_centr_U()
void oomph::EighthSphereDomain::r_centr_U (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of central box macro element zeta \(\in [-1,1]^2 \)
   {
     f[0] = Radius * 0.25 * (1.0 + zeta[0]);
     f[1] = Radius * 0.5;
     f[2] = Radius * 0.25 * (1.0 + zeta[1]);
   }
References f(), Radius, and Eigen::zeta().
Referenced by macro_element_boundary(), and r_up_D().
r_front_B()
void oomph::EighthSphereDomain::r_front_B (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of top left box macro element zeta \(\in [-1,1]^2 \)
   {
     r_centr_F(t, zeta, f);
   }
References f(), r_centr_F(), plotPSD::t, and Eigen::zeta().
Referenced by macro_element_boundary().
r_front_D()
void oomph::EighthSphereDomain::r_front_D (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of top left box macro element zeta \(\in [-1,1]^2 \)
   {
     // position vector on sphere
     Vector<double> on_sphere(3);
     Vector<double> temp_zeta(2);
     temp_zeta[0] = zeta[0];
     temp_zeta[1] = -1.0;
     r_front_F(t, temp_zeta, on_sphere);
     // position vector on center box
     Vector<double> on_center(3);
     on_center[0] = 0.5 * Radius * 0.5 * (zeta[0] + 1.0);
     on_center[1] = 0.0;
     on_center[2] = 0.5 * Radius;
     // straight line across
     for (unsigned i = 0; i < 3; i++)
     {
       f[i] =
         on_center[i] + 0.5 * (zeta[1] + 1.0) * (on_sphere[i] - on_center[i]);
     }
   }
References f(), i, r_front_F(), Radius, plotPSD::t, and Eigen::zeta().
Referenced by macro_element_boundary().
r_front_F()
void oomph::EighthSphereDomain::r_front_F (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of top left box macro element zeta \(\in [-1,1]^2 \)
   {
     double k0 = 0.5 * (1.0 + zeta[0]);
     double k1 = 0.5 * (1.0 + zeta[1]);
     Vector<double> p(3);
     Vector<double> point1(3);
     Vector<double> point2(3);
     point1[0] = 0.5 * Radius * k0;
     point1[1] = 0.0;
     point1[2] = Radius - k0 * 0.5 * Radius;
     point2[0] = k0 * Radius / 3.0;
     point2[1] = 0.5 * Radius - k0 * Radius / 6.0;
     point2[2] = 0.5 * Radius - k0 * Radius / 6.0;
     for (unsigned i = 0; i < 3; i++)
     {
       p[i] = point1[i] + k1 * (point2[i] - point1[i]);
     }
     double alpha = Radius / std::sqrt(p[0] * p[0] + p[1] * p[1] + p[2] * p[2]);
     for (unsigned i = 0; i < 3; i++)
     {
       f[i] = alpha * p[i];
     }
   }
References alpha, f(), i, p, Radius, sqrt(), and Eigen::zeta().
Referenced by macro_element_boundary(), r_front_D(), and r_front_L().
r_front_L()
void oomph::EighthSphereDomain::r_front_L (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of top left box macro element zeta \(\in [-1,1]^2 \)
   {
     // position vector on sphere
     Vector<double> on_sphere(3);
     Vector<double> temp_zeta(2);
     temp_zeta[0] = -1.0;
     temp_zeta[1] = zeta[0];
     r_front_F(t, temp_zeta, on_sphere);
     // position vector on center box
     Vector<double> on_center(3);
     on_center[0] = 0.0;
     on_center[1] = 0.5 * Radius * 0.5 * (zeta[0] + 1.0);
     on_center[2] = 0.5 * Radius;
     // straight line across
     for (unsigned i = 0; i < 3; i++)
     {
       f[i] =
         on_center[i] + 0.5 * (zeta[1] + 1.0) * (on_sphere[i] - on_center[i]);
     }
   }
References f(), i, r_front_F(), Radius, plotPSD::t, and Eigen::zeta().
Referenced by macro_element_boundary().
r_front_R()
void oomph::EighthSphereDomain::r_front_R (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of top left box macro element zeta \(\in [-1,1]^2 \)
   {
     Vector<double> zeta2(2);
     zeta2[0] = zeta[1];
     zeta2[1] = zeta[0];
     r_right_F(t, zeta2, f);
   }
References f(), r_right_F(), plotPSD::t, and Eigen::zeta().
Referenced by macro_element_boundary().
r_front_U()
void oomph::EighthSphereDomain::r_front_U (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of top left box macro element zeta \(\in [-1,1]^2 \)
   {
     r_up_F(t, zeta, f);
   }
References f(), r_up_F(), plotPSD::t, and Eigen::zeta().
Referenced by macro_element_boundary().
r_right_B()
void oomph::EighthSphereDomain::r_right_B (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of right box macro element zeta \(\in [-1,1]^2 \)
   {
     // position vector on sphere
     Vector<double> on_sphere(3);
     Vector<double> temp_zeta(2);
     temp_zeta[0] = zeta[1];
     temp_zeta[1] = -1.0;
     r_right_R(t, temp_zeta, on_sphere);
     // position vector on center box
     Vector<double> on_center(3);
     on_center[0] = 0.5 * Radius;
     on_center[1] = 0.5 * Radius * 0.5 * (zeta[1] + 1.0);
     on_center[2] = 0.0;
     // strait line across
     for (unsigned i = 0; i < 3; i++)
     {
       f[i] =
         on_center[i] + 0.5 * (zeta[0] + 1.0) * (on_sphere[i] - on_center[i]);
     }
   }
References f(), i, r_right_R(), Radius, plotPSD::t, and Eigen::zeta().
Referenced by macro_element_boundary().
r_right_D()
void oomph::EighthSphereDomain::r_right_D (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of right box macro element zeta \(\in [-1,1]^2 \)
   {
     // position vector on sphere
     Vector<double> on_sphere(3);
     Vector<double> temp_zeta(2);
     temp_zeta[0] = -1.0;
     temp_zeta[1] = zeta[1];
     r_right_R(t, temp_zeta, on_sphere);
     // position vector on center box
     Vector<double> on_center(3);
     on_center[0] = 0.5 * Radius;
     on_center[1] = 0.0;
     on_center[2] = 0.5 * Radius * 0.5 * (zeta[1] + 1.0);
     // strait line across
     for (unsigned i = 0; i < 3; i++)
     {
       f[i] =
         on_center[i] + 0.5 * (zeta[0] + 1.0) * (on_sphere[i] - on_center[i]);
     }
   }
References f(), i, r_right_R(), Radius, plotPSD::t, and Eigen::zeta().
Referenced by macro_element_boundary().
r_right_F()
void oomph::EighthSphereDomain::r_right_F (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of right box macro element zeta \(\in [-1,1]^2 \)
   {
     // position vector on sphere
     Vector<double> on_sphere(3);
     Vector<double> temp_zeta(2);
     temp_zeta[0] = zeta[1];
     temp_zeta[1] = 1.0;
     r_right_R(t, temp_zeta, on_sphere);
     // position vector on center box
     Vector<double> on_center(3);
     on_center[0] = 0.5 * Radius;
     on_center[1] = 0.5 * Radius * 0.5 * (zeta[1] + 1.0);
     on_center[2] = 0.5 * Radius;
     // strait line across
     for (unsigned i = 0; i < 3; i++)
     {
       f[i] =
         on_center[i] + 0.5 * (zeta[0] + 1.0) * (on_sphere[i] - on_center[i]);
     }
   }
References f(), i, r_right_R(), Radius, plotPSD::t, and Eigen::zeta().
Referenced by macro_element_boundary(), and r_front_R().
r_right_L()
void oomph::EighthSphereDomain::r_right_L (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of right box macro element zeta \(\in [-1,1]^2 \)
   {
     r_centr_R(t, zeta, f);
   }
References f(), r_centr_R(), plotPSD::t, and Eigen::zeta().
Referenced by macro_element_boundary().
r_right_R()
void oomph::EighthSphereDomain::r_right_R (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of right box macro element zeta \(\in [-1,1]^2 \)
   {
     double k0 = 0.5 * (1.0 + zeta[0]);
     double k1 = 0.5 * (1.0 + zeta[1]);
     Vector<double> p(3);
     Vector<double> point1(3);
     Vector<double> point2(3);
     point1[0] = Radius - 0.5 * Radius * k0;
     point1[1] = 0.5 * Radius * k0;
     point1[2] = 0.0;
     point2[0] = 0.5 * Radius - k0 * Radius / 6.0;
     point2[1] = k0 * Radius / 3.0;
     point2[2] = 0.5 * Radius - k0 * Radius / 6.0;
     for (unsigned i = 0; i < 3; i++)
     {
       p[i] = point1[i] + k1 * (point2[i] - point1[i]);
     }
     double alpha = Radius / std::sqrt(p[0] * p[0] + p[1] * p[1] + p[2] * p[2]);
     for (unsigned i = 0; i < 3; i++)
     {
       f[i] = alpha * p[i];
     }
   }
References alpha, f(), i, p, Radius, sqrt(), and Eigen::zeta().
Referenced by macro_element_boundary(), r_right_B(), r_right_D(), r_right_F(), and r_right_U().
r_right_U()
void oomph::EighthSphereDomain::r_right_U (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of right box macro element zeta \(\in [-1,1]^2 \)
   {
     // position vector on sphere
     Vector<double> on_sphere(3);
     Vector<double> temp_zeta(2);
     temp_zeta[0] = 1.0;
     temp_zeta[1] = zeta[1];
     r_right_R(t, temp_zeta, on_sphere);
     // position vector on center box
     Vector<double> on_center(3);
     on_center[0] = 0.5 * Radius;
     on_center[1] = 0.5 * Radius;
     on_center[2] = 0.5 * Radius * 0.5 * (zeta[1] + 1.0);
     // strait line across
     for (unsigned i = 0; i < 3; i++)
     {
       f[i] =
         on_center[i] + 0.5 * (zeta[0] + 1.0) * (on_sphere[i] - on_center[i]);
     }
   }
References f(), i, r_right_R(), Radius, plotPSD::t, and Eigen::zeta().
Referenced by macro_element_boundary(), and r_up_R().
r_up_B()
void oomph::EighthSphereDomain::r_up_B (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of top left box macro element zeta \(\in [-1,1]^2 \)
   {
     // position vector on sphere
     Vector<double> on_sphere(3);
     Vector<double> temp_zeta(2);
     temp_zeta[0] = zeta[0];
     temp_zeta[1] = -1.0;
     r_up_U(t, temp_zeta, on_sphere);
     // position vector on center box
     Vector<double> on_center(3);
     on_center[0] = 0.5 * Radius * 0.5 * (zeta[0] + 1.0);
     on_center[1] = 0.5 * Radius;
     on_center[2] = 0.0;
     // strait line across
     for (unsigned i = 0; i < 3; i++)
     {
       f[i] =
         on_center[i] + 0.5 * (zeta[1] + 1.0) * (on_sphere[i] - on_center[i]);
     }
   }
References f(), i, r_up_U(), Radius, plotPSD::t, and Eigen::zeta().
Referenced by macro_element_boundary().
r_up_D()
void oomph::EighthSphereDomain::r_up_D (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of top left box macro element zeta \(\in [-1,1]^2 \)
   {
     r_centr_U(t, zeta, f);
   }
References f(), r_centr_U(), plotPSD::t, and Eigen::zeta().
Referenced by macro_element_boundary().
r_up_F()
void oomph::EighthSphereDomain::r_up_F (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of top left box macro element zeta \(\in [-1,1]^2 \)
   {
     // position vector on sphere
     Vector<double> on_sphere(3);
     Vector<double> temp_zeta(2);
     temp_zeta[0] = zeta[0];
     temp_zeta[1] = 1.0;
     r_up_U(t, temp_zeta, on_sphere);
     // position vector on center box
     Vector<double> on_center(3);
     on_center[0] = 0.5 * Radius * 0.5 * (zeta[0] + 1.0);
     on_center[1] = 0.5 * Radius;
     on_center[2] = 0.5 * Radius;
     // straight line across
     for (unsigned i = 0; i < 3; i++)
     {
       f[i] =
         on_center[i] + 0.5 * (zeta[1] + 1.0) * (on_sphere[i] - on_center[i]);
     }
   }
References f(), i, r_up_U(), Radius, plotPSD::t, and Eigen::zeta().
Referenced by macro_element_boundary(), and r_front_U().
r_up_L()
void oomph::EighthSphereDomain::r_up_L (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of top left box macro element zeta \(\in [-1,1]^2 \)
   {
     // position vector on sphere
     Vector<double> on_sphere(3);
     Vector<double> temp_zeta(2);
     temp_zeta[0] = -1.0;
     temp_zeta[1] = zeta[1];
     r_up_U(t, temp_zeta, on_sphere);
     // position vector on center box
     Vector<double> on_center(3);
     on_center[0] = 0.0;
     on_center[1] = 0.5 * Radius;
     on_center[2] = 0.5 * Radius * 0.5 * (zeta[1] + 1.0);
     // strait line across
     for (unsigned i = 0; i < 3; i++)
     {
       f[i] =
         on_center[i] + 0.5 * (zeta[0] + 1.0) * (on_sphere[i] - on_center[i]);
     }
   }
References f(), i, r_up_U(), Radius, plotPSD::t, and Eigen::zeta().
Referenced by macro_element_boundary().
r_up_R()
void oomph::EighthSphereDomain::r_up_R (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of top left box macro element zeta \(\in [-1,1]^2 \)
   {
     r_right_U(t, zeta, f);
   }
References f(), r_right_U(), plotPSD::t, and Eigen::zeta().
Referenced by macro_element_boundary().
r_up_U()
void oomph::EighthSphereDomain::r_up_U (const unsigned & t, const Vector< double > & zeta, Vector< double > & f) private
Boundary of top left box macro element zeta \(\in [-1,1]^2 \)
   {
     double k0 = 0.5 * (1.0 + zeta[0]);
     double k1 = 0.5 * (1.0 + zeta[1]);
     Vector<double> p(3);
     Vector<double> point1(3);
     Vector<double> point2(3);
     point1[0] = 0.5 * Radius * k0;
     point1[1] = Radius - 0.5 * Radius * k0;
     point1[2] = 0;
     point2[0] = k0 * Radius / 3.0;
     point2[1] = 0.5 * Radius - k0 * Radius / 6.0;
     point2[2] = 0.5 * Radius - k0 * Radius / 6.0;
     for (unsigned i = 0; i < 3; i++)
     {
       p[i] = point1[i] + k1 * (point2[i] - point1[i]);
     }
     double alpha = Radius / std::sqrt(p[0] * p[0] + p[1] * p[1] + p[2] * p[2]);
     for (unsigned i = 0; i < 3; i++)
     {
       f[i] = alpha * p[i];
     }
   }
References alpha, f(), i, p, Radius, sqrt(), and Eigen::zeta().
Referenced by macro_element_boundary(), r_up_B(), r_up_F(), and r_up_L().
Member Data Documentation
Radius
double oomph::EighthSphereDomain::Radius private
Referenced by r_centr_B(), r_centr_D(), r_centr_F(), r_centr_L(), r_centr_R(), r_centr_U(), r_front_D(), r_front_F(), r_front_L(), r_right_B(), r_right_D(), r_right_F(), r_right_R(), r_right_U(), r_up_B(), r_up_F(), r_up_L(), and r_up_U().
The documentation for this class was generated from the following file:
eighth_sphere_domain.h