MercuryDPM: boostmultiprec.cpp File Reference
boostmultiprec.cpp File Reference
#include <sstream>
#include <Eigen/Dense>
#include <boost/serialization/nvp.hpp>
#include <boost/multiprecision/cpp_dec_float.hpp>
#include <boost/multiprecision/number.hpp>
#include <boost/math/special_functions.hpp>
#include <boost/math/complex.hpp>
Classes
struct Eigen::NumTraits< Real >
struct Eigen::NumTraits< boost::multiprecision::detail::expression< T1, T2, T3, T4, T5 > >
struct Eigen::internal::cast_impl< Real, NewType >
struct Eigen::internal::cast_impl< Real, std::complex< Real > >
Namespaces
Eigen
Namespace containing all symbols from the Eigen library.
Eigen::internal
Namespace containing low-level routines from the Eigen library.
boost
boost::multiprecision
Macros
#define EIGEN_TEST_MAX_SIZE 50
Typedefs
typedef boost::multiprecision::number< boost::multiprecision::cpp_dec_float< 100 >, boost::multiprecision::et_on > Real
Functions
template<>
Real Eigen::test_precision< Real > ()
Real boost::multiprecision::fabs (const Real &a)
Real boost::multiprecision::fmax (const Real &a, const Real &b)
bool boost::multiprecision::test_isMuchSmallerThan (const Real &a, const Real &b)
bool boost::multiprecision::test_isApprox (const Real &a, const Real &b)
bool boost::multiprecision::test_isApproxOrLessThan (const Real &a, const Real &b)
Real boost::multiprecision::get_test_precision (const Real &)
Real boost::multiprecision::test_relative_error (const Real &a, const Real &b)
EIGEN_DECLARE_TEST (boostmultiprec)
Macro Definition Documentation
EIGEN_TEST_MAX_SIZE
#define EIGEN_TEST_MAX_SIZE 50
Typedef Documentation
Real
typedef boost::multiprecision::number<boost::multiprecision::cpp_dec_float<100>, boost::multiprecision::et_on> Real
Function Documentation
EIGEN_DECLARE_TEST()
EIGEN_DECLARE_TEST (boostmultiprec)
{
   typedef Matrix<Real, Dynamic, Dynamic> Mat;
   typedef Matrix<std::complex<Real>, Dynamic, Dynamic> MatC;
   std::cout << "NumTraits<Real>::epsilon()         = " << NumTraits<Real>::epsilon() << std::endl;
   std::cout << "NumTraits<Real>::dummy_precision() = " << NumTraits<Real>::dummy_precision() << std::endl;
   std::cout << "NumTraits<Real>::lowest()          = " << NumTraits<Real>::lowest() << std::endl;
   std::cout << "NumTraits<Real>::highest()         = " << NumTraits<Real>::highest() << std::endl;
   std::cout << "NumTraits<Real>::digits10()        = " << NumTraits<Real>::digits10() << std::endl;
   std::cout << "NumTraits<Real>::max_digits10()    = " << NumTraits<Real>::max_digits10() << std::endl;
   // check stream output
   {
     Mat A(10, 10);
     A.setRandom();
     std::stringstream ss;
     ss << A;
   }
   {
     MatC A(10, 10);
     A.setRandom();
     std::stringstream ss;
     ss << A;
   }
   for (int i = 0; i < g_repeat; i++) {
     int s = internal::random<int>(1, EIGEN_TEST_MAX_SIZE);
     CALL_SUBTEST_1(cholesky(Mat(s, s)));
     CALL_SUBTEST_2(lu_non_invertible<Mat>());
     CALL_SUBTEST_2(lu_invertible<Mat>());
     CALL_SUBTEST_2(lu_non_invertible<MatC>());
     CALL_SUBTEST_2(lu_invertible<MatC>());
     CALL_SUBTEST_3(
         qr(Mat(internal::random<int>(1, EIGEN_TEST_MAX_SIZE), internal::random<int>(1, EIGEN_TEST_MAX_SIZE))));
     CALL_SUBTEST_3(qr_invertible<Mat>());
     CALL_SUBTEST_4(qr<Mat>());
     CALL_SUBTEST_4(cod<Mat>());
     CALL_SUBTEST_4(qr_invertible<Mat>());
     CALL_SUBTEST_5(qr<Mat>());
     CALL_SUBTEST_5(qr_invertible<Mat>());
     CALL_SUBTEST_6(selfadjointeigensolver(Mat(s, s)));
     CALL_SUBTEST_7(eigensolver(Mat(s, s)));
     CALL_SUBTEST_8(generalized_eigensolver_real(Mat(s, s)));
     TEST_SET_BUT_UNUSED_VARIABLE(s)
   }
   CALL_SUBTEST_9(
       (jacobisvd_thin_options(Mat(internal::random<int>(EIGEN_TEST_MAX_SIZE / 4, EIGEN_TEST_MAX_SIZE),
                                   internal::random<int>(EIGEN_TEST_MAX_SIZE / 4, EIGEN_TEST_MAX_SIZE / 2)))));
   CALL_SUBTEST_9(
       (jacobisvd_full_options(Mat(internal::random<int>(EIGEN_TEST_MAX_SIZE / 4, EIGEN_TEST_MAX_SIZE),
                                   internal::random<int>(EIGEN_TEST_MAX_SIZE / 4, EIGEN_TEST_MAX_SIZE / 2)))));
   CALL_SUBTEST_10((bdcsvd_thin_options(Mat(internal::random<int>(EIGEN_TEST_MAX_SIZE / 4, EIGEN_TEST_MAX_SIZE),
                                            internal::random<int>(EIGEN_TEST_MAX_SIZE / 4, EIGEN_TEST_MAX_SIZE / 2)))));
   CALL_SUBTEST_10((bdcsvd_full_options(Mat(internal::random<int>(EIGEN_TEST_MAX_SIZE / 4, EIGEN_TEST_MAX_SIZE),
                                            internal::random<int>(EIGEN_TEST_MAX_SIZE / 4, EIGEN_TEST_MAX_SIZE / 2)))));
   CALL_SUBTEST_11((test_simplicial_cholesky_T<Real, int, ColMajor>()));
 }
References bdcsvd_full_options(), bdcsvd_thin_options(), CALL_SUBTEST_1, CALL_SUBTEST_10, CALL_SUBTEST_11, CALL_SUBTEST_2, CALL_SUBTEST_3, CALL_SUBTEST_4, CALL_SUBTEST_5, CALL_SUBTEST_6, CALL_SUBTEST_7, CALL_SUBTEST_8, CALL_SUBTEST_9, cholesky(), Eigen::Dynamic, EIGEN_TEST_MAX_SIZE, eigensolver(), oomph::SarahBL::epsilon, Eigen::g_repeat, generalized_eigensolver_real(), i, jacobisvd_full_options(), jacobisvd_thin_options(), qr(), s, selfadjointeigensolver(), and TEST_SET_BUT_UNUSED_VARIABLE.