MercuryDPM: LiquidMigrationWilletViscousSpecies Class Reference
LiquidMigrationWilletViscousSpecies Class Reference
LiquidMigrationWilletViscousSpecies contains the parameters used to describe a short-range force caused by liquid bridges.
#include <LiquidMigrationWilletViscousSpecies.h>
Public Types
typedef LiquidMigrationWilletViscousInteraction InteractionType
The correct Interaction type for this AdhesiveForceSpecies.
Public Types inherited from LiquidMigrationWilletSpecies
typedef LiquidMigrationWilletInteraction InteractionType
The correct Interaction type for this AdhesiveForceSpecies.
Public Member Functions
LiquidMigrationWilletViscousSpecies ()
The default constructor.
LiquidMigrationWilletViscousSpecies (const LiquidMigrationWilletViscousSpecies &s)
The default copy constructor.
~LiquidMigrationWilletViscousSpecies ()
The default destructor.
void read (std::istream &is)
Reads the species properties from an input stream.
void write (std::ostream &os) const
Writes the species properties to an output stream.
std::string getBaseName () const
Used in Species::getName to obtain a unique name for each Species.
void mix (LiquidMigrationWilletViscousSpecies *S, LiquidMigrationWilletViscousSpecies *T)
creates default values for mixed species
void setViscosity (Mdouble viscosity)
used to set the Viscosity of the liquid.
Mdouble getViscosity () const
used to access the Viscosity of the liquid.
Public Member Functions inherited from LiquidMigrationWilletSpecies
LiquidMigrationWilletSpecies ()
The default constructor.
LiquidMigrationWilletSpecies (const LiquidMigrationWilletSpecies &s)
The default copy constructor.
~LiquidMigrationWilletSpecies ()
The default destructor.
void read (std::istream &is)
Reads the species properties from an input stream.
void write (std::ostream &os) const
Writes the species properties to an output stream.
std::string getBaseName () const
Used in Species::getName to obtain a unique name for each Species.
void mix (LiquidMigrationWilletSpecies *S, LiquidMigrationWilletSpecies *T)
creates default values for mixed species
void setInteractionDistance ()
returns the largest separation distance at which adhesive short-range forces can occur.
void setLiquidBridgeVolumeMax (Mdouble liquidBridgeVolume)
used to set the Volume of the liquid bridge.
Mdouble getLiquidBridgeVolumeMax () const
used to access the Volume of the liquid bridge.
void setLiquidBridgeVolumeMin (Mdouble)
used to set the Volume of the liquid bridge.
Mdouble getLiquidBridgeVolumeMin () const
used to access the Volume of the liquid bridge.
void setDistributionCoefficient (Mdouble distributionCoefficient)
used to set the distribution coefficient of the liquid.
Mdouble getDistributionCoefficient () const
used to access the surface tension of the liquid.
void setSurfaceTension (Mdouble surfaceTension)
used to set the surface tension of the liquid.
Mdouble getSurfaceTension () const
used to access the surface tension of the liquid.
void setContactAngle (Mdouble contactAngle)
used to set the contact angle between particle and liquid bridge surface (in radians)
Mdouble getContactAngle () const
used to access the contact angle between particle and liquid bridge surface.
Public Member Functions inherited from BaseForce
BaseSpecies * getBaseSpecies () const
void setBaseSpecies (BaseSpecies *baseSpecies)
Private Attributes
Mdouble viscosity_
viscosity of the liquid
Detailed Description
LiquidMigrationWilletViscousSpecies contains the parameters used to describe a short-range force caused by liquid bridges.
See LiquidMigrationWilletViscousInteraction::computeAdhesionForce for a description of the force law.
Member Typedef Documentation
InteractionType
typedef LiquidMigrationWilletViscousInteraction LiquidMigrationWilletViscousSpecies::InteractionType
The correct Interaction type for this AdhesiveForceSpecies.
Constructor & Destructor Documentation
LiquidMigrationWilletViscousSpecies() [1/2]
LiquidMigrationWilletViscousSpecies::LiquidMigrationWilletViscousSpecies ()
The default constructor.
         : LiquidMigrationWilletSpecies()
 {
     viscosity_ = 0.0;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"LiquidMigrationWilletViscousSpecies::LiquidMigrationWilletViscousSpecies() finished"<<std::endl;
 #endif
 }
References viscosity_.
LiquidMigrationWilletViscousSpecies() [2/2]
LiquidMigrationWilletViscousSpecies::LiquidMigrationWilletViscousSpecies (const LiquidMigrationWilletViscousSpecies & s)
The default copy constructor.
Parameters
[in] the species that is copied
         : LiquidMigrationWilletSpecies(s)
 {
     viscosity_ = s.viscosity_;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"LiquidMigrationWilletViscousSpecies::LiquidMigrationWilletViscousSpecies(const LiquidMigrationWilletViscousSpecies &p) finished"<<std::endl;
 #endif
 }
References s, and viscosity_.
~LiquidMigrationWilletViscousSpecies()
LiquidMigrationWilletViscousSpecies::~LiquidMigrationWilletViscousSpecies ()
The default destructor.
 {
 #ifdef DEBUG_DESTRUCTOR
     std::cout<<"LiquidMigrationWilletViscousSpecies::~LiquidMigrationWilletViscousSpecies() finished"<<std::endl;
 #endif
 }
Member Function Documentation
getBaseName()
std::string LiquidMigrationWilletViscousSpecies::getBaseName () const
Used in Species::getName to obtain a unique name for each Species.
Returns
a string containing the name of the species (minus the word "Species")
 {
     return "LiquidMigrationWilletViscous";
 }
getViscosity()
Mdouble LiquidMigrationWilletViscousSpecies::getViscosity () const
used to access the Viscosity of the liquid.
Returns
the the viscosity of the liquid.
 {
     return viscosity_;
 }
References viscosity_.
Referenced by LiquidMigrationWilletViscousInteraction::computeAdhesionForce().
mix()
void LiquidMigrationWilletViscousSpecies::mix (LiquidMigrationWilletViscousSpecies * S, LiquidMigrationWilletViscousSpecies * T)
creates default values for mixed species
For all parameters we assume that the harmonic mean of the parameters of the original two species is a sensible default.
Parameters
[in] S,T the two species whose properties are mixed to create the new species
 {
     LiquidMigrationWilletSpecies::mix(S, T);
     viscosity_ = BaseSpecies::average(S->getViscosity(), T->getViscosity());
 }
References BaseSpecies::average(), LiquidMigrationWilletSpecies::mix(), oomph::QuadTreeNames::S, and viscosity_.
read()
void LiquidMigrationWilletViscousSpecies::read (std::istream & is)
Reads the species properties from an input stream.
Parameters
[in] input stream (typically the restart file)
 {
     LiquidMigrationWilletSpecies::read(is);
     std::string dummy;
     is >> dummy >> viscosity_;
 }
References LiquidMigrationWilletSpecies::read(), oomph::Global_string_for_annotation::string(), and viscosity_.
setViscosity()
void LiquidMigrationWilletViscousSpecies::setViscosity (Mdouble viscosity)
used to set the Viscosity of the liquid.
Parameters
[in] viscosity the viscosity of the liquid.
 {
     logger.assert_always(viscosity >= 0, "Error in setViscosity(%), viscosity should be >= 0", viscosity);
     viscosity_ = viscosity;
 }
References logger, and viscosity_.
write()
void LiquidMigrationWilletViscousSpecies::write (std::ostream & os) const
Writes the species properties to an output stream.
Parameters
[out] output stream (typically the restart file)
 {
     LiquidMigrationWilletSpecies::write(os);
     os << " viscosity_ " << viscosity_;
 }
References viscosity_, and LiquidMigrationWilletSpecies::write().
Member Data Documentation
viscosity_
Mdouble LiquidMigrationWilletViscousSpecies::viscosity_ private
viscosity of the liquid
Referenced by getViscosity(), LiquidMigrationWilletViscousSpecies(), mix(), read(), setViscosity(), and write().
The documentation for this class was generated from the following files:
LiquidMigrationWilletViscousSpecies.h
LiquidMigrationWilletViscousSpecies.cc