MercuryDPM: Eigen::internal::MappedSuperNodalMatrix< Scalar_, StorageIndex_ >::InnerIterator Class Reference
Eigen::internal::MappedSuperNodalMatrix< Scalar_, StorageIndex_ >::InnerIterator Class Reference
InnerIterator class to iterate over nonzero values of the current column in the supernodal matrix L.
#include <SparseLU_SupernodalMatrix.h>
Public Member Functions
InnerIterator (const MappedSuperNodalMatrix &mat, Index outer)
InnerIterator & operator++ ()
Scalar value () const
Scalar & valueRef ()
Index index () const
Index row () const
Index col () const
Index supIndex () const
operator bool () const
Protected Attributes
const MappedSuperNodalMatrix & m_matrix
const Index m_outer
const Index m_supno
Index m_idval
const Index m_startidval
const Index m_endidval
Index m_idrow
Index m_endidrow
Detailed Description
template<typename Scalar_, typename StorageIndex_>
class Eigen::internal::MappedSuperNodalMatrix< Scalar_, StorageIndex_ >::InnerIterator
InnerIterator class to iterate over nonzero values of the current column in the supernodal matrix L.
Constructor & Destructor Documentation
InnerIterator()
template<typename Scalar_ , typename StorageIndex_ > Eigen::internal::MappedSuperNodalMatrix< Scalar_, StorageIndex_ >::InnerIterator::InnerIterator (const MappedSuperNodalMatrix & mat, Index outer) inline
       : m_matrix(mat),
         m_outer(outer),
         m_supno(mat.colToSup()[outer]),
         m_idval(mat.colIndexPtr()[outer]),
         m_startidval(m_idval),
         m_endidval(mat.colIndexPtr()[outer + 1]),
         m_idrow(mat.rowIndexPtr()[mat.supToCol()[mat.colToSup()[outer]]]),
         m_endidrow(mat.rowIndexPtr()[mat.supToCol()[mat.colToSup()[outer]] + 1]) {}
Member Function Documentation
col()
template<typename Scalar_ , typename StorageIndex_ > Index Eigen::internal::MappedSuperNodalMatrix< Scalar_, StorageIndex_ >::InnerIterator::col () const inline
 { return m_outer; }
index()
template<typename Scalar_ , typename StorageIndex_ > Index Eigen::internal::MappedSuperNodalMatrix< Scalar_, StorageIndex_ >::InnerIterator::index () const inline
 { return m_matrix.rowIndex()[m_idrow]; }
operator bool()
template<typename Scalar_ , typename StorageIndex_ > Eigen::internal::MappedSuperNodalMatrix< Scalar_, StorageIndex_ >::InnerIterator::operator bool () const inline
{
     return ((m_idval < m_endidval) && (m_idval >= m_startidval) && (m_idrow < m_endidrow));
   }
operator++()
template<typename Scalar_ , typename StorageIndex_ > InnerIterator& Eigen::internal::MappedSuperNodalMatrix< Scalar_, StorageIndex_ >::InnerIterator::operator++ () inline
{
     m_idval++;
     m_idrow++;
     return *this;
   }
row()
template<typename Scalar_ , typename StorageIndex_ > Index Eigen::internal::MappedSuperNodalMatrix< Scalar_, StorageIndex_ >::InnerIterator::row () const inline
 { return index(); }
Referenced by Eigen::internal::MappedSuperNodalMatrix< Scalar_, StorageIndex_ >::solveInPlace(), and Eigen::internal::MappedSuperNodalMatrix< Scalar_, StorageIndex_ >::solveTransposedInPlace().
supIndex()
template<typename Scalar_ , typename StorageIndex_ > Index Eigen::internal::MappedSuperNodalMatrix< Scalar_, StorageIndex_ >::InnerIterator::supIndex () const inline
 { return m_supno; }
value()
template<typename Scalar_ , typename StorageIndex_ > Scalar Eigen::internal::MappedSuperNodalMatrix< Scalar_, StorageIndex_ >::InnerIterator::value () const inline
 { return m_matrix.valuePtr()[m_idval]; }
Referenced by Eigen::internal::MappedSuperNodalMatrix< Scalar_, StorageIndex_ >::solveInPlace(), and Eigen::internal::MappedSuperNodalMatrix< Scalar_, StorageIndex_ >::solveTransposedInPlace().
valueRef()
template<typename Scalar_ , typename StorageIndex_ > Scalar& Eigen::internal::MappedSuperNodalMatrix< Scalar_, StorageIndex_ >::InnerIterator::valueRef () inline
 { return const_cast<Scalar&>(m_matrix.valuePtr()[m_idval]); }
Member Data Documentation
m_endidrow
template<typename Scalar_ , typename StorageIndex_ > Index Eigen::internal::MappedSuperNodalMatrix< Scalar_, StorageIndex_ >::InnerIterator::m_endidrow protected
m_endidval
template<typename Scalar_ , typename StorageIndex_ > const Index Eigen::internal::MappedSuperNodalMatrix< Scalar_, StorageIndex_ >::InnerIterator::m_endidval protected
m_idrow
template<typename Scalar_ , typename StorageIndex_ > Index Eigen::internal::MappedSuperNodalMatrix< Scalar_, StorageIndex_ >::InnerIterator::m_idrow protected
m_idval
template<typename Scalar_ , typename StorageIndex_ > Index Eigen::internal::MappedSuperNodalMatrix< Scalar_, StorageIndex_ >::InnerIterator::m_idval protected
m_matrix
template<typename Scalar_ , typename StorageIndex_ > const MappedSuperNodalMatrix& Eigen::internal::MappedSuperNodalMatrix< Scalar_, StorageIndex_ >::InnerIterator::m_matrix protected
m_outer
template<typename Scalar_ , typename StorageIndex_ > const Index Eigen::internal::MappedSuperNodalMatrix< Scalar_, StorageIndex_ >::InnerIterator::m_outer protected
m_startidval
template<typename Scalar_ , typename StorageIndex_ > const Index Eigen::internal::MappedSuperNodalMatrix< Scalar_, StorageIndex_ >::InnerIterator::m_startidval protected
m_supno
template<typename Scalar_ , typename StorageIndex_ > const Index Eigen::internal::MappedSuperNodalMatrix< Scalar_, StorageIndex_ >::InnerIterator::m_supno protected
The documentation for this class was generated from the following file:
SparseLU_SupernodalMatrix.h