MercuryDPM: Eigen::internal::gebp_kernel< std::complex< double >, std::complex< double >, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs > Struct Template Reference
Eigen::internal::gebp_kernel< std::complex< double >, std::complex< double >, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs > Struct Template Reference
#include <MatrixProduct.h>
Public Types
typedef quad_traits< double >::vectortype Packet
typedef Packet1cd Packetc
typedef quad_traits< double >::rhstype RhsPacket
Public Member Functions
void operator() (const DataMapper &res, const std::complex< double > *blockA, const std::complex< double > *blockB, Index rows, Index depth, Index cols, std::complex< double > alpha, Index strideA=-1, Index strideB=-1, Index offsetA=0, Index offsetB=0)
Member Typedef Documentation
Packet
template<typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef quad_traits<double>::vectortype Eigen::internal::gebp_kernel< std::complex< double >, std::complex< double >, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::Packet
Packetc
template<typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef Packet1cd Eigen::internal::gebp_kernel< std::complex< double >, std::complex< double >, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::Packetc
RhsPacket
template<typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef quad_traits<double>::rhstype Eigen::internal::gebp_kernel< std::complex< double >, std::complex< double >, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::RhsPacket
Member Function Documentation
operator()()
template<typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> void Eigen::internal::gebp_kernel< std::complex< double >, std::complex< double >, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::operator() (const DataMapper & res, const std::complex< double > * blockA, const std::complex< double > * blockB, Index rows, Index depth, Index cols, std::complex< double > alpha, Index strideA = -1, Index strideB = -1, Index offsetA = 0, Index offsetB = 0)
{
   const Index accRows = quad_traits<double>::rows;
   const Index accCols = quad_traits<double>::size;
   static void (*gemm_function)(const DataMapper&, const std::complex<double>*, const std::complex<double>*, Index,
                                Index, Index, std::complex<double>, Index, Index, Index, Index) =
 #ifdef EIGEN_MATRIX_PRODUCT_MMA_ALTIVEC_H
       (supportsMMA())
           ? &Eigen::internal::gemm_complexMMA<std::complex<double>, std::complex<double>, std::complex<double>, double,
                                               Packet, Packetc, RhsPacket, DataMapper, accRows, accCols, ConjugateLhs,
                                               ConjugateRhs, false, false>
           :
 #endif
           &Eigen::internal::gemm_complex<std::complex<double>, std::complex<double>, std::complex<double>, double,
                                          Packet, Packetc, RhsPacket, DataMapper, accRows, accCols, ConjugateLhs,
                                          ConjugateRhs, false, false>;
   gemm_function(res, blockA, blockB, rows, depth, cols, alpha, strideA, strideB, offsetA, offsetB);
 }
References alpha, cols, Eigen::internal::gemm_complex(), Eigen::internal::gemm_complexMMA(), res, rows, and Eigen::internal::supportsMMA().
The documentation for this struct was generated from the following file:
MatrixProduct.h