MercuryDPM: bench_svd.cpp File Reference
bench_svd.cpp File Reference
#include <iostream>
#include <bench/BenchTimer.h>
#include <unsupported/Eigen/SVD>
Macros
#define REPEAT 10
#define NUMBER_SAMPLE 2
Functions
template<typename MatrixType >
void bench_svd (const MatrixType &a=MatrixType())
int main (int argc, char *argv[])
Macro Definition Documentation
NUMBER_SAMPLE
#define NUMBER_SAMPLE 2
REPEAT
#define REPEAT 10
Function Documentation
bench_svd()
template<typename MatrixType > void bench_svd (const MatrixType & a = MatrixType())
{
   MatrixType m = MatrixType::Random(a.rows(), a.cols());
   BenchTimer timerJacobi;
   BenchTimer timerBDC;
   timerJacobi.reset();
   timerBDC.reset();
   cout << " Only compute Singular Values" << endl;
   for (int k = 1; k <= NUMBER_SAMPLE; ++k) {
     timerBDC.start();
     for (int i = 0; i < REPEAT; ++i) {
       BDCSVD<MatrixType> bdc_matrix(m);
     }
     timerBDC.stop();
     timerJacobi.start();
     for (int i = 0; i < REPEAT; ++i) {
       JacobiSVD<MatrixType> jacobi_matrix(m);
     }
     timerJacobi.stop();
     cout << "Sample " << k << " : " << REPEAT << " computations :  Jacobi : " << fixed << timerJacobi.value() << "s ";
     cout << " || "
          << " BDC : " << timerBDC.value() << "s " << endl
          << endl;
     if (timerBDC.value() >= timerJacobi.value())
       cout << "KO : BDC is " << timerJacobi.value() / timerBDC.value() << "  times faster than Jacobi" << endl;
     else
       cout << "OK : BDC is " << timerJacobi.value() / timerBDC.value() << "  times faster than Jacobi" << endl;
   }
   cout << "       =================" << endl;
   std::cout << std::endl;
   timerJacobi.reset();
   timerBDC.reset();
   cout << " Computes rotation matrix" << endl;
   for (int k = 1; k <= NUMBER_SAMPLE; ++k) {
     timerBDC.start();
     for (int i = 0; i < REPEAT; ++i) {
       BDCSVD<MatrixType> bdc_matrix(m, ComputeFullU | ComputeFullV);
     }
     timerBDC.stop();
     timerJacobi.start();
     for (int i = 0; i < REPEAT; ++i) {
       JacobiSVD<MatrixType> jacobi_matrix(m, ComputeFullU | ComputeFullV);
     }
     timerJacobi.stop();
     cout << "Sample " << k << " : " << REPEAT << " computations :  Jacobi : " << fixed << timerJacobi.value() << "s ";
     cout << " || "
          << " BDC : " << timerBDC.value() << "s " << endl
          << endl;
     if (timerBDC.value() >= timerJacobi.value())
       cout << "KO : BDC is " << timerJacobi.value() / timerBDC.value() << "  times faster than Jacobi" << endl;
     else
       cout << "OK : BDC is " << timerJacobi.value() / timerBDC.value() << "  times faster than Jacobi" << endl;
   }
   std::cout << std::endl;
 }
References a, Eigen::ComputeFullU, Eigen::ComputeFullV, i, k, m, NUMBER_SAMPLE, REPEAT, Eigen::BenchTimer::reset(), Eigen::BenchTimer::start(), Eigen::BenchTimer::stop(), and Eigen::BenchTimer::value().
main()
int main (int argc , char * argv[])
{
   std::cout << std::endl;
   std::cout << "On a (Dynamic, Dynamic) (6, 6) Matrix" << std::endl;
   bench_svd<Matrix<double, Dynamic, Dynamic> >(Matrix<double, Dynamic, Dynamic>(6, 6));
   std::cout << "On a (Dynamic, Dynamic) (32, 32) Matrix" << std::endl;
   bench_svd<Matrix<double, Dynamic, Dynamic> >(Matrix<double, Dynamic, Dynamic>(32, 32));
   // std::cout<<"On a (Dynamic, Dynamic) (128, 128) Matrix" <<std::endl;
   // bench_svd<Matrix<double,Dynamic,Dynamic> >(Matrix<double,Dynamic,Dynamic>(128, 128));
   std::cout << "On a (Dynamic, Dynamic) (160, 160) Matrix" << std::endl;
   bench_svd<Matrix<double, Dynamic, Dynamic> >(Matrix<double, Dynamic, Dynamic>(160, 160));
   std::cout << "--------------------------------------------------------------------" << std::endl;
 }