MercuryDPM: oomph::PowerLawBerEngRegConstitutiveEquation< DIM > Class Template Reference
oomph::PowerLawBerEngRegConstitutiveEquation< DIM > Class Template Reference
#include <generalised_newtonian_constitutive_models.h>
Public Member Functions
PowerLawBerEngRegConstitutiveEquation (double *power_pt, double *reg_par_pt)
double viscosity (const double &second_invariant_of_rate_of_strain_tensor)
Public Member Functions inherited from oomph::GeneralisedNewtonianConstitutiveEquation< DIM >
GeneralisedNewtonianConstitutiveEquation ()
Empty constructor.
virtual ~GeneralisedNewtonianConstitutiveEquation ()
Empty virtual destructor.
virtual double dviscosity_dinvariant (const double &second_invariant_of_rate_of_strain_tensor)=0
Private Attributes
double * Power_pt
power law index n
double * Regularisation_parameter_pt
regularisation parameter e << 1
Detailed Description
template<unsigned DIM>
class oomph::PowerLawBerEngRegConstitutiveEquation< DIM >
A GeneralisedNewtonianConstitutiveEquation class defining a power-law fluid regularised according to Bercovier and Engelman (1980) to allow for n < 1
Constructor & Destructor Documentation
PowerLawBerEngRegConstitutiveEquation()
template<unsigned DIM> oomph::PowerLawBerEngRegConstitutiveEquation< DIM >::PowerLawBerEngRegConstitutiveEquation (double * power_pt, double * reg_par_pt) inline
       : GeneralisedNewtonianConstitutiveEquation<DIM>(),
         Power_pt(power_pt),
         Regularisation_parameter_pt(reg_par_pt)
     {
     }
Member Function Documentation
viscosity()
template<unsigned DIM> double oomph::PowerLawBerEngRegConstitutiveEquation< DIM >::viscosity (const double & second_invariant_of_rate_of_strain_tensor) inline virtual
Function implementing the constitutive model Input: second invariant of the rate of strain Output: the viscosity For Newtonian behaviour this returns 1
Implements oomph::GeneralisedNewtonianConstitutiveEquation< DIM >.
     {
       // Pre-multiply the second invariant with +/-1 depending on whether it's
       // positive or not
       double sign = -1.0;
       if (second_invariant_of_rate_of_strain_tensor >= 0.0)
       {
         sign = 1.0;
       }
       // Calculate the square root of the absolute value of the
       // second invariant of the rate of strain tensor
       double measure_of_rate_of_strain =
         sqrt(sign * second_invariant_of_rate_of_strain_tensor);
       return pow(
         (2.0 * measure_of_rate_of_strain + *Regularisation_parameter_pt),
         *Power_pt - 1.0);
     }
References Eigen::bfloat16_impl::pow(), oomph::PowerLawBerEngRegConstitutiveEquation< DIM >::Power_pt, oomph::PowerLawBerEngRegConstitutiveEquation< DIM >::Regularisation_parameter_pt, SYCL::sign(), and sqrt().
Member Data Documentation
Power_pt
template<unsigned DIM> double* oomph::PowerLawBerEngRegConstitutiveEquation< DIM >::Power_pt private
power law index n
Referenced by oomph::PowerLawBerEngRegConstitutiveEquation< DIM >::viscosity().
Regularisation_parameter_pt
template<unsigned DIM> double* oomph::PowerLawBerEngRegConstitutiveEquation< DIM >::Regularisation_parameter_pt private
regularisation parameter e << 1
Referenced by oomph::PowerLawBerEngRegConstitutiveEquation< DIM >::viscosity().
The documentation for this class was generated from the following file:
generalised_newtonian_constitutive_models.h