MercuryDPM: Eigen::internal::generic_y1< T, float > Struct Template Reference
Eigen::internal::generic_y1< T, float > Struct Template Reference
#include <BesselFunctionsImpl.h>
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T run (const T &x)
Member Function Documentation
run()
template<typename T > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE T Eigen::internal::generic_y1< T, float >::run (const T & x) inline static
{
     /* j1f.c
      *  Bessel function of second kind of order one
      *
      *
      *
      * SYNOPSIS:
      *
      * double x, y, y1();
      *
      * y = y1( x );
      *
      *
      *
      * DESCRIPTION:
      *
      * Returns Bessel function of the second kind of order one
      * of the argument.
      *
      * The domain is divided into the intervals [0, 2] and
      * (2, infinity). In the first interval a rational approximation
      * R(x) is employed to compute
      *
      *                  2
      * y0(x)  =  (w - r  ) x R(x^2)  +  2/pi (ln(x) j1(x) - 1/x) .
      *                 1
      *
      * Thus a call to j1() is required.
      *
      * In the second interval, the modulus and phase are approximated
      * by polynomials of the form Modulus(x) = sqrt(1/x) Q(1/x)
      * and Phase(x) = x + 1/x S(1/x^2) - 3pi/4.  Then the function is
      *
      *   y0(x) = Modulus(x) sin( Phase(x) ).
      *
      *
      *
      *
      * ACCURACY:
      *
      *                      Absolute error:
      * arithmetic   domain      # trials      peak         rms
      *    IEEE      0,  2       100000       2.2e-7     4.6e-8
      *    IEEE      2, 32       100000       1.9e-7     5.3e-8
      *
      * (error criterion relative when |y1| > 1).
      *
      */
     const float YP[] = {8.061978323326852E-009f, -9.496460629917016E-007f, 6.719543806674249E-005f,
                         -2.641785726447862E-003f, 4.202369946500099E-002f};
     const float MO1[] = {6.913942741265801E-002f,  -2.284801500053359E-001f, 3.138238455499697E-001f,
                          -2.102302420403875E-001f, 5.435364690523026E-003f,  1.493389585089498E-001f,
                          4.976029650847191E-006f,  7.978845453073848E-001f};
     const float PH1[] = {-4.497014141919556E+001f, 5.073465654089319E+001f,  -2.485774108720340E+001f,
                          7.222973196770240E+000f,  -1.544842782180211E+000f, 3.503787691653334E-001f,
                          -1.637986776941202E-001f, 3.749989509080821E-001f};
     const T YO1 = pset1<T>(4.66539330185668857532f);
     const T NEG_THPIO4F = pset1<T>(-2.35619449019234492885f); /* -3*pi/4 */
     const T TWOOPI = pset1<T>(0.636619772367581343075535f);   /* 2/pi */
     const T NEG_MAXNUM = pset1<T>(-NumTraits<float>::infinity());
     T z = pmul(x, x);
     T x_le_two = pmul(psub(z, YO1), internal::ppolevl<T, 4>::run(z, YP));
     x_le_two = pmadd(x_le_two, x, pmul(TWOOPI, pmadd(generic_j1<T, float>::run(x), plog(x), pdiv(pset1<T>(-1.0f), x))));
     x_le_two = pselect(pcmp_lt(x, pset1<T>(0.0f)), NEG_MAXNUM, x_le_two);
     T q = pdiv(pset1<T>(1.0), x);
     T w = prsqrt(x);
     T p = pmul(w, internal::ppolevl<T, 7>::run(q, MO1));
     w = pmul(q, q);
     T xn = pmadd(q, internal::ppolevl<T, 7>::run(w, PH1), NEG_THPIO4F);
     T x_gt_two = pmul(p, psin(padd(xn, x)));
     return pselect(pcmp_le(x, pset1<T>(2.0)), x_le_two, x_gt_two);
   }
References p, Eigen::internal::padd(), Eigen::internal::pcmp_le(), Eigen::internal::pcmp_lt(), Eigen::internal::pdiv(), Eigen::internal::plog(), Eigen::internal::pmadd(), Eigen::internal::pmul(), Eigen::internal::prsqrt(), Eigen::internal::pselect(), Eigen::internal::psin(), Eigen::internal::psub(), Eigen::numext::q, w, and plotDoE::x.
The documentation for this struct was generated from the following file:
BesselFunctionsImpl.h