MercuryDPM: Eigen::internal::patan_reduced< Scalar > Struct Template Reference
Eigen::internal::patan_reduced< Scalar > Struct Template Reference
#include <GenericPacketMathFunctions.h>
Public Member Functions
EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet run (const Packet &x)
EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet run (const Packet &x)
Static Public Member Functions
template<typename Packet >
static EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet run (const Packet &x)
Member Function Documentation
run() [1/3]
template<typename Scalar > template<typename Packet > static EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet Eigen::internal::patan_reduced< Scalar >::run (const Packet & x) static
Referenced by Eigen::internal::generic_atan().
run() [2/3]
EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet Eigen::internal::patan_reduced< double >::run (const Packet & x)
{
   constexpr double alpha[] = {2.6667153866462208e-05, 3.0917513112462781e-03, 5.2574296781008604e-02,
                               3.0409318473444424e-01, 7.5365702534987022e-01, 8.2704055405494614e-01,
                               3.3004361289279920e-01};
   constexpr double beta[] = {
       2.7311202462436667e-04, 1.0899150928962708e-02, 1.1548932646420353e-01, 4.9716458728465573e-01, 1.0,
       9.3705509168587852e-01, 3.3004361289279920e-01};
   Packet x2 = pmul(x, x);
   Packet p = ppolevl<Packet, 6>::run(x2, alpha);
   Packet q = ppolevl<Packet, 6>::run(x2, beta);
   return pmul(x, pdiv(p, q));
 }
References alpha, beta, p, Eigen::internal::pdiv(), Eigen::internal::pmul(), Eigen::numext::q, Eigen::internal::ppolevl< Packet, N >::run(), plotDoE::x, and Global_parameters::x2().
run() [3/3]
EIGEN_DEFINE_FUNCTION_ALLOWING_MULTIPLE_DEFINITIONS Packet Eigen::internal::patan_reduced< float >::run (const Packet & x)
{
   constexpr float alpha[] = {1.12026982009410858154296875e-01f, 7.296695709228515625e-01f, 8.109951019287109375e-01f};
   constexpr float beta[] = {1.00917108356952667236328125e-02f, 2.8318560123443603515625e-01f, 1.0f,
                             8.109951019287109375e-01f};
   Packet x2 = pmul(x, x);
   Packet p = ppolevl<Packet, 2>::run(x2, alpha);
   Packet q = ppolevl<Packet, 3>::run(x2, beta);
   return pmul(x, pdiv(p, q));
 }
References alpha, beta, p, Eigen::internal::pdiv(), Eigen::internal::pmul(), Eigen::numext::q, Eigen::internal::ppolevl< Packet, N >::run(), plotDoE::x, and Global_parameters::x2().
The documentation for this struct was generated from the following file:
GenericPacketMathFunctions.h