MercuryDPM: Eigen::SluMatrixMapHelper< SparseMatrixBase< Derived > > Struct Template Reference
Eigen::SluMatrixMapHelper< SparseMatrixBase< Derived > > Struct Template Reference
#include <SuperLUSupport.h>
Public Types
typedef Derived MatrixType
Static Public Member Functions
static void run (MatrixType &mat, SluMatrix &res)
Member Typedef Documentation
MatrixType
template<typename Derived > typedef Derived Eigen::SluMatrixMapHelper< SparseMatrixBase< Derived > >::MatrixType
Member Function Documentation
run()
template<typename Derived > static void Eigen::SluMatrixMapHelper< SparseMatrixBase< Derived > >::run (MatrixType & mat, SluMatrix & res) inline static
{
     if ((MatrixType::Flags & RowMajorBit) == RowMajorBit) {
       res.setStorageType(SLU_NR);
       res.nrow = mat.cols();
       res.ncol = mat.rows();
     } else {
       res.setStorageType(SLU_NC);
       res.nrow = mat.rows();
       res.ncol = mat.cols();
     }
     res.Mtype = SLU_GE;
     res.storage.nnz = mat.nonZeros();
     res.storage.values = mat.valuePtr();
     res.storage.innerInd = mat.innerIndexPtr();
     res.storage.outerInd = mat.outerIndexPtr();
     res.setScalarType<typename MatrixType::Scalar>();
     // FIXME the following is not very accurate
     if (MatrixType::Flags & Upper) res.Mtype = SLU_TRU;
     if (MatrixType::Flags & Lower) res.Mtype = SLU_TRL;
     eigen_assert(((MatrixType::Flags & SelfAdjoint) == 0) && "SelfAdjoint matrix shape not supported by SuperLU");
   }
References Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::cols(), eigen_assert, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::innerIndexPtr(), Eigen::Lower, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::nonZeros(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::outerIndexPtr(), res, Eigen::RowMajorBit, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::rows(), Eigen::SelfAdjoint, SLU_GE, SLU_NC, SLU_NR, SLU_TRL, SLU_TRU, Eigen::Upper, and Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::valuePtr().
The documentation for this struct was generated from the following file:
SuperLUSupport.h