MercuryDPM: MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies > Class Template Reference
MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies > Class Template Reference final
Contains contact force properties for contacts between particles with two different species.
#include <MixedSpecies.h>
Public Member Functions
MixedSpecies ()
The default constructor.
MixedSpecies (const MixedSpecies &s)
The default copy constructor.
MixedSpecies (const Species< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies > &s)
Creates a mixed species with the same force properties as a Species.
virtual ~MixedSpecies ()
The default destructor.
MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies > * copy () const final
Creates a deep copy of the MixedSpecies from which it is called.
void copyInto (BaseSpecies *bs) const final
Copies the content of this into the species bs, if they are of the same type.
void read (std::istream &is) final
Reads the species properties from an input stream.
void write (std::ostream &os) const final
Writes the MixedSpecies properties to an output stream.
std::string getName () const final
Returns the name of the MixedSpecies as it is used in the restart file.
BaseInteraction * getNewInteraction (BaseInteractable *const P, BaseInteractable *const I, unsigned timeStamp) const final
When a contact between two particles is determined, an Interaction object is created, as the type of Interaction depends on the MixedSpecies type.
BaseInteraction * getEmptyInteraction () const final
void deleteEmptyInteraction (BaseInteraction *interaction) const final
bool getUseAngularDOFs () const final
Returns true if torques have to be calculated.
void mixAll (BaseSpecies *const S, BaseSpecies *const T) final
sets the MixedSpecies properties by mixing the properties of
two particle species
Public Member Functions inherited from BaseSpecies
BaseSpecies ()
The default constructor.
BaseSpecies (BaseNormalForce *normalForce, BaseFrictionForce *frictionForce_, BaseAdhesiveForce *adhesiveForce)
BaseSpecies (const BaseSpecies &p)
The copy constructor.
~BaseSpecies ()
The default destructor.
void setHandler (SpeciesHandler *handler)
Sets the pointer to the handler to which this species belongs.
SpeciesHandler * getHandler () const
Returns the pointer to the handler to which this species belongs.
Mdouble getInteractionDistance () const
returns the largest separation distance at which adhesive short-range forces can occur.
BaseNormalForce * getNormalForce () const
BaseFrictionForce * getFrictionForce () const
BaseAdhesiveForce * getAdhesiveForce () const
void setInteractionDistance (Mdouble interactionDistance)
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Public Member Functions inherited from EmptyFrictionSpecies
EmptyFrictionSpecies ()
The default constructor.
EmptyFrictionSpecies (const EmptyFrictionSpecies &s UNUSED)
The default copy constructor.
~EmptyFrictionSpecies ()
The default destructor.
void read (std::istream &is)
Reads the species properties from an input stream.
void write (std::ostream &os) const
Writes the species properties to an output stream.
std::string getBaseName () const
Used in Species::getName to obtain a unique name for each Species.
void mix (EmptyFrictionSpecies *S, EmptyFrictionSpecies *T)
creates default values for mixed species
Public Member Functions inherited from BaseForce
BaseSpecies * getBaseSpecies () const
void setBaseSpecies (BaseSpecies *baseSpecies)
Public Member Functions inherited from EmptyAdhesiveSpecies
EmptyAdhesiveSpecies ()
The default constructor.
EmptyAdhesiveSpecies (const EmptyAdhesiveSpecies &s UNUSED)
The default copy constructor.
~EmptyAdhesiveSpecies ()
The default destructor.
void read (std::istream &is)
Reads the species properties from an input stream.
void write (std::ostream &os) const
Writes the species properties to an output stream.
std::string getBaseName () const
Used in Species::getName to obtain a unique name for each Species.
void mix (EmptyAdhesiveSpecies *S, EmptyAdhesiveSpecies *T)
creates default values for mixed species
Public Member Functions inherited from BaseAdhesiveForce
virtual void setInteractionDistance ()
Additional Inherited Members
Public Types inherited from EmptyFrictionSpecies
typedef EmptyFrictionInteraction InteractionType
The correct Interaction type for this FrictionForceSpecies.
Public Types inherited from EmptyAdhesiveSpecies
typedef EmptyAdhesiveInteraction InteractionType
The correct Interaction type for this AdhesiveForceSpecies.
Static Public Member Functions inherited from BaseSpecies
static Mdouble average (Mdouble a, Mdouble b)
Returns the harmonic mean of two variables.
static Mdouble averageInf (Mdouble a, Mdouble b)
Returns the harmonic mean of two variables, returning inf if either is inf.
Protected Attributes inherited from BaseSpecies
BaseNormalForce * normalForce_
A pointer to the normal force parameters.
BaseFrictionForce * frictionForce_
A pointer to the friction force parameters.
BaseAdhesiveForce * adhesiveForce_
A pointer to the adhesive force parameters.
Detailed Description
template<class NormalForceSpecies, class FrictionForceSpecies = EmptyFrictionSpecies, class AdhesiveForceSpecies = EmptyAdhesiveSpecies>
class MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >
Contains contact force properties for contacts between particles with two different species.
See Species for details.
Constructor & Destructor Documentation
MixedSpecies() [1/3]
template<class NormalForceSpecies , class FrictionForceSpecies , class AdhesiveForceSpecies > MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::MixedSpecies
The default constructor.
         : BaseSpecies(this,this,this), NormalForceSpecies(), FrictionForceSpecies(), AdhesiveForceSpecies()
 {
     normalForce_ = this;
     frictionForce_ = this;
     adhesiveForce_ = this;
     normalForce_->setBaseSpecies(this);
     frictionForce_->setBaseSpecies(this);
     adhesiveForce_->setBaseSpecies(this);
     logger(DEBUG, "MixedSpecies::MixedSpecies() finished");
 }
References BaseSpecies::adhesiveForce_, DEBUG, BaseSpecies::frictionForce_, logger, BaseSpecies::normalForce_, and BaseForce::setBaseSpecies().
MixedSpecies() [2/3]
template<class NormalForceSpecies , class FrictionForceSpecies , class AdhesiveForceSpecies > MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::MixedSpecies (const MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies > & s)
The default copy constructor.
         : BaseSpecies(s), NormalForceSpecies(s), FrictionForceSpecies(s), AdhesiveForceSpecies(s)
 {
     normalForce_ = this;
     frictionForce_ = this;
     adhesiveForce_ = this;
     normalForce_->setBaseSpecies(this);
     frictionForce_->setBaseSpecies(this);
     adhesiveForce_->setBaseSpecies(this);
     logger(DEBUG, "MixedSpecies::MixedSpecies(const MixedSpecies &p) finished");
 }
References BaseSpecies::adhesiveForce_, DEBUG, BaseSpecies::frictionForce_, logger, BaseSpecies::normalForce_, and BaseForce::setBaseSpecies().
MixedSpecies() [3/3]
template<class NormalForceSpecies , class FrictionForceSpecies , class AdhesiveForceSpecies > MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::MixedSpecies (const Species< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies > & s)
Creates a mixed species with the same force properties as a Species.
         : BaseSpecies(s), NormalForceSpecies(s), FrictionForceSpecies(s), AdhesiveForceSpecies(s)
 {
     normalForce_ = this;
     frictionForce_ = this;
     adhesiveForce_ = this;
     normalForce_->setBaseSpecies(this);
     frictionForce_->setBaseSpecies(this);
     adhesiveForce_->setBaseSpecies(this);
     logger(DEBUG, "MixedSpecies::MixedSpecies(const MixedSpecies &p) finished");
 }
References BaseSpecies::adhesiveForce_, DEBUG, BaseSpecies::frictionForce_, logger, BaseSpecies::normalForce_, and BaseForce::setBaseSpecies().
~MixedSpecies()
template<class NormalForceSpecies , class FrictionForceSpecies , class AdhesiveForceSpecies > MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::~MixedSpecies virtual
The default destructor.
 {
     logger(DEBUG, "MixedSpecies::~MixedSpecies() finished");
 }
References DEBUG, and logger.
Member Function Documentation
copy()
template<class NormalForceSpecies , class FrictionForceSpecies , class AdhesiveForceSpecies > MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies > * MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::copy final virtual
Creates a deep copy of the MixedSpecies from which it is called.
MixedSpecies copy method. It calls to copy constructor of this MixedSpecies, useful for polymorphism.
Implements BaseSpecies.
 {
     return new MixedSpecies(*this);
 }
Referenced by SpeciesHandler::readAndAddObject().
copyInto()
template<class NormalForceSpecies , class FrictionForceSpecies , class AdhesiveForceSpecies > void MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::copyInto (BaseSpecies * bs) const final virtual
Copies the content of this into the species bs, if they are of the same type.
Useful for polymorphism: speciesHandler.getObject(i)->copyInto(bs); creates a deep copy (i.e. also copies properties of the derived species), whereas bs = speciesHandler.getObject(i); would only create a shallow copy.
Implements BaseSpecies.
 {
     if (bs == nullptr)
     {
         logger(WARN, "Error in %::copyInto: cannot copy into a nullptr");
         return;
     }
     auto* s = dynamic_cast<MixedSpecies<NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies>*>(bs);
     if (s == nullptr)
     {
         logger(WARN, "Error in %::copyInto: copying of species failed", getName());
         return;
     }
     *s = *this;
 }
References getName(), logger, s, and WARN.
deleteEmptyInteraction()
template<class NormalForceSpecies , class FrictionForceSpecies , class AdhesiveForceSpecies > void MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::deleteEmptyInteraction (BaseInteraction * interaction) const final virtual
Implements BaseSpecies.
 {
     Interaction<typename NormalForceSpecies::InteractionType, typename FrictionForceSpecies::InteractionType, typename AdhesiveForceSpecies::InteractionType>* interactionDestroyer;
     interactionDestroyer = dynamic_cast<Interaction<typename NormalForceSpecies::InteractionType, typename FrictionForceSpecies::InteractionType, typename AdhesiveForceSpecies::InteractionType>*>(interaction);
     delete interactionDestroyer;
 }
getEmptyInteraction()
template<class NormalForceSpecies , class FrictionForceSpecies , class AdhesiveForceSpecies > BaseInteraction * MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::getEmptyInteraction () const final virtual
Todo:
add documentation
Implements BaseSpecies.
 {
     return new Interaction<typename NormalForceSpecies::InteractionType, typename FrictionForceSpecies::InteractionType, typename AdhesiveForceSpecies::InteractionType>();
 }
getName()
template<class NormalForceSpecies , class FrictionForceSpecies , class AdhesiveForceSpecies > std::string MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::getName final virtual
Returns the name of the MixedSpecies as it is used in the restart file.
Returns the name of the MixedSpecies as it is used in the restart file. The name of the species is a concatenation of the names of the three force
components, e.g.
MixedSpecies<LinearViscoelasticNormalSpecies,SlidingFrictionSpecies,ReversibleAdhesiveSpecies> species; std::cout << species.getName();
will output "LinearViscoelasticSlidingFrictionReversibleAdhesiveMixedSpecies". The EmptyFrictionSpecies and the EmptyAdhesiveSpecies return empty strings, such that
MixedSpecies<LinearViscoelasticNormalSpecies> species; std::cout << species.getName();
will output "LinearViscoelasticMixedSpecies".
Returns
The name of the MixedSpecies.
Implements BaseObject.
 {
     return NormalForceSpecies::getBaseName()
            + FrictionForceSpecies::getBaseName()
            + AdhesiveForceSpecies::getBaseName() + "MixedSpecies";
 }
getNewInteraction()
template<class NormalForceSpecies , class FrictionForceSpecies , class AdhesiveForceSpecies > BaseInteraction * MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::getNewInteraction (BaseInteractable *const P, BaseInteractable *const I, unsigned timeStamp) const final virtual
When a contact between two particles is determined, an Interaction object is created, as the type of Interaction depends on the MixedSpecies type.
The input parameters of this function are directly passed into the constructor for the new interaction. See Interaction for details.
Parameters
[in] P first of the two objects that interact
[in] I second of the two objects that interact
[in] timeStamp current value of DPMBase::time_
Returns
pointer to the newly created Interaction.
Implements BaseSpecies.
 {
     // JMFT: memory is allocated here, so it will need to be freed later
     return new Interaction<typename NormalForceSpecies::InteractionType, typename FrictionForceSpecies::InteractionType, typename AdhesiveForceSpecies::InteractionType>(
             P, I, timeStamp);
 }
References I, and Global_Physical_Variables::P.
getUseAngularDOFs()
template<class NormalForceSpecies , class FrictionForceSpecies , class AdhesiveForceSpecies > bool MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::getUseAngularDOFs final virtual
Returns true if torques have to be calculated.
Returns true for any FrictionForceSpecies except EmptyFrictionSpecies, because for spherical particles, torques are only caused by tangential forces. See SpeciesHandler::useAngularDOFs for more details
Returns
true iff torques have to be calculated
Implements BaseSpecies.
 {
     return FrictionForceSpecies::getUseAngularDOFs();
 }
mixAll()
template<class NormalForceSpecies , class FrictionForceSpecies , class AdhesiveForceSpecies > void MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::mixAll (BaseSpecies *const S , BaseSpecies *const T) final virtual
sets the MixedSpecies properties by mixing the properties of
two particle species
Uses the harmonic mean for most properties. Calls the mix function for each of the force species from which MixedSpecies is derived.
Parameters
[in] S the first of two species whose properties are mixed to create the new species
[in] T the second of two species whose properties are mixed to create the new species
Implements BaseSpecies.
 {
     logger.assert_always(T!= nullptr && S!= nullptr,"Arguments of mixAll cannot be null pointers");
     logger.assert_always(S->getNormalForce()->getConstantRestitution() == T->getNormalForce()->getConstantRestitution(), "mixing two LinearPlasticViscoelasticNormalSpecies, but only one has constantRestitution");
     NormalForceSpecies::setConstantRestitution(S->getNormalForce()->getConstantRestitution());
     const auto TN = dynamic_cast<NormalForceSpecies*> (T);
     const auto TF = dynamic_cast<FrictionForceSpecies*> (T);
     const auto TA = dynamic_cast<AdhesiveForceSpecies*> (T);
     logger.assert_always(TN!= nullptr && TF!= nullptr && TA!= nullptr,
             "Cannot mix two species of different type (% and %)",S->getName(),T->getName());
     const auto SN = dynamic_cast<NormalForceSpecies*> (S);
     const auto SF = dynamic_cast<FrictionForceSpecies*> (S);
     const auto SA = dynamic_cast<AdhesiveForceSpecies*> (S);
     logger.assert_always(SN!= nullptr && SF!= nullptr && SA!= nullptr,
             "Cannot mix two species of different type (% and %)",S->getName(),T->getName());
     NormalForceSpecies::mix(SN,TN);
     FrictionForceSpecies::mix(SF,TF);
     AdhesiveForceSpecies::mix(SA,TA);
 }
References logger, and oomph::QuadTreeNames::S.
Referenced by main().
read()
template<class NormalForceSpecies , class FrictionForceSpecies , class AdhesiveForceSpecies > void MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::read (std::istream & is) final virtual
Reads the species properties from an input stream.
Called by SpeciesHandler::readAndAddObject
Parameters
[in] is input stream (typically the restart file)
Reimplemented from BaseSpecies.
 {
     //note: name is already read by SpeciesHandler::readAndAddObject
     std::string dummy;
     unsigned int id, index;
     is >> dummy >> id;
     is >> dummy >> index;
     BaseObject::setId(id);
     BaseObject::setIndex(index);
     BaseSpecies::read(is);
     NormalForceSpecies::read(is);
     FrictionForceSpecies::read(is);
     AdhesiveForceSpecies::read(is);
     // ensure that interaction distance is recomputed after restarting
     AdhesiveForceSpecies::setInteractionDistance();
 }
References Eigen::TensorSycl::internal::read(), BaseSpecies::read(), BaseObject::setId(), BaseObject::setIndex(), and oomph::Global_string_for_annotation::string().
write()
template<class NormalForceSpecies , class FrictionForceSpecies , class AdhesiveForceSpecies > void MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::write (std::ostream & os) const final virtual
Writes the MixedSpecies properties to an output stream.
It prints human readable MixedSpecies information to the output stream, typically to Files::restartFile::fstream_. The basic species information is written in ParticleSpecies::write; then the three force types write additional information to the stream.
Parameters
[out] os output stream (typically the restart file)
Reimplemented from BaseSpecies.
 {
     os << getName();
     os << " idA " << BaseObject::getId();
     os << " idB " << BaseObject::getIndex();
     BaseSpecies::write(os);
     NormalForceSpecies::write(os);
     FrictionForceSpecies::write(os);
     AdhesiveForceSpecies::write(os);
 }
References BaseObject::getId(), BaseObject::getIndex(), getName(), Eigen::TensorSycl::internal::write(), and BaseSpecies::write().
The documentation for this class was generated from the following file:
MixedSpecies.h