MercuryDPM: oomph::TBubbleEnrichedElement< DIM, NNODE_1D > Class Template Reference
oomph::TBubbleEnrichedElement< DIM, NNODE_1D > Class Template Reference
#include <Telements.h>
Public Member Functions
const unsigned Central_node_on_face [3]
void build_face_element (const int &face_index, FaceElement *face_element_pt)
The face element for is the same in the two-dimesional case.
const unsigned Central_node_on_face [4]
void build_face_element (const int &face_index, FaceElement *face_element_pt)
Detailed Description
template<unsigned DIM, unsigned NNODE_1D>
class oomph::TBubbleEnrichedElement< DIM, NNODE_1D >
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// TElement class for which the shape functions have been enriched by a single bubble function of the next order
Empty, just establishes the template parameters
Member Function Documentation
build_face_element() [1/2]
void oomph::TBubbleEnrichedElement< 2, 3 >::build_face_element (const int & face_index, FaceElement * face_element_pt)
The face element for is the same in the two-dimesional case.
   {
     TElement<2, 3>::build_face_element(face_index, face_element_pt);
   }
build_face_element() [2/2]
void oomph::TBubbleEnrichedElement< 3, 3 >::build_face_element (const int & face_index, FaceElement * face_element_pt)
Function to setup geometrical information for lower-dimensional FaceElements (which are of type TBubbleEnrichedElement<2,3>).
   {
     // Call the standard unenriched build function
     TElement<3, 3>::build_face_element(face_index, face_element_pt);
     // Set the enriched number of total face nodes
     const unsigned n_face_nodes = 7;
     // Resize storage for the number of values originally stored
     // at the face element's nodes.
     face_element_pt->nbulk_value_resize(n_face_nodes);
     // Resize storage for the bulk node numbers corresponding to
     // the nodes of the face
     face_element_pt->bulk_node_number_resize(n_face_nodes);
     // So the faces are
     // 0 : s_0 fixed
     // 1 : s_1 fixed
     // 2 : s_2 fixed
     // 3 : sloping face
     // Copy central node across
     unsigned bulk_number = Central_node_on_face[face_index];
     face_element_pt->node_pt(n_face_nodes - 1) = node_pt(bulk_number);
     face_element_pt->bulk_node_number(n_face_nodes - 1) = bulk_number;
     // set the number of values originally stored at this node
     face_element_pt->nbulk_value(n_face_nodes - 1) =
       required_nvalue(bulk_number);
   }
References oomph::FaceElement::bulk_node_number(), oomph::FaceElement::bulk_node_number_resize(), oomph::FaceElement::nbulk_value(), oomph::FaceElement::nbulk_value_resize(), and oomph::FiniteElement::node_pt().
Central_node_on_face() [1/2]
const unsigned oomph::TBubbleEnrichedElement< 2, 3 >::Central_node_on_face
Central_node_on_face() [2/2]
const unsigned oomph::TBubbleEnrichedElement< 3, 3 >::Central_node_on_face
The documentation for this class was generated from the following file:
Telements.h