MercuryDPM: casting_test_runner< SrcScalar, EnableIf > Struct Template Reference
casting_test_runner< SrcScalar, EnableIf > Struct Template Reference
Static Public Member Functions
static void run ()
Member Function Documentation
run()
template<typename SrcScalar , typename EnableIf = void> static void casting_test_runner< SrcScalar, EnableIf >::run () inline static
                     {
     casting_test<SrcScalar, bool>::run();
     casting_test<SrcScalar, int8_t>::run();
     casting_test<SrcScalar, uint8_t>::run();
     casting_test<SrcScalar, int16_t>::run();
     casting_test<SrcScalar, uint16_t>::run();
     casting_test<SrcScalar, int32_t>::run();
     casting_test<SrcScalar, uint32_t>::run();
     casting_test<SrcScalar, int64_t>::run();
     casting_test<SrcScalar, uint64_t>::run();
     casting_test<SrcScalar, half>::run();
     casting_test<SrcScalar, bfloat16>::run();
     casting_test<SrcScalar, float>::run();
     casting_test<SrcScalar, double>::run();
     casting_test<SrcScalar, std::complex<float>>::run();
     casting_test<SrcScalar, std::complex<double>>::run();
   }
References casting_test< SrcScalar, TgtScalar >::run().
Referenced by casting_all(), and casting_test_runner< SrcScalar, std::enable_if_t<(NumTraits< SrcScalar >::IsComplex)> >::run().
The documentation for this struct was generated from the following file:
basicstuff.cpp