MercuryDPM: oomph::FoepplvonKarmanEquations Class Reference
oomph::FoepplvonKarmanEquations Class Reference abstract
#include <foeppl_von_karman_elements.h>
Public Types
typedef void(* FoepplvonKarmanPressureFctPt) (const Vector< double > &x, double &f)
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Public Member Functions
FoepplvonKarmanEquations ()
FoepplvonKarmanEquations (const FoepplvonKarmanEquations &dummy)=delete
Broken copy constructor.
void operator= (const FoepplvonKarmanEquations &)=delete
Broken assignment operator.
const double & eta () const
Eta.
double *& eta_pt ()
Pointer to eta.
void set_volume_constraint_pressure_data_as_external_data (Data *data_pt)
virtual unsigned nodal_index_fvk (const unsigned &i=0) const
void output (std::ostream &outfile)
Output with default number of plot points.
void output (std::ostream &outfile, const unsigned &n_plot)
void output (FILE *file_pt)
C_style output with default number of plot points.
void output (FILE *file_pt, const unsigned &n_plot)
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output exact soln: x,y,w_exact at n_plot^DIM plot points.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Get error against and norm of exact solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Dummy, time dependent error checker.
FoepplvonKarmanPressureFctPt & pressure_fct_pt ()
Access function: Pointer to pressure function.
FoepplvonKarmanPressureFctPt pressure_fct_pt () const
Access function: Pointer to pressure function. Const version.
FoepplvonKarmanPressureFctPt & airy_forcing_fct_pt ()
Access function: Pointer to Airy forcing function.
FoepplvonKarmanPressureFctPt airy_forcing_fct_pt () const
Access function: Pointer to Airy forcing function. Const version.
virtual void get_pressure_fvk (const unsigned &ipt, const Vector< double > &x, double &pressure) const
virtual void get_airy_forcing_fvk (const unsigned &ipt, const Vector< double > &x, double &airy_forcing) const
void get_gradient_of_deflection (const Vector< double > &s, Vector< double > &gradient) const
Get gradient of deflection: gradient[i] = dw/dx_i.
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Fill in the residuals with this element's contribution.
double interpolated_w_fvk (const Vector< double > &s, unsigned index=0) const
void interpolated_stress (const Vector< double > &s, double &sigma_xx, double &sigma_yy, double &sigma_xy)
Compute in-plane stresses.
virtual double get_bounded_volume () const
unsigned self_test ()
Self-test: Return 0 for OK.
void use_linear_bending_model ()
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
virtual void disable_ALE ()
virtual void enable_ALE ()
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual unsigned nvertex_node () const
virtual Node * vertex_node_pt (const unsigned &j) const
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Protected Member Functions
virtual double dshape_and_dtest_eulerian_fvk (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
virtual double dshape_and_dtest_eulerian_at_knot_fvk (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Attributes
double * Eta_pt
Pointer to global eta.
FoepplvonKarmanPressureFctPt Pressure_fct_pt
Pointer to pressure function:
FoepplvonKarmanPressureFctPt Airy_forcing_fct_pt
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Private Attributes
bool Linear_bending_model
int Volume_constraint_pressure_external_data_index
Static Private Attributes
static double Default_Physical_Constant_Value = 0.0
Default value for physical constants.
Additional Inherited Members
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
A class for all isoparametric elements that solve the Foeppl von Karman equations.
\[ \nabla^4 w - \eta Diamond^4(w,\phi) = p(x,y) \]
and
\[ \nabla^4 \phi + \frac{1}{2} Diamond^4(w,w) = 0 \]
This contains the generic maths. Shape functions, geometric mapping etc. must get implemented in derived class.
Member Typedef Documentation
FoepplvonKarmanPressureFctPt
typedef void(* oomph::FoepplvonKarmanEquations::FoepplvonKarmanPressureFctPt) (const Vector< double > &x, double &f)
Function pointer to pressure function fct(x,f(x)) – x is a Vector!
Constructor & Destructor Documentation
FoepplvonKarmanEquations() [1/2]
oomph::FoepplvonKarmanEquations::FoepplvonKarmanEquations () inline
Constructor (must initialise the Pressure_fct_pt and Airy_forcing_fct_pt to null). Also set physical parameters to their default values. No volume constraint applied by default.
                                : Pressure_fct_pt(0), Airy_forcing_fct_pt(0)
     {
       // Set all the physical constants to the default value (zero)
       Eta_pt = &Default_Physical_Constant_Value;
       Linear_bending_model = false;
       // No volume constraint
       Volume_constraint_pressure_external_data_index = -1;
     }
References Default_Physical_Constant_Value, Eta_pt, Linear_bending_model, and Volume_constraint_pressure_external_data_index.
FoepplvonKarmanEquations() [2/2]
oomph::FoepplvonKarmanEquations::FoepplvonKarmanEquations (const FoepplvonKarmanEquations & dummy) delete
Broken copy constructor.
Member Function Documentation
airy_forcing_fct_pt() [1/2]
FoepplvonKarmanPressureFctPt& oomph::FoepplvonKarmanEquations::airy_forcing_fct_pt () inline
Access function: Pointer to Airy forcing function.
     {
       return Airy_forcing_fct_pt;
     }
References Airy_forcing_fct_pt.
airy_forcing_fct_pt() [2/2]
FoepplvonKarmanPressureFctPt oomph::FoepplvonKarmanEquations::airy_forcing_fct_pt () const inline
Access function: Pointer to Airy forcing function. Const version.
     {
       return Airy_forcing_fct_pt;
     }
References Airy_forcing_fct_pt.
compute_error() [1/2]
void oomph::FoepplvonKarmanEquations::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) virtual
Get error against and norm of exact solution.
Validate against exact solution
Solution is provided via function pointer. Plot error at a given number of plot points.
Reimplemented from oomph::FiniteElement.
   {
     // Initialise
     error = 0.0;
     norm = 0.0;
     // Vector of local coordinates
     Vector<double> s(2);
     // Vector for coordintes
     Vector<double> x(2);
     // Find out how many nodes there are in the element
     unsigned n_node = nnode();
     Shape psi(n_node);
     // Set the value of n_intpt
     unsigned n_intpt = integral_pt()->nweight();
     // Tecplot
     outfile << "ZONE" << std::endl;
     // Exact solution Vector (here a scalar)
     // Vector<double> exact_soln(1);
     Vector<double> exact_soln(2);
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Assign values of s
       for (unsigned i = 0; i < 2; i++)
       {
         s[i] = integral_pt()->knot(ipt, i);
       }
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Get jacobian of mapping
       double J = J_eulerian(s);
       // Premultiply the weights and the Jacobian
       double W = w * J;
       // Get x position as Vector
       interpolated_x(s, x);
       // Get FE function value
       double w_fe = interpolated_w_fvk(s);
       // Get exact solution at this point
       (*exact_soln_pt)(x, exact_soln);
       // Output x,y,error
       for (unsigned i = 0; i < 2; i++)
       {
         outfile << x[i] << " ";
       }
       outfile << exact_soln[0] << " " << exact_soln[0] - w_fe << std::endl;
       // Add to error and norm
       norm += exact_soln[0] * exact_soln[0] * W;
       error += (exact_soln[0] - w_fe) * (exact_soln[0] - w_fe) * W;
     }
   }
References calibrate::error, ProblemParameters::exact_soln(), i, oomph::FiniteElement::integral_pt(), interpolated_w_fvk(), oomph::FiniteElement::interpolated_x(), J, oomph::FiniteElement::J_eulerian(), oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::Integral::nweight(), s, w, oomph::QuadTreeNames::W, oomph::Integral::weight(), and plotDoE::x.
compute_error() [2/2]
void oomph::FoepplvonKarmanEquations::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) inline virtual
Dummy, time dependent error checker.
Reimplemented from oomph::FiniteElement.
     {
       throw OomphLibError(
         "There is no time-dependent compute_error() for Foeppl von Karman"
         "elements",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
dshape_and_dtest_eulerian_at_knot_fvk()
virtual double oomph::FoepplvonKarmanEquations::dshape_and_dtest_eulerian_at_knot_fvk (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const protected pure virtual
Shape/test functions and derivs w.r.t. to global coords at integration point ipt; return Jacobian of mapping
Implemented in oomph::TFoepplvonKarmanElement< NNODE_1D >, and oomph::QFoepplvonKarmanElement< NNODE_1D >.
Referenced by fill_in_contribution_to_residuals().
dshape_and_dtest_eulerian_fvk()
virtual double oomph::FoepplvonKarmanEquations::dshape_and_dtest_eulerian_fvk (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const protected pure virtual
Shape/test functions and derivs w.r.t. to global coords at local coord. s; return Jacobian of mapping
Implemented in oomph::TFoepplvonKarmanElement< NNODE_1D >, and oomph::QFoepplvonKarmanElement< NNODE_1D >.
eta()
const double& oomph::FoepplvonKarmanEquations::eta () const inline
Eta.
     {
       return *Eta_pt;
     }
References Eta_pt.
Referenced by fill_in_contribution_to_residuals().
eta_pt()
double*& oomph::FoepplvonKarmanEquations::eta_pt () inline
Pointer to eta.
     {
       return Eta_pt;
     }
References Eta_pt.
fill_in_contribution_to_residuals()
void oomph::FoepplvonKarmanEquations::fill_in_contribution_to_residuals (Vector< double > & residuals) virtual
Fill in the residuals with this element's contribution.
Compute contribution to element residual Vector
Pure version without hanging nodes
Reimplemented from oomph::GeneralisedElement.
   {
     // Find out how many nodes there are
     const unsigned n_node = nnode();
     // Set up memory for the shape and test functions
     Shape psi(n_node), test(n_node);
     DShape dpsidx(n_node, 2), dtestdx(n_node, 2);
     // Indices at which the unknowns are stored
     const unsigned w_nodal_index = nodal_index_fvk(0);
     const unsigned laplacian_w_nodal_index = nodal_index_fvk(1);
     const unsigned phi_nodal_index = nodal_index_fvk(2);
     const unsigned laplacian_phi_nodal_index = nodal_index_fvk(3);
     const unsigned smooth_dwdx_nodal_index = nodal_index_fvk(4);
     const unsigned smooth_dwdy_nodal_index = nodal_index_fvk(5);
     const unsigned smooth_dphidx_nodal_index = nodal_index_fvk(6);
     const unsigned smooth_dphidy_nodal_index = nodal_index_fvk(7);
     // Set the value of n_intpt
     const unsigned n_intpt = integral_pt()->nweight();
     // Integers to store the local equation numbers
     int local_eqn = 0;
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Call the derivatives of the shape and test functions
       double J =
         dshape_and_dtest_eulerian_at_knot_fvk(ipt, psi, dpsidx, test, dtestdx);
       // Premultiply the weights and the Jacobian
       double W = w * J;
       // Allocate and initialise to zero storage for the interpolated values
       Vector<double> interpolated_x(2, 0.0);
       double interpolated_w = 0;
       double interpolated_laplacian_w = 0;
       double interpolated_phi = 0;
       double interpolated_laplacian_phi = 0;
       Vector<double> interpolated_dwdx(2, 0.0);
       Vector<double> interpolated_dlaplacian_wdx(2, 0.0);
       Vector<double> interpolated_dphidx(2, 0.0);
       Vector<double> interpolated_dlaplacian_phidx(2, 0.0);
       Vector<double> interpolated_smooth_dwdx(2, 0.0);
       Vector<double> interpolated_smooth_dphidx(2, 0.0);
       double interpolated_continuous_d2wdx2 = 0;
       double interpolated_continuous_d2wdy2 = 0;
       double interpolated_continuous_d2phidx2 = 0;
       double interpolated_continuous_d2phidy2 = 0;
       double interpolated_continuous_d2wdxdy = 0;
       double interpolated_continuous_d2phidxdy = 0;
       // Calculate function values and derivatives:
       //-----------------------------------------
       Vector<double> nodal_value(8, 0.0);
       // Loop over nodes
       for (unsigned l = 0; l < n_node; l++)
       {
         // Get the nodal values
         nodal_value[0] = raw_nodal_value(l, w_nodal_index);
         nodal_value[1] = raw_nodal_value(l, laplacian_w_nodal_index);
         if (!Linear_bending_model)
         {
           nodal_value[2] = raw_nodal_value(l, phi_nodal_index);
           nodal_value[3] = raw_nodal_value(l, laplacian_phi_nodal_index);
           nodal_value[4] = raw_nodal_value(l, smooth_dwdx_nodal_index);
           nodal_value[5] = raw_nodal_value(l, smooth_dwdy_nodal_index);
           nodal_value[6] = raw_nodal_value(l, smooth_dphidx_nodal_index);
           nodal_value[7] = raw_nodal_value(l, smooth_dphidy_nodal_index);
         }
         // Add contributions from current node/shape function
         interpolated_w += nodal_value[0] * psi(l);
         interpolated_laplacian_w += nodal_value[1] * psi(l);
         if (!Linear_bending_model)
         {
           interpolated_phi += nodal_value[2] * psi(l);
           interpolated_laplacian_phi += nodal_value[3] * psi(l);
           interpolated_smooth_dwdx[0] += nodal_value[4] * psi(l);
           interpolated_smooth_dwdx[1] += nodal_value[5] * psi(l);
           interpolated_smooth_dphidx[0] += nodal_value[6] * psi(l);
           interpolated_smooth_dphidx[1] += nodal_value[7] * psi(l);
           interpolated_continuous_d2wdx2 += nodal_value[4] * dpsidx(l, 0);
           interpolated_continuous_d2wdy2 += nodal_value[5] * dpsidx(l, 1);
           interpolated_continuous_d2phidx2 += nodal_value[6] * dpsidx(l, 0);
           interpolated_continuous_d2phidy2 += nodal_value[7] * dpsidx(l, 1);
           // mjr CHECK THESE
           interpolated_continuous_d2wdxdy +=
             0.5 *
             (nodal_value[4] * dpsidx(l, 1) + nodal_value[5] * dpsidx(l, 0));
           interpolated_continuous_d2phidxdy +=
             0.5 *
             (nodal_value[6] * dpsidx(l, 1) + nodal_value[7] * dpsidx(l, 0));
         }
         // Loop over directions
         for (unsigned j = 0; j < 2; j++)
         {
           interpolated_x[j] += raw_nodal_position(l, j) * psi(l);
           interpolated_dwdx[j] += nodal_value[0] * dpsidx(l, j);
           interpolated_dlaplacian_wdx[j] += nodal_value[1] * dpsidx(l, j);
           if (!Linear_bending_model)
           {
             interpolated_dphidx[j] += nodal_value[2] * dpsidx(l, j);
             interpolated_dlaplacian_phidx[j] += nodal_value[3] * dpsidx(l, j);
           }
         }
       }
       // Get pressure function
       //-------------------
       double pressure;
       get_pressure_fvk(ipt, interpolated_x, pressure);
       double airy_forcing;
       get_airy_forcing_fvk(ipt, interpolated_x, airy_forcing);
       // Assemble residuals and Jacobian
       //--------------------------------
       // Loop over the test functions
       for (unsigned l = 0; l < n_node; l++)
       {
         // Get the local equation
         local_eqn = nodal_local_eqn(l, w_nodal_index);
         // IF it's not a boundary condition
         if (local_eqn >= 0)
         {
           residuals[local_eqn] += pressure * test(l) * W;
           // Reduced order biharmonic operator
           for (unsigned k = 0; k < 2; k++)
           {
             residuals[local_eqn] +=
               interpolated_dlaplacian_wdx[k] * dtestdx(l, k) * W;
           }
           if (!Linear_bending_model)
           {
             // Monge-Ampere part
             residuals[local_eqn] += eta() *
                                     (interpolated_continuous_d2wdx2 *
                                        interpolated_continuous_d2phidy2 +
                                      interpolated_continuous_d2wdy2 *
                                        interpolated_continuous_d2phidx2 -
                                      2.0 * interpolated_continuous_d2wdxdy *
                                        interpolated_continuous_d2phidxdy) *
                                     test(l) * W;
           }
         }
         // Get the local equation
         local_eqn = nodal_local_eqn(l, laplacian_w_nodal_index);
         // IF it's not a boundary condition
         if (local_eqn >= 0)
         {
           // The coupled Poisson equations for the biharmonic operator
           residuals[local_eqn] += interpolated_laplacian_w * test(l) * W;
           for (unsigned k = 0; k < 2; k++)
           {
             residuals[local_eqn] += interpolated_dwdx[k] * dtestdx(l, k) * W;
           }
         }
         // Get the local equation
         local_eqn = nodal_local_eqn(l, phi_nodal_index);
         // IF it's not a boundary condition
         if (local_eqn >= 0)
         {
           residuals[local_eqn] += airy_forcing * test(l) * W;
           // Reduced order biharmonic operator
           for (unsigned k = 0; k < 2; k++)
           {
             residuals[local_eqn] +=
               interpolated_dlaplacian_phidx[k] * dtestdx(l, k) * W;
           }
           // Monge-Ampere part
           residuals[local_eqn] -=
             (interpolated_continuous_d2wdx2 * interpolated_continuous_d2wdy2 -
              interpolated_continuous_d2wdxdy *
                interpolated_continuous_d2wdxdy) *
             test(l) * W;
         }
         // Get the local equation
         local_eqn = nodal_local_eqn(l, laplacian_phi_nodal_index);
         // IF it's not a boundary condition
         if (local_eqn >= 0)
         {
           // The coupled Poisson equations for the biharmonic operator
           residuals[local_eqn] += interpolated_laplacian_phi * test(l) * W;
           for (unsigned k = 0; k < 2; k++)
           {
             residuals[local_eqn] += interpolated_dphidx[k] * dtestdx(l, k) * W;
           }
         }
         // Residuals for the smooth derivatives
         local_eqn = nodal_local_eqn(l, smooth_dwdx_nodal_index);
         if (local_eqn >= 0)
         {
           residuals[local_eqn] +=
             (interpolated_dwdx[0] - interpolated_smooth_dwdx[0]) * test(l) * W;
         }
         local_eqn = nodal_local_eqn(l, smooth_dwdy_nodal_index);
         if (local_eqn >= 0)
         {
           residuals[local_eqn] +=
             (interpolated_dwdx[1] - interpolated_smooth_dwdx[1]) * test(l) * W;
         }
         local_eqn = nodal_local_eqn(l, smooth_dphidx_nodal_index);
         if (local_eqn >= 0)
         {
           residuals[local_eqn] +=
             (interpolated_dphidx[0] - interpolated_smooth_dphidx[0]) * test(l) *
             W;
         }
         local_eqn = nodal_local_eqn(l, smooth_dphidy_nodal_index);
         if (local_eqn >= 0)
         {
           residuals[local_eqn] +=
             (interpolated_dphidx[1] - interpolated_smooth_dphidx[1]) * test(l) *
             W;
         }
       }
     } // End of loop over integration points
     // Finally: My contribution to the volume constraint equation
     // (if any). Note this must call get_bounded_volume since the
     // definition of the bounded volume can be overloaded in derived
     // elements.
     if (Volume_constraint_pressure_external_data_index >= 0)
     {
       local_eqn =
         external_local_eqn(Volume_constraint_pressure_external_data_index, 0);
       if (local_eqn >= 0)
       {
         residuals[local_eqn] += get_bounded_volume();
       }
     }
   }
References dshape_and_dtest_eulerian_at_knot_fvk(), eta(), oomph::GeneralisedElement::external_local_eqn(), get_airy_forcing_fvk(), get_bounded_volume(), get_pressure_fvk(), oomph::FiniteElement::integral_pt(), oomph::FiniteElement::interpolated_x(), J, j, k, Linear_bending_model, oomph::FiniteElement::nnode(), nodal_index_fvk(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::nodal_value(), oomph::Integral::nweight(), oomph::FiniteElement::raw_nodal_position(), oomph::FiniteElement::raw_nodal_value(), Eigen::test, Volume_constraint_pressure_external_data_index, w, oomph::QuadTreeNames::W, and oomph::Integral::weight().
get_airy_forcing_fvk()
virtual void oomph::FoepplvonKarmanEquations::get_airy_forcing_fvk (const unsigned & ipt, const Vector< double > & x, double & airy_forcing) const inline virtual
Get Airy forcing term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the pressure function might be determined by another system of equations.
     {
       // If no pressure function has been set, return zero
       if (Airy_forcing_fct_pt == 0)
       {
         airy_forcing = 0.0;
       }
       else
       {
         // Get pressure strength
         (*Airy_forcing_fct_pt)(x, airy_forcing);
       }
     }
References Airy_forcing_fct_pt, and plotDoE::x.
Referenced by fill_in_contribution_to_residuals().
get_bounded_volume()
virtual double oomph::FoepplvonKarmanEquations::get_bounded_volume () const inline virtual
Return the integral of the displacement over the current element, effectively calculating its contribution to the volume under the membrane. Virtual so it can be overloaded in multi-physics where the volume may incorporate an offset, say.
     {
       // Number of nodes and integration points for the current element
       const unsigned n_node = nnode();
       const unsigned n_intpt = integral_pt()->nweight();
       // Shape functions and their derivatives
       Shape psi(n_node);
       DShape dpsidx(n_node, 2);
       // The nodal index at which the displacement is stored
       const unsigned w_nodal_index = nodal_index_fvk();
       // Initalise the integral variable
       double integral_w = 0;
       // Loop over the integration points
       for (unsigned ipt = 0; ipt < n_intpt; ipt++)
       {
         // Get the integral weight
         double w = integral_pt()->weight(ipt);
         // Get determinant of the Jacobian of the mapping
         double J = dshape_eulerian_at_knot(ipt, psi, dpsidx);
         // Premultiply the weight and Jacobian
         double W = w * J;
         // Initialise storage for the w value and nodal value
         double interpolated_w = 0;
         double w_nodal_value;
         // Loop over the shape functions/nodes
         for (unsigned l = 0; l < n_node; l++)
         {
           // Get the current nodal value
           w_nodal_value = raw_nodal_value(l, w_nodal_index);
           // Add the contribution to interpolated w
           interpolated_w += w_nodal_value * psi(l);
         }
         // Add the contribution from the current integration point
         integral_w += interpolated_w * W;
       }
       // Return the calculated integral
       return integral_w;
     }
References oomph::FiniteElement::dshape_eulerian_at_knot(), oomph::FiniteElement::integral_pt(), J, oomph::FiniteElement::nnode(), nodal_index_fvk(), oomph::Integral::nweight(), oomph::FiniteElement::raw_nodal_value(), w, oomph::QuadTreeNames::W, and oomph::Integral::weight().
Referenced by fill_in_contribution_to_residuals().
get_gradient_of_deflection()
void oomph::FoepplvonKarmanEquations::get_gradient_of_deflection (const Vector< double > & s, Vector< double > & gradient) const inline
Get gradient of deflection: gradient[i] = dw/dx_i.
     {
       // Find out how many nodes there are in the element
       const unsigned n_node = nnode();
       // Get the index at which the unknown is stored
       const unsigned w_nodal_index = nodal_index_fvk(0);
       // Set up memory for the shape and test functions
       Shape psi(n_node);
       DShape dpsidx(n_node, 2);
       // Call the derivatives of the shape and test functions
       dshape_eulerian(s, psi, dpsidx);
       // Initialise to zero
       for (unsigned j = 0; j < 2; j++)
       {
         gradient[j] = 0.0;
       }
       // Loop over nodes
       for (unsigned l = 0; l < n_node; l++)
       {
         // Loop over derivative directions
         for (unsigned j = 0; j < 2; j++)
         {
           gradient[j] += this->nodal_value(l, w_nodal_index) * dpsidx(l, j);
         }
       }
     }
References oomph::FiniteElement::dshape_eulerian(), j, oomph::FiniteElement::nnode(), nodal_index_fvk(), oomph::FiniteElement::nodal_value(), and s.
Referenced by oomph::TFoepplvonKarmanElement< NNODE_1D >::get_Z2_flux().
get_pressure_fvk()
virtual void oomph::FoepplvonKarmanEquations::get_pressure_fvk (const unsigned & ipt, const Vector< double > & x, double & pressure) const inline virtual
Get pressure term at (Eulerian) position x. This function is virtual to allow overloading in multi-physics problems where the strength of the pressure function might be determined by another system of equations.
     {
       // If no pressure function has been set, return zero
       if (Pressure_fct_pt == 0)
       {
         pressure = 0.0;
       }
       else
       {
         // Get pressure strength
         (*Pressure_fct_pt)(x, pressure);
       }
     }
References Pressure_fct_pt, and plotDoE::x.
Referenced by fill_in_contribution_to_residuals().
interpolated_stress()
void oomph::FoepplvonKarmanEquations::interpolated_stress (const Vector< double > & s, double & sigma_xx, double & sigma_yy, double & sigma_xy)
Compute in-plane stresses.
   {
     // No in plane stresses if linear bending
     if (Linear_bending_model)
     {
       sigma_xx = 0.0;
       sigma_yy = 0.0;
       sigma_xy = 0.0;
       return;
     }
     // Get shape fcts and derivs
     unsigned n_dim = this->dim();
     unsigned n_node = this->nnode();
     Shape psi(n_node);
     DShape dpsidx(n_node, n_dim);
     dshape_eulerian(s, psi, dpsidx);
     double interpolated_continuous_d2phidx2 = 0;
     double interpolated_continuous_d2phidy2 = 0;
     double interpolated_continuous_d2phidxdy = 0;
     const unsigned smooth_dphidx_nodal_index = nodal_index_fvk(6);
     const unsigned smooth_dphidy_nodal_index = nodal_index_fvk(7);
     // Loop over nodes
     for (unsigned l = 0; l < n_node; l++)
     {
       interpolated_continuous_d2phidx2 +=
         raw_nodal_value(l, smooth_dphidx_nodal_index) * dpsidx(l, 0);
       interpolated_continuous_d2phidy2 +=
         raw_nodal_value(l, smooth_dphidy_nodal_index) * dpsidx(l, 1);
       interpolated_continuous_d2phidxdy +=
         0.5 * (raw_nodal_value(l, smooth_dphidx_nodal_index) * dpsidx(l, 1) +
                raw_nodal_value(l, smooth_dphidy_nodal_index) * dpsidx(l, 0));
     }
     sigma_xx = interpolated_continuous_d2phidy2;
     sigma_yy = interpolated_continuous_d2phidx2;
     sigma_xy = -interpolated_continuous_d2phidxdy;
   }
References oomph::FiniteElement::dim(), oomph::FiniteElement::dshape_eulerian(), Linear_bending_model, oomph::FiniteElement::nnode(), nodal_index_fvk(), oomph::FiniteElement::raw_nodal_value(), and s.
interpolated_w_fvk()
double oomph::FoepplvonKarmanEquations::interpolated_w_fvk (const Vector< double > & s, unsigned index = 0) const inline
Return FE representation of function value w_fvk(s) at local coordinate s (by default - if index > 0, returns FE representation of valued stored at index^th nodal index
     {
       // Find number of nodes
       const unsigned n_node = nnode();
       // Get the index at which the poisson unknown is stored
       const unsigned w_nodal_index = nodal_index_fvk(index);
       // Local shape function
       Shape psi(n_node);
       // Find values of shape function
       shape(s, psi);
       // Initialise value of u
       double interpolated_w = 0.0;
       // Loop over the local nodes and sum
       for (unsigned l = 0; l < n_node; l++)
       {
         interpolated_w += this->nodal_value(l, w_nodal_index) * psi[l];
       }
       return (interpolated_w);
     }
References oomph::FiniteElement::nnode(), nodal_index_fvk(), oomph::FiniteElement::nodal_value(), s, and oomph::FiniteElement::shape().
Referenced by compute_error(), and output().
nodal_index_fvk()
virtual unsigned oomph::FoepplvonKarmanEquations::nodal_index_fvk (const unsigned & i = 0) const inline virtual
Return the index at which the i-th unknown value is stored. The default value, i, is appropriate for single-physics problems. By default, these are: 0: w 1: laplacian w 2: phi 3: laplacian phi 4-8: smooth first derivatives In derived multi-physics elements, this function should be overloaded to reflect the chosen storage scheme. Note that these equations require that the unknown is always stored at the same index at each node.
     {
       return i;
     }
References i.
Referenced by fill_in_contribution_to_residuals(), get_bounded_volume(), get_gradient_of_deflection(), interpolated_stress(), interpolated_w_fvk(), and use_linear_bending_model().
operator=()
void oomph::FoepplvonKarmanEquations::operator= (const FoepplvonKarmanEquations &) delete
Broken assignment operator.
output() [1/4]
void oomph::FoepplvonKarmanEquations::output (FILE * file_pt) inline virtual
C_style output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::TFoepplvonKarmanElement< NNODE_1D >, and oomph::QFoepplvonKarmanElement< NNODE_1D >.
     {
       const unsigned n_plot = 5;
       output(file_pt, n_plot);
     }
References output().
output() [2/4]
void oomph::FoepplvonKarmanEquations::output (FILE * file_pt, const unsigned & nplot) virtual
C-style output FE representation of soln: x,y,w at n_plot^DIM plot points
C-style output function:
x,y,w
nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::TFoepplvonKarmanElement< NNODE_1D >, and oomph::QFoepplvonKarmanElement< NNODE_1D >.
   {
     // Vector of local coordinates
     Vector<double> s(2);
     // Tecplot header info
     fprintf(file_pt, "%s", tecplot_zone_string(nplot).c_str());
     // Loop over plot points
     unsigned num_plot_points = nplot_points(nplot);
     for (unsigned iplot = 0; iplot < num_plot_points; iplot++)
     {
       // Get local coordinates of plot point
       get_s_plot(iplot, nplot, s);
       for (unsigned i = 0; i < 2; i++)
       {
         fprintf(file_pt, "%g ", interpolated_x(s, i));
       }
       fprintf(file_pt, "%g \n", interpolated_w_fvk(s));
     }
     // Write tecplot footer (e.g. FE connectivity lists)
     write_tecplot_zone_footer(file_pt, nplot);
   }
References oomph::FiniteElement::get_s_plot(), i, interpolated_w_fvk(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output() [3/4]
void oomph::FoepplvonKarmanEquations::output (std::ostream & outfile) inline virtual
Output with default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::TFoepplvonKarmanElement< NNODE_1D >, and oomph::QFoepplvonKarmanElement< NNODE_1D >.
     {
       const unsigned n_plot = 5;
       output(outfile, n_plot);
     }
Referenced by output(), oomph::QFoepplvonKarmanElement< NNODE_1D >::output(), and oomph::TFoepplvonKarmanElement< NNODE_1D >::output().
output() [4/4]
void oomph::FoepplvonKarmanEquations::output (std::ostream & outfile, const unsigned & nplot) virtual
Output FE representation of soln: x,y,w at n_plot^DIM plot points
Output function:
x,y,w
nplot points in each coordinate direction
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::TFoepplvonKarmanElement< NNODE_1D >, and oomph::QFoepplvonKarmanElement< NNODE_1D >.
   {
     // Vector of local coordinates
     Vector<double> s(2);
     // Tecplot header info
     outfile << tecplot_zone_string(nplot);
     // Loop over plot points
     unsigned num_plot_points = nplot_points(nplot);
     for (unsigned iplot = 0; iplot < num_plot_points; iplot++)
     {
       // Get local coordinates of plot point
       get_s_plot(iplot, nplot, s);
       for (unsigned i = 0; i < 2; i++)
       {
         outfile << interpolated_x(s, i) << " ";
       }
       outfile << interpolated_w_fvk(s) << std::endl;
     }
     // Write tecplot footer (e.g. FE connectivity lists)
     write_tecplot_zone_footer(outfile, nplot);
   }
References oomph::FiniteElement::get_s_plot(), i, interpolated_w_fvk(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output_fct() [1/2]
virtual void oomph::FoepplvonKarmanEquations::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) inline virtual
Output exact soln: x,y,w_exact at n_plot^DIM plot points (dummy time-dependent version to keep intel compiler happy)
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::TFoepplvonKarmanElement< NNODE_1D >, and oomph::QFoepplvonKarmanElement< NNODE_1D >.
     {
       throw OomphLibError(
         "There is no time-dependent output_fct() for Foeppl von Karman"
         "elements ",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
output_fct() [2/2]
void oomph::FoepplvonKarmanEquations::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) virtual
Output exact soln: x,y,w_exact at n_plot^DIM plot points.
Output exact solution
Solution is provided via function pointer. Plot at a given number of plot points.
x,y,w_exact
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::TFoepplvonKarmanElement< NNODE_1D >, and oomph::QFoepplvonKarmanElement< NNODE_1D >.
   {
     // Vector of local coordinates
     Vector<double> s(2);
     // Vector for coordintes
     Vector<double> x(2);
     // Tecplot header info
     outfile << tecplot_zone_string(nplot);
     // Exact solution Vector (here a scalar)
     // Vector<double> exact_soln(1);
     Vector<double> exact_soln(2);
     // Loop over plot points
     unsigned num_plot_points = nplot_points(nplot);
     for (unsigned iplot = 0; iplot < num_plot_points; iplot++)
     {
       // Get local coordinates of plot point
       get_s_plot(iplot, nplot, s);
       // Get x position as Vector
       interpolated_x(s, x);
       // Get exact solution at this point
       (*exact_soln_pt)(x, exact_soln);
       // Output x,y,w_exact
       for (unsigned i = 0; i < 2; i++)
       {
         outfile << x[i] << " ";
       }
       outfile << exact_soln[0] << std::endl;
     }
     // Write tecplot footer (e.g. FE connectivity lists)
     write_tecplot_zone_footer(outfile, nplot);
   }
References ProblemParameters::exact_soln(), oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), oomph::FiniteElement::write_tecplot_zone_footer(), and plotDoE::x.
Referenced by oomph::QFoepplvonKarmanElement< NNODE_1D >::output_fct(), and oomph::TFoepplvonKarmanElement< NNODE_1D >::output_fct().
pressure_fct_pt() [1/2]
FoepplvonKarmanPressureFctPt& oomph::FoepplvonKarmanEquations::pressure_fct_pt () inline
Access function: Pointer to pressure function.
     {
       return Pressure_fct_pt;
     }
References Pressure_fct_pt.
pressure_fct_pt() [2/2]
FoepplvonKarmanPressureFctPt oomph::FoepplvonKarmanEquations::pressure_fct_pt () const inline
Access function: Pointer to pressure function. Const version.
     {
       return Pressure_fct_pt;
     }
References Pressure_fct_pt.
self_test()
unsigned oomph::FoepplvonKarmanEquations::self_test () virtual
Self-test: Return 0 for OK.
Reimplemented from oomph::FiniteElement.
   {
     bool passed = true;
     // Check lower-level stuff
     if (FiniteElement::self_test() != 0)
     {
       passed = false;
     }
     // Return verdict
     if (passed)
     {
       return 0;
     }
     else
     {
       return 1;
     }
   }
References oomph::FiniteElement::self_test().
set_volume_constraint_pressure_data_as_external_data()
void oomph::FoepplvonKarmanEquations::set_volume_constraint_pressure_data_as_external_data (Data * data_pt) inline
Set Data value containing a single value which represents the volume control pressure as external data for this element. Only used for volume controlled problems in conjunction with FoepplvonKarmanVolumeConstraintElement.
     {
 #ifdef PARANOID
       if (data_pt->nvalue() != 1)
       {
         throw OomphLibError("Data object that contains volume control pressure "
                             "should only contain a single value. ",
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // Add as external data and remember the index in the element's storage
       // scheme
       Volume_constraint_pressure_external_data_index =
         add_external_data(data_pt);
     }
References oomph::GeneralisedElement::add_external_data(), oomph::Data::nvalue(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and Volume_constraint_pressure_external_data_index.
use_linear_bending_model()
void oomph::FoepplvonKarmanEquations::use_linear_bending_model () inline
Sets a flag to signify that we are solving the linear, pure bending equations, and pin all the nodal values that will not be used in this case
     {
       // Set the boolean flag
       Linear_bending_model = true;
       // Get the index of the first FvK nodal value
       unsigned first_fvk_nodal_index = nodal_index_fvk();
       // Get the total number of FvK nodal values (assuming they are stored
       // contiguously) at node 0 (it's the same at all nodes anyway)
       unsigned total_fvk_nodal_indicies = 8;
       // Get the number of nodes in this element
       unsigned n_node = nnode();
       // Loop over the appropriate nodal indices
       for (unsigned index = first_fvk_nodal_index + 2;
            index < first_fvk_nodal_index + total_fvk_nodal_indicies;
            index++)
       {
         // Loop over the nodes in the element
         for (unsigned inod = 0; inod < n_node; inod++)
         {
           // Pin the nodal value at the current index
           node_pt(inod)->pin(index);
         }
       }
     }
References Linear_bending_model, oomph::FiniteElement::nnode(), nodal_index_fvk(), oomph::FiniteElement::node_pt(), and oomph::Data::pin().
Member Data Documentation
Airy_forcing_fct_pt
FoepplvonKarmanPressureFctPt oomph::FoepplvonKarmanEquations::Airy_forcing_fct_pt protected
Referenced by airy_forcing_fct_pt(), and get_airy_forcing_fvk().
Default_Physical_Constant_Value
double oomph::FoepplvonKarmanEquations::Default_Physical_Constant_Value = 0.0 static private
Default value for physical constants.
Default value physical constants.
Referenced by FoepplvonKarmanEquations().
Eta_pt
double* oomph::FoepplvonKarmanEquations::Eta_pt protected
Pointer to global eta.
Referenced by eta(), eta_pt(), and FoepplvonKarmanEquations().
Linear_bending_model
bool oomph::FoepplvonKarmanEquations::Linear_bending_model private
Flag which stores whether we are using a linear, pure bending model instead of the full non-linear Foeppl-von Karman
Referenced by fill_in_contribution_to_residuals(), FoepplvonKarmanEquations(), interpolated_stress(), and use_linear_bending_model().
Pressure_fct_pt
FoepplvonKarmanPressureFctPt oomph::FoepplvonKarmanEquations::Pressure_fct_pt protected
Pointer to pressure function:
Referenced by get_pressure_fvk(), and pressure_fct_pt().
Volume_constraint_pressure_external_data_index
int oomph::FoepplvonKarmanEquations::Volume_constraint_pressure_external_data_index private
Index of the external Data object that represents the volume constraint pressure (initialised to -1 indicating no such constraint) Gets overwritten when calling set_volume_constraint_pressure_data_as_external_data(...)
Referenced by fill_in_contribution_to_residuals(), FoepplvonKarmanEquations(), and set_volume_constraint_pressure_data_as_external_data().
The documentation for this class was generated from the following files:
foeppl_von_karman_elements.h
foeppl_von_karman_elements.cc