MercuryDPM: vectorization_logic< Scalar, Enable > Struct Template Reference
vectorization_logic< Scalar, Enable > Struct Template Reference
Public Types
enum { PacketSize = internal::unpacket_traits<PacketType>::size , HalfPacketSize = internal::unpacket_traits<HalfPacketType>::size }
typedef internal::packet_traits< Scalar > PacketTraits
typedef internal::packet_traits< Scalar >::type PacketType
typedef internal::unpacket_traits< PacketType >::half HalfPacketType
Static Public Member Functions
static void run ()
Member Typedef Documentation
HalfPacketType
template<typename Scalar , bool Enable = internal::packet_traits<Scalar>::Vectorizable> typedef internal::unpacket_traits<PacketType>::half vectorization_logic< Scalar, Enable >::HalfPacketType
PacketTraits
template<typename Scalar , bool Enable = internal::packet_traits<Scalar>::Vectorizable> typedef internal::packet_traits<Scalar> vectorization_logic< Scalar, Enable >::PacketTraits
PacketType
template<typename Scalar , bool Enable = internal::packet_traits<Scalar>::Vectorizable> typedef internal::packet_traits<Scalar>::type vectorization_logic< Scalar, Enable >::PacketType
Member Enumeration Documentation
anonymous enum
template<typename Scalar , bool Enable = internal::packet_traits<Scalar>::Vectorizable> anonymous enum
Enumerator
PacketSize
HalfPacketSize
        {
     PacketSize = internal::unpacket_traits<PacketType>::size,
     HalfPacketSize = internal::unpacket_traits<HalfPacketType>::size
   };
Member Function Documentation
run()
template<typename Scalar , bool Enable = internal::packet_traits<Scalar>::Vectorizable> static void vectorization_logic< Scalar, Enable >::run () inline static
                     {
     typedef Matrix<Scalar, PacketSize, 1> Vector1;
     typedef Matrix<Scalar, Dynamic, 1> VectorX;
     typedef Matrix<Scalar, Dynamic, Dynamic> MatrixXX;
     typedef Matrix<Scalar, PacketSize, PacketSize> Matrix11;
     typedef Matrix<Scalar, (Matrix11::Flags & RowMajorBit) ? 8 : 2 * PacketSize,
                    (Matrix11::Flags & RowMajorBit) ? 2 * PacketSize : 8>
         Matrix22;
     typedef Matrix<Scalar, (Matrix11::Flags & RowMajorBit) ? 16 : 4 * PacketSize,
                    (Matrix11::Flags & RowMajorBit) ? 4 * PacketSize : 16>
         Matrix44;
     typedef Matrix<Scalar, (Matrix11::Flags & RowMajorBit) ? 16 : 4 * PacketSize,
                    (Matrix11::Flags & RowMajorBit) ? 4 * PacketSize : 16,
                    DontAlign | EIGEN_DEFAULT_MATRIX_STORAGE_ORDER_OPTION>
         Matrix44u;
     typedef Matrix<Scalar, 4 * PacketSize, 4 * PacketSize, ColMajor> Matrix44c;
     typedef Matrix<Scalar, 4 * PacketSize, 4 * PacketSize, RowMajor> Matrix44r;
     typedef Matrix<Scalar,
                    (PacketSize == 16  ? 8
                     : PacketSize == 8 ? 4
                     : PacketSize == 4 ? 2
                     : PacketSize == 2 ? 1
                                       : /*PacketSize==1 ?*/ 1),
                    (PacketSize == 16  ? 2
                     : PacketSize == 8 ? 2
                     : PacketSize == 4 ? 2
                     : PacketSize == 2 ? 2
                                       : /*PacketSize==1 ?*/ 1)>
         Matrix1;
     typedef Matrix<Scalar,
                    (PacketSize == 16  ? 8
                     : PacketSize == 8 ? 4
                     : PacketSize == 4 ? 2
                     : PacketSize == 2 ? 1
                                       : /*PacketSize==1 ?*/ 1),
                    (PacketSize == 16  ? 2
                     : PacketSize == 8 ? 2
                     : PacketSize == 4 ? 2
                     : PacketSize == 2 ? 2
                                       : /*PacketSize==1 ?*/ 1),
                    DontAlign | ((Matrix1::Flags & RowMajorBit) ? RowMajor : ColMajor)>
         Matrix1u;
     // this type is made such that it can only be vectorized when viewed as a linear 1D vector
     typedef Matrix<Scalar,
                    (PacketSize == 16  ? 4
                     : PacketSize == 8 ? 4
                     : PacketSize == 4 ? 6
                     : PacketSize == 2 ? ((Matrix11::Flags & RowMajorBit) ? 2 : 3)
                                       : /*PacketSize==1 ?*/ 1),
                    (PacketSize == 16  ? 12
                     : PacketSize == 8 ? 6
                     : PacketSize == 4 ? 2
                     : PacketSize == 2 ? ((Matrix11::Flags & RowMajorBit) ? 3 : 2)
                                       : /*PacketSize==1 ?*/ 3)>
         Matrix3;
 #if !EIGEN_GCC_AND_ARCH_DOESNT_WANT_STACK_ALIGNMENT
     VERIFY(test_assign(Vector1(), Vector1(), InnerVectorizedTraversal, CompleteUnrolling));
     VERIFY(test_assign(Vector1(), Vector1() + Vector1(), InnerVectorizedTraversal, CompleteUnrolling));
     VERIFY(test_assign(Vector1(), Vector1().cwiseProduct(Vector1()), InnerVectorizedTraversal, CompleteUnrolling));
     VERIFY(test_assign(Vector1(), Vector1().template cast<Scalar>(), InnerVectorizedTraversal, CompleteUnrolling));
     VERIFY(test_assign(Matrix44(), Matrix44() + Matrix44(), InnerVectorizedTraversal, InnerUnrolling));
     VERIFY(test_assign(Matrix44u(), Matrix44() + Matrix44(),
                        EIGEN_UNALIGNED_VECTORIZE ? InnerVectorizedTraversal : LinearTraversal,
                        EIGEN_UNALIGNED_VECTORIZE ? InnerUnrolling : NoUnrolling));
     VERIFY(test_assign(Matrix1(), Matrix1() + Matrix1(),
                        (int(Matrix1::InnerSizeAtCompileTime) % int(PacketSize)) == 0 ? InnerVectorizedTraversal
                                                                                      : LinearVectorizedTraversal,
                        CompleteUnrolling));
     VERIFY(test_assign(Matrix1u(), Matrix1() + Matrix1(),
                        EIGEN_UNALIGNED_VECTORIZE
                            ? ((int(Matrix1::InnerSizeAtCompileTime) % int(PacketSize)) == 0 ? InnerVectorizedTraversal
                                                                                             : LinearVectorizedTraversal)
                            : LinearTraversal,
                        CompleteUnrolling));
     VERIFY(test_assign(Matrix44c().col(1), Matrix44c().col(2) + Matrix44c().col(3), InnerVectorizedTraversal,
                        CompleteUnrolling));
     VERIFY(test_assign(Matrix44r().row(2), Matrix44r().row(1) + Matrix44r().row(1), InnerVectorizedTraversal,
                        CompleteUnrolling));
     if (PacketSize > 1) {
       typedef Matrix<Scalar, 3, 3, ColMajor> Matrix33c;
       typedef Matrix<Scalar, 3, 1, ColMajor> Vector3;
       VERIFY(
           test_assign(Matrix33c().row(2), Matrix33c().row(1) + Matrix33c().row(1), LinearTraversal, CompleteUnrolling));
       // Vectorization depends on too many factors - ignore.
       VERIFY(test_assign(Vector3(), Vector3() + Vector3(), -1, CompleteUnrolling));
       VERIFY(test_assign(Matrix3(), Matrix3().cwiseProduct(Matrix3()), LinearVectorizedTraversal, CompleteUnrolling));
       // Vectorization depends on too many factors - ignore.
       VERIFY(
           test_assign(Matrix<Scalar, 17, 17>(), Matrix<Scalar, 17, 17>() + Matrix<Scalar, 17, 17>(), -1, NoUnrolling));
       VERIFY(test_assign(Matrix11(), Matrix11() + Matrix11(), InnerVectorizedTraversal, CompleteUnrolling));
       VERIFY(test_assign(Matrix11(),
                          Matrix<Scalar, 21, 21>().template block<PacketSize, PacketSize>(2, 3) +
                              Matrix<Scalar, 21, 21>().template block<PacketSize, PacketSize>(3, 2),
                          (EIGEN_UNALIGNED_VECTORIZE) ? InnerVectorizedTraversal : DefaultTraversal,
                          CompleteUnrolling | InnerUnrolling));
       VERIFY(test_assign(Vector1(), Matrix11() * Vector1(), InnerVectorizedTraversal, CompleteUnrolling));
       VERIFY(test_assign(Matrix11(), Matrix11().lazyProduct(Matrix11()), InnerVectorizedTraversal,
                          InnerUnrolling + CompleteUnrolling));
     }
     VERIFY(test_redux(Vector1(), LinearVectorizedTraversal, CompleteUnrolling));
     VERIFY(test_redux(Vector1().array() * Vector1().array(), LinearVectorizedTraversal, CompleteUnrolling));
     VERIFY(test_redux((Vector1().array() * Vector1().array()).col(0), LinearVectorizedTraversal, CompleteUnrolling));
     VERIFY(test_redux(Matrix<Scalar, PacketSize, 3>(), LinearVectorizedTraversal, CompleteUnrolling));
     VERIFY(test_redux(Matrix3(), LinearVectorizedTraversal, CompleteUnrolling));
     VERIFY(test_redux(Matrix44(), LinearVectorizedTraversal, NoUnrolling));
     if (PacketSize > 1) {
       VERIFY(test_redux(Matrix44().template block < (Matrix1::Flags & RowMajorBit) ? 4 : PacketSize,
                         (Matrix1::Flags & RowMajorBit) ? PacketSize : 4 > (1, 2), SliceVectorizedTraversal,
                         CompleteUnrolling));
       VERIFY(test_redux(Matrix44().template block < (Matrix1::Flags & RowMajorBit) ? 2 : PacketSize,
                         (Matrix1::Flags & RowMajorBit) ? PacketSize : 2 > (1, 2), DefaultTraversal, CompleteUnrolling));
     }
     VERIFY(
         test_redux(Matrix44c().template block<2 * PacketSize, 1>(1, 2), LinearVectorizedTraversal, CompleteUnrolling));
     VERIFY(
         test_redux(Matrix44r().template block<1, 2 * PacketSize>(2, 1), LinearVectorizedTraversal, CompleteUnrolling));
     VERIFY((test_assign<Map<Matrix22, AlignedMax, OuterStride<3 * PacketSize> >, Matrix22>(InnerVectorizedTraversal,
                                                                                            CompleteUnrolling)));
     VERIFY((test_assign<
             Map<Matrix<Scalar, internal::plain_enum_max(2, PacketSize), internal::plain_enum_max(2, PacketSize)>,
                 AlignedMax, InnerStride<3 * PacketSize> >,
             Matrix<Scalar, internal::plain_enum_max(2, PacketSize), internal::plain_enum_max(2, PacketSize)> >(
         DefaultTraversal, PacketSize >= 8 ? InnerUnrolling : CompleteUnrolling)));
     VERIFY((test_assign(Matrix11(),
                         Matrix<Scalar, PacketSize, internal::plain_enum_min(2, PacketSize)>() *
                             Matrix<Scalar, internal::plain_enum_min(2, PacketSize), PacketSize>(),
                         InnerVectorizedTraversal, CompleteUnrolling)));
 #endif
     VERIFY(test_assign(MatrixXX(10, 10), MatrixXX(20, 20).block(10, 10, 2, 3), SliceVectorizedTraversal, NoUnrolling));
     VERIFY(test_redux(VectorX(10), LinearVectorizedTraversal, NoUnrolling));
   }
References Eigen::AlignedMax, block(), col(), Eigen::ColMajor, Eigen::CompleteUnrolling, Eigen::DefaultTraversal, Eigen::DontAlign, EIGEN_DEFAULT_MATRIX_STORAGE_ORDER_OPTION, EIGEN_UNALIGNED_VECTORIZE, Eigen::InnerUnrolling, Eigen::InnerVectorizedTraversal, Eigen::LinearTraversal, Eigen::LinearVectorizedTraversal, Eigen::NoUnrolling, vectorization_logic< Scalar, Enable >::PacketSize, Eigen::internal::plain_enum_max(), Eigen::internal::plain_enum_min(), row(), Eigen::RowMajor, Eigen::RowMajorBit, Eigen::SliceVectorizedTraversal, test_assign(), test_redux(), and VERIFY.
The documentation for this struct was generated from the following file:
vectorization_logic.cpp