MercuryDPM: MatrixBase_row.cpp File Reference
MatrixBase_row.cpp File Reference
Functions
m row (1)
Variables
Matrix3d m = Matrix3d::Identity()
Function Documentation
row()
m row (1)
Referenced by Eigen::MatrixBase< Derived >::applyHouseholderOnTheLeft(), Eigen::MatrixBase< Derived >::applyOnTheLeft(), Eigen::CompleteOrthogonalDecomposition< MatrixType_, PermutationIndex_ >::applyZAdjointOnTheLeftInPlace(), Eigen::CompleteOrthogonalDecomposition< MatrixType_, PermutationIndex_ >::applyZOnTheLeftInPlace(), Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::assignCoeff(), Eigen::internal::triangular_dense_assignment_kernel< UpLo, SelfAdjoint, SetOpposite, DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::assignCoeff(), Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::assignCoeffByOuterInner(), Eigen::internal::triangular_dense_assignment_kernel< UpLo, Mode, SetOpposite, DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::assignOppositeCoeff(), Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::assignPacket(), Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >::assignPacket(), Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, Functor, Version >::assignPacketByOuterInner(), Eigen::internal::generic_dense_assignment_kernel< DstEvaluatorTypeT, SrcEvaluatorTypeT, swap_assign_op< typename DstEvaluatorTypeT::Scalar >, Specialized >::assignPacketByOuterInner(), Eigen::internal::bload(), block(), Eigen::internal::BlockedInPlaceTranspose(), Eigen::internal::bstore(), Eigen::internal::calcColLoops(), Eigen::internal::calcVecColLoops(), Eigen::internal::calcVecLoops(), Eigen::internal::calcVSXColLoops(), calcVSXVecColLoops(), calcVSXVecLoops(), Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::check_array_bounds(), Eigen::TriangularBase< Derived >::check_coordinates(), check_indexed_view(), choose(), Eigen::BlockSparseMatrixView< BlockSparseMatrixT >::coeff(), Eigen::internal::evaluator< PlainObjectBase< Derived > >::coeff(), Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::coeff(), Eigen::internal::unary_evaluator< CwiseUnaryOp< UnaryOp, ArgType >, IndexBased >::coeff(), Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::coeff(), Eigen::internal::ternary_evaluator< CwiseTernaryOp< TernaryOp, Arg1, Arg2, Arg3 >, IndexBased, IndexBased >::coeff(), Eigen::internal::binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, IndexBased, IndexBased >::coeff(), Eigen::internal::unary_evaluator< CwiseUnaryView< UnaryOp, ArgType, StrideType >, IndexBased >::coeff(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::coeff(), Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::coeff(), Eigen::internal::evaluator< Select< ConditionMatrixType, ThenMatrixType, ElseMatrixType > >::coeff(), Eigen::internal::unary_evaluator< Replicate< ArgType, RowFactor, ColFactor > >::coeff(), Eigen::internal::evaluator_wrapper_base< XprType >::coeff(), Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::coeff(), Eigen::DenseCoeffsBase< Derived, ReadOnlyAccessors >::coeff(), Eigen::DiagonalBase< Derived >::coeff(), Eigen::ForceAlignedAccess< ExpressionType >::coeff(), Eigen::internal::unary_evaluator< IndexedView< ArgType, RowIndices, ColIndices >, IndexBased >::coeff(), Eigen::ProductImpl< Lhs, Rhs, Option, Dense >::coeff(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::coeff(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DiagonalShape, DenseShape >::coeff(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DenseShape, DiagonalShape >::coeff(), Eigen::SelfAdjointView< MatrixType_, UpLo >::coeff(), Eigen::TriangularBase< Derived >::coeff(), Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense >::coeff(), Eigen::internal::visitor_evaluator< XprType >::coeff(), Eigen::BlockImpl< XprType, BlockRows, BlockCols, true, Sparse >::coeff(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::coeff(), Eigen::BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Sparse >::coeff(), Eigen::internal::evaluator< SparseCompressedBase< Derived > >::coeff(), Eigen::SparseMapBase< Derived, ReadOnlyAccessors >::coeff(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::coeff(), Eigen::SparseVector< Scalar_, Options_, StorageIndex_ >::coeff(), Eigen::internal::unary_evaluator< CoherentPadOp< ArgType, SizeAtCompileTime > >::coeff(), Eigen::KroneckerProductBase< Derived >::coeff(), Eigen::internal::evaluator< Diagonal< ArgType, DiagIndex > >::coeff(), Eigen::Diagonal< MatrixType, DiagIndex_ >::coeff(), Eigen::internal::evaluator< CwiseNullaryOp< NullaryOp, PlainObjectType > >::coeff(), Eigen::internal::evaluator< PlainObjectBase< Derived > >::coeffRef(), Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::coeffRef(), Eigen::internal::unary_evaluator< CwiseUnaryView< UnaryOp, ArgType, StrideType >, IndexBased >::coeffRef(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::coeffRef(), Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::coeffRef(), Eigen::internal::evaluator_wrapper_base< XprType >::coeffRef(), Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::coeffRef(), Eigen::internal::CwiseUnaryViewImpl< ViewOp, MatrixType, StrideType, Dense, true >::coeffRef(), Eigen::DenseCoeffsBase< Derived, WriteAccessors >::coeffRef(), Eigen::ForceAlignedAccess< ExpressionType >::coeffRef(), Eigen::internal::unary_evaluator< IndexedView< ArgType, RowIndices, ColIndices >, IndexBased >::coeffRef(), Eigen::MapBase< Derived, WriteAccessors >::coeffRef(), Eigen::SelfAdjointView< MatrixType_, UpLo >::coeffRef(), Eigen::TriangularBase< Derived >::coeffRef(), Eigen::TriangularViewImpl< MatrixType_, Mode_, Dense >::coeffRef(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::coeffRef(), Eigen::BlockImpl< XprType, BlockRows, BlockCols, InnerPanel, Sparse >::coeffRef(), Eigen::internal::evaluator< SparseCompressedBase< Derived > >::coeffRef(), Eigen::SparseMapBase< Derived, WriteAccessors >::coeffRef(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::coeffRef(), Eigen::SparseVector< Scalar_, Options_, StorageIndex_ >::coeffRef(), Eigen::BlockSparseMatrixView< BlockSparseMatrixT >::coeffRef(), Eigen::internal::CwiseUnaryViewImpl< ViewOp, MatrixType, StrideType, Dense, false >::coeffRef(), Eigen::internal::evaluator< Diagonal< ArgType, DiagIndex > >::coeffRef(), Eigen::Diagonal< MatrixType, DiagIndex_ >::coeffRef(), Eigen::internal::unary_evaluator< Transpose< ArgType >, IteratorBased >::InnerIterator::col(), Eigen::internal::coletree(), Eigen::internal::colVecColLoopBody(), Eigen::internal::colVecColLoopBodyExtra(), Eigen::internal::colVecColLoopBodyExtraN(), Eigen::internal::colVecLoopBody(), Eigen::internal::colVecLoopBodyExtra(), Eigen::internal::colVecLoopBodyExtraN(), Eigen::internal::colVSXLoops(), colVSXVecColLoopBody(), colVSXVecColLoopBodyExtra(), colVSXVecColLoopBodyExtraN(), colVSXVecLoopBody(), colVSXVecLoopBodyExtra(), colVSXVecLoopBodyExtraN(), Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::computeIndex(), Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::computeIndexPair(), Eigen::SparseInverse< Scalar >::computeInverse(), Eigen::internal::convertArrayF32toBF16Col(), Eigen::internal::convertArrayF32toBF16ColVSX(), coo_tocsr(), Eigen::TriangularBase< Derived >::copyCoeff(), oomph::TrilinosEpetraHelpers::create_distributed_epetra_matrix(), oomph::TrilinosEpetraHelpers::create_distributed_epetra_matrix_for_aztecoo(), sparseGaussianTest< Scalar >::df(), Eigen::internal::evaluator< SparseCompressedBase< Derived > >::find(), internal::Colamd::find_ordering(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::findOrInsertCoeff(), Eigen::internal::gemm_cols(), Eigen::internal::gemm_complex_cols(), Eigen::internal::gemm_unrolled_complex_row_iteration(), Eigen::internal::gemm_unrolled_row_iteration(), Eigen::internal::gemmbfloat16(), Eigen::internal::gemmMMA_cols(), Eigen::internal::gemmMMA_complex_cols(), Eigen::internal::gemmMMAbfloat16(), oomph::SumOfMatrices::get_as_indices(), BinArray::get_neighbouring_bins_helper(), hessenberg(), internal::Colamd::init_rows_cols(), internal::Colamd::init_scoring(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insert(), Eigen::SparseVector< Scalar_, Options_, StorageIndex_ >::insert(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertBack(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertBackUncompressed(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertCompressed(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertUncompressed(), oomph::BlockPreconditioner< MATRIX >::internal_get_block(), Eigen::SplineFitting< SplineType >::InterpolateWithDerivatives(), LoadIProfiles(), Eigen::loadMarketDense(), Eigen::DenseBase< Derived >::maxCoeff(), Eigen::DenseBase< Derived >::minCoeff(), oomph::CCDoubleMatrix::multiply(), oomph::TrilinosEpetraHelpers::multiply(), oomph::CRDoubleMatrix::multiply(), Eigen::IncompleteLUT< Scalar_, StorageIndex_ >::keep_diag::operator()(), Eigen::SimplicialCholeskyBase< Derived >::keep_diag::operator()(), circulant_functor< ArgType >::operator()(), indexing_functor< ArgType, RowIndexType, ColIndexType >::operator()(), Eigen::internal::SimpleTensorContractionMapper< Scalar, Index, side, Tensor, nocontract_t, contract_t, packet_size, inner_dim_contiguous, Alignment, MakePointer_ >::operator()(), Eigen::DenseCoeffsBase< Derived, WriteAccessors >::operator()(), Eigen::RandomSetter< SparseMatrixType, MapTraits, OuterPacketBits >::operator()(), Eigen::DenseCoeffsBase< Derived, ReadOnlyAccessors >::operator()(), Eigen::TriangularBase< Derived >::operator()(), Eigen::Transform< Scalar_, Dim_, Mode_, Options_ >::operator()(), Eigen::internal::companion< Scalar_, Deg_ >::operator()(), Eigen::internal::gemm_functor< Scalar, Index, Gemm, Lhs, Rhs, Dest, BlockingType >::operator()(), Eigen::internal::scalar_identity_op< Scalar >::operator()(), NurbsUtils::array2< T >::operator()(), Eigen::internal::evaluator< PlainObjectBase< Derived > >::packet(), Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::packet(), Eigen::internal::unary_evaluator< CwiseUnaryOp< UnaryOp, ArgType >, IndexBased >::packet(), Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::packet(), Eigen::internal::ternary_evaluator< CwiseTernaryOp< TernaryOp, Arg1, Arg2, Arg3 >, IndexBased, IndexBased >::packet(), Eigen::internal::binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, IndexBased, IndexBased >::packet(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::packet(), Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::packet(), Eigen::internal::unary_evaluator< Replicate< ArgType, RowFactor, ColFactor > >::packet(), Eigen::internal::evaluator_wrapper_base< XprType >::packet(), Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::packet(), Eigen::DenseCoeffsBase< Derived, ReadOnlyAccessors >::packet(), Eigen::ForceAlignedAccess< ExpressionType >::packet(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, LazyProduct >, ProductTag, DenseShape, DenseShape >::packet(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DiagonalShape, DenseShape >::packet(), Eigen::internal::product_evaluator< Product< Lhs, Rhs, ProductKind >, ProductTag, DenseShape, DiagonalShape >::packet(), Eigen::internal::visitor_evaluator< XprType >::packet(), Eigen::internal::unary_evaluator< CoherentPadOp< ArgType, SizeAtCompileTime > >::packet(), Eigen::internal::evaluator< CwiseNullaryOp< NullaryOp, PlainObjectType > >::packet(), Eigen::internal::diagonal_product_evaluator_base< MatrixType, DiagonalType, Derived, ProductOrder >::packet_impl(), Eigen::PlainObjectBase< Derived >::PlainObjectBase(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::prune(), Eigen::internal::PutMatrixElt(), Eigen::internal::QuickSplit(), randMatrixUnitary(), Eigen::TensorSycl::internal::read(), Eigen::DenseBase< Derived >::reverseInPlace(), Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IteratorBased >::InnerVectorInnerIterator::row(), Eigen::internal::block_xpr_helper< Block< XprType, BlockRows, BlockCols, InnerPanel > >::row(), vectorization_logic< Scalar, Enable >::run(), vectorization_logic_half< Scalar, Enable >::run(), Eigen::internal::etor_product_packet_impl< RowMajor, UnrollingIndex, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::internal::etor_product_packet_impl< ColMajor, UnrollingIndex, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::internal::etor_product_packet_impl< RowMajor, Dynamic, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::internal::etor_product_packet_impl< ColMajor, Dynamic, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::internal::etor_product_packet_impl< RowMajor, 1, Lhs, Rhs, Packet, LoadMode >::run(), Eigen::internal::etor_product_packet_impl< ColMajor, 1, Lhs, Rhs, Packet, LoadMode >::run(), schur(), Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::srcCoeff(), Eigen::internal::unary_evaluator< CwiseUnaryOp< core_cast_op< SrcType, DstType >, ArgType >, IndexBased >::srcPacket(), test_stl_iterators(), Eigen::Block< XprType, BlockRows, BlockCols, InnerPanel >::unwind(), verifyIsQuasiTriangular(), Eigen::MapBase< Derived, WriteAccessors >::writePacket(), Eigen::ForceAlignedAccess< ExpressionType >::writePacket(), Eigen::internal::evaluator< PlainObjectBase< Derived > >::writePacket(), Eigen::internal::unary_evaluator< Transpose< ArgType >, IndexBased >::writePacket(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >::writePacket(), Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::writePacket(), Eigen::internal::evaluator_wrapper_base< XprType >::writePacket(), and Eigen::internal::unary_evaluator< Reverse< ArgType, Direction > >::writePacket().
Variable Documentation
m
Matrix3d m = Matrix3d::Identity()