MercuryDPM: Eigen::MovableScalar< Scalar > Struct Template Reference
Eigen::MovableScalar< Scalar > Struct Template Reference
#include <MovableScalar.h>
Public Member Functions
MovableScalar ()
~MovableScalar ()
MovableScalar (const MovableScalar &other)
MovableScalar (MovableScalar &&other) noexcept
MovableScalar & operator= (const MovableScalar &other)
MovableScalar & operator= (MovableScalar &&other) noexcept
MovableScalar (const Scalar &scalar)
operator Scalar () const
Private Member Functions
void set (const Scalar &value)
Scalar get () const
Private Attributes
Scalar * m_data = nullptr
Constructor & Destructor Documentation
MovableScalar() [1/4]
template<typename Scalar > Eigen::MovableScalar< Scalar >::MovableScalar () inline
 : m_data(new Scalar) {}
~MovableScalar()
template<typename Scalar > Eigen::MovableScalar< Scalar >::~MovableScalar () inline
 { delete m_data; }
References Eigen::MovableScalar< Scalar >::m_data.
MovableScalar() [2/4]
template<typename Scalar > Eigen::MovableScalar< Scalar >::MovableScalar (const MovableScalar< Scalar > & other) inline
 : m_data(new Scalar) { set(other.get()); }
References Eigen::MovableScalar< Scalar >::get(), and Eigen::MovableScalar< Scalar >::set().
MovableScalar() [3/4]
template<typename Scalar > Eigen::MovableScalar< Scalar >::MovableScalar (MovableScalar< Scalar > && other) inline noexcept
 : m_data(other.m_data) { other.m_data = nullptr; }
MovableScalar() [4/4]
template<typename Scalar > Eigen::MovableScalar< Scalar >::MovableScalar (const Scalar & scalar) inline
 : m_data(new Scalar) { set(scalar); }
References Eigen::MovableScalar< Scalar >::set().
Member Function Documentation
get()
template<typename Scalar > Scalar Eigen::MovableScalar< Scalar >::get () const inline private
                      {
     eigen_assert(m_data != nullptr);
     // suppress compiler warnings
     return m_data == nullptr ? Scalar() : *m_data;
   }
References eigen_assert, and Eigen::MovableScalar< Scalar >::m_data.
Referenced by Eigen::MovableScalar< Scalar >::MovableScalar(), Eigen::MovableScalar< Scalar >::operator Scalar(), and Eigen::MovableScalar< Scalar >::operator=().
operator Scalar()
template<typename Scalar > Eigen::MovableScalar< Scalar >::operator Scalar () const inline
 { return get(); }
References Eigen::MovableScalar< Scalar >::get().
operator=() [1/2]
template<typename Scalar > MovableScalar& Eigen::MovableScalar< Scalar >::operator= (const MovableScalar< Scalar > & other) inline
{
     set(other.get());
     return *this;
   }
References Eigen::MovableScalar< Scalar >::get(), and Eigen::MovableScalar< Scalar >::set().
operator=() [2/2]
template<typename Scalar > MovableScalar& Eigen::MovableScalar< Scalar >::operator= (MovableScalar< Scalar > && other) inline noexcept
{
     m_data = other.m_data;
     other.m_data = nullptr;
     return *this;
   }
References Eigen::MovableScalar< Scalar >::m_data.
set()
template<typename Scalar > void Eigen::MovableScalar< Scalar >::set (const Scalar & value) inline private
{
     eigen_assert(m_data != nullptr);
     // suppress compiler warnings
     if (m_data != nullptr) *m_data = value;
   }
References eigen_assert, Eigen::MovableScalar< Scalar >::m_data, and Eigen::value.
Referenced by Eigen::MovableScalar< Scalar >::MovableScalar(), and Eigen::MovableScalar< Scalar >::operator=().
Member Data Documentation
m_data
template<typename Scalar > Scalar* Eigen::MovableScalar< Scalar >::m_data = nullptr private
Referenced by Eigen::MovableScalar< Scalar >::get(), Eigen::MovableScalar< Scalar >::operator=(), Eigen::MovableScalar< Scalar >::set(), and Eigen::MovableScalar< Scalar >::~MovableScalar().
The documentation for this struct was generated from the following file:
MovableScalar.h