MercuryDPM: Eigen::internal::redux_impl< Func, Evaluator, SliceVectorizedTraversal, Unrolling > Struct Template Reference
Eigen::internal::redux_impl< Func, Evaluator, SliceVectorizedTraversal, Unrolling > Struct Template Reference
#include <Redux.h>
Public Types
typedef Evaluator::Scalar Scalar
typedef redux_traits< Func, Evaluator >::PacketType PacketType
Static Public Member Functions
template<typename XprType >
static EIGEN_DEVICE_FUNC Scalar run (const Evaluator &eval, const Func &func, const XprType &xpr)
Member Typedef Documentation
PacketType
template<typename Func , typename Evaluator , int Unrolling> typedef redux_traits<Func, Evaluator>::PacketType Eigen::internal::redux_impl< Func, Evaluator, SliceVectorizedTraversal, Unrolling >::PacketType
Scalar
template<typename Func , typename Evaluator , int Unrolling> typedef Evaluator::Scalar Eigen::internal::redux_impl< Func, Evaluator, SliceVectorizedTraversal, Unrolling >::Scalar
Member Function Documentation
run()
template<typename Func , typename Evaluator , int Unrolling> template<typename XprType > static EIGEN_DEVICE_FUNC Scalar Eigen::internal::redux_impl< Func, Evaluator, SliceVectorizedTraversal, Unrolling >::run (const Evaluator & eval, const Func & func, const XprType & xpr) inline static
{
     eigen_assert(xpr.rows() > 0 && xpr.cols() > 0 && "you are using an empty matrix");
     constexpr Index packetSize = redux_traits<Func, Evaluator>::PacketSize;
     const Index innerSize = xpr.innerSize();
     const Index outerSize = xpr.outerSize();
     const Index packetedInnerSize = ((innerSize) / packetSize) * packetSize;
     Scalar res;
     if (packetedInnerSize) {
       PacketType packet_res = eval.template packet<Unaligned, PacketType>(0, 0);
       for (Index j = 0; j < outerSize; ++j)
         for (Index i = (j == 0 ? packetSize : 0); i < packetedInnerSize; i += Index(packetSize))
           packet_res = func.packetOp(packet_res, eval.template packetByOuterInner<Unaligned, PacketType>(j, i));
       res = func.predux(packet_res);
       for (Index j = 0; j < outerSize; ++j)
         for (Index i = packetedInnerSize; i < innerSize; ++i) res = func(res, eval.coeffByOuterInner(j, i));
     } else  // too small to vectorize anything.
             // since this is dynamic-size hence inefficient anyway for such small sizes, don't try to optimize.
     {
       res = redux_impl<Func, Evaluator, DefaultTraversal, NoUnrolling>::run(eval, func, xpr);
     }
     return res;
   }
References Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::cols(), eigen_assert, func(), i, j, res, Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::rows(), and run().
The documentation for this struct was generated from the following file:
Redux.h