MercuryDPM: RisingBubbleProblem< ELEMENT > Class Template Reference
RisingBubbleProblem< ELEMENT > Class Template Reference
Micky mouse problem.
Public Member Functions
RisingBubbleProblem ()
Constructor.
~RisingBubbleProblem ()
Destructor (empty)
void create_free_surface_elements ()
Create free surface elements.
void delete_free_surface_elements ()
Delete free surface elements.
void actions_after_adapt ()
Totally new mesh, need to fix it.
void actions_before_newton_solve ()
Update the problem specs before solve: (Re)set boundary conditions.
void actions_after_newton_solve ()
Update the problem specs before solve (empty)
void doc_solution (const unsigned &nplot, DocInfo &doc_info)
Doc the solution.
void create_volume_constraint_elements ()
Create elements that impose volume constraint on the bubble.
void delete_volume_constraint_elements ()
Delete volume constraint elements.
void snap_onto_sphere ()
Snap the boundary nodes onto the sphere.
Public Member Functions inherited from oomph::Problem
virtual void debug_hook_fct (const unsigned &i)
void set_analytic_dparameter (double *const &parameter_pt)
void unset_analytic_dparameter (double *const &parameter_pt)
bool is_dparameter_calculated_analytically (double *const &parameter_pt)
void set_analytic_hessian_products ()
void unset_analytic_hessian_products ()
bool are_hessian_products_calculated_analytically ()
void set_pinned_values_to_zero ()
bool distributed () const
virtual void actions_before_adapt ()
OomphCommunicator * communicator_pt ()
access function to the oomph-lib communicator
const OomphCommunicator * communicator_pt () const
access function to the oomph-lib communicator, const version
Problem ()
Problem (const Problem &dummy)=delete
Broken copy constructor.
void operator= (const Problem &)=delete
Broken assignment operator.
virtual ~Problem ()
Virtual destructor to clean up memory.
Mesh *& mesh_pt ()
Return a pointer to the global mesh.
Mesh *const & mesh_pt () const
Return a pointer to the global mesh (const version)
Mesh *& mesh_pt (const unsigned &imesh)
Mesh *const & mesh_pt (const unsigned &imesh) const
Return a pointer to the i-th submesh (const version)
unsigned nsub_mesh () const
Return number of submeshes.
unsigned add_sub_mesh (Mesh *const &mesh_pt)
void flush_sub_meshes ()
void build_global_mesh ()
void rebuild_global_mesh ()
LinearSolver *& linear_solver_pt ()
Return a pointer to the linear solver object.
LinearSolver *const & linear_solver_pt () const
Return a pointer to the linear solver object (const version)
LinearSolver *& mass_matrix_solver_for_explicit_timestepper_pt ()
LinearSolver * mass_matrix_solver_for_explicit_timestepper_pt () const
EigenSolver *& eigen_solver_pt ()
Return a pointer to the eigen solver object.
EigenSolver *const & eigen_solver_pt () const
Return a pointer to the eigen solver object (const version)
Time *& time_pt ()
Return a pointer to the global time object.
Time * time_pt () const
Return a pointer to the global time object (const version).
double & time ()
Return the current value of continuous time.
double time () const
Return the current value of continuous time (const version)
TimeStepper *& time_stepper_pt ()
const TimeStepper * time_stepper_pt () const
TimeStepper *& time_stepper_pt (const unsigned &i)
Return a pointer to the i-th timestepper.
ExplicitTimeStepper *& explicit_time_stepper_pt ()
Return a pointer to the explicit timestepper.
unsigned long set_timestepper_for_all_data (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data=false)
virtual void shift_time_values ()
Shift all values along to prepare for next timestep.
AssemblyHandler *& assembly_handler_pt ()
Return a pointer to the assembly handler object.
AssemblyHandler *const & assembly_handler_pt () const
Return a pointer to the assembly handler object (const version)
double & minimum_dt ()
Access function to min timestep in adaptive timestepping.
double & maximum_dt ()
Access function to max timestep in adaptive timestepping.
unsigned & max_newton_iterations ()
Access function to max Newton iterations before giving up.
void problem_is_nonlinear (const bool &prob_lin)
Access function to Problem_is_nonlinear.
double & max_residuals ()
bool & time_adaptive_newton_crash_on_solve_fail ()
Access function for Time_adaptive_newton_crash_on_solve_fail.
double & newton_solver_tolerance ()
void add_time_stepper_pt (TimeStepper *const &time_stepper_pt)
void set_explicit_time_stepper_pt (ExplicitTimeStepper *const &explicit_time_stepper_pt)
void initialise_dt (const double &dt)
void initialise_dt (const Vector< double > &dt)
Data *& global_data_pt (const unsigned &i)
Return a pointer to the the i-th global data object.
void add_global_data (Data *const &global_data_pt)
void flush_global_data ()
LinearAlgebraDistribution *const & dof_distribution_pt () const
Return the pointer to the dof distribution (read-only)
unsigned long ndof () const
Return the number of dofs.
unsigned ntime_stepper () const
Return the number of time steppers.
unsigned nglobal_data () const
Return the number of global data values.
unsigned self_test ()
Self-test: Check meshes and global data. Return 0 for OK.
void enable_store_local_dof_pt_in_elements ()
void disable_store_local_dof_pt_in_elements ()
unsigned long assign_eqn_numbers (const bool &assign_local_eqn_numbers=true)
void describe_dofs (std::ostream &out= *(oomph_info.stream_pt())) const
void enable_discontinuous_formulation ()
void disable_discontinuous_formulation ()
void get_dofs (DoubleVector &dofs) const
void get_dofs (const unsigned &t, DoubleVector &dofs) const
Return vector of the t'th history value of all dofs.
void set_dofs (const DoubleVector &dofs)
Set the values of the dofs.
void set_dofs (const unsigned &t, DoubleVector &dofs)
Set the history values of the dofs.
void set_dofs (const unsigned &t, Vector< double * > &dof_pt)
void add_to_dofs (const double &lambda, const DoubleVector &increment_dofs)
Add lambda x incremenet_dofs[l] to the l-th dof.
double * global_dof_pt (const unsigned &i)
double & dof (const unsigned &i)
i-th dof in the problem
double dof (const unsigned &i) const
i-th dof in the problem (const version)
double *& dof_pt (const unsigned &i)
Pointer to i-th dof in the problem.
double * dof_pt (const unsigned &i) const
Pointer to i-th dof in the problem (const version)
virtual void get_inverse_mass_matrix_times_residuals (DoubleVector &Mres)
virtual void get_dvaluesdt (DoubleVector &f)
virtual void get_residuals (DoubleVector &residuals)
Get the total residuals Vector for the problem.
virtual void get_jacobian (DoubleVector &residuals, DenseDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CRDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CCDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, SumOfMatrices &jacobian)
void get_fd_jacobian (DoubleVector &residuals, DenseMatrix< double > &jacobian)
Get the full Jacobian by finite differencing.
void get_derivative_wrt_global_parameter (double *const &parameter_pt, DoubleVector &result)
void get_hessian_vector_products (DoubleVectorWithHaloEntries const &Y, Vector< DoubleVectorWithHaloEntries > const &C, Vector< DoubleVectorWithHaloEntries > &product)
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, Vector< DoubleVector > &eigenvector, const bool &steady=true)
Solve the eigenproblem.
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, const bool &steady=true)
virtual void get_eigenproblem_matrices (CRDoubleMatrix &mass_matrix, CRDoubleMatrix &main_matrix, const double &shift=0.0)
void assign_eigenvector_to_dofs (DoubleVector &eigenvector)
Assign the eigenvector passed to the function to the dofs.
void add_eigenvector_to_dofs (const double &epsilon, const DoubleVector &eigenvector)
void store_current_dof_values ()
Store the current values of the degrees of freedom.
void restore_dof_values ()
Restore the stored values of the degrees of freedom.
void enable_jacobian_reuse ()
void disable_jacobian_reuse ()
Disable recycling of Jacobian in Newton iteration.
bool jacobian_reuse_is_enabled ()
Is recycling of Jacobian in Newton iteration enabled?
bool & use_predictor_values_as_initial_guess ()
void newton_solve ()
Use Newton method to solve the problem.
void enable_globally_convergent_newton_method ()
enable globally convergent Newton method
void disable_globally_convergent_newton_method ()
disable globally convergent Newton method
void newton_solve (unsigned const &max_adapt)
void steady_newton_solve (unsigned const &max_adapt=0)
void copy (Problem *orig_problem_pt)
virtual Problem * make_copy ()
virtual void read (std::ifstream &restart_file, bool &unsteady_restart)
virtual void read (std::ifstream &restart_file)
virtual void dump (std::ofstream &dump_file) const
void dump (const std::string &dump_file_name) const
void delete_all_external_storage ()
virtual void symmetrise_eigenfunction_for_adaptive_pitchfork_tracking ()
double * bifurcation_parameter_pt () const
void get_bifurcation_eigenfunction (Vector< DoubleVector > &eigenfunction)
void activate_fold_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const DoubleVector &normalisation, const bool &block_solve=true)
void activate_pitchfork_tracking (double *const &parameter_pt, const DoubleVector &symmetry_vector, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const double &omega, const DoubleVector &null_real, const DoubleVector &null_imag, const bool &block_solve=true)
void deactivate_bifurcation_tracking ()
void reset_assembly_handler_to_default ()
Reset the system to the standard non-augemented state.
double arc_length_step_solve (double *const &parameter_pt, const double &ds, const unsigned &max_adapt=0)
double arc_length_step_solve (Data *const &data_pt, const unsigned &data_index, const double &ds, const unsigned &max_adapt=0)
void reset_arc_length_parameters ()
int & sign_of_jacobian ()
void explicit_timestep (const double &dt, const bool &shift_values=true)
Take an explicit timestep of size dt.
void unsteady_newton_solve (const double &dt)
void unsteady_newton_solve (const double &dt, const bool &shift_values)
void unsteady_newton_solve (const double &dt, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const unsigned &suppress_resolve_after_spatial_adapt_flag, const bool &first, const bool &shift=true)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon, const bool &shift_values)
void assign_initial_values_impulsive ()
void assign_initial_values_impulsive (const double &dt)
void calculate_predictions ()
Calculate predictions.
void enable_mass_matrix_reuse ()
void disable_mass_matrix_reuse ()
bool mass_matrix_reuse_is_enabled ()
Return whether the mass matrix is being reused.
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly (DocInfo &doc_info)
void refine_uniformly_and_prune (DocInfo &doc_info)
void refine_uniformly ()
void refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform refinement for submesh i_mesh with documentation.
void refine_uniformly (const unsigned &i_mesh)
Do uniform refinement for submesh i_mesh without documentation.
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly (DocInfo &doc_info)
void p_refine_uniformly_and_prune (DocInfo &doc_info)
void p_refine_uniformly ()
void p_refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-refinement for submesh i_mesh with documentation.
void p_refine_uniformly (const unsigned &i_mesh)
Do uniform p-refinement for submesh i_mesh without documentation.
void refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const unsigned &i_mesh, const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void refine_selected_elements (const Vector< Vector< RefineableElement * >> &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void p_refine_selected_elements (const Vector< Vector< PRefineableElement * >> &elements_to_be_refined_pt)
unsigned unrefine_uniformly ()
unsigned unrefine_uniformly (const unsigned &i_mesh)
void p_unrefine_uniformly (DocInfo &doc_info)
void p_unrefine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-unrefinement for submesh i_mesh without documentation.
void adapt (unsigned &n_refined, unsigned &n_unrefined)
void adapt ()
void p_adapt (unsigned &n_refined, unsigned &n_unrefined)
void p_adapt ()
void adapt_based_on_error_estimates (unsigned &n_refined, unsigned &n_unrefined, Vector< Vector< double >> &elemental_error)
void adapt_based_on_error_estimates (Vector< Vector< double >> &elemental_error)
void get_all_error_estimates (Vector< Vector< double >> &elemental_error)
void doc_errors (DocInfo &doc_info)
Get max and min error for all elements in submeshes.
void doc_errors ()
Get max and min error for all elements in submeshes.
void enable_info_in_newton_solve ()
void disable_info_in_newton_solve ()
Disable the output of information when in the newton solver.
Public Member Functions inherited from oomph::ExplicitTimeSteppableObject
ExplicitTimeSteppableObject ()
Empty constructor.
ExplicitTimeSteppableObject (const ExplicitTimeSteppableObject &)=delete
Broken copy constructor.
void operator= (const ExplicitTimeSteppableObject &)=delete
Broken assignment operator.
virtual ~ExplicitTimeSteppableObject ()
Empty destructor.
virtual void actions_before_explicit_stage ()
virtual void actions_after_explicit_stage ()
Public Attributes
Data * Bubble_pressure_data_pt
Pointer to data that will store the bubble pressure.
RefineableSolidTetgenMesh< ELEMENT > * Fluid_mesh_pt
Pointer to the fluid mesh.
Mesh * Free_surface_mesh_pt
Pointers to mesh of free surface elements.
Mesh * Volume_constraint_mesh_pt
Pointer to mesh containing elements that impose volume constraint.
VolumeConstraintElement * Vol_constraint_el_pt
Pointer to element that imposes volume constraint for bubble.
TetgenMeshOLDFacetedSurface * Outer_boundary_pt
Storage for the outer boundary object.
Vector< TetgenMeshOLDFacetedSurface * > Inner_boundary_pt
Public Attributes inherited from oomph::Problem
bool Shut_up_in_newton_solve
Additional Inherited Members
Public Types inherited from oomph::Problem
typedef void(* SpatialErrorEstimatorFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error)
Function pointer for spatial error estimator.
typedef void(* SpatialErrorEstimatorWithDocFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error, DocInfo &doc_info)
Function pointer for spatial error estimator with doc.
Static Public Attributes inherited from oomph::Problem
static bool Suppress_warning_about_actions_before_read_unstructured_meshes
Protected Types inherited from oomph::Problem
enum Assembly_method {
Perform_assembly_using_vectors_of_pairs , Perform_assembly_using_two_vectors , Perform_assembly_using_maps , Perform_assembly_using_lists ,
Perform_assembly_using_two_arrays
}
Enumerated flags to determine which sparse assembly method is used.
Protected Member Functions inherited from oomph::Problem
unsigned setup_element_count_per_dof ()
virtual void sparse_assemble_row_or_column_compressed (Vector< int * > &column_or_row_index, Vector< int * > &row_or_column_start, Vector< double * > &value, Vector< unsigned > &nnz, Vector< double * > &residual, bool compressed_row_flag)
virtual void actions_before_newton_convergence_check ()
virtual void actions_before_newton_step ()
virtual void actions_after_newton_step ()
virtual void actions_before_implicit_timestep ()
virtual void actions_after_implicit_timestep ()
virtual void actions_after_implicit_timestep_and_error_estimation ()
virtual void actions_before_explicit_timestep ()
Actions that should be performed before each explicit time step.
virtual void actions_after_explicit_timestep ()
Actions that should be performed after each explicit time step.
virtual void actions_before_read_unstructured_meshes ()
virtual void actions_after_read_unstructured_meshes ()
virtual void actions_after_change_in_global_parameter (double *const &parameter_pt)
virtual void actions_after_change_in_bifurcation_parameter ()
virtual void actions_after_parameter_increase (double *const &parameter_pt)
double & dof_derivative (const unsigned &i)
double & dof_current (const unsigned &i)
virtual void set_initial_condition ()
virtual double global_temporal_error_norm ()
unsigned newton_solve_continuation (double *const &parameter_pt)
unsigned newton_solve_continuation (double *const &parameter_pt, DoubleVector &z)
void calculate_continuation_derivatives (double *const &parameter_pt)
void calculate_continuation_derivatives (const DoubleVector &z)
void calculate_continuation_derivatives_fd (double *const &parameter_pt)
bool does_pointer_correspond_to_problem_data (double *const &parameter_pt)
void set_consistent_pinned_values_for_continuation ()
Protected Attributes inherited from oomph::Problem
Vector< Problem * > Copy_of_problem_pt
std::map< double *, bool > Calculate_dparameter_analytic
bool Calculate_hessian_products_analytic
LinearAlgebraDistribution * Dof_distribution_pt
Vector< double * > Dof_pt
Vector of pointers to dofs.
DoubleVectorWithHaloEntries Element_count_per_dof
double Relaxation_factor
double Newton_solver_tolerance
unsigned Max_newton_iterations
Maximum number of Newton iterations.
unsigned Nnewton_iter_taken
Vector< double > Max_res
Maximum residuals at start and after each newton iteration.
double Max_residuals
bool Time_adaptive_newton_crash_on_solve_fail
bool Jacobian_reuse_is_enabled
Is re-use of Jacobian in Newton iteration enabled? Default: false.
bool Jacobian_has_been_computed
bool Problem_is_nonlinear
bool Pause_at_end_of_sparse_assembly
bool Doc_time_in_distribute
unsigned Sparse_assembly_method
unsigned Sparse_assemble_with_arrays_initial_allocation
unsigned Sparse_assemble_with_arrays_allocation_increment
Vector< Vector< unsigned > > Sparse_assemble_with_arrays_previous_allocation
double Numerical_zero_for_sparse_assembly
double FD_step_used_in_get_hessian_vector_products
bool Mass_matrix_reuse_is_enabled
bool Mass_matrix_has_been_computed
bool Discontinuous_element_formulation
double Minimum_dt
Minimum desired dt: if dt falls below this value, exit.
double Maximum_dt
Maximum desired dt.
double DTSF_max_increase
double DTSF_min_decrease
double Minimum_dt_but_still_proceed
bool Scale_arc_length
Boolean to control whether arc-length should be scaled.
double Desired_proportion_of_arc_length
Proportion of the arc-length to taken by the parameter.
double Theta_squared
int Sign_of_jacobian
Storage for the sign of the global Jacobian.
double Continuation_direction
double Parameter_derivative
Storage for the derivative of the global parameter wrt arc-length.
double Parameter_current
Storage for the present value of the global parameter.
bool Use_continuation_timestepper
Boolean to control original or new storage of dof stuff.
unsigned Dof_derivative_offset
unsigned Dof_current_offset
Vector< double > Dof_derivative
Storage for the derivative of the problem variables wrt arc-length.
Vector< double > Dof_current
Storage for the present values of the variables.
double Ds_current
Storage for the current step value.
unsigned Desired_newton_iterations_ds
double Minimum_ds
Minimum desired value of arc-length.
bool Bifurcation_detection
Boolean to control bifurcation detection via determinant of Jacobian.
bool Bisect_to_find_bifurcation
Boolean to control wheter bisection is used to located bifurcation.
bool First_jacobian_sign_change
Boolean to indicate whether a sign change has occured in the Jacobian.
bool Arc_length_step_taken
Boolean to indicate whether an arc-length step has been taken.
bool Use_finite_differences_for_continuation_derivatives
OomphCommunicator * Communicator_pt
The communicator for this problem.
bool Always_take_one_newton_step
double Timestep_reduction_factor_after_nonconvergence
bool Keep_temporal_error_below_tolerance
Static Protected Attributes inherited from oomph::Problem
static ContinuationStorageScheme Continuation_time_stepper
Storage for the single static continuation timestorage object.
Detailed Description
template<class ELEMENT>
class RisingBubbleProblem< ELEMENT >
Micky mouse problem.
Constructor & Destructor Documentation
RisingBubbleProblem()
template<class ELEMENT > RisingBubbleProblem< ELEMENT >::RisingBubbleProblem
Constructor.
Constructor for RisingBubble problem.
 {
  //Add a time stepper
  this->add_time_stepper_pt(new BDF<2>);
  // Create bubble pressure as global Data
  Bubble_pressure_data_pt = new Data(1);
  unsigned index_of_traded_pressure=0;
  this->add_global_data(Bubble_pressure_data_pt);
  Vol_constraint_el_pt =
   new VolumeConstraintElement(&Global_Parameters::Volume,
                               Bubble_pressure_data_pt,
                               index_of_traded_pressure);
  //Provide a reasonable initial guess for bubble pressure (hydrostatics):
  Bubble_pressure_data_pt->set_value(index_of_traded_pressure,
                                     2.0*Global_Parameters::Ca/
                                     Global_Parameters::Radius);
  //Make the external box
  const double box_width = Global_Parameters::Box_width;
  const double box_length = Global_Parameters::Box_length;
  Vector<Vector<double> > box_point(8);
  box_point[0].resize(3);
  box_point[0][0] = -box_width;
  box_point[0][1] = -box_width;
  box_point[0][2] = -box_length;
  box_point[1].resize(3);
  box_point[1][0] = -box_width;
  box_point[1][1] =  box_width;
  box_point[1][2] = -box_length;
  box_point[2].resize(3);
  box_point[2][0] = -box_width;
  box_point[2][1] =  box_width;
  box_point[2][2] =  box_length;
  box_point[3].resize(3);
  box_point[3][0] = -box_width;
  box_point[3][1] = -box_width;
  box_point[3][2] =  box_length;
  box_point[4].resize(3);
  box_point[4][0] =  box_width;
  box_point[4][1] = -box_width;
  box_point[4][2] = -box_length;
  box_point[5].resize(3);
  box_point[5][0] =  box_width;
  box_point[5][1] =  box_width;
  box_point[5][2] = -box_length;
  box_point[6].resize(3);
  box_point[6][0] =  box_width;
  box_point[6][1] =  box_width;
  box_point[6][2] =  box_length;
  box_point[7].resize(3);
  box_point[7][0] =  box_width;
  box_point[7][1] =  -box_width;
  box_point[7][2] =  box_length;
  Vector<Vector<unsigned> > box_facet(6);
  box_facet[0].resize(4);
  box_facet[0][0] = 0;
  box_facet[0][1] = 4;
  box_facet[0][2] = 7;
  box_facet[0][3] = 3;
  box_facet[1].resize(4);
  box_facet[1][0] = 4;
  box_facet[1][1] = 5;
  box_facet[1][2] = 6;
  box_facet[1][3] = 7;
  box_facet[2].resize(4);
  box_facet[2][0] = 3;
  box_facet[2][1] = 7;
  box_facet[2][2] = 6;
  box_facet[2][3] = 2;
  box_facet[3].resize(4);
  box_facet[3][0] = 6;
  box_facet[3][1] = 5;
  box_facet[3][2] = 1;
  box_facet[3][3] = 2;
  box_facet[4].resize(4);
  box_facet[4][0] = 3;
  box_facet[4][1] = 2;
  box_facet[4][2] = 1;
  box_facet[4][3] = 0;
  box_facet[5].resize(4);
  box_facet[5][0] = 5;
  box_facet[5][1] = 1;
  box_facet[5][2] = 0;
  box_facet[5][3] = 4;
  Vector<unsigned> box_facet_boundary_id(6);
  box_facet_boundary_id[0] = 1;
  box_facet_boundary_id[1] = 2;
  box_facet_boundary_id[2] = 3;
  box_facet_boundary_id[3] = 4;
  box_facet_boundary_id[4] = 5;
  box_facet_boundary_id[5] = 6;
  //Make the outer boundary object
  Outer_boundary_pt =
   new TetgenMeshOLDFacetedSurface(box_point,box_facet,box_facet_boundary_id);
   //Set basic icosahedron points
  Vector<Vector<double> > icosa_point(12);
  //Golden ratio
  const double phi = 0.5*(1.0 + sqrt(5.0));
  icosa_point[0].resize(3);
  icosa_point[0][0] = 0.0;
  icosa_point[0][1] = 1.0;
  icosa_point[0][2] = phi;
  icosa_point[1].resize(3);
  icosa_point[1][0] = 0.0;
  icosa_point[1][1] = -1.0;
  icosa_point[1][2] = phi;
  icosa_point[2].resize(3);
  icosa_point[2][0] = 0.0;
  icosa_point[2][1] = 1.0;
  icosa_point[2][2] = -phi;
  icosa_point[3].resize(3);
  icosa_point[3][0] = 0.0;
  icosa_point[3][1] = -1.0;
  icosa_point[3][2] = -phi;
  icosa_point[4].resize(3);
  icosa_point[4][0] = 1.0;
  icosa_point[4][1] = phi;
  icosa_point[4][2] = 0.0;
  icosa_point[5].resize(3);
  icosa_point[5][0] = -1.0;
  icosa_point[5][1] = phi;
  icosa_point[5][2] = 0.0;
  icosa_point[6].resize(3);
  icosa_point[6][0] = 1.0;
  icosa_point[6][1] = -phi;
  icosa_point[6][2] = 0.0;
  icosa_point[7].resize(3);
  icosa_point[7][0] = -1.0;
  icosa_point[7][1] = -phi;
  icosa_point[7][2] = 0.0;
  icosa_point[8].resize(3);
  icosa_point[8][0] = phi;
  icosa_point[8][1] = 0.0;
  icosa_point[8][2] = 1.0;
  icosa_point[9].resize(3);
  icosa_point[9][0] = phi;
  icosa_point[9][1] = 0.0;
  icosa_point[9][2] = -1.0;
  icosa_point[10].resize(3);
  icosa_point[10][0] = -phi;
  icosa_point[10][1] = 0.0;
  icosa_point[10][2] = 1.0;
  icosa_point[11].resize(3);
  icosa_point[11][0] = -phi;
  icosa_point[11][1] = 0.0;
  icosa_point[11][2] = -1.0;
  //Scale the points by the radius
  for(unsigned p=0;p<12;p++)
   {
    double r2 = 0.0;
    for(unsigned i=0;i<3;i++) {r2 += icosa_point[p][i]*icosa_point[p][i];}
    //Now scale all of the points
    for(unsigned i=0;i<3;i++)
     {
      icosa_point[p][i] *= Global_Parameters::Radius/sqrt(r2);
     }
   }
  //Set up the connectivity
  Vector<Vector<unsigned> > icosa_facet(20);
  icosa_facet[0].resize(3);
  icosa_facet[0][0] = 0;
  icosa_facet[0][1] = 1;
  icosa_facet[0][2] = 8;
  icosa_facet[1].resize(3);
  icosa_facet[1][0] = 0;
  icosa_facet[1][1] = 10;
  icosa_facet[1][2] = 1;
  icosa_facet[2].resize(3);
  icosa_facet[2][0] = 0;
  icosa_facet[2][1] = 5;
  icosa_facet[2][2] = 10;
  icosa_facet[3].resize(3);
  icosa_facet[3][0] = 0;
  icosa_facet[3][1] = 4;
  icosa_facet[3][2] = 5;
  icosa_facet[4].resize(3);
  icosa_facet[4][0] = 0;
  icosa_facet[4][1] = 8;
  icosa_facet[4][2] = 4;
  icosa_facet[5].resize(3);
  icosa_facet[5][0] = 5;
  icosa_facet[5][1] = 11;
  icosa_facet[5][2] = 10;
  icosa_facet[6].resize(3);
  icosa_facet[6][0] = 5;
  icosa_facet[6][1] = 2;
  icosa_facet[6][2] = 11;
  icosa_facet[7].resize(3);
  icosa_facet[7][0] = 4;
  icosa_facet[7][1] = 2;
  icosa_facet[7][2] = 5;
  icosa_facet[8].resize(3);
  icosa_facet[8][0] = 4;
  icosa_facet[8][1] = 9;
  icosa_facet[8][2] = 2;
  icosa_facet[9].resize(3);
  icosa_facet[9][0] = 8;
  icosa_facet[9][1] = 9;
  icosa_facet[9][2] = 4;
  icosa_facet[10].resize(3);
  icosa_facet[10][0] = 6;
  icosa_facet[10][1] = 9;
  icosa_facet[10][2] = 8;
  icosa_facet[11].resize(3);
  icosa_facet[11][0] = 1;
  icosa_facet[11][1] = 6;
  icosa_facet[11][2] = 8;
  icosa_facet[12].resize(3);
  icosa_facet[12][0] = 1;
  icosa_facet[12][1] = 7;
  icosa_facet[12][2] = 6;
  icosa_facet[13].resize(3);
  icosa_facet[13][0] = 10;
  icosa_facet[13][1] = 7;
  icosa_facet[13][2] = 1;
  icosa_facet[14].resize(3);
  icosa_facet[14][0] = 10;
  icosa_facet[14][1] = 11;
  icosa_facet[14][2] = 7;
  icosa_facet[15].resize(3);
  icosa_facet[15][0] = 11;
  icosa_facet[15][1] = 3;
  icosa_facet[15][2] = 7;
  icosa_facet[16].resize(3);
  icosa_facet[16][0] = 7;
  icosa_facet[16][1] = 3;
  icosa_facet[16][2] = 6;
  icosa_facet[17].resize(3);
  icosa_facet[17][0] = 6;
  icosa_facet[17][1] = 3;
  icosa_facet[17][2] = 9;
  icosa_facet[18].resize(3);
  icosa_facet[18][0] = 9;
  icosa_facet[18][1] = 3;
  icosa_facet[18][2] = 2;
  icosa_facet[19].resize(3);
  icosa_facet[19][0] = 2;
  icosa_facet[19][1] = 3;
  icosa_facet[19][2] = 11;
  //Set each icosahedral facet to be a separate boundary
  //This is required so that we can set up a unique surface
  //coordinate system
  Vector<unsigned> icosa_facet_boundary_id(20);
  for(unsigned i=0;i<20;i++)
   {
    icosa_facet_boundary_id[i] = 7+i;
   }
  //Create the inner boundary object
  Inner_boundary_pt.resize(1);
  Inner_boundary_pt[0] =
   new TetgenMeshClosedFacetedSurface(icosa_point,icosa_facet,
                                      icosa_facet_boundary_id);
  Vector<double> inner_point(3,0.0);
  dynamic_cast<TetgenMeshClosedFacetedSurface*>(Inner_boundary_pt[0])->
   set_hole(inner_point);
  /*in.numberofregions = 1;
  in.regionlist = new double[5*in.numberofregions];
  in.regionlist[0] = 0.0;
  in.regionlist[1] = 0.0;
  in.regionlist[2] = 0.0;
  in.regionlist[3] = 1;
  in.regionlist[4] = 1;*/
  Fluid_mesh_pt =
   new RefineableSolidTetgenMesh<ELEMENT>(Outer_boundary_pt,
                                          Inner_boundary_pt,2.0,
                                          this->time_stepper_pt(),
                                          true);
  //Must split the elements in the corners
  Fluid_mesh_pt->split_elements_in_corners(this->time_stepper_pt());
  // Set error estimator for bulk mesh
  Z2ErrorEstimator* error_estimator_pt=new Z2ErrorEstimator;
  Fluid_mesh_pt->spatial_error_estimator_pt()=error_estimator_pt;
  // Set targets for spatial adaptivity
  Fluid_mesh_pt->max_permitted_error()=0.005;
  Fluid_mesh_pt->min_permitted_error()=0.001;
  Fluid_mesh_pt->max_element_size()=1.0;
  Fluid_mesh_pt->min_element_size()=0.001;
  // Use coarser mesh during validation
  if (CommandLineArgs::command_line_flag_has_been_set("--validation"))
   {
    Fluid_mesh_pt->max_element_size()=2.0;
    Fluid_mesh_pt->min_element_size()=0.1;
   }
  // Set the problem pointer
  Fluid_mesh_pt->problem_pt()=this;
  // Set the boundary conditions for this problem
  // Only on the "outer boundaries"
  for(unsigned ibound=0;ibound<6;ibound++)
  {
   unsigned final_index = 3;
   //Do no pin the outlet z-velocity
   if(ibound==2) {final_index = 2;}
    unsigned num_nod= Fluid_mesh_pt->nboundary_node(ibound);
    for (unsigned inod=0;inod<num_nod;inod++)
    {
     Node* nod_pt = Fluid_mesh_pt->boundary_node_pt(ibound,inod);
     //Pin the fluid velocities
     for(unsigned i=0;i<final_index;++i) {nod_pt->pin(i);}
     //Now pin all positions not on bubble
     for(unsigned i=0;i<3;i++)
      {dynamic_cast<SolidNode*>(nod_pt)->pin_position(i);}
    }
  }
  // Complete the build of all elements so they are fully functional
  //Find number of elements in mesh
  unsigned n_element = Fluid_mesh_pt->nelement();
  // Loop over the elements to set up element-specific
  // things that cannot be handled by constructor
  for(unsigned i=0;i<n_element;i++)
   {
    // Upcast from GeneralElement to the present element
    ELEMENT* el_pt = dynamic_cast<ELEMENT*>(Fluid_mesh_pt->element_pt(i));
    //Set the source function pointer
    el_pt->re_pt() = &Global_Parameters::Re;
    //Set the gravity term
    el_pt->re_invfr_pt() = &Global_Parameters::ReInvFr;
    //Set gravity
    el_pt->g_pt() = &Global_Parameters::G;
    //Set the contitutive parameter
    el_pt->constitutive_law_pt() = Global_Parameters::Constitutive_law_pt;
   }
  //Loop over the elements in region 1
  /*unsigned n_inner = Fluid_mesh_pt->nregion_element(1);
  for(unsigned e=0;e<n_inner;++e)
   {
    // Upcast from GeneralElement to the present element
    ELEMENT* el_pt = dynamic_cast<ELEMENT*>(Fluid_mesh_pt->region_element_pt(1,e));
    //Set the source function pointer
    el_pt->viscosity_ratio_pt() = &Global_Parameters::Visc_Ratio;
    }*/
  //Now create the other meshes
  Free_surface_mesh_pt = new Mesh;
  create_free_surface_elements();
  Volume_constraint_mesh_pt = new Mesh;
  create_volume_constraint_elements();
  //Combine the meshes
  //Bubble_pressure_data_pt->pin(0);
  // Add volume constraint sub mesh
  this->add_sub_mesh(this->Volume_constraint_mesh_pt);
  // Add Fluid_mesh_pt sub meshes
  this->add_sub_mesh(Fluid_mesh_pt);
  // Add Free_surface sub meshes
  this->add_sub_mesh(this->Free_surface_mesh_pt);
  // Build global mesh
  this->build_global_mesh();
  // Setup equation numbering scheme
  cout <<"Number of equations: " << assign_eqn_numbers() << std::endl;
 }
References Global_Parameters::Box_length, Global_Parameters::Box_width, Global_Parameters::Ca, oomph::CommandLineArgs::command_line_flag_has_been_set(), Global_Parameters::Constitutive_law_pt, MeshRefinement::error_estimator_pt, Global_Parameters::G, i, p, oomph::Data::pin(), Global_Parameters::Radius, Global_Parameters::Re, Global_Parameters::ReInvFr, sqrt(), and Global_Parameters::Volume.
~RisingBubbleProblem()
template<class ELEMENT > RisingBubbleProblem< ELEMENT >::~RisingBubbleProblem () inline
Destructor (empty)
   {
    //Delete the objects
    unsigned nh = Inner_boundary_pt.size();
    for(unsigned h=0;h<nh;++h)
     {
      delete Inner_boundary_pt[h];
     }
    delete Outer_boundary_pt;
   }
Member Function Documentation
actions_after_adapt()
template<class ELEMENT > void RisingBubbleProblem< ELEMENT >::actions_after_adapt () inline virtual
Totally new mesh, need to fix it.
Reimplemented from oomph::Problem.
   {
    // Set the boundary conditions for this problem
    // Only on the "outer boundaries"
    for(unsigned ibound=0;ibound<6;ibound++)
     {
      unsigned final_index = 3;
      //Do no pin the outlet z-velocity
      if(ibound==2) {final_index = 2;}
      unsigned num_nod= Fluid_mesh_pt->nboundary_node(ibound);
      for (unsigned inod=0;inod<num_nod;inod++)
       {
        for(unsigned i=0;i<final_index;++i)
         {
          Fluid_mesh_pt->boundary_node_pt(ibound,inod)->pin(i);
         }
       }
     }
    // Complete the build of all elements so they are fully functional
    //Find number of elements in mesh
    unsigned n_element = Fluid_mesh_pt->nelement();
    // Loop over the elements to set up element-specific
    // things that cannot be handled by constructor
    for(unsigned i=0;i<n_element;i++)
     {
      // Upcast from GeneralElement to the present element
      ELEMENT* el_pt = dynamic_cast<ELEMENT*>(Fluid_mesh_pt->element_pt(i));
      //Set the source function pointer
      el_pt->re_pt() = &Global_Parameters::Re;
      //Set the gravity term
      el_pt->re_invfr_pt() = &Global_Parameters::ReInvFr;
      el_pt->g_pt() = &Global_Parameters::G;
      //Set the contitutive law
      el_pt->constitutive_law_pt() = Global_Parameters::Constitutive_law_pt;
     }
   }
References Global_Parameters::Constitutive_law_pt, Global_Parameters::G, i, Global_Parameters::Re, and Global_Parameters::ReInvFr.
actions_after_newton_solve()
template<class ELEMENT > void RisingBubbleProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update the problem specs before solve (empty)
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve()
template<class ELEMENT > void RisingBubbleProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve: (Re)set boundary conditions.
Reimplemented from oomph::Problem.
   {
    //Loop over the boundaries
    for(unsigned ibound=0;ibound<6;ibound++)
     {
      //Don't boundary 3's z-coordinates
      unsigned final_index = 3;
      if(ibound==2) {final_index = 2;}
      // Loop over the nodes on boundary
      unsigned num_nod=Fluid_mesh_pt->nboundary_node(ibound);
      for (unsigned inod=0;inod<num_nod;inod++)
       {
        Node* nod_pt=Fluid_mesh_pt->boundary_node_pt(ibound,inod);
        for(unsigned i=0;i<final_index;++i) {nod_pt->set_value(i,0.0);}
       }
     }
    //Now set a Poiseuille like inflow
    {
     using namespace Global_Parameters;
     // Loop over the nodes on boundary
     unsigned num_nod=Fluid_mesh_pt->nboundary_node(5);
     for (unsigned inod=0;inod<num_nod;inod++)
      {
       //Node* nod_pt=Fluid_mesh_pt->boundary_node_pt(5,inod);
        //double x = nod_pt->x(0);
        //double y = nod_pt->x(1);
        //double u = (Box_width-x)*(Box_width+x)*(Box_width-y)*(Box_width+y);
        // nod_pt->set_value(2,u);
      }
    }
   }
References i, and oomph::Data::set_value().
create_free_surface_elements()
template<class ELEMENT > void RisingBubbleProblem< ELEMENT >::create_free_surface_elements () inline
Create free surface elements.
Volume constraint element stores the Data item that stores the bubble pressure that is adjusted/traded to allow for volume conservation. Which value is the pressure stored in?
   {
    unsigned p_traded_index=Vol_constraint_el_pt->index_of_traded_pressure();
    //Loop over the free surface boundaries
    //which is actually quite a large number
    unsigned nb=Fluid_mesh_pt->nboundary();
    for(unsigned b=6;b<nb;b++)
     {
      // How many bulk fluid elements are adjacent to boundary b?
      unsigned n_element = Fluid_mesh_pt->nboundary_element(b);
      // Loop over the bulk fluid elements adjacent to boundary b?
      for(unsigned e=0;e<n_element;e++)
       {
        // Get pointer to the bulk fluid element that is
      // adjacent to boundary b
        ELEMENT* bulk_elem_pt = dynamic_cast<ELEMENT*>(
         Fluid_mesh_pt->boundary_element_pt(b,e));
        //Find the index of the face of element e along boundary b
        int face_index = Fluid_mesh_pt->face_index_at_boundary(b,e);
        // Create new element
        ElasticSurfaceFluidInterfaceElement<ELEMENT>* el_pt =
         new ElasticSurfaceFluidInterfaceElement<ELEMENT>(
          bulk_elem_pt,face_index);
        // Add it to the mesh
        Free_surface_mesh_pt->add_element_pt(el_pt);
        //Add the appropriate boundary number
        el_pt->set_boundary_number_in_bulk_mesh(b);
        //Specify the capillary number
        el_pt->ca_pt() = &Global_Parameters::Ca;
        // Specify the bubble pressure (pointer to Data object and
        // index of value within that Data object that corresponds
        // to the traded pressure
        el_pt->set_external_pressure_data(
         Vol_constraint_el_pt->p_traded_data_pt(),p_traded_index);
       }
     }
   }
References b, Global_Parameters::Ca, oomph::FluidInterfaceElement::ca_pt(), e(), nb, oomph::FaceElement::set_boundary_number_in_bulk_mesh(), and oomph::FluidInterfaceElement::set_external_pressure_data().
create_volume_constraint_elements()
template<class ELEMENT > void RisingBubbleProblem< ELEMENT >::create_volume_constraint_elements () inline
Create elements that impose volume constraint on the bubble.
   {
    // Add volume constraint element to the mesh
    Volume_constraint_mesh_pt->add_element_pt(Vol_constraint_el_pt);
    //Loop over the free surface boundaries
    unsigned nb=Fluid_mesh_pt->nboundary();
    for(unsigned b=6;b<nb;b++)
     {
      // How many bulk fluid elements are adjacent to boundary b?
      unsigned n_element = Fluid_mesh_pt->nboundary_element(b);
      // Loop over the bulk fluid elements adjacent to boundary b?
      for(unsigned e=0;e<n_element;e++)
       {
        // Get pointer to the bulk fluid element that is
        // adjacent to boundary b
        ELEMENT* bulk_elem_pt = dynamic_cast<ELEMENT*>(
         Fluid_mesh_pt->boundary_element_pt(b,e));
        //Find the index of the face of element e along boundary b
        int face_index = Fluid_mesh_pt->face_index_at_boundary(b,e);
        // Create new element
        ElasticSurfaceVolumeConstraintBoundingElement<ELEMENT>* el_pt =
         new ElasticSurfaceVolumeConstraintBoundingElement<ELEMENT>(
          bulk_elem_pt,face_index);
        //Set the "master" volume control element
        el_pt->set_volume_constraint_element(Vol_constraint_el_pt);
        // Add it to the mesh
        Volume_constraint_mesh_pt->add_element_pt(el_pt);
       }
     }
   }
References b, e(), nb, and oomph::VolumeConstraintBoundingElement::set_volume_constraint_element().
delete_free_surface_elements()
template<class ELEMENT > void RisingBubbleProblem< ELEMENT >::delete_free_surface_elements () inline
Delete free surface elements.
   {
    // How many surface elements are in the surface mesh
    unsigned n_element = Free_surface_mesh_pt->nelement();
    // Loop over the surface elements
    for(unsigned e=0;e<n_element;e++)
     {
      // Kill surface element
      delete Free_surface_mesh_pt->element_pt(e);
     }
    // Wipe the mesh
    Free_surface_mesh_pt->flush_element_and_node_storage();
   } // end of delete_free_surface_elements
References e().
delete_volume_constraint_elements()
template<class ELEMENT > void RisingBubbleProblem< ELEMENT >::delete_volume_constraint_elements () inline
Delete volume constraint elements.
   {
    // How many surface elements are in the surface mesh
    unsigned n_element = Volume_constraint_mesh_pt->nelement();
    // Loop over the surface elements (but don't kill the volume constraint
    // element (element 0))
    unsigned first_el_to_be_killed=1;
    for(unsigned e=first_el_to_be_killed;e<n_element;e++)
     {
      delete Volume_constraint_mesh_pt->element_pt(e);
     }
    // Wipe the mesh
    Volume_constraint_mesh_pt->flush_element_and_node_storage();
   } // end of delete_volume_constraint_elements
References e().
doc_solution()
template<class ELEMENT > void RisingBubbleProblem< ELEMENT >::doc_solution (const unsigned & nplot, DocInfo & doc_info)
Doc the solution.
 {
  ofstream some_file;
  char filename[100];
  // Doc local node numbering
  //-------------------------
  sprintf(filename,"%s/node_numbering%i.dat",doc_info.directory().c_str(),
          doc_info.number());
  some_file.open(filename);
  FiniteElement* el_pt=Fluid_mesh_pt->finite_element_pt(0);
  unsigned nnode=el_pt->nnode();
  unsigned ndim=el_pt->node_pt(0)->ndim();
  for (unsigned j=0;j<nnode;j++)
   {
    for (unsigned i=0;i<ndim;i++)
     {
      some_file << el_pt->node_pt(j)->x(i) << " " ;
     }
    some_file << j << std::endl;
   }
  some_file.close();
  //Tell me how many elements there are
  std::cout << "Surface " << Free_surface_mesh_pt->nelement() << "\n";
  // Output boundaries
  //------------------
  sprintf(filename,"%s/surface%i.dat",doc_info.directory().c_str(),
          doc_info.number());
  some_file.open(filename);
  Free_surface_mesh_pt->output(some_file,nplot);
  //Tell me what we have
  some_file.close();
  // Output solution
  //----------------
  sprintf(filename,"%s/soln%i.dat",doc_info.directory().c_str(),
          doc_info.number());
  some_file.open(filename);
  Fluid_mesh_pt->output(some_file,nplot);
  some_file.close();
 } // end of doc
References oomph::DocInfo::directory(), MergeRestartFiles::filename, i, j, oomph::Node::ndim(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::DocInfo::number(), and oomph::Node::x().
snap_onto_sphere()
template<class ELEMENT > void RisingBubbleProblem< ELEMENT >::snap_onto_sphere () inline
Snap the boundary nodes onto the sphere.
   {
    const unsigned n_boundary = Fluid_mesh_pt->nboundary();
    for(unsigned b=6;b<n_boundary;b++)
     {
      unsigned n_node = Fluid_mesh_pt->nboundary_node(b);
      for(unsigned n=0;n<n_node;++n)
       {
        Node* nod_pt = Fluid_mesh_pt->boundary_node_pt(b,n);
        double x = nod_pt->x(0);
        double y = nod_pt->x(1);
        double z = nod_pt->x(2);
        //Now let's snap by calculating the angle
        double r = sqrt(x*x + y*y + z*z);
        double theta = acos(z/r);
        double phi = atan2(y,x);
        //Do the snapping
        double R_new = Global_Parameters::Radius;
        nod_pt->x(0) = R_new*sin(theta)*cos(phi);
        nod_pt->x(1) = R_new*sin(theta)*sin(phi);
        nod_pt->x(2) = R_new*cos(theta);
       }
      //Loop over the elements adjacent to the boundary
      unsigned n_element = this->Fluid_mesh_pt->nboundary_element(b);
      if(n_element > 0)
       {
        //Make a dummy simplex element
        TElement<3,2> dummy_four_node_element;
        //Make a dummy quadratic element
        TElement<3,3> dummy_ten_node_element;
        Vector<double> s(3);
        Vector<double> x_new(3);
        for(unsigned n=0;n<4;n++) {dummy_four_node_element.construct_node(n);}
        for(unsigned n=0;n<10;n++) {dummy_ten_node_element.construct_node(n);}
        for(unsigned e=0;e<n_element;e++)
         {
          //Cache the element pointer
          ELEMENT* elem_pt = dynamic_cast<ELEMENT*>(
           this->Fluid_mesh_pt->boundary_element_pt(b,e));
          //Find the number of nodes
          const unsigned n_node = elem_pt->nnode();
          //Only do something if not simplex element
          if(n_node > 4)
           {
            //Copy the nodes into the dummy
            for(unsigned n=0;n<4;n++)
             {
              for(unsigned i=0;i<3;i++)
               {
                dummy_four_node_element.node_pt(n)->x(i) =
                 elem_pt->node_pt(n)->x(i);
               }
             }
            //Now sort out the mid-side nodes
            for(unsigned n=4;n<10;n++)
             {
              //If it's not on a boundary then reset to be interpolated
              //from the simplex
              if(!elem_pt->node_pt(n)->is_on_boundary())
               {
                elem_pt->local_coordinate_of_node(n,s);
                dummy_four_node_element.interpolated_x(s,x_new);
                for(unsigned i=0;i<3;i++) {elem_pt->node_pt(n)->x(i) = x_new[i];}
               }
             }
           }
          //If we have more than 10 nodes interpolate from the quadratic shape
          if(n_node > 10)
           {
            //Copy the nodes into the dummy
            for(unsigned n=0;n<10;n++)
             {
              for(unsigned i=0;i<3;i++)
               {
                dummy_ten_node_element.node_pt(n)->x(i) =
                 elem_pt->node_pt(n)->x(i);
               }
             }
            //Now sort out the mid-face and central nodes
            for(unsigned n=10;n<n_node;n++)
             {
              //If it's not on a boundary then reset to be interpolated
              //from the simplex
              if(!elem_pt->node_pt(n)->is_on_boundary())
               {
                elem_pt->local_coordinate_of_node(n,s);
                dummy_ten_node_element.interpolated_x(s,x_new);
                for(unsigned i=0;i<3;i++) {elem_pt->node_pt(n)->x(i) = x_new[i];}
               }
             }
           }
         }
       } //End of fix up of elements
     }
   }
References acos(), atan2(), b, cos(), e(), i, n, UniformPSDSelfTest::r, Global_Parameters::Radius, s, sin(), sqrt(), BiharmonicTestFunctions2::theta, plotDoE::x, oomph::Node::x(), and y.
Member Data Documentation
Bubble_pressure_data_pt
template<class ELEMENT > Data* RisingBubbleProblem< ELEMENT >::Bubble_pressure_data_pt
Pointer to data that will store the bubble pressure.
Fluid_mesh_pt
template<class ELEMENT > RefineableSolidTetgenMesh<ELEMENT>* RisingBubbleProblem< ELEMENT >::Fluid_mesh_pt
Pointer to the fluid mesh.
Free_surface_mesh_pt
template<class ELEMENT > Mesh* RisingBubbleProblem< ELEMENT >::Free_surface_mesh_pt
Pointers to mesh of free surface elements.
Inner_boundary_pt
template<class ELEMENT > Vector<TetgenMeshOLDFacetedSurface*> RisingBubbleProblem< ELEMENT >::Inner_boundary_pt
Outer_boundary_pt
template<class ELEMENT > TetgenMeshOLDFacetedSurface* RisingBubbleProblem< ELEMENT >::Outer_boundary_pt
Storage for the outer boundary object.
Vol_constraint_el_pt
template<class ELEMENT > VolumeConstraintElement* RisingBubbleProblem< ELEMENT >::Vol_constraint_el_pt
Pointer to element that imposes volume constraint for bubble.
Volume_constraint_mesh_pt
template<class ELEMENT > Mesh* RisingBubbleProblem< ELEMENT >::Volume_constraint_mesh_pt
Pointer to mesh containing elements that impose volume constraint.
The documentation for this class was generated from the following file:
uns_adapt_3d_fs.cc