MercuryDPM: collapsible_channel_algebraic.cc File Reference
collapsible_channel_algebraic.cc File Reference
#include <iostream>
#include "generic.h"
#include "navier_stokes.h"
#include "my_alg_channel_mesh.h"
Classes
class OscillatingWall
class CollapsibleChannelProblem< ELEMENT >
Problem class.
Namespaces
BL_Squash
Global_Physical_Variables
Global variables.
Functions
double BL_Squash::squash_fct (const double &s)
void Global_Physical_Variables::prescribed_traction (const double &t, const Vector< double > &x, const Vector< double > &n, Vector< double > &traction)
Traction applied on the fluid at the left (inflow) boundary.
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
Driver code for an unsteady adaptive collapsible channel problem with prescribed wall motion. Presence of command line arguments indicates validation run with coarse resolution and small number of timesteps.
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Reduction in resolution for validation run?
  unsigned coarsening_factor=1;
  if (CommandLineArgs::Argc>1)
   {
    coarsening_factor=4;
   }
  // Number of elements in the domain
  unsigned nup=20/coarsening_factor;
  unsigned ncollapsible=40/coarsening_factor;
  unsigned ndown=40/coarsening_factor;
  unsigned ny=16/coarsening_factor;
  // Length of the domain
  double lup=5.0;
  double lcollapsible=10.0;
  double ldown=10.0;
  double ly=1.0;
  // Initial amplitude of the wall deformation
  double amplitude=1.0e-2; // ADJUST
  // Period of oscillation
  double period=0.45;
  // Pressure/applied traction on the left boundary: This is consistent with
  // steady Poiseuille flow
  Global_Physical_Variables::P_up=12.0*(lup+lcollapsible+ldown);
  //Set output directory
  DocInfo doc_info;
  doc_info.set_directory("RESLT");
  // Open a trace file
  ofstream trace_file;
  char filename[100];
  sprintf(filename,"%s/trace.dat",doc_info.directory().c_str());
  trace_file.open(filename);
 #ifdef ADAPTIVE
  // Build the problem with Crouzeix Raviart Element
  CollapsibleChannelProblem<AlgebraicElement<RefineableQCrouzeixRaviartElement<2> > >
   problem(nup, ncollapsible, ndown, ny,
           lup, lcollapsible, ldown, ly,
           amplitude,period);
 #else
  // Build the problem with Crouzeix Raviart Element
  CollapsibleChannelProblem<AlgebraicElement<QCrouzeixRaviartElement<2> > >
   problem(nup, ncollapsible, ndown, ny,
           lup, lcollapsible, ldown, ly,
           amplitude,period);
 #endif
  // Number of timesteps per period
  unsigned nsteps_per_period=40;
  // Number of periods
  unsigned nperiod=3;
  // Number of timesteps (reduced for validation)
  unsigned nstep=nsteps_per_period*nperiod;
  if (CommandLineArgs::Argc>1)
   {
    nstep=3;
   }
  //Timestep:
  double dt=period/double(nsteps_per_period);
  // Start time
  double t_min=0.0;
  // Initialise timestep and set initial conditions
  problem.time_pt()->time()=t_min;
  problem.initialise_dt(dt);
  problem.set_initial_condition();
   // Output the initial solution
  problem.doc_solution(doc_info, trace_file);
  // Step number
  doc_info.number()++;
 #ifdef ADAPTIVE
  // Set targets for spatial adaptivity
  problem.bulk_mesh_pt()->max_permitted_error()=1.0e-3;
  problem.bulk_mesh_pt()->min_permitted_error()=1.0e-5;
  // Overwrite with reduced targets for validation run to force
  // some refinement during the first few timesteps
  if (CommandLineArgs::Argc>1)
   {
    problem.bulk_mesh_pt()->max_permitted_error()=1.0e-4;
    problem.bulk_mesh_pt()->min_permitted_error()=1.0e-6;
   }
  // First timestep: We may re-assign the initial condition
  // following any mesh adaptation.
  bool first=true;
  // Max. number of adaptations during first timestep
  unsigned max_adapt=10;
 #endif
  // Timestepping loop
  for (unsigned istep=0;istep<nstep;istep++)
   {
 #ifdef ADAPTIVE
    // Solve the problem
    problem.unsteady_newton_solve(dt, max_adapt, first);
 #else
    // Solve the problem
    problem.unsteady_newton_solve(dt);
 #endif
    // Outpt the solution
    problem.doc_solution(doc_info, trace_file);
    // Step number
    doc_info.number()++;
 #ifdef ADAPTIVE
    // We've done one step: Don't re-assign the initial conditions
    // and limit the number of adaptive mesh refinements to one
    // per timestep.
    first=false;
    max_adapt=1;
 #endif
   }
  trace_file.close();
 } //end of driver code
References oomph::CommandLineArgs::Argc, oomph::DocInfo::directory(), MergeRestartFiles::filename, Mesh_Parameters::ly, oomph::DocInfo::number(), Mesh_Parameters::ny, Global_Physical_Variables::P_up, problem, oomph::DocInfo::set_directory(), and Flag_definition::setup().