MercuryDPM: turek_flag_non_fsi.cc File Reference
turek_flag_non_fsi.cc File Reference
#include "generic.h"
#include "navier_stokes.h"
#include "meshes/cylinder_with_flag_mesh.h"
Classes
class Flag_definition::TopOfFlag
GeomObject that defines the upper boundary of the flag.
class Flag_definition::BottomOfFlag
GeomObject that defines the lower boundary of the flag.
class Flag_definition::TipOfFlag
GeomObject that defines the tip of the flag.
class TurekNonFSIProblem< ELEMENT >
Flow around a cylinder with flag.
Namespaces
Global_Parameters
Namespace for global parameters.
Flag_definition
Namespace for definition of flag boundaries.
Functions
Vector< double > Flag_definition::upper_tip (const double &t)
Time-dependent vector to upper tip of the "flag".
Vector< double > Flag_definition::lower_tip (const double &t)
Time-dependent vector to bottom tip of the "flag".
void Flag_definition::setup (Time *time_pt)
Create all GeomObjects needed to define the cylinder and the flag.
int main (int argc, char *argv[])
Variables
double Flag_definition::Period =10.0
Period of prescribed flag oscillation.
double Flag_definition::H =0.2
Height of flag.
double Flag_definition::L =3.5
Length of flag.
double Flag_definition::Centre_x =2.0
x position of centre of cylinder
double Flag_definition::Centre_y =2.0
y position of centre of cylinder
double Flag_definition::Radius =0.5
Radius of cylinder.
double Flag_definition::Amplitude =0.33
Amplitude of tip deflection.
Time * Flag_definition::Time_pt =0
Pointer to the global time object.
TopOfFlag * Flag_definition::Top_flag_pt =0
Pointer to GeomObject that bounds the upper edge of the flag.
BottomOfFlag * Flag_definition::Bottom_flag_pt =0
Pointer to GeomObject that bounds the bottom edge of the flag.
TipOfFlag * Flag_definition::Tip_flag_pt =0
Pointer to GeomObject that bounds the tip edge of the flag.
Circle * Flag_definition::Cylinder_pt =0
Function Documentation
main()
int main (int argc , char * argv[])
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// Driver code – pass a command line argument if you want to run the code in validation mode where it only performs a few steps
Initialise timestep
Output intial guess for steady Newton solve
Output steady solution = initial condition for subsequent unsteady solve
Reduce the max number of adaptations for time-dependent simulation
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Set up doc info
  DocInfo doc_info;
  doc_info.set_directory("RESLT");
  doc_info.number()=0;
  // Length and height of domain
  double length=25.0;
  double height=4.1;
 #ifdef USE_MACRO_ELEMENTS
  // Create Problem with Domain/MacroElement-based node update
  TurekNonFSIProblem<RefineableQCrouzeixRaviartElement<2> >
   problem(length,height);
 #else
  // Create Problem with AlgebraicMesh-based node update
  TurekNonFSIProblem
   <AlgebraicElement<RefineableQCrouzeixRaviartElement<2> > >
   problem(length, height);
 #endif
 // Number of timesteps per period
  unsigned nsteps_per_period=40;
  // Number of periods
  unsigned nperiod=3;
  // Number of timesteps  (reduced for validation)
  unsigned nstep=nsteps_per_period*nperiod;
  if (CommandLineArgs::Argc>1)
   {
    nstep=2;
    // Also reduce the Reynolds number to reduce the mesh refinement
    Global_Parameters::Re=10.0;
   }
  //Timestep:
  double dt=Flag_definition::Period/double(nsteps_per_period);
  problem.initialise_dt(dt);
  // Solve adaptively with up to max_adapt rounds of refinement (fewer if
  // run during self-test)
  unsigned max_adapt=3;
  if (CommandLineArgs::Argc>1)
   {
    max_adapt=1;
   }
  problem.doc_solution(doc_info);
  doc_info.number()++;
  // Do steady solve first -- this also sets the history values
  // to those corresponding to an impulsive start from the
  // steady solution
  problem.steady_newton_solve(max_adapt);
  problem.doc_solution(doc_info);
  doc_info.number()++;
  max_adapt=1;
  // We don't want to re-assign the initial condition after the mesh
  // adaptation
  bool first=false;
 // Timestepping loop
  for (unsigned istep=0;istep<nstep;istep++)
   {
    // Solve the problem
    problem.unsteady_newton_solve(dt,max_adapt,first);
    // Output the solution
    problem.doc_solution(doc_info);
    // Step number
    doc_info.number()++;
   }
 }//end of main
References oomph::CommandLineArgs::Argc, Global_Physical_Variables::height(), oomph::DocInfo::number(), Flag_definition::Period, problem, Global_Parameters::Re, oomph::DocInfo::set_directory(), and Flag_definition::setup().