MercuryDPM: oomph::TreeForest Class Reference
oomph::TreeForest Class Reference abstract
#include <tree.h>
Public Member Functions
TreeForest (Vector< TreeRoot * > &trees_pt)
TreeForest ()
Default constructor (empty and broken)
TreeForest (const TreeForest &dummy)=delete
Broken copy constructor.
void operator= (const TreeForest &)=delete
Broken assignment operator.
virtual ~TreeForest ()
Kill tree forest: Delete the constituent trees.
void stick_leaves_into_vector (Vector< Tree * > &forest_nodes)
Traverse forst and stick pointers to leaf "nodes" into Vector.
void stick_all_tree_nodes_into_vector (Vector< Tree * > &all_forest_nodes)
Traverse forest and stick pointers to all "nodes" into Vector.
virtual void check_all_neighbours (DocInfo &doc_info)=0
virtual void open_hanging_node_files (DocInfo &doc_info, Vector< std::ofstream * > &output_stream)=0
void close_hanging_node_files (DocInfo &doc_info, Vector< std::ofstream * > &output_stream)
unsigned ntree ()
Number of trees in forest.
TreeRoot * tree_pt (const unsigned &i) const
Return pointer to i-th tree in forest.
void flush_trees ()
Flush trees from forest.
Protected Attributes
Vector< TreeRoot * > Trees_pt
Vector containing the pointers to the trees.
Detailed Description
A TreeForest consists of a collection of TreeRoots. Each member tree can have neighbours in various enumerated directions (e.g. S/W/N/E for a QuadTreeForest) and the orientation of their compasses can differ, allowing for complex, unstructured meshes.
Constructor & Destructor Documentation
TreeForest() [1/3]
oomph::TreeForest::TreeForest (Vector< TreeRoot * > & trees_pt)
Constructor for Tree forest: Pass Vector of (pointers to) constituents trees.
Constructor for TreeForest:
Pass:
trees_pt[], the Vector of pointers to the constituent trees (TreeRoot objects)
Note that the pointers to the neighbour's of each tree must have been allocated before the constructor is called, otherwise the relative rotation scheme will not be constructed correctly.
 : Trees_pt(trees_pt) {}
TreeForest() [2/3]
oomph::TreeForest::TreeForest () inline
Default constructor (empty and broken)
     {
       // Throw an error
       throw OomphLibError(
         "Don't call an empty constructor for a TreeForest object",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
TreeForest() [3/3]
oomph::TreeForest::TreeForest (const TreeForest & dummy) delete
Broken copy constructor.
~TreeForest()
oomph::TreeForest::~TreeForest () virtual
Kill tree forest: Delete the constituent trees.
Destructor: Delete the constituent trees (and thus the objects associated with its non-leaf nodes!)
   {
     long int numtrees = Trees_pt.size();
     for (long int i = 0; i < numtrees; i++)
     {
       // Kill the trees
       delete Trees_pt[i];
       Trees_pt[i] = 0;
     }
   }
References i, and Trees_pt.
Member Function Documentation
check_all_neighbours()
virtual void oomph::TreeForest::check_all_neighbours (DocInfo & doc_info) pure virtual
Document/check the neighbours of all the nodes in the forest. This must be overloaded for different types of forest.
Implemented in oomph::QuadTreeForest, oomph::OcTreeForest, and oomph::BinaryTreeForest.
Referenced by oomph::TreeBasedRefineableMeshBase::adapt_mesh(), and oomph::TreeBasedRefineableMeshBase::p_adapt_mesh().
close_hanging_node_files()
void oomph::TreeForest::close_hanging_node_files (DocInfo & doc_info, Vector< std::ofstream * > & output_stream)
Close output files that will store any hanging nodes in the forest and delete any associated storage. This can be performed genercially in this base class.
Close the hanging node output files and delete storage allocated at the pointers. This can be done generically at the base level
   {
     // Find the number of files
     unsigned n_file = output_stream.size();
     // If we opened the files, close them
     if (doc_info.is_doc_enabled())
     {
       for (unsigned n = 0; n < n_file; n++)
       {
         output_stream[n]->close();
       }
     }
     // We should have always created ofstreams, so delete them and null out
     for (unsigned n = n_file; n > 0; n--)
     {
       delete output_stream[n - 1];
       output_stream[n - 1] = 0;
     }
     // Finally clear out the vector
     output_stream.clear();
   }
References oomph::DocInfo::is_doc_enabled(), and n.
Referenced by oomph::TreeBasedRefineableMeshBase::adapt_mesh(), and oomph::TreeBasedRefineableMeshBase::p_adapt_mesh().
flush_trees()
void oomph::TreeForest::flush_trees () inline
Flush trees from forest.
     {
       // Clear Trees_pt vector
       Trees_pt.clear();
     }
References Trees_pt.
Referenced by oomph::RefineableBrickMesh< ELEMENT >::setup_octree_forest(), and oomph::RefineableQuadMesh< ELEMENT >::setup_quadtree_forest().
ntree()
unsigned oomph::TreeForest::ntree () inline
Number of trees in forest.
     {
       return Trees_pt.size();
     }
References Trees_pt.
Referenced by oomph::TreeBasedRefineableMeshBase::adapt_mesh(), oomph::QuadTreeForest::construct_north_equivalents(), oomph::OcTreeForest::construct_up_right_equivalents(), oomph::BinaryTreeForest::find_neighbours(), oomph::OcTreeForest::find_neighbours(), oomph::QuadTreeForest::find_neighbours(), oomph::TreeBasedRefineableMeshBase::p_adapt_mesh(), oomph::TreeBasedRefineableMesh< ELEMENT >::p_refine_elements_if_required(), oomph::TreeBasedRefineableMesh< ELEMENT >::split_elements_if_required(), stick_all_tree_nodes_into_vector(), and stick_leaves_into_vector().
open_hanging_node_files()
virtual void oomph::TreeForest::open_hanging_node_files (DocInfo & doc_info, Vector< std::ofstream * > & output_stream) pure virtual
Open output files that will store any hanging nodes in the forest. Return a vector of the output streams. This is included in the tree structure, so that we can use generic routines for mesh adaptation in two and three dimensions. The need for pointers to the output streams is because one cannot copy a stream!
Implemented in oomph::QuadTreeForest, oomph::OcTreeForest, and oomph::BinaryTreeForest.
Referenced by oomph::TreeBasedRefineableMeshBase::adapt_mesh(), and oomph::TreeBasedRefineableMeshBase::p_adapt_mesh().
operator=()
void oomph::TreeForest::operator= (const TreeForest &) delete
Broken assignment operator.
stick_all_tree_nodes_into_vector()
void oomph::TreeForest::stick_all_tree_nodes_into_vector (Vector< Tree * > & all_forest_nodes)
Traverse forest and stick pointers to all "nodes" into Vector.
Traverse TreeForest: Preorder traverse and stick pointers to all nodes into Vector
   {
     unsigned numtrees = ntree();
     for (unsigned itree = 0; itree < numtrees; itree++)
     {
       all_forest_nodes.push_back(tree_pt(itree));
       // Now do the sons (if they exist)
       unsigned numsons = tree_pt(itree)->nsons();
       if (numsons > 0)
       {
         // Now do the sons (if they exist)
         for (unsigned i = 0; i < numsons; i++)
         {
           tree_pt(itree)->son_pt(i)->stick_all_tree_nodes_into_vector(
             all_forest_nodes);
         }
       }
     }
   }
References i, oomph::Tree::nsons(), ntree(), oomph::Tree::son_pt(), oomph::Tree::stick_all_tree_nodes_into_vector(), and tree_pt().
Referenced by oomph::TreeBasedRefineableMeshBase::adapt_mesh(), oomph::BinaryTreeForest::check_all_neighbours(), oomph::OcTreeForest::check_all_neighbours(), oomph::QuadTreeForest::check_all_neighbours(), oomph::TreeBasedRefineableMeshBase::get_elements_at_refinement_level(), oomph::TreeBasedRefineableMeshBase::get_refinement_pattern(), oomph::TreeBasedRefineableMeshBase::p_adapt_mesh(), oomph::BinaryTreeForest::self_test(), oomph::OcTreeForest::self_test(), oomph::QuadTreeForest::self_test(), oomph::RefineableBrickMesh< ELEMENT >::setup_octree_forest(), and oomph::RefineableQuadMesh< ELEMENT >::setup_quadtree_forest().
stick_leaves_into_vector()
void oomph::TreeForest::stick_leaves_into_vector (Vector< Tree * > & forest_nodes)
Traverse forst and stick pointers to leaf "nodes" into Vector.
Traverse TreeForest: Preorder traverse and stick pointers to leaf nodes (only) into Vector
   {
     unsigned numtrees = ntree();
     for (unsigned itree = 0; itree < numtrees; itree++)
     {
       // Now do the sons (if they exist)
       unsigned numsons = tree_pt(itree)->nsons();
       if (numsons > 0)
       {
         for (unsigned i = 0; i < numsons; i++)
         {
           tree_pt(itree)->son_pt(i)->stick_leaves_into_vector(forest_nodes);
         }
       }
       else
       {
         forest_nodes.push_back(tree_pt(itree));
       }
     }
   }
References i, oomph::Tree::nsons(), ntree(), oomph::Tree::son_pt(), oomph::Tree::stick_leaves_into_vector(), and tree_pt().
Referenced by oomph::TreeBasedRefineableMeshBase::adapt_mesh(), oomph::TreeBasedRefineableMeshBase::p_adapt_mesh(), and oomph::TreeBasedRefineableMeshBase::refine_as_in_reference_mesh().
tree_pt()
TreeRoot* oomph::TreeForest::tree_pt (const unsigned & i) const inline
Return pointer to i-th tree in forest.
     {
       return Trees_pt[i];
     }
References i, and Trees_pt.
Referenced by oomph::TreeBasedRefineableMeshBase::adapt_mesh(), oomph::TreeBasedRefineableMeshBase::p_adapt_mesh(), oomph::TreeBasedRefineableMesh< ELEMENT >::p_refine_elements_if_required(), oomph::TreeBasedRefineableMesh< ELEMENT >::split_elements_if_required(), stick_all_tree_nodes_into_vector(), and stick_leaves_into_vector().
Member Data Documentation
Trees_pt
Vector<TreeRoot*> oomph::TreeForest::Trees_pt protected
Vector containing the pointers to the trees.
Referenced by oomph::OcTreeForest::construct_up_right_equivalents(), oomph::BinaryTreeForest::find_neighbours(), oomph::OcTreeForest::find_neighbours(), oomph::QuadTreeForest::find_neighbours(), flush_trees(), ntree(), tree_pt(), and ~TreeForest().
The documentation for this class was generated from the following files:
tree.h
tree.cc