MercuryDPM: Eigen::internal::CoeffLoader< Tensor, true, MakePointer_ > Struct Template Reference
Eigen::internal::CoeffLoader< Tensor, true, MakePointer_ > Struct Template Reference
#include <TensorContractionMapper.h>
Public Types
enum { DirectOffsets = true }
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE CoeffLoader (const Tensor &tensor)
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE void offsetBuffer (typename Tensor::Index offset)
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE const MakePointer_< const typename Tensor::Scalar >::Type data () const
EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE Tensor::Scalar coeff (typename Tensor::Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Tensor::PacketReturnType packet (typename Tensor::Index index) const
Private Types
typedef Tensor::Scalar Scalar
Private Attributes
MakePointer_< const Scalar >::Type m_data
Member Typedef Documentation
Scalar
template<typename Tensor , template< class > class MakePointer_> typedef Tensor::Scalar Eigen::internal::CoeffLoader< Tensor, true, MakePointer_ >::Scalar private
Member Enumeration Documentation
anonymous enum
template<typename Tensor , template< class > class MakePointer_> anonymous enum
Enumerator
DirectOffsets
 { DirectOffsets = true };
Constructor & Destructor Documentation
CoeffLoader()
template<typename Tensor , template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE Eigen::internal::CoeffLoader< Tensor, true, MakePointer_ >::CoeffLoader (const Tensor & tensor) inline
 : m_data(tensor.data()) {}
Member Function Documentation
coeff()
template<typename Tensor , template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE Tensor::Scalar Eigen::internal::CoeffLoader< Tensor, true, MakePointer_ >::coeff (typename Tensor::Index index) const inline
{
     return loadConstant(m_data + index);
   }
References Eigen::internal::loadConstant().
data()
template<typename Tensor , template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE const MakePointer_<const typename Tensor::Scalar>::Type Eigen::internal::CoeffLoader< Tensor, true, MakePointer_ >::data () const inline
{
     return m_data;
   }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
offsetBuffer()
template<typename Tensor , template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_ALWAYS_INLINE void Eigen::internal::CoeffLoader< Tensor, true, MakePointer_ >::offsetBuffer (typename Tensor::Index offset) inline
 { m_data += offset; }
packet()
template<typename Tensor , template< class > class MakePointer_> template<int LoadMode> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Tensor::PacketReturnType Eigen::internal::CoeffLoader< Tensor, true, MakePointer_ >::packet (typename Tensor::Index index) const inline
{
     return internal::ploadt_ro<typename Tensor::PacketReturnType, LoadMode>(m_data + index);
   }
Member Data Documentation
m_data
template<typename Tensor , template< class > class MakePointer_> MakePointer_<const Scalar>::Type Eigen::internal::CoeffLoader< Tensor, true, MakePointer_ >::m_data private
The documentation for this struct was generated from the following file:
TensorContractionMapper.h