MercuryDPM: oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM > Class Template Reference
oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM > Class Template Reference
#include <generalised_newtonian_constitutive_models.h>
Public Member Functions
HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation (double *yield_stress_pt, double *flow_index_pt, double *critical_second_invariant_pt)
"Cutoff regularised" Herschel Bulkley constitutive equation
double calculate_cutoff_viscosity ()
double calculate_zero_shear_viscosity ()
Function that calculates the viscosity at zero I2.
void report_cut_off_values (double &cut_off_invariant, double &cut_off_viscosity, double &zero_shear_viscosity)
Report cutoff values.
double viscosity (const double &second_invariant_of_rate_of_strain_tensor)
Viscosity ratio as a fct of strain rate invariant.
double dviscosity_dinvariant (const double &second_invariant_of_rate_of_strain_tensor)
Deriv of viscosity w.r.t. strain rate invariant.
Public Member Functions inherited from oomph::GeneralisedNewtonianConstitutiveEquation< DIM >
GeneralisedNewtonianConstitutiveEquation ()
Empty constructor.
virtual ~GeneralisedNewtonianConstitutiveEquation ()
Empty virtual destructor.
Private Attributes
double * Yield_stress_pt
yield stress tau_y
double * Flow_index_pt
power law index n
double * Critical_second_invariant_pt
double a
double b
double c
double alpha
Detailed Description
template<unsigned DIM>
class oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >
A GeneralisedNewtonianConstitutiveEquation class defining a Herschel-Bulkley fluid using Tanner and Milthorpe's (1983) regularisation with a smooth transition using a quadratic
Constructor & Destructor Documentation
HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation()
template<unsigned DIM> oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation (double * yield_stress_pt, double * flow_index_pt, double * critical_second_invariant_pt) inline
"Cutoff regularised" Herschel Bulkley constitutive equation
Blend over one order of magnitude
Calculate the coefficients of the quadratic equation
get the cutoff viscosity
get the zero shear viscosity
       : GeneralisedNewtonianConstitutiveEquation<DIM>(),
         Yield_stress_pt(yield_stress_pt),
         Flow_index_pt(flow_index_pt),
         Critical_second_invariant_pt(critical_second_invariant_pt),
         a(0.0),
         b(0.0),
         c(0.0)
     {
       alpha = 0.1;
       if (fabs(*Critical_second_invariant_pt) > 0.0)
       {
         a = (pow(2.0, *Flow_index_pt - 3.0) * (*Flow_index_pt - 1.0) *
                pow(fabs(*Critical_second_invariant_pt),
                    (*Flow_index_pt - 1.0) / 2.0 - 2.0) -
              (*Yield_stress_pt) /
                (8.0 * pow(fabs(*Critical_second_invariant_pt), 5.0 / 2.0))) /
             (1.0 - alpha);
         b = -2.0 * a * alpha * fabs(*Critical_second_invariant_pt);
         c = (*Yield_stress_pt) /
               (2.0 * sqrt(fabs(*Critical_second_invariant_pt))) +
             pow(2.0 * sqrt(fabs(*Critical_second_invariant_pt)),
                 *Flow_index_pt - 1.0) -
             a * pow(fabs(*Critical_second_invariant_pt), 2.0) -
             b * fabs(*Critical_second_invariant_pt);
       }
       double cut_off_viscosity = calculate_cutoff_viscosity();
       double zero_shear_viscosity = calculate_zero_shear_viscosity();
       oomph_info << "HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation: "
                  << " zero shear viscosity = " << zero_shear_viscosity
                  << std::endl;
       oomph_info << "HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation: "
                  << " cut off viscosity = " << cut_off_viscosity << std::endl;
       oomph_info << "                                              "
                  << " cutoff invariant = " << *Critical_second_invariant_pt
                  << std::endl;
     }
References oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::a, oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::alpha, oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::b, oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::c, oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_cutoff_viscosity(), oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_zero_shear_viscosity(), oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::Critical_second_invariant_pt, boost::multiprecision::fabs(), oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::Flow_index_pt, oomph::oomph_info, Eigen::bfloat16_impl::pow(), and sqrt().
Member Function Documentation
calculate_cutoff_viscosity()
template<unsigned DIM> double oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_cutoff_viscosity () inline
Function that calculates the viscosity at the cutoff invariant Note: this is NOT the viscosity at zero I2
     {
       // Calculate the Newtonian cutoff viscosity from the constitutive
       // equation and the cutoff value of the second invariant
       return (*Yield_stress_pt) /
                (2.0 * sqrt(std::max(fabs(*Critical_second_invariant_pt),
                                     DBL_EPSILON))) +
              pow((2.0 * sqrt(std::max(fabs(*Critical_second_invariant_pt),
                                       DBL_EPSILON))),
                  *Flow_index_pt - 1.0);
     }
References oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::Critical_second_invariant_pt, boost::multiprecision::fabs(), oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::Flow_index_pt, max, Eigen::bfloat16_impl::pow(), sqrt(), and oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::Yield_stress_pt.
Referenced by oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_zero_shear_viscosity(), oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation(), and oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::report_cut_off_values().
calculate_zero_shear_viscosity()
template<unsigned DIM> double oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_zero_shear_viscosity () inline
Function that calculates the viscosity at zero I2.
     {
       // The maximum of either the viscosity at alpha*cut-off or the cut-off
       // viscosity for a cut-off of zero
       return std::max(a * pow(alpha, 2.0) *
                           pow(fabs(*Critical_second_invariant_pt), 2.0) +
                         b * alpha * fabs(*Critical_second_invariant_pt) + c,
                       calculate_cutoff_viscosity());
     }
References oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::a, oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::alpha, oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::b, oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::c, oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_cutoff_viscosity(), oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::Critical_second_invariant_pt, boost::multiprecision::fabs(), max, and Eigen::bfloat16_impl::pow().
Referenced by oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation(), oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::report_cut_off_values(), and oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::viscosity().
dviscosity_dinvariant()
template<unsigned DIM> double oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::dviscosity_dinvariant (const double & second_invariant_of_rate_of_strain_tensor) inline virtual
Deriv of viscosity w.r.t. strain rate invariant.
Implements oomph::GeneralisedNewtonianConstitutiveEquation< DIM >.
     {
       if (fabs(second_invariant_of_rate_of_strain_tensor) <
           alpha * fabs(*Critical_second_invariant_pt))
       {
         return 0.0;
       }
       else if (fabs(second_invariant_of_rate_of_strain_tensor) <
                fabs(*Critical_second_invariant_pt))
       {
         return 2.0 * a * fabs(second_invariant_of_rate_of_strain_tensor) + b;
       }
       return pow(2.0, *Flow_index_pt - 2.0) * (*Flow_index_pt - 1.0) *
                pow(fabs(second_invariant_of_rate_of_strain_tensor),
                    (*Flow_index_pt - 1.0) / 2.0 - 1.0) -
              (*Yield_stress_pt) /
                (4.0 * pow(fabs(second_invariant_of_rate_of_strain_tensor),
                           3.0 / 2.0));
     }
References oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::a, oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::alpha, oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::b, oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::Critical_second_invariant_pt, boost::multiprecision::fabs(), oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::Flow_index_pt, and Eigen::bfloat16_impl::pow().
report_cut_off_values()
template<unsigned DIM> void oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::report_cut_off_values (double & cut_off_invariant, double & cut_off_viscosity, double & zero_shear_viscosity) inline
Report cutoff values.
     {
       cut_off_invariant = *Critical_second_invariant_pt;
       cut_off_viscosity = calculate_cutoff_viscosity();
       zero_shear_viscosity = calculate_zero_shear_viscosity();
     }
References oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_cutoff_viscosity(), oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_zero_shear_viscosity(), and oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::Critical_second_invariant_pt.
viscosity()
template<unsigned DIM> double oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::viscosity (const double & second_invariant_of_rate_of_strain_tensor) inline virtual
Viscosity ratio as a fct of strain rate invariant.
Implements oomph::GeneralisedNewtonianConstitutiveEquation< DIM >.
     {
       if (fabs(second_invariant_of_rate_of_strain_tensor) <
           alpha * fabs(*Critical_second_invariant_pt))
       {
         return calculate_zero_shear_viscosity();
       }
       else if (fabs(second_invariant_of_rate_of_strain_tensor) <
                fabs(*Critical_second_invariant_pt))
       {
         return a * pow(fabs(second_invariant_of_rate_of_strain_tensor), 2.0) +
                b * fabs(second_invariant_of_rate_of_strain_tensor) + c;
       }
       return (*Yield_stress_pt) /
                (2.0 * sqrt(fabs(second_invariant_of_rate_of_strain_tensor))) +
              pow(2.0 * sqrt(fabs(second_invariant_of_rate_of_strain_tensor)),
                  *Flow_index_pt - 1.0);
     }
References oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::a, oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::alpha, oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::b, oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::c, oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_zero_shear_viscosity(), oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::Critical_second_invariant_pt, boost::multiprecision::fabs(), oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::Flow_index_pt, Eigen::bfloat16_impl::pow(), sqrt(), and oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::Yield_stress_pt.
Member Data Documentation
a
template<unsigned DIM> double oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::a private
We use a quadratic function to smoothly blend from the Herschel Bulkley model at the cut-off to a constant viscosity as the strain rate /approaches zero; this way we avoid the discontinuity of the gradient at the cut-off, which is present in the classic Tanner Milthorpe regularisation
Referenced by oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_zero_shear_viscosity(), oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::dviscosity_dinvariant(), oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation(), and oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::viscosity().
alpha
template<unsigned DIM> double oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::alpha private
Fraction of the cut-off strain rate below which the viscosity is constant 0 <= \alpha < 1
Referenced by oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_zero_shear_viscosity(), oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::dviscosity_dinvariant(), oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation(), and oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::viscosity().
b
template<unsigned DIM> double oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::b private
Referenced by oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_zero_shear_viscosity(), oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::dviscosity_dinvariant(), oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation(), and oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::viscosity().
c
template<unsigned DIM> double oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::c private
Referenced by oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_zero_shear_viscosity(), oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation(), and oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::viscosity().
Critical_second_invariant_pt
template<unsigned DIM> double* oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::Critical_second_invariant_pt private
value of the second invariant below which we have constant (Newtonian) viscosity – assumed to be always positive
Referenced by oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_cutoff_viscosity(), oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_zero_shear_viscosity(), oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::dviscosity_dinvariant(), oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation(), oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::report_cut_off_values(), and oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::viscosity().
Flow_index_pt
template<unsigned DIM> double* oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::Flow_index_pt private
power law index n
Referenced by oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_cutoff_viscosity(), oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::dviscosity_dinvariant(), oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation(), and oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::viscosity().
Yield_stress_pt
template<unsigned DIM> double* oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::Yield_stress_pt private
yield stress tau_y
Referenced by oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::calculate_cutoff_viscosity(), and oomph::HerschelBulkleyTanMilRegWithBlendingConstitutiveEquation< DIM >::viscosity().
The documentation for this class was generated from the following file:
generalised_newtonian_constitutive_models.h