MercuryDPM: Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 3, false > Struct Template Reference
Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 3, false > Struct Template Reference
#include <SelfAdjointEigenSolver.h>
Public Types
typedef SolverType::MatrixType MatrixType
typedef SolverType::RealVectorType VectorType
typedef SolverType::Scalar Scalar
typedef SolverType::EigenvectorsType EigenvectorsType
Static Public Member Functions
static EIGEN_DEVICE_FUNC void computeRoots (const MatrixType &m, VectorType &roots)
static EIGEN_DEVICE_FUNC bool extract_kernel (MatrixType &mat, Ref< VectorType > res, Ref< VectorType > representative)
static EIGEN_DEVICE_FUNC void run (SolverType &solver, const MatrixType &mat, int options)
Member Typedef Documentation
EigenvectorsType
template<typename SolverType > typedef SolverType::EigenvectorsType Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 3, false >::EigenvectorsType
MatrixType
template<typename SolverType > typedef SolverType::MatrixType Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 3, false >::MatrixType
Scalar
template<typename SolverType > typedef SolverType::Scalar Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 3, false >::Scalar
VectorType
template<typename SolverType > typedef SolverType::RealVectorType Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 3, false >::VectorType
Member Function Documentation
computeRoots()
template<typename SolverType > static EIGEN_DEVICE_FUNC void Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 3, false >::computeRoots (const MatrixType & m, VectorType & roots) inline static
Computes the roots of the characteristic polynomial of m. For numerical stability m.trace() should be near zero and to avoid over- or underflow m should be normalized.
{
     EIGEN_USING_STD(sqrt)
     EIGEN_USING_STD(atan2)
     EIGEN_USING_STD(cos)
     EIGEN_USING_STD(sin)
     const Scalar s_inv3 = Scalar(1) / Scalar(3);
     const Scalar s_sqrt3 = sqrt(Scalar(3));
     // The characteristic equation is x^3 - c2*x^2 + c1*x - c0 = 0.  The
     // eigenvalues are the roots to this equation, all guaranteed to be
     // real-valued, because the matrix is symmetric.
     Scalar c0 = m(0, 0) * m(1, 1) * m(2, 2) + Scalar(2) * m(1, 0) * m(2, 0) * m(2, 1) - m(0, 0) * m(2, 1) * m(2, 1) -
                 m(1, 1) * m(2, 0) * m(2, 0) - m(2, 2) * m(1, 0) * m(1, 0);
     Scalar c1 = m(0, 0) * m(1, 1) - m(1, 0) * m(1, 0) + m(0, 0) * m(2, 2) - m(2, 0) * m(2, 0) + m(1, 1) * m(2, 2) -
                 m(2, 1) * m(2, 1);
     Scalar c2 = m(0, 0) + m(1, 1) + m(2, 2);
     // Construct the parameters used in classifying the roots of the equation
     // and in solving the equation for the roots in closed form.
     Scalar c2_over_3 = c2 * s_inv3;
     Scalar a_over_3 = (c2 * c2_over_3 - c1) * s_inv3;
     a_over_3 = numext::maxi(a_over_3, Scalar(0));
     Scalar half_b = Scalar(0.5) * (c0 + c2_over_3 * (Scalar(2) * c2_over_3 * c2_over_3 - c1));
     Scalar q = a_over_3 * a_over_3 * a_over_3 - half_b * half_b;
     q = numext::maxi(q, Scalar(0));
     // Compute the eigenvalues by solving for the roots of the polynomial.
     Scalar rho = sqrt(a_over_3);
     Scalar theta = atan2(sqrt(q), half_b) * s_inv3;  // since sqrt(q) > 0, atan2 is in [0, pi] and theta is in [0, pi/3]
     Scalar cos_theta = cos(theta);
     Scalar sin_theta = sin(theta);
     // roots are already sorted, since cos is monotonically decreasing on [0, pi]
     roots(0) = c2_over_3 - rho * (cos_theta + s_sqrt3 * sin_theta);  // == 2*rho*cos(theta+2pi/3)
     roots(1) = c2_over_3 - rho * (cos_theta - s_sqrt3 * sin_theta);  // == 2*rho*cos(theta+ pi/3)
     roots(2) = c2_over_3 + Scalar(2) * rho * cos_theta;
   }
References Eigen::atan2(), cos(), EIGEN_USING_STD, m, Eigen::numext::maxi(), Eigen::numext::q, sin(), sqrt(), and BiharmonicTestFunctions2::theta.
extract_kernel()
template<typename SolverType > static EIGEN_DEVICE_FUNC bool Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 3, false >::extract_kernel (MatrixType & mat, Ref< VectorType > res, Ref< VectorType > representative) inline static
{
     EIGEN_USING_STD(abs);
     EIGEN_USING_STD(sqrt);
     Index i0;
     // Find non-zero column i0 (by construction, there must exist a non zero coefficient on the diagonal):
     mat.diagonal().cwiseAbs().maxCoeff(&i0);
     // mat.col(i0) is a good candidate for an orthogonal vector to the current eigenvector,
     // so let's save it:
     representative = mat.col(i0);
     Scalar n0, n1;
     VectorType c0, c1;
     n0 = (c0 = representative.cross(mat.col((i0 + 1) % 3))).squaredNorm();
     n1 = (c1 = representative.cross(mat.col((i0 + 2) % 3))).squaredNorm();
     if (n0 > n1)
       res = c0 / sqrt(n0);
     else
       res = c1 / sqrt(n1);
     return true;
   }
References abs(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::diagonal(), EIGEN_USING_STD, res, and sqrt().
run()
template<typename SolverType > static EIGEN_DEVICE_FUNC void Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 3, false >::run (SolverType & solver, const MatrixType & mat, int options) inline static
{
     eigen_assert(mat.cols() == 3 && mat.cols() == mat.rows());
     eigen_assert((options & ~(EigVecMask | GenEigMask)) == 0 && (options & EigVecMask) != EigVecMask &&
                  "invalid option parameter");
     bool computeEigenvectors = (options & ComputeEigenvectors) == ComputeEigenvectors;
     EigenvectorsType& eivecs = solver.m_eivec;
     VectorType& eivals = solver.m_eivalues;
     // Shift the matrix to the mean eigenvalue and map the matrix coefficients to [-1:1] to avoid over- and underflow.
     Scalar shift = mat.trace() / Scalar(3);
     // TODO Avoid this copy. Currently it is necessary to suppress bogus values when determining maxCoeff and for
     // computing the eigenvectors later
     MatrixType scaledMat = mat.template selfadjointView<Lower>();
     scaledMat.diagonal().array() -= shift;
     Scalar scale = scaledMat.cwiseAbs().maxCoeff();
     if (scale > 0) scaledMat /= scale;  // TODO for scale==0 we could save the remaining operations
     // compute the eigenvalues
     computeRoots(scaledMat, eivals);
     // compute the eigenvectors
     if (computeEigenvectors) {
       if ((eivals(2) - eivals(0)) <= Eigen::NumTraits<Scalar>::epsilon()) {
         // All three eigenvalues are numerically the same
         eivecs.setIdentity();
       } else {
         MatrixType tmp;
         tmp = scaledMat;
         // Compute the eigenvector of the most distinct eigenvalue
         Scalar d0 = eivals(2) - eivals(1);
         Scalar d1 = eivals(1) - eivals(0);
         Index k(0), l(2);
         if (d0 > d1) {
           numext::swap(k, l);
           d0 = d1;
         }
         // Compute the eigenvector of index k
         {
           tmp.diagonal().array() -= eivals(k);
           // By construction, 'tmp' is of rank 2, and its kernel corresponds to the respective eigenvector.
           extract_kernel(tmp, eivecs.col(k), eivecs.col(l));
         }
         // Compute eigenvector of index l
         if (d0 <= 2 * Eigen::NumTraits<Scalar>::epsilon() * d1) {
           // If d0 is too small, then the two other eigenvalues are numerically the same,
           // and thus we only have to ortho-normalize the near orthogonal vector we saved above.
           eivecs.col(l) -= eivecs.col(k).dot(eivecs.col(l)) * eivecs.col(l);
           eivecs.col(l).normalize();
         } else {
           tmp = scaledMat;
           tmp.diagonal().array() -= eivals(l);
           VectorType dummy;
           extract_kernel(tmp, eivecs.col(l), dummy);
         }
         // Compute last eigenvector from the other two
         eivecs.col(1) = eivecs.col(2).cross(eivecs.col(0)).normalized();
       }
     }
     // Rescale back to the original size.
     eivals *= scale;
     eivals.array() += shift;
     solver.m_info = Success;
     solver.m_isInitialized = true;
     solver.m_eigenvectorsOk = computeEigenvectors;
   }
References Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::cols(), Eigen::ComputeEigenvectors, computeRoots(), eigen_assert, Eigen::EigVecMask, eivals, Eigen::GenEigMask, k, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::rows(), solver, Eigen::Success, Eigen::numext::swap(), and tmp.
The documentation for this struct was generated from the following file:
SelfAdjointEigenSolver.h