MercuryDPM: FreeSurfaceRotationProblem< ELEMENT > Class Template Reference
FreeSurfaceRotationProblem< ELEMENT > Class Template Reference
Entry flow problem in quarter tube domain.
Public Member Functions
FreeSurfaceRotationProblem (DocInfo &doc_info, const double &min_error_target, const double &max_error_target)
Constructor: Pass DocInfo object and target errors.
~FreeSurfaceRotationProblem ()
Destructor (empty)
void actions_after_newton_solve ()
Doc the solution after solve.
void actions_before_newton_solve ()
Update the problem specs before solve.
void actions_before_newton_convergence_check ()
void doc_solution ()
Doc the solution.
AxialSpineQuarterTubeMesh< ELEMENT, SpineSurfaceFluidInterfaceElement< ELEMENT > > * mesh_pt ()
FreeSurfaceRotationProblem (DocInfo &doc_info, const double &min_error_target, const double &max_error_target, const unsigned &hijack_flag)
Constructor: Pass DocInfo object and target errors.
~FreeSurfaceRotationProblem ()
Destructor to clean up memory (empty)
void actions_after_newton_solve ()
Doc the solution after solve.
void actions_before_newton_solve ()
Update the problem specs before solve.
void actions_before_newton_convergence_check ()
void create_volume_constraint_elements ()
Create the volume constraint elements.
void doc_solution ()
Doc the solution.
Public Member Functions inherited from oomph::Problem
virtual void debug_hook_fct (const unsigned &i)
void set_analytic_dparameter (double *const &parameter_pt)
void unset_analytic_dparameter (double *const &parameter_pt)
bool is_dparameter_calculated_analytically (double *const &parameter_pt)
void set_analytic_hessian_products ()
void unset_analytic_hessian_products ()
bool are_hessian_products_calculated_analytically ()
void set_pinned_values_to_zero ()
bool distributed () const
virtual void actions_before_adapt ()
virtual void actions_after_adapt ()
Actions that are to be performed after a mesh adaptation.
OomphCommunicator * communicator_pt ()
access function to the oomph-lib communicator
const OomphCommunicator * communicator_pt () const
access function to the oomph-lib communicator, const version
Problem ()
Problem (const Problem &dummy)=delete
Broken copy constructor.
void operator= (const Problem &)=delete
Broken assignment operator.
virtual ~Problem ()
Virtual destructor to clean up memory.
Mesh *& mesh_pt ()
Return a pointer to the global mesh.
Mesh *const & mesh_pt () const
Return a pointer to the global mesh (const version)
Mesh *& mesh_pt (const unsigned &imesh)
Mesh *const & mesh_pt (const unsigned &imesh) const
Return a pointer to the i-th submesh (const version)
unsigned nsub_mesh () const
Return number of submeshes.
unsigned add_sub_mesh (Mesh *const &mesh_pt)
void flush_sub_meshes ()
void build_global_mesh ()
void rebuild_global_mesh ()
LinearSolver *& linear_solver_pt ()
Return a pointer to the linear solver object.
LinearSolver *const & linear_solver_pt () const
Return a pointer to the linear solver object (const version)
LinearSolver *& mass_matrix_solver_for_explicit_timestepper_pt ()
LinearSolver * mass_matrix_solver_for_explicit_timestepper_pt () const
EigenSolver *& eigen_solver_pt ()
Return a pointer to the eigen solver object.
EigenSolver *const & eigen_solver_pt () const
Return a pointer to the eigen solver object (const version)
Time *& time_pt ()
Return a pointer to the global time object.
Time * time_pt () const
Return a pointer to the global time object (const version).
double & time ()
Return the current value of continuous time.
double time () const
Return the current value of continuous time (const version)
TimeStepper *& time_stepper_pt ()
const TimeStepper * time_stepper_pt () const
TimeStepper *& time_stepper_pt (const unsigned &i)
Return a pointer to the i-th timestepper.
ExplicitTimeStepper *& explicit_time_stepper_pt ()
Return a pointer to the explicit timestepper.
unsigned long set_timestepper_for_all_data (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data=false)
virtual void shift_time_values ()
Shift all values along to prepare for next timestep.
AssemblyHandler *& assembly_handler_pt ()
Return a pointer to the assembly handler object.
AssemblyHandler *const & assembly_handler_pt () const
Return a pointer to the assembly handler object (const version)
double & minimum_dt ()
Access function to min timestep in adaptive timestepping.
double & maximum_dt ()
Access function to max timestep in adaptive timestepping.
unsigned & max_newton_iterations ()
Access function to max Newton iterations before giving up.
void problem_is_nonlinear (const bool &prob_lin)
Access function to Problem_is_nonlinear.
double & max_residuals ()
bool & time_adaptive_newton_crash_on_solve_fail ()
Access function for Time_adaptive_newton_crash_on_solve_fail.
double & newton_solver_tolerance ()
void add_time_stepper_pt (TimeStepper *const &time_stepper_pt)
void set_explicit_time_stepper_pt (ExplicitTimeStepper *const &explicit_time_stepper_pt)
void initialise_dt (const double &dt)
void initialise_dt (const Vector< double > &dt)
Data *& global_data_pt (const unsigned &i)
Return a pointer to the the i-th global data object.
void add_global_data (Data *const &global_data_pt)
void flush_global_data ()
LinearAlgebraDistribution *const & dof_distribution_pt () const
Return the pointer to the dof distribution (read-only)
unsigned long ndof () const
Return the number of dofs.
unsigned ntime_stepper () const
Return the number of time steppers.
unsigned nglobal_data () const
Return the number of global data values.
unsigned self_test ()
Self-test: Check meshes and global data. Return 0 for OK.
void enable_store_local_dof_pt_in_elements ()
void disable_store_local_dof_pt_in_elements ()
unsigned long assign_eqn_numbers (const bool &assign_local_eqn_numbers=true)
void describe_dofs (std::ostream &out= *(oomph_info.stream_pt())) const
void enable_discontinuous_formulation ()
void disable_discontinuous_formulation ()
void get_dofs (DoubleVector &dofs) const
void get_dofs (const unsigned &t, DoubleVector &dofs) const
Return vector of the t'th history value of all dofs.
void set_dofs (const DoubleVector &dofs)
Set the values of the dofs.
void set_dofs (const unsigned &t, DoubleVector &dofs)
Set the history values of the dofs.
void set_dofs (const unsigned &t, Vector< double * > &dof_pt)
void add_to_dofs (const double &lambda, const DoubleVector &increment_dofs)
Add lambda x incremenet_dofs[l] to the l-th dof.
double * global_dof_pt (const unsigned &i)
double & dof (const unsigned &i)
i-th dof in the problem
double dof (const unsigned &i) const
i-th dof in the problem (const version)
double *& dof_pt (const unsigned &i)
Pointer to i-th dof in the problem.
double * dof_pt (const unsigned &i) const
Pointer to i-th dof in the problem (const version)
virtual void get_inverse_mass_matrix_times_residuals (DoubleVector &Mres)
virtual void get_dvaluesdt (DoubleVector &f)
virtual void get_residuals (DoubleVector &residuals)
Get the total residuals Vector for the problem.
virtual void get_jacobian (DoubleVector &residuals, DenseDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CRDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CCDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, SumOfMatrices &jacobian)
void get_fd_jacobian (DoubleVector &residuals, DenseMatrix< double > &jacobian)
Get the full Jacobian by finite differencing.
void get_derivative_wrt_global_parameter (double *const &parameter_pt, DoubleVector &result)
void get_hessian_vector_products (DoubleVectorWithHaloEntries const &Y, Vector< DoubleVectorWithHaloEntries > const &C, Vector< DoubleVectorWithHaloEntries > &product)
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, Vector< DoubleVector > &eigenvector, const bool &steady=true)
Solve the eigenproblem.
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, const bool &steady=true)
virtual void get_eigenproblem_matrices (CRDoubleMatrix &mass_matrix, CRDoubleMatrix &main_matrix, const double &shift=0.0)
void assign_eigenvector_to_dofs (DoubleVector &eigenvector)
Assign the eigenvector passed to the function to the dofs.
void add_eigenvector_to_dofs (const double &epsilon, const DoubleVector &eigenvector)
void store_current_dof_values ()
Store the current values of the degrees of freedom.
void restore_dof_values ()
Restore the stored values of the degrees of freedom.
void enable_jacobian_reuse ()
void disable_jacobian_reuse ()
Disable recycling of Jacobian in Newton iteration.
bool jacobian_reuse_is_enabled ()
Is recycling of Jacobian in Newton iteration enabled?
bool & use_predictor_values_as_initial_guess ()
void newton_solve ()
Use Newton method to solve the problem.
void enable_globally_convergent_newton_method ()
enable globally convergent Newton method
void disable_globally_convergent_newton_method ()
disable globally convergent Newton method
void newton_solve (unsigned const &max_adapt)
void steady_newton_solve (unsigned const &max_adapt=0)
void copy (Problem *orig_problem_pt)
virtual Problem * make_copy ()
virtual void read (std::ifstream &restart_file, bool &unsteady_restart)
virtual void read (std::ifstream &restart_file)
virtual void dump (std::ofstream &dump_file) const
void dump (const std::string &dump_file_name) const
void delete_all_external_storage ()
virtual void symmetrise_eigenfunction_for_adaptive_pitchfork_tracking ()
double * bifurcation_parameter_pt () const
void get_bifurcation_eigenfunction (Vector< DoubleVector > &eigenfunction)
void activate_fold_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const DoubleVector &normalisation, const bool &block_solve=true)
void activate_pitchfork_tracking (double *const &parameter_pt, const DoubleVector &symmetry_vector, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const double &omega, const DoubleVector &null_real, const DoubleVector &null_imag, const bool &block_solve=true)
void deactivate_bifurcation_tracking ()
void reset_assembly_handler_to_default ()
Reset the system to the standard non-augemented state.
double arc_length_step_solve (double *const &parameter_pt, const double &ds, const unsigned &max_adapt=0)
double arc_length_step_solve (Data *const &data_pt, const unsigned &data_index, const double &ds, const unsigned &max_adapt=0)
void reset_arc_length_parameters ()
int & sign_of_jacobian ()
void explicit_timestep (const double &dt, const bool &shift_values=true)
Take an explicit timestep of size dt.
void unsteady_newton_solve (const double &dt)
void unsteady_newton_solve (const double &dt, const bool &shift_values)
void unsteady_newton_solve (const double &dt, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const unsigned &suppress_resolve_after_spatial_adapt_flag, const bool &first, const bool &shift=true)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon, const bool &shift_values)
void assign_initial_values_impulsive ()
void assign_initial_values_impulsive (const double &dt)
void calculate_predictions ()
Calculate predictions.
void enable_mass_matrix_reuse ()
void disable_mass_matrix_reuse ()
bool mass_matrix_reuse_is_enabled ()
Return whether the mass matrix is being reused.
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly (DocInfo &doc_info)
void refine_uniformly_and_prune (DocInfo &doc_info)
void refine_uniformly ()
void refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform refinement for submesh i_mesh with documentation.
void refine_uniformly (const unsigned &i_mesh)
Do uniform refinement for submesh i_mesh without documentation.
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly (DocInfo &doc_info)
void p_refine_uniformly_and_prune (DocInfo &doc_info)
void p_refine_uniformly ()
void p_refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-refinement for submesh i_mesh with documentation.
void p_refine_uniformly (const unsigned &i_mesh)
Do uniform p-refinement for submesh i_mesh without documentation.
void refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const unsigned &i_mesh, const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void refine_selected_elements (const Vector< Vector< RefineableElement * >> &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void p_refine_selected_elements (const Vector< Vector< PRefineableElement * >> &elements_to_be_refined_pt)
unsigned unrefine_uniformly ()
unsigned unrefine_uniformly (const unsigned &i_mesh)
void p_unrefine_uniformly (DocInfo &doc_info)
void p_unrefine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-unrefinement for submesh i_mesh without documentation.
void adapt (unsigned &n_refined, unsigned &n_unrefined)
void adapt ()
void p_adapt (unsigned &n_refined, unsigned &n_unrefined)
void p_adapt ()
void adapt_based_on_error_estimates (unsigned &n_refined, unsigned &n_unrefined, Vector< Vector< double >> &elemental_error)
void adapt_based_on_error_estimates (Vector< Vector< double >> &elemental_error)
void get_all_error_estimates (Vector< Vector< double >> &elemental_error)
void doc_errors (DocInfo &doc_info)
Get max and min error for all elements in submeshes.
void doc_errors ()
Get max and min error for all elements in submeshes.
void enable_info_in_newton_solve ()
void disable_info_in_newton_solve ()
Disable the output of information when in the newton solver.
Public Member Functions inherited from oomph::ExplicitTimeSteppableObject
ExplicitTimeSteppableObject ()
Empty constructor.
ExplicitTimeSteppableObject (const ExplicitTimeSteppableObject &)=delete
Broken copy constructor.
void operator= (const ExplicitTimeSteppableObject &)=delete
Broken assignment operator.
virtual ~ExplicitTimeSteppableObject ()
Empty destructor.
virtual void actions_before_explicit_stage ()
virtual void actions_after_explicit_stage ()
Public Attributes
AxialSpineQuarterTubeMesh< ELEMENT, SpineSurfaceFluidInterfaceElement< ELEMENT > > * Bulk_mesh_pt
Mesh * Volume_computation_mesh_pt
Storage for the elements that compute the enclosed fluid volume.
Mesh * Volume_constraint_mesh_pt
Storage for the volume constraint element.
Public Attributes inherited from oomph::Problem
bool Shut_up_in_newton_solve
Private Attributes
DocInfo Doc_info
Doc info object.
double Volume
The volume of the fluid.
Data * Pext_pt
Data * Traded_pressure_data_pt
Storage for the pressure that is traded for the volume constraint.
Additional Inherited Members
Public Types inherited from oomph::Problem
typedef void(* SpatialErrorEstimatorFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error)
Function pointer for spatial error estimator.
typedef void(* SpatialErrorEstimatorWithDocFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error, DocInfo &doc_info)
Function pointer for spatial error estimator with doc.
Static Public Attributes inherited from oomph::Problem
static bool Suppress_warning_about_actions_before_read_unstructured_meshes
Protected Types inherited from oomph::Problem
enum Assembly_method {
Perform_assembly_using_vectors_of_pairs , Perform_assembly_using_two_vectors , Perform_assembly_using_maps , Perform_assembly_using_lists ,
Perform_assembly_using_two_arrays
}
Enumerated flags to determine which sparse assembly method is used.
Protected Member Functions inherited from oomph::Problem
unsigned setup_element_count_per_dof ()
virtual void sparse_assemble_row_or_column_compressed (Vector< int * > &column_or_row_index, Vector< int * > &row_or_column_start, Vector< double * > &value, Vector< unsigned > &nnz, Vector< double * > &residual, bool compressed_row_flag)
virtual void actions_before_newton_step ()
virtual void actions_after_newton_step ()
virtual void actions_before_implicit_timestep ()
virtual void actions_after_implicit_timestep ()
virtual void actions_after_implicit_timestep_and_error_estimation ()
virtual void actions_before_explicit_timestep ()
Actions that should be performed before each explicit time step.
virtual void actions_after_explicit_timestep ()
Actions that should be performed after each explicit time step.
virtual void actions_before_read_unstructured_meshes ()
virtual void actions_after_read_unstructured_meshes ()
virtual void actions_after_change_in_global_parameter (double *const &parameter_pt)
virtual void actions_after_change_in_bifurcation_parameter ()
virtual void actions_after_parameter_increase (double *const &parameter_pt)
double & dof_derivative (const unsigned &i)
double & dof_current (const unsigned &i)
virtual void set_initial_condition ()
virtual double global_temporal_error_norm ()
unsigned newton_solve_continuation (double *const &parameter_pt)
unsigned newton_solve_continuation (double *const &parameter_pt, DoubleVector &z)
void calculate_continuation_derivatives (double *const &parameter_pt)
void calculate_continuation_derivatives (const DoubleVector &z)
void calculate_continuation_derivatives_fd (double *const &parameter_pt)
bool does_pointer_correspond_to_problem_data (double *const &parameter_pt)
void set_consistent_pinned_values_for_continuation ()
Protected Attributes inherited from oomph::Problem
Vector< Problem * > Copy_of_problem_pt
std::map< double *, bool > Calculate_dparameter_analytic
bool Calculate_hessian_products_analytic
LinearAlgebraDistribution * Dof_distribution_pt
Vector< double * > Dof_pt
Vector of pointers to dofs.
DoubleVectorWithHaloEntries Element_count_per_dof
double Relaxation_factor
double Newton_solver_tolerance
unsigned Max_newton_iterations
Maximum number of Newton iterations.
unsigned Nnewton_iter_taken
Vector< double > Max_res
Maximum residuals at start and after each newton iteration.
double Max_residuals
bool Time_adaptive_newton_crash_on_solve_fail
bool Jacobian_reuse_is_enabled
Is re-use of Jacobian in Newton iteration enabled? Default: false.
bool Jacobian_has_been_computed
bool Problem_is_nonlinear
bool Pause_at_end_of_sparse_assembly
bool Doc_time_in_distribute
unsigned Sparse_assembly_method
unsigned Sparse_assemble_with_arrays_initial_allocation
unsigned Sparse_assemble_with_arrays_allocation_increment
Vector< Vector< unsigned > > Sparse_assemble_with_arrays_previous_allocation
double Numerical_zero_for_sparse_assembly
double FD_step_used_in_get_hessian_vector_products
bool Mass_matrix_reuse_is_enabled
bool Mass_matrix_has_been_computed
bool Discontinuous_element_formulation
double Minimum_dt
Minimum desired dt: if dt falls below this value, exit.
double Maximum_dt
Maximum desired dt.
double DTSF_max_increase
double DTSF_min_decrease
double Minimum_dt_but_still_proceed
bool Scale_arc_length
Boolean to control whether arc-length should be scaled.
double Desired_proportion_of_arc_length
Proportion of the arc-length to taken by the parameter.
double Theta_squared
int Sign_of_jacobian
Storage for the sign of the global Jacobian.
double Continuation_direction
double Parameter_derivative
Storage for the derivative of the global parameter wrt arc-length.
double Parameter_current
Storage for the present value of the global parameter.
bool Use_continuation_timestepper
Boolean to control original or new storage of dof stuff.
unsigned Dof_derivative_offset
unsigned Dof_current_offset
Vector< double > Dof_derivative
Storage for the derivative of the problem variables wrt arc-length.
Vector< double > Dof_current
Storage for the present values of the variables.
double Ds_current
Storage for the current step value.
unsigned Desired_newton_iterations_ds
double Minimum_ds
Minimum desired value of arc-length.
bool Bifurcation_detection
Boolean to control bifurcation detection via determinant of Jacobian.
bool Bisect_to_find_bifurcation
Boolean to control wheter bisection is used to located bifurcation.
bool First_jacobian_sign_change
Boolean to indicate whether a sign change has occured in the Jacobian.
bool Arc_length_step_taken
Boolean to indicate whether an arc-length step has been taken.
bool Use_finite_differences_for_continuation_derivatives
OomphCommunicator * Communicator_pt
The communicator for this problem.
bool Always_take_one_newton_step
double Timestep_reduction_factor_after_nonconvergence
bool Keep_temporal_error_below_tolerance
Static Protected Attributes inherited from oomph::Problem
static ContinuationStorageScheme Continuation_time_stepper
Storage for the single static continuation timestorage object.
Detailed Description
template<class ELEMENT>
class FreeSurfaceRotationProblem< ELEMENT >
Entry flow problem in quarter tube domain.
Constructor & Destructor Documentation
FreeSurfaceRotationProblem() [1/2]
template<class ELEMENT > FreeSurfaceRotationProblem< ELEMENT >::FreeSurfaceRotationProblem (DocInfo & doc_info, const double & min_error_target, const double & max_error_target)
Constructor: Pass DocInfo object and target errors.
Constructor: Pass DocInfo object and error targets.
  : Doc_info(doc_info)
 {
  Data *Pext_pt = new Data(1);
  Pext_pt->pin(0);
  Pext_pt->set_value(0,0.0);
  //Set the contact angle
  const double pi = MathematicalConstants::Pi;
  Global_Physical_Variables::Angle = 0.5*pi;
  Newton_solver_tolerance = 2.0e-5;
  // Setup mesh:
  //------------
  // Create geometric objects: Elliptical tube with half axes = radius = 1.0
  double radius=1.0;
  GeomObject* Wall_pt=new EllipticalTube(radius,radius);
  // Boundaries on object
  Vector<double> xi_lo(2);
  // height of inflow
  xi_lo[0]=0.0;
  // start of Wall_pt
  xi_lo[1]=0.0;
  Vector<double> xi_hi(2);
  // height of outflow
  xi_hi[0]=2.0;
  // end of Wall_pt
  xi_hi[1]=0.5*MathematicalConstants::Pi;
  // # of layers
  unsigned nlayer=1;
  //Radial divider is located half-way along the circumference
  double frac_mid=0.5;
  // Build and assign mesh
  Problem::mesh_pt()=
   new AxialSpineQuarterTubeMesh<ELEMENT,SpineSurfaceFluidInterfaceElement<ELEMENT> >
   (Wall_pt,xi_lo,frac_mid,xi_hi,nlayer);
  // Set error estimator
  Z2ErrorEstimator* error_estimator_pt=new Z2ErrorEstimator;
  mesh_pt()->spatial_error_estimator_pt()=error_estimator_pt;
  // Error targets for adaptive refinement
  mesh_pt()->max_permitted_error()=max_error_target;
  mesh_pt()->min_permitted_error()=min_error_target;
  //Doc the boundaries
  ofstream some_file;
  char filename[100];
  sprintf(filename,"boundaries.dat");
  some_file.open(filename);
  mesh_pt()->output_boundaries(some_file);
  some_file.close();
  //Set the boundary conditions
  //Boundary 0 is the bottom of the domain (pinned)
  {
   unsigned b = 0;
   unsigned n_node = mesh_pt()->nboundary_node(b);
   for(unsigned n=0;n<n_node;n++)
    {
     for(unsigned i=0;i<3;i++) {mesh_pt()->boundary_node_pt(b,n)->pin(i);}
    }
  }
  //Boundary 1 is the boundary x is zero, so pin the x-velocity
  {
   unsigned b = 1;
   unsigned n_node = mesh_pt()->nboundary_node(b);
   for(unsigned n=0;n<n_node;n++)
    {
     mesh_pt()->boundary_node_pt(b,n)->pin(0);
    }
  }
  //Boundary 2 is the boundary y=0, so pin the y-velocity
  //otherwise free
  {
   unsigned b = 2;
   unsigned n_node = mesh_pt()->nboundary_node(b);
   for(unsigned n=0;n<n_node;n++)
    {
     mesh_pt()->boundary_node_pt(b,n)->pin(1);
    }
  }
  //Boundary 3 is the wall, so pinned in all coordinates
  {
   unsigned b = 3;
   unsigned n_node = mesh_pt()->nboundary_node(b);
   for(unsigned n=0;n<n_node;n++)
    {
     for(unsigned i=0;i<3;i++)
      {
       mesh_pt()->boundary_node_pt(b,n)->pin(i);
      }
     if(n==0)
      {
       //Pin one spine heights on the wall
       static_cast<SpineNode*>(mesh_pt()->boundary_node_pt(b,n))->
        spine_pt()->spine_height_pt()->pin(0);
      }
    }
  }
  //Boundary 4 must be the top, so it's traction free
  // Loop over the elements to set up element-specific
  // things that cannot be handled by constructor
  unsigned n_element = mesh_pt()->nbulk();
  for(unsigned i=0;i<n_element;i++)
   {
    // Upcast from GeneralisedElement to the present element
    ELEMENT* el_pt = dynamic_cast<ELEMENT*>(mesh_pt()->element_pt(i));
    //Set the Reynolds number, etc
    el_pt->re_pt() = &Global_Physical_Variables::Re;
    //Set the gravitational force
    el_pt->re_invfr_pt() = &Global_Physical_Variables::ReInvFr;
    el_pt->g_pt() = &Global_Physical_Variables::G;
   }
  //Loop over the interface elements and set the capillary number
  unsigned n_interface = mesh_pt()->ninterface_element();
  for(unsigned e=0;e<n_interface;e++)
   {
    SpineSurfaceFluidInterfaceElement<ELEMENT>* el_pt
     = dynamic_cast<SpineSurfaceFluidInterfaceElement<ELEMENT>*>(
      mesh_pt()->interface_element_pt(e));
    //set the capillary number
    el_pt->ca_pt() =  &Global_Physical_Variables::Ca;
    //Set the
    el_pt->set_external_pressure_data(Pext_pt);
   }
  // Pin redudant pressure dofs
  RefineableNavierStokesEquations<3>::
   pin_redundant_nodal_pressures(mesh_pt()->bulk_element_pt());
  // Set solid body rotation as initial solution
  unsigned n_nod=mesh_pt()->nnode();
  for (unsigned j=0;j<n_nod;j++)
   {
    using namespace Global_Physical_Variables;
    Node* node_pt=mesh_pt()->node_pt(j);
    // Recover coordinates
    double x=node_pt->x(0);
    double y=node_pt->x(1);
    double r=sqrt(x*x+y*y);
    double theta = atan2(y,x);
    // Solid body rotation
    node_pt->set_value(0,-Omega*r*sin(theta));
    node_pt->set_value(1,Omega*r*cos(theta));
    node_pt->set_value(2,0.0);
   }
  //Attach the boundary conditions to the mesh
  cout <<"Number of equations: " << assign_eqn_numbers() << std::endl;
 } // end_of_constructor
References Global_Physical_Variables::Angle, oomph::Problem::assign_eqn_numbers(), atan2(), b, Global_Physical_Variables::Ca, oomph::FluidInterfaceElement::ca_pt(), cos(), e(), MeshRefinement::error_estimator_pt, MergeRestartFiles::filename, Global_Physical_Variables::G, i, AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::interface_element_pt(), j, FreeSurfaceRotationProblem< ELEMENT >::mesh_pt(), n, AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::nbulk(), oomph::Problem::Newton_solver_tolerance, AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::ninterface_element(), Global_Physical_Variables::Omega, FreeSurfaceRotationProblem< ELEMENT >::Pext_pt, constants::pi, BiharmonicTestFunctions2::Pi, oomph::Data::pin(), UniformPSDSelfTest::r, UniformPSDSelfTest::radius, Global_Physical_Variables::Re, Global_Physical_Variables::ReInvFr, oomph::FluidInterfaceElement::set_external_pressure_data(), oomph::Data::set_value(), sin(), sqrt(), BiharmonicTestFunctions2::theta, plotDoE::x, oomph::Node::x(), and y.
~FreeSurfaceRotationProblem() [1/2]
template<class ELEMENT > FreeSurfaceRotationProblem< ELEMENT >::~FreeSurfaceRotationProblem () inline
Destructor (empty)
 {}
FreeSurfaceRotationProblem() [2/2]
template<class ELEMENT > FreeSurfaceRotationProblem< ELEMENT >::FreeSurfaceRotationProblem (DocInfo & doc_info, const double & min_error_target, const double & max_error_target, const unsigned & hijack_flag)
Constructor: Pass DocInfo object and target errors.
Constructor: Pass DocInfo object and error targets.
  : Volume(atan(1.0)), Doc_info(doc_info)
 {
  //Create a pointer to the external pressure
  Pext_pt = new Data(1);
  Pext_pt->set_value(0,0.0);
  //Add the external pressure to the global data
  add_global_data(Pext_pt);
  //Set the contact angle
  const double pi = MathematicalConstants::Pi;
  Global_Physical_Variables::Angle = 0.5*pi;
  // Setup mesh:
  //------------
  // Create geometric objects: Elliptical tube with half axes = radius = 1.0
  double radius=1.0;
  GeomObject* Wall_pt=new EllipticalTube(radius,radius);
  // Boundaries on object
  Vector<double> xi_lo(2);
  // height of inflow
  xi_lo[0]=0.0;
  // start of Wall_pt
  xi_lo[1]=0.0;
  Vector<double> xi_hi(2);
  // height of outflow
  xi_hi[0]=1.0;
  // end of Wall_pt
  xi_hi[1]=0.5*MathematicalConstants::Pi;
  // # of layers
  unsigned nlayer=1;
  //Radial divider is located half-way along the circumference
  double frac_mid=0.5;
  // Build and assign mesh
  Bulk_mesh_pt =
   new AxialSpineQuarterTubeMesh<
    ELEMENT,
    SpineSurfaceFluidInterfaceElement<ELEMENT> >
   (Wall_pt,xi_lo,frac_mid,xi_hi,nlayer);
  // Set error estimator
  Z2ErrorEstimator* error_estimator_pt=new Z2ErrorEstimator;
  Bulk_mesh_pt->spatial_error_estimator_pt()=error_estimator_pt;
  // Error targets for adaptive refinement
  Bulk_mesh_pt->max_permitted_error()=max_error_target;
  Bulk_mesh_pt->min_permitted_error()=min_error_target;
  //Doc the boundaries
  /*ofstream some_file;
  char filename[100];
  sprintf(filename,"boundaries.dat");
  some_file.open(filename);
  Bulk_mesh_pt->output_boundaries(some_file);
  some_file.close();*/
  //Set the boundary conditions
  //Boundary 0 is the bottom of the domain (pinned)
  {
   unsigned b = 0;
   unsigned n_node = Bulk_mesh_pt->nboundary_node(b);
   for(unsigned n=0;n<n_node;n++)
    {
     for(unsigned i=0;i<3;i++) {Bulk_mesh_pt->boundary_node_pt(b,n)->pin(i);}
    }
  }
  //Boundary 1 is the boundary x is zero, so pin the x-velocity
  {
   unsigned b = 1;
   unsigned n_node = Bulk_mesh_pt->nboundary_node(b);
   for(unsigned n=0;n<n_node;n++)
    {
     Bulk_mesh_pt->boundary_node_pt(b,n)->pin(0);
    }
  }
  //Boundary 2 is the boundary y=0, so pin the y-velocity
  //otherwise free
  {
   unsigned b = 2;
   unsigned n_node = Bulk_mesh_pt->nboundary_node(b);
   for(unsigned n=0;n<n_node;n++)
    {
     Bulk_mesh_pt->boundary_node_pt(b,n)->pin(1);
    }
  }
  //Boundary 3 is the wall, so pinned in all coordinates
  {
   unsigned b = 3;
   unsigned n_node = Bulk_mesh_pt->nboundary_node(b);
   for(unsigned n=0;n<n_node;n++)
    {
     for(unsigned i=0;i<3;i++)
      {
       Bulk_mesh_pt->boundary_node_pt(b,n)->pin(i);
      }
     /*if(n==0)
      {
       //Pin one spine heights on the wall
       static_cast<SpineNode*>(Bulk_mesh_pt->boundary_node_pt(b,n))->
        spine_pt()->spine_height_pt()->pin(0);
        }*/
    }
  }
  //Boundary 4 must be the top, so it's traction free
  // Loop over the elements to set up element-specific
  // things that cannot be handled by constructor
  unsigned n_element = Bulk_mesh_pt->nbulk();
  for(unsigned i=0;i<n_element;i++)
   {
    // Upcast from GeneralisedElement to the present element
    ELEMENT* el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(i));
    //Set the Reynolds number, etc
    el_pt->re_pt() = &Global_Physical_Variables::Re;
    //Set the gravitational force
    el_pt->re_invfr_pt() = &Global_Physical_Variables::ReInvFr;
    el_pt->g_pt() = &Global_Physical_Variables::G;
   }
  // Pin redudant pressure dofs. This must be done before
  // pinning the single pressure does because it unpins things
  RefineableNavierStokesEquations<3>::
   pin_redundant_nodal_pressures(Bulk_mesh_pt->bulk_element_pt());
  //If not hijacking the internal pressure
  if(hijack_flag==0)
   {
    //We trade for the external pressu
    Traded_pressure_data_pt = Pext_pt;
    // Since the external pressure is "traded" for the volume constraint,
    // it no longer sets the overall pressure, and we
    // can add an arbitrary constant to all pressures. To make
    // the solution unique, we pin a single pressure value in the bulk:
    // We arbitrarily set the pressure dof 0 in element 0 to zero.
    dynamic_cast<ELEMENT*>(Bulk_mesh_pt->bulk_element_pt(0))
     ->fix_pressure(0,0.0);
   }
  //Otherwise we are hijacking an internal value
  else
   {
    // The external pressure is pinned -- the external pressure
    // sets the pressure throughout the domain -- we do not have
    // the liberty to fix another pressure value!
    Pext_pt->pin(0);
    //If the flag is one, it's Taylor hood (hijack the nodal value)
    if(hijack_flag==1)
     {
     //Hijack one of the pressure values in the fluid and use it
     //as the pressure whose value is determined by the volume constraint.
     //(Its value will affect the residual of that element but it will not
     //be determined by it, i.e. it's hijacked).
     Traded_pressure_data_pt = dynamic_cast<ELEMENT*>(
      Bulk_mesh_pt->bulk_element_pt(0))->hijack_nodal_value(0,3);
     }
    //Otherwise hijack internal
    else
    {
     //Hijack one of the pressure values in the fluid and use it
     //as the pressure whose value is determined by the volume constraint.
     //(Its value will affect the residual of that element but it will not
     //be determined by it, i.e. it's hijacked).
     Traded_pressure_data_pt = dynamic_cast<ELEMENT*>(
      Bulk_mesh_pt->bulk_element_pt(0))->hijack_internal_value(0,0);
    }
   }
  //Loop over the interface elements and set the capillary number
  unsigned n_interface = Bulk_mesh_pt->ninterface_element();
  for(unsigned e=0;e<n_interface;e++)
   {
    SpineSurfaceFluidInterfaceElement<ELEMENT>* el_pt
     = dynamic_cast<SpineSurfaceFluidInterfaceElement<ELEMENT>*>(
      Bulk_mesh_pt->interface_element_pt(e));
    //set the capillary number
    el_pt->ca_pt() =  &Global_Physical_Variables::Ca;
    //Set the external pressure
    el_pt->set_external_pressure_data(Pext_pt);
   }
  // Set solid body rotation as initial solution
  unsigned n_nod=Bulk_mesh_pt->nnode();
  for (unsigned j=0;j<n_nod;j++)
   {
    using namespace Global_Physical_Variables;
    Node* node_pt=Bulk_mesh_pt->node_pt(j);
    // Recover coordinates
    double x=node_pt->x(0);
    double y=node_pt->x(1);
    double r=sqrt(x*x+y*y);
    double theta = atan2(y,x);
    // Solid body rotation
    node_pt->set_value(0,-Omega*r*sin(theta));
    node_pt->set_value(1,Omega*r*cos(theta));
    node_pt->set_value(2,0.0);
   }
  this->create_volume_constraint_elements();
  this->add_sub_mesh(Bulk_mesh_pt);
  this->add_sub_mesh(Volume_computation_mesh_pt);
  this->add_sub_mesh(Volume_constraint_mesh_pt);
  this->build_global_mesh();
  //Attach the boundary conditions to the mesh
  cout <<"Number of equations: " << assign_eqn_numbers() << std::endl;
 } // end_of_constructor
References oomph::Problem::add_global_data(), oomph::Problem::add_sub_mesh(), Global_Physical_Variables::Angle, oomph::Problem::assign_eqn_numbers(), atan2(), b, oomph::Problem::build_global_mesh(), AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::bulk_element_pt(), FreeSurfaceRotationProblem< ELEMENT >::Bulk_mesh_pt, Global_Physical_Variables::Ca, oomph::FluidInterfaceElement::ca_pt(), cos(), FreeSurfaceRotationProblem< ELEMENT >::create_volume_constraint_elements(), e(), MeshRefinement::error_estimator_pt, Global_Physical_Variables::G, i, AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::interface_element_pt(), j, n, AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::nbulk(), AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::ninterface_element(), oomph::SarahBL::Omega, FreeSurfaceRotationProblem< ELEMENT >::Pext_pt, constants::pi, BiharmonicTestFunctions2::Pi, oomph::Data::pin(), UniformPSDSelfTest::r, UniformPSDSelfTest::radius, Global_Physical_Variables::Re, Global_Physical_Variables::ReInvFr, oomph::FluidInterfaceElement::set_external_pressure_data(), oomph::Data::set_value(), sin(), sqrt(), BiharmonicTestFunctions2::theta, FreeSurfaceRotationProblem< ELEMENT >::Traded_pressure_data_pt, FreeSurfaceRotationProblem< ELEMENT >::Volume_computation_mesh_pt, FreeSurfaceRotationProblem< ELEMENT >::Volume_constraint_mesh_pt, plotDoE::x, oomph::Node::x(), and y.
~FreeSurfaceRotationProblem() [2/2]
template<class ELEMENT > FreeSurfaceRotationProblem< ELEMENT >::~FreeSurfaceRotationProblem () inline
Destructor to clean up memory (empty)
 {}
Member Function Documentation
actions_after_newton_solve() [1/2]
template<class ELEMENT > void FreeSurfaceRotationProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Doc the solution after solve.
Reimplemented from oomph::Problem.
   {
    // Doc solution after solving
    doc_solution();
    // Increment label for output files
    Doc_info.number()++;
   }
References GlobalParameters::Doc_info, and oomph::DocInfo::number().
actions_after_newton_solve() [2/2]
template<class ELEMENT > void FreeSurfaceRotationProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Doc the solution after solve.
Reimplemented from oomph::Problem.
   {
    // Doc solution after solving
    doc_solution();
    // Increment label for output files
    Doc_info.number()++;
   }
References GlobalParameters::Doc_info, and oomph::DocInfo::number().
actions_before_newton_convergence_check() [1/2]
template<class ELEMENT > void FreeSurfaceRotationProblem< ELEMENT >::actions_before_newton_convergence_check () inline virtual
Spine heights/lengths are unknowns in the problem so their values get corrected during each Newton step. However, changing their value does not automatically change the nodal positions, so we need to update all of them
Reimplemented from oomph::Problem.
   {
    mesh_pt()->node_update();
   }
actions_before_newton_convergence_check() [2/2]
template<class ELEMENT > void FreeSurfaceRotationProblem< ELEMENT >::actions_before_newton_convergence_check () inline virtual
Spine heights/lengths are unknowns in the problem so their values get corrected during each Newton step. However, changing their value does not automatically change the nodal positions, so we need to update all of them
Reimplemented from oomph::Problem.
   {
    Bulk_mesh_pt->node_update();
   }
actions_before_newton_solve() [1/2]
template<class ELEMENT > void FreeSurfaceRotationProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve.
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [2/2]
template<class ELEMENT > void FreeSurfaceRotationProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update the problem specs before solve.
Reimplemented from oomph::Problem.
 {}
create_volume_constraint_elements()
template<class ELEMENT > void FreeSurfaceRotationProblem< ELEMENT >::create_volume_constraint_elements
Create the volume constraint elements.
Create the volume constraint elements on all boundaries surrounding the volume
 {
  //The single volume constraint element
  Volume_constraint_mesh_pt = new Mesh;
  VolumeConstraintElement* vol_constraint_element =
   new VolumeConstraintElement(&Volume,Traded_pressure_data_pt,0);
  Volume_constraint_mesh_pt->add_element_pt(vol_constraint_element);
  //Now create the volume computation elements
  Volume_computation_mesh_pt = new Mesh;
  //Loop over all boundaries (or a subset why?)
  for(unsigned b=0;b<5;b++)
   {
    // How many bulk fluid elements are adjacent to boundary b?
    unsigned n_element = Bulk_mesh_pt->nboundary_element(b);
    // Loop over the bulk fluid elements adjacent to boundary b?
    for(unsigned e=0;e<n_element;e++)
     {
      // Get pointer to the bulk fluid element that is
      // adjacent to boundary b
      ELEMENT* bulk_elem_pt = dynamic_cast<ELEMENT*>(
       Bulk_mesh_pt->boundary_element_pt(b,e));
      //Find the index of the face of element e along boundary b
      int face_index = Bulk_mesh_pt->face_index_at_boundary(b,e);
      // Create new element
      SpineSurfaceVolumeConstraintBoundingElement<ELEMENT>* el_pt =
       new SpineSurfaceVolumeConstraintBoundingElement<ELEMENT>(
        bulk_elem_pt,face_index);
      //Set the "master" volume control element
      el_pt->set_volume_constraint_element(vol_constraint_element);
      // Add it to the mesh
      Volume_computation_mesh_pt->add_element_pt(el_pt);
     }
   }
 }
References oomph::Mesh::add_element_pt(), b, FreeSurfaceRotationProblem< ELEMENT >::Bulk_mesh_pt, e(), oomph::VolumeConstraintBoundingElement::set_volume_constraint_element(), FreeSurfaceRotationProblem< ELEMENT >::Traded_pressure_data_pt, FreeSurfaceRotationProblem< ELEMENT >::Volume, FreeSurfaceRotationProblem< ELEMENT >::Volume_computation_mesh_pt, and FreeSurfaceRotationProblem< ELEMENT >::Volume_constraint_mesh_pt.
Referenced by FreeSurfaceRotationProblem< ELEMENT >::FreeSurfaceRotationProblem().
doc_solution() [1/2]
template<class ELEMENT > void FreeSurfaceRotationProblem< ELEMENT >::doc_solution
Doc the solution.
 {
  ofstream some_file;
  char filename[100];
  // Number of plot points
  unsigned npts;
  npts=5;
  // Output solution
  sprintf(filename,"%s/soln%i.dat",Doc_info.directory().c_str(),
          Doc_info.number());
  some_file.open(filename);
  mesh_pt()->output(some_file,npts);
  some_file.close();
 } // end_of_doc_solution
References oomph::DocInfo::directory(), FreeSurfaceRotationProblem< ELEMENT >::Doc_info, MergeRestartFiles::filename, FreeSurfaceRotationProblem< ELEMENT >::mesh_pt(), and oomph::DocInfo::number().
doc_solution() [2/2]
template<class ELEMENT > void FreeSurfaceRotationProblem< ELEMENT >::doc_solution ()
Doc the solution.
mesh_pt()
template<class ELEMENT > AxialSpineQuarterTubeMesh<ELEMENT,SpineSurfaceFluidInterfaceElement<ELEMENT> >* FreeSurfaceRotationProblem< ELEMENT >::mesh_pt () inline
Overload generic access function by one that returns a pointer to the specific mesh
   {
    return
     dynamic_cast<AxialSpineQuarterTubeMesh<ELEMENT,
     SpineSurfaceFluidInterfaceElement<ELEMENT> >*>
     (Problem::mesh_pt());
   }
Referenced by FreeSurfaceRotationProblem< ELEMENT >::doc_solution(), and FreeSurfaceRotationProblem< ELEMENT >::FreeSurfaceRotationProblem().
Member Data Documentation
Bulk_mesh_pt
template<class ELEMENT > AxialSpineQuarterTubeMesh< ELEMENT, SpineSurfaceFluidInterfaceElement<ELEMENT> >* FreeSurfaceRotationProblem< ELEMENT >::Bulk_mesh_pt
Overload generic access function by one that returns a pointer to the specific mesh
Referenced by FreeSurfaceRotationProblem< ELEMENT >::create_volume_constraint_elements(), and FreeSurfaceRotationProblem< ELEMENT >::FreeSurfaceRotationProblem().
Doc_info
template<class ELEMENT > DocInfo FreeSurfaceRotationProblem< ELEMENT >::Doc_info private
Doc info object.
Referenced by FreeSurfaceRotationProblem< ELEMENT >::doc_solution().
Pext_pt
template<class ELEMENT > Data* FreeSurfaceRotationProblem< ELEMENT >::Pext_pt private
Referenced by FreeSurfaceRotationProblem< ELEMENT >::FreeSurfaceRotationProblem().
Traded_pressure_data_pt
template<class ELEMENT > Data* FreeSurfaceRotationProblem< ELEMENT >::Traded_pressure_data_pt private
Storage for the pressure that is traded for the volume constraint.
Referenced by FreeSurfaceRotationProblem< ELEMENT >::create_volume_constraint_elements(), and FreeSurfaceRotationProblem< ELEMENT >::FreeSurfaceRotationProblem().
Volume
template<class ELEMENT > double FreeSurfaceRotationProblem< ELEMENT >::Volume private
The volume of the fluid.
Referenced by FreeSurfaceRotationProblem< ELEMENT >::create_volume_constraint_elements().
Volume_computation_mesh_pt
template<class ELEMENT > Mesh* FreeSurfaceRotationProblem< ELEMENT >::Volume_computation_mesh_pt
Storage for the elements that compute the enclosed fluid volume.
Referenced by FreeSurfaceRotationProblem< ELEMENT >::create_volume_constraint_elements(), and FreeSurfaceRotationProblem< ELEMENT >::FreeSurfaceRotationProblem().
Volume_constraint_mesh_pt
template<class ELEMENT > Mesh* FreeSurfaceRotationProblem< ELEMENT >::Volume_constraint_mesh_pt
Storage for the volume constraint element.
Referenced by FreeSurfaceRotationProblem< ELEMENT >::create_volume_constraint_elements(), and FreeSurfaceRotationProblem< ELEMENT >::FreeSurfaceRotationProblem().
The documentation for this class was generated from the following files:
free_surface_rotation.cc
3d_static_cap.cc