MercuryDPM: oomph::AxisymmetricQAdvectionCrouzeixRaviartElement Class Reference
oomph::AxisymmetricQAdvectionCrouzeixRaviartElement Class Reference
#include <axisymmetric_advection_navier_stokes_elements.h>
Public Member Functions
AxisymmetricQAdvectionCrouzeixRaviartElement ()
unsigned required_nvalue (const unsigned &n) const
void disable_ALE ()
Final override for disable ALE.
void enable_ALE ()
Final override for enable ALE.
unsigned nscalar_paraview () const
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
std::string scalar_name_paraview (const unsigned &i) const
void output (std::ostream &outfile)
Overload the standard output function with the broken default.
void output (std::ostream &outfile, const unsigned &nplot)
void output (FILE *file_pt)
C-style output function: Broken default.
void output (FILE *file_pt, const unsigned &n_plot)
C-style output function: Broken default.
void output_fct (std::ostream &outfile, const unsigned &Nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output function for an exact solution: Broken default.
void output_fct (std::ostream &outfile, const unsigned &Nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
unsigned u_index_axi_adv_diff () const
void compute_norm (double &norm)
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
void get_wind_axi_adv_diff (const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &wind) const
void fill_in_contribution_to_residuals (Vector< double > &residuals)
void fill_in_off_diagonal_jacobian_blocks_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
Public Member Functions inherited from oomph::QAxisymAdvectionDiffusionElement< 3 >
QAxisymAdvectionDiffusionElement ()
QAxisymAdvectionDiffusionElement (const QAxisymAdvectionDiffusionElement< NNODE_1D > &dummy)=delete
Broken copy constructor.
unsigned required_nvalue (const unsigned &n) const
Broken assignment operator.
void output (std::ostream &outfile)
void output (std::ostream &outfile, const unsigned &n_plot)
void output (FILE *file_pt)
void output (FILE *file_pt, const unsigned &n_plot)
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Public Member Functions inherited from oomph::QElement< 2, NNODE_1D >
QElement ()
Constructor.
QElement (const QElement &)=delete
Broken copy constructor.
void shape (const Vector< double > &s, Shape &psi) const
Broken assignment operator.
void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
Derivatives of shape functions for specific QElement<2,..>
void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double s_min () const
Min. value of local coordinate.
double s_max () const
Max. value of local coordinate.
unsigned nvertex_node () const
Number of vertex nodes in the element.
Node * vertex_node_pt (const unsigned &j) const
Pointer to the j-th vertex node in the element.
void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
Get local coordinates of node j in the element; vector sets its own size.
void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
Get the local fraction of node j in the element.
double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
Node * get_node_at_local_coordinate (const Vector< double > &s) const
Get the node at the specified local coordinate.
unsigned nnode_1d () const
Number of nodes along each element edge.
unsigned nplot_points_paraview (const unsigned &nplot) const
unsigned nsub_elements_paraview (const unsigned &nplot) const
void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &use_equally_spaced_interior_sample_points=false) const
std::string tecplot_zone_string (const unsigned &nplot) const
unsigned nplot_points (const unsigned &nplot) const
unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::QuadElementBase
QuadElementBase ()
Constructor. Empty.
Public Member Functions inherited from oomph::QElementBase
QElementBase ()
Constructor: Initialise pointers to macro element reference coords.
QElementBase (const QElementBase &)=delete
Broken copy constructor.
virtual ~QElementBase ()
Broken assignment operator.
bool local_coord_is_valid (const Vector< double > &s)
Check whether the local coordinate are valid or not.
void move_local_coord_back_into_element (Vector< double > &s) const
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
double & s_macro_ll (const unsigned &i)
double & s_macro_ur (const unsigned &i)
double s_macro_ll (const unsigned &i) const
double s_macro_ur (const unsigned &i) const
void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
unsigned nnode_on_face () const
ElementGeometry::ElementGeometry element_geometry () const
It's a Q element!
Public Member Functions inherited from oomph::QElementGeometricBase
QElementGeometricBase ()
Empty default constructor.
QElementGeometricBase (const QElementGeometricBase &)=delete
Broken copy constructor.
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
double size () const
void point_output (std::ostream &outfile, const Vector< double > &s)
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::AxisymAdvectionDiffusionEquations
AxisymAdvectionDiffusionEquations ()
AxisymAdvectionDiffusionEquations (const AxisymAdvectionDiffusionEquations &dummy)=delete
Broken copy constructor.
double du_dt_axi_adv_diff (const unsigned &n) const
void disable_ALE ()
void enable_ALE ()
unsigned nscalar_paraview () const
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
std::string scalar_name_paraview (const unsigned &i) const
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Get error against and norm of exact solution.
AxisymAdvectionDiffusionSourceFctPt & source_fct_pt ()
Access function: Pointer to source function.
AxisymAdvectionDiffusionSourceFctPt source_fct_pt () const
Access function: Pointer to source function. Const version.
AxisymAdvectionDiffusionWindFctPt & wind_fct_pt ()
Access function: Pointer to wind function.
AxisymAdvectionDiffusionWindFctPt wind_fct_pt () const
Access function: Pointer to wind function. Const version.
const double & pe () const
Peclet number.
double *& pe_pt ()
Pointer to Peclet number.
const double & pe_st () const
Peclet number multiplied by Strouhal number.
double *& pe_st_pt ()
Pointer to Peclet number multipled by Strouha number.
const double & d () const
Peclet number multiplied by Strouhal number.
double *& d_pt ()
Pointer to Peclet number multipled by Strouha number.
virtual void get_source_axi_adv_diff (const unsigned &ipt, const Vector< double > &x, double &source) const
void get_flux (const Vector< double > &s, Vector< double > &flux) const
Get flux: [du/dr,du/dz].
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Add the element's contribution to its residual vector (wrapper)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
double interpolated_u_axi_adv_diff (const Vector< double > &s) const
Return FE representation of function value u(s) at local coordinate s.
virtual void dinterpolated_u_axi_adv_diff_ddata (const Vector< double > &s, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
unsigned self_test ()
Self-test: Return 0 for OK.
Public Member Functions inherited from oomph::AxisymmetricQCrouzeixRaviartElement
AxisymmetricQCrouzeixRaviartElement ()
Constructor, there are three internal values (for the pressure)
double p_axi_nst (const unsigned &i) const
unsigned npres_axi_nst () const
Return number of pressure values.
void fix_pressure (const unsigned &p_dof, const double &pvalue)
Function to fix the internal pressure dof idof_internal.
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction) const
Compute traction at local coordinate s for outer unit normal N.
int p_local_eqn (const unsigned &n) const
void output (std::ostream &outfile)
Redirect output to NavierStokesEquations output.
void output (std::ostream &outfile, const unsigned &n_plot)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt)
Redirect output to NavierStokesEquations output.
void output (FILE *file_pt, const unsigned &n_plot)
Redirect output to NavierStokesEquations output.
unsigned ndof_types () const
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::AxisymmetricNavierStokesEquations
AxisymmetricNavierStokesEquations ()
Constructor: NULL the body force and source function.
const double & re () const
Reynolds number.
const double & re_st () const
Product of Reynolds and Strouhal number (=Womersley number)
double *& re_pt ()
Pointer to Reynolds number.
double *& re_st_pt ()
Pointer to product of Reynolds and Strouhal number (=Womersley number)
const double & re_invfr () const
Global inverse Froude number.
double *& re_invfr_pt ()
Pointer to global inverse Froude number.
const double & re_invro () const
Global Reynolds number multiplied by inverse Rossby number.
double *& re_invro_pt ()
Pointer to global inverse Froude number.
const Vector< double > & g () const
Vector of gravitational components.
Vector< double > *& g_pt ()
Pointer to Vector of gravitational components.
const double & density_ratio () const
double *& density_ratio_pt ()
Pointer to Density ratio.
const double & viscosity_ratio () const
double *& viscosity_ratio_pt ()
Pointer to Viscosity Ratio.
virtual unsigned u_index_axi_nst (const unsigned &i) const
unsigned u_index_nst (const unsigned &i) const
unsigned n_u_nst () const
double du_dt_axi_nst (const unsigned &n, const unsigned &i) const
void disable_ALE ()
void enable_ALE ()
virtual int p_nodal_index_axi_nst () const
Which nodal value represents the pressure?
double pressure_integral () const
Integral of pressure over element.
double dissipation () const
Return integral of dissipation over element.
double dissipation (const Vector< double > &s) const
Return dissipation at local coordinate s.
double kin_energy () const
Get integral of kinetic energy over element.
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
Strain-rate tensor: \(e_{ij} \) where \(i,j = r,z,\theta \) (in that order)
void traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction) const
void get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > &press_mass_diag, Vector< double > &veloc_mass_diag, const unsigned &which_one=0)
unsigned nscalar_paraview () const
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
std::string scalar_name_paraview (const unsigned &i) const
void point_output_data (const Vector< double > &s, Vector< double > &data)
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element's residual Vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
Compute the element's residual Vector.
void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
void interpolated_u_axi_nst (const Vector< double > &s, Vector< double > &veloc) const
Compute vector of FE interpolated velocity u at local coordinate s.
double interpolated_u_axi_nst (const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s.
double interpolated_u_axi_nst (const unsigned &t, const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s.
virtual void dinterpolated_u_axi_nst_ddata (const Vector< double > &s, const unsigned &i, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
double interpolated_p_axi_nst (const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s.
double interpolated_duds_axi_nst (const Vector< double > &s, const unsigned &i, const unsigned &j) const
double interpolated_dudx_axi_nst (const Vector< double > &s, const unsigned &i, const unsigned &j) const
double interpolated_dudt_axi_nst (const Vector< double > &s, const unsigned &i) const
double interpolated_d_dudx_dX_axi_nst (const Vector< double > &s, const unsigned &p, const unsigned &q, const unsigned &i, const unsigned &k) const
double compute_physical_size () const
Compute the volume of the element.
Public Member Functions inherited from oomph::NavierStokesElementWithDiagonalMassMatrices
NavierStokesElementWithDiagonalMassMatrices ()
Empty constructor.
virtual ~NavierStokesElementWithDiagonalMassMatrices ()
Virtual destructor.
NavierStokesElementWithDiagonalMassMatrices (const NavierStokesElementWithDiagonalMassMatrices &)=delete
Broken copy constructor.
void operator= (const NavierStokesElementWithDiagonalMassMatrices &)=delete
Broken assignment operator.
Additional Inherited Members
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Public Types inherited from oomph::AxisymAdvectionDiffusionEquations
typedef void(* AxisymAdvectionDiffusionSourceFctPt) (const Vector< double > &x, double &f)
typedef void(* AxisymAdvectionDiffusionWindFctPt) (const Vector< double > &x, Vector< double > &wind)
Public Attributes inherited from oomph::AxisymmetricNavierStokesEquations
void(*&)(const double &time, const Vector< double > &x, Vector< double > &f) axi_nst_body_force_fct_pt ()
Access function for the body-force pointer.
double(*&)(const double &time, const Vector< double > &x) source_fct_pt ()
Access function for the source-function pointer.
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Static Public Attributes inherited from oomph::AxisymmetricNavierStokesEquations
static Vector< double > Gamma
Vector to decide whether the stress-divergence form is used or not.
Protected Member Functions inherited from oomph::QAxisymAdvectionDiffusionElement< 3 >
double dshape_and_dtest_eulerian_axi_adv_diff (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_axi_adv_diff (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Member Functions inherited from oomph::AxisymAdvectionDiffusionEquations
virtual void fill_in_generic_residual_contribution_axi_adv_diff (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
Protected Member Functions inherited from oomph::AxisymmetricQCrouzeixRaviartElement
double dshape_and_dtest_eulerian_axi_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_axi_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const
void pshape_axi_nst (const Vector< double > &s, Shape &psi) const
Pressure shape functions at local coordinate s.
void pshape_axi_nst (const Vector< double > &s, Shape &psi, Shape &test) const
Pressure shape and test functions at local coordinte s.
Protected Member Functions inherited from oomph::AxisymmetricNavierStokesEquations
virtual void get_body_force_axi_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &result)
Calculate the body force fct at a given time and Eulerian position.
virtual void get_body_force_gradient_axi_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, DenseMatrix< double > &d_body_force_dx)
double get_source_fct (const double &time, const unsigned &ipt, const Vector< double > &x)
Calculate the source fct at given time and Eulerian position.
virtual void get_source_fct_gradient (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &gradient)
virtual void get_viscosity_ratio_axisym_nst (const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, double &visc_ratio)
virtual void fill_in_generic_residual_contribution_axi_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
virtual void fill_in_generic_dresidual_contribution_axi_nst (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam, unsigned flag)
void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Protected Attributes inherited from oomph::AxisymAdvectionDiffusionEquations
double * Pe_pt
Pointer to global Peclet number.
double * PeSt_pt
Pointer to global Peclet number multiplied by Strouhal number.
double * D_pt
Pointer to global Diffusion parameter.
AxisymAdvectionDiffusionSourceFctPt Source_fct_pt
Pointer to source function:
AxisymAdvectionDiffusionWindFctPt Wind_fct_pt
Pointer to wind function:
bool ALE_is_disabled
Boolean flag to indicate whether AlE formulation is disable.
Protected Attributes inherited from oomph::AxisymmetricQCrouzeixRaviartElement
unsigned P_axi_nst_internal_index
Protected Attributes inherited from oomph::AxisymmetricNavierStokesEquations
double * Viscosity_Ratio_pt
double * Density_Ratio_pt
double * Re_pt
Pointer to global Reynolds number.
double * ReSt_pt
Pointer to global Reynolds number x Strouhal number (=Womersley)
double * ReInvFr_pt
double * ReInvRo_pt
Vector< double > * G_pt
Pointer to global gravity Vector.
void(* Body_force_fct_pt)(const double &time, const Vector< double > &x, Vector< double > &result)
Pointer to body force function.
double(* Source_fct_pt)(const double &time, const Vector< double > &x)
Pointer to volumetric source function.
bool ALE_is_disabled
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
A class that solves the Boussinesq approximation of the Navier–Stokes and energy equations by coupling two pre-existing classes. The QAdvectionDiffusionReactionElement with bi-quadratic interpolation for the scalar variables (temperature and concentration) and QCrouzeixRaviartElement which solves the Navier–Stokes equations using bi-quadratic interpolation for the velocities and a discontinuous bi-linear interpolation for the pressure. Note that we are free to choose the order in which we store the variables at the nodes. In this case we choose to store the variables in the order fluid velocities followed by temperature. We must, therefore, overload the function AdvectionDiffusionReactionEquations<2,DIM>::u_index_adv_diff_react() to indicate that the temperature is stored at the DIM-th position not the 0-th. We do not need to overload the corresponding function in the NavierStokesEquations<DIM> class because the velocities are stored first.
Constructor & Destructor Documentation
AxisymmetricQAdvectionCrouzeixRaviartElement()
oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::AxisymmetricQAdvectionCrouzeixRaviartElement () inline
Constructor: call the underlying constructors and initialise the pointer to the Rayleigh number to point to the default value of 0.0.
                                                 :
   QAxisymAdvectionDiffusionElement<3>(),
   AxisymmetricQCrouzeixRaviartElement() {}
Member Function Documentation
compute_error() [1/2]
void oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) inline virtual
Validate against exact solution. Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element Call the broken default
Reimplemented from oomph::FiniteElement.
   {FiniteElement::compute_error(outfile,exact_soln_pt,error,norm);}
References oomph::FiniteElement::compute_error(), and calibrate::error.
compute_error() [2/2]
void oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) inline virtual
Validate against exact solution at given time Solution is provided via function pointer. Plot at a given number of plot points and compute L2 error and L2 norm of velocity solution over element Call the broken default
Reimplemented from oomph::FiniteElement.
   {FiniteElement::compute_error(outfile,exact_soln_pt,
                                 time,error,norm);}
References oomph::FiniteElement::compute_error(), and calibrate::error.
compute_norm()
void oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::compute_norm (double & norm) inline virtual
Compute norm of solution – broken virtual can be overloaded by element writer to implement whatever norm is desired for the specific element
Reimplemented from oomph::GeneralisedElement.
   {AxisymmetricQCrouzeixRaviartElement::compute_norm(norm);}
References oomph::GeneralisedElement::compute_norm().
disable_ALE()
void oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::disable_ALE () inline virtual
Final override for disable ALE.
Reimplemented from oomph::FiniteElement.
   {
    //Disable ALE in both sets of equations
    AxisymmetricNavierStokesEquations::disable_ALE();
    AxisymAdvectionDiffusionEquations::enable_ALE();
   }
References oomph::AxisymmetricNavierStokesEquations::disable_ALE(), and oomph::AxisymAdvectionDiffusionEquations::enable_ALE().
enable_ALE()
void oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::enable_ALE () inline virtual
Final override for enable ALE.
Reimplemented from oomph::FiniteElement.
   {
    //Enable ALE in both sets of equations
    AxisymmetricNavierStokesEquations::enable_ALE();
    AxisymAdvectionDiffusionEquations::enable_ALE();
   }
References oomph::AxisymAdvectionDiffusionEquations::enable_ALE(), and oomph::AxisymmetricNavierStokesEquations::enable_ALE().
fill_in_contribution_to_jacobian()
void oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline virtual
Compute the element's residual Vector and the Jacobian matrix. Use finite-differencing only for the off-diagonal blocks.
Reimplemented from oomph::GeneralisedElement.
  {
   //Calculate the Navier-Stokes contributions (diagonal block and residuals)
   AxisymmetricNavierStokesEquations::
    fill_in_contribution_to_jacobian(residuals,jacobian);
    //Calculate the advection-diffusion contributions
    //(diagonal block and residuals)
   AxisymAdvectionDiffusionEquations::
     fill_in_contribution_to_jacobian(residuals,jacobian);
   //Add in the off-diagonal blocks
   fill_in_off_diagonal_jacobian_blocks_by_fd(residuals,jacobian);
  } //End of jacobian calculation
References oomph::AxisymAdvectionDiffusionEquations::fill_in_contribution_to_jacobian(), oomph::AxisymmetricNavierStokesEquations::fill_in_contribution_to_jacobian(), and fill_in_off_diagonal_jacobian_blocks_by_fd().
fill_in_contribution_to_jacobian_and_mass_matrix()
void oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix) inline virtual
Add the element's contribution to its residuals vector, jacobian matrix and mass matrix
Reimplemented from oomph::GeneralisedElement.
   {
    AxisymmetricNavierStokesEquations::
     fill_in_contribution_to_jacobian_and_mass_matrix(
      residuals,jacobian,mass_matrix);
    AxisymAdvectionDiffusionEquations::
     fill_in_contribution_to_jacobian_and_mass_matrix(
      residuals,jacobian,mass_matrix);
    fill_in_off_diagonal_jacobian_blocks_by_fd(residuals,jacobian);
   }
References oomph::AxisymmetricNavierStokesEquations::fill_in_contribution_to_jacobian_and_mass_matrix(), oomph::GeneralisedElement::fill_in_contribution_to_jacobian_and_mass_matrix(), and fill_in_off_diagonal_jacobian_blocks_by_fd().
fill_in_contribution_to_residuals()
void oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::fill_in_contribution_to_residuals (Vector< double > & residuals) inline virtual
Calculate the element's contribution to the residual vector. Recall that fill_in_* functions MUST NOT initialise the entries in the vector to zero. This allows us to call the fill_in_* functions of the constituent single-physics elements sequentially, without wiping out any previously computed entries.
Reimplemented from oomph::GeneralisedElement.
   {
    //Fill in the residuals of the Navier-Stokes equations
    AxisymmetricNavierStokesEquations::fill_in_contribution_to_residuals(residuals);
    //Fill in the residuals of the advection-diffusion eqautions
    AxisymAdvectionDiffusionEquations::fill_in_contribution_to_residuals(residuals);
   }
References oomph::AxisymAdvectionDiffusionEquations::fill_in_contribution_to_residuals(), and oomph::AxisymmetricNavierStokesEquations::fill_in_contribution_to_residuals().
fill_in_off_diagonal_jacobian_blocks_by_fd()
void oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::fill_in_off_diagonal_jacobian_blocks_by_fd (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline
Helper function to get the off-diagonal blocks of the Jacobian matrix by finite differences
   {
    //Local storage for the index in the nodes at which the
    //Navier-Stokes velocities are stored (we know that this should be 0,1,2)
    unsigned u_nodal_nst[3];
    for(unsigned i=0;i<3;i++)
     {u_nodal_nst[i] = this->u_index_nst(i);}
    //Local storage for the  index at which the temperature and
    //solute are  stored
    unsigned C_nodal_adv_diff = this->u_index_axi_adv_diff();
    //Find the total number of unknowns in the elements
    unsigned n_dof = this->ndof();
    //Temporary storage for residuals
    Vector<double> newres(n_dof);
    //Storage for local unknown and local equation
    int local_unknown =0, local_eqn = 0;
    //Set the finite difference step
    double fd_step = FiniteElement::Default_fd_jacobian_step;
    //Find the number of nodes
    unsigned n_node = this->nnode();
    //Calculate the contribution of the Navier--Stokes velocities to the
    //advection-diffusion equations
    //Loop over the nodes
    for(unsigned n=0;n<n_node;n++)
     {
      //There are 3 values of the  velocities
      for(unsigned i=0;i<3;i++)
       {
        //Get the local velocity equation number
        local_unknown = this->nodal_local_eqn(n,u_nodal_nst[i]);
        //If it's not pinned
        if(local_unknown >= 0)
         {
          //Get a pointer to the velocity value
          double *value_pt = this->node_pt(n)->value_pt(u_nodal_nst[i]);
          //Save the old value
          double old_var = *value_pt;
          //Increment the value
          *value_pt += fd_step;
          //Get the altered advection-diffusion residuals.
          //Do this using fill_in because get_residuals has never been
          //overloaded, and will actually compute all residuals which
          //is slightly inefficient.
          for(unsigned m=0;m<n_dof;m++) {newres[m] = 0.0;}
          AxisymAdvectionDiffusionEquations::
           fill_in_contribution_to_residuals(newres);
          //Now fill in the Advection-Diffusion-Reaction sub-block
          //of the jacobian
          for(unsigned m=0;m<n_node;m++)
           {
            //Local equation for temperature or solute
            local_eqn = this->nodal_local_eqn(m,C_nodal_adv_diff);
            //If it's not a boundary condition
            if(local_eqn >= 0)
             {
              double sum = (newres[local_eqn] - residuals[local_eqn])/fd_step;
              jacobian(local_eqn,local_unknown) = sum;
             }
           }
          //Reset the nodal data
          *value_pt = old_var;
         }
       }
     } //End of loop over nodes
 }
References oomph::GeneralisedElement::Default_fd_jacobian_step, oomph::AxisymAdvectionDiffusionEquations::fill_in_contribution_to_residuals(), i, m, n, oomph::GeneralisedElement::ndof(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), u_index_axi_adv_diff(), oomph::AxisymmetricNavierStokesEquations::u_index_nst(), and oomph::Data::value_pt().
Referenced by fill_in_contribution_to_jacobian(), and fill_in_contribution_to_jacobian_and_mass_matrix().
get_wind_axi_adv_diff()
void oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::get_wind_axi_adv_diff (const unsigned & ipt, const Vector< double > & s, const Vector< double > & x, Vector< double > & wind) const inline virtual
Overload the wind function in the advection-diffusion equations. This provides the coupling from the Navier–Stokes equations to the advection-diffusion equations because the wind is the fluid velocity.
Reimplemented from oomph::AxisymAdvectionDiffusionEquations.
  {
   //The wind function is simply the velocity at the points
   this->interpolated_u_axi_nst(s,wind);
  }
References oomph::AxisymmetricNavierStokesEquations::interpolated_u_axi_nst().
nscalar_paraview()
unsigned oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::nscalar_paraview () const inline virtual
Number of scalars/fields output by this element. Reimplements broken virtual function in base class.
Reimplemented from oomph::FiniteElement.
  {
   return AxisymmetricNavierStokesEquations::nscalar_paraview()
    + AxisymAdvectionDiffusionEquations::nscalar_paraview();
  }
References oomph::AxisymAdvectionDiffusionEquations::nscalar_paraview(), and oomph::AxisymmetricNavierStokesEquations::nscalar_paraview().
output() [1/4]
void oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::output (FILE * file_pt) inline virtual
C-style output function: Broken default.
Reimplemented from oomph::FiniteElement.
   {FiniteElement::output(file_pt);}
References oomph::FiniteElement::output().
output() [2/4]
void oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::output (FILE * file_pt, const unsigned & n_plot) inline virtual
C-style output function: Broken default.
Reimplemented from oomph::FiniteElement.
   {FiniteElement::output(file_pt,n_plot);}
References oomph::FiniteElement::output().
output() [3/4]
void oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::output (std::ostream & outfile) inline virtual
Overload the standard output function with the broken default.
Reimplemented from oomph::FiniteElement.
 {FiniteElement::output(outfile);}
References oomph::FiniteElement::output().
output() [4/4]
void oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::output (std::ostream & outfile, const unsigned & nplot) inline virtual
Output function:
Output x, y, u, v, p, theta at Nplot^DIM plot points
Reimplemented from oomph::FiniteElement.
   {
    //vector of local coordinates
    Vector<double> s(2);
    // Tecplot header info
    outfile << this->tecplot_zone_string(nplot);
    // Loop over plot points
    unsigned num_plot_points=this->nplot_points(nplot);
    for (unsigned iplot=0;iplot<num_plot_points;iplot++)
     {
      // Get local coordinates of plot point
      this->get_s_plot(iplot,nplot,s);
      // Output the position of the plot point
      for(unsigned i=0;i<2;i++)
       {outfile << this->interpolated_x(s,i) << " ";}
      // Output the fluid velocities at the plot point
      for(unsigned i=0;i<3;i++)
       {outfile << this->interpolated_u_axi_nst(s,i) << " ";}
      // Output the fluid pressure at the plot point
      outfile << this->interpolated_p_axi_nst(s)  << " ";
      //Output the solute concentration
      outfile << this->interpolated_u_axi_adv_diff(s) << " ";
      outfile << "\n";
     }
    outfile << std::endl;
    // Write tecplot footer (e.g. FE connectivity lists)
    this->write_tecplot_zone_footer(outfile,nplot);
   } //End of output function
References oomph::QElement< 2, NNODE_1D >::get_s_plot(), i, oomph::AxisymmetricNavierStokesEquations::interpolated_p_axi_nst(), oomph::AxisymAdvectionDiffusionEquations::interpolated_u_axi_adv_diff(), oomph::AxisymmetricNavierStokesEquations::interpolated_u_axi_nst(), oomph::FiniteElement::interpolated_x(), oomph::QElement< 2, NNODE_1D >::nplot_points(), s, oomph::QElement< 2, NNODE_1D >::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
output_fct() [1/2]
void oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::output_fct (std::ostream & outfile, const unsigned & Nplot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) inline virtual
Output function for a time-dependent exact solution: Broken default.
Reimplemented from oomph::FiniteElement.
   {
    FiniteElement::
     output_fct(outfile,Nplot,time,exact_soln_pt);
   }
References oomph::FiniteElement::output_fct().
output_fct() [2/2]
void oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::output_fct (std::ostream & outfile, const unsigned & Nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) inline virtual
Output function for an exact solution: Broken default.
Reimplemented from oomph::FiniteElement.
   {FiniteElement::output_fct(outfile,Nplot,exact_soln_pt);}
References oomph::FiniteElement::output_fct().
required_nvalue()
unsigned oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::required_nvalue (const unsigned & n) const inline virtual
The required number of values stored at the nodes is the sum of the required values of the two single-physics elements. Note that this step is generic for any multi-physics element of this type.
Reimplemented from oomph::AxisymmetricQCrouzeixRaviartElement.
   {return (QAxisymAdvectionDiffusionElement<3>::required_nvalue(n) +
            AxisymmetricQCrouzeixRaviartElement::required_nvalue(n));}
References n, and oomph::AxisymmetricQCrouzeixRaviartElement::required_nvalue().
scalar_name_paraview()
std::string oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::scalar_name_paraview (const unsigned & i) const inline virtual
Name of the i-th scalar field. Default implementation returns V1 for the first one, V2 for the second etc. Can (should!) be overloaded with more meaningful names in specific elements.
Reimplemented from oomph::FiniteElement.
  {
   return AxisymmetricNavierStokesEquations::scalar_name_paraview(i);
   //AxisymAdvectionDiffusionEquations::scalar_name_paraview(i);
  }
References i, and oomph::AxisymmetricNavierStokesEquations::scalar_name_paraview().
scalar_value_paraview()
void oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::scalar_value_paraview (std::ofstream & file_out, const unsigned & i, const unsigned & nplot) const inline virtual
Write values of the i-th scalar field at the plot points. Needs to be implemented for each new specific element type.
Reimplemented from oomph::FiniteElement.
  {
   AxisymmetricNavierStokesEquations::scalar_value_paraview(file_out,i,nplot);
   AxisymAdvectionDiffusionEquations::scalar_value_paraview(file_out,i,nplot);
  }
References i, oomph::AxisymAdvectionDiffusionEquations::scalar_value_paraview(), and oomph::AxisymmetricNavierStokesEquations::scalar_value_paraview().
u_index_axi_adv_diff()
unsigned oomph::AxisymmetricQAdvectionCrouzeixRaviartElement::u_index_axi_adv_diff () const inline virtual
Overload the index at which the temperature and solute concentration variables are stored.
Reimplemented from oomph::AxisymAdvectionDiffusionEquations.
 {return 3;}
Referenced by fill_in_off_diagonal_jacobian_blocks_by_fd().
The documentation for this class was generated from the following file:
axisymmetric_advection_navier_stokes_elements.h