MercuryDPM: stefan_boltzmann_melt.cc File Reference
stefan_boltzmann_melt.cc File Reference
#include <fenv.h>
#include "math.h"
#include <complex>
#include "generic.h"
#include "unsteady_heat.h"
#include "heat_transfer_and_melt_elements.h"
#include "temporary_stefan_boltzmann_elements.h"
#include "solid.h"
#include "constitutive.h"
#include "meshes/triangle_mesh.h"
Classes
class StefanBoltzmannMeltElement< ELEMENT >
class MyIntegral
class StefanBoltzmannProblem< ELEMENT >
Problem class.
Namespaces
GlobalParameters
Global parameters.
Functions
void GlobalParameters::get_source (const double &time, const Vector< double > &x, double &source)
Source function.
void GlobalParameters::get_exact_u (const double &time, const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
double GlobalParameters::melt_flux (const double &t)
double GlobalParameters::radius (const double &t)
Exact radius of inner circle.
double GlobalParameters::incoming_sb_inside (const double &t)
Incoming sb radiation on inside.
double GlobalParameters::incoming_sb_outside (const double &t)
Incoming sb radiation on outside.
int main (int argc, char **argv)
Solve 2D problem.
Variables
double GlobalParameters::Lambda_sq =0.0
Non-dim density for pseudo-solid.
double GlobalParameters::Nu =0.3
Poisson's ratio for pseudo-solid.
ConstitutiveLaw * GlobalParameters::Constitutive_law_pt =0
Pointer to constitutive law.
double GlobalParameters::Melt_temperature =0.8288627710
Melt-temperature.
double GlobalParameters::R_hat =0.1
Temporal variation in inner radius (for exact solution)
double GlobalParameters::V0 =1.0
Coeff for (time-)constant variation of temperature in inner circle.
double GlobalParameters::V0_hat =0.5
Coeff for time variation inner circle.
Function Documentation
main()
int main (int argc , char ** argv)
Solve 2D problem.
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Define possible command line arguments and parse the ones that
  // were actually specified
  // Number of integration points for new integration scheme.
  // Use normal Gauss rule if not specified.
  CommandLineArgs::specify_command_line_flag("--nintpt",
                                             &GlobalParameters::Nintpt);
  // Output directory
  CommandLineArgs::specify_command_line_flag("--dir",
                                             &GlobalParameters::Directory);
  // Timestep
  double dt=0.05;
  CommandLineArgs::specify_command_line_flag("--dt",&dt);
  // Max time
  double t_max=2.0;
  CommandLineArgs::specify_command_line_flag("--t_max",&t_max);
  // No source terms
  CommandLineArgs::specify_command_line_flag("--no_source");
  // Target area
  CommandLineArgs::specify_command_line_flag("--el_area",
                                             &GlobalParameters::Target_area);
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  // Create generalised Hookean constitutive equations
  GlobalParameters::Constitutive_law_pt =
   new GeneralisedHookean(&GlobalParameters::Nu);
  oomph_info << "Building/solving for  GlobalParameters::Target_area = "
             << GlobalParameters::Target_area << std::endl;
  // Set up the problem with 2D six-node elements
  StefanBoltzmannProblem
   <ProjectableUnsteadyHeatElement<
    PseudoSolidNodeUpdateElement<TUnsteadyHeatElement<2,3>,
                                 TPVDElement<2,3> > > >
   problem;
  // Initialise timestep -- also sets the weights for all timesteppers
  // in the problem.
  problem.initialise_dt(dt);
  problem.assign_initial_values_impulsive();
  //Output initial condition
  problem.doc_solution();
  // Timestepping loop
  while (problem.time_pt()->time()<=t_max)
   {
    // Take timestep
    problem.unsteady_newton_solve(dt);
    //Output solution
    problem.doc_solution();
   }
 } //end of main
References GlobalParameters::Constitutive_law_pt, GlobalParameters::Directory, oomph::CommandLineArgs::doc_specified_flags(), GlobalParameters::Nintpt, GlobalParameters::Nu, oomph::oomph_info, oomph::CommandLineArgs::parse_and_assign(), problem, oomph::CommandLineArgs::setup(), oomph::CommandLineArgs::specify_command_line_flag(), and GlobalParameters::Target_area.