MercuryDPM: SquarePacking Class Reference
SquarePacking Class Reference
Public Member Functions
void setupInitialConditions () override
This function allows to set the initial conditions for our problem to be solved, by default particle locations are randomly set. Remember particle properties must also be defined here.
Public Member Functions inherited from StatisticsVector< O >
void constructor ()
this is the actual constructor, sets up all basic things
void constructor (std::string name)
StatisticsVector ()
Basic constructor only calls constructor()
StatisticsVector (std::string name)
StatisticsVector (StatisticsVector &other)
Copy constructor.
StatisticsVector (int argc, char *argv[])
Advanced constructor that accepts arguments from the command line.
void readStatArguments (int argc, char *argv[])
std::string printStat ()
Outputs member variable values to a std::string.
void set_statType ()
void writeOutputFiles ()
Writes simulation data to all the main Mercury files: .data, .ene, .fstat, .xballs and .restart (see the Mercury website for more details regarding these files).
void print_help ()
void setNX (int new_)
void set_hx (Mdouble hx)
void setNY (int new_)
void set_hy (Mdouble hy)
void setNZ (int new_)
void set_hz (Mdouble hz)
void setN (int n)
void setN (int nx_, int ny_, int nz_)
void set_h (Mdouble h)
int getNX ()
int getNY ()
int getNZ ()
void setCGTimeMin (Mdouble t)
void setTimeMaxStat (Mdouble t)
void setCGTimeAveragingInterval (Mdouble t)
Mdouble getCGTimeMin ()
Mdouble getTimeMaxStat ()
Mdouble getCGTimeAveragingInterval ()
bool check_current_time_for_statistics ()
void setCGShape (const char *new_)
void setCGShape (CG_TYPE new_)
CG_TYPE getCGShape ()
void getN (int &nx_, int &ny_, int &nz_)
void setCGWidth (Mdouble w)
Set CG variables w2 and CG_invvolume.
void setCGWidth2 (Mdouble new_)
Set CG variables w2 and CG_invvolume.
Mdouble getCGWidth ()
Mdouble getCGWidthSquared ()
Mdouble getCutoff ()
Mdouble getCutoff2 ()
std::string print_CG ()
Output coarse graining variables.
StatisticsPoint< T > average (std::vector< StatisticsPoint< T > > &P)
Output average of statistical variables.
virtual void reset_statistics ()
Set all statistical variables to zero.
void statistics_from_fstat_and_data ()
get StatisticsPoint
void statistics_from_p3 ()
void jump_p3c ()
void setDoTimeAverage (bool new_)
bool getDoTimeAverage ()
void setStressTypeForFixedParticles (int new_)
int getStressTypeForFixedParticles ()
void set_infiniteStressForFixedParticles (bool new_)
void setMirrorAtDomainBoundary (Mdouble new_)
Mdouble getMirrorAtDomainBoundary ()
void setDoVariance (bool new_)
bool getDoVariance ()
void setDoGradient (bool new_)
bool getDoGradient ()
void setSuperExact (bool new_)
bool getSuperExact ()
void setDoIgnoreFixedParticles (bool new_)
bool getDoIgnoreFixedParticles ()
void verbose ()
void setVerbosityLevel (int new_)
int getVerbosityLevel () const
void setCGWidthalls (bool new_)
bool getCGWidthalls ()
void setDoPeriodicWalls (bool new_)
bool getDoPeriodicWalls ()
void setCGWidth_over_rmax (Mdouble new_)
Mdouble getCGWidth_over_rmax ()
void setPositions ()
Set position of StatisticsPoint points and set variables to 0.
bool readNextDataFile (unsigned int format)
void gather_force_statistics_from_fstat_and_data ()
void gather_force_statistics_from_p3c (int version)
void gather_force_statistics_from_p3w (int version, std::vector< int > &index)
void evaluate_force_statistics (int wp=0)
void evaluate_wall_force_statistics (Vec3D P, int wp=0)
void jump_fstat ()
void initialiseStatistics ()
Initializes statistics, i.e. setting w2, setting the grid and writing the header lines in the .stat file.
void outputStatistics ()
Calculates statistics for Particles (i.e. not collisions)
void gatherContactStatistics (unsigned int index1, int index2, Vec3D Contact, Mdouble delta, Mdouble ctheta, Mdouble fdotn, Mdouble fdott, Vec3D P1_P2_normal_, Vec3D P1_P2_tangential)
Calculates statistics for one collision (can be any kind of collision)
void processStatistics (bool usethese)
Processes all gathered statistics and resets them afterwards. (Processing means either calculating time averages or writing out statistics)
void finishStatistics ()
Finish all statistics (i.e. write out final data)
void write_statistics ()
Writes regular statistics.
void write_time_average_statistics ()
Writes out time averaged statistics.
void evaluate_particle_statistics (std::vector< BaseParticle * >::iterator P, int wp=0)
Calculates statistics for a single Particle.
std::vector< StatisticsPoint< T > > getCGPoints ()
Mdouble getXMinStat ()
Functions to acces and change the domain of statistics.
Mdouble getYMinStat ()
Mdouble getZMinStat ()
Mdouble getXMaxStat ()
Mdouble getYMaxStat ()
Mdouble getZMaxStat ()
void setXMinStat (Mdouble xMinStat_)
void setYMinStat (Mdouble yMinStat_)
void setZMinStat (Mdouble zMinStat_)
void setXMaxStat (Mdouble xMaxStat_)
void setYMaxStat (Mdouble yMaxStat_)
void setZMaxStat (Mdouble zMaxStat_)
int getNTimeAverage ()
Mdouble setInfinitelyLongDistance ()
void set_Polynomial (std::vector< Mdouble > new_coefficients, unsigned int new_dim)
void set_Polynomial (Mdouble *new_coefficients, unsigned int num_coeff, unsigned int new_dim)
void setPolynomialName (const char *new_name)
std::string getPolynomialName ()
void setDoDoublePoints (bool new_)
bool getDoDoublePoints ()
void setNTimeAverageReset (int new_)
bool getNTimeAverageReset ()
void set_rmin (Mdouble new_)
void set_rmax (Mdouble new_)
void set_hmax (Mdouble new_)
Mdouble evaluatePolynomial (Mdouble r)
Mdouble evaluatePolynomialGradient (Mdouble r)
Mdouble evaluateIntegral (Mdouble n1, Mdouble n2, Mdouble t)
unsigned int getStepSize () const
void setStepSize (unsigned int stepSize)
void setIndSpecies (unsigned int indSpecies)
Public Member Functions inherited from DPMBase
void constructor ()
A function which initialises the member variables to default values, so that the problem can be solved off the shelf; sets up a basic two dimensional problem which can be solved off the shelf. It is called in the constructor DPMBase().
DPMBase ()
Constructor that calls the "void constructor()".
DPMBase (const DPMBase &other)
Copy constructor type-2.
virtual ~DPMBase ()
virtual destructor
void autoNumber ()
The autoNumber() function calls three functions: setRunNumber(), readRunNumberFromFile() and incrementRunNumberInFile().
std::vector< int > get1DParametersFromRunNumber (int size_x) const
This turns a counter into 1 index, which is a useful feature for performing 1D parameter study. The index run from 1:size_x, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
std::vector< int > get2DParametersFromRunNumber (int size_x, int size_y) const
This turns a counter into 2 indices which is a very useful feature for performing a 2D study. The indices run from 1:size_x and 1:size_y, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
std::vector< int > get3DParametersFromRunNumber (int size_x, int size_y, int size_z) const
This turns a counter into 3 indices, which is a useful feature for performing a 3D parameter study. The indices run from 1:size_x, 1:size_y and 1:size_z, while the study number starts at 0 (initially the counter=1 in COUNTER_DONOTDEL)
int launchNewRun (const char *name, bool quick=false)
This launches a code from within this code. Please pass the name of the code to run.
void setRunNumber (int runNumber)
This sets the counter/Run number, overriding the defaults.
int getRunNumber () const
This returns the current value of the counter (runNumber_)
virtual void decompose ()
Sends particles from processorId to the root processor.
void solve ()
The work horse of the code.
void initialiseSolve ()
Beginning of the solve routine, before time stepping.
void finaliseSolve ()
End of the solve routine, after time stepping.
virtual void computeOneTimeStep ()
Performs everything needed for one time step, used in the time-loop of solve().
void checkSettings ()
Checks if the essentials are set properly to go ahead with solving the problem.
void forceWriteOutputFiles ()
Writes output files immediately, even if the current time step was not meant to be written. Also resets the last saved time step.
void solve (int argc, char *argv[])
The work horse of the code. Can handle flags from the command line.
virtual void writeXBallsScript () const
This writes a script which can be used to load the xballs problem to display the data just generated.
virtual Mdouble getInfo (const BaseParticle &P) const
A virtual function that returns some user-specified information about a particle.
ParticleVtkWriter * getVtkWriter () const
virtual void writeRestartFile ()
Stores all the particle data for current save time step to a "restart" file, which is a file simply intended to store all the information necessary to "restart" a simulation from a given time step (see also MercuryDPM.org for more information on restart files).
void writeDataFile ()
void writeEneFile ()
void writeFStatFile ()
void fillDomainWithParticles (unsigned N=50)
bool readRestartFile (ReadOptions opt=ReadOptions::ReadAll)
Reads all the particle data corresponding to a given, existing . restart file (for more details regarding restart files, refer to the training materials on the MercuryDPM website).Returns true if it is successful, false otherwise.
int readRestartFile (std::string fileName, ReadOptions opt=ReadOptions::ReadAll)
The same as readRestartFile(bool), but also reads all the particle data corresponding to the current saved time step.
virtual void write (std::ostream &os, bool writeAllParticles=true) const
virtual void read (std::istream &is, ReadOptions opt=ReadOptions::ReadAll)
Reads all data from a restart file, e.g. domain data and particle data.
virtual BaseWall * readUserDefinedWall (const std::string &type) const
Allows you to read in a wall defined in a Driver directory; see USER/Luca/ScrewFiller.
virtual void readOld (std::istream &is)
Reads all data from a restart file, e.g. domain data and particle data; old version.
bool readDataFile (std::string fileName="", unsigned int format=0)
This allows particle data to be reloaded from data files.
bool readParAndIniFiles (std::string fileName)
Allows the user to read par.ini files (useful to read files produced by the MDCLR simulation code - external to MercuryDPM)
bool readNextDataFile (unsigned int format=0)
Reads the next data file with default format=0. However, one can modify the format based on whether the particle data corresponds to 3D or 2D data- see Visualising data in xballs.
void readNextFStatFile ()
Reads the next fstat file.
bool findNextExistingDataFile (Mdouble tMin, bool verbose=true)
Finds and opens the next data file, if such a file exists.
bool readArguments (int argc, char *argv[])
Can interpret main function input arguments that are passed by the driver codes.
virtual bool readNextArgument (int &i, int argc, char *argv[])
Interprets the i^th command-line argument.
virtual bool checkParticleForInteraction (const BaseParticle &P)
Checks whether a particle P has any interaction with walls or other particles.
virtual bool checkParticleForInteractionLocal (const BaseParticle &P)
Checks if a particle P has any interaction with walls or other particles in the local domain.
bool checkParticleForInteractionLocalPeriodic (const BaseParticle &P)
void readSpeciesFromDataFile (bool read=true)
void importParticlesAs (ParticleHandler &particleHandler, InteractionHandler &interactionHandler, const ParticleSpecies *species)
Copies particles, interactions assigning species from a local simulation to a global one. Useful for the creation of a cluster.
MERCURYDPM_DEPRECATED File & getDataFile ()
The non const version. Allows one to edit the File::dataFile.
MERCURYDPM_DEPRECATED File & getEneFile ()
The non const version. Allows to edit the File::eneFile.
MERCURYDPM_DEPRECATED File & getFStatFile ()
The non const version. Allows to edit the File::fStatFile.
MERCURYDPM_DEPRECATED File & getRestartFile ()
The non const version. Allows to edit the File::restartFile.
MERCURYDPM_DEPRECATED File & getStatFile ()
The non const version. Allows to edit the File::statFile.
File & getInteractionFile ()
Return a reference to the file InteractionsFile.
MERCURYDPM_DEPRECATED const File & getDataFile () const
The const version. Does not allow for any editing of the File::dataFile.
MERCURYDPM_DEPRECATED const File & getEneFile () const
The const version. Does not allow for any editing of the File::eneFile.
MERCURYDPM_DEPRECATED const File & getFStatFile () const
The const version. Does not allow for any editing of the File::fStatFile.
MERCURYDPM_DEPRECATED const File & getRestartFile () const
The const version. Does not allow for any editing of the File::restartFile.
MERCURYDPM_DEPRECATED const File & getStatFile () const
The const version. Does not allow for any editing of the File::statFile.
const File & getInteractionFile () const
Returns a constant reference to an Interactions file.
const std::string & getName () const
Returns the name of the file. Does not allow to change it though.
void setName (const std::string &name)
Allows to set the name of all the files (ene, data, fstat, restart, stat)
void setName (const char *name)
Calls setName(std::string)
void setSaveCount (unsigned int saveCount)
Sets File::saveCount_ for all files (ene, data, fstat, restart, stat)
void setFileType (FileType fileType)
Sets File::fileType_ for all files (ene, data, fstat, restart, stat)
void setOpenMode (std::fstream::openmode openMode)
Sets File::openMode_ for all files (ene, data, fstat, restart, stat)
void resetFileCounter ()
Resets the file counter for each file i.e. for ene, data, fstat, restart, stat)
void closeFiles ()
Closes all files (ene, data, fstat, restart, stat) that were opened to read or write.
void setVTKOutputDirectory (const std::string &dir)
Sets the output directory of the VTK files.
void setLastSavedTimeStep (unsigned int nextSavedTimeStep)
Sets the next time step for all the files (ene, data, fstat, restart, stat) at which the data is to be written or saved.
Mdouble getTime () const
Returns the current simulation time.
Mdouble getNextTime () const
Returns the current simulation time.
unsigned int getNumberOfTimeSteps () const
Returns the current counter of time-steps, i.e. the number of time-steps that the simulation has undergone so far.
void setTime (Mdouble time)
Sets a new value for the current simulation time.
void setTimeMax (Mdouble newTMax)
Sets a new value for the maximum simulation duration.
Mdouble getTimeMax () const
Returns the maximum simulation duration.
void setLogarithmicSaveCount (Mdouble logarithmicSaveCountBase)
Sets File::logarithmicSaveCount_ for all files (ene, data, fstat, restart, stat)
void setNToWrite (int nToWrite)
set the number of elements to write to the screen
int getNToWrite () const
get the number of elements to write to the
void setRotation (bool rotation)
Sets whether particle rotation is enabled or disabled.
bool getRotation () const
Indicates whether particle rotation is enabled or disabled.
MERCURYDPM_DEPRECATED void setWallsWriteVTK (FileType writeWallsVTK)
Sets whether walls are written into a VTK file.
MERCURYDPM_DEPRECATED void setWallsWriteVTK (bool)
Sets whether walls are written into a VTK file.
MERCURYDPM_DEPRECATED void setInteractionsWriteVTK (bool)
Sets whether interactions are written into a VTK file.
void setParticlesWriteVTK (bool writeParticlesVTK)
Sets whether particles are written in a VTK file.
void setSuperquadricParticlesWriteVTK (bool writeSuperquadricParticlesVTK)
MERCURYDPM_DEPRECATED FileType getWallsWriteVTK () const
Returns whether walls are written in a VTK file.
bool getParticlesWriteVTK () const
Returns whether particles are written in a VTK file.
bool getSuperquadricParticlesWriteVTK () const
Mdouble getXMin () const
If the length of the problem domain in x-direction is XMax - XMin, then getXMin() returns XMin.
Mdouble getXMax () const
If the length of the problem domain in x-direction is XMax - XMin, then getXMax() returns XMax.
Mdouble getYMin () const
If the length of the problem domain in y-direction is YMax - YMin, then getYMin() returns YMin.
Mdouble getYMax () const
If the length of the problem domain in y-direction is YMax - YMin, then getYMax() returns XMax.
Mdouble getZMin () const
If the length of the problem domain in z-direction is ZMax - ZMin, then getZMin() returns ZMin.
Mdouble getZMax () const
If the length of the problem domain in z-direction is ZMax - ZMin, then getZMax() returns ZMax.
Mdouble getXCenter () const
Mdouble getYCenter () const
Mdouble getZCenter () const
Vec3D getCenter () const
get center of domain
Vec3D getMin () const
Returns the minimum coordinates of the problem domain.
Vec3D getMax () const
Returns the maximum coordinates of the problem domain.
void setXMin (Mdouble newXMin)
Sets the value of XMin, the lower bound of the problem domain in the x-direction.
void setYMin (Mdouble newYMin)
Sets the value of YMin, the lower bound of the problem domain in the y-direction.
void setZMin (Mdouble newZMin)
Sets the value of ZMin, the lower bound of the problem domain in the z-direction.
void setXMax (Mdouble newXMax)
Sets the value of XMax, the upper bound of the problem domain in the x-direction.
void setYMax (Mdouble newYMax)
Sets the value of YMax, the upper bound of the problem domain in the y-direction.
void setZMax (Mdouble newZMax)
Sets the value of ZMax, the upper bound of the problem domain in the z-direction.
void setMax (const Vec3D &max)
Sets the maximum coordinates of the problem domain.
void setMax (Mdouble, Mdouble, Mdouble)
Sets the maximum coordinates of the problem domain.
void setDomain (const Vec3D &min, const Vec3D &max)
Sets the minimum coordinates of the problem domain.
void setMin (const Vec3D &min)
Sets the minimum coordinates of the problem domain.
void setMin (Mdouble, Mdouble, Mdouble)
Sets the minimum coordinates of the problem domain.
void setTimeStep (Mdouble newDt)
Sets a new value for the simulation time step.
Mdouble getTimeStep () const
Returns the simulation time step.
void setNumberOfOMPThreads (int numberOfOMPThreads)
Sets the number of omp threads.
int getNumberOfOMPThreads () const
Returns the number of omp threads.
void setXBallsColourMode (int newCMode)
Set the xballs output mode.
int getXBallsColourMode () const
Get the xballs colour mode (CMode).
void setXBallsVectorScale (double newVScale)
Set the scale of vectors in xballs.
double getXBallsVectorScale () const
Returns the scale of vectors used in xballs.
void setXBallsAdditionalArguments (std::string newXBArgs)
Set the additional arguments for xballs.
std::string getXBallsAdditionalArguments () const
Returns the additional arguments for xballs.
void setXBallsScale (Mdouble newScale)
Sets the scale of the view (either normal, zoom in or zoom out) to display in xballs. The default is fit to screen.
double getXBallsScale () const
Returns the scale of the view in xballs.
void setGravity (Vec3D newGravity)
Sets a new value for the gravitational acceleration.
Vec3D getGravity () const
Returns the gravitational acceleration.
void setBackgroundDrag (Mdouble backgroundDrag)
Simple access function to turn on a background drag. The force of particleVelocity*drag is applied (note, it allowed to be negative i.e. create energy)
const Mdouble getBackgroundDrag () const
Return the background drag.
void setDimension (unsigned int newDim)
Sets both the system dimensions and the particle dimensionality.
void setSystemDimensions (unsigned int newDim)
Sets the system dimensionality.
unsigned int getSystemDimensions () const
Returns the system dimensionality.
void setParticleDimensions (unsigned int particleDimensions)
Sets the particle dimensionality.
unsigned int getParticleDimensions () const
Returns the particle dimensionality.
std::string getRestartVersion () const
This is to take into account for different Mercury versions. Returns the version of the restart file.
void setRestartVersion (std::string newRV)
Sets restart_version.
bool getRestarted () const
Returns the flag denoting if the simulation was restarted or not.
void setRestarted (bool newRestartedFlag)
Allows to set the flag stating if the simulation is to be restarted or not.
bool getAppend () const
Returns whether the "append" option is on or off.
void setAppend (bool newAppendFlag)
Sets whether the "append" option is on or off.
Mdouble getElasticEnergy () const
Returns the global elastic energy within the system.
Mdouble getKineticEnergy () const
Returns the global kinetic energy stored in the system.
Mdouble getGravitationalEnergy (Vec3D origin={0, 0, 0}) const
Returns the global gravitational potential energy stored relative to a user-defined origin in the system. Note, if no origin is specified the real origin i.e. (0,0,0) is taken.
Mdouble getRotationalEnergy () const
Returns the global rotational energy stored in the system.
Mdouble getTotalEnergy () const
Mdouble getTotalMass () const
JMFT: Return the total mass of the system, excluding fixed particles.
Vec3D getCentreOfMass () const
JMFT: Return the centre of mass of the system, excluding fixed particles.
Vec3D getTotalMomentum () const
JMFT: Return the total momentum of the system, excluding fixed particles.
double getCPUTime ()
double getWallTime ()
virtual void hGridInsertParticle (BaseParticle *obj UNUSED)
virtual void hGridUpdateParticle (BaseParticle *obj UNUSED)
virtual void hGridRemoveParticle (BaseParticle *obj UNUSED)
virtual void hGridUpdateMove (BaseParticle *, Mdouble)
bool mpiIsInCommunicationZone (BaseParticle *particle)
Checks if the position of the particle is in an mpi communication zone or not.
bool mpiInsertParticleCheck (BaseParticle *P)
Function that checks if the mpi particle should really be inserted by the current domain.
void insertGhostParticle (BaseParticle *P)
This function inserts a particle in the mpi communication boundaries.
void updateGhostGrid (BaseParticle *P)
Checks if the Domain/periodic interaction distance needs to be updated and updates it accordingly.
void setNumberOfDomains (std::vector< unsigned > direction)
Sets the number of domains in x-,y- and z-direction. Required for parallel computations.
void splitDomain (DomainSplit domainSplit)
std::vector< unsigned > getNumberOfDomains ()
returns the number of domains
Domain * getCurrentDomain ()
Function that returns a pointer to the domain corresponding to the processor.
void removeOldFiles () const
virtual void hGridGetInteractingParticleList (BaseParticle *obj, std::vector< BaseParticle * > &list)
Creates a list of neighbour particles obtained from the hgrid.
virtual void computeWallForces (BaseWall *w)
virtual bool getHGridUpdateEachTimeStep () const
void setMeanVelocity (Vec3D V_mean_goal)
This function will help you set a fixed kinetic energy and mean velocity in your system.
void setMeanVelocityAndKineticEnergy (Vec3D V_mean_goal, Mdouble Ek_goal)
This function will help you set a fixed kinetic energy and mean velocity in your system.
Mdouble getTotalVolume () const
Get the total volume of the cuboid system.
Matrix3D getKineticStress () const
Calculate the kinetic stress tensor in the system averaged over the whole volume.
Matrix3D getStaticStress () const
Calculate the static stress tensor in the system averaged over the whole volume.
Matrix3D getTotalStress () const
Calculate the total stress tensor in the system averaged over the whole volume.
virtual void handleParticleRemoval (unsigned int id)
Handles the removal of particles from the particleHandler.
virtual void handleParticleAddition (unsigned int id, BaseParticle *p)
Handles the addition of particles to the particleHandler.
void writePythonFileForVTKVisualisation () const
writes .py file for ParaView
void setWritePythonFileForVTKVisualisation (bool forceWritePythonFileForVTKVisualisation)
bool getWritePythonFileForVTKVisualisation () const
WallVTKWriter & getWallVTKWriter ()
Public Attributes
int N
Public Attributes inherited from DPMBase
SpeciesHandler speciesHandler
A handler to that stores the species type i.e. LinearViscoelasticSpecies, etc.
RNG random
This is a random generator, often used for setting up the initial conditions etc...
ParticleHandler particleHandler
An object of the class ParticleHandler, contains the pointers to all the particles created.
ParticleHandler paoloParticleHandler
Fake particleHandler created by Paolo needed temporary by just Paolo.
WallHandler wallHandler
An object of the class WallHandler. Contains pointers to all the walls created.
BoundaryHandler boundaryHandler
An object of the class BoundaryHandler which concerns insertion and deletion of particles into or from regions.
PeriodicBoundaryHandler periodicBoundaryHandler
Internal handler that deals with periodic boundaries, especially in a parallel build.
DomainHandler domainHandler
An object of the class DomainHandler which deals with parallel code.
InteractionHandler interactionHandler
An object of the class InteractionHandler.
CGHandler cgHandler
Object of the class cgHandler.
File dataFile
An instance of class File to handle in- and output into a .data file.
File fStatFile
An instance of class File to handle in- and output into a .fstat file.
File eneFile
An instance of class File to handle in- and output into a .ene file.
File restartFile
An instance of class File to handle in- and output into a .restart file.
File statFile
An instance of class File to handle in- and output into a .stat file.
File interactionFile
File class to handle in- and output into .interactions file. This file hold information about interactions.
Time clock_
record when the simulation started
Additional Inherited Members
Public Types inherited from DPMBase
enum class ReadOptions : int { ReadAll , ReadNoInteractions , ReadNoParticlesAndInteractions }
enum class DomainSplit {
X , Y , Z , XY ,
XZ , YZ , XYZ
}
Static Public Member Functions inherited from DPMBase
static void incrementRunNumberInFile ()
Increment the run Number (counter value) stored in the file_counter (COUNTER_DONOTDEL) by 1 and store the new value in the counter file.
static int readRunNumberFromFile ()
Read the run number or the counter from the counter file (COUNTER_DONOTDEL)
static bool areInContact (const BaseParticle *pI, const BaseParticle *pJ)
Checks if two particle are in contact or is there any positive overlap.
Protected Member Functions inherited from StatisticsVector< O >
bool satisfiesInclusionCriteria (BaseParticle *P)
bool loadVelocityProfile (const char *filename)
bool loadPositions (const char *filename)
Vec3D getVelocityProfile (Vec3D Position)
bool read_next_from_p3p_file ()
void autoSetSystemDimensions ()
Protected Member Functions inherited from DPMBase
virtual void computeAllForces ()
Computes all the forces acting on the particles using the BaseInteractable::setForce() and BaseInteractable::setTorque()
virtual void computeInternalForces (BaseParticle *)
Computes the internal forces on particle i (internal in the sense that the sum over all these forces is zero i.e. fully modelled forces)
virtual void computeInternalForce (BaseParticle *, BaseParticle *)
Computes the forces between two particles (internal in the sense that the sum over all these forces is zero i.e. fully modelled forces)
virtual void computeExternalForces (BaseParticle *)
Computes the external forces, such as gravity, acting on particles.
virtual void computeForcesDueToWalls (BaseParticle *, BaseWall *)
Computes the forces on the particles due to the walls (normals are outward normals)
virtual void actionsOnRestart ()
A virtual function where the users can add extra code which is executed only when the code is restarted.
virtual void actionsBeforeTimeLoop ()
A virtual function. Allows one to carry out any operations before the start of the time loop.
virtual void hGridActionsBeforeTimeLoop ()
A virtual function that allows one to carry out hGrid operations before the start of the time loop.
virtual void hGridActionsBeforeTimeStep ()
A virtual function that allows one to set or execute hGrid parameters or operations before every simulation time step.
virtual void actionsBeforeTimeStep ()
A virtual function which allows to define operations to be executed before the new time step.
virtual void computeAdditionalForces ()
A virtual function which allows to define operations to be executed prior to the OMP force collect.
virtual void actionsAfterSolve ()
A virtual function which allows to define operations to be executed after the solve().
virtual void actionsAfterTimeStep ()
A virtual function which allows to define operations to be executed after time step.
void writeVTKFiles () const
virtual void outputXBallsData (std::ostream &os) const
This function writes the location of the walls and particles in a format the XBalls program can read. For more information on the XBalls program, see Visualising data in xballs.
virtual void outputXBallsDataParticle (unsigned int i, unsigned int format, std::ostream &os) const
This function writes out the particle locations into an output stream in a format the XBalls program can read. For more information on the XBalls program, see Visualising data in xballs.
virtual void writeEneHeader (std::ostream &os) const
Writes a header with a certain format for ENE file.
virtual void writeFstatHeader (std::ostream &os) const
Writes a header with a certain format for FStat file.
virtual void writeEneTimeStep (std::ostream &os) const
Write the global kinetic, potential energy, etc. in the system.
void gatherContactStatistics ()
virtual void integrateBeforeForceComputation ()
Update particles' and walls' positions and velocities before force computation.
virtual void integrateAfterForceComputation ()
Update particles' and walls' positions and velocities after force computation.
virtual void checkInteractionWithBoundaries ()
There are a range of boundaries one could implement depending on ones' problem. This methods checks for interactions between particles and such range of boundaries. See BaseBoundary.h and all the boundaries in the Boundaries folder.
virtual void hGridActionsBeforeIntegration ()
This function has to be called before integrateBeforeForceComputation.
virtual void hGridActionsAfterIntegration ()
This function has to be called after integrateBeforeForceComputation.
void setFixedParticles (unsigned int n)
Sets a number, n, of particles in the particleHandler as "fixed particles".
virtual void printTime () const
Displays the current simulation time and the maximum simulation duration.
virtual bool continueSolve () const
A virtual function for deciding whether to continue the simulation, based on a user-specified criterion.
void outputInteractionDetails () const
Displays the interaction details corresponding to the pointer objects in the interaction handler.
bool isTimeEqualTo (Mdouble time) const
Checks whether the input variable "time" is the current time in the simulation.
void removeDuplicatePeriodicParticles ()
Removes periodic duplicate Particles.
void checkAndDuplicatePeriodicParticles ()
For simulations using periodic boundaries, checks and adds particles when necessary into the particle handler. See DPMBase.cc and PeriodicBoundary.cc for more details.
void performGhostParticleUpdate ()
When the Verlet scheme updates the positions and velocities of particles, ghost particles will need an update as wel. Their status will also be updated accordingly.
void deleteGhostParticles (std::set< BaseParticle * > &particlesToBeDeleted)
void synchroniseParticle (BaseParticle *, unsigned fromProcessor=0)
void performGhostVelocityUpdate ()
updates the final time-step velocity of the ghost particles
void disableSoftStop ()
This prevents the initialisation of the soft stop feature.
void discontinueSolve ()
This discontinues the solve loop after the current time step is finished.
Protected Attributes inherited from StatisticsVector< O >
StatType statType
Possible values X,Y,Z,XY,XZ,YZ,XYZ,RAZ,RA,RZ,AZ,R,A are used to determine if the statistics are averaged; f.e. StatType X is averaged over y and z.
int nx
Grid size nx,ny,nz (by default the points of evaluation are placed in an grid on the domain [xMinStat,xMaxStat]x[yMinStat,yMaxStat]x[zMinStat,zMaxStat].
int ny
see nx
int nz
see nx
Mdouble xMinStat
By default the domain is set to the domain of the MD problem (indicated by setting the stat-domain values to nan), but can be resized.
Mdouble xMaxStat
Mdouble yMinStat
Mdouble yMaxStat
Mdouble zMinStat
Mdouble zMaxStat
int nxMirrored
extension of grid size from mirrored points
int nyMirrored
int nzMirrored
std::vector< StatisticsPoint< T > > Points
A vector that stores the values of the statistical variables at a given position.
std::vector< StatisticsPoint< T > > dx
A vector that stores the gradient in x of all statistical variables at a given position.
std::vector< StatisticsPoint< T > > dy
A vector that stores the gradient in y of all statistical variables at a given position.
std::vector< StatisticsPoint< T > > dz
A vector that stores the gradient in z of all statistical variables at a given position.
std::vector< StatisticsPoint< T > > timeAverage
A vector used to sum up all statistical values in Points for time-averaging.
std::vector< StatisticsPoint< T > > timeVariance
a vector used to sum up the variance in time of all statistical values
std::vector< StatisticsPoint< T > > dxTimeAverage
a vector used to sum up all statistical gradients in dx for time-averaging
std::vector< StatisticsPoint< T > > dyTimeAverage
a vector used to sum up all statistical gradients in dy for time-averaging
std::vector< StatisticsPoint< T > > dzTimeAverage
a vector used to sum up all statistical gradients in dz for time-averaging
bool doTimeAverage
Determines if output is averaged over time.
int nTimeAverageReset
Determines after how many time steps the time average is reset.
bool doVariance
Determines if variance is outputted.
bool doGradient
Determines if gradient is outputted.
int nTimeAverage
A counter needed to average over time.
CG_TYPE CG_type
coarse graining type (Gaussian, Heaviside, Polynomial)
NORMALIZED_POLYNOMIAL< T > CGPolynomial
Stores the Polynomial, if the cg function is an axisymmetric function Polynomial in r.
Mdouble w2
coarse graining width squared; for HeavisideSphere and Gaussian
Mdouble cutoff
The distance from the origin at which the cg function vanishes; cutoff=w for HeavisideSphere or Polynomial, 3*w for Gaussian.
Mdouble cutoff2
Mdouble w_over_rmax
if w is not set manually then w will be set by multiplying this value by the largest particle radius at t=0
Mdouble tMinStat
Statistical output will only be created if t>tMinStat.
Mdouble tMaxStat
Statistical output will only be created if t<tMaxStat.
Mdouble tIntStat
Statistical output will only be created if tMaxStat-tIntStat< t< tMaxStat.
Mdouble indSpecies
defines the species for which statistics are extracted (-1 for all species)
Mdouble rmin
defines the minimum radius of the particles for which statistics are extracted
Mdouble rmax
defines the maximum radius of the particles for which statistics are extracted
Mdouble hmax
defines the maximum height of the particles for which statistics are extracted
bool walls
Turns off walls before evaluation.
bool periodicWalls
Turns off periodic walls before evaluation (needed for averaging, because we do not yet check if particle is in domain)
bool ignoreFixedParticles
Determines if fixed particles contribute to particle statistics (density, ...)
int StressTypeForFixedParticles
Stress type for fixed particles.
int verbosity
Determines how much is outputted to the terminal.
int format
format of the data input file
Mdouble mirrorAtDomainBoundary
0: Statistics near the wall are equal to statistics away from the wall; 1: Statistics are mirrored at the domain boundaries; up to a maximum depth specified by this number
bool isMDCLR
bool superexact
If true, cutoff radius for Gaussian is set to 5*w (from 3*w)
bool doDoublePoints
Vec3D P1
Position of first contact point.
Vec3D P2
Position of second contact point.
Vec3D P1_P2_normal
Direction of contact.
Mdouble P1_P2_distance
Length of contact line.
Matrix3D P1_P2_NormalStress
Contact stress from normal forces along the line of contact.
Matrix3D P1_P2_ContactCoupleStress
Vec3D P1_P2_Contact
Matrix3D P1_P2_TangentialStress
Contact stress from tangential forces along the line of contact.
Vec3D P1_P2_NormalTraction
Traction from normal forces at contact of flow with fixed particles or walls.
Vec3D P1_P2_TangentialTraction
Traction from tangential forces at contact of flow with fixed particles or walls.
MatrixSymmetric3D P1_P2_Fabric
Fabric.
Vec3D P1_P2_CollisionalHeatFlux
not yet working
Mdouble P1_P2_Dissipation
not yet working
Mdouble P1_P2_Potential
not yet working
std::vector< Vec3D > VelocityProfile
Vec3D VelocityProfile_Min
Vec3D VelocityProfile_D
std::fstream p3p_file
std::fstream p3c_file
std::fstream p3w_file
bool p3Format
unsigned int stepSize_
std::vector< Vec3D > positions_
bool centerPointInFStat_
Member Function Documentation
setupInitialConditions()
void SquarePacking::setupInitialConditions () inline override virtual
This function allows to set the initial conditions for our problem to be solved, by default particle locations are randomly set. Remember particle properties must also be defined here.
A virtual function with no implementation but can be overridden.
Todo:
I (Anthony) wants to change this to be an external function. This has a lot of advantages especially when using copy-constructors. This is a major change and will break other codes, so therefore has to be done carefully.
This sets up the particles initial conditions it is as you expect the user to override this. By default the particles are randomly distributed
Reimplemented from DPMBase.
{
         // make sure the number of particles is right
         logger(INFO, "Creating a cubic packing of %^3 particles", N);
         double Radius = .5;
         //set Particles' position, radius, velocity and bounding box
         setDomain({0, 0, -0.5}, {5, 5, 0.5});
         SphericalParticle P0;
         P0.setSpecies(speciesHandler.getObject(0));
         for (int i = 0; i < N; i++)
             for (int j = 0; j < N; j++)
             {
                 P0.setRadius(Radius);
                 P0.setVelocity(Vec3D(0.0, 0.0, 0.0));
                 P0.setPosition(Radius * Vec3D(1. + 2. * i, 1. + 2. * j, 0.0));
                 //setXMax(std::max(getXMax(),P0.getPosition().X+Radius));
                 //setYMax(std::max(getYMax(),P0.getPosition().Y+Radius));
                 particleHandler.copyAndAddObject(P0);
             }
         //set walls
         InfiniteWall w0;
         w0.setSpecies(speciesHandler.getObject(0));
         w0.set(Vec3D(-1, 0, 0), Vec3D(getXMin(), 0, 0));
         wallHandler.copyAndAddObject(w0);
         w0.set(Vec3D( 1, 0, 0), Vec3D(getXMax(), 0, 0));
         wallHandler.copyAndAddObject(w0);
         w0.set(Vec3D( 0,-1, 0), Vec3D(0, getYMin(), 0));
         wallHandler.copyAndAddObject(w0);
         w0.set(Vec3D( 0, 1, 0), Vec3D(0, getYMax(), 0));
         wallHandler.copyAndAddObject(w0);
     }
References BaseHandler< T >::copyAndAddObject(), BaseHandler< T >::getObject(), DPMBase::getXMax(), DPMBase::getXMin(), DPMBase::getYMax(), DPMBase::getYMin(), i, INFO, j, logger, N, Problem_Parameter::P0, DPMBase::particleHandler, Global_Physical_Variables::Radius, InfiniteWall::set(), DPMBase::setDomain(), BaseWall::setSpecies(), DPMBase::speciesHandler, and DPMBase::wallHandler.
Member Data Documentation
N
int SquarePacking::N
Referenced by setupInitialConditions().
The documentation for this class was generated from the following file:
SquarePackingSelfTest.cpp