MercuryDPM: EqualityChecker< Scalar, StorageIndex, Dim > Class Template Reference
EqualityChecker< Scalar, StorageIndex, Dim > Class Template Reference
Public Member Functions
EqualityChecker (const Scalar *input_data_, const DSizes< StorageIndex, Dim > &input_dims_, const DSizes< StorageIndex, Dim > &input_strides_, const DSizes< StorageIndex, Dim > &output_dims_, const DSizes< StorageIndex, Dim > &output_strides_)
void operator() (const Scalar *output_data) const
Private Member Functions
void check_recursive (const Scalar *input, const Scalar *output, int depth=0) const
Private Attributes
const Scalar * input_data
const DSizes< StorageIndex, Dim > & input_dims
const DSizes< StorageIndex, Dim > & input_strides
const DSizes< StorageIndex, Dim > & output_dims
const DSizes< StorageIndex, Dim > & output_strides
Constructor & Destructor Documentation
EqualityChecker()
template<typename Scalar , typename StorageIndex , int Dim> EqualityChecker< Scalar, StorageIndex, Dim >::EqualityChecker (const Scalar * input_data_, const DSizes< StorageIndex, Dim > & input_dims_, const DSizes< StorageIndex, Dim > & input_strides_, const DSizes< StorageIndex, Dim > & output_dims_, const DSizes< StorageIndex, Dim > & output_strides_) inline
       : input_data(input_data_),
         input_dims(input_dims_),
         input_strides(input_strides_),
         output_dims(output_dims_),
         output_strides(output_strides_) {}
Member Function Documentation
check_recursive()
template<typename Scalar , typename StorageIndex , int Dim> void EqualityChecker< Scalar, StorageIndex, Dim >::check_recursive (const Scalar * input, const Scalar * output, int depth = 0) const inline private
{
     if (depth == Dim) {
       VERIFY_IS_EQUAL(*input, *output);
       return;
     }
     for (int i = 0; i < output_dims[depth]; ++i) {
       check_recursive(input + i % input_dims[depth] * input_strides[depth], output + i * output_strides[depth],
                       depth + 1);
     }
   }
References Global_Variables::Dim, i, EqualityChecker< Scalar, StorageIndex, Dim >::input_dims, EqualityChecker< Scalar, StorageIndex, Dim >::input_strides, output(), EqualityChecker< Scalar, StorageIndex, Dim >::output_dims, EqualityChecker< Scalar, StorageIndex, Dim >::output_strides, and VERIFY_IS_EQUAL.
Referenced by EqualityChecker< Scalar, StorageIndex, Dim >::operator()().
operator()()
template<typename Scalar , typename StorageIndex , int Dim> void EqualityChecker< Scalar, StorageIndex, Dim >::operator() (const Scalar * output_data) const inline
 { check_recursive(input_data, output_data); }
References EqualityChecker< Scalar, StorageIndex, Dim >::check_recursive(), and EqualityChecker< Scalar, StorageIndex, Dim >::input_data.
Member Data Documentation
input_data
template<typename Scalar , typename StorageIndex , int Dim> const Scalar* EqualityChecker< Scalar, StorageIndex, Dim >::input_data private
Referenced by EqualityChecker< Scalar, StorageIndex, Dim >::operator()().
input_dims
template<typename Scalar , typename StorageIndex , int Dim> const DSizes<StorageIndex, Dim>& EqualityChecker< Scalar, StorageIndex, Dim >::input_dims private
Referenced by EqualityChecker< Scalar, StorageIndex, Dim >::check_recursive().
input_strides
template<typename Scalar , typename StorageIndex , int Dim> const DSizes<StorageIndex, Dim> & EqualityChecker< Scalar, StorageIndex, Dim >::input_strides private
Referenced by EqualityChecker< Scalar, StorageIndex, Dim >::check_recursive().
output_dims
template<typename Scalar , typename StorageIndex , int Dim> const DSizes<StorageIndex, Dim> & EqualityChecker< Scalar, StorageIndex, Dim >::output_dims private
Referenced by EqualityChecker< Scalar, StorageIndex, Dim >::check_recursive().
output_strides
template<typename Scalar , typename StorageIndex , int Dim> const DSizes<StorageIndex, Dim> & EqualityChecker< Scalar, StorageIndex, Dim >::output_strides private
Referenced by EqualityChecker< Scalar, StorageIndex, Dim >::check_recursive().
The documentation for this class was generated from the following file:
cxx11_tensor_block_access.cpp