MercuryDPM: DominoBatch.cpp File Reference
DominoBatch.cpp File Reference
#include "CMakeDefinitions.h"
#include <iostream>
#include <memory>
#include <stdexcept>
#include <string>
#include <array>
#include "Walls/InfiniteWall.h"
#include <stdio.h>
Functions
std::string ExecCommand (const char *cmd)
int main (int argc, char **argv)
Function Documentation
ExecCommand()
std::string ExecCommand (const char * cmd)
{
     std::array<char, 128> buffer;
     std::string result;
     std::unique_ptr<FILE, int(*)(FILE*)> pipe(popen(cmd, "r"), pclose);
     if (!pipe) {
         std::string ret = "Could not run an extra OS command: "; ret.append(cmd);
         throw std::runtime_error(ret);
     }
     while (fgets(buffer.data(), buffer.size(), pipe.get()) != nullptr) {
         result += buffer.data();
     }
     return result;
 }
References int(), ret, and oomph::Global_string_for_annotation::string().
Referenced by main().
main()
int main (int argc , char ** argv)
 {
     std::string command;
     command = "python3 " + getMercuryDPMSourceDir() + "/Tools/SimpleOpt/BatchRun.py " + getMercuryDPMSourceDir() + " " + getMercuryDPMBuildDir();
     std::cout<<ExecCommand(command.c_str())<<std::endl;
     return 0;
 }
References ExecCommand(), getMercuryDPMBuildDir(), getMercuryDPMSourceDir(), and oomph::Global_string_for_annotation::string().