MercuryDPM: Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs > Struct Template Reference
Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs > Struct Template Reference
#include <GeneralBlockPanelKernel.h>
Public Types
enum {
Vectorizable = Traits::Vectorizable , LhsProgress = Traits::LhsProgress , LhsProgressHalf = HalfTraits::LhsProgress , LhsProgressQuarter = QuarterTraits::LhsProgress ,
RhsProgress = Traits::RhsProgress , RhsProgressHalf = HalfTraits::RhsProgress , RhsProgressQuarter = QuarterTraits::RhsProgress , ResPacketSize = Traits::ResPacketSize
}
typedef gebp_traits< LhsScalar, RhsScalar, ConjugateLhs, ConjugateRhs, Architecture::Target > Traits
typedef gebp_traits< LhsScalar, RhsScalar, ConjugateLhs, ConjugateRhs, Architecture::Target, GEBPPacketHalf > HalfTraits
typedef gebp_traits< LhsScalar, RhsScalar, ConjugateLhs, ConjugateRhs, Architecture::Target, GEBPPacketQuarter > QuarterTraits
typedef Traits::ResScalar ResScalar
typedef Traits::LhsPacket LhsPacket
typedef Traits::RhsPacket RhsPacket
typedef Traits::ResPacket ResPacket
typedef Traits::AccPacket AccPacket
typedef Traits::RhsPacketx4 RhsPacketx4
typedef RhsPanelHelper< RhsPacket, RhsPacketx4, 15 >::type RhsPanel15
typedef RhsPanelHelper< RhsPacket, RhsPacketx4, 27 >::type RhsPanel27
typedef gebp_traits< RhsScalar, LhsScalar, ConjugateRhs, ConjugateLhs, Architecture::Target > SwappedTraits
typedef SwappedTraits::ResScalar SResScalar
typedef SwappedTraits::LhsPacket SLhsPacket
typedef SwappedTraits::RhsPacket SRhsPacket
typedef SwappedTraits::ResPacket SResPacket
typedef SwappedTraits::AccPacket SAccPacket
typedef HalfTraits::LhsPacket LhsPacketHalf
typedef HalfTraits::RhsPacket RhsPacketHalf
typedef HalfTraits::ResPacket ResPacketHalf
typedef HalfTraits::AccPacket AccPacketHalf
typedef QuarterTraits::LhsPacket LhsPacketQuarter
typedef QuarterTraits::RhsPacket RhsPacketQuarter
typedef QuarterTraits::ResPacket ResPacketQuarter
typedef QuarterTraits::AccPacket AccPacketQuarter
typedef DataMapper::LinearMapper LinearMapper
Public Member Functions
EIGEN_DONT_INLINE void operator() (const DataMapper &res, const LhsScalar *blockA, const RhsScalar *blockB, Index rows, Index depth, Index cols, ResScalar alpha, Index strideA=-1, Index strideB=-1, Index offsetA=0, Index offsetB=0)
Member Typedef Documentation
AccPacket
template<typename LhsScalar , typename RhsScalar , typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef Traits::AccPacket Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::AccPacket
AccPacketHalf
template<typename LhsScalar , typename RhsScalar , typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef HalfTraits::AccPacket Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::AccPacketHalf
AccPacketQuarter
template<typename LhsScalar , typename RhsScalar , typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef QuarterTraits::AccPacket Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::AccPacketQuarter
HalfTraits
template<typename LhsScalar , typename RhsScalar , typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef gebp_traits<LhsScalar, RhsScalar, ConjugateLhs, ConjugateRhs, Architecture::Target, GEBPPacketHalf> Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::HalfTraits
LhsPacket
template<typename LhsScalar , typename RhsScalar , typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef Traits::LhsPacket Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::LhsPacket
LhsPacketHalf
template<typename LhsScalar , typename RhsScalar , typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef HalfTraits::LhsPacket Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::LhsPacketHalf
LhsPacketQuarter
template<typename LhsScalar , typename RhsScalar , typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef QuarterTraits::LhsPacket Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::LhsPacketQuarter
LinearMapper
template<typename LhsScalar , typename RhsScalar , typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef DataMapper::LinearMapper Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::LinearMapper
QuarterTraits
template<typename LhsScalar , typename RhsScalar , typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef gebp_traits<LhsScalar, RhsScalar, ConjugateLhs, ConjugateRhs, Architecture::Target, GEBPPacketQuarter> Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::QuarterTraits
ResPacket
template<typename LhsScalar , typename RhsScalar , typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef Traits::ResPacket Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::ResPacket
ResPacketHalf
template<typename LhsScalar , typename RhsScalar , typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef HalfTraits::ResPacket Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::ResPacketHalf
ResPacketQuarter
template<typename LhsScalar , typename RhsScalar , typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef QuarterTraits::ResPacket Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::ResPacketQuarter
ResScalar
template<typename LhsScalar , typename RhsScalar , typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef Traits::ResScalar Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::ResScalar
RhsPacket
template<typename LhsScalar , typename RhsScalar , typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef Traits::RhsPacket Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::RhsPacket
RhsPacketHalf
template<typename LhsScalar , typename RhsScalar , typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef HalfTraits::RhsPacket Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::RhsPacketHalf
RhsPacketQuarter
template<typename LhsScalar , typename RhsScalar , typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef QuarterTraits::RhsPacket Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::RhsPacketQuarter
RhsPacketx4
template<typename LhsScalar , typename RhsScalar , typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef Traits::RhsPacketx4 Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::RhsPacketx4
RhsPanel15
template<typename LhsScalar , typename RhsScalar , typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef RhsPanelHelper<RhsPacket, RhsPacketx4, 15>::type Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::RhsPanel15
RhsPanel27
template<typename LhsScalar , typename RhsScalar , typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef RhsPanelHelper<RhsPacket, RhsPacketx4, 27>::type Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::RhsPanel27
SAccPacket
template<typename LhsScalar , typename RhsScalar , typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef SwappedTraits::AccPacket Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::SAccPacket
SLhsPacket
template<typename LhsScalar , typename RhsScalar , typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef SwappedTraits::LhsPacket Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::SLhsPacket
SResPacket
template<typename LhsScalar , typename RhsScalar , typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef SwappedTraits::ResPacket Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::SResPacket
SResScalar
template<typename LhsScalar , typename RhsScalar , typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef SwappedTraits::ResScalar Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::SResScalar
SRhsPacket
template<typename LhsScalar , typename RhsScalar , typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef SwappedTraits::RhsPacket Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::SRhsPacket
SwappedTraits
template<typename LhsScalar , typename RhsScalar , typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef gebp_traits<RhsScalar, LhsScalar, ConjugateRhs, ConjugateLhs, Architecture::Target> Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::SwappedTraits
Traits
template<typename LhsScalar , typename RhsScalar , typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> typedef gebp_traits<LhsScalar, RhsScalar, ConjugateLhs, ConjugateRhs, Architecture::Target> Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::Traits
Member Enumeration Documentation
anonymous enum
template<typename LhsScalar , typename RhsScalar , typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> anonymous enum
Enumerator
Vectorizable
LhsProgress
LhsProgressHalf
LhsProgressQuarter
RhsProgress
RhsProgressHalf
RhsProgressQuarter
ResPacketSize
        {
     Vectorizable = Traits::Vectorizable,
     LhsProgress = Traits::LhsProgress,
     LhsProgressHalf = HalfTraits::LhsProgress,
     LhsProgressQuarter = QuarterTraits::LhsProgress,
     RhsProgress = Traits::RhsProgress,
     RhsProgressHalf = HalfTraits::RhsProgress,
     RhsProgressQuarter = QuarterTraits::RhsProgress,
     ResPacketSize = Traits::ResPacketSize
   };
Member Function Documentation
operator()()
template<typename LhsScalar , typename RhsScalar , typename Index , typename DataMapper , int mr, int nr, bool ConjugateLhs, bool ConjugateRhs> EIGEN_DONT_INLINE void Eigen::internal::gebp_kernel< LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs >::operator() (const DataMapper & res, const LhsScalar * blockA, const RhsScalar * blockB, Index rows, Index depth, Index cols, ResScalar alpha, Index strideA = -1, Index strideB = -1, Index offsetA = 0, Index offsetB = 0)
{
   Traits traits;
   SwappedTraits straits;
   if (strideA == -1) strideA = depth;
   if (strideB == -1) strideB = depth;
   conj_helper<LhsScalar, RhsScalar, ConjugateLhs, ConjugateRhs> cj;
   Index packet_cols4 = nr >= 4 ? (cols / 4) * 4 : 0;
   Index packet_cols8 = nr >= 8 ? (cols / 8) * 8 : 0;
   const Index peeled_mc3 = mr >= 3 * Traits::LhsProgress ? (rows / (3 * LhsProgress)) * (3 * LhsProgress) : 0;
   const Index peeled_mc2 =
       mr >= 2 * Traits::LhsProgress ? peeled_mc3 + ((rows - peeled_mc3) / (2 * LhsProgress)) * (2 * LhsProgress) : 0;
   const Index peeled_mc1 =
       mr >= 1 * Traits::LhsProgress ? peeled_mc2 + ((rows - peeled_mc2) / (1 * LhsProgress)) * (1 * LhsProgress) : 0;
   const Index peeled_mc_half =
       mr >= LhsProgressHalf ? peeled_mc1 + ((rows - peeled_mc1) / (LhsProgressHalf)) * (LhsProgressHalf) : 0;
   const Index peeled_mc_quarter =
       mr >= LhsProgressQuarter
           ? peeled_mc_half + ((rows - peeled_mc_half) / (LhsProgressQuarter)) * (LhsProgressQuarter)
           : 0;
   enum { pk = 8 };  // NOTE Such a large peeling factor is important for large matrices (~ +5% when >1000 on Haswell)
   const Index peeled_kc = depth & ~(pk - 1);
   const int prefetch_res_offset = 32 / sizeof(ResScalar);
   //     const Index depth2     = depth & ~1;
   //---------- Process 3 * LhsProgress rows at once ----------
   // This corresponds to 3*LhsProgress x nr register blocks.
   // Usually, make sense only with FMA
   if (mr >= 3 * Traits::LhsProgress) {
     // Here, the general idea is to loop on each largest micro horizontal panel of the lhs (3*Traits::LhsProgress x
     // depth) and on each largest micro vertical panel of the rhs (depth * nr). Blocking sizes, i.e., 'depth' has been
     // computed so that the micro horizontal panel of the lhs fit in L1. However, if depth is too small, we can extend
     // the number of rows of these horizontal panels. This actual number of rows is computed as follow:
     const Index l1 = defaultL1CacheSize;  // in Bytes, TODO, l1 should be passed to this function.
     // The max(1, ...) here is needed because we may be using blocking params larger than what our known l1 cache size
     // suggests we should be using: either because our known l1 cache size is inaccurate (e.g. on Android, we can only
     // guess), or because we are testing specific blocking sizes.
     const Index actual_panel_rows =
         (3 * LhsProgress) * std::max<Index>(1, ((l1 - sizeof(ResScalar) * mr * nr - depth * nr * sizeof(RhsScalar)) /
                                                 (depth * sizeof(LhsScalar) * 3 * LhsProgress)));
     for (Index i1 = 0; i1 < peeled_mc3; i1 += actual_panel_rows) {
       const Index actual_panel_end = (std::min)(i1 + actual_panel_rows, peeled_mc3);
 #if EIGEN_ARCH_ARM64 || EIGEN_ARCH_LOONGARCH64
       EIGEN_IF_CONSTEXPR(nr >= 8) {
         for (Index j2 = 0; j2 < packet_cols8; j2 += 8) {
           for (Index i = i1; i < actual_panel_end; i += 3 * LhsProgress) {
             const LhsScalar* blA = &blockA[i * strideA + offsetA * (3 * LhsProgress)];
             prefetch(&blA[0]);
             // gets res block as register
             AccPacket C0, C1, C2, C3, C4, C5, C6, C7, C8, C9, C10, C11, C12, C13, C14, C15, C16, C17, C18, C19, C20,
                 C21, C22, C23;
             traits.initAcc(C0);
             traits.initAcc(C1);
             traits.initAcc(C2);
             traits.initAcc(C3);
             traits.initAcc(C4);
             traits.initAcc(C5);
             traits.initAcc(C6);
             traits.initAcc(C7);
             traits.initAcc(C8);
             traits.initAcc(C9);
             traits.initAcc(C10);
             traits.initAcc(C11);
             traits.initAcc(C12);
             traits.initAcc(C13);
             traits.initAcc(C14);
             traits.initAcc(C15);
             traits.initAcc(C16);
             traits.initAcc(C17);
             traits.initAcc(C18);
             traits.initAcc(C19);
             traits.initAcc(C20);
             traits.initAcc(C21);
             traits.initAcc(C22);
             traits.initAcc(C23);
             LinearMapper r0 = res.getLinearMapper(i, j2 + 0);
             LinearMapper r1 = res.getLinearMapper(i, j2 + 1);
             LinearMapper r2 = res.getLinearMapper(i, j2 + 2);
             LinearMapper r3 = res.getLinearMapper(i, j2 + 3);
             LinearMapper r4 = res.getLinearMapper(i, j2 + 4);
             LinearMapper r5 = res.getLinearMapper(i, j2 + 5);
             LinearMapper r6 = res.getLinearMapper(i, j2 + 6);
             LinearMapper r7 = res.getLinearMapper(i, j2 + 7);
             r0.prefetch(0);
             r1.prefetch(0);
             r2.prefetch(0);
             r3.prefetch(0);
             r4.prefetch(0);
             r5.prefetch(0);
             r6.prefetch(0);
             r7.prefetch(0);
             // performs "inner" products
             const RhsScalar* blB = &blockB[j2 * strideB + offsetB * 8];
             prefetch(&blB[0]);
             LhsPacket A0, A1;
             for (Index k = 0; k < peeled_kc; k += pk) {
               EIGEN_ASM_COMMENT("begin gebp micro kernel 3pX8");
               // 27 registers are taken (24 for acc, 3 for lhs).
               RhsPanel27 rhs_panel;
               RhsPacket T0;
               LhsPacket A2;
 #if EIGEN_ARCH_ARM64 && defined(EIGEN_VECTORIZE_NEON) && EIGEN_GNUC_STRICT_LESS_THAN(9, 0, 0)
 // see http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1633
 // without this workaround A0, A1, and A2 are loaded in the same register,
 // which is not good for pipelining
 #define EIGEN_GEBP_3Px8_REGISTER_ALLOC_WORKAROUND __asm__("" : "+w,m"(A0), "+w,m"(A1), "+w,m"(A2));
 #else
 #define EIGEN_GEBP_3Px8_REGISTER_ALLOC_WORKAROUND
 #endif
 #define EIGEN_GEBP_ONESTEP(K)                                                                                     \
   do {                                                                                                            \
     EIGEN_ASM_COMMENT("begin step of gebp micro kernel 3pX8");                                                    \
     traits.loadLhs(&blA[(0 + 3 * K) * LhsProgress], A0);                                                          \
     traits.loadLhs(&blA[(1 + 3 * K) * LhsProgress], A1);                                                          \
     traits.loadLhs(&blA[(2 + 3 * K) * LhsProgress], A2);                                                          \
     EIGEN_GEBP_3Px8_REGISTER_ALLOC_WORKAROUND traits.loadRhs(blB + (0 + 8 * K) * Traits::RhsProgress, rhs_panel); \
     traits.madd(A0, rhs_panel, C0, T0, fix<0>);                                                                   \
     traits.madd(A1, rhs_panel, C8, T0, fix<0>);                                                                   \
     traits.madd(A2, rhs_panel, C16, T0, fix<0>);                                                                  \
     traits.updateRhs(blB + (1 + 8 * K) * Traits::RhsProgress, rhs_panel);                                         \
     traits.madd(A0, rhs_panel, C1, T0, fix<1>);                                                                   \
     traits.madd(A1, rhs_panel, C9, T0, fix<1>);                                                                   \
     traits.madd(A2, rhs_panel, C17, T0, fix<1>);                                                                  \
     traits.updateRhs(blB + (2 + 8 * K) * Traits::RhsProgress, rhs_panel);                                         \
     traits.madd(A0, rhs_panel, C2, T0, fix<2>);                                                                   \
     traits.madd(A1, rhs_panel, C10, T0, fix<2>);                                                                  \
     traits.madd(A2, rhs_panel, C18, T0, fix<2>);                                                                  \
     traits.updateRhs(blB + (3 + 8 * K) * Traits::RhsProgress, rhs_panel);                                         \
     traits.madd(A0, rhs_panel, C3, T0, fix<3>);                                                                   \
     traits.madd(A1, rhs_panel, C11, T0, fix<3>);                                                                  \
     traits.madd(A2, rhs_panel, C19, T0, fix<3>);                                                                  \
     traits.loadRhs(blB + (4 + 8 * K) * Traits::RhsProgress, rhs_panel);                                           \
     traits.madd(A0, rhs_panel, C4, T0, fix<0>);                                                                   \
     traits.madd(A1, rhs_panel, C12, T0, fix<0>);                                                                  \
     traits.madd(A2, rhs_panel, C20, T0, fix<0>);                                                                  \
     traits.updateRhs(blB + (5 + 8 * K) * Traits::RhsProgress, rhs_panel);                                         \
     traits.madd(A0, rhs_panel, C5, T0, fix<1>);                                                                   \
     traits.madd(A1, rhs_panel, C13, T0, fix<1>);                                                                  \
     traits.madd(A2, rhs_panel, C21, T0, fix<1>);                                                                  \
     traits.updateRhs(blB + (6 + 8 * K) * Traits::RhsProgress, rhs_panel);                                         \
     traits.madd(A0, rhs_panel, C6, T0, fix<2>);                                                                   \
     traits.madd(A1, rhs_panel, C14, T0, fix<2>);                                                                  \
     traits.madd(A2, rhs_panel, C22, T0, fix<2>);                                                                  \
     traits.updateRhs(blB + (7 + 8 * K) * Traits::RhsProgress, rhs_panel);                                         \
     traits.madd(A0, rhs_panel, C7, T0, fix<3>);                                                                   \
     traits.madd(A1, rhs_panel, C15, T0, fix<3>);                                                                  \
     traits.madd(A2, rhs_panel, C23, T0, fix<3>);                                                                  \
     EIGEN_ASM_COMMENT("end step of gebp micro kernel 3pX8");                                                      \
   } while (false)
               EIGEN_GEBP_ONESTEP(0);
               EIGEN_GEBP_ONESTEP(1);
               EIGEN_GEBP_ONESTEP(2);
               EIGEN_GEBP_ONESTEP(3);
               EIGEN_GEBP_ONESTEP(4);
               EIGEN_GEBP_ONESTEP(5);
               EIGEN_GEBP_ONESTEP(6);
               EIGEN_GEBP_ONESTEP(7);
               blB += pk * 8 * RhsProgress;
               blA += pk * 3 * Traits::LhsProgress;
               EIGEN_ASM_COMMENT("end gebp micro kernel 3pX8");
             }
             // process remaining peeled loop
             for (Index k = peeled_kc; k < depth; k++) {
               RhsPanel27 rhs_panel;
               RhsPacket T0;
               LhsPacket A2;
               EIGEN_GEBP_ONESTEP(0);
               blB += 8 * RhsProgress;
               blA += 3 * Traits::LhsProgress;
             }
 #undef EIGEN_GEBP_ONESTEP
             ResPacket R0, R1, R2;
             ResPacket alphav = pset1<ResPacket>(alpha);
             R0 = r0.template loadPacket<ResPacket>(0 * Traits::ResPacketSize);
             R1 = r0.template loadPacket<ResPacket>(1 * Traits::ResPacketSize);
             R2 = r0.template loadPacket<ResPacket>(2 * Traits::ResPacketSize);
             traits.acc(C0, alphav, R0);
             traits.acc(C8, alphav, R1);
             traits.acc(C16, alphav, R2);
             r0.storePacket(0 * Traits::ResPacketSize, R0);
             r0.storePacket(1 * Traits::ResPacketSize, R1);
             r0.storePacket(2 * Traits::ResPacketSize, R2);
             R0 = r1.template loadPacket<ResPacket>(0 * Traits::ResPacketSize);
             R1 = r1.template loadPacket<ResPacket>(1 * Traits::ResPacketSize);
             R2 = r1.template loadPacket<ResPacket>(2 * Traits::ResPacketSize);
             traits.acc(C1, alphav, R0);
             traits.acc(C9, alphav, R1);
             traits.acc(C17, alphav, R2);
             r1.storePacket(0 * Traits::ResPacketSize, R0);
             r1.storePacket(1 * Traits::ResPacketSize, R1);
             r1.storePacket(2 * Traits::ResPacketSize, R2);
             R0 = r2.template loadPacket<ResPacket>(0 * Traits::ResPacketSize);
             R1 = r2.template loadPacket<ResPacket>(1 * Traits::ResPacketSize);
             R2 = r2.template loadPacket<ResPacket>(2 * Traits::ResPacketSize);
             traits.acc(C2, alphav, R0);
             traits.acc(C10, alphav, R1);
             traits.acc(C18, alphav, R2);
             r2.storePacket(0 * Traits::ResPacketSize, R0);
             r2.storePacket(1 * Traits::ResPacketSize, R1);
             r2.storePacket(2 * Traits::ResPacketSize, R2);
             R0 = r3.template loadPacket<ResPacket>(0 * Traits::ResPacketSize);
             R1 = r3.template loadPacket<ResPacket>(1 * Traits::ResPacketSize);
             R2 = r3.template loadPacket<ResPacket>(2 * Traits::ResPacketSize);
             traits.acc(C3, alphav, R0);
             traits.acc(C11, alphav, R1);
             traits.acc(C19, alphav, R2);
             r3.storePacket(0 * Traits::ResPacketSize, R0);
             r3.storePacket(1 * Traits::ResPacketSize, R1);
             r3.storePacket(2 * Traits::ResPacketSize, R2);
             R0 = r4.template loadPacket<ResPacket>(0 * Traits::ResPacketSize);
             R1 = r4.template loadPacket<ResPacket>(1 * Traits::ResPacketSize);
             R2 = r4.template loadPacket<ResPacket>(2 * Traits::ResPacketSize);
             traits.acc(C4, alphav, R0);
             traits.acc(C12, alphav, R1);
             traits.acc(C20, alphav, R2);
             r4.storePacket(0 * Traits::ResPacketSize, R0);
             r4.storePacket(1 * Traits::ResPacketSize, R1);
             r4.storePacket(2 * Traits::ResPacketSize, R2);
             R0 = r5.template loadPacket<ResPacket>(0 * Traits::ResPacketSize);
             R1 = r5.template loadPacket<ResPacket>(1 * Traits::ResPacketSize);
             R2 = r5.template loadPacket<ResPacket>(2 * Traits::ResPacketSize);
             traits.acc(C5, alphav, R0);
             traits.acc(C13, alphav, R1);
             traits.acc(C21, alphav, R2);
             r5.storePacket(0 * Traits::ResPacketSize, R0);
             r5.storePacket(1 * Traits::ResPacketSize, R1);
             r5.storePacket(2 * Traits::ResPacketSize, R2);
             R0 = r6.template loadPacket<ResPacket>(0 * Traits::ResPacketSize);
             R1 = r6.template loadPacket<ResPacket>(1 * Traits::ResPacketSize);
             R2 = r6.template loadPacket<ResPacket>(2 * Traits::ResPacketSize);
             traits.acc(C6, alphav, R0);
             traits.acc(C14, alphav, R1);
             traits.acc(C22, alphav, R2);
             r6.storePacket(0 * Traits::ResPacketSize, R0);
             r6.storePacket(1 * Traits::ResPacketSize, R1);
             r6.storePacket(2 * Traits::ResPacketSize, R2);
             R0 = r7.template loadPacket<ResPacket>(0 * Traits::ResPacketSize);
             R1 = r7.template loadPacket<ResPacket>(1 * Traits::ResPacketSize);
             R2 = r7.template loadPacket<ResPacket>(2 * Traits::ResPacketSize);
             traits.acc(C7, alphav, R0);
             traits.acc(C15, alphav, R1);
             traits.acc(C23, alphav, R2);
             r7.storePacket(0 * Traits::ResPacketSize, R0);
             r7.storePacket(1 * Traits::ResPacketSize, R1);
             r7.storePacket(2 * Traits::ResPacketSize, R2);
           }
         }
       }
 #endif
       for (Index j2 = packet_cols8; j2 < packet_cols4; j2 += 4) {
         for (Index i = i1; i < actual_panel_end; i += 3 * LhsProgress) {
           // We selected a 3*Traits::LhsProgress x nr micro block of res which is entirely
           // stored into 3 x nr registers.
           const LhsScalar* blA = &blockA[i * strideA + offsetA * (3 * LhsProgress)];
           prefetch(&blA[0]);
           // gets res block as register
           AccPacket C0, C1, C2, C3, C4, C5, C6, C7, C8, C9, C10, C11;
           traits.initAcc(C0);
           traits.initAcc(C1);
           traits.initAcc(C2);
           traits.initAcc(C3);
           traits.initAcc(C4);
           traits.initAcc(C5);
           traits.initAcc(C6);
           traits.initAcc(C7);
           traits.initAcc(C8);
           traits.initAcc(C9);
           traits.initAcc(C10);
           traits.initAcc(C11);
           LinearMapper r0 = res.getLinearMapper(i, j2 + 0);
           LinearMapper r1 = res.getLinearMapper(i, j2 + 1);
           LinearMapper r2 = res.getLinearMapper(i, j2 + 2);
           LinearMapper r3 = res.getLinearMapper(i, j2 + 3);
           r0.prefetch(0);
           r1.prefetch(0);
           r2.prefetch(0);
           r3.prefetch(0);
           // performs "inner" products
           const RhsScalar* blB = &blockB[j2 * strideB + offsetB * 4];
           prefetch(&blB[0]);
           LhsPacket A0, A1;
           for (Index k = 0; k < peeled_kc; k += pk) {
             EIGEN_ASM_COMMENT("begin gebp micro kernel 3pX4");
             // 15 registers are taken (12 for acc, 3 for lhs).
             RhsPanel15 rhs_panel;
             RhsPacket T0;
             LhsPacket A2;
 #if EIGEN_ARCH_ARM64 && defined(EIGEN_VECTORIZE_NEON) && EIGEN_GNUC_STRICT_LESS_THAN(9, 0, 0)
 // see http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1633
 // without this workaround A0, A1, and A2 are loaded in the same register,
 // which is not good for pipelining
 #define EIGEN_GEBP_3PX4_REGISTER_ALLOC_WORKAROUND __asm__("" : "+w,m"(A0), "+w,m"(A1), "+w,m"(A2));
 #else
 #define EIGEN_GEBP_3PX4_REGISTER_ALLOC_WORKAROUND
 #endif
 #define EIGEN_GEBP_ONESTEP(K)                                             \
   do {                                                                    \
     EIGEN_ASM_COMMENT("begin step of gebp micro kernel 3pX4");            \
     EIGEN_ASM_COMMENT("Note: these asm comments work around bug 935!");   \
     internal::prefetch(blA + (3 * K + 16) * LhsProgress);                 \
     if (EIGEN_ARCH_ARM || EIGEN_ARCH_MIPS) {                              \
       internal::prefetch(blB + (4 * K + 16) * RhsProgress);               \
     } /* Bug 953 */                                                       \
     traits.loadLhs(&blA[(0 + 3 * K) * LhsProgress], A0);                  \
     traits.loadLhs(&blA[(1 + 3 * K) * LhsProgress], A1);                  \
     traits.loadLhs(&blA[(2 + 3 * K) * LhsProgress], A2);                  \
     EIGEN_GEBP_3PX4_REGISTER_ALLOC_WORKAROUND                             \
     traits.loadRhs(blB + (0 + 4 * K) * Traits::RhsProgress, rhs_panel);   \
     traits.madd(A0, rhs_panel, C0, T0, fix<0>);                           \
     traits.madd(A1, rhs_panel, C4, T0, fix<0>);                           \
     traits.madd(A2, rhs_panel, C8, T0, fix<0>);                           \
     traits.updateRhs(blB + (1 + 4 * K) * Traits::RhsProgress, rhs_panel); \
     traits.madd(A0, rhs_panel, C1, T0, fix<1>);                           \
     traits.madd(A1, rhs_panel, C5, T0, fix<1>);                           \
     traits.madd(A2, rhs_panel, C9, T0, fix<1>);                           \
     traits.updateRhs(blB + (2 + 4 * K) * Traits::RhsProgress, rhs_panel); \
     traits.madd(A0, rhs_panel, C2, T0, fix<2>);                           \
     traits.madd(A1, rhs_panel, C6, T0, fix<2>);                           \
     traits.madd(A2, rhs_panel, C10, T0, fix<2>);                          \
     traits.updateRhs(blB + (3 + 4 * K) * Traits::RhsProgress, rhs_panel); \
     traits.madd(A0, rhs_panel, C3, T0, fix<3>);                           \
     traits.madd(A1, rhs_panel, C7, T0, fix<3>);                           \
     traits.madd(A2, rhs_panel, C11, T0, fix<3>);                          \
     EIGEN_ASM_COMMENT("end step of gebp micro kernel 3pX4");              \
   } while (false)
             internal::prefetch(blB);
             EIGEN_GEBP_ONESTEP(0);
             EIGEN_GEBP_ONESTEP(1);
             EIGEN_GEBP_ONESTEP(2);
             EIGEN_GEBP_ONESTEP(3);
             EIGEN_GEBP_ONESTEP(4);
             EIGEN_GEBP_ONESTEP(5);
             EIGEN_GEBP_ONESTEP(6);
             EIGEN_GEBP_ONESTEP(7);
             blB += pk * 4 * RhsProgress;
             blA += pk * 3 * Traits::LhsProgress;
             EIGEN_ASM_COMMENT("end gebp micro kernel 3pX4");
           }
           // process remaining peeled loop
           for (Index k = peeled_kc; k < depth; k++) {
             RhsPanel15 rhs_panel;
             RhsPacket T0;
             LhsPacket A2;
             EIGEN_GEBP_ONESTEP(0);
             blB += 4 * RhsProgress;
             blA += 3 * Traits::LhsProgress;
           }
 #undef EIGEN_GEBP_ONESTEP
           ResPacket R0, R1, R2;
           ResPacket alphav = pset1<ResPacket>(alpha);
           R0 = r0.template loadPacket<ResPacket>(0 * Traits::ResPacketSize);
           R1 = r0.template loadPacket<ResPacket>(1 * Traits::ResPacketSize);
           R2 = r0.template loadPacket<ResPacket>(2 * Traits::ResPacketSize);
           traits.acc(C0, alphav, R0);
           traits.acc(C4, alphav, R1);
           traits.acc(C8, alphav, R2);
           r0.storePacket(0 * Traits::ResPacketSize, R0);
           r0.storePacket(1 * Traits::ResPacketSize, R1);
           r0.storePacket(2 * Traits::ResPacketSize, R2);
           R0 = r1.template loadPacket<ResPacket>(0 * Traits::ResPacketSize);
           R1 = r1.template loadPacket<ResPacket>(1 * Traits::ResPacketSize);
           R2 = r1.template loadPacket<ResPacket>(2 * Traits::ResPacketSize);
           traits.acc(C1, alphav, R0);
           traits.acc(C5, alphav, R1);
           traits.acc(C9, alphav, R2);
           r1.storePacket(0 * Traits::ResPacketSize, R0);
           r1.storePacket(1 * Traits::ResPacketSize, R1);
           r1.storePacket(2 * Traits::ResPacketSize, R2);
           R0 = r2.template loadPacket<ResPacket>(0 * Traits::ResPacketSize);
           R1 = r2.template loadPacket<ResPacket>(1 * Traits::ResPacketSize);
           R2 = r2.template loadPacket<ResPacket>(2 * Traits::ResPacketSize);
           traits.acc(C2, alphav, R0);
           traits.acc(C6, alphav, R1);
           traits.acc(C10, alphav, R2);
           r2.storePacket(0 * Traits::ResPacketSize, R0);
           r2.storePacket(1 * Traits::ResPacketSize, R1);
           r2.storePacket(2 * Traits::ResPacketSize, R2);
           R0 = r3.template loadPacket<ResPacket>(0 * Traits::ResPacketSize);
           R1 = r3.template loadPacket<ResPacket>(1 * Traits::ResPacketSize);
           R2 = r3.template loadPacket<ResPacket>(2 * Traits::ResPacketSize);
           traits.acc(C3, alphav, R0);
           traits.acc(C7, alphav, R1);
           traits.acc(C11, alphav, R2);
           r3.storePacket(0 * Traits::ResPacketSize, R0);
           r3.storePacket(1 * Traits::ResPacketSize, R1);
           r3.storePacket(2 * Traits::ResPacketSize, R2);
         }
       }
       // Deal with remaining columns of the rhs
       for (Index j2 = packet_cols4; j2 < cols; j2++) {
         for (Index i = i1; i < actual_panel_end; i += 3 * LhsProgress) {
           // One column at a time
           const LhsScalar* blA = &blockA[i * strideA + offsetA * (3 * Traits::LhsProgress)];
           prefetch(&blA[0]);
           // gets res block as register
           AccPacket C0, C4, C8;
           traits.initAcc(C0);
           traits.initAcc(C4);
           traits.initAcc(C8);
           LinearMapper r0 = res.getLinearMapper(i, j2);
           r0.prefetch(0);
           // performs "inner" products
           const RhsScalar* blB = &blockB[j2 * strideB + offsetB];
           LhsPacket A0, A1, A2;
           for (Index k = 0; k < peeled_kc; k += pk) {
             EIGEN_ASM_COMMENT("begin gebp micro kernel 3pX1");
             RhsPacket B_0;
 #define EIGEN_GEBGP_ONESTEP(K)                                          \
   do {                                                                  \
     EIGEN_ASM_COMMENT("begin step of gebp micro kernel 3pX1");          \
     EIGEN_ASM_COMMENT("Note: these asm comments work around bug 935!"); \
     traits.loadLhs(&blA[(0 + 3 * K) * LhsProgress], A0);                \
     traits.loadLhs(&blA[(1 + 3 * K) * LhsProgress], A1);                \
     traits.loadLhs(&blA[(2 + 3 * K) * LhsProgress], A2);                \
     traits.loadRhs(&blB[(0 + K) * RhsProgress], B_0);                   \
     traits.madd(A0, B_0, C0, B_0, fix<0>);                              \
     traits.madd(A1, B_0, C4, B_0, fix<0>);                              \
     traits.madd(A2, B_0, C8, B_0, fix<0>);                              \
     EIGEN_ASM_COMMENT("end step of gebp micro kernel 3pX1");            \
   } while (false)
             EIGEN_GEBGP_ONESTEP(0);
             EIGEN_GEBGP_ONESTEP(1);
             EIGEN_GEBGP_ONESTEP(2);
             EIGEN_GEBGP_ONESTEP(3);
             EIGEN_GEBGP_ONESTEP(4);
             EIGEN_GEBGP_ONESTEP(5);
             EIGEN_GEBGP_ONESTEP(6);
             EIGEN_GEBGP_ONESTEP(7);
             blB += int(pk) * int(RhsProgress);
             blA += int(pk) * 3 * int(Traits::LhsProgress);
             EIGEN_ASM_COMMENT("end gebp micro kernel 3pX1");
           }
           // process remaining peeled loop
           for (Index k = peeled_kc; k < depth; k++) {
             RhsPacket B_0;
             EIGEN_GEBGP_ONESTEP(0);
             blB += RhsProgress;
             blA += 3 * Traits::LhsProgress;
           }
 #undef EIGEN_GEBGP_ONESTEP
           ResPacket R0, R1, R2;
           ResPacket alphav = pset1<ResPacket>(alpha);
           R0 = r0.template loadPacket<ResPacket>(0 * Traits::ResPacketSize);
           R1 = r0.template loadPacket<ResPacket>(1 * Traits::ResPacketSize);
           R2 = r0.template loadPacket<ResPacket>(2 * Traits::ResPacketSize);
           traits.acc(C0, alphav, R0);
           traits.acc(C4, alphav, R1);
           traits.acc(C8, alphav, R2);
           r0.storePacket(0 * Traits::ResPacketSize, R0);
           r0.storePacket(1 * Traits::ResPacketSize, R1);
           r0.storePacket(2 * Traits::ResPacketSize, R2);
         }
       }
     }
   }
   //---------- Process 2 * LhsProgress rows at once ----------
   if (mr >= 2 * Traits::LhsProgress) {
     const Index l1 = defaultL1CacheSize;  // in Bytes, TODO, l1 should be passed to this function.
     // The max(1, ...) here is needed because we may be using blocking params larger than what our known l1 cache size
     // suggests we should be using: either because our known l1 cache size is inaccurate (e.g. on Android, we can only
     // guess), or because we are testing specific blocking sizes.
     Index actual_panel_rows =
         (2 * LhsProgress) * std::max<Index>(1, ((l1 - sizeof(ResScalar) * mr * nr - depth * nr * sizeof(RhsScalar)) /
                                                 (depth * sizeof(LhsScalar) * 2 * LhsProgress)));
     for (Index i1 = peeled_mc3; i1 < peeled_mc2; i1 += actual_panel_rows) {
       Index actual_panel_end = (std::min)(i1 + actual_panel_rows, peeled_mc2);
 #if EIGEN_ARCH_ARM64 || EIGEN_ARCH_LOONGARCH64
       EIGEN_IF_CONSTEXPR(nr >= 8) {
         for (Index j2 = 0; j2 < packet_cols8; j2 += 8) {
           for (Index i = i1; i < actual_panel_end; i += 2 * LhsProgress) {
             const LhsScalar* blA = &blockA[i * strideA + offsetA * (2 * Traits::LhsProgress)];
             prefetch(&blA[0]);
             AccPacket C0, C1, C2, C3, C4, C5, C6, C7, C8, C9, C10, C11, C12, C13, C14, C15;
             traits.initAcc(C0);
             traits.initAcc(C1);
             traits.initAcc(C2);
             traits.initAcc(C3);
             traits.initAcc(C4);
             traits.initAcc(C5);
             traits.initAcc(C6);
             traits.initAcc(C7);
             traits.initAcc(C8);
             traits.initAcc(C9);
             traits.initAcc(C10);
             traits.initAcc(C11);
             traits.initAcc(C12);
             traits.initAcc(C13);
             traits.initAcc(C14);
             traits.initAcc(C15);
             LinearMapper r0 = res.getLinearMapper(i, j2 + 0);
             LinearMapper r1 = res.getLinearMapper(i, j2 + 1);
             LinearMapper r2 = res.getLinearMapper(i, j2 + 2);
             LinearMapper r3 = res.getLinearMapper(i, j2 + 3);
             LinearMapper r4 = res.getLinearMapper(i, j2 + 4);
             LinearMapper r5 = res.getLinearMapper(i, j2 + 5);
             LinearMapper r6 = res.getLinearMapper(i, j2 + 6);
             LinearMapper r7 = res.getLinearMapper(i, j2 + 7);
             r0.prefetch(prefetch_res_offset);
             r1.prefetch(prefetch_res_offset);
             r2.prefetch(prefetch_res_offset);
             r3.prefetch(prefetch_res_offset);
             r4.prefetch(prefetch_res_offset);
             r5.prefetch(prefetch_res_offset);
             r6.prefetch(prefetch_res_offset);
             r7.prefetch(prefetch_res_offset);
             const RhsScalar* blB = &blockB[j2 * strideB + offsetB * 8];
             prefetch(&blB[0]);
             LhsPacket A0, A1;
             for (Index k = 0; k < peeled_kc; k += pk) {
               RhsPacketx4 rhs_panel;
               RhsPacket T0;
 // NOTE: the begin/end asm comments below work around bug 935!
 // but they are not enough for gcc>=6 without FMA (bug 1637)
 #if EIGEN_GNUC_STRICT_AT_LEAST(6, 0, 0) && defined(EIGEN_VECTORIZE_SSE)
 #define EIGEN_GEBP_2Px8_SPILLING_WORKAROUND __asm__("" : [a0] "+x,m"(A0), [a1] "+x,m"(A1));
 #else
 #define EIGEN_GEBP_2Px8_SPILLING_WORKAROUND
 #endif
 #define EIGEN_GEBGP_ONESTEP(K)                                                                   \
   do {                                                                                           \
     EIGEN_ASM_COMMENT("begin step of gebp micro kernel 2pX8");                                   \
     traits.loadLhs(&blA[(0 + 2 * K) * LhsProgress], A0);                                         \
     traits.loadLhs(&blA[(1 + 2 * K) * LhsProgress], A1);                                         \
     traits.loadRhs(&blB[(0 + 8 * K) * RhsProgress], rhs_panel);                                  \
     traits.madd(A0, rhs_panel, C0, T0, fix<0>);                                                  \
     traits.madd(A1, rhs_panel, C8, T0, fix<0>);                                                  \
     traits.updateRhs(&blB[(1 + 8 * K) * RhsProgress], rhs_panel);                                \
     traits.madd(A0, rhs_panel, C1, T0, fix<1>);                                                  \
     traits.madd(A1, rhs_panel, C9, T0, fix<1>);                                                  \
     traits.updateRhs(&blB[(2 + 8 * K) * RhsProgress], rhs_panel);                                \
     traits.madd(A0, rhs_panel, C2, T0, fix<2>);                                                  \
     traits.madd(A1, rhs_panel, C10, T0, fix<2>);                                                 \
     traits.updateRhs(&blB[(3 + 8 * K) * RhsProgress], rhs_panel);                                \
     traits.madd(A0, rhs_panel, C3, T0, fix<3>);                                                  \
     traits.madd(A1, rhs_panel, C11, T0, fix<3>);                                                 \
     traits.loadRhs(&blB[(4 + 8 * K) * RhsProgress], rhs_panel);                                  \
     traits.madd(A0, rhs_panel, C4, T0, fix<0>);                                                  \
     traits.madd(A1, rhs_panel, C12, T0, fix<0>);                                                 \
     traits.updateRhs(&blB[(5 + 8 * K) * RhsProgress], rhs_panel);                                \
     traits.madd(A0, rhs_panel, C5, T0, fix<1>);                                                  \
     traits.madd(A1, rhs_panel, C13, T0, fix<1>);                                                 \
     traits.updateRhs(&blB[(6 + 8 * K) * RhsProgress], rhs_panel);                                \
     traits.madd(A0, rhs_panel, C6, T0, fix<2>);                                                  \
     traits.madd(A1, rhs_panel, C14, T0, fix<2>);                                                 \
     traits.updateRhs(&blB[(7 + 8 * K) * RhsProgress], rhs_panel);                                \
     traits.madd(A0, rhs_panel, C7, T0, fix<3>);                                                  \
     traits.madd(A1, rhs_panel, C15, T0, fix<3>);                                                 \
     EIGEN_GEBP_2Px8_SPILLING_WORKAROUND EIGEN_ASM_COMMENT("end step of gebp micro kernel 2pX8"); \
   } while (false)
               EIGEN_ASM_COMMENT("begin gebp micro kernel 2pX8");
               EIGEN_GEBGP_ONESTEP(0);
               EIGEN_GEBGP_ONESTEP(1);
               EIGEN_GEBGP_ONESTEP(2);
               EIGEN_GEBGP_ONESTEP(3);
               EIGEN_GEBGP_ONESTEP(4);
               EIGEN_GEBGP_ONESTEP(5);
               EIGEN_GEBGP_ONESTEP(6);
               EIGEN_GEBGP_ONESTEP(7);
               blB += pk * 8 * RhsProgress;
               blA += pk * (2 * Traits::LhsProgress);
               EIGEN_ASM_COMMENT("end gebp micro kernel 2pX8");
             }
             // process remaining peeled loop
             for (Index k = peeled_kc; k < depth; k++) {
               RhsPacketx4 rhs_panel;
               RhsPacket T0;
               EIGEN_GEBGP_ONESTEP(0);
               blB += 8 * RhsProgress;
               blA += 2 * Traits::LhsProgress;
             }
 #undef EIGEN_GEBGP_ONESTEP
             ResPacket R0, R1, R2, R3;
             ResPacket alphav = pset1<ResPacket>(alpha);
             R0 = r0.template loadPacket<ResPacket>(0 * Traits::ResPacketSize);
             R1 = r0.template loadPacket<ResPacket>(1 * Traits::ResPacketSize);
             R2 = r1.template loadPacket<ResPacket>(0 * Traits::ResPacketSize);
             R3 = r1.template loadPacket<ResPacket>(1 * Traits::ResPacketSize);
             traits.acc(C0, alphav, R0);
             traits.acc(C8, alphav, R1);
             traits.acc(C1, alphav, R2);
             traits.acc(C9, alphav, R3);
             r0.storePacket(0 * Traits::ResPacketSize, R0);
             r0.storePacket(1 * Traits::ResPacketSize, R1);
             r1.storePacket(0 * Traits::ResPacketSize, R2);
             r1.storePacket(1 * Traits::ResPacketSize, R3);
             R0 = r2.template loadPacket<ResPacket>(0 * Traits::ResPacketSize);
             R1 = r2.template loadPacket<ResPacket>(1 * Traits::ResPacketSize);
             R2 = r3.template loadPacket<ResPacket>(0 * Traits::ResPacketSize);
             R3 = r3.template loadPacket<ResPacket>(1 * Traits::ResPacketSize);
             traits.acc(C2, alphav, R0);
             traits.acc(C10, alphav, R1);
             traits.acc(C3, alphav, R2);
             traits.acc(C11, alphav, R3);
             r2.storePacket(0 * Traits::ResPacketSize, R0);
             r2.storePacket(1 * Traits::ResPacketSize, R1);
             r3.storePacket(0 * Traits::ResPacketSize, R2);
             r3.storePacket(1 * Traits::ResPacketSize, R3);
             R0 = r4.template loadPacket<ResPacket>(0 * Traits::ResPacketSize);
             R1 = r4.template loadPacket<ResPacket>(1 * Traits::ResPacketSize);
             R2 = r5.template loadPacket<ResPacket>(0 * Traits::ResPacketSize);
             R3 = r5.template loadPacket<ResPacket>(1 * Traits::ResPacketSize);
             traits.acc(C4, alphav, R0);
             traits.acc(C12, alphav, R1);
             traits.acc(C5, alphav, R2);
             traits.acc(C13, alphav, R3);
             r4.storePacket(0 * Traits::ResPacketSize, R0);
             r4.storePacket(1 * Traits::ResPacketSize, R1);
             r5.storePacket(0 * Traits::ResPacketSize, R2);
             r5.storePacket(1 * Traits::ResPacketSize, R3);
             R0 = r6.template loadPacket<ResPacket>(0 * Traits::ResPacketSize);
             R1 = r6.template loadPacket<ResPacket>(1 * Traits::ResPacketSize);
             R2 = r7.template loadPacket<ResPacket>(0 * Traits::ResPacketSize);
             R3 = r7.template loadPacket<ResPacket>(1 * Traits::ResPacketSize);
             traits.acc(C6, alphav, R0);
             traits.acc(C14, alphav, R1);
             traits.acc(C7, alphav, R2);
             traits.acc(C15, alphav, R3);
             r6.storePacket(0 * Traits::ResPacketSize, R0);
             r6.storePacket(1 * Traits::ResPacketSize, R1);
             r7.storePacket(0 * Traits::ResPacketSize, R2);
             r7.storePacket(1 * Traits::ResPacketSize, R3);
           }
         }
       }
 #endif
       for (Index j2 = packet_cols8; j2 < packet_cols4; j2 += 4) {
         for (Index i = i1; i < actual_panel_end; i += 2 * LhsProgress) {
           // We selected a 2*Traits::LhsProgress x nr micro block of res which is entirely
           // stored into 2 x nr registers.
           const LhsScalar* blA = &blockA[i * strideA + offsetA * (2 * Traits::LhsProgress)];
           prefetch(&blA[0]);
           // gets res block as register
           AccPacket C0, C1, C2, C3, C4, C5, C6, C7;
           traits.initAcc(C0);
           traits.initAcc(C1);
           traits.initAcc(C2);
           traits.initAcc(C3);
           traits.initAcc(C4);
           traits.initAcc(C5);
           traits.initAcc(C6);
           traits.initAcc(C7);
           LinearMapper r0 = res.getLinearMapper(i, j2 + 0);
           LinearMapper r1 = res.getLinearMapper(i, j2 + 1);
           LinearMapper r2 = res.getLinearMapper(i, j2 + 2);
           LinearMapper r3 = res.getLinearMapper(i, j2 + 3);
           r0.prefetch(prefetch_res_offset);
           r1.prefetch(prefetch_res_offset);
           r2.prefetch(prefetch_res_offset);
           r3.prefetch(prefetch_res_offset);
           // performs "inner" products
           const RhsScalar* blB = &blockB[j2 * strideB + offsetB * 4];
           prefetch(&blB[0]);
           LhsPacket A0, A1;
           for (Index k = 0; k < peeled_kc; k += pk) {
             EIGEN_ASM_COMMENT("begin gebp micro kernel 2pX4");
             RhsPacketx4 rhs_panel;
             RhsPacket T0;
 // NOTE: the begin/end asm comments below work around bug 935!
 // but they are not enough for gcc>=6 without FMA (bug 1637)
 #if EIGEN_GNUC_STRICT_AT_LEAST(6, 0, 0) && defined(EIGEN_VECTORIZE_SSE) && !(EIGEN_COMP_LCC)
 #define EIGEN_GEBP_2PX4_SPILLING_WORKAROUND __asm__("" : [a0] "+x,m"(A0), [a1] "+x,m"(A1));
 #else
 #define EIGEN_GEBP_2PX4_SPILLING_WORKAROUND
 #endif
 #define EIGEN_GEBGP_ONESTEP(K)                                  \
   do {                                                          \
     EIGEN_ASM_COMMENT("begin step of gebp micro kernel 2pX4");  \
     traits.loadLhs(&blA[(0 + 2 * K) * LhsProgress], A0);        \
     traits.loadLhs(&blA[(1 + 2 * K) * LhsProgress], A1);        \
     traits.loadRhs(&blB[(0 + 4 * K) * RhsProgress], rhs_panel); \
     traits.madd(A0, rhs_panel, C0, T0, fix<0>);                 \
     traits.madd(A1, rhs_panel, C4, T0, fix<0>);                 \
     traits.madd(A0, rhs_panel, C1, T0, fix<1>);                 \
     traits.madd(A1, rhs_panel, C5, T0, fix<1>);                 \
     traits.madd(A0, rhs_panel, C2, T0, fix<2>);                 \
     traits.madd(A1, rhs_panel, C6, T0, fix<2>);                 \
     traits.madd(A0, rhs_panel, C3, T0, fix<3>);                 \
     traits.madd(A1, rhs_panel, C7, T0, fix<3>);                 \
     EIGEN_GEBP_2PX4_SPILLING_WORKAROUND                         \
     EIGEN_ASM_COMMENT("end step of gebp micro kernel 2pX4");    \
   } while (false)
             internal::prefetch(blB + (48 + 0));
             EIGEN_GEBGP_ONESTEP(0);
             EIGEN_GEBGP_ONESTEP(1);
             EIGEN_GEBGP_ONESTEP(2);
             EIGEN_GEBGP_ONESTEP(3);
             internal::prefetch(blB + (48 + 16));
             EIGEN_GEBGP_ONESTEP(4);
             EIGEN_GEBGP_ONESTEP(5);
             EIGEN_GEBGP_ONESTEP(6);
             EIGEN_GEBGP_ONESTEP(7);
             blB += pk * 4 * RhsProgress;
             blA += pk * (2 * Traits::LhsProgress);
             EIGEN_ASM_COMMENT("end gebp micro kernel 2pX4");
           }
           // process remaining peeled loop
           for (Index k = peeled_kc; k < depth; k++) {
             RhsPacketx4 rhs_panel;
             RhsPacket T0;
             EIGEN_GEBGP_ONESTEP(0);
             blB += 4 * RhsProgress;
             blA += 2 * Traits::LhsProgress;
           }
 #undef EIGEN_GEBGP_ONESTEP
           ResPacket R0, R1, R2, R3;
           ResPacket alphav = pset1<ResPacket>(alpha);
           R0 = r0.template loadPacket<ResPacket>(0 * Traits::ResPacketSize);
           R1 = r0.template loadPacket<ResPacket>(1 * Traits::ResPacketSize);
           R2 = r1.template loadPacket<ResPacket>(0 * Traits::ResPacketSize);
           R3 = r1.template loadPacket<ResPacket>(1 * Traits::ResPacketSize);
           traits.acc(C0, alphav, R0);
           traits.acc(C4, alphav, R1);
           traits.acc(C1, alphav, R2);
           traits.acc(C5, alphav, R3);
           r0.storePacket(0 * Traits::ResPacketSize, R0);
           r0.storePacket(1 * Traits::ResPacketSize, R1);
           r1.storePacket(0 * Traits::ResPacketSize, R2);
           r1.storePacket(1 * Traits::ResPacketSize, R3);
           R0 = r2.template loadPacket<ResPacket>(0 * Traits::ResPacketSize);
           R1 = r2.template loadPacket<ResPacket>(1 * Traits::ResPacketSize);
           R2 = r3.template loadPacket<ResPacket>(0 * Traits::ResPacketSize);
           R3 = r3.template loadPacket<ResPacket>(1 * Traits::ResPacketSize);
           traits.acc(C2, alphav, R0);
           traits.acc(C6, alphav, R1);
           traits.acc(C3, alphav, R2);
           traits.acc(C7, alphav, R3);
           r2.storePacket(0 * Traits::ResPacketSize, R0);
           r2.storePacket(1 * Traits::ResPacketSize, R1);
           r3.storePacket(0 * Traits::ResPacketSize, R2);
           r3.storePacket(1 * Traits::ResPacketSize, R3);
         }
       }
       // Deal with remaining columns of the rhs
       for (Index j2 = packet_cols4; j2 < cols; j2++) {
         for (Index i = i1; i < actual_panel_end; i += 2 * LhsProgress) {
           // One column at a time
           const LhsScalar* blA = &blockA[i * strideA + offsetA * (2 * Traits::LhsProgress)];
           prefetch(&blA[0]);
           // gets res block as register
           AccPacket C0, C4;
           traits.initAcc(C0);
           traits.initAcc(C4);
           LinearMapper r0 = res.getLinearMapper(i, j2);
           r0.prefetch(prefetch_res_offset);
           // performs "inner" products
           const RhsScalar* blB = &blockB[j2 * strideB + offsetB];
           LhsPacket A0, A1;
           for (Index k = 0; k < peeled_kc; k += pk) {
             EIGEN_ASM_COMMENT("begin gebp micro kernel 2pX1");
             RhsPacket B_0, B1;
 #define EIGEN_GEBGP_ONESTEP(K)                                          \
   do {                                                                  \
     EIGEN_ASM_COMMENT("begin step of gebp micro kernel 2pX1");          \
     EIGEN_ASM_COMMENT("Note: these asm comments work around bug 935!"); \
     traits.loadLhs(&blA[(0 + 2 * K) * LhsProgress], A0);                \
     traits.loadLhs(&blA[(1 + 2 * K) * LhsProgress], A1);                \
     traits.loadRhs(&blB[(0 + K) * RhsProgress], B_0);                   \
     traits.madd(A0, B_0, C0, B1, fix<0>);                               \
     traits.madd(A1, B_0, C4, B_0, fix<0>);                              \
     EIGEN_ASM_COMMENT("end step of gebp micro kernel 2pX1");            \
   } while (false)
             EIGEN_GEBGP_ONESTEP(0);
             EIGEN_GEBGP_ONESTEP(1);
             EIGEN_GEBGP_ONESTEP(2);
             EIGEN_GEBGP_ONESTEP(3);
             EIGEN_GEBGP_ONESTEP(4);
             EIGEN_GEBGP_ONESTEP(5);
             EIGEN_GEBGP_ONESTEP(6);
             EIGEN_GEBGP_ONESTEP(7);
             blB += int(pk) * int(RhsProgress);
             blA += int(pk) * 2 * int(Traits::LhsProgress);
             EIGEN_ASM_COMMENT("end gebp micro kernel 2pX1");
           }
           // process remaining peeled loop
           for (Index k = peeled_kc; k < depth; k++) {
             RhsPacket B_0, B1;
             EIGEN_GEBGP_ONESTEP(0);
             blB += RhsProgress;
             blA += 2 * Traits::LhsProgress;
           }
 #undef EIGEN_GEBGP_ONESTEP
           ResPacket R0, R1;
           ResPacket alphav = pset1<ResPacket>(alpha);
           R0 = r0.template loadPacket<ResPacket>(0 * Traits::ResPacketSize);
           R1 = r0.template loadPacket<ResPacket>(1 * Traits::ResPacketSize);
           traits.acc(C0, alphav, R0);
           traits.acc(C4, alphav, R1);
           r0.storePacket(0 * Traits::ResPacketSize, R0);
           r0.storePacket(1 * Traits::ResPacketSize, R1);
         }
       }
     }
   }
   //---------- Process 1 * LhsProgress rows at once ----------
   if (mr >= 1 * Traits::LhsProgress) {
     lhs_process_one_packet<nr, LhsProgress, RhsProgress, LhsScalar, RhsScalar, ResScalar, AccPacket, LhsPacket,
                            RhsPacket, ResPacket, Traits, LinearMapper, DataMapper>
         p;
     p(res, blockA, blockB, alpha, peeled_mc2, peeled_mc1, strideA, strideB, offsetA, offsetB, prefetch_res_offset,
       peeled_kc, pk, cols, depth, packet_cols4);
   }
   //---------- Process LhsProgressHalf rows at once ----------
   if ((LhsProgressHalf < LhsProgress) && mr >= LhsProgressHalf) {
     lhs_process_fraction_of_packet<nr, LhsProgressHalf, RhsProgressHalf, LhsScalar, RhsScalar, ResScalar, AccPacketHalf,
                                    LhsPacketHalf, RhsPacketHalf, ResPacketHalf, HalfTraits, LinearMapper, DataMapper>
         p;
     p(res, blockA, blockB, alpha, peeled_mc1, peeled_mc_half, strideA, strideB, offsetA, offsetB, prefetch_res_offset,
       peeled_kc, pk, cols, depth, packet_cols4);
   }
   //---------- Process LhsProgressQuarter rows at once ----------
   if ((LhsProgressQuarter < LhsProgressHalf) && mr >= LhsProgressQuarter) {
     lhs_process_fraction_of_packet<nr, LhsProgressQuarter, RhsProgressQuarter, LhsScalar, RhsScalar, ResScalar,
                                    AccPacketQuarter, LhsPacketQuarter, RhsPacketQuarter, ResPacketQuarter,
                                    QuarterTraits, LinearMapper, DataMapper>
         p;
     p(res, blockA, blockB, alpha, peeled_mc_half, peeled_mc_quarter, strideA, strideB, offsetA, offsetB,
       prefetch_res_offset, peeled_kc, pk, cols, depth, packet_cols4);
   }
   //---------- Process remaining rows, 1 at once ----------
   if (peeled_mc_quarter < rows) {
 #if EIGEN_ARCH_ARM64 || EIGEN_ARCH_LOONGARCH64
     EIGEN_IF_CONSTEXPR(nr >= 8) {
       // loop on each panel of the rhs
       for (Index j2 = 0; j2 < packet_cols8; j2 += 8) {
         // loop on each row of the lhs (1*LhsProgress x depth)
         for (Index i = peeled_mc_quarter; i < rows; i += 1) {
           const LhsScalar* blA = &blockA[i * strideA + offsetA];
           prefetch(&blA[0]);
           // gets a 1 x 1 res block as registers
           ResScalar C0(0), C1(0), C2(0), C3(0), C4(0), C5(0), C6(0), C7(0);
           const RhsScalar* blB = &blockB[j2 * strideB + offsetB * 8];
           for (Index k = 0; k < depth; k++) {
             LhsScalar A0 = blA[k];
             RhsScalar B_0;
             B_0 = blB[0];
             C0 = cj.pmadd(A0, B_0, C0);
             B_0 = blB[1];
             C1 = cj.pmadd(A0, B_0, C1);
             B_0 = blB[2];
             C2 = cj.pmadd(A0, B_0, C2);
             B_0 = blB[3];
             C3 = cj.pmadd(A0, B_0, C3);
             B_0 = blB[4];
             C4 = cj.pmadd(A0, B_0, C4);
             B_0 = blB[5];
             C5 = cj.pmadd(A0, B_0, C5);
             B_0 = blB[6];
             C6 = cj.pmadd(A0, B_0, C6);
             B_0 = blB[7];
             C7 = cj.pmadd(A0, B_0, C7);
             blB += 8;
           }
           res(i, j2 + 0) += alpha * C0;
           res(i, j2 + 1) += alpha * C1;
           res(i, j2 + 2) += alpha * C2;
           res(i, j2 + 3) += alpha * C3;
           res(i, j2 + 4) += alpha * C4;
           res(i, j2 + 5) += alpha * C5;
           res(i, j2 + 6) += alpha * C6;
           res(i, j2 + 7) += alpha * C7;
         }
       }
     }
 #endif
     for (Index j2 = packet_cols8; j2 < packet_cols4; j2 += 4) {
       // loop on each row of the lhs (1*LhsProgress x depth)
       for (Index i = peeled_mc_quarter; i < rows; i += 1) {
         const LhsScalar* blA = &blockA[i * strideA + offsetA];
         prefetch(&blA[0]);
         const RhsScalar* blB = &blockB[j2 * strideB + offsetB * 4];
         // If LhsProgress is 8 or 16, it assumes that there is a
         // half or quarter packet, respectively, of the same size as
         // nr (which is currently 4) for the return type.
         const int SResPacketHalfSize = unpacket_traits<typename unpacket_traits<SResPacket>::half>::size;
         const int SResPacketQuarterSize =
             unpacket_traits<typename unpacket_traits<typename unpacket_traits<SResPacket>::half>::half>::size;
         // The following code assumes we can load SRhsPacket in such a way that
         // it multiplies blocks of 4 elements in SLhsPacket.  This is not the
         // case for some customized kernels (i.e. NEON fp16).  If the assumption
         // fails, drop down to the scalar path.
         constexpr bool kCanLoadSRhsQuad =
             (unpacket_traits<SLhsPacket>::size < 4) ||
             (unpacket_traits<SRhsPacket>::size % ((std::max<int>)(unpacket_traits<SLhsPacket>::size, 4) / 4)) == 0;
         if (kCanLoadSRhsQuad && (SwappedTraits::LhsProgress % 4) == 0 && (SwappedTraits::LhsProgress <= 16) &&
             (SwappedTraits::LhsProgress != 8 || SResPacketHalfSize == nr) &&
             (SwappedTraits::LhsProgress != 16 || SResPacketQuarterSize == nr)) {
           SAccPacket C0, C1, C2, C3;
           straits.initAcc(C0);
           straits.initAcc(C1);
           straits.initAcc(C2);
           straits.initAcc(C3);
           const Index spk = (std::max)(1, SwappedTraits::LhsProgress / 4);
           const Index endk = (depth / spk) * spk;
           const Index endk4 = (depth / (spk * 4)) * (spk * 4);
           Index k = 0;
           for (; k < endk4; k += 4 * spk) {
             SLhsPacket A0, A1;
             SRhsPacket B_0, B_1;
             straits.loadLhsUnaligned(blB + 0 * SwappedTraits::LhsProgress, A0);
             straits.loadLhsUnaligned(blB + 1 * SwappedTraits::LhsProgress, A1);
             straits.loadRhsQuad(blA + 0 * spk, B_0);
             straits.loadRhsQuad(blA + 1 * spk, B_1);
             straits.madd(A0, B_0, C0, B_0, fix<0>);
             straits.madd(A1, B_1, C1, B_1, fix<0>);
             straits.loadLhsUnaligned(blB + 2 * SwappedTraits::LhsProgress, A0);
             straits.loadLhsUnaligned(blB + 3 * SwappedTraits::LhsProgress, A1);
             straits.loadRhsQuad(blA + 2 * spk, B_0);
             straits.loadRhsQuad(blA + 3 * spk, B_1);
             straits.madd(A0, B_0, C2, B_0, fix<0>);
             straits.madd(A1, B_1, C3, B_1, fix<0>);
             blB += 4 * SwappedTraits::LhsProgress;
             blA += 4 * spk;
           }
           C0 = padd(padd(C0, C1), padd(C2, C3));
           for (; k < endk; k += spk) {
             SLhsPacket A0;
             SRhsPacket B_0;
             straits.loadLhsUnaligned(blB, A0);
             straits.loadRhsQuad(blA, B_0);
             straits.madd(A0, B_0, C0, B_0, fix<0>);
             blB += SwappedTraits::LhsProgress;
             blA += spk;
           }
           if (SwappedTraits::LhsProgress == 8) {
             // Special case where we have to first reduce the accumulation register C0
             typedef std::conditional_t<SwappedTraits::LhsProgress >= 8, typename unpacket_traits<SResPacket>::half,
                                        SResPacket>
                 SResPacketHalf;
             typedef std::conditional_t<SwappedTraits::LhsProgress >= 8, typename unpacket_traits<SLhsPacket>::half,
                                        SLhsPacket>
                 SLhsPacketHalf;
             typedef std::conditional_t<SwappedTraits::LhsProgress >= 8, typename unpacket_traits<SRhsPacket>::half,
                                        SRhsPacket>
                 SRhsPacketHalf;
             typedef std::conditional_t<SwappedTraits::LhsProgress >= 8, typename unpacket_traits<SAccPacket>::half,
                                        SAccPacket>
                 SAccPacketHalf;
             SResPacketHalf R = res.template gatherPacket<SResPacketHalf>(i, j2);
             SResPacketHalf alphav = pset1<SResPacketHalf>(alpha);
             if (depth - endk > 0) {
               // We have to handle the last row of the rhs which corresponds to a half-packet
               SLhsPacketHalf a0;
               SRhsPacketHalf b0;
               straits.loadLhsUnaligned(blB, a0);
               straits.loadRhs(blA, b0);
               SAccPacketHalf c0 = predux_half_dowto4(C0);
               straits.madd(a0, b0, c0, b0, fix<0>);
               straits.acc(c0, alphav, R);
             } else {
               straits.acc(predux_half_dowto4(C0), alphav, R);
             }
             res.scatterPacket(i, j2, R);
           } else if (SwappedTraits::LhsProgress == 16) {
             // Special case where we have to first reduce the
             // accumulation register C0. We specialize the block in
             // template form, so that LhsProgress < 16 paths don't
             // fail to compile
             last_row_process_16_packets<LhsScalar, RhsScalar, Index, DataMapper, mr, nr, ConjugateLhs, ConjugateRhs> p;
             p(res, straits, blA, blB, depth, endk, i, j2, alpha, C0);
           } else {
             SResPacket R = res.template gatherPacket<SResPacket>(i, j2);
             SResPacket alphav = pset1<SResPacket>(alpha);
             straits.acc(C0, alphav, R);
             res.scatterPacket(i, j2, R);
           }
         } else  // scalar path
         {
           // get a 1 x 4 res block as registers
           ResScalar C0(0), C1(0), C2(0), C3(0);
           for (Index k = 0; k < depth; k++) {
             LhsScalar A0;
             RhsScalar B_0, B_1;
             A0 = blA[k];
             B_0 = blB[0];
             B_1 = blB[1];
             C0 = cj.pmadd(A0, B_0, C0);
             C1 = cj.pmadd(A0, B_1, C1);
             B_0 = blB[2];
             B_1 = blB[3];
             C2 = cj.pmadd(A0, B_0, C2);
             C3 = cj.pmadd(A0, B_1, C3);
             blB += 4;
           }
           res(i, j2 + 0) += alpha * C0;
           res(i, j2 + 1) += alpha * C1;
           res(i, j2 + 2) += alpha * C2;
           res(i, j2 + 3) += alpha * C3;
         }
       }
     }
     // remaining columns
     for (Index j2 = packet_cols4; j2 < cols; j2++) {
       // loop on each row of the lhs (1*LhsProgress x depth)
       for (Index i = peeled_mc_quarter; i < rows; i += 1) {
         const LhsScalar* blA = &blockA[i * strideA + offsetA];
         prefetch(&blA[0]);
         // gets a 1 x 1 res block as registers
         ResScalar C0(0);
         const RhsScalar* blB = &blockB[j2 * strideB + offsetB];
         for (Index k = 0; k < depth; k++) {
           LhsScalar A0 = blA[k];
           RhsScalar B_0 = blB[k];
           C0 = cj.pmadd(A0, B_0, C0);
         }
         res(i, j2) += alpha * C0;
       }
     }
   }
 }
References Eigen::internal::gebp_traits< LhsScalar_, RhsScalar_, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::acc(), alpha, Global_Physical_Variables::C1, Global_Physical_Variables::C2, cols, Eigen::internal::defaultL1CacheSize, EIGEN_ASM_COMMENT, EIGEN_GEBGP_ONESTEP, EIGEN_GEBP_ONESTEP, EIGEN_IF_CONSTEXPR, i, Eigen::internal::gebp_traits< LhsScalar_, RhsScalar_, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::initAcc(), int(), k, Eigen::internal::gebp_traits< LhsScalar_, RhsScalar_, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::loadLhsUnaligned(), Eigen::internal::gebp_traits< LhsScalar_, RhsScalar_, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::loadRhs(), Eigen::internal::gebp_traits< LhsScalar_, RhsScalar_, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::loadRhsQuad(), Eigen::internal::gebp_traits< LhsScalar_, RhsScalar_, ConjLhs_, ConjRhs_, Arch, PacketSize_ >::madd(), max, min, p, Eigen::internal::padd(), Eigen::internal::conj_helper< LhsType, RhsType, ConjLhs, ConjRhs >::pmadd(), Eigen::internal::predux_half_dowto4(), Eigen::internal::prefetch(), R, res, rows, and size.
The documentation for this struct was generated from the following file:
products/GeneralBlockPanelKernel.h