MercuryDPM: Eigen::internal::unary_evaluator< CwiseUnaryOp< UnaryOp, ArgType >, IndexBased > Struct Template Reference
Eigen::internal::unary_evaluator< CwiseUnaryOp< UnaryOp, ArgType >, IndexBased > Struct Template Reference
#include <CoreEvaluators.h>
Classes
struct Data
Public Types
enum { CoeffReadCost = int(evaluator<ArgType>::CoeffReadCost) + int(functor_traits<UnaryOp>::Cost) , Flags , Alignment = evaluator<ArgType>::Alignment }
typedef CwiseUnaryOp< UnaryOp, ArgType > XprType
typedef XprType::CoeffReturnType CoeffReturnType
Public Types inherited from Eigen::internal::evaluator_base< CwiseUnaryOp< UnaryOp, ArgType > >
enum
typedef traits< CwiseUnaryOp< UnaryOp, ArgType > > ExpressionTraits
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE unary_evaluator (const XprType &op)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
template<int LoadMode, typename PacketType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType packet (Index row, Index col) const
template<int LoadMode, typename PacketType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType packet (Index index) const
Public Member Functions inherited from Eigen::internal::evaluator_base< CwiseUnaryOp< UnaryOp, ArgType > >
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE evaluator_base ()=default
Protected Attributes
Data m_d
Member Typedef Documentation
CoeffReturnType
template<typename UnaryOp , typename ArgType > typedef XprType::CoeffReturnType Eigen::internal::unary_evaluator< CwiseUnaryOp< UnaryOp, ArgType >, IndexBased >::CoeffReturnType
XprType
template<typename UnaryOp , typename ArgType > typedef CwiseUnaryOp<UnaryOp, ArgType> Eigen::internal::unary_evaluator< CwiseUnaryOp< UnaryOp, ArgType >, IndexBased >::XprType
Member Enumeration Documentation
anonymous enum
template<typename UnaryOp , typename ArgType > anonymous enum
Enumerator
CoeffReadCost
Flags
Alignment
        {
     CoeffReadCost = int(evaluator<ArgType>::CoeffReadCost) + int(functor_traits<UnaryOp>::Cost),
     Flags = evaluator<ArgType>::Flags &
             (HereditaryBits | LinearAccessBit | (functor_traits<UnaryOp>::PacketAccess ? PacketAccessBit : 0)),
     Alignment = evaluator<ArgType>::Alignment
   };
Constructor & Destructor Documentation
unary_evaluator()
template<typename UnaryOp , typename ArgType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::internal::unary_evaluator< CwiseUnaryOp< UnaryOp, ArgType >, IndexBased >::unary_evaluator (const XprType & op) inline explicit
                                                                                     : m_d(op) {
     EIGEN_INTERNAL_CHECK_COST_VALUE(functor_traits<UnaryOp>::Cost);
     EIGEN_INTERNAL_CHECK_COST_VALUE(CoeffReadCost);
   }
References EIGEN_INTERNAL_CHECK_COST_VALUE.
Member Function Documentation
coeff() [1/2]
template<typename UnaryOp , typename ArgType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::unary_evaluator< CwiseUnaryOp< UnaryOp, ArgType >, IndexBased >::coeff (Index index) const inline
{
     return m_d.func()(m_d.argImpl.coeff(index));
   }
coeff() [2/2]
template<typename UnaryOp , typename ArgType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::unary_evaluator< CwiseUnaryOp< UnaryOp, ArgType >, IndexBased >::coeff (Index row, Index col) const inline
{
     return m_d.func()(m_d.argImpl.coeff(row, col));
   }
References col(), and row().
packet() [1/2]
template<typename UnaryOp , typename ArgType > template<int LoadMode, typename PacketType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType Eigen::internal::unary_evaluator< CwiseUnaryOp< UnaryOp, ArgType >, IndexBased >::packet (Index index) const inline
{
     return m_d.func().packetOp(m_d.argImpl.template packet<LoadMode, PacketType>(index));
   }
packet() [2/2]
template<typename UnaryOp , typename ArgType > template<int LoadMode, typename PacketType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType Eigen::internal::unary_evaluator< CwiseUnaryOp< UnaryOp, ArgType >, IndexBased >::packet (Index row, Index col) const inline
{
     return m_d.func().packetOp(m_d.argImpl.template packet<LoadMode, PacketType>(row, col));
   }
References col(), and row().
Member Data Documentation
m_d
template<typename UnaryOp , typename ArgType > Data Eigen::internal::unary_evaluator< CwiseUnaryOp< UnaryOp, ArgType >, IndexBased >::m_d protected
The documentation for this struct was generated from the following file:
CoreEvaluators.h