MercuryDPM: Eigen::internal::compute_inverse< MatrixType, ResultType, Size > Struct Template Reference
Eigen::internal::compute_inverse< MatrixType, ResultType, Size > Struct Template Reference
#include <InverseImpl.h>
Static Public Member Functions
static EIGEN_DEVICE_FUNC void run (const MatrixType &matrix, ResultType &result)
Member Function Documentation
run()
template<typename MatrixType , typename ResultType , int Size = MatrixType::RowsAtCompileTime> static EIGEN_DEVICE_FUNC void Eigen::internal::compute_inverse< MatrixType, ResultType, Size >::run (const MatrixType & matrix, ResultType & result) inline static
{
     result = matrix.partialPivLu().inverse();
   }
References matrix().
Referenced by Eigen::internal::compute_inverse_and_det_with_check< MatrixType, ResultType, 4 >::run(), and Eigen::internal::Assignment< DstXprType, Inverse< XprType >, internal::assign_op< typename DstXprType::Scalar, typename XprType::Scalar >, Dense2Dense >::run().
The documentation for this struct was generated from the following file:
InverseImpl.h