MercuryDPM: Eigen::TensorEvaluator< const TensorPairReducerOp< ReduceOp, Dims, ArgType >, Device > Struct Template Reference
Eigen::TensorEvaluator< const TensorPairReducerOp< ReduceOp, Dims, ArgType >, Device > Struct Template Reference
#include <TensorArgMax.h>
Public Types
enum {
IsAligned = false , PacketAccess = false , BlockAccess = false , PreferBlockAccess = TensorEvaluator<ArgType, Device>::PreferBlockAccess ,
CoordAccess = false , RawAccess = false
}
typedef TensorPairReducerOp< ReduceOp, Dims, ArgType > XprType
typedef XprType::Index Index
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
typedef TensorIndexPairOp< ArgType >::CoeffReturnType PairType
typedef TensorEvaluator< const TensorReductionOp< ReduceOp, Dims, const TensorIndexPairOp< ArgType > >, Device >::Dimensions Dimensions
typedef TensorEvaluator< const TensorIndexPairOp< ArgType >, Device >::Dimensions InputDimensions
typedef array< Index, NumDims > StrideDims
typedef StorageMemory< CoeffReturnType, Device > Storage
typedef Storage::Type EvaluatorPointerType
typedef StorageMemory< PairType, Device > PairStorageMem
typedef internal::TensorBlockNotImplemented TensorBlock
Public Member Functions
EIGEN_STRONG_INLINE TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions & dimensions () const
EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (EvaluatorPointerType)
EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
EIGEN_DEVICE_FUNC EvaluatorPointerType data () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
Static Public Attributes
static constexpr int NumDims = internal::array_size<InputDimensions>::value
static constexpr int Layout
Protected Attributes
TensorEvaluator< const TensorIndexPairOp< ArgType >, Device > m_orig_impl
TensorEvaluator< const TensorReductionOp< ReduceOp, Dims, const TensorIndexPairOp< ArgType > >, Device > m_impl
const Index m_return_dim
StrideDims m_strides
Index m_stride_mod
Index m_stride_div
Private Member Functions
EIGEN_DEVICE_FUNC void gen_strides (const InputDimensions &dims, StrideDims &strides)
Member Typedef Documentation
CoeffReturnType
template<typename ReduceOp , typename Dims , typename ArgType , typename Device > typedef XprType::CoeffReturnType Eigen::TensorEvaluator< const TensorPairReducerOp< ReduceOp, Dims, ArgType >, Device >::CoeffReturnType
Dimensions
template<typename ReduceOp , typename Dims , typename ArgType , typename Device > typedef TensorEvaluator<const TensorReductionOp<ReduceOp, Dims, const TensorIndexPairOp<ArgType> >, Device>::Dimensions Eigen::TensorEvaluator< const TensorPairReducerOp< ReduceOp, Dims, ArgType >, Device >::Dimensions
EvaluatorPointerType
template<typename ReduceOp , typename Dims , typename ArgType , typename Device > typedef Storage::Type Eigen::TensorEvaluator< const TensorPairReducerOp< ReduceOp, Dims, ArgType >, Device >::EvaluatorPointerType
Index
template<typename ReduceOp , typename Dims , typename ArgType , typename Device > typedef XprType::Index Eigen::TensorEvaluator< const TensorPairReducerOp< ReduceOp, Dims, ArgType >, Device >::Index
InputDimensions
template<typename ReduceOp , typename Dims , typename ArgType , typename Device > typedef TensorEvaluator<const TensorIndexPairOp<ArgType>, Device>::Dimensions Eigen::TensorEvaluator< const TensorPairReducerOp< ReduceOp, Dims, ArgType >, Device >::InputDimensions
PairStorageMem
template<typename ReduceOp , typename Dims , typename ArgType , typename Device > typedef StorageMemory<PairType, Device> Eigen::TensorEvaluator< const TensorPairReducerOp< ReduceOp, Dims, ArgType >, Device >::PairStorageMem
PairType
template<typename ReduceOp , typename Dims , typename ArgType , typename Device > typedef TensorIndexPairOp<ArgType>::CoeffReturnType Eigen::TensorEvaluator< const TensorPairReducerOp< ReduceOp, Dims, ArgType >, Device >::PairType
Scalar
template<typename ReduceOp , typename Dims , typename ArgType , typename Device > typedef XprType::Scalar Eigen::TensorEvaluator< const TensorPairReducerOp< ReduceOp, Dims, ArgType >, Device >::Scalar
Storage
template<typename ReduceOp , typename Dims , typename ArgType , typename Device > typedef StorageMemory<CoeffReturnType, Device> Eigen::TensorEvaluator< const TensorPairReducerOp< ReduceOp, Dims, ArgType >, Device >::Storage
StrideDims
template<typename ReduceOp , typename Dims , typename ArgType , typename Device > typedef array<Index, NumDims> Eigen::TensorEvaluator< const TensorPairReducerOp< ReduceOp, Dims, ArgType >, Device >::StrideDims
TensorBlock
template<typename ReduceOp , typename Dims , typename ArgType , typename Device > typedef internal::TensorBlockNotImplemented Eigen::TensorEvaluator< const TensorPairReducerOp< ReduceOp, Dims, ArgType >, Device >::TensorBlock
XprType
template<typename ReduceOp , typename Dims , typename ArgType , typename Device > typedef TensorPairReducerOp<ReduceOp, Dims, ArgType> Eigen::TensorEvaluator< const TensorPairReducerOp< ReduceOp, Dims, ArgType >, Device >::XprType
Member Enumeration Documentation
anonymous enum
template<typename ReduceOp , typename Dims , typename ArgType , typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
BlockAccess
PreferBlockAccess
CoordAccess
RawAccess
        {
     IsAligned = /*TensorEvaluator<ArgType, Device>::IsAligned*/ false,
     PacketAccess = /*TensorEvaluator<ArgType, Device>::PacketAccess*/ false,
     BlockAccess = false,
     PreferBlockAccess = TensorEvaluator<ArgType, Device>::PreferBlockAccess,
     CoordAccess = false,  // to be implemented
     RawAccess = false
   };
Constructor & Destructor Documentation
TensorEvaluator()
template<typename ReduceOp , typename Dims , typename ArgType , typename Device > EIGEN_STRONG_INLINE Eigen::TensorEvaluator< const TensorPairReducerOp< ReduceOp, Dims, ArgType >, Device >::TensorEvaluator (const XprType & op, const Device & device) inline
       : m_orig_impl(op.expression(), device),
         m_impl(op.expression().index_pairs().reduce(op.reduce_dims(), op.reduce_op()), device),
         m_return_dim(op.return_dim()) {
     gen_strides(m_orig_impl.dimensions(), m_strides);
     if (Layout == static_cast<int>(ColMajor)) {
       const Index total_size = internal::array_prod(m_orig_impl.dimensions());
       m_stride_mod = (m_return_dim < NumDims - 1) ? m_strides[m_return_dim + 1] : total_size;
     } else {
       const Index total_size = internal::array_prod(m_orig_impl.dimensions());
       m_stride_mod = (m_return_dim > 0) ? m_strides[m_return_dim - 1] : total_size;
     }
     // If m_return_dim is not a valid index, returns 1 or this can crash on Windows.
     m_stride_div =
         ((m_return_dim >= 0) && (m_return_dim < static_cast<Index>(m_strides.size()))) ? m_strides[m_return_dim] : 1;
   }
References Eigen::internal::array_prod(), Eigen::ColMajor, and Eigen::TensorEvaluator< Derived, Device >::Layout.
Member Function Documentation
cleanup()
template<typename ReduceOp , typename Dims , typename ArgType , typename Device > EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorPairReducerOp< ReduceOp, Dims, ArgType >, Device >::cleanup () inline
 { m_impl.cleanup(); }
Referenced by framework.Frame::__init__().
coeff()
template<typename ReduceOp , typename Dims , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::TensorEvaluator< const TensorPairReducerOp< ReduceOp, Dims, ArgType >, Device >::coeff (Index index) const inline
{
     const PairType v = m_impl.coeff(index);
     return (m_return_dim < 0) ? v.first : (v.first % m_stride_mod) / m_stride_div;
   }
References v.
costPerCoeff()
template<typename ReduceOp , typename Dims , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorEvaluator< const TensorPairReducerOp< ReduceOp, Dims, ArgType >, Device >::costPerCoeff (bool vectorized) const inline
{
     const double compute_cost =
         1.0 + (m_return_dim < 0 ? 0.0 : (TensorOpCost::ModCost<Index>() + TensorOpCost::DivCost<Index>()));
     return m_orig_impl.costPerCoeff(vectorized) + m_impl.costPerCoeff(vectorized) + TensorOpCost(0, 0, compute_cost);
   }
data()
template<typename ReduceOp , typename Dims , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EvaluatorPointerType Eigen::TensorEvaluator< const TensorPairReducerOp< ReduceOp, Dims, ArgType >, Device >::data () const inline
 { return NULL; }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
dimensions()
template<typename ReduceOp , typename Dims , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions& Eigen::TensorEvaluator< const TensorPairReducerOp< ReduceOp, Dims, ArgType >, Device >::dimensions () const inline
 { return m_impl.dimensions(); }
evalSubExprsIfNeeded()
template<typename ReduceOp , typename Dims , typename ArgType , typename Device > EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorPairReducerOp< ReduceOp, Dims, ArgType >, Device >::evalSubExprsIfNeeded (EvaluatorPointerType) inline
{
     m_impl.evalSubExprsIfNeeded(NULL);
     return true;
   }
gen_strides()
template<typename ReduceOp , typename Dims , typename ArgType , typename Device > EIGEN_DEVICE_FUNC void Eigen::TensorEvaluator< const TensorPairReducerOp< ReduceOp, Dims, ArgType >, Device >::gen_strides (const InputDimensions & dims, StrideDims & strides) inline private
{
     if (m_return_dim < 0) {
       return;  // Won't be using the strides.
     }
     eigen_assert(m_return_dim < NumDims && "Asking to convert index to a dimension outside of the rank");
     // Calculate m_stride_div and m_stride_mod, which are used to
     // calculate the value of an index w.r.t. the m_return_dim.
     if (Layout == static_cast<int>(ColMajor)) {
       strides[0] = 1;
       for (int i = 1; i < NumDims; ++i) {
         strides[i] = strides[i - 1] * dims[i - 1];
       }
     } else {
       strides[NumDims - 1] = 1;
       for (int i = NumDims - 2; i >= 0; --i) {
         strides[i] = strides[i + 1] * dims[i + 1];
       }
     }
   }
References Eigen::ColMajor, eigen_assert, i, Eigen::TensorEvaluator< Derived, Device >::Layout, and Eigen::internal::strides().
Member Data Documentation
Layout
template<typename ReduceOp , typename Dims , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorPairReducerOp< ReduceOp, Dims, ArgType >, Device >::Layout static constexpr
Initial value:
=
      TensorEvaluator<const TensorReductionOp<ReduceOp, Dims, const TensorIndexPairOp<ArgType>>, Device>::Layout
m_impl
template<typename ReduceOp , typename Dims , typename ArgType , typename Device > TensorEvaluator<const TensorReductionOp<ReduceOp, Dims, const TensorIndexPairOp<ArgType> >, Device> Eigen::TensorEvaluator< const TensorPairReducerOp< ReduceOp, Dims, ArgType >, Device >::m_impl protected
m_orig_impl
template<typename ReduceOp , typename Dims , typename ArgType , typename Device > TensorEvaluator<const TensorIndexPairOp<ArgType>, Device> Eigen::TensorEvaluator< const TensorPairReducerOp< ReduceOp, Dims, ArgType >, Device >::m_orig_impl protected
m_return_dim
template<typename ReduceOp , typename Dims , typename ArgType , typename Device > const Index Eigen::TensorEvaluator< const TensorPairReducerOp< ReduceOp, Dims, ArgType >, Device >::m_return_dim protected
m_stride_div
template<typename ReduceOp , typename Dims , typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorPairReducerOp< ReduceOp, Dims, ArgType >, Device >::m_stride_div protected
m_stride_mod
template<typename ReduceOp , typename Dims , typename ArgType , typename Device > Index Eigen::TensorEvaluator< const TensorPairReducerOp< ReduceOp, Dims, ArgType >, Device >::m_stride_mod protected
m_strides
template<typename ReduceOp , typename Dims , typename ArgType , typename Device > StrideDims Eigen::TensorEvaluator< const TensorPairReducerOp< ReduceOp, Dims, ArgType >, Device >::m_strides protected
NumDims
template<typename ReduceOp , typename Dims , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorPairReducerOp< ReduceOp, Dims, ArgType >, Device >::NumDims = internal::array_size<InputDimensions>::value static constexpr
The documentation for this struct was generated from the following file:
TensorArgMax.h