MercuryDPM: Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ > Class Template Reference
Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ > Class Template Reference
Dense linear problems and decompositions » Reference » QR_Module
Householder rank-revealing QR decomposition of a matrix with full pivoting.
#include <FullPivHouseholderQR.h>
Public Types
enum { MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime , MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime }
typedef MatrixType_ MatrixType
typedef SolverBase< FullPivHouseholderQR > Base
typedef PermutationIndex_ PermutationIndex
typedef internal::FullPivHouseholderQRMatrixQReturnType< MatrixType, PermutationIndex > MatrixQReturnType
typedef internal::plain_diag_type< MatrixType >::type HCoeffsType
typedef Matrix< PermutationIndex, 1, internal::min_size_prefer_dynamic(ColsAtCompileTime, RowsAtCompileTime), RowMajor, 1, internal::min_size_prefer_fixed(MaxColsAtCompileTime, MaxRowsAtCompileTime)> IntDiagSizeVectorType
typedef PermutationMatrix< ColsAtCompileTime, MaxColsAtCompileTime, PermutationIndex > PermutationType
typedef internal::plain_row_type< MatrixType >::type RowVectorType
typedef internal::plain_col_type< MatrixType >::type ColVectorType
typedef MatrixType::PlainObject PlainObject
Public Types inherited from Eigen::SolverBase< FullPivHouseholderQR< MatrixType_, PermutationIndex_ > >
enum
typedef EigenBase< FullPivHouseholderQR< MatrixType_, PermutationIndex_ > > Base
typedef internal::traits< FullPivHouseholderQR< MatrixType_, PermutationIndex_ > >::Scalar Scalar
typedef Scalar CoeffReturnType
typedef Transpose< const FullPivHouseholderQR< MatrixType_, PermutationIndex_ > > ConstTransposeReturnType
typedef std::conditional_t< NumTraits< Scalar >::IsComplex, CwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, const ConstTransposeReturnType >, const ConstTransposeReturnType > AdjointReturnType
Public Types inherited from Eigen::EigenBase< Derived >
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< Derived >::StorageKind StorageKind
Public Member Functions
FullPivHouseholderQR ()
Default Constructor.
FullPivHouseholderQR (Index rows, Index cols)
Default Constructor with memory preallocation.
template<typename InputType >
FullPivHouseholderQR (const EigenBase< InputType > &matrix)
Constructs a QR factorization from a given matrix.
template<typename InputType >
FullPivHouseholderQR (EigenBase< InputType > &matrix)
Constructs a QR factorization from a given matrix.
MatrixQReturnType matrixQ (void) const
const MatrixType & matrixQR () const
template<typename InputType >
FullPivHouseholderQR & compute (const EigenBase< InputType > &matrix)
const PermutationType & colsPermutation () const
const IntDiagSizeVectorType & rowsTranspositions () const
MatrixType::Scalar determinant () const
MatrixType::RealScalar absDeterminant () const
MatrixType::RealScalar logAbsDeterminant () const
MatrixType::Scalar signDeterminant () const
Index rank () const
Index dimensionOfKernel () const
bool isInjective () const
bool isSurjective () const
bool isInvertible () const
const Inverse< FullPivHouseholderQR > inverse () const
Index rows () const
Index cols () const
const HCoeffsType & hCoeffs () const
FullPivHouseholderQR & setThreshold (const RealScalar &threshold)
FullPivHouseholderQR & setThreshold (Default_t)
RealScalar threshold () const
Index nonzeroPivots () const
RealScalar maxPivot () const
template<typename RhsType , typename DstType >
void _solve_impl (const RhsType &rhs, DstType &dst) const
template<bool Conjugate, typename RhsType , typename DstType >
void _solve_impl_transposed (const RhsType &rhs, DstType &dst) const
template<typename InputType >
FullPivHouseholderQR< MatrixType, PermutationIndex > & compute (const EigenBase< InputType > &matrix)
Public Member Functions inherited from Eigen::SolverBase< FullPivHouseholderQR< MatrixType_, PermutationIndex_ > >
SolverBase ()
~SolverBase ()
const Solve< FullPivHouseholderQR< MatrixType_, PermutationIndex_ >, Rhs > solve (const MatrixBase< Rhs > &b) const
const ConstTransposeReturnType transpose () const
const AdjointReturnType adjoint () const
constexpr EIGEN_DEVICE_FUNC FullPivHouseholderQR< MatrixType_, PermutationIndex_ > & derived ()
constexpr EIGEN_DEVICE_FUNC const FullPivHouseholderQR< MatrixType_, PermutationIndex_ > & derived () const
Public Member Functions inherited from Eigen::EigenBase< Derived >
constexpr EIGEN_DEVICE_FUNC Derived & derived ()
constexpr EIGEN_DEVICE_FUNC const Derived & derived () const
EIGEN_DEVICE_FUNC Derived & const_cast_derived () const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index size () const EIGEN_NOEXCEPT
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
template<typename Device >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< Derived, Device > device (Device &device)
template<typename Device >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< const Derived, Device > device (Device &device) const
Protected Member Functions
void computeInPlace ()
Protected Member Functions inherited from Eigen::SolverBase< FullPivHouseholderQR< MatrixType_, PermutationIndex_ > >
void _check_solve_assertion (const Rhs &b) const
Protected Attributes
MatrixType m_qr
HCoeffsType m_hCoeffs
IntDiagSizeVectorType m_rows_transpositions
IntDiagSizeVectorType m_cols_transpositions
PermutationType m_cols_permutation
RowVectorType m_temp
bool m_isInitialized
bool m_usePrescribedThreshold
RealScalar m_prescribedThreshold
RealScalar m_maxpivot
Index m_nonzero_pivots
RealScalar m_precision
Index m_det_p
Friends
class SolverBase< FullPivHouseholderQR >
Detailed Description
template<typename MatrixType_, typename PermutationIndex_>
class Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >
Householder rank-revealing QR decomposition of a matrix with full pivoting.
Template Parameters
MatrixType_ the type of the matrix of which we are computing the QR decomposition
This class performs a rank-revealing QR decomposition of a matrix A into matrices P, P', Q and R such that
\[ \mathbf{P} \, \mathbf{A} \, \mathbf{P}' = \mathbf{Q} \, \mathbf{R} \]
by using Householder transformations. Here, P and P' are permutation matrices, Q a unitary matrix and R an upper triangular matrix.
This decomposition performs a very prudent full pivoting in order to be rank-revealing and achieve optimal numerical stability. The trade-off is that it is slower than HouseholderQR and ColPivHouseholderQR.
This class supports the inplace decomposition mechanism.
See also
MatrixBase::fullPivHouseholderQr()
Member Typedef Documentation
Base
template<typename MatrixType_ , typename PermutationIndex_ > typedef SolverBase<FullPivHouseholderQR> Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::Base
ColVectorType
template<typename MatrixType_ , typename PermutationIndex_ > typedef internal::plain_col_type<MatrixType>::type Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::ColVectorType
HCoeffsType
template<typename MatrixType_ , typename PermutationIndex_ > typedef internal::plain_diag_type<MatrixType>::type Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::HCoeffsType
IntDiagSizeVectorType
template<typename MatrixType_ , typename PermutationIndex_ > typedef Matrix<PermutationIndex, 1, internal::min_size_prefer_dynamic(ColsAtCompileTime, RowsAtCompileTime), RowMajor, 1, internal::min_size_prefer_fixed(MaxColsAtCompileTime, MaxRowsAtCompileTime)> Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::IntDiagSizeVectorType
MatrixQReturnType
template<typename MatrixType_ , typename PermutationIndex_ > typedef internal::FullPivHouseholderQRMatrixQReturnType<MatrixType, PermutationIndex> Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::MatrixQReturnType
MatrixType
template<typename MatrixType_ , typename PermutationIndex_ > typedef MatrixType_ Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::MatrixType
PermutationIndex
template<typename MatrixType_ , typename PermutationIndex_ > typedef PermutationIndex_ Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::PermutationIndex
PermutationType
template<typename MatrixType_ , typename PermutationIndex_ > typedef PermutationMatrix<ColsAtCompileTime, MaxColsAtCompileTime, PermutationIndex> Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::PermutationType
PlainObject
template<typename MatrixType_ , typename PermutationIndex_ > typedef MatrixType::PlainObject Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::PlainObject
RowVectorType
template<typename MatrixType_ , typename PermutationIndex_ > typedef internal::plain_row_type<MatrixType>::type Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::RowVectorType
Member Enumeration Documentation
anonymous enum
template<typename MatrixType_ , typename PermutationIndex_ > anonymous enum
Enumerator
MaxRowsAtCompileTime
MaxColsAtCompileTime
        {
     MaxRowsAtCompileTime = MatrixType::MaxRowsAtCompileTime,
     MaxColsAtCompileTime = MatrixType::MaxColsAtCompileTime
   };
Constructor & Destructor Documentation
FullPivHouseholderQR() [1/4]
template<typename MatrixType_ , typename PermutationIndex_ > Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::FullPivHouseholderQR () inline
Default Constructor.
The default constructor is useful in cases in which the user intends to perform decompositions via FullPivHouseholderQR::compute(const MatrixType&).
       : m_qr(),
         m_hCoeffs(),
         m_rows_transpositions(),
         m_cols_transpositions(),
         m_cols_permutation(),
         m_temp(),
         m_isInitialized(false),
         m_usePrescribedThreshold(false) {}
FullPivHouseholderQR() [2/4]
template<typename MatrixType_ , typename PermutationIndex_ > Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::FullPivHouseholderQR (Index rows, Index cols) inline
Default Constructor with memory preallocation.
Like the default constructor but with preallocation of the internal data according to the specified problem size.
See also
FullPivHouseholderQR()
       : m_qr(rows, cols),
         m_hCoeffs((std::min)(rows, cols)),
         m_rows_transpositions((std::min)(rows, cols)),
         m_cols_transpositions((std::min)(rows, cols)),
         m_cols_permutation(cols),
         m_temp(cols),
         m_isInitialized(false),
         m_usePrescribedThreshold(false) {}
FullPivHouseholderQR() [3/4]
template<typename MatrixType_ , typename PermutationIndex_ > template<typename InputType > Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::FullPivHouseholderQR (const EigenBase< InputType > & matrix) inline explicit
Constructs a QR factorization from a given matrix.
This constructor computes the QR factorization of the matrix matrix by calling the method compute(). It is a short cut for:
FullPivHouseholderQR<MatrixType> qr(matrix.rows(), matrix.cols());
qr.compute(matrix);
See also
compute()
       : m_qr(matrix.rows(), matrix.cols()),
         m_hCoeffs((std::min)(matrix.rows(), matrix.cols())),
         m_rows_transpositions((std::min)(matrix.rows(), matrix.cols())),
         m_cols_transpositions((std::min)(matrix.rows(), matrix.cols())),
         m_cols_permutation(matrix.cols()),
         m_temp(matrix.cols()),
         m_isInitialized(false),
         m_usePrescribedThreshold(false) {
     compute(matrix.derived());
   }
References Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::compute(), and matrix().
FullPivHouseholderQR() [4/4]
template<typename MatrixType_ , typename PermutationIndex_ > template<typename InputType > Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::FullPivHouseholderQR (EigenBase< InputType > & matrix) inline explicit
Constructs a QR factorization from a given matrix.
This overloaded constructor is provided for inplace decomposition when MatrixType is a Eigen::Ref.
See also
FullPivHouseholderQR(const EigenBase&)
       : m_qr(matrix.derived()),
         m_hCoeffs((std::min)(matrix.rows(), matrix.cols())),
         m_rows_transpositions((std::min)(matrix.rows(), matrix.cols())),
         m_cols_transpositions((std::min)(matrix.rows(), matrix.cols())),
         m_cols_permutation(matrix.cols()),
         m_temp(matrix.cols()),
         m_isInitialized(false),
         m_usePrescribedThreshold(false) {
     computeInPlace();
   }
References Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::computeInPlace().
Member Function Documentation
_solve_impl()
template<typename MatrixType_ , typename PermutationIndex_ > template<typename RhsType , typename DstType > void Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::_solve_impl (const RhsType & rhs, DstType & dst) const
{
   const Index l_rank = rank();
   // FIXME introduce nonzeroPivots() and use it here. and more generally,
   // make the same improvements in this dec as in FullPivLU.
   if (l_rank == 0) {
     dst.setZero();
     return;
   }
   typename RhsType::PlainObject c(rhs);
   Matrix<typename RhsType::Scalar, 1, RhsType::ColsAtCompileTime> temp(rhs.cols());
   for (Index k = 0; k < l_rank; ++k) {
     Index remainingSize = rows() - k;
     c.row(k).swap(c.row(m_rows_transpositions.coeff(k)));
     c.bottomRightCorner(remainingSize, rhs.cols())
         .applyHouseholderOnTheLeft(m_qr.col(k).tail(remainingSize - 1), m_hCoeffs.coeff(k), &temp.coeffRef(0));
   }
   m_qr.topLeftCorner(l_rank, l_rank).template triangularView<Upper>().solveInPlace(c.topRows(l_rank));
   for (Index i = 0; i < l_rank; ++i) dst.row(m_cols_permutation.indices().coeff(i)) = c.row(i);
   for (Index i = l_rank; i < cols(); ++i) dst.row(m_cols_permutation.indices().coeff(i)).setZero();
 }
References calibrate::c, Eigen::PlainObjectBase< Derived >::coeff(), Eigen::Matrix< Scalar_, Rows_, Cols_, Options_, MaxRows_, MaxCols_ >::coeffRef(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::cols(), i, Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, StorageIndex_ >::indices(), k, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_cols_permutation, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_hCoeffs, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_qr, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_rows_transpositions, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::rank(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::rows(), and setZero().
_solve_impl_transposed()
template<typename MatrixType_ , typename PermutationIndex_ > template<bool Conjugate, typename RhsType , typename DstType > void Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::_solve_impl_transposed (const RhsType & rhs, DstType & dst) const
{
   const Index l_rank = rank();
   if (l_rank == 0) {
     dst.setZero();
     return;
   }
   typename RhsType::PlainObject c(m_cols_permutation.transpose() * rhs);
   m_qr.topLeftCorner(l_rank, l_rank)
       .template triangularView<Upper>()
       .transpose()
       .template conjugateIf<Conjugate>()
       .solveInPlace(c.topRows(l_rank));
   dst.topRows(l_rank) = c.topRows(l_rank);
   dst.bottomRows(rows() - l_rank).setZero();
   Matrix<Scalar, 1, DstType::ColsAtCompileTime> temp(dst.cols());
   const Index size = (std::min)(rows(), cols());
   for (Index k = size - 1; k >= 0; --k) {
     Index remainingSize = rows() - k;
     dst.bottomRightCorner(remainingSize, dst.cols())
         .applyHouseholderOnTheLeft(m_qr.col(k).tail(remainingSize - 1).template conjugateIf<!Conjugate>(),
                                    m_hCoeffs.template conjugateIf<Conjugate>().coeff(k), &temp.coeffRef(0));
     dst.row(k).swap(dst.row(m_rows_transpositions.coeff(k)));
   }
 }
References calibrate::c, Eigen::PlainObjectBase< Derived >::coeff(), Eigen::Matrix< Scalar_, Rows_, Cols_, Options_, MaxRows_, MaxCols_ >::coeffRef(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::cols(), k, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_cols_permutation, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_hCoeffs, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_qr, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_rows_transpositions, min, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::rank(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::rows(), Eigen::EigenBase< Derived >::size(), and Eigen::PermutationBase< Derived >::transpose().
absDeterminant()
template<typename MatrixType , typename PermutationIndex > MatrixType::RealScalar Eigen::FullPivHouseholderQR< MatrixType, PermutationIndex >::absDeterminant
Returns
the absolute value of the determinant of the matrix of which *this is the QR decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the QR decomposition has already been computed.
Note
This is only for square matrices.
Warning
a determinant can be very big or small, so for matrices of large enough dimension, there is a risk of overflow/underflow. One way to work around that is to use logAbsDeterminant() instead.
See also
determinant(), logAbsDeterminant(), MatrixBase::determinant()
{
   using std::abs;
   eigen_assert(m_isInitialized && "FullPivHouseholderQR is not initialized.");
   eigen_assert(m_qr.rows() == m_qr.cols() && "You can't take the determinant of a non-square matrix!");
   return isInjective() ? abs(m_qr.diagonal().prod()) : RealScalar(0);
 }
References abs(), eigen_assert, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::isInjective(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_isInitialized, and Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_qr.
cols()
template<typename MatrixType_ , typename PermutationIndex_ > Index Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::cols () const inline
 { return m_qr.cols(); }
References Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_qr.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::_solve_impl(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::_solve_impl_transposed(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::computeInPlace(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::dimensionOfKernel(), Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType, PermutationIndex >::evalTo(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::isInjective(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
colsPermutation()
template<typename MatrixType_ , typename PermutationIndex_ > const PermutationType& Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::colsPermutation () const inline
Returns
a const reference to the column permutation matrix
{
     eigen_assert(m_isInitialized && "FullPivHouseholderQR is not initialized.");
     return m_cols_permutation;
   }
References eigen_assert, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_cols_permutation, and Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_isInitialized.
compute() [1/2]
template<typename MatrixType_ , typename PermutationIndex_ > template<typename InputType > FullPivHouseholderQR& Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::compute (const EigenBase< InputType > & matrix)
Referenced by ctms_decompositions(), and Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::FullPivHouseholderQR().
compute() [2/2]
template<typename MatrixType_ , typename PermutationIndex_ > template<typename InputType > FullPivHouseholderQR<MatrixType, PermutationIndex>& Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::compute (const EigenBase< InputType > & matrix)
Performs the QR factorization of the given matrix matrix. The result of the factorization is stored into *this, and a reference to *this is returned.
See also
class FullPivHouseholderQR, FullPivHouseholderQR(const MatrixType&)
{
   m_qr = matrix.derived();
   computeInPlace();
   return *this;
 }
References Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::computeInPlace(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_qr, and matrix().
computeInPlace()
template<typename MatrixType , typename PermutationIndex > void Eigen::FullPivHouseholderQR< MatrixType, PermutationIndex >::computeInPlace protected
{
   eigen_assert(m_qr.cols() <= NumTraits<PermutationIndex>::highest());
   using std::abs;
   Index rows = m_qr.rows();
   Index cols = m_qr.cols();
   Index size = (std::min)(rows, cols);
   m_hCoeffs.resize(size);
   m_temp.resize(cols);
   m_precision = NumTraits<Scalar>::epsilon() * RealScalar(size);
   m_rows_transpositions.resize(size);
   m_cols_transpositions.resize(size);
   Index number_of_transpositions = 0;
   RealScalar biggest(0);
   m_nonzero_pivots = size;  // the generic case is that in which all pivots are nonzero (invertible case)
   m_maxpivot = RealScalar(0);
   for (Index k = 0; k < size; ++k) {
     Index row_of_biggest_in_corner, col_of_biggest_in_corner;
     typedef internal::scalar_score_coeff_op<Scalar> Scoring;
     typedef typename Scoring::result_type Score;
     Score score = m_qr.bottomRightCorner(rows - k, cols - k)
                       .unaryExpr(Scoring())
                       .maxCoeff(&row_of_biggest_in_corner, &col_of_biggest_in_corner);
     row_of_biggest_in_corner += k;
     col_of_biggest_in_corner += k;
     RealScalar biggest_in_corner =
         internal::abs_knowing_score<Scalar>()(m_qr(row_of_biggest_in_corner, col_of_biggest_in_corner), score);
     if (k == 0) biggest = biggest_in_corner;
     // if the corner is negligible, then we have less than full rank, and we can finish early
     if (internal::isMuchSmallerThan(biggest_in_corner, biggest, m_precision)) {
       m_nonzero_pivots = k;
       for (Index i = k; i < size; i++) {
         m_rows_transpositions.coeffRef(i) = internal::convert_index<PermutationIndex>(i);
         m_cols_transpositions.coeffRef(i) = internal::convert_index<PermutationIndex>(i);
         m_hCoeffs.coeffRef(i) = Scalar(0);
       }
       break;
     }
     m_rows_transpositions.coeffRef(k) = internal::convert_index<PermutationIndex>(row_of_biggest_in_corner);
     m_cols_transpositions.coeffRef(k) = internal::convert_index<PermutationIndex>(col_of_biggest_in_corner);
     if (k != row_of_biggest_in_corner) {
       m_qr.row(k).tail(cols - k).swap(m_qr.row(row_of_biggest_in_corner).tail(cols - k));
       ++number_of_transpositions;
     }
     if (k != col_of_biggest_in_corner) {
       m_qr.col(k).swap(m_qr.col(col_of_biggest_in_corner));
       ++number_of_transpositions;
     }
     RealScalar beta;
     m_qr.col(k).tail(rows - k).makeHouseholderInPlace(m_hCoeffs.coeffRef(k), beta);
     m_qr.coeffRef(k, k) = beta;
     // remember the maximum absolute value of diagonal coefficients
     if (abs(beta) > m_maxpivot) m_maxpivot = abs(beta);
     m_qr.bottomRightCorner(rows - k, cols - k - 1)
         .applyHouseholderOnTheLeft(m_qr.col(k).tail(rows - k - 1), m_hCoeffs.coeffRef(k), &m_temp.coeffRef(k + 1));
   }
   m_cols_permutation.setIdentity(cols);
   for (Index k = 0; k < size; ++k) m_cols_permutation.applyTranspositionOnTheRight(k, m_cols_transpositions.coeff(k));
   m_det_p = (number_of_transpositions % 2) ? -1 : 1;
   m_isInitialized = true;
 }
References abs(), Eigen::PermutationBase< Derived >::applyTranspositionOnTheRight(), beta, Eigen::PlainObjectBase< Derived >::coeff(), Eigen::Matrix< Scalar_, Rows_, Cols_, Options_, MaxRows_, MaxCols_ >::coeffRef(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::cols(), eigen_assert, oomph::SarahBL::epsilon, i, Eigen::internal::isMuchSmallerThan(), k, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_cols_permutation, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_cols_transpositions, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_det_p, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_hCoeffs, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_isInitialized, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_maxpivot, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_nonzero_pivots, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_precision, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_qr, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_rows_transpositions, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_temp, min, Eigen::PlainObjectBase< Derived >::resize(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::rows(), Eigen::PermutationBase< Derived >::setIdentity(), and Eigen::EigenBase< Derived >::size().
Referenced by Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::compute(), and Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::FullPivHouseholderQR().
determinant()
template<typename MatrixType , typename PermutationIndex > MatrixType::Scalar Eigen::FullPivHouseholderQR< MatrixType, PermutationIndex >::determinant
Returns
the determinant of the matrix of which *this is the QR decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the QR decomposition has already been computed.
Note
This is only for square matrices.
Warning
a determinant can be very big or small, so for matrices of large enough dimension, there is a risk of overflow/underflow. One way to work around that is to use logAbsDeterminant() instead.
See also
absDeterminant(), logAbsDeterminant(), MatrixBase::determinant()
{
   eigen_assert(m_isInitialized && "HouseholderQR is not initialized.");
   eigen_assert(m_qr.rows() == m_qr.cols() && "You can't take the determinant of a non-square matrix!");
   Scalar detQ;
   internal::householder_determinant<HCoeffsType, Scalar, NumTraits<Scalar>::IsComplex>::run(m_hCoeffs, detQ);
   return isInjective() ? (detQ * Scalar(m_det_p)) * m_qr.diagonal().prod() : Scalar(0);
 }
References eigen_assert, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::isInjective(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_det_p, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_hCoeffs, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_isInitialized, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_qr, and Eigen::run().
dimensionOfKernel()
template<typename MatrixType_ , typename PermutationIndex_ > Index Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::dimensionOfKernel () const inline
Returns
the dimension of the kernel of the matrix of which *this is the QR decomposition.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
{
     eigen_assert(m_isInitialized && "FullPivHouseholderQR is not initialized.");
     return cols() - rank();
   }
References Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::cols(), eigen_assert, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_isInitialized, and Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::rank().
hCoeffs()
template<typename MatrixType_ , typename PermutationIndex_ > const HCoeffsType& Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::hCoeffs () const inline
Returns
a const reference to the vector of Householder coefficients used to represent the factor Q.
For advanced uses only.
 { return m_hCoeffs; }
References Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_hCoeffs.
inverse()
template<typename MatrixType_ , typename PermutationIndex_ > const Inverse<FullPivHouseholderQR> Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::inverse () const inline
Returns
the inverse of the matrix of which *this is the QR decomposition.
Note
If this matrix is not invertible, the returned matrix has undefined coefficients. Use isInvertible() to first determine whether this matrix is invertible.
{
     eigen_assert(m_isInitialized && "FullPivHouseholderQR is not initialized.");
     return Inverse<FullPivHouseholderQR>(*this);
   }
References eigen_assert, and Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_isInitialized.
isInjective()
template<typename MatrixType_ , typename PermutationIndex_ > bool Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::isInjective () const inline
Returns
true if the matrix of which *this is the QR decomposition represents an injective linear map, i.e. has trivial kernel; false otherwise.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
{
     eigen_assert(m_isInitialized && "FullPivHouseholderQR is not initialized.");
     return rank() == cols();
   }
References Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::cols(), eigen_assert, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_isInitialized, and Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::rank().
Referenced by Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::absDeterminant(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::determinant(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::isInvertible(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::logAbsDeterminant(), and Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::signDeterminant().
isInvertible()
template<typename MatrixType_ , typename PermutationIndex_ > bool Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::isInvertible () const inline
Returns
true if the matrix of which *this is the QR decomposition is invertible.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
{
     eigen_assert(m_isInitialized && "FullPivHouseholderQR is not initialized.");
     return isInjective() && isSurjective();
   }
References eigen_assert, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::isInjective(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::isSurjective(), and Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_isInitialized.
isSurjective()
template<typename MatrixType_ , typename PermutationIndex_ > bool Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::isSurjective () const inline
Returns
true if the matrix of which *this is the QR decomposition represents a surjective linear map; false otherwise.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
{
     eigen_assert(m_isInitialized && "FullPivHouseholderQR is not initialized.");
     return rank() == rows();
   }
References eigen_assert, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_isInitialized, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::rank(), and Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::rows().
Referenced by Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::isInvertible().
logAbsDeterminant()
template<typename MatrixType , typename PermutationIndex > MatrixType::RealScalar Eigen::FullPivHouseholderQR< MatrixType, PermutationIndex >::logAbsDeterminant
Returns
the natural log of the absolute value of the determinant of the matrix of which *this is the QR decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the QR decomposition has already been computed.
Note
This is only for square matrices.
This method is useful to work around the risk of overflow/underflow that's inherent to determinant computation.
See also
determinant(), absDeterminant(), MatrixBase::determinant()
{
   eigen_assert(m_isInitialized && "FullPivHouseholderQR is not initialized.");
   eigen_assert(m_qr.rows() == m_qr.cols() && "You can't take the determinant of a non-square matrix!");
   return isInjective() ? m_qr.diagonal().cwiseAbs().array().log().sum() : -NumTraits<RealScalar>::infinity();
 }
References eigen_assert, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::isInjective(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_isInitialized, and Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_qr.
matrixQ()
template<typename MatrixType , typename PermutationIndex > FullPivHouseholderQR< MatrixType, PermutationIndex >::MatrixQReturnType Eigen::FullPivHouseholderQR< MatrixType, PermutationIndex >::matrixQ (void) const inline
Returns
Expression object representing the matrix Q
{
   eigen_assert(m_isInitialized && "FullPivHouseholderQR is not initialized.");
   return MatrixQReturnType(m_qr, m_hCoeffs, m_rows_transpositions);
 }
References eigen_assert, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_hCoeffs, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_isInitialized, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_qr, and Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_rows_transpositions.
matrixQR()
template<typename MatrixType_ , typename PermutationIndex_ > const MatrixType& Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::matrixQR () const inline
Returns
a reference to the matrix where the Householder QR decomposition is stored
{
     eigen_assert(m_isInitialized && "FullPivHouseholderQR is not initialized.");
     return m_qr;
   }
References eigen_assert, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_isInitialized, and Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_qr.
maxPivot()
template<typename MatrixType_ , typename PermutationIndex_ > RealScalar Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::maxPivot () const inline
Returns
the absolute value of the biggest pivot, i.e. the biggest diagonal coefficient of U.
 { return m_maxpivot; }
References Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_maxpivot.
nonzeroPivots()
template<typename MatrixType_ , typename PermutationIndex_ > Index Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::nonzeroPivots () const inline
Returns
the number of nonzero pivots in the QR decomposition. Here nonzero is meant in the exact sense, not in a fuzzy sense. So that notion isn't really intrinsically interesting, but it is still useful when implementing algorithms.
See also
rank()
{
     eigen_assert(m_isInitialized && "LU is not initialized.");
     return m_nonzero_pivots;
   }
References eigen_assert, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_isInitialized, and Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_nonzero_pivots.
rank()
template<typename MatrixType_ , typename PermutationIndex_ > Index Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::rank () const inline
Returns
the rank of the matrix of which *this is the QR decomposition.
Note
This method has to determine which pivots should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
{
     using std::abs;
     eigen_assert(m_isInitialized && "FullPivHouseholderQR is not initialized.");
     RealScalar premultiplied_threshold = abs(m_maxpivot) * threshold();
     Index result = 0;
     for (Index i = 0; i < m_nonzero_pivots; ++i) result += (abs(m_qr.coeff(i, i)) > premultiplied_threshold);
     return result;
   }
References abs(), eigen_assert, i, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_isInitialized, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_maxpivot, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_nonzero_pivots, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_qr, and Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::threshold().
Referenced by Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::_solve_impl(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::_solve_impl_transposed(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::dimensionOfKernel(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::isInjective(), and Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::isSurjective().
rows()
template<typename MatrixType_ , typename PermutationIndex_ > Index Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::rows () const inline
 { return m_qr.rows(); }
References Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_qr.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::_solve_impl(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::_solve_impl_transposed(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::computeInPlace(), Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType, PermutationIndex >::evalTo(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::isSurjective(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
rowsTranspositions()
template<typename MatrixType_ , typename PermutationIndex_ > const IntDiagSizeVectorType& Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::rowsTranspositions () const inline
Returns
a const reference to the vector of indices representing the rows transpositions
{
     eigen_assert(m_isInitialized && "FullPivHouseholderQR is not initialized.");
     return m_rows_transpositions;
   }
References eigen_assert, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_isInitialized, and Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_rows_transpositions.
setThreshold() [1/2]
template<typename MatrixType_ , typename PermutationIndex_ > FullPivHouseholderQR& Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::setThreshold (const RealScalar & threshold) inline
Allows to prescribe a threshold to be used by certain methods, such as rank(), who need to determine when pivots are to be considered nonzero. This is not used for the QR decomposition itself.
When it needs to get the threshold value, Eigen calls threshold(). By default, this uses a formula to automatically determine a reasonable threshold. Once you have called the present method setThreshold(const RealScalar&), your value is used instead.
Parameters
threshold The new value to use as the threshold.
A pivot will be considered nonzero if its absolute value is strictly greater than \(\vert pivot \vert \leqslant threshold \times \vert maxpivot \vert \) where maxpivot is the biggest pivot.
If you want to come back to the default behavior, call setThreshold(Default_t)
{
     m_usePrescribedThreshold = true;
     m_prescribedThreshold = threshold;
     return *this;
   }
References Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_prescribedThreshold, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_usePrescribedThreshold, and Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::threshold().
setThreshold() [2/2]
template<typename MatrixType_ , typename PermutationIndex_ > FullPivHouseholderQR& Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::setThreshold (Default_t) inline
Allows to come back to the default behavior, letting Eigen use its default formula for determining the threshold.
You should pass the special object Eigen::Default as parameter here.
qr.setThreshold(Eigen::Default);
See the documentation of setThreshold(const RealScalar&).
{
     m_usePrescribedThreshold = false;
     return *this;
   }
References Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_usePrescribedThreshold.
signDeterminant()
template<typename MatrixType , typename PermutationIndex > MatrixType::Scalar Eigen::FullPivHouseholderQR< MatrixType, PermutationIndex >::signDeterminant
Returns
the sign of the determinant of the matrix of which *this is the QR decomposition. It has only linear complexity (that is, O(n) where n is the dimension of the square matrix) as the QR decomposition has already been computed.
Note
This is only for square matrices.
This method is useful to work around the risk of overflow/underflow that's inherent to determinant computation.
See also
determinant(), absDeterminant(), logAbsDeterminant(), MatrixBase::determinant()
{
   eigen_assert(m_isInitialized && "FullPivHouseholderQR is not initialized.");
   eigen_assert(m_qr.rows() == m_qr.cols() && "You can't take the determinant of a non-square matrix!");
   Scalar detQ;
   internal::householder_determinant<HCoeffsType, Scalar, NumTraits<Scalar>::IsComplex>::run(m_hCoeffs, detQ);
   return isInjective() ? (detQ * Scalar(m_det_p)) * m_qr.diagonal().array().sign().prod() : Scalar(0);
 }
References eigen_assert, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::isInjective(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_det_p, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_hCoeffs, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_isInitialized, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_qr, and Eigen::run().
threshold()
template<typename MatrixType_ , typename PermutationIndex_ > RealScalar Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::threshold () const inline
Returns the threshold that will be used by certain methods such as rank().
See the documentation of setThreshold(const RealScalar&).
{
     eigen_assert(m_isInitialized || m_usePrescribedThreshold);
     return m_usePrescribedThreshold ? m_prescribedThreshold
                                     // this formula comes from experimenting (see "LU precision tuning" thread on the
                                     // list) and turns out to be identical to Higham's formula used already in LDLt.
                                     : NumTraits<Scalar>::epsilon() * RealScalar(m_qr.diagonalSize());
   }
References eigen_assert, oomph::SarahBL::epsilon, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_isInitialized, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_prescribedThreshold, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_qr, and Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_usePrescribedThreshold.
Referenced by Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::rank(), and Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::setThreshold().
Friends And Related Function Documentation
SolverBase< FullPivHouseholderQR >
template<typename MatrixType_ , typename PermutationIndex_ > friend class SolverBase< FullPivHouseholderQR > friend
Member Data Documentation
m_cols_permutation
template<typename MatrixType_ , typename PermutationIndex_ > PermutationType Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_cols_permutation protected
Referenced by Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::_solve_impl(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::_solve_impl_transposed(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::colsPermutation(), and Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::computeInPlace().
m_cols_transpositions
template<typename MatrixType_ , typename PermutationIndex_ > IntDiagSizeVectorType Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_cols_transpositions protected
Referenced by Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::computeInPlace().
m_det_p
template<typename MatrixType_ , typename PermutationIndex_ > Index Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_det_p protected
Referenced by Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::computeInPlace(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::determinant(), and Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::signDeterminant().
m_hCoeffs
template<typename MatrixType_ , typename PermutationIndex_ > HCoeffsType Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_hCoeffs protected
Referenced by Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::_solve_impl(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::_solve_impl_transposed(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::computeInPlace(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::determinant(), Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType, PermutationIndex >::evalTo(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::hCoeffs(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::matrixQ(), and Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::signDeterminant().
m_isInitialized
template<typename MatrixType_ , typename PermutationIndex_ > bool Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_isInitialized protected
Referenced by Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::absDeterminant(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::colsPermutation(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::computeInPlace(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::determinant(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::dimensionOfKernel(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::inverse(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::isInjective(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::isInvertible(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::isSurjective(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::logAbsDeterminant(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::matrixQ(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::matrixQR(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::nonzeroPivots(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::rank(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::rowsTranspositions(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::signDeterminant(), and Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::threshold().
m_maxpivot
template<typename MatrixType_ , typename PermutationIndex_ > RealScalar Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_maxpivot protected
Referenced by Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::computeInPlace(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::maxPivot(), and Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::rank().
m_nonzero_pivots
template<typename MatrixType_ , typename PermutationIndex_ > Index Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_nonzero_pivots protected
Referenced by Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::computeInPlace(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::nonzeroPivots(), and Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::rank().
m_precision
template<typename MatrixType_ , typename PermutationIndex_ > RealScalar Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_precision protected
Referenced by Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::computeInPlace().
m_prescribedThreshold
template<typename MatrixType_ , typename PermutationIndex_ > RealScalar Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_prescribedThreshold protected
Referenced by Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::setThreshold(), and Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::threshold().
m_qr
template<typename MatrixType_ , typename PermutationIndex_ > MatrixType Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_qr protected
Referenced by Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::_solve_impl(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::_solve_impl_transposed(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::absDeterminant(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::cols(), Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType, PermutationIndex >::cols(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::compute(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::computeInPlace(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::determinant(), Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType, PermutationIndex >::evalTo(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::logAbsDeterminant(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::matrixQ(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::matrixQR(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::rank(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::rows(), Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType, PermutationIndex >::rows(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::signDeterminant(), and Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::threshold().
m_rows_transpositions
template<typename MatrixType_ , typename PermutationIndex_ > IntDiagSizeVectorType Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_rows_transpositions protected
Referenced by Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::_solve_impl(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::_solve_impl_transposed(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::computeInPlace(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::matrixQ(), and Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::rowsTranspositions().
m_temp
template<typename MatrixType_ , typename PermutationIndex_ > RowVectorType Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_temp protected
Referenced by Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::computeInPlace().
m_usePrescribedThreshold
template<typename MatrixType_ , typename PermutationIndex_ > bool Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_usePrescribedThreshold protected
Referenced by Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::setThreshold(), and Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::threshold().
The documentation for this class was generated from the following files:
ForwardDeclarations.h
FullPivHouseholderQR.h