MercuryDPM: Vec3D Class Reference
Vec3D Class Reference
#include <Vector.h>
Public Member Functions
Vec3D ()
constructor
Vec3D (const SmallVector< 3 > &vector)
Vec3D (const std::array< Mdouble, 3 > &vector)
Alternative constructor, taking a const std::array<Mdouble, 3>
Vec3D (const Mdouble x, const Mdouble y, const Mdouble z)
Alternative constructor, taking the three elements as arguments.
void setZero ()
Sets all elements to zero.
void setNaN ()
Sets all elements to NaN.
bool isZero () const
Checks if ALL elements are zero.
bool isNaN () const
Checks if ALL elements are zero.
Vec3D operator+ (const Vec3D &a) const
Adds another vector.
Vec3D operator- (const Vec3D a) const
Binary vector subtraction.
bool operator== (const Vec3D &a) const
Vec3D multiplyElementwise (const Vec3D &a) const
Vec3D divideElementwise (const Vec3D &a) const
Vec3D signedSquare () const
Vec3D operator* (const Mdouble a) const
Multiplies by a scalar.
Vec3D operator/ (Mdouble a) const
Divides by a scalar.
Vec3D & operator+= (const Vec3D &a)
Adds another vector.
bool operator>= (const Vec3D &a) const
Checks if all coordinates satisfy this>=a.
bool operator< (const Vec3D &a) const
Vec3D & operator-= (const Vec3D &a)
Subtracts another vector.
Vec3D & operator*= (Mdouble a)
Multiplies by a scalar.
Vec3D & operator/= (const Mdouble a)
Divides by a scalar.
Mdouble dot (const Vec3D &b) const
Calculates the dot product of this with another Vec3D: \(this \cdot b\).
void normalise ()
Makes this Vec3D unit length.
void setLength (Mdouble length)
Make this Vec3D a certain length.
Vec3D cross (const Vec3D &b) const
Calculates the cross product of this with another Vec3D: \(this \times b\).
Mdouble getLength () const
Calculates the length of this Vec3D: \(\sqrt{a\cdot a} \).
Mdouble getLengthSquared () const
Calculates the squared length of this Vec3D: \(a\cdot a \).
Mdouble getComponent (int index) const
Returns the requested component of this Vec3D.
void setComponent (int index, double val)
Sets the requested component of this Vec3D to the requested value.
Mdouble & operator[] (int index)
Implements operator [] to easier access to x, y, z.
const Mdouble & operator[] (int index) const
Implements static variant of operator [].
Mdouble & x ()
RW reference to X.
Mdouble x () const
RO reference to X.
Mdouble & y ()
RW reference to Y.
Mdouble y () const
RO reference to Y.
Mdouble & z ()
RW reference to Z.
Mdouble z () const
RO reference to Z.
void setX (Mdouble x)
void setY (Mdouble y)
void setZ (Mdouble z)
Mdouble getX () const
Mdouble getY () const
Mdouble getZ () const
void set (Mdouble x, Mdouble y, Mdouble z)
Mdouble getRadialCoordinateSquared () const
Returns the square of the radial cylindrical coordinate, r^2=x^2+y^2.
Mdouble getRadialCoordinate () const
Returns the square of the radial cylindrical coordinate, r=sqrt(x^2+y^2).
Vec3D getSphericalCoordinates () const
Returns the representation of this Vec3D in spherical coordinates.
Vec3D getCylindricalCoordinates () const
Returns the representation of this Vec3D in cylindrical coordinates.
Vec3D getFromCylindricalCoordinates () const
Returns the representation of this Vec3D in cylindrical coordinates.
Vec3D getCylindricalTensorField (const Vec3D &position) const
Returns this vector field at point p to cylindrical coordinates.
bool isEqualTo (const Vec3D &other, double tol) const
Checks if the length this Vec3D is equal the length of other with a certain tolerance.
Static Public Member Functions
static Mdouble dot (const Vec3D &a, const Vec3D &b)
Calculates the dot product of two Vec3D: \(a \cdot b\).
static Vec3D max (const Vec3D &a, const Vec3D &b)
Calculates the pointwise maximum of two Vec3D.
static Vec3D min (const Vec3D &a, const Vec3D &b)
Calculates the pointwise minimum of two Vec3D.
static double max (const Vec3D &a)
Calculates the maximum coordinate of vector a.
static double min (const Vec3D &a)
Calculates the minimum coordinate of vector a.
static Vec3D square (const Vec3D &a)
Calculates the pointwise square of a Vec3D.
static Vec3D sqrt (const Vec3D &a)
Calculates the pointwise square root of a Vec3D.
static Vec3D cross (const Vec3D &a, const Vec3D &b)
Calculates the cross product of two Vec3D: \(a \times b\).
static Mdouble getDistance (const Vec3D &a, const Vec3D &b)
Calculates the distance between two Vec3D: \(\sqrt{\left(a-b\right) \cdot \left(a-b\right)} \).
static Mdouble getDistanceSquared (const Vec3D &a, const Vec3D &b)
Calculates the squared distance between two Vec3D: \(\left(a-b\right) \cdot \left(a-b\right) \).
static Mdouble getLength (const Vec3D &a)
Calculates the length of a Vec3D: \(\sqrt{a\cdot a} \).
static Mdouble getLengthSquared (const Vec3D &a)
Calculates the squared length of a Vec3D: \(a\cdot a \).
static Vec3D getUnitVector (const Vec3D &a)
Returns a unit Vec3D based on a.
Public Attributes
Mdouble X
the vector components
Mdouble Y
Mdouble Z
Friends
std::ostream & operator<< (std::ostream &os, const Vec3D &a)
Adds elements to an output stream.
std::istream & operator>> (std::istream &is, Vec3D &a)
Adds elements to an input stream.
Vec3D operator- (const Vec3D &a)
Reverts the direction of a vector.
Vec3D operator* (Mdouble a, const Vec3D &b)
Multiplies all elements by a scalar.
Constructor & Destructor Documentation
Vec3D() [1/4]
Vec3D::Vec3D () inline
constructor
     { setZero(); }
References setZero().
Referenced by cross(), divideElementwise(), getCylindricalCoordinates(), getCylindricalTensorField(), getFromCylindricalCoordinates(), getUnitVector(), max(), min(), multiplyElementwise(), operator*(), operator+(), operator-(), operator/(), signedSquare(), sqrt(), and square().
Vec3D() [2/4]
Vec3D::Vec3D (const SmallVector< 3 > & vector)
Alternative constructor, that constructs a Vec3D from a SmallVector size 3
Parameters
[in] vector Small vector that should be copied
 {
     X = vector[0];
     Y = vector[1];
     Z = vector[2];
 }
References X, Y, and Z.
Vec3D() [3/4]
Vec3D::Vec3D (const std::array< Mdouble, 3 > & vector) inline
Alternative constructor, taking a const std::array<Mdouble, 3>
Alternative constructor, lets you define all three elements.
Parameters
[in] vector std::array<Mdouble, 3>
     {
         X = vector[0];
         Y = vector[1];
         Z = vector[2];
     };
References X, Y, and Z.
Vec3D() [4/4]
Vec3D::Vec3D (const Mdouble x, const Mdouble y, const Mdouble z) inline
Alternative constructor, taking the three elements as arguments.
Alternative constructor, lets you define all three elements.
Parameters
[in] x the x-component
[in] y the y-component
[in] z the z-component
     {
         X = x;
         Y = y;
         Z = z;
     }
References X, x(), Y, y(), Z, and z().
Member Function Documentation
cross() [1/2]
Vec3D Vec3D::cross (const Vec3D & a, const Vec3D & b) static
Calculates the cross product of two Vec3D: \(a \times b\).
Calculates the cross product of two vectors NB: this is a STATIC function!
Parameters
[in] a the first vector
[in] b the second vector
Returns
the cross product of the arguments
 {
     return Vec3D(a.Y * b.Z - a.Z * b.Y, a.Z * b.X - a.X * b.Z, a.X * b.Y - a.Y * b.X);
 }
References a, b, and Vec3D().
Referenced by MarbleRun::actionsAfterTimeStep(), IntersectionOfWalls::add3PointObject(), ChuteWithHopper::addHopper(), IntersectionOfWalls::addTetra(), IntersectionOfWalls::addTetraSTL(), MeshTriangle::checkInteractions(), DPMBase::computeAllForces(), Mercury3Dclump::computeAllForces(), DPMBase::computeForcesDueToWalls(), FrictionInteraction::computeFrictionForce(), MindlinRollingTorsionInteraction::computeFrictionForce(), DPMBase::computeInternalForce(), ChuteWithPeriodicInflow::computeInternalForces(), IntersectionOfWalls::createOpenPrism(), IntersectionOfWalls::createPrism(), cross(), BaseParticle::getAngularMomentum(), MeshTriangle::getBaricentricWeight(), HorizontalBaseScrew::getDistanceAndNormal(), BasicIntersectionOfWalls::getDistanceAndNormal(), BaseWall::getInteractionWith(), TriangleMeshWall::getInteractionWith(), ParticleParticleCollision::getRelativeVelocity(), WallParticleCollision::getRelativeVelocity(), Membrane::Edge::getSineHalfTheta(), BaseInteractable::getVelocityAtContact(), TriangleMeshWall::getVolumeTetrahedron(), InfiniteWall::InfiniteWall(), TriangleWall::isInsideTriangle(), main(), WearableTriangulatedWall::processDebris(), ClumpParticle::rotatePrincipalDirections(), AngledPeriodicBoundary::set(), TriangulatedWall::setNormalsAndNeighbours(), IntersectionOfWalls::setPointsAndLines(), AxisymmetricHopper::setupInitialConditions(), WearableTriangleMeshWall::storeDebris(), WearableTriangulatedWall::storeDebris(), UniformRandomPDs(), ClumpParticle::updatePebblesVelPos(), MeshTriangle::updateVertexAndNormal(), TriangleWall::updateVertexAndNormal(), and WallVTKWriter::writeVTKSurfaceArea().
cross() [2/2]
Vec3D Vec3D::cross (const Vec3D & b) const inline
Calculates the cross product of this with another Vec3D: \(this \times b\).
 { return Vec3D::cross(*this, b); }
References b, and cross().
divideElementwise()
Vec3D Vec3D::divideElementwise (const Vec3D & a) const inline
{
         return Vec3D(X/a.X, Y/a.Y, Z/a.Z);
     }
References a, Vec3D(), X, Y, and Z.
dot() [1/2]
Mdouble Vec3D::dot (const Vec3D & a, const Vec3D & b) static
Calculates the dot product of two Vec3D: \(a \cdot b\).
Calculates the dot product of two vectors. NB: this is a STATIC function!
Parameters
[in] a the first vector
[in] b the second vector
Returns
the resulting scalar
 {
     return a.X * b.X + a.Y * b.Y + a.Z * b.Z;
 }
References a, and b.
Referenced by ChangingTOIParticle::actionsAfterTimeStep(), IntersectionOfWalls::addTetraSTL(), Membrane::Edge::applyBendForce(), Membrane::Edge::applyStretchForce(), Membrane::Edge::calculateUPre(), ConstantMassFlowMaserBoundary::checkBoundaryAfterParticleMoved(), CGHandler::computeContactPoints(), FrictionInteraction::computeFrictionForce(), MindlinInteraction::computeFrictionForce(), MindlinRollingTorsionInteraction::computeFrictionForce(), ChuteWithPeriodicInflow::computeInternalForces(), HertzianBSHPViscoelasticInteraction::computeNormalForce(), HertzianViscoelasticInteraction::computeNormalForce(), LinearPlasticViscoelasticInteraction::computeNormalForce(), LinearViscoelasticInteraction::computeNormalForce(), MeltableInteraction::computeNormalForce(), SinterInteraction::computeNormalForce(), SinterLinInteraction::computeNormalForce(), SPHInteraction::computeNormalForce(), HertzianSinterInteraction::computeSinterForce(), SlidingFrictionInteraction::computeSlidingSpring(), HorizontalBaseScrew::convertLimits(), AngledPeriodicBoundary::distance(), dot(), BaseInteraction::gatherContactStatistics(), MeshTriangle::getBaricentricWeight(), CGCoordinates::R::getCNormal(), ConstantMassFlowMaserBoundary::getDistance(), SubcriticalMaserBoundary::getDistance(), FluxBoundary::getDistance(), TriangulatedWall::Face::getDistance(), DeletionBoundary::getDistance(), PeriodicBoundary::getDistance(), TimeDependentPeriodicBoundary::getDistance(), NurbsSurface::getDistance(), ArcWall::getDistanceAndNormal(), AxisymmetricIntersectionOfWalls::getDistanceAndNormal(), HorizontalBaseScrew::getDistanceAndNormal(), BasicIntersectionOfWalls::getDistanceAndNormal(), Combtooth::getDistanceAndNormal(), TriangleWall::getDistanceAndNormal(), TriangulatedWall::Face::getDistanceAndNormal(), IntersectionOfWalls::getDistanceAndNormal(), SubcriticalMaserBoundaryTEST::getDistanceFromRight(), InfiniteWall::getDistanceNormalOverlapSuperquadric(), MeshTriangle::getDistanceNormalOverlapType(), DPMBase::getGravitationalEnergy(), CGCoordinates::R::getINormal(), CGCoordinates::XYZ::getINormal(), InteractionHandler::getInteraction(), BaseWall::getInteractionWith(), BaseWall::getLinePlaneIntersect(), AngledPeriodicBoundary::getOpeningAngle(), MeltableInteraction::getOverlapGrowthRate(), CGCoordinates::R::getPNormal(), DPMBase::getRotationalEnergy(), BaseParticle::getRotationalEnergy(), ClumpParticle::getRotationalEnergy(), Membrane::Edge::getSineHalfTheta(), MindlinInteraction::getTangentialOverlap(), Membrane::getVolume(), TriangleMeshWall::getVolumeTetrahedron(), InfiniteWallWithHole::getWallDistance(), FrictionInteraction::integrate(), MindlinRollingTorsionInteraction::integrate(), PeriodicBoundary::isClosestToLeftBoundary(), TimeDependentPeriodicBoundary::isClosestToLeftBoundary(), ConstantMassFlowMaserBoundary::isClosestToRightBoundary(), SubcriticalMaserBoundary::isClosestToRightBoundary(), BaseWall::isInsideWallVTK(), main(), InfiniteWallWithHole::move_time(), SuperQuadricParticle::overlapFromContactPoint(), BaseWall::projectOntoWallVTK(), ClumpParticle::rotatePrincipalDirections(), ClumpParticle::rotateTensorOfInertia(), DeletionBoundary::set(), FluxBoundary::set(), ArcWall::set(), ConstantMassFlowMaserBoundary::set(), PeriodicBoundary::set(), SubcriticalMaserBoundary::set(), InfiniteWallWithHole::set(), TimeDependentPeriodicBoundary::set(), AngledPeriodicBoundary::set(), ChutePeriodic::set_chute_parameters(), Vreman::set_symmetric_contraction(), ContractionWithPeriodicInflow::set_symmetric_contraction(), ChuteWithPeriodicInflowAndContraction::set_symmetric_contraction(), ChuteWithContraction::set_symmetric_contraction(), ConstantMassFlowMaserBoundary::setPlanewiseShift(), PeriodicBoundary::setPlanewiseShift(), SubcriticalMaserBoundary::setPlanewiseShift(), IntersectionOfWalls::setPointsAndLines(), AngledPeriodicBoundary::shiftPosition(), AngledPeriodicBoundary::shiftPositions(), WearableTriangulatedWall::storeDebris(), ClumpParticle::updateExtraQuantities(), MindlinInteraction::updateK_t(), DPMBase::writeEneTimeStep(), LawinenBox::writeEneTimeStep(), BaseCoupling< M, O >::writeEneTimeStep(), SilbertHstop::writeToEne(), and BaseInteraction::writeToFStat().
dot() [2/2]
Mdouble Vec3D::dot (const Vec3D & b) const inline
Calculates the dot product of this with another Vec3D: \(this \cdot b\).
 { return Vec3D::dot(*this, b); }
References b, and dot().
getComponent()
Mdouble Vec3D::getComponent (int index) const
Returns the requested component of this Vec3D.
returns the vector element belonging to the given index.
Parameters
[in] index the index of interest (should be 0, 1 or 2)
Returns
the value of the vector element belonging to the given index
 {
     switch (index)
     {
         case 0:
             return X;
         case 1:
             return Y;
         case 2:
             return Z;
         default:
             logger(ERROR, "[Vector::getComponent] Index = %, which is too high for a 3D vector (should be 0-2).",
                    index);
             return 0;
     }
 }
References ERROR, logger, X, Y, and Z.
Referenced by MeshTriangle::checkInteractions(), Dipole::computeMultipoleExpansion(), Domain::containsParticle(), Panel::createPanels(), Domain::findNearbyBoundaries(), Panel::Panel(), Domain::setBounds(), and Domain::setRange().
getCylindricalCoordinates()
Vec3D Vec3D::getCylindricalCoordinates () const
Returns the representation of this Vec3D in cylindrical coordinates.
Transforms the (Cartesian) vector to cylindrical coordinates
Returns
Transformed vector
 {
     return Vec3D(std::sqrt(X * X + Y * Y), std::atan2(Y, X), Z);
 }
References atan2(), sqrt(), Vec3D(), X, Y, and Z.
Referenced by CylinderInsertionBoundary::placeParticle().
getCylindricalTensorField()
Vec3D Vec3D::getCylindricalTensorField (const Vec3D & p) const
Returns this vector field at point p to cylindrical coordinates.
Transforms the (Cartesian) vector to cylindrical coordinates. See https://en.wikipedia.org/wiki/Vector_fields_in_cylindrical_and_spherical_coordinates
Returns
Transformed vector
 {
     //define sin(A)=y/r, cos(A)=x/r
     Mdouble r = std::sqrt(p.X * p.X + p.Y * p.Y);
     Mdouble s = p.Y / r;
     Mdouble c = p.X / r;
     if (r == 0)
     {
         s = 0;
         c = 1;
     }
     return Vec3D(X * c + Y * s, -X * s + Y * c, Z);
 }
References calibrate::c, p, UniformPSDSelfTest::r, s, sqrt(), Vec3D(), X, Y, and Z.
Referenced by CGFields::StandardFields::setCylindricalFields(), and CGFields::GradVelocityField::setCylindricalFields().
getDistance()
Mdouble Vec3D::getDistance (const Vec3D & a, const Vec3D & b) static
Calculates the distance between two Vec3D: \(\sqrt{\left(a-b\right) \cdot \left(a-b\right)} \).
Calculates the square of the distance (i.e. the length of the difference) between two vectors. NB: this is a STATIC function!
Parameters
[in] a the first vector
[in] b the second vector
Returns
the square of the distance between the two arguments.
Calculates the distance (i.e. the length of the difference) between two vectors NB: this is a STATIC function!
Parameters
[in] a the first vector
[in] b the second vector
Returns
the distance between the two arguments.
 {
     return std::sqrt(getDistanceSquared(a, b));
 }
References a, b, getDistanceSquared(), and sqrt().
Referenced by main(), Panel::setPanelInteractions(), and WallVTKWriter::writeCGFields().
getDistanceSquared()
static Mdouble Vec3D::getDistanceSquared (const Vec3D & a, const Vec3D & b) inline static
Calculates the squared distance between two Vec3D: \(\left(a-b\right) \cdot \left(a-b\right) \).
{
         const double X = a.X-b.X;
         const double Y = a.Y-b.Y;
         const double Z = a.Z-b.Z;
         return (X * X + Y * Y + Z * Z);
         //return getLengthSquared(a - b);
     }
References a, b, X, Y, and Z.
Referenced by Mercury3Dclump::checkClumpForInteraction(), Mercury3Dclump::checkClumpForInteractionPeriodic(), DPMBase::checkParticleForInteractionLocal(), ChuteWithPeriodicInflow::computeInternalForces(), getDistance(), Mercury3D::hGridFindContactsWithTargetCell(), and BaseParticle::isInContactWith().
getFromCylindricalCoordinates()
Vec3D Vec3D::getFromCylindricalCoordinates () const
Returns the representation of this Vec3D in cylindrical coordinates.
Transforms the (cylindrical) vector to cartesian coordinates
Returns
Transformed vector
Todo:
 {
     return Vec3D(X * std::cos(Y), X * std::sin(Y), Z);
 }
References cos(), sin(), Vec3D(), X, Y, and Z.
getLength() [1/2]
Mdouble Vec3D::getLength () const
Calculates the length of this Vec3D: \(\sqrt{a\cdot a} \).
Calculates the length of this vector
Returns
the (scalar) length of this vector
 {
     return std::sqrt(getLengthSquared());
 }
References getLengthSquared(), and sqrt().
Referenced by CGHandler::computeContactPoints(), AngledPeriodicBoundarySecondUnitTest::computeExternalForces(), ChuteWithPeriodicInflow::computeInternalForces(), SphericalWall::getDistance(), SphericalWall::getDistanceAndNormal(), TriangulatedWall::Face::getDistanceAndNormal(), AngledPeriodicBoundary::set(), AxisymmetricHopper::setupInitialConditions(), and testCGHandler().
getLength() [2/2]
Mdouble Vec3D::getLength (const Vec3D & a) static
Calculates the length of a Vec3D: \(\sqrt{a\cdot a} \).
Calculates the length of a given vector NB: this is a STATIC function!
Parameters
[in] a vector to be measured.
Returns
length of the argument.
 {
     return a.getLength();
 }
References a.
Referenced by ChangingTOIParticle::actionsAfterTimeStep(), DrivenParticleClass::actionsAfterTimeStep(), NautaMixer::addScrew(), Membrane::Edge::applyBendForce(), BaseCluster::applyCentralForce(), Membrane::Edge::applyStretchForce(), BondedInteraction::bondInPlace(), SolidifyingLiquidMigrationWilletInteraction::bondInPlace(), Combtooth::Combtooth(), Mercury3Dclump::computeAllForces(), CGHandler::computeContactPoints(), FrictionInteraction::computeFrictionForce(), MindlinInteraction::computeFrictionForce(), MindlinRollingTorsionInteraction::computeFrictionForce(), ChuteWithPeriodicInflow::computeInternalForces(), ScrewsymmetricIntersectionOfWalls::computeNormalRadialDeltaN(), SlidingFrictionInteraction::computeSlidingSpring(), Quaternion::fromAxisAndAngle(), BaseInteraction::gatherContactStatistics(), AxisymmetricIntersectionOfWalls::getDistanceAndNormal(), HorizontalBaseScrew::getDistanceAndNormal(), Coil::getDistanceAndNormal(), Combtooth::getDistanceAndNormal(), CylindricalWall::getDistanceAndNormal(), InfiniteWallWithHole::getDistanceAndNormal(), ParabolaChute::getDistanceAndNormal(), SineWall::getDistanceAndNormal(), VChute::getDistanceAndNormal(), ClumpParticle::getRotationalEnergy(), MindlinInteraction::getTangentialOverlap(), SlidingFrictionInteraction::getTangentialOverlap(), main(), BaseCluster::makeDataAnalysis(), FileReader::read(), ClumpParticle::rotatePrincipalDirections(), Combtooth::set(), Chute::setChuteAngle(), WearableTriangleMeshWall::storeDebris(), ClumpParticle::updateExtraQuantities(), MindlinInteraction::updateK_t(), MeshTriangle::updateVertexAndNormal(), SingleParticle< SpeciesType >::writeEneTimeStep(), BaseInteraction::writeToFStat(), and WallVTKWriter::writeVTKSurfaceArea().
getLengthSquared() [1/2]
Mdouble Vec3D::getLengthSquared () const
Calculates the squared length of this Vec3D: \(a\cdot a \).
Calculates the square of the length of itself
Returns
the square of the length of this vector
 {
     return (X * X + Y * Y + Z * Z);
 }
References X, Y, and Z.
Referenced by DPM::computeLocalCGHGrid(), DPM::computeLocalVolumeFraction(), DPM::computeLocalVolumeFractionHGrid(), HorizontalBaseScrew::convertLimits(), Domain::findNewMPIInteractions(), NurbsSurface::getDistance(), HorizontalBaseScrew::getDistanceAndNormal(), TriangulatedWall::Face::getDistanceAndNormal(), CGCoordinates::XYZ::getDistanceSquared(), SuperQuadricParticle::getInitialGuessForContact(), BaseParticle::getInteractionWith(), SuperQuadricParticle::getInteractionWith(), getLength(), CGCoordinates::XYZ::getTangentialSquared(), isEqualTo(), and normalise().
getLengthSquared() [2/2]
static Mdouble Vec3D::getLengthSquared (const Vec3D & a) inline static
Calculates the squared length of a Vec3D: \(a\cdot a \).
Calculates the square of the length of a given vector. NB: this is a STATIC function!
Parameters
[in] a the vector.
Returns
the square of the length of the argument.
     {
         return (a.X * a.X + a.Y * a.Y + a.Z * a.Z);
     }
References a.
Referenced by LawinenBox::actionsBeforeTimeStep(), IntersectionOfWalls::add3PointObject(), ChuteWithHopper::addHopper(), IntersectionOfWalls::addPlate(), IntersectionOfWalls::addTetra(), IntersectionOfWalls::addTetraSTL(), PeriodicBoundary::checkBoundaryAfterParticlesMove(), FrictionInteraction::computeFrictionForce(), MindlinRollingTorsionInteraction::computeFrictionForce(), SlidingFrictionInteraction::computeFrictionForce(), ChuteWithPeriodicInflow::computeInternalForces(), IntersectionOfWalls::getDistanceAndNormal(), SimpleDrumSuperquadrics::getDistanceNormalOverlapSuperquadric(), FrictionInteraction::getElasticEnergy(), MindlinInteraction::getElasticEnergy(), MindlinRollingTorsionInteraction::getElasticEnergy(), SlidingFrictionInteraction::getElasticEnergy(), BaseParticle::getKineticEnergy(), ClumpParticle::getRotationalEnergy(), InfiniteWall::InfiniteWall(), BaseParticle::integrateBeforeForceComputation(), ClumpParticle::integrateBeforeForceComputation(), LawinenBox::printTime(), setDistance(), DPMBase::setMeanVelocityAndKineticEnergy(), Domain::updateParticlePosition(), and PeriodicBoundaryHandler::updateParticles().
getRadialCoordinate()
Mdouble Vec3D::getRadialCoordinate () const
Returns the square of the radial cylindrical coordinate, r=sqrt(x^2+y^2).
 {
     return std::sqrt(X * X + Y * Y);
 }
References sqrt(), X, and Y.
getRadialCoordinateSquared()
Mdouble Vec3D::getRadialCoordinateSquared () const
Returns the square of the radial cylindrical coordinate, r^2=x^2+y^2.
 {
     return X * X + Y * Y;
 }
References X, and Y.
getSphericalCoordinates()
Vec3D Vec3D::getSphericalCoordinates () const
Returns the representation of this Vec3D in spherical coordinates.
Transforms the (Cartesian) vector to spherical coordinates
Returns
Transformed vector
 {
     Vec3D sphericalCoord;
     // Calculate radial distance
     sphericalCoord.X = std::sqrt(X * X + Y * Y + Z * Z);
     // Calculate azimuthal angle (theta)
     sphericalCoord.Y = std::acos(Z / sphericalCoord.X);
     // Calculate polar angle (phi)
     if (X == 0.0)
     {
         if (Y >= 0.0)
         {
             sphericalCoord.Z = constants::pi / 2.0;
         }
         else
         {
             sphericalCoord.Z = -constants::pi / 2.0;
         }
     }
     else
     {
         sphericalCoord.Z = std::atan2(Y, X);
         // Adjust the range to [0, 2*pi)
         if (sphericalCoord.Z < 0.0)
         {
             sphericalCoord.Z += 2.0 * constants::pi;
         }
     }
     return sphericalCoord;
 }
References acos(), atan2(), constants::pi, sqrt(), X, Y, and Z.
Referenced by SphereInsertionBoundary::placeParticle().
getUnitVector()
Vec3D Vec3D::getUnitVector (const Vec3D & a) static
Returns a unit Vec3D based on a.
Calculates the unit vector of a given vector (unless it is a vector with zero length; in that case it returns a 3D vector with each element equal to zero). NB: this is a STATIC function!
Parameters
[in] a the vector of interest
Returns
unit vector in the direction of the argument (unless the argument has length zero; in that case a zero-vector).
 {
     Mdouble Length2 = a.getLengthSquared();
     if (Length2 != 0.0)
         return a / std::sqrt(Length2);
     else
         return Vec3D(0, 0, 0);
 }
References a, sqrt(), and Vec3D().
Referenced by IntersectionOfWalls::createOpenPrism(), IntersectionOfWalls::createPrism(), MindlinInteraction::getTangentialOverlap(), WearableTriangulatedWall::processDebris(), TriangulatedWall::setNormalsAndNeighbours(), CGHandlerSelfTest::setupInitialConditions(), and MindlinInteraction::updateK_t().
getX()
Mdouble Vec3D::getX () const inline
     { return X; }
References X.
Referenced by VolumeCoupling::checkParticlesInFiniteElems(), VolumeCoupling::computeCouplingOnFEM(), SCoupling< M, O >::computeSCouplingForcesFromTriangles(), VolumeCoupling::getProjectionAndProjected(), and BaseCoupling< M, O >::writeEneTimeStep().
getY()
Mdouble Vec3D::getY () const inline
     { return Y; }
References Y.
Referenced by VolumeCoupling::checkParticlesInFiniteElems(), VolumeCoupling::computeCouplingOnFEM(), SCoupling< M, O >::computeSCouplingForcesFromTriangles(), and VolumeCoupling::getProjectionAndProjected().
getZ()
Mdouble Vec3D::getZ () const inline
     { return Z; }
References Z.
Referenced by VolumeCoupling::checkParticlesInFiniteElems(), VolumeCoupling::computeCouplingOnFEM(), SCoupling< M, O >::computeSCouplingForcesFromTriangles(), VolumeCoupling::getProjectionAndProjected(), RollingOverTriangleWalls::setupInitialConditions(), and MercuryProblem::setupInitialConditions().
isEqualTo()
bool Vec3D::isEqualTo (const Vec3D & other, double tol) const
Checks if the length this Vec3D is equal the length of other with a certain tolerance.
Checks if the length of the vector is equal to the one given in the first argument (other), with a tolerance given in the second argument (tol).
Parameters
[in] other the 3D vector to check against
[in] tol the tolerance
Returns
returns TRUE if the difference between the lengths of this vector and that given in the first argument (other) is smaller than the given tolerance.
 {
     if ((Vec3D::getLengthSquared(*this - other)) <= tol * tol)
     {
         return true;
     }
     else
     {
         return false;
     }
 }
References getLengthSquared().
Referenced by STLTriangle::isEqualTo(), and main().
isNaN()
bool Vec3D::isNaN () const
Checks if ALL elements are zero.
Checks if ALL elements are zero
Returns
TRUE if ALL elements are zero
 {
     return std::isnan(X) || std::isnan(Y) || std::isnan(Z);
 }
References isnan, X, Y, and Z.
isZero()
bool Vec3D::isZero () const inline
Checks if ALL elements are zero.
     { return X == 0.0 && Y == 0.0 && Z == 0.0; }
References X, Y, and Z.
Referenced by MeshTriangle::rotate(), TriangleWall::rotate(), ArcWallUnitTest::setupInitialConditions(), and TriangleWall::updateVertexAndNormal().
max() [1/2]
static double Vec3D::max (const Vec3D & a) inline static
Calculates the maximum coordinate of vector a.
 {return std::max(std::max(a.X,a.Y),a.Z);}
References a, and max.
max() [2/2]
Vec3D Vec3D::max (const Vec3D & a, const Vec3D & b) static
Calculates the pointwise maximum of two Vec3D.
Calculates the pointwise maximum of two vectors. NB: this is a STATIC function!
Parameters
[in] a the first vector
[in] b the second vector
Returns
The resulting vector, in which each element is the maximum of the equivalent elements of the arguments
 {
     return Vec3D(std::max(a.X, b.X), std::max(a.Y, b.Y), std::max(a.Z, b.Z));
 }
References a, b, max, and Vec3D().
Referenced by statistics_while_running< T >::auto_set_domain(), FileReader::read(), TriangleMeshWall::updateBoundingBox(), TriangleMeshWall::updateBoundingBoxGlobal(), MeshTriangle::updateVertexAndNormal(), and TriangleWall::updateVertexAndNormal().
min() [1/2]
static double Vec3D::min (const Vec3D & a) inline static
Calculates the minimum coordinate of vector a.
 {return std::min(std::min(a.X,a.Y),a.Z);}
References a, and min.
min() [2/2]
Vec3D Vec3D::min (const Vec3D & a, const Vec3D & b) static
Calculates the pointwise minimum of two Vec3D.
Calculates the pointwise minimum of two vectors. NB: this is a STATIC function!
Parameters
[in] a the first vector
[in] b the second vector
Returns
The resulting vector, in which each element is the minimum of the equivalent elements of the arguments
 {
     return Vec3D(std::min(a.X, b.X), std::min(a.Y, b.Y), std::min(a.Z, b.Z));
 }
References a, b, min, and Vec3D().
Referenced by BaseWall::addParticlesAtWall(), statistics_while_running< T >::auto_set_domain(), FileReader::read(), TriangleMeshWall::updateBoundingBox(), TriangleMeshWall::updateBoundingBoxGlobal(), MeshTriangle::updateVertexAndNormal(), and TriangleWall::updateVertexAndNormal().
multiplyElementwise()
Vec3D Vec3D::multiplyElementwise (const Vec3D & a) const inline
{
         return Vec3D(X*a.X, Y*a.Y, Z*a.Z);
     }
References a, Vec3D(), X, Y, and Z.
Referenced by BaseWall::setForceControl(), and BaseWall::setVelocityControl().
normalise()
void Vec3D::normalise ()
Makes this Vec3D unit length.
Normalises the vector, i.e. divides all elements by the vectors length (resulting in a vector in the same direction, but with unit length).
 {
     Mdouble length2 = this->getLengthSquared();
     if (length2 == 0)
     {
         logger(ERROR, "Normalizing a vector of length 0");
     }
     *this /= std::sqrt(length2);
 }
References ERROR, getLengthSquared(), logger, and sqrt().
Referenced by IntersectionOfWalls::addTetraSTL(), HorizontalScrew::getDistanceAndNormal(), ScrewsymmetricIntersectionOfWalls::getDistanceAndNormal(), SimpleDrumSuperquadrics::getDistanceAndNormal(), Screw::getDistanceAndNormalLabCoordinates(), SimpleDrumSuperquadrics::getDistanceNormalOverlapSuperquadric(), ClumpParticle::rotatePrincipalDirections(), ArcWall::set(), setLength(), HorizontalMixer::setOuterWalls(), HorizontalMixerWalls::setOuterWalls(), UniformRandomPDs(), MeshTriangle::updateVertexAndNormal(), and TriangleWall::updateVertexAndNormal().
operator*()
Vec3D Vec3D::operator* (const Mdouble a) const inline
Multiplies by a scalar.
Multiplies each element with a scalar
Parameters
[in] a the scalar to be multiplied with
Returns
the resulting vector
     {
         return Vec3D(X * a, Y * a, Z * a);
     }
References a, Vec3D(), X, Y, and Z.
operator*=()
Vec3D& Vec3D::operator*= (Mdouble a) inline
Multiplies by a scalar.
Multiplies each element by a scalar
Parameters
[in] a scalar to be multiplied by
Returns
(reference to) itself, i.e. resulting vector
{
         X *= a;
         Y *= a;
         Z *= a;
         return *this;
     }
References a, X, Y, and Z.
operator+()
Vec3D Vec3D::operator+ (const Vec3D & a) const inline
Adds another vector.
Adds vector to itself
Parameters
[in] a vector to be added
Returns
resulting 3D vector
     {
         return Vec3D(X + a.X, Y + a.Y, Z + a.Z);
     }
References a, Vec3D(), X, Y, and Z.
operator+=()
Vec3D& Vec3D::operator+= (const Vec3D & a) inline
Adds another vector.
Adds a vector to itself
Parameters
[in] a vector to be added
Returns
(reference to) itself, i.e. resulting vector
     {
         X += a.X;
         Y += a.Y;
         Z += a.Z;
         return *this;
     }
References a, X, Y, and Z.
operator-()
Vec3D Vec3D::operator- (const Vec3D a) const inline
Binary vector subtraction.
Subtracts a vector from another vector
Parameters
[in] a vector to be subtracted
Returns
resulting vector
     {
         return Vec3D(X - a.X, Y - a.Y, Z - a.Z);
     };
References a, Vec3D(), X, Y, and Z.
operator-=()
Vec3D& Vec3D::operator-= (const Vec3D & a) inline
Subtracts another vector.
Subtracts a vector from itself
Parameters
[in] a vector to be subtracted
Returns
(reference to) itself, i.e. resulting vector
     {
         X -= a.X;
         Y -= a.Y;
         Z -= a.Z;
         return *this;
     }
References a, X, Y, and Z.
operator/()
Vec3D Vec3D::operator/ (Mdouble a) const inline
Divides by a scalar.
Divides each element by a scalar
Parameters
[in] a the scalar to be divided by
Returns
resulting vector
{
         return Vec3D(X / a, Y / a, Z / a);
     }
References a, Vec3D(), X, Y, and Z.
operator/=()
Vec3D& Vec3D::operator/= (const Mdouble a) inline
Divides by a scalar.
Divides each element by a scalar
Parameters
[in] a scalar to be divided by
Returns
(reference to) itself, i.e. resulting vector
     {
         X /= a;
         Y /= a;
         Z /= a;
         return *this;
     }
References a, X, Y, and Z.
operator<()
bool Vec3D::operator< (const Vec3D & a) const inline
{
         return X<a.X && Y<a.Y && Z<a.Z;
     }
References a, X, Y, and Z.
operator==()
bool Vec3D::operator== (const Vec3D & a) const inline
     {
         return X == a.X and Y == a.Y and Z == a.Z;
     };
References a, X, Y, and Z.
operator>=()
bool Vec3D::operator>= (const Vec3D & a) const inline
Checks if all coordinates satisfy this>=a.
{
         return X>=a.X && Y>=a.Y && Z>=a.Z;
     }
References a, X, Y, and Z.
operator[]() [1/2]
Mdouble& Vec3D::operator[] (int index) inline
Implements operator [] to easier access to x, y, z.
     {
         switch (index)
         {
             case 0:
                 return X;
             case 1:
                 return Y;
             case 2:
                 return Z;
             default:
                 throw std::out_of_range("Index out of bounds");
         }
     }
References X, Y, and Z.
operator[]() [2/2]
const Mdouble& Vec3D::operator[] (int index) const inline
Implements static variant of operator [].
     {
         switch (index)
         {
             case 0:
                 return X;
             case 1:
                 return Y;
             case 2:
                 return Z;
             default:
                 throw std::out_of_range("Index out of bounds");
         }
     }
References X, Y, and Z.
set()
void Vec3D::set (Mdouble x, Mdouble y, Mdouble z) inline
     {
         X = x;
         Y = y;
         Z = z;
     }
References X, x(), Y, y(), Z, and z().
setComponent()
void Vec3D::setComponent (int index, double val)
Sets the requested component of this Vec3D to the requested value.
Sets the element of the vector belonging to the first argument (index) to the value given in the second argument (val).
Parameters
[in] index index of element of interest,
[in] val value to be set
 {
     switch (index)
     {
         case 0:
             X = val;
             break;
         case 1:
             Y = val;
             break;
         case 2:
             Z = val;
             break;
         default:
             logger(ERROR, "[Vector::setComponent] Index = %, which is too high for a 3D vector (should be 0-2).",
                    index);
     }
 }
References ERROR, logger, calibrate::val, X, Y, and Z.
Referenced by ScaleCoupling< M, O >::computeCouplingForce(), Panel::createPanels(), Panel::Panel(), and Domain::setBounds().
setLength()
void Vec3D::setLength (Mdouble length)
Make this Vec3D a certain length.
Sets the length of the vector to a given scalar (while maintaining the direction).
Parameters
[in] length the length to be set
 {
     this->normalise();
     *this *= length;
 }
References normalise().
setNaN()
void Vec3D::setNaN ()
Sets all elements to NaN.
Sets each element to zero.
 {
     X = constants::NaN;
     Y = constants::NaN;
     Z = constants::NaN;
 }
References constants::NaN, X, Y, and Z.
Referenced by BaseInteraction::BaseInteraction().
setX()
void Vec3D::setX (Mdouble x) inline
     { X = x; }
References X, and x().
Referenced by SCoupling< M, O >::createDPMWallsFromFiniteElems().
setY()
void Vec3D::setY (Mdouble y) inline
     { Y = y; }
References Y, and y().
Referenced by SCoupling< M, O >::createDPMWallsFromFiniteElems().
setZ()
void Vec3D::setZ (Mdouble z) inline
     { Z = z; }
References Z, and z().
Referenced by SCoupling< M, O >::createDPMWallsFromFiniteElems().
setZero()
void Vec3D::setZero ()
Sets all elements to zero.
Sets each element to zero.
 {
     X = 0.0;
     Y = 0.0;
     Z = 0.0;
 }
References X, Y, and Z.
Referenced by BaseInteractable::BaseInteractable(), BaseInteraction::BaseInteraction(), Coil::Coil(), ChuteWithPeriodicInflow::computeInternalForces(), CylinderInsertionBoundary::CylinderInsertionBoundary(), FrictionInteraction::FrictionInteraction(), HorizontalScrew::HorizontalScrew(), BaseCluster::makeDataAnalysis(), MindlinInteraction::MindlinInteraction(), MindlinRollingTorsionInteraction::MindlinRollingTorsionInteraction(), BaseInteractable::resetForceTorque(), Screw::Screw(), CGFields::DisplacementField::setZero(), CGFields::GradVelocityField::setZero(), CGFields::StandardFields::setZero(), SlidingFrictionInteraction::SlidingFrictionInteraction(), SphereInsertionBoundary::SphereInsertionBoundary(), StatisticsPoint< T >::StatisticsPoint(), testCGHandler(), and Vec3D().
signedSquare()
Vec3D Vec3D::signedSquare () const inline
{
         return Vec3D(fabs(X)*X, fabs(Y)*Y, fabs(Z)*Z);
     }
References boost::multiprecision::fabs(), Vec3D(), X, Y, and Z.
sqrt()
Vec3D Vec3D::sqrt (const Vec3D & a) static
Calculates the pointwise square root of a Vec3D.
Calculates the pointwise square root of a given vector. NB: this is a STATIC function!
Parameters
[in] a the vector to be pointwise square rooted
Returns
the resulting vector, of which each element is the square root of the equivalent element of the argument.
 {
     return Vec3D(std::sqrt(a.X), std::sqrt(a.Y), std::sqrt(a.Z));
 }
References a, sqrt(), and Vec3D().
square()
Vec3D Vec3D::square (const Vec3D & a) static
Calculates the pointwise square of a Vec3D.
Calculates the pointwise square of the vector. NB: this is a STATIC function!
Parameters
[in] a the vector to be squared.
Returns
the resulting vector, of which each element is the square of the equivalent element of the argument.
 {
     return Vec3D(a.X * a.X, a.Y * a.Y, a.Z * a.Z);
 }
References a, and Vec3D().
Referenced by CGFields::DisplacementField::getSquared(), CGFields::GradVelocityField::getSquared(), and CGFields::StandardFields::getSquared().
x() [1/2]
Mdouble& Vec3D::x () inline
RW reference to X.
     { return X; }
References X.
Referenced by DPMBase::getXMax(), DPMBase::getXMin(), DPMBase::read(), DPMBase::readNextDataFile(), DPMBase::readOld(), WallHandler::readTriangleWall(), set(), DPMBase::setMax(), DPMBase::setMin(), setX(), DPMBase::setXMax(), DPMBase::setXMin(), and Vec3D().
x() [2/2]
Mdouble Vec3D::x () const inline
RO reference to X.
     { return X; }
References X.
y() [1/2]
Mdouble& Vec3D::y () inline
RW reference to Y.
     { return Y; }
References Y.
Referenced by DPMBase::getYMax(), DPMBase::getYMin(), DPMBase::read(), DPMBase::readNextDataFile(), DPMBase::readOld(), WallHandler::readTriangleWall(), set(), DPMBase::setMax(), DPMBase::setMin(), setY(), DPMBase::setYMax(), DPMBase::setYMin(), and Vec3D().
y() [2/2]
Mdouble Vec3D::y () const inline
RO reference to Y.
     { return Y; }
References Y.
z() [1/2]
Mdouble& Vec3D::z () inline
RW reference to Z.
     { return Z; }
References Z.
Referenced by DPMBase::getZMax(), DPMBase::getZMin(), DPMBase::read(), DPMBase::readNextDataFile(), DPMBase::readOld(), WallHandler::readTriangleWall(), set(), DPMBase::setMax(), DPMBase::setMin(), setZ(), DPMBase::setZMax(), DPMBase::setZMin(), and Vec3D().
z() [2/2]
Mdouble Vec3D::z () const inline
RO reference to Z.
     { return Z; }
References Z.
Friends And Related Function Documentation
operator*
Vec3D operator* (Mdouble a, const Vec3D & b) friend
Multiplies all elements by a scalar.
Multiplies each element of a given vector (b) by a given scalar (a). NB: this is a global function and a friend of the Vec3D class. Gets called when a scalar multiplication of the form (Mdouble) * (Vec3D) is performed.
Parameters
[in] a the scalar
[in] b the vector
Returns
the resulting vector
{
         return Vec3D(b.X * a, b.Y * a, b.Z * a);
     }
operator-
Vec3D operator- (const Vec3D & a) friend
Reverts the direction of a vector.
{
         return Vec3D(-a.X, -a.Y, -a.Z);
     }
operator<<
std::ostream& operator<< (std::ostream & os, const Vec3D & a) friend
Adds elements to an output stream.
Adds all elements of the vector to an output stream. NB: this is a global function and a friend of the Vec3D class!
Parameters
[in] os the output stream,
[in] a The vector of interest
Returns
the output stream with vector elements added
 {
     os << a.X << ' ' << a.Y << ' ' << a.Z;
     return os;
 }
operator>>
std::istream& operator>> (std::istream & is, Vec3D & a) friend
Adds elements to an input stream.
Reads all elements of a given vector from an input stream. NB: this is a global function and a friend of the Vec3D class!
Parameters
[in,out] is the input stream
[in,out] a the vector to be read in
Returns
the input stream from which the vector elements were read
 {
     is >> a.X;
     is >> a.Y;
     is >> a.Z;
     //TW: clearing the stream avoids the nasty problem on ARM processors that the failbit is set to true if numbers below DBL_MIN=1e-308 are read.
     #if defined(__arm__) || defined(__aarch64__)
         if (is.fail()) {
             if (fabs(a.X)<std::numeric_limits<Mdouble>::min() or fabs(a.Y)<std::numeric_limits<Mdouble>::min() or fabs(a.Z)<std::numeric_limits<Mdouble>::min()) {
                 logger(VERBOSE, "Read in subnormal number %", a);
                 is.clear();
             }
         }
     #endif
     return is;
 }
Member Data Documentation
X
Mdouble Vec3D::X
the vector components
Referenced by ScaleCoupledBeam::actionsAfterSolve(), HertzianBSHPInteractionTwoParticleElasticCollision::actionsAfterSolve(), SphericalSuperQuadricCollision::actionsAfterSolve(), SpeciesTest::actionsAfterSolve(), T_protectiveWall::actionsAfterTimeStep(), ChangingTOIParticle::actionsAfterTimeStep(), SingleParticleSegregation::actionsAfterTimeStep(), ContactDetectionNormalSpheresTest::actionsAfterTimeStep(), ContactDetectionRotatedSpheresTest::actionsAfterTimeStep(), protectiveWall::actionsAfterTimeStep(), DrivenParticleClass::actionsAfterTimeStep(), LawinenBox::actionsBeforeTimeStep(), SmoothChute::actionsBeforeTimeStep(), AngleOfRepose::actionsBeforeTimeStep(), Chutebelt::actionsBeforeTimeStep(), StressStrainControlBoundary::activateStrainRateControl(), NautaMixer::addBaseWall(), NautaMixer::addConeWall(), ChuteWithHopper::addHopper(), NautaMixer::addParticlesAtWall(), BaseWall::addParticlesAtWall(), ClumpParticle::angularAccelerateClumpIterative(), statistics_while_running< T >::auto_set_domain(), HeaterBoundary::checkBoundaryAfterParticleMoved(), ChuteWithContraction::ChuteWithContraction(), ChuteWithPeriodicInflow::cleanChute(), ChuteWithContraction::cleanChute(), Chute::cleanChute(), ScrewsymmetricIntersectionOfWalls::computeDeltaZ(), SuperQuadricParticle::computeHessianLabFixed(), Mercury2D::computeInternalForces(), Mercury3D::computeInternalForces(), ChuteWithPeriodicInflow::computeInternalForces(), BaseCluster::computeInternalStructure(), SuperQuadricParticle::computeMass(), ScrewsymmetricIntersectionOfWalls::computeNormalRadialDeltaN(), SuperQuadricParticle::computeResidualContactDetection(), SuperQuadricParticle::computeShape(), SuperQuadricParticle::computeShapeGradientLabFixed(), AxisymmetricIntersectionOfWalls::convertLimits(), ScrewsymmetricIntersectionOfWalls::convertLimits(), Funnel::create_funnel(), LawinenBox::create_inflow_particle(), Funnel::create_inflow_particle(), FlowRule::create_inflow_particle(), SilbertPeriodic::create_inflow_particle(), Chute::createBottom(), divideElementwise(), ChuteWithWedge::extendBottom(), SubcriticalMaserBoundaryTEST::extendBottom(), MembraneDemo::fixMembraneEdges(), Quaternion::fromAxisAndAngle(), BidisperseCubeInsertionBoundary::generateParticle(), BaseWall::getAxis(), getComponent(), SuperQuadricParticle::getContactPointPlanB(), getCylindricalCoordinates(), getCylindricalTensorField(), BaseParticle::getDisplacement2(), HeaterBoundary::getDistance(), CubeDeletionBoundary::getDistance(), HorizontalScrew::getDistanceAndNormal(), ScrewsymmetricIntersectionOfWalls::getDistanceAndNormal(), BasicIntersectionOfWalls::getDistanceAndNormal(), Coil::getDistanceAndNormal(), CylindricalWall::getDistanceAndNormal(), InfiniteWallWithHole::getDistanceAndNormal(), SineWall::getDistanceAndNormal(), VChute::getDistanceAndNormal(), LevelSetWall::getDistanceAndNormalLabCoordinates(), Screw::getDistanceAndNormalLabCoordinates(), getDistanceSquared(), getFromCylindricalCoordinates(), InfiniteWall::getFurthestPointSuperQuadric(), InfiniteWallWithHole::getHoleDistance(), SuperQuadricParticle::getInitialGuessForContact(), SuperQuadricParticle::getInteractionWithSuperQuad(), SuperQuadricParticle::getJacobianOfContactDetectionObjective(), getLengthSquared(), ParticleHandler::getMassTimesPosition(), getMPISum(), DomainHandler::getParticleDomainGlobalIndex(), getRadialCoordinate(), getRadialCoordinateSquared(), ParticleParticleCollision::getRelativeVelocityComponents(), WallParticleCollision::getRelativeVelocityComponents(), getSphericalCoordinates(), CGExactOverlapUnitTest::getVolume(), HeaterBoundary::getVolume(), SuperQuadricParticle::getVolume(), CGCoordinates::O::getVolumeOfAveragedDimensions(), WearableNurbsWall::getVolumeUnderSurface(), WearableNurbsWall::getVolumeUnderSurfaceX(), getX(), DPMBase::getXCenter(), Mercury2D::hGridFindParticleContacts(), Mercury3D::hGridFindParticleContacts(), Mercury2D::hGridGetInteractingParticleList(), Mercury3D::hGridGetInteractingParticleList(), Mercury2D::hGridHasParticleContacts(), Mercury3D::hGridHasParticleContacts(), Mercury2D::hGridUpdateParticle(), Mercury3D::hGridUpdateParticle(), MarbleRun::includeInDomain(), InitialConditions< SpeciesType >::InitialConditions(), ContactDetectionIntersectionOfWallsTest::introduceParticlesAtWall(), SuperQuadricParticle::isInContactWith(), isNaN(), isZero(), LawinenBox::LawinenBox(), LeesEdwardsSelfTest::LeesEdwardsSelfTest(), load(), main(), multiplyElementwise(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator<(), operator==(), operator>=(), operator[](), ChuteWithPeriodicInflow::outputXBallsDataParticlee(), SuperQuadricParticle::overlapFromContactPoint(), BaseCluster::particleInsertionSuccessful(), FixedClusterInsertionBoundary::placeParticle(), ChuteInsertionBoundary::placeParticle(), CubeInsertionBoundary::placeParticle(), CylinderInsertionBoundary::placeParticle(), PolydisperseInsertionBoundary::placeParticle(), RandomClusterInsertionBoundary::placeParticle(), SphereInsertionBoundary::placeParticle(), ChuteWithPeriodicInflow::printTime(), RotatingDrumWet::printTime(), ForceLawsMPI2Test::printTime(), BaseCluster::printTime(), DPMBase::readNextDataFile(), save(), set(), SuperQuadricParticle::setBoundingRadius(), setComponent(), CGFields::OrientationField::setFields(), BaseCG::setHX(), SuperQuadricParticle::setInertia(), setNaN(), Quaternion::setOrientationViaNormal(), Domain::setRange(), HeaterBoundary::setStrength2D(), HeaterBoundary::setStrength3D(), ClosedCSCWalls::setupInitialConditions(), CSCInit::setupInitialConditions(), CSCWalls::setupInitialConditions(), MercuryLogo::setupInitialConditions(), SmoothChute::setupInitialConditions(), HourGlass::setupInitialConditions(), MinimalExampleDrum::setupInitialConditions(), TimeDependentPeriodicBoundary3DSelfTest::setupInitialConditions(), AngleOfRepose::setupInitialConditions(), GetDistanceAndNormalForIntersectionOfWalls::setupInitialConditions(), GetDistanceAndNormalForScrew::setupInitialConditions(), GetDistanceAndNormalForTriangleWall::setupInitialConditions(), ParticleCreation::setupInitialConditions(), my_problem_HGRID::setupInitialConditions(), GetDistanceAndNormalForTriangleWalls::setupInitialConditions(), DrumRot::setupInitialConditions(), RotatingDrum::setupInitialConditions(), EllipticalSuperQuadricCollision::setupInitialConditions(), Tutorial11::setupInitialConditions(), ArcWallUnitTest::setupInitialConditions(), MD_demo::setupInitialConditions(), ChuteBottom::setupInitialConditions(), BaseCG::setX(), setX(), setZero(), signedSquare(), FlowFrontChute::stretch(), ContactDetectionNormalSpheresTest::test(), Packing::test(), HertzContactRestitutionUnitTest::test(), UniformRandomPDs(), ScaleCoupling< M, O >::updateCoupledElements(), StressStrainControlBoundary::updateDomainSize(), PeriodicBoundaryHandler::updateMaserParticle(), Vec3D(), SuperQuadricParticle::writeDebugMessageStep2(), SuperQuadricParticle::writeDebugMessageStep3(), DPMBase::writeEneTimeStep(), LawinenBox::writeEneTimeStep(), Drum::writeEneTimeStep(), Slide::writeEneTimeStep(), BaseCoupling< M, O >::writeEneTimeStep(), GranuDrum::writeResults(), RotatingDrumBidisperse::writeResults(), BaseCluster::writeToCdatFile(), HorizontalScrew::writeVTK(), Screw::writeVTK(), and x().
Y
Mdouble Vec3D::Y
Referenced by ChangingTOIParticle::actionsAfterTimeStep(), SingleParticleSegregation::actionsAfterTimeStep(), ContactDetectionNormalSpheresTest::actionsAfterTimeStep(), ContactDetectionRotatedSpheresTest::actionsAfterTimeStep(), DrivenParticleClass::actionsAfterTimeStep(), SmoothChute::actionsBeforeTimeStep(), AngleOfRepose::actionsBeforeTimeStep(), Slide::actionsBeforeTimeStep(), StressStrainControlBoundary::activateStrainRateControl(), NautaMixer::addParticlesAtWall(), BaseWall::addParticlesAtWall(), ClumpParticle::angularAccelerateClumpIterative(), statistics_while_running< T >::auto_set_domain(), HeaterBoundary::checkBoundaryAfterParticleMoved(), ScrewsymmetricIntersectionOfWalls::computeDeltaZ(), SuperQuadricParticle::computeHessianLabFixed(), Mercury2D::computeInternalForces(), Mercury3D::computeInternalForces(), BaseCluster::computeInternalStructure(), SuperQuadricParticle::computeMass(), ScrewsymmetricIntersectionOfWalls::computeNormalRadialDeltaN(), SuperQuadricParticle::computeResidualContactDetection(), SuperQuadricParticle::computeShape(), SuperQuadricParticle::computeShapeGradientLabFixed(), AxisymmetricIntersectionOfWalls::convertLimits(), ScrewsymmetricIntersectionOfWalls::convertLimits(), Funnel::create_funnel(), LawinenBox::create_inflow_particle(), Funnel::create_inflow_particle(), FlowRule::create_inflow_particle(), SilbertPeriodic::create_inflow_particle(), Chute::createBottom(), divideElementwise(), SubcriticalMaserBoundaryTEST::extendBottom(), MembraneDemo::fixMembraneEdges(), MembraneSelfTest::fixMembraneEdges(), Quaternion::fromAxisAndAngle(), BidisperseCubeInsertionBoundary::generateParticle(), BaseWall::getAxis(), getComponent(), SuperQuadricParticle::getContactPointPlanB(), getCylindricalCoordinates(), getCylindricalTensorField(), BaseParticle::getDisplacement2(), HeaterBoundary::getDistance(), CubeDeletionBoundary::getDistance(), HorizontalScrew::getDistanceAndNormal(), ScrewsymmetricIntersectionOfWalls::getDistanceAndNormal(), BasicIntersectionOfWalls::getDistanceAndNormal(), Coil::getDistanceAndNormal(), CylindricalWall::getDistanceAndNormal(), InfiniteWallWithHole::getDistanceAndNormal(), SimpleDrumSuperquadrics::getDistanceAndNormal(), SineWall::getDistanceAndNormal(), VChute::getDistanceAndNormal(), LevelSetWall::getDistanceAndNormalLabCoordinates(), Screw::getDistanceAndNormalLabCoordinates(), SimpleDrumSuperquadrics::getDistanceNormalOverlapSuperquadric(), getDistanceSquared(), getFromCylindricalCoordinates(), InfiniteWall::getFurthestPointSuperQuadric(), InfiniteWallWithHole::getHoleDistance(), SuperQuadricParticle::getInitialGuessForContact(), SuperQuadricParticle::getInteractionWithSuperQuad(), SuperQuadricParticle::getJacobianOfContactDetectionObjective(), getLengthSquared(), ParticleHandler::getMassTimesPosition(), getMPISum(), DomainHandler::getParticleDomainGlobalIndex(), getRadialCoordinate(), getRadialCoordinateSquared(), ParticleParticleCollision::getRelativeVelocityComponents(), WallParticleCollision::getRelativeVelocityComponents(), getSphericalCoordinates(), CGExactOverlapUnitTest::getVolume(), HeaterBoundary::getVolume(), SuperQuadricParticle::getVolume(), CGCoordinates::O::getVolumeOfAveragedDimensions(), WearableNurbsWall::getVolumeUnderSurface(), WearableNurbsWall::getVolumeUnderSurfaceX(), getY(), DPMBase::getYCenter(), Mercury2D::hGridFindParticleContacts(), Mercury3D::hGridFindParticleContacts(), Mercury2D::hGridGetInteractingParticleList(), Mercury3D::hGridGetInteractingParticleList(), Mercury2D::hGridHasParticleContacts(), Mercury3D::hGridHasParticleContacts(), Mercury2D::hGridUpdateParticle(), Mercury3D::hGridUpdateParticle(), MarbleRun::includeInDomain(), InitialConditions< SpeciesType >::InitialConditions(), ContactDetectionIntersectionOfWallsTest::introduceParticlesAtWall(), SuperQuadricParticle::isInContactWith(), isNaN(), isZero(), LawinenBox::LawinenBox(), LeesEdwardsSelfTest::LeesEdwardsSelfTest(), load(), main(), multiplyElementwise(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator<(), operator==(), operator>=(), operator[](), ChuteWithPeriodicInflow::outputXBallsDataParticlee(), SuperQuadricParticle::overlapFromContactPoint(), BaseCluster::particleInsertionSuccessful(), FixedClusterInsertionBoundary::placeParticle(), ChuteInsertionBoundary::placeParticle(), CubeInsertionBoundary::placeParticle(), CylinderInsertionBoundary::placeParticle(), PolydisperseInsertionBoundary::placeParticle(), RandomClusterInsertionBoundary::placeParticle(), SphereInsertionBoundary::placeParticle(), BaseCluster::printTime(), DPMBase::readNextDataFile(), save(), set(), SuperQuadricParticle::setBoundingRadius(), setComponent(), CGFields::OrientationField::setFields(), BaseCG::setHY(), SuperQuadricParticle::setInertia(), setNaN(), Quaternion::setOrientationViaNormal(), Domain::setRange(), HeaterBoundary::setStrength2D(), HeaterBoundary::setStrength3D(), ClosedCSCWalls::setupInitialConditions(), CSCInit::setupInitialConditions(), CSCWalls::setupInitialConditions(), MercuryLogo::setupInitialConditions(), SmoothChute::setupInitialConditions(), HourGlass::setupInitialConditions(), MinimalExampleDrum::setupInitialConditions(), TimeDependentPeriodicBoundary3DSelfTest::setupInitialConditions(), AngleOfRepose::setupInitialConditions(), ParticleCreation::setupInitialConditions(), my_problem_HGRID::setupInitialConditions(), RotatingDrum::setupInitialConditions(), EllipticalSuperQuadricCollision::setupInitialConditions(), Tutorial11::setupInitialConditions(), ArcWallUnitTest::setupInitialConditions(), MD_demo::setupInitialConditions(), ChuteBottom::setupInitialConditions(), BaseCG::setY(), setY(), setZero(), signedSquare(), Packing::test(), UniformRandomPDs(), ScaleCoupling< M, O >::updateCoupledElements(), StressStrainControlBoundary::updateDomainSize(), Vec3D(), SuperQuadricParticle::writeDebugMessageStep2(), SuperQuadricParticle::writeDebugMessageStep3(), DPMBase::writeEneTimeStep(), Slide::writeEneTimeStep(), BaseCoupling< M, O >::writeEneTimeStep(), BaseCluster::writeToCdatFile(), HorizontalScrew::writeVTK(), Screw::writeVTK(), and y().
Z
Mdouble Vec3D::Z
Referenced by GranuHeap::actionsAfterTimeStep(), ClosedCSCRestart::actionsAfterTimeStep(), ClosedCSCRun::actionsAfterTimeStep(), ClosedCSCWalls::actionsAfterTimeStep(), ChangingTOIParticle::actionsAfterTimeStep(), MarbleRun::actionsAfterTimeStep(), BouncingSuperQuadric::actionsAfterTimeStep(), ContactDetectionNormalSpheresTest::actionsAfterTimeStep(), ContactDetectionRotatedSpheresTest::actionsAfterTimeStep(), DrivenParticleClass::actionsAfterTimeStep(), LawinenBox::actionsBeforeTimeStep(), SmoothChute::actionsBeforeTimeStep(), StressStrainControlBoundary::activateStrainRateControl(), NautaMixer::addBaseWall(), NautaMixer::addConeWall(), ChuteWithHopper::addHopper(), NautaMixer::addParticlesAtWall(), BaseWall::addParticlesAtWall(), ClumpParticle::angularAccelerateClumpIterative(), statistics_while_running< T >::auto_set_domain(), statistics_while_running< T >::auto_set_z(), HeaterBoundary::checkBoundaryAfterParticleMoved(), Funnel::cleanChute(), ScrewsymmetricIntersectionOfWalls::computeDeltaZ(), SuperQuadricParticle::computeHessianLabFixed(), Mercury3D::computeInternalForces(), BaseCluster::computeInternalStructure(), SuperQuadricParticle::computeMass(), ScrewsymmetricIntersectionOfWalls::computeNormalRadialDeltaN(), SuperQuadricParticle::computeResidualContactDetection(), SuperQuadricParticle::computeShape(), SuperQuadricParticle::computeShapeGradientLabFixed(), ClosedCSCWalls::continueSolve(), AxisymmetricIntersectionOfWalls::convertLimits(), ScrewsymmetricIntersectionOfWalls::convertLimits(), Funnel::create_funnel(), LawinenBox::create_inflow_particle(), Funnel::create_inflow_particle(), FlowRule::create_inflow_particle(), SilbertPeriodic::create_inflow_particle(), divideElementwise(), SubcriticalMaserBoundaryTEST::extendBottom(), Quaternion::fromAxisAndAngle(), BidisperseCubeInsertionBoundary::generateParticle(), BaseWall::getAxis(), getComponent(), SuperQuadricParticle::getContactPointPlanB(), getCylindricalCoordinates(), getCylindricalTensorField(), BaseParticle::getDisplacement2(), HeaterBoundary::getDistance(), CubeDeletionBoundary::getDistance(), HorizontalBaseScrew::getDistanceAndNormal(), HorizontalScrew::getDistanceAndNormal(), ScrewsymmetricIntersectionOfWalls::getDistanceAndNormal(), BasicIntersectionOfWalls::getDistanceAndNormal(), Coil::getDistanceAndNormal(), CylindricalWall::getDistanceAndNormal(), InfiniteWallWithHole::getDistanceAndNormal(), SineWall::getDistanceAndNormal(), VChute::getDistanceAndNormal(), LevelSetWall::getDistanceAndNormalLabCoordinates(), Screw::getDistanceAndNormalLabCoordinates(), getDistanceSquared(), SphericalIndenter::getForceOnIndenter(), getFromCylindricalCoordinates(), InfiniteWall::getFurthestPointSuperQuadric(), SphericalIndenter::getIndenterHeight(), SphericalIndenter::getIndenterVelocity(), SuperQuadricParticle::getInitialGuessForContact(), SuperQuadricParticle::getInteractionWithSuperQuad(), SuperQuadricParticle::getJacobianOfContactDetectionObjective(), getLengthSquared(), ParticleHandler::getMassTimesPosition(), getMPISum(), DomainHandler::getParticleDomainGlobalIndex(), getSphericalCoordinates(), CGExactOverlapUnitTest::getVolume(), HeaterBoundary::getVolume(), SuperQuadricParticle::getVolume(), CGCoordinates::O::getVolumeOfAveragedDimensions(), WearableNurbsWall::getVolumeUnderSurface(), WearableNurbsWall::getVolumeUnderSurfaceX(), getZ(), DPMBase::getZCenter(), Mercury3D::hGridFindParticleContacts(), Mercury3D::hGridGetInteractingParticleList(), Mercury3D::hGridHasParticleContacts(), Mercury3D::hGridUpdateParticle(), MarbleRun::includeInDomain(), InitialConditions< SpeciesType >::InitialConditions(), ContactDetectionIntersectionOfWallsTest::introduceParticlesAtWall(), SuperQuadricParticle::isInContactWith(), isNaN(), isZero(), load(), main(), multiplyElementwise(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator<(), operator==(), operator>=(), operator[](), ChuteWithPeriodicInflow::outputXBallsDataParticlee(), SuperQuadricParticle::overlapFromContactPoint(), BaseCluster::particleInsertionSuccessful(), FixedClusterInsertionBoundary::placeParticle(), ChuteInsertionBoundary::placeParticle(), CubeInsertionBoundary::placeParticle(), CylinderInsertionBoundary::placeParticle(), PolydisperseInsertionBoundary::placeParticle(), RandomClusterInsertionBoundary::placeParticle(), SphereInsertionBoundary::placeParticle(), ClosedCSCRestart::printTime(), ClosedCSCRun::printTime(), ClosedCSCWalls::printTime(), RotatingDrumWet::printTime(), CubeDeletionBoundarySelfTest::printTime(), DeletionBoundarySelfTest::printTime(), BaseCluster::printTime(), DPMBase::readNextDataFile(), save(), ClosedCSCWalls::saveWalls(), set(), SuperQuadricParticle::setBoundingRadius(), setComponent(), CGFields::OrientationField::setFields(), BaseCG::setHZ(), SuperQuadricParticle::setInertia(), setNaN(), Quaternion::setOrientationViaNormal(), Domain::setRange(), HeaterBoundary::setStrength2D(), HeaterBoundary::setStrength3D(), ClosedCSCWalls::setupInitialConditions(), CSCInit::setupInitialConditions(), CSCWalls::setupInitialConditions(), MercuryLogo::setupInitialConditions(), SmoothChute::setupInitialConditions(), HourGlass::setupInitialConditions(), MinimalExampleDrum::setupInitialConditions(), TimeDependentPeriodicBoundary3DSelfTest::setupInitialConditions(), GetDistanceAndNormalForIntersectionOfWalls::setupInitialConditions(), GetDistanceAndNormalForScrew::setupInitialConditions(), GetDistanceAndNormalForTriangleWall::setupInitialConditions(), ParticleCreation::setupInitialConditions(), GetDistanceAndNormalForTriangleWalls::setupInitialConditions(), DrumRot::setupInitialConditions(), RotatingDrum::setupInitialConditions(), InitialConditions< SpeciesType >::setupInitialConditions(), EllipticalSuperQuadricCollision::setupInitialConditions(), Tutorial11::setupInitialConditions(), MD_demo::setupInitialConditions(), ChuteBottom::setupInitialConditions(), BaseCG::setZ(), setZ(), setZero(), signedSquare(), Packing::test(), UniformRandomPDs(), ScaleCoupling< M, O >::updateCoupledElements(), StressStrainControlBoundary::updateDomainSize(), Vec3D(), SuperQuadricParticle::writeDebugMessageStep2(), SuperQuadricParticle::writeDebugMessageStep3(), DPMBase::writeEneTimeStep(), LawinenBox::writeEneTimeStep(), Drum::writeEneTimeStep(), Penetration::writeEneTimeStep(), SingleParticle< SpeciesType >::writeEneTimeStep(), BaseCoupling< M, O >::writeEneTimeStep(), GranuDrum::writeResults(), RotatingDrumBidisperse::writeResults(), BaseCluster::writeToCdatFile(), AxisymmetricIntersectionOfWalls::writeVTK(), HorizontalBaseScrew::writeVTK(), HorizontalScrew::writeVTK(), Screw::writeVTK(), and z().
The documentation for this class was generated from the following files:
Kernel/Math/Vector.h
Vector.cc