MercuryDPM: Eigen::TensorEvaluator< TensorSlicingOp< StartIndices, Sizes, ArgType >, Device > Struct Template Reference
Eigen::TensorEvaluator< TensorSlicingOp< StartIndices, Sizes, ArgType >, Device > Struct Template Reference
#include <TensorMorphing.h>
Public Types
enum {
IsAligned = false , PacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess , BlockAccess = TensorEvaluator<ArgType, Device>::BlockAccess , PreferBlockAccess = true ,
CoordAccess = false , RawAccess = (NumDims == 1) & TensorEvaluator<ArgType, Device>::RawAccess
}
typedef TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device > Base
typedef TensorSlicingOp< StartIndices, Sizes, ArgType > XprType
typedef XprType::Index Index
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef Sizes Dimensions
typedef std::remove_const_t< Scalar > ScalarNoConst
typedef internal::TensorBlockDescriptor< NumDims, Index > TensorBlockDesc
typedef internal::TensorBlockScratchAllocator< Device > TensorBlockScratch
Public Types inherited from Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >
enum {
IsAligned = false , PacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess , BlockAccess , PreferBlockAccess = true ,
CoordAccess = false , RawAccess = false
}
typedef TensorSlicingOp< StartIndices, Sizes, ArgType > XprType
typedef XprType::Index Index
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef Sizes Dimensions
typedef StorageMemory< CoeffReturnType, Device > Storage
typedef StorageMemory< std::remove_const_t< CoeffReturnType >, Device > ConstCastStorage
typedef Storage::Type EvaluatorPointerType
typedef std::remove_const_t< Scalar > ScalarNoConst
typedef internal::TensorBlockDescriptor< NumDims, Index > TensorBlockDesc
typedef internal::TensorBlockScratchAllocator< Device > TensorBlockScratch
typedef TensorEvaluator< const ArgType, Device >::TensorBlock TensorBlock
Public Member Functions
EIGEN_STRONG_INLINE TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType & coeffRef (Index index) const
template<int StoreMode>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void writePacket (Index index, const PacketReturnType &x) const
template<typename TensorBlock >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void writeBlock (const TensorBlockDesc &desc, const TensorBlock &block)
Public Member Functions inherited from Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >
EIGEN_STRONG_INLINE TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions & dimensions () const
EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (EvaluatorPointerType data)
EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType packet (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::TensorBlockResourceRequirements getResourceRequirements () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorBlock block (TensorBlockDesc &desc, TensorBlockScratch &scratch, bool=false) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Storage::Type data () const
Static Public Attributes
static constexpr int NumDims = internal::array_size<Sizes>::value
static constexpr int Layout = TensorEvaluator<ArgType, Device>::Layout
Static Public Attributes inherited from Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >
static constexpr int NumDims = internal::array_size<Sizes>::value
static constexpr int Layout = TensorEvaluator<ArgType, Device>::Layout
Additional Inherited Members
Protected Member Functions inherited from Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index srcCoeff (Index index) const
Protected Attributes inherited from Eigen::TensorEvaluator< const TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >
array< Index, NumDims > m_outputStrides
array< internal::TensorIntDivisor< Index >, NumDims > m_fastOutputStrides
array< Index, NumDims > m_inputStrides
TensorEvaluator< ArgType, Device > m_impl
const Device EIGEN_DEVICE_REF m_device
Dimensions m_dimensions
bool m_is_identity
const StartIndices m_offsets
Member Typedef Documentation
Base
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > typedef TensorEvaluator<const TensorSlicingOp<StartIndices, Sizes, ArgType>, Device> Eigen::TensorEvaluator< TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::Base
CoeffReturnType
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > typedef XprType::CoeffReturnType Eigen::TensorEvaluator< TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::CoeffReturnType
Dimensions
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > typedef Sizes Eigen::TensorEvaluator< TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::Dimensions
Index
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > typedef XprType::Index Eigen::TensorEvaluator< TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::Index
PacketReturnType
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorEvaluator< TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::PacketReturnType
Scalar
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > typedef XprType::Scalar Eigen::TensorEvaluator< TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::Scalar
ScalarNoConst
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > typedef std::remove_const_t<Scalar> Eigen::TensorEvaluator< TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::ScalarNoConst
TensorBlockDesc
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > typedef internal::TensorBlockDescriptor<NumDims, Index> Eigen::TensorEvaluator< TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::TensorBlockDesc
TensorBlockScratch
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > typedef internal::TensorBlockScratchAllocator<Device> Eigen::TensorEvaluator< TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::TensorBlockScratch
XprType
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > typedef TensorSlicingOp<StartIndices, Sizes, ArgType> Eigen::TensorEvaluator< TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::XprType
Member Enumeration Documentation
anonymous enum
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
BlockAccess
PreferBlockAccess
CoordAccess
RawAccess
        {
     IsAligned = false,
     PacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess,
     BlockAccess = TensorEvaluator<ArgType, Device>::BlockAccess,
     PreferBlockAccess = true,
     CoordAccess = false,
     RawAccess = (NumDims == 1) & TensorEvaluator<ArgType, Device>::RawAccess
   };
Constructor & Destructor Documentation
TensorEvaluator()
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > EIGEN_STRONG_INLINE Eigen::TensorEvaluator< TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::TensorEvaluator (const XprType & op, const Device & device) inline
 : Base(op, device) {}
Member Function Documentation
coeffRef()
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType& Eigen::TensorEvaluator< TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::coeffRef (Index index) const inline
{
     if (this->m_is_identity) {
       return this->m_impl.coeffRef(index);
     } else {
       return this->m_impl.coeffRef(this->srcCoeff(index));
     }
   }
writeBlock()
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > template<typename TensorBlock > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::writeBlock (const TensorBlockDesc & desc, const TensorBlock & block) inline
{
     TensorBlockDesc arg_desc = desc.WithOffset(this->srcCoeff(desc.offset()));
     this->m_impl.writeBlock(arg_desc, block);
   }
References Eigen::TensorEvaluator< Derived, Device >::block(), Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::offset(), and Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::WithOffset().
writePacket()
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > template<int StoreMode> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::writePacket (Index index, const PacketReturnType & x) const inline
{
     if (this->m_is_identity) {
       this->m_impl.template writePacket<StoreMode>(index, x);
       return;
     }
     const int packetSize = PacketType<CoeffReturnType, Device>::size;
     Index inputIndices[] = {0, 0};
     Index indices[] = {index, index + packetSize - 1};
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       EIGEN_UNROLL_LOOP
       for (int i = NumDims - 1; i > 0; --i) {
         const Index idx0 = indices[0] / this->m_fastOutputStrides[i];
         const Index idx1 = indices[1] / this->m_fastOutputStrides[i];
         inputIndices[0] += (idx0 + this->m_offsets[i]) * this->m_inputStrides[i];
         inputIndices[1] += (idx1 + this->m_offsets[i]) * this->m_inputStrides[i];
         indices[0] -= idx0 * this->m_outputStrides[i];
         indices[1] -= idx1 * this->m_outputStrides[i];
       }
       inputIndices[0] += (indices[0] + this->m_offsets[0]);
       inputIndices[1] += (indices[1] + this->m_offsets[0]);
     } else {
       EIGEN_UNROLL_LOOP
       for (int i = 0; i < NumDims - 1; ++i) {
         const Index idx0 = indices[0] / this->m_fastOutputStrides[i];
         const Index idx1 = indices[1] / this->m_fastOutputStrides[i];
         inputIndices[0] += (idx0 + this->m_offsets[i]) * this->m_inputStrides[i];
         inputIndices[1] += (idx1 + this->m_offsets[i]) * this->m_inputStrides[i];
         indices[0] -= idx0 * this->m_outputStrides[i];
         indices[1] -= idx1 * this->m_outputStrides[i];
       }
       inputIndices[0] += (indices[0] + this->m_offsets[NumDims - 1]);
       inputIndices[1] += (indices[1] + this->m_offsets[NumDims - 1]);
     }
     if (inputIndices[1] - inputIndices[0] == packetSize - 1) {
       this->m_impl.template writePacket<StoreMode>(inputIndices[0], x);
     } else {
       EIGEN_ALIGN_MAX CoeffReturnType values[packetSize];
       internal::pstore<CoeffReturnType, PacketReturnType>(values, x);
       this->m_impl.coeffRef(inputIndices[0]) = values[0];
       this->m_impl.coeffRef(inputIndices[1]) = values[packetSize - 1];
       EIGEN_UNROLL_LOOP
       for (int i = 1; i < packetSize - 1; ++i) {
         this->coeffRef(index + i) = values[i];
       }
     }
   }
References Eigen::TensorEvaluator< Derived, Device >::coeffRef(), Eigen::ColMajor, EIGEN_ALIGN_MAX, EIGEN_UNROLL_LOOP, i, Eigen::TensorEvaluator< Derived, Device >::Layout, and plotDoE::x.
Member Data Documentation
Layout
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::Layout = TensorEvaluator<ArgType, Device>::Layout static constexpr
NumDims
template<typename StartIndices , typename Sizes , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< TensorSlicingOp< StartIndices, Sizes, ArgType >, Device >::NumDims = internal::array_size<Sizes>::value static constexpr
The documentation for this struct was generated from the following file:
TensorMorphing.h