MercuryDPM: BoussinesqPreconditioner Class Reference
BoussinesqPreconditioner Class Reference
Public Member Functions
BoussinesqPreconditioner (Problem *problem_pt)
~BoussinesqPreconditioner ()
Destructor: Clean up.
BoussinesqPreconditioner (const BoussinesqPreconditioner &)
Broken copy constructor.
void use_block_diagonal_version ()
Switch to block-diagonal preconditioner.
void use_block_triangular_version_with_fluid_on_temperature ()
void use_block_triangular_version_with_temperature_on_fluid ()
void setup ()
Setup the preconditioner.
void preconditioner_solve (const DoubleVector &r, DoubleVector &z)
Apply preconditioner to r.
NavierStokesSchurComplementPreconditioner * navier_stokes_preconditioner_pt () const
Access function to the Navier Stokes preconditioner (inexact solver)
void enable_doc_time ()
Enable documentation of timings.
void disable_doc_time ()
Disable documentation of timings.
Public Member Functions inherited from oomph::BlockPreconditioner< CRDoubleMatrix >
BlockPreconditioner ()
Constructor.
BlockPreconditioner (const BlockPreconditioner &)=delete
Broken copy constructor.
virtual ~BlockPreconditioner ()
Destructor.
void operator= (const BlockPreconditioner &)=delete
Broken assignment operator.
CRDoubleMatrix * matrix_pt () const
void turn_on_recursive_debug_flag ()
void turn_off_recursive_debug_flag ()
void turn_on_debug_flag ()
Toggles on the debug flag.
void turn_off_debug_flag ()
Toggles off the debug flag.
void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse)
void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse, const Vector< Vector< unsigned >> &doftype_coarsen_map_coarse)
virtual void block_setup ()
void block_setup (const Vector< unsigned > &dof_to_block_map)
void get_block (const unsigned &i, const unsigned &j, CRDoubleMatrix &output_matrix, const bool &ignore_replacement_block=false) const
CRDoubleMatrix get_block (const unsigned &i, const unsigned &j, const bool &ignore_replacement_block=false) const
void set_master_matrix_pt (CRDoubleMatrix *in_matrix_pt)
Set the matrix_pt in the upper-most master preconditioner.
void get_block_other_matrix (const unsigned &i, const unsigned &j, CRDoubleMatrix *in_matrix_pt, CRDoubleMatrix &output_matrix)
void get_blocks (DenseMatrix< bool > &required_blocks, DenseMatrix< CRDoubleMatrix * > &block_matrix_pt) const
void get_dof_level_block (const unsigned &i, const unsigned &j, CRDoubleMatrix &output_block, const bool &ignore_replacement_block=false) const
void get_dof_level_block (const unsigned &block_i, const unsigned &block_j, CRDoubleMatrix &output_block, const bool &ignore_replacement_block) const
CRDoubleMatrix get_concatenated_block (const VectorMatrix< BlockSelector > &selected_block)
void get_concatenated_block_vector (const Vector< unsigned > &block_vec_number, const DoubleVector &v, DoubleVector &b)
void return_concatenated_block_vector (const Vector< unsigned > &block_vec_number, const DoubleVector &b, DoubleVector &v) const
Takes concatenated block ordered vector, b, and copies its.
void get_block_vectors (const Vector< unsigned > &block_vec_number, const DoubleVector &v, Vector< DoubleVector > &s) const
void get_block_vectors (const DoubleVector &v, Vector< DoubleVector > &s) const
void return_block_vectors (const Vector< unsigned > &block_vec_number, const Vector< DoubleVector > &s, DoubleVector &v) const
void return_block_vectors (const Vector< DoubleVector > &s, DoubleVector &v) const
void get_block_vector (const unsigned &n, const DoubleVector &v, DoubleVector &b) const
void return_block_vector (const unsigned &n, const DoubleVector &b, DoubleVector &v) const
void get_block_ordered_preconditioner_vector (const DoubleVector &v, DoubleVector &w)
void return_block_ordered_preconditioner_vector (const DoubleVector &w, DoubleVector &v) const
unsigned nblock_types () const
Return the number of block types.
unsigned ndof_types () const
Return the total number of DOF types.
const Mesh * mesh_pt (const unsigned &i) const
unsigned nmesh () const
int block_number (const unsigned &i_dof) const
Return the block number corresponding to a global index i_dof.
int index_in_block (const unsigned &i_dof) const
const LinearAlgebraDistribution * block_distribution_pt (const unsigned &b) const
Access function to the block distributions (const version).
LinearAlgebraDistribution * block_distribution_pt (const unsigned b)
Access function to the block distributions (non-const version).
LinearAlgebraDistribution * dof_block_distribution_pt (const unsigned &b)
Access function to the dof-level block distributions.
const LinearAlgebraDistribution * master_distribution_pt () const
unsigned ndof_types_in_mesh (const unsigned &i) const
bool is_subsidiary_block_preconditioner () const
bool is_master_block_preconditioner () const
void set_block_output_to_files (const std::string &basefilename)
void disable_block_output_to_files ()
Turn off output of blocks (by clearing the basefilename string).
bool block_output_on () const
Test if output of blocks is on or not.
void output_blocks_to_files (const std::string &basefilename, const unsigned &precision=8) const
void post_block_matrix_assembly_partial_clear ()
BlockPreconditioner< CRDoubleMatrix > * master_block_preconditioner_pt () const
Access function to the master block preconditioner pt.
void clear_block_preconditioner_base ()
void document ()
Vector< Vector< unsigned > > doftype_coarsen_map_fine () const
Vector< unsigned > get_fine_grain_dof_types_in (const unsigned &i) const
unsigned nfine_grain_dof_types_in (const unsigned &i) const
MapMatrix< unsigned, CRDoubleMatrix * > replacement_dof_block_pt () const
Access function to the replaced dof-level blocks.
void setup_matrix_vector_product (MatrixVectorProduct *matvec_prod_pt, CRDoubleMatrix *block_pt, const Vector< unsigned > &block_col_indices)
void setup_matrix_vector_product (MatrixVectorProduct *matvec_prod_pt, CRDoubleMatrix *block_pt, const unsigned &block_col_index)
void internal_get_block_ordered_preconditioner_vector (const DoubleVector &v, DoubleVector &w) const
void internal_return_block_ordered_preconditioner_vector (const DoubleVector &w, DoubleVector &v) const
unsigned internal_nblock_types () const
unsigned internal_ndof_types () const
void internal_return_block_vector (const unsigned &n, const DoubleVector &b, DoubleVector &v) const
void internal_get_block_vector (const unsigned &n, const DoubleVector &v, DoubleVector &b) const
void internal_get_block_vectors (const Vector< unsigned > &block_vec_number, const DoubleVector &v, Vector< DoubleVector > &s) const
void internal_get_block_vectors (const DoubleVector &v, Vector< DoubleVector > &s) const
void internal_return_block_vectors (const Vector< unsigned > &block_vec_number, const Vector< DoubleVector > &s, DoubleVector &v) const
void internal_return_block_vectors (const Vector< DoubleVector > &s, DoubleVector &v) const
void internal_get_block (const unsigned &i, const unsigned &j, CRDoubleMatrix &output_block) const
void internal_get_block (const unsigned &block_i, const unsigned &block_j, CRDoubleMatrix &output_block) const
int internal_block_number (const unsigned &i_dof) const
int internal_index_in_block (const unsigned &i_dof) const
const LinearAlgebraDistribution * internal_block_distribution_pt (const unsigned &b) const
Access function to the internal block distributions.
void insert_auxiliary_block_distribution (const Vector< unsigned > &block_vec_number, LinearAlgebraDistribution *dist_pt)
void block_matrix_test (const unsigned &i, const unsigned &j, const CRDoubleMatrix *block_matrix_pt) const
int get_index_of_value (const Vector< myType > &vec, const myType val, const bool sorted=false) const
Public Member Functions inherited from oomph::Preconditioner
Preconditioner ()
Constructor.
Preconditioner (const Preconditioner &)=delete
Broken copy constructor.
void operator= (const Preconditioner &)=delete
Broken assignment operator.
virtual ~Preconditioner ()
Destructor (empty)
virtual void preconditioner_solve_transpose (const DoubleVector &r, DoubleVector &z)
void setup (DoubleMatrixBase *matrix_pt)
void setup (const Problem *problem_pt, DoubleMatrixBase *matrix_pt)
void enable_silent_preconditioner_setup ()
Set up the block preconditioner quietly!
void disable_silent_preconditioner_setup ()
Be verbose in the block preconditioner setup.
virtual void set_matrix_pt (DoubleMatrixBase *matrix_pt)
Set the matrix pointer.
virtual const OomphCommunicator * comm_pt () const
Get function for comm pointer.
virtual void set_comm_pt (const OomphCommunicator *const comm_pt)
Set the communicator pointer.
double setup_time () const
Returns the time to setup the preconditioner.
virtual void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse)
virtual void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse, const Vector< Vector< unsigned >> &doftype_coarsen_map_coarse)
Public Member Functions inherited from oomph::DistributableLinearAlgebraObject
DistributableLinearAlgebraObject ()
Default constructor - create a distribution.
DistributableLinearAlgebraObject (const DistributableLinearAlgebraObject &matrix)=delete
Broken copy constructor.
void operator= (const DistributableLinearAlgebraObject &)=delete
Broken assignment operator.
virtual ~DistributableLinearAlgebraObject ()
Destructor.
LinearAlgebraDistribution * distribution_pt () const
access to the LinearAlgebraDistribution
unsigned nrow () const
access function to the number of global rows.
unsigned nrow_local () const
access function for the num of local rows on this processor.
unsigned nrow_local (const unsigned &p) const
access function for the num of local rows on this processor.
unsigned first_row () const
access function for the first row on this processor
unsigned first_row (const unsigned &p) const
access function for the first row on this processor
bool distributed () const
distribution is serial or distributed
bool distribution_built () const
void build_distribution (const LinearAlgebraDistribution *const dist_pt)
void build_distribution (const LinearAlgebraDistribution &dist)
Private Member Functions
void clean_up_memory ()
Clean up memory, delete the blocks allocated in setup.
Private Attributes
NavierStokesSchurComplementPreconditioner * Navier_stokes_preconditioner_pt
Pointer the Navier Stokes preconditioner (inexact solver)
Preconditioner * Temperature_preconditioner_pt
Pointer to the temperature preconditioner (inexact solver)
Preconditioner * P_preconditioner_pt
Inexact solver for P block.
Preconditioner * F_preconditioner_pt
Inexact solver for F block.
CRDoubleMatrix * Block_matrix_0_1_pt
Pointer to fluid/temperature interaction matrix.
CRDoubleMatrix * Block_matrix_1_0_pt
Pointer to temperature/fluid interaction matrix.
bool Preconditioner_has_been_setup
Boolean indicating the preconditioner has been set up.
bool Retain_temperature_onto_fluid_terms
bool Retain_fluid_onto_temperature_terms
bool Doc_time
Set Doc_time to true for outputting results of timings.
Additional Inherited Members
Protected Member Functions inherited from oomph::BlockPreconditioner< CRDoubleMatrix >
void set_nmesh (const unsigned &n)
void set_mesh (const unsigned &i, const Mesh *const mesh_pt, const bool &allow_multiple_element_type_in_mesh=false)
void set_replacement_dof_block (const unsigned &block_i, const unsigned &block_j, CRDoubleMatrix *replacement_dof_block_pt)
bool any_mesh_distributed () const
int internal_dof_number (const unsigned &i_dof) const
unsigned internal_index_in_dof (const unsigned &i_dof) const
unsigned internal_block_dimension (const unsigned &b) const
unsigned internal_dof_block_dimension (const unsigned &i) const
unsigned master_nrow () const
unsigned internal_master_dof_number (const unsigned &b) const
const LinearAlgebraDistribution * internal_preconditioner_matrix_distribution_pt () const
const LinearAlgebraDistribution * preconditioner_matrix_distribution_pt () const
Protected Member Functions inherited from oomph::DistributableLinearAlgebraObject
void clear_distribution ()
Protected Attributes inherited from oomph::BlockPreconditioner< CRDoubleMatrix >
MapMatrix< unsigned, CRDoubleMatrix * > Replacement_dof_block_pt
The replacement dof-level blocks.
Vector< LinearAlgebraDistribution * > Block_distribution_pt
The distribution for the blocks.
Vector< Vector< unsigned > > Block_to_dof_map_coarse
Vector< Vector< unsigned > > Block_to_dof_map_fine
Mapping for the block types to the most fine grain dof types.
Vector< Vector< unsigned > > Doftype_coarsen_map_coarse
Vector< Vector< unsigned > > Doftype_coarsen_map_fine
Vector< LinearAlgebraDistribution * > Internal_block_distribution_pt
Storage for the default distribution for each internal block.
Vector< LinearAlgebraDistribution * > Dof_block_distribution_pt
Vector< unsigned > Allow_multiple_element_type_in_mesh
Vector< const Mesh * > Mesh_pt
Vector< unsigned > Ndof_types_in_mesh
unsigned Internal_nblock_types
unsigned Internal_ndof_types
Protected Attributes inherited from oomph::Preconditioner
bool Silent_preconditioner_setup
Boolean to indicate whether or not the build should be done silently.
std::ostream * Stream_pt
Pointer to the output stream – defaults to std::cout.
Detailed Description
Boussinesq preconditioner. This extracts upper/lower triangular blocks in the 3x3 overall block matrix structure arising from the monolithic discretisation of Boussinesq problems. Dofs are decomposed into fluid velocity, pressure and temperature unknowns. NavierStokesSchurComplementPreconditioner is used as the inexact solver for the fluid block; SuperLU (in its incarnation as an "exact" preconditioner) is used for the temperature block. By default we retain the fluid on temperature off diagonal blocks.
Constructor & Destructor Documentation
BoussinesqPreconditioner() [1/2]
BoussinesqPreconditioner::BoussinesqPreconditioner (Problem * problem_pt) inline
Constructor: By default use block triangular form with retained fluid on temperature terms. Requires a non-constant problem pointer because of the underlying NavierStokesSchurComplementPreconditioner.
   {
    // Default setting: Fluid onto temperature
    Retain_temperature_onto_fluid_terms=false;
    Retain_fluid_onto_temperature_terms=true;
    // Create the Navier Stokes preconditioner
    Navier_stokes_preconditioner_pt =
     new NavierStokesSchurComplementPreconditioner(problem_pt);
    Navier_stokes_preconditioner_pt->disable_doc_time();
    //Set the temperature preconditioner
    Temperature_preconditioner_pt = new SuperLUPreconditioner;
    //Initialise the P and F block preconditioners
    P_preconditioner_pt = 0;
    F_preconditioner_pt = 0;
 #ifdef OOMPH_HAS_HYPRE
 //If we have compiled with MPI,
 //only use HYPRE if it's been initialised
 #ifdef OOMPH_HAS_MPI
    if(MPI_Helpers::mpi_has_been_initialised())
 #endif
     {
      //Set up the internal preconditioners
      P_preconditioner_pt = new HyprePreconditioner;
      // Set parameters for use as preconditioner on Poisson-type problem
      Hypre_default_settings::set_defaults_for_3D_poisson_problem(
       static_cast<HyprePreconditioner*>(P_preconditioner_pt));
      // Use Hypre for the Schur complement block
      Navier_stokes_preconditioner_pt->
       set_p_preconditioner(P_preconditioner_pt);
      F_preconditioner_pt = new HyprePreconditioner;
      // Set parameters for use as preconditioner in for momentum
      // block in Navier-Stokes problem
      Hypre_default_settings::set_defaults_for_navier_stokes_momentum_block(
       static_cast<HyprePreconditioner*>(F_preconditioner_pt));
      // Use Hypre for momentum block
      Navier_stokes_preconditioner_pt->
       set_f_preconditioner(F_preconditioner_pt);
      //Set the Temperature preconditioner to also use AMG
      delete Temperature_preconditioner_pt; Temperature_preconditioner_pt = 0;
      Temperature_preconditioner_pt = new HyprePreconditioner;
      Hypre_default_settings::set_defaults_for_navier_stokes_momentum_block(
       static_cast<HyprePreconditioner*>(Temperature_preconditioner_pt));
     }
 #endif
    // Preconditioner hasn't been set up yet.
    Preconditioner_has_been_setup=false;
    // Null out pointers to additional block matrices not already
    // stored in Navier Stokes block preconditioner
    Block_matrix_0_1_pt=0;
    Block_matrix_1_0_pt=0;
    // set Doc_time to false
    Doc_time = false;
    // set the mesh to be the main mesh of the problem
    this->set_nmesh(1);
    this->set_mesh(0,problem_pt->mesh_pt());
    // Set up the (non-const) mesh pointer for the schur complement
    // preconditioner.
    Navier_stokes_preconditioner_pt->set_navier_stokes_mesh
     (problem_pt->mesh_pt());
   }
References oomph::Problem::mesh_pt(), oomph::MPI_Helpers::mpi_has_been_initialised(), oomph::Hypre_default_settings::set_defaults_for_3D_poisson_problem(), and oomph::Hypre_default_settings::set_defaults_for_navier_stokes_momentum_block().
~BoussinesqPreconditioner()
BoussinesqPreconditioner::~BoussinesqPreconditioner () inline
Destructor: Clean up.
   {
    // Do what it says
    clean_up_memory();
    //Delete the P block preconditioners
    delete P_preconditioner_pt;  P_preconditioner_pt = 0;
    //Delete the F block preconditioner
    delete F_preconditioner_pt; F_preconditioner_pt = 0;
    //Delete the Navier-Stokes preconditioner (inexact solver)
    delete Navier_stokes_preconditioner_pt; Navier_stokes_preconditioner_pt = 0;
    //Delete the temperature preconditioner (inexact solver)
    delete Temperature_preconditioner_pt; Temperature_preconditioner_pt = 0;
   }
References oomph::TerminateHelper::clean_up_memory().
BoussinesqPreconditioner() [2/2]
BoussinesqPreconditioner::BoussinesqPreconditioner (const BoussinesqPreconditioner &) inline
Broken copy constructor.
   {
    BrokenCopy::broken_copy("BoussinesqPreconditioner");
   }
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
clean_up_memory()
void BoussinesqPreconditioner::clean_up_memory () inline private virtual
Clean up memory, delete the blocks allocated in setup.
Reimplemented from oomph::Preconditioner.
   {
    if (Preconditioner_has_been_setup)
     {
      if (Retain_temperature_onto_fluid_terms)
       {
        delete Block_matrix_0_1_pt;
        Block_matrix_0_1_pt=0;
       }
      if (Retain_fluid_onto_temperature_terms)
       {
        delete Block_matrix_1_0_pt;
        Block_matrix_1_0_pt=0;
       }
     }
   }
disable_doc_time()
void BoussinesqPreconditioner::disable_doc_time () inline
Disable documentation of timings.
 {Doc_time = false;}
enable_doc_time()
void BoussinesqPreconditioner::enable_doc_time () inline
Enable documentation of timings.
 {Doc_time = true;}
navier_stokes_preconditioner_pt()
NavierStokesSchurComplementPreconditioner* BoussinesqPreconditioner::navier_stokes_preconditioner_pt () const inline
Access function to the Navier Stokes preconditioner (inexact solver)
   {
    return Navier_stokes_preconditioner_pt;
   }
preconditioner_solve()
void BoussinesqPreconditioner::preconditioner_solve (const DoubleVector & r, DoubleVector & z) virtual
Apply preconditioner to r.
Apply preconditioner to Vector r.
Implements oomph::Preconditioner.
 {
  // if z is not setup then give it the same distribution
  if (!z.built())
   {
    z.build(r.distribution_pt(),0.0);
   }
  // Make copy of residual vector (to overcome const-ness
  DoubleVector res(r);
  // Retain off-diagonals that represent effect of temperature on fluid
  //-------------------------------------------------------------------
  if (Retain_temperature_onto_fluid_terms)
   {
    // Working vectors
    DoubleVector temp_temperature_vec;
    DoubleVector temp_fluid_vec;
    // Copy temperature values from residual to temp_vec:
    // Loop over all entries in the global vector (this one
    // includes tempearture, velocity and pressure dofs in some random fashion)
    get_block_vector(1,res,temp_temperature_vec);
    // Solve temperature system by back-substitution
    // with LU-decomposed temperature-temperature Jacobian
    Temperature_preconditioner_pt->preconditioner_solve(temp_temperature_vec,
                                                        temp_temperature_vec);
    this->return_block_vector(1,temp_temperature_vec,z);
    // NOTE: temp_temperature_vec now contains z_t = S^{-1} r_t
    // Multiply C_{ut} by z_t
    Block_matrix_0_1_pt->multiply(temp_temperature_vec,temp_fluid_vec);
 //   Mat_vec_operator_0_1_pt->multiply(temp_temperature_vec,temp_fluid_vec);
    temp_temperature_vec.clear();
    // Subtract from fluid residual vector for fluid solve
    DoubleVector another_temp_vec;
    this->get_block_vector(0,res,another_temp_vec);
    another_temp_vec -= temp_fluid_vec;
    this->return_block_vector(0,another_temp_vec,res);
    // now apply the navier stokes lsc preconditioner
    Navier_stokes_preconditioner_pt->preconditioner_solve(res,z);
   }
  // Retain off-diagonals that represent effect of fluid on temperature
  //-------------------------------------------------------------------
  // (or diagonal preconditioner)
  //-----------------------------
  else
   {
    // Call fluid preconditioner for fluid block
    Navier_stokes_preconditioner_pt->preconditioner_solve(res,z);
    // Working vectors
    DoubleVector temp_temperature_vec;
    // get the temperature vector
    get_block_vector(1,res,temp_temperature_vec);
    // Do matrix vector products with fluid onto temperature coupling matrices:
    if (Retain_fluid_onto_temperature_terms)
     {
      DoubleVector temp_fluid_vec;
      get_block_vector(0,z,temp_fluid_vec);
      // Auxiliary vector to hold the matrix vector product of the
      // fluid-onto-temperature coupling matrices with the fluid solutions:
      DoubleVector aux_vec;
      // Multiply C_{tu} by z_u
      Block_matrix_1_0_pt->multiply(temp_fluid_vec, aux_vec);
      // ...and subtract from r_t:
      temp_temperature_vec-=aux_vec;
     }
    // Solve temperature system by back-substitution
    // with LU-decomposed temperature-temperature Jacobian
    Temperature_preconditioner_pt->preconditioner_solve(temp_temperature_vec,
                                                  temp_temperature_vec);
    // Now copy result_vec (i.e. z_t) back into the global vector z.
    // Loop over all entries in the global results vector z:
    return_block_vector(1,temp_temperature_vec,z);
   }
 }
References oomph::DoubleVector::build(), oomph::DoubleVector::built(), oomph::DoubleVector::clear(), UniformPSDSelfTest::r, and res.
setup()
void BoussinesqPreconditioner::setup () virtual
Setup the preconditioner.
Setup the preconditioner. Note: Matrix must be a CRDoubleMatrix.
/////////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////////
Implements oomph::Preconditioner.
  {
   // Clean up any existing data
   this->clean_up_memory();
   // Get total number of dofs.
   unsigned n_dof=mesh_pt(0)->finite_element_pt(0)->dim()+2;
   // Number of fluid dofs: one less
   unsigned n_fluid_dof = n_dof-1;
   // This preconditioner has two types of DOF: Fluid dofs and temperature dofs
   // Initialise block type to zero (correct for fluid dofs)
   Vector<unsigned> dof_to_block_map(n_dof,0);
   // Temperature dofs are "type one"
   dof_to_block_map[n_dof-1] = 1;
   // Call block setup for this preconditioner
   this->block_setup(dof_to_block_map);
   // Block mapping for the subsidiary Navier Stokes preconditioner:
   // blocks 0 and 1 in the Boussinesq preconditioner are also blocks 0 and 1
   // in the subsidiary Navier Stokes one.
   Vector<unsigned> ns_dof_lookup(n_fluid_dof);
   for (unsigned i = 0; i < n_fluid_dof; i++)
    {
     ns_dof_lookup[i] = i;
    }
   // Turn the Navier Stokes Schur complement preconditioner into a
   // subsidiary preconditioner of this preconditioner
   Navier_stokes_preconditioner_pt->
    turn_into_subsidiary_block_preconditioner(this,ns_dof_lookup);
   // Setup the Navier Stokes preconditioner:
   Navier_stokes_preconditioner_pt->setup(matrix_pt());
   // Extract the additional blocks we need for Boussinesq:
   // Temperature matrix
   CRDoubleMatrix* block_matrix_1_1_pt = new CRDoubleMatrix;
   this->get_block(1,1,*block_matrix_1_1_pt);
   // Temperature on fluid terms (if needed)
   if (Retain_temperature_onto_fluid_terms)
    {
     delete Block_matrix_0_1_pt; Block_matrix_0_1_pt = 0;
     Block_matrix_0_1_pt = new CRDoubleMatrix;
     this->get_block(0,1,*Block_matrix_0_1_pt);
    }
   // Fluid on temperature terms (if needed)
   if (Retain_fluid_onto_temperature_terms)
    {
     delete Block_matrix_1_0_pt; Block_matrix_1_0_pt = 0;
     Block_matrix_1_0_pt = new CRDoubleMatrix;
     this->get_block(1,0,*Block_matrix_1_0_pt);
    }
   // Setup the temperature preconditioner (inexact solver)
   double t_start = TimingHelpers::timer();
   Temperature_preconditioner_pt->setup(block_matrix_1_1_pt);
   double t_end = TimingHelpers::timer();
   double setup_time= t_end-t_start;
   delete block_matrix_1_1_pt; block_matrix_1_1_pt = 0;
  // Output times
  if(Doc_time)
   {
    oomph_info << "Temperature sub-preconditioner setup time [sec]: "
               << setup_time << "\n";
    // Doc density of retained interaction block
    if (Retain_temperature_onto_fluid_terms)
     {
      oomph_info
       << "Fill level of temperature on fluid blocks (C_ut and C_pt): " <<
       double(Block_matrix_0_1_pt->nnz())/
       double(Block_matrix_0_1_pt->nrow()*
              Block_matrix_0_1_pt->ncol())*100.0
       << "%  " << std::endl;
     }
    // Doc density of retained interaction block
    if (Retain_fluid_onto_temperature_terms)
     {
      oomph_info
       << "Fill level of fluid on temperature blocks (C_tu and C_tp): " <<
       double(Block_matrix_1_0_pt->nnz())/
       double(Block_matrix_1_0_pt->nrow()*
              Block_matrix_1_0_pt->ncol())*100.0
       << "%  " << std::endl;
     }
   }
   // We're done (and we stored some data)
   Preconditioner_has_been_setup=true;
  }
References oomph::TerminateHelper::clean_up_memory(), i, oomph::oomph_info, and oomph::TimingHelpers::timer().
use_block_diagonal_version()
void BoussinesqPreconditioner::use_block_diagonal_version () inline
Switch to block-diagonal preconditioner.
   {
    Retain_temperature_onto_fluid_terms=false;
    Retain_fluid_onto_temperature_terms=false;
   }
use_block_triangular_version_with_fluid_on_temperature()
void BoussinesqPreconditioner::use_block_triangular_version_with_fluid_on_temperature () inline
Switch to block-triangular preconditioner in which action of fluid dofs onto temperature equations is retained
   {
    Retain_temperature_onto_fluid_terms=false;
    Retain_fluid_onto_temperature_terms=true;
   }
use_block_triangular_version_with_temperature_on_fluid()
void BoussinesqPreconditioner::use_block_triangular_version_with_temperature_on_fluid () inline
Switch to block-triangular preconditioner in which action of temperature dofs onto fluid equations is retained
   {
    Retain_temperature_onto_fluid_terms=true;
    Retain_fluid_onto_temperature_terms=false;
   }
Member Data Documentation
Block_matrix_0_1_pt
CRDoubleMatrix* BoussinesqPreconditioner::Block_matrix_0_1_pt private
Pointer to fluid/temperature interaction matrix.
Block_matrix_1_0_pt
CRDoubleMatrix* BoussinesqPreconditioner::Block_matrix_1_0_pt private
Pointer to temperature/fluid interaction matrix.
Doc_time
bool BoussinesqPreconditioner::Doc_time private
Set Doc_time to true for outputting results of timings.
F_preconditioner_pt
Preconditioner* BoussinesqPreconditioner::F_preconditioner_pt private
Inexact solver for F block.
Navier_stokes_preconditioner_pt
NavierStokesSchurComplementPreconditioner* BoussinesqPreconditioner::Navier_stokes_preconditioner_pt private
Pointer the Navier Stokes preconditioner (inexact solver)
P_preconditioner_pt
Preconditioner* BoussinesqPreconditioner::P_preconditioner_pt private
Inexact solver for P block.
Preconditioner_has_been_setup
bool BoussinesqPreconditioner::Preconditioner_has_been_setup private
Boolean indicating the preconditioner has been set up.
Retain_fluid_onto_temperature_terms
bool BoussinesqPreconditioner::Retain_fluid_onto_temperature_terms private
Boolean flag used to indicate that the fluid onto temperature interaction terms are to be retained
Retain_temperature_onto_fluid_terms
bool BoussinesqPreconditioner::Retain_temperature_onto_fluid_terms private
Boolean flag used to indicate that the temperature onto fluid interaction terms are to be retained
Temperature_preconditioner_pt
Preconditioner* BoussinesqPreconditioner::Temperature_preconditioner_pt private
Pointer to the temperature preconditioner (inexact solver)
The documentation for this class was generated from the following file:
3d_ref_b_convect.cc