MercuryDPM: WearableTriangulatedWall Class Reference
WearableTriangulatedWall Class Reference
#include <WearableTriangulatedWall.h>
Public Member Functions
WearableTriangulatedWall ()
Default constructor.
WearableTriangulatedWall (const WearableTriangulatedWall &other)
Copy constructor.
WearableTriangulatedWall (Mdouble lengthU, Mdouble lengthV, Mdouble resolutionU, Mdouble resolutionV)
Creates flat triangulated rectangle with certain resolution.
~WearableTriangulatedWall () override
Destructor.
WearableTriangulatedWall & operator= (const WearableTriangulatedWall &other)
WearableTriangulatedWall * copy () const override
Wall copy method. It calls the copy constructor of this Wall, useful for polymorphism.
void read (std::istream &is) override
Reads an WearableTriangulatedWall from an input stream, for example a restart file.
void write (std::ostream &os) const override
Writes an WearableTriangulatedWall to an output stream, for example a restart file.
std::string getName () const override
Returns the name of the object, here the string "WearableTriangulatedWall".
void computeWear () override
Public Member Functions inherited from TriangulatedWall
TriangulatedWall ()
Default constructor.
TriangulatedWall (const TriangulatedWall &other)
Copy constructor.
TriangulatedWall (std::string filename, const ParticleSpecies *species)
Constructor setting values.
TriangulatedWall (const std::vector< Vec3D > &points, const std::vector< std::vector< unsigned >> &cells, const ParticleSpecies *species)
Constructor setting values.
void set (const std::vector< Vec3D > &points, const std::vector< std::vector< unsigned >> &cells)
void readVTK (std::string filename)
void writeVTK (VTKContainer &vtk) const override
~TriangulatedWall () override
Destructor.
TriangulatedWall & operator= (const TriangulatedWall &other)
bool getDistanceAndNormal (const BaseParticle &p, Mdouble &distance, Vec3D &normal_return) const override
Compute the distance from the wall for a given BaseParticle and return if there is a collision. If there is a collision, also return the normal vector.
void move (const Vec3D &move) override
Move the TriangulatedWall to a new position, which is a Vec3D from the old position.
BaseInteraction * getInteractionWith (BaseParticle *p, unsigned timeStamp, InteractionHandler *interactionHandler) override
Get the interaction between this TriangulatedWall and given BaseParticle at a given time.
Public Member Functions inherited from BaseWall
BaseWall ()
Default constructor.
BaseWall (const BaseWall &w)
Copy constructor.
~BaseWall () override
Default destructor.
virtual bool getDistanceNormalOverlap (const BaseParticle &P, Mdouble &distance, Vec3D &normal_return, Mdouble &overlap) const
virtual bool getDistanceNormalOverlapSuperquadric (const SuperQuadricParticle &p, Mdouble &distance, Vec3D &normal_return, Mdouble &overlap) const
virtual Vec3D getFurthestPointSuperQuadric (const Vec3D &normalBodyFixed, const Vec3D &axes, Mdouble eps1, Mdouble eps2) const
virtual void setHandler (WallHandler *handler)
A function which sets the WallHandler for this BaseWall.
WallHandler * getHandler () const
A function which returns the WallHandler that handles this BaseWall.
void setIndSpecies (unsigned int indSpecies) override
Define the species of this wall using the index of the species in the SpeciesHandler in this DPMBase.
void setSpecies (const ParticleSpecies *species)
Defines the species of the current wall.
bool isFixed () const override
void setForceControl (Vec3D forceGoal, Vec3D gainFactor, Vec3D baseVelocity={0, 0, 0})
Slowly adjusts the force on a wall towards a specified goal, by adjusting (prescribing) the velocity of the wall.
virtual bool isLocal (Vec3D &min, Vec3D &max) const
bool getLinePlaneIntersect (Vec3D &intersect, const Vec3D &p0, const Vec3D &p1, const Vec3D &n, const Vec3D &p)
bool isInsideWallVTK (const Vec3D &point, const Vec3D &normal, const Vec3D &position) const
void projectOntoWallVTK (Vec3D &point0, const Vec3D &point1, const Vec3D &normal, const Vec3D &position) const
void intersectVTK (std::vector< Vec3D > &points, Vec3D normal, Vec3D position) const
virtual BaseInteraction * getInteractionWithSuperQuad (SuperQuadricParticle *p, unsigned timeStamp, InteractionHandler *interactionHandler)
void getVTK (std::vector< Vec3D > &points, std::vector< std::vector< double >> &triangleStrips)
const Vec3D getAxis () const
virtual void actionsOnRestart ()
No implementation but can be overidden in its derived classes.
virtual void actionsAfterParticleGhostUpdate ()
No implementation but can be overidden in its derived classes.
virtual void handleParticleAddition (unsigned int id, BaseParticle *p)
Handles the addition of particles to the particleHandler.
virtual void handleParticleRemoval (unsigned int id)
Handles the addition of particles to the particleHandler.
virtual void checkInteractions (InteractionHandler *interactionHandler, unsigned int timeStamp)
Check if all interactions are valid.
bool getVTKVisibility () const
void setVTKVisibility (bool vtkVisibility)
void addRenderedWall (BaseWall *w)
BaseWall * getRenderedWall (size_t i) const
std::vector< BaseWall * > getRenderedWalls () const
void removeRenderedWalls ()
void renderWall (VTKContainer &vtk)
void addParticlesAtWall (unsigned numElements=50)
void setVelocityControl (Vec3D forceGoal, Vec3D gainFactor, Vec3D baseVelocity)
virtual void writeWallDetailsVTK (VTKData &data) const
Public Member Functions inherited from BaseInteractable
BaseInteractable ()
Default BaseInteractable constructor.
BaseInteractable (const BaseInteractable &p)
Copy constructor.
~BaseInteractable () override
Destructor, it simply destructs the BaseInteractable and all the objects it contains.
unsigned int getIndSpecies () const
Returns the index of the species associated with the interactable object.
const ParticleSpecies * getSpecies () const
Returns a pointer to the species of this BaseInteractable.
void setSpecies (const ParticleSpecies *species)
Sets the species of this BaseInteractable.
const Vec3D & getForce () const
Returns the force on this BaseInteractable.
const Vec3D & getTorque () const
Returns the torque on this BaseInteractable.
void setForce (const Vec3D &force)
Sets the force on this BaseInteractable.
void setTorque (const Vec3D &torque)
Sets the torque on this BaseInteractable.
void addForce (const Vec3D &addForce)
Adds an amount to the force on this BaseInteractable.
void addTorque (const Vec3D &addTorque)
Adds an amount to the torque on this BaseInteractable.
virtual void resetForceTorque (int numberOfOMPthreads)
void sumForceTorqueOMP ()
const Vec3D & getPosition () const
Returns the position of this BaseInteractable.
const Quaternion & getOrientation () const
Returns the orientation of this BaseInteractable.
virtual void setPosition (const Vec3D &position)
Sets the position of this BaseInteractable.
void setOrientationViaNormal (Vec3D normal)
Sets the orientation of this BaseInteractable by defining the vector that results from the rotation of the (1,0,0) vector.
void setOrientationViaEuler (Vec3D eulerAngle)
Sets the orientation of this BaseInteractable by defining the euler angles.
virtual void setOrientation (const Quaternion &orientation)
Sets the orientation of this BaseInteractable.
virtual void rotate (const Vec3D &angularVelocityDt)
Rotates this BaseInteractable.
const std::vector< BaseInteraction * > & getInteractions () const
Returns a list of interactions which belong to this interactable.
void addInteraction (BaseInteraction *I)
Adds an interaction to this BaseInteractable.
bool removeInteraction (BaseInteraction *I)
Removes an interaction from this BaseInteractable.
void copyInteractionsForPeriodicParticles (const BaseInteractable &p)
Copies interactions to this BaseInteractable whenever a periodic copy made.
void setVelocity (const Vec3D &velocity)
set the velocity of the BaseInteractable.
void setAngularVelocity (const Vec3D &angularVelocity)
set the angular velocity of the BaseInteractble.
void addVelocity (const Vec3D &velocity)
adds an increment to the velocity.
void addAngularVelocity (const Vec3D &angularVelocity)
add an increment to the angular velocity.
virtual const Vec3D & getVelocity () const
Returns the velocity of this interactable.
virtual const Vec3D & getAngularVelocity () const
Returns the angular velocity of this interactable.
void setPrescribedPosition (const std::function< Vec3D(double)> &prescribedPosition)
Allows the position of an infinite mass interactable to be prescribed.
void applyPrescribedPosition (double time)
Computes the position from the user defined prescribed position function.
void setPrescribedVelocity (const std::function< Vec3D(double)> &prescribedVelocity)
Allows the velocity of an infinite mass interactable to be prescribed.
void applyPrescribedVelocity (double time)
Computes the velocity from the user defined prescribed velocity function.
void setPrescribedOrientation (const std::function< Quaternion(double)> &prescribedOrientation)
Allows the orientation of the infinite mass interactbale to be prescribed.
void applyPrescribedOrientation (double time)
Computes the orientation from the user defined prescribed orientation function.
void setPrescribedAngularVelocity (const std::function< Vec3D(double)> &prescribedAngularVelocity)
Allows the angular velocity of the infinite mass interactable to be prescribed.
void applyPrescribedAngularVelocity (double time)
Computes the angular velocity from the user defined prescribed angular velocity.
virtual const Vec3D getVelocityAtContact (const Vec3D &contact) const
Returns the velocity at the contact point, use by many force laws.
void integrateBeforeForceComputation (double time, double timeStep)
This is part of integrate routine for objects with infinite mass.
void integrateAfterForceComputation (double time, double timeStep)
This is part of the integration routine for objects with infinite mass.
virtual Mdouble getInvMass () const
virtual Mdouble getCurvature (const Vec3D &labFixedCoordinates) const
virtual bool isFaceContact (const Vec3D &normal) const
Public Member Functions inherited from BaseObject
BaseObject ()=default
Default constructor.
BaseObject (const BaseObject &p)=default
Copy constructor, copies all the objects BaseObject contains.
virtual ~BaseObject ()=default
virtual destructor
virtual void moveInHandler (unsigned int index)
Except that it is virtual, it does the same thing as setIndex() does.
void setIndex (unsigned int index)
Allows one to assign an index to an object in the handler/container.
void setId (unsigned long id)
Assigns a unique identifier to each object in the handler (container) which remains constant even after the object is deleted from the container/handler.
unsigned int getIndex () const
Returns the index of the object in the handler.
unsigned int getId () const
Returns the unique identifier of any particular object.
void setGroupId (unsigned groupId)
unsigned getGroupId () const
Private Member Functions
void storeDebris (Vec3D P, const Vec3D &debris)
void processDebris ()
Private Attributes
std::vector< std::vector< Vec3D > > debris_
Additional Inherited Members
Static Public Member Functions inherited from BaseWall
static void addToVTK (const std::vector< Vec3D > &points, VTKContainer &vtk)
Takes the points provided and adds a triangle strip connecting these points to the vtk container.
Protected Attributes inherited from TriangulatedWall
std::vector< Vec3D > vertex_
std::vector< Face > face_
Constructor & Destructor Documentation
WearableTriangulatedWall() [1/3]
WearableTriangulatedWall::WearableTriangulatedWall ()
Default constructor.
 {
     logger(DEBUG, "WearableTriangulatedWall() constructed.");
 }
References DEBUG, and logger.
Referenced by copy().
WearableTriangulatedWall() [2/3]
WearableTriangulatedWall::WearableTriangulatedWall (const WearableTriangulatedWall & other)
Copy constructor.
Parameters
[in] other The WearableTriangulatedWall that must be copied.
         : TriangulatedWall(other)
 {
     debris_ = other.debris_;
 }
References debris_.
WearableTriangulatedWall() [3/3]
WearableTriangulatedWall::WearableTriangulatedWall (Mdouble lengthU, Mdouble lengthV, Mdouble resolutionU, Mdouble resolutionV)
Creates flat triangulated rectangle with certain resolution.
Parameters
lengthU Length in u-direction
lengthV Length in v-direction
resolutionU Max stepsize in u-direction
resolutionV Max stepsize in v-direction
     : TriangulatedWall()
 {
     // Make resolutions fit
     auto numU = static_cast<unsigned>(lengthU / resolutionU);
     if (lengthU / numU > resolutionU)
     {
         numU++;
         resolutionU = lengthU / numU;
     }
     auto numV = static_cast<unsigned>(lengthV / resolutionV);
     if (lengthV / numV > resolutionV)
     {
         numV++;
         resolutionV = lengthV / numV;
     }
     // Actual number of points is one more
     numU++;
     numV++;
     std::vector<Vec3D> points;
     std::vector<std::vector<unsigned>> cells;
     points.reserve(numU * numV);
     cells.reserve(2 * (numU - 1) * (numV - 1));
     for (unsigned j = 0; j < numV; j++)
     {
         for (unsigned i = 0; i < numU; i++)
         {
             Vec3D p = Vec3D(i * resolutionU, j * resolutionV, 0.0);
             points.push_back(p);
             if (i < numU - 1 && j < numV - 1)
             {
                 // Bottom left
                 unsigned baseIdx = i + j * numU;
                 // Bottom left, top left, top right (clockwise)
                 cells.push_back({baseIdx, baseIdx + numU, baseIdx + numU + 1});
                 // Bottom left, top right, bottom right (clockwise)
                 cells.push_back({baseIdx, baseIdx + numU + 1, baseIdx + 1});
             }
         }
     }
     TriangulatedWall::set(points, cells);
     // Initialize debris vector
     std::vector<Vec3D> temp0(3, Vec3D(0.0, 0.0, 0.0));
     std::vector<std::vector<Vec3D>> temp1(face_.size(), temp0);
     debris_ = temp1;
 }
References debris_, TriangulatedWall::face_, i, j, p, and TriangulatedWall::set().
~WearableTriangulatedWall()
WearableTriangulatedWall::~WearableTriangulatedWall () override
Destructor.
 {
     logger(DEBUG, "~WearableTriangulatedWall() has been called.");
 }
References DEBUG, and logger.
Member Function Documentation
computeWear()
void WearableTriangulatedWall::computeWear () override virtual
Reimplemented from BaseWall.
 {
     // Archard wear model, from https://en.wikipedia.org/wiki/Archard_equation
     // Q = KWL/H
     // Q is the total volume of wear debris produced
     // K is a dimensionless constant (typically mild wear 1e-8, severe wear 1e-2)
     // W is the total normal load
     // L is the sliding distance
     // H is the hardness of the softest contacting surfaces
     const Mdouble dt = getHandler()->getDPMBase()->getTimeStep();
     for (BaseInteraction* interaction : getInteractions())
     {
         // Ignore interactions from periodic particles. (Although it seems Q evaluates to 0 anyway (absolute normal force equals 0), but just to be sure)
         if (static_cast<BaseParticle*>(interaction->getP())->getPeriodicFromParticle() != nullptr)
             continue;
         Mdouble K = 1.0e-6; // For testing only, should be set by user
         Mdouble W = interaction->getAbsoluteNormalForce();
         // Pythagoras to get tangential magnitude from vector and normal magnitude
         Mdouble tangentialRelativeVelocity = std::sqrt(interaction->getRelativeVelocity().getLengthSquared() -
                                                        interaction->getNormalRelativeVelocity() * interaction->getNormalRelativeVelocity());
         Mdouble L = tangentialRelativeVelocity * dt;
         Mdouble H = 1.0; // For testing only, should be set by user
         Mdouble Q = K * W * L / H;
         storeDebris(interaction->getContactPoint(), interaction->getNormal() * -Q);
 //        storeDebris(interaction->getContactPoint(), Vec3D(0.0, 0.0, 1.0) * -Q);
     }
     if (!getInteractions().empty())
     {
         processDebris();
         // Reset debris to zero
         std::vector<Vec3D> temp0(3, Vec3D(0.0, 0.0, 0.0));
         std::fill(debris_.begin(), debris_.end(), temp0);
     }
 }
References debris_, BaseHandler< T >::getDPMBase(), BaseWall::getHandler(), BaseInteractable::getInteractions(), BaseParticle::getPeriodicFromParticle(), DPMBase::getTimeStep(), H, PlanarWave::K, L, processDebris(), Q, sqrt(), storeDebris(), and oomph::QuadTreeNames::W.
copy()
WearableTriangulatedWall * WearableTriangulatedWall::copy () const override virtual
Wall copy method. It calls the copy constructor of this Wall, useful for polymorphism.
Returns
pointer to a WearableTriangulatedWall object allocated using new.
Reimplemented from TriangulatedWall.
 {
     return new WearableTriangulatedWall(*this);
 }
References WearableTriangulatedWall().
Referenced by operator=().
getName()
std::string WearableTriangulatedWall::getName () const override virtual
Returns the name of the object, here the string "WearableTriangulatedWall".
Returns
The string "WearableTriangulatedWall".
Reimplemented from TriangulatedWall.
 {
     return "WearableTriangulatedWall";
 }
operator=()
WearableTriangulatedWall & WearableTriangulatedWall::operator= (const WearableTriangulatedWall & other)
Copy assignment operator.
Parameters
[in] other The WearableTriangulatedWall that must be copied.
 {
     logger(DEBUG, "WearableTriangulatedWall::operator= called.");
     if (this == &other)
     {
         return *this;
     }
     return *(other.copy());
 }
References copy(), DEBUG, and logger.
processDebris()
void WearableTriangulatedWall::processDebris () private
 {
     for (unsigned i = 0; i < face_.size(); i++)
     {
         *face_[i].vertex[0] += debris_[i][0];
         *face_[i].vertex[1] += debris_[i][1];
         *face_[i].vertex[2] += debris_[i][2];
     }
     //set normals and positions
     for (auto& face: face_)
     {
         face.normal = Vec3D::getUnitVector(
                 Vec3D::cross(*face.vertex[1] - *face.vertex[0], *face.vertex[2] - *face.vertex[0]));
     }
     //set edge normals (inwards facing)
     for (auto& face: face_)
     {
         face.edgeNormal[0] = Vec3D::getUnitVector(Vec3D::cross(face.normal, *face.vertex[1] - *face.vertex[0]));
         face.edgeNormal[1] = Vec3D::getUnitVector(Vec3D::cross(face.normal, *face.vertex[2] - *face.vertex[1]));
         face.edgeNormal[2] = Vec3D::getUnitVector(Vec3D::cross(face.normal, *face.vertex[0] - *face.vertex[2]));
     }
 }
References Vec3D::cross(), debris_, TriangulatedWall::face_, Vec3D::getUnitVector(), and i.
Referenced by computeWear().
read()
void WearableTriangulatedWall::read (std::istream & is) override virtual
Reads an WearableTriangulatedWall from an input stream, for example a restart file.
Parameters
[in] is The input stream from which the WearableTriangulatedWall is read, usually a restart file.
Reimplemented from TriangulatedWall.
 {
     TriangulatedWall::read(is);
 }
References TriangulatedWall::read().
storeDebris()
void WearableTriangulatedWall::storeDebris (Vec3D P, const Vec3D & debris) private
 {
     // Not sure if needed for triangulated wall?
 //    // Rotate global point back to local coordinate system.
 //    P -= getPosition();
 //    getOrientation().rotateBack(P);
     unsigned it = 0;
     for (auto& f : face_)
     {
         const Vec3D a = *f.vertex[0] - P;
         const Vec3D b = *f.vertex[1] - P;
         const Vec3D c = *f.vertex[2] - P;
         const Vec3D u = Vec3D::cross(b, c);
         const Vec3D v = Vec3D::cross(c, a);
         const Vec3D w = Vec3D::cross(a, b);
         // When all are pointing in same direction, the point is inside (or on edge of) the triangle.
         if (!(Vec3D::dot(u, v) < 0.0 || Vec3D::dot(u, w) < 0.0))
         {
             break;
         }
         it++;
     }
     // temporary because this should not happen
     if (it >= face_.size())
     {
 //        logger(INFO, "does this happen?");
         return;
     }
     // For now every vertex simply gets 1/3 of debris
     debris_[it][0] += debris / 3.0;
     debris_[it][1] += debris / 3.0;
     debris_[it][2] += debris / 3.0;
 }
References a, b, calibrate::c, Vec3D::cross(), debris_, Vec3D::dot(), f(), TriangulatedWall::face_, Global_Physical_Variables::P, v, and w.
Referenced by computeWear().
write()
void WearableTriangulatedWall::write (std::ostream & os) const override virtual
Writes an WearableTriangulatedWall to an output stream, for example a restart file.
Parameters
[in] os The output stream where the WearableTriangulatedWall must be written to, usually a restart file.
Reimplemented from TriangulatedWall.
 {
     TriangulatedWall::write(os);
 }
References TriangulatedWall::write().
Member Data Documentation
debris_
std::vector<std::vector<Vec3D> > WearableTriangulatedWall::debris_ private
Referenced by computeWear(), processDebris(), storeDebris(), and WearableTriangulatedWall().
The documentation for this class was generated from the following files:
WearableTriangulatedWall.h
WearableTriangulatedWall.cc