MercuryDPM: Eigen::internal::bytewise_bitwise_helper< T > Struct Template Reference
Eigen::internal::bytewise_bitwise_helper< T > Struct Template Reference
#include <GenericPacketMath.h>
Static Public Member Functions
static EIGEN_DEVICE_FUNC T bitwise_and (const T &a, const T &b)
static EIGEN_DEVICE_FUNC T bitwise_or (const T &a, const T &b)
static EIGEN_DEVICE_FUNC T bitwise_xor (const T &a, const T &b)
static EIGEN_DEVICE_FUNC T bitwise_not (const T &a)
Static Private Member Functions
template<typename Op >
static EIGEN_DEVICE_FUNC T unary (const T &a, Op op)
template<typename Op >
static EIGEN_DEVICE_FUNC T binary (const T &a, const T &b, Op op)
Member Function Documentation
binary()
template<typename T > template<typename Op > static EIGEN_DEVICE_FUNC T Eigen::internal::bytewise_bitwise_helper< T >::binary (const T & a, const T & b, Op op) inline static private
{
     const unsigned char* a_ptr = reinterpret_cast<const unsigned char*>(&a);
     const unsigned char* b_ptr = reinterpret_cast<const unsigned char*>(&b);
     T c;
     unsigned char* c_ptr = reinterpret_cast<unsigned char*>(&c);
     for (size_t i = 0; i < sizeof(T); ++i) {
       *c_ptr++ = op(*a_ptr++, *b_ptr++);
     }
     return c;
   }
References a, b, calibrate::c, i, and op.
Referenced by Eigen::internal::bytewise_bitwise_helper< T >::bitwise_and(), Eigen::internal::bytewise_bitwise_helper< T >::bitwise_or(), and Eigen::internal::bytewise_bitwise_helper< T >::bitwise_xor().
bitwise_and()
template<typename T > static EIGEN_DEVICE_FUNC T Eigen::internal::bytewise_bitwise_helper< T >::bitwise_and (const T & a, const T & b) inline static
{
     return binary(a, b, bit_and<unsigned char>());
   }
References a, b, and Eigen::internal::bytewise_bitwise_helper< T >::binary().
Referenced by Eigen::internal::pand().
bitwise_not()
template<typename T > static EIGEN_DEVICE_FUNC T Eigen::internal::bytewise_bitwise_helper< T >::bitwise_not (const T & a) inline static
 { return unary(a, bit_not<unsigned char>()); }
References a, and Eigen::internal::bytewise_bitwise_helper< T >::unary().
Referenced by Eigen::internal::pnot().
bitwise_or()
template<typename T > static EIGEN_DEVICE_FUNC T Eigen::internal::bytewise_bitwise_helper< T >::bitwise_or (const T & a, const T & b) inline static
 { return binary(a, b, bit_or<unsigned char>()); }
References a, b, and Eigen::internal::bytewise_bitwise_helper< T >::binary().
Referenced by Eigen::internal::por().
bitwise_xor()
template<typename T > static EIGEN_DEVICE_FUNC T Eigen::internal::bytewise_bitwise_helper< T >::bitwise_xor (const T & a, const T & b) inline static
{
     return binary(a, b, bit_xor<unsigned char>());
   }
References a, b, and Eigen::internal::bytewise_bitwise_helper< T >::binary().
Referenced by Eigen::internal::pxor().
unary()
template<typename T > template<typename Op > static EIGEN_DEVICE_FUNC T Eigen::internal::bytewise_bitwise_helper< T >::unary (const T & a, Op op) inline static private
{
     const unsigned char* a_ptr = reinterpret_cast<const unsigned char*>(&a);
     T c;
     unsigned char* c_ptr = reinterpret_cast<unsigned char*>(&c);
     for (size_t i = 0; i < sizeof(T); ++i) {
       *c_ptr++ = op(*a_ptr++);
     }
     return c;
   }
References a, calibrate::c, i, and op.
Referenced by Eigen::internal::bytewise_bitwise_helper< T >::bitwise_not().
The documentation for this struct was generated from the following file:
GenericPacketMath.h