MercuryDPM: oomph::OomphInfo Class Reference
oomph::OomphInfo Class Reference
#include <oomph_definitions.h>
Public Member Functions
OomphInfo ()
template<class _Tp >
std::ostream & operator<< (_Tp argument)
std::ostream *& stream_pt ()
Access function for the stream pointer.
std::ostream & operator<< (std::ostream &(*f)(std::ostream &))
Overload insertor to handle stream modifiers.
OutputModifier *& output_modifier_pt ()
Access function for the output modifier pointer.
Private Attributes
std::ostream * Stream_pt
Pointer to the output stream – defaults to std::cout.
OutputModifier * Output_modifier_pt
Pointer to the output modifier object – defaults to no modification.
Detailed Description
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// This class is a wrapper to a stream and an output modifier that is used to control the "info" output from OomphLib. Its instationiation can be used like std::cout.
Constructor & Destructor Documentation
OomphInfo()
oomph::OomphInfo::OomphInfo () inline
Set default values for the output stream (cout) and modifier (no modification)
       : Stream_pt(&std::cout), Output_modifier_pt(&default_output_modifier)
     {
     }
Member Function Documentation
operator<<() [1/2]
template<class _Tp > std::ostream& oomph::OomphInfo::operator<< (_Tp argument) inline
Overload the << operator, writing output to the stream addressed by Stream_pt and calling the function defined by the object addressed by Output_modifier_pt
     {
       // If the Output_modifer function returns true
       // echo the argument to the stream and return the (vanilla) stream
       if ((*Output_modifier_pt)(*Stream_pt))
       {
         *Stream_pt << argument;
         return (*Stream_pt);
       }
       // Otherwise return the null stream (suppress all future output)
       return oomph_nullstream;
     }
References oomph::oomph_nullstream, and GlobalParameters::Stream_pt.
operator<<() [2/2]
std::ostream& oomph::OomphInfo::operator<< (std::ostream &(*)(std::ostream &) f) inline
Overload insertor to handle stream modifiers.
     {
       return f(*Stream_pt);
     }
References f(), and GlobalParameters::Stream_pt.
output_modifier_pt()
OutputModifier*& oomph::OomphInfo::output_modifier_pt () inline
Access function for the output modifier pointer.
     {
       return Output_modifier_pt;
     }
Referenced by oomph::MPI_Helpers::init(), and main().
stream_pt()
std::ostream*& oomph::OomphInfo::stream_pt () inline
Access function for the stream pointer.
     {
       return Stream_pt;
     }
References GlobalParameters::Stream_pt.
Referenced by PMLStructuredCubicHelmholtz< ELEMENT >::apply_boundary_conditions(), oomph::BlackBoxFDNewtonSolver::black_box_fd_newton_solve(), oomph::MGSolver< DIM >::disable_output(), oomph::HelmholtzMGPreconditioner< DIM >::disable_output(), main(), oomph::HelmholtzMGPreconditioner< DIM >::preconditioner_solve(), oomph::MGPreconditioner< DIM >::preconditioner_solve(), oomph::BlockDiagonalPreconditioner< MATRIX >::setup(), oomph::BlockTriangularPreconditioner< MATRIX >::setup(), oomph::MGPreconditioner< DIM >::setup(), oomph::HelmholtzMGPreconditioner< DIM >::setup(), oomph::ExactDGPBlockPreconditioner< MATRIX >::setup(), oomph::BandedBlockTriangularPreconditioner< MATRIX >::setup(), oomph::SpaceTimeNavierStokesSubsidiaryPreconditioner::setup(), oomph::GMRESBlockPreconditioner::setup(), and oomph::MGSolver< DIM >::solve().
Member Data Documentation
Output_modifier_pt
OutputModifier* oomph::OomphInfo::Output_modifier_pt private
Pointer to the output modifier object – defaults to no modification.
Stream_pt
std::ostream* oomph::OomphInfo::Stream_pt private
Pointer to the output stream – defaults to std::cout.
The documentation for this class was generated from the following file:
oomph_definitions.h