MercuryDPM: check_sqrt_impl< std::complex< T > > Struct Template Reference
check_sqrt_impl< std::complex< T > > Struct Template Reference
Static Public Member Functions
static void run ()
Member Function Documentation
run()
template<typename T > static void check_sqrt_impl< std::complex< T > >::run () inline static
                     {
     typedef typename std::complex<T> ComplexT;
     for (int i = 0; i < 1000; ++i) {
       const ComplexT x = internal::random<ComplexT>();
       const ComplexT sqrtx = numext::sqrt(x);
       VERIFY_IS_APPROX(sqrtx * sqrtx, x);
     }
     // Corner cases.
     const T zero = T(0);
     const T one = T(1);
     const T inf = std::numeric_limits<T>::infinity();
     const T nan = std::numeric_limits<T>::quiet_NaN();
     // Set of corner cases from https://en.cppreference.com/w/cpp/numeric/complex/sqrt
     const int kNumCorners = 20;
     const ComplexT corners[kNumCorners][2] = {
         {ComplexT(zero, zero), ComplexT(zero, zero)},  {ComplexT(-zero, zero), ComplexT(zero, zero)},
         {ComplexT(zero, -zero), ComplexT(zero, zero)}, {ComplexT(-zero, -zero), ComplexT(zero, zero)},
         {ComplexT(one, inf), ComplexT(inf, inf)},      {ComplexT(nan, inf), ComplexT(inf, inf)},
         {ComplexT(one, -inf), ComplexT(inf, -inf)},    {ComplexT(nan, -inf), ComplexT(inf, -inf)},
         {ComplexT(-inf, one), ComplexT(zero, inf)},    {ComplexT(inf, one), ComplexT(inf, zero)},
         {ComplexT(-inf, -one), ComplexT(zero, -inf)},  {ComplexT(inf, -one), ComplexT(inf, -zero)},
         {ComplexT(-inf, nan), ComplexT(nan, inf)},     {ComplexT(inf, nan), ComplexT(inf, nan)},
         {ComplexT(zero, nan), ComplexT(nan, nan)},     {ComplexT(one, nan), ComplexT(nan, nan)},
         {ComplexT(nan, zero), ComplexT(nan, nan)},     {ComplexT(nan, one), ComplexT(nan, nan)},
         {ComplexT(nan, -one), ComplexT(nan, nan)},     {ComplexT(nan, nan), ComplexT(nan, nan)},
     };
     for (int i = 0; i < kNumCorners; ++i) {
       const ComplexT& x = corners[i][0];
       const ComplexT sqrtx = corners[i][1];
       VERIFY_IS_EQUAL_OR_NANS(numext::sqrt(x), sqrtx);
     }
   }
References corners(), i, constants::inf, sqrt(), VERIFY_IS_APPROX, VERIFY_IS_EQUAL_OR_NANS, plotDoE::x, and zero().
The documentation for this struct was generated from the following file:
numext.cpp