MercuryDPM: oomph::TElement2BulkCoordinateDerivatives Namespace Reference
oomph::TElement2BulkCoordinateDerivatives Namespace Reference
Functions
void face0 (const Vector< double > &s, DenseMatrix< double > &dsbulk_dsface, unsigned &interior_direction)
Function for the "left" face along which s0 is fixed.
void face1 (const Vector< double > &s, DenseMatrix< double > &dsbulk_dsface, unsigned &interior_direction)
Function for the "bottom" face along which s1 is fixed.
void face2 (const Vector< double > &s, DenseMatrix< double > &dsbulk_dsface, unsigned &interior_direction)
Function for the sloping face.
Detailed Description
Namespace for helper functions that calculate derivatives of the local coordinates in the bulk elements wrt the local coordinates in the face element.
Function Documentation
face0()
void oomph::TElement2BulkCoordinateDerivatives::face0 (const Vector< double > & s, DenseMatrix< double > & dsbulk_dsface, unsigned & interior_direction)
Function for the "left" face along which s0 is fixed.
     {
       // Bulk coordinate s[0] does not vary along the face
       dsbulk_dsface(0, 0) = 0.0;
       // Bulk coordinate s[1] is the face coordinate
       dsbulk_dsface(1, 0) = 1.0;
       // The interior direction is given by s[0]
       interior_direction = 0;
     }
Referenced by oomph::TElement< 2, NNODE_1D >::build_face_element().
face1()
void oomph::TElement2BulkCoordinateDerivatives::face1 (const Vector< double > & s, DenseMatrix< double > & dsbulk_dsface, unsigned & interior_direction)
Function for the "bottom" face along which s1 is fixed.
     {
       // Bulk coordinate s[0] is the face coordinate
       dsbulk_dsface(0, 0) = 1.0;
       // Bulk coordinate s[1] does not vary along the face
       dsbulk_dsface(1, 0) = 0.0;
       // The interior direction is given by s[1]
       interior_direction = 1;
     }
Referenced by oomph::TElement< 2, NNODE_1D >::build_face_element().
face2()
void oomph::TElement2BulkCoordinateDerivatives::face2 (const Vector< double > & s, DenseMatrix< double > & dsbulk_dsface, unsigned & interior_direction)
Function for the sloping face.
     {
       // Bulk coordinate s[0] decreases along the face
       dsbulk_dsface(0, 0) = -1.0;
       // Bulk coordinate s[1] increases along the face
       dsbulk_dsface(1, 0) = 1.0;
       // The interior direction is given by s[0] (or s[1])
       interior_direction = 0;
     }
Referenced by oomph::TElement< 2, NNODE_1D >::build_face_element().