MercuryDPM: Eigen::internal::visitor_evaluator< XprType > Class Template Reference
Eigen::internal::visitor_evaluator< XprType > Class Template Reference
#include <Visitor.h>
Public Types
typedef evaluator< XprType > Evaluator
typedef XprType::Scalar Scalar
using Packet = typename packet_traits< Scalar >::type
typedef std::remove_const_t< typename XprType::CoeffReturnType > CoeffReturnType
Public Member Functions
EIGEN_DEVICE_FUNC visitor_evaluator (const XprType &xpr)
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index size () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index row, Index col) const
template<typename Packet , int Alignment = Unaligned>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet packet (Index row, Index col) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
template<typename Packet , int Alignment = XprAlignment>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet packet (Index index) const
Static Public Attributes
static constexpr bool PacketAccess = static_cast<bool>(Evaluator::Flags & PacketAccessBit)
static constexpr bool LinearAccess = static_cast<bool>(Evaluator::Flags & LinearAccessBit)
static constexpr bool IsRowMajor = static_cast<bool>(XprType::IsRowMajor)
static constexpr int RowsAtCompileTime = XprType::RowsAtCompileTime
static constexpr int ColsAtCompileTime = XprType::ColsAtCompileTime
static constexpr int XprAlignment = Evaluator::Alignment
static constexpr int CoeffReadCost = Evaluator::CoeffReadCost
Protected Attributes
Evaluator m_evaluator
const XprType & m_xpr
Member Typedef Documentation
CoeffReturnType
template<typename XprType > typedef std::remove_const_t<typename XprType::CoeffReturnType> Eigen::internal::visitor_evaluator< XprType >::CoeffReturnType
Evaluator
template<typename XprType > typedef evaluator<XprType> Eigen::internal::visitor_evaluator< XprType >::Evaluator
Packet
template<typename XprType > using Eigen::internal::visitor_evaluator< XprType >::Packet = typename packet_traits<Scalar>::type
Scalar
template<typename XprType > typedef XprType::Scalar Eigen::internal::visitor_evaluator< XprType >::Scalar
Constructor & Destructor Documentation
visitor_evaluator()
template<typename XprType > EIGEN_DEVICE_FUNC Eigen::internal::visitor_evaluator< XprType >::visitor_evaluator (const XprType & xpr) inline explicit
 : m_evaluator(xpr), m_xpr(xpr) {}
Member Function Documentation
coeff() [1/2]
template<typename XprType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::visitor_evaluator< XprType >::coeff (Index index) const inline
 { return m_evaluator.coeff(index); }
References Eigen::internal::visitor_evaluator< XprType >::m_evaluator.
coeff() [2/2]
template<typename XprType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::visitor_evaluator< XprType >::coeff (Index row, Index col) const inline
{
     return m_evaluator.coeff(row, col);
   }
References col(), Eigen::internal::visitor_evaluator< XprType >::m_evaluator, and row().
cols()
template<typename XprType > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::internal::visitor_evaluator< XprType >::cols () const inline
 { return m_xpr.cols(); }
References Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::cols(), and Eigen::internal::visitor_evaluator< XprType >::m_xpr.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
packet() [1/2]
template<typename XprType > template<typename Packet , int Alignment = XprAlignment> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet Eigen::internal::visitor_evaluator< XprType >::packet (Index index) const inline
{
     return m_evaluator.template packet<Alignment, Packet>(index);
   }
References Eigen::internal::visitor_evaluator< XprType >::m_evaluator.
packet() [2/2]
template<typename XprType > template<typename Packet , int Alignment = Unaligned> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet Eigen::internal::visitor_evaluator< XprType >::packet (Index row, Index col) const inline
{
     return m_evaluator.template packet<Alignment, Packet>(row, col);
   }
References col(), Eigen::internal::visitor_evaluator< XprType >::m_evaluator, and row().
rows()
template<typename XprType > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::internal::visitor_evaluator< XprType >::rows () const inline
 { return m_xpr.rows(); }
References Eigen::internal::visitor_evaluator< XprType >::m_xpr, and Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::rows().
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
size()
template<typename XprType > EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::internal::visitor_evaluator< XprType >::size () const inline
 { return m_xpr.size(); }
References Eigen::internal::visitor_evaluator< XprType >::m_xpr.
Member Data Documentation
CoeffReadCost
template<typename XprType > constexpr int Eigen::internal::visitor_evaluator< XprType >::CoeffReadCost = Evaluator::CoeffReadCost static constexpr
ColsAtCompileTime
template<typename XprType > constexpr int Eigen::internal::visitor_evaluator< XprType >::ColsAtCompileTime = XprType::ColsAtCompileTime static constexpr
IsRowMajor
template<typename XprType > constexpr bool Eigen::internal::visitor_evaluator< XprType >::IsRowMajor = static_cast<bool>(XprType::IsRowMajor) static constexpr
LinearAccess
template<typename XprType > constexpr bool Eigen::internal::visitor_evaluator< XprType >::LinearAccess = static_cast<bool>(Evaluator::Flags & LinearAccessBit) static constexpr
m_evaluator
template<typename XprType > Evaluator Eigen::internal::visitor_evaluator< XprType >::m_evaluator protected
Referenced by Eigen::internal::visitor_evaluator< XprType >::coeff(), and Eigen::internal::visitor_evaluator< XprType >::packet().
m_xpr
template<typename XprType > const XprType& Eigen::internal::visitor_evaluator< XprType >::m_xpr protected
Referenced by Eigen::internal::visitor_evaluator< XprType >::cols(), Eigen::internal::visitor_evaluator< XprType >::rows(), and Eigen::internal::visitor_evaluator< XprType >::size().
PacketAccess
template<typename XprType > constexpr bool Eigen::internal::visitor_evaluator< XprType >::PacketAccess = static_cast<bool>(Evaluator::Flags & PacketAccessBit) static constexpr
RowsAtCompileTime
template<typename XprType > constexpr int Eigen::internal::visitor_evaluator< XprType >::RowsAtCompileTime = XprType::RowsAtCompileTime static constexpr
XprAlignment
template<typename XprType > constexpr int Eigen::internal::visitor_evaluator< XprType >::XprAlignment = Evaluator::Alignment static constexpr
The documentation for this class was generated from the following file:
Visitor.h