MercuryDPM: Eigen::TensorEvaluator< const TensorRef< Derived >, Device > Struct Template Reference
Eigen::TensorEvaluator< const TensorRef< Derived >, Device > Struct Template Reference
#include <TensorRef.h>
Public Types
enum {
IsAligned = false , PacketAccess = false , BlockAccess = false , PreferBlockAccess = false ,
CoordAccess = false , RawAccess = false
}
typedef Derived::Index Index
typedef Derived::Scalar Scalar
typedef Derived::Scalar CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef Derived::Dimensions Dimensions
typedef StorageMemory< CoeffReturnType, Device > Storage
typedef Storage::Type EvaluatorPointerType
typedef internal::TensorBlockNotImplemented TensorBlock
Public Member Functions
EIGEN_STRONG_INLINE TensorEvaluator (const TensorRef< Derived > &m, const Device &)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions & dimensions () const
EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (EvaluatorPointerType)
EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index index)
EIGEN_DEVICE_FUNC const Scalar * data () const
Static Public Attributes
static constexpr int Layout = TensorRef<Derived>::Layout
Protected Attributes
TensorRef< Derived > m_ref
Member Typedef Documentation
CoeffReturnType
template<typename Derived , typename Device > typedef Derived::Scalar Eigen::TensorEvaluator< const TensorRef< Derived >, Device >::CoeffReturnType
Dimensions
template<typename Derived , typename Device > typedef Derived::Dimensions Eigen::TensorEvaluator< const TensorRef< Derived >, Device >::Dimensions
EvaluatorPointerType
template<typename Derived , typename Device > typedef Storage::Type Eigen::TensorEvaluator< const TensorRef< Derived >, Device >::EvaluatorPointerType
Index
template<typename Derived , typename Device > typedef Derived::Index Eigen::TensorEvaluator< const TensorRef< Derived >, Device >::Index
PacketReturnType
template<typename Derived , typename Device > typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorEvaluator< const TensorRef< Derived >, Device >::PacketReturnType
Scalar
template<typename Derived , typename Device > typedef Derived::Scalar Eigen::TensorEvaluator< const TensorRef< Derived >, Device >::Scalar
Storage
template<typename Derived , typename Device > typedef StorageMemory<CoeffReturnType, Device> Eigen::TensorEvaluator< const TensorRef< Derived >, Device >::Storage
TensorBlock
template<typename Derived , typename Device > typedef internal::TensorBlockNotImplemented Eigen::TensorEvaluator< const TensorRef< Derived >, Device >::TensorBlock
Member Enumeration Documentation
anonymous enum
template<typename Derived , typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
BlockAccess
PreferBlockAccess
CoordAccess
RawAccess
        {
     IsAligned = false,
     PacketAccess = false,
     BlockAccess = false,
     PreferBlockAccess = false,
     CoordAccess = false,  // to be implemented
     RawAccess = false
   };
Constructor & Destructor Documentation
TensorEvaluator()
template<typename Derived , typename Device > EIGEN_STRONG_INLINE Eigen::TensorEvaluator< const TensorRef< Derived >, Device >::TensorEvaluator (const TensorRef< Derived > & m, const Device &) inline
 : m_ref(m) {}
Member Function Documentation
cleanup()
template<typename Derived , typename Device > EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorRef< Derived >, Device >::cleanup () inline
 {}
Referenced by framework.Frame::__init__().
coeff()
template<typename Derived , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::TensorEvaluator< const TensorRef< Derived >, Device >::coeff (Index index) const inline
 { return m_ref.coeff(index); }
coeffRef()
template<typename Derived , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::TensorEvaluator< const TensorRef< Derived >, Device >::coeffRef (Index index) inline
 { return m_ref.coeffRef(index); }
data()
template<typename Derived , typename Device > EIGEN_DEVICE_FUNC const Scalar* Eigen::TensorEvaluator< const TensorRef< Derived >, Device >::data () const inline
 { return m_ref.data(); }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
dimensions()
template<typename Derived , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions& Eigen::TensorEvaluator< const TensorRef< Derived >, Device >::dimensions () const inline
 { return m_ref.dimensions(); }
evalSubExprsIfNeeded()
template<typename Derived , typename Device > EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorRef< Derived >, Device >::evalSubExprsIfNeeded (EvaluatorPointerType) inline
 { return true; }
Member Data Documentation
Layout
template<typename Derived , typename Device > constexpr int Eigen::TensorEvaluator< const TensorRef< Derived >, Device >::Layout = TensorRef<Derived>::Layout static constexpr
m_ref
template<typename Derived , typename Device > TensorRef<Derived> Eigen::TensorEvaluator< const TensorRef< Derived >, Device >::m_ref protected
The documentation for this struct was generated from the following file:
TensorRef.h