MercuryDPM: FreeFallRestart.cpp File Reference
FreeFallRestart.cpp File Reference
#include "DPMBase.h"
#include "Walls/InfiniteWall.h"
#include "Species/LinearViscoelasticSpecies.h"
Classes
class FreeFall
This code is a example on how to write a restartable mercury code.
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
Start off my solving the default problem
 {
     FreeFall dpm;
     //set FreeFall-specific parameters here
     dpm.setName("FreeFallRestart");
     dpm.setSaveCount(1000);
     dpm.setTimeStep(1e-6);
     dpm.setTimeMax(0.5);
     dpm.setDomain(Vec3D(-1e-3,-1e-3,0e-3),Vec3D(1e-3,1e-3,10e-3));
     dpm.setGravity(Vec3D(0,0,-9.8));
     //restart and run until final time 1, using command line arguments:
     // ./freeFallRestart -r -tmax 1
     dpm.solve(argc,argv);
     return 0;
 }
References e(), DPMBase::setDomain(), DPMBase::setGravity(), DPMBase::setName(), DPMBase::setSaveCount(), DPMBase::setTimeMax(), DPMBase::setTimeStep(), and DPMBase::solve().