MercuryDPM: Eigen::TensorEvaluator< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device > Struct Template Reference
Eigen::TensorEvaluator< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device > Struct Template Reference
#include <TensorMorphing.h>
Public Types
enum {
IsAligned = false , PacketAccess = false , BlockAccess = false , PreferBlockAccess = TensorEvaluator<ArgType, Device>::PreferBlockAccess ,
RawAccess = false
}
typedef TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType > XprType
typedef XprType::Index Index
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef StorageMemory< CoeffReturnType, Device > Storage
typedef Storage::Type EvaluatorPointerType
typedef Strides Dimensions
typedef internal::TensorBlockNotImplemented TensorBlock
Public Member Functions
EIGEN_STRONG_INLINE TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions & dimensions () const
EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (EvaluatorPointerType)
EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Storage::Type data () const
Static Public Attributes
static constexpr int NumDims = internal::array_size<Strides>::value
static constexpr int Layout = TensorEvaluator<ArgType, Device>::Layout
Protected Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index srcCoeff (Index index) const
Static Protected Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index clamp (Index value, Index min, Index max)
Protected Attributes
array< Index, NumDims > m_outputStrides
array< internal::TensorIntDivisor< Index >, NumDims > m_fastOutputStrides
array< Index, NumDims > m_inputStrides
bool m_is_identity
TensorEvaluator< ArgType, Device > m_impl
const Device EIGEN_DEVICE_REF m_device
DSizes< Index, NumDims > m_startIndices
DSizes< Index, NumDims > m_dimensions
DSizes< Index, NumDims > m_offsets
const Strides m_strides
Member Typedef Documentation
CoeffReturnType
template<typename StartIndices , typename StopIndices , typename Strides , typename ArgType , typename Device > typedef XprType::CoeffReturnType Eigen::TensorEvaluator< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device >::CoeffReturnType
Dimensions
template<typename StartIndices , typename StopIndices , typename Strides , typename ArgType , typename Device > typedef Strides Eigen::TensorEvaluator< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device >::Dimensions
EvaluatorPointerType
template<typename StartIndices , typename StopIndices , typename Strides , typename ArgType , typename Device > typedef Storage::Type Eigen::TensorEvaluator< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device >::EvaluatorPointerType
Index
template<typename StartIndices , typename StopIndices , typename Strides , typename ArgType , typename Device > typedef XprType::Index Eigen::TensorEvaluator< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device >::Index
PacketReturnType
template<typename StartIndices , typename StopIndices , typename Strides , typename ArgType , typename Device > typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorEvaluator< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device >::PacketReturnType
Scalar
template<typename StartIndices , typename StopIndices , typename Strides , typename ArgType , typename Device > typedef XprType::Scalar Eigen::TensorEvaluator< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device >::Scalar
Storage
template<typename StartIndices , typename StopIndices , typename Strides , typename ArgType , typename Device > typedef StorageMemory<CoeffReturnType, Device> Eigen::TensorEvaluator< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device >::Storage
TensorBlock
template<typename StartIndices , typename StopIndices , typename Strides , typename ArgType , typename Device > typedef internal::TensorBlockNotImplemented Eigen::TensorEvaluator< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device >::TensorBlock
XprType
template<typename StartIndices , typename StopIndices , typename Strides , typename ArgType , typename Device > typedef TensorStridingSlicingOp<StartIndices, StopIndices, Strides, ArgType> Eigen::TensorEvaluator< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device >::XprType
Member Enumeration Documentation
anonymous enum
template<typename StartIndices , typename StopIndices , typename Strides , typename ArgType , typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
BlockAccess
PreferBlockAccess
RawAccess
        {
     // Alignment can't be guaranteed at compile time since it depends on the
     // slice offsets and sizes.
     IsAligned = false,
     PacketAccess = false,
     BlockAccess = false,
     PreferBlockAccess = TensorEvaluator<ArgType, Device>::PreferBlockAccess,
     RawAccess = false
   };
Constructor & Destructor Documentation
TensorEvaluator()
template<typename StartIndices , typename StopIndices , typename Strides , typename ArgType , typename Device > EIGEN_STRONG_INLINE Eigen::TensorEvaluator< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device >::TensorEvaluator (const XprType & op, const Device & device) inline
       : m_impl(op.expression(), device), m_device(device), m_strides(op.strides()) {
     // Handle degenerate intervals by gracefully clamping and allowing m_dimensions to be zero
     DSizes<Index, NumDims> startIndicesClamped, stopIndicesClamped;
     for (ptrdiff_t i = 0; i < internal::array_size<Dimensions>::value; ++i) {
       eigen_assert(m_strides[i] != 0 && "0 stride is invalid");
       if (m_strides[i] > 0) {
         startIndicesClamped[i] = clamp(op.startIndices()[i], 0, m_impl.dimensions()[i]);
         stopIndicesClamped[i] = clamp(op.stopIndices()[i], 0, m_impl.dimensions()[i]);
       } else {
         /* implies m_strides[i] < 0 by assert */
         startIndicesClamped[i] = clamp(op.startIndices()[i], -1, m_impl.dimensions()[i] - 1);
         stopIndicesClamped[i] = clamp(op.stopIndices()[i], -1, m_impl.dimensions()[i] - 1);
       }
       m_startIndices[i] = startIndicesClamped[i];
     }
     typedef typename TensorEvaluator<ArgType, Device>::Dimensions InputDimensions;
     const InputDimensions& input_dims = m_impl.dimensions();
     // compute output tensor shape
     m_is_identity = true;
     for (int i = 0; i < NumDims; i++) {
       Index interval = stopIndicesClamped[i] - startIndicesClamped[i];
       if (interval == 0 || ((interval < 0) != (m_strides[i] < 0))) {
         m_dimensions[i] = 0;
       } else {
         m_dimensions[i] = (interval / m_strides[i]) + (interval % m_strides[i] != 0 ? 1 : 0);
         eigen_assert(m_dimensions[i] >= 0);
       }
       if (m_strides[i] != 1 || interval != m_impl.dimensions()[i]) {
         m_is_identity = false;
       }
     }
     Strides output_dims = m_dimensions;
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       m_inputStrides[0] = m_strides[0];
       m_offsets[0] = startIndicesClamped[0];
       Index previousDimProduct = 1;
       for (int i = 1; i < NumDims; ++i) {
         previousDimProduct *= input_dims[i - 1];
         m_inputStrides[i] = previousDimProduct * m_strides[i];
         m_offsets[i] = startIndicesClamped[i] * previousDimProduct;
       }
       // Don't initialize m_fastOutputStrides[0] since it won't ever be accessed.
       m_outputStrides[0] = 1;
       for (int i = 1; i < NumDims; ++i) {
         m_outputStrides[i] = m_outputStrides[i - 1] * output_dims[i - 1];
         m_fastOutputStrides[i] = internal::TensorIntDivisor<Index>(m_outputStrides[i] > 0 ? m_outputStrides[i] : 1);
       }
     } else {
       m_inputStrides[NumDims - 1] = m_strides[NumDims - 1];
       m_offsets[NumDims - 1] = startIndicesClamped[NumDims - 1];
       Index previousDimProduct = 1;
       for (int i = NumDims - 2; i >= 0; --i) {
         previousDimProduct *= input_dims[i + 1];
         m_inputStrides[i] = previousDimProduct * m_strides[i];
         m_offsets[i] = startIndicesClamped[i] * previousDimProduct;
       }
       m_outputStrides[NumDims - 1] = 1;
       for (int i = NumDims - 2; i >= 0; --i) {
         m_outputStrides[i] = m_outputStrides[i + 1] * output_dims[i + 1];
         m_fastOutputStrides[i] = internal::TensorIntDivisor<Index>(m_outputStrides[i] > 0 ? m_outputStrides[i] : 1);
       }
     }
   }
References Eigen::ColMajor, Eigen::TensorEvaluator< Derived, Device >::dimensions(), eigen_assert, i, Eigen::TensorEvaluator< Derived, Device >::Layout, op, and Eigen::value.
Member Function Documentation
clamp()
template<typename StartIndices , typename StopIndices , typename Strides , typename ArgType , typename Device > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device >::clamp (Index value, Index min, Index max) inline static protected
{
 #ifndef SYCL_DEVICE_ONLY
     return numext::maxi(min, numext::mini(max, value));
 #else
     return cl::sycl::clamp(value, min, max);
 #endif
   }
References Eigen::max(), Eigen::numext::maxi(), Eigen::min(), Eigen::numext::mini(), and Eigen::value.
cleanup()
template<typename StartIndices , typename StopIndices , typename Strides , typename ArgType , typename Device > EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device >::cleanup () inline
 { m_impl.cleanup(); }
Referenced by framework.Frame::__init__().
coeff()
template<typename StartIndices , typename StopIndices , typename Strides , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::TensorEvaluator< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device >::coeff (Index index) const inline
{
     if (m_is_identity) {
       return m_impl.coeff(index);
     } else {
       return m_impl.coeff(srcCoeff(index));
     }
   }
costPerCoeff()
template<typename StartIndices , typename StopIndices , typename Strides , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorEvaluator< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device >::costPerCoeff (bool vectorized) const inline
{
     return m_impl.costPerCoeff(vectorized) + TensorOpCost(0, 0, m_is_identity ? 1 : NumDims);
   }
data()
template<typename StartIndices , typename StopIndices , typename Strides , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Storage::Type Eigen::TensorEvaluator< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device >::data () const inline
 { return NULL; }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
dimensions()
template<typename StartIndices , typename StopIndices , typename Strides , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions& Eigen::TensorEvaluator< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device >::dimensions () const inline
 { return m_dimensions; }
evalSubExprsIfNeeded()
template<typename StartIndices , typename StopIndices , typename Strides , typename ArgType , typename Device > EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device >::evalSubExprsIfNeeded (EvaluatorPointerType) inline
{
     m_impl.evalSubExprsIfNeeded(NULL);
     return true;
   }
srcCoeff()
template<typename StartIndices , typename StopIndices , typename Strides , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index Eigen::TensorEvaluator< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device >::srcCoeff (Index index) const inline protected
{
     Index inputIndex = 0;
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       EIGEN_UNROLL_LOOP
       for (int i = NumDims - 1; i >= 0; --i) {
         const Index idx = index / m_fastOutputStrides[i];
         inputIndex += idx * m_inputStrides[i] + m_offsets[i];
         index -= idx * m_outputStrides[i];
       }
     } else {
       EIGEN_UNROLL_LOOP
       for (int i = 0; i < NumDims; ++i) {
         const Index idx = index / m_fastOutputStrides[i];
         inputIndex += idx * m_inputStrides[i] + m_offsets[i];
         index -= idx * m_outputStrides[i];
       }
     }
     return inputIndex;
   }
References Eigen::ColMajor, EIGEN_UNROLL_LOOP, i, and Eigen::TensorEvaluator< Derived, Device >::Layout.
Member Data Documentation
Layout
template<typename StartIndices , typename StopIndices , typename Strides , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device >::Layout = TensorEvaluator<ArgType, Device>::Layout static constexpr
m_device
template<typename StartIndices , typename StopIndices , typename Strides , typename ArgType , typename Device > const Device EIGEN_DEVICE_REF Eigen::TensorEvaluator< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device >::m_device protected
m_dimensions
template<typename StartIndices , typename StopIndices , typename Strides , typename ArgType , typename Device > DSizes<Index, NumDims> Eigen::TensorEvaluator< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device >::m_dimensions protected
m_fastOutputStrides
template<typename StartIndices , typename StopIndices , typename Strides , typename ArgType , typename Device > array<internal::TensorIntDivisor<Index>, NumDims> Eigen::TensorEvaluator< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device >::m_fastOutputStrides protected
m_impl
template<typename StartIndices , typename StopIndices , typename Strides , typename ArgType , typename Device > TensorEvaluator<ArgType, Device> Eigen::TensorEvaluator< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device >::m_impl protected
m_inputStrides
template<typename StartIndices , typename StopIndices , typename Strides , typename ArgType , typename Device > array<Index, NumDims> Eigen::TensorEvaluator< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device >::m_inputStrides protected
m_is_identity
template<typename StartIndices , typename StopIndices , typename Strides , typename ArgType , typename Device > bool Eigen::TensorEvaluator< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device >::m_is_identity protected
m_offsets
template<typename StartIndices , typename StopIndices , typename Strides , typename ArgType , typename Device > DSizes<Index, NumDims> Eigen::TensorEvaluator< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device >::m_offsets protected
m_outputStrides
template<typename StartIndices , typename StopIndices , typename Strides , typename ArgType , typename Device > array<Index, NumDims> Eigen::TensorEvaluator< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device >::m_outputStrides protected
m_startIndices
template<typename StartIndices , typename StopIndices , typename Strides , typename ArgType , typename Device > DSizes<Index, NumDims> Eigen::TensorEvaluator< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device >::m_startIndices protected
m_strides
template<typename StartIndices , typename StopIndices , typename Strides , typename ArgType , typename Device > const Strides Eigen::TensorEvaluator< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device >::m_strides protected
NumDims
template<typename StartIndices , typename StopIndices , typename Strides , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorStridingSlicingOp< StartIndices, StopIndices, Strides, ArgType >, Device >::NumDims = internal::array_size<Strides>::value static constexpr
The documentation for this struct was generated from the following file:
TensorMorphing.h