MercuryDPM: Eigen::internal::nearest_integer_packetop_impl< Packet, false, false > Struct Template Reference
Eigen::internal::nearest_integer_packetop_impl< Packet, false, false > Struct Template Reference
#include <GenericPacketMathFunctions.h>
Public Types
using Scalar = typename unpacket_traits< Packet >::type
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet run_floor (const Packet &x)
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet run_ceil (const Packet &x)
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet run_rint (const Packet &x)
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet run_round (const Packet &x)
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet run_trunc (const Packet &x)
Member Typedef Documentation
Scalar
template<typename Packet > using Eigen::internal::nearest_integer_packetop_impl< Packet, false, false >::Scalar = typename unpacket_traits<Packet>::type
Member Function Documentation
run_ceil()
template<typename Packet > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet Eigen::internal::nearest_integer_packetop_impl< Packet, false, false >::run_ceil (const Packet & x) inline static
 { return generic_ceil(x); }
References Eigen::internal::generic_ceil(), and plotDoE::x.
run_floor()
template<typename Packet > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet Eigen::internal::nearest_integer_packetop_impl< Packet, false, false >::run_floor (const Packet & x) inline static
 { return generic_floor(x); }
References Eigen::internal::generic_floor(), and plotDoE::x.
run_rint()
template<typename Packet > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet Eigen::internal::nearest_integer_packetop_impl< Packet, false, false >::run_rint (const Packet & x) inline static
 { return generic_rint(x); }
References Eigen::internal::generic_rint(), and plotDoE::x.
run_round()
template<typename Packet > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet Eigen::internal::nearest_integer_packetop_impl< Packet, false, false >::run_round (const Packet & x) inline static
 { return generic_round(x); }
References Eigen::internal::generic_round(), and plotDoE::x.
run_trunc()
template<typename Packet > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet Eigen::internal::nearest_integer_packetop_impl< Packet, false, false >::run_trunc (const Packet & x) inline static
 { return generic_trunc(x); }
References Eigen::internal::generic_trunc(), and plotDoE::x.
The documentation for this struct was generated from the following file:
GenericPacketMathFunctions.h