MercuryDPM: tree_3d.cc File Reference
tree_3d.cc File Reference
#include <typeinfo>
#include "generic.h"
#include "poisson.h"
#include "meshes/simple_cubic_mesh.h"
Classes
class CompareElementCoordinate< ELEMENT >
class Rotateable< ELEMENT >
class TestRefineableCubicMesh< ELEMENT >
class TestPoissonProblem< ELEMENT >
Poisson problem on rotatable, refineable cubic brick mesh.
Namespaces
TanhSolnForPoisson
Namespace for exact solution for Poisson equation with "sharp step".
Functions
void TanhSolnForPoisson::get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void TanhSolnForPoisson::get_exact_u (const Vector< double > &x, double &u)
Exact solution as a scalar.
void TanhSolnForPoisson::get_source (const Vector< double > &x, double &source)
Source function to make it an exact solution.
template<class ELEMENT >
void run_test (const unsigned &i)
int main ()
Driver code for 2D Poisson problem.
Function Documentation
main()
int main ()
Driver code for 2D Poisson problem.
 {
  run_test<Rotateable<RefineableQPoissonElement<3,2> > >(1);
  run_test<Rotateable<RefineableQPoissonElement<3,3> > >(2);
  run_test<Rotateable<RefineableQSpectralPoissonElement<3,4> > >(3);
 } //end of main
run_test()
template<class ELEMENT > void run_test (const unsigned & i)
Global function that is used to run the rotation tests for different elements
 {
  char dirname[100];
  sprintf(dirname,"RESLT%i",i);
  // Create label for output
  //------------------------
  DocInfo doc_info;
  // Set output directory
  doc_info.set_directory(dirname);
  // Step number
  doc_info.number()=0;
  //Set up the problem
  //------------------
  for(unsigned i=0;i<24;i++)
   {
    //Create the problem with rotation i
    TestPoissonProblem<ELEMENT>
     problem(i,&TanhSolnForPoisson::get_source);
    // Solve the problem, performing up to 2 adaptive refinements
    problem.newton_solve();
    //Output the solution
    problem.doc_solution(doc_info);
    doc_info.number()++;
   }
 }
References TanhSolnForPoisson::get_source(), i, oomph::DocInfo::number(), problem, and oomph::DocInfo::set_directory().