MercuryDPM: AirwayReopeningProblem< ELEMENT > Class Template Reference
AirwayReopeningProblem< ELEMENT > Class Template Reference
Bretherton problem.
Public Member Functions
AirwayReopeningProblem ()
Constructor:
~AirwayReopeningProblem ()
Destructor, clean up all allocated memory.
void actions_after_change_in_global_parameter (double *const &parameter_pt)
void actions_before_newton_convergence_check ()
void actions_before_newton_solve ()
Update before solve: empty.
void actions_after_newton_solve ()
void fix_pressure (const unsigned &e, const unsigned &l, const double &pvalue)
Fix pressure value l in element e to value p_value.
void parameter_study (const unsigned &nsteps, const bool &restart)
Run a parameter study; perform specified number of steps.
void doc_solution (DocInfo &doc_info)
Doc the solution.
void construct_poisson_outlet_elements ()
Set up the actual outlet elements.
void delete_outlet_elements ()
Delete the outlet elements.
void construct_pressure_gradient_outlet_elements ()
Set up the inital outlet elements.
double get_outlet_flux ()
void change_boundary_conditions ()
void dump (ofstream &dump_file) const
Dump the entire problem.
void read (ifstream &restart_file)
Read the entire problem.
void connect_walls (Mesh *const &wall_mesh_pt, GeomObject *const &geom_object_pt, map< double, pair< GeomObject *, Vector< double > > > &globalmap)
Setup the coupling between the upper and lower walls.
Public Member Functions inherited from oomph::Problem
virtual void debug_hook_fct (const unsigned &i)
void set_analytic_dparameter (double *const &parameter_pt)
void unset_analytic_dparameter (double *const &parameter_pt)
bool is_dparameter_calculated_analytically (double *const &parameter_pt)
void set_analytic_hessian_products ()
void unset_analytic_hessian_products ()
bool are_hessian_products_calculated_analytically ()
void set_pinned_values_to_zero ()
bool distributed () const
virtual void actions_before_adapt ()
virtual void actions_after_adapt ()
Actions that are to be performed after a mesh adaptation.
OomphCommunicator * communicator_pt ()
access function to the oomph-lib communicator
const OomphCommunicator * communicator_pt () const
access function to the oomph-lib communicator, const version
Problem ()
Problem (const Problem &dummy)=delete
Broken copy constructor.
void operator= (const Problem &)=delete
Broken assignment operator.
virtual ~Problem ()
Virtual destructor to clean up memory.
Mesh *& mesh_pt ()
Return a pointer to the global mesh.
Mesh *const & mesh_pt () const
Return a pointer to the global mesh (const version)
Mesh *& mesh_pt (const unsigned &imesh)
Mesh *const & mesh_pt (const unsigned &imesh) const
Return a pointer to the i-th submesh (const version)
unsigned nsub_mesh () const
Return number of submeshes.
unsigned add_sub_mesh (Mesh *const &mesh_pt)
void flush_sub_meshes ()
void build_global_mesh ()
void rebuild_global_mesh ()
LinearSolver *& linear_solver_pt ()
Return a pointer to the linear solver object.
LinearSolver *const & linear_solver_pt () const
Return a pointer to the linear solver object (const version)
LinearSolver *& mass_matrix_solver_for_explicit_timestepper_pt ()
LinearSolver * mass_matrix_solver_for_explicit_timestepper_pt () const
EigenSolver *& eigen_solver_pt ()
Return a pointer to the eigen solver object.
EigenSolver *const & eigen_solver_pt () const
Return a pointer to the eigen solver object (const version)
Time *& time_pt ()
Return a pointer to the global time object.
Time * time_pt () const
Return a pointer to the global time object (const version).
double & time ()
Return the current value of continuous time.
double time () const
Return the current value of continuous time (const version)
TimeStepper *& time_stepper_pt ()
const TimeStepper * time_stepper_pt () const
TimeStepper *& time_stepper_pt (const unsigned &i)
Return a pointer to the i-th timestepper.
ExplicitTimeStepper *& explicit_time_stepper_pt ()
Return a pointer to the explicit timestepper.
unsigned long set_timestepper_for_all_data (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data=false)
virtual void shift_time_values ()
Shift all values along to prepare for next timestep.
AssemblyHandler *& assembly_handler_pt ()
Return a pointer to the assembly handler object.
AssemblyHandler *const & assembly_handler_pt () const
Return a pointer to the assembly handler object (const version)
double & minimum_dt ()
Access function to min timestep in adaptive timestepping.
double & maximum_dt ()
Access function to max timestep in adaptive timestepping.
unsigned & max_newton_iterations ()
Access function to max Newton iterations before giving up.
void problem_is_nonlinear (const bool &prob_lin)
Access function to Problem_is_nonlinear.
double & max_residuals ()
bool & time_adaptive_newton_crash_on_solve_fail ()
Access function for Time_adaptive_newton_crash_on_solve_fail.
double & newton_solver_tolerance ()
void add_time_stepper_pt (TimeStepper *const &time_stepper_pt)
void set_explicit_time_stepper_pt (ExplicitTimeStepper *const &explicit_time_stepper_pt)
void initialise_dt (const double &dt)
void initialise_dt (const Vector< double > &dt)
Data *& global_data_pt (const unsigned &i)
Return a pointer to the the i-th global data object.
void add_global_data (Data *const &global_data_pt)
void flush_global_data ()
LinearAlgebraDistribution *const & dof_distribution_pt () const
Return the pointer to the dof distribution (read-only)
unsigned long ndof () const
Return the number of dofs.
unsigned ntime_stepper () const
Return the number of time steppers.
unsigned nglobal_data () const
Return the number of global data values.
unsigned self_test ()
Self-test: Check meshes and global data. Return 0 for OK.
void enable_store_local_dof_pt_in_elements ()
void disable_store_local_dof_pt_in_elements ()
unsigned long assign_eqn_numbers (const bool &assign_local_eqn_numbers=true)
void describe_dofs (std::ostream &out= *(oomph_info.stream_pt())) const
void enable_discontinuous_formulation ()
void disable_discontinuous_formulation ()
void get_dofs (DoubleVector &dofs) const
void get_dofs (const unsigned &t, DoubleVector &dofs) const
Return vector of the t'th history value of all dofs.
void set_dofs (const DoubleVector &dofs)
Set the values of the dofs.
void set_dofs (const unsigned &t, DoubleVector &dofs)
Set the history values of the dofs.
void set_dofs (const unsigned &t, Vector< double * > &dof_pt)
void add_to_dofs (const double &lambda, const DoubleVector &increment_dofs)
Add lambda x incremenet_dofs[l] to the l-th dof.
double * global_dof_pt (const unsigned &i)
double & dof (const unsigned &i)
i-th dof in the problem
double dof (const unsigned &i) const
i-th dof in the problem (const version)
double *& dof_pt (const unsigned &i)
Pointer to i-th dof in the problem.
double * dof_pt (const unsigned &i) const
Pointer to i-th dof in the problem (const version)
virtual void get_inverse_mass_matrix_times_residuals (DoubleVector &Mres)
virtual void get_dvaluesdt (DoubleVector &f)
virtual void get_residuals (DoubleVector &residuals)
Get the total residuals Vector for the problem.
virtual void get_jacobian (DoubleVector &residuals, DenseDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CRDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CCDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, SumOfMatrices &jacobian)
void get_fd_jacobian (DoubleVector &residuals, DenseMatrix< double > &jacobian)
Get the full Jacobian by finite differencing.
void get_derivative_wrt_global_parameter (double *const &parameter_pt, DoubleVector &result)
void get_hessian_vector_products (DoubleVectorWithHaloEntries const &Y, Vector< DoubleVectorWithHaloEntries > const &C, Vector< DoubleVectorWithHaloEntries > &product)
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, Vector< DoubleVector > &eigenvector, const bool &steady=true)
Solve the eigenproblem.
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, const bool &steady=true)
virtual void get_eigenproblem_matrices (CRDoubleMatrix &mass_matrix, CRDoubleMatrix &main_matrix, const double &shift=0.0)
void assign_eigenvector_to_dofs (DoubleVector &eigenvector)
Assign the eigenvector passed to the function to the dofs.
void add_eigenvector_to_dofs (const double &epsilon, const DoubleVector &eigenvector)
void store_current_dof_values ()
Store the current values of the degrees of freedom.
void restore_dof_values ()
Restore the stored values of the degrees of freedom.
void enable_jacobian_reuse ()
void disable_jacobian_reuse ()
Disable recycling of Jacobian in Newton iteration.
bool jacobian_reuse_is_enabled ()
Is recycling of Jacobian in Newton iteration enabled?
bool & use_predictor_values_as_initial_guess ()
void newton_solve ()
Use Newton method to solve the problem.
void enable_globally_convergent_newton_method ()
enable globally convergent Newton method
void disable_globally_convergent_newton_method ()
disable globally convergent Newton method
void newton_solve (unsigned const &max_adapt)
void steady_newton_solve (unsigned const &max_adapt=0)
void copy (Problem *orig_problem_pt)
virtual Problem * make_copy ()
virtual void read (std::ifstream &restart_file, bool &unsteady_restart)
void dump (const std::string &dump_file_name) const
void delete_all_external_storage ()
virtual void symmetrise_eigenfunction_for_adaptive_pitchfork_tracking ()
double * bifurcation_parameter_pt () const
void get_bifurcation_eigenfunction (Vector< DoubleVector > &eigenfunction)
void activate_fold_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const DoubleVector &normalisation, const bool &block_solve=true)
void activate_pitchfork_tracking (double *const &parameter_pt, const DoubleVector &symmetry_vector, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const double &omega, const DoubleVector &null_real, const DoubleVector &null_imag, const bool &block_solve=true)
void deactivate_bifurcation_tracking ()
void reset_assembly_handler_to_default ()
Reset the system to the standard non-augemented state.
double arc_length_step_solve (double *const &parameter_pt, const double &ds, const unsigned &max_adapt=0)
double arc_length_step_solve (Data *const &data_pt, const unsigned &data_index, const double &ds, const unsigned &max_adapt=0)
void reset_arc_length_parameters ()
int & sign_of_jacobian ()
void explicit_timestep (const double &dt, const bool &shift_values=true)
Take an explicit timestep of size dt.
void unsteady_newton_solve (const double &dt)
void unsteady_newton_solve (const double &dt, const bool &shift_values)
void unsteady_newton_solve (const double &dt, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const unsigned &suppress_resolve_after_spatial_adapt_flag, const bool &first, const bool &shift=true)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon, const bool &shift_values)
void assign_initial_values_impulsive ()
void assign_initial_values_impulsive (const double &dt)
void calculate_predictions ()
Calculate predictions.
void enable_mass_matrix_reuse ()
void disable_mass_matrix_reuse ()
bool mass_matrix_reuse_is_enabled ()
Return whether the mass matrix is being reused.
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly (DocInfo &doc_info)
void refine_uniformly_and_prune (DocInfo &doc_info)
void refine_uniformly ()
void refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform refinement for submesh i_mesh with documentation.
void refine_uniformly (const unsigned &i_mesh)
Do uniform refinement for submesh i_mesh without documentation.
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly (DocInfo &doc_info)
void p_refine_uniformly_and_prune (DocInfo &doc_info)
void p_refine_uniformly ()
void p_refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-refinement for submesh i_mesh with documentation.
void p_refine_uniformly (const unsigned &i_mesh)
Do uniform p-refinement for submesh i_mesh without documentation.
void refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const unsigned &i_mesh, const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void refine_selected_elements (const Vector< Vector< RefineableElement * >> &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void p_refine_selected_elements (const Vector< Vector< PRefineableElement * >> &elements_to_be_refined_pt)
unsigned unrefine_uniformly ()
unsigned unrefine_uniformly (const unsigned &i_mesh)
void p_unrefine_uniformly (DocInfo &doc_info)
void p_unrefine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-unrefinement for submesh i_mesh without documentation.
void adapt (unsigned &n_refined, unsigned &n_unrefined)
void adapt ()
void p_adapt (unsigned &n_refined, unsigned &n_unrefined)
void p_adapt ()
void adapt_based_on_error_estimates (unsigned &n_refined, unsigned &n_unrefined, Vector< Vector< double >> &elemental_error)
void adapt_based_on_error_estimates (Vector< Vector< double >> &elemental_error)
void get_all_error_estimates (Vector< Vector< double >> &elemental_error)
void doc_errors (DocInfo &doc_info)
Get max and min error for all elements in submeshes.
void doc_errors ()
Get max and min error for all elements in submeshes.
void enable_info_in_newton_solve ()
void disable_info_in_newton_solve ()
Disable the output of information when in the newton solver.
Public Member Functions inherited from oomph::ExplicitTimeSteppableObject
ExplicitTimeSteppableObject ()
Empty constructor.
ExplicitTimeSteppableObject (const ExplicitTimeSteppableObject &)=delete
Broken copy constructor.
void operator= (const ExplicitTimeSteppableObject &)=delete
Broken assignment operator.
virtual ~ExplicitTimeSteppableObject ()
Empty destructor.
virtual void actions_before_explicit_stage ()
virtual void actions_after_explicit_stage ()
Private Attributes
ELEMENT * Control_element_pt
Pointer to control element.
ofstream Trace_file
Trace file.
BrethertonSpineMesh< ELEMENT, SpineLineFluidInterfaceElement< ELEMENT > > * Bulk_mesh_pt
Pointer to bulk mesh.
OneDLagrangianMesh< FSIHermiteBeamElement > * Upper_wall_mesh_pt
Pointer to Wall mesh.
OneDLagrangianMesh< FSIHermiteBeamElement > * Lower_wall_mesh_pt
Pointer to lower wall mesh.
Mesh * Constraint_mesh_pt
Pointer to the constraint mesh.
GeomObject * Undeformed_upper_wall_geom_pt
Pointer to the Undeformed wall.
GeomObject * Undeformed_lower_wall_geom_pt
Pointer to the Undeformed wall.
double Fixed_spine_height
Fixed height value.
Data * Bubble_pressure_data_pt
Data value that represents the bubble pressure.
Data * Mesh_fraction_at_transition_pt
Vector< FiniteElement * > Gravity_traction_element_pt
Vector of pointers to the traction elements.
Vector< FiniteElement * > Outlet_traction_element_pt
Vector of pointers to the outlet traciton elements.
FluxConstraint * Flux_constraint_pt
Flux constraint element.
bool Frontal_solver
Boolean flag to specify the use of the frontal solver.
Additional Inherited Members
Public Types inherited from oomph::Problem
typedef void(* SpatialErrorEstimatorFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error)
Function pointer for spatial error estimator.
typedef void(* SpatialErrorEstimatorWithDocFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error, DocInfo &doc_info)
Function pointer for spatial error estimator with doc.
Public Attributes inherited from oomph::Problem
bool Shut_up_in_newton_solve
Static Public Attributes inherited from oomph::Problem
static bool Suppress_warning_about_actions_before_read_unstructured_meshes
Protected Types inherited from oomph::Problem
enum Assembly_method {
Perform_assembly_using_vectors_of_pairs , Perform_assembly_using_two_vectors , Perform_assembly_using_maps , Perform_assembly_using_lists ,
Perform_assembly_using_two_arrays
}
Enumerated flags to determine which sparse assembly method is used.
Protected Member Functions inherited from oomph::Problem
unsigned setup_element_count_per_dof ()
virtual void sparse_assemble_row_or_column_compressed (Vector< int * > &column_or_row_index, Vector< int * > &row_or_column_start, Vector< double * > &value, Vector< unsigned > &nnz, Vector< double * > &residual, bool compressed_row_flag)
virtual void actions_before_newton_step ()
virtual void actions_after_newton_step ()
virtual void actions_before_implicit_timestep ()
virtual void actions_after_implicit_timestep ()
virtual void actions_after_implicit_timestep_and_error_estimation ()
virtual void actions_before_explicit_timestep ()
Actions that should be performed before each explicit time step.
virtual void actions_after_explicit_timestep ()
Actions that should be performed after each explicit time step.
virtual void actions_before_read_unstructured_meshes ()
virtual void actions_after_read_unstructured_meshes ()
virtual void actions_after_change_in_bifurcation_parameter ()
virtual void actions_after_parameter_increase (double *const &parameter_pt)
double & dof_derivative (const unsigned &i)
double & dof_current (const unsigned &i)
virtual void set_initial_condition ()
virtual double global_temporal_error_norm ()
unsigned newton_solve_continuation (double *const &parameter_pt)
unsigned newton_solve_continuation (double *const &parameter_pt, DoubleVector &z)
void calculate_continuation_derivatives (double *const &parameter_pt)
void calculate_continuation_derivatives (const DoubleVector &z)
void calculate_continuation_derivatives_fd (double *const &parameter_pt)
bool does_pointer_correspond_to_problem_data (double *const &parameter_pt)
void set_consistent_pinned_values_for_continuation ()
Protected Attributes inherited from oomph::Problem
Vector< Problem * > Copy_of_problem_pt
std::map< double *, bool > Calculate_dparameter_analytic
bool Calculate_hessian_products_analytic
LinearAlgebraDistribution * Dof_distribution_pt
Vector< double * > Dof_pt
Vector of pointers to dofs.
DoubleVectorWithHaloEntries Element_count_per_dof
double Relaxation_factor
double Newton_solver_tolerance
unsigned Max_newton_iterations
Maximum number of Newton iterations.
unsigned Nnewton_iter_taken
Vector< double > Max_res
Maximum residuals at start and after each newton iteration.
double Max_residuals
bool Time_adaptive_newton_crash_on_solve_fail
bool Jacobian_reuse_is_enabled
Is re-use of Jacobian in Newton iteration enabled? Default: false.
bool Jacobian_has_been_computed
bool Problem_is_nonlinear
bool Pause_at_end_of_sparse_assembly
bool Doc_time_in_distribute
unsigned Sparse_assembly_method
unsigned Sparse_assemble_with_arrays_initial_allocation
unsigned Sparse_assemble_with_arrays_allocation_increment
Vector< Vector< unsigned > > Sparse_assemble_with_arrays_previous_allocation
double Numerical_zero_for_sparse_assembly
double FD_step_used_in_get_hessian_vector_products
bool Mass_matrix_reuse_is_enabled
bool Mass_matrix_has_been_computed
bool Discontinuous_element_formulation
double Minimum_dt
Minimum desired dt: if dt falls below this value, exit.
double Maximum_dt
Maximum desired dt.
double DTSF_max_increase
double DTSF_min_decrease
double Minimum_dt_but_still_proceed
bool Scale_arc_length
Boolean to control whether arc-length should be scaled.
double Desired_proportion_of_arc_length
Proportion of the arc-length to taken by the parameter.
double Theta_squared
int Sign_of_jacobian
Storage for the sign of the global Jacobian.
double Continuation_direction
double Parameter_derivative
Storage for the derivative of the global parameter wrt arc-length.
double Parameter_current
Storage for the present value of the global parameter.
bool Use_continuation_timestepper
Boolean to control original or new storage of dof stuff.
unsigned Dof_derivative_offset
unsigned Dof_current_offset
Vector< double > Dof_derivative
Storage for the derivative of the problem variables wrt arc-length.
Vector< double > Dof_current
Storage for the present values of the variables.
double Ds_current
Storage for the current step value.
unsigned Desired_newton_iterations_ds
double Minimum_ds
Minimum desired value of arc-length.
bool Bifurcation_detection
Boolean to control bifurcation detection via determinant of Jacobian.
bool Bisect_to_find_bifurcation
Boolean to control wheter bisection is used to located bifurcation.
bool First_jacobian_sign_change
Boolean to indicate whether a sign change has occured in the Jacobian.
bool Arc_length_step_taken
Boolean to indicate whether an arc-length step has been taken.
bool Use_finite_differences_for_continuation_derivatives
OomphCommunicator * Communicator_pt
The communicator for this problem.
bool Always_take_one_newton_step
double Timestep_reduction_factor_after_nonconvergence
bool Keep_temporal_error_below_tolerance
Static Protected Attributes inherited from oomph::Problem
static ContinuationStorageScheme Continuation_time_stepper
Storage for the single static continuation timestorage object.
Detailed Description
template<class ELEMENT>
class AirwayReopeningProblem< ELEMENT >
Bretherton problem.
Constructor & Destructor Documentation
AirwayReopeningProblem()
template<class ELEMENT > AirwayReopeningProblem< ELEMENT >::AirwayReopeningProblem
Constructor:
Problem constructor.
 {
  Frontal_solver = false;
  // Number of elements in the deposited film region
  unsigned nx1=100;//300;
  // Number of elements in the bottom part of the transition region
  unsigned nx2=6;//12;
  // Number of elements in channel region
  unsigned nx3=100;//300;
  // Number of elements in the vertical part of the transition region
  // (=half the number of elements in the liquid filled region ahead
  // of the finger tip)
  unsigned nhalf=2;//4;
  // Number of elements through thickness of deposited film
  unsigned nh=2;//3;
  // Number of elements in each wall
  unsigned nwall = 100;// 450;
  // Thickness of deposited film
  double h = 0.128;
  // Start coordinate on wall
  double xi0= -300.0;
  double start_transition = -1.0;
  // End of transition region on wall
  double xi1 = 1.5;
  // End of liquid filled region (inflow) on wall
  double xi2 = 150.0;//300.0
  //Set the frontal solver, if desired
  if(Frontal_solver)
   {
    linear_solver_pt() = new HSL_MA42;
   }
  //Create a bubble presure data
  Bubble_pressure_data_pt = new Data(1);
  //This will be global data
  add_global_data(Bubble_pressure_data_pt);
  //Create a mesh fraction data
  Mesh_fraction_at_transition_pt = new Data(1);
  add_global_data(Mesh_fraction_at_transition_pt);
  //Pin the value
  Mesh_fraction_at_transition_pt->set_value(0,0.5);
  Mesh_fraction_at_transition_pt->pin(0);
  // The underformed wall is a straight line at y = 1.0
  Undeformed_upper_wall_geom_pt = new StraightLine(1.0);
  // Create the Lagrangian Mesh
  Upper_wall_mesh_pt =
   new OneDLagrangianMesh<FSIHermiteBeamElement>(nwall,xi0,xi2,
                                                 Undeformed_upper_wall_geom_pt);
  //Loop over the wall elements
  unsigned n_upper_wall_element = Upper_wall_mesh_pt->nelement();
  for(unsigned e=0;e<n_upper_wall_element;e++)
   {
    FSIHermiteBeamElement *element_pt = dynamic_cast<FSIHermiteBeamElement*>(
     Upper_wall_mesh_pt->element_pt(e));
    //Assign the undeformed beam shape
    element_pt->undeformed_beam_pt() = Undeformed_upper_wall_geom_pt;
    //Set the load vector
    element_pt->load_vector_fct_pt() = &Global_Physical_Variables::spring_load;
    //Set the wall thickness
    element_pt->h_pt() = &Global_Physical_Variables::H;
    //Set the axial pre-stress
    element_pt->sigma0_pt() = &Global_Physical_Variables::T;
    //Function that specifies the load ratios
    element_pt->q_pt() = &Global_Physical_Variables::Q;
    //In this case the normal is directed out of the fluid
    element_pt->set_normal_pointing_out_of_fluid();
  }
  //Create a geometric object that represents the wall geometry
  MeshAsGeomObject* upper_wall_element_pt =
   new MeshAsGeomObject(Upper_wall_mesh_pt);
  // The underformed lower wall is a straight line at y = -1.0
  Undeformed_lower_wall_geom_pt = new StraightLine(-1.0);
  // Create the Lagrangian Mesh
  Lower_wall_mesh_pt =
   new OneDLagrangianMesh<FSIHermiteBeamElement>(nwall,xi0,xi2,
                                                 Undeformed_lower_wall_geom_pt);
  //Loop over the wall elements
  unsigned n_lower_wall_element = Lower_wall_mesh_pt->nelement();
  for(unsigned e=0;e<n_lower_wall_element;e++)
   {
    FSIHermiteBeamElement *element_pt = dynamic_cast<FSIHermiteBeamElement*>(
     Lower_wall_mesh_pt->element_pt(e));
    //Assign the undeformed beam shape
    element_pt->undeformed_beam_pt() = Undeformed_lower_wall_geom_pt;
    //Set the load vector
    element_pt->load_vector_fct_pt() =
     &Global_Physical_Variables::spring_load_lower;
    //Set the wall thickness
    element_pt->h_pt() = &Global_Physical_Variables::H;
    //Set the axial pre-stress
    element_pt->sigma0_pt() = &Global_Physical_Variables::T;
    //Function that specifies the load ratios
    element_pt->q_pt() = &Global_Physical_Variables::Q;
    //In this case the normal is OK
    //element_pt->set_normal_pointing_into_fluid();
  }
  //Create a geometric object that represents the wall geometry
  MeshAsGeomObject* lower_wall_element_pt =
   new MeshAsGeomObject(Lower_wall_mesh_pt);
  // Create wall geom objects
  //GeomObject* lower_wall_pt = new StraightLine(-1.0);
  GeomObject* lower_wall_pt = lower_wall_element_pt;
  Global_Physical_Variables::Lower_wall_pt  = lower_wall_pt;
  //GeomObject* upper_wall_pt=new StraightLine( 1.0);
  GeomObject* upper_wall_pt = upper_wall_element_pt;
  Global_Physical_Variables::Upper_wall_pt = upper_wall_pt;
  //Now create the mesh
  Bulk_mesh_pt = new  BrethertonSpineMesh<ELEMENT,
   SpineLineFluidInterfaceElement<ELEMENT> >
   (nx1,nx2,nx3,nh,nhalf,h,lower_wall_pt,upper_wall_pt,xi0,start_transition,
    xi1,xi2);
  //Set the vertical fraction
  Bulk_mesh_pt->set_spine_centre_fraction_pt(
   Mesh_fraction_at_transition_pt->value_pt(0));
  // Store the control element
  Control_element_pt=Bulk_mesh_pt->control_element_pt();
  //Create a fixed element using the central spine
  FixSpineHeightElement* fix_spine_element_pt =
   new FixSpineHeightElement(
    static_cast<SpineNode*>(Control_element_pt->node_pt(8)));
  //Set the fixed spine height
  Fixed_spine_height =
   static_cast<SpineNode*>(Control_element_pt
                           ->node_pt(8))->spine_pt()->height();
  //Add the fixed height to it
  fix_spine_element_pt->height_pt() = &Fixed_spine_height;
  //Set the pressure data
  fix_spine_element_pt->set_traded_pressure_data(Bubble_pressure_data_pt);
  //Add the Fixed element to the mesh
  Bulk_mesh_pt->add_element_pt(fix_spine_element_pt);
  //Loop over the elements next to the inflow boundarys
  for(unsigned b=3;b<=5;b+=2)
   {
    unsigned nbound_element = Bulk_mesh_pt->nboundary_element(b);
    for(unsigned e=0;e<nbound_element;e++)
     {
      SpineGravityTractionElement<ELEMENT>* inlet_element
       = new SpineGravityTractionElement<ELEMENT>(
        Bulk_mesh_pt->boundary_element_pt(b,e),
        Bulk_mesh_pt->face_index_at_boundary(b,e));
      //Add the elements to the local storage
      Gravity_traction_element_pt.push_back(inlet_element);
      //Add the elements to the mesh
      Bulk_mesh_pt->add_element_pt(inlet_element);
     }
   }
  //Set a prescribed flux element
  Flux_constraint_pt = new FluxConstraint;
  Constraint_mesh_pt = new Mesh;
  Constraint_mesh_pt->add_element_pt(Flux_constraint_pt);
  Flux_constraint_pt->internal_data_pt(0)->pin(0);
  construct_pressure_gradient_outlet_elements();
  Bulk_mesh_pt->node_update();
  {
   //Set the boundary coordinates on the upper wall
   unsigned nbound = Bulk_mesh_pt->nboundary_node(2);
   Vector<double> zeta(1);
   for(unsigned n=0;n<nbound;n++)
    {
     Node* node_pt = Bulk_mesh_pt->boundary_node_pt(2,n);
     zeta[0] = node_pt->x(0);
     node_pt->set_coordinates_on_boundary(2,zeta);
    }
  }
  //Sort out the interaction the upper wall
  FSI_functions::setup_fluid_load_info_for_solid_elements<ELEMENT,2>
   (this,2,Bulk_mesh_pt,Upper_wall_mesh_pt);
  {
   //Set the boundary coordinates on the lower wall
   unsigned nbound = Bulk_mesh_pt->nboundary_node(0);
   Vector<double> zeta(1);
   for(unsigned n=0;n<nbound;n++)
    {
     Node* node_pt = Bulk_mesh_pt->boundary_node_pt(0,n);
     zeta[0] = node_pt->x(0);
     node_pt->set_coordinates_on_boundary(0,zeta);
    }
  }
  //Sort out the interaction the lower wall
  FSI_functions::setup_fluid_load_info_for_solid_elements<ELEMENT,2>
   (this,0,Bulk_mesh_pt,Lower_wall_mesh_pt);
  add_sub_mesh(Bulk_mesh_pt);
  add_sub_mesh(Upper_wall_mesh_pt);
  add_sub_mesh(Lower_wall_mesh_pt);
  add_sub_mesh(Constraint_mesh_pt);
  build_global_mesh();
  // Connect the upper mesh
  connect_walls(Lower_wall_mesh_pt,upper_wall_pt,
                Global_Physical_Variables::upper_map);
  connect_walls(Upper_wall_mesh_pt,lower_wall_pt,
                Global_Physical_Variables::lower_map);
  // Set the boundary conditions for this problem: All nodes are
  // free by default -- just pin the ones that have Dirichlet conditions
  // here
  //Pin one end of the mesh (prevent transvere slide)
  Upper_wall_mesh_pt->boundary_node_pt(1,0)->pin_position(0,0);
  Upper_wall_mesh_pt->boundary_node_pt(0,0)->pin_position(0,0);
  //Pin both ends of the lower mesh
  Lower_wall_mesh_pt->boundary_node_pt(1,0)->pin_position(0,0);
  Lower_wall_mesh_pt->boundary_node_pt(0,0)->pin_position(0,0);
  //Pin the lower mesh vertically
  Lower_wall_mesh_pt->boundary_node_pt(0,0)->pin_position(0,1);
  // No slip on boundaries 0 1 (inflow) and 2
  for(unsigned long ibound=0;ibound<=2;ibound++)
   {
    unsigned num_nod=Bulk_mesh_pt->nboundary_node(ibound);
    for (unsigned inod=0;inod<num_nod;inod++)
     {
      //Leave the inflow traction free in the both directions
      if(ibound!=1)
       {
        Bulk_mesh_pt->boundary_node_pt(ibound,inod)->pin(0);
        Bulk_mesh_pt->boundary_node_pt(ibound,inod)->pin(1);
       }
     }
   }
  // Set the values of the velocities on the wall boundaries
  for (unsigned ibound=0;ibound<=2;ibound+=2)
   {
    unsigned num_nod=Bulk_mesh_pt->nboundary_node(ibound);
    for (unsigned inod=0;inod<num_nod;inod++)
     {
      // Parallel flow
      Bulk_mesh_pt->boundary_node_pt(ibound,inod)->set_value(0,-1.0);
      Bulk_mesh_pt->boundary_node_pt(ibound,inod)->set_value(1, 0.0);
     }
   }
  //Loop over the upper wall
  {
   unsigned b=2;
   unsigned num_nod=Bulk_mesh_pt->nboundary_node(b);
   for (unsigned inod=0;inod<num_nod;inod++)
    {
     //cast to a spine node
     SpineNode* spine_node_pt = static_cast<SpineNode*>
      (Bulk_mesh_pt->boundary_node_pt(b,inod));
     //Find the id of the node
     unsigned id = spine_node_pt->node_update_fct_id();
     switch(id)
      {
      case 4:
      case 5:
       //Add the auxilliary function, so that the no-slip condition is
       //applied properly
       spine_node_pt->set_auxiliary_node_update_fct_pt(
        No_Slip::no_slip_condition_first);
       break;
      case 6:
       spine_node_pt->set_auxiliary_node_update_fct_pt(
        No_Slip::no_slip_condition_second);
       break;
      default:
       cout << "Should not get here" << std::endl;
       break;
      }
    }
  }
  //Loop over the lower wall
  {
   unsigned b=0;
   unsigned num_nod=Bulk_mesh_pt->nboundary_node(b);
   for (unsigned inod=0;inod<num_nod;inod++)
    {
     //cast to a spine node
     SpineNode* spine_node_pt = static_cast<SpineNode*>
      (Bulk_mesh_pt->boundary_node_pt(b,inod));
     //Find the id of the node
     unsigned id = spine_node_pt->node_update_fct_id();
     switch(id)
      {
      case 0:
      case 1:
      case 6:
       //Add the auxilliary function, so that the no-slip condition is
       //applied properly
       spine_node_pt->set_auxiliary_node_update_fct_pt(
        No_Slip::no_slip_condition_first);
       break;
      default:
       cout << "Should not get here" << std::endl;
       break;
      }
    }
  }
  //Parallel, uniform outflow on boundaries 3 and 5
  for (unsigned ibound=3;ibound<=5;ibound+=2)
   {
    unsigned num_nod=Bulk_mesh_pt->nboundary_node(ibound);
    for (unsigned inod=0;inod<num_nod;inod++)
     {
      // Parallel inflow
      Bulk_mesh_pt->boundary_node_pt(ibound,inod)->set_value(0, -1.0);
      Bulk_mesh_pt->boundary_node_pt(ibound,inod)->set_value(1, 0.0);
     }
   }
  //Loop over the elements in the layer
  unsigned long n_bulk=Bulk_mesh_pt->nbulk();
  for(unsigned long i=0;i<n_bulk;i++)
   {
    //Cast to a fluid element
    ELEMENT *el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->
                                            bulk_element_pt(i));
    //Set the Reynolds number, etc
    el_pt->re_pt() = &Global_Physical_Variables::Re;
    el_pt->re_st_pt() = &Global_Physical_Variables::ReSt;
    el_pt->re_invfr_pt() = &Global_Physical_Variables::ReInvFr;
    el_pt->g_pt() = &Global_Physical_Variables::G;
   }
  //Loop over 1D interface elements and set capillary number
  unsigned interface_element_pt_range = Bulk_mesh_pt->ninterface_element();
  for(unsigned i=0;i<interface_element_pt_range;i++)
   {
    //Cast to a interface element
    SpineLineFluidInterfaceElement<ELEMENT>* el_pt =
     dynamic_cast<SpineLineFluidInterfaceElement<ELEMENT>*>
     (Bulk_mesh_pt->interface_element_pt(i));
    //Set the Capillary number
    el_pt->ca_pt() = &Global_Physical_Variables::Ca;
    //Set the external pressure data
    el_pt->set_external_pressure_data(Bubble_pressure_data_pt);
    //We need to make sure that we hijack the nodes on the boundaries
    if(i==0) {el_pt->hijack_nodal_value(0,0);}
    if(i==interface_element_pt_range-1)
     {el_pt->hijack_nodal_value(el_pt->nnode()-1,0);}
   }
  //Loop over the traction elements
  unsigned n_traction = Gravity_traction_element_pt.size();
  for(unsigned e=0;e<n_traction;e++)
   {
    //Cast to the traction element
    SpineGravityTractionElement<ELEMENT>* el_pt =
     dynamic_cast<SpineGravityTractionElement<ELEMENT>*>
     (Gravity_traction_element_pt[e]);
    //Set the Reynolds number divided by the Froude number
    el_pt->re_invfr_pt() = &Global_Physical_Variables::ReInvFr;
    el_pt->g_pt() = &Global_Physical_Variables::G;
   }
  //Do equation numbering
  cout << "Number of unknowns: " << assign_eqn_numbers() << std::endl;
  //Sort the elements if using the frontal solver
  //If this is not done, it's very slow indeed
  //If it is done, then it's very fast compared to SuperLU
  if(Frontal_solver)
   {
    std::sort(mesh_pt()->element_pt().begin(),
              mesh_pt()->element_pt().end(),
              ElementCmp());
   }
 }
References oomph::Mesh::add_element_pt(), b, Global_Physical_Variables::Ca, oomph::FluidInterfaceElement::ca_pt(), e(), Eigen::placeholders::end, Global_Physical_Variables::G, SpineGravityTractionElement< ELEMENT >::g_pt(), Global_Physical_Variables::H, oomph::KirchhoffLoveBeamEquations::h_pt(), FixSpineHeightElement::height_pt(), oomph::Hijacked< ELEMENT >::hijack_nodal_value(), i, oomph::KirchhoffLoveBeamEquations::load_vector_fct_pt, Global_Physical_Variables::lower_map, Global_Physical_Variables::Lower_wall_pt, n, oomph::FiniteElement::nnode(), No_Slip::no_slip_condition_first(), No_Slip::no_slip_condition_second(), oomph::SpineNode::node_update_fct_id(), Global_Physical_Variables::Q, oomph::FSIWallElement::q_pt(), Global_Physical_Variables::Re, SpineGravityTractionElement< ELEMENT >::re_invfr_pt(), Global_Physical_Variables::ReInvFr, Global_Physical_Variables::ReSt, oomph::Node::set_auxiliary_node_update_fct_pt(), oomph::Node::set_coordinates_on_boundary(), oomph::FluidInterfaceElement::set_external_pressure_data(), oomph::FSIHermiteBeamElement::set_normal_pointing_out_of_fluid(), FixSpineHeightElement::set_traded_pressure_data(), oomph::KirchhoffLoveBeamEquations::sigma0_pt(), Global_Physical_Variables::spring_load(), Global_Physical_Variables::spring_load_lower(), Global_Physical_Variables::T, oomph::KirchhoffLoveBeamEquations::undeformed_beam_pt(), Global_Physical_Variables::upper_map, Global_Physical_Variables::Upper_wall_pt, oomph::Node::x(), and Eigen::zeta().
~AirwayReopeningProblem()
template<class ELEMENT > AirwayReopeningProblem< ELEMENT >::~AirwayReopeningProblem () inline
Destructor, clean up all allocated memory.
   {
    //Delete objects created in constructor in reverse order
    delete Constraint_mesh_pt;
    delete Bulk_mesh_pt;
    //Delete objects associated with lower wall mesh
    delete Global_Physical_Variables::Lower_wall_pt;
    delete Lower_wall_mesh_pt;
    delete Undeformed_lower_wall_geom_pt;
    //Delete objects associated with upper wall mesh
    delete Global_Physical_Variables::Upper_wall_pt;
    delete Upper_wall_mesh_pt;
    delete Undeformed_upper_wall_geom_pt;
    //Delete global data
    delete Mesh_fraction_at_transition_pt;
    delete Bubble_pressure_data_pt;
   //Delete the linear solver, if allocated
    if(Frontal_solver) {delete linear_solver_pt();}
   }
References Global_Physical_Variables::Lower_wall_pt, and Global_Physical_Variables::Upper_wall_pt.
Member Function Documentation
actions_after_change_in_global_parameter()
template<class ELEMENT > void AirwayReopeningProblem< ELEMENT >::actions_after_change_in_global_parameter (double *const & parameter_pt) inline virtual
Overload the continuation actions because we're continuing in Ca which does not affect the mesh
Reimplemented from oomph::Problem.
   {
    //Check that the multipliers have worked
    using namespace Global_Physical_Variables;
    ReInvFr = Bo/Ca;
    Re = ReCa*Ca;
    Q = Ca*Gamma;
    T = 100.0*Gamma/H;
   }
References Global_Physical_Variables::Bo, Global_Physical_Variables::Ca, Global_Physical_Variables::Gamma, H, Global_Physical_Variables::Q, GlobalPhysicalVariables::Re, Global_Physical_Variables::ReCa, and GlobalPhysicalVariables::ReInvFr.
actions_after_newton_solve()
template<class ELEMENT > void AirwayReopeningProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update after solve can remain empty, because the update is performed automatically after every Newton step.
Reimplemented from oomph::Problem.
 {}
actions_before_newton_convergence_check()
template<class ELEMENT > void AirwayReopeningProblem< ELEMENT >::actions_before_newton_convergence_check () inline virtual
Spine heights/lengths are unknowns in the problem so their values get corrected during each Newton step. However, changing their value does not automatically change the nodal positions, so we need to update all of them
Reimplemented from oomph::Problem.
   {
     actions_after_change_in_global_parameter(&Global_Physical_Variables::Ca);
    // Mesh Update
    Bulk_mesh_pt->node_update();
    // This driver code cannot be allowed to use the analytical form of
    // get_dresidual_dnodal_coordinates(...) that is implemented in the
    // NavierStokesEquations class, since the elemental residuals have
    // contributions from external data which is not taken into account
    // by that routine. We therefore force the bulk elements to use the
    // fully-finite differenced version.
    const unsigned n_bulk_element = Bulk_mesh_pt->nelement();
    for(unsigned e=0;e<n_bulk_element;e++)
     {
      ElementWithMovingNodes* el_pt =
       dynamic_cast<ElementWithMovingNodes*>(Bulk_mesh_pt->element_pt(e));
      el_pt->evaluate_shape_derivs_by_direct_fd();
     }
   }
References Global_Physical_Variables::Ca, e(), and oomph::ElementWithMovingNodes::evaluate_shape_derivs_by_direct_fd().
actions_before_newton_solve()
template<class ELEMENT > void AirwayReopeningProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update before solve: empty.
Reimplemented from oomph::Problem.
 {}
change_boundary_conditions()
template<class ELEMENT > void AirwayReopeningProblem< ELEMENT >::change_boundary_conditions () inline
   {
    //Delete the traction elements and set what we really want
    delete_outlet_elements();
    //Construct the new elements
    construct_poisson_outlet_elements();
    //Rebuild the global mesh
    rebuild_global_mesh();
    //Now set a consistent flux
    Flux_constraint_pt->set_flux(get_outlet_flux());
    //Unpin the flux constraint
    Flux_constraint_pt->internal_data_pt(0)->unpin(0);
    //Hijack the nodes again
    for(unsigned i=0;i<Outlet_traction_element_pt.size();i++)
     {
      dynamic_cast<SpineGravityTractionElement<ELEMENT>*>(
       Outlet_traction_element_pt[i])->hijack_all_nodes();
     }
    //Hijack the nodes again
    for(unsigned i=0;i<Gravity_traction_element_pt.size();i++)
     {
      dynamic_cast<SpineGravityTractionElement<ELEMENT>*>(
       Gravity_traction_element_pt[i])->hijack_all_nodes();
     }
    //Do equation numbering
    cout << "Number of unknowns: " << assign_eqn_numbers() << std::endl;
    //Sort the elements if using the frontal solver
    if(Frontal_solver)
     {
      std::sort(mesh_pt()->element_pt().begin(),
                mesh_pt()->element_pt().end(),
                ElementCmp());
     }
   }
References Eigen::placeholders::end, and i.
connect_walls()
template<class ELEMENT > void AirwayReopeningProblem< ELEMENT >::connect_walls (Mesh *const & wall_mesh_pt, GeomObject *const & geom_object_pt, map< double, pair< GeomObject *, Vector< double > > > & globalmap) inline
Setup the coupling between the upper and lower walls.
   {
    //Loop over the elements in the wall mesh
    unsigned n_wall_element = wall_mesh_pt->nelement();
    for(unsigned e=0;e<n_wall_element;e++)
     {
      //A set of geometric data to be added to the element
      set<Data*> extra_data;
      //Cast each element to an FSIWallElement
      FSIHermiteBeamElement *solid_element_pt =
       dynamic_cast<FSIHermiteBeamElement*>(wall_mesh_pt->element_pt(e));
      //Find the number of Gauss points of the element
      unsigned nintpt = solid_element_pt->integral_pt()->nweight();
      //Find the dimension of the element
      unsigned el_dim = solid_element_pt->dim();
      //Set storage for the local coordinates in the solid and bulk elements
      Vector<double> s(el_dim), s_bulk(el_dim);
      //Set storage for the zeta (intrinsic coordinate) at the Gauss point
      Vector<double> zeta(el_dim);
      //Define storage for the geometric object that contains the Gauss point
      GeomObject *sub_obj_pt;
      //Loop over the integration points
      for(unsigned ipt=0;ipt<nintpt;ipt++)
       {
        //Loop over the dimension of the solid element and find the local
        //coordinates of the Gauss points
        for(unsigned i=0;i<el_dim;i++)
         {s[i] = solid_element_pt->integral_pt()->knot(ipt,i);}
        //Get the value of zeta at the integration point
        //Note that zeta coincides with xi (the Lagrangian coordinate)
        //in solid elements
        solid_element_pt->interpolated_xi(s,zeta);
        //Find the geometric object and local coordinate within that
        //object for the given value of the intrinsic coordinate, zeta.
        geom_object_pt->locate_zeta(zeta, sub_obj_pt, s_bulk);
        //Stick the result in the map
        globalmap[zeta[0]] = make_pair(sub_obj_pt,s_bulk);
        //Now sort add the external data to the set
        unsigned n_sub_geom_data = sub_obj_pt->ngeom_data();
        for(unsigned i=0;i<n_sub_geom_data;i++)
         {
          extra_data.insert(sub_obj_pt->geom_data_pt(i));
         }
       }
      //Add the data to the external data of the object
      for(set<Data*>::iterator it=extra_data.begin();
          it!=extra_data.end();++it)
       {
        solid_element_pt->add_external_data(*it);
       }
     }
   }
References oomph::GeneralisedElement::add_external_data(), oomph::FiniteElement::dim(), e(), el_dim, oomph::Mesh::element_pt(), oomph::GeomObject::geom_data_pt(), i, oomph::FiniteElement::integral_pt(), oomph::SolidFiniteElement::interpolated_xi(), oomph::Integral::knot(), oomph::GeomObject::locate_zeta(), oomph::Mesh::nelement(), oomph::GeomObject::ngeom_data(), oomph::Integral::nweight(), s, and Eigen::zeta().
construct_poisson_outlet_elements()
template<class ELEMENT > void AirwayReopeningProblem< ELEMENT >::construct_poisson_outlet_elements () inline
Set up the actual outlet elements.
   {
    //Loop over the elements on the outlet boundary
    unsigned b=1;
    unsigned nbound_element = Bulk_mesh_pt->nboundary_element(b);
    for(unsigned e=0;e<nbound_element;e++)
     {
      SpineGravityTractionElement<ELEMENT>* outlet_element
       = new SpineGravityTractionElement<ELEMENT>(
        Bulk_mesh_pt->boundary_element_pt(b,e),
        Bulk_mesh_pt->face_index_at_boundary(b,e));
      //Add the flux constraint
      outlet_element->set_delta_p_pt(Flux_constraint_pt->internal_data_pt(0));
      //Add the elements to the local storage
      Outlet_traction_element_pt.push_back(outlet_element);
      //Add the elements to the mesh
      Bulk_mesh_pt->add_element_pt(outlet_element);
     }
   }
References b, e(), and SpineGravityTractionElement< ELEMENT >::set_delta_p_pt().
construct_pressure_gradient_outlet_elements()
template<class ELEMENT > void AirwayReopeningProblem< ELEMENT >::construct_pressure_gradient_outlet_elements () inline
Set up the inital outlet elements.
   {
    //Loop over the elements next to the inflow boundarys
    unsigned b=1;
    unsigned nbound_element = Bulk_mesh_pt->nboundary_element(b);
    for(unsigned e=0;e<nbound_element;e++)
     {
      SpineElement<NavierStokesTractionElement<ELEMENT> >* outlet_element
       = new SpineElement<NavierStokesTractionElement<ELEMENT> >(
        Bulk_mesh_pt->boundary_element_pt(b,e),
        Bulk_mesh_pt->face_index_at_boundary(b,e));
      //Add the elements to the local storage
      Outlet_traction_element_pt.push_back(outlet_element);
      //Add the traction function
      outlet_element->traction_fct_pt() =
       &Global_Physical_Variables::hydrostatic_pressure;
      //Add the elements to the mesh
      Bulk_mesh_pt->add_element_pt(outlet_element);
     }
   }
References b, e(), and Global_Physical_Variables::hydrostatic_pressure().
delete_outlet_elements()
template<class ELEMENT > void AirwayReopeningProblem< ELEMENT >::delete_outlet_elements () inline
Delete the outlet elements.
   {
    unsigned n_outlet = Outlet_traction_element_pt.size();
    for(unsigned e=n_outlet;e>0;e--)
     {
      //Remove and delete the outlet elements
      Bulk_mesh_pt->element_pt().pop_back();
      delete Outlet_traction_element_pt[e-1];
      Outlet_traction_element_pt[e-1] = 0;
     }
    Outlet_traction_element_pt.clear();
   }
References e().
doc_solution()
template<class ELEMENT > void AirwayReopeningProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc the solution.
 {
  ofstream some_file;
  char filename[100];
  // Number of plot points
  unsigned npts=5;
  // Number of interface elements
 // unsigned ninterface=Bulk_mesh_pt->ninterface_element();
  // Number of spines
  //unsigned nspine=Bulk_mesh_pt->nspine();
  // Control coordinate: At bubble tip
  Vector<double> s(2);
  s[0]=1.0;
  s[1]=1.0;
  // Last proper spine
  unsigned last_spine=Bulk_mesh_pt->nfree_surface_spines()-1;
  // Doc
  Trace_file << " " << Global_Physical_Variables::Ca;
  Trace_file << " " << Global_Physical_Variables::Bo;
  Trace_file << " " << Global_Physical_Variables::Re;
  Trace_file << " " << Global_Physical_Variables::Tube_width;
  Trace_file << " " << get_outlet_flux();
  Trace_file << " " <<
   Upper_wall_mesh_pt->boundary_node_pt(0,0)->x(1);
  Trace_file << " " <<
   Upper_wall_mesh_pt->boundary_node_pt(1,0)->x(1);
  Trace_file << " " <<
   Lower_wall_mesh_pt->boundary_node_pt(0,0)->x(1);
  Trace_file << " " <<
   Lower_wall_mesh_pt->boundary_node_pt(1,0)->x(1);
  Trace_file << " " << Bubble_pressure_data_pt->value(0);
   Trace_file << " " << Bulk_mesh_pt->spine_pt(0)->height();
  Trace_file << " " << Bulk_mesh_pt->spine_pt(last_spine)->height();
  Trace_file << " " << 1.3375*pow(Global_Physical_Variables::Ca,2.0/3.0);
  Trace_file << " " <<
   (Bubble_pressure_data_pt->value(0)-Control_element_pt->interpolated_p_nst(s))*
                       Global_Physical_Variables::Ca;
  Trace_file << " " << 1.0+3.8*pow(Global_Physical_Variables::Ca,2.0/3.0);
  Trace_file << " " << Control_element_pt->interpolated_u_nst(s,0);
  Trace_file << " " << Control_element_pt->interpolated_u_nst(s,1);
  Trace_file << " "
 //             << abs(dynamic_cast<SpineLineFluidInterfaceElement<ELEMENT>*>(
 //                Bulk_mesh_pt->interface_element_pt(0))->
 //                actual_contact_angle_left())*
 //                180.0/MathematicalConstants::Pi << " " ;
 //  Trace_file << " "
 //             << abs(dynamic_cast<SpineLineFluidInterfaceElement<ELEMENT>*>(
 //                Bulk_mesh_pt->interface_element_pt(ninterface-1))->
 //                actual_contact_angle_right())*
 //                180.0/MathematicalConstants::Pi
             << " ";
  //Trace_file << get_outlet_flux() << " ";
  Trace_file << std::endl;
  // Output solution
  sprintf(filename,"%s/soln%i.dat",doc_info.directory().c_str(),
          doc_info.number());
  some_file.open(filename);
  unsigned n_bulk=Bulk_mesh_pt->nbulk();
  for(unsigned i=0;i<n_bulk;i++)
   {
    ELEMENT *el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->
                                            bulk_element_pt(i));
    el_pt->output(some_file,npts);
   }
  some_file.close();
 }
References Global_Physical_Variables::Bo, Global_Physical_Variables::Ca, oomph::DocInfo::directory(), MergeRestartFiles::filename, i, oomph::DocInfo::number(), Eigen::bfloat16_impl::pow(), Global_Physical_Variables::Re, s, oomph::Problem_Parameter::Trace_file, and Global_Physical_Variables::Tube_width.
dump()
template<class ELEMENT > void AirwayReopeningProblem< ELEMENT >::dump (ofstream & dump_file) const inline virtual
Dump the entire problem.
Reimplemented from oomph::Problem.
   {
    using namespace Global_Physical_Variables;
    dump_file << Re << std::endl;
    dump_file << ReSt << std::endl;
    dump_file << ReInvFr << std::endl;
    dump_file << Ca << std::endl;
    dump_file << Bo << std::endl;
    dump_file << Pext << std::endl;
    dump_file << G[0] << " " << G[1] << std::endl;
    dump_file << Nu << std::endl;
    dump_file << H << std::endl;
    dump_file << Gamma << std::endl;
    dump_file << T << std::endl;
    dump_file << Kstiff << std::endl;
    dump_file << Q << std::endl;
    dump_file << Kseparation << std::endl;
    dump_file << Tube_width << std::endl;
    dump_file << Ktable << std::endl;
    dump_file << Fixed_spine_height << std::endl;
    //Standard problem dumper
    Problem::dump(dump_file);
   }
References Global_Physical_Variables::Bo, Global_Physical_Variables::Ca, G, Global_Physical_Variables::Gamma, H, Global_Physical_Variables::Kseparation, Global_Physical_Variables::Kstiff, Global_Physical_Variables::Ktable, Constitutive_Parameters::Nu, Global_Physical_Variables::Pext, Global_Physical_Variables::Q, GlobalPhysicalVariables::Re, GlobalPhysicalVariables::ReInvFr, GlobalPhysicalVariables::ReSt, and Global_Physical_Variables::Tube_width.
fix_pressure()
template<class ELEMENT > void AirwayReopeningProblem< ELEMENT >::fix_pressure (const unsigned & e, const unsigned & l, const double & pvalue) inline
Fix pressure value l in element e to value p_value.
   {
    //Fix the pressure at that element
    dynamic_cast<ELEMENT *>(Bulk_mesh_pt->element_pt(e))->
     fix_pressure(l,pvalue);
   }
References e().
get_outlet_flux()
template<class ELEMENT > double AirwayReopeningProblem< ELEMENT >::get_outlet_flux () inline
   {
    if(dynamic_cast<SpineGravityTractionElement<ELEMENT>*>
       (Outlet_traction_element_pt[0])==0)
     {return 0.0;}
    double flux = 0.0;
    //Loop over the outlet and calculate the flux
    for(unsigned e=0;e<Outlet_traction_element_pt.size();e++)
     {
      flux += dynamic_cast<SpineGravityTractionElement<ELEMENT>*>
       (Outlet_traction_element_pt[e])->get_flux();
     }
    return flux;
   }
References e(), ProblemParameters::flux(), and oomph::get_flux().
parameter_study()
template<class ELEMENT > void AirwayReopeningProblem< ELEMENT >::parameter_study (const unsigned & nsteps, const bool & restart)
Run a parameter study; perform specified number of steps.
Parameter study.
 {
  double flux = 0.0;
  // Increase maximum residual
  Problem::Max_residuals=100.0;
  Problem::Max_newton_iterations=100;
  //Problem::Newton_solver_tolerance=1.0e-6;
  // Set output directory
  DocInfo doc_info;
  doc_info.set_directory("RESLT");
  doc_info.number()=0;
  /*double zeta_trans_start_lo = -1.0;
  double zeta_trans_end_lo = 1.5;
  double fraction = 0.45;*/
  // Open trace file
  char filename[100], dumpfile[100];
  sprintf(filename,"%s/trace.dat",doc_info.directory().c_str());
  Trace_file.open(filename);
  Trace_file << "VARIABLES=\"Ca\",";
  Trace_file << "\"h<sub>bottom</sub>\",\"h<sub>too</sub>\",";
  Trace_file << "\"h<sub>Bretherton</sub>\",\"p<sub>tip</sub>\",";
  Trace_file << "\"p<sub>tip (Bretherton)</sub>\",\"u<sub>stag</sub>\",";
  Trace_file << "\"v<sub>stag</sub>\"";
  Trace_file << "\"<greek>a</greek><sub>bottom</sub>\",";
  Trace_file << "\"<greek>a</greek><sub>top</sub>\"";
  Trace_file << std::endl;
  if(restart)
   {
    ifstream dumpfile("dump.dat");
    read(dumpfile);
    dumpfile.close();
   }
  // Initial scaling factor for Ca reduction
  //double factor=1.5;
  // Update so the initial domain shape is plotted properly
  Bulk_mesh_pt->node_update();
  //Doc initial solution
  doc_solution(doc_info);
  //Loop over the steps
  for(unsigned step=1;step<=nsteps;step++)
   {
    cout << std::endl << "STEP " << step << std::endl;
    //Solve
    cout << "Solving for capillary number: "
         << Global_Physical_Variables::Ca
         << " Bo = "
         << Global_Physical_Variables::Bo << std::endl;
    if((!restart) || (step > 1))
     {
      using namespace Global_Physical_Variables;
      newton_solve();
     }
    else
     {
      cout << "Restart skipping" << std::endl;
     }
    cout << "Bubble pressure is " << Bubble_pressure_data_pt->value(0) << std::endl;
    // Doc solution
    doc_info.number()++;
    doc_solution(doc_info);
    //Dump if we're solving a real problem
    if(step > 1)
     {
      using namespace Global_Physical_Variables;
      sprintf(dumpfile,
              "%s/dump.Ca_%g.Bo_%g.Re_%g.H_%g.TW_%g_Frac_%g.Kstiff_%g.dat",
              doc_info.directory().c_str(),
              Ca,Bo,Re,H,Tube_width,
              Mesh_fraction_at_transition_pt->value(0),Kstiff);
      ofstream dumpstream(dumpfile);
      dump(dumpstream);
      dumpstream.close();
      cout << "Actual flux is " << get_outlet_flux() << std::endl;
     }
    //First time round, unpin things
    if(step==1)
     {
      change_boundary_conditions();
      flux = Flux_constraint_pt->read_flux();
     }
    //Otherwise do our parameter study
    else
     {
      using namespace Global_Physical_Variables;
      //Now start to increase the flux
      //The computed flux is -0.389 or something so
      //if we start from -0.35 and subtract 0.05 we get 0.4
      //and then continue from the first time
      if(step==2) {flux = -0.35;}
      //Then worry about the flux
      if(flux > -2.0) {flux -= 0.05; Flux_constraint_pt->set_flux(flux);}
      else
       {
        if(flux < -2.0) {flux = -2.0; Flux_constraint_pt->set_flux(flux);}
        //Now increase the capillary number
        if(Ca < 0.1) {Ca += 0.01;}
        else
         {
          Ca = 0.1;
          //Finally reduce the spring stiffness
          Kstiff -= 0.5*1.0e-7;
         }
       }
     }
   }
 }
References Global_Physical_Variables::Bo, Global_Physical_Variables::Ca, oomph::DocInfo::directory(), MergeRestartFiles::filename, ProblemParameters::flux(), H, Global_Physical_Variables::Kstiff, oomph::Locate_zeta_helpers::Max_newton_iterations, oomph::DocInfo::number(), GlobalPhysicalVariables::Re, Eigen::TensorSycl::internal::read(), oomph::DocInfo::set_directory(), oomph::Problem_Parameter::Trace_file, and Global_Physical_Variables::Tube_width.
read()
template<class ELEMENT > void AirwayReopeningProblem< ELEMENT >::read (ifstream & restart_file) inline virtual
Read the entire problem.
Reimplemented from oomph::Problem.
   {
    using namespace Global_Physical_Variables;
    restart_file >> Re;
    restart_file >> ReSt;
    restart_file >> ReInvFr;
    restart_file >> Ca;
    restart_file >> Bo;
    restart_file >> Pext;
    restart_file >> G[0];
    restart_file >> G[1];
    restart_file >> Nu;
    restart_file >> H;
    restart_file >> Gamma;
    restart_file >> T;
    restart_file >> Kstiff;
    restart_file >> Q;
    restart_file >> Kseparation;
    restart_file >> Tube_width;
    restart_file >> Ktable;
    restart_file >> Fixed_spine_height;
    //Standard problem reader
    Problem::read(restart_file);
   }
References Global_Physical_Variables::Bo, Global_Physical_Variables::Ca, G, Global_Physical_Variables::Gamma, H, Global_Physical_Variables::Kseparation, Global_Physical_Variables::Kstiff, Global_Physical_Variables::Ktable, Constitutive_Parameters::Nu, Global_Physical_Variables::Pext, Global_Physical_Variables::Q, GlobalPhysicalVariables::Re, Eigen::TensorSycl::internal::read(), GlobalPhysicalVariables::ReInvFr, GlobalPhysicalVariables::ReSt, Global_Physical_Variables::T, and Global_Physical_Variables::Tube_width.
Member Data Documentation
Bubble_pressure_data_pt
template<class ELEMENT > Data* AirwayReopeningProblem< ELEMENT >::Bubble_pressure_data_pt private
Data value that represents the bubble pressure.
Bulk_mesh_pt
template<class ELEMENT > BrethertonSpineMesh<ELEMENT, SpineLineFluidInterfaceElement<ELEMENT> >* AirwayReopeningProblem< ELEMENT >::Bulk_mesh_pt private
Pointer to bulk mesh.
Constraint_mesh_pt
template<class ELEMENT > Mesh* AirwayReopeningProblem< ELEMENT >::Constraint_mesh_pt private
Pointer to the constraint mesh.
Control_element_pt
template<class ELEMENT > ELEMENT* AirwayReopeningProblem< ELEMENT >::Control_element_pt private
Pointer to control element.
Fixed_spine_height
template<class ELEMENT > double AirwayReopeningProblem< ELEMENT >::Fixed_spine_height private
Fixed height value.
Flux_constraint_pt
template<class ELEMENT > FluxConstraint* AirwayReopeningProblem< ELEMENT >::Flux_constraint_pt private
Flux constraint element.
Frontal_solver
template<class ELEMENT > bool AirwayReopeningProblem< ELEMENT >::Frontal_solver private
Boolean flag to specify the use of the frontal solver.
Gravity_traction_element_pt
template<class ELEMENT > Vector<FiniteElement*> AirwayReopeningProblem< ELEMENT >::Gravity_traction_element_pt private
Vector of pointers to the traction elements.
Lower_wall_mesh_pt
template<class ELEMENT > OneDLagrangianMesh<FSIHermiteBeamElement>* AirwayReopeningProblem< ELEMENT >::Lower_wall_mesh_pt private
Pointer to lower wall mesh.
Mesh_fraction_at_transition_pt
template<class ELEMENT > Data* AirwayReopeningProblem< ELEMENT >::Mesh_fraction_at_transition_pt private
Data value that represents the vertical fraction between the upper and lower walls of the centre of the spines at the point of transition of the spine mesh
Outlet_traction_element_pt
template<class ELEMENT > Vector<FiniteElement*> AirwayReopeningProblem< ELEMENT >::Outlet_traction_element_pt private
Vector of pointers to the outlet traciton elements.
Trace_file
template<class ELEMENT > ofstream AirwayReopeningProblem< ELEMENT >::Trace_file private
Trace file.
Undeformed_lower_wall_geom_pt
template<class ELEMENT > GeomObject* AirwayReopeningProblem< ELEMENT >::Undeformed_lower_wall_geom_pt private
Pointer to the Undeformed wall.
Undeformed_upper_wall_geom_pt
template<class ELEMENT > GeomObject* AirwayReopeningProblem< ELEMENT >::Undeformed_upper_wall_geom_pt private
Pointer to the Undeformed wall.
Upper_wall_mesh_pt
template<class ELEMENT > OneDLagrangianMesh<FSIHermiteBeamElement>* AirwayReopeningProblem< ELEMENT >::Upper_wall_mesh_pt private
Pointer to Wall mesh.
The documentation for this class was generated from the following file:
elastic_bretherton.cc