MercuryDPM: StokesFlowExactWind Namespace Reference
StokesFlowExactWind Namespace Reference
Functions
void get_wind (const Vector< double > &x, Vector< double > &wind)
Wind that represents a constantly translating sphere.
Detailed Description
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Function Documentation
get_wind()
void StokesFlowExactWind::get_wind (const Vector< double > & x, Vector< double > & wind)
Wind that represents a constantly translating sphere.
  {
   double x_sc = x[0] - 0.0;
   double z_sc = x[1] - Global_Parameters::Sphere_centre_z;
   double r = sqrt(x_sc*x_sc + z_sc*z_sc);
   double theta = atan2(x_sc,z_sc);
   double sp_r=0.5;
   double r_sc = r/sp_r;
   double u_r_sph = -(-1.0  + 1.5/(r_sc) - 0.5/(r_sc*r_sc*r_sc))*cos(theta);
   double u_theta_sph = -(1.0 - 0.75/(r_sc) - 0.25/(r_sc*r_sc*r_sc))*sin(theta);
   wind[0]= u_r_sph*sin(theta) + u_theta_sph*cos(theta);
   wind[1]= u_r_sph*cos(theta) - u_theta_sph*sin(theta);
  }
References atan2(), cos(), UniformPSDSelfTest::r, sin(), Global_Parameters::Sphere_centre_z, sqrt(), BiharmonicTestFunctions2::theta, and plotDoE::x.