MercuryDPM: HGridUpdateUnitTest.cpp File Reference
HGridUpdateUnitTest.cpp File Reference
#include <iostream>
#include <Species/LinearViscoelasticSpecies.h>
#include "Chute.h"
Classes
class DPM
In this file a cubic packing of 5^3 particles in a tri-axial box is created and allowed to settle under small gravity. After that Z statistics are calculated.
Functions
int main ()
Function Documentation
main()
int main ()
 {
     // Problem parameters
     DPM problem;
     problem.setFileType(FileType::NO_FILE);
     problem.setHGridCellOverSizeRatio(2);
     problem.setHGridUpdateEachTimeStep(false);
     problem.setName("HGridUpdateUnitTest");   // data output file name
     problem.setTimeStep(1e-4);
     problem.setTimeMax(10);
     problem.setDomain({0,0,0},{1,1,1});
     // Particle species
     LinearViscoelasticSpecies species;              // initialise species
     species.setDensity(2000);                       // particle density
     species.setCollisionTimeAndRestitutionCoefficient( 5e-3, 0.8, 1);
     auto s = problem.speciesHandler.copyAndAddObject(species);   // assign species to problem species handler
     SphericalParticle particle;
     particle.setSpecies(s);
     particle.setRadius(0.5);
     particle.setVelocity({1,0,0});
     auto p = problem.particleHandler.copyAndAddObject(particle);
     //logger(INFO,"Cell %",)
     //solve
     problem.solve();
     problem.hGridInfo();
     return 0;
 }
References e(), NO_FILE, p, problem, s, LinearViscoelasticNormalSpecies::setCollisionTimeAndRestitutionCoefficient(), ParticleSpecies::setDensity(), BaseParticle::setRadius(), BaseParticle::setSpecies(), and BaseInteractable::setVelocity().