MercuryDPM: SinSolution Namespace Reference
SinSolution Namespace Reference
Namespace for forced exact solution for UnsteadyHeat equation.
Functions
void get_exact_u (const double &t, const Vector< double > &x, Vector< double > &u)
Exact solution as a vector.
void get_exact_u (const double &t, const Vector< double > &x, double &u)
Exact solution as a scalar.
void get_source (const double &t, const Vector< double > &x, double &source)
Source function to make it an exact solution.
Variables
double U_shift =8.0
Detailed Description
Namespace for forced exact solution for UnsteadyHeat equation.
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Function Documentation
get_exact_u() [1/2]
void SinSolution::get_exact_u (const double & t, const Vector< double > & x, double & u)
Exact solution as a scalar.
   {
     // Cache the value of pi
     double pi=MathematicalConstants::Pi;
     // The full solution
     u=sin(pi*x[0])*sin(pi*x[1])*cos(2.0*pi*t)+U_shift;
   } // End of get_exact_u
References cos(), constants::pi, oomph::MathematicalConstants::Pi, sin(), plotPSD::t, U_shift, and plotDoE::x.
get_exact_u() [2/2]
void SinSolution::get_exact_u (const double & t, const Vector< double > & x, Vector< double > & u)
Exact solution as a vector.
   {
     // Cache the value of pi
     double pi=MathematicalConstants::Pi;
     // The full solution
     u[0]=sin(pi*x[0])*sin(pi*x[1])*cos(2.0*pi*t)+U_shift;
   } // End of get_exact_u
References cos(), constants::pi, oomph::MathematicalConstants::Pi, sin(), plotPSD::t, U_shift, and plotDoE::x.
Referenced by UnsteadyHeatProblem< ELEMENT >::apply_boundary_conditions(), and UnsteadyHeatProblem< ELEMENT >::doc_solution().
get_source()
void SinSolution::get_source (const double & t, const Vector< double > & x, double & source)
Source function to make it an exact solution.
   {
     // Cache the value of pi
     double pi=MathematicalConstants::Pi;
     // The temporal derivative of the solution
     double du_dt=-2.0*pi*sin(pi*x[0])*sin(pi*x[1])*sin(2.0*pi*t);
     // Second derivative of spatial contribution w.r.t. x
     double d2u_dx2=-pow(pi,2)*sin(pi*x[0])*sin(pi*x[1])*cos(2.0*pi*t);
     // Second derivative of spatial contribution w.r.t. y
     double d2u_dy2=-pow(pi,2)*sin(pi*x[0])*sin(pi*x[1])*cos(2.0*pi*t);
     // Assign the source function value
     source=-GlobalParameters::Alpha*du_dt+
            GlobalParameters::Beta*(d2u_dx2+d2u_dy2);
   } // End of get_source
References GlobalParameters::Alpha, GlobalParameters::Beta, cos(), constants::pi, oomph::MathematicalConstants::Pi, Eigen::bfloat16_impl::pow(), sin(), TestProblem::source(), plotPSD::t, and plotDoE::x.
Referenced by main().
Variable Documentation
U_shift
double SinSolution::U_shift =8.0
Referenced by get_exact_u().