MercuryDPM: Eigen::BlockSparseMatrixView< BlockSparseMatrixT > Class Template Reference
Eigen::BlockSparseMatrixView< BlockSparseMatrixT > Class Template Reference
#include <BlockSparseMatrix.h>
Classes
class InnerIterator
Public Types
enum {
Flags = BlockSparseMatrixT::Options , Options = BlockSparseMatrixT::Options , RowsAtCompileTime = BlockSparseMatrixT::RowsAtCompileTime , ColsAtCompileTime = BlockSparseMatrixT::ColsAtCompileTime ,
MaxColsAtCompileTime = BlockSparseMatrixT::MaxColsAtCompileTime , MaxRowsAtCompileTime = BlockSparseMatrixT::MaxRowsAtCompileTime
}
typedef Ref< typename BlockSparseMatrixT::BlockScalar > Scalar
typedef Ref< typename BlockSparseMatrixT::BlockRealScalar > RealScalar
typedef BlockSparseMatrixT::Index Index
typedef BlockSparseMatrixT Nested
Public Types inherited from Eigen::SparseMatrixBase< BlockSparseMatrixT >
enum
typedef internal::traits< BlockSparseMatrixT >::Scalar Scalar
typedef Scalar value_type
typedef internal::packet_traits< Scalar >::type PacketScalar
typedef internal::traits< BlockSparseMatrixT >::StorageKind StorageKind
typedef internal::traits< BlockSparseMatrixT >::StorageIndex StorageIndex
typedef internal::add_const_on_value_type_if_arithmetic< typename internal::packet_traits< Scalar >::type >::type PacketReturnType
typedef SparseMatrixBase StorageBaseType
typedef Matrix< StorageIndex, Dynamic, 1 > IndexVector
typedef Matrix< Scalar, Dynamic, 1 > ScalarVector
typedef std::conditional_t< NumTraits< Scalar >::IsComplex, CwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, Eigen::Transpose< const BlockSparseMatrixT > >, Transpose< const BlockSparseMatrixT > > AdjointReturnType
typedef Transpose< BlockSparseMatrixT > TransposeReturnType
typedef Transpose< const BlockSparseMatrixT > ConstTransposeReturnType
typedef SparseMatrix< Scalar, Flags &RowMajorBit ? RowMajor :ColMajor, StorageIndex > PlainObject
typedef NumTraits< Scalar >::Real RealScalar
typedef std::conditional_t< HasDirectAccess_, const Scalar &, Scalar > CoeffReturnType
typedef CwiseNullaryOp< internal::scalar_constant_op< Scalar >, Matrix< Scalar, Dynamic, Dynamic > > ConstantReturnType
typedef Matrix< Scalar, RowsAtCompileTime, ColsAtCompileTime > DenseMatrixType
typedef Matrix< Scalar, internal::max_size_prefer_dynamic(RowsAtCompileTime, ColsAtCompileTime), internal::max_size_prefer_dynamic(RowsAtCompileTime, ColsAtCompileTime)> SquareMatrixType
typedef EigenBase< BlockSparseMatrixT > Base
Public Types inherited from Eigen::EigenBase< BlockSparseMatrixT >
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< BlockSparseMatrixT >::StorageKind StorageKind
Public Member Functions
BlockSparseMatrixView (const BlockSparseMatrixT &spblockmat)
Index outerSize () const
Index cols () const
Index rows () const
Scalar coeff (Index row, Index col)
Scalar coeffRef (Index row, Index col)
Public Member Functions inherited from Eigen::SparseMatrixBase< BlockSparseMatrixT >
BlockSparseMatrixT & operator= (const EigenBase< OtherDerived > &other)
BlockSparseMatrixT & operator= (const ReturnByValue< OtherDerived > &other)
BlockSparseMatrixT & operator= (const SparseMatrixBase< OtherDerived > &other)
BlockSparseMatrixT & operator= (const BlockSparseMatrixT &other)
const BlockSparseMatrixT & derived () const
BlockSparseMatrixT & derived ()
BlockSparseMatrixT & const_cast_derived () const
Index rows () const
Index cols () const
Index size () const
bool isVector () const
Index outerSize () const
Index innerSize () const
bool isRValue () const
BlockSparseMatrixT & markAsRValue ()
SparseMatrixBase ()
BlockSparseMatrixT & operator+= (const SparseMatrixBase< OtherDerived > &other)
BlockSparseMatrixT & operator+= (const DiagonalBase< OtherDerived > &other)
BlockSparseMatrixT & operator+= (const EigenBase< OtherDerived > &other)
EIGEN_STRONG_INLINE BlockSparseMatrixT & operator+= (const SparseMatrixBase< OtherDerived > &other)
BlockSparseMatrixT & operator-= (const SparseMatrixBase< OtherDerived > &other)
BlockSparseMatrixT & operator-= (const DiagonalBase< OtherDerived > &other)
BlockSparseMatrixT & operator-= (const EigenBase< OtherDerived > &other)
EIGEN_STRONG_INLINE BlockSparseMatrixT & operator-= (const SparseMatrixBase< OtherDerived > &other)
BlockSparseMatrixT & operator*= (const Scalar &other)
BlockSparseMatrixT & operator*= (const SparseMatrixBase< OtherDerived > &other)
BlockSparseMatrixT & operator/= (const Scalar &other)
EIGEN_STRONG_INLINE const CwiseProductDenseReturnType< OtherDerived >::Type cwiseProduct (const MatrixBase< OtherDerived > &other) const
EIGEN_STRONG_INLINE const SparseMatrixBase< BlockSparseMatrixT >::template CwiseProductDenseReturnType< OtherDerived >::Type cwiseProduct (const MatrixBase< OtherDerived > &other) const
const Product< BlockSparseMatrixT, OtherDerived > operator* (const DiagonalBase< OtherDerived > &other) const
const Product< BlockSparseMatrixT, OtherDerived, AliasFreeProduct > operator* (const SparseMatrixBase< OtherDerived > &other) const
const Product< BlockSparseMatrixT, OtherDerived > operator* (const MatrixBase< OtherDerived > &other) const
SparseSymmetricPermutationProduct< BlockSparseMatrixT, Upper|Lower > twistedBy (const PermutationMatrix< Dynamic, Dynamic, StorageIndex > &perm) const
const TriangularView< const BlockSparseMatrixT, Mode > triangularView () const
ConstSelfAdjointViewReturnType< UpLo >::Type selfadjointView () const
SelfAdjointViewReturnType< UpLo >::Type selfadjointView ()
SparseMatrixBase< BlockSparseMatrixT >::template ConstSelfAdjointViewReturnType< UpLo >::Type selfadjointView () const
SparseMatrixBase< BlockSparseMatrixT >::template SelfAdjointViewReturnType< UpLo >::Type selfadjointView ()
Scalar dot (const MatrixBase< OtherDerived > &other) const
Scalar dot (const SparseMatrixBase< OtherDerived > &other) const
internal::traits< BlockSparseMatrixT >::Scalar dot (const MatrixBase< OtherDerived > &other) const
internal::traits< BlockSparseMatrixT >::Scalar dot (const SparseMatrixBase< OtherDerived > &other) const
RealScalar squaredNorm () const
RealScalar norm () const
RealScalar blueNorm () const
TransposeReturnType transpose ()
const ConstTransposeReturnType transpose () const
const AdjointReturnType adjoint () const
DenseMatrixType toDense () const
bool isApprox (const SparseMatrixBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool isApprox (const MatrixBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
const internal::eval< BlockSparseMatrixT >::type eval () const
Scalar sum () const
const SparseView< BlockSparseMatrixT > pruned (const Scalar &reference=Scalar(0), const RealScalar &epsilon=NumTraits< Scalar >::dummy_precision()) const
Public Member Functions inherited from Eigen::EigenBase< BlockSparseMatrixT >
constexpr EIGEN_DEVICE_FUNC BlockSparseMatrixT & derived ()
constexpr EIGEN_DEVICE_FUNC const BlockSparseMatrixT & derived () const
EIGEN_DEVICE_FUNC BlockSparseMatrixT & const_cast_derived () const
EIGEN_DEVICE_FUNC const BlockSparseMatrixT & const_derived () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index size () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< BlockSparseMatrixT, Device > device (Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< const BlockSparseMatrixT, Device > device (Device &device) const
Protected Attributes
const BlockSparseMatrixT & m_spblockmat
Protected Attributes inherited from Eigen::SparseMatrixBase< BlockSparseMatrixT >
bool m_isRValue
Additional Inherited Members
Protected Member Functions inherited from Eigen::SparseMatrixBase< BlockSparseMatrixT >
BlockSparseMatrixT & assign (const OtherDerived &other)
void assignGeneric (const OtherDerived &other)
Static Protected Member Functions inherited from Eigen::SparseMatrixBase< BlockSparseMatrixT >
static StorageIndex convert_index (const Index idx)
Member Typedef Documentation
Index
template<typename BlockSparseMatrixT > typedef BlockSparseMatrixT::Index Eigen::BlockSparseMatrixView< BlockSparseMatrixT >::Index
Nested
template<typename BlockSparseMatrixT > typedef BlockSparseMatrixT Eigen::BlockSparseMatrixView< BlockSparseMatrixT >::Nested
RealScalar
template<typename BlockSparseMatrixT > typedef Ref<typename BlockSparseMatrixT::BlockRealScalar> Eigen::BlockSparseMatrixView< BlockSparseMatrixT >::RealScalar
Scalar
template<typename BlockSparseMatrixT > typedef Ref<typename BlockSparseMatrixT::BlockScalar> Eigen::BlockSparseMatrixView< BlockSparseMatrixT >::Scalar
Member Enumeration Documentation
anonymous enum
template<typename BlockSparseMatrixT > anonymous enum
Enumerator
Flags
Options
RowsAtCompileTime
ColsAtCompileTime
MaxColsAtCompileTime
MaxRowsAtCompileTime
        {
     Flags = BlockSparseMatrixT::Options,
     Options = BlockSparseMatrixT::Options,
     RowsAtCompileTime = BlockSparseMatrixT::RowsAtCompileTime,
     ColsAtCompileTime = BlockSparseMatrixT::ColsAtCompileTime,
     MaxColsAtCompileTime = BlockSparseMatrixT::MaxColsAtCompileTime,
     MaxRowsAtCompileTime = BlockSparseMatrixT::MaxRowsAtCompileTime
   };
Constructor & Destructor Documentation
BlockSparseMatrixView()
template<typename BlockSparseMatrixT > Eigen::BlockSparseMatrixView< BlockSparseMatrixT >::BlockSparseMatrixView (const BlockSparseMatrixT & spblockmat) inline
 : m_spblockmat(spblockmat) {}
Member Function Documentation
coeff()
template<typename BlockSparseMatrixT > Scalar Eigen::BlockSparseMatrixView< BlockSparseMatrixT >::coeff (Index row, Index col) inline
 { return m_spblockmat.coeff(row, col); }
References col(), Eigen::BlockSparseMatrixView< BlockSparseMatrixT >::m_spblockmat, and row().
coeffRef()
template<typename BlockSparseMatrixT > Scalar Eigen::BlockSparseMatrixView< BlockSparseMatrixT >::coeffRef (Index row, Index col) inline
 { return m_spblockmat.coeffRef(row, col); }
References col(), Eigen::BlockSparseMatrixView< BlockSparseMatrixT >::m_spblockmat, and row().
cols()
template<typename BlockSparseMatrixT > Index Eigen::BlockSparseMatrixView< BlockSparseMatrixT >::cols () const inline
 { return m_spblockmat.blockCols(); }
References Eigen::BlockSparseMatrixView< BlockSparseMatrixT >::m_spblockmat.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), Eigen::BlockSparseMatrixView< BlockSparseMatrixT >::outerSize(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
outerSize()
template<typename BlockSparseMatrixT > Index Eigen::BlockSparseMatrixView< BlockSparseMatrixT >::outerSize () const inline
 { return (Flags & RowMajorBit) == 1 ? this->rows() : this->cols(); }
References Eigen::BlockSparseMatrixView< BlockSparseMatrixT >::cols(), Eigen::RowMajorBit, and Eigen::BlockSparseMatrixView< BlockSparseMatrixT >::rows().
rows()
template<typename BlockSparseMatrixT > Index Eigen::BlockSparseMatrixView< BlockSparseMatrixT >::rows () const inline
 { return m_spblockmat.blockRows(); }
References Eigen::BlockSparseMatrixView< BlockSparseMatrixT >::m_spblockmat.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), Eigen::BlockSparseMatrixView< BlockSparseMatrixT >::outerSize(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
Member Data Documentation
m_spblockmat
template<typename BlockSparseMatrixT > const BlockSparseMatrixT& Eigen::BlockSparseMatrixView< BlockSparseMatrixT >::m_spblockmat protected
Referenced by Eigen::BlockSparseMatrixView< BlockSparseMatrixT >::coeff(), Eigen::BlockSparseMatrixView< BlockSparseMatrixT >::coeffRef(), Eigen::BlockSparseMatrixView< BlockSparseMatrixT >::cols(), and Eigen::BlockSparseMatrixView< BlockSparseMatrixT >::rows().
The documentation for this class was generated from the following file:
BlockSparseMatrix.h