MercuryDPM: Eigen::internal::bitwise_binary_impl< Scalar, true > Struct Template Reference
Eigen::internal::bitwise_binary_impl< Scalar, true > Struct Template Reference
#include <BinaryFunctors.h>
Public Types
using Real = typename NumTraits< Scalar >::Real
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar run_and (const Scalar &a, const Scalar &b)
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar run_or (const Scalar &a, const Scalar &b)
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar run_xor (const Scalar &a, const Scalar &b)
Member Typedef Documentation
Real
template<typename Scalar > using Eigen::internal::bitwise_binary_impl< Scalar, true >::Real = typename NumTraits<Scalar>::Real
Member Function Documentation
run_and()
template<typename Scalar > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar Eigen::internal::bitwise_binary_impl< Scalar, true >::run_and (const Scalar & a, const Scalar & b) inline static
{
     Real real_result = bitwise_binary_impl<Real>::run_and(numext::real(a), numext::real(b));
     Real imag_result = bitwise_binary_impl<Real>::run_and(numext::imag(a), numext::imag(b));
     return Scalar(real_result, imag_result);
   }
References a, b, imag(), and Eigen::internal::bitwise_binary_impl< Scalar, IsComplex >::run_and().
run_or()
template<typename Scalar > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar Eigen::internal::bitwise_binary_impl< Scalar, true >::run_or (const Scalar & a, const Scalar & b) inline static
{
     Real real_result = bitwise_binary_impl<Real>::run_or(numext::real(a), numext::real(b));
     Real imag_result = bitwise_binary_impl<Real>::run_or(numext::imag(a), numext::imag(b));
     return Scalar(real_result, imag_result);
   }
References a, b, imag(), and Eigen::internal::bitwise_binary_impl< Scalar, IsComplex >::run_or().
run_xor()
template<typename Scalar > static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar Eigen::internal::bitwise_binary_impl< Scalar, true >::run_xor (const Scalar & a, const Scalar & b) inline static
{
     Real real_result = bitwise_binary_impl<Real>::run_xor(numext::real(a), numext::real(b));
     Real imag_result = bitwise_binary_impl<Real>::run_xor(numext::imag(a), numext::imag(b));
     return Scalar(real_result, imag_result);
   }
References a, b, imag(), and Eigen::internal::bitwise_binary_impl< Scalar, IsComplex >::run_xor().
The documentation for this struct was generated from the following file:
BinaryFunctors.h