MercuryDPM: fsi_channel_with_leaflet.cc File Reference
mpi/solvers/fsi_channel_with_leaflet.cc File Reference
#include "generic.h"
#include "beam.h"
#include "navier_stokes.h"
#include "meshes/channel_with_leaflet_mesh.h"
#include "meshes/one_d_lagrangian_mesh.h"
Classes
class UndeformedLeaflet
GeomObject: Undeformed straight, vertical leaflet.
class FSIChannelWithLeafletProblem< ELEMENT >
FSI leaflet in channel.
class SimpleFSIPreconditioner< MATRIX >
Namespaces
Global_Physical_Variables
Global variables.
Functions
double Global_Physical_Variables::flux (const double &t)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
//////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////// Driver code – pass a command line argument if you want to run the code in validation mode where it only performs a few steps
 {
 #ifdef OOMPH_HAS_MPI
  MPI_Helpers::init(argc,argv);
 #endif
  //Parameters for the leaflet: x-position of root and height
  double x_0 = 1.0;
  double hleaflet=0.5;
  // Number of elements in various regions of mesh
  unsigned nleft=6;
  unsigned nright=18;
  unsigned ny1=3;
  unsigned ny2=3;
  // Dimensions of fluid mesh: length to the left and right of leaflet
  // and total height
  double lleft =1.0;
  double lright=3.0;
  double htot=1.0;
  //Build the problem
  FSIChannelWithLeafletProblem<
   AlgebraicElement<RefineableQTaylorHoodElement<2> > >
   problem(lleft,lright,hleaflet,
           htot,nleft,nright,ny1,ny2,x_0);
  // Create the solver.
 #ifdef OOMPH_HAS_TRILINOS
  TrilinosAztecOOSolver* solver_pt = new TrilinosAztecOOSolver;
  solver_pt->solver_type() = TrilinosAztecOOSolver::GMRES;
 #else
  GMRES<CRDoubleMatrix>* solver_pt = new GMRES<CRDoubleMatrix>;
 #endif
  // Pass the solver to the problem.
  problem.linear_solver_pt() = solver_pt;
  // Create the preconditioner
  SimpleFSIPreconditioner<CRDoubleMatrix>* preconditioner_pt
   = new SimpleFSIPreconditioner<CRDoubleMatrix>(&problem);
  // Pass the meshes to the preconditioner.
  preconditioner_pt->set_navier_stokes_mesh(problem.fluid_mesh_pt());
  preconditioner_pt->set_solid_mesh(problem.solid_mesh_pt());
  // Pass the preconditioner to the solver
  solver_pt->preconditioner_pt() = preconditioner_pt;
  // Set up doc info
  DocInfo doc_info;
  doc_info.set_directory("RESLT");
  // Set max. number of adaptations
  unsigned max_adapt=3;
  // solve and document
  problem.steady_newton_solve(max_adapt);
  problem.doc_solution(doc_info);
 #ifdef OOMPH_HAS_MPI
  MPI_Helpers::finalize();
 #endif
 }//end of main
References oomph::IterativeLinearSolver::preconditioner_pt(), problem, oomph::DocInfo::set_directory(), oomph::SimpleFSIPreconditioner< MATRIX >::set_navier_stokes_mesh(), and oomph::TrilinosAztecOOSolver::solver_type().