MercuryDPM: Eigen::Ref< SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType > Class Template Reference
Eigen::Ref< SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType > Class Template Reference
Sparse linear algebra » Reference » SparseCore_Module
A sparse matrix expression referencing an existing sparse expression.
#include <SparseRef.h>
Public Types
typedef internal::SparseRefBase< Ref > Base
Public Types inherited from Eigen::internal::SparseRefBase< Ref< SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType > >
typedef SparseMapBase< Ref< SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType > > Base
Public Member Functions
template<int OtherOptions>
Ref (SparseMatrix< MatScalar, OtherOptions, MatIndex > &expr)
template<int OtherOptions>
Ref (Map< SparseMatrix< MatScalar, OtherOptions, MatIndex >> &expr)
template<typename Derived >
Ref (const SparseCompressedBase< Derived > &expr)
Public Member Functions inherited from Eigen::internal::SparseRefBase< Ref< SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType > >
SparseRefBase ()
Private Types
typedef SparseMatrix< MatScalar, MatOptions, MatIndex > PlainObjectType
typedef internal::traits< Ref > Traits
Private Member Functions
template<int OtherOptions>
Ref (const SparseMatrix< MatScalar, OtherOptions, MatIndex > &expr)
template<int OtherOptions>
Ref (const Map< SparseMatrix< MatScalar, OtherOptions, MatIndex >> &expr)
Additional Inherited Members
Protected Member Functions inherited from Eigen::internal::SparseRefBase< Ref< SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType > >
void construct (Expression &expr)
Detailed Description
template<typename MatScalar, int MatOptions, typename MatIndex, int Options, typename StrideType>
class Eigen::Ref< SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType >
A sparse matrix expression referencing an existing sparse expression.
Template Parameters
SparseMatrixType the equivalent sparse matrix type of the referenced data, it must be a template instance of class SparseMatrix.
Options specifies whether the a standard compressed format is required Options is StandardCompressedFormat, or 0. The default is 0.
See also
class Ref
Member Typedef Documentation
Base
template<typename MatScalar , int MatOptions, typename MatIndex , int Options, typename StrideType > typedef internal::SparseRefBase<Ref> Eigen::Ref< SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Base
PlainObjectType
template<typename MatScalar , int MatOptions, typename MatIndex , int Options, typename StrideType > typedef SparseMatrix<MatScalar, MatOptions, MatIndex> Eigen::Ref< SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType >::PlainObjectType private
Traits
template<typename MatScalar , int MatOptions, typename MatIndex , int Options, typename StrideType > typedef internal::traits<Ref> Eigen::Ref< SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Traits private
Constructor & Destructor Documentation
Ref() [1/5]
template<typename MatScalar , int MatOptions, typename MatIndex , int Options, typename StrideType > template<int OtherOptions> Eigen::Ref< SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref (const SparseMatrix< MatScalar, OtherOptions, MatIndex > & expr) inline private
Ref() [2/5]
template<typename MatScalar , int MatOptions, typename MatIndex , int Options, typename StrideType > template<int OtherOptions> Eigen::Ref< SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref (const Map< SparseMatrix< MatScalar, OtherOptions, MatIndex >> & expr) inline private
Ref() [3/5]
template<typename MatScalar , int MatOptions, typename MatIndex , int Options, typename StrideType > template<int OtherOptions> Eigen::Ref< SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref (SparseMatrix< MatScalar, OtherOptions, MatIndex > & expr) inline
{
     EIGEN_STATIC_ASSERT(
         bool(Traits::template match<SparseMatrix<MatScalar, OtherOptions, MatIndex>>::MatchAtCompileTime),
         STORAGE_LAYOUT_DOES_NOT_MATCH);
     eigen_assert(((Options & int(StandardCompressedFormat)) == 0) || (expr.isCompressed()));
     Base::construct(expr.derived());
   }
References Eigen::RefBase< Derived >::construct(), Eigen::SparseMatrixBase< Derived >::derived(), eigen_assert, EIGEN_STATIC_ASSERT, Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::isCompressed(), match(), and Eigen::StandardCompressedFormat.
Ref() [4/5]
template<typename MatScalar , int MatOptions, typename MatIndex , int Options, typename StrideType > template<int OtherOptions> Eigen::Ref< SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref (Map< SparseMatrix< MatScalar, OtherOptions, MatIndex >> & expr) inline
{
     EIGEN_STATIC_ASSERT(
         bool(Traits::template match<SparseMatrix<MatScalar, OtherOptions, MatIndex>>::MatchAtCompileTime),
         STORAGE_LAYOUT_DOES_NOT_MATCH);
     eigen_assert(((Options & int(StandardCompressedFormat)) == 0) || (expr.isCompressed()));
     Base::construct(expr.derived());
   }
References Eigen::RefBase< Derived >::construct(), eigen_assert, EIGEN_STATIC_ASSERT, match(), and Eigen::StandardCompressedFormat.
Ref() [5/5]
template<typename MatScalar , int MatOptions, typename MatIndex , int Options, typename StrideType > template<typename Derived > Eigen::Ref< SparseMatrix< MatScalar, MatOptions, MatIndex >, Options, StrideType >::Ref (const SparseCompressedBase< Derived > & expr) inline
   {
     EIGEN_STATIC_ASSERT(bool(internal::is_lvalue<Derived>::value), THIS_EXPRESSION_IS_NOT_A_LVALUE__IT_IS_READ_ONLY);
     EIGEN_STATIC_ASSERT(bool(Traits::template match<Derived>::MatchAtCompileTime), STORAGE_LAYOUT_DOES_NOT_MATCH);
     eigen_assert(((Options & int(StandardCompressedFormat)) == 0) || (expr.isCompressed()));
     Base::construct(expr.const_cast_derived());
   }
References Eigen::SparseMatrixBase< Derived >::const_cast_derived(), Eigen::RefBase< Derived >::construct(), eigen_assert, EIGEN_STATIC_ASSERT, Eigen::SparseCompressedBase< Derived >::isCompressed(), and Eigen::StandardCompressedFormat.
The documentation for this class was generated from the following file:
SparseRef.h