MercuryDPM: oomph::LinearSolver Class Reference
oomph::LinearSolver Class Reference abstract
#include <linear_solver.h>
Public Member Functions
LinearSolver ()
Empty constructor, initialise the member data.
LinearSolver (const LinearSolver &dummy)=delete
Broken copy constructor.
void operator= (const LinearSolver &)=delete
Broken assignment operator.
virtual ~LinearSolver ()
Empty virtual destructor.
void enable_doc_time ()
Enable documentation of solve times.
void disable_doc_time ()
Disable documentation of solve times.
bool is_doc_time_enabled () const
Is documentation of solve times enabled?
bool is_resolve_enabled () const
Boolean flag indicating if resolves are enabled.
virtual void enable_resolve ()
virtual void disable_resolve ()
virtual void solve (Problem *const &problem_pt, DoubleVector &result)=0
virtual void solve (DoubleMatrixBase *const &matrix_pt, const DoubleVector &rhs, DoubleVector &result)
virtual void solve (DoubleMatrixBase *const &matrix_pt, const Vector< double > &rhs, Vector< double > &result)
virtual void solve_transpose (Problem *const &problem_pt, DoubleVector &result)
virtual void solve_transpose (DoubleMatrixBase *const &matrix_pt, const DoubleVector &rhs, DoubleVector &result)
virtual void solve_transpose (DoubleMatrixBase *const &matrix_pt, const Vector< double > &rhs, Vector< double > &result)
virtual void resolve (const DoubleVector &rhs, DoubleVector &result)
virtual void resolve_transpose (const DoubleVector &rhs, DoubleVector &result)
virtual void clean_up_memory ()
virtual double jacobian_setup_time () const
virtual double linear_solver_solution_time () const
virtual void enable_computation_of_gradient ()
void disable_computation_of_gradient ()
void reset_gradient ()
void get_gradient (DoubleVector &gradient)
function to access the gradient, provided it has been computed
Public Member Functions inherited from oomph::DistributableLinearAlgebraObject
DistributableLinearAlgebraObject ()
Default constructor - create a distribution.
DistributableLinearAlgebraObject (const DistributableLinearAlgebraObject &matrix)=delete
Broken copy constructor.
void operator= (const DistributableLinearAlgebraObject &)=delete
Broken assignment operator.
virtual ~DistributableLinearAlgebraObject ()
Destructor.
LinearAlgebraDistribution * distribution_pt () const
access to the LinearAlgebraDistribution
unsigned nrow () const
access function to the number of global rows.
unsigned nrow_local () const
access function for the num of local rows on this processor.
unsigned nrow_local (const unsigned &p) const
access function for the num of local rows on this processor.
unsigned first_row () const
access function for the first row on this processor
unsigned first_row (const unsigned &p) const
access function for the first row on this processor
bool distributed () const
distribution is serial or distributed
bool distribution_built () const
void build_distribution (const LinearAlgebraDistribution *const dist_pt)
void build_distribution (const LinearAlgebraDistribution &dist)
Protected Attributes
bool Enable_resolve
bool Doc_time
Boolean flag that indicates whether the time taken.
bool Compute_gradient
bool Gradient_has_been_computed
flag that indicates whether the gradient was computed or not
DoubleVector Gradient_for_glob_conv_newton_solve
Additional Inherited Members
Protected Member Functions inherited from oomph::DistributableLinearAlgebraObject
void clear_distribution ()
Detailed Description
Base class for all linear solvers. This merely defines standard interfaces for linear solvers, so that different solvers can be used in a clean and transparent manner. Note that LinearSolvers are primarily used to solve the linear systems arising in oomph-lib's Newton iteration. Their primary solve function therefore takes a pointer to the associated problem, construct its Jacobian matrix and residual vector, and return the solution of the linear system formed by the Jacobian and the residual vector. We also provide broken virtual interfaces to a linear-algebra-type solve function in which the matrix and the rhs can be specified, but this are not guaranteed to implemented for all linear solvers (e.g. for frontal solvers).
Constructor & Destructor Documentation
LinearSolver() [1/2]
oomph::LinearSolver::LinearSolver () inline
Empty constructor, initialise the member data.
       : Enable_resolve(false),
         Doc_time(true),
         Compute_gradient(false),
         Gradient_has_been_computed(false)
     {
     }
LinearSolver() [2/2]
oomph::LinearSolver::LinearSolver (const LinearSolver & dummy) delete
Broken copy constructor.
~LinearSolver()
virtual oomph::LinearSolver::~LinearSolver () inline virtual
Empty virtual destructor.
 {}
Member Function Documentation
clean_up_memory()
virtual void oomph::LinearSolver::clean_up_memory () inline virtual
Empty virtual function that can be overloaded in specific linear solvers to clean up any memory that may have been allocated (e.g. when preparing for a re-solve).
Reimplemented in oomph::GMRESBlockPreconditioner, oomph::GMRESBlockPreconditioner, oomph::HelmholtzGMRESMG< MATRIX >, oomph::ComplexGMRES< MATRIX >, oomph::ComplexDampedJacobi< MATRIX >, oomph::TrilinosAztecOOSolver, oomph::MumpsSolver, oomph::SuperLUSolver, oomph::DenseLU, oomph::AugmentedProblemGMRES, oomph::GMRES< MATRIX >, oomph::DampedJacobi< MATRIX >, oomph::GS< CRDoubleMatrix >, oomph::GS< MATRIX >, oomph::BiCGStab< MATRIX >, oomph::CG< MATRIX >, oomph::HypreSolver, oomph::MGPreconditioner< DIM >, oomph::MGSolver< DIM >, and oomph::HSL_MA42.
 {}
Referenced by oomph::CRDoubleMatrix::clear().
disable_computation_of_gradient()
void oomph::LinearSolver::disable_computation_of_gradient () inline
function to disable the computation of the gradient required for the globally convergent Newton method
     {
       Compute_gradient = false;
     }
References Compute_gradient.
disable_doc_time()
void oomph::LinearSolver::disable_doc_time () inline
Disable documentation of solve times.
     {
       Doc_time = false;
     }
References Doc_time.
Referenced by oomph::NewMumpsPreconditioner::disable_doc_time(), oomph::HelmholtzMGPreconditioner< DIM >::disable_smoother_and_superlu_doc_time(), main(), parallel_test(), PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::PerturbedStateProblem(), oomph::ProblemBasedShiftInvertOperator::ProblemBasedShiftInvertOperator(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::project(), oomph::ARPACK::solve_eigenproblem(), oomph::SuperLUPreconditioner::SuperLUPreconditioner(), and TetmeshPoissonProblem< ELEMENT >::TetmeshPoissonProblem().
disable_resolve()
virtual void oomph::LinearSolver::disable_resolve () inline virtual
Disable resolve (i.e. store matrix and/or LU decomposition, say) This function simply resets an internal flag. It's virtual so it can be overloaded to perform additional tasks such as cleaning up memory that is only required for the resolve.
Reimplemented in oomph::HelmholtzGMRESMG< MATRIX >, oomph::ComplexGMRES< MATRIX >, oomph::TrilinosAztecOOSolver, oomph::MumpsSolver, oomph::SuperLUSolver, oomph::AugmentedProblemGMRES, oomph::GMRES< MATRIX >, oomph::GS< CRDoubleMatrix >, oomph::GS< MATRIX >, oomph::BiCGStab< MATRIX >, oomph::CG< MATRIX >, oomph::HypreSolver, and oomph::HSL_MA42.
     {
       Enable_resolve = false;
     }
References Enable_resolve.
Referenced by oomph::Problem::calculate_continuation_derivatives(), oomph::HSL_MA42::disable_resolve(), oomph::CG< MATRIX >::disable_resolve(), oomph::BiCGStab< MATRIX >::disable_resolve(), oomph::GS< MATRIX >::disable_resolve(), oomph::GS< CRDoubleMatrix >::disable_resolve(), oomph::GMRES< MATRIX >::disable_resolve(), oomph::AugmentedProblemGMRES::disable_resolve(), oomph::SuperLUSolver::disable_resolve(), oomph::MumpsSolver::disable_resolve(), oomph::ComplexGMRES< MATRIX >::disable_resolve(), oomph::HelmholtzGMRESMG< MATRIX >::disable_resolve(), oomph::FoldHandler::FoldHandler(), oomph::HopfHandler::HopfHandler(), oomph::Problem::newton_solve_continuation(), oomph::AugmentedBlockFoldLinearSolver::resolve(), oomph::BlockPitchForkLinearSolver::resolve(), oomph::AugmentedBlockPitchForkLinearSolver::resolve(), run_it(), oomph::AugmentedBlockFoldLinearSolver::solve(), oomph::BlockPitchForkLinearSolver::solve(), oomph::AugmentedBlockPitchForkLinearSolver::solve(), oomph::BlockHopfLinearSolver::solve(), oomph::ARPACK::solve_eigenproblem(), and oomph::BlockHopfLinearSolver::solve_for_two_rhs().
enable_computation_of_gradient()
virtual void oomph::LinearSolver::enable_computation_of_gradient () inline virtual
function to enable the computation of the gradient required for the globally convergent Newton method
Reimplemented in oomph::SuperLUSolver, and oomph::GMRES< MATRIX >.
     {
       throw OomphLibError(
         "enable_computation_of_gradient() not implemented for "
         "this linear solver",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::Problem::newton_solve().
enable_doc_time()
void oomph::LinearSolver::enable_doc_time () inline
Enable documentation of solve times.
     {
       Doc_time = true;
     }
References Doc_time.
Referenced by oomph::NewMumpsPreconditioner::enable_doc_time(), main(), and oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::project().
enable_resolve()
virtual void oomph::LinearSolver::enable_resolve () inline virtual
Enable resolve (i.e. store matrix and/or LU decomposition, say) Virtual so it can be overloaded to perform additional tasks
     {
       Enable_resolve = true;
     }
References Enable_resolve.
Referenced by oomph::ProblemBasedShiftInvertOperator::apply(), oomph::Problem::calculate_continuation_derivatives(), oomph::FoldHandler::FoldHandler(), oomph::Problem::get_inverse_mass_matrix_times_residuals(), oomph::HopfHandler::HopfHandler(), oomph::Problem::newton_solve(), oomph::Problem::newton_solve_continuation(), oomph::AugmentedBlockFoldLinearSolver::resolve(), oomph::BlockPitchForkLinearSolver::resolve(), oomph::AugmentedBlockPitchForkLinearSolver::resolve(), run_it(), oomph::AugmentedBlockFoldLinearSolver::solve(), oomph::BlockPitchForkLinearSolver::solve(), oomph::AugmentedBlockPitchForkLinearSolver::solve(), oomph::BlockHopfLinearSolver::solve(), oomph::ARPACK::solve_eigenproblem(), and oomph::BlockHopfLinearSolver::solve_for_two_rhs().
get_gradient()
void oomph::LinearSolver::get_gradient (DoubleVector & gradient) inline
function to access the gradient, provided it has been computed
     {
 #ifdef PARANOID
       if (Gradient_has_been_computed)
       {
 #endif
         gradient = Gradient_for_glob_conv_newton_solve;
 #ifdef PARANOID
       }
       else
       {
         throw OomphLibError(
           "The gradient has not been computed for this linear solver!",
           OOMPH_CURRENT_FUNCTION,
           OOMPH_EXCEPTION_LOCATION);
       }
 #endif
     }
References Gradient_for_glob_conv_newton_solve, Gradient_has_been_computed, OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::Problem::newton_solve().
is_doc_time_enabled()
bool oomph::LinearSolver::is_doc_time_enabled () const inline
Is documentation of solve times enabled?
     {
       return Doc_time;
     }
References Doc_time.
Referenced by oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::project().
is_resolve_enabled()
bool oomph::LinearSolver::is_resolve_enabled () const inline
Boolean flag indicating if resolves are enabled.
     {
       return Enable_resolve;
     }
References Enable_resolve.
Referenced by oomph::Problem::calculate_continuation_derivatives(), oomph::FoldHandler::FoldHandler(), oomph::HopfHandler::HopfHandler(), and oomph::Problem::newton_solve_continuation().
jacobian_setup_time()
virtual double oomph::LinearSolver::jacobian_setup_time () const inline virtual
returns the time taken to assemble the Jacobian matrix and residual vector (needs to be overloaded for each solver)
Reimplemented in oomph::SuperLUSolver, oomph::DenseLU, and oomph::IterativeLinearSolver.
     {
       throw OomphLibError(
         "jacobian_setup_time has not been implemented for this linear solver",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
       return 0;
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
linear_solver_solution_time()
virtual double oomph::LinearSolver::linear_solver_solution_time () const inline virtual
return the time taken to solve the linear system (needs to be overloaded for each linear solver)
Reimplemented in oomph::SuperLUSolver, oomph::DenseLU, and oomph::IterativeLinearSolver.
     {
       throw OomphLibError(
         "linear_solver_solution_time() not implemented for this linear solver",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
       return 0;
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
operator=()
void oomph::LinearSolver::operator= (const LinearSolver &) delete
Broken assignment operator.
reset_gradient()
void oomph::LinearSolver::reset_gradient () inline
function to reset the size of the gradient before each Newton solve
     {
       Gradient_for_glob_conv_newton_solve.clear();
     }
References oomph::DoubleVector::clear(), and Gradient_for_glob_conv_newton_solve.
Referenced by oomph::Problem::newton_solve().
resolve()
virtual void oomph::LinearSolver::resolve (const DoubleVector & rhs, DoubleVector & result) inline virtual
Resolve the system defined by the last assembled jacobian and the rhs vector. Solution is returned in the vector result. (broken virtual)
Reimplemented in oomph::TrilinosAztecOOSolver, oomph::HypreSolver, oomph::HelmholtzGMRESMG< MATRIX >, oomph::MumpsSolver, oomph::SuperLUSolver, oomph::AugmentedProblemGMRES, oomph::GMRES< MATRIX >, oomph::DampedJacobi< MATRIX >, oomph::GS< CRDoubleMatrix >, oomph::GS< MATRIX >, oomph::BiCGStab< MATRIX >, oomph::CG< MATRIX >, oomph::HSL_MA42, oomph::BlockHopfLinearSolver, oomph::AugmentedBlockPitchForkLinearSolver, oomph::BlockPitchForkLinearSolver, and oomph::AugmentedBlockFoldLinearSolver.
     {
       throw OomphLibError(
         "Resolve function not implemented for this linear solver",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::ProblemBasedShiftInvertOperator::apply(), oomph::Problem::calculate_continuation_derivatives(), oomph::FoldHandler::FoldHandler(), oomph::Problem::get_inverse_mass_matrix_times_residuals(), oomph::HopfHandler::HopfHandler(), oomph::Problem::newton_solve(), oomph::Problem::newton_solve_continuation(), oomph::AugmentedBlockFoldLinearSolver::resolve(), oomph::BlockPitchForkLinearSolver::resolve(), oomph::AugmentedBlockPitchForkLinearSolver::resolve(), run_it(), oomph::AugmentedBlockFoldLinearSolver::solve(), oomph::BlockPitchForkLinearSolver::solve(), oomph::AugmentedBlockPitchForkLinearSolver::solve(), oomph::BlockHopfLinearSolver::solve(), oomph::ARPACK::solve_eigenproblem(), and oomph::BlockHopfLinearSolver::solve_for_two_rhs().
resolve_transpose()
virtual void oomph::LinearSolver::resolve_transpose (const DoubleVector & rhs, DoubleVector & result) inline virtual
Solver: Resolve the system defined by the last assembled jacobian and the rhs vector. Solution is returned in the vector result. (broken virtual)
Reimplemented in oomph::SuperLUSolver.
     {
       // Create an output stream
       std::ostringstream error_message_stream;
       // Create the error message
       error_message_stream
         << "The function to resolve the transposed system has "
         << "not yet been\nimplemented for this solver." << std::endl;
       // Throw the error message
       throw OomphLibError(error_message_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     } // End of resolve_transpose
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
solve() [1/3]
virtual void oomph::LinearSolver::solve (DoubleMatrixBase *const & matrix_pt, const DoubleVector & rhs, DoubleVector & result) inline virtual
Linear-algebra-type solver: Takes pointer to a matrix and rhs vector and returns the solution of the linear system.
Reimplemented in oomph::HelmholtzGMRESMG< MATRIX >, oomph::TrilinosAztecOOSolver, oomph::AugmentedProblemGMRES, oomph::GMRES< MATRIX >, oomph::DampedJacobi< MATRIX >, oomph::GS< CRDoubleMatrix >, oomph::GS< MATRIX >, oomph::BiCGStab< MATRIX >, oomph::CG< MATRIX >, oomph::HypreSolver, oomph::MumpsSolver, oomph::SuperLUSolver, oomph::FD_LU, oomph::DenseLU, oomph::HSL_MA42, oomph::BlockHopfLinearSolver, oomph::AugmentedBlockPitchForkLinearSolver, oomph::BlockPitchForkLinearSolver, and oomph::AugmentedBlockFoldLinearSolver.
     {
       throw OomphLibError(
         "DoubleVector based solve function not implemented for this solver",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
solve() [2/3]
virtual void oomph::LinearSolver::solve (DoubleMatrixBase *const & matrix_pt, const Vector< double > & rhs, Vector< double > & result) inline virtual
Linear-algebra-type solver: Takes pointer to a matrix and rhs vector and returns the solution of the linear system.
Reimplemented in oomph::HelmholtzGMRESMG< MATRIX >, oomph::ComplexGMRES< MATRIX >, oomph::FD_LU, oomph::DenseLU, oomph::AugmentedProblemGMRES, oomph::GMRES< MATRIX >, oomph::GS< CRDoubleMatrix >, oomph::GS< MATRIX >, oomph::BiCGStab< MATRIX >, oomph::HSL_MA42, oomph::BlockHopfLinearSolver, oomph::AugmentedBlockPitchForkLinearSolver, oomph::BlockPitchForkLinearSolver, and oomph::AugmentedBlockFoldLinearSolver.
     {
       throw OomphLibError(
         "Vector<double> based solve function not implemented for this solver",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
solve() [3/3]
virtual void oomph::LinearSolver::solve (Problem *const & problem_pt, DoubleVector & result) pure virtual
Solver: Takes pointer to problem and returns the results vector which contains the solution of the linear system defined by the problem's fully assembled Jacobian and residual vector.
Implemented in oomph::TrilinosAztecOOSolver, oomph::HypreSolver, oomph::GMRESBlockPreconditioner, oomph::GMRESBlockPreconditioner, oomph::HelmholtzFGMRESMG< MATRIX >, oomph::HelmholtzGMRESMG< MATRIX >, oomph::ComplexGMRES< MATRIX >, oomph::ComplexDampedJacobi< MATRIX >, oomph::MumpsSolver, oomph::SuperLUSolver, oomph::FD_LU, oomph::DenseLU, oomph::AugmentedProblemGMRES, oomph::GMRES< MATRIX >, oomph::DampedJacobi< MATRIX >, oomph::GS< CRDoubleMatrix >, oomph::GS< MATRIX >, oomph::BiCGStab< MATRIX >, oomph::CG< MATRIX >, oomph::MGSolver< DIM >, oomph::HSL_MA42, oomph::BlockHopfLinearSolver, oomph::AugmentedBlockPitchForkLinearSolver, oomph::BlockPitchForkLinearSolver, and oomph::AugmentedBlockFoldLinearSolver.
Referenced by oomph::ProblemBasedShiftInvertOperator::apply(), oomph::Problem::calculate_continuation_derivatives(), oomph::FoldHandler::FoldHandler(), oomph::Problem::get_inverse_mass_matrix_times_residuals(), oomph::HopfHandler::HopfHandler(), oomph::Problem::newton_solve(), oomph::Problem::newton_solve_continuation(), run_it(), oomph::SolidICProblem::set_newmark_initial_condition_consistently(), oomph::HSL_MA42::solve(), oomph::BiCGStab< MATRIX >::solve(), oomph::GS< MATRIX >::solve(), oomph::GS< CRDoubleMatrix >::solve(), oomph::GMRES< MATRIX >::solve(), oomph::AugmentedProblemGMRES::solve(), oomph::FD_LU::solve(), oomph::ComplexGMRES< MATRIX >::solve(), oomph::HelmholtzGMRESMG< MATRIX >::solve(), oomph::DoubleMatrixBase::solve(), oomph::AugmentedBlockFoldLinearSolver::solve(), oomph::BlockPitchForkLinearSolver::solve(), oomph::AugmentedBlockPitchForkLinearSolver::solve(), oomph::BlockHopfLinearSolver::solve(), oomph::ARPACK::solve_eigenproblem(), and oomph::BlockHopfLinearSolver::solve_for_two_rhs().
solve_transpose() [1/3]
virtual void oomph::LinearSolver::solve_transpose (DoubleMatrixBase *const & matrix_pt, const DoubleVector & rhs, DoubleVector & result) inline virtual
Linear-algebra-type solver: Takes pointer to a matrix and rhs vector and returns the solution of the linear system.
Reimplemented in oomph::SuperLUSolver.
     {
       throw OomphLibError(
         "DoubleVector based solve function not implemented for this solver",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
solve_transpose() [2/3]
virtual void oomph::LinearSolver::solve_transpose (DoubleMatrixBase *const & matrix_pt, const Vector< double > & rhs, Vector< double > & result) inline virtual
Linear-algebra-type solver: Takes pointer to a matrix and rhs vector and returns the solution of the linear system.
     {
       throw OomphLibError(
         "Vector<double> based solve function not implemented for this solver",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
solve_transpose() [3/3]
virtual void oomph::LinearSolver::solve_transpose (Problem *const & problem_pt, DoubleVector & result) inline virtual
Solver: Takes pointer to problem and returns the results vector which contains the solution of the linear system defined by the problem's fully assembled Jacobian and residual vector (broken virtual).
Reimplemented in oomph::SuperLUSolver.
     {
       // Create an output stream
       std::ostringstream error_message_stream;
       // Create the error message
       error_message_stream << "The function to solve the transposed system has "
                            << "not yet been\nimplemented for this solver."
                            << std::endl;
       // Throw the error message
       throw OomphLibError(error_message_stream.str(),
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     } // End of solve_transpose
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Member Data Documentation
Compute_gradient
bool oomph::LinearSolver::Compute_gradient protected
flag that indicates whether the gradient required for the globally convergent Newton method should be computed or not
Referenced by disable_computation_of_gradient(), oomph::GMRES< MATRIX >::enable_computation_of_gradient(), oomph::SuperLUSolver::enable_computation_of_gradient(), oomph::SuperLUSolver::solve(), and oomph::SuperLUSolver::solve_transpose().
Doc_time
bool oomph::LinearSolver::Doc_time protected
Boolean flag that indicates whether the time taken.
Referenced by oomph::MumpsSolver::backsub(), oomph::DenseLU::DenseLU(), disable_doc_time(), oomph::MGSolver< DIM >::disable_output(), oomph::MGSolver< DIM >::disable_v_cycle_output(), enable_doc_time(), oomph::MGSolver< DIM >::enable_output(), oomph::MGSolver< DIM >::enable_v_cycle_output(), oomph::MumpsSolver::factorise(), oomph::HypreSolver::HypreSolver(), is_doc_time_enabled(), oomph::GMRESBlockPreconditioner::preconditioner_solve(), oomph::SuperLUSolver::resolve(), oomph::MumpsSolver::resolve(), oomph::HypreSolver::resolve(), oomph::TrilinosAztecOOSolver::resolve(), oomph::SuperLUSolver::resolve_transpose(), oomph::MumpsSolver::solve(), oomph::GS< CRDoubleMatrix >::solve(), oomph::AugmentedProblemGMRES::solve(), oomph::DenseLU::solve(), oomph::FD_LU::solve(), oomph::SuperLUSolver::solve(), oomph::HelmholtzGMRESMG< MATRIX >::solve(), oomph::HelmholtzFGMRESMG< MATRIX >::solve(), oomph::HypreSolver::solve(), oomph::TrilinosAztecOOSolver::solve(), oomph::GS< CRDoubleMatrix >::solve_helper(), oomph::AugmentedProblemGMRES::solve_helper(), oomph::SuperLUSolver::solve_transpose(), oomph::TrilinosAztecOOSolver::solve_using_AztecOO(), and oomph::TrilinosAztecOOSolver::solver_setup().
Enable_resolve
bool oomph::LinearSolver::Enable_resolve protected
Boolean that indicates whether the matrix (or its factors, in the case of direct solver) should be stored so that the resolve function can be used.
Referenced by oomph::HypreSolver::disable_resolve(), disable_resolve(), oomph::TrilinosAztecOOSolver::disable_resolve(), enable_resolve(), is_resolve_enabled(), oomph::DenseLU::solve(), oomph::SuperLUSolver::solve(), oomph::MumpsSolver::solve(), oomph::CG< MATRIX >::solve(), oomph::BiCGStab< MATRIX >::solve(), oomph::GS< MATRIX >::solve(), oomph::DampedJacobi< MATRIX >::solve(), oomph::GMRES< MATRIX >::solve(), oomph::TrilinosAztecOOSolver::solve(), oomph::AugmentedBlockFoldLinearSolver::solve(), oomph::BlockPitchForkLinearSolver::solve(), oomph::AugmentedBlockPitchForkLinearSolver::solve(), oomph::BlockHopfLinearSolver::solve(), oomph::HSL_MA42::solve(), oomph::GS< CRDoubleMatrix >::solve(), oomph::AugmentedProblemGMRES::solve(), oomph::HelmholtzGMRESMG< MATRIX >::solve(), oomph::HelmholtzFGMRESMG< MATRIX >::solve(), oomph::HypreSolver::solve(), oomph::HSL_MA42::solve_for_one_dof(), oomph::BlockHopfLinearSolver::solve_for_two_rhs(), and oomph::SuperLUSolver::solve_transpose().
Gradient_for_glob_conv_newton_solve
DoubleVector oomph::LinearSolver::Gradient_for_glob_conv_newton_solve protected
DoubleVector storing the gradient for the globally convergent Newton method
Referenced by get_gradient(), reset_gradient(), oomph::SuperLUSolver::solve(), and oomph::SuperLUSolver::solve_transpose().
Gradient_has_been_computed
bool oomph::LinearSolver::Gradient_has_been_computed protected
flag that indicates whether the gradient was computed or not
Referenced by get_gradient(), oomph::SuperLUSolver::solve(), and oomph::SuperLUSolver::solve_transpose().
The documentation for this class was generated from the following file:
linear_solver.h