MercuryDPM: oomph::CollapsibleChannelDomain Class Reference
oomph::CollapsibleChannelDomain Class Reference
Collapsible channel domain.
#include <collapsible_channel_domain.h>
Public Types
typedef double(* BLSquashFctPt) (const double &s)
typedef double(* AxialSpacingFctPt) (const double &xi)
Public Member Functions
CollapsibleChannelDomain (const unsigned &nup, const unsigned &ncollapsible, const unsigned &ndown, const unsigned &ny, const double &lup, const double &lcollapsible, const double &ldown, const double &ly, GeomObject *wall_pt)
~CollapsibleChannelDomain ()
Destructor: emtpy; cleanup done in base class.
unsigned nup ()
Number of vertical columns of macro elements the upstream section.
unsigned ncollapsible ()
Number of vertical clumns of macro elements in the "collapsible" segment.
unsigned ndown ()
Number of vertical columns of macro elements in the downstream section.
unsigned ny ()
Number of macro-elements across the channel.
double l_up ()
Length of upstream section.
double l_collapsible ()
Length of collapsible segment.
double l_down ()
Length of downstream section.
double l_y ()
Width of channel.
GeomObject *& wall_pt ()
GeomObject * wall_pt () const
BLSquashFctPt & bl_squash_fct_pt ()
double s_squash (const double &s)
AxialSpacingFctPt & axial_spacing_fct_pt ()
double axial_spacing_fct (const double &xi)
void macro_element_boundary (const unsigned &t, const unsigned &imacro, const unsigned &idirect, const Vector< double > &zeta, Vector< double > &r)
void enable_rotate_domain ()
Rotate the domain (for axisymmetric problems)
void disable_rotate_domain ()
Undo rotation of the domain (for axisymmetric problems)
Public Member Functions inherited from oomph::Domain
Domain ()
Constructor.
Domain (const Domain &)=delete
Broken copy constructor.
void operator= (const Domain &)=delete
Broken assignment operator.
virtual ~Domain ()
MacroElement * macro_element_pt (const unsigned &i)
Access to i-th macro element.
unsigned nmacro_element ()
Number of macro elements in domain.
void output (const std::string &filename, const unsigned &nplot)
Output macro elements.
void output (std::ostream &outfile, const unsigned &nplot)
Output macro elements.
virtual void macro_element_boundary (const double &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void macro_element_boundary (const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void output_macro_element_boundaries (const std::string &filename, const unsigned &nplot)
Output all macro element boundaries as tecplot zones.
void output_macro_element_boundaries (std::ostream &outfile, const unsigned &nplot)
Output all macro element boundaries as tecplot zones.
virtual void dmacro_element_boundary (const unsigned &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
virtual void dmacro_element_boundary (const double &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void dmacro_element_boundary (const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
virtual void d2macro_element_boundary (const unsigned &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
virtual void d2macro_element_boundary (const double &t, const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
void d2macro_element_boundary (const unsigned &i_macro, const unsigned &i_direct, const Vector< double > &s, Vector< double > &f)
Static Public Member Functions
static double default_BL_squash_fct (const double &s)
Private Member Functions
void r_N_straight (const Vector< double > &zeta, Vector< double > &r, const unsigned &imacro, const unsigned &part)
void r_W_straight (const Vector< double > &zeta, Vector< double > &r, const unsigned &imacro, const unsigned &part)
void r_S_straight (const Vector< double > &zeta, Vector< double > &r, const unsigned &imacro, const unsigned &part)
void r_E_straight (const Vector< double > &zeta, Vector< double > &r, const unsigned &imacro, const unsigned &part)
void r_N_collapsible (const unsigned &t, const Vector< double > &zeta, Vector< double > &r, const unsigned &imacro)
void r_W_collapsible (const unsigned &t, const Vector< double > &zeta, Vector< double > &r, const unsigned &imacro)
void r_S_collapsible (const unsigned &t, const Vector< double > &zeta, Vector< double > &r, const unsigned &imacro)
void r_E_collapsible (const unsigned &t, const Vector< double > &zeta, Vector< double > &r, const unsigned &imacro)
Static Private Member Functions
static double default_axial_spacing_fct (const double &xi)
Private Attributes
BLSquashFctPt BL_squash_fct_pt
AxialSpacingFctPt Axial_spacing_fct_pt
unsigned Nup
Number of vertical element columns in upstream section.
unsigned Ncollapsible
Number of vertical element columns in "collapsible" section.
unsigned Ndown
Number of vertical element columns in downstream section.
unsigned Ny
Number of macro elements across channel.
double Lup
x-length in the upstream part of the channel
double Lcollapsible
x-length in the "collapsible" part of the channel
double Ldown
x-length in the downstream part of the channel
double Ly
Width.
GeomObject * Wall_pt
Pointer to the geometric object that parametrises the collapsible wall.
bool Rotate_domain
Rotate domain (for axisymmetric problems, say)
Additional Inherited Members
Protected Attributes inherited from oomph::Domain
Vector< MacroElement * > Macro_element_pt
Vector of pointers to macro elements.
Detailed Description
Collapsible channel domain.
Member Typedef Documentation
AxialSpacingFctPt
typedef double(* oomph::CollapsibleChannelDomain::AxialSpacingFctPt) (const double &xi)
Typedef for function pointer for function that implements axial spacing of macro elements
BLSquashFctPt
typedef double(* oomph::CollapsibleChannelDomain::BLSquashFctPt) (const double &s)
Typedef for function pointer for function that squashes the macro elements near the wall to help resolution of any wall boundary layers.
Constructor & Destructor Documentation
CollapsibleChannelDomain()
oomph::CollapsibleChannelDomain::CollapsibleChannelDomain (const unsigned & nup, const unsigned & ncollapsible, const unsigned & ndown, const unsigned & ny, const double & lup, const double & lcollapsible, const double & ldown, const double & ly, GeomObject * wall_pt) inline
Constructor: Pass the number of (macro-)elements, the domain lengths in the x- and y-direction and the pointer to the geometric object that specifies the shape of the "collapsible" segment.
       : BL_squash_fct_pt(&default_BL_squash_fct),
         Axial_spacing_fct_pt(&default_axial_spacing_fct),
         Rotate_domain(false)
     {
       Nup = nup;
       Ncollapsible = ncollapsible;
       Ndown = ndown;
       Ny = ny;
       Lup = lup;
       Lcollapsible = lcollapsible;
       Ldown = ldown;
       Ly = ly;
       Wall_pt = wall_pt;
       // Total number of macro elements
       unsigned nmacro = (Nup + Ncollapsible + Ndown) * Ny;
       // Build the macro elements
       Macro_element_pt.resize(nmacro);
       for (unsigned i = 0; i < nmacro; i++)
       {
         Macro_element_pt[i] = new QMacroElement<2>(this, i);
       }
     }
References i, Lcollapsible, Ldown, Lup, Mesh_Parameters::ly, Ly, oomph::Domain::Macro_element_pt, ncollapsible(), Ncollapsible, ndown(), Ndown, nup(), Nup, ny(), Ny, wall_pt(), and Wall_pt.
~CollapsibleChannelDomain()
oomph::CollapsibleChannelDomain::~CollapsibleChannelDomain () inline
Destructor: emtpy; cleanup done in base class.
 {}
Member Function Documentation
axial_spacing_fct()
double oomph::CollapsibleChannelDomain::axial_spacing_fct (const double & xi) inline
Function that implements axial spacing of macro elements
     {
       return Axial_spacing_fct_pt(xi);
     }
References Axial_spacing_fct_pt.
Referenced by r_E_straight(), r_N_straight(), r_S_straight(), and r_W_straight().
axial_spacing_fct_pt()
AxialSpacingFctPt& oomph::CollapsibleChannelDomain::axial_spacing_fct_pt () inline
Function pointer for function that implements axial spacing of macro elements
     {
       return Axial_spacing_fct_pt;
     }
References Axial_spacing_fct_pt.
Referenced by oomph::CollapsibleChannelMesh< ELEMENT >::axial_spacing_fct_pt().
bl_squash_fct_pt()
BLSquashFctPt& oomph::CollapsibleChannelDomain::bl_squash_fct_pt () inline
Function pointer for function that squashes the macro elements near wall. Default mapping (identity) leaves the y-coordinate of the nodal points unchanged.
     {
       return BL_squash_fct_pt;
     }
References BL_squash_fct_pt.
Referenced by oomph::AlgebraicCollapsibleChannelMesh< ELEMENT >::AlgebraicCollapsibleChannelMesh(), oomph::CollapsibleChannelMesh< ELEMENT >::bl_squash_fct_pt(), and oomph::MyAlgebraicCollapsibleChannelMesh< ELEMENT >::MyAlgebraicCollapsibleChannelMesh().
default_axial_spacing_fct()
static double oomph::CollapsibleChannelDomain::default_axial_spacing_fct (const double & xi) inline static private
Default for function that implements axial spacing of macro elements
     {
       return xi;
     }
default_BL_squash_fct()
static double oomph::CollapsibleChannelDomain::default_BL_squash_fct (const double & s) inline static
Default for function that squashes the macro elements near the walls. Identity.
     {
       return s;
     }
References s.
disable_rotate_domain()
void oomph::CollapsibleChannelDomain::disable_rotate_domain () inline
Undo rotation of the domain (for axisymmetric problems)
     {
       Rotate_domain = false;
     }
References Rotate_domain.
enable_rotate_domain()
void oomph::CollapsibleChannelDomain::enable_rotate_domain () inline
Rotate the domain (for axisymmetric problems)
     {
       Rotate_domain = true;
     }
References Rotate_domain.
l_collapsible()
double oomph::CollapsibleChannelDomain::l_collapsible () inline
Length of collapsible segment.
     {
       return Lcollapsible;
     }
References Lcollapsible.
l_down()
double oomph::CollapsibleChannelDomain::l_down () inline
Length of downstream section.
     {
       return Ldown;
     }
References Ldown.
l_up()
double oomph::CollapsibleChannelDomain::l_up () inline
Length of upstream section.
     {
       return Lup;
     }
References Lup.
l_y()
double oomph::CollapsibleChannelDomain::l_y () inline
Width of channel.
     {
       return Ly;
     }
References Ly.
macro_element_boundary()
void oomph::CollapsibleChannelDomain::macro_element_boundary (const unsigned & t, const unsigned & imacro, const unsigned & idirect, const Vector< double > & zeta, Vector< double > & r) virtual
Vector representation of the imacro-th macro element boundary idirect (N/S/W/E) at time level t (t=0: present; t>0: previous): \({\bf r}({\bf zeta}) \) Note that the local coordinate zeta is a 1D Vector rather than a scalar – this is unavoidable because this function implements the pure virtual function in the Domain base class.
////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////// Vector representation of the imacro-th macro element boundary idirect (N/S/W/E) at time level t (t=0: present; t>0: previous): \({\bf r}({\bf zeta}) \) Note that the local coordinate zeta is a 1D Vector rather than a scalar – this is unavoidable because this function implements the pure virtual function in the Domain base class.
Implements oomph::Domain.
   {
     using namespace QuadTreeNames;
 #ifdef WARN_ABOUT_SUBTLY_CHANGED_OOMPH_INTERFACES
     // Warn about time argument being moved to the front
     OomphLibWarning(
       "Order of function arguments has changed between versions 0.8 and 0.85",
       "CollapsibleChannelDomain::macro_element_boundary(...)",
       OOMPH_EXCEPTION_LOCATION);
 #endif
     // Total number of vertical columns of (macro-)elements
     unsigned n_x = Nup + Ncollapsible + Ndown;
     // Which direction?
     if (idirect == N)
     {
       // Upstream part of the channel
       if ((imacro % n_x) < Nup)
       {
         r_N_straight(zeta, r, imacro, 0);
       }
       // Downstream part of channel
       else if ((imacro % n_x) >= Nup + Ncollapsible)
       {
         r_N_straight(zeta, r, imacro, 1);
       }
       // Collapsible segment
       else if (((imacro % n_x) < Nup + Ncollapsible) && ((imacro % n_x) >= Nup))
       {
         r_N_collapsible(t, zeta, r, imacro);
       }
       else
       {
         std::ostringstream error_stream;
         error_stream << "Never get here! imacro, idirect: " << imacro << " "
                      << idirect << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
     }
     else if (idirect == S)
     {
       // Upstream part
       if ((imacro % n_x) < Nup)
       {
         r_S_straight(zeta, r, imacro, 0);
       }
       // Downstream part
       else if ((imacro % n_x) >= Nup + Ncollapsible)
       {
         r_S_straight(zeta, r, imacro, 1);
       }
       // "Collapsible" bit
       else if (((imacro % n_x) < Nup + Ncollapsible) && ((imacro % n_x) >= Nup))
       {
         r_S_collapsible(t, zeta, r, imacro);
       }
       else
       {
         std::ostringstream error_stream;
         error_stream << "Never get here! imacro, idirect: " << imacro << " "
                      << idirect << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
     }
     else if (idirect == E)
     {
       // Upstream bit
       if ((imacro % n_x) < Nup)
       {
         r_E_straight(zeta, r, imacro, 0);
       }
       // Downstream bit
       else if ((imacro % n_x) >= Nup + Ncollapsible)
       {
         r_E_straight(zeta, r, imacro, 1);
       }
       // "Collapsible" bit
       else if (((imacro % n_x) < Nup + Ncollapsible) && ((imacro % n_x) >= Nup))
       {
         r_E_collapsible(t, zeta, r, imacro);
       }
       else
       {
         std::ostringstream error_stream;
         error_stream << "Never get here! imacro, idirect: " << imacro << " "
                      << idirect << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
     }
     else if (idirect == W)
     {
       // Upstream bit
       if ((imacro % n_x) < Nup)
       {
         r_W_straight(zeta, r, imacro, 0);
       }
       // Downstream bit
       else if ((imacro % n_x) >= Nup + Ncollapsible)
       {
         r_W_straight(zeta, r, imacro, 1);
       }
       // "Collapsible" bit
       else if (((imacro % n_x) < Nup + Ncollapsible) && ((imacro % n_x) >= Nup))
       {
         r_W_collapsible(t, zeta, r, imacro);
       }
       else
       {
         std::ostringstream error_stream;
         error_stream << "Never get here! imacro, idirect: " << imacro << " "
                      << idirect << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
     }
     // Rotate?
     if (Rotate_domain)
     {
       double radius = r[1];
       double z = r[0];
       r[0] = radius;
       r[1] = -z;
     }
   }
References Global_Physical_Variables::E, N, Ncollapsible, Ndown, Nup, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, UniformPSDSelfTest::r, r_E_collapsible(), r_E_straight(), r_N_collapsible(), r_N_straight(), r_S_collapsible(), r_S_straight(), r_W_collapsible(), r_W_straight(), UniformPSDSelfTest::radius, Rotate_domain, oomph::QuadTreeNames::S, plotPSD::t, oomph::QuadTreeNames::W, and Eigen::zeta().
ncollapsible()
unsigned oomph::CollapsibleChannelDomain::ncollapsible () inline
Number of vertical clumns of macro elements in the "collapsible" segment.
     {
       return Ncollapsible;
     }
References Ncollapsible.
Referenced by CollapsibleChannelDomain().
ndown()
unsigned oomph::CollapsibleChannelDomain::ndown () inline
Number of vertical columns of macro elements in the downstream section.
     {
       return Ndown;
     }
References Ndown.
Referenced by CollapsibleChannelDomain().
nup()
unsigned oomph::CollapsibleChannelDomain::nup () inline
Number of vertical columns of macro elements the upstream section.
     {
       return Nup;
     }
References Nup.
Referenced by CollapsibleChannelDomain().
ny()
unsigned oomph::CollapsibleChannelDomain::ny () inline
Number of macro-elements across the channel.
     {
       return Ny;
     }
References Ny.
Referenced by CollapsibleChannelDomain().
r_E_collapsible()
void oomph::CollapsibleChannelDomain::r_E_collapsible (const unsigned & t, const Vector< double > & zeta, Vector< double > & r, const unsigned & imacro) private
Eastern boundary of the macro element imacro in the collapsible section
Eastern edge of the macro element in the collapsible part of the channel; \(\zeta \in [-1,1] \)
   {
     // Determines the "coordinates" of the macro-element
     unsigned x = unsigned(imacro % (Nup + Ncollapsible + Ndown));
     unsigned y = unsigned(double(imacro) / double(Nup + Ncollapsible + Ndown));
     // Vector of Lagrangian coordinates
     Vector<double> xi(1);
     xi[0] = (double(x - Nup) + 1.0) * (Lcollapsible / double(Ncollapsible));
     // Position vector on upper wall:
     Vector<double> r_wall(2);
     Wall_pt->position(t, xi, r_wall);
     // Point will be located on straight line from bottom to top wall
     double fract = (double(y) + (0.5 * (1.0 + zeta[0]))) / double(Ny);
     // Map it via squash fct
     fract = s_squash(fract);
     // x-cooordinate -- straight line from fixed position on the bottom
     // wall to moving position on the top wall
     r[0] = Lup + xi[0] + (r_wall[0] - (xi[0] + Lup)) * fract;
     // y-coordinate
     r[1] = r_wall[1] * fract;
   }
References Lcollapsible, Lup, Ncollapsible, Ndown, Nup, Ny, oomph::GeomObject::position(), UniformPSDSelfTest::r, s_squash(), plotPSD::t, Wall_pt, plotDoE::x, y, and Eigen::zeta().
Referenced by macro_element_boundary().
r_E_straight()
void oomph::CollapsibleChannelDomain::r_E_straight (const Vector< double > & zeta, Vector< double > & r, const unsigned & imacro, const unsigned & part) private
Eastern boundary of the macro element imacro in the upstream (part=0) or downstream (part=1) sections
Eastern edge of the macro element in the straight parts of the channel; \(\zeta \in [-1,1] \) part=0 in the upstream part, part=1 in the downstream part
   {
     // Determines the "coordinates" of the macro-element
     unsigned x = unsigned(imacro % (Nup + Ncollapsible + Ndown));
     unsigned y = unsigned(double(imacro) / double(Nup + Ncollapsible + Ndown));
     // Where are we?
     switch (part)
     {
       case 0: // in the upstream part of the channel
         // Parametrizes the boundary
         r[0] = axial_spacing_fct((double(x) + 1.0) * (Lup / double(Nup)));
         r[1] = (double(y) + (0.5 * (1.0 + zeta[0]))) * (Ly / double(Ny));
         // Map it via squash fct
         r[1] = Ly * s_squash(r[1] / Ly);
         break;
       case 1: // in the downstream part of the channel
         // Parametrizes the boundary
         r[0] = axial_spacing_fct((double(x - Nup - Ncollapsible) + 1.0) *
                                    (Ldown / double(Ndown)) +
                                  Lup + Lcollapsible);
         r[1] = (double(y) + (0.5 * (1.0 + zeta[0]))) * (Ly / double(Ny));
         // Map it via squash fct
         r[1] = Ly * s_squash(r[1] / Ly);
         break;
       default:
         std::ostringstream error_stream;
         error_stream << "Never get here! part=" << part << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
   }
References axial_spacing_fct(), Lcollapsible, Ldown, Lup, Ly, Ncollapsible, Ndown, Nup, Ny, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, UniformPSDSelfTest::r, s_squash(), plotDoE::x, y, and Eigen::zeta().
Referenced by macro_element_boundary().
r_N_collapsible()
void oomph::CollapsibleChannelDomain::r_N_collapsible (const unsigned & t, const Vector< double > & zeta, Vector< double > & r, const unsigned & imacro) private
Northern boundary of the macro element imacro in the collapsible section
Northern edge of the macro element in the collapsible part of the channel; \(\zeta \in [-1,1] \)
   {
     // Determines the "coordinates" of the macro-element
     unsigned x = unsigned(imacro % (Nup + Ncollapsible + Ndown));
     unsigned y = unsigned(double(imacro) / double(Nup + Ncollapsible + Ndown));
     // Vector of Lagrangian coordinates
     Vector<double> xi(1);
     xi[0] = (double(x - Nup) + (0.5 * (1.0 + zeta[0]))) *
             (Lcollapsible / double(Ncollapsible));
     // Position vector on upper wall:
     Vector<double> r_wall(2);
     Wall_pt->position(t, xi, r_wall);
     // Point will be located on straight line from bottom to top wall
     double fract = (double(y) + 1.0) / double(Ny);
     // Map it via squash fct
     fract = s_squash(fract);
     // x-cooordinate -- straight line from fixed position on the bottom
     // wall to moving position on the top wall
     r[0] = Lup + xi[0] + (r_wall[0] - (xi[0] + Lup)) * fract;
     // y-coordinate
     r[1] = r_wall[1] * fract;
   }
References Lcollapsible, Lup, Ncollapsible, Ndown, Nup, Ny, oomph::GeomObject::position(), UniformPSDSelfTest::r, s_squash(), plotPSD::t, Wall_pt, plotDoE::x, y, and Eigen::zeta().
Referenced by macro_element_boundary().
r_N_straight()
void oomph::CollapsibleChannelDomain::r_N_straight (const Vector< double > & zeta, Vector< double > & r, const unsigned & imacro, const unsigned & part) private
Northern boundary of the macro element imacro in the upstream (part=0) or downstream (part=1) sections
Northern edge of the macro element in the straight parts of the channel; \(\zeta \in [-1,1] \) part=0 in the left part, part=1 in the right part
   {
     // Determines the "coordinates" of the macro-element
     unsigned x = unsigned(imacro % (Nup + Ncollapsible + Ndown));
     unsigned y = unsigned(double(imacro) / double(Nup + Ncollapsible + Ndown));
     // Where are we?
     switch (part)
     {
       case 0: // in the upstream part of the channel
         // Parametrizes the boundary
         r[0] = axial_spacing_fct((double(x) + (0.5 * (1.0 + zeta[0]))) *
                                  (Lup / double(Nup)));
         r[1] = (double(y) + 1.0) * (Ly / double(Ny));
         // Map it via squash fct
         r[1] = Ly * s_squash(r[1] / Ly);
         break;
       case 1: // in the downstream part of the channel
         // Parametrizes the boundary
         r[0] = axial_spacing_fct(
           (double(x - Nup - Ncollapsible) + (0.5 * (1.0 + zeta[0]))) *
             (Ldown / double(Ndown)) +
           Lup + Lcollapsible);
         r[1] = (double(y) + 1.0) * (Ly / double(Ny));
         // Map it via squash fct
         r[1] = Ly * s_squash(r[1] / Ly);
         break;
       default:
         std::ostringstream error_stream;
         error_stream << "Never get here! part=" << part << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
   }
References axial_spacing_fct(), Lcollapsible, Ldown, Lup, Ly, Ncollapsible, Ndown, Nup, Ny, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, UniformPSDSelfTest::r, s_squash(), plotDoE::x, y, and Eigen::zeta().
Referenced by macro_element_boundary().
r_S_collapsible()
void oomph::CollapsibleChannelDomain::r_S_collapsible (const unsigned & t, const Vector< double > & zeta, Vector< double > & r, const unsigned & imacro) private
Southern boundary of the macro element imacro in the collapsible section
Southern edge of the macro element in the collapsible part of the channel; \(\zeta \in [-1,1] \)
   {
     // Determines the "coordinates" of the macro-element
     unsigned x = unsigned(imacro % (Nup + Ncollapsible + Ndown));
     unsigned y = unsigned(double(imacro) / double(Nup + Ncollapsible + Ndown));
     // Vector of Lagrangian coordinates
     Vector<double> xi(1);
     xi[0] = (double(x - Nup) + (0.5 * (1.0 + zeta[0]))) *
             (Lcollapsible / double(Ncollapsible));
     // Position vector on upper wall:
     Vector<double> r_wall(2);
     Wall_pt->position(t, xi, r_wall);
     // Point will be located on straight line from bottom to top wall
     double fract = double(y) / double(Ny);
     // Map it via squash fct
     fract = s_squash(fract);
     // x-cooordinate -- straight line from fixed position on the bottom
     // wall to moving position on the top wall
     r[0] = Lup + xi[0] + (r_wall[0] - (xi[0] + Lup)) * fract;
     // y-coordinate
     r[1] = r_wall[1] * fract;
   }
References Lcollapsible, Lup, Ncollapsible, Ndown, Nup, Ny, oomph::GeomObject::position(), UniformPSDSelfTest::r, s_squash(), plotPSD::t, Wall_pt, plotDoE::x, y, and Eigen::zeta().
Referenced by macro_element_boundary().
r_S_straight()
void oomph::CollapsibleChannelDomain::r_S_straight (const Vector< double > & zeta, Vector< double > & r, const unsigned & imacro, const unsigned & part) private
Southern boundary of the macro element imacro in the upstream (part=0) or downstream (part=1) sections
Southern edge of the macro element in the straight parts of the channel; \(\zeta \in [-1,1] \) part=0 in the left part, part=1 in the right part
   {
     // Determines the "coordinates" of the macro-element
     unsigned x = unsigned(imacro % (Nup + Ncollapsible + Ndown));
     unsigned y = unsigned(double(imacro) / double(Nup + Ncollapsible + Ndown));
     // Where are we?
     switch (part)
     {
       case 0: // in the upstream bit
         // Parametrizes the boundary
         r[0] = axial_spacing_fct((double(x) + (0.5 * (1 + zeta[0]))) *
                                  (Lup / double(Nup)));
         r[1] = double(y) * (Ly / double(Ny));
         // Map it via squash fct
         r[1] = Ly * s_squash(r[1] / Ly);
         break;
       case 1: // in the downstream bit
         // Parametrizes the boundary
         r[0] = axial_spacing_fct(
           (double(x - Nup - Ncollapsible) + (0.5 * (1 + zeta[0]))) *
             (Ldown / double(Ndown)) +
           Lup + Lcollapsible);
         r[1] = double(y) * (Ly / double(Ny));
         // Map it via squash fct
         r[1] = Ly * s_squash(r[1] / Ly);
         break;
       default:
         std::ostringstream error_stream;
         error_stream << "Never get here! part=" << part << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
   }
References axial_spacing_fct(), Lcollapsible, Ldown, Lup, Ly, Ncollapsible, Ndown, Nup, Ny, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, UniformPSDSelfTest::r, s_squash(), plotDoE::x, y, and Eigen::zeta().
Referenced by macro_element_boundary().
r_W_collapsible()
void oomph::CollapsibleChannelDomain::r_W_collapsible (const unsigned & t, const Vector< double > & zeta, Vector< double > & r, const unsigned & imacro) private
Western boundary of the macro element imacro in the collapsible section
Western edge of the macro element in the collapsible part of the channel; \(\zeta \in [-1,1] \).
   {
     // Determines the "coordinates" of the macro-element
     unsigned x = unsigned(imacro % (Nup + Ncollapsible + Ndown));
     unsigned y = unsigned(double(imacro) / double(Nup + Ncollapsible + Ndown));
     // Vector of Lagrangian coordinates
     Vector<double> xi(1);
     xi[0] = double(x - Nup) * (Lcollapsible / double(Ncollapsible));
     // Position vector on upper wall:
     Vector<double> r_wall(2);
     Wall_pt->position(t, xi, r_wall);
     // Point will be located on straight line from bottom to top wall
     double fract = (double(y) + (0.5 * (1.0 + zeta[0]))) / double(Ny);
     // Map it via squash fct
     fract = s_squash(fract);
     // x-cooordinate -- straight line from fixed position on the bottom
     // wall to moving position on the top wall
     r[0] = Lup + xi[0] + (r_wall[0] - (xi[0] + Lup)) * fract;
     // y-coordinate
     r[1] = r_wall[1] * fract;
   }
References Lcollapsible, Lup, Ncollapsible, Ndown, Nup, Ny, oomph::GeomObject::position(), UniformPSDSelfTest::r, s_squash(), plotPSD::t, Wall_pt, plotDoE::x, y, and Eigen::zeta().
Referenced by macro_element_boundary().
r_W_straight()
void oomph::CollapsibleChannelDomain::r_W_straight (const Vector< double > & zeta, Vector< double > & r, const unsigned & imacro, const unsigned & part) private
Western boundary of the macro element imacro in the upstream (part=0) or downstream (part=1) sections
Western edge of the macro element in the upstream (part=0) or downstream (part=1) parts of the channel; \(\zeta \in [-1,1] \)
   {
     // Determines the "coordinates" of the macro-element
     unsigned x = unsigned(imacro % (Nup + Ncollapsible + Ndown));
     unsigned y = unsigned(double(imacro) / double(Nup + Ncollapsible + Ndown));
     // Where are we?
     switch (part)
     {
       case 0: // in the upstream part of the channel
         // Parametrize the boundary
         r[0] = axial_spacing_fct(double(x) * (Lup / double(Nup)));
         r[1] = (double(y) + (0.5 * (1.0 + zeta[0]))) * (Ly / double(Ny));
         // Map it via squash fct
         r[1] = Ly * s_squash(r[1] / Ly);
         break;
       case 1: // in the downstream part of the channel
         // Parametrizes the boundary
         r[0] = axial_spacing_fct(double(x - Nup - Ncollapsible) *
                                    (Ldown / double(Ndown)) +
                                  Lup + Lcollapsible);
         r[1] = (double(y) + (0.5 * (1.0 + zeta[0]))) * (Ly / double(Ny));
         // Map it via squash fct
         r[1] = Ly * s_squash(r[1] / Ly);
         break;
       default:
         std::ostringstream error_stream;
         error_stream << "Never get here! part=" << part << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
   }
References axial_spacing_fct(), Lcollapsible, Ldown, Lup, Ly, Ncollapsible, Ndown, Nup, Ny, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, UniformPSDSelfTest::r, s_squash(), plotDoE::x, y, and Eigen::zeta().
Referenced by macro_element_boundary().
s_squash()
double oomph::CollapsibleChannelDomain::s_squash (const double & s) inline
Function that squashes the macro elements near the wall. Input argument should vary between 0 and 1; function should return stretched/squashed coordinate in the same range. Default implementation is the identity; can be overloaded by specifying a different function pointer with bl_squash_fct_pt().
     {
       return BL_squash_fct_pt(s);
     }
References BL_squash_fct_pt, and s.
Referenced by r_E_collapsible(), r_E_straight(), r_N_collapsible(), r_N_straight(), r_S_collapsible(), r_S_straight(), r_W_collapsible(), and r_W_straight().
wall_pt() [1/2]
GeomObject*& oomph::CollapsibleChannelDomain::wall_pt () inline
Access to pointer to the geometric object that parametrises the collapsible wall
     {
       return Wall_pt;
     }
References Wall_pt.
Referenced by CollapsibleChannelDomain().
wall_pt() [2/2]
GeomObject* oomph::CollapsibleChannelDomain::wall_pt () const inline
Access to pointer to the geometric object that parametrises the collapsible wall (const version)
     {
       return Wall_pt;
     }
References Wall_pt.
Member Data Documentation
Axial_spacing_fct_pt
AxialSpacingFctPt oomph::CollapsibleChannelDomain::Axial_spacing_fct_pt private
Function pointer for function that implements axial spacing of macro elements
Referenced by axial_spacing_fct(), and axial_spacing_fct_pt().
BL_squash_fct_pt
BLSquashFctPt oomph::CollapsibleChannelDomain::BL_squash_fct_pt private
Function pointer for function that squashes the macro elements near the walls
Referenced by bl_squash_fct_pt(), and s_squash().
Lcollapsible
double oomph::CollapsibleChannelDomain::Lcollapsible private
x-length in the "collapsible" part of the channel
Referenced by CollapsibleChannelDomain(), l_collapsible(), r_E_collapsible(), r_E_straight(), r_N_collapsible(), r_N_straight(), r_S_collapsible(), r_S_straight(), r_W_collapsible(), and r_W_straight().
Ldown
double oomph::CollapsibleChannelDomain::Ldown private
x-length in the downstream part of the channel
Referenced by CollapsibleChannelDomain(), l_down(), r_E_straight(), r_N_straight(), r_S_straight(), and r_W_straight().
Lup
double oomph::CollapsibleChannelDomain::Lup private
x-length in the upstream part of the channel
Referenced by CollapsibleChannelDomain(), l_up(), r_E_collapsible(), r_E_straight(), r_N_collapsible(), r_N_straight(), r_S_collapsible(), r_S_straight(), r_W_collapsible(), and r_W_straight().
Ly
double oomph::CollapsibleChannelDomain::Ly private
Width.
Referenced by CollapsibleChannelDomain(), l_y(), r_E_straight(), r_N_straight(), r_S_straight(), and r_W_straight().
Ncollapsible
unsigned oomph::CollapsibleChannelDomain::Ncollapsible private
Number of vertical element columns in "collapsible" section.
Referenced by CollapsibleChannelDomain(), macro_element_boundary(), ncollapsible(), r_E_collapsible(), r_E_straight(), r_N_collapsible(), r_N_straight(), r_S_collapsible(), r_S_straight(), r_W_collapsible(), and r_W_straight().
Ndown
unsigned oomph::CollapsibleChannelDomain::Ndown private
Number of vertical element columns in downstream section.
Referenced by CollapsibleChannelDomain(), macro_element_boundary(), ndown(), r_E_collapsible(), r_E_straight(), r_N_collapsible(), r_N_straight(), r_S_collapsible(), r_S_straight(), r_W_collapsible(), and r_W_straight().
Nup
unsigned oomph::CollapsibleChannelDomain::Nup private
Number of vertical element columns in upstream section.
Referenced by CollapsibleChannelDomain(), macro_element_boundary(), nup(), r_E_collapsible(), r_E_straight(), r_N_collapsible(), r_N_straight(), r_S_collapsible(), r_S_straight(), r_W_collapsible(), and r_W_straight().
Ny
unsigned oomph::CollapsibleChannelDomain::Ny private
Number of macro elements across channel.
Referenced by CollapsibleChannelDomain(), ny(), r_E_collapsible(), r_E_straight(), r_N_collapsible(), r_N_straight(), r_S_collapsible(), r_S_straight(), r_W_collapsible(), and r_W_straight().
Rotate_domain
bool oomph::CollapsibleChannelDomain::Rotate_domain private
Rotate domain (for axisymmetric problems, say)
Referenced by disable_rotate_domain(), enable_rotate_domain(), and macro_element_boundary().
Wall_pt
GeomObject* oomph::CollapsibleChannelDomain::Wall_pt private
Pointer to the geometric object that parametrises the collapsible wall.
Referenced by CollapsibleChannelDomain(), r_E_collapsible(), r_N_collapsible(), r_S_collapsible(), r_W_collapsible(), and wall_pt().
The documentation for this class was generated from the following file:
collapsible_channel_domain.h