MercuryDPM: Tutorial_sparse_example.cpp File Reference
Tutorial_sparse_example.cpp File Reference
#include <Eigen/Sparse>
#include <vector>
#include <iostream>
Typedefs
typedef Eigen::SparseMatrix< double > SpMat
typedef Eigen::Triplet< double > T
Functions
void buildProblem (std::vector< T > &coefficients, Eigen::VectorXd &b, int n)
void saveAsBitmap (const Eigen::VectorXd &x, int n, const char *filename)
int main (int argc, char **argv)
Typedef Documentation
SpMat
typedef Eigen::SparseMatrix<double> SpMat
T
typedef Eigen::Triplet<double> T
Function Documentation
buildProblem()
void buildProblem (std::vector< T > & coefficients, Eigen::VectorXd & b, int n)
{
   b.setZero();
   Eigen::ArrayXd boundary = Eigen::ArrayXd::LinSpaced(n, 0, M_PI).sin().pow(2);
   for (int j = 0; j < n; ++j) {
     for (int i = 0; i < n; ++i) {
       int id = i + j * n;
       insertCoefficient(id, i - 1, j, -1, coefficients, b, boundary);
       insertCoefficient(id, i + 1, j, -1, coefficients, b, boundary);
       insertCoefficient(id, i, j - 1, -1, coefficients, b, boundary);
       insertCoefficient(id, i, j + 1, -1, coefficients, b, boundary);
       insertCoefficient(id, i, j, 4, coefficients, b, boundary);
     }
   }
 }
References b, i, insertCoefficient(), j, M_PI, and n.
Referenced by main().
main()
int main (int argc , char ** argv)
{
   if (argc != 2) {
     std::cerr << "Error: expected one and only one argument.\n";
     return -1;
   }
   int n = 300;    // size of the image
   int m = n * n;  // number of unknowns (=number of pixels)
   // Assembly:
   std::vector<T> coefficients;  // list of non-zeros coefficients
   Eigen::VectorXd b(m);         // the right hand side-vector resulting from the constraints
   buildProblem(coefficients, b, n);
   SpMat A(m, m);
   A.setFromTriplets(coefficients.begin(), coefficients.end());
   // Solving:
   Eigen::SimplicialCholesky<SpMat> chol(A);  // performs a Cholesky factorization of A
   Eigen::VectorXd x = chol.solve(b);         // use the factorization to solve for the given right hand side
   // Export the result to a file:
   saveAsBitmap(x, n, argv[1]);
   return 0;
 }
References b, buildProblem(), m, n, saveAsBitmap(), Eigen::SparseSolverBase< Derived >::solve(), and plotDoE::x.
saveAsBitmap()
void saveAsBitmap (const Eigen::VectorXd & x, int n, const char * filename)
{
   Eigen::Array<unsigned char, Eigen::Dynamic, Eigen::Dynamic> bits = (x * 255).cast<unsigned char>();
   QImage img(bits.data(), n, n, QImage::Format_Indexed8);
   img.setColorCount(256);
   for (int i = 0; i < 256; i++) img.setColor(i, qRgb(i, i, i));
   img.save(filename);
 }
References Eigen::test::bits(), MergeRestartFiles::filename, i, n, and plotDoE::x.
Referenced by main().