MercuryDPM: LiquidMigrationSelfTest.cpp File Reference
LiquidMigrationSelfTest.cpp File Reference
#include "Mercury2D.h"
#include "Particles/LiquidFilmParticle.h"
#include "Walls/InfiniteWall.h"
#include <iostream>
#include "Species/Species.h"
#include "Species/LinearViscoelasticFrictionLiquidMigrationWilletSpecies.h"
#include <iomanip>
Classes
class LiquidMigrationSelfTest
In this file two particles are symmetrically placed in a bi-axial box are allowed to jump around under gravity. It tests walls gravity and symmetry.
Functions
int main (int argc UNUSED, char *argv[] UNUSED)
Function Documentation
main()
int main (int argc UNUSED, char *argv[] UNUSED)
 {
     LiquidMigrationSelfTest LiquidMigrationProblem;
     LiquidMigrationProblem.setName("LiquidMigrationSelfTest");
     LiquidMigrationProblem.setSystemDimensions(3);
     LiquidMigrationProblem.setXBallsAdditionalArguments("-v0 -solid -3dturn 1");
     auto species = new LinearViscoelasticFrictionLiquidMigrationWilletSpecies;
     LiquidMigrationProblem.speciesHandler.addObject(species);
     species->setDensity(2000);
     species->setStiffness(10000);
     species->setLiquidBridgeVolumeMax(5e-12);
     species->setDistributionCoefficient(0.8);
     species->setSurfaceTension(1.0);
     species->setContactAngle(20.0 * constants::pi / 180.0);
     LiquidMigrationProblem.setTimeMax(0.7);//2.5);
     LiquidMigrationProblem.setSaveCount(100);
     LiquidMigrationProblem.setTimeStep(2e-5);
     LiquidMigrationProblem.fStatFile.setFileType(FileType::NO_FILE);
     LiquidMigrationProblem.solve();
 }
References SpeciesHandler::addObject(), e(), DPMBase::fStatFile, NO_FILE, constants::pi, File::setFileType(), DPMBase::setName(), DPMBase::setSaveCount(), DPMBase::setSystemDimensions(), DPMBase::setTimeMax(), DPMBase::setTimeStep(), DPMBase::setXBallsAdditionalArguments(), DPMBase::solve(), and DPMBase::speciesHandler.