MercuryDPM: ElasticRingProblem< ELEMENT > Class Template Reference
ElasticRingProblem< ELEMENT > Class Template Reference
Ring problem.
Public Member Functions
ElasticRingProblem (const unsigned &n_element, bool &displ_control, bool &load_data_already_exists)
Constructor for elastic ring problem.
OneDLagrangianMesh< ELEMENT > * mesh_pt ()
Access function for the specific mesh.
void actions_after_newton_solve ()
Update function is empty.
void actions_before_newton_solve ()
Update function is empty.
void doc_solution (DocInfo &doc_info, ofstream &trace_file)
Doc solution.
void parameter_study (DocInfo &doc_info)
Perform the parameter study.
ElasticRingProblem (const unsigned &n_element)
Constructor: Pass umber of elements.
OneDLagrangianMesh< ELEMENT > * mesh_pt ()
Access function for the specific mesh.
void actions_after_newton_solve ()
Update function is empty.
void actions_before_newton_solve ()
Update function is empty.
void doc_solution (DocInfo &doc_info, ofstream &trace_file)
Doc solution.
void parameter_study (DocInfo &doc_info)
Perform the parameter study.
ElasticRingProblem (const unsigned &N, const double &L)
Constructor for elastic ring problem.
OneDLagrangianMesh< ELEMENT > * mesh_pt ()
Access function for the mesh.
void actions_after_newton_solve ()
Update function is empty.
void actions_before_newton_solve ()
Update function is empty.
void doc_solution (DocInfo &doc_info)
Doc solution.
void unsteady_run ()
Do unsteady run.
ElasticRingProblem (const unsigned &n_element)
Constructor: Number of elements.
OneDLagrangianMesh< ELEMENT > * mesh_pt ()
Access function for the specific mesh.
void actions_after_newton_solve ()
Update function is empty.
void actions_before_newton_solve ()
Update function is empty.
void set_initial_conditions ()
Setup initial conditions.
void doc_solution (DocInfo &doc_info)
Doc solution.
void unsteady_run ()
Do unsteady run.
void dump_it (ofstream &dump_file)
void restart (ifstream &restart_file)
Public Member Functions inherited from oomph::Problem
virtual void debug_hook_fct (const unsigned &i)
void set_analytic_dparameter (double *const &parameter_pt)
void unset_analytic_dparameter (double *const &parameter_pt)
bool is_dparameter_calculated_analytically (double *const &parameter_pt)
void set_analytic_hessian_products ()
void unset_analytic_hessian_products ()
bool are_hessian_products_calculated_analytically ()
void set_pinned_values_to_zero ()
bool distributed () const
virtual void actions_before_adapt ()
virtual void actions_after_adapt ()
Actions that are to be performed after a mesh adaptation.
OomphCommunicator * communicator_pt ()
access function to the oomph-lib communicator
const OomphCommunicator * communicator_pt () const
access function to the oomph-lib communicator, const version
Problem ()
Problem (const Problem &dummy)=delete
Broken copy constructor.
void operator= (const Problem &)=delete
Broken assignment operator.
virtual ~Problem ()
Virtual destructor to clean up memory.
Mesh *& mesh_pt ()
Return a pointer to the global mesh.
Mesh *const & mesh_pt () const
Return a pointer to the global mesh (const version)
Mesh *& mesh_pt (const unsigned &imesh)
Mesh *const & mesh_pt (const unsigned &imesh) const
Return a pointer to the i-th submesh (const version)
unsigned nsub_mesh () const
Return number of submeshes.
unsigned add_sub_mesh (Mesh *const &mesh_pt)
void flush_sub_meshes ()
void build_global_mesh ()
void rebuild_global_mesh ()
LinearSolver *& linear_solver_pt ()
Return a pointer to the linear solver object.
LinearSolver *const & linear_solver_pt () const
Return a pointer to the linear solver object (const version)
LinearSolver *& mass_matrix_solver_for_explicit_timestepper_pt ()
LinearSolver * mass_matrix_solver_for_explicit_timestepper_pt () const
EigenSolver *& eigen_solver_pt ()
Return a pointer to the eigen solver object.
EigenSolver *const & eigen_solver_pt () const
Return a pointer to the eigen solver object (const version)
Time *& time_pt ()
Return a pointer to the global time object.
Time * time_pt () const
Return a pointer to the global time object (const version).
double & time ()
Return the current value of continuous time.
double time () const
Return the current value of continuous time (const version)
TimeStepper *& time_stepper_pt ()
const TimeStepper * time_stepper_pt () const
TimeStepper *& time_stepper_pt (const unsigned &i)
Return a pointer to the i-th timestepper.
ExplicitTimeStepper *& explicit_time_stepper_pt ()
Return a pointer to the explicit timestepper.
unsigned long set_timestepper_for_all_data (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data=false)
virtual void shift_time_values ()
Shift all values along to prepare for next timestep.
AssemblyHandler *& assembly_handler_pt ()
Return a pointer to the assembly handler object.
AssemblyHandler *const & assembly_handler_pt () const
Return a pointer to the assembly handler object (const version)
double & minimum_dt ()
Access function to min timestep in adaptive timestepping.
double & maximum_dt ()
Access function to max timestep in adaptive timestepping.
unsigned & max_newton_iterations ()
Access function to max Newton iterations before giving up.
void problem_is_nonlinear (const bool &prob_lin)
Access function to Problem_is_nonlinear.
double & max_residuals ()
bool & time_adaptive_newton_crash_on_solve_fail ()
Access function for Time_adaptive_newton_crash_on_solve_fail.
double & newton_solver_tolerance ()
void add_time_stepper_pt (TimeStepper *const &time_stepper_pt)
void set_explicit_time_stepper_pt (ExplicitTimeStepper *const &explicit_time_stepper_pt)
void initialise_dt (const double &dt)
void initialise_dt (const Vector< double > &dt)
Data *& global_data_pt (const unsigned &i)
Return a pointer to the the i-th global data object.
void add_global_data (Data *const &global_data_pt)
void flush_global_data ()
LinearAlgebraDistribution *const & dof_distribution_pt () const
Return the pointer to the dof distribution (read-only)
unsigned long ndof () const
Return the number of dofs.
unsigned ntime_stepper () const
Return the number of time steppers.
unsigned nglobal_data () const
Return the number of global data values.
unsigned self_test ()
Self-test: Check meshes and global data. Return 0 for OK.
void enable_store_local_dof_pt_in_elements ()
void disable_store_local_dof_pt_in_elements ()
unsigned long assign_eqn_numbers (const bool &assign_local_eqn_numbers=true)
void describe_dofs (std::ostream &out= *(oomph_info.stream_pt())) const
void enable_discontinuous_formulation ()
void disable_discontinuous_formulation ()
void get_dofs (DoubleVector &dofs) const
void get_dofs (const unsigned &t, DoubleVector &dofs) const
Return vector of the t'th history value of all dofs.
void set_dofs (const DoubleVector &dofs)
Set the values of the dofs.
void set_dofs (const unsigned &t, DoubleVector &dofs)
Set the history values of the dofs.
void set_dofs (const unsigned &t, Vector< double * > &dof_pt)
void add_to_dofs (const double &lambda, const DoubleVector &increment_dofs)
Add lambda x incremenet_dofs[l] to the l-th dof.
double * global_dof_pt (const unsigned &i)
double & dof (const unsigned &i)
i-th dof in the problem
double dof (const unsigned &i) const
i-th dof in the problem (const version)
double *& dof_pt (const unsigned &i)
Pointer to i-th dof in the problem.
double * dof_pt (const unsigned &i) const
Pointer to i-th dof in the problem (const version)
virtual void get_inverse_mass_matrix_times_residuals (DoubleVector &Mres)
virtual void get_dvaluesdt (DoubleVector &f)
virtual void get_residuals (DoubleVector &residuals)
Get the total residuals Vector for the problem.
virtual void get_jacobian (DoubleVector &residuals, DenseDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CRDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CCDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, SumOfMatrices &jacobian)
void get_fd_jacobian (DoubleVector &residuals, DenseMatrix< double > &jacobian)
Get the full Jacobian by finite differencing.
void get_derivative_wrt_global_parameter (double *const &parameter_pt, DoubleVector &result)
void get_hessian_vector_products (DoubleVectorWithHaloEntries const &Y, Vector< DoubleVectorWithHaloEntries > const &C, Vector< DoubleVectorWithHaloEntries > &product)
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, Vector< DoubleVector > &eigenvector, const bool &steady=true)
Solve the eigenproblem.
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, const bool &steady=true)
virtual void get_eigenproblem_matrices (CRDoubleMatrix &mass_matrix, CRDoubleMatrix &main_matrix, const double &shift=0.0)
void assign_eigenvector_to_dofs (DoubleVector &eigenvector)
Assign the eigenvector passed to the function to the dofs.
void add_eigenvector_to_dofs (const double &epsilon, const DoubleVector &eigenvector)
void store_current_dof_values ()
Store the current values of the degrees of freedom.
void restore_dof_values ()
Restore the stored values of the degrees of freedom.
void enable_jacobian_reuse ()
void disable_jacobian_reuse ()
Disable recycling of Jacobian in Newton iteration.
bool jacobian_reuse_is_enabled ()
Is recycling of Jacobian in Newton iteration enabled?
bool & use_predictor_values_as_initial_guess ()
void newton_solve ()
Use Newton method to solve the problem.
void enable_globally_convergent_newton_method ()
enable globally convergent Newton method
void disable_globally_convergent_newton_method ()
disable globally convergent Newton method
void newton_solve (unsigned const &max_adapt)
void steady_newton_solve (unsigned const &max_adapt=0)
void copy (Problem *orig_problem_pt)
virtual Problem * make_copy ()
virtual void read (std::ifstream &restart_file, bool &unsteady_restart)
virtual void read (std::ifstream &restart_file)
virtual void dump (std::ofstream &dump_file) const
void dump (const std::string &dump_file_name) const
void delete_all_external_storage ()
virtual void symmetrise_eigenfunction_for_adaptive_pitchfork_tracking ()
double * bifurcation_parameter_pt () const
void get_bifurcation_eigenfunction (Vector< DoubleVector > &eigenfunction)
void activate_fold_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const DoubleVector &normalisation, const bool &block_solve=true)
void activate_pitchfork_tracking (double *const &parameter_pt, const DoubleVector &symmetry_vector, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const double &omega, const DoubleVector &null_real, const DoubleVector &null_imag, const bool &block_solve=true)
void deactivate_bifurcation_tracking ()
void reset_assembly_handler_to_default ()
Reset the system to the standard non-augemented state.
double arc_length_step_solve (double *const &parameter_pt, const double &ds, const unsigned &max_adapt=0)
double arc_length_step_solve (Data *const &data_pt, const unsigned &data_index, const double &ds, const unsigned &max_adapt=0)
void reset_arc_length_parameters ()
int & sign_of_jacobian ()
void explicit_timestep (const double &dt, const bool &shift_values=true)
Take an explicit timestep of size dt.
void unsteady_newton_solve (const double &dt)
void unsteady_newton_solve (const double &dt, const bool &shift_values)
void unsteady_newton_solve (const double &dt, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const unsigned &suppress_resolve_after_spatial_adapt_flag, const bool &first, const bool &shift=true)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon, const bool &shift_values)
void assign_initial_values_impulsive ()
void assign_initial_values_impulsive (const double &dt)
void calculate_predictions ()
Calculate predictions.
void enable_mass_matrix_reuse ()
void disable_mass_matrix_reuse ()
bool mass_matrix_reuse_is_enabled ()
Return whether the mass matrix is being reused.
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly (DocInfo &doc_info)
void refine_uniformly_and_prune (DocInfo &doc_info)
void refine_uniformly ()
void refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform refinement for submesh i_mesh with documentation.
void refine_uniformly (const unsigned &i_mesh)
Do uniform refinement for submesh i_mesh without documentation.
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly (DocInfo &doc_info)
void p_refine_uniformly_and_prune (DocInfo &doc_info)
void p_refine_uniformly ()
void p_refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-refinement for submesh i_mesh with documentation.
void p_refine_uniformly (const unsigned &i_mesh)
Do uniform p-refinement for submesh i_mesh without documentation.
void refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const unsigned &i_mesh, const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void refine_selected_elements (const Vector< Vector< RefineableElement * >> &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void p_refine_selected_elements (const Vector< Vector< PRefineableElement * >> &elements_to_be_refined_pt)
unsigned unrefine_uniformly ()
unsigned unrefine_uniformly (const unsigned &i_mesh)
void p_unrefine_uniformly (DocInfo &doc_info)
void p_unrefine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-unrefinement for submesh i_mesh without documentation.
void adapt (unsigned &n_refined, unsigned &n_unrefined)
void adapt ()
void p_adapt (unsigned &n_refined, unsigned &n_unrefined)
void p_adapt ()
void adapt_based_on_error_estimates (unsigned &n_refined, unsigned &n_unrefined, Vector< Vector< double >> &elemental_error)
void adapt_based_on_error_estimates (Vector< Vector< double >> &elemental_error)
void get_all_error_estimates (Vector< Vector< double >> &elemental_error)
void doc_errors (DocInfo &doc_info)
Get max and min error for all elements in submeshes.
void doc_errors ()
Get max and min error for all elements in submeshes.
void enable_info_in_newton_solve ()
void disable_info_in_newton_solve ()
Disable the output of information when in the newton solver.
Public Member Functions inherited from oomph::ExplicitTimeSteppableObject
ExplicitTimeSteppableObject ()
Empty constructor.
ExplicitTimeSteppableObject (const ExplicitTimeSteppableObject &)=delete
Broken copy constructor.
void operator= (const ExplicitTimeSteppableObject &)=delete
Broken assignment operator.
virtual ~ExplicitTimeSteppableObject ()
Empty destructor.
virtual void actions_before_explicit_stage ()
virtual void actions_after_explicit_stage ()
Private Attributes
bool Displ_control
Use displacement control?
GeomObject * Undef_geom_pt
Pointer to geometric object that represents the undeformed shape.
unsigned Nbeam_element
Number of elements in the beam mesh.
double Length
Length of domain (in terms of the Lagrangian coordinates)
ELEMENT * Displ_control_elem_pt
Vector< double > S_displ_control
At what local coordinate are we applying displacement control?
SolidInitialCondition * IC_pt
Pointer to object that specifies the initial condition.
ofstream Trace_file
Trace file for recording control data.
unsigned Validation_run_flag
Flag for validation run: Default: 0 = no validation run.
bool Restart_flag
Restart flag specified via command line?
Additional Inherited Members
Public Types inherited from oomph::Problem
typedef void(* SpatialErrorEstimatorFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error)
Function pointer for spatial error estimator.
typedef void(* SpatialErrorEstimatorWithDocFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error, DocInfo &doc_info)
Function pointer for spatial error estimator with doc.
Public Attributes inherited from oomph::Problem
bool Shut_up_in_newton_solve
Static Public Attributes inherited from oomph::Problem
static bool Suppress_warning_about_actions_before_read_unstructured_meshes
Protected Types inherited from oomph::Problem
enum Assembly_method {
Perform_assembly_using_vectors_of_pairs , Perform_assembly_using_two_vectors , Perform_assembly_using_maps , Perform_assembly_using_lists ,
Perform_assembly_using_two_arrays
}
Enumerated flags to determine which sparse assembly method is used.
Protected Member Functions inherited from oomph::Problem
unsigned setup_element_count_per_dof ()
virtual void sparse_assemble_row_or_column_compressed (Vector< int * > &column_or_row_index, Vector< int * > &row_or_column_start, Vector< double * > &value, Vector< unsigned > &nnz, Vector< double * > &residual, bool compressed_row_flag)
virtual void actions_before_newton_convergence_check ()
virtual void actions_before_newton_step ()
virtual void actions_after_newton_step ()
virtual void actions_before_implicit_timestep ()
virtual void actions_after_implicit_timestep ()
virtual void actions_after_implicit_timestep_and_error_estimation ()
virtual void actions_before_explicit_timestep ()
Actions that should be performed before each explicit time step.
virtual void actions_after_explicit_timestep ()
Actions that should be performed after each explicit time step.
virtual void actions_before_read_unstructured_meshes ()
virtual void actions_after_read_unstructured_meshes ()
virtual void actions_after_change_in_global_parameter (double *const &parameter_pt)
virtual void actions_after_change_in_bifurcation_parameter ()
virtual void actions_after_parameter_increase (double *const &parameter_pt)
double & dof_derivative (const unsigned &i)
double & dof_current (const unsigned &i)
virtual void set_initial_condition ()
virtual double global_temporal_error_norm ()
unsigned newton_solve_continuation (double *const &parameter_pt)
unsigned newton_solve_continuation (double *const &parameter_pt, DoubleVector &z)
void calculate_continuation_derivatives (double *const &parameter_pt)
void calculate_continuation_derivatives (const DoubleVector &z)
void calculate_continuation_derivatives_fd (double *const &parameter_pt)
bool does_pointer_correspond_to_problem_data (double *const &parameter_pt)
void set_consistent_pinned_values_for_continuation ()
Protected Attributes inherited from oomph::Problem
Vector< Problem * > Copy_of_problem_pt
std::map< double *, bool > Calculate_dparameter_analytic
bool Calculate_hessian_products_analytic
LinearAlgebraDistribution * Dof_distribution_pt
Vector< double * > Dof_pt
Vector of pointers to dofs.
DoubleVectorWithHaloEntries Element_count_per_dof
double Relaxation_factor
double Newton_solver_tolerance
unsigned Max_newton_iterations
Maximum number of Newton iterations.
unsigned Nnewton_iter_taken
Vector< double > Max_res
Maximum residuals at start and after each newton iteration.
double Max_residuals
bool Time_adaptive_newton_crash_on_solve_fail
bool Jacobian_reuse_is_enabled
Is re-use of Jacobian in Newton iteration enabled? Default: false.
bool Jacobian_has_been_computed
bool Problem_is_nonlinear
bool Pause_at_end_of_sparse_assembly
bool Doc_time_in_distribute
unsigned Sparse_assembly_method
unsigned Sparse_assemble_with_arrays_initial_allocation
unsigned Sparse_assemble_with_arrays_allocation_increment
Vector< Vector< unsigned > > Sparse_assemble_with_arrays_previous_allocation
double Numerical_zero_for_sparse_assembly
double FD_step_used_in_get_hessian_vector_products
bool Mass_matrix_reuse_is_enabled
bool Mass_matrix_has_been_computed
bool Discontinuous_element_formulation
double Minimum_dt
Minimum desired dt: if dt falls below this value, exit.
double Maximum_dt
Maximum desired dt.
double DTSF_max_increase
double DTSF_min_decrease
double Minimum_dt_but_still_proceed
bool Scale_arc_length
Boolean to control whether arc-length should be scaled.
double Desired_proportion_of_arc_length
Proportion of the arc-length to taken by the parameter.
double Theta_squared
int Sign_of_jacobian
Storage for the sign of the global Jacobian.
double Continuation_direction
double Parameter_derivative
Storage for the derivative of the global parameter wrt arc-length.
double Parameter_current
Storage for the present value of the global parameter.
bool Use_continuation_timestepper
Boolean to control original or new storage of dof stuff.
unsigned Dof_derivative_offset
unsigned Dof_current_offset
Vector< double > Dof_derivative
Storage for the derivative of the problem variables wrt arc-length.
Vector< double > Dof_current
Storage for the present values of the variables.
double Ds_current
Storage for the current step value.
unsigned Desired_newton_iterations_ds
double Minimum_ds
Minimum desired value of arc-length.
bool Bifurcation_detection
Boolean to control bifurcation detection via determinant of Jacobian.
bool Bisect_to_find_bifurcation
Boolean to control wheter bisection is used to located bifurcation.
bool First_jacobian_sign_change
Boolean to indicate whether a sign change has occured in the Jacobian.
bool Arc_length_step_taken
Boolean to indicate whether an arc-length step has been taken.
bool Use_finite_differences_for_continuation_derivatives
OomphCommunicator * Communicator_pt
The communicator for this problem.
bool Always_take_one_newton_step
double Timestep_reduction_factor_after_nonconvergence
bool Keep_temporal_error_below_tolerance
Static Protected Attributes inherited from oomph::Problem
static ContinuationStorageScheme Continuation_time_stepper
Storage for the single static continuation timestorage object.
Detailed Description
template<class ELEMENT>
class ElasticRingProblem< ELEMENT >
Ring problem.
////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////// Oscillating ring problem: Compare small-amplitude oscillations against analytical solution of the linearised equations.
Constructor & Destructor Documentation
ElasticRingProblem() [1/4]
template<class ELEMENT > ElasticRingProblem< ELEMENT >::ElasticRingProblem (const unsigned & n_element, bool & displ_control, bool & load_data_already_exists)
Constructor for elastic ring problem.
Constructor: Number of elements and flags for displ control and displacement control with existing data respectively.
                                                                                  :
  Displ_control(displ_control),Nbeam_element(n_element)
 {
  // Undeformed beam is an elliptical ring
  Undef_geom_pt=new Ellipse(1.0,1.0);
  // Length of the doamin (in terms of the Lagrangian coordinates)
  double length=2.0*atan(1.0);
  //Now create the (Lagrangian!) mesh
  Problem::mesh_pt() =
   new OneDLagrangianMesh<ELEMENT>(n_element,length,Undef_geom_pt);
  // Boundary condition:
  // Bottom:
  unsigned ibound=0;
  // No vertical displacement
  mesh_pt()->boundary_node_pt(ibound,0)->pin_position(1);
  // Infinite slope: Pin type 1 (slope) dof for displacement direction 0
  mesh_pt()->boundary_node_pt(ibound,0)->pin_position(1,0);
  // Top:
  ibound=1;
   // No horizontal displacement
  mesh_pt()->boundary_node_pt(ibound,0)->pin_position(0);
  // Zero slope: Pin type 1 (slope) dof for displacement direction 1
  mesh_pt()->boundary_node_pt(ibound,0)->pin_position(1,1);
  // Normal load incrementation
  //===========================
  if (!Displ_control)
   {
    // Create Data object whose one-and-only value contains the
    // (in principle) adjustable load
    Global_Physical_Variables::Pext_data_pt=new Data(1);
    //Pin the external pressure because it isn't actually adjustable.
    Global_Physical_Variables::Pext_data_pt->pin(0);
   }
  // Displacement control
  //=====================
  else
   {
    // Choose element in which displacement control is applied: the last one
    SolidFiniteElement* controlled_element_pt=
     dynamic_cast<ELEMENT*>(mesh_pt()->element_pt(Nbeam_element-1));
    // Fix the displacement in the vertical (1) direction...
    unsigned controlled_direction=1;
    //... at right end of the control element
    Vector<double> s_displ_control(1);
    s_displ_control[0]=1.0;
    // Pointer to displacement control element
    DisplacementControlElement* displ_control_el_pt;
    // Displacement control without previously existing load Data
    //-----------------------------------------------------------
    if (!load_data_already_exists)
     {
      // Build displacement control element
      displ_control_el_pt=
       new DisplacementControlElement(controlled_element_pt,
                                      s_displ_control,
                                      controlled_direction,
                                      &Global_Physical_Variables::Xprescr);
      // The constructor of the  DisplacementControlElement has created
      // a new Data object whose one-and-only value contains the
      // adjustable load: Use this Data object in the load function:
      Global_Physical_Variables::Pext_data_pt=displ_control_el_pt->
       displacement_control_load_pt();
     }
    // Demonstrate use of displacement control with some existing data
    //----------------------------------------------------------------
    else
     {
      // Create Data object whose one-and-only value contains the
      // adjustable load
      Global_Physical_Variables::Pext_data_pt=new Data(1);
      // Currently, nobody's "in charge of" this Data so it won't
      // get included in any equation numbering schemes etc.
      // --> declare it to be "global Data" for the Problem
      // so the Problem is in charge and will perform such tasks.
      add_global_data(Global_Physical_Variables::Pext_data_pt);
      // Build displacement control element and pass pointer to the
      // already existing adjustable load Data.
      displ_control_el_pt=
       new  DisplacementControlElement(controlled_element_pt,
                                       s_displ_control,
                                       controlled_direction,
                                       &Global_Physical_Variables::Xprescr,
                                       Global_Physical_Variables::Pext_data_pt);
     }
    // Add the displacement-control element to the mesh
    mesh_pt()->add_element_pt(displ_control_el_pt);
   }
  //Loop over the elements to set physical parameters etc.
  for(unsigned i=0;i<Nbeam_element;i++)
   {
    //Cast to proper element type
    ELEMENT *elem_pt = dynamic_cast<ELEMENT*>(mesh_pt()->element_pt(i));
    // Set wall thickness
    elem_pt->h_pt() = &Global_Physical_Variables::H;
    // Function that specifies load Vector
    elem_pt->load_vector_fct_pt() = &Global_Physical_Variables::press_load;
    //Assign the undeformed beam shape
    elem_pt->undeformed_beam_pt() = Undef_geom_pt;
    // Displacement control? If so, the load on *all* elements
    // is affected by an unknown -- the external pressure, stored
    // as the one-and-only value in a Data object: Add it to the
    // elements' external Data.
    if (Displ_control)
     {
      //The external pressure is external data for all elements
      elem_pt->add_external_data(Global_Physical_Variables::Pext_data_pt);
     }
   }
  // Do equation numbering
  cout << "# of dofs " << assign_eqn_numbers() << std::endl;
 } // end of constructor
References oomph::Problem::add_global_data(), oomph::Problem::assign_eqn_numbers(), Eigen::bfloat16_impl::atan(), ElasticRingProblem< ELEMENT >::Displ_control, Global_Physical_Variables::H, i, ElasticRingProblem< ELEMENT >::mesh_pt(), ElasticRingProblem< ELEMENT >::Nbeam_element, Global_Physical_Variables::Pext_data_pt, oomph::Data::pin(), Global_Physical_Variables::press_load(), ElasticRingProblem< ELEMENT >::Undef_geom_pt, and Global_Physical_Variables::Xprescr.
ElasticRingProblem() [2/4]
template<class ELEMENT , class TIMESTEPPER > ElasticRingProblem< ELEMENT, TIMESTEPPER >::ElasticRingProblem (const unsigned & n_element)
Constructor: Pass umber of elements.
Constructor for elastic ring problem.
 {
  // Undeformed beam is an elliptical ring
  Undef_geom_pt=new Ellipse(1.0,1.0);
  // Angle
  double phi=MathematicalConstants::Pi/
   double(Global_Physical_Variables::Nbuckl);
  // Length of the doamin (in terms of the Lagrangian coordinates)
  double length=phi;
  // Actual number of elements
  Nbeam_element=n_element;
  //Now create the (Lagrangian!) mesh
  Problem::mesh_pt() =
   new OneDLagrangianMesh<ELEMENT>(Nbeam_element,length,Undef_geom_pt);
  // "Bulk" beam element that the boundary condition element is attached to
  int face_index=1;
  ELEMENT* bulk_el_pt=dynamic_cast<ELEMENT*>(
   mesh_pt()->element_pt(n_element-1));
  // Create boundary condition element
  ClampedSlidingHermiteBeamBoundaryConditionElement*
   bc_el_pt = new
   ClampedSlidingHermiteBeamBoundaryConditionElement(
    bulk_el_pt,face_index);
  // Set vectors that define the symmetry line
  Vector<double> vector_to_symmetry_line(2);
  vector_to_symmetry_line[0]=0.0;
  vector_to_symmetry_line[1]=0.0;
  Vector<double> normal_to_symmetry_line(2);
  normal_to_symmetry_line[0]=-sin(phi);
  normal_to_symmetry_line[1]= cos(phi);
  bc_el_pt->set_symmetry_line(vector_to_symmetry_line,
                              normal_to_symmetry_line);
  // Add boundary condition element to mesh
  mesh_pt()->add_element_pt(bc_el_pt);
  // Boundary condition: Only at bottom
  //-----------------------------------
  // Bottom:
  unsigned ibound=0;
  // No vertical displacement
  mesh_pt()->boundary_node_pt(ibound,0)->pin_position(1);
  // Infinite slope: Pin type 1 (slope) dof for displacement direction 0
  mesh_pt()->boundary_node_pt(ibound,0)->pin_position(1,0);
  // Displacement control
  //---------------------
  // Choose element in which displacement control is applied: the first one
  SolidFiniteElement* controlled_element_pt=
   dynamic_cast<ELEMENT*>(mesh_pt()->element_pt(0));
  // Fix the displacement in the horizontal direction...
  unsigned controlled_direction=0;
  //... at left end of the control element
  Vector<double> s_displ_control(1);
  s_displ_control[0]=0.0;
  // Pointer to displacement control element
  DisplacementControlElement* displ_control_el_pt;
  // Build displacement control element
  displ_control_el_pt=
   new DisplacementControlElement(controlled_element_pt,
                                  s_displ_control,
                                  controlled_direction,
                                  &Global_Physical_Variables::Xprescr);
  // The constructor of the  DisplacementControlElement has created
  // a new Data object whose one-and-only value contains the
  // adjustable load: Use this Data object in the load function:
  Global_Physical_Variables::Pext_data_pt=displ_control_el_pt->
   displacement_control_load_pt();
  // Add the displacement-control element to the mesh
  mesh_pt()->add_element_pt(displ_control_el_pt);
  //Loop over the elements to set physical parameters etc.
  for(unsigned i=0;i<Nbeam_element;i++)
   {
    //Cast to proper element type
    ELEMENT *elem_pt = dynamic_cast<ELEMENT*>(mesh_pt()->element_pt(i));
    // Set wall thickness
    elem_pt->h_pt() = &Global_Physical_Variables::H;
    // Function that specifies load Vector
    elem_pt->load_vector_fct_pt() = &Global_Physical_Variables::press_load;
    //Assign the undeformed beam shape
    elem_pt->undeformed_beam_pt() = Undef_geom_pt;
    // Displacement control: The load on *all* elements
    // is affected by an unknown -- the external pressure, stored
    // as the one-and-only value in a Data object: Add it to the
    // elements' external Data.
    elem_pt->add_external_data(Global_Physical_Variables::Pext_data_pt);
   }
  // Do equation numbering
  cout << "# of dofs " << assign_eqn_numbers() << std::endl;
 } // end of constructor
References cos(), Global_Physical_Variables::H, i, Global_Physical_Variables::Nbuckl, Global_Physical_Variables::Pext_data_pt, BiharmonicTestFunctions2::Pi, Global_Physical_Variables::press_load(), oomph::ClampedSlidingHermiteBeamBoundaryConditionElement::set_symmetry_line(), sin(), and Global_Physical_Variables::Xprescr.
ElasticRingProblem() [3/4]
template<class ELEMENT , class TIMESTEPPER > ElasticRingProblem< ELEMENT, TIMESTEPPER >::ElasticRingProblem (const unsigned & N, const double & L)
Constructor for elastic ring problem.
Constructor: Number of elements, length of domain, flag for setting Newmark IC directly or consistently
  : Length(L)
 {
  //Allocate the timestepper -- This constructs the time object as well
  add_time_stepper_pt(new TIMESTEPPER());
  // Undeformed beam is an elliptical ring
  Undef_geom_pt=new Ellipse(1.0,1.0);
  //Now create the (Lagrangian!) mesh
  Problem::mesh_pt() = new OneDLagrangianMesh<ELEMENT>(
   N,L,Undef_geom_pt,Problem::time_stepper_pt());
  // Boundary condition:
  // Bottom:
  unsigned ibound=0;
  // No vertical displacement
  mesh_pt()->boundary_node_pt(ibound,0)->pin_position(1);
  // Zero slope: Pin type 1 dof for displacement direction 0
  mesh_pt()->boundary_node_pt(ibound,0)->pin_position(1,0);
  // Top:
  ibound=1;
  // No horizontal displacement
  mesh_pt()->boundary_node_pt(ibound,0)->pin_position(0);
  // Zero slope: Pin type 1 dof for displacement direction 1
  mesh_pt()->boundary_node_pt(ibound,0)->pin_position(1,1);
  // Resize vector of local coordinates for control displacement
  // (here only used to identify the point whose displacement we're
  // tracing)
  S_displ_control.resize(1);
  // Complete build of all elements so they are fully functional
  // -----------------------------------------------------------
  // Find number of elements in mesh
  unsigned Nelement = mesh_pt()->nelement();
  // Loop over the elements to set pointer to undeformed wall shape
  for(unsigned i=0;i<Nelement;i++)
   {
    // Cast to proper element type
    ELEMENT *elem_pt = dynamic_cast<ELEMENT*>(mesh_pt()->element_pt(i));
    // Assign the undeformed surface
    elem_pt->undeformed_beam_pt() = Undef_geom_pt;
   }
  // Establish control displacment: (even though no displacement
  // control is applied we still want to doc the displacement at the same point)
  // Choose element: (This is the last one)
  Displ_control_elem_pt=dynamic_cast<ELEMENT*>(
   mesh_pt()->element_pt(Nelement-1));
  // Fix/doc the displacement in the vertical (1) direction at right end of
  // the control element
  S_displ_control[0]=1.0;
  // Do equation numbering
  cout << "# of dofs " << assign_eqn_numbers() << std::endl;
  // Geometric object that specifies the initial conditions
  double eps_buckl=1.0e-2;
  double HoR=dynamic_cast<ELEMENT*>(mesh_pt()->element_pt(0))->h();
  unsigned n_buckl=2;
  unsigned imode=2;
  GeomObject* ic_geom_object_pt=
   new PseudoBucklingRing(eps_buckl,HoR,n_buckl,imode,
                          Problem::time_stepper_pt());
  // Setup object that specifies the initial conditions:
  IC_pt = new SolidInitialCondition(ic_geom_object_pt);
 } // end of constructor
References oomph::Problem::add_time_stepper_pt(), oomph::Problem::assign_eqn_numbers(), ElasticRingProblem< ELEMENT >::Displ_control_elem_pt, i, ElasticRingProblem< ELEMENT >::IC_pt, L, ElasticRingProblem< ELEMENT >::mesh_pt(), N, ElasticRingProblem< ELEMENT >::S_displ_control, and ElasticRingProblem< ELEMENT >::Undef_geom_pt.
ElasticRingProblem() [4/4]
template<class ELEMENT > ElasticRingProblem< ELEMENT >::ElasticRingProblem (const unsigned & n_element)
Constructor: Number of elements.
Member Function Documentation
actions_after_newton_solve() [1/4]
template<class ELEMENT > void ElasticRingProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update function is empty.
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [2/4]
template<class ELEMENT > void ElasticRingProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update function is empty.
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [3/4]
template<class ELEMENT > void ElasticRingProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update function is empty.
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [4/4]
template<class ELEMENT > void ElasticRingProblem< ELEMENT >::actions_after_newton_solve () inline virtual
Update function is empty.
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [1/4]
template<class ELEMENT > void ElasticRingProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update function is empty.
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [2/4]
template<class ELEMENT > void ElasticRingProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update function is empty.
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [3/4]
template<class ELEMENT > void ElasticRingProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update function is empty.
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [4/4]
template<class ELEMENT > void ElasticRingProblem< ELEMENT >::actions_before_newton_solve () inline virtual
Update function is empty.
Reimplemented from oomph::Problem.
 {}
doc_solution() [1/4]
template<class ELEMENT , class TIMESTEPPER > void ElasticRingProblem< ELEMENT, TIMESTEPPER >::doc_solution (DocInfo & doc_info)
Doc solution.
Document solution.
 {
  cout << "Doc-ing step " <<  doc_info.number()
       << " for time " << time_stepper_pt()->time_pt()->time() << std::endl;
  // Loop over all elements to get global kinetic and potential energy
  unsigned Nelem=mesh_pt()->nelement();
  double global_kin=0;
  double global_pot=0;
  double pot,kin;
  for (unsigned ielem=0;ielem<Nelem;ielem++)
   {
    dynamic_cast<ELEMENT*>(mesh_pt()->element_pt(ielem))->get_energy(pot,kin);
    global_kin+=kin;
    global_pot+=pot;
   }
  // Control displacement for initial condition object
  Vector<double> xi_ctrl(1);
  Vector<double> posn_ctrl(2);
  // Lagrangian coordinate of control point
  xi_ctrl[0]=Displ_control_elem_pt->interpolated_xi(S_displ_control,0);
  // Get position
  IC_pt->geom_object_pt()->position(xi_ctrl,posn_ctrl);
  // Write trace file: Time, control position, energies
  Trace_file << time_pt()->time()  << " "
             << Displ_control_elem_pt->interpolated_x(S_displ_control,1)
             << " " << global_pot  << " " << global_kin
             << " " << global_pot + global_kin
             << " " << posn_ctrl[1]
             << std::endl;
  ofstream some_file;
  char filename[100];
  // Number of plot points
  unsigned npts=5;
  // Output solution
  sprintf(filename,"%s/ring%i.dat",doc_info.directory().c_str(),
          doc_info.number());
  some_file.open(filename);
  mesh_pt()->output(some_file,npts);
  some_file.close();
  // Loop over all elements do dump out previous solutions
  unsigned nsteps=time_stepper_pt()->nprev_values();
  for (unsigned t=0;t<=nsteps;t++)
   {
    sprintf(filename,"%s/ring%i-%i.dat",doc_info.directory().c_str(),
            doc_info.number(),t);
    some_file.open(filename);
    unsigned Nelem=mesh_pt()->nelement();
    for (unsigned ielem=0;ielem<Nelem;ielem++)
     {
      dynamic_cast<ELEMENT*>(mesh_pt()->element_pt(ielem))->
       output(t,some_file,npts);
     }
    some_file.close();
   }
  // Output for initial condition object
  sprintf(filename,"%s/ic_ring%i.dat",doc_info.directory().c_str(),
          doc_info.number());
  some_file.open(filename);
  unsigned nplot=1+(npts-1)*mesh_pt()->nelement();
  Vector<double> xi(1);
  Vector<double> posn(2);
  Vector<double> veloc(2);
  Vector<double> accel(2);
  for (unsigned iplot=0;iplot<nplot;iplot++)
   {
    xi[0]=Length/double(nplot-1)*double(iplot);
    IC_pt->geom_object_pt()->position(xi,posn);
    IC_pt->geom_object_pt()->dposition_dt(xi,1,veloc);
    IC_pt->geom_object_pt()->dposition_dt(xi,2,accel);
    some_file << posn[0] << " " << posn[1] << " "
              << xi[0] << " "
              << veloc[0] << " " << veloc[1] << " "
              << accel[0] << " " << accel[1] << " "
              << sqrt(pow(posn[0],2)+pow(posn[1],2)) << " "
              << sqrt(pow(veloc[0],2)+pow(veloc[1],2)) << " "
              << sqrt(pow(accel[0],2)+pow(accel[1],2)) << " "
              << std::endl;
   }
  some_file.close();
 } // end of doc solution
References oomph::DocInfo::directory(), MergeRestartFiles::filename, Global_Physical_Variables::Length, oomph::DocInfo::number(), output(), Eigen::ArrayBase< Derived >::pow(), sqrt(), plotPSD::t, and oomph::Problem_Parameter::Trace_file.
doc_solution() [2/4]
template<class ELEMENT > void ElasticRingProblem< ELEMENT >::doc_solution (DocInfo & doc_info)
Doc solution.
doc_solution() [3/4]
template<class ELEMENT > void ElasticRingProblem< ELEMENT >::doc_solution (DocInfo & doc_info, ofstream & trace_file)
Doc solution.
Document solution.
 {
  ofstream some_file;
  char filename[100];
  // Number of plot points
  unsigned npts=5;
  // Output solution
  sprintf(filename,"%s/ring%i.dat",doc_info.directory().c_str(),
          doc_info.number());
  some_file.open(filename);
  mesh_pt()->output(some_file,npts);
  some_file.close();
  // Local coordinates of plot points at left and right end of domain
  Vector<double> s_left(1);
  s_left[0]=-1.0;
  Vector<double> s_right(1);
  s_right[0]=1.0;
  // Write trace file: Pressure, two radii
  trace_file
   << Global_Physical_Variables::Pext_data_pt->value(0)/
   (pow(Global_Physical_Variables::H,3)/12.0)
   << " "
   << dynamic_cast<ELEMENT*>(mesh_pt()->
                             element_pt(0))->interpolated_x(s_left,0)
   << " "
   << dynamic_cast<ELEMENT*>
   (mesh_pt()->element_pt(Nbeam_element-1))->interpolated_x(s_right,1)
   << std::endl;
 } // end of doc
References oomph::DocInfo::directory(), MergeRestartFiles::filename, Global_Physical_Variables::H, oomph::DocInfo::number(), Global_Physical_Variables::Pext_data_pt, Eigen::ArrayBase< Derived >::pow(), and oomph::Data::value().
doc_solution() [4/4]
template<class ELEMENT > void ElasticRingProblem< ELEMENT >::doc_solution (DocInfo & doc_info, ofstream & trace_file)
Doc solution.
dump_it()
template<class ELEMENT , class TIMESTEPPER > void ElasticRingProblem< ELEMENT, TIMESTEPPER >::dump_it (ofstream & dump_file)
Dump problem-specific parameter values, then dump generic problem data.
 {
  // Write Pcos
  dump_file << Global_Physical_Variables::Pcos << " # Pcos" << std::endl;
  // Write validation run flag
  dump_file << Validation_run_flag
            << " # Validation run flag" << std::endl;
  // Call generic dump()
  Problem::dump(dump_file);
 } // end of dump it
References Global_Physical_Variables::Pcos.
mesh_pt() [1/4]
template<class ELEMENT > OneDLagrangianMesh<ELEMENT>* ElasticRingProblem< ELEMENT >::mesh_pt () inline
Access function for the specific mesh.
   {
    return dynamic_cast<OneDLagrangianMesh<ELEMENT>*>(Problem::mesh_pt());
   }
Referenced by ElasticRingProblem< ELEMENT >::ElasticRingProblem().
mesh_pt() [2/4]
template<class ELEMENT > OneDLagrangianMesh<ELEMENT>* ElasticRingProblem< ELEMENT >::mesh_pt () inline
Access function for the specific mesh.
   {
    return dynamic_cast<OneDLagrangianMesh<ELEMENT>*>(Problem::mesh_pt());
   }
mesh_pt() [3/4]
template<class ELEMENT > OneDLagrangianMesh<ELEMENT>* ElasticRingProblem< ELEMENT >::mesh_pt () inline
Access function for the mesh.
   {
    return dynamic_cast<OneDLagrangianMesh<ELEMENT>*>(Problem::mesh_pt());
   }
mesh_pt() [4/4]
template<class ELEMENT > OneDLagrangianMesh<ELEMENT>* ElasticRingProblem< ELEMENT >::mesh_pt () inline
Access function for the specific mesh.
   {
    return dynamic_cast<OneDLagrangianMesh<ELEMENT>*>(Problem::mesh_pt());
   }
parameter_study() [1/2]
template<class ELEMENT > void ElasticRingProblem< ELEMENT >::parameter_study (DocInfo & doc_info)
Perform the parameter study.
Solver loop to perform parameter study.
Perturbation pressure
 {
  //Open a trace file
  char filename[100];
  sprintf(filename,"%s/trace.dat",doc_info.directory().c_str());
  ofstream trace_file(filename);
  trace_file << "VARIABLES=\"p_e_x_t\",\"R_1\",\"R_2\"" << std::endl;
  trace_file << "ZONE" << std::endl;
  //Output initial data
  doc_solution(doc_info,trace_file);
  // Number of steps
  unsigned nstep= 11; //51;
  // Increments
  double displ_increment=1.0/double(nstep-1);
  double p_buckl=3.00*pow(Global_Physical_Variables::H,3)/12.0;
  double p_owc  =5.22*pow(Global_Physical_Variables::H,3)/12.0;
  double pext_increment=(p_owc-p_buckl)/double(nstep-1);
  // Set initial values for parameters that are to be incremented
  Global_Physical_Variables::Xprescr=1.0+displ_increment;
  Global_Physical_Variables::Pext_data_pt->set_value(0,p_buckl-pext_increment);
  // Without displacement control the Newton method converges very slowly
  // as we approach the axisymmetric state: Allow more iterations before
  // calling it a day...
  if (Displ_control)
   {
    Max_newton_iterations=100;
   }
  // Downward loop over parameter incrementation with pcos>0
  //--------------------------------------------------------
  Global_Physical_Variables::Pcos=1.0e-5;
  // Downward loop over parameter incrementation
  //---------------------------------------------
  for(unsigned i=1;i<=nstep;i++)
   {
    // Displacement control?
    if (!Displ_control)
     {
      // Increment pressure
      Global_Physical_Variables::external_pressure() += pext_increment;
     }
    else
     {
      // Increment control displacement
      Global_Physical_Variables::Xprescr-=displ_increment;
     }
    // Solve
    newton_solve();
    // Doc solution
    doc_info.number()++;
    doc_solution(doc_info,trace_file);
   } // end of downward loop
  // Reset perturbation pressure
  //----------------------------
  Global_Physical_Variables::Pcos=0.0;
  // Set initial values for parameters that are to be incremented
  Global_Physical_Variables::Xprescr-=displ_increment;
  Global_Physical_Variables::external_pressure() += pext_increment;
  // Start new zone for tecplot
  trace_file << "ZONE" << std::endl;
  // Upward loop over parameter incrementation
  //------------------------------------------
  for(unsigned i=nstep;i<2*nstep;i++)
   {
    // Displacement control?
    if (!Displ_control)
     {
      // Increment pressure
      Global_Physical_Variables::external_pressure() -= pext_increment;
     }
    else
     {
      // Increment control displacement
      Global_Physical_Variables::Xprescr+=displ_increment;
     }
    // Solve
    newton_solve();
    // Doc solution
    doc_info.number()++;
    doc_solution(doc_info,trace_file);
   }
 } // end of run
References oomph::DocInfo::directory(), Global_Physical_Variables::external_pressure(), MergeRestartFiles::filename, Global_Physical_Variables::H, i, oomph::Locate_zeta_helpers::Max_newton_iterations, oomph::DocInfo::number(), Global_Physical_Variables::Pcos, Global_Physical_Variables::Pext_data_pt, Eigen::ArrayBase< Derived >::pow(), oomph::Data::set_value(), and Global_Physical_Variables::Xprescr.
parameter_study() [2/2]
template<class ELEMENT > void ElasticRingProblem< ELEMENT >::parameter_study (DocInfo & doc_info)
Perform the parameter study.
restart()
template<class ELEMENT , class TIMESTEPPER > void ElasticRingProblem< ELEMENT, TIMESTEPPER >::restart (ifstream & restart_file)
Read problem-specific parameter values, then recover generic problem data.
 {
  string input_string;
  // Read line up to termination sign
  getline(restart_file,input_string,'#');
  // Ignore rest of line
  restart_file.ignore(80,'\n');
  // Read in pcos
  Global_Physical_Variables::Pcos=atof(input_string.c_str());
  // Read line up to termination sign
  getline(restart_file,input_string,'#');
  // Ignore rest of line
  restart_file.ignore(80,'\n');
  // Read in Long run flag
  Validation_run_flag=
   unsigned(atof(input_string.c_str()));
  // Call generic read()
  Problem::read(restart_file);
 } // end of restart
References Global_Physical_Variables::Pcos, and Eigen::TensorSycl::internal::read().
set_initial_conditions()
template<class ELEMENT , class TIMESTEPPER > void ElasticRingProblem< ELEMENT, TIMESTEPPER >::set_initial_conditions
Setup initial conditions.
Setup initial conditions – either restart from solution specified via command line or impulsive start.
 {
  // No restart file --> impulsive start from initial configuration
  // assigned in the Lagrangian mesh.
  if (!Restart_flag)
   {
    // Set initial timestep
    double dt=1.0;
    // Assign impulsive start
    assign_initial_values_impulsive(dt);
   }
  // Restart file specified via command line
  else
   {
    // Try to open restart file
    ifstream* restart_file_pt=
     new ifstream(CommandLineArgs::Argv[2],ios_base::in);
    if (restart_file_pt!=0)
     {
      cout << "Have opened " << CommandLineArgs::Argv[2] <<
       " for restart. " << std::endl;
     }
    else
     {
      std::ostringstream error_stream;
      error_stream << "ERROR while trying to open "
                   << CommandLineArgs::Argv[2]
                   << " for restart." << std::endl;
      throw OomphLibError(error_stream.str(),
                          OOMPH_CURRENT_FUNCTION,
                          OOMPH_EXCEPTION_LOCATION);
     }
    // Read restart data:
    restart(*restart_file_pt);
   }
 } // end of set ic
References oomph::CommandLineArgs::Argv, OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
unsteady_run() [1/2]
template<class ELEMENT , class TIMESTEPPER > void ElasticRingProblem< ELEMENT, TIMESTEPPER >::unsteady_run
Do unsteady run.
Solver loop to perform unsteady run.
Label for output
 {
  DocInfo doc_info;
  // Output directory
  doc_info.set_directory("RESLT");
  // Step number
  doc_info.number()=0;
  // Set up trace file
  char filename[100];
  sprintf(filename,"%s/trace_ring.dat",doc_info.directory().c_str());
  Trace_file.open(filename);
  Trace_file <<  "VARIABLES=\"time\",\"R<sub>ctrl</sub>\",\"E<sub>pot</sub>\"";
  Trace_file << ",\"E<sub>kin</sub>\",\"E<sub>kin</sub>+E<sub>pot</sub>\"";
  Trace_file << ",\"<sub>exact</sub>R<sub>ctrl</sub>\""
             << std::endl;
  // Number of steps
  unsigned nstep=600;
  if (Global_Physical_Variables::Long_run_flag==0) {nstep=10;}
  // Initial timestep
  double dt=1.0;
  // Ratio for timestep reduction
  double timestep_ratio=1.0;
  if (Global_Physical_Variables::Fixed_timestep_flag==0) {timestep_ratio=0.995;}
  // Number of previous timesteps stored
  unsigned ndt=time_stepper_pt()->time_pt()->ndt();
  // Setup vector of "previous" timesteps
  Vector<double> dt_prev(ndt);
  dt_prev[0]=dt;
  for (unsigned i=1;i<ndt;i++)
   {
    dt_prev[i]=dt_prev[i-1]/timestep_ratio;
   }
  // Initialise the history of previous timesteps
  time_pt()->initialise_dt(dt_prev);
  // Initialise time
  double time0=10.0;
  time_pt()->time()=time0;
  // Setup analytical initial condition?
  if (Global_Physical_Variables::Consistent_newmark_ic)
   {
    // Note: Time has been scaled on intrinsic timescale so
    // we don't need to specify a multiplier for the inertia
    // terms (the default assignment of 1.0 is OK)
    SolidMesh::Solid_IC_problem.
     set_newmark_initial_condition_consistently(
      this,mesh_pt(),static_cast<TIMESTEPPER*>(time_stepper_pt()),IC_pt,dt);
   }
  else
   {
    SolidMesh::Solid_IC_problem.
     set_newmark_initial_condition_directly(
      this,mesh_pt(),static_cast<TIMESTEPPER*>(time_stepper_pt()),IC_pt,dt);
   }
  //Output initial data
  doc_solution(doc_info);
  // Time integration loop
  for(unsigned i=1;i<=nstep;i++)
   {
    // Solve
    unsteady_newton_solve(dt);
    // Doc solution
    doc_info.number()++;
    doc_solution(doc_info);
    // Reduce timestep
    if (time_pt()->time()<100.0) {dt=timestep_ratio*dt;}
   }
 } // end of unsteady run
References Global_Physical_Variables::Consistent_newmark_ic, oomph::DocInfo::directory(), MergeRestartFiles::filename, Global_Physical_Variables::Fixed_timestep_flag, i, Global_Physical_Variables::Long_run_flag, oomph::DocInfo::number(), oomph::DocInfo::set_directory(), and oomph::Problem_Parameter::Trace_file.
unsteady_run() [2/2]
template<class ELEMENT > void ElasticRingProblem< ELEMENT >::unsteady_run ()
Do unsteady run.
Member Data Documentation
Displ_control
template<class ELEMENT > bool ElasticRingProblem< ELEMENT >::Displ_control private
Use displacement control?
Referenced by ElasticRingProblem< ELEMENT >::ElasticRingProblem().
Displ_control_elem_pt
template<class ELEMENT > ELEMENT* ElasticRingProblem< ELEMENT >::Displ_control_elem_pt private
In which element are we applying displacement control? (here only used for doc of radius)
Referenced by ElasticRingProblem< ELEMENT >::ElasticRingProblem().
IC_pt
template<class ELEMENT > SolidInitialCondition* ElasticRingProblem< ELEMENT >::IC_pt private
Pointer to object that specifies the initial condition.
Referenced by ElasticRingProblem< ELEMENT >::ElasticRingProblem().
Length
template<class ELEMENT > double ElasticRingProblem< ELEMENT >::Length private
Length of domain (in terms of the Lagrangian coordinates)
Nbeam_element
template<class ELEMENT > unsigned ElasticRingProblem< ELEMENT >::Nbeam_element private
Number of elements in the beam mesh.
Referenced by ElasticRingProblem< ELEMENT >::ElasticRingProblem().
Restart_flag
template<class ELEMENT > bool ElasticRingProblem< ELEMENT >::Restart_flag private
Restart flag specified via command line?
S_displ_control
template<class ELEMENT > Vector<double> ElasticRingProblem< ELEMENT >::S_displ_control private
At what local coordinate are we applying displacement control?
Referenced by ElasticRingProblem< ELEMENT >::ElasticRingProblem().
Trace_file
template<class ELEMENT > ofstream ElasticRingProblem< ELEMENT >::Trace_file private
Trace file for recording control data.
Undef_geom_pt
template<class ELEMENT > GeomObject * ElasticRingProblem< ELEMENT >::Undef_geom_pt private
Pointer to geometric object that represents the undeformed shape.
Referenced by ElasticRingProblem< ELEMENT >::ElasticRingProblem().
Validation_run_flag
template<class ELEMENT > unsigned ElasticRingProblem< ELEMENT >::Validation_run_flag private
Flag for validation run: Default: 0 = no validation run.
The documentation for this class was generated from the following files:
steady_ring.cc
steady_third_ring.cc
lin_unsteady_ring.cc
unsteady_ring.cc