MercuryDPM: Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, SparseSelfAdjoint2Sparse > Struct Template Reference
Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, SparseSelfAdjoint2Sparse > Struct Template Reference
#include <SparseSelfAdjointView.h>
Public Types
typedef DstXprType::StorageIndex StorageIndex
typedef internal::assign_op< typename DstXprType::Scalar, typename SrcXprType::Scalar > AssignOpType
Static Public Member Functions
template<typename DestScalar , int StorageOrder>
static void run (SparseMatrix< DestScalar, StorageOrder, StorageIndex > &dst, const SrcXprType &src, const AssignOpType &)
template<typename DestScalar , int StorageOrder, typename AssignFunc >
static void run (SparseMatrix< DestScalar, StorageOrder, StorageIndex > &dst, const SrcXprType &src, const AssignFunc &func)
template<typename DestScalar , int StorageOrder>
static void run (SparseMatrix< DestScalar, StorageOrder, StorageIndex > &dst, const SrcXprType &src, const internal::add_assign_op< typename DstXprType::Scalar, typename SrcXprType::Scalar > &)
template<typename DestScalar , int StorageOrder>
static void run (SparseMatrix< DestScalar, StorageOrder, StorageIndex > &dst, const SrcXprType &src, const internal::sub_assign_op< typename DstXprType::Scalar, typename SrcXprType::Scalar > &)
Member Typedef Documentation
AssignOpType
template<typename DstXprType , typename SrcXprType , typename Functor > typedef internal::assign_op<typename DstXprType::Scalar, typename SrcXprType::Scalar> Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, SparseSelfAdjoint2Sparse >::AssignOpType
StorageIndex
template<typename DstXprType , typename SrcXprType , typename Functor > typedef DstXprType::StorageIndex Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, SparseSelfAdjoint2Sparse >::StorageIndex
Member Function Documentation
run() [1/4]
template<typename DstXprType , typename SrcXprType , typename Functor > template<typename DestScalar , int StorageOrder, typename AssignFunc > static void Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, SparseSelfAdjoint2Sparse >::run (SparseMatrix< DestScalar, StorageOrder, StorageIndex > & dst, const SrcXprType & src, const AssignFunc & func) inline static
{
     SparseMatrix<DestScalar, StorageOrder, StorageIndex> tmp(src.rows(), src.cols());
     run(tmp, src, AssignOpType());
     call_assignment_no_alias_no_transpose(dst, tmp, func);
   }
References Eigen::internal::call_assignment_no_alias_no_transpose(), Eigen::run(), and tmp.
run() [2/4]
template<typename DstXprType , typename SrcXprType , typename Functor > template<typename DestScalar , int StorageOrder> static void Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, SparseSelfAdjoint2Sparse >::run (SparseMatrix< DestScalar, StorageOrder, StorageIndex > & dst, const SrcXprType & src, const AssignOpType &) inline static
{
     internal::permute_symm_to_fullsymm<SrcXprType::Mode, false>(src.matrix(), dst);
   }
run() [3/4]
template<typename DstXprType , typename SrcXprType , typename Functor > template<typename DestScalar , int StorageOrder> static void Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, SparseSelfAdjoint2Sparse >::run (SparseMatrix< DestScalar, StorageOrder, StorageIndex > & dst, const SrcXprType & src, const internal::add_assign_op< typename DstXprType::Scalar, typename SrcXprType::Scalar > &) inline static
{
     SparseMatrix<DestScalar, StorageOrder, StorageIndex> tmp(src.rows(), src.cols());
     run(tmp, src, AssignOpType());
     dst += tmp;
   }
References Eigen::run(), and tmp.
run() [4/4]
template<typename DstXprType , typename SrcXprType , typename Functor > template<typename DestScalar , int StorageOrder> static void Eigen::internal::Assignment< DstXprType, SrcXprType, Functor, SparseSelfAdjoint2Sparse >::run (SparseMatrix< DestScalar, StorageOrder, StorageIndex > & dst, const SrcXprType & src, const internal::sub_assign_op< typename DstXprType::Scalar, typename SrcXprType::Scalar > &) inline static
{
     SparseMatrix<DestScalar, StorageOrder, StorageIndex> tmp(src.rows(), src.cols());
     run(tmp, src, AssignOpType());
     dst -= tmp;
   }
References Eigen::run(), and tmp.
The documentation for this struct was generated from the following file:
SparseSelfAdjointView.h