MercuryDPM: oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM > Class Template Reference
oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM > Class Template Reference
#include <generalised_newtonian_constitutive_models.h>
Public Member Functions
HerschelBulkleyTanMilRegConstitutiveEquation (double *yield_stress_pt, double *flow_index_pt, double *critical_second_invariant_pt)
"Cutoff regularised" Herschel Bulkley constitutive equation
double calculate_cut_off_viscosity ()
Function that calculates the cut off viscosity.
void report_cut_off_values (double &cut_off_invariant, double &cut_off_viscosity)
Report cutoff values.
double viscosity (const double &second_invariant_of_rate_of_strain_tensor)
Viscosity ratio as a fct of strain rate invariant.
double dviscosity_dinvariant (const double &second_invariant_of_rate_of_strain_tensor)
Deriv of viscosity w.r.t. strain rate invariant.
Public Member Functions inherited from oomph::GeneralisedNewtonianConstitutiveEquation< DIM >
GeneralisedNewtonianConstitutiveEquation ()
Empty constructor.
virtual ~GeneralisedNewtonianConstitutiveEquation ()
Empty virtual destructor.
Private Attributes
double * Yield_stress_pt
yield stress tau_y
double * Flow_index_pt
power law index n
double * Critical_second_invariant_pt
Detailed Description
template<unsigned DIM>
class oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >
A GeneralisedNewtonianConstitutiveEquation class defining a Herschel-Bulkley fluid using Tanner and Milthorpe's (1983) regularisation
Constructor & Destructor Documentation
HerschelBulkleyTanMilRegConstitutiveEquation()
template<unsigned DIM> oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::HerschelBulkleyTanMilRegConstitutiveEquation (double * yield_stress_pt, double * flow_index_pt, double * critical_second_invariant_pt) inline
"Cutoff regularised" Herschel Bulkley constitutive equation
       : GeneralisedNewtonianConstitutiveEquation<DIM>(),
         Yield_stress_pt(yield_stress_pt),
         Flow_index_pt(flow_index_pt),
         Critical_second_invariant_pt(critical_second_invariant_pt)
     {
       // Calculate the Newtonian cutoff viscosity from the constitutive
       // equation and the cutoff value of the second invariant
       double cut_off_viscosity = calculate_cut_off_viscosity();
       oomph_info << "HerschelBulkleyTanMilRegConstitutiveEquation: "
                  << " cutoff viscosity = " << cut_off_viscosity << std::endl;
       oomph_info << "                                              "
                  << " cutoff invariant = " << *Critical_second_invariant_pt
                  << std::endl;
     }
References oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::calculate_cut_off_viscosity(), oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::Critical_second_invariant_pt, and oomph::oomph_info.
Member Function Documentation
calculate_cut_off_viscosity()
template<unsigned DIM> double oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::calculate_cut_off_viscosity () inline
Function that calculates the cut off viscosity.
     {
       return (*Yield_stress_pt) /
                (2.0 * sqrt((*Critical_second_invariant_pt))) +
              pow((2.0 * sqrt((*Critical_second_invariant_pt))),
                  *Flow_index_pt - 1.0);
     }
References oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::Critical_second_invariant_pt, oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::Flow_index_pt, Eigen::bfloat16_impl::pow(), sqrt(), and oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::Yield_stress_pt.
Referenced by oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::HerschelBulkleyTanMilRegConstitutiveEquation(), oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::report_cut_off_values(), and oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::viscosity().
dviscosity_dinvariant()
template<unsigned DIM> double oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::dviscosity_dinvariant (const double & second_invariant_of_rate_of_strain_tensor) inline virtual
Deriv of viscosity w.r.t. strain rate invariant.
Implements oomph::GeneralisedNewtonianConstitutiveEquation< DIM >.
     {
       // Pre-multiply the second invariant with +/-1 depending on whether it's
       // positive or not
       double sign = -1.0;
       if (second_invariant_of_rate_of_strain_tensor >= 0.0)
       {
         sign = 1.0;
       }
       if (sign * second_invariant_of_rate_of_strain_tensor <
           (*Critical_second_invariant_pt))
       {
         return 0.0;
       }
       else
       {
         return sign * pow(2.0, (*Flow_index_pt) - 2.0) *
                  ((*Flow_index_pt) - 1.0) *
                  pow(sign * second_invariant_of_rate_of_strain_tensor,
                      ((*Flow_index_pt) - 1.0) / 2.0 - 1.0) -
                sign * (*Yield_stress_pt) /
                  (4.0 * pow(sign * second_invariant_of_rate_of_strain_tensor,
                             3.0 / 2.0));
       }
     }
References oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::Critical_second_invariant_pt, oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::Flow_index_pt, Eigen::bfloat16_impl::pow(), SYCL::sign(), and oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::Yield_stress_pt.
report_cut_off_values()
template<unsigned DIM> void oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::report_cut_off_values (double & cut_off_invariant, double & cut_off_viscosity) inline
Report cutoff values.
     {
       cut_off_invariant = *Critical_second_invariant_pt;
       cut_off_viscosity = calculate_cut_off_viscosity();
     }
References oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::calculate_cut_off_viscosity(), and oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::Critical_second_invariant_pt.
viscosity()
template<unsigned DIM> double oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::viscosity (const double & second_invariant_of_rate_of_strain_tensor) inline virtual
Viscosity ratio as a fct of strain rate invariant.
Implements oomph::GeneralisedNewtonianConstitutiveEquation< DIM >.
     {
       // Pre-multiply the second invariant with +/-1 depending on whether it's
       // positive or not
       double sign = -1.0;
       if (second_invariant_of_rate_of_strain_tensor >= 0.0)
       {
         sign = 1.0;
       }
       // std::cout<<"I2 "<<second_invariant_of_rate_of_strain_tensor<<std::endl;
       // if the second invariant is below the cutoff we have a constant,
       // Newtonian viscosity
       if (sign * second_invariant_of_rate_of_strain_tensor <
           (*Critical_second_invariant_pt))
       {
         return calculate_cut_off_viscosity();
       }
       else
       {
         // Calculate the square root of the absolute value of the
         // second invariant of the rate of strain tensor
         double measure_of_rate_of_strain =
           sqrt(sign * second_invariant_of_rate_of_strain_tensor);
         return (*Yield_stress_pt) / (2.0 * measure_of_rate_of_strain) +
                pow((2.0 * measure_of_rate_of_strain), *Flow_index_pt - 1.0);
       }
     }
References oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::calculate_cut_off_viscosity(), oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::Critical_second_invariant_pt, oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::Flow_index_pt, Eigen::bfloat16_impl::pow(), SYCL::sign(), sqrt(), and oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::Yield_stress_pt.
Member Data Documentation
Critical_second_invariant_pt
template<unsigned DIM> double* oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::Critical_second_invariant_pt private
value of the second invariant below which we have constant (Newtonian) viscosity – assumed to be always positive
Referenced by oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::calculate_cut_off_viscosity(), oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::dviscosity_dinvariant(), oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::HerschelBulkleyTanMilRegConstitutiveEquation(), oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::report_cut_off_values(), and oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::viscosity().
Flow_index_pt
template<unsigned DIM> double* oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::Flow_index_pt private
power law index n
Referenced by oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::calculate_cut_off_viscosity(), oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::dviscosity_dinvariant(), and oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::viscosity().
Yield_stress_pt
template<unsigned DIM> double* oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::Yield_stress_pt private
yield stress tau_y
Referenced by oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::calculate_cut_off_viscosity(), oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::dviscosity_dinvariant(), and oomph::HerschelBulkleyTanMilRegConstitutiveEquation< DIM >::viscosity().
The documentation for this class was generated from the following file:
generalised_newtonian_constitutive_models.h