MercuryDPM: DenseLM< Scalar > Struct Template Reference
DenseLM< Scalar > Struct Template Reference
Public Types
typedef DenseFunctor< Scalar > Base
typedef Base::JacobianType JacobianType
typedef Matrix< Scalar, Dynamic, 1 > VectorType
Public Types inherited from Eigen::DenseFunctor< Scalar >
enum
typedef Scalar Scalar
typedef Matrix< Scalar, InputsAtCompileTime, 1 > InputType
typedef Matrix< Scalar, ValuesAtCompileTime, 1 > ValueType
typedef Matrix< Scalar, ValuesAtCompileTime, InputsAtCompileTime > JacobianType
typedef ColPivHouseholderQR< JacobianType > QRSolver
Public Member Functions
DenseLM (int n, int m)
VectorType model (const VectorType &uv, VectorType &x)
void initPoints (VectorType &uv_ref, VectorType &x)
int operator() (const VectorType &uv, VectorType &fvec)
int df (const VectorType &uv, JacobianType &fjac)
Public Member Functions inherited from Eigen::DenseFunctor< Scalar >
DenseFunctor ()
DenseFunctor (int inputs, int values)
int inputs () const
int values () const
Public Attributes
VectorType m_x
VectorType m_y
Public Attributes inherited from Eigen::DenseFunctor< Scalar >
const int m_inputs
const int m_values
Member Typedef Documentation
Base
template<typename Scalar > typedef DenseFunctor<Scalar> DenseLM< Scalar >::Base
JacobianType
template<typename Scalar > typedef Base::JacobianType DenseLM< Scalar >::JacobianType
VectorType
template<typename Scalar > typedef Matrix<Scalar, Dynamic, 1> DenseLM< Scalar >::VectorType
Constructor & Destructor Documentation
DenseLM()
template<typename Scalar > DenseLM< Scalar >::DenseLM (int n, int m) inline
 : DenseFunctor<Scalar>(n, m) {}
Member Function Documentation
df()
template<typename Scalar > int DenseLM< Scalar >::df (const VectorType & uv, JacobianType & fjac) inline
{
     int m = Base::values();
     int n = Base::inputs();
     eigen_assert(n == uv.size());
     eigen_assert(fjac.rows() == m);
     eigen_assert(fjac.cols() == n);
     int half = n / 2;
     VectorBlock<const VectorType> u(uv, 0, half);
     VectorBlock<const VectorType> v(uv, half, half);
     for (int j = 0; j < m; j++) {
       for (int i = 0; i < half; i++) {
         fjac.coeffRef(j, i) = -std::exp(-(m_x(j) - i) * (m_x(j) - i) / (v(i) * v(i)));
         fjac.coeffRef(j, i + half) = -2. * u(i) * (m_x(j) - i) * (m_x(j) - i) / (std::pow(v(i), 3)) *
                                      std::exp(-(m_x(j) - i) * (m_x(j) - i) / (v(i) * v(i)));
       }
     }
     return 0;
   }
References Eigen::Matrix< Scalar_, Rows_, Cols_, Options_, MaxRows_, MaxCols_ >::coeffRef(), Eigen::PlainObjectBase< Derived >::cols(), eigen_assert, Eigen::bfloat16_impl::exp(), i, j, m, n, Eigen::bfloat16_impl::pow(), Eigen::PlainObjectBase< Derived >::rows(), and v.
initPoints()
template<typename Scalar > void DenseLM< Scalar >::initPoints (VectorType & uv_ref, VectorType & x) inline
{
     m_x = x;
     m_y = this->model(uv_ref, x);
   }
References plotDoE::x.
Referenced by test_denseLM_T().
model()
template<typename Scalar > VectorType DenseLM< Scalar >::model (const VectorType & uv, VectorType & x) inline
{
     VectorType y;  // Should change to use expression template
     int m = Base::values();
     int n = Base::inputs();
     eigen_assert(uv.size() % 2 == 0);
     eigen_assert(uv.size() == n);
     eigen_assert(x.size() == m);
     y.setZero(m);
     int half = n / 2;
     VectorBlock<const VectorType> u(uv, 0, half);
     VectorBlock<const VectorType> v(uv, half, half);
     for (int j = 0; j < m; j++) {
       for (int i = 0; i < half; i++) y(j) += u(i) * std::exp(-(x(j) - i) * (x(j) - i) / (v(i) * v(i)));
     }
     return y;
   }
References eigen_assert, Eigen::bfloat16_impl::exp(), i, j, m, n, v, plotDoE::x, and y.
operator()()
template<typename Scalar > int DenseLM< Scalar >::operator() (const VectorType & uv, VectorType & fvec) inline
{
     int m = Base::values();
     int n = Base::inputs();
     eigen_assert(uv.size() % 2 == 0);
     eigen_assert(uv.size() == n);
     eigen_assert(fvec.size() == m);
     int half = n / 2;
     VectorBlock<const VectorType> u(uv, 0, half);
     VectorBlock<const VectorType> v(uv, half, half);
     for (int j = 0; j < m; j++) {
       fvec(j) = m_y(j);
       for (int i = 0; i < half; i++) {
         fvec(j) -= u(i) * std::exp(-(m_x(j) - i) * (m_x(j) - i) / (v(i) * v(i)));
       }
     }
     return 0;
   }
References eigen_assert, Eigen::bfloat16_impl::exp(), i, j, m, n, and v.
Member Data Documentation
m_x
template<typename Scalar > VectorType DenseLM< Scalar >::m_x
m_y
template<typename Scalar > VectorType DenseLM< Scalar >::m_y
The documentation for this struct was generated from the following file:
denseLM.cpp