MercuryDPM: Time Class Reference
Time Class Reference
Allows for timing the algorithms; accurate up to 0.01 sec.
#include <MercuryTime.h>
Public Member Functions
Time ()
void tic ()
This is like a start button of a stopwatch. Assigns the variable start with the current number of clock ticks.
Mdouble toc ()
This is like a stop button of a stopwatch. Assigns the variable finish to the current value of ticks returned by clock().
Mdouble getCPUTime () const
Mdouble getWallTime ()
Mdouble toctic ()
Outputs the toc value and resets the start time.
Private Attributes
clock_t start
Stores the number of clock ticks, called by Time::tic().
std::chrono::time_point< std::chrono::high_resolution_clock > wallClockStart
clock_t finish
Stores the number of clock ticks, called by Time::toc().
std::chrono::time_point< std::chrono::high_resolution_clock > wallClockFinish
Detailed Description
Allows for timing the algorithms; accurate up to 0.01 sec.
Calculates the amount of computational time used, in seconds. Works on the same concept of stopwatch, where one presses start and stops when needed. The difference returns the total time used up. Usage: Time time; ...; std::cout << time.toc();
Constructor & Destructor Documentation
Time()
Time::Time () inline
             {
         tic();
         start = 0;
         finish = 0;
     }
References finish, start, and tic().
Member Function Documentation
getCPUTime()
Mdouble Time::getCPUTime () const inline
Returns the time elapsed (in seconds) between tic and toc.
     {
         return (Mdouble(finish) - Mdouble(start)) / CLOCKS_PER_SEC;
     }
References finish, and start.
Referenced by DPMBase::getCPUTime().
getWallTime()
Mdouble Time::getWallTime () inline
Returns the time elapsed (in seconds) between tic and toc.
     {
         return std::chrono::duration<double>(wallClockFinish-wallClockStart).count();
     }
References wallClockFinish, and wallClockStart.
Referenced by DPMBase::getWallTime(), and toc().
tic()
void Time::tic () inline
This is like a start button of a stopwatch. Assigns the variable start with the current number of clock ticks.
     {
         start = clock(); //clock tics
         wallClockStart = std::chrono::high_resolution_clock::now();
     }
References start, and wallClockStart.
Referenced by main(), DPMBase::solve(), and Time().
toc()
Mdouble Time::toc () inline
This is like a stop button of a stopwatch. Assigns the variable finish to the current value of ticks returned by clock().
Returns
However, it also returns the total real time in seconds.
     {
         finish = clock();
         wallClockFinish = std::chrono::high_resolution_clock::now();
         return getWallTime();
     }
References finish, getWallTime(), and wallClockFinish.
Referenced by main(), DPMBase::solve(), and toctic().
toctic()
Mdouble Time::toctic () inline
Outputs the toc value and resets the start time.
     {
         Mdouble tocTime = toc();
         start = finish;
         return tocTime;
     }
References finish, start, and toc().
Member Data Documentation
finish
clock_t Time::finish private
Stores the number of clock ticks, called by Time::toc().
Referenced by getCPUTime(), Time(), toc(), and toctic().
start
clock_t Time::start private
Stores the number of clock ticks, called by Time::tic().
Referenced by getCPUTime(), tic(), Time(), and toctic().
wallClockFinish
std::chrono::time_point<std::chrono::high_resolution_clock> Time::wallClockFinish private
Referenced by getWallTime(), and toc().
wallClockStart
std::chrono::time_point<std::chrono::high_resolution_clock> Time::wallClockStart private
Referenced by getWallTime(), and tic().
The documentation for this class was generated from the following file:
MercuryTime.h