MercuryDPM: Eigen::internal::compute_inverse_size4< Architecture::Target, double, MatrixType, ResultType > Struct Template Reference
Eigen::internal::compute_inverse_size4< Architecture::Target, double, MatrixType, ResultType > Struct Template Reference
#include <InverseSize4.h>
Public Types
enum { MatrixAlignment = traits<MatrixType>::Alignment , ResultAlignment = traits<ResultType>::Alignment , StorageOrdersMatch = (MatrixType::Flags & RowMajorBit) == (ResultType::Flags & RowMajorBit) }
typedef std::conditional_t<(MatrixType::Flags &LinearAccessBit), MatrixType const &, typename MatrixType::PlainObject > ActualMatrixType
Static Public Member Functions
static void run (const MatrixType &mat, ResultType &result)
Member Typedef Documentation
ActualMatrixType
template<typename MatrixType , typename ResultType > typedef std::conditional_t<(MatrixType::Flags & LinearAccessBit), MatrixType const &, typename MatrixType::PlainObject> Eigen::internal::compute_inverse_size4< Architecture::Target, double, MatrixType, ResultType >::ActualMatrixType
Member Enumeration Documentation
anonymous enum
template<typename MatrixType , typename ResultType > anonymous enum
Enumerator
MatrixAlignment
ResultAlignment
StorageOrdersMatch
        {
     MatrixAlignment = traits<MatrixType>::Alignment,
     ResultAlignment = traits<ResultType>::Alignment,
     StorageOrdersMatch = (MatrixType::Flags & RowMajorBit) == (ResultType::Flags & RowMajorBit)
   };
Member Function Documentation
run()
template<typename MatrixType , typename ResultType > static void Eigen::internal::compute_inverse_size4< Architecture::Target, double, MatrixType, ResultType >::run (const MatrixType & mat, ResultType & result) inline static
{
     ActualMatrixType matrix(mat);
     // Four 2x2 sub-matrices of the input matrix, each is further divided into upper and lower
     // row e.g. A1, upper row of A, A2, lower row of A
     // input = [[A, B],  =  [[[A1, [B1,
     //          [C, D]]        A2], B2]],
     //                       [[C1, [D1,
     //                         C2], D2]]]
     Packet2d A1, A2, B1, B2, C1, C2, D1, D2;
     const double *data = matrix.data();
     const Index stride = matrix.innerStride();
     if (StorageOrdersMatch) {
       A1 = ploadt<Packet2d, MatrixAlignment>(data + stride * 0);
       B1 = ploadt<Packet2d, MatrixAlignment>(data + stride * 2);
       A2 = ploadt<Packet2d, MatrixAlignment>(data + stride * 4);
       B2 = ploadt<Packet2d, MatrixAlignment>(data + stride * 6);
       C1 = ploadt<Packet2d, MatrixAlignment>(data + stride * 8);
       D1 = ploadt<Packet2d, MatrixAlignment>(data + stride * 10);
       C2 = ploadt<Packet2d, MatrixAlignment>(data + stride * 12);
       D2 = ploadt<Packet2d, MatrixAlignment>(data + stride * 14);
     } else {
       Packet2d temp;
       A1 = ploadt<Packet2d, MatrixAlignment>(data + stride * 0);
       C1 = ploadt<Packet2d, MatrixAlignment>(data + stride * 2);
       A2 = ploadt<Packet2d, MatrixAlignment>(data + stride * 4);
       C2 = ploadt<Packet2d, MatrixAlignment>(data + stride * 6);
       temp = A1;
       A1 = vec2d_unpacklo(A1, A2);
       A2 = vec2d_unpackhi(temp, A2);
       temp = C1;
       C1 = vec2d_unpacklo(C1, C2);
       C2 = vec2d_unpackhi(temp, C2);
       B1 = ploadt<Packet2d, MatrixAlignment>(data + stride * 8);
       D1 = ploadt<Packet2d, MatrixAlignment>(data + stride * 10);
       B2 = ploadt<Packet2d, MatrixAlignment>(data + stride * 12);
       D2 = ploadt<Packet2d, MatrixAlignment>(data + stride * 14);
       temp = B1;
       B1 = vec2d_unpacklo(B1, B2);
       B2 = vec2d_unpackhi(temp, B2);
       temp = D1;
       D1 = vec2d_unpacklo(D1, D2);
       D2 = vec2d_unpackhi(temp, D2);
     }
     // determinants of the sub-matrices
     Packet2d dA, dB, dC, dD;
     dA = vec2d_swizzle2(A2, A2, 1);
     dA = pmul(A1, dA);
     dA = psub(dA, vec2d_duplane(dA, 1));
     dB = vec2d_swizzle2(B2, B2, 1);
     dB = pmul(B1, dB);
     dB = psub(dB, vec2d_duplane(dB, 1));
     dC = vec2d_swizzle2(C2, C2, 1);
     dC = pmul(C1, dC);
     dC = psub(dC, vec2d_duplane(dC, 1));
     dD = vec2d_swizzle2(D2, D2, 1);
     dD = pmul(D1, dD);
     dD = psub(dD, vec2d_duplane(dD, 1));
     Packet2d DC1, DC2, AB1, AB2;
     // AB = A# * B, where A# denotes the adjugate of A, and * denotes matrix product.
     AB1 = pmul(B1, vec2d_duplane(A2, 1));
     AB2 = pmul(B2, vec2d_duplane(A1, 0));
     AB1 = psub(AB1, pmul(B2, vec2d_duplane(A1, 1)));
     AB2 = psub(AB2, pmul(B1, vec2d_duplane(A2, 0)));
     // DC = D#*C
     DC1 = pmul(C1, vec2d_duplane(D2, 1));
     DC2 = pmul(C2, vec2d_duplane(D1, 0));
     DC1 = psub(DC1, pmul(C2, vec2d_duplane(D1, 1)));
     DC2 = psub(DC2, pmul(C1, vec2d_duplane(D2, 0)));
     Packet2d d1, d2;
     // determinant of the input matrix, det = |A||D| + |B||C| - trace(A#*B*D#*C)
     Packet2d det;
     // reciprocal of the determinant of the input matrix, rd = 1/det
     Packet2d rd;
     d1 = pmul(AB1, vec2d_swizzle2(DC1, DC2, 0));
     d2 = pmul(AB2, vec2d_swizzle2(DC1, DC2, 3));
     rd = padd(d1, d2);
     rd = padd(rd, vec2d_duplane(rd, 1));
     d1 = pmul(dA, dD);
     d2 = pmul(dB, dC);
     det = padd(d1, d2);
     det = psub(det, rd);
     det = vec2d_duplane(det, 0);
     rd = pdiv(pset1<Packet2d>(1.0), det);
     // rows of four sub-matrices of the inverse
     Packet2d iA1, iA2, iB1, iB2, iC1, iC2, iD1, iD2;
     // iD = D*|A| - C*A#*B
     iD1 = pmul(AB1, vec2d_duplane(C1, 0));
     iD2 = pmul(AB1, vec2d_duplane(C2, 0));
     iD1 = padd(iD1, pmul(AB2, vec2d_duplane(C1, 1)));
     iD2 = padd(iD2, pmul(AB2, vec2d_duplane(C2, 1)));
     dA = vec2d_duplane(dA, 0);
     iD1 = psub(pmul(D1, dA), iD1);
     iD2 = psub(pmul(D2, dA), iD2);
     // iA = A*|D| - B*D#*C
     iA1 = pmul(DC1, vec2d_duplane(B1, 0));
     iA2 = pmul(DC1, vec2d_duplane(B2, 0));
     iA1 = padd(iA1, pmul(DC2, vec2d_duplane(B1, 1)));
     iA2 = padd(iA2, pmul(DC2, vec2d_duplane(B2, 1)));
     dD = vec2d_duplane(dD, 0);
     iA1 = psub(pmul(A1, dD), iA1);
     iA2 = psub(pmul(A2, dD), iA2);
     // iB = C*|B| - D * (A#B)# = C*|B| - D*B#*A
     iB1 = pmul(D1, vec2d_swizzle2(AB2, AB1, 1));
     iB2 = pmul(D2, vec2d_swizzle2(AB2, AB1, 1));
     iB1 = psub(iB1, pmul(vec2d_swizzle2(D1, D1, 1), vec2d_swizzle2(AB2, AB1, 2)));
     iB2 = psub(iB2, pmul(vec2d_swizzle2(D2, D2, 1), vec2d_swizzle2(AB2, AB1, 2)));
     dB = vec2d_duplane(dB, 0);
     iB1 = psub(pmul(C1, dB), iB1);
     iB2 = psub(pmul(C2, dB), iB2);
     // iC = B*|C| - A * (D#C)# = B*|C| - A*C#*D
     iC1 = pmul(A1, vec2d_swizzle2(DC2, DC1, 1));
     iC2 = pmul(A2, vec2d_swizzle2(DC2, DC1, 1));
     iC1 = psub(iC1, pmul(vec2d_swizzle2(A1, A1, 1), vec2d_swizzle2(DC2, DC1, 2)));
     iC2 = psub(iC2, pmul(vec2d_swizzle2(A2, A2, 1), vec2d_swizzle2(DC2, DC1, 2)));
     dC = vec2d_duplane(dC, 0);
     iC1 = psub(pmul(B1, dC), iC1);
     iC2 = psub(pmul(B2, dC), iC2);
     EIGEN_ALIGN_MAX const double sign_mask1[2] = {0.0, -0.0};
     EIGEN_ALIGN_MAX const double sign_mask2[2] = {-0.0, 0.0};
     const Packet2d sign_PN = pload<Packet2d>(sign_mask1);
     const Packet2d sign_NP = pload<Packet2d>(sign_mask2);
     d1 = pxor(rd, sign_PN);
     d2 = pxor(rd, sign_NP);
     Index res_stride = result.outerStride();
     double *res = result.data();
     pstoret<double, Packet2d, ResultAlignment>(res + 0, pmul(vec2d_swizzle2(iA2, iA1, 3), d1));
     pstoret<double, Packet2d, ResultAlignment>(res + res_stride, pmul(vec2d_swizzle2(iA2, iA1, 0), d2));
     pstoret<double, Packet2d, ResultAlignment>(res + 2, pmul(vec2d_swizzle2(iB2, iB1, 3), d1));
     pstoret<double, Packet2d, ResultAlignment>(res + res_stride + 2, pmul(vec2d_swizzle2(iB2, iB1, 0), d2));
     pstoret<double, Packet2d, ResultAlignment>(res + 2 * res_stride, pmul(vec2d_swizzle2(iC2, iC1, 3), d1));
     pstoret<double, Packet2d, ResultAlignment>(res + 3 * res_stride, pmul(vec2d_swizzle2(iC2, iC1, 0), d2));
     pstoret<double, Packet2d, ResultAlignment>(res + 2 * res_stride + 2, pmul(vec2d_swizzle2(iD2, iD1, 3), d1));
     pstoret<double, Packet2d, ResultAlignment>(res + 3 * res_stride + 2, pmul(vec2d_swizzle2(iD2, iD1, 0), d2));
   }
References Global_Physical_Variables::C1, Global_Physical_Variables::C2, data, EIGEN_ALIGN_MAX, matrix(), Eigen::internal::padd(), Eigen::internal::pdiv(), Eigen::internal::pload< Packet2d >(), Eigen::internal::pmul(), Eigen::internal::pset1< Packet2d >(), Eigen::internal::psub(), Eigen::internal::pxor(), res, vec2d_duplane, Eigen::internal::vec2d_swizzle2(), Eigen::internal::vec2d_unpackhi(), and Eigen::internal::vec2d_unpacklo().
The documentation for this struct was generated from the following file:
InverseSize4.h