MercuryDPM: vectorization_logic_half< Scalar, Enable > Struct Template Reference
vectorization_logic_half< Scalar, Enable > Struct Template Reference
Public Types
using RealScalar = typename NumTraits< Scalar >::Real
typedef internal::packet_traits< Scalar > PacketTraits
typedef internal::unpacket_traits< typename internal::packet_traits< Scalar >::type >::half PacketType
Static Public Member Functions
static void run ()
Static Public Attributes
static constexpr int PacketSize = internal::unpacket_traits<PacketType>::size
Member Typedef Documentation
PacketTraits
template<typename Scalar , bool Enable = !internal::is_same< typename internal::unpacket_traits<typename internal::packet_traits<Scalar>::type>::half, typename internal::packet_traits<Scalar>::type>::value> typedef internal::packet_traits<Scalar> vectorization_logic_half< Scalar, Enable >::PacketTraits
PacketType
template<typename Scalar , bool Enable = !internal::is_same< typename internal::unpacket_traits<typename internal::packet_traits<Scalar>::type>::half, typename internal::packet_traits<Scalar>::type>::value> typedef internal::unpacket_traits<typename internal::packet_traits<Scalar>::type>::half vectorization_logic_half< Scalar, Enable >::PacketType
RealScalar
template<typename Scalar , bool Enable = !internal::is_same< typename internal::unpacket_traits<typename internal::packet_traits<Scalar>::type>::half, typename internal::packet_traits<Scalar>::type>::value> using vectorization_logic_half< Scalar, Enable >::RealScalar = typename NumTraits<Scalar>::Real
Member Function Documentation
run()
template<typename Scalar , bool Enable = !internal::is_same< typename internal::unpacket_traits<typename internal::packet_traits<Scalar>::type>::half, typename internal::packet_traits<Scalar>::type>::value> static void vectorization_logic_half< Scalar, Enable >::run () inline static
                     {
     // Some half-packets have a byte size < EIGEN_MIN_ALIGN_BYTES (e.g. Packet2f),
     // which causes many of these tests to fail since they don't vectorize if
     // EIGEN_UNALIGNED_VECTORIZE is 0 (the matrix is assumed unaligned).
     // Adjust the matrix sizes to account for these alignment issues.
     constexpr int PacketBytes = sizeof(Scalar) * PacketSize;
     constexpr int MinVSize = int(EIGEN_UNALIGNED_VECTORIZE) ? PacketSize
                              : PacketBytes >= EIGEN_MIN_ALIGN_BYTES
                                  ? PacketSize
                                  : (EIGEN_MIN_ALIGN_BYTES + sizeof(Scalar) - 1) / sizeof(Scalar);
     typedef Matrix<Scalar, MinVSize, 1> Vector1;
     typedef Matrix<Scalar, MinVSize, MinVSize> Matrix11;
     typedef Matrix<Scalar, 5 * MinVSize, 7, ColMajor> Matrix57;
     typedef Matrix<Scalar, 3 * MinVSize, 5, ColMajor> Matrix35;
     typedef Matrix<Scalar, 5 * MinVSize, 7, DontAlign | ColMajor> Matrix57u;
     typedef Matrix<Scalar,
                    (PacketSize == 16  ? 8
                     : PacketSize == 8 ? 4
                     : PacketSize == 4 ? 2
                     : PacketSize == 2 ? 1
                                       : /*PacketSize==1 ?*/ 1),
                    (PacketSize == 16  ? 2
                     : PacketSize == 8 ? 2
                     : PacketSize == 4 ? 2
                     : PacketSize == 2 ? 2
                                       : /*PacketSize==1 ?*/ 1)>
         Matrix1;
     typedef Matrix<Scalar,
                    (PacketSize == 16  ? 8
                     : PacketSize == 8 ? 4
                     : PacketSize == 4 ? 2
                     : PacketSize == 2 ? 1
                                       : /*PacketSize==1 ?*/ 1),
                    (PacketSize == 16  ? 2
                     : PacketSize == 8 ? 2
                     : PacketSize == 4 ? 2
                     : PacketSize == 2 ? 2
                                       : /*PacketSize==1 ?*/ 1),
                    DontAlign | ((Matrix1::Flags & RowMajorBit) ? RowMajor : ColMajor)>
         Matrix1u;
     // this type is made such that it can only be vectorized when viewed as a linear 1D vector
     typedef Matrix<Scalar,
                    (MinVSize == 16  ? 4
                     : MinVSize == 8 ? 4
                     : MinVSize == 4 ? 6
                     : MinVSize == 2 ? ((Matrix11::Flags & RowMajorBit) ? 2 : 3)
                                     : /*PacketSize==1 ?*/ 1),
                    (MinVSize == 16  ? 12
                     : MinVSize == 8 ? 6
                     : MinVSize == 4 ? 2
                     : MinVSize == 2 ? ((Matrix11::Flags & RowMajorBit) ? 3 : 2)
                                     : /*PacketSize==1 ?*/ 3)>
         Matrix3;
 #if !EIGEN_GCC_AND_ARCH_DOESNT_WANT_STACK_ALIGNMENT
     VERIFY(test_assign(Vector1(), Vector1(), InnerVectorizedTraversal, CompleteUnrolling));
     VERIFY(test_assign(Vector1(), Vector1() + Vector1(), InnerVectorizedTraversal, CompleteUnrolling));
     VERIFY(test_assign(Vector1(), Vector1().template segment<MinVSize>(0).derived(),
                        EIGEN_UNALIGNED_VECTORIZE ? InnerVectorizedTraversal : LinearVectorizedTraversal,
                        CompleteUnrolling));
     VERIFY(test_assign(Vector1(), Scalar(RealScalar(2.1)) * Vector1() - Vector1(), InnerVectorizedTraversal,
                        CompleteUnrolling));
     VERIFY(test_assign(
         Vector1(),
         (Scalar(RealScalar(2.1)) * Vector1().template segment<MinVSize>(0) - Vector1().template segment<MinVSize>(0))
             .derived(),
         EIGEN_UNALIGNED_VECTORIZE ? InnerVectorizedTraversal : LinearVectorizedTraversal, CompleteUnrolling));
     VERIFY(test_assign(Vector1(), Vector1().cwiseProduct(Vector1()), InnerVectorizedTraversal, CompleteUnrolling));
     VERIFY(test_assign(Vector1(), Vector1().template cast<Scalar>(), InnerVectorizedTraversal, CompleteUnrolling));
     VERIFY(test_assign(Matrix57(), Matrix57() + Matrix57(), InnerVectorizedTraversal, InnerUnrolling));
     VERIFY(test_assign(Matrix57u(), Matrix57() + Matrix57(),
                        EIGEN_UNALIGNED_VECTORIZE ? InnerVectorizedTraversal : LinearTraversal,
                        EIGEN_UNALIGNED_VECTORIZE ? InnerUnrolling : NoUnrolling));
     VERIFY(test_assign(Matrix1u(), Matrix1() + Matrix1(),
                        EIGEN_UNALIGNED_VECTORIZE
                            ? ((int(Matrix1::InnerSizeAtCompileTime) % int(PacketSize)) == 0 ? InnerVectorizedTraversal
                                                                                             : LinearVectorizedTraversal)
                            : LinearTraversal,
                        CompleteUnrolling));
     if (PacketSize > 1) {
       typedef Matrix<Scalar, 3, 3, ColMajor> Matrix33c;
       VERIFY(
           test_assign(Matrix33c().row(2), Matrix33c().row(1) + Matrix33c().row(1), LinearTraversal, CompleteUnrolling));
       // Unrolling depends on read costs and unroll limits, which vary - ignore.
       VERIFY(test_assign(Matrix3(), Matrix3().cwiseQuotient(Matrix3()),
                          PacketTraits::HasDiv ? LinearVectorizedTraversal : LinearTraversal, -1));
       VERIFY(test_assign(Matrix<Scalar, 17, 17>(), Matrix<Scalar, 17, 17>() + Matrix<Scalar, 17, 17>(),
                          sizeof(Scalar) == 16
                              ? InnerVectorizedTraversal
                              : (EIGEN_UNALIGNED_VECTORIZE ? LinearVectorizedTraversal : LinearTraversal),
                          NoUnrolling));
       VERIFY(test_assign(Matrix11(),
                          Matrix<Scalar, 17, 17>().template block<MinVSize, MinVSize>(2, 3) +
                              Matrix<Scalar, 17, 17>().template block<MinVSize, MinVSize>(8, 4),
                          EIGEN_UNALIGNED_VECTORIZE ? InnerVectorizedTraversal : DefaultTraversal,
                          InnerUnrolling + CompleteUnrolling));
       VERIFY(test_assign(Vector1(), Matrix11() * Vector1(), InnerVectorizedTraversal, CompleteUnrolling));
       VERIFY(test_assign(Matrix11(), Matrix11().lazyProduct(Matrix11()), InnerVectorizedTraversal,
                          InnerUnrolling + CompleteUnrolling));
     }
     VERIFY(test_redux(Vector1(), LinearVectorizedTraversal, CompleteUnrolling));
     VERIFY(test_redux(Matrix<Scalar, MinVSize, 3>(), LinearVectorizedTraversal, CompleteUnrolling));
     VERIFY(test_redux(Matrix3(), LinearVectorizedTraversal, CompleteUnrolling));
     VERIFY(test_redux(Matrix35(), LinearVectorizedTraversal, CompleteUnrolling));
     VERIFY(test_redux(Matrix57().template block < PacketSize == 1 ? 2 : PacketSize, 3 > (1, 0),
                       SliceVectorizedTraversal, CompleteUnrolling));
     if (PacketSize > 1) {
       VERIFY(test_redux(Matrix57().template block<PacketSize, 2>(1, 0), DefaultTraversal, CompleteUnrolling));
     }
     VERIFY((test_assign<
             Map<Matrix<Scalar, internal::plain_enum_max(2, PacketSize), internal::plain_enum_max(2, PacketSize)>,
                 AlignedMax, InnerStride<3 * PacketSize> >,
             Matrix<Scalar, internal::plain_enum_max(2, PacketSize), internal::plain_enum_max(2, PacketSize)> >(
         DefaultTraversal, PacketSize > 4 ? InnerUnrolling : CompleteUnrolling)));
     VERIFY((test_assign(Matrix57(), Matrix<Scalar, 5 * MinVSize, 3>() * Matrix<Scalar, 3, 7>(),
                         InnerVectorizedTraversal, InnerUnrolling + CompleteUnrolling)));
 #endif
   }
References Eigen::AlignedMax, Eigen::ColMajor, Eigen::CompleteUnrolling, Eigen::DefaultTraversal, Eigen::DontAlign, EIGEN_MIN_ALIGN_BYTES, EIGEN_UNALIGNED_VECTORIZE, Eigen::InnerUnrolling, Eigen::InnerVectorizedTraversal, int(), Eigen::LinearTraversal, Eigen::LinearVectorizedTraversal, Eigen::NoUnrolling, vectorization_logic_half< Scalar, Enable >::PacketSize, Eigen::internal::plain_enum_max(), row(), Eigen::RowMajor, Eigen::RowMajorBit, Eigen::SliceVectorizedTraversal, test_assign(), test_redux(), and VERIFY.
Member Data Documentation
PacketSize
template<typename Scalar , bool Enable = !internal::is_same< typename internal::unpacket_traits<typename internal::packet_traits<Scalar>::type>::half, typename internal::packet_traits<Scalar>::type>::value> constexpr int vectorization_logic_half< Scalar, Enable >::PacketSize = internal::unpacket_traits<PacketType>::size static constexpr
Referenced by vectorization_logic_half< Scalar, Enable >::run().
The documentation for this struct was generated from the following file:
vectorization_logic.cpp