MercuryDPM: SaveToStl Namespace Reference
SaveToStl Namespace Reference
Functions
def MakeSphere (pos, R, edges_phi, edges_theta)
def SavePebblesStl (filename, pebbles, N_phi, N_theta)
def SaveVoxelGridStl (filename, vox, bbox, span)
def SaveStlSnap (input_mesh, pos, v1, v2, v3, filename)
def SaveStlSequence (OPT, DATA)
Function Documentation
MakeSphere()
def SaveToStl.MakeSphere (pos, R, edges_phi, edges_theta)
 def MakeSphere(pos, R, edges_phi, edges_theta):
     from stl import mesh
     # This function creates an stl model of a sphere
     data = np.zeros((edges_theta - 1) * edges_phi * 2, dtype=mesh.Mesh.dtype)  # Create the data structure for triangles
     x = pos[0]
     y = pos[1]
     z = pos[2]
     k = 0
     for j in range(edges_phi):
         for i in range(edges_theta):
             # v1...v4 - vertices of triangles
             # Triangle 1: v1, v2, v3
             # Triangle 2: v3, v2, v4
             v1 = np.array([x + R * np.sin(np.pi * (i / edges_theta)) * np.cos(2 * np.pi * (j / edges_phi)),
                            y + R * np.sin(np.pi * (i / edges_theta)) * np.sin(2 * np.pi * (j / edges_phi)),
                            z + R * np.cos(np.pi * (i / edges_theta))])
             v2 = np.array([x + R * np.sin(np.pi * ((i + 1) / edges_theta)) * np.cos(2 * np.pi * (j / edges_phi)),
                            y + R * np.sin(np.pi * ((i + 1) / edges_theta)) * np.sin(2 * np.pi * (j / edges_phi)),
                            z + R * np.cos(np.pi * ((i + 1) / edges_theta))])
             v3 = np.array([x + R * np.sin(np.pi * (i / edges_theta)) * np.cos(2 * np.pi * ((j + 1) / edges_phi)),
                            y + R * np.sin(np.pi * (i / edges_theta)) * np.sin(2 * np.pi * ((j + 1) / edges_phi)),
                            z + R * np.cos(np.pi * (i / edges_theta))])
             v4 = np.array([x + R * np.sin(np.pi * ((i + 1) / edges_theta)) * np.cos(2 * np.pi * ((j + 1) / edges_phi)),
                            y + R * np.sin(np.pi * ((i + 1) / edges_theta)) * np.sin(2 * np.pi * ((j + 1) / edges_phi)),
                            z + R * np.cos(np.pi * ((i + 1) / edges_theta))])
             if (not (np.allclose(v1, v3))):
                 data['vectors'][k] = np.array([v1, v2, v3])
                 k += 1
             if (not (np.allclose(v2, v4))):
                 data['vectors'][k] = np.array([v3, v2, v4])
                 k += 1
     return data
Referenced by SavePebblesStl().
SavePebblesStl()
def SaveToStl.SavePebblesStl (filename, pebbles, N_phi, N_theta)
 def SavePebblesStl(filename, pebbles, N_phi, N_theta):
     from stl import mesh
     data = MakeSphere(pebbles[0][:3], pebbles[0][3], N_phi, N_theta)
     for pebble in range(1, len(pebbles)):
         data = np.hstack((data, MakeSphere(pebbles[pebble][:3], pebbles[pebble][3], N_phi, N_theta)))
     your_mesh = mesh.Mesh(data, remove_empty_areas=True)
     your_mesh.save(filename)
     print("stl model saved: " + filename)
     return
References MakeSphere(), and Eigen::internal.print().
Referenced by OutputData.OutputClumpData().
SaveStlSequence()
def SaveToStl.SaveStlSequence (OPT, DATA)
 def SaveStlSequence(OPT, DATA):
     # Load clump sequence
     filename = OPT['clumpSeqDir'] + 'ClumpSeq.txt'
     textfile = open(filename, "r")
     content_list = textfile.readlines()
     sequence = np.zeros([len(content_list), 13])
     for i in range(len(content_list)):
         content_list[i] = content_list[i].replace("\n", "")
         word_list = content_list[i].split(' ')
         for j in range (13):
             sequence[i][j] = float(word_list[j])
     DATA['clumpSequence'] = sequence
     # Save stl sequence
     for i in range(len(sequence)):
         pos = sequence[i][1:4]
         v1 = sequence[i][4:7]
         v2 = sequence[i][7:10]
         v3 = sequence[i][10:13]
         print("pos:", pos, "v1:", v1, "v2:", v2, "v3:", v3)
         SaveStlSnap(DATA['stlMesh'], pos, v1, v2, v3, './Blender/StlSeq/' + 's_' + str(i) + '.stl')
     return OPT, DATA
References Eigen::internal.print(), SaveStlSnap(), oomph::DoubleVectorHelpers.split(), and compute_granudrum_aor.str.
Referenced by MClump.main().
SaveStlSnap()
def SaveToStl.SaveStlSnap (input_mesh, pos, v1, v2, v3, filename)
 def SaveStlSnap(input_mesh, pos, v1, v2, v3, filename):
     print("pos", pos)
     import copy
     ms = copy.deepcopy(input_mesh)
     # Rotate mesh to pd
     e1 = np.array([1,0,0])
     e2 = np.array([0,1,0])
     e3 = np.array([0,0,1])
     Q = np.array([
         [e1@v1, e2@v1, e3@v1],
         [e1@v2, e2@v2, e3@v2],
         [e1@v3, e2@v3, e3@v3]])
     for j in range(len(ms.normals)):
         ms.v0[j]  = Q @ ms.v0[j]
         ms.v1[j]  = Q @ ms.v1[j]
         ms.v2[j]  = Q @ ms.v2[j]
         ms.normals[j]  = Q @ ms.normals[j]
     # Shift Mesh's center of gravity to a specified location
     for j in range(len(ms.normals)):
         ms.v0[j] += pos
         ms.v1[j] += pos
         ms.v2[j] += pos
     ms.save(filename)
     return
References Eigen::internal.print().
Referenced by SaveStlSequence().
SaveVoxelGridStl()
def SaveToStl.SaveVoxelGridStl (filename, vox, bbox, span)
 def SaveVoxelGridStl(filename, vox, bbox, span):
     # A function that saves voxels as an stl
     #   Numbering of vertices v1-v8:
     #        z
     #       |
     #      1----4
     #      |\   |\
     #     |  2----3
     #     5----8  __ y
     #     \    \
     #      6----7
     #      \
     #       x
     N = vox.shape[0]
     from stl import mesh
     data = np.zeros(12 * N ** 3, dtype=mesh.Mesh.dtype)  # Create the data structure for triangles
     l = span / N
     p = 0
     for i in range(N):
         for j in range(N):
             for k in range(N):
                 vox_center = np.array([bbox[0] + l * (1 + 2 * i), bbox[2] + l * (1 + 2 * j), bbox[4] + l * (1 + 2 * k)])
                 v1 = vox_center + l * np.array([-1, -1, 1])
                 v2 = vox_center + l * np.array([1, -1, 1])
                 v3 = vox_center + l * np.array([1, 1, 1])
                 v4 = vox_center + l * np.array([-1, 1, 1])
                 v5 = vox_center + l * np.array([-1, -1, -1])
                 v6 = vox_center + l * np.array([1, -1, -1])
                 v7 = vox_center + l * np.array([1, 1, -1])
                 v8 = vox_center + l * np.array([-1, 1, -1])
                 # Create cube sides
                 if (i == 0 and vox[i, j, k]) or (i > 0 and (vox[i, j, k] and not vox[i - 1, j, k])):
                     data['vectors'][p] = np.array([v1, v4, v5])
                     data['vectors'][p + 1] = np.array([v5, v4, v8])
                     p += 2
                 if (j == 0 and vox[i, j, k]) or (j > 0 and (vox[i, j, k] and not vox[i, j - 1, k])):
                     data['vectors'][p] = np.array([v6, v2, v1])
                     data['vectors'][p + 1] = np.array([v6, v1, v5])
                     p += 2
                 if (k == 0 and vox[i, j, k]) or (k > 0 and (vox[i, j, k] and not vox[i, j, k - 1])):
                     data['vectors'][p] = np.array([v7, v8, v5])
                     data['vectors'][p + 1] = np.array([v7, v5, v6])
                     p += 2
                 if (i == N - 1 and vox[i, j, k]) or (i < N - 1 and (vox[i, j, k] and not vox[i + 1, j, k])):
                     data['vectors'][p] = np.array([v3, v6, v2])
                     data['vectors'][p + 1] = np.array([v3, v7, v6])
                     p += 2
                 if (j == N - 1 and vox[i, j, k]) or (j < N - 1 and (vox[i, j, k] and not vox[i, j + 1, k])):
                     data['vectors'][p] = np.array([v7, v3, v4])
                     data['vectors'][p + 1] = np.array([v7, v4, v8])
                     p += 2
                 if (k == N - 1 and vox[i, j, k]) or (k < N - 1 and (vox[i, j, k] and not vox[i, j, k + 1])):
                     data['vectors'][p] = np.array([v4, v1, v2])
                     data['vectors'][p + 1] = np.array([v4, v2, v3])
                     p += 2
     mesh = mesh.Mesh(data, remove_empty_areas=True)
     mesh.save(filename)
     return
Referenced by OutputData.OutputClumpData().