MercuryDPM: Eigen::internal::dhs_cpack< Scalar, DataMapper, Packet, PacketC, StorageOrder, Conjugate, PanelMode, UseLhs > Struct Template Reference
Eigen::internal::dhs_cpack< Scalar, DataMapper, Packet, PacketC, StorageOrder, Conjugate, PanelMode, UseLhs > Struct Template Reference
#include <MatrixProduct.h>
Public Member Functions
template<bool transpose>
EIGEN_ALWAYS_INLINE void dhs_cblock (PacketBlock< PacketC, 8 > &cblock, PacketBlock< Packet, 4 > &block, Packet16uc permute)
EIGEN_ALWAYS_INLINE void dhs_ccopy (Scalar *blockAt, const DataMapper &lhs2, Index &i, Index &rir, Index &rii, Index depth, const Index vectorSize)
EIGEN_STRONG_INLINE void operator() (std::complex< Scalar > *blockA, const DataMapper &lhs, Index depth, Index rows, Index stride, Index offset)
Member Function Documentation
dhs_cblock()
template<typename Scalar , typename DataMapper , typename Packet , typename PacketC , int StorageOrder, bool Conjugate, bool PanelMode, bool UseLhs> template<bool transpose> EIGEN_ALWAYS_INLINE void Eigen::internal::dhs_cpack< Scalar, DataMapper, Packet, PacketC, StorageOrder, Conjugate, PanelMode, UseLhs >::dhs_cblock (PacketBlock< PacketC, 8 > & cblock, PacketBlock< Packet, 4 > & block, Packet16uc permute) inline
{
     if (transpose) {
       block.packet[0] = vec_perm(cblock.packet[0].v, cblock.packet[1].v, permute);
       block.packet[1] = vec_perm(cblock.packet[2].v, cblock.packet[3].v, permute);
       block.packet[2] = vec_perm(cblock.packet[4].v, cblock.packet[5].v, permute);
       block.packet[3] = vec_perm(cblock.packet[6].v, cblock.packet[7].v, permute);
       Packet4f t0, t1, t2, t3;
 #ifdef EIGEN_VECTORIZE_VSX
       t0 = reinterpret_cast<Packet>(
           vec_mergeh(reinterpret_cast<Packet2ul>(block.packet[0]), reinterpret_cast<Packet2ul>(block.packet[1])));
       t1 = reinterpret_cast<Packet>(
           vec_mergel(reinterpret_cast<Packet2ul>(block.packet[0]), reinterpret_cast<Packet2ul>(block.packet[1])));
       t2 = reinterpret_cast<Packet>(
           vec_mergeh(reinterpret_cast<Packet2ul>(block.packet[2]), reinterpret_cast<Packet2ul>(block.packet[3])));
       t3 = reinterpret_cast<Packet>(
           vec_mergel(reinterpret_cast<Packet2ul>(block.packet[2]), reinterpret_cast<Packet2ul>(block.packet[3])));
 #else
       t0 = reinterpret_cast<Packet>(vec_perm(block.packet[0], block.packet[1], p16uc_TRANSPOSE64_HI));
       t1 = reinterpret_cast<Packet>(vec_perm(block.packet[0], block.packet[1], p16uc_TRANSPOSE64_LO));
       t2 = reinterpret_cast<Packet>(vec_perm(block.packet[2], block.packet[3], p16uc_TRANSPOSE64_HI));
       t3 = reinterpret_cast<Packet>(vec_perm(block.packet[2], block.packet[3], p16uc_TRANSPOSE64_LO));
 #endif
       block.packet[0] = t0;
       block.packet[1] = t1;
       block.packet[2] = t2;
       block.packet[3] = t3;
     } else {
       block.packet[0] = vec_perm(cblock.packet[0].v, cblock.packet[4].v, permute);
       block.packet[1] = vec_perm(cblock.packet[1].v, cblock.packet[5].v, permute);
       block.packet[2] = vec_perm(cblock.packet[2].v, cblock.packet[6].v, permute);
       block.packet[3] = vec_perm(cblock.packet[3].v, cblock.packet[7].v, permute);
     }
   }
References block(), Eigen::internal::p16uc_TRANSPOSE64_HI, Eigen::internal::p16uc_TRANSPOSE64_LO, Eigen::internal::PacketBlock< Packet, N >::packet, and anonymous_namespace{skew_symmetric_matrix3.cpp}::transpose().
dhs_ccopy()
template<typename Scalar , typename DataMapper , typename Packet , typename PacketC , int StorageOrder, bool Conjugate, bool PanelMode, bool UseLhs> EIGEN_ALWAYS_INLINE void Eigen::internal::dhs_cpack< Scalar, DataMapper, Packet, PacketC, StorageOrder, Conjugate, PanelMode, UseLhs >::dhs_ccopy (Scalar * blockAt, const DataMapper & lhs2, Index & i, Index & rir, Index & rii, Index depth, const Index vectorSize) inline
{
     PacketBlock<Packet, 4> blockr, blocki;
     PacketBlock<PacketC, 8> cblock;
     for (; i + vectorSize <= depth; i += vectorSize) {
       if (UseLhs) {
         bload<DataMapper, PacketC, 2, StorageOrder, true, 4>(cblock, lhs2, 0, i);
       } else {
         bload<DataMapper, PacketC, 2, StorageOrder, true, 4>(cblock, lhs2, i, 0);
       }
       if (((StorageOrder == RowMajor) && UseLhs) || (((StorageOrder == ColMajor) && !UseLhs))) {
         dhs_cblock<true>(cblock, blockr, p16uc_GETREAL32b);
         dhs_cblock<true>(cblock, blocki, p16uc_GETIMAG32b);
       } else {
         dhs_cblock<false>(cblock, blockr, p16uc_GETREAL32);
         dhs_cblock<false>(cblock, blocki, p16uc_GETIMAG32);
       }
       if (Conjugate) {
         blocki.packet[0] = -blocki.packet[0];
         blocki.packet[1] = -blocki.packet[1];
         blocki.packet[2] = -blocki.packet[2];
         blocki.packet[3] = -blocki.packet[3];
       }
       storeBlock<Scalar, Packet, 4>(blockAt + rir, blockr);
       storeBlock<Scalar, Packet, 4>(blockAt + rii, blocki);
       rir += 4 * vectorSize;
       rii += 4 * vectorSize;
     }
   }
References Eigen::ColMajor, i, Eigen::internal::p16uc_GETIMAG32, Eigen::internal::p16uc_GETIMAG32b, Eigen::internal::p16uc_GETREAL32, Eigen::internal::p16uc_GETREAL32b, Eigen::internal::PacketBlock< Packet, N >::packet, and Eigen::RowMajor.
Referenced by Eigen::internal::dhs_cpack< double, DataMapper, Packet, PacketC, StorageOrder, Conjugate, PanelMode, true >::operator()(), Eigen::internal::dhs_cpack< double, DataMapper, Packet, PacketC, StorageOrder, Conjugate, PanelMode, false >::operator()(), and Eigen::internal::dhs_cpack< Scalar, DataMapper, Packet, PacketC, StorageOrder, Conjugate, PanelMode, UseLhs >::operator()().
operator()()
template<typename Scalar , typename DataMapper , typename Packet , typename PacketC , int StorageOrder, bool Conjugate, bool PanelMode, bool UseLhs> EIGEN_STRONG_INLINE void Eigen::internal::dhs_cpack< Scalar, DataMapper, Packet, PacketC, StorageOrder, Conjugate, PanelMode, UseLhs >::operator() (std::complex< Scalar > * blockA, const DataMapper & lhs, Index depth, Index rows, Index stride, Index offset) inline
{
     const Index vectorSize = quad_traits<Scalar>::vectorsize;
     const Index vectorDelta = vectorSize * ((PanelMode) ? stride : depth);
     Index rir = ((PanelMode) ? (vectorSize * offset) : 0), rii;
     Scalar* blockAt = reinterpret_cast<Scalar*>(blockA);
     Index j = 0;
     for (; j + vectorSize <= rows; j += vectorSize) {
       const DataMapper lhs2 = UseLhs ? lhs.getSubMapper(j, 0) : lhs.getSubMapper(0, j);
       Index i = 0;
       rii = rir + vectorDelta;
       dhs_ccopy(blockAt, lhs2, i, rir, rii, depth, vectorSize);
       for (; i < depth; i++) {
         PacketBlock<Packet, 1> blockr, blocki;
         PacketBlock<PacketC, 2> cblock;
         if (((StorageOrder == ColMajor) && UseLhs) || (((StorageOrder == RowMajor) && !UseLhs))) {
           if (UseLhs) {
             cblock.packet[0] = lhs2.template loadPacket<PacketC>(0, i);
             cblock.packet[1] = lhs2.template loadPacket<PacketC>(2, i);
           } else {
             cblock.packet[0] = lhs2.template loadPacket<PacketC>(i, 0);
             cblock.packet[1] = lhs2.template loadPacket<PacketC>(i, 2);
           }
         } else {
           if (UseLhs) {
             cblock.packet[0] = pload2(lhs2(0, i), lhs2(1, i));
             cblock.packet[1] = pload2(lhs2(2, i), lhs2(3, i));
           } else {
             cblock.packet[0] = pload2(lhs2(i, 0), lhs2(i, 1));
             cblock.packet[1] = pload2(lhs2(i, 2), lhs2(i, 3));
           }
         }
         blockr.packet[0] = vec_perm(cblock.packet[0].v, cblock.packet[1].v, p16uc_GETREAL32);
         blocki.packet[0] = vec_perm(cblock.packet[0].v, cblock.packet[1].v, p16uc_GETIMAG32);
         if (Conjugate) {
           blocki.packet[0] = -blocki.packet[0];
         }
         pstore<Scalar>(blockAt + rir, blockr.packet[0]);
         pstore<Scalar>(blockAt + rii, blocki.packet[0]);
         rir += vectorSize;
         rii += vectorSize;
       }
       rir += ((PanelMode) ? (vectorSize * (2 * stride - depth)) : vectorDelta);
     }
     if (!UseLhs) {
       if (PanelMode) rir -= (offset * (vectorSize - 1));
       for (; j < rows; j++) {
         const DataMapper lhs2 = lhs.getSubMapper(0, j);
         rii = rir + ((PanelMode) ? stride : depth);
         for (Index i = 0; i < depth; i++) {
           blockAt[rir] = lhs2(i, 0).real();
           if (Conjugate)
             blockAt[rii] = -lhs2(i, 0).imag();
           else
             blockAt[rii] = lhs2(i, 0).imag();
           rir += 1;
           rii += 1;
         }
         rir += ((PanelMode) ? (2 * stride - depth) : depth);
       }
     } else {
       if (j < rows) {
         if (PanelMode) rir += (offset * (rows - j - vectorSize));
         rii = rir + (((PanelMode) ? stride : depth) * (rows - j));
         for (Index i = 0; i < depth; i++) {
           Index k = j;
           for (; k < rows; k++) {
             blockAt[rir] = lhs(k, i).real();
             if (Conjugate)
               blockAt[rii] = -lhs(k, i).imag();
             else
               blockAt[rii] = lhs(k, i).imag();
             rir += 1;
             rii += 1;
           }
         }
       }
     }
   }
References Eigen::ColMajor, Eigen::internal::dhs_cpack< Scalar, DataMapper, Packet, PacketC, StorageOrder, Conjugate, PanelMode, UseLhs >::dhs_ccopy(), i, j, k, Eigen::internal::p16uc_GETIMAG32, Eigen::internal::p16uc_GETREAL32, Eigen::internal::PacketBlock< Packet, N >::packet, Eigen::internal::pload2(), Eigen::RowMajor, and rows.
The documentation for this struct was generated from the following file:
MatrixProduct.h