MercuryDPM: Eigen::internal::Packet2cf Struct Reference
Eigen::internal::Packet2cf Struct Reference
#include <Complex.h>
Public Member Functions
EIGEN_STRONG_INLINE Packet2cf ()
EIGEN_STRONG_INLINE Packet2cf (const Packet4f &a)
EIGEN_STRONG_INLINE Packet2cf pmul (const Packet2cf &a, const Packet2cf &b)
EIGEN_STRONG_INLINE Packet2cf & operator*= (const Packet2cf &b)
EIGEN_STRONG_INLINE Packet2cf operator* (const Packet2cf &b) const
EIGEN_STRONG_INLINE Packet2cf & operator+= (const Packet2cf &b)
EIGEN_STRONG_INLINE Packet2cf operator+ (const Packet2cf &b) const
EIGEN_STRONG_INLINE Packet2cf & operator-= (const Packet2cf &b)
EIGEN_STRONG_INLINE Packet2cf operator- (const Packet2cf &b) const
EIGEN_STRONG_INLINE Packet2cf operator- (void) const
EIGEN_STRONG_INLINE Packet2cf ()
EIGEN_STRONG_INLINE Packet2cf (const __m128 &a)
EIGEN_STRONG_INLINE Packet2cf ()
EIGEN_STRONG_INLINE Packet2cf (const std::complex< float > &a, const std::complex< float > &b)
EIGEN_STRONG_INLINE Packet2cf (const Packet4f &a)
EIGEN_STRONG_INLINE Packet2cf (const Packet2cf &a)
EIGEN_STRONG_INLINE Packet2cf & operator= (const Packet2cf &b)
EIGEN_STRONG_INLINE Packet2cf conjugate (void) const
EIGEN_STRONG_INLINE Packet2cf & operator*= (const Packet2cf &b)
EIGEN_STRONG_INLINE Packet2cf operator* (const Packet2cf &b) const
EIGEN_STRONG_INLINE Packet2cf & operator+= (const Packet2cf &b)
EIGEN_STRONG_INLINE Packet2cf operator+ (const Packet2cf &b) const
EIGEN_STRONG_INLINE Packet2cf & operator-= (const Packet2cf &b)
EIGEN_STRONG_INLINE Packet2cf operator- (const Packet2cf &b) const
EIGEN_STRONG_INLINE Packet2cf operator/ (const Packet2cf &b) const
EIGEN_STRONG_INLINE Packet2cf & operator/= (const Packet2cf &b)
EIGEN_STRONG_INLINE Packet2cf operator- (void) const
EIGEN_STRONG_INLINE Packet2cf ()
EIGEN_STRONG_INLINE Packet2cf (const Packet4f &a)
EIGEN_STRONG_INLINE Packet2cf ()
EIGEN_STRONG_INLINE Packet2cf (const __m128 &a)
EIGEN_STRONG_INLINE Packet2cf ()
EIGEN_STRONG_INLINE Packet2cf (const Packet4f &a)
Public Attributes
Packet4f v
union {
Packet4f v
Packet1cd cd [2]
};
Constructor & Destructor Documentation
Packet2cf() [1/14]
EIGEN_STRONG_INLINE Eigen::internal::Packet2cf::Packet2cf () inline explicit
 {}
Referenced by conjugate(), operator*(), operator*=(), operator+(), operator-(), operator/(), operator/=(), and pmul().
Packet2cf() [2/14]
EIGEN_STRONG_INLINE Eigen::internal::Packet2cf::Packet2cf (const Packet4f & a) inline explicit
 : v(a) {}
Packet2cf() [3/14]
EIGEN_STRONG_INLINE Eigen::internal::Packet2cf::Packet2cf () inline
 {}
Packet2cf() [4/14]
EIGEN_STRONG_INLINE Eigen::internal::Packet2cf::Packet2cf (const __m128 & a) inline explicit
 : v(a) {}
Packet2cf() [5/14]
EIGEN_STRONG_INLINE Eigen::internal::Packet2cf::Packet2cf () inline
 {}
Packet2cf() [6/14]
EIGEN_STRONG_INLINE Eigen::internal::Packet2cf::Packet2cf (const std::complex< float > & a, const std::complex< float > & b) inline explicit
{
     Packet4f t = {std::real(a), std::imag(a), std::real(b), std::imag(b)};
     v = t;
   }
References a, b, imag(), plotPSD::t, and v.
Packet2cf() [7/14]
EIGEN_STRONG_INLINE Eigen::internal::Packet2cf::Packet2cf (const Packet4f & a) inline explicit
 : v(a) {}
Packet2cf() [8/14]
EIGEN_STRONG_INLINE Eigen::internal::Packet2cf::Packet2cf (const Packet2cf & a) inline
 : v(a.v) {}
Packet2cf() [9/14]
EIGEN_STRONG_INLINE Eigen::internal::Packet2cf::Packet2cf () inline
 {}
Packet2cf() [10/14]
EIGEN_STRONG_INLINE Eigen::internal::Packet2cf::Packet2cf (const Packet4f & a) inline explicit
 : v(a) {}
Packet2cf() [11/14]
EIGEN_STRONG_INLINE Eigen::internal::Packet2cf::Packet2cf () inline
 {}
Packet2cf() [12/14]
EIGEN_STRONG_INLINE Eigen::internal::Packet2cf::Packet2cf (const __m128 & a) inline explicit
 : v(a) {}
Packet2cf() [13/14]
EIGEN_STRONG_INLINE Eigen::internal::Packet2cf::Packet2cf () inline
 {}
Packet2cf() [14/14]
EIGEN_STRONG_INLINE Eigen::internal::Packet2cf::Packet2cf (const Packet4f & a) inline explicit
 : v(a) {}
Member Function Documentation
conjugate()
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::Packet2cf::conjugate (void) const inline
{
     return Packet2cf((Packet4f)__builtin_msa_bnegi_d((v2u64)v, 63));
   }
References Packet2cf(), and v.
operator*() [1/2]
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::Packet2cf::operator* (const Packet2cf & b) const inline
 { return Packet2cf(*this) *= b; }
References b, and Packet2cf().
operator*() [2/2]
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::Packet2cf::operator* (const Packet2cf & b) const inline
 { return Packet2cf(*this) *= b; }
References b, and Packet2cf().
operator*=() [1/2]
EIGEN_STRONG_INLINE Packet2cf& Eigen::internal::Packet2cf::operator*= (const Packet2cf & b) inline
{
     v = pmul(Packet2cf(*this), b).v;
     return *this;
   }
References b, Packet2cf(), pmul(), and v.
operator*=() [2/2]
EIGEN_STRONG_INLINE Packet2cf& Eigen::internal::Packet2cf::operator*= (const Packet2cf & b) inline
{
     Packet4f v1, v2;
     // Get the real values of a | a1_re | a1_re | a2_re | a2_re |
     v1 = (Packet4f)__builtin_msa_ilvev_w((v4i32)v, (v4i32)v);
     // Get the imag values of a | a1_im | a1_im | a2_im | a2_im |
     v2 = (Packet4f)__builtin_msa_ilvod_w((v4i32)v, (v4i32)v);
     // Multiply the real a with b
     v1 = pmul(v1, b.v);
     // Multiply the imag a with b
     v2 = pmul(v2, b.v);
     // Conjugate v2
     v2 = Packet2cf(v2).conjugate().v;
     // Swap real/imag elements in v2.
     v2 = (Packet4f)__builtin_msa_shf_w((v4i32)v2, EIGEN_MSA_SHF_I8(1, 0, 3, 2));
     // Add and return the result
     v = padd(v1, v2);
     return *this;
   }
References b, EIGEN_MSA_SHF_I8, Packet2cf(), Eigen::internal::padd(), pmul(), v, v1(), and v2().
operator+() [1/2]
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::Packet2cf::operator+ (const Packet2cf & b) const inline
 { return Packet2cf(*this) += b; }
References b, and Packet2cf().
operator+() [2/2]
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::Packet2cf::operator+ (const Packet2cf & b) const inline
 { return Packet2cf(*this) += b; }
References b, and Packet2cf().
operator+=() [1/2]
EIGEN_STRONG_INLINE Packet2cf& Eigen::internal::Packet2cf::operator+= (const Packet2cf & b) inline
{
     v = padd(v, b.v);
     return *this;
   }
References b, Eigen::internal::padd(), and v.
operator+=() [2/2]
EIGEN_STRONG_INLINE Packet2cf& Eigen::internal::Packet2cf::operator+= (const Packet2cf & b) inline
{
     v = padd(v, b.v);
     return *this;
   }
References b, Eigen::internal::padd(), and v.
operator-() [1/4]
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::Packet2cf::operator- (const Packet2cf & b) const inline
 { return Packet2cf(*this) -= b; }
References b, and Packet2cf().
operator-() [2/4]
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::Packet2cf::operator- (const Packet2cf & b) const inline
 { return Packet2cf(*this) -= b; }
References b, and Packet2cf().
operator-() [3/4]
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::Packet2cf::operator- (void) const inline
 { return Packet2cf(-v); }
References Packet2cf(), and v.
operator-() [4/4]
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::Packet2cf::operator- (void) const inline
 { return Packet2cf(pnegate(v)); }
References Packet2cf(), Eigen::internal::pnegate(), and v.
operator-=() [1/2]
EIGEN_STRONG_INLINE Packet2cf& Eigen::internal::Packet2cf::operator-= (const Packet2cf & b) inline
{
     v = psub(v, b.v);
     return *this;
   }
References b, Eigen::internal::psub(), and v.
operator-=() [2/2]
EIGEN_STRONG_INLINE Packet2cf& Eigen::internal::Packet2cf::operator-= (const Packet2cf & b) inline
{
     v = psub(v, b.v);
     return *this;
   }
References b, Eigen::internal::psub(), and v.
operator/()
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::Packet2cf::operator/ (const Packet2cf & b) const inline
 { return pdiv_complex(Packet2cf(*this), b); }
References b, Packet2cf(), and Eigen::internal::pdiv_complex().
operator/=()
EIGEN_STRONG_INLINE Packet2cf& Eigen::internal::Packet2cf::operator/= (const Packet2cf & b) inline
{
     *this = Packet2cf(*this) / b;
     return *this;
   }
References b, and Packet2cf().
operator=()
EIGEN_STRONG_INLINE Packet2cf& Eigen::internal::Packet2cf::operator= (const Packet2cf & b) inline
{
     v = b.v;
     return *this;
   }
References b, and v.
pmul()
EIGEN_STRONG_INLINE Packet2cf Eigen::internal::Packet2cf::pmul (const Packet2cf & a, const Packet2cf & b) inline
{
     Packet4f v1, v2;
     // Permute and multiply the real parts of a and b
     v1 = vec_perm(a.v, a.v, p16uc_PSET32_WODD);
     // Get the imaginary parts of a
     v2 = vec_perm(a.v, a.v, p16uc_PSET32_WEVEN);
     // multiply a_re * b
     v1 = vec_madd(v1, b.v, p4f_ZERO);
     // multiply a_im * b and get the conjugate result
     v2 = vec_madd(v2, b.v, p4f_ZERO);
     v2 = reinterpret_cast<Packet4f>(pxor(v2, reinterpret_cast<Packet4f>(p4ui_CONJ_XOR)));
     // permute back to a proper order
     v2 = vec_perm(v2, v2, p16uc_COMPLEX32_REV);
     return Packet2cf(padd<Packet4f>(v1, v2));
   }
References a, b, Eigen::internal::p16uc_COMPLEX32_REV, Eigen::internal::p16uc_PSET32_WEVEN, Eigen::internal::p16uc_PSET32_WODD, Eigen::internal::p4ui_CONJ_XOR, Packet2cf(), Eigen::internal::padd< Packet4f >(), Eigen::internal::pxor(), v1(), and v2().
Referenced by operator*=().
Member Data Documentation
union { ... }
cd
Packet1cd Eigen::internal::Packet2cf::cd[2]
v
Packet4f Eigen::internal::Packet2cf::v
Referenced by conjugate(), operator*=(), operator+=(), operator-(), operator-=(), operator=(), Packet2cf(), Eigen::internal::pdiv_complex(), Eigen::internal::pexp_complex(), Eigen::internal::phypot_complex(), pload_complex_full_row(), pload_realimag_combine_row(), Eigen::internal::plog_complex(), Eigen::internal::psqrt_complex(), and Eigen::internal::psign_impl< Packet, std::enable_if_t< NumTraits< typename unpacket_traits< Packet >::type >::IsComplex &&unpacket_traits< Packet >::vectorizable > >::run().
The documentation for this struct was generated from the following file:
AltiVec/Complex.h