MercuryDPM: oomph::BiharmonicEquations< DIM > Class Template Reference
oomph::BiharmonicEquations< DIM > Class Template Reference abstract
Biharmonic Equation Class - contains the equations.
#include <biharmonic_elements.h>
Public Types
typedef void(* SourceFctPt) (const Vector< double > &x, double &u)
source function type definition
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Public Member Functions
BiharmonicEquations ()
Constructor (must initialise the Source_fct_pt to null)
~BiharmonicEquations ()
virtual double u (const unsigned &n, const unsigned &k) const =0
virtual void get_source (const unsigned &ipt, const Vector< double > &x, double &source) const
gets source strength
void fill_in_contribution_to_residuals (Vector< double > &residuals)
wrapper function, adds contribution to residual
void fill_in_contribution_to_jacobian (Vector< double > &residual, DenseMatrix< double > &jacobian)
wrapper function, adds contribution to residual and generic
void output (std::ostream &outfile, const unsigned &nplot)
output with nplot points
void output (std::ostream &outfile)
Output at default number of plot points.
void output (FILE *file_pt)
C-style output.
void output (FILE *file_pt, const unsigned &n_plot)
C_style output at n_plot points.
void output_fluid_velocity (std::ostream &outfile, const unsigned &nplot)
output fluid velocity field
void interpolated_dudx (const Vector< double > &s, Vector< double > &dudx)
output with nplot points
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
output analytic solution
void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
computes the error
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
double interpolated_u_biharmonic (const Vector< double > &s)
calculates interpolated u at s
unsigned self_test ()
self test wrapper
unsigned get_d2_dof ()
return number of second derivate degrees of freedom
unsigned ndof_types () const
void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
SourceFctPt & source_fct_pt ()
Access functions for the source function pointer.
SourceFctPt source_fct_pt () const
Access functions for the source function pointers (const version)
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
virtual void disable_ALE ()
virtual void enable_ALE ()
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual unsigned nvertex_node () const
virtual Node * vertex_node_pt (const unsigned &j) const
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Protected Member Functions
virtual void fill_in_generic_residual_contribution_biharmonic (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned JFLAG)
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Attributes
SourceFctPt Source_fct_pt
Pointer to source function:
Vector< int > Local_eqn
Array to hold local eqn numbers: Local_eqn[n] (=-1 for BC)
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Static Private Attributes
static const unsigned d2_dof [] = {1, 3, 6}
Additional Inherited Members
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
template<unsigned DIM>
class oomph::BiharmonicEquations< DIM >
Biharmonic Equation Class - contains the equations.
Member Typedef Documentation
SourceFctPt
template<unsigned DIM> typedef void(* oomph::BiharmonicEquations< DIM >::SourceFctPt) (const Vector< double > &x, double &u)
source function type definition
Constructor & Destructor Documentation
BiharmonicEquations()
template<unsigned DIM> oomph::BiharmonicEquations< DIM >::BiharmonicEquations () inline
Constructor (must initialise the Source_fct_pt to null)
 : Source_fct_pt(0) {}
~BiharmonicEquations()
template<unsigned DIM> oomph::BiharmonicEquations< DIM >::~BiharmonicEquations () inline
 {};
Member Function Documentation
compute_error() [1/2]
template<unsigned DIM> void oomph::BiharmonicEquations< DIM >::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double & error, double & norm) inline virtual
computes the error
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::BiharmonicElement< DIM >.
     {
       // Initialise
       error = 0.0;
       norm = 0.0;
       // Vector of local coordinates
       Vector<double> s(DIM);
       // Vector for coordintes
       Vector<double> x(DIM);
       // Find out how many nodes there are in the element
       unsigned n_node = this->nnode();
       Shape psi(n_node);
       // Set the value of n_intpt
       unsigned n_intpt = this->integral_pt()->nweight();
       // Tecplot header info
       outfile << this->tecplot_zone_string(3);
       // Tecplot
       // outfile << "ZONE" << std::endl;
       // Exact solution Vector (here a scalar)
       Vector<double> exact_soln(1);
       // Loop over the integration points
       for (unsigned ipt = 0; ipt < n_intpt; ipt++)
       {
         // Assign values of s
         for (unsigned i = 0; i < DIM; i++)
         {
           s[i] = this->integral_pt()->knot(ipt, i);
         }
         // Get the integral weight
         double w = this->integral_pt()->weight(ipt);
         // Get jacobian of mapping
         double J = this->J_eulerian(s);
         // Premultiply the weights and the Jacobian
         double W = w * J;
         // Get x position as Vector
         this->interpolated_x(s, x);
         // Get FE function value
         double u_fe = interpolated_u_biharmonic(s);
         // Get exact solution at this point
         (*exact_soln_pt)(x, exact_soln);
         // Output x,y,...,error
         for (unsigned i = 0; i < DIM; i++)
         {
           outfile << x[i] << " ";
         }
         outfile << exact_soln[0] << " " << fabs(exact_soln[0] - u_fe)
                 << std::endl;
         // Add to error and norm
         norm += exact_soln[0] * exact_soln[0] * W;
         error += (exact_soln[0] - u_fe) * (exact_soln[0] - u_fe) * W;
       }
       this->write_tecplot_zone_footer(outfile, 3);
     }
References DIM, calibrate::error, ProblemParameters::exact_soln(), boost::multiprecision::fabs(), i, oomph::FiniteElement::integral_pt(), oomph::BiharmonicEquations< DIM >::interpolated_u_biharmonic(), oomph::FiniteElement::interpolated_x(), J, oomph::FiniteElement::J_eulerian(), oomph::Integral::knot(), oomph::FiniteElement::nnode(), oomph::Integral::nweight(), s, oomph::FiniteElement::tecplot_zone_string(), w, oomph::QuadTreeNames::W, oomph::Integral::weight(), oomph::FiniteElement::write_tecplot_zone_footer(), and plotDoE::x.
Referenced by oomph::BiharmonicElement< DIM >::compute_error().
compute_error() [2/2]
template<unsigned DIM> void oomph::BiharmonicEquations< DIM >::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, double & error, double & norm) inline virtual
Plot the error when compared against a given time-dependent exact solution \({\bf f}(t,{\bf x}) \). Also calculates the norm of the error and that of the exact solution. Call broken base-class version.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::BiharmonicElement< DIM >.
     {
       FiniteElement::compute_error(outfile, exact_soln_pt, time, error, norm);
     }
References oomph::FiniteElement::compute_error(), and calibrate::error.
fill_in_contribution_to_jacobian()
template<unsigned DIM> void oomph::BiharmonicEquations< DIM >::fill_in_contribution_to_jacobian (Vector< double > & residual, DenseMatrix< double > & jacobian) inline virtual
wrapper function, adds contribution to residual and generic
Reimplemented from oomph::GeneralisedElement.
     {
       // call generic routine with flag set to 1
       fill_in_generic_residual_contribution_biharmonic(residual, jacobian, 1);
     }
References oomph::BiharmonicEquations< DIM >::fill_in_generic_residual_contribution_biharmonic().
fill_in_contribution_to_residuals()
template<unsigned DIM> void oomph::BiharmonicEquations< DIM >::fill_in_contribution_to_residuals (Vector< double > & residuals) inline virtual
wrapper function, adds contribution to residual
Reimplemented from oomph::GeneralisedElement.
     {
       // create a dummy matrix
       DenseDoubleMatrix dummy(1);
       // call the generic residuals functions with flag set to zero
       fill_in_generic_residual_contribution_biharmonic(residuals, dummy, 0);
     }
References oomph::BiharmonicEquations< DIM >::fill_in_generic_residual_contribution_biharmonic().
fill_in_generic_residual_contribution_biharmonic()
template<unsigned DIM> void oomph::BiharmonicEquations< DIM >::fill_in_generic_residual_contribution_biharmonic (Vector< double > & residuals, DenseMatrix< double > & jacobian, unsigned JFLAG) protected virtual
Compute element residual Vector only (if JFLAG=and/or element Jacobian matrix
   {
     // Find out how many nodes there are
     unsigned n_node = this->nnode();
     // Find out how many values there
     unsigned n_value = this->node_pt(0)->nvalue();
     // Find out how many degrees of freedom are associated with 2nd derivative
     unsigned d2_dof = this->get_d2_dof();
     // set up memory for shape and test functions
     Shape psi(n_node, n_value);
     DShape dpsidx(n_node, n_value, DIM);
     DShape d2psidx(n_node, n_value, d2_dof);
     // Shape psi(n_node,n_value);
     DShape dpsids(n_node, n_value, DIM);
     DShape d2psids(n_node, n_value, d2_dof);
     // storage of single local coordinate
     Vector<double> s(DIM);
     // number of integration points
     unsigned n_intpt = this->integral_pt()->nweight();
     // loop over integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // set local coordinates to be intergration scheme knot
       for (unsigned i = 0; i < DIM; i++)
         s[i] = this->integral_pt()->knot(ipt, i);
       // find weight at knot
       double w = this->integral_pt()->weight(ipt);
       // find shape fn and derivate fns at knot point,
       // and Jacobian of local to global mapping
       double J = this->d2shape_eulerian(s, psi, dpsidx, d2psidx);
       this->d2shape_local(s, psi, dpsids, d2psids);
       // premultiply weight by jacobian
       double W = w * J;
       // initialise storage for d2u_interpolated
       Vector<double> d2u_interpolated(DIM);
       for (unsigned i = 0; i < DIM; i++)
       {
         d2u_interpolated[i] = 0.0;
       }
       // loop over nodes, degrees of freedom, and dimension to calculate
       // interpolated_d2u
       for (unsigned n = 0; n < n_node; n++)
       {
         for (unsigned k = 0; k < n_value; k++)
         {
           for (unsigned d = 0; d < DIM; d++)
           {
             d2u_interpolated[d] +=
               this->node_pt(n)->value(k) * d2psidx(n, k, d);
           }
         }
       }
       // create vector for interpolated position and calculate
       Vector<double> interpolated_position(DIM);
       this->interpolated_x(s, interpolated_position);
       // evaluate source function at knot position
       double source = 0.0;
       get_source(ipt, interpolated_position, source);
       // loop over nodes
       for (unsigned n1 = 0; n1 < n_node; n1++)
       {
         // loop over types of degrees of freedom
         for (unsigned k1 = 0; k1 < n_value; k1++)
         {
           // determine the local equation number
           int local_eqn_number = this->nodal_local_eqn(n1, k1);
           // if local equation number equal to -1 then its a boundary
           // node(pinned)
           if (local_eqn_number >= 0)
           {
             // add source contribution to residual
             residuals[local_eqn_number] -= source * psi(n1, k1) * W;
             // loop over dimension of d2u interpolated
             for (unsigned d1 = 0; d1 < DIM; d1++)
             {
               // loop over derivatives of d2psidx
               for (unsigned d2 = 0; d2 < DIM; d2++)
               {
                 // add residual contribution
                 residuals[local_eqn_number] +=
                   d2u_interpolated[d1] * d2psidx(n1, k1, d2) * W;
               }
               // calculate the jacobian
               if (JFLAG)
               {
                 // loop over nodes
                 for (unsigned n2 = 0; n2 < n_node; n2++)
                 {
                   // loop over types of degrees of freedom
                   for (unsigned k2 = 0; k2 < n_value; k2++)
                   {
                     // get local dof, -if -1 then node pinned
                     int local_dof_number = this->nodal_local_eqn(n2, k2);
                     // if local dof # = -1, then its pinned
                     if (local_dof_number >= 0)
                     {
                       // loop over derivatives
                       for (unsigned d2 = 0; d2 < DIM; d2++)
                       {
                         // add contribution to jacobian
                         jacobian(local_eqn_number, local_dof_number) +=
                           d2psidx(n1, k1, d1) * d2psidx(n2, k2, d2) * W;
                       }
                     }
                   }
                 }
               }
             }
           }
         }
       }
     }
   }
References DIM, TanhSolnForPoisson::get_source(), i, J, k, n, s, TestProblem::source(), w, and oomph::QuadTreeNames::W.
Referenced by oomph::BiharmonicEquations< DIM >::fill_in_contribution_to_jacobian(), and oomph::BiharmonicEquations< DIM >::fill_in_contribution_to_residuals().
get_d2_dof()
template<unsigned DIM> unsigned oomph::BiharmonicEquations< DIM >::get_d2_dof () inline
return number of second derivate degrees of freedom
     {
       return d2_dof[DIM - 1];
     }
References oomph::BiharmonicEquations< DIM >::d2_dof, and DIM.
get_dof_numbers_for_unknowns()
template<unsigned DIM> void oomph::BiharmonicEquations< DIM >::get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> & dof_lookup_list) const inline virtual
Create a list of pairs for all unknowns in this element, so that the first entry in each pair contains the global equation number of the unknown, while the second one contains the number of the "DOF types" that this unknown is associated with. (Function can obviously only be called if the equation numbering scheme has been set up.) (for block preconditioning)
Reimplemented from oomph::GeneralisedElement.
     {
       // number of nodes
       int n_node = this->nnode();
       // number of degrees of freedom at each node
       int n_value = this->node_pt(0)->nvalue();
       // temporary pair (used to store dof lookup prior to being added to list
       std::pair<unsigned long, unsigned> dof_lookup;
       // loop over the nodes
       for (int n = 0; n < n_node; n++)
       {
         // loop over the degree of freedom
         for (int k = 0; k < n_value; k++)
         {
           // determine local eqn number
           int local_eqn_number = this->nodal_local_eqn(n, k);
           // if local equation number is less than zero then nodal dof pinned
           // then ignore
           if (local_eqn_number >= 0)
           {
             // store dof lookup in temporary pair
             dof_lookup.first = this->eqn_number(local_eqn_number);
             dof_lookup.second = k;
             dof_lookup_list.push_front(dof_lookup);
             // add to list
           }
         }
       }
     }
References oomph::GeneralisedElement::eqn_number(), k, oomph::GeneralisedElement::local_eqn_number(), n, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_local_eqn(), oomph::FiniteElement::node_pt(), and oomph::Data::nvalue().
get_source()
template<unsigned DIM> virtual void oomph::BiharmonicEquations< DIM >::get_source (const unsigned & ipt, const Vector< double > & x, double & source) const inline virtual
gets source strength
     {
       // if source function is not provided, i.e. zero, then return zero
       if (Source_fct_pt == 0)
       {
         source = 0.0;
       }
       // else get source strength
       else
       {
         (*Source_fct_pt)(x, source);
       }
     }
References TestProblem::source(), oomph::BiharmonicEquations< DIM >::Source_fct_pt, and plotDoE::x.
interpolated_dudx()
template<unsigned DIM> void oomph::BiharmonicEquations< DIM >::interpolated_dudx (const Vector< double > & s, Vector< double > & dudx) inline
output with nplot points
     {
       // Find out how many nodes there are
       unsigned n_node = this->nnode();
       // Find out how many values there
       unsigned n_value = this->node_pt(0)->nvalue();
       // set up memory for shape functions
       Shape psi(n_node, n_value);
       DShape dpsidx(n_node, n_value, DIM);
       // evaluate dpsidx at local coordinate s
       dshape_eulerian(s, psi, dpsidx);
       // initialise storage for d2u_interpolated
       dudx[0] = 0.0;
       dudx[1] = 0.0;
       // loop over nodes, degrees of freedom, and dimension to calculate
       // interpolated_d2u
       for (unsigned n = 0; n < n_node; n++)
       {
         for (unsigned k = 0; k < n_value; k++)
         {
           for (unsigned d = 0; d < DIM; d++)
           {
             dudx[d] += this->node_pt(n)->value(k) * dpsidx(n, k, d);
           }
         }
       }
     }
References DIM, oomph::FiniteElement::dshape_eulerian(), k, n, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::Data::nvalue(), s, and oomph::Node::value().
Referenced by oomph::BiharmonicEquations< DIM >::output_fluid_velocity().
interpolated_u_biharmonic()
template<unsigned DIM> double oomph::BiharmonicEquations< DIM >::interpolated_u_biharmonic (const Vector< double > & s) inline
calculates interpolated u at s
     {
       // initialise storage for u_interpolated
       double uu = 0;
       // number of nodes
       unsigned n_node = this->nnode();
       // number of degrees of freedom per node
       unsigned n_value = this->node_pt(0)->nvalue();
       // set up memory for shape functions
       Shape psi(n_node, n_value);
       // find shape fn at position s
       this->shape(s, psi);
       // calculate interpolated u
       for (unsigned n = 0; n < n_node; n++)
       {
         for (unsigned k = 0; k < n_value; k++)
         {
           uu += u(n, k) * psi(n, k);
         }
       }
       // return interpolated_u
       return uu;
     }
References k, n, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::Data::nvalue(), oomph::FiniteElement::shape(), and oomph::BiharmonicEquations< DIM >::u().
Referenced by oomph::BiharmonicEquations< DIM >::compute_error(), and oomph::BiharmonicEquations< DIM >::output().
ndof_types()
template<unsigned DIM> unsigned oomph::BiharmonicEquations< DIM >::ndof_types () const inline virtual
The number of "DOF types" that degrees of freedom in this element are sub-divided into (for block preconditioning)
Reimplemented from oomph::GeneralisedElement.
     {
       return this->required_nvalue(1);
     }
References oomph::FiniteElement::required_nvalue().
output() [1/4]
template<unsigned DIM> void oomph::BiharmonicEquations< DIM >::output (FILE * file_pt) inline virtual
C-style output.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::BiharmonicElement< DIM >.
     {
       FiniteElement::output(file_pt);
     }
References oomph::FiniteElement::output().
output() [2/4]
template<unsigned DIM> void oomph::BiharmonicEquations< DIM >::output (FILE * file_pt, const unsigned & n_plot) inline virtual
C_style output at n_plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::BiharmonicElement< DIM >.
     {
       FiniteElement::output(file_pt, n_plot);
     }
References oomph::FiniteElement::output().
output() [3/4]
template<unsigned DIM> void oomph::BiharmonicEquations< DIM >::output (std::ostream & outfile) inline virtual
Output at default number of plot points.
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::BiharmonicElement< DIM >.
     {
       FiniteElement::output(outfile);
     }
References oomph::FiniteElement::output().
output() [4/4]
template<unsigned DIM> void oomph::BiharmonicEquations< DIM >::output (std::ostream & outfile, const unsigned & nplot) inline virtual
output with nplot points
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::BiharmonicElement< DIM >.
     {
       // Vector of local coordinates
       Vector<double> s(DIM);
       // Tecplot header info
       outfile << this->tecplot_zone_string(nplot);
       // Loop over plot points
       unsigned num_plot_points = this->nplot_points(nplot);
       for (unsigned iplot = 0; iplot < num_plot_points; iplot++)
       {
         // Get local coordinates of plot point
         this->get_s_plot(iplot, nplot, s);
         for (unsigned i = 0; i < DIM; i++)
         {
           outfile << this->interpolated_x(s, i) << " ";
         }
         outfile << interpolated_u_biharmonic(s) << std::endl;
       }
       // Write tecplot footer (e.g. FE connectivity lists)
       this->write_tecplot_zone_footer(outfile, nplot);
     }
References DIM, oomph::FiniteElement::get_s_plot(), i, oomph::BiharmonicEquations< DIM >::interpolated_u_biharmonic(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
Referenced by oomph::BiharmonicElement< DIM >::output().
output_fct() [1/2]
template<unsigned DIM> void oomph::BiharmonicEquations< DIM >::output_fct (std::ostream & outfile, const unsigned & nplot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) inline virtual
Output exact solution specified via function pointer at a given time and at a given number of plot points. Function prints as many components as are returned in solution Vector. Implement broken FiniteElement base class version
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::BiharmonicElement< DIM >.
     {
       FiniteElement::output_fct(outfile, nplot, time, exact_soln_pt);
     }
References oomph::FiniteElement::output_fct().
output_fct() [2/2]
template<unsigned DIM> void oomph::BiharmonicEquations< DIM >::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) inline virtual
output analytic solution
Reimplemented from oomph::FiniteElement.
Reimplemented in oomph::BiharmonicElement< DIM >.
     {
       // Vector of local coordinates
       Vector<double> s(DIM);
       // Vector for coordintes
       Vector<double> x(DIM);
       // Tecplot header info
       outfile << this->tecplot_zone_string(nplot);
       // Exact solution Vector (here a scalar)
       Vector<double> exact_soln(1);
       // Loop over plot points
       unsigned num_plot_points = this->nplot_points(nplot);
       for (unsigned iplot = 0; iplot < num_plot_points; iplot++)
       {
         // Get local coordinates of plot point
         this->get_s_plot(iplot, nplot, s);
         // Get x position as Vector
         this->interpolated_x(s, x);
         // Get exact solution at this point
         (*exact_soln_pt)(x, exact_soln);
         // Output x,y,...,u_exact
         for (unsigned i = 0; i < DIM; i++)
         {
           outfile << x[i] << " ";
         }
         outfile << exact_soln[0] << std::endl;
       }
       // Write tecplot footer (e.g. FE connectivity lists)
       this->write_tecplot_zone_footer(outfile, nplot);
     }
References DIM, ProblemParameters::exact_soln(), oomph::FiniteElement::get_s_plot(), i, oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), oomph::FiniteElement::write_tecplot_zone_footer(), and plotDoE::x.
Referenced by oomph::BiharmonicElement< DIM >::output_fct().
output_fluid_velocity()
template<unsigned DIM> void oomph::BiharmonicEquations< DIM >::output_fluid_velocity (std::ostream & outfile, const unsigned & nplot) inline
output fluid velocity field
     {
       // Vector of local coordinates
       Vector<double> s(DIM);
       // Tecplot header info
       outfile << this->tecplot_zone_string(nplot);
       // Loop over plot points
       unsigned num_plot_points = this->nplot_points(nplot);
       for (unsigned iplot = 0; iplot < num_plot_points; iplot++)
       {
         // Get local coordinates of plot point
         this->get_s_plot(iplot, nplot, s);
         for (unsigned i = 0; i < DIM; i++)
         {
           outfile << this->interpolated_x(s, i) << " ";
         }
         Vector<double> dudx(2, 0.0);
         interpolated_dudx(s, dudx);
         outfile << dudx[1] << "  " << -dudx[0] << std::endl;
       }
       // Write tecplot footer (e.g. FE connectivity lists)
       this->write_tecplot_zone_footer(outfile, nplot);
     }
References DIM, oomph::FiniteElement::get_s_plot(), i, oomph::BiharmonicEquations< DIM >::interpolated_dudx(), oomph::FiniteElement::interpolated_x(), oomph::FiniteElement::nplot_points(), s, oomph::FiniteElement::tecplot_zone_string(), and oomph::FiniteElement::write_tecplot_zone_footer().
Referenced by oomph::BiharmonicFluidProblem< DIM >::doc_solution().
self_test()
template<unsigned DIM> unsigned oomph::BiharmonicEquations< DIM >::self_test () inline virtual
self test wrapper
Reimplemented from oomph::FiniteElement.
     {
       bool passed = true;
       // Check lower-level stuff
       if (FiniteElement::self_test() != 0)
       {
         passed = false;
       }
       // Return verdict
       if (passed)
       {
         return 0;
       }
       else
       {
         return 1;
       }
     }
References oomph::FiniteElement::self_test().
source_fct_pt() [1/2]
template<unsigned DIM> SourceFctPt& oomph::BiharmonicEquations< DIM >::source_fct_pt () inline
Access functions for the source function pointer.
     {
       return Source_fct_pt;
     }
References oomph::BiharmonicEquations< DIM >::Source_fct_pt.
Referenced by oomph::BiharmonicProblem< DIM >::set_source_function().
source_fct_pt() [2/2]
template<unsigned DIM> SourceFctPt oomph::BiharmonicEquations< DIM >::source_fct_pt () const inline
Access functions for the source function pointers (const version)
     {
       return Source_fct_pt;
     }
References oomph::BiharmonicEquations< DIM >::Source_fct_pt.
u()
template<unsigned DIM> virtual double oomph::BiharmonicEquations< DIM >::u (const unsigned & n, const unsigned & k) const pure virtual
Access function: Nodal function value at local node n Uses suitably interpolated value for hanging nodes.
Implemented in oomph::BiharmonicElement< DIM >.
Referenced by oomph::BiharmonicEquations< DIM >::interpolated_u_biharmonic().
Member Data Documentation
d2_dof
template<unsigned DIM> const unsigned oomph::BiharmonicEquations< DIM >::d2_dof = {1, 3, 6} static private
Referenced by oomph::BiharmonicEquations< DIM >::get_d2_dof().
Local_eqn
template<unsigned DIM> Vector<int> oomph::BiharmonicEquations< DIM >::Local_eqn protected
Array to hold local eqn numbers: Local_eqn[n] (=-1 for BC)
Source_fct_pt
template<unsigned DIM> SourceFctPt oomph::BiharmonicEquations< DIM >::Source_fct_pt protected
Pointer to source function:
Referenced by oomph::BiharmonicEquations< DIM >::get_source(), and oomph::BiharmonicEquations< DIM >::source_fct_pt().
The documentation for this class was generated from the following files:
biharmonic_elements.h
biharmonic_elements.cc