MercuryDPM: Eigen::internal::imklfft Namespace Reference
Eigen::internal::imklfft Namespace Reference
Classes
struct plan
struct plan< float >
struct plan< double >
struct imklfft_impl
Functions
MKL_Complex16 * complex_cast (const std::complex< double > *p)
MKL_Complex8 * complex_cast (const std::complex< float > *p)
void configure_descriptor (std::shared_ptr< DFTI_DESCRIPTOR > &handl, enum DFTI_CONFIG_VALUE precision, enum DFTI_CONFIG_VALUE forward_domain, MKL_LONG dimension, MKL_LONG *sizes)
Function Documentation
complex_cast() [1/2]
MKL_Complex16* Eigen::internal::imklfft::complex_cast (const std::complex< double > * p) inline
{
   return const_cast<MKL_Complex16*>(reinterpret_cast<const MKL_Complex16*>(p));
 }
References p.
Referenced by Eigen::internal::imklfft::imklfft_impl< Scalar_ >::fwd(), Eigen::internal::imklfft::imklfft_impl< Scalar_ >::fwd2(), Eigen::internal::imklfft::imklfft_impl< Scalar_ >::inv(), and Eigen::internal::imklfft::imklfft_impl< Scalar_ >::inv2().
complex_cast() [2/2]
MKL_Complex8* Eigen::internal::imklfft::complex_cast (const std::complex< float > * p) inline
{
   return const_cast<MKL_Complex8*>(reinterpret_cast<const MKL_Complex8*>(p));
 }
References p.
configure_descriptor()
void Eigen::internal::imklfft::configure_descriptor (std::shared_ptr< DFTI_DESCRIPTOR > & handl, enum DFTI_CONFIG_VALUE precision, enum DFTI_CONFIG_VALUE forward_domain, MKL_LONG dimension, MKL_LONG * sizes) inline
{
   eigen_assert(dimension == 1 || dimension == 2 && "Transformation dimension must be less than 3.");
   DFTI_DESCRIPTOR_HANDLE res = nullptr;
   if (dimension == 1) {
     RUN_OR_ASSERT(DftiCreateDescriptor(&res, precision, forward_domain, dimension, *sizes),
                   "DftiCreateDescriptor failed.")
     handl.reset(res, [](DFTI_DESCRIPTOR_HANDLE handle) { DftiFreeDescriptor(&handle); });
     if (forward_domain == DFTI_REAL) {
       // Set CCE storage
       RUN_OR_ASSERT(DftiSetValue(handl.get(), DFTI_CONJUGATE_EVEN_STORAGE, DFTI_COMPLEX_COMPLEX),
                     "DftiSetValue failed.")
     }
   } else {
     RUN_OR_ASSERT(DftiCreateDescriptor(&res, precision, DFTI_COMPLEX, dimension, sizes), "DftiCreateDescriptor failed.")
     handl.reset(res, [](DFTI_DESCRIPTOR_HANDLE handle) { DftiFreeDescriptor(&handle); });
   }
   RUN_OR_ASSERT(DftiSetValue(handl.get(), DFTI_PLACEMENT, DFTI_NOT_INPLACE), "DftiSetValue failed.")
   RUN_OR_ASSERT(DftiCommitDescriptor(handl.get()), "DftiCommitDescriptor failed.")
 }
References eigen_assert, res, RUN_OR_ASSERT, and sizes.
Referenced by Eigen::internal::imklfft::plan< float >::forward(), Eigen::internal::imklfft::plan< double >::forward(), Eigen::internal::imklfft::plan< float >::forward2(), Eigen::internal::imklfft::plan< double >::forward2(), Eigen::internal::imklfft::plan< float >::inverse(), Eigen::internal::imklfft::plan< double >::inverse(), Eigen::internal::imklfft::plan< float >::inverse2(), and Eigen::internal::imklfft::plan< double >::inverse2().