MercuryDPM: Eigen::internal::binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, IndexBased, IndexBased > Struct Template Reference
Eigen::internal::binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, IndexBased, IndexBased > Struct Template Reference
#include <CoreEvaluators.h>
Classes
struct Data
Public Types
enum {
CoeffReadCost , LhsFlags = evaluator<Lhs>::Flags , RhsFlags = evaluator<Rhs>::Flags , SameType = is_same<typename Lhs::Scalar, typename Rhs::Scalar>::value ,
StorageOrdersAgree = (int(LhsFlags) & RowMajorBit) == (int(RhsFlags) & RowMajorBit) , Flags0 , Flags = (Flags0 & ~RowMajorBit) | (LhsFlags & RowMajorBit) , Alignment = plain_enum_min(evaluator<Lhs>::Alignment, evaluator<Rhs>::Alignment)
}
typedef CwiseBinaryOp< BinaryOp, Lhs, Rhs > XprType
typedef XprType::CoeffReturnType CoeffReturnType
Public Types inherited from Eigen::internal::evaluator_base< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >
enum
typedef traits< CwiseBinaryOp< BinaryOp, Lhs, Rhs > > ExpressionTraits
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE binary_evaluator (const XprType &xpr)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
template<int LoadMode, typename PacketType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType packet (Index row, Index col) const
template<int LoadMode, typename PacketType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType packet (Index index) const
Public Member Functions inherited from Eigen::internal::evaluator_base< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE evaluator_base ()=default
Protected Attributes
Data m_d
Member Typedef Documentation
CoeffReturnType
template<typename BinaryOp , typename Lhs , typename Rhs > typedef XprType::CoeffReturnType Eigen::internal::binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, IndexBased, IndexBased >::CoeffReturnType
XprType
template<typename BinaryOp , typename Lhs , typename Rhs > typedef CwiseBinaryOp<BinaryOp, Lhs, Rhs> Eigen::internal::binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, IndexBased, IndexBased >::XprType
Member Enumeration Documentation
anonymous enum
template<typename BinaryOp , typename Lhs , typename Rhs > anonymous enum
Enumerator
CoeffReadCost
LhsFlags
RhsFlags
SameType
StorageOrdersAgree
Flags0
Flags
Alignment
        {
     CoeffReadCost =
         int(evaluator<Lhs>::CoeffReadCost) + int(evaluator<Rhs>::CoeffReadCost) + int(functor_traits<BinaryOp>::Cost),
     LhsFlags = evaluator<Lhs>::Flags,
     RhsFlags = evaluator<Rhs>::Flags,
     SameType = is_same<typename Lhs::Scalar, typename Rhs::Scalar>::value,
     StorageOrdersAgree = (int(LhsFlags) & RowMajorBit) == (int(RhsFlags) & RowMajorBit),
     Flags0 = (int(LhsFlags) | int(RhsFlags)) &
              (HereditaryBits |
               (int(LhsFlags) & int(RhsFlags) &
                ((StorageOrdersAgree ? LinearAccessBit : 0) |
                 (functor_traits<BinaryOp>::PacketAccess && StorageOrdersAgree && SameType ? PacketAccessBit : 0)))),
     Flags = (Flags0 & ~RowMajorBit) | (LhsFlags & RowMajorBit),
     Alignment = plain_enum_min(evaluator<Lhs>::Alignment, evaluator<Rhs>::Alignment)
   };
Constructor & Destructor Documentation
binary_evaluator()
template<typename BinaryOp , typename Lhs , typename Rhs > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::internal::binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, IndexBased, IndexBased >::binary_evaluator (const XprType & xpr) inline explicit
                                                                                       : m_d(xpr) {
     EIGEN_INTERNAL_CHECK_COST_VALUE(functor_traits<BinaryOp>::Cost);
     EIGEN_INTERNAL_CHECK_COST_VALUE(CoeffReadCost);
   }
References EIGEN_INTERNAL_CHECK_COST_VALUE.
Member Function Documentation
coeff() [1/2]
template<typename BinaryOp , typename Lhs , typename Rhs > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, IndexBased, IndexBased >::coeff (Index index) const inline
{
     return m_d.func()(m_d.lhsImpl.coeff(index), m_d.rhsImpl.coeff(index));
   }
coeff() [2/2]
template<typename BinaryOp , typename Lhs , typename Rhs > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, IndexBased, IndexBased >::coeff (Index row, Index col) const inline
{
     return m_d.func()(m_d.lhsImpl.coeff(row, col), m_d.rhsImpl.coeff(row, col));
   }
References col(), and row().
packet() [1/2]
template<typename BinaryOp , typename Lhs , typename Rhs > template<int LoadMode, typename PacketType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType Eigen::internal::binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, IndexBased, IndexBased >::packet (Index index) const inline
{
     return m_d.func().packetOp(m_d.lhsImpl.template packet<LoadMode, PacketType>(index),
                                m_d.rhsImpl.template packet<LoadMode, PacketType>(index));
   }
packet() [2/2]
template<typename BinaryOp , typename Lhs , typename Rhs > template<int LoadMode, typename PacketType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType Eigen::internal::binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, IndexBased, IndexBased >::packet (Index row, Index col) const inline
{
     return m_d.func().packetOp(m_d.lhsImpl.template packet<LoadMode, PacketType>(row, col),
                                m_d.rhsImpl.template packet<LoadMode, PacketType>(row, col));
   }
References col(), and row().
Member Data Documentation
m_d
template<typename BinaryOp , typename Lhs , typename Rhs > Data Eigen::internal::binary_evaluator< CwiseBinaryOp< BinaryOp, Lhs, Rhs >, IndexBased, IndexBased >::m_d protected
The documentation for this struct was generated from the following file:
CoreEvaluators.h