MercuryDPM: Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::Stack Struct Reference
Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::Stack Struct Reference
#include <SimplicialCholesky_impl.h>
Public Member Functions
Stack (StorageIndex *data, StorageIndex size, StorageIndex maxSize)
bool empty () const
Index size () const
StorageIndex back () const
void push (const StorageIndex &value)
void pop ()
Public Attributes
StorageIndex * m_data
Index m_size
const Index m_maxSize
Constructor & Destructor Documentation
Stack()
template<typename Scalar , typename StorageIndex > Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::Stack::Stack (StorageIndex * data, StorageIndex size, StorageIndex maxSize) inline
         : m_data(data), m_size(size), m_maxSize(maxSize) {
       eigen_assert(size >= 0);
       eigen_assert(maxSize >= size);
     }
References eigen_assert, and Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::Stack::size().
Member Function Documentation
back()
template<typename Scalar , typename StorageIndex > StorageIndex Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::Stack::back () const inline
{
       eigen_assert(m_size > 0);
       return m_data[m_size - 1];
     }
References eigen_assert, Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::Stack::m_data, and Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::Stack::m_size.
Referenced by Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::calc_post().
empty()
template<typename Scalar , typename StorageIndex > bool Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::Stack::empty () const inline
 { return m_size == 0; }
References Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::Stack::m_size.
Referenced by Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::calc_post().
pop()
template<typename Scalar , typename StorageIndex > void Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::Stack::pop () inline
                {
       eigen_assert(m_size > 0);
       m_size--;
     }
References eigen_assert, and Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::Stack::m_size.
Referenced by Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::calc_post().
push()
template<typename Scalar , typename StorageIndex > void Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::Stack::push (const StorageIndex & value) inline
{
 #ifndef EIGEN_NO_DEBUG
       eigen_assert(m_size < m_maxSize);
 #endif
       m_data[m_size] = value;
       m_size++;
     }
References eigen_assert, Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::Stack::m_data, Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::Stack::m_maxSize, Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::Stack::m_size, and Eigen::value.
Referenced by Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::calc_post().
size()
template<typename Scalar , typename StorageIndex > Index Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::Stack::size () const inline
 { return m_size; }
References Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::Stack::m_size.
Referenced by Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::calc_post(), and Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::Stack::Stack().
Member Data Documentation
m_data
template<typename Scalar , typename StorageIndex > StorageIndex* Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::Stack::m_data
Referenced by Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::Stack::back(), and Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::Stack::push().
m_maxSize
template<typename Scalar , typename StorageIndex > const Index Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::Stack::m_maxSize
Referenced by Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::Stack::push().
m_size
template<typename Scalar , typename StorageIndex > Index Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::Stack::m_size
Referenced by Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::Stack::back(), Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::Stack::empty(), Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::Stack::pop(), Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::Stack::push(), and Eigen::internal::simpl_chol_helper< Scalar, StorageIndex >::Stack::size().
The documentation for this struct was generated from the following file:
SimplicialCholesky_impl.h