MercuryDPM: Eigen::internal::visitor_impl< Visitor, Derived, Dynamic, true, true, ShortCircuitEvaluation > Struct Template Reference
Eigen::internal::visitor_impl< Visitor, Derived, Dynamic, true, true, ShortCircuitEvaluation > Struct Template Reference
#include <Visitor.h>
Public Types
using Scalar = typename Derived::Scalar
using Packet = typename packet_traits< Scalar >::type
using short_circuit = short_circuit_eval_impl< Visitor, ShortCircuitEvaluation >
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void run (const Derived &mat, Visitor &visitor)
Static Public Attributes
static constexpr int PacketSize = packet_traits<Scalar>::size
Member Typedef Documentation
Packet
template<typename Visitor , typename Derived , bool ShortCircuitEvaluation> using Eigen::internal::visitor_impl< Visitor, Derived, Dynamic, true, true, ShortCircuitEvaluation >::Packet = typename packet_traits<Scalar>::type
Scalar
template<typename Visitor , typename Derived , bool ShortCircuitEvaluation> using Eigen::internal::visitor_impl< Visitor, Derived, Dynamic, true, true, ShortCircuitEvaluation >::Scalar = typename Derived::Scalar
short_circuit
template<typename Visitor , typename Derived , bool ShortCircuitEvaluation> using Eigen::internal::visitor_impl< Visitor, Derived, Dynamic, true, true, ShortCircuitEvaluation >::short_circuit = short_circuit_eval_impl<Visitor, ShortCircuitEvaluation>
Member Function Documentation
run()
template<typename Visitor , typename Derived , bool ShortCircuitEvaluation> static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::visitor_impl< Visitor, Derived, Dynamic, true, true, ShortCircuitEvaluation >::run (const Derived & mat, Visitor & visitor) inline static
{
     const Index size = mat.size();
     if (size == 0) return;
     Index k = 0;
     if (size < PacketSize) {
       visitor.init(mat.coeff(0), 0);
       k = 1;
     } else {
       Packet p = mat.template packet<Packet>(k);
       visitor.initpacket(p, k);
       k = PacketSize;
     }
     if EIGEN_PREDICT_FALSE (short_circuit::run(visitor)) return;
     for (; k + PacketSize - 1 < size; k += PacketSize) {
       Packet p = mat.template packet<Packet>(k);
       visitor.packet(p, k);
       if EIGEN_PREDICT_FALSE (short_circuit::run(visitor)) return;
     }
     for (; k < size; k++) {
       visitor(mat.coeff(k), k);
       if EIGEN_PREDICT_FALSE (short_circuit::run(visitor)) return;
     }
   }
References Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::coeff(), EIGEN_PREDICT_FALSE, k, p, run(), size, and Eigen::SparseMatrixBase< Derived >::size().
Member Data Documentation
PacketSize
template<typename Visitor , typename Derived , bool ShortCircuitEvaluation> constexpr int Eigen::internal::visitor_impl< Visitor, Derived, Dynamic, true, true, ShortCircuitEvaluation >::PacketSize = packet_traits<Scalar>::size static constexpr
The documentation for this struct was generated from the following file:
Visitor.h