MercuryDPM: Eigen::test::runall< Scalar, PacketType, IsComplex, IsInteger > Struct Template Reference
Eigen::test::runall< Scalar, PacketType, IsComplex, IsInteger > Struct Template Reference
Static Public Member Functions
static void run ()
Member Function Documentation
run()
template<typename Scalar , typename PacketType , bool IsComplex, bool IsInteger> static void Eigen::test::runall< Scalar, PacketType, IsComplex, IsInteger >::run () inline static
 { packetmath_real<Scalar, PacketType>(); }
Referenced by Eigen::test::runner< Scalar, PacketType, true, true >::run(), Eigen::test::runner< Scalar, PacketType, true, false >::run(), and Eigen::test::runner< Scalar, PacketType, false, false >::run().
The documentation for this struct was generated from the following files:
packetmath_test_shared.h
special_packetmath.cpp