MercuryDPM: CGHandlerSelfTest.cpp File Reference
CGHandlerSelfTest.cpp File Reference
#include "Mercury3D.h"
#include "StatisticsVector.h"
#include "Walls/InfiniteWall.h"
#include "CG/CG.h"
#include "CG/TimeSmoothedCG.h"
#include "CG/TimeAveragedCG.h"
#include "CG/Functions/Lucy.h"
#include "CG/Functions/Linear.h"
#include "CG/Functions/Heaviside.h"
#include "CG/Functions/Gauss.h"
#include <cmath>
#include <iostream>
#include <iomanip>
#include <Species/LinearViscoelasticSpecies.h>
Classes
class CGHandlerSelfTest
In this file a cubic packing of 5^3 particles in a tri-axial box is created and allowed to settle under small gravity. After that Z statistics are calculated.
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
 {
     //declare the DPM problem and set the name
     CGHandlerSelfTest problem;
     problem.setName("CGHandlerSelfTest");
     //set gravity and the species properties
     problem.setSystemDimensions(3);
     problem.setGravity(Vec3D(0., 0., -1.));
     auto species = problem.speciesHandler.copyAndAddObject(LinearViscoelasticSpecies());
     species->setDensity(6.0 / constants::pi);
     species->setCollisionTimeAndRestitutionCoefficient(.01, .1, 1.);
     //accordingly, set the time step, final time, and save count
     problem.setTimeStep(.0002);
     problem.setTimeMax(0.5); //a total of 5000 time steps
     problem.setSaveCount(20);
     //define the different coarse-graining objects
     CG<CGCoordinates::O> cg0;
     cg0.statFile.setSaveCount(5);
     cg0.statFile.setName(problem.getName() + ".LucyO.T.stat");
     cg0.setTimeMax(0.2);
     problem.cgHandler.copyAndAddObject(cg0);
     TimeSmoothedCG<CGCoordinates::O> cg1;
     cg1.setWidthTime(0.01);
     cg1.setTimeStep(problem.getTimeStep()*problem.dataFile.getSaveCount());
     cg1.setTimeMax(0.2);
     cg1.statFile.setSaveCount(5);
     cg1.statFile.setName(problem.getName() + ".LucyO.TS.stat");
     problem.cgHandler.copyAndAddObject(cg1);
     TimeAveragedCG<CGCoordinates::O> cg2;
     cg2.setTimeMin(0.3);
     cg2.statFile.setSaveCount(5);
     cg2.statFile.setName(problem.getName() + ".LucyO.TA.stat");
     problem.cgHandler.copyAndAddObject(cg2);
     helpers::writeToFile(problem.getName()+".time.gnu","set title 'check if time-dependent, time-smoothed and time-averaged solutions agree'\n"
                          "set xlabel 't'\n "
             "set ylabel 'volume-averaged contact force'\n"
             "p 'CGHandlerSelfTest.LucyO.T.stat' u 1:24 w l t 'time-dependent', 'CGHandlerSelfTest.LucyO.TS.stat' u 1:24 w l t 'time-smoothed', 'CGHandlerSelfTest.LucyO.TA.stat' u (0):24 w p t 'time-averaged'"
     );
 //    CG<CGCoordinates::Z> cgB;
 //    cgB.setNZ(200);
 //    cgB.setWidth(0.3);
 //    cgB.statFile.setSaveCount(20000);
 //    cgB.statFile.setName(problem.getName() + ".LucyZ.stat");
 //    problem.cgHandler.copyAndAddObject(cgB);
 //
 //    CG<CGFunctions::LinearZ> cgC;
 //    cgC.setNZ(200);
 //    cgC.setWidth(0.3);
 //    cgC.statFile.setSaveCount(20000);
 //    cgC.statFile.setName(problem.getName() + ".LinearZ.stat");
 //    problem.cgHandler.copyAndAddObject(cgC);
 //
 //    CG<CGFunctions::HeavisideZ> cgD;
 //    cgD.setNZ(200);
 //    cgD.setWidth(0.3);
 //    cgD.statFile.setSaveCount(20000);
 //    cgD.statFile.setName(problem.getName() + ".HeavisideZ.stat");
 //    problem.cgHandler.copyAndAddObject(cgD);
 //
 //    CG<CGFunctions::GaussZ> cgE;
 //    cgE.setNZ(200);
 //    cgE.setWidth(0.1);
 //    cgE.statFile.setSaveCount(20000);
 //    cgE.statFile.setName(problem.getName() + ".GaussZ.stat");
 //    problem.cgHandler.copyAndAddObject(cgE);
 //
 //    CG<CGCoordinates::XZ> cgF;
 //    cgF.setNX(30);
 //    cgF.setNZ(30);
 //    cgF.setWidth(0.45);
 //    cgF.statFile.setSaveCount(20000);
 //    cgF.statFile.setName(problem.getName() + ".LucyXZ.stat");
 //    problem.cgHandler.copyAndAddObject(cgF);
 //
 //    CG<CGFunctions::LinearXZ> cgG;
 //    cgG.setNX(30);
 //    cgG.setNZ(30);
 //    cgG.setWidth(0.45);
 //    cgG.statFile.setSaveCount(20000);
 //    cgG.statFile.setName(problem.getName() + ".LinearXZ.stat");
 //    problem.cgHandler.copyAndAddObject(cgG);
 //
 //    CG<CGFunctions::HeavisideXZ> cgH;
 //    cgH.setNX(30);
 //    cgH.setNZ(30);
 //    cgH.setWidth(0.45);
 //    cgH.statFile.setSaveCount(20000);
 //    cgH.statFile.setName(problem.getName() + ".HeavisideXZ.stat");
 //    problem.cgHandler.copyAndAddObject(cgH);
 //
 //    CG<CGFunctions::GaussXZ> cgI;
 //    cgI.setNX(30);
 //    cgI.setNZ(30);
 //    cgI.setWidth(0.15);
 //    cgI.statFile.setSaveCount(20000);
 //    cgI.statFile.setName(problem.getName() + ".GaussXZ.stat");
 //    problem.cgHandler.copyAndAddObject(cgI);
 //
 //    CG<CGCoordinates::XYZ> cgJ;
 //    cgJ.setNX(10);
 //    cgJ.setNY(10);
 //    cgJ.setNZ(10);
 //    cgJ.setWidth(0.45);
 //    cgJ.statFile.setSaveCount(20000);
 //    cgJ.statFile.setName(problem.getName() + ".LucyXYZ.stat");
 //    problem.cgHandler.copyAndAddObject(cgJ);
 //
 //    CG<CGFunctions::LinearXYZ> cgK;
 //    cgK.setNX(10);
 //    cgK.setNY(10);
 //    cgK.setNZ(10);
 //    cgK.setWidth(0.45);
 //    cgK.statFile.setSaveCount(20000);
 //    cgK.statFile.setName(problem.getName() + ".LinearXYZ.stat");
 //    problem.cgHandler.copyAndAddObject(cgK);
 //
 //    CG<CGFunctions::HeavisideXYZ> cgL;
 //    cgL.setNX(10);
 //    cgL.setNY(10);
 //    cgL.setNZ(10);
 //    cgL.setWidth(0.45);
 //    cgL.statFile.setSaveCount(20000);
 //    cgL.statFile.setName(problem.getName() + ".HeavisideXYZ.stat");
 //    problem.cgHandler.copyAndAddObject(cgL);
 //
 //    CG<CGFunctions::GaussXYZ> cgM;
 //    cgM.setNX(10);
 //    cgM.setNY(10);
 //    cgM.setNZ(10);
 //    cgM.setWidth(0.15);
 //    cgM.statFile.setSaveCount(20000);
 //    cgM.statFile.setName(problem.getName() + ".GaussXYZ.stat");
 //    problem.cgHandler.copyAndAddObject(cgM);
 //
 //    CG<CGFunctions::GaussY> cg7;
 //    cg7.setNY(200);
 //    cg7.setWidth(0.15);
 //    cg7.statFile.setSaveCount(20000);
 //    cg7.statFile.setName(problem.getName() + ".GaussY.stat");
 //    problem.cgHandler.copyAndAddObject(cg7);
 //
 //    CG<CGFunctions::GaussX> cg8;
 //    cg8.setNX(200);
 //    cg8.setWidth(0.15);
 //    cg8.statFile.setSaveCount(20000);
 //    cg8.statFile.setName(problem.getName() + ".GaussX.stat");
 //    problem.cgHandler.copyAndAddObject(cg8);
 //
 //    CG<CGFunctions::GaussYZ> cg9;
 //    cg9.setNY(30);
 //    cg9.setNZ(30);
 //    cg9.setWidth(0.15);
 //    cg9.statFile.setSaveCount(20000);
 //    cg9.statFile.setName(problem.getName() + ".GaussYZ.stat");
 //    problem.cgHandler.copyAndAddObject(cg9);
 //
 //    CG<CGFunctions::GaussXY> cgA;
 //    cgA.setNX(30);
 //    cgA.setNY(30);
 //    cgA.setWidth(0.15);
 //    cgA.statFile.setSaveCount(20000);
 //    cgA.statFile.setName(problem.getName() + ".GaussXY.stat");
 //    problem.cgHandler.copyAndAddObject(cgA);
     //run the simulation
     problem.solve(argc, argv);
 }
References constants::pi, problem, File::setName(), File::setSaveCount(), BaseCG::setTimeMax(), BaseCG::setTimeMin(), TimeSmoothedCG< Coordinates, BaseFunction, Fields >::setTimeStep(), TimeSmoothedCG< Coordinates, BaseFunction, Fields >::setWidthTime(), BaseCG::statFile, and helpers::writeToFile().