MercuryDPM: Boundary_Items Namespace Reference
Boundary_Items Namespace Reference
Functions
void get_exact_u_b1 (double &time, const Vector< double > &x, double &u)
void boundary_velocity (double &time, const Vector< double > &x, double &u)
void boundary_velocity (const double &time, const Vector< double > &x, double &u)
Function Documentation
boundary_velocity() [1/2]
void Boundary_Items::boundary_velocity (const double & time, const Vector< double > & x, double & u)
  {
   // u assignment - spin-up problem
   u = x[0]*(1.0 - std::exp(-100*time));
  }
References Eigen::bfloat16_impl::exp(), and plotDoE::x.
boundary_velocity() [2/2]
void Boundary_Items::boundary_velocity (double & time, const Vector< double > & x, double & u)
  {
   //Spin-up with a "fast" exponential forcing
   u = x[0]*sin(x[1])*(1.0 - std::exp(-100*time));
  }
References Eigen::bfloat16_impl::exp(), sin(), and plotDoE::x.
Referenced by SphericalSpinUpProblem< ELEMENT >::actions_before_implicit_timestep(), and SphericalSpinUpProblem< ELEMENT >::set_boundary_conditions().
get_exact_u_b1()
void Boundary_Items::get_exact_u_b1 (double & time, const Vector< double > & x, double & u)
  {
   // u assignment - spin-up problem
   u = x[0]*sin(x[1])*(1.0 - std::exp(-time));
   // u assignment - DSDJ problem
   //u = x[0]*sin(time)*sin(x[1]);
  }
References Eigen::bfloat16_impl::exp(), sin(), and plotDoE::x.
Referenced by RefineableSphericalSpinUpProblem< ELEMENT >::set_boundary_conditions().