MercuryDPM: BinaryReader Class Reference
BinaryReader Class Reference
This gives functionality to read information from binary formats like STL etc. This class is complete stand-alone and is tested with one any reference to other MecuryDPM code except Vections and Logger.
#include <BinaryReader.h>
Public Member Functions
BinaryReader (std::string)
Default constuction, requires to users to prove the name of the file that will be opened.
~BinaryReader ()
Destructor, simple closes the file.
std::string readString (unsigned int numChar)
reads the next so many Characters (bytes) as a std::string
double readDouble (unsigned int size)
read the next so many bytes as a double
unsigned int readUnsignedInt (unsigned int size)
read the next so many bytes as a unsined int
double readFloat (unsigned int size)
read the next so many bytes as a double (not in this case they were saves as a float orgainlly)
void ignoreChar (unsigned int size)
read and ignore the next number of characters
Private Member Functions
void openFile (std::string fileName)
opens the file with fileName
void closeFile ()
close the file with fileName
Private Attributes
std::ifstream binaryFile_
The pointer for the binary file.
Detailed Description
This gives functionality to read information from binary formats like STL etc. This class is complete stand-alone and is tested with one any reference to other MecuryDPM code except Vections and Logger.
Constructor & Destructor Documentation
BinaryReader()
BinaryReader::BinaryReader (std::string fileName) explicit
Default constuction, requires to users to prove the name of the file that will be opened.
Parameters
[in[ fileName fileName of the binary file which is to be opened \deatails This is the default and only constuctor and it calls the private method openFile.
 {
     openFile(fileName);
 }
References UniformPSDSelfTest::fileName, and openFile().
~BinaryReader()
BinaryReader::~BinaryReader ()
Destructor, simple closes the file.
This is the destructor it simple closes the file as this is the only memory that needs freeing up
 {
     closeFile();
 }
References closeFile().
Member Function Documentation
closeFile()
void BinaryReader::closeFile () private
close the file with fileName
Simple function that closes the file; this is private and can only be called by the destructor
 {
     binaryFile_.close();
 }
References binaryFile_.
Referenced by ~BinaryReader().
ignoreChar()
void BinaryReader::ignoreChar (unsigned int size)
read and ignore the next number of characters
Parameters
[in] size number of bytpes to be ignored
Reads and disgards the next size characters size*8 bytes from the binary file
 {
     char tempRead[size];
     binaryFile_.read(tempRead, size);
 }
References binaryFile_, and size.
Referenced by main(), WallHandler::readTriangleWall(), and STLReader::STLReader().
openFile()
void BinaryReader::openFile (std::string fileName) private
opens the file with fileName
Parameters
[in] fileName fileName of the binary file which is to be opened
This opens the file associated with fileName, note the file is points is stored in the private varibles binaryFile_
 {
     binaryFile_.open(fileName, std::ios::binary);
     if (!binaryFile_)
     {
         logger(ERROR, "BinaryReader::openFile Could not open file; file % not found", fileName);
     }
 }
References binaryFile_, ERROR, UniformPSDSelfTest::fileName, and logger.
Referenced by BinaryReader().
readDouble()
double BinaryReader::readDouble (unsigned int size)
read the next so many bytes as a double
Parameters
[in] size This is the size in bytes of the double stored in the file
Returns
a double that is the double read from the file
Usage myDouble = readDouble(4) would read a 8*4 = 32 bit double from the file; or myDouble = readDouble(8) would read a 64 bit double from the file.
 {
     char tempRead[size];
     binaryFile_.read(tempRead, 4);
     double* returnDoublePtr = reinterpret_cast<double*>(tempRead);
     return (*returnDoublePtr);
 }
References binaryFile_, and size.
readFloat()
double BinaryReader::readFloat (unsigned int size)
read the next so many bytes as a double (not in this case they were saves as a float orgainlly)
Parameters
[in] size This is the size in bytes of the float stored in the file
Returns
a double (not a float) that is the upcast of the float that is read in.
Usage myDouble = readFloat(4) would read 32 bit float from file covert it to a double and then return this double.
See also
BinaryReader::readDouble Note, this is different to readDouble as the binary represation of a double and a float is different.
 {
     char tempRead[size];
     binaryFile_.read(tempRead, 4);
     float* returnFloatPtr = reinterpret_cast<float*>(tempRead);
     return static_cast<double>(*returnFloatPtr);
 }
References binaryFile_, and size.
Referenced by main(), WallHandler::readTriangleWall(), and STLReader::STLReader().
readString()
std::string BinaryReader::readString (unsigned int numChar)
reads the next so many Characters (bytes) as a std::string
Parameters
[in] numChar The number of characters to be read in from the binary file.
Returns
The function returns a std::string which is as long as the numChar requested.
The usages is myString = readString(6) will read in the next 6 characters from the binaryfile as a string.
 {
     char tempRead[numChar];
     binaryFile_.read(tempRead, numChar);
     std::string returnString(tempRead);
     return returnString;
 }
References binaryFile_, and oomph::Global_string_for_annotation::string().
Referenced by main(), WallHandler::readTriangleWall(), and STLReader::STLReader().
readUnsignedInt()
unsigned int BinaryReader::readUnsignedInt (unsigned int size)
read the next so many bytes as a unsined int
Parameters
[in] size This is the size in bytes of the unsigned int that is stored in the file.
Returns
a unsigned int this is the unisgned int that is read in
Usage myUnsignedInt = readUnsignedInt(4) woudl read a 32 bit (4*8) unsigned int from the file.
 {
     char tempRead[size];
     binaryFile_.read(tempRead, size);
     unsigned int* returnUnsignedInt = reinterpret_cast<unsigned int*>(tempRead);
     return (*returnUnsignedInt);
 }
References binaryFile_, and size.
Referenced by main(), WallHandler::readTriangleWall(), and STLReader::STLReader().
Member Data Documentation
binaryFile_
std::ifstream BinaryReader::binaryFile_ private
The pointer for the binary file.
Referenced by closeFile(), ignoreChar(), openFile(), readDouble(), readFloat(), readString(), and readUnsignedInt().
The documentation for this class was generated from the following files:
BinaryReader.h
BinaryReader.cc