MercuryDPM: Eigen::internal::IndexedViewHelperIndicesWrapper< ArithmeticSequence< FirstType, SizeType, IncrType >, NestedSizeAtCompileTime, void > Struct Template Reference
Eigen::internal::IndexedViewHelperIndicesWrapper< ArithmeticSequence< FirstType, SizeType, IncrType >, NestedSizeAtCompileTime, void > Struct Template Reference
#include <IndexedViewHelper.h>
Public Types
using Indices = ArithmeticSequence< FirstType, SizeType, IncrType >
using type = ArithmeticSequenceRange< FirstAtCompileTime, SizeAtCompileTime, IncrAtCompileTime >
Static Public Member Functions
static type CreateIndexSequence (const Indices &indices, Index nested_size)
Static Public Attributes
static constexpr Index EvalFirstAtCompileTime
static constexpr Index EvalSizeAtCompileTime
static constexpr Index EvalIncrAtCompileTime
static constexpr Index FirstAtCompileTime
static constexpr Index SizeAtCompileTime
static constexpr Index IncrAtCompileTime
Member Typedef Documentation
Indices
template<typename FirstType , typename SizeType , typename IncrType , int NestedSizeAtCompileTime> using Eigen::internal::IndexedViewHelperIndicesWrapper< ArithmeticSequence< FirstType, SizeType, IncrType >, NestedSizeAtCompileTime, void >::Indices = ArithmeticSequence<FirstType, SizeType, IncrType>
type
template<typename FirstType , typename SizeType , typename IncrType , int NestedSizeAtCompileTime> using Eigen::internal::IndexedViewHelperIndicesWrapper< ArithmeticSequence< FirstType, SizeType, IncrType >, NestedSizeAtCompileTime, void >::type = ArithmeticSequenceRange<FirstAtCompileTime, SizeAtCompileTime, IncrAtCompileTime>
Member Function Documentation
CreateIndexSequence()
template<typename FirstType , typename SizeType , typename IncrType , int NestedSizeAtCompileTime> static type Eigen::internal::IndexedViewHelperIndicesWrapper< ArithmeticSequence< FirstType, SizeType, IncrType >, NestedSizeAtCompileTime, void >::CreateIndexSequence (const Indices & indices, Index nested_size) inline static
{
     Index first =
         SymbolicExpressionEvaluator<FirstType, NestedSizeAtCompileTime>::eval(indices.firstObject(), nested_size);
     Index size =
         SymbolicExpressionEvaluator<SizeType, NestedSizeAtCompileTime>::eval(indices.sizeObject(), nested_size);
     Index incr =
         SymbolicExpressionEvaluator<IncrType, NestedSizeAtCompileTime>::eval(indices.incrObject(), nested_size);
     return type(first, size, incr);
   }
References Eigen::internal::SymbolicExpressionEvaluator< Expr, SizeAtCompileTime, EnableIf >::eval(), Eigen::ArithmeticSequence< FirstType, SizeType, IncrType >::firstObject(), Eigen::ArithmeticSequence< FirstType, SizeType, IncrType >::incrObject(), size, and Eigen::ArithmeticSequence< FirstType, SizeType, IncrType >::sizeObject().
Member Data Documentation
EvalFirstAtCompileTime
template<typename FirstType , typename SizeType , typename IncrType , int NestedSizeAtCompileTime> constexpr Index Eigen::internal::IndexedViewHelperIndicesWrapper< ArithmeticSequence< FirstType, SizeType, IncrType >, NestedSizeAtCompileTime, void >::EvalFirstAtCompileTime static constexpr
Initial value:
=
      SymbolicExpressionEvaluator<FirstType, NestedSizeAtCompileTime>::ValueAtCompileTime
EvalIncrAtCompileTime
template<typename FirstType , typename SizeType , typename IncrType , int NestedSizeAtCompileTime> constexpr Index Eigen::internal::IndexedViewHelperIndicesWrapper< ArithmeticSequence< FirstType, SizeType, IncrType >, NestedSizeAtCompileTime, void >::EvalIncrAtCompileTime static constexpr
Initial value:
=
      SymbolicExpressionEvaluator<IncrType, NestedSizeAtCompileTime>::ValueAtCompileTime
EvalSizeAtCompileTime
template<typename FirstType , typename SizeType , typename IncrType , int NestedSizeAtCompileTime> constexpr Index Eigen::internal::IndexedViewHelperIndicesWrapper< ArithmeticSequence< FirstType, SizeType, IncrType >, NestedSizeAtCompileTime, void >::EvalSizeAtCompileTime static constexpr
Initial value:
=
      SymbolicExpressionEvaluator<SizeType, NestedSizeAtCompileTime>::ValueAtCompileTime
FirstAtCompileTime
template<typename FirstType , typename SizeType , typename IncrType , int NestedSizeAtCompileTime> constexpr Index Eigen::internal::IndexedViewHelperIndicesWrapper< ArithmeticSequence< FirstType, SizeType, IncrType >, NestedSizeAtCompileTime, void >::FirstAtCompileTime static constexpr
Initial value:
=
      (int(EvalFirstAtCompileTime) == Undefined) ? Index(DynamicIndex) : EvalFirstAtCompileTime
IncrAtCompileTime
template<typename FirstType , typename SizeType , typename IncrType , int NestedSizeAtCompileTime> constexpr Index Eigen::internal::IndexedViewHelperIndicesWrapper< ArithmeticSequence< FirstType, SizeType, IncrType >, NestedSizeAtCompileTime, void >::IncrAtCompileTime static constexpr
Initial value:
=
      (int(EvalIncrAtCompileTime) == Undefined) ? Index(DynamicIndex) : EvalIncrAtCompileTime
SizeAtCompileTime
template<typename FirstType , typename SizeType , typename IncrType , int NestedSizeAtCompileTime> constexpr Index Eigen::internal::IndexedViewHelperIndicesWrapper< ArithmeticSequence< FirstType, SizeType, IncrType >, NestedSizeAtCompileTime, void >::SizeAtCompileTime static constexpr
Initial value:
=
      (int(EvalSizeAtCompileTime) == Undefined) ? Index(Dynamic) : EvalSizeAtCompileTime
The documentation for this struct was generated from the following file:
IndexedViewHelper.h