MercuryDPM: oomph::GeneralCircle Class Reference
oomph::GeneralCircle Class Reference
#include <circle.h>
Public Member Functions
GeneralCircle (const double &x_c, const double &y_c, const double &r)
Constructor: Pass x and y-coords of centre and radius (all pinned)
GeneralCircle (Data *geom_data_pt)
virtual ~GeneralCircle ()
Destructor: Clean up if necessary.
void position (const Vector< double > &zeta, Vector< double > &r) const
Position Vector at Lagrangian coordinate zeta.
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
double & x_c ()
Access function to x-coordinate of centre of circle.
double & y_c ()
Access function to y-coordinate of centre of circle.
double & R ()
Access function to radius of circle.
unsigned ngeom_data () const
How many items of Data does the shape of the object depend on?
Data * geom_data_pt (const unsigned &j)
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition_dt (const Vector< double > &zeta, const unsigned &j, Vector< double > &drdt)
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
virtual void locate_zeta (const Vector< double > &zeta, GeomObject *&sub_geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
Protected Attributes
Vector< Data * > Geom_data_pt
Vector of pointers to Data items that affects the object's shape.
bool Must_clean_up
Do I need to clean up?
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Detailed Description
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// GeneralCircle in 2D space.
\[ x = X_c + R \cos(\zeta) \]
\[ y = Y_c + R \sin(\zeta) \]
The three parameters \(X_c, Y_c \) and \(R \) are represented by Data and can therefore be unknowns in the problem.
Constructor & Destructor Documentation
GeneralCircle() [1/2]
oomph::GeneralCircle::GeneralCircle (const double & x_c, const double & y_c, const double & r) inline
Constructor: Pass x and y-coords of centre and radius (all pinned)
                                 : GeomObject(1,2)
   {
    // Create Data: We have one Data item with 3 values. The Data object
    // stores the x position of the circle's centre as value 0,
    // the y position of the circle's centre as value 1, and the
    // circle's radius as value 2.
    Geom_data_pt.resize(1);
    Geom_data_pt[0] = new Data(3);
    // Assign data: X_c -- the value is free by default: Need to pin it.
    // Pin the data
    Geom_data_pt[0]->pin(0);
    // Give it a value:
    Geom_data_pt[0]->set_value(0,x_c);
    // Assign data: Y_c -- the value is free by default: Need to pin it.
    // Pin the data
    Geom_data_pt[0]->pin(1);
    // Give it a value:
    Geom_data_pt[0]->set_value(1,y_c);
    // Assign data: R -- the value is free by default: Need to pin it.
    // Pin the data
    Geom_data_pt[0]->pin(2);
    // Give it a value:
    Geom_data_pt[0]->set_value(2,r);
    // I've created the data, I need to clean up
    Must_clean_up=true;
   }
References Geom_data_pt, Must_clean_up, UniformPSDSelfTest::r, x_c(), and y_c().
GeneralCircle() [2/2]
oomph::GeneralCircle::GeneralCircle (Data * geom_data_pt) inline
Alternative constructor: Pass x and y-coords of centre and radius (all as part of Data)
Geom_data_pt[0]->value(0) = X_c;
Geom_data_pt[0]->value(1) = Y_c;
Geom_data_pt[0]->value(2) = R;
                                    : GeomObject(1,2)
   {
 #ifdef PARANOID
    if (geom_data_pt->nvalue()!=3)
     {
      std::ostringstream error_stream;
      error_stream << "Geometric Data must have 3 values, not "
                   << geom_data_pt->nvalue() << std::endl;
      throw OomphLibError(error_stream.str(),
                          OOMPH_CURRENT_FUNCTION,
                          OOMPH_EXCEPTION_LOCATION);
     }
 #endif
    Geom_data_pt.resize(1);
    Geom_data_pt[0]=geom_data_pt;
    // Data has been created externally: Must not clean up
    Must_clean_up=false;
   } //end of alternative constructor
References geom_data_pt(), Geom_data_pt, Must_clean_up, oomph::Data::nvalue(), OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
~GeneralCircle()
virtual oomph::GeneralCircle::~GeneralCircle () inline virtual
Destructor: Clean up if necessary.
   {
    // Do I need to clean up?
    if (Must_clean_up)
     {
      unsigned ngeom_data=Geom_data_pt.size();
      for (unsigned i=0;i<ngeom_data;i++)
       {
        delete Geom_data_pt[i];
        Geom_data_pt[i]=0;
       }
     }
   } // end of destructor
References Geom_data_pt, i, Must_clean_up, and ngeom_data().
Member Function Documentation
geom_data_pt()
Data* oomph::GeneralCircle::geom_data_pt (const unsigned & j) inline virtual
Return pointer to the j-th Data item that the object's shape depends on
Reimplemented from oomph::GeomObject.
 {return Geom_data_pt[j];}
References Geom_data_pt, and j.
Referenced by GeneralCircle().
ngeom_data()
unsigned oomph::GeneralCircle::ngeom_data () const inline virtual
How many items of Data does the shape of the object depend on?
Reimplemented from oomph::GeomObject.
 {return Geom_data_pt.size();}
References Geom_data_pt.
Referenced by ~GeneralCircle().
position() [1/2]
void oomph::GeneralCircle::position (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position Vector at Lagrangian coordinate zeta at time level t (t=0: present; t>0: previous level). Steady object, so we simply forward the call to the steady version.
Reimplemented from oomph::GeomObject.
   {position(zeta,r);}
References position(), UniformPSDSelfTest::r, and Eigen::zeta().
position() [2/2]
void oomph::GeneralCircle::position (const Vector< double > & zeta, Vector< double > & r) const inline virtual
Position Vector at Lagrangian coordinate zeta.
Implements oomph::GeomObject.
   {
    // Extract data
    double X_c= Geom_data_pt[0]->value(0);
    double Y_c= Geom_data_pt[0]->value(1);
    double R= Geom_data_pt[0]->value(2);
    // Position vector
    r[0] = X_c+R*cos(zeta[0]);
    r[1] = Y_c+R*sin(zeta[0]);
   } // end of position(...)
References cos(), Geom_data_pt, UniformPSDSelfTest::r, R(), sin(), ProblemParameters::Y_c, and Eigen::zeta().
Referenced by main(), and position().
R()
double& oomph::GeneralCircle::R () inline
Access function to radius of circle.
 {return *Geom_data_pt[0]->value_pt(2);}
References Geom_data_pt.
Referenced by position().
x_c()
double& oomph::GeneralCircle::x_c () inline
Access function to x-coordinate of centre of circle.
 {return *Geom_data_pt[0]->value_pt(0);}
References Geom_data_pt.
Referenced by GeneralCircle().
y_c()
double& oomph::GeneralCircle::y_c () inline
Access function to y-coordinate of centre of circle.
 {return *Geom_data_pt[0]->value_pt(1);}
References Geom_data_pt.
Referenced by oomph::ElasticallySupportedRingElement::fill_in_generic_residual_contribution(), GeneralCircle(), and main().
Member Data Documentation
Geom_data_pt
Vector<Data*> oomph::GeneralCircle::Geom_data_pt protected
Vector of pointers to Data items that affects the object's shape.
Referenced by oomph::ElasticallySupportedRingElement::ElasticallySupportedRingElement(), GeneralCircle(), geom_data_pt(), ngeom_data(), position(), R(), x_c(), y_c(), and ~GeneralCircle().
Must_clean_up
bool oomph::GeneralCircle::Must_clean_up protected
Do I need to clean up?
Referenced by oomph::ElasticallySupportedRingElement::ElasticallySupportedRingElement(), GeneralCircle(), and ~GeneralCircle().
The documentation for this class was generated from the following file:
circle.h