MercuryDPM: plate.cc File Reference
plate.cc File Reference
#include "generic.h"
#include "shell.h"
#include "meshes/rectangular_quadmesh.h"
Classes
class FlatPlate
Flat plate in x-y plane.
class FlatPlateMesh< ELEMENT >
class PlateProblem< ELEMENT >
Namespaces
Global_Physical_Variables
Global variables.
Functions
double & Global_Physical_Variables::external_pressure ()
Access function to value of external pressure.
void Global_Physical_Variables::press_load (const Vector< double > &xi, const Vector< double > &x, const Vector< double > &N, Vector< double > &load)
Load function: Perturbation pressure to force non-axisymmetric deformation.
int main (int argc, char *argv[])
Driver.
Variables
double Global_Physical_Variables::Prescribed_z = 0.0
Prescribed position of control point.
Function Documentation
main()
int main (int argc , char * argv[])
Driver.
(pow(0.05,3)/12.0) << " "
 {
  //Store command line arguments
  CommandLineArgs::setup(argc,argv);
  //Length of domain
  double L_x=10.0;
  double L_y=1.0;
  //Set up the problem
  PlateProblem<StorableShapeSolidElement<DiagHermiteShellElement> >
   problem(10,3,L_x,L_y);
  ofstream some_file;
  char filename[100];
  // Label for output
  DocInfo doc_info;
  // Output directory
  doc_info.set_directory("RESLT");
  //Open an output trace file
  sprintf(filename,"%s/trace.dat",doc_info.directory().c_str());
  ofstream trace_file(filename);
  trace_file << "VARIABLES=\"p_e_x_t\",\"z_ctrl\"" << std::endl;
  trace_file << "ZONE" << std::endl;
  //Gradually deflect the plate by decreasing the value of the prescribed
  //position
  unsigned nstep=2;
  for(unsigned i=0;i<nstep;i++)
   {
    // Increase displacement
    Global_Physical_Variables::Prescribed_z -= 0.1;
    // Solve
    problem.newton_solve();
    // Calculate exact solution for `string under tension' (applicable for
    // small wall thickness and pinned ends)
    // The tangent of the angle beta
    double tanbeta =-2.0*Global_Physical_Variables::Prescribed_z/L_x;
    double exact_pressure = 0.0;
    //If the plate has deformed, calculate the pressure required
    if(tanbeta!=0)
     {
      //Calculate the opening angle alpha
      double alpha = 2.0*atan(2.0*tanbeta/(1.0-tanbeta*tanbeta));
       // Jump back onto the main branch if alpha>180 degrees
      if (alpha<0) alpha+=2.0*MathematicalConstants::Pi;
      // Green strain:
      double gamma=0.5*(0.25*alpha*alpha/(sin(0.5*alpha)*sin(0.5*alpha))-1.0);
      //Calculate the exact pressure
      exact_pressure=Global_Physical_Variables::H*
       (Global_Physical_Variables::Sigma0+gamma)*alpha/L_x;
     }
    //Output the pressure
    trace_file
     << Global_Physical_Variables::external_pressure() << " "
     << Global_Physical_Variables::Prescribed_z  << " "
     << exact_pressure << " "
     << std::endl;
    //Output the shape
    sprintf(filename,"%s/plate%i.dat",doc_info.directory().c_str(),
            doc_info.number());
    some_file.open(filename);
    problem.mesh_pt()->output(some_file,15);
 //    for (unsigned e=0;e<nelem;e++)
 //     {
 //      mesh_pt()->finite_element_pt(e)->output(some_file,15);
 //     }
    some_file.close();
    // Increment counter for output files
    doc_info.number()++;
   }
  //Close the trace file
  trace_file.close();
 }
References alpha, Eigen::bfloat16_impl::atan(), oomph::DocInfo::directory(), Global_Physical_Variables::external_pressure(), MergeRestartFiles::filename, mathsFunc::gamma(), Global_Physical_Variables::H, i, Global_Parameters::L_x, Global_Parameters::L_y, oomph::DocInfo::number(), BiharmonicTestFunctions2::Pi, Global_Physical_Variables::Prescribed_z, problem, oomph::DocInfo::set_directory(), Flag_definition::setup(), Global_Physical_Variables::Sigma0, and sin().