MercuryDPM: STLReader Class Reference
STLReader Class Reference
Public Member Functions
STLReader (std::string fileName)
void addTriangle (const Vec3D normal, const Vec3D vertex1, const Vec3D vertex2, const Vec3D vertex3)
void output ()
STLTriangle getTriangle (const unsigned int num)
Public Member Functions inherited from BinaryReader
BinaryReader (std::string)
Default constuction, requires to users to prove the name of the file that will be opened.
~BinaryReader ()
Destructor, simple closes the file.
std::string readString (unsigned int numChar)
reads the next so many Characters (bytes) as a std::string
double readDouble (unsigned int size)
read the next so many bytes as a double
unsigned int readUnsignedInt (unsigned int size)
read the next so many bytes as a unsined int
double readFloat (unsigned int size)
read the next so many bytes as a double (not in this case they were saves as a float orgainlly)
void ignoreChar (unsigned int size)
read and ignore the next number of characters
Private Attributes
std::string header_
unsigned numTriangles_
std::vector< STLTriangle > Triangles_
Constructor & Destructor Documentation
STLReader()
STLReader::STLReader (std::string fileName) inline
                                   : BinaryReader(fileName)
     {
         header_= readString(80);
         numTriangles_ = readUnsignedInt(4);
         Triangles_.resize(numTriangles_);
         for (unsigned int i=0; i<(numTriangles_);i++)
         {
             Triangles_[i].normal.x() = readFloat(4);
             Triangles_[i].normal.y() = readFloat(4);
             Triangles_[i].normal.z() = readFloat(4);
             Triangles_[i].vertex1.x() = readFloat(4);
             Triangles_[i].vertex1.y() = readFloat(4);
             Triangles_[i].vertex1.z() = readFloat(4);
             Triangles_[i].vertex2.x() = readFloat(4);
             Triangles_[i].vertex2.y() = readFloat(4);
             Triangles_[i].vertex2.z() = readFloat(4);
             Triangles_[i].vertex3.x() = readFloat(4);
             Triangles_[i].vertex3.y() = readFloat(4);
             Triangles_[i].vertex3.z() = readFloat(4);
             //Now ignore (read) the two dummy characters
             ignoreChar(2);
         }
     }
References header_, i, BinaryReader::ignoreChar(), numTriangles_, BinaryReader::readFloat(), BinaryReader::readString(), BinaryReader::readUnsignedInt(), and Triangles_.
Member Function Documentation
addTriangle()
void STLReader::addTriangle (const Vec3D normal, const Vec3D vertex1, const Vec3D vertex2, const Vec3D vertex3) inline
     {
         STLTriangle triangleToAdd(normal,vertex1,vertex2,vertex3);
         Triangles_.push_back(triangleToAdd);
     }
References WallFunction::normal(), and Triangles_.
getTriangle()
STLTriangle STLReader::getTriangle (const unsigned int num) inline
     {
         return Triangles_[num];
     }
References Triangles_.
Referenced by main().
output()
void STLReader::output () inline
     {
         logger(INFO, "%\n", header_, Flusher::NO_FLUSH);
         for (unsigned int i = 0; i < (numTriangles_); i++)
         {
             logger(INFO, "Triangle % has normal % and vertexes % % %",
                    i, Triangles_[i].normal, Triangles_[i].vertex1, Triangles_[i].vertex2, Triangles_[i].vertex3);
         }
     }
References header_, i, INFO, logger, NO_FLUSH, WallFunction::normal(), numTriangles_, and Triangles_.
Member Data Documentation
header_
std::string STLReader::header_ private
Referenced by output(), and STLReader().
numTriangles_
unsigned STLReader::numTriangles_ private
Referenced by output(), and STLReader().
Triangles_
std::vector<STLTriangle> STLReader::Triangles_ private
Referenced by addTriangle(), getTriangle(), output(), and STLReader().
The documentation for this class was generated from the following file:
BinaryReaderSTL1by1by1bySquareUnitTest.cpp