MercuryDPM: cxx11_tensor_empty.cpp File Reference
cxx11_tensor_empty.cpp File Reference
#include "main.h"
#include <Eigen/CXX11/Tensor>
Functions
static void test_empty_tensor ()
static void test_empty_fixed_size_tensor ()
EIGEN_DECLARE_TEST (cxx11_tensor_empty)
Function Documentation
EIGEN_DECLARE_TEST()
EIGEN_DECLARE_TEST (cxx11_tensor_empty)
{
   CALL_SUBTEST(test_empty_tensor());
   CALL_SUBTEST(test_empty_fixed_size_tensor());
 }
References CALL_SUBTEST, test_empty_fixed_size_tensor(), and test_empty_tensor().
test_empty_fixed_size_tensor()
static void test_empty_fixed_size_tensor () static
{
   TensorFixedSize<float, Sizes<0> > source;
   TensorFixedSize<float, Sizes<0> > tgt1 = source;
   TensorFixedSize<float, Sizes<0> > tgt2(source);
   TensorFixedSize<float, Sizes<0> > tgt3;
   tgt3 = tgt1;
   tgt3 = tgt2;
 }
References TestProblem::source().
Referenced by EIGEN_DECLARE_TEST().
test_empty_tensor()
static void test_empty_tensor () static
{
   Tensor<float, 2> source;
   Tensor<float, 2> tgt1 = source;
   Tensor<float, 2> tgt2(source);
   Tensor<float, 2> tgt3;
   tgt3 = tgt1;
   tgt3 = tgt2;
 }
References TestProblem::source().
Referenced by EIGEN_DECLARE_TEST().