MercuryDPM: oomph::ExactSubBiharmonicPreconditioner Class Reference
oomph::ExactSubBiharmonicPreconditioner Class Reference
#include <biharmonic_preconditioner.h>
Public Member Functions
ExactSubBiharmonicPreconditioner (BiharmonicPreconditioner *master_prec_pt, const bool &retain_all_blocks=false)
Constructor - for a preconditioner acting as a sub preconditioner.
~ExactSubBiharmonicPreconditioner ()
destructor deletes the exact preconditioner
void clean_up_memory ()
delete the subsidiary preconditioner pointer
ExactSubBiharmonicPreconditioner (const ExactSubBiharmonicPreconditioner &)=delete
Broken copy constructor.
void operator= (const ExactSubBiharmonicPreconditioner &)=delete
Broken assignment operator.
void setup ()
Setup the preconditioner.
void preconditioner_solve (const DoubleVector &r, DoubleVector &z)
Apply preconditioner to r.
Public Member Functions inherited from oomph::BlockPreconditioner< CRDoubleMatrix >
BlockPreconditioner ()
Constructor.
BlockPreconditioner (const BlockPreconditioner &)=delete
Broken copy constructor.
virtual ~BlockPreconditioner ()
Destructor.
void operator= (const BlockPreconditioner &)=delete
Broken assignment operator.
CRDoubleMatrix * matrix_pt () const
void turn_on_recursive_debug_flag ()
void turn_off_recursive_debug_flag ()
void turn_on_debug_flag ()
Toggles on the debug flag.
void turn_off_debug_flag ()
Toggles off the debug flag.
void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse)
void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse, const Vector< Vector< unsigned >> &doftype_coarsen_map_coarse)
virtual void block_setup ()
void block_setup (const Vector< unsigned > &dof_to_block_map)
void get_block (const unsigned &i, const unsigned &j, CRDoubleMatrix &output_matrix, const bool &ignore_replacement_block=false) const
CRDoubleMatrix get_block (const unsigned &i, const unsigned &j, const bool &ignore_replacement_block=false) const
void set_master_matrix_pt (CRDoubleMatrix *in_matrix_pt)
Set the matrix_pt in the upper-most master preconditioner.
void get_block_other_matrix (const unsigned &i, const unsigned &j, CRDoubleMatrix *in_matrix_pt, CRDoubleMatrix &output_matrix)
void get_blocks (DenseMatrix< bool > &required_blocks, DenseMatrix< CRDoubleMatrix * > &block_matrix_pt) const
void get_dof_level_block (const unsigned &i, const unsigned &j, CRDoubleMatrix &output_block, const bool &ignore_replacement_block=false) const
void get_dof_level_block (const unsigned &block_i, const unsigned &block_j, CRDoubleMatrix &output_block, const bool &ignore_replacement_block) const
CRDoubleMatrix get_concatenated_block (const VectorMatrix< BlockSelector > &selected_block)
void get_concatenated_block_vector (const Vector< unsigned > &block_vec_number, const DoubleVector &v, DoubleVector &b)
void return_concatenated_block_vector (const Vector< unsigned > &block_vec_number, const DoubleVector &b, DoubleVector &v) const
Takes concatenated block ordered vector, b, and copies its.
void get_block_vectors (const Vector< unsigned > &block_vec_number, const DoubleVector &v, Vector< DoubleVector > &s) const
void get_block_vectors (const DoubleVector &v, Vector< DoubleVector > &s) const
void return_block_vectors (const Vector< unsigned > &block_vec_number, const Vector< DoubleVector > &s, DoubleVector &v) const
void return_block_vectors (const Vector< DoubleVector > &s, DoubleVector &v) const
void get_block_vector (const unsigned &n, const DoubleVector &v, DoubleVector &b) const
void return_block_vector (const unsigned &n, const DoubleVector &b, DoubleVector &v) const
void get_block_ordered_preconditioner_vector (const DoubleVector &v, DoubleVector &w)
void return_block_ordered_preconditioner_vector (const DoubleVector &w, DoubleVector &v) const
unsigned nblock_types () const
Return the number of block types.
unsigned ndof_types () const
Return the total number of DOF types.
const Mesh * mesh_pt (const unsigned &i) const
unsigned nmesh () const
int block_number (const unsigned &i_dof) const
Return the block number corresponding to a global index i_dof.
int index_in_block (const unsigned &i_dof) const
const LinearAlgebraDistribution * block_distribution_pt (const unsigned &b) const
Access function to the block distributions (const version).
LinearAlgebraDistribution * block_distribution_pt (const unsigned b)
Access function to the block distributions (non-const version).
LinearAlgebraDistribution * dof_block_distribution_pt (const unsigned &b)
Access function to the dof-level block distributions.
const LinearAlgebraDistribution * master_distribution_pt () const
unsigned ndof_types_in_mesh (const unsigned &i) const
bool is_subsidiary_block_preconditioner () const
bool is_master_block_preconditioner () const
void set_block_output_to_files (const std::string &basefilename)
void disable_block_output_to_files ()
Turn off output of blocks (by clearing the basefilename string).
bool block_output_on () const
Test if output of blocks is on or not.
void output_blocks_to_files (const std::string &basefilename, const unsigned &precision=8) const
void post_block_matrix_assembly_partial_clear ()
BlockPreconditioner< CRDoubleMatrix > * master_block_preconditioner_pt () const
Access function to the master block preconditioner pt.
void clear_block_preconditioner_base ()
void document ()
Vector< Vector< unsigned > > doftype_coarsen_map_fine () const
Vector< unsigned > get_fine_grain_dof_types_in (const unsigned &i) const
unsigned nfine_grain_dof_types_in (const unsigned &i) const
MapMatrix< unsigned, CRDoubleMatrix * > replacement_dof_block_pt () const
Access function to the replaced dof-level blocks.
void setup_matrix_vector_product (MatrixVectorProduct *matvec_prod_pt, CRDoubleMatrix *block_pt, const Vector< unsigned > &block_col_indices)
void setup_matrix_vector_product (MatrixVectorProduct *matvec_prod_pt, CRDoubleMatrix *block_pt, const unsigned &block_col_index)
void internal_get_block_ordered_preconditioner_vector (const DoubleVector &v, DoubleVector &w) const
void internal_return_block_ordered_preconditioner_vector (const DoubleVector &w, DoubleVector &v) const
unsigned internal_nblock_types () const
unsigned internal_ndof_types () const
void internal_return_block_vector (const unsigned &n, const DoubleVector &b, DoubleVector &v) const
void internal_get_block_vector (const unsigned &n, const DoubleVector &v, DoubleVector &b) const
void internal_get_block_vectors (const Vector< unsigned > &block_vec_number, const DoubleVector &v, Vector< DoubleVector > &s) const
void internal_get_block_vectors (const DoubleVector &v, Vector< DoubleVector > &s) const
void internal_return_block_vectors (const Vector< unsigned > &block_vec_number, const Vector< DoubleVector > &s, DoubleVector &v) const
void internal_return_block_vectors (const Vector< DoubleVector > &s, DoubleVector &v) const
void internal_get_block (const unsigned &i, const unsigned &j, CRDoubleMatrix &output_block) const
void internal_get_block (const unsigned &block_i, const unsigned &block_j, CRDoubleMatrix &output_block) const
int internal_block_number (const unsigned &i_dof) const
int internal_index_in_block (const unsigned &i_dof) const
const LinearAlgebraDistribution * internal_block_distribution_pt (const unsigned &b) const
Access function to the internal block distributions.
void insert_auxiliary_block_distribution (const Vector< unsigned > &block_vec_number, LinearAlgebraDistribution *dist_pt)
void block_matrix_test (const unsigned &i, const unsigned &j, const CRDoubleMatrix *block_matrix_pt) const
int get_index_of_value (const Vector< myType > &vec, const myType val, const bool sorted=false) const
Public Member Functions inherited from oomph::Preconditioner
Preconditioner ()
Constructor.
Preconditioner (const Preconditioner &)=delete
Broken copy constructor.
void operator= (const Preconditioner &)=delete
Broken assignment operator.
virtual ~Preconditioner ()
Destructor (empty)
virtual void preconditioner_solve_transpose (const DoubleVector &r, DoubleVector &z)
void setup (DoubleMatrixBase *matrix_pt)
void setup (const Problem *problem_pt, DoubleMatrixBase *matrix_pt)
void enable_silent_preconditioner_setup ()
Set up the block preconditioner quietly!
void disable_silent_preconditioner_setup ()
Be verbose in the block preconditioner setup.
virtual void set_matrix_pt (DoubleMatrixBase *matrix_pt)
Set the matrix pointer.
virtual const OomphCommunicator * comm_pt () const
Get function for comm pointer.
virtual void set_comm_pt (const OomphCommunicator *const comm_pt)
Set the communicator pointer.
double setup_time () const
Returns the time to setup the preconditioner.
virtual void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse)
virtual void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse, const Vector< Vector< unsigned >> &doftype_coarsen_map_coarse)
Public Member Functions inherited from oomph::DistributableLinearAlgebraObject
DistributableLinearAlgebraObject ()
Default constructor - create a distribution.
DistributableLinearAlgebraObject (const DistributableLinearAlgebraObject &matrix)=delete
Broken copy constructor.
void operator= (const DistributableLinearAlgebraObject &)=delete
Broken assignment operator.
virtual ~DistributableLinearAlgebraObject ()
Destructor.
LinearAlgebraDistribution * distribution_pt () const
access to the LinearAlgebraDistribution
unsigned nrow () const
access function to the number of global rows.
unsigned nrow_local () const
access function for the num of local rows on this processor.
unsigned nrow_local (const unsigned &p) const
access function for the num of local rows on this processor.
unsigned first_row () const
access function for the first row on this processor
unsigned first_row (const unsigned &p) const
access function for the first row on this processor
bool distributed () const
distribution is serial or distributed
bool distribution_built () const
void build_distribution (const LinearAlgebraDistribution *const dist_pt)
void build_distribution (const LinearAlgebraDistribution &dist)
Public Attributes
Preconditioner * Sub_preconditioner_pt
bool Retain_all_blocks
Additional Inherited Members
Protected Member Functions inherited from oomph::BlockPreconditioner< CRDoubleMatrix >
void set_nmesh (const unsigned &n)
void set_mesh (const unsigned &i, const Mesh *const mesh_pt, const bool &allow_multiple_element_type_in_mesh=false)
void set_replacement_dof_block (const unsigned &block_i, const unsigned &block_j, CRDoubleMatrix *replacement_dof_block_pt)
bool any_mesh_distributed () const
int internal_dof_number (const unsigned &i_dof) const
unsigned internal_index_in_dof (const unsigned &i_dof) const
unsigned internal_block_dimension (const unsigned &b) const
unsigned internal_dof_block_dimension (const unsigned &i) const
unsigned master_nrow () const
unsigned internal_master_dof_number (const unsigned &b) const
const LinearAlgebraDistribution * internal_preconditioner_matrix_distribution_pt () const
const LinearAlgebraDistribution * preconditioner_matrix_distribution_pt () const
Protected Member Functions inherited from oomph::DistributableLinearAlgebraObject
void clear_distribution ()
Protected Attributes inherited from oomph::BlockPreconditioner< CRDoubleMatrix >
MapMatrix< unsigned, CRDoubleMatrix * > Replacement_dof_block_pt
The replacement dof-level blocks.
Vector< LinearAlgebraDistribution * > Block_distribution_pt
The distribution for the blocks.
Vector< Vector< unsigned > > Block_to_dof_map_coarse
Vector< Vector< unsigned > > Block_to_dof_map_fine
Mapping for the block types to the most fine grain dof types.
Vector< Vector< unsigned > > Doftype_coarsen_map_coarse
Vector< Vector< unsigned > > Doftype_coarsen_map_fine
Vector< LinearAlgebraDistribution * > Internal_block_distribution_pt
Storage for the default distribution for each internal block.
Vector< LinearAlgebraDistribution * > Dof_block_distribution_pt
Vector< unsigned > Allow_multiple_element_type_in_mesh
Vector< const Mesh * > Mesh_pt
Vector< unsigned > Ndof_types_in_mesh
unsigned Internal_nblock_types
unsigned Internal_ndof_types
Protected Attributes inherited from oomph::Preconditioner
bool Silent_preconditioner_setup
Boolean to indicate whether or not the build should be done silently.
std::ostream * Stream_pt
Pointer to the output stream – defaults to std::cout.
Detailed Description
Sub Biharmonic Preconditioner - an exact preconditioner for the 3x3 top left hand corner sub block matrix. Used as part of the BiharmonicPreconditioner<MATRIX> . By default this uses the BBD (block-bordered-diagonal/arrow-shaped) preconditioner; can also switch to full BD version (in which case all the 3x3 blocks are retained)
Constructor & Destructor Documentation
ExactSubBiharmonicPreconditioner() [1/2]
oomph::ExactSubBiharmonicPreconditioner::ExactSubBiharmonicPreconditioner (BiharmonicPreconditioner * master_prec_pt, const bool & retain_all_blocks = false) inline
Constructor - for a preconditioner acting as a sub preconditioner.
       : Retain_all_blocks(retain_all_blocks)
     {
       // Block mapping for ExactSubBiharmonicPreconditioner
       Vector<unsigned> block_lookup(3);
       block_lookup[0] = 0;
       block_lookup[1] = 1;
       block_lookup[2] = 2;
       // set as subsidiary block preconditioner
       this->turn_into_subsidiary_block_preconditioner(master_prec_pt,
                                                       block_lookup);
       // null the Sub preconditioner pt
       Sub_preconditioner_pt = 0;
     }
References Sub_preconditioner_pt, and oomph::BlockPreconditioner< CRDoubleMatrix >::turn_into_subsidiary_block_preconditioner().
~ExactSubBiharmonicPreconditioner()
oomph::ExactSubBiharmonicPreconditioner::~ExactSubBiharmonicPreconditioner () inline
destructor deletes the exact preconditioner
     {
       this->clean_up_memory();
     }
References clean_up_memory().
ExactSubBiharmonicPreconditioner() [2/2]
oomph::ExactSubBiharmonicPreconditioner::ExactSubBiharmonicPreconditioner (const ExactSubBiharmonicPreconditioner &) delete
Broken copy constructor.
Member Function Documentation
clean_up_memory()
void oomph::ExactSubBiharmonicPreconditioner::clean_up_memory () inline virtual
delete the subsidiary preconditioner pointer
Reimplemented from oomph::Preconditioner.
     {
       delete Sub_preconditioner_pt;
       Sub_preconditioner_pt = 0;
     }
References Sub_preconditioner_pt.
Referenced by setup(), and ~ExactSubBiharmonicPreconditioner().
operator=()
void oomph::ExactSubBiharmonicPreconditioner::operator= (const ExactSubBiharmonicPreconditioner &) delete
Broken assignment operator.
preconditioner_solve()
void oomph::ExactSubBiharmonicPreconditioner::preconditioner_solve (const DoubleVector & r, DoubleVector & z) virtual
Apply preconditioner to r.
preconditioner solve for the exact sub biharmonic preconditioner
Implements oomph::Preconditioner.
   {
     // vectors for use within the sub preconditioner
     DoubleVector sub_r;
     DoubleVector sub_z;
     // get the sub r vector
     get_block_ordered_preconditioner_vector(r, sub_r);
     // solve the preconditioner
     Sub_preconditioner_pt->preconditioner_solve(sub_r, sub_z);
     // return the sub z vector to the master z vector
     return_block_ordered_preconditioner_vector(sub_z, z);
   }
References oomph::BlockPreconditioner< CRDoubleMatrix >::get_block_ordered_preconditioner_vector(), oomph::Preconditioner::preconditioner_solve(), UniformPSDSelfTest::r, oomph::BlockPreconditioner< CRDoubleMatrix >::return_block_ordered_preconditioner_vector(), and Sub_preconditioner_pt.
setup()
void oomph::ExactSubBiharmonicPreconditioner::setup () virtual
Setup the preconditioner.
setup for the exact sub biharmonic preconditioner
Implements oomph::Preconditioner.
   {
     // clean up memory first
     this->clean_up_memory();
     // setup
     this->block_setup();
     // Number of block types
     unsigned n_block_types = this->nblock_types();
     // check for required number of blocks
 #ifdef PARANOID
     if (n_block_types != 3)
     {
       std::ostringstream error_message;
       error_message
         << "This preconditioner requires 3 block types.\n"
         << "It is sub preconditioner for the BiharmonicPreconditioner.\n";
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Data type indicating which blocks from the preconditioner matrix we want
     VectorMatrix<BlockSelector> required_blocks(n_block_types, n_block_types);
     // boolean indicating if we want the block or not, stored for readability.
     // Initially this is set to true for all blocks. Later we select which
     // blocks we do not want.
     const bool want_block = true;
     for (unsigned b_i = 0; b_i < n_block_types; b_i++)
     {
       for (unsigned b_j = 0; b_j < n_block_types; b_j++)
       {
         required_blocks[b_i][b_j].select_block(b_i, b_j, want_block);
       }
     }
     // Which blocks do we not want?
     if (!Retain_all_blocks)
     {
       required_blocks[1][2].do_not_want_block();
       required_blocks[2][1].do_not_want_block();
     }
     // Get the preconditioner matrix as defined by required_blocks
     CRDoubleMatrix preconditioner_matrix =
       this->get_concatenated_block(required_blocks);
     // setup the preconditioner
     Sub_preconditioner_pt = new SuperLUPreconditioner;
     Sub_preconditioner_pt->setup(&preconditioner_matrix);
     // preconditioner_matrix will now go out of scope (and is destroyed).
   }
References oomph::BlockPreconditioner< CRDoubleMatrix >::block_setup(), clean_up_memory(), oomph::BlockPreconditioner< CRDoubleMatrix >::get_concatenated_block(), oomph::BlockPreconditioner< CRDoubleMatrix >::nblock_types(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, Retain_all_blocks, oomph::Preconditioner::setup(), and Sub_preconditioner_pt.
Member Data Documentation
Retain_all_blocks
bool oomph::ExactSubBiharmonicPreconditioner::Retain_all_blocks
Boolean indicating that all blocks are to be retained (defaults to false)
Referenced by setup().
Sub_preconditioner_pt
Preconditioner* oomph::ExactSubBiharmonicPreconditioner::Sub_preconditioner_pt
Referenced by clean_up_memory(), ExactSubBiharmonicPreconditioner(), preconditioner_solve(), and setup().
The documentation for this class was generated from the following files:
biharmonic_preconditioner.h
biharmonic_preconditioner.cc