MercuryDPM: MovingWallUnitTest.cpp File Reference
MovingWallUnitTest.cpp File Reference
#include <cmath>
#include <iostream>
#include <iomanip>
#include <Logger.h>
#include "DPMBase.h"
#include "Species/LinearViscoelasticSlidingFrictionSpecies.h"
#include "Walls/InfiniteWall.h"
Classes
class MovingWall
class MovingWallReference
In the reference case the particle just moves two times as fast.
class MovingWallSimpleIntegration
class MovingWallPrescribedPosition
class MovingWallPrescribedVelocity
class MovingWallPrescribedPositionPrescribedVelocity
class MovingWallTangential
class MovingWallTangentialReference
In the reference case the particle just moves two times as fast.
class MovingWallTangentialSimpleIntegration
class MovingWallTangentialPrescribedPosition
class MovingWallTangentialPrescribedVelocity
class MovingWallTangentialPrescribedPositionPrescribedVelocity
Functions
void compareParticles (BaseParticle *Ptest, BaseParticle *Pref, double absError, Vec3D positionDifference, Vec3D velocityDifference, Quaternion orientationDifference, Vec3D AngularVelocityDifference)
int main (int argc UNUSED, char *argv[] UNUSED)
Function Documentation
compareParticles()
void compareParticles (BaseParticle * Ptest, BaseParticle * Pref, double absError, Vec3D positionDifference, Vec3D velocityDifference, Quaternion orientationDifference, Vec3D AngularVelocityDifference)
 {
     if (!mathsFunc::isEqual(Ptest->getPosition(), Pref->getPosition() + positionDifference, absError))
     {
         logger(FATAL, "The particle has the wrong position. It is %, however is should be %, the difference is %", Ptest->getPosition(), Pref->getPosition() + positionDifference, Ptest->getPosition() - Pref->getPosition() - positionDifference);
     }
     if (!mathsFunc::isEqual(Ptest->getVelocity(), Pref->getVelocity() + velocityDifference, absError))
     {
         logger(FATAL, "The particle has the wrong velocity. It is %, however is should be %, the difference is %", Ptest->getVelocity(), Pref->getVelocity() + velocityDifference, Ptest->getVelocity() - Pref->getVelocity() - velocityDifference);
     }
     if (!mathsFunc::isEqual(Ptest->getOrientation(), Pref->getOrientation() + orientationDifference, absError))
     {
         logger(FATAL, "The particle has the wrong orientation. It is %, however is should be %, the difference is %", Ptest->getOrientation(), Pref->getOrientation() + orientationDifference, Ptest->getOrientation() - Pref->getOrientation() - orientationDifference);
     }
     if (!mathsFunc::isEqual(Ptest->getAngularVelocity(), Pref->getAngularVelocity() + AngularVelocityDifference, absError))
     {
         logger(FATAL, "The particle has the wrong angular velocity. It is %, however is should be %, the difference is %", Ptest->getAngularVelocity(), Pref->getAngularVelocity() + AngularVelocityDifference, Ptest->getAngularVelocity() - Pref->getAngularVelocity() - AngularVelocityDifference);
     }
 }
References FATAL, BaseInteractable::getAngularVelocity(), BaseInteractable::getOrientation(), BaseInteractable::getPosition(), BaseInteractable::getVelocity(), mathsFunc::isEqual(), and logger.
Referenced by main().
main()
int main (int argc UNUSED, char *argv[] UNUSED)
 {
     {
         MovingWallReference problem0;
         problem0.setName("MovingWallUnitTest_Normal_Reference");
         problem0.solve();
         MovingWallSimpleIntegration problem1;
         problem1.setName("MovingWallUnitTest_Normal_SimpleIntegration");
         problem1.solve();
         MovingWallPrescribedPosition problem2;
         problem2.setName("MovingWallUnitTest_Normal_PrescribedPosition");
         problem2.solve();
         MovingWallPrescribedVelocity problem3;
         problem3.setName("MovingWallUnitTest_Normal_PrescribedVelocity");
         problem3.solve();
         MovingWallPrescribedPositionPrescribedVelocity problem4;
         problem4.setName("MovingWallUnitTest_Normal_PrescribedPositionPrescribedVelocity");
         problem4.solve();
         Vec3D positionDifference = Vec3D(0.0, 0.0, problem0.getTime());
         Vec3D velocityDifference = Vec3D(0.0, 0.0, 1.0);
         Quaternion orientationDifference = {0,0,0,0};
         Vec3D angularVelocityDifference = Vec3D(0.0, 0.0, 0.0);
         compareParticles(problem1.particleHandler.getLastObject(), problem0.particleHandler.getLastObject(), 1e-10, positionDifference, velocityDifference, orientationDifference, angularVelocityDifference);
         compareParticles(problem2.particleHandler.getLastObject(), problem0.particleHandler.getLastObject(), 1e-10, positionDifference, velocityDifference, orientationDifference, angularVelocityDifference);
         compareParticles(problem3.particleHandler.getLastObject(), problem0.particleHandler.getLastObject(), 1e-10, positionDifference, velocityDifference, orientationDifference, angularVelocityDifference);
         compareParticles(problem4.particleHandler.getLastObject(), problem0.particleHandler.getLastObject(), 1e-10, positionDifference, velocityDifference, orientationDifference, angularVelocityDifference);
     }
     {
         MovingWallTangentialReference problem5;
         problem5.setName("MovingWallUnitTest_Tangential_Reference");
         problem5.solve();
         MovingWallTangentialSimpleIntegration problem6;
         problem6.setName("MovingWallUnitTest_Tangential_SimpleIntegration");
         problem6.solve();
         MovingWallTangentialPrescribedPosition problem7;
         problem7.setName("MovingWallUnitTest_Tangential_PrescribedPosition");
         problem7.solve();
         MovingWallTangentialPrescribedVelocity problem8;
         problem8.setName("MovingWallUnitTest_Tangential_PrescribedVelocity");
         problem8.solve();
         MovingWallTangentialPrescribedPositionPrescribedVelocity problem9;
         problem9.setName("MovingWallUnitTest_Tangential_PrescribedPositionPrescribedVelocity");
         problem9.solve();
         Vec3D positionDifference = Vec3D(problem5.getTime(), 0.0, 0.0);
         Vec3D velocityDifference = Vec3D(1.0, 0.0, 0.0);
         Quaternion orientationDifference = {0,0,0,0};
         Vec3D angularVelocityDifference = Vec3D(0.0, 0.0, 0.0);
         compareParticles(problem6.particleHandler.getLastObject(), problem5.particleHandler.getLastObject(), 1e-10, positionDifference, velocityDifference, orientationDifference, angularVelocityDifference);
         compareParticles(problem7.particleHandler.getLastObject(), problem5.particleHandler.getLastObject(), 1e-10, positionDifference, velocityDifference, orientationDifference, angularVelocityDifference);
         compareParticles(problem8.particleHandler.getLastObject(), problem5.particleHandler.getLastObject(), 1e-10, positionDifference, velocityDifference, orientationDifference, angularVelocityDifference);
         compareParticles(problem9.particleHandler.getLastObject(), problem5.particleHandler.getLastObject(), 1e-10, positionDifference, velocityDifference, orientationDifference, angularVelocityDifference);
     }
     /*
     diff ../../../Source/Drivers/UnitTests/SelfTestData/movingWall.data MovingWallUnitTest_Normal_PrescribedPosition.data
     diff ../../../Source/Drivers/UnitTests/SelfTestData/movingWall.data MovingWallUnitTest_Normal_PrescribedVelocity.data
     diff ../../../Source/Drivers/UnitTests/SelfTestData/movingWall.data MovingWallUnitTest_Normal_PrescribedPositionPrescribedVelocity.data
     diff ../../../Source/Drivers/UnitTests/SelfTestData/movingWall.data MovingWallUnitTest_Normal_SimpleIntegration.data
     diff ../../../Source/Drivers/UnitTests/SelfTestData/noMovingWall.data MovingWallUnitTest_Normal_Reference.data
     diff ../../../Source/Drivers/UnitTests/SelfTestData/movingWallTangential.data MovingWallUnitTest_Tangential_PrescribedPosition.data
     diff ../../../Source/Drivers/UnitTests/SelfTestData/movingWallTangential.data MovingWallUnitTest_Tangential_PrescribedVelocity.data
     diff ../../../Source/Drivers/UnitTests/SelfTestData/movingWallTangential.data MovingWallUnitTest_Tangential_PrescribedPositionPrescribedVelocity.data
     diff ../../../Source/Drivers/UnitTests/SelfTestData/movingWallTangential.data MovingWallUnitTest_Tangential_SimpleIntegration.data
     diff ../../../Source/Drivers/UnitTests/SelfTestData/noMovingWallTangential.data MovingWallUnitTest_Tangential_Reference.data
     */
     return 0;
 }
References compareParticles(), e(), BaseHandler< T >::getLastObject(), DPMBase::getTime(), DPMBase::particleHandler, DPMBase::setName(), and DPMBase::solve().