MercuryDPM: spine_channel.cc File Reference
spine_channel.cc File Reference
#include "generic.h"
#include "navier_stokes.h"
#include "meshes/channel_spine_mesh.h"
Classes
class SinusoidalWall
class ChannelSpineFlowProblem< ELEMENT >
Namespaces
Global_Physical_Variables
Global variables.
Functions
int main ()
Driver for channel flow problem with spine mesh.
void doc_sparse_node_update ()
Create the files to illustrate the sparse node update operation.
Function Documentation
doc_sparse_node_update()
void doc_sparse_node_update ()
Create the files to illustrate the sparse node update operation.
 {
  // Set output directory
  DocInfo doc_info;
  doc_info.set_directory("RESLT");
  // Setup mesh
  // # of elements in x-direction in left region
  unsigned Nx0=1;
  // # of elements in x-direction in centre region
  unsigned Nx1=5;
  // # of elements in x-direction in right region
  unsigned Nx2=1;
  // # of elements in y-direction
  unsigned Ny=5;
  // Domain length in x-direction in left region
  double Lx0=0.5;
  // Domain length in x-direction in centre region
  double Lx1=1.0;
  // Domain length in x-direction in right region
  double Lx2=0.5;
  // Domain length in y-direction
  double Ly=1.0;
  double amplitude_upper = -0.4*Ly;
  double zeta_min=Lx0;
  double zeta_max=Lx0+Lx1;
  GeomObject* UpperWall =
   new SinusoidalWall(Ly,amplitude_upper,zeta_min,zeta_max);
  // Build and assign mesh
  ChannelSpineMesh<SpineElement<QTaylorHoodElement<2> > >* mesh_pt =
   new ChannelSpineMesh<SpineElement<QTaylorHoodElement<2> > >(Nx0,Nx1,Nx2,Ny,
                                                              Lx0,Lx1,Lx2,Ly,
                                                              UpperWall);
  // Update *all* nodal positions
  mesh_pt->node_update();
  // Change the amplitude
  dynamic_cast<SinusoidalWall*>(mesh_pt->wall_pt())->amplitude()=0.5;
  unsigned count=0;
  ofstream some_file;
  char filename[100];
  // Number of plot points
  unsigned npts=5;
  // Output solution
  sprintf(filename,"%s/mesh_update%i.dat",doc_info.directory().c_str(),
          count);
  count++;
  // Loop over spines in centre
  unsigned n_node = mesh_pt->nnode();
  for (unsigned inode=0;inode<n_node;inode++)
   {
    SpineNode* node_pt=dynamic_cast<SpineNode*>(
     mesh_pt->node_pt(inode));
    if (node_pt->node_update_fct_id()==1)
     {
      node_pt->node_update();
      // Output solution
      some_file.open(filename);
      sprintf(filename,"%s/mesh_update%i.dat",doc_info.directory().c_str(),
              count);
      count++;
      mesh_pt->output(some_file,npts);
      some_file.close();
     }
   }
 }
References oomph::DocInfo::directory(), MergeRestartFiles::filename, Global_Parameters::Ly, oomph::Mesh::nnode(), oomph::SpineMesh::node_pt(), oomph::SpineMesh::node_update(), oomph::SpineNode::node_update(), oomph::SpineNode::node_update_fct_id(), GlobalParameters::Ny, oomph::Mesh::output(), oomph::DocInfo::set_directory(), and oomph::ChannelSpineMesh< ELEMENT >::wall_pt().
main()
int main ()
Driver for channel flow problem with spine mesh.
 {
  // Set output directory
  DocInfo doc_info;
  doc_info.set_directory("RESLT");
  doc_info.number()=0;
  // Solve problem with Taylor Hood elements
  //---------------------------------------
  {
   //Build problem
   ChannelSpineFlowProblem<SpineElement<QTaylorHoodElement<2> > >
    problem;
   // Solve the problem with automatic adaptation
   problem.newton_solve();
   //Output solution
   problem.doc_solution(doc_info);
   // Step number
   doc_info.number()++;
  } // end of Taylor Hood elements
  // Solve problem with Crouzeix Raviart elements
  //--------------------------------------------
  {
   // Build problem
   ChannelSpineFlowProblem<SpineElement<QCrouzeixRaviartElement<2> > >
    problem;
   // Solve the problem with automatic adaptation
   problem.newton_solve();
   //Output solution
   problem.doc_solution(doc_info);
   // Step number
   doc_info.number()++;
  } // end of Crouzeix Raviart elements
 } // end_of_main
References oomph::DocInfo::number(), problem, and oomph::DocInfo::set_directory().