MercuryDPM: two_dim.cc File Reference
two_dim.cc File Reference
#include "generic.h"
#include "./Thomo_lin_elasticity_elements.h"
#include "meshes/triangle_mesh.h"
Classes
class CompareNodeCoordinatesX
class CompareNodeCoordinatesY
class HomogenisationProblem< ELEMENT >
Problem class to simulate viscous inclusion propagating along 2D channel.
Namespaces
Problem_Parameter
Namespace for Problem Parameter.
Functions
void Problem_Parameter::bulk_elasticity_tensor_pt (const Vector< double > &x, ElasticityTensor *&E_pt)
void Problem_Parameter::fibre_elasticity_tensor_pt (const Vector< double > &x, ElasticityTensor *&E_pt)
int main (int argc, char **argv)
Driver code for moving block problem.
Variables
double Problem_Parameter::P0 = 3.0
double Problem_Parameter::M0 = 1.3
double Problem_Parameter::Pr = 23.5
double Problem_Parameter::Mr = 30.0
ElasticityTensor * Problem_Parameter::E_bulk_pt
ElasticityTensor * Problem_Parameter::E_fibre_pt
Function Documentation
main()
int main (int argc , char ** argv)
Driver code for moving block problem.
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Define possible command line arguments and parse the ones that
  // were actually specified
  // Validation?
  CommandLineArgs::specify_command_line_flag("--validation");
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  {
   using namespace Problem_Parameter;
   Vector<double> lame_bulk(2);
   lame_bulk[0] = P0/M0; lame_bulk[1] = 1.0;
   E_bulk_pt = new IsotropicElasticityTensor(lame_bulk);
   Vector<double> lame_fibre(2);
   lame_fibre[0] = Pr/M0; lame_fibre[1] = Mr/M0;
   E_fibre_pt = new IsotropicElasticityTensor(lame_fibre);
   }
  // Create problem in initial configuration
  // which solves the required problem
  HomogenisationProblem<THomogenisedLinearElasticityElement<2,3> > problem;
 } //End of main
References oomph::CommandLineArgs::doc_specified_flags(), Problem_Parameter::E_bulk_pt, Problem_Parameter::E_fibre_pt, Problem_Parameter::M0, Problem_Parameter::Mr, Problem_Parameter::P0, oomph::CommandLineArgs::parse_and_assign(), Problem_Parameter::Pr, problem, Flag_definition::setup(), and oomph::CommandLineArgs::specify_command_line_flag().