MercuryDPM: CGCoordinates::R Class Reference
CGCoordinates::R Class Reference
Defines the non-averaged directions on which spatial coarse-graining is applied (the x-direction for R); all other directions are averaged
over homogeneously.
#include <R.h>
Public Member Functions
void write (std::ostream &os) const
Writes the coordinates in human-readable form to an ostream.
Mdouble getDistanceSquared (const Vec3D &p) const
Returns the square of the distance between the particle p and the current CGPoint, in the non-averaged directions.
void setR (Mdouble r)
Returns the position of the current CGPoint, in the non-averaged directions.
const Mdouble getR () const
Mdouble getINormal (const BaseInteraction &c, const Vec3D &normal) const
For the Interaction between particles/walls P and I, this function returns the dot product between the normal vector of the interaction and the branch vector from the current CGPoint towards I.
Mdouble getPNormal (const BaseInteraction &c, const Vec3D &normal) const
For the Interaction between particles/walls P and I, this function returns the dot product between the normal vector of the interaction and the branch vector from the current CGPoint towards P.
Mdouble getCNormal (const BaseInteraction &c, const Vec3D &normal) const
For the Interaction between particles/walls P and I, this function returns the dot product between the normal vector of the interaction and the branch vector from the current CGPoint towards the contact point.
Mdouble getWeight () override
Static Public Member Functions
static void writeNames (std::ostream &os)
Writes the coordinate names in human-readable form to an ostream.
static Mdouble getVolumeOfAveragedDimensions (const Vec3D &min, const Vec3D &max)
returns the factor the CGFunction has to be divided by, due to integrating the variables over the averaged dimensions, 1.0 for XYZ.
static Mdouble getLength (const Vec3D &p)
Returns the length of the input vector in the non-averaged directions.
static void normalisePolynomialCoefficients (std::vector< Mdouble > &coefficients, Mdouble cutoff)
Normalises the coefficients of Polynomial CGFunction such that the integral over all non-averaged dimensions is unity.
static Mdouble getDomainVolume (const Vec3D &min, const Vec3D &max)
static bool isResolvedIn (unsigned i)
static std::string getName ()
Static Public Member Functions inherited from CGCoordinates::Base_X_Y_Z
static Mdouble getGaussPrefactor (Mdouble width, Mdouble cutoff)
Computes the prefactor of the Gauss CGFunction, which is dependent on the number of non-averaged dimensions.
static Mdouble getGaussIntegralPrefactor (Mdouble distance, Mdouble width, Mdouble cutoff)
Computes the prefactor of the Gauss line integral, which is dependent on the number of non-averaged dimensions.
static void normalisePolynomialCoefficients (std::vector< Mdouble > &coefficients, Mdouble cutoff)
Normalises the coefficients of Polynomial CGFunction such that the integral over all non-averaged dimensions is unity.
static const unsigned countVariables ()
Static Public Member Functions inherited from CGCoordinates::BaseCoordinates
static Mdouble getDomainVolume (const Vec3D &min, const Vec3D &max)
Protected Attributes
Mdouble r_
Detailed Description
Defines the non-averaged directions on which spatial coarse-graining is applied (the x-direction for R); all other directions are averaged
over homogeneously.
See XYZ for details.
Member Function Documentation
getCNormal()
Mdouble R::getCNormal (const BaseInteraction & c, const Vec3D & normal) const
For the Interaction between particles/walls P and I, this function returns the dot product between the normal vector of the interaction and the branch vector from the current CGPoint towards the contact point.
 {
     if (Vec3D::dot(c.getContactPoint(), normal) > 0)
     {
         return (getLength(c.getContactPoint()) - r_);
     }
     else
     {
         return -(getLength(c.getContactPoint()) - r_);
     }
 }
References calibrate::c, Vec3D::dot(), getLength(), WallFunction::normal(), and r_.
getDistanceSquared()
Mdouble R::getDistanceSquared (const Vec3D & p) const
Returns the square of the distance between the particle p and the current CGPoint, in the non-averaged directions.
 {
     return mathsFunc::square(getLength(p) - r_);
 }
References getLength(), p, r_, and mathsFunc::square().
getDomainVolume()
Mdouble R::getDomainVolume (const Vec3D & min, const Vec3D & max) static
 {
     //note, the x-coordinate represents the r-coordinate here
     return constants::pi * (max.X * max.X - min.X * min.X) * (max.Z - min.Z);
 }
References max, min, and constants::pi.
getINormal()
Mdouble R::getINormal (const BaseInteraction & c, const Vec3D & normal) const
For the Interaction between particles/walls P and I, this function returns the dot product between the normal vector of the interaction and the branch vector from the current CGPoint towards I.
 {
     if (Vec3D::dot(c.getContactPoint(), normal) > 0)
     {
         return (getLength(c.getI()->getPosition()) - r_);
     }
     else
     {
         return -(getLength(c.getI()->getPosition()) - r_);
     }
 }
References calibrate::c, Vec3D::dot(), getLength(), WallFunction::normal(), and r_.
getLength()
Mdouble R::getLength (const Vec3D & p) static
Returns the length of the input vector in the non-averaged directions.
Parameters
[in] p vector whose length should be determined
Returns
length of the vector in the non-averaged directions
Todo:
 {
     return sqrt(p.X * p.X + p.Y * p.Y);
 }
References p, and sqrt().
Referenced by getCNormal(), getDistanceSquared(), getINormal(), and getPNormal().
getName()
std::string R::getName () static
 {
     return "R";
 }
getPNormal()
Mdouble R::getPNormal (const BaseInteraction & c, const Vec3D & normal) const
For the Interaction between particles/walls P and I, this function returns the dot product between the normal vector of the interaction and the branch vector from the current CGPoint towards P.
 {
     if (Vec3D::dot(c.getContactPoint(), normal) > 0)
     {
         return (getLength(c.getP()->getPosition()) - r_);
     }
     else
     {
         return -(getLength(c.getP()->getPosition()) - r_);
     }
 }
References calibrate::c, Vec3D::dot(), getLength(), WallFunction::normal(), and r_.
getR()
const Mdouble CGCoordinates::R::getR () const inline
     { return r_; }
References r_.
getVolumeOfAveragedDimensions()
Mdouble R::getVolumeOfAveragedDimensions (const Vec3D & min, const Vec3D & max) static
returns the factor the CGFunction has to be divided by, due to integrating the variables over the averaged dimensions, 1.0 for XYZ.
 {
     return (max.Z - min.Z);//2*constants::pi
 }
References max, and min.
getWeight()
Mdouble R::getWeight () override virtual
returns the weight function needed in getTotal (required as functions cannot be)
Returns
Reimplemented from CGCoordinates::BaseCoordinates.
 {
     return r_;
 }
References r_.
isResolvedIn()
static bool CGCoordinates::R::isResolvedIn (unsigned i) inline static
 {return i==0?true:false;}
References i.
normalisePolynomialCoefficients()
void R::normalisePolynomialCoefficients (std::vector< Mdouble > & coefficients, Mdouble cutoff) static
Normalises the coefficients of Polynomial CGFunction such that the integral over all non-averaged dimensions is unity.
The volume is computed as
\[volume=\int_0^1\sum_{i=1}^n c_i r^i 2 dr = 2 \sum_{i=1}^n c_i/(i+1) \]
Todo:
 {
     Mdouble volume = 0.0;
     for (std::size_t i = 0; i < coefficients.size(); i++)
         volume += coefficients[i] / static_cast<Mdouble>(i + 1);
     volume *= 2.0 * cutoff;
     for (double& coefficient : coefficients)
         coefficient /= volume;
 }
References i.
setR()
void R::setR (Mdouble r)
Returns the position of the current CGPoint, in the non-averaged directions.
 {
     r_ = r;
 }
References UniformPSDSelfTest::r, and r_.
write()
void R::write (std::ostream & os) const
Writes the coordinates in human-readable form to an ostream.
 {
     os << r_ << ' ';
 }
References r_.
writeNames()
void R::writeNames (std::ostream & os) static
Writes the coordinate names in human-readable form to an ostream.
 {
     os << "r ";
 }
Member Data Documentation
r_
Mdouble CGCoordinates::R::r_ protected
The x-position of the current CGPoint.
Referenced by getCNormal(), getDistanceSquared(), getINormal(), getPNormal(), getR(), getWeight(), setR(), and write().
The documentation for this class was generated from the following files:
R.h
R.cc