MercuryDPM: mesh_from_triangle_poisson.cc File Reference
mesh_from_triangle_poisson.cc File Reference
#include "generic.h"
#include "poisson.h"
#include "meshes/triangle_mesh.h"
Classes
class PoissonProblem< ELEMENT >
Micky mouse Poisson problem.
Namespaces
TanhSolnForPoisson
Namespace for exact solution for Poisson equation with "sharp step".
Functions
void TanhSolnForPoisson::get_exact_u (const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void TanhSolnForPoisson::get_exact_u (const Vector< double > &x, double &u)
Exact solution as a scalar.
void TanhSolnForPoisson::get_source (const Vector< double > &x, double &source)
Source function to make it an exact solution.
int main (int argc, char *argv[])
Demonstrate how to solve Poisson problem.
Function Documentation
main()
int main (int argc , char * argv[])
Demonstrate how to solve Poisson problem.
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Check number of command line arguments: Need exactly two.
  if (argc!=4)
   {
    std::string error_message =
     "Wrong number of command line arguments.\n";
    error_message +=
     "Must specify the following file names  \n";
    error_message +=
     "filename.node then filename.ele then filename.poly\n";
    throw OomphLibError(error_message,
                        OOMPH_CURRENT_FUNCTION,
                        OOMPH_EXCEPTION_LOCATION);
   }
 #ifdef ADAPT
  const unsigned max_adapt = 3;
 #endif
  // Convert arguments to strings that specify the input file names
  string node_file_name(argv[1]);
  string element_file_name(argv[2]);
  string poly_file_name(argv[3]);
  // Label for output
  DocInfo doc_info;
  // Output directory
  doc_info.set_directory("RESLT");
 #ifndef ADAPT
  // Do the problem with cubic elements
  //-----------------------------------
  {
   cout << std::endl << "Cubic elements" << std::endl;
   cout <<         "==============" << std::endl << std::endl;
   //Set up the problem
   PoissonProblem<TPoissonElement<2,4> >
    problem(&TanhSolnForPoisson::get_source,node_file_name,
            element_file_name,
            poly_file_name);
   // Solve the problem
   problem.newton_solve();
   //Output solution
   problem.doc_solution(doc_info);
   //Increment counter for solutions
   doc_info.number()++;
  }
 #endif
  // Do the problem with quadratic elements
  //---------------------------------------
  {
   cout << std::endl  << "Quadratic elements" << std::endl;
   cout <<               "===================" << std::endl << std::endl;
 #ifdef ADAPT
   //Set up the problem
   PoissonProblem<ProjectablePoissonElement<TPoissonElement<2,3> > >
    problem(&TanhSolnForPoisson::get_source,node_file_name,
            element_file_name,
            poly_file_name);
 #else
   //Set up the problem
   PoissonProblem<TPoissonElement<2,3> >
    problem(&TanhSolnForPoisson::get_source,node_file_name,
            element_file_name,
            poly_file_name);
 #endif
 #ifdef ADAPT
   // Solve the problem with adaptation
   problem.newton_solve(max_adapt);
 #else
   // Solve the problem
   problem.newton_solve();
 #endif
   //Output solution
   problem.doc_solution(doc_info);
   //Increment counter for solutions
   doc_info.number()++;
  }
  // Do the problem with linear elements
  //------------------------------------
  {
   cout << std::endl << "Linear elements" << std::endl;
   cout <<              "===============" << std::endl << std::endl;
 #ifdef ADAPT
   //Set up the problem
   PoissonProblem<ProjectablePoissonElement<TPoissonElement<2,2> > >
    problem(&TanhSolnForPoisson::get_source,node_file_name,
            element_file_name,
            poly_file_name);
 #else
   //Set up the problem
   PoissonProblem<TPoissonElement<2,2> >
    problem(&TanhSolnForPoisson::get_source,node_file_name,
            element_file_name,
            poly_file_name);
 #endif
 #ifdef ADAPT
   // Solve the problem with adaptation
   problem.newton_solve(max_adapt);
 #else
   // Solve the problem
   problem.newton_solve();
 #endif
   //Output solution
   problem.doc_solution(doc_info);
   //Increment counter for solutions
   doc_info.number()++;
  }
 }
References TanhSolnForPoisson::get_source(), oomph::DocInfo::number(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, problem, oomph::DocInfo::set_directory(), Flag_definition::setup(), and oomph::Global_string_for_annotation::string().