MercuryDPM: oomph::LowStorageRungeKutta< ORDER > Class Template Reference
oomph::LowStorageRungeKutta< ORDER > Class Template Reference
#include <explicit_timesteppers.h>
Public Member Functions
LowStorageRungeKutta ()
Constructor, set the type.
LowStorageRungeKutta (const LowStorageRungeKutta &)=delete
Broken copy constructor.
void operator= (const LowStorageRungeKutta &)=delete
Broken assignment operator.
void timestep (ExplicitTimeSteppableObject *const &object_pt, const double &dt)
Function that is used to advance the solution by time dt.
LowStorageRungeKutta ()
void timestep (ExplicitTimeSteppableObject *const &object_pt, const double &dt)
Pure virtual function that is used to advance time in the object.
Public Member Functions inherited from oomph::ExplicitTimeStepper
ExplicitTimeStepper ()
Empty Constructor.
ExplicitTimeStepper (const ExplicitTimeStepper &)=delete
Broken copy constructor.
void operator= (const ExplicitTimeStepper &)=delete
Broken assignment operator.
virtual ~ExplicitTimeStepper ()
Empty virtual destructor — no memory is allocated in this class.
Private Attributes
Vector< double > A
Vector< double > B
Vector< double > C
Additional Inherited Members
Protected Attributes inherited from oomph::ExplicitTimeStepper
std::string Type
Detailed Description
template<unsigned ORDER>
class oomph::LowStorageRungeKutta< ORDER >
=========================================================== Runge Kutta Timestepping that uses low storage
Constructor & Destructor Documentation
LowStorageRungeKutta() [1/3]
template<unsigned ORDER> oomph::LowStorageRungeKutta< ORDER >::LowStorageRungeKutta
Constructor, set the type.
   {
     Type = "LowStorageRungeKutta";
   }
LowStorageRungeKutta() [2/3]
template<unsigned ORDER> oomph::LowStorageRungeKutta< ORDER >::LowStorageRungeKutta (const LowStorageRungeKutta< ORDER > &) delete
Broken copy constructor.
LowStorageRungeKutta() [3/3]
oomph::LowStorageRungeKutta< 4 >::LowStorageRungeKutta ()
   {
     Type = "LowStorageRungeKutta";
     A.resize(5);
     A[0] = 0.0;
     A[1] = -567301805773.0 / 1357537059087.0;
     A[2] = -2404267990393.0 / 2016746695238.0;
     A[3] = -3550918686646.0 / 2091501179385.0;
     A[4] = -1275806237668.0 / 842570457699.0;
     B.resize(5);
     B[0] = 1432997174477.0 / 9575080441755.0;
     B[1] = 5161836677717.0 / 13612068292357.0;
     B[2] = 1720146321549.0 / 2090206949498.0;
     B[3] = 3134564353537.0 / 4481467310338.0;
     B[4] = 2277821191437.0 / 14882151754819.0;
     C.resize(5);
     C[0] = B[0];
     C[1] = 2526269341429.0 / 6820363962896.0;
     C[2] = 2006345519317.0 / 3224310063776.0;
     C[3] = 2802321613138.0 / 2924317926251.0;
     C[4] = 1.0;
   }
References Eigen::PlainObjectBase< Derived >::resize().
Member Function Documentation
operator=()
template<unsigned ORDER> void oomph::LowStorageRungeKutta< ORDER >::operator= (const LowStorageRungeKutta< ORDER > &) delete
Broken assignment operator.
timestep() [1/2]
void oomph::LowStorageRungeKutta< 4 >::timestep (ExplicitTimeSteppableObject *const & object_pt, const double & dt) virtual
Pure virtual function that is used to advance time in the object.
Implements oomph::ExplicitTimeStepper.
   {
     object_pt->actions_before_explicit_timestep();
     // Store the initial time
     const double initial_time = object_pt->time();
     // Temporary storage
     DoubleVector k;
     // Temporary storage for the inverse mass matrix multiplied by the residuals
     DoubleVector minv_res;
     // Loop over the number of steps in the scheme
     for (unsigned i = 0; i < 5; i++)
     {
       object_pt->actions_before_explicit_stage();
       // Get the inverse mass matrix multiplied by the current value
       // of the residuals
       object_pt->get_dvaluesdt(minv_res);
       // Get the values of k
       const unsigned n_dof = minv_res.nrow();
       // First time round resize k and initialise to zero
       if (i == 0)
       {
         k.build(minv_res.distribution_pt(), 0.0);
       }
       // Now construct the next value of k
       for (unsigned n = 0; n < n_dof; n++)
       {
         k[n] *= A[i];
         k[n] += dt * minv_res[n];
       }
       // Add to the residuals
       object_pt->add_to_dofs(B[i], k);
       // Set the new time
       object_pt->time() = initial_time + C[i] * dt;
       object_pt->actions_after_explicit_stage();
     }
     object_pt->actions_after_explicit_timestep();
   }
References oomph::ExplicitTimeSteppableObject::actions_after_explicit_stage(), oomph::ExplicitTimeSteppableObject::actions_after_explicit_timestep(), oomph::ExplicitTimeSteppableObject::actions_before_explicit_stage(), oomph::ExplicitTimeSteppableObject::actions_before_explicit_timestep(), oomph::ExplicitTimeSteppableObject::add_to_dofs(), oomph::DistributableLinearAlgebraObject::distribution_pt(), oomph::ExplicitTimeSteppableObject::get_dvaluesdt(), i, k, n, oomph::DistributableLinearAlgebraObject::nrow(), and oomph::ExplicitTimeSteppableObject::time().
timestep() [2/2]
template<unsigned ORDER> void oomph::LowStorageRungeKutta< ORDER >::timestep (ExplicitTimeSteppableObject *const & object_pt, const double & dt) virtual
Function that is used to advance the solution by time dt.
Broken default timestep for LowStorageRungeKutta.
Implements oomph::ExplicitTimeStepper.
   {
     std::ostringstream error_stream;
     error_stream << "Timestep not implemented for order " << ORDER << "\n";
     throw OomphLibError(
       error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
   }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Member Data Documentation
A
template<unsigned ORDER> Vector<double> oomph::LowStorageRungeKutta< ORDER >::A private
B
template<unsigned ORDER> Vector<double> oomph::LowStorageRungeKutta< ORDER >::B private
C
template<unsigned ORDER> Vector<double> oomph::LowStorageRungeKutta< ORDER >::C private
The documentation for this class was generated from the following files:
explicit_timesteppers.h
explicit_timesteppers.cc