MercuryDPM: driven_cavity.cc File Reference
navier_stokes/navier_stokes_with_singularity/driven_cavity.cc File Reference
#include "generic.h"
#include "navier_stokes.h"
#include "meshes/simple_rectangular_quadmesh.h"
#include "navier_stokes_elements_with_singularity.h"
#include "finite_re_perturbation.h"
Classes
class MyTaylorHoodElement
class RectangularDrivenCavityProblem< ELEMENT >
Driven cavity problem in rectangular domain.
Namespaces
Global_Physical_Variables
Global variables.
Global_Parameters
Namespace for global parameters.
Functions
double Global_Parameters::blend (const Vector< double > &x, const Vector< double > &x_c)
Blend function, centred at x_c.
Vector< double > Global_Parameters::grad_blend (const Vector< double > &x, const Vector< double > &x_c)
Gradient of blend function, centred at x_c.
Vector< double > Global_Parameters::velocity_couette (const Vector< double > &x)
Couette flow.
double Global_Parameters::pressure_couette (const Vector< double > &x)
Couette Pressure.
void Global_Parameters::exact_couette (const Vector< double > &x, Vector< double > &soln)
Combined exact solution (u,v,p)
Vector< double > Global_Parameters::velocity_pseudo_singularity_for_couette (const Vector< double > &x)
Pseudo_singularity for computation of Couette flow.
Vector< Vector< double > > Global_Parameters::grad_velocity_pseudo_singularity_for_couette (const Vector< double > &x)
Pseudo_singularity for computation of Couette flow: grad[i][j] = du_i/dx_j.
double Global_Parameters::pressure_pseudo_singularity_for_couette (const Vector< double > &x)
Pseudo_singularity for computation of Couette flow.
Vector< double > Global_Parameters::blended_velocity_pseudo_singularity_for_couette (const Vector< double > &x)
Blended Pseudo_singularity for computation of Couette flow.
Vector< Vector< double > > Global_Parameters::blended_grad_velocity_pseudo_singularity_for_couette (const Vector< double > &x)
double Global_Parameters::blended_pressure_pseudo_singularity_for_couette (const Vector< double > &x)
Blended Pseudo_singularity for computation of Couette flow.
Vector< double > Global_Parameters::velocity_singularity1 (const Vector< double > &x)
Function that computes the fitting velocity solution near the corner (0,0)
Vector< double > Global_Parameters::velocity_singularity2 (const Vector< double > &x)
Function that computes the fitting velocity solution near the corner (1,0)
Vector< Vector< double > > Global_Parameters::grad_velocity_singularity1 (const Vector< double > &coord)
Vector< Vector< double > > Global_Parameters::grad_velocity_singularity2 (const Vector< double > &coord)
double Global_Parameters::pressure_singularity1 (const Vector< double > &x)
Function that computes the fitting pressure solution near the corner (0,0)
double Global_Parameters::pressure_singularity2 (const Vector< double > &x)
Function that computes the fitting pressure solution near the corner (1,0)
Vector< double > Global_Parameters::grad_pressure_singularity1 (const Vector< double > &coord)
void Global_Parameters::analytic_solution1 (const Vector< double > &x, Vector< double > &solution)
Function that computes the fitting solutions near the corner (0,0)
void Global_Parameters::analytic_solution2 (const Vector< double > &x, Vector< double > &solution)
Function that computes the fitting solutions near the corner (1,0)
int main (int argc, char **argv)
Variables
unsigned Global_Parameters::Element_multiplier = 1
unsigned Global_Parameters::N_x =10
unsigned Global_Parameters::N_y =10
double Global_Parameters::L_x =1.0
double Global_Parameters::L_y =1.0
unsigned Global_Parameters::Direction = 1
double Global_Parameters::R_blend_inner =0.2
Inner blending radius.
double Global_Parameters::R_blend_outer =0.8
Outer blending radius.
double Global_Parameters::A_couette =1.0
Amplitude of linearly varying part.
double Global_Parameters::B_couette =1.0
Amplitude of singular part.
Vector< double > Global_Parameters::X_c_couette (2, 0.0)
Random center for blended couette pseudo singularity.
Function Documentation
main()
int main (int argc , char ** argv)
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// Driver for RectangularDrivenCavity test problem – test drive with two different types of element.
 {
 #ifdef OOMPH_HAS_MPI
  MPI_Helpers::init(argc,argv);
 #endif
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Define possible command line arguments and parse the ones that
  // were actually specified
  // Use blending?
  CommandLineArgs::specify_command_line_flag("--blend");
  // Multiplier for elements
  CommandLineArgs::specify_command_line_flag(
   "--element_multiplier",
   &Global_Parameters::Element_multiplier);
  // Multiplier for elements
  CommandLineArgs::specify_command_line_flag(
   "--re",
   &Global_Physical_Variables::Re);
  // Use higher order integration scheme?
  CommandLineArgs::specify_command_line_flag(
   "--use_high_order_integration_scheme");
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  // Check singularities and their gradients
  {
   ofstream some_file;
   some_file.open("u_sing.dat");
   unsigned nplot=100;
   some_file << "ZONE I=" << nplot << ", J=" << nplot << std::endl;
   Vector<double> x(2);
   for (unsigned i=0;i<nplot;i++)
    {
     x[0]=double(i)/double(nplot-1);
     for (unsigned j=0;j<nplot;j++)
      {
       x[1]=double(j)/double(nplot-1);
       // Get veloc
       //Vector<double> u=Global_Parameters::velocity_singularity1(x);
       //Vector<Vector<double> > grad_u=Global_Parameters::grad_velocity_singularity1(x);
       //Vector<double> u=Global_Parameters::velocity_singularity2(x);
       //Vector<Vector<double> > grad_u=Global_Parameters::grad_velocity_singularity2(x);
       Vector<double> u=Global_Parameters::blended_velocity_pseudo_singularity_for_couette(x);
       Vector<Vector<double> > grad_u=Global_Parameters::blended_grad_velocity_pseudo_singularity_for_couette(x);
       some_file << x[0] << " " << x[1] << " "
                 << u[0] << " " << u[1] << " "
                 << grad_u[0][0] << " " << grad_u[0][1] << " "
                 << grad_u[1][0] << " " << grad_u[1][1] << " "
                 << std::endl;
      }
    }
   some_file.close();
  }
  // Set up doc info
  // ---------------
  // Label for output
  DocInfo doc_info;
  // Set output directory
  doc_info.set_directory("RESLT");
 #ifdef DONT_USE_SINGULARITY
  // Build the problem with QTaylorHoodElements
  RectangularDrivenCavityProblem<MyTaylorHoodElement> problem;
 #else
  // Build the problem with singular QTaylorHoodElements
  RectangularDrivenCavityProblem<NavierStokesElementWithSingularity<
   MyTaylorHoodElement> > problem;
 #endif
  // Solve the problem
  problem.newton_solve();
  // Outpt the solution
  problem.doc_solution(doc_info);
  // Step number
  doc_info.number()++;
 } // end_of_main
References Global_Parameters::blended_grad_velocity_pseudo_singularity_for_couette(), Global_Parameters::blended_velocity_pseudo_singularity_for_couette(), oomph::CommandLineArgs::doc_specified_flags(), Global_Parameters::Element_multiplier, i, j, oomph::DocInfo::number(), oomph::CommandLineArgs::parse_and_assign(), problem, Global_Physical_Variables::Re, oomph::DocInfo::set_directory(), Flag_definition::setup(), oomph::CommandLineArgs::specify_command_line_flag(), and plotDoE::x.