MercuryDPM: QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D > Class Template Reference
QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D > Class Template Reference
#include <gen_axisym_advection_diffusion_elements.h>
Public Member Functions
QGeneralisedAxisymAdvectionDiffusionElement ()
QGeneralisedAxisymAdvectionDiffusionElement (const QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D > &dummy)=delete
Broken copy constructor.
unsigned required_nvalue (const unsigned &n) const
Broken assignment operator.
void output (std::ostream &outfile)
void output (std::ostream &outfile, const unsigned &n_plot)
void output (FILE *file_pt)
void output (FILE *file_pt, const unsigned &n_plot)
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Protected Member Functions
double dshape_and_dtest_eulerian_cons_axisym_adv_diff (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
double dshape_and_dtest_eulerian_at_knot_cons_axisym_adv_diff (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const
Static Private Attributes
static const unsigned Initial_Nvalue = 1
Detailed Description
template<unsigned NNODE_1D>
class QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >
//////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////// QGeneralisedAxisymAdvectionDiffusionElement elements are linear/quadrilateral/brick-shaped Advection Diffusion elements with isoparametric interpolation for the function.
Constructor & Destructor Documentation
QGeneralisedAxisymAdvectionDiffusionElement() [1/2]
template<unsigned NNODE_1D> QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::QGeneralisedAxisymAdvectionDiffusionElement () inline
Constructor: Call constructors for QElement and Advection Diffusion equations
       : QElement<2, NNODE_1D>(), GeneralisedAxisymAdvectionDiffusionEquations()
     {
     }
QGeneralisedAxisymAdvectionDiffusionElement() [2/2]
template<unsigned NNODE_1D> QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::QGeneralisedAxisymAdvectionDiffusionElement (const QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D > & dummy) delete
Broken copy constructor.
Member Function Documentation
dshape_and_dtest_eulerian_at_knot_cons_axisym_adv_diff()
template<unsigned NNODE_1D> double QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::dshape_and_dtest_eulerian_at_knot_cons_axisym_adv_diff (const unsigned & ipt, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const inline protected
Shape, test functions & derivs. w.r.t. to global coords. at integration point ipt. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
   {
     // Call the geometrical shape functions and derivatives
     double J = this->dshape_eulerian_at_knot(ipt, psi, dpsidx);
     // Set the test functions equal to the shape functions (pointer copy)
     test = psi;
     dtestdx = dpsidx;
     // Return the jacobian
     return J;
   }
References J.
dshape_and_dtest_eulerian_cons_axisym_adv_diff()
template<unsigned NNODE_1D> double QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::dshape_and_dtest_eulerian_cons_axisym_adv_diff (const Vector< double > & s, Shape & psi, DShape & dpsidx, Shape & test, DShape & dtestdx) const inline protected
Shape, test functions & derivs. w.r.t. to global coords. Return Jacobian.
Define the shape functions and test functions and derivatives w.r.t. global coordinates and return Jacobian of mapping.
Galerkin: Test functions = shape functions
   {
     // Call the geometrical shape functions and derivatives
     double J = this->dshape_eulerian(s, psi, dpsidx);
     // Loop over the test functions and derivatives and set them equal to the
     // shape functions
     for (unsigned i = 0; i < NNODE_1D; i++)
     {
       test[i] = psi[i];
       for (unsigned j = 0; j < 2; j++)
       {
         dtestdx(i, j) = dpsidx(i, j);
       }
     }
     // Return the jacobian
     return J;
   }
References i, J, j, and s.
output() [1/4]
template<unsigned NNODE_1D> void QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::output (FILE * file_pt) inline
C-style output function: r,z,u
     {
       GeneralisedAxisymAdvectionDiffusionEquations::output(file_pt);
     }
References oomph::output().
output() [2/4]
template<unsigned NNODE_1D> void QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::output (FILE * file_pt, const unsigned & n_plot) inline
C-style output function: r,z,u at n_plot^2 plot points
     {
       GeneralisedAxisymAdvectionDiffusionEquations::output(file_pt, n_plot);
     }
References oomph::output().
output() [3/4]
template<unsigned NNODE_1D> void QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::output (std::ostream & outfile) inline
Output function: r,z,u
     {
       GeneralisedAxisymAdvectionDiffusionEquations::output(outfile);
     }
References oomph::output().
output() [4/4]
template<unsigned NNODE_1D> void QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::output (std::ostream & outfile, const unsigned & n_plot) inline
Output function: r,z,u at n_plot^2 plot points
     {
       GeneralisedAxisymAdvectionDiffusionEquations::output(outfile, n_plot);
     }
References oomph::output().
output_fct() [1/2]
template<unsigned NNODE_1D> void QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) inline
Output function for a time-dependent exact solution. r,z,u_exact at n_plot^2 plot points (Calls the steady version)
     {
       GeneralisedAxisymAdvectionDiffusionEquations::output_fct(
         outfile, n_plot, time, exact_soln_pt);
     }
References oomph::output_fct().
output_fct() [2/2]
template<unsigned NNODE_1D> void QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::output_fct (std::ostream & outfile, const unsigned & n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) inline
Output function for an exact solution: r,z,u_exact at n_plot^2 plot points
     {
       GeneralisedAxisymAdvectionDiffusionEquations ::output_fct(
         outfile, n_plot, exact_soln_pt);
     }
References oomph::output_fct().
required_nvalue()
template<unsigned NNODE_1D> unsigned QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::required_nvalue (const unsigned & n) const inline
Broken assignment operator.
Required # of ‘values’ (pinned or dofs) at node n
     {
       return Initial_Nvalue;
     }
Member Data Documentation
Initial_Nvalue
template<unsigned NNODE_1D> const unsigned QGeneralisedAxisymAdvectionDiffusionElement< NNODE_1D >::Initial_Nvalue = 1 static private
Static array of ints to hold number of variables at nodes: Initial_Nvalue[n]
The documentation for this class was generated from the following files:
gen_axisym_advection_diffusion_elements.h
gen_axisym_advection_diffusion_elements.cc