MercuryDPM: oomph::GeneralPurposeBlockPreconditioner< MATRIX > Class Template Reference
oomph::GeneralPurposeBlockPreconditioner< MATRIX > Class Template Reference
#include <general_purpose_block_preconditioners.h>
Public Types
typedef Preconditioner *(* SubsidiaryPreconditionerFctPt) ()
Public Member Functions
GeneralPurposeBlockPreconditioner ()
constructor
virtual ~GeneralPurposeBlockPreconditioner ()
virtual void clean_up_memory ()
GeneralPurposeBlockPreconditioner (const GeneralPurposeBlockPreconditioner &)=delete
Broken copy constructor.
void operator= (const GeneralPurposeBlockPreconditioner &)=delete
Broken assignment operator.
void set_subsidiary_preconditioner_function (SubsidiaryPreconditionerFctPt sub_prec_fn)
access function to set the subsidiary preconditioner function.
void reset_subsidiary_preconditioner_function_to_default ()
Reset the subsidiary preconditioner function to its default.
void set_subsidiary_preconditioner_pt (Preconditioner *prec, const unsigned &i)
Preconditioner * subsidiary_preconditioner_pt (const unsigned &i) const
void set_dof_to_block_map (Vector< unsigned > &dof_to_block_map)
Specify a DOF to block map.
void add_mesh (const Mesh *mesh_pt, const bool &allow_multiple_element_type_in_mesh=false)
unsigned gp_nmesh ()
Public Member Functions inherited from oomph::BlockPreconditioner< MATRIX >
BlockPreconditioner ()
Constructor.
virtual ~BlockPreconditioner ()
Destructor.
BlockPreconditioner (const BlockPreconditioner &)=delete
Broken copy constructor.
void operator= (const BlockPreconditioner &)=delete
Broken assignment operator.
MATRIX * matrix_pt () const
void turn_on_recursive_debug_flag ()
void turn_off_recursive_debug_flag ()
void turn_on_debug_flag ()
Toggles on the debug flag.
void turn_off_debug_flag ()
Toggles off the debug flag.
void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< MATRIX > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse)
void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< MATRIX > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse, const Vector< Vector< unsigned >> &doftype_coarsen_map_coarse)
virtual void block_setup ()
void block_setup (const Vector< unsigned > &dof_to_block_map)
void get_block (const unsigned &i, const unsigned &j, MATRIX &output_matrix, const bool &ignore_replacement_block=false) const
MATRIX get_block (const unsigned &i, const unsigned &j, const bool &ignore_replacement_block=false) const
void set_master_matrix_pt (MATRIX *in_matrix_pt)
Set the matrix_pt in the upper-most master preconditioner.
void get_block_other_matrix (const unsigned &i, const unsigned &j, MATRIX *in_matrix_pt, MATRIX &output_matrix)
void get_blocks (DenseMatrix< bool > &required_blocks, DenseMatrix< MATRIX * > &block_matrix_pt) const
void get_dof_level_block (const unsigned &i, const unsigned &j, MATRIX &output_block, const bool &ignore_replacement_block=false) const
MATRIX get_concatenated_block (const VectorMatrix< BlockSelector > &selected_block)
void get_concatenated_block_vector (const Vector< unsigned > &block_vec_number, const DoubleVector &v, DoubleVector &b)
void return_concatenated_block_vector (const Vector< unsigned > &block_vec_number, const DoubleVector &b, DoubleVector &v) const
Takes concatenated block ordered vector, b, and copies its.
void get_block_vectors (const Vector< unsigned > &block_vec_number, const DoubleVector &v, Vector< DoubleVector > &s) const
void get_block_vectors (const DoubleVector &v, Vector< DoubleVector > &s) const
void return_block_vectors (const Vector< unsigned > &block_vec_number, const Vector< DoubleVector > &s, DoubleVector &v) const
void return_block_vectors (const Vector< DoubleVector > &s, DoubleVector &v) const
void get_block_vector (const unsigned &n, const DoubleVector &v, DoubleVector &b) const
void return_block_vector (const unsigned &n, const DoubleVector &b, DoubleVector &v) const
void get_block_ordered_preconditioner_vector (const DoubleVector &v, DoubleVector &w)
void return_block_ordered_preconditioner_vector (const DoubleVector &w, DoubleVector &v) const
unsigned nblock_types () const
Return the number of block types.
unsigned ndof_types () const
Return the total number of DOF types.
const Mesh * mesh_pt (const unsigned &i) const
unsigned nmesh () const
int block_number (const unsigned &i_dof) const
Return the block number corresponding to a global index i_dof.
int index_in_block (const unsigned &i_dof) const
const LinearAlgebraDistribution * block_distribution_pt (const unsigned &b) const
Access function to the block distributions (const version).
LinearAlgebraDistribution * block_distribution_pt (const unsigned b)
Access function to the block distributions (non-const version).
LinearAlgebraDistribution * dof_block_distribution_pt (const unsigned &b)
Access function to the dof-level block distributions.
const LinearAlgebraDistribution * master_distribution_pt () const
unsigned ndof_types_in_mesh (const unsigned &i) const
bool is_subsidiary_block_preconditioner () const
bool is_master_block_preconditioner () const
void set_block_output_to_files (const std::string &basefilename)
void disable_block_output_to_files ()
Turn off output of blocks (by clearing the basefilename string).
bool block_output_on () const
Test if output of blocks is on or not.
void output_blocks_to_files (const std::string &basefilename, const unsigned &precision=8) const
void post_block_matrix_assembly_partial_clear ()
BlockPreconditioner< MATRIX > * master_block_preconditioner_pt () const
Access function to the master block preconditioner pt.
void clear_block_preconditioner_base ()
void document ()
Vector< Vector< unsigned > > doftype_coarsen_map_fine () const
Vector< unsigned > get_fine_grain_dof_types_in (const unsigned &i) const
unsigned nfine_grain_dof_types_in (const unsigned &i) const
MapMatrix< unsigned, CRDoubleMatrix * > replacement_dof_block_pt () const
Access function to the replaced dof-level blocks.
void setup_matrix_vector_product (MatrixVectorProduct *matvec_prod_pt, CRDoubleMatrix *block_pt, const Vector< unsigned > &block_col_indices)
void setup_matrix_vector_product (MatrixVectorProduct *matvec_prod_pt, CRDoubleMatrix *block_pt, const unsigned &block_col_index)
void internal_get_block_ordered_preconditioner_vector (const DoubleVector &v, DoubleVector &w) const
void internal_return_block_ordered_preconditioner_vector (const DoubleVector &w, DoubleVector &v) const
unsigned internal_nblock_types () const
unsigned internal_ndof_types () const
void internal_return_block_vector (const unsigned &n, const DoubleVector &b, DoubleVector &v) const
void internal_get_block_vector (const unsigned &n, const DoubleVector &v, DoubleVector &b) const
void internal_get_block_vectors (const Vector< unsigned > &block_vec_number, const DoubleVector &v, Vector< DoubleVector > &s) const
void internal_get_block_vectors (const DoubleVector &v, Vector< DoubleVector > &s) const
void internal_return_block_vectors (const Vector< unsigned > &block_vec_number, const Vector< DoubleVector > &s, DoubleVector &v) const
void internal_return_block_vectors (const Vector< DoubleVector > &s, DoubleVector &v) const
void internal_get_block (const unsigned &i, const unsigned &j, MATRIX &output_block) const
int internal_block_number (const unsigned &i_dof) const
int internal_index_in_block (const unsigned &i_dof) const
const LinearAlgebraDistribution * internal_block_distribution_pt (const unsigned &b) const
Access function to the internal block distributions.
void insert_auxiliary_block_distribution (const Vector< unsigned > &block_vec_number, LinearAlgebraDistribution *dist_pt)
void block_matrix_test (const unsigned &i, const unsigned &j, const MATRIX *block_matrix_pt) const
template<typename myType >
int get_index_of_value (const Vector< myType > &vec, const myType val, const bool sorted=false) const
void internal_get_block (const unsigned &block_i, const unsigned &block_j, CRDoubleMatrix &output_block) const
void get_dof_level_block (const unsigned &block_i, const unsigned &block_j, CRDoubleMatrix &output_block, const bool &ignore_replacement_block) const
Public Member Functions inherited from oomph::Preconditioner
Preconditioner ()
Constructor.
Preconditioner (const Preconditioner &)=delete
Broken copy constructor.
void operator= (const Preconditioner &)=delete
Broken assignment operator.
virtual ~Preconditioner ()
Destructor (empty)
virtual void preconditioner_solve (const DoubleVector &r, DoubleVector &z)=0
virtual void preconditioner_solve_transpose (const DoubleVector &r, DoubleVector &z)
void setup (DoubleMatrixBase *matrix_pt)
void setup (const Problem *problem_pt, DoubleMatrixBase *matrix_pt)
void enable_silent_preconditioner_setup ()
Set up the block preconditioner quietly!
void disable_silent_preconditioner_setup ()
Be verbose in the block preconditioner setup.
virtual void setup ()=0
virtual void set_matrix_pt (DoubleMatrixBase *matrix_pt)
Set the matrix pointer.
virtual const OomphCommunicator * comm_pt () const
Get function for comm pointer.
virtual void set_comm_pt (const OomphCommunicator *const comm_pt)
Set the communicator pointer.
double setup_time () const
Returns the time to setup the preconditioner.
virtual void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse)
virtual void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse, const Vector< Vector< unsigned >> &doftype_coarsen_map_coarse)
Public Member Functions inherited from oomph::DistributableLinearAlgebraObject
DistributableLinearAlgebraObject ()
Default constructor - create a distribution.
DistributableLinearAlgebraObject (const DistributableLinearAlgebraObject &matrix)=delete
Broken copy constructor.
void operator= (const DistributableLinearAlgebraObject &)=delete
Broken assignment operator.
virtual ~DistributableLinearAlgebraObject ()
Destructor.
LinearAlgebraDistribution * distribution_pt () const
access to the LinearAlgebraDistribution
unsigned nrow () const
access function to the number of global rows.
unsigned nrow_local () const
access function for the num of local rows on this processor.
unsigned nrow_local (const unsigned &p) const
access function for the num of local rows on this processor.
unsigned first_row () const
access function for the first row on this processor
unsigned first_row (const unsigned &p) const
access function for the first row on this processor
bool distributed () const
distribution is serial or distributed
bool distribution_built () const
void build_distribution (const LinearAlgebraDistribution *const dist_pt)
void build_distribution (const LinearAlgebraDistribution &dist)
Protected Member Functions
void gp_preconditioner_set_all_meshes ()
Set the mesh in the block preconditioning framework.
void gp_preconditioner_block_setup ()
Modified block setup for general purpose block preconditioners.
void fill_in_subsidiary_preconditioners (const unsigned &nprec_needed)
Protected Member Functions inherited from oomph::BlockPreconditioner< MATRIX >
void set_nmesh (const unsigned &n)
void set_mesh (const unsigned &i, const Mesh *const mesh_pt, const bool &allow_multiple_element_type_in_mesh=false)
void set_replacement_dof_block (const unsigned &block_i, const unsigned &block_j, CRDoubleMatrix *replacement_dof_block_pt)
bool any_mesh_distributed () const
int internal_dof_number (const unsigned &i_dof) const
unsigned internal_index_in_dof (const unsigned &i_dof) const
unsigned internal_block_dimension (const unsigned &b) const
unsigned internal_dof_block_dimension (const unsigned &i) const
unsigned master_nrow () const
unsigned internal_master_dof_number (const unsigned &b) const
const LinearAlgebraDistribution * internal_preconditioner_matrix_distribution_pt () const
const LinearAlgebraDistribution * preconditioner_matrix_distribution_pt () const
Protected Member Functions inherited from oomph::DistributableLinearAlgebraObject
void clear_distribution ()
Protected Attributes
Vector< Preconditioner * > Subsidiary_preconditioner_pt
List of preconditioners to use for the blocks to be solved.
SubsidiaryPreconditionerFctPt Subsidiary_preconditioner_creation_function_pt
Protected Attributes inherited from oomph::BlockPreconditioner< MATRIX >
MapMatrix< unsigned, CRDoubleMatrix * > Replacement_dof_block_pt
The replacement dof-level blocks.
Vector< LinearAlgebraDistribution * > Block_distribution_pt
The distribution for the blocks.
Vector< Vector< unsigned > > Block_to_dof_map_coarse
Vector< Vector< unsigned > > Block_to_dof_map_fine
Mapping for the block types to the most fine grain dof types.
Vector< Vector< unsigned > > Doftype_coarsen_map_coarse
Vector< Vector< unsigned > > Doftype_coarsen_map_fine
Vector< LinearAlgebraDistribution * > Internal_block_distribution_pt
Storage for the default distribution for each internal block.
Vector< LinearAlgebraDistribution * > Dof_block_distribution_pt
Vector< unsigned > Allow_multiple_element_type_in_mesh
Vector< const Mesh * > Mesh_pt
Vector< unsigned > Ndof_types_in_mesh
unsigned Internal_nblock_types
unsigned Internal_ndof_types
Protected Attributes inherited from oomph::Preconditioner
bool Silent_preconditioner_setup
Boolean to indicate whether or not the build should be done silently.
std::ostream * Stream_pt
Pointer to the output stream – defaults to std::cout.
Private Attributes
Vector< unsigned > Dof_to_block_map
the set of dof to block maps for this preconditioner
Vector< std::pair< const Mesh *, bool > > Gp_mesh_pt
Detailed Description
template<typename MATRIX>
class oomph::GeneralPurposeBlockPreconditioner< MATRIX >
Base class for general purpose block preconditioners. Deals with setting subsidiary preconditioners and dof to block maps. Subsidiary preconditioners can be set in two ways: 1) A pointer to a subsidiary preconditioner for block i can be passed to set_subsidiary_preconditioner_pt(prec, i). 2) A default subsidiary preconditioner can be set up by providing a function pointer to a function which creates a preconditioner. During setup() all unset subsidiary preconditioner pointers will be filled in using this function. By default this uses SuperLU.
Member Typedef Documentation
SubsidiaryPreconditionerFctPt
template<typename MATRIX > typedef Preconditioner*(* oomph::GeneralPurposeBlockPreconditioner< MATRIX >::SubsidiaryPreconditionerFctPt) ()
typedef for a function that allows other preconditioners to be employed to solve the subsidiary linear systems. The function should return a pointer to the required subsidiary preconditioner generated using new. This preconditioner is responsible for the destruction of the subsidiary preconditioners.
Constructor & Destructor Documentation
GeneralPurposeBlockPreconditioner() [1/2]
template<typename MATRIX > oomph::GeneralPurposeBlockPreconditioner< MATRIX >::GeneralPurposeBlockPreconditioner () inline
constructor
       : BlockPreconditioner<MATRIX>(),
         Subsidiary_preconditioner_creation_function_pt(
           &PreconditionerCreationFunctions::create_super_lu_preconditioner)
     {
       // Make sure that the Gp_mesh_pt container is size zero.
       Gp_mesh_pt.resize(0);
     }
References oomph::GeneralPurposeBlockPreconditioner< MATRIX >::Gp_mesh_pt.
~GeneralPurposeBlockPreconditioner()
template<typename MATRIX > virtual oomph::GeneralPurposeBlockPreconditioner< MATRIX >::~GeneralPurposeBlockPreconditioner () inline virtual
Destructor: clean up memory then delete all subsidiary preconditioners.
     {
       this->clean_up_memory();
       for (unsigned j = 0, nj = Subsidiary_preconditioner_pt.size(); j < nj;
            j++)
       {
         delete Subsidiary_preconditioner_pt[j];
       }
     }
References oomph::GeneralPurposeBlockPreconditioner< MATRIX >::clean_up_memory(), j, and oomph::GeneralPurposeBlockPreconditioner< MATRIX >::Subsidiary_preconditioner_pt.
GeneralPurposeBlockPreconditioner() [2/2]
template<typename MATRIX > oomph::GeneralPurposeBlockPreconditioner< MATRIX >::GeneralPurposeBlockPreconditioner (const GeneralPurposeBlockPreconditioner< MATRIX > &) delete
Broken copy constructor.
Member Function Documentation
add_mesh()
template<typename MATRIX > void oomph::GeneralPurposeBlockPreconditioner< MATRIX >::add_mesh (const Mesh * mesh_pt, const bool & allow_multiple_element_type_in_mesh = false) inline
Adds a mesh to be used by the block preconditioning framework for classifying DOF types. Optional boolean argument (default: false) allows the mesh to contain multiple element types.
     {
 #ifdef PARANOID
       // Check that the mesh pointer is not null.
       if (mesh_pt == 0)
       {
         std::ostringstream err_msg;
         err_msg << "The mesh_pt is null, please point it to a mesh.\n";
         throw OomphLibError(
           err_msg.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // Push back the mesh pointer and the boolean in a pair.
       Gp_mesh_pt.push_back(
         std::make_pair(mesh_pt, allow_multiple_element_type_in_mesh));
     }
References oomph::GeneralPurposeBlockPreconditioner< MATRIX >::Gp_mesh_pt, oomph::BlockPreconditioner< MATRIX >::mesh_pt(), OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by main(), PreconditionedFSICollapsibleChannelProblem< ELEMENT >::PreconditionedFSICollapsibleChannelProblem(), NavierStokesProblem< ELEMENT >::set_up_spacetime_solver(), UnsteadyHeatProblem< ELEMENT >::set_up_spacetime_solver(), and TorusProblem< ELEMENT >::TorusProblem().
clean_up_memory()
template<typename MATRIX > virtual void oomph::GeneralPurposeBlockPreconditioner< MATRIX >::clean_up_memory () inline virtual
??ds I think clean_up_memory is supposed to clear out any stuff that doesn't need to be stored between solves. Call clean up on any non-null subsidiary preconditioners.
Reimplemented from oomph::Preconditioner.
Reimplemented in oomph::BandedBlockTriangularPreconditioner< MATRIX >, oomph::ExactDGPBlockPreconditioner< MATRIX >, oomph::BlockTriangularPreconditioner< MATRIX >, and oomph::BlockDiagonalPreconditioner< MATRIX >.
     {
       // Call clean up in any subsidiary precondtioners that are set.
       for (unsigned j = 0, nj = Subsidiary_preconditioner_pt.size(); j < nj;
            j++)
       {
         if (Subsidiary_preconditioner_pt[j] != 0)
         {
           Subsidiary_preconditioner_pt[j]->clean_up_memory();
         }
       }
       // Clean up the block preconditioner base class stuff
       this->clear_block_preconditioner_base();
     }
References oomph::BlockPreconditioner< MATRIX >::clear_block_preconditioner_base(), j, and oomph::GeneralPurposeBlockPreconditioner< MATRIX >::Subsidiary_preconditioner_pt.
Referenced by oomph::BlockDiagonalPreconditioner< MATRIX >::clean_up_memory(), oomph::BlockTriangularPreconditioner< MATRIX >::clean_up_memory(), oomph::ExactDGPBlockPreconditioner< MATRIX >::clean_up_memory(), oomph::BandedBlockTriangularPreconditioner< MATRIX >::clean_up_memory(), oomph::BlockDiagonalPreconditioner< MATRIX >::~BlockDiagonalPreconditioner(), oomph::BlockTriangularPreconditioner< MATRIX >::~BlockTriangularPreconditioner(), and oomph::GeneralPurposeBlockPreconditioner< MATRIX >::~GeneralPurposeBlockPreconditioner().
fill_in_subsidiary_preconditioners()
template<typename MATRIX > void oomph::GeneralPurposeBlockPreconditioner< MATRIX >::fill_in_subsidiary_preconditioners (const unsigned & nprec_needed) inline protected
Create any subsidiary preconditioners needed. Usually nprec_needed = nblock_types, except for the ExactBlockPreconditioner which only requires one preconditioner.
     {
       // If it's empty then fill it in with null pointers.
       if (Subsidiary_preconditioner_pt.empty())
       {
         Subsidiary_preconditioner_pt.assign(nprec_needed, 0);
       }
       else
       {
         // Otherwise check we have the right number of them
 #ifdef PARANOID
         if (Subsidiary_preconditioner_pt.size() != nprec_needed)
         {
           using namespace StringConversion;
           std::string error_msg = "Wrong number of precondtioners in";
           error_msg += "Subsidiary_preconditioner_pt, should have ";
           error_msg += to_string(nprec_needed) + " but we actually have ";
           error_msg += to_string(Subsidiary_preconditioner_pt.size());
           throw OomphLibError(
             error_msg, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
         }
 #endif
       }
       // Now replace any null pointers with new preconditioners
       for (unsigned j = 0, nj = Subsidiary_preconditioner_pt.size(); j < nj;
            j++)
       {
         if (Subsidiary_preconditioner_pt[j] == 0)
         {
           Subsidiary_preconditioner_pt[j] =
             (*Subsidiary_preconditioner_creation_function_pt)();
         }
       }
     }
References j, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::Global_string_for_annotation::string(), oomph::GeneralPurposeBlockPreconditioner< MATRIX >::Subsidiary_preconditioner_pt, and oomph::StringConversion::to_string().
Referenced by oomph::BlockDiagonalPreconditioner< MATRIX >::fill_in_subsidiary_preconditioners().
gp_nmesh()
template<typename MATRIX > unsigned oomph::GeneralPurposeBlockPreconditioner< MATRIX >::gp_nmesh () inline
Returns the number of meshes currently set in the GeneralPurposeBlockPreconditioner base class.
     {
       return Gp_mesh_pt.size();
     }
References oomph::GeneralPurposeBlockPreconditioner< MATRIX >::Gp_mesh_pt.
Referenced by oomph::GeneralPurposeBlockPreconditioner< MATRIX >::gp_preconditioner_set_all_meshes().
gp_preconditioner_block_setup()
template<typename MATRIX > void oomph::GeneralPurposeBlockPreconditioner< MATRIX >::gp_preconditioner_block_setup () inline protected
Modified block setup for general purpose block preconditioners.
     {
       if (Dof_to_block_map.size() > 0)
       {
         BlockPreconditioner<MATRIX>::block_setup(Dof_to_block_map);
       }
       else
       {
         BlockPreconditioner<MATRIX>::block_setup();
       }
     }
References oomph::BlockPreconditioner< MATRIX >::block_setup(), and oomph::GeneralPurposeBlockPreconditioner< MATRIX >::Dof_to_block_map.
gp_preconditioner_set_all_meshes()
template<typename MATRIX > void oomph::GeneralPurposeBlockPreconditioner< MATRIX >::gp_preconditioner_set_all_meshes () inline protected
Set the mesh in the block preconditioning framework.
     {
       const unsigned nmesh = gp_nmesh();
 #ifdef PARANOID
       if (nmesh == 0)
       {
         std::ostringstream err_msg;
         err_msg << "There are no meshes set.\n"
                 << "Have you remembered to call add_mesh(...)?\n";
         throw OomphLibError(
           err_msg.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       this->set_nmesh(nmesh);
       for (unsigned mesh_i = 0; mesh_i < nmesh; mesh_i++)
       {
         this->set_mesh(
           mesh_i, Gp_mesh_pt[mesh_i].first, Gp_mesh_pt[mesh_i].second);
       }
     }
References oomph::GeneralPurposeBlockPreconditioner< MATRIX >::Gp_mesh_pt, oomph::GeneralPurposeBlockPreconditioner< MATRIX >::gp_nmesh(), oomph::BlockPreconditioner< MATRIX >::nmesh(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::BlockPreconditioner< MATRIX >::set_mesh(), and oomph::BlockPreconditioner< MATRIX >::set_nmesh().
operator=()
template<typename MATRIX > void oomph::GeneralPurposeBlockPreconditioner< MATRIX >::operator= (const GeneralPurposeBlockPreconditioner< MATRIX > &) delete
Broken assignment operator.
reset_subsidiary_preconditioner_function_to_default()
template<typename MATRIX > void oomph::GeneralPurposeBlockPreconditioner< MATRIX >::reset_subsidiary_preconditioner_function_to_default () inline
Reset the subsidiary preconditioner function to its default.
     {
       Subsidiary_preconditioner_creation_function_pt =
         &PreconditionerCreationFunctions::create_super_lu_preconditioner;
     }
References oomph::PreconditionerCreationFunctions::create_super_lu_preconditioner(), and oomph::GeneralPurposeBlockPreconditioner< MATRIX >::Subsidiary_preconditioner_creation_function_pt.
set_dof_to_block_map()
template<typename MATRIX > void oomph::GeneralPurposeBlockPreconditioner< MATRIX >::set_dof_to_block_map (Vector< unsigned > & dof_to_block_map) inline
Specify a DOF to block map.
     {
       Dof_to_block_map = dof_to_block_map;
     }
References oomph::GeneralPurposeBlockPreconditioner< MATRIX >::Dof_to_block_map.
Referenced by NavierStokesProblem< ELEMENT >::set_up_spacetime_solver(), UnsteadyHeatProblem< ELEMENT >::set_up_spacetime_solver(), and oomph::PseudoElasticPreconditioner::setup().
set_subsidiary_preconditioner_function()
template<typename MATRIX > void oomph::GeneralPurposeBlockPreconditioner< MATRIX >::set_subsidiary_preconditioner_function (SubsidiaryPreconditionerFctPt sub_prec_fn) inline
access function to set the subsidiary preconditioner function.
     {
       Subsidiary_preconditioner_creation_function_pt = sub_prec_fn;
     }
References oomph::GeneralPurposeBlockPreconditioner< MATRIX >::Subsidiary_preconditioner_creation_function_pt.
Referenced by main(), FSIChannelWithLeafletProblem< ELEMENT >::set_iterative_solver(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::set_pseudo_elastic_fsi_solver(), set_pseudo_elastic_fsi_solver(), NavierStokesProblem< ELEMENT >::set_up_spacetime_solver(), and oomph::PseudoElasticPreconditioner::setup().
set_subsidiary_preconditioner_pt()
template<typename MATRIX > void oomph::GeneralPurposeBlockPreconditioner< MATRIX >::set_subsidiary_preconditioner_pt (Preconditioner * prec, const unsigned & i) inline
Set the subsidiary preconditioner to use for block i. The subsidiary preconditioner should have been created using new (the general purpose block preconditioner will delete it later). If null the general purpose block preconditioner will use the Subsidiary_preconditioner_creation_function_pt to create the preconditioner during setup().
     {
       // If the vector is currently too small to hold that many
       // preconditioners then expand it and fill with nulls.
       if (Subsidiary_preconditioner_pt.size() < i + 1)
       {
         Subsidiary_preconditioner_pt.resize(i + 1, 0);
       }
       // Note: the size of the vector is checked by
       // fill_in_subsidiary_preconditioners(..)  when we know what size it
       // should be.
       // I'm assuming that the number of preconditioners is always "small"
       // compared to Jacobian size, so a resize doesn't waste much time.
       // Put the pointer in the vector
       Subsidiary_preconditioner_pt[i] = prec;
     }
References i, and oomph::GeneralPurposeBlockPreconditioner< MATRIX >::Subsidiary_preconditioner_pt.
subsidiary_preconditioner_pt()
template<typename MATRIX > Preconditioner* oomph::GeneralPurposeBlockPreconditioner< MATRIX >::subsidiary_preconditioner_pt (const unsigned & i) const inline
Get the subsidiary precondtioner pointer in block i (is allowed to be null if not yet set).
     {
       return Subsidiary_preconditioner_pt[i];
     }
References i, and oomph::GeneralPurposeBlockPreconditioner< MATRIX >::Subsidiary_preconditioner_pt.
Member Data Documentation
Dof_to_block_map
template<typename MATRIX > Vector<unsigned> oomph::GeneralPurposeBlockPreconditioner< MATRIX >::Dof_to_block_map private
the set of dof to block maps for this preconditioner
Referenced by oomph::GeneralPurposeBlockPreconditioner< MATRIX >::gp_preconditioner_block_setup(), and oomph::GeneralPurposeBlockPreconditioner< MATRIX >::set_dof_to_block_map().
Gp_mesh_pt
template<typename MATRIX > Vector<std::pair<const Mesh*, bool> > oomph::GeneralPurposeBlockPreconditioner< MATRIX >::Gp_mesh_pt private
Vector of mesh pointers and a boolean indicating if we allow multiple element types in the same mesh.
Referenced by oomph::GeneralPurposeBlockPreconditioner< MATRIX >::add_mesh(), oomph::GeneralPurposeBlockPreconditioner< MATRIX >::GeneralPurposeBlockPreconditioner(), oomph::GeneralPurposeBlockPreconditioner< MATRIX >::gp_nmesh(), and oomph::GeneralPurposeBlockPreconditioner< MATRIX >::gp_preconditioner_set_all_meshes().
Subsidiary_preconditioner_creation_function_pt
template<typename MATRIX > SubsidiaryPreconditionerFctPt oomph::GeneralPurposeBlockPreconditioner< MATRIX >::Subsidiary_preconditioner_creation_function_pt protected
Function to create any subsidiary preconditioners not set in Subsidiary_preconditioner_pt.
Referenced by oomph::GeneralPurposeBlockPreconditioner< MATRIX >::reset_subsidiary_preconditioner_function_to_default(), and oomph::GeneralPurposeBlockPreconditioner< MATRIX >::set_subsidiary_preconditioner_function().
Subsidiary_preconditioner_pt
template<typename MATRIX > Vector<Preconditioner*> oomph::GeneralPurposeBlockPreconditioner< MATRIX >::Subsidiary_preconditioner_pt protected
List of preconditioners to use for the blocks to be solved.
Referenced by oomph::GeneralPurposeBlockPreconditioner< MATRIX >::clean_up_memory(), oomph::GeneralPurposeBlockPreconditioner< MATRIX >::fill_in_subsidiary_preconditioners(), oomph::BlockDiagonalPreconditioner< MATRIX >::fill_in_subsidiary_preconditioners(), oomph::ExactBlockPreconditioner< MATRIX >::preconditioner_pt(), oomph::GeneralPurposeBlockPreconditioner< MATRIX >::set_subsidiary_preconditioner_pt(), oomph::GeneralPurposeBlockPreconditioner< MATRIX >::subsidiary_preconditioner_pt(), and oomph::GeneralPurposeBlockPreconditioner< MATRIX >::~GeneralPurposeBlockPreconditioner().
The documentation for this class was generated from the following file:
general_purpose_block_preconditioners.h