MercuryDPM: Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased > Struct Template Reference
Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased > Struct Template Reference
#include <CoreEvaluators.h>
Public Types
enum { RowsAtCompileTime = XprType::RowsAtCompileTime , ForwardLinearAccess }
typedef Block< ArgType, BlockRows, BlockCols, InnerPanel > XprType
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
Public Types inherited from Eigen::internal::evaluator_base< Block< ArgType, BlockRows, BlockCols, InnerPanel > >
enum
typedef traits< Block< ArgType, BlockRows, BlockCols, InnerPanel > > ExpressionTraits
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE unary_evaluator (const XprType &block)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index row, Index col)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & coeffRef (Index index)
template<int LoadMode, typename PacketType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType packet (Index row, Index col) const
template<int LoadMode, typename PacketType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType packet (Index index) const
template<int StoreMode, typename PacketType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void writePacket (Index row, Index col, const PacketType &x)
template<int StoreMode, typename PacketType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void writePacket (Index index, const PacketType &x)
Public Member Functions inherited from Eigen::internal::evaluator_base< Block< ArgType, BlockRows, BlockCols, InnerPanel > >
EIGEN_DEVICE_FUNC constexpr EIGEN_STRONG_INLINE evaluator_base ()=default
Protected Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType linear_coeff_impl (Index index, internal::true_type) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType linear_coeff_impl (Index index, internal::false_type) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & linear_coeffRef_impl (Index index, internal::true_type)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar & linear_coeffRef_impl (Index index, internal::false_type)
Protected Attributes
evaluator< ArgType > m_argImpl
const variable_if_dynamic< Index,(ArgType::RowsAtCompileTime==1 &&BlockRows==1) ? 0 :Dynamic > m_startRow
const variable_if_dynamic< Index,(ArgType::ColsAtCompileTime==1 &&BlockCols==1) ? 0 :Dynamic > m_startCol
const variable_if_dynamic< Index, ForwardLinearAccess ? Dynamic :0 > m_linear_offset
Member Typedef Documentation
CoeffReturnType
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> typedef XprType::CoeffReturnType Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::CoeffReturnType
Scalar
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> typedef XprType::Scalar Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::Scalar
XprType
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> typedef Block<ArgType, BlockRows, BlockCols, InnerPanel> Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::XprType
Member Enumeration Documentation
anonymous enum
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> anonymous enum
Enumerator
RowsAtCompileTime
ForwardLinearAccess
        {
     RowsAtCompileTime = XprType::RowsAtCompileTime,
     ForwardLinearAccess = (InnerPanel || int(XprType::IsRowMajor) == int(ArgType::IsRowMajor)) &&
                           bool(evaluator<ArgType>::Flags & LinearAccessBit)
   };
Constructor & Destructor Documentation
unary_evaluator()
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::unary_evaluator (const XprType & block) inline explicit
       : m_argImpl(block.nestedExpression()),
         m_startRow(block.startRow()),
         m_startCol(block.startCol()),
         m_linear_offset(ForwardLinearAccess
                             ? (ArgType::IsRowMajor
                                    ? block.startRow() * block.nestedExpression().cols() + block.startCol()
                                    : block.startCol() * block.nestedExpression().rows() + block.startRow())
                             : 0) {}
Member Function Documentation
coeff() [1/2]
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::coeff (Index index) const inline
{
     return linear_coeff_impl(index, bool_constant<ForwardLinearAccess>());
   }
coeff() [2/2]
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::coeff (Index row, Index col) const inline
{
     return m_argImpl.coeff(m_startRow.value() + row, m_startCol.value() + col);
   }
References col(), and row().
coeffRef() [1/2]
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::coeffRef (Index index) inline
{
     return linear_coeffRef_impl(index, bool_constant<ForwardLinearAccess>());
   }
coeffRef() [2/2]
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::coeffRef (Index row, Index col) inline
{
     return m_argImpl.coeffRef(m_startRow.value() + row, m_startCol.value() + col);
   }
References col(), and row().
linear_coeff_impl() [1/2]
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::linear_coeff_impl (Index index, internal::false_type) const inline protected
{
     return coeff(RowsAtCompileTime == 1 ? 0 : index, RowsAtCompileTime == 1 ? index : 0);
   }
linear_coeff_impl() [2/2]
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::linear_coeff_impl (Index index, internal::true_type) const inline protected
{
     return m_argImpl.coeff(m_linear_offset.value() + index);
   }
linear_coeffRef_impl() [1/2]
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::linear_coeffRef_impl (Index index, internal::false_type) inline protected
{
     return coeffRef(RowsAtCompileTime == 1 ? 0 : index, RowsAtCompileTime == 1 ? index : 0);
   }
linear_coeffRef_impl() [2/2]
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Scalar& Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::linear_coeffRef_impl (Index index, internal::true_type) inline protected
{
     return m_argImpl.coeffRef(m_linear_offset.value() + index);
   }
packet() [1/2]
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> template<int LoadMode, typename PacketType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::packet (Index index) const inline
{
     if (ForwardLinearAccess)
       return m_argImpl.template packet<LoadMode, PacketType>(m_linear_offset.value() + index);
     else
       return packet<LoadMode, PacketType>(RowsAtCompileTime == 1 ? 0 : index, RowsAtCompileTime == 1 ? index : 0);
   }
packet() [2/2]
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> template<int LoadMode, typename PacketType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketType Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::packet (Index row, Index col) const inline
{
     return m_argImpl.template packet<LoadMode, PacketType>(m_startRow.value() + row, m_startCol.value() + col);
   }
References col(), and row().
writePacket() [1/2]
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> template<int StoreMode, typename PacketType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::writePacket (Index index, const PacketType & x) inline
{
     if (ForwardLinearAccess)
       return m_argImpl.template writePacket<StoreMode, PacketType>(m_linear_offset.value() + index, x);
     else
       return writePacket<StoreMode, PacketType>(RowsAtCompileTime == 1 ? 0 : index, RowsAtCompileTime == 1 ? index : 0,
                                                 x);
   }
References plotDoE::x.
writePacket() [2/2]
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> template<int StoreMode, typename PacketType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::writePacket (Index row, Index col, const PacketType & x) inline
{
     return m_argImpl.template writePacket<StoreMode, PacketType>(m_startRow.value() + row, m_startCol.value() + col, x);
   }
References col(), row(), and plotDoE::x.
Member Data Documentation
m_argImpl
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> evaluator<ArgType> Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::m_argImpl protected
m_linear_offset
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> const variable_if_dynamic<Index, ForwardLinearAccess ? Dynamic : 0> Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::m_linear_offset protected
m_startCol
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> const variable_if_dynamic<Index, (ArgType::ColsAtCompileTime == 1 && BlockCols == 1) ? 0 : Dynamic> Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::m_startCol protected
m_startRow
template<typename ArgType , int BlockRows, int BlockCols, bool InnerPanel> const variable_if_dynamic<Index, (ArgType::RowsAtCompileTime == 1 && BlockRows == 1) ? 0 : Dynamic> Eigen::internal::unary_evaluator< Block< ArgType, BlockRows, BlockCols, InnerPanel >, IndexBased >::m_startRow protected
The documentation for this struct was generated from the following file:
CoreEvaluators.h