MercuryDPM: multi_domain_ref_b_convection.cc File Reference
mpi/multi_domain/boussinesq_convection/multi_domain_ref_b_convection.cc File Reference
#include "generic.h"
#include "advection_diffusion.h"
#include "navier_stokes.h"
#include "multi_physics.h"
#include "meshes/rectangular_quadmesh.h"
Classes
class RefineableConvectionProblem< NST_ELEMENT, AD_ELEMENT >
Namespaces
Global_Physical_Variables
Global variables.
Functions
int main (int argc, char **argv)
Variables
Vector< double > Global_Physical_Variables::Direction_of_gravity (2)
Gravity vector.
Function Documentation
main()
int main (int argc , char ** argv)
Driver code for 2D Boussinesq convection problem with adaptivity.
 {
 #ifdef OOMPH_HAS_MPI
  MPI_Helpers::init(argc,argv);
 #endif
   // Switch off output modifier
  oomph_info.output_modifier_pt() = &default_output_modifier;
  // Define processor-labeled output file for all on-screen stuff
  std::ofstream output_stream;
  char filename[100];
  sprintf(filename,"OUTPUT.%i",MPI_Helpers::communicator_pt()->my_rank());
  output_stream.open(filename);
  oomph_info.stream_pt() = &output_stream;
  OomphLibWarning::set_stream_pt(&output_stream);
  OomphLibError::set_stream_pt(&output_stream);
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Set the direction of gravity
  Global_Physical_Variables::Direction_of_gravity[0] = 0.0;
  Global_Physical_Variables::Direction_of_gravity[1] = -1.0;
  // Create the problem with 2D nine-node refineable elements.
  RefineableConvectionProblem<
  RefineableNavierStokesBoussinesqElement<
  RefineableQCrouzeixRaviartElement<2>,
   RefineableQAdvectionDiffusionElement<2,3> > ,
   RefineableAdvectionDiffusionBoussinesqElement<
   RefineableQAdvectionDiffusionElement<2,3>,
   RefineableQCrouzeixRaviartElement<2> >
   > problem;
  // Apply a perturbation to the upper boundary condition to
  // force the solution into the symmetry-broken state.
  problem.enable_imperfection();
  // Distribute the problem
 #ifdef OOMPH_HAS_MPI
  DocInfo mesh_doc_info;
  mesh_doc_info.number()=0;
  mesh_doc_info.set_directory("RESLT_MULTI");
  bool report_stats=true;
  // Are there command-line arguments?
  if (CommandLineArgs::Argc==1)
   {
    // No arguments, so distribute without reference to partition vector
    problem.distribute(mesh_doc_info,report_stats);
   }
  else
   {
    // Make up some distribution in which both meshes get some elements
    unsigned n_element=problem.mesh_pt()->nelement();
    Vector<unsigned> element_partition(n_element);
    std::string input_string;
    for (unsigned e=0;e<n_element;e++)
     {
      unsigned target_part=0;
      if ( (e<unsigned(0.25*double(n_element))) ||
           ( (e>unsigned(0.5*double(n_element))) &&
             (e<unsigned(0.75*double(n_element))) ) )
       {
        target_part=1;
       }
      element_partition[e]=target_part;
     }
    problem.distribute(element_partition,mesh_doc_info,report_stats);
   }
 #endif
  //Document the solution
  problem.doc_solution();
  //Solve the problem with (up to) two levels of adaptation
  problem.newton_solve(2);
  //Document the solution
  problem.doc_solution();
  // Make the boundary conditions perfect and solve again.
  // Now the slightly perturbed symmetry broken state computed
  // above is used as the initial condition and the Newton solver
  // converges to the symmetry broken solution, even without
  // the perturbation
  problem.disable_imperfection();
  problem.newton_solve(2);
  problem.doc_solution();
  // Refine unformly to give us something to prune
  oomph_info << "About to refine uniformly\n";
  problem.refine_uniformly();
  problem.doc_solution();
  oomph_info << "About to prune\n";
  problem.prune_halo_elements_and_nodes();
  problem.doc_solution();
  oomph_info << "About to solve again\n";
  problem.newton_solve(1);
  problem.doc_solution();
 #ifdef OOMPH_HAS_MPI
  MPI_Helpers::finalize();
 #endif
 } // end of main
References oomph::CommandLineArgs::Argc, oomph::MPI_Helpers::communicator_pt(), oomph::default_output_modifier, oomph::Global_Physical_Variables::Direction_of_gravity, e(), MergeRestartFiles::filename, oomph::MPI_Helpers::finalize(), oomph::MPI_Helpers::init(), oomph::DocInfo::number(), oomph::oomph_info, oomph::OomphInfo::output_modifier_pt(), problem, oomph::DocInfo::set_directory(), oomph::OomphLibError::set_stream_pt(), oomph::OomphLibWarning::set_stream_pt(), oomph::CommandLineArgs::setup(), oomph::OomphInfo::stream_pt(), and oomph::Global_string_for_annotation::string().