MercuryDPM: oomph::TriangleMeshOpenCurve Class Reference
oomph::TriangleMeshOpenCurve Class Reference
#include <unstructured_two_d_mesh_geometry_base.h>
Public Member Functions
TriangleMeshOpenCurve (const Vector< TriangleMeshCurveSection * > &curve_section_pt)
Constructor.
virtual ~TriangleMeshOpenCurve ()
Empty destructor.
unsigned nvertices () const
Number of vertices.
unsigned nsegments () const
Total number of segments.
void output (std::ostream &outfile, const unsigned &n_sample=50)
Output each sub-boundary at n_sample (default: 50) points.
TriangleMeshPolyLine * polyline_pt (const unsigned &i) const
Pointer to i-th constituent polyline.
TriangleMeshPolyLine * polyline_pt (const unsigned &i)
Pointer to i-th constituent polyline.
Public Member Functions inherited from oomph::TriangleMeshCurve
TriangleMeshCurve (const Vector< TriangleMeshCurveSection * > &curve_section_pt)
Empty constructor.
virtual ~TriangleMeshCurve ()
Empty destructor.
unsigned max_boundary_id ()
Return max boundary id of associated curves.
virtual unsigned ncurve_section () const
Number of constituent curves.
void enable_polyline_refinement (const double &tolerance=0.08)
void set_polyline_refinement_tolerance (const double &tolerance)
double polyline_refinement_tolerance ()
void disable_polyline_refinement ()
Disable refinement of polylines.
void enable_polyline_unrefinement (const double &tolerance=0.04)
void set_polyline_unrefinement_tolerance (const double &tolerance)
double polyline_unrefinement_tolerance ()
void disable_polyline_unrefinement ()
Disable unrefinement of polylines.
virtual TriangleMeshCurveSection * curve_section_pt (const unsigned &i) const
Pointer to i-th constituent curve section.
virtual TriangleMeshCurveSection *& curve_section_pt (const unsigned &i)
Pointer to i-th constituent curve section.
Additional Inherited Members
Protected Attributes inherited from oomph::TriangleMeshCurve
Vector< TriangleMeshCurveSection * > Curve_section_pt
Vector of curve sections.
Detailed Description
////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////// Base class defining an open curve for the Triangle mesh generation Basically used to define internal boundaries on the mesh
Constructor & Destructor Documentation
TriangleMeshOpenCurve()
oomph::TriangleMeshOpenCurve::TriangleMeshOpenCurve (const Vector< TriangleMeshCurveSection * > & curve_section_pt)
Constructor.
Class defining an open curve for the Triangle mesh generation.
////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////
     : TriangleMeshCurve(curve_section_pt)
   {
     // Matching of curve sections i.e. the last vertex of
     // the i curve section should match with the first
     // vertex of the i+1 curve section
     // Total number of boundaries
     unsigned n_boundaries = Curve_section_pt.size();
     // Check last point of each boundary bit coincides with first point
     // on next one
     for (unsigned i = 0; i < n_boundaries - 1; i++)
     {
       // Auxiliary vertex for storing the vertex values of contiguous curves
       Vector<double> v1(2);
       Vector<double> v2(2);
       // This is for getting the final coordinates of the i curve section
       Curve_section_pt[i]->final_vertex_coordinate(v1);
       // This is for the start coordinates of the i+1 curve section
       Curve_section_pt[i + 1]->initial_vertex_coordinate(v2);
       // Work out error
       double error = sqrt(pow(v1[0] - v2[0], 2) + pow(v1[1] - v2[1], 2));
       if (error > ToleranceForVertexMismatchInPolygons::Tolerable_error)
       {
         std::ostringstream error_stream;
         error_stream
           << "The start and end points of curve section boundary parts " << i
           << " and " << i + 1
           << " don't match when judged \nwith the tolerance of "
           << ToleranceForVertexMismatchInPolygons::Tolerable_error
           << " which is specified in the namespace \nvariable "
           << "ToleranceForVertexMismatchInPolygons::Tolerable_error.\n\n"
           << "Feel free to adjust this or to recompile the code without\n"
           << "paranoia if you think this is OK...\n"
           << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
       else
       {
         // Aligns (only implemented for polylines)
         TriangleMeshPolyLine* current_polyline =
           dynamic_cast<TriangleMeshPolyLine*>(Curve_section_pt[i]);
         TriangleMeshPolyLine* next_polyline =
           dynamic_cast<TriangleMeshPolyLine*>(Curve_section_pt[i + 1]);
         if (current_polyline && next_polyline)
         {
           unsigned last_vertex = current_polyline->nvertex() - 1;
           next_polyline->vertex_coordinate(0) =
             current_polyline->vertex_coordinate(last_vertex);
         }
       }
     } // For n_boundaries - 1
   }
References oomph::TriangleMeshCurve::Curve_section_pt, calibrate::error, i, oomph::TriangleMeshPolyLine::nvertex(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, Eigen::bfloat16_impl::pow(), sqrt(), oomph::ToleranceForVertexMismatchInPolygons::Tolerable_error, v1(), v2(), and oomph::TriangleMeshPolyLine::vertex_coordinate().
~TriangleMeshOpenCurve()
virtual oomph::TriangleMeshOpenCurve::~TriangleMeshOpenCurve () inline virtual
Empty destructor.
 {}
Member Function Documentation
nsegments()
unsigned oomph::TriangleMeshOpenCurve::nsegments () const inline virtual
Total number of segments.
Implements oomph::TriangleMeshCurve.
     {
       unsigned n_curve_section = ncurve_section();
       unsigned nseg = 0;
       for (unsigned j = 0; j < n_curve_section; j++)
       {
         nseg += Curve_section_pt[j]->nsegment();
       }
       return nseg;
     }
References oomph::TriangleMeshCurve::Curve_section_pt, j, and oomph::TriangleMeshCurve::ncurve_section().
nvertices()
unsigned oomph::TriangleMeshOpenCurve::nvertices () const inline virtual
Number of vertices.
Implements oomph::TriangleMeshCurve.
     {
       unsigned n_vertices = 0;
       unsigned n_curve_section = ncurve_section();
       for (unsigned i = 0; i < n_curve_section; i++)
         n_vertices += Curve_section_pt[i]->nvertex();
       // If there's just one boundary. All the vertices should be counted
       if (n_curve_section == 1)
       {
         n_vertices += 1;
       }
       return n_vertices;
     }
References oomph::TriangleMeshCurve::Curve_section_pt, i, and oomph::TriangleMeshCurve::ncurve_section().
output()
void oomph::TriangleMeshOpenCurve::output (std::ostream & outfile, const unsigned & n_sample = 50) inline virtual
Output each sub-boundary at n_sample (default: 50) points.
Implements oomph::TriangleMeshCurve.
     {
       unsigned nb = Curve_section_pt.size();
       for (unsigned i = 0; i < nb; i++)
       {
         Curve_section_pt[i]->output(outfile, n_sample);
       }
     }
References oomph::TriangleMeshCurve::Curve_section_pt, i, and nb.
polyline_pt() [1/2]
TriangleMeshPolyLine* oomph::TriangleMeshOpenCurve::polyline_pt (const unsigned & i) inline
Pointer to i-th constituent polyline.
     {
       TriangleMeshPolyLine* tmp_polyline =
         dynamic_cast<TriangleMeshPolyLine*>(Curve_section_pt[i]);
 #ifdef PARANOID
       if (tmp_polyline == NULL)
       {
         std::ostringstream error_stream;
         error_stream << "The (" << i
                      << ")-th TriangleMeshCurveSection is not a "
                      << "TriangleMeshPolyLine.\nPlease make sure that when you"
                      << "first created this object the (" << i << ")-th\n"
                      << "TriangleCurveSection is a TriangleMeshPolyLine."
                      << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       return tmp_polyline;
     }
References oomph::TriangleMeshCurve::Curve_section_pt, i, OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
polyline_pt() [2/2]
TriangleMeshPolyLine* oomph::TriangleMeshOpenCurve::polyline_pt (const unsigned & i) const inline
Pointer to i-th constituent polyline.
     {
       TriangleMeshPolyLine* tmp_polyline =
         dynamic_cast<TriangleMeshPolyLine*>(Curve_section_pt[i]);
 #ifdef PARANOID
       if (tmp_polyline == NULL)
       {
         std::ostringstream error_stream;
         error_stream << "The (" << i
                      << ")-th TriangleMeshCurveSection is not a "
                      << "TriangleMeshPolyLine.\nPlease make sure that when you"
                      << "first created this object the (" << i << ")-th\n"
                      << "TriangleCurveSection is a TriangleMeshPolyLine."
                      << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       return tmp_polyline;
     }
References oomph::TriangleMeshCurve::Curve_section_pt, i, OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
The documentation for this class was generated from the following files:
unstructured_two_d_mesh_geometry_base.h
unstructured_two_d_mesh_geometry_base.cc