MercuryDPM: oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT > Class Template Reference
oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT > Class Template Reference
#include <face_mesh_project.h>
Public Member Functions
BackupMeshForProjection (Mesh *mesh_pt, const unsigned &boundary_id, const unsigned &id_of_field_to_be_projected=UINT_MAX)
void project_onto_new_mesh (Mesh *new_mesh_pt)
void copy_onto_original_mesh ()
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void setup_boundary_element_info ()
virtual void setup_boundary_element_info (std::ostream &outfile)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void node_update (const bool &update_all_solid_nodes=false)
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Private Attributes
std::map< Node *, Node * > New_node_pt
Map returning new node, labeled by node point in original mesh.
unsigned Boundary_id
Boundary id.
unsigned ID_of_field_to_be_projected
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Detailed Description
template<class GEOMETRIC_ELEMENT>
class oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT >
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// Class that makes backup (via a deep copy) of a mesh, keeping alive enough information to allow the solution that is currently stored on the mesh to be projected onto another mesh sometime in the future (when the original mesh may already have been deleted). This is mainly useful for the projection of additional nodal values (such as Lagrange multipliers) created by FaceElements. ASSUMPTION: All fields in the element are represented by isoparametric Lagrange interpolation between the nodal values. Any fields that do not fall into this category will not be copied across correctly and if you're unlucky the code may die...).
Constructor & Destructor Documentation
BackupMeshForProjection()
template<class GEOMETRIC_ELEMENT > oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT >::BackupMeshForProjection (Mesh * mesh_pt, const unsigned & boundary_id, const unsigned & id_of_field_to_be_projected = UINT_MAX) inline
Constructor: Pass existing mesh and the boundary ID (need to find the boundary coordinates that are used for the projection. Optional final argument specifies the ID of the field (i.e. the index of the relevant nodal value!) to be projected. If omitted, we project all of them.
       : Boundary_id(boundary_id),
         ID_of_field_to_be_projected(id_of_field_to_be_projected)
     {
       // Find unique nodes (via elements because Node_pt vector in
       // original mesh may not have been filled (typical for most
       // face element meshes)
       unsigned nel = mesh_pt->nelement();
       Element_pt.reserve(nel);
       Node_pt.reserve(mesh_pt->nnode());
       for (unsigned e = 0; e < nel; e++)
       {
         FiniteElement* el_pt = mesh_pt->finite_element_pt(e);
         if (el_pt != 0)
         {
           // Make new element
 #ifdef PARANOID
           if (dynamic_cast<GEOMETRIC_ELEMENT*>(mesh_pt->element_pt(e)) == 0)
           {
             std::ostringstream error_message;
             error_message << "Element is of wrong type " << typeid(el_pt).name()
                           << " doesn't match template parameter!" << std::endl;
             throw OomphLibError(error_message.str(),
                                 OOMPH_CURRENT_FUNCTION,
                                 OOMPH_EXCEPTION_LOCATION);
             if (el_pt->ninternal_data() != 0)
             {
               std::ostringstream error_message;
               error_message
                 << "Internal data will NOT be projected across!\n"
                 << "If you want this functionality you'll have to \n"
                 << "implement it yourself" << std::endl;
               OomphLibWarning(error_message.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
             }
           }
 #endif
           // Make a new element
           GenericLagrangeInterpolatedProjectableElement<GEOMETRIC_ELEMENT>*
             new_el_pt = new GenericLagrangeInterpolatedProjectableElement<
               GEOMETRIC_ELEMENT>;
           // Set boundary ID
           new_el_pt->set_boundary_id(Boundary_id);
           // Set nodal dimension
           unsigned nodal_dim = el_pt->node_pt(0)->ndim();
           new_el_pt->set_nodal_dimension(nodal_dim);
           // Add it to mesh
           add_element_pt(new_el_pt);
           // Create new nodes if needed
           unsigned nnod = el_pt->nnode();
           for (unsigned j = 0; j < nnod; j++)
           {
             Node* old_node_pt = el_pt->node_pt(j);
             if (New_node_pt[old_node_pt] == 0)
             {
               Node* new_nod_pt = 0;
 #ifdef PARANOID
               // Check boundary node-ness
               if (!old_node_pt->is_on_boundary())
               {
                 std::ostringstream error_message;
                 error_message << "Node isn't on a boundary!" << std::endl;
                 throw OomphLibError(error_message.str(),
                                     OOMPH_CURRENT_FUNCTION,
                                     OOMPH_EXCEPTION_LOCATION);
               }
 #endif
               // How many values are we projecting? Default: All
               unsigned nval = old_node_pt->nvalue();
               unsigned first_index_in_old_node = 0;
               if (ID_of_field_to_be_projected != UINT_MAX)
               {
                 nval = dynamic_cast<BoundaryNodeBase*>(old_node_pt)
                          ->nvalue_assigned_by_face_element(
                            ID_of_field_to_be_projected);
                 first_index_in_old_node =
                   dynamic_cast<BoundaryNodeBase*>(old_node_pt)
                     ->index_of_first_value_assigned_by_face_element(
                       ID_of_field_to_be_projected);
               }
               // Build new node
               new_nod_pt =
                 new BoundaryNode<Node>(old_node_pt->time_stepper_pt(),
                                        old_node_pt->ndim(),
                                        old_node_pt->nposition_type(),
                                        nval);
               // Copy data across
               unsigned n_time = old_node_pt->ntstorage();
               for (unsigned t = 0; t < n_time; t++)
               {
                 for (unsigned i = 0; i < nval; i++)
                 {
                   new_nod_pt->set_value(
                     t, i, old_node_pt->value(t, first_index_in_old_node + i));
                 }
               }
               // Copy nodal positions
               unsigned n_dim = old_node_pt->ndim();
               for (unsigned i = 0; i < n_dim; i++)
               {
                 new_nod_pt->x(i) = old_node_pt->x(i);
               }
               // Add to boundary
               new_nod_pt->add_to_boundary(Boundary_id);
               // Transfer boundary coordinates
 #ifdef PARANOID
               if (!old_node_pt->is_on_boundary(Boundary_id))
               {
                 std::ostringstream error_message;
                 error_message << "Boundary ID specified as " << Boundary_id
                               << " but node isn't actually on that boundary!"
                               << std::endl;
                 throw OomphLibError(error_message.str(),
                                     OOMPH_CURRENT_FUNCTION,
                                     OOMPH_EXCEPTION_LOCATION);
               }
 #endif
               // Get vector of coordinates on mesh boundary from old node
               unsigned n = old_node_pt->ncoordinates_on_boundary(Boundary_id);
               Vector<double> zeta(n);
               old_node_pt->get_coordinates_on_boundary(Boundary_id, zeta);
               // Set for new node
               new_nod_pt->set_coordinates_on_boundary(Boundary_id, zeta);
               // Add node
               Node_pt.push_back(new_nod_pt);
               // Setup association
               New_node_pt[old_node_pt] = new_nod_pt;
             }
             // Set node pointer from new element
             new_el_pt->node_pt(j) = New_node_pt[old_node_pt];
           }
         }
       }
     }
References oomph::Mesh::add_element_pt(), oomph::Node::add_to_boundary(), oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT >::Boundary_id, e(), oomph::Mesh::Element_pt, oomph::Mesh::element_pt(), oomph::Mesh::finite_element_pt(), oomph::Node::get_coordinates_on_boundary(), i, oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT >::ID_of_field_to_be_projected, oomph::Node::is_on_boundary(), j, n, plotDoE::name, oomph::Node::ncoordinates_on_boundary(), oomph::Node::ndim(), oomph::Mesh::nelement(), oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT >::New_node_pt, oomph::GeneralisedElement::ninternal_data(), oomph::FiniteElement::nnode(), oomph::Mesh::nnode(), oomph::FiniteElement::node_pt(), oomph::Mesh::Node_pt, oomph::Node::nposition_type(), oomph::Data::ntstorage(), oomph::Data::nvalue(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::GenericLagrangeInterpolatedProjectableElement< ELEMENT >::set_boundary_id(), oomph::Node::set_coordinates_on_boundary(), oomph::FiniteElement::set_nodal_dimension(), oomph::Data::set_value(), plotPSD::t, oomph::Data::time_stepper_pt(), oomph::Node::value(), oomph::Node::x(), and Eigen::zeta().
Member Function Documentation
copy_onto_original_mesh()
template<class GEOMETRIC_ELEMENT > void oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT >::copy_onto_original_mesh () inline
Copy nodal values back onto original mesh from which this mesh was built. This obviously only makes sense if the original mesh still exists!
     {
       for (std::map<Node*, Node*>::iterator it = New_node_pt.begin();
            it != New_node_pt.end();
            it++)
       {
         // Get old node (in the previously existing mesh)
         Node* old_node_pt = (*it).first;
         // ...and corresponding new one (in the mesh where we did the projection
         Node* new_node_pt = (*it).second;
         // How many values are we moving across?
         unsigned nval = old_node_pt->nvalue();
         unsigned first_index_in_old_node = 0;
         if (ID_of_field_to_be_projected != UINT_MAX)
         {
           nval =
             dynamic_cast<BoundaryNodeBase*>(old_node_pt)
               ->nvalue_assigned_by_face_element(ID_of_field_to_be_projected);
           first_index_in_old_node =
             dynamic_cast<BoundaryNodeBase*>(old_node_pt)
               ->index_of_first_value_assigned_by_face_element(
                 ID_of_field_to_be_projected);
         }
         // Copy data across (include offset in orig mesh)
         unsigned n_time = old_node_pt->ntstorage();
         for (unsigned t = 0; t < n_time; t++)
         {
           for (unsigned i = 0; i < nval; i++)
           {
             old_node_pt->set_value(
               t, first_index_in_old_node + i, new_node_pt->value(t, i));
           }
         }
       }
     }
References i, oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT >::ID_of_field_to_be_projected, oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT >::New_node_pt, oomph::Data::ntstorage(), oomph::Data::nvalue(), oomph::Data::set_value(), plotPSD::t, and oomph::Node::value().
Referenced by oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT >::project_onto_new_mesh().
project_onto_new_mesh()
template<class GEOMETRIC_ELEMENT > void oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT >::project_onto_new_mesh (Mesh * new_mesh_pt) inline
Project the solution that was present in the original mesh and from which this backup mesh was created onto the mesh pointed to by new_mesh_pt. Note that elements in the new mesh do not have to be projectable. The original mesh may by now have been deleted.
     {
       // Make copy of new mesh that we can project onto
       BackupMeshForProjection<GEOMETRIC_ELEMENT>* projectable_new_mesh_pt =
         new BackupMeshForProjection<GEOMETRIC_ELEMENT>(
           new_mesh_pt, Boundary_id, ID_of_field_to_be_projected);
       // Create projection problem
       ProjectionProblem<
         GenericLagrangeInterpolatedProjectableElement<GEOMETRIC_ELEMENT>>*
         proj_problem_pt = new ProjectionProblem<
           GenericLagrangeInterpolatedProjectableElement<GEOMETRIC_ELEMENT>>;
       // Set the mesh we want to project onto
       proj_problem_pt->mesh_pt() = projectable_new_mesh_pt;
       // Project from projectable copy of original mesh -- this one!
       bool dont_project_positions = true;
       proj_problem_pt->project(this, dont_project_positions);
       // Copy nodal values onto the corresponding nodes in the new mesh
       projectable_new_mesh_pt->copy_onto_original_mesh();
       // Kill!
       delete proj_problem_pt;
       delete projectable_new_mesh_pt;
     }
References oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT >::Boundary_id, oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT >::copy_onto_original_mesh(), and oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT >::ID_of_field_to_be_projected.
Referenced by ContactProblem< ELEMENT >::actions_after_adapt().
Member Data Documentation
Boundary_id
template<class GEOMETRIC_ELEMENT > unsigned oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT >::Boundary_id private
Boundary id.
Referenced by oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT >::BackupMeshForProjection(), and oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT >::project_onto_new_mesh().
ID_of_field_to_be_projected
template<class GEOMETRIC_ELEMENT > unsigned oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT >::ID_of_field_to_be_projected private
ID of field to be projected (UINT_MAX if there isn't one, in which case we're doing all of them.
Referenced by oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT >::BackupMeshForProjection(), oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT >::copy_onto_original_mesh(), and oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT >::project_onto_new_mesh().
New_node_pt
template<class GEOMETRIC_ELEMENT > std::map<Node*, Node*> oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT >::New_node_pt private
Map returning new node, labeled by node point in original mesh.
Referenced by oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT >::BackupMeshForProjection(), and oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT >::copy_onto_original_mesh().
The documentation for this class was generated from the following file:
face_mesh_project.h