MercuryDPM: Eigen::SparseSolverBase< Derived > Class Template Reference
Eigen::SparseSolverBase< Derived > Class Template Reference
Sparse linear algebra » Reference » SparseCore_Module
A base class for sparse solvers.
#include <SparseSolverBase.h>
Public Member Functions
SparseSolverBase ()
SparseSolverBase (SparseSolverBase &&other)
~SparseSolverBase ()
Derived & derived ()
const Derived & derived () const
template<typename Rhs >
const Solve< Derived, Rhs > solve (const MatrixBase< Rhs > &b) const
template<typename Rhs >
const Solve< Derived, Rhs > solve (const SparseMatrixBase< Rhs > &b) const
template<typename Rhs , typename Dest >
void _solve_impl (const SparseMatrixBase< Rhs > &b, SparseMatrixBase< Dest > &dest) const
Protected Attributes
bool m_isInitialized
Additional Inherited Members
Private Member Functions inherited from Eigen::internal::noncopyable
EIGEN_DEVICE_FUNC noncopyable ()
EIGEN_DEVICE_FUNC ~noncopyable ()
Detailed Description
template<typename Derived>
class Eigen::SparseSolverBase< Derived >
A base class for sparse solvers.
Template Parameters
Derived the actual type of the solver.
Constructor & Destructor Documentation
SparseSolverBase() [1/2]
template<typename Derived > Eigen::SparseSolverBase< Derived >::SparseSolverBase () inline
Default constructor
 : m_isInitialized(false) {}
SparseSolverBase() [2/2]
template<typename Derived > Eigen::SparseSolverBase< Derived >::SparseSolverBase (SparseSolverBase< Derived > && other) inline
 : internal::noncopyable{}, m_isInitialized{other.m_isInitialized} {}
~SparseSolverBase()
template<typename Derived > Eigen::SparseSolverBase< Derived >::~SparseSolverBase () inline
 {}
Member Function Documentation
_solve_impl()
template<typename Derived > template<typename Rhs , typename Dest > void Eigen::SparseSolverBase< Derived >::_solve_impl (const SparseMatrixBase< Rhs > & b, SparseMatrixBase< Dest > & dest) const inline
default implementation of solving with a sparse rhs
{
     internal::solve_sparse_through_dense_panels(derived(), b.derived(), dest.derived());
   }
References b, Eigen::SparseSolverBase< Derived >::derived(), Eigen::SparseMatrixBase< Derived >::derived(), and Eigen::internal::solve_sparse_through_dense_panels().
derived() [1/2]
template<typename Derived > Derived& Eigen::SparseSolverBase< Derived >::derived () inline
 { return *static_cast<Derived*>(this); }
Referenced by Eigen::SparseSolverBase< Derived >::_solve_impl(), and Eigen::SparseSolverBase< Derived >::solve().
derived() [2/2]
template<typename Derived > const Derived& Eigen::SparseSolverBase< Derived >::derived () const inline
 { return *static_cast<const Derived*>(this); }
solve() [1/2]
template<typename Derived > template<typename Rhs > const Solve<Derived, Rhs> Eigen::SparseSolverBase< Derived >::solve (const MatrixBase< Rhs > & b) const inline
Returns
an expression of the solution x of \(A x = b \) using the current decomposition of A.
See also
compute()
{
     eigen_assert(m_isInitialized && "Solver is not initialized.");
     eigen_assert(derived().rows() == b.rows() && "solve(): invalid number of rows of the right hand side matrix b");
     return Solve<Derived, Rhs>(derived(), b.derived());
   }
References b, Eigen::SparseSolverBase< Derived >::derived(), eigen_assert, Eigen::SparseSolverBase< Derived >::m_isInitialized, and rows.
Referenced by check_sparse_inverse(), check_sparse_solving(), and main().
solve() [2/2]
template<typename Derived > template<typename Rhs > const Solve<Derived, Rhs> Eigen::SparseSolverBase< Derived >::solve (const SparseMatrixBase< Rhs > & b) const inline
Returns
an expression of the solution x of \(A x = b \) using the current decomposition of A.
See also
compute()
{
     eigen_assert(m_isInitialized && "Solver is not initialized.");
     eigen_assert(derived().rows() == b.rows() && "solve(): invalid number of rows of the right hand side matrix b");
     return Solve<Derived, Rhs>(derived(), b.derived());
   }
References b, Eigen::SparseSolverBase< Derived >::derived(), eigen_assert, Eigen::SparseSolverBase< Derived >::m_isInitialized, and rows.
Member Data Documentation
m_isInitialized
template<typename Derived > bool Eigen::SparseSolverBase< Derived >::m_isInitialized mutable protected
Referenced by Eigen::SparseSolverBase< Derived >::solve(), and Eigen::SparseLUTransposeView< Conjugate, SparseLUType >::SparseLUTransposeView().
The documentation for this class was generated from the following file:
SparseSolverBase.h