MercuryDPM: Flag_definition::TipOfFlag Class Reference
Flag_definition::TipOfFlag Class Reference
GeomObject that defines the tip of the flag.
Public Member Functions
TipOfFlag ()
Constructor.
~TipOfFlag ()
Destructor (empty)
void position (const unsigned &t, const Vector< double > &xi, Vector< double > &r) const
void position (const Vector< double > &xi, Vector< double > &r) const
Current position.
unsigned ngeom_data () const
Number of geometric Data in GeomObject: None.
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual Data * geom_data_pt (const unsigned &j)
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition_dt (const Vector< double > &zeta, const unsigned &j, Vector< double > &drdt)
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
virtual void locate_zeta (const Vector< double > &zeta, GeomObject *&sub_geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
Additional Inherited Members
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Detailed Description
GeomObject that defines the tip of the flag.
Constructor & Destructor Documentation
TipOfFlag()
Flag_definition::TipOfFlag::TipOfFlag () inline
Constructor.
 : GeomObject(1,2) {}
~TipOfFlag()
Flag_definition::TipOfFlag::~TipOfFlag () inline
Destructor (empty)
 {}
Member Function Documentation
ngeom_data()
unsigned Flag_definition::TipOfFlag::ngeom_data () const inline virtual
Number of geometric Data in GeomObject: None.
Reimplemented from oomph::GeomObject.
 {return 0;}
position() [1/2]
void Flag_definition::TipOfFlag::position (const unsigned & t, const Vector< double > & xi, Vector< double > & r) const inline virtual
Return the position This object links the tips of the top and bottom by a straight line whilst xi[0] goes from -H/2 to H/2.
Reimplemented from oomph::GeomObject.
     {
      Vector<double> point_top(upper_tip(Time_pt->time(t)));
      Vector<double> point_bottom(lower_tip(Time_pt->time(t)));
      r[1]= point_bottom[1]+(xi[0]+H/2.0)/H*(point_top[1]-point_bottom[1]);
      r[0]= point_bottom[0]+(xi[0]+H/2.0)/H*(point_top[0]-point_bottom[0]);
     }
References H, Flag_definition::lower_tip(), UniformPSDSelfTest::r, plotPSD::t, oomph::Time::time(), Flag_definition::Time_pt, and Flag_definition::upper_tip().
position() [2/2]
void Flag_definition::TipOfFlag::position (const Vector< double > & xi, Vector< double > & r) const inline virtual
Current position.
Implements oomph::GeomObject.
     {
      return position(0,xi,r);
     }
References UniformPSDSelfTest::r.
The documentation for this class was generated from the following file:
turek_flag_non_fsi.cc