MercuryDPM: File.h File Reference
File.h File Reference
#include <fstream>
#include "GeneralDefine.h"
Classes
class File
Enumerations
enum class FileType : unsigned char { NO_FILE = 0 , ONE_FILE = 1 , MULTIPLE_FILES = 2 , MULTIPLE_FILES_PADDED = 3 }
With FileType options, one is able to choose if data is to be read/written from/into no or single or multiple files.
Functions
std::string to_string_padded (unsigned int value)
Pads the number This function tries to pad the number to 4 digits, which is used when you create multiple files with padded numbers. Any numbers larger than 4 digits return unmodified.
std::ostream & operator<< (std::ostream &os, FileType fileType)
Writes the FileType as a human-readable string into the output stream 'os'.
std::istream & operator>> (std::istream &is, FileType &fileType)
Reads the FileType from an input stream 'is'.
Variables
const unsigned NEVER = static_cast<const unsigned int>(-1)
Enumeration Type Documentation
FileType
enum FileType : unsigned char strong
With FileType options, one is able to choose if data is to be read/written from/into no or single or multiple files.
Enumerator
NO_FILE
file will not be created/read
ONE_FILE
all data will be written into/ read from a single file called name_
MULTIPLE_FILES
each time-step will be written into/read from separate files numbered consecutively: name_.0, name_.1, .. so on
MULTIPLE_FILES_PADDED
each time-step will be written into/read from separate files numbered consecutively, with numbers padded by zeros to a minimum of four digits: name_.0000, name_.0001, ..
 {
             NO_FILE = 0,
             ONE_FILE = 1,
             MULTIPLE_FILES = 2,
             MULTIPLE_FILES_PADDED = 3
 };
Function Documentation
operator<<()
std::ostream& operator<< (std::ostream & os, FileType fileType)
Writes the FileType as a human-readable string into the output stream 'os'.
Parameters
[in,out] os output stream to which the fileType is written
[in] fileType the fileType that has to be written to the output stream
Returns
the output stream "os" that is returned after adding the fileType string
 {
     if (fileType == FileType::NO_FILE)
         os << "NO_FILE";
     else if (fileType == FileType::ONE_FILE)
         os << "ONE_FILE";
     else if (fileType == FileType::MULTIPLE_FILES)
         os << "MULTIPLE_FILES";
     else if (fileType == FileType::MULTIPLE_FILES_PADDED)
         os << "MULTIPLE_FILES_PADDED";
     else
     {
         logger(ERROR, "FileType not recognized");
     }
     return os;
 }
References ERROR, logger, MULTIPLE_FILES, MULTIPLE_FILES_PADDED, NO_FILE, and ONE_FILE.
operator>>()
std::istream& operator>> (std::istream & is, FileType & fileType)
Reads the FileType from an input stream 'is'.
Parameters
[in,out] is The input stream from which the fileType is read
[in] fileType The fileType that has to be read from the input stream
Returns
the input stream "is" (that is returned after the fileType string is read out)
 {
     std::string fileTypeString;
     is >> fileTypeString;
     if (!fileTypeString.compare("NO_FILE"))
         fileType = FileType::NO_FILE;
     else if (!fileTypeString.compare("ONE_FILE"))
         fileType = FileType::ONE_FILE;
     else if (!fileTypeString.compare("MULTIPLE_FILES"))
         fileType = FileType::MULTIPLE_FILES;
     else if (!fileTypeString.compare("MULTIPLE_FILES_PADDED"))
         fileType = FileType::MULTIPLE_FILES_PADDED;
     else
     {
         logger(ERROR, "operator>>: FileType % not recognized", fileTypeString);
     }
     return is;
 }
References ERROR, logger, MULTIPLE_FILES, MULTIPLE_FILES_PADDED, NO_FILE, ONE_FILE, and oomph::Global_string_for_annotation::string().
to_string_padded()
std::string to_string_padded (unsigned int value)
Pads the number This function tries to pad the number to 4 digits, which is used when you create multiple files with padded numbers. Any numbers larger than 4 digits return unmodified.
Parameters
value The value to modify
Returns
A padded string
 {
     std::ostringstream out;
     out << std::setw(4) << std::setfill('0') << value;
     return out.str();
 }
References out(), and Eigen::value.
Referenced by File::getFullName(), and DPMBase::removeOldFiles().
Variable Documentation
NEVER
const unsigned NEVER = static_cast<const unsigned int>(-1)
Todo:
IFCD: can we make this an int instead of unsigned int, as -1 as an unsigned is not good style?
Referenced by BaseCG::BaseCG(), File::File(), CGHandler::finish(), DPMBase::forceWriteOutputFiles(), main(), File::read(), DPMBase::resetFileCounter(), File::saveCurrentTimeStepNoFileTypeCheck(), Calibration::setOutput(), Wall::setupInitialConditions(), and File::writeFirstAndLastTimeStep().