MercuryDPM: BVH.cpp File Reference
BVH.cpp File Reference
#include "main.h"
#include <Eigen/StdVector>
#include <Eigen/Geometry>
#include <unsupported/Eigen/BVH>
Classes
struct Ball< Dim >
struct BallPointStuff< Dim >
struct TreeTest< Dim >
Namespaces
Eigen
Namespace containing all symbols from the Eigen library.
Functions
template<typename Scalar , int Dim>
AlignedBox< Scalar, Dim > Eigen::bounding_box (const Matrix< Scalar, Dim, 1 > &v)
template<int Dim>
AlignedBox< double, Dim > bounding_box (const Ball< Dim > &b)
double SQR (double x)
EIGEN_DECLARE_TEST (BVH)
Function Documentation
bounding_box()
template<int Dim> AlignedBox<double, Dim> bounding_box (const Ball< Dim > & b)
{
   return AlignedBox<double, Dim>(b.center.array() - b.radius, b.center.array() + b.radius);
 }
References b.
EIGEN_DECLARE_TEST()
EIGEN_DECLARE_TEST (BVH)
{
   for (int i = 0; i < g_repeat; i++) {
 #ifdef EIGEN_TEST_PART_1
     TreeTest<2> test2;
     CALL_SUBTEST(test2.testIntersect1());
     CALL_SUBTEST(test2.testMinimize1());
     CALL_SUBTEST(test2.testIntersect2());
     CALL_SUBTEST(test2.testMinimize2());
 #endif
 #ifdef EIGEN_TEST_PART_2
     TreeTest<3> test3;
     CALL_SUBTEST(test3.testIntersect1());
     CALL_SUBTEST(test3.testMinimize1());
     CALL_SUBTEST(test3.testIntersect2());
     CALL_SUBTEST(test3.testMinimize2());
 #endif
 #ifdef EIGEN_TEST_PART_3
     TreeTest<4> test4;
     CALL_SUBTEST(test4.testIntersect1());
     CALL_SUBTEST(test4.testMinimize1());
     CALL_SUBTEST(test4.testIntersect2());
     CALL_SUBTEST(test4.testMinimize2());
 #endif
   }
 }
References CALL_SUBTEST, Eigen::g_repeat, i, test2(), TreeTest< Dim >::testIntersect1(), TreeTest< Dim >::testIntersect2(), TreeTest< Dim >::testMinimize1(), and TreeTest< Dim >::testMinimize2().
SQR()
double SQR (double x) inline
 { return x * x; }
References plotDoE::x.
Referenced by BallPointStuff< Dim >::intersectObject(), BallPointStuff< Dim >::intersectObjectObject(), BallPointStuff< Dim >::intersectObjectVolume(), BallPointStuff< Dim >::intersectVolumeObject(), BallPointStuff< Dim >::minimumOnObject(), BallPointStuff< Dim >::minimumOnObjectObject(), BallPointStuff< Dim >::minimumOnObjectVolume(), and BallPointStuff< Dim >::minimumOnVolumeObject().