MercuryDPM: Eigen::internal::TensorCwiseBinaryBlock< BinaryOp, LhsTensorBlock, RhsTensorBlock > Class Template Reference
Eigen::internal::TensorCwiseBinaryBlock< BinaryOp, LhsTensorBlock, RhsTensorBlock > Class Template Reference
#include <TensorBlock.h>
Public Types
typedef std::conditional_t< NoArgBlockAccess, void, TensorCwiseBinaryOp< BinaryOp, const typename LhsTensorBlock::XprType, const typename RhsTensorBlock::XprType > > XprType
typedef XprScalar< XprType >::type Scalar
Public Member Functions
TensorCwiseBinaryBlock (const LhsTensorBlock &left_block, const RhsTensorBlock &right_block, const BinaryOp &functor)
TensorBlockKind kind () const
XprType expr () const
const Scalar * data () const
void cleanup ()
Private Attributes
LhsTensorBlock m_left_block
RhsTensorBlock m_right_block
BinaryOp m_functor
Static Private Attributes
static constexpr bool NoArgBlockAccess
Member Typedef Documentation
Scalar
template<typename BinaryOp , typename LhsTensorBlock , typename RhsTensorBlock > typedef XprScalar<XprType>::type Eigen::internal::TensorCwiseBinaryBlock< BinaryOp, LhsTensorBlock, RhsTensorBlock >::Scalar
XprType
template<typename BinaryOp , typename LhsTensorBlock , typename RhsTensorBlock > typedef std::conditional_t< NoArgBlockAccess, void, TensorCwiseBinaryOp<BinaryOp, const typename LhsTensorBlock::XprType, const typename RhsTensorBlock::XprType> > Eigen::internal::TensorCwiseBinaryBlock< BinaryOp, LhsTensorBlock, RhsTensorBlock >::XprType
Constructor & Destructor Documentation
TensorCwiseBinaryBlock()
template<typename BinaryOp , typename LhsTensorBlock , typename RhsTensorBlock > Eigen::internal::TensorCwiseBinaryBlock< BinaryOp, LhsTensorBlock, RhsTensorBlock >::TensorCwiseBinaryBlock (const LhsTensorBlock & left_block, const RhsTensorBlock & right_block, const BinaryOp & functor) inline
       : m_left_block(left_block), m_right_block(right_block), m_functor(functor) {}
Member Function Documentation
cleanup()
template<typename BinaryOp , typename LhsTensorBlock , typename RhsTensorBlock > void Eigen::internal::TensorCwiseBinaryBlock< BinaryOp, LhsTensorBlock, RhsTensorBlock >::cleanup () inline
                  {
     m_left_block.cleanup();
     m_right_block.cleanup();
   }
References Eigen::internal::TensorCwiseBinaryBlock< BinaryOp, LhsTensorBlock, RhsTensorBlock >::m_left_block, and Eigen::internal::TensorCwiseBinaryBlock< BinaryOp, LhsTensorBlock, RhsTensorBlock >::m_right_block.
Referenced by framework.Frame::__init__().
data()
template<typename BinaryOp , typename LhsTensorBlock , typename RhsTensorBlock > const Scalar* Eigen::internal::TensorCwiseBinaryBlock< BinaryOp, LhsTensorBlock, RhsTensorBlock >::data () const inline
 { return NULL; }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
expr()
template<typename BinaryOp , typename LhsTensorBlock , typename RhsTensorBlock > XprType Eigen::internal::TensorCwiseBinaryBlock< BinaryOp, LhsTensorBlock, RhsTensorBlock >::expr () const inline
 { return XprType(m_left_block.expr(), m_right_block.expr(), m_functor); }
References Eigen::internal::TensorCwiseBinaryBlock< BinaryOp, LhsTensorBlock, RhsTensorBlock >::m_functor, Eigen::internal::TensorCwiseBinaryBlock< BinaryOp, LhsTensorBlock, RhsTensorBlock >::m_left_block, and Eigen::internal::TensorCwiseBinaryBlock< BinaryOp, LhsTensorBlock, RhsTensorBlock >::m_right_block.
kind()
template<typename BinaryOp , typename LhsTensorBlock , typename RhsTensorBlock > TensorBlockKind Eigen::internal::TensorCwiseBinaryBlock< BinaryOp, LhsTensorBlock, RhsTensorBlock >::kind () const inline
 { return internal::TensorBlockKind::kExpr; }
References Eigen::internal::kExpr.
Member Data Documentation
m_functor
template<typename BinaryOp , typename LhsTensorBlock , typename RhsTensorBlock > BinaryOp Eigen::internal::TensorCwiseBinaryBlock< BinaryOp, LhsTensorBlock, RhsTensorBlock >::m_functor private
Referenced by Eigen::internal::TensorCwiseBinaryBlock< BinaryOp, LhsTensorBlock, RhsTensorBlock >::expr().
m_left_block
template<typename BinaryOp , typename LhsTensorBlock , typename RhsTensorBlock > LhsTensorBlock Eigen::internal::TensorCwiseBinaryBlock< BinaryOp, LhsTensorBlock, RhsTensorBlock >::m_left_block private
Referenced by Eigen::internal::TensorCwiseBinaryBlock< BinaryOp, LhsTensorBlock, RhsTensorBlock >::cleanup(), and Eigen::internal::TensorCwiseBinaryBlock< BinaryOp, LhsTensorBlock, RhsTensorBlock >::expr().
m_right_block
template<typename BinaryOp , typename LhsTensorBlock , typename RhsTensorBlock > RhsTensorBlock Eigen::internal::TensorCwiseBinaryBlock< BinaryOp, LhsTensorBlock, RhsTensorBlock >::m_right_block private
Referenced by Eigen::internal::TensorCwiseBinaryBlock< BinaryOp, LhsTensorBlock, RhsTensorBlock >::cleanup(), and Eigen::internal::TensorCwiseBinaryBlock< BinaryOp, LhsTensorBlock, RhsTensorBlock >::expr().
NoArgBlockAccess
template<typename BinaryOp , typename LhsTensorBlock , typename RhsTensorBlock > constexpr bool Eigen::internal::TensorCwiseBinaryBlock< BinaryOp, LhsTensorBlock, RhsTensorBlock >::NoArgBlockAccess static constexpr private
Initial value:
= internal::is_void<typename LhsTensorBlock::XprType>::value ||
                                           internal::is_void<typename RhsTensorBlock::XprType>::value
The documentation for this class was generated from the following file:
TensorBlock.h