MercuryDPM: oomph::AlgebraicChannelWithLeafletMesh< ELEMENT > Class Template Reference
oomph::AlgebraicChannelWithLeafletMesh< ELEMENT > Class Template Reference
#include <channel_with_leaflet_mesh.template.h>
Public Member Functions
AlgebraicChannelWithLeafletMesh (GeomObject *leaflet_pt, const double &lleft, const double &lright, const double &hleaflet, const double &htot, const unsigned &nleft, const unsigned &nright, const unsigned &ny1, const unsigned &ny2, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
virtual ~AlgebraicChannelWithLeafletMesh ()
Destructor: empty.
void update_node_update (AlgebraicNode *&node_pt)
void algebraic_node_update (const unsigned &t, AlgebraicNode *&node_pt)
Perform algebraic node update.
Public Member Functions inherited from oomph::AlgebraicMesh
AlgebraicMesh ()
AlgebraicMesh (const AlgebraicMesh &)=delete
Broken copy constructor.
~AlgebraicMesh ()
Broken assignment operator.
AlgebraicNode * node_pt (const unsigned long &n)
Return a pointer to the n-th global AlgebraicNode.
void node_update (const bool &update_all_solid_nodes=false)
unsigned self_test ()
Self test: check consistentency of multiple node updates.
void add_geom_object_list_pt (GeomObject *geom_object_pt)
unsigned ngeom_object_list_pt ()
Return number of geometric objects associated with AlgebraicMesh.
GeomObject * geom_object_list_pt (const unsigned &i)
Access function to the ith GeomObject.
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Public Member Functions inherited from oomph::ChannelWithLeafletMesh< ELEMENT >
ChannelWithLeafletMesh (GeomObject *leaflet_pt, const double &lleft, const double &lright, const double &hleaflet, const double &htot, const unsigned &nleft, const unsigned &nright, const unsigned &ny1, const unsigned &ny2, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
virtual ~ChannelWithLeafletMesh ()
Destructor : empty.
ChannelWithLeafletDomain * domain_pt ()
Access function to domain.
Public Member Functions inherited from oomph::SimpleRectangularQuadMesh< ELEMENT >
SimpleRectangularQuadMesh (const unsigned &Nx, const unsigned &Ny, const double &Lx, const double &Ly, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
const unsigned & nx () const
Access function for number of elements in x directions.
const unsigned & ny () const
Access function for number of elements in y directions.
Public Member Functions inherited from oomph::QuadMeshBase
QuadMeshBase ()
Constructor (empty)
QuadMeshBase (const QuadMeshBase &node)=delete
Broken copy constructor.
void operator= (const QuadMeshBase &)=delete
Broken assignment operator.
virtual ~QuadMeshBase ()
Destructor (empty)
void setup_boundary_element_info ()
void setup_boundary_element_info (std::ostream &outfile)
Protected Member Functions
void setup_algebraic_node_update ()
Function to setup the algebraic node update.
void node_update_I (const unsigned &t, AlgebraicNode *&node_pt)
Update function for nodes in lower left region (I)
void node_update_II (const unsigned &t, AlgebraicNode *&node_pt)
Update function for nodes in lower right region (II)
void node_update_III (const unsigned &t, AlgebraicNode *&node_pt)
Update function for nodes in upper left region (III)
void node_update_IV (const unsigned &t, AlgebraicNode *&node_pt)
Update function for nodes in upper right region (IV)
void slanted_bound_up (const unsigned &t, const Vector< double > &zeta, Vector< double > &r)
Helper function.
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Protected Attributes
double X_0
double Hleaflet
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Protected Attributes inherited from oomph::ChannelWithLeafletMesh< ELEMENT >
ChannelWithLeafletDomain * Domain_pt
Pointer to domain.
GeomObject * Leaflet_pt
Pointer to GeomObject that represents the leaflet.
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Detailed Description
template<class ELEMENT>
class oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >
//////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// Algebraic version of ChannelWithLeafletMesh. Leaflet is assumed to be in its undeformed (straight vertical) position when the algebraic node update is set up.
Constructor & Destructor Documentation
AlgebraicChannelWithLeafletMesh()
template<class ELEMENT > oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::AlgebraicChannelWithLeafletMesh (GeomObject * leaflet_pt, const double & lleft, const double & lright, const double & hleaflet, const double & htot, const unsigned & nleft, const unsigned & nright, const unsigned & ny1, const unsigned & ny2, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) inline
Constructor: Pass pointer to GeomObject that represents the leaflet, the length of the domain to left and right of the leaflet, the height of the leaflet and the overall height of the channel, the number of element columns to the left and right of the leaflet, the number of rows of elements from the bottom of the channel to the end of the leaflet, the number of rows of elements above the end of the leaflet. Timestepper defaults to Steady default Timestepper defined in the Mesh base class
       : ChannelWithLeafletMesh<ELEMENT>(leaflet_pt,
                                         lleft,
                                         lright,
                                         hleaflet,
                                         htot,
                                         nleft,
                                         nright,
                                         ny1,
                                         ny2,
                                         time_stepper_pt)
     {
       // Store origin of leaflet for fast reference
       Vector<double> zeta(1);
       zeta[0] = 0.0;
       Vector<double> r(2);
       this->Leaflet_pt->position(zeta, r);
       X_0 = r[0];
       // Store length of the leaflet for fast access (it's also available
       // through the domain, of course)
       Hleaflet = hleaflet;
       // Add the geometric object to the list associated with this AlgebraicMesh
       AlgebraicMesh::add_geom_object_list_pt(leaflet_pt);
       // Setup algebraic node update operations
       setup_algebraic_node_update();
     }
References oomph::AlgebraicMesh::add_geom_object_list_pt(), oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::Hleaflet, oomph::ChannelWithLeafletMesh< ELEMENT >::Leaflet_pt, oomph::GeomObject::position(), UniformPSDSelfTest::r, oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::setup_algebraic_node_update(), oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::X_0, and Eigen::zeta().
~AlgebraicChannelWithLeafletMesh()
template<class ELEMENT > virtual oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::~AlgebraicChannelWithLeafletMesh () inline virtual
Destructor: empty.
 {}
Member Function Documentation
algebraic_node_update()
template<class ELEMENT > void oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::algebraic_node_update (const unsigned & t, AlgebraicNode *& node_pt) virtual
Perform algebraic node update.
Update nodal position at time level t (t=0: present; t>0: previous)
Implements oomph::AlgebraicMesh.
   {
     unsigned id = node_pt->node_update_fct_id();
     switch (id)
     {
       case 1:
         node_update_I(t, node_pt);
         break;
       case 2:
         node_update_II(t, node_pt);
         break;
       case 3:
         node_update_III(t, node_pt);
         break;
       case 4:
         node_update_IV(t, node_pt);
         break;
       default:
         std::ostringstream error_message;
         error_message << "The node update fct id is " << id
                       << ", but it should only be one of " << 1 << ", " << 2
                       << ", " << 3 << " or " << 4 << std::endl;
         std::string function_name =
           "AlgebraicChannelWithLeafletMesh::algebraic_node_update()";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
     }
   } // end of algebraic_node_update()
References oomph::AlgebraicNode::node_update_fct_id(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::Global_string_for_annotation::string(), and plotPSD::t.
node_update_I()
template<class ELEMENT > void oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::node_update_I (const unsigned & t, AlgebraicNode *& node_pt) protected
Update function for nodes in lower left region (I)
Node update for region I.
   {
     // relevant data of the domain for part I
     double lleft = this->domain_pt()->lleft();
     // Extract reference values for update by copy construction
     Vector<double> ref_value(node_pt->vector_ref_value());
     // Extract geometric objects for update by copy construction
     Vector<GeomObject*> geom_object_pt(node_pt->vector_geom_object_pt());
     // Pointer to wall geom object
     GeomObject* leaflet_pt = geom_object_pt[0];
     // Coordinates of the steady node on the left boundary
     // corresponding to the current node
     double y0 = ref_value[0];
     double x0 = -lleft + X_0;
     // second reference value: local coordinate on wall
     Vector<double> s(1);
     s[0] = ref_value[1];
     // Get position vector to wall at timestep t
     Vector<double> r_wall(2);
     leaflet_pt->position(t, s, r_wall);
     // Third reference value : fraction of the horizontal line
     // between the edge and the wall
     double r = ref_value[2];
     // Assign new nodal coordinates
     node_pt->x(t, 0) = x0 + r * (r_wall[0] - x0);
     node_pt->x(t, 1) = y0 + r * (r_wall[1] - y0);
   }
References oomph::GeomObject::position(), UniformPSDSelfTest::r, s, plotPSD::t, oomph::AlgebraicNode::vector_geom_object_pt(), oomph::AlgebraicNode::vector_ref_value(), oomph::Node::x(), Global::x0, and TanhSolnForPoisson::X_0.
node_update_II()
template<class ELEMENT > void oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::node_update_II (const unsigned & t, AlgebraicNode *& node_pt) protected
Update function for nodes in lower right region (II)
Node update for region II.
   {
     // relevant data of the domain for part II
     double lright = this->domain_pt()->lright();
     // Extract reference values for update by copy construction
     Vector<double> ref_value(node_pt->vector_ref_value());
     // Extract geometric objects for update by copy construction
     Vector<GeomObject*> geom_object_pt(node_pt->vector_geom_object_pt());
     // Pointer to wall geom object
     GeomObject* leaflet_pt = geom_object_pt[0];
     // Coordinates of the steady node on the right boundary
     // corresponding to the current node
     double y0 = ref_value[0];
     double x0 = X_0 + lright;
     // Second reference value: Zeta coordinate on wall
     Vector<double> s(1);
     s[0] = ref_value[1];
     // Get position vector to wall at timestep t
     Vector<double> r_wall(2);
     leaflet_pt->position(t, s, r_wall);
     // Third reference value : fraction of the horizontal line
     // between the wall and the right edge
     double r = ref_value[2];
     // Assign new nodal coordinates
     node_pt->x(t, 0) = r_wall[0] + r * (x0 - r_wall[0]);
     node_pt->x(t, 1) = r_wall[1] + r * (y0 - r_wall[1]);
   }
References oomph::GeomObject::position(), UniformPSDSelfTest::r, s, plotPSD::t, oomph::AlgebraicNode::vector_geom_object_pt(), oomph::AlgebraicNode::vector_ref_value(), oomph::Node::x(), Global::x0, and TanhSolnForPoisson::X_0.
node_update_III()
template<class ELEMENT > void oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::node_update_III (const unsigned & t, AlgebraicNode *& node_pt) protected
Update function for nodes in upper left region (III)
Node update for region III.
   {
     // relevant data of the domain for part I
     double lleft = this->domain_pt()->lleft();
     // Extract reference values for update by copy construction
     Vector<double> ref_value(node_pt->vector_ref_value());
     // Coordinates of the steady node on the left boundary
     // corresponding to the current node
     double y0 = ref_value[0];
     double x0 = -lleft + X_0;
     Vector<double> s(1);
     s[0] = ref_value[1];
     // Get position vector
     Vector<double> r_line(2);
     slanted_bound_up(t, s, r_line);
     // Third reference value : fraction of the horizontal line
     // between the edge and the middle line
     double r = ref_value[2];
     // Assign new nodal coordinates
     node_pt->x(t, 0) = x0 + r * (r_line[0] - x0);
     node_pt->x(t, 1) = y0 + r * (r_line[1] - y0);
   }
References UniformPSDSelfTest::r, s, plotPSD::t, oomph::AlgebraicNode::vector_ref_value(), oomph::Node::x(), Global::x0, and TanhSolnForPoisson::X_0.
node_update_IV()
template<class ELEMENT > void oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::node_update_IV (const unsigned & t, AlgebraicNode *& node_pt) protected
Update function for nodes in upper right region (IV)
Node update for region IV.
   {
     // relevant data of the domain for part I
     double lright = this->domain_pt()->lright();
     // Extract reference values for update by copy construction
     Vector<double> ref_value(node_pt->vector_ref_value());
     // Coordinates of the steady node on the left boundary
     // corresponding to the current node
     double y0 = ref_value[0];
     double x0 = X_0 + lright;
     // Second reference value: Zeta coordinate on the middle line
     Vector<double> s(1);
     s[0] = ref_value[1];
     // Get position vector  at timestep t
     Vector<double> r_line(2);
     slanted_bound_up(t, s, r_line);
     // Third reference value : fraction of the horizontal line
     // between the middle line and the right edge
     double r = ref_value[2];
     // Assign new nodal coordinates
     node_pt->x(t, 0) = r_line[0] + r * (x0 - r_line[0]);
     node_pt->x(t, 1) = r_line[1] + r * (y0 - r_line[1]);
   }
References UniformPSDSelfTest::r, s, plotPSD::t, oomph::AlgebraicNode::vector_ref_value(), oomph::Node::x(), Global::x0, and TanhSolnForPoisson::X_0.
setup_algebraic_node_update()
template<class ELEMENT > void oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::setup_algebraic_node_update protected
Function to setup the algebraic node update.
//////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// Setup algebraic node update. Leaflet is assumed to be in its undeformed (straight vertical) position!
   {
     // Extract some reference lengths from the Domain.
     double hleaflet = this->domain_pt()->hleaflet();
     double htot = this->domain_pt()->htot();
     double lleft = this->domain_pt()->lleft();
     double lright = this->domain_pt()->lright();
     // Loop over all nodes in mesh
     unsigned nnod = this->nnode();
     for (unsigned j = 0; j < nnod; j++)
     {
       // Get pointer to node
       AlgebraicNode* nod_pt = node_pt(j);
       // Get coordinates
       double x = nod_pt->x(0);
       double y = nod_pt->x(1);
       // Quick check to know if the wall is in its undeformed position
       // It actually checks that the top of the wall is in (x_0,hleaflet)
       Vector<double> zeta(1);
       Vector<double> r(2);
       zeta[0] = Hleaflet;
       this->Leaflet_pt->position(zeta, r);
       if ((r[0] != X_0) || (r[1] != hleaflet))
       {
         std::ostringstream error_stream;
         error_stream << "Wall must be in its undeformed position when\n"
                      << "algebraic node update information is set up!\n "
                      << r[0] << " " << X_0 << " " << r[1] << " " << hleaflet
                      << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
       // The update function requires four parameters:
       Vector<double> ref_value(4);
       // Part I
       if ((x <= X_0) && (y <= hleaflet))
       {
         // First reference value: y0
         ref_value[0] = y;
         // zeta coordinate on wall : fourth reference value
         //(needed for adaptativity)
         Vector<double> zeta(1);
         zeta[0] = y;
         ref_value[3] = zeta[0];
         // Sub-geomobject corresponding to the zeta coordinate on the wall
         GeomObject* geom_obj_pt;
         Vector<double> s(1);
         this->Leaflet_pt->locate_zeta(zeta, geom_obj_pt, s);
         // Create vector of geomobject for add_node_update_info()
         Vector<GeomObject*> geom_object_pt(1);
         geom_object_pt[0] = geom_obj_pt;
         // Second  reference value: Reference local coordinate
         // in the sub-geomobject
         ref_value[1] = s[0];
         // Third reference value:fraction of the horizontal line
         // between the edge and the wall
         ref_value[2] = (lleft + x - X_0) / lleft;
         // Setup algebraic update for node: Pass update information
         // to AlgebraicNode:
         nod_pt->add_node_update_info(1, // ID
                                      this, // mesh
                                      geom_object_pt, // vector of geom objects
                                      ref_value); // vector of ref. values
       }
       // Part II
       if ((x >= X_0) && (y <= hleaflet))
       {
         // First reference value: y0
         ref_value[0] = y;
         // zeta coordinate on wall: fourth reference value
         //(needed for adaptativity)
         Vector<double> zeta(1);
         zeta[0] = y;
         ref_value[3] = zeta[0];
         // Sub-geomobject corresponding to the zeta coordinate on the wall
         GeomObject* geom_obj_pt;
         Vector<double> s(1);
         this->Leaflet_pt->locate_zeta(zeta, geom_obj_pt, s);
         // Create vector of geomobject for add_node_update_info()
         Vector<GeomObject*> geom_object_pt(1);
         geom_object_pt[0] = geom_obj_pt;
         // Second  reference value: Reference local coordinate
         // in the sub-geomobject
         ref_value[1] = s[0];
         // Third reference value:fraction of the horizontal line
         // between the edge and the wall
         ref_value[2] = (x - X_0) / lright;
         // Setup algebraic update for node: Pass update information
         // to AlgebraicNode:
         nod_pt->add_node_update_info(2, // ID
                                      this, // mesh
                                      geom_object_pt, // vector of geom objects
                                      ref_value); // vector of ref. values
       }
       // Part III
       if ((x <= X_0) && (y >= hleaflet))
       {
         // First reference value: y0
         ref_value[0] = y;
         // Second reference value: zeta coordinate on the middle line
         ref_value[1] = (y - hleaflet) / (htot - hleaflet);
         // Third reference value:fraction of the horizontal line
         // between the edge and the middle line
         ref_value[2] = (lleft + x - X_0) / lleft;
         // geomobject
         Vector<GeomObject*> geom_object_pt(1);
         geom_object_pt[0] = this->Leaflet_pt;
         // Setup algebraic update for node: Pass update information
         // to AlgebraicNode:
         nod_pt->add_node_update_info(3, // ID
                                      this, // mesh
                                      geom_object_pt, // vector of geom objects
                                      ref_value); // vector of ref. values
       }
       // Part IV
       if ((x >= X_0) && (y >= hleaflet))
       {
         // First reference value: y0
         ref_value[0] = y;
         // Second reference value: zeta coordinate on wall
         ref_value[1] = (y - hleaflet) / (htot - hleaflet);
         // Third reference value:fraction of the horizontal line
         // between the edge and the wall
         ref_value[2] = (x - X_0) / lright;
         // geomobject
         Vector<GeomObject*> geom_object_pt(1);
         geom_object_pt[0] = this->Leaflet_pt;
         // Setup algebraic update for node: Pass update information
         // to AlgebraicNode:
         nod_pt->add_node_update_info(4, // ID
                                      this, // mesh
                                      geom_object_pt, // vector of geom objects
                                      ref_value); // vector of ref. values
       }
     }
   } // end of setup_algebraic_node_update
References oomph::AlgebraicNode::add_node_update_info(), j, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, UniformPSDSelfTest::r, s, plotDoE::x, oomph::Node::x(), TanhSolnForPoisson::X_0, y, and Eigen::zeta().
Referenced by oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::AlgebraicChannelWithLeafletMesh().
slanted_bound_up()
template<class ELEMENT > void oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::slanted_bound_up (const unsigned & t, const Vector< double > & zeta, Vector< double > & r) protected
Helper function.
Slanted bound : helper function.
Coordinates of the point on the boundary beetween the upper and the lower part, in the same column, at the east.
   {
     double htot = this->domain_pt()->htot();
     Vector<double> xi(1);
     xi[0] = Hleaflet;
     Vector<double> r_join(2);
     this->Leaflet_pt->position(t, xi, r_join);
     r[0] = r_join[0] + zeta[0] * (X_0 - r_join[0]);
     r[1] = r_join[1] + zeta[0] * (htot - r_join[1]);
   }
References UniformPSDSelfTest::r, plotPSD::t, TanhSolnForPoisson::X_0, and Eigen::zeta().
update_node_update()
template<class ELEMENT > void oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::update_node_update (AlgebraicNode *& node_pt) inline virtual
Update the geometric references that are used to update node after mesh adaptation. Empty – no update of node update required without adaptivity
Implements oomph::AlgebraicMesh.
Reimplemented in oomph::RefineableAlgebraicChannelWithLeafletMesh< ELEMENT >.
 {}
Member Data Documentation
Hleaflet
template<class ELEMENT > double oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::Hleaflet protected
Length of the leaflet (stored explicitly for reference in algebraic node update – it's also stored independently in domain....)
Referenced by oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::AlgebraicChannelWithLeafletMesh().
X_0
template<class ELEMENT > double oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::X_0 protected
Origin of the wall (stored explicitly for reference in algebraic node update – it's also stored independently in domain....)
Referenced by oomph::AlgebraicChannelWithLeafletMesh< ELEMENT >::AlgebraicChannelWithLeafletMesh().
The documentation for this class was generated from the following files:
channel_with_leaflet_mesh.template.h
channel_with_leaflet_mesh.template.cc