MercuryDPM: oomph::RefineableSolidElement Class Reference
oomph::RefineableSolidElement Class Reference
#include <refineable_elements.h>
Public Member Functions
RefineableSolidElement ()
Constructor.
virtual ~RefineableSolidElement ()
Virtual Destructor, delete any allocated storage.
void assign_solid_local_eqn_numbers (const bool &store_local_dof_pt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void identify_geometric_data (std::set< Data * > &geometric_data_pt)
void fill_in_jacobian_from_solid_position_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
bool is_undeformed_macro_element_used_for_new_lagrangian_coords () const
void enable_use_of_undeformed_macro_element_for_new_lagrangian_coords ()
void disable_use_of_undeformed_macro_element_for_new_lagrangian_coords ()
DenseMatrix< int > & local_position_hang_eqn (Node *const &node_pt)
virtual void further_build ()
Public Member Functions inherited from oomph::RefineableElement
RefineableElement ()
virtual ~RefineableElement ()
Destructor, delete the allocated storage for the hanging equations.
RefineableElement (const RefineableElement &)=delete
Broken copy constructor.
void operator= (const RefineableElement &)=delete
Broken assignment operator.
Tree * tree_pt ()
Access function: Pointer to quadtree representation of this element.
void set_tree_pt (Tree *my_tree_pt)
Set pointer to quadtree representation of this element.
virtual unsigned required_nsons () const
bool refinement_is_enabled ()
Flag to indicate suppression of any refinement.
void disable_refinement ()
Suppress of any refinement for this element.
void enable_refinement ()
Emnable refinement for this element.
template<class ELEMENT >
void split (Vector< ELEMENT * > &son_pt) const
int local_hang_eqn (Node *const &node_pt, const unsigned &i)
virtual void build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt, bool &was_already_built, std::ofstream &new_nodes_file)=0
void set_refinement_level (const int &refine_level)
Set the refinement level.
unsigned refinement_level () const
Return the Refinement level.
void select_for_refinement ()
Select the element for refinement.
void deselect_for_refinement ()
Deselect the element for refinement.
void select_sons_for_unrefinement ()
Unrefinement will be performed by merging the four sons of this element.
void deselect_sons_for_unrefinement ()
bool to_be_refined ()
Has the element been selected for refinement?
bool sons_to_be_unrefined ()
Has the element been selected for unrefinement?
virtual void rebuild_from_sons (Mesh *&mesh_pt)=0
virtual void unbuild ()
virtual void deactivate_element ()
virtual bool nodes_built ()
Return true if all the nodes have been built, false if not.
long number () const
Element number (for debugging/plotting)
void set_number (const long &mynumber)
Set element number (for debugging/plotting)
virtual unsigned ncont_interpolated_values () const =0
virtual void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
virtual void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)=0
virtual Node * interpolating_node_pt (const unsigned &n, const int &value_id)
virtual double local_one_d_fraction_of_interpolating_node (const unsigned &n1d, const unsigned &i, const int &value_id)
virtual Node * get_interpolating_node_at_local_coordinate (const Vector< double > &s, const int &value_id)
virtual unsigned ninterpolating_node (const int &value_id)
virtual unsigned ninterpolating_node_1d (const int &value_id)
virtual void interpolating_basis (const Vector< double > &s, Shape &psi, const int &value_id) const
virtual void check_integrity (double &max_error)=0
void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual RefineableElement * root_element_pt ()
virtual RefineableElement * father_element_pt () const
Return a pointer to the father element.
void get_father_at_refinement_level (unsigned &refinement_level, RefineableElement *&father_at_reflevel_pt)
virtual void initial_setup (Tree *const &adopted_father_pt=0, const unsigned &initial_p_order=0)
virtual void pre_build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt)
Pre-build the element.
virtual void setup_hanging_nodes (Vector< std::ofstream * > &output_stream)
virtual void further_setup_hanging_nodes ()
void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
unsigned nshape_controlling_nodes ()
std::map< Node *, unsigned > shape_controlling_node_lookup ()
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void disable_ALE ()
virtual void enable_ALE ()
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual unsigned nvertex_node () const
virtual Node * vertex_node_pt (const unsigned &j) const
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (std::ostream &outfile)
virtual void output (std::ostream &outfile, const unsigned &n_plot)
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output (FILE *file_pt)
virtual void output (FILE *file_pt, const unsigned &n_plot)
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output an exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output a time-dependent exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::SolidFiniteElement
void set_lagrangian_dimension (const unsigned &lagrangian_dimension)
virtual bool has_internal_solid_data ()
SolidFiniteElement ()
Constructor: Set defaults.
virtual ~SolidFiniteElement ()
Destructor to clean up any allocated memory.
SolidFiniteElement (const SolidFiniteElement &)=delete
Broken copy constructor.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_x_and_xi (const Vector< double > &s, Vector< double > &x_fe, Vector< double > &x, Vector< double > &xi_fe, Vector< double > &xi) const
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt, MacroElement *undeformed_macro_elem_pt)
void set_undeformed_macro_elem_pt (MacroElement *undeformed_macro_elem_pt)
MacroElement * undeformed_macro_elem_pt ()
Access function to pointer to "undeformed" macro element.
double dshape_lagrangian (const Vector< double > &s, Shape &psi, DShape &dpsidxi) const
virtual double dshape_lagrangian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidxi) const
double d2shape_lagrangian (const Vector< double > &s, Shape &psi, DShape &dpsidxi, DShape &d2psidxi) const
virtual double d2shape_lagrangian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidxi, DShape &d2psidxi) const
unsigned lagrangian_dimension () const
unsigned nnodal_lagrangian_type () const
Node * construct_node (const unsigned &n)
Construct the local node n and return a pointer to it.
Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
Node * construct_boundary_node (const unsigned &n)
Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
double raw_lagrangian_position (const unsigned &n, const unsigned &i) const
double raw_lagrangian_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double lagrangian_position (const unsigned &n, const unsigned &i) const
Return i-th Lagrangian coordinate at local node n.
double lagrangian_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
virtual double interpolated_xi (const Vector< double > &s, const unsigned &i) const
virtual void interpolated_xi (const Vector< double > &s, Vector< double > &xi) const
virtual void interpolated_dxids (const Vector< double > &s, DenseMatrix< double > &dxids) const
virtual void J_lagrangian (const Vector< double > &s) const
virtual double J_lagrangian_at_knot (const unsigned &ipt) const
SolidInitialCondition *& solid_ic_pt ()
Pointer to object that describes the initial condition.
void enable_solve_for_consistent_newmark_accel ()
void disable_solve_for_consistent_newmark_accel ()
Set to reset the problem being solved to be the standard problem.
MultiplierFctPt & multiplier_fct_pt ()
MultiplierFctPt multiplier_fct_pt () const
virtual void get_residuals_for_solid_ic (Vector< double > &residuals)
void fill_in_residuals_for_solid_ic (Vector< double > &residuals)
void fill_in_jacobian_for_solid_ic (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_for_newmark_accel (DenseMatrix< double > &jacobian)
void compute_norm (double &el_norm)
int position_local_eqn (const unsigned &n, const unsigned &k, const unsigned &j) const
Protected Member Functions
void assemble_local_to_lagrangian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
void assemble_local_to_lagrangian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
double local_to_lagrangian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Protected Member Functions inherited from oomph::RefineableElement
void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
void assign_hanging_local_eqn_numbers (const bool &store_local_dof_pt)
Assign the local equation numbers for hanging node variables.
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Protected Member Functions inherited from oomph::FiniteElement
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
virtual void fill_in_contribution_to_residuals (Vector< double > &residuals)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Member Functions inherited from oomph::SolidFiniteElement
void fill_in_generic_jacobian_for_solid_ic (Vector< double > &residuals, DenseMatrix< double > &jacobian, const unsigned &flag)
void set_nnodal_lagrangian_type (const unsigned &nlagrangian_type)
virtual double local_to_lagrangian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_lagrangian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
void describe_solid_local_dofs (std::ostream &out, const std::string &current_string) const
Classifies dofs locally for solid specific aspects.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_solid_position_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_solid_position_fd ()
virtual void reset_after_solid_position_fd ()
virtual void update_in_solid_position_fd (const unsigned &i)
virtual void reset_in_solid_position_fd (const unsigned &i)
Protected Attributes
bool Use_undeformed_macro_element_for_new_lagrangian_coords
Protected Attributes inherited from oomph::RefineableElement
Tree * Tree_pt
A pointer to a general tree object.
unsigned Refine_level
Refinement level.
bool To_be_refined
Flag for refinement.
bool Refinement_is_enabled
Flag to indicate suppression of any refinement.
bool Sons_to_be_unrefined
Flag for unrefinement.
long Number
Global element number – for plotting/validation purposes.
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Protected Attributes inherited from oomph::SolidFiniteElement
MacroElement * Undeformed_macro_elem_pt
Pointer to the element's "undeformed" macro element (NULL by default)
SolidInitialCondition * Solid_ic_pt
Pointer to object that specifies the initial condition.
bool Solve_for_consistent_newmark_accel_flag
Private Member Functions
void assign_solid_hanging_local_eqn_numbers (const bool &store_local_dof_pt)
Private Attributes
std::map< Node *, DenseMatrix< int > > Local_position_hang_eqn
Additional Inherited Members
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Public Types inherited from oomph::SolidFiniteElement
typedef double(* MultiplierFctPt) (const Vector< double > &xi)
Static Public Member Functions inherited from oomph::RefineableElement
static double & max_integrity_tolerance ()
Max. allowed discrepancy in element integrity check.
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Static Protected Member Functions inherited from oomph::RefineableElement
static void check_value_id (const int &n_continuously_interpolated_values, const int &value_id)
Static Protected Attributes inherited from oomph::RefineableElement
static double Max_integrity_tolerance = 1.0e-8
Max. allowed discrepancy in element integrity check.
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
/////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////// RefineableSolidElements are SolidFiniteElements that may be subdivided into children to provide a better local approximation to the solution. The distinction is required to keep a clean separation between problems that alter nodal positions and others. A number of procedures are generic and are included in this class.
Constructor & Destructor Documentation
RefineableSolidElement()
oomph::RefineableSolidElement::RefineableSolidElement () inline
Constructor.
       : RefineableElement(),
         SolidFiniteElement(),
         Use_undeformed_macro_element_for_new_lagrangian_coords(false)
     {
     }
~RefineableSolidElement()
virtual oomph::RefineableSolidElement::~RefineableSolidElement () inline virtual
Virtual Destructor, delete any allocated storage.
 {}
Member Function Documentation
assemble_local_to_lagrangian_jacobian()
void oomph::RefineableSolidElement::assemble_local_to_lagrangian_jacobian (const DShape & dpsids, DenseMatrix< double > & jacobian) const protected virtual
Assemble the jacobian matrix for the mapping from local to lagrangian coordinates, given the derivatives of the shape function Overload the standard version to use the hanging information for the lagrangian coordinates.
Internal function that is used to assemble the jacobian of the mapping from local coordinates (s) to the lagrangian coordinates (xi), given the derivatives of the shape functions.
Reimplemented from oomph::SolidFiniteElement.
   {
     // Find the the dimension of the element
     const unsigned el_dim = dim();
     // Find the number of shape functions and shape functions types
     const unsigned n_shape = nnode();
     const unsigned n_shape_type = nnodal_lagrangian_type();
     // Loop over the rows of the jacobian
     for (unsigned i = 0; i < el_dim; i++)
     {
       // Loop over the columns of the jacobian
       for (unsigned j = 0; j < el_dim; j++)
       {
         // Zero the entry
         jacobian(i, j) = 0.0;
         // Loop over the shape functions
         for (unsigned l = 0; l < n_shape; l++)
         {
           for (unsigned k = 0; k < n_shape_type; k++)
           {
             // Jacobian is dx_j/ds_i, which is represented by the sum
             // over the dpsi/ds_i of the nodal points X j
             // Use the hanging version here
             jacobian(i, j) +=
               lagrangian_position_gen(l, k, j) * dpsids(l, k, i);
           }
         }
       }
     }
   }
References oomph::FiniteElement::dim(), el_dim, i, j, k, oomph::SolidFiniteElement::lagrangian_position_gen(), oomph::SolidFiniteElement::nnodal_lagrangian_type(), and oomph::FiniteElement::nnode().
assemble_local_to_lagrangian_jacobian2()
void oomph::RefineableSolidElement::assemble_local_to_lagrangian_jacobian2 (const DShape & d2psids, DenseMatrix< double > & jacobian2) const protected virtual
Assemble the the "jacobian" matrix of second derivatives, given the second derivatives of the shape functions w.r.t. local coordinates Overload the standard version to use the hanging information for the lagrangian coordinates.
Internal function that is used to assemble the jacobian of second derivatives of the the mapping from local coordinates (s) to the lagrangian coordinates (xi), given the second derivatives of the shape functions.
Reimplemented from oomph::SolidFiniteElement.
   {
     // Find the the dimension of the element
     const unsigned el_dim = dim();
     // Find the number of shape functions and shape functions types
     const unsigned n_shape = nnode();
     const unsigned n_shape_type = nnodal_lagrangian_type();
     // Find the number of second derivatives
     const unsigned n_row = N2deriv[el_dim];
     // Assemble the "jacobian" (d^2 x_j/ds_i^2) for second derivatives of
     // shape functions
     // Loop over the rows (number of second derivatives)
     for (unsigned i = 0; i < n_row; i++)
     {
       // Loop over the columns (element dimension
       for (unsigned j = 0; j < el_dim; j++)
       {
         // Zero the entry
         jacobian2(i, j) = 0.0;
         // Loop over the shape functions
         for (unsigned l = 0; l < n_shape; l++)
         {
           // Loop over the shape function types
           for (unsigned k = 0; k < n_shape_type; k++)
           {
             // Add the terms to the jacobian entry
             // Use the hanging version here
             jacobian2(i, j) +=
               lagrangian_position_gen(l, k, j) * d2psids(l, k, i);
           }
         }
       }
     }
   }
References oomph::FiniteElement::dim(), el_dim, i, j, k, oomph::SolidFiniteElement::lagrangian_position_gen(), oomph::FiniteElement::N2deriv, oomph::SolidFiniteElement::nnodal_lagrangian_type(), and oomph::FiniteElement::nnode().
assign_solid_hanging_local_eqn_numbers()
void oomph::RefineableSolidElement::assign_solid_hanging_local_eqn_numbers (const bool & store_local_dof_pt) private
Assign local equation numbers to the hanging values associated with positions or additional solid values.
The standard equation numbering scheme for solid positions, so that hanging Node information is included.
   {
     // Find the number of nodes
     const unsigned n_node = nnode();
     // Check there are nodes!
     if (n_node > 0)
     {
       // Wipe the local matrix maps, they will be assigned below
       Local_position_hang_eqn.clear();
       // Find the local numbers
       const unsigned n_position_type = nnodal_position_type();
       const unsigned nodal_dim = nodal_dimension();
       // Matrix structure to store all positional equations at a node
       DenseMatrix<int> Position_local_eqn_at_node(n_position_type, nodal_dim);
       // Map that store whether the node's equation numbers have already been
       // added to the local arrays
       std::map<Node*, bool> local_eqn_number_done;
       // Get number of dofs so far
       unsigned local_eqn_number = ndof();
       // A local queue to store the global equation numbers
       std::deque<unsigned long> global_eqn_number_queue;
       // Now loop over all the nodes again to find the master nodes
       // of any hanging nodes that have not yet been assigned
       for (unsigned n = 0; n < n_node; n++)
       {
         // POSITIONAL EQUATAIONS
         // If the node is a hanging node
         if (node_pt(n)->is_hanging())
         {
           // Find the local hang info object
           HangInfo* hang_info_pt = node_pt(n)->hanging_pt();
           // Find the number of master nodes
           unsigned n_master = hang_info_pt->nmaster();
           // Loop over the master nodes
           for (unsigned m = 0; m < n_master; m++)
           {
             // Get the m-th master node
             Node* Master_node_pt = hang_info_pt->master_node_pt(m);
             // If the local equation numbers associated with this master node
             // have not already been assigned, assign them
             if (local_eqn_number_done[Master_node_pt] == false)
             {
               // Now we need to test whether the master node is actually
               // a local node, in which case its local equation numbers
               // will already have been assigned and stored in
               // position_local_eqn(n,j,k)
               // Storage for the index of the local node
               // Initialised to n_node (beyond the possible indices of
               //"real" nodes)
               unsigned local_node_index = n_node;
               // Loop over the local nodes (again)
               for (unsigned n1 = 0; n1 < n_node; n1++)
               {
                 // If the master node is a local node
                 // get its index and break out of the loop
                 if (Master_node_pt == node_pt(n1))
                 {
                   local_node_index = n1;
                   break;
                 }
               }
               // Now we test whether the node was found
               if (local_node_index < n_node)
               {
                 // Loop over the number of position dofs
                 for (unsigned j = 0; j < n_position_type; j++)
                 {
                   // Loop over the dimension of each node
                   for (unsigned k = 0; k < nodal_dim; k++)
                   {
                     // Set the values in the node-based positional look-up
                     // scheme
                     Position_local_eqn_at_node(j, k) =
                       position_local_eqn(local_node_index, j, k);
                   }
                 }
               }
               // Otherwise it's a new master node
               else
               {
                 // Loop over the number of position dofs
                 for (unsigned j = 0; j < n_position_type; j++)
                 {
                   // Loop over the dimension of each node
                   for (unsigned k = 0; k < nodal_dim; k++)
                   {
                     // Get equation number (position_eqn_number)
                     // Note eqn_number is long !
                     long eqn_number = static_cast<SolidNode*>(Master_node_pt)
                                         ->position_eqn_number(j, k);
                     // If equation_number positive add to array
                     if (eqn_number >= 0)
                     {
                       // Add global equation number to the local queue
                       global_eqn_number_queue.push_back(eqn_number);
                       // Add pointer to the dof to the queue if required
                       if (store_local_dof_pt)
                       {
                         GeneralisedElement::Dof_pt_deque.push_back(
                           &(Master_node_pt->x_gen(j, k)));
                       }
                       // Add to pointer-based scheme
                       Position_local_eqn_at_node(j, k) = local_eqn_number;
                       // Increase the number of local variables
                       local_eqn_number++;
                     }
                     // Otherwise the value is pinned
                     else
                     {
                       Position_local_eqn_at_node(j, k) = Data::Is_pinned;
                     }
                   }
                 }
               } // End of case when it's a new master node
               // Dofs included with this node have now been done
               local_eqn_number_done[Master_node_pt] = true;
               // Add to the pointer-based reference scheme
               Local_position_hang_eqn[Master_node_pt] =
                 Position_local_eqn_at_node;
             }
           }
         }
       } // End of loop over nodes
       // Now add our global equations numbers to the internal element storage
       add_global_eqn_numbers(global_eqn_number_queue,
                              GeneralisedElement::Dof_pt_deque);
       // Clear the memory used in the deque
       if (store_local_dof_pt)
       {
         std::deque<double*>().swap(GeneralisedElement::Dof_pt_deque);
       }
     } // End of if nodes
   }
References oomph::GeneralisedElement::add_global_eqn_numbers(), oomph::GeneralisedElement::Dof_pt_deque, oomph::GeneralisedElement::eqn_number(), oomph::Node::hanging_pt(), oomph::Data::Is_pinned, j, k, oomph::GeneralisedElement::local_eqn_number(), Local_position_hang_eqn, m, oomph::HangInfo::master_node_pt(), n, oomph::GeneralisedElement::ndof(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_dimension(), oomph::FiniteElement::node_pt(), oomph::SolidFiniteElement::position_local_eqn(), and oomph::Node::x_gen().
Referenced by assign_solid_local_eqn_numbers().
assign_solid_local_eqn_numbers()
void oomph::RefineableSolidElement::assign_solid_local_eqn_numbers (const bool & store_local_dof_pt) inline virtual
Overload the local equation numbers for Data stored as part of solid nodes to include hanging node data
Reimplemented from oomph::SolidFiniteElement.
     {
       SolidFiniteElement::assign_solid_local_eqn_numbers(store_local_dof_pt);
       assign_solid_hanging_local_eqn_numbers(store_local_dof_pt);
     }
References assign_solid_hanging_local_eqn_numbers(), and oomph::SolidFiniteElement::assign_solid_local_eqn_numbers().
disable_use_of_undeformed_macro_element_for_new_lagrangian_coords()
void oomph::RefineableSolidElement::disable_use_of_undeformed_macro_element_for_new_lagrangian_coords () inline
Unset the flag deciding if the Lagrangian coordinates of newly-created interior SolidNodes are to be determined by the father element's undeformed MacroElement representation (if it has one).
     {
       Use_undeformed_macro_element_for_new_lagrangian_coords = false;
     }
References Use_undeformed_macro_element_for_new_lagrangian_coords.
enable_use_of_undeformed_macro_element_for_new_lagrangian_coords()
void oomph::RefineableSolidElement::enable_use_of_undeformed_macro_element_for_new_lagrangian_coords () inline
Set the flag deciding if the Lagrangian coordinates of newly-created interior SolidNodes are to be determined by the father element's undeformed MacroElement representation (if it has one).
     {
       Use_undeformed_macro_element_for_new_lagrangian_coords = true;
     }
References Use_undeformed_macro_element_for_new_lagrangian_coords.
fill_in_jacobian_from_solid_position_by_fd()
void oomph::RefineableSolidElement::fill_in_jacobian_from_solid_position_by_fd (Vector< double > & residuals, DenseMatrix< double > & jacobian) virtual
Compute element residual Vector and element Jacobian matrix corresponding to the solid positions. Overloaded version to take the hanging nodes into account
This function calculates the entries of Jacobian matrix, used in the Newton method, associated with the elastic problem in which the nodal position is a variable. It does this using finite differences, rather than an analytical formulation, so can be done in total generality. Overload the standard case to include hanging node case
Reimplemented from oomph::SolidFiniteElement.
   {
     // Find the number of nodes
     const unsigned n_node = nnode();
     // If there are no nodes, return straight away
     if (n_node == 0)
     {
       return;
     }
     // Call the update function to ensure that the element is in
     // a consistent state before finite differencing starts
     update_before_solid_position_fd();
     //  bool use_first_order_fd=false;
     // Find the number of positional dofs and nodal dimension
     const unsigned n_position_type = nnodal_position_type();
     const unsigned nodal_dim = nodal_dimension();
     // Find the number of dofs in the element
     const unsigned n_dof = ndof();
     // Create newres vector
     Vector<double> newres(n_dof); //, newres_minus(n_dof);
     // Used default value defined in GeneralisedElement
     const double fd_step = Default_fd_jacobian_step;
     // Integer storage for local unknowns
     int local_unknown = 0;
     // Loop over the nodes
     for (unsigned l = 0; l < n_node; l++)
     {
       // Get the pointer to the node
       Node* const local_node_pt = node_pt(l);
       // If the node is not a hanging node
       if (local_node_pt->is_hanging() == false)
       {
         // Loop over position dofs
         for (unsigned k = 0; k < n_position_type; k++)
         {
           // Loop over dimension
           for (unsigned i = 0; i < nodal_dim; i++)
           {
             local_unknown = position_local_eqn(l, k, i);
             // If the variable is free
             if (local_unknown >= 0)
             {
               // Store a pointer to the (generalised) Eulerian nodal position
               double* const value_pt = &(local_node_pt->x_gen(k, i));
               // Save the old value of the (generalised) Eulerian nodal position
               const double old_var = *value_pt;
               // Increment the  (generalised) Eulerian nodal position
               *value_pt += fd_step;
               // Perform any auxialiary node updates
               local_node_pt->perform_auxiliary_node_update_fct();
               // Update any other dependent variables
               update_in_solid_position_fd(l);
               // Calculate the new residuals
               get_residuals(newres);
               //            if (use_first_order_fd)
               {
                 // Do forward finite differences
                 for (unsigned m = 0; m < n_dof; m++)
                 {
                   // Stick the entry into the Jacobian matrix
                   jacobian(m, local_unknown) =
                     (newres[m] - residuals[m]) / fd_step;
                 }
               }
               //             else
               //              {
               //               //Take backwards step for the  (generalised)
               //               Eulerian nodal
               //               // position
               //               node_pt(l)->x_gen(k,i) = old_var-fd_step;
               //               //Calculate the new residuals at backward
               //               position get_residuals(newres_minus);
               //               //Do central finite differences
               //               for(unsigned m=0;m<n_dof;m++)
               //                {
               //                 //Stick the entry into the Jacobian matrix
               //                 jacobian(m,local_unknown) =
               //                  (newres[m] - newres_minus[m])/(2.0*fd_step);
               //                }
               //              }
               // Reset the (generalised) Eulerian nodal position
               *value_pt = old_var;
               // Perform any auxialiary node updates
               local_node_pt->perform_auxiliary_node_update_fct();
               // Reset any other dependent variables
               reset_in_solid_position_fd(l);
             }
           }
         }
       }
       // Otherwise it's a hanging node
       else
       {
         // Find the local hanging object
         HangInfo* hang_info_pt = local_node_pt->hanging_pt();
         // Loop over the master nodes
         const unsigned n_master = hang_info_pt->nmaster();
         for (unsigned m = 0; m < n_master; m++)
         {
           // Get the pointer to the master node
           Node* const master_node_pt = hang_info_pt->master_node_pt(m);
           // Get the local equation numbers for the master node
           DenseMatrix<int> Position_local_eqn_at_node =
             Local_position_hang_eqn[master_node_pt];
           // Loop over position dofs
           for (unsigned k = 0; k < n_position_type; k++)
           {
             // Loop over dimension
             for (unsigned i = 0; i < nodal_dim; i++)
             {
               local_unknown = Position_local_eqn_at_node(k, i);
               // If the variable is free
               if (local_unknown >= 0)
               {
                 // Store a pointer to the (generalised) Eulerian nodal position
                 double* const value_pt = &(master_node_pt->x_gen(k, i));
                 // Save the old value of the (generalised) Eulerian nodal
                 // position
                 const double old_var = *value_pt;
                 // Increment the  (generalised) Eulerian nodal position
                 *value_pt += fd_step;
                 // Perform any auxialiary node updates
                 master_node_pt->perform_auxiliary_node_update_fct();
                 // Update any dependent variables
                 update_in_solid_position_fd(l);
                 // Calculate the new residuals
                 get_residuals(newres);
                 //              if (use_first_order_fd)
                 {
                   // Do forward finite differences
                   for (unsigned m = 0; m < n_dof; m++)
                   {
                     // Stick the entry into the Jacobian matrix
                     jacobian(m, local_unknown) =
                       (newres[m] - residuals[m]) / fd_step;
                   }
                 }
                 //               else
                 //                {
                 //                 //Take backwards step for the  (generalised)
                 //                 Eulerian nodal
                 //                 // position
                 //                 master_node_pt->x_gen(k,i) = old_var-fd_step;
                 //                 //Calculate the new residuals at backward
                 //                 position get_residuals(newres_minus);
                 //                 //Do central finite differences
                 //                 for(unsigned m=0;m<n_dof;m++)
                 //                  {
                 //                   //Stick the entry into the Jacobian matrix
                 //                   jacobian(m,local_unknown) =
                 //                    (newres[m] -
                 //                    newres_minus[m])/(2.0*fd_step);
                 //                  }
                 //                }
                 // Reset the (generalised) Eulerian nodal position
                 *value_pt = old_var;
                 // Perform any auxialiary node updates
                 master_node_pt->perform_auxiliary_node_update_fct();
                 // Reset any other dependent variables
                 reset_in_solid_position_fd(l);
               }
             }
           }
         }
       } // End of hanging node case
     } // End of loop over nodes
     // End of finite difference loop
     // Final reset of any dependent data
     reset_after_solid_position_fd();
   }
References oomph::GeneralisedElement::Default_fd_jacobian_step, oomph::GeneralisedElement::get_residuals(), oomph::Node::hanging_pt(), i, oomph::Node::is_hanging(), k, Local_position_hang_eqn, m, oomph::HangInfo::master_node_pt(), oomph::GeneralisedElement::ndof(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnodal_position_type(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_dimension(), oomph::FiniteElement::node_pt(), oomph::Node::perform_auxiliary_node_update_fct(), oomph::SolidFiniteElement::position_local_eqn(), oomph::SolidFiniteElement::reset_after_solid_position_fd(), oomph::SolidFiniteElement::reset_in_solid_position_fd(), oomph::SolidFiniteElement::update_before_solid_position_fd(), oomph::SolidFiniteElement::update_in_solid_position_fd(), and oomph::Node::x_gen().
further_build()
virtual void oomph::RefineableSolidElement::further_build () inline virtual
Further build: Pass the father's Use_undeformed_macro_element_for_new_lagrangian_coords flag down, then call the underlying RefineableElement's version.
Reimplemented from oomph::RefineableElement.
Reimplemented in oomph::RefineableQDPVDElement< DIM, NNODE_1D >, oomph::RefineableQPVDElementWithPressure< DIM >, oomph::RefineableQPVDElementWithPressure< DIM >, oomph::RefineableQPVDElementWithPressure< DIM >, oomph::RefineablePVDEquationsWithPressure< DIM >, and oomph::RefineablePVDEquations< DIM >.
     {
       Use_undeformed_macro_element_for_new_lagrangian_coords =
         dynamic_cast<RefineableSolidElement*>(father_element_pt())
           ->is_undeformed_macro_element_used_for_new_lagrangian_coords();
       RefineableElement::further_build();
     }
References oomph::RefineableElement::father_element_pt(), oomph::RefineableElement::further_build(), is_undeformed_macro_element_used_for_new_lagrangian_coords(), and Use_undeformed_macro_element_for_new_lagrangian_coords.
Referenced by oomph::RefineablePVDEquations< DIM >::further_build(), and oomph::RefineablePVDEquationsWithPressure< DIM >::further_build().
geom_data_pt()
Data * oomph::RefineableSolidElement::geom_data_pt (const unsigned & j) virtual
Return pointer to the j-th Data item that the object's shape depends on: Positional data of non-hanging nodes and positional data of master nodes. Recomputed on the fly.
Reimplemented from oomph::SolidFiniteElement.
   {
     // Find the number of nodes
     const unsigned n_node = nnode();
     // Temporary storage for unique position data. Set and vector are
     // required to ensure uniqueness in enumeration on different processors.
     // Set checks uniqueness; Vector stores entries in predictable order.
     std::set<Data*> all_position_data_pt;
     Vector<Data*> all_position_data_vector_pt;
     // Number of entries in set before possibly adding new entry
     unsigned n_old = 0;
     // Now loop over all the nodes again to find the master nodes
     // of any hanging nodes that have not yet been assigned
     for (unsigned n = 0; n < n_node; n++)
     {
       // If the node is a hanging node
       if (node_pt(n)->is_hanging())
       {
         // Find the local hang info object
         HangInfo* hang_info_pt = node_pt(n)->hanging_pt();
         // Find the number of master nodes
         unsigned n_master = hang_info_pt->nmaster();
         // Loop over the master nodes
         for (unsigned m = 0; m < n_master; m++)
         {
           // Get the m-th master node
           Node* Master_node_pt = hang_info_pt->master_node_pt(m);
           // Positional data
           Data* pos_data_pt =
             dynamic_cast<SolidNode*>(Master_node_pt)->variable_position_pt();
           // Add to set
           n_old = all_position_data_pt.size();
           all_position_data_pt.insert(pos_data_pt);
           // New entry?
           if (all_position_data_pt.size() > n_old)
           {
             all_position_data_vector_pt.push_back(pos_data_pt);
           }
         }
       }
       // Not hanging
       else
       {
         // Add node itself to set
         // Positional data
         Data* pos_data_pt =
           dynamic_cast<SolidNode*>(node_pt(n))->variable_position_pt();
         // Add to set
         n_old = all_position_data_pt.size();
         all_position_data_pt.insert(pos_data_pt);
         // New entry?
         if (all_position_data_pt.size() > n_old)
         {
           all_position_data_vector_pt.push_back(pos_data_pt);
         }
       }
     } // End of loop over nodes
     // Return j-th entry
     return all_position_data_vector_pt[j];
   }
References oomph::Node::hanging_pt(), j, m, oomph::HangInfo::master_node_pt(), n, oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), and oomph::FiniteElement::node_pt().
identify_geometric_data()
void oomph::RefineableSolidElement::identify_geometric_data (std::set< Data * > & geometric_data_pt) virtual
Specify Data that affects the geometry of the element by adding the position Data to the set that's passed in. (This functionality is required in FSI problems; set is used to avoid double counting). Refineable version includes hanging nodes
Reimplemented from oomph::SolidFiniteElement.
   {
     // Loop over the node update data and add to the set
     const unsigned n_node = this->nnode();
     for (unsigned j = 0; j < n_node; j++)
     {
       // If the node is a hanging node
       if (node_pt(j)->is_hanging())
       {
         // Find the local hang info object
         HangInfo* hang_info_pt = node_pt(j)->hanging_pt();
         // Find the number of master nodes
         unsigned n_master = hang_info_pt->nmaster();
         // Loop over the master nodes
         for (unsigned m = 0; m < n_master; m++)
         {
           // Get the m-th master node
           Node* Master_node_pt = hang_info_pt->master_node_pt(m);
           // Add to set
           geometric_data_pt.insert(
             dynamic_cast<SolidNode*>(Master_node_pt)->variable_position_pt());
         }
       }
       // Not hanging
       else
       {
         // Add node itself to set
         geometric_data_pt.insert(
           dynamic_cast<SolidNode*>(node_pt(j))->variable_position_pt());
       }
     }
   }
References oomph::Node::hanging_pt(), j, m, oomph::HangInfo::master_node_pt(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), and oomph::FiniteElement::node_pt().
is_undeformed_macro_element_used_for_new_lagrangian_coords()
bool oomph::RefineableSolidElement::is_undeformed_macro_element_used_for_new_lagrangian_coords () const inline
Return the flag deciding if the Lagrangian coordinates of newly-created interior SolidNodes are to be determined by the father element's undeformed MacroElement representation (if it has one). Default: False as it means that, following a refinement an element is no longer in equilbrium (as the Lagrangian coordinate is determined differently from the Eulerian one). However, basing the Lagrangian coordinates on the undeformed MacroElement can be more stable numerically and for steady problems it's not a big deal either way as the difference between the two formulations only matters at finite resolution so we have no right to say that one is "more correct" than the other...
     {
       return Use_undeformed_macro_element_for_new_lagrangian_coords;
     }
References Use_undeformed_macro_element_for_new_lagrangian_coords.
Referenced by further_build().
local_position_hang_eqn()
DenseMatrix<int>& oomph::RefineableSolidElement::local_position_hang_eqn (Node *const & node_pt) inline
Access the local equation number of of hanging node variables associated with nodal positions. The function returns a dense matrix that contains all the local equation numbers corresponding to the positional degrees of freedom.
     {
       return Local_position_hang_eqn[node_pt];
     }
References Local_position_hang_eqn, and oomph::FiniteElement::node_pt().
Referenced by oomph::RefineableQDPVDElement< DIM, NNODE_1D >::fill_in_generic_contribution_to_residuals_pvd(), oomph::RefineableImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_displ_lagr_multiplier(), and oomph::RefineableFSIImposeDisplacementByLagrangeMultiplierElement< ELEMENT >::refineable_fill_in_generic_contribution_to_residuals_fsi_displ_lagr_multiplier().
local_to_lagrangian_mapping_diagonal()
double oomph::RefineableSolidElement::local_to_lagrangian_mapping_diagonal (const DShape & dpsids, DenseMatrix< double > & jacobian, DenseMatrix< double > & inverse_jacobian) const protected virtual
Calculate the mapping from local to Lagrangian coordinates given the derivatives of the shape functions w.r.t the local coorindates. assuming that the coordinates are aligned in the direction of the local coordinates, i.e. there are no cross terms and the jacobian is diagonal. This function returns the determinant of the jacobian, the jacobian and the inverse jacobian.
Calculate the mapping from local to lagrangian coordinates assuming that the coordinates are aligned in the direction of the local coordinates, i.e. there are no cross terms and the jacobian is diagonal. The local derivatives are passed as dpsids and the jacobian and inverse jacobian are returned.
Reimplemented from oomph::SolidFiniteElement.
   {
     // Find the dimension of the element
     const unsigned el_dim = dim();
     // Find the number of shape functions and shape functions types
     const unsigned n_shape = nnode();
     const unsigned n_shape_type = nnodal_lagrangian_type();
     // In this case we assume that there are no cross terms, that is
     // global coordinate 0 is always in the direction of local coordinate 0
     // Loop over the coordinates
     for (unsigned i = 0; i < el_dim; i++)
     {
       // Zero the jacobian and inverse jacobian entries
       for (unsigned j = 0; j < el_dim; j++)
       {
         jacobian(i, j) = 0.0;
         inverse_jacobian(i, j) = 0.0;
       }
       // Loop over the shape functions
       for (unsigned l = 0; l < n_shape; l++)
       {
         // Loop over the types of dof
         for (unsigned k = 0; k < n_shape_type; k++)
         {
           // Derivatives are always dx_{i}/ds_{i}
           jacobian(i, i) += lagrangian_position_gen(l, k, i) * dpsids(l, k, i);
         }
       }
     }
     // Now calculate the determinant of the matrix
     double det = 1.0;
     for (unsigned i = 0; i < el_dim; i++)
     {
       det *= jacobian(i, i);
     }
 // Report if Matrix is singular, or negative
 #ifdef PARANOID
     check_jacobian(det);
 #endif
     // Calculate the inverse mapping (trivial in this case)
     for (unsigned i = 0; i < el_dim; i++)
     {
       inverse_jacobian(i, i) = 1.0 / jacobian(i, i);
     }
     // Return the value of the Jacobian
     return (det);
   }
References oomph::FiniteElement::check_jacobian(), oomph::FiniteElement::dim(), el_dim, i, j, k, oomph::SolidFiniteElement::lagrangian_position_gen(), oomph::SolidFiniteElement::nnodal_lagrangian_type(), and oomph::FiniteElement::nnode().
ngeom_data()
unsigned oomph::RefineableSolidElement::ngeom_data () const virtual
The number of geometric data affecting a RefineableSolidFiniteElement is the positional Data of all non-hanging nodes plus the geometric Data of all distinct master nodes. Recomputed on the fly.
Reimplemented from oomph::SolidFiniteElement.
   {
     // Find the number of nodes
     const unsigned n_node = nnode();
     // Temporary storage for unique position data
     std::set<Data*> all_position_data_pt;
     // Now loop over all the nodes again to find the master nodes
     // of any hanging nodes that have not yet been assigned
     for (unsigned n = 0; n < n_node; n++)
     {
       // If the node is a hanging node
       if (node_pt(n)->is_hanging())
       {
         // Find the local hang info object
         HangInfo* hang_info_pt = node_pt(n)->hanging_pt();
         // Find the number of master nodes
         unsigned n_master = hang_info_pt->nmaster();
         // Loop over the master nodes
         for (unsigned m = 0; m < n_master; m++)
         {
           // Get the m-th master node
           Node* Master_node_pt = hang_info_pt->master_node_pt(m);
           // Add to set
           all_position_data_pt.insert(
             dynamic_cast<SolidNode*>(Master_node_pt)->variable_position_pt());
         }
       }
       // Not hanging
       else
       {
         // Add node itself to set
         all_position_data_pt.insert(
           dynamic_cast<SolidNode*>(node_pt(n))->variable_position_pt());
       }
     } // End of loop over nodes
     // How many are there?
     return all_position_data_pt.size();
   }
References oomph::Node::hanging_pt(), m, oomph::HangInfo::master_node_pt(), n, oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), and oomph::FiniteElement::node_pt().
Member Data Documentation
Local_position_hang_eqn
std::map<Node*, DenseMatrix<int> > oomph::RefineableSolidElement::Local_position_hang_eqn private
Storage for local equation numbers of hanging node variables associated with nodal positions. local position equation number = Local_position_hang_eqn(master_node_pt,ival)
Referenced by assign_solid_hanging_local_eqn_numbers(), fill_in_jacobian_from_solid_position_by_fd(), and local_position_hang_eqn().
Use_undeformed_macro_element_for_new_lagrangian_coords
bool oomph::RefineableSolidElement::Use_undeformed_macro_element_for_new_lagrangian_coords protected
Flag deciding if the Lagrangian coordinates of newly-created interior SolidNodes are to be determined by the father element's undeformed MacroElement representation (if it has one). Default: False as it means that, following a refinement an element is no longer in equilbrium (as the Lagrangian coordinate is determined differently from the Eulerian one). However, basing the Lagrangian coordinates on the undeformed MacroElement can be more stable numerically and for steady problems it's not a big deal either way as the difference between the two formulations only matters at finite resolution so we have no right to say that one is "more correct" than the other...
Referenced by disable_use_of_undeformed_macro_element_for_new_lagrangian_coords(), enable_use_of_undeformed_macro_element_for_new_lagrangian_coords(), further_build(), and is_undeformed_macro_element_used_for_new_lagrangian_coords().
The documentation for this class was generated from the following files:
refineable_elements.h
refineable_elements.cc