MercuryDPM: Cwise_array_power_array.cpp File Reference
Cwise_array_power_array.cpp File Reference
Functions
Array< double, 1, 3 > x (8, 25, 3)
Array< double, 1, 3 > e (1./3., 0.5, 2.)
Function Documentation
e()
Array<double, 1, 3> e (1./ 3., 0. 5, 2.)
Referenced by __attribute__(), SilbertHstop::actionAfterTimeStep(), TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::actions_after_adapt(), UnstructuredTorusProblem< ELEMENT >::actions_after_adapt(), FlowAroundCylinderProblem< ELEMENT >::actions_after_adapt(), FourierDecomposedHelmholtzProblem< ELEMENT >::actions_after_adapt(), MeltContactProblem< ELEMENT >::actions_after_adapt(), UnsteadyHeatMeltProblem< ELEMENT >::actions_after_adapt(), HelmholtzPointSourceProblem< ELEMENT >::actions_after_adapt(), FSICollapsibleChannelProblem< ELEMENT >::actions_after_adapt(), UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::actions_after_adapt(), UnstructuredSolidProblem< ELEMENT, MESH >::actions_after_adapt(), RefineableDrivenCavityProblem< ELEMENT >::actions_after_adapt(), QuarterCircleDrivenCavityProblem< ELEMENT >::actions_after_adapt(), PRefineableDrivenCavityProblem< ELEMENT >::actions_after_adapt(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::actions_after_adapt(), PMLStructuredCubicHelmholtz< ELEMENT >::actions_after_adapt(), PMLHelmholtzMGProblem< ELEMENT >::actions_after_adapt(), CollapsibleChannelProblem< ELEMENT >::actions_after_adapt(), RefineableYoungLaplaceProblem< ELEMENT >::actions_after_adapt(), ShellProblem< ELEMENT >::actions_after_distribute(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::actions_after_distribute(), AxisymmetricVibratingShellProblem< ELEMENT >::actions_after_newton_convergence_check(), VibratingShellProblem< ELEMENT >::actions_after_newton_convergence_check(), oomph::IMRByBDF::actions_after_timestep(), MeltContactProblem< ELEMENT >::actions_before_adapt(), UnstructuredSolidProblem< ELEMENT, MESH >::actions_before_adapt(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::actions_before_distribute(), AxisymmetricVibratingShellProblem< ELEMENT >::actions_before_newton_convergence_check(), VibratingShellProblem< ELEMENT >::actions_before_newton_convergence_check(), AirwayReopeningProblem< ELEMENT >::actions_before_newton_convergence_check(), ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_before_newton_convergence_check(), ThreeDimBethertonProblem< ELEMENT >::actions_before_newton_convergence_check(), ForceLawsMPI2Test::actionsAfterSolve(), SphericalSuperQuadricCollision::actionsAfterSolve(), SpeciesTest::actionsAfterSolve(), GranuHeap::actionsAfterTimeStep(), RotatingDrumBidisperseInitialise::actionsAfterTimeStep(), BouncingSuperQuadric::actionsAfterTimeStep(), ContactDetectionNormalSpheresTest::actionsAfterTimeStep(), ContactDetectionRotatedSpheresTest::actionsAfterTimeStep(), DrivenParticleClass::actionsAfterTimeStep(), LawinenBox::actionsBeforeTimeStep(), DPM::actionsBeforeTimeStep(), ForceLawsMPI2Test::actionsBeforeTimeStep(), Slide::actionsBeforeTimeStep(), BrethertonProblem< ELEMENT >::activate_inflow_dependency(), ActivatorInhibitorProblem< ELEMENT >::ActivatorInhibitorProblem(), oomph::RefineableTetgenMesh< ELEMENT >::adapt(), oomph::RefineableGmshTetMesh< ELEMENT >::adapt(), oomph::TreeBasedRefineableMeshBase::adapt(), oomph::TreeBasedRefineableMeshBase::adapt_mesh(), oomph::PeriodicOrbitAssemblyHandler< NNODE_1D >::adapt_temporal_mesh(), oomph::Problem::adaptive_unsteady_newton_solve(), Eigen::DynamicSGroup::add(), FlowAroundCylinderProblem< ELEMENT >::add_eigenproblem(), BendingCantileverProblem< ELEMENT >::add_gravity(), MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::add_mortaring_elements(), ChutePeriodic::add_particles(), oomph::StefanBoltzmannRadiationBase::add_stefan_boltzmann_illumination_info(), AirwayReopeningProblem< ELEMENT >::AirwayReopeningProblem(), AngledPeriodicBoundarySecondUnitTest::AngledPeriodicBoundarySecondUnitTest(), AngledPeriodicBoundaryUnitTest::AngledPeriodicBoundaryUnitTest(), AngleOfRepose::AngleOfRepose(), RenderingWidget::animate(), BendingCantileverProblem< ELEMENT >::apply_boundary_conditions(), PMLStructuredCubicHelmholtz< ELEMENT >::apply_boundary_conditions(), oomph::NavierStokesSchurComplementPreconditioner::assemble_inv_press_and_veloc_mass_matrix_diagonal(), oomph::PressureBasedSolidLSCPreconditioner::assemble_mass_matrix_diagonal(), oomph::PeriodicOrbitTemporalMesh< ELEMENT >::assemble_residuals(), oomph::PeriodicOrbitTemporalMesh< ELEMENT >::assemble_residuals_and_jacobian(), oomph::TetMeshBase::assess_mesh_quality(), SpineGravityTractionElement< ELEMENT >::assign_additional_local_eqn_numbers(), oomph::LinearisedAxisymmetricNavierStokesEquations::assign_additional_local_eqn_numbers(), CylinderMesh< ELEMENT >::assign_centreline_nodes(), oomph::Problem::assign_eqn_numbers(), PolarNSProblem< ELEMENT >::assign_external_pressure(), oomph::jh_mesh< ELEMENT >::assign_fluid_element_vector(), oomph::streamfunction_mesh::assign_fluid_element_vector(), oomph::Mesh::assign_initial_values_impulsive(), RefineablePeriodicLoadProblem< ELEMENT >::assign_traction_elements(), oomph::CircularCylindricalShellMesh< ELEMENT >::assign_undeformed_positions(), oomph::Multi_domain_functions::aux_setup_multi_domain_interaction(), AxialSolidQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::AxialSolidQuarterTubeMesh(), AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::AxialSpineQuarterTubeMesh(), AxisymFreeSurfaceNozzleAdvDiffRobinProblem< ELEMENT >::AxisymFreeSurfaceNozzleAdvDiffRobinProblem(), AxisymmetricLinearElasticityProblem< ELEMENT, TIMESTEPPER >::AxisymmetricLinearElasticityProblem(), oomph::BackupMeshForProjection< GEOMETRIC_ELEMENT >::BackupMeshForProjection(), BaseStateProblem< BASE_ELEMENT >::BaseStateProblem(), Beam::Beam(), bench(), bench_prod(), SolidBag::bendBag(), BendingCantileverProblem< ELEMENT >::BendingCantileverProblem(), CRBond_Bessel::bessjy01a(), CRBond_Bessel::bessjyna(), CRBond_Bessel::bessjynb(), CRBond_Bessel::bessjyv(), oomph::Problem::bifurcation_adapt_helper(), binary_op_test(), BouncingSuperQuadric::BouncingSuperQuadric(), BoundariesSelfTest::BoundariesSelfTest(), oomph::TetMeshBase::boundary_element_in_region_pt(), oomph::UnstructuredTwoDMeshGeometryBase::boundary_element_in_region_pt(), oomph::Mesh::boundary_element_pt(), BratuProblem< ELEMENT >::BratuProblem(), oomph::BrethertonSpineMesh< ELEMENT, SpineLineFluidInterfaceElement< ELEMENT > >::BrethertonSpineMesh(), oomph::ElementElementConstraintElement::build(), oomph::ChannelSpineMesh< ELEMENT >::build_channel_spine_mesh(), oomph::Mesh::build_face_mesh(), oomph::GmshTetMesh< ELEMENT >::build_from_scaffold(), oomph::GeompackQuadMesh< ELEMENT >::build_from_scaffold(), oomph::SimpleCubicTetMesh< ELEMENT >::build_from_scaffold(), oomph::TetgenMesh< ELEMENT >::build_from_scaffold(), oomph::TriangleMesh< ELEMENT >::build_from_scaffold(), oomph::QuadFromTriangleMesh< ELEMENT >::build_from_scaffold(), oomph::MeshAsGeomObject::build_it(), RefineableDrivenCavityProblem< ELEMENT >::build_mesh(), RefineableUnsteadyHeatProblem< ELEMENT >::build_mesh(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::build_mesh(), oomph::CircularCylindricalShellMesh< ELEMENT >::build_mesh(), oomph::BackwardStepQuadMesh< ELEMENT >::build_mesh(), oomph::ExtrudedCubeMeshFromQuadMesh< ELEMENT >::build_mesh(), oomph::FishMesh< ELEMENT >::build_mesh(), oomph::OneDMesh< ELEMENT >::build_mesh(), oomph::BrickFromTetMesh< ELEMENT >::build_mesh(), MyCanyonMesh< ELEMENT, INTERFACE_ELEMENT >::build_single_layer_mesh(), STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::build_single_layer_mesh(), MyTipMesh< ELEMENT, INTERFACE_ELEMENT >::build_single_layer_mesh(), oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::build_two_layer_mesh(), oomph::TwoLayerSpineMesh< BASE_ELEMENT >::build_two_layer_mesh(), Membrane::buildMesh(), HGridOptimiser::calcDfDx(), UnstructuredTorusProblem< ELEMENT >::calculate_area(), HomogenisationProblem< ELEMENT >::calculate_coefficients(), AxisymmetricVibratingShellProblem< ELEMENT >::calculate_error_of_fixed_point_iteration(), VibratingShellProblem< ELEMENT >::calculate_error_of_fixed_point_iteration(), oomph::Mesh::calculate_predictions(), oomph::Problem::calculate_predictions(), UnstructuredTorusProblem< ELEMENT >::calculate_square_of_l2_norm(), CapProblem< ELEMENT >::CapProblem(), Eigen::EulerAngles< Scalar_, _System >::cast(), pcast_array< SrcPacket, TgtPacket, 8, 1 >::cast(), CRBond_Bessel::cbessikv(), ChannelSpineFlowProblem< ELEMENT >::ChannelSpineFlowProblem(), oomph::ChannelWithLeafletMesh< ELEMENT >::ChannelWithLeafletMesh(), ChannelWithLeafletProblem< ELEMENT >::ChannelWithLeafletProblem(), FourierDecomposedHelmholtzProblem< ELEMENT >::check_gamma(), check_global_interpolation2d(), oomph::PRefineableQElement< 2, INITIAL_NNODE_1D >::check_integrity(), oomph::RefineableQElement< 3 >::check_integrity(), oomph::RefineableQElement< 1 >::check_integrity(), oomph::RefineableQElement< 2 >::check_integrity(), oomph::Mesh::check_inverted_elements(), check_locate_zeta(), oomph::TriangleScaffoldMesh::check_mesh_integrity(), oomph::TimeStepper::check_predicted_values_up_to_date(), check_product(), VorticityRecoveryProblem< ELEMENT >::check_smoothed_vorticity(), check_sparse_inverse(), Beam::checkBeamDeflection(), HGridOptimiser::checkLimit(), VolumeCoupling::checkParticlesInFiniteElems(), ChutePeriodicDemo::ChutePeriodicDemo(), ChuteWithWedge::ChuteWithWedge(), CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::CoatedSphereProblem(), oomph::CollapsibleChannelMesh< ELEMENT >::CollapsibleChannelMesh(), CollapsibleChannelProblem< ELEMENT >::CollapsibleChannelProblem(), InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::complete_build(), MovingBlockProblem< ELEMENT >::complete_element_build(), UnstructuredFvKProblem< ELEMENT >::complete_problem_setup(), AxiPoroProblem< ELEMENT, TIMESTEPPER >::complete_problem_setup(), DarcyProblem< ELEMENT >::complete_problem_setup(), AxisymmetricVibratingShellProblem< ELEMENT >::complete_problem_setup(), VibratingShellProblem< ELEMENT >::complete_problem_setup(), MeltContactProblem< ELEMENT >::complete_problem_setup(), SolarRadiationProblem< ELEMENT >::complete_problem_setup(), ContactProblem< ELEMENT >::complete_problem_setup(), UnsteadyHeatMeltProblem< ELEMENT >::complete_problem_setup(), UnsteadyHeatProblem< ELEMENT >::complete_problem_setup(), HomogenisationProblem< ELEMENT >::complete_problem_setup(), CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::complete_problem_setup(), CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::complete_problem_setup(), UnstructuredPoissonProblem< ELEMENT >::complete_problem_setup(), UnstructuredImmersedEllipseProblem< ELEMENT >::complete_problem_setup(), NavierStokesProblem< ELEMENT >::complete_problem_setup(), TwoLayerInterfaceProblem< ELEMENT >::complete_problem_setup(), UnstructuredFluidProblem< ELEMENT >::complete_problem_setup(), BubbleInChannelProblem< ELEMENT >::complete_problem_setup(), DropInChannelProblem< ELEMENT >::complete_problem_setup(), VorticityRecoveryProblem< ELEMENT >::complete_problem_setup(), ElasticAnnulusProblem< ELASTICITY_ELEMENT >::complete_problem_setup(), FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::complete_problem_setup(), RingWithTRibProblem< ELASTICITY_ELEMENT >::complete_problem_setup(), oomph::FourierDecomposedHelmholtzDtNBoundaryElement< ELEMENT >::complete_setup_of_dependencies(), oomph::HelmholtzDtNBoundaryElement< ELEMENT >::complete_setup_of_dependencies(), oomph::RefineableTriangleMesh< ELEMENT >::compute_area_target(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::compute_areas(), FlowAroundHalfCylinderProblem< ELEMENT >::compute_drag_nusselt(), AdvectionProblem::compute_error(), TwoDDGProblem< ELEMENT >::compute_error(), oomph::Mesh::compute_error(), AxisymmetricVibratingShellProblem< ELEMENT >::compute_error_estimate(), VibratingShellProblem< ELEMENT >::compute_error_estimate(), TwoLayerInterfaceProblem< ELEMENT >::compute_error_estimate(), UnstructuredFluidProblem< ELEMENT >::compute_error_estimate(), BubbleInChannelProblem< ELEMENT >::compute_error_estimate(), DropInChannelProblem< ELEMENT >::compute_error_estimate(), oomph::HelmholtzDtNMesh< ELEMENT >::compute_fourier_components(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::compute_integrated_concentrations(), ElasticQuadFromTriangleMesh< ELEMENT >::compute_norm(), oomph::Mesh::compute_norm(), RefineableSphericalCouetteProblem< ELEMENT >::compute_torque(), InterfaceProblem< ELEMENT, TIMESTEPPER >::compute_total_mass(), oomph::RefineableTetgenMesh< ELEMENT >::compute_volume_target(), oomph::RefineableTetMeshBase::compute_volume_target(), LiquidBridgeBagheriInteraction::computeAdhesionForce(), SuperQuadricParticle::computeContactPoint(), FrictionInteraction::computeFrictionForce(), MindlinInteraction::computeFrictionForce(), MindlinRollingTorsionInteraction::computeFrictionForce(), HertzianSinterInteraction::computeSinterForce(), SlidingFrictionInteraction::computeSlidingSpring(), AirwayReopeningProblem< ELEMENT >::connect_walls(), AirwayReopeningProblem< ELEMENT >::construct_poisson_outlet_elements(), AirwayReopeningProblem< ELEMENT >::construct_pressure_gradient_outlet_elements(), oomph::OcTreeForest::construct_up_right_equivalents(), Contact::Contact(), InitialBed::continueSolve(), RotatingDrumBidisperseInitialise::continueSolve(), InitialConditions< SpeciesType >::continueSolve(), DPM::continueSolve(), ContProblem< ELEMENT >::ContProblem(), contraction_batch(), contraction_both_transposed(), contraction_lhs_transposed(), contraction_rhs_transposed(), oomph::Mesh::convert_to_boundary_node(), PSDContinuous::convertSubtractiveToCumulative(), oomph::Problem::copy(), CoupledBeam::CoupledBeam(), ShellProblem< ELEMENT >::create_bc_elements(), oomph::TwoDimensionalPMLHelper::create_bottom_left_pml_mesh(), oomph::TwoDimensionalPMLHelper::create_bottom_pml_mesh(), oomph::TwoDimensionalPMLHelper::create_bottom_right_pml_mesh(), BendingCantileverProblem< ELEMENT >::create_constraint_elements(), RefineableYoungLaplaceProblem< ELEMENT >::create_contact_angle_elements(), YoungLaplaceProblem< ELEMENT >::create_contact_angle_elements(), MeltContactProblem< ELEMENT >::create_contact_elements(), SolarRadiationProblem< ELEMENT >::create_contact_elements(), ContactProblem< ELEMENT >::create_contact_elements(), ContactProblem< ELEMENT >::create_contact_heat_elements_on_boulder(), ContactProblem< ELEMENT >::create_displ_imposition_elements(), UnstructuredImmersedEllipseProblem< ELEMENT >::create_drag_elements(), PressureWaveFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_fluid_traction_elements(), UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_fluid_traction_elements(), UnstructuredFluidProblem< ELEMENT >::create_fluid_traction_elements(), MeltContactProblem< ELEMENT >::create_flux_elements(), SolarRadiationProblem< ELEMENT >::create_flux_elements(), UnsteadyHeatMeltProblem< ELEMENT >::create_flux_elements(), UnsteadyHeatProblem< ELEMENT >::create_flux_elements(), FluxPoissonMGProblem< ELEMENT, MESH >::create_flux_elements(), FluxPoissonProblem< ELEMENT >::create_flux_elements(), ScatteringProblem< ELEMENT >::create_flux_elements(), PMLProblem< ELEMENT >::create_flux_elements(), TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::create_flux_elements(), LinearWaveProblem< ELEMENT, TIMESTEPPER >::create_flux_elements(), RefineableUnsteadyHeatProblem< ELEMENT >::create_flux_elements(), RefineableTwoMeshFluxPoissonProblem< ELEMENT >::create_flux_elements(), AxisymFreeSurfaceNozzleAdvDiffRobinProblem< ELEMENT >::create_flux_elements(), TwoMeshFluxPoissonProblem< ELEMENT >::create_flux_elements(), TwoMeshFluxSteadyAxisymAdvectionDiffusionProblem< ELEMENT >::create_flux_elements(), FourierDecomposedHelmholtzProblem< ELEMENT >::create_flux_elements_on_inner_boundary(), PMLFourierDecomposedHelmholtzProblem< ELEMENT >::create_flux_elements_on_inner_boundary(), PseudoSolidCapProblem< ELEMENT >::create_free_surface_elements(), AxisymmetricVibratingShellProblem< ELEMENT >::create_free_surface_elements(), VibratingShellProblem< ELEMENT >::create_free_surface_elements(), RefineableRotatingCylinderProblem< ELEMENT >::create_free_surface_elements(), TwoLayerInterfaceProblem< ELEMENT >::create_free_surface_elements(), RisingBubbleProblem< ELEMENT >::create_free_surface_elements(), BubbleInChannelProblem< ELEMENT >::create_free_surface_elements(), DropInChannelProblem< ELEMENT >::create_free_surface_elements(), CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_fsi_traction_elements(), CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_fsi_traction_elements(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_fsi_traction_elements(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_fsi_traction_elements(), UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_fsi_traction_elements(), CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_helmholtz_ABC_elements(), CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_helmholtz_DtN_elements(), CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_helmholtz_DtN_elements(), CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_helmholtz_fsi_flux_elements(), CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_helmholtz_fsi_flux_elements(), ContactProblem< ELEMENT >::create_imposed_heat_flux_elements_on_boulder(), SilbertPeriodic::create_inflow_particle(), InterfaceProblem< ELEMENT, TIMESTEPPER >::create_interface_elements(), PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::create_interface_elements(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::create_interface_elements(), UnstructuredTorusProblem< ELEMENT >::create_lagrange_multiplier_elements(), FSICollapsibleChannelProblem< ELEMENT >::create_lagrange_multiplier_elements(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_lagrange_multiplier_elements(), FSIChannelWithLeafletProblem< ELEMENT >::create_lagrange_multiplier_elements(), UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_lagrange_multiplier_elements(), PrescribedBoundaryDisplacementProblem< ELEMENT >::create_lagrange_multiplier_elements(), UnstructuredImmersedEllipseProblem< ELEMENT >::create_lagrange_multiplier_elements(), UnstructuredFluidProblem< ELEMENT >::create_lagrange_multiplier_elements(), CollapsibleChannelProblem< ELEMENT >::create_lagrange_multiplier_elements(), oomph::TwoDimensionalPMLHelper::create_left_pml_mesh(), MeltContactProblem< ELEMENT >::create_melt_elements(), StefanBoltzmannProblem< ELEMENT >::create_melt_elements(), oomph::GmshTetScaffoldMesh::create_mesh_from_msh_file(), FourierDecomposedHelmholtzProblem< ELEMENT >::create_outer_bc_elements(), HelmholtzPointSourceProblem< ELEMENT >::create_outer_bc_elements(), ScatteringProblem< ELEMENT >::create_outer_bc_elements(), TiltedCavityProblem< ELEMENT >::create_parall_outflow_lagrange_elements(), UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_parallel_flow_lagrange_elements(), UnstructuredFluidProblem< ELEMENT >::create_parallel_outflow_lagrange_elements(), PMLProblem< ELEMENT >::create_power_elements(), PMLFourierDecomposedHelmholtzProblem< ELEMENT >::create_power_monitor_mesh(), FpTestProblem::create_refineable_traction_elements(), oomph::TwoDimensionalPMLHelper::create_right_pml_mesh(), StefanBoltzmannProblem< ELEMENT >::create_sb_elements(), CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_solid_traction_elements(), CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::create_solid_traction_elements(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::create_solid_traction_elements(), oomph::TwoDimensionalPMLHelper::create_top_left_pml_mesh(), oomph::TwoDimensionalPMLHelper::create_top_pml_mesh(), oomph::TwoDimensionalPMLHelper::create_top_right_pml_mesh(), CantileverProblem< ELEMENT >::create_traction_elements(), FpTestProblem::create_traction_elements(), BlockCompressionProblem< ELEMENT >::create_traction_elements(), UnstructuredSolidProblem< ELEMENT, MESH >::create_traction_elements(), AnnularDiskProblem< ELASTICITY_ELEMENT >::create_traction_elements(), RingWithTRibProblem< ELASTICITY_ELEMENT >::create_traction_elements(), CollapsibleChannelProblem< ELEMENT >::create_traction_elements(), RayleighTractionProblem< ELEMENT, TIMESTEPPER >::create_traction_elements(), FSICollapsibleChannelProblem< ELEMENT >::create_traction_elements(), SheetGlueProblem< ELEMENT >::create_traction_elements(), CapProblem< ELEMENT >::create_volume_constraint_elements(), PseudoSolidCapProblem< ELEMENT >::create_volume_constraint_elements(), RefineableRotatingCylinderProblem< ELEMENT >::create_volume_constraint_elements(), FreeSurfaceRotationProblem< ELEMENT >::create_volume_constraint_elements(), SolidFreeSurfaceRotationProblem< ELEMENT >::create_volume_constraint_elements(), RisingBubbleProblem< ELEMENT >::create_volume_constraint_elements(), BubbleInChannelProblem< ELEMENT >::create_volume_constraint_elements(), DropInChannelProblem< ELEMENT >::create_volume_constraint_elements(), Chute::createBottom(), CylinderAndInterfaceMesh< ELEMENT >::CylinderAndInterfaceMesh(), oomph::CylinderWithFlagMesh< ELEMENT >::CylinderWithFlagMesh(), oomph::TopologicallyRectangularDomain::d2r_E(), oomph::TopologicallyRectangularDomain::d2r_N(), oomph::TopologicallyRectangularDomain::d2r_S(), oomph::TopologicallyRectangularDomain::d2r_W(), oomph::Mesh::delete_all_external_storage(), RefineableYoungLaplaceProblem< ELEMENT >::delete_contact_angle_elements(), MeltContactProblem< ELEMENT >::delete_contact_elements(), SolarRadiationProblem< ELEMENT >::delete_contact_elements(), ContactProblem< ELEMENT >::delete_contact_elements(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::delete_dependent_position_elements(), ContactProblem< ELEMENT >::delete_displ_imposition_elements(), UnstructuredImmersedEllipseProblem< ELEMENT >::delete_drag_elements(), FourierDecomposedHelmholtzProblem< ELEMENT >::delete_face_elements(), HelmholtzPointSourceProblem< ELEMENT >::delete_face_elements(), ScatteringProblem< ELEMENT >::delete_face_elements(), CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::delete_face_elements(), CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::delete_face_elements(), PMLFourierDecomposedHelmholtzProblem< ELEMENT >::delete_face_elements(), MeltContactProblem< ELEMENT >::delete_flux_elements(), SolarRadiationProblem< ELEMENT >::delete_flux_elements(), UnsteadyHeatMeltProblem< ELEMENT >::delete_flux_elements(), UnsteadyHeatProblem< ELEMENT >::delete_flux_elements(), FluxPoissonMGProblem< ELEMENT, MESH >::delete_flux_elements(), TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::delete_flux_elements(), RefineableUnsteadyHeatProblem< ELEMENT >::delete_flux_elements(), RefineableTwoMeshFluxPoissonProblem< ELEMENT >::delete_flux_elements(), AxisymFreeSurfaceNozzleAdvDiffRobinProblem< ELEMENT >::delete_flux_elements(), TwoMeshFluxSteadyAxisymAdvectionDiffusionProblem< ELEMENT >::delete_flux_elements(), AxisymmetricVibratingShellProblem< ELEMENT >::delete_free_surface_elements(), VibratingShellProblem< ELEMENT >::delete_free_surface_elements(), RefineableRotatingCylinderProblem< ELEMENT >::delete_free_surface_elements(), TwoLayerInterfaceProblem< ELEMENT >::delete_free_surface_elements(), RisingBubbleProblem< ELEMENT >::delete_free_surface_elements(), BubbleInChannelProblem< ELEMENT >::delete_free_surface_elements(), DropInChannelProblem< ELEMENT >::delete_free_surface_elements(), UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::delete_fsi_traction_elements(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::delete_fsi_traction_elements(), CollapsibleChannelProblem< ELEMENT >::delete_inflow_traction_elements(), InterfaceProblem< ELEMENT, TIMESTEPPER >::delete_interface_elements(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::delete_interface_elements(), UnstructuredTorusProblem< ELEMENT >::delete_lagrange_multiplier_elements(), FSICollapsibleChannelProblem< ELEMENT >::delete_lagrange_multiplier_elements(), FSIChannelWithLeafletProblem< ELEMENT >::delete_lagrange_multiplier_elements(), UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::delete_lagrange_multiplier_elements(), PrescribedBoundaryDisplacementProblem< ELEMENT >::delete_lagrange_multiplier_elements(), UnstructuredImmersedEllipseProblem< ELEMENT >::delete_lagrange_multiplier_elements(), UnstructuredFluidProblem< ELEMENT >::delete_lagrange_multiplier_elements(), CollapsibleChannelProblem< ELEMENT >::delete_lagrange_multiplier_elements(), MeltContactProblem< ELEMENT >::delete_melt_elements(), CollapsibleChannelProblem< ELEMENT >::delete_outflow_flux_control_elements(), CollapsibleChannelProblem< ELEMENT >::delete_outflow_impedance_elements(), AirwayReopeningProblem< ELEMENT >::delete_outlet_elements(), oomph::NavierStokesEquations< DIM >::delete_pressure_advection_diffusion_robin_elements(), oomph::SpaceTimeNavierStokesEquations< DIM >::delete_pressure_advection_diffusion_robin_elements(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::delete_pressure_advection_diffusion_robin_elements(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::delete_slave_position_elements(), RefineablePeriodicLoadProblem< ELEMENT >::delete_traction_elements(), CantileverProblem< ELEMENT >::delete_traction_elements(), BlockCompressionProblem< ELEMENT >::delete_traction_elements(), FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::delete_traction_elements(), AnnularDiskProblem< ELASTICITY_ELEMENT >::delete_traction_elements(), RingWithTRibProblem< ELASTICITY_ELEMENT >::delete_traction_elements(), CollapsibleChannelProblem< ELEMENT >::delete_traction_elements(), FSICollapsibleChannelProblem< ELEMENT >::delete_traction_elements(), RefineableRotatingCylinderProblem< ELEMENT >::delete_volume_constraint_elements(), RisingBubbleProblem< ELEMENT >::delete_volume_constraint_elements(), BubbleInChannelProblem< ELEMENT >::delete_volume_constraint_elements(), DropInChannelProblem< ELEMENT >::delete_volume_constraint_elements(), chwirut2_functor::df(), rat42_functor::df(), MGH10_functor::df(), BoxBOD_functor::df(), Bennett5_functor::df(), rat43_functor::df(), eckerle4_functor::df(), DGProblem< ELEMENT >::DGProblem(), oomph::OcTreeRoot::direction_of_neighbour(), AxisymmetricVibratingShellProblem< ELEMENT >::disable_aitken_extrapolation_for_all_elements(), VibratingShellProblem< ELEMENT >::disable_aitken_extrapolation_for_all_elements(), AxisymmetricVibratingShellProblem< ELEMENT >::disable_fixed_point_iteration_for_strain_rate_for_all_elements(), VibratingShellProblem< ELEMENT >::disable_fixed_point_iteration_for_strain_rate_for_all_elements(), oomph::Problem::disable_mass_matrix_reuse(), oomph::DiskTetMeshFacetedSurface::DiskTetMeshFacetedSurface(), oomph::DiskWithTorusAroundEdgeTetMeshFacetedSurface::DiskWithTorusAroundEdgeTetMeshFacetedSurface(), oomph::DiskWithTwoLayersTetMeshFacetedSurface::DiskWithTwoLayersTetMeshFacetedSurface(), MD_demo::DistInt(), Eigen::BDCSVD< MatrixType_, Options_ >::divide(), oomph::SolidHelpers::doc_2D_principal_stress(), UnstructuredFluidProblem< ELEMENT >::doc_boundary_coordinates(), oomph::Mesh::doc_boundary_coordinates(), DiskShockWaveProblem< ELEMENT, TIMESTEPPER >::doc_displ_and_veloc(), oomph::Z2ErrorEstimator::doc_flux(), oomph::FSI_functions::doc_fsi(), oomph::StefanBoltzmannHelper::doc_sample_points(), DarcyProblem< ELEMENT >::doc_shape_functions(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solid_boundary_coordinates(), UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solid_boundary_coordinates(), MeltContactProblem< ELEMENT >::doc_solution(), SolarRadiationProblem< ELEMENT >::doc_solution(), ContactProblem< ELEMENT >::doc_solution(), UnsteadyHeatMeltProblem< ELEMENT >::doc_solution(), CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::doc_solution(), PrescribedBoundaryDisplacementProblem< ELEMENT >::doc_solution(), PMLStructuredCubicHelmholtz< ELEMENT >::doc_solution(), DiskShockWaveProblem< ELEMENT, TIMESTEPPER >::doc_solution(), RingWithTRibProblem< ELASTICITY_ELEMENT >::doc_solution(), CompressedSquareProblem< ELEMENT >::doc_solution(), UnstructuredImmersedEllipseProblem< ELEMENT >::doc_solution(), UnstructuredFvKProblem< ELEMENT >::doc_solution(), AxisymmetricVibratingShellProblem< ELEMENT >::doc_solution(), VibratingShellProblem< ELEMENT >::doc_solution(), BubbleInChannelProblem< ELEMENT >::doc_solution(), DropInChannelProblem< ELEMENT >::doc_solution(), UnstructuredFluidProblem< ELEMENT >::doc_solution(), RefineableDrivenCavityProblem< ELEMENT >::doc_solution(), TetmeshPoissonProblem< ELEMENT >::doc_solution(), FourierDecomposedHelmholtzProblem< ELEMENT >::doc_solution(), StefanBoltzmannProblem< ELEMENT >::doc_solution(), HelmholtzPointSourceProblem< ELEMENT >::doc_solution(), ScatteringProblem< ELEMENT >::doc_solution(), CoatedSphereProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::doc_solution(), UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solution(), CantileverProblem< ELEMENT >::doc_solution(), AxisymFreeSurfaceNozzleAdvDiffRobinProblem< ELEMENT >::doc_solution(), ThreeDimBethertonProblem< ELEMENT >::doc_solution(), PMLFourierDecomposedHelmholtzProblem< ELEMENT >::doc_solution(), FluxPoissonProblem< ELEMENT >::doc_solution(), PolarNSProblem< ELEMENT >::doc_solution(), StaticDiskCompressionProblem< ELEMENT >::doc_solution(), DiskOscillationProblem< ELEMENT >::doc_solution(), SimpleShearProblem< ELEMENT >::doc_solution(), VorticityRecoveryProblem< ELEMENT >::doc_solution(), FSIChannelWithLeafletProblem< ELEMENT >::doc_solution(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::doc_solution(), ShellProblem< ELEMENT >::doc_solution(), RefineableYoungLaplaceProblem< ELEMENT >::doc_solution(), oomph::WomersleyProblem< ELEMENT, DIM >::doc_solution(), PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::doc_solution(), ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::doc_solution(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::doc_solution(), checkIdx::doCheck_(), BaseCluster::doEneOutput(), oomph::Mesh::does_pointer_correspond_to_mesh_data(), DPM::DPM(), oomph::TopologicallyRectangularDomain::dr_E(), oomph::TopologicallyRectangularDomain::dr_N(), oomph::TopologicallyRectangularDomain::dr_S(), oomph::TopologicallyRectangularDomain::dr_W(), GpuHelper::drawVector(), GpuHelper::drawVectorBox(), Eigen::NumTraits< double >::dummy_precision(), Eigen::NumTraits< Real >::dummy_precision(), oomph::DummyErrorEstimator::DummyErrorEstimator(), oomph::Problem::dump(), oomph::Mesh::dump(), dump_table_for_subset(), oomph::TriangleScaffoldMesh::edge_boundary(), oomph::TetgenScaffoldMesh::edge_index(), oomph::TriangleScaffoldMesh::edge_index(), ProblemParameters::edge_sign_setup(), TestProblem::edge_sign_setup(), Global_Physical_Variables::edge_sign_setup(), efficiency_of_subset(), EIGEN_DECLARE_TEST(), eigensolver_generic_extra(), ElasticBeamProblem::ElasticBeamProblem(), ElasticFishMesh< ELEMENT >::ElasticFishMesh(), ElasticInclinedPlaneProblem< ELEMENT, TIMESTEPPER >::ElasticInclinedPlaneProblem(), ElasticInterfaceProblem< ELEMENT, TIMESTEPPER >::ElasticInterfaceProblem(), ElasticQuadFromTriangleMesh< ELEMENT >::ElasticQuadFromTriangleMesh(), ElasticQuarterTubeMesh< ELEMENT >::ElasticQuarterTubeMesh(), oomph::ElasticRefineableQuarterPipeMesh< ELEMENT >::ElasticRefineableQuarterPipeMesh(), ElasticRefineableTwoLayerMesh< ELEMENT >::ElasticRefineableTwoLayerMesh(), ElasticTwoLayerMesh< ELEMENT >::ElasticTwoLayerMesh(), oomph::TetgenScaffoldMesh::element_attribute(), oomph::TriangleScaffoldMesh::element_attribute(), oomph::PerturbedSpineMesh::element_node_pt(), oomph::SolidMesh::element_node_pt(), oomph::SpineMesh::element_node_pt(), PolarNSProblem< ELEMENT >::element_output(), oomph::Mesh::element_pt(), oomph::ElementElementConstraintElementHelper::element_pt_to_data_pt(), oomph::TwoLayerPerturbedSpineMesh< ELEMENT >::element_reorder(), oomph::ChannelSpineMesh< ELEMENT >::element_reorder(), oomph::RectangularQuadMesh< ELEMENT >::element_reorder(), ElementAnalysis::ElementAnalysis(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::empty_mesh(), AxisymmetricVibratingShellProblem< ELEMENT >::enable_aitken_extrapolation_for_all_elements(), VibratingShellProblem< ELEMENT >::enable_aitken_extrapolation_for_all_elements(), AxisymmetricVibratingShellProblem< ELEMENT >::enable_fixed_point_iteration_for_strain_rate_for_all_elements(), VibratingShellProblem< ELEMENT >::enable_fixed_point_iteration_for_strain_rate_for_all_elements(), oomph::Problem::enable_mass_matrix_reuse(), PMLStructuredCubicHelmholtz< ELEMENT >::enable_pmls(), EultingSphereProblem< ELEMENT >::EultingSphereProblem(), eval_closed_spline2d(), eval_spline3d(), eval_spline3d_onbrks(), oomph::ElementElementMortaringElement::evaluate_constraint_functions(), oomph::SarahBL::exact_soln(), SarahBL::exact_soln(), oomph::ElementElementConstraintElement::extern_data_eqn(), oomph::ElementElementConstraintElement::extern_data_pt(), oomph::TetgenScaffoldMesh::face_boundary(), oomph::TetgenScaffoldMesh::face_index(), oomph::Mesh::face_index_at_boundary(), oomph::TetMeshBase::face_index_at_boundary_in_region(), oomph::UnstructuredTwoDMeshGeometryBase::face_index_at_boundary_in_region(), RefineableBinArray::fill_bin_array(), NonRefineableBinArray::fill_bin_array(), oomph::NetFluxControlElement< ELEMENT >::fill_in_contribution_to_residuals(), oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst(), oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst(), oomph::SpaceTimeNavierStokesEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst(), oomph::NavierStokesEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst(), oomph::RefineableNavierStokesEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst(), oomph::NetFluxControlElement< ELEMENT >::fill_in_generic_residual_contribution_flux_control(), finalizeBenchmark(), Eigen::DynamicSGroup::findElement(), RotatingProblem< ELEMENT >::finish_problem_setup(), oomph::MeshAsGeomObject::finite_element_pt(), oomph::Mesh::finite_element_pt(), FishPoissonProblem< ELEMENT >::FishPoissonProblem(), AirwayReopeningProblem< ELEMENT >::fix_pressure(), BrethertonProblem< ELEMENT >::fix_pressure(), BaseStateProblem< BASE_ELEMENT >::fix_pressure(), PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::fix_pressure(), RotatingCylinderProblem< ELEMENT, TIMESTEPPER >::fix_pressure(), RectangularDrivenCavityProblem< ELEMENT >::fix_pressure(), MovingBlockProblem< ELEMENT >::fix_pressure(), RefineableDrivenCavityProblem< ELEMENT >::fix_pressure(), QuarterCircleDrivenCavityProblem< ELEMENT >::fix_pressure(), PRefineableDrivenCavityProblem< ELEMENT >::fix_pressure(), RefineableConvectionProblem< NST_ELEMENT, AD_ELEMENT >::fix_pressure(), ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::fix_pressure(), DDConvectionProblem< NST_ELEMENT, AD_ELEMENT >::fix_pressure(), RefineableDDConvectionProblem< NST_ELEMENT, AD_ELEMENT >::fix_pressure(), RefineableSphereConvectionProblem< ELEMENT >::fix_pressure(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::fix_pressure(), QuarterCircleDrivenCavityProblem2< ELEMENT >::fix_pressure(), OscEllipseProblem< ELEMENT, TIMESTEPPER >::fix_pressure(), FpTestProblem::fix_pressure(), InterfaceProblem< ELEMENT, TIMESTEPPER >::fix_pressure(), TwoLayerInterfaceProblem< ELEMENT >::fix_pressure(), RayleighProblem< ELEMENT, TIMESTEPPER >::fix_pressure(), RefineableSphericalCouetteProblem< ELEMENT >::fix_pressure(), RefineableSphericalSpinUpProblem< ELEMENT >::fix_pressure(), SphericalSpinUpProblem< ELEMENT >::fix_pressure(), SphericalSteadyRotationProblem< ELEMENT >::fix_pressure(), ThreeDimBethertonProblem< ELEMENT >::fix_pressure(), PolarNSProblem< ELEMENT >::fix_pressure(), MembraneDemo::fixMembraneEdges(), MembraneSelfTest::fixMembraneEdges(), float_pow_test_impl(), FlowAroundCylinderProblem< ELEMENT >::FlowAroundCylinderProblem(), FlowAroundHalfCylinderProblem< ELEMENT >::FlowAroundHalfCylinderProblem(), FlowPastBoxProblem< ELEMENT >::FlowPastBoxProblem(), oomph::Refineable_r_mesh< ELEMENT >::fluid_elt_pt(), FluxAndPeriodicBoundarySelfTest::FluxAndPeriodicBoundarySelfTest(), FluxBoundarySelfTest::FluxBoundarySelfTest(), FluxPoissonMGProblem< ELEMENT, MESH >::FluxPoissonMGProblem(), FluxPoissonProblem< ELEMENT >::FluxPoissonProblem(), oomph::FoldHandler::FoldHandler(), ForceLawsMPI2Test::ForceLawsMPI2Test(), FourierDecomposedTimeHarmonicLinearElasticityProblem< ELEMENT >::FourierDecomposedTimeHarmonicLinearElasticityProblem(), FpTestProblem::FpTestProblem(), FreeSurfaceRotationProblem< ELEMENT >::FreeSurfaceRotationProblem(), FSIChannelWithLeafletProblem< ELEMENT >::FSIChannelWithLeafletProblem(), FSICollapsibleChannelProblem< ELEMENT >::FSICollapsibleChannelProblem(), oomph::FSIDrivenCavityMesh< ELEMENT >::FSIDrivenCavityMesh(), FSIDrivenCavityProblem< ELEMENT >::FSIDrivenCavityProblem(), FSIRingProblem::FSIRingProblem(), oomph::SarahBL::full_exact_soln(), SarahBL::full_exact_soln(), STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::full_output(), mathsFunc::gamma(), gemv_col(), RefineableUnsteadyHeatProblem< ELEMENT >::generic_actions_after(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::generic_actions_after(), oomph::GeompackQuadScaffoldMesh::GeompackQuadScaffoldMesh(), oomph::FoepplvonKarmanVolumeConstraintElement< ELEMENT, MESH >::get_bounded_volume(), FallingBlockProblem< ELEMENT >::get_dissipation(), oomph::ExtrudedCubeMeshFromQuadMesh< ELEMENT >::get_element_boundary_information(), oomph::Z2ErrorEstimator::get_element_errors(), oomph::DummyErrorEstimator::get_element_errors(), oomph::TreeBasedRefineableMeshBase::get_elements_at_refinement_level(), UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::get_fluid_dissipation(), oomph::ImmersedRigidBodyElement::get_force_and_torque(), oomph::Problem::get_hessian_vector_products(), oomph::Problem::get_inverse_mass_matrix_times_residuals(), oomph::Problem::get_jacobian(), ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::get_kinetic_energy(), DDConvectionProblem< NST_ELEMENT, AD_ELEMENT >::get_kinetic_energy(), RefineableDDConvectionProblem< NST_ELEMENT, AD_ELEMENT >::get_kinetic_energy(), ThreeDimBethertonProblem< ELEMENT >::get_lambda(), NodeReordering::get_node_reordering(), oomph::Mesh::get_node_reordering(), AirwayReopeningProblem< ELEMENT >::get_outlet_flux(), oomph::NavierStokesSchurComplementPreconditioner::get_pressure_advection_diffusion_matrix(), oomph::Z2ErrorEstimator::get_recovered_flux_in_patch(), oomph::VorticitySmoother< ELEMENT >::get_recovered_vorticity_in_patch(), oomph::TreeBasedRefineableMeshBase::get_refinement_levels(), oomph::TreeBasedRefineableMeshBase::get_refinement_pattern(), oomph::Problem::get_residuals(), PolarNSProblem< ELEMENT >::get_shear_stress(), UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::get_solid_strain_energy(), UnstructuredSolidProblem< ELEMENT, MESH >::get_strain_energy(), PolarNSProblem< ELEMENT >::get_symmetry(), oomph::StreamfunctionProblem::get_vels(), SinterNormalSpecies::getCollisionTime(), LinearPlasticViscoelasticNormalSpecies::getCollisionTime(), SinterLinNormalSpecies::getCollisionTime(), Eigen::BenchTimer::getCpuTime(), HorizontalScrew::getDistanceAndNormal(), Coil::getDistanceAndNormal(), ParabolaChute::getDistanceAndNormal(), SineWall::getDistanceAndNormal(), TriangulatedWall::Face::getDistanceAndNormal(), Screw::getDistanceAndNormalLabCoordinates(), SimpleDrumSuperquadrics::getDistanceNormalOverlapSuperquadric(), InfiniteWall::getFurthestPointSuperQuadric(), SuperQuadricParticle::getInitialGuessForContact(), BaseWall::getInteractionWith(), SuperQuadricParticle::getInteractionWithSuperQuad(), BaseWall::getLinePlaneIntersect(), SolidProblem< ELEMENT_TYPE >::getMassMomentumEnergy(), HGridOptimiser::getOptimalDistribution(), Eigen::BenchTimer::getRealTime(), ClumpParticle::getRotationalEnergy(), SCoupling< M, O >::getSCoupledElements(), BasicIntersectionOfWalls::getVTK(), BasicUnionOfWalls::getVTK(), GluedSolidMesh::glue(), GluedSolidMesh::GluedSolidMesh(), HGridOptimiser::goldenSectionSearch(), Gravity::gravity(), oomph::HalfRectangleWithHoleMesh< ELEMENT >::HalfRectangleWithHoleMesh(), Membrane::handleParticleAddition(), Membrane::handleParticleRemoval(), HelmholtzPointSourceProblem< ELEMENT >::HelmholtzPointSourceProblem(), Hertzian2DUnitTest::Hertzian2DUnitTest(), HomogenisationProblem< ELEMENT >::HomogenisationProblem(), oomph::HopfHandler::HopfHandler(), hyperplane(), Eigen::Hyperplane< Scalar_, AmbientDim_, Options_ >::Hyperplane(), oomph::HypreInterface::HypreInterface(), SegregatedFSICollapsibleChannelProblem< ELEMENT >::identify_fluid_and_solid_dofs(), SegregatedFSIDrivenCavityProblem< ELEMENT >::identify_fluid_and_solid_dofs(), oomph::BiharmonicFluidProblem< DIM >::impose_fluid_flow_on_edge(), oomph::ImposeFluxForWomersleyElement< DIM >::ImposeFluxForWomersleyElement(), oomph::StefanBoltzmannRadiationBase::incoming_stefan_boltzmann_radiation(), Eigen::IterScaling< MatrixType_ >::init(), oomph::BrethertonSpineMesh< ELEMENT, SpineLineFluidInterfaceElement< ELEMENT > >::initial_element_reorder(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::initial_element_reorder(), ScaleCoupling< M, O >::initialiseCoupledElements(), Membrane::initializeEdgeBendingQuantities(), oomph::jh_mesh< ELEMENT >::inlet_traction_elt_pt(), oomph::streamfunction_mesh::inlet_traction_elt_pt(), inplace(), InsertionBoundaryMPI2Test::InsertionBoundaryMPI2Test(), InterfaceProblem< ELEMENT, TIMESTEPPER >::InterfaceProblem(), oomph::ElementElementConstraintElement::intern_data_eqn(), oomph::ElementElementConstraintElement::intern_data_pt(), oomph::AxisymmetricPoroelasticityEquations::interpolated_div_q(), MeshTriangle::isInsideTriangle(), BaseWall::isInsideWallVTK(), CFDDEMCoupleTest::itterateL(), RenderingWidget::keyPressEvent(), kill_trailing(), kill_trailingn(), LaserOnLayer::LaserOnLayer(), LawinenBox::LawinenBox(), LeesEdwardsDemo::LeesEdwardsDemo(), TwoDDGProblem< ELEMENT >::limit(), oomph::DGMesh::limit_slopes(), linearStructure(), linearstructure_overflow(), LinearWaveProblem< ELEMENT, TIMESTEPPER >::LinearWaveProblem(), lines(), LiquidMigrationMPI2Test::LiquidMigrationMPI2Test(), MarbleRun::loadBigSeesaw(), Membrane::loadFromSTL(), loadingTest(), MarbleRun::loadSmallSeesaw(), MarbleRun::loadSTLFile(), oomph::Multi_domain_functions::locate_zeta_for_local_coordinates(), ElasticRefineableTwoLayerMesh< ELEMENT >::lower_layer_element_pt(), oomph::jh_mesh< ELEMENT >::lower_stress_integral_elt_pt(), main(), InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::make_free_surface_elements(), ElasticRefineableQuarterCircleSectorMesh< ELEMENT >::make_traction_element_mesh(), InclinedPlaneProblem< ELEMENT, INTERFACE_ELEMENT >::make_traction_elements(), Eigen::internal::matrix_function_compute_mu(), oomph::Mesh::max_and_min_element_size(), MeltSpinningProblem< ELEMENT >::MeltSpinningProblem(), oomph::Mesh::merge_meshes(), MortaringHelpers::MergedSolidMesh::MergedSolidMesh(), MinimalExampleDrum::MinimalExampleDrum(), Eigen::LevenbergMarquardt< FunctorType_ >::minimizeOneStep(), Eigen::LevenbergMarquardt< FunctorType_ >::minimizeOptimumStorageOneStep(), Eigen::internal::minimum_degree_ordering(), MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::MortaringValidationProblem(), RenderingWidget::mouseMoveEvent(), RenderingWidget::mousePressEvent(), OneDimMesh< ELEMENT >::neighbour_finder(), oomph::NetFluxControlElement< ELEMENT >::NetFluxControlElement(), oomph::ElementElementConstraintElement::node_eqn(), NodeReordering::node_global_position_comparison(), oomph::NodeOrdering::node_global_position_comparison(), oomph::ElementElementConstraintElement::node_pt(), oomph::Mesh::node_update(), oomph::ImmersedRigidBodyElement::node_update_adjacent_fluid_elements(), normalAndTangentialLoadingTest(), objectivenessTest(), OneDimMesh< ELEMENT >::OneDimMesh(), Eigen::internal::scalar_logistic_op< float >::operator()(), Eigen::internal::scalar_logistic_op_impl< T, std::enable_if_t< NumTraits< T >::IsComplex > >::operator()(), oomph::NonLinearElasticitySmoothMesh< ELEMENT >::operator()(), oomph::LinearElasticitySmoothMesh< LINEAR_ELASTICITY_ELEMENT >::operator()(), oomph::PoissonSmoothMesh< POISSON_ELEMENT >::operator()(), Eigen::RotationBase< Derived, Dim_ >::operator*(), Eigen::internal::operator*(), oomph::PeriodicOrbitTemporalMesh< ELEMENT >::orbit_output(), oomph::PeriodicOrbitAssemblyHandler< NNODE_1D >::orbit_output(), OrrSommerfeldProblem< ELEMENT >::OrrSommerfeldProblem(), oomph::jh_mesh< ELEMENT >::outlet_traction_elt_pt(), oomph::streamfunction_mesh::outlet_traction_elt_pt(), SSPorousChannelElement::output(), oomph::Mesh::output(), NonRefineableBinArray::output_bins(), oomph::TriangleMesh< ELEMENT >::output_boundary_coordinates(), OneDimMesh< ELEMENT >::output_faces(), oomph::Mesh::output_fct(), oomph::NavierStokesEquations< DIM >::output_pressure_advection_diffusion_robin_elements(), oomph::SpaceTimeNavierStokesEquations< DIM >::output_pressure_advection_diffusion_robin_elements(), oomph::SpaceTimeNavierStokesMixedOrderEquations< DIM >::output_pressure_advection_diffusion_robin_elements(), LiquidMigrationMPI2Test::outputXBallsData(), LiquidMigrationSelfTest::outputXBallsData(), SuperQuadricParticle::overlapFromContactPoint(), oomph::TreeBasedRefineableMeshBase::p_adapt(), oomph::TreeBasedRefineableMeshBase::p_adapt_mesh(), oomph::TreeBasedRefineableMesh< ELEMENT >::p_refine_elements_if_required(), oomph::TreeBasedRefineableMeshBase::p_refine_selected_elements(), oomph::TreeBasedRefineableMeshBase::p_refine_uniformly(), oomph::TreeBasedRefineableMeshBase::p_unrefine_uniformly(), packetmath_real(), Eigen::internal::scalar_logistic_op< float >::packetOp(), Eigen::internal::scalar_logistic_op_impl< T, EnableIf >::packetOp(), parallel_test(), SphericalSteadyRotationProblem< ELEMENT >::parameter_study(), parametrizedline(), rapidjson::GenericReader< Encoding, Allocator >::ParseString(), oomph::METIS::partition_mesh(), BaseStateProblem< BASE_ELEMENT >::pass_updated_nondim_parameters_to_elements(), PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::pass_updated_nondim_parameters_to_elements(), Eigen::internal::pcast(), Eigen::internal::pcast< Packet2d, Packet16c >(), Eigen::internal::pcast< Packet2d, Packet16uc >(), Eigen::internal::pcast< Packet2l, Packet16c >(), Eigen::internal::pcast< Packet2l, Packet16uc >(), Eigen::internal::pcast< Packet2ul, Packet16c >(), Eigen::internal::pcast< Packet2ul, Packet16uc >(), Eigen::internal::pcast< Packet8d, Packet8l >(), PeriodicLoadProblem< ELEMENT >::PeriodicLoadProblem(), PerturbedStateProblem< BASE_ELEMENT, PERTURBED_ELEMENT >::PerturbedStateProblem(), Eigen::internal::pfrexp< Packet8bf >(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::pin_all(), FlowAroundCylinderProblem< ELEMENT >::pin_all_base_flow_dofs(), oomph::NavierStokesSchurComplementPreconditioner::pin_all_non_pressure_dofs(), oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::pin_all_non_pressure_dofs(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::pin_dofs_of_field(), MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::pin_mortared_status_dofs(), RefineableDrivenCavityProblem< ELEMENT >::pin_only_pressure_at_origin(), oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::pin_redundant_nodal_pressures(), oomph::RefineableAxisymmetricNavierStokesEquations::pin_redundant_nodal_pressures(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::pin_redundant_nodal_pressures(), oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::pin_redundant_nodal_pressures(), oomph::RefineableLinearisedNavierStokesEquations::pin_redundant_nodal_pressures(), oomph::RefineableNavierStokesEquations< DIM >::pin_redundant_nodal_pressures(), oomph::RefineablePolarNavierStokesEquations::pin_redundant_nodal_pressures(), oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::pin_redundant_nodal_pressures(), oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >::pin_redundant_nodal_pressures(), oomph::RefineableSphericalNavierStokesEquations::pin_redundant_nodal_pressures(), oomph::LinearElasticityEquationsBase< DIM >::pin_redundant_nodal_solid_pressures(), oomph::PVDEquationsBase< DIM >::pin_redundant_nodal_solid_pressures(), oomph::PitchForkHandler::PitchForkHandler(), Eigen::PlainObjectBase< Derived >::PlainObjectBase(), PlateProblem< ELEMENT >::PlateProblem(), Eigen::internal::pldexp< Packet4d >(), Eigen::internal::pldexp< Packet8d >(), Eigen::internal::pldexp_fast(), Eigen::internal::pldexp_fast< Packet2d >(), Eigen::internal::pldexp_fast< Packet4d >(), Eigen::internal::pldexp_generic(), Eigen::internal::ploaddup< Packet16bf >(), Eigen::internal::ploaddup< Packet16h >(), Eigen::internal::plog< Packet4f >(), Eigen::internal::plog_impl_double(), Eigen::internal::plog_impl_float(), oomph::MGSolver< DIM >::plot(), oomph::PMLCornerQuadMesh< ELEMENT >::PMLCornerQuadMesh(), PMLHelmholtzMGProblem< ELEMENT >::PMLHelmholtzMGProblem(), PMLProblem< ELEMENT >::PMLProblem(), oomph::PMLQuadMesh< ELEMENT >::PMLQuadMesh(), PMLStructuredCubicHelmholtz< ELEMENT >::PMLStructuredCubicHelmholtz(), PoissonProblem< ELEMENT >::PoissonProblem(), PolarNSProblem< ELEMENT >::PolarNSProblem(), Eigen::RunQueue< Work, kSize >::PopBack(), Eigen::RunQueue< Work, kSize >::PopBackHalf(), Eigen::RunQueue< Work, kSize >::PopFront(), rapidjson::internal::Pow10(), oomph::WomersleyImpedanceTubeBase< ELEMENT, DIM >::precompute_aux_integrals(), PRefineableDrivenCavityProblem< ELEMENT >::PRefineableDrivenCavityProblem(), PressureWaveFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::PressureWaveFSIProblem(), PSDContinuous::print(), PSD::printPSD(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::project(), PseudoElasticCollapsibleChannelProblem< FLUID_ELEMENT, SOLID_ELEMENT >::PseudoElasticCollapsibleChannelProblem(), PseudoSolidCapProblem< ELEMENT >::PseudoSolidCapProblem(), Eigen::internal::ptranspose(), Eigen::RunQueue< Work, kSize >::PushBack(), Eigen::RunQueue< Work, kSize >::PushFront(), QFaceTestProblem< ELEMENT >::QFaceTestProblem(), QuarterCircleDrivenCavityProblem< ELEMENT >::QuarterCircleDrivenCavityProblem(), QuarterCircleDrivenCavityProblem2< ELEMENT >::QuarterCircleDrivenCavityProblem2(), oomph::QuarterCircleSectorMesh< ELEMENT >::QuarterCircleSectorMesh(), oomph::QuarterPipeMesh< ELEMENT >::QuarterPipeMesh(), quaternion(), RayleighProblem< ELEMENT, TIMESTEPPER >::RayleighProblem(), RayleighTractionProblem< ELEMENT, TIMESTEPPER >::RayleighTractionProblem(), oomph::Mesh::read(), oomph::Problem::read(), SuperQuadricParticle::read(), Membrane::read(), PoissonProblem< ELEMENT >::read_custom_distribution_from_file(), oomph::VorticitySmoother< ELEMENT >::recover_vorticity(), oomph::RectangleWithHoleAndAnnularRegionMesh< ELEMENT >::RectangleWithHoleAndAnnularRegionMesh(), RectangleWithHoleMesh< ELEMENT >::RectangleWithHoleMesh(), oomph::RectangleWithHoleMesh< ELEMENT >::RectangleWithHoleMesh(), RectangularDrivenCavityProblem< ELEMENT >::RectangularDrivenCavityProblem(), oomph::TreeBasedRefineableMeshBase::refine_as_in_reference_mesh(), CollapsibleChannelProblem< ELEMENT >::refine_elements_based_on_x_coord(), oomph::TreeBasedRefineableMeshBase::refine_selected_elements(), oomph::TreeBasedRefineableMeshBase::refine_uniformly(), RefineableCylinderAndInterfaceMesh< ELEMENT >::RefineableCylinderAndInterfaceMesh(), RefineableDrivenCavityProblem< ELEMENT >::RefineableDrivenCavityProblem(), oomph::RefineableEighthSphereMesh< ELEMENT >::RefineableEighthSphereMesh(), RefineableElutingSphereProblem< ELEMENT >::RefineableElutingSphereProblem(), RefineableFishPoissonProblem< ELEMENT >::RefineableFishPoissonProblem(), oomph::RefineableHalfRectangleWithHoleMesh< ELEMENT >::RefineableHalfRectangleWithHoleMesh(), RefineablePeriodicLoadProblem< ELEMENT >::RefineablePeriodicLoadProblem(), RefineablePorousChannelProblem< ELEMENT >::RefineablePorousChannelProblem(), oomph::RefineableQuadMeshWithMovingCylinder< ELEMENT >::RefineableQuadMeshWithMovingCylinder(), oomph::RefineableRectangleWithHoleAndAnnularRegionMesh< ELEMENT >::RefineableRectangleWithHoleAndAnnularRegionMesh(), RefineableRectangleWithHoleMesh< ELEMENT >::RefineableRectangleWithHoleMesh(), oomph::RefineableRectangleWithHoleMesh< ELEMENT >::RefineableRectangleWithHoleMesh(), RefineableRotatingCylinderProblem< ELEMENT >::RefineableRotatingCylinderProblem(), RefineableSphereConvectionProblem< ELEMENT >::RefineableSphereConvectionProblem(), RefineableSphericalCouetteProblem< ELEMENT >::RefineableSphericalCouetteProblem(), RefineableSphericalSpinUpProblem< ELEMENT >::RefineableSphericalSpinUpProblem(), oomph::RefineableTetgenMesh< ELEMENT >::RefineableTetgenMesh(), RefineableTwoMeshFluxPoissonProblem< ELEMENT >::RefineableTwoMeshFluxPoissonProblem(), RefineableUnsteadyHeatProblem< ELEMENT >::RefineableUnsteadyHeatProblem(), RefineableYoungLaplaceProblem< ELEMENT >::RefineableYoungLaplaceProblem(), regimeForceUnitTest::regimeForceUnitTest(), oomph::UnstructuredTwoDMeshGeometryBase::region_element_pt(), oomph::TetMeshBase::region_element_pt(), ElasticRefineableQuarterCircleSectorMesh< ELEMENT >::remake_traction_element_mesh(), oomph::jh_mesh< ELEMENT >::remove_shear_elements(), oomph::jh_mesh< ELEMENT >::remove_traction_elements(), oomph::streamfunction_mesh::remove_traction_elements(), oomph::HSL_MA42::reorder_elements(), oomph::BrethertonSpineMesh< ELEMENT, INTERFACE_ELEMENT >::reposition_spines(), oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::reset_pin_status(), oomph::NavierStokesSchurComplementPreconditioner::reset_pin_status(), oomph::AugmentedBlockFoldLinearSolver::resolve(), oomph::AugmentedBlockPitchForkLinearSolver::resolve(), HeatedCircularPenetratorElement::resulting_force(), CircularPenetratorElement::resulting_force(), Quaternion::rotateInverseInertiaTensor(), ClumpParticle::rotatePrincipalDirections(), RotatingCylinderProblem< ELEMENT, TIMESTEPPER >::RotatingCylinderProblem(), RotatingDrumBidisperseInitialise::RotatingDrumBidisperseInitialise(), RotatingProblem< ELEMENT >::RotatingProblem(), Detail::round(), benchmark_t::run(), Eigen::internal::eulerangles_assign_impl< System, Other, 3, 3 >::run(), Eigen::internal::eulerangles_assign_impl< System, Other, 3, 1 >::run(), checkIdx::run(), run_navier_stokes_outflow(), PoissonProblem< ELEMENT >::save_custom_distribution_to_file(), ScatteringProblem< ELEMENT >::ScatteringProblem(), UnstructuredFluidProblem< ELEMENT >::set_boundary_conditions(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::set_boundary_conditions(), AxiPoroProblem< ELEMENT, TIMESTEPPER >::set_boundary_values(), oomph::Mesh::set_consistent_pinned_values_for_continuation(), HeatedCircularPenetratorElement::set_contact_element_mesh_pt(), CircularPenetratorElement::set_contact_element_mesh_pt(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::set_coordinate_for_projection(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::set_current_field_for_projection(), oomph::BiharmonicProblem< DIM >::set_dirichlet_boundary_condition(), MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::set_do_not_output_distance(), oomph::ImmersedRigidBodyElement::set_drag_mesh(), oomph::Mesh::set_elemental_internal_time_stepper(), oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::set_external_data_from_navier_stokes_outflow_mesh(), AdvectionProblem::set_initial_conditions(), EulerProblem::set_initial_conditions(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::set_lagrangian_coordinate_for_projection(), oomph::BiharmonicProblem< DIM >::set_neumann_boundary_condition(), AxisymmetricVibratingShellProblem< ELEMENT >::set_nprev_for_extrapolation_of_strain_rate_for_all_elements(), VibratingShellProblem< ELEMENT >::set_nprev_for_extrapolation_of_strain_rate_for_all_elements(), MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::set_output_distance(), CollapsibleChannelProblem< ELEMENT >::set_parallel_outflow(), oomph::Problem::set_pinned_values_to_zero(), CollapsibleChannelProblem< ELEMENT >::set_poiseuille_outflow(), RefineableTwoMeshFluxPoissonProblem< ELEMENT >::set_prescribed_flux_pt(), ScatteringProblem< ELEMENT >::set_prescribed_incoming_flux_pt(), set_pseudo_elastic_fsi_solver(), oomph::MGSolver< DIM >::set_self_test_vector(), GranularJet::set_silbert(), ChutePeriodic::set_silbert_parameters(), VariableBottom::set_silbert_parameters(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::set_time_level_for_projection(), SuperQuadricParticle::setAxesAndExponents(), PSD::setDistributionPhiNormal(), Quaternion::setEuler(), SuperQuadricParticle::setExponents(), MercuryBase::setHGridCellOverSizeRatio(), ChuteWithHopper::setHopper(), Quaternion::setOrientationViaNormal(), ClumpParticle::setPrincipalDirections_e1(), ClumpParticle::setPrincipalDirections_e2(), ClumpParticle::setPrincipalDirections_e3(), InsertionBoundary::setPSD(), GranularJet::setSilbert(), SegregationPeriodic::setSpeciesProperties(), ChutePeriodic::setup(), oomph::AlgebraicRefineableQuarterTubeMesh< ELEMENT >::setup_algebraic_node_update(), oomph::RefineableLineMesh< ELEMENT >::setup_binary_tree_forest(), oomph::TetMeshBase::setup_boundary_coordinates(), oomph::XdaTetMesh< ELEMENT >::setup_boundary_coordinates(), oomph::UnstructuredTwoDMeshGeometryBase::setup_boundary_coordinates(), oomph::BrickMeshBase::setup_boundary_element_info(), oomph::LineMeshBase::setup_boundary_element_info(), oomph::QuadMeshBase::setup_boundary_element_info(), oomph::TetMeshBase::setup_boundary_element_info(), oomph::TriangleMeshBase::setup_boundary_element_info(), oomph::HermiteQuadMesh< ELEMENT >::setup_boundary_element_info(), oomph::Multi_domain_functions::setup_bulk_elements_adjacent_to_face_mesh(), oomph::Problem::setup_element_count_per_dof(), MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::setup_elements(), oomph::DGMesh::setup_face_neighbour_info(), oomph::FourierDecomposedHelmholtzDtNMesh< ELEMENT >::setup_gamma(), oomph::HelmholtzDtNMesh< ELEMENT >::setup_gamma(), CollapsibleChannelProblem< ELEMENT >::setup_inflow_traction_elements(), SamplePointContainer::setup_min_and_max_coordinates(), MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::setup_multi_domain_interaction(), oomph::RefineableBrickMesh< ELEMENT >::setup_octree_forest(), HelmholtzPointSourceProblem< ELEMENT >::setup_outer_boundary(), ScatteringProblem< ELEMENT >::setup_outer_boundary(), CollapsibleChannelProblem< ELEMENT >::setup_outflow_flux_control_elements(), CollapsibleChannelProblem< ELEMENT >::setup_outflow_impedance_elements(), oomph::VorticitySmoother< ELEMENT >::setup_patches(), oomph::Z2ErrorEstimator::setup_patches(), oomph::RefineableQuadMesh< ELEMENT >::setup_quadtree_forest(), StefanBoltzmannProblem< ELEMENT >::setup_sb_radiation(), SolarRadiationProblem< ELEMENT >::setup_shielding_nodes(), oomph::StefanBoltzmannHelper::setup_stefan_boltzmann_visibility(), ChangingTOIParticle::setupInitialConditions(), NozzleDemo::setupInitialConditions(), RotatingDrumWet::setupInitialConditions(), Chain::setupInitialConditions(), ForceLawsMPI2Test::setupInitialConditions(), LiquidMigrationMPI2Test::setupInitialConditions(), FreeCooling2DinWalls::setupInitialConditions(), ShiftingConstantMassFlowMaserBoundarySelfTest::setupInitialConditions(), ShiftingMaserBoundarySelfTest::setupInitialConditions(), MeltableForceLaw2SelfTest::setupInitialConditions(), GetDistanceAndNormalForIntersectionOfWalls::setupInitialConditions(), GetDistanceAndNormalForScrew::setupInitialConditions(), GetDistanceAndNormalForTriangleWall::setupInitialConditions(), Drum::setupInitialConditions(), HertzSelfTest::setupInitialConditions(), MindlinSelfTest::setupInitialConditions(), Penetration::setupInitialConditions(), Silo::setupInitialConditions(), CubeDeletionBoundarySelfTest::setupInitialConditions(), DeletionBoundarySelfTest::setupInitialConditions(), DistributionPhiNormalSelfTest::setupInitialConditions(), DistributionSelfTest::setupInitialConditions(), DistributionToPSDSelfTest::setupInitialConditions(), InsertionBoundarySelfTest::setupInitialConditions(), MultiplePSDSelfTest::setupInitialConditions(), NozzleSelfTest::setupInitialConditions(), PolydisperseInsertionBoundarySelfTest::setupInitialConditions(), PSDManualInsertionSelfTest::setupInitialConditions(), ChargedBondedInteractionSelfTest::setupInitialConditions(), HertzianBSHPInteractionTwoParticleElasticCollision::setupInitialConditions(), LiquidMigrationSelfTest::setupInitialConditions(), DPM::setupInitialConditions(), ContactDetectionIntersectionOfWallsTest::setupInitialConditions(), GetDistanceAndNormalForTriangleWalls::setupInitialConditions(), RollingOverTriangleWalls::setupInitialConditions(), UnionOfWalls::setupInitialConditions(), BouncingSuperQuadric::setupInitialConditions(), EllipticalSuperQuadricCollision::setupInitialConditions(), SlidingSpheresUnitTest::setupInitialConditions(), ContactDetectionNormalSpheresTest::setupInitialConditions(), ContactDetectionRotatedSpheresTest::setupInitialConditions(), ShapesDemo::setupInitialConditions(), ParticleParticleInteraction::setupInitialConditions(), ParticleParticleInteractionWithPlasticForces::setupInitialConditions(), ParticleWallInteraction::setupInitialConditions(), ArcWallUnitTest::setupInitialConditions(), TwoParticles::setupInitialConditions(), Packing::setupInitialConditions(), PSDSelfTest::setupInitialConditions(), EvaporationAndHeatTest::setupInitialConditions(), RandomClusterInsertionBoundarySelfTest::setupInitialConditions(), FreeFall::setupInitialConditions(), HeatTransferUnitTest::setupInitialConditions(), PeriodicWalls::setupInitialConditions(), PeriodicWallsWithSlidingFrictionUnitTest::setupInitialConditions(), SeparateFilesSelfTest::setupInitialConditions(), SetDistributionPhiNormalSelfTest::setupInitialConditions(), SpeciesTest::setupInitialConditions(), CoupledBeam::setupMercury(), CoupledProblem::setupMercury(), ScaleCoupledBeam::setupOomph(), CoupledBeam::setupOomph(), CoupledProblem::setupOomph(), ShearStage::ShearStage(), ShellProblem< ELEMENT >::ShellProblem(), oomph::Mesh::shift_time_values(), Siegen::Siegen(), SilbertPeriodic::SilbertPeriodic(), SimpleRefineableFishMesh< ELEMENT >::SimpleRefineableFishMesh(), SingleParticle< SpeciesType >::SingleParticle(), SinterPair::SinterPair(), Slide::Slide(), oomph::RefineableTetgenMesh< ELEMENT >::snap_nodes_onto_boundary(), oomph::TetMeshBase::snap_nodes_onto_geometric_objects(), RisingBubbleProblem< ELEMENT >::snap_onto_sphere(), oomph::TetMeshBase::snap_to_quadratic_surface(), SolidBag::SolidBag(), SolidFreeSurfaceRotationProblem< ELEMENT >::SolidFreeSurfaceRotationProblem(), SolidProblem< ELEMENT_TYPE >::SolidProblem(), PredPreyProblem< ELEMENT >::solve(), ABCProblem< ELEMENT, TIMESTEPPERT >::solve(), oomph::AugmentedBlockFoldLinearSolver::solve(), oomph::AugmentedBlockPitchForkLinearSolver::solve(), oomph::BlockHopfLinearSolver::solve(), oomph::HSL_MA42::solve(), ShellProblem< ELEMENT >::solve(), SilbertHstop::solve_analytic(), oomph::HSL_MA42::solve_for_one_dof(), oomph::BlockHopfLinearSolver::solve_for_two_rhs(), solve_with_fully_automatic_adaptation(), solve_with_incremental_adaptation(), solve_with_selected_refinement_pattern(), Eigen::HybridNonLinearSolver< FunctorType, Scalar >::solveNumericalDiffOneStep(), Eigen::HybridNonLinearSolver< FunctorType, Scalar >::solveOneStep(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_lists(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_maps(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_two_arrays(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_two_vectors(), oomph::Problem::sparse_assemble_row_or_column_compressed_with_vectors_of_pairs(), sparse_basic(), sparse_extra(), sparse_product(), sparse_vector(), SphericalSpinUpProblem< ELEMENT >::SphericalSpinUpProblem(), SphericalSteadyRotationProblem< ELEMENT >::SphericalSteadyRotationProblem(), SpikedChannelSpineFlowProblem< ELEMENT >::SpikedChannelSpineFlowProblem(), oomph::TreeBasedRefineableMesh< ELEMENT >::split_elements_if_required(), oomph::TetMeshBase::split_elements_in_corners(), stable_norm(), StefanBoltzmannProblem< ELEMENT >::StefanBoltzmannProblem(), AxisymmetricVibratingShellProblem< ELEMENT >::strainrate_norm(), VibratingShellProblem< ELEMENT >::strainrate_norm(), STSpineMesh< ELEMENT, INTERFACE_ELEMENT >::surface_output(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::SurfactantProblem(), svd_least_square(), ContactProblem< ELEMENT >::switch_to_force_control(), TangentialSpringEnergyConservationUnitTest::TangentialSpringEnergyConservationUnitTest(), BoundingRadiusTester::test(), ContactDetectionNormalSpheresTest::test(), InertiaTensorTester::test(), VolumeTest::test(), Packing::test(), HertzContactRestitutionUnitTest::test(), test1(), test2(), test_array_zip_and_apply(), test_exponent(), test_hypot(), test_nnls_handles_dependent_columns(), test_nnls_handles_wide_matrix(), test_nnls_repeated_calls_to_compute_and_solve(), test_nnls_with_half_precision(), test_no_out_of_bounds(), test_precision< double >(), Eigen::test_precision< double >(), Eigen::test_precision< Real >(), test_scalar(), test_sycl_contraction(), ShapeGradientHessianTester::testCushion(), ShapeGradientHessianTester::testEllipsoid(), ContactDetectionWithWallTester::testEllipsoidsContact(), testMatrixType(), TreeTest< Dim >::testMinimize2(), ShapeGradientHessianTester::testRoundedBeam(), ShapeGradientHessianTester::testSphere(), ContactDetectionWithWallTester::testSpheresContact(), oomph::TetgenScaffoldMesh::TetgenScaffoldMesh(), TetmeshPoissonProblem< ELEMENT >::TetmeshPoissonProblem(), TFaceTestProblem< ELEMENT >::TFaceTestProblem(), oomph::ThinLayerBrickOnTetMesh< ELEMENT >::ThinLayerBrickOnTetMesh(), ThreeDimBethertonProblem< ELEMENT >::ThreeDimBethertonProblem(), TiltedCavityProblem< ELEMENT >::TiltedCavityProblem(), TimeDependentPeriodicBoundary3DSelfTest::TimeDependentPeriodicBoundary3DSelfTest(), TimeDependentPeriodicBoundaryTest::TimeDependentPeriodicBoundaryTest(), oomph::EBDF3::timestep(), TorusProblem< ELEMENT >::TorusProblem(), oomph::Mesh::total_size(), oomph::ImposeFluxForWomersleyElement< DIM >::total_volume_flux(), oomph::NavierStokesImpedanceTractionElement< BULK_NAVIER_STOKES_ELEMENT, WOMERSLEY_ELEMENT, DIM >::total_volume_flux_into_downstream_tube(), oomph::WomersleyImpedanceTubeBase< ELEMENT, DIM >::total_volume_flux_into_impedance_tube(), oomph::MyProblem::trace_values(), FlowAroundCylinderProblem< ELEMENT >::transfer_eigenfunction_as_initial_condition(), transformations(), transformations_computed_scaling_continuity(), TriangleFaceTestProblem< ELEMENT >::TriangleFaceTestProblem(), oomph::TriangleScaffoldMesh::TriangleScaffoldMesh(), triangular_square(), TriangulatedScrewSelfTest::TriangulatedScrewSelfTest(), TriangulatedStepSelfTest::TriangulatedStepSelfTest(), TriangulatedStepWallSelfTest::TriangulatedStepWallSelfTest(), TriangulatedWallSelfTest::TriangulatedWallSelfTest(), Eigen::internal::tridiagonal_qr_step(), Eigen::internal::trig_reduce_huge(), oomph::TrilinosAztecOOSolver::TrilinosAztecOOSolver(), TurekNonFSIProblem< ELEMENT >::TurekNonFSIProblem(), TurekProblem< FLUID_ELEMENT, SOLID_ELEMENT >::TurekProblem(), TwoByTwoMPIDomainMPI4Test::TwoByTwoMPIDomainMPI4Test(), TwoDDGMesh< ELEMENT >::TwoDDGMesh(), TwoDDGProblem< ELEMENT >::TwoDDGProblem(), TwoMeshFluxAdvectionDiffusionProblem< ELEMENT >::TwoMeshFluxAdvectionDiffusionProblem(), TwoMeshFluxPoissonProblem< ELEMENT >::TwoMeshFluxPoissonProblem(), unary_op_test(), ConvectionProblem< NST_ELEMENT, AD_ELEMENT >::unfix_pressure(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::unfix_pressure(), UniformTranspiration< ELEMENT >::UniformTranspiration(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::unpin_all(), FlowAroundCylinderProblem< ELEMENT >::unpin_all_base_flow_dofs(), oomph::RefineableLinearisedAxisymmetricNavierStokesEquations::unpin_all_pressure_dofs(), oomph::RefineableAxisymmetricNavierStokesEquations::unpin_all_pressure_dofs(), oomph::RefineableGeneralisedNewtonianAxisymmetricNavierStokesEquations::unpin_all_pressure_dofs(), oomph::RefineableGeneralisedNewtonianNavierStokesEquations< DIM >::unpin_all_pressure_dofs(), oomph::RefineableLinearisedNavierStokesEquations::unpin_all_pressure_dofs(), oomph::RefineableNavierStokesEquations< DIM >::unpin_all_pressure_dofs(), oomph::RefineablePolarNavierStokesEquations::unpin_all_pressure_dofs(), oomph::RefineableSpaceTimeNavierStokesEquations< DIM >::unpin_all_pressure_dofs(), oomph::RefineableSpaceTimeNavierStokesMixedOrderEquations< DIM >::unpin_all_pressure_dofs(), oomph::RefineableSphericalNavierStokesEquations::unpin_all_pressure_dofs(), oomph::PVDEquationsBase< DIM >::unpin_all_solid_pressure_dofs(), oomph::ProjectionProblem< PROJECTABLE_ELEMENT >::unpin_dofs_of_field(), SurfactantProblem< ELEMENT, INTERFACE_ELEMENT >::unpin_surface(), oomph::TreeBasedRefineableMeshBase::unrefine_uniformly(), UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >::UnstructuredFSIProblem(), UnstructuredTorusProblem< ELEMENT >::UnstructuredTorusProblem(), oomph::RefineableTetgenMesh< ELEMENT >::update_faceted_surface_using_face_mesh(), AxisymmetricVibratingShellProblem< ELEMENT >::update_latest_fixed_point_iteration_guess_for_strain_rate_for_all_elements(), VibratingShellProblem< ELEMENT >::update_latest_fixed_point_iteration_guess_for_strain_rate_for_all_elements(), SolarRadiationProblem< ELEMENT >::update_limiting_angles(), Membrane::updateEdgeMass(), ClumpParticle::updateExtraQuantities(), ElasticRefineableTwoLayerMesh< ELEMENT >::upper_layer_element_pt(), oomph::jh_mesh< ELEMENT >::upper_stress_integral_elt_pt(), oomph::FpPressureAdvectionDiffusionProblem< ELEMENT >::validate(), PSD::validateProbabilityDensityDistribution(), verify_euler(), MortaringValidationProblem< ELEMENT, NON_MORTAR_ELEMENT >::verify_mortared_nodes_coincide(), Wall::Wall(), Wind_fct_pt(), oomph::WomersleyImpedanceTubeBase< ELEMENT, DIM >::WomersleyImpedanceTubeBase(), oomph::WomersleyMesh< WOMERSLEY_ELEMENT >::WomersleyMesh(), oomph::WomersleyProblem< ELEMENT, DIM >::WomersleyProblem(), Membrane::write(), SilbertHstop::writeToEne(), SolidProblem< ELEMENT_TYPE >::writeToVTK(), oomph::XdaTetMesh< ELEMENT >::XdaTetMesh(), CapProblem< ELEMENT >::~CapProblem(), and PseudoSolidCapProblem< ELEMENT >::~PseudoSolidCapProblem().
x()
Array<double, 1, 3> x (8 , 25 , 3)