MercuryDPM: two_d_linear_wave_flux.cc File Reference
two_d_linear_wave_flux.cc File Reference
#include "generic.h"
#include "linear_wave.h"
#include "meshes/rectangular_quadmesh.h"
Classes
class LinearWaveProblem< ELEMENT, TIMESTEPPER >
LinearWave problem in rectanglular domain.
Namespaces
TanhSolnForLinearWave
Functions
double TanhSolnForLinearWave::exact_u (const double &time, const Vector< double > &x)
Exact solution.
double TanhSolnForLinearWave::exact_dudt (const double &time, const Vector< double > &x)
1st time-deriv of exact solution
double TanhSolnForLinearWave::exact_d2udt2 (const double &time, const Vector< double > &x)
2nd time-deriv of exact solution
void TanhSolnForLinearWave::get_exact_u (const double &time, const Vector< double > &x, Vector< double > &u)
Exact solution as a vector.
void TanhSolnForLinearWave::get_source (const double &time, const Vector< double > &x, double &source)
Source function to make it an exact solution.
void TanhSolnForLinearWave::get_exact_gradient (const double &time, const Vector< double > &x, Vector< double > &dudx)
Gradient of exact solution.
void TanhSolnForLinearWave::prescribed_flux_on_fixed_y_boundary (const double &time, const Vector< double > &x, double &flux)
Prescribed flux on a fixed y max boundary.
int main (int argc, char *argv[])
Demonstrate how to solve LinearWave problem.
Function Documentation
main()
int main (int argc , char * argv[])
Demonstrate how to solve LinearWave problem.
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Pointer to source function
  LinearWaveEquations<2>::LinearWaveSourceFctPt source_fct_pt=
   &TanhSolnForLinearWave::get_source;
  // Number of elements in x direction
  unsigned n_x=10;
  // Number of elements in y direction
  unsigned n_y=20;
  // Build problem
  LinearWaveProblem<QLinearWaveElement<2,3>, Newmark<1> >
   problem(n_x,n_y,source_fct_pt);
  // Run it
  problem.unsteady_run();
 }; // end of main
References TanhSolnForLinearWave::get_source(), problem, Flag_definition::setup(), and oomph::source_fct_pt().