MercuryDPM: Eigen::internal::compute_inverse_size4< Architecture::Target, float, MatrixType, ResultType > Struct Template Reference
Eigen::internal::compute_inverse_size4< Architecture::Target, float, MatrixType, ResultType > Struct Template Reference
#include <InverseSize4.h>
Public Types
enum { MatrixAlignment = traits<MatrixType>::Alignment , ResultAlignment = traits<ResultType>::Alignment , StorageOrdersMatch = (MatrixType::Flags & RowMajorBit) == (ResultType::Flags & RowMajorBit) }
typedef std::conditional_t<(MatrixType::Flags &LinearAccessBit), MatrixType const &, typename MatrixType::PlainObject > ActualMatrixType
Static Public Member Functions
static void run (const MatrixType &mat, ResultType &result)
Member Typedef Documentation
ActualMatrixType
template<typename MatrixType , typename ResultType > typedef std::conditional_t<(MatrixType::Flags & LinearAccessBit), MatrixType const &, typename MatrixType::PlainObject> Eigen::internal::compute_inverse_size4< Architecture::Target, float, MatrixType, ResultType >::ActualMatrixType
Member Enumeration Documentation
anonymous enum
template<typename MatrixType , typename ResultType > anonymous enum
Enumerator
MatrixAlignment
ResultAlignment
StorageOrdersMatch
        {
     MatrixAlignment = traits<MatrixType>::Alignment,
     ResultAlignment = traits<ResultType>::Alignment,
     StorageOrdersMatch = (MatrixType::Flags & RowMajorBit) == (ResultType::Flags & RowMajorBit)
   };
Member Function Documentation
run()
template<typename MatrixType , typename ResultType > static void Eigen::internal::compute_inverse_size4< Architecture::Target, float, MatrixType, ResultType >::run (const MatrixType & mat, ResultType & result) inline static
{
     ActualMatrixType matrix(mat);
     const float *data = matrix.data();
     const Index stride = matrix.innerStride();
     Packet4f L1 = ploadt<Packet4f, MatrixAlignment>(data);
     Packet4f L2 = ploadt<Packet4f, MatrixAlignment>(data + stride * 4);
     Packet4f L3 = ploadt<Packet4f, MatrixAlignment>(data + stride * 8);
     Packet4f L4 = ploadt<Packet4f, MatrixAlignment>(data + stride * 12);
     // Four 2x2 sub-matrices of the input matrix
     // input = [[A, B],
     //          [C, D]]
     Packet4f A, B, C, D;
     if (!StorageOrdersMatch) {
       A = vec4f_unpacklo(L1, L2);
       B = vec4f_unpacklo(L3, L4);
       C = vec4f_unpackhi(L1, L2);
       D = vec4f_unpackhi(L3, L4);
     } else {
       A = vec4f_movelh(L1, L2);
       B = vec4f_movehl(L2, L1);
       C = vec4f_movelh(L3, L4);
       D = vec4f_movehl(L4, L3);
     }
     Packet4f AB, DC;
     // AB = A# * B, where A# denotes the adjugate of A, and * denotes matrix product.
     AB = pmul(vec4f_swizzle2(A, A, 3, 3, 0, 0), B);
     AB = psub(AB, pmul(vec4f_swizzle2(A, A, 1, 1, 2, 2), vec4f_swizzle2(B, B, 2, 3, 0, 1)));
     // DC = D#*C
     DC = pmul(vec4f_swizzle2(D, D, 3, 3, 0, 0), C);
     DC = psub(DC, pmul(vec4f_swizzle2(D, D, 1, 1, 2, 2), vec4f_swizzle2(C, C, 2, 3, 0, 1)));
     // determinants of the sub-matrices
     Packet4f dA, dB, dC, dD;
     dA = pmul(vec4f_swizzle2(A, A, 3, 3, 1, 1), A);
     dA = psub(dA, vec4f_movehl(dA, dA));
     dB = pmul(vec4f_swizzle2(B, B, 3, 3, 1, 1), B);
     dB = psub(dB, vec4f_movehl(dB, dB));
     dC = pmul(vec4f_swizzle2(C, C, 3, 3, 1, 1), C);
     dC = psub(dC, vec4f_movehl(dC, dC));
     dD = pmul(vec4f_swizzle2(D, D, 3, 3, 1, 1), D);
     dD = psub(dD, vec4f_movehl(dD, dD));
     Packet4f d, d1, d2;
     d = pmul(vec4f_swizzle2(DC, DC, 0, 2, 1, 3), AB);
     d = padd(d, vec4f_movehl(d, d));
     d = padd(d, vec4f_swizzle2(d, d, 1, 0, 0, 0));
     d1 = pmul(dA, dD);
     d2 = pmul(dB, dC);
     // determinant of the input matrix, det = |A||D| + |B||C| - trace(A#*B*D#*C)
     Packet4f det = vec4f_duplane(psub(padd(d1, d2), d), 0);
     // reciprocal of the determinant of the input matrix, rd = 1/det
     Packet4f rd = preciprocal(det);
     // Four sub-matrices of the inverse
     Packet4f iA, iB, iC, iD;
     // iD = D*|A| - C*A#*B
     iD = pmul(vec4f_swizzle2(C, C, 0, 0, 2, 2), vec4f_movelh(AB, AB));
     iD = padd(iD, pmul(vec4f_swizzle2(C, C, 1, 1, 3, 3), vec4f_movehl(AB, AB)));
     iD = psub(pmul(D, vec4f_duplane(dA, 0)), iD);
     // iA = A*|D| - B*D#*C
     iA = pmul(vec4f_swizzle2(B, B, 0, 0, 2, 2), vec4f_movelh(DC, DC));
     iA = padd(iA, pmul(vec4f_swizzle2(B, B, 1, 1, 3, 3), vec4f_movehl(DC, DC)));
     iA = psub(pmul(A, vec4f_duplane(dD, 0)), iA);
     // iB = C*|B| - D * (A#B)# = C*|B| - D*B#*A
     iB = pmul(D, vec4f_swizzle2(AB, AB, 3, 0, 3, 0));
     iB = psub(iB, pmul(vec4f_swizzle2(D, D, 1, 0, 3, 2), vec4f_swizzle2(AB, AB, 2, 1, 2, 1)));
     iB = psub(pmul(C, vec4f_duplane(dB, 0)), iB);
     // iC = B*|C| - A * (D#C)# = B*|C| - A*C#*D
     iC = pmul(A, vec4f_swizzle2(DC, DC, 3, 0, 3, 0));
     iC = psub(iC, pmul(vec4f_swizzle2(A, A, 1, 0, 3, 2), vec4f_swizzle2(DC, DC, 2, 1, 2, 1)));
     iC = psub(pmul(B, vec4f_duplane(dC, 0)), iC);
     EIGEN_ALIGN_MAX const float sign_mask[4] = {0.0f, -0.0f, -0.0f, 0.0f};
     const Packet4f p4f_sign_PNNP = pload<Packet4f>(sign_mask);
     rd = pxor(rd, p4f_sign_PNNP);
     iA = pmul(iA, rd);
     iB = pmul(iB, rd);
     iC = pmul(iC, rd);
     iD = pmul(iD, rd);
     Index res_stride = result.outerStride();
     float *res = result.data();
     pstoret<float, Packet4f, ResultAlignment>(res + 0, vec4f_swizzle2(iA, iB, 3, 1, 3, 1));
     pstoret<float, Packet4f, ResultAlignment>(res + res_stride, vec4f_swizzle2(iA, iB, 2, 0, 2, 0));
     pstoret<float, Packet4f, ResultAlignment>(res + 2 * res_stride, vec4f_swizzle2(iC, iD, 3, 1, 3, 1));
     pstoret<float, Packet4f, ResultAlignment>(res + 3 * res_stride, vec4f_swizzle2(iC, iD, 2, 0, 2, 0));
   }
References D, data, EIGEN_ALIGN_MAX, matrix(), Eigen::internal::padd(), Eigen::internal::pload< Packet4f >(), Eigen::internal::pmul(), Eigen::internal::preciprocal(), Eigen::internal::psub(), Eigen::internal::pxor(), res, vec4f_duplane, Eigen::internal::vec4f_movehl(), Eigen::internal::vec4f_movelh(), Eigen::internal::vec4f_swizzle2(), Eigen::internal::vec4f_unpackhi(), and Eigen::internal::vec4f_unpacklo().
The documentation for this struct was generated from the following file:
InverseSize4.h