MercuryDPM: PerturbationSolution Namespace Reference
PerturbationSolution Namespace Reference
Christian's perturbation solution.
Functions
double get_radial_distance (const Vector< double > &x)
function to compute radial distance of this point
double get_azimuthal_angle (const Vector< double > &x)
function to return angle of radial line from positive x-axis
void polar_to_cartesian_velocity (const Vector< double > u_polar, const double phi, Vector< double > &u_cart)
function to convert velocity vectors from polar to Cartesian coords
void leading_order_veloc_and_pressure (const double r, const double phi, Vector< double > &u_0, double &p_0)
Leading order solution (u and p are in polar coordinates)
void first_order_veloc_and_pressure (const double r, const double phi, Vector< double > &u_1, double &p_1)
First order correction (u and p are in polar coordinates)
void second_order_veloc_and_pressure (const double r, const double phi, Vector< double > &u_2, double &p_2)
Second order correction (u and p are in polar coordinates)
void full_soln (const Vector< double > &x, Vector< double > &u, double &p, const unsigned &nterms=2)
void perturbation_soln_for_plot (const Vector< double > &x, Vector< double > &soln)
Combined solution (u,v,p) for plotting.
void first_order_perturbation_for_plot (const Vector< double > &x, Vector< double > &soln)
First order-perturbation for plotting.
void second_order_perturbation_for_plot (const Vector< double > &x, Vector< double > &soln)
Second order-perturbation for plotting.
Variables
void(* veloc_and_pressure_term_pt [3])(const double, const double, Vector< double > &, double &)
array of function pointers for each term in expansion
unsigned N_terms_for_plot =2
Number of terms in perturbation expansion for plot.
Detailed Description
Christian's perturbation solution.
Function Documentation
first_order_perturbation_for_plot()
void PerturbationSolution::first_order_perturbation_for_plot (const Vector< double > & x, Vector< double > & soln)
First order-perturbation for plotting.
   {
    soln.resize(3);
    // get radial distance to this point from origin
    double r = get_radial_distance(x);
    // get azimuthal angle of this point
    double phi = get_azimuthal_angle(x);
    // vector to hold each velocity term (Cartesian)
    Vector<double> u_i(2);
    // vector to hold velocity term (polar coordinates)
    Vector<double> u_polar(2);
    // variable to hold each pressure term
    double p_i = 0;
    // compute the term (in polar coordinates)
    veloc_and_pressure_term_pt[0](r, phi, u_polar, p_i);
    // convert coordinates to Cartesians
    polar_to_cartesian_velocity(u_polar, phi, u_i);
    // multiply by appropriate power of Re and add it to the solution
    soln[0]=-u_i[0];
    soln[1]=-u_i[1];
    soln[2]=-p_i;
    for (unsigned i=0;i<3;i++)
     {
      if (std::isinf(soln[i])) soln[i]=200.0;
      if (std::isnan(soln[i])) soln[i]=200.0;
     }
   }
References get_azimuthal_angle(), get_radial_distance(), i, isinf, isnan, polar_to_cartesian_velocity(), UniformPSDSelfTest::r, veloc_and_pressure_term_pt, and plotDoE::x.
first_order_veloc_and_pressure()
void PerturbationSolution::first_order_veloc_and_pressure (const double r, const double phi, Vector< double > & u_1, double & p_1)
First order correction (u and p are in polar coordinates)
   {
     // first order velocity term, r component
     u_1[0] = (r*(-2*pow(Pi,2)*(8 + pow(Pi,2)) +
        2*(8*pow(phi,2)*(-4 + pow(Pi,2)) - 8*phi*Pi*(2 + pow(Pi,2)) + pow(Pi,2)*(8 + pow(Pi,2)))*
         cos(2*phi) + (32*phi - 72*Pi - 64*pow(phi,2)*Pi + 24*phi*pow(Pi,2) + 6*pow(Pi,3) + pow(Pi,5))*
         sin(2*phi)))/(32.*pow(-4 + pow(Pi,2),2));
     // phi component
     u_1[1] = (r*(Pi*(24 - 14*pow(Pi,2) - pow(Pi,4) + 4*phi*Pi*(8 + pow(Pi,2))) +
        (-64*pow(phi,2)*Pi + 8*phi*(12 + pow(Pi,2)) + Pi*(-24 + 14*pow(Pi,2) + pow(Pi,4)))*cos(2*phi) -
        2*(24 + 10*pow(Pi,2) + pow(Pi,4) + 8*pow(phi,2)*(-4 + pow(Pi,2)) - 8*phi*Pi*(6 + pow(Pi,2)))*
         sin(2*phi)))/(32.*pow(-4 + pow(Pi,2),2));
     // first order pressure term
     p_1 = -(pow(Pi,2)*(-8 + pow(Pi,2))*log(r))/(4.*pow(-4 + pow(Pi,2),2));
   }
References cos(), Eigen::bfloat16_impl::log(), BiharmonicTestFunctions2::Pi, Eigen::bfloat16_impl::pow(), UniformPSDSelfTest::r, and sin().
full_soln()
void PerturbationSolution::full_soln (const Vector< double > & x, Vector< double > & u, double & p, const unsigned & nterms = 2)
Full solution. Final optional argument specifies number of terms in expansion (Stokes or Stokes plus leading order correction in Re)
   {
     // get radial distance to this point from origin
     double r = get_radial_distance(x);
     // get azimuthal angle of this point
     double phi = get_azimuthal_angle(x);
     // vector to hold each velocity term (Cartesian)
     Vector<double> u_i(2);
     // vector to hold velocity term (polar coordinates)
     Vector<double> u_polar(2);
     // variable to hold each pressure term
     double p_i = 0;
     // initialise solutions
     u[0] = 0.0;
     u[1] = 0.0;
     p    = 0.0;
     // -------------------------------------------
     // compute each term and add it to the solution
     for (unsigned i = 0; i < nterms; i++)
     {
       // compute the term (in polar coordinates)
       veloc_and_pressure_term_pt[i](r, phi, u_polar, p_i);
       // convert coordinates to Cartesians
       polar_to_cartesian_velocity(u_polar, phi, u_i);
       // multiply by appropriate power of Re and add it to the solution
       u[0] -= pow(Re, i) * u_i[0];
       u[1] -= pow(Re, i) * u_i[1];
       p    -= pow(Re, i) * p_i;
     }
   }
References get_azimuthal_angle(), get_radial_distance(), i, p, polar_to_cartesian_velocity(), Eigen::bfloat16_impl::pow(), UniformPSDSelfTest::r, GlobalPhysicalVariables::Re, veloc_and_pressure_term_pt, and plotDoE::x.
Referenced by perturbation_soln_for_plot().
get_azimuthal_angle()
double PerturbationSolution::get_azimuthal_angle (const Vector< double > & x)
function to return angle of radial line from positive x-axis
   {
     return atan2(x[1], x[0]);
   }
References atan2(), and plotDoE::x.
Referenced by first_order_perturbation_for_plot(), full_soln(), and second_order_perturbation_for_plot().
get_radial_distance()
double PerturbationSolution::get_radial_distance (const Vector< double > & x)
function to compute radial distance of this point
   {
     return sqrt(x[0]*x[0] + x[1]*x[1]);
   }
References sqrt(), and plotDoE::x.
Referenced by first_order_perturbation_for_plot(), full_soln(), and second_order_perturbation_for_plot().
leading_order_veloc_and_pressure()
void PerturbationSolution::leading_order_veloc_and_pressure (const double r, const double phi, Vector< double > & u_0, double & p_0)
Leading order solution (u and p are in polar coordinates)
   {
     // leading order velocity term, r component
     u_0[0] =
       (((4 + 2*phi*Pi - pow(Pi,2))*cos(phi) + 2*(-2*phi + Pi)*sin(phi)))/(-4 + pow(Pi,2));
     // phi component
     u_0[1] = ((-4*phi*cos(phi) + Pi*(-2*phi + Pi)*sin(phi)))/(-4 + pow(Pi,2));
     // leading order pressure term
     p_0 = (4*(2*cos(phi) + Pi*sin(phi)))/((-4 + pow(Pi,2))*r);
   }
References cos(), BiharmonicTestFunctions2::Pi, Eigen::bfloat16_impl::pow(), UniformPSDSelfTest::r, and sin().
perturbation_soln_for_plot()
void PerturbationSolution::perturbation_soln_for_plot (const Vector< double > & x, Vector< double > & soln)
Combined solution (u,v,p) for plotting.
   {
    soln.resize(3);
    double p=0.0;
    full_soln(x,soln,p,N_terms_for_plot);
    if (std::isinf(p)) p=200.0;
    if (std::isnan(p)) p=200.0;
    soln[2]=p;
   }
References full_soln(), isinf, isnan, N_terms_for_plot, p, and plotDoE::x.
polar_to_cartesian_velocity()
void PerturbationSolution::polar_to_cartesian_velocity (const Vector< double > u_polar, const double phi, Vector< double > & u_cart)
function to convert velocity vectors from polar to Cartesian coords
   {
     u_cart[0] = u_polar[0] * cos(phi) - u_polar[1] * sin(phi);
     u_cart[1] = u_polar[0] * sin(phi) + u_polar[1] * cos(phi);
   }
References cos(), and sin().
Referenced by first_order_perturbation_for_plot(), full_soln(), and second_order_perturbation_for_plot().
second_order_perturbation_for_plot()
void PerturbationSolution::second_order_perturbation_for_plot (const Vector< double > & x, Vector< double > & soln)
Second order-perturbation for plotting.
   {
    soln.resize(3);
    // get radial distance to this point from origin
    double r = get_radial_distance(x);
    // get azimuthal angle of this point
    double phi = get_azimuthal_angle(x);
    // vector to hold each velocity term (Cartesian)
    Vector<double> u_i(2);
    // vector to hold velocity term (polar coordinates)
    Vector<double> u_polar(2);
    // variable to hold each pressure term
    double p_i = 0;
    // compute the term (in polar coordinates)
    veloc_and_pressure_term_pt[1](r, phi, u_polar, p_i);
    // convert coordinates to Cartesians
    polar_to_cartesian_velocity(u_polar, phi, u_i);
    // multiply by appropriate power of Re and add it to the solution
    soln[0]=-u_i[0];
    soln[1]=-u_i[1];
    soln[2]=-p_i;
    for (unsigned i=0;i<3;i++)
     {
      if (std::isinf(soln[i])) soln[i]=200.0;
      if (std::isnan(soln[i])) soln[i]=200.0;
     }
   }
References get_azimuthal_angle(), get_radial_distance(), i, isinf, isnan, polar_to_cartesian_velocity(), UniformPSDSelfTest::r, veloc_and_pressure_term_pt, and plotDoE::x.
second_order_veloc_and_pressure()
void PerturbationSolution::second_order_veloc_and_pressure (const double r, const double phi, Vector< double > & u_2, double & p_2)
Second order correction (u and p are in polar coordinates)
   {
     // second order velocity term, r component
     u_2[0] = (pow(r,2)*(2*(-3952 + 3672*pow(Pi,2) - 51*pow(Pi,4) - 21*pow(Pi,6) +
           192*pow(phi,3)*Pi*(4 + pow(Pi,2)) + 72*phi*Pi*(2 + pow(Pi,2))*(-8 + 3*pow(Pi,2)) +
           144*pow(phi,2)*(20 + 5*pow(Pi,2) - 2*pow(Pi,4)))*cos(phi) +
        2*(3952 - 3672*pow(Pi,2) + 51*pow(Pi,4) + 21*pow(Pi,6) + 288*pow(phi,3)*Pi*(-12 + pow(Pi,2)) -
           432*pow(phi,2)*(-12 + 5*pow(Pi,2) + pow(Pi,4)) + 24*phi*Pi*(276 + 85*pow(Pi,2) + 9*pow(Pi,4)))*
         cos(3*phi) + (-768*pow(phi,3)*(4 + pow(Pi,2)) + 144*pow(phi,2)*Pi*(20 + 13*pow(Pi,2)) -
           36*phi*(-32 + 32*pow(Pi,2) + 42*pow(Pi,4) + pow(Pi,6)) +
           Pi*(-3648 + 2576*pow(Pi,2) + 564*pow(Pi,4) + 9*pow(Pi,6)))*sin(phi) +
        (3072*Pi + 1152*pow(phi,3)*(4 - 3*pow(Pi,2)) + 432*pow(phi,2)*Pi*(36 + 5*pow(Pi,2)) -
           pow(Pi,3)*(2560 + 252*pow(Pi,2) + 27*pow(Pi,4)) +
           12*phi*(-1024 + 72*pow(Pi,2) + 54*pow(Pi,4) + 3*pow(Pi,6)))*sin(3*phi)))/
    (4608.*pow(-4 + pow(Pi,2),3));
     // phi component
     u_2[1] = (pow(r,2)*((-768*pow(phi,3)*(4 + pow(Pi,2)) + 144*pow(phi,2)*Pi*(-12 + 5*pow(Pi,2)) -
           36*phi*(-224 - 16*pow(Pi,2) + 10*pow(Pi,4) + pow(Pi,6)) +
           Pi*(2112 + 1424*pow(Pi,2) + 132*pow(Pi,4) + 9*pow(Pi,6)))*cos(phi) +
        (-384*pow(phi,3)*(-4 + 3*pow(Pi,2)) + 48*pow(phi,2)*Pi*(156 + 11*pow(Pi,2)) -
           Pi*(2112 + 1424*pow(Pi,2) + 132*pow(Pi,4) + 9*pow(Pi,6)) +
           4*phi*(-1856 + 3*pow(Pi,2)*(6 + pow(Pi,2))*(28 + pow(Pi,2))))*cos(3*phi) +
        2*(-80 - 3960*pow(Pi,2) + 231*pow(Pi,4) + 39*pow(Pi,6) - 192*pow(phi,3)*Pi*(4 + pow(Pi,2)) +
           144*pow(phi,2)*(12 + 3*pow(Pi,2) + 2*pow(Pi,4)) - 72*phi*Pi*(-40 + 8*pow(Pi,2) + 3*pow(Pi,4)))*
         sin(phi) - 2*(80 - 888*pow(Pi,2) + 85*pow(Pi,4) + 9*pow(Pi,6) +
           96*pow(phi,3)*Pi*(-12 + pow(Pi,2)) + 8*phi*Pi*(588 + 107*pow(Pi,2) + 9*pow(Pi,4)) -
           48*pow(phi,2)*(-52 + 3*pow(Pi,2)*(9 + pow(Pi,2))))*sin(3*phi)))/(1536.*pow(-4 + pow(Pi,2),3));
     // second order pressure term
     p_2 = (r*(-((9632 - 6264*pow(Pi,2) + 552*pow(Pi,4) + 33*pow(Pi,6) + 144*phi*Pi*(28 - 13*pow(Pi,2)) +
             192*pow(phi,3)*Pi*(4 + pow(Pi,2)) - 288*pow(phi,2)*(20 + pow(Pi,2)))*cos(phi)) +
        9*(-352 + 80*pow(Pi,2) + 22*pow(Pi,4) + pow(Pi,6) + 32*pow(phi,2)*(4 - 3*pow(Pi,2)) +
           16*phi*Pi*(36 + pow(Pi,2)))*cos(3*phi) +
        (384*pow(phi,3)*(4 + pow(Pi,2)) - 144*pow(phi,2)*Pi*(-20 + 3*pow(Pi,2) + pow(Pi,4)) +
           36*phi*(-256 - 72*pow(Pi,2) + 10*pow(Pi,4) + pow(Pi,6)) +
           Pi*(7152 - 124*pow(Pi,2) + 24*pow(Pi,4) + 9*pow(Pi,6)))*sin(phi) -
        36*(96*phi - 48*(-2 + pow(phi,2))*Pi - 56*phi*pow(Pi,2) + 4*(4 + pow(phi,2))*pow(Pi,3) -
           4*phi*pow(Pi,4) + pow(Pi,5))*sin(3*phi)))/(576.*pow(-4 + pow(Pi,2),3));
   }
References cos(), BiharmonicTestFunctions2::Pi, Eigen::bfloat16_impl::pow(), UniformPSDSelfTest::r, and sin().
Variable Documentation
N_terms_for_plot
unsigned PerturbationSolution::N_terms_for_plot =2
Number of terms in perturbation expansion for plot.
Referenced by perturbation_soln_for_plot().
veloc_and_pressure_term_pt
void(* PerturbationSolution::veloc_and_pressure_term_pt[3])(const double, const double, Vector< double > &, double &) (const double , const double , Vector< double > & , double &)
Initial value:
=
  { & leading_order_veloc_and_pressure,
    & first_order_veloc_and_pressure,
    & second_order_veloc_and_pressure
  }
array of function pointers for each term in expansion
Referenced by first_order_perturbation_for_plot(), full_soln(), and second_order_perturbation_for_plot().