MercuryDPM: Time2Finish Class Reference
Time2Finish Class Reference
Estimates the total time, in seconds, left to reach the end of any simulation. First, the class needs to be initialized by calling set. After the class is initialized, an estimate of the total remaining time of the simulation can be found by calling getTime2Finish. The estimate is based on rate at which the simulation time progressed since initialization.
#include <MercuryTime.h>
Public Member Functions
Time2Finish (Mdouble t, Mdouble tMax)
Initialises the variable start with the current value of clock ticks, the current time and the final time of the simulation.
Mdouble getTime2Finish (Mdouble t)
Estimates the total time, in seconds, left to reach the end of any simulation. After the class is initialized, an estimate of the total remaining time of the simulation can be found by calling getTime2Finish. The estimate is based on rate at which the simulation time progressed since initialization.
std::string getFinishTime (Mdouble t)
Returns the estimated finish time based on the amount of time left to finish.
Private Attributes
clock_t startTime_
Stores the current number of clock ticks at the start.
Mdouble time_
Stores the simulation time (DPM units)
Mdouble timeMax_
Stores the total simulation time (DPM units)
Detailed Description
Estimates the total time, in seconds, left to reach the end of any simulation. First, the class needs to be initialized by calling set. After the class is initialized, an estimate of the total remaining time of the simulation can be found by calling getTime2Finish. The estimate is based on rate at which the simulation time progressed since initialization.
E.g., assume that the class has been initialized at simulation time 0, with final time 10. Then, getTime2Finish is called after 1 hour at simulation time 2. Since the code required 0.5 hours per simulation time unit and there are 8 simulation time units left, it is likely to finish in 4 hours.
Constructor & Destructor Documentation
Time2Finish()
Time2Finish::Time2Finish (Mdouble t, Mdouble tMax) inline
Initialises the variable start with the current value of clock ticks, the current time and the final time of the simulation.
Parameters
[in] t current simulation time.
[in] tMax total simulation time for which the simulation is set to run.
     {
         startTime_ = clock();
         time_ = t;
         timeMax_ = tMax;
     }
References startTime_, plotPSD::t, time_, and timeMax_.
Member Function Documentation
getFinishTime()
std::string Time2Finish::getFinishTime (Mdouble t) inline
Returns the estimated finish time based on the amount of time left to finish.
Parameters
[in] t current simulation time
Returns
time of the day, in hours, at which the simulation is predicted to end
     {
         // gets the estimated time left to finish.
         Mdouble time2Finish = getTime2Finish(t);
         // adds to the estimated time to current time and also type-casting Mdouble to time_t.
         time_t finish = time(nullptr) + time2Finish;
         std::stringstream ss;
         //write estimated end time
         ss << ctime(&finish);
         //decrement put pointer by one to avoid line break
         ss.seekp((long) ss.tellp() - 1);
         //write time to finish
         ss << " (" << time2Finish / 3600 << "h)";
         return ss.str();
     }
References getTime2Finish(), and plotPSD::t.
getTime2Finish()
Mdouble Time2Finish::getTime2Finish (Mdouble t) inline
Estimates the total time, in seconds, left to reach the end of any simulation. After the class is initialized, an estimate of the total remaining time of the simulation can be found by calling getTime2Finish. The estimate is based on rate at which the simulation time progressed since initialization.
E.g., assume that the class has been initialized at simulation time 0, with final time 10. Then, getTime2Finish is called after 1 hour at simulation time 2. Since the code required 0.5 hours per simulation time unit and there are 8 simulation time units left, it is likely to finish in 4 hours.
Parameters
[in] t current simulation time.
Returns
Mdouble time, in seconds, left to reach the end of any simulation
     {
         clock_t finish = clock();
         Mdouble elapsedTime = (Mdouble(finish) - Mdouble(startTime_)) / CLOCKS_PER_SEC;
         if (fabs(time_ - t) < 1.e-9)
         {
             logger(WARN, "Choose an other value for t");
             return 0;
         }
         else
         {
             Mdouble time2Finish = elapsedTime * (timeMax_ - time_) / (t - time_);
             startTime_ = finish;
             time_ = t;
             return time2Finish;
         }
     }
References boost::multiprecision::fabs(), logger, startTime_, plotPSD::t, time_, timeMax_, and WARN.
Referenced by getFinishTime().
Member Data Documentation
startTime_
clock_t Time2Finish::startTime_ private
Stores the current number of clock ticks at the start.
Referenced by getTime2Finish(), and Time2Finish().
time_
Mdouble Time2Finish::time_ private
Stores the simulation time (DPM units)
Referenced by getTime2Finish(), and Time2Finish().
timeMax_
Mdouble Time2Finish::timeMax_ private
Stores the total simulation time (DPM units)
Referenced by getTime2Finish(), and Time2Finish().
The documentation for this class was generated from the following file:
MercuryTime.h