MercuryDPM: STLReaderUnitTest.cpp File Reference
STLReaderUnitTest.cpp File Reference
#include <fstream>
#include <iostream>
#include <vector>
#include <string>
#include <BinaryReader.h>
#include <Logger.h>
#include <Math/Vector.h>
#include <CMakeDefinitions.h>
#include <Mercury3D.h>
#include <Species/LinearViscoelasticSpecies.h>
Functions
int main ()
Test of the STL reader. The files read is an STL file containing 12 triangles that forms a unit cube, created in autocad.
Function Documentation
main()
int main ()
Test of the STL reader. The files read is an STL file containing 12 triangles that forms a unit cube, created in autocad.
 {
     std::string directory = getMercuryDPMSourceDir();
     std::string filename = directory+"/Drivers/ImportTools/ExampleSTLFiles/Box1x1x1.stl";
     Mercury3D dpm;
     auto species = dpm.speciesHandler.copyAndAddObject(LinearViscoelasticSpecies());
     dpm.wallHandler.readTriangleWall(filename,species);
     helpers::check(dpm.wallHandler.getNumberOfObjects(),12,0,"Number of walls read");
     dpm.write(std::cout,true);
     return 0;
 }
References helpers::check(), BaseHandler< T >::copyAndAddObject(), MergeRestartFiles::filename, getMercuryDPMSourceDir(), BaseHandler< T >::getNumberOfObjects(), WallHandler::readTriangleWall(), DPMBase::speciesHandler, oomph::Global_string_for_annotation::string(), DPMBase::wallHandler, and MercuryBase::write().