MercuryDPM: Eigen::SelfAdjointView< MatrixType_, UpLo > Class Template Reference
Eigen::SelfAdjointView< MatrixType_, UpLo > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
Expression of a selfadjoint matrix from a triangular part of a dense matrix.
#include <SelfAdjointView.h>
Public Types
enum { Mode = internal::traits<SelfAdjointView>::Mode , Flags = internal::traits<SelfAdjointView>::Flags , TransposeMode = ((int(Mode) & int(Upper)) ? Lower : 0) | ((int(Mode) & int(Lower)) ? Upper : 0) }
typedef MatrixType_ MatrixType
typedef TriangularBase< SelfAdjointView > Base
typedef internal::traits< SelfAdjointView >::MatrixTypeNested MatrixTypeNested
typedef internal::traits< SelfAdjointView >::MatrixTypeNestedCleaned MatrixTypeNestedCleaned
typedef MatrixTypeNestedCleaned NestedExpression
typedef internal::traits< SelfAdjointView >::Scalar Scalar
The type of coefficients in this matrix.
typedef MatrixType::StorageIndex StorageIndex
typedef internal::remove_all_t< typename MatrixType::ConjugateReturnType > MatrixConjugateReturnType
typedef SelfAdjointView< std::add_const_t< MatrixType >, UpLo > ConstSelfAdjointView
typedef MatrixType::PlainObject PlainObject
typedef SelfAdjointView< const MatrixConjugateReturnType, UpLo > ConjugateReturnType
typedef SelfAdjointView< const typename MatrixType::AdjointReturnType, TransposeMode > AdjointReturnType
typedef SelfAdjointView< typename MatrixType::TransposeReturnType, TransposeMode > TransposeReturnType
typedef SelfAdjointView< const typename MatrixType::ConstTransposeReturnType, TransposeMode > ConstTransposeReturnType
typedef NumTraits< Scalar >::Real RealScalar
typedef Matrix< RealScalar, internal::traits< MatrixType >::ColsAtCompileTime, 1 > EigenvaluesReturnType
Public Types inherited from Eigen::TriangularBase< SelfAdjointView< MatrixType_, UpLo > >
enum
typedef internal::traits< SelfAdjointView< MatrixType_, UpLo > >::Scalar Scalar
typedef internal::traits< SelfAdjointView< MatrixType_, UpLo > >::StorageKind StorageKind
typedef internal::traits< SelfAdjointView< MatrixType_, UpLo > >::StorageIndex StorageIndex
typedef internal::traits< SelfAdjointView< MatrixType_, UpLo > >::FullMatrixType DenseMatrixType
typedef DenseMatrixType DenseType
typedef SelfAdjointView< MatrixType_, UpLo > const & Nested
Public Types inherited from Eigen::EigenBase< Derived >
typedef Eigen::Index Index
The interface type of indices.
typedef internal::traits< Derived >::StorageKind StorageKind
Public Member Functions
EIGEN_DEVICE_FUNC SelfAdjointView (MatrixType &matrix)
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index outerStride () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index innerStride () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC Scalar coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC Scalar & coeffRef (Index row, Index col)
EIGEN_DEVICE_FUNC const MatrixTypeNestedCleaned & _expression () const
EIGEN_DEVICE_FUNC const MatrixTypeNestedCleaned & nestedExpression () const
EIGEN_DEVICE_FUNC MatrixTypeNestedCleaned & nestedExpression ()
template<typename OtherDerived >
EIGEN_DEVICE_FUNC const Product< SelfAdjointView, OtherDerived > operator* (const MatrixBase< OtherDerived > &rhs) const
template<typename DerivedU , typename DerivedV >
EIGEN_DEVICE_FUNC SelfAdjointView & rankUpdate (const MatrixBase< DerivedU > &u, const MatrixBase< DerivedV > &v, const Scalar &alpha=Scalar(1))
template<typename DerivedU >
EIGEN_DEVICE_FUNC SelfAdjointView & rankUpdate (const MatrixBase< DerivedU > &u, const Scalar &alpha=Scalar(1))
template<unsigned int TriMode>
EIGEN_DEVICE_FUNC std::conditional_t<(TriMode &(Upper|Lower))==(UpLo &(Upper|Lower)), TriangularView< MatrixType, TriMode >, TriangularView< typename MatrixType::AdjointReturnType, TriMode > > triangularView () const
EIGEN_DEVICE_FUNC const ConjugateReturnType conjugate () const
template<bool Cond>
EIGEN_DEVICE_FUNC std::conditional_t< Cond, ConjugateReturnType, ConstSelfAdjointView > conjugateIf () const
EIGEN_DEVICE_FUNC const AdjointReturnType adjoint () const
template<class Dummy = int>
EIGEN_DEVICE_FUNC TransposeReturnType transpose (std::enable_if_t< Eigen::internal::is_lvalue< MatrixType >::value, Dummy * >=nullptr)
EIGEN_DEVICE_FUNC const ConstTransposeReturnType transpose () const
EIGEN_DEVICE_FUNC MatrixType::ConstDiagonalReturnType diagonal () const
const LLT< PlainObject, UpLo > llt () const
const LDLT< PlainObject, UpLo > ldlt () const
EIGEN_DEVICE_FUNC EigenvaluesReturnType eigenvalues () const
Computes the eigenvalues of a matrix.
EIGEN_DEVICE_FUNC RealScalar operatorNorm () const
Computes the L2 operator norm.
template<typename DerivedU >
EIGEN_DEVICE_FUNC SelfAdjointView< MatrixType, UpLo > & rankUpdate (const MatrixBase< DerivedU > &u, const Scalar &alpha)
template<typename DerivedU , typename DerivedV >
EIGEN_DEVICE_FUNC SelfAdjointView< MatrixType, UpLo > & rankUpdate (const MatrixBase< DerivedU > &u, const MatrixBase< DerivedV > &v, const Scalar &alpha)
Public Member Functions inherited from Eigen::TriangularBase< SelfAdjointView< MatrixType_, UpLo > >
EIGEN_DEVICE_FUNC TriangularBase ()
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index outerStride () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index innerStride () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC void resize (Index rows, Index cols)
EIGEN_DEVICE_FUNC Scalar coeff (Index row, Index col) const
EIGEN_DEVICE_FUNC Scalar & coeffRef (Index row, Index col)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void copyCoeff (Index row, Index col, Other &other)
EIGEN_DEVICE_FUNC Scalar operator() (Index row, Index col) const
EIGEN_DEVICE_FUNC Scalar & operator() (Index row, Index col)
EIGEN_DEVICE_FUNC const SelfAdjointView< MatrixType_, UpLo > & derived () const
EIGEN_DEVICE_FUNC SelfAdjointView< MatrixType_, UpLo > & derived ()
EIGEN_DEVICE_FUNC void evalTo (MatrixBase< DenseDerived > &other) const
EIGEN_DEVICE_FUNC void evalToLazy (MatrixBase< DenseDerived > &other) const
EIGEN_DEVICE_FUNC DenseMatrixType toDenseMatrix () const
Public Member Functions inherited from Eigen::EigenBase< Derived >
constexpr EIGEN_DEVICE_FUNC Derived & derived ()
constexpr EIGEN_DEVICE_FUNC const Derived & derived () const
EIGEN_DEVICE_FUNC Derived & const_cast_derived () const
EIGEN_DEVICE_FUNC const Derived & const_derived () const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index size () const EIGEN_NOEXCEPT
template<typename Dest >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void addTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void subTo (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheRight (Dest &dst) const
template<typename Dest >
EIGEN_DEVICE_FUNC void applyThisOnTheLeft (Dest &dst) const
template<typename Device >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< Derived, Device > device (Device &device)
template<typename Device >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE DeviceWrapper< const Derived, Device > device (Device &device) const
Protected Attributes
MatrixTypeNested m_matrix
Friends
template<typename OtherDerived >
EIGEN_DEVICE_FUNC const Product< OtherDerived, SelfAdjointView > operator* (const MatrixBase< OtherDerived > &lhs, const SelfAdjointView &rhs)
EIGEN_DEVICE_FUNC const SelfAdjointView< const EIGEN_SCALAR_BINARYOP_EXPR_RETURN_TYPE(Scalar, MatrixType, product), UpLo > operator* (const Scalar &s, const SelfAdjointView &mat)
Additional Inherited Members
Protected Member Functions inherited from Eigen::TriangularBase< SelfAdjointView< MatrixType_, UpLo > >
void check_coordinates (Index row, Index col) const
void check_coordinates_internal (Index, Index) const
Detailed Description
template<typename MatrixType_, unsigned int UpLo>
class Eigen::SelfAdjointView< MatrixType_, UpLo >
Expression of a selfadjoint matrix from a triangular part of a dense matrix.
Template Parameters
MatrixType the type of the dense matrix storing the coefficients
TriangularPart can be either Lower or Upper
This class is an expression of a sefladjoint matrix from a triangular part of a matrix with given dense storage of the coefficients. It is the return type of MatrixBase::selfadjointView() and most of the time this is the only way that it is used.
See also
class TriangularBase, MatrixBase::selfadjointView()
Member Typedef Documentation
AdjointReturnType
template<typename MatrixType_ , unsigned int UpLo> typedef SelfAdjointView<const typename MatrixType::AdjointReturnType, TransposeMode> Eigen::SelfAdjointView< MatrixType_, UpLo >::AdjointReturnType
Base
template<typename MatrixType_ , unsigned int UpLo> typedef TriangularBase<SelfAdjointView> Eigen::SelfAdjointView< MatrixType_, UpLo >::Base
ConjugateReturnType
template<typename MatrixType_ , unsigned int UpLo> typedef SelfAdjointView<const MatrixConjugateReturnType, UpLo> Eigen::SelfAdjointView< MatrixType_, UpLo >::ConjugateReturnType
ConstSelfAdjointView
template<typename MatrixType_ , unsigned int UpLo> typedef SelfAdjointView<std::add_const_t<MatrixType>, UpLo> Eigen::SelfAdjointView< MatrixType_, UpLo >::ConstSelfAdjointView
ConstTransposeReturnType
template<typename MatrixType_ , unsigned int UpLo> typedef SelfAdjointView<const typename MatrixType::ConstTransposeReturnType, TransposeMode> Eigen::SelfAdjointView< MatrixType_, UpLo >::ConstTransposeReturnType
EigenvaluesReturnType
template<typename MatrixType_ , unsigned int UpLo> typedef Matrix<RealScalar, internal::traits<MatrixType>::ColsAtCompileTime, 1> Eigen::SelfAdjointView< MatrixType_, UpLo >::EigenvaluesReturnType
Return type of eigenvalues()
MatrixConjugateReturnType
template<typename MatrixType_ , unsigned int UpLo> typedef internal::remove_all_t<typename MatrixType::ConjugateReturnType> Eigen::SelfAdjointView< MatrixType_, UpLo >::MatrixConjugateReturnType
MatrixType
template<typename MatrixType_ , unsigned int UpLo> typedef MatrixType_ Eigen::SelfAdjointView< MatrixType_, UpLo >::MatrixType
MatrixTypeNested
template<typename MatrixType_ , unsigned int UpLo> typedef internal::traits<SelfAdjointView>::MatrixTypeNested Eigen::SelfAdjointView< MatrixType_, UpLo >::MatrixTypeNested
MatrixTypeNestedCleaned
template<typename MatrixType_ , unsigned int UpLo> typedef internal::traits<SelfAdjointView>::MatrixTypeNestedCleaned Eigen::SelfAdjointView< MatrixType_, UpLo >::MatrixTypeNestedCleaned
NestedExpression
template<typename MatrixType_ , unsigned int UpLo> typedef MatrixTypeNestedCleaned Eigen::SelfAdjointView< MatrixType_, UpLo >::NestedExpression
PlainObject
template<typename MatrixType_ , unsigned int UpLo> typedef MatrixType::PlainObject Eigen::SelfAdjointView< MatrixType_, UpLo >::PlainObject
RealScalar
template<typename MatrixType_ , unsigned int UpLo> typedef NumTraits<Scalar>::Real Eigen::SelfAdjointView< MatrixType_, UpLo >::RealScalar
Real part of Scalar
Scalar
template<typename MatrixType_ , unsigned int UpLo> typedef internal::traits<SelfAdjointView>::Scalar Eigen::SelfAdjointView< MatrixType_, UpLo >::Scalar
The type of coefficients in this matrix.
StorageIndex
template<typename MatrixType_ , unsigned int UpLo> typedef MatrixType::StorageIndex Eigen::SelfAdjointView< MatrixType_, UpLo >::StorageIndex
TransposeReturnType
template<typename MatrixType_ , unsigned int UpLo> typedef SelfAdjointView<typename MatrixType::TransposeReturnType, TransposeMode> Eigen::SelfAdjointView< MatrixType_, UpLo >::TransposeReturnType
Member Enumeration Documentation
anonymous enum
template<typename MatrixType_ , unsigned int UpLo> anonymous enum
Enumerator
Mode
Flags
TransposeMode
        {
     Mode = internal::traits<SelfAdjointView>::Mode,
     Flags = internal::traits<SelfAdjointView>::Flags,
     TransposeMode = ((int(Mode) & int(Upper)) ? Lower : 0) | ((int(Mode) & int(Lower)) ? Upper : 0)
   };
Constructor & Destructor Documentation
SelfAdjointView()
template<typename MatrixType_ , unsigned int UpLo> EIGEN_DEVICE_FUNC Eigen::SelfAdjointView< MatrixType_, UpLo >::SelfAdjointView (MatrixType & matrix) inline explicit
 : m_matrix(matrix) {}
Member Function Documentation
_expression()
template<typename MatrixType_ , unsigned int UpLo> EIGEN_DEVICE_FUNC const MatrixTypeNestedCleaned& Eigen::SelfAdjointView< MatrixType_, UpLo >::_expression () const inline
 { return m_matrix; }
References Eigen::SelfAdjointView< MatrixType_, UpLo >::m_matrix.
adjoint()
template<typename MatrixType_ , unsigned int UpLo> EIGEN_DEVICE_FUNC const AdjointReturnType Eigen::SelfAdjointView< MatrixType_, UpLo >::adjoint () const inline
See also
MatrixBase::adjoint() const
 { return AdjointReturnType(m_matrix.adjoint()); }
References Eigen::SelfAdjointView< MatrixType_, UpLo >::m_matrix.
coeff()
template<typename MatrixType_ , unsigned int UpLo> EIGEN_DEVICE_FUNC Scalar Eigen::SelfAdjointView< MatrixType_, UpLo >::coeff (Index row, Index col) const inline
See also
MatrixBase::coeff()
Warning
the coordinates must fit into the referenced triangular part
{
     Base::check_coordinates_internal(row, col);
     return m_matrix.coeff(row, col);
   }
References Eigen::TriangularBase< Derived >::check_coordinates_internal(), col(), Eigen::SelfAdjointView< MatrixType_, UpLo >::m_matrix, and row().
coeffRef()
template<typename MatrixType_ , unsigned int UpLo> EIGEN_DEVICE_FUNC Scalar& Eigen::SelfAdjointView< MatrixType_, UpLo >::coeffRef (Index row, Index col) inline
See also
MatrixBase::coeffRef()
Warning
the coordinates must fit into the referenced triangular part
{
     EIGEN_STATIC_ASSERT_LVALUE(SelfAdjointView);
     Base::check_coordinates_internal(row, col);
     return m_matrix.coeffRef(row, col);
   }
References Eigen::TriangularBase< Derived >::check_coordinates_internal(), col(), EIGEN_STATIC_ASSERT_LVALUE, Eigen::SelfAdjointView< MatrixType_, UpLo >::m_matrix, and row().
Referenced by foo().
cols()
template<typename MatrixType_ , unsigned int UpLo> EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::SelfAdjointView< MatrixType_, UpLo >::cols () const inline
 { return m_matrix.cols(); }
References Eigen::SelfAdjointView< MatrixType_, UpLo >::m_matrix.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
conjugate()
template<typename MatrixType_ , unsigned int UpLo> EIGEN_DEVICE_FUNC const ConjugateReturnType Eigen::SelfAdjointView< MatrixType_, UpLo >::conjugate (void) const inline
See also
MatrixBase::conjugate() const
{
     return ConjugateReturnType(m_matrix.conjugate());
   }
References Eigen::SelfAdjointView< MatrixType_, UpLo >::m_matrix.
conjugateIf()
template<typename MatrixType_ , unsigned int UpLo> template<bool Cond> EIGEN_DEVICE_FUNC std::conditional_t<Cond, ConjugateReturnType, ConstSelfAdjointView> Eigen::SelfAdjointView< MatrixType_, UpLo >::conjugateIf () const inline
Returns
an expression of the complex conjugate of *this if Cond==true, returns *this otherwise.
{
     typedef std::conditional_t<Cond, ConjugateReturnType, ConstSelfAdjointView> ReturnType;
     return ReturnType(m_matrix.template conjugateIf<Cond>());
   }
References Eigen::SelfAdjointView< MatrixType_, UpLo >::m_matrix.
diagonal()
template<typename MatrixType_ , unsigned int UpLo> EIGEN_DEVICE_FUNC MatrixType::ConstDiagonalReturnType Eigen::SelfAdjointView< MatrixType_, UpLo >::diagonal () const inline
Returns
a const expression of the main diagonal of the matrix *this
This method simply returns the diagonal of the nested expression, thus by-passing the SelfAdjointView decorator.
See also
MatrixBase::diagonal(), class Diagonal
{
     return typename MatrixType::ConstDiagonalReturnType(m_matrix);
   }
References Eigen::SelfAdjointView< MatrixType_, UpLo >::m_matrix.
eigenvalues()
template<typename MatrixType , unsigned int UpLo> EIGEN_DEVICE_FUNC SelfAdjointView< MatrixType, UpLo >::EigenvaluesReturnType Eigen::SelfAdjointView< MatrixType, UpLo >::eigenvalues inline
Computes the eigenvalues of a matrix.
Returns
Column vector containing the eigenvalues.
\eigenvalues_module This function computes the eigenvalues with the help of the SelfAdjointEigenSolver class. The eigenvalues are repeated according to their algebraic multiplicity, so there are as many eigenvalues as rows in the matrix.
Example:
MatrixXd ones = MatrixXd::Ones(3, 3);
VectorXd eivals = ones.selfadjointView<Lower>().eigenvalues();
cout << "The eigenvalues of the 3x3 matrix of ones are:" << endl << eivals << endl;
Output:
See also
SelfAdjointEigenSolver::eigenvalues(), MatrixBase::eigenvalues()
{
   PlainObject thisAsMatrix(*this);
   return SelfAdjointEigenSolver<PlainObject>(thisAsMatrix, false).eigenvalues();
 }
References Eigen::SelfAdjointEigenSolver< MatrixType_ >::eigenvalues().
innerStride()
template<typename MatrixType_ , unsigned int UpLo> EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::SelfAdjointView< MatrixType_, UpLo >::innerStride () const inline
 { return m_matrix.innerStride(); }
References Eigen::SelfAdjointView< MatrixType_, UpLo >::m_matrix.
ldlt()
template<typename MatrixType , unsigned int UpLo> const LDLT< typename SelfAdjointView< MatrixType, UpLo >::PlainObject, UpLo > Eigen::SelfAdjointView< MatrixType, UpLo >::ldlt inline
\cholesky_module
Returns
the Cholesky decomposition with full pivoting without square root of *this
See also
MatrixBase::ldlt()
{
   return LDLT<PlainObject, UpLo>(m_matrix);
 }
References Eigen::LDLT< MatrixType_, UpLo_ >::m_matrix.
llt()
template<typename MatrixType , unsigned int UpLo> const LLT< typename SelfAdjointView< MatrixType, UpLo >::PlainObject, UpLo > Eigen::SelfAdjointView< MatrixType, UpLo >::llt inline
\cholesky_module
Returns
the LLT decomposition of *this
See also
SelfAdjointView::llt()
           {
   return LLT<PlainObject, UpLo>(m_matrix);
 }
References Eigen::LLT< MatrixType_, UpLo_ >::m_matrix.
nestedExpression() [1/2]
template<typename MatrixType_ , unsigned int UpLo> EIGEN_DEVICE_FUNC MatrixTypeNestedCleaned& Eigen::SelfAdjointView< MatrixType_, UpLo >::nestedExpression () inline
 { return m_matrix; }
References Eigen::SelfAdjointView< MatrixType_, UpLo >::m_matrix.
nestedExpression() [2/2]
template<typename MatrixType_ , unsigned int UpLo> EIGEN_DEVICE_FUNC const MatrixTypeNestedCleaned& Eigen::SelfAdjointView< MatrixType_, UpLo >::nestedExpression () const inline
 { return m_matrix; }
References Eigen::SelfAdjointView< MatrixType_, UpLo >::m_matrix.
operator*()
template<typename MatrixType_ , unsigned int UpLo> template<typename OtherDerived > EIGEN_DEVICE_FUNC const Product<SelfAdjointView, OtherDerived> Eigen::SelfAdjointView< MatrixType_, UpLo >::operator* (const MatrixBase< OtherDerived > & rhs) const inline
Efficient triangular matrix times vector/matrix product
{
     return Product<SelfAdjointView, OtherDerived>(*this, rhs.derived());
   }
operatorNorm()
template<typename MatrixType , unsigned int UpLo> EIGEN_DEVICE_FUNC SelfAdjointView< MatrixType, UpLo >::RealScalar Eigen::SelfAdjointView< MatrixType, UpLo >::operatorNorm inline
Computes the L2 operator norm.
Returns
Operator norm of the matrix.
\eigenvalues_module This function computes the L2 operator norm of a self-adjoint matrix. For a self-adjoint matrix, the operator norm is the largest eigenvalue.
The current implementation uses the eigenvalues of the matrix, as computed by eigenvalues(), to compute the operator norm of the matrix.
Example:
MatrixXd ones = MatrixXd::Ones(3, 3);
cout << "The operator norm of the 3x3 matrix of ones is " << ones.selfadjointView<Lower>().operatorNorm() << endl;
Output:
See also
eigenvalues(), MatrixBase::operatorNorm()
{
   return eigenvalues().cwiseAbs().maxCoeff();
 }
outerStride()
template<typename MatrixType_ , unsigned int UpLo> EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::SelfAdjointView< MatrixType_, UpLo >::outerStride () const inline
 { return m_matrix.outerStride(); }
References Eigen::SelfAdjointView< MatrixType_, UpLo >::m_matrix.
rankUpdate() [1/4]
template<typename MatrixType_ , unsigned int UpLo> template<typename DerivedU , typename DerivedV > EIGEN_DEVICE_FUNC SelfAdjointView<MatrixType, UpLo>& Eigen::SelfAdjointView< MatrixType_, UpLo >::rankUpdate (const MatrixBase< DerivedU > & u, const MatrixBase< DerivedV > & v, const Scalar & alpha)
{
   typedef internal::blas_traits<DerivedU> UBlasTraits;
   typedef typename UBlasTraits::DirectLinearAccessType ActualUType;
   typedef internal::remove_all_t<ActualUType> ActualUType_;
   internal::add_const_on_value_type_t<ActualUType> actualU = UBlasTraits::extract(u.derived());
   typedef internal::blas_traits<DerivedV> VBlasTraits;
   typedef typename VBlasTraits::DirectLinearAccessType ActualVType;
   typedef internal::remove_all_t<ActualVType> ActualVType_;
   internal::add_const_on_value_type_t<ActualVType> actualV = VBlasTraits::extract(v.derived());
   // If MatrixType is row major, then we use the routine for lower triangular in the upper triangular case and
   // vice versa, and take the complex conjugate of all coefficients and vector entries.
   enum { IsRowMajor = (internal::traits<MatrixType>::Flags & RowMajorBit) ? 1 : 0 };
   Scalar actualAlpha = alpha * UBlasTraits::extractScalarFactor(u.derived()) *
                        numext::conj(VBlasTraits::extractScalarFactor(v.derived()));
   if (IsRowMajor) actualAlpha = numext::conj(actualAlpha);
   typedef internal::remove_all_t<
       typename internal::conj_expr_if<int(IsRowMajor) ^ int(UBlasTraits::NeedToConjugate), ActualUType_>::type>
       UType;
   typedef internal::remove_all_t<
       typename internal::conj_expr_if<int(IsRowMajor) ^ int(VBlasTraits::NeedToConjugate), ActualVType_>::type>
       VType;
   internal::selfadjoint_rank2_update_selector<Scalar, Index, UType, VType,
                                               (IsRowMajor ? int(UpLo == Upper ? Lower : Upper)
                                                           : UpLo)>::run(_expression().const_cast_derived().data(),
                                                                         _expression().outerStride(), UType(actualU),
                                                                         VType(actualV), actualAlpha);
   return *this;
 }
References alpha, conj(), int(), Eigen::Lower, Eigen::RowMajorBit, Eigen::run(), compute_granudrum_aor::type, Eigen::Upper, and v.
rankUpdate() [2/4]
template<typename MatrixType_ , unsigned int UpLo> template<typename DerivedU , typename DerivedV > EIGEN_DEVICE_FUNC SelfAdjointView& Eigen::SelfAdjointView< MatrixType_, UpLo >::rankUpdate (const MatrixBase< DerivedU > & u, const MatrixBase< DerivedV > & v, const Scalar & alpha = Scalar(1))
Perform a symmetric rank 2 update of the selfadjoint matrix *this: \(this = this + \alpha u v^* + conj(\alpha) v u^* \)
Returns
a reference to *this
The vectors u and v must be column vectors, however they can be a adjoint expression without any overhead. Only the meaningful triangular part of the matrix is updated, the rest is left unchanged.
See also
rankUpdate(const MatrixBase<DerivedU>&, Scalar)
rankUpdate() [3/4]
template<typename MatrixType_ , unsigned int UpLo> template<typename DerivedU > EIGEN_DEVICE_FUNC SelfAdjointView<MatrixType, UpLo>& Eigen::SelfAdjointView< MatrixType_, UpLo >::rankUpdate (const MatrixBase< DerivedU > & u, const Scalar & alpha)
{
   selfadjoint_product_selector<MatrixType, DerivedU, UpLo>::run(_expression().const_cast_derived(), u.derived(), alpha);
   return *this;
 }
References alpha, and run().
rankUpdate() [4/4]
template<typename MatrixType_ , unsigned int UpLo> template<typename DerivedU > EIGEN_DEVICE_FUNC SelfAdjointView& Eigen::SelfAdjointView< MatrixType_, UpLo >::rankUpdate (const MatrixBase< DerivedU > & u, const Scalar & alpha = Scalar(1))
Perform a symmetric rank K update of the selfadjoint matrix *this: \(this = this + \alpha (u u^*) \) where u is a vector or matrix.
Returns
a reference to *this
Note that to perform \(this = this + \alpha (u^* u) \) you can simply call this function with u.adjoint().
See also
rankUpdate(const MatrixBase<DerivedU>&, const MatrixBase<DerivedV>&, Scalar)
rows()
template<typename MatrixType_ , unsigned int UpLo> EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index Eigen::SelfAdjointView< MatrixType_, UpLo >::rows () const inline
 { return m_matrix.rows(); }
References Eigen::SelfAdjointView< MatrixType_, UpLo >::m_matrix.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
transpose() [1/2]
template<typename MatrixType_ , unsigned int UpLo> EIGEN_DEVICE_FUNC const ConstTransposeReturnType Eigen::SelfAdjointView< MatrixType_, UpLo >::transpose () const inline
See also
MatrixBase::transpose() const
{
     return ConstTransposeReturnType(m_matrix.transpose());
   }
References Eigen::SelfAdjointView< MatrixType_, UpLo >::m_matrix.
transpose() [2/2]
template<typename MatrixType_ , unsigned int UpLo> template<class Dummy = int> EIGEN_DEVICE_FUNC TransposeReturnType Eigen::SelfAdjointView< MatrixType_, UpLo >::transpose (std::enable_if_t< Eigen::internal::is_lvalue< MatrixType >::value, Dummy * > = nullptr) inline
See also
MatrixBase::transpose()
{
     typename MatrixType::TransposeReturnType tmp(m_matrix);
     return TransposeReturnType(tmp);
   }
References Eigen::SelfAdjointView< MatrixType_, UpLo >::m_matrix, and tmp.
triangularView()
template<typename MatrixType_ , unsigned int UpLo> template<unsigned int TriMode> EIGEN_DEVICE_FUNC std::conditional_t<(TriMode & (Upper | Lower)) == (UpLo & (Upper | Lower)), TriangularView<MatrixType, TriMode>, TriangularView<typename MatrixType::AdjointReturnType, TriMode> > Eigen::SelfAdjointView< MatrixType_, UpLo >::triangularView () const inline
Returns
an expression of a triangular view extracted from the current selfadjoint view of a given triangular part
The parameter TriMode can have the following values: Upper, StrictlyUpper, UnitUpper, Lower, StrictlyLower, UnitLower.
If TriMode references the same triangular part than *this, then this method simply return a TriangularView of the nested expression, otherwise, the nested expression is first transposed, thus returning a TriangularView<Transpose<MatrixType>> object.
See also
MatrixBase::triangularView(), class TriangularView
{
     std::conditional_t<(TriMode & (Upper | Lower)) == (UpLo & (Upper | Lower)), MatrixType&,
                        typename MatrixType::ConstTransposeReturnType>
         tmp1(m_matrix);
     std::conditional_t<(TriMode & (Upper | Lower)) == (UpLo & (Upper | Lower)), MatrixType&,
                        typename MatrixType::AdjointReturnType>
         tmp2(tmp1);
     return std::conditional_t<(TriMode & (Upper | Lower)) == (UpLo & (Upper | Lower)),
                               TriangularView<MatrixType, TriMode>,
                               TriangularView<typename MatrixType::AdjointReturnType, TriMode> >(tmp2);
   }
References Eigen::Lower, Eigen::SelfAdjointView< MatrixType_, UpLo >::m_matrix, and Eigen::Upper.
Friends And Related Function Documentation
operator* [1/2]
template<typename MatrixType_ , unsigned int UpLo> template<typename OtherDerived > EIGEN_DEVICE_FUNC const Product<OtherDerived, SelfAdjointView> operator* (const MatrixBase< OtherDerived > & lhs, const SelfAdjointView< MatrixType_, UpLo > & rhs) friend
Efficient vector/matrix times triangular matrix product
{
     return Product<OtherDerived, SelfAdjointView>(lhs.derived(), rhs);
   }
operator* [2/2]
template<typename MatrixType_ , unsigned int UpLo> EIGEN_DEVICE_FUNC const SelfAdjointView<const EIGEN_SCALAR_BINARYOP_EXPR_RETURN_TYPE(Scalar, MatrixType, product), UpLo> operator* (const Scalar & s, const SelfAdjointView< MatrixType_, UpLo > & mat) friend
{
     return (s * mat.nestedExpression()).template selfadjointView<UpLo>();
   }
Member Data Documentation
m_matrix
template<typename MatrixType_ , unsigned int UpLo> MatrixTypeNested Eigen::SelfAdjointView< MatrixType_, UpLo >::m_matrix protected
Referenced by Eigen::SelfAdjointView< MatrixType_, UpLo >::_expression(), Eigen::SelfAdjointView< MatrixType_, UpLo >::adjoint(), Eigen::SelfAdjointView< MatrixType_, UpLo >::coeff(), Eigen::SelfAdjointView< MatrixType_, UpLo >::coeffRef(), Eigen::SelfAdjointView< MatrixType_, UpLo >::cols(), Eigen::SelfAdjointView< MatrixType_, UpLo >::conjugate(), Eigen::SelfAdjointView< MatrixType_, UpLo >::conjugateIf(), Eigen::SelfAdjointView< MatrixType_, UpLo >::diagonal(), Eigen::SelfAdjointView< MatrixType_, UpLo >::innerStride(), Eigen::SelfAdjointView< MatrixType_, UpLo >::nestedExpression(), Eigen::SelfAdjointView< MatrixType_, UpLo >::outerStride(), Eigen::SelfAdjointView< MatrixType_, UpLo >::rows(), Eigen::SelfAdjointView< MatrixType_, UpLo >::transpose(), and Eigen::SelfAdjointView< MatrixType_, UpLo >::triangularView().
The documentation for this class was generated from the following files:
SelfAdjointView.h
LDLT.h
LLT.h
SelfadjointProduct.h
SelfadjointRank2Update.h
MatrixBaseEigenvalues.h