MercuryDPM: adaptive_driven_cavity.cc File Reference
demo_drivers/navier_stokes/navier_stokes_with_singularity/adaptive_driven_cavity.cc File Reference
#include "generic.h"
#include "navier_stokes.h"
#include "meshes/rectangular_quadmesh.h"
#include "finite_re_perturbation.h"
Classes
class RefineableDrivenCavityProblem< ELEMENT >
Namespaces
Global_Physical_Variables
Global variables.
Functions
int main (int argc, char *argv[])
Driver for RefineableDrivenCavity test problem.
Variables
double Global_Physical_Variables::Max_permitted_error =-1.0
double Global_Physical_Variables::Min_permitted_error =-1.0
Function Documentation
main()
int main (int argc , char * argv[])
Driver for RefineableDrivenCavity test problem.
 {
  // Allow indefinite refinement without complaints about near singular
  // Jacobian
  FiniteElement::Tolerance_for_singular_jacobian=0.0;
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Reynolds number
  CommandLineArgs::specify_command_line_flag("--re",
                                             &Global_Physical_Variables::Re);
  // Max error
  CommandLineArgs::specify_command_line_flag(
   "--max_permitted_error",
   &Global_Physical_Variables::Max_permitted_error);
  // Min error
  CommandLineArgs::specify_command_line_flag(
   "--min_permitted_error",
   &Global_Physical_Variables::Min_permitted_error);
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  // Set output directory
  DocInfo doc_info;
  doc_info.set_directory("RESLT");
  // Set max. number of black-box adaptation
  unsigned max_adapt=1;
  //Build problem
  RefineableDrivenCavityProblem<RefineableQTaylorHoodElement<2> > problem;
  unsigned n_adapt=10;
  for (unsigned i=0;i<n_adapt;i++)
   {
    // Solve the problem with automatic adaptation
    problem.newton_solve(max_adapt);
    //Output solution
    problem.doc_solution(doc_info);
    // Step number
    doc_info.number()++;
   }
 } // end_of_main
References oomph::CommandLineArgs::doc_specified_flags(), i, Global_Physical_Variables::Max_permitted_error, Global_Physical_Variables::Min_permitted_error, oomph::DocInfo::number(), oomph::CommandLineArgs::parse_and_assign(), problem, Global_Physical_Variables::Re, oomph::DocInfo::set_directory(), Flag_definition::setup(), and oomph::CommandLineArgs::specify_command_line_flag().