MercuryDPM: unstructured_adaptive_ALE.cc File Reference
unstructured_adaptive_ALE.cc File Reference
#include <fenv.h>
#include "generic.h"
#include "navier_stokes.h"
#include "solid.h"
#include "constitutive.h"
#include "rigid_body.h"
#include "meshes/triangle_mesh.h"
Classes
class oomph::MyTaylorHoodElement< DIM >
Overload TaylorHood element to modify output.
class oomph::FaceGeometry< MyTaylorHoodElement >
class UnstructuredFluidProblem< ELEMENT >
Unstructured Navier-Stokes ALE Problem.
Namespaces
oomph
DRAIG: Change all instances of (SPATIAL_DIM) to (DIM-1).
oomph::Problem_Parameter
Namespace for Problem Parameter.
Functions
int main (int argc, char **argv)
Driver code for moving block problem.
Variables
double oomph::Problem_Parameter::Block_x_velocity =0.5
Block velocity.
double oomph::Problem_Parameter::Block_y_velocity =0.3
Block velocity.
double oomph::Problem_Parameter::Block_rotation_velocity =1.0
Block velocity.
Vector< Data * > oomph::Problem_Parameter::Centre_displacement_data_pt
DocInfo oomph::Problem_Parameter::Doc_info
Doc info.
double oomph::Problem_Parameter::Lambda_sq =0.0
Function Documentation
main()
int main (int argc , char ** argv)
Driver code for moving block problem.
 {
  // feenableexcept(FE_INVALID | FE_DIVBYZERO | FE_OVERFLOW | FE_UNDERFLOW);
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Define possible command line arguments and parse the ones that
  // were actually specified
  // Validation?
  CommandLineArgs::specify_command_line_flag("--validation");
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  // Create generalised Hookean constitutive equations
  Problem_Parameter::Constitutive_law_pt =
   new GeneralisedHookean(&Problem_Parameter::Nu);
  // Open trace file
  Problem_Parameter::Trace_file.open("RESLT/trace.dat");
  // Open norm file
  Problem_Parameter::Norm_file.open("RESLT/norm.dat");
  // Create problem in initial configuration
  UnstructuredFluidProblem<ProjectableTaylorHoodElement<MyTaylorHoodElement> >
   problem;
  // Initialise timestepper
  double dt=0.025;
  problem.initialise_dt(dt);
  // Perform impulsive start
  problem.assign_initial_values_impulsive();
  // Output initial conditions
  problem.doc_solution();
  // Solve problem a few times on given mesh
  unsigned nstep=3;
  for (unsigned i=0;i<nstep;i++)
   {
    // Solve the problem
    problem.unsteady_newton_solve(dt);
    problem.doc_solution();
   }
  // Now do a couple of adaptations
  unsigned ncycle=100;
  if (CommandLineArgs::command_line_flag_has_been_set("--validation"))
   {
    ncycle=1;
    oomph_info << "Only doing one cycle during validation\n";
   }
  for (unsigned j=0;j<ncycle;j++)
   {
    // Adapt
    problem.adapt();
    //Solve problem a few times
    for (unsigned i=0;i<nstep;i++)
     {
      // Solve the problem
      problem.unsteady_newton_solve(dt);
      // Build the label for doc
      std::stringstream label;
      label << "Cycle " <<j << " Step "<< i;
      problem.doc_solution(label.str());
     }
   }
 } //End of main
References oomph::CommandLineArgs::command_line_flag_has_been_set(), Problem_Parameter::Constitutive_law_pt, oomph::CommandLineArgs::doc_specified_flags(), i, j, UniformPSDSelfTest::label, Problem_Parameter::Norm_file, Problem_Parameter::Nu, oomph::oomph_info, oomph::CommandLineArgs::parse_and_assign(), problem, Flag_definition::setup(), oomph::CommandLineArgs::specify_command_line_flag(), and Problem_Parameter::Trace_file.