MercuryDPM: Leaflet Class Reference
Leaflet Class Reference
Public Member Functions
Leaflet (const double &length, const double &d_x, const double &d_y, const double &x_0, const double &period, Time *time_pt)
virtual ~Leaflet ()
Destructor – emtpy.
void position (const unsigned &t, const Vector< double > &xi, Vector< double > &r) const
void position (const Vector< double > &xi, Vector< double > &r) const
Steady version: Get current shape.
unsigned ngeom_data () const
Number of geometric Data in GeomObject: None.
double length ()
Length of the leaflet.
double & d_x ()
Amplitude of horizontal tip displacement.
double d_y ()
Amplitude of vertical tip displacement.
double x_0 ()
x-coordinate of leaflet origin
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual Data * geom_data_pt (const unsigned &j)
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition_dt (const Vector< double > &zeta, const unsigned &j, Vector< double > &drdt)
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
virtual void locate_zeta (const Vector< double > &zeta, GeomObject *&sub_geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
Private Attributes
double Length
Length in terms of Lagrangian coordinates.
double D_x
Horizontal displacement of tip.
double D_y
Vertical displacement of tip.
double X_0
Origin.
double T
Period of the oscillations.
Time * Time_pt
Pointer to the global time object.
Additional Inherited Members
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Detailed Description
GeomObject representing a vertical leaflet that performs bending and stretching oscillations.
Constructor & Destructor Documentation
Leaflet()
Leaflet::Leaflet (const double & length, const double & d_x, const double & d_y, const double & x_0, const double & period, Time * time_pt) inline
Constructor: Pass length (in Lagrangian coordinates), the amplitude of the horizontal and vertical deflection of the tip, the x-coordinate of the origin and the period of the oscillation. Passes the number of Lagrangian and Eulerian coordinates to the constructor of the GeomObject base class.
   : GeomObject(1,2), Length(length), D_x(d_x), D_y(d_y), X_0(x_0),
    T(period),Time_pt(time_pt) {}
~Leaflet()
virtual Leaflet::~Leaflet () inline virtual
Destructor – emtpy.
 {}
Member Function Documentation
d_x()
double& Leaflet::d_x () inline
Amplitude of horizontal tip displacement.
 {return D_x;}
d_y()
double Leaflet::d_y () inline
Amplitude of vertical tip displacement.
 {return D_y;}
length()
double Leaflet::length () inline
Length of the leaflet.
 { return Length; }
References Global_Physical_Variables::Length.
ngeom_data()
unsigned Leaflet::ngeom_data () const inline virtual
Number of geometric Data in GeomObject: None.
Reimplemented from oomph::GeomObject.
 {return 0;}
position() [1/2]
void Leaflet::position (const unsigned & t, const Vector< double > & xi, Vector< double > & r) const inline virtual
Position vector, r, to the point identified by
its 1D Lagrangian coordinate, xi (passed as a 1D Vector) at discrete time level t (t=0: present; t>0: previous).
Reimplemented from oomph::GeomObject.
   {
     using namespace MathematicalConstants;
    //Position
     r[0] =  X_0 + D_x*xi[0]*xi[0]/Length/Length*sin(2.0*Pi*Time_pt->time(t)/T);
     r[1] = xi[0]*(1.0+D_y/Length*0.5*(1.0-cos(4.0*Pi*Time_pt->time(t)/T)));
   }
References cos(), Global_Physical_Variables::Length, BiharmonicTestFunctions2::Pi, UniformPSDSelfTest::r, sin(), plotPSD::t, oomph::Time::time(), Flag_definition::Time_pt, and TanhSolnForPoisson::X_0.
position() [2/2]
void Leaflet::position (const Vector< double > & xi, Vector< double > & r) const inline virtual
Steady version: Get current shape.
Implements oomph::GeomObject.
   {
    position(0,xi,r);
   }
References UniformPSDSelfTest::r.
x_0()
double Leaflet::x_0 () inline
x-coordinate of leaflet origin
 {return X_0;}
References TanhSolnForPoisson::X_0.
Member Data Documentation
D_x
double Leaflet::D_x private
Horizontal displacement of tip.
D_y
double Leaflet::D_y private
Vertical displacement of tip.
Length
double Leaflet::Length private
Length in terms of Lagrangian coordinates.
T
double Leaflet::T private
Period of the oscillations.
Time_pt
Time* Leaflet::Time_pt private
Pointer to the global time object.
X_0
double Leaflet::X_0 private
Origin.
The documentation for this class was generated from the following file:
channel_with_leaflet.cc