MercuryDPM: oomph::TetgenMesh< ELEMENT > Class Template Reference
oomph::TetgenMesh< ELEMENT > Class Template Reference
#include <tetgen_mesh.template.h>
Public Member Functions
TetgenMesh ()
Empty constructor.
TetgenMesh (const std::string &node_file_name, const std::string &element_file_name, const std::string &face_file_name, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper, const bool &use_attributes=false)
Constructor with the input files.
TetgenMesh (tetgenio &tetgen_data, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper, const bool &use_attributes=false)
Constructor with tetgenio data structure.
TetgenMesh (const std::string &node_file_name, const std::string &element_file_name, const std::string &face_file_name, const bool &split_corner_elements, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper, const bool &use_attributes=false)
TetgenMesh (tetgenio &tetgen_data, const bool &split_corner_elements, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper, const bool &use_attributes=false)
TetgenMesh (TetMeshFacetedClosedSurface *const &outer_boundary_pt, Vector< TetMeshFacetedSurface * > &internal_surface_pt, const double &element_volume, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper, const bool &use_attributes=false, const bool &split_corner_elements=false, Vector< double > *const &target_element_volume_in_region_pt=nullptr)
void build_tetgenio (TetMeshFacetedSurface *const &outer_boundary_pt, Vector< TetMeshFacetedSurface * > &internal_surface_pt, Vector< double > *const &target_element_volume_in_region_pt, tetgenio &tetgen_io)
Build tetgenio object from the TetMeshFacetedSurfaces.
~TetgenMesh ()
Empty destructor.
void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
bool tetgenio_exists () const
Boolen defining whether tetgenio object has been built or not.
tetgenio *& tetgenio_pt ()
Access to the triangulateio representation of the mesh.
void set_deep_copy_tetgenio_pt (tetgenio *const &tetgenio_pt)
Set the tetgen pointer by a deep copy.
void deep_copy_of_tetgenio (tetgenio *const &input_pt, tetgenio *&output_pt)
Public Member Functions inherited from oomph::TetMeshBase
TetMeshBase ()
Constructor.
TetMeshBase (const TetMeshBase &node)=delete
Broken copy constructor.
void operator= (const TetMeshBase &)=delete
Broken assignment operator.
virtual ~TetMeshBase ()
Destructor (empty)
void assess_mesh_quality (std::ofstream &some_file)
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b)
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b, const bool &switch_normal)
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b, const bool &switch_normal, std::ofstream &outfile)
template<class ELEMENT >
void setup_boundary_coordinates (const unsigned &b, std::ofstream &outfile)
unsigned nboundary_element_in_region (const unsigned &b, const unsigned &r) const
Return the number of elements adjacent to boundary b in region r.
FiniteElement * boundary_element_in_region_pt (const unsigned &b, const unsigned &r, const unsigned &e) const
Return pointer to the e-th element adjacent to boundary b in region r.
int face_index_at_boundary_in_region (const unsigned &b, const unsigned &r, const unsigned &e) const
Return face index of the e-th element adjacent to boundary b in region r.
unsigned nregion ()
Return the number of regions specified by attributes.
unsigned nregion_element (const unsigned &r)
Return the number of elements in region r.
double region_attribute (const unsigned &i)
FiniteElement * region_element_pt (const unsigned &r, const unsigned &e)
Return the e-th element in the r-th region.
template<class ELEMENT >
void snap_to_quadratic_surface (const Vector< unsigned > &boundary_id, const std::string &quadratic_surface_file_name, const bool &switch_normal, DocInfo &doc_info)
template<class ELEMENT >
void snap_to_quadratic_surface (const Vector< unsigned > &boundary_id, const std::string &quadratic_surface_file_name, const bool &switch_normal)
void snap_nodes_onto_geometric_objects ()
template<class ELEMENT >
void split_elements_in_corners (TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
void setup_boundary_element_info ()
void setup_boundary_element_info (std::ostream &outfile)
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void node_update (const bool &update_all_solid_nodes=false)
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Protected Member Functions
void build_from_scaffold (TimeStepper *time_stepper_pt, const bool &use_attributes)
Build mesh from scaffold.
void setup_reverse_lookup_schemes_for_faceted_surface (TetMeshFacetedSurface *const &faceted_surface_pt)
Function to setup the reverse look-up schemes.
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Protected Attributes
TetgenScaffoldMesh * Tmp_mesh_pt
Temporary scaffold mesh.
bool Tetgenio_exists
tetgenio * Tetgenio_pt
Tetgen representation of mesh.
bool Use_attributes
Protected Attributes inherited from oomph::TetMeshBase
Vector< Vector< FiniteElement * > > Region_element_pt
Vector< double > Region_attribute
Vector< std::map< unsigned, Vector< FiniteElement * > > > Boundary_region_element_pt
Storage for elements adjacent to a boundary in a particular region.
Vector< std::map< unsigned, Vector< int > > > Face_index_region_at_boundary
TetMeshFacetedClosedSurface * Outer_boundary_pt
Faceted surface that defines outer boundaries.
Vector< TetMeshFacetedSurface * > Internal_surface_pt
Vector to faceted surfaces that define internal boundaries.
std::map< unsigned, TetMeshFacetedSurface * > Tet_mesh_faceted_surface_pt
std::map< unsigned, TetMeshFacet * > Tet_mesh_facet_pt
std::map< unsigned, Vector< Vector< double > > > Triangular_facet_vertex_boundary_coordinate
TimeStepper * Time_stepper_pt
Timestepper used to build nodes.
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::TetMeshBase
static double Tolerance_for_boundary_finding = 1.0e-5
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Detailed Description
template<class ELEMENT>
class oomph::TetgenMesh< ELEMENT >
Unstructured tet mesh based on output from Tetgen: http://wias-berlin.de/software/tetgen/
Constructor & Destructor Documentation
TetgenMesh() [1/6]
template<class ELEMENT > oomph::TetgenMesh< ELEMENT >::TetgenMesh () inline
Empty constructor.
     {
       // Mesh can only be built with 3D Telements.
       MeshChecker::assert_geometric_element<TElementGeometricBase, ELEMENT>(3);
     }
TetgenMesh() [2/6]
template<class ELEMENT > oomph::TetgenMesh< ELEMENT >::TetgenMesh (const std::string & node_file_name, const std::string & element_file_name, const std::string & face_file_name, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper, const bool & use_attributes = false) inline
Constructor with the input files.
       : Tetgenio_exists(false), Tetgenio_pt(nullptr)
     {
       // Mesh can only be built with 3D Telements.
       MeshChecker::assert_geometric_element<TElementGeometricBase, ELEMENT>(3);
       // Store the attributes
       Use_attributes = use_attributes;
       // Store timestepper used to build elements
       Time_stepper_pt = time_stepper_pt;
       // Build scaffold
       Tmp_mesh_pt = new TetgenScaffoldMesh(
         node_file_name, element_file_name, face_file_name);
       // Convert mesh from scaffold to actual mesh
       build_from_scaffold(time_stepper_pt, use_attributes);
       // Kill the scaffold
       delete Tmp_mesh_pt;
       Tmp_mesh_pt = 0;
       // Setup boundary coordinates
       unsigned nb = nboundary();
       for (unsigned b = 0; b < nb; b++)
       {
         bool switch_normal = false;
         setup_boundary_coordinates<ELEMENT>(b, switch_normal);
       }
     }
References b, oomph::TetgenMesh< ELEMENT >::build_from_scaffold(), nb, oomph::Mesh::nboundary(), oomph::TetMeshBase::Time_stepper_pt, oomph::TetgenMesh< ELEMENT >::Tmp_mesh_pt, and oomph::TetgenMesh< ELEMENT >::Use_attributes.
TetgenMesh() [3/6]
template<class ELEMENT > oomph::TetgenMesh< ELEMENT >::TetgenMesh (tetgenio & tetgen_data, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper, const bool & use_attributes = false) inline
Constructor with tetgenio data structure.
     {
       // Mesh can only be built with 3D Telements.
       MeshChecker::assert_geometric_element<TElementGeometricBase, ELEMENT>(3);
       // Store the attributes
       Use_attributes = use_attributes;
       // Store timestepper used to build elements
       Time_stepper_pt = time_stepper_pt;
       // We do not have a tetgenio representation
       Tetgenio_exists = false;
       Tetgenio_pt = 0;
       // Build scaffold
       Tmp_mesh_pt = new TetgenScaffoldMesh(tetgen_data);
       // Convert mesh from scaffold to actual mesh
       build_from_scaffold(time_stepper_pt, use_attributes);
       // Kill the scaffold
       delete Tmp_mesh_pt;
       Tmp_mesh_pt = 0;
       // Setup boundary coordinates
       unsigned nb = nboundary();
       for (unsigned b = 0; b < nb; b++)
       {
         bool switch_normal = false;
         setup_boundary_coordinates<ELEMENT>(b, switch_normal);
       }
     }
References b, oomph::TetgenMesh< ELEMENT >::build_from_scaffold(), nb, oomph::Mesh::nboundary(), oomph::TetgenMesh< ELEMENT >::Tetgenio_exists, oomph::TetgenMesh< ELEMENT >::Tetgenio_pt, oomph::TetMeshBase::Time_stepper_pt, oomph::TetgenMesh< ELEMENT >::Tmp_mesh_pt, and oomph::TetgenMesh< ELEMENT >::Use_attributes.
TetgenMesh() [4/6]
template<class ELEMENT > oomph::TetgenMesh< ELEMENT >::TetgenMesh (const std::string & node_file_name, const std::string & element_file_name, const std::string & face_file_name, const bool & split_corner_elements, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper, const bool & use_attributes = false) inline
Constructor with the input files. Setting the boolean flag to true splits "corner" elements, i.e. elements that that have at least three faces on a domain boundary. The relevant elements are split without introducing hanging nodes so the sons have a "worse" shape than their fathers. However, this step avoids otherwise-hard-to-diagnose problems in fluids problems where the application of boundary conditions at such "corner" elements can overconstrain the solution.
     {
       // Mesh can only be built with 3D Telements.
       MeshChecker::assert_geometric_element<TElementGeometricBase, ELEMENT>(3);
       // Store the attributes
       Use_attributes = use_attributes;
       // Store timestepper used to build elements
       Time_stepper_pt = time_stepper_pt;
       // We do not have a tetgenio representation
       this->Tetgenio_exists = false;
       this->Tetgenio_pt = 0;
       // Build scaffold
       Tmp_mesh_pt = new TetgenScaffoldMesh(
         node_file_name, element_file_name, face_file_name);
       // Convert mesh from scaffold to actual mesh
       build_from_scaffold(time_stepper_pt, use_attributes);
       // Kill the scaffold
       delete Tmp_mesh_pt;
       Tmp_mesh_pt = 0;
       // Split corner elements
       if (split_corner_elements)
       {
         split_elements_in_corners<ELEMENT>();
       }
       // Setup boundary coordinates
       unsigned nb = nboundary();
       for (unsigned b = 0; b < nb; b++)
       {
         bool switch_normal = false;
         setup_boundary_coordinates<ELEMENT>(b, switch_normal);
       }
     }
References b, oomph::TetgenMesh< ELEMENT >::build_from_scaffold(), nb, oomph::Mesh::nboundary(), oomph::TetgenMesh< ELEMENT >::Tetgenio_exists, oomph::TetgenMesh< ELEMENT >::Tetgenio_pt, oomph::TetMeshBase::Time_stepper_pt, oomph::TetgenMesh< ELEMENT >::Tmp_mesh_pt, and oomph::TetgenMesh< ELEMENT >::Use_attributes.
TetgenMesh() [5/6]
template<class ELEMENT > oomph::TetgenMesh< ELEMENT >::TetgenMesh (tetgenio & tetgen_data, const bool & split_corner_elements, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper, const bool & use_attributes = false) inline
Constructor with tetgen data structure Setting the boolean flag to true splits "corner" elements, i.e. elements that that have at least three faces on a domain boundary. The relevant elements are split without introducing hanging nodes so the sons have a "worse" shape than their fathers. However, this step avoids otherwise-hard-to-diagnose problems in fluids problems where the application of boundary conditions at such "corner" elements can overconstrain the solution.
     {
       // Mesh can only be built with 3D Telements.
       MeshChecker::assert_geometric_element<TElementGeometricBase, ELEMENT>(3);
       // Store the attributes
       Use_attributes = use_attributes;
       // Store timestepper used to build elements
       Time_stepper_pt = time_stepper_pt;
       // We do not have a tetgenio representation
       this->Tetgenio_exists = false;
       this->Tetgenio_pt = nullptr;
       // Build scaffold
       Tmp_mesh_pt = new TetgenScaffoldMesh(tetgen_data);
       // Convert mesh from scaffold to actual mesh
       build_from_scaffold(time_stepper_pt, use_attributes);
       // Kill the scaffold
       delete Tmp_mesh_pt;
       Tmp_mesh_pt = nullptr;
       // Split corner elements
       if (split_corner_elements)
       {
         split_elements_in_corners<ELEMENT>();
       }
       // Setup boundary coordinates
       unsigned nb = nboundary();
       for (unsigned b = 0; b < nb; b++)
       {
         bool switch_normal = false;
         setup_boundary_coordinates<ELEMENT>(b, switch_normal);
       }
     }
References b, oomph::TetgenMesh< ELEMENT >::build_from_scaffold(), nb, oomph::Mesh::nboundary(), oomph::TetgenMesh< ELEMENT >::Tetgenio_exists, oomph::TetgenMesh< ELEMENT >::Tetgenio_pt, oomph::TetMeshBase::Time_stepper_pt, oomph::TetgenMesh< ELEMENT >::Tmp_mesh_pt, and oomph::TetgenMesh< ELEMENT >::Use_attributes.
TetgenMesh() [6/6]
template<class ELEMENT > oomph::TetgenMesh< ELEMENT >::TetgenMesh (TetMeshFacetedClosedSurface *const & outer_boundary_pt, Vector< TetMeshFacetedSurface * > & internal_surface_pt, const double & element_volume, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper, const bool & use_attributes = false, const bool & split_corner_elements = false, Vector< double > *const & target_element_volume_in_region_pt = nullptr) inline
Build mesh, based on a TetgenMeshFactedClosedSurface that specifies the outer boundary of the domain and any number of internal boundaries, specified by TetMeshFacetedSurfaces. Also specify target size for uniform element size. Optionally specify the target element volume in each region.
     {
       // Mesh can only be built with 3D Telements.
       MeshChecker::assert_geometric_element<TElementGeometricBase, ELEMENT>(3);
       // Store the attributes
       Use_attributes = use_attributes;
       // Store timestepper used to build elements
       Time_stepper_pt = time_stepper_pt;
       // Copy across
       Outer_boundary_pt = outer_boundary_pt;
       // Setup the reverse lookup scheme
       this->setup_reverse_lookup_schemes_for_faceted_surface(Outer_boundary_pt);
       // Store the internal boundary
       Internal_surface_pt = internal_surface_pt;
       // Setup the reverse lookup schemes
       {
         unsigned n = this->Internal_surface_pt.size();
         for (unsigned i = 0; i < n; i++)
         {
           this->setup_reverse_lookup_schemes_for_faceted_surface(
             Internal_surface_pt[i]);
         }
       }
       // Tetgen data structure for the input and output
       tetgenio in;
       this->build_tetgenio(outer_boundary_pt,
                            internal_surface_pt,
                            target_element_volume_in_region_pt,
                            in);
       // Now tetrahedralise
       // The 'p' switch reads a Piecewise Linear Complex, which generates a
       // Delaunay tetrahedralization of the input. The 'q' switch prevents
       // generation of high-aspect ratio tets (slivers), with the trailing float
       // indicating the maximum allowed aspect ratio (default is 2.0). The 'a'
       // switch without  subsequent floating-point number switches on the
       // specific element volume constraints for particular regions (the 5th
       // index in the tetgenio.regionlist array). The 'A' enables region
       // attributes, and the second 'a' switch with the subsequent float sets
       // the global (non-region-specific) element volume constraint.
       std::stringstream input_string;
       input_string << "pq2.0aAa" << element_volume;
       // input_string << "Vpq1.414Aa" << element_volume;
       // << "Q"; // Q for quiet!
       // << "V"; // V for verbose incl. quality output!
       // If any of the boundaries should not be split add the "Y" flag
       bool can_boundaries_be_split =
         outer_boundary_pt->boundaries_can_be_split_in_tetgen();
       {
         unsigned n_internal = internal_surface_pt.size();
         for (unsigned i = 0; i < n_internal; i++)
         {
           can_boundaries_be_split &=
             internal_surface_pt[i]->boundaries_can_be_split_in_tetgen();
         }
       }
       // If we can't split the boundaries add the flag
       if (can_boundaries_be_split == false)
       {
         input_string << "Y";
       }
       // Now convert to a C-style string
       char tetswitches[100];
       sprintf(tetswitches, "%s", input_string.str().c_str());
       // Make a new tetgen representation
       this->Tetgenio_exists = true;
       Tetgenio_pt = new tetgenio;
       tetrahedralize(tetswitches, &in, this->Tetgenio_pt);
       // Build scaffold
       Tmp_mesh_pt = new TetgenScaffoldMesh(*this->Tetgenio_pt);
       // If any of the objects are different regions then we need to use
       // the atributes
       bool regions_exist = false;
       {
         unsigned n_internal = internal_surface_pt.size();
         for (unsigned i = 0; i < n_internal; i++)
         {
           TetMeshFacetedClosedSurface* srf_pt =
             dynamic_cast<TetMeshFacetedClosedSurface*>(internal_surface_pt[i]);
           if (srf_pt != 0)
           {
             unsigned n_int_pts = srf_pt->ninternal_point_for_tetgen();
             for (unsigned j = 0; j < n_int_pts; j++)
             {
               regions_exist |=
                 srf_pt->internal_point_identifies_region_for_tetgen(j);
             }
           }
         }
       }
       // If there are regions, use the attributes
       if (regions_exist)
       {
         Use_attributes = true;
       }
       // Convert mesh from scaffold to actual mesh
       build_from_scaffold(time_stepper_pt, Use_attributes);
       // Kill the scaffold
       delete Tmp_mesh_pt;
       Tmp_mesh_pt = 0;
       // Split corner elements
       if (split_corner_elements)
       {
         split_elements_in_corners<ELEMENT>();
       }
       // Setup boundary coordinates
       unsigned nb = nboundary();
       for (unsigned b = 0; b < nb; b++)
       {
         bool switch_normal = false;
         setup_boundary_coordinates<ELEMENT>(b, switch_normal);
       }
       // Now snap onto geometric objects associated with triangular facets
       // (if any!)
       snap_nodes_onto_geometric_objects();
     }
References b, oomph::TetMeshFacetedSurface::boundaries_can_be_split_in_tetgen(), oomph::TetgenMesh< ELEMENT >::build_from_scaffold(), oomph::TetgenMesh< ELEMENT >::build_tetgenio(), i, oomph::TetMeshFacetedClosedSurface::internal_point_identifies_region_for_tetgen(), oomph::TetMeshBase::Internal_surface_pt, j, n, nb, oomph::Mesh::nboundary(), oomph::TetMeshFacetedClosedSurface::ninternal_point_for_tetgen(), oomph::TetMeshBase::Outer_boundary_pt, oomph::TetgenMesh< ELEMENT >::setup_reverse_lookup_schemes_for_faceted_surface(), oomph::TetMeshBase::snap_nodes_onto_geometric_objects(), oomph::TetgenMesh< ELEMENT >::Tetgenio_exists, oomph::TetgenMesh< ELEMENT >::Tetgenio_pt, tetrahedralize(), oomph::TetMeshBase::Time_stepper_pt, oomph::TetgenMesh< ELEMENT >::Tmp_mesh_pt, and oomph::TetgenMesh< ELEMENT >::Use_attributes.
~TetgenMesh()
template<class ELEMENT > oomph::TetgenMesh< ELEMENT >::~TetgenMesh () inline
Empty destructor.
     {
       if (Tetgenio_exists)
       {
         delete Tetgenio_pt;
       }
     }
References oomph::TetgenMesh< ELEMENT >::Tetgenio_exists, and oomph::TetgenMesh< ELEMENT >::Tetgenio_pt.
Member Function Documentation
build_from_scaffold()
template<class ELEMENT > void TetgenMesh::build_from_scaffold (TimeStepper * time_stepper_pt, const bool & use_attributes) protected
Build mesh from scaffold.
Build unstructured tet mesh based on output from scaffold.
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
   {
     // Mesh can only be built with 3D Telements.
     MeshChecker::assert_geometric_element<TElementGeometricBase, ELEMENT>(3);
     // Create space for elements
     unsigned nelem = Tmp_mesh_pt->nelement();
     Element_pt.resize(nelem);
     // Create space for nodes
     unsigned nnode_scaffold = Tmp_mesh_pt->nnode();
     Node_pt.resize(nnode_scaffold);
     // Set number of boundaries
     unsigned nbound = Tmp_mesh_pt->nboundary();
     set_nboundary(nbound);
     Boundary_element_pt.resize(nbound);
     Face_index_at_boundary.resize(nbound);
     // If we have different regions, then resize the region
     // information
     if (use_attributes)
     {
       Boundary_region_element_pt.resize(nbound);
       Face_index_region_at_boundary.resize(nbound);
     }
     // Build elements
     for (unsigned e = 0; e < nelem; e++)
     {
       Element_pt[e] = new ELEMENT;
     }
     // Number of nodes per element
     unsigned nnod_el = Tmp_mesh_pt->finite_element_pt(0)->nnode();
     // Setup map to check the (pseudo-)global node number
     // Nodes whose number is zero haven't been copied across
     // into the mesh yet.
     std::map<Node*, unsigned> global_number;
     unsigned global_count = 0;
     // Map of element attribute pairs
     std::map<double, Vector<FiniteElement*>> element_attribute_map;
     // Loop over elements in scaffold mesh, visit their nodes
     for (unsigned e = 0; e < nelem; e++)
     {
       // Loop over all nodes in element
       for (unsigned j = 0; j < nnod_el; j++)
       {
         // Pointer to node in the scaffold mesh
         Node* scaffold_node_pt = Tmp_mesh_pt->finite_element_pt(e)->node_pt(j);
         // Get the (pseudo-)global node number in scaffold mesh
         // (It's zero [=default] if not visited this one yet)
         unsigned j_global = global_number[scaffold_node_pt];
         // Haven't done this one yet
         if (j_global == 0)
         {
           // Get pointer to set of mesh boundaries that this
           // scaffold node occupies; NULL if the node is not on any boundary
           std::set<unsigned>* boundaries_pt;
           scaffold_node_pt->get_boundaries_pt(boundaries_pt);
           // Is it on boundaries?
           if (boundaries_pt != 0)
           {
             // Create new boundary node
             Node* new_node_pt =
               finite_element_pt(e)->construct_boundary_node(j, time_stepper_pt);
             // Give it a number (not necessarily the global node
             // number in the scaffold mesh -- we just need something
             // to keep track...)
             global_count++;
             global_number[scaffold_node_pt] = global_count;
             // Add to boundaries
             for (std::set<unsigned>::iterator it = boundaries_pt->begin();
                  it != boundaries_pt->end();
                  ++it)
             {
               add_boundary_node(*it, new_node_pt);
             }
           }
           // Build normal node
           else
           {
             // Create new normal node
             finite_element_pt(e)->construct_node(j, time_stepper_pt);
             // Give it a number (not necessarily the global node
             // number in the scaffold mesh -- we just need something
             // to keep track...)
             global_count++;
             global_number[scaffold_node_pt] = global_count;
           }
           // Copy new node, created using the NEW element's construct_node
           // function into global storage, using the same global
           // node number that we've just associated with the
           // corresponding node in the scaffold mesh
           Node_pt[global_count - 1] = finite_element_pt(e)->node_pt(j);
           // Assign coordinates
           Node_pt[global_count - 1]->x(0) = scaffold_node_pt->x(0);
           Node_pt[global_count - 1]->x(1) = scaffold_node_pt->x(1);
           Node_pt[global_count - 1]->x(2) = scaffold_node_pt->x(2);
         }
         // This one has already been done: Copy across
         else
         {
           finite_element_pt(e)->node_pt(j) = Node_pt[j_global - 1];
         }
       }
       // Store the attributes in the map
       if (use_attributes)
       {
         element_attribute_map[Tmp_mesh_pt->element_attribute(e)].push_back(
           finite_element_pt(e));
       }
     }
     // Now let's construct lists
     // Find the number of attributes
     if (use_attributes)
     {
       unsigned n_attribute = element_attribute_map.size();
       // There are n_attribute different regions
       Region_element_pt.resize(n_attribute);
       Region_attribute.resize(n_attribute);
       // Copy the vectors in the map over to our internal storage
       unsigned count = 0;
       for (std::map<double, Vector<FiniteElement*>>::iterator it =
              element_attribute_map.begin();
            it != element_attribute_map.end();
            ++it)
       {
         Region_attribute[count] = it->first;
         Region_element_pt[count] = it->second;
         ++count;
       }
     }
     // At this point we've created all the elements and
     // created their vertex nodes. Now we need to create
     // the additional (midside and internal) nodes!
     unsigned boundary_id;
     // Get number of nodes along element edge and dimension of element (3)
     // from first element
     unsigned n_node_1d = finite_element_pt(0)->nnode_1d();
     // At the moment we're only able to deal with nnode_1d=2 or 3.
     if ((n_node_1d != 2) && (n_node_1d != 3))
     {
       std::ostringstream error_message;
       error_message << "Mesh generation from tetgen currently only works\n";
       error_message << "for nnode_1d = 2 or 3. You're trying to use it\n";
       error_message << "for nnode_1d=" << n_node_1d << std::endl;
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
     // Spatial dimension of element = number of local coordinates
     unsigned dim = finite_element_pt(0)->dim();
     // Storage for the local coordinate of the new node
     Vector<double> s(dim);
     // Get number of nodes in the element from first element
     unsigned n_node = finite_element_pt(0)->nnode();
     // Storage for each global edge of the mesh
     unsigned n_global_edge = Tmp_mesh_pt->nglobal_edge();
     Vector<Vector<Node*>> nodes_on_global_edge(n_global_edge);
     // Storage for each global face of the mesh
     unsigned n_global_face = Tmp_mesh_pt->nglobal_face();
     Vector<Vector<Node*>> nodes_on_global_face(n_global_face);
     // Map storing the mid-side of an edge; edge identified by
     // pointers to vertex nodes in scaffold mesh
     // MapMatrix<Node*,Node*> central_edge_node_pt;
     // Node* edge_node1_pt=0;
     // Node* edge_node2_pt=0;
     // Map storing the mid point of a face; face identified by
     // set of pointers to vertex nodes in scaffold mesh
     // std::map<std::set<Node*>,Node*> central_face_node_pt;
     // std::set<Node*> face_nodes_pt;
     // Mapping of Tetgen faces to face nodes in the enriched element
     unsigned face_map[4] = {1, 0, 2, 3};
     // Storage for the faces shared by the edges
     const unsigned faces_on_edge[6][2] = {
       {0, 1}, {0, 2}, {1, 2}, {0, 3}, {2, 3}, {1, 3}};
     // Loop over all elements
     for (unsigned e = 0; e < nelem; e++)
     {
       // Cache pointers to the elements
       FiniteElement* const elem_pt = this->finite_element_pt(e);
       FiniteElement* const tmp_elem_pt = Tmp_mesh_pt->finite_element_pt(e);
       // The number of edge nodes is 4 + 6*(n_node1d-2)
       unsigned n_edge_node = 4 + 6 * (n_node_1d - 2);
       // Now loop over the edge nodes
       // assuming that the numbering scheme is the same as the triangles
       // which puts edge nodes in ascending order.
       // We don't have any higher than quadratic at the moment, so it's
       // a bit academic really.
       // Only bother if we actually have some edge nodes
       if (n_edge_node > 4)
       {
         // Start from node number 4
         unsigned n = 4;
         // Loop over the edges
         for (unsigned j = 0; j < 6; ++j)
         {
           // Find the global edge index
           unsigned edge_index = Tmp_mesh_pt->edge_index(e, j);
           // Use the intersection of the appropriate faces to determine
           // whether the boundaries on which an edge lies
           std::set<unsigned> edge_boundaries;
           for (unsigned i = 0; i < 2; ++i)
           {
             unsigned face_boundary_id =
               Tmp_mesh_pt->face_boundary(e, faces_on_edge[j][i]);
             if (face_boundary_id > 0)
             {
               edge_boundaries.insert(face_boundary_id);
             }
           }
           // If the nodes on the edge have not been allocated, construct them
           if (nodes_on_global_edge[edge_index].size() == 0)
           {
             // Now loop over the nodes on the edge
             for (unsigned j2 = 0; j2 < n_node_1d - 2; ++j2)
             {
               // Storage for the new node
               Node* new_node_pt = 0;
               // If the edge is on a boundary, determined from the
               // scaffold mesh, construct a boundary node
               // The use of the scaffold mesh's edge_boundary data structure
               // ensures that a boundary node is created, even if the faces of
               // the current element do not lie on boundaries
               if (Tmp_mesh_pt->edge_boundary(edge_index) == true)
               {
                 new_node_pt =
                   elem_pt->construct_boundary_node(n, time_stepper_pt);
                 // Add it to the boundaries in the set,
                 // remembering to subtract one to get to the oomph-lib numbering
                 // scheme
                 for (std::set<unsigned>::iterator it = edge_boundaries.begin();
                      it != edge_boundaries.end();
                      ++it)
                 {
                   this->add_boundary_node((*it) - 1, new_node_pt);
                 }
               }
               // Otherwise construct a normal node
               else
               {
                 new_node_pt = elem_pt->construct_node(n, time_stepper_pt);
               }
               // Find the local coordinates of the node
               elem_pt->local_coordinate_of_node(n, s);
               // Find the coordinates of the new node from the exiting and
               // fully-functional element in the scaffold mesh
               for (unsigned i = 0; i < dim; ++i)
               {
                 new_node_pt->x(i) = tmp_elem_pt->interpolated_x(s, i);
               }
               // Add the newly created node to the global node list
               Node_pt.push_back(new_node_pt);
               // Add to the edge index
               nodes_on_global_edge[edge_index].push_back(new_node_pt);
               // Increment the local node number
               ++n;
             } // end of loop over edge nodes
           }
           // Otherwise just set the pointers (orientation assumed the same)
           else
           {
             for (unsigned j2 = 0; j2 < n_node_1d - 2; ++j2)
             {
               elem_pt->node_pt(n) = nodes_on_global_edge[edge_index][j2];
               // It is possible that the edge may be on additional boundaries
               // through another element
               // So add again (note that this function will not add to
               // boundaries twice)
               for (std::set<unsigned>::iterator it = edge_boundaries.begin();
                    it != edge_boundaries.end();
                    ++it)
               {
                 this->add_boundary_node((*it) - 1, elem_pt->node_pt(n));
               }
               ++n;
             }
           }
         } // End of loop over edges
         // Deal with enriched elements
         if (n_node == 15)
         {
           // Now loop over the faces
           for (unsigned j = 0; j < 4; ++j)
           {
             // Find the boundary id of the face (need to map between node
             // numbers and the face)
             boundary_id = Tmp_mesh_pt->face_boundary(e, face_map[j]);
             // Find the global face index (need to map between node numbers and
             // the face)
             unsigned face_index = Tmp_mesh_pt->face_index(e, face_map[j]);
             // If the nodes on the face have not been allocated
             if (nodes_on_global_face[face_index].size() == 0)
             {
               // Storage for the new node
               Node* new_node_pt = 0;
               // If the face is on a boundary, construct a boundary node
               if (boundary_id > 0)
               {
                 new_node_pt =
                   elem_pt->construct_boundary_node(n, time_stepper_pt);
                 // Add it to the boundary
                 this->add_boundary_node(boundary_id - 1, new_node_pt);
               }
               // Otherwise construct a normal node
               else
               {
                 new_node_pt = elem_pt->construct_node(n, time_stepper_pt);
               }
               // Find the local coordinates of the node
               elem_pt->local_coordinate_of_node(n, s);
               // Find the coordinates of the new node from the exiting and
               // fully-functional element in the scaffold mesh
               for (unsigned i = 0; i < dim; ++i)
               {
                 new_node_pt->x(i) = tmp_elem_pt->interpolated_x(s, i);
               }
               // Add the newly created node to the global node list
               Node_pt.push_back(new_node_pt);
               // Add to the face index
               nodes_on_global_face[face_index].push_back(new_node_pt);
               // Increment the local node number
               ++n;
             }
             // Otherwise just set the single node from the face element
             else
             {
               elem_pt->node_pt(n) = nodes_on_global_face[face_index][0];
               ++n;
             }
           } // end of loop over faces
           // Construct the element's central node, which is not on a boundary
           {
             Node* new_node_pt =
               finite_element_pt(e)->construct_node(n, time_stepper_pt);
             Node_pt.push_back(new_node_pt);
             // Find the local coordinates of the node
             elem_pt->local_coordinate_of_node(n, s);
             // Find the coordinates of the new node from the existing
             // and fully-functional element in the scaffold mesh
             for (unsigned i = 0; i < dim; i++)
             {
               new_node_pt->x(i) = tmp_elem_pt->interpolated_x(s, i);
             }
           }
         } // End of enriched case
       } // End of case for edge nodes
       // Now loop over the faces to setup the information about elements
       // adjacent to the boundary
       for (unsigned j = 0; j < 4; ++j)
       {
         // Find the boundary id of the face
         boundary_id = Tmp_mesh_pt->face_boundary(e, j);
         if (boundary_id > 0)
         {
           Boundary_element_pt[boundary_id - 1].push_back(elem_pt);
           // Need to put a shift in here because of an inconsistent naming
           // convention between tetgen and our faces
           // Tetgen Face 0 is our Face 3
           // Tetgen Face 1 is our Face 2
           // Tetgen Face 2 is our Face 1
           // Tetgen Face 3 is our Face 0
           Face_index_at_boundary[boundary_id - 1].push_back(3 - j);
           // If using regions set up the boundary information
           if (use_attributes)
           {
             // Element adjacent to boundary
             Boundary_region_element_pt[boundary_id - 1]
                                       [static_cast<unsigned>(
                                          Tmp_mesh_pt->element_attribute(e))]
                                         .push_back(elem_pt);
             // Need to put a shift in here because of an inconsistent naming
             // convention between triangle and face elements
             Face_index_region_at_boundary[boundary_id - 1]
                                          [static_cast<unsigned>(
                                             Tmp_mesh_pt->element_attribute(e))]
                                            .push_back(3 - j);
           }
         }
       } // End of loop over faces
       // Lookup scheme has now been setup
       Lookup_for_elements_next_boundary_is_setup = true;
       //   /*
       //   //For standard quadratic elements all nodes are edge nodes
       //   unsigned n_vertex_and_edge_node = n_node;
       //   //If we have enriched elements, there are only 10 vertex and edge
       //   nodes if(n_node==15)
       //    {
       //     //There are only 10 vertex and edge nodes
       //     n_vertex_and_edge_node = 10;
       //    }
       //   // Loop over the new (edge) nodes in the element and create them.
       //   for(unsigned j=4;j<n_vertex_and_edge_node;j++)
       //    {
       //     // Figure out edge nodes
       //     switch(j)
       //      {
       //       // Node 4 is between nodes 0 and 1
       //      case 4:
       //       edge_node1_pt=Tmp_mesh_pt->finite_element_pt(e)->node_pt(0);
       //       edge_node2_pt=Tmp_mesh_pt->finite_element_pt(e)->node_pt(1);
       //       break;
       //       // Node 5 is between nodes 0 and 2
       //      case 5:
       //       edge_node1_pt=Tmp_mesh_pt->finite_element_pt(e)->node_pt(0);
       //       edge_node2_pt=Tmp_mesh_pt->finite_element_pt(e)->node_pt(2);
       //       break;
       //       // Node 6 is between nodes 0 and 3
       //      case 6:
       //       edge_node1_pt=Tmp_mesh_pt->finite_element_pt(e)->node_pt(0);
       //       edge_node2_pt=Tmp_mesh_pt->finite_element_pt(e)->node_pt(3);
       //       break;
       //       // Node 7 is between nodes 1 and 2
       //      case 7:
       //       edge_node1_pt=Tmp_mesh_pt->finite_element_pt(e)->node_pt(1);
       //       edge_node2_pt=Tmp_mesh_pt->finite_element_pt(e)->node_pt(2);
       //       break;
       //       // Node 8 is between nodes 2 and 3
       //      case 8:
       //       edge_node1_pt=Tmp_mesh_pt->finite_element_pt(e)->node_pt(2);
       //       edge_node2_pt=Tmp_mesh_pt->finite_element_pt(e)->node_pt(3);
       //       break;
       //       // Node 9 is between nodes 1 and 3
       //      case 9:
       //       edge_node1_pt=Tmp_mesh_pt->finite_element_pt(e)->node_pt(1);
       //       edge_node2_pt=Tmp_mesh_pt->finite_element_pt(e)->node_pt(3);
       //       break;
       //       break;
       //       //Error
       //      default:
       //       throw OomphLibError("More than ten edge nodes in Tet Element",
       //       OOMPH_CURRENT_FUNCTION,
       //                           OOMPH_EXCEPTION_LOCATION);
       //      }
       //     // Do we need a boundary node?
       //     bool need_boundary_node=false;
       //     // hierher At some point fine tune via intersection of boundary
       //     sets if
       //     (edge_node1_pt->is_on_boundary()&&edge_node2_pt->is_on_boundary())
       //      {
       //       need_boundary_node=true;
       //      }
       //     // Do we need a new node?
       //     if (central_edge_node_pt(edge_node1_pt,edge_node2_pt)==0)
       //      {
       //       Node* new_node_pt=0;
       //       // Create new  boundary node
       //       if (need_boundary_node)
       //        {
       //         new_node_pt=finite_element_pt(e)->
       //          construct_boundary_node(j,time_stepper_pt);
       //        }
       //       // Create new normal node
       //       else
       //        {
       //         new_node_pt=finite_element_pt(e)->
       //          construct_node(j,time_stepper_pt);
       //        }
       //       Node_pt.push_back(new_node_pt);
       //       // Now indicate existence of newly created mideside node in map
       //       central_edge_node_pt(edge_node1_pt,edge_node2_pt)=new_node_pt;
       //       central_edge_node_pt(edge_node2_pt,edge_node1_pt)=new_node_pt;
       //       // What are the node's local coordinates?
       //       finite_element_pt(e)->local_coordinate_of_node(j,s);
       //       // Find the coordinates of the new node from the existing
       //       // and fully-functional element in the scaffold mesh
       //       for(unsigned i=0;i<dim;i++)
       //        {
       //         new_node_pt->x(i)=
       //          Tmp_mesh_pt->finite_element_pt(e)->interpolated_x(s,i);
       //        }
       //      }
       //     else
       //      {
       //       // Set pointer to the existing node
       //       finite_element_pt(e)->node_pt(j)=
       //        central_edge_node_pt(edge_node1_pt,edge_node2_pt);
       //      }
       //    } // end of loop over new nodes
       //   //Need to sort out the face nodes
       //   if(n_node==15)
       //    {
       //     // Loop over the new (face) nodes in the element and create them.
       //     for(unsigned j=10;j<14;j++)
       //      {
       //       //Empty the set of face nodes
       //       face_nodes_pt.clear();
       //       // Figure out face nodes
       //       switch(j)
       //        {
       //         // Node 10 is between nodes 0 and 1 and 3
       //        case 10:
       //         face_nodes_pt.insert(Tmp_mesh_pt->finite_element_pt(e)->node_pt(0));
       //         face_nodes_pt.insert(Tmp_mesh_pt->finite_element_pt(e)->node_pt(1));
       //         face_nodes_pt.insert(Tmp_mesh_pt->finite_element_pt(e)->node_pt(3));
       //         break;
       //         // Node 11 is between nodes 0 and 1 and 2
       //        case 11:
       //         face_nodes_pt.insert(Tmp_mesh_pt->finite_element_pt(e)->node_pt(0));
       //         face_nodes_pt.insert(Tmp_mesh_pt->finite_element_pt(e)->node_pt(1));
       //         face_nodes_pt.insert(Tmp_mesh_pt->finite_element_pt(e)->node_pt(2));
       //         break;
       //         // Node 12 is between nodes 0 and 2 and 3
       //        case 12:
       //         face_nodes_pt.insert(Tmp_mesh_pt->finite_element_pt(e)->node_pt(0));
       //         face_nodes_pt.insert(Tmp_mesh_pt->finite_element_pt(e)->node_pt(2));
       //         face_nodes_pt.insert(Tmp_mesh_pt->finite_element_pt(e)->node_pt(3));
       //         break;
       //         // Node 13 is between nodes 1 and 2 and 3
       //        case 13:
       //         face_nodes_pt.insert(Tmp_mesh_pt->finite_element_pt(e)->node_pt(1));
       //         face_nodes_pt.insert(Tmp_mesh_pt->finite_element_pt(e)->node_pt(2));
       //         face_nodes_pt.insert(Tmp_mesh_pt->finite_element_pt(e)->node_pt(3));
       //         break;
       //         //Error
       //        default:
       //         throw OomphLibError("More than four face nodes in Tet Element",
       //         OOMPH_CURRENT_FUNCTION,
       //                             OOMPH_EXCEPTION_LOCATION);
       //        }
       //       // Do we need a boundary node?
       //       bool need_boundary_node=false;
       //       //Work it out from the face boundary
       //       boundary_id = Tmp_mesh_pt->face_boundary(e,face_map[j-10]);
       //       //If it's non-zero then we do need to create a boundary node
       //       if(boundary_id!=0) {need_boundary_node=true;}
       //       // Do we need a new node?
       //       if (central_face_node_pt[face_nodes_pt]==0)
       //        {
       //         Node* new_node_pt=0;
       //         // Create a new  boundary node
       //         if (need_boundary_node)
       //          {
       //           new_node_pt=finite_element_pt(e)->
       //            construct_boundary_node(j,time_stepper_pt);
       //           //Add it to the boundary
       //           add_boundary_node(boundary_id-1,new_node_pt);
       //          }
       //         // Create new normal node
       //         else
       //          {
       //           new_node_pt=finite_element_pt(e)->
       //            construct_node(j,time_stepper_pt);
       //          }
       //         Node_pt.push_back(new_node_pt);
       //       // Now indicate existence of newly created mideside node in map
       //       central_face_node_pt[face_nodes_pt]=new_node_pt;
       //       // What are the node's local coordinates?
       //       finite_element_pt(e)->local_coordinate_of_node(j,s);
       //       // Find the coordinates of the new node from the existing
       //       // and fully-functional element in the scaffold mesh
       //       for(unsigned i=0;i<dim;i++)
       //        {
       //         new_node_pt->x(i)=
       //          Tmp_mesh_pt->finite_element_pt(e)->interpolated_x(s,i);
       //        }
       //        }
       //       else
       //        {
       //         // Set pointer to the existing node
       //         finite_element_pt(e)->node_pt(j)=
       //          central_face_node_pt[face_nodes_pt];
       //        }
       //      } //End of loop over face nodes
       //     //Construct the element's central node, which is not on a boundary
       //     {
       //      Node* new_node_pt=
       //       finite_element_pt(e)->construct_node(14,time_stepper_pt);
       //      Node_pt.push_back(new_node_pt);
       //      // What are the node's local coordinates?
       //      finite_element_pt(e)->local_coordinate_of_node(14,s);
       //      // Find the coordinates of the new node from the existing
       //      // and fully-functional element in the scaffold mesh
       //      for(unsigned i=0;i<dim;i++)
       //       {
       //        new_node_pt->x(i)=
       //         Tmp_mesh_pt->finite_element_pt(e)->interpolated_x(s,i);
       //       }
       //     }
       //    } //End of enriched case
       //  } //end of loop over elements
       // //Boundary conditions
       // // Matrix map to check if a node has already been added to
       // // the boundary number b
       // MapMatrixMixed<Node*,unsigned,bool> bound_node_done;
       // // Loop over elements
       // for (unsigned e=0;e<nelem;e++)
       //  {
       //   // Loop over new local nodes
       //   for(unsigned j=4;j<n_node;j++)
       //    {
       //     // Pointer to the element's local node
       //     Node* loc_node_pt=finite_element_pt(e)->node_pt(j);
       //     // This will have to be changed for higher-order elements
       //     //=======================================================
       //     //  These are the face nodes on the element's face 0:
       //     if ( (j==4) || (j==5) || (j==7) )
       //      {
       //       boundary_id=Tmp_mesh_pt->face_boundary(e,0);
       //       if (boundary_id!=0)
       //        {
       //         if (!bound_node_done(loc_node_pt,boundary_id-1))
       //          {
       //           add_boundary_node(boundary_id-1,loc_node_pt);
       //           bound_node_done(loc_node_pt,boundary_id-1)=true;
       //          }
       //        }
       //      }
       //     // These are the face nodes on the element's face 1:
       //     if ( (j==4) || (j==6) || (j==9) )
       //      {
       //       boundary_id=Tmp_mesh_pt->face_boundary(e,1);
       //       if (boundary_id!=0)
       //        {
       //         if (!bound_node_done(loc_node_pt,boundary_id-1))
       //          {
       //           add_boundary_node(boundary_id-1,loc_node_pt);
       //           bound_node_done(loc_node_pt,boundary_id-1)=true;
       //          }
       //        }
       //      }
       //     // These are the face nodes on the element's face 2:
       //     if ( (j==5) || (j==6) || (j==8) )
       //      {
       //       boundary_id=Tmp_mesh_pt->face_boundary(e,2);
       //       if (boundary_id!=0)
       //        {
       //         if (!bound_node_done(loc_node_pt,boundary_id-1))
       //          {
       //           add_boundary_node(boundary_id-1,loc_node_pt);
       //           bound_node_done(loc_node_pt,boundary_id-1)=true;
       //          }
       //        }
       //      }
       //     // These are the face nodes on the element's face 3:
       //     if  ( (j==7) || (j==8) || (j==9) )
       //      {
       //       boundary_id=Tmp_mesh_pt->face_boundary(e,3);
       //       if (boundary_id!=0)
       //        {
       //         if (!bound_node_done(loc_node_pt,boundary_id-1))
       //          {
       //           add_boundary_node(boundary_id-1,loc_node_pt);
       //           bound_node_done(loc_node_pt,boundary_id-1)=true;
       //          }
       //        }
       //      }
       //    } //end for j
       // */
     } // end for e
   } // end function
References oomph::FiniteElement::construct_boundary_node(), oomph::FiniteElement::construct_node(), e(), oomph::Node::get_boundaries_pt(), i, oomph::FiniteElement::interpolated_x(), j, oomph::FiniteElement::local_coordinate_of_node(), n, oomph::FiniteElement::node_pt(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, s, size, and oomph::Node::x().
Referenced by oomph::RefineableTetgenMesh< ELEMENT >::RefineableTetgenMesh(), and oomph::TetgenMesh< ELEMENT >::TetgenMesh().
build_tetgenio()
template<class ELEMENT > void oomph::TetgenMesh< ELEMENT >::build_tetgenio (TetMeshFacetedSurface *const & outer_boundary_pt, Vector< TetMeshFacetedSurface * > & internal_surface_pt, Vector< double > *const & target_element_volume_in_region_pt, tetgenio & tetgen_io) inline
Build tetgenio object from the TetMeshFacetedSurfaces.
ALH: This may not be needed
     {
       // Pointer to Tetgen facet
       tetgenio::facet* f;
       // Pointer to Tetgen polygon
       tetgenio::polygon* p;
       // Start all indices from 1 (it's a choice and we've made it
       tetgen_io.firstnumber = 1;
       tetgen_io.useindex = true;
       // Find the number of internal surfaces
       const unsigned n_internal = internal_surface_pt.size();
       // Find the number of points on the outer boundary
       const unsigned n_outer_vertex = outer_boundary_pt->nvertex();
       tetgen_io.numberofpoints = n_outer_vertex;
       // Find the number of points on the inner boundaries and add to the totals
       Vector<unsigned> n_internal_vertex(n_internal);
       Vector<unsigned> internal_vertex_offset(n_internal);
       for (unsigned h = 0; h < n_internal; ++h)
       {
         n_internal_vertex[h] = internal_surface_pt[h]->nvertex();
         internal_vertex_offset[h] = tetgen_io.numberofpoints;
         tetgen_io.numberofpoints += n_internal_vertex[h];
       }
       // Read the data into the point list
       tetgen_io.pointlist = new double[tetgen_io.numberofpoints * 3];
       tetgen_io.pointmarkerlist = new int[tetgen_io.numberofpoints];
       unsigned counter = 0;
       for (unsigned n = 0; n < n_outer_vertex; ++n)
       {
         for (unsigned i = 0; i < 3; ++i)
         {
           tetgen_io.pointlist[counter] =
             outer_boundary_pt->vertex_coordinate(n, i);
           ++counter;
         }
       }
       for (unsigned h = 0; h < n_internal; ++h)
       {
         const unsigned n_inner = n_internal_vertex[h];
         for (unsigned n = 0; n < n_inner; ++n)
         {
           for (unsigned i = 0; i < 3; ++i)
           {
             tetgen_io.pointlist[counter] =
               internal_surface_pt[h]->vertex_coordinate(n, i);
             ++counter;
           }
         }
       }
       // Set up the pointmarkers
       counter = 0;
       for (unsigned n = 0; n < n_outer_vertex; ++n)
       {
         tetgen_io.pointmarkerlist[counter] =
           outer_boundary_pt->one_based_vertex_boundary_id(n);
         ++counter;
       }
       for (unsigned h = 0; h < n_internal; ++h)
       {
         const unsigned n_inner = n_internal_vertex[h];
         for (unsigned n = 0; n < n_inner; ++n)
         {
           tetgen_io.pointmarkerlist[counter] =
             internal_surface_pt[h]->one_based_vertex_boundary_id(n);
           ++counter;
         }
       }
       // Now the facets
       unsigned n_outer_facet = outer_boundary_pt->nfacet();
       tetgen_io.numberoffacets = n_outer_facet;
       Vector<unsigned> n_inner_facet(n_internal);
       for (unsigned h = 0; h < n_internal; ++h)
       {
         n_inner_facet[h] = internal_surface_pt[h]->nfacet();
         tetgen_io.numberoffacets += n_inner_facet[h];
       }
       tetgen_io.facetlist = new tetgenio::facet[tetgen_io.numberoffacets];
       tetgen_io.facetmarkerlist = new int[tetgen_io.numberoffacets];
       counter = 0;
       for (unsigned n = 0; n < n_outer_facet; ++n)
       {
         // Set pointer to facet
         f = &tetgen_io.facetlist[counter];
         f->numberofpolygons = 1;
         f->polygonlist = new tetgenio::polygon[f->numberofpolygons];
         f->numberofholes = 0;
         f->holelist = NULL;
         p = &f->polygonlist[0];
         Vector<unsigned> facet = outer_boundary_pt->vertex_index_in_tetgen(n);
         p->numberofvertices = facet.size();
         p->vertexlist = new int[p->numberofvertices];
         for (int i = 0; i < p->numberofvertices; ++i)
         {
           // The offset here is because we have insisted on 1-based indexing
           p->vertexlist[i] = facet[i] + 1;
         }
         // Set up the boundary markers
         tetgen_io.facetmarkerlist[counter] =
           outer_boundary_pt->one_based_facet_boundary_id(n);
         // Increase the counter
         ++counter;
       }
       // Initialise the number of holes
       tetgen_io.numberofholes = 0;
       // and the number of regions
       tetgen_io.numberofregions = 0;
       // Loop over the internal stuff
       for (unsigned h = 0; h < n_internal; ++h)
       {
         for (unsigned n = 0; n < n_inner_facet[h]; ++n)
         {
           // Set pointer to facet
           f = &tetgen_io.facetlist[counter];
           f->numberofpolygons = 1;
           f->polygonlist = new tetgenio::polygon[f->numberofpolygons];
           f->numberofholes = 0;
           f->holelist = NULL;
           p = &f->polygonlist[0];
           Vector<unsigned> facet =
             internal_surface_pt[h]->vertex_index_in_tetgen(n);
           p->numberofvertices = facet.size();
           p->vertexlist = new int[p->numberofvertices];
           for (int i = 0; i < p->numberofvertices; ++i)
           {
             // Add the 1-based and vertex offsets to get these number correct
             p->vertexlist[i] = facet[i] + internal_vertex_offset[h] + 1;
           }
           // Set up the boundary markers
           tetgen_io.facetmarkerlist[counter] =
             internal_surface_pt[h]->one_based_facet_boundary_id(n);
           ++counter;
         }
         // If it's a hole/region add it
         TetMeshFacetedClosedSurface* srf_pt =
           dynamic_cast<TetMeshFacetedClosedSurface*>(internal_surface_pt[h]);
         if (srf_pt != 0)
         {
           unsigned n_int_pts = srf_pt->ninternal_point_for_tetgen();
           for (unsigned j = 0; j < n_int_pts; j++)
           {
             if (srf_pt->internal_point_identifies_hole_for_tetgen(j))
             {
               ++tetgen_io.numberofholes;
             }
             // Otherwise it may be region
             else
             {
               if (srf_pt->internal_point_identifies_region_for_tetgen(j))
               {
                 ++tetgen_io.numberofregions;
               }
             }
           }
         }
       }
       // Set storage for the holes
       tetgen_io.holelist = new double[3 * tetgen_io.numberofholes];
       // Loop over all the internal boundaries again
       counter = 0;
       for (unsigned h = 0; h < n_internal; ++h)
       {
         TetMeshFacetedClosedSurface* srf_pt =
           dynamic_cast<TetMeshFacetedClosedSurface*>(internal_surface_pt[h]);
         if (srf_pt != 0)
         {
           unsigned n_int_pts = srf_pt->ninternal_point_for_tetgen();
           for (unsigned j = 0; j < n_int_pts; j++)
           {
             if (srf_pt->internal_point_identifies_hole_for_tetgen(j))
             {
               for (unsigned i = 0; i < 3; ++i)
               {
                 tetgen_io.holelist[counter] =
                   srf_pt->internal_point_for_tetgen(j, i);
                 ++counter;
               }
             }
           }
         }
       }
       // Set storage for the regions
       tetgen_io.regionlist = new double[5 * tetgen_io.numberofregions];
       // Loop over all the internal boundaries again
       counter = 0;
       for (unsigned h = 0; h < n_internal; ++h)
       {
         TetMeshFacetedClosedSurface* srf_pt =
           dynamic_cast<TetMeshFacetedClosedSurface*>(internal_surface_pt[h]);
         if (srf_pt != 0)
         {
           unsigned n_int_pts = srf_pt->ninternal_point_for_tetgen();
           for (unsigned j = 0; j < n_int_pts; j++)
           {
             if (srf_pt->internal_point_identifies_region_for_tetgen(j))
             {
               for (unsigned i = 0; i < 3; ++i)
               {
                 tetgen_io.regionlist[counter] =
                   srf_pt->internal_point_for_tetgen(j, i);
                 ++counter;
               }
               tetgen_io.regionlist[counter] =
                 static_cast<double>(srf_pt->region_id_for_tetgen(j));
               ++counter;
               // if there's no target volumes specified, default to zero
               if (target_element_volume_in_region_pt == nullptr)
               {
                 tetgen_io.regionlist[counter] = 0;
               }
               else
               {
                 // deliberate integer division here to round down to the region
                 // number (five doubles per region)
                 tetgen_io.regionlist[counter] =
                   (*target_element_volume_in_region_pt)[unsigned(counter / 5)];
               }
               ++counter;
             }
           }
         }
       }
     }
References f(), tetgenio::facetlist, tetgenio::facetmarkerlist, tetgenio::firstnumber, tetgenio::holelist, i, oomph::TetMeshFacetedClosedSurface::internal_point_for_tetgen(), oomph::TetMeshFacetedClosedSurface::internal_point_identifies_hole_for_tetgen(), oomph::TetMeshFacetedClosedSurface::internal_point_identifies_region_for_tetgen(), j, n, oomph::TetMeshFacetedSurface::nfacet(), oomph::TetMeshFacetedClosedSurface::ninternal_point_for_tetgen(), tetgenio::numberoffacets, tetgenio::numberofholes, tetgenio::numberofpoints, tetgenio::numberofregions, oomph::TetMeshFacetedSurface::nvertex(), oomph::TetMeshFacetedSurface::one_based_facet_boundary_id(), oomph::TetMeshFacetedSurface::one_based_vertex_boundary_id(), p, tetgenio::pointlist, tetgenio::pointmarkerlist, oomph::TetMeshFacetedClosedSurface::region_id_for_tetgen(), tetgenio::regionlist, tetgenio::useindex, oomph::TetMeshFacetedSurface::vertex_coordinate(), and oomph::TetMeshFacetedSurface::vertex_index_in_tetgen().
Referenced by oomph::TetgenMesh< ELEMENT >::TetgenMesh().
deep_copy_of_tetgenio()
template<class ELEMENT > void TetgenMesh::deep_copy_of_tetgenio (tetgenio *const & input_pt, tetgenio *& output_pt)
Transfer tetgenio data from the input to the output The output is assumed to have been constructed and "empty"
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// Transfer tetgenio data from the input to the output The output is assumed to have been constructed and "empty"
   {
     // Copy data values
     output_pt->firstnumber = input_pt->firstnumber;
     output_pt->mesh_dim = input_pt->mesh_dim;
     output_pt->useindex = input_pt->useindex;
     // Copy the number of points
     output_pt->numberofpoints = input_pt->numberofpoints;
     output_pt->numberofpointattributes = input_pt->numberofpointattributes;
     output_pt->numberofpointmtrs = input_pt->numberofpointmtrs;
     const int n_point = output_pt->numberofpoints;
     if (n_point > 0)
     {
       output_pt->pointlist = new double[n_point * 3];
       // Copy the values
       for (int n = 0; n < (n_point * 3); ++n)
       {
         output_pt->pointlist[n] = input_pt->pointlist[n];
       }
       // If there are point markers copy as well
       if (input_pt->pointmarkerlist != (int*)NULL)
       {
         output_pt->pointmarkerlist = new int[n_point];
         for (int n = 0; n < n_point; ++n)
         {
           output_pt->pointmarkerlist[n] = input_pt->pointmarkerlist[n];
         }
       }
       const int n_attr = output_pt->numberofpointattributes;
       if (n_attr > 0)
       {
         output_pt->pointattributelist = new double[n_point * n_attr];
         for (int n = 0; n < (n_point * n_attr); ++n)
         {
           output_pt->pointattributelist[n] = input_pt->pointattributelist[n];
         }
       }
     } // End of point case
     // Now add in metric tensors (if there are any)
     const int n_point_mtr = output_pt->numberofpointmtrs;
     if (n_point_mtr > 0)
     {
       output_pt->pointmtrlist = new double[n_point * n_point_mtr];
       for (int n = 0; n < (n_point * n_point_mtr); ++n)
       {
         output_pt->pointmtrlist[n] = input_pt->pointmtrlist[n];
       }
     }
     // Next tetrahedrons
     output_pt->numberoftetrahedra = input_pt->numberoftetrahedra;
     output_pt->numberofcorners = input_pt->numberofcorners;
     output_pt->numberoftetrahedronattributes =
       input_pt->numberoftetrahedronattributes;
     const int n_tetra = output_pt->numberoftetrahedra;
     const int n_corner = output_pt->numberofcorners;
     if (n_tetra > 0)
     {
       output_pt->tetrahedronlist = new int[n_tetra * n_corner];
       for (int n = 0; n < (n_tetra * n_corner); ++n)
       {
         output_pt->tetrahedronlist[n] = input_pt->tetrahedronlist[n];
       }
       // Add in the volume constriants
       if (input_pt->tetrahedronvolumelist != (double*)NULL)
       {
         output_pt->tetrahedronvolumelist = new double[n_tetra];
         for (int n = 0; n < n_tetra; ++n)
         {
           output_pt->tetrahedronvolumelist[n] =
             input_pt->tetrahedronvolumelist[n];
         }
       }
       // Add in the attributes
       const int n_tetra_attr = output_pt->numberoftetrahedronattributes;
       if (n_tetra_attr > 0)
       {
         output_pt->tetrahedronattributelist =
           new double[n_tetra * n_tetra_attr];
         for (int n = 0; n < (n_tetra * n_tetra_attr); ++n)
         {
           output_pt->tetrahedronattributelist[n] =
             input_pt->tetrahedronattributelist[n];
         }
       }
       // Add in the neighbour list
       if (input_pt->neighborlist != (int*)NULL)
       {
         output_pt->neighborlist = new int[n_tetra * 4];
         for (int n = 0; n < (n_tetra * 4); ++n)
         {
           output_pt->neighborlist = input_pt->neighborlist;
         }
       }
     } // End of tetrahedron section
     // Now arrange the facet list
     output_pt->numberoffacets = input_pt->numberoffacets;
     const int n_facet = output_pt->numberoffacets;
     if (n_facet > 0)
     {
       output_pt->facetlist = new tetgenio::facet[n_facet];
       for (int n = 0; n < n_facet; ++n)
       {
         tetgenio::facet* input_f_pt = &input_pt->facetlist[n];
         tetgenio::facet* output_f_pt = &output_pt->facetlist[n];
         // Copy polygons and holes from the facets
         output_f_pt->numberofpolygons = input_f_pt->numberofpolygons;
         // Loop over polygons
         const int n_poly = output_f_pt->numberofpolygons;
         if (n_poly > 0)
         {
           output_f_pt->polygonlist = new tetgenio::polygon[n_poly];
           for (int p = 0; p < n_poly; ++p)
           {
             tetgenio::polygon* output_p_pt = &output_f_pt->polygonlist[p];
             tetgenio::polygon* input_p_pt = &input_f_pt->polygonlist[p];
             // Find out how many vertices each polygon has
             output_p_pt->numberofvertices = input_p_pt->numberofvertices;
             // Now copy of the vertices
             const int n_vertex = output_p_pt->numberofvertices;
             if (n_vertex > 0)
             {
               output_p_pt->vertexlist = new int[n_vertex];
               for (int v = 0; v < n_vertex; ++v)
               {
                 output_p_pt->vertexlist[v] = input_p_pt->vertexlist[v];
               }
             }
           }
         }
         // Hole information
         output_f_pt->numberofholes = input_f_pt->numberofholes;
         const int n_hole = output_f_pt->numberofholes;
         if (n_hole > 0)
         {
           throw OomphLibError("Don't know how to handle holes yet\n",
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
         }
       } // end of loop over facets
       // Add the facetmarkers if there are any
       if (input_pt->facetmarkerlist != (int*)NULL)
       {
         output_pt->facetmarkerlist = new int[n_facet];
         for (int n = 0; n < n_facet; ++n)
         {
           output_pt->facetmarkerlist[n] = input_pt->facetmarkerlist[n];
         }
       }
     }
     // Now the holes
     output_pt->numberofholes = input_pt->numberofholes;
     const int n_hole = output_pt->numberofholes;
     if (n_hole > 0)
     {
       output_pt->holelist = new double[n_hole * 3];
       for (int n = 0; n < (n_hole * 3); ++n)
       {
         output_pt->holelist[n] = input_pt->holelist[n];
       }
     }
     // Now the regions
     output_pt->numberofregions = input_pt->numberofregions;
     const int n_region = output_pt->numberofregions;
     if (n_region > 0)
     {
       output_pt->regionlist = new double[n_region * 5];
       for (int n = 0; n < (n_region * 5); ++n)
       {
         output_pt->regionlist[n] = input_pt->regionlist[n];
       }
     }
     // Now the facet constraints
     output_pt->numberoffacetconstraints = input_pt->numberoffacetconstraints;
     const int n_facet_const = output_pt->numberoffacetconstraints;
     if (n_facet_const > 0)
     {
       output_pt->facetconstraintlist = new double[n_facet_const * 2];
       for (int n = 0; n < (n_facet_const * 2); ++n)
       {
         output_pt->facetconstraintlist[n] = input_pt->facetconstraintlist[n];
       }
     }
     // Now the segment constraints
     output_pt->numberofsegmentconstraints =
       input_pt->numberofsegmentconstraints;
     const int n_seg_const = output_pt->numberofsegmentconstraints;
     if (n_seg_const > 0)
     {
       output_pt->segmentconstraintlist = new double[n_seg_const * 2];
       for (int n = 0; n < (n_seg_const * 2); ++n)
       {
         output_pt->segmentconstraintlist[n] =
           input_pt->segmentconstraintlist[n];
       }
     }
     // Now the face list
     output_pt->numberoftrifaces = input_pt->numberoftrifaces;
     const int n_tri_face = output_pt->numberoftrifaces;
     if (n_tri_face > 0)
     {
       output_pt->trifacelist = new int[n_tri_face * 3];
       for (int n = 0; n < (n_tri_face * 3); ++n)
       {
         output_pt->trifacelist[n] = input_pt->trifacelist[n];
       }
       output_pt->trifacemarkerlist = new int[n_tri_face];
       for (int n = 0; n < n_tri_face; ++n)
       {
         output_pt->trifacemarkerlist[n] = input_pt->trifacemarkerlist[n];
       }
     }
     // Now the edge list
     output_pt->numberofedges = input_pt->numberofedges;
     const int n_edge = output_pt->numberofedges;
     if (n_edge > 0)
     {
       output_pt->edgelist = new int[n_edge * 2];
       for (int n = 0; n < (n_edge * 2); ++n)
       {
         output_pt->edgelist[n] = input_pt->edgelist[n];
       }
       output_pt->edgemarkerlist = new int[n_edge];
       for (int n = 0; n < n_edge; ++n)
       {
         output_pt->edgemarkerlist[n] = input_pt->edgemarkerlist[n];
       }
     }
   }
References tetgenio::edgelist, tetgenio::edgemarkerlist, tetgenio::facetconstraintlist, tetgenio::facetlist, tetgenio::facetmarkerlist, tetgenio::firstnumber, tetgenio::holelist, tetgenio::mesh_dim, n, tetgenio::neighborlist, tetgenio::numberofcorners, tetgenio::numberofedges, tetgenio::numberoffacetconstraints, tetgenio::numberoffacets, tetgenio::facet::numberofholes, tetgenio::numberofholes, tetgenio::numberofpointattributes, tetgenio::numberofpointmtrs, tetgenio::numberofpoints, tetgenio::facet::numberofpolygons, tetgenio::numberofregions, tetgenio::numberofsegmentconstraints, tetgenio::numberoftetrahedra, tetgenio::numberoftetrahedronattributes, tetgenio::numberoftrifaces, tetgenio::polygon::numberofvertices, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, p, tetgenio::pointattributelist, tetgenio::pointlist, tetgenio::pointmarkerlist, tetgenio::pointmtrlist, tetgenio::facet::polygonlist, tetgenio::regionlist, tetgenio::segmentconstraintlist, tetgenio::tetrahedronattributelist, tetgenio::tetrahedronlist, tetgenio::tetrahedronvolumelist, tetgenio::trifacelist, tetgenio::trifacemarkerlist, tetgenio::useindex, v, and tetgenio::polygon::vertexlist.
Referenced by oomph::RefineableTetgenMesh< ELEMENT >::RefineableTetgenMesh(), and oomph::TetgenMesh< ELEMENT >::set_deep_copy_tetgenio_pt().
set_deep_copy_tetgenio_pt()
template<class ELEMENT > void oomph::TetgenMesh< ELEMENT >::set_deep_copy_tetgenio_pt (tetgenio *const & tetgenio_pt) inline
Set the tetgen pointer by a deep copy.
     {
       // Delete the existing data
       if (Tetgenio_exists)
       {
         delete Tetgenio_pt;
       }
       this->Tetgenio_pt = new tetgenio;
       // Create a deep copy of tetgenio_pt and store the result in
       // Tetgenio_pt
       this->deep_copy_of_tetgenio(tetgenio_pt, this->Tetgenio_pt);
     }
References oomph::TetgenMesh< ELEMENT >::deep_copy_of_tetgenio(), oomph::TetgenMesh< ELEMENT >::Tetgenio_exists, and oomph::TetgenMesh< ELEMENT >::Tetgenio_pt.
set_mesh_level_time_stepper()
template<class ELEMENT > void oomph::TetgenMesh< ELEMENT >::set_mesh_level_time_stepper (TimeStepper *const & time_stepper_pt, const bool & preserve_existing_data) inline virtual
Overload set_mesh_level_time_stepper so that the stored time stepper now corresponds to the new timestepper
Reimplemented from oomph::Mesh.
     {
       this->Time_stepper_pt = time_stepper_pt;
     }
References oomph::TetMeshBase::Time_stepper_pt.
setup_reverse_lookup_schemes_for_faceted_surface()
template<class ELEMENT > void TetgenMesh::setup_reverse_lookup_schemes_for_faceted_surface (TetMeshFacetedSurface *const & faceted_surface_pt) protected
Function to setup the reverse look-up schemes.
Helper function to set up the reverse look up scheme for facets. This is used to set up boundary coordinates.
   {
     // Set up reverse lookup scheme for a given faceted surface
     // Assumption is that there there is one boundary ID per facet.
     unsigned n_facet = faceted_surface_pt->nfacet();
     for (unsigned f = 0; f < n_facet; f++)
     {
       unsigned b = faceted_surface_pt->one_based_facet_boundary_id(f);
       if (b != 0)
       {
         this->Tet_mesh_faceted_surface_pt[b - 1] = faceted_surface_pt;
         this->Tet_mesh_facet_pt[b - 1] = faceted_surface_pt->facet_pt(f);
       }
       else
       {
         std::ostringstream error_message;
         error_message << "Boundary IDs have to be one-based. Yours is " << b
                       << "\n";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
     }
   }
References b, f(), oomph::TetMeshFacetedSurface::facet_pt(), oomph::TetMeshFacetedSurface::nfacet(), oomph::TetMeshFacetedSurface::one_based_facet_boundary_id(), OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
Referenced by oomph::RefineableTetgenMesh< ELEMENT >::RefineableTetgenMesh(), and oomph::TetgenMesh< ELEMENT >::TetgenMesh().
tetgenio_exists()
template<class ELEMENT > bool oomph::TetgenMesh< ELEMENT >::tetgenio_exists () const inline
Boolen defining whether tetgenio object has been built or not.
     {
       return Tetgenio_exists;
     }
References oomph::TetgenMesh< ELEMENT >::Tetgenio_exists.
tetgenio_pt()
template<class ELEMENT > tetgenio*& oomph::TetgenMesh< ELEMENT >::tetgenio_pt () inline
Access to the triangulateio representation of the mesh.
     {
       return Tetgenio_pt;
     }
References oomph::TetgenMesh< ELEMENT >::Tetgenio_pt.
Referenced by oomph::RefineableTetgenMesh< ELEMENT >::adapt().
Member Data Documentation
Tetgenio_exists
template<class ELEMENT > bool oomph::TetgenMesh< ELEMENT >::Tetgenio_exists protected
Boolean to indicate whether a tetgenio representation of the mesh exists
Referenced by oomph::RefineableTetgenMesh< ELEMENT >::RefineableTetgenMesh(), oomph::TetgenMesh< ELEMENT >::set_deep_copy_tetgenio_pt(), oomph::TetgenMesh< ELEMENT >::tetgenio_exists(), oomph::TetgenMesh< ELEMENT >::TetgenMesh(), and oomph::TetgenMesh< ELEMENT >::~TetgenMesh().
Tetgenio_pt
template<class ELEMENT > tetgenio* oomph::TetgenMesh< ELEMENT >::Tetgenio_pt protected
Tetgen representation of mesh.
Referenced by oomph::RefineableTetgenMesh< ELEMENT >::RefineableTetgenMesh(), oomph::TetgenMesh< ELEMENT >::set_deep_copy_tetgenio_pt(), oomph::TetgenMesh< ELEMENT >::tetgenio_pt(), oomph::TetgenMesh< ELEMENT >::TetgenMesh(), and oomph::TetgenMesh< ELEMENT >::~TetgenMesh().
Tmp_mesh_pt
template<class ELEMENT > TetgenScaffoldMesh* oomph::TetgenMesh< ELEMENT >::Tmp_mesh_pt protected
Temporary scaffold mesh.
Referenced by oomph::RefineableTetgenMesh< ELEMENT >::RefineableTetgenMesh(), and oomph::TetgenMesh< ELEMENT >::TetgenMesh().
Use_attributes
template<class ELEMENT > bool oomph::TetgenMesh< ELEMENT >::Use_attributes protected
Boolean flag to indicate whether to use attributes or not (required for multidomain meshes)
Referenced by oomph::TetgenMesh< ELEMENT >::TetgenMesh().
The documentation for this class was generated from the following files:
tetgen_mesh.template.h
tetgen_mesh.template.cc