MercuryDPM: oomph::RefineableNavierStokesEquations< DIM > Class Template Reference
oomph::RefineableNavierStokesEquations< DIM > Class Template Reference abstract
#include <refineable_navier_stokes_elements.h>
Public Member Functions
RefineableNavierStokesEquations ()
Constructor.
virtual Node * pressure_node_pt (const unsigned &n_p)
void get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > &press_mass_diag, Vector< double > &veloc_mass_diag, const unsigned &which_one=0)
unsigned num_Z2_flux_terms ()
Number of 'flux' terms for Z2 error estimation.
void get_Z2_flux (const Vector< double > &s, Vector< double > &flux)
void further_build ()
Further build, pass the pointers down to the sons.
void dinterpolated_u_nst_ddata (const Vector< double > &s, const unsigned &i, Vector< double > &du_ddata, Vector< unsigned > &global_eqn_number)
Public Member Functions inherited from oomph::NavierStokesEquations< DIM >
NavierStokesEquations ()
const double & re () const
Reynolds number.
const double & re_st () const
Product of Reynolds and Strouhal number (=Womersley number)
double *& re_pt ()
Pointer to Reynolds number.
double *& re_st_pt ()
Pointer to product of Reynolds and Strouhal number (=Womersley number)
const double & viscosity_ratio () const
double *& viscosity_ratio_pt ()
Pointer to Viscosity Ratio.
const double & density_ratio () const
double *& density_ratio_pt ()
Pointer to Density ratio.
const double & re_invfr () const
Global inverse Froude number.
double *& re_invfr_pt ()
Pointer to global inverse Froude number.
const Vector< double > & g () const
Vector of gravitational components.
Vector< double > *& g_pt ()
Pointer to Vector of gravitational components.
NavierStokesBodyForceFctPt & body_force_fct_pt ()
Access function for the body-force pointer.
NavierStokesBodyForceFctPt body_force_fct_pt () const
Access function for the body-force pointer. Const version.
NavierStokesSourceFctPt & source_fct_pt ()
Access function for the source-function pointer.
NavierStokesSourceFctPt source_fct_pt () const
Access function for the source-function pointer. Const version.
NavierStokesPressureAdvDiffSourceFctPt & source_fct_for_pressure_adv_diff ()
NavierStokesPressureAdvDiffSourceFctPt source_fct_for_pressure_adv_diff () const
int & pinned_fp_pressure_eqn ()
virtual unsigned npres_nst () const =0
Function to return number of pressure degrees of freedom.
virtual void pshape_nst (const Vector< double > &s, Shape &psi) const =0
Compute the pressure shape functions at local coordinate s.
virtual void pshape_nst (const Vector< double > &s, Shape &psi, Shape &test) const =0
virtual double dpshape_and_dptest_eulerian_nst (const Vector< double > &s, Shape &ppsi, DShape &dppsidx, Shape &ptest, DShape &dptestdx) const =0
double u_nst (const unsigned &n, const unsigned &i) const
double u_nst (const unsigned &t, const unsigned &n, const unsigned &i) const
virtual unsigned u_index_nst (const unsigned &i) const
unsigned n_u_nst () const
double du_dt_nst (const unsigned &n, const unsigned &i) const
void disable_ALE ()
void enable_ALE ()
virtual double p_nst (const unsigned &n_p) const =0
virtual double p_nst (const unsigned &t, const unsigned &n_p) const =0
Pressure at local pressure "node" n_p at time level t.
virtual void fix_pressure (const unsigned &p_dof, const double &p_value)=0
Pin p_dof-th pressure dof and set it to value specified by p_value.
virtual int p_nodal_index_nst () const
double pressure_integral () const
Integral of pressure over element.
double dissipation () const
Return integral of dissipation over element.
double dissipation (const Vector< double > &s) const
Return dissipation at local coordinate s.
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
Compute the vorticity vector at local coordinate s.
void get_vorticity (const Vector< double > &s, double &vorticity) const
Compute the scalar vorticity at local coordinate s (2D)
double kin_energy () const
Get integral of kinetic energy over element.
double d_kin_energy_dt () const
Get integral of time derivative of kinetic energy over element.
void strain_rate (const Vector< double > &s, DenseMatrix< double > &strain_rate) const
Strain-rate tensor: 1/2 (du_i/dx_j + du_j/dx_i)
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction)
void get_traction (const Vector< double > &s, const Vector< double > &N, Vector< double > &traction_p, Vector< double > &traction_visc_n, Vector< double > &traction_visc_t)
void get_load (const Vector< double > &s, const Vector< double > &N, Vector< double > &load)
unsigned nscalar_paraview () const
void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
std::string scalar_name_paraview (const unsigned &i) const
void output (std::ostream &outfile)
void output (std::ostream &outfile, const unsigned &nplot)
void output (FILE *file_pt)
void output (FILE *file_pt, const unsigned &nplot)
void full_output (std::ostream &outfile)
void full_output (std::ostream &outfile, const unsigned &nplot)
void output_veloc (std::ostream &outfile, const unsigned &nplot, const unsigned &t)
void output_vorticity (std::ostream &outfile, const unsigned &nplot)
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
void compute_norm (double &norm)
Compute norm of solution: square of the L2 norm of the velocities.
void compute_norm (Vector< double > &norm)
Compute the vector norm of the FEM solution.
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Compute the element's residual Vector.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
Compute the element's residual Vector.
void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
void fill_in_pressure_advection_diffusion_residuals (Vector< double > &residuals)
void fill_in_pressure_advection_diffusion_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void pin_all_non_pressure_dofs (std::map< Data *, std::vector< int >> &eqn_number_backup)
Pin all non-pressure dofs and backup eqn numbers.
virtual void build_fp_press_adv_diff_robin_bc_element (const unsigned &face_index)=0
void output_pressure_advection_diffusion_robin_elements (std::ostream &outfile)
void delete_pressure_advection_diffusion_robin_elements ()
void interpolated_u_nst (const Vector< double > &s, Vector< double > &veloc) const
Compute vector of FE interpolated velocity u at local coordinate s.
double interpolated_u_nst (const Vector< double > &s, const unsigned &i) const
Return FE interpolated velocity u[i] at local coordinate s.
double interpolated_u_nst (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual double interpolated_p_nst (const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s.
double interpolated_p_nst (const unsigned &t, const Vector< double > &s) const
Return FE interpolated pressure at local coordinate s at time level t.
double interpolated_dudx_nst (const Vector< double > &s, const unsigned &i, const unsigned &j) const
void point_output_data (const Vector< double > &s, Vector< double > &data)
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
void get_vorticity (const Vector< double > &s, double &vorticity) const
void get_vorticity (const Vector< double > &s, Vector< double > &vorticity) const
Compute 3D vorticity vector at local coordinate s.
Public Member Functions inherited from oomph::FSIFluidElement
FSIFluidElement ()
Constructor.
FSIFluidElement (const FSIFluidElement &)=delete
Broken copy constructor.
void operator= (const FSIFluidElement &)=delete
Broken assignment operator.
virtual void identify_load_data (std::set< std::pair< Data *, unsigned >> &paired_load_data)=0
virtual void identify_pressure_data (std::set< std::pair< Data *, unsigned >> &paired_pressure_data)=0
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::TemplateFreeNavierStokesEquationsBase
TemplateFreeNavierStokesEquationsBase ()
Constructor (empty)
virtual ~TemplateFreeNavierStokesEquationsBase ()
Virtual destructor (empty)
virtual int p_local_eqn (const unsigned &n) const =0
Public Member Functions inherited from oomph::NavierStokesElementWithDiagonalMassMatrices
NavierStokesElementWithDiagonalMassMatrices ()
Empty constructor.
virtual ~NavierStokesElementWithDiagonalMassMatrices ()
Virtual destructor.
NavierStokesElementWithDiagonalMassMatrices (const NavierStokesElementWithDiagonalMassMatrices &)=delete
Broken copy constructor.
void operator= (const NavierStokesElementWithDiagonalMassMatrices &)=delete
Broken assignment operator.
Public Member Functions inherited from oomph::RefineableElement
RefineableElement ()
virtual ~RefineableElement ()
Destructor, delete the allocated storage for the hanging equations.
RefineableElement (const RefineableElement &)=delete
Broken copy constructor.
void operator= (const RefineableElement &)=delete
Broken assignment operator.
Tree * tree_pt ()
Access function: Pointer to quadtree representation of this element.
void set_tree_pt (Tree *my_tree_pt)
Set pointer to quadtree representation of this element.
virtual unsigned required_nsons () const
bool refinement_is_enabled ()
Flag to indicate suppression of any refinement.
void disable_refinement ()
Suppress of any refinement for this element.
void enable_refinement ()
Emnable refinement for this element.
template<class ELEMENT >
void split (Vector< ELEMENT * > &son_pt) const
int local_hang_eqn (Node *const &node_pt, const unsigned &i)
virtual void build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt, bool &was_already_built, std::ofstream &new_nodes_file)=0
void set_refinement_level (const int &refine_level)
Set the refinement level.
unsigned refinement_level () const
Return the Refinement level.
void select_for_refinement ()
Select the element for refinement.
void deselect_for_refinement ()
Deselect the element for refinement.
void select_sons_for_unrefinement ()
Unrefinement will be performed by merging the four sons of this element.
void deselect_sons_for_unrefinement ()
bool to_be_refined ()
Has the element been selected for refinement?
bool sons_to_be_unrefined ()
Has the element been selected for unrefinement?
virtual void rebuild_from_sons (Mesh *&mesh_pt)=0
virtual void unbuild ()
virtual void deactivate_element ()
virtual bool nodes_built ()
Return true if all the nodes have been built, false if not.
long number () const
Element number (for debugging/plotting)
void set_number (const long &mynumber)
Set element number (for debugging/plotting)
virtual unsigned ncont_interpolated_values () const =0
virtual void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
virtual void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)=0
virtual Node * interpolating_node_pt (const unsigned &n, const int &value_id)
virtual double local_one_d_fraction_of_interpolating_node (const unsigned &n1d, const unsigned &i, const int &value_id)
virtual Node * get_interpolating_node_at_local_coordinate (const Vector< double > &s, const int &value_id)
virtual unsigned ninterpolating_node (const int &value_id)
virtual unsigned ninterpolating_node_1d (const int &value_id)
virtual void interpolating_basis (const Vector< double > &s, Shape &psi, const int &value_id) const
virtual void check_integrity (double &max_error)=0
void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual RefineableElement * root_element_pt ()
virtual RefineableElement * father_element_pt () const
Return a pointer to the father element.
void get_father_at_refinement_level (unsigned &refinement_level, RefineableElement *&father_at_reflevel_pt)
virtual void initial_setup (Tree *const &adopted_father_pt=0, const unsigned &initial_p_order=0)
virtual void pre_build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt)
Pre-build the element.
virtual void setup_hanging_nodes (Vector< std::ofstream * > &output_stream)
virtual void further_setup_hanging_nodes ()
unsigned nshape_controlling_nodes ()
std::map< Node *, unsigned > shape_controlling_node_lookup ()
Public Member Functions inherited from oomph::ElementWithZ2ErrorEstimator
ElementWithZ2ErrorEstimator ()
Default empty constructor.
ElementWithZ2ErrorEstimator (const ElementWithZ2ErrorEstimator &)=delete
Broken copy constructor.
void operator= (const ElementWithZ2ErrorEstimator &)=delete
Broken assignment operator.
virtual unsigned ncompound_fluxes ()
virtual void compute_exact_Z2_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_flux_pt, double &error, double &norm)
virtual void get_Z2_compound_flux_indices (Vector< unsigned > &flux_index)
virtual unsigned nvertex_node () const =0
Number of vertex nodes in the element.
virtual Node * vertex_node_pt (const unsigned &j) const =0
virtual unsigned nrecovery_order ()=0
Order of recovery shape functions.
virtual double geometric_jacobian (const Vector< double > &x)
Static Public Member Functions
static void pin_redundant_nodal_pressures (const Vector< GeneralisedElement * > &element_pt)
static void unpin_all_pressure_dofs (const Vector< GeneralisedElement * > &element_pt)
Unpin all pressure dofs in elements listed in vector.
Static Public Member Functions inherited from oomph::RefineableElement
static double & max_integrity_tolerance ()
Max. allowed discrepancy in element integrity check.
Protected Member Functions
virtual void unpin_elemental_pressure_dofs ()=0
Unpin all pressure dofs in the element.
virtual void pin_elemental_redundant_nodal_pressure_dofs ()
void fill_in_generic_residual_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix, unsigned flag)
void fill_in_generic_pressure_advection_diffusion_contribution_nst (Vector< double > &residuals, DenseMatrix< double > &jacobian, unsigned flag)
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
Protected Member Functions inherited from oomph::NavierStokesEquations< DIM >
virtual double dshape_and_dtest_eulerian_nst (const Vector< double > &s, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
virtual double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, Shape &test, DShape &dtestdx) const =0
virtual double dshape_and_dtest_eulerian_at_knot_nst (const unsigned &ipt, Shape &psi, DShape &dpsidx, RankFourTensor< double > &d_dpsidx_dX, Shape &test, DShape &dtestdx, RankFourTensor< double > &d_dtestdx_dX, DenseMatrix< double > &djacobian_dX) const =0
virtual void get_body_force_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, Vector< double > &result)
virtual void get_body_force_gradient_nst (const double &time, const unsigned &ipt, const Vector< double > &s, const Vector< double > &x, DenseMatrix< double > &d_body_force_dx)
virtual double get_source_nst (const double &time, const unsigned &ipt, const Vector< double > &x)
virtual void get_source_gradient_nst (const double &time, const unsigned &ipt, const Vector< double > &x, Vector< double > &gradient)
virtual void fill_in_generic_dresidual_contribution_nst (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam, unsigned flag)
void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
Protected Member Functions inherited from oomph::FiniteElement
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Member Functions inherited from oomph::RefineableElement
void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
void assign_hanging_local_eqn_numbers (const bool &store_local_dof_pt)
Assign the local equation numbers for hanging node variables.
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Additional Inherited Members
Public Types inherited from oomph::NavierStokesEquations< DIM >
typedef void(* NavierStokesBodyForceFctPt) (const double &time, const Vector< double > &x, Vector< double > &body_force)
typedef double(* NavierStokesSourceFctPt) (const double &time, const Vector< double > &x)
typedef double(* NavierStokesPressureAdvDiffSourceFctPt) (const Vector< double > &x)
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Static Public Attributes inherited from oomph::NavierStokesEquations< DIM >
static Vector< double > Gamma
Vector to decide whether the stress-divergence form is used or not.
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Static Protected Member Functions inherited from oomph::RefineableElement
static void check_value_id (const int &n_continuously_interpolated_values, const int &value_id)
Protected Attributes inherited from oomph::NavierStokesEquations< DIM >
double * Viscosity_Ratio_pt
double * Density_Ratio_pt
double * Re_pt
Pointer to global Reynolds number.
double * ReSt_pt
Pointer to global Reynolds number x Strouhal number (=Womersley)
double * ReInvFr_pt
Vector< double > * G_pt
Pointer to global gravity Vector.
NavierStokesBodyForceFctPt Body_force_fct_pt
Pointer to body force function.
NavierStokesSourceFctPt Source_fct_pt
Pointer to volumetric source function.
NavierStokesPressureAdvDiffSourceFctPt Press_adv_diff_source_fct_pt
bool ALE_is_disabled
Vector< FpPressureAdvDiffRobinBCElementBase * > Pressure_advection_diffusion_robin_element_pt
int Pinned_fp_pressure_eqn
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Protected Attributes inherited from oomph::RefineableElement
Tree * Tree_pt
A pointer to a general tree object.
unsigned Refine_level
Refinement level.
bool To_be_refined
Flag for refinement.
bool Refinement_is_enabled
Flag to indicate suppression of any refinement.
bool Sons_to_be_unrefined
Flag for unrefinement.
long Number
Global element number – for plotting/validation purposes.
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Static Protected Attributes inherited from oomph::RefineableElement
static double Max_integrity_tolerance = 1.0e-8
Max. allowed discrepancy in element integrity check.
Detailed Description
template<unsigned DIM>
class oomph::RefineableNavierStokesEquations< DIM >
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// Refineable version of the Navier–Stokes equations
Constructor & Destructor Documentation
RefineableNavierStokesEquations()
template<unsigned DIM> oomph::RefineableNavierStokesEquations< DIM >::RefineableNavierStokesEquations () inline
Constructor.
       : NavierStokesEquations<DIM>(),
         RefineableElement(),
         ElementWithZ2ErrorEstimator()
     {
     }
Member Function Documentation
dinterpolated_u_nst_ddata()
template<unsigned DIM> void oomph::RefineableNavierStokesEquations< DIM >::dinterpolated_u_nst_ddata (const Vector< double > & s, const unsigned & i, Vector< double > & du_ddata, Vector< unsigned > & global_eqn_number) inline virtual
Compute the derivatives of the i-th component of velocity at point s with respect to all data that can affect its value. In addition, return the global equation numbers corresponding to the data. Overload the non-refineable version to take account of hanging node information
Reimplemented from oomph::NavierStokesEquations< DIM >.
     {
       // Find number of nodes
       unsigned n_node = this->nnode();
       // Local shape function
       Shape psi(n_node);
       // Find values of shape function at the given local coordinate
       this->shape(s, psi);
       // Find the index at which the velocity component is stored
       const unsigned u_nodal_index = this->u_index_nst(i);
       // Storage for hang info pointer
       HangInfo* hang_info_pt = 0;
       // Storage for global equation
       int global_eqn = 0;
       // Find the number of dofs associated with interpolated u
       unsigned n_u_dof = 0;
       for (unsigned l = 0; l < n_node; l++)
       {
         unsigned n_master = 1;
         // Local bool (is the node hanging)
         bool is_node_hanging = this->node_pt(l)->is_hanging();
         // If the node is hanging, get the number of master nodes
         if (is_node_hanging)
         {
           hang_info_pt = this->node_pt(l)->hanging_pt();
           n_master = hang_info_pt->nmaster();
         }
         // Otherwise there is just one master node, the node itself
         else
         {
           n_master = 1;
         }
         // Loop over the master nodes
         for (unsigned m = 0; m < n_master; m++)
         {
           // Get the equation number
           if (is_node_hanging)
           {
             // Get the equation number from the master node
             global_eqn =
               hang_info_pt->master_node_pt(m)->eqn_number(u_nodal_index);
           }
           else
           {
             // Global equation number
             global_eqn = this->node_pt(l)->eqn_number(u_nodal_index);
           }
           // If it's positive add to the count
           if (global_eqn >= 0)
           {
             ++n_u_dof;
           }
         }
       }
       // Now resize the storage schemes
       du_ddata.resize(n_u_dof, 0.0);
       global_eqn_number.resize(n_u_dof, 0);
       // Loop over th nodes again and set the derivatives
       unsigned count = 0;
       // Loop over the local nodes and sum
       for (unsigned l = 0; l < n_node; l++)
       {
         unsigned n_master = 1;
         double hang_weight = 1.0;
         // Local bool (is the node hanging)
         bool is_node_hanging = this->node_pt(l)->is_hanging();
         // If the node is hanging, get the number of master nodes
         if (is_node_hanging)
         {
           hang_info_pt = this->node_pt(l)->hanging_pt();
           n_master = hang_info_pt->nmaster();
         }
         // Otherwise there is just one master node, the node itself
         else
         {
           n_master = 1;
         }
         // Loop over the master nodes
         for (unsigned m = 0; m < n_master; m++)
         {
           // If the node is hanging get weight from master node
           if (is_node_hanging)
           {
             // Get the hang weight from the master node
             hang_weight = hang_info_pt->master_weight(m);
           }
           else
           {
             // Node contributes with full weight
             hang_weight = 1.0;
           }
           // Get the equation number
           if (is_node_hanging)
           {
             // Get the equation number from the master node
             global_eqn =
               hang_info_pt->master_node_pt(m)->eqn_number(u_nodal_index);
           }
           else
           {
             // Local equation number
             global_eqn = this->node_pt(l)->eqn_number(u_nodal_index);
           }
           if (global_eqn >= 0)
           {
             // Set the global equation number
             global_eqn_number[count] = global_eqn;
             // Set the derivative with respect to the unknown
             du_ddata[count] = psi[l] * hang_weight;
             // Increase the counter
             ++count;
           }
         }
       }
     }
References oomph::Data::eqn_number(), oomph::Node::hanging_pt(), oomph::Node::is_hanging(), m, oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::FiniteElement::shape(), and oomph::NavierStokesEquations< DIM >::u_index_nst().
Referenced by RefineableQAdvectionDiffusionElementWithExternalElement< DIM >::get_dwind_adv_diff_dexternal_element_data().
fill_in_generic_pressure_advection_diffusion_contribution_nst()
template<unsigned DIM> void oomph::RefineableNavierStokesEquations< DIM >::fill_in_generic_pressure_advection_diffusion_contribution_nst (Vector< double > & residuals, DenseMatrix< double > & jacobian, unsigned flag) protected virtual
Compute the residuals for the associated pressure advection diffusion problem. Used by the Fp preconditioner. flag=1(or 0): do (or don't) compute the Jacobian as well.
Reimplemented from oomph::NavierStokesEquations< DIM >.
   {
     // Return immediately if there are no dofs
     if (ndof() == 0) return;
     // Find out how many nodes there are
     unsigned n_node = nnode();
     // Find out how many pressure dofs there are
     unsigned n_pres = this->npres_nst();
     // Find the indices at which the local velocities are stored
     unsigned u_nodal_index[DIM];
     for (unsigned i = 0; i < DIM; i++)
     {
       u_nodal_index[i] = this->u_index_nst(i);
     }
     // Which nodal value represents the pressure? (Negative if pressure
     // is not based on nodal interpolation).
     int p_index = this->p_nodal_index_nst();
     // Local array of booleans that are true if the l-th pressure value is
     // hanging (avoid repeated virtual function calls)
     bool pressure_dof_is_hanging[n_pres];
     // If the pressure is stored at a node
     if (p_index >= 0)
     {
       // Read out whether the pressure is hanging
       for (unsigned l = 0; l < n_pres; ++l)
       {
         pressure_dof_is_hanging[l] = pressure_node_pt(l)->is_hanging(p_index);
       }
     }
     // Otherwise the pressure is not stored at a node and so cannot hang
     else
     {
       // pressure advection diffusion doesn't work for this one!
       throw OomphLibError(
         "Pressure advection diffusion does not work in this case\n",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
       for (unsigned l = 0; l < n_pres; ++l)
       {
         pressure_dof_is_hanging[l] = false;
       }
     }
     // Set up memory for the velocity shape fcts
     Shape psif(n_node);
     DShape dpsidx(n_node, DIM);
     // Set up memory for pressure shape and test functions
     Shape psip(n_pres), testp(n_pres);
     DShape dpsip(n_pres, DIM);
     DShape dtestp(n_pres, DIM);
     // Number of integration points
     unsigned n_intpt = integral_pt()->nweight();
     // Set the Vector to hold local coordinates
     Vector<double> s(DIM);
     // Get Physical Variables from Element
     // Reynolds number must be multiplied by the density ratio
     double scaled_re = this->re() * this->density_ratio();
     // Integers to store the local equations and unknowns
     int local_eqn = 0, local_unknown = 0;
     // Pointers to hang info objects
     HangInfo *hang_info_pt = 0, *hang_info2_pt = 0;
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Assign values of s
       for (unsigned i = 0; i < DIM; i++) s[i] = integral_pt()->knot(ipt, i);
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Call the derivatives of the veloc shape functions
       // (Derivs not needed but they are free)
       double J = this->dshape_eulerian_at_knot(ipt, psif, dpsidx);
       // Call the pressure shape and test functions
       this->dpshape_and_dptest_eulerian_nst(s, psip, dpsip, testp, dtestp);
       // Premultiply the weights and the Jacobian
       double W = w * J;
       // Calculate local values of the pressure and velocity components
       // Allocate
       Vector<double> interpolated_u(DIM, 0.0);
       Vector<double> interpolated_x(DIM, 0.0);
       Vector<double> interpolated_dpdx(DIM, 0.0);
       // Calculate pressure gradient
       for (unsigned l = 0; l < n_pres; l++)
       {
         for (unsigned i = 0; i < DIM; i++)
         {
           interpolated_dpdx[i] += this->p_nst(l) * dpsip(l, i);
         }
       }
       // Calculate velocities
       // Loop over nodes
       for (unsigned l = 0; l < n_node; l++)
       {
         // Loop over directions
         for (unsigned i = 0; i < DIM; i++)
         {
           // Get the nodal value
           double u_value = nodal_value(l, u_nodal_index[i]);
           interpolated_u[i] += u_value * psif[l];
           interpolated_x[i] += nodal_position(l, i) * psif[l];
         }
       }
       // Source function (for validaton only)
       double source = 0.0;
       if (this->Press_adv_diff_source_fct_pt != 0)
       {
         source = this->Press_adv_diff_source_fct_pt(interpolated_x);
       }
       // Number of master nodes and storage for the weight of the shape function
       unsigned n_master = 1;
       double hang_weight = 1.0;
       // Loop over the pressure shape functions
       for (unsigned l = 0; l < n_pres; l++)
       {
         // If the pressure dof is hanging
         if (pressure_dof_is_hanging[l])
         {
           // Pressure dof is hanging so it must be nodal-based
           // Get the hang info object
           hang_info_pt = this->pressure_node_pt(l)->hanging_pt(p_index);
           // Get the number of master nodes from the pressure node
           n_master = hang_info_pt->nmaster();
         }
         // Otherwise the node is its own master
         else
         {
           n_master = 1;
         }
         // Loop over the master nodes
         for (unsigned m = 0; m < n_master; m++)
         {
           // Get the number of the unknown
           // If the pressure dof is hanging
           if (pressure_dof_is_hanging[l])
           {
             // Get the local equation from the master node
             local_eqn =
               this->local_hang_eqn(hang_info_pt->master_node_pt(m), p_index);
             // Get the weight for the node
             hang_weight = hang_info_pt->master_weight(m);
           }
           else
           {
             local_eqn = this->p_local_eqn(l);
             hang_weight = 1.0;
           }
           // If the equation is not pinned
           if (local_eqn >= 0)
           {
             residuals[local_eqn] -= source * testp[l] * W * hang_weight;
             for (unsigned k = 0; k < DIM; k++)
             {
               residuals[local_eqn] +=
                 interpolated_dpdx[k] *
                 (scaled_re * interpolated_u[k] * testp[l] + dtestp(l, k)) * W *
                 hang_weight;
             }
             // Jacobian too?
             if (flag)
             {
               // Number of master nodes and weights
               unsigned n_master2 = 1;
               double hang_weight2 = 1.0;
               // Loop over the pressure shape functions
               for (unsigned l2 = 0; l2 < n_pres; l2++)
               {
                 // If the pressure dof is hanging
                 if (pressure_dof_is_hanging[l2])
                 {
                   hang_info2_pt =
                     this->pressure_node_pt(l2)->hanging_pt(p_index);
                   // Pressure dof is hanging so it must be nodal-based
                   // Get the number of master nodes from the pressure node
                   n_master2 = hang_info2_pt->nmaster();
                 }
                 // Otherwise the node is its own master
                 else
                 {
                   n_master2 = 1;
                 }
                 // Loop over the master nodes
                 for (unsigned m2 = 0; m2 < n_master2; m2++)
                 {
                   // Get the number of the unknown
                   // If the pressure dof is hanging
                   if (pressure_dof_is_hanging[l2])
                   {
                     // Get the unknown from the master node
                     local_unknown = this->local_hang_eqn(
                       hang_info2_pt->master_node_pt(m2), p_index);
                     // Get the weight from the hanging object
                     hang_weight2 = hang_info2_pt->master_weight(m2);
                   }
                   else
                   {
                     local_unknown = this->p_local_eqn(l2);
                     hang_weight2 = 1.0;
                   }
                   // If the unknown is not pinned
                   if (local_unknown >= 0)
                   {
                     if ((int(eqn_number(local_eqn)) !=
                          this->Pinned_fp_pressure_eqn) &&
                         (int(eqn_number(local_unknown)) !=
                          this->Pinned_fp_pressure_eqn))
                     {
                       for (unsigned k = 0; k < DIM; k++)
                       {
                         jacobian(local_eqn, local_unknown) +=
                           dtestp(l2, k) *
                           (scaled_re * interpolated_u[k] * testp[l] +
                            dtestp(l, k)) *
                           W * hang_weight * hang_weight2;
                       }
                     }
                     else
                     {
                       if ((int(eqn_number(local_eqn)) ==
                            this->Pinned_fp_pressure_eqn) &&
                           (int(eqn_number(local_unknown)) ==
                            this->Pinned_fp_pressure_eqn))
                       {
                         jacobian(local_eqn, local_unknown) = 1.0;
                       }
                     }
                   }
                 }
               }
             } /*End of Jacobian calculation*/
           } // End of if not boundary condition
         } // End of loop over master nodes
       } // End of loop over l
     } // end of integration loop
     // Now add boundary contributions from Robin BCs
     unsigned nrobin =
       this->Pressure_advection_diffusion_robin_element_pt.size();
     for (unsigned e = 0; e < nrobin; e++)
     {
       this->Pressure_advection_diffusion_robin_element_pt[e]
         ->fill_in_generic_residual_contribution_fp_press_adv_diff_robin_bc(
           residuals, jacobian, flag);
     }
   }
References DIM, e(), i, int(), J, k, m, m2(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, s, TestProblem::source(), w, and oomph::QuadTreeNames::W.
fill_in_generic_residual_contribution_nst()
template<unsigned DIM> void oomph::RefineableNavierStokesEquations< DIM >::fill_in_generic_residual_contribution_nst (Vector< double > & residuals, DenseMatrix< double > & jacobian, DenseMatrix< double > & mass_matrix, unsigned flag) protected virtual
Add element's contribution to elemental residual vector and/or Jacobian matrix flag=1: compute both flag=0: compute only residual vector
Add element's contribution to the elemental residual vector and/or Jacobian matrix. flag=1: compute both flag=0: compute only residual vector
Reimplemented from oomph::NavierStokesEquations< DIM >.
   {
     // Find out how many nodes there are
     unsigned n_node = nnode();
     // Get continuous time from timestepper of first node
     double time = node_pt(0)->time_stepper_pt()->time_pt()->time();
     // Find out how many pressure dofs there are
     unsigned n_pres = this->npres_nst();
     // Get the indices at which the velocity components are stored
     unsigned u_nodal_index[DIM];
     for (unsigned i = 0; i < DIM; i++)
     {
       u_nodal_index[i] = this->u_index_nst(i);
     }
     // Which nodal value represents the pressure? (Negative if pressure
     // is not based on nodal interpolation).
     int p_index = this->p_nodal_index_nst();
     // Local array of booleans that are true if the l-th pressure value is
     // hanging (avoid repeated virtual function calls)
     bool pressure_dof_is_hanging[n_pres];
     // If the pressure is stored at a node
     if (p_index >= 0)
     {
       // Read out whether the pressure is hanging
       for (unsigned l = 0; l < n_pres; ++l)
       {
         pressure_dof_is_hanging[l] = pressure_node_pt(l)->is_hanging(p_index);
       }
     }
     // Otherwise the pressure is not stored at a node and so cannot hang
     else
     {
       for (unsigned l = 0; l < n_pres; ++l)
       {
         pressure_dof_is_hanging[l] = false;
       }
     }
     // Set up memory for the shape and test functions
     Shape psif(n_node), testf(n_node);
     DShape dpsifdx(n_node, DIM), dtestfdx(n_node, DIM);
     // Set up memory for pressure shape and test functions
     Shape psip(n_pres), testp(n_pres);
     // Set the value of n_intpt
     unsigned n_intpt = integral_pt()->nweight();
     // Set the Vector to hold local coordinates
     Vector<double> s(DIM);
     // Get Physical Variables from Element
     // Reynolds number must be multiplied by the density ratio
     double scaled_re = this->re() * this->density_ratio();
     double scaled_re_st = this->re_st() * this->density_ratio();
     double scaled_re_inv_fr = this->re_invfr() * this->density_ratio();
     double visc_ratio = this->viscosity_ratio();
     Vector<double> G = this->g();
     // Integers that store the local equations and unknowns
     int local_eqn = 0, local_unknown = 0;
     // Pointers to hang info objects
     HangInfo *hang_info_pt = 0, *hang_info2_pt = 0;
     // Local boolean for ALE (or not)
     bool ALE_is_disabled_flag = this->ALE_is_disabled;
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Assign values of s
       for (unsigned i = 0; i < DIM; i++)
       {
         s[i] = integral_pt()->knot(ipt, i);
       }
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Call the derivatives of the shape and test functions
       double J = this->dshape_and_dtest_eulerian_at_knot_nst(
         ipt, psif, dpsifdx, testf, dtestfdx);
       // Call the pressure shape and test functions
       this->pshape_nst(s, psip, testp);
       // Premultiply the weights and the Jacobian
       double W = w * J;
       // Calculate local values of the pressure and velocity components
       //--------------------------------------------------------------
       double interpolated_p = 0.0;
       Vector<double> interpolated_u(DIM, 0.0);
       Vector<double> interpolated_x(DIM, 0.0);
       Vector<double> mesh_veloc(DIM, 0.0);
       Vector<double> dudt(DIM, 0.0);
       DenseMatrix<double> interpolated_dudx(DIM, DIM, 0.0);
       // Calculate pressure
       for (unsigned l = 0; l < n_pres; l++)
       {
         interpolated_p += this->p_nst(l) * psip[l];
       }
       // Calculate velocities and derivatives
       // Loop over nodes
       for (unsigned l = 0; l < n_node; l++)
       {
         // Loop over directions
         for (unsigned i = 0; i < DIM; i++)
         {
           // Get the nodal value
           double u_value = this->nodal_value(l, u_nodal_index[i]);
           interpolated_u[i] += u_value * psif[l];
           interpolated_x[i] += this->nodal_position(l, i) * psif[l];
           dudt[i] += this->du_dt_nst(l, i) * psif[l];
           // Loop over derivative directions for velocity gradients
           for (unsigned j = 0; j < DIM; j++)
           {
             interpolated_dudx(i, j) += u_value * dpsifdx(l, j);
           }
         }
       }
       if (!ALE_is_disabled_flag)
       {
         // Loop over nodes
         for (unsigned l = 0; l < n_node; l++)
         {
           // Loop over directions
           for (unsigned i = 0; i < DIM; i++)
           {
             mesh_veloc[i] += this->dnodal_position_dt(l, i) * psif[l];
           }
         }
       }
       // Get the user-defined body force terms
       Vector<double> body_force(DIM);
       this->get_body_force_nst(time, ipt, s, interpolated_x, body_force);
       // Get the user-defined source function
       double source = this->get_source_nst(time, ipt, interpolated_x);
       // MOMENTUM EQUATIONS
       //==================
       // Number of master nodes and storage for the weight of the shape function
       unsigned n_master = 1;
       double hang_weight = 1.0;
       // Loop over the nodes for the test functions/equations
       //----------------------------------------------------
       for (unsigned l = 0; l < n_node; l++)
       {
         // Local boolean to indicate whether the node is hanging
         bool is_node_hanging = node_pt(l)->is_hanging();
         // If the node is hanging
         if (is_node_hanging)
         {
           hang_info_pt = node_pt(l)->hanging_pt();
           // Read out number of master nodes from hanging data
           n_master = hang_info_pt->nmaster();
         }
         // Otherwise the node is its own master
         else
         {
           n_master = 1;
         }
         // Loop over the master nodes
         for (unsigned m = 0; m < n_master; m++)
         {
           // Loop over velocity components for equations
           for (unsigned i = 0; i < DIM; i++)
           {
             // Get the equation number
             // If the node is hanging
             if (is_node_hanging)
             {
               // Get the equation number from the master node
               local_eqn = this->local_hang_eqn(hang_info_pt->master_node_pt(m),
                                                u_nodal_index[i]);
               // Get the hang weight from the master node
               hang_weight = hang_info_pt->master_weight(m);
             }
             // If the node is not hanging
             else
             {
               // Local equation number
               local_eqn = this->nodal_local_eqn(l, u_nodal_index[i]);
               // Node contributes with full weight
               hang_weight = 1.0;
             }
             // If it's not a boundary condition...
             if (local_eqn >= 0)
             {
               // Temporary variable to hold the residuals
               double sum = 0.0;
               // Add the user-defined body force terms
               sum += body_force[i];
               // Add the gravitational body force term
               sum += scaled_re_inv_fr * G[i];
               // Add in the inertial term
               sum -= scaled_re_st * dudt[i];
               // Convective terms, including mesh velocity
               for (unsigned k = 0; k < DIM; k++)
               {
                 double tmp = scaled_re * interpolated_u[k];
                 if (!ALE_is_disabled_flag)
                 {
                   tmp -= scaled_re_st * mesh_veloc[k];
                 }
                 sum -= tmp * interpolated_dudx(i, k);
               }
               // Add the pressure gradient term
               sum = (sum * testf[l] + interpolated_p * dtestfdx(l, i)) * W *
                     hang_weight;
               // Add in the stress tensor terms
               // The viscosity ratio needs to go in here to ensure
               // continuity of normal stress is satisfied even in flows
               // with zero pressure gradient!
               for (unsigned k = 0; k < DIM; k++)
               {
                 sum -= visc_ratio *
                        (interpolated_dudx(i, k) +
                         this->Gamma[i] * interpolated_dudx(k, i)) *
                        dtestfdx(l, k) * W * hang_weight;
               }
               // Add contribution
               residuals[local_eqn] += sum;
               // CALCULATE THE JACOBIAN
               if (flag)
               {
                 // Number of master nodes and weights
                 unsigned n_master2 = 1;
                 double hang_weight2 = 1.0;
                 // Loop over the velocity nodes for columns
                 for (unsigned l2 = 0; l2 < n_node; l2++)
                 {
                   // Local boolean to indicate whether the node is hanging
                   bool is_node2_hanging = node_pt(l2)->is_hanging();
                   // If the node is hanging
                   if (is_node2_hanging)
                   {
                     hang_info2_pt = node_pt(l2)->hanging_pt();
                     // Read out number of master nodes from hanging data
                     n_master2 = hang_info2_pt->nmaster();
                   }
                   // Otherwise the node is its own master
                   else
                   {
                     n_master2 = 1;
                   }
                   // Loop over the master nodes
                   for (unsigned m2 = 0; m2 < n_master2; m2++)
                   {
                     // Loop over the velocity components
                     for (unsigned i2 = 0; i2 < DIM; i2++)
                     {
                       // Get the number of the unknown
                       // If the node is hanging
                       if (is_node2_hanging)
                       {
                         // Get the equation number from the master node
                         local_unknown = this->local_hang_eqn(
                           hang_info2_pt->master_node_pt(m2), u_nodal_index[i2]);
                         // Get the hang weights
                         hang_weight2 = hang_info2_pt->master_weight(m2);
                       }
                       else
                       {
                         local_unknown =
                           this->nodal_local_eqn(l2, u_nodal_index[i2]);
                         hang_weight2 = 1.0;
                       }
                       // If the unknown is non-zero
                       if (local_unknown >= 0)
                       {
                         // Add contribution to Elemental Matrix
                         jacobian(local_eqn, local_unknown) -=
                           visc_ratio * this->Gamma[i] * dpsifdx(l2, i) *
                           dtestfdx(l, i2) * W * hang_weight * hang_weight2;
                         // Now add in the inertial terms
                         jacobian(local_eqn, local_unknown) -=
                           scaled_re * psif[l2] * interpolated_dudx(i, i2) *
                           testf[l] * W * hang_weight * hang_weight2;
                         // Extra diagonal components if i2=i
                         if (i2 == i)
{
                           // Mass matrix entries
                           // Again note the positive sign because the mass
                           // matrix is taken on the other side of the equation
                           if (flag == 2)
{
                             mass_matrix(local_eqn, local_unknown) +=
                               scaled_re_st * psif[l2] * testf[l] * W *
                               hang_weight * hang_weight2;
                           }
                           // du/dt term
                           jacobian(local_eqn, local_unknown) -=
                             scaled_re_st *
                             node_pt(l2)->time_stepper_pt()->weight(1, 0) *
                             psif[l2] * testf[l] * W * hang_weight *
                             hang_weight2;
                           // Extra advective terms
                           for (unsigned k = 0; k < DIM; k++)
{
                             double tmp = scaled_re * interpolated_u[k];
                             if (!ALE_is_disabled_flag)
{
                               tmp -= scaled_re_st * mesh_veloc[k];
                             }
                             jacobian(local_eqn, local_unknown) -=
                               tmp * dpsifdx(l2, k) * testf[l] * W *
                               hang_weight * hang_weight2;
                           }
                           // Extra viscous terms
                           for (unsigned k = 0; k < DIM; k++)
{
                             jacobian(local_eqn, local_unknown) -=
                               visc_ratio * dpsifdx(l2, k) * dtestfdx(l, k) * W *
                               hang_weight * hang_weight2;
                           }
                         }
                       }
                     }
                   }
                 }
                 // Loop over the pressure shape functions
                 for (unsigned l2 = 0; l2 < n_pres; l2++)
                 {
                   // If the pressure dof is hanging
                   if (pressure_dof_is_hanging[l2])
                   {
                     hang_info2_pt =
                       this->pressure_node_pt(l2)->hanging_pt(p_index);
                     // Pressure dof is hanging so it must be nodal-based
                     // Get the number of master nodes from the pressure node
                     n_master2 = hang_info2_pt->nmaster();
                   }
                   // Otherwise the node is its own master
                   else
                   {
                     n_master2 = 1;
                   }
                   // Loop over the master nodes
                   for (unsigned m2 = 0; m2 < n_master2; m2++)
                   {
                     // Get the number of the unknown
                     // If the pressure dof is hanging
                     if (pressure_dof_is_hanging[l2])
                     {
                       // Get the unknown from the master node
                       local_unknown = this->local_hang_eqn(
                         hang_info2_pt->master_node_pt(m2), p_index);
                       // Get the weight from the hanging object
                       hang_weight2 = hang_info2_pt->master_weight(m2);
                     }
                     else
                     {
                       local_unknown = this->p_local_eqn(l2);
                       hang_weight2 = 1.0;
                     }
                     // If the unknown is not pinned
                     if (local_unknown >= 0)
                     {
                       jacobian(local_eqn, local_unknown) +=
                         psip[l2] * dtestfdx(l, i) * W * hang_weight *
                         hang_weight2;
                     }
                   }
                 }
               } // End of Jacobian calculation
             } // End of if not boundary condition statement
           } // End of loop over components of non-hanging node
         } // End of loop over master nodes
       } // End of loop over nodes for equations
       // CONTINUITY EQUATION
       //===================
       // Loop over the pressure shape functions
       for (unsigned l = 0; l < n_pres; l++)
       {
         // If the pressure dof is hanging
         if (pressure_dof_is_hanging[l])
         {
           // Pressure dof is hanging so it must be nodal-based
           // Get the hang info object
           hang_info_pt = this->pressure_node_pt(l)->hanging_pt(p_index);
           // Get the number of master nodes from the pressure node
           n_master = hang_info_pt->nmaster();
         }
         // Otherwise the node is its own master
         else
         {
           n_master = 1;
         }
         // Loop over the master nodes
         for (unsigned m = 0; m < n_master; m++)
         {
           // Get the number of the unknown
           // If the pressure dof is hanging
           if (pressure_dof_is_hanging[l])
           {
             // Get the local equation from the master node
             local_eqn =
               this->local_hang_eqn(hang_info_pt->master_node_pt(m), p_index);
             // Get the weight for the node
             hang_weight = hang_info_pt->master_weight(m);
           }
           else
           {
             local_eqn = this->p_local_eqn(l);
             hang_weight = 1.0;
           }
           // If the equation is not pinned
           if (local_eqn >= 0)
           {
             // Source term
             residuals[local_eqn] -= source * testp[l] * W * hang_weight;
             // Loop over velocity components
             for (unsigned k = 0; k < DIM; k++)
             {
               residuals[local_eqn] +=
                 interpolated_dudx(k, k) * testp[l] * W * hang_weight;
             }
             // CALCULATE THE JACOBIAN
             if (flag)
             {
               unsigned n_master2 = 1;
               double hang_weight2 = 1.0;
               // Loop over the velocity nodes for columns
               for (unsigned l2 = 0; l2 < n_node; l2++)
               {
                 // Local boolean to indicate whether the node is hanging
                 bool is_node2_hanging = node_pt(l2)->is_hanging();
                 // If the node is hanging
                 if (is_node2_hanging)
                 {
                   hang_info2_pt = node_pt(l2)->hanging_pt();
                   // Read out number of master nodes from hanging data
                   n_master2 = hang_info2_pt->nmaster();
                 }
                 // Otherwise the node is its own master
                 else
                 {
                   n_master2 = 1;
                 }
                 // Loop over the master nodes
                 for (unsigned m2 = 0; m2 < n_master2; m2++)
                 {
                   // Loop over the velocity components
                   for (unsigned i2 = 0; i2 < DIM; i2++)
                   {
                     // Get the number of the unknown
                     // If the node is hanging
                     if (is_node2_hanging)
                     {
                       // Get the equation number from the master node
                       local_unknown = this->local_hang_eqn(
                         hang_info2_pt->master_node_pt(m2), u_nodal_index[i2]);
                       hang_weight2 = hang_info2_pt->master_weight(m2);
                     }
                     else
                     {
                       local_unknown =
                         this->nodal_local_eqn(l2, u_nodal_index[i2]);
                       hang_weight2 = 1.0;
                     }
                     // If the unknown is not pinned
                     if (local_unknown >= 0)
                     {
                       jacobian(local_eqn, local_unknown) +=
                         dpsifdx(l2, i2) * testp[l] * W * hang_weight *
                         hang_weight2;
                     }
                   }
                 }
               }
               // NO PRESSURE CONTRIBUTION TO THE JACOBIAN
             } // End of jacobian calculation
           }
         }
       } // End of loop over pressure variables
     } // End of loop over integration points
   }
References oomph::ALE_is_disabled, Global_Parameters::body_force(), DIM, G, GlobalPhysicalVariables::Gamma, i, J, j, k, m, m2(), oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), s, TestProblem::source(), tmp, w, and oomph::QuadTreeNames::W.
further_build()
template<unsigned DIM> void oomph::RefineableNavierStokesEquations< DIM >::further_build () inline virtual
Further build, pass the pointers down to the sons.
Reimplemented from oomph::RefineableElement.
Reimplemented in oomph::RefineableQCrouzeixRaviartElement< DIM >, oomph::RefineableQCrouzeixRaviartElement< 2 >, oomph::RefineableQCrouzeixRaviartElement< DIM >, oomph::RefineableQCrouzeixRaviartElement< 2 >, oomph::PRefineableQCrouzeixRaviartElement< DIM >, oomph::RefineableQCrouzeixRaviartElement< DIM >, oomph::RefineableQCrouzeixRaviartElement< 2 >, oomph::PRefineableQCrouzeixRaviartElement< DIM >, and oomph::PRefineableQCrouzeixRaviartElement< DIM >.
     {
       // Find the father element
       RefineableNavierStokesEquations<DIM>* cast_father_element_pt =
         dynamic_cast<RefineableNavierStokesEquations<DIM>*>(
           this->father_element_pt());
       // Set the viscosity ratio pointer
       this->Viscosity_Ratio_pt = cast_father_element_pt->viscosity_ratio_pt();
       // Set the density ratio pointer
       this->Density_Ratio_pt = cast_father_element_pt->density_ratio_pt();
       // Set pointer to global Reynolds number
       this->Re_pt = cast_father_element_pt->re_pt();
       // Set pointer to global Reynolds number x Strouhal number (=Womersley)
       this->ReSt_pt = cast_father_element_pt->re_st_pt();
       // Set pointer to global Reynolds number x inverse Froude number
       this->ReInvFr_pt = cast_father_element_pt->re_invfr_pt();
       // Set pointer to global gravity Vector
       this->G_pt = cast_father_element_pt->g_pt();
       // Set pointer to body force function
       this->Body_force_fct_pt = cast_father_element_pt->body_force_fct_pt();
       // Set pointer to volumetric source function
       this->Source_fct_pt = cast_father_element_pt->source_fct_pt();
       // Set the ALE flag
       this->ALE_is_disabled = cast_father_element_pt->ALE_is_disabled;
     }
References oomph::NavierStokesEquations< DIM >::ALE_is_disabled, oomph::NavierStokesEquations< DIM >::Body_force_fct_pt, oomph::NavierStokesEquations< DIM >::body_force_fct_pt(), oomph::NavierStokesEquations< DIM >::Density_Ratio_pt, oomph::NavierStokesEquations< DIM >::density_ratio_pt(), oomph::RefineableElement::father_element_pt(), oomph::NavierStokesEquations< DIM >::G_pt, oomph::NavierStokesEquations< DIM >::g_pt(), oomph::NavierStokesEquations< DIM >::re_invfr_pt(), oomph::NavierStokesEquations< DIM >::Re_pt, oomph::NavierStokesEquations< DIM >::re_pt(), oomph::NavierStokesEquations< DIM >::re_st_pt(), oomph::NavierStokesEquations< DIM >::ReInvFr_pt, oomph::NavierStokesEquations< DIM >::ReSt_pt, oomph::NavierStokesEquations< DIM >::Source_fct_pt, oomph::NavierStokesEquations< DIM >::source_fct_pt(), oomph::NavierStokesEquations< DIM >::Viscosity_Ratio_pt, and oomph::NavierStokesEquations< DIM >::viscosity_ratio_pt().
Referenced by oomph::PRefineableQCrouzeixRaviartElement< DIM >::further_build().
get_dresidual_dnodal_coordinates()
template<unsigned DIM> void oomph::RefineableNavierStokesEquations< DIM >::get_dresidual_dnodal_coordinates (RankThreeTensor< double > & dresidual_dnodal_coordinates) protected virtual
Compute derivatives of elemental residual vector with respect to nodal coordinates. Overwrites default implementation in FiniteElement base class. dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij}
Compute derivatives of elemental residual vector with respect to nodal coordinates. dresidual_dnodal_coordinates(l,i,j) = d res(l) / dX_{ij} Overloads the FD-based version in the FE base class.
Reimplemented from oomph::RefineableElement.
   {
     // Return immediately if there are no dofs
     if (ndof() == 0)
     {
       return;
     }
     // Determine number of nodes in element
     const unsigned n_node = nnode();
     // Get continuous time from timestepper of first node
     double time = node_pt(0)->time_stepper_pt()->time_pt()->time();
     // Determine number of pressure dofs in element
     const unsigned n_pres = this->npres_nst();
     // Find the indices at which the local velocities are stored
     unsigned u_nodal_index[DIM];
     for (unsigned i = 0; i < DIM; i++)
     {
       u_nodal_index[i] = this->u_index_nst(i);
     }
     // Which nodal value represents the pressure? (Negative if pressure
     // is not based on nodal interpolation).
     const int p_index = this->p_nodal_index_nst();
     // Local array of booleans that are true if the l-th pressure value is
     // hanging (avoid repeated virtual function calls)
     bool pressure_dof_is_hanging[n_pres];
     // If the pressure is stored at a node
     if (p_index >= 0)
     {
       // Read out whether the pressure is hanging
       for (unsigned l = 0; l < n_pres; ++l)
       {
         pressure_dof_is_hanging[l] = pressure_node_pt(l)->is_hanging(p_index);
       }
     }
     // Otherwise the pressure is not stored at a node and so cannot hang
     else
     {
       for (unsigned l = 0; l < n_pres; ++l)
       {
         pressure_dof_is_hanging[l] = false;
       }
     }
     // Set up memory for the shape and test functions
     Shape psif(n_node), testf(n_node);
     DShape dpsifdx(n_node, DIM), dtestfdx(n_node, DIM);
     // Set up memory for pressure shape and test functions
     Shape psip(n_pres), testp(n_pres);
     // Determine number of shape controlling nodes
     const unsigned n_shape_controlling_node = nshape_controlling_nodes();
     // Deriatives of shape fct derivatives w.r.t. nodal coords
     RankFourTensor<double> d_dpsifdx_dX(
       DIM, n_shape_controlling_node, n_node, DIM);
     RankFourTensor<double> d_dtestfdx_dX(
       DIM, n_shape_controlling_node, n_node, DIM);
     // Derivative of Jacobian of mapping w.r.t. to nodal coords
     DenseMatrix<double> dJ_dX(DIM, n_shape_controlling_node);
     // Derivatives of derivative of u w.r.t. nodal coords
     RankFourTensor<double> d_dudx_dX(DIM, n_shape_controlling_node, DIM, DIM);
     // Derivatives of nodal velocities w.r.t. nodal coords:
     // Assumption: Interaction only local via no-slip so
     // X_ij only affects U_ij.
     DenseMatrix<double> d_U_dX(DIM, n_shape_controlling_node, 0.0);
     // Determine the number of integration points
     const unsigned n_intpt = integral_pt()->nweight();
     // Vector to hold local coordinates
     Vector<double> s(DIM);
     // Get physical variables from element
     // (Reynolds number must be multiplied by the density ratio)
     double scaled_re = this->re() * this->density_ratio();
     double scaled_re_st = this->re_st() * this->density_ratio();
     double scaled_re_inv_fr = this->re_invfr() * this->density_ratio();
     double visc_ratio = this->viscosity_ratio();
     Vector<double> G = this->g();
     // FD step
     double eps_fd = GeneralisedElement::Default_fd_jacobian_step;
     // Pre-compute derivatives of nodal velocities w.r.t. nodal coords:
     // Assumption: Interaction only local via no-slip so
     // X_ij only affects U_ij.
     bool element_has_node_with_aux_node_update_fct = false;
     std::map<Node*, unsigned> local_shape_controlling_node_lookup =
       shape_controlling_node_lookup();
     // FD loop over shape-controlling nodes
     for (std::map<Node*, unsigned>::iterator it =
            local_shape_controlling_node_lookup.begin();
          it != local_shape_controlling_node_lookup.end();
          it++)
     {
       // Get node
       Node* nod_pt = it->first;
       // Get its number
       unsigned q = it->second;
       // Only compute if there's a node-update fct involved
       if (nod_pt->has_auxiliary_node_update_fct_pt())
       {
         element_has_node_with_aux_node_update_fct = true;
         // Current nodal velocity
         Vector<double> u_ref(DIM);
         for (unsigned i = 0; i < DIM; i++)
         {
           u_ref[i] = *(nod_pt->value_pt(u_nodal_index[i]));
         }
         // FD
         for (unsigned p = 0; p < DIM; p++)
         {
           // Make backup
           double backup = nod_pt->x(p);
           // Do FD step. No node update required as we're
           // attacking the coordinate directly...
           nod_pt->x(p) += eps_fd;
           // Do auxiliary node update (to apply no slip)
           nod_pt->perform_auxiliary_node_update_fct();
           // Evaluate
           d_U_dX(p, q) =
             (*(nod_pt->value_pt(u_nodal_index[p])) - u_ref[p]) / eps_fd;
           // Reset
           nod_pt->x(p) = backup;
           // Do auxiliary node update (to apply no slip)
           nod_pt->perform_auxiliary_node_update_fct();
         }
       }
     }
     // Integer to store the local equation number
     int local_eqn = 0;
     // Pointers to hang info object
     HangInfo* hang_info_pt = 0;
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Assign values of s
       for (unsigned i = 0; i < DIM; i++)
       {
         s[i] = integral_pt()->knot(ipt, i);
       }
       // Get the integral weight
       const double w = integral_pt()->weight(ipt);
       // Call the derivatives of the shape and test functions
       const double J =
         this->dshape_and_dtest_eulerian_at_knot_nst(ipt,
                                                     psif,
                                                     dpsifdx,
                                                     d_dpsifdx_dX,
                                                     testf,
                                                     dtestfdx,
                                                     d_dtestfdx_dX,
                                                     dJ_dX);
       // Call the pressure shape and test functions
       this->pshape_nst(s, psip, testp);
       // Calculate local values of the pressure and velocity components
       // Allocate
       double interpolated_p = 0.0;
       Vector<double> interpolated_u(DIM, 0.0);
       Vector<double> interpolated_x(DIM, 0.0);
       Vector<double> mesh_velocity(DIM, 0.0);
       Vector<double> dudt(DIM, 0.0);
       DenseMatrix<double> interpolated_dudx(DIM, DIM, 0.0);
       // Calculate pressure
       for (unsigned l = 0; l < n_pres; l++)
       {
         interpolated_p += this->p_nst(l) * psip[l];
       }
       // Calculate velocities and derivatives:
       // Loop over nodes
       for (unsigned l = 0; l < n_node; l++)
       {
         // Loop over directions
         for (unsigned i = 0; i < DIM; i++)
         {
           // Get the nodal value
           const double u_value = nodal_value(l, u_nodal_index[i]);
           interpolated_u[i] += u_value * psif[l];
           interpolated_x[i] += nodal_position(l, i) * psif[l];
           dudt[i] += this->du_dt_nst(l, i) * psif[l];
           // Loop over derivative directions
           for (unsigned j = 0; j < DIM; j++)
           {
             interpolated_dudx(i, j) += u_value * dpsifdx(l, j);
           }
         }
       }
       if (!this->ALE_is_disabled)
       {
         // Loop over nodes
         for (unsigned l = 0; l < n_node; l++)
         {
           // Loop over directions
           for (unsigned i = 0; i < DIM; i++)
           {
             mesh_velocity[i] += this->dnodal_position_dt(l, i) * psif[l];
           }
         }
       }
       // Calculate derivative of du_i/dx_k w.r.t. nodal positions X_{pq}
       // Loop over shape-controlling nodes
       for (unsigned q = 0; q < n_shape_controlling_node; q++)
       {
         // Loop over coordinate directions
         for (unsigned p = 0; p < DIM; p++)
         {
           for (unsigned i = 0; i < DIM; i++)
           {
             for (unsigned k = 0; k < DIM; k++)
             {
               double aux = 0.0;
               for (unsigned j = 0; j < n_node; j++)
               {
                 aux +=
                   nodal_value(j, u_nodal_index[i]) * d_dpsifdx_dX(p, q, j, k);
               }
               d_dudx_dX(p, q, i, k) = aux;
             }
           }
         }
       }
       // Get weight of actual nodal position/value in computation of mesh
       // velocity from positional/value time stepper
       const double pos_time_weight =
         node_pt(0)->position_time_stepper_pt()->weight(1, 0);
       const double val_time_weight =
         node_pt(0)->time_stepper_pt()->weight(1, 0);
       // Get the user-defined body force terms
       Vector<double> body_force(DIM);
       this->get_body_force_nst(time, ipt, s, interpolated_x, body_force);
       // Get the user-defined source function
       const double source = this->get_source_nst(time, ipt, interpolated_x);
       // Get gradient of body force function
       DenseMatrix<double> d_body_force_dx(DIM, DIM, 0.0);
       this->get_body_force_gradient_nst(
         time, ipt, s, interpolated_x, d_body_force_dx);
       // Get gradient of source function
       Vector<double> source_gradient(DIM, 0.0);
       this->get_source_gradient_nst(time, ipt, interpolated_x, source_gradient);
       // Assemble shape derivatives
       //---------------------------
       // MOMENTUM EQUATIONS
       // ------------------
       // Number of master nodes and storage for the weight of the shape function
       unsigned n_master = 1;
       double hang_weight = 1.0;
       // Loop over the test functions
       for (unsigned l = 0; l < n_node; l++)
       {
         // Local boolean to indicate whether the node is hanging
         bool is_node_hanging = node_pt(l)->is_hanging();
         // If the node is hanging
         if (is_node_hanging)
         {
           hang_info_pt = node_pt(l)->hanging_pt();
           // Read out number of master nodes from hanging data
           n_master = hang_info_pt->nmaster();
         }
         // Otherwise the node is its own master
         else
         {
           n_master = 1;
         }
         // Loop over the master nodes
         for (unsigned m = 0; m < n_master; m++)
         {
           // Loop over coordinate directions
           for (unsigned i = 0; i < DIM; i++)
           {
             // Get the equation number
             // If the node is hanging
             if (is_node_hanging)
             {
               // Get the equation number from the master node
               local_eqn = this->local_hang_eqn(hang_info_pt->master_node_pt(m),
                                                u_nodal_index[i]);
               // Get the hang weight from the master node
               hang_weight = hang_info_pt->master_weight(m);
             }
             // If the node is not hanging
             else
             {
               // Local equation number
               local_eqn = this->nodal_local_eqn(l, u_nodal_index[i]);
               // Node contributes with full weight
               hang_weight = 1.0;
             }
             // IF it's not a boundary condition
             if (local_eqn >= 0)
             {
               // Loop over coordinate directions
               for (unsigned p = 0; p < DIM; p++)
               {
                 // Loop over shape controlling nodes
                 for (unsigned q = 0; q < n_shape_controlling_node; q++)
                 {
                   // Residual x deriv of Jacobian
                   // ----------------------------
                   // Add the user-defined body force terms
                   double sum = body_force[i] * testf[l];
                   // Add the gravitational body force term
                   sum += scaled_re_inv_fr * testf[l] * G[i];
                   // Add the pressure gradient term
                   sum += interpolated_p * dtestfdx(l, i);
                   // Add in the stress tensor terms
                   // The viscosity ratio needs to go in here to ensure
                   // continuity of normal stress is satisfied even in flows
                   // with zero pressure gradient!
                   for (unsigned k = 0; k < DIM; k++)
                   {
                     sum -= visc_ratio *
                            (interpolated_dudx(i, k) +
                             this->Gamma[i] * interpolated_dudx(k, i)) *
                            dtestfdx(l, k);
                   }
                   // Add in the inertial terms
                   // du/dt term
                   sum -= scaled_re_st * dudt[i] * testf[l];
                   // Convective terms, including mesh velocity
                   for (unsigned k = 0; k < DIM; k++)
                   {
                     double tmp = scaled_re * interpolated_u[k];
                     if (!this->ALE_is_disabled)
                     {
                       tmp -= scaled_re_st * mesh_velocity[k];
                     }
                     sum -= tmp * interpolated_dudx(i, k) * testf[l];
                   }
                   // Multiply throsugh by deriv of Jacobian and integration
                   // weight
                   dresidual_dnodal_coordinates(local_eqn, p, q) +=
                     sum * dJ_dX(p, q) * w * hang_weight;
                   // Derivative of residual x Jacobian
                   // ---------------------------------
                   // Body force
                   sum = d_body_force_dx(i, p) * psif(q) * testf(l);
                   // Pressure gradient term
                   sum += interpolated_p * d_dtestfdx_dX(p, q, l, i);
                   // Viscous term
                   for (unsigned k = 0; k < DIM; k++)
                   {
                     sum -=
                       visc_ratio * ((interpolated_dudx(i, k) +
                                      this->Gamma[i] * interpolated_dudx(k, i)) *
                                       d_dtestfdx_dX(p, q, l, k) +
                                     (d_dudx_dX(p, q, i, k) +
                                      this->Gamma[i] * d_dudx_dX(p, q, k, i)) *
                                       dtestfdx(l, k));
                   }
                   // Convective terms, including mesh velocity
                   for (unsigned k = 0; k < DIM; k++)
                   {
                     double tmp = scaled_re * interpolated_u[k];
                     if (!this->ALE_is_disabled)
                     {
                       tmp -= scaled_re_st * mesh_velocity[k];
                     }
                     sum -= tmp * d_dudx_dX(p, q, i, k) * testf(l);
                   }
                   if (!this->ALE_is_disabled)
                   {
                     sum += scaled_re_st * pos_time_weight * psif(q) *
                            interpolated_dudx(i, p) * testf(l);
                   }
                   // Multiply through by Jacobian and integration weight
                   dresidual_dnodal_coordinates(local_eqn, p, q) +=
                     sum * J * w * hang_weight;
                 } // End of loop over shape controlling nodes q
               } // End of loop over coordinate directions p
               // Derivs w.r.t. to nodal velocities
               // ---------------------------------
               if (element_has_node_with_aux_node_update_fct)
               {
                 // Loop over local nodes
                 for (unsigned q_local = 0; q_local < n_node; q_local++)
                 {
                   // Number of master nodes and storage for the weight of
                   // the shape function
                   unsigned n_master2 = 1;
                   double hang_weight2 = 1.0;
                   HangInfo* hang_info2_pt = 0;
                   // Local boolean to indicate whether the node is hanging
                   bool is_node_hanging2 = node_pt(q_local)->is_hanging();
                   Node* actual_shape_controlling_node_pt = node_pt(q_local);
                   // If the node is hanging
                   if (is_node_hanging2)
                   {
                     hang_info2_pt = node_pt(q_local)->hanging_pt();
                     // Read out number of master nodes from hanging data
                     n_master2 = hang_info2_pt->nmaster();
                   }
                   // Otherwise the node is its own master
                   else
                   {
                     n_master2 = 1;
                   }
                   // Loop over the master nodes
                   for (unsigned mm = 0; mm < n_master2; mm++)
                   {
                     if (is_node_hanging2)
                     {
                       actual_shape_controlling_node_pt =
                         hang_info2_pt->master_node_pt(mm);
                       hang_weight2 = hang_info2_pt->master_weight(mm);
                     }
                     // Find the corresponding number
                     unsigned q = local_shape_controlling_node_lookup
                       [actual_shape_controlling_node_pt];
                     // Loop over coordinate directions
                     for (unsigned p = 0; p < DIM; p++)
                     {
                       double sum = -visc_ratio * this->Gamma[i] *
                                      dpsifdx(q_local, i) * dtestfdx(l, p) -
                                    scaled_re * psif(q_local) *
                                      interpolated_dudx(i, p) * testf(l);
                       if (i == p)
                       {
                         sum -= scaled_re_st * val_time_weight * psif(q_local) *
                                testf(l);
                         for (unsigned k = 0; k < DIM; k++)
{
                           sum -=
                             visc_ratio * dpsifdx(q_local, k) * dtestfdx(l, k);
                           double tmp = scaled_re * interpolated_u[k];
                           if (!this->ALE_is_disabled)
{
                             tmp -= scaled_re_st * mesh_velocity[k];
                           }
                           sum -= tmp * dpsifdx(q_local, k) * testf(l);
                         }
                       }
                       dresidual_dnodal_coordinates(local_eqn, p, q) +=
                         sum * d_U_dX(p, q) * J * w * hang_weight * hang_weight2;
                     }
                   } // End of loop over master nodes
                 } // End of loop over local nodes
               } // End of if(element_has_node_with_aux_node_update_fct)
             } // local_eqn>=0
           }
         }
       } // End of loop over test functions
       // CONTINUITY EQUATION
       // -------------------
       // Loop over the shape functions
       for (unsigned l = 0; l < n_pres; l++)
       {
         // If the pressure dof is hanging
         if (pressure_dof_is_hanging[l])
         {
           // Pressure dof is hanging so it must be nodal-based
           // Get the hang info object
           hang_info_pt = this->pressure_node_pt(l)->hanging_pt(p_index);
           // Get the number of master nodes from the pressure node
           n_master = hang_info_pt->nmaster();
         }
         // Otherwise the node is its own master
         else
         {
           n_master = 1;
         }
         // Loop over the master nodes
         for (unsigned m = 0; m < n_master; m++)
         {
           // Get the number of the unknown
           // If the pressure dof is hanging
           if (pressure_dof_is_hanging[l])
           {
             // Get the local equation from the master node
             local_eqn =
               this->local_hang_eqn(hang_info_pt->master_node_pt(m), p_index);
             // Get the weight for the node
             hang_weight = hang_info_pt->master_weight(m);
           }
           else
           {
             local_eqn = this->p_local_eqn(l);
             hang_weight = 1.0;
           }
           // If not a boundary conditions
           if (local_eqn >= 0)
           {
             // Loop over coordinate directions
             for (unsigned p = 0; p < DIM; p++)
             {
               // Loop over nodes
               for (unsigned q = 0; q < n_shape_controlling_node; q++)
               {
                 // Residual x deriv of Jacobian
                 //-----------------------------
                 // Source term
                 double aux = -source;
                 // Loop over velocity components
                 for (unsigned k = 0; k < DIM; k++)
                 {
                   aux += interpolated_dudx(k, k);
                 }
                 // Multiply through by deriv of Jacobian and integration weight
                 dresidual_dnodal_coordinates(local_eqn, p, q) +=
                   aux * dJ_dX(p, q) * testp[l] * w * hang_weight;
                 // Derivative of residual x Jacobian
                 // ---------------------------------
                 // Loop over velocity components
                 aux = -source_gradient[p] * psif(q);
                 for (unsigned k = 0; k < DIM; k++)
                 {
                   aux += d_dudx_dX(p, q, k, k);
                 }
                 // Multiply through by Jacobian and integration weight
                 dresidual_dnodal_coordinates(local_eqn, p, q) +=
                   aux * testp[l] * J * w * hang_weight;
               }
             }
             // Derivs w.r.t. to nodal velocities
             // ---------------------------------
             if (element_has_node_with_aux_node_update_fct)
             {
               // Loop over local nodes
               for (unsigned q_local = 0; q_local < n_node; q_local++)
               {
                 // Number of master nodes and storage for the weight of
                 // the shape function
                 unsigned n_master2 = 1;
                 double hang_weight2 = 1.0;
                 HangInfo* hang_info2_pt = 0;
                 // Local boolean to indicate whether the node is hanging
                 bool is_node_hanging2 = node_pt(q_local)->is_hanging();
                 Node* actual_shape_controlling_node_pt = node_pt(q_local);
                 // If the node is hanging
                 if (is_node_hanging2)
                 {
                   hang_info2_pt = node_pt(q_local)->hanging_pt();
                   // Read out number of master nodes from hanging data
                   n_master2 = hang_info2_pt->nmaster();
                 }
                 // Otherwise the node is its own master
                 else
                 {
                   n_master2 = 1;
                 }
                 // Loop over the master nodes
                 for (unsigned mm = 0; mm < n_master2; mm++)
                 {
                   if (is_node_hanging2)
                   {
                     actual_shape_controlling_node_pt =
                       hang_info2_pt->master_node_pt(mm);
                     hang_weight2 = hang_info2_pt->master_weight(mm);
                   }
                   // Find the corresponding number
                   unsigned q = local_shape_controlling_node_lookup
                     [actual_shape_controlling_node_pt];
                   // Loop over coordinate directions
                   for (unsigned p = 0; p < DIM; p++)
                   {
                     double aux = dpsifdx(q_local, p) * testp(l);
                     dresidual_dnodal_coordinates(local_eqn, p, q) +=
                       aux * d_U_dX(p, q) * J * w * hang_weight * hang_weight2;
                   }
                 } // End of loop over (mm) master nodes
               } // End of loop over local nodes q_local
             } // End of if(element_has_node_with_aux_node_update_fct)
           } // End of if it's not a boundary condition
         } // End of loop over (m) master nodes
       } // End of loop over shape functions for continuity eqn
     } // End of loop over integration points
   }
References oomph::ALE_is_disabled, Global_Parameters::body_force(), oomph::GeneralisedElement::Default_fd_jacobian_step, DIM, G, GlobalPhysicalVariables::Gamma, oomph::Node::has_auxiliary_node_update_fct_pt(), i, J, j, k, m, oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), p, oomph::Node::perform_auxiliary_node_update_fct(), Eigen::numext::q, s, TestProblem::source(), tmp, oomph::Data::value_pt(), w, and oomph::Node::x().
get_pressure_and_velocity_mass_matrix_diagonal()
template<unsigned DIM> void oomph::RefineableNavierStokesEquations< DIM >::get_pressure_and_velocity_mass_matrix_diagonal (Vector< double > & press_mass_diag, Vector< double > & veloc_mass_diag, const unsigned & which_one = 0) virtual
Compute the diagonal of the velocity/pressure mass matrices. If which one=0, both are computed, otherwise only the pressure (which_one=1) or the velocity mass matrix (which_one=2 – the LSC version of the preconditioner only needs that one)
Reimplemented from oomph::NavierStokesEquations< DIM >.
   {
     // Resize and initialise
     unsigned n_dof = ndof();
     if ((which_one == 0) || (which_one == 1))
       press_mass_diag.assign(n_dof, 0.0);
     if ((which_one == 0) || (which_one == 2))
       veloc_mass_diag.assign(n_dof, 0.0);
     // Pointers to hang info object
     HangInfo* hang_info_pt = 0;
     // Number of master nodes and weight for shape fcts
     unsigned n_master = 1;
     double hang_weight = 1.0;
     // find out how many nodes there are
     unsigned n_node = nnode();
     // Set up memory for veloc shape functions
     Shape psi(n_node);
     // Find number of pressure dofs
     unsigned n_pres = this->npres_nst();
     // Pressure shape function
     Shape psi_p(n_pres);
     // Local coordinates
     Vector<double> s(DIM);
     // find the indices at which the local velocities are stored
     Vector<unsigned> u_nodal_index(DIM);
     for (unsigned i = 0; i < DIM; i++)
     {
       u_nodal_index[i] = this->u_index_nst(i);
     }
     // Which nodal value represents the pressure? (Negative if pressure
     // is not based on nodal interpolation).
     int p_index = this->p_nodal_index_nst();
     // Local array of booleans that are true if the l-th pressure value is
     // hanging (avoid repeated virtual function calls)
     bool pressure_dof_is_hanging[n_pres];
     // If the pressure is stored at a node
     if (p_index >= 0)
     {
       // Read out whether the pressure is hanging
       for (unsigned l = 0; l < n_pres; ++l)
       {
         pressure_dof_is_hanging[l] = pressure_node_pt(l)->is_hanging(p_index);
       }
     }
     // Otherwise the pressure is not stored at a node and so cannot hang
     else
     {
       for (unsigned l = 0; l < n_pres; ++l)
       {
         pressure_dof_is_hanging[l] = false;
       }
     }
     // Number of integration points
     unsigned n_intpt = integral_pt()->nweight();
     // Integer to store the local equations no
     int local_eqn = 0;
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Get the integral weight
       double w = integral_pt()->weight(ipt);
       // Get determinant of Jacobian of the mapping
       double J = J_eulerian_at_knot(ipt);
       // Assign values of s
       for (unsigned i = 0; i < DIM; i++)
       {
         s[i] = integral_pt()->knot(ipt, i);
       }
       // Premultiply weights and Jacobian
       double W = w * J;
       // Do we want the velocity one?
       if ((which_one == 0) || (which_one == 2))
       {
         // Get the velocity shape functions
         shape_at_knot(ipt, psi);
         // Number of master nodes and storage for the weight of the shape
         // function
         unsigned n_master = 1;
         double hang_weight = 1.0;
         // Loop over the nodes for the test functions/equations
         //----------------------------------------------------
         for (unsigned l = 0; l < n_node; l++)
         {
           // Local boolean to indicate whether the node is hanging
           bool is_node_hanging = node_pt(l)->is_hanging();
           // If the node is hanging
           if (is_node_hanging)
           {
             hang_info_pt = node_pt(l)->hanging_pt();
             // Read out number of master nodes from hanging data
             n_master = hang_info_pt->nmaster();
           }
           // Otherwise the node is its own master
           else
           {
             n_master = 1;
           }
           // Loop over the master nodes
           for (unsigned m = 0; m < n_master; m++)
           {
             // Loop over velocity components for equations
             for (unsigned i = 0; i < DIM; i++)
             {
               // Get the equation number
               // If the node is hanging
               if (is_node_hanging)
               {
                 // Get the equation number from the master node
                 local_eqn = this->local_hang_eqn(
                   hang_info_pt->master_node_pt(m), u_nodal_index[i]);
                 // Get the hang weight from the master node
                 hang_weight = hang_info_pt->master_weight(m);
               }
               // If the node is not hanging
               else
               {
                 // Local equation number
                 local_eqn = this->nodal_local_eqn(l, u_nodal_index[i]);
                 // Node contributes with full weight
                 hang_weight = 1.0;
               }
               // If it's not a boundary condition...
               if (local_eqn >= 0)
               {
                 //       //Loop over the veclocity shape functions
                 //       for(unsigned l=0; l<n_node; l++)
                 //        {
                 //         //Loop over the velocity components
                 //         for(unsigned i=0; i<DIM; i++)
                 //          {
                 //           local_eqn = nodal_local_eqn(l,u_nodal_index[i]);
                 //           //If not a boundary condition
                 //           if(local_eqn >= 0)
                 //            {
                 // Add the contribution
                 veloc_mass_diag[local_eqn] += pow(psi[l] * hang_weight, 2) * W;
               }
             }
           }
         }
       }
       // Do we want the pressure one?
       if ((which_one == 0) || (which_one == 1))
       {
         // Get the pressure shape functions
         this->pshape_nst(s, psi_p);
         // Loop over the pressure shape functions
         for (unsigned l = 0; l < n_pres; l++)
         {
           // If the pressure dof is hanging
           if (pressure_dof_is_hanging[l])
           {
             // Pressure dof is hanging so it must be nodal-based
             // Get the hang info object
             hang_info_pt = this->pressure_node_pt(l)->hanging_pt(p_index);
             // Get the number of master nodes from the pressure node
             n_master = hang_info_pt->nmaster();
           }
           // Otherwise the node is its own master
           else
           {
             n_master = 1;
           }
           // Loop over the master nodes
           for (unsigned m = 0; m < n_master; m++)
           {
             // Get the number of the unknown
             // If the pressure dof is hanging
             if (pressure_dof_is_hanging[l])
             {
               // Get the local equation from the master node
               local_eqn =
                 this->local_hang_eqn(hang_info_pt->master_node_pt(m), p_index);
               // Get the weight for the node
               hang_weight = hang_info_pt->master_weight(m);
             }
             else
             {
               local_eqn = this->p_local_eqn(l);
               hang_weight = 1.0;
             }
             // If the equation is not pinned
             if (local_eqn >= 0)
             {
               //       //Loop over the veclocity shape functions
               //       for(unsigned l=0; l<n_pres; l++)
               //        {
               //         // Get equation number
               //         local_eqn = p_local_eqn(l);
               //         //If not a boundary condition
               //         if(local_eqn >= 0)
               //          {
               // Add the contribution
               press_mass_diag[local_eqn] += pow(psi_p[l] * hang_weight, 2) * W;
             }
           }
         }
       }
     }
   }
References DIM, i, J, m, oomph::HangInfo::master_node_pt(), oomph::HangInfo::master_weight(), oomph::HangInfo::nmaster(), Eigen::bfloat16_impl::pow(), s, w, and oomph::QuadTreeNames::W.
get_Z2_flux()
template<unsigned DIM> void oomph::RefineableNavierStokesEquations< DIM >::get_Z2_flux (const Vector< double > & s, Vector< double > & flux) inline virtual
Get 'flux' for Z2 error recovery: Upper triangular entries in strain rate tensor.
Implements oomph::ElementWithZ2ErrorEstimator.
     {
 #ifdef PARANOID
       unsigned num_entries = DIM + (DIM * (DIM - 1)) / 2;
       if (flux.size() < num_entries)
       {
         std::ostringstream error_message;
         error_message << "The flux vector has the wrong number of entries, "
                       << flux.size() << ", whereas it should be at least "
                       << num_entries << std::endl;
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // Get strain rate matrix
       DenseMatrix<double> strainrate(DIM);
       this->strain_rate(s, strainrate);
       // Pack into flux Vector
       unsigned icount = 0;
       // Start with diagonal terms
       for (unsigned i = 0; i < DIM; i++)
       {
         flux[icount] = strainrate(i, i);
         icount++;
       }
       // Off diagonals row by row
       for (unsigned i = 0; i < DIM; i++)
       {
         for (unsigned j = i + 1; j < DIM; j++)
         {
           flux[icount] = strainrate(i, j);
           icount++;
         }
       }
     }
References DIM, ProblemParameters::flux(), i, j, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::NavierStokesEquations< DIM >::strain_rate().
Referenced by RefineableBuoyantQCrouzeixRaviartElement< DIM >::get_Z2_flux(), oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >::get_Z2_flux(), and oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::get_Z2_flux().
num_Z2_flux_terms()
template<unsigned DIM> unsigned oomph::RefineableNavierStokesEquations< DIM >::num_Z2_flux_terms () inline virtual
Number of 'flux' terms for Z2 error estimation.
Implements oomph::ElementWithZ2ErrorEstimator.
     {
       // DIM diagonal strain rates, DIM(DIM -1) /2 off diagonal rates
       return DIM + (DIM * (DIM - 1)) / 2;
     }
References DIM.
Referenced by RefineableBuoyantQCrouzeixRaviartElement< DIM >::get_Z2_compound_flux_indices(), oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >::get_Z2_compound_flux_indices(), oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::get_Z2_compound_flux_indices(), RefineableBuoyantQCrouzeixRaviartElement< DIM >::get_Z2_flux(), oomph::RefineableDoubleBuoyantQCrouzeixRaviartElement< DIM >::get_Z2_flux(), and oomph::RefineableBuoyantQCrouzeixRaviartElement< DIM >::get_Z2_flux().
pin_elemental_redundant_nodal_pressure_dofs()
template<unsigned DIM> virtual void oomph::RefineableNavierStokesEquations< DIM >::pin_elemental_redundant_nodal_pressure_dofs () inline protected virtual
Pin unused nodal pressure dofs (empty by default, because by default pressure dofs are not associated with nodes)
Reimplemented in oomph::RefineableQTaylorHoodElement< DIM >, and oomph::RefineableQTaylorHoodElement< 2 >.
 {}
Referenced by oomph::RefineableNavierStokesEquations< DIM >::pin_redundant_nodal_pressures().
pin_redundant_nodal_pressures()
template<unsigned DIM> static void oomph::RefineableNavierStokesEquations< DIM >::pin_redundant_nodal_pressures (const Vector< GeneralisedElement * > & element_pt) inline static
Loop over all elements in Vector (which typically contains all the elements in a fluid mesh) and pin the nodal pressure degrees of freedom that are not being used. Function uses the member function
RefineableNavierStokesEquations:: pin_elemental_redundant_nodal_pressure_dofs()
which is empty by default and should be implemented for elements with nodal pressure degrees of freedom (e.g. for refineable Taylor-Hood.)
     {
       // Loop over all elements and call the function that pins their
       // unused nodal pressure data
       unsigned n_element = element_pt.size();
       for (unsigned e = 0; e < n_element; e++)
       {
         dynamic_cast<RefineableNavierStokesEquations<DIM>*>(element_pt[e])
           ->pin_elemental_redundant_nodal_pressure_dofs();
       }
     }
References e(), and oomph::RefineableNavierStokesEquations< DIM >::pin_elemental_redundant_nodal_pressure_dofs().
Referenced by FlowAroundCylinderProblem< ELEMENT >::actions_after_adapt(), RefineablePorousChannelProblem< ELEMENT >::actions_after_adapt(), MovingBlockProblem< ELEMENT >::actions_after_adapt(), and RefineablePorousChannelProblem< ELEMENT >::RefineablePorousChannelProblem().
pressure_node_pt()
template<unsigned DIM> virtual Node* oomph::RefineableNavierStokesEquations< DIM >::pressure_node_pt (const unsigned & n_p) inline virtual
Pointer to n_p-th pressure node (Default: NULL, indicating that pressure is not based on nodal interpolation).
Reimplemented in oomph::RefineableQTaylorHoodElement< DIM >, and oomph::RefineableQTaylorHoodElement< 2 >.
     {
       return NULL;
     }
unpin_all_pressure_dofs()
template<unsigned DIM> static void oomph::RefineableNavierStokesEquations< DIM >::unpin_all_pressure_dofs (const Vector< GeneralisedElement * > & element_pt) inline static
Unpin all pressure dofs in elements listed in vector.
     {
       // Loop over all elements
       unsigned n_element = element_pt.size();
       for (unsigned e = 0; e < n_element; e++)
       {
         dynamic_cast<RefineableNavierStokesEquations<DIM>*>(element_pt[e])
           ->unpin_elemental_pressure_dofs();
       }
     }
References e(), and oomph::RefineableNavierStokesEquations< DIM >::unpin_elemental_pressure_dofs().
Referenced by FlowAroundCylinderProblem< ELEMENT >::actions_after_adapt(), RefineablePorousChannelProblem< ELEMENT >::actions_after_adapt(), MovingBlockProblem< ELEMENT >::actions_after_adapt(), RefineableConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_after_adapt(), and RefineableDDConvectionProblem< NST_ELEMENT, AD_ELEMENT >::actions_after_adapt().
unpin_elemental_pressure_dofs()
template<unsigned DIM> virtual void oomph::RefineableNavierStokesEquations< DIM >::unpin_elemental_pressure_dofs () protected pure virtual
Unpin all pressure dofs in the element.
Implemented in oomph::PRefineableQCrouzeixRaviartElement< DIM >, oomph::RefineableQCrouzeixRaviartElement< DIM >, oomph::RefineableQCrouzeixRaviartElement< 2 >, oomph::RefineableQTaylorHoodElement< DIM >, and oomph::RefineableQTaylorHoodElement< 2 >.
Referenced by oomph::RefineableNavierStokesEquations< DIM >::unpin_all_pressure_dofs().
The documentation for this class was generated from the following files:
refineable_navier_stokes_elements.h
refineable_navier_stokes_elements.cc