MercuryDPM: BaseForce Class Reference
BaseForce Class Reference
#include <BaseForce.h>
Public Member Functions
BaseSpecies * getBaseSpecies () const
void setBaseSpecies (BaseSpecies *baseSpecies)
Private Attributes
BaseSpecies * baseSpecies_ = nullptr
Member Function Documentation
getBaseSpecies()
BaseSpecies* BaseForce::getBaseSpecies () const inline
     {
         logger.assert_debug(baseSpecies_,"BaseSpecies not set; consider using species.setHandler()");
         return baseSpecies_;
     }
References baseSpecies_, and logger.
Referenced by LinearPlasticViscoelasticNormalSpecies::computeBondNumberMax(), HertzianSinterNormalSpecies::computeTimeStep(), ChargedBondedSpecies::setInteractionDistance(), LiquidBridgeBagheriSpecies::setInteractionDistance(), LiquidBridgeClassicalWilletSpecies::setInteractionDistance(), LiquidBridgeWilletSpecies::setInteractionDistance(), LiquidMigrationLSSpecies::setInteractionDistance(), LiquidMigrationWilletSpecies::setInteractionDistance(), ReversibleAdhesiveSpecies::setInteractionDistance(), and MindlinSpecies::setPoissonRatio().
setBaseSpecies()
void BaseForce::setBaseSpecies (BaseSpecies * baseSpecies) inline
     {
         baseSpecies_ = baseSpecies;
     }
References baseSpecies_.
Referenced by BaseSpecies::BaseSpecies(), MixedSpecies< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::MixedSpecies(), and Species< NormalForceSpecies, FrictionForceSpecies, AdhesiveForceSpecies >::Species().
Member Data Documentation
baseSpecies_
BaseSpecies* BaseForce::baseSpecies_ = nullptr private
Referenced by getBaseSpecies(), and setBaseSpecies().
The documentation for this class was generated from the following file:
BaseForce.h