MercuryDPM: Eigen::internal::CacheSizes Struct Reference
Eigen::internal::CacheSizes Struct Reference
#include <GeneralBlockPanelKernel.h>
Public Member Functions
CacheSizes ()
Public Attributes
std::ptrdiff_t m_l1
std::ptrdiff_t m_l2
std::ptrdiff_t m_l3
Detailed Description
Constructor & Destructor Documentation
CacheSizes()
Eigen::internal::CacheSizes::CacheSizes () inline
                : m_l1(-1), m_l2(-1), m_l3(-1) {
     int l1CacheSize, l2CacheSize, l3CacheSize;
     queryCacheSizes(l1CacheSize, l2CacheSize, l3CacheSize);
     m_l1 = manage_caching_sizes_helper(l1CacheSize, defaultL1CacheSize);
     m_l2 = manage_caching_sizes_helper(l2CacheSize, defaultL2CacheSize);
     m_l3 = manage_caching_sizes_helper(l3CacheSize, defaultL3CacheSize);
   }
References Eigen::internal::defaultL1CacheSize, Eigen::internal::defaultL2CacheSize, Eigen::internal::defaultL3CacheSize, Eigen::l1CacheSize(), Eigen::l2CacheSize(), Eigen::l3CacheSize(), m_l1, m_l2, m_l3, Eigen::internal::manage_caching_sizes_helper(), and Eigen::internal::queryCacheSizes().
Member Data Documentation
m_l1
std::ptrdiff_t Eigen::internal::CacheSizes::m_l1
Referenced by CacheSizes(), and Eigen::internal::manage_caching_sizes().
m_l2
std::ptrdiff_t Eigen::internal::CacheSizes::m_l2
Referenced by CacheSizes(), and Eigen::internal::manage_caching_sizes().
m_l3
std::ptrdiff_t Eigen::internal::CacheSizes::m_l3
Referenced by CacheSizes(), and Eigen::internal::manage_caching_sizes().
The documentation for this struct was generated from the following file:
products/GeneralBlockPanelKernel.h