MercuryDPM: Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device > Struct Template Reference
Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device > Struct Template Reference
#include <TensorMorphing.h>
Classes
struct BlockIteratorState
Public Types
enum ReshapingKind { OneByN = 0 , NByOne = 1 , Runtime = 2 }
enum { IsAligned = TensorEvaluator<ArgType, Device>::IsAligned , PacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess }
typedef TensorReshapingOp< NewDimensions, ArgType > XprType
typedef NewDimensions Dimensions
typedef XprType::Index Index
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef StorageMemory< CoeffReturnType, Device > Storage
typedef Storage::Type EvaluatorPointerType
typedef StorageMemory< std::remove_const_t< CoeffReturnType >, Device > ConstCastStorage
typedef std::remove_const_t< Scalar > ScalarNoConst
typedef internal::TensorBlockDescriptor< NumOutputDims, Index > TensorBlockDesc
typedef internal::TensorBlockScratchAllocator< Device > TensorBlockScratch
typedef internal::TensorMaterializedBlock< ScalarNoConst, NumOutputDims, Layout, Index > TensorBlock
Public Member Functions
EIGEN_STRONG_INLINE TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions & dimensions () const
EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (EvaluatorPointerType data)
EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType packet (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::TensorBlockResourceRequirements getResourceRequirements () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorBlock block (TensorBlockDesc &desc, TensorBlockScratch &scratch, bool=false) const
EIGEN_DEVICE_FUNC Storage::Type data () const
EIGEN_DEVICE_FUNC const TensorEvaluator< ArgType, Device > & impl () const
Static Public Attributes
static constexpr int NumOutputDims = internal::array_size<Dimensions>::value
static constexpr int NumInputDims
static const ReshapingKind kind
static constexpr int Layout = TensorEvaluator<ArgType, Device>::Layout
Protected Attributes
TensorEvaluator< ArgType, Device > m_impl
NewDimensions m_dimensions
Member Typedef Documentation
CoeffReturnType
template<typename NewDimensions , typename ArgType , typename Device > typedef XprType::CoeffReturnType Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >::CoeffReturnType
ConstCastStorage
template<typename NewDimensions , typename ArgType , typename Device > typedef StorageMemory<std::remove_const_t<CoeffReturnType>, Device> Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >::ConstCastStorage
Dimensions
template<typename NewDimensions , typename ArgType , typename Device > typedef NewDimensions Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >::Dimensions
EvaluatorPointerType
template<typename NewDimensions , typename ArgType , typename Device > typedef Storage::Type Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >::EvaluatorPointerType
Index
template<typename NewDimensions , typename ArgType , typename Device > typedef XprType::Index Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >::Index
PacketReturnType
template<typename NewDimensions , typename ArgType , typename Device > typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >::PacketReturnType
Scalar
template<typename NewDimensions , typename ArgType , typename Device > typedef XprType::Scalar Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >::Scalar
ScalarNoConst
template<typename NewDimensions , typename ArgType , typename Device > typedef std::remove_const_t<Scalar> Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >::ScalarNoConst
Storage
template<typename NewDimensions , typename ArgType , typename Device > typedef StorageMemory<CoeffReturnType, Device> Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >::Storage
TensorBlock
template<typename NewDimensions , typename ArgType , typename Device > typedef internal::TensorMaterializedBlock<ScalarNoConst, NumOutputDims, Layout, Index> Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >::TensorBlock
TensorBlockDesc
template<typename NewDimensions , typename ArgType , typename Device > typedef internal::TensorBlockDescriptor<NumOutputDims, Index> Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >::TensorBlockDesc
TensorBlockScratch
template<typename NewDimensions , typename ArgType , typename Device > typedef internal::TensorBlockScratchAllocator<Device> Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >::TensorBlockScratch
XprType
template<typename NewDimensions , typename ArgType , typename Device > typedef TensorReshapingOp<NewDimensions, ArgType> Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >::XprType
Member Enumeration Documentation
anonymous enum
template<typename NewDimensions , typename ArgType , typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
        {
     IsAligned = TensorEvaluator<ArgType, Device>::IsAligned,
     PacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess,
     // For trivial reshapes with raw access to underlying data we will provide
     // zero overhead block access.
     // TODO(ezhulenev): Consider adding block access without raw access?
     BlockAccess = TensorEvaluator<ArgType, Device>::RawAccess && NumInputDims > 0 && NumOutputDims > 0,
     PreferBlockAccess = false,
     CoordAccess = false,  // to be implemented
     RawAccess = TensorEvaluator<ArgType, Device>::RawAccess
   };
ReshapingKind
template<typename NewDimensions , typename ArgType , typename Device > enum Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >::ReshapingKind
Enumerator
OneByN
NByOne
Runtime
                      {
     // We do not use layout information to determine reshaping kind.
     // Depending on the layout `N` can be inner or outer dimension.
     OneByN = 0,  // expr.reshape(1, N)
     NByOne = 1,  // expr.reshape(N, 1)
     Runtime = 2  // Reshape dimensions are dynamic (specified at runtime).
   };
Constructor & Destructor Documentation
TensorEvaluator()
template<typename NewDimensions , typename ArgType , typename Device > EIGEN_STRONG_INLINE Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >::TensorEvaluator (const XprType & op, const Device & device) inline
       : m_impl(op.expression(), device), m_dimensions(op.dimensions()) {
     // The total size of the reshaped tensor must be equal to the total size
     // of the input tensor.
     eigen_assert(internal::array_prod(m_impl.dimensions()) == internal::array_prod(op.dimensions()));
   }
References Eigen::internal::array_prod(), eigen_assert, and op.
Member Function Documentation
block()
template<typename NewDimensions , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorBlock Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >::block (TensorBlockDesc & desc, TensorBlockScratch & scratch, bool = false) const inline
{
     eigen_assert(m_impl.data() != NULL);
     eigen_assert((kind == Runtime) || (kind == OneByN && desc.dimensions()[0] == 1) ||
                  (kind == NByOne && desc.dimensions()[1] == 1));
     if (kind == OneByN || kind == NByOne) {
       // We can guarantee at compile time that block is just a contiguous slice
       // of the underlying expression memory buffer.
       return TensorBlock(internal::TensorBlockKind::kView, m_impl.data() + desc.offset(), desc.dimensions());
     } else {
       // This will do additional runtime checks, and in the end it might be also
       // a view, or it might be a block materialized in the temporary buffer.
       return TensorBlock::materialize(m_impl.data(), m_dimensions, desc, scratch);
     }
   }
References Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::dimensions(), eigen_assert, Eigen::internal::kView, Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::materialize(), NByOne(), and Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::offset().
cleanup()
template<typename NewDimensions , typename ArgType , typename Device > EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >::cleanup () inline
 { m_impl.cleanup(); }
Referenced by framework.Frame::__init__().
coeff()
template<typename NewDimensions , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >::coeff (Index index) const inline
 { return m_impl.coeff(index); }
costPerCoeff()
template<typename NewDimensions , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >::costPerCoeff (bool vectorized) const inline
{
     return m_impl.costPerCoeff(vectorized);
   }
data()
template<typename NewDimensions , typename ArgType , typename Device > EIGEN_DEVICE_FUNC Storage::Type Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >::data () const inline
 { return constCast(m_impl.data()); }
References Eigen::constCast().
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
dimensions()
template<typename NewDimensions , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions& Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >::dimensions () const inline
 { return m_dimensions; }
evalSubExprsIfNeeded()
template<typename NewDimensions , typename ArgType , typename Device > EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >::evalSubExprsIfNeeded (EvaluatorPointerType data) inline
 { return m_impl.evalSubExprsIfNeeded(data); }
References Eigen::TensorEvaluator< Derived, Device >::data().
getResourceRequirements()
template<typename NewDimensions , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::TensorBlockResourceRequirements Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >::getResourceRequirements () const inline
{
     return internal::TensorBlockResourceRequirements::any();
   }
References Eigen::internal::TensorBlockResourceRequirements::any().
impl()
template<typename NewDimensions , typename ArgType , typename Device > EIGEN_DEVICE_FUNC const TensorEvaluator<ArgType, Device>& Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >::impl () const inline
 { return m_impl; }
packet()
template<typename NewDimensions , typename ArgType , typename Device > template<int LoadMode> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >::packet (Index index) const inline
{
     return m_impl.template packet<LoadMode>(index);
   }
Member Data Documentation
kind
template<typename NewDimensions , typename ArgType , typename Device > const ReshapingKind Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >::kind static
Initial value:
=
        (NumOutputDims == 2 && internal::index_statically_eq<NewDimensions>(0, 1)) ? OneByN
      : (NumOutputDims == 2 && internal::index_statically_eq<NewDimensions>(1, 1)) ? NByOne
      : Runtime
Layout
template<typename NewDimensions , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >::Layout = TensorEvaluator<ArgType, Device>::Layout static constexpr
m_dimensions
template<typename NewDimensions , typename ArgType , typename Device > NewDimensions Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >::m_dimensions protected
m_impl
template<typename NewDimensions , typename ArgType , typename Device > TensorEvaluator<ArgType, Device> Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >::m_impl protected
NumInputDims
template<typename NewDimensions , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >::NumInputDims static constexpr
Initial value:
=
      internal::array_size<typename TensorEvaluator<ArgType, Device>::Dimensions>::value
NumOutputDims
template<typename NewDimensions , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorReshapingOp< NewDimensions, ArgType >, Device >::NumOutputDims = internal::array_size<Dimensions>::value static constexpr
The documentation for this struct was generated from the following file:
TensorMorphing.h