MercuryDPM: oomph::PoroelasticityEquations< DIM > Class Template Reference
oomph::PoroelasticityEquations< DIM > Class Template Reference abstract
#include <poroelasticity_elements.h>
Public Types
typedef void(* SourceFctPt) (const double &time, const Vector< double > &x, Vector< double > &f)
Source function pointer typedef.
typedef void(* MassSourceFctPt) (const double &time, const Vector< double > &x, double &f)
Mass source function pointer typedef.
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Public Member Functions
PoroelasticityEquations ()
Constructor.
const double & lambda_sq () const
Access function for timescale ratio (nondim density)
double *& lambda_sq_pt ()
Access function for pointer to timescale ratio (nondim density)
const double & density_ratio () const
Access function for the density ratio.
double *& density_ratio_pt ()
Access function for pointer to the density ratio.
const double & k_inv () const
Access function for the nondim inverse permeability.
double *& k_inv_pt ()
Access function for pointer to the nondim inverse permeability.
const double & alpha () const
Access function for alpha.
double *& alpha_pt ()
Access function for pointer to alpha.
const double & porosity () const
Access function for the porosity.
double *& porosity_pt ()
Access function for pointer to the porosity.
SourceFctPt & force_solid_fct_pt ()
Access function: Pointer to solid force function.
SourceFctPt force_solid_fct_pt () const
Access function: Pointer to solid force function (const version)
SourceFctPt & force_fluid_fct_pt ()
Access function: Pointer to fluid force function.
SourceFctPt force_fluid_fct_pt () const
Access function: Pointer to fluid force function (const version)
MassSourceFctPt & mass_source_fct_pt ()
Access function: Pointer to mass source function.
MassSourceFctPt mass_source_fct_pt () const
Access function: Pointer to mass source function (const version)
void force_solid (const double &time, const Vector< double > &x, Vector< double > &b) const
void force_fluid (const double &time, const Vector< double > &x, Vector< double > &b) const
void mass_source (const double &time, const Vector< double > &x, double &b) const
ElasticityTensor *& elasticity_tensor_pt ()
Return the pointer to the elasticity_tensor.
const double E (const unsigned &i, const unsigned &j, const unsigned &k, const unsigned &l) const
Access function to the entries in the elasticity tensor.
void get_stress (const Vector< double > &s, DenseMatrix< double > &sigma) const
void get_strain (const Vector< double > &s, DenseMatrix< double > &strain) const
Return the strain tensor.
virtual unsigned required_nvalue (const unsigned &n) const =0
Number of values required at node n.
virtual unsigned u_index (const unsigned &n) const =0
Return the nodal index of the n-th solid displacement unknown.
virtual int q_edge_local_eqn (const unsigned &n) const =0
Return the equation number of the n-th edge (flux) degree of freedom.
virtual int q_internal_local_eqn (const unsigned &n) const =0
virtual unsigned q_edge_index (const unsigned &n) const =0
Return the nodal index at which the nth edge unknown is stored.
virtual unsigned q_internal_index () const =0
virtual unsigned q_edge_node_number (const unsigned &n) const =0
Return the number of the node where the nth edge unknown is stored.
virtual double q_edge (const unsigned &n) const =0
Return the values of the edge (flux) degrees of freedom.
virtual double q_edge (const unsigned &t, const unsigned &n) const =0
virtual double q_internal (const unsigned &n) const =0
Return the values of the internal (moment) degrees of freedom.
virtual double q_internal (const unsigned &t, const unsigned &n) const =0
virtual unsigned nq_basis () const =0
Return the total number of computational basis functions for q.
virtual unsigned nq_basis_edge () const =0
Return the number of edge basis functions for q.
virtual void get_q_basis_local (const Vector< double > &s, Shape &q_basis) const =0
Returns the local form of the q basis at local coordinate s.
virtual void get_div_q_basis_local (const Vector< double > &s, Shape &div_q_basis_ds) const =0
void get_q_basis (const Vector< double > &s, Shape &q_basis) const
Returns the transformed basis at local coordinate s.
virtual unsigned nedge_gauss_point () const =0
Returns the number of gauss points along each edge of the element.
virtual double edge_gauss_point (const unsigned &edge, const unsigned &n) const =0
Returns the nth gauss point along an edge.
virtual void edge_gauss_point_global (const unsigned &edge, const unsigned &n, Vector< double > &x) const =0
Returns the global coordinates of the nth gauss point along an edge.
virtual void pin_q_internal_value (const unsigned &n)=0
Pin the nth internal q value.
virtual int p_local_eqn (const unsigned &n) const =0
Return the equation number of the n-th pressure degree of freedom.
virtual double p_value (unsigned &n) const =0
Return the nth pressure value.
virtual unsigned np_basis () const =0
Return the total number of pressure basis functions.
virtual void get_p_basis (const Vector< double > &s, Shape &p_basis) const =0
Return the pressure basis.
virtual void pin_p_value (const unsigned &n, const double &p)=0
Pin the nth pressure value.
virtual void scale_basis (Shape &basis) const =0
Scale the edge basis to allow arbitrary edge mappings.
double transform_basis (const Vector< double > &s, const Shape &q_basis_local, Shape &psi, DShape &dpsi, Shape &q_basis) const
double transform_basis (const Vector< double > &s, const Shape &q_basis_local, Shape &psi, Shape &q_basis) const
void fill_in_contribution_to_residuals (Vector< double > &residuals)
Fill in contribution to residuals for the Darcy equations.
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Fill in the Jacobian matrix for the Newton method.
void interpolated_u (const Vector< double > &s, Vector< double > &disp) const
Calculate the FE representation of u.
double interpolated_u (const Vector< double > &s, const unsigned &i) const
Calculate the FE representation of the i-th component of u.
void interpolated_q (const Vector< double > &s, Vector< double > &u) const
Calculate the FE representation of q.
double interpolated_q (const Vector< double > &s, const unsigned i) const
Calculate the FE representation of the i-th component of q.
void interpolated_div_q (const Vector< double > &s, double &div_q) const
Calculate the FE representation of div u.
double interpolated_div_q (const Vector< double > &s)
Calculate the FE representation of div q and return it.
void interpolated_p (const Vector< double > &s, double &p) const
Calculate the FE representation of p.
double interpolated_p (const Vector< double > &s) const
Calculate the FE representation of p and return it.
double du_dt (const unsigned &n, const unsigned &i) const
du/dt at local node n
double d2u_dt2 (const unsigned &n, const unsigned &i) const
d^2u/dt^2 at local node n
double dq_edge_dt (const unsigned &n) const
dq_edge/dt for the n-th edge degree of freedom
double dq_internal_dt (const unsigned &n) const
dq_internal/dt for the n-th internal degree of freedom
void set_q_internal_timestepper (TimeStepper *const time_stepper_pt)
Set the timestepper of the q internal data object.
unsigned self_test ()
void output (std::ostream &outfile)
Output with default number of plot points.
void output (std::ostream &outfile, const unsigned &nplot)
void output_fct (std::ostream &outfile, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
void output_fct (std::ostream &outfile, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
virtual void disable_ALE ()
virtual void enable_ALE ()
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual unsigned nvertex_node () const
virtual Node * vertex_node_pt (const unsigned &j) const
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output (FILE *file_pt)
virtual void output (FILE *file_pt, const unsigned &n_plot)
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Protected Member Functions
virtual double shape_basis_test_local (const Vector< double > &s, Shape &psi, DShape &dpsi, Shape &u_basis, Shape &u_test, DShape &du_basis_dx, DShape &du_test_dx, Shape &q_basis, Shape &q_test, Shape &p_basis, Shape &p_test, Shape &div_q_basis_ds, Shape &div_q_test_ds) const =0
virtual double shape_basis_test_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, Shape &u_basis, Shape &u_test, DShape &du_basis_dx, DShape &du_test_dx, Shape &q_basis, Shape &q_test, Shape &p_basis, Shape &p_test, Shape &div_q_basis_ds, Shape &div_q_test_ds) const =0
virtual void fill_in_generic_residual_contribution (Vector< double > &residuals, DenseMatrix< double > &jacobian, bool flag)
Fill in residuals and, if flag==true, jacobian.
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Attributes
ElasticityTensor * Elasticity_tensor_pt
Pointer to the elasticity tensor.
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Private Attributes
SourceFctPt Force_solid_fct_pt
Pointer to solid source function.
SourceFctPt Force_fluid_fct_pt
Pointer to fluid source function.
MassSourceFctPt Mass_source_fct_pt
Pointer to the mass source function.
double * Lambda_sq_pt
Timescale ratio (non-dim. density)
double * Density_ratio_pt
Density ratio.
double * K_inv_pt
1/k
double * Alpha_pt
Alpha.
double * Porosity_pt
Porosity.
Static Private Attributes
static double Default_lambda_sq_value = 1.0
Static default value for timescale ratio (1.0 – for natural scaling)
static double Default_density_ratio_value = 1.0
Static default value for the density ratio.
static double Default_k_inv_value = 1.0
Static default value for 1/k.
static double Default_alpha_value = 1.0
Static default value for alpha.
static double Default_porosity_value = 1.0
Static default value for the porosity.
Additional Inherited Members
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
template<unsigned DIM>
class oomph::PoroelasticityEquations< DIM >
Class implementing the generic maths of the poroelasticity equations: linear elasticity coupled with Darcy equations (using Raviart-Thomas elements with both edge and internal degrees of freedom)
Member Typedef Documentation
MassSourceFctPt
template<unsigned DIM> typedef void(* oomph::PoroelasticityEquations< DIM >::MassSourceFctPt) (const double &time, const Vector< double > &x, double &f)
Mass source function pointer typedef.
SourceFctPt
template<unsigned DIM> typedef void(* oomph::PoroelasticityEquations< DIM >::SourceFctPt) (const double &time, const Vector< double > &x, Vector< double > &f)
Source function pointer typedef.
Constructor & Destructor Documentation
PoroelasticityEquations()
template<unsigned DIM> oomph::PoroelasticityEquations< DIM >::PoroelasticityEquations () inline
Constructor.
       : Elasticity_tensor_pt(0),
         Force_solid_fct_pt(0),
         Force_fluid_fct_pt(0),
         Mass_source_fct_pt(0),
         Lambda_sq_pt(&Default_lambda_sq_value),
         Density_ratio_pt(&Default_density_ratio_value),
         K_inv_pt(&Default_k_inv_value),
         Alpha_pt(&Default_alpha_value),
         Porosity_pt(&Default_porosity_value)
     {
     }
Member Function Documentation
alpha()
template<unsigned DIM> const double& oomph::PoroelasticityEquations< DIM >::alpha () const inline
Access function for alpha.
     {
       return *Alpha_pt;
     }
References oomph::PoroelasticityEquations< DIM >::Alpha_pt.
alpha_pt()
template<unsigned DIM> double*& oomph::PoroelasticityEquations< DIM >::alpha_pt () inline
Access function for pointer to alpha.
     {
       return Alpha_pt;
     }
References oomph::PoroelasticityEquations< DIM >::Alpha_pt.
compute_error() [1/2]
template<unsigned DIM> void oomph::PoroelasticityEquations< DIM >::compute_error (std::ostream & outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > & error, Vector< double > & norm) virtual
Compute the error between the FE solution and the exact solution using the H(div) norm for q and L^2 norm for p
Compute the error between the FE solution and the exact solution using the H(div) norm for q and L^2 norm for u and p
Reimplemented from oomph::FiniteElement.
   {
     for (unsigned i = 0; i < 3; i++)
     {
       error[i] = 0.0;
       norm[i] = 0.0;
     }
     // Vector of local coordinates
     Vector<double> s(DIM);
     // Vector for coordinates
     Vector<double> x(DIM);
     // Set the value of n_intpt
     unsigned n_intpt = this->integral_pt()->nweight();
     outfile << "ZONE" << std::endl;
     // Exact solution Vector (u,v,[w])
     Vector<double> exact_soln(2 * DIM + 2);
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Assign values of s
       for (unsigned i = 0; i < DIM; i++)
       {
         s[i] = this->integral_pt()->knot(ipt, i);
       }
       // Get the integral weight
       double w = this->integral_pt()->weight(ipt);
       // Get jacobian of mapping
       double J = this->J_eulerian(s);
       // Premultiply the weights and the Jacobian
       double W = w * J;
       // Get x position as Vector
       this->interpolated_x(s, x);
       // Get exact solution at this point
       (*exact_soln_pt)(x, exact_soln);
       // Displacement error
       for (unsigned i = 0; i < DIM; i++)
       {
         norm[0] += exact_soln[i] * exact_soln[i] * W;
         // Error due to q_i
         error[0] += (exact_soln[i] - this->interpolated_u(s, i)) *
                     (exact_soln[i] - this->interpolated_u(s, i)) * W;
       }
       // Flux error
       for (unsigned i = 0; i < DIM; i++)
       {
         norm[1] += exact_soln[DIM + i] * exact_soln[DIM + i] * W;
         // Error due to q_i
         error[1] += (exact_soln[DIM + i] - this->interpolated_q(s, i)) *
                     (exact_soln[DIM + i] - this->interpolated_q(s, i)) * W;
       }
       // Flux divergence error
       norm[1] += exact_soln[2 * DIM] * exact_soln[2 * DIM] * W;
       error[1] += (exact_soln[2 * DIM] - interpolated_div_q(s)) *
                   (exact_soln[2 * DIM] - interpolated_div_q(s)) * W;
       // Pressure error
       norm[2] += exact_soln[2 * DIM + 1] * exact_soln[2 * DIM + 1] * W;
       error[2] += (exact_soln[2 * DIM + 1] - this->interpolated_p(s)) *
                   (exact_soln[2 * DIM + 1] - this->interpolated_p(s)) * W;
       // Output x,y,[z]
       for (unsigned i = 0; i < DIM; i++)
       {
         outfile << x[i] << " ";
       }
       // Output u_1_error,u_2_error,...
       for (unsigned i = 0; i < DIM; i++)
       {
         outfile << exact_soln[i] - this->interpolated_u(s, i) << " ";
       }
       // Output q_1_error,q_2_error,...
       for (unsigned i = 0; i < DIM; i++)
       {
         outfile << exact_soln[DIM + i] - this->interpolated_q(s, i) << " ";
       }
       // Output p_error
       outfile << exact_soln[2 * DIM + 1] - this->interpolated_p(s) << " ";
       outfile << std::endl;
     }
   }
References DIM, calibrate::error, ProblemParameters::exact_soln(), i, J, s, w, oomph::QuadTreeNames::W, and plotDoE::x.
compute_error() [2/2]
template<unsigned DIM> void oomph::PoroelasticityEquations< DIM >::compute_error (std::ostream & outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double & time, Vector< double > & error, Vector< double > & norm) virtual
Compute the error between the FE solution and the exact solution using the H(div) norm for q and L^2 norm for p. Unsteady version
Compute the error between the FE solution and the exact solution using the H(div) norm for u and L^2 norm for p. Unsteady version
Reimplemented from oomph::FiniteElement.
   {
     for (unsigned i = 0; i < 3; i++)
     {
       error[i] = 0.0;
       norm[i] = 0.0;
     }
     // Vector of local coordinates
     Vector<double> s(DIM);
     // Vector for coordinates
     Vector<double> x(DIM);
     // Set the value of n_intpt
     unsigned n_intpt = this->integral_pt()->nweight();
     outfile << "ZONE" << std::endl;
     // Exact solution Vector (u,v,[w])
     Vector<double> exact_soln(2 * DIM + 2);
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Assign values of s
       for (unsigned i = 0; i < DIM; i++)
       {
         s[i] = this->integral_pt()->knot(ipt, i);
       }
       // Get the integral weight
       double w = this->integral_pt()->weight(ipt);
       // Get jacobian of mapping
       double J = this->J_eulerian(s);
       // Premultiply the weights and the Jacobian
       double W = w * J;
       // Get x position as Vector
       this->interpolated_x(s, x);
       // Get exact solution at this point
       (*exact_soln_pt)(time, x, exact_soln);
       // Displacement error
       for (unsigned i = 0; i < DIM; i++)
       {
         norm[0] += exact_soln[i] * exact_soln[i] * W;
         // Error due to q_i
         error[0] += (exact_soln[i] - this->interpolated_u(s, i)) *
                     (exact_soln[i] - this->interpolated_u(s, i)) * W;
       }
       // Flux error
       for (unsigned i = 0; i < DIM; i++)
       {
         norm[1] += exact_soln[DIM + i] * exact_soln[DIM + i] * W;
         // Error due to q_i
         error[1] += (exact_soln[DIM + i] - this->interpolated_q(s, i)) *
                     (exact_soln[DIM + i] - this->interpolated_q(s, i)) * W;
       }
       // Flux divergence error
       norm[1] += exact_soln[2 * DIM] * exact_soln[2 * DIM] * W;
       error[1] += (exact_soln[2 * DIM] - interpolated_div_q(s)) *
                   (exact_soln[2 * DIM] - interpolated_div_q(s)) * W;
       // Pressure error
       norm[2] += exact_soln[2 * DIM + 1] * exact_soln[2 * DIM + 1] * W;
       error[2] += (exact_soln[2 * DIM + 1] - this->interpolated_p(s)) *
                   (exact_soln[2 * DIM + 1] - this->interpolated_p(s)) * W;
       // Output x,y,[z]
       for (unsigned i = 0; i < DIM; i++)
       {
         outfile << x[i] << " ";
       }
       // Output u_1_error,u_2_error,...
       for (unsigned i = 0; i < DIM; i++)
       {
         outfile << exact_soln[i] - this->interpolated_u(s, i) << " ";
       }
       // Output q_1_error,q_2_error,...
       for (unsigned i = 0; i < DIM; i++)
       {
         outfile << exact_soln[DIM + i] - this->interpolated_q(s, i) << " ";
       }
       // Output p_error
       outfile << exact_soln[2 * DIM + 1] - this->interpolated_p(s) << " ";
       outfile << std::endl;
     }
   }
References DIM, calibrate::error, ProblemParameters::exact_soln(), i, J, s, w, oomph::QuadTreeNames::W, and plotDoE::x.
d2u_dt2()
template<unsigned DIM> double oomph::PoroelasticityEquations< DIM >::d2u_dt2 (const unsigned & n, const unsigned & i) const inline
d^2u/dt^2 at local node n
     {
       // Get the timestepper
       TimeStepper* time_stepper_pt = node_pt(n)->time_stepper_pt();
       // Storage for the derivative - initialise to 0
       double d2u_dt2 = 0.0;
       // If we are doing an unsteady solve then calculate the derivative
       if (!time_stepper_pt->is_steady())
       {
         // Get the nodal index
         const unsigned u_nodal_index = u_index(i);
         // Get the number of values required to represent history
         const unsigned n_time = time_stepper_pt->ntstorage();
         // Loop over history values
         for (unsigned t = 0; t < n_time; t++)
         {
           // Add the contribution to the derivative
           d2u_dt2 +=
             time_stepper_pt->weight(2, t) * nodal_value(t, n, u_nodal_index);
         }
       }
       return d2u_dt2;
     }
References i, oomph::TimeStepper::is_steady(), n, oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), plotPSD::t, oomph::GeomObject::time_stepper_pt(), oomph::Data::time_stepper_pt(), oomph::PoroelasticityEquations< DIM >::u_index(), and oomph::TimeStepper::weight().
density_ratio()
template<unsigned DIM> const double& oomph::PoroelasticityEquations< DIM >::density_ratio () const inline
Access function for the density ratio.
     {
       return *Density_ratio_pt;
     }
References oomph::PoroelasticityEquations< DIM >::Density_ratio_pt.
density_ratio_pt()
template<unsigned DIM> double*& oomph::PoroelasticityEquations< DIM >::density_ratio_pt () inline
Access function for pointer to the density ratio.
     {
       return Density_ratio_pt;
     }
References oomph::PoroelasticityEquations< DIM >::Density_ratio_pt.
dq_edge_dt()
template<unsigned DIM> double oomph::PoroelasticityEquations< DIM >::dq_edge_dt (const unsigned & n) const inline
dq_edge/dt for the n-th edge degree of freedom
     {
       unsigned node_num = q_edge_node_number(n);
       // get the timestepper
       TimeStepper* time_stepper_pt = node_pt(node_num)->time_stepper_pt();
       // storage for the derivative - initialise to 0
       double dq_dt = 0.0;
       // if we are doing an unsteady solve then calculate the derivative
       if (!time_stepper_pt->is_steady())
       {
         // get the number of values required to represent history
         const unsigned n_time = time_stepper_pt->ntstorage();
         // loop over history values
         for (unsigned t = 0; t < n_time; t++)
         {
           // add the contribution to the derivative
           dq_dt += time_stepper_pt->weight(1, t) * q_edge(t, n);
         }
       }
       return dq_dt;
     }
References oomph::TimeStepper::is_steady(), n, oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), oomph::PoroelasticityEquations< DIM >::q_edge(), oomph::PoroelasticityEquations< DIM >::q_edge_node_number(), plotPSD::t, oomph::GeomObject::time_stepper_pt(), oomph::Data::time_stepper_pt(), and oomph::TimeStepper::weight().
dq_internal_dt()
template<unsigned DIM> double oomph::PoroelasticityEquations< DIM >::dq_internal_dt (const unsigned & n) const inline
dq_internal/dt for the n-th internal degree of freedom
     {
       // get the internal data index for q
       unsigned internal_index = q_internal_index();
       // get the timestepper
       TimeStepper* time_stepper_pt =
         internal_data_pt(internal_index)->time_stepper_pt();
       // storage for the derivative - initialise to 0
       double dq_dt = 0.0;
       // if we are doing an unsteady solve then calculate the derivative
       if (!time_stepper_pt->is_steady())
       {
         // get the number of values required to represent history
         const unsigned n_time = time_stepper_pt->ntstorage();
         // loop over history values
         for (unsigned t = 0; t < n_time; t++)
         {
           // add the contribution to the derivative
           dq_dt += time_stepper_pt->weight(1, t) * q_internal(t, n);
         }
       }
       return dq_dt;
     }
References oomph::GeneralisedElement::internal_data_pt(), oomph::TimeStepper::is_steady(), n, oomph::TimeStepper::ntstorage(), oomph::PoroelasticityEquations< DIM >::q_internal(), oomph::PoroelasticityEquations< DIM >::q_internal_index(), plotPSD::t, oomph::GeomObject::time_stepper_pt(), oomph::Data::time_stepper_pt(), and oomph::TimeStepper::weight().
du_dt()
template<unsigned DIM> double oomph::PoroelasticityEquations< DIM >::du_dt (const unsigned & n, const unsigned & i) const inline
du/dt at local node n
     {
       // Get the timestepper
       TimeStepper* time_stepper_pt = node_pt(n)->time_stepper_pt();
       // Storage for the derivative - initialise to 0
       double du_dt = 0.0;
       // If we are doing an unsteady solve then calculate the derivative
       if (!time_stepper_pt->is_steady())
       {
         // Get the nodal index
         const unsigned u_nodal_index = u_index(i);
         // Get the number of values required to represent history
         const unsigned n_time = time_stepper_pt->ntstorage();
         // Loop over history values
         for (unsigned t = 0; t < n_time; t++)
         {
           // Add the contribution to the derivative
           du_dt +=
             time_stepper_pt->weight(1, t) * nodal_value(t, n, u_nodal_index);
         }
       }
       return du_dt;
     }
References i, oomph::TimeStepper::is_steady(), n, oomph::FiniteElement::nodal_value(), oomph::FiniteElement::node_pt(), oomph::TimeStepper::ntstorage(), plotPSD::t, oomph::GeomObject::time_stepper_pt(), oomph::Data::time_stepper_pt(), oomph::PoroelasticityEquations< DIM >::u_index(), and oomph::TimeStepper::weight().
E()
template<unsigned DIM> const double oomph::PoroelasticityEquations< DIM >::E (const unsigned & i, const unsigned & j, const unsigned & k, const unsigned & l) const inline
Access function to the entries in the elasticity tensor.
     {
       return (*Elasticity_tensor_pt)(i, j, k, l);
     }
References oomph::PoroelasticityEquations< DIM >::Elasticity_tensor_pt, i, j, and k.
edge_gauss_point()
template<unsigned DIM> virtual double oomph::PoroelasticityEquations< DIM >::edge_gauss_point (const unsigned & edge, const unsigned & n) const pure virtual
Returns the nth gauss point along an edge.
Implemented in oomph::TPoroelasticityElement< ORDER >.
edge_gauss_point_global()
template<unsigned DIM> virtual void oomph::PoroelasticityEquations< DIM >::edge_gauss_point_global (const unsigned & edge, const unsigned & n, Vector< double > & x) const pure virtual
Returns the global coordinates of the nth gauss point along an edge.
Implemented in oomph::TPoroelasticityElement< ORDER >.
elasticity_tensor_pt()
template<unsigned DIM> ElasticityTensor*& oomph::PoroelasticityEquations< DIM >::elasticity_tensor_pt () inline
Return the pointer to the elasticity_tensor.
     {
       return Elasticity_tensor_pt;
     }
References oomph::PoroelasticityEquations< DIM >::Elasticity_tensor_pt.
fill_in_contribution_to_jacobian()
template<unsigned DIM> void oomph::PoroelasticityEquations< DIM >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline virtual
Fill in the Jacobian matrix for the Newton method.
Reimplemented from oomph::FiniteElement.
     {
       this->fill_in_generic_residual_contribution(residuals, jacobian, 1);
     }
References oomph::PoroelasticityEquations< DIM >::fill_in_generic_residual_contribution().
fill_in_contribution_to_residuals()
template<unsigned DIM> void oomph::PoroelasticityEquations< DIM >::fill_in_contribution_to_residuals (Vector< double > & residuals) inline virtual
Fill in contribution to residuals for the Darcy equations.
Reimplemented from oomph::GeneralisedElement.
     {
       this->fill_in_generic_residual_contribution(
         residuals, GeneralisedElement::Dummy_matrix, 0);
     }
References oomph::GeneralisedElement::Dummy_matrix, and oomph::PoroelasticityEquations< DIM >::fill_in_generic_residual_contribution().
fill_in_generic_residual_contribution()
template<unsigned DIM> void oomph::PoroelasticityEquations< DIM >::fill_in_generic_residual_contribution (Vector< double > & residuals, DenseMatrix< double > & jacobian, bool flag) protected virtual
Fill in residuals and, if flag==true, jacobian.
   {
     // Get the number of geometric nodes, total number of basis functions,
     // and number of edges basis functions
     const unsigned n_node = nnode();
     const unsigned n_q_basis = nq_basis();
     const unsigned n_q_basis_edge = nq_basis_edge();
     const unsigned n_p_basis = np_basis();
     // Storage for the geometric and computational bases and the test functions
     Shape psi(n_node), u_basis(n_node), u_test(n_node), q_basis(n_q_basis, DIM),
       q_test(n_q_basis, DIM), p_basis(n_p_basis), p_test(n_p_basis),
       div_q_basis_ds(n_q_basis), div_q_test_ds(n_q_basis);
     DShape dpsidx(n_node, DIM), du_basis_dx(n_node, DIM),
       du_test_dx(n_node, DIM);
     // Get the number of integration points
     unsigned n_intpt = integral_pt()->nweight();
     // Storage for the local coordinates
     Vector<double> s(DIM);
     // Storage for the elasticity source function
     Vector<double> f_solid(DIM);
     // Storage for the source function
     Vector<double> f_fluid(DIM);
     // Storage for the mass source function
     double mass_source_local;
     // Storage for Lambda_sq
     double lambda_sq = this->lambda_sq();
     // Get the value of 1/k
     double k_inv = this->k_inv();
     // Get the value of alpha
     double alpha = this->alpha();
     // Get the value of the porosity
     double porosity = this->porosity();
     // Get the density ratio
     double density_ratio = this->density_ratio();
     // Precompute the ratio of fluid density to combined density
     double rho_f_over_rho =
       density_ratio / (1 + porosity * (density_ratio - 1));
     // Get continuous time from timestepper of first node
     double time = node_pt(0)->time_stepper_pt()->time_pt()->time();
     // Local equation and unknown numbers
     int local_eqn = 0, local_unknown = 0;
     // Loop over the integration points
     for (unsigned ipt = 0; ipt < n_intpt; ipt++)
     {
       // Find the local coordinates at the integration point
       for (unsigned i = 0; i < DIM; i++)
       {
         s[i] = integral_pt()->knot(ipt, i);
       }
       // Get the weight of the intetgration point
       double w = integral_pt()->weight(ipt);
       // Call the basis functions and test functions and get the
       // (geometric) jacobian of the current element
       double J = shape_basis_test_local_at_knot(ipt,
                                                 psi,
                                                 dpsidx,
                                                 u_basis,
                                                 u_test,
                                                 du_basis_dx,
                                                 du_test_dx,
                                                 q_basis,
                                                 q_test,
                                                 p_basis,
                                                 p_test,
                                                 div_q_basis_ds,
                                                 div_q_test_ds);
       // Storage for interpolated values
       Vector<double> interpolated_x(DIM, 0.0);
       Vector<double> interpolated_u(DIM, 0.0);
       DenseMatrix<double> interpolated_du_dx(DIM, DIM, 0.0);
       double interpolated_div_du_dt_dx = 0.0;
       Vector<double> interpolated_d2u_dt2(DIM, 0.0);
       Vector<double> interpolated_q(DIM, 0.0);
       double interpolated_div_q_ds = 0.0;
       Vector<double> interpolated_dq_dt(DIM, 0.0);
       double interpolated_p = 0.0;
       // loop over the vector basis functions to find interpolated x
       for (unsigned l = 0; l < n_node; l++)
       {
         // Loop over the geometric basis functions
         for (unsigned i = 0; i < DIM; i++)
         {
           interpolated_x[i] += nodal_position(l, i) * psi(l);
           interpolated_d2u_dt2[i] += this->d2u_dt2(l, i) * u_basis(l);
           // Get the nodal displacements
           const double u_value = this->raw_nodal_value(l, u_index(i));
           interpolated_u[i] += u_value * u_basis(l);
           // Loop over derivative directions
           for (unsigned j = 0; j < DIM; j++)
           {
             interpolated_du_dx(i, j) += u_value * du_basis_dx(l, j);
           }
           // divergence of the time derivative of the solid displacement
           interpolated_div_du_dt_dx += this->du_dt(l, i) * du_basis_dx(l, i);
         }
       }
       // loop over the nodes and use the geometric basis functions to find the
       // interpolated flux and its time derivative
       for (unsigned i = 0; i < DIM; i++)
       {
         // Loop over the edge basis vectors
         for (unsigned l = 0; l < n_q_basis_edge; l++)
         {
           interpolated_q[i] += q_edge(l) * q_basis(l, i);
           interpolated_dq_dt[i] += dq_edge_dt(l) * q_basis(l, i);
         }
         // Loop over the internal basis vectors
         for (unsigned l = n_q_basis_edge; l < n_q_basis; l++)
         {
           interpolated_q[i] += q_internal(l - n_q_basis_edge) * q_basis(l, i);
           interpolated_dq_dt[i] +=
             dq_internal_dt(l - n_q_basis_edge) * q_basis(l, i);
         }
       }
       // loop over the pressure basis and find the interpolated pressure
       for (unsigned l = 0; l < n_p_basis; l++)
       {
         interpolated_p += p_value(l) * p_basis(l);
       }
       // loop over the u edge divergence basis and the u internal divergence
       // basis to find interpolated div u
       for (unsigned l = 0; l < n_q_basis_edge; l++)
       {
         interpolated_div_q_ds += q_edge(l) * div_q_basis_ds(l);
       }
       for (unsigned l = n_q_basis_edge; l < n_q_basis; l++)
       {
         interpolated_div_q_ds +=
           q_internal(l - n_q_basis_edge) * div_q_basis_ds(l);
       }
       // Get the solid forcing
       this->force_solid(time, interpolated_x, f_solid);
       // Get the fluid forcing
       this->force_fluid(time, interpolated_x, f_fluid);
       // Get the mass source function
       this->mass_source(time, interpolated_x, mass_source_local);
       // Premultiply the weights and the Jacobian
       double W = w * J;
       // Linear elasticity:
       for (unsigned l = 0; l < n_node; l++)
       {
         for (unsigned a = 0; a < DIM; a++)
         {
           local_eqn = this->nodal_local_eqn(l, u_index(a));
           if (local_eqn >= 0)
           {
             residuals[local_eqn] +=
               (lambda_sq * (interpolated_d2u_dt2[a] +
                             rho_f_over_rho * interpolated_dq_dt[a]) -
                f_solid[a]) *
               u_test(l) * W;
             // Stress term
             for (unsigned b = 0; b < DIM; b++)
             {
               if (a == b)
               {
                 residuals[local_eqn] -=
                   alpha * interpolated_p * du_test_dx(l, b) * W;
               }
               for (unsigned c = 0; c < DIM; c++)
               {
                 for (unsigned d = 0; d < DIM; d++)
                 {
                   // Add the stress terms to the residuals
                   residuals[local_eqn] += this->E(a, b, c, d) *
                                           interpolated_du_dx(c, d) *
                                           du_test_dx(l, b) * W;
                 }
               }
             }
             // Jacobian entries
             if (flag)
             {
               // d(u_eqn_l,a)/d(U_l2,c)
               for (unsigned l2 = 0; l2 < n_node; l2++)
               {
                 for (unsigned c = 0; c < DIM; c++)
                 {
                   local_unknown = this->nodal_local_eqn(l2, u_index(c));
                   if (local_unknown >= 0)
                   {
                     if (a == c)
                     {
                       jacobian(local_eqn, local_unknown) +=
                         lambda_sq *
                         this->node_pt(l2)->time_stepper_pt()->weight(2, 0) *
                         u_basis(l2) * u_test(l) * W;
                     }
                     for (unsigned b = 0; b < DIM; b++)
                     {
                       for (unsigned d = 0; d < DIM; d++)
                       {
                         jacobian(local_eqn, local_unknown) +=
                           this->E(a, b, c, d) * du_basis_dx(l2, d) *
                           du_test_dx(l, b) * W;
                       }
                     }
                   }
                 }
               }
               // d(u_eqn_l,a)/d(Q_l2)
               for (unsigned l2 = 0; l2 < n_q_basis; l2++)
               {
                 TimeStepper* timestepper_pt = 0;
                 if (l2 < n_q_basis_edge)
                 {
                   local_unknown = q_edge_local_eqn(l2);
                   timestepper_pt =
                     this->node_pt(q_edge_node_number(l2))->time_stepper_pt();
                 }
                 else // n_q_basis_edge <= l < n_basis
                 {
                   local_unknown = q_internal_local_eqn(l2 - n_q_basis_edge);
                   timestepper_pt = this->internal_data_pt(q_internal_index())
                                      ->time_stepper_pt();
                 }
                 if (local_unknown >= 0)
                 {
                   jacobian(local_eqn, local_unknown) +=
                     lambda_sq * rho_f_over_rho * timestepper_pt->weight(1, 0) *
                     q_basis(l2, a) * u_test(l) * W;
                 }
               }
               // d(u_eqn_l,a)/d(P_l2)
               for (unsigned l2 = 0; l2 < n_p_basis; l2++)
               {
                 local_unknown = p_local_eqn(l2);
                 if (local_unknown >= 0)
                 {
                   jacobian(local_eqn, local_unknown) -=
                     alpha * p_basis(l2) * du_test_dx(l, a) * W;
                 }
               }
             } // End of Jacobian entries
           } // End of if not boundary condition
         } // End of loop over dimensions
       } // End of loop over u test functions
       // Darcy:
       // Loop over the test functions
       for (unsigned l = 0; l < n_q_basis; l++)
       {
         if (l < n_q_basis_edge)
         {
           local_eqn = q_edge_local_eqn(l);
         }
         else // n_q_basis_edge <= l < n_basis
         {
           local_eqn = q_internal_local_eqn(l - n_q_basis_edge);
         }
         // If it's not a boundary condition
         if (local_eqn >= 0)
         {
           for (unsigned i = 0; i < DIM; i++)
           {
             residuals[local_eqn] +=
               (k_inv * interpolated_q[i] - rho_f_over_rho * f_fluid[i] +
                rho_f_over_rho * lambda_sq *
                  (interpolated_d2u_dt2[i] +
                   (1.0 / porosity) * interpolated_dq_dt[i])) *
               q_test(l, i) * w * J;
           }
           // deliberately no jacobian factor in this integral
           residuals[local_eqn] -= (interpolated_p * div_q_test_ds(l)) * w;
           // Jacobian entries
           if (flag)
           {
             // d(q_eqn_l)/d(U_l2,c)
             for (unsigned l2 = 0; l2 < n_node; l2++)
             {
               for (unsigned c = 0; c < DIM; c++)
               {
                 local_unknown = this->nodal_local_eqn(l2, u_index(c));
                 if (local_unknown >= 0)
                 {
                   jacobian(local_eqn, local_unknown) +=
                     rho_f_over_rho * lambda_sq *
                     this->node_pt(l2)->time_stepper_pt()->weight(2, 0) *
                     u_basis(l2) * q_test(l, c) * W;
                 }
               }
             }
             // d(q_eqn_l)/d(Q_l2)
             for (unsigned l2 = 0; l2 < n_q_basis; l2++)
             {
               TimeStepper* timestepper_pt = 0;
               if (l2 < n_q_basis_edge)
               {
                 local_unknown = q_edge_local_eqn(l2);
                 timestepper_pt =
                   this->node_pt(q_edge_node_number(l2))->time_stepper_pt();
               }
               else // n_q_basis_edge <= l < n_basis
               {
                 local_unknown = q_internal_local_eqn(l2 - n_q_basis_edge);
                 timestepper_pt =
                   this->internal_data_pt(q_internal_index())->time_stepper_pt();
               }
               if (local_unknown >= 0)
               {
                 for (unsigned c = 0; c < DIM; c++)
                 {
                   jacobian(local_eqn, local_unknown) +=
                     q_basis(l2, c) * q_test(l, c) *
                     (k_inv + rho_f_over_rho * lambda_sq *
                                timestepper_pt->weight(1, 0) / porosity) *
                     W;
                 }
               }
             }
             // d(q_eqn_l)/d(P_l2)
             for (unsigned l2 = 0; l2 < n_p_basis; l2++)
             {
               local_unknown = p_local_eqn(l2);
               // deliberately no jacobian factor in this term
               jacobian(local_eqn, local_unknown) -=
                 p_basis(l2) * div_q_test_ds(l) * w;
             }
           } // End of Jacobian entries
         } // End of if not boundary condition
       } // End of loop over q test functions
       // loop over pressure test functions
       for (unsigned l = 0; l < n_p_basis; l++)
       {
         // get the local equation number
         local_eqn = p_local_eqn(l);
         // If it's not a boundary condition
         if (local_eqn >= 0)
         {
           // solid divergence term
           residuals[local_eqn] +=
             alpha * interpolated_div_du_dt_dx * p_test(l) * w * J;
           // fluid divergence term - deliberately no jacobian factor in this
           // term
           residuals[local_eqn] += interpolated_div_q_ds * p_test(l) * w;
           // mass source term
           residuals[local_eqn] -= mass_source_local * p_test(l) * w * J;
           // Jacobian entries
           if (flag)
           {
             // d(p_eqn_l)/d(U_l2,c)
             for (unsigned l2 = 0; l2 < n_node; l2++)
             {
               for (unsigned c = 0; c < DIM; c++)
               {
                 local_unknown = this->nodal_local_eqn(l2, u_index(c));
                 if (local_unknown >= 0)
                 {
                   jacobian(local_eqn, local_unknown) +=
                     alpha * this->node_pt(l2)->time_stepper_pt()->weight(1, 0) *
                     du_basis_dx(l2, c) * p_test(l) * W;
                 }
               }
             }
             // d(p_eqn_l)/d(Q_l2)
             for (unsigned l2 = 0; l2 < n_q_basis; l2++)
             {
               if (l2 < n_q_basis_edge)
               {
                 local_unknown = q_edge_local_eqn(l2);
               }
               else // n_q_basis_edge <= l < n_basis
               {
                 local_unknown = q_internal_local_eqn(l2 - n_q_basis_edge);
               }
               if (local_unknown >= 0)
               {
                 jacobian(local_eqn, local_unknown) +=
                   p_test(l) * div_q_basis_ds(l2) * w;
               }
             }
           } // End of Jacobian entries
         } // End of if not boundary condition
       } // End of loop over p test functions
     } // End of loop over integration points
   }
References DIM, and s.
Referenced by oomph::PoroelasticityEquations< DIM >::fill_in_contribution_to_jacobian(), and oomph::PoroelasticityEquations< DIM >::fill_in_contribution_to_residuals().
force_fluid()
template<unsigned DIM> void oomph::PoroelasticityEquations< DIM >::force_fluid (const double & time, const Vector< double > & x, Vector< double > & b) const inline
Indirect access to the fluid forcing function - returns 0 if no forcing function has been set
     {
       // If no function has been set, return zero vector
       if (Force_fluid_fct_pt == 0)
       {
         // Get spatial dimension of element
         unsigned n = dim();
         for (unsigned i = 0; i < n; i++)
         {
           b[i] = 0.0;
         }
       }
       else
       {
         (*Force_fluid_fct_pt)(time, x, b);
       }
     }
References b, oomph::FiniteElement::dim(), oomph::PoroelasticityEquations< DIM >::Force_fluid_fct_pt, i, n, and plotDoE::x.
force_fluid_fct_pt() [1/2]
template<unsigned DIM> SourceFctPt& oomph::PoroelasticityEquations< DIM >::force_fluid_fct_pt () inline
Access function: Pointer to fluid force function.
     {
       return Force_fluid_fct_pt;
     }
References oomph::PoroelasticityEquations< DIM >::Force_fluid_fct_pt.
force_fluid_fct_pt() [2/2]
template<unsigned DIM> SourceFctPt oomph::PoroelasticityEquations< DIM >::force_fluid_fct_pt () const inline
Access function: Pointer to fluid force function (const version)
     {
       return Force_fluid_fct_pt;
     }
References oomph::PoroelasticityEquations< DIM >::Force_fluid_fct_pt.
force_solid()
template<unsigned DIM> void oomph::PoroelasticityEquations< DIM >::force_solid (const double & time, const Vector< double > & x, Vector< double > & b) const inline
Indirect access to the solid force function - returns 0 if no forcing function has been set
     {
       // If no function has been set, return zero vector
       if (Force_solid_fct_pt == 0)
       {
         // Get spatial dimension of element
         unsigned n = dim();
         for (unsigned i = 0; i < n; i++)
         {
           b[i] = 0.0;
         }
       }
       else
       {
         (*Force_solid_fct_pt)(time, x, b);
       }
     }
References b, oomph::FiniteElement::dim(), oomph::PoroelasticityEquations< DIM >::Force_solid_fct_pt, i, n, and plotDoE::x.
force_solid_fct_pt() [1/2]
template<unsigned DIM> SourceFctPt& oomph::PoroelasticityEquations< DIM >::force_solid_fct_pt () inline
Access function: Pointer to solid force function.
     {
       return Force_solid_fct_pt;
     }
References oomph::PoroelasticityEquations< DIM >::Force_solid_fct_pt.
force_solid_fct_pt() [2/2]
template<unsigned DIM> SourceFctPt oomph::PoroelasticityEquations< DIM >::force_solid_fct_pt () const inline
Access function: Pointer to solid force function (const version)
     {
       return Force_solid_fct_pt;
     }
References oomph::PoroelasticityEquations< DIM >::Force_solid_fct_pt.
get_div_q_basis_local()
template<unsigned DIM> virtual void oomph::PoroelasticityEquations< DIM >::get_div_q_basis_local (const Vector< double > & s, Shape & div_q_basis_ds) const pure virtual
Returns the local form of the q basis and dbasis/ds at local coordinate s
Implemented in oomph::TPoroelasticityElement< ORDER >, oomph::TPoroelasticityElement< ORDER >, and oomph::TPoroelasticityElement< ORDER >.
Referenced by oomph::PoroelasticityEquations< DIM >::interpolated_div_q().
get_p_basis()
template<unsigned DIM> virtual void oomph::PoroelasticityEquations< DIM >::get_p_basis (const Vector< double > & s, Shape & p_basis) const pure virtual
Return the pressure basis.
Implemented in oomph::TPoroelasticityElement< ORDER >, oomph::TPoroelasticityElement< ORDER >, and oomph::TPoroelasticityElement< ORDER >.
Referenced by oomph::PoroelasticityEquations< DIM >::interpolated_p().
get_q_basis()
template<unsigned DIM> void oomph::PoroelasticityEquations< DIM >::get_q_basis (const Vector< double > & s, Shape & q_basis) const inline
Returns the transformed basis at local coordinate s.
     {
       const unsigned n_node = this->nnode();
       Shape psi(n_node, DIM);
       const unsigned n_q_basis = this->nq_basis();
       Shape q_basis_local(n_q_basis, DIM);
       this->get_q_basis_local(s, q_basis_local);
       (void)this->transform_basis(s, q_basis_local, psi, q_basis);
     }
References DIM, oomph::PoroelasticityEquations< DIM >::get_q_basis_local(), oomph::FiniteElement::nnode(), oomph::PoroelasticityEquations< DIM >::nq_basis(), and oomph::PoroelasticityEquations< DIM >::transform_basis().
Referenced by oomph::PoroelasticityEquations< DIM >::interpolated_q().
get_q_basis_local()
template<unsigned DIM> virtual void oomph::PoroelasticityEquations< DIM >::get_q_basis_local (const Vector< double > & s, Shape & q_basis) const pure virtual
Returns the local form of the q basis at local coordinate s.
Implemented in oomph::TPoroelasticityElement< ORDER >, oomph::TPoroelasticityElement< ORDER >, and oomph::TPoroelasticityElement< ORDER >.
Referenced by oomph::PoroelasticityEquations< DIM >::get_q_basis().
get_strain()
template<unsigned DIM> void oomph::PoroelasticityEquations< DIM >::get_strain (const Vector< double > & s, DenseMatrix< double > & strain) const
Return the strain tensor.
Compute the strain tensor at local coordinate s.
Now fill in the entries of the strain tensor
   {
 #ifdef PARANOID
     if ((strain.ncol() != DIM) || (strain.nrow() != DIM))
     {
       std::ostringstream error_message;
       error_message << "Strain matrix is " << strain.ncol() << " x "
                     << strain.nrow() << ", but dimension of the equations is "
                     << DIM << std::endl;
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
     /*
     //Find out how many position types there are
     unsigned n_position_type = this->nnodal_position_type();
     if(n_position_type != 1)
      {
       throw OomphLibError(
        "PoroElasticity is not yet implemented for more than one position type",
        OOMPH_CURRENT_FUNCTION,
        OOMPH_EXCEPTION_LOCATION);
      }
     */
 #endif
     // Find out how many nodes there are in the element
     unsigned n_node = nnode();
     // Find the indices at which the local velocities are stored
     unsigned u_nodal_index[DIM];
     for (unsigned i = 0; i < DIM; i++)
     {
       u_nodal_index[i] = u_index(i);
     }
     // Set up memory for the shape and derivative functions
     Shape psi(n_node);
     DShape dpsidx(n_node, DIM);
     // Call the derivatives of the shape functions
     (void)dshape_eulerian(s, psi, dpsidx);
     // Calculate interpolated values of the derivative of global position
     DenseMatrix<double> interpolated_dudx(DIM, DIM, 0.0);
     // Loop over nodes
     for (unsigned l = 0; l < n_node; l++)
     {
       // Loop over velocity components
       for (unsigned i = 0; i < DIM; i++)
       {
         // Get the nodal value
         const double u_value = this->nodal_value(l, u_nodal_index[i]);
         // Loop over derivative directions
         for (unsigned j = 0; j < DIM; j++)
         {
           interpolated_dudx(i, j) += u_value * dpsidx(l, j);
         }
       }
     }
     for (unsigned i = 0; i < DIM; i++)
     {
       // Do upper half of matrix
       // Note that j must be signed here for the comparison test to work
       // Also i must be cast to an int
       for (int j = (DIM - 1); j >= static_cast<int>(i); j--)
       {
         // Off diagonal terms
         if (static_cast<int>(i) != j)
         {
           strain(i, j) =
             0.5 * (interpolated_dudx(i, j) + interpolated_dudx(j, i));
         }
         // Diagonal terms will including growth factor when it comes back in
         else
         {
           strain(i, i) = interpolated_dudx(i, i);
         }
       }
       // Matrix is symmetric so just copy lower half
       for (int j = (i - 1); j >= 0; j--)
       {
         strain(i, j) = strain(j, i);
       }
     }
   }
References DIM, i, j, oomph::DenseMatrix< T >::ncol(), oomph::DenseMatrix< T >::nrow(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and s.
get_stress()
template<unsigned DIM> void oomph::PoroelasticityEquations< DIM >::get_stress (const Vector< double > & s, DenseMatrix< double > & stress) const
Return the Cauchy stress tensor, as calculated from the elasticity tensor at specified local coordinate
Compute the Cauchy stress tensor at local coordinate s for displacement formulation.
   {
 #ifdef PARANOID
     if ((stress.ncol() != DIM) || (stress.nrow() != DIM))
     {
       std::ostringstream error_message;
       error_message << "Stress matrix is " << stress.ncol() << " x "
                     << stress.nrow() << ", but dimension of the equations is "
                     << DIM << std::endl;
       throw OomphLibError(
         error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
 #endif
     // Get strain
     DenseMatrix<double> strain(DIM, DIM);
     this->get_strain(s, strain);
     // Now fill in the entries of the stress tensor without exploiting
     // symmetry -- sorry too lazy. This fct is only used for
     // postprocessing anyway...
     for (unsigned i = 0; i < DIM; i++)
     {
       for (unsigned j = 0; j < DIM; j++)
       {
         stress(i, j) = 0.0;
         for (unsigned k = 0; k < DIM; k++)
         {
           for (unsigned l = 0; k < DIM; k++)
           {
             stress(i, j) += this->E(i, j, k, l) * strain(k, l);
           }
         }
       }
     }
   }
References DIM, Global_Physical_Variables::E, i, j, k, oomph::DenseMatrix< T >::ncol(), oomph::DenseMatrix< T >::nrow(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and s.
interpolated_div_q() [1/2]
template<unsigned DIM> double oomph::PoroelasticityEquations< DIM >::interpolated_div_q (const Vector< double > & s) inline
Calculate the FE representation of div q and return it.
     {
       // Temporary storage for div u
       double div_q = 0;
       // Get the intepolated divergence
       interpolated_div_q(s, div_q);
       // Return it
       return div_q;
     }
References oomph::PoroelasticityEquations< DIM >::interpolated_div_q(), and s.
interpolated_div_q() [2/2]
template<unsigned DIM> void oomph::PoroelasticityEquations< DIM >::interpolated_div_q (const Vector< double > & s, double & div_q) const inline
Calculate the FE representation of div u.
     {
       // Zero the divergence
       div_q = 0;
       // Get the number of nodes, q basis function, and q edge basis functions
       unsigned n_node = nnode();
       const unsigned n_q_basis = nq_basis();
       const unsigned n_q_basis_edge = nq_basis_edge();
       // Storage for the divergence basis
       Shape div_q_basis_ds(n_q_basis);
       // Storage for the geometric basis and it's derivatives
       Shape psi(n_node);
       DShape dpsi(n_node, DIM);
       // Call the geometric shape functions and their derivatives
       this->dshape_local(s, psi, dpsi);
       // Storage for the inverse of the geometric jacobian (just so we can call
       // the local to eulerian mapping)
       DenseMatrix<double> inverse_jacobian(DIM);
       // Get the determinant of the geometric mapping
       double det = local_to_eulerian_mapping(dpsi, inverse_jacobian);
       // Get the divergence basis (wrt local coords) at local coords s
       get_div_q_basis_local(s, div_q_basis_ds);
       // Add the contribution to the divergence from the edge basis functions
       for (unsigned l = 0; l < n_q_basis_edge; l++)
       {
         div_q += 1.0 / det * div_q_basis_ds(l) * q_edge(l);
       }
       // Add the contribution to the divergence from the internal basis
       // functions
       for (unsigned l = n_q_basis_edge; l < n_q_basis; l++)
       {
         div_q += 1.0 / det * div_q_basis_ds(l) * q_internal(l - n_q_basis_edge);
       }
     }
References DIM, oomph::FiniteElement::dshape_local(), oomph::PoroelasticityEquations< DIM >::get_div_q_basis_local(), oomph::FiniteElement::local_to_eulerian_mapping(), oomph::FiniteElement::nnode(), oomph::PoroelasticityEquations< DIM >::nq_basis(), oomph::PoroelasticityEquations< DIM >::nq_basis_edge(), oomph::PoroelasticityEquations< DIM >::q_edge(), oomph::PoroelasticityEquations< DIM >::q_internal(), and s.
Referenced by oomph::PoroelasticityEquations< DIM >::interpolated_div_q().
interpolated_p() [1/2]
template<unsigned DIM> double oomph::PoroelasticityEquations< DIM >::interpolated_p (const Vector< double > & s) const inline
Calculate the FE representation of p and return it.
     {
       // Temporary storage for p
       double p = 0;
       // Get the interpolated pressure
       interpolated_p(s, p);
       // Return it
       return p;
     }
References oomph::PoroelasticityEquations< DIM >::interpolated_p(), p, and s.
interpolated_p() [2/2]
template<unsigned DIM> void oomph::PoroelasticityEquations< DIM >::interpolated_p (const Vector< double > & s, double & p) const inline
Calculate the FE representation of p.
     {
       // Get the number of p basis functions
       unsigned n_p_basis = np_basis();
       // Storage for the p basis
       Shape p_basis(n_p_basis);
       // Call the p basis
       get_p_basis(s, p_basis);
       // Zero the pressure
       p = 0;
       // Add the contribution to the pressure from each basis function
       for (unsigned l = 0; l < n_p_basis; l++)
       {
         p += p_value(l) * p_basis(l);
       }
     }
References oomph::PoroelasticityEquations< DIM >::get_p_basis(), oomph::PoroelasticityEquations< DIM >::np_basis(), p, oomph::PoroelasticityEquations< DIM >::p_value(), and s.
Referenced by oomph::PoroelasticityEquations< DIM >::interpolated_p().
interpolated_q() [1/2]
template<unsigned DIM> double oomph::PoroelasticityEquations< DIM >::interpolated_q (const Vector< double > & s, const unsigned i) const inline
Calculate the FE representation of the i-th component of q.
     {
       unsigned n_q_basis = nq_basis();
       unsigned n_q_basis_edge = nq_basis_edge();
       Shape q_basis(n_q_basis, DIM);
       get_q_basis(s, q_basis);
       double q_i = 0.0;
       for (unsigned l = 0; l < n_q_basis_edge; l++)
       {
         q_i += q_edge(l) * q_basis(l, i);
       }
       for (unsigned l = n_q_basis_edge; l < n_q_basis; l++)
       {
         q_i += q_internal(l - n_q_basis_edge) * q_basis(l, i);
       }
       return q_i;
     }
References DIM, oomph::PoroelasticityEquations< DIM >::get_q_basis(), i, oomph::PoroelasticityEquations< DIM >::nq_basis(), oomph::PoroelasticityEquations< DIM >::nq_basis_edge(), oomph::PoroelasticityEquations< DIM >::q_edge(), oomph::PoroelasticityEquations< DIM >::q_internal(), and s.
interpolated_q() [2/2]
template<unsigned DIM> void oomph::PoroelasticityEquations< DIM >::interpolated_q (const Vector< double > & s, Vector< double > & u) const inline
Calculate the FE representation of q.
     {
       unsigned n_q_basis = nq_basis();
       unsigned n_q_basis_edge = nq_basis_edge();
       Shape q_basis(n_q_basis, DIM);
       get_q_basis(s, q_basis);
       for (unsigned i = 0; i < DIM; i++)
       {
         u[i] = 0.0;
         for (unsigned l = 0; l < n_q_basis_edge; l++)
         {
           u[i] += q_edge(l) * q_basis(l, i);
         }
         for (unsigned l = n_q_basis_edge; l < n_q_basis; l++)
         {
           u[i] += q_internal(l - n_q_basis_edge) * q_basis(l, i);
         }
       }
     }
References DIM, oomph::PoroelasticityEquations< DIM >::get_q_basis(), i, oomph::PoroelasticityEquations< DIM >::nq_basis(), oomph::PoroelasticityEquations< DIM >::nq_basis_edge(), oomph::PoroelasticityEquations< DIM >::q_edge(), oomph::PoroelasticityEquations< DIM >::q_internal(), and s.
interpolated_u() [1/2]
template<unsigned DIM> double oomph::PoroelasticityEquations< DIM >::interpolated_u (const Vector< double > & s, const unsigned & i) const inline
Calculate the FE representation of the i-th component of u.
     {
       // Find number of nodes
       unsigned n_node = nnode();
       // Local shape function
       Shape psi(n_node);
       // Find values of shape function
       shape(s, psi);
       // Get nodal index at which i-th velocity is stored
       unsigned u_nodal_index = u_index(i);
       // Initialise value of u
       double interpolated_u = 0.0;
       // Loop over the local nodes and sum
       for (unsigned l = 0; l < n_node; l++)
       {
         interpolated_u += nodal_value(l, u_nodal_index) * psi[l];
       }
       return (interpolated_u);
     }
References i, oomph::PoroelasticityEquations< DIM >::interpolated_u(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), and oomph::PoroelasticityEquations< DIM >::u_index().
interpolated_u() [2/2]
template<unsigned DIM> void oomph::PoroelasticityEquations< DIM >::interpolated_u (const Vector< double > & s, Vector< double > & disp) const inline
Calculate the FE representation of u.
     {
       // Find number of nodes
       unsigned n_node = nnode();
       // Local shape function
       Shape psi(n_node);
       // Find values of shape function
       shape(s, psi);
       for (unsigned i = 0; i < DIM; i++)
       {
         // Index at which the nodal value is stored
         unsigned u_nodal_index = u_index(i);
         // Initialise value of u
         disp[i] = 0.0;
         // Loop over the local nodes and sum
         for (unsigned l = 0; l < n_node; l++)
         {
           disp[i] += nodal_value(l, u_nodal_index) * psi[l];
         }
       }
     }
References DIM, i, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), s, oomph::FiniteElement::shape(), and oomph::PoroelasticityEquations< DIM >::u_index().
Referenced by oomph::PoroelasticityEquations< DIM >::interpolated_u().
k_inv()
template<unsigned DIM> const double& oomph::PoroelasticityEquations< DIM >::k_inv () const inline
Access function for the nondim inverse permeability.
     {
       return *K_inv_pt;
     }
References oomph::PoroelasticityEquations< DIM >::K_inv_pt.
k_inv_pt()
template<unsigned DIM> double*& oomph::PoroelasticityEquations< DIM >::k_inv_pt () inline
Access function for pointer to the nondim inverse permeability.
     {
       return K_inv_pt;
     }
References oomph::PoroelasticityEquations< DIM >::K_inv_pt.
lambda_sq()
template<unsigned DIM> const double& oomph::PoroelasticityEquations< DIM >::lambda_sq () const inline
Access function for timescale ratio (nondim density)
     {
       return *Lambda_sq_pt;
     }
References oomph::PoroelasticityEquations< DIM >::Lambda_sq_pt.
lambda_sq_pt()
template<unsigned DIM> double*& oomph::PoroelasticityEquations< DIM >::lambda_sq_pt () inline
Access function for pointer to timescale ratio (nondim density)
     {
       return Lambda_sq_pt;
     }
References oomph::PoroelasticityEquations< DIM >::Lambda_sq_pt.
mass_source()
template<unsigned DIM> void oomph::PoroelasticityEquations< DIM >::mass_source (const double & time, const Vector< double > & x, double & b) const inline
Indirect access to the mass source function - returns 0 if no mass source function has been set
     {
       // If no function has been set, return zero vector
       if (Mass_source_fct_pt == 0)
       {
         b = 0.0;
       }
       else
       {
         (*Mass_source_fct_pt)(time, x, b);
       }
     }
References b, oomph::PoroelasticityEquations< DIM >::Mass_source_fct_pt, and plotDoE::x.
mass_source_fct_pt() [1/2]
template<unsigned DIM> MassSourceFctPt& oomph::PoroelasticityEquations< DIM >::mass_source_fct_pt () inline
Access function: Pointer to mass source function.
     {
       return Mass_source_fct_pt;
     }
References oomph::PoroelasticityEquations< DIM >::Mass_source_fct_pt.
mass_source_fct_pt() [2/2]
template<unsigned DIM> MassSourceFctPt oomph::PoroelasticityEquations< DIM >::mass_source_fct_pt () const inline
Access function: Pointer to mass source function (const version)
     {
       return Mass_source_fct_pt;
     }
References oomph::PoroelasticityEquations< DIM >::Mass_source_fct_pt.
nedge_gauss_point()
template<unsigned DIM> virtual unsigned oomph::PoroelasticityEquations< DIM >::nedge_gauss_point () const pure virtual
Returns the number of gauss points along each edge of the element.
Implemented in oomph::TPoroelasticityElement< ORDER >, oomph::TPoroelasticityElement< ORDER >, and oomph::TPoroelasticityElement< ORDER >.
np_basis()
template<unsigned DIM> virtual unsigned oomph::PoroelasticityEquations< DIM >::np_basis () const pure virtual
Return the total number of pressure basis functions.
Implemented in oomph::TPoroelasticityElement< ORDER >, oomph::TPoroelasticityElement< ORDER >, and oomph::TPoroelasticityElement< ORDER >.
Referenced by oomph::PoroelasticityEquations< DIM >::interpolated_p().
nq_basis()
template<unsigned DIM> virtual unsigned oomph::PoroelasticityEquations< DIM >::nq_basis () const pure virtual
Return the total number of computational basis functions for q.
Implemented in oomph::TPoroelasticityElement< ORDER >, oomph::TPoroelasticityElement< ORDER >, and oomph::TPoroelasticityElement< ORDER >.
Referenced by oomph::PoroelasticityEquations< DIM >::get_q_basis(), oomph::PoroelasticityEquations< DIM >::interpolated_div_q(), and oomph::PoroelasticityEquations< DIM >::interpolated_q().
nq_basis_edge()
template<unsigned DIM> virtual unsigned oomph::PoroelasticityEquations< DIM >::nq_basis_edge () const pure virtual
Return the number of edge basis functions for q.
Implemented in oomph::TPoroelasticityElement< ORDER >, oomph::TPoroelasticityElement< ORDER >, and oomph::TPoroelasticityElement< ORDER >.
Referenced by oomph::PoroelasticityEquations< DIM >::interpolated_div_q(), and oomph::PoroelasticityEquations< DIM >::interpolated_q().
output() [1/2]
template<unsigned DIM> void oomph::PoroelasticityEquations< DIM >::output (std::ostream & outfile) inline virtual
Output with default number of plot points.
Reimplemented from oomph::FiniteElement.
     {
       unsigned nplot = 5;
       output(outfile, nplot);
     }
Referenced by oomph::TPoroelasticityElement< ORDER >::output().
output() [2/2]
template<unsigned DIM> void oomph::PoroelasticityEquations< DIM >::output (std::ostream & outfile, const unsigned & nplot) virtual
Output FE representation of soln: x,y,u1,u2,div_q,p at Nplot^DIM plot points
Output FE representation of soln: x,y,u1,u2,q1,q2,div_q,p at Nplot^DIM plot points
Reimplemented from oomph::FiniteElement.
   {
     // Vector of local coordinates
     Vector<double> s(DIM);
     // Tecplot header info
     outfile << tecplot_zone_string(nplot);
     // Loop over plot points
     unsigned num_plot_points = nplot_points(nplot);
     for (unsigned iplot = 0; iplot < num_plot_points; iplot++)
     {
       // Get local coordinates of plot point
       get_s_plot(iplot, nplot, s);
       // Output the components of the position
       for (unsigned i = 0; i < DIM; i++)
       {
         outfile << interpolated_x(s, i) << " ";
       }
       // Output the components of the FE representation of u at s
       for (unsigned i = 0; i < DIM; i++)
       {
         outfile << interpolated_u(s, i) << " ";
       }
       // Output the components of the FE representation of q at s
       for (unsigned i = 0; i < DIM; i++)
       {
         outfile << interpolated_q(s, i) << " ";
       }
       // Output FE representation of div u at s
       outfile << interpolated_div_q(s) << " ";
       // Output FE representation of p at s
       outfile << interpolated_p(s) << " ";
       const unsigned n_node = this->nnode();
       Shape psi(n_node);
       shape(s, psi);
       Vector<double> interpolated_du_dt(DIM, 0.0);
       for (unsigned i = 0; i < DIM; i++)
       {
         for (unsigned l = 0; l < n_node; l++)
         {
           interpolated_du_dt[i] += du_dt(l, i) * psi(l);
         }
         outfile << interpolated_du_dt[i] << " ";
       }
       Vector<double> interpolated_d2u_dt2(DIM, 0.0);
       for (unsigned i = 0; i < DIM; i++)
       {
         for (unsigned l = 0; l < n_node; l++)
         {
           interpolated_d2u_dt2[i] += d2u_dt2(l, i) * psi(l);
         }
         outfile << interpolated_d2u_dt2[i] << " ";
       }
       const unsigned n_q_basis = this->nq_basis();
       const unsigned n_q_basis_edge = this->nq_basis_edge();
       Shape q_basis(n_q_basis, DIM), q_basis_local(n_q_basis, DIM);
       this->get_q_basis_local(s, q_basis_local);
       (void)this->transform_basis(s, q_basis_local, psi, q_basis);
       Vector<double> interpolated_dq_dt(DIM, 0.0);
       for (unsigned i = 0; i < DIM; i++)
       {
         for (unsigned l = 0; l < n_q_basis_edge; l++)
         {
           interpolated_dq_dt[i] += dq_edge_dt(l) * q_basis(l, i);
         }
         for (unsigned l = n_q_basis_edge; l < n_q_basis; l++)
         {
           interpolated_dq_dt[i] +=
             dq_internal_dt(l - n_q_basis_edge) * q_basis(l, i);
         }
         outfile << interpolated_dq_dt[i] << " ";
       }
       outfile << std::endl;
     }
     // Write tecplot footer (e.g. FE connectivity lists)
     this->write_tecplot_zone_footer(outfile, nplot);
   }
References DIM, i, s, and oomph::OneDimLagrange::shape().
output_fct() [1/2]
template<unsigned DIM> void oomph::PoroelasticityEquations< DIM >::output_fct (std::ostream & outfile, const unsigned & nplot, const double & time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) virtual
Output FE representation of exact soln: x,y,u1,u2,div_q,p at Nplot^DIM plot points. Unsteady version
Reimplemented from oomph::FiniteElement.
   {
     // Vector of local coordinates
     Vector<double> s(DIM);
     // Vector for coordintes
     Vector<double> x(DIM);
     // Tecplot header info
     outfile << this->tecplot_zone_string(nplot);
     // Exact solution Vector
     Vector<double> exact_soln(2 * DIM + 2);
     // Loop over plot points
     unsigned num_plot_points = this->nplot_points(nplot);
     for (unsigned iplot = 0; iplot < num_plot_points; iplot++)
     {
       // Get local coordinates of plot point
       this->get_s_plot(iplot, nplot, s);
       // Get x position as Vector
       this->interpolated_x(s, x);
       // Get exact solution at this point
       (*exact_soln_pt)(time, x, exact_soln);
       // Output x,y,q_exact,p_exact,div_q_exact
       for (unsigned i = 0; i < DIM; i++)
       {
         outfile << x[i] << " ";
       }
       for (unsigned i = 0; i < 2 * DIM + 2; i++)
       {
         outfile << exact_soln[i] << " ";
       }
       outfile << std::endl;
     }
     // Write tecplot footer (e.g. FE connectivity lists)
     this->write_tecplot_zone_footer(outfile, nplot);
   }
References DIM, ProblemParameters::exact_soln(), i, s, and plotDoE::x.
output_fct() [2/2]
template<unsigned DIM> void oomph::PoroelasticityEquations< DIM >::output_fct (std::ostream & outfile, const unsigned & nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) virtual
Output FE representation of exact soln: x,y,u1,u2,div_q,p at Nplot^DIM plot points
Output FE representation of exact soln: x,y,u1,u2,q1,q2,div_q,p at Nplot^DIM plot points
Reimplemented from oomph::FiniteElement.
   {
     // Vector of local coordinates
     Vector<double> s(DIM);
     // Vector for coordintes
     Vector<double> x(DIM);
     // Tecplot header info
     outfile << this->tecplot_zone_string(nplot);
     // Exact solution Vector
     Vector<double> exact_soln(2 * DIM + 2);
     // Loop over plot points
     unsigned num_plot_points = this->nplot_points(nplot);
     for (unsigned iplot = 0; iplot < num_plot_points; iplot++)
     {
       // Get local coordinates of plot point
       this->get_s_plot(iplot, nplot, s);
       // Get x position as Vector
       this->interpolated_x(s, x);
       // Get exact solution at this point
       (*exact_soln_pt)(x, exact_soln);
       // Output x,y,q_exact,p_exact,div_q_exact
       for (unsigned i = 0; i < DIM; i++)
       {
         outfile << x[i] << " ";
       }
       for (unsigned i = 0; i < 2 * DIM + 2; i++)
       {
         outfile << exact_soln[i] << " ";
       }
       outfile << std::endl;
     }
     // Write tecplot footer (e.g. FE connectivity lists)
     this->write_tecplot_zone_footer(outfile, nplot);
   }
References DIM, ProblemParameters::exact_soln(), i, s, and plotDoE::x.
p_local_eqn()
template<unsigned DIM> virtual int oomph::PoroelasticityEquations< DIM >::p_local_eqn (const unsigned & n) const pure virtual
Return the equation number of the n-th pressure degree of freedom.
Implemented in oomph::TPoroelasticityElement< ORDER >.
p_value()
template<unsigned DIM> virtual double oomph::PoroelasticityEquations< DIM >::p_value (unsigned & n) const pure virtual
Return the nth pressure value.
Implemented in oomph::TPoroelasticityElement< ORDER >.
Referenced by oomph::PoroelasticityEquations< DIM >::interpolated_p().
pin_p_value()
template<unsigned DIM> virtual void oomph::PoroelasticityEquations< DIM >::pin_p_value (const unsigned & n, const double & p) pure virtual
Pin the nth pressure value.
Implemented in oomph::TPoroelasticityElement< ORDER >.
pin_q_internal_value()
template<unsigned DIM> virtual void oomph::PoroelasticityEquations< DIM >::pin_q_internal_value (const unsigned & n) pure virtual
Pin the nth internal q value.
Implemented in oomph::TPoroelasticityElement< ORDER >.
porosity()
template<unsigned DIM> const double& oomph::PoroelasticityEquations< DIM >::porosity () const inline
Access function for the porosity.
     {
       return *Porosity_pt;
     }
References oomph::PoroelasticityEquations< DIM >::Porosity_pt.
porosity_pt()
template<unsigned DIM> double*& oomph::PoroelasticityEquations< DIM >::porosity_pt () inline
Access function for pointer to the porosity.
     {
       return Porosity_pt;
     }
References oomph::PoroelasticityEquations< DIM >::Porosity_pt.
q_edge() [1/2]
template<unsigned DIM> virtual double oomph::PoroelasticityEquations< DIM >::q_edge (const unsigned & n) const pure virtual
Return the values of the edge (flux) degrees of freedom.
Implemented in oomph::TPoroelasticityElement< ORDER >.
Referenced by oomph::PoroelasticityEquations< DIM >::dq_edge_dt(), oomph::PoroelasticityEquations< DIM >::interpolated_div_q(), and oomph::PoroelasticityEquations< DIM >::interpolated_q().
q_edge() [2/2]
template<unsigned DIM> virtual double oomph::PoroelasticityEquations< DIM >::q_edge (const unsigned & t, const unsigned & n) const pure virtual
Return the values of the edge (flux) degrees of freedom at time history level t
Implemented in oomph::TPoroelasticityElement< ORDER >.
q_edge_index()
template<unsigned DIM> virtual unsigned oomph::PoroelasticityEquations< DIM >::q_edge_index (const unsigned & n) const pure virtual
Return the nodal index at which the nth edge unknown is stored.
Implemented in oomph::TPoroelasticityElement< ORDER >.
q_edge_local_eqn()
template<unsigned DIM> virtual int oomph::PoroelasticityEquations< DIM >::q_edge_local_eqn (const unsigned & n) const pure virtual
Return the equation number of the n-th edge (flux) degree of freedom.
Implemented in oomph::TPoroelasticityElement< ORDER >.
q_edge_node_number()
template<unsigned DIM> virtual unsigned oomph::PoroelasticityEquations< DIM >::q_edge_node_number (const unsigned & n) const pure virtual
Return the number of the node where the nth edge unknown is stored.
Implemented in oomph::TPoroelasticityElement< ORDER >.
Referenced by oomph::PoroelasticityEquations< DIM >::dq_edge_dt().
q_internal() [1/2]
template<unsigned DIM> virtual double oomph::PoroelasticityEquations< DIM >::q_internal (const unsigned & n) const pure virtual
Return the values of the internal (moment) degrees of freedom.
Implemented in oomph::TPoroelasticityElement< ORDER >.
Referenced by oomph::PoroelasticityEquations< DIM >::dq_internal_dt(), oomph::PoroelasticityEquations< DIM >::interpolated_div_q(), and oomph::PoroelasticityEquations< DIM >::interpolated_q().
q_internal() [2/2]
template<unsigned DIM> virtual double oomph::PoroelasticityEquations< DIM >::q_internal (const unsigned & t, const unsigned & n) const pure virtual
Return the values of the internal (moment) degrees of freedom at time history level t
Implemented in oomph::TPoroelasticityElement< ORDER >.
q_internal_index()
template<unsigned DIM> virtual unsigned oomph::PoroelasticityEquations< DIM >::q_internal_index () const pure virtual
Return the index of the internal data where the q_internal degrees of freedom are stored
Implemented in oomph::TPoroelasticityElement< ORDER >.
Referenced by oomph::PoroelasticityEquations< DIM >::dq_internal_dt(), and oomph::PoroelasticityEquations< DIM >::set_q_internal_timestepper().
q_internal_local_eqn()
template<unsigned DIM> virtual int oomph::PoroelasticityEquations< DIM >::q_internal_local_eqn (const unsigned & n) const pure virtual
Return the equation number of the n-th internal (moment) degree of freedom
Implemented in oomph::TPoroelasticityElement< ORDER >.
required_nvalue()
template<unsigned DIM> virtual unsigned oomph::PoroelasticityEquations< DIM >::required_nvalue (const unsigned & n) const pure virtual
Number of values required at node n.
Reimplemented from oomph::FiniteElement.
Implemented in oomph::TPoroelasticityElement< ORDER >.
scale_basis()
template<unsigned DIM> virtual void oomph::PoroelasticityEquations< DIM >::scale_basis (Shape & basis) const pure virtual
Scale the edge basis to allow arbitrary edge mappings.
Implemented in oomph::TPoroelasticityElement< ORDER >.
self_test()
template<unsigned DIM> unsigned oomph::PoroelasticityEquations< DIM >::self_test () inline virtual
Self-test: Check inversion of element & do self-test for GeneralisedElement. Return 0 if OK.
Self-test: Have all internal values been classified as pinned/unpinned? Has pointer to spatial integration scheme been set? Return 0 if OK.
Reimplemented from oomph::FiniteElement.
     {
       return 0;
     }
set_q_internal_timestepper()
template<unsigned DIM> void oomph::PoroelasticityEquations< DIM >::set_q_internal_timestepper (TimeStepper *const time_stepper_pt) inline
Set the timestepper of the q internal data object.
     {
       unsigned q_index = q_internal_index();
       this->internal_data_pt(q_index)->set_time_stepper(time_stepper_pt, false);
     }
References oomph::GeneralisedElement::internal_data_pt(), oomph::PoroelasticityEquations< DIM >::q_internal_index(), oomph::Data::set_time_stepper(), and oomph::GeomObject::time_stepper_pt().
shape_basis_test_local()
template<unsigned DIM> virtual double oomph::PoroelasticityEquations< DIM >::shape_basis_test_local (const Vector< double > & s, Shape & psi, DShape & dpsi, Shape & u_basis, Shape & u_test, DShape & du_basis_dx, DShape & du_test_dx, Shape & q_basis, Shape & q_test, Shape & p_basis, Shape & p_test, Shape & div_q_basis_ds, Shape & div_q_test_ds) const protected pure virtual
Returns the geometric basis, and the q, p and divergence basis functions and test functions at local coordinate s
Implemented in oomph::TPoroelasticityElement< ORDER >.
shape_basis_test_local_at_knot()
template<unsigned DIM> virtual double oomph::PoroelasticityEquations< DIM >::shape_basis_test_local_at_knot (const unsigned & ipt, Shape & psi, DShape & dpsi, Shape & u_basis, Shape & u_test, DShape & du_basis_dx, DShape & du_test_dx, Shape & q_basis, Shape & q_test, Shape & p_basis, Shape & p_test, Shape & div_q_basis_ds, Shape & div_q_test_ds) const protected pure virtual
Returns the geometric basis, and the q, p and divergence basis functions and test functions at integration point ipt
Implemented in oomph::TPoroelasticityElement< ORDER >.
transform_basis() [1/2]
template<unsigned DIM> double oomph::PoroelasticityEquations< DIM >::transform_basis (const Vector< double > & s, const Shape & q_basis_local, Shape & psi, DShape & dpsi, Shape & q_basis) const
Performs a div-conserving transformation of the vector basis functions from the reference element to the actual element
   {
     // Call the (geometric) shape functions and their derivatives
     //(void)this->dshape_eulerian(s,psi,dpsi);
     this->dshape_local(s, psi, dpsi);
     // Storage for the (geometric) jacobian and its inverse
     DenseMatrix<double> jacobian(DIM), inverse_jacobian(DIM);
     // Get the jacobian of the geometric mapping and its determinant
     double det = local_to_eulerian_mapping(dpsi, jacobian, inverse_jacobian);
     // Transform the derivative of the geometric basis so that it's w.r.t.
     // global coordinates
     this->transform_derivatives(inverse_jacobian, dpsi);
     // Get the number of computational basis vectors
     const unsigned n_q_basis = this->nq_basis();
     // Loop over the basis vectors
     for (unsigned l = 0; l < n_q_basis; l++)
     {
       // Loop over the spatial components
       for (unsigned i = 0; i < DIM; i++)
       {
         // Zero the basis
         q_basis(l, i) = 0.0;
       }
     }
     // Loop over the spatial components
     for (unsigned i = 0; i < DIM; i++)
     {
       // And again
       for (unsigned j = 0; j < DIM; j++)
       {
         // Get the element of the jacobian (must transpose it due to different
         // conventions) and divide by the determinant
         double jac_trans = jacobian(j, i) / det;
         // Loop over the computational basis vectors
         for (unsigned l = 0; l < n_q_basis; l++)
         {
           // Apply the appropriate div-conserving mapping
           q_basis(l, i) += jac_trans * q_basis_local(l, j);
         }
       }
     }
     // Scale the basis by the ratio of the length of the edge to the length of
     // the corresponding edge on the reference element
     scale_basis(q_basis);
     return det;
   }
References DIM, i, j, and s.
Referenced by oomph::PoroelasticityEquations< DIM >::get_q_basis(), and oomph::PoroelasticityEquations< DIM >::transform_basis().
transform_basis() [2/2]
template<unsigned DIM> double oomph::PoroelasticityEquations< DIM >::transform_basis (const Vector< double > & s, const Shape & q_basis_local, Shape & psi, Shape & q_basis) const inline
Performs a div-conserving transformation of the vector basis functions from the reference element to the actual element
     {
       const unsigned n_node = this->nnode();
       DShape dpsi(n_node, DIM);
       return transform_basis(s, q_basis_local, psi, dpsi, q_basis);
     }
References DIM, oomph::FiniteElement::nnode(), s, and oomph::PoroelasticityEquations< DIM >::transform_basis().
u_index()
template<unsigned DIM> virtual unsigned oomph::PoroelasticityEquations< DIM >::u_index (const unsigned & n) const pure virtual
Return the nodal index of the n-th solid displacement unknown.
Implemented in oomph::TPoroelasticityElement< ORDER >.
Referenced by oomph::PoroelasticityEquations< DIM >::d2u_dt2(), oomph::PoroelasticityEquations< DIM >::du_dt(), and oomph::PoroelasticityEquations< DIM >::interpolated_u().
Member Data Documentation
Alpha_pt
template<unsigned DIM> double* oomph::PoroelasticityEquations< DIM >::Alpha_pt private
Alpha.
Referenced by oomph::PoroelasticityEquations< DIM >::alpha(), and oomph::PoroelasticityEquations< DIM >::alpha_pt().
Default_alpha_value
template<unsigned DIM> double oomph::PoroelasticityEquations< DIM >::Default_alpha_value = 1.0 static private
Static default value for alpha.
Default_density_ratio_value
template<unsigned DIM> double oomph::PoroelasticityEquations< DIM >::Default_density_ratio_value = 1.0 static private
Static default value for the density ratio.
Default_k_inv_value
template<unsigned DIM> double oomph::PoroelasticityEquations< DIM >::Default_k_inv_value = 1.0 static private
Static default value for 1/k.
Default_lambda_sq_value
template<unsigned DIM> double oomph::PoroelasticityEquations< DIM >::Default_lambda_sq_value = 1.0 static private
Static default value for timescale ratio (1.0 – for natural scaling)
Default_porosity_value
template<unsigned DIM> double oomph::PoroelasticityEquations< DIM >::Default_porosity_value = 1.0 static private
Static default value for the porosity.
Density_ratio_pt
template<unsigned DIM> double* oomph::PoroelasticityEquations< DIM >::Density_ratio_pt private
Density ratio.
Referenced by oomph::PoroelasticityEquations< DIM >::density_ratio(), and oomph::PoroelasticityEquations< DIM >::density_ratio_pt().
Elasticity_tensor_pt
template<unsigned DIM> ElasticityTensor* oomph::PoroelasticityEquations< DIM >::Elasticity_tensor_pt protected
Pointer to the elasticity tensor.
Referenced by oomph::PoroelasticityEquations< DIM >::E(), and oomph::PoroelasticityEquations< DIM >::elasticity_tensor_pt().
Force_fluid_fct_pt
template<unsigned DIM> SourceFctPt oomph::PoroelasticityEquations< DIM >::Force_fluid_fct_pt private
Pointer to fluid source function.
Referenced by oomph::PoroelasticityEquations< DIM >::force_fluid(), and oomph::PoroelasticityEquations< DIM >::force_fluid_fct_pt().
Force_solid_fct_pt
template<unsigned DIM> SourceFctPt oomph::PoroelasticityEquations< DIM >::Force_solid_fct_pt private
Pointer to solid source function.
Referenced by oomph::PoroelasticityEquations< DIM >::force_solid(), and oomph::PoroelasticityEquations< DIM >::force_solid_fct_pt().
K_inv_pt
template<unsigned DIM> double* oomph::PoroelasticityEquations< DIM >::K_inv_pt private
1/k
Referenced by oomph::PoroelasticityEquations< DIM >::k_inv(), and oomph::PoroelasticityEquations< DIM >::k_inv_pt().
Lambda_sq_pt
template<unsigned DIM> double* oomph::PoroelasticityEquations< DIM >::Lambda_sq_pt private
Timescale ratio (non-dim. density)
Referenced by oomph::PoroelasticityEquations< DIM >::lambda_sq(), and oomph::PoroelasticityEquations< DIM >::lambda_sq_pt().
Mass_source_fct_pt
template<unsigned DIM> MassSourceFctPt oomph::PoroelasticityEquations< DIM >::Mass_source_fct_pt private
Pointer to the mass source function.
Referenced by oomph::PoroelasticityEquations< DIM >::mass_source(), and oomph::PoroelasticityEquations< DIM >::mass_source_fct_pt().
Porosity_pt
template<unsigned DIM> double* oomph::PoroelasticityEquations< DIM >::Porosity_pt private
Porosity.
Referenced by oomph::PoroelasticityEquations< DIM >::porosity(), and oomph::PoroelasticityEquations< DIM >::porosity_pt().
The documentation for this class was generated from the following files:
poroelasticity_elements.h
poroelasticity_elements.cc