MercuryDPM: Eigen::internal::image_retval_base< DecompositionType_ > Class Template Reference
Eigen::internal::image_retval_base< DecompositionType_ > Class Template Reference
#include <Image.h>
Public Types
typedef DecompositionType_ DecompositionType
typedef DecompositionType::MatrixType MatrixType
typedef ReturnByValue< image_retval_base > Base
Public Types inherited from Eigen::ReturnByValue< image_retval_base< DecompositionType_ > >
typedef internal::traits< image_retval_base< DecompositionType_ > >::ReturnType ReturnType
typedef internal::dense_xpr_base< ReturnByValue >::type Base
Public Member Functions
image_retval_base (const DecompositionType &dec, const MatrixType &originalMatrix)
Index rows () const
Index cols () const
Index rank () const
const DecompositionType & dec () const
const MatrixType & originalMatrix () const
template<typename Dest >
void evalTo (Dest &dst) const
Public Member Functions inherited from Eigen::ReturnByValue< image_retval_base< DecompositionType_ > >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
const Unusable & coeff (Index) const
const Unusable & coeff (Index, Index) const
Unusable & coeffRef (Index)
Unusable & coeffRef (Index, Index)
Protected Attributes
const DecompositionType & m_dec
Index m_rank
Index m_cols
const MatrixType & m_originalMatrix
Member Typedef Documentation
Base
template<typename DecompositionType_ > typedef ReturnByValue<image_retval_base> Eigen::internal::image_retval_base< DecompositionType_ >::Base
DecompositionType
template<typename DecompositionType_ > typedef DecompositionType_ Eigen::internal::image_retval_base< DecompositionType_ >::DecompositionType
MatrixType
template<typename DecompositionType_ > typedef DecompositionType::MatrixType Eigen::internal::image_retval_base< DecompositionType_ >::MatrixType
Constructor & Destructor Documentation
image_retval_base()
template<typename DecompositionType_ > Eigen::internal::image_retval_base< DecompositionType_ >::image_retval_base (const DecompositionType & dec, const MatrixType & originalMatrix) inline
       : m_dec(dec), m_rank(dec.rank()), m_cols(m_rank == 0 ? 1 : m_rank), m_originalMatrix(originalMatrix) {}
Member Function Documentation
cols()
template<typename DecompositionType_ > Index Eigen::internal::image_retval_base< DecompositionType_ >::cols () const inline
 { return m_cols; }
References Eigen::internal::image_retval_base< DecompositionType_ >::m_cols.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
dec()
template<typename DecompositionType_ > const DecompositionType& Eigen::internal::image_retval_base< DecompositionType_ >::dec () const inline
 { return m_dec; }
References Eigen::internal::image_retval_base< DecompositionType_ >::m_dec.
evalTo()
template<typename DecompositionType_ > template<typename Dest > void Eigen::internal::image_retval_base< DecompositionType_ >::evalTo (Dest & dst) const inline
{
     static_cast<const image_retval<DecompositionType>*>(this)->evalTo(dst);
   }
originalMatrix()
template<typename DecompositionType_ > const MatrixType& Eigen::internal::image_retval_base< DecompositionType_ >::originalMatrix () const inline
 { return m_originalMatrix; }
References Eigen::internal::image_retval_base< DecompositionType_ >::m_originalMatrix.
rank()
template<typename DecompositionType_ > Index Eigen::internal::image_retval_base< DecompositionType_ >::rank () const inline
 { return m_rank; }
References Eigen::internal::image_retval_base< DecompositionType_ >::m_rank.
rows()
template<typename DecompositionType_ > Index Eigen::internal::image_retval_base< DecompositionType_ >::rows () const inline
 { return m_dec.rows(); }
References Eigen::internal::image_retval_base< DecompositionType_ >::m_dec.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
Member Data Documentation
m_cols
template<typename DecompositionType_ > Index Eigen::internal::image_retval_base< DecompositionType_ >::m_cols protected
Referenced by Eigen::internal::image_retval_base< DecompositionType_ >::cols().
m_dec
template<typename DecompositionType_ > const DecompositionType& Eigen::internal::image_retval_base< DecompositionType_ >::m_dec protected
Referenced by Eigen::internal::image_retval_base< DecompositionType_ >::dec(), and Eigen::internal::image_retval_base< DecompositionType_ >::rows().
m_originalMatrix
template<typename DecompositionType_ > const MatrixType& Eigen::internal::image_retval_base< DecompositionType_ >::m_originalMatrix protected
Referenced by Eigen::internal::image_retval_base< DecompositionType_ >::originalMatrix().
m_rank
template<typename DecompositionType_ > Index Eigen::internal::image_retval_base< DecompositionType_ >::m_rank protected
Referenced by Eigen::internal::image_retval_base< DecompositionType_ >::rank().
The documentation for this class was generated from the following files:
ForwardDeclarations.h
Image.h