MercuryDPM: Eigen::internal::product_selfadjoint_matrix< Scalar, Index, LhsStorageOrder, false, ConjugateLhs, RhsStorageOrder, true, ConjugateRhs, ColMajor, ResInnerStride > Struct Template Reference
Eigen::internal::product_selfadjoint_matrix< Scalar, Index, LhsStorageOrder, false, ConjugateLhs, RhsStorageOrder, true, ConjugateRhs, ColMajor, ResInnerStride > Struct Template Reference
#include <SelfadjointMatrixMatrix.h>
Static Public Member Functions
static EIGEN_DONT_INLINE void run (Index rows, Index cols, const Scalar *lhs_, Index lhsStride, const Scalar *rhs_, Index rhsStride, Scalar *res, Index resIncr, Index resStride, const Scalar &alpha, level3_blocking< Scalar, Scalar > &blocking)
Member Function Documentation
run()
template<typename Scalar , typename Index , int LhsStorageOrder, bool ConjugateLhs, int RhsStorageOrder, bool ConjugateRhs, int ResInnerStride> EIGEN_DONT_INLINE void Eigen::internal::product_selfadjoint_matrix< Scalar, Index, LhsStorageOrder, false, ConjugateLhs, RhsStorageOrder, true, ConjugateRhs, ColMajor, ResInnerStride >::run (Index rows, Index cols, const Scalar * lhs_, Index lhsStride, const Scalar * rhs_, Index rhsStride, Scalar * res, Index resIncr, Index resStride, const Scalar & alpha, level3_blocking< Scalar, Scalar > & blocking) static
{
   Index size = cols;
   typedef gebp_traits<Scalar, Scalar> Traits;
   typedef const_blas_data_mapper<Scalar, Index, LhsStorageOrder> LhsMapper;
   typedef blas_data_mapper<typename Traits::ResScalar, Index, ColMajor, Unaligned, ResInnerStride> ResMapper;
   LhsMapper lhs(lhs_, lhsStride);
   ResMapper res(res_, resStride, resIncr);
   Index kc = blocking.kc();                    // cache block size along the K direction
   Index mc = (std::min)(rows, blocking.mc());  // cache block size along the M direction
   std::size_t sizeA = kc * mc;
   std::size_t sizeB = kc * cols;
   ei_declare_aligned_stack_constructed_variable(Scalar, blockA, sizeA, blocking.blockA());
   ei_declare_aligned_stack_constructed_variable(Scalar, blockB, sizeB, blocking.blockB());
   gebp_kernel<Scalar, Scalar, Index, ResMapper, Traits::mr, Traits::nr, ConjugateLhs, ConjugateRhs> gebp_kernel;
   gemm_pack_lhs<Scalar, Index, LhsMapper, Traits::mr, Traits::LhsProgress, typename Traits::LhsPacket4Packing,
                 LhsStorageOrder>
       pack_lhs;
   symm_pack_rhs<Scalar, Index, Traits::nr, RhsStorageOrder> pack_rhs;
   for (Index k2 = 0; k2 < size; k2 += kc) {
     const Index actual_kc = (std::min)(k2 + kc, size) - k2;
     pack_rhs(blockB, rhs_, rhsStride, actual_kc, cols, k2);
     // => GEPP
     for (Index i2 = 0; i2 < rows; i2 += mc) {
       const Index actual_mc = (std::min)(i2 + mc, rows) - i2;
       pack_lhs(blockA, lhs.getSubMapper(i2, k2), actual_kc, actual_mc);
       gebp_kernel(res.getSubMapper(i2, 0), blockA, blockB, actual_mc, actual_kc, cols, alpha);
     }
   }
 }
References alpha, Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::blockA(), Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::blockB(), cols, ei_declare_aligned_stack_constructed_variable, Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::kc(), Eigen::internal::level3_blocking< LhsScalar_, RhsScalar_ >::mc(), min, res, rows, and size.
The documentation for this struct was generated from the following file:
SelfadjointMatrixMatrix.h