MercuryDPM: circular_driven_cavity2.cc File Reference
circular_driven_cavity2.cc File Reference
#include "generic.h"
#include "navier_stokes.h"
#include "meshes/quarter_circle_sector_mesh.h"
Classes
class QuarterCircleDrivenCavityProblem2< ELEMENT >
Namespaces
Global_Physical_Variables2
Namespace for physical parameters.
Functions
void Global_Physical_Variables2::body_force (const double &time, const Vector< double > &x, Vector< double > &result)
Functional body force.
void Global_Physical_Variables2::zero_body_force (const double &time, const Vector< double > &x, Vector< double > &result)
Zero functional body force.
int main ()
Driver for QuarterCircleDrivenCavityProblem2 test problem.
Variables
double Global_Physical_Variables2::Re =100
Reynolds number.
double Global_Physical_Variables2::Re_invFr =100
Reynolds/Froude number.
Vector< double > Global_Physical_Variables2::Gravity (2)
Gravity vector.
Function Documentation
main()
int main ()
Driver for QuarterCircleDrivenCavityProblem2 test problem.
 {
  // Set output directory and initialise count
  DocInfo doc_info;
  doc_info.set_directory("RESLT2");
  // Set max. number of black-box adaptation
  unsigned max_adapt=3;
  // Solve problem 1 with Taylor-Hood elements
  //--------------------------------------------
  {
   // Set up downwards-Gravity vector
   Global_Physical_Variables2::Gravity[0] = 0.0;
   Global_Physical_Variables2::Gravity[1] = -1.0;
   // Set up Gamma vector for stress-divergence form
   NavierStokesEquations<2>::Gamma[0]=1;
   NavierStokesEquations<2>::Gamma[1]=1;
   // Build problem with Gravity vector in stress divergence form,
   // using zero body force function
   QuarterCircleDrivenCavityProblem2<RefineableQTaylorHoodElement<2> >
    problem(&Global_Physical_Variables2::zero_body_force);
   // Solve the problem with automatic adaptation
   problem.newton_solve(max_adapt);
   // Step number
   doc_info.number()=0;
   // Output solution
   problem.doc_solution(doc_info);
  } // end of problem 1
  // Solve problem 2 with Taylor Hood elements
  //--------------------------------------------
  {
   // Set up zero-Gravity vector
   Global_Physical_Variables2::Gravity[0] = 0.0;
   Global_Physical_Variables2::Gravity[1] = 0.0;
   // Set up Gamma vector for simplified form
   NavierStokesEquations<2>::Gamma[0]=0;
   NavierStokesEquations<2>::Gamma[1]=0;
   // Build problem with body force function and simplified form,
   // using body force function
   QuarterCircleDrivenCavityProblem2<RefineableQTaylorHoodElement<2> >
    problem(&Global_Physical_Variables2::body_force);
   // Solve the problem with automatic adaptation
   problem.newton_solve(max_adapt);
   // Step number
   doc_info.number()=1;
   // Output solution
   problem.doc_solution(doc_info);
  } // end of problem 2
 } // end_of_main
References Global_Physical_Variables2::body_force(), Global_Physical_Variables2::Gravity, oomph::DocInfo::number(), problem, oomph::DocInfo::set_directory(), and Global_Physical_Variables2::zero_body_force().