MercuryDPM: Eigen::TensorBase< Derived, ReadOnlyAccessors > Class Template Reference
Eigen::TensorBase< Derived, ReadOnlyAccessors > Class Template Reference
#include <TensorBase.h>
Public Types
typedef internal::traits< Derived > DerivedTraits
typedef DerivedTraits::Scalar Scalar
typedef DerivedTraits::Index Index
typedef std::remove_const_t< Scalar > CoeffReturnType
typedef Eigen::IndexPair< Index > DimensionPair
typedef TensorScanOp< internal::SumReducer< CoeffReturnType >, const Derived > TensorScanSumOp
typedef TensorScanOp< internal::ProdReducer< CoeffReturnType >, const Derived > TensorScanProdOp
Public Member Functions
template<typename CustomNullaryOp >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseNullaryOp< CustomNullaryOp, const Derived > nullaryExpr (const CustomNullaryOp &func) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseNullaryOp< internal::scalar_constant_op< Scalar >, const Derived > constant (const Scalar &value) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseNullaryOp< internal::UniformRandomGenerator< Scalar >, const Derived > random () const
template<typename RandomGenerator >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseNullaryOp< RandomGenerator, const Derived > random (const RandomGenerator &gen=RandomGenerator()) const
template<typename Generator >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorGeneratorOp< Generator, const Derived > generate (const Generator &generator) const
template<typename CustomUnaryOp >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< CustomUnaryOp, const Derived > unaryExpr (const CustomUnaryOp &func) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_opposite_op< Scalar >, const Derived > operator- () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_sqrt_op< Scalar >, const Derived > sqrt () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_sign_op< Scalar >, const Derived > sign () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_rsqrt_op< Scalar >, const Derived > rsqrt () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_square_op< Scalar >, const Derived > square () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_cube_op< Scalar >, const Derived > cube () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_inverse_op< Scalar >, const Derived > inverse () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_tanh_op< Scalar >, const Derived > tanh () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_lgamma_op< Scalar >, const Derived > lgamma () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_digamma_op< Scalar >, const Derived > digamma () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_bessel_i0_op< Scalar >, const Derived > bessel_i0 () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_bessel_i0e_op< Scalar >, const Derived > bessel_i0e () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_bessel_i1_op< Scalar >, const Derived > bessel_i1 () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_bessel_i1e_op< Scalar >, const Derived > bessel_i1e () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_bessel_j0_op< Scalar >, const Derived > bessel_j0 () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_bessel_y0_op< Scalar >, const Derived > bessel_y0 () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_bessel_j1_op< Scalar >, const Derived > bessel_j1 () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_bessel_y1_op< Scalar >, const Derived > bessel_y1 () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_bessel_k0_op< Scalar >, const Derived > bessel_k0 () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_bessel_k0e_op< Scalar >, const Derived > bessel_k0e () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_bessel_k1_op< Scalar >, const Derived > bessel_k1 () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_bessel_k1e_op< Scalar >, const Derived > bessel_k1e () const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp< internal::scalar_igamma_op< Scalar >, const Derived, const OtherDerived > igamma (const OtherDerived &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp< internal::scalar_igamma_der_a_op< Scalar >, const Derived, const OtherDerived > igamma_der_a (const OtherDerived &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp< internal::scalar_gamma_sample_der_alpha_op< Scalar >, const Derived, const OtherDerived > gamma_sample_der_alpha (const OtherDerived &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp< internal::scalar_igammac_op< Scalar >, const Derived, const OtherDerived > igammac (const OtherDerived &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp< internal::scalar_zeta_op< Scalar >, const Derived, const OtherDerived > zeta (const OtherDerived &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp< internal::scalar_polygamma_op< Scalar >, const Derived, const OtherDerived > polygamma (const OtherDerived &other) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_erf_op< Scalar >, const Derived > erf () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_erfc_op< Scalar >, const Derived > erfc () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_ndtri_op< Scalar >, const Derived > ndtri () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_logistic_op< Scalar >, const Derived > sigmoid () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_exp_op< Scalar >, const Derived > exp () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_expm1_op< Scalar >, const Derived > expm1 () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_log_op< Scalar >, const Derived > log () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_log1p_op< Scalar >, const Derived > log1p () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_log2_op< Scalar >, const Derived > log2 () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_abs_op< Scalar >, const Derived > abs () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_arg_op< Scalar >, const Derived > arg () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_clamp_op< Scalar >, const Derived > clip (Scalar min, Scalar max) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const std::conditional_t< NumTraits< CoeffReturnType >::IsComplex, TensorCwiseUnaryOp< internal::scalar_conjugate_op< Scalar >, const Derived >, Derived > conjugate () const
template<typename ScalarExponent >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const std::enable_if_t< internal::is_arithmetic< typename NumTraits< ScalarExponent >::Real >::value, TensorCwiseUnaryOp< internal::scalar_unary_pow_op< Scalar, ScalarExponent >, const Derived > > pow (ScalarExponent exponent) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_real_op< Scalar >, const Derived > real () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_imag_op< Scalar >, const Derived > imag () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::bind2nd_op< internal::scalar_sum_op< Scalar, Scalar > >, const Derived > operator+ (Scalar rhs) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::bind2nd_op< internal::scalar_difference_op< Scalar, Scalar > >, const Derived > operator- (Scalar rhs) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::bind2nd_op< internal::scalar_product_op< Scalar, Scalar > >, const Derived > operator* (Scalar rhs) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::bind2nd_op< internal::scalar_quotient_op< Scalar, Scalar > >, const Derived > operator/ (Scalar rhs) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_mod_op< Scalar >, const Derived > operator% (Scalar rhs) const
template<int NanPropagation = PropagateFast>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp< internal::scalar_max_op< Scalar, Scalar, NanPropagation >, const Derived, const TensorCwiseNullaryOp< internal::scalar_constant_op< Scalar >, const Derived > > cwiseMax (Scalar threshold) const
template<int NanPropagation = PropagateFast>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp< internal::scalar_min_op< Scalar, Scalar, NanPropagation >, const Derived, const TensorCwiseNullaryOp< internal::scalar_constant_op< Scalar >, const Derived > > cwiseMin (Scalar threshold) const
template<typename NewType >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const std::conditional_t< internal::is_same< NewType, CoeffReturnType >::value, Derived, TensorConversionOp< NewType, const Derived > > cast () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_round_op< Scalar >, const Derived > round () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_rint_op< Scalar >, const Derived > rint () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_ceil_op< Scalar >, const Derived > ceil () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_floor_op< Scalar >, const Derived > floor () const
template<typename CustomBinaryOp , typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp< CustomBinaryOp, const Derived, const OtherDerived > binaryExpr (const OtherDerived &other, const CustomBinaryOp &func) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp< internal::scalar_sum_op< Scalar >, const Derived, const OtherDerived > operator+ (const OtherDerived &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp< internal::scalar_difference_op< Scalar >, const Derived, const OtherDerived > operator- (const OtherDerived &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp< internal::scalar_product_op< Scalar >, const Derived, const OtherDerived > operator* (const OtherDerived &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp< internal::scalar_quotient_op< Scalar >, const Derived, const OtherDerived > operator/ (const OtherDerived &other) const
template<int NaNPropagation = PropagateFast, typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp< internal::scalar_max_op< Scalar, Scalar, NaNPropagation >, const Derived, const OtherDerived > cwiseMax (const OtherDerived &other) const
template<int NaNPropagation = PropagateFast, typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp< internal::scalar_min_op< Scalar, Scalar, NaNPropagation >, const Derived, const OtherDerived > cwiseMin (const OtherDerived &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp< internal::scalar_boolean_and_op< Scalar >, const Derived, const OtherDerived > operator&& (const OtherDerived &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp< internal::scalar_boolean_or_op< Scalar >, const Derived, const OtherDerived > operator|| (const OtherDerived &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp< internal::scalar_bitwise_and_op< Scalar >, const Derived, const OtherDerived > operator& (const OtherDerived &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp< internal::scalar_bitwise_or_op< Scalar >, const Derived, const OtherDerived > operator| (const OtherDerived &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp< internal::scalar_bitwise_xor_op< Scalar >, const Derived, const OtherDerived > operator^ (const OtherDerived &other) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_boolean_not_op< Scalar >, const Derived > operator! () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp< internal::scalar_bitwise_not_op< Scalar >, const Derived > operator~ () const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp< internal::scalar_cmp_op< Scalar, Scalar, internal::cmp_LT >, const Derived, const OtherDerived > operator< (const TensorBase< OtherDerived, ReadOnlyAccessors > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp< internal::scalar_cmp_op< Scalar, Scalar, internal::cmp_LE >, const Derived, const OtherDerived > operator<= (const TensorBase< OtherDerived, ReadOnlyAccessors > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp< internal::scalar_cmp_op< Scalar, Scalar, internal::cmp_GT >, const Derived, const OtherDerived > operator> (const TensorBase< OtherDerived, ReadOnlyAccessors > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp< internal::scalar_cmp_op< Scalar, Scalar, internal::cmp_GE >, const Derived, const OtherDerived > operator>= (const TensorBase< OtherDerived, ReadOnlyAccessors > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp< internal::scalar_cmp_op< Scalar, Scalar, internal::cmp_EQ >, const Derived, const OtherDerived > operator== (const TensorBase< OtherDerived, ReadOnlyAccessors > &other) const
template<typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp< internal::scalar_cmp_op< Scalar, Scalar, internal::cmp_NEQ >, const Derived, const OtherDerived > operator!= (const TensorBase< OtherDerived, ReadOnlyAccessors > &other) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp< internal::scalar_cmp_op< Scalar, Scalar, internal::cmp_LT >, const Derived, const TensorCwiseNullaryOp< internal::scalar_constant_op< Scalar >, const Derived > > operator< (Scalar threshold) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp< internal::scalar_cmp_op< Scalar, Scalar, internal::cmp_LE >, const Derived, const TensorCwiseNullaryOp< internal::scalar_constant_op< Scalar >, const Derived > > operator<= (Scalar threshold) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp< internal::scalar_cmp_op< Scalar, Scalar, internal::cmp_GT >, const Derived, const TensorCwiseNullaryOp< internal::scalar_constant_op< Scalar >, const Derived > > operator> (Scalar threshold) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp< internal::scalar_cmp_op< Scalar, Scalar, internal::cmp_GE >, const Derived, const TensorCwiseNullaryOp< internal::scalar_constant_op< Scalar >, const Derived > > operator>= (Scalar threshold) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp< internal::scalar_cmp_op< Scalar, Scalar, internal::cmp_EQ >, const Derived, const TensorCwiseNullaryOp< internal::scalar_constant_op< Scalar >, const Derived > > operator== (Scalar threshold) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp< internal::scalar_cmp_op< Scalar, Scalar, internal::cmp_NEQ >, const Derived, const TensorCwiseNullaryOp< internal::scalar_constant_op< Scalar >, const Derived > > operator!= (Scalar threshold) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorConversionOp (isnan)() const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorConversionOp (isinf)() const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorConversionOp (isfinite)() const
template<typename ThenDerived , typename ElseDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorSelectOp< const Derived, const ThenDerived, const ElseDerived > select (const ThenDerived &thenTensor, const ElseDerived &elseTensor) const
template<typename OtherDerived , typename Dimensions >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorContractionOp< const Dimensions, const Derived, const OtherDerived, const NoOpOutputKernel > contract (const OtherDerived &other, const Dimensions &dims) const
template<typename OtherDerived , typename Dimensions , typename OutputKernel >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorContractionOp< const Dimensions, const Derived, const OtherDerived, const OutputKernel > contract (const OtherDerived &other, const Dimensions &dims, const OutputKernel &output_kernel) const
template<typename KernelDerived , typename Dimensions >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorConvolutionOp< const Dimensions, const Derived, const KernelDerived > convolve (const KernelDerived &kernel, const Dimensions &dims) const
template<int FFTDataType, int FFTDirection, typename FFT >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorFFTOp< const FFT, const Derived, FFTDataType, FFTDirection > fft (const FFT &dims) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorScanSumOp cumsum (const Index &axis, bool exclusive=false) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorScanProdOp cumprod (const Index &axis, bool exclusive=false) const
template<typename Reducer >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorScanOp< Reducer, const Derived > scan (const Index &axis, const Reducer &reducer, bool exclusive=false) const
template<typename Dims >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorReductionOp< internal::SumReducer< CoeffReturnType >, const Dims, const Derived > sum (const Dims &dims) const
const TensorReductionOp< internal::SumReducer< CoeffReturnType >, const DimensionList< Index, NumDimensions >, const Derived > sum () const
template<typename Dims >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorReductionOp< internal::MeanReducer< CoeffReturnType >, const Dims, const Derived > mean (const Dims &dims) const
const TensorReductionOp< internal::MeanReducer< CoeffReturnType >, const DimensionList< Index, NumDimensions >, const Derived > mean () const
template<typename Dims >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorReductionOp< internal::ProdReducer< CoeffReturnType >, const Dims, const Derived > prod (const Dims &dims) const
const TensorReductionOp< internal::ProdReducer< CoeffReturnType >, const DimensionList< Index, NumDimensions >, const Derived > prod () const
template<typename Dims , int NanPropagation = PropagateFast>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorReductionOp< internal::MaxReducer< CoeffReturnType, NanPropagation >, const Dims, const Derived > maximum (const Dims &dims) const
template<int NanPropagation = PropagateFast>
const TensorReductionOp< internal::MaxReducer< CoeffReturnType, NanPropagation >, const DimensionList< Index, NumDimensions >, const Derived > maximum () const
template<typename Dims , int NanPropagation = PropagateFast>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorReductionOp< internal::MinReducer< CoeffReturnType, NanPropagation >, const Dims, const Derived > minimum (const Dims &dims) const
template<int NanPropagation = PropagateFast>
const TensorReductionOp< internal::MinReducer< CoeffReturnType, NanPropagation >, const DimensionList< Index, NumDimensions >, const Derived > minimum () const
template<typename Dims >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorReductionOp< internal::AndReducer, const Dims, const std::conditional_t< internal::is_same< bool, CoeffReturnType >::value, Derived, TensorConversionOp< bool, const Derived > > > all (const Dims &dims) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorReductionOp< internal::AndReducer, const DimensionList< Index, NumDimensions >, const std::conditional_t< internal::is_same< bool, CoeffReturnType >::value, Derived, TensorConversionOp< bool, const Derived > > > all () const
template<typename Dims >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorReductionOp< internal::OrReducer, const Dims, const std::conditional_t< internal::is_same< bool, CoeffReturnType >::value, Derived, TensorConversionOp< bool, const Derived > > > any (const Dims &dims) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorReductionOp< internal::OrReducer, const DimensionList< Index, NumDimensions >, const std::conditional_t< internal::is_same< bool, CoeffReturnType >::value, Derived, TensorConversionOp< bool, const Derived > > > any () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorPairReducerOp< internal::ArgMaxPairReducer< Pair< Index, CoeffReturnType > >, const array< Index, NumDimensions >, const Derived > argmax () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorPairReducerOp< internal::ArgMinPairReducer< Pair< Index, CoeffReturnType > >, const array< Index, NumDimensions >, const Derived > argmin () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorPairReducerOp< internal::ArgMaxPairReducer< Pair< Index, CoeffReturnType > >, const array< Index, 1 >, const Derived > argmax (const Index return_dim) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorPairReducerOp< internal::ArgMinPairReducer< Pair< Index, CoeffReturnType > >, const array< Index, 1 >, const Derived > argmin (const Index return_dim) const
template<typename Reducer , typename Dims >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorReductionOp< Reducer, const Dims, const Derived > reduce (const Dims &dims, const Reducer &reducer) const
template<typename Dims >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorTraceOp< const Dims, const Derived > trace (const Dims &dims) const
const TensorTraceOp< const DimensionList< Index, NumDimensions >, const Derived > trace () const
template<typename Broadcast >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorBroadcastingOp< const Broadcast, const Derived > broadcast (const Broadcast &bcast) const
template<typename Axis , typename OtherDerived >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorConcatenationOp< Axis, const Derived, const OtherDerived > concatenate (const OtherDerived &other, Axis axis) const
template<typename PatchDims >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorPatchOp< const PatchDims, const Derived > extract_patches (const PatchDims &patch_dims) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorImagePatchOp< Dynamic, Dynamic, const Derived > extract_image_patches (const Index patch_rows=1, const Index patch_cols=1, const Index row_stride=1, const Index col_stride=1, const Index in_row_stride=1, const Index in_col_stride=1, const PaddingType padding_type=PADDING_SAME, const Scalar padding_value=Scalar(0)) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorImagePatchOp< Dynamic, Dynamic, const Derived > extract_image_patches (const Index patch_rows, const Index patch_cols, const Index row_stride, const Index col_stride, const Index in_row_stride, const Index in_col_stride, const Index row_inflate_stride, const Index col_inflate_stride, const Index padding_top, const Index padding_bottom, const Index padding_left, const Index padding_right, const Scalar padding_value) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorVolumePatchOp< Dynamic, Dynamic, Dynamic, const Derived > extract_volume_patches (const Index patch_planes, const Index patch_rows, const Index patch_cols, const Index plane_stride=1, const Index row_stride=1, const Index col_stride=1, const PaddingType padding_type=PADDING_SAME, const Scalar padding_value=Scalar(0)) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorVolumePatchOp< Dynamic, Dynamic, Dynamic, const Derived > extract_volume_patches (const Index patch_planes, const Index patch_rows, const Index patch_cols, const Index plane_stride, const Index row_stride, const Index col_stride, const Index plane_inflate_stride, const Index row_inflate_stride, const Index col_inflate_stride, const Index padding_top_z, const Index padding_bottom_z, const Index padding_top, const Index padding_bottom, const Index padding_left, const Index padding_right, const Scalar padding_value=Scalar(0)) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorLayoutSwapOp< const Derived > swap_layout () const
template<typename NewDimensions >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorReshapingOp< const NewDimensions, const Derived > reshape (const NewDimensions &newDimensions) const
template<typename StartIndices , typename Sizes >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorSlicingOp< const StartIndices, const Sizes, const Derived > slice (const StartIndices &startIndices, const Sizes &sizes) const
template<typename StartIndices , typename StopIndices , typename Strides >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorStridingSlicingOp< const StartIndices, const StopIndices, const Strides, const Derived > stridedSlice (const StartIndices &startIndices, const StopIndices &stopIndices, const Strides &strides) const
template<Index DimId>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorChippingOp< DimId, const Derived > chip (const Index offset) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorChippingOp< Dynamic, const Derived > chip (const Index offset, const Index dim) const
template<typename ReverseDimensions >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorReverseOp< const ReverseDimensions, const Derived > reverse (const ReverseDimensions &rev) const
template<typename Rolls >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorRollOp< const Rolls, const Derived > roll (const Rolls &rolls) const
template<typename PaddingDimensions >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorPaddingOp< const PaddingDimensions, const Derived > pad (const PaddingDimensions &padding) const
template<typename PaddingDimensions >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorPaddingOp< const PaddingDimensions, const Derived > pad (const PaddingDimensions &padding, const Scalar padding_value) const
template<typename Shuffle >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorShufflingOp< const Shuffle, const Derived > shuffle (const Shuffle &shfl) const
template<typename Strides >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorStridingOp< const Strides, const Derived > stride (const Strides &strides) const
template<typename Strides >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorInflationOp< const Strides, const Derived > inflate (const Strides &strides) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorIndexPairOp< const Derived > index_pairs () const
template<typename CustomUnaryFunc >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCustomUnaryOp< const CustomUnaryFunc, const Derived > customOp (const CustomUnaryFunc &op) const
template<typename OtherDerived , typename CustomBinaryFunc >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCustomBinaryOp< const CustomBinaryFunc, const Derived, const OtherDerived > customOp (const OtherDerived &other, const CustomBinaryFunc &op) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorForcedEvalOp< const Derived > eval () const
template<typename Format >
const TensorWithFormat< Derived, DerivedTraits::Layout, DerivedTraits::NumDimensions, Format > format (const Format &fmt) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Derived & derived () const
Static Public Attributes
static constexpr int NumDimensions = DerivedTraits::NumDimensions
Friends
template<typename Scalar , int NumIndices, int Options, typename IndexType >
class Tensor
template<typename Scalar , typename Dimensions , int Option, typename IndexTypes >
class TensorFixedSize
template<typename OtherDerived , int AccessLevel>
class Eigen::TensorBase
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE friend const TensorCwiseUnaryOp< internal::bind1st_op< internal::scalar_sum_op< Scalar > >, const Derived > operator+ (Scalar lhs, const Derived &rhs)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE friend const TensorCwiseUnaryOp< internal::bind1st_op< internal::scalar_difference_op< Scalar > >, const Derived > operator- (Scalar lhs, const Derived &rhs)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE friend const TensorCwiseUnaryOp< internal::bind1st_op< internal::scalar_product_op< Scalar > >, const Derived > operator* (Scalar lhs, const Derived &rhs)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE friend const TensorCwiseUnaryOp< internal::bind1st_op< internal::scalar_quotient_op< Scalar > >, const Derived > operator/ (Scalar lhs, const Derived &rhs)
Member Typedef Documentation
CoeffReturnType
template<typename Derived > typedef std::remove_const_t<Scalar> Eigen::TensorBase< Derived, ReadOnlyAccessors >::CoeffReturnType
DerivedTraits
template<typename Derived > typedef internal::traits<Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::DerivedTraits
DimensionPair
template<typename Derived > typedef Eigen::IndexPair<Index> Eigen::TensorBase< Derived, ReadOnlyAccessors >::DimensionPair
Index
template<typename Derived > typedef DerivedTraits::Index Eigen::TensorBase< Derived, ReadOnlyAccessors >::Index
Scalar
template<typename Derived > typedef DerivedTraits::Scalar Eigen::TensorBase< Derived, ReadOnlyAccessors >::Scalar
TensorScanProdOp
template<typename Derived > typedef TensorScanOp<internal::ProdReducer<CoeffReturnType>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::TensorScanProdOp
TensorScanSumOp
template<typename Derived > typedef TensorScanOp<internal::SumReducer<CoeffReturnType>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::TensorScanSumOp
Member Function Documentation
abs()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_abs_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::abs () const inline
                 {
       return unaryExpr(internal::scalar_abs_op<Scalar>());
     }
all() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorReductionOp<internal::AndReducer, const DimensionList<Index, NumDimensions>, const std::conditional_t<internal::is_same<bool, CoeffReturnType>::value, Derived, TensorConversionOp<bool, const Derived> > > Eigen::TensorBase< Derived, ReadOnlyAccessors >::all () const inline
                 {
       DimensionList<Index, NumDimensions> in_dims;
       return cast<bool>().reduce(in_dims, internal::AndReducer());
     }
all() [2/2]
template<typename Derived > template<typename Dims > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorReductionOp<internal::AndReducer, const Dims, const std::conditional_t<internal::is_same<bool, CoeffReturnType>::value, Derived, TensorConversionOp<bool, const Derived> > > Eigen::TensorBase< Derived, ReadOnlyAccessors >::all (const Dims & dims) const inline
{
       return cast<bool>().reduce(dims, internal::AndReducer());
     }
any() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorReductionOp<internal::OrReducer, const DimensionList<Index, NumDimensions>, const std::conditional_t<internal::is_same<bool, CoeffReturnType>::value, Derived, TensorConversionOp<bool, const Derived> > > Eigen::TensorBase< Derived, ReadOnlyAccessors >::any () const inline
                 {
       DimensionList<Index, NumDimensions> in_dims;
       return cast<bool>().reduce(in_dims, internal::OrReducer());
     }
any() [2/2]
template<typename Derived > template<typename Dims > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorReductionOp<internal::OrReducer, const Dims, const std::conditional_t<internal::is_same<bool, CoeffReturnType>::value, Derived, TensorConversionOp<bool, const Derived> > > Eigen::TensorBase< Derived, ReadOnlyAccessors >::any (const Dims & dims) const inline
{
       return cast<bool>().reduce(dims, internal::OrReducer());
     }
arg()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_arg_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::arg () const inline
                 {
       return unaryExpr(internal::scalar_arg_op<Scalar>());
     }
argmax() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorPairReducerOp< internal::ArgMaxPairReducer<Pair<Index, CoeffReturnType> >, const array<Index, NumDimensions>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::argmax () const inline
                    {
       array<Index, NumDimensions> in_dims;
       for (Index d = 0; d < NumDimensions; ++d) in_dims[d] = d;
       return TensorPairReducerOp<
         internal::ArgMaxPairReducer<Pair<Index, CoeffReturnType> >,
         const array<Index, NumDimensions>,
         const Derived>(derived(), internal::ArgMaxPairReducer<Pair<Index, CoeffReturnType> >(), -1, in_dims);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived(), and Eigen::TensorBase< Derived, AccessLevel >::NumDimensions.
argmax() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorPairReducerOp< internal::ArgMaxPairReducer<Pair<Index, CoeffReturnType> >, const array<Index, 1>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::argmax (const Index return_dim) const inline
{
       array<Index, 1> in_dims;
       in_dims[0] = return_dim;
       return TensorPairReducerOp<
         internal::ArgMaxPairReducer<Pair<Index, CoeffReturnType> >,
         const array<Index, 1>,
         const Derived>(derived(), internal::ArgMaxPairReducer<Pair<Index, CoeffReturnType> >(), return_dim, in_dims);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
argmin() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorPairReducerOp< internal::ArgMinPairReducer<Pair<Index, CoeffReturnType> >, const array<Index, NumDimensions>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::argmin () const inline
                    {
       array<Index, NumDimensions> in_dims;
       for (Index d = 0; d < NumDimensions; ++d) in_dims[d] = d;
       return TensorPairReducerOp<
         internal::ArgMinPairReducer<Pair<Index, CoeffReturnType> >,
         const array<Index, NumDimensions>,
         const Derived>(derived(), internal::ArgMinPairReducer<Pair<Index, CoeffReturnType> >(), -1, in_dims);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived(), and Eigen::TensorBase< Derived, AccessLevel >::NumDimensions.
argmin() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorPairReducerOp< internal::ArgMinPairReducer<Pair<Index, CoeffReturnType> >, const array<Index, 1>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::argmin (const Index return_dim) const inline
{
       array<Index, 1> in_dims;
       in_dims[0] = return_dim;
       return TensorPairReducerOp<
         internal::ArgMinPairReducer<Pair<Index, CoeffReturnType> >,
         const array<Index, 1>,
         const Derived>(derived(), internal::ArgMinPairReducer<Pair<Index, CoeffReturnType> >(), return_dim, in_dims);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
bessel_i0()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_bessel_i0_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::bessel_i0 () const inline
                       {
       return unaryExpr(internal::scalar_bessel_i0_op<Scalar>());
     }
bessel_i0e()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_bessel_i0e_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::bessel_i0e () const inline
{
       return unaryExpr(internal::scalar_bessel_i0e_op<Scalar>());
     }
bessel_i1()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_bessel_i1_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::bessel_i1 () const inline
                       {
       return unaryExpr(internal::scalar_bessel_i1_op<Scalar>());
     }
bessel_i1e()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_bessel_i1e_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::bessel_i1e () const inline
{
       return unaryExpr(internal::scalar_bessel_i1e_op<Scalar>());
     }
bessel_j0()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_bessel_j0_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::bessel_j0 () const inline
                       {
       return unaryExpr(internal::scalar_bessel_j0_op<Scalar>());
     }
bessel_j1()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_bessel_j1_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::bessel_j1 () const inline
                       {
       return unaryExpr(internal::scalar_bessel_j1_op<Scalar>());
     }
bessel_k0()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_bessel_k0_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::bessel_k0 () const inline
                       {
       return unaryExpr(internal::scalar_bessel_k0_op<Scalar>());
     }
bessel_k0e()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_bessel_k0e_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::bessel_k0e () const inline
{
       return unaryExpr(internal::scalar_bessel_k0e_op<Scalar>());
     }
bessel_k1()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_bessel_k1_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::bessel_k1 () const inline
                       {
       return unaryExpr(internal::scalar_bessel_k1_op<Scalar>());
     }
bessel_k1e()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_bessel_k1e_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::bessel_k1e () const inline
{
       return unaryExpr(internal::scalar_bessel_k1e_op<Scalar>());
     }
bessel_y0()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_bessel_y0_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::bessel_y0 () const inline
                       {
       return unaryExpr(internal::scalar_bessel_y0_op<Scalar>());
     }
bessel_y1()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_bessel_y1_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::bessel_y1 () const inline
                       {
       return unaryExpr(internal::scalar_bessel_y1_op<Scalar>());
     }
binaryExpr()
template<typename Derived > template<typename CustomBinaryOp , typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp<CustomBinaryOp, const Derived, const OtherDerived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::binaryExpr (const OtherDerived & other, const CustomBinaryOp & func) const inline
{
       return TensorCwiseBinaryOp<CustomBinaryOp, const Derived, const OtherDerived>(derived(), other, func);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
broadcast()
template<typename Derived > template<typename Broadcast > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorBroadcastingOp<const Broadcast, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::broadcast (const Broadcast & bcast) const inline
{
       return TensorBroadcastingOp<const Broadcast, const Derived>(derived(), bcast);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
cast()
template<typename Derived > template<typename NewType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const std::conditional_t<internal::is_same<NewType, CoeffReturnType>::value, Derived, TensorConversionOp<NewType, const Derived> > Eigen::TensorBase< Derived, ReadOnlyAccessors >::cast () const inline
                  {
       return choose(Cond<internal::is_same<NewType, CoeffReturnType>::value>(), derived(), TensorConversionOp<NewType, const Derived>(derived()));
     }
References Eigen::choose(), and Eigen::TensorBase< Derived, AccessLevel >::derived().
ceil()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_ceil_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::ceil () const inline
                  {
       return unaryExpr(internal::scalar_ceil_op<Scalar>());
     }
chip() [1/2]
template<typename Derived > template<Index DimId> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorChippingOp<DimId, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::chip (const Index offset) const inline
{
       EIGEN_STATIC_ASSERT(DimId < Derived::NumDimensions && DimId >= 0, Chip_Dim_out_of_range)
       return TensorChippingOp<DimId, const Derived>(derived(), offset, DimId);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived(), and EIGEN_STATIC_ASSERT.
chip() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorChippingOp<Dynamic, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::chip (const Index offset, const Index dim) const inline
{
       return TensorChippingOp<Dynamic, const Derived>(derived(), offset, dim);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
clip()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_clamp_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::clip (Scalar min, Scalar max) const inline
{
       return unaryExpr(internal::scalar_clamp_op<Scalar>(min, max));
     }
References Eigen::max(), and Eigen::min().
concatenate()
template<typename Derived > template<typename Axis , typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorConcatenationOp<Axis, const Derived, const OtherDerived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::concatenate (const OtherDerived & other, Axis axis) const inline
{
       return TensorConcatenationOp<Axis, const Derived, const OtherDerived>(derived(), other.derived(), axis);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
conjugate()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const std::conditional_t<NumTraits<CoeffReturnType>::IsComplex, TensorCwiseUnaryOp<internal::scalar_conjugate_op<Scalar>, const Derived>, Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::conjugate (void) const inline
                       {
       return choose(Cond<NumTraits<CoeffReturnType>::IsComplex>(), unaryExpr(internal::scalar_conjugate_op<Scalar>()), derived());
     }
References Eigen::choose(), and Eigen::TensorBase< Derived, AccessLevel >::derived().
constant()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseNullaryOp<internal::scalar_constant_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::constant (const Scalar & value) const inline
{
       return nullaryExpr(internal::scalar_constant_op<Scalar>(value));
     }
References Eigen::value.
contract() [1/2]
template<typename Derived > template<typename OtherDerived , typename Dimensions > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorContractionOp<const Dimensions, const Derived, const OtherDerived, const NoOpOutputKernel> Eigen::TensorBase< Derived, ReadOnlyAccessors >::contract (const OtherDerived & other, const Dimensions & dims) const inline
{
       return TensorContractionOp<const Dimensions, const Derived, const OtherDerived, const NoOpOutputKernel>(derived(), other.derived(), dims);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
contract() [2/2]
template<typename Derived > template<typename OtherDerived , typename Dimensions , typename OutputKernel > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorContractionOp<const Dimensions, const Derived, const OtherDerived, const OutputKernel> Eigen::TensorBase< Derived, ReadOnlyAccessors >::contract (const OtherDerived & other, const Dimensions & dims, const OutputKernel & output_kernel) const inline
{
       return TensorContractionOp<const Dimensions, const Derived, const OtherDerived, const OutputKernel>(derived(), other.derived(), dims, output_kernel);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
convolve()
template<typename Derived > template<typename KernelDerived , typename Dimensions > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorConvolutionOp<const Dimensions, const Derived, const KernelDerived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::convolve (const KernelDerived & kernel, const Dimensions & dims) const inline
{
       return TensorConvolutionOp<const Dimensions, const Derived, const KernelDerived>(derived(), kernel.derived(), dims);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
cube()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_cube_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::cube () const inline
                  {
       return unaryExpr(internal::scalar_cube_op<Scalar>());
     }
cumprod()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorScanProdOp Eigen::TensorBase< Derived, ReadOnlyAccessors >::cumprod (const Index & axis, bool exclusive = false) const inline
{
       return TensorScanProdOp(derived(), axis, exclusive);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
cumsum()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorScanSumOp Eigen::TensorBase< Derived, ReadOnlyAccessors >::cumsum (const Index & axis, bool exclusive = false) const inline
{
       return TensorScanSumOp(derived(), axis, exclusive);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
customOp() [1/2]
template<typename Derived > template<typename CustomUnaryFunc > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCustomUnaryOp<const CustomUnaryFunc, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::customOp (const CustomUnaryFunc & op) const inline
{
       return TensorCustomUnaryOp<const CustomUnaryFunc, const Derived>(derived(), op);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived(), and op.
customOp() [2/2]
template<typename Derived > template<typename OtherDerived , typename CustomBinaryFunc > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCustomBinaryOp<const CustomBinaryFunc, const Derived, const OtherDerived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::customOp (const OtherDerived & other, const CustomBinaryFunc & op) const inline
{
       return TensorCustomBinaryOp<const CustomBinaryFunc, const Derived, const OtherDerived>(derived(), other, op);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived(), and op.
cwiseMax() [1/2]
template<typename Derived > template<int NaNPropagation = PropagateFast, typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp<internal::scalar_max_op<Scalar,Scalar, NaNPropagation>, const Derived, const OtherDerived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::cwiseMax (const OtherDerived & other) const inline
{
       return binaryExpr(other.derived(), internal::scalar_max_op<Scalar,Scalar, NaNPropagation>());
     }
cwiseMax() [2/2]
template<typename Derived > template<int NanPropagation = PropagateFast> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp<internal::scalar_max_op<Scalar,Scalar,NanPropagation>, const Derived, const TensorCwiseNullaryOp<internal::scalar_constant_op<Scalar>, const Derived> > Eigen::TensorBase< Derived, ReadOnlyAccessors >::cwiseMax (Scalar threshold) const inline
{
       return cwiseMax<NanPropagation>(constant(threshold));
     }
cwiseMin() [1/2]
template<typename Derived > template<int NaNPropagation = PropagateFast, typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp<internal::scalar_min_op<Scalar,Scalar, NaNPropagation>, const Derived, const OtherDerived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::cwiseMin (const OtherDerived & other) const inline
{
       return binaryExpr(other.derived(), internal::scalar_min_op<Scalar,Scalar, NaNPropagation>());
     }
cwiseMin() [2/2]
template<typename Derived > template<int NanPropagation = PropagateFast> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp<internal::scalar_min_op<Scalar,Scalar,NanPropagation>, const Derived, const TensorCwiseNullaryOp<internal::scalar_constant_op<Scalar>, const Derived> > Eigen::TensorBase< Derived, ReadOnlyAccessors >::cwiseMin (Scalar threshold) const inline
{
       return cwiseMin<NanPropagation>(constant(threshold));
     }
derived()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Derived& Eigen::TensorBase< Derived, ReadOnlyAccessors >::derived () const inline
 { return *static_cast<const Derived*>(this); }
digamma()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_digamma_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::digamma () const inline
                     {
       return unaryExpr(internal::scalar_digamma_op<Scalar>());
     }
erf()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_erf_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::erf () const inline
                 {
       return unaryExpr(internal::scalar_erf_op<Scalar>());
     }
erfc()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_erfc_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::erfc () const inline
                  {
       return unaryExpr(internal::scalar_erfc_op<Scalar>());
     }
eval()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorForcedEvalOp<const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::eval () const inline
{
       return TensorForcedEvalOp<const Derived>(derived());
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
exp()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_exp_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::exp () const inline
                 {
       return unaryExpr(internal::scalar_exp_op<Scalar>());
     }
expm1()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_expm1_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::expm1 () const inline
                   {
       return unaryExpr(internal::scalar_expm1_op<Scalar>());
     }
extract_image_patches() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorImagePatchOp<Dynamic, Dynamic, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::extract_image_patches (const Index patch_rows, const Index patch_cols, const Index row_stride, const Index col_stride, const Index in_row_stride, const Index in_col_stride, const Index row_inflate_stride, const Index col_inflate_stride, const Index padding_top, const Index padding_bottom, const Index padding_left, const Index padding_right, const Scalar padding_value) const inline
{
       return TensorImagePatchOp<Dynamic, Dynamic, const Derived>(derived(), patch_rows, patch_cols, row_stride, col_stride,
                                                                  in_row_stride, in_col_stride, row_inflate_stride, col_inflate_stride,
                                                                  padding_top, padding_bottom, padding_left, padding_right, padding_value);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
extract_image_patches() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorImagePatchOp<Dynamic, Dynamic, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::extract_image_patches (const Index patch_rows = 1, const Index patch_cols = 1, const Index row_stride = 1, const Index col_stride = 1, const Index in_row_stride = 1, const Index in_col_stride = 1, const PaddingType padding_type = PADDING_SAME, const Scalar padding_value = Scalar(0)) const inline
{
       return TensorImagePatchOp<Dynamic, Dynamic, const Derived>(derived(), patch_rows, patch_cols, row_stride, col_stride,
                                                                  in_row_stride, in_col_stride, 1, 1, padding_type, padding_value);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
extract_patches()
template<typename Derived > template<typename PatchDims > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorPatchOp<const PatchDims, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::extract_patches (const PatchDims & patch_dims) const inline
{
       return TensorPatchOp<const PatchDims, const Derived>(derived(), patch_dims);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
extract_volume_patches() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorVolumePatchOp<Dynamic, Dynamic, Dynamic, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::extract_volume_patches (const Index patch_planes, const Index patch_rows, const Index patch_cols, const Index plane_stride, const Index row_stride, const Index col_stride, const Index plane_inflate_stride, const Index row_inflate_stride, const Index col_inflate_stride, const Index padding_top_z, const Index padding_bottom_z, const Index padding_top, const Index padding_bottom, const Index padding_left, const Index padding_right, const Scalar padding_value = Scalar(0)) const inline
{
       return TensorVolumePatchOp<Dynamic, Dynamic, Dynamic, const Derived>(derived(), patch_planes, patch_rows, patch_cols, plane_stride, row_stride, col_stride, 1, 1, 1, plane_inflate_stride, row_inflate_stride, col_inflate_stride, padding_top_z, padding_bottom_z, padding_top, padding_bottom, padding_left, padding_right, padding_value);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
extract_volume_patches() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorVolumePatchOp<Dynamic, Dynamic, Dynamic, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::extract_volume_patches (const Index patch_planes, const Index patch_rows, const Index patch_cols, const Index plane_stride = 1, const Index row_stride = 1, const Index col_stride = 1, const PaddingType padding_type = PADDING_SAME, const Scalar padding_value = Scalar(0)) const inline
{
       return TensorVolumePatchOp<Dynamic, Dynamic, Dynamic, const Derived>(derived(), patch_planes, patch_rows, patch_cols, plane_stride, row_stride, col_stride, 1, 1, 1, 1, 1, 1, padding_type, padding_value);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
fft()
template<typename Derived > template<int FFTDataType, int FFTDirection, typename FFT > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorFFTOp<const FFT, const Derived, FFTDataType, FFTDirection> Eigen::TensorBase< Derived, ReadOnlyAccessors >::fft (const FFT & dims) const inline
{
       return TensorFFTOp<const FFT, const Derived, FFTDataType, FFTDirection>(derived(), dims);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
floor()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_floor_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::floor () const inline
                   {
       return unaryExpr(internal::scalar_floor_op<Scalar>());
     }
format()
template<typename Derived > template<typename Format > const TensorWithFormat<Derived,DerivedTraits::Layout,DerivedTraits::NumDimensions, Format> Eigen::TensorBase< Derived, ReadOnlyAccessors >::format (const Format & fmt) const inline
{
       return TensorWithFormat<Derived,DerivedTraits::Layout,DerivedTraits::NumDimensions, Format>(derived(), fmt);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
gamma_sample_der_alpha()
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp<internal::scalar_gamma_sample_der_alpha_op<Scalar>, const Derived, const OtherDerived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::gamma_sample_der_alpha (const OtherDerived & other) const inline
{
       return binaryExpr(other.derived(), internal::scalar_gamma_sample_der_alpha_op<Scalar>());
     }
generate()
template<typename Derived > template<typename Generator > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorGeneratorOp<Generator, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::generate (const Generator & generator) const inline
{
       return TensorGeneratorOp<Generator, const Derived>(derived(), generator);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
igamma()
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp<internal::scalar_igamma_op<Scalar>, const Derived, const OtherDerived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::igamma (const OtherDerived & other) const inline
{
       return binaryExpr(other.derived(), internal::scalar_igamma_op<Scalar>());
     }
igamma_der_a()
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp<internal::scalar_igamma_der_a_op<Scalar>, const Derived, const OtherDerived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::igamma_der_a (const OtherDerived & other) const inline
{
       return binaryExpr(other.derived(), internal::scalar_igamma_der_a_op<Scalar>());
     }
igammac()
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp<internal::scalar_igammac_op<Scalar>, const Derived, const OtherDerived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::igammac (const OtherDerived & other) const inline
{
       return binaryExpr(other.derived(), internal::scalar_igammac_op<Scalar>());
     }
imag()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_imag_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::imag () const inline
                  {
       return unaryExpr(internal::scalar_imag_op<Scalar>());
     }
index_pairs()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorIndexPairOp<const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::index_pairs () const inline
{
       return TensorIndexPairOp<const Derived>(derived());
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
inflate()
template<typename Derived > template<typename Strides > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorInflationOp<const Strides, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::inflate (const Strides & strides) const inline
{
       return TensorInflationOp<const Strides, const Derived>(derived(), strides);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived(), and Eigen::internal::strides().
inverse()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_inverse_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::inverse () const inline
                     {
       return unaryExpr(internal::scalar_inverse_op<Scalar>());
     }
lgamma()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_lgamma_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::lgamma () const inline
                    {
       return unaryExpr(internal::scalar_lgamma_op<Scalar>());
     }
log()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_log_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::log () const inline
                 {
       return unaryExpr(internal::scalar_log_op<Scalar>());
     }
log1p()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_log1p_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::log1p () const inline
                   {
       return unaryExpr(internal::scalar_log1p_op<Scalar>());
     }
log2()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_log2_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::log2 () const inline
                  {
       return unaryExpr(internal::scalar_log2_op<Scalar>());
     }
maximum() [1/2]
template<typename Derived > template<int NanPropagation = PropagateFast> const TensorReductionOp<internal::MaxReducer<CoeffReturnType,NanPropagation>, const DimensionList<Index, NumDimensions>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::maximum () const inline
                     {
       DimensionList<Index, NumDimensions> in_dims;
       return TensorReductionOp<internal::MaxReducer<CoeffReturnType,NanPropagation>, const DimensionList<Index, NumDimensions>, const Derived>(derived(), in_dims, internal::MaxReducer<CoeffReturnType,NanPropagation>());
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
maximum() [2/2]
template<typename Derived > template<typename Dims , int NanPropagation = PropagateFast> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorReductionOp<internal::MaxReducer<CoeffReturnType,NanPropagation>, const Dims, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::maximum (const Dims & dims) const inline
{
       return TensorReductionOp<internal::MaxReducer<CoeffReturnType,NanPropagation>, const Dims, const Derived>(derived(), dims, internal::MaxReducer<CoeffReturnType,NanPropagation>());
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
mean() [1/2]
template<typename Derived > const TensorReductionOp<internal::MeanReducer<CoeffReturnType>, const DimensionList<Index, NumDimensions>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::mean () const inline
                  {
       DimensionList<Index, NumDimensions> in_dims;
       return TensorReductionOp<internal::MeanReducer<CoeffReturnType>, const DimensionList<Index, NumDimensions>, const Derived>(derived(), in_dims, internal::MeanReducer<CoeffReturnType>());
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
mean() [2/2]
template<typename Derived > template<typename Dims > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorReductionOp<internal::MeanReducer<CoeffReturnType>, const Dims, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::mean (const Dims & dims) const inline
{
       return TensorReductionOp<internal::MeanReducer<CoeffReturnType>, const Dims, const Derived>(derived(), dims, internal::MeanReducer<CoeffReturnType>());
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
minimum() [1/2]
template<typename Derived > template<int NanPropagation = PropagateFast> const TensorReductionOp<internal::MinReducer<CoeffReturnType,NanPropagation>, const DimensionList<Index, NumDimensions>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::minimum () const inline
                     {
       DimensionList<Index, NumDimensions> in_dims;
       return TensorReductionOp<internal::MinReducer<CoeffReturnType,NanPropagation>, const DimensionList<Index, NumDimensions>, const Derived>(derived(), in_dims, internal::MinReducer<CoeffReturnType,NanPropagation>());
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
minimum() [2/2]
template<typename Derived > template<typename Dims , int NanPropagation = PropagateFast> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorReductionOp<internal::MinReducer<CoeffReturnType,NanPropagation>, const Dims, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::minimum (const Dims & dims) const inline
{
       return TensorReductionOp<internal::MinReducer<CoeffReturnType,NanPropagation>, const Dims, const Derived>(derived(), dims, internal::MinReducer<CoeffReturnType,NanPropagation>());
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
ndtri()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_ndtri_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::ndtri () const inline
                   {
       return unaryExpr(internal::scalar_ndtri_op<Scalar>());
     }
nullaryExpr()
template<typename Derived > template<typename CustomNullaryOp > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseNullaryOp<CustomNullaryOp, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::nullaryExpr (const CustomNullaryOp & func) const inline
{
       return TensorCwiseNullaryOp<CustomNullaryOp, const Derived>(derived(), func);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
operator!()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_boolean_not_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator! () const inline
                       {
       return unaryExpr(internal::scalar_boolean_not_op<Scalar>());
     }
operator!=() [1/2]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp<internal::scalar_cmp_op<Scalar, Scalar, internal::cmp_NEQ>, const Derived, const OtherDerived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator!= (const TensorBase< OtherDerived, ReadOnlyAccessors > & other) const inline
{
       return binaryExpr(other.derived(), internal::scalar_cmp_op<Scalar, Scalar, internal::cmp_NEQ>());
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
operator!=() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp<internal::scalar_cmp_op<Scalar, Scalar, internal::cmp_NEQ>, const Derived, const TensorCwiseNullaryOp<internal::scalar_constant_op<Scalar>, const Derived> > Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator!= (Scalar threshold) const inline
{
       return operator!=(constant(threshold));
     }
References Eigen::operator!=().
operator%()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_mod_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator% (Scalar rhs) const inline
{
       EIGEN_STATIC_ASSERT(NumTraits<Scalar>::IsInteger, YOU_MADE_A_PROGRAMMING_MISTAKE_TRY_MOD);
       return unaryExpr(internal::scalar_mod_op<Scalar>(rhs));
     }
References EIGEN_STATIC_ASSERT.
operator&()
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp<internal::scalar_bitwise_and_op<Scalar>, const Derived, const OtherDerived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator& (const OtherDerived & other) const inline
{
       return binaryExpr(other.derived(), internal::scalar_bitwise_and_op<Scalar>());
     }
operator&&()
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp<internal::scalar_boolean_and_op<Scalar>, const Derived, const OtherDerived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator&& (const OtherDerived & other) const inline
{
       return binaryExpr(other.derived(), internal::scalar_boolean_and_op<Scalar>());
     }
operator*() [1/2]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp<internal::scalar_product_op<Scalar>, const Derived, const OtherDerived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator* (const OtherDerived & other) const inline
{
       return binaryExpr(other.derived(), internal::scalar_product_op<Scalar>());
     }
operator*() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::bind2nd_op<internal::scalar_product_op<Scalar,Scalar> >, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator* (Scalar rhs) const inline
{
       return unaryExpr(internal::bind2nd_op<internal::scalar_product_op<Scalar,Scalar> >(rhs));
     }
operator+() [1/2]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp<internal::scalar_sum_op<Scalar>, const Derived, const OtherDerived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator+ (const OtherDerived & other) const inline
{
       return binaryExpr(other.derived(), internal::scalar_sum_op<Scalar>());
     }
operator+() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::bind2nd_op<internal::scalar_sum_op<Scalar,Scalar> >, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator+ (Scalar rhs) const inline
{
       return unaryExpr(internal::bind2nd_op<internal::scalar_sum_op<Scalar,Scalar> >(rhs));
     }
operator-() [1/3]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_opposite_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator- (void) const inline
                       {
       return unaryExpr(internal::scalar_opposite_op<Scalar>());
     }
operator-() [2/3]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp<internal::scalar_difference_op<Scalar>, const Derived, const OtherDerived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator- (const OtherDerived & other) const inline
{
       return binaryExpr(other.derived(), internal::scalar_difference_op<Scalar>());
     }
operator-() [3/3]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::bind2nd_op<internal::scalar_difference_op<Scalar,Scalar> >, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator- (Scalar rhs) const inline
{
       EIGEN_STATIC_ASSERT((NumTraits<Scalar>::IsSigned || internal::is_same<Scalar, const std::complex<float> >::value), YOU_MADE_A_PROGRAMMING_MISTAKE);
       return unaryExpr(internal::bind2nd_op<internal::scalar_difference_op<Scalar,Scalar> >(rhs));
     }
References EIGEN_STATIC_ASSERT, and Eigen::value.
operator/() [1/2]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp<internal::scalar_quotient_op<Scalar>, const Derived, const OtherDerived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator/ (const OtherDerived & other) const inline
{
       return binaryExpr(other.derived(), internal::scalar_quotient_op<Scalar>());
     }
operator/() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::bind2nd_op<internal::scalar_quotient_op<Scalar,Scalar> >, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator/ (Scalar rhs) const inline
{
       return unaryExpr(internal::bind2nd_op<internal::scalar_quotient_op<Scalar,Scalar> >(rhs));
     }
operator<() [1/2]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp<internal::scalar_cmp_op<Scalar, Scalar, internal::cmp_LT>, const Derived, const OtherDerived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator< (const TensorBase< OtherDerived, ReadOnlyAccessors > & other) const inline
{
       return binaryExpr(other.derived(), internal::scalar_cmp_op<Scalar, Scalar, internal::cmp_LT>());
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
operator<() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp<internal::scalar_cmp_op<Scalar, Scalar, internal::cmp_LT>, const Derived, const TensorCwiseNullaryOp<internal::scalar_constant_op<Scalar>, const Derived> > Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator< (Scalar threshold) const inline
{
       return operator<(constant(threshold));
     }
References operator<().
operator<=() [1/2]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp<internal::scalar_cmp_op<Scalar, Scalar, internal::cmp_LE>, const Derived, const OtherDerived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator<= (const TensorBase< OtherDerived, ReadOnlyAccessors > & other) const inline
{
       return binaryExpr(other.derived(), internal::scalar_cmp_op<Scalar, Scalar, internal::cmp_LE>());
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
operator<=() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp<internal::scalar_cmp_op<Scalar, Scalar, internal::cmp_LE>, const Derived, const TensorCwiseNullaryOp<internal::scalar_constant_op<Scalar>, const Derived> > Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator<= (Scalar threshold) const inline
{
       return operator<=(constant(threshold));
     }
References operator<=().
operator==() [1/2]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp<internal::scalar_cmp_op<Scalar, Scalar, internal::cmp_EQ>, const Derived, const OtherDerived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator== (const TensorBase< OtherDerived, ReadOnlyAccessors > & other) const inline
{
       return binaryExpr(other.derived(), internal::scalar_cmp_op<Scalar, Scalar, internal::cmp_EQ>());
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
operator==() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp<internal::scalar_cmp_op<Scalar, Scalar, internal::cmp_EQ>, const Derived, const TensorCwiseNullaryOp<internal::scalar_constant_op<Scalar>, const Derived> > Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator== (Scalar threshold) const inline
{
       return operator==(constant(threshold));
     }
References Eigen::operator==().
operator>() [1/2]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp<internal::scalar_cmp_op<Scalar, Scalar, internal::cmp_GT>, const Derived, const OtherDerived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator> (const TensorBase< OtherDerived, ReadOnlyAccessors > & other) const inline
{
       return binaryExpr(other.derived(), internal::scalar_cmp_op<Scalar, Scalar, internal::cmp_GT>());
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
operator>() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp<internal::scalar_cmp_op<Scalar, Scalar, internal::cmp_GT>, const Derived, const TensorCwiseNullaryOp<internal::scalar_constant_op<Scalar>, const Derived> > Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator> (Scalar threshold) const inline
{
       return operator>(constant(threshold));
     }
References Eigen::bfloat16_impl::operator>().
operator>=() [1/2]
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp<internal::scalar_cmp_op<Scalar, Scalar, internal::cmp_GE>, const Derived, const OtherDerived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator>= (const TensorBase< OtherDerived, ReadOnlyAccessors > & other) const inline
{
       return binaryExpr(other.derived(), internal::scalar_cmp_op<Scalar, Scalar, internal::cmp_GE>());
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
operator>=() [2/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp<internal::scalar_cmp_op<Scalar, Scalar, internal::cmp_GE>, const Derived, const TensorCwiseNullaryOp<internal::scalar_constant_op<Scalar>, const Derived> > Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator>= (Scalar threshold) const inline
{
       return operator>=(constant(threshold));
     }
References Eigen::bfloat16_impl::operator>=().
operator^()
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp<internal::scalar_bitwise_xor_op<Scalar>, const Derived, const OtherDerived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator^ (const OtherDerived & other) const inline
{
       return binaryExpr(other.derived(), internal::scalar_bitwise_xor_op<Scalar>());
     }
operator|()
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp<internal::scalar_bitwise_or_op<Scalar>, const Derived, const OtherDerived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator| (const OtherDerived & other) const inline
{
       return binaryExpr(other.derived(), internal::scalar_bitwise_or_op<Scalar>());
     }
operator||()
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp<internal::scalar_boolean_or_op<Scalar>, const Derived, const OtherDerived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator|| (const OtherDerived & other) const inline
{
       return binaryExpr(other.derived(), internal::scalar_boolean_or_op<Scalar>());
     }
operator~()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_bitwise_not_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::operator~ () const inline
                       {
       return unaryExpr(internal::scalar_bitwise_not_op<Scalar>());
     }
pad() [1/2]
template<typename Derived > template<typename PaddingDimensions > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorPaddingOp<const PaddingDimensions, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::pad (const PaddingDimensions & padding) const inline
{
       return TensorPaddingOp<const PaddingDimensions, const Derived>(derived(), padding, internal::scalar_cast_op<int, Scalar>()(0));
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
pad() [2/2]
template<typename Derived > template<typename PaddingDimensions > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorPaddingOp<const PaddingDimensions, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::pad (const PaddingDimensions & padding, const Scalar padding_value) const inline
{
       return TensorPaddingOp<const PaddingDimensions, const Derived>(derived(), padding, padding_value);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
polygamma()
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp<internal::scalar_polygamma_op<Scalar>, const Derived, const OtherDerived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::polygamma (const OtherDerived & other) const inline
{
       return binaryExpr(other.derived(), internal::scalar_polygamma_op<Scalar>());
     }
pow()
template<typename Derived > template<typename ScalarExponent > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const std::enable_if_t<internal::is_arithmetic<typename NumTraits<ScalarExponent>::Real>::value, TensorCwiseUnaryOp<internal::scalar_unary_pow_op<Scalar, ScalarExponent>, const Derived> > Eigen::TensorBase< Derived, ReadOnlyAccessors >::pow (ScalarExponent exponent) const inline
     {
         return unaryExpr(internal::scalar_unary_pow_op<Scalar, ScalarExponent>(exponent));
     }
prod() [1/2]
template<typename Derived > const TensorReductionOp<internal::ProdReducer<CoeffReturnType>, const DimensionList<Index, NumDimensions>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::prod () const inline
                  {
       DimensionList<Index, NumDimensions> in_dims;
       return TensorReductionOp<internal::ProdReducer<CoeffReturnType>, const DimensionList<Index, NumDimensions>, const Derived>(derived(), in_dims, internal::ProdReducer<CoeffReturnType>());
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
prod() [2/2]
template<typename Derived > template<typename Dims > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorReductionOp<internal::ProdReducer<CoeffReturnType>, const Dims, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::prod (const Dims & dims) const inline
{
       return TensorReductionOp<internal::ProdReducer<CoeffReturnType>, const Dims, const Derived>(derived(), dims, internal::ProdReducer<CoeffReturnType>());
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
random() [1/2]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseNullaryOp<internal::UniformRandomGenerator<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::random () const inline
                    {
       return nullaryExpr(internal::UniformRandomGenerator<Scalar>());
     }
random() [2/2]
template<typename Derived > template<typename RandomGenerator > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseNullaryOp<RandomGenerator, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::random (const RandomGenerator & gen = RandomGenerator()) const inline
{
       return nullaryExpr(gen);
     }
real()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_real_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::real () const inline
                  {
       return unaryExpr(internal::scalar_real_op<Scalar>());
     }
reduce()
template<typename Derived > template<typename Reducer , typename Dims > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorReductionOp<Reducer, const Dims, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::reduce (const Dims & dims, const Reducer & reducer) const inline
{
       return TensorReductionOp<Reducer, const Dims, const Derived>(derived(), dims, reducer);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
reshape()
template<typename Derived > template<typename NewDimensions > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorReshapingOp<const NewDimensions, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::reshape (const NewDimensions & newDimensions) const inline
{
       return TensorReshapingOp<const NewDimensions, const Derived>(derived(), newDimensions);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
reverse()
template<typename Derived > template<typename ReverseDimensions > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorReverseOp<const ReverseDimensions, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::reverse (const ReverseDimensions & rev) const inline
{
       return TensorReverseOp<const ReverseDimensions, const Derived>(derived(), rev);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
rint()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_rint_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::rint () const inline
                  {
       return unaryExpr(internal::scalar_rint_op<Scalar>());
     }
roll()
template<typename Derived > template<typename Rolls > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorRollOp<const Rolls, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::roll (const Rolls & rolls) const inline
{
       return TensorRollOp<const Rolls, const Derived>(derived(), rolls);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
round()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_round_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::round () const inline
                   {
       return unaryExpr(internal::scalar_round_op<Scalar>());
     }
rsqrt()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_rsqrt_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::rsqrt () const inline
                   {
       return unaryExpr(internal::scalar_rsqrt_op<Scalar>());
     }
scan()
template<typename Derived > template<typename Reducer > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorScanOp<Reducer, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::scan (const Index & axis, const Reducer & reducer, bool exclusive = false) const inline
{
       return TensorScanOp<Reducer, const Derived>(derived(), axis, exclusive, reducer);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
select()
template<typename Derived > template<typename ThenDerived , typename ElseDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorSelectOp<const Derived, const ThenDerived, const ElseDerived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::select (const ThenDerived & thenTensor, const ElseDerived & elseTensor) const inline
{
       return TensorSelectOp<const Derived, const ThenDerived, const ElseDerived>(derived(), thenTensor.derived(), elseTensor.derived());
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
shuffle()
template<typename Derived > template<typename Shuffle > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorShufflingOp<const Shuffle, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::shuffle (const Shuffle & shfl) const inline
{
       return TensorShufflingOp<const Shuffle, const Derived>(derived(), shfl);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
sigmoid()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_logistic_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::sigmoid () const inline
                     {
       return unaryExpr(internal::scalar_logistic_op<Scalar>());
     }
sign()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_sign_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::sign () const inline
                  {
       return unaryExpr(internal::scalar_sign_op<Scalar>());
     }
slice()
template<typename Derived > template<typename StartIndices , typename Sizes > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorSlicingOp<const StartIndices, const Sizes, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::slice (const StartIndices & startIndices, const Sizes & sizes) const inline
{
       return TensorSlicingOp<const StartIndices, const Sizes, const Derived>(derived(), startIndices, sizes);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived(), and sizes.
sqrt()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_sqrt_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::sqrt () const inline
                  {
       return unaryExpr(internal::scalar_sqrt_op<Scalar>());
     }
square()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_square_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::square () const inline
                    {
       return unaryExpr(internal::scalar_square_op<Scalar>());
     }
stride()
template<typename Derived > template<typename Strides > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorStridingOp<const Strides, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::stride (const Strides & strides) const inline
{
       return TensorStridingOp<const Strides, const Derived>(derived(), strides);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived(), and Eigen::internal::strides().
stridedSlice()
template<typename Derived > template<typename StartIndices , typename StopIndices , typename Strides > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorStridingSlicingOp<const StartIndices, const StopIndices, const Strides, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::stridedSlice (const StartIndices & startIndices, const StopIndices & stopIndices, const Strides & strides) const inline
{
       return TensorStridingSlicingOp<const StartIndices, const StopIndices, const Strides,
                                 const Derived>(derived(), startIndices, stopIndices, strides);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived(), and Eigen::internal::strides().
sum() [1/2]
template<typename Derived > const TensorReductionOp<internal::SumReducer<CoeffReturnType>, const DimensionList<Index, NumDimensions>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::sum () const inline
                 {
       DimensionList<Index, NumDimensions> in_dims;
       return TensorReductionOp<internal::SumReducer<CoeffReturnType>, const DimensionList<Index, NumDimensions>, const Derived>(derived(), in_dims, internal::SumReducer<CoeffReturnType>());
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
sum() [2/2]
template<typename Derived > template<typename Dims > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorReductionOp<internal::SumReducer<CoeffReturnType>, const Dims, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::sum (const Dims & dims) const inline
{
       return TensorReductionOp<internal::SumReducer<CoeffReturnType>, const Dims, const Derived>(derived(), dims, internal::SumReducer<CoeffReturnType>());
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
swap_layout()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorLayoutSwapOp<const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::swap_layout () const inline
{
       return TensorLayoutSwapOp<const Derived>(derived());
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
tanh()
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<internal::scalar_tanh_op<Scalar>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::tanh () const inline
                  {
       return unaryExpr(internal::scalar_tanh_op<Scalar>());
     }
TensorConversionOp() [1/3]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Eigen::TensorBase< Derived, ReadOnlyAccessors >::TensorConversionOp (isfinite) const inline
{
       return unaryExpr(internal::scalar_isfinite_op<Scalar, true>()).template cast<bool>();
     }
TensorConversionOp() [2/3]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Eigen::TensorBase< Derived, ReadOnlyAccessors >::TensorConversionOp (isinf) const inline
                     {
       return unaryExpr(internal::scalar_isinf_op<Scalar, true>()).template cast<bool>();
     }
TensorConversionOp() [3/3]
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Eigen::TensorBase< Derived, ReadOnlyAccessors >::TensorConversionOp (isnan) const inline
                     {
       return unaryExpr(internal::scalar_isnan_op<Scalar, true>()).template cast<bool>();
     }
trace() [1/2]
template<typename Derived > const TensorTraceOp<const DimensionList<Index, NumDimensions>, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::trace () const inline
                   {
       DimensionList<Index, NumDimensions> in_dims;
       return TensorTraceOp<const DimensionList<Index, NumDimensions>, const Derived>(derived(), in_dims);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
trace() [2/2]
template<typename Derived > template<typename Dims > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorTraceOp<const Dims, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::trace (const Dims & dims) const inline
{
       return TensorTraceOp<const Dims, const Derived>(derived(), dims);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
unaryExpr()
template<typename Derived > template<typename CustomUnaryOp > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseUnaryOp<CustomUnaryOp, const Derived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::unaryExpr (const CustomUnaryOp & func) const inline
{
       return TensorCwiseUnaryOp<CustomUnaryOp, const Derived>(derived(), func);
     }
References Eigen::TensorBase< Derived, AccessLevel >::derived().
zeta()
template<typename Derived > template<typename OtherDerived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const TensorCwiseBinaryOp<internal::scalar_zeta_op<Scalar>, const Derived, const OtherDerived> Eigen::TensorBase< Derived, ReadOnlyAccessors >::zeta (const OtherDerived & other) const inline
{
       return binaryExpr(other.derived(), internal::scalar_zeta_op<Scalar>());
     }
Friends And Related Function Documentation
Eigen::TensorBase
template<typename Derived > template<typename OtherDerived , int AccessLevel> friend class Eigen::TensorBase friend
operator*
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE friend const TensorCwiseUnaryOp<internal::bind1st_op<internal::scalar_product_op<Scalar> >, const Derived> operator* (Scalar lhs, const Derived & rhs) friend
{
       return rhs.unaryExpr(internal::bind1st_op<internal::scalar_product_op<Scalar> >(lhs));
     }
operator+
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE friend const TensorCwiseUnaryOp<internal::bind1st_op<internal::scalar_sum_op<Scalar> >, const Derived> operator+ (Scalar lhs, const Derived & rhs) friend
{
       return rhs.unaryExpr(internal::bind1st_op<internal::scalar_sum_op<Scalar> >(lhs));
     }
operator-
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE friend const TensorCwiseUnaryOp<internal::bind1st_op<internal::scalar_difference_op<Scalar> >, const Derived> operator- (Scalar lhs, const Derived & rhs) friend
{
       return rhs.unaryExpr(internal::bind1st_op<internal::scalar_difference_op<Scalar> >(lhs));
     }
operator/
template<typename Derived > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE friend const TensorCwiseUnaryOp<internal::bind1st_op<internal::scalar_quotient_op<Scalar> >, const Derived> operator/ (Scalar lhs, const Derived & rhs) friend
{
       return rhs.unaryExpr(internal::bind1st_op<internal::scalar_quotient_op<Scalar> >(lhs));
     }
Tensor
template<typename Derived > template<typename Scalar , int NumIndices, int Options, typename IndexType > friend class Tensor friend
TensorFixedSize
template<typename Derived > template<typename Scalar , typename Dimensions , int Option, typename IndexTypes > friend class TensorFixedSize friend
Member Data Documentation
NumDimensions
template<typename Derived > constexpr int Eigen::TensorBase< Derived, ReadOnlyAccessors >::NumDimensions = DerivedTraits::NumDimensions static constexpr
The documentation for this class was generated from the following file:
TensorBase.h