MercuryDPM: matrixfree_cg.cpp File Reference
matrixfree_cg.cpp File Reference
#include <iostream>
#include <Eigen/Core>
#include <Eigen/Dense>
#include <Eigen/IterativeLinearSolvers>
#include <unsupported/Eigen/IterativeSolvers>
Classes
struct Eigen::internal::traits< MatrixReplacement >
class MatrixReplacement
struct Eigen::internal::generic_product_impl< MatrixReplacement, Rhs, SparseShape, DenseShape, GemvProduct >
Namespaces
Eigen
Namespace containing all symbols from the Eigen library.
Eigen::internal
Namespace containing low-level routines from the Eigen library.
Functions
int main ()
Function Documentation
main()
int main ()
            {
   int n = 10;
   Eigen::SparseMatrix<double> S = Eigen::MatrixXd::Random(n, n).sparseView(0.5, 1);
   S = S.transpose() * S;
   MatrixReplacement A;
   A.attachMyMatrix(S);
   Eigen::VectorXd b(n), x;
   b.setRandom();
   // Solve Ax = b using various iterative solver with matrix-free version:
   {
     Eigen::ConjugateGradient<MatrixReplacement, Eigen::Lower | Eigen::Upper, Eigen::IdentityPreconditioner> cg;
     cg.compute(A);
     x = cg.solve(b);
     std::cout << "CG:       #iterations: " << cg.iterations() << ", estimated error: " << cg.error() << std::endl;
   }
   {
     Eigen::BiCGSTAB<MatrixReplacement, Eigen::IdentityPreconditioner> bicg;
     bicg.compute(A);
     x = bicg.solve(b);
     std::cout << "BiCGSTAB: #iterations: " << bicg.iterations() << ", estimated error: " << bicg.error() << std::endl;
   }
   {
     Eigen::GMRES<MatrixReplacement, Eigen::IdentityPreconditioner> gmres;
     gmres.compute(A);
     x = gmres.solve(b);
     std::cout << "GMRES:    #iterations: " << gmres.iterations() << ", estimated error: " << gmres.error() << std::endl;
   }
   {
     Eigen::DGMRES<MatrixReplacement, Eigen::IdentityPreconditioner> gmres;
     gmres.compute(A);
     x = gmres.solve(b);
     std::cout << "DGMRES:   #iterations: " << gmres.iterations() << ", estimated error: " << gmres.error() << std::endl;
   }
   {
     Eigen::MINRES<MatrixReplacement, Eigen::Lower | Eigen::Upper, Eigen::IdentityPreconditioner> minres;
     minres.compute(A);
     x = minres.solve(b);
     std::cout << "MINRES:   #iterations: " << minres.iterations() << ", estimated error: " << minres.error()
               << std::endl;
   }
 }
References b, Eigen::IterativeSolverBase< Derived >::compute(), Eigen::IterativeSolverBase< Derived >::error(), Eigen::internal::gmres(), Eigen::IterativeSolverBase< Derived >::iterations(), Eigen::internal::minres(), n, oomph::QuadTreeNames::S, Eigen::SparseSolverBase< Derived >::solve(), and plotDoE::x.