MercuryDPM: oomph::TubeMesh< ELEMENT > Class Template Reference
oomph::TubeMesh< ELEMENT > Class Template Reference
#include <tube_mesh.template.h>
Public Member Functions
TubeMesh (GeomObject *wall_pt, const Vector< double > &centreline_limits, const Vector< double > &theta_positions, const Vector< double > &radius_box, const unsigned &nlayer, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
virtual ~TubeMesh ()
Destructor: empty.
GeomObject *& volume_pt ()
Access function to GeomObject representing wall.
TubeDomain * domain_pt ()
Access function to domain.
TubeDomain * domain_pt () const
Access function to underlying domain.
Public Member Functions inherited from oomph::BrickMeshBase
BrickMeshBase ()
Constructor (empty)
BrickMeshBase (const BrickMeshBase &)=delete
Broken copy constructor.
virtual ~BrickMeshBase ()
Broken assignment operator.
void setup_boundary_element_info ()
void setup_boundary_element_info (std::ostream &outfile)
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void node_update (const bool &update_all_solid_nodes=false)
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
virtual void read (std::ifstream &restart_file)
Read solution from restart file.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Protected Attributes
TubeDomain * Domain_pt
Pointer to domain.
GeomObject * Volume_pt
Pointer to the geometric object that represents the curved wall.
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Detailed Description
template<class ELEMENT>
class oomph::TubeMesh< ELEMENT >
3D tube mesh class. The domain is specified by the GeomObject that identifies the entire volume. Non-refineable base version!
The mesh boundaries are numbered as follows:
Boundary 0: "Inflow" cross section; located along the line parametrised by \(\xi_0 = \xi_0^{lo} \).
Boundary 1: The outer wall, represetned by \(\xi_2 = 1\).
Boundary 2: The out flow, represented by \(\xi_0 = \xi_0^{hi}\).
Constructor & Destructor Documentation
TubeMesh()
template<class ELEMENT > oomph::TubeMesh< ELEMENT >::TubeMesh (GeomObject * volume_pt, const Vector< double > & centreline_limits, const Vector< double > & theta_positions, const Vector< double > & radius_box, const unsigned & nlayer, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
Constructor: Pass pointer to geometric object that specifies the volume, start and end coordinates for the centreline on the geometric object. Values of theta at which dividing lines are to be placed, fractions of the radius for the central box at the dividing lines, the number of layers and the timestepper. Timestepper defaults to Steady dummy timestepper.
Constructor for deformable quarter tube mesh class. The domain is specified by the GeomObject that identifies the entire volume.
     : Volume_pt(volume_pt)
   {
     // Mesh can only be built with 3D Qelements.
     MeshChecker::assert_geometric_element<QElementGeometricBase, ELEMENT>(3);
     // Build macro element-based domain
     Domain_pt = new TubeDomain(
       volume_pt, centreline_limits, theta_positions, radius_box, nlayer);
     // Set the number of boundaries
     set_nboundary(3);
     // We have only bothered to parametrise boundary 1
     Boundary_coordinate_exists[1] = true;
     // Allocate the store for the elements
     unsigned nelem = 5 * nlayer;
     Element_pt.resize(nelem);
     // Create  dummy element so we can determine the number of nodes
     ELEMENT* dummy_el_pt = new ELEMENT;
     // Read out the number of linear points in the element
     unsigned n_p = dummy_el_pt->nnode_1d();
     // Kill the element
     delete dummy_el_pt;
     // Can now allocate the store for the nodes
     unsigned nnodes_total =
       (n_p * n_p + 4 * (n_p - 1) * (n_p - 1)) * (1 + nlayer * (n_p - 1));
     Node_pt.resize(nnodes_total);
     Vector<double> s(3);
     Vector<double> r(3);
     // Storage for the intrinsic boundary coordinate
     Vector<double> zeta(2);
     // Loop over elements and create all nodes
     for (unsigned ielem = 0; ielem < nelem; ielem++)
     {
       // Create element
       Element_pt[ielem] = new ELEMENT;
       // Loop over rows in z/s_2-direction
       for (unsigned i2 = 0; i2 < n_p; i2++)
       {
         // Loop over rows in y/s_1-direction
         for (unsigned i1 = 0; i1 < n_p; i1++)
         {
           // Loop over rows in x/s_0-direction
           for (unsigned i0 = 0; i0 < n_p; i0++)
           {
             // Local node number
             unsigned jnod_local = i0 + i1 * n_p + i2 * n_p * n_p;
             // Create the node
             Node* node_pt = finite_element_pt(ielem)->construct_node(
               jnod_local, time_stepper_pt);
             // Set the position of the node from macro element mapping
             s[0] = -1.0 + 2.0 * double(i0) / double(n_p - 1);
             s[1] = -1.0 + 2.0 * double(i1) / double(n_p - 1);
             s[2] = -1.0 + 2.0 * double(i2) / double(n_p - 1);
             Domain_pt->macro_element_pt(ielem)->macro_map(s, r);
             node_pt->x(0) = r[0];
             node_pt->x(1) = r[1];
             node_pt->x(2) = r[2];
           }
         }
       }
     }
     // Initialise number of global nodes
     unsigned node_count = 0;
     // Tolerance for node killing:
     double node_kill_tol = 1.0e-12;
     // Check for error in node killing
     bool stopit = false;
     // Define pine
     const double pi = MathematicalConstants::Pi;
     // Loop over elements
     for (unsigned ielem = 0; ielem < nelem; ielem++)
     {
       // Which layer?
       unsigned ilayer = unsigned(ielem / 5);
       // Which macro element?
       switch (ielem % 5)
       {
           // Macro element 0: Central box
           //-----------------------------
         case 0:
           // Loop over rows in z/s_2-direction
           for (unsigned i2 = 0; i2 < n_p; i2++)
           {
             // Loop over rows in y/s_1-direction
             for (unsigned i1 = 0; i1 < n_p; i1++)
             {
               // Loop over rows in x/s_0-direction
               for (unsigned i0 = 0; i0 < n_p; i0++)
               {
                 // Local node number
                 unsigned jnod_local = i0 + i1 * n_p + i2 * n_p * n_p;
                 // Has the node been killed?
                 bool killed = false;
                 // First layer of all nodes in s_2 direction gets killed
                 // and re-directed to nodes in previous element layer
                 if ((i2 == 0) && (ilayer > 0))
                 {
                   // Neighbour element
                   unsigned ielem_neigh = ielem - 5;
                   // Node in neighbour element
                   unsigned i0_neigh = i0;
                   unsigned i1_neigh = i1;
                   unsigned i2_neigh = n_p - 1;
                   unsigned jnod_local_neigh =
                     i0_neigh + i1_neigh * n_p + i2_neigh * n_p * n_p;
                   // Check:
                   for (unsigned i = 0; i < 3; i++)
                   {
                     double error = std::fabs(
                       finite_element_pt(ielem)->node_pt(jnod_local)->x(i) -
                       finite_element_pt(ielem_neigh)
                         ->node_pt(jnod_local_neigh)
                         ->x(i));
                     if (error > node_kill_tol)
                     {
                       oomph_info << "Error in node killing for i " << i << " "
                                  << error << std::endl;
                       stopit = true;
                     }
                   }
                   // Kill node
                   delete finite_element_pt(ielem)->node_pt(jnod_local);
                   killed = true;
                   // Set pointer to neighbour:
                   finite_element_pt(ielem)->node_pt(jnod_local) =
                     finite_element_pt(ielem_neigh)->node_pt(jnod_local_neigh);
                 }
                 // No duplicate node: Copy across to mesh
                 if (!killed)
                 {
                   Node_pt[node_count] =
                     finite_element_pt(ielem)->node_pt(jnod_local);
                   // Set boundaries:
                   // Back: Boundary 0
                   if ((i2 == 0) && (ilayer == 0))
                   {
                     this->convert_to_boundary_node(Node_pt[node_count]);
                     add_boundary_node(0, Node_pt[node_count]);
                   }
                   // Front: Boundary 2
                   if ((i2 == n_p - 1) && (ilayer == nlayer - 1))
                   {
                     this->convert_to_boundary_node(Node_pt[node_count]);
                     add_boundary_node(2, Node_pt[node_count]);
                   }
                   // Increment node counter
                   node_count++;
                 }
               }
             }
           }
           break;
           // Macro element 1: Bottom
           //---------------------------------
         case 1:
           // Loop over rows in z/s_2-direction
           for (unsigned i2 = 0; i2 < n_p; i2++)
           {
             // Loop over rows in y/s_1-direction
             for (unsigned i1 = 0; i1 < n_p; i1++)
             {
               // Loop over rows in x/s_0-direction
               for (unsigned i0 = 0; i0 < n_p; i0++)
               {
                 // Local node number
                 unsigned jnod_local = i0 + i1 * n_p + i2 * n_p * n_p;
                 // Has the node been killed?
                 bool killed = false;
                 // First layer of all nodes in s_2 direction gets killed
                 // and re-directed to nodes in previous element layer
                 if ((i2 == 0) && (ilayer > 0))
                 {
                   // Neighbour element
                   unsigned ielem_neigh = ielem - 5;
                   // Node in neighbour element
                   unsigned i0_neigh = i0;
                   unsigned i1_neigh = i1;
                   unsigned i2_neigh = n_p - 1;
                   unsigned jnod_local_neigh =
                     i0_neigh + i1_neigh * n_p + i2_neigh * n_p * n_p;
                   // Check:
                   for (unsigned i = 0; i < 3; i++)
                   {
                     double error = std::fabs(
                       finite_element_pt(ielem)->node_pt(jnod_local)->x(i) -
                       finite_element_pt(ielem_neigh)
                         ->node_pt(jnod_local_neigh)
                         ->x(i));
                     if (error > node_kill_tol)
                     {
                       oomph_info << "Error in node killing for i " << i << " "
                                  << error << std::endl;
                       stopit = true;
                     }
                   }
                   // Kill node
                   delete finite_element_pt(ielem)->node_pt(jnod_local);
                   killed = true;
                   // Set pointer to neighbour:
                   finite_element_pt(ielem)->node_pt(jnod_local) =
                     finite_element_pt(ielem_neigh)->node_pt(jnod_local_neigh);
                 }
                 // Not in first layer:
                 else
                 {
                   // Duplicate node: kill and set pointer to central element
                   if (i1 == (n_p - 1))
                   {
                     // Neighbour element
                     unsigned ielem_neigh = ielem - 1;
                     // Node in neighbour element
                     unsigned i0_neigh = i0;
                     unsigned i1_neigh = 0;
                     unsigned i2_neigh = i2;
                     unsigned jnod_local_neigh =
                       i0_neigh + i1_neigh * n_p + i2_neigh * n_p * n_p;
                     // Check:
                     for (unsigned i = 0; i < 3; i++)
                     {
                       double error = std::fabs(
                         finite_element_pt(ielem)->node_pt(jnod_local)->x(i) -
                         finite_element_pt(ielem_neigh)
                           ->node_pt(jnod_local_neigh)
                           ->x(i));
                       if (error > node_kill_tol)
                       {
                         oomph_info << "Error in node killing for i " << i << " "
                                    << error << std::endl;
                         stopit = true;
                       }
                     }
                     // Kill node
                     delete finite_element_pt(ielem)->node_pt(jnod_local);
                     killed = true;
                     // Set pointer to neighbour:
                     finite_element_pt(ielem)->node_pt(jnod_local) =
                       finite_element_pt(ielem_neigh)->node_pt(jnod_local_neigh);
                   }
                 }
                 // No duplicate node: Copy across to mesh
                 if (!killed)
                 {
                   Node_pt[node_count] =
                     finite_element_pt(ielem)->node_pt(jnod_local);
                   // Set boundaries:
                   // Back: Boundary 0
                   if ((i2 == 0) && (ilayer == 0))
                   {
                     this->convert_to_boundary_node(Node_pt[node_count]);
                     add_boundary_node(0, Node_pt[node_count]);
                   }
                   // Front: Boundary 2
                   if ((i2 == n_p - 1) && (ilayer == nlayer - 1))
                   {
                     this->convert_to_boundary_node(Node_pt[node_count]);
                     add_boundary_node(2, Node_pt[node_count]);
                   }
                   // Bottom: outer boundary
                   if (i1 == 0)
                   {
                     this->convert_to_boundary_node(Node_pt[node_count]);
                     add_boundary_node(1, Node_pt[node_count]);
                     // Get axial boundary coordinate
                     zeta[0] = centreline_limits[0] +
                               (double(ilayer) + double(i2) / double(n_p - 1)) *
                                 (centreline_limits[1] - centreline_limits[0]) /
                                 double(nlayer);
                     // Get azimuthal boundary coordinate
                     zeta[1] = theta_positions[0] +
                               double(i1) / double(n_p - 1) * 0.5 *
                                 (theta_positions[1] - theta_positions[0]);
                     Node_pt[node_count]->set_coordinates_on_boundary(1, zeta);
                   }
                   // Increment node counter
                   node_count++;
                 }
               }
             }
           } // End of loop over nodes
           break;
           // Macro element 2: Right element
           //--------------------------------
         case 2:
           // Loop over rows in z/s_2-direction
           for (unsigned i2 = 0; i2 < n_p; i2++)
           {
             // Loop over rows in y/s_1-direction
             for (unsigned i1 = 0; i1 < n_p; i1++)
             {
               // Loop over rows in x/s_0-direction
               for (unsigned i0 = 0; i0 < n_p; i0++)
               {
                 // Local node number
                 unsigned jnod_local = i0 + i1 * n_p + i2 * n_p * n_p;
                 // Has the node been killed?
                 bool killed = false;
                 // First layer of all nodes in s_2 direction gets killed
                 // and re-directed to nodes in previous element layer
                 if ((i2 == 0) && (ilayer > 0))
                 {
                   // Neighbour element
                   unsigned ielem_neigh = ielem - 5;
                   // Node in neighbour element
                   unsigned i0_neigh = i0;
                   unsigned i1_neigh = i1;
                   unsigned i2_neigh = n_p - 1;
                   unsigned jnod_local_neigh =
                     i0_neigh + i1_neigh * n_p + i2_neigh * n_p * n_p;
                   // Check:
                   for (unsigned i = 0; i < 3; i++)
                   {
                     double error = std::fabs(
                       finite_element_pt(ielem)->node_pt(jnod_local)->x(i) -
                       finite_element_pt(ielem_neigh)
                         ->node_pt(jnod_local_neigh)
                         ->x(i));
                     if (error > node_kill_tol)
                     {
                       oomph_info << "Error in node killing for i " << i << " "
                                  << error << std::endl;
                       stopit = true;
                     }
                   }
                   // Kill node
                   delete finite_element_pt(ielem)->node_pt(jnod_local);
                   killed = true;
                   // Set pointer to neighbour:
                   finite_element_pt(ielem)->node_pt(jnod_local) =
                     finite_element_pt(ielem_neigh)->node_pt(jnod_local_neigh);
                 }
                 // Not in first layer:
                 else
                 {
                   // Duplicate node: kill and set pointer to previous element
                   if (i1 == 0)
                   {
                     // Neighbour element
                     unsigned ielem_neigh = ielem - 1;
                     // Node in neighbour element
                     unsigned i0_neigh = n_p - 1;
                     unsigned i1_neigh = n_p - 1 - i0;
                     unsigned i2_neigh = i2;
                     unsigned jnod_local_neigh =
                       i0_neigh + i1_neigh * n_p + i2_neigh * n_p * n_p;
                     // Check:
                     for (unsigned i = 0; i < 3; i++)
                     {
                       double error = std::fabs(
                         finite_element_pt(ielem)->node_pt(jnod_local)->x(i) -
                         finite_element_pt(ielem_neigh)
                           ->node_pt(jnod_local_neigh)
                           ->x(i));
                       if (error > node_kill_tol)
                       {
                         oomph_info << "Error in node killing for i " << i << " "
                                    << error << std::endl;
                         stopit = true;
                       }
                     }
                     // Kill node
                     delete finite_element_pt(ielem)->node_pt(jnod_local);
                     killed = true;
                     // Set pointer to neighbour:
                     finite_element_pt(ielem)->node_pt(jnod_local) =
                       finite_element_pt(ielem_neigh)->node_pt(jnod_local_neigh);
                   }
                   // Duplicate node: kill and set pointer to central element
                   if ((i0 == 0) && (i1 != 0))
                   {
                     // Neighbour element
                     unsigned ielem_neigh = ielem - 2;
                     // Node in neighbour element
                     unsigned i0_neigh = n_p - 1;
                     unsigned i1_neigh = i1;
                     unsigned i2_neigh = i2;
                     unsigned jnod_local_neigh =
                       i0_neigh + i1_neigh * n_p + i2_neigh * n_p * n_p;
                     // Check:
                     for (unsigned i = 0; i < 3; i++)
                     {
                       double error = std::fabs(
                         finite_element_pt(ielem)->node_pt(jnod_local)->x(i) -
                         finite_element_pt(ielem_neigh)
                           ->node_pt(jnod_local_neigh)
                           ->x(i));
                       if (error > node_kill_tol)
                       {
                         oomph_info << "Error in node killing for i " << i << " "
                                    << error << std::endl;
                         stopit = true;
                       }
                     }
                     // Kill node
                     delete finite_element_pt(ielem)->node_pt(jnod_local);
                     killed = true;
                     // Set pointer to neighbour:
                     finite_element_pt(ielem)->node_pt(jnod_local) =
                       finite_element_pt(ielem_neigh)->node_pt(jnod_local_neigh);
                   }
                   // No duplicate node: Copy across to mesh
                   if (!killed)
                   {
                     Node_pt[node_count] =
                       finite_element_pt(ielem)->node_pt(jnod_local);
                     // Set boundaries:
                     // Back: Boundary 0
                     if ((i2 == 0) && (ilayer == 0))
                     {
                       this->convert_to_boundary_node(Node_pt[node_count]);
                       add_boundary_node(0, Node_pt[node_count]);
                     }
                     // Front: Boundary 2
                     if ((i2 == n_p - 1) && (ilayer == nlayer - 1))
                     {
                       this->convert_to_boundary_node(Node_pt[node_count]);
                       add_boundary_node(2, Node_pt[node_count]);
                     }
                     // Tube boundary
                     if (i0 == n_p - 1)
                     {
                       this->convert_to_boundary_node(Node_pt[node_count]);
                       add_boundary_node(1, Node_pt[node_count]);
                       // Get axial boundary coordinate
                       zeta[0] =
                         centreline_limits[0] +
                         (double(ilayer) + double(i2) / double(n_p - 1)) *
                           (centreline_limits[1] - centreline_limits[0]) /
                           double(nlayer);
                       // Get azimuthal boundary coordinate
                       zeta[1] = theta_positions[1] +
                                 double(i1) / double(n_p - 1) * 0.5 *
                                   (theta_positions[2] - theta_positions[1]);
                       Node_pt[node_count]->set_coordinates_on_boundary(1, zeta);
                     }
                     // Increment node counter
                     node_count++;
                   }
                 }
               }
             }
           }
           break;
           // Macro element 3: Top element
           //--------------------------------
         case 3:
           // Loop over rows in z/s_2-direction
           for (unsigned i2 = 0; i2 < n_p; i2++)
           {
             // Loop over rows in y/s_1-direction
             for (unsigned i1 = 0; i1 < n_p; i1++)
             {
               // Loop over rows in x/s_0-direction
               for (unsigned i0 = 0; i0 < n_p; i0++)
               {
                 // Local node number
                 unsigned jnod_local = i0 + i1 * n_p + i2 * n_p * n_p;
                 // Has the node been killed?
                 bool killed = false;
                 // First layer of all nodes in s_2 direction gets killed
                 // and re-directed to nodes in previous element layer
                 if ((i2 == 0) && (ilayer > 0))
                 {
                   // Neighbour element
                   unsigned ielem_neigh = ielem - 5;
                   // Node in neighbour element
                   unsigned i0_neigh = i0;
                   unsigned i1_neigh = i1;
                   unsigned i2_neigh = n_p - 1;
                   unsigned jnod_local_neigh =
                     i0_neigh + i1_neigh * n_p + i2_neigh * n_p * n_p;
                   // Check:
                   for (unsigned i = 0; i < 3; i++)
                   {
                     double error = std::fabs(
                       finite_element_pt(ielem)->node_pt(jnod_local)->x(i) -
                       finite_element_pt(ielem_neigh)
                         ->node_pt(jnod_local_neigh)
                         ->x(i));
                     if (error > node_kill_tol)
                     {
                       oomph_info << "Error in node killing for i " << i << " "
                                  << error << std::endl;
                       stopit = true;
                     }
                   }
                   // Kill node
                   delete finite_element_pt(ielem)->node_pt(jnod_local);
                   killed = true;
                   // Set pointer to neighbour:
                   finite_element_pt(ielem)->node_pt(jnod_local) =
                     finite_element_pt(ielem_neigh)->node_pt(jnod_local_neigh);
                 }
                 // Not in first layer:
                 else
                 {
                   // Duplicate node: kill and set pointer to previous element
                   if (i0 == n_p - 1)
                   {
                     // Neighbour element
                     unsigned ielem_neigh = ielem - 1;
                     // Node in neighbour element
                     unsigned i0_neigh = i1;
                     unsigned i1_neigh = n_p - 1;
                     unsigned i2_neigh = i2;
                     unsigned jnod_local_neigh =
                       i0_neigh + i1_neigh * n_p + i2_neigh * n_p * n_p;
                     // Check:
                     for (unsigned i = 0; i < 3; i++)
                     {
                       double error = std::fabs(
                         finite_element_pt(ielem)->node_pt(jnod_local)->x(i) -
                         finite_element_pt(ielem_neigh)
                           ->node_pt(jnod_local_neigh)
                           ->x(i));
                       if (error > node_kill_tol)
                       {
                         oomph_info << "Error in node killing for i " << i << " "
                                    << error << std::endl;
                         stopit = true;
                       }
                     }
                     // Kill node
                     delete finite_element_pt(ielem)->node_pt(jnod_local);
                     killed = true;
                     // Set pointer to neighbour:
                     finite_element_pt(ielem)->node_pt(jnod_local) =
                       finite_element_pt(ielem_neigh)->node_pt(jnod_local_neigh);
                   }
                   // Duplicate node: kill and set pointer to central element
                   if ((i1 == 0) && (i0 != n_p - 1))
                   {
                     // Neighbour element
                     unsigned ielem_neigh = ielem - 3;
                     // Node in neighbour element
                     unsigned i0_neigh = i0;
                     unsigned i1_neigh = n_p - 1;
                     unsigned i2_neigh = i2;
                     unsigned jnod_local_neigh =
                       i0_neigh + i1_neigh * n_p + i2_neigh * n_p * n_p;
                     // Check:
                     for (unsigned i = 0; i < 3; i++)
                     {
                       double error = std::fabs(
                         finite_element_pt(ielem)->node_pt(jnod_local)->x(i) -
                         finite_element_pt(ielem_neigh)
                           ->node_pt(jnod_local_neigh)
                           ->x(i));
                       if (error > node_kill_tol)
                       {
                         oomph_info << "Error in node killing for i " << i << " "
                                    << error << std::endl;
                         stopit = true;
                       }
                     }
                     // Kill node
                     delete finite_element_pt(ielem)->node_pt(jnod_local);
                     killed = true;
                     // Set pointer to neighbour:
                     finite_element_pt(ielem)->node_pt(jnod_local) =
                       finite_element_pt(ielem_neigh)->node_pt(jnod_local_neigh);
                   }
                   // No duplicate node: Copy across to mesh
                   if (!killed)
                   {
                     Node_pt[node_count] =
                       finite_element_pt(ielem)->node_pt(jnod_local);
                     // Set boundaries:
                     // Back: Boundary 0
                     if ((i2 == 0) && (ilayer == 0))
                     {
                       this->convert_to_boundary_node(Node_pt[node_count]);
                       add_boundary_node(0, Node_pt[node_count]);
                     }
                     // Front: Boundary 2
                     if ((i2 == n_p - 1) && (ilayer == nlayer - 1))
                     {
                       this->convert_to_boundary_node(Node_pt[node_count]);
                       add_boundary_node(2, Node_pt[node_count]);
                     }
                     // Tube boundary
                     if (i1 == n_p - 1)
                     {
                       this->convert_to_boundary_node(Node_pt[node_count]);
                       add_boundary_node(1, Node_pt[node_count]);
                       // Get axial boundary coordinate
                       zeta[0] =
                         centreline_limits[0] +
                         (double(ilayer) + double(i2) / double(n_p - 1)) *
                           (centreline_limits[1] - centreline_limits[0]) /
                           double(nlayer);
                       // Get azimuthal boundary coordinate
                       zeta[1] = theta_positions[3] +
                                 double(i0) / double(n_p - 1) * 0.5 *
                                   (theta_positions[2] - theta_positions[3]);
                       Node_pt[node_count]->set_coordinates_on_boundary(1, zeta);
                     }
                     // Increment node counter
                     node_count++;
                   }
                 }
               }
             }
           }
           break;
           // Macro element 4: Left element
           //--------------------------------
         case 4:
           // Loop over rows in z/s_2-direction
           for (unsigned i2 = 0; i2 < n_p; i2++)
           {
             // Loop over rows in y/s_1-direction
             for (unsigned i1 = 0; i1 < n_p; i1++)
             {
               // Loop over rows in x/s_0-direction
               for (unsigned i0 = 0; i0 < n_p; i0++)
               {
                 // Local node number
                 unsigned jnod_local = i0 + i1 * n_p + i2 * n_p * n_p;
                 // Has the node been killed?
                 bool killed = false;
                 // First layer of all nodes in s_2 direction gets killed
                 // and re-directed to nodes in previous element layer
                 if ((i2 == 0) && (ilayer > 0))
                 {
                   // Neighbour element
                   unsigned ielem_neigh = ielem - 5;
                   // Node in neighbour element
                   unsigned i0_neigh = i0;
                   unsigned i1_neigh = i1;
                   unsigned i2_neigh = n_p - 1;
                   unsigned jnod_local_neigh =
                     i0_neigh + i1_neigh * n_p + i2_neigh * n_p * n_p;
                   // Check:
                   for (unsigned i = 0; i < 3; i++)
                   {
                     double error = std::fabs(
                       finite_element_pt(ielem)->node_pt(jnod_local)->x(i) -
                       finite_element_pt(ielem_neigh)
                         ->node_pt(jnod_local_neigh)
                         ->x(i));
                     if (error > node_kill_tol)
                     {
                       oomph_info << "Error in node killing for i " << i << " "
                                  << error << std::endl;
                       stopit = true;
                     }
                   }
                   // Kill node
                   delete finite_element_pt(ielem)->node_pt(jnod_local);
                   killed = true;
                   // Set pointer to neighbour:
                   finite_element_pt(ielem)->node_pt(jnod_local) =
                     finite_element_pt(ielem_neigh)->node_pt(jnod_local_neigh);
                 }
                 // Not in first layer:
                 else
                 {
                   // Duplicate node: kill and set pointer to previous element
                   if (i1 == n_p - 1)
                   {
                     // Neighbour element
                     unsigned ielem_neigh = ielem - 1;
                     // Node in neighbour element
                     unsigned i0_neigh = 0;
                     unsigned i1_neigh = n_p - 1 - i0;
                     unsigned i2_neigh = i2;
                     unsigned jnod_local_neigh =
                       i0_neigh + i1_neigh * n_p + i2_neigh * n_p * n_p;
                     // Check:
                     for (unsigned i = 0; i < 3; i++)
                     {
                       double error = std::fabs(
                         finite_element_pt(ielem)->node_pt(jnod_local)->x(i) -
                         finite_element_pt(ielem_neigh)
                           ->node_pt(jnod_local_neigh)
                           ->x(i));
                       if (error > node_kill_tol)
                       {
                         oomph_info << "Error in node killing for i " << i << " "
                                    << error << std::endl;
                         stopit = true;
                       }
                     }
                     // Kill node
                     delete finite_element_pt(ielem)->node_pt(jnod_local);
                     killed = true;
                     // Set pointer to neighbour:
                     finite_element_pt(ielem)->node_pt(jnod_local) =
                       finite_element_pt(ielem_neigh)->node_pt(jnod_local_neigh);
                   }
                   // Duplicate node: kill and set pointer to central element
                   if ((i0 == n_p - 1) && (i1 != n_p - 1))
                   {
                     // Neighbour element
                     unsigned ielem_neigh = ielem - 4;
                     // Node in neighbour element
                     unsigned i0_neigh = 0;
                     unsigned i1_neigh = i1;
                     unsigned i2_neigh = i2;
                     unsigned jnod_local_neigh =
                       i0_neigh + i1_neigh * n_p + i2_neigh * n_p * n_p;
                     // Check:
                     for (unsigned i = 0; i < 3; i++)
                     {
                       double error = std::fabs(
                         finite_element_pt(ielem)->node_pt(jnod_local)->x(i) -
                         finite_element_pt(ielem_neigh)
                           ->node_pt(jnod_local_neigh)
                           ->x(i));
                       if (error > node_kill_tol)
                       {
                         oomph_info << "Error in node killing for i " << i << " "
                                    << error << std::endl;
                         stopit = true;
                       }
                     }
                     // Kill node
                     delete finite_element_pt(ielem)->node_pt(jnod_local);
                     killed = true;
                     // Set pointer to neighbour:
                     finite_element_pt(ielem)->node_pt(jnod_local) =
                       finite_element_pt(ielem_neigh)->node_pt(jnod_local_neigh);
                   }
                   // Duplicate node: kill and set pointer to other ring element
                   if ((i1 == 0) && (i0 != n_p - 1))
                   {
                     // Neighbour element
                     unsigned ielem_neigh = ielem - 3;
                     // Node in neighbour element
                     unsigned i0_neigh = 0;
                     unsigned i1_neigh = i0;
                     unsigned i2_neigh = i2;
                     unsigned jnod_local_neigh =
                       i0_neigh + i1_neigh * n_p + i2_neigh * n_p * n_p;
                     // Check:
                     for (unsigned i = 0; i < 3; i++)
                     {
                       double error = std::fabs(
                         finite_element_pt(ielem)->node_pt(jnod_local)->x(i) -
                         finite_element_pt(ielem_neigh)
                           ->node_pt(jnod_local_neigh)
                           ->x(i));
                       if (error > node_kill_tol)
                       {
                         oomph_info << "Error in node killing for i " << i << " "
                                    << error << std::endl;
                         stopit = true;
                       }
                     }
                     // Kill node
                     delete finite_element_pt(ielem)->node_pt(jnod_local);
                     killed = true;
                     // Set pointer to neighbour:
                     finite_element_pt(ielem)->node_pt(jnod_local) =
                       finite_element_pt(ielem_neigh)->node_pt(jnod_local_neigh);
                   }
                   // No duplicate node: Copy across to mesh
                   if (!killed)
                   {
                     Node_pt[node_count] =
                       finite_element_pt(ielem)->node_pt(jnod_local);
                     // Set boundaries:
                     // Back: Boundary 0
                     if ((i2 == 0) && (ilayer == 0))
                     {
                       this->convert_to_boundary_node(Node_pt[node_count]);
                       add_boundary_node(0, Node_pt[node_count]);
                     }
                     // Front: Boundary 2
                     if ((i2 == n_p - 1) && (ilayer == nlayer - 1))
                     {
                       this->convert_to_boundary_node(Node_pt[node_count]);
                       add_boundary_node(2, Node_pt[node_count]);
                     }
                     // Tube boundary
                     if (i0 == 0)
                     {
                       this->convert_to_boundary_node(Node_pt[node_count]);
                       add_boundary_node(1, Node_pt[node_count]);
                       // Get axial boundary coordinate
                       zeta[0] =
                         centreline_limits[0] +
                         (double(ilayer) + double(i2) / double(n_p - 1)) *
                           (centreline_limits[1] - centreline_limits[0]) /
                           double(nlayer);
                       // Get azimuthal boundary coordinate
                       zeta[1] =
                         theta_positions[0] + 2.0 * pi +
                         double(i1) / double(n_p - 1) * 0.5 *
                           (theta_positions[3] - theta_positions[0] + 2.0 * pi);
                       Node_pt[node_count]->set_coordinates_on_boundary(1, zeta);
                     }
                     // Increment node counter
                     node_count++;
                   }
                 }
               }
             }
           }
           break;
       }
     }
     // Terminate if there's been an error
     if (stopit)
     {
       std::ostringstream error_stream;
       error_stream << "Error in killing nodes\n"
                    << "The most probable cause is that the domain is not\n"
                    << "compatible with the mesh.\n"
                    << "For the TubeMesh, the domain must be\n"
                    << "topologically consistent with a quarter tube with a\n"
                    << "non-curved centreline.\n";
       throw OomphLibError(
         error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     }
     // Setup boundary element lookup schemes
     setup_boundary_element_info();
   }
References oomph::Mesh::add_boundary_node(), oomph::Mesh::Boundary_coordinate_exists, oomph::FiniteElement::construct_node(), oomph::Mesh::convert_to_boundary_node(), oomph::TubeMesh< ELEMENT >::Domain_pt, oomph::Mesh::Element_pt, calibrate::error, boost::multiprecision::fabs(), oomph::Mesh::finite_element_pt(), i, oomph::Domain::macro_element_pt(), oomph::MacroElement::macro_map(), oomph::FiniteElement::node_pt(), oomph::Mesh::Node_pt, oomph::Mesh::node_pt(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::oomph_info, constants::pi, oomph::MathematicalConstants::Pi, UniformPSDSelfTest::r, s, oomph::Mesh::set_nboundary(), oomph::BrickMeshBase::setup_boundary_element_info(), oomph::TubeMesh< ELEMENT >::volume_pt(), plotDoE::x, oomph::Node::x(), and Eigen::zeta().
~TubeMesh()
template<class ELEMENT > virtual oomph::TubeMesh< ELEMENT >::~TubeMesh () inline virtual
Destructor: empty.
     {
       delete Domain_pt;
     }
References oomph::TubeMesh< ELEMENT >::Domain_pt.
Member Function Documentation
domain_pt() [1/2]
template<class ELEMENT > TubeDomain* oomph::TubeMesh< ELEMENT >::domain_pt () inline
Access function to domain.
     {
       return Domain_pt;
     }
References oomph::TubeMesh< ELEMENT >::Domain_pt.
domain_pt() [2/2]
template<class ELEMENT > TubeDomain* oomph::TubeMesh< ELEMENT >::domain_pt () const inline
Access function to underlying domain.
     {
       return Domain_pt;
     }
References oomph::TubeMesh< ELEMENT >::Domain_pt.
volume_pt()
template<class ELEMENT > GeomObject*& oomph::TubeMesh< ELEMENT >::volume_pt () inline
Access function to GeomObject representing wall.
     {
       return Volume_pt;
     }
References oomph::TubeMesh< ELEMENT >::Volume_pt.
Referenced by oomph::TubeMesh< ELEMENT >::TubeMesh().
Member Data Documentation
Domain_pt
template<class ELEMENT > TubeDomain* oomph::TubeMesh< ELEMENT >::Domain_pt protected
Pointer to domain.
Referenced by oomph::TubeMesh< ELEMENT >::domain_pt(), oomph::RefineableTubeMesh< ELEMENT >::RefineableTubeMesh(), oomph::TubeMesh< ELEMENT >::TubeMesh(), and oomph::TubeMesh< ELEMENT >::~TubeMesh().
Volume_pt
template<class ELEMENT > GeomObject* oomph::TubeMesh< ELEMENT >::Volume_pt protected
Pointer to the geometric object that represents the curved wall.
Referenced by oomph::TubeMesh< ELEMENT >::volume_pt().
The documentation for this class was generated from the following files:
tube_mesh.template.h
tube_mesh.template.cc