MercuryDPM: InterfaceProblem< ELEMENT, TIMESTEPPER > Class Template Reference
InterfaceProblem< ELEMENT, TIMESTEPPER > Class Template Reference
Single axisymmetric fluid interface problem in rectangular domain.
Public Member Functions
InterfaceProblem (const unsigned &n_r, const unsigned &n_z, const double &l_r, const double &h)
Constructor for single fluid interface problem.
~InterfaceProblem ()
Destructor (empty)
void actions_before_newton_convergence_check ()
void actions_before_newton_solve ()
void actions_after_newton_solve ()
void set_initial_condition ()
void doc_solution (DocInfo &doc_info)
Doc the solution.
void unsteady_run (const double &t_max, const double &dt)
Do unsteady run up to maximum time t_max with given timestep dt.
InterfaceProblem (const unsigned &n_r, const unsigned &n_z, const double &l_r, const double &h)
~InterfaceProblem ()
Destructor (empty)
void actions_before_newton_convergence_check ()
void actions_before_newton_solve ()
void actions_after_newton_solve ()
void set_initial_condition ()
void doc_solution (DocInfo &doc_info)
Doc the solution.
void unsteady_run (const double &t_max, const double &dt)
Do unsteady run up to maximum time t_max with given timestep dt.
InterfaceProblem ()
Constructor.
~InterfaceProblem ()
Destructor (empty)
void set_initial_condition ()
Set initial conditions.
void set_boundary_conditions ()
Set boundary conditions.
void doc_solution (DocInfo &doc_info)
Document the solution.
void unsteady_run (const double &t_max, const double &dt)
Do unsteady run up to maximum time t_max with given timestep dt.
InterfaceProblem (const unsigned &n_r, const unsigned &n_z1, const unsigned &n_z2, const double &l_r, const double &h1, const double &h2)
Constructor for axisymmetric two fluid interface problem.
~InterfaceProblem ()
Destructor (empty)
void set_initial_condition ()
Set initial conditions.
void set_boundary_conditions ()
Set boundary conditions.
void doc_solution (DocInfo &doc_info)
Doc the solution.
void unsteady_run (const double &t_max, const double &dt)
Do unsteady run up to maximum time t_max with given timestep dt.
InterfaceProblem (const unsigned &n_r, const unsigned &n_y, const unsigned &n_theta, const double &r_min, const double &r_max, const double &l_y, const double &theta_max)
Problem constructor.
void actions_before_newton_convergence_check ()
void unsteady_run (const unsigned &nstep)
Run an unsteady simulation with specified number of steps.
void doc_solution (DocInfo &doc_info)
Doc the solution.
double compute_total_mass ()
Compute the total mass.
InterfaceProblem (const unsigned &n_r, const unsigned &n_z, const double &l_z)
Constructor for single fluid interface problem.
~InterfaceProblem ()
Destructor (empty)
void actions_before_newton_convergence_check ()
void set_initial_condition ()
double global_temporal_error_norm ()
void doc_solution (DocInfo &doc_info)
Doc the solution.
void unsteady_run (const double &t_max, const double &dt)
Do unsteady run up to maximum time t_max with given timestep dt.
double compute_total_mass ()
Compute the total mass of the insoluble surfactant.
InterfaceProblem (const unsigned &n_r, const unsigned &n_z, const double &l_z)
~InterfaceProblem ()
Destructor (empty)
void set_initial_condition ()
double global_temporal_error_norm ()
void doc_solution (DocInfo &doc_info)
Doc the solution.
void unsteady_run (const double &t_max, const double &dt)
Do unsteady run up to maximum time t_max with given timestep dt.
double compute_total_mass ()
Compute the total mass of the insoluble surfactant.
InterfaceProblem (const unsigned &n_x, const unsigned &n_y, const double &l_x, const double &h)
~InterfaceProblem ()
Destructor (empty)
void set_initial_condition ()
Set initial conditions.
void set_boundary_conditions ()
Set boundary conditions.
void doc_solution (DocInfo &doc_info)
Document the solution.
void unsteady_run (const double &t_max, const double &dt)
Do unsteady run up to maximum time t_max with given timestep dt.
InterfaceProblem (const unsigned &n_x, const unsigned &n_y, const double &l_x, const double &h)
~InterfaceProblem ()
Destructor (empty)
void set_initial_condition ()
Set initial conditions.
void set_boundary_conditions ()
Set boundary conditions.
void doc_solution (DocInfo &doc_info)
Doc the solution.
void unsteady_run (const double &t_max, const double &dt)
Do unsteady run up to maximum time t_max with given timestep dt.
InterfaceProblem (const unsigned &Nx, const unsigned &Ny, const unsigned &Nz, const double &Lx, const double &Ly, const double &h)
void actions_before_newton_convergence_check ()
void unsteady_run (const unsigned &nstep)
Run an unsteady simulation with specified number of steps.
void doc_solution (DocInfo &doc_info)
Doc the solution.
InterfaceProblem ()
Constructor.
~InterfaceProblem ()
Destructor (empty)
void set_initial_condition ()
Set initial conditions.
void set_boundary_conditions ()
Set boundary conditions.
void doc_solution (DocInfo &doc_info)
Document the solution.
void unsteady_run (const double &t_max, const double &dt)
Do unsteady run up to maximum time t_max with given timestep dt.
InterfaceProblem (const unsigned &n_x, const unsigned &n_y1, const unsigned &n_y2, const double &l_x, const double &h1, const double &h2)
~InterfaceProblem ()
Destructor (empty)
void set_initial_condition ()
Set initial conditions.
void set_boundary_conditions ()
Set boundary conditions.
void doc_solution (DocInfo &doc_info)
Doc the solution.
void unsteady_run (const double &t_max, const double &dt)
Do unsteady run up to maximum time t_max with given timestep dt.
Public Member Functions inherited from oomph::Problem
virtual void debug_hook_fct (const unsigned &i)
void set_analytic_dparameter (double *const &parameter_pt)
void unset_analytic_dparameter (double *const &parameter_pt)
bool is_dparameter_calculated_analytically (double *const &parameter_pt)
void set_analytic_hessian_products ()
void unset_analytic_hessian_products ()
bool are_hessian_products_calculated_analytically ()
void set_pinned_values_to_zero ()
bool distributed () const
OomphCommunicator * communicator_pt ()
access function to the oomph-lib communicator
const OomphCommunicator * communicator_pt () const
access function to the oomph-lib communicator, const version
Problem ()
Problem (const Problem &dummy)=delete
Broken copy constructor.
void operator= (const Problem &)=delete
Broken assignment operator.
virtual ~Problem ()
Virtual destructor to clean up memory.
Mesh *& mesh_pt ()
Return a pointer to the global mesh.
Mesh *const & mesh_pt () const
Return a pointer to the global mesh (const version)
Mesh *& mesh_pt (const unsigned &imesh)
Mesh *const & mesh_pt (const unsigned &imesh) const
Return a pointer to the i-th submesh (const version)
unsigned nsub_mesh () const
Return number of submeshes.
unsigned add_sub_mesh (Mesh *const &mesh_pt)
void flush_sub_meshes ()
void build_global_mesh ()
void rebuild_global_mesh ()
LinearSolver *& linear_solver_pt ()
Return a pointer to the linear solver object.
LinearSolver *const & linear_solver_pt () const
Return a pointer to the linear solver object (const version)
LinearSolver *& mass_matrix_solver_for_explicit_timestepper_pt ()
LinearSolver * mass_matrix_solver_for_explicit_timestepper_pt () const
EigenSolver *& eigen_solver_pt ()
Return a pointer to the eigen solver object.
EigenSolver *const & eigen_solver_pt () const
Return a pointer to the eigen solver object (const version)
Time *& time_pt ()
Return a pointer to the global time object.
Time * time_pt () const
Return a pointer to the global time object (const version).
double & time ()
Return the current value of continuous time.
double time () const
Return the current value of continuous time (const version)
TimeStepper *& time_stepper_pt ()
const TimeStepper * time_stepper_pt () const
TimeStepper *& time_stepper_pt (const unsigned &i)
Return a pointer to the i-th timestepper.
ExplicitTimeStepper *& explicit_time_stepper_pt ()
Return a pointer to the explicit timestepper.
unsigned long set_timestepper_for_all_data (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data=false)
virtual void shift_time_values ()
Shift all values along to prepare for next timestep.
AssemblyHandler *& assembly_handler_pt ()
Return a pointer to the assembly handler object.
AssemblyHandler *const & assembly_handler_pt () const
Return a pointer to the assembly handler object (const version)
double & minimum_dt ()
Access function to min timestep in adaptive timestepping.
double & maximum_dt ()
Access function to max timestep in adaptive timestepping.
unsigned & max_newton_iterations ()
Access function to max Newton iterations before giving up.
void problem_is_nonlinear (const bool &prob_lin)
Access function to Problem_is_nonlinear.
double & max_residuals ()
bool & time_adaptive_newton_crash_on_solve_fail ()
Access function for Time_adaptive_newton_crash_on_solve_fail.
double & newton_solver_tolerance ()
void add_time_stepper_pt (TimeStepper *const &time_stepper_pt)
void set_explicit_time_stepper_pt (ExplicitTimeStepper *const &explicit_time_stepper_pt)
void initialise_dt (const double &dt)
void initialise_dt (const Vector< double > &dt)
Data *& global_data_pt (const unsigned &i)
Return a pointer to the the i-th global data object.
void add_global_data (Data *const &global_data_pt)
void flush_global_data ()
LinearAlgebraDistribution *const & dof_distribution_pt () const
Return the pointer to the dof distribution (read-only)
unsigned long ndof () const
Return the number of dofs.
unsigned ntime_stepper () const
Return the number of time steppers.
unsigned nglobal_data () const
Return the number of global data values.
unsigned self_test ()
Self-test: Check meshes and global data. Return 0 for OK.
void enable_store_local_dof_pt_in_elements ()
void disable_store_local_dof_pt_in_elements ()
unsigned long assign_eqn_numbers (const bool &assign_local_eqn_numbers=true)
void describe_dofs (std::ostream &out= *(oomph_info.stream_pt())) const
void enable_discontinuous_formulation ()
void disable_discontinuous_formulation ()
void get_dofs (DoubleVector &dofs) const
void get_dofs (const unsigned &t, DoubleVector &dofs) const
Return vector of the t'th history value of all dofs.
void set_dofs (const DoubleVector &dofs)
Set the values of the dofs.
void set_dofs (const unsigned &t, DoubleVector &dofs)
Set the history values of the dofs.
void set_dofs (const unsigned &t, Vector< double * > &dof_pt)
void add_to_dofs (const double &lambda, const DoubleVector &increment_dofs)
Add lambda x incremenet_dofs[l] to the l-th dof.
double * global_dof_pt (const unsigned &i)
double & dof (const unsigned &i)
i-th dof in the problem
double dof (const unsigned &i) const
i-th dof in the problem (const version)
double *& dof_pt (const unsigned &i)
Pointer to i-th dof in the problem.
double * dof_pt (const unsigned &i) const
Pointer to i-th dof in the problem (const version)
virtual void get_inverse_mass_matrix_times_residuals (DoubleVector &Mres)
virtual void get_dvaluesdt (DoubleVector &f)
virtual void get_residuals (DoubleVector &residuals)
Get the total residuals Vector for the problem.
virtual void get_jacobian (DoubleVector &residuals, DenseDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CRDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, CCDoubleMatrix &jacobian)
virtual void get_jacobian (DoubleVector &residuals, SumOfMatrices &jacobian)
void get_fd_jacobian (DoubleVector &residuals, DenseMatrix< double > &jacobian)
Get the full Jacobian by finite differencing.
void get_derivative_wrt_global_parameter (double *const &parameter_pt, DoubleVector &result)
void get_hessian_vector_products (DoubleVectorWithHaloEntries const &Y, Vector< DoubleVectorWithHaloEntries > const &C, Vector< DoubleVectorWithHaloEntries > &product)
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, Vector< DoubleVector > &eigenvector, const bool &steady=true)
Solve the eigenproblem.
void solve_eigenproblem (const unsigned &n_eval, Vector< std::complex< double >> &eigenvalue, const bool &steady=true)
virtual void get_eigenproblem_matrices (CRDoubleMatrix &mass_matrix, CRDoubleMatrix &main_matrix, const double &shift=0.0)
void assign_eigenvector_to_dofs (DoubleVector &eigenvector)
Assign the eigenvector passed to the function to the dofs.
void add_eigenvector_to_dofs (const double &epsilon, const DoubleVector &eigenvector)
void store_current_dof_values ()
Store the current values of the degrees of freedom.
void restore_dof_values ()
Restore the stored values of the degrees of freedom.
void enable_jacobian_reuse ()
void disable_jacobian_reuse ()
Disable recycling of Jacobian in Newton iteration.
bool jacobian_reuse_is_enabled ()
Is recycling of Jacobian in Newton iteration enabled?
bool & use_predictor_values_as_initial_guess ()
void newton_solve ()
Use Newton method to solve the problem.
void enable_globally_convergent_newton_method ()
enable globally convergent Newton method
void disable_globally_convergent_newton_method ()
disable globally convergent Newton method
void newton_solve (unsigned const &max_adapt)
void steady_newton_solve (unsigned const &max_adapt=0)
void copy (Problem *orig_problem_pt)
virtual Problem * make_copy ()
virtual void read (std::ifstream &restart_file, bool &unsteady_restart)
virtual void read (std::ifstream &restart_file)
virtual void dump (std::ofstream &dump_file) const
void dump (const std::string &dump_file_name) const
void delete_all_external_storage ()
virtual void symmetrise_eigenfunction_for_adaptive_pitchfork_tracking ()
double * bifurcation_parameter_pt () const
void get_bifurcation_eigenfunction (Vector< DoubleVector > &eigenfunction)
void activate_fold_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const bool &block_solve=true)
void activate_bifurcation_tracking (double *const &parameter_pt, const DoubleVector &eigenvector, const DoubleVector &normalisation, const bool &block_solve=true)
void activate_pitchfork_tracking (double *const &parameter_pt, const DoubleVector &symmetry_vector, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const bool &block_solve=true)
void activate_hopf_tracking (double *const &parameter_pt, const double &omega, const DoubleVector &null_real, const DoubleVector &null_imag, const bool &block_solve=true)
void deactivate_bifurcation_tracking ()
void reset_assembly_handler_to_default ()
Reset the system to the standard non-augemented state.
double arc_length_step_solve (double *const &parameter_pt, const double &ds, const unsigned &max_adapt=0)
double arc_length_step_solve (Data *const &data_pt, const unsigned &data_index, const double &ds, const unsigned &max_adapt=0)
void reset_arc_length_parameters ()
int & sign_of_jacobian ()
void explicit_timestep (const double &dt, const bool &shift_values=true)
Take an explicit timestep of size dt.
void unsteady_newton_solve (const double &dt)
void unsteady_newton_solve (const double &dt, const bool &shift_values)
void unsteady_newton_solve (const double &dt, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const bool &first, const bool &shift=true)
double doubly_adaptive_unsteady_newton_solve (const double &dt, const double &epsilon, const unsigned &max_adapt, const unsigned &suppress_resolve_after_spatial_adapt_flag, const bool &first, const bool &shift=true)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon)
double adaptive_unsteady_newton_solve (const double &dt_desired, const double &epsilon, const bool &shift_values)
void assign_initial_values_impulsive ()
void assign_initial_values_impulsive (const double &dt)
void calculate_predictions ()
Calculate predictions.
void enable_mass_matrix_reuse ()
void disable_mass_matrix_reuse ()
bool mass_matrix_reuse_is_enabled ()
Return whether the mass matrix is being reused.
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void refine_uniformly (DocInfo &doc_info)
void refine_uniformly_and_prune (DocInfo &doc_info)
void refine_uniformly ()
void refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform refinement for submesh i_mesh with documentation.
void refine_uniformly (const unsigned &i_mesh)
Do uniform refinement for submesh i_mesh without documentation.
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh)
void p_refine_uniformly_and_prune (const Vector< unsigned > &nrefine_for_mesh, DocInfo &doc_info)
void p_refine_uniformly (DocInfo &doc_info)
void p_refine_uniformly_and_prune (DocInfo &doc_info)
void p_refine_uniformly ()
void p_refine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-refinement for submesh i_mesh with documentation.
void p_refine_uniformly (const unsigned &i_mesh)
Do uniform p-refinement for submesh i_mesh without documentation.
void refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void refine_selected_elements (const unsigned &i_mesh, const Vector< RefineableElement * > &elements_to_be_refined_pt)
void refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void refine_selected_elements (const Vector< Vector< RefineableElement * >> &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< unsigned > &elements_to_be_refined)
void p_refine_selected_elements (const unsigned &i_mesh, const Vector< PRefineableElement * > &elements_to_be_refined_pt)
void p_refine_selected_elements (const Vector< Vector< unsigned >> &elements_to_be_refined)
void p_refine_selected_elements (const Vector< Vector< PRefineableElement * >> &elements_to_be_refined_pt)
unsigned unrefine_uniformly ()
unsigned unrefine_uniformly (const unsigned &i_mesh)
void p_unrefine_uniformly (DocInfo &doc_info)
void p_unrefine_uniformly (const unsigned &i_mesh, DocInfo &doc_info)
Do uniform p-unrefinement for submesh i_mesh without documentation.
void adapt (unsigned &n_refined, unsigned &n_unrefined)
void adapt ()
void p_adapt (unsigned &n_refined, unsigned &n_unrefined)
void p_adapt ()
void adapt_based_on_error_estimates (unsigned &n_refined, unsigned &n_unrefined, Vector< Vector< double >> &elemental_error)
void adapt_based_on_error_estimates (Vector< Vector< double >> &elemental_error)
void get_all_error_estimates (Vector< Vector< double >> &elemental_error)
void doc_errors (DocInfo &doc_info)
Get max and min error for all elements in submeshes.
void doc_errors ()
Get max and min error for all elements in submeshes.
void enable_info_in_newton_solve ()
void disable_info_in_newton_solve ()
Disable the output of information when in the newton solver.
Public Member Functions inherited from oomph::ExplicitTimeSteppableObject
ExplicitTimeSteppableObject ()
Empty constructor.
ExplicitTimeSteppableObject (const ExplicitTimeSteppableObject &)=delete
Broken copy constructor.
void operator= (const ExplicitTimeSteppableObject &)=delete
Broken assignment operator.
virtual ~ExplicitTimeSteppableObject ()
Empty destructor.
virtual void actions_before_explicit_stage ()
virtual void actions_after_explicit_stage ()
Public Attributes
HorizontalSingleLayerSpineMesh< ELEMENT > * Bulk_mesh_pt
Access function for the specific mesh.
Mesh * Interface_mesh_pt
Mesh for the free surface (interface) elements.
SingleLayerSpineMesh< ELEMENT > * Bulk_mesh_pt
Access function for the specific mesh.
Mesh * Surface_mesh_pt
Mesh for the interface elements.
MyHorizontalSingleLayerSpineMesh< ELEMENT > * Bulk_mesh_pt
Access function for the specific mesh.
ElasticRectangularQuadMesh< ELEMENT > * Bulk_mesh_pt
Access function for the specific mesh.
Public Attributes inherited from oomph::Problem
bool Shut_up_in_newton_solve
Private Member Functions
void deform_free_surface (const double &epsilon)
Deform the mesh/free surface to a prescribed function.
void deform_free_surface (const double &epsilon, const double &k)
Deform the mesh/free surface to a prescribed function.
void actions_before_newton_solve ()
No actions required before solve step.
void actions_after_newton_solve ()
No actions required after solve step.
void actions_before_implicit_timestep ()
void actions_before_adapt ()
Strip off the interface elements before adapting the bulk mesh.
void actions_after_adapt ()
Rebuild the mesh of interface elements after adapting the bulk mesh.
void create_interface_elements ()
Create the 1d interface elements.
void delete_interface_elements ()
Delete the 1d interface elements.
void deform_free_surface (const double &epsilon, const double &k)
Deform the mesh/free surface to a prescribed function.
void fix_pressure (const unsigned &e, const unsigned &pdof, const double &pvalue)
Fix pressure in element e at pressure dof pdof and set to pvalue.
void actions_before_newton_convergence_check ()
void actions_before_newton_solve ()
No actions required before solve step.
void actions_after_newton_solve ()
void deform_free_surface (const double &epsilon, const double &k)
Deform the mesh/free surface to a prescribed function.
void fix_pressure (const unsigned &e, const unsigned &pdof, const double &pvalue)
Fix pressure in element e at pressure dof pdof and set to pvalue.
void deform_free_surface (const double &epsilon)
Deform the mesh/free surface to a prescribed function.
void deform_free_surface (const double &epsilon)
Deform the mesh/free surface to a prescribed function.
void actions_before_newton_solve ()
No actions required before solve step.
void actions_after_newton_solve ()
No actions required after solve step.
void actions_before_implicit_timestep ()
void deform_free_surface (const double &epsilon, const unsigned &n_periods)
Deform the mesh/free surface to a prescribed function.
void actions_before_newton_convergence_check ()
void actions_before_newton_solve ()
No actions required before solve step.
void actions_after_newton_solve ()
void deform_free_surface (const double &epsilon, const unsigned &n_periods)
Deform the mesh/free surface to a prescribed function.
void actions_before_newton_solve ()
No actions required before solve step.
void actions_after_newton_solve ()
No actions required after solve step.
void actions_before_implicit_timestep ()
void actions_before_adapt ()
Strip off the interface elements before adapting the bulk mesh.
void actions_after_adapt ()
Rebuild the mesh of interface elements after adapting the bulk mesh.
void create_interface_elements ()
Create the 1d interface elements.
void delete_interface_elements ()
Delete the 1d interface elements.
void deform_free_surface (const double &epsilon, const unsigned &n_periods)
Deform the mesh/free surface to a prescribed function.
void fix_pressure (const unsigned &e, const unsigned &pdof, const double &pvalue)
Fix pressure in element e at pressure dof pdof and set to pvalue.
void actions_before_newton_convergence_check ()
void actions_before_newton_solve ()
No actions required before solve step.
void actions_after_newton_solve ()
void deform_free_surface (const double &epsilon, const unsigned &n_periods)
Deform the mesh/free surface to a prescribed function.
void fix_pressure (const unsigned &e, const unsigned &pdof, const double &pvalue)
Fix pressure in element e at pressure dof pdof and set to pvalue.
Private Attributes
ofstream Trace_file
Trace file.
double Lr
Width of domain.
double Height
Height of the domain.
ElasticRefineableTwoLayerMesh< ELEMENT > * Bulk_mesh_pt
Pointer to the (specific) "bulk" mesh.
ConstitutiveLaw * Constitutive_law_pt
Pointer to the constitutive law.
TwoLayerSpineMesh< ELEMENT > * Bulk_mesh_pt
Pointer to the specific bulk mesh.
double R_max
Axial lengths of domain.
double L_y
AnnularSpineMesh< ELEMENT > * Bulk_mesh_pt
Pointer to bulk mesh.
Node * Document_node_pt
Pointer to a node for documentation purposes.
double Lx
Width of domain.
double Ly
SingleLayerCubicSpineMesh< ELEMENT > * Bulk_mesh_pt
Pointer to bulk mesh.
Additional Inherited Members
Public Types inherited from oomph::Problem
typedef void(* SpatialErrorEstimatorFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error)
Function pointer for spatial error estimator.
typedef void(* SpatialErrorEstimatorWithDocFctPt) (Mesh *&mesh_pt, Vector< double > &elemental_error, DocInfo &doc_info)
Function pointer for spatial error estimator with doc.
Static Public Attributes inherited from oomph::Problem
static bool Suppress_warning_about_actions_before_read_unstructured_meshes
Protected Types inherited from oomph::Problem
enum Assembly_method {
Perform_assembly_using_vectors_of_pairs , Perform_assembly_using_two_vectors , Perform_assembly_using_maps , Perform_assembly_using_lists ,
Perform_assembly_using_two_arrays
}
Enumerated flags to determine which sparse assembly method is used.
Protected Member Functions inherited from oomph::Problem
unsigned setup_element_count_per_dof ()
virtual void sparse_assemble_row_or_column_compressed (Vector< int * > &column_or_row_index, Vector< int * > &row_or_column_start, Vector< double * > &value, Vector< unsigned > &nnz, Vector< double * > &residual, bool compressed_row_flag)
virtual void actions_before_newton_step ()
virtual void actions_after_newton_step ()
virtual void actions_after_implicit_timestep ()
virtual void actions_after_implicit_timestep_and_error_estimation ()
virtual void actions_before_explicit_timestep ()
Actions that should be performed before each explicit time step.
virtual void actions_after_explicit_timestep ()
Actions that should be performed after each explicit time step.
virtual void actions_before_read_unstructured_meshes ()
virtual void actions_after_read_unstructured_meshes ()
virtual void actions_after_change_in_global_parameter (double *const &parameter_pt)
virtual void actions_after_change_in_bifurcation_parameter ()
virtual void actions_after_parameter_increase (double *const &parameter_pt)
double & dof_derivative (const unsigned &i)
double & dof_current (const unsigned &i)
unsigned newton_solve_continuation (double *const &parameter_pt)
unsigned newton_solve_continuation (double *const &parameter_pt, DoubleVector &z)
void calculate_continuation_derivatives (double *const &parameter_pt)
void calculate_continuation_derivatives (const DoubleVector &z)
void calculate_continuation_derivatives_fd (double *const &parameter_pt)
bool does_pointer_correspond_to_problem_data (double *const &parameter_pt)
void set_consistent_pinned_values_for_continuation ()
Protected Attributes inherited from oomph::Problem
Vector< Problem * > Copy_of_problem_pt
std::map< double *, bool > Calculate_dparameter_analytic
bool Calculate_hessian_products_analytic
LinearAlgebraDistribution * Dof_distribution_pt
Vector< double * > Dof_pt
Vector of pointers to dofs.
DoubleVectorWithHaloEntries Element_count_per_dof
double Relaxation_factor
double Newton_solver_tolerance
unsigned Max_newton_iterations
Maximum number of Newton iterations.
unsigned Nnewton_iter_taken
Vector< double > Max_res
Maximum residuals at start and after each newton iteration.
double Max_residuals
bool Time_adaptive_newton_crash_on_solve_fail
bool Jacobian_reuse_is_enabled
Is re-use of Jacobian in Newton iteration enabled? Default: false.
bool Jacobian_has_been_computed
bool Problem_is_nonlinear
bool Pause_at_end_of_sparse_assembly
bool Doc_time_in_distribute
unsigned Sparse_assembly_method
unsigned Sparse_assemble_with_arrays_initial_allocation
unsigned Sparse_assemble_with_arrays_allocation_increment
Vector< Vector< unsigned > > Sparse_assemble_with_arrays_previous_allocation
double Numerical_zero_for_sparse_assembly
double FD_step_used_in_get_hessian_vector_products
bool Mass_matrix_reuse_is_enabled
bool Mass_matrix_has_been_computed
bool Discontinuous_element_formulation
double Minimum_dt
Minimum desired dt: if dt falls below this value, exit.
double Maximum_dt
Maximum desired dt.
double DTSF_max_increase
double DTSF_min_decrease
double Minimum_dt_but_still_proceed
bool Scale_arc_length
Boolean to control whether arc-length should be scaled.
double Desired_proportion_of_arc_length
Proportion of the arc-length to taken by the parameter.
double Theta_squared
int Sign_of_jacobian
Storage for the sign of the global Jacobian.
double Continuation_direction
double Parameter_derivative
Storage for the derivative of the global parameter wrt arc-length.
double Parameter_current
Storage for the present value of the global parameter.
bool Use_continuation_timestepper
Boolean to control original or new storage of dof stuff.
unsigned Dof_derivative_offset
unsigned Dof_current_offset
Vector< double > Dof_derivative
Storage for the derivative of the problem variables wrt arc-length.
Vector< double > Dof_current
Storage for the present values of the variables.
double Ds_current
Storage for the current step value.
unsigned Desired_newton_iterations_ds
double Minimum_ds
Minimum desired value of arc-length.
bool Bifurcation_detection
Boolean to control bifurcation detection via determinant of Jacobian.
bool Bisect_to_find_bifurcation
Boolean to control wheter bisection is used to located bifurcation.
bool First_jacobian_sign_change
Boolean to indicate whether a sign change has occured in the Jacobian.
bool Arc_length_step_taken
Boolean to indicate whether an arc-length step has been taken.
bool Use_finite_differences_for_continuation_derivatives
OomphCommunicator * Communicator_pt
The communicator for this problem.
bool Always_take_one_newton_step
double Timestep_reduction_factor_after_nonconvergence
bool Keep_temporal_error_below_tolerance
Static Protected Attributes inherited from oomph::Problem
static ContinuationStorageScheme Continuation_time_stepper
Storage for the single static continuation timestorage object.
Detailed Description
template<class ELEMENT, class TIMESTEPPER>
class InterfaceProblem< ELEMENT, TIMESTEPPER >
Single axisymmetric fluid interface problem in rectangular domain.
Single fluid interface problem.
Axisymmetric two fluid interface problem in a rectangular domain.
/////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////
Single fluid interface problem including transport of an insoluble surfactant.
Single axisymmetric fluid interface problem including the transport of an insoluble surfactant.
Single axisymmetric fluid interface problem including the transport of an soluble surfactant.
/////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////// Single fluid free surface problem in a rectangular domain which is periodic in the x direction
/////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////// Two fluid interface problem in a rectangular domain which is periodic in the x direction
Constructor & Destructor Documentation
InterfaceProblem() [1/12]
template<class ELEMENT , class TIMESTEPPER > InterfaceProblem< ELEMENT, TIMESTEPPER >::InterfaceProblem (const unsigned & n_r, const unsigned & n_z, const double & l_r, const double & h)
Constructor for single fluid interface problem.
Constructor for single fluid free surface problem.
Constructor: Pass the number of elements and the lengths of the domain in the r and z directions (h is the height of the fluid layer i.e. the length of the domain in the z direction)
                                   : Lr(l_r),
                                     Height(h)
 {
  // Allocate the timestepper (this constructs the time object as well)
  add_time_stepper_pt(new TIMESTEPPER);
  // Build and assign mesh (the "false" boolean flag tells the mesh
  // constructor that the domain is not periodic in r)
  Bulk_mesh_pt =
   new HorizontalSingleLayerSpineMesh<ELEMENT>(n_r,n_z,l_r,h,time_stepper_pt());
  //Create "surface mesh" that will only contain the interface elements
  Interface_mesh_pt = new Mesh;
  {
   // How many bulk elements are adjacent to boundary b?
   unsigned n_element = Bulk_mesh_pt->nboundary_element(1);
   // Loop over the bulk elements adjacent to boundary b?
   for(unsigned e=0;e<n_element;e++)
    {
     // Get pointer to the bulk element that is adjacent to boundary b
     ELEMENT* bulk_elem_pt = dynamic_cast<ELEMENT*>(
      Bulk_mesh_pt->boundary_element_pt(1,e));
     // Find the index of the face of element e along boundary b
     int face_index = Bulk_mesh_pt->face_index_at_boundary(1,e);
     // Build the corresponding free surface element
     SpineAxisymmetricFluidInterfaceElement<ELEMENT>* interface_element_pt = new
      SpineAxisymmetricFluidInterfaceElement<ELEMENT>(bulk_elem_pt,face_index);
     //Add the prescribed-flux element to the surface mesh
     Interface_mesh_pt->add_element_pt(interface_element_pt);
    } //end of loop over bulk elements adjacent to boundary b
  }
  // Add the two sub meshes to the problem
  add_sub_mesh(Bulk_mesh_pt);
  add_sub_mesh(Interface_mesh_pt);
  // Combine all submeshes into a single Mesh
  build_global_mesh();
  // --------------------------------------------
  // Set the boundary conditions for this problem
  // --------------------------------------------
  // All nodes are free by default -- just pin the ones that have
  // Dirichlet conditions here
  // Determine number of mesh boundaries
  const unsigned n_boundary = Bulk_mesh_pt->nboundary();
  // Loop over mesh boundaries
  for(unsigned b=0;b<n_boundary;b++)
   {
    // Determine number of nodes on boundary b
    const unsigned n_node = Bulk_mesh_pt->nboundary_node(b);
    // Loop over nodes on boundary b
    for(unsigned n=0;n<n_node;n++)
     {
      // Pin azimuthal velocity on bounds
      Bulk_mesh_pt->boundary_node_pt(b,n)->pin(2);
      // Pin radial velocity on axis of symmetry
      if(b==3)
       {
        Bulk_mesh_pt->boundary_node_pt(b,n)->pin(0);
       }
      // Pin axial velocity on bottom and top walls (no penetration)
      if(b==0 || b==2)
       {
        Bulk_mesh_pt->boundary_node_pt(b,n)->pin(1);
       }
     } // End of loop over nodes on boundary b
   } // End of loop over mesh boundaries
  // ----------------------------------------------------------------
  // Complete the problem setup to make the elements fully functional
  // ----------------------------------------------------------------
  // Determine number of bulk elements in mesh
  const unsigned n_bulk = Bulk_mesh_pt->nelement();
  // Loop over the bulk elements
  for(unsigned e=0;e<n_bulk;e++)
   {
    // Upcast from GeneralisedElement to the present element
    ELEMENT *el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(e));
    // Set the Reynolds number
    el_pt->re_pt() = &Global_Physical_Variables::Re;
    // Set the Womersley number
    el_pt->re_st_pt() = &Global_Physical_Variables::ReSt;
    // Set the product of the Reynolds number and the inverse of the
    // Froude number
    el_pt->re_invfr_pt() = &Global_Physical_Variables::ReInvFr;
    // Set the direction of gravity
    el_pt->g_pt() = &Global_Physical_Variables::G;
   } // End of loop over bulk elements
  // Create a Data object whose single value stores the external pressure
  Data* external_pressure_data_pt = new Data(1);
  // Pin and set the external pressure to some arbitrary value
  double p_ext = Global_Physical_Variables::P_ext;
  external_pressure_data_pt->pin(0);
  external_pressure_data_pt->set_value(0,p_ext);
  // Determine number of 1D interface elements in mesh
  const unsigned n_interface_element = Interface_mesh_pt->nelement();
  // Loop over the interface elements
  for(unsigned e=0;e<n_interface_element;e++)
   {
    // Upcast from GeneralisedElement to the present element
    SpineAxisymmetricFluidInterfaceElement<ELEMENT>* el_pt =
     dynamic_cast<SpineAxisymmetricFluidInterfaceElement<ELEMENT>*>
     (Interface_mesh_pt->element_pt(e));
    // Set the Capillary number
    el_pt->ca_pt() = &Global_Physical_Variables::Ca;
    // Pass the Data item that contains the single external pressure value
    el_pt->set_external_pressure_data(external_pressure_data_pt);
   } // End of loop over interface elements
  // Setup equation numbering scheme
  cout << "Number of equations: " << assign_eqn_numbers() << std::endl;
 } // End of constructor
References oomph::Mesh::add_element_pt(), oomph::Problem::add_sub_mesh(), oomph::Problem::add_time_stepper_pt(), oomph::Problem::assign_eqn_numbers(), b, oomph::Problem::build_global_mesh(), InterfaceProblem< ELEMENT, TIMESTEPPER >::Bulk_mesh_pt, Global_Physical_Variables::Ca, oomph::FluidInterfaceElement::ca_pt(), e(), oomph::Mesh::element_pt(), Global_Physical_Variables::G, InterfaceProblem< ELEMENT, TIMESTEPPER >::Interface_mesh_pt, n, oomph::Mesh::nelement(), Global_Physical_Variables::P_ext, oomph::Data::pin(), Global_Physical_Variables::Re, Global_Physical_Variables::ReInvFr, Global_Physical_Variables::ReSt, oomph::FluidInterfaceElement::set_external_pressure_data(), oomph::Data::set_value(), and oomph::Problem::time_stepper_pt().
~InterfaceProblem() [1/10]
template<class ELEMENT , class TIMESTEPPER > InterfaceProblem< ELEMENT, TIMESTEPPER >::~InterfaceProblem () inline
Destructor (empty)
 {}
InterfaceProblem() [2/12]
template<class ELEMENT , class TIMESTEPPER > InterfaceProblem< ELEMENT, TIMESTEPPER >::InterfaceProblem (const unsigned & n_r, const unsigned & n_z, const double & l_r, const double & h)
Constructor: Pass the number of elements and the lengths of the domain in the r and z directions (h is the height of the fluid layer i.e. the length of the domain in the z direction)
~InterfaceProblem() [2/10]
template<class ELEMENT , class TIMESTEPPER > InterfaceProblem< ELEMENT, TIMESTEPPER >::~InterfaceProblem () inline
Destructor (empty)
 {}
InterfaceProblem() [3/12]
template<class ELEMENT , class TIMESTEPPER > InterfaceProblem< ELEMENT, TIMESTEPPER >::InterfaceProblem
Constructor.
Constructor for two fluid interface problem.
Constructor for axisymmetric two fluid interface problem.
 {
  // Allocate the timestepper (this constructs the time object as well)
  add_time_stepper_pt(new TIMESTEPPER);
  // Define number of elements in r direction
  const unsigned n_r = 3;
  // Define number of elements in z direction in lower fluid (fluid 1)
  const unsigned n_z1 = 3;
  // Define number of elements in z direction in upper fluid (fluid 2)
  const unsigned n_z2 = 3;
  // Define width of domain and store as class member data
  const double l_r = 1.0;
  this->Lr = l_r;
  // Define height of lower fluid layer
  const double h1 = 1.0;
  // Define height of upper fluid layer
  const double h2 = 1.0;
  // Build and assign the "bulk" mesh
  Bulk_mesh_pt = new ElasticRefineableTwoLayerMesh<ELEMENT>
   (n_r,n_z1,n_z2,l_r,h1,h2,time_stepper_pt());
  // Create and set the error estimator for spatial adaptivity
  Bulk_mesh_pt->spatial_error_estimator_pt() = new Z2ErrorEstimator;
  // Set the maximum refinement level for the mesh to 4
  Bulk_mesh_pt->max_refinement_level() = 4;
  // Create the "surface" mesh that will contain only the interface
  // elements. The constructor just creates the mesh without giving
  // it any elements, nodes, etc.
  Surface_mesh_pt = new Mesh;
  // Create interface elements at the boundary between the two fluids,
  // and add them to the surface mesh
  create_interface_elements();
  // Add the two sub meshes to the problem
  add_sub_mesh(Bulk_mesh_pt);
  add_sub_mesh(Surface_mesh_pt);
  // Combine all sub-meshes into a single mesh
  build_global_mesh();
  // --------------------------------------------
  // Set the boundary conditions for this problem
  // --------------------------------------------
  // All nodes are free by default -- just pin the ones that have
  // Dirichlet conditions here
  // Determine number of mesh boundaries
  const unsigned n_boundary = Bulk_mesh_pt->nboundary();
  // Loop over mesh boundaries
  for(unsigned b=0;b<n_boundary;b++)
   {
    // Determine number of nodes on boundary b
    const unsigned n_node = Bulk_mesh_pt->nboundary_node(b);
    // Loop over nodes on boundary b
    for(unsigned n=0;n<n_node;n++)
     {
      // Fluid boundary conditions:
      // --------------------------
      // Pin radial and azimuthal velocities (no slip/penetration)
      // on all boundaries other than the interface (b=4)
      if(b!=4)
       {
        Bulk_mesh_pt->boundary_node_pt(b,n)->pin(0);
        Bulk_mesh_pt->boundary_node_pt(b,n)->pin(2);
       }
      // Pin axial velocity on top (b=2) and bottom (b=0) boundaries
      // (no penetration). Because we have a slippery outer wall we do
      // NOT pin the axial velocity on this boundary (b=1); similarly,
      // we do not pin the axial velocity on the symmetry boundary (b=3).
      if(b==0 || b==2) { Bulk_mesh_pt->boundary_node_pt(b,n)->pin(1); }
      // Solid boundary conditions:
      // --------------------------
      // Pin vertical displacement on solid boundaries
      if(b==0 || b==2) { Bulk_mesh_pt->boundary_node_pt(b,n)->pin_position(1); }
     } // End of loop over nodes on boundary b
   } // End of loop over mesh boundaries
  // Loop over all nodes in mesh
  const unsigned n_node = Bulk_mesh_pt->nnode();
  for(unsigned n=0;n<n_node;n++)
   {
    // Pin horizontal displacement of all nodes
    Bulk_mesh_pt->node_pt(n)->pin_position(0);
    // Pin all azimuthal velocities throughout the bulk of the domain
    Bulk_mesh_pt->node_pt(n)->pin(2);
   }
  // Define a constitutive law for the solid equations: generalised Hookean
  Constitutive_law_pt = new GeneralisedHookean(&Global_Physical_Variables::Nu);
  // ----------------------------------------------------------------
  // Complete the problem setup to make the elements fully functional
  // ----------------------------------------------------------------
  // Compute number of bulk elements in lower/upper fluids
  const unsigned n_lower = n_r*n_z1;
  const unsigned n_upper = n_r*n_z2;
  // Loop over bulk elements in lower fluid
  for(unsigned e=0;e<n_lower;e++)
   {
    // Upcast from GeneralisedElement to the present element
    ELEMENT *el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(e));
    // Set the Reynolds number
    el_pt->re_pt() = &Global_Physical_Variables::Re;
    // Set the Womersley number
    el_pt->re_st_pt() = &Global_Physical_Variables::ReSt;
    // Set the product of the Reynolds number and the inverse of the
    // Froude number
    el_pt->re_invfr_pt() = &Global_Physical_Variables::ReInvFr;
    // Set the direction of gravity
    el_pt->g_pt() = &Global_Physical_Variables::G;
    // Set the constitutive law
    el_pt->constitutive_law_pt() = Constitutive_law_pt;
   } // End of loop over bulk elements in lower fluid
  // Loop over bulk elements in upper fluid
  for(unsigned e=n_lower;e<(n_lower+n_upper);e++)
   {
    // Upcast from GeneralisedElement to the present element
    ELEMENT *el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(e));
    // Set the Reynolds number
    el_pt->re_pt() = &Global_Physical_Variables::Re;
    // Set the Womersley number
    el_pt->re_st_pt() = &Global_Physical_Variables::ReSt;
    // Set the product of the Reynolds number and the inverse of the
    // Froude number
    el_pt->re_invfr_pt() = &Global_Physical_Variables::ReInvFr;
    // Set the direction of gravity
    el_pt->g_pt() = &Global_Physical_Variables::G;
    // Set the viscosity ratio
    el_pt->viscosity_ratio_pt() = &Global_Physical_Variables::Viscosity_Ratio;
    // Set the density ratio
    el_pt->density_ratio_pt() = &Global_Physical_Variables::Density_Ratio;
    // Set the constitutive law
    el_pt->constitutive_law_pt() = Constitutive_law_pt;
   } // End of loop over bulk elements in upper fluid
  // Set the pressure in the first element at 'node' 0 to 0.0
  fix_pressure(0,0,0.0);
  // Pin the redundant solid pressures (if any)
  PVDEquationsBase<2>::pin_redundant_nodal_solid_pressures(
   Bulk_mesh_pt->element_pt());
  // Apply the boundary conditions
  set_boundary_conditions();
  // Set up equation numbering scheme
  cout << "Number of equations: " << assign_eqn_numbers() << std::endl;
 } // End of constructor
References b, Constitutive::Constitutive_law_pt, Global_Physical_Variables::Density_Ratio, e(), Global_Physical_Variables::G, Global_Parameters::Lr, n, Global_Physical_Variables::Nu, Global_Physical_Variables::Re, Global_Physical_Variables::ReInvFr, Global_Physical_Variables::ReSt, and Global_Physical_Variables::Viscosity_Ratio.
~InterfaceProblem() [3/10]
template<class ELEMENT , class TIMESTEPPER > InterfaceProblem< ELEMENT, TIMESTEPPER >::~InterfaceProblem () inline
Destructor (empty)
 {}
InterfaceProblem() [4/12]
template<class ELEMENT , class TIMESTEPPER > InterfaceProblem< ELEMENT, TIMESTEPPER >::InterfaceProblem (const unsigned & n_r, const unsigned & n_z1, const unsigned & n_z2, const double & l_r, const double & h1, const double & h2)
Constructor for axisymmetric two fluid interface problem.
Constructor for two fluid interface problem.
Problem constructor.
Constructor: Pass the number of elements and the width of the domain in the r direction. Also pass the number of elements in the z direction of the bottom (fluid 1) and top (fluid 2) layers, along with the heights of both layers.
                                                      : Lr(l_r)
 {
  // Allocate the timestepper (this constructs the time object as well)
  add_time_stepper_pt(new TIMESTEPPER);
  // Build and assign mesh
  Bulk_mesh_pt = new TwoLayerSpineMesh<ELEMENT>
   (n_r,n_z1,n_z2,l_r,h1,h2,time_stepper_pt());
  Surface_mesh_pt = new Mesh;
  //Loop over the horizontal elements
  for(unsigned i=0;i<n_r;i++)
   {
    //Construct a new 1D line element on the face on which the local
    //coordinate 1 is fixed at its max. value (1) -- Face 2
    FiniteElement *interface_element_pt =  new
     SpineAxisymmetricFluidInterfaceElement<ELEMENT>(
      Bulk_mesh_pt->finite_element_pt(n_r*(n_z1-1)+i),2);
    this->Surface_mesh_pt->add_element_pt(interface_element_pt);
   }
  // --------------------------------------------
  // Set the boundary conditions for this problem
  // --------------------------------------------
  // All nodes are free by default -- just pin the ones that have
  // Dirichlet conditions here
  // Loop over mesh boundaries
  for(unsigned b=0;b<6;b++)
   {
    // Determine number of nodes on boundary b
    const unsigned n_node = Bulk_mesh_pt->nboundary_node(b);
    // Loop over nodes on boundary b
    for (unsigned n=0;n<n_node;n++)
     {
      // Pin radial and azimuthal velocities on all boundaries
      // (no slip/penetration)
      Bulk_mesh_pt->boundary_node_pt(b,n)->pin(0);
      Bulk_mesh_pt->boundary_node_pt(b,n)->pin(2);
      // Pin axial velocity on top (b=3) and bottom (b=0) boundaries
      // (no penetration). Because we have a slippery outer wall we do
      // NOT pin the axial velocity on this boundary (b=1,2); similarly,
      // we do not pin the axial velocity on the symmetry boundary (b=4,5).
      if(b==0 || b==3) { Bulk_mesh_pt->boundary_node_pt(b,n)->pin(1); }
     }
   }
  // Pin all azimuthal velocities throughout the bulk of the domain
  const unsigned n_node = Bulk_mesh_pt->nnode();
  for(unsigned n=0;n<n_node;n++) { Bulk_mesh_pt->node_pt(n)->pin(2); }
  // ----------------------------------------------------------------
  // Complete the problem setup to make the elements fully functional
  // ----------------------------------------------------------------
  // Determine number of bulk elements in lower/upper fluids
  const unsigned n_lower = Bulk_mesh_pt->nlower();
  const unsigned n_upper = Bulk_mesh_pt->nupper();
  // Loop over bulk elements in lower fluid
  for(unsigned e=0;e<n_lower;e++)
   {
    // Upcast from GeneralisedElement to the present element
    ELEMENT *el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->
                                            lower_layer_element_pt(e));
    // Set the Reynolds number
    el_pt->re_pt() = &Global_Physical_Variables::Re;
    // Set the Womersley number
    el_pt->re_st_pt() = &Global_Physical_Variables::ReSt;
    // Set the product of the Reynolds number and the inverse of the
    // Froude number
    el_pt->re_invfr_pt() = &Global_Physical_Variables::ReInvFr;
    // Set the direction of gravity
    el_pt->g_pt() = &Global_Physical_Variables::G;
   } // End of loop over bulk elements in lower fluid
  // Loop over bulk elements in upper fluid
  for(unsigned e=0;e<n_upper;e++)
   {
    // Upcast from GeneralisedElement to the present element
    ELEMENT *el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->
                                            upper_layer_element_pt(e));
    // Set the Reynolds number
    el_pt->re_pt() = &Global_Physical_Variables::Re;
    // Set the Womersley number
    el_pt->re_st_pt() = &Global_Physical_Variables::ReSt;
    // Set the product of the Reynolds number and the inverse of the
    // Froude number
    el_pt->re_invfr_pt() = &Global_Physical_Variables::ReInvFr;
    // Set the viscosity ratio
    el_pt->viscosity_ratio_pt() = &Global_Physical_Variables::Viscosity_Ratio;
    // Set the density ratio
    el_pt->density_ratio_pt() = &Global_Physical_Variables::Density_Ratio;
    // Set the direction of gravity
    el_pt->g_pt() = &Global_Physical_Variables::G;
   } // End of loop over bulk elements in upper fluid
  // Set the pressure in the first element at 'node' 0 to 0.0
  fix_pressure(0,0,0.0);
  // Determine number of 1D interface elements in mesh
  unsigned n_interface_element = Surface_mesh_pt->nelement();
  // Loop over interface elements
  for(unsigned e=0;e<n_interface_element;e++)
   {
    // Upcast from GeneralisedElement to the present element
    SpineAxisymmetricFluidInterfaceElement<ELEMENT>* el_pt =
     dynamic_cast<SpineAxisymmetricFluidInterfaceElement<ELEMENT>*>
     (Surface_mesh_pt->element_pt(e));
    // Set the Strouhal number
    el_pt->ca_pt() = &Global_Physical_Variables::St;
    // Set the Capillary number
    el_pt->ca_pt() = &Global_Physical_Variables::Ca;
   } // End of loop over interface elements
  // Apply the boundary conditions
  set_boundary_conditions();
  this->add_sub_mesh(Bulk_mesh_pt);
  this->add_sub_mesh(Surface_mesh_pt);
  this->build_global_mesh();
  // Setup equation numbering scheme
  cout << "Number of equations: " << assign_eqn_numbers() << std::endl;
 } // End of constructor
References oomph::Mesh::add_element_pt(), oomph::Problem::add_sub_mesh(), oomph::Problem::add_time_stepper_pt(), oomph::Problem::assign_eqn_numbers(), b, oomph::Problem::build_global_mesh(), InterfaceProblem< ELEMENT, TIMESTEPPER >::Bulk_mesh_pt, Global_Physical_Variables::Ca, oomph::FluidInterfaceElement::ca_pt(), Global_Physical_Variables::Density_Ratio, e(), oomph::Mesh::element_pt(), InterfaceProblem< ELEMENT, TIMESTEPPER >::fix_pressure(), Global_Physical_Variables::G, i, n, oomph::Mesh::nelement(), Global_Physical_Variables::Re, Global_Physical_Variables::ReInvFr, Global_Physical_Variables::ReSt, InterfaceProblem< ELEMENT, TIMESTEPPER >::set_boundary_conditions(), Global_Physical_Variables::St, InterfaceProblem< ELEMENT, TIMESTEPPER >::Surface_mesh_pt, oomph::Problem::time_stepper_pt(), and Global_Physical_Variables::Viscosity_Ratio.
~InterfaceProblem() [4/10]
template<class ELEMENT , class TIMESTEPPER > InterfaceProblem< ELEMENT, TIMESTEPPER >::~InterfaceProblem () inline
Destructor (empty)
 {}
InterfaceProblem() [5/12]
template<class ELEMENT , class TIMESTEPPER > InterfaceProblem< ELEMENT, TIMESTEPPER >::InterfaceProblem (const unsigned & n_r, const unsigned & n_y, const unsigned & n_theta, const double & r_min, const double & r_max, const double & l_y, const double & theta_max)
Problem constructor.
Constructor: Pass number of elements in x and y directions. Also lengths of the domain in x- and y-directions and the height of the layer
  : R_max(r_max), L_y(l_y)
 {
  //this->linear_solver_pt() = new HSL_MA42;
  //static_cast<HSL_MA42*>(this->linear_solver_pt())->lenbuf_factor0() = 3.0;
  //static_cast<HSL_MA42*>(this->linear_solver_pt())->lenbuf_factor1() = 3.0;
  //static_cast<HSL_MA42*>(this->linear_solver_pt())->lenbuf_factor2() = 3.0;
  //Allocate the timestepper
  add_time_stepper_pt(new TIMESTEPPER);
  //Now create the bulk mesh -- this should be your new annular mesh
  Bulk_mesh_pt = new AnnularSpineMesh<ELEMENT>
    (n_r,n_y,n_theta,r_min,r_max,l_y,0.0,theta_max,time_stepper_pt());
  //Set the documented node
  Document_node_pt = Bulk_mesh_pt->boundary_node_pt(5,0);
  //Create the surface mesh that will contain the interface elements
  //First create storage, but with no elements or nodes
  Surface_mesh_pt = new Mesh;
  // Loop over those elements adjacent to the free surface,
  // which we shall choose to be the upper surface
  for(unsigned e1=0;e1<n_y;e1++)
   {
    for(unsigned e2=0;e2<n_theta;e2++)
     {
      // Set a pointer to the bulk element we wish to our interface
      // element to
      FiniteElement* bulk_element_pt =
       Bulk_mesh_pt->finite_element_pt(n_theta*n_y*(n_r-1) + e2 + e1*n_theta);
      // Create the interface element (on face 3 of the bulk element)
      FiniteElement* interface_element_pt =
       new SpineSurfaceSurfactantTransportInterfaceElement<ELEMENT>(bulk_element_pt,3);
    // Add the interface element to the surface mesh
    this->Surface_mesh_pt->add_element_pt(interface_element_pt);
     }
   }
  // Add the two sub-meshes to the problem
  add_sub_mesh(Bulk_mesh_pt);
  add_sub_mesh(Surface_mesh_pt);
  // Combine all sub-meshes into a single mesh
  build_global_mesh();
  //Pin all nodes on the bottom
  unsigned long n_boundary_node = Bulk_mesh_pt->nboundary_node(0);
  for(unsigned long n=0;n<n_boundary_node;n++)
   {
    for(unsigned i=0;i<3;i++)
     {
      Bulk_mesh_pt->boundary_node_pt(0,n)->pin(i);
     }
   }
  //On the front and back (y=const) pin in y-direction
  for(unsigned b=1;b<4;b+=2)
   {
    n_boundary_node = Bulk_mesh_pt->nboundary_node(b);
    for(unsigned long n=0;n<n_boundary_node;n++)
     {
      Bulk_mesh_pt->boundary_node_pt(b,n)->pin(1);
     }
   }
  //On sides pin in z-direction
  for(unsigned b=4;b<5;b+=2)
   {
    n_boundary_node = Bulk_mesh_pt->nboundary_node(b);
    for(unsigned long n=0;n<n_boundary_node;n++)
     {
      Bulk_mesh_pt->boundary_node_pt(b,n)->pin(2);
     }
   }
  // pinning the top surface
  for(unsigned b=2;b<3;b++)
   {
    n_boundary_node = Bulk_mesh_pt->nboundary_node(b);
    for(unsigned long n=0;n<n_boundary_node;n++)
     {
      Bulk_mesh_pt->boundary_node_pt(b,n)->pin(0);
     }
   }
  //Loop over the upper surface and set the surface concentration
  {
   unsigned b=5;
   n_boundary_node = Bulk_mesh_pt->nboundary_node(b);
   for(unsigned long n=0;n<n_boundary_node;n++)
    {
     Bulk_mesh_pt->boundary_node_pt(b,n)->set_value(3,1.0);;
    }
  }
  //Create a Data object whose single value stores the
  //external pressure
  Data* external_pressure_data_pt = new Data(1);
  // Set and pin the external pressure to some random value
  external_pressure_data_pt->set_value(0,1.31);
  external_pressure_data_pt->pin(0);
  //Complete the problem setup to make the elements fully functional
  //Loop over the elements in the layer
  unsigned n_bulk=Bulk_mesh_pt->nelement();
  for(unsigned e=0;e<n_bulk;e++)
   {
    //Cast to a fluid element
    ELEMENT *el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(e));
    //Set the Reynolds number, etc
    el_pt->re_pt() = &Global_Physical_Variables::Re;
    el_pt->re_st_pt() = &Global_Physical_Variables::ReSt;
    el_pt->re_invfr_pt() = &Global_Physical_Variables::ReInvFr;
    el_pt->g_pt() = &Global_Physical_Variables::G;
   }
  //Loop over 2D interface elements and set capillary number and
  //the external pressure
  unsigned long interface_element_pt_range =
   Surface_mesh_pt->nelement();
  for(unsigned e=0;e<interface_element_pt_range;e++)
   {
    //Cast to a interface element
    SpineSurfaceSurfactantTransportInterfaceElement<ELEMENT>* el_pt =
     dynamic_cast<SpineSurfaceSurfactantTransportInterfaceElement<ELEMENT>*>
     (Surface_mesh_pt->element_pt(e));
    //Set the Capillary number
    el_pt->ca_pt() = &Global_Physical_Variables::Ca;
    //Pass the Data item that contains the single external pressure value
    el_pt->set_external_pressure_data(external_pressure_data_pt);
    // Set the surface elasticity number
    el_pt->beta_pt() = &Global_Physical_Variables::Beta;
    // Set the surface peclect number
    el_pt->peclet_s_pt() = &Global_Physical_Variables::Peclet_S;
    // Set the surface peclect number multiplied by strouhal number
    el_pt->peclet_strouhal_s_pt() = &Global_Physical_Variables::Peclet_St_S;
   }
  //Do equation numbering
  cout << assign_eqn_numbers() << std::endl;
  //Now sort the elements to minimise frontwidth
  std::sort(mesh_pt()->element_pt().begin(),
            mesh_pt()->element_pt().end(),
            ElementCmp());
 }
References oomph::Mesh::add_element_pt(), oomph::Problem::add_sub_mesh(), oomph::Problem::add_time_stepper_pt(), oomph::Problem::assign_eqn_numbers(), b, Global_Physical_Variables::Beta, oomph::SurfactantTransportInterfaceElement::beta_pt(), oomph::Problem::build_global_mesh(), InterfaceProblem< ELEMENT, TIMESTEPPER >::Bulk_mesh_pt, Global_Physical_Variables::Ca, oomph::FluidInterfaceElement::ca_pt(), InterfaceProblem< ELEMENT, TIMESTEPPER >::Document_node_pt, e(), oomph::Mesh::element_pt(), Eigen::placeholders::end, Global_Physical_Variables::G, i, oomph::Problem::mesh_pt(), n, oomph::Mesh::nelement(), Global_Physical_Variables::Peclet_S, oomph::SurfactantTransportInterfaceElement::peclet_s_pt(), Global_Physical_Variables::Peclet_St_S, oomph::SurfactantTransportInterfaceElement::peclet_strouhal_s_pt(), oomph::Data::pin(), BiharmonicTestFunctions2::r_max, BiharmonicTestFunctions2::r_min, Global_Physical_Variables::Re, Global_Physical_Variables::ReInvFr, Global_Physical_Variables::ReSt, oomph::FluidInterfaceElement::set_external_pressure_data(), oomph::Data::set_value(), InterfaceProblem< ELEMENT, TIMESTEPPER >::Surface_mesh_pt, and oomph::Problem::time_stepper_pt().
InterfaceProblem() [6/12]
template<class ELEMENT , class TIMESTEPPER > InterfaceProblem< ELEMENT, TIMESTEPPER >::InterfaceProblem (const unsigned & n_r, const unsigned & n_z, const double & l_z)
Constructor for single fluid interface problem.
Constructor: Pass the number of elements in radial and axial directions and the length of the domain in the z direction)
 {
  // Allocate the timestepper (this constructs the time object as well)
  add_time_stepper_pt(new TIMESTEPPER(true));
  // Build and assign mesh (the "false" boolean flag tells the mesh
  // constructor that the domain is not periodic in r)
  Bulk_mesh_pt = new MyHorizontalSingleLayerSpineMesh<ELEMENT>(n_r,n_z,1.0,l_z,time_stepper_pt());
  //Create "surface mesh" that will only contain the interface elements
  Interface_mesh_pt = new Mesh;
  {
   // How many bulk elements are adjacent to boundary b?
    // Boundary 1 is the outer boundary
    // The boundaries are labelled
    //                   2
    //                 3   1
    //                   0
   unsigned n_element = Bulk_mesh_pt->nboundary_element(3);
   // Loop over the bulk elements adjacent to boundary b?
   for(unsigned e=0;e<n_element;e++)
    {
     // Get pointer to the bulk element that is adjacent to boundary b
     ELEMENT* bulk_elem_pt = dynamic_cast<ELEMENT*>(
      Bulk_mesh_pt->boundary_element_pt(3,e));
     // Find the index of the face of element e along boundary b
     int face_index = Bulk_mesh_pt->face_index_at_boundary(3,e);
     // Build the corresponding free surface element
     SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement<ELEMENT>* interface_element_pt = new
       SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement<ELEMENT>(bulk_elem_pt,face_index);
     //Add the prescribed-flux element to the surface mesh
      Interface_mesh_pt->add_element_pt(interface_element_pt);
    } //end of loop over bulk elements adjacent to boundary b
  }
  // Add the two sub meshes to the problem
  add_sub_mesh(Bulk_mesh_pt);
  add_sub_mesh(Interface_mesh_pt);
  // Combine all submeshes into a single Mesh
  build_global_mesh();
  // --------------------------------------------
  // Set the boundary conditions for this problem
  // --------------------------------------------
  //Pin all azimuthal velocities
  {
   unsigned n_node = this->Bulk_mesh_pt->nnode();
   for(unsigned n=0;n<n_node;++n)
    {
     this->Bulk_mesh_pt->node_pt(n)->pin(2);
    }
  }
  // All nodes are free by default -- just pin the ones that have
  // Dirichlet conditions here
  unsigned ibound = 3;
  unsigned n_node = Bulk_mesh_pt->nboundary_node(ibound);
  for(unsigned n=0;n<n_node;n++)
    {
      Bulk_mesh_pt->boundary_node_pt(ibound,n)->set_value(3,1.0);
    }
  // Determine number of mesh boundaries
  const unsigned n_boundary = Bulk_mesh_pt->nboundary();
  // Loop over mesh boundaries
  for(unsigned b=0;b<n_boundary;b++)
   {
    // Determine number of nodes on boundary b
    const unsigned n_node = Bulk_mesh_pt->nboundary_node(b);
    // Loop over nodes on boundary b
    for(unsigned n=0;n<n_node;n++)
     {
      // Pin azimuthal velocity on bounds
      Bulk_mesh_pt->boundary_node_pt(b,n)->pin(2);
      // Pin velocity on the outer wall
      if(b==1)
       {
     Bulk_mesh_pt->boundary_node_pt(b,n)->pin(0);
     Bulk_mesh_pt->boundary_node_pt(b,n)->pin(1);
       }
      // Pin axial velocity on bottom and top walls (no penetration)
      if(b==0 || b==2)
       {
        Bulk_mesh_pt->boundary_node_pt(b,n)->pin(1);
       }
     } // End of loop over nodes on boundary b
   } // End of loop over mesh boundaries
  // ----------------------------------------------------------------
  // Complete the problem setup to make the elements fully functional
  // ----------------------------------------------------------------
  // Determine number of bulk elements in mesh
  const unsigned n_bulk = Bulk_mesh_pt->nelement();
  // Loop over the bulk elements
  for(unsigned e=0;e<n_bulk;e++)
   {
    // Upcast from GeneralisedElement to the present element
    ELEMENT *el_pt = dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(e));
    // Set the Reynolds number
    el_pt->re_pt() = &Global_Physical_Variables::Re;
    // Set the Womersley number
    el_pt->re_st_pt() = &Global_Physical_Variables::ReSt;
    // Set the product of the Reynolds number and the inverse of the
    // Froude number
    el_pt->re_invfr_pt() = &Global_Physical_Variables::ReInvFr;
    // Set the direction of gravity
    el_pt->g_pt() = &Global_Physical_Variables::G;
   } // End of loop over bulk elements
  // Create a Data object whose single value stores the external pressure
  Data* external_pressure_data_pt = new Data(1);
  // Pin and set the external pressure to some arbitrary value
  double p_ext = Global_Physical_Variables::P_ext;
  external_pressure_data_pt->pin(0);
  external_pressure_data_pt->set_value(0,p_ext);
  // Determine number of 1D interface elements in mesh
  const unsigned n_interface_element = Interface_mesh_pt->nelement();
  // Loop over the interface elements
  for(unsigned e=0;e<n_interface_element;e++)
   {
    // Upcast from GeneralisedElement to the present element
    SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement<ELEMENT>* el_pt =
     dynamic_cast<SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement<ELEMENT>*>
     (Interface_mesh_pt->element_pt(e));
    // Set the Capillary number
    el_pt->ca_pt() = &Global_Physical_Variables::Ca;
    // Pass the Data item that contains the single external pressure value
    el_pt->set_external_pressure_data(external_pressure_data_pt);
    // Set the surface elasticity number
    el_pt->beta_pt() = &Global_Physical_Variables::Beta;
    // Set the surface peclect number
    el_pt->peclet_s_pt() = &Global_Physical_Variables::Peclet_S;
    // Set the surface peclect number multiplied by strouhal number
    el_pt->peclet_strouhal_s_pt() = &Global_Physical_Variables::Peclet_St_S;
   } // End of loop over interface elements
  // Setup equation numbering scheme
  cout << "Number of equations: " << assign_eqn_numbers() << std::endl;
 } // End of constructor
References b, Global_Physical_Variables::Beta, oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::beta_pt(), oomph::Global_Physical_Variables::Ca, oomph::FluidInterfaceElement::ca_pt(), e(), Global_Physical_Variables::G, n, oomph::Mesh::nboundary_element(), Global_Physical_Variables::P_ext, Global_Physical_Variables::Peclet_S, oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::peclet_s_pt(), Global_Physical_Variables::Peclet_St_S, oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::peclet_strouhal_s_pt(), oomph::Data::pin(), oomph::Global_Physical_Variables::Re, oomph::Global_Physical_Variables::ReInvFr, Global_Physical_Variables::ReSt, oomph::FluidInterfaceElement::set_external_pressure_data(), and oomph::Data::set_value().
~InterfaceProblem() [5/10]
template<class ELEMENT , class TIMESTEPPER > InterfaceProblem< ELEMENT, TIMESTEPPER >::~InterfaceProblem () inline
Destructor (empty)
 {}
InterfaceProblem() [7/12]
template<class ELEMENT , class TIMESTEPPER > InterfaceProblem< ELEMENT, TIMESTEPPER >::InterfaceProblem (const unsigned & n_r, const unsigned & n_z, const double & l_z)
Constructor: Pass the number of elements in radial and axial directions and the length of the domain in the z direction)
~InterfaceProblem() [6/10]
template<class ELEMENT , class TIMESTEPPER > InterfaceProblem< ELEMENT, TIMESTEPPER >::~InterfaceProblem () inline
Destructor (empty)
 {}
InterfaceProblem() [8/12]
template<class ELEMENT , class TIMESTEPPER > InterfaceProblem< ELEMENT, TIMESTEPPER >::InterfaceProblem (const unsigned & n_x, const unsigned & n_y, const double & l_x, const double & h)
Constructor: Pass the number of elements and the lengths of the domain in the x and y directions (h is the height of the fluid layer i.e. the length of the domain in the y direction)
~InterfaceProblem() [7/10]
template<class ELEMENT , class TIMESTEPPER > InterfaceProblem< ELEMENT, TIMESTEPPER >::~InterfaceProblem () inline
Destructor (empty)
 {}
InterfaceProblem() [9/12]
template<class ELEMENT , class TIMESTEPPER > InterfaceProblem< ELEMENT, TIMESTEPPER >::InterfaceProblem (const unsigned & n_x, const unsigned & n_y, const double & l_x, const double & h)
Constructor: Pass the number of elements and the lengths of the domain in the x and y directions (h is the height of the fluid layer i.e. the length of the domain in the y direction)
~InterfaceProblem() [8/10]
template<class ELEMENT , class TIMESTEPPER > InterfaceProblem< ELEMENT, TIMESTEPPER >::~InterfaceProblem () inline
Destructor (empty)
 {}
InterfaceProblem() [10/12]
template<class ELEMENT , class TIMESTEPPER > InterfaceProblem< ELEMENT, TIMESTEPPER >::InterfaceProblem (const unsigned & Nx, const unsigned & Ny, const unsigned & Nz, const double & Lx, const double & Ly, const double & h)
Constructor: Pass number of elements in x and y directions. Also lengths of the domain in x- and y-directions and the height of the layer
InterfaceProblem() [11/12]
template<class ELEMENT , class TIMESTEPPER > InterfaceProblem< ELEMENT, TIMESTEPPER >::InterfaceProblem ()
Constructor.
~InterfaceProblem() [9/10]
template<class ELEMENT , class TIMESTEPPER > InterfaceProblem< ELEMENT, TIMESTEPPER >::~InterfaceProblem () inline
Destructor (empty)
 {}
InterfaceProblem() [12/12]
template<class ELEMENT , class TIMESTEPPER > InterfaceProblem< ELEMENT, TIMESTEPPER >::InterfaceProblem (const unsigned & n_x, const unsigned & n_y1, const unsigned & n_y2, const double & l_x, const double & h1, const double & h2)
Constructor: Pass the number of elements and the width of the domain in the x direction. Also pass the number of elements in the y direction of the bottom (fluid 1) and top (fluid 2) layers, along with the heights of both layers.
~InterfaceProblem() [10/10]
template<class ELEMENT , class TIMESTEPPER > InterfaceProblem< ELEMENT, TIMESTEPPER >::~InterfaceProblem () inline
Destructor (empty)
 {}
Member Function Documentation
actions_after_adapt() [1/2]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::actions_after_adapt private virtual
Rebuild the mesh of interface elements after adapting the bulk mesh.
Reimplemented from oomph::Problem.
 {
  // Create the interface elements
  this->create_interface_elements();
  // Rebuild the Problem's global mesh from its various sub-meshes
  rebuild_global_mesh();
  // Pin horizontal displacement of all nodes
  const unsigned n_node = Bulk_mesh_pt->nnode();
  for(unsigned n=0;n<n_node;n++) { Bulk_mesh_pt->node_pt(n)->pin_position(0); }
  // Unpin all fluid pressure dofs
  RefineableAxisymmetricNavierStokesEquations::
   unpin_all_pressure_dofs(Bulk_mesh_pt->element_pt());
  // Pin redudant fluid pressure dofs
  RefineableAxisymmetricNavierStokesEquations::
   pin_redundant_nodal_pressures(Bulk_mesh_pt->element_pt());
  // Now set the pressure in the first element at 'node' 0 to 0.0
  fix_pressure(0,0,0.0);
  // Pin the redundant solid pressures (if any)
  PVDEquationsBase<2>::pin_redundant_nodal_solid_pressures(
   Bulk_mesh_pt->element_pt());
  // Reset the boundary conditions
  set_boundary_conditions();
 } // End of actions_after_adapt
References n.
actions_after_adapt() [2/2]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::actions_after_adapt () private virtual
Rebuild the mesh of interface elements after adapting the bulk mesh.
Reimplemented from oomph::Problem.
actions_after_newton_solve() [1/8]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::actions_after_newton_solve () inline virtual
Update after solve can remain empty, because the update is performed automatically after every Newton step.
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [2/8]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::actions_after_newton_solve () inline virtual
Update after solve can remain empty, because the update is performed automatically after every Newton step.
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [3/8]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::actions_after_newton_solve () inline private virtual
No actions required after solve step.
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [4/8]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::actions_after_newton_solve () inline private virtual
Update after solve can remain empty, because the update is performed automatically after every Newton step.
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [5/8]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::actions_after_newton_solve () inline private virtual
No actions required after solve step.
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [6/8]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::actions_after_newton_solve () inline private virtual
Update after solve can remain empty, because the update is performed automatically after every Newton step.
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [7/8]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::actions_after_newton_solve () inline private virtual
No actions required after solve step.
Reimplemented from oomph::Problem.
 {}
actions_after_newton_solve() [8/8]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::actions_after_newton_solve () inline private virtual
Update after solve can remain empty, because the update is performed automatically after every Newton step.
Reimplemented from oomph::Problem.
 {}
actions_before_adapt() [1/2]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::actions_before_adapt private virtual
Strip off the interface elements before adapting the bulk mesh.
Reimplemented from oomph::Problem.
 {
  // Delete the interface elements and wipe the surface mesh
  delete_interface_elements();
  // Rebuild the Problem's global mesh from its various sub-meshes
  rebuild_global_mesh();
 } // End of actions_before_adapt
actions_before_adapt() [2/2]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::actions_before_adapt () private virtual
Strip off the interface elements before adapting the bulk mesh.
Reimplemented from oomph::Problem.
actions_before_implicit_timestep() [1/3]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::actions_before_implicit_timestep () inline private virtual
Actions before the timestep: For maximum stability, reset the current nodal positions to be the "stress-free" ones.
Reimplemented from oomph::Problem.
   {
    Bulk_mesh_pt->set_lagrangian_nodal_coordinates();
   }
actions_before_implicit_timestep() [2/3]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::actions_before_implicit_timestep () inline private virtual
Actions before the timestep: For maximum stability, reset the current nodal positions to be the "stress-free" ones.
Reimplemented from oomph::Problem.
   {
    Bulk_mesh_pt->set_lagrangian_nodal_coordinates();
   }
actions_before_implicit_timestep() [3/3]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::actions_before_implicit_timestep () inline private virtual
Actions before the timestep: For maximum stability, reset the current nodal positions to be the "stress-free" ones.
Reimplemented from oomph::Problem.
   {
    Bulk_mesh_pt->set_lagrangian_nodal_coordinates();
   }
actions_before_newton_convergence_check() [1/8]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::actions_before_newton_convergence_check () inline virtual
Spine heights/lengths are unknowns in the problem so their values get corrected during each Newton step. However, changing their value does not automatically change the nodal positions, so we need to update all of them here.
Reimplemented from oomph::Problem.
   {
    Bulk_mesh_pt->node_update();
   }
actions_before_newton_convergence_check() [2/8]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::actions_before_newton_convergence_check () inline virtual
Spine heights/lengths are unknowns in the problem so their values get corrected during each Newton step. However, changing their value does not automatically change the nodal positions, so we need to update all of them here.
Reimplemented from oomph::Problem.
   {
    Bulk_mesh_pt->node_update();
   }
actions_before_newton_convergence_check() [3/8]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::actions_before_newton_convergence_check () inline private virtual
Spine heights/lengths are unknowns in the problem so their values get corrected during each Newton step. However, changing their value does not automatically change the nodal positions, so we need to update all of them here.
Reimplemented from oomph::Problem.
   {
    Bulk_mesh_pt->node_update();
   }
actions_before_newton_convergence_check() [4/8]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::actions_before_newton_convergence_check () inline virtual
Spine heights/lengths are unknowns in the problem so their values get corrected during each Newton step. However, changing their value does not automatically change the nodal positions, so we need to update all of them
Reimplemented from oomph::Problem.
 {Bulk_mesh_pt->node_update();}
actions_before_newton_convergence_check() [5/8]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::actions_before_newton_convergence_check () inline virtual
Spine heights/lengths are unknowns in the problem so their values get corrected during each Newton step. However, changing their value does not automatically change the nodal positions, so we need to update all of them here.
Reimplemented from oomph::Problem.
   {
    Bulk_mesh_pt->node_update();
   }
actions_before_newton_convergence_check() [6/8]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::actions_before_newton_convergence_check () inline private virtual
Spine heights/lengths are unknowns in the problem so their values get corrected during each Newton step. However, changing their value does not automatically change the nodal positions, so we need to update all of them here.
Reimplemented from oomph::Problem.
   {
    Bulk_mesh_pt->node_update();
   }
References oomph::SpineMesh::node_update().
actions_before_newton_convergence_check() [7/8]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::actions_before_newton_convergence_check () inline virtual
Spine heights/lengths are unknowns in the problem so their values get corrected during each Newton step. However, changing their value does not automatically change the nodal positions, so we need to update all of them
Reimplemented from oomph::Problem.
 {Bulk_mesh_pt->node_update();}
actions_before_newton_convergence_check() [8/8]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::actions_before_newton_convergence_check () inline private virtual
Spine heights/lengths are unknowns in the problem so their values get corrected during each Newton step. However, changing their value does not automatically change the nodal positions, so we need to update all of them here.
Reimplemented from oomph::Problem.
   {
    Bulk_mesh_pt->node_update();
   }
actions_before_newton_solve() [1/8]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::actions_before_newton_solve () inline virtual
Any actions that are to be performed before a complete Newton solve (e.g. adjust boundary conditions). CAREFUL: This step should (and if the FD-based LinearSolver FD_LU is used, must) only update values that are pinned!
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [2/8]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::actions_before_newton_solve () inline virtual
Any actions that are to be performed before a complete Newton solve (e.g. adjust boundary conditions). CAREFUL: This step should (and if the FD-based LinearSolver FD_LU is used, must) only update values that are pinned!
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [3/8]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::actions_before_newton_solve () inline private virtual
No actions required before solve step.
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [4/8]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::actions_before_newton_solve () inline private virtual
No actions required before solve step.
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [5/8]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::actions_before_newton_solve () inline private virtual
No actions required before solve step.
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [6/8]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::actions_before_newton_solve () inline private virtual
No actions required before solve step.
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [7/8]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::actions_before_newton_solve () inline private virtual
No actions required before solve step.
Reimplemented from oomph::Problem.
 {}
actions_before_newton_solve() [8/8]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::actions_before_newton_solve () inline private virtual
No actions required before solve step.
Reimplemented from oomph::Problem.
 {}
compute_total_mass() [1/3]
template<class ELEMENT , class TIMESTEPPER > double InterfaceProblem< ELEMENT, TIMESTEPPER >::compute_total_mass () inline
Compute the total mass.
   {
    double mass = 0.0;
    // Determine number of 1D interface elements in mesh
    const unsigned n_interface_element = Surface_mesh_pt->nelement();
    // Loop over the interface elements
    for(unsigned e=0;e<n_interface_element;e++)
     {
      // Upcast from GeneralisedElement to the present element
      SpineSurfaceSurfactantTransportInterfaceElement<ELEMENT>* el_pt =
       dynamic_cast<SpineSurfaceSurfactantTransportInterfaceElement<ELEMENT>*>
       (Surface_mesh_pt->element_pt(e));
      mass += el_pt->integrate_c();
     }
    return mass;
   }
References e(), and oomph::SurfactantTransportInterfaceElement::integrate_c().
compute_total_mass() [2/3]
template<class ELEMENT , class TIMESTEPPER > double InterfaceProblem< ELEMENT, TIMESTEPPER >::compute_total_mass () inline
Compute the total mass of the insoluble surfactant.
   {
    //Initialise to zero
    double mass = 0.0;
    // Determine number of 1D interface elements in mesh
    const unsigned n_interface_element = Interface_mesh_pt->nelement();
    // Loop over the interface elements
    for(unsigned e=0;e<n_interface_element;e++)
     {
      // Upcast from GeneralisedElement to the present element
      SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement<ELEMENT>* el_pt =
       dynamic_cast<SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement<ELEMENT>*>
       (Interface_mesh_pt->element_pt(e));
      //Add contribution from each element
      mass += el_pt->integrate_c();
     }
    return mass;
   } // End of compute_total_mass
References e(), oomph::Mesh::element_pt(), oomph::SpineAxisymmetricMarangoniSurfactantFluidInterfaceElement< ELEMENT >::integrate_c(), and oomph::Mesh::nelement().
compute_total_mass() [3/3]
template<class ELEMENT , class TIMESTEPPER > double InterfaceProblem< ELEMENT, TIMESTEPPER >::compute_total_mass () inline
Compute the total mass of the insoluble surfactant.
   {
    //Initialise to zero
    double mass = 0.0;
    // Determine number of 1D interface elements in mesh
    const unsigned n_interface_element = Interface_mesh_pt->nelement();
    // Loop over the interface elements
    for(unsigned e=0;e<n_interface_element;e++)
     {
      // Upcast from GeneralisedElement to the present element
      ElasticAxisymmetricSurfactantTransportInterfaceElement<ELEMENT>* el_pt =
       dynamic_cast<ElasticAxisymmetricSurfactantTransportInterfaceElement<ELEMENT>*>
       (Interface_mesh_pt->element_pt(e));
      //Add contribution from each element
      mass += el_pt->integrate_c();
     }
    return mass;
   } // End of compute_total_mass
References e(), oomph::Mesh::element_pt(), oomph::SurfactantTransportInterfaceElement::integrate_c(), and oomph::Mesh::nelement().
create_interface_elements() [1/2]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::create_interface_elements private
Create the 1d interface elements.
Create interface elements between the two fluids in the mesh pointed to by Bulk_mesh_pt and add the elements to the Mesh object pointed to by Surface_mesh_pt.
 {
  // Determine number of bulk elements adjacent to interface (boundary 4)
  const unsigned n_element = this->Bulk_mesh_pt->nboundary_element(4);
  // Loop over those elements adjacent to the interface
  for(unsigned e=0;e<n_element;e++)
   {
    // Get pointer to the bulk element that is adjacent to the interface
    ELEMENT* bulk_elem_pt = dynamic_cast<ELEMENT*>(
     this->Bulk_mesh_pt->boundary_element_pt(4,e));
    // We only want to attach interface elements to the bulk elements
    // which are BELOW the interface, and so we filter out those above by
    // referring to the viscosity_ratio_pt
    if(bulk_elem_pt->viscosity_ratio_pt()
       !=&Global_Physical_Variables::Viscosity_Ratio)
     {
      // Find index of the face of element e that corresponds to the interface
      const int face_index = this->Bulk_mesh_pt->face_index_at_boundary(4,e);
      // Create the interface element
      FiniteElement* interface_element_element_pt =
       new ElasticAxisymmetricFluidInterfaceElement<ELEMENT>(bulk_elem_pt,
                                                             face_index);
      // Add the interface element to the surface mesh
      this->Surface_mesh_pt->add_element_pt(interface_element_element_pt);
     }
   }
  // --------------------------------------------------------
  // Complete the setup to make the elements fully functional
  // --------------------------------------------------------
  // Determine number of 1D interface elements in mesh
  const unsigned n_interface_element = this->Surface_mesh_pt->nelement();
  // Loop over the interface elements
  for(unsigned e=0;e<n_interface_element;e++)
   {
    // Upcast from GeneralisedElement to the present element
    ElasticAxisymmetricFluidInterfaceElement<ELEMENT>* el_pt =
     dynamic_cast<ElasticAxisymmetricFluidInterfaceElement<ELEMENT>*>
     (Surface_mesh_pt->element_pt(e));
    // Set the Strouhal number
    el_pt->st_pt() = &Global_Physical_Variables::St;
    // Set the Capillary number
    el_pt->ca_pt() = &Global_Physical_Variables::Ca;
   } // End of loop over interface elements
 } // End of create_interface_elements()
References Global_Physical_Variables::Ca, oomph::FluidInterfaceElement::ca_pt(), e(), Global_Physical_Variables::St, oomph::FluidInterfaceElement::st_pt(), and Global_Physical_Variables::Viscosity_Ratio.
create_interface_elements() [2/2]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::create_interface_elements () private
Create the 1d interface elements.
deform_free_surface() [1/10]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::deform_free_surface (const double & epsilon) inline private
Deform the mesh/free surface to a prescribed function.
   {
    // Determine number of spines in mesh
    const unsigned n_spine = Bulk_mesh_pt->nspine();
    // Loop over spines in mesh
    for(unsigned i=0;i<n_spine;i++)
     {
      // Determine z coordinate of spine
      double z_value = Bulk_mesh_pt->boundary_node_pt(1,i)->x(1);
      // Set spine height
      Bulk_mesh_pt->spine_pt(i)->height() = Lr + epsilon*cos((z_value/Height)*2.0*MathematicalConstants::Pi);
     } // End of loop over spines
    // Update nodes in bulk mesh
    Bulk_mesh_pt->node_update();
   } // End of deform_free_surface
References oomph::Mesh::boundary_node_pt(), cos(), oomph::SarahBL::epsilon, GlobalParameters::Height, oomph::Spine::height(), i, Global_Parameters::Lr, oomph::SpineMesh::node_update(), oomph::SpineMesh::nspine(), BiharmonicTestFunctions2::Pi, oomph::SpineMesh::spine_pt(), and oomph::Node::x().
deform_free_surface() [2/10]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::deform_free_surface (const double & epsilon) inline private
Deform the mesh/free surface to a prescribed function.
   {
    // Determine number of spines in mesh
    const unsigned n_spine = Bulk_mesh_pt->nspine();
    // Loop over spines in mesh
    for(unsigned i=0;i<n_spine;i++)
     {
      // Determine z coordinate of spine
      double z_value = Bulk_mesh_pt->boundary_node_pt(1,i)->x(1);
      // Set spine height
      Bulk_mesh_pt->spine_pt(i)->height() =
       Global_Physical_Variables::Film_Thickness*(1.0 +
                                                  + epsilon*cos(Global_Physical_Variables::Alpha*z_value));
     } // End of loop over spines
    // Update nodes in bulk mesh
    Bulk_mesh_pt->node_update();
   } // End of deform_free_surface
References Global_Physical_Variables::Alpha, oomph::Mesh::boundary_node_pt(), cos(), oomph::SarahBL::epsilon, Global_Physical_Variables::Film_Thickness, oomph::Spine::height(), i, oomph::SpineMesh::node_update(), oomph::SpineMesh::nspine(), oomph::SpineMesh::spine_pt(), and oomph::Node::x().
deform_free_surface() [3/10]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::deform_free_surface (const double & epsilon) inline private
Deform the mesh/free surface to a prescribed function.
   {
    //Loop over all nodes in the mesh
    const unsigned n_node = Bulk_mesh_pt->nnode();
    for(unsigned n=0;n<n_node;n++)
     {
      //Find out the r value
      double r = Bulk_mesh_pt->node_pt(n)->x(0);
      // Determine z coordinate of spine
      double z_value = Bulk_mesh_pt->node_pt(n)->x(1);
      //Set the thickess of the filme
      double thickness =
       Global_Physical_Variables::Film_Thickness*(1.0 +
                                                  + epsilon*cos(Global_Physical_Variables::Alpha*z_value));
      //Now scale the position accordingly
      Bulk_mesh_pt->node_pt(n)->x(0) = 1.0 - (1.0-r)*thickness;
     }
    //Reset the lagrangian coordinates
    Bulk_mesh_pt->set_lagrangian_nodal_coordinates();
   } // End of deform_free_surface
References Global_Physical_Variables::Alpha, cos(), oomph::SarahBL::epsilon, Global_Physical_Variables::Film_Thickness, n, oomph::Mesh::nnode(), oomph::SolidMesh::node_pt(), UniformPSDSelfTest::r, oomph::SolidMesh::set_lagrangian_nodal_coordinates(), and oomph::Node::x().
deform_free_surface() [4/10]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::deform_free_surface (const double & epsilon, const double & k) inline private
Deform the mesh/free surface to a prescribed function.
   {
    // Initialise Bessel functions (only need the first!)
    double j0, j1, y0, y1, j0p, j1p, y0p, y1p;
    // Determine number of spines in mesh
    const unsigned n_spine = Bulk_mesh_pt->nspine();
    // Loop over spines in mesh
    for(unsigned i=0;i<n_spine;i++)
     {
      // Determine r coordinate of spine
      double r_value = Bulk_mesh_pt->boundary_node_pt(0,i)->x(0);
      // Get Bessel functions J_0(kr), J_1(kr), Y_0(kr), Y_1(kr)
      // and their derivatives
      CRBond_Bessel::bessjy01a(k*r_value,j0,j1,y0,y1,j0p,j1p,y0p,y1p);
      // Set spine height
      Bulk_mesh_pt->spine_pt(i)->height() = 1.0 + epsilon*j0;
     } // End of loop over spines
    // Update nodes in bulk mesh
    Bulk_mesh_pt->node_update();
   } // End of deform_free_surface
References CRBond_Bessel::bessjy01a(), oomph::Mesh::boundary_node_pt(), oomph::SarahBL::epsilon, oomph::Spine::height(), i, k, oomph::SpineMesh::node_update(), oomph::SpineMesh::nspine(), oomph::SpineMesh::spine_pt(), and oomph::Node::x().
deform_free_surface() [5/10]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::deform_free_surface (const double & epsilon, const double & k) private
Deform the mesh/free surface to a prescribed function.
deform_free_surface() [6/10]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::deform_free_surface (const double & epsilon, const double & k) private
Deform the mesh/free surface to a prescribed function.
deform_free_surface() [7/10]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::deform_free_surface (const double & epsilon, const unsigned & n_periods) private
Deform the mesh/free surface to a prescribed function.
 {
  // Determine number of nodes in the "bulk" mesh
  const unsigned n_node = Bulk_mesh_pt->nnode();
  // Loop over all nodes in mesh
  for(unsigned n=0;n<n_node;n++)
   {
    // Determine eulerian position of node
    const double current_x_pos = Bulk_mesh_pt->node_pt(n)->x(0);
    const double current_y_pos = Bulk_mesh_pt->node_pt(n)->x(1);
    // Determine new vertical position of node
    const double new_y_pos = current_y_pos
     + (1.0-fabs(1.0-current_y_pos))*epsilon
     *(cos(2.0*n_periods*MathematicalConstants::Pi*current_x_pos/Lx));
    // Set new position
    Bulk_mesh_pt->node_pt(n)->x(1) = new_y_pos;
   }
 } // End of deform_free_surface
References cos(), oomph::SarahBL::epsilon, boost::multiprecision::fabs(), Global_Parameters::Lx, n, and BiharmonicTestFunctions2::Pi.
deform_free_surface() [8/10]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::deform_free_surface (const double & epsilon, const unsigned & n_periods) private
Deform the mesh/free surface to a prescribed function.
deform_free_surface() [9/10]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::deform_free_surface (const double & epsilon, const unsigned & n_periods) private
Deform the mesh/free surface to a prescribed function.
deform_free_surface() [10/10]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::deform_free_surface (const double & epsilon, const unsigned & n_periods) private
Deform the mesh/free surface to a prescribed function.
delete_interface_elements() [1/2]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::delete_interface_elements private
Delete the 1d interface elements.
Delete the interface elements and wipe the surface mesh.
 {
  // Determine number of interface elements
  const unsigned n_interface_element = Surface_mesh_pt->nelement();
  // Loop over interface elements and delete
  for(unsigned e=0;e<n_interface_element;e++)
   {
    delete Surface_mesh_pt->element_pt(e);
   }
  // Wipe the mesh
  Surface_mesh_pt->flush_element_and_node_storage();
 } // End of delete_interface_elements
References e().
delete_interface_elements() [2/2]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::delete_interface_elements () private
Delete the 1d interface elements.
doc_solution() [1/12]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::doc_solution (DocInfo & doc_info)
Doc the solution.
Document the solution.
 {
  // Output the time
  double t= time_pt()->time();
  cout << "Time is now " << t << std::endl;
  // Document in trace file
  Trace_file << time_pt()->time() << " "
             << Bulk_mesh_pt->spine_pt(0)->height() << std::endl;
  ofstream some_file;
  char filename[100];
  // Set number of plot points (in each coordinate direction)
  const unsigned npts = 5;
  // Open solution output file
  sprintf(filename,"%s/soln%i.dat",doc_info.directory().c_str(),
          doc_info.number());
  some_file.open(filename);
  // Output solution to file
  Bulk_mesh_pt->output(some_file,npts);
  Interface_mesh_pt->output(some_file,npts);
  // Write file as a tecplot text object...
  some_file << "TEXT X=2.5,Y=93.6,F=HELV,HU=POINT,C=BLUE,H=26,T=\"time = "
            << time_pt()->time() << "\"";
  // ...and draw a horizontal line whose length is proportional
  // to the elapsed time
  some_file << "GEOMETRY X=2.5,Y=98,T=LINE,C=BLUE,LT=0.4" << std::endl;
  some_file << "1" << std::endl;
  some_file << "2" << std::endl;
  some_file << " 0 0" << std::endl;
  some_file << time_pt()->time()*20.0 << " 0" << std::endl;
  // Close solution output file
  some_file.close();
  // Output solution to file in paraview format
  string file_name="soln"+StringConversion::to_string(doc_info.number())
   +".vtu";
  sprintf(filename,"%s/%s",doc_info.directory().c_str(),file_name.c_str());
  some_file.open(filename);
  Bulk_mesh_pt->output_paraview(some_file,npts);
  some_file.close();
  // Write pvd information
  ParaviewHelper::write_pvd_information(Global_Physical_Variables::Pvd_file,
                                        file_name,t);
 } // End of doc_solution
References oomph::DocInfo::directory(), Particles2023AnalysisHung::file_name, MergeRestartFiles::filename, oomph::DocInfo::number(), Global_Physical_Variables::Pvd_file, plotPSD::t, oomph::StringConversion::to_string(), oomph::Problem_Parameter::Trace_file, and oomph::ParaviewHelper::write_pvd_information().
doc_solution() [2/12]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::doc_solution (DocInfo & doc_info)
Doc the solution.
doc_solution() [3/12]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::doc_solution (DocInfo & doc_info)
Document the solution.
doc_solution() [4/12]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::doc_solution (DocInfo & doc_info)
Doc the solution.
doc_solution() [5/12]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::doc_solution (DocInfo & doc_info)
Doc the solution.
doc_solution() [6/12]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::doc_solution (DocInfo & doc_info)
Doc the solution.
doc_solution() [7/12]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::doc_solution (DocInfo & doc_info)
Doc the solution.
doc_solution() [8/12]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::doc_solution (DocInfo & doc_info)
Document the solution.
doc_solution() [9/12]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::doc_solution (DocInfo & doc_info)
Doc the solution.
doc_solution() [10/12]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::doc_solution (DocInfo & doc_info)
Doc the solution.
doc_solution() [11/12]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::doc_solution (DocInfo & doc_info)
Document the solution.
doc_solution() [12/12]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::doc_solution (DocInfo & doc_info)
Doc the solution.
fix_pressure() [1/4]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::fix_pressure (const unsigned & e, const unsigned & pdof, const double & pvalue) inline private
Fix pressure in element e at pressure dof pdof and set to pvalue.
   {
    // Fix the pressure at that element
    dynamic_cast<ELEMENT*>(mesh_pt()->element_pt(e))->
                           fix_pressure(pdof,pvalue);
   }
References e().
Referenced by InterfaceProblem< ELEMENT, TIMESTEPPER >::InterfaceProblem().
fix_pressure() [2/4]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::fix_pressure (const unsigned & e, const unsigned & pdof, const double & pvalue) inline private
Fix pressure in element e at pressure dof pdof and set to pvalue.
   {
    // Fix the pressure at that element
    dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(e))->
                           fix_pressure(pdof,pvalue);
   }
References e().
fix_pressure() [3/4]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::fix_pressure (const unsigned & e, const unsigned & pdof, const double & pvalue) inline private
Fix pressure in element e at pressure dof pdof and set to pvalue.
   {
    // Fix the pressure at that element
    dynamic_cast<ELEMENT*>(mesh_pt()->element_pt(e))->
                           fix_pressure(pdof,pvalue);
   }
References e().
fix_pressure() [4/4]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::fix_pressure (const unsigned & e, const unsigned & pdof, const double & pvalue) inline private
Fix pressure in element e at pressure dof pdof and set to pvalue.
   {
    // Fix the pressure at that element
    dynamic_cast<ELEMENT*>(Bulk_mesh_pt->element_pt(e))->
                           fix_pressure(pdof,pvalue);
   }
References e().
global_temporal_error_norm() [1/2]
template<class ELEMENT , class TIMESTEPPER > double InterfaceProblem< ELEMENT, TIMESTEPPER >::global_temporal_error_norm () inline virtual
The global temporal error norm, based on the movement of the nodes in the radial direction only (because that's the only direction in which they move!)
Reimplemented from oomph::Problem.
   {
    //Temp
    double global_error = 0.0;
    //Find out how many nodes there are in the problem
    const unsigned n_node = Bulk_mesh_pt->nnode();
    //Loop over the nodes and calculate the errors in the positions
    for(unsigned n=0;n<n_node;n++)
     {
      //Set the dimensions to be restricted to the radial direction only
      const unsigned n_dim = 1;
      //Set the position error to zero
      double node_position_error = 0.0;
      //Loop over the dimensions
      for(unsigned i=0;i<n_dim;i++)
       {
        //Get position error
        double error =
         Bulk_mesh_pt->node_pt(n)->position_time_stepper_pt()->
         temporal_error_in_position(Bulk_mesh_pt->node_pt(n),i);
        //Add the square of the individual error to the position error
        node_position_error += error*error;
       }
      //Divide the position error by the number of dimensions
      node_position_error /= n_dim;
      //Now add to the global error
      global_error += node_position_error;
     }
    //Now the global error must be divided by the number of nodes
    global_error /= n_node;
    //Return the square root of the errr
    return sqrt(global_error);
   }
References calibrate::error, i, n, and sqrt().
global_temporal_error_norm() [2/2]
template<class ELEMENT , class TIMESTEPPER > double InterfaceProblem< ELEMENT, TIMESTEPPER >::global_temporal_error_norm () inline virtual
The global temporal error norm, based on the movement of the nodes in the radial direction only (because that's the only direction in which they move!)
Reimplemented from oomph::Problem.
   {
    //Temp
    double global_error = 0.0;
    //Find out how many nodes there are in the problem
    const unsigned n_node = Bulk_mesh_pt->nnode();
    //Loop over the nodes and calculate the errors in the positions
    for(unsigned n=0;n<n_node;n++)
     {
      //Set the dimensions to be restricted to the radial direction only
      const unsigned n_dim = 1;
      //Set the position error to zero
      double node_position_error = 0.0;
      //Loop over the dimensions
      for(unsigned i=0;i<n_dim;i++)
       {
        //Get position error
        double error =
         Bulk_mesh_pt->node_pt(n)->position_time_stepper_pt()->
         temporal_error_in_position(Bulk_mesh_pt->node_pt(n),i);
        //Add the square of the individual error to the position error
        node_position_error += error*error;
       }
      //Divide the position error by the number of dimensions
      node_position_error /= n_dim;
      //Now add to the global error
      global_error += node_position_error;
     }
    //Now the global error must be divided by the number of nodes
    global_error /= n_node;
    //Return the square root of the errr
    return sqrt(global_error);
   }
References calibrate::error, i, n, and sqrt().
set_boundary_conditions() [1/6]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::set_boundary_conditions
Set boundary conditions.
Set boundary conditions: Set all velocity components to zero on the top and bottom (solid) walls and the radial and azimuthal components only to zero on the side boundaries
Set boundary conditions: Set both velocity components to zero on the bottom (solid) wall and the horizontal component only to zero on the side (periodic) boundaries
Set boundary conditions: Set both velocity components to zero on the top and bottom (solid) walls and the horizontal component only to zero on the side (periodic) boundaries
 {
  // Determine number of mesh boundaries
  const unsigned n_boundary = Bulk_mesh_pt->nboundary();
  // Loop over mesh boundaries
  for(unsigned b=0;b<n_boundary;b++)
   {
    // Determine number of nodes on boundary b
    const unsigned n_node = Bulk_mesh_pt->nboundary_node(b);
    // Loop over nodes on boundary b
    for(unsigned n=0;n<n_node;n++)
     {
      // Set radial component of the velocity to zero on all boundaries
      // other than the interface (b=4)
      if(b!=4) { Bulk_mesh_pt->boundary_node_pt(b,n)->set_value(0,0.0); }
      // Set azimuthal component of the velocity to zero on all boundaries
      // other than the interface (b=4)
      if(b!=4) { Bulk_mesh_pt->boundary_node_pt(b,n)->set_value(2,0.0); }
      // Set axial component of the velocity to zero on solid boundaries
      if(b==0 || b==2)
       {
        Bulk_mesh_pt->boundary_node_pt(b,n)->set_value(1,0.0);
       }
     }
   }
 } // End of set_boundary_conditions
References b, and n.
Referenced by InterfaceProblem< ELEMENT, TIMESTEPPER >::InterfaceProblem().
set_boundary_conditions() [2/6]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::set_boundary_conditions ()
Set boundary conditions.
set_boundary_conditions() [3/6]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::set_boundary_conditions ()
Set boundary conditions.
set_boundary_conditions() [4/6]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::set_boundary_conditions ()
Set boundary conditions.
set_boundary_conditions() [5/6]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::set_boundary_conditions ()
Set boundary conditions.
set_boundary_conditions() [6/6]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::set_boundary_conditions ()
Set boundary conditions.
set_initial_condition() [1/10]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::set_initial_condition inline virtual
Set initial conditions: Set all nodal velocities to zero and initialise the previous velocities to correspond to an impulsive start
Set initial conditions: Set all nodal velocities to zero and initialise the previous velocities and nodal positions to correspond to an impulsive start
Reimplemented from oomph::Problem.
   {
    // Determine number of nodes in mesh
    const unsigned n_node = Bulk_mesh_pt->nnode();
    // Loop over all nodes in mesh
    for(unsigned n=0;n<n_node;n++)
     {
      // Loop over the three velocity components
      for(unsigned i=0;i<3;i++)
       {
        // Set velocity component i of node n to zero
        Bulk_mesh_pt->node_pt(n)->set_value(i,0.0);
       }
     }
    // Initialise the previous velocity values for timestepping
    // corresponding to an impulsive start
    assign_initial_values_impulsive();
   } // End of set_initial_condition
References i, and n.
set_initial_condition() [2/10]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::set_initial_condition () inline virtual
Set initial conditions: Set all nodal velocities to zero and initialise the previous velocities to correspond to an impulsive start
Reimplemented from oomph::Problem.
   {
    // Determine number of nodes in mesh
    const unsigned n_node = Bulk_mesh_pt->nnode();
    // Loop over all nodes in mesh
    for(unsigned n=0;n<n_node;n++)
     {
      // Loop over the three velocity components
      for(unsigned i=0;i<3;i++)
       {
        // Set velocity component i of node n to zero
        Bulk_mesh_pt->node_pt(n)->set_value(i,0.0);
       }
     }
    // Initialise the previous velocity values for timestepping
    // corresponding to an impulsive start
    assign_initial_values_impulsive();
   } // End of set_initial_condition
References i, and n.
set_initial_condition() [3/10]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::set_initial_condition () virtual
Set initial conditions.
Reimplemented from oomph::Problem.
set_initial_condition() [4/10]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::set_initial_condition () virtual
Set initial conditions.
Reimplemented from oomph::Problem.
set_initial_condition() [5/10]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::set_initial_condition () inline virtual
Set initial conditions: Set all nodal velocities to zero and initialise the previous velocities to correspond to an impulsive start
Reimplemented from oomph::Problem.
   {
    // Determine number of nodes in mesh
    const unsigned n_node = Bulk_mesh_pt->nnode();
    // Loop over all nodes in mesh
    for(unsigned n=0;n<n_node;n++)
     {
      // Loop over the three velocity components
      for(unsigned i=0;i<3;i++)
       {
        // Set velocity component i of node n to zero
        Bulk_mesh_pt->node_pt(n)->set_value(i,0.0);
       }
     }
    // Initialise the previous velocity values for timestepping
    // corresponding to an impulsive start
    assign_initial_values_impulsive();
   } // End of set_initial_condition
References i, and n.
set_initial_condition() [6/10]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::set_initial_condition () inline virtual
Set initial conditions: Set all nodal velocities to zero and initialise the previous velocities to correspond to an impulsive start
Reimplemented from oomph::Problem.
   {
    // Determine number of nodes in mesh
    const unsigned n_node = Bulk_mesh_pt->nnode();
    // Loop over all nodes in mesh
    for(unsigned n=0;n<n_node;n++)
     {
      // Loop over the three velocity components
      for(unsigned i=0;i<3;i++)
       {
        // Set velocity component i of node n to zero
        Bulk_mesh_pt->node_pt(n)->set_value(i,0.0);
       }
      //Set the bulk concentration to be 1
      Bulk_mesh_pt->node_pt(n)->set_value(3,1.0);
     }
    // Initialise the previous velocity values for timestepping
    // corresponding to an impulsive start
    assign_initial_values_impulsive();
   } // End of set_initial_condition
References i, and n.
set_initial_condition() [7/10]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::set_initial_condition () virtual
Set initial conditions.
Reimplemented from oomph::Problem.
set_initial_condition() [8/10]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::set_initial_condition () virtual
Set initial conditions.
Reimplemented from oomph::Problem.
set_initial_condition() [9/10]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::set_initial_condition () virtual
Set initial conditions.
Reimplemented from oomph::Problem.
set_initial_condition() [10/10]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::set_initial_condition () virtual
Set initial conditions.
Reimplemented from oomph::Problem.
unsteady_run() [1/12]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::unsteady_run (const double & t_max, const double & dt)
Do unsteady run up to maximum time t_max with given timestep dt.
Perform run up to specified time t_max with given timestep dt.
 {
  // Set value of epsilon
  double epsilon = Global_Physical_Variables::Epsilon;
  // Deform the mesh/free surface
  deform_free_surface(epsilon);
  // Initialise DocInfo object
  DocInfo doc_info;
  // Set output directory
  doc_info.set_directory("RESLT");
  // Initialise counter for solutions
  doc_info.number()=0;
  // Open trace file
  char filename[100];
  sprintf(filename,"%s/trace.dat",doc_info.directory().c_str());
  Trace_file.open(filename);
  // Initialise trace file
  Trace_file << "time" << ", "
             << "edge spine height" << ", "
             << "contact angle left" << ", "
             << "contact angle right" << ", " << std::endl;
  // Initialise timestep
  initialise_dt(dt);
  // Set initial conditions
  set_initial_condition();
  // Determine number of timesteps
  const unsigned n_timestep = unsigned(t_max/dt);
  // Open pvd file -- a wrapper for all the different
  // vtu output files plus information about continuous time
  // to facilitate animations in paraview
  sprintf(filename,"%s/soln.pvd",doc_info.directory().c_str());
  Global_Physical_Variables::Pvd_file.open(filename);
  ParaviewHelper::write_pvd_header(Global_Physical_Variables::Pvd_file);
  // Doc initial solution
  doc_solution(doc_info);
  // Increment counter for solutions
  doc_info.number()++;
  // Timestepping loop
  for(unsigned t=1;t<=n_timestep;t++)
   {
    // Output current timestep to screen
    cout << "\nTimestep " << t << " of " << n_timestep << std::endl;
    // Take one fixed timestep
    unsteady_newton_solve(dt);
    // Doc solution
    doc_solution(doc_info);
    // Increment counter for solutions
    doc_info.number()++;
   } // End of timestepping loop
  // write footer and close pvd file
  ParaviewHelper::write_pvd_footer(Global_Physical_Variables::Pvd_file);
  Global_Physical_Variables::Pvd_file.close();
 } // End of unsteady_run
References oomph::DocInfo::directory(), Global_Physical_Variables::Epsilon, oomph::SarahBL::epsilon, MergeRestartFiles::filename, oomph::DocInfo::number(), Global_Physical_Variables::Pvd_file, oomph::DocInfo::set_directory(), plotPSD::t, oomph::Problem_Parameter::Trace_file, oomph::ParaviewHelper::write_pvd_footer(), and oomph::ParaviewHelper::write_pvd_header().
unsteady_run() [2/12]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::unsteady_run (const double & t_max, const double & dt)
Do unsteady run up to maximum time t_max with given timestep dt.
unsteady_run() [3/12]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::unsteady_run (const double & t_max, const double & dt)
Do unsteady run up to maximum time t_max with given timestep dt.
unsteady_run() [4/12]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::unsteady_run (const double & t_max, const double & dt)
Do unsteady run up to maximum time t_max with given timestep dt.
unsteady_run() [5/12]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::unsteady_run (const double & t_max, const double & dt)
Do unsteady run up to maximum time t_max with given timestep dt.
unsteady_run() [6/12]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::unsteady_run (const double & t_max, const double & dt)
Do unsteady run up to maximum time t_max with given timestep dt.
unsteady_run() [7/12]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::unsteady_run (const double & t_max, const double & dt)
Do unsteady run up to maximum time t_max with given timestep dt.
unsteady_run() [8/12]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::unsteady_run (const double & t_max, const double & dt)
Do unsteady run up to maximum time t_max with given timestep dt.
unsteady_run() [9/12]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::unsteady_run (const double & t_max, const double & dt)
Do unsteady run up to maximum time t_max with given timestep dt.
unsteady_run() [10/12]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::unsteady_run (const double & t_max, const double & dt)
Do unsteady run up to maximum time t_max with given timestep dt.
unsteady_run() [11/12]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::unsteady_run (const unsigned & nstep)
Run an unsteady simulation with specified number of steps.
Unsteady run with specified number of steps.
 {
  // Increase maximum residual
  Problem::Max_residuals=500.0;
  //Distort the mesh
  const double epsilon=Global_Physical_Variables::Epsilon;
  unsigned Nspine = Bulk_mesh_pt->nspine();
  for(unsigned i=0;i<Nspine;i++)
   {
     double y_value = Bulk_mesh_pt->boundary_node_pt(0,i)->x(1);
     Bulk_mesh_pt->spine_pt(i)->height() =
      Global_Physical_Variables::Film_Thickness*(1.0 +
                                                 + epsilon*cos(Global_Physical_Variables::Alpha*y_value));
   }
  //Make sure to update
  Bulk_mesh_pt->node_update();
  // Doc info object
  DocInfo doc_info;
  // Set output directory
  doc_info.set_directory("RESLT");
  doc_info.number()=0;
  // Open trace file
  char filename[100];
  sprintf(filename,"%s/trace.dat",doc_info.directory().c_str());
  Trace_file.open(filename);
  Trace_file << "VARIABLES=\"time\",";
  Trace_file << "\"h<sub>left</sub>\",\"h<sub>right</sub>\"";
  Trace_file << "\n";
  //Set value of dt
  double  dt = 0.1;
  //Initialise all time values
  assign_initial_values_impulsive(dt);
  //Doc initial solution
  doc_solution(doc_info);
 //Loop over the timesteps
  for(unsigned t=1;t<=nstep;t++)
   {
    cout << "TIMESTEP " << t << std::endl;
    //Take one fixed timestep
    unsteady_newton_solve(dt);
    // Doc solution
    doc_info.number()++;
    doc_solution(doc_info);
    }
 }
References Global_Physical_Variables::Alpha, cos(), oomph::DocInfo::directory(), Global_Physical_Variables::Epsilon, oomph::SarahBL::epsilon, MergeRestartFiles::filename, Global_Physical_Variables::Film_Thickness, i, oomph::DocInfo::number(), oomph::DocInfo::set_directory(), plotPSD::t, and oomph::Problem_Parameter::Trace_file.
unsteady_run() [12/12]
template<class ELEMENT , class TIMESTEPPER > void InterfaceProblem< ELEMENT, TIMESTEPPER >::unsteady_run (const unsigned & nstep)
Run an unsteady simulation with specified number of steps.
Member Data Documentation
Bulk_mesh_pt [1/8]
template<class ELEMENT , class TIMESTEPPER > TwoLayerSpineMesh< ELEMENT > * InterfaceProblem< ELEMENT, TIMESTEPPER >::Bulk_mesh_pt
Access function for the specific mesh.
Pointer to the specific bulk mesh.
The bulk fluid mesh, complete with spines and update information.
Pointer to the (specific) "bulk" mesh.
Referenced by InterfaceProblem< ELEMENT, TIMESTEPPER >::InterfaceProblem().
Bulk_mesh_pt [2/8]
template<class ELEMENT , class TIMESTEPPER > SingleLayerSpineMesh<ELEMENT>* InterfaceProblem< ELEMENT, TIMESTEPPER >::Bulk_mesh_pt
Access function for the specific mesh.
The bulk fluid mesh, complete with spines and update information.
Bulk_mesh_pt [3/8]
template<class ELEMENT , class TIMESTEPPER > ElasticRefineableTwoLayerMesh<ELEMENT>* InterfaceProblem< ELEMENT, TIMESTEPPER >::Bulk_mesh_pt private
Pointer to the (specific) "bulk" mesh.
Bulk_mesh_pt [4/8]
template<class ELEMENT , class TIMESTEPPER > TwoLayerSpineMesh<ELEMENT>* InterfaceProblem< ELEMENT, TIMESTEPPER >::Bulk_mesh_pt private
Pointer to the specific bulk mesh.
Bulk_mesh_pt [5/8]
template<class ELEMENT , class TIMESTEPPER > AnnularSpineMesh<ELEMENT>* InterfaceProblem< ELEMENT, TIMESTEPPER >::Bulk_mesh_pt private
Pointer to bulk mesh.
Bulk_mesh_pt [6/8]
template<class ELEMENT , class TIMESTEPPER > MyHorizontalSingleLayerSpineMesh<ELEMENT>* InterfaceProblem< ELEMENT, TIMESTEPPER >::Bulk_mesh_pt
Access function for the specific mesh.
Bulk_mesh_pt [7/8]
template<class ELEMENT , class TIMESTEPPER > ElasticRectangularQuadMesh<ELEMENT>* InterfaceProblem< ELEMENT, TIMESTEPPER >::Bulk_mesh_pt
Access function for the specific mesh.
Pointer to the (specific) "bulk" mesh.
Bulk_mesh_pt [8/8]
template<class ELEMENT , class TIMESTEPPER > SingleLayerCubicSpineMesh<ELEMENT>* InterfaceProblem< ELEMENT, TIMESTEPPER >::Bulk_mesh_pt private
Pointer to bulk mesh.
Constitutive_law_pt
template<class ELEMENT , class TIMESTEPPER > ConstitutiveLaw * InterfaceProblem< ELEMENT, TIMESTEPPER >::Constitutive_law_pt private
Pointer to the constitutive law.
Document_node_pt
template<class ELEMENT , class TIMESTEPPER > Node * InterfaceProblem< ELEMENT, TIMESTEPPER >::Document_node_pt private
Pointer to a node for documentation purposes.
Node for documentatin.
Referenced by InterfaceProblem< ELEMENT, TIMESTEPPER >::InterfaceProblem().
Height
template<class ELEMENT , class TIMESTEPPER > double InterfaceProblem< ELEMENT, TIMESTEPPER >::Height private
Height of the domain.
Interface_mesh_pt
template<class ELEMENT , class TIMESTEPPER > Mesh * InterfaceProblem< ELEMENT, TIMESTEPPER >::Interface_mesh_pt
Mesh for the free surface (interface) elements.
Referenced by InterfaceProblem< ELEMENT, TIMESTEPPER >::InterfaceProblem().
L_y
template<class ELEMENT , class TIMESTEPPER > double InterfaceProblem< ELEMENT, TIMESTEPPER >::L_y private
Lr
template<class ELEMENT , class TIMESTEPPER > double InterfaceProblem< ELEMENT, TIMESTEPPER >::Lr private
Width of domain.
Lx
template<class ELEMENT , class TIMESTEPPER > double InterfaceProblem< ELEMENT, TIMESTEPPER >::Lx private
Width of domain.
Axial lengths of domain.
Ly
template<class ELEMENT , class TIMESTEPPER > double InterfaceProblem< ELEMENT, TIMESTEPPER >::Ly private
R_max
template<class ELEMENT , class TIMESTEPPER > double InterfaceProblem< ELEMENT, TIMESTEPPER >::R_max private
Axial lengths of domain.
Surface_mesh_pt
template<class ELEMENT , class TIMESTEPPER > Mesh * InterfaceProblem< ELEMENT, TIMESTEPPER >::Surface_mesh_pt
Mesh for the interface elements.
The mesh that contains the free surface elements.
Pointer to the surface mes.
Pointer to the surface mesh.
Pointer to the "surface" mesh.
Referenced by InterfaceProblem< ELEMENT, TIMESTEPPER >::InterfaceProblem().
Trace_file
template<class ELEMENT , class TIMESTEPPER > ofstream InterfaceProblem< ELEMENT, TIMESTEPPER >::Trace_file private
Trace file.
The documentation for this class was generated from the following files:
rayleigh_instability.cc
single_layer_free_surface_axisym.cc
elastic_two_layer_interface_axisym.cc
spine_two_layer_interface_axisym.cc
3d_rayleigh_instability_surfactant.cc
rayleigh_instability_insoluble_surfactant.cc
rayleigh_instability_soluble_surfactant.cc
elastic_single_layer.cc
spine_single_layer.cc
3d_free_surface.cc
elastic_two_layer_interface.cc
spine_two_layer_interface.cc