MercuryDPM: oomph::CumulativeTimings Namespace Reference
oomph::CumulativeTimings Namespace Reference
Namespace for global (cumulative) timings.
Functions
void start (const unsigned &i)
(Re-)start i-th timer
void halt (const unsigned &i)
Halt i-th timer.
double cumulative_time (const unsigned &i)
Report time accumulated by i-th timer.
void reset (const unsigned &i)
Reset i-th timer.
void reset ()
Reset all timers.
void set_ntimers (const unsigned &ntimers)
Set number of timings that can be recorded in parallel.
Variables
Vector< clock_t > Timing
Cumulative timings.
Vector< clock_t > Start_time
Start times of active timers.
Detailed Description
Namespace for global (cumulative) timings.
/////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////
Function Documentation
cumulative_time()
double oomph::CumulativeTimings::cumulative_time (const unsigned & i)
Report time accumulated by i-th timer.
     {
       return double(Timing[i]) / CLOCKS_PER_SEC;
     }
References i, and Timing.
halt()
void oomph::CumulativeTimings::halt (const unsigned & i)
Halt i-th timer.
     {
       Timing[i] += clock() - Start_time[i];
     }
References i, Start_time, and Timing.
reset() [1/2]
void oomph::CumulativeTimings::reset ()
Reset all timers.
     {
       unsigned n = Timing.size();
       for (unsigned i = 0; i < n; i++)
       {
         Timing[i] = clock_t(0.0);
       }
     }
References i, n, and Timing.
reset() [2/2]
void oomph::CumulativeTimings::reset (const unsigned & i)
Reset i-th timer.
     {
       Timing[i] = clock_t(0.0);
     }
References i, and Timing.
set_ntimers()
void oomph::CumulativeTimings::set_ntimers (const unsigned & ntimers)
Set number of timings that can be recorded in parallel.
     {
       Timing.resize(ntimers, clock_t(0.0));
       Start_time.resize(ntimers, clock_t(0.0));
     }
References Start_time, and Timing.
Referenced by oomph::Timer::Timer().
start()
void oomph::CumulativeTimings::start (const unsigned & i)
(Re-)start i-th timer
     {
       Start_time[i] = clock();
     }
References i, and Start_time.
Referenced by PolarNSProblem< ELEMENT >::actions_before_solve(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >::applyThisOnTheLeft(), Eigen::ThreadPoolTempl< Environment >::AssertBounds(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::atInRange(), Eigen::SparseMapBase< Derived, ReadOnlyAccessors >::coeff(), Eigen::SparseMapBase< Derived, WriteAccessors >::coeffRef(), Coil::Coil(), Eigen::internal::BandMatrixBase< Derived >::col(), Eigen::TensorSycl::internal::FullReductionKernelFunctor< Evaluator, OpType, local_range >::compute_reduction(), oomph::RefineableTetgenMesh< ELEMENT >::compute_volume_target(), oomph::RefineableTetMeshBase::compute_volume_target(), Eigen::internal::computeFromTridiagonal_impl(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::conservativeResize(), contraction(), contraction_batch(), contractionABT(), contractionAT(), contractionBT(), contractionRowMajor(), Eigen::ThreadPoolTempl< Environment >::DecodePartition(), Eigen::BDCSVD< MatrixType_, Options_ >::deflation43(), HGridOptimiser::diffEndExpectedCellsIntegral(), HGridOptimiser::diffHExpectedCellsIntegral(), HGridOptimiser::diffHExpectedCellsIntegralCellNumerator(), HGridOptimiser::diffStartExpectedCellsIntegral(), GpuHelper::draw(), Eigen::ThreadPoolTempl< Environment >::EncodePartition(), Eigen::internal::hseq_side_dependent_impl< VectorsType, CoeffsType, Side >::essentialVector(), Eigen::internal::hseq_side_dependent_impl< VectorsType, CoeffsType, OnTheRight >::essentialVector(), HGridOptimiser::expectedCellsIntegral(), HGridOptimiser::expectedCellsIntegralCellDenominator(), HGridOptimiser::expectedCellsIntegralCellNumerator(), oomph::SuperLUSolver::factorise_serial(), FancySpheres::FancySpheres(), Eigen::internal::fdjac1(), finalizeBenchmark(), internal::Colamd::find_ordering(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::findOrInsertCoeff(), for(), internal::Colamd::garbage_collection(), get_time(), helpers::getRealTime(), AreaVTK::getTotalsurfaceAreaFromFile(), HorizontalScrew::HorizontalScrew(), internal::Colamd::init_scoring(), HGridOptimiser::initialisePolyFunc(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertByOuterInner(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertCompressed(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertUncompressed(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::insertUncompressedAtByOuterInner(), oomph::RefineableQElement< 2 >::interpolated_zeta_on_edge(), oomph::RefineableQElement< 3 >::interpolated_zeta_on_face(), Eigen::ThreadPoolTempl< Environment >::LocalSteal(), main(), Eigen::SparseMatrix< Scalar_, Options_, StorageIndex_ >::makeCompressed(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >::operator=(), PolarNSProblem< ELEMENT >::output_streamfunction(), MandelbrotWidget::paintEvent(), Eigen::ForkJoinScheduler::ParallelFor(), Eigen::ForkJoinScheduler::ParallelForAsync(), oomph::METIS::partition_mesh(), HGridOptimiser::pdfInt(), HGridOptimiser::pdfIntCell(), PolarNSProblem< ELEMENT >::pin_boundaries(), PolarNSProblem< ELEMENT >::pin_boundaries_to_zero(), Eigen::RunQueue< Work, kSize >::PopBackHalf(), oomph::BlockTriangularPreconditioner< MATRIX >::preconditioner_solve(), oomph::BandedBlockTriangularPreconditioner< MATRIX >::preconditioner_solve(), oomph::PseudoElasticPreconditionerSubsidiaryBlockPreconditionerOld::preconditioner_solve(), Eigen::internal::InnerMostDimReducer< Self, Op, true, false >::reduce(), MandelbrotThread::render(), Eigen::internal::smart_copy_helper< T, true >::run(), Eigen::internal::smart_copy_helper< T, false >::run(), Eigen::internal::smart_memmove_helper< T, true >::run(), Eigen::internal::smart_memmove_helper< T, false >::run(), Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, true, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, ResInnerStride, Version >::run(), Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheLeft, Mode, Conjugate, TriStorageOrder, ColMajor, OtherInnerStride >::run(), Eigen::internal::unaligned_dense_assignment_loop< false >::run(), Eigen::ForkJoinScheduler::RunParallelForAsync(), Eigen::ThreadPoolTempl< Environment >::ScheduleWithHint(), Screw::Screw(), Eigen::internal::CompressedStorage< Scalar_, StorageIndex_ >::searchLowerIndex(), segmentFromRange(), Coil::set(), Eigen::internal::AmbiVector< Scalar_, StorageIndex_ >::setBounds(), HorizontalMixer::setScrewWalls(), Eigen::ThreadPoolTempl< Environment >::SetStealPartitions(), TriangulatedScrewSelfTest::setupInitialConditions(), skinnyTensor_col(), skinnyTensor_row(), Eigen::internal::smart_copy(), Eigen::internal::smart_memmove(), Eigen::internal::smart_move(), CGCoordinates::spaceEvenly(), sparse_basic(), Eigen::ThreadPoolTempl< Environment >::Steal(), tensor_contraction_batch_per_device(), tensor_contraction_both_transposed_per_device(), tensor_contraction_lhs_transposed_per_device(), tensor_contraction_rhs_transposed_per_device(), tensorOutofBound(), tensorScalar(), tensorTensor(), tensorTensor_k(), tensorTensor_m(), tensorTensor_n(), tensorTensor_sizes(), tensorVector(), test_strided_slice(), Eigen::internal::tridiagonal_qr_step(), vectorTensor(), and vectorVector().
Variable Documentation
Start_time
Vector< clock_t > oomph::CumulativeTimings::Start_time
Start times of active timers.
Referenced by halt(), oomph::Timer::halt(), set_ntimers(), oomph::Timer::set_ntimers(), start(), and oomph::Timer::start().
Timing
Vector< clock_t > oomph::CumulativeTimings::Timing
Cumulative timings.
Referenced by cumulative_time(), oomph::Timer::cumulative_time(), halt(), oomph::Timer::halt(), reset(), oomph::Timer::reset(), set_ntimers(), and oomph::Timer::set_ntimers().