MercuryDPM: fsi_osc_ring.cc File Reference
mpi/multi_domain/fsi_osc_ring/fsi_osc_ring.cc File Reference
#include "generic.h"
#include "navier_stokes.h"
#include "beam.h"
#include "meshes/quarter_circle_sector_mesh.h"
#include "meshes/one_d_lagrangian_mesh.h"
Classes
class FSIRingProblem
Namespaces
Global_Physical_Variables
Global variables.
Functions
void Global_Physical_Variables::set_params ()
void Global_Physical_Variables::pcos_load (const Vector< double > &xi, const Vector< double > &x, const Vector< double > &N, Vector< double > &load)
int main (int argc, char *argv[])
Driver for fsi ring test problem.
Function Documentation
main()
int main (int argc , char * argv[])
Driver for fsi ring test problem.
Perturbation pressure
Duration of initial pcos perturbation
Amplitude of initial deformation
 {
 #ifdef OOMPH_HAS_MPI
  MPI_Helpers::init(argc,argv);
 #endif
   // Switch off output modifier
  oomph_info.output_modifier_pt() = &default_output_modifier;
  // Define processor-labeled output file for all on-screen stuff
  std::ofstream output_stream;
  char filename[100];
  sprintf(filename,"OUTPUT.%i",MPI_Helpers::communicator_pt()->my_rank());
  output_stream.open(filename);
  oomph_info.stream_pt() = &output_stream;
  OomphLibWarning::set_stream_pt(&output_stream);
  OomphLibError::set_stream_pt(&output_stream);
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Number of elements
  unsigned nelem = 13;
  double pcos_initial=1.0e-6; // ADJUST
  double pcos_duration=0.3; // ADJUST
  double eps_ampl=0.0; // ADJUST
  //Set up the problem
  FSIRingProblem* problem_pt
   = new FSIRingProblem(nelem,eps_ampl,pcos_initial,pcos_duration);
  // Do parameter study
  problem_pt->dynamic_run();
  // clean
 // delete problem_pt;
 #ifdef OOMPH_HAS_MPI
  MPI_Helpers::finalize();
 #endif
 }
References oomph::default_output_modifier, FSIRingProblem::dynamic_run(), MergeRestartFiles::filename, FSIRingProblem::FSIRingProblem(), oomph::oomph_info, oomph::OomphInfo::output_modifier_pt(), Flag_definition::setup(), and oomph::OomphInfo::stream_pt().