MercuryDPM: Eigen::TensorEvaluator< const TensorInflationOp< Strides, ArgType >, Device > Struct Template Reference
Eigen::TensorEvaluator< const TensorInflationOp< Strides, ArgType >, Device > Struct Template Reference
#include <TensorInflation.h>
Public Types
enum {
IsAligned = false , PacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess , BlockAccess = false , PreferBlockAccess = false ,
CoordAccess = false , RawAccess = false
}
typedef TensorInflationOp< Strides, ArgType > XprType
typedef XprType::Index Index
typedef DSizes< Index, NumDims > Dimensions
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef StorageMemory< CoeffReturnType, Device > Storage
typedef Storage::Type EvaluatorPointerType
typedef internal::TensorBlockNotImplemented TensorBlock
Public Member Functions
EIGEN_STRONG_INLINE TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions & dimensions () const
EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (EvaluatorPointerType)
EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool getInputIndex (Index index, Index *inputIndex) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType packet (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
EIGEN_DEVICE_FUNC EvaluatorPointerType data () const
Static Public Attributes
static constexpr int NumDims = internal::array_size<typename TensorEvaluator<ArgType, Device>::Dimensions>::value
static constexpr int PacketSize = PacketType<CoeffReturnType, Device>::size
static constexpr int Layout = TensorEvaluator<ArgType, Device>::Layout
Protected Attributes
Dimensions m_dimensions
array< Index, NumDims > m_outputStrides
array< Index, NumDims > m_inputStrides
TensorEvaluator< ArgType, Device > m_impl
const Strides m_strides
array< internal::TensorIntDivisor< Index >, NumDims > m_fastStrides
Member Typedef Documentation
CoeffReturnType
template<typename Strides , typename ArgType , typename Device > typedef XprType::CoeffReturnType Eigen::TensorEvaluator< const TensorInflationOp< Strides, ArgType >, Device >::CoeffReturnType
Dimensions
template<typename Strides , typename ArgType , typename Device > typedef DSizes<Index, NumDims> Eigen::TensorEvaluator< const TensorInflationOp< Strides, ArgType >, Device >::Dimensions
EvaluatorPointerType
template<typename Strides , typename ArgType , typename Device > typedef Storage::Type Eigen::TensorEvaluator< const TensorInflationOp< Strides, ArgType >, Device >::EvaluatorPointerType
Index
template<typename Strides , typename ArgType , typename Device > typedef XprType::Index Eigen::TensorEvaluator< const TensorInflationOp< Strides, ArgType >, Device >::Index
PacketReturnType
template<typename Strides , typename ArgType , typename Device > typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorEvaluator< const TensorInflationOp< Strides, ArgType >, Device >::PacketReturnType
Scalar
template<typename Strides , typename ArgType , typename Device > typedef XprType::Scalar Eigen::TensorEvaluator< const TensorInflationOp< Strides, ArgType >, Device >::Scalar
Storage
template<typename Strides , typename ArgType , typename Device > typedef StorageMemory<CoeffReturnType, Device> Eigen::TensorEvaluator< const TensorInflationOp< Strides, ArgType >, Device >::Storage
TensorBlock
template<typename Strides , typename ArgType , typename Device > typedef internal::TensorBlockNotImplemented Eigen::TensorEvaluator< const TensorInflationOp< Strides, ArgType >, Device >::TensorBlock
XprType
template<typename Strides , typename ArgType , typename Device > typedef TensorInflationOp<Strides, ArgType> Eigen::TensorEvaluator< const TensorInflationOp< Strides, ArgType >, Device >::XprType
Member Enumeration Documentation
anonymous enum
template<typename Strides , typename ArgType , typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
BlockAccess
PreferBlockAccess
CoordAccess
RawAccess
        {
     IsAligned = /*TensorEvaluator<ArgType, Device>::IsAligned*/ false,
     PacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess,
     BlockAccess = false,
     PreferBlockAccess = false,
     CoordAccess = false,  // to be implemented
     RawAccess = false
   };
Constructor & Destructor Documentation
TensorEvaluator()
template<typename Strides , typename ArgType , typename Device > EIGEN_STRONG_INLINE Eigen::TensorEvaluator< const TensorInflationOp< Strides, ArgType >, Device >::TensorEvaluator (const XprType & op, const Device & device) inline
       : m_impl(op.expression(), device), m_strides(op.strides()) {
     m_dimensions = m_impl.dimensions();
     // Expand each dimension to the inflated dimension.
     for (int i = 0; i < NumDims; ++i) {
       m_dimensions[i] = (m_dimensions[i] - 1) * op.strides()[i] + 1;
     }
     // Remember the strides for fast division.
     for (int i = 0; i < NumDims; ++i) {
       m_fastStrides[i] = internal::TensorIntDivisor<Index>(m_strides[i]);
     }
     const typename TensorEvaluator<ArgType, Device>::Dimensions& input_dims = m_impl.dimensions();
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       m_outputStrides[0] = 1;
       m_inputStrides[0] = 1;
       for (int i = 1; i < NumDims; ++i) {
         m_outputStrides[i] = m_outputStrides[i - 1] * m_dimensions[i - 1];
         m_inputStrides[i] = m_inputStrides[i - 1] * input_dims[i - 1];
       }
     } else {  // RowMajor
       m_outputStrides[NumDims - 1] = 1;
       m_inputStrides[NumDims - 1] = 1;
       for (int i = NumDims - 2; i >= 0; --i) {
         m_outputStrides[i] = m_outputStrides[i + 1] * m_dimensions[i + 1];
         m_inputStrides[i] = m_inputStrides[i + 1] * input_dims[i + 1];
       }
     }
   }
References Eigen::ColMajor, Eigen::TensorEvaluator< Derived, Device >::dimensions(), i, Eigen::TensorEvaluator< Derived, Device >::Layout, and op.
Member Function Documentation
cleanup()
template<typename Strides , typename ArgType , typename Device > EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorInflationOp< Strides, ArgType >, Device >::cleanup () inline
 { m_impl.cleanup(); }
Referenced by framework.Frame::__init__().
coeff()
template<typename Strides , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::TensorEvaluator< const TensorInflationOp< Strides, ArgType >, Device >::coeff (Index index) const inline
{
     Index inputIndex = 0;
     if (getInputIndex(index, &inputIndex)) {
       return m_impl.coeff(inputIndex);
     } else {
       return Scalar(0);
     }
   }
costPerCoeff()
template<typename Strides , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorEvaluator< const TensorInflationOp< Strides, ArgType >, Device >::costPerCoeff (bool vectorized) const inline
{
     const double compute_cost = NumDims * (3 * TensorOpCost::DivCost<Index>() + 3 * TensorOpCost::MulCost<Index>() +
                                            2 * TensorOpCost::AddCost<Index>());
     const double input_size = m_impl.dimensions().TotalSize();
     const double output_size = m_dimensions.TotalSize();
     if (output_size == 0) return TensorOpCost();
     return m_impl.costPerCoeff(vectorized) +
            TensorOpCost(sizeof(CoeffReturnType) * input_size / output_size, 0, compute_cost, vectorized, PacketSize);
   }
References Eigen::TensorEvaluator< Derived, Device >::PacketSize.
data()
template<typename Strides , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EvaluatorPointerType Eigen::TensorEvaluator< const TensorInflationOp< Strides, ArgType >, Device >::data () const inline
 { return NULL; }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
dimensions()
template<typename Strides , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions& Eigen::TensorEvaluator< const TensorInflationOp< Strides, ArgType >, Device >::dimensions () const inline
 { return m_dimensions; }
evalSubExprsIfNeeded()
template<typename Strides , typename ArgType , typename Device > EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorInflationOp< Strides, ArgType >, Device >::evalSubExprsIfNeeded (EvaluatorPointerType) inline
{
     m_impl.evalSubExprsIfNeeded(NULL);
     return true;
   }
getInputIndex()
template<typename Strides , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorInflationOp< Strides, ArgType >, Device >::getInputIndex (Index index, Index * inputIndex) const inline
{
     eigen_assert(index < dimensions().TotalSize());
     *inputIndex = 0;
     if (static_cast<int>(Layout) == static_cast<int>(ColMajor)) {
       EIGEN_UNROLL_LOOP
       for (int i = NumDims - 1; i > 0; --i) {
         const Index idx = index / m_outputStrides[i];
         if (idx != idx / m_fastStrides[i] * m_strides[i]) {
           return false;
         }
         *inputIndex += idx / m_strides[i] * m_inputStrides[i];
         index -= idx * m_outputStrides[i];
       }
       if (index != index / m_fastStrides[0] * m_strides[0]) {
         return false;
       }
       *inputIndex += index / m_strides[0];
       return true;
     } else {
       EIGEN_UNROLL_LOOP
       for (int i = 0; i < NumDims - 1; ++i) {
         const Index idx = index / m_outputStrides[i];
         if (idx != idx / m_fastStrides[i] * m_strides[i]) {
           return false;
         }
         *inputIndex += idx / m_strides[i] * m_inputStrides[i];
         index -= idx * m_outputStrides[i];
       }
       if (index != index / m_fastStrides[NumDims - 1] * m_strides[NumDims - 1]) {
         return false;
       }
       *inputIndex += index / m_strides[NumDims - 1];
     }
     return true;
   }
References Eigen::ColMajor, Eigen::TensorEvaluator< Derived, Device >::dimensions(), eigen_assert, EIGEN_UNROLL_LOOP, i, and Eigen::TensorEvaluator< Derived, Device >::Layout.
packet()
template<typename Strides , typename ArgType , typename Device > template<int LoadMode> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType Eigen::TensorEvaluator< const TensorInflationOp< Strides, ArgType >, Device >::packet (Index index) const inline
{
     EIGEN_STATIC_ASSERT((PacketSize > 1), YOU_MADE_A_PROGRAMMING_MISTAKE)
     eigen_assert(index + PacketSize - 1 < dimensions().TotalSize());
     EIGEN_ALIGN_MAX std::remove_const_t<CoeffReturnType> values[PacketSize];
     EIGEN_UNROLL_LOOP
     for (int i = 0; i < PacketSize; ++i) {
       values[i] = coeff(index + i);
     }
     PacketReturnType rslt = internal::pload<PacketReturnType>(values);
     return rslt;
   }
References Eigen::TensorEvaluator< Derived, Device >::coeff(), Eigen::TensorEvaluator< Derived, Device >::dimensions(), EIGEN_ALIGN_MAX, eigen_assert, EIGEN_STATIC_ASSERT, EIGEN_UNROLL_LOOP, i, and Eigen::TensorEvaluator< Derived, Device >::PacketSize.
Member Data Documentation
Layout
template<typename Strides , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorInflationOp< Strides, ArgType >, Device >::Layout = TensorEvaluator<ArgType, Device>::Layout static constexpr
m_dimensions
template<typename Strides , typename ArgType , typename Device > Dimensions Eigen::TensorEvaluator< const TensorInflationOp< Strides, ArgType >, Device >::m_dimensions protected
m_fastStrides
template<typename Strides , typename ArgType , typename Device > array<internal::TensorIntDivisor<Index>, NumDims> Eigen::TensorEvaluator< const TensorInflationOp< Strides, ArgType >, Device >::m_fastStrides protected
m_impl
template<typename Strides , typename ArgType , typename Device > TensorEvaluator<ArgType, Device> Eigen::TensorEvaluator< const TensorInflationOp< Strides, ArgType >, Device >::m_impl protected
m_inputStrides
template<typename Strides , typename ArgType , typename Device > array<Index, NumDims> Eigen::TensorEvaluator< const TensorInflationOp< Strides, ArgType >, Device >::m_inputStrides protected
m_outputStrides
template<typename Strides , typename ArgType , typename Device > array<Index, NumDims> Eigen::TensorEvaluator< const TensorInflationOp< Strides, ArgType >, Device >::m_outputStrides protected
m_strides
template<typename Strides , typename ArgType , typename Device > const Strides Eigen::TensorEvaluator< const TensorInflationOp< Strides, ArgType >, Device >::m_strides protected
NumDims
template<typename Strides , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorInflationOp< Strides, ArgType >, Device >::NumDims = internal::array_size<typename TensorEvaluator<ArgType, Device>::Dimensions>::value static constexpr
PacketSize
template<typename Strides , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< const TensorInflationOp< Strides, ArgType >, Device >::PacketSize = PacketType<CoeffReturnType, Device>::size static constexpr
The documentation for this struct was generated from the following file:
TensorInflation.h