MercuryDPM: linear_solid_contact_with_gravity.cc File Reference
linear_solid_contact_with_gravity.cc File Reference
#include <fenv.h>
#include "generic.h"
#include "solid.h"
#include "linear_elasticity.h"
#include "meshes/triangle_mesh.h"
#include "meshes/rectangular_quadmesh.h"
#include "contact_elements.h"
Classes
class FiniteElementComp
class WarpedLine
Warped line in 2D space.
class CircularPenetratorElement
class ContactProblem< ELEMENT >
Problem class.
Namespaces
ProblemParameters
Namespace for exact solution and problem parameters.
Functions
void ProblemParameters::body_force (const double &time, const Vector< double > &x, Vector< double > &result)
The body force function.
int main (int argc, char *argv[])
Driver code.
Variables
double ProblemParameters::Body_force_amplitude =0.0
Body force magnitude.
double ProblemParameters::Body_force_alpha =1.0e4
WarpedLine ProblemParameters::Boundary_geom_object_left (1.0e-10, 0.0, X_contact_end_left)
WarpedLine ProblemParameters::Boundary_geom_object_contact (1.0e-10, X_contact_end_left, X_contact_end_right)
WarpedLine ProblemParameters::Boundary_geom_object_right (1.0e-10, X_contact_end_right, 1.0)
IsotropicElasticityTensor ProblemParameters::E (Nu)
The elasticity tensor.
Function Documentation
main()
int main (int argc , char * argv[])
Driver code.
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////
 {
  FiniteElement::Accept_negative_jacobian=true;
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Define possible command line arguments and parse the ones that
  // were actually specified
  // Suppress adaptation
  CommandLineArgs::specify_command_line_flag("--no_adapt");
  // Initial element size
  CommandLineArgs::specify_command_line_flag("--el_area",
                                             &ProblemParameters::El_area);
  // Suppress adaptation
  CommandLineArgs::specify_command_line_flag("--validate");
  // Parse command line
  CommandLineArgs::parse_and_assign();
  // Doc what has actually been specified on the command line
  CommandLineArgs::doc_specified_flags();
  // Create generalised Hookean constitutive equations
  ProblemParameters::Constitutive_law_pt =
   new GeneralisedHookean(&ProblemParameters::Nu);
  // Define centre of penetrator
  ProblemParameters::Centre.resize(2);
  ProblemParameters::Centre[0]=0.5;
  ProblemParameters::Centre[1]=1.0+ProblemParameters::Radius;
  // Build penetrator
  ProblemParameters::Penetrator_pt =
   new CircularPenetrator(&ProblemParameters::Centre,
                          ProblemParameters::Radius);
 #ifdef STRUCTURED_MESH
  // Build problem
  ContactProblem<RefineablePseudoSolidNodeUpdateElement<
   RefineableQLinearElasticityElement<2,3>,
   RefineableQPVDElement<2,3> > >
   problem;
 #else
  // Build problem
  ContactProblem
   <ProjectableLinearElasticityElement<
  PseudoSolidNodeUpdateElement<TLinearElasticityElement<2,3>,
                               TPVDElement<2,3> > > > problem;
 #endif
  // Pure imposed displacement of upper surface -- no contact
  //---------------------------------------------------------
  {
   // Doc initial domain shape
   problem.doc_solution();
   // Max. number of adaptations per solve
   unsigned max_adapt=1;
   //Parameter incrementation
   unsigned nstep=2;
   for(unsigned i=0;i<nstep;i++)
    {
     double d_ampl=0.05;
     double ampl=0.0;
 #ifdef STRUCTURED_MESH
     // Increment imposed boundary displacement
     ProblemParameters::Boundary_geom_object.ampl()+=d_ampl;
     ampl=ProblemParameters::Boundary_geom_object.ampl();
 #else
     // Increment imposed boundary displacement
     ProblemParameters::Boundary_geom_object_left.ampl()+=d_ampl;
     ProblemParameters::Boundary_geom_object_contact.ampl()+=d_ampl;
     ProblemParameters::Boundary_geom_object_right.ampl()+=d_ampl;
     ampl=ProblemParameters::Boundary_geom_object_contact.ampl();
 #endif
     oomph_info << "Re-solving for prescr displ amplitude = "
                << ampl << std::endl;
     // Solve the problem with Newton's method, allowing
     // up to max_adapt mesh adaptations after every solve.
     problem.newton_solve(max_adapt);
     // Doc solution
     problem.doc_solution();
    }
  }
 #ifdef STRUCTURED_MESH
  ProblemParameters::Centre[1]=
   ProblemParameters::Boundary_geom_object.y_c()-
   ProblemParameters::Boundary_geom_object.radius()+
   ProblemParameters::Radius;
 #else
  ProblemParameters::Centre[1]=
   ProblemParameters::Boundary_geom_object_contact.y_c()-
   ProblemParameters::Boundary_geom_object_contact.radius()+
   ProblemParameters::Radius;
 #endif
   //Output initial condition
  problem.doc_solution();
  unsigned max_adapt=1;
  if (CommandLineArgs::command_line_flag_has_been_set("--no_adapt"))
   {
    max_adapt=0;
   }
  // Move position of centre directly
  //----------------------------------
  double dyc=0.00024;
  unsigned nstep=3;
  for (unsigned i=0;i<nstep;i++)
   {
    ProblemParameters::Centre[1]-=dyc;
    oomph_info << "Re-solving imposed circle pos for yc="
               << ProblemParameters::Centre[1]
               << std::endl;
    // Solve
    problem.newton_solve(max_adapt);
    //Output solution
    problem.doc_solution();
   }
  // Now increase resolution
  //------------------------
  nstep=3;
  for (unsigned i=0;i<nstep;i++)
  {
   oomph_info << "Re-solving imposed circle pos for element length factor: "
              << ProblemParameters::Element_length_factor
              << std::endl;
   // Re-solve
   problem.newton_solve(max_adapt);
   //Output solution
   problem.doc_solution();
   // Refine
   ProblemParameters::Element_length_factor/=2.0;
  }
  // Switch to node control
  ProblemParameters::Impose_position_of_centre=false;
  // Use displacement control initially
  //-----------------------------------
  problem.adapt();
  problem.switch_to_displ_control();
  dyc=0.0003;
  nstep=1;
  for (unsigned i=0;i<nstep;i++)
   {
    ProblemParameters::Y_c-=dyc;
    oomph_info << "Re-solving for yc="
               << ProblemParameters::Y_c
               << std::endl;
    // Solve
    problem.newton_solve(max_adapt);
    //Output solution
    problem.doc_solution();
   }
  // Switch to force control
  problem.switch_to_force_control();
  // Balance it in the horizontal direction
  //---------------------------------------
  ProblemParameters::Horizontal_force=0.0;
  oomph_info << "RE-solving for weight="
             << dynamic_cast<CircularPenetratorElement*>(
              ProblemParameters::Penetrator_pt)->target_weight()
             << " and horizontal force: "
             << dynamic_cast<CircularPenetratorElement*>(
              ProblemParameters::Penetrator_pt)->target_horizontal_force()
             << std::endl;
  // Re-solve
  problem.newton_solve(max_adapt);
  //Output solution
  problem.doc_solution();
  // Now increase weight
  //--------------------
  double dweight=0.0001;
  nstep=1;
  for (unsigned i=0;i<nstep;i++)
   {
    oomph_info << "Re-solving for weight="
               << dynamic_cast<CircularPenetratorElement*>(
                ProblemParameters::Penetrator_pt)->target_weight()
               << " and horizontal force: "
               << dynamic_cast<CircularPenetratorElement*>(
                ProblemParameters::Penetrator_pt)->target_horizontal_force()
               << std::endl;
    // Re-solve
    problem.newton_solve(max_adapt);
    //Output solution
    problem.doc_solution();
    // Increase weight
    ProblemParameters::Weight+=dweight;
   }
 // Now detach elastic body
 //------------------------
  nstep=3;
  double d_lift_off_ampl=0.0001;
  for (unsigned i=0;i<nstep;i++)
   {
    double lift_off=0.0;
 #ifdef STRUCTURED_MESH
     // Increment imposed boundary displacement
     ProblemParameters::Boundary_geom_object.lift_off_amplitude()+=
      d_lift_off_ampl;
     lift_off=ProblemParameters::Boundary_geom_object.lift_off_amplitude();
 #else
     // Increment imposed boundary displacement
     ProblemParameters::Boundary_geom_object_left.lift_off_amplitude()+=
      d_lift_off_ampl;
     ProblemParameters::Boundary_geom_object_contact.lift_off_amplitude()+=
      d_lift_off_ampl;
     ProblemParameters::Boundary_geom_object_right.lift_off_amplitude()+=
      d_lift_off_ampl;
     lift_off=ProblemParameters::Boundary_geom_object_contact.
      lift_off_amplitude();
 #endif
   oomph_info << "Re-solving for weight="
               << dynamic_cast<CircularPenetratorElement*>(
                ProblemParameters::Penetrator_pt)->target_weight()
               << " and horizontal force: "
               << dynamic_cast<CircularPenetratorElement*>(
                ProblemParameters::Penetrator_pt)->target_horizontal_force()
               << " and lift off: "
               << lift_off
               << std::endl;
   // Re-solve
   problem.newton_solve(max_adapt);
   //Output solution
   problem.doc_solution();
  }
 }
References WarpedLine::ampl(), Global_Physical_Variables::Boundary_geom_object, ProblemParameters::Boundary_geom_object_contact, ProblemParameters::Boundary_geom_object_left, ProblemParameters::Boundary_geom_object_right, ProblemParameters::Centre, oomph::CommandLineArgs::command_line_flag_has_been_set(), ProblemParameters::Constitutive_law_pt, oomph::CommandLineArgs::doc_specified_flags(), ProblemParameters::El_area, ProblemParameters::Element_length_factor, ProblemParameters::Horizontal_force, i, ProblemParameters::Impose_position_of_centre, WarpedLine::lift_off_amplitude(), ProblemParameters::Nu, oomph::oomph_info, oomph::CommandLineArgs::parse_and_assign(), ProblemParameters::Penetrator_pt, problem, ProblemParameters::Radius, WarpedLine::radius(), Flag_definition::setup(), oomph::CommandLineArgs::specify_command_line_flag(), ProblemParameters::Weight, WarpedLine::y_c(), and ProblemParameters::Y_c.