MercuryDPM: Eigen::internal::dhs_pack< double, DataMapper, Packet2d, StorageOrder, PanelMode, false > Struct Template Reference
Eigen::internal::dhs_pack< double, DataMapper, Packet2d, StorageOrder, PanelMode, false > Struct Template Reference
#include <MatrixProduct.h>
Public Member Functions
template<Index n>
EIGEN_ALWAYS_INLINE void dhs_copy (double *blockB, const DataMapper &rhs2, Index &i, Index &ri, Index depth, const Index vectorSize)
EIGEN_STRONG_INLINE void operator() (double *blockB, const DataMapper &rhs, Index depth, Index cols, Index stride, Index offset)
Member Function Documentation
dhs_copy()
template<typename DataMapper , int StorageOrder, bool PanelMode> template<Index n> EIGEN_ALWAYS_INLINE void Eigen::internal::dhs_pack< double, DataMapper, Packet2d, StorageOrder, PanelMode, false >::dhs_copy (double * blockB, const DataMapper & rhs2, Index & i, Index & ri, Index depth, const Index vectorSize) inline
{
     PacketBlock<Packet2d, 2> block1[n], block2[n];
     PacketBlock<Packet2d, 4> block3[n];
     for (; i + n * vectorSize <= depth; i += n * vectorSize) {
       for (Index k = 0; k < n; k++) {
         if (StorageOrder == ColMajor) {
           block1[k].packet[0] = rhs2.template loadPacket<Packet2d>(i + k * vectorSize, 0);
           block1[k].packet[1] = rhs2.template loadPacket<Packet2d>(i + k * vectorSize, 1);
           block2[k].packet[0] = rhs2.template loadPacket<Packet2d>(i + k * vectorSize, 2);
           block2[k].packet[1] = rhs2.template loadPacket<Packet2d>(i + k * vectorSize, 3);
         } else {
           block3[k].packet[0] = rhs2.template loadPacket<Packet2d>(i + k * vectorSize + 0, 0);  //[a1 a2]
           block3[k].packet[1] = rhs2.template loadPacket<Packet2d>(i + k * vectorSize + 0, 2);  //[a3 a4]
           block3[k].packet[2] = rhs2.template loadPacket<Packet2d>(i + k * vectorSize + 1, 0);  //[b1 b2]
           block3[k].packet[3] = rhs2.template loadPacket<Packet2d>(i + k * vectorSize + 1, 2);  //[b3 b4]
         }
       }
       if (StorageOrder == ColMajor) {
         for (Index k = 0; k < n; k++) {
           ptranspose(block1[k]);
           ptranspose(block2[k]);
         }
       }
       for (Index k = 0; k < n; k++) {
         if (StorageOrder == ColMajor) {
           pstore<double>(blockB + ri + k * 4 * vectorSize, block1[k].packet[0]);
           pstore<double>(blockB + ri + k * 4 * vectorSize + 2, block2[k].packet[0]);
           pstore<double>(blockB + ri + k * 4 * vectorSize + 4, block1[k].packet[1]);
           pstore<double>(blockB + ri + k * 4 * vectorSize + 6, block2[k].packet[1]);
         } else {
           storeBlock<double, Packet2d, 4>(blockB + ri + k * 4 * vectorSize, block3[k]);
         }
       }
       ri += n * 4 * vectorSize;
     }
   }
References Eigen::ColMajor, i, k, n, Eigen::internal::PacketBlock< Packet, N >::packet, Eigen::internal::pstore< double >(), and Eigen::internal::ptranspose().
operator()()
template<typename DataMapper , int StorageOrder, bool PanelMode> EIGEN_STRONG_INLINE void Eigen::internal::dhs_pack< double, DataMapper, Packet2d, StorageOrder, PanelMode, false >::operator() (double * blockB, const DataMapper & rhs, Index depth, Index cols, Index stride, Index offset) inline
{
     const Index vectorSize = quad_traits<double>::vectorsize;
     Index ri = 0, j = 0;
     for (; j + 2 * vectorSize <= cols; j += 2 * vectorSize) {
       const DataMapper rhs2 = rhs.getSubMapper(0, j);
       Index i = 0;
       if (PanelMode) ri += offset * (2 * vectorSize);
       dhs_copy<4>(blockB, rhs2, i, ri, depth, vectorSize);
       dhs_copy<2>(blockB, rhs2, i, ri, depth, vectorSize);
       dhs_copy<1>(blockB, rhs2, i, ri, depth, vectorSize);
       for (; i < depth; i++) {
         if (StorageOrder == ColMajor) {
           blockB[ri + 0] = rhs2(i, 0);
           blockB[ri + 1] = rhs2(i, 1);
           ri += vectorSize;
           blockB[ri + 0] = rhs2(i, 2);
           blockB[ri + 1] = rhs2(i, 3);
         } else {
           Packet2d rhsV = rhs2.template loadPacket<Packet2d>(i, 0);
           pstore<double>(blockB + ri, rhsV);
           ri += vectorSize;
           rhsV = rhs2.template loadPacket<Packet2d>(i, 2);
           pstore<double>(blockB + ri, rhsV);
         }
         ri += vectorSize;
       }
       if (PanelMode) ri += (2 * vectorSize) * (stride - offset - depth);
     }
     if (PanelMode) ri += offset;
     for (; j < cols; j++) {
       const DataMapper rhs2 = rhs.getSubMapper(0, j);
       for (Index i = 0; i < depth; i++) {
         blockB[ri] = rhs2(i, 0);
         ri += 1;
       }
       if (PanelMode) ri += stride - depth;
     }
   }
References Eigen::ColMajor, cols, i, j, and Eigen::internal::pstore< double >().
The documentation for this struct was generated from the following file:
MatrixProduct.h