MercuryDPM: oomph::HelmholtzBCElementBase< ELEMENT > Class Template Reference
oomph::HelmholtzBCElementBase< ELEMENT > Class Template Reference
#include <helmholtz_bc_elements.h>
Public Member Functions
HelmholtzBCElementBase (FiniteElement *const &bulk_el_pt, const int &face_index)
Constructor, takes the pointer to the "bulk" element and the face index.
HelmholtzBCElementBase ()
Broken empty constructor.
HelmholtzBCElementBase (const HelmholtzBCElementBase &dummy)=delete
Broken copy constructor.
double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
Broken assignment operator.
void output (std::ostream &outfile)
void output (std::ostream &outfile, const unsigned &n_plot)
void output (FILE *file_pt)
void output (FILE *file_pt, const unsigned &n_plot)
virtual std::complex< unsigned > u_index_helmholtz () const
double global_power_contribution ()
double global_power_contribution (std::ofstream &outfile)
void compute_contribution_to_fourier_components (Vector< std::complex< double >> &a_coeff_pos, Vector< std::complex< double >> &a_coeff_neg)
Public Member Functions inherited from oomph::FaceElement
FaceElement ()
Constructor: Initialise all appropriate member data.
virtual ~FaceElement ()
Empty virtual destructor.
FaceElement (const FaceElement &)=delete
Broken copy constructor.
const unsigned & boundary_number_in_bulk_mesh () const
Broken assignment operator.
void set_boundary_number_in_bulk_mesh (const unsigned &b)
Set function for the boundary number in bulk mesh.
double J_eulerian (const Vector< double > &s) const
double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
double interpolated_x (const Vector< double > &s, const unsigned &i) const
double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
void interpolated_x (const Vector< double > &s, Vector< double > &x) const
void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
int & normal_sign ()
int normal_sign () const
int & face_index ()
int face_index () const
const Vector< double > * tangent_direction_pt () const
Public access function for the tangent direction pointer.
void set_tangent_direction (Vector< double > *tangent_direction_pt)
Set the tangent direction vector.
void turn_on_warning_for_discontinuous_tangent ()
void turn_off_warning_for_discontinuous_tangent ()
void continuous_tangent_and_outer_unit_normal (const Vector< double > &s, Vector< Vector< double >> &tang_vec, Vector< double > &unit_normal) const
void continuous_tangent_and_outer_unit_normal (const unsigned &ipt, Vector< Vector< double >> &tang_vec, Vector< double > &unit_normal) const
void outer_unit_normal (const Vector< double > &s, Vector< double > &unit_normal) const
Compute outer unit normal at the specified local coordinate.
void outer_unit_normal (const unsigned &ipt, Vector< double > &unit_normal) const
Compute outer unit normal at ipt-th integration point.
FiniteElement *& bulk_element_pt ()
Pointer to higher-dimensional "bulk" element.
FiniteElement * bulk_element_pt () const
Pointer to higher-dimensional "bulk" element (const version)
CoordinateMappingFctPt & face_to_bulk_coordinate_fct_pt ()
CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt () const
BulkCoordinateDerivativesFctPt & bulk_coordinate_derivatives_fct_pt ()
BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt () const
Vector< double > local_coordinate_in_bulk (const Vector< double > &s) const
void get_local_coordinate_in_bulk (const Vector< double > &s, Vector< double > &s_bulk) const
void get_ds_bulk_ds_face (const Vector< double > &s, DenseMatrix< double > &dsbulk_dsface, unsigned &interior_direction) const
unsigned & bulk_position_type (const unsigned &i)
const unsigned & bulk_position_type (const unsigned &i) const
void bulk_node_number_resize (const unsigned &i)
Resize the storage for the bulk node numbers.
unsigned & bulk_node_number (const unsigned &n)
const unsigned & bulk_node_number (const unsigned &n) const
void bulk_position_type_resize (const unsigned &i)
Resize the storage for bulk_position_type to i entries.
unsigned & nbulk_value (const unsigned &n)
unsigned nbulk_value (const unsigned &n) const
void nbulk_value_resize (const unsigned &i)
void resize_nodes (Vector< unsigned > &nadditional_data_values)
void output_zeta (std::ostream &outfile, const unsigned &nplot)
Output boundary coordinate zeta.
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
virtual bool local_coord_is_valid (const Vector< double > &s)
Broken assignment operator.
virtual void move_local_coord_back_into_element (Vector< double > &s) const
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
virtual void local_coordinate_of_node (const unsigned &j, Vector< double > &s) const
virtual void local_fraction_of_node (const unsigned &j, Vector< double > &s_fraction)
virtual double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
virtual void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape (const Vector< double > &s, Shape &psi) const =0
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsids) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
virtual unsigned nnode_1d () const
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
virtual void disable_ALE ()
virtual void enable_ALE ()
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual unsigned nvertex_node () const
virtual Node * vertex_node_pt (const unsigned &j) const
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
virtual Node * get_node_at_local_coordinate (const Vector< double > &s) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual ElementGeometry::ElementGeometry element_geometry () const
Return the geometry type of the element (either Q or T usually).
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output an exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output a time-dependent exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
virtual unsigned nnode_on_face () const
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Protected Member Functions
double test_only (const Vector< double > &s, Shape &test) const
double d_shape_and_test_local (const Vector< double > &s, Shape &psi, Shape &test, DShape &dpsi_ds, DShape &dtest_ds) const
Protected Member Functions inherited from oomph::FaceElement
void add_additional_values (const Vector< unsigned > &nadditional_values, const unsigned &id)
Protected Member Functions inherited from oomph::FiniteElement
virtual void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
virtual void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
virtual void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
virtual void fill_in_contribution_to_residuals (Vector< double > &residuals)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Protected Attributes
std::complex< unsigned > U_index_helmholtz
unsigned Dim
The spatial dimension of the problem.
Protected Attributes inherited from oomph::FaceElement
unsigned Boundary_number_in_bulk_mesh
The boundary number in the bulk mesh to which this element is attached.
FiniteElement * Bulk_element_pt
Pointer to the associated higher-dimensional "bulk" element.
Vector< unsigned > Bulk_node_number
Vector< unsigned > Nbulk_value
Vector< double > * Tangent_direction_pt
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Additional Inherited Members
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
template<class ELEMENT>
class oomph::HelmholtzBCElementBase< ELEMENT >
////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////// A class for elements that allow the approximation of the Sommerfeld radiation BC. The element geometry is obtained from the FaceGeometry<ELEMENT> policy class.
Constructor & Destructor Documentation
HelmholtzBCElementBase() [1/3]
template<class ELEMENT > oomph::HelmholtzBCElementBase< ELEMENT >::HelmholtzBCElementBase (FiniteElement *const & bulk_el_pt, const int & face_index)
Constructor, takes the pointer to the "bulk" element and the face index.
Constructor, takes the pointer to the "bulk" element and the index of the face to which the element is attached.
     : FaceGeometry<ELEMENT>(), FaceElement()
   {
 #ifdef PARANOID
     {
       // Check that the element is not a refineable 3d element
       ELEMENT* elem_pt = new ELEMENT;
       // If it's three-d
       if (elem_pt->dim() == 3)
       {
         // Is it refineable
         if (dynamic_cast<RefineableElement*>(elem_pt))
         {
           // Issue a warning
           OomphLibWarning("This flux element will not"
                           "work correctly if nodes are hanging\n",
                           "HelmholtzBCElementBase::Constructor",
                           OOMPH_EXCEPTION_LOCATION);
         }
       }
     }
 #endif
     // Let the bulk element build the FaceElement, i.e. setup the pointers
     // to its nodes (by referring to the appropriate nodes in the bulk
     // element), etc.
     bulk_el_pt->build_face_element(face_index, this);
     // Extract the dimension of the problem from the dimension of
     // the first node
     Dim = this->node_pt(0)->ndim();
     // Set up U_index_helmholtz. Initialise to zero, which probably won't change
     // in most cases, oh well, the price we pay for generality
     U_index_helmholtz = std::complex<unsigned>(0, 1);
     // Cast to the appropriate HelmholtzEquation so that we can
     // find the index at which the variable is stored
     // We assume that the dimension of the full problem is the same
     // as the dimension of the node, if this is not the case you will have
     // to write custom elements, sorry
     switch (Dim)
     {
         // One dimensional problem
       case 1:
       {
         HelmholtzEquations<1>* eqn_pt =
           dynamic_cast<HelmholtzEquations<1>*>(bulk_el_pt);
         // If the cast has failed die
         if (eqn_pt == 0)
         {
           std::string error_string =
             "Bulk element must inherit from HelmholtzEquations.";
           error_string +=
             "Nodes are one dimensional, but cannot cast the bulk element to\n";
           error_string += "HelmholtzEquations<1>\n.";
           error_string += "If you desire this functionality, you must "
                           "implement it yourself\n";
           throw OomphLibError(
             error_string, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
         }
         // Otherwise read out the value
         else
         {
           // Read the index from the (cast) bulk element
           U_index_helmholtz = eqn_pt->u_index_helmholtz();
         }
       }
       break;
       // Two dimensional problem
       case 2:
       {
         HelmholtzEquations<2>* eqn_pt =
           dynamic_cast<HelmholtzEquations<2>*>(bulk_el_pt);
         // If the cast has failed die
         if (eqn_pt == 0)
         {
           std::string error_string =
             "Bulk element must inherit from HelmholtzEquations.";
           error_string +=
             "Nodes are two dimensional, but cannot cast the bulk element to\n";
           error_string += "HelmholtzEquations<2>\n.";
           error_string += "If you desire this functionality, you must "
                           "implement it yourself\n";
           throw OomphLibError(
             error_string, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
         }
         else
         {
           // Read the index from the (cast) bulk element
           U_index_helmholtz = eqn_pt->u_index_helmholtz();
         }
       }
       break;
       // Three dimensional problem
       case 3:
       {
         HelmholtzEquations<3>* eqn_pt =
           dynamic_cast<HelmholtzEquations<3>*>(bulk_el_pt);
         // If the cast has failed die
         if (eqn_pt == 0)
         {
           std::string error_string =
             "Bulk element must inherit from HelmholtzEquations.";
           error_string += "Nodes are three dimensional, but cannot cast the "
                           "bulk element to\n";
           error_string += "HelmholtzEquations<3>\n.";
           error_string += "If you desire this functionality, you must "
                           "implement it yourself\n";
           throw OomphLibError(
             error_string, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
         }
         else
         {
           // Read the index from the (cast) bulk element
           U_index_helmholtz = eqn_pt->u_index_helmholtz();
         }
       }
       break;
       // Any other case is an error
       default:
         std::ostringstream error_stream;
         error_stream << "Dimension of node is " << Dim
                      << ". It should be 1,2, or 3!" << std::endl;
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
         break;
     }
   }
References oomph::FiniteElement::build_face_element(), oomph::HelmholtzBCElementBase< ELEMENT >::Dim, oomph::FaceElement::face_index(), oomph::Node::ndim(), oomph::FiniteElement::node_pt(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::Global_string_for_annotation::string(), oomph::HelmholtzBCElementBase< ELEMENT >::U_index_helmholtz, and oomph::HelmholtzEquations< DIM >::u_index_helmholtz().
HelmholtzBCElementBase() [2/3]
template<class ELEMENT > oomph::HelmholtzBCElementBase< ELEMENT >::HelmholtzBCElementBase () inline
Broken empty constructor.
     {
       throw OomphLibError(
         "Don't call empty constructor for HelmholtzBCElementBase",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
HelmholtzBCElementBase() [3/3]
template<class ELEMENT > oomph::HelmholtzBCElementBase< ELEMENT >::HelmholtzBCElementBase (const HelmholtzBCElementBase< ELEMENT > & dummy) delete
Broken copy constructor.
Member Function Documentation
compute_contribution_to_fourier_components()
template<class ELEMENT > void oomph::HelmholtzBCElementBase< ELEMENT >::compute_contribution_to_fourier_components (Vector< std::complex< double >> & a_coeff_pos, Vector< std::complex< double >> & a_coeff_neg) inline
Compute element's contribution to Fourier components of the solution – length of vector indicates number of terms to be computed.
     {
 #ifdef PARANOID
       if (a_coeff_pos.size() != a_coeff_neg.size())
       {
         std::ostringstream error_stream;
         error_stream << "a_coeff_pos and a_coeff_neg must have "
                      << "the same size. \n";
         throw OomphLibError(
           error_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // define the imaginary number
       const std::complex<double> I(0.0, 1.0);
       // Find out how many nodes there are
       const unsigned n_node = this->nnode();
       // Set up memory for the shape  functions
       Shape psi(n_node);
       DShape dpsi(n_node, 1);
       // Set the value of n_intpt
       const unsigned n_intpt = this->integral_pt()->nweight();
       // Set the Vector to hold local coordinates
       Vector<double> s(this->Dim - 1);
       // Initialise
       unsigned n = a_coeff_pos.size();
       for (unsigned i = 0; i < n; i++)
       {
         a_coeff_pos[i] = std::complex<double>(0.0, 0.0);
         a_coeff_neg[i] = std::complex<double>(0.0, 0.0);
       }
       // Loop over the integration points
       //--------------------------------
       for (unsigned ipt = 0; ipt < n_intpt; ipt++)
       {
         // Assign values of s
         for (unsigned i = 0; i < (this->Dim - 1); i++)
         {
           s[i] = this->integral_pt()->knot(ipt, i);
         }
         // Get the integral weight
         double w = this->integral_pt()->weight(ipt);
         // Get the shape functions
         this->dshape_local(s, psi, dpsi);
         // Eulerian coordinates at Gauss point
         Vector<double> interpolated_x(this->Dim, 0.0);
         // Derivs of Eulerian coordinates w.r.t. local coordinates
         Vector<double> interpolated_dxds(this->Dim);
         std::complex<double> interpolated_u(0.0, 0.0);
         // Assemble x and its derivs
         for (unsigned l = 0; l < n_node; l++)
         {
           // Loop over directions
           for (unsigned i = 0; i < this->Dim; i++)
           {
             interpolated_x[i] += this->nodal_position(l, i) * psi[l];
             interpolated_dxds[i] += this->nodal_position(l, i) * dpsi(l, 0);
           }
           // Get the nodal value of the helmholtz unknown
           const std::complex<double> u_value(
             this->nodal_value(l, this->U_index_helmholtz.real()),
             this->nodal_value(l, this->U_index_helmholtz.imag()));
           // Add to the interpolated value
           interpolated_u += u_value * psi(l);
         } // End of loop over the nodes
         // calculate the integral
         //-----------------------
         // Get polar angle
         double phi = atan2(interpolated_x[1], interpolated_x[0]);
         // define dphi_ds=(-yx'+y'x)/(x^2+y^2)
         double denom = (interpolated_x[0] * interpolated_x[0]) +
                        (interpolated_x[1] * interpolated_x[1]);
         double nom = -interpolated_dxds[1] * interpolated_x[0] +
                      interpolated_dxds[0] * interpolated_x[1];
         double dphi_ds = std::fabs(nom / denom);
         // Positive coefficients
         for (unsigned i = 0; i < n; i++)
         {
           a_coeff_pos[i] +=
             interpolated_u * exp(-I * phi * double(i)) * dphi_ds * w;
         }
         // Negative coefficients
         for (unsigned i = 1; i < n; i++)
         {
           a_coeff_neg[i] +=
             interpolated_u * exp(I * phi * double(i)) * dphi_ds * w;
         }
       } // End of loop over integration points
     }
References atan2(), oomph::HelmholtzBCElementBase< ELEMENT >::Dim, oomph::FiniteElement::dshape_local(), Eigen::bfloat16_impl::exp(), boost::multiprecision::fabs(), i, I, oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), oomph::Integral::knot(), n, oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_position(), oomph::FiniteElement::nodal_value(), oomph::Integral::nweight(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, s, oomph::HelmholtzBCElementBase< ELEMENT >::U_index_helmholtz, w, and oomph::Integral::weight().
Referenced by oomph::HelmholtzDtNMesh< ELEMENT >::compute_fourier_components().
d_shape_and_test_local()
template<class ELEMENT > double oomph::HelmholtzBCElementBase< ELEMENT >::d_shape_and_test_local (const Vector< double > & s, Shape & psi, Shape & test, DShape & dpsi_ds, DShape & dtest_ds) const inline protected
Function to compute the shape, test functions and derivates and to return the Jacobian of mapping between local and global (Eulerian) coordinates
     {
       // Find number of nodes
       unsigned n_node = nnode();
       // Get the shape functions
       dshape_local(s, psi, dpsi_ds);
       // Set the test functions to be the same as the shape functions
       for (unsigned i = 0; i < n_node; i++)
       {
         for (unsigned j = 0; j < (Dim - 1); j++)
         {
           test[i] = psi[i];
           dtest_ds(i, j) = dpsi_ds(i, j);
         }
       }
       // Return the value of the jacobian
       return J_eulerian(s);
     }
References oomph::HelmholtzBCElementBase< ELEMENT >::Dim, oomph::FiniteElement::dshape_local(), i, j, oomph::FaceElement::J_eulerian(), oomph::FiniteElement::nnode(), and s.
Referenced by oomph::HelmholtzAbsorbingBCElement< ELEMENT >::fill_in_generic_residual_contribution_helmholtz_abc().
global_power_contribution() [1/2]
template<class ELEMENT > double oomph::HelmholtzBCElementBase< ELEMENT >::global_power_contribution () inline
Compute the element's contribution to the time-averaged radiated power over the artificial boundary
     {
       // Dummy output file
       std::ofstream outfile;
       return global_power_contribution(outfile);
     }
Referenced by CoatedDiskProblem< ELASTICITY_ELEMENT, HELMHOLTZ_ELEMENT >::doc_solution(), HelmholtzPointSourceProblem< ELEMENT >::doc_solution(), and ScatteringProblem< ELEMENT >::doc_solution().
global_power_contribution() [2/2]
template<class ELEMENT > double oomph::HelmholtzBCElementBase< ELEMENT >::global_power_contribution (std::ofstream & outfile) inline
Compute the element's contribution to the time-averaged radiated power over the artificial boundary. Also output the power density as a fct of the polar angle in the specified output file if it's open.
     {
       // pointer to the corresponding bulk element
       ELEMENT* bulk_elem_pt = dynamic_cast<ELEMENT*>(this->bulk_element_pt());
       // Number of nodes in bulk element
       unsigned nnode_bulk = bulk_elem_pt->nnode();
       const unsigned n_node_local = nnode();
       // get the dim of the bulk and local nodes
       const unsigned bulk_dim = bulk_elem_pt->dim();
       const unsigned local_dim = this->dim();
       // Set up memory for the shape and test functions
       Shape psi(n_node_local);
       // Set up memory for the shape functions
       Shape psi_bulk(nnode_bulk);
       DShape dpsi_bulk_dx(nnode_bulk, bulk_dim);
       // Set up memory for the outer unit normal
       Vector<double> unit_normal(bulk_dim);
       // Set the value of n_intpt
       const unsigned n_intpt = integral_pt()->nweight();
       // Set the Vector to hold local coordinates
       Vector<double> s(local_dim);
       double power = 0.0;
       // Output?
       if (outfile.is_open())
       {
         outfile << "ZONE\n";
       }
       // Loop over the integration points
       //--------------------------------
       for (unsigned ipt = 0; ipt < n_intpt; ipt++)
       {
         // Assign values of s
         for (unsigned i = 0; i < local_dim; i++)
         {
           s[i] = integral_pt()->knot(ipt, i);
         }
         // get the outer_unit_ext vector
         this->outer_unit_normal(s, unit_normal);
         // Get the integral weight
         double w = integral_pt()->weight(ipt);
         // Get jacobian of mapping
         double J = J_eulerian(s);
         // Premultiply the weights and the Jacobian
         double W = w * J;
         // Get local coordinates in bulk element by copy construction
         Vector<double> s_bulk(local_coordinate_in_bulk(s));
         // Call the derivatives of the shape  functions
         // in the bulk -- must do this via s because this point
         // is not an integration point the bulk element!
         (void)bulk_elem_pt->dshape_eulerian(s_bulk, psi_bulk, dpsi_bulk_dx);
         this->shape(s, psi);
         // Derivs of Eulerian coordinates w.r.t. local coordinates
         std::complex<double> dphi_dn(0.0, 0.0);
         Vector<std::complex<double>> interpolated_dphidx(bulk_dim);
         std::complex<double> interpolated_phi(0.0, 0.0);
         Vector<double> x(bulk_dim);
         // Calculate function value and derivatives:
         //-----------------------------------------
         // Loop over nodes
         for (unsigned l = 0; l < nnode_bulk; l++)
         {
           // Get the nodal value of the helmholtz unknown
           const std::complex<double> phi_value(
             bulk_elem_pt->nodal_value(l,
                                       bulk_elem_pt->u_index_helmholtz().real()),
             bulk_elem_pt->nodal_value(
               l, bulk_elem_pt->u_index_helmholtz().imag()));
           // Loop over directions
           for (unsigned i = 0; i < bulk_dim; i++)
           {
             interpolated_dphidx[i] += phi_value * dpsi_bulk_dx(l, i);
           }
         } // End of loop over the bulk_nodes
         for (unsigned l = 0; l < n_node_local; l++)
         {
           // Get the nodal value of the helmholtz unknown
           const std::complex<double> phi_value(
             nodal_value(l, u_index_helmholtz().real()),
             nodal_value(l, u_index_helmholtz().imag()));
           interpolated_phi += phi_value * psi(l);
         }
         // define dphi_dn
         for (unsigned i = 0; i < bulk_dim; i++)
         {
           dphi_dn += interpolated_dphidx[i] * unit_normal[i];
         }
         // Power density
         double integrand = 0.5 * (interpolated_phi.real() * dphi_dn.imag() -
                                   interpolated_phi.imag() * dphi_dn.real());
         // Output?
         if (outfile.is_open())
         {
           interpolated_x(s, x);
           double phi = atan2(x[1], x[0]);
           outfile << x[0] << " " << x[1] << " " << phi << " " << integrand
                   << "\n";
         }
         // ...add to integral
         power += integrand * W;
       }
       return power;
     }
References atan2(), oomph::FaceElement::bulk_element_pt(), oomph::FiniteElement::dim(), i, imag(), oomph::FiniteElement::integral_pt(), oomph::FaceElement::interpolated_x(), J, oomph::FaceElement::J_eulerian(), oomph::Integral::knot(), oomph::FaceElement::local_coordinate_in_bulk(), oomph::FiniteElement::nnode(), oomph::FiniteElement::nodal_value(), oomph::Integral::nweight(), oomph::FaceElement::outer_unit_normal(), s, oomph::FiniteElement::shape(), oomph::HelmholtzBCElementBase< ELEMENT >::u_index_helmholtz(), w, oomph::QuadTreeNames::W, oomph::Integral::weight(), and plotDoE::x.
output() [1/4]
template<class ELEMENT > void oomph::HelmholtzBCElementBase< ELEMENT >::output (FILE * file_pt) inline virtual
C-style output function – forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
     {
       FiniteElement::output(file_pt);
     }
References oomph::FiniteElement::output().
output() [2/4]
template<class ELEMENT > void oomph::HelmholtzBCElementBase< ELEMENT >::output (FILE * file_pt, const unsigned & n_plot) inline virtual
C-style output function – forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
     {
       FiniteElement::output(file_pt, n_plot);
     }
References oomph::FiniteElement::output().
output() [3/4]
template<class ELEMENT > void oomph::HelmholtzBCElementBase< ELEMENT >::output (std::ostream & outfile) inline virtual
Output function – forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
     {
       FiniteElement::output(outfile);
     }
References oomph::FiniteElement::output().
output() [4/4]
template<class ELEMENT > void oomph::HelmholtzBCElementBase< ELEMENT >::output (std::ostream & outfile, const unsigned & n_plot) inline virtual
Output function – forward to broken version in FiniteElement until somebody decides what exactly they want to plot here...
Reimplemented from oomph::FiniteElement.
     {
       FiniteElement::output(outfile, n_plot);
     }
References oomph::FiniteElement::output().
test_only()
template<class ELEMENT > double oomph::HelmholtzBCElementBase< ELEMENT >::test_only (const Vector< double > & s, Shape & test) const inline protected
Function to compute the shape and test functions and to return the Jacobian of mapping between local and global (Eulerian) coordinates
     {
       // Get the shape functions
       shape(s, test);
       // Return the value of the jacobian
       return J_eulerian(s);
     }
References oomph::FaceElement::J_eulerian(), s, and oomph::FiniteElement::shape().
Referenced by oomph::HelmholtzDtNBoundaryElement< ELEMENT >::fill_in_generic_residual_contribution_helmholtz_DtN_bc().
u_index_helmholtz()
template<class ELEMENT > virtual std::complex<unsigned> oomph::HelmholtzBCElementBase< ELEMENT >::u_index_helmholtz () const inline virtual
Return the index at which the real/imag unknown value is stored.
     {
       return std::complex<unsigned>(U_index_helmholtz.real(),
                                     U_index_helmholtz.imag());
     }
References oomph::HelmholtzBCElementBase< ELEMENT >::U_index_helmholtz.
Referenced by oomph::HelmholtzBCElementBase< ELEMENT >::global_power_contribution(), and oomph::HelmholtzDtNMesh< ELEMENT >::setup_gamma().
zeta_nodal()
template<class ELEMENT > double oomph::HelmholtzBCElementBase< ELEMENT >::zeta_nodal (const unsigned & n, const unsigned & k, const unsigned & i) const inline virtual
Broken assignment operator.
Specify the value of nodal zeta from the face geometry The "global" intrinsic coordinate of the element when viewed as part of a geometric object should be given by the FaceElement representation, by default (needed to break indeterminacy if bulk element is SolidElement)
Reimplemented from oomph::FaceElement.
     {
       return FaceElement::zeta_nodal(n, k, i);
     }
References i, k, n, and oomph::FaceElement::zeta_nodal().
Member Data Documentation
Dim
template<class ELEMENT > unsigned oomph::HelmholtzBCElementBase< ELEMENT >::Dim protected
The spatial dimension of the problem.
Referenced by oomph::HelmholtzBCElementBase< ELEMENT >::compute_contribution_to_fourier_components(), oomph::HelmholtzBCElementBase< ELEMENT >::d_shape_and_test_local(), oomph::HelmholtzAbsorbingBCElement< ELEMENT >::fill_in_generic_residual_contribution_helmholtz_abc(), oomph::HelmholtzDtNBoundaryElement< ELEMENT >::fill_in_generic_residual_contribution_helmholtz_DtN_bc(), and oomph::HelmholtzBCElementBase< ELEMENT >::HelmholtzBCElementBase().
U_index_helmholtz
template<class ELEMENT > std::complex<unsigned> oomph::HelmholtzBCElementBase< ELEMENT >::U_index_helmholtz protected
The index at which the real and imag part of the unknown is stored at the nodes
Referenced by oomph::HelmholtzBCElementBase< ELEMENT >::compute_contribution_to_fourier_components(), oomph::HelmholtzAbsorbingBCElement< ELEMENT >::fill_in_generic_residual_contribution_helmholtz_abc(), oomph::HelmholtzDtNBoundaryElement< ELEMENT >::fill_in_generic_residual_contribution_helmholtz_DtN_bc(), oomph::HelmholtzBCElementBase< ELEMENT >::HelmholtzBCElementBase(), and oomph::HelmholtzBCElementBase< ELEMENT >::u_index_helmholtz().
The documentation for this class was generated from the following file:
helmholtz_bc_elements.h