MercuryDPM: cxx11_tensor_comparisons.cpp File Reference
cxx11_tensor_comparisons.cpp File Reference
#include "main.h"
#include <Eigen/CXX11/Tensor>
Typedefs
using Scalar = float
using TypedLTOp = internal::scalar_cmp_op< Scalar, Scalar, internal::cmp_LT, true >
using TypedLEOp = internal::scalar_cmp_op< Scalar, Scalar, internal::cmp_LE, true >
using TypedGTOp = internal::scalar_cmp_op< Scalar, Scalar, internal::cmp_GT, true >
using TypedGEOp = internal::scalar_cmp_op< Scalar, Scalar, internal::cmp_GE, true >
using TypedEQOp = internal::scalar_cmp_op< Scalar, Scalar, internal::cmp_EQ, true >
using TypedNEOp = internal::scalar_cmp_op< Scalar, Scalar, internal::cmp_NEQ, true >
Functions
static void test_orderings ()
static void test_equality ()
static void test_isnan ()
static void test_isinf ()
static void test_isfinite ()
EIGEN_DECLARE_TEST (cxx11_tensor_comparisons)
Typedef Documentation
Scalar
using Scalar = float
TypedEQOp
using TypedEQOp = internal::scalar_cmp_op<Scalar, Scalar, internal::cmp_EQ, true>
TypedGEOp
using TypedGEOp = internal::scalar_cmp_op<Scalar, Scalar, internal::cmp_GE, true>
TypedGTOp
using TypedGTOp = internal::scalar_cmp_op<Scalar, Scalar, internal::cmp_GT, true>
TypedLEOp
using TypedLEOp = internal::scalar_cmp_op<Scalar, Scalar, internal::cmp_LE, true>
TypedLTOp
using TypedLTOp = internal::scalar_cmp_op<Scalar, Scalar, internal::cmp_LT, true>
TypedNEOp
using TypedNEOp = internal::scalar_cmp_op<Scalar, Scalar, internal::cmp_NEQ, true>
Function Documentation
EIGEN_DECLARE_TEST()
EIGEN_DECLARE_TEST (cxx11_tensor_comparisons)
{
   CALL_SUBTEST(test_orderings());
   CALL_SUBTEST(test_equality());
   CALL_SUBTEST(test_isnan());
   CALL_SUBTEST(test_isinf());
   CALL_SUBTEST(test_isfinite());
 }
References CALL_SUBTEST, test_equality(), test_isfinite(), test_isinf(), test_isnan(), and test_orderings().
test_equality()
static void test_equality () static
{
   Tensor<Scalar, 3> mat1(2, 3, 7);
   Tensor<Scalar, 3> mat2(2, 3, 7);
   mat1.setRandom();
   mat2.setRandom();
   for (int i = 0; i < 2; ++i) {
     for (int j = 0; j < 3; ++j) {
       for (int k = 0; k < 7; ++k) {
         if (internal::random<bool>()) {
           mat2(i, j, k) = mat1(i, j, k);
         }
       }
     }
   }
   Tensor<bool, 3> eq(2, 3, 7);
   Tensor<bool, 3> ne(2, 3, 7);
   Tensor<Scalar, 3> typed_eq(2, 3, 7);
   Tensor<Scalar, 3> typed_ne(2, 3, 7);
   eq = (mat1 == mat2);
   ne = (mat1 != mat2);
   typed_eq = mat1.binaryExpr(mat2, TypedEQOp());
   typed_ne = mat1.binaryExpr(mat2, TypedNEOp());
   for (int i = 0; i < 2; ++i) {
     for (int j = 0; j < 3; ++j) {
       for (int k = 0; k < 7; ++k) {
         VERIFY_IS_EQUAL(eq(i, j, k), mat1(i, j, k) == mat2(i, j, k));
         VERIFY_IS_EQUAL(ne(i, j, k), mat1(i, j, k) != mat2(i, j, k));
         VERIFY_IS_EQUAL(eq(i, j, k), (bool)typed_eq(i, j, k));
         VERIFY_IS_EQUAL(ne(i, j, k), (bool)typed_ne(i, j, k));
       }
     }
   }
 }
References i, j, k, mat1(), Eigen::TensorBase< Derived, AccessLevel >::setRandom(), and VERIFY_IS_EQUAL.
Referenced by EIGEN_DECLARE_TEST().
test_isfinite()
static void test_isfinite () static
{
   Tensor<Scalar, 3> mat(2, 3, 7);
   mat.setRandom();
   for (int i = 0; i < 2; ++i) {
     for (int j = 0; j < 3; ++j) {
       for (int k = 0; k < 7; ++k) {
         if (internal::random<bool>()) {
           mat(i, j, k) = std::numeric_limits<Scalar>::infinity();
         }
         if (internal::random<bool>()) {
           mat(i, j, k) = std::numeric_limits<Scalar>::quiet_NaN();
         }
       }
     }
   }
   Tensor<bool, 3> inf(2, 3, 7);
   inf = (mat.isfinite)();
   for (int i = 0; i < 2; ++i) {
     for (int j = 0; j < 3; ++j) {
       for (int k = 0; k < 7; ++k) {
         VERIFY_IS_EQUAL(inf(i, j, k), (std::isfinite)(mat(i, j, k)));
       }
     }
   }
 }
References i, constants::inf, isfinite, j, k, and VERIFY_IS_EQUAL.
Referenced by EIGEN_DECLARE_TEST().
test_isinf()
static void test_isinf () static
{
   Tensor<Scalar, 3> mat(2, 3, 7);
   mat.setRandom();
   for (int i = 0; i < 2; ++i) {
     for (int j = 0; j < 3; ++j) {
       for (int k = 0; k < 7; ++k) {
         if (internal::random<bool>()) {
           mat(i, j, k) = std::numeric_limits<Scalar>::infinity();
         }
       }
     }
   }
   Tensor<bool, 3> inf(2, 3, 7);
   inf = (mat.isinf)();
   for (int i = 0; i < 2; ++i) {
     for (int j = 0; j < 3; ++j) {
       for (int k = 0; k < 7; ++k) {
         VERIFY_IS_EQUAL(inf(i, j, k), (std::isinf)(mat(i, j, k)));
       }
     }
   }
 }
References i, constants::inf, isinf, j, k, and VERIFY_IS_EQUAL.
Referenced by EIGEN_DECLARE_TEST().
test_isnan()
static void test_isnan () static
{
   Tensor<Scalar, 3> mat(2, 3, 7);
   mat.setRandom();
   for (int i = 0; i < 2; ++i) {
     for (int j = 0; j < 3; ++j) {
       for (int k = 0; k < 7; ++k) {
         if (internal::random<bool>()) {
           mat(i, j, k) = std::numeric_limits<Scalar>::quiet_NaN();
         }
       }
     }
   }
   Tensor<bool, 3> nan(2, 3, 7);
   nan = (mat.isnan)();
   for (int i = 0; i < 2; ++i) {
     for (int j = 0; j < 3; ++j) {
       for (int k = 0; k < 7; ++k) {
         VERIFY_IS_EQUAL(nan(i, j, k), (std::isnan)(mat(i, j, k)));
       }
     }
   }
 }
References i, isnan, j, k, and VERIFY_IS_EQUAL.
Referenced by EIGEN_DECLARE_TEST().
test_orderings()
static void test_orderings () static
{
   Tensor<Scalar, 3> mat1(2, 3, 7);
   Tensor<Scalar, 3> mat2(2, 3, 7);
   mat1.setRandom();
   mat2.setRandom();
   Tensor<bool, 3> lt(2, 3, 7);
   Tensor<bool, 3> le(2, 3, 7);
   Tensor<bool, 3> gt(2, 3, 7);
   Tensor<bool, 3> ge(2, 3, 7);
   Tensor<Scalar, 3> typed_lt(2, 3, 7);
   Tensor<Scalar, 3> typed_le(2, 3, 7);
   Tensor<Scalar, 3> typed_gt(2, 3, 7);
   Tensor<Scalar, 3> typed_ge(2, 3, 7);
   lt = mat1 < mat2;
   le = mat1 <= mat2;
   gt = mat1 > mat2;
   ge = mat1 >= mat2;
   typed_lt = mat1.binaryExpr(mat2, TypedLTOp());
   typed_le = mat1.binaryExpr(mat2, TypedLEOp());
   typed_gt = mat1.binaryExpr(mat2, TypedGTOp());
   typed_ge = mat1.binaryExpr(mat2, TypedGEOp());
   for (int i = 0; i < 2; ++i) {
     for (int j = 0; j < 3; ++j) {
       for (int k = 0; k < 7; ++k) {
         VERIFY_IS_EQUAL(lt(i, j, k), mat1(i, j, k) < mat2(i, j, k));
         VERIFY_IS_EQUAL(le(i, j, k), mat1(i, j, k) <= mat2(i, j, k));
         VERIFY_IS_EQUAL(gt(i, j, k), mat1(i, j, k) > mat2(i, j, k));
         VERIFY_IS_EQUAL(ge(i, j, k), mat1(i, j, k) >= mat2(i, j, k));
         VERIFY_IS_EQUAL(lt(i, j, k), (bool)typed_lt(i, j, k));
         VERIFY_IS_EQUAL(le(i, j, k), (bool)typed_le(i, j, k));
         VERIFY_IS_EQUAL(gt(i, j, k), (bool)typed_gt(i, j, k));
         VERIFY_IS_EQUAL(ge(i, j, k), (bool)typed_ge(i, j, k));
       }
     }
   }
 }
References i, j, k, mat1(), Eigen::TensorBase< Derived, AccessLevel >::setRandom(), and VERIFY_IS_EQUAL.
Referenced by EIGEN_DECLARE_TEST().