MercuryDPM: shift_test_impl< ArrayType > Struct Template Reference
shift_test_impl< ArrayType > Struct Template Reference
Public Types
typedef ArrayType::Scalar Scalar
Static Public Member Functions
template<size_t N = 1>
static std::enable_if_t<(N > MaxShift), void > run (const ArrayType &)
template<size_t N = 1>
static std::enable_if_t<(N<=MaxShift), void > run (const ArrayType &m)
Static Public Attributes
static constexpr size_t Size = sizeof(Scalar)
static constexpr size_t MaxShift = (CHAR_BIT * Size) - 1
Member Typedef Documentation
Scalar
template<typename ArrayType > typedef ArrayType::Scalar shift_test_impl< ArrayType >::Scalar
Member Function Documentation
run() [1/2]
template<typename ArrayType > template<size_t N = 1> static std::enable_if_t<(N > MaxShift), void> shift_test_impl< ArrayType >::run (const ArrayType &) inline static
 {}
Referenced by shift_test().
run() [2/2]
template<typename ArrayType > template<size_t N = 1> static std::enable_if_t<(N <= MaxShift), void> shift_test_impl< ArrayType >::run (const ArrayType & m) inline static
{
     const Index rows = m.rows();
     const Index cols = m.cols();
     ArrayType m1 = ArrayType::Random(rows, cols), m2(rows, cols), m3(rows, cols);
     m2 = m1.unaryExpr([](const Scalar& v) { return numext::logical_shift_left(v, N); });
     m3 = m1.unaryExpr(logical_left_shift_op<N, Scalar>());
     VERIFY_IS_CWISE_EQUAL(m2, m3);
     m2 = m1.unaryExpr([](const Scalar& v) { return numext::logical_shift_right(v, N); });
     m3 = m1.unaryExpr(logical_right_shift_op<N, Scalar>());
     VERIFY_IS_CWISE_EQUAL(m2, m3);
     m2 = m1.unaryExpr([](const Scalar& v) { return numext::arithmetic_shift_right(v, N); });
     m3 = m1.unaryExpr(arithmetic_right_shift_op<N, Scalar>());
     VERIFY_IS_CWISE_EQUAL(m2, m3);
     run<N + 1>(m);
   }
References Eigen::numext::arithmetic_shift_right(), cols, Eigen::numext::logical_shift_left(), Eigen::numext::logical_shift_right(), m, m1, m2(), N, rows, v, and VERIFY_IS_CWISE_EQUAL.
Member Data Documentation
MaxShift
template<typename ArrayType > constexpr size_t shift_test_impl< ArrayType >::MaxShift = (CHAR_BIT * Size) - 1 static constexpr
Size
template<typename ArrayType > constexpr size_t shift_test_impl< ArrayType >::Size = sizeof(Scalar) static constexpr
The documentation for this struct was generated from the following file:
array_cwise.cpp