MercuryDPM: oomph::CoarseTwoIntoOne< MATRIX > Class Template Reference
oomph::CoarseTwoIntoOne< MATRIX > Class Template Reference
#include <multi_poisson_block_preconditioners.h>
Public Member Functions
CoarseTwoIntoOne ()
Constructor for CoarseTwoIntoOne.
~CoarseTwoIntoOne ()
Destructor - delete the diagonal solvers (subsidiary preconditioners)
virtual void clean_up_my_memory ()
clean up the memory
CoarseTwoIntoOne (const CoarseTwoIntoOne &)
Broken copy constructor.
void operator= (const CoarseTwoIntoOne &)
Broken assignment operator.
void setup ()
Setup the preconditioner.
void preconditioner_solve (const DoubleVector &r, DoubleVector &z)
void set_multi_poisson_mesh (Mesh *multi_poisson_mesh_pt)
Specify the mesh that contains multi-poisson elements.
void setup (DoubleMatrixBase *matrix_pt)
void setup (const Problem *problem_pt, DoubleMatrixBase *matrix_pt)
virtual void setup ()=0
Public Member Functions inherited from oomph::BlockPreconditioner< MATRIX >
BlockPreconditioner ()
Constructor.
virtual ~BlockPreconditioner ()
Destructor.
BlockPreconditioner (const BlockPreconditioner &)=delete
Broken copy constructor.
void operator= (const BlockPreconditioner &)=delete
Broken assignment operator.
MATRIX * matrix_pt () const
void turn_on_recursive_debug_flag ()
void turn_off_recursive_debug_flag ()
void turn_on_debug_flag ()
Toggles on the debug flag.
void turn_off_debug_flag ()
Toggles off the debug flag.
void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< MATRIX > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse)
void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< MATRIX > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse, const Vector< Vector< unsigned >> &doftype_coarsen_map_coarse)
virtual void block_setup ()
void block_setup (const Vector< unsigned > &dof_to_block_map)
void get_block (const unsigned &i, const unsigned &j, MATRIX &output_matrix, const bool &ignore_replacement_block=false) const
MATRIX get_block (const unsigned &i, const unsigned &j, const bool &ignore_replacement_block=false) const
void set_master_matrix_pt (MATRIX *in_matrix_pt)
Set the matrix_pt in the upper-most master preconditioner.
void get_block_other_matrix (const unsigned &i, const unsigned &j, MATRIX *in_matrix_pt, MATRIX &output_matrix)
void get_blocks (DenseMatrix< bool > &required_blocks, DenseMatrix< MATRIX * > &block_matrix_pt) const
void get_dof_level_block (const unsigned &i, const unsigned &j, MATRIX &output_block, const bool &ignore_replacement_block=false) const
MATRIX get_concatenated_block (const VectorMatrix< BlockSelector > &selected_block)
void get_concatenated_block_vector (const Vector< unsigned > &block_vec_number, const DoubleVector &v, DoubleVector &b)
void return_concatenated_block_vector (const Vector< unsigned > &block_vec_number, const DoubleVector &b, DoubleVector &v) const
Takes concatenated block ordered vector, b, and copies its.
void get_block_vectors (const Vector< unsigned > &block_vec_number, const DoubleVector &v, Vector< DoubleVector > &s) const
void get_block_vectors (const DoubleVector &v, Vector< DoubleVector > &s) const
void return_block_vectors (const Vector< unsigned > &block_vec_number, const Vector< DoubleVector > &s, DoubleVector &v) const
void return_block_vectors (const Vector< DoubleVector > &s, DoubleVector &v) const
void get_block_vector (const unsigned &n, const DoubleVector &v, DoubleVector &b) const
void return_block_vector (const unsigned &n, const DoubleVector &b, DoubleVector &v) const
void get_block_ordered_preconditioner_vector (const DoubleVector &v, DoubleVector &w)
void return_block_ordered_preconditioner_vector (const DoubleVector &w, DoubleVector &v) const
unsigned nblock_types () const
Return the number of block types.
unsigned ndof_types () const
Return the total number of DOF types.
const Mesh * mesh_pt (const unsigned &i) const
unsigned nmesh () const
int block_number (const unsigned &i_dof) const
Return the block number corresponding to a global index i_dof.
int index_in_block (const unsigned &i_dof) const
const LinearAlgebraDistribution * block_distribution_pt (const unsigned &b) const
Access function to the block distributions (const version).
LinearAlgebraDistribution * block_distribution_pt (const unsigned b)
Access function to the block distributions (non-const version).
LinearAlgebraDistribution * dof_block_distribution_pt (const unsigned &b)
Access function to the dof-level block distributions.
const LinearAlgebraDistribution * master_distribution_pt () const
unsigned ndof_types_in_mesh (const unsigned &i) const
bool is_subsidiary_block_preconditioner () const
bool is_master_block_preconditioner () const
void set_block_output_to_files (const std::string &basefilename)
void disable_block_output_to_files ()
Turn off output of blocks (by clearing the basefilename string).
bool block_output_on () const
Test if output of blocks is on or not.
void output_blocks_to_files (const std::string &basefilename, const unsigned &precision=8) const
void post_block_matrix_assembly_partial_clear ()
BlockPreconditioner< MATRIX > * master_block_preconditioner_pt () const
Access function to the master block preconditioner pt.
void clear_block_preconditioner_base ()
void document ()
Vector< Vector< unsigned > > doftype_coarsen_map_fine () const
Vector< unsigned > get_fine_grain_dof_types_in (const unsigned &i) const
unsigned nfine_grain_dof_types_in (const unsigned &i) const
MapMatrix< unsigned, CRDoubleMatrix * > replacement_dof_block_pt () const
Access function to the replaced dof-level blocks.
void setup_matrix_vector_product (MatrixVectorProduct *matvec_prod_pt, CRDoubleMatrix *block_pt, const Vector< unsigned > &block_col_indices)
void setup_matrix_vector_product (MatrixVectorProduct *matvec_prod_pt, CRDoubleMatrix *block_pt, const unsigned &block_col_index)
void internal_get_block_ordered_preconditioner_vector (const DoubleVector &v, DoubleVector &w) const
void internal_return_block_ordered_preconditioner_vector (const DoubleVector &w, DoubleVector &v) const
unsigned internal_nblock_types () const
unsigned internal_ndof_types () const
void internal_return_block_vector (const unsigned &n, const DoubleVector &b, DoubleVector &v) const
void internal_get_block_vector (const unsigned &n, const DoubleVector &v, DoubleVector &b) const
void internal_get_block_vectors (const Vector< unsigned > &block_vec_number, const DoubleVector &v, Vector< DoubleVector > &s) const
void internal_get_block_vectors (const DoubleVector &v, Vector< DoubleVector > &s) const
void internal_return_block_vectors (const Vector< unsigned > &block_vec_number, const Vector< DoubleVector > &s, DoubleVector &v) const
void internal_return_block_vectors (const Vector< DoubleVector > &s, DoubleVector &v) const
void internal_get_block (const unsigned &i, const unsigned &j, MATRIX &output_block) const
int internal_block_number (const unsigned &i_dof) const
int internal_index_in_block (const unsigned &i_dof) const
const LinearAlgebraDistribution * internal_block_distribution_pt (const unsigned &b) const
Access function to the internal block distributions.
void insert_auxiliary_block_distribution (const Vector< unsigned > &block_vec_number, LinearAlgebraDistribution *dist_pt)
void block_matrix_test (const unsigned &i, const unsigned &j, const MATRIX *block_matrix_pt) const
template<typename myType >
int get_index_of_value (const Vector< myType > &vec, const myType val, const bool sorted=false) const
void internal_get_block (const unsigned &block_i, const unsigned &block_j, CRDoubleMatrix &output_block) const
void get_dof_level_block (const unsigned &block_i, const unsigned &block_j, CRDoubleMatrix &output_block, const bool &ignore_replacement_block) const
Public Member Functions inherited from oomph::Preconditioner
Preconditioner ()
Constructor.
Preconditioner (const Preconditioner &)=delete
Broken copy constructor.
void operator= (const Preconditioner &)=delete
Broken assignment operator.
virtual ~Preconditioner ()
Destructor (empty)
virtual void preconditioner_solve_transpose (const DoubleVector &r, DoubleVector &z)
void setup (DoubleMatrixBase *matrix_pt)
void setup (const Problem *problem_pt, DoubleMatrixBase *matrix_pt)
void enable_silent_preconditioner_setup ()
Set up the block preconditioner quietly!
void disable_silent_preconditioner_setup ()
Be verbose in the block preconditioner setup.
virtual void clean_up_memory ()
Clean up memory (empty). Generic interface function.
virtual void set_matrix_pt (DoubleMatrixBase *matrix_pt)
Set the matrix pointer.
virtual const OomphCommunicator * comm_pt () const
Get function for comm pointer.
virtual void set_comm_pt (const OomphCommunicator *const comm_pt)
Set the communicator pointer.
double setup_time () const
Returns the time to setup the preconditioner.
virtual void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse)
virtual void turn_into_subsidiary_block_preconditioner (BlockPreconditioner< CRDoubleMatrix > *master_block_prec_pt, const Vector< unsigned > &doftype_in_master_preconditioner_coarse, const Vector< Vector< unsigned >> &doftype_coarsen_map_coarse)
Public Member Functions inherited from oomph::DistributableLinearAlgebraObject
DistributableLinearAlgebraObject ()
Default constructor - create a distribution.
DistributableLinearAlgebraObject (const DistributableLinearAlgebraObject &matrix)=delete
Broken copy constructor.
void operator= (const DistributableLinearAlgebraObject &)=delete
Broken assignment operator.
virtual ~DistributableLinearAlgebraObject ()
Destructor.
LinearAlgebraDistribution * distribution_pt () const
access to the LinearAlgebraDistribution
unsigned nrow () const
access function to the number of global rows.
unsigned nrow_local () const
access function for the num of local rows on this processor.
unsigned nrow_local (const unsigned &p) const
access function for the num of local rows on this processor.
unsigned first_row () const
access function for the first row on this processor
unsigned first_row (const unsigned &p) const
access function for the first row on this processor
bool distributed () const
distribution is serial or distributed
bool distribution_built () const
void build_distribution (const LinearAlgebraDistribution *const dist_pt)
void build_distribution (const LinearAlgebraDistribution &dist)
Private Attributes
Preconditioner * Subsidiary_preconditioner_pt
Pointer to the preconditioners/inexact solvers.
Mesh * Multi_poisson_mesh_pt
Additional Inherited Members
Protected Member Functions inherited from oomph::BlockPreconditioner< MATRIX >
void set_nmesh (const unsigned &n)
void set_mesh (const unsigned &i, const Mesh *const mesh_pt, const bool &allow_multiple_element_type_in_mesh=false)
void set_replacement_dof_block (const unsigned &block_i, const unsigned &block_j, CRDoubleMatrix *replacement_dof_block_pt)
bool any_mesh_distributed () const
int internal_dof_number (const unsigned &i_dof) const
unsigned internal_index_in_dof (const unsigned &i_dof) const
unsigned internal_block_dimension (const unsigned &b) const
unsigned internal_dof_block_dimension (const unsigned &i) const
unsigned master_nrow () const
unsigned internal_master_dof_number (const unsigned &b) const
const LinearAlgebraDistribution * internal_preconditioner_matrix_distribution_pt () const
const LinearAlgebraDistribution * preconditioner_matrix_distribution_pt () const
Protected Member Functions inherited from oomph::DistributableLinearAlgebraObject
void clear_distribution ()
Protected Attributes inherited from oomph::BlockPreconditioner< MATRIX >
MapMatrix< unsigned, CRDoubleMatrix * > Replacement_dof_block_pt
The replacement dof-level blocks.
Vector< LinearAlgebraDistribution * > Block_distribution_pt
The distribution for the blocks.
Vector< Vector< unsigned > > Block_to_dof_map_coarse
Vector< Vector< unsigned > > Block_to_dof_map_fine
Mapping for the block types to the most fine grain dof types.
Vector< Vector< unsigned > > Doftype_coarsen_map_coarse
Vector< Vector< unsigned > > Doftype_coarsen_map_fine
Vector< LinearAlgebraDistribution * > Internal_block_distribution_pt
Storage for the default distribution for each internal block.
Vector< LinearAlgebraDistribution * > Dof_block_distribution_pt
Vector< unsigned > Allow_multiple_element_type_in_mesh
Vector< const Mesh * > Mesh_pt
Vector< unsigned > Ndof_types_in_mesh
unsigned Internal_nblock_types
unsigned Internal_ndof_types
Protected Attributes inherited from oomph::Preconditioner
bool Silent_preconditioner_setup
Boolean to indicate whether or not the build should be done silently.
std::ostream * Stream_pt
Pointer to the output stream – defaults to std::cout.
Detailed Description
template<typename MATRIX>
class oomph::CoarseTwoIntoOne< MATRIX >
//////////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////////////// CoarseTwoIntoOne block diagonal preconditioner which works with only two DOF types. If this is used by a master preconditioner to operate on a compound block with more than two DOF types then they must be coarsened via a parameter to the master preconditioner's member function turn_into_subsidiary_block_preconditioner(...).
The uses SimpleOneDofOnly as a subsidiary block preconditioner. Thus the two DOF types are coarsened.
Constructor & Destructor Documentation
CoarseTwoIntoOne() [1/2]
template<typename MATRIX > oomph::CoarseTwoIntoOne< MATRIX >::CoarseTwoIntoOne () inline
Constructor for CoarseTwoIntoOne.
                      : BlockPreconditioner<MATRIX>()
    {
     Subsidiary_preconditioner_pt = 0;
     Multi_poisson_mesh_pt=0;
    } // end_of_constructor
References oomph::CoarseTwoIntoOne< MATRIX >::Multi_poisson_mesh_pt, and oomph::CoarseTwoIntoOne< MATRIX >::Subsidiary_preconditioner_pt.
~CoarseTwoIntoOne()
template<typename MATRIX > oomph::CoarseTwoIntoOne< MATRIX >::~CoarseTwoIntoOne () inline
Destructor - delete the diagonal solvers (subsidiary preconditioners)
    {
     this->clean_up_my_memory();
    }
References oomph::CoarseTwoIntoOne< MATRIX >::clean_up_my_memory().
CoarseTwoIntoOne() [2/2]
template<typename MATRIX > oomph::CoarseTwoIntoOne< MATRIX >::CoarseTwoIntoOne (const CoarseTwoIntoOne< MATRIX > &) inline
Broken copy constructor.
    {
     BrokenCopy::broken_copy("CoarseTwoIntoOne");
    }
References oomph::BrokenCopy::broken_copy().
Member Function Documentation
clean_up_my_memory()
template<typename MATRIX > void oomph::CoarseTwoIntoOne< MATRIX >::clean_up_my_memory virtual
clean up the memory
The clean up function.
  {
    // Delete the subsidiary block preconditioner (approximate solver)
    if(Subsidiary_preconditioner_pt!=0)
    {
      delete Subsidiary_preconditioner_pt;
      Subsidiary_preconditioner_pt=0;
    }
  } // End of clean_up_my_memory function.
Referenced by oomph::CoarseTwoIntoOne< MATRIX >::~CoarseTwoIntoOne().
operator=()
template<typename MATRIX > void oomph::CoarseTwoIntoOne< MATRIX >::operator= (const CoarseTwoIntoOne< MATRIX > &) inline
Broken assignment operator.
    {
     BrokenCopy::broken_assign("CoarseTwoIntoOne");
    }
References oomph::BrokenCopy::broken_assign().
preconditioner_solve()
template<typename MATRIX > void oomph::CoarseTwoIntoOne< MATRIX >::preconditioner_solve (const DoubleVector & r, DoubleVector & z) virtual
Preconditioner solve for the diagonal preconditioner: Apply preconditioner to r and return z, so that P z = r, where P is the block diagonal matrix constructed from the original linear system.
Implements oomph::Preconditioner.
  {
    // Call the subsidiary block preconditioner's preconditioner_solve(...)
    // function. We do not need to return the solution to the vector z since
    // this is handled by the subsidiary BLOCK preconditioner.
    Subsidiary_preconditioner_pt->preconditioner_solve(r,z);
  }
References UniformPSDSelfTest::r.
set_multi_poisson_mesh()
template<typename MATRIX > void oomph::CoarseTwoIntoOne< MATRIX >::set_multi_poisson_mesh (Mesh * multi_poisson_mesh_pt) inline
Specify the mesh that contains multi-poisson elements.
   {
    Multi_poisson_mesh_pt=multi_poisson_mesh_pt;
   }
References oomph::CoarseTwoIntoOne< MATRIX >::Multi_poisson_mesh_pt.
Referenced by oomph::OnePlusFourWithTwoCoarse< MATRIX >::setup().
setup() [1/4]
template<typename MATRIX > void oomph::CoarseTwoIntoOne< MATRIX >::setup virtual
Setup the preconditioner.
The setup function.
Implements oomph::Preconditioner.
  {
   // clean the memory
   this->clean_up_my_memory();
 #ifdef PARANOID
   if (Multi_poisson_mesh_pt == 0)
    {
     std::stringstream err;
     err << "Please set pointer to mesh using set_multi_poisson_mesh(...).\n";
     throw OomphLibError(err.str(),
                         OOMPH_CURRENT_FUNCTION,
                         OOMPH_EXCEPTION_LOCATION);
    }
 #endif
   // The preconditioner works with one mesh; set it!
   this->set_nmesh(1);
   this->set_mesh(0,Multi_poisson_mesh_pt);
 #ifdef PARANOID
   // This preconditioner only works for 2 dof types
   unsigned n_dof_types = this->ndof_types();
   // Output the number of dof types.
   std::cout << "CoarseTwoIntoOne ndof_types: " << n_dof_types << std::endl;
   if (n_dof_types!=2)
    {
     std::stringstream tmp;
     tmp << "This preconditioner only works for problems with 2 dof types\n"
         << "Yours has " << n_dof_types;
     throw OomphLibError(tmp.str(),
                         OOMPH_CURRENT_FUNCTION,
                         OOMPH_EXCEPTION_LOCATION);
    }
 #endif
   // Set up the generic block look up scheme
   this->block_setup();
 #ifdef PARANOID
   unsigned n_block_types = this->nblock_types();
   std::cout << "CoarseTwoIntoOne nblock_types: "
             << n_block_types << std::endl;
   if (n_block_types!=2)
    {
     std::stringstream tmp;
     tmp << "There are supposed to be two block types.\n"
         << "Yours has " << n_block_types;
     throw OomphLibError(tmp.str(),
                         OOMPH_CURRENT_FUNCTION,
                         OOMPH_EXCEPTION_LOCATION);
    }
 #endif
   // Create the subsidiary preconditioners
   SimpleOneDofOnly<CRDoubleMatrix>* block_prec_pt =
     new SimpleOneDofOnly<CRDoubleMatrix>;
   Subsidiary_preconditioner_pt = block_prec_pt;
   // Setup preconditioner
   // We use a subsidiary block preconditioner which accepts only one DOF
   // types. Since we have two DOF types, we must coarsen DOF types.
   {
    // Set mesh
    block_prec_pt->set_multi_poisson_mesh(Multi_poisson_mesh_pt);
     // This is the usual dof map between master's DOF type and subsidiary
     // DOF types. In this case, the vector [0,1] tells the subsidiary block
     // preconditioner that it's DOF type 0(1) is mapped to the master's DOF
     // type 0(1).
    Vector<unsigned>dof_map(2);
    dof_map[0] = 0;
    dof_map[1] = 1;
    // To coarsen DOF types, we have a 2D Vector.
    // Size of the outer Vector is the number of subsidiary DOF types.
    const unsigned n_sub_dof_types = 1;
    Vector<Vector<unsigned> >doftype_coarsening(n_sub_dof_types);
    // The inner vector(s) tells the subsidiary block preconditioner which
    // DOF types to coarsen into one. In this case the 0th inner vector is
    // of size TWO with values [0,1], this tells the subsidiary block
    // preconditioner that IT'S DOF type 0 and 1 is coarsened into
    // DOF type 0.
    doftype_coarsening[0].resize(2);
    doftype_coarsening[0][0]=0;
    doftype_coarsening[0][1]=1;
    block_prec_pt->turn_into_subsidiary_block_preconditioner(this,
                                       dof_map,doftype_coarsening);
    // Set up block preconditioner. Note that because the subsidiary
    // preconditioner is a block preconditioner itself it is given
    // the pointer to the "full" matrix
    block_prec_pt->setup(this->matrix_pt());
   }
  }
References OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::SimpleOneDofOnly< MATRIX >::set_multi_poisson_mesh(), oomph::SimpleOneDofOnly< MATRIX >::setup(), tmp, and oomph::BlockPreconditioner< MATRIX >::turn_into_subsidiary_block_preconditioner().
Referenced by oomph::OnePlusFourWithTwoCoarse< MATRIX >::setup().
setup() [2/4]
template<typename MATRIX > virtual void oomph::Preconditioner::setup virtual
Setup the preconditioner. Pure virtual generic interface function.
Implements oomph::Preconditioner.
setup() [3/4]
template<typename MATRIX > void oomph::Preconditioner::setup inline virtual
Compatability layer for old preconditioners where problem pointers were needed. The problem pointer is only used to get a communicator pointer.
Implements oomph::Preconditioner.
     {
       ObsoleteCode::obsolete();
       setup(matrix_pt);
     }
setup() [4/4]
template<typename MATRIX > void oomph::Preconditioner::setup inline virtual
Setup the preconditioner: store the matrix pointer and the communicator pointer then call preconditioner specific setup() function.
Implements oomph::Preconditioner.
     {
       // Store matrix pointer
       set_matrix_pt(matrix_pt);
       // Extract and store communicator pointer
       DistributableLinearAlgebraObject* dist_obj_pt =
         dynamic_cast<DistributableLinearAlgebraObject*>(matrix_pt);
       if (dist_obj_pt != 0)
       {
         set_comm_pt(dist_obj_pt->distribution_pt()->communicator_pt());
       }
       else
       {
         set_comm_pt(0);
       }
       double setup_time_start = TimingHelpers::timer();
       setup();
       double setup_time_finish = TimingHelpers::timer();
       Setup_time = setup_time_finish - setup_time_start;
     }
Member Data Documentation
Multi_poisson_mesh_pt
template<typename MATRIX > Mesh* oomph::CoarseTwoIntoOne< MATRIX >::Multi_poisson_mesh_pt private
Pointer to mesh with preconditionable elements used for classification of dof types.
Referenced by oomph::CoarseTwoIntoOne< MATRIX >::CoarseTwoIntoOne(), and oomph::CoarseTwoIntoOne< MATRIX >::set_multi_poisson_mesh().
Subsidiary_preconditioner_pt
template<typename MATRIX > Preconditioner* oomph::CoarseTwoIntoOne< MATRIX >::Subsidiary_preconditioner_pt private
Pointer to the preconditioners/inexact solvers.
Referenced by oomph::CoarseTwoIntoOne< MATRIX >::CoarseTwoIntoOne().
The documentation for this class was generated from the following file:
multi_poisson_block_preconditioners.h