MercuryDPM: Eigen::internal::TensorCwiseUnaryBlock< UnaryOp, ArgTensorBlock > Class Template Reference
Eigen::internal::TensorCwiseUnaryBlock< UnaryOp, ArgTensorBlock > Class Template Reference
#include <TensorBlock.h>
Public Types
typedef std::conditional_t< NoArgBlockAccess, void, TensorCwiseUnaryOp< UnaryOp, const typename ArgTensorBlock::XprType > > XprType
typedef XprScalar< XprType >::type Scalar
Public Member Functions
TensorCwiseUnaryBlock (const ArgTensorBlock &arg_block, const UnaryOp &functor)
TensorBlockKind kind () const
XprType expr () const
const Scalar * data () const
void cleanup ()
Private Attributes
ArgTensorBlock m_arg_block
UnaryOp m_functor
Static Private Attributes
static constexpr bool NoArgBlockAccess = internal::is_void<typename ArgTensorBlock::XprType>::value
Member Typedef Documentation
Scalar
template<typename UnaryOp , typename ArgTensorBlock > typedef XprScalar<XprType>::type Eigen::internal::TensorCwiseUnaryBlock< UnaryOp, ArgTensorBlock >::Scalar
XprType
template<typename UnaryOp , typename ArgTensorBlock > typedef std::conditional_t<NoArgBlockAccess, void, TensorCwiseUnaryOp<UnaryOp, const typename ArgTensorBlock::XprType> > Eigen::internal::TensorCwiseUnaryBlock< UnaryOp, ArgTensorBlock >::XprType
Constructor & Destructor Documentation
TensorCwiseUnaryBlock()
template<typename UnaryOp , typename ArgTensorBlock > Eigen::internal::TensorCwiseUnaryBlock< UnaryOp, ArgTensorBlock >::TensorCwiseUnaryBlock (const ArgTensorBlock & arg_block, const UnaryOp & functor) inline
       : m_arg_block(arg_block), m_functor(functor) {}
Member Function Documentation
cleanup()
template<typename UnaryOp , typename ArgTensorBlock > void Eigen::internal::TensorCwiseUnaryBlock< UnaryOp, ArgTensorBlock >::cleanup () inline
 { m_arg_block.cleanup(); }
References Eigen::internal::TensorCwiseUnaryBlock< UnaryOp, ArgTensorBlock >::m_arg_block.
Referenced by framework.Frame::__init__().
data()
template<typename UnaryOp , typename ArgTensorBlock > const Scalar* Eigen::internal::TensorCwiseUnaryBlock< UnaryOp, ArgTensorBlock >::data () const inline
 { return NULL; }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
expr()
template<typename UnaryOp , typename ArgTensorBlock > XprType Eigen::internal::TensorCwiseUnaryBlock< UnaryOp, ArgTensorBlock >::expr () const inline
 { return XprType(m_arg_block.expr(), m_functor); }
References Eigen::internal::TensorCwiseUnaryBlock< UnaryOp, ArgTensorBlock >::m_arg_block, and Eigen::internal::TensorCwiseUnaryBlock< UnaryOp, ArgTensorBlock >::m_functor.
kind()
template<typename UnaryOp , typename ArgTensorBlock > TensorBlockKind Eigen::internal::TensorCwiseUnaryBlock< UnaryOp, ArgTensorBlock >::kind () const inline
 { return internal::TensorBlockKind::kExpr; }
References Eigen::internal::kExpr.
Member Data Documentation
m_arg_block
template<typename UnaryOp , typename ArgTensorBlock > ArgTensorBlock Eigen::internal::TensorCwiseUnaryBlock< UnaryOp, ArgTensorBlock >::m_arg_block private
Referenced by Eigen::internal::TensorCwiseUnaryBlock< UnaryOp, ArgTensorBlock >::cleanup(), and Eigen::internal::TensorCwiseUnaryBlock< UnaryOp, ArgTensorBlock >::expr().
m_functor
template<typename UnaryOp , typename ArgTensorBlock > UnaryOp Eigen::internal::TensorCwiseUnaryBlock< UnaryOp, ArgTensorBlock >::m_functor private
Referenced by Eigen::internal::TensorCwiseUnaryBlock< UnaryOp, ArgTensorBlock >::expr().
NoArgBlockAccess
template<typename UnaryOp , typename ArgTensorBlock > constexpr bool Eigen::internal::TensorCwiseUnaryBlock< UnaryOp, ArgTensorBlock >::NoArgBlockAccess = internal::is_void<typename ArgTensorBlock::XprType>::value static constexpr private
The documentation for this class was generated from the following file:
TensorBlock.h