MercuryDPM: Eigen::TensorEvaluator< TensorShufflingOp< Shuffle, ArgType >, Device > Struct Template Reference
Eigen::TensorEvaluator< TensorShufflingOp< Shuffle, ArgType >, Device > Struct Template Reference
#include <TensorShuffling.h>
Public Types
enum {
IsAligned = false , PacketAccess = (PacketType<CoeffReturnType, Device>::size > 1) , BlockAccess = TensorEvaluator<ArgType, Device>::RawAccess , PreferBlockAccess = true ,
RawAccess = false
}
typedef TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device > Base
typedef TensorShufflingOp< Shuffle, ArgType > XprType
typedef XprType::Index Index
typedef DSizes< Index, NumDims > Dimensions
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef std::remove_const_t< Scalar > ScalarNoConst
typedef internal::TensorBlockDescriptor< NumDims, Index > TensorBlockDesc
Public Types inherited from Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >
enum {
IsAligned = false , PacketAccess = (PacketType<CoeffReturnType, Device>::size > 1) , BlockAccess = TensorEvaluator<ArgType, Device>::RawAccess , PreferBlockAccess = true ,
CoordAccess = false , RawAccess = false
}
typedef TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device > Self
typedef TensorShufflingOp< Shuffle, ArgType > XprType
typedef XprType::Index Index
typedef DSizes< Index, NumDims > Dimensions
typedef XprType::Scalar Scalar
typedef XprType::CoeffReturnType CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef StorageMemory< CoeffReturnType, Device > Storage
typedef Storage::Type EvaluatorPointerType
typedef std::remove_const_t< Scalar > ScalarNoConst
typedef internal::TensorBlockDescriptor< NumDims, Index > TensorBlockDesc
typedef internal::TensorBlockScratchAllocator< Device > TensorBlockScratch
typedef internal::TensorMaterializedBlock< ScalarNoConst, NumDims, Layout, Index > TensorBlock
Public Member Functions
EIGEN_STRONG_INLINE TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType & coeffRef (Index index) const
template<int StoreMode>
EIGEN_STRONG_INLINE void writePacket (Index index, const PacketReturnType &x) const
template<typename TensorBlock >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void writeBlock (const TensorBlockDesc &desc, const TensorBlock &block)
Public Member Functions inherited from Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >
EIGEN_STRONG_INLINE TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const Dimensions & dimensions () const
EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (EvaluatorPointerType)
EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType packet (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::TensorBlockResourceRequirements getResourceRequirements () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorBlock block (TensorBlockDesc &desc, TensorBlockScratch &scratch, bool root_of_expr_ast=false) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
EIGEN_DEVICE_FUNC Storage::Type data () const
Static Public Attributes
static constexpr int NumDims = internal::array_size<typename TensorEvaluator<ArgType, Device>::Dimensions>::value
static constexpr int PacketSize = PacketType<CoeffReturnType, Device>::size
static constexpr int Layout = TensorEvaluator<ArgType, Device>::Layout
Static Public Attributes inherited from Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >
static constexpr int NumDims = internal::array_size<typename TensorEvaluator<ArgType, Device>::Dimensions>::value
static constexpr int PacketSize = PacketType<CoeffReturnType, Device>::size
static constexpr int Layout = TensorEvaluator<ArgType, Device>::Layout
Additional Inherited Members
Protected Member Functions inherited from Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index GetBlockOutputIndex (Index input_index, const DSizes< Index, NumDims > &input_block_strides, const DSizes< Index, NumDims > &output_block_strides, const DSizes< internal::TensorIntDivisor< Index >, NumDims > &fast_input_block_strides) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Index srcCoeff (Index index) const
Protected Attributes inherited from Eigen::TensorEvaluator< const TensorShufflingOp< Shuffle, ArgType >, Device >
Dimensions m_dimensions
bool m_is_identity
array< int, NumDims > m_shuffle
array< Index, NumDims > m_inverseShuffle
array< Index, NumDims > m_outputStrides
array< internal::TensorIntDivisor< Index >, NumDims > m_fastOutputStrides
array< Index, NumDims > m_inputStrides
array< Index, NumDims > m_unshuffledInputStrides
const Device EIGEN_DEVICE_REF m_device
TensorEvaluator< ArgType, Device > m_impl
Member Typedef Documentation
Base
template<typename Shuffle , typename ArgType , typename Device > typedef TensorEvaluator<const TensorShufflingOp<Shuffle, ArgType>, Device> Eigen::TensorEvaluator< TensorShufflingOp< Shuffle, ArgType >, Device >::Base
CoeffReturnType
template<typename Shuffle , typename ArgType , typename Device > typedef XprType::CoeffReturnType Eigen::TensorEvaluator< TensorShufflingOp< Shuffle, ArgType >, Device >::CoeffReturnType
Dimensions
template<typename Shuffle , typename ArgType , typename Device > typedef DSizes<Index, NumDims> Eigen::TensorEvaluator< TensorShufflingOp< Shuffle, ArgType >, Device >::Dimensions
Index
template<typename Shuffle , typename ArgType , typename Device > typedef XprType::Index Eigen::TensorEvaluator< TensorShufflingOp< Shuffle, ArgType >, Device >::Index
PacketReturnType
template<typename Shuffle , typename ArgType , typename Device > typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorEvaluator< TensorShufflingOp< Shuffle, ArgType >, Device >::PacketReturnType
Scalar
template<typename Shuffle , typename ArgType , typename Device > typedef XprType::Scalar Eigen::TensorEvaluator< TensorShufflingOp< Shuffle, ArgType >, Device >::Scalar
ScalarNoConst
template<typename Shuffle , typename ArgType , typename Device > typedef std::remove_const_t<Scalar> Eigen::TensorEvaluator< TensorShufflingOp< Shuffle, ArgType >, Device >::ScalarNoConst
TensorBlockDesc
template<typename Shuffle , typename ArgType , typename Device > typedef internal::TensorBlockDescriptor<NumDims, Index> Eigen::TensorEvaluator< TensorShufflingOp< Shuffle, ArgType >, Device >::TensorBlockDesc
XprType
template<typename Shuffle , typename ArgType , typename Device > typedef TensorShufflingOp<Shuffle, ArgType> Eigen::TensorEvaluator< TensorShufflingOp< Shuffle, ArgType >, Device >::XprType
Member Enumeration Documentation
anonymous enum
template<typename Shuffle , typename ArgType , typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
BlockAccess
PreferBlockAccess
RawAccess
        {
     IsAligned = false,
     PacketAccess = (PacketType<CoeffReturnType, Device>::size > 1),
     BlockAccess = TensorEvaluator<ArgType, Device>::RawAccess,
     PreferBlockAccess = true,
     RawAccess = false
   };
Constructor & Destructor Documentation
TensorEvaluator()
template<typename Shuffle , typename ArgType , typename Device > EIGEN_STRONG_INLINE Eigen::TensorEvaluator< TensorShufflingOp< Shuffle, ArgType >, Device >::TensorEvaluator (const XprType & op, const Device & device) inline
 : Base(op, device) {}
Member Function Documentation
coeffRef()
template<typename Shuffle , typename ArgType , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType& Eigen::TensorEvaluator< TensorShufflingOp< Shuffle, ArgType >, Device >::coeffRef (Index index) const inline
{
     return this->m_impl.coeffRef(this->srcCoeff(index));
   }
writeBlock()
template<typename Shuffle , typename ArgType , typename Device > template<typename TensorBlock > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< TensorShufflingOp< Shuffle, ArgType >, Device >::writeBlock (const TensorBlockDesc & desc, const TensorBlock & block) inline
{
     eigen_assert(this->m_impl.data() != NULL);
     typedef internal::TensorBlockIO<ScalarNoConst, Index, NumDims, Layout> TensorBlockIO;
     typedef typename TensorBlockIO::Dst TensorBlockIODst;
     typedef typename TensorBlockIO::Src TensorBlockIOSrc;
     const Scalar* block_buffer = block.data();
     // TODO(ezhulenev): TensorBlockIO should be able to read from any Eigen
     // expression with coefficient and packet access as `src`.
     void* mem = NULL;
     if (block_buffer == NULL) {
       mem = this->m_device.allocate(desc.size() * sizeof(Scalar));
       ScalarNoConst* buf = static_cast<ScalarNoConst*>(mem);
       typedef internal::TensorBlockAssignment<ScalarNoConst, NumDims, typename TensorBlock::XprType, Index>
           TensorBlockAssignment;
       TensorBlockAssignment::Run(
           TensorBlockAssignment::target(desc.dimensions(), internal::strides<Layout>(desc.dimensions()), buf),
           block.expr());
       block_buffer = buf;
     }
     // Read from block.
     TensorBlockIOSrc src(internal::strides<Layout>(desc.dimensions()), block_buffer);
     // Write to the output buffer.
     typename TensorBlockIO::Dimensions output_strides(this->m_unshuffledInputStrides);
     typename TensorBlockIO::Dimensions output_dimensions;
     for (int i = 0; i < NumDims; ++i) {
       output_dimensions[this->m_shuffle[i]] = desc.dimension(i);
     }
     TensorBlockIODst dst(output_dimensions, output_strides, this->m_impl.data(), this->srcCoeff(desc.offset()));
     // Reorder dimensions according to the shuffle.
     typename TensorBlockIO::DimensionsMap dst_to_src_dim_map;
     for (int i = 0; i < NumDims; ++i) {
       dst_to_src_dim_map[i] = static_cast<int>(this->m_inverseShuffle[i]);
     }
     TensorBlockIO::Copy(dst, src, dst_to_src_dim_map);
     // Deallocate temporary buffer used for the block materialization.
     if (mem != NULL) this->m_device.deallocate(mem);
   }
References Eigen::TensorEvaluator< Derived, Device >::block(), Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::data(), Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::dimension(), Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::dimensions(), eigen_assert, Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::expr(), i, Eigen::TensorEvaluator< Derived, Device >::m_device, Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::offset(), and Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::size().
writePacket()
template<typename Shuffle , typename ArgType , typename Device > template<int StoreMode> EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< TensorShufflingOp< Shuffle, ArgType >, Device >::writePacket (Index index, const PacketReturnType & x) const inline
{
     EIGEN_ALIGN_MAX std::remove_const_t<CoeffReturnType> values[PacketSize];
     internal::pstore<CoeffReturnType, PacketReturnType>(values, x);
     EIGEN_UNROLL_LOOP
     for (int i = 0; i < PacketSize; ++i) {
       this->coeffRef(index + i) = values[i];
     }
   }
References Eigen::TensorEvaluator< Derived, Device >::coeffRef(), EIGEN_ALIGN_MAX, EIGEN_UNROLL_LOOP, i, Eigen::TensorEvaluator< Derived, Device >::PacketSize, and plotDoE::x.
Member Data Documentation
Layout
template<typename Shuffle , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< TensorShufflingOp< Shuffle, ArgType >, Device >::Layout = TensorEvaluator<ArgType, Device>::Layout static constexpr
NumDims
template<typename Shuffle , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< TensorShufflingOp< Shuffle, ArgType >, Device >::NumDims = internal::array_size<typename TensorEvaluator<ArgType, Device>::Dimensions>::value static constexpr
PacketSize
template<typename Shuffle , typename ArgType , typename Device > constexpr int Eigen::TensorEvaluator< TensorShufflingOp< Shuffle, ArgType >, Device >::PacketSize = PacketType<CoeffReturnType, Device>::size static constexpr
The documentation for this struct was generated from the following file:
TensorShuffling.h