MercuryDPM: Eigen::internal::conj_helper< Packet, Packet, true, true > Struct Template Reference
Eigen::internal::conj_helper< Packet, Packet, true, true > Struct Template Reference
#include <ConjHelper.h>
Public Types
typedef Packet ResultType
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet pmadd (const Packet &x, const Packet &y, const Packet &c) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet pmul (const Packet &x, const Packet &y) const
Member Typedef Documentation
ResultType
template<typename Packet > typedef Packet Eigen::internal::conj_helper< Packet, Packet, true, true >::ResultType
Member Function Documentation
pmadd()
template<typename Packet > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet Eigen::internal::conj_helper< Packet, Packet, true, true >::pmadd (const Packet & x, const Packet & y, const Packet & c) const inline
{
     return Eigen::internal::pmadd(pconj(x), pconj(y), c);
   }
References calibrate::c, Eigen::internal::pconj(), Eigen::internal::pmadd(), plotDoE::x, and Eigen::internal::y.
pmul()
template<typename Packet > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Packet Eigen::internal::conj_helper< Packet, Packet, true, true >::pmul (const Packet & x, const Packet & y) const inline
{
     return pconj(Eigen::internal::pmul(x, y));
   }
References Eigen::internal::pconj(), Eigen::internal::pmul(), plotDoE::x, and Eigen::internal::y.
The documentation for this struct was generated from the following file:
ConjHelper.h