MercuryDPM: unsteady_vmtk_fsi.cc File Reference
unsteady_vmtk_fsi.cc File Reference
#include "generic.h"
#include "solid.h"
#include "constitutive.h"
#include "navier_stokes.h"
#include "poisson.h"
#include "linear_elasticity.h"
#include "meshes/tetgen_mesh.h"
Classes
class UnstructuredFSIProblem< FLUID_ELEMENT, SOLID_ELEMENT >
Unstructured 3D FSI problem.
Namespaces
Global_Parameters
Namespace for global parameters.
Enumerations
enum { Global_Parameters::Parallel_flow_lagrange_multiplier_id , Global_Parameters::FSI_interface_displacement_lagrange_multiplier_id }
Functions
int main (int argc, char **argv)
Demonstrate how to solve an unstructured 3D FSI problem.
Variables
bool Global_Parameters::Prescribe_pressure =false
Boolean to choose if inflow pressure (true) or volume flux are prescribed.
double Global_Parameters::P_in_max =0.0025
Max. inflow pressure (during periodic variation)
double Global_Parameters::Period =0.1
Period of periodic variation in inflow pressure.
double Global_Parameters::P_in =0.0
Fluid pressure on inflow boundary.
double Global_Parameters::P_out =-0.25
Fluid pressure on outflow boundary.
double Global_Parameters::Peak_prescribed_flow_rate =-1.0
Peak prescribed flow rate.
double Global_Parameters::Prescribed_flow_rate =Peak_prescribed_flow_rate
Prescribed flow rate.
Data * Global_Parameters::P_in_data_pt =0
Function Documentation
main()
int main (int argc , char ** argv)
Demonstrate how to solve an unstructured 3D FSI problem.
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Relax tolerance
  TetMeshBase::Tolerance_for_boundary_finding = 1e-10;
  // Label for output
  DocInfo doc_info;
  // Output directory
  doc_info.set_directory("RESLT");
  // Create generalised Hookean constitutive equations
  Global_Parameters::Constitutive_law_pt =
   new GeneralisedHookean(&Global_Parameters::Nu);
  //Set up the problem
  UnstructuredFSIProblem<
  PseudoSolidNodeUpdateElement<TTaylorHoodElement<3>, TPVDElement<3,3> >,
   TPVDElement<3,3> > problem;
  //Output initial configuration
  problem.doc_solution(doc_info);
  doc_info.number()++;
  //Set value of dt
  unsigned nsteps_per_period=40;
  double dt = Global_Parameters::Period/double(nsteps_per_period);
  problem.initialise_dt(dt);
  // Increment FSI parameter during steady runs
  unsigned nq=4;
  if (CommandLineArgs::Argc==2)
   {
    oomph_info << "Smaller number of steps for test\n";
    nq=1;
   }
  double q_increment=2.0e-6;
  for (unsigned iq=0;iq<nq;iq++)
   {
    // Bump up fsi parameter
    Global_Parameters::Q+=q_increment;
    // Doc parameters
    problem.doc_parameters();
    cout << "Steady solve...\n";
    // Solve the steady problem first
    problem.steady_newton_solve();
    //Output solution
    problem.doc_solution(doc_info);
    doc_info.number()++;
   }
  // Do timestepping
  unsigned nperiod=20;
  unsigned nstep=nperiod*nsteps_per_period;
  if (CommandLineArgs::Argc==2)
   {
    string arg=CommandLineArgs::Argv[1];
    oomph_info << "Smaller number of steps for test\n";
    nstep=1;
   }
  for (unsigned istep=0;istep<nstep;istep++)
   {
    cout << "Unsteady solve...\n";
    // Solve the problem
    problem.unsteady_newton_solve(dt);
    //Output solution
    problem.doc_solution(doc_info);
    doc_info.number()++;
   }
 } // end_of_main
References oomph::CommandLineArgs::Argc, oomph::CommandLineArgs::Argv, Global_Parameters::Constitutive_law_pt, e(), Global_Parameters::Nu, oomph::DocInfo::number(), oomph::oomph_info, Global_Parameters::Period, problem, Global_Parameters::Q, oomph::DocInfo::set_directory(), and Flag_definition::setup().