MercuryDPM: Eigen::internal::gemm_pack_lhs< Scalar, Index, DataMapper, Pack1, Pack2, Packet, ColMajor, Conjugate, PanelMode > Struct Template Reference
Eigen::internal::gemm_pack_lhs< Scalar, Index, DataMapper, Pack1, Pack2, Packet, ColMajor, Conjugate, PanelMode > Struct Template Reference
#include <GeneralBlockPanelKernel.h>
Public Types
typedef DataMapper::LinearMapper LinearMapper
Public Member Functions
EIGEN_DONT_INLINE void operator() (Scalar *blockA, const DataMapper &lhs, Index depth, Index rows, Index stride=0, Index offset=0)
Member Typedef Documentation
LinearMapper
template<typename Scalar , typename Index , typename DataMapper , int Pack1, int Pack2, typename Packet , bool Conjugate, bool PanelMode> typedef DataMapper::LinearMapper Eigen::internal::gemm_pack_lhs< Scalar, Index, DataMapper, Pack1, Pack2, Packet, ColMajor, Conjugate, PanelMode >::LinearMapper
Member Function Documentation
operator()()
template<typename Scalar , typename Index , typename DataMapper , int Pack1, int Pack2, typename Packet , bool Conjugate, bool PanelMode> EIGEN_DONT_INLINE void Eigen::internal::gemm_pack_lhs< Scalar, Index, DataMapper, Pack1, Pack2, Packet, ColMajor, Conjugate, PanelMode >::operator() (Scalar * blockA, const DataMapper & lhs, Index depth, Index rows, Index stride = 0, Index offset = 0)
{
   typedef typename unpacket_traits<Packet>::half HalfPacket;
   typedef typename unpacket_traits<typename unpacket_traits<Packet>::half>::half QuarterPacket;
   enum {
     PacketSize = unpacket_traits<Packet>::size,
     HalfPacketSize = unpacket_traits<HalfPacket>::size,
     QuarterPacketSize = unpacket_traits<QuarterPacket>::size,
     HasHalf = (int)HalfPacketSize < (int)PacketSize,
     HasQuarter = (int)QuarterPacketSize < (int)HalfPacketSize
   };
   EIGEN_ASM_COMMENT("EIGEN PRODUCT PACK LHS");
   EIGEN_UNUSED_VARIABLE(stride);
   EIGEN_UNUSED_VARIABLE(offset);
   eigen_assert(((!PanelMode) && stride == 0 && offset == 0) || (PanelMode && stride >= depth && offset <= stride));
   eigen_assert(((Pack1 % PacketSize) == 0 && Pack1 <= 4 * PacketSize) || (Pack1 <= 4));
   conj_if<NumTraits<Scalar>::IsComplex && Conjugate> cj;
   Index count = 0;
   const Index peeled_mc3 = Pack1 >= 3 * PacketSize ? (rows / (3 * PacketSize)) * (3 * PacketSize) : 0;
   const Index peeled_mc2 =
       Pack1 >= 2 * PacketSize ? peeled_mc3 + ((rows - peeled_mc3) / (2 * PacketSize)) * (2 * PacketSize) : 0;
   const Index peeled_mc1 =
       Pack1 >= 1 * PacketSize ? peeled_mc2 + ((rows - peeled_mc2) / (1 * PacketSize)) * (1 * PacketSize) : 0;
   const Index peeled_mc_half =
       Pack1 >= HalfPacketSize ? peeled_mc1 + ((rows - peeled_mc1) / (HalfPacketSize)) * (HalfPacketSize) : 0;
   const Index peeled_mc_quarter = Pack1 >= QuarterPacketSize ? (rows / (QuarterPacketSize)) * (QuarterPacketSize) : 0;
   const Index last_lhs_progress = rows > peeled_mc_quarter ? (rows - peeled_mc_quarter) & ~1 : 0;
   const Index peeled_mc0 = Pack2 >= PacketSize              ? peeled_mc_quarter
                            : Pack2 > 1 && last_lhs_progress ? (rows / last_lhs_progress) * last_lhs_progress
                                                             : 0;
   Index i = 0;
   // Pack 3 packets
   if (Pack1 >= 3 * PacketSize) {
     for (; i < peeled_mc3; i += 3 * PacketSize) {
       if (PanelMode) count += (3 * PacketSize) * offset;
       for (Index k = 0; k < depth; k++) {
         Packet A, B, C;
         A = lhs.template loadPacket<Packet>(i + 0 * PacketSize, k);
         B = lhs.template loadPacket<Packet>(i + 1 * PacketSize, k);
         C = lhs.template loadPacket<Packet>(i + 2 * PacketSize, k);
         pstore(blockA + count, cj.pconj(A));
         count += PacketSize;
         pstore(blockA + count, cj.pconj(B));
         count += PacketSize;
         pstore(blockA + count, cj.pconj(C));
         count += PacketSize;
       }
       if (PanelMode) count += (3 * PacketSize) * (stride - offset - depth);
     }
   }
   // Pack 2 packets
   if (Pack1 >= 2 * PacketSize) {
     for (; i < peeled_mc2; i += 2 * PacketSize) {
       if (PanelMode) count += (2 * PacketSize) * offset;
       for (Index k = 0; k < depth; k++) {
         Packet A, B;
         A = lhs.template loadPacket<Packet>(i + 0 * PacketSize, k);
         B = lhs.template loadPacket<Packet>(i + 1 * PacketSize, k);
         pstore(blockA + count, cj.pconj(A));
         count += PacketSize;
         pstore(blockA + count, cj.pconj(B));
         count += PacketSize;
       }
       if (PanelMode) count += (2 * PacketSize) * (stride - offset - depth);
     }
   }
   // Pack 1 packets
   if (Pack1 >= 1 * PacketSize) {
     for (; i < peeled_mc1; i += 1 * PacketSize) {
       if (PanelMode) count += (1 * PacketSize) * offset;
       for (Index k = 0; k < depth; k++) {
         Packet A;
         A = lhs.template loadPacket<Packet>(i + 0 * PacketSize, k);
         pstore(blockA + count, cj.pconj(A));
         count += PacketSize;
       }
       if (PanelMode) count += (1 * PacketSize) * (stride - offset - depth);
     }
   }
   // Pack half packets
   if (HasHalf && Pack1 >= HalfPacketSize) {
     for (; i < peeled_mc_half; i += HalfPacketSize) {
       if (PanelMode) count += (HalfPacketSize)*offset;
       for (Index k = 0; k < depth; k++) {
         HalfPacket A;
         A = lhs.template loadPacket<HalfPacket>(i + 0 * (HalfPacketSize), k);
         pstoreu(blockA + count, cj.pconj(A));
         count += HalfPacketSize;
       }
       if (PanelMode) count += (HalfPacketSize) * (stride - offset - depth);
     }
   }
   // Pack quarter packets
   if (HasQuarter && Pack1 >= QuarterPacketSize) {
     for (; i < peeled_mc_quarter; i += QuarterPacketSize) {
       if (PanelMode) count += (QuarterPacketSize)*offset;
       for (Index k = 0; k < depth; k++) {
         QuarterPacket A;
         A = lhs.template loadPacket<QuarterPacket>(i + 0 * (QuarterPacketSize), k);
         pstoreu(blockA + count, cj.pconj(A));
         count += QuarterPacketSize;
       }
       if (PanelMode) count += (QuarterPacketSize) * (stride - offset - depth);
     }
   }
   // Pack2 may be *smaller* than PacketSize—that happens for
   // products like real * complex, where we have to go half the
   // progress on the lhs in order to duplicate those operands to
   // address both real & imaginary parts on the rhs. This portion will
   // pack those half ones until they match the number expected on the
   // last peeling loop at this point (for the rhs).
   if (Pack2 < PacketSize && Pack2 > 1) {
     for (; i < peeled_mc0; i += last_lhs_progress) {
       if (PanelMode) count += last_lhs_progress * offset;
       for (Index k = 0; k < depth; k++)
         for (Index w = 0; w < last_lhs_progress; w++) blockA[count++] = cj(lhs(i + w, k));
       if (PanelMode) count += last_lhs_progress * (stride - offset - depth);
     }
   }
   // Pack scalars
   for (; i < rows; i++) {
     if (PanelMode) count += offset;
     for (Index k = 0; k < depth; k++) blockA[count++] = cj(lhs(i, k));
     if (PanelMode) count += (stride - offset - depth);
   }
 }
References EIGEN_ASM_COMMENT, eigen_assert, EIGEN_UNUSED_VARIABLE, i, int(), k, Eigen::internal::pstore(), Eigen::internal::pstoreu(), rows, and w.
The documentation for this struct was generated from the following file:
products/GeneralBlockPanelKernel.h