MercuryDPM: CGCoordinates::XYZ Class Reference
CGCoordinates::XYZ Class Reference
Defines the position of the CGPoint, in the non-averaged directions, i.e. all directions on which spatial coarse-graining is applied (all directions for XYZ); all other directions are averaged over homogeneously.
#include <XYZ.h>
Public Member Functions
void write (std::ostream &os) const
Writes the coordinates in human-readable form to an ostream.
Mdouble getDistanceSquared (const Vec3D &p) const
Returns the square of the distance between the particle p and the current CGPoint, in the non-averaged directions.
void setXYZ (Vec3D p)
Returns the position of the current CGPoint, in the non-averaged directions.
void setHalfExtend (Vec3D halfExtend)
Sets the extend of the current grid cell.
Mdouble getINormal (const BaseInteraction &c, const Vec3D &normal) const
For the Interaction between particles/walls P and I, this function returns the dot product between the normal vector of the interaction and the branch vector from the current CGPoint towards I.
Mdouble getPNormal (const BaseInteraction &c, const Vec3D &normal) const
For the Interaction between particles/walls P and I, this function returns the dot product between the normal vector of the interaction and the branch vector from the current CGPoint towards P.
Mdouble getCNormal (const BaseInteraction &c, const Vec3D &normal) const
For the Interaction between particles/walls P and I, this function returns the dot product between the normal vector of the interaction and the branch vector from the current CGPoint towards the contact point.
Mdouble getTangentialSquared (const BaseInteraction &c, Mdouble pNormal) const
For the Interaction between particles/walls P and I, this function returns the square of the minimum distance between the the current CGPoint and the branch vector between P and I.
Public Member Functions inherited from CGCoordinates::BaseCoordinates
virtual Mdouble getWeight ()
Static Public Member Functions
static void writeNames (std::ostream &os)
Writes the coordinate names in human-readable form to an ostream.
static Mdouble getVolumeOfAveragedDimensions (const Vec3D &min, const Vec3D &max)
returns the factor the CGFunction has to be divided by, due to integrating the variables over the averaged dimensions, 1.0 for XYZ.
static Mdouble getLength (const Vec3D &p)
Returns the length of the input vector in the non-averaged directions.
static Mdouble getGaussPrefactor (Mdouble width, Mdouble cutoff)
Computes the prefactor of the Gauss CGFunction, which is dependent on the number of non-averaged dimensions.
static Mdouble getGaussIntegralPrefactor (Mdouble distance, Mdouble width, Mdouble cutoff)
Computes the prefactor of the Gauss line integral, which is dependent on the number of non-averaged dimensions.
static void normalisePolynomialCoefficients (std::vector< Mdouble > &coefficients, Mdouble cutoff)
Normalises the coefficients of Polynomial CGFunction such that the integral over all non-averaged dimensions is unity.
static const unsigned countVariables ()
static bool isResolvedIn (unsigned i)
static std::string getName ()
Static Public Member Functions inherited from CGCoordinates::BaseCoordinates
static Mdouble getDomainVolume (const Vec3D &min, const Vec3D &max)
Protected Attributes
Vec3D p_
Vec3D pointHalfExtend_
Detailed Description
Defines the position of the CGPoint, in the non-averaged directions, i.e. all directions on which spatial coarse-graining is applied (all directions for XYZ); all other directions are averaged over homogeneously.
In addition to defining the spatial variable, the classes in CGCoordinates contain all functions that only depend on how many coordinate directions are locally resolved (i.e. not averaged over); e.g. getDistanceSquared and getVolumeOfAveragedDimensions.
The CGCoordinates class should be chosen such that the system in homogeneous (symmetric) in the averaged directions. E.g., periodic chutes are homogeneous in x, y and t, but varying in z, so Z should be used.
See member CGCoordinates for more details.
Member Function Documentation
countVariables()
const unsigned XYZ::countVariables () static
returns the number of variables (in this case three)
 {
     return 3;
 }
getCNormal()
Mdouble XYZ::getCNormal (const BaseInteraction & c, const Vec3D & normal) const
For the Interaction between particles/walls P and I, this function returns the dot product between the normal vector of the interaction and the branch vector from the current CGPoint towards the contact point.
Parameters
[in] c the Interaction object from which iNormal is computed
Returns
cNormal, one of the three distances needed to calculate the line integral \(\psi\) which defines the stress distribution (see image).
Illustration of the line integral
 {
     return Vec3D::dot(c.getContactPoint() - p_, c.getNormal());
 }
getDistanceSquared()
Mdouble XYZ::getDistanceSquared (const Vec3D & p) const
Returns the square of the distance between the particle p and the current CGPoint, in the non-averaged directions.
This function is needed to evaluate the CGFunction, as this function has the distance between the CGPoint and the Particle as an argument. To properly account for the averaging, the distance is only computed in the non-averaged directions.
Parameters
[in] p the position of a particle for which the distance is computed.
 {
     return Vec3D::getLengthSquared(p_ - p);
 }
References Vec3D::getLengthSquared(), p, and p_.
getGaussIntegralPrefactor()
Mdouble XYZ::getGaussIntegralPrefactor (Mdouble distance, Mdouble width, Mdouble cutoff) static
Computes the prefactor of the Gauss line integral, which is dependent on the number of non-averaged dimensions.
The prefactor of the Gauss line integral is set such that the integral over the non-averaged dimensions is unity.
Parameters
[in] distance length of the branch vector along which the line integral is evaluated.
[in] width width (equals the standard deviation in 1D) of the Gauss CGFunction.
[in] cutoff cutoff of the Gauss CGFunction
Returns
the prefactor of the Gauss CGFunction.
 {
     Mdouble widthSqrt2 = width * constants::sqrt_2;
     Mdouble a = -cutoff;
     Mdouble b = cutoff + distance;
     //full 2D prefactor
     Mdouble prefactor = 1.0 / (constants::sqrt_2 * constants::sqrt_pi * width);
     prefactor = mathsFunc::square(prefactor) / (1.0 - exp(-0.5 * mathsFunc::square(cutoff / width)));
     return prefactor * 0.5 / (
             +erf(b / widthSqrt2) * b
             + widthSqrt2 / constants::sqrt_pi * exp(-mathsFunc::square(b / widthSqrt2))
             - erf(a / widthSqrt2) * a
             - widthSqrt2 / constants::sqrt_pi * exp(-mathsFunc::square(a / widthSqrt2))
     );
 }
References a, b, Eigen::bfloat16_impl::exp(), constants::sqrt_2, constants::sqrt_pi, and mathsFunc::square().
getGaussPrefactor()
Mdouble XYZ::getGaussPrefactor (Mdouble width, Mdouble cutoff) static
Computes the prefactor of the Gauss CGFunction, which is dependent on the number of non-averaged dimensions.
The prefactor of the Gauss CGFunction is set such that the integral over the non-averaged dimensions is unity.
Parameters
[in] width width (equals the standard deviation in 1D) of the Gauss CGFunction.
[in] cutoff cutoff of the Gauss CGFunction
Returns
the prefactor of the Gauss CGFunction.
 {
     //Wolfram alpha: erf(c/(sqrt(2) w))-(sqrt(2/pi) c e^(-c^2/(2 w^2)))/w
     Mdouble prefactor = 1.0 / (constants::sqrt_2 * constants::sqrt_pi * width);
     Mdouble cw = cutoff / width;
     return mathsFunc::cubic(prefactor) / (
             erf(cw / constants::sqrt_2)
             - constants::sqrt_2 / constants::sqrt_pi * cw * exp(-0.5 * mathsFunc::square(cw))
     );
 }
References mathsFunc::cubic(), Eigen::bfloat16_impl::exp(), constants::sqrt_2, constants::sqrt_pi, and mathsFunc::square().
getINormal()
Mdouble XYZ::getINormal (const BaseInteraction & c, const Vec3D & normal) const
For the Interaction between particles/walls P and I, this function returns the dot product between the normal vector of the interaction and the branch vector from the current CGPoint towards I.
Parameters
[in] c the Interaction object from which iNormal is computed
Returns
iNormal, one of the three distances needed to calculate the line integral \(\psi\) which defines the stress distribution (see image).
Illustration of the line integral
 {
     return Vec3D::dot(c.getI()->getPosition() - p_, c.getNormal());
 }
References calibrate::c, Vec3D::dot(), and p_.
getLength()
Mdouble XYZ::getLength (const Vec3D & p) static
Returns the length of the input vector in the non-averaged directions.
Parameters
[in] p vector whose length should be determined
Returns
length of the vector in the non-averaged directions
Todo:
 {
     return sqrt(p.X * p.X + p.Y * p.Y + p.Z * p.Z);
 }
References p, and sqrt().
getName()
std::string XYZ::getName () static
 {
     return "XYZ";
 }
getPNormal()
Mdouble XYZ::getPNormal (const BaseInteraction & c, const Vec3D & normal) const
For the Interaction between particles/walls P and I, this function returns the dot product between the normal vector of the interaction and the branch vector from the current CGPoint towards P.
Parameters
[in] c the Interaction object from which iNormal is computed
Returns
pNormal, one of the three distances needed to calculate the line integral \(\psi\) which defines the stress distribution (see image).
Illustration of the line integral
 {
     return Vec3D::dot(c.getP()->getPosition() - p_, c.getNormal());
 }
getTangentialSquared()
Mdouble XYZ::getTangentialSquared (const BaseInteraction & c, Mdouble pNormal) const
For the Interaction between particles/walls P and I, this function returns the square of the minimum distance between the the current CGPoint and the branch vector between P and I.
Parameters
[in] c the Interaction object from which iNormal is computed
[in] pNormal the output of getPNormal needed for the computation.
Returns
iNormal, one of the three distances needed to calculate the line integral \(\psi\) which defines the stress distribution (see image).
Illustration of the line integral
 {
     return Vec3D::getLengthSquared(c.getP()->getPosition() - p_) - mathsFunc::square(pNormal);
 }
References calibrate::c, Vec3D::getLengthSquared(), p_, and mathsFunc::square().
getVolumeOfAveragedDimensions()
Mdouble XYZ::getVolumeOfAveragedDimensions (const Vec3D & min, const Vec3D & max) static
returns the factor the CGFunction has to be divided by, due to integrating the variables over the averaged dimensions, 1.0 for XYZ.
If averaged dimensions are present (i.e. for all Coordinates except XYZ), the CGFunction has to be divided by a factor (here called volume) due to integrating the variables over the averaged dimensions.
Parameters
[in] min the lower limits of the mesh domain (xMin, yMin, zMin)
[in] max the upper limits of the mesh domain (xMax, yMax, zMax)
Returns
the volume factor
 {
     return 1.0;
 }
isResolvedIn()
static bool CGCoordinates::XYZ::isResolvedIn (unsigned i) inline static
 {return true;}
normalisePolynomialCoefficients()
void XYZ::normalisePolynomialCoefficients (std::vector< Mdouble > & coefficients, Mdouble cutoff) static
Normalises the coefficients of Polynomial CGFunction such that the integral over all non-averaged dimensions is unity.
The volume is computed as
\[volume= \int_0^1\sum_{i=1}^n c_i r/c^i 4 pi r^2 dr = 4 pi \sum_{i=1}^n c_i/(i+3) \]
with 4 pi r^2 the surface area of a sphere.
Parameters
[in,out] coefficients the coefficients of Polynomial CGFunctions.
[in] cutoff cutoff of the Gauss CGFunction
 {
     Mdouble volume = 0.0;
     for (std::size_t i = 0; i < coefficients.size(); i++)
         volume += coefficients[i] / static_cast<Mdouble>(i + 3);
     volume *= 4.0 * constants::pi * mathsFunc::cubic(cutoff);
     for (double& coefficient : coefficients)
         coefficient /= volume;
 }
References mathsFunc::cubic(), i, and constants::pi.
setHalfExtend()
void CGCoordinates::XYZ::setHalfExtend (Vec3D halfExtend) inline
Sets the extend of the current grid cell.
 { pointHalfExtend_ = halfExtend; }
References pointHalfExtend_.
setXYZ()
void XYZ::setXYZ (Vec3D p)
Returns the position of the current CGPoint, in the non-averaged directions.
Parameters
[in] p the position that is to be set.
 {
     p_ = p;
 }
References p, and p_.
Referenced by VolumeCoupling::getProjectionMatrix().
write()
void XYZ::write (std::ostream & os) const
Writes the coordinates in human-readable form to an ostream.
Parameters
[out] os the ostream file to which the position is written
 {
     os << p_ << ' ';
 }
References p_.
writeNames()
void XYZ::writeNames (std::ostream & os) static
Writes the coordinate names in human-readable form to an ostream.
 {
     os << "x y z ";
 }
Member Data Documentation
p_
Vec3D CGCoordinates::XYZ::p_ protected
The position of the current CGPoint.
Referenced by getDistanceSquared(), getINormal(), getTangentialSquared(), setXYZ(), and write().
pointHalfExtend_
Vec3D CGCoordinates::XYZ::pointHalfExtend_ protected
Referenced by setHalfExtend().
The documentation for this class was generated from the following files:
XYZ.h
XYZ.cc