MercuryDPM: oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT > Class Template Reference
oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT > Class Template Reference
#include <navier_stokes_elements_with_singularity.h>
Public Types
typedef Vector< double >(* NavierStokesVelocitySingularFctPt) (const Vector< double > &x)
Function pointer to the velocity singular function:
typedef Vector< Vector< double > >(* NavierStokesGradVelocitySingularFctPt) (const Vector< double > &x)
Function pointer to the gradient of the velocity singular function:
typedef double(* NavierStokesPressureSingularFctPt) (const Vector< double > &x)
Function pointer to the pressure singular function:
typedef Vector< double >(* NavierStokesGradPressureSingularFctPt) (const Vector< double > &x)
Function pointer to the gradient of the pressure singular function:
Public Member Functions
SingularNavierStokesSolutionElement ()
Constructor.
bool & singular_function_satisfies_stokes_equation ()
double c () const
Find the value of the unknown amplitude C.
void set_c (const double &value)
Find the value of the unknown amplitude C.
void pin_c ()
Pin the value of the unknown amplitude C.
void unpin_c ()
Unpin the value of the unknown amplitude C.
void set_wrapped_navier_stokes_element_pt (WRAPPED_NAVIER_STOKES_ELEMENT *wrapped_navier_stokes_el_pt, const Vector< double > &s, unsigned *direction_pt)
NavierStokesVelocitySingularFctPt & velocity_singular_fct_pt ()
Access function to pointer to velocity singular function.
NavierStokesGradVelocitySingularFctPt & grad_velocity_singular_fct_pt ()
Access function to pointer to gradient of velocity singular function.
NavierStokesPressureSingularFctPt & pressure_singular_fct_pt ()
Access function to pointer to pressure singular function.
NavierStokesGradPressureSingularFctPt & grad_pressure_singular_fct_pt ()
Access function to pointer to gradient of pressure singular function.
Vector< double > velocity_singular_function (const Vector< double > &x) const
Evaluate velocity singular function at Eulerian position x.
Vector< Vector< double > > grad_velocity_singular_function (const Vector< double > &x) const
double pressure_singular_function (const Vector< double > &x) const
Evaluate pressure singular function at Eulerian position x.
Vector< double > grad_pressure_singular_function (const Vector< double > &x) const
Evaluate gradient of pressure singular function at Eulerian position x.
Vector< double > u_bar (const Vector< double > &x)
Vector< Vector< double > > grad_u_bar (const Vector< double > &x)
double p_bar (const Vector< double > &x)
Vector< double > grad_p_bar (const Vector< double > &x)
void fill_in_contribution_to_residuals (Vector< double > &residual)
Compute residual.
void fill_in_contribution_to_jacobian (Vector< double > &residual, DenseMatrix< double > &jacobian)
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual unsigned self_test ()
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Private Member Functions
void fill_in_generic_contribution_to_residuals (Vector< double > &residual, DenseMatrix< double > &jacobian, const unsigned &flag)
Compute local residual, and, if flag=1, local jacobian matrix.
Private Attributes
WRAPPED_NAVIER_STOKES_ELEMENT * Wrapped_navier_stokes_el_pt
Pointer to wrapped Navier-Stokes element.
NavierStokesVelocitySingularFctPt Velocity_singular_fct_pt
Pointer to velocity singular function.
NavierStokesGradVelocitySingularFctPt Grad_velocity_singular_fct_pt
NavierStokesPressureSingularFctPt Pressure_singular_fct_pt
Pointer to pressure singular function.
NavierStokesGradPressureSingularFctPt Grad_pressure_singular_fct_pt
Pointer to gradient of pressure singular function.
Vector< double > S_in_wrapped_navier_stokes_element
Local coordinates of singulariity in wrapped Navier-Stokes element.
unsigned * Direction_pt
Direction of the derivative used for the residual of the element.
bool Singular_function_satisfies_stokes_equation
Additional Inherited Members
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
template<class WRAPPED_NAVIER_STOKES_ELEMENT>
class oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >
We consider a singularity in the solution at the point O.
This class defines the singular functions.
velocity_singularity:
u_bar = C*velocity_singular_function
pressure_singularity:
p_bar = C*pressure_singular_function
and their gradients
The class also defines the function that computes the residual associated to C which is:
R_C = \frac{\partial p_FE}{\partial x_i} (O)
and thus regularises the FE solution by setting the pressure gradient in the coordinate direction x_i to zero. If the amplitude of the singular solution is known, pin C.
Member Typedef Documentation
NavierStokesGradPressureSingularFctPt
template<class WRAPPED_NAVIER_STOKES_ELEMENT > typedef Vector<double>(* oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::NavierStokesGradPressureSingularFctPt) (const Vector< double > &x)
Function pointer to the gradient of the pressure singular function:
NavierStokesGradVelocitySingularFctPt
template<class WRAPPED_NAVIER_STOKES_ELEMENT > typedef Vector<Vector<double> >(* oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::NavierStokesGradVelocitySingularFctPt) (const Vector< double > &x)
Function pointer to the gradient of the velocity singular function:
NavierStokesPressureSingularFctPt
template<class WRAPPED_NAVIER_STOKES_ELEMENT > typedef double(* oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::NavierStokesPressureSingularFctPt) (const Vector< double > &x)
Function pointer to the pressure singular function:
NavierStokesVelocitySingularFctPt
template<class WRAPPED_NAVIER_STOKES_ELEMENT > typedef Vector<double>(* oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::NavierStokesVelocitySingularFctPt) (const Vector< double > &x)
Function pointer to the velocity singular function:
Constructor & Destructor Documentation
SingularNavierStokesSolutionElement()
template<class WRAPPED_NAVIER_STOKES_ELEMENT > oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::SingularNavierStokesSolutionElement () inline
Constructor.
   {
    // Initialise Function pointer to velocity singular function to NULL
    Velocity_singular_fct_pt=0;
    // Initialise Function pointer to gradient of velocity singular
    // function to NULL
    Grad_velocity_singular_fct_pt=0;
    // Initialise Function pointer to pressure singular function to NULL
    Pressure_singular_fct_pt=0;
    // Initialise Function pointer to gradient of pressure singular
    // function to NULL
    Grad_pressure_singular_fct_pt=0;
    // Initalise pointer to the wrapped Navier-Stokes element which will be
    // used to compute the residual and which includes the point O
    Wrapped_navier_stokes_el_pt=0;
    // Initialise the pointer to the direction of the derivative used
    // for the residual of this element
    Direction_pt=0;
    // Safe assumption: Singular fct does not satisfy Stokes eqn
    Singular_function_satisfies_stokes_equation=false;
    // Create a single item of internal Data, storing one unknown which
    // represents the unknown C.
    add_internal_data(new Data(1));
   }
References oomph::GeneralisedElement::add_internal_data(), oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::Direction_pt, oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::Grad_pressure_singular_fct_pt, oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::Grad_velocity_singular_fct_pt, oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::Pressure_singular_fct_pt, oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::Singular_function_satisfies_stokes_equation, oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::Velocity_singular_fct_pt, and oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::Wrapped_navier_stokes_el_pt.
Member Function Documentation
c()
template<class WRAPPED_NAVIER_STOKES_ELEMENT > double oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::c () const inline
Find the value of the unknown amplitude C.
  {
   return internal_data_pt(0)->value(0);
  }
References oomph::GeneralisedElement::internal_data_pt(), and oomph::Data::value().
Referenced by oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::grad_p_bar(), oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::grad_u_bar(), oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::p_bar(), and oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::u_bar().
fill_in_contribution_to_jacobian()
template<class WRAPPED_NAVIER_STOKES_ELEMENT > void oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::fill_in_contribution_to_jacobian (Vector< double > & residuals, DenseMatrix< double > & jacobian) inline virtual
Add the elemental contribution to the jacobian matrix. and the residuals vector. Note that this function will NOT initialise the residuals vector or the jacobian matrix. It must be called after the residuals vector and jacobian matrix have been initialised to zero. The default is to use finite differences to calculate the jacobian
Reimplemented from oomph::GeneralisedElement.
  {
   fill_in_generic_contribution_to_residuals(residual,jacobian,1);
  }
References oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::fill_in_generic_contribution_to_residuals().
fill_in_contribution_to_residuals()
template<class WRAPPED_NAVIER_STOKES_ELEMENT > void oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::fill_in_contribution_to_residuals (Vector< double > & residual) inline virtual
Compute residual.
Reimplemented from oomph::GeneralisedElement.
  {
   fill_in_generic_contribution_to_residuals
    (residual,GeneralisedElement::Dummy_matrix,0);
  }
References oomph::GeneralisedElement::Dummy_matrix, and oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::fill_in_generic_contribution_to_residuals().
fill_in_generic_contribution_to_residuals()
template<class WRAPPED_NAVIER_STOKES_ELEMENT > void oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::fill_in_generic_contribution_to_residuals (Vector< double > & residual, DenseMatrix< double > & jacobian, const unsigned & flag) inline private
Compute local residual, and, if flag=1, local jacobian matrix.
  {
   // Get the local eqn number of our one-and-only
   // unknown
   int eqn_number=internal_local_eqn(0,0);
   if (eqn_number>=0)
    {
     residual[eqn_number] = Wrapped_navier_stokes_el_pt->dpdx_fe_only
      (S_in_wrapped_navier_stokes_element,Direction_pt);
     // Do we want the Jacobian too?
     if (flag)
      {
       // Find the number of pressure dofs in the wrapped Navier-Stokes
       // element pointed by
       // the SingularNavierStokesSolutionElement class
       unsigned n_pres = Wrapped_navier_stokes_el_pt->npres_nst();
       // Find the dimension of the problem
       unsigned cached_dim=Wrapped_navier_stokes_el_pt->dim();
       // Set up memory for the pressure shape functions and their derivatives
       Shape psip(n_pres), testp(n_pres);
       DShape dpsipdx(n_pres,cached_dim), dtestpdx(n_pres,cached_dim);
       // Compute the pressure shape functions and their derivatives
       // at the local coordinate S_in_wrapped_navier_stokes_element
       // (Test fcts not really needed but nobody's got around to writing
       // a fct that only picks out the basis fcts.
       Wrapped_navier_stokes_el_pt->dpshape_and_dptest_eulerian_nst
        (S_in_wrapped_navier_stokes_element,psip,dpsipdx,testp,dtestpdx);
       // Derivs
       for (unsigned j=0;j<n_pres;j++)
        {
         // Unknown
         int local_unknown = Wrapped_navier_stokes_el_pt->p_local_eqn(j);
         // If not pinned
         if (local_unknown >= 0)
          {
           // Add the contribution of the node to the local jacobian
           jacobian(eqn_number,local_unknown) = dpsipdx(j,*Direction_pt);
          }
        }
      }
    }
  }
References oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::Direction_pt, oomph::GeneralisedElement::eqn_number(), oomph::GeneralisedElement::internal_local_eqn(), j, oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::S_in_wrapped_navier_stokes_element, and oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::Wrapped_navier_stokes_el_pt.
Referenced by oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::fill_in_contribution_to_jacobian(), and oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::fill_in_contribution_to_residuals().
grad_p_bar()
template<class WRAPPED_NAVIER_STOKES_ELEMENT > Vector<double> oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::grad_p_bar (const Vector< double > & x) inline
Evaluate gradient of pressure singular function (including its amplitude): grad_p_bar = C * grad_pressure_singular
  {
   // Find the value of C
   double c=internal_data_pt(0)->value(0);
   // Initialise the gradient of pressure
   Vector<double> grad_p=grad_pressure_singular_function(x);
   // Find the dimension of the problem
   unsigned cached_dim=Wrapped_navier_stokes_el_pt->dim();
   // Multiply the components of the gradient of pressure by the unknown C
   for (unsigned d=0;d<cached_dim;d++)
    {
     grad_p[d] *= c;
    }
   // Value of grad_p_bar at the position x
   return grad_p;
  }
References oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::c(), oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::grad_pressure_singular_function(), oomph::GeneralisedElement::internal_data_pt(), oomph::Data::value(), oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::Wrapped_navier_stokes_el_pt, and plotDoE::x.
grad_pressure_singular_fct_pt()
template<class WRAPPED_NAVIER_STOKES_ELEMENT > NavierStokesGradPressureSingularFctPt& oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::grad_pressure_singular_fct_pt () inline
Access function to pointer to gradient of pressure singular function.
   {return Grad_pressure_singular_fct_pt;}
References oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::Grad_pressure_singular_fct_pt.
grad_pressure_singular_function()
template<class WRAPPED_NAVIER_STOKES_ELEMENT > Vector<double> oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::grad_pressure_singular_function (const Vector< double > & x) const inline
Evaluate gradient of pressure singular function at Eulerian position x.
   {
 #ifdef PARANOID
    if (Grad_pressure_singular_fct_pt==0)
     {
      std::stringstream error_stream;
      error_stream
       << "Pointer to gradient of pressure singular function "
       << "hasn't been defined!"
       << std::endl;
      throw OomphLibError(
       error_stream.str(),
       OOMPH_CURRENT_FUNCTION,
       OOMPH_EXCEPTION_LOCATION);
     }
 #endif
    // Evaluate gradient of pressure singular function
    return (*Grad_pressure_singular_fct_pt)(x);
   }
References oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::Grad_pressure_singular_fct_pt, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and plotDoE::x.
Referenced by oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::grad_p_bar().
grad_u_bar()
template<class WRAPPED_NAVIER_STOKES_ELEMENT > Vector<Vector<double> > oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::grad_u_bar (const Vector< double > & x) inline
Evaluate gradient of velocity singular function (including its amplitude): grad_u_bar = C * grad_velocity_singular; grad[i][j] = du_i/dx_j
   {
    // Find the value of C
    double c=internal_data_pt(0)->value(0);
    // Initialise the gradient of velocity vector
    Vector<Vector<double> > grad_u=grad_velocity_singular_function(x);
    // Find the dimension of the problem
    unsigned cached_dim=Wrapped_navier_stokes_el_pt->dim();
    // Multiply the components of the gradient of velocity by the unknown C
    for (unsigned d=0;d<cached_dim;d++)
     {
      for (unsigned i=0;i<cached_dim;i++)
       {
        grad_u[d][i] *= c;
       }
     }
    // Value of grad_u_bar at the position x
    return grad_u;
   }
References oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::c(), oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::grad_velocity_singular_function(), i, oomph::GeneralisedElement::internal_data_pt(), oomph::Data::value(), oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::Wrapped_navier_stokes_el_pt, and plotDoE::x.
grad_velocity_singular_fct_pt()
template<class WRAPPED_NAVIER_STOKES_ELEMENT > NavierStokesGradVelocitySingularFctPt& oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::grad_velocity_singular_fct_pt () inline
Access function to pointer to gradient of velocity singular function.
   {return Grad_velocity_singular_fct_pt;}
References oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::Grad_velocity_singular_fct_pt.
grad_velocity_singular_function()
template<class WRAPPED_NAVIER_STOKES_ELEMENT > Vector<Vector<double> > oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::grad_velocity_singular_function (const Vector< double > & x) const inline
Evaluate gradient of velocity singular function at Eulerian position x. grad[i][j] = du_i/dx_j
   {
 #ifdef PARANOID
    if (Grad_velocity_singular_fct_pt==0)
     {
      std::stringstream error_stream;
      error_stream
       << "Pointer to gradient of velocity singular function "
       << "hasn't been defined!"
       << std::endl;
      throw OomphLibError(
       error_stream.str(),
       OOMPH_CURRENT_FUNCTION,
       OOMPH_EXCEPTION_LOCATION);
     }
 #endif
    // Evaluate gradient of velocity singular function
    return (*Grad_velocity_singular_fct_pt)(x);
   }
References oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::Grad_velocity_singular_fct_pt, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and plotDoE::x.
Referenced by oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::grad_u_bar().
p_bar()
template<class WRAPPED_NAVIER_STOKES_ELEMENT > double oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::p_bar (const Vector< double > & x) inline
Evaluate pressure singular function (including its amplitude): p_bar = C * pressure_singular
  {
   // Find the value of C
   double c=internal_data_pt(0)->value(0);
   // Value of p_bar at the position x
   return c*pressure_singular_function(x);
  }
References oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::c(), oomph::GeneralisedElement::internal_data_pt(), oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::pressure_singular_function(), oomph::Data::value(), and plotDoE::x.
pin_c()
template<class WRAPPED_NAVIER_STOKES_ELEMENT > void oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::pin_c () inline
Pin the value of the unknown amplitude C.
  {
   return internal_data_pt(0)->pin(0);
  }
References oomph::GeneralisedElement::internal_data_pt(), and oomph::Data::pin().
pressure_singular_fct_pt()
template<class WRAPPED_NAVIER_STOKES_ELEMENT > NavierStokesPressureSingularFctPt& oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::pressure_singular_fct_pt () inline
Access function to pointer to pressure singular function.
   {return Pressure_singular_fct_pt;}
References oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::Pressure_singular_fct_pt.
pressure_singular_function()
template<class WRAPPED_NAVIER_STOKES_ELEMENT > double oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::pressure_singular_function (const Vector< double > & x) const inline
Evaluate pressure singular function at Eulerian position x.
  {
 #ifdef PARANOID
   if (Pressure_singular_fct_pt==0)
    {
     std::stringstream error_stream;
     error_stream
      << "Pointer to pressure singular function hasn't been defined!"
      << std::endl;
     throw OomphLibError(
      error_stream.str(),
      OOMPH_CURRENT_FUNCTION,
      OOMPH_EXCEPTION_LOCATION);
    }
 #endif
   // Evaluate pressure singular function
   return (*Pressure_singular_fct_pt)(x);
  }
References OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::Pressure_singular_fct_pt, and plotDoE::x.
Referenced by oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::p_bar().
set_c()
template<class WRAPPED_NAVIER_STOKES_ELEMENT > void oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::set_c (const double & value) inline
Find the value of the unknown amplitude C.
  {
   internal_data_pt(0)->set_value(0,value);
  }
References oomph::GeneralisedElement::internal_data_pt(), oomph::Data::set_value(), and Eigen::value.
set_wrapped_navier_stokes_element_pt()
template<class WRAPPED_NAVIER_STOKES_ELEMENT > void oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::set_wrapped_navier_stokes_element_pt (WRAPPED_NAVIER_STOKES_ELEMENT * wrapped_navier_stokes_el_pt, const Vector< double > & s, unsigned * direction_pt) inline
Set pointer to associated wrapped Navier-Stokes element which contains the singularity (at local coordinate s). Also specify the direction in which the slope of the FE part of the pressure is set to zero. (Could also set a velocity derivative to zero but this needs to be done with a separate function. Write it if you need it...)
  {
   // Assign the pointer to the variable Wrapped_navier_stokes_el_pt
   Wrapped_navier_stokes_el_pt = wrapped_navier_stokes_el_pt;
   // Find number of nodes in the element
   unsigned nnod=wrapped_navier_stokes_el_pt->nnode();
   // Loop over the nodes of the element
   for (unsigned j=0;j<nnod;j++)
    {
     // Add the node as external data in the
     // SingularNavierStokesSolutionElement class. Note that this
     // assumes that the pressure is stored at the nodes (Taylor Hood type
     // NSt elements, which is assumed elsewhere too...)
     add_external_data(Wrapped_navier_stokes_el_pt->node_pt(j));
    }
   // Assign the pointer to the local coordinate at which the residual
   // will be computed
   S_in_wrapped_navier_stokes_element = s;
   // Assign the pointer to the direction at which the derivative used
   // in the residual will be computed
   Direction_pt = direction_pt;
  }
References oomph::GeneralisedElement::add_external_data(), oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::Direction_pt, j, s, oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::S_in_wrapped_navier_stokes_element, and oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::Wrapped_navier_stokes_el_pt.
singular_function_satisfies_stokes_equation()
template<class WRAPPED_NAVIER_STOKES_ELEMENT > bool& oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::singular_function_satisfies_stokes_equation () inline
Assert that singular function satisfies the Stokes equations by setting this to true or false.
   {
    return Singular_function_satisfies_stokes_equation;
   }
References oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::Singular_function_satisfies_stokes_equation.
u_bar()
template<class WRAPPED_NAVIER_STOKES_ELEMENT > Vector<double> oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::u_bar (const Vector< double > & x) inline
Evaluate velocity singular function (including its amplitude): u_bar = C * velocity_singular
   {
    // Find the value of C
    double c=internal_data_pt(0)->value(0);
    // Initialise the velocity vector
    Vector<double> u=velocity_singular_function(x);
    // Find the dimension of the problem
    unsigned cached_dim=Wrapped_navier_stokes_el_pt->dim();
    // Multiply the components of the velocity vector by the unknown C
    for (unsigned d=0;d<cached_dim;d++)
     {
      u[d] *= c;
     }
    // Value of u_bar at the position x
    return u;
   }
References oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::c(), oomph::GeneralisedElement::internal_data_pt(), oomph::Data::value(), oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::velocity_singular_function(), oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::Wrapped_navier_stokes_el_pt, and plotDoE::x.
unpin_c()
template<class WRAPPED_NAVIER_STOKES_ELEMENT > void oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::unpin_c () inline
Unpin the value of the unknown amplitude C.
  {
   return internal_data_pt(0)->unpin(0);
  }
References oomph::GeneralisedElement::internal_data_pt(), and oomph::Data::unpin().
velocity_singular_fct_pt()
template<class WRAPPED_NAVIER_STOKES_ELEMENT > NavierStokesVelocitySingularFctPt& oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::velocity_singular_fct_pt () inline
Access function to pointer to velocity singular function.
   {return Velocity_singular_fct_pt;}
References oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::Velocity_singular_fct_pt.
velocity_singular_function()
template<class WRAPPED_NAVIER_STOKES_ELEMENT > Vector<double> oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::velocity_singular_function (const Vector< double > & x) const inline
Evaluate velocity singular function at Eulerian position x.
   {
 #ifdef PARANOID
    if (Velocity_singular_fct_pt==0)
     {
      std::stringstream error_stream;
      error_stream
       << "Pointer to velocity singular function hasn't been defined!"
       << std::endl;
      throw OomphLibError(
       error_stream.str(),
       OOMPH_CURRENT_FUNCTION,
       OOMPH_EXCEPTION_LOCATION);
     }
 #endif
    // Evaluate velocity singular function
    return (*Velocity_singular_fct_pt)(x);
   }
References OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::Velocity_singular_fct_pt, and plotDoE::x.
Referenced by oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::u_bar().
Member Data Documentation
Direction_pt
template<class WRAPPED_NAVIER_STOKES_ELEMENT > unsigned* oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::Direction_pt private
Direction of the derivative used for the residual of the element.
Referenced by oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::fill_in_generic_contribution_to_residuals(), oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::set_wrapped_navier_stokes_element_pt(), and oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::SingularNavierStokesSolutionElement().
Grad_pressure_singular_fct_pt
template<class WRAPPED_NAVIER_STOKES_ELEMENT > NavierStokesGradPressureSingularFctPt oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::Grad_pressure_singular_fct_pt private
Pointer to gradient of pressure singular function.
Referenced by oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::grad_pressure_singular_fct_pt(), oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::grad_pressure_singular_function(), and oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::SingularNavierStokesSolutionElement().
Grad_velocity_singular_fct_pt
template<class WRAPPED_NAVIER_STOKES_ELEMENT > NavierStokesGradVelocitySingularFctPt oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::Grad_velocity_singular_fct_pt private
Pointer to gradient of velocity singular function; grad[i][j] = du_i/dx_j
Referenced by oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::grad_velocity_singular_fct_pt(), oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::grad_velocity_singular_function(), and oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::SingularNavierStokesSolutionElement().
Pressure_singular_fct_pt
template<class WRAPPED_NAVIER_STOKES_ELEMENT > NavierStokesPressureSingularFctPt oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::Pressure_singular_fct_pt private
Pointer to pressure singular function.
Referenced by oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::pressure_singular_fct_pt(), oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::pressure_singular_function(), and oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::SingularNavierStokesSolutionElement().
S_in_wrapped_navier_stokes_element
template<class WRAPPED_NAVIER_STOKES_ELEMENT > Vector<double> oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::S_in_wrapped_navier_stokes_element private
Local coordinates of singulariity in wrapped Navier-Stokes element.
Referenced by oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::fill_in_generic_contribution_to_residuals(), and oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::set_wrapped_navier_stokes_element_pt().
Singular_function_satisfies_stokes_equation
template<class WRAPPED_NAVIER_STOKES_ELEMENT > bool oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::Singular_function_satisfies_stokes_equation private
Referenced by oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::singular_function_satisfies_stokes_equation(), and oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::SingularNavierStokesSolutionElement().
Velocity_singular_fct_pt
template<class WRAPPED_NAVIER_STOKES_ELEMENT > NavierStokesVelocitySingularFctPt oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::Velocity_singular_fct_pt private
Pointer to velocity singular function.
Referenced by oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::SingularNavierStokesSolutionElement(), oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::velocity_singular_fct_pt(), and oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::velocity_singular_function().
Wrapped_navier_stokes_el_pt
template<class WRAPPED_NAVIER_STOKES_ELEMENT > WRAPPED_NAVIER_STOKES_ELEMENT* oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::Wrapped_navier_stokes_el_pt private
Pointer to wrapped Navier-Stokes element.
Referenced by oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::fill_in_generic_contribution_to_residuals(), oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::grad_p_bar(), oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::grad_u_bar(), oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::set_wrapped_navier_stokes_element_pt(), oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::SingularNavierStokesSolutionElement(), and oomph::SingularNavierStokesSolutionElement< WRAPPED_NAVIER_STOKES_ELEMENT >::u_bar().
The documentation for this class was generated from the following file:
navier_stokes_elements_with_singularity.h