MercuryDPM: MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > Class Template Reference
MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > Class Template Reference
#include <MPIInteraction.h>
Public Member Functions
MPIInteraction ()
void copyFromInteraction (const Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > *interaction)
void copyToInteraction (Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > *interaction, const bool resetPointers)
template<class DUMMY = FrictionForceInteraction>
std::enable_if< std::is_base_of< SlidingFrictionInteraction, DUMMY >::value, void >::type getSlidingSpring (const Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > *interaction)
template<class DUMMY = FrictionForceInteraction>
std::enable_if< std::is_base_of< SlidingFrictionInteraction, DUMMY >::value, void >::type setSlidingSpring (Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > *interaction)
template<class DUMMY = FrictionForceInteraction>
std::enable_if<!(std::is_base_of< SlidingFrictionInteraction, DUMMY >::value), void >::type getSlidingSpring (const Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > *interaction)
template<class DUMMY = FrictionForceInteraction>
std::enable_if<!(std::is_base_of< SlidingFrictionInteraction, DUMMY >::value), void >::type setSlidingSpring (Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > *interaction)
template<class DUMMY = FrictionForceInteraction>
std::enable_if< std::is_base_of< FrictionInteraction, DUMMY >::value, void >::type getFrictionSprings (const Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > *interaction)
template<class DUMMY = FrictionForceInteraction>
std::enable_if< std::is_base_of< FrictionInteraction, DUMMY >::value, void >::type setFrictionSprings (Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > *interaction)
template<class DUMMY = FrictionForceInteraction>
std::enable_if<!(std::is_base_of< FrictionInteraction, DUMMY >::value), void >::type getFrictionSprings (const Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > *interaction)
template<class DUMMY = FrictionForceInteraction>
std::enable_if<!(std::is_base_of< FrictionInteraction, DUMMY >::value), void >::type setFrictionSprings (Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > *interaction)
template<class DUMMY = AdhesiveForceInteraction>
std::enable_if<(std::is_base_of< LiquidMigrationWilletInteraction, DUMMY >::value||std::is_base_of< LiquidBridgeWilletInteraction, DUMMY >::value||std::is_base_of< IrreversibleAdhesiveInteraction, DUMMY >::value), void >::type getWasInContact (const Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > *interaction)
template<class DUMMY = AdhesiveForceInteraction>
std::enable_if<(std::is_base_of< LiquidMigrationWilletInteraction, DUMMY >::value||std::is_base_of< LiquidBridgeWilletInteraction, DUMMY >::value||std::is_base_of< IrreversibleAdhesiveInteraction, DUMMY >::value), void >::type setWasInContact (Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > *interaction)
template<class DUMMY = AdhesiveForceInteraction>
std::enable_if<!(std::is_base_of< LiquidMigrationWilletInteraction, DUMMY >::value||std::is_base_of< LiquidBridgeWilletInteraction, DUMMY >::value||std::is_base_of< IrreversibleAdhesiveInteraction, DUMMY >::value), void >::type getWasInContact (const Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > *interaction)
template<class DUMMY = AdhesiveForceInteraction>
std::enable_if<!(std::is_base_of< LiquidMigrationWilletInteraction, DUMMY >::value||std::is_base_of< LiquidBridgeWilletInteraction, DUMMY >::value||std::is_base_of< IrreversibleAdhesiveInteraction, DUMMY >::value), void >::type setWasInContact (Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > *interaction)
template<class DUMMY = AdhesiveForceInteraction>
std::enable_if<(std::is_base_of< BondedInteraction, DUMMY >::value), void >::type getBonded (const Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > *interaction)
template<class DUMMY = AdhesiveForceInteraction>
std::enable_if<(std::is_base_of< BondedInteraction, DUMMY >::value), void >::type setBonded (Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > *interaction)
template<class DUMMY = AdhesiveForceInteraction>
std::enable_if<!(std::is_base_of< BondedInteraction, DUMMY >::value), void >::type getBonded (const Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > *interaction)
template<class DUMMY = AdhesiveForceInteraction>
std::enable_if<!(std::is_base_of< BondedInteraction, DUMMY >::value), void >::type setBonded (Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > *interaction)
template<class DUMMY = AdhesiveForceInteraction>
std::enable_if<(std::is_base_of< LiquidMigrationWilletInteraction, DUMMY >::value), void >::type getLiquidBridge (const Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > *interaction)
template<class DUMMY = AdhesiveForceInteraction>
std::enable_if<(std::is_base_of< LiquidMigrationWilletInteraction, DUMMY >::value), void >::type setLiquidBridge (Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > *interaction)
template<class DUMMY = AdhesiveForceInteraction>
std::enable_if<!(std::is_base_of< LiquidMigrationWilletInteraction, DUMMY >::value), void >::type getLiquidBridge (const Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > *interaction)
template<class DUMMY = AdhesiveForceInteraction>
std::enable_if<!(std::is_base_of< LiquidMigrationWilletInteraction, DUMMY >::value), void >::type setLiquidBridge (Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > *interaction)
template<class DUMMY = NormalForceInteraction>
std::enable_if<(std::is_base_of< LinearPlasticViscoelasticInteraction, DUMMY >::value), void >::type getMaximumOverlap (const Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > *interaction)
template<class DUMMY = NormalForceInteraction>
std::enable_if<(std::is_base_of< LinearPlasticViscoelasticInteraction, DUMMY >::value), void >::type setMaximumOverlap (Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > *interaction)
template<class DUMMY = NormalForceInteraction>
std::enable_if<!(std::is_base_of< LinearPlasticViscoelasticInteraction, DUMMY >::value), void >::type getMaximumOverlap (const Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > *interaction)
template<class DUMMY = NormalForceInteraction>
std::enable_if<!(std::is_base_of< LinearPlasticViscoelasticInteraction, DUMMY >::value), void >::type setMaximumOverlap (Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > *interaction)
Public Attributes
unsigned int P
unsigned int I
unsigned int speciesId
bool isWallInteraction
unsigned timeStamp
Vec3D force
Vec3D torque
std::conditional< std::is_base_of< SlidingFrictionInteraction, FrictionForceInteraction >::value, Vec3D, Empty >::type slidingSpring
std::conditional< std::is_base_of< FrictionInteraction, FrictionForceInteraction >::value, Vec3D, Empty >::type rollingSpring
std::conditional< std::is_base_of< FrictionInteraction, FrictionForceInteraction >::value, Vec3D, Empty >::type torsionSpring
std::conditional<(std::is_base_of< LiquidMigrationWilletInteraction, AdhesiveForceInteraction >::value||std::is_base_of< LiquidBridgeWilletInteraction, AdhesiveForceInteraction >::value||std::is_base_of< IrreversibleAdhesiveInteraction, AdhesiveForceInteraction >::value), bool, Empty >::type wasInContact
std::conditional< std::is_base_of< BondedInteraction, AdhesiveForceInteraction >::value, bool, Empty >::type bonded
std::conditional< std::is_base_of< LiquidMigrationWilletInteraction, AdhesiveForceInteraction >::value, Mdouble, Empty >::type liquidbridgeVolume
std::conditional< std::is_base_of< LinearPlasticViscoelasticInteraction, NormalForceInteraction >::value, Mdouble, Empty >::type maxOverlap
Constructor & Destructor Documentation
MPIInteraction()
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::MPIInteraction
 {
 }
Member Function Documentation
copyFromInteraction()
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > void MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::copyFromInteraction (const Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > * interaction)
 {
     //logger.assert_debug(interaction->getP()->getId(),"Trying to copy an unreal interaction: P is not defined");
     //logger.assert_debug(interaction->getP()->getId(),"Trying to copy an unreal interaction: I is not defined");
     if (interaction->getP() == nullptr) logger(WARN, "P is not defined!!");
     if (interaction->getI() == nullptr) logger(WARN, "I is not defined!!");
     P = interaction->getP()->getId();
     I = interaction->getI()->getId();
     if (dynamic_cast<const BaseParticle*>(interaction->getI()) == nullptr)
     {
         isWallInteraction = true;
     }
     else
     {
         isWallInteraction = false;
     }
     timeStamp = interaction->getTimeStamp();
     force = interaction->getForce();
     torque = interaction->getTorque();
     getSlidingSpring(interaction);
     getFrictionSprings(interaction);
     getWasInContact(interaction);
     getBonded(interaction);
     getLiquidBridge(interaction);
     getMaximumOverlap(interaction);
 }
References BaseInteraction::getForce(), BaseInteraction::getI(), BaseObject::getId(), BaseInteraction::getP(), BaseInteraction::getTimeStamp(), BaseInteraction::getTorque(), I, logger, Global_Physical_Variables::P, and WARN.
Referenced by Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::getMPIInteraction().
copyToInteraction()
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > void MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::copyToInteraction (Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > * interaction, const bool resetPointers)
 {
     //Basic interaction values
     BaseInteraction* basicInteraction = static_cast<BaseInteraction*>(interaction);
     basicInteraction->setBasicMPIInteractionValues(P, I, timeStamp, force, torque, isWallInteraction, resetPointers);
     //Specific history interaction values, interaction type denpendent
     setSlidingSpring(interaction);
     setFrictionSprings(interaction);
     setWasInContact(interaction);
     setBonded(interaction);
     setLiquidBridge(interaction);
     setMaximumOverlap(interaction);
 }
References I, Global_Physical_Variables::P, and BaseInteraction::setBasicMPIInteractionValues().
Referenced by Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::setMPIInteraction().
getBonded() [1/2]
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > template<class DUMMY = AdhesiveForceInteraction> std::enable_if<(std::is_base_of<BondedInteraction, DUMMY>::value), void>::type MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::getBonded (const Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > * interaction) inline
     {
         bonded = interaction->AdhesiveForceInteraction::getBonded();
     }
References MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::bonded.
getBonded() [2/2]
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > template<class DUMMY = AdhesiveForceInteraction> std::enable_if<!(std::is_base_of<BondedInteraction, DUMMY>::value), void>::type MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::getBonded (const Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > * interaction) inline
     {
     }
getFrictionSprings() [1/2]
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > template<class DUMMY = FrictionForceInteraction> std::enable_if<std::is_base_of<FrictionInteraction, DUMMY>::value, void>::type MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::getFrictionSprings (const Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > * interaction) inline
     {
         rollingSpring = interaction->FrictionForceInteraction::getRollingSpring();
         torsionSpring = interaction->FrictionForceInteraction::getTorsionSpring();
     }
References MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::rollingSpring, and MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::torsionSpring.
getFrictionSprings() [2/2]
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > template<class DUMMY = FrictionForceInteraction> std::enable_if<!(std::is_base_of<FrictionInteraction, DUMMY>::value), void>::type MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::getFrictionSprings (const Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > * interaction) inline
     {
     }
getLiquidBridge() [1/2]
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > template<class DUMMY = AdhesiveForceInteraction> std::enable_if<(std::is_base_of<LiquidMigrationWilletInteraction, DUMMY>::value), void>::type MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::getLiquidBridge (const Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > * interaction) inline
     {
         liquidbridgeVolume = interaction->AdhesiveForceInteraction::getLiquidBridgeVolume();
     }
References MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::liquidbridgeVolume.
getLiquidBridge() [2/2]
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > template<class DUMMY = AdhesiveForceInteraction> std::enable_if<!(std::is_base_of<LiquidMigrationWilletInteraction, DUMMY>::value), void>::type MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::getLiquidBridge (const Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > * interaction) inline
     {
     }
getMaximumOverlap() [1/2]
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > template<class DUMMY = NormalForceInteraction> std::enable_if<(std::is_base_of<LinearPlasticViscoelasticInteraction, DUMMY>::value), void>::type MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::getMaximumOverlap (const Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > * interaction) inline
     {
         maxOverlap = interaction->NormalForceInteraction::getMaxOverlap();
     }
References MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::maxOverlap.
getMaximumOverlap() [2/2]
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > template<class DUMMY = NormalForceInteraction> std::enable_if<!(std::is_base_of<LinearPlasticViscoelasticInteraction, DUMMY>::value), void>::type MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::getMaximumOverlap (const Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > * interaction) inline
     {
     }
getSlidingSpring() [1/2]
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > template<class DUMMY = FrictionForceInteraction> std::enable_if<std::is_base_of<SlidingFrictionInteraction, DUMMY>::value, void>::type MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::getSlidingSpring (const Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > * interaction) inline
     {
         slidingSpring = interaction->FrictionForceInteraction::getSlidingSpring();
     }
References MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::slidingSpring.
getSlidingSpring() [2/2]
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > template<class DUMMY = FrictionForceInteraction> std::enable_if<!(std::is_base_of<SlidingFrictionInteraction, DUMMY>::value), void>::type MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::getSlidingSpring (const Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > * interaction) inline
     {
     }
getWasInContact() [1/2]
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > template<class DUMMY = AdhesiveForceInteraction> std::enable_if<(std::is_base_of<LiquidMigrationWilletInteraction, DUMMY>::value || std::is_base_of<LiquidBridgeWilletInteraction, DUMMY>::value || std::is_base_of<IrreversibleAdhesiveInteraction, DUMMY>::value), void>::type MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::getWasInContact (const Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > * interaction) inline
     {
         wasInContact = interaction->AdhesiveForceInteraction::getWasInContact();
     }
References MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::wasInContact.
getWasInContact() [2/2]
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > template<class DUMMY = AdhesiveForceInteraction> std::enable_if<!(std::is_base_of<LiquidMigrationWilletInteraction, DUMMY>::value || std::is_base_of<LiquidBridgeWilletInteraction, DUMMY>::value || std::is_base_of<IrreversibleAdhesiveInteraction, DUMMY>::value), void>::type MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::getWasInContact (const Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > * interaction) inline
     {
     }
setBonded() [1/2]
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > template<class DUMMY = AdhesiveForceInteraction> std::enable_if<(std::is_base_of<BondedInteraction, DUMMY>::value), void>::type MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::setBonded (Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > * interaction) inline
     {
         interaction->AdhesiveForceInteraction::setBonded(bonded);
     }
References MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::bonded.
setBonded() [2/2]
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > template<class DUMMY = AdhesiveForceInteraction> std::enable_if<!(std::is_base_of<BondedInteraction, DUMMY>::value), void>::type MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::setBonded (Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > * interaction) inline
     {
     }
setFrictionSprings() [1/2]
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > template<class DUMMY = FrictionForceInteraction> std::enable_if<std::is_base_of<FrictionInteraction, DUMMY>::value, void>::type MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::setFrictionSprings (Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > * interaction) inline
     {
         interaction->FrictionForceInteraction::setRollingSpring(rollingSpring);
         interaction->FrictionForceInteraction::setTorsionSpring(torsionSpring);
     }
References MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::rollingSpring, and MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::torsionSpring.
setFrictionSprings() [2/2]
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > template<class DUMMY = FrictionForceInteraction> std::enable_if<!(std::is_base_of<FrictionInteraction, DUMMY>::value), void>::type MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::setFrictionSprings (Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > * interaction) inline
     {
     }
setLiquidBridge() [1/2]
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > template<class DUMMY = AdhesiveForceInteraction> std::enable_if<(std::is_base_of<LiquidMigrationWilletInteraction, DUMMY>::value), void>::type MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::setLiquidBridge (Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > * interaction) inline
     {
         interaction->AdhesiveForceInteraction::setLiquidBridgeVolume(liquidbridgeVolume);
     }
References MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::liquidbridgeVolume.
setLiquidBridge() [2/2]
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > template<class DUMMY = AdhesiveForceInteraction> std::enable_if<!(std::is_base_of<LiquidMigrationWilletInteraction, DUMMY>::value), void>::type MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::setLiquidBridge (Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > * interaction) inline
     {
     }
setMaximumOverlap() [1/2]
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > template<class DUMMY = NormalForceInteraction> std::enable_if<(std::is_base_of<LinearPlasticViscoelasticInteraction, DUMMY>::value), void>::type MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::setMaximumOverlap (Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > * interaction) inline
     {
         interaction->NormalForceInteraction::setMaxOverlap(maxOverlap);
     }
References MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::maxOverlap.
setMaximumOverlap() [2/2]
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > template<class DUMMY = NormalForceInteraction> std::enable_if<!(std::is_base_of<LinearPlasticViscoelasticInteraction, DUMMY>::value), void>::type MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::setMaximumOverlap (Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > * interaction) inline
     {
     }
setSlidingSpring() [1/2]
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > template<class DUMMY = FrictionForceInteraction> std::enable_if<std::is_base_of<SlidingFrictionInteraction, DUMMY>::value, void>::type MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::setSlidingSpring (Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > * interaction) inline
     {
         interaction->FrictionForceInteraction::setSlidingSpring(slidingSpring);
     }
References MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::slidingSpring.
setSlidingSpring() [2/2]
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > template<class DUMMY = FrictionForceInteraction> std::enable_if<!(std::is_base_of<SlidingFrictionInteraction, DUMMY>::value), void>::type MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::setSlidingSpring (Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > * interaction) inline
     {
     }
setWasInContact() [1/2]
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > template<class DUMMY = AdhesiveForceInteraction> std::enable_if<(std::is_base_of<LiquidMigrationWilletInteraction, DUMMY>::value || std::is_base_of<LiquidBridgeWilletInteraction, DUMMY>::value || std::is_base_of<IrreversibleAdhesiveInteraction, DUMMY>::value), void>::type MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::setWasInContact (Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > * interaction) inline
     {
         interaction->AdhesiveForceInteraction::setWasInContact(wasInContact);
     }
References MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::wasInContact.
setWasInContact() [2/2]
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > template<class DUMMY = AdhesiveForceInteraction> std::enable_if<!(std::is_base_of<LiquidMigrationWilletInteraction, DUMMY>::value || std::is_base_of<LiquidBridgeWilletInteraction, DUMMY>::value || std::is_base_of<IrreversibleAdhesiveInteraction, DUMMY>::value), void>::type MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::setWasInContact (Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction > * interaction) inline
     {
     }
Member Data Documentation
bonded
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > std::conditional< std::is_base_of<BondedInteraction, AdhesiveForceInteraction>::value, bool, Empty>::type MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::bonded
Referenced by MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::getBonded(), and MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::setBonded().
force
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > Vec3D MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::force
I
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > unsigned int MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::I
Referenced by Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::getInteractionDetails().
isWallInteraction
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > bool MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::isWallInteraction
Referenced by Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::getInteractionDetails().
liquidbridgeVolume
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > std::conditional< std::is_base_of<LiquidMigrationWilletInteraction, AdhesiveForceInteraction>::value, Mdouble, Empty>::type MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::liquidbridgeVolume
Referenced by MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::getLiquidBridge(), and MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::setLiquidBridge().
maxOverlap
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > std::conditional< std::is_base_of<LinearPlasticViscoelasticInteraction, NormalForceInteraction>::value, Mdouble, Empty>::type MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::maxOverlap
Referenced by MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::getMaximumOverlap(), and MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::setMaximumOverlap().
P
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > unsigned int MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::P
Referenced by Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::getInteractionDetails().
rollingSpring
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > std::conditional< std::is_base_of<FrictionInteraction, FrictionForceInteraction>::value, Vec3D, Empty>::type MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::rollingSpring
Referenced by MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::getFrictionSprings(), and MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::setFrictionSprings().
slidingSpring
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > std::conditional< std::is_base_of<SlidingFrictionInteraction, FrictionForceInteraction>::value, Vec3D, Empty>::type MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::slidingSpring
Referenced by MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::getSlidingSpring(), and MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::setSlidingSpring().
speciesId
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > unsigned int MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::speciesId
timeStamp
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > unsigned MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::timeStamp
Referenced by Interaction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::getInteractionDetails().
torque
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > Vec3D MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::torque
torsionSpring
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > std::conditional< std::is_base_of<FrictionInteraction, FrictionForceInteraction>::value, Vec3D, Empty>::type MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::torsionSpring
Referenced by MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::getFrictionSprings(), and MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::setFrictionSprings().
wasInContact
template<class NormalForceInteraction , class FrictionForceInteraction , class AdhesiveForceInteraction > std::conditional< (std::is_base_of<LiquidMigrationWilletInteraction, AdhesiveForceInteraction>::value || std::is_base_of<LiquidBridgeWilletInteraction, AdhesiveForceInteraction>::value || std::is_base_of<IrreversibleAdhesiveInteraction, AdhesiveForceInteraction>::value), bool, Empty>::type MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::wasInContact
Referenced by MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::getWasInContact(), and MPIInteraction< NormalForceInteraction, FrictionForceInteraction, AdhesiveForceInteraction >::setWasInContact().
The documentation for this class was generated from the following file:
MPIInteraction.h