MercuryDPM: Tutorial_ReshapeMat2Mat.cpp File Reference
Tutorial_ReshapeMat2Mat.cpp File Reference
Functions
MatrixXf M1 (2, 6)
M1<< 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12;Map< MatrixXf > M2 (M1.data(), 6, 2)
Function Documentation
M1()
MatrixXf M1 (2 , 6)
M2()
M1<< 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12;Map<MatrixXf> M2 (M1. data(), 6 , 2)
Referenced by oomph::ConstitutiveLaw::are_matrices_of_equal_dimensions(), CFile::copy(), and test_blocks().