MercuryDPM: oomph::PRefineableQElement< 1, INITIAL_NNODE_1D > Class Template Reference
oomph::PRefineableQElement< 1, INITIAL_NNODE_1D > Class Template Reference
#include <hp_refineable_elements.h>
Public Member Functions
PRefineableQElement ()
Constructor.
virtual ~PRefineableQElement ()
Destructor.
void initial_setup (Tree *const &adopted_father_pt=0, const unsigned &initial_p_order=0)
void pre_build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt)
void p_refine (const int &inc, Mesh *const &mesh_pt, GeneralisedElement *const &clone_pt)
p-refine the element (refine if inc>0, unrefine if inc<0).
void shape (const Vector< double > &s, Shape &psi) const
Overload the shape functions.
void dshape_local (const Vector< double > &s, Shape &psi, DShape &dpsi) const
Derivatives of shape functions for PRefineableQElement<DIM>
void d2shape_local (const Vector< double > &s, Shape &psi, DShape &dpsids, DShape &d2psids) const
void further_setup_hanging_nodes ()
unsigned nnode_1d () const
unsigned initial_p_order () const
Get the initial P_order.
Node * get_node_at_local_coordinate (const Vector< double > &s) const
Return the node at the specified local coordinate.
Node * node_created_by_son_of_neighbour (const Vector< double > &s_fraction, bool &is_periodic)
void local_coordinate_of_node (const unsigned &n, Vector< double > &s) const
Get local coordinates of node j in the element; vector sets its own size.
void local_fraction_of_node (const unsigned &n, Vector< double > &s_fraction)
Get the local fractino of node j in the element.
double local_one_d_fraction_of_node (const unsigned &n1d, const unsigned &i)
The local one-d fraction is the same.
void rebuild_from_sons (Mesh *&mesh_pt)
void check_integrity (double &max_error)
Public Member Functions inherited from oomph::RefineableQElement< 1 >
RefineableQElement ()
Constructor: Pass refinement level (default 0 = root)
RefineableQElement (const RefineableQElement< 1 > &dummy)=delete
Broken copy constructor.
virtual ~RefineableQElement ()
Broken assignment operator.
unsigned required_nsons () const
A refineable line element has two sons.
Node * node_created_by_neighbour (const Vector< double > &s_fraction, bool &is_periodic)
Node * node_created_by_son_of_neighbour (const Vector< double > &s_fraction, bool &is_periodic)
virtual void build (Mesh *&mesh_pt, Vector< Node * > &new_node_pt, bool &was_already_built, std::ofstream &new_nodes_file)
void check_integrity (double &max_error)
void output_corners (std::ostream &outfile, const std::string &colour) const
Print corner nodes, using colour.
BinaryTree * binary_tree_pt ()
Pointer to binary tree representation of this element.
BinaryTree * binary_tree_pt () const
Pointer to binary tree representation of this element (const version)
void setup_hanging_nodes (Vector< std::ofstream * > &output_stream)
Line elements have no hanging nodes so this is deliberately left empty.
Public Member Functions inherited from oomph::RefineableElement
RefineableElement ()
virtual ~RefineableElement ()
Destructor, delete the allocated storage for the hanging equations.
RefineableElement (const RefineableElement &)=delete
Broken copy constructor.
void operator= (const RefineableElement &)=delete
Broken assignment operator.
Tree * tree_pt ()
Access function: Pointer to quadtree representation of this element.
void set_tree_pt (Tree *my_tree_pt)
Set pointer to quadtree representation of this element.
bool refinement_is_enabled ()
Flag to indicate suppression of any refinement.
void disable_refinement ()
Suppress of any refinement for this element.
void enable_refinement ()
Emnable refinement for this element.
template<class ELEMENT >
void split (Vector< ELEMENT * > &son_pt) const
int local_hang_eqn (Node *const &node_pt, const unsigned &i)
void set_refinement_level (const int &refine_level)
Set the refinement level.
unsigned refinement_level () const
Return the Refinement level.
void select_for_refinement ()
Select the element for refinement.
void deselect_for_refinement ()
Deselect the element for refinement.
void select_sons_for_unrefinement ()
Unrefinement will be performed by merging the four sons of this element.
void deselect_sons_for_unrefinement ()
bool to_be_refined ()
Has the element been selected for refinement?
bool sons_to_be_unrefined ()
Has the element been selected for unrefinement?
virtual void unbuild ()
virtual void deactivate_element ()
long number () const
Element number (for debugging/plotting)
void set_number (const long &mynumber)
Set element number (for debugging/plotting)
virtual unsigned ncont_interpolated_values () const =0
virtual void get_interpolated_values (const Vector< double > &s, Vector< double > &values)
virtual void get_interpolated_values (const unsigned &t, const Vector< double > &s, Vector< double > &values)=0
virtual Node * interpolating_node_pt (const unsigned &n, const int &value_id)
virtual double local_one_d_fraction_of_interpolating_node (const unsigned &n1d, const unsigned &i, const int &value_id)
virtual Node * get_interpolating_node_at_local_coordinate (const Vector< double > &s, const int &value_id)
virtual unsigned ninterpolating_node (const int &value_id)
virtual unsigned ninterpolating_node_1d (const int &value_id)
virtual void interpolating_basis (const Vector< double > &s, Shape &psi, const int &value_id) const
void identify_field_data_for_interactions (std::set< std::pair< Data *, unsigned >> &paired_field_data)
void assign_nodal_local_eqn_numbers (const bool &store_local_dof_pt)
virtual RefineableElement * root_element_pt ()
virtual RefineableElement * father_element_pt () const
Return a pointer to the father element.
void get_father_at_refinement_level (unsigned &refinement_level, RefineableElement *&father_at_reflevel_pt)
virtual void further_build ()
Further build: e.g. deal with interpolation of internal values.
void get_dresidual_dnodal_coordinates (RankThreeTensor< double > &dresidual_dnodal_coordinates)
unsigned nshape_controlling_nodes ()
std::map< Node *, unsigned > shape_controlling_node_lookup ()
Public Member Functions inherited from oomph::FiniteElement
void set_dimension (const unsigned &dim)
void set_nodal_dimension (const unsigned &nodal_dim)
void set_nnodal_position_type (const unsigned &nposition_type)
Set the number of types required to interpolate the coordinate.
void set_n_node (const unsigned &n)
int nodal_local_eqn (const unsigned &n, const unsigned &i) const
double dJ_eulerian_at_knot (const unsigned &ipt, Shape &psi, DenseMatrix< double > &djacobian_dX) const
FiniteElement ()
Constructor.
virtual ~FiniteElement ()
FiniteElement (const FiniteElement &)=delete
Broken copy constructor.
void get_centre_of_gravity_and_max_radius_in_terms_of_zeta (Vector< double > &cog, double &max_radius) const
MacroElement * macro_elem_pt ()
Access function to pointer to macro element.
void get_x (const Vector< double > &s, Vector< double > &x) const
void get_x (const unsigned &t, const Vector< double > &s, Vector< double > &x)
virtual void set_integration_scheme (Integral *const &integral_pt)
Set the spatial integration scheme.
Integral *const & integral_pt () const
Return the pointer to the integration scheme (const version)
virtual void shape_at_knot (const unsigned &ipt, Shape &psi) const
virtual void dshape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids) const
virtual void d2shape_local_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsids, DShape &d2psids) const
virtual double J_eulerian (const Vector< double > &s) const
virtual double J_eulerian_at_knot (const unsigned &ipt) const
void check_J_eulerian_at_knots (bool &passed) const
void check_jacobian (const double &jacobian) const
double dshape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx) const
virtual double dshape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsi, DenseMatrix< double > &djacobian_dX, RankFourTensor< double > &d_dpsidx_dX) const
double d2shape_eulerian (const Vector< double > &s, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual double d2shape_eulerian_at_knot (const unsigned &ipt, Shape &psi, DShape &dpsidx, DShape &d2psidx) const
virtual void describe_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void describe_nodal_local_dofs (std::ostream &out, const std::string &current_string) const
virtual void assign_all_generic_local_eqn_numbers (const bool &store_local_dof_pt)
Node *& node_pt (const unsigned &n)
Return a pointer to the local node n.
Node *const & node_pt (const unsigned &n) const
Return a pointer to the local node n (const version)
unsigned nnode () const
Return the number of nodes.
double raw_nodal_position (const unsigned &n, const unsigned &i) const
double raw_nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &i) const
double raw_dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double raw_dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position (const unsigned &n, const unsigned &i) const
double nodal_position (const unsigned &t, const unsigned &n, const unsigned &i) const
double dnodal_position_dt (const unsigned &n, const unsigned &i) const
Return the i-th component of nodal velocity: dx/dt at local node n.
double dnodal_position_dt (const unsigned &n, const unsigned &j, const unsigned &i) const
double nodal_position_gen (const unsigned &n, const unsigned &k, const unsigned &i) const
double nodal_position_gen (const unsigned &t, const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &n, const unsigned &k, const unsigned &i) const
double dnodal_position_gen_dt (const unsigned &j, const unsigned &n, const unsigned &k, const unsigned &i) const
virtual void disable_ALE ()
virtual void enable_ALE ()
virtual unsigned required_nvalue (const unsigned &n) const
unsigned nnodal_position_type () const
bool has_hanging_nodes () const
unsigned nodal_dimension () const
Return the required Eulerian dimension of the nodes in this element.
virtual Node * construct_node (const unsigned &n)
virtual Node * construct_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
virtual Node * construct_boundary_node (const unsigned &n)
virtual Node * construct_boundary_node (const unsigned &n, TimeStepper *const &time_stepper_pt)
int get_node_number (Node *const &node_pt) const
double raw_nodal_value (const unsigned &n, const unsigned &i) const
double raw_nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &n, const unsigned &i) const
double nodal_value (const unsigned &t, const unsigned &n, const unsigned &i) const
unsigned dim () const
virtual double interpolated_x (const Vector< double > &s, const unsigned &i) const
Return FE interpolated coordinate x[i] at local coordinate s.
virtual double interpolated_x (const unsigned &t, const Vector< double > &s, const unsigned &i) const
virtual void interpolated_x (const Vector< double > &s, Vector< double > &x) const
Return FE interpolated position x[] at local coordinate s as Vector.
virtual void interpolated_x (const unsigned &t, const Vector< double > &s, Vector< double > &x) const
virtual double interpolated_dxdt (const Vector< double > &s, const unsigned &i, const unsigned &t)
virtual void interpolated_dxdt (const Vector< double > &s, const unsigned &t, Vector< double > &dxdt)
unsigned ngeom_data () const
Data * geom_data_pt (const unsigned &j)
void position (const Vector< double > &zeta, Vector< double > &r) const
void position (const unsigned &t, const Vector< double > &zeta, Vector< double > &r) const
void dposition_dt (const Vector< double > &zeta, const unsigned &t, Vector< double > &drdt)
virtual double zeta_nodal (const unsigned &n, const unsigned &k, const unsigned &i) const
void interpolated_zeta (const Vector< double > &s, Vector< double > &zeta) const
void locate_zeta (const Vector< double > &zeta, GeomObject *&geom_object_pt, Vector< double > &s, const bool &use_coordinate_as_initial_guess=false)
virtual void node_update ()
virtual void identify_geometric_data (std::set< Data * > &geometric_data_pt)
virtual double s_min () const
Min value of local coordinate.
virtual double s_max () const
Max. value of local coordinate.
double size () const
virtual double compute_physical_size () const
virtual void point_output_data (const Vector< double > &s, Vector< double > &data)
void point_output (std::ostream &outfile, const Vector< double > &s)
virtual unsigned nplot_points_paraview (const unsigned &nplot) const
virtual unsigned nsub_elements_paraview (const unsigned &nplot) const
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_output_offset_information (std::ofstream &file_out, const unsigned &nplot, unsigned &counter) const
virtual void write_paraview_type (std::ofstream &file_out, const unsigned &nplot) const
virtual void write_paraview_offsets (std::ofstream &file_out, const unsigned &nplot, unsigned &offset_sum) const
virtual unsigned nscalar_paraview () const
virtual void scalar_value_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
virtual void scalar_value_fct_paraview (std::ofstream &file_out, const unsigned &i, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
virtual std::string scalar_name_paraview (const unsigned &i) const
virtual void output (std::ostream &outfile)
virtual void output (std::ostream &outfile, const unsigned &n_plot)
virtual void output (const unsigned &t, std::ostream &outfile, const unsigned &n_plot) const
virtual void output (FILE *file_pt)
virtual void output (FILE *file_pt, const unsigned &n_plot)
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt)
Output an exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt)
Output a time-dependent exact solution over the element.
virtual void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, const SolutionFunctorBase &exact_soln) const
Output a time-dependent exact solution over the element.
virtual void get_s_plot (const unsigned &i, const unsigned &nplot, Vector< double > &s, const bool &shifted_to_interior=false) const
virtual std::string tecplot_zone_string (const unsigned &nplot) const
virtual void write_tecplot_zone_footer (std::ostream &outfile, const unsigned &nplot) const
virtual void write_tecplot_zone_footer (FILE *file_pt, const unsigned &nplot) const
virtual unsigned nplot_points (const unsigned &nplot) const
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Calculate the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_abs_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error)
void integrate_fct (FiniteElement::SteadyExactSolutionFctPt integrand_fct_pt, Vector< double > &integral)
Integrate Vector-valued function over element.
void integrate_fct (FiniteElement::UnsteadyExactSolutionFctPt integrand_fct_pt, const double &time, Vector< double > &integral)
Integrate Vector-valued time-dep function over element.
virtual void build_face_element (const int &face_index, FaceElement *face_element_pt)
virtual unsigned self_test ()
virtual unsigned get_bulk_node_number (const int &face_index, const unsigned &i) const
virtual int face_outer_unit_normal_sign (const int &face_index) const
Get the sign of the outer unit normal on the face given by face_index.
void face_node_number_error_check (const unsigned &i) const
Range check for face node numbers.
virtual CoordinateMappingFctPt face_to_bulk_coordinate_fct_pt (const int &face_index) const
virtual BulkCoordinateDerivativesFctPt bulk_coordinate_derivatives_fct_pt (const int &face_index) const
Public Member Functions inherited from oomph::GeneralisedElement
GeneralisedElement ()
Constructor: Initialise all pointers and all values to zero.
virtual ~GeneralisedElement ()
Virtual destructor to clean up any memory allocated by the object.
GeneralisedElement (const GeneralisedElement &)=delete
Broken copy constructor.
void operator= (const GeneralisedElement &)=delete
Broken assignment operator.
Data *& internal_data_pt (const unsigned &i)
Return a pointer to i-th internal data object.
Data *const & internal_data_pt (const unsigned &i) const
Return a pointer to i-th internal data object (const version)
Data *& external_data_pt (const unsigned &i)
Return a pointer to i-th external data object.
Data *const & external_data_pt (const unsigned &i) const
Return a pointer to i-th external data object (const version)
unsigned long eqn_number (const unsigned &ieqn_local) const
int local_eqn_number (const unsigned long &ieqn_global) const
unsigned add_external_data (Data *const &data_pt, const bool &fd=true)
bool external_data_fd (const unsigned &i) const
void exclude_external_data_fd (const unsigned &i)
void include_external_data_fd (const unsigned &i)
void flush_external_data ()
Flush all external data.
void flush_external_data (Data *const &data_pt)
Flush the object addressed by data_pt from the external data array.
unsigned ninternal_data () const
Return the number of internal data objects.
unsigned nexternal_data () const
Return the number of external data objects.
unsigned ndof () const
Return the number of equations/dofs in the element.
void dof_vector (const unsigned &t, Vector< double > &dof)
Return the vector of dof values at time level t.
void dof_pt_vector (Vector< double * > &dof_pt)
Return the vector of pointers to dof values.
void set_internal_data_time_stepper (const unsigned &i, TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void assign_internal_eqn_numbers (unsigned long &global_number, Vector< double * > &Dof_pt)
void describe_dofs (std::ostream &out, const std::string &current_string) const
void add_internal_value_pt_to_map (std::map< unsigned, double * > &map_of_value_pt)
virtual void assign_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void complete_setup_of_dependencies ()
virtual void get_residuals (Vector< double > &residuals)
virtual void get_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
virtual void get_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void get_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void get_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void get_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void get_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void get_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void get_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void get_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_norm (double &norm)
virtual unsigned ndof_types () const
virtual void get_dof_numbers_for_unknowns (std::list< std::pair< unsigned long, unsigned >> &dof_lookup_list) const
Public Member Functions inherited from oomph::GeomObject
GeomObject ()
Default constructor.
GeomObject (const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim)
GeomObject (const unsigned &nlagrangian, const unsigned &ndim, TimeStepper *time_stepper_pt)
GeomObject (const GeomObject &dummy)=delete
Broken copy constructor.
void operator= (const GeomObject &)=delete
Broken assignment operator.
virtual ~GeomObject ()
(Empty) destructor
unsigned nlagrangian () const
Access function to # of Lagrangian coordinates.
unsigned ndim () const
Access function to # of Eulerian coordinates.
void set_nlagrangian_and_ndim (const unsigned &n_lagrangian, const unsigned &n_dim)
Set # of Lagrangian and Eulerian coordinates.
TimeStepper *& time_stepper_pt ()
TimeStepper * time_stepper_pt () const
virtual void position (const double &t, const Vector< double > &zeta, Vector< double > &r) const
virtual void dposition (const Vector< double > &zeta, DenseMatrix< double > &drdzeta) const
virtual void d2position (const Vector< double > &zeta, RankThreeTensor< double > &ddrdzeta) const
virtual void d2position (const Vector< double > &zeta, Vector< double > &r, DenseMatrix< double > &drdzeta, RankThreeTensor< double > &ddrdzeta) const
Public Member Functions inherited from oomph::LineElementBase
LineElementBase ()
Constructor. Empty.
virtual unsigned nvertex_node () const =0
Number of vertex nodes in the element.
virtual Node * vertex_node_pt (const unsigned &j) const =0
Pointer to the j-th vertex node in the element.
Public Member Functions inherited from oomph::QElementBase
QElementBase ()
Constructor: Initialise pointers to macro element reference coords.
QElementBase (const QElementBase &)=delete
Broken copy constructor.
virtual ~QElementBase ()
Broken assignment operator.
bool local_coord_is_valid (const Vector< double > &s)
Check whether the local coordinate are valid or not.
void move_local_coord_back_into_element (Vector< double > &s) const
virtual void set_macro_elem_pt (MacroElement *macro_elem_pt)
double & s_macro_ll (const unsigned &i)
double & s_macro_ur (const unsigned &i)
double s_macro_ll (const unsigned &i) const
double s_macro_ur (const unsigned &i) const
void get_x_from_macro_element (const Vector< double > &s, Vector< double > &x) const
void get_x_from_macro_element (const unsigned &t, const Vector< double > &s, Vector< double > &x)
unsigned nnode_on_face () const
ElementGeometry::ElementGeometry element_geometry () const
It's a Q element!
Public Member Functions inherited from oomph::QElementGeometricBase
QElementGeometricBase ()
Empty default constructor.
QElementGeometricBase (const QElementGeometricBase &)=delete
Broken copy constructor.
Public Member Functions inherited from oomph::PRefineableElement
PRefineableElement ()
Constructor, calls the RefineableElement constructor.
virtual ~PRefineableElement ()
Destructor, empty.
PRefineableElement (const PRefineableElement &)=delete
Broken copy constructor.
void operator= (const PRefineableElement &)=delete
Broken assignment operator.
bool p_refinement_is_enabled ()
Flag to indicate suppression of any refinement.
void disable_p_refinement ()
Suppress of any refinement for this element.
void enable_p_refinement ()
Emnable refinement for this element.
unsigned & p_order ()
Access function to P_order.
unsigned p_order () const
Access function to P_order (const version)
void select_for_p_refinement ()
Select the element for p-refinement.
void deselect_for_p_refinement ()
Deselect the element for p-refinement.
void select_for_p_unrefinement ()
Select the element for p-unrefinement.
void deselect_for_p_unrefinement ()
Deselect the element for p-unrefinement.
bool to_be_p_refined ()
Has the element been selected for refinement?
bool to_be_p_unrefined ()
Has the element been selected for p-unrefinement?
bool nodes_built ()
Return true if all the nodes have been built, false if not.
Protected Member Functions
void binary_hang_helper (const int &value_id, const int &my_edge, std::ofstream &output_hangfile)
Set up hanging node information. Empty for 1D elements.
Protected Member Functions inherited from oomph::RefineableQElement< 1 >
void setup_father_bounds ()
void setup_hang_for_value (const int &value_id)
Line elements have no hanging nodes so this is deliberately left empty.
void binary_hang_helper (const int &value_id, const int &my_edge, std::ofstream &output_hangfile)
Line elements have no hanging nodes so this is deliberately left empty.
Protected Member Functions inherited from oomph::RefineableElement
void assemble_local_to_eulerian_jacobian (const DShape &dpsids, DenseMatrix< double > &jacobian) const
void assemble_local_to_eulerian_jacobian2 (const DShape &d2psids, DenseMatrix< double > &jacobian2) const
void assemble_eulerian_base_vectors (const DShape &dpsids, DenseMatrix< double > &interpolated_G) const
double local_to_eulerian_mapping_diagonal (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
void assign_hanging_local_eqn_numbers (const bool &store_local_dof_pt)
Assign the local equation numbers for hanging node variables.
virtual void fill_in_jacobian_from_nodal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian)
Protected Member Functions inherited from oomph::FiniteElement
template<unsigned DIM>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double invert_jacobian_mapping (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
virtual double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
double local_to_eulerian_mapping (const DShape &dpsids, DenseMatrix< double > &inverse_jacobian) const
virtual void dJ_eulerian_dnodal_coordinates (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<unsigned DIM>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
virtual void d_dshape_eulerian_dnodal_coordinates (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<unsigned DIM>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
virtual void transform_derivatives (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
void transform_derivatives_diagonal (const DenseMatrix< double > &inverse_jacobian, DShape &dbasis) const
virtual void transform_second_derivatives (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<unsigned DIM>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
void fill_in_jacobian_from_nodal_by_fd (DenseMatrix< double > &jacobian)
virtual void update_before_nodal_fd ()
virtual void reset_after_nodal_fd ()
virtual void update_in_nodal_fd (const unsigned &i)
virtual void reset_in_nodal_fd (const unsigned &i)
void fill_in_contribution_to_jacobian (Vector< double > &residuals, DenseMatrix< double > &jacobian)
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Zero-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
One-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
Two-d specialisation of function to calculate inverse of jacobian mapping.
template<>
double invert_jacobian (const DenseMatrix< double > &jacobian, DenseMatrix< double > &inverse_jacobian) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void dJ_eulerian_dnodal_coordinates_templated_helper (const DenseMatrix< double > &jacobian, const DShape &dpsids, DenseMatrix< double > &djacobian_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void d_dshape_eulerian_dnodal_coordinates_templated_helper (const double &det_jacobian, const DenseMatrix< double > &jacobian, const DenseMatrix< double > &djacobian_dX, const DenseMatrix< double > &inverse_jacobian, const DShape &dpsids, RankFourTensor< double > &d_dpsidx_dX) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_template (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
template<>
void transform_second_derivatives_diagonal (const DenseMatrix< double > &jacobian, const DenseMatrix< double > &inverse_jacobian, const DenseMatrix< double > &jacobian2, DShape &dbasis, DShape &d2basis) const
Protected Member Functions inherited from oomph::GeneralisedElement
unsigned add_internal_data (Data *const &data_pt, const bool &fd=true)
bool internal_data_fd (const unsigned &i) const
void exclude_internal_data_fd (const unsigned &i)
void include_internal_data_fd (const unsigned &i)
void clear_global_eqn_numbers ()
void add_global_eqn_numbers (std::deque< unsigned long > const &global_eqn_numbers, std::deque< double * > const &global_dof_pt)
virtual void assign_internal_and_external_local_eqn_numbers (const bool &store_local_dof_pt)
virtual void assign_additional_local_eqn_numbers ()
int internal_local_eqn (const unsigned &i, const unsigned &j) const
int external_local_eqn (const unsigned &i, const unsigned &j)
virtual void fill_in_contribution_to_residuals (Vector< double > &residuals)
void fill_in_jacobian_from_internal_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_internal_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (Vector< double > &residuals, DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
void fill_in_jacobian_from_external_by_fd (DenseMatrix< double > &jacobian, const bool &fd_all_data=false)
virtual void update_before_internal_fd ()
virtual void reset_after_internal_fd ()
virtual void update_in_internal_fd (const unsigned &i)
virtual void reset_in_internal_fd (const unsigned &i)
virtual void update_before_external_fd ()
virtual void reset_after_external_fd ()
virtual void update_in_external_fd (const unsigned &i)
virtual void reset_in_external_fd (const unsigned &i)
virtual void fill_in_contribution_to_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_jacobian_and_mass_matrix (Vector< double > &residuals, DenseMatrix< double > &jacobian, DenseMatrix< double > &mass_matrix)
virtual void fill_in_contribution_to_dresiduals_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam)
virtual void fill_in_contribution_to_djacobian_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam)
virtual void fill_in_contribution_to_djacobian_and_dmass_matrix_dparameter (double *const &parameter_pt, Vector< double > &dres_dparam, DenseMatrix< double > &djac_dparam, DenseMatrix< double > &dmass_matrix_dparam)
virtual void fill_in_contribution_to_hessian_vector_products (Vector< double > const &Y, DenseMatrix< double > const &C, DenseMatrix< double > &product)
virtual void fill_in_contribution_to_inner_products (Vector< std::pair< unsigned, unsigned >> const &history_index, Vector< double > &inner_product)
virtual void fill_in_contribution_to_inner_product_vectors (Vector< unsigned > const &history_index, Vector< Vector< double >> &inner_product_vector)
Additional Inherited Members
Public Types inherited from oomph::RefineableQElement< 1 >
typedef void(RefineableQElement< 1 >::* VoidMemberFctPt) ()
Public Types inherited from oomph::FiniteElement
typedef void(* SteadyExactSolutionFctPt) (const Vector< double > &, Vector< double > &)
typedef void(* UnsteadyExactSolutionFctPt) (const double &, const Vector< double > &, Vector< double > &)
Static Public Member Functions inherited from oomph::RefineableElement
static double & max_integrity_tolerance ()
Max. allowed discrepancy in element integrity check.
Static Public Attributes inherited from oomph::FiniteElement
static double Tolerance_for_singular_jacobian = 1.0e-16
Tolerance below which the jacobian is considered singular.
static bool Accept_negative_jacobian = false
static bool Suppress_output_while_checking_for_inverted_elements
Static Public Attributes inherited from oomph::GeneralisedElement
static bool Suppress_warning_about_repeated_internal_data
static bool Suppress_warning_about_repeated_external_data = true
static double Default_fd_jacobian_step = 1.0e-8
Static Protected Member Functions inherited from oomph::RefineableElement
static void check_value_id (const int &n_continuously_interpolated_values, const int &value_id)
Protected Attributes inherited from oomph::RefineableElement
Tree * Tree_pt
A pointer to a general tree object.
unsigned Refine_level
Refinement level.
bool To_be_refined
Flag for refinement.
bool Refinement_is_enabled
Flag to indicate suppression of any refinement.
bool Sons_to_be_unrefined
Flag for unrefinement.
long Number
Global element number – for plotting/validation purposes.
Protected Attributes inherited from oomph::FiniteElement
MacroElement * Macro_elem_pt
Pointer to the element's macro element (NULL by default)
Protected Attributes inherited from oomph::GeomObject
unsigned NLagrangian
Number of Lagrangian (intrinsic) coordinates.
unsigned Ndim
Number of Eulerian coordinates.
TimeStepper * Geom_object_time_stepper_pt
Protected Attributes inherited from oomph::PRefineableElement
unsigned P_order
The polynomial expansion order of the elemental basis functions.
bool To_be_p_refined
Flag for p-refinement.
bool P_refinement_is_enabled
Flag to indicate suppression of any refinement.
bool To_be_p_unrefined
Flag for unrefinement.
Static Protected Attributes inherited from oomph::RefineableQElement< 1 >
static std::map< unsigned, DenseMatrix< int > > Father_bound
Static Protected Attributes inherited from oomph::RefineableElement
static double Max_integrity_tolerance = 1.0e-8
Max. allowed discrepancy in element integrity check.
Static Protected Attributes inherited from oomph::FiniteElement
static const unsigned Default_Initial_Nvalue = 0
Default value for the number of values at a node.
static const double Node_location_tolerance = 1.0e-14
static const unsigned N2deriv [] = {0, 1, 3, 6}
Static Protected Attributes inherited from oomph::GeneralisedElement
static DenseMatrix< double > Dummy_matrix
static std::deque< double * > Dof_pt_deque
Detailed Description
template<unsigned INITIAL_NNODE_1D>
class oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >
p-refineable version of RefineableQElement<1,INITIAL_NNODE_1D>. Generic class definitions
Constructor & Destructor Documentation
PRefineableQElement()
template<unsigned INITIAL_NNODE_1D> oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::PRefineableQElement () inline
Constructor.
 : PRefineableElement(), RefineableQElement<1>() {}
~PRefineableQElement()
template<unsigned INITIAL_NNODE_1D> virtual oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::~PRefineableQElement () inline virtual
Destructor.
 {}
Member Function Documentation
binary_hang_helper()
template<unsigned INITIAL_NNODE_1D> void oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::binary_hang_helper (const int & value_id, const int & my_edge, std::ofstream & output_hangfile) protected
Set up hanging node information. Empty for 1D elements.
Internal function to set up the hanging nodes on a particular edge of the element. (Not required in 1D.)
   {
   }
check_integrity()
template<unsigned INITIAL_NNODE_1D> void oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::check_integrity (double & max_error) virtual
Check the integrity of interpolated values across element boundaries.
Check inter-element continuity of
nodal positions
(nodally) interpolated function values
Implements oomph::RefineableElement.
   {
     RefineableQElement<1>::check_integrity(max_error);
   }
References MeshRefinement::max_error.
d2shape_local()
template<unsigned INITIAL_NNODE_1D> void oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::d2shape_local (const Vector< double > & s, Shape & psi, DShape & dpsids, DShape & d2psids) const virtual
Second derivatives of shape functions for PRefineableQElement<DIM> d2psids(i,0) = \(d^2 \psi_j / d s^2 \)
Reimplemented from oomph::FiniteElement.
   {
     std::ostringstream error_message;
     error_message
       << "\nd2shape_local currently not implemented for this element\n";
     throw OomphLibError(
       error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
   }
References OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
dshape_local()
template<unsigned INITIAL_NNODE_1D> void oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::dshape_local (const Vector< double > & s, Shape & psi, DShape & dpsi) const virtual
Derivatives of shape functions for PRefineableQElement<DIM>
Reimplemented from oomph::FiniteElement.
   {
     switch (p_order())
     {
       case 2:
       {
         // Calculate nodal positions
         OneDimensionalLegendreShape<2>::calculate_nodal_positions();
         // Call the shape functions and derivatives
         OneDimensionalLegendreShape<2> psi1(s[0]);
         OneDimensionalLegendreDShape<2> dpsi1ds(s[0]);
         // Loop over shapes and copy across
         for (unsigned i = 0; i < p_order(); i++)
         {
           psi(i) = psi1[i];
           dpsi(i, 0) = dpsi1ds[i];
         }
         break;
       }
       case 3:
       {
         // Calculate nodal positions
         OneDimensionalLegendreShape<3>::calculate_nodal_positions();
         // Call the shape functions and derivatives
         OneDimensionalLegendreShape<3> psi1(s[0]);
         OneDimensionalLegendreDShape<3> dpsi1ds(s[0]);
         // Loop over shapes and copy across
         for (unsigned i = 0; i < p_order(); i++)
         {
           psi(i) = psi1[i];
           dpsi(i, 0) = dpsi1ds[i];
         }
         break;
       }
       case 4:
       {
         // Calculate nodal positions
         OneDimensionalLegendreShape<4>::calculate_nodal_positions();
         // Call the shape functions and derivatives
         OneDimensionalLegendreShape<4> psi1(s[0]);
         OneDimensionalLegendreDShape<4> dpsi1ds(s[0]);
         // Loop over shapes and copy across
         for (unsigned i = 0; i < p_order(); i++)
         {
           psi(i) = psi1[i];
           dpsi(i, 0) = dpsi1ds[i];
         }
         break;
       }
       case 5:
       {
         // Calculate nodal positions
         OneDimensionalLegendreShape<5>::calculate_nodal_positions();
         // Call the shape functions and derivatives
         OneDimensionalLegendreShape<5> psi1(s[0]);
         OneDimensionalLegendreDShape<5> dpsi1ds(s[0]);
         // Loop over shapes and copy across
         for (unsigned i = 0; i < p_order(); i++)
         {
           psi(i) = psi1[i];
           dpsi(i, 0) = dpsi1ds[i];
         }
         break;
       }
       case 6:
       {
         // Calculate nodal positions
         OneDimensionalLegendreShape<6>::calculate_nodal_positions();
         // Call the shape functions and derivatives
         OneDimensionalLegendreShape<6> psi1(s[0]);
         OneDimensionalLegendreDShape<6> dpsi1ds(s[0]);
         // Loop over shapes and copy across
         for (unsigned i = 0; i < p_order(); i++)
         {
           psi(i) = psi1[i];
           dpsi(i, 0) = dpsi1ds[i];
         }
         break;
       }
       case 7:
       {
         // Calculate nodal positions
         OneDimensionalLegendreShape<7>::calculate_nodal_positions();
         // Call the shape functions and derivatives
         OneDimensionalLegendreShape<7> psi1(s[0]);
         OneDimensionalLegendreDShape<7> dpsi1ds(s[0]);
         // Loop over shapes and copy across
         for (unsigned i = 0; i < p_order(); i++)
         {
           psi(i) = psi1[i];
           dpsi(i, 0) = dpsi1ds[i];
         }
         break;
       }
       default:
         oomph_info
           << "\n ERROR: PRefineableQElement::dshape_local() exceeded maximum";
         oomph_info << "\n        polynomial order for shape functions."
                    << std::endl;
     }
   }
References oomph::OneDimensionalLegendreShape< NNODE_1D >::calculate_nodal_positions(), i, oomph::oomph_info, and s.
further_setup_hanging_nodes()
template<unsigned INITIAL_NNODE_1D> void oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::further_setup_hanging_nodes () inline virtual
Perform additional hanging node procedures for variables that are not interpolated by all nodes (e.g. lower order interpolations for the pressure in Taylor Hood).
Reimplemented from oomph::RefineableElement.
 {}
get_node_at_local_coordinate()
template<unsigned INITIAL_NNODE_1D> Node * oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::get_node_at_local_coordinate (const Vector< double > & s) const virtual
Return the node at the specified local coordinate.
Reimplemented from oomph::FiniteElement.
   {
     // Load the tolerance into a local variable
     double tol = FiniteElement::Node_location_tolerance;
     // There is one possible index.
     Vector<int> index(1);
     // Determine the index
     // -------------------
     // If we are at the lower limit, the index is zero
     if (std::fabs(s[0] + 1.0) < tol)
     {
       index[0] = 0;
     }
     // If we are at the upper limit, the index is the number of nodes minus 1
     else if (std::fabs(s[0] - 1.0) < tol)
     {
       index[0] = this->nnode_1d() - 1;
     }
     // Otherwise, we have to calculate the index in general
     else
     {
       // Compute Gauss-Lobatto-Legendre node positions
       Vector<double> z;
       Orthpoly::gll_nodes(this->nnode_1d(), z);
       // Loop over possible internal nodal positions
       for (unsigned n = 1; n < this->nnode_1d() - 1; n++)
       {
         if (std::fabs(z[n] - s[0]) < tol)
         {
           index[0] = n;
           break;
         }
       }
       // No matching nodes
       return 0;
     }
     // If we've got here we have a node, so let's return a pointer to it
     return this->node_pt(index[0]);
   }
References boost::multiprecision::fabs(), oomph::Orthpoly::gll_nodes(), n, oomph::FiniteElement::Node_location_tolerance, and s.
Referenced by p_refine().
initial_p_order()
template<unsigned INITIAL_NNODE_1D> unsigned oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::initial_p_order () const inline virtual
Get the initial P_order.
Implements oomph::PRefineableElement.
     {
       return INITIAL_NNODE_1D;
     }
initial_setup()
template<unsigned INITIAL_NNODE_1D> void oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::initial_setup (Tree *const & adopted_father_pt = 0, const unsigned & initial_p_order = 0) virtual
Initial setup of element (set the correct p-order and integration scheme) If an adopted father is specified, information from this is used instead of using the father found from the tree.
Set the correct p-order of the element based on that of its father. Then construct an integration scheme of the correct order. If an adopted father is specified, information from this is used instead of using the father found from the tree.
Reimplemented from oomph::RefineableElement.
   {
     // Storage for pointer to my father (in binarytree impersonation)
     BinaryTree* father_pt = 0;
     // Check if an adopted father has been specified
     if (adopted_father_pt != 0)
     {
       // Get pointer to my father (in binarytree impersonation)
       father_pt = dynamic_cast<BinaryTree*>(adopted_father_pt);
     }
     // Check if element is in a tree
     else if (Tree_pt != 0)
     {
       // Get pointer to my father (in binarytree impersonation)
       father_pt = dynamic_cast<BinaryTree*>(binary_tree_pt()->father_pt());
     }
     // else
     // {
     //  throw OomphLibError(
     //         "Element not in a tree, and no adopted father has been
     //         specified!", OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
     // }
     // Check if element has father
     if (father_pt != 0 || initial_p_order != 0)
     {
       if (father_pt != 0)
       {
         PRefineableQElement<1, INITIAL_NNODE_1D>* father_el_pt =
           dynamic_cast<PRefineableQElement<1, INITIAL_NNODE_1D>*>(
             father_pt->object_pt());
         if (father_el_pt != 0)
         {
           unsigned father_p_order = father_el_pt->p_order();
           // Set p-order to that of father
           P_order = father_p_order;
         }
       }
       else
       {
         P_order = initial_p_order;
       }
       // Now sort out the element...
       // (has p nodes)
       unsigned new_n_node = P_order;
       // Allocate new space for Nodes (at the element level)
       this->set_n_node(new_n_node);
       // Set integration scheme
       delete this->integral_pt();
       switch (P_order)
       {
         case 2:
           this->set_integration_scheme(new GaussLobattoLegendre<1, 2>);
           break;
         case 3:
           this->set_integration_scheme(new GaussLobattoLegendre<1, 3>);
           break;
         case 4:
           this->set_integration_scheme(new GaussLobattoLegendre<1, 4>);
           break;
         case 5:
           this->set_integration_scheme(new GaussLobattoLegendre<1, 5>);
           break;
         case 6:
           this->set_integration_scheme(new GaussLobattoLegendre<1, 6>);
           break;
         case 7:
           this->set_integration_scheme(new GaussLobattoLegendre<1, 7>);
           break;
         default:
           std::ostringstream error_message;
           error_message << "\nERROR: Exceeded maximum polynomial order for";
           error_message << "\n       integration scheme.\n";
           throw OomphLibError(error_message.str(),
                               OOMPH_CURRENT_FUNCTION,
                               OOMPH_EXCEPTION_LOCATION);
       }
     }
   }
References oomph::Tree::object_pt(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, and oomph::PRefineableElement::p_order().
local_coordinate_of_node()
template<unsigned INITIAL_NNODE_1D> void oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::local_coordinate_of_node (const unsigned & n, Vector< double > & s) const virtual
Get local coordinates of node j in the element; vector sets its own size.
Reimplemented from oomph::FiniteElement.
   {
     s.resize(1);
     switch (this->nnode_1d())
     {
       case 2:
         OneDimensionalLegendreShape<2>::calculate_nodal_positions();
         s[0] = OneDimensionalLegendreShape<2>::nodal_position(n);
         break;
       case 3:
         OneDimensionalLegendreShape<3>::calculate_nodal_positions();
         s[0] = OneDimensionalLegendreShape<3>::nodal_position(n);
         break;
       case 4:
         OneDimensionalLegendreShape<4>::calculate_nodal_positions();
         s[0] = OneDimensionalLegendreShape<4>::nodal_position(n);
         break;
       case 5:
         OneDimensionalLegendreShape<5>::calculate_nodal_positions();
         s[0] = OneDimensionalLegendreShape<5>::nodal_position(n);
         break;
       case 6:
         OneDimensionalLegendreShape<6>::calculate_nodal_positions();
         s[0] = OneDimensionalLegendreShape<6>::nodal_position(n);
         break;
       case 7:
         OneDimensionalLegendreShape<7>::calculate_nodal_positions();
         s[0] = OneDimensionalLegendreShape<7>::nodal_position(n);
         break;
       default:
         oomph_info << "\n ERROR: Exceeded maximum polynomial order for";
         oomph_info << "\n        shape functions." << std::endl;
         break;
     }
   }
References oomph::OneDimensionalLegendreShape< NNODE_1D >::calculate_nodal_positions(), n, oomph::OneDimensionalLegendreShape< NNODE_1D >::nodal_position(), oomph::oomph_info, and s.
local_fraction_of_node()
template<unsigned INITIAL_NNODE_1D> void oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::local_fraction_of_node (const unsigned & n, Vector< double > & s_fraction) virtual
Get the local fractino of node j in the element.
Reimplemented from oomph::FiniteElement.
   {
     this->local_coordinate_of_node(n, s_fraction);
     s_fraction[0] = 0.5 * (s_fraction[0] + 1.0);
   }
References n.
local_one_d_fraction_of_node()
template<unsigned INITIAL_NNODE_1D> double oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::local_one_d_fraction_of_node (const unsigned & n1d, const unsigned & i) virtual
The local one-d fraction is the same.
Reimplemented from oomph::FiniteElement.
   {
     switch (this->nnode_1d())
     {
       case 2:
         OneDimensionalLegendreShape<2>::calculate_nodal_positions();
         return 0.5 *
                (OneDimensionalLegendreShape<2>::nodal_position(n1d) + 1.0);
       case 3:
         OneDimensionalLegendreShape<3>::calculate_nodal_positions();
         return 0.5 *
                (OneDimensionalLegendreShape<3>::nodal_position(n1d) + 1.0);
       case 4:
         OneDimensionalLegendreShape<4>::calculate_nodal_positions();
         return 0.5 *
                (OneDimensionalLegendreShape<4>::nodal_position(n1d) + 1.0);
       case 5:
         OneDimensionalLegendreShape<5>::calculate_nodal_positions();
         return 0.5 *
                (OneDimensionalLegendreShape<5>::nodal_position(n1d) + 1.0);
       case 6:
         OneDimensionalLegendreShape<6>::calculate_nodal_positions();
         return 0.5 *
                (OneDimensionalLegendreShape<6>::nodal_position(n1d) + 1.0);
       case 7:
         OneDimensionalLegendreShape<7>::calculate_nodal_positions();
         return 0.5 *
                (OneDimensionalLegendreShape<7>::nodal_position(n1d) + 1.0);
       default:
         std::ostringstream error_message;
         error_message << "\nERROR: Exceeded maximum polynomial order for";
         error_message << "\n       shape functions.\n";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
         return 0.0;
     }
   }
References oomph::OneDimensionalLegendreShape< NNODE_1D >::calculate_nodal_positions(), oomph::OneDimensionalLegendreShape< NNODE_1D >::nodal_position(), OOMPH_CURRENT_FUNCTION, and OOMPH_EXCEPTION_LOCATION.
nnode_1d()
template<unsigned INITIAL_NNODE_1D> unsigned oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::nnode_1d () const inline virtual
Returns the number of nodes along each edge of the element. Overloaded to return the (variable) p-order rather than the template argument.
Reimplemented from oomph::FiniteElement.
     {
       return this->p_order();
     }
node_created_by_son_of_neighbour()
template<unsigned INITIAL_NNODE_1D> Node * oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::node_created_by_son_of_neighbour (const Vector< double > & s_fraction, bool & is_periodic)
If a neighbouring element's son has already created a node at a position corresponding to the local fractional position within the present element, s_fraction, return a pointer to that node. If not, return NULL (0). If the node is periodic the flag is_periodic will be true
   {
     // Not possible in 1D case, so return null pointer
     return 0;
   }
p_refine()
template<unsigned INITIAL_NNODE_1D> void oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::p_refine (const int & inc, Mesh *const & mesh_pt, GeneralisedElement *const & clone_pt) virtual
p-refine the element (refine if inc>0, unrefine if inc<0).
p-refine the element inc times. (If inc<0 then p-unrefinement is performed.)
Implements oomph::PRefineableElement.
   {
     // Cast clone to correct type
     PRefineableQElement<1, INITIAL_NNODE_1D>* clone_el_pt =
       dynamic_cast<PRefineableQElement<1, INITIAL_NNODE_1D>*>(clone_pt);
     // Check if we can use it
     if (clone_el_pt == 0)
     {
       throw OomphLibError(
         "Cloned copy must be a PRefineableQElement<1,INITIAL_NNODE_1D>!",
         OOMPH_CURRENT_FUNCTION,
         OOMPH_EXCEPTION_LOCATION);
     }
 #ifdef PARANOID
     // Clone exists, so check that it is infact a copy of me
     else
     {
       // Flag to keep track of check
       bool clone_is_ok = true;
       // Does the clone have the correct p-order?
       clone_is_ok = clone_is_ok && (clone_el_pt->p_order() == this->p_order());
       if (!clone_is_ok)
       {
         std::ostringstream err_stream;
         err_stream << "Clone element has a different p-order from me,"
                    << std::endl
                    << "but it is supposed to be a copy!" << std::endl;
         throw OomphLibError(
           err_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
       // Does the clone have the same number of nodes as me?
       clone_is_ok = clone_is_ok && (clone_el_pt->nnode() == this->nnode());
       if (!clone_is_ok)
       {
         std::ostringstream err_stream;
         err_stream << "Clone element has a different number of nodes from me,"
                    << std::endl
                    << "but it is supposed to be a copy!" << std::endl;
         throw OomphLibError(
           err_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
       // Does the clone have the same nodes as me?
       for (unsigned n = 0; n < this->nnode(); n++)
       {
         clone_is_ok =
           clone_is_ok && (clone_el_pt->node_pt(n) == this->node_pt(n));
       }
       if (!clone_is_ok)
       {
         std::ostringstream err_stream;
         err_stream << "The nodes belonging to the clone element are different"
                    << std::endl
                    << "from mine, but it is supposed to be a copy!"
                    << std::endl;
         throw OomphLibError(
           err_stream.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
       // If we get to here then the clone has all the information we require
     }
 #endif
     // Currently we can't handle the case of generalised coordinates
     // since we haven't established how they should be interpolated.
     // Buffer this case:
     if (clone_el_pt->node_pt(0)->nposition_type() != 1)
     {
       throw OomphLibError("Can't handle generalised nodal positions (yet).",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
     // Timestepper should be the same for all nodes -- use it
     // to create timesteppers for new nodes
     TimeStepper* time_stepper_pt = this->node_pt(0)->time_stepper_pt();
     // Get number of history values (incl. present)
     unsigned ntstorage = time_stepper_pt->ntstorage();
     // Increment p-order of the element
     P_order += inc;
     // Change integration scheme
     delete this->integral_pt();
     switch (P_order)
     {
       case 2:
         this->set_integration_scheme(new GaussLobattoLegendre<1, 2>);
         break;
       case 3:
         this->set_integration_scheme(new GaussLobattoLegendre<1, 3>);
         break;
       case 4:
         this->set_integration_scheme(new GaussLobattoLegendre<1, 4>);
         break;
       case 5:
         this->set_integration_scheme(new GaussLobattoLegendre<1, 5>);
         break;
       case 6:
         this->set_integration_scheme(new GaussLobattoLegendre<1, 6>);
         break;
       case 7:
         this->set_integration_scheme(new GaussLobattoLegendre<1, 7>);
         break;
       default:
         std::ostringstream error_message;
         error_message << "\nERROR: Exceeded maximum polynomial order for";
         error_message << "\n       integration scheme.\n";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
     }
     // Allocate new space for Nodes (at the element level)
     this->set_n_node(P_order);
     // Copy vertex nodes and create new internal nodes
     //------------------------------------------------
     // Setup vertex coordinates in element:
     //-------------------------------------
     Vector<double> s_left(1);
     Vector<double> s_right(1);
     s_left[0] = -1.0;
     s_right[0] = 1.0;
     // Local coordinate in element
     Vector<double> s(1);
     Vector<double> s_fraction(1);
     // Loop over all nodes in the element
     for (unsigned n = 0; n < P_order; n++)
     {
       // Get the fractional position (in the current element) of the node
       // in the direction of s[0]
       s_fraction[0] = this->local_one_d_fraction_of_node(n, 0);
       // Evaluate the local coordinate of the node in the father element
       s[0] = s_left[0] + (s_right[0] - s_left[0]) * s_fraction[0];
       // Initialise flag: So far, this node hasn't been built or copied yet
       bool node_done = false;
       // Get the pointer to the node in this element (or rather, its clone),
       // returns NULL if there is not node
       Node* created_node_pt = clone_el_pt->get_node_at_local_coordinate(s);
       // Does this node already exist in this element?
       //----------------------------------------------
       if (created_node_pt != 0)
       {
         // Copy node across
         this->node_pt(n) = created_node_pt;
         // Make sure that we update the values at the node so that they
         // are consistent with the present representation. This is only
         // needed for mixed interpolation where the value at the father
         // could now become active.
         // Loop over all history values
         for (unsigned t = 0; t < ntstorage; t++)
         {
           // Get values from father element
           // Note: get_interpolated_values() sets Vector size itself
           Vector<double> prev_values;
           clone_el_pt->get_interpolated_values(t, s, prev_values);
           // Find the minimum number of values
           //(either those stored at the node, or those returned by
           // the function)
           unsigned n_val_at_node = created_node_pt->nvalue();
           unsigned n_val_from_function = prev_values.size();
           // Use the ternary conditional operator here
           unsigned n_var = n_val_at_node < n_val_from_function ?
                              n_val_at_node :
                              n_val_from_function;
           // Assign the values that we can
           for (unsigned k = 0; k < n_var; k++)
           {
             created_node_pt->set_value(t, k, prev_values[k]);
           }
         }
         // Indicate that node has been created by copy
         node_done = true;
       }
       // Node does not exist in this element
       //------------------------------------
       // If the node has not been built anywhere ---> build it here
       if (!node_done)
       {
         // In a 1D mesh any node which lies on the boundary must exist in
         // the initial (coarse) mesh, so any newly-built nodes cannot be
         // boundary nodes. Therefore we always create a normal "bulk" node.
         // Create node and set the pointer to it from the element
         created_node_pt = this->construct_node(n, time_stepper_pt);
         // Now we set the position and values at the newly created node
         // Now we set the position and values at the newly created node.
         // In the first instance use macro element or FE representation
         // to create past and present nodal positions.
         // (THIS STEP SHOULD NOT BE SKIPPED FOR ALGEBRAIC ELEMENTS AS NOT
         // ALL OF THEM NECESSARILY IMPLEMENT NONTRIVIAL NODE UPDATE
         // FUNCTIONS. CALLING THE NODE UPDATE FOR SUCH ELEMENTS/NODES WILL
         // LEAVE THEIR NODAL POSITIONS WHERE THEY WERE (THIS IS APPROPRIATE
         // ONCE THEY HAVE BEEN GIVEN POSITIONS) BUT WILL NOT ASSIGN SENSIBLE
         // INITIAL POSITIONS!)
         // Loop over history values
         for (unsigned t = 0; t < ntstorage; t++)
         {
           // Allocate storage for the previous position of the node
           Vector<double> x_prev(1);
           // Get position from father element -- this uses the macro
           // element representation if appropriate.
           clone_el_pt->get_x(t, s, x_prev);
           // Set the previous position of the new node
           created_node_pt->x(t, 0) = x_prev[0];
           // Allocate storage for the previous values at the node
           // NOTE: the size of this vector is equal to the number of values
           // (e.g. 3 velocity components and 1 pressure, say)
           // associated with each node and NOT the number of history values
           // which the node stores!
           Vector<double> prev_values;
           // Get values from father element
           // Note: get_interpolated_values() sets Vector size itself.
           clone_el_pt->get_interpolated_values(t, s, prev_values);
           // Determine the number of values at the new node
           const unsigned n_value = created_node_pt->nvalue();
           // Loop over all values and set the previous values
           for (unsigned v = 0; v < n_value; v++)
           {
             created_node_pt->set_value(t, v, prev_values[v]);
           }
         } // End of loop over history values
         // Add new node to mesh (if requested)
         if (mesh_pt != 0)
         {
           mesh_pt->add_node_pt(created_node_pt);
         }
         AlgebraicElementBase* alg_el_pt =
           dynamic_cast<AlgebraicElementBase*>(this);
         // If we do have an algebraic element
         if (alg_el_pt != 0)
         {
           std::string error_message = "Have not implemented p-refinement for";
           error_message += "Algebraic p-refineable elements yet\n";
           throw OomphLibError(
             error_message,
             "PRefineableQElement<1,INITIAL_NNODE_1D>::p_refine()",
             OOMPH_EXCEPTION_LOCATION);
         }
       } // End of case where we build the node ourselves
       // Check if the element is an algebraic element
       AlgebraicElementBase* alg_el_pt =
         dynamic_cast<AlgebraicElementBase*>(this);
       // If the element is an algebraic element, setup
       // node position (past and present) from algebraic node update
       // function. This over-writes previous assingments that
       // were made based on the macro-element/FE representation.
       // NOTE: YES, THIS NEEDS TO BE CALLED REPEATEDLY IF THE
       // NODE IS MEMBER OF MULTIPLE ELEMENTS: THEY ALL ASSIGN
       // THE SAME NODAL POSITIONS BUT WE NEED TO ADD THE REMESH
       // INFO FOR *ALL* ROOT ELEMENTS!
       if (alg_el_pt != 0)
       {
         // Build algebraic node update info for new node
         // This sets up the node update data for all node update
         // functions that are shared by all nodes in the father
         // element
         alg_el_pt->setup_algebraic_node_update(
           this->node_pt(n), s, clone_el_pt);
       }
     } // End of loop over all nodes in element
     // If the element is a MacroElementNodeUpdateElement, set
     // the update parameters for the current element's nodes --
     // all this needs is the vector of (pointers to the)
     // geometric objects that affect the MacroElement-based
     // node update -- this needs to be done to set the node
     // update info for newly created nodes
     MacroElementNodeUpdateElementBase* clone_m_el_pt =
       dynamic_cast<MacroElementNodeUpdateElementBase*>(clone_el_pt);
     if (clone_m_el_pt != 0)
     {
       // Get vector of geometric objects from father (construct vector
       // via copy operation)
       Vector<GeomObject*> geom_object_pt(clone_m_el_pt->geom_object_pt());
       // Cast current element to MacroElementNodeUpdateElement:
       MacroElementNodeUpdateElementBase* m_el_pt =
         dynamic_cast<MacroElementNodeUpdateElementBase*>(this);
 #ifdef PARANOID
       if (m_el_pt == 0)
       {
         std::string error_message =
           "Failed to cast to MacroElementNodeUpdateElementBase*\n";
         error_message +=
           "Strange -- if my clone is a MacroElementNodeUpdateElement\n";
         error_message += "then I should be too....\n";
         throw OomphLibError(
           error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
       }
 #endif
       // Build update info by passing vector of geometric objects:
       // This sets the current element to be the update element
       // for all of the element's nodes -- this is reversed
       // if the element is ever un-refined in the father element's
       // rebuild_from_sons() function which overwrites this
       // assignment to avoid nasty segmentation faults that occur
       // when a node tries to update itself via an element that no
       // longer exists...
       m_el_pt->set_node_update_info(geom_object_pt);
     }
     // Loop over all nodes in element again, to re-set the positions
     // This must be done using the new element's macro-element
     // representation, rather than the old version which may be
     // of a different p-order!
     for (unsigned n = 0; n < P_order; n++)
     {
       // Get the fractional position of the node in the direction of s[0]
       s_fraction[0] = this->local_one_d_fraction_of_node(n, 0);
       // Local coordinate
       s[0] = s_left[0] + (s_right[0] - s_left[0]) * s_fraction[0];
       // Loop over # of history values
       for (unsigned t = 0; t < ntstorage; t++)
       {
         // Get position from father element -- this uses the macro
         // element representation if appropriate. If the node
         // turns out to be a hanging node later on, then
         // its position gets adjusted in line with its
         // hanging node interpolation.
         Vector<double> x_prev(1);
         this->get_x(t, s, x_prev);
         // Set previous positions of the new node
         this->node_pt(n)->x(t, 0) = x_prev[0];
       }
     }
     // Not necessary to delete the old nodes since all original nodes are in the
     // current mesh and so will be pruned as part of the mesh adaption process.
     // Do any further-build required
     this->further_build();
   }
References oomph::Mesh::add_node_pt(), oomph::MacroElementNodeUpdateElementBase::geom_object_pt(), oomph::RefineableElement::get_interpolated_values(), get_node_at_local_coordinate(), oomph::FiniteElement::get_x(), k, n, oomph::FiniteElement::nnode(), oomph::FiniteElement::node_pt(), oomph::Node::nposition_type(), oomph::TimeStepper::ntstorage(), oomph::Data::nvalue(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::PRefineableElement::p_order(), s, oomph::MacroElementNodeUpdateElementBase::set_node_update_info(), oomph::Data::set_value(), oomph::AlgebraicElementBase::setup_algebraic_node_update(), oomph::Global_string_for_annotation::string(), plotPSD::t, v, and oomph::Node::x().
pre_build()
template<unsigned INITIAL_NNODE_1D> void oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::pre_build (Mesh *& mesh_pt, Vector< Node * > & new_node_pt) virtual
Pre-build (search father for required nodes which may already exist)
Check the father element for any required nodes which already exist
Reimplemented from oomph::RefineableElement.
   {
     /*
       //Pointer to my father (in binarytree impersonation)
       BinaryTree* father_pt =
       dynamic_cast<BinaryTree*>(binary_tree_pt()->father_pt());
       // Check if element has father
       if (father_pt!=0)
       {
       PRefineableQElement<1>* father_el_pt =
       dynamic_cast<PRefineableQElement<1>*>
       (this->tree_pt()->father_pt()->object_pt());
       if (father_el_pt!=0)
       {
       // Pre-build actions
       //??
       }
       else
       {
       std::ostringstream error_message;
       error_message <<"\nERROR: Dynamic cast failed!\n";
       throw OomphLibError(error_message.str(),
       OOMPH_CURRENT_FUNCTION,
       OOMPH_EXCEPTION_LOCATION);
       }
       }
     */
   }
rebuild_from_sons()
template<unsigned INITIAL_NNODE_1D> void oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::rebuild_from_sons (Mesh *& mesh_pt) virtual
Rebuild the element. This needs to find any nodes in the sons which are still required.
Rebuild the element from nodes found in its sons Adjusts its p-order to be the maximum of its sons' p-orders
Implements oomph::RefineableElement.
   {
     // Get p-orders of sons
     unsigned n_sons = this->tree_pt()->nsons();
     Vector<unsigned> son_p_order(n_sons);
     unsigned max_son_p_order = 0;
     for (unsigned ison = 0; ison < n_sons; ison++)
     {
       PRefineableElement* el_pt = dynamic_cast<PRefineableElement*>(
         this->tree_pt()->son_pt(ison)->object_pt());
       son_p_order[ison] = el_pt->p_order();
       if (son_p_order[ison] > max_son_p_order)
         max_son_p_order = son_p_order[ison];
     }
     unsigned old_Nnode = this->nnode();
     unsigned old_P_order = this->p_order();
     // Set p-order of the element
     this->p_order() = max_son_p_order;
     // Change integration scheme
     delete this->integral_pt();
     switch (this->p_order())
     {
       case 2:
         this->set_integration_scheme(new GaussLobattoLegendre<1, 2>);
         break;
       case 3:
         this->set_integration_scheme(new GaussLobattoLegendre<1, 3>);
         break;
       case 4:
         this->set_integration_scheme(new GaussLobattoLegendre<1, 4>);
         break;
       case 5:
         this->set_integration_scheme(new GaussLobattoLegendre<1, 5>);
         break;
       case 6:
         this->set_integration_scheme(new GaussLobattoLegendre<1, 6>);
         break;
       case 7:
         this->set_integration_scheme(new GaussLobattoLegendre<1, 7>);
         break;
       default:
         std::ostringstream error_message;
         error_message << "\nERROR: Exceeded maximum polynomial order for";
         error_message << "\n       integration scheme.\n";
         throw OomphLibError(error_message.str(),
                             OOMPH_CURRENT_FUNCTION,
                             OOMPH_EXCEPTION_LOCATION);
     }
     // Back up pointers to old nodes before they are lost
     Vector<Node*> old_node_pt(old_Nnode);
     for (unsigned n = 0; n < old_Nnode; n++)
     {
       old_node_pt[n] = this->node_pt(n);
     }
     // Allocate new space for Nodes (at the element level)
     this->set_n_node(this->p_order());
     // Copy vertex nodes and create new edge and internal nodes
     //---------------------------------------------------------
     // Copy vertex nodes
     this->node_pt(0) = old_node_pt[0];
     this->node_pt(this->p_order() - 1) = old_node_pt[old_P_order - 1];
     //=============================================================
     // Below this line is copied from RefineableQSpectralElement<2>
     // The timestepper should be the same for all nodes and node 0 should
     // never be deleted.
     if (this->node_pt(0) == 0)
     {
       throw OomphLibError("The vertex node (0) does not exist",
                           OOMPH_CURRENT_FUNCTION,
                           OOMPH_EXCEPTION_LOCATION);
     }
     TimeStepper* time_stepper_pt = this->node_pt(0)->time_stepper_pt();
     // Determine number of history values stored
     const unsigned ntstorage = time_stepper_pt->ntstorage();
     // Allocate storage for local coordinates
     Vector<double> s_fraction(1), s(1);
     // Determine the number of nodes in the element
     const unsigned n_node = this->nnode_1d();
     // Loop over the nodes in the element
     for (unsigned n = 0; n < n_node; n++)
     {
       // Get the fractional position of the node in the direction of s[0]
       s_fraction[0] = this->local_one_d_fraction_of_node(n, 0);
       // Determine the local coordinate in the father element
       s[0] = -1.0 + 2.0 * s_fraction[0];
       // If the node has not been built
       if (this->node_pt(n) == 0)
       {
         // Has the node been created by one of its neighbours?
         bool is_periodic = false;
         Node* created_node_pt =
           this->node_created_by_neighbour(s_fraction, is_periodic);
         // If it has, set the pointer
         if (created_node_pt != 0)
         {
           // If the node is periodic
           if (is_periodic)
           {
             throw OomphLibError("Cannot handle periodic nodes yet",
                                 OOMPH_CURRENT_FUNCTION,
                                 OOMPH_EXCEPTION_LOCATION);
           }
           // Non-periodic case, just set the pointer
           else
           {
             this->node_pt(n) = created_node_pt;
           }
         }
         // Otherwise, we need to build it
         else
         {
           // First, find the son element in which the node should live
           // Find coordinate in the son
           Vector<double> s_in_son(1);
           using namespace BinaryTreeNames;
           int son = -10;
           // If s_fraction is between 0 and 0.5, we are in the left son
           if (s_fraction[0] < 0.5)
           {
             son = L;
             s_in_son[0] = -1.0 + 4.0 * s_fraction[0];
           }
           // Otherwise we are in the right son
           else
           {
             son = R;
             s_in_son[0] = -1.0 + 4.0 * (s_fraction[0] - 0.5);
           }
           // Get the pointer to the son element in which the new node
           // would live
           PRefineableQElement<1, INITIAL_NNODE_1D>* son_el_pt =
             dynamic_cast<PRefineableQElement<1, INITIAL_NNODE_1D>*>(
               this->tree_pt()->son_pt(son)->object_pt());
           // In 1D we should never be rebuilding an element's vertex nodes
           // (since they will never be deleted), so throw an error if we
           // appear to be doing so
 #ifdef PARANOID
           if (n == 0 || n == n_node - 1)
           {
             std::string error_message =
               "I am trying to rebuild one of the (two) vertex nodes in\n";
             error_message +=
               "this 1D element. It should not have been possible to delete\n";
             error_message += "either of these!\n";
             throw OomphLibError(
               error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
           }
 #endif
           // With this in mind we will always be creating normal "bulk" nodes
           this->node_pt(n) = this->construct_node(n, time_stepper_pt);
           // Now we set the position and values at the newly created node
           // In the first instance use macro element or FE representation
           // to create past and present nodal positions.
           // (THIS STEP SHOULD NOT BE SKIPPED FOR ALGEBRAIC ELEMENTS AS NOT
           // ALL OF THEM NECESSARILY IMPLEMENT NONTRIVIAL NODE UPDATE
           // FUNCTIONS. CALLING THE NODE UPDATE FOR SUCH ELEMENTS/NODES WILL
           // LEAVE THEIR NODAL POSITIONS WHERE THEY WERE (THIS IS APPROPRIATE
           // ONCE THEY HAVE BEEN GIVEN POSITIONS) BUT WILL NOT ASSIGN SENSIBLE
           // INITIAL POSITIONS!)
           // Loop over history values
           for (unsigned t = 0; t < ntstorage; t++)
           {
             // Allocate storage for the previous position of the node
             Vector<double> x_prev(1);
             // Get position from son element -- this uses the macro element
             // representation if appropriate
             son_el_pt->get_x(t, s_in_son, x_prev);
             // Set the previous position of the new node
             this->node_pt(n)->x(t, 0) = x_prev[0];
             // Allocate storage for the previous values at the node
             // NOTE: the size of this vector is equal to the number of values
             // (e.g. 3 velocity components and 1 pressure, say)
             // associated with each node and NOT the number of history values
             // which the node stores!
             Vector<double> prev_values;
             // Get values from son element
             // Note: get_interpolated_values() sets Vector size itself.
             son_el_pt->get_interpolated_values(t, s_in_son, prev_values);
             // Determine the number of values at the new node
             const unsigned n_value = this->node_pt(n)->nvalue();
             // Loop over all values and set the previous values
             for (unsigned v = 0; v < n_value; v++)
             {
               this->node_pt(n)->set_value(t, v, prev_values[v]);
             }
           } // End of loop over history values
           // Add new node to mesh
           mesh_pt->add_node_pt(this->node_pt(n));
         } // End of case where we build the node ourselves
       } // End of if this node has not been built
     } // End of loop over nodes in element
     // Check if the element is an algebraic element
     // This is done on all nodes in the element after reconstruction
     // rather than as the nodes are built
     AlgebraicElementBase* alg_el_pt = dynamic_cast<AlgebraicElementBase*>(this);
     // If so, throw error
     if (alg_el_pt != 0)
     {
       std::string error_message =
         "Have not implemented rebuilding from sons for";
       error_message += "Algebraic p-refineable elements yet\n";
       throw OomphLibError(
         error_message,
         "PRefineableQElement<1,INITIAL_NNODE_1D>::rebuild_from_sons()",
         OOMPH_EXCEPTION_LOCATION);
     }
   }
References oomph::Mesh::add_node_pt(), oomph::RefineableElement::get_interpolated_values(), oomph::FiniteElement::get_x(), L, n, oomph::TimeStepper::ntstorage(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION, oomph::PRefineableElement::p_order(), R, s, oomph::Global_string_for_annotation::string(), plotPSD::t, and v.
shape()
template<unsigned INITIAL_NNODE_1D> void oomph::PRefineableQElement< 1, INITIAL_NNODE_1D >::shape (const Vector< double > & s, Shape & psi) const virtual
Overload the shape functions.
Shape functions for PRefineableQElement<DIM>
Implements oomph::FiniteElement.
   {
     switch (p_order())
     {
       case 2:
       {
         // Calculate nodal positions
         OneDimensionalLegendreShape<2>::calculate_nodal_positions();
         // Create one-dim shape functions
         OneDimensionalLegendreShape<2> psi1(s[0]);
         // Now let's loop over the nodal points in the element
         // and copy the values back in
         for (unsigned i = 0; i < p_order(); i++)
         {
           psi(i) = psi1[i];
         }
         break;
       }
       case 3:
       {
         // Calculate nodal positions
         OneDimensionalLegendreShape<3>::calculate_nodal_positions();
         // Create one-dim shape functions
         OneDimensionalLegendreShape<3> psi1(s[0]);
         // Now let's loop over the nodal points in the element
         // and copy the values back in
         for (unsigned i = 0; i < p_order(); i++)
         {
           psi(i) = psi1[i];
         }
         break;
       }
       case 4:
       {
         // Calculate nodal positions
         OneDimensionalLegendreShape<4>::calculate_nodal_positions();
         // Create one-dim shape functions
         OneDimensionalLegendreShape<4> psi1(s[0]);
         // Now let's loop over the nodal points in the element
         // and copy the values back in
         for (unsigned i = 0; i < p_order(); i++)
         {
           psi(i) = psi1[i];
         }
         break;
       }
       case 5:
       {
         // Calculate nodal positions
         OneDimensionalLegendreShape<5>::calculate_nodal_positions();
         // Create one-dim shape functions
         OneDimensionalLegendreShape<5> psi1(s[0]);
         // Now let's loop over the nodal points in the element
         // and copy the values back in
         for (unsigned i = 0; i < p_order(); i++)
         {
           psi(i) = psi1[i];
         }
         break;
       }
       case 6:
       {
         // Calculate nodal positions
         OneDimensionalLegendreShape<6>::calculate_nodal_positions();
         // Create one-dim shape functions
         OneDimensionalLegendreShape<6> psi1(s[0]);
         // Now let's loop over the nodal points in the element
         // and copy the values back in
         for (unsigned i = 0; i < p_order(); i++)
         {
           psi(i) = psi1[i];
         }
         break;
       }
       case 7:
       {
         // Calculate nodal positions
         OneDimensionalLegendreShape<7>::calculate_nodal_positions();
         // Create one-dim shape functions
         OneDimensionalLegendreShape<7> psi1(s[0]);
         // Now let's loop over the nodal points in the element
         // and copy the values back in
         for (unsigned i = 0; i < p_order(); i++)
         {
           psi(i) = psi1[i];
         }
         break;
       }
       default:
         oomph_info << "\n ERROR: PRefineableQElement::shape() exceeded maximum";
         oomph_info << "\n        polynomial order for shape functions."
                    << std::endl;
     }
   }
References oomph::OneDimensionalLegendreShape< NNODE_1D >::calculate_nodal_positions(), i, oomph::oomph_info, and s.
The documentation for this class was generated from the following files:
hp_refineable_elements.h
hp_refineable_elements.cc