MercuryDPM: TanhSolnForUnsteadyHeat Namespace Reference
TanhSolnForUnsteadyHeat Namespace Reference
Functions
double step_position (const double &time)
Position of step (x-axis intercept)
void get_exact_u (const double &time, const Vector< double > &x, Vector< double > &u)
Exact solution as a Vector.
void get_exact_u (const double &time, const Vector< double > &x, double &u)
Exact solution as a scalar.
void get_source (const double &time, const Vector< double > &x, double &source)
Source function to make it an exact solution.
void prescribed_flux_on_fixed_y_boundary (const double &time, const Vector< double > &x, double &flux)
Flux required by the exact solution on a boundary on which y is fixed.
Variables
double Alpha
Parameter for steepness of step.
double Beta
Parameter for amplitude of step translation.
double Gamma
Parameter for timescale of step translation.
double TanPhi
Parameter for angle of step.
Detailed Description
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// Namespace for exact solution of unsteady heat equation with sharp step
Function Documentation
get_exact_u() [1/2]
void TanhSolnForUnsteadyHeat::get_exact_u (const double & time, const Vector< double > & x, double & u)
Exact solution as a scalar.
  {
   double X=x[0];
   double Y=x[1];
   u=tanh(0.1E1-Alpha*(TanPhi*(X-Beta*tanh(Gamma*cos(0.2E1*
          MathematicalConstants::Pi*time)))-Y));
  }
References Alpha, Beta, cos(), Gamma, BiharmonicTestFunctions2::Pi, Eigen::bfloat16_impl::tanh(), TanPhi, plotDoE::x, X, and Y.
get_exact_u() [2/2]
void TanhSolnForUnsteadyHeat::get_exact_u (const double & time, const Vector< double > & x, Vector< double > & u)
Exact solution as a Vector.
  {
   double X=x[0];
   double Y=x[1];
   u[0]=tanh(0.1E1-Alpha*(TanPhi*(X-Beta*tanh(Gamma*cos(0.2E1*
        MathematicalConstants::Pi*time)))-Y));
  }
References Alpha, Beta, cos(), Gamma, BiharmonicTestFunctions2::Pi, Eigen::bfloat16_impl::tanh(), TanPhi, plotDoE::x, X, and Y.
Referenced by RefineableUnsteadyHeatProblem< ELEMENT >::doc_solution().
get_source()
void TanhSolnForUnsteadyHeat::get_source (const double & time, const Vector< double > & x, double & source)
Source function to make it an exact solution.
  {
   double X=x[0];
   double Y=x[1];
   source =  -2.0*tanh(0.1E1-Alpha*(TanPhi*(X-Beta*tanh(Gamma*cos(0.2E1*
 MathematicalConstants::Pi*time)))-Y))*(1.0-pow(tanh(0.1E1-Alpha*(TanPhi*(X-
 Beta*tanh(Gamma*cos(0.2E1*MathematicalConstants::Pi*time)))-Y)),2.0))*Alpha*
 Alpha*TanPhi*TanPhi-2.0*tanh(0.1E1-Alpha*(TanPhi*(X-Beta*tanh(Gamma*cos(0.2E1*
 MathematicalConstants::Pi*time)))-Y))*(1.0-pow(tanh(0.1E1-Alpha*(TanPhi*(X-
 Beta*tanh(Gamma*cos(0.2E1*MathematicalConstants::Pi*time)))-Y)),2.0))*Alpha*
 Alpha+0.2E1*(1.0-pow(tanh(0.1E1-Alpha*(TanPhi*(X-Beta*tanh(Gamma*cos(0.2E1*
 MathematicalConstants::Pi*time)))-Y)),2.0))*Alpha*TanPhi*Beta*(1.0-pow(tanh(
 Gamma*cos(0.2E1*MathematicalConstants::Pi*time)),2.0))*Gamma*sin(0.2E1*
 MathematicalConstants::Pi*time)*MathematicalConstants::Pi;
  }
References Alpha, Beta, cos(), Gamma, BiharmonicTestFunctions2::Pi, Eigen::bfloat16_impl::pow(), sin(), TestProblem::source(), Eigen::bfloat16_impl::tanh(), TanPhi, plotDoE::x, X, and Y.
Referenced by main(), and run_it().
prescribed_flux_on_fixed_y_boundary()
void TanhSolnForUnsteadyHeat::prescribed_flux_on_fixed_y_boundary (const double & time, const Vector< double > & x, double & flux)
Flux required by the exact solution on a boundary on which y is fixed.
  {
   double X=x[0];
   double Y=x[1];
   //The outer unit normal to the boundary is (0,-1)
   double NX =  0.0;
   double NY = -1.0;
   //The flux in terms of the normal is
   flux =  -(1.0-pow(tanh(0.1E1-Alpha*(TanPhi*(X-Beta*tanh(Gamma*cos(0.2E1*
 MathematicalConstants::Pi*time)))-Y)),2.0))*Alpha*TanPhi*NX+(1.0-pow(tanh(
 0.1E1-Alpha*(TanPhi*(X-Beta*tanh(Gamma*cos(0.2E1*MathematicalConstants::Pi*
 time)))-Y)),2.0))*Alpha*NY;
  }
References Alpha, Beta, cos(), ProblemParameters::flux(), Gamma, BiharmonicTestFunctions2::Pi, Eigen::bfloat16_impl::pow(), Eigen::bfloat16_impl::tanh(), TanPhi, plotDoE::x, X, and Y.
Referenced by RefineableUnsteadyHeatProblem< ELEMENT >::RefineableUnsteadyHeatProblem().
step_position()
double TanhSolnForUnsteadyHeat::step_position (const double & time)
Position of step (x-axis intercept)
  {
   return Beta*tanh(Gamma*cos(0.2E1*MathematicalConstants::Pi*time));
  }
References Beta, cos(), Gamma, BiharmonicTestFunctions2::Pi, and Eigen::bfloat16_impl::tanh().
Referenced by RefineableUnsteadyHeatProblem< ELEMENT >::doc_solution().
Variable Documentation
Alpha
double TanhSolnForUnsteadyHeat::Alpha
Parameter for steepness of step.
Referenced by get_exact_u(), get_source(), prescribed_flux_on_fixed_y_boundary(), and RefineableUnsteadyHeatProblem< ELEMENT >::RefineableUnsteadyHeatProblem().
Beta
double TanhSolnForUnsteadyHeat::Beta
Parameter for amplitude of step translation.
Referenced by get_exact_u(), get_source(), prescribed_flux_on_fixed_y_boundary(), RefineableUnsteadyHeatProblem< ELEMENT >::RefineableUnsteadyHeatProblem(), and step_position().
Gamma
double TanhSolnForUnsteadyHeat::Gamma
Parameter for timescale of step translation.
Referenced by get_exact_u(), get_source(), prescribed_flux_on_fixed_y_boundary(), RefineableUnsteadyHeatProblem< ELEMENT >::RefineableUnsteadyHeatProblem(), and step_position().
TanPhi
double TanhSolnForUnsteadyHeat::TanPhi
Parameter for angle of step.
Referenced by get_exact_u(), get_source(), prescribed_flux_on_fixed_y_boundary(), and RefineableUnsteadyHeatProblem< ELEMENT >::RefineableUnsteadyHeatProblem().