MercuryDPM: oomph::SingleLayerCubicSpineMesh< ELEMENT > Class Template Reference
oomph::SingleLayerCubicSpineMesh< ELEMENT > Class Template Reference
#include <single_layer_cubic_spine_mesh.template.h>
Public Member Functions
SingleLayerCubicSpineMesh (const unsigned &nx, const unsigned &ny, const unsigned &nz, const double &lx, const double &ly, const double &h, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
virtual void spine_node_update (SpineNode *spine_node_pt)
Public Member Functions inherited from oomph::SimpleCubicMesh< ELEMENT >
SimpleCubicMesh (const unsigned &nx, const unsigned &ny, const unsigned &nz, const double &lx, const double &ly, const double &lz, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
SimpleCubicMesh (const unsigned &nx, const unsigned &ny, const unsigned &nz, const double &xmin, const double &xmax, const double &ymin, const double &ymax, const double &zmin, const double &zmax, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
const unsigned & nx () const
Access function for number of elements in x directions.
const unsigned & ny () const
Access function for number of elements in y directions.
const unsigned & nz () const
Access function for number of elements in y directions.
Public Member Functions inherited from oomph::BrickMeshBase
BrickMeshBase ()
Constructor (empty)
BrickMeshBase (const BrickMeshBase &)=delete
Broken copy constructor.
virtual ~BrickMeshBase ()
Broken assignment operator.
void setup_boundary_element_info ()
void setup_boundary_element_info (std::ostream &outfile)
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Public Member Functions inherited from oomph::SpineMesh
virtual ~SpineMesh ()
Destructor to clean up the memory allocated to the spines.
Spine *& spine_pt (const unsigned long &i)
Return the i-th spine in the mesh.
const Spine * spine_pt (const unsigned long &i) const
Return the i-th spine in the mesh (const version)
unsigned long nspine () const
Return the number of spines in the mesh.
void add_spine_pt (Spine *const &spine_pt)
Add a spine to the mesh.
SpineNode * node_pt (const unsigned long &n)
Return a pointer to the n-th global SpineNode.
SpineNode * element_node_pt (const unsigned long &e, const unsigned &n)
unsigned long assign_global_spine_eqn_numbers (Vector< double * > &Dof_pt)
Assign spines to Spine_pt vector of element.
void describe_spine_dofs (std::ostream &out, const std::string &current_string) const
void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_spine_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Assign time stepper to spines data.
void set_consistent_pinned_spine_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
bool does_pointer_correspond_to_spine_data (double *const &parameter_pt)
void node_update (const bool &update_all_solid_nodes=false)
void dump (std::ofstream &dump_file) const
Overload the dump function so that the spine data is dumped.
void read (std::ifstream &restart_file)
Overload the read function so that the spine data is also read.
Protected Member Functions
virtual void build_single_layer_mesh (TimeStepper *time_stepper_pt)
Protected Member Functions inherited from oomph::SimpleCubicMesh< ELEMENT >
void build_mesh (TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Generic mesh construction function: contains all the hard work.
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Protected Attributes inherited from oomph::SimpleCubicMesh< ELEMENT >
unsigned Nx
Number of elements in x direction.
unsigned Ny
Number of elements in y direction.
unsigned Nz
Number of elements in y direction.
double Xmin
Minimum value of x coordinate.
double Xmax
Maximum value of x coordinate.
double Ymin
Minimum value of y coordinate.
double Ymax
Minimum value of y coordinate.
double Zmin
Minimum value of z coordinate.
double Zmax
Maximum value of z coordinate.
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Protected Attributes inherited from oomph::SpineMesh
Vector< Spine * > Spine_pt
A Spine mesh contains a Vector of pointers to spines.
Detailed Description
template<class ELEMENT>
class oomph::SingleLayerCubicSpineMesh< ELEMENT >
Spine mesh class derived from standard cubic 3D mesh. The mesh contains a layer of spinified fluid elements (of type ELEMENT; e.g SpineElement<QCrouzeixRaviartElement<3>) for 3D problems, in which the interface's vertical position can vary
This mesh has been carefully designed so that the numeration of the nodes on the boundaries 0 and 5 (bottom and top) coincides with the numeration of the spines
Constructor & Destructor Documentation
SingleLayerCubicSpineMesh()
template<class ELEMENT > oomph::SingleLayerCubicSpineMesh< ELEMENT >::SingleLayerCubicSpineMesh (const unsigned & nx, const unsigned & ny, const unsigned & nz, const double & lx, const double & ly, const double & h, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper)
Constructor: Pass number of elements in x-direction, number of elements in y-direction, number of elements in z-direction, lengths in x- and y- directions, height of layer, and pointer to timestepper (defaults to Steady timestepper)
Constructor for spine 3D mesh: Pass number of elements in x-direction, number of elements in y-direction, number elements in z-direction, length, width and height of layer, and pointer to timestepper (defaults to Static timestepper).
     : SimpleCubicMesh<ELEMENT>(nx, ny, nz, lx, ly, h, time_stepper_pt)
   {
     // Mesh can only be built with 3D Qelements.
     MeshChecker::assert_geometric_element<QElementGeometricBase, ELEMENT>(3);
     // Mesh can only be built with spine elements
     MeshChecker::assert_geometric_element<SpineFiniteElement, ELEMENT>(3);
     // Now build the single layer mesh on top of the existing mesh
     build_single_layer_mesh(time_stepper_pt);
   }
References oomph::SingleLayerCubicSpineMesh< ELEMENT >::build_single_layer_mesh().
Member Function Documentation
build_single_layer_mesh()
template<class ELEMENT > void oomph::SingleLayerCubicSpineMesh< ELEMENT >::build_single_layer_mesh (TimeStepper * time_stepper_pt) protected virtual
Helper function to actually build the single-layer spine mesh (called from various constructors)
Helper function that actually builds the single-layer spine mesh based on the parameters set in the various constructors
   {
     // Read out the number of elements in the x-direction
     unsigned n_x = this->Nx;
     // Read out the number of elements in the y-direction
     unsigned n_y = this->Ny;
     // Read out the number of elements in the z-direction
     unsigned n_z = this->Nz;
     // Allocate memory for the spines and fractions along spines
     // Read out number of linear points in the element
     unsigned n_p = dynamic_cast<ELEMENT*>(finite_element_pt(0))->nnode_1d();
     // Allocate store for the spines: (different in the case of periodic meshes
     // !!)
     Spine_pt.reserve(((n_p - 1) * n_x + 1) * ((n_p - 1) * n_y + 1));
     // Now we loop over all the elements and attach the spines
     // FIRST ELEMENT: Element 0
     // Loop over the nodes on the base of the element
     for (unsigned l1 = 0; l1 < n_p; l1++) // y loop over the nodes
     {
       for (unsigned l2 = 0; l2 < n_p; l2++) // x loop over the nodes
       {
         // Assign the new spine with length h
         Spine* new_spine_pt = new Spine(1.0);
         Spine_pt.push_back(new_spine_pt);
         // Get pointer to node
         SpineNode* nod_pt = element_node_pt(0, l2 + l1 * n_p);
         // Set the pointer to the spine
         nod_pt->spine_pt() = new_spine_pt;
         // Set the fraction
         nod_pt->fraction() = 0.0;
         // Pointer to the mesh that implements the update fct
         nod_pt->spine_mesh_pt() = this;
         // Loop vertically along the spine
         // Loop over the elements
         for (unsigned long k = 0; k < n_z; k++)
         {
           // Loop over the vertical nodes, apart from the first
           for (unsigned l3 = 1; l3 < n_p; l3++)
           {
             // Get pointer to node
             SpineNode* nod_pt =
               element_node_pt(k * n_x * n_y, l3 * n_p * n_p + l2 + l1 * n_p);
             // Set the pointer to the spine
             nod_pt->spine_pt() = new_spine_pt;
             // Set the fraction
             nod_pt->fraction() =
               (double(k) + double(l3) / double(n_p - 1)) / double(n_z);
             // Pointer to the mesh that implements the update fct
             nod_pt->spine_mesh_pt() = this;
           }
         }
       }
     }
     // LOOP OVER OTHER ELEMENTS IN THE FIRST ROW
     //-----------------------------------------
     // The procedure is the same but we have to identify the
     // before defined spines for not defining them two times
     for (unsigned j = 1; j < n_x; j++) // loop over the elements in the first
                                        // row
     {
       for (unsigned l1 = 0; l1 < n_p; l1++) // y loop over the nodes
       {
         // First we copy the last row of nodes into the
         // first row of the new element (and extend to the third dimension)
         for (unsigned l2 = 1; l2 < n_p; l2++) // x loop over the nodes
         {
           // Node j + i*np
           // Assign the new spine with unit length
           Spine* new_spine_pt = new Spine(1.0);
           Spine_pt.push_back(new_spine_pt);
           // Get pointer to node
           SpineNode* nod_pt = element_node_pt(j, l2 + l1 * n_p);
           // Set the pointer to the spine
           nod_pt->spine_pt() = new_spine_pt;
           // Set the fraction
           nod_pt->fraction() = 0.0;
           // Pointer to the mesh that implements the update fct
           nod_pt->spine_mesh_pt() = this;
           // Loop vertically along the spine
           // Loop over the elements
           for (unsigned long k = 0; k < n_z; k++)
           {
             // Loop over the vertical nodes, apart from the first
             for (unsigned l3 = 1; l3 < n_p; l3++)
             {
               // Get pointer to node
               SpineNode* nod_pt = element_node_pt(
                 j + k * n_x * n_y, l3 * n_p * n_p + l2 + l1 * n_p);
               // Set the pointer to the spine
               nod_pt->spine_pt() = new_spine_pt;
               // Set the fraction
               nod_pt->fraction() =
                 (double(k) + double(l3) / double(n_p - 1)) / double(n_z);
               // Pointer to the mesh that implements the update fct
               nod_pt->spine_mesh_pt() = this;
             }
           }
         }
       }
     }
     // REST OF THE ELEMENTS
     // Now we loop over the rest of the elements.
     // We will separate the first of each row being al the rest equal
     for (unsigned long i = 1; i < n_y; i++)
     {
       // FIRST ELEMENT OF THE ROW
       // First line of nodes is copied from the element of the bottom
       for (unsigned l1 = 1; l1 < n_p; l1++) // y loop over the nodes
       {
         for (unsigned l2 = 0; l2 < n_p; l2++) // x loop over the nodes
         {
           // Node j + i*np
           // Assign the new spine with unit length
           Spine* new_spine_pt = new Spine(1.0);
           Spine_pt.push_back(new_spine_pt);
           // Get pointer to node
           // Element i*n_x; node l2 + l1*n_p
           SpineNode* nod_pt = element_node_pt(i * n_x, l2 + l1 * n_p);
           // Set the pointer to the spine
           nod_pt->spine_pt() = new_spine_pt;
           // Set the fraction
           nod_pt->fraction() = 0.0;
           // Pointer to the mesh that implements the update fct
           nod_pt->spine_mesh_pt() = this;
           // Loop vertically along the spine
           // Loop over the elements
           for (unsigned long k = 0; k < n_z; k++)
           {
             // Loop over the vertical nodes, apart from the first
             for (unsigned l3 = 1; l3 < n_p; l3++)
             {
               // Get pointer to node
               SpineNode* nod_pt = element_node_pt(
                 i * n_x + k * n_x * n_y, l3 * n_p * n_p + l2 + l1 * n_p);
               // Set the pointer to the spine
               nod_pt->spine_pt() = new_spine_pt;
               // Set the fraction
               nod_pt->fraction() =
                 (double(k) + double(l3) / double(n_p - 1)) / double(n_z);
               // Pointer to the mesh that implements the update fct
               nod_pt->spine_mesh_pt() = this;
             }
           }
         }
       }
       // REST OF THE ELEMENTS OF THE ROW
       for (unsigned j = 1; j < n_x; j++)
       {
         // First line of nodes is copied from the element of the bottom
         for (unsigned l1 = 1; l1 < n_p; l1++) // y loop over the nodes
         {
           for (unsigned l2 = 1; l2 < n_p; l2++) // x loop over the nodes
           {
             // Node j + i*np
             // Assign the new spine with unit length
             Spine* new_spine_pt = new Spine(1.0);
             Spine_pt.push_back(new_spine_pt);
             // Get pointer to node
             // Element j + i*n_x; node l2 + l1*n_p
             SpineNode* nod_pt = element_node_pt(j + i * n_x, l2 + l1 * n_p);
             // Set the pointer to the spine
             nod_pt->spine_pt() = new_spine_pt;
             // Set the fraction
             nod_pt->fraction() = 0.0;
             // Pointer to the mesh that implements the update fct
             nod_pt->spine_mesh_pt() = this;
             // Loop vertically along the spine
             // Loop over the elements
             for (unsigned long k = 0; k < n_z; k++)
             {
               // Loop over the vertical nodes, apart from the first
               for (unsigned l3 = 1; l3 < n_p; l3++)
               {
                 // Get pointer to node
                 SpineNode* nod_pt = element_node_pt(
                   j + i * n_x + k * n_x * n_y, l3 * n_p * n_p + l2 + l1 * n_p);
                 // Set the pointer to the spine
                 nod_pt->spine_pt() = new_spine_pt;
                 // Set the fraction
                 nod_pt->fraction() =
                   (double(k) + double(l3) / double(n_p - 1)) / double(n_z);
                 // Pointer to the mesh that implements the update fct
                 nod_pt->spine_mesh_pt() = this;
               }
             }
           }
         }
       }
     }
   }
References oomph::SpineNode::fraction(), i, j, k, GlobalParameters::Nx, GlobalParameters::Ny, Global_Parameters::Nz, oomph::SpineNode::spine_mesh_pt(), and oomph::SpineNode::spine_pt().
Referenced by oomph::SingleLayerCubicSpineMesh< ELEMENT >::SingleLayerCubicSpineMesh().
spine_node_update()
template<class ELEMENT > virtual void oomph::SingleLayerCubicSpineMesh< ELEMENT >::spine_node_update (SpineNode * spine_node_pt) inline virtual
General node update function implements pure virtual function defined in SpineMesh base class and performs specific node update actions: along vertical spines
Implements oomph::SpineMesh.
Reimplemented in oomph::AnnularSpineMesh< ELEMENT >.
     {
       // Get fraction along the spine
       double W = spine_node_pt->fraction();
       // Get spine height
       double H = spine_node_pt->h();
       // Set the value of z
       spine_node_pt->x(2) = this->Zmin + W * H;
     }
References oomph::SpineNode::fraction(), H, oomph::SpineNode::h(), oomph::QuadTreeNames::W, oomph::Node::x(), and oomph::SimpleCubicMesh< ELEMENT >::Zmin.
The documentation for this class was generated from the following files:
single_layer_cubic_spine_mesh.template.h
single_layer_cubic_spine_mesh.template.cc