MercuryDPM: Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType > Class Template Reference
Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
Generic expression where a coefficient-wise binary operator is applied to two expressions.
#include <CwiseBinaryOp.h>
Public Types
typedef internal::remove_all_t< BinaryOp > Functor
typedef internal::remove_all_t< LhsType > Lhs
typedef internal::remove_all_t< RhsType > Rhs
typedef CwiseBinaryOpImpl< BinaryOp, LhsType, RhsType, typename internal::cwise_promote_storage_type< typename internal::traits< LhsType >::StorageKind, typename internal::traits< Rhs >::StorageKind, BinaryOp >::ret >::Base Base
typedef internal::ref_selector< LhsType >::type LhsNested
typedef internal::ref_selector< RhsType >::type RhsNested
typedef std::remove_reference_t< LhsNested > LhsNested_
typedef std::remove_reference_t< RhsNested > RhsNested_
Public Types inherited from Eigen::CwiseBinaryOpImpl< BinaryOp, LhsType, RhsType, internal::cwise_promote_storage_type< internal::traits< LhsType >::StorageKind, internal::traits< RhsType >::StorageKind, BinaryOp >::ret >
typedef internal::generic_xpr_base< CwiseBinaryOp< BinaryOp, LhsType, RhsType > >::type Base
Public Member Functions
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CwiseBinaryOp (const Lhs &aLhs, const Rhs &aRhs, const BinaryOp &func=BinaryOp())
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const LhsNested_ & lhs () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const RhsNested_ & rhs () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const BinaryOp & functor () const
Protected Attributes
LhsNested m_lhs
RhsNested m_rhs
const BinaryOp m_functor
Detailed Description
template<typename BinaryOp, typename LhsType, typename RhsType>
class Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >
Generic expression where a coefficient-wise binary operator is applied to two expressions.
Template Parameters
BinaryOp template functor implementing the operator
LhsType the type of the left-hand side
RhsType the type of the right-hand side
This class represents an expression where a coefficient-wise binary operator is applied to two expressions. It is the return type of binary operators, by which we mean only those binary operators where both the left-hand side and the right-hand side are Eigen expressions. For example, the return type of matrix1+matrix2 is a CwiseBinaryOp.
Most of the time, this is the only way that it is used, so you typically don't have to name CwiseBinaryOp types explicitly.
See also
MatrixBase::binaryExpr(const MatrixBase<OtherDerived> &,const CustomBinaryOp &) const, class CwiseUnaryOp, class CwiseNullaryOp
Member Typedef Documentation
Base
template<typename BinaryOp , typename LhsType , typename RhsType > typedef CwiseBinaryOpImpl< BinaryOp, LhsType, RhsType, typename internal::cwise_promote_storage_type<typename internal::traits<LhsType>::StorageKind, typename internal::traits<Rhs>::StorageKind, BinaryOp>::ret>::Base Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::Base
Functor
template<typename BinaryOp , typename LhsType , typename RhsType > typedef internal::remove_all_t<BinaryOp> Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::Functor
Lhs
template<typename BinaryOp , typename LhsType , typename RhsType > typedef internal::remove_all_t<LhsType> Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::Lhs
LhsNested
template<typename BinaryOp , typename LhsType , typename RhsType > typedef internal::ref_selector<LhsType>::type Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::LhsNested
LhsNested_
template<typename BinaryOp , typename LhsType , typename RhsType > typedef std::remove_reference_t<LhsNested> Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::LhsNested_
Rhs
template<typename BinaryOp , typename LhsType , typename RhsType > typedef internal::remove_all_t<RhsType> Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::Rhs
RhsNested
template<typename BinaryOp , typename LhsType , typename RhsType > typedef internal::ref_selector<RhsType>::type Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::RhsNested
RhsNested_
template<typename BinaryOp , typename LhsType , typename RhsType > typedef std::remove_reference_t<RhsNested> Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::RhsNested_
Constructor & Destructor Documentation
CwiseBinaryOp()
template<typename BinaryOp , typename LhsType , typename RhsType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::CwiseBinaryOp (const Lhs & aLhs, const Rhs & aRhs, const BinaryOp & func = BinaryOp()) inline
       : m_lhs(aLhs), m_rhs(aRhs), m_functor(func) {
     eigen_assert(aLhs.rows() == aRhs.rows() && aLhs.cols() == aRhs.cols());
   }
References eigen_assert.
Member Function Documentation
cols()
template<typename BinaryOp , typename LhsType , typename RhsType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EIGEN_CONSTEXPR Index Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::cols () const inline
{
     // return the fixed size type if available to enable compile time optimizations
     return internal::traits<internal::remove_all_t<LhsNested>>::ColsAtCompileTime == Dynamic ? m_rhs.cols()
                                                                                              : m_lhs.cols();
   }
References Eigen::Dynamic, Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::m_lhs, and Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::m_rhs.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), Eigen::internal::visitor_evaluator< XprType >::cols(), Eigen::Reshaped< XprType, Rows, Cols, Order >::Reshaped(), Eigen::internal::redux_impl< Func, Evaluator, DefaultTraversal, NoUnrolling >::run(), Eigen::internal::redux_impl< Func, Evaluator, SliceVectorizedTraversal, Unrolling >::run(), Eigen::internal::redux_impl< Func, Evaluator, LinearVectorizedTraversal, CompleteUnrolling >::run(), Eigen::internal::triangular_solver_selector< Lhs, Rhs, Side, Mode, NoUnrolling, 1 >::run(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
functor()
template<typename BinaryOp , typename LhsType , typename RhsType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const BinaryOp& Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::functor () const inline
Returns
the functor representing the binary operation
 { return m_functor; }
References Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::m_functor.
lhs()
template<typename BinaryOp , typename LhsType , typename RhsType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const LhsNested_& Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::lhs () const inline
Returns
the left hand side nested expression
 { return m_lhs; }
References Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::m_lhs.
Referenced by Eigen::internal::check_transpose_aliasing_run_time_selector< Scalar, DestIsTransposed, CwiseBinaryOp< BinOp, DerivedA, DerivedB > >::run(), and Eigen::internal::Assignment< DstXprType, CwiseBinaryOp< internal::scalar_product_op< ScalarBis, Scalar >, const CwiseNullaryOp< internal::scalar_constant_op< ScalarBis >, Plain >, const Product< Lhs, Rhs, DefaultProduct > >, AssignFunc, Dense2Dense >::run().
rhs()
template<typename BinaryOp , typename LhsType , typename RhsType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE const RhsNested_& Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::rhs () const inline
Returns
the right hand side nested expression
 { return m_rhs; }
References Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::m_rhs.
Referenced by Eigen::internal::check_transpose_aliasing_run_time_selector< Scalar, DestIsTransposed, CwiseBinaryOp< BinOp, DerivedA, DerivedB > >::run(), and Eigen::internal::Assignment< DstXprType, CwiseBinaryOp< internal::scalar_product_op< ScalarBis, Scalar >, const CwiseNullaryOp< internal::scalar_constant_op< ScalarBis >, Plain >, const Product< Lhs, Rhs, DefaultProduct > >, AssignFunc, Dense2Dense >::run().
rows()
template<typename BinaryOp , typename LhsType , typename RhsType > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE EIGEN_CONSTEXPR Index Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::rows () const inline
{
     // return the fixed size type if available to enable compile time optimizations
     return internal::traits<internal::remove_all_t<LhsNested>>::RowsAtCompileTime == Dynamic ? m_rhs.rows()
                                                                                              : m_lhs.rows();
   }
References Eigen::Dynamic, Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::m_lhs, and Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::m_rhs.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), Eigen::Reshaped< XprType, Rows, Cols, Order >::Reshaped(), Eigen::internal::visitor_evaluator< XprType >::rows(), Eigen::internal::redux_impl< Func, Evaluator, DefaultTraversal, NoUnrolling >::run(), Eigen::internal::redux_impl< Func, Evaluator, SliceVectorizedTraversal, Unrolling >::run(), Eigen::internal::redux_impl< Func, Evaluator, LinearVectorizedTraversal, CompleteUnrolling >::run(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
Member Data Documentation
m_functor
template<typename BinaryOp , typename LhsType , typename RhsType > const BinaryOp Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::m_functor protected
Referenced by Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::functor().
m_lhs
template<typename BinaryOp , typename LhsType , typename RhsType > LhsNested Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::m_lhs protected
Referenced by Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::cols(), Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::lhs(), and Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::rows().
m_rhs
template<typename BinaryOp , typename LhsType , typename RhsType > RhsNested Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::m_rhs protected
Referenced by Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::cols(), Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::rhs(), and Eigen::CwiseBinaryOp< BinaryOp, LhsType, RhsType >::rows().
The documentation for this class was generated from the following file:
CwiseBinaryOp.h