MercuryDPM: Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType, PermutationIndex > Struct Template Reference
Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType, PermutationIndex > Struct Template Reference
Dense linear problems and decompositions » Reference » QR_Module
Expression type for return value of FullPivHouseholderQR::matrixQ()
#include <FullPivHouseholderQR.h>
Public Types
typedef FullPivHouseholderQR< MatrixType, PermutationIndex >::IntDiagSizeVectorType IntDiagSizeVectorType
typedef internal::plain_diag_type< MatrixType >::type HCoeffsType
typedef Matrix< typename MatrixType::Scalar, 1, MatrixType::RowsAtCompileTime, RowMajor, 1, MatrixType::MaxRowsAtCompileTime > WorkVectorType
Public Types inherited from Eigen::ReturnByValue< FullPivHouseholderQRMatrixQReturnType< MatrixType, PermutationIndex > >
typedef internal::traits< FullPivHouseholderQRMatrixQReturnType< MatrixType, PermutationIndex > >::ReturnType ReturnType
typedef internal::dense_xpr_base< ReturnByValue >::type Base
Public Member Functions
FullPivHouseholderQRMatrixQReturnType (const MatrixType &qr, const HCoeffsType &hCoeffs, const IntDiagSizeVectorType &rowsTranspositions)
template<typename ResultType >
void evalTo (ResultType &result) const
template<typename ResultType >
void evalTo (ResultType &result, WorkVectorType &workspace) const
Index rows () const
Index cols () const
Public Member Functions inherited from Eigen::ReturnByValue< FullPivHouseholderQRMatrixQReturnType< MatrixType, PermutationIndex > >
EIGEN_DEVICE_FUNC void evalTo (Dest &dst) const
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index rows () const EIGEN_NOEXCEPT
EIGEN_DEVICE_FUNC EIGEN_CONSTEXPR Index cols () const EIGEN_NOEXCEPT
const Unusable & coeff (Index) const
const Unusable & coeff (Index, Index) const
Unusable & coeffRef (Index)
Unusable & coeffRef (Index, Index)
Protected Attributes
MatrixType::Nested m_qr
HCoeffsType::Nested m_hCoeffs
IntDiagSizeVectorType::Nested m_rowsTranspositions
Detailed Description
template<typename MatrixType, typename PermutationIndex>
struct Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType, PermutationIndex >
Expression type for return value of FullPivHouseholderQR::matrixQ()
Template Parameters
MatrixType type of underlying dense matrix
Member Typedef Documentation
HCoeffsType
template<typename MatrixType , typename PermutationIndex > typedef internal::plain_diag_type<MatrixType>::type Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType, PermutationIndex >::HCoeffsType
IntDiagSizeVectorType
template<typename MatrixType , typename PermutationIndex > typedef FullPivHouseholderQR<MatrixType, PermutationIndex>::IntDiagSizeVectorType Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType, PermutationIndex >::IntDiagSizeVectorType
WorkVectorType
template<typename MatrixType , typename PermutationIndex > typedef Matrix<typename MatrixType::Scalar, 1, MatrixType::RowsAtCompileTime, RowMajor, 1, MatrixType::MaxRowsAtCompileTime> Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType, PermutationIndex >::WorkVectorType
Constructor & Destructor Documentation
FullPivHouseholderQRMatrixQReturnType()
template<typename MatrixType , typename PermutationIndex > Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType, PermutationIndex >::FullPivHouseholderQRMatrixQReturnType (const MatrixType & qr, const HCoeffsType & hCoeffs, const IntDiagSizeVectorType & rowsTranspositions) inline
       : m_qr(qr), m_hCoeffs(hCoeffs), m_rowsTranspositions(rowsTranspositions) {}
Member Function Documentation
cols()
template<typename MatrixType , typename PermutationIndex > Index Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType, PermutationIndex >::cols () const inline
 { return m_qr.rows(); }
References Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_qr.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
evalTo() [1/2]
template<typename MatrixType , typename PermutationIndex > template<typename ResultType > void Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType, PermutationIndex >::evalTo (ResultType & result) const inline
{
     const Index rows = m_qr.rows();
     WorkVectorType workspace(rows);
     evalTo(result, workspace);
   }
References Eigen::EigenBase< Derived >::evalTo(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_qr, and Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::rows().
evalTo() [2/2]
template<typename MatrixType , typename PermutationIndex > template<typename ResultType > void Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType, PermutationIndex >::evalTo (ResultType & result, WorkVectorType & workspace) const inline
{
     using numext::conj;
     // compute the product H'_0 H'_1 ... H'_n-1,
     // where H_k is the k-th Householder transformation I - h_k v_k v_k'
     // and v_k is the k-th Householder vector [1,m_qr(k+1,k), m_qr(k+2,k), ...]
     const Index rows = m_qr.rows();
     const Index cols = m_qr.cols();
     const Index size = (std::min)(rows, cols);
     workspace.resize(rows);
     result.setIdentity(rows, rows);
     for (Index k = size - 1; k >= 0; k--) {
       result.block(k, k, rows - k, rows - k)
           .applyHouseholderOnTheLeft(m_qr.col(k).tail(rows - k - 1), conj(m_hCoeffs.coeff(k)), &workspace.coeffRef(k));
       result.row(k).swap(result.row(m_rowsTranspositions.coeff(k)));
     }
   }
References Eigen::Matrix< Scalar_, Rows_, Cols_, Options_, MaxRows_, MaxCols_ >::coeffRef(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::cols(), conj(), Eigen::conj(), k, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_hCoeffs, Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_qr, min, Eigen::PlainObjectBase< Derived >::resize(), Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::rows(), and Eigen::EigenBase< Derived >::size().
rows()
template<typename MatrixType , typename PermutationIndex > Index Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType, PermutationIndex >::rows () const inline
 { return m_qr.rows(); }
References Eigen::FullPivHouseholderQR< MatrixType_, PermutationIndex_ >::m_qr.
Referenced by gdb.printers._MatrixEntryIterator::__next__(), gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), and gdb.printers.EigenSparseMatrixPrinter::to_string().
Member Data Documentation
m_hCoeffs
template<typename MatrixType , typename PermutationIndex > HCoeffsType::Nested Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType, PermutationIndex >::m_hCoeffs protected
m_qr
template<typename MatrixType , typename PermutationIndex > MatrixType::Nested Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType, PermutationIndex >::m_qr protected
m_rowsTranspositions
template<typename MatrixType , typename PermutationIndex > IntDiagSizeVectorType::Nested Eigen::internal::FullPivHouseholderQRMatrixQReturnType< MatrixType, PermutationIndex >::m_rowsTranspositions protected
The documentation for this struct was generated from the following file:
FullPivHouseholderQR.h