MercuryDPM: ChargedBondedSpecies Class Reference
ChargedBondedSpecies Class Reference
ChargedBondedSpecies contains the parameters used to describe a linear reversible short-range force.
#include <ChargedBondedSpecies.h>
Public Types
typedef ChargedBondedInteraction InteractionType
The correct Interaction type for this AdhesiveForceSpecies.
Public Member Functions
ChargedBondedSpecies ()
The default constructor.
ChargedBondedSpecies (const ChargedBondedSpecies &s)
The default constructor.
~ChargedBondedSpecies ()=default
The default constructor.
void read (std::istream &is)
Reads the species properties from an input stream.
void write (std::ostream &os) const
Writes the species properties to an output stream.
std::string getBaseName () const
Used in Species::getName to obtain a unique name for each Species.
void mix (ChargedBondedSpecies *S, ChargedBondedSpecies *T)
creates default values for mixed species
void setInteractionDistance ()
returns the largest separation distance at which adhesive short-range forces can occur.
void setAdhesionStiffness (Mdouble new_k0)
Allows the spring constant to be changed.
Mdouble getAdhesionStiffness () const
Allows the spring constant to be accessed.
void setAdhesionForceMax (Mdouble new_f0)
Allows the spring constant to be changed.
Mdouble getAdhesionForceMax () const
Allows the spring constant to be accessed.
int getCharge () const
void setCharge (int newCharge)
void setBondForceMax (Mdouble new_f0)
Allows the spring constant for the BOND to be changed (Do not confuse with the charged interaction strength!)
Mdouble getBondForceMax () const
Allows the maximal force for 'bonding' particles together to be accessed.
void setBondDissipation (Mdouble disp)
Allows the additional dissipation used to damp oscillations between bondd particles to be changed.
Mdouble getBondDissipation () const
Allows the additional dissipation used to damp oscillations between bondd particles to be accessed.
Mdouble getVanDerWaalsStiffness () const
Mdouble getVanDerWaalsForceMax () const
void setVanDerWaalsStiffness (Mdouble)
void setVanDerWaalsForceMax (Mdouble)
Public Member Functions inherited from BaseForce
BaseSpecies * getBaseSpecies () const
void setBaseSpecies (BaseSpecies *baseSpecies)
Private Attributes
Mdouble adhesionStiffness_
stiffness of linear adhesion force
Mdouble adhesionForceMax_
adhesion force at zero overlap
int charge_
Mdouble bondForceMax_
The maximal force which acts to bind together particles which are "bondd" into a single body.
Mdouble bondDissipation_
dissipation in bond
Mdouble vanDerWaalsForceMax_
Mdouble vanDerWaalsStiffness_
Detailed Description
ChargedBondedSpecies contains the parameters used to describe a linear reversible short-range force.
See ChargedBondedInteraction::computeForce for a description of the force law.
Member Typedef Documentation
InteractionType
typedef ChargedBondedInteraction ChargedBondedSpecies::InteractionType
The correct Interaction type for this AdhesiveForceSpecies.
Constructor & Destructor Documentation
ChargedBondedSpecies() [1/2]
ChargedBondedSpecies::ChargedBondedSpecies ()
The default constructor.
Default constructor for charged species. Sets default values for all relevant parameters. Note: if the stiffness of particles is left as zero, no force will be felt during interaction with other particles
Parameters
[in] s the species that is copied
 {
     //setting adhesion values initially to zero such that, by default, particles do not experience
     //long range forces
     adhesionForceMax_ = 0;
     adhesionStiffness_ = 1;
     //similarly, setting bond properties to zero such that, by default, particles cannot be 'bondd'...
     bondForceMax_ = 0;
     //...and do not impart any excess dissipation!
     bondDissipation_ = 0;
     //Setting also parameters corresponding to the van der Waals force to zero by default
     vanDerWaalsForceMax_ = 0;
     vanDerWaalsStiffness_ = 1;
     charge_ = 0;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"ChargedBondedSpecies::ChargedBondedSpecies() finished"<<std::endl;
 #endif
 }
References adhesionForceMax_, adhesionStiffness_, bondDissipation_, bondForceMax_, charge_, vanDerWaalsForceMax_, and vanDerWaalsStiffness_.
ChargedBondedSpecies() [2/2]
ChargedBondedSpecies::ChargedBondedSpecies (const ChargedBondedSpecies & s)
The default constructor.
Copy constructor for charged species
Parameters
[in] s the species that is copied
 {
     adhesionForceMax_ = s.adhesionForceMax_;
     adhesionStiffness_ = s.adhesionStiffness_;
     bondForceMax_ = s.bondForceMax_;
     bondDissipation_ = s.bondDissipation_;
     vanDerWaalsForceMax_ = s.vanDerWaalsForceMax_;
     vanDerWaalsStiffness_ = s.vanDerWaalsStiffness_;
     charge_ = s.charge_;
 #ifdef DEBUG_CONSTRUCTOR
     std::cout<<"ChargedBondedSpecies::ChargedBondedSpecies(const ChargedBondedSpecies &p) finished"<<std::endl;
 #endif
 }
References adhesionForceMax_, adhesionStiffness_, bondDissipation_, bondForceMax_, charge_, s, vanDerWaalsForceMax_, and vanDerWaalsStiffness_.
~ChargedBondedSpecies()
ChargedBondedSpecies::~ChargedBondedSpecies () default
The default constructor.
Member Function Documentation
getAdhesionForceMax()
Mdouble ChargedBondedSpecies::getAdhesionForceMax () const
Allows the spring constant to be accessed.
 {
     return adhesionForceMax_;
 }
References adhesionForceMax_.
Referenced by ChargedBondedInteraction::computeAdhesionForce(), and ChargedBondedInteraction::getElasticEnergy().
getAdhesionStiffness()
Mdouble ChargedBondedSpecies::getAdhesionStiffness () const
Allows the spring constant to be accessed.
 {
     return adhesionStiffness_;
 }
References adhesionStiffness_.
Referenced by ChargedBondedInteraction::computeAdhesionForce(), and ChargedBondedInteraction::getElasticEnergy().
getBaseName()
std::string ChargedBondedSpecies::getBaseName () const
Used in Species::getName to obtain a unique name for each Species.
Returns the name of thebcurrent species
Returns
a string containing the name of the species (minus the word "Species")
 {
     return "ChargedBonded";
 }
getBondDissipation()
Mdouble ChargedBondedSpecies::getBondDissipation () const
Allows the additional dissipation used to damp oscillations between bondd particles to be accessed.
Allows the value of the dissipation between bondd particles to be accessed. This can be used to eliminate oscillations which may arise due to the forces holding the particles together competing with the usual forces which act to push particles in contact apart!
 {
     return bondDissipation_;
 }
References bondDissipation_.
Referenced by ChargedBondedInteraction::computeAdhesionForce().
getBondForceMax()
Mdouble ChargedBondedSpecies::getBondForceMax () const
Allows the maximal force for 'bonding' particles together to be accessed.
Allows the the maximal force of the 'bond' used to bond particles together to be accessed.
 {
     return bondForceMax_;
 }
References bondForceMax_.
Referenced by ChargedBondedInteraction::computeAdhesionForce(), and ChargedBondedInteraction::getElasticEnergy().
getCharge()
int ChargedBondedSpecies::getCharge () const
 {
     return charge_;
 }
References charge_.
getVanDerWaalsForceMax()
Mdouble ChargedBondedSpecies::getVanDerWaalsForceMax () const
 {
     return vanDerWaalsForceMax_;
 }
References vanDerWaalsForceMax_.
Referenced by ChargedBondedInteraction::computeAdhesionForce(), and ChargedBondedInteraction::getElasticEnergy().
getVanDerWaalsStiffness()
Mdouble ChargedBondedSpecies::getVanDerWaalsStiffness () const
 {
     return vanDerWaalsStiffness_;
 }
References vanDerWaalsStiffness_.
Referenced by ChargedBondedInteraction::computeAdhesionForce(), and ChargedBondedInteraction::getElasticEnergy().
mix()
void ChargedBondedSpecies::mix (ChargedBondedSpecies * S, ChargedBondedSpecies * T)
creates default values for mixed species
Calling this function acts to assign values of maximum adhesion force and stiffness for mixed species interactions. For all parameters we assume that the harmonic mean of the parameters of the original two species is a sensible default.
Parameters
[in] S,T the two species whose properties are mixed to create the new species
 {
     //'mixing' properties relating to the charged force interactions between particles
     setAdhesionForceMax(BaseSpecies::average(S->getAdhesionForceMax(), T->getAdhesionForceMax()));
     setAdhesionStiffness(BaseSpecies::average(S->getAdhesionStiffness(), T->getAdhesionStiffness()));
     //ensuring that, in addition, bond properties are also 'mixed'
     bondForceMax_ = BaseSpecies::average(S->getBondForceMax(), T->getBondForceMax());
     bondDissipation_ = BaseSpecies::average(S->getBondDissipation(), T->getBondDissipation());
     //and that the van der Waals force also is computed correctly
     vanDerWaalsForceMax_ = BaseSpecies::average(S->getVanDerWaalsForceMax(), T->getVanDerWaalsForceMax());
     vanDerWaalsStiffness_ = BaseSpecies::average(S->getVanDerWaalsStiffness(), T->getVanDerWaalsStiffness());
     charge_ = 0; //note mixedSpecies dont need charge, it's a particle property.
 }
References BaseSpecies::average(), bondDissipation_, bondForceMax_, charge_, oomph::QuadTreeNames::S, setAdhesionForceMax(), setAdhesionStiffness(), vanDerWaalsForceMax_, and vanDerWaalsStiffness_.
read()
void ChargedBondedSpecies::read (std::istream & is)
Reads the species properties from an input stream.
Parameters
[in] is input stream (typically the restart file)
 {
     std::string dummy;
     is >> dummy >> adhesionForceMax_;
     is >> dummy >> adhesionStiffness_;
     is >> dummy >> charge_;
     is >> dummy >> bondForceMax_;
     is >> dummy >> bondDissipation_;
     is >> dummy >> vanDerWaalsForceMax_;
     is >> dummy >> vanDerWaalsStiffness_;
 }
References adhesionForceMax_, adhesionStiffness_, bondDissipation_, bondForceMax_, charge_, oomph::Global_string_for_annotation::string(), vanDerWaalsForceMax_, and vanDerWaalsStiffness_.
setAdhesionForceMax()
void ChargedBondedSpecies::setAdhesionForceMax (Mdouble new_f0)
Allows the spring constant to be changed.
 {
     if (new_f0 >= 0) {
         adhesionForceMax_ = new_f0;
         setInteractionDistance();
     } else {
         logger(ERROR, "Error in setAdhesionForceMax");
     }
 }
References adhesionForceMax_, ERROR, logger, and setInteractionDistance().
Referenced by mix().
setAdhesionStiffness()
void ChargedBondedSpecies::setAdhesionStiffness (Mdouble new_k0)
Allows the spring constant to be changed.
 {
     if (new_k0 >= 0) {
         adhesionStiffness_ = new_k0;
         setInteractionDistance();
     } else {
         logger(ERROR, "Error in setAdhesionStiffness");
     }
 }
References adhesionStiffness_, ERROR, logger, and setInteractionDistance().
Referenced by mix().
setBondDissipation()
void ChargedBondedSpecies::setBondDissipation (Mdouble disp)
Allows the additional dissipation used to damp oscillations between bondd particles to be changed.
Allows the value of the dissipation between bondd particles to be changed. This can be used to eliminate oscillations which may arise due to the forces holding the particles together competing with the usual forces which act to push particles in contact apart!
 {
     if (disp >= 0)
         bondDissipation_ = disp;
     else
     {
         logger(ERROR, "Error in setAdhesionDissipation");
     }
 }
References bondDissipation_, ERROR, and logger.
setBondForceMax()
void ChargedBondedSpecies::setBondForceMax (Mdouble new_f0)
Allows the spring constant for the BOND to be changed (Do not confuse with the charged interaction strength!)
Allows the spring constant to be changed This means that we can alter the strength with which particles are "bondd" together and, thus, the mean distance by which bondd particles overlap by. As such, we can alter the geometry of multi-particle structures formed.
 {
     if (new_f0 >= 0)
     {
         bondForceMax_ = new_f0;
     }
     else
     {
         logger(ERROR, "Error in setBondForceMax");
     }
 }
References bondForceMax_, ERROR, and logger.
setCharge()
void ChargedBondedSpecies::setCharge (int newCharge)
 {
     //making sure that the user can only enter 1 (positive charge) -1 (negative charge)
     //or zero (no charge)
     if (newCharge == 0 || newCharge == 1 || newCharge == -1)
         charge_ = newCharge;
     else
     {
         logger(ERROR, "Error in setCharge - charge must be +1, -1 or zero");
     }
 }
References charge_, ERROR, and logger.
setInteractionDistance()
void ChargedBondedSpecies::setInteractionDistance () virtual
returns the largest separation distance at which adhesive short-range forces can occur.
Returns
the maximum separation distance below which adhesive forces can occur (needed for contact detection)
Reimplemented from BaseAdhesiveForce.
 {
     logger.assert_debug(adhesionStiffness_ != 0.0,"ChargedBondedSpecies::getInteractionDistance(): adhesionStiffness cannot be zero");
     getBaseSpecies()->setInteractionDistance(adhesionForceMax_ / adhesionStiffness_);
 }
References adhesionForceMax_, adhesionStiffness_, BaseForce::getBaseSpecies(), logger, and BaseSpecies::setInteractionDistance().
Referenced by setAdhesionForceMax(), and setAdhesionStiffness().
setVanDerWaalsForceMax()
void ChargedBondedSpecies::setVanDerWaalsForceMax (Mdouble fMax)
 {
     if (fMax < 0)
     {
         logger(ERROR, "Error in setVanDerWaalsForceMax.");
     }
     else
     {
         vanDerWaalsForceMax_ = fMax;
     }
 }
References ERROR, logger, and vanDerWaalsForceMax_.
setVanDerWaalsStiffness()
void ChargedBondedSpecies::setVanDerWaalsStiffness (Mdouble stiffness)
 {
     vanDerWaalsStiffness_ = stiffness;
 }
References vanDerWaalsStiffness_.
write()
void ChargedBondedSpecies::write (std::ostream & os) const
Writes the species properties to an output stream.
Parameters
[out] os output stream (typically the restart file)
 {
     os << " adhesionForceMax " << adhesionForceMax_;
     os << " adhesionStiffness " << adhesionStiffness_;
     os << " charge " << charge_;
     os << " bondForceMax " << bondForceMax_;
     os << " bondDissipation " << bondDissipation_;
     os << " vanDerWaalsForceMax " << vanDerWaalsForceMax_;
     os << " vanDerWaalsStiffness " << vanDerWaalsStiffness_;
 }
References adhesionForceMax_, adhesionStiffness_, bondDissipation_, bondForceMax_, charge_, vanDerWaalsForceMax_, and vanDerWaalsStiffness_.
Member Data Documentation
adhesionForceMax_
Mdouble ChargedBondedSpecies::adhesionForceMax_ private
adhesion force at zero overlap
Referenced by ChargedBondedSpecies(), getAdhesionForceMax(), read(), setAdhesionForceMax(), setInteractionDistance(), and write().
adhesionStiffness_
Mdouble ChargedBondedSpecies::adhesionStiffness_ private
stiffness of linear adhesion force
Referenced by ChargedBondedSpecies(), getAdhesionStiffness(), read(), setAdhesionStiffness(), setInteractionDistance(), and write().
bondDissipation_
Mdouble ChargedBondedSpecies::bondDissipation_ private
dissipation in bond
the additional dissipation used to 'damp' oscillations between bondd particles
Referenced by ChargedBondedSpecies(), getBondDissipation(), mix(), read(), setBondDissipation(), and write().
bondForceMax_
Mdouble ChargedBondedSpecies::bondForceMax_ private
The maximal force which acts to bind together particles which are "bondd" into a single body.
Referenced by ChargedBondedSpecies(), getBondForceMax(), mix(), read(), setBondForceMax(), and write().
charge_
int ChargedBondedSpecies::charge_ private
Referenced by ChargedBondedSpecies(), getCharge(), mix(), read(), setCharge(), and write().
vanDerWaalsForceMax_
Mdouble ChargedBondedSpecies::vanDerWaalsForceMax_ private
Referenced by ChargedBondedSpecies(), getVanDerWaalsForceMax(), mix(), read(), setVanDerWaalsForceMax(), and write().
vanDerWaalsStiffness_
Mdouble ChargedBondedSpecies::vanDerWaalsStiffness_ private
Referenced by ChargedBondedSpecies(), getVanDerWaalsStiffness(), mix(), read(), setVanDerWaalsStiffness(), and write().
The documentation for this class was generated from the following files:
ChargedBondedSpecies.h
ChargedBondedSpecies.cc