MercuryDPM: Smoother_Factory_Function_Helper Namespace Reference
Smoother_Factory_Function_Helper Namespace Reference
Returns a pointer to a smoother of the appropriate type.
Functions
HelmholtzSmoother * set_pre_smoother ()
HelmholtzSmoother * set_post_smoother ()
Smoother * set_smoother ()
Variables
double Omega =0.4
The value of the damping factor for the damped Jacobi smoother.
Detailed Description
Returns a pointer to a smoother of the appropriate type.
////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////// /////////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Function Documentation
set_post_smoother()
Smoother * Smoother_Factory_Function_Helper::set_post_smoother ()
Returns a pointer to a Smoother object which is to be used as the post-smoother
  {
   // Create a new DampedJacobi object
   return new ComplexDampedJacobi<CRDoubleMatrix>(Omega);
  }
References Omega.
Referenced by PMLStructuredCubicHelmholtz< ELEMENT >::set_gmres_multigrid_solver(), and PMLHelmholtzMGProblem< ELEMENT >::set_gmres_multigrid_solver().
set_pre_smoother()
Smoother * Smoother_Factory_Function_Helper::set_pre_smoother ()
Returns a pointer to a Smoother object which is to be used as the pre-smoother
  {
   // Create a new DampedJacobi object
   return new ComplexDampedJacobi<CRDoubleMatrix>(Omega);
  }
References Omega.
Referenced by PMLStructuredCubicHelmholtz< ELEMENT >::set_gmres_multigrid_solver(), and PMLHelmholtzMGProblem< ELEMENT >::set_gmres_multigrid_solver().
set_smoother()
Smoother * Smoother_Factory_Function_Helper::set_smoother ()
Returns a pointer to a Gauss-Seidel Smoother object which can be used as a pre- or post-smoother
Returns a pointer to a Gauss-Seidel Smoother object which is to be used as a pre- or post-smoother
  {
   // Create a new GS object
   return new GS<CRDoubleMatrix>;
  } // End of set_pre_smoother
Referenced by FluxPoissonMGProblem< ELEMENT, MESH >::set_multigrid_solver(), and UnitCubePoissonMGProblem< ELEMENT, MESH >::set_multigrid_solver().
Variable Documentation
Omega
double Smoother_Factory_Function_Helper::Omega =0.4
The value of the damping factor for the damped Jacobi smoother.
Referenced by main(), set_post_smoother(), and set_pre_smoother().