MercuryDPM: free_surface_rotation.cc File Reference
free_surface_rotation.cc File Reference
#include "generic.h"
#include "navier_stokes.h"
#include "fluid_interface.h"
#include "meshes/quarter_tube_mesh.h"
Classes
class AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >
class FreeSurfaceRotationProblem< ELEMENT >
Entry flow problem in quarter tube domain.
Namespaces
Global_Physical_Variables
Global variables.
WallFunction
Functions
void WallFunction::normal (const Vector< double > &x, Vector< double > &normal)
int main (int argc, char *argv[])
Variables
double Global_Physical_Variables::Omega = 0.0
Rotation rate.
Vector< double > Global_Physical_Variables::G (3) = 1.0
Direction of gravity.
Function Documentation
main()
int main (int argc , char * argv[])
///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////// Driver for 3D entry flow into a quarter tube. If there are any command line arguments, we regard this as a validation run and perform only a single adaptation
 {
  // Store command line arguments
  CommandLineArgs::setup(argc,argv);
  // Allow (up to) five rounds of fully automatic adapation in response to
  //-----------------------------------------------------------------------
  // error estimate
  //---------------
  //unsigned max_adapt;
  double max_error_target,min_error_target;
  using namespace Global_Physical_Variables;
  G[0] = 0.0; G[1] = 0.0; G[2] = -1.0;
  // Set max number of adaptations in black-box Newton solver and
  // error targets for adaptation
  if (CommandLineArgs::Argc==1)
   {
    // Up to five adaptations
    //max_adapt=5;
    // Error targets for adaptive refinement
    max_error_target=0.005;
    min_error_target=0.0005;
   }
  // Validation run: Only one adaptation. Relax error targets
  // to ensure that not all elements are refined so we're getting
  // some hanging nodes.
  else
   {
    // Validation run: Just one round of adaptation
    //max_adapt=1;
    // Error targets for adaptive refinement
    max_error_target=0.02;
    min_error_target=0.002;
   }
  // end max_adapt setup
  // Set up doc info
  DocInfo doc_info;
  const double pi = MathematicalConstants::Pi;
  // Do Taylor-Hood elements
  //------------------------
  {
   // Set output directory
   doc_info.set_directory("RESLT_TH");
   // Step number
   doc_info.number()=0;
   // Build problem
   FreeSurfaceRotationProblem<SpineElement<RefineableQTaylorHoodElement<3> > >
    problem(doc_info,min_error_target,max_error_target);
   cout << " Doing Taylor-Hood elements " << std::endl;
   // Doc solution after solving
   problem.doc_solution();
   // Solve the problem  (DO NOT ADAPT)
   problem.newton_solve();
   for(unsigned i=0;i<5;i++)
    {
     Angle -= 0.05*pi;
     problem.newton_solve();
    }
  }
  // Do Crouzeix-Raviart elements
  //-----------------------------
  {
   // Set output directory
   doc_info.set_directory("RESLT_CR");
   // Step number
   doc_info.number()=0;
   // Build problem
   FreeSurfaceRotationProblem<
    SpineElement<RefineableQCrouzeixRaviartElement<3> > >
    problem(doc_info,min_error_target,max_error_target);
   cout << " Doing Crouzeix-Raviart elements " << std::endl;
   // Solve the problem  DO NOT ADAPT
   problem.newton_solve();
   }
 } // end_of_main
References Global_Physical_Variables::Angle, oomph::CommandLineArgs::Argc, G, i, oomph::DocInfo::number(), constants::pi, BiharmonicTestFunctions2::Pi, problem, oomph::DocInfo::set_directory(), and Flag_definition::setup().