MercuryDPM: rapidjson::GenericWriteStream Class Reference
rapidjson::GenericWriteStream Class Reference
Wrapper of std::ostream for output.
#include <genericstream.h>
Public Types
typedef char Ch
Character type. Only support char.
Public Member Functions
GenericWriteStream (std::ostream &os)
Constructor.
void Put (char c)
void PutN (char c, size_t n)
void Flush ()
size_t Tell () const
char Peek () const
char Take ()
char * PutBegin ()
size_t PutEnd (char *)
Private Attributes
std::ostream & os_
Detailed Description
Wrapper of std::ostream for output.
Member Typedef Documentation
Ch
typedef char rapidjson::GenericWriteStream::Ch
Character type. Only support char.
Constructor & Destructor Documentation
GenericWriteStream()
rapidjson::GenericWriteStream::GenericWriteStream (std::ostream & os) inline
Constructor.
Parameters
os Output stream.
                                          : os_(os) {
       }
Member Function Documentation
Flush()
void rapidjson::GenericWriteStream::Flush () inline
                    {
         os_.flush();
       }
References os_.
Peek()
char rapidjson::GenericWriteStream::Peek () const inline
 { RAPIDJSON_ASSERT(false); }
References RAPIDJSON_ASSERT.
Put()
void rapidjson::GenericWriteStream::Put (char c) inline
{
         os_.put(c);
       }
References calibrate::c, and os_.
Referenced by PutN().
PutBegin()
char* rapidjson::GenericWriteStream::PutBegin () inline
 { RAPIDJSON_ASSERT(false); return 0; }
References RAPIDJSON_ASSERT.
PutEnd()
size_t rapidjson::GenericWriteStream::PutEnd (char *) inline
 { RAPIDJSON_ASSERT(false); return 0; }
References RAPIDJSON_ASSERT.
PutN()
void rapidjson::GenericWriteStream::PutN (char c, size_t n) inline
{
         for (size_t i = 0; i < n; ++i) {
           Put(c);
         }
       }
References calibrate::c, i, n, and Put().
Referenced by rapidjson::PutN().
Take()
char rapidjson::GenericWriteStream::Take () inline
 { RAPIDJSON_ASSERT(false); }
References RAPIDJSON_ASSERT.
Tell()
size_t rapidjson::GenericWriteStream::Tell () const inline
{
         return (int)os_.tellp();
       }
References os_.
Member Data Documentation
os_
std::ostream& rapidjson::GenericWriteStream::os_ private
Referenced by Flush(), Put(), and Tell().
The documentation for this class was generated from the following file:
genericstream.h