MercuryDPM: Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device > Struct Template Reference
Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device > Struct Template Reference
#include <TensorEvalTo.h>
Public Types
enum {
IsAligned = TensorEvaluator<ArgType, Device>::IsAligned , PacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess , BlockAccess = true , PreferBlockAccess = false ,
CoordAccess = false , RawAccess = true
}
typedef TensorEvalToOp< ArgType, MakePointer_ > XprType
typedef ArgType::Scalar Scalar
typedef TensorEvaluator< ArgType, Device >::Dimensions Dimensions
typedef XprType::Index Index
typedef std::remove_const_t< typename XprType::CoeffReturnType > CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef Eigen::internal::traits< XprType >::PointerType TensorPointerType
typedef StorageMemory< CoeffReturnType, Device > Storage
typedef Storage::Type EvaluatorPointerType
typedef internal::TensorBlockDescriptor< NumDims, Index > TensorBlockDesc
typedef internal::TensorBlockScratchAllocator< Device > TensorBlockScratch
typedef TensorEvaluator< const ArgType, Device >::TensorBlock ArgTensorBlock
typedef internal::TensorBlockAssignment< CoeffReturnType, NumDims, typename ArgTensorBlock::XprType, Index > TensorBlockAssignment
Public Member Functions
EIGEN_STRONG_INLINE TensorEvaluator (const XprType &op, const Device &device)
EIGEN_STRONG_INLINE ~TensorEvaluator ()
EIGEN_DEVICE_FUNC const Dimensions & dimensions () const
EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (EvaluatorPointerType scalar)
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void evalScalar (Index i) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void evalPacket (Index i) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::TensorBlockResourceRequirements getResourceRequirements () const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void evalBlock (TensorBlockDesc &desc, TensorBlockScratch &scratch)
EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType coeff (Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType packet (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
EIGEN_DEVICE_FUNC EvaluatorPointerType data () const
ArgType expression () const
Static Public Attributes
static constexpr int PacketSize = PacketType<CoeffReturnType, Device>::size
static constexpr int Layout = TensorEvaluator<ArgType, Device>::Layout
static constexpr int NumDims = internal::traits<ArgType>::NumDimensions
Private Attributes
TensorEvaluator< ArgType, Device > m_impl
EvaluatorPointerType m_buffer
const ArgType m_expression
Member Typedef Documentation
ArgTensorBlock
template<typename ArgType , typename Device , template< class > class MakePointer_> typedef TensorEvaluator<const ArgType, Device>::TensorBlock Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >::ArgTensorBlock
CoeffReturnType
template<typename ArgType , typename Device , template< class > class MakePointer_> typedef std::remove_const_t<typename XprType::CoeffReturnType> Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >::CoeffReturnType
Dimensions
template<typename ArgType , typename Device , template< class > class MakePointer_> typedef TensorEvaluator<ArgType, Device>::Dimensions Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >::Dimensions
EvaluatorPointerType
template<typename ArgType , typename Device , template< class > class MakePointer_> typedef Storage::Type Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >::EvaluatorPointerType
Index
template<typename ArgType , typename Device , template< class > class MakePointer_> typedef XprType::Index Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >::Index
PacketReturnType
template<typename ArgType , typename Device , template< class > class MakePointer_> typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >::PacketReturnType
Scalar
template<typename ArgType , typename Device , template< class > class MakePointer_> typedef ArgType::Scalar Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >::Scalar
Storage
template<typename ArgType , typename Device , template< class > class MakePointer_> typedef StorageMemory<CoeffReturnType, Device> Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >::Storage
TensorBlockAssignment
template<typename ArgType , typename Device , template< class > class MakePointer_> typedef internal::TensorBlockAssignment<CoeffReturnType, NumDims, typename ArgTensorBlock::XprType, Index> Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >::TensorBlockAssignment
TensorBlockDesc
template<typename ArgType , typename Device , template< class > class MakePointer_> typedef internal::TensorBlockDescriptor<NumDims, Index> Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >::TensorBlockDesc
TensorBlockScratch
template<typename ArgType , typename Device , template< class > class MakePointer_> typedef internal::TensorBlockScratchAllocator<Device> Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >::TensorBlockScratch
TensorPointerType
template<typename ArgType , typename Device , template< class > class MakePointer_> typedef Eigen::internal::traits<XprType>::PointerType Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >::TensorPointerType
XprType
template<typename ArgType , typename Device , template< class > class MakePointer_> typedef TensorEvalToOp<ArgType, MakePointer_> Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >::XprType
Member Enumeration Documentation
anonymous enum
template<typename ArgType , typename Device , template< class > class MakePointer_> anonymous enum
Enumerator
IsAligned
PacketAccess
BlockAccess
PreferBlockAccess
CoordAccess
RawAccess
        {
     IsAligned = TensorEvaluator<ArgType, Device>::IsAligned,
     PacketAccess = TensorEvaluator<ArgType, Device>::PacketAccess,
     BlockAccess = true,
     PreferBlockAccess = false,
     CoordAccess = false,  // to be implemented
     RawAccess = true
   };
Constructor & Destructor Documentation
TensorEvaluator()
template<typename ArgType , typename Device , template< class > class MakePointer_> EIGEN_STRONG_INLINE Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >::TensorEvaluator (const XprType & op, const Device & device) inline
       : m_impl(op.expression(), device), m_buffer(device.get(op.buffer())), m_expression(op.expression()) {}
~TensorEvaluator()
template<typename ArgType , typename Device , template< class > class MakePointer_> EIGEN_STRONG_INLINE Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >::~TensorEvaluator () inline
 {}
Member Function Documentation
cleanup()
template<typename ArgType , typename Device , template< class > class MakePointer_> EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >::cleanup () inline
 { m_impl.cleanup(); }
Referenced by framework.Frame::__init__().
coeff()
template<typename ArgType , typename Device , template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE CoeffReturnType Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >::coeff (Index index) const inline
 { return m_buffer[index]; }
costPerCoeff()
template<typename ArgType , typename Device , template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >::costPerCoeff (bool vectorized) const inline
{
     // We assume that evalPacket or evalScalar is called to perform the
     // assignment and account for the cost of the write here.
     return m_impl.costPerCoeff(vectorized) + TensorOpCost(0, sizeof(CoeffReturnType), 0, vectorized, PacketSize);
   }
References Eigen::TensorEvaluator< Derived, Device >::PacketSize.
data()
template<typename ArgType , typename Device , template< class > class MakePointer_> EIGEN_DEVICE_FUNC EvaluatorPointerType Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >::data () const inline
 { return m_buffer; }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
dimensions()
template<typename ArgType , typename Device , template< class > class MakePointer_> EIGEN_DEVICE_FUNC const Dimensions& Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >::dimensions () const inline
 { return m_impl.dimensions(); }
evalBlock()
template<typename ArgType , typename Device , template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >::evalBlock (TensorBlockDesc & desc, TensorBlockScratch & scratch) inline
{
     // Add `m_buffer` as destination buffer to the block descriptor.
     desc.template AddDestinationBuffer<Layout>(
         /*dst_base=*/m_buffer + desc.offset(),
         /*dst_strides=*/internal::strides<Layout>(m_impl.dimensions()));
     ArgTensorBlock block = m_impl.block(desc, scratch, /*root_of_expr_ast=*/true);
     // If block was evaluated into a destination buffer, there is no need to do
     // an assignment.
     if (block.kind() != internal::TensorBlockKind::kMaterializedInOutput) {
       TensorBlockAssignment::Run(
           TensorBlockAssignment::target(desc.dimensions(), internal::strides<Layout>(m_impl.dimensions()), m_buffer,
                                         desc.offset()),
           block.expr());
     }
     block.cleanup();
   }
References Eigen::TensorEvaluator< Derived, Device >::block(), Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::cleanup(), Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::dimensions(), Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::expr(), Eigen::internal::TensorMaterializedBlock< Scalar, NumDims, Layout, IndexType >::kind(), Eigen::internal::kMaterializedInOutput, and Eigen::internal::TensorBlockDescriptor< NumDims, IndexType >::offset().
evalPacket()
template<typename ArgType , typename Device , template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >::evalPacket (Index i) const inline
{
     internal::pstoret<CoeffReturnType, PacketReturnType, Aligned>(
         m_buffer + i, m_impl.template packet < TensorEvaluator<ArgType, Device>::IsAligned ? Aligned : Unaligned > (i));
   }
References Eigen::Aligned, i, Eigen::TensorEvaluator< Derived, Device >::packet(), and Eigen::Unaligned.
evalScalar()
template<typename ArgType , typename Device , template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >::evalScalar (Index i) const inline
 { m_buffer[i] = m_impl.coeff(i); }
References i.
evalSubExprsIfNeeded()
template<typename ArgType , typename Device , template< class > class MakePointer_> EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >::evalSubExprsIfNeeded (EvaluatorPointerType scalar) inline
{
     EIGEN_UNUSED_VARIABLE(scalar);
     eigen_assert(scalar == NULL);
     return m_impl.evalSubExprsIfNeeded(m_buffer);
   }
References eigen_assert, and EIGEN_UNUSED_VARIABLE.
expression()
template<typename ArgType , typename Device , template< class > class MakePointer_> ArgType Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >::expression () const inline
 { return m_expression; }
getResourceRequirements()
template<typename ArgType , typename Device , template< class > class MakePointer_> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE internal::TensorBlockResourceRequirements Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >::getResourceRequirements () const inline
{
     return m_impl.getResourceRequirements();
   }
packet()
template<typename ArgType , typename Device , template< class > class MakePointer_> template<int LoadMode> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >::packet (Index index) const inline
{
     return internal::ploadt<PacketReturnType, LoadMode>(m_buffer + index);
   }
Member Data Documentation
Layout
template<typename ArgType , typename Device , template< class > class MakePointer_> constexpr int Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >::Layout = TensorEvaluator<ArgType, Device>::Layout static constexpr
m_buffer
template<typename ArgType , typename Device , template< class > class MakePointer_> EvaluatorPointerType Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >::m_buffer private
m_expression
template<typename ArgType , typename Device , template< class > class MakePointer_> const ArgType Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >::m_expression private
m_impl
template<typename ArgType , typename Device , template< class > class MakePointer_> TensorEvaluator<ArgType, Device> Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >::m_impl private
NumDims
template<typename ArgType , typename Device , template< class > class MakePointer_> constexpr int Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >::NumDims = internal::traits<ArgType>::NumDimensions static constexpr
PacketSize
template<typename ArgType , typename Device , template< class > class MakePointer_> constexpr int Eigen::TensorEvaluator< const TensorEvalToOp< ArgType, MakePointer_ >, Device >::PacketSize = PacketType<CoeffReturnType, Device>::size static constexpr
The documentation for this struct was generated from the following file:
TensorEvalTo.h