MercuryDPM: oomph::ParaviewHelper Namespace Reference
oomph::ParaviewHelper Namespace Reference
Namespace for paraview-style output helper functions.
Functions
void write_pvd_header (std::ofstream &pvd_file)
Write the pvd file header.
void write_pvd_information (std::ofstream &pvd_file, const std::string &output_filename, const double &time)
void write_pvd_footer (std::ofstream &pvd_file)
Write the pvd file footer.
Detailed Description
Namespace for paraview-style output helper functions.
//////////////////////////////////////////////////////////////////// //////////////////////////////////////////////////////////////////// ////////////////////////////////////////////////////////////////////
Function Documentation
write_pvd_footer()
void oomph::ParaviewHelper::write_pvd_footer (std::ofstream & pvd_file)
Write the pvd file footer.
     {
       pvd_file << "</Collection>" << std::endl << "</VTKFile>";
     }
Referenced by InterfaceProblem< ELEMENT, TIMESTEPPER >::unsteady_run().
write_pvd_header()
void oomph::ParaviewHelper::write_pvd_header (std::ofstream & pvd_file)
Write the pvd file header.
     {
       pvd_file << "<?xml version=\"1.0\"?>" << std::endl
                << "<VTKFile type=\"Collection\" version=\"0.1\">" << std::endl
                << "<Collection>" << std::endl;
     }
Referenced by InterfaceProblem< ELEMENT, TIMESTEPPER >::unsteady_run().
write_pvd_information()
void oomph::ParaviewHelper::write_pvd_information (std::ofstream & pvd_file, const std::string & output_filename, const double & time)
Add name of output file and associated continuous time to pvd file.
     {
       // Output the actual time values
       pvd_file << "<DataSet timestep=\"" << time << "\" ";
       // Apparently this has to go in
       pvd_file << "part=\"0\" ";
       // Add the name of the file, so that the pvd file knows what it is called
       pvd_file << "file=\"" << output_filename << "\"/>" << std::endl;
     }
Referenced by InterfaceProblem< ELEMENT, TIMESTEPPER >::doc_solution().