MercuryDPM: Eigen::TensorEvaluator< const TensorCwiseTernaryOp< TernaryOp, Arg1Type, Arg2Type, Arg3Type >, Device > Struct Template Reference
Eigen::TensorEvaluator< const TensorCwiseTernaryOp< TernaryOp, Arg1Type, Arg2Type, Arg3Type >, Device > Struct Template Reference
#include <TensorEvaluator.h>
Public Types
enum {
IsAligned , PacketAccess , BlockAccess = false , PreferBlockAccess ,
CoordAccess = false , RawAccess = false
}
typedef TensorCwiseTernaryOp< TernaryOp, Arg1Type, Arg2Type, Arg3Type > XprType
typedef XprType::Index Index
typedef XprType::Scalar Scalar
typedef internal::traits< XprType >::Scalar CoeffReturnType
typedef PacketType< CoeffReturnType, Device >::type PacketReturnType
typedef TensorEvaluator< Arg1Type, Device >::Dimensions Dimensions
typedef StorageMemory< CoeffReturnType, Device > Storage
typedef Storage::Type EvaluatorPointerType
typedef internal::TensorBlockNotImplemented TensorBlock
Public Member Functions
EIGEN_DEVICE_FUNC TensorEvaluator (const XprType &op, const Device &device)
EIGEN_DEVICE_FUNC const Dimensions & dimensions () const
EIGEN_STRONG_INLINE bool evalSubExprsIfNeeded (EvaluatorPointerType)
EIGEN_STRONG_INLINE void cleanup ()
EIGEN_DEVICE_FUNC CoeffReturnType coeff (Index index) const
template<int LoadMode>
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType packet (Index index) const
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost costPerCoeff (bool vectorized) const
EIGEN_DEVICE_FUNC EvaluatorPointerType data () const
Static Public Attributes
static constexpr int Layout = TensorEvaluator<Arg1Type, Device>::Layout
static constexpr int PacketSize = PacketType<CoeffReturnType, Device>::size
Private Attributes
const TernaryOp m_functor
TensorEvaluator< Arg1Type, Device > m_arg1Impl
TensorEvaluator< Arg2Type, Device > m_arg2Impl
TensorEvaluator< Arg3Type, Device > m_arg3Impl
Member Typedef Documentation
CoeffReturnType
template<typename TernaryOp , typename Arg1Type , typename Arg2Type , typename Arg3Type , typename Device > typedef internal::traits<XprType>::Scalar Eigen::TensorEvaluator< const TensorCwiseTernaryOp< TernaryOp, Arg1Type, Arg2Type, Arg3Type >, Device >::CoeffReturnType
Dimensions
template<typename TernaryOp , typename Arg1Type , typename Arg2Type , typename Arg3Type , typename Device > typedef TensorEvaluator<Arg1Type, Device>::Dimensions Eigen::TensorEvaluator< const TensorCwiseTernaryOp< TernaryOp, Arg1Type, Arg2Type, Arg3Type >, Device >::Dimensions
EvaluatorPointerType
template<typename TernaryOp , typename Arg1Type , typename Arg2Type , typename Arg3Type , typename Device > typedef Storage::Type Eigen::TensorEvaluator< const TensorCwiseTernaryOp< TernaryOp, Arg1Type, Arg2Type, Arg3Type >, Device >::EvaluatorPointerType
Index
template<typename TernaryOp , typename Arg1Type , typename Arg2Type , typename Arg3Type , typename Device > typedef XprType::Index Eigen::TensorEvaluator< const TensorCwiseTernaryOp< TernaryOp, Arg1Type, Arg2Type, Arg3Type >, Device >::Index
PacketReturnType
template<typename TernaryOp , typename Arg1Type , typename Arg2Type , typename Arg3Type , typename Device > typedef PacketType<CoeffReturnType, Device>::type Eigen::TensorEvaluator< const TensorCwiseTernaryOp< TernaryOp, Arg1Type, Arg2Type, Arg3Type >, Device >::PacketReturnType
Scalar
template<typename TernaryOp , typename Arg1Type , typename Arg2Type , typename Arg3Type , typename Device > typedef XprType::Scalar Eigen::TensorEvaluator< const TensorCwiseTernaryOp< TernaryOp, Arg1Type, Arg2Type, Arg3Type >, Device >::Scalar
Storage
template<typename TernaryOp , typename Arg1Type , typename Arg2Type , typename Arg3Type , typename Device > typedef StorageMemory<CoeffReturnType, Device> Eigen::TensorEvaluator< const TensorCwiseTernaryOp< TernaryOp, Arg1Type, Arg2Type, Arg3Type >, Device >::Storage
TensorBlock
template<typename TernaryOp , typename Arg1Type , typename Arg2Type , typename Arg3Type , typename Device > typedef internal::TensorBlockNotImplemented Eigen::TensorEvaluator< const TensorCwiseTernaryOp< TernaryOp, Arg1Type, Arg2Type, Arg3Type >, Device >::TensorBlock
XprType
template<typename TernaryOp , typename Arg1Type , typename Arg2Type , typename Arg3Type , typename Device > typedef TensorCwiseTernaryOp<TernaryOp, Arg1Type, Arg2Type, Arg3Type> Eigen::TensorEvaluator< const TensorCwiseTernaryOp< TernaryOp, Arg1Type, Arg2Type, Arg3Type >, Device >::XprType
Member Enumeration Documentation
anonymous enum
template<typename TernaryOp , typename Arg1Type , typename Arg2Type , typename Arg3Type , typename Device > anonymous enum
Enumerator
IsAligned
PacketAccess
BlockAccess
PreferBlockAccess
CoordAccess
RawAccess
        {
     IsAligned = TensorEvaluator<Arg1Type, Device>::IsAligned & TensorEvaluator<Arg2Type, Device>::IsAligned &
                 TensorEvaluator<Arg3Type, Device>::IsAligned,
     PacketAccess = TensorEvaluator<Arg1Type, Device>::PacketAccess && TensorEvaluator<Arg2Type, Device>::PacketAccess &&
                    TensorEvaluator<Arg3Type, Device>::PacketAccess && internal::functor_traits<TernaryOp>::PacketAccess,
     BlockAccess = false,
     PreferBlockAccess = TensorEvaluator<Arg1Type, Device>::PreferBlockAccess ||
                         TensorEvaluator<Arg2Type, Device>::PreferBlockAccess ||
                         TensorEvaluator<Arg3Type, Device>::PreferBlockAccess,
     CoordAccess = false,  // to be implemented
     RawAccess = false
   };
Constructor & Destructor Documentation
TensorEvaluator()
template<typename TernaryOp , typename Arg1Type , typename Arg2Type , typename Arg3Type , typename Device > EIGEN_DEVICE_FUNC Eigen::TensorEvaluator< const TensorCwiseTernaryOp< TernaryOp, Arg1Type, Arg2Type, Arg3Type >, Device >::TensorEvaluator (const XprType & op, const Device & device) inline
       : m_functor(op.functor()),
         m_arg1Impl(op.arg1Expression(), device),
         m_arg2Impl(op.arg2Expression(), device),
         m_arg3Impl(op.arg3Expression(), device) {
     EIGEN_STATIC_ASSERT((static_cast<int>(TensorEvaluator<Arg1Type, Device>::Layout) ==
                              static_cast<int>(TensorEvaluator<Arg3Type, Device>::Layout) ||
                          internal::traits<XprType>::NumDimensions <= 1),
                         YOU_MADE_A_PROGRAMMING_MISTAKE);
     EIGEN_STATIC_ASSERT((internal::is_same<typename internal::traits<Arg1Type>::StorageKind,
                                            typename internal::traits<Arg2Type>::StorageKind>::value),
                         STORAGE_KIND_MUST_MATCH)
     EIGEN_STATIC_ASSERT((internal::is_same<typename internal::traits<Arg1Type>::StorageKind,
                                            typename internal::traits<Arg3Type>::StorageKind>::value),
                         STORAGE_KIND_MUST_MATCH)
     EIGEN_STATIC_ASSERT((internal::is_same<typename internal::traits<Arg1Type>::Index,
                                            typename internal::traits<Arg2Type>::Index>::value),
                         STORAGE_INDEX_MUST_MATCH)
     EIGEN_STATIC_ASSERT((internal::is_same<typename internal::traits<Arg1Type>::Index,
                                            typename internal::traits<Arg3Type>::Index>::value),
                         STORAGE_INDEX_MUST_MATCH)
     eigen_assert(dimensions_match(m_arg1Impl.dimensions(), m_arg2Impl.dimensions()) &&
                  dimensions_match(m_arg1Impl.dimensions(), m_arg3Impl.dimensions()));
   }
References Eigen::dimensions_match(), eigen_assert, EIGEN_STATIC_ASSERT, and Eigen::value.
Member Function Documentation
cleanup()
template<typename TernaryOp , typename Arg1Type , typename Arg2Type , typename Arg3Type , typename Device > EIGEN_STRONG_INLINE void Eigen::TensorEvaluator< const TensorCwiseTernaryOp< TernaryOp, Arg1Type, Arg2Type, Arg3Type >, Device >::cleanup () inline
{
     m_arg1Impl.cleanup();
     m_arg2Impl.cleanup();
     m_arg3Impl.cleanup();
   }
Referenced by framework.Frame::__init__().
coeff()
template<typename TernaryOp , typename Arg1Type , typename Arg2Type , typename Arg3Type , typename Device > EIGEN_DEVICE_FUNC CoeffReturnType Eigen::TensorEvaluator< const TensorCwiseTernaryOp< TernaryOp, Arg1Type, Arg2Type, Arg3Type >, Device >::coeff (Index index) const inline
{
     return m_functor(m_arg1Impl.coeff(index), m_arg2Impl.coeff(index), m_arg3Impl.coeff(index));
   }
costPerCoeff()
template<typename TernaryOp , typename Arg1Type , typename Arg2Type , typename Arg3Type , typename Device > EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE TensorOpCost Eigen::TensorEvaluator< const TensorCwiseTernaryOp< TernaryOp, Arg1Type, Arg2Type, Arg3Type >, Device >::costPerCoeff (bool vectorized) const inline
{
     const double functor_cost = internal::functor_traits<TernaryOp>::Cost;
     return m_arg1Impl.costPerCoeff(vectorized) + m_arg2Impl.costPerCoeff(vectorized) +
            m_arg3Impl.costPerCoeff(vectorized) + TensorOpCost(0, 0, functor_cost, vectorized, PacketSize);
   }
References Eigen::TensorEvaluator< Derived, Device >::PacketSize.
data()
template<typename TernaryOp , typename Arg1Type , typename Arg2Type , typename Arg3Type , typename Device > EIGEN_DEVICE_FUNC EvaluatorPointerType Eigen::TensorEvaluator< const TensorCwiseTernaryOp< TernaryOp, Arg1Type, Arg2Type, Arg3Type >, Device >::data () const inline
 { return NULL; }
Referenced by gdb.printers.EigenMatrixPrinter::children(), gdb.printers.EigenSparseMatrixPrinter::children(), gdb.printers.EigenQuaternionPrinter::children(), gdb.printers.EigenMatrixPrinter::to_string(), gdb.printers.EigenSparseMatrixPrinter::to_string(), and gdb.printers.EigenQuaternionPrinter::to_string().
dimensions()
template<typename TernaryOp , typename Arg1Type , typename Arg2Type , typename Arg3Type , typename Device > EIGEN_DEVICE_FUNC const Dimensions& Eigen::TensorEvaluator< const TensorCwiseTernaryOp< TernaryOp, Arg1Type, Arg2Type, Arg3Type >, Device >::dimensions () const inline
{
     // TODO: use arg2 or arg3 dimensions if they are known at compile time.
     return m_arg1Impl.dimensions();
   }
evalSubExprsIfNeeded()
template<typename TernaryOp , typename Arg1Type , typename Arg2Type , typename Arg3Type , typename Device > EIGEN_STRONG_INLINE bool Eigen::TensorEvaluator< const TensorCwiseTernaryOp< TernaryOp, Arg1Type, Arg2Type, Arg3Type >, Device >::evalSubExprsIfNeeded (EvaluatorPointerType) inline
{
     m_arg1Impl.evalSubExprsIfNeeded(NULL);
     m_arg2Impl.evalSubExprsIfNeeded(NULL);
     m_arg3Impl.evalSubExprsIfNeeded(NULL);
     return true;
   }
packet()
template<typename TernaryOp , typename Arg1Type , typename Arg2Type , typename Arg3Type , typename Device > template<int LoadMode> EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE PacketReturnType Eigen::TensorEvaluator< const TensorCwiseTernaryOp< TernaryOp, Arg1Type, Arg2Type, Arg3Type >, Device >::packet (Index index) const inline
{
     return m_functor.packetOp(m_arg1Impl.template packet<LoadMode>(index), m_arg2Impl.template packet<LoadMode>(index),
                               m_arg3Impl.template packet<LoadMode>(index));
   }
Member Data Documentation
Layout
template<typename TernaryOp , typename Arg1Type , typename Arg2Type , typename Arg3Type , typename Device > constexpr int Eigen::TensorEvaluator< const TensorCwiseTernaryOp< TernaryOp, Arg1Type, Arg2Type, Arg3Type >, Device >::Layout = TensorEvaluator<Arg1Type, Device>::Layout static constexpr
m_arg1Impl
template<typename TernaryOp , typename Arg1Type , typename Arg2Type , typename Arg3Type , typename Device > TensorEvaluator<Arg1Type, Device> Eigen::TensorEvaluator< const TensorCwiseTernaryOp< TernaryOp, Arg1Type, Arg2Type, Arg3Type >, Device >::m_arg1Impl private
m_arg2Impl
template<typename TernaryOp , typename Arg1Type , typename Arg2Type , typename Arg3Type , typename Device > TensorEvaluator<Arg2Type, Device> Eigen::TensorEvaluator< const TensorCwiseTernaryOp< TernaryOp, Arg1Type, Arg2Type, Arg3Type >, Device >::m_arg2Impl private
m_arg3Impl
template<typename TernaryOp , typename Arg1Type , typename Arg2Type , typename Arg3Type , typename Device > TensorEvaluator<Arg3Type, Device> Eigen::TensorEvaluator< const TensorCwiseTernaryOp< TernaryOp, Arg1Type, Arg2Type, Arg3Type >, Device >::m_arg3Impl private
m_functor
template<typename TernaryOp , typename Arg1Type , typename Arg2Type , typename Arg3Type , typename Device > const TernaryOp Eigen::TensorEvaluator< const TensorCwiseTernaryOp< TernaryOp, Arg1Type, Arg2Type, Arg3Type >, Device >::m_functor private
PacketSize
template<typename TernaryOp , typename Arg1Type , typename Arg2Type , typename Arg3Type , typename Device > constexpr int Eigen::TensorEvaluator< const TensorCwiseTernaryOp< TernaryOp, Arg1Type, Arg2Type, Arg3Type >, Device >::PacketSize = PacketType<CoeffReturnType, Device>::size static constexpr
The documentation for this struct was generated from the following file:
TensorEvaluator.h