MercuryDPM: Eigen::internal::unary_pow::exponent_helper< ScalarExponent, IsInteger > Struct Template Reference
Eigen::internal::unary_pow::exponent_helper< ScalarExponent, IsInteger > Struct Template Reference
#include <GenericPacketMathFunctions.h>
Public Types
using safe_abs_type = ScalarExponent
Static Public Member Functions
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ScalarExponent safe_abs (const ScalarExponent &exp)
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool is_odd (const ScalarExponent &exp)
static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ScalarExponent floor_div_two (const ScalarExponent &exp)
Static Public Attributes
static constexpr ScalarExponent one_half = ScalarExponent(0.5)
Member Typedef Documentation
safe_abs_type
template<typename ScalarExponent , bool IsInteger = NumTraits<ScalarExponent>::IsInteger> using Eigen::internal::unary_pow::exponent_helper< ScalarExponent, IsInteger >::safe_abs_type = ScalarExponent
Member Function Documentation
floor_div_two()
template<typename ScalarExponent , bool IsInteger = NumTraits<ScalarExponent>::IsInteger> static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ScalarExponent Eigen::internal::unary_pow::exponent_helper< ScalarExponent, IsInteger >::floor_div_two (const ScalarExponent & exp) inline static
{
     ScalarExponent exp_div_2 = exp * one_half;
     return numext::floor(exp_div_2);
   }
References Eigen::bfloat16_impl::exp(), Eigen::numext::floor(), and Eigen::internal::unary_pow::exponent_helper< ScalarExponent, IsInteger >::one_half.
is_odd()
template<typename ScalarExponent , bool IsInteger = NumTraits<ScalarExponent>::IsInteger> static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE bool Eigen::internal::unary_pow::exponent_helper< ScalarExponent, IsInteger >::is_odd (const ScalarExponent & exp) inline static
{
     eigen_assert(((numext::isfinite)(exp) && exp == numext::floor(exp)) && "exp must be an integer");
     ScalarExponent exp_div_2 = exp * one_half;
     ScalarExponent floor_exp_div_2 = numext::floor(exp_div_2);
     return exp_div_2 != floor_exp_div_2;
   }
References eigen_assert, Eigen::bfloat16_impl::exp(), Eigen::numext::floor(), Eigen::numext::isfinite(), and Eigen::internal::unary_pow::exponent_helper< ScalarExponent, IsInteger >::one_half.
safe_abs()
template<typename ScalarExponent , bool IsInteger = NumTraits<ScalarExponent>::IsInteger> static EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE ScalarExponent Eigen::internal::unary_pow::exponent_helper< ScalarExponent, IsInteger >::safe_abs (const ScalarExponent & exp) inline static
{
     return numext::abs(exp);
   }
References Eigen::numext::abs(), and Eigen::bfloat16_impl::exp().
Member Data Documentation
one_half
template<typename ScalarExponent , bool IsInteger = NumTraits<ScalarExponent>::IsInteger> constexpr ScalarExponent Eigen::internal::unary_pow::exponent_helper< ScalarExponent, IsInteger >::one_half = ScalarExponent(0.5) static constexpr
Referenced by Eigen::internal::unary_pow::exponent_helper< ScalarExponent, IsInteger >::floor_div_two(), and Eigen::internal::unary_pow::exponent_helper< ScalarExponent, IsInteger >::is_odd().
The documentation for this struct was generated from the following file:
GenericPacketMathFunctions.h