MercuryDPM: FancySpheres Class Reference
FancySpheres Class Reference
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW FancySpheres ()
void draw ()
Protected Attributes
std::vector< Vector3f > mCenters
std::vector< float > mRadii
IcoSphere mIcoSphere
Constructor & Destructor Documentation
FancySpheres()
EIGEN_MAKE_ALIGNED_OPERATOR_NEW FancySpheres::FancySpheres () inline
                  {
     const int levels = 4;
     const float scale = 0.33;
     float radius = 100;
     std::vector<int> parents;
     // leval 0
     mCenters.push_back(Vector3f::Zero());
     parents.push_back(-1);
     mRadii.push_back(radius);
     // generate level 1 using icosphere vertices
     radius *= 0.45;
     {
       float dist = mRadii[0] * 0.9;
       for (int i = 0; i < 12; ++i) {
         mCenters.push_back(mIcoSphere.vertices()[i] * dist);
         mRadii.push_back(radius);
         parents.push_back(0);
       }
     }
     static const float angles[10] = {0, 0, M_PI, 0. * M_PI, M_PI, 0.5 * M_PI, M_PI, 1. * M_PI, M_PI, 1.5 * M_PI};
     // generate other levels
     int start = 1;
     for (int l = 1; l < levels; l++) {
       radius *= scale;
       int end = mCenters.size();
       for (int i = start; i < end; ++i) {
         Vector3f c = mCenters[i];
         Vector3f ax0 = (c - mCenters[parents[i]]).normalized();
         Vector3f ax1 = ax0.unitOrthogonal();
         Quaternionf q;
         q.setFromTwoVectors(Vector3f::UnitZ(), ax0);
         Affine3f t = Translation3f(c) * q * Scaling(mRadii[i] + radius);
         for (int j = 0; j < 5; ++j) {
           Vector3f newC =
               c + ((AngleAxisf(angles[j * 2 + 1], ax0) * AngleAxisf(angles[j * 2 + 0] * (l == 1 ? 0.35 : 0.5), ax1)) *
                    ax0) *
                       (mRadii[i] + radius * 0.8);
           mCenters.push_back(newC);
           mRadii.push_back(radius);
           parents.push_back(i);
         }
       }
       start = end;
     }
   }
References calibrate::c, Eigen::placeholders::end, i, j, M_PI, Eigen::numext::q, UniformPSDSelfTest::radius, Eigen::Scaling(), oomph::CumulativeTimings::start(), plotPSD::t, and oomph::PseudoSolidHelper::Zero.
Member Function Documentation
draw()
void FancySpheres::draw () inline
               {
     int end = mCenters.size();
     glEnable(GL_NORMALIZE);
     for (int i = 0; i < end; ++i) {
       Affine3f t = Translation3f(mCenters[i]) * Scaling(mRadii[i]);
       gpu.pushMatrix(GL_MODELVIEW);
       gpu.multMatrix(t.matrix(), GL_MODELVIEW);
       mIcoSphere.draw(2);
       gpu.popMatrix(GL_MODELVIEW);
     }
     glDisable(GL_NORMALIZE);
   }
References Eigen::placeholders::end, gpu, i, GpuHelper::multMatrix(), GpuHelper::popMatrix(), GpuHelper::pushMatrix(), Eigen::Scaling(), and plotPSD::t.
Referenced by RenderingWidget::drawScene().
Member Data Documentation
mCenters
std::vector<Vector3f> FancySpheres::mCenters protected
mIcoSphere
IcoSphere FancySpheres::mIcoSphere protected
mRadii
std::vector<float> FancySpheres::mRadii protected
The documentation for this class was generated from the following file:
quaternion_demo.cpp