MercuryDPM: Eigen::TensorIOFormatBase< Derived_ > Struct Template Reference
Eigen::TensorIOFormatBase< Derived_ > Struct Template Reference
#include <TensorIO.h>
Public Types
using Derived = Derived_
Public Member Functions
TensorIOFormatBase (const std::vector< std::string > &separator, const std::vector< std::string > &prefix, const std::vector< std::string > &suffix, int precision=StreamPrecision, int flags=0, const std::string &tenPrefix="", const std::string &tenSuffix="", const char fill=' ')
void init_spacer ()
Public Attributes
std::string tenPrefix
std::string tenSuffix
std::vector< std::string > prefix
std::vector< std::string > suffix
std::vector< std::string > separator
char fill
int precision
int flags
std::vector< std::string > spacer {}
Member Typedef Documentation
Derived
template<typename Derived_ > using Eigen::TensorIOFormatBase< Derived_ >::Derived = Derived_
Constructor & Destructor Documentation
TensorIOFormatBase()
template<typename Derived_ > Eigen::TensorIOFormatBase< Derived_ >::TensorIOFormatBase (const std::vector< std::string > & separator, const std::vector< std::string > & prefix, const std::vector< std::string > & suffix, int precision = StreamPrecision, int flags = 0, const std::string & tenPrefix = "", const std::string & tenSuffix = "", const char fill = ' ') inline
       : tenPrefix(tenPrefix),
         tenSuffix(tenSuffix),
         prefix(prefix),
         suffix(suffix),
         separator(separator),
         fill(fill),
         precision(precision),
         flags(flags) {
     init_spacer();
   }
References Eigen::TensorIOFormatBase< Derived_ >::init_spacer().
Member Function Documentation
init_spacer()
template<typename Derived_ > void Eigen::TensorIOFormatBase< Derived_ >::init_spacer () inline
                      {
     if ((flags & DontAlignCols)) return;
     spacer.resize(prefix.size());
     spacer[0] = "";
     int i = int(tenPrefix.length()) - 1;
     while (i >= 0 && tenPrefix[i] != '\n') {
       spacer[0] += ' ';
       i--;
     }
     for (std::size_t k = 1; k < prefix.size(); k++) {
       int j = int(prefix[k].length()) - 1;
       while (j >= 0 && prefix[k][j] != '\n') {
         spacer[k] += ' ';
         j--;
       }
     }
   }
References Eigen::DontAlignCols, Eigen::TensorIOFormatBase< Derived_ >::flags, i, int(), j, k, Eigen::TensorIOFormatBase< Derived_ >::prefix, Eigen::TensorIOFormatBase< Derived_ >::spacer, and Eigen::TensorIOFormatBase< Derived_ >::tenPrefix.
Referenced by Eigen::TensorIOFormatBase< Derived_ >::TensorIOFormatBase().
Member Data Documentation
fill
template<typename Derived_ > char Eigen::TensorIOFormatBase< Derived_ >::fill
flags
template<typename Derived_ > int Eigen::TensorIOFormatBase< Derived_ >::flags
Referenced by Eigen::TensorIOFormatBase< Derived_ >::init_spacer().
precision
template<typename Derived_ > int Eigen::TensorIOFormatBase< Derived_ >::precision
prefix
template<typename Derived_ > std::vector<std::string> Eigen::TensorIOFormatBase< Derived_ >::prefix
Referenced by Eigen::TensorIOFormatBase< Derived_ >::init_spacer().
separator
template<typename Derived_ > std::vector<std::string> Eigen::TensorIOFormatBase< Derived_ >::separator
spacer
template<typename Derived_ > std::vector<std::string> Eigen::TensorIOFormatBase< Derived_ >::spacer {}
Referenced by Eigen::TensorIOFormatBase< Derived_ >::init_spacer().
suffix
template<typename Derived_ > std::vector<std::string> Eigen::TensorIOFormatBase< Derived_ >::suffix
tenPrefix
template<typename Derived_ > std::string Eigen::TensorIOFormatBase< Derived_ >::tenPrefix
Referenced by Eigen::TensorIOFormatBase< Derived_ >::init_spacer().
tenSuffix
template<typename Derived_ > std::string Eigen::TensorIOFormatBase< Derived_ >::tenSuffix
The documentation for this struct was generated from the following file:
TensorIO.h