MercuryDPM: Eigen::internal::trsmKernelR< Scalar, Index, Mode, Conjugate, TriStorageOrder, OtherInnerStride, Specialized > Struct Template Reference
Eigen::internal::trsmKernelR< Scalar, Index, Mode, Conjugate, TriStorageOrder, OtherInnerStride, Specialized > Struct Template Reference
#include <TriangularSolverMatrix.h>
Static Public Member Functions
static void kernel (Index size, Index otherSize, const Scalar *_tri, Index triStride, Scalar *_other, Index otherIncr, Index otherStride)
Member Function Documentation
kernel()
template<typename Scalar , typename Index , int Mode, bool Conjugate, int TriStorageOrder, int OtherInnerStride, bool Specialized> EIGEN_STRONG_INLINE void Eigen::internal::trsmKernelR< Scalar, Index, Mode, Conjugate, TriStorageOrder, OtherInnerStride, Specialized >::kernel (Index size, Index otherSize, const Scalar * _tri, Index triStride, Scalar * _other, Index otherIncr, Index otherStride) static
{
   typedef typename NumTraits<Scalar>::Real RealScalar;
   typedef blas_data_mapper<Scalar, Index, ColMajor, Unaligned, OtherInnerStride> LhsMapper;
   typedef const_blas_data_mapper<Scalar, Index, TriStorageOrder> RhsMapper;
   LhsMapper lhs(_other, otherStride, otherIncr);
   RhsMapper rhs(_tri, triStride);
   enum { RhsStorageOrder = TriStorageOrder, IsLower = (Mode & Lower) == Lower };
   conj_if<Conjugate> conj;
   for (Index k = 0; k < size; ++k) {
     Index j = IsLower ? size - k - 1 : k;
     typename LhsMapper::LinearMapper r = lhs.getLinearMapper(0, j);
     for (Index k3 = 0; k3 < k; ++k3) {
       Scalar b = conj(rhs(IsLower ? j + 1 + k3 : k3, j));
       typename LhsMapper::LinearMapper a = lhs.getLinearMapper(0, IsLower ? j + 1 + k3 : k3);
       for (Index i = 0; i < otherSize; ++i) r(i) -= a(i) * b;
     }
     if ((Mode & UnitDiag) == 0) {
       Scalar inv_rjj = RealScalar(1) / conj(rhs(j, j));
       for (Index i = 0; i < otherSize; ++i) r(i) *= inv_rjj;
     }
   }
 }
References a, b, Eigen::conj(), i, j, k, Eigen::Lower, UniformPSDSelfTest::r, size, and Eigen::UnitDiag.
Referenced by Eigen::internal::trsmKernelR< double, Index, Mode, false, TriStorageOrder, 1, true >::kernel(), and Eigen::internal::trsmKernelR< float, Index, Mode, false, TriStorageOrder, 1, true >::kernel().
The documentation for this struct was generated from the following files:
TrsmKernel.h
TriangularSolverMatrix.h