MercuryDPM: AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT > Class Template Reference
AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT > Class Template Reference
Public Member Functions
FiniteElement *& interface_element_pt (const unsigned long &i)
Access functions for pointers to interface elements.
unsigned long ninterface_element () const
Number of elements on interface.
FiniteElement *& interface_edge_element_pt (const unsigned long &i)
Access functions for pointers to interface elements.
unsigned long ninterface_edge_element () const
Number of elements on interface.
Vector< GeneralisedElement * > & bulk_element_pt ()
GeneralisedElement *& bulk_element_pt (const unsigned long &i)
Access functions for pointers to elements in bulk.
unsigned long nbulk () const
Number of elements in bulk.
AxialSpineQuarterTubeMesh (GeomObject *wall_pt, const Vector< double > &xi_lo, const double &fract_mid, const Vector< double > &xi_hi, const unsigned &nlayer, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor.
virtual void spine_node_update (SpineNode *spine_node_pt)
Update nodal positions in response to spine changes.
FiniteElement *& interface_element_pt (const unsigned long &i)
Access functions for pointers to interface elements.
unsigned long ninterface_element () const
Number of elements on interface.
FiniteElement *& interface_edge_element_pt (const unsigned long &i)
Access functions for pointers to interface elements.
unsigned long ninterface_edge_element () const
Number of elements on interface.
Vector< GeneralisedElement * > & bulk_element_pt ()
GeneralisedElement *& bulk_element_pt (const unsigned long &i)
Access functions for pointers to elements in bulk.
unsigned long nbulk () const
Number of elements in bulk.
AxialSpineQuarterTubeMesh (GeomObject *wall_pt, const Vector< double > &xi_lo, const double &fract_mid, const Vector< double > &xi_hi, const unsigned &nlayer, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
Constructor.
virtual void spine_node_update (SpineNode *spine_node_pt)
Update nodal positions in response to spine changes.
Public Member Functions inherited from oomph::RefineableQuarterTubeMesh< ELEMENT >
RefineableQuarterTubeMesh (GeomObject *wall_pt, const Vector< double > &xi_lo, const double &fract_mid, const Vector< double > &xi_hi, const unsigned &nlayer, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
virtual ~RefineableQuarterTubeMesh ()
Destructor: empty.
Public Member Functions inherited from oomph::QuarterTubeMesh< ELEMENT >
QuarterTubeMesh (GeomObject *wall_pt, const Vector< double > &xi_lo, const double &fract_mid, const Vector< double > &xi_hi, const unsigned &nlayer, TimeStepper *time_stepper_pt=&Mesh::Default_TimeStepper)
virtual ~QuarterTubeMesh ()
Destructor: empty.
GeomObject *& wall_pt ()
Access function to GeomObject representing wall.
QuarterTubeDomain * domain_pt ()
Access function to domain.
QuarterTubeDomain::BLSquashFctPt & bl_squash_fct_pt ()
virtual QuarterTubeDomain::AxialSpacingFctPt & axial_spacing_fct_pt ()
Function pointer for function for axial spacing.
QuarterTubeDomain * domain_pt () const
Access function to underlying domain.
Public Member Functions inherited from oomph::BrickMeshBase
BrickMeshBase ()
Constructor (empty)
BrickMeshBase (const BrickMeshBase &)=delete
Broken copy constructor.
virtual ~BrickMeshBase ()
Broken assignment operator.
void setup_boundary_element_info ()
void setup_boundary_element_info (std::ostream &outfile)
Public Member Functions inherited from oomph::Mesh
Mesh ()
Default constructor.
Mesh (const Vector< Mesh * > &sub_mesh_pt)
void merge_meshes (const Vector< Mesh * > &sub_mesh_pt)
virtual void reset_boundary_element_info (Vector< unsigned > &ntmp_boundary_elements, Vector< Vector< unsigned >> &ntmp_boundary_elements_in_region, Vector< FiniteElement * > &deleted_elements)
Virtual function to perform the reset boundary elements info rutines.
template<class BULK_ELEMENT >
void doc_boundary_coordinates (const unsigned &b, std::ofstream &the_file)
virtual void scale_mesh (const double &factor)
Mesh (const Mesh &dummy)=delete
Broken copy constructor.
void operator= (const Mesh &)=delete
Broken assignment operator.
virtual ~Mesh ()
Virtual Destructor to clean up all memory.
void flush_element_and_node_storage ()
void flush_element_storage ()
void flush_node_storage ()
Node *& node_pt (const unsigned long &n)
Return pointer to global node n.
Node * node_pt (const unsigned long &n) const
Return pointer to global node n (const version)
GeneralisedElement *& element_pt (const unsigned long &e)
Return pointer to element e.
GeneralisedElement * element_pt (const unsigned long &e) const
Return pointer to element e (const version)
const Vector< GeneralisedElement * > & element_pt () const
Return reference to the Vector of elements.
Vector< GeneralisedElement * > & element_pt ()
Return reference to the Vector of elements.
FiniteElement * finite_element_pt (const unsigned &e) const
Node *& boundary_node_pt (const unsigned &b, const unsigned &n)
Return pointer to node n on boundary b.
Node * boundary_node_pt (const unsigned &b, const unsigned &n) const
Return pointer to node n on boundary b.
void set_nboundary (const unsigned &nbound)
Set the number of boundaries in the mesh.
void remove_boundary_nodes ()
Clear all pointers to boundary nodes.
void remove_boundary_nodes (const unsigned &b)
void remove_boundary_node (const unsigned &b, Node *const &node_pt)
Remove a node from the boundary b.
void add_boundary_node (const unsigned &b, Node *const &node_pt)
Add a (pointer to) a node to the b-th boundary.
void copy_boundary_node_data_from_nodes ()
bool boundary_coordinate_exists (const unsigned &i) const
Indicate whether the i-th boundary has an intrinsic coordinate.
unsigned long nelement () const
Return number of elements in the mesh.
unsigned long nnode () const
Return number of nodes in the mesh.
unsigned ndof_types () const
Return number of dof types in mesh.
unsigned elemental_dimension () const
Return number of elemental dimension in mesh.
unsigned nodal_dimension () const
Return number of nodal dimension in mesh.
void add_node_pt (Node *const &node_pt)
Add a (pointer to a) node to the mesh.
void add_element_pt (GeneralisedElement *const &element_pt)
Add a (pointer to) an element to the mesh.
virtual void reorder_nodes (const bool &use_old_ordering=true)
virtual void get_node_reordering (Vector< Node * > &reordering, const bool &use_old_ordering=true) const
template<class BULK_ELEMENT , template< class > class FACE_ELEMENT>
void build_face_mesh (const unsigned &b, Mesh *const &face_mesh_pt)
unsigned self_test ()
Self-test: Check elements and nodes. Return 0 for OK.
void max_and_min_element_size (double &max_size, double &min_size)
double total_size ()
void check_inverted_elements (bool &mesh_has_inverted_elements, std::ofstream &inverted_element_file)
void check_inverted_elements (bool &mesh_has_inverted_elements)
unsigned check_for_repeated_nodes (const double &epsilon=1.0e-12)
Vector< Node * > prune_dead_nodes ()
unsigned nboundary () const
Return number of boundaries.
unsigned long nboundary_node (const unsigned &ibound) const
Return number of nodes on a particular boundary.
FiniteElement * boundary_element_pt (const unsigned &b, const unsigned &e) const
Return pointer to e-th finite element on boundary b.
Node * get_some_non_boundary_node () const
unsigned nboundary_element (const unsigned &b) const
Return number of finite elements that are adjacent to boundary b.
int face_index_at_boundary (const unsigned &b, const unsigned &e) const
virtual void dump (std::ofstream &dump_file, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void dump (const std::string &dump_file_name, const bool &use_old_ordering=true) const
Dump the data in the mesh into a file for restart.
void output_paraview (std::ofstream &file_out, const unsigned &nplot) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt) const
void output_fct_paraview (std::ofstream &file_out, const unsigned &nplot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt) const
void output (std::ostream &outfile)
Output for all elements.
void output (std::ostream &outfile, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output (FILE *file_pt)
Output for all elements (C-style output)
void output (FILE *file_pt, const unsigned &nplot)
Output at f(n_plot) points in each element (C-style output)
void output (const std::string &output_filename)
Output for all elements.
void output (const std::string &output_filename, const unsigned &n_plot)
Output at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, FiniteElement::SteadyExactSolutionFctPt)
Output a given Vector function at f(n_plot) points in each element.
void output_fct (std::ostream &outfile, const unsigned &n_plot, const double &time, FiniteElement::UnsteadyExactSolutionFctPt)
void output_boundaries (std::ostream &outfile)
Output the nodes on the boundaries (into separate tecplot zones)
void output_boundaries (const std::string &output_filename)
void assign_initial_values_impulsive ()
Assign initial values for an impulsive start.
void shift_time_values ()
void calculate_predictions ()
void set_nodal_and_elemental_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_consistent_pinned_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
Set consistent values for pinned data in continuation.
bool does_pointer_correspond_to_mesh_data (double *const &parameter_pt)
Does the double pointer correspond to any mesh data.
void set_nodal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Set the timestepper associated with the nodal data in the mesh.
void set_elemental_internal_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
virtual void compute_norm (double &norm)
virtual void compute_norm (Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, double &error, double &norm)
virtual void compute_error (FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (std::ostream &outfile, FiniteElement::SteadyExactSolutionFctPt exact_soln_pt, Vector< double > &error, Vector< double > &norm)
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, double &error, double &norm)
Returns the norm of the error and that of the exact solution.
virtual void compute_error (FiniteElement::UnsteadyExactSolutionFctPt exact_soln_pt, const double &time, Vector< double > &error, Vector< double > &norm)
bool is_mesh_distributed () const
Boolean to indicate if Mesh has been distributed.
OomphCommunicator * communicator_pt () const
void delete_all_external_storage ()
Wipe the storage for all externally-based elements.
Public Member Functions inherited from oomph::RefineableBrickMesh< ELEMENT >
RefineableBrickMesh ()
Constructor: Setup static octree data.
RefineableBrickMesh (const RefineableBrickMesh &dummy)=delete
Broken copy constructor.
void operator= (const RefineableBrickMesh &)=delete
Broken assignment operator.
virtual ~RefineableBrickMesh ()
Destructor:
virtual void setup_tree_forest ()
void setup_octree_forest ()
Do what it says...
Public Member Functions inherited from oomph::TreeBasedRefineableMesh< ELEMENT >
TreeBasedRefineableMesh ()
Constructor, call the constructor of the base class.
TreeBasedRefineableMesh (const TreeBasedRefineableMesh &dummy)=delete
Broken copy constructor.
virtual ~TreeBasedRefineableMesh ()
Empty virtual destructor.
Public Member Functions inherited from oomph::TreeBasedRefineableMeshBase
TreeBasedRefineableMeshBase ()
Constructor.
TreeBasedRefineableMeshBase (const TreeBasedRefineableMeshBase &dummy)=delete
Broken copy constructor.
void operator= (const TreeBasedRefineableMeshBase &)=delete
Broken assignment operator.
virtual ~TreeBasedRefineableMeshBase ()
Empty Destructor:
void adapt (const Vector< double > &elemental_error)
void p_adapt (const Vector< double > &elemental_error)
void refine_uniformly (DocInfo &doc_info)
Refine mesh uniformly and doc process.
void refine_uniformly ()
Refine mesh uniformly.
void p_refine_uniformly (DocInfo &doc_info)
p-refine mesh uniformly and doc process
void p_refine_uniformly ()
p-refine mesh uniformly
unsigned unrefine_uniformly ()
void p_unrefine_uniformly (DocInfo &doc_info)
p-unrefine mesh uniformly
TreeForest * forest_pt ()
Return pointer to the Forest represenation of the mesh.
void doc_adaptivity_targets (std::ostream &outfile)
Doc the targets for mesh adaptation.
unsigned & max_refinement_level ()
Access fct for max. permissible refinement level (relative to base mesh)
unsigned & min_refinement_level ()
Access fct for min. permissible refinement level (relative to base mesh)
unsigned & max_p_refinement_level ()
unsigned & min_p_refinement_level ()
virtual void adapt_mesh (DocInfo &doc_info)
virtual void adapt_mesh ()
void p_adapt_mesh (DocInfo &doc_info)
void p_adapt_mesh ()
virtual void refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
virtual void refine_selected_elements (const Vector< RefineableElement * > &elements_to_be_refined)
void p_refine_selected_elements (const Vector< unsigned > &elements_to_be_refined)
p-refine mesh by refining the elements identified by their numbers.
void p_refine_selected_elements (const Vector< PRefineableElement * > &elements_to_be_refined_pt)
p-refine mesh by refining the elements identified by their pointers.
virtual void refine_base_mesh_as_in_reference_mesh (TreeBasedRefineableMeshBase *const &ref_mesh_pt)
Refine to same degree as the reference mesh.
virtual bool refine_base_mesh_as_in_reference_mesh_minus_one (TreeBasedRefineableMeshBase *const &ref_mesh_pt)
virtual void refine_as_in_reference_mesh (TreeBasedRefineableMeshBase *const &ref_mesh_pt)
virtual void get_refinement_levels (unsigned &min_refinement_level, unsigned &max_refinement_level)
Get max/min refinement levels in mesh.
virtual void get_elements_at_refinement_level (unsigned &refinement_level, Vector< RefineableElement * > &level_elements)
virtual void get_refinement_pattern (Vector< Vector< unsigned >> &to_be_refined)
void refine_base_mesh (Vector< Vector< unsigned >> &to_be_refined)
Refine base mesh according to specified refinement pattern.
virtual void refine (std::ifstream &restart_file)
Refine mesh according to refinement pattern in restart file.
virtual void dump_refinement (std::ostream &outfile)
Dump refinement pattern to allow for rebuild.
virtual void read_refinement (std::ifstream &restart_file, Vector< Vector< unsigned >> &to_be_refined)
Read refinement pattern to allow for rebuild.
unsigned uniform_refinement_level_when_pruned () const
unsigned & uniform_refinement_level_when_pruned ()
Level to which the mesh was uniformly refined when it was pruned.
Public Member Functions inherited from oomph::RefineableMeshBase
bool adapt_flag ()
RefineableMeshBase ()
RefineableMeshBase (const RefineableMeshBase &dummy)=delete
Broken copy constructor.
void operator= (const RefineableMeshBase &)=delete
Broken assignment operator.
virtual ~RefineableMeshBase ()
Empty Destructor:
unsigned nrefined ()
Access fct for number of elements that were refined.
unsigned nunrefined ()
Access fct for number of elements that were unrefined.
unsigned & nrefinement_overruled ()
unsigned & max_keep_unrefined ()
ErrorEstimator *& spatial_error_estimator_pt ()
Access to spatial error estimator.
ErrorEstimator * spatial_error_estimator_pt () const
Access to spatial error estimator (const version.
double & min_permitted_error ()
double & max_permitted_error ()
double & min_error ()
double & max_error ()
DocInfo *& doc_info_pt ()
Access fct for pointer to DocInfo.
void enable_adaptation ()
Enable adaptation.
void disable_adaptation ()
Disable adaptation.
void enable_p_adaptation ()
Enable adaptation.
void disable_p_adaptation ()
Disable adaptation.
void enable_additional_synchronisation_of_hanging_nodes ()
Enable additional synchronisation of hanging nodes.
void disable_additional_synchronisation_of_hanging_nodes ()
Disable additional synchronisation of hanging nodes.
bool is_adaptation_enabled () const
Return whether the mesh is to be adapted.
bool is_p_adaptation_enabled () const
Return whether the mesh is to be adapted.
bool is_additional_synchronisation_of_hanging_nodes_disabled () const
Return whether additional synchronisation is enabled.
DocInfo doc_info ()
Access fct for DocInfo.
void p_unrefine_uniformly (DocInfo &doc_info)
p-unrefine mesh uniformly
Public Member Functions inherited from oomph::SpineMesh
virtual ~SpineMesh ()
Destructor to clean up the memory allocated to the spines.
Spine *& spine_pt (const unsigned long &i)
Return the i-th spine in the mesh.
const Spine * spine_pt (const unsigned long &i) const
Return the i-th spine in the mesh (const version)
unsigned long nspine () const
Return the number of spines in the mesh.
void add_spine_pt (Spine *const &spine_pt)
Add a spine to the mesh.
SpineNode * node_pt (const unsigned long &n)
Return a pointer to the n-th global SpineNode.
SpineNode * element_node_pt (const unsigned long &e, const unsigned &n)
unsigned long assign_global_spine_eqn_numbers (Vector< double * > &Dof_pt)
Assign spines to Spine_pt vector of element.
void describe_spine_dofs (std::ostream &out, const std::string &current_string) const
void set_mesh_level_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
void set_spine_time_stepper (TimeStepper *const &time_stepper_pt, const bool &preserve_existing_data)
Assign time stepper to spines data.
void set_consistent_pinned_spine_values_for_continuation (ContinuationStorageScheme *const &continuation_stepper_pt)
bool does_pointer_correspond_to_spine_data (double *const &parameter_pt)
void node_update (const bool &update_all_solid_nodes=false)
void dump (std::ofstream &dump_file) const
Overload the dump function so that the spine data is dumped.
void read (std::ifstream &restart_file)
Overload the read function so that the spine data is also read.
Private Attributes
Vector< GeneralisedElement * > Bulk_element_pt
Vector of pointers to element in the fluid layer.
Vector< FiniteElement * > Interface_element_pt
Vector of pointers to interface elements.
Vector< FiniteElement * > Interface_edge_element_pt
Vector of pointers to interface elements.
Additional Inherited Members
Public Types inherited from oomph::Mesh
typedef void(FiniteElement::* SteadyExactSolutionFctPt) (const Vector< double > &x, Vector< double > &soln)
typedef void(FiniteElement::* UnsteadyExactSolutionFctPt) (const double &time, const Vector< double > &x, Vector< double > &soln)
Static Public Attributes inherited from oomph::Mesh
static Steady< 0 > Default_TimeStepper
The Steady Timestepper.
static bool Suppress_warning_about_empty_mesh_level_time_stepper_function
Static boolean flag to control warning about mesh level timesteppers.
Protected Member Functions inherited from oomph::Mesh
unsigned long assign_global_eqn_numbers (Vector< double * > &Dof_pt)
Assign (global) equation numbers to the nodes.
void describe_dofs (std::ostream &out, const std::string &current_string) const
void describe_local_dofs (std::ostream &out, const std::string &current_string) const
void assign_local_eqn_numbers (const bool &store_local_dof_pt)
Assign local equation numbers in all elements.
void convert_to_boundary_node (Node *&node_pt, const Vector< FiniteElement * > &finite_element_pt)
void convert_to_boundary_node (Node *&node_pt)
Protected Member Functions inherited from oomph::TreeBasedRefineableMeshBase
void complete_hanging_nodes (const int &ncont_interpolated_values)
Complete the hanging node scheme recursively.
void complete_hanging_nodes_recursively (Node *&nod_pt, Vector< Node * > &master_nodes, Vector< double > &hang_weights, const int &ival)
Auxiliary routine for recursive hanging node completion.
Protected Attributes inherited from oomph::QuarterTubeMesh< ELEMENT >
QuarterTubeDomain * Domain_pt
Pointer to domain.
GeomObject * Wall_pt
Pointer to the geometric object that represents the curved wall.
Vector< double > Xi_lo
Lower limits for the coordinates along the wall.
double Fract_mid
Fraction along wall where outer ring is to be divided.
Vector< double > Xi_hi
Upper limits for the coordinates along the wall.
Protected Attributes inherited from oomph::Mesh
Vector< Vector< Node * > > Boundary_node_pt
bool Lookup_for_elements_next_boundary_is_setup
Vector< Vector< FiniteElement * > > Boundary_element_pt
Vector< Vector< int > > Face_index_at_boundary
Vector< Node * > Node_pt
Vector of pointers to nodes.
Vector< GeneralisedElement * > Element_pt
Vector of pointers to generalised elements.
std::vector< bool > Boundary_coordinate_exists
Protected Attributes inherited from oomph::TreeBasedRefineableMeshBase
unsigned Uniform_refinement_level_when_pruned
Level to which the mesh was uniformly refined when it was pruned.
unsigned Max_refinement_level
Max. permissible refinement level (relative to base mesh)
unsigned Min_refinement_level
Min. permissible refinement level (relative to base mesh)
unsigned Max_p_refinement_level
Max. permissible p-refinement level (relative to base mesh)
unsigned Min_p_refinement_level
Min. permissible p-refinement level (relative to base mesh)
TreeForest * Forest_pt
Forest representation of the mesh.
Protected Attributes inherited from oomph::RefineableMeshBase
ErrorEstimator * Spatial_error_estimator_pt
Pointer to spatial error estimator.
double Max_permitted_error
Max. error (i.e. split elements if their error is larger)
double Min_permitted_error
Min. error (i.e. (try to) merge elements if their error is smaller)
double Min_error
Min.actual error.
double Max_error
Max. actual error.
unsigned Nrefined
Stats: Number of elements that were refined.
unsigned Nunrefined
Stats: Number of elements that were unrefined.
bool Adapt_flag
Flag that requests adaptation.
bool P_adapt_flag
Flag that requests p-adaptation.
bool Additional_synchronisation_of_hanging_nodes_not_required
Flag that disables additional synchronisation of hanging nodes.
DocInfo * Doc_info_pt
Pointer to DocInfo.
unsigned Max_keep_unrefined
unsigned Nrefinement_overruled
Protected Attributes inherited from oomph::SpineMesh
Vector< Spine * > Spine_pt
A Spine mesh contains a Vector of pointers to spines.
Constructor & Destructor Documentation
AxialSpineQuarterTubeMesh() [1/2]
template<class ELEMENT , class INTERFACE_ELEMENT > AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::AxialSpineQuarterTubeMesh (GeomObject * wall_pt, const Vector< double > & xi_lo, const double & fract_mid, const Vector< double > & xi_hi, const unsigned & nlayer, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) inline
Constructor.
                                                     :
   QuarterTubeMesh<ELEMENT>(wall_pt,xi_lo,fract_mid,xi_hi,
                            nlayer,time_stepper_pt),
   RefineableQuarterTubeMesh<ELEMENT>(wall_pt,xi_lo,fract_mid,xi_hi,
                                       nlayer,time_stepper_pt),
   SpineMesh()
   {
    //Perform a singleuniform refinement
    this->refine_uniformly();
    this->refine_uniformly();
    unsigned n_layer=4;
    //Now worry about the spines the trick is to loop over each
    //layer in turn. We determine the layer based on the z coordinate
    //of the first node in each element.
    Bulk_element_pt = Element_pt;
    //Loop over all the elements
    unsigned n_element = this->nelement();
    for(unsigned e=0;e<n_element;e++)
     {
      //If the element is on the lowest layer
      if(std::abs(finite_element_pt(e)->node_pt(0)->x(2)) < 1.0e-15)
       {
        //Find the number of 1d nodes
        unsigned n_p = finite_element_pt(e)->nnode_1d();
        //Loop over the lowest layer
        for(unsigned n=0;n<(n_p*n_p);n++)
         {
          //Get pointer to the node
          SpineNode* nod_pt = element_node_pt(e,n);
          //If the node has no spine, create one
          if(nod_pt->spine_pt() == 0)
           {
            //Create a new spine of length 2
            Spine* new_spine_pt = new Spine(2.0);
            //Add it to the mesh
            Spine_pt.push_back(new_spine_pt);
            nod_pt->spine_pt() = new_spine_pt;
            //The fraction is zeo
            nod_pt->fraction() = 0.0;
            //Pointer to the mesh the implements the update
            nod_pt->spine_mesh_pt() = this;
           }
          //Loop up the spine and set the other nodes in the element
          for(unsigned m=1;m<n_p;m++)
           {
            SpineNode* nod2_pt = element_node_pt(e,(n_p*n_p)*m + n);
            nod2_pt->spine_pt() = nod_pt->spine_pt();
            nod2_pt->fraction() = nod2_pt->x(2)/2.0;
            nod2_pt->spine_mesh_pt() = this;
           }
         }
       }
     }
    double layer_width = 2.0/(double)n_layer;
    FiniteElement *interface_element_pt=0;
    //Loop over the remaining layers
    for(unsigned l=1;l<n_layer;l++)
     {
      double boundary = layer_width*l;
      //Treat the second layer
      for(unsigned e=0;e<n_element;e++)
       {
        //If the element is on the second layer
        if(std::abs(finite_element_pt(e)->node_pt(0)->x(2)-boundary) < 1.0e-15)
         {
          //If on the last layer
          if(l==n_layer-1)
           {
            //We can build the interface elements at the max
            //of the element (face 3)
            interface_element_pt
             = new INTERFACE_ELEMENT(finite_element_pt(e),3);
            //push it back onto the stack
            Element_pt.push_back(interface_element_pt);
            //Add it to the stack of interface elements
            Interface_element_pt.push_back(interface_element_pt);
           }
          //Find the number of 1d nodes
          unsigned n_p = finite_element_pt(e)->nnode_1d();
          //Loop over the lowest layer
          for(unsigned n=0;n<(n_p*n_p);n++)
           {
            //Get pointer to the spine of the nodes
            Spine* spine_pt = element_node_pt(e,n)->spine_pt();
            //Loop up the spine and set the other nodes in the element
            for(unsigned m=1;m<n_p;m++)
             {
              SpineNode* nod_pt = element_node_pt(e,(n_p*n_p)*m + n);
              nod_pt->spine_pt() = spine_pt;
              nod_pt->fraction() = nod_pt->x(2)/2.0;
              nod_pt->spine_mesh_pt() = this;
             }
           }
          if(l==n_layer-1)
           {
            //Is the interface adjacent to the wall
            unsigned n_p = interface_element_pt->nnode_1d();
            //Which boundary
            std::vector<int> adjacent(4,true);
            for(unsigned n=0;n<n_p;n++)
             {
              //Bottom
              adjacent[0] &=
               interface_element_pt->node_pt(n)->is_on_boundary(3);
              //Right
              adjacent[1] &=
               interface_element_pt->node_pt(n*n_p + n_p-1)->is_on_boundary(3);
              //Top
              adjacent[2] &=
               interface_element_pt->node_pt(n_p*(n_p-1) + n)->is_on_boundary(3);
              //Left
              adjacent[3] &=
               interface_element_pt->node_pt(n*n_p)->is_on_boundary(3);
             }
            //Now if we have a match make the element
            FluidInterfaceBoundingElement* interface_edge_element_pt=0;
            if(adjacent[0])
             {
              interface_edge_element_pt
               = dynamic_cast<INTERFACE_ELEMENT*>(interface_element_pt)
               ->make_bounding_element(-2);
             }
            else if(adjacent[1])
             {
              interface_edge_element_pt
               = dynamic_cast<INTERFACE_ELEMENT*>(interface_element_pt)
               ->make_bounding_element(1);
             }
            else if(adjacent[2])
             {
              interface_edge_element_pt
               = dynamic_cast<INTERFACE_ELEMENT*>(interface_element_pt)
               ->make_bounding_element(2);
            }
           else if(adjacent[3])
            {
             interface_edge_element_pt
              = dynamic_cast<INTERFACE_ELEMENT*>(interface_element_pt)
              ->make_bounding_element(-1);
            }
           if(interface_edge_element_pt!=0)
            {
             Element_pt.push_back(interface_edge_element_pt);
             Interface_edge_element_pt.push_back(interface_edge_element_pt);
             dynamic_cast<FluidInterfaceBoundingElement*>
              (interface_edge_element_pt)->wall_unit_normal_fct_pt()
              = WallFunction::normal;
             //Set the contact angle
             dynamic_cast<FluidInterfaceBoundingElement*>
              (interface_edge_element_pt)->
              set_contact_angle(&Global_Physical_Variables::Angle);
             //and pass the capillary number
             dynamic_cast<FluidInterfaceBoundingElement*>
              (interface_edge_element_pt)->ca_pt() =
              &Global_Physical_Variables::Ca;
            }
           } //End of final layer stuff
         }
       }
     }
    /*  //Treat the third layer
    for(unsigned e=0;e<n_element;e++)
     {
      //If the element is on the third layer
      if(std::abs(finite_element_pt(e)->node_pt(0)->x(2)-1.0) < 1.0e-15)
       {
        //Find the number of 1d nodes
        unsigned n_p = finite_element_pt(e)->nnode_1d();
        //Loop over the lowest layer
        for(unsigned n=0;n<(n_p*n_p);n++)
         {
          //Get pointer to the spine of the nodes
          Spine* spine_pt = element_node_pt(e,n)->spine_pt();
          //Loop up the spine and set the other nodes in the element
          for(unsigned m=1;m<n_p;m++)
           {
            SpineNode* nod_pt = element_node_pt(e,(n_p*n_p)*m + n);
            nod_pt->spine_pt() = spine_pt;
            nod_pt->fraction() = nod_pt->x(2)/2.0;
            nod_pt->spine_mesh_pt() = this;
           }
         }
       }
       }*/
    /*  //Treat the final layer
    for(unsigned e=0;e<n_element;e++)
     {
      //If the element is on the fourth layer
      if(std::abs(finite_element_pt(e)->node_pt(0)->x(2)-1.5) < 1.0e-15)
       {
        //We can build the interface elements at the max
        //of the element
        FiniteElement *interface_element_pt
         = new INTERFACE_ELEMENT(finite_element_pt(e),2,1);
        //push it back onto the stack
        Element_pt.push_back(interface_element_pt);
        //Add it to the stack of interface elements
        Interface_element_pt.push_back(interface_element_pt);
        //Find the number of 1d nodes
        unsigned n_p = finite_element_pt(e)->nnode_1d();
        //Loop over the lowest layer
        for(unsigned n=0;n<(n_p*n_p);n++)
         {
          //Get pointer to the spine of the nodes
          Spine* spine_pt = element_node_pt(e,n)->spine_pt();
          //Loop up the spine and set the other nodes in the element
          for(unsigned m=1;m<n_p;m++)
           {
            SpineNode* nod_pt = element_node_pt(e,(n_p*n_p)*m + n);
            nod_pt->spine_pt() = spine_pt;
            nod_pt->fraction() = nod_pt->x(2)/2.0;
            nod_pt->spine_mesh_pt() = this;
           }
         }
       }
       } */
   }
References abs(), Global_Physical_Variables::Angle, Global_Physical_Variables::Ca, e(), oomph::SpineNode::fraction(), oomph::Node::is_on_boundary(), m, n, oomph::FiniteElement::nnode_1d(), oomph::FiniteElement::node_pt(), WallFunction::normal(), oomph::SpineNode::spine_mesh_pt(), oomph::SpineNode::spine_pt(), plotDoE::x, and oomph::Node::x().
AxialSpineQuarterTubeMesh() [2/2]
template<class ELEMENT , class INTERFACE_ELEMENT > AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::AxialSpineQuarterTubeMesh (GeomObject * wall_pt, const Vector< double > & xi_lo, const double & fract_mid, const Vector< double > & xi_hi, const unsigned & nlayer, TimeStepper * time_stepper_pt = &Mesh::Default_TimeStepper) inline
Constructor.
                                                     :
   QuarterTubeMesh<ELEMENT>(wall_pt,xi_lo,fract_mid,xi_hi,
                            nlayer,time_stepper_pt),
   RefineableQuarterTubeMesh<ELEMENT>(wall_pt,xi_lo,fract_mid,xi_hi,
                                       nlayer,time_stepper_pt),
   SpineMesh()
   {
    //Perform a singleuniform refinement
    this->refine_uniformly();
    //this->refine_uniformly();
    //There are actually four layers
    unsigned n_layer=2;
    //Now worry about the spines the trick is to loop over each
    //layer in turn. We determine the layer based on the z coordinate
    //of the first node in each element.
    Bulk_element_pt = Element_pt;
    //Loop over all the elements
    unsigned n_element = this->nelement();
    for(unsigned e=0;e<n_element;e++)
     {
      //If the element is on the lowest layer
      if(std::abs(finite_element_pt(e)->node_pt(0)->x(2)) < 1.0e-15)
       {
        //Find the number of 1d nodes
        unsigned n_p = finite_element_pt(e)->nnode_1d();
        //Loop over the lowest layer
        for(unsigned n=0;n<(n_p*n_p);n++)
         {
          //Get pointer to the node
          SpineNode* nod_pt = element_node_pt(e,n);
          //If the node has no spine, create one
          if(nod_pt->spine_pt() == 0)
           {
            //Create a new spine of length 1
            Spine* new_spine_pt = new Spine(1.0);
            //Add it to the mesh
            Spine_pt.push_back(new_spine_pt);
            nod_pt->spine_pt() = new_spine_pt;
            //The fraction is zeo
            nod_pt->fraction() = 0.0;
            //Pointer to the mesh the implements the update
            nod_pt->spine_mesh_pt() = this;
           }
          //Loop up the spine and set the other nodes in the element
          for(unsigned m=1;m<n_p;m++)
           {
            SpineNode* nod2_pt = element_node_pt(e,(n_p*n_p)*m + n);
            nod2_pt->spine_pt() = nod_pt->spine_pt();
            nod2_pt->fraction() = nod2_pt->x(2);
            nod2_pt->spine_mesh_pt() = this;
           }
         }
       }
     }
    double layer_width = 1.0/(double)n_layer;
    FiniteElement *interface_element_pt=0;
    //Loop over the remaining layers
    for(unsigned l=1;l<n_layer;l++)
     {
      double boundary = layer_width*l;
      //Treat the second layer
      for(unsigned e=0;e<n_element;e++)
       {
        //If the element is on the second layer
        if(std::abs(finite_element_pt(e)->node_pt(0)->x(2)-boundary) < 1.0e-15)
         {
          //If on the last layer
          if(l==n_layer-1)
           {
            //We can build the interface elements at the max
            //of the element (face 3)
            interface_element_pt
             = new INTERFACE_ELEMENT(finite_element_pt(e),3);
            //push it back onto the stack
            Element_pt.push_back(interface_element_pt);
            //Add it to the stack of interface elements
            Interface_element_pt.push_back(interface_element_pt);
           }
          //Find the number of 1d nodes
          unsigned n_p = finite_element_pt(e)->nnode_1d();
          //Loop over the lowest layer
          for(unsigned n=0;n<(n_p*n_p);n++)
           {
            //Get pointer to the spine of the nodes
            Spine* spine_pt = element_node_pt(e,n)->spine_pt();
            //Loop up the spine and set the other nodes in the element
            for(unsigned m=1;m<n_p;m++)
             {
              SpineNode* nod_pt = element_node_pt(e,(n_p*n_p)*m + n);
              nod_pt->spine_pt() = spine_pt;
              nod_pt->fraction() = nod_pt->x(2);
              nod_pt->spine_mesh_pt() = this;
             }
           }
          if(l==n_layer-1)
           {
            //Is the interface adjacent to the wall
            unsigned n_p = interface_element_pt->nnode_1d();
            //Which boundary
            std::vector<int> adjacent(4,true);
            for(unsigned n=0;n<n_p;n++)
             {
              //Bottom
              adjacent[0] &=
               interface_element_pt->node_pt(n)->is_on_boundary(3);
              //Right
              adjacent[1] &=
               interface_element_pt->node_pt(n*n_p + n_p-1)->is_on_boundary(3);
              //Top
              adjacent[2] &=
               interface_element_pt->node_pt(n_p*(n_p-1) + n)->is_on_boundary(3);
              //Left
              adjacent[3] &=
               interface_element_pt->node_pt(n*n_p)->is_on_boundary(3);
             }
            //Now if we have a match make the element
            FluidInterfaceBoundingElement* interface_edge_element_pt=0;
            if(adjacent[0])
             {
              interface_edge_element_pt
               = dynamic_cast<INTERFACE_ELEMENT*>(interface_element_pt)
               ->make_bounding_element(-2);
             }
            else if(adjacent[1])
             {
              interface_edge_element_pt
               = dynamic_cast<INTERFACE_ELEMENT*>(interface_element_pt)
               ->make_bounding_element(1);
             }
            else if(adjacent[2])
             {
              interface_edge_element_pt
               = dynamic_cast<INTERFACE_ELEMENT*>(interface_element_pt)
               ->make_bounding_element(2);
            }
           else if(adjacent[3])
            {
             interface_edge_element_pt
              = dynamic_cast<INTERFACE_ELEMENT*>(interface_element_pt)
              ->make_bounding_element(-1);
            }
           if(interface_edge_element_pt!=0)
            {
             Element_pt.push_back(interface_edge_element_pt);
             Interface_edge_element_pt.push_back(interface_edge_element_pt);
             dynamic_cast<FluidInterfaceBoundingElement*>
              (interface_edge_element_pt)->wall_unit_normal_fct_pt()
              = WallFunction::normal;
             //Set the contact angle
             dynamic_cast<FluidInterfaceBoundingElement*>
              (interface_edge_element_pt)->
              set_contact_angle(&Global_Physical_Variables::Angle);
             //Set the capillary number
             dynamic_cast<FluidInterfaceBoundingElement*>
              (interface_edge_element_pt)->
              ca_pt()=&Global_Physical_Variables::Ca;
            }
           } //End of final layer stuff
         }
       }
     }
   }
References abs(), Global_Physical_Variables::Angle, Global_Physical_Variables::Ca, e(), oomph::SpineNode::fraction(), oomph::Node::is_on_boundary(), m, n, oomph::FiniteElement::nnode_1d(), oomph::FiniteElement::node_pt(), WallFunction::normal(), oomph::SpineNode::spine_mesh_pt(), oomph::SpineNode::spine_pt(), plotDoE::x, and oomph::Node::x().
Member Function Documentation
bulk_element_pt() [1/4]
template<class ELEMENT , class INTERFACE_ELEMENT > Vector<GeneralisedElement*>& AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::bulk_element_pt () inline
   {return Bulk_element_pt;}
Referenced by FreeSurfaceRotationProblem< ELEMENT >::FreeSurfaceRotationProblem().
bulk_element_pt() [2/4]
template<class ELEMENT , class INTERFACE_ELEMENT > Vector<GeneralisedElement*>& AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::bulk_element_pt () inline
   {return Bulk_element_pt;}
bulk_element_pt() [3/4]
template<class ELEMENT , class INTERFACE_ELEMENT > GeneralisedElement* & AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::bulk_element_pt (const unsigned long & i) inline
Access functions for pointers to elements in bulk.
   {return Bulk_element_pt[i];}
References i.
bulk_element_pt() [4/4]
template<class ELEMENT , class INTERFACE_ELEMENT > GeneralisedElement* & AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::bulk_element_pt (const unsigned long & i) inline
Access functions for pointers to elements in bulk.
   {return Bulk_element_pt[i];}
References i.
interface_edge_element_pt() [1/2]
template<class ELEMENT , class INTERFACE_ELEMENT > FiniteElement* & AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::interface_edge_element_pt (const unsigned long & i) inline
Access functions for pointers to interface elements.
   {return Interface_edge_element_pt[i];}
References i.
interface_edge_element_pt() [2/2]
template<class ELEMENT , class INTERFACE_ELEMENT > FiniteElement* & AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::interface_edge_element_pt (const unsigned long & i) inline
Access functions for pointers to interface elements.
   {return Interface_edge_element_pt[i];}
References i.
interface_element_pt() [1/2]
template<class ELEMENT , class INTERFACE_ELEMENT > FiniteElement* & AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::interface_element_pt (const unsigned long & i) inline
Access functions for pointers to interface elements.
   {return Interface_element_pt[i];}
References i.
Referenced by FreeSurfaceRotationProblem< ELEMENT >::FreeSurfaceRotationProblem().
interface_element_pt() [2/2]
template<class ELEMENT , class INTERFACE_ELEMENT > FiniteElement* & AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::interface_element_pt (const unsigned long & i) inline
Access functions for pointers to interface elements.
   {return Interface_element_pt[i];}
References i.
nbulk() [1/2]
template<class ELEMENT , class INTERFACE_ELEMENT > unsigned long AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::nbulk () const inline
Number of elements in bulk.
 {return Bulk_element_pt.size();}
Referenced by FreeSurfaceRotationProblem< ELEMENT >::FreeSurfaceRotationProblem().
nbulk() [2/2]
template<class ELEMENT , class INTERFACE_ELEMENT > unsigned long AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::nbulk () const inline
Number of elements in bulk.
 {return Bulk_element_pt.size();}
ninterface_edge_element() [1/2]
template<class ELEMENT , class INTERFACE_ELEMENT > unsigned long AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::ninterface_edge_element () const inline
Number of elements on interface.
   {return Interface_edge_element_pt.size();}
ninterface_edge_element() [2/2]
template<class ELEMENT , class INTERFACE_ELEMENT > unsigned long AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::ninterface_edge_element () const inline
Number of elements on interface.
   {return Interface_edge_element_pt.size();}
ninterface_element() [1/2]
template<class ELEMENT , class INTERFACE_ELEMENT > unsigned long AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::ninterface_element () const inline
Number of elements on interface.
 {return Interface_element_pt.size();}
Referenced by FreeSurfaceRotationProblem< ELEMENT >::FreeSurfaceRotationProblem().
ninterface_element() [2/2]
template<class ELEMENT , class INTERFACE_ELEMENT > unsigned long AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::ninterface_element () const inline
Number of elements on interface.
 {return Interface_element_pt.size();}
spine_node_update() [1/2]
template<class ELEMENT , class INTERFACE_ELEMENT > virtual void AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update (SpineNode * spine_node_pt) inline virtual
Update nodal positions in response to spine changes.
Implements oomph::SpineMesh.
   {
    //Get fraction along the spine
    double W = spine_node_pt->fraction();
    //Get spine height
    double H = spine_node_pt->h();
    //Set the value of z
    spine_node_pt->x(2) = this->Xi_lo[0] + W*H;
   }
References oomph::SpineNode::fraction(), H, oomph::SpineNode::h(), oomph::QuadTreeNames::W, and oomph::Node::x().
spine_node_update() [2/2]
template<class ELEMENT , class INTERFACE_ELEMENT > virtual void AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::spine_node_update (SpineNode * spine_node_pt) inline virtual
Update nodal positions in response to spine changes.
Implements oomph::SpineMesh.
   {
    //Get fraction along the spine
    double W = spine_node_pt->fraction();
    //Get spine height
    double H = spine_node_pt->h();
    //Set the value of z
    spine_node_pt->x(2) = this->Xi_lo[0] + W*H;
   }
References oomph::SpineNode::fraction(), H, oomph::SpineNode::h(), oomph::QuadTreeNames::W, and oomph::Node::x().
Member Data Documentation
Bulk_element_pt
template<class ELEMENT , class INTERFACE_ELEMENT > Vector< GeneralisedElement * > AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::Bulk_element_pt private
Vector of pointers to element in the fluid layer.
Interface_edge_element_pt
template<class ELEMENT , class INTERFACE_ELEMENT > Vector< FiniteElement * > AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::Interface_edge_element_pt private
Vector of pointers to interface elements.
Interface_element_pt
template<class ELEMENT , class INTERFACE_ELEMENT > Vector< FiniteElement * > AxialSpineQuarterTubeMesh< ELEMENT, INTERFACE_ELEMENT >::Interface_element_pt private
Vector of pointers to interface elements.
The documentation for this class was generated from the following files:
free_surface_rotation.cc
3d_static_cap.cc