MercuryDPM: oomph::Euler Class Reference
oomph::Euler Class Reference
#include <explicit_timesteppers.h>
Public Member Functions
Euler ()
Constructor, set the type.
Euler (const Euler &)=delete
Broken copy constructor.
void operator= (const Euler &)=delete
Broken assignment operator.
void timestep (ExplicitTimeSteppableObject *const &object_pt, const double &dt)
Euler timestepping x^{t+1} = x^{t} + dt M^{-1} L(x^{t})
Public Member Functions inherited from oomph::ExplicitTimeStepper
ExplicitTimeStepper ()
Empty Constructor.
ExplicitTimeStepper (const ExplicitTimeStepper &)=delete
Broken copy constructor.
void operator= (const ExplicitTimeStepper &)=delete
Broken assignment operator.
virtual ~ExplicitTimeStepper ()
Empty virtual destructor — no memory is allocated in this class.
Additional Inherited Members
Protected Attributes inherited from oomph::ExplicitTimeStepper
std::string Type
Detailed Description
=========================================================== Simple first-order Euler Timestepping
Constructor & Destructor Documentation
Euler() [1/2]
oomph::Euler::Euler () inline
Constructor, set the type.
     {
       Type = "Euler";
     }
References oomph::ExplicitTimeStepper::Type.
Euler() [2/2]
oomph::Euler::Euler (const Euler &) delete
Broken copy constructor.
Member Function Documentation
operator=()
void oomph::Euler::operator= (const Euler &) delete
Broken assignment operator.
timestep()
void oomph::Euler::timestep (ExplicitTimeSteppableObject *const & object_pt, const double & dt) virtual
Euler timestepping x^{t+1} = x^{t} + dt M^{-1} L(x^{t})
Overload function that is used to advance time in the object reference by object_pt by an amount dt
Implements oomph::ExplicitTimeStepper.
   {
     object_pt->actions_before_explicit_timestep();
     object_pt->actions_before_explicit_stage();
     // Vector that will hold the inverse mass matrix multiplied by the
     // residuals
     DoubleVector minv_res;
     // Get M^{-1} R
     object_pt->get_dvaluesdt(minv_res);
     // Add the result to the unknowns
     object_pt->add_to_dofs(dt, minv_res);
     // Increment the time by the appropriate amount
     object_pt->time() += dt;
     // Call any actions required after the change in the unknowns
     object_pt->actions_after_explicit_stage();
     object_pt->actions_after_explicit_timestep();
   }
References oomph::ExplicitTimeSteppableObject::actions_after_explicit_stage(), oomph::ExplicitTimeSteppableObject::actions_after_explicit_timestep(), oomph::ExplicitTimeSteppableObject::actions_before_explicit_stage(), oomph::ExplicitTimeSteppableObject::actions_before_explicit_timestep(), oomph::ExplicitTimeSteppableObject::add_to_dofs(), oomph::ExplicitTimeSteppableObject::get_dvaluesdt(), and oomph::ExplicitTimeSteppableObject::time().
The documentation for this class was generated from the following files:
explicit_timesteppers.h
explicit_timesteppers.cc