MercuryDPM: MindlinSelfTest.cpp File Reference
MindlinSelfTest.cpp File Reference
#include "Species/HertzianViscoelasticMindlinSpecies.h"
#include "Species/HertzianViscoelasticSlidingFrictionSpecies.h"
#include "DPMBase.h"
#include "ContactLawTestHelpers.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
 {
     Mdouble displacement=0.015;
     Mdouble tangentialDisplacement=0.0025;
     Mdouble velocity=0.01;
     Mdouble radius=0.25;
     //runs a loading - unloading - reloading test for normal and tangential forces, plus tests the objectiveness
     //- for Hertz-Mindlin
     HertzianViscoelasticMindlinSpecies species;
     species.setDensity(6./constants::pi);
     species.setEffectiveElasticModulusAndPoissonRatio(1e5, 0.3);
     species.setDissipation(2.0);
 //  species.setSlidingDissipation(4.0/7.0);
     species.setSlidingFrictionCoefficient(0.1);
     loadingTest(&species, displacement, velocity, radius, "MindlinSelfTestLoading");
     normalAndTangentialLoadingTest(&species, displacement, tangentialDisplacement, velocity, radius,
                                             "MindlinSelfTestNormalAndTangentialLoading");
     objectivenessTest(&species, displacement, tangentialDisplacement, velocity, radius, "MindlinSelfTestFrameIndependence");
     /*
      * //- for Hertz-SlidingFriction
     HertzianViscoelasticSlidingFrictionSpecies species2;
     species2.setDensity(6./constants::pi);
     species2.setEffectiveElasticModulus(1e5);
     species2.setDissipation(2.0);
     species2.setSlidingStiffness(300.0);
     species2.setSlidingFrictionCoefficient(1.0);
 */
     //Note: for correct signs, plot:
     //"MindlinSelfTestTangentialLoading.fstat" using 8:($10*$14)
     //loadingTest(&species2, displacement, velocity, radius);
     //normalAndTangentialLoadingTest(&species2, displacement, tangentialDisplacement, velocity, radius);
     //objectivenessTest(&species2, displacement, tangentialDisplacement, velocity, radius);
 }
References loadingTest(), normalAndTangentialLoadingTest(), objectivenessTest(), constants::pi, UniformPSDSelfTest::radius, ParticleSpecies::setDensity(), and Jeffery_Solution::velocity().